### PR TITLE
Repathed the floors of the rest of the station maps.

### PR DESCRIPTION
**Pull request by xxalpha**
Repathed the floors of Asteroid station, Bird station, Dream station, Efficiency station and Ministation to use the proper floor types instead of var edited icon states.

Added one airless type:
 - /turf/open/floor/plating/airless/warnplate/corner

Asteroid was fully converted to TGM, hence the many line additions.

### CODE REVIEW

**Comment by coiax** [comment]
I've been unable to make any changes to asteroidstation without it crashing DM.

**Comment by pudl** [comment]
ABSOLUTE SHIT

**Comment by ike709** [comment]
why exactly does it matter?

**Comment by pudl** [comment]
IT DOESNT

**Comment by Jalleo** [comment]
Standardisation matters a lot. Makes things easier to maintain.

**Comment by pudl** [comment]
NOTHING ABOUT THIS MAKES ANYTHING EASIER TO MAINTAIN

**Comment by xxalpha** [comment]
Stop.

**Comment by optimumtact** [comment]
xxalpha buffing their own line count I see

**Pull request merged**
