### PR TITLE
Gives krav maga gloves to the HoS

### PR DESCRIPTION
**Pull request by PKPenguin321**
Part of 3 PRs intended mainly for test merging (and possibly eventually actually merging if the test goes well) that have to do with giving sec krav maga

[Check out the krav maga for sec poll on the forums right here.](https://tgstation13.science/phpBB/viewtopic.php?f=10&t=6466)

Check out https://github.com/tgstation/-tg-station/pull/17046 and https://github.com/tgstation/-tg-station/pull/17044 for the 2 sister PRs

:cl: PKPenguin321
rscadd: The HoS now starts the round with krav maga gloves.
/:cl:

### CODE REVIEW

**Comment by Man-Shroom-** [comment]
for posterity

only if stungloves are re-added

stungloves would obviously be nerfed in the following ways

1. Only one charge
2. Don't stun for a silly amount of time
3. Very obvious sprites

**Comment by Core0verload** [comment]
The warden gloves one is the best option. HoS already has a lot of unique gear.

**Comment by Fox-McCloud** [comment]
>only if stungloves are re-added

There's a difference between stun gloves (which could literally be anyone) and gloves that you can reasonably expect a particular job to have.

**Comment by xxalpha** [comment]
I have no problem with this item, but I think security doesn't need more shit.

Give it to ERT, Syndicates and one in the vault safe.

**Comment by Robustin** [comment]
Sure, as a test, but between this and wrestling belt I'm already kind of worn out of needing to learn all the special noises and gimmicks that the martials arts can do now. Going to be even more annoying when a traitor or ling gets them and starts running around beating people to death with a bunch of weird THWACKS that the victims don't understand. I made sleeping carp 20TC not because of the ranged immunity, even the CMO has an edge over a sleeping meme 1v1 in melee, but because of how powerful it is to be able to reliably kill people with your bare hands.

Also I can almost guarantee this is going to have some screwed up interactions with sleeping carp.

**Comment by PKPenguin321** [comment]
Nah, all implementations of krav are temporary, temp martial art datums automatically override permanent ones like sleeping carp and fix themselves when krav is removed

**Comment by KorPhaeron** [comment]
HoS already has plenty of cool loot

**Pull request closed without merging**
