### PR TITLE
Adds 2 new Detective outfits to the Detective Autodrobe.

### PR DESCRIPTION
**Pull request by Iamgoofball**
## About The Pull Request

Adds two new detective outfits to the game.
dreamseeker_G53HZwuBPE
dreamseeker_JO9ciQyf8c
dreamseeker_UWBren12fZ
dreamseeker_CJ8EJmaeD1

https://github.com/Skyrat-SS13/Skyrat-tg/pull/4779
## Why It's Good For The Game

These are classic detective outfits from Disco Elysium, incredibly recognizable, and the sprites are great. Detectives will love these costumes!

## Changelog
:cl: Iamgoofball, borrowed from Surrealaser from fulpstation, spriter d4n0w4r 
imageadd: Adds two new outfits to the Detective's autodrobe.
/:cl:

### CODE REVIEW

**Comment by necromanceranne** [comment]
It's tragic we no longer have the smile mutation, because damn would that be appropriate right now.

**Comment by Iamgoofball** [comment]
Linked the original PR. The skyrat PR didn't actually fully implement the outfits so I had to implement the glasses, shoes, and gloves.

**Comment by RaveRadbury** [comment]
Honestly the warden could probably use someone to talk to. It can get lonely in the brig.

**Comment by MMMiracles** [comment]
this is very disco

**Comment by necromanceranne** [comment]
> Linked the original PR. 

Oops, sorry if that was there already, was a little buried at the bottom there.

**Comment by Iamgoofball** [comment]
@RaveRadbury He has the prisoners for that

**Comment by newfren** [comment]
yesssss

**Comment by notfrying1pans** [comment]
image

**Comment by thestubborn** [comment]
> 
> 
> Linked the original PR. The skyrat PR didn't actually fully implement the outfits so I had to implement the glasses, shoes, and gloves.

i did, I just forgot and done it in another pr lul

**Comment by AndroidMK2** [comment]
Detective drip acquired.

**Comment by Mothblocks** [comment]
> These are classic detective outfits

just say its from disco elysium

**Comment by Helianthus00** [comment]
I'd appreciate if the original coder, Surrealaser, was credited for this. This is originally a port from the old Fulpstation repo, which Skyrat failed to credit. Here is the PR. Sprites are the exact same. Thank you for crediting the original spriter. https://github.com/TheSwain/Fulpstation/pull/306

**Comment by Bawhoppen** [comment]
Huh I didn't know D4n0w4r was still around. Neat.

**Comment by Iamgoofball** [comment]
@Helianthus00 Will do, thanks!

**Review by Twaticus — CHANGES_REQUESTED** [review]
icons/mob/clothing/under/security.dmi - jamrock_suit & aerostatic_suit need the hand/arm areas filled in
otherwise it all look gud

**Comment by tralezab** [comment]
solve review + conflicts and undraft when ready

**Pull request closed without merging**
