### PR TITLE
RPD auto wrench

### PR DESCRIPTION
**Pull request by Dennok**
:cl:
add: RPD automaticaly wrench printed pipes to floor.
add: RPD eat pipe mode can unwrench pipe and eat.
code: pipe deconstruct changed to return created pipe.
add: Meters can be attached to the floor by screwdriver
/:cl:

[why]: i like pipes.
helps build with wind and singulo pulls,
removes the need for pipe pixel hunting.

ezgif com-video-to-gif
ezgif com-video-to-gif 1
ezgif com-video-to-gif 2
ezgif com-video-to-gif 3

### CODE REVIEW

**Comment by praisenarsie** [comment]
you just made a new branch ontop of your other branch

**Comment by ExcessiveUseOfCobblestone** [comment]
does this work?

**Comment by Dennok** [comment]
a make 2 branches, and pull one commit from one to another.

I test it on 511 and dont find bugs ir rruntimes.

**Comment by ExcessiveUseOfCobblestone** [comment]
it's not instant right?

**Comment by Dennok** [comment]
What instant ?

**Comment by optimumtact** [comment]
buff disguised as QoL change

**Comment by ExcessiveUseOfCobblestone** [comment]
> it's instant

no no no no no no no no

also no rationale please close!!!!

**Comment by DaedalusGame** [comment]
>helps build with wind and singulo pulls
>>no rationale
>no to near instant

this really made me think

**Comment by cacogen** [comment]
ill fite u #36354

I like this but it might be too OP. I dunno. Disposals traps (and infinite disposal loops) are already pretty powerful.

**Comment by 81Denton** [comment]
>also no rationale please close!!!!
>>helps build with wind and singulo pulls

🤔

**Comment by Spaceinaba** [comment]
dude lmao wrenching them down is instant just get good

**Comment by ExcessiveUseOfCobblestone** [comment]
@81Denton @DaedalusGame do you guys know how to check PR body edits or is it easier to hop on a bandwagon?

**Comment by Dennok** [comment]
@cacogen disposals still need to be welded,

**Comment by ExcessiveUseOfCobblestone** [comment]
From Steel to MrDoom to Dennok, when will the alts end?!!!

**Comment by duncathan** [comment]
Your branch is a mess and you're doing too much in here. I'm ok with *one* part of this PR. If you make a new PR, on a FRESH branch, that auto-wrenches placed atmos pipes (not disposals or transit tubes) then I'll be willing to merge that.

**Comment by DaedalusGame** [comment]
go home minecraft girl

**Comment by ExcessiveUseOfCobblestone** [comment]
careful or ill eat your fruitloops toucan

**Pull request closed without merging**
