### PR TITLE
Fixes tram consoles getting depowered incorrectly

### PR DESCRIPTION
**Pull request by Kylerace**
## About The Pull Request
thanks to fikou for reporting this
tram consoles had an issue where if they left an area with power, went through an area without power, then another area with power, and then returned to the first area with power, they would become unpowered, like so:

powered area A -> depowered area  B -> powerered area C
A                      <- B                            <-  C
console is depowered when it returns to A from B

whats actually happening is that the tram assumes that the area at its lower left corner is the area of all of its contents, so when the tram goes from a depowered area to a powered area, it will call depowered_area.Exit() and powered_area.Enter() for each of its contents, but since the tram console is still in a depowered area, any get_area() calls returns the depowered area since its still there

so now we just check each contents areas individually. its slower (looping through contents in group_move() already took about 3/8ths of the time as the entire proc, so this isnt trivial) but its correct

also makes a few list vars on /industrial_lift true lists instead of lazylists because there wasnt actually a need to do that.

## Why It's Good For The Game
fix

## Changelog

:cl:
fix: tram consoles will no longer randomly depower if they return from an area without power
/:cl:

### CODE REVIEW

**Comment by lessthnthree** [comment]
Do tram consoles still stay powered when they come from a powered area and arrive in an unpowered area?

**Comment by Kylerace** [comment]
> Do tram consoles still stay powered when they come from a powered area and arrive in an unpowered area?

@lessthnthree 
they will depower for the duration that they stay within a depowered area and gain power when they move into a powered area. not hard to "fix" but considering you cant do anything with a tram console while its moving theres no point.

**Comment by Kylerace** [comment]
oh you mean when they stay within a depowered area but one of their destinations is still powered. yeah theyll depower in that case, probably shouldnt though and its not that hard to change

**Comment by lessthnthree** [comment]
> 

Current issue: 
-Tram gets called to unpowered area.
-Tram call buttons are correctly disabled in the area due to lack of power
-Tram controls still work to move it
-Tram can also still be called using buttons on other parts of the station, when it should technically be broken and have no power

**Pull request merged**
