### PR TITLE
*PROBABLY BROKEN* Heads get a mini egun on lowpop

### PR DESCRIPTION
**Pull request by Tacolizard**
:cl:
experiment: On server populations lower than 40, Heads spawn with mini E-Guns for self defense
/:cl:

so this feature was originally planned but was forgotten after mini eguns got initially merged.

this code is probably broken.

problems that might break this:

1. i know nothing of DM syntax
2. I don't know if the function i used for checking playercount works
3. memes

### CODE REVIEW

**Comment by Iamgoofball** [comment]
did you even test this

**Comment by Tacolizard** [comment]
@Iamgoofball of course not who do you think i am

**Comment by Tacolizard** [comment]
@Iamgoofball i usually make my prs from a mac and do damage control when i get home

**Comment by duncathan** [comment]
in what world is 40 players "low" pop

**Pull request closed without merging**
