### PR TITLE
Quantum Pads can now be Renamed

### PR DESCRIPTION
**Pull request by ExcessiveUseOfCobblestone**
:cl: Cobby
:tweak: Allows Quantum Pads to be renamed. Trust these as much as you trust the "try jumping" messages on Dark Souls.
/:cl:

This allows for quick [re]labeling of Quantum pads and was the purpose of setting `unique_rename` to /obj/.

As alluded to in the CL, feel free to use this maliciously as antag ;-)

### CODE REVIEW

**Comment by MMMiracles** [comment]
rest in peace labelers

**Comment by ExcessiveUseOfCobblestone** [comment]
I've considered replacing the pen with the hand labeler and just edit the hand labeler.

**Comment by FantasticFwoosh** [comment]
Mmm ["Power consuming ladder"]

Thats pretty much what it is.

**Comment by ExcessiveUseOfCobblestone** [comment]
name: "Leads to FUN!" 
description: Hop on for a fun time!

*sends to lava deathtrap*

**Pull request merged**
