### PR TITLE
Adds enviroskirts and durathread skirts

### PR DESCRIPTION
**Pull request by carlarctg**
## About The Pull Request
Adds enviroskirts and durathread skirts. The enviroskirts aren't exposed to the environment, they have plastic tubing on the legs.

## Why It's Good For The Game
Fashion is crew content right??

## Changelog
:cl:
add: Plasmamen can now wear enviroskirts!
add: Durathread skirts added too.
/:cl:

### CODE REVIEW

**Comment by Fikou** [comment]
why

**Comment by carlarctg** [comment]
> why

Scared?

**Comment by CRITAWAKETS** [comment]
Do you think God stays in heaven because he too lives in fear of what he's created?

**Comment by carlarctg** [comment]
sprites courtesy of kryson: 
image

**Comment by carlarctg** [comment]
just kidding this is the real sprite base for everything
image

**Comment by 81Denton** [comment]
We have this race of aliens that wear heavy envirosuits because they horribly combust on contact with oxygen and now they wear skirts? With plastic tubing on their legs? Suspension of disbelief only goes that far.

**Comment by Kraseo** [comment]
they used to be actual exosuits but it turns out plasmamen having space-proof shit from the get-go was bad

**Comment by PKPenguin321** [comment]
they are purple skeletons

**Comment by Mickyan** [comment]
I was already mildly annoyed by the implication of engineers using skirts as work outfits but this is jumping the shark

**Comment by kriskog** [comment]
Hardskirts next :tada:

**Comment by Shadowflame909** [comment]
add durathread cat-ears and envirocat-ears please

**Comment by wesoda25** [comment]
Plasmamen should be genderless imo

**Comment by cacogen** [comment]
idc lol

**Comment by wesoda25** [comment]
Allow me to rephrase that. Introducing gender content to a race of skeletons is stupid and snowflakey. Para is next door.

**Comment by carlarctg** [comment]
wow you inmediately jump to thinking skirts are girl-only???

that's pretty gender-binaryist dude, what about the scottish
what if i want to rp as a scottish fire skeleton??
what if i just want to wear a skirt
your problematic arguments are sickening

**Comment by PKPenguin321** [comment]
Was gonna say that this goes against the general theme of plasma men being horrible beyond-death monstrosities, but then I realized they kind of lack an established theme. We should make plasmamen always end sentences with a period with a speech filter, like how lizards drag their "s" sounds. Exclamation points and question marks would be changed to just a period. They would come off as emotionless and practically robotic. It would be cool and give them a sort of theme

**Comment by 81Denton** [comment]
Let's not

**Comment by nemvar** [comment]
Sad

**Comment by Twaticus** [comment]
sad

**Comment by kriskog** [comment]
Sad

**Comment by Shadowflame909** [comment]
Happy

**Comment by tmtmtl30** [comment]
im fuming

**Pull request closed without merging**
