### PR TITLE
Anatomic Panacea now imparts neurine in addition to other chemicals.

### PR DESCRIPTION
**Pull request by Eaglendia**
## About The Pull Request

Anatomic Panacea now adds neurine in addition to other chemicals, allowing Changelings to cure minor brain traumas with their own abilities. Recovering from traumas with neurine is still RNG-based; the amount chosen is because six units of neurine is the smallest whole number value that affords a >90% chance of curing a minor trauma.

## Why It's Good For The Game

While Anatomic Panacea is able to heal brain damage from the user, balance changes to changeling abilities are dated and not cognizant of the divide between brain damage and brain traumas. Changelings are meant to be masters of biology, and their brain is vestigial anyway, so it makes no sense that some drugs, a random event, or a really good bonk on the head can permanently inhibit their bodily function.

This change is meant to be more of a quality-of-life and sanity (the ability says it fixes all of my problems, why doesn't it fix my brain?) patch than one that will significantly change interaction balance. As such, major brain traumas are not cured and changelings are still able to be brainwashed via surgery.

## Changelog
:cl:
balance: Changelings can now cure minor brain traumas with Anatomic Panacea.
/:cl:

### CODE REVIEW

**Comment by Angustmeta** [comment]
Too little considering they're also injected with pentetic acid, which purges other chems 2u per tick.

**Comment by Angustmeta** [comment]
The pentetic acid purges 2u per tick, so six units will probably only tick 3 times.

**Comment by Eaglendia** [comment]
Heck, you're right. I didn't even think about that. Do the other chem amounts even take that into consideration?

**Comment by Angustmeta** [comment]
I have no idea. They're like in-between bad and okish. 

- Mutadone doesn't matter since it's instant. 
- Antihol at 10u has time to reduce some drunkenness, but not much. 
- 25u mannitol will heal like 35 brain damage if I count right. Kinda weak but still kinda helps.

**Comment by Eaglendia** [comment]
This probably demands a higher-effort change, then, and I'd also like to talk to someone re: balance where Changelings and major traumas/brainwashing stand.

**Pull request closed without merging**
