### PR TITLE
Adds tables near produce consoles

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request

Adds tables near produce consoles

## Why It's Good For The Game

This is for mitigating the contamination mechanic introduced in https://github.com/tgstation/tgstation/pull/76018 . Ideally the consoles would auto target the table too but... one bridge at a time.

## Changelog

:cl:
qol: Produce consoles now have tables near them.
/:cl:

### CODE REVIEW

**Comment by MrMelbert** [comment]
Perhaps the produce should ship in a box? Seems a little cluttered, especially the one on Deltastation, which is covering a vent

**Comment by YehnBeep** [comment]
...That would be pretty huge QoL besides, now that you mention it. Let me see if I can figure out how to do that.

**Comment by YehnBeep** [comment]
Well, this is a bit of a dilemma for me. On the one hand I feel like the box is the much better solution - aside from preventing contamination, it'd also save chefs from doing laps between the console and kitchen. And using a table is just really awkward. But on the other, it seems I really was not born to be a coder; I can't make heads or tails of that side of things.

**Comment by YehnBeep** [comment]
Hm, well. Boxing would be much better I think, even for non-express orders in case the cargo tech accidentally opens the crate, but - this is what I can do for now, and even if awkward, I think a table is better than nothing.

**Review by Maurukas — APPROVED** [review]

**Pull request merged**
