### PR TITLE
buffs fridges

### PR DESCRIPTION
**Pull request by PKPenguin321**
https://www.youtube.com/watch?v=Arib8uWMWsM

### CODE REVIEW

**Comment by KorPhaeron** [comment]
Here is the problem

>stand inside fridge
>detonate maxcaps
>walk out unharmed

**Comment by Zilenan91** [comment]
Yeah this could be a problem. Perhaps make it so only anchored fridges can resist explosions.

**Comment by PKPenguin321** [comment]
it's a meme pr for a reason

**Comment by KazeEspada** [comment]
Make the fridge survive and make it do brute damage for every space it flew.

**Comment by PKPenguin321** [comment]
>asking me to do actual effort

ehhh joke's over

**Pull request closed without merging**
