### PR TITLE
Reverts shoe change and readds old shoe sprites

### PR DESCRIPTION
**Pull request by anconfuzedrock**
:cl:
imageadd: Old shoe object sprites
/:cl:
image

### CODE REVIEW

**Comment by wesoda25** [comment]
Why do we add new sprites even if they look like shit

**Comment by nicbn** [comment]
The RiDE NevEr EnDS

**Comment by HomocidlePancakes** [comment]
Keep the jumpsuit sprite though. That one was actually good.

**Comment by VileBeggar** [comment]
> 
> 
> Keep the jumpboots sprite though. That one was actually good.

if you're going to remove them, remove all of them, mismatching sprites is terrible

**Comment by MrDoomBringer** [comment]
massively based pr

**Comment by Farquaar** [comment]
I like the new sprites better than the old sprites

**Comment by subject217** [comment]
SOUL VS SOULLESS

**Comment by optimumtact** [comment]
I intend to merge this, I don't think the new shoe sprites looked good and they had the wrong perspective

**Comment by anconfuzedrock** [comment]
The design of the new shoes clearly had effort put into them, and they were well designed, but there are many well designed swords that you shouldn't bring to a gunfight. The sprites stick out like a sore thumb when opening any closet. They'd only look less out of place if all sprites were similarly redone so they didn't seem like the largest thing in the closet, and since those weren't done, doing things halfway is worse than not doing them.

**Comment by actioninja** [comment]
RIP
People liked them at first at least.

**Comment by anconfuzedrock** [comment]
PS the clown shoe sprites looked like condoms

**Pull request merged**
