### PR TITLE
Updates security barriers to be wallening'd

### PR DESCRIPTION
**Pull request by YesterdaysPromise**
## About The Pull Request

Brings barriers to 3/4 wallening-appropriate perspective.
Interdyne 1

## Why It's Good For The Game

Brings the sprite to current standards.

## Changelog

:cl:
image: adjusted security barriers to be in 3/4 perspective.
/:cl:

### CODE REVIEW

**Comment by Pepsilawn** [comment]
How does it look pre-deployed?

**Comment by YesterdaysPromise** [comment]
> How does it look pre-deployed?

Uses pre-wallening sprite. Easier to distinguish which one is which now! Didn't see a reason to change it.

**Comment by YesterdaysPromise** [comment]
> How does it look pre-deployed?

image
alright alright

**Comment by SomeoneYouProbablyKnow** [comment]
They look like a little play pen, like i can climb in and there's gonna be a ball pit inside. Love em

**Pull request merged**
