### PR TITLE
Lizard's Gas(LAVALAND EDITION)

### PR DESCRIPTION
**Pull request by EEASAS**
## About The Pull Request
Adds a new lavaland ruin from the Lizard's Gas franchise
image
## Why It's Good For The Game
Lore and also more ruin is good
## Changelog
:cl:
add: New Lizard's Gas ruin, this time in lavaland
/:cl:

### CODE REVIEW

**Review by L0pz — APPROVED** [review]

**Comment by nianjiilical** [comment]
i appreciate the implication that someone built a presumably functional gasoline station five yards from an active pool of literal magma at one point

**Review by Maurukas — CHANGES_REQUESTED** [review]
Weirdly rotated air alarm here:
image
May want a light in the airlock:
image

Otherwise looks good.

**Comment by EEASAS** [comment]
what exactly do you mean weirdly rotated air alarm?

**Review by Maurukas — APPROVED** [review]
Disregard the air alarm, I am not up to date. Presuming it's some Wallening stuff creeping in.

**Pull request merged**
