### PR TITLE
Adds the ore satchel of holding

### PR DESCRIPTION
**Pull request by ghost**
holding
Adds the ore satchel of holding to R&D. Requiring bluespace 3 and materials 4 research, it is relatively cheap and can hold an infinite amount of ores. Sprites made by me.

This has been a very requested feature, and it's far easier than lugging around an ore crate, but still requires at least some effort (diamonds, uranium, and gold are all fairly rare, and the research is somewhat difficult).

### CODE REVIEW

**Comment by Iamgoofball** [comment]
:+1:

**Comment by Xhuis** [comment]
Crap forgot the changelog, will do that now

**Comment by Lumipharon** [comment]
Now that accelerators are mlgpr0 no scoping super sanic AOE mining kill sticks, it's good that R&D can still offer them something useful.

**Comment by Iamgoofball** [comment]
accelerator nerfs someday

**Comment by hornygranny** [comment]
remarkably good idea

**Comment by TheVekter** [comment]
50000000000/10.

**Comment by Mandurrrh** [comment]
:+1: yes please.

**Comment by GunHog** [comment]
That was MY idea! :+1:

**Comment by Miauw62** [comment]
:+1:

**Comment by Xhuis** [comment]
Removed diamond cost + squashed commits

**Pull request merged**
