### PR TITLE
[Ready] Roundstart SecHUD glasses for detectives & balanced access to "Arrest" option through them

### PR DESCRIPTION
**Pull request by Shadark**
## About The Pull Request

Detectives get SecHUD glasses roundstart.

## Why It's Good For The Game

I'd say the SecHUD glassesare very important for the Detective: It allows you to discern implanted/non implanted people at a glance and recognize people by their roles too. My second point is: I'm not a security main, but I've played some rounds as a Detective, Security officer, even Warden, and without fail when there's a Detective in the house, they'll almost ALWAYS request (or take) some SecHUD glassesfor themselves. Typical roundstart play by the detective would be going to Warden's or Security lockers and bugging someone for spare SecHUD glassesuntil they comply, and I don't think anyone is gonna deny this request because it would be a detriment for the entire security department.

I honestly don't think this is some kind of "powergame" mechanic, even if the detective is supposed to act as an investigator and not a vigilante, the glasses allow them to perform better in almost every enviroment, and honestly it's just the current "meta", let them have their cake.

Besides, Pubby already had them, _best map ever_.

## Changelog
:cl:
tweak: Nanotrasen has upgraded the Detective starting gear: they now possess SecHUD glasses like every other Security Officer.
balance: Security access is now needed to set arrest status through SecHUDs.
add: Nanotrasen has decided to address Detectives' concerns about going "out of style". DetDrobes now contain a pair of normal sunglasses.
/:cl:

### CODE REVIEW

**Comment by Shadark** [comment]
The unrelated changes at Meta I have no idea why they're here, but I guess it doesn't change anything. If it does, I'm changing them ofc.

**Comment by MrDoomBringer** [comment]
This PR is kinda silly
The detective's entire point is that they investigate crime scenes to figure out who _should be_ arrested, not look at people who are already wanted and arrest/shoot at them. That's a security officer's role.

Your justification is kind of weak, too. 
>anyone is gonna deny this request because it would be a detriment for the entire security department. 

This same reasoning could be applied to giving them a roundstart mindshield-pin combat shotgun and full riot armor or something

**Comment by Shadark** [comment]
> The detective's entire point is that they investigate crime scenes to figure out who _should be_ arrested, not look at people who are already wanted and arrest/shoot at them. That's a security officer's role.

I'm not giving them tools to arrest or shoot people, I'm just giving them the tools to perform better at their investigative job (you can get into some stressful situations when you're lurking around looking for suspicious things and being able to discern at a glance if someone could be friendly or not is invaluable). Even more, I'd be up to close this PR if someone wants to code some special detective glasses that only allows him to have the SecHud but without the ability to arrest people, that I consider it could be out of the scope of the Detective job.

> This same reasoning could be applied to giving them a roundstart mindshield-pin combat shotgun and full riot armor or something

Well, 2 things about that line of reasoning: 

- That's a very false analogy since I'm not suggesting that, just giving them what most of the detectives I've seen (me included) always request/take roundstart. I'm not suggesting that "because everyone does it, we should modify the code to allow them to do so", but I think that could be an useful addition to the game, besides what everybody does.
- I haven't seen any detective asking for combat shotgun and full riot armor roundstart, and if that happened, I wouldn't be surprised if the warden/HoS just laughed on their face and continued playing, because that's a very unreasonable request that completely overlaps the Detective job with Security tasks.

**Comment by ATH1909** [comment]
> Even more, I'd be up to close this PR if someone wants to code some special detective glasses that only allows him to have the SecHud but without the ability to arrest people, that I consider it could be out of the scope of the Detective job.

Don't secHUDs only let you set people to arrest if you have sec access? Lemme check.

**Comment by ATH1909** [comment]
```
			// Checks the user has security clearence before allowing them to change arrest status via hud, comment out to enable all access
			var/allowed_access = null
			var/obj/item/clothing/glasses/hud/security/G = H.glasses
			if(istype(G) && (G.obj_flags & EMAGGED))
				allowed_access = "@%&ERROR_%$*"
			else //Implant and standard glasses check access
				if(H.wear_id)
					var/list/access = H.wear_id.GetAccess()
					if(ACCESS_SEC_DOORS in access)
						allowed_access = H.get_authentification_name()

			if(!allowed_access)
				to_chat(H, "<span class='warning'>ERROR: Invalid access.</span>")
				return
```

**Comment by ATH1909** [comment]
detectives have sec door access, but you could change this to its own access type, I suppose

**Comment by anconfuzedrock** [comment]
I FUCKING HATE MY LIFE

**Comment by anconfuzedrock** [comment]
oh my fUCK

Detectives do not need to have this for about a dozen reasons but here's a question for what-a reason do they need it
If security is so understaffed that it's reasonable to ask for sechuds then they can get them
If security isn't so understaffed then no fuckin' problem. either a criminal is too minor for it to be important to the detective, or so major that even the detective will know about the criminal instead of by a big red fucking W
We do not need more people playing detective as "security officer but he has a nice lethal gun every round that is basically the best ballistic on station"
We need detectives who know that every other officer can arrest but only THEY are in charge of investigations so they should do that fucking part

**Comment by HomocidlePancakes** [comment]
Det being able to view records through through the glasses instead of the console is not as bad as you make it look, people. Sure, he can see wanted people, and, of course, you can go write a 500 word essay on how it encourages “””behavior not fit for a detective”””, but being silly on the interwebs is entirely your choice, and I in any way shape or form can not stop you.

**Comment by Learner10** [comment]
>  Typical roundstart play by the detective would be going to Warden's or Security lockers and bugging someone for spare HUDGlasses until they comply,

Just because you see this happen doesn't mean that this is the norm.

Frankly, that additional data might end up getting in the way of an investigation since you can easily be tunnel visioned by a flashing red W. Most detective evidence is really based on job garb, appearances, fingerprint data, and other such stuff evidence, not arrest warrents, who's wanted, and who's not. They've got that info available elsewhere.

Besides, if they really need it (answer, they don't need it, it's just convenient), they usually can just crank a lathe printed Sec Hud into their glasses anyhow. It's not that far in terms of research.

Also, most importantly, sec huds have a poor matching look for the more tactfully dressed Detective. Don't make me seek out the QM or Lawyer just to trade down glasses.

**Comment by Shadark** [comment]
New changes (I'll update the changelog after this message):

- In order to be able to set arrest status, you now need ACCESS_SECURITY (Security) instead of ACCESS_SEC_DOORS (Brig). In fact, previously, CE, CMO, detective, lawyer and RD could also set arrest status through SecHuds.
- Similarly, portable turrets needed only ACCESS_SEC_DOORS instead of ACCESS_SECURITY (that includes security equipment), I thought this was appropriate to change.
- One pair of normal sunglasses spawn in the DetDrobe.

**Comment by Cartographer-D** [comment]
Knowing at a glance who is already set to arrest/parole/ w/e is great for the Det. The people who are going to try to arrest other people are going to go for the secHUDs regardless of this change. The Det acting as an officer without permission is a policy issue, not a code issue and this doesn't really enable them, just makes it easier to do their job either way. 

Being able to tail someone who you see is on arrest and use binoculars or some other gadget to spy on them and see what they do to gather more evidence is one of the many ways this helps the Det flesh out a role. Great change.

**Comment by Shadark** [comment]
Well, I wanna clarify that this is ready but open for further feedback (I've already tried to ask @ discord for someone to review this without avail).

**Comment by kriskog** [comment]
We don't need this. Detectives are not full security members, on purpose. They are not intended to be arresting people, and if you need to set someone to arrest you can do so using any of the security consoles around the station.

**Comment by Shadark** [comment]
Going to reparaphrase the messages I typed in Discord for transparency and further input:

1. I don't feel like the main point of the closing message addresses what's this PR about. In fact, I _nerfed_ the access to the arrest option through SecHUDs to most roles (without this PR, roles such as Lawyer, CMO, etc; can arrest people through SecHUDs and I'd say they're not supposed to, either).
2. Any detective could be arresting people now (but I concede that it'd be easier with roundstart SecHUDs), more if they request SecHUDs now to the warden/HoS. I'm not proposing giving them more tools to do so. I'm just proposing giving them more access to roundstart tools that they have available. Obviously, those tools could be used wrongly (in this case and within the scope of this PR: they could be pursuing wanted people instead of investigating crimes, because they can't set to arrest anymore through SecHUDs) but I think they won't provide so much of an advantage/distraction (from their supposed job) so as not to allow it.

As for your Discord question: "I also said detectives are not supposed to be arresting people, so why do they need sechuds?" - I also explained my personal opinion in the PR message: "It allows you to discern implanted/non implanted people at a glance and recognize people by their roles too" - Maybe I could rewrite that message (english not my first language, yadda yadda) for more clarity, but at least I don't think that the reasons you gave are accurate to the spirit of the PR. I have seen multiple instances of detectives requesting SecHUDs, so I'd also ask, "why do they feel like they need them?" - If many people is playing Detective wrongly, maybe we should rework what Detective is all about, or start enforcing it by the rules.

**Comment by kriskog** [comment]
The PR was less than two days away from getting autoclosed, it had no other maintainer interest either.

**Pull request closed without merging**
