### PR TITLE
Adds random character when antagonist preference

### PR DESCRIPTION
**Pull request by kriskog**
## About The Pull Request
Well known statics rejoice! You can now choose to have random name/body/age/gender whenever you roll roundstart antagonist.

Since player mobs are generated before antag datums are handed out, I added a list that collects minds chosen as antags during pre_setup() to keep track of this.

"Other" was also missing from the random gender, added it.

Wizard, clown op, nukeop, latejoin and midround antags are excempt. 

## Why It's Good For The Game
Some static namers get metagamed to the extreme when antagonists, this should help alleviate that while allowing them to keep static naming for the RP. Keep in mind all conversion, midround and latejoin antag rolls are excempt, this is not a guarantee someone is a non-antag.

## Changelog
:cl: Skoglol
add: Random name/body/age/gender when roundstart antagonist preference added. 
add: Random gender will now have a chance of picking "Other".
/:cl:

### CODE REVIEW

**Comment by Naloacisamazing** [comment]
Blessed PR

**Comment by carlarctg** [comment]
@Fikou why downvote

**Comment by SkeletalElite** [comment]
GENE BALL MOVING

**Comment by BOBAMAx** [comment]
add an exception so that people with ckey "Nabski" can't enable this

**Comment by Shapsy** [comment]
I feel like this hurts the social aspects of SS13 where even your friends and people you get along with can be bad guys (assuming the player behind them has antags enabled at all). I also feel like this may cause other knock-on meta issues (notice that player X was a random name the last few times they were traitor so their static is probably immune from those antag types, or undue suspicion against all randomnames)

Aside from that, I left "Other" out of the random gender options on purpose since I figured most players would want to stick with the gender binary, but if people are fine with it then :+1:

**Comment by ATH1909** [comment]
Uh, aren't people gonna use this to gain a reputation of always being a "confirmed good guy" (unless they've been converted or something, which isn't usually possible on lowpop), because if they were a roundstart antagonist, they'd be under a random name?

**Comment by ATH1909** [comment]
Also, people are gonna go "Hmmmmm, there was a staticnamer moth/ethereal/lizardperson/whatever geneticist last round, and now there's another moth/ethereal/lizardperson/whatever geneticist this round with randomized features. I bet they're an antag!".

**Comment by PKPenguin321** [comment]
Gotta agree, the meta aspect of this isn't worth what little benefit it gives

**Comment by kriskog** [comment]
At least in dynamic, midround and latejoin triggers fairly often. This is by far not a guarantee your friendly neighborhood static is not an antag, even when conversion is out.

**Comment by kriskog** [comment]
> 
> 
> Uh, aren't people gonna use this to give their characters a reputation of always being a "confirmed good guy" (unless they've been converted or something, which isn't usually possible on lowpop), because if they were a roundstart antagonist, they'd have a random name?

If they do, it's an admin issue. You could say the same thing about people with antags off today.

>
> 
> I can envision now (with only a slight bit of exaggeration/hyperbole) people salting at wardens for DARING to brig someone on lowpop whom EVERYONE _clearly_ knows has this option always enabled (smh, it's like brigging a sec officer for being a traitor, everyone _KNOWS_ that XYZ can't be a blood brother! just quit playing sec forever, you drooling imbecile!).

Again, admin issue. We have to trust our players to not impose OOC knowledge on people IC. You know how latejoin traitor practically never triggers on secret, yet people don't use that as proof they are not an antag? Same thing.

> 
> 
> Also, people are gonna go "Hmmmmm, there was a staticnamer moth/ethereal/lizardperson/whatever geneticist (or virologist or some other role with not much competition for slots (that night)) last round, and now there's another moth/ethereal/lizardperson/whatever geneticist this round with randomized features. I bet they're an antag!".

If you act on shit like this, you are part of the problem even without this change. We can already meta people based on their behaviour IC, most people have antag tells. Most people don't.


I think that the slight risk of someone abusing the system (and at the same time opening themselves up to administrative action) is worth improving the game for people who need it. This is an age old issue, where people will happily rush maints if they hear "Help maint Lexia traitor" but ignore the call if it's just a random name.

**Comment by Cyprex** [comment]
Subtly treating people differently is hard to handle since everyone does it. For example, you see two dead sec officers: Lexia Black and some random name you don't recognize? This is technically against the rules, but most of the server does this so this isn't actionable.

Things like these are headaches for admins, please don't create more of them.

**Comment by Akrilla** [comment]
> I feel like this hurts the social aspects of SS13 where even your friends and people you get along with can be bad guys (assuming the player behind them has antags enabled at all). I also feel like this may cause other knock-on meta issues (notice that player X was a random name the last few times they were traitor so their static is probably immune from those antag types, or undue suspicion against all randomnames)
> 
> Aside from that, I left "Other" out of the random gender options on purpose since I figured most players would want to stick with the gender binary, but if people are fine with it then 👍

I play tg for the social experience of being wordless killed tbh

**Comment by ecronogist** [comment]
honestly if someone wants to roll antag they should have a third character slot open for antag shit that's set to all random or whatever "shady" character they'd like to whip up
**that's IF they actually care to do this.**
the tools are already there for this - this is just making it a lazy toggle, i.e. extra stuff that doesn't require automation
i'm not discrediting your work i'm just saying the way to do this is already available, assuming the player doesn't have all three slots allocated to genuine characters (which, to be frank, i don't think most people do this)

i dunno chief i just believe this to be a non issue in my epic shitty opinion

**Comment by Fhaxaris** [comment]
This isn't really going to cause more problems than there already are. People will always have meta info, and there is no great way to stop them from getting it.

**Comment by fatted50** [comment]
lexia black buff

**Comment by optimumtact** [comment]
people are going to metafriend either way

**Comment by Shadowflame909** [comment]
Bad PR

how do I lay down and die when lexia black is antag if I don't even know its them

You're putting me in a whole world of suffering that I could have avoided previously

**Comment by wesoda25** [comment]
Perhaps if someones playstyle is so shit that they can't play the game normally they should focus on fixing that instead of getting a code solution

**Comment by Shadowflame909** [comment]
yeah that whole metagame issues of "gene ball isnt here but nabski is here" argument isn't the real issue

now people who previously were lienant on static name murderbone because of how assholish behavior could be attributed to there static now can just enable this and go full boomer murder all the dang time.

not epic have mercy

**Comment by kriskog** [comment]
Are you seriously defending metagrudging? You cunts are fucking depressing.

**Comment by Shadowflame909** [comment]
what's depressing is not looking on the other side of this and defending murderbone

If you kill everyone's joy every time you play antag that you NEED this feature. (Which, the majority don't.) That should be a mental check on yourself.

Anyone who isn't infamously unfun to play against and doesn't abuse features to there absolute limits has no need for a feature like this.

Ahem Ahem Seeing Lexia Black in virology as they created a plague that killed everyone in 5 seconds versus seeing random unstatic in virology doing the same.

You literally can't tell them to cut that shit out without a non-static.

This feature really helps people enjoy single player gta with none of the consequences.

Hell fucking yeah, if you see Lexia Black doing virology as the CMO. You're coming in there with a hazmat suit because you already know whatever they coop up won't have any counterplay.

cringe feature, thanks for the extra unstoppable murderbone kriskog.

**Comment by kriskog** [comment]
If you go rushing into viro just because Lexia Black is there, you are the reason this feature is needed in the first place. Stop metagaming people, and maybe they wont see the need to turn this on.

**Comment by Shadowflame909** [comment]
If your antag gimmick is making death viruses that kill you with no counter-play. Recognizability is literally the last defense to stop that.

It's a part of this game to lose. But I dunno, Cuban Pete 2.0 who bombs the station every round they get antag. Or E-bow + E-Sword JR all the time shouldn't be absolutely vilified for being completely unoriginal and annoying?

Change your playstyle, and don't hide behind a "god-mode" to cheese people with terrible gimmicks.

**Comment by kriskog** [comment]
Luckily, I can choose to just "hide behind" the rules that tell you not to bring grudges and other metainfo from one round to another. You need to reconsider how you play this game.

**Comment by Shadowflame909** [comment]
trying to have your mass murderbone cake and eat it too.

The rules also say don't be a dick Kriskog.

Items like the supermatter sword and Instant kill rifle are admin only for a reason.

So creating and hiding behind a feature such as this, when you antag and use a gimmick that completely removes any "response" that is possible against you by one shotting the entire crew is shit.

If you're going to use a gimmick that takes the "multiplayer" out of a multiplayer game like ss13. The least you can do is accept the salt that is bethrowed upon you for making the masses go horizontal.

If you can't even do that, yet continue to use such a gimmick. You honestly shouldn't play at all.

Also, defending a feature such as this is hypocritical. When you yourself recently made a change to nerf antag adrenaline power very heavily. As players being able to negate themselves from being stopped by security without any recourse from said security players sucked and was baffling.

All I'm really saying is, It's like playing the game the way it isn't meant to be played. Or at least stressing its core features to its very limits, and getting a "get out of jail free card" with this PR.

That's not right.

Isn't that why tasers were removed? For taking away the abillity to react from the player in an instant?

This is effectively the same thing now. Just of a higher part of the system that makes this game work.

This is the "tasers" of the antag system.

**Pull request merged**
