### PR TITLE
(prev grey bull only) Soda and beer cans fit on tool belts - honoring the age-old tradition of drinking on the job

### PR DESCRIPTION
**Pull request by KazooBard**
## About The Pull Request
The grey bull can fits on storage belts. There's so little value to be had from using it to store other reagents that it's not worth it, but grey bull on a belt lets people do more micro in backpacks. Yes, I could do it without this, yes, it'd be easier if I didn't have to juggle to have my kidney stone juice. Really small change, really neat, not game breaking or anything, plenty of people would be happy *if you count assistant players as people

## Why It's Good For The Game

Look, it fits! 

361471076-c53bbf46-cc30-411b-bd12-1c0ad1ea87f3

## Changelog

:cl:
qol: All cans (soda cans etc) fit on utility belts now. Drink on the job!
/:cl:

### CODE REVIEW

**Review by MrMelbert — APPROVED** [review]

**Comment by Loafin34** [comment]
could you hang spess beer on the tool belt as well?

**Comment by projectkepler-ru** [comment]
drinking greybull before hacking a door is like popping crit a cola then using the shortstop to snipe that one guy you really don't like

**Comment by TheVekter** [comment]
Bee cans

**Comment by private-tristan** [comment]
Please update changelog to reflect the new changes?

**Comment by Stalkeros2** [comment]
Bee cans

**Comment by TheVekter** [comment]
> Bee cans

Get his as

**Comment by KazooBard** [comment]
All is updated, hoping someone merges it! :D

**Review by Cyberboss — APPROVED** [review]

**Pull request merged**
