### PR TITLE
Makes Wizards get only a special "fuck their shit up" objective

### PR DESCRIPTION
**Pull request by ghost**
because stealth wizards are gay

:cl: More Robust Than You
tweak: The wizard's federation no longer cares about jetpacks or telearmor, they just wanna fuck NT up!
/:cl:

### CODE REVIEW

**Comment by MoreRobustThanYou** [comment]
@Cyberboss try playing as not-the-wizard during a stealth wiz round. it's slow and horrid.

**Comment by Firecage** [comment]
A-Are you goofball?

**Comment by CPTANT** [comment]
Yeah, seriously who cares about objectives when you are a wizard?

**Comment by Firecage** [comment]
Well, one round I decided to actually do my objectives. Disguised as an assistant, assassinated a miner, escaped on the shuttle when it eventually came. Everyone thought it was extended.

**Comment by MoreRobustThanYou** [comment]
99% of wizards just blow shit up til they get gang raped by greytide...

**Comment by kevinz000** [comment]
Dumb

**Comment by Iamgoofball** [comment]
Stealth wizard is bad

**Comment by kevinz000** [comment]
TG has more than enough murderbone without an objective telling a specific type of antag to do it at all costs.
Also this is literally free greentext you dumb fuck.

**Comment by BeeSting12** [comment]
He's right but this doesn't make it a good idea

**Comment by DoctoreMad** [comment]
Clearly wizards should have all the possible objectives but they are only encouraged to complete one thirds of them all.

**Comment by InsaneHyena** [comment]
Fuck stealth wizards, and fuck friendly wizards.

**Comment by Aloraydrel** [comment]
4x mindswap apprentice is the thinking mans build

**Comment by Robustin** [comment]
I agree. Nobody wins when a wizard when a wizard actually TRIES to do their objective and escape via stealth instead of just brute forcing their way through the round. 

Stealth isn't "being sneaky, wearing a good disguise, etc." its literally just sitting in an unreachable part of maint(think Ian shirt or rainbow shirt) and then teleport+jaunting onto an escape pod with 5 seconds to launch.

**Comment by kevinz000** [comment]
Stealth wizards are shit and I'm not supporting them.
However 'Free greentext with the OPTIONAL (oh yeah TG objectives are optional!) objective of kill everyone and destroy everything' doesn't sound like anywhere near a good fix.

**Comment by Armhulen** [comment]
Add a survive objective and I support this

**Comment by AnturK** [comment]
Make it just cause chaos without being specific on damage and i'll be fine with this. Wizard rounds are already at the mercy of the player, so might as well drop the pretence objectives matter.

**Comment by CosmicScientist** [comment]
You might as well give them a real objective to do with wizardry than just tell them they have a non-objective.

Assassination and theft are perfectly serviceable.

Stealth is only a problem because there's no-one to do anything whilst the stealth happens (so do something like remove stealthy spells unless the wizard is paired up with another wizard or antag who will go loud for them).

**Comment by Bawhoppen** [comment]
image
:thinking:

**Pull request closed without merging**
