### PR TITLE
Salt and Pepper resprite

### PR DESCRIPTION
**Pull request by chanoc1**
:cl: chanoc1
tweak: Resprited the salt shaker
tweak: Resprited the pepper shaker
/:cl:
peppermillsmall
saltshakersmall

### CODE REVIEW

**Comment by Cheridan** [comment]
watch out you're messing with tgstation culture here

**Comment by Anonmare** [comment]
That salt sprite looks nothing like the playerbase

**Comment by chanoc1** [comment]
i thought the old sprites looked really out of place

**Comment by optimumtact** [comment]
you should update the emote sprite as well

**Comment by Nienhaus** [comment]
Or leave the emote so it's remembered.

**Comment by chanoc1** [comment]
i agree with neinhaus, its ~legacy~

**Comment by WJohn** [comment]
These don't even look any better than what we have right now.

**Comment by nullbear** [comment]
i'm with Wjohn. but im pretty sure this is a meme PR anyways so.

**Comment by chanoc1** [comment]
this is NOT a meme PR. also what chu talking about the ones we have right now have gross thick black outlines and no shading

**Comment by WJohn** [comment]
So do these though???

**Comment by FantasticFwoosh** [comment]
Salt and pepper shakers differ across the globe, to me all salt salt and pepper shakers look like your first sprite in shape in jolly old England, round so that you can spill more salt on your fish and chips, whilst most American shakers, popularised by American roadside restaurants are traditionally like the old designs.

> If you really wanted to _go out there_, you could have made a great big pepper/salt grinder sprite

Really a clash of cultures, i initially like this but just keep in mind that people might be alienated. Especially surrounding the salt shakers (and as mentioned, tg culture)

**Comment by chanoc1** [comment]
these don't have a black outline. at least not pure black. You never want to go pure black

**Comment by WJohn** [comment]
I'll get to these personally pretty soon, anyway and make something even less liked, don't worry, you won't have to bear any of the brunt of the vitriol. LET PAPA DO IT.

**Comment by chanoc1** [comment]
Thanks _papa john_ :^)

**Pull request closed without merging**
