### PR TITLE
New Bone Armor Sprites: Digi Friendly Edition

### PR DESCRIPTION
**Pull request by Mey-Ha-Zah**
## About The Pull Request

Changes the Bone Armor Sprites. And makes it so Digi Players keep their funny legs.
image

## Why It's Good For The Game

Always irked me how bone armor, a staple of the ashwalkers, hid their legs. Now they don't. Yay.

## Changelog

Updates Bone armor sprites. Sprites no longer hide Digi legs.

:cl:
image: added/modified/removed some icons or images
/:cl:

### CODE REVIEW

**Comment by LePiromano** [comment]
cool asf but now it doesn't make sense why wearing it prevents you from stepping on cacti

**Comment by Deultus** [comment]
It looks terrible.

**Comment by Xkallubar** [comment]
Looks ugly. Especially the helmet. Half of it doesn't even look bone.

**Comment by Mey-Ha-Zah** [comment]
Seems general sentiment is I should make it clearer the legs are protected.
Will be re-doing it then and re-opening later if I finish it.

Unlikely due to IRL constraints but we shall see.

**Pull request closed without merging**
