### PR TITLE
Replaces 'Goebbles' random last name

### PR DESCRIPTION
**Pull request by CoffeeDragon16**
## About The Pull Request

Removes a last name that's one character off the name of Nazi Joseph Goebbels. This replaces them with Gobbles and Gobbler, because those are funny.

## Why It's Good For The Game

You probably shouldn't be able to roll a nazi's name, also can cause confusion for admins thinking a guy chose it because hurrhurr Hitler.

## Changelog
:cl:
tweak: Removes 'Goebbles' from the last name list, replaces with Gobbles and Gobbler.
/:cl:

### CODE REVIEW

**Comment by Qustinnus** [comment]
alright you hate germans i get it.

**Comment by IndieanaJones** [comment]
This seems like an odd change, I feel either you or whoever convinced you to make this PR was really reaching for the nazi connection,

**Comment by CoffeeDragon16** [comment]
i just dont want people to get bwoinked over a random name

**Comment by Jared-Fogle** [comment]
when i think of goebbels i dont think of nazis, i say as i passed my history class only because the teacher desperately wanted me to stop drooling on all the desks

**Review by Mothblocks — DISMISSED** [review]

**Comment by LemonInTheDark** [comment]
This seems somewhat pointless honestly, you could in theory roll plenty of names that would make an admin boink you. I don't see why this misspelling of a nazi's last name should be any different. Then again, it is name that's associated with nazis, so eh

**Review by Rohesie — DISMISSED** [review]
Absolutely no loss here.
The nazi propaganda minister is the only Goebbels I know of, and it's not precisely an obscure figure.

**Comment by Qustinnus** [comment]
american moment

**Comment by TheVekter** [comment]
Eh, it's one of those "no reason to do it, no reason not to" things. Might as well get rid of it.

**Comment by SweptWasTaken** [comment]
Change it to Gobbles.

**Comment by CoffeeDragon16** [comment]
Done

**Comment by actioninja** [comment]
change it to gobbles

**Review by actioninja — DISMISSED** [review]

**Comment by CoffeeDragon16** [comment]
Why not both?

**Review by actioninja — APPROVED** [review]

**Comment by Jared-Fogle** [comment]
add the new names in the changelog

**Comment by cacogen** [comment]
Yeah this is fine people can still get in trouble for it by picking it themselves if they want.

**Comment by interestingusernam3** [comment]
Goebbles is a german surname. 
Famous Goebbels's unrelated to the IIIrd Reich:

- https://en.wikipedia.org/wiki/Robert_Goebbels
- https://en.wikipedia.org/wiki/Heiner_Goebbels
- https://en.wikipedia.org/wiki/Matthias_Goebbels

Incomplete map of the Goebbels's alive today:
https://forebears.io/surnames/goebbels

Whoever bwoinked you over the surname Goebbels probably doesn't know that German people didn't stop existing after WW2.

**Comment by cacogen** [comment]
I meant picking "Joseph Goebbels". There should just be a blacklist for the randomiser set in config for certain name combinations servers don't like to avoid someone getting in trouble the 1 in 100 rounds the stars align and give somebody the name of a historic person who was bad.

**Comment by Rohesie** [comment]
Or just remove this last name, less than 1000 people in the world having it currently according to the (incomplete) map source posted here?

**Comment by cacogen** [comment]
No, that is a worse solution than what I suggested because it doesn't solve the underlying problem.

**Comment by Timberpoes** [comment]
Yeet this shit. If you want to use it as a name, input it manually.

It's not a policy ban on the name, just yeeting it out of the random pool of autonames. I support this PR.

**Comment by Ryll-Ryll** [comment]
lol gobbles

**Comment by Qustinnus** [comment]
richard gobbler 😏

**Comment by interestingusernam3** [comment]
>I meant picking "Joseph Goebbels". There should just be a blacklist for the randomiser set in config for certain name combinations servers don't like to avoid someone getting in trouble the 1 in 100 rounds the stars align and give somebody the name of a historic person who was bad.

By setting a slot to always random name you automatically accept the possibility of rolling "Sissy Goebbles".

**Comment by interestingusernam3** [comment]
The probablility of a male character with random name on becoming a misspelled german propaganda minister is 1/380190 (1/length of male first names file in lines * 1/length of male surnames file in lines, if anyone wants to verify).

**Comment by cacogen** [comment]
I once got a random name of someone who used to play a lot back when I started years after they stopped playing and someone PDA'd me thinking I was them. I was sort of close with them when they did play so it was odd.

**Comment by Makarov22** [comment]
This is fucking hilarious

**Pull request merged**
