### PR TITLE
Removes grind_results from empty soda cans

### PR DESCRIPTION
**Pull request by 81Denton**
:cl: Denton
code: Removes grind_results from empty soda cans since they can't be ground.
/:cl:

Empty (non-crushed) soda cans count as containers and can't be ground. No reason for them to have grind_results.

### CODE REVIEW

**Review by Cyberboss — DISMISSED** [review]
Fucking reagent ids were a mistake

**Comment by Shirbu** [comment]
Denton, I was under the impression that soda cans count as reagent containers, and can't be ground without first being crushed.

**Comment by 81Denton** [comment]
Darn, let me actually test that.

**Comment by 81Denton** [comment]
You were right, empty soda cans count as containers and can't be ground. I'll remove their grind_results.

**Comment by Shirbu** [comment]
Excellent! In case you didn't know, (as I didn't) if you empty the can and harm intent hit it on your face, it becomes the crumpled can.

**Review by Cyberboss — APPROVED** [review]

**Pull request merged**
