### PR TITLE
Stops particle holders from appearing on context menu

### PR DESCRIPTION
**Pull request by ChungusGamer666**
## About The Pull Request

Basically, due to carbons using KEEP_TOGETHER, particles were appearing on the context menu which is annoying. I have no idea why it behaves like this.
Buuut, giving particle holders the KEEP_APART flag does fix this.

closes https://github.com/tgstation/tgstation/issues/75641

## Why It's Good For The Game

Bugfix good

## Changelog

no

### CODE REVIEW

**Comment by ChungusGamer666** [comment]
@JohnFulpWillard you wanted this

**Comment by ChungusGamer666** [comment]
Particle holders should still not appear in the context menu if you right click someone who is on fire. I'll see if I fucked up the deletion logic on the status effect though.

**Comment by SyncIt21** [comment]
> Particle holders should still not appear in the context menu if you right click someone who is on fire. I'll see if I fucked up the deletion logic on the status effect though.

Agreed, What i am hoping is rather than addressing only half the problem of hiding the particle holder from the context menu maybe you can also check to see if they are properly deleted as well, but i understand if that's out of scope

**Comment by ChungusGamer666** [comment]
@SyncIt21 Deletion logic appears to be fine, it just so happens that being wet also creates a new particle holder for water particles :)
Either way, pushed some commits to be extra sure that particle holders dont stick around.

**Pull request merged**
