### PR TITLE
Fixes iron duplication bug (This is why you use defines, people)

### PR DESCRIPTION
**Pull request by GPeckman**
## About The Pull Request

In PR #75437, sheets were changed from being 2000 units of material to being only 100. This caused an unintended bug, as the datum for iron rods didn't properly use the define. As a result, you could duplicate a sheet of iron into 20 sheets by turning it into rods and inserting it into a protolathe. This makes rods properly use the define, fixing the dupe.
## Why It's Good For The Game

Dupe bugs bad, I guess.
## Changelog
:cl:
fix: You can no longer duplicate iron by turning sheets into rods and putting the rods back into the protolathe
/:cl:

### CODE REVIEW

**Review by ArcaneMusic — APPROVED** [review]
Appreciated

**Comment by SyncIt21** [comment]
Can we like speed merge this?. We have 100 open PR's now

**Review by JohnFulpWillard — CHANGES_REQUESTED** [review]
Please while you're here, get the other instances of this

``/obj/item/stack/cable_coil``
``/obj/item/stack/pipe_cleaner_coil``
``/obj/item/stack/rods/lava``

**Comment by GPeckman** [comment]
Alright, I've made those 3 things used defines too. I also updated the pipecleaner grind_results to use the same format as normal cable.

**Pull request merged**
