### PR TITLE
artifact science (to replace experimentor, not RnD)

### PR DESCRIPTION
**Pull request by mc-oofert**
https://hackmd.io/@UqfVJWC0TWKOUxyjs-iyzA/ByX2Vi-bh

slightly based off gooncode, primarily some effects and most of the triggers

## About The Pull Request

adds artifacts; detailed in the design document but im going to keep it short here:
experimentor is removed, the space it used is now used for artsci labs

you can buy replacement analysis form bins from cargo

### artifacts
anyway these are in better detail explained in my design doc so im going to just summarize it here
artifacts are mysterious objects, that can be dug up by miners, or can start in the artlab.
they have a random function chosen by rarity, and their sprite is random decided by their "Origin", which are Nar-sie, Wizard, Ancient.
they are usually large, dense artifacts, but can also be handheld!
On certain types of artifacts, origin can minorly affect the RNG of the artifact.
Artifacts are inert until activated, more on that later
a scientists job is to figure out how to activate the artifact, and use it if its beneficial or sell it to cargo after properly writing out an analysis form and sticking it to the artifact, which then is sold at cargo.
image
these are the triggers
image

artifact types calculate their Potency on their own, which is used to determine how much does it sell for and how much stimulus do you need to activate it
minor example i guess

https://github.com/tgstation/tgstation/assets/70376633/d4a96f9a-6873-4f5a-9235-47ba75351d85

### machines

image

these are the machines you use to supply higher levels of stimulus
xray can show you some tidbits but dont rely on that, xray gives radiation stimulus
heating pad heats or cools artifacts on top of it, gas piped into it is passively cooled to 20C (it also heats people)
zapper shocks (naturally)
the rest of the triggers you figure out on your own so good luck

### admin swag

image

## todo

- [ ] get better sprites for the missing sprites
- [ ] finish up the unfinished artifact types
- [ ] clean up some code

also credit to rex9001 and some other dude for sprite help

## Why It's Good For The Game

experimentor is an old fucking crusty piece of shit and its probably better that its get replaced with something that has more depth than clicking 1 button

## Changelog
:cl:
add: artifact science, artifacts
del: EXPERIMENTOR, and its relics
/:cl:

### CODE REVIEW

**Comment by SimplySmiley123** [comment]
Hopefully it's not so rare it's never gonna be found for most of the rounds and hopefully not so randomly bullshit that nobody will want to roll the dice once an artifact gets brought to science and rewarding enough to bother risking getting bombed or whatever other bad effects there'll be.

**Comment by nikothedude** [comment]
we bay now baby

**Comment by HalfPunch** [comment]
I hope there will be as much really good artifacts as really deadly ones

**Comment by carlarctg** [comment]
im going to miss my free teleporter and corgi spawners

**Comment by CCC23** [comment]
Beautifual

**Review by jlsnow301 — CHANGES_REQUESTED** [review]
These will need to be made into typescript at least. Let me know on discord if you need help with it

**Comment by ZeWaka** [comment]
unfortunately dead via licensing as a lot of this code is *heavily* based off of unrelicenseable gooncode
in the future read the readme

**Comment by mc-oofert** [comment]
> unfortunately dead via licensing as a lot of this code is _heavily_ based off of unrelicenseable gooncode in the future read the readme

1984 by awful licensing

**Pull request closed without merging**
