### PR TITLE
[omega]engine re-buildings.

### PR DESCRIPTION
**Pull request by SgtxRootbeer**
:cl: Rootbeer
del: severely shortened most of the scrubber piping in sm engine room
del: severely shortened most of the distro piping in sm engine room
tweak: set the filter that connects the waste-filter loop to the waste-scrubber loop to "nothing" instead of "plasma" so plasma doesnt clog up the loop.
add: filter to injector in space for SM engine, so the exhaust can actually go somewhere other than clogging up the cooling loop.
add: atmo to cooling loop piping hookup, isn't fully hooked up.
add: arrivals security checkpoint is defined as its own area.
del: a lot of duplicated air alarms in the engineering section of the station.
add: a lot of wiring for apc terminals that was missing previously
Fix: defined some areas near the evac shuttle properly now.
/:cl:
my first attempt using map merger, tell me if I borked it, now for my reasoning.
A private server I play on hosted a 16 hour long session on this map, (would have been +24hr if not for the MC shitting itself on the machines subsystem... but thats another story.) 
As the engineer, I was appalled by the engine setup that was put there. no filter to get rid of waste, no handling of waste, i had to manually move canisters of gas to the engine room, and we lived in constant fear of the engine delaminating. I went to the captain and declared the engine unfit for service, pending 3-4 hours of re-building.
eventually, we opened up a hole to space, and cargo-ordered some solar panels for high-energy equipment, and got xenobiology to  replace literally all of the APC cells with yellow slime cells.

During my adventures in mapping, I noticed a lot of duplicated air alarms. The wiki page on mapping states "exactly one" so, I fixed that.
I also noticed 3 APCs were missing the wire knots underneath to connect them to the grid, that was fixed. 
In arrivals, the security checkpoint had its own apc, despite being defined as the same area as the surrounding halls, rather than let the outside APC control the door to the checkpoint, and allow greyshits inside, I defined it as its own area.
edit: added picture
old:
capture3
new:
capture23

### CODE REVIEW

**Comment by ShadowDeath6** [comment]
changelog meme spotted

**Comment by SgtxRootbeer** [comment]
"Fission mailed, we'll get em next time..."
>skub: skub
fine.

**Comment by MrPerson** [comment]
Just a heads up, you can disable viewing the areas in Dream Maker by:

1. Go to the top bar -> layers-> untick "areas" or hitting ctrl-1
2. Top bar -> layers -> tick "only show seletable layers".

**Comment by SgtxRootbeer** [comment]
@MrPerson 
Thanks, but I was using fastdmm.

**Comment by MrPerson** [comment]
Better make a note to try it out at some point, then. Nice to see it was functional and useful.

**Comment by Tokiko1** [comment]
Consider using engine floor for the entire room so it doesn't melt to space if one of the engine windows breaks.

**Comment by PKPenguin321** [comment]
>Thanks, but I was using fastdmm.

Go to options -> filters and delete the area path line

**Comment by SgtxRootbeer** [comment]
I will take a look at those options when I get home, until then, all I can do is yak on GitHub with my phone.

**Comment by SgtxRootbeer** [comment]
updated, i thought about upgrading the floor, but then i realized 2 things. 
1, engineering is going to be tinkering with this engine a lot, and having to rip up reinforcement isnt gonna be fun.
2, not only is it a possible upgrade for engineering to add to their engine, but by not allowing it, i severely lower the chance of my update getting called a hugbox update.

**Comment by SgtxRootbeer** [comment]
After doing more testing with the previous engine setup, I have determined that this update is no longer needed.

**Pull request closed without merging**
