### PR TITLE
> "IT'S A TARP"

### PR DESCRIPTION
**Pull request by Cyberboss**

### CODE REVIEW

**Comment by FantasticFwoosh** [comment]
DONT STEP ON ME REEEEEEEEEEE

**Comment by ExcessiveUseOfCobblestone** [comment]
Tarp!

**Comment by ShadowDeath6** [comment]
That description is A+

**Comment by Tacolizard** [comment]
do you hate fun cyberboss?

also the sprite should be changed to a blue tarp sprite

**Comment by CPTANT** [comment]
Leave the memes alone!

**Comment by XDTM** [comment]
The Tarps spell for wizards when

**Pull request merged**
