### PR TITLE
Adds Snowman costume

### PR DESCRIPTION
**Pull request by swankcookie**
:cl: swankcookie
bugfix: Fixes issue of space-Christians forgetting about the true, humbling values of space-Christmas.
rscadd: Adds snowmen outfits
/:cl:
snowman

### CODE REVIEW

**Comment by swankcookie** [comment]
can i get a "merge ASAP" tag, please?

**Comment by PKPenguin321** [comment]
https://github.com/swankcookie/-tg-station/blob/snowman/code/game/machinery/vending.dm#L615
>IF YOU MODIFY THE PRODUCTS LIST OF A MACHINE, MAKE SURE TO UPDATE ITS RESUPPLY CANISTER CHARGES in vending_items.dm

dunno if you actually need to since this is a seasonal object anyways but iunno

**Comment by swankcookie** [comment]
oh great thanks

**Comment by Bawhoppen** [comment]
why is desc not shit-tier frozen meme come on you ruined your opportunity

**Comment by CosmicScientist** [comment]
:+1:
@Bawhoppen that's too relevant, it'd need to be references to The Snowman (I like the current descriptions though).

**Comment by bgobandit** [comment]
@Bawhoppen 
maybe you should just
....
............
............

**Comment by duncathan** [comment]
@bgobandit 
Fuck you and your shitty fucking meme god damn ;-;

**Comment by Cheridan** [comment]
do you wanna grief a snowman?
it doesn't have to be a snowman

**Comment by Niknakflak** [comment]
Hell, why not just make this a new playable race :^)

**Comment by Bawhoppen** [comment]
if its a playable race it needs a spell thats just magic missile but snowballs instead

**Pull request merged**
