### PR TITLE
Adds a new mutation: Antiglow

### PR DESCRIPTION
**Pull request by nemvar**
## About The Pull Request

Adds a new mutation. Anti-Glow. It is created by mixing void magnet and glowy and negates the light around you.
Also slightly alters mutation conflict code so it is more straight forward

## Why It's Good For The Game

Ther was talk about more mutations and I'm a man of the people. It was also on this list https://file.house/62Et.png and I thought it was a good idea.

## Changelog
:cl:
add: A new mutation. Anti-Glow. Same as Glowy only the exact opposite
/:cl:

### CODE REVIEW

**Comment by optimumtact** [comment]
power creep

**Comment by Arathianen** [comment]
Power anti-creep:

Mix power creep with void magnet

**Comment by Shadowflame909** [comment]
Good PR.

Nightmares will now haunt genetics for this

**Comment by PKPenguin321** [comment]
Nice! Thanks for this

**Pull request merged**
