### PR TITLE
Selected Access in HoP Console is Now Green (From Red) For Viewability

### PR DESCRIPTION
**Pull request by kriskog**
## About The Pull Request
Changes the red text on the access buttons to black.

Old:
image

New:
image

## Why It's Good For The Game
Many eyes were saved today.

## Changelog
:cl: Skoglol
tweak: Hop console now hurts your eyes less. Red button text replaced with green.
/:cl:

### CODE REVIEW

**Comment by cacogen** [comment]
I don't think black is a good choice of highlighting colour. You could just make the blue background darker for selected buttons, which seems to be how Windows does it when you click things.

**Comment by Akrilla** [comment]
Black/white is really not clear. Just decrease colour saturation

**Comment by kriskog** [comment]
Was already looking at other options. How is this?
image

**Comment by cacogen** [comment]
I mean I don't like the colour scheme but the red wasn't very good either.
It looks better than the black. I would look at other UIs and see how they
handle depressed buttons.

Here is an example of what I meant by darkening the background when the
button is selected that I found in like 2 seconds on Google Images:

**Comment by cacogen** [comment]
I mean I don't like the colour scheme but the red wasn't very good either.
It looks better than the black. I would look at other UIs and see how they
handle depressed buttons.

Here is an example of what I meant by darkening the background when the
button is selected that I found in like 2 seconds on Google Images:

**Comment by kriskog** [comment]
I am not trying to reinvent the buttons for our old UI, just make these in particular not horrible to look at. I went with a greenish, its better than black and conveys whats going on more than well enough.

**Comment by cacogen** [comment]
You can see the button backgrounds go white when highlighted, while the text stays the same colour. Similarly, in some UIs, the background changes shade when the button is toggled to indicate the button has been pushed in. You wouldn't have to worry about a garish looking colour against the background and readability would be better. I think it would be better than what you have.

But this is bikeshedding so I'm not going to butt in again.

**Pull request merged**
