### PR TITLE
Excessive amounts of soy milk now have a side effect

### PR DESCRIPTION
**Pull request by GuppyLaxx**
**Title.**
:cl: GuppyLaxx
add: Drinking too much soy milk can have rather "feminine" side effects for males now, watchout!
/:cl:

Why : Immersion.

### CODE REVIEW

**Comment by MMMiracles** [comment]
even if it wasn't a joke pr it probably won't get through since forced sex changes get some people's panties in a bunch because muh snowflake and admins didn't want to deal with the bullshit

**Comment by GuppyLaxx** [comment]
Use charcoal! It takes 50 chem cycles for it to take effect, that's more than enough time to get something to purge yourself.

**Comment by granpawalton** [comment]
what if you kept it but changed it so it wasnt a permanent effect and gave it a lower threshold accordingly. Like making it a temporary voice changing effect or something that would give meme messages to chat.

**Comment by ninjanomnom** [comment]
Can we not

**Comment by Iamgoofball** [comment]
https://www.fertstert.org/article/S0015-0282(09)00966-2/pdf
https://www.fertstert.org/article/S0015-0282(10)00368-7/pdf

soy doesn't impact shit lmao

**Pull request closed without merging**
