### PR TITLE
Cool and Nice PDAs

### PR DESCRIPTION
**Pull request by maxymax13**
## About The Pull Request
soulless

Makes all PDAs look cool and good for once.

- [x] Achieve cartridge overlay

- [x] Achieve curator overlay functionality

## Why It's Good For The Game
Game look nice shiny fancy make player happy yes 

## Changelog
:cl:
imageadd: Despite rumors of being phased out, Nanotrasen has produced a new slight revision of their employee PDAs. The Syndicate has responded accordingly with their own PDAs, too.
/:cl:

### CODE REVIEW

**Comment by PKPenguin321** [comment]
This is less 3/4ths and more "they were put on a diet and are skinnier now" and saying that that makes them automatically better is actually pretty fatphobic and ableist

**Comment by Pumpkinoe** [comment]
skinnier PDAs are cute :) but i like both sprites

**Comment by wesoda25** [comment]
How does it look in game?

**Comment by maxymax13** [comment]
> 
> 
> How does it look in game?
dreamseeker_Cjs8OEKGHI
Supposed to look somewhat like this. Having troubles with Git right now but the code looks fine and the dmi seems well formed.

**Comment by Fikou** [comment]
i dont think it fits the tg style with everything on these sprites being very soft colors

**Comment by wesoda25** [comment]
> i dont think it fits the tg style with everything on these sprites being very soft colors, it really stands out in that inventory picture and the light looks lame

Agreed, I feel as if the shape is a lot less defined than some other things we have

**Comment by maxymax13** [comment]
it's almost the same colors as the originals except for some turbo neon saturated vomit pdas i cleaned up somewhat though

**Comment by ATH1909** [comment]
:soul:

:soulless:

**Comment by maxymax13** [comment]
assistant pda
curator pda
it works

**Comment by Iatots** [comment]
Wasted space on the left and blurry shading; the screen in particular melds into the background on anything vaguely gray.

**Comment by dootdoom** [comment]
ew

**Comment by Twaticus** [comment]
colors feel very muddied, not an improvement sorry

**Comment by maxymax13** [comment]
the colors are the exact same though :(

**Comment by scarwolff** [comment]
precisely

**Pull request closed without merging**
