### PR TITLE
Adds stungloves to tgstation

### PR DESCRIPTION
**Pull request by optimumtact**
As a mutation braindead people can ask for

:cl: oranges
add: Added stungloves to the brain damage lines
/:cl:

I think this will really Cheer Cheri up.

### CODE REVIEW

**Comment by calzilla1** [comment]
WE BANNED YOU FOR A REASON

**Comment by ShizCalev** [comment]
these fucking memes are too much

**Review by Cyberboss — APPROVED** [review]

**Comment by Cheridan** [comment]
:(

**Comment by Niknakflak** [comment]
these are getting old

**Pull request merged**
