### PR TITLE
[MDB Ignore] Combines Cargobus consoles with Dept. Order Consoles, freeing all departments of 1 whole tile of space

### PR DESCRIPTION
**Pull request by MrMelbert**
## About The Pull Request

- Departmental orders are now an NTOS app
   - To download, they require `ACCESS_COMMAND`.
   - To use, they require one access from the department.
       - This means you cannot order things from not-your-department unless you have an ID. 
   - When newly downloading the app, it will prompt a head of staff to insert an ID, to determine which department to be linked to.

- Changes chat room overlay from the kind that AI uploads use to a new icon. 

- Minor refactors to department order in general. 

image

image-1

## Why It's Good For The Game

These two computers are surprising waste spacers for two things which are tied together. 
So why not combine them?

The lesser used cargobus chat is still there, and departmental orders are front and center. 

This gives mappers a ton more leeway when mapping departments out and is overall less clutter.

## Changelog

:cl: Melbert
qol: Cargobus chat console and Departmental Order console are now combined into one. 
qol: Mod PCs active on the "chat client" apps no longer look like AI uploads (and now have their own sprite) 
refactor: Departmental order consoles were refactored a bit, report any oddities. 
/:cl:

### CODE REVIEW

**Comment by Paxilmaniac** [comment]
With this single extra free tile in each department I can now turbo powergame in a really specific and annoying way that will provide me zero net benefit 👍

**Comment by san7890** [comment]
if only we still had kilo

**Comment by zxaber** [comment]
It seems to me that both of these functions could exist on modular PCs. For the order console, we would tie to the access that an inserted ID has, and we could just move the cargo chats into the existing chat program.

**Comment by MrMelbert** [comment]
> It seems to me that both of these functions could exist on modular PCs. For the order console, we would tie to the access that an inserted ID has, and we could just move the cargo chats into the existing chat program.

You should look at the code 😉

**Comment by Elli-Skala** [comment]
> balance: You can't order from Departmental Order consoles without having the required access to.

Is this balance?  I thought this was already a thing?

**Comment by MrMelbert** [comment]
> > balance: You can't order from Departmental Order consoles without having the required access to.
> 
> Is this balance? I thought this was already a thing?

...Was it already a thing? I guess I cam remove that

**Comment by Loafin34** [comment]
does this mean as atmos techs we would have to ask the chief engineer to order BZ? what if it's lowpop? will we have to get command access from captain/hop to order stuff for free?

**Comment by Jacquerel** [comment]
Fix map conflict and we're probably good

**Pull request merged**
