### PR TITLE
Adds integrated jetpack to Captain's hardsuit

### PR DESCRIPTION
**Pull request by Spess-Rando**
:cl: Sligneris
add: Integrated jetpack has been added to Captain's SWAT armor
/:cl:

With this, the Captain would be able to use an integrated jetpack like HoS and CE without stealing from CE's locker or pestering the miners.

### CODE REVIEW

**Comment by optimumtact** [comment]
Strongly opposed, contributes further to hardsuit power creep

**Comment by kevinz000** [comment]
@optimumtact They're the only space gear other than crappy EVA suits, what else would get buffs? They even slow you down indoors...

**Comment by InsaneHyena** [comment]
Power creep.

**Comment by xxalpha** [comment]
Honestly, if there's any hardsuit that should have them it's the Captains.

**Comment by GunHog** [comment]
Captain already gets compact jetpack which he can put away, similar to Nuke Ops. 

Then again, it would be a matter of choice: A fast jetpack he can put away easily, or a slow jetpack built into his suit. He is the Captain, and should always have the best.

**Comment by Anonmare** [comment]
Disagree tbh. I don't think anyone but the CMO should have an integral jetpack hardsuit but that's out of the scope of this PR

**Comment by Shapsy** [comment]
No one should have integral jetpacks by default (and why the CMO of all people?)

**Comment by Niknakflak** [comment]
Nonsense, the HoS has it, no reason to have the FINAL BOSS of the station without the same kind of buff the HoS has lmao, come on guys it's basic science

**Comment by XDTM** [comment]
CE has it guys

**Comment by PKPenguin321** [comment]
>*other thing* is stupid so we should keep adding more *stupid thing*

Powercreep 101

**Comment by xxalpha** [comment]
It's the captain, the most buff role in the station.

**Comment by KingPhilipIII** [comment]
Nerf Captain 2017.

**Comment by Militaires** [comment]
>thumbing up own pr

**Comment by LanCartwright** [comment]
The captain should not be the most powerful person on the station.

**Comment by Sligneris** [comment]
>The captain should not be the most powerful person on the station.
Um, isn't that exactly what the captain is?

**Comment by Sligneris** [comment]
>The captain should not be the most powerful person on the station.

Um, isn't that exactly what the captain is?

**Comment by coiax** [comment]
> thumbing up own PR

That's nothing, CHECK THIS OUT

**Comment by coiax** [comment]
@Sligneris I don't care about "muh hardsuit power creep", I agree that it's odd that the CE and HoS have builtin jetpacks, but not the captain.

But.

The captain has his special TRAITOR ITEM PLZ STEAL ME jetpack. It even fits in a backpack, unlike 90% of jetpacks. What about the poor golden jetpack? :(

**Comment by LanCartwright** [comment]
> Um, isn't that exactly what the captain is?
No, the HOS is meant to be the final boss, the robustest of the robust, the guy that's hardest to kill, the guy that confronts you or you have to confront.

The Captain is a figurehead, the buffer and the protector of his key card and his disk. He isn't meant to fight as much as he's meant to run and stay out of danger.

**Comment by Sligneris** [comment]
> No, the HOS is meant to be the final boss, the robustest of the robust, the guy that's hardest to kill, the guy that confronts you or you have to confront.

... Except not really?

Ever since the old days, Captain has the highest armor values, the best equipment, including a self-rechargable laser that no one else gets roundstart...

HoS is a right hand man, HoS is [The Dragon](http://tvtropes.org/pmwiki/pmwiki.php/Main/TheDragon). But HoS is definitely not the final stand.

**Comment by PKPenguin321** [comment]
We have a horrible habit as a code base to make rare and unique items easily obtainable or given away for free roundstart like this "because this other thing has it so why can't this thing?!"
Maybe it would be easier to just remove inbuilt jetpacks and stop adding rare/unique items

**Comment by LanCartwright** [comment]
He had above average protection against ranged weapons but was limited to chest protection. And a lack of combat equipment (two laser weapons and a telebaton). 

The HOS had shields, the armoury, better weapons, and an armour that covers the whole spectrum of defense.

The Captain is only to fight as a last resort; it's his job to keep moving and not lose his items. The captain is the final stand because he's meant to be the slippery one.

**Comment by Sligneris** [comment]
Being meant to be slippery all the more justifies an integrated hardsuit jetpack then, given that moving in space outside the station is very well a part of that.

**Comment by Kromgar** [comment]
Captains jetpack doesnt fit in bacpacks

**Comment by GunHog** [comment]
https://github.com/tgstation/tgstation/blob/22949887a768bcf9629d3a0d2e9105175696b7d7/code/game/objects/items/weapons/tanks/jetpack.dm#L113

It does.

**Comment by FantasticFwoosh** [comment]
Basically the ability to steal a high grade suit of armor & a jet-pack simultaneously for your traitor objective (if that counts) within the first 2 minutes of the game if you're really professional in breaking and entering the captains quarters or happen to dunk the cap.

**Comment by optimumtact** [comment]
At this time we'd prefer jetpacks are left as bulky items, integrated jetpacks were a mistake

**Pull request closed without merging**
