### PR TITLE
Vareditable harm alarm cooldowns

### PR DESCRIPTION
**Pull request by silicons**
This is a horrible idea but consider it a refactor.

### CODE REVIEW

**Comment by PKPenguin321** [comment]
make the sound vareditable too? maybe even the message while we're here

**Comment by lzimann** [comment]
The bad idea would be abuse it. But having things like this a variable(or a define) instead of a loose number is way better for maintability.

**Comment by ExcessiveUseOfCobblestone** [comment]
Funny harm alarm sounds with the round's meme is hilarious admins are not evil STOP!

**Comment by Cyberboss** [comment]
Badmin creep

**Comment by Haevacht** [comment]
Evil genius at work. I should play more eggborg.

**Comment by Anonmare** [comment]
Fuck Normies alarm when?

**Comment by KorPhaeron** [comment]
>adding 6 new vars to facilitate sound spam

cease

**Pull request closed without merging**
