### PR TITLE
this isn't funny i'm locked in the least fun room in the fucking map

### PR DESCRIPTION
**Pull request by Iamgoofball**

### CODE REVIEW

**Comment by Bawhoppen** [comment]
its a forced meme

**Comment by Kraseo** [comment]
imagen

**Comment by Bawhoppen** [comment]
stop letting people in on it go away

**Comment by GunHog** [comment]
And this goes right next to the guy who did not know about carbon dioxide!

**Comment by ExcessiveUseOfCobblestone** [comment]
i think the cultists are metacomming

**Comment by KingPhilipIII** [comment]
I approve wholly of this meme.

**Pull request merged**
