### PR TITLE
Removes a horrid description

### PR DESCRIPTION
**Pull request by Bawhoppen**

### CODE REVIEW

**Comment by frtbngll** [comment]
Why are you removing the Problem Sleuth memes m8?

**Comment by MMMiracles** [comment]
muh grandfathered references

**Comment by Dorsisdwarf** [comment]
If you must change this, change it to **can be found in any good detective's hat**.

You know, because it is.

**Comment by Bawhoppen** [comment]
why did you close this?

**Comment by Bawhoppen** [comment]
The reason I don't want this to be in the description, is because it is a completely nonsensical OOC message, and I want to keep the feature kind of secret actually

**Comment by Hatfish** [comment]
If you really want to remove some horrid descriptions you should start with the proto-kinetic accelerator.

**Comment by Bawhoppen** [comment]
nothing horrid about that one

**Pull request closed without merging**
