### PR TITLE
Adds a new role-restricted item to the Bartender's uplink: Lethals.

### PR DESCRIPTION
**Pull request by dessysalta**
## About The Pull Request

Hey you. Yeah, you. Did you just serve someone a drink, only to be asked 'can I give Pun Pun to the chef'? If yes, do you also happen to be the Traitor antagonist? Well, you're in luck! For the low price of 4 TC (and a little bit of reputation, let's say 300) you can now blow that scummy monkey-killing bastard back to Terra and teach them to mess with you.

**READ:** Adds a role-restricted item to the bartender's traitor uplink, a box of 7 lethal (buckshot) rounds.

## Why It's Good For The Game

I think bartender is a role that, while fun as a traitor, deserves their own role-restricted item--the chaplain, mime, clown, janitor, and a good many other roles have their own, so let's add the bartender to the mix. Past that, having the lethality of a revolver with the style of a double-barrel is nifty; the box of lethals doesn't really get used besides in an away mission or space ruin here and there, and finally, I think it makes sense for traitor bartenders to ask the Syndicate for a box of real, chest-hair buckshot rounds.

## Changelog

:cl:
add: Adds a box of lethal shotgun shells to a bartender's traitor uplink.
/:cl:

### CODE REVIEW

**Comment by necromanceranne** [comment]
Why am I buying 7 shots of buckshot for one TC each over just making some improvised shot for free? Or spending that TC on a Makarov that does comparatively similar damage at longer ranges for the same price?

Buckshot was badly gutted damage wise as well as removed from printing. It's only redeeming feature currently is wounding power, and that is still overshadowed by improvised shells doing that and are almost _entirely free_.

**Comment by EuclidianGeometer** [comment]
i think the idea of a bartender traitor item is fun, but this one seems quite weak, especially for the price you've set it at. the bartender can get an autolathe pretty easily- i /think/ service can print the board, but if not, you have enough fair reasons to ask for one that cargo or engineering or science should cough up the board pretty easily- and then you have access to as many normal shells as you want, and that's not even counting the pretty good improvised ones.

I think a bartender item should be more along the lines of something to do directly with the bartending. i know goon has a shot glass that's actually a 50u beaker you down all in one shot as a traitor item for their bartender, for example, which allows you to easily poison someone all in one go (even with normal alcohol, given the strength of some of these drinks.)

**Comment by dessysalta** [comment]
> i think the idea of a bartender traitor item is fun, but this one seems quite weak, especially for the price you've set it at. the bartender can get an autolathe pretty easily- i /think/ service can print the board, but if not, you have enough fair reasons to ask for one that cargo or engineering or science should cough up the board pretty easily- and then you have access to as many normal shells as you want, and that's not even counting the pretty good improvised ones.
> 
> I think a bartender item should be more along the lines of something to do directly with the bartending. i know goon has a shot glass that's actually a 50u beaker you down all in one shot as a traitor item for their bartender, for example, which allows you to easily poison someone all in one go (even with normal alcohol, given the strength of some of these drinks.)

These are good points; I honestly was just worried my PR would get insta-denied because 4tc buckshot sounded strong. It doesn't take much to buy a few boxes and then just unload them into whatever and whoever.

That being said, I'm not much of an actual coder (maybe that'll change in time) and so a more concrete bartender Syndie item is out of my league for now. That also being said, I had an idea for a shaker that looks identical but can synthesize deadly chemicals--something in that realm.

Anyways, I'm gonna change this to be cheaper given both of the comments I've gotten. 4 sounds good given it's the same price of the .357 speedloader; its about the same damage too. I dunno, I guess I was just paranoid.

**Comment by SkeletalElite** [comment]
> Anyways, I'm gonna change this to be cheaper given both of the comments I've gotten. 4 sounds good given it's the same price of the .357 speedloader; its about the same damage too. I dunno, I guess I was just paranoid.

a big part of the value of the speedloader is actually the reusable loader itself.

You can print more .357 ammo but it normally has to be loaded 1 shot at a time. The speedloader lets you quickly load 7 more shots. I'd honestly go even lower and put it at 3.

**Comment by dessysalta** [comment]
> > Anyways, I'm gonna change this to be cheaper given both of the comments I've gotten. 4 sounds good given it's the same price of the .357 speedloader; its about the same damage too. I dunno, I guess I was just paranoid.
> 
> a big part of the value of the speedloader is actually the reusable loader itself.
> 
> You can print more .357 ammo but it normally has to be loaded 1 shot at a time. The speedloader lets you quickly load 7 more shots. I'd honestly go even lower and put it at 3.

Maybe! I'll wait for feedback from either a maintainer or headmin before I lower it (if I even do lmao).

**Comment by Jackal-boop** [comment]
Spit ballin here. Lower the price to 5 TC and give it 3 dart shells with a 50u capacity.

**Comment by Wallemations** [comment]
Arguably the bartender TC item is an emag, since you can emag the booze dispensers to get fake beer & more for poison.
Sure it's not the most lethal thing but you can do some interesting stuff with it.

Either way I feel just giving them a couple rounds of buckshot is a little boring.

**Comment by MMMiracles** [comment]
a double-barrel speedloader (these actually exist for the type of shotgun the bartender uses) and like 4-6 lethal shells for 5-6 TC would be a decent bundle choice tbh

**Comment by necromanceranne** [comment]
> a double-barrel speedloader (these actually exist for the type of shotgun the bartender uses) and like 4-6 lethal shells for 5-6 TC would be a decent bundle choice tbh

I know what you're talking about but I think those only work with a single barrelled gun.

Mechanically for our sake, that's basically just turning the double-barrelled shotgun into a riot shotgun. Not super interesting, but entirely doable.

**Comment by Serxule** [comment]
i dont think a speedloader is really worth it unless the box comes with 7 of the speedloaders instead of 7 lethals solo

**Comment by Mothblocks** [comment]
booooring. i dont like it

**Pull request closed without merging**
