### PR TITLE
Deletes magic armor

### LINKED ISSUE #34931: "magic" damage flag apparently exists and is used but no item provides magic armor
Discovered during armor datums testmerge, magic was not implemented for armor datums. It has silently failed before. 

I have added it to armor datums, however using it doesn't require armor datums to get merged. Just add an item in the armor list that says magic = <whatever>. Perhaps someone should add magic armor to items like inquisitor/DS/gem-encrusted hardsuits, wizard robes, something else?

### PR DESCRIPTION
**Pull request by JohnFulpWillard**
## About The Pull Request

lord forgive me for doing a good first issue
I did not know this was a thing until I saw the issue on it and thought "no way that still exists, that issue is 3 years old", but GUESS what.

## Why It's Good For The Game

Closes #34931 and removes a useless and unused armor value.

## Changelog

Not needed, this changes absolutely nothing in-game.

### CODE REVIEW

**Comment by Fikou** [comment]
bro how else will i protect myself from magic projectiles

**Comment by necromanceranne** [comment]
Ah yes magic armor that thing that...does...

**Comment by Iamgoofball** [comment]
Since nothing provides magic armor, this means things don't get blocked by armor when they have the magic flag. You are, in fact, making armor impact a bunch of stuff it previously didn't. Can you add 100% armor pen to those projectiles?

**Comment by ATH1909** [comment]
alternatively, we could give magic armor to, like, religious robes and the berserker hardsuit

**Comment by necromanceranne** [comment]
> Since nothing provides magic armor, this means things don't get blocked by armor when they have the magic flag. You are, in fact, making armor impact a bunch of stuff it previously didn't. Can you add 100% armor pen to those projectiles in replacement to avoid a balance chance from occuring?

You know I hadn't considered this but actually you're right, this define existed as a shit way to mark magic projectiles as 'ignore armor'. Which technically doesn't make it useless, but it sure isn't the best way to do this lol.

**Comment by JohnFulpWillard** [comment]
> 
> 
> Since nothing provides magic armor, this means things don't get blocked by armor when they have the magic flag. You are, in fact, making armor impact a bunch of stuff it previously didn't. Can you add 100% armor pen to those projectiles in replacement to avoid a balance chance from occuring?

They seem to already all have 100% armor penetration

**Review by ShizCalev — APPROVED** [review]

**Pull request merged**
