### PR TITLE
Fixes unused shuttles being available in the game

### PR DESCRIPTION
**Pull request by Iamgoofball**
https://tgstation13.org/phpBB/viewtopic.php?f=33&t=9109#p241267

no point in supporting unused content

remember when I said this would happen :^)

# blame the admins listening to forum warriors, not me

### CODE REVIEW

**Comment by optimumtact** [comment]
seems reasonable

**Comment by Iamgoofball** [comment]
remember guys if you want something removed, stop playing for a few weeks then bitch on the forums

**Comment by Armhulen** [comment]
Delete emergency_luxury.dmm

:((((((((((((((((((((((

**Comment by Iamgoofball** [comment]
1. no
2. don't pretend
3. stop pretending

**Pull request closed without merging**
