### PR TITLE
DisplayTimeText mk2

### PR DESCRIPTION
**Pull request by ShizCalev**
Closes #30940

This one gives better time readouts, per the suggestion by @ChangelingRain 

c69bqq5
dhfmxr1

### CODE REVIEW

**Comment by ChangelingRain** [comment]
Obviously, I prefer this one.

**Comment by MrStonedOne** [comment]
I doubt we need to display fractions of a second.

**Comment by Jordie0608** [comment]
Unless this'd be used for bans I can't think of where we'd need to count days.

**Comment by ShizCalev** [comment]
This look fine?

From;
we3ps4m

to 
vz5gukq

**Comment by optimumtact** [comment]
huh how has it gone from 1 minute to 4 minutes?

**Comment by ShizCalev** [comment]
I ended the rounds at different times.

**Comment by ShizCalev** [comment]
Oranges saying that pointed out that the shift duration being shown was incorrect to begin with, gg.

**Pull request merged**
