### PR TITLE
Adds type checks to HUD alert clicks to prevent ghosts from causing runtimes

### PR DESCRIPTION
**Pull request by silicons**
title

### CODE REVIEW

**Comment by Cyberboss** [comment]
How are ghosts even getting these alerts?

**Comment by lzimann** [comment]
this isn't the fix

**Comment by RemieRichards** [comment]
@Cyberboss probably from observing people who get the alert, Observe (not orbit) you inherit their UI.

**Review by Cyberboss — CHANGES_REQUESTED** [review]
Just make observer/can_resist() return FALSE

**Comment by kevinz000** [comment]
fixing in a few hours

**Comment by kevinz000** [comment]
yes mom i fixed it

**Pull request merged**
