### PR TITLE
Adds 1 more pellet to rubbers and buck

### PR DESCRIPTION
**Pull request by LanCartwright**
i never asked for this
do not blame me
:cl:
tweak: Shotguns shells now have one extra pellet.
/:cl:

### CODE REVIEW

**Comment by WJohn** [comment]
:+1: 
More viable now.

This buffs the buckshot at point blank from 75 to 90, which makes it a fair upgrade over the slug's 60, and more usable against crowds/at range.

Don't remember the rubber's stats but yeah, that's a bit more viable now too.

**Comment by kilog** [comment]
Sounds pretty balanced. More variation, anyways.

**Comment by Zilenan91** [comment]
@WJohn If these all hit the same limb the bleeding damage will kill somebody in under a second

**Comment by tkdrg** [comment]
Good, getting shotgunned to the face point-blank *should* hurt.

**Comment by Lumipharon** [comment]
err, dunno if insta kill should is a good idea, considering how easy it is to get... Oh well.

**Comment by tkdrg** [comment]
It's only instacrit at point blank. It was already >60 damage anyway, so this isn't that much of a difference, I think?

**Comment by Zilenan91** [comment]
It was 75 before

**Comment by WJohn** [comment]
Yeah this isn't an instacrit unless you're already hurt a bit. This makes a point blank buckshot shell 90 damage, and keep in mind you basically have to be clicked on for this to happen. You gotta be *really* bad at the game to let that happen.

Besides, we already have slugs which could reliably two shot you at a distance, so this just makes it usable.

**Comment by Zilenan91** [comment]
Well yeah theoretically it doesn't 1 shot you, but if they all hit the same limb and you have no armor you'll bleed out in seconds so it's basically an instant crit. I still don't have a problem with it though because bullets aren't perfectly accurate.

**Pull request merged**
