### PR TITLE
Update stale.yml

### PR DESCRIPTION
**Pull request by MrsTonedOne**

### CODE REVIEW

**Comment by Iamgoofball** [comment]
this isnt going to fly

**Comment by optimumtact** [comment]
What is your problem? I was already closing stale pr's faster than this, it's actually a relaxing of the previous level of closing.

**Comment by MrStonedOne** [comment]
If there was an option to disable closing, I would use that, but its currently in a pr on the actions repo that has spent 5 months with approval but no merge. (sound familiar)

My issue is the automatic closing of stale prs without a method that allows the user to re-open the pr themselves.

If the correct action to take on a pr was merge (like it was with #50422), it should not be getting closed, it should be getting merged.

If you'd like, I would be more than happy to include such functionality on the tools domain, a simple page where users auth to github then can re-open any of their closed prs that were closed by the github actions bot.

**Comment by optimumtact** [comment]
I appreciate your response, however, I do not feel that it a major issue for someone to have to open a new PR if their one is closed for being stale.

#50422 is an oversight, it was missed, that happens from time to time, but not enough to need any such drastic action.

`If you'd like, I would be more than happy to include such functionality on the tools domain,`

I appreciate the request, but unless the majority of maintainers indicate otherwise, we will be sticking with the current process, and I would appreciate you abiding by the decision instead of being a dick about it.

**Pull request closed without merging**
