### PR TITLE
tgui-next focus works more similarly to elder-tgui

### PR DESCRIPTION
**Pull request by sohpeach**
## About The Pull Request
This PR means that tgui-next windows can be scrolled without focusing them (on Windows 8.1+) ~~and that focus is not taken from the game when opening tgui-next windows.~~

The reason that an internal HTML element needs implicit focus is because tgui-next has its own scrollbar-sort-of-system that is deeper than the root HTML document. Scroll events will not be passed to it until it is focused.

If you don't know what I mean by focus, atm if you open a tgui-next window your movement keys will stop working (and other keys.)

## Why It's Good For The Game
This makes tgui-next behave the same as tgui, also I want to be able to scroll down tgui-next windows without clicking on them.

## Changelog
:cl:
fix: tgui-next interfaces can be scrolled without clicking on them on Windows 8.1+ and higher.
/:cl:

### CODE REVIEW

**Comment by actioninja** [comment]
Windows taking focus when opened is intentional.

**Comment by willox** [comment]
It's not intentional because tgui doesn't do it.

**Comment by MCterra10** [comment]
I agree, scrolling inactive windows a standard feature on all modern operating systems and I see no reason why this could "intentionally" be disabled

**Review by stylemistake — APPROVED** [review]
Looking good. Thanks for PR.

**Comment by willox** [comment]
I'd like to point out where old-tgui has a similar piece of code to relinquish focus back to the map:

https://github.com/tgstation/tgstation/blob/642c9b2/tgui/src/tgui.ract#L52

This is simply a change that makes tgui-next emulate old-tgui more properly.

**Comment by willox** [comment]
after a discussion with @actioninja i've removed the change to not steal focus from the game map. tgui-next should eventually have interfaces with hotkeys that make this ideal behaviour and i'm personally only really concerned about being able to scroll on interfaces without clicking them.

**Review by actioninja — APPROVED** [review]

**Pull request merged**
