### PR TITLE
Removes some questionable AI names

### PR DESCRIPTION
**Pull request by githubuser4141**
## About The Pull Request

Removes/rewords some of the possible AI name rolls.

## Why It's Good For The Game

Edits out questionable AI names that probably aren't wholesome considering we're a 4chan server "TG == Traditional Games/Gaming". I probably missed some so I'll come back to this later when I've had some coffee

:cl:
del: Changes AI .txt names
/:cl:

### CODE REVIEW

**Comment by dragomagol** [comment]
No comment on the contents of the PR, but names need to be alphabetized.

**Comment by junkgle01** [comment]
B166ER is a reference to the Matrix, not a slur reference. Why did you remove "Fum"? What's inappropriate about that?

**Comment by BlueMemesauce** [comment]
> B166ER

think of the letter "C"

**Comment by junkgle01** [comment]
> > B166ER is a reference to the Matrix, not a slur reference. Why did you remove "Fum"? What's inappropriate about that?
> 
> think of the letter "C"
 
 But there's no joke in that. It literally just replaces "C" with "F". It makes no sense, so that's why i'm doubting it's even referencing that at all.

**Comment by dragomagol** [comment]
> > B166ER is a reference to the Matrix, not a slur reference. Why did you remove "Fum"? What's inappropriate about that?
> 
> think of the letter "C"

If it's because it sounds like "cum" that's very silly

**Comment by junkgle01** [comment]
> > > B166ER is a reference to the Matrix, not a slur reference. Why did you remove "Fum"? What's inappropriate about that?
> > 
> > 
> > think of the letter "C"
> 
> If it's because it sounds like "cum" that's very silly

Exactly!!

**Comment by Mothblocks** [comment]
these are insane stretches

**Pull request closed without merging**
