### PR TITLE
brain swap from delimber anomaly doesn't kill you

### LINKED ISSUE #66840: Delimber anomaly can round remove you
Reporting client version: 514.1583

## Round ID:
182897

## Testmerges:
- [Optimizes Runechat](https://www.github.com/tgstation/tgstation/pull/65791)
- [Dynamic 2022, Part 1 - Redesigning midround rolls (Midrounds happen far more frequently now, and scale their power over time)](https://www.github.com/tgstation/tgstation/pull/65997)

## Reproduction:
Stand near delimber anomaly
Have your brain qdel'd and replaced with a soul/mind-less nightmare/alien/other brain
Removed from round :)

### PR DESCRIPTION
**Pull request by Ghilker**
## About The Pull Request
fix #66840 by removing the ORGAN_VITAL flag if present

## Why It's Good For The Game
fix getting round removed

## Changelog

:cl:
fix: brain swap from delimber anomaly doesn't kill you
/:cl:

### CODE REVIEW

**Comment by VladinXXV** [comment]
untested code moment?
image

**Comment by VladinXXV** [comment]
image
This does not fix the bug.

**Comment by VladinXXV** [comment]
The issue isn't that the anomaly kills you (thought it does, eventually). The issue is that you are qdel'ing my brain to replace it with another one, and now my mind doesn't exist.

**Comment by VladinXXV** [comment]
Also the fact that you can get basetype organs (organ/implant/cyber), xeno larvae, and PROBABLY romerol tumors (I haven't confirmed this one yet).

**Comment by zxaber** [comment]
Perhaps the brain should just be immune to being swapped out?

**Comment by Shadowflame909** [comment]
> Also the fact that you can get basetype organs (organ/implant/cyber), xeno larvae, and PROBABLY romerol tumors (I haven't confirmed this one yet).

should of been a whitelist and not a blacklist tbqh

When you can get EVERYTHING in the game. eventually someones gonna get something they shouldn't of gotten. Like colossus's throat, or romerol, or an admin-only race's arm.

**Comment by MrMelbert** [comment]
i am pretty sure this either
1. doesn't fix the bug (as evidenced by vladin's comment
2. isn't the correct fix even if it did

you may have to blacklist brains entirely, either that or find out why it's really deleting minds/brains

**Comment by Ghilker** [comment]
I'll close this for now since I'm pretty busy and don't have time to code for a while, will fix this when I have time

**Pull request closed without merging**
