### PR TITLE
Fixes transitions

### LINKED ISSUE #31050: Unable to fly off station sector
Round ID: 76664
Server revision compiled on: 2017-09-27
The following pull requests are currently test merged:
#31034: 'Nightmare organ' by KorPhaeron at commit b6fa79
Based off origin/master commit: b0dd98

Jetpacking north, south, east or west all resulted in getting back to station sector (2), used GPS to verify.

### PR DESCRIPTION
**Pull request by AnturK**
Fixes #31050

### CODE REVIEW

**Review by Cyberboss — APPROVED** [review]

**Comment by newfren** [comment]
Hi friend Anturk does this also fix being able to fly into the lavaland Z-level from space?

**Comment by AnturK** [comment]
Yes, all transitions are shifted with this, so lavaland gets space one instead.

**Comment by KorPhaeron** [comment]
Speedmerging because its a one line change that will prevent significant admin hassle constantly fishing people from lavaland

**Comment by Xhuis** [comment]
Dammit, z-code. Thanks for fixing this! I'm kind of a little dense when it comes to z-code so I wasn't sure how to do it myself.

**Pull request merged**
