### PR TITLE
New Flash bang sounds (OW FUCK MY EARS edition)

### PR DESCRIPTION
**Pull request by Cuboos**
Created a new flashbang sound and a ringing effect for when you go deaf, very realistic, it's almost like your ears are actually bleeding (NOTE: that is a joke, this isn't actually a painful sound, i checked)

### CODE REVIEW

**Comment by RemieRichards** [comment]
does this ever actually stop?

**Comment by Zilenan91** [comment]
Can we not add a sound that makes people feel physical pain thank you.

**Comment by Cuboos** [comment]
@Zilenan91 did you actually read the PR? I said it doesn't pay attention! And seriously, it doesn't...

**Comment by Chocobro** [comment]
flashbang sound made me jump, flash_ring didn't cause any pain from the frequency. it's also in a range that's safe for human ears. i'm using headphones.

**Comment by Jordie0608** [comment]
Sounds a bit more a heavy blunt impact than a flashbang but it's definitely better than before.
There's some audible buffeting in flash_ring which I'm not sure is intentional, sounds alright however.

**Comment by Cuboos** [comment]
It's suppose to be "muffled noise" since Byond can't actually muffle sound.

**Comment by Cuboos** [comment]
Also these were my other two attempts, but Coderbus didn't like them 
https://dl.dropboxusercontent.com/u/9654207/flashbang.wav
https://dl.dropboxusercontent.com/u/9654207/flashbang2.wav

**Pull request merged**
