### PR TITLE
<coiax> kevinz000, can we talk about making catpeople a seperate race

### PR DESCRIPTION
**Pull request by Iamgoofball**
# if you can't beat them, join them

dreamseeker_2016-12-11_00-03-59

Pictured from right to left: Vulpkanin, Tajaran, Skrell, IPC

# Vulpkanin

Vulpkanin are a species of sharp-witted canine-pideds residing on the planet Altam just barely within the dual-star Vazzend system. Their politically de-centralized society and independent natures have led them to become a species and culture both feared and respected for their scientific breakthroughs. Discovery, loyalty, and utilitarianism dominates their lifestyles to the degree it can cause conflict with more rigorous and strict authorities. They speak a guttural language known as 'Canilunzt' which has a heavy emphasis on utilizing tail positioning and ear twitches to communicate intent.

# Tajaran
The Tajaran race is a species of feline-like bipeds hailing from the planet of Ahdomai in the S'randarr system. They have been brought up into the space age by the Humans and Skrell, and have been influenced heavily by their long history of Slavemaster rule. They have a structured, clan-influenced way of family and politics. They prefer colder environments, and speak a variety of languages, mostly Siik'Maas, using unique inflections their mouths form.

# Skrell

An amphibious species, Skrell come from the star system known as Qerr'Vallis, which translates to 'Star of the royals' or 'Light of the Crown'. Skrell are a highly advanced and logical race who live under the rule of the Qerr'Katish, a caste within their society which keeps the empire of the Skrell running smoothly. Skrell are herbivores on the whole and tend to be co-operative with the other species of the galaxy, although they rarely reveal the secrets of their empire to their allies.

# IPC

Positronic intelligence really took off in the 26th century, and it is not uncommon to see independant, free-willed robots on many human stations, particularly in fringe systems where standards are slightly lax and public opinion less relevant to corporate operations. IPCs (Integrated Positronic Chassis) are a loose category of self-willed robots with a humanoid form, generally self-owned after being 'born' into servitude; they are reliable and dedicated workers, albeit more than slightly inhuman in outlook and perspective.

# Q&A
## i dont like furry crap in my game
Too bad, you sound TRIGGERED!!! LOL!!!!
## this doesnt fit the theme
Too bad, you sound TRIGGERED!!! LOL!!!
It's just cosmetic, why are you complaining? Why do you get to tell people how to play?
## these are unoriginal
No they aren't they have LORE
## this is just because you're :salt: over petting
Not really. The way I see it, if we can add those cosmetic RP features what's wrong with this cosmetic RP feature?

### CODE REVIEW

**Comment by kevinz000** [comment]
fuck you shitty golfball

**Comment by dannno** [comment]
why aren't you gitbanned yet

**Comment by Armhulen** [comment]
i enjoy golfballs

**Comment by coiax** [comment]
You haven't actually ported them though. Also atomize your PRs.

**Comment by Haevacht** [comment]
what attempt is this, number 7?

**Comment by WJohn** [comment]
i've lost track

**Pull request closed without merging**
