### PR TITLE
Removes mining scanner

### PR DESCRIPTION
**Pull request by Core0verload**
This PR removes the mining scanners and replaces them with old mode mesons. Because with autoscanner being default option, there isn't much difference between these two, and inventory clutter is always bad.

You can now use multitool or t-ray scanner for stopping gibtonite reactions. Same with mining drone modes. A multitool is added to mining lockers, because it's also useful for cracking abandoned crates. Yes, I know abandoned crates multitool printout is broken, but I'll fix it later.

It also adds 3 new ore sprites to make ore less repeating. One for iron ore and two for uranium ore.
mining

### CODE REVIEW

**Comment by TechnoAlchemisto** [comment]
Okay but... "remove inventory clutter" "but here is this item you need to stop gibtonite and change mining drone modes" it's the same amount of clutter? 

The mining tool was cool and unique, and the difference between the two is that one is better than the other hence the use of the voucher. 

An unnecessary change.

**Comment by Core0verload** [comment]
You only need a multitool if you use mining drones or gibtonite charges. If you just avoid gibtonite or let it explode in it's place, feel free to leave the multitool at base.

**Comment by Bawhoppen** [comment]
:-1:x:100: do you seriously not understand why the fuck we have these

**Comment by Core0verload** [comment]
Yes I don't. I would ask you why, but I know how "based" you ususally are, so I wouldn't get an answer.

**Comment by RandomMarine** [comment]
With this, any chucklefuck assistant can now stop the r0 gibtonite you just primed in escape.

**Comment by KorPhaeron** [comment]
Ergo added them so that the asteroid wouldnt be rainbow.

Dont really see the point in removing them either.

**Comment by duncathan** [comment]
>Yes I don't. I would ask you why, but I know how "based" you usually are, so I know I wouldn't get an answer anyway.

Bawhoppen btfo

**Comment by Bawhoppen** [comment]
its because its a nice thematic item that works to help balance out the job and flesh out it's mechanics, aswell as it should be only available to mining which will also limit who can fuck with gibtonite

**Comment by bgobandit** [comment]
:-1: for reasons everyone has said, plus when I port the bay/polaris drill I'll just have to re-add them

**Comment by KorPhaeron** [comment]
@bgobandit 

The what now?

**Comment by bgobandit** [comment]
Bay/Polaris has a giant-ass drill in several pieces that mines ore from underground, you use their mining scanners to find good places to set the drill up. they also have special ore types only findable underground

**Comment by PKPenguin321** [comment]
:+1: for the sprites though, those are cool

**Comment by ATDoop** [comment]
why not find more uses for the mining scanner instead? i think this is a bad idea. more sprites for ore is cool though.

**Comment by xxalpha** [comment]
Instead of removing a feature, just remove the code that spawns the items that trigger you.

**Comment by KorPhaeron** [comment]
@Core0verload 

Also the mining scanner works from your backpack

**Comment by Fox-McCloud** [comment]
>for reasons everyone has said, plus when I port the bay/polaris drill I'll just have to re-add them

Don't port that. It's literally no-skill easy mode and increases production for no reason at all without any risk.

Miners can quite literally set up the drill, turn it on, then go chit-chat or AFK for 30 minutes, then come back and have every type of mineral. 

I would know; we had them.

**Comment by bgobandit** [comment]
I was going to port it with modifications, such as if you leave it unattended it can cause lava spurts (for lavaland) and probably drop the rates of the ore you should really get from the asteroid instead.

**Comment by KorPhaeron** [comment]
I dislike this, please PR the multiple icons separately though

**Comment by Core0verload** [comment]
It wouldn't work well without the rest of PR, because the new icons lack the shitty scanner-specific "fade out" effect. And I generally lost interest in doing anything for mining with all that "we no longer support asteroid and you better suck it" stuff.

**Pull request closed without merging**
