### PR TITLE
Removes 10mm ammo

### PR DESCRIPTION
**Pull request by ghost**
:cl: iksyp
del: 10mm ammo has been universally phased out in favor of .45
add: The syndicate has decided to create new ammo types for .45, which include incendiary rounds, armor-piercing rounds, and hollow-point rounds. These are now being served in C-20r variants for nukeops.
tweak: all guns that previously used 10mm now use .45
spellcheck: the SMG magazine description in the uplink now correctly states the amount of rounds in one magazine.
/:cl:

because 10mm and .45 are functionally identical and have very little reason to be separate in my opinion.
this has balance implications and if you want to scream at me just comment below

### CODE REVIEW

**Comment by Wilchenx** [comment]
Either give the normal stetchkin 9mm ammo like it has in real life and like the other stetchkin has or this is retarded.

**Comment by praisenarsie** [comment]
what wilchen said

**Comment by JStheguy** [comment]
Ah yes, because it is utterly impossible for there to be a variant of a gun that is chambered in a different caliber from the original version. That never happens.

**Comment by iskyp** [comment]
9mm is much weaker than .45 and im not going to change the guns ammo for that reason

**Comment by iskyp** [comment]
>is bloat a concern

**Comment by ExcessiveUseOfCobblestone** [comment]
Ammo differences are important so when you add a mechanism to get ammo you don't have to have 500 balance discussions about "BUT WHAT IF THEY HAVE X GUN?!!!". Heaven forbid if you want to touch values on said ammo.

That's why i'm confused as to what "ammo bloat" is and why it's more beneficial to remove it rather than have those distinctions and simply not add more ammo types unless needed (The last item I recall that's even pertaining to ammo is tech shells, and those have unique functionality / pr'd forever ago).

**Comment by Shadowflame909** [comment]
I'm unsure if we want to give every gun the same ammo type boss.

**Comment by iskyp** [comment]
I'm not denying that ammo differences are important, but if two ammo types act functionally identical, then they don't need to be different. Here, for example, .45 and 10mm are functionally identical in game, but are separate ammo types for some reason. Meanwhile, .50 and 7.62 are different because they have different purposes.

**Comment by iskyp** [comment]
both 10mm and .45 are easily accessible (can be built in a hacked autolathe)
both 10mm and .45 do the same amount of damage
both 10mm and .45 are used in syndicate weaponry and non-syndicate weaponry
why is there a separation in the first place
it's not like 4.6 and 9mm, where 4.6 was made to prevent sec from mass-producing rounds from an autolathe

**Comment by epochayur** [comment]
>but if two ammo types act functionally identical, then they don't need to be different

literally incorrect

remember, if you want to put in a removal PR for no discernible reason, just say "muh bloat"

**Comment by Shadowflame909** [comment]
"muh powercreep" "muh slippery slope" now my real argument is, before you make a removal pr. At least finish the replacement. I want my hollow point. Reeeer

**Comment by ExcessiveUseOfCobblestone** [comment]
> both ammos are easily accessible
The ammo boxes, yes. Not the clips that would now become interchangeable across weapons that use such ammo.

>both ammos do the same amount of damage
Correct, we don't remove items based on this metric

>both 10mm and .45 are used in syndicate weaponry and non-syndicate weaponry
Same here

Maybe I'm just naturally drawn to the shed but I personally don't see a reason for this that outweighs the potential issues of having them being the same.

**Comment by iskyp** [comment]
>the clips become interchangeable
>clips
in all seriousness, magazines wouldn't become interchangeable, just the ammo inside of them would (i have to make the m1911 mag a separate type path tho because snowflake)

>we don't remove items based on having the same damage
of course not, but these shared enough in common that they really didn't need to be different in the first place

>potential issues
vague, please explain

**Comment by subject217** [comment]
Easy abuse of this change, I can reload a C-20r magazine for free instead of having to buy another or find a hacked autolathe just with the bunch of Stechkin magazines that spawn on the Syndicate Infiltrator. You'd also be giving incendiary, AP, and HP ammo to the C-20r, which only has ball ammo currently. Although the fact that you bothered to make incendiary ammo but think the other two are worthless says to me that you are way out of touch.
>The ammo boxes, yes. Not the clips that would now become interchangeable across weapons that use such ammo.

Could you give an example of this? This seems like a non-issue to me, interchangeable ammo doesn't mean they'll accept other magazines, and at any rate all you have to do is spam Z with the magazine in hand then use the other one to pick all the ammo up instantly.

**Comment by iskyp** [comment]
@subject217 that is a fair point, and the obvious solution is to remove the infiltrator
I realized that i probably should add the other two ammo types back in and will be doing so later

**Comment by subject217** [comment]
If you're not adding C-20r magazines as well then it becomes a loophole to get powerful ammo in a C-20r. I WOULD pay a bunch of TC for AP ammo in it, especially for war ops. If you ARE going to add C-20r magazines for these ammo types, then this becomes a balance change. It's almost like having the C-20r and the Stechkin use different ammo types is relevant for balancing nuke ops!

**Comment by iskyp** [comment]
i realized this would affect nukeops, it's kind of why i made this PR
i wanted to see how people would react to it

**Comment by subject217** [comment]
Should have a balance tag then, and you should have proper magazines for the C-20r, instead of hiding behind the cry of gunbloat.

**Comment by iskyp** [comment]
there's a difference between balance changes and tweaks with balance implications:
#37024 v. #36390

**Comment by ExcessiveUseOfCobblestone** [comment]
Haven't bothered to review the code (since i'm not a fan of it :^] ) to notice that special magazines have been given.

All of this to remove a perceived notion that """"""bloat""""" is silly though and I don't feel like contending the issue anymore when an actual issue has been presented and the immediate response to the well-made point was "well uh.... just remove it".

**Comment by improvedname** [comment]
@iskyp
Everything i can see between those two prs are

Oldman makes a nerf for cult which is just a buff in disguise in someway

Oldman buffs security

**Comment by subject217** [comment]
@improvedname His point is that one of them is big and marked as balance/rebalance and the other is small and is marked as tweak. Personally I think this lies in between those two in terms of balance significance and should still be marked as balance, but it doesn't matter.

**Comment by iskyp** [comment]
>the immediate response to the well-made point was "well uh.... just remove it".
>that is a fair point, and the obvious solution is to remove the infiltrator
>remove the entire infiltrator

I understand that sarcasm in text is hard to read at times but I thought it was pretty obvious I was joking here

anyways just got home time to finish pr

**Comment by YakumoChen** [comment]
the c20r is powerful and I don't think we should be putting free ammo for it anywhere for nuke ops

**Comment by Tlaltecuhtli** [comment]
shit pr

**Comment by iskyp** [comment]
alright I'm not getting any more fun out of people screaming in this pr

**Pull request closed without merging**
