### PR TITLE
Fixes the Blob being banished to the shadow realm

### LINKED ISSUE #38203: Blob falling into tear in reality creates an unending round state
Issue reported from  Round ID: 88778 (/tg/Station Sybil [ENGLISH] [US-EAST] [100% LAG FREE])

Reporting client version: 512

[Round ID]: Not really applicable, but 88778

[Reproduction]: If a blob is hit with a BoH bomb they fall into the tear in reality and can continue to expand to the limits of the new z-level, which is not enough to reach a victory state for the blob but makes it virtually unassailable by the crew, barring perhaps an extremely coordinated maxcap bombing which would have a high chance of failing. Given the right circumstances and server population this would effectively extend the round indefinitely, since the shuttle can't leave while a blob is alive - in the specific instance being reported admin intervention was required to remove the blob after even an eight-member deathsquad failed to destroy it.

### PR DESCRIPTION
**Pull request by CitrusGender**
[Changelogs]: # After years of evolving in bluespace environments, the blob figured out how to escape bluespace entrapment, but only barely.

I got the bright idea of adding the stationloving component to the blob core. This should follow the blob when it moves around the station with things such as the tear in the fabric of reality. Naksu's component code does a REALLY good job of making sure the object stays on the station, so I just wanted to make sure that the blob doesn't respawn after it's deleted or killed by preventing the forcemove with a new variable. This can be used for other things too.

https://feen.us/qn9y1ct1.mp4

:cl:
tweak: The blob core (and only the blob core) now respawns randomly on the station when the core is taken off z-level
fix: Prevents the round from going into an unending state
code: Added a variable to the stationloving component for objects that can be destroyed but not moved off z-level
/:cl:

[why]: # Fixes #38203  and is actually hilarious to watch. Also provides a disincentive (or incentive?) to BoH bombing the blob.

### CODE REVIEW

**Comment by davethwave** [comment]
Better than what it is now.

**Comment by PKPenguin321** [comment]
Only complaint is no more mining level blobs

**Comment by CitrusGender** [comment]
problem with that @vuonojenmustaturska  was that the blob wasn't able to be deleted via qdel (hence why I added it with the second commit.) I mean, we can do it like that but admins would have to delete the overmind to delete the blob and something about that sounds like a problem waiting to happen.

**Comment by CitrusGender** [comment]
>add PR only to revert it soon after
>red X now

okay

**Comment by Anonmare** [comment]
I play Reborn the Monster

**Comment by Shadowflame909** [comment]
why is this not merged ahh

**Review by SpaceManiac — APPROVED** [review]
Works in testing

**Pull request merged**
