### PR TITLE
Painkillers now actually induce analgesic effects

### PR DESCRIPTION
**Pull request by Absolucy**
## About The Pull Request

This adds a new trait, `TRAIT_ANALGESIA`, and makes various painkillers (+ tenacity trauma) apply said trait.

This prevents various pain-related effects, such as screaming due to pain, and also provides a speed bonus during surgery.

## Why It's Good For The Game

Gives more of an incentive to actually use reagents such as morphine or miner's salve.

## Changelog
:cl:
add: Painkillers (i.e morphine, miner's salve) now actually induce analgesic effects, preventing various pain-related effects, such as screaming due to pain, and also provides a speed bonus during surgery.
add: The tenacity trauma (traumatic neuropathy) also applies analgesic effects.
refactor: Simplified code related to reagents adding traits.
/:cl:

### CODE REVIEW

**Comment by Profakos** [comment]
This is very good and long overdue refactor. But there are some minor edge cases, or at the very least, this will prevent the terrifed status effect's from making you scream if you took some painkillers.

**Comment by Absolucy** [comment]
I very very much don't want to go through every single `emote("scream")` to add a HAS_TRAIT check to...

**Comment by Profakos** [comment]
That is fair.

**Comment by Absolucy** [comment]
Initially I was going through and adding unique messages to _every message related to hurting/pain_, but I realized it was too much effort for too little gain.

**Comment by optimumtact** [comment]
I'm not really comfortable increasing surgery speed even more without feedback from some experienced medbay players.

another way to structure it might be a slowdown + a speedup from painkillers to make it balance neutral.

@Mothblocks

**Comment by Higgin** [comment]
a slowdown without painkillers would make even tending with the current starting kit unreliable - improv surgery or floor surgery, in most settings where it happens, would be in shambles.

The way it's been offset elsewhere is that being unconscious gets you around the slowdown in a pinch, but this has a few problems even if it introduces a tradeoff (making yourself helpless to get better help:)

- it means you stare at a black screen and nobody gets to talk to each other (yes this also applies to the sleep part of my viro rework)
- it leads to the paradise or "guy with self-resp virus gets in cryo tube" bind of people saying "just sleep bro" which isn't terrible but is pretty nakedly gamey and unintuitive

Idk what you do to get around it - I don't personally feel it would hurt to speed up surgery a bit for the added effort of using a resource to remove pain on living people. A slowdown on the flipside would also give more reason to use the autopsy surgery for a buff even when tending (though I'm guessing this doesn't apply to the dead.)

no clear recommendations, just some thoughts, but happy to see this being developed

**Comment by DrAmazing343** [comment]
I'm not on some crazy balance stuff right now, but if there's a way to give the Numb quirk the non-screamy property for surgeries, I do know someone that would appreciate it. It makes sense, and has always been kinda odd.

**Comment by Eronymun** [comment]
I like the screaming change, now I can roleplay not being in pain when I crush myself with the airlock for fun.

**Comment by JackTrysGames** [comment]
But does this work with the Numb trait, which is supposed to make you completely unable to feel pain?

**Pull request merged**
