### PR TITLE
Improves bee lore

### PR DESCRIPTION
**Pull request by Iamgoofball**
see title

### CODE REVIEW

**Comment by KingPhilipIII** [comment]
Speed merge.

**Comment by Durkel** [comment]
fuck you

**Comment by meeeeme** [comment]
Really activates my almonds

**Comment by Iamgoofball** [comment]
requesting review from @bobdobbington

**Comment by ike709** [comment]
Goofball managed to steal FTL13's #2000

https://github.com/FTL13/FTL13/pull/2000

**Pull request merged**
