### PR TITLE
[Ready]New walking and turning sounds for the Ripley Mk. I and II, interaction sounds for the hydraulic clamp

### PR DESCRIPTION
**Pull request by InvalidArgument3**
## About The Pull Request

New movement sounds that only affect the Ripley power-loader, and a hydraulic clamp sound that plays when it is used to open doors, firelocks, and loading objects. 

https://streamable.com/3wjq2x Old
note: mech turning sounds are currently broken at the time of this PR being made
 
updated sound demo:
https://streamable.com/gi1iy5
with the rotation sound fix from #54529 
https://streamable.com/f4utrb
## Why It's Good For The Game

Makes the mech stand out more as a heavy-lifting utility device. Also it sounds cool.

## Changelog
:cl:
add: new Ripley movement sounds!
add: new hydraulic clamp interaction sounds!
/:cl:

### CODE REVIEW

**Comment by TheBonded** [comment]
>hydraulic clamp sound that plays when it is used to open doors, firelocks, and loading objects.
hydraulic clamps can be used to force doors open? does it act like jaws of life, opening powered doors too?

**Comment by Farquaar** [comment]
My personal opinion: I like the new sound, but it feels so... light?
It would be better if the mech sounded a bit heavier when it hit the ground. Right now it sounds like a person hitting their hand on a stack of binders.

**Comment by InvalidArgument3** [comment]
> > hydraulic clamp sound that plays when it is used to open doors, firelocks, and loading objects.
> > hydraulic clamps can be used to force doors open? does it act like jaws of life, opening powered doors too?

No, the clamp can't open powered doors like a jaws of life.


 

> My personal opinion: I like the new sound, but it feels so... light?
> It would be better if the mech sounded a bit heavier when it hit the ground. Right now it sounds like a person stomping a boot on a table or a stack of binders.

I think it fits. The ripley is a lightly armored exo-suit, but also it is missing the turning sounds which help a lot.

**Comment by Qustinnus** [comment]
it sounds way too light. the ripley is a lightly armored mech, that doesn't mean its as quiet as a ballet dancer. https://www.youtube.com/watch?v=FSrcMaid0mg

**Comment by InvalidArgument3** [comment]
Here it is on TGMC, with the turnsound properly playing.
https://streamable.com/1j4isb

> it sounds way too light. the ripley is a lightly armored mech, that doesn't mean its as quiet as a ballet dancer. https://www.youtube.com/watch?v=FSrcMaid0mg

That does sound a lot more interesting. I'll see what else works better

**Comment by InvalidArgument3** [comment]
https://streamable.com/gi1iy5

**Comment by ShizCalev** [comment]
just to be 100% clear here, whats the source of that new sound?

**Comment by InvalidArgument3** [comment]
> just to be 100% clear here, whats the source of that new sound?

The movement and rotating sounds are slightly tweaked from TGMC's power-loader,  and the clamp sound is a generic hydraulic sound effect from mechwarrior 4: mercenaries.

**Comment by InvalidArgument3** [comment]
https://streamable.com/f4utrb new NEW sound demo, this time with the rotation sound fix from #54529 merged

**Comment by githubuser4141** [comment]
> it sounds way too light. the ripley is a lightly armored mech, that doesn't mean its as quiet as a ballet dancer. https://www.youtube.com/watch?v=FSrcMaid0mg

The MK II isn't really 'lightly armored' even without upgrading it's armor it's a fair bit stronger then a gygax and it easily beats any other mech armor wise with all three goliath plates.

**Comment by Qustinnus** [comment]
im pointing out the source material

**Review by ghost — APPROVED** [review]
audio is good imo, lot better than what was there before.

**Pull request merged**
