### PR TITLE
Make SStgui actually read the html from the disk at runtime

### PR DESCRIPTION
**Pull request by Cyberboss**
Either fix this or the comment

### CODE REVIEW

**Comment by AnturK** [comment]
Why ?

**Comment by RemieRichards** [comment]
the comment isn't wrong.
'resource strings' are compile-time validated by DM, and then build into the RSC, when the user wants to view the UI, it's read from the RSC, which is a file, on disk.

if you MUST change something (you don't need to), then change/remove the comment.

**Comment by MrStonedOne** [comment]
No, with how this works, the actual html is not read from the user's cache, its joined with other shit and sent to the user via browse.

The `'` should be changed to `"`

In fact, for most html related things, I'd like to see these use fcopy_rsc, not ``, so that it's added to the rsc at world start, not compile time, so you don't need recompiles to change them.

**Comment by duncathan** [comment]
fix it properly as mso suggested imo

**Pull request merged**
