### PR TITLE
Autolathe produces items on top of itself

### PR DESCRIPTION
**Pull request by kingofkosmos**
Rather than it spitting the products at your feet.

Here you can see it in its natural environment:
autolathe

Also the Exosuit Fabricator now has a dir-variable so mappers can set its spitting direction. South is the default dir.

### CODE REVIEW

**Comment by Jalleo** [comment]
could you expand this at a later PR by letting the person set where it outputs stuff? like on top or to a tile beside it.
This change could work well for consistency but having a way for players to set it themselves in game feels like a nicer option.

**Comment by GunHog** [comment]
:+1: for autolathe, :-1: to Exofab for how annoying that would get due to how many items are pushed out during cyborg/mech jobs.

**Comment by palpatine213** [comment]
I agree with gunhog here. :-1: to exofab, :+1: to autolathe

**Comment by CorruptComputer** [comment]
Make it a var, so mappers can change the direction.

**Comment by PKPenguin321** [comment]
what gunhog said
and what corruptcomputer said if that's feasible

**Comment by Lumipharon** [comment]
neat.

**Comment by xxalpha** [comment]
Definitely make the exosuit fab spitting direction a var.

**Comment by Lumipharon** [comment]
You can Rotate many machines (sleeper, freezer, cryo etc), by screwdrivering then wrenching to rotate it.

Could you configure the exofab to do the same thing, only to effect the output direction, with a 5th option including on top?

With the current setup, you're limited on where you can place the fab (spawning items onto walls/other machines etc).

**Comment by kingofkosmos** [comment]
Exosuit Fabricator wrenching-solution was way too difficult for me, sorry. It now spits in the direction of its dir-variable, which's default is south.

**Comment by PKPenguin321** [comment]
it's cool, at least there's a var :+1:

**Comment by Lumipharon** [comment]
King, but the wrenching thing for other machines just changes the dir var - it's exactly what you're doing.

**Comment by CorruptComputer** [comment]
Someone should also update the mapping wiki, it is insanely out of date and not useful anymore. I used to use it for just quick references of dirs and whatnot. 

If no one else wants to I could do it tomorrow.

**Comment by CorruptComputer** [comment]
Also this should be added to anything that spits out items.

**Comment by Aranclanos** [comment]
you should update the OP

**Comment by kingofkosmos** [comment]
Oh right, updated.

**Comment by Razharas** [comment]
Looks nice to me

**Comment by Lumipharon** [comment]
Based as fuck.

**Comment by kingofkosmos** [comment]
No, it just does that from now on, like every other machine (except the Exosuit Fab).

**Pull request merged**
