### PR TITLE
Adds a tally of produced power to feedback

### PR DESCRIPTION
**Pull request by Cyberboss**
Logs the amount of power produced by all generators into a tally made up of the owning type for balance reference

### CODE REVIEW

**Comment by Fikou** [comment]
Please consider this a friendly warning, your PR's must have a properly descriptive title and body content that explains the purpose of the PR.

Your current title and or body content does not meet requirements, so please update it.

**Comment by Jared-Fogle** [comment]
@Fikou It was properly descriptive to someone with DB access, like me 😏

**Comment by cacogen** [comment]
>Save data to a database nobody can look at

based

**Comment by Cyberboss** [comment]
...

https://sb.atlantaned.space/rounds/150034/

**Comment by optimumtact** [comment]
Individual round values are not particularly useful or interesting, what you really need is monthly averages/batching to see change over periods of time

**Comment by Cyberboss** [comment]
Meh

**Pull request closed without merging**
