### PR TITLE
AStar fixes

### PR DESCRIPTION
**Pull request by Aranclanos**
Fixes diseases not infecting people behind tables or other objects with density that do not block air.
Fixes poly from smashing herself constantly against windows trying to reach unreacheable items.
Changed the way AStar selects the adjacent turfs from each turf, taking in count the capabilities of the object or mob who will move. For example, being able to pass over tables.
The new system will use the bitflag atmos_adjacent_turfs to reach for adjacent turfs and CanPass().
Fixes issue #436

### CODE REVIEW

**Comment by Aranclanos** [comment]
this took me 8 hours, but the first two I played around making a completely new different AStar who went awfully wrong and laggy, so they don't really count.

**Comment by RemieRichards** [comment]
> the first two I played around making a completely new different AStar who went awfully wrong and laggy, so they don't really count.

Aran*

**Comment by PKPenguin321** [comment]
>Fixes poly from smashing herself constantly against windows trying to reach unreacheable items.

*I knew it*

**Comment by Cheridan** [comment]
stupid birds :bird:

**Comment by Aranclanos** [comment]
BAAWK

**Pull request merged**
