### PR TITLE
Adds attack_dir to multiple common damage sources, fixes mechs' directional armor

### LINKED ISSUE #74022: Mecha directional damage multiplier is being used inconsistently
it would seem that mecha's armor weaknesses from the rear/sides are not used throughout every way to attack a mecha, i.e. ranged and blob attacks use the directional armor, while most of other attacks don't.

way back in #16607 it was used throughout seemingly every attack instance, but some of those were seemingly lost during the multiple refactors in the following years

`take_damage()` proc even has the `attack_dir` var but it goes unused

https://github.com/tgstation/tgstation/blob/413f2413144e658b8b8f687d3834a265c84db05c/code/modules/vehicles/mecha/mecha_defense.dm#L39-L50

https://github.com/tgstation/tgstation/blob/413f2413144e658b8b8f687d3834a265c84db05c/code/modules/vehicles/mecha/mecha_defense.dm#L72-L107

https://github.com/tgstation/tgstation/blob/413f2413144e658b8b8f687d3834a265c84db05c/code/modules/vehicles/mecha/mecha_defense.dm#L116-L130

https://github.com/tgstation/tgstation/blob/413f2413144e658b8b8f687d3834a265c84db05c/code/modules/vehicles/mecha/mecha_defense.dm#L280-L301

### LINKED ISSUE #81260: Attacking mechs with melee weapons from various directions does not modify their armor.
## Issue Summary

Mechs do not use facing to determine armor variance against melee weapons. It only checks for ``run_atom_armor`` with a facing in the ``bullet_act()`` proc.

This was not true prior to this PR https://github.com/tgstation/tgstation/pull/65375

And was only fixed for projectiles in this pr https://github.com/tgstation/tgstation/pull/67411

## Reproduction:

Step 1: Spawn in a mech with, like, melee armor. Let's maybe var edit it to 50 melee armor for ease.

Step 2: Get a melee weapon without a demolition modifier. Let's make it 10 force for ease, as above.

Step 3: Hit the mech, and check its integrity. 

You'll discover that, when you smack the mech from any direction, it does not alter the damage dealt except by the standard value of the armor (so, 50%, therefore 5 damage)

### PR DESCRIPTION
**Pull request by SmArtKar**
## About The Pull Request

Closes #81260
Closes #74022
Currently mechs are the only atoms utilizing attack_dir but I added it in multiple other places that were missing it to ensure that if something else uses it it won't break in those scenarios

## Changelog
:cl:
fix: Mechs' directional armor now actually works
/:cl:

### CODE REVIEW

**Comment by SmArtKar** [comment]
arrgh how did it break linters

**Comment by githubuser4141** [comment]
does this mean mechs have directional damage on regular item attacks (toolbox, eseord) now rather then only mob attacks and projectiles?

**Comment by Sealed101** [comment]
hi there #74022

**Comment by Ghommie** [comment]
immagine

**Comment by SmArtKar** [comment]
> immagine

found why this was the case, blame damage thresholds because someone chose energy axe despite its base force not being high enough to get through mauler's armor + damage threshold

**Pull request merged**
