### PR TITLE
Adds the red cross emblems to the list of banned content

### PR DESCRIPTION
**Pull request by Thunder12345**
## About The Pull Request

Adds a new item to the banned content list in CONTRIBUTING.md:

"Imagery which contains any of the protected emblems of the [Red Cross Movement](https://www.ifrc.org/emblems-and-logo). Unauthorised use of these symbols is prohibited by the First Geneva Convention and the laws of some countries."

## Why It's Good For The Game

We have already been removing or preventing any appearances of these symbols when they are found (In all cases so far I believe it's been the red cross), so it makes sense to explicitly ban their use to clarify this point and avoid future misunderstandings or issues.

### CODE REVIEW

**Comment by cacogen** [comment]
So cool knowing this game has violated the Geneva Convention

**Comment by ExcessiveUseOfCobblestone** [comment]
Can you move both the tos and any legalise items above the “please don’t pr species content”

seems weird that’s just in the middle of things like nazis and law-breaking symbols.

**Comment by Thunder12345** [comment]
> Can you move both the tos and any legalise items above the “please don’t pr species content”
> 
> seems weird that’s just in the middle of things like nazis and law-breaking symbols.

👍

**Comment by TheBonded** [comment]
Woo! That's one less Geneva Convention violation to worry about

**Pull request closed without merging**
