### PR TITLE
Fixes Poly speak.

### PR DESCRIPTION
**Pull request by AnturK**
Absorbing PunPun, squawk.

### CODE REVIEW

**Comment by Poojawa** [comment]
Our Poly was stuck on yelling

'[Engineering] Poly  yells, " We don't got no medics, lass. " '

all shift. for two hours.

**Comment by Ratvar** [comment]
You don't got no medics, lass.

**Comment by praisenarsie** [comment]
You don't got no medics, lass.

**Comment by Poojawa** [comment]
Oh, I implimented this fix, and it didn't fix aaaanything. aaa

**Comment by AnturK** [comment]
First survival streak needs to end for this to work.

**Comment by DoctoreMad** [comment]
You don't got no medics, lass.

**Review by Cyberboss — APPROVED** [review]

**Pull request merged**
