### PR TITLE
Gives more berets to the station

### PR DESCRIPTION
**Pull request by tralezab**
## About The Pull Request

Adds more berets to the vendors.

## Why It's Good For The Game

image

Well if sinful declares there's a beret drought we gotta do something about it

## Changelog
:cl:
add: Added new berets to the vendor
/:cl:

### CODE REVIEW

**Comment by DaydreamIQ** [comment]
The excuse people give is something about "Every job has a beret and its dumb we're not a military." but yeah, berets are just a nice option to have I don't see why its such an issue. We have a billion variations of bandana but they aint getting trimmed, good pr

**Comment by LemonInTheDark** [comment]
sinful is wrong

**Comment by BlueMemesauce** [comment]
Didn't we have a whole argument a couple months ago about how theres too many berets? When is the last time you've even seen someone wear a beret?

**Comment by tralezab** [comment]
> Didn't we have a whole argument a couple months ago about how theres too many berets? When is the last time you've even seen someone wear a beret?
> 
> Nevermind this is just a meme PR that increases the quantity available in the vendor, bluememesauce has been memed

BUT WHERE'S THE MEME

**Comment by DrDiasyl** [comment]
Beret is a symbol of power and authority in my opinion, but drip is drip so whatever, let people wear berets.

**Comment by Fikou** [comment]
/tg/station has fallen.

**Comment by DrDiasyl** [comment]
> The excuse people give is something about "Every job has a beret and its dumb we're not a military." but yeah, berets are just a nice option to have I don't see why its such an issue. We have a billion variations of bandana but they aint getting trimmed, good pr

(This just doubles amount of berets in the clothing vendors)

**Comment by tralezab** [comment]
which can be any color *taps forehead*

**Pull request merged**
