### PR TITLE
Removes a bunch of unused families huds

### PR DESCRIPTION
**Pull request by Rex9001**
## About The Pull Request
Does what it says on the tin, slices out a bunch of unused antag huds.
## Why It's Good For The Game
Its getting pretty annoying to work within that file when half the icons arent used, so this just removes them. The file is less cluttered now.
## Changelog
Shouldn't be player facing

### CODE REVIEW

**Comment by Fikou** [comment]
theyre useful for admin events

**Comment by Rex9001** [comment]
> theyre useful for admin events

I havent seen these used ever, do you want them all to stay?

**Comment by Fikou** [comment]
no this isnt binding i just think theyre useful as generic icons for team antags (admins can create antag teams in game panel and give them custom icons)

**Comment by Iamgoofball** [comment]
I'd move 'em off to a different dmi file then.

**Comment by Rex9001** [comment]
> I'd move 'em off to a different dmi file then.

Id be fine doing that ig

**Pull request merged**
