### PR TITLE
Holoparasite Theme/Name Datums

### PR DESCRIPTION
**Pull request by ChangelingRain**
:cl: Joan
imageadd: Support holoparasites now have a healing effect with their color when successfully healing a target.
tweak: Ranged holoparasite projectiles now take on the color of the holoparasite.
bugfix: Holoparasite communication(holo->summoner) now sends the message to all holoparasites the summoner has.
bugfix: If you have multiple holoparasites for some reason, Reset Guardian allows you to choose which to reset.
tweak: Resetting a holoparasite also resets its color and name, to make it more obvious it's a new player.
rscadd: Holoparasites can now see their summoner's health and various ability cooldowns from the status panel.
/:cl:

Fixes up communication/force-recall/reset to use hasparasites() instead of checking the mob list.
Holoparasites now use a theme datum, produced via New(), for their name/theme/colouration instead of having the guardian creator set it.
Holoparasites now have a dark grey spanclass for various text, and will use the holoparasite's color when referring to it in internal messages.

### CODE REVIEW

**Comment by optimumtact** [comment]
Dunno how I feel about using datums for this, feels like they should be data in either json or txt form.

**Comment by duncathan** [comment]
I agree with oranges; JSON is better suited to this IMO

**Comment by Razharas** [comment]
><Joan> it's not totally necessary it's something that probably should be done later

**Comment by ChangelingRain** [comment]
I'm like 50% sure it's a style thing and at minimum it works as-is

**Pull request merged**
