### PR TITLE
Fixes #10809: Ctrl+C not working

### LINKED ISSUE #10809: Ctrl+C no longer copies text
http://puu.sh/japDK/e39450db6b.png
Thanks to the [recent resist hotkey pull](https://github.com/tgstation/-tg-station/pull/10715), ctrl+c now always tries to resist and no longer copies text. Could the resist hotkey get moved to something else instead?

### PR DESCRIPTION
**Pull request by freerealestate**
- Fixed #10809
- Changed resist to B (hotkeys mode) and ctrl+B (either mode) instead.
- Fully removed End resist from cyborgs.

### CODE REVIEW

**Comment by SconesC** [comment]
:+1:

**Comment by phil235** [comment]
@freerealestate What are the other changes for ("allow-html = false" and other stuff below) ?

**Comment by freerealestate** [comment]
Those just happen automatically when you edit skin.dmf for some reason.

I can easily remove them, but I haven't noticed them change anything and
it'll mean they'll have to be removed every time someone edits skin.dmf.

**Comment by Jordie0608** [comment]
@phil235 see these commits for what @freerealestate refers to
https://github.com/Jordie0608/-tg-station/commit/66165778b77aa31cd402d423f63b70a7af38d9e2
https://github.com/tgstation/-tg-station/commit/5c4d5841542c4fa0c77c08a103cad2159b3af975

**Pull request merged**
