### PR TITLE
[Ready] Fixes the 2 minutes of interface lag (such as ready button not working) when a client connects.

### PR DESCRIPTION
**Pull request by MrsTonedOne**
This is a port of /vg/'s asset cache system. Thanks @PJB3005

Byond will queue all browse(), browse_rsc(), and winset() calls to the client, to ensure they load in order, and ensure any resources from a browse_rsc call (css/html/js) are already at the client by the time any html windows loads.

How ever, each file/call is processed separately, and byond will wait for the reply from the client before it will send the next file.

Our current system sends all of these html resource files to the client at once when they connect, this is the sole cause of the lag when a client connects. Byond will not send the client a file it already has, but it has to ask the client first, and it does so one file at a time, waiting for a reply from the client before sending the next request down the pipe.

This system fixes that.

Basically it works like this:
Client connects: nothing happens, no massive queuing of browse_rsc() calls, so no interface delay
Client opens a asset_cache controlled html based interface
Asset cache gets notified by the html based interface what assets the client needs to have.
Asset cache checks to see if it's sent that client those files.
Asset cache sends the missing ones, adding them to the list of assets the client has.

This basically spreads out the delay to when you first open a window that uses resources, where it is much more manageable. But ensures it doesn't queue these calls more than once for a given client on a given connection. (this list is stored on the /client/ so that if they re-connect on a different version it doesn't break things)

I've kinda done a halfass port without too much thought, I see some room for improvement to better fit /tg/'s coding style and make the system more flexible. I'm PRing this because if I don't, it will never get finished.

PDAs and html_interface has been imported into the new system lazily to test. at 100ms fake lag, client interface lag on connection went from **35 seconds to ~~16~~ 2 seconds**. ~~Nanoui hasn't been imported, and once it is, that should drop down to almost nothing.~~

I'm going to hold off on properly adding nanoui into this system, until after the bay nanoui port. The current implementation prevents it from causing the lag, but might cause oddites if a first time user or somebody with a cache opens a nano ui window in the first 60 seconds of connecting.

I tested crew monitor, pdas, cryo, apcs, coms console, medical record, security record,

no runtimes or odd errors.

:cl:
bugfix: fixes interfaces (like the "ready" button) being unresponsive for the first minute or two after connecting.
/:cl:

### CODE REVIEW

**Comment by optimumtact** [comment]
what's the potential to figure out different assets, zip them server side and then deliver as a single file and unzip client side?

**Comment by optimumtact** [comment]
ps, how slow does this make the first PDA load?

**Comment by PJB3005** [comment]
Right now on /vg/, opening the PDA initially takes ~15 seconds? We have more PDA assets though, and even then it could be better optimized, another idea is to make assets like the PDA's be gradually sent to a client.

Oh, @MrStonedOne, you're missing the skin file modifications, and the `client/Topic()` addition for the asset job reception.

**Comment by MrStonedOne** [comment]
I forgot to hit save on the skin file and not sure what happened to the topic modifications.

As for opening the pda, it takes 5 seconds for the first time you open a pda.

I'm gonna look at lowering that by making it only request the resources it plans on using for that page. No need to send every carthage's icon as well as the pai icons when it's an assistant's pda.

**Comment by PJB3005** [comment]
Yeah that's what I was thinking too with "optimizations".

**Comment by tkdrg** [comment]
Another option would be placing all the icons into a single .png and just loading the icons from that using css (the html interface cards already do that if you check cards.css).

**Comment by MrStonedOne** [comment]
This is ready, I'm gonna hold off on properly adding nanoui to asset cache because that is a more extensive change and there is a current pr that is importing bay's nanoui.

Once that pr is closed or merged, i'll work nanoui in to this system.

For now the code will send them the asset files in a way that won't block the ready button.

I also make it so it will take idle time in which the client isn't sending any asset files and pre-cache the client with the current asset list in a way that doesn't block browse() calls.

**Comment by RemieRichards** [comment]
HoG uses ```browse_rsc()``` for structure build UIs, there's about 10 or so files, you want to go ahead and make an asset thing now or should I do it in a later HoG PR?

**Comment by MrStonedOne** [comment]
@RemieRichards I'll handle those cases when i do the pr that more properly handles nanoui. They don't affect just after connection lag, so they aren't a priority in this PR.

**Comment by RemieRichards** [comment]
Yeah I realised a while after that I do those when the UI opens, so there's no noticeable lag from it.
But good for clarification.

**Comment by MrStonedOne** [comment]
I've tested this rather extensively (clearing my cache each time), it's ready for a merge

**Pull request merged**
