### PR TITLE
podpeople ass icon

### PR DESCRIPTION
**Pull request by Ghilker**
## About The Pull Request
asspodperson
image

## Why It's Good For The Game
adds missing ass

## Changelog

:cl:
imageadd: adds the podpeople photocopy ass
/:cl:

### CODE REVIEW

**Comment by Jolly-66** [comment]
Zamn he did it

**Comment by Shadowflame909** [comment]
wait but they photosynthesize. What comes out?

**Review by Imaginos16 — APPROVED** [review]
Zaaaaaaaaaaaaaaaaaaaaaaaaaaaaamn

**Comment by NightmareChamillian** [comment]
>  What comes out? Oxygen?
CO2, of course!

**Comment by notfrying1pans** [comment]
😳

**Comment by Toastgoats** [comment]
Now do moths coward

**Comment by the-orange-cow** [comment]
this looks like ass

*bah dum tssssss*

**Pull request merged**
