### PR TITLE
[READY]Gateway Update

### PR DESCRIPTION
**Pull request by silicons**
Saves on some lines of code
Makes some gateway things vareditable
Makes an admin verb accessible again
Makes away mission starts spawnable.

### CODE REVIEW

**Comment by Iamgoofball** [comment]
No.

We replaced gateways with space and lavaland ruins.

**Comment by SgtxRootbeer** [comment]
space and lavaland ruins are only accessable by a limited population (the miners, mostly, and they have a job to do of getting mats)
gateway seems better.

**Comment by WJohn** [comment]
gateway and space ruins are bad pretty much entirely because they're ridiculously horribly designed, more than anything. them being able to drain more than half of the crew's population because the gateway does not start at the same place (or very close by) means most people end up dead in that location.

**Comment by kevinz000** [comment]
This is a generic update to gateway.
Has nothing to do with the state of the away missions.

**Comment by Haevacht** [comment]
Looks to do more than just gateway shenanigans.

**Comment by kevinz000** [comment]
yes but this will not impact existing away missions in any way, only modify away mission loading and how their landmarks are treated. existing missions will have to be edited to use the new automatically adding landmarks.

**Comment by improvedname** [comment]
Make gateway missions like escape shuttles buyablr coordinates and everytime a new coordinate is bought it wipes out the old on3

**Comment by Thunder12345** [comment]
For the downstreams that do use it

**Comment by kevinz000** [comment]
@ma44 I can manually load in maps for events.

**Comment by MimicFaux** [comment]
This is what I've been wanting. I've been jury rigging ladders at the gateway to host off station events. Getting access to the gateway itself will be a huge boon.

**Comment by Haevacht** [comment]
I meant the admin FPS verb changes kev.

**Comment by kevinz000** [comment]
@Haevacht I just realized that the verbs were in debugging and I couldn't find them and changing them is unnecessary

**Comment by Tacolizard** [comment]
@Iamgoofball we have a ton of great ruins and no way to properly explore them.

we should work on fleshing out space exploration, not gateway shenanigans.

**Comment by optimumtact** [comment]
Well on the whole this reduces lines of code and looks clean enough so I guess ¯\_(ツ)_/¯

**Pull request merged**
