### PR TITLE
Bedsheets now display properly.

### PR DESCRIPTION
**Pull request by san7890**
## About The Pull Request

Have you ever wanted to get a restful snooze, but you shiver to fucking death because of this bull-shit?:

image

FUCK!

This PR fixes that, by fixing how the layers on bedsheets are, so that they are on the plane above mobs. Because... it wasn't done when we did FOV last month. 

image

Finally, comfy restful sleep.

## Why It's Good For The Game

Bedsheets should show above the player. There is no reason for it to not show up above the player (as it does without this PR fixing it)

## Changelog

:cl:
fix: To everyone who likes sleep, hopefully you can all dream a little bit sounder now that all of your bedsheets actually cover you now rather than persist under you (and any other mobs).
/:cl:

### CODE REVIEW

**Review by LemonInTheDark — APPROVED** [review]
Make sure your changelog tells them what you actually fixed, it's the only record players have of this stuff and all

**Comment by AdipemDragon** [comment]
doesn't this pr step on the toes of what https://github.com/tgstation/tgstation/pull/63903 is doing or am i being a worrywart?

**Comment by san7890** [comment]
> doesn't this pr step on the toes of what https://github.com/tgstation/tgstation/pull/63903 is doing or am i being a worrywart?

Everything operates on DEFINES, and all that PR changes is the value of the define. I scanned through the numbers, and this could be merged right now or after that PR, it shouldn't matter because the defines are linked to the same file and will work regardless. You could be concerned had I assigned a number in this code rather than the define, but this is both backwards-compatible and future-proof.

**Comment by exymian** [comment]
thank you so much

**Pull request merged**
