### PR TITLE
(Fix) Metastation AI should not be the victim of anti-cable activists

### PR DESCRIPTION
**Pull request by KathrinBailey**
## About The Pull Request
image
https://www.youtube.com/watch?v=3WShMzwT-nM

## Why It's Good For The Game
admin why i got no power why tcomms off???

## Changelog
:cl:
fix: Metastation's AI satellite is now wired to the station again.
/:cl:

### CODE REVIEW

**Comment by Kylerace** [comment]
how long was that cable missing

**Comment by Ghilker** [comment]
the cable is not there to prevent one power sink to kill the AI that easily

**Comment by KathrinBailey** [comment]
> the cable is not there to prevent one power sink to kill the AI that easily

(X) to doubt, look at tcomms wiring.

**Comment by Ghilker** [comment]
> > the cable is not there to prevent one power sink to kill the AI that easily
> 
> (X) to doubt, look at tcomms wiring.

what about comms wiring?

**Comment by KathrinBailey** [comment]
> > > the cable is not there to prevent one power sink to kill the AI that easily
> > 
> > 
> > (X) to doubt, look at tcomms wiring.
> 
> what about comms wiring?

are you honestly trying to call this a "feature" when tcomms is now unwired to the main grid at roundstart and will lose power every round? It's not even connected to the SMES in the AI sat.



> how long was that cable missing

If I were to have an absolute random guess, the external metastation rework thingy PR might have done it? I think it was the one that moved the entire AI satellite up a tile, I dunno.

**Comment by Ghilker** [comment]
> > > > the cable is not there to prevent one power sink to kill the AI that easily
> > > 
> > > 
> > > (X) to doubt, look at tcomms wiring.
> > 
> > 
> > what about comms wiring?
> 
> are you honestly trying to call this a "feature" when tcomms is now unwired to the main grid at roundstart and will lose power every round? It's not even connected to the SMES in the AI sat.

then connect the tcomms to the smes, now you'll kill AI with just one power sink

> > how long was that cable missing
> 
> If I were to have an absolute random guess, the external metastation rework thingy PR might have done it? I think it was the one that moved the entire AI satellite up a tile, I dunno.

it's missing since forever now

**Comment by CRITAWAKETS** [comment]
this isnt a fix, its intentional because a power sink will cause major problemos to the AI.

**Comment by zxaber** [comment]
That wire has been missing for at least four years, and the AI is disconnected from the station on every map. Very hard to believe this was by accident.

Telecomms loses power after about two hours or so. Literally anyone can fix this in-game if it becomes an issue.

**Comment by KathrinBailey** [comment]
> That wire has been missing for at least four years, and the AI is disconnected from the station on every map. Very hard to believe this was by accident.
> Telecomms loses power after about two hours or so. Literally anyone can fix this in-game if it becomes an issue.

> this isnt a fix, its intentional because a power sink will cause major problemos to the AI.

> then connect the tcomms to the smes, now you'll kill AI with just one power sink

All of you are very very very wrong.
This doesn't connect the AI to the station.
This connects telecomms, AI sat exterior, foyer, antechamber and AI satellite maint to the chamber.
**The AI is still disconnected.**
This is a bug, it's very obviously a bug.

**Comment by Ghilker** [comment]
if it is like that is fine then

**Comment by optimumtact** [comment]
no no kathrin you obviously just dont' understand the SHEER brilliance of the mapper who made this change

This single wire is so critical, so important to not be there that all powerdrains are STOPPED dead, instantly

**Comment by KathrinBailey** [comment]
> no no kathrin you obviously just dont' understand the SHEER brilliance of the mapper who made this change
> 
> This single wire is so critical, so important to not be there that all powerdrains are STOPPED dead, instantly

just use the halo 3 power drain and throw it at the AI
image
then just use an xray laser gun to headshot the AI through the reinforced walls whilst their shields are down 👍

**Review by ShizCalev — APPROVED** [review]

**Review by ShizCalev — CHANGES_REQUESTED** [review]
actually that approval was a touch premature. the cable was infact not connect to prevent a 2 minute in powersink from killing the AI (time is irrelevant, issue is the same.)

these powernets should remain separate unless an engineer / borg decides to merge them during a round imo.

**Comment by KathrinBailey** [comment]
> actually that approval was a touch premature. the cable was infact not connect to prevent a 2 minute in powersink from killing the AI (time is irrelevant, issue is the same.)
> 
> these powernets should remain separate unless an engineer / borg decides to merge them during a round imo.

I think I need to reiterate again that **this does not connect the AI to the rest of the station.**
This connects the following areas to the station:
AI interior
AI antechamber
AI exterior
AI maintenance
Telecomms

The AI is still on it's own net with a SMES, not connected to the rest of the satellite.

**Comment by KathrinBailey** [comment]
So to put all these collective misunderstandings to what this does to rest:
image

**Comment by KathrinBailey** [comment]
This is for the sole benefit of telecommunications not running dry due to it's considerably huge power-draw. ⚡ 
If the AI's closed powernet had to power the entire satellite, well... all those Assistant radio peotry readings will be the death of the AI.

**Comment by Cyprex** [comment]
Out of curiousity when does it run dry in practice on metastation?
Also there should be a matching missing cable on the other side of the tubes(outside the airlock) unless someone added a cable there in the past

**Comment by optimumtact** [comment]
mfw

**Comment by Maurukas** [comment]
The entire station is now drawing power out of the telecomms SMES instead of the just the six satelite APCs.

image

**Pull request merged**
