### PR TITLE
Icebox Chemfactory is on a lower z-level, adds a bit of maintenance, fixes area issues with hydro [MULTI-Z] [WAGE CAGE]

### PR DESCRIPTION
**Pull request by tralezab**
## About The Pull Request

~~Also probably adds a multi-z plumbing pipe, because I basically gotta.~~ Actually, we're good!

<details>
  <summary>Chemistry Changes (Atmos pipes barricaded off until the fix for them is merged)</summary>
  
 image
 image

  
</details>

<details>
  <summary>Maintenance Changes</summary>
  
 image
 image
 image

  
</details>

## Why It's Good For The Game

Gives Icebox WAY more space (despite being a fairly large map, it had the smallest chemfactory. Boo!
Gives Maintenance WAY more space (icebox has historically had a really, really lackluster maintenance)
Wage cage (Wage cage)
Moves output shutters to the active treatment room (Way closer, much nicer for doctors)

## Changelog
:cl:
add: Chemfactory has been multi-z'd on icebox, and it's not so damn small anymore!
/:cl:

### CODE REVIEW

**Comment by tralezab** [comment]
This goes without saying, but this is one of the most cursed prs i've made in awhile

**Comment by TiviPlus** [comment]
wagie wagie...

**Comment by tralezab** [comment]
actually, chem recievers work. neat!

**Comment by san7890** [comment]
Nice wage cage.

Shouldn't it have an external entrance/exit? Unless that's not a standard in any way.

**Comment by tralezab** [comment]
The rage cage is entered through the ladder!

**Comment by nightred** [comment]
image
You are merging the waste and supply lines. You need a separate adapter for each line.
Also the layer enabled Multiz adapter has not yet been merged so this will not connect.

**Comment by tralezab** [comment]
such is life for those in the cage

**Comment by san7890** [comment]
My bad, I saw the wage cage ladder, but was referring to a different thing.

Shouldn't the Lower part of Chemistry, the factory part, have an exit onto the ice planet?

**Comment by tralezab** [comment]
Naw, they don't really have a need... I think!

**Comment by Jared-Fogle** [comment]
> ~~Also probably adds a multi-z plumbing pipe, because I basically gotta.~~

So then how do the pressers get back up?

**Comment by tralezab** [comment]
Plumbing has teleportation! Apparently. How have I never noticed? Anyway, you can just link up the bottom bits to the top bits and be just fine.

**Comment by Tlaltecuhtli** [comment]
chemistry machines (apoecary) is med job now tho

**Comment by Winterous** [comment]
Yes plumbing has teleportation, but you need to BUILD the teleporters, they cost bluespace crystals.

**Comment by Jared-Fogle** [comment]
> Yes plumbing has teleportation, but you need to BUILD the teleporters, they cost bluespace crystals.

This was my concern.

**Comment by hannahscript** [comment]
And even worse, someone needs to research it. I love the change but you're gonna have to carry those meds up until like 30 minutes into the shift

**Comment by tralezab** [comment]
I've mapped em in, they're already present. The screenshots don't show it but all you'll need to do is link em which you can do in seconds

**Comment by ArcaneMusic** [comment]
For why does the waged bird cage?

**Comment by tralezab** [comment]
I just like the idea of the wage cage turning into plasma molten death at some point.

**Comment by Winterous** [comment]
I suppose the 'free' bluespace crystals don't really matter in the grand scheme of things. Cool!

**Comment by Barhandar** [comment]
Alternate title: Kicks Chemist NEETs Into Basement As They Deserve

**Comment by tralezab** [comment]
I really wish I could encourage people to use the wage cage more..,

**Comment by ShizCalev** [comment]
Conflicts.

**Pull request closed without merging**
