### PR TITLE
Improved Cabin Away Mission

### PR DESCRIPTION
**Pull request by ishitbyabullet**
## About The Pull Request
This is a change to the Cabin away mission. There is now more stuff in the cabin AND outside of the cabin. Not only that, the map is no longer a **giant fucking box of emptiness.** This also has manually placed trees and stuff  which means no more randomly generated flora (which didn't even work CORRECTLY in my experience). All in all, it makes the away mission better for truly feeling immersed in snow cabin roleplay.

_Thanks to Jegub for spriting a snowlegion with a head sprite as well. Thanks to Fikou, Qustinnus, Nemvar, and Tralezab for trying to help me code a snowlegion mob (was unable able to finish it sadly). Thanks to MrDoomBringer for saying he would add a mob inside something for me. Thanks to Actioninja and others I asked for helping me with removing a merge conflict. Thanks to Terry Round 144046 for being the first to playtest my away mission (they made me laugh due to how they checked every corner for secrets before I actually added any secrets)._

## Why It's Good For The Game

Because the map is no longer completely fucking boring. I mean, the map was literally a giant box. The lumbermill looked pathetic. Dear god, the old map wasn't good.

## Changelog
:cl: Central Command ft. bald people
add: We recently lost contact with a snow resort cabin that has a gateway. Due to the gateway and lack of communication, we have allowed you to come to this location for us. Yes, this is a different snow resort cabin.
del: We also declared that the old cabin away mission site is no longer necessary for you guys to explore. We already know everything there is to know about it. Good job!
/:cl:

### CODE REVIEW

**Comment by ishitbyabullet** [comment]
dreammaker_2019-07-30_17-18-15

**Comment by ishitbyabullet** [comment]
It says _maps/RandomZLevels/Cabin.dmm is a conflicting file however I deleted it. It shouldn't even exist anymore. I don't get what the issue with it is.

**Comment by Dawson1917** [comment]
Where are the bunnies?? How am I supposed to get my easter bunny zoomsuit??

**Comment by ishitbyabullet** [comment]
penguins won the war between bunnies obviously.

**Comment by nicbn** [comment]
Some suggestions:

* You should add some dirt around.
* The 2 arcades in the middle of the hallway feel really out of place (I suggest shrinking the theatre and putting it in the bar).
* The piano should be in the theatre, not in the backstage.
* Why are the fireplaces behind windoors?
* Should probably have some more heaters scattered around.
* Cryo pods aren't touching the wall.
* The turbine makes no sense.
* Maybe add atmos to make the maintenance have more purpose?
* Replacing some airlocks with regular doors would probably improve the looks of the area.
* I think maintenance airlocks shouldn't be wooden (that way it'd be easier to "find" them).
* It would look better if surgery room was isolated. By moving the cryos upwards (so that they touch the wall), you may have some room to move the oxygen canister, so you can add a wall. I'd suggest having the tools table adjacent to the console, and using shower curtains as doors.

**Comment by ishitbyabullet** [comment]
1. You mean dirt as in floor decal right?
2. It was to try and make the hallway not feel soulless. Honestly, they aren't needed at all.
3.. The piano is supposed to be moved. I'll place it in the theatre though.
4.. I think it's supposed to be like a protective screen? Was part of the original map.
5. Heaters are nice.
6. Oh yeah. Thanks for pointing that out.
7. Turbine is part of the original map. I think it's supposed to be an excuse for the infinite energy SMES. It works for me tbh.
8. I don't know what you mean by atmos however I find it unnecessary. I should add fans though. I hate how the fucking outside has no air because "lolcold"
9. Which airlocks? I can think of only the theatre, bar, and manager office.
10. Hmmm. I can try that.
9. 
5.

**Comment by nicbn** [comment]
1. Yes
2. You could add some entertainment monitors, newscasters and intercomms to the walls.
8. Atmos pipes, which leads to vents and scrubbers. Have a minimal setup with at least an air can and injectors to outside (or go full setup with filters and all).
9. Bathroom ones and the ones you cited.

**Comment by Detective-Google** [comment]
Dumb thing that might be fixed already- while it makes aesthetic sense for the soda fountain to be accessible to everyone, wouldn't this make it a huge pain in the ass for a bartender to mix drinks that require sodas as ingredients?

**Comment by Detective-Google** [comment]
another thing that's probably already fixed, it seems the penguins have a habit of mysteriously *fuckin dying* presumably something to do with the atmos comp

**Comment by ishitbyabullet** [comment]
If they die to the cold then that is something I can not solve.

I hate how snow just decides oxygen is for the weak so it just makes oxygen ninja vanish for some reason????????

**Pull request merged**
