### PR TITLE
Adds portable air pump and portable scrubber crates to cargo

### PR DESCRIPTION
**Pull request by googobbug**
## About The Pull Request

Adds three new crates to cargo: two air pumps for 2500 credits, two scrubbers for 2500 credits, and one huge scrubber for 5000 credits.

## Why It's Good For The Game

Makes it actually possible to get more of these machines and gives engineering / science a reason to visit cargo.

## Changelog
:cl: Bumtickley00
add: Cargo can now buy portable air pumps and portable scrubbers
/:cl:

### CODE REVIEW

**Comment by Jalleo** [comment]
I thought they were made buildable back when space heaters were done too. I am surprised.

**Comment by stylemistake** [comment]
I approve this PR. Limited supply of portable pumps and scrubbers was always getting in the way.

**Comment by carlarctg** [comment]
more cargo bloat that will never be ordered

**Comment by stylemistake** [comment]
I strongly disagree. Portable scrubbers will be a yet another source of income, once placed on lavaland. Miasma tycoon.

**Comment by dr-bee** [comment]
Any chance of making the industrial sized ones that are in toxins available? Buying more of those would be actually awesome.

**Comment by AdmiralPancakes1** [comment]
oh yeah I forgot about those ones

**Comment by Cyprex** [comment]
Seems like this will make lavaland gas farms even easier.

**Comment by AdmiralPancakes1** [comment]
Not really, portable scrubbers are worse than floor scrubbers for farming since they can't run on expanded mode (and still need power). You can't use huge scrubbers to farm either because gas only counts for money if it's in a canister and you can't wrench huge scrubbers to a connector to get the gas out.

**Review by 81Denton — APPROVED** [review]

**Pull request merged**
