### PR TITLE
Removes Oh Hai Daniel shuttle from purchase, pending rework (Shuttle changes #4)

### PR DESCRIPTION
**Pull request by coiax**
:cl: coiax
del: Removes Oh Hai Daniel shuttle from purchase, pending a rework.
/:cl:

Currently it's too small, has no engines, is a little memey.

I want to expand it, make it a little more usable/safe, while still
embracing the complex backstory that makes it so rich.

### CODE REVIEW

**Comment by lzimann** [comment]
Title is kinda misleading since you are not actually removing the shuttle and just making it not buyable.

**Comment by Iamgoofball** [comment]
What the fuck :-1:

Are we not allowed to have downgrade shuttles?

It's an apartment. Not an actual shuttle.

**Comment by KorPhaeron** [comment]
Why not just rework it if you're going to rework it?

I don't think this is need of removal so badly that we can't wait on the replacement.

**Comment by CakeQ** [comment]
Oh hi Daniel is the best shuttle pls no remove

**Comment by ChemicalRascal** [comment]
@KorPhaeron The entirety of tgstation needs to be reworked let's remove it all in the meantime

**Comment by coiax** [comment]
It's a super non-functional shuttle that is too small.

**Comment by CakeQ** [comment]
ya but it's great

**Comment by Iamgoofball** [comment]
@coiax 
It's perfectly functional. It docks, it has a shuttle console, it takes off properly. It's intentionally inferior to the  normal shuttle because you get a payout for buying it.

Hell, it's even got LORE.

**Comment by KorPhaeron** [comment]
I don't think both tiny shuttles should be removed at once. If admins dont want people buying them there is still the config option

**Pull request closed without merging**
