### PR TITLE
Adds the ability to ban someone from OOC

### PR DESCRIPTION
**Pull request by Shadowlight213**
This totally wasn't influenced by a community member.

### CODE REVIEW

**Comment by Supermichael777** [comment]
10/10 don't let one shirker ruin it for the rest of us

**Comment by Shadowlight213** [comment]
@dorsisdwarf you can remove the dnm, I am an admin damnit.

**Comment by Shadowlight213** [comment]
Fuck. This is gonna conflict with the selective ooc mute pr.

**Comment by Dorsisdwarf** [comment]
Well gee as long as you tested it on sybil live.

**Comment by kevinz000** [comment]
I fell a tiny bit of sorrow for Punnches
His essence will be banished forever following the two OOC muting feature additions

**Comment by MrStonedOne** [comment]
One downside, that we might want to look at fixing....

Job bans are only loaded at round start.

Meaning if somebody got un-banned from ooc, it would take until next round before they could talk in ooc.

**Comment by Jordie0608** [comment]
The jobban system in general is lacking and clearly had SQL shoehorned into a .sav based system.

**Comment by Shadowlight213** [comment]
The refactor of database banning is probably going to have to be done in another PR.

**Comment by Shadowlight213** [comment]
@Jordie0608 @phil235 @Razharas @RemieRichards @Cheridan 
Ready for review/merge

**Comment by HankMoodyExperience** [comment]
vekter tested, :faggot: approved

**Comment by Sarcalogo** [comment]
punnches420 did nothign wrong

**Pull request merged**
