### PR TITLE
MOD update: Modular Cores

### LINKED ISSUE #63945: You can shoe tie (smite) MODsuit boots
## Reproduction:

- Upset an admin while wearing a MODsuit
- Have to untie your MOD boots

image

### LINKED ISSUE #63973: Some MODsuit MODs seem to be missing incapacitated checks for active use
## Reproduction:

I discovered that the Crate Clamp MOD doesn't check for handcuffed when selected and used.
(Meaning you can pick up / lower crates when you probably shouldn't be able to.)

When I went to look at the code, I realized that a few select use mods don't seem to have checks for incapacitated (cuffed, in crit). Tether as another example.

### PR DESCRIPTION
**Pull request by Fikou**
## About The Pull Request

minor changes:
- improves the springlock module by spreading damage across limbs, but making the equipping buff it gives better
- improves the rave module by using color matrices, and fixes it crashing the tgui
- fixes teleport module fucking up your matrices
- adds advanced storage modules to the techweb
- fixes not being able to spraypaint your suit (or any storage item for that matter)
- fixes berserker suit having infinite charge for real
- makes armor booster not remove your heat protection (rip elite nukies)
- balances bomb armor on some suits
- makes it so some specific suits protect their contents from explosions (research, syndicate, captain, admin)
- fixes #63945
- fixes #63973

bigger changes:
1. The suit slowdown is now 1/5 per piece, including the control unit, instead of 1/4 per piece, so undeployed suits will have a minor slowdown
2. You can now right click the deploy and activate action buttons. Right clicking activation will skip the prompt if you want to use it. Right clicking deploy will try to deploy/retract all pieces at once.
3. Adds support for modular cores. They can power your suit in a different way and in the future add some other cool stuff. Currently there are 3 core types:
- Standard: These use ethereal hearts to convert cell charge into viable sources of power. Your current experience.
- Infinite: Infinite charge palladium core. Used by some admin suits and the wizard suit.
- Ethereal: Use power directly from ethereal bodies, not requiring any power cell at all, only work on beings with ethereal stomachs, craftable.

image

https://streamable.com/0p3qa5

## Why It's Good For The Game

makes the suits more modular, adds support for more unique suits like blood powered cult stuff, adds a quick way to use them, makes them not a better backpack by giving them at least a bit of a slowdown

## Changelog

:cl: Fikou
qol: You can now right-click modsuit action buttons to activate them faster.
balance: Undeployed modsuits now have 1/5 of the slowdown instead of 0 (from 0.15 on quick suits like rescue and 0.2 on semi quick like advanced or medical to 0.35 on research and 0.4 on prototype)
qol: the storage modsuit module now tries to scoop up the suit storage item
balance: you can now print expanded storage modules
fix: the magnate suit now has a jetpack
fix: you can now spraypaint storage items
fix: fixes bomb protecting modsuits not protecting the contents from bombs
fix: fixes elite suit nukies burning down
add: MODsuit modular cores. These power your suit, the three types of them are: standard, your current ones, using power cells. infinite, dont use power at all, used by some admin and wizard suits. ethereal, these dont use power cells, but an ethereal's charge directly, they are craftable.
/:cl:

### CODE REVIEW

**Comment by TheBonded** [comment]
How do ethereal cells work exactly? Do they only work if the pilot is an ethereal? Or am I misunderstanding that?

**Comment by optimumtact** [comment]
mod dlc

**Comment by Fikou** [comment]
> How do ethereal cells work exactly? Do they only work if the pilot is an ethereal? Or am I misunderstanding that?

they work on anyone with an ethereal stomach, so if you do surgery you can use it as a human.

**Comment by Shadowflame909** [comment]
> > How do ethereal cells work exactly? Do they only work if the pilot is an ethereal? Or am I misunderstanding that?
> 
> they work on anyone with an ethereal stomach, so if you do surgery you can use it as a human.

Ethereal doing stomach trades for a laser

I do love stimulation of the ingame economy

**Comment by necromanceranne** [comment]
1/5th of a slowdown for many of the faster suits is going to be so small as to be negligible I think. I'd have to wear it to see the difference but I personally think this only impacts the heavier suits like the prototype suit, but for stuff like rescue the slowdown may as well not be there.

**Comment by AndroidMK2** [comment]
How much power does it drain from ethereal cell, don't want to start dying from starvation after few minutes when using some power voring modules.

**Comment by SamDDBS** [comment]
if youre going to add the requirement to install a core after construction, dont you think you shouldve removed the first core from the construction process?

**Pull request merged**
