### PR TITLE
Armor fix 2 electric boogaloo

### PR DESCRIPTION
**Pull request by yackemflam**
:cl: Yackemflam
fix: fixed the standard vest being weaker than the slim variant 
/:cl:

Standard armor vest and slim armor vest now have the same armor values

### CODE REVIEW

**Comment by optimumtact** [comment]
Why not nerf the slim variant to match the standard vest instead?

**Comment by yackemflam** [comment]
I can if you want.
Works either way for me

**Comment by optimumtact** [comment]
yes please

**Comment by yackemflam** [comment]
Done

**Pull request merged**
