### PR TITLE
Revert "Singularity Gen isn't Exportable"

### PR DESCRIPTION
**Pull request by Core0verload**
Reverts tgstation/tgstation#21571

There is absolutely no reason to make singulo generator unexportable. Yes, it's 4000 credits, but you have to actually get it from the engineers to sell it. And 4000 credits is not that much: it's **8 crates** (found right in the cargo bay!) or **8 plasma sheets**.

Engineering can give a maximum of 3 generators if they decide to go green and use only solars - it's 12000 credits. **30 plasma sheets from engineering secure storage - the ones that are used to fuel PACMAN - sell for 15000 credits**, and you don't even have to pull them to cargo.

### CODE REVIEW

**Comment by optimumtact** [comment]
This is a design lead decision and not up for debate.

**Comment by Core0verload** [comment]
"design lead decision"? what the fuck

**Comment by optimumtact** [comment]
have you been living under a rock?

Also why did you break cargo with exports man, it was all fine before the exports nation attacked.

**Comment by Core0verload** [comment]
Cargo was fine back with stable income, then Goof removed it, and I had to add something back.

**Comment by ma44** [comment]
"Let's remove an item that isn't exported a lot, but is worth 4000 credits so it sounds scary and overpowered since there's only two on the entire station!"

**Pull request closed without merging**
