### PR TITLE
The floor is lava admin/wizard event can be ignored by floating mobs

### PR DESCRIPTION
**Pull request by timothymtorres**
## About The Pull Request

The Floor is Lava admin/wizard event would affect mobs even if there was no gravity present.  In zero gravity, mobs are floating and should be able ignore lava effects.

## Why It's Good For The Game

Better consistency.

## Changelog

:cl:
qol: The floor is lava admin/wizard event can be ignored by floating mobs
/:cl:

### CODE REVIEW

**Comment by anclandor** [comment]
But now you can just avoid the event by disabling grav-gen.

**Comment by YakumoChen** [comment]
Gravity generator takes so long to spool down the event would have run its course by the time it turns off.

**Comment by anclandor** [comment]
> Gravity generator takes so long to spool down the event would have run its course by the time it turns off.

Even if you cut its power?

**Comment by YakumoChen** [comment]
Yes

**Pull request merged**
