### PR TITLE
Cabin fixes

### PR DESCRIPTION
**Pull request by KazeEspada**
Cabin has some minor tweaks.
Geothermal Generator is now dense.
A toolbox is guarenteed to spawn.
There are now more keys then ATVs because people are assholes.
Rabbit spawning as been cut by 1/10. This means an average of 10 rabbits during generation down from 100.

### CODE REVIEW

**Comment by bgobandit** [comment]
KILL THE WABBIT

**Comment by KazeEspada** [comment]
I have an easter idea planned for this.

**Comment by Supermichael777** [comment]
jesus christ this had 100 rabbits all with emotes? WHOS IDEA WAS THIS?

**Comment by KazeEspada** [comment]
1 percent chance of rabbits over the size of cabin is 100 rabbits. 0.1 is 10.

**Pull request merged**
