### PR TITLE
Fixes airless shuttles

### LINKED ISSUE #30359: Purchased Shuttles Arrive without Air
Round ID 75597
Oh Hi Daniel arrived without air. This also happened with the Emergency escape bar in a previous round.

### PR DESCRIPTION
**Pull request by AnturK**
Fixes #30359

I'm amazed it took that long for this to have any effect.

### CODE REVIEW

**Comment by AnturK** [comment]
This have other nasty side effects, should probably be testmerged.

**Comment by vuonojenmustaturska** [comment]
Any chance cargo shuttles could be fixed as well?

**Comment by PraiseRatvar** [comment]
cargo shuttles have been depressurizing since the dawn of time that it's pretty much part of the /tg/station experience™️

**Comment by vuonojenmustaturska** [comment]
Unless the user experience is malicious by design, we should fix it. Just because something has always been broken doesn't mean fixing it has a cost where we are removing something special.

**Review by Cyberboss — APPROVED** [review]

**Pull request merged**
