### PR TITLE
Fixes Ministation hydroponics tray supply pack.

### PR DESCRIPTION
**Pull request by harmonyn**
Fixes https://github.com/tgstation/-tg-station/issues/4305. Instead of getting the outdated tray, you get the component parts to build your own (correct) tray.

GIMME THOSE TWO POINTS FAM

### CODE REVIEW

**Comment by tkdrg** [comment]
Why did you do this. Literally no other items come from cargo as a board + some stock parts. Just repath it to /constructable instead of /unattached

**Comment by Firecage** [comment]
What tkdrg said, makes more sense for them to send you a pre-build hydrotray made from the stock parts.

**Comment by bgobandit** [comment]
wait constructable is a thing? why wasn't it in the file was I asleep sigh

**Comment by tkdrg** [comment]
@bgobandit

**Pull request merged**
