### PR TITLE
Fixes smoker addiction, reworks addiction system a bit.

### LINKED ISSUE #57168: Hallucinogen addiction effect doesn't go away on Junkie
## Reproduction:

I rolled junkie on hardcore random with hallucinogen addiction. I couldn't get my fix and then got the spinning blurr effect applied to me. I finally chucked down about 90u of mindbreaker toxin in an attempt to fix it, but that didnt work. Eventually an admin removed the quirk and tried all sorts of stuff, with no avail. Eventually I just asked them to delete my eyes because the spinning blurr effect actually really started fucking with my real life eyes. 

(Also buff the junkie roundstart pill bottle, 1u pills don't do anything anymore)

@Qustinnus

### LINKED ISSUE #57705: Something is very wrong with smoker perk / nicotine addiction
## Round ID:
[158174](https://scrubby.melonmesa.com/round/158174)

## Reproduction:

Joined late to the round. In the time it took to travel to the shuttle down the halls to my department I had became massively withdrawn from nicotine. I had 3 nicotine related moodlets. Even consuming directly 50 units of liquid nicotine did nothing to satiate. Later, I asked an admin to spawn me in at centcom with some smokes and a grinder so I could collect some info. With a timer up I got about 50 seconds in before I was massively withdrawn from nicotine. Yet again I tried liquid nicotine, I even got the moodlet message that I had overdosed on nicotine, yet the withdrawal did not go down.

A picture of the triple whammy of a negative moodlet after 50 seconds.
bGxKMmBqa

### PR DESCRIPTION
**Pull request by prodirus**
## About The Pull Request

Fixes #57705, fixes #57168

Please don't kill me, Floyd.

OK, so the problem was that with the recent addiction rework, it only considered an addiction satisfied if you had more than 2u of the chem in your body. Smokers would never reach 2u in any normal circumstance, so this kinda ruined them.

This PR changes this to instead check if the mob has the chem in their body for 6 seconds consecutively (with a bit of leeway, since it checks once every 2 seconds), and if so, the addiction is satisfied.

Also adds a slight positive moodlet for if the addiction is satisfied from stage 2 or higher withdrawal level. Proc can also be extended to have addiction specific benefits if desired, although none is included in this PR.

Stage 0 withdrawal level has also been added, which should allow addicts to function normally as long as they constantly satisfy their addictions since some of the addictions had pretty bad effects even at stage 1 withdrawal.

Starting pills for junkies is also increased from 1u to 2u, so that they are more reliably able to satisfy their urges with 1 pill.

## Why It's Good For The Game

Makes the addiction system a bit less tedious to deal with for most people, giving them an option to keep operating normally if they can keep their addiction in check.

Smoking addiction should no longer be a mental death spiral.

Me burning all of my GBP. 😢 

## Changelog
:cl:
balance: Addictions can now be satisfied by having the chem in your body for 6 seconds consecutively.
balance: Roundstart junkie pills increased from 1u to 2u to more likely be able to satisfy addictions.
balance: Slight positive moodlet from satisfying addiction from a stage 2 or higher withdrawal level.
balance: Stage 0 withdrawal symptoms allows addicts to operate normally as long as they keep their addictions in check
fix: Addicts no longer constantly have a "I need x" moodlet debuff even if they're currently on the drug.
fix: Smokers should no longer be trapped in a jitter and depression spiral.
/:cl:

### CODE REVIEW

**Comment by prodirus** [comment]
I'm not sure if these tags are the right ones to use.

**Comment by Time-Green** [comment]
Does this also fix #57168 ? In short, junkie addictions cannot be in any way satiated.

Also yeah you should get GBP from this one, it's fixing an oversight in the system

**Comment by prodirus** [comment]
> Does this also fix #57168 ? In short, junkie addictions cannot be in any way satiated.
> 
> Also yeah you should get GBP from this one, it's fixing an oversight in the system

No, but it should be easy enough to remove the filter with the stage 0 stuff. Let me test it out and PR it in.

**Comment by Qustinnus** [comment]
looking over this for 2 seconds and noticed this won't work, addictions are singletons. You can't store dynamic data on them.

**Comment by prodirus** [comment]
Closing this until I think of a better way or someone comes up with a better way.

**Pull request closed without merging**
