### PR TITLE
Adds SDQL chat command

### PR DESCRIPTION
**Pull request by Cyberboss**
People who will like this: @kevinz000

### CODE REVIEW

**Comment by deathride58** [comment]
You spent so much time thinking how you could, but never stopped to think about if you *should*

mr_terry, sdql CALL SpinAnimation(1,-1) ON /obj/screen/plane_master

**Comment by Cyberboss** [comment]
Admemes aren't my responsibility

**Comment by Jordie0608** [comment]
I feel like this is a bad idea.

**Comment by Shadowlight213** [comment]
No No
just no

**Comment by kevinz000** [comment]
awww cyberboss loves me after all <3

**Comment by kevinz000** [comment]
@deathride58 SHHH NON TGMIN DONT TELL THEM

**Comment by Shadowlight213** [comment]
Time to remove kevinz from chat commands access

**Comment by Cyberboss** [comment]
Sad

**Comment by Cyberboss** [comment]
I can see legitimate remote admin uses for this though

**Comment by lzimann** [comment]
what are the good reasons?

**Comment by Cyberboss** [comment]
```
[11:22:40] <Cyberboss> its a way to find out whatever information about the game you want without needing a specific chat command for it
```

**Comment by Shadowlight213** [comment]
Mr_bagil sdql SELECT /atom

:^)

**Pull request merged**
