### PR TITLE
Removes autophago, ARDS, and alkali; bumps plasma fixation and regen coma down to level 7 to fill the void

### PR DESCRIPTION
**Pull request by ATH1909**
## About The Pull Request

The autophagocytosis necrosis, acute respiratory distress syndrome, and alkali perspiration symptoms have been removed from the game. The flesh death, choking, and spontaneous combustion symptoms still exist.

The plasma fixation and regenerative coma symptoms have been bumped down from level 8 to level 7.

Stable uranium gel, the chemical used to mutate level 8 symptoms, has been removed from the game.

## Why It's Good For The Game

These three symptoms are the station-wipers. They kill in ~2 minutes, they don't hit a virus'sf stats _too_ badly, and they're the reason why being infected by a deathvirus makes people go "welp, guess I'll die". If you have died to a virologist-made virus, you died to one of these three symptoms.

I personally believe that without these three symptoms, viruses won't have a kill speed high enough to brute force their way through people who chug healing meds or beeline to cooking up a cure. Flesh death, choking, and spontaneous combustion were not axed because they kill MUCH more slowly AND nuke your virus's stats, especially stealth and transmission, which are critical for deathviruses that don't show up on health huds and/or spread via contact.

Narcolepsy is on my radar as something that could combo with the lesser kill symptoms to get them that effective kill speed (by cutting into your actionable time before death), but I'm giving it the benefit of the doubt for now.

**Without (good) kill symptoms, antag viruses should pivot more towards debuffing and disabling the crew to set up for an easy 'bone (or trolling) instead of doing that 'bone for the viro entirely automatically while the viro huddles in maint.**

This left level 7 as a symptom tier with only 2 symptoms in it (metabolic boost and toxolysis), so I merged level 7 with level 8, which also has only 2 symptoms in it (plasma fixation and regen coma). Regen coma is still gated behind uranium access, and is arguably harder to get now because there are more symptoms in its tier.

## Changelog

:cl: ATHATH
del: The autophagocytosis necrosis, acute respiratory distress syndrome, and alkali perspiration symptoms have been removed from the game. The flesh death, choking, and spontaneous combustion symptoms still exist.
del: Stable uranium gel, the chemical used to mutate level 8 symptoms, has been removed from the game. The plasma fixation and regenerative coma symptoms have been bumped down from level 8 to level 7.
/:cl:

### CODE REVIEW

**Comment by ATH1909** [comment]
re https://hackmd.io/@Higgin/HJljdBuNp:
I believe that this PR does contribute towards the design goals set out in this document by improving the crew's ability to meaningfully fight viruses. By giving virus victims more time before incapacitation, we allow them more time to repair chemistry machines and cook cures. By reducing virus DPS, we improve the ability of normal healing meds to stave off virus deaths.

**Comment by Higgin** [comment]
> re https://hackmd.io/@Higgin/HJljdBuNp: I believe that this PR does contribute towards the design goals set out in this document by improving the crew's ability to meaningfully fight viruses. By giving virus victims more time before incapacitation, we allow them more time to repair chemistry machines and cook cures. By reducing virus DPS, we improve the ability of normal healing meds to stave off virus deaths.

I could go either way on this. The way my changes work actually nerfs all these symptoms significantly because most of them only fire their worst effects - the ones that make them most oppressive - at the max stages - so they're much less reliably firing, in my testing, in a way that gives them consistent 'DPS.' 

For instance, ARDS can dip down into stage 4 and stage 3, giving you a pretty healthy window to recover oxyloss, or at least making it a lot less reliable as a straight route to death. When it knocks you out, even, it buffs your chance to recover and reduce the stage each cycle. I do like them being there and existing as a threat - 

I'd like them to still exist at some level, but on the other hand, I can basically walk onto mining as an assistant and make a max-threshold ARDS virus with a little bit of gambling and about twenty minutes - plus variations to get around cures - with a trivial amount of risk, interdependence, or reward. 

If/when my designs get to the point of making symptoms something you find out in the wild, I could see them returning as something you quest for, or have to collect in cooperation by harvesting virus parts from other people, or mobs, or whatever it ends up looking like. 

Alternatively - could do something like moving them up to level 8 (or a new level 9?) and making level 8/9 symptoms require a chem comboing with lavaland reagents like wittel or hollow water? Something that at least admits of seeing 'the virologist is down on lavaland, that's something to worry about' or them reaching out to miners to help with getting the stuff.

Curious to hear what other folks think, but I think it's worth a shot. These would not be hard to readd.

Of all those, ARDS is the biggest offender because of the oxyloss knockout - my experience with it in testing has been that it's a lot more tame right now, and much easier dealt with if you've got at least one other person there or very basic oxyloss chems if you get into a bind (convermol in 5u from a convermol syringe heals about 135 oxyloss once it hits full scaling. It's pretty absurd.)

**Comment by Exester509** [comment]
Gotta love people only producing virology balance changes and reworks after a PR proposes its removal

**Comment by Striders13** [comment]
I'd rather be dead than live with a buffed confusion/cough virus

**Comment by Majkl-J** [comment]
> Gotta love people only producing virology balance changes and reworks after a PR proposes its removal

I mean it works!

**Review by SuperNovaa41 — APPROVED** [review]

**Comment by Nabski89** [comment]
I repeatedly tried and couldn't get Narcolepsy to do much of anything, and I think you can counter it with coffee.

I feel like the uranium/gold-silver gate is less than it was when it was originally added as a reagent because you can get it from the linked lathes now. I have fond memories of trying to convince chemists to give me silver and begging miners for permission.

**Comment by Higgin** [comment]
replacing uranium in the level 7-8 recipes with wittel would be a flex

**Comment by ATH1909** [comment]
> replacing uranium in the level 7-8 recipes with wittel would be a flex

eh, it would really just turn antag viro into a gamble; either to roll a wittel geyser in the first place or to have no one notice you down on lavaland trying to harvest it. once the virus is actually made, the result other players experience would be the same.

**Comment by moocowswag** [comment]
the symptoms and math behind them should be looked at before jumping to removal probably.

**Comment by Higgin** [comment]
> the symptoms and math behind them should be looked at before jumping to removal probably.

I've rebalanced my PR around making them (and the ceiling for transmissible bad viruses more generally) a 50% survival rate or thereabouts - #79854 - if you don't interact since they require no interaction on the deliverer's part to have an effect. 

I consider that preferable to removal here too. It keeps something cool in the game while fixing the "first principle" problem of balance.

**Comment by zeskorion** [comment]
I will note that other killsymptoms kinda suck. feel free to port some of the debilitating symptoms added by beeviro for a more interesting experience as far as antag viro goes.

especially cuz i'm softnuking it anyways 🤷‍♀️

**Pull request closed without merging**
