### PR TITLE
Removes the superfluous breathing mask from the survival box of plasmamen

### PR DESCRIPTION
**Pull request by FernandoJ8**
## About The Pull Request

What it says in the title, plasmamen no longer have a breathing mask in their survival box.

## Why It's Good For The Game

Plasmamen already start with a breathing mask equipped, they don't need a second one taking up space in their box.

## Changelog

:cl:
qol: Removes the unnecessary plasmamen survival box breathing mask
/:cl:

### CODE REVIEW

**Comment by FernandoJ8** [comment]
This isn't considered touching species code, right?

**Comment by jughu** [comment]
Keep it in

**Comment by Time-Green** [comment]
It’s still a nice thing to keep in in-case they lose their mask and end up suffocating. That is what an emergency box is for

**Comment by GuillaumePrata** [comment]
While I agree it is a good thing to have an extra, it is thrown out on the floor by the majority of the players.
If you want the extra safety, grab one in a locker, else it will just slightly decrease the random trash people throw around every shift.

**Comment by FernandoJ8** [comment]
> It’s still a nice thing to keep in in-case they lose their mask and end up suffocating. That is what an emergency box is for

No, the emergency box is for species that don't start with one and who will need one. If you REALLY need an extra mask, grab one from the many spare ones left in lockers around the station, otherwise, like Guillaume said, it's just clutter thrown on the floor roundstart

**Pull request merged**
