### PR TITLE
neurotoxin (bar drink) is no longer an instant permanent stun and instead causes severe brain damage the longer it's in you

### PR DESCRIPTION
**Pull request by ghost**
## Changelog
:cl:
balance: Neurotoxin no longer stuns for an infinite period of time and instead causes severe brain damage
/:cl:

neurotoxin is probably the root of all chemistry issues, being the one vital component in any deathmix and a hardstun that can't be escaped without antihol already in your system or negated in any fashion no matter how many stun resists you have because it stuns you constantly as long as it's in your system

rather than mute toxin + neurotoxin having mute toxin be the issue, it seems more like the chemical that stuns you and renders you unable to do anything to get any form of outside help aside from scream might actually be the issue instead

to keep it's use as a weapon, however, it now causes escalating amounts of brain damage the longer it's in you and is also a potent alcohol in and of itself, which has its own downsides. if it's still too weak i can buff it more because i don't want to take away cool shit from bartenders but a sixty second stun for like 15u is kind of silly and i think we can agree on that

### CODE REVIEW

**Comment by anconfuzedrock** [comment]
beepsky smash?

**Comment by VileBeggar** [comment]
what's with all these nerfs recently, yeesh.

**Comment by AdamElTablawy** [comment]
i wanted to do it before 4dplanner did it and removed it entirely or some shit

not that i dislike him but i'd prefer to have it in the game rather than completely obliterated

i'm working on beepsky smash later i just have to figure out how to make drinking it set you to wanted

**Comment by wesoda25** [comment]
Make it still work on xenomorphs. 

But yeah why all the nerfs this is pretty dumb. Its not even that much of an issue.

**Comment by Swiftkor** [comment]
I mean we already have impredzine for giving people crippling autism

**Comment by AdamElTablawy** [comment]
oh shit i forgot about xenomorphs i don't want to nerf serviceborg xeno thrashing

**Comment by kevinz000** [comment]
fuck someone else grabbed it

**Comment by Tlaltecuhtli** [comment]
hey i m making better neurotox change u chumb close this pr

**Comment by AdamElTablawy** [comment]
@wesoda25 as a chemist main i love the shit out of neurotoxin but it IS a big issue since it's literally the only chem you will ever consider using that isn't an experimental deathmix to see if you can make something better and, spoiler alert, you can't

hard unresistable stun > anything else you could substitute

especially paired with like, fire, so you burn to death being unable to extinguish yourself, or like 4dplanner showed pleuf + neurotox

you don't see it a lot but that's mostly due to the absolute incompetence and stupidity on the part of /tg/ as a whole rather than the lack of power behind something as grossly imbalanced as this

**Comment by wesoda25** [comment]
Fair enough. For the most part I’ve always found neurotoxin to be a pointless addition to deathmixes, since its metab rate is so high and it takes up death chem space. No real point when you can cut them to walk speed instantly, which is basically a stun in tg. 

All it’ll really do is force chemists to get a bit more creative.

**Comment by AdamElTablawy** [comment]
forcing them to move at walk speed is powerful, yes, but it gives them the opportunity to shoot back, and when using a deathmix you probably are relying on a syringe gun and not, say, a laser and tazer.

you can still kill someone with a deathmix but it doesn't mean much if they can pop antitoxin if they're still up and they can still shoot you dead before they die

a stun + any murder chem is usually enough to guarantee quick death-fire chems are only useful with stuns, lexorin is lethal enough to kill regardless, etc

**Comment by Shadowflame909** [comment]
Chloral Hydrate, Morphine and my friend Zombie Powder are about to be the only things left.

Maybe not Zombie Powder at this rate.

**Comment by 4dplanner** [comment]
Beepsky smash stuns too, and it is better for ultimate stealth

**Comment by AdamElTablawy** [comment]
i'm going to change beepsky smash to make drinking it set you to wanted as soon as i figure out how, so that won't be a concern for long

**Comment by ExcessiveUseOfCobblestone** [comment]
tfw how to stun aliens now

**Comment by Shadowflame909** [comment]
>First we lose muh ayylmao cuff

>now we lose muh ayylmao stun

Holy shit coder-base is not a fan of peaceful detainment methods

**Comment by wesoda25** [comment]
lmao wait does pax work on xenomorphs?

**Comment by AdamElTablawy** [comment]
i believe xenomorphs can get brain traumas and as a result pax should work on them, but they can still tackle you while on pax

any chemical will affect xenomorphs if it is in their system and does a damage type they are weak to-chloral will knock them out, neurotoxin will stun them, chlorine trifluoride will burn them, and so forth

(incidentally this does mean you can absolutely stop a xeno infestation in its tracks with skewium)

**Comment by OverlyGeneric** [comment]
> tfw how to stun aliens now

tfw when were becoming CM.

good pr, bro. 👍

**Comment by Cyberboss** [comment]
Other one is better

**Pull request closed without merging**
