### PR TITLE
Increases laser projectile speed

### PR DESCRIPTION
**Pull request by Bytube**
## About The Pull Request
Increases projectile speed for lasers (not including emitters and the instakill rifle).
Most lasers have had their projectile speed increased to 0.6 from the default 0.8; the hellfire laser gun, already having a projectile speed of 0.6, has been increased to 0.4.

## Why It's Good For The Game
The security arsenal is pretty weak compared to the weapons employed by antagonists, especially after the shotgun nerf. Increasing the projectile speed of their laser guns slightly will make security weapons much more viable in combat.

## Changelog
:cl:
balance: Most lasers now have slightly faster projectiles.
/:cl:

### CODE REVIEW

**Comment by itseasytosee** [comment]
Laser projectiles? You gotta get back on your meds old man this is a new era.

**Comment by Bytube** [comment]
Made a mistake and applied value changes to `/obj/projectile/beam`'s children, which have now been removed (thanks @Ewwmewgewd for pointing that out)

**Comment by vpellen** [comment]
Doesn't this compete directly with #57086

**Comment by optimumtact** [comment]
I have no interest in doing this, but I will consider the hitscan one for at least a playtest.

Closing in 24 hours

**Comment by MrDoomBringer** [comment]
image

**Comment by MrDoomBringer** [comment]
(i do not pretend to know what goes on inside oranges head this is a post)

**Pull request closed without merging**
