### PR TITLE
Secborg - Blue Edition

### PR DESCRIPTION
**Pull request by Sylphet**
## About The Pull Request

Secborg blue now. Blue good. Red bad. Wow.

https://user-images.githubusercontent.com/58074918/162540806-72256192-0244-4b90-9300-52dfbae44ff9.mp4

## Why It's Good For The Game

Secborgs are not, in policy, members of security, nor do they care about space law. They are AI aligned as any other borg is. One of the major issues with them in the past was validhunting and working with security to the point of overlooking harm. This more clearly defines them visually as /not/ part of security, improving consistency with policy and hopefully reducing the sec mindset among borgs - especially a problem given that the servers Secborgs run on are MRP and their players are subject to RP Rule 4, not exempt like security are.

## Changelog

:cl:
add: Replaced secborg sprite
/:cl:

### CODE REVIEW

**Comment by SuperNovaa41** [comment]
bikeshedding for downstreams

**Comment by Fikou** [comment]
the light blues contrast too much.
the red lights dont seem like a good idea, id do yellow/white instead

**Comment by Mothblocks** [comment]
> bikeshedding for downstreams

sec-borgs are enabled on campbell right now, and MSO wants to enable it on manuel if it works

**Comment by DaydreamIQ** [comment]
> > bikeshedding for downstreams
> 
> sec-borgs are enabled on campbell right now, and MSO wants to enable it on manuel if it works

I was wondering what the hell was up with that, If secborgs don't come back perhaps this could be a peacekeeper alt skin?

**Comment by bluetshirtguy** [comment]
why is it blue

**Comment by bluetshirtguy** [comment]
> > bikeshedding for downstreams
> 
> sec-borgs are enabled on campbell right now, and MSO wants to enable it on manuel if it works

if only the head admins could do anything about it

**Comment by Shadowflame909** [comment]
Yo, listen up here's a story

**Comment by Mothblocks** [comment]
> if only the head admins could do anything about it

head admins do not have access to campbell but also this is mostly irrelevant for this pull request

**Comment by MMMiracles** [comment]
white/yellow like fikou said would probably look better, blue makes it almost seem like its a sub-command role or some weird shit like the HoP

**Comment by Bawhoppen** [comment]
Nono this is perfect

**Comment by zxaber** [comment]
I'd say a darker blue (maybe navy?). But good change either way.

The red lights should be part of the flashlight color tbqh.

**Comment by ATH1909** [comment]
it's literally called a secborg, though

**Comment by ATH1909** [comment]
> > > bikeshedding for downstreams
> > 
> > 
> > sec-borgs are enabled on campbell right now, and MSO wants to enable it on manuel if it works
> 
> I was wondering what the hell was up with that, If secborgs don't come back perhaps this could be a peacekeeper alt skin?

yeah, I really don't get why we're trying to make the model literally named "security cyborg" into a non-member of sec. if you want a borg specialized in the neutralization of harm who isn't associated with sec, that is literally a PK borg. why are we trying to twist secborgs into something they're not instead of just working on making PK borgs more functional?

**Comment by Mothblocks** [comment]
i will put a bullet in my head before i listen to ath talk about policy revolving validhunting

**Comment by Mothblocks** [comment]
also i dont know why i got 7 confused emojis i was just the messenger

**Comment by Mothblocks** [comment]
only to the extent that it's actually **relevant to the reason this pull request was made**, secborgs are not considered members if security by administration

**Comment by Twaticus** [comment]
> only to the extent that it's actually **relevant to the reason this pull request was made**, secborgs are not considered members of security by administration

/obj/item/robot_model/security
	name = "Security"
	radio_channels = list(RADIO_CHANNEL_SECURITY)
	cyborg_base_icon = "sec"
	model_select_icon = "security"

ok you got bigger problems than some red paint

**Comment by Twaticus** [comment]
dreammaker_NU4GBT7qn6

**Comment by Mothblocks** [comment]
> ok you got bigger problems than some red paint

agree fwiw

**Comment by ATH1909** [comment]
> i will put a bullet in my head before i listen to ath talk about policy revolving validhunting

:(

**Comment by Bawhoppen** [comment]
I just think blue sec borg is funny

**Comment by wesoda25** [comment]
We could make it baker-miller pink which is used in prisons to reduce hostility and aggression. 🙂

https://en.m.wikipedia.org/wiki/Baker-Miller_pink

**Comment by Mothblocks** [comment]
i think you kid but that would be cute

**Comment by chemistrymain2** [comment]
man it's a good thing cyborg tipping exists now

**Comment by Bawhoppen** [comment]
oh my gosh I forgot we added cyborg tipping

**Comment by Coastfront** [comment]
So they're just glorified peacekeepers with a batong thistime?

**Comment by Mothblocks** [comment]
@tgstation/sprite-team

**Review by Twaticus — APPROVED** [review]
dumb

**Pull request merged**
