### PR TITLE
Ports fuzzy handcuffs and fuzzy legcuffs from Vorestation

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request
Title. Everything is tested and works.

## Why It's Good For The Game
I think this feature could really assist some of our manuel players in
roleplaying the true depth of their commitments to each other.

## Changelog
:cl:
add: Ported fuzzy handcuffs and fuzzy legcuffs from Vorestation. To get those, hack the cargo console and buy an "ERP restraints crate".
code: Coded behavior for locking legcuffs on people in a handcuff-like way. Because apparently no item in our codebase had that functionality before.
/:cl:

### CODE REVIEW

**Comment by interestingusernam3** [comment]
Epic linter fail intentional

**Comment by Serxule** [comment]
why not port species too

**Comment by interestingusernam3** [comment]
>why not port species too

Wouldn't that corrupt people's character slots or something once it'd get untestmerged

**Comment by Serxule** [comment]
> > why not port species too
> 
> Wouldn't that corrupt people's character slots or something after getting untestmerged

i thought that could maybe happen BUT when Halloween species are added its fine

**Comment by interestingusernam3** [comment]
Halloween species still exist in the code while unavaible.
If I read the code correctly, there is a datum variable called pref_species that stores character slot species. This means removing a species will result in... I don't know, invalid species pref probably gets automatically fixed somewhere if it occurs but I personally can't guarantee that it won't delete clients/prefferences, crash the game or corrupt server data.

**Pull request closed without merging**
