### PR TITLE
Removes bows

### LINKED ISSUE #25764: Firing a bow drops a spent arrow as well as firing an arrow
Take the bow and fire it, it shoots the arrow and drops another arrow, which is technically a casing, but now spent. Firing the bow with the spent casing breaks the bow and makes it so you can't fire anymore arrows.

### LINKED ISSUE #27581: Bows have multiple bugs and usability issues.
1. When firing a bow, a duplicate arrow will be spawned directly beneath you.
2. This arrow can be fired from the bow, but only once, afterwards the bow itself will be permanently broken and impossible to fire from using regular arrows, either.
3. Not sure if a bug or balance decision, but arrows do not embed even with a 45% embed chance. Shouldn't that be their selling feature? Who has ever heard of an arrow that does NOT embed??
4. Bow have extremely unwieldy loading mechanics. You need to hold an arrow in one hand, place it in the bow held in your other hand, swap TO that hand (and being careful not to grab the bow, as it will swap hands and DROP the arrow), use the bow to stretch it, THEN fire. This could all be simplified to a simple arrow -> bow is ready + swap hands.

### PR DESCRIPTION
**Pull request by ChangelingRain**
Closes #25764
Closes #27581

These don't work very well, don't show up without admin spawns, and could probably have been done in a much more simple manner.

### CODE REVIEW

**Comment by WJohn** [comment]
Honestly we could just fix these up and make them possible to craft. Doesn't seem to hard to make one, conceptually. Plank + cable or watcher sinew, and it'd be a cool item for ashwalkers.

**Comment by ChangelingRain** [comment]
That's why the sprites are still in.
"Fixing" them basically means entirely rewriting them since right now they're...... bad.....

**Comment by FantasticFwoosh** [comment]
> @WJohn : Honestly we could just fix these up and make them possible to craft. Doesn't seem to hard to make one, conceptually. Plank + cable or watcher sinew, and it'd be a cool item for ashwalkers.

Y'know this is what [diving into the ideas forum](https://tgstation13.org/phpBB/search.php?keywords=bow&fid%5B0%5D=9) to organise some feature content for the eventual code thaw is for right?

**Comment by WJohn** [comment]
Well at least the sprites aren't being removed, they're not bad, so we can rewrite them at a later date.

**Review by Cyberboss — APPROVED** [review]

**Comment by lzimann** [comment]
rip my shitcode

**Comment by Ergovisavi** [comment]
>don't show up without admin spawns,

The anomalous crystal can spawn them, reee, and now I won't be able to change that variant due to the stupid freeze

**Pull request merged**
