### PR TITLE
[READY] The AI can now think like a true intellectual

### PR DESCRIPTION
**Pull request by ghost**
:cl: Cdey78 (Ported by Floyd / Qustinnus)
imageadd: AI can now think
imageadd: New OOC emote: 🤔!
/:cl:

port from FTL

How it looks: https://gyazo.com/88aa8ffc5e2e621a073309a36dfe2d4c

Death animation: https://gyazo.com/ae2b95ff20efacd74f110d0f898fb70a

status display:
image

OOC version:
image

### CODE REVIEW

**Comment by Qustinnus** [comment]
clearly im not one

**Comment by Ratvar** [comment]
cursed

**Comment by 81Denton** [comment]
makes me 🤔

**Comment by ChangelingRain** [comment]
this thinking emoji looks very... green.

**Comment by Qustinnus** [comment]
I'm color blind and I can't sprite

**Comment by Qustinnus** [comment]
he is thinking wrong wtf learn how to thonk >:(

**Comment by MrDoomBringer** [comment]
@Qustinnus literally no u

**Comment by Qustinnus** [comment]
the pointer finger goes under the lips not before!!

**Comment by MrDoomBringer** [comment]
@Qustinnus i did that u dingus
image

**Comment by Qustinnus** [comment]
oh lol i thought the bottom one was urs

**Review by Cyberboss — CHANGES_REQUESTED** [review]
Use doombringer's sprites

**Comment by Qustinnus** [comment]
my git is still broken so i cant atm

**Comment by MrDoomBringer** [comment]
ill make status display + death animation n stuff tomo btw

**Comment by Iamgoofball** [comment]
@Qustinnus the death animation should be the emoji falling apart like in that one gif

**Comment by Qustinnus** [comment]
@Iamgoofball you mean the gif in the pr body?
the gif that has "death animation" infront of it?

🤔

**Comment by Iamgoofball** [comment]
that's it fading out of existence bro, not falling to the ground

**Comment by MrDoomBringer** [comment]
@Iamgoofball why not https://media.tenor.com/images/2a263a9aac8cd0833e4eb86d5e4ebe5d/tenor.gif

**Comment by Militaires** [comment]
goof means :thinkingapart:

**Comment by Qustinnus** [comment]
replaced it @Cyberboss

**Pull request merged**
