### PR TITLE
[wip] Clothing set picking

### PR DESCRIPTION
**Pull request by ghost**
Allows certain jobs to spawn in different clothing sets, selected in the preference level menu.

Replaces the nazi greatcoat with a warden-style police jacket for corporate HoSes.
Adds red jumpsuits for most security jobs.

### CODE REVIEW

**Comment by Nienhaus** [comment]
It might be a good idea to add choosing between the labcoats or something...

**Comment by paprka** [comment]
Huh?

**Comment by Dorsisdwarf** [comment]
Since the description isn't clear, the Nazi greatcoat is still in the locker if you don't take papcurity right?

**Comment by paprka** [comment]
"Replaces" isn't clear enough?

**Comment by ike709** [comment]
What if I want to commit clown genocide?

**Comment by paprka** [comment]
If i readd the greatcoat it will be a steal objective too :laughing:

**Comment by ike709** [comment]
readd it then

**Comment by paprka** [comment]
Going to work on this a bit more before making a PR actually.

**Comment by Steelpoint** [comment]
I did some quick testing. As noted its rough but looking cool.

As I've stated I would prefer the HoS be able to select the department's style for the round, but baby steps.

I did note that Officers choosing the tactical sprites still use the corporate armour vest.

Anyway, looking forward to see where this goes.

**Pull request closed without merging**
