### PR TITLE
Removes Tactical Game Cards.

### PR DESCRIPTION
**Pull request by ArcaneMusic**
## About The Pull Request

This pull request removes Tactical Game Cards from the game.

In scope, this includes the card system itself, card holders, the unit tests, relevant Admin Verbs, and the Holodeck Simulation.

## Why It's Good For The Game

Following some discussion, it would seem that there's no maintainer interested in looking at changes for it. If that's not the case then my all means this would be a place to discuss it, but as it stands right now none of the three original developers of the TCG, between Potato, EOB, or myself really have any strong direction or desire to overhaul the system or to review associated changes related to the feature, and perhaps it's for the best that we simply scrap it and reapproach it from it's original design angle, that being a collectable system with some sort of persistency.

## Changelog

:cl:
del: The Tactical Game Cards Collectable Card Game has officially been shuttered, as a consequence of running out of Redwoods.
/:cl:

### CODE REVIEW

**Comment by ExcessiveUseOfCobblestone** [comment]
Im not really inclined to merge this, I think theres a sane middle ground of "its a collectible mechanic but if people want to play it proper we will support that too", with the focus being a cute collectible mechanic while also giving the people who want to giga game on it their space to do so as well.

If I was told "no, we dont want there to really be a game associated with it and just make it collectibles"then I would respect that, but it seems like its just kinda in the ether right now about where anyone wants to take this and, given it's completely contained currently, I don't see any reason to scrap it in the interim.

going to put DNM just so any interested party can talk it out w me.

**Comment by deathrobotpunch** [comment]
the fuck.

**Comment by deathrobotpunch** [comment]
https://github.com/tgstation/tgstation/pull/86288

https://github.com/tgstation/tgstation/pull/86288

**Comment by Timonkeyn** [comment]
Who even cares if the TCG is maintained or not? I would be more inclined if you argued on the basis of disabling the holodeck level instead of removing it as a whole since the cards themselves barely have any unique functionality (if any)

**Comment by Archie700** [comment]
I think we need a really good reason why they should be removed if no one wants to maintain it besides "no one wants to maintain it".

**Comment by necromanceranne** [comment]
I'm not usually so vocal about minor content I don't even use, but from what I could see, EuSouAFazer is at least trying to do something with the content you lot haven't touched in literal years. It is beyond shitty to just abort the feature the moment it starts getting any attention from a developer looking to expand it or improve it.

It is equally shitty to then stonewall that dev because none of you can allow enough personal distance from the project that has sat almost untouched for years to let someone else change its course or make something of it themselves. Give them a bloody break.

**Pull request closed without merging**
