### PR TITLE
Adds PDA-Message Photo Attachment

### PR DESCRIPTION
**Pull request by AnturK**
Has science gone too far?

Still not sure if this is useful for anything but(t) gimmicks or a good idea but whatever.
Also it now says (Photo) instead of (ATTCH), couldn't be bothered to make another screenshot.

### CODE REVIEW

**Comment by GunHog** [comment]
Can AIs send these as well?

**Comment by AnturK** [comment]
Oh. Good point. Totally forgot they use their own verbs. Will add it in a moment.

**Comment by Chocobro** [comment]
are we able to send text at the same time? like a caption. because space twitter

**Comment by AnturK** [comment]
Not sure how to make the AI prompt less annoying if you don't want to send pictures but have taken some.

Caption ? You mean the window name ? I guess i could add it but i'm not a fan of too many popups at once.

**Comment by AndroidSFV** [comment]
I was going to do this sooner or later (probably much later). Looks nice!

**Comment by PKPenguin321** [comment]
Now ERPers can send nudes :+1:

**Comment by SconesC** [comment]
Hilarious, merge posthaste

**Comment by SconesC** [comment]
Is this in the clear?

**Comment by AnturK** [comment]
This is finished if that's what you're asking.

**Comment by SconesC** [comment]
Get it innn

**Comment by phil235** [comment]
A changelog would be nice.

**Pull request merged**
