### PR TITLE
Several surgery improvements

### PR DESCRIPTION
**Pull request by XDTM**
Hello i'm back

## About The Pull Request

Made a bunch of changes to surgery in general to improve the quality of life of normal and underhanded surgery.

Change list:
- **Surgery now gives detailed description to the surgeon and anyone within one tile of distance, and more vague or ambiguous descriptions to the patient and anyone further away.** This can lead to a surgeon being able to perform a brainwashing in place of a brain surgery with nobody being the wiser, or implanting a different organ than the one agreed on, and so on.
- **Using the wrong surgery tool no longer attacks the patient**, as long as it is in help/disarm intent and the tool is in fact meant for surgery.
- **Added a new surgery, Muscled Veins**, as the contrast to Vein Threading: it makes the patient able to survive without a heart.

Minor changes:
- Separated the STABLEHEART trait in STABLEHEART and STABLELIVER. Anything that already gave STABLEHEART now also gives STABLELIVER, so there is no gameplay change.
- People lying down can no longer use the surgery console (to prevent peeking).
- The visible_message proc can now take a list of mobs to ignore instead of only one.
- Lowered the cost for Advanced Surgery by 1000 (since @ExcessiveUseOfCobblestone lowered the export price instead of the research cost on their PR).
- **"The Necrotic Revival surgery now uses a syringe/pen instead of a hemostat.**

## Why It's Good For The Game

Makes it easier for people not confident in surgery since their mistakes will not be broadcasted to everyone in the room nor they will hurt the patient.
Makes it possible to do sneaky surgery on unsuspecting patients without knocking them unconscious first.
Adds another advanced option for people trying to create the perfect human; it's still a choice between near-immunity to bleeding and heart attack immunity, since you can only get one.

## Changelog
:cl: XDTM
add: Added a new advanced surgery, Muscled Veins: it makes the patient able to survive without a heart.
add: Using the wrong surgery tool during surgery no longer attacks the patient, if on help or disarm intent.
add: Surgery steps are now shown in detail only to the surgeon and anyone standing adjacent to them; the patient and people watching from further away get a more vague/ambiguous description.
tweak: The Necrotic Revival surgery now requires a syringe instead of a hemostat.
fix: Lowered the cost of the Advanced Surgery techweb node by 1000 (as intended with the addition of the new healing node).
/:cl:

### CODE REVIEW

**Comment by vuonojenmustaturska** [comment]
`Started the traits_2 var on atoms, since the traits_1 var was out of spaces.` i assume you mean flags_* ? There's still more room there, bitfields were expanded to 24 bits in 512.1427

**Comment by ExcessiveUseOfCobblestone** [comment]
Nightcoding is bad okay?!!

**Comment by XDTM** [comment]
Europe exists

**Comment by AffectedArc07** [comment]
@ExcessiveUseOfCobblestone bedcoding tends to work well though

**Comment by adamkad1** [comment]
> Europe exists

whaddya mean europe exists?

**Comment by ExcessiveUseOfCobblestone** [comment]
I was referring to

> Lowered the cost for Advanced Surgery by 1000 (since @ExcessiveUseOfCobblestone lowered the export price instead of the research cost on their PR).

**Comment by KomradeSpectre** [comment]
Does Muscled Veins prevent the Hivemind heart attack ability?

**Comment by OverlyGeneric** [comment]
hey, at least it's more interesting and helpful than broken bones.

Frankenstein-esque surgery should be a thing and this is a step towards that direction.

**Comment by XDTM** [comment]
> 
> 
> I was referring to
> 
> > Lowered the cost for Advanced Surgery by 1000 (since @ExcessiveUseOfCobblestone lowered the export price instead of the research cost on their PR).

Whoops i misinterpreted

**Comment by Arathianen** [comment]
Great changes. I especially like buffing doing "fake"/misleading surgeries. Brainwashing might actually be used for a change.

**Comment by CRITAWAKETS** [comment]
Muscled veins feels kind of useless since heart attacks are so infrequent anyway. How about making it faster blood regen?

**Comment by XDTM** [comment]
Nah, the alternative already helps with blood loss. Heart attack immunity is pretty niche, but it's also free to get and it does prevent a near-instant death from those rare sources.

**Comment by ninjanomnom** [comment]
This really needs to be split into multiple prs

**Comment by FloranOtten** [comment]
Does it hide the advanced surgery steps from the patient? What'd be the point of sneakily doing brainwashing instead of brain surgery if the patient can see, get up and clubber you over the skull?

**Comment by XDTM** [comment]
The patient only gets the vague description, yes

**Comment by ninjanomnom** [comment]
On checking the actual changes in this pr again I'm surprised at how many things you've combined here.

There are way too many changes bundled in this pr. You need to make new pull requests that actually separate out these things so they can be reviewed properly and approved or denied individually.

**Comment by XDTM** [comment]
I'd atomize this, but i cannot for the life of me figure out how to extract single files from commits with git (why is git so unnecessarily complicated?).
I don't exactly relish the idea of manually undoing the unrelated changes and repeating that for several PRs either, so i guess i'll just let this one go.

**Pull request closed without merging**
