### PR TITLE
buffs chainsaws a bit

### PR DESCRIPTION
**Pull request by ghost**
Fire axes:
Can be held in one hand for space.
Can be held on back for space.
Deals 24 damage.
Found in atmos and bridge
Chainsaws:
Must use 2 hands at all times
Cannot be stored anywhere on body
Deals 21 damage
Found nowhere, must be crafted with plasteel (engineering or mining), circular saw(robotics or medical and you can't take it as they NEED it for surgery, maybe cargo but i'm not sure on that), and wire. some tools needed.

So there, that's why i'm increasing the force of the chainsaw by 3 points! Thank you john nuclear for teaching me how to git.

### CODE REVIEW

**Comment by Armhulen** [comment]
i forgot to do the surgery attached chainsaw, i'll get to that in a second. yay for first prs!

**Comment by Armhulen** [comment]
i made a mistake with git, i'll fix it and make a new pr

**Comment by DoctoreMad** [comment]
>plasteel (engineering or mining), circular saw(robotics or medical and you can't take it as they NEED it for surgery, maybe cargo but i'm not sure on that), and wire. some tools needed.

Wow. A common in-station metal, something that can be made in a autolathe, wire, and some tools which you can easily get.

**Comment by Armhulen** [comment]
WAIT MISTAKES MAKE AGAIN FIXING ONE SECOND

we'll talk balance once this works

**Pull request closed without merging**
