### PR TITLE
Moves TgsInitializationsComplete call to immediately after world/New()

### PR DESCRIPTION
**Pull request by Cyberboss**
Reason: #39770 

As it stands, we aren't prepared to share the data folder with another server during initializations so this is necessary until that issue is fixed

### CODE REVIEW

**Comment by Cyberboss** [comment]
still need to look at banlist and icon cache

**Comment by Cyberboss** [comment]
@SpaceManiac ideas for the icon cache?

**Comment by Cyberboss** [comment]
Also spritesheets

**Comment by SpaceManiac** [comment]
the spritesheet files are just caches, not actual persistent data, I forget whether it's the css or the png but one of the two needs to keep existing for BYOND to be able to send it to clients

**Comment by MrStonedOne** [comment]
That could be fixed.

`fcopy_rsc()` allows you to copy an asset into the dyn.rsc file and returns a pointer/reference that can be added to the asset cache or otherwise sent via browse_rsc.

There is zero reason to keep the files around

**Comment by Cyberboss** [comment]
Alternatively, we could add a `tmp` folder at the root level we use for
stuff like this that just wouldn't be linked

**Comment by Cyberboss** [comment]
Forgot to take off WIP. Think I got everything.

**Comment by optimumtact** [comment]
conflicts

**Comment by optimumtact** [comment]
stale

**Pull request merged**
