### PR TITLE
Fixes lighting of pixel shifted objects and reverts the hacky memleak fix + other lighting fixes

### PR DESCRIPTION
**Pull request by MrsTonedOne**
Fixes lighting of pixel shifted objects and reverts the hacky memleak fix.

~~more details in a moment.~~

Lighting will now cast from the pixel turf using get_turf_pixel, but have the view() of the loc turf.

before:
image
After:
image

This also reverts #24754 since the proper byond version is out.

This might also fix some oddities with fractional light ranges but only time will tell.

Renamed lighting overlay to lighting object because people would assume it was a byond overlay when it is not.

Fixed a few typed loops i saw.

Made recalc_atom_opacity cheaper.

@PJB3005 

TODO:

- [x] This broke turfs having lighting. I need to fix that.
- [x] I found a issue in how lighting is queued in the SS that is leading light updates to get delayed by a few ticks. I must crush this.
- [ ] Test after rebase

Reverts "Lighting micro optimizations and fixes (#24939)"

### CODE REVIEW

**Comment by MrPerson** [comment]
I gave this a quick once over and it seems ok

**Comment by Razharas** [comment]
>more details in a moment.

>MrStonedOne commented an hour ago

**Comment by PKPenguin321** [comment]
Is this the PR that will remove color lights bleeding through walls or is that going to be in a future MSO "Godtier Lighting" Series PR™️?

**Comment by MrStonedOne** [comment]
That will be in a future pr.

I need to shave off some performance issues to make room for walls having 2 to 4 lighting objects

**Comment by MrStonedOne** [comment]
I'm going to have to just manually re-do this pr.

**Comment by MrStonedOne** [comment]
too many conflicts

**Comment by MrStonedOne** [comment]
thanks @Cyberboss

**Comment by MrStonedOne** [comment]
On second thought, i'll just revert cyberboss's pr before doing the rebase

**Comment by MrPerson** [comment]
I hate to be That Guy but this will also conflict with #25046 somewhat. Luckily I don't think it will be too too bad, so I'm extremely happy to resolve the conflicts myself.

**Comment by MrStonedOne** [comment]
only one line of one commit. Nowhere near as bad as 5 seperate hunks each of 3 files in just 1 commit before the rebase even touched the next set of commits that all touched the same files.

**Comment by AnturK** [comment]
Fixes #24872

**Pull request merged**
