### PR TITLE
WOOPS I made grilleshocks cause explosions

### PR DESCRIPTION
**Pull request by silicons**
Honk!
fuck i put in two arguments and forgot to update it reee
edit: for those of you who aren't into reading goofcode, this makes every lightning bolt explode things and stun things, instead of only tesla. everything else still should be stunning, though.

### CODE REVIEW

**Comment by GunHog** [comment]
Thanks Kev

**Comment by anconfuzedrock** [comment]
remove it already people can just use the glass shard

**Comment by kevinz000** [comment]
@anconfuzedrock Grilles are NOT the only thing this affects, and their purpose is not for glass shards.
read the code pls.

**Comment by Arianya** [comment]
Emergent gameplay. Keep it in.

**Comment by XDTM** [comment]
Oh good now i can use tesla traps without it blowing up its own wire

**Pull request merged**
