### PR TITLE
Held health analyzers show surgery steps

### PR DESCRIPTION
**Pull request by FlufflesTheDog**
## About The Pull Request
Holding a health analyzer in your off-hand while performing surgery will give you reminders for what the next step of a surgery is, both at the end of each step and if you attempt to use an incorrect tool. Inspired by https://github.com/tgstation/tgstation/pull/77362#issuecomment-1665109332, because I couldn't think of a way to have operating computers soft-link to stasis beds in a way that made any sense (iirc the lore is that advanced surgeries are simply the computer telling you how to do them)

image
## Why It's Good For The Game
Needing to memorize dozens of different surgeries before you can become a viable doctor is brutal for new players. Making the steps easier to see without checking the wiki every two seconds will make the job more approachable and give people a more interactive path towards improving.
## Changelog
:cl:

qol: Health analyzers will now helpfully remind you how to continue a surgery

/:cl:

### CODE REVIEW

**Comment by Serxule** [comment]
i agree this is good qol, but itd make operating tables/computers useless for new players (new players likely wont be doing research surgeries), and only used for surgeries which you cant do normally, until you get a surgical processer module for your modsuit in which case they are now fully useless for anyone

**Comment by DATA-xPUNGED** [comment]
Remembering the steps without the use of a surgery computer is a part of getting good at medical. Also, doctors are ALREADY too reliant on health analyzers imo

**Comment by FlufflesTheDog** [comment]
> itd make operating tables/computers useless for new players

They're already useless/under-used in my experience, new players rarely have a decent enough supply of formaldehyde or epi pens to be able to use surgery tables in the first place, so surgery tables end up being a sure-fire way to make things even harder on yourself, when you can take your time on stasis and keep tabbing over to a wiki (which is a jarring and immersion ruining experience, imo)


> Remembering the steps without the use of a surgery computer is a part of getting good at medical. Also, doctors are ALREADY too reliant on health analyzers imo

I'm absolutely one to advocate for a high skill ceiling on jobs, but I think making meaningfully participating more difficult doesn't really help with that. Doctors that rely on the health analyzer for surgery steps will still be notably more clunky and slow just on the merit of needing to stop each step to check the readout, so good doctors will still be apparent and valued.

And as cool as it sounds to need to rely on more varied tools to diagnose problems (I would love a reason to use the new stethoscope and penlight features,) something geared towards accessibility for new players ideally needs to be on a very accessible item that they're already encouraged to use

**Comment by Jacquerel** [comment]
I like this as a feature of operating tables (where you should be doing surgery) while teaching new players to do surgery on stasis beds (where people should be waiting for triage) is something I would like to discourage. 
This does the latter.

**Comment by GuillaumePrata** [comment]
This PR doesn't give anything that alt tabbing doesn't give.

I hate stasis surgery way more than the average person, but if we want the surgery theaters to be used more, we should figure out another way to achieve it that isn't blocking information from new players.

**Comment by VladinXXV** [comment]
My biggest concern with this is tend wounds. At present, the health analyzer already serves the very important purpose of telling you the damage level after each tending. With this for each tend as well, it's going to make for a VERY cluttered chat.

I can appreciate the idea here, but ultimately, it isn't that hard to let the surgery computer tell you what comes next. Even guessing is good enough for most surgeries, since they tend to follow a similar structure and toolset (granted, there are oddballs in there).

From my experience, the lack of formaldehyde is definitely the biggest barrier to more frequent operating table usage, followed by burn wounds at risk of infection. I'd rather see formaldehyde become more available and less of a hassle to use. The mixed medipen crate is a great option, but underutilized and not quite enough, in my opinion. Formaldehyde patches are not that hard to make, but chemistry is not fun and you will not force me to do it. The bottles given to paramedics and the coroner are the greatest offenders. I do not want to inject 5u at a time with a syringe or fumble with a cadaver's mask and glasses to try and squirt it into their eyes.

The best solution is educating players on good practices, I think. The bottles of formaldehyde given to the coroner and paramedics can easily be turned into 1u patches, which can be stuffed into pill bottles to be carried on medical belts and such 7 at a time.

**Comment by iwishforducks** [comment]
this is a good PR. not sure why there's so many naysayers worried about the usefulness of surgery tables. if the balance of surgery tables rely on how much metaknowledge you have then... lol? like you all realize how ridiculous that sounds, right?

yes, learning the surgery steps is a skill, sure, but the only thing this does is make metaknowledge more readily available rather than having to alt tab. i know that's what i did when i first started medical: i would just have the wiki page open for the surgeries. all this does is make metaknowledge more streamlined and friendly to new players in-game.

with that said, two worries, one of which was brought up just the comment above me:

tend surgeries- does it spam chat when you use the surgery?

how should new players be taught this? it's sorta difficult for them to manage their hands. i know a lot of medical doctors don't know about the tend + offhand analyzer trick. absolutely out of scope of this pr but we should figure out how to push new players to use this

**Comment by FlufflesTheDog** [comment]
There's no prompt at the end of auto repeatable steps, so tending isn't spammy. 

As for teaching new players about this, perhaps I could add an examine message to analyzers or perhaps a remark on the surgery selection screen, but I'm sure it'll largely be via the normal ways players discover new mechanics, by reading the wiki or by some helpful soul telling them. I also like to think there's decent odds people scan someone, start a surgery to fix something, and find out by luck.

**Comment by CoiledLamb** [comment]
> I like this as a feature of operating tables (where you should be doing surgery) while teaching new players to do surgery on stasis beds (where people should be waiting for triage) is something I would like to discourage. This does the latter.

big agree! this is a cute feature, but detracts from the actual benefit of operating rooms... which is already pretty good for communicating game information in a comprehensive, IC way.

**Comment by SimplySmiley123** [comment]
> i agree this is good qol, but itd make operating tables/computers useless for new players (new players likely wont be doing research surgeries), and only used for surgeries which you cant do normally, until you get a surgical processer module for your modsuit in which case they are now fully useless for anyone
> 
> also, operating computers used to work for stasis beds, that was specifically a removed feature

To be honest, barely anyone if ever at all uses surgical processor in a modsuit, especially since paramedics use it way more then doctors do.

**Comment by YehnBeep** [comment]
A thought:

What if health analyzers at least had a warning line along the, well, lines of "Warning: Patient organs decaying. Apply formaldehyde or use a stasis bed to halt this." ?

Now I bet most newer players would reach for the latter so I don't think it fixes the issue very well, but the one thing I think it would do is help prevent "I tried to do surgery on a surgery table and their organs kept dying so now I just always use a stasis bed" becoming a sort of default.

A possible second step could be clearer indicators that formaldehyde is in epi pens, or maybe having a small amount start next to surgery tables, or so on.

**Comment by Ryll-Ryll** [comment]
This definitely seems like a good improvement 👍

**Comment by ZephyrTFA** [comment]
I don't want this as a function of the health analyzer; as it removes 90% of the reason for operating computers to exist.

**Comment by Kapu1178** [comment]
isnt 90% of the reason operating computers exist so you can perform upgraded surgeries? bruh?

**Comment by LemonInTheDark** [comment]
> I don't want this as a function of the health analyzer; as it removes 90% of the reason for operating computers to exist.

ok you need to talk to ryll then, since they seem to support it

**Comment by carlarctg** [comment]
why are we gating new player helpful information to operating computers? you dont need mesons to examine a reinforced wall and get the next deconstruction step?

**Comment by Serxule** [comment]
> you dont need mesons to examine a reinforced wall and get the next deconstruction step?

my guy what are you even talking about

**Comment by FlufflesTheDog** [comment]
To elaborate on why I think this is good, I'll say that I think having "memorize this list of steps, and do it again for every one of the dozens of surgeries in the game" as a substantial "good at your job" milestone to be very uninteresting gameplay. 

It's not dynamic, there's no problem solving, there's no challenge or actual skill. To me the fun part, and the part that I think makes someone a **good** doctor, is the ability to look at a patient and figure out what's wrong, and what treatments would best fix those problems (possibly asking for help from someone like a chemist or geneticist in the process). And even potentially deciding to leave some problems towards the end or until after you deal with another patient.

I think the comparison to construction above does actually have its place here; ANYONE can just grab some tools and figure out the dozen random steps to (de)constructing most structures, just by examining things. No fumbling through the wiki required. The same concept is shown in robotics, where anyone can examine an exosuit to see exactly what parts and tools you need to finish construction. Even though the various mechs also follow a very similar formula between them.

I don't think medical should be any exception. Surgery shouldn't have obscure steps that require either constantly checking the wiki, or risking tradeoffs like organ decay just to do your job.

**Comment by Jacquerel** [comment]
you don't need to memorise the steps for surgery because the place you're intended to do surgery already tells you what the steps are

**Comment by iwishforducks** [comment]
> you don't need to memorise the steps for surgery because the place you're intended to do surgery already tells you what the steps are

Intended place or not, surgeries still happen on stasis beds and even outside of medical at times. I would say a significant number of surgeries take places in unintended places.

**Comment by CoiledLamb** [comment]
> > you don't need to memorise the steps for surgery because the place you're intended to do surgery already tells you what the steps are
> 
> Intended place or not, surgeries still happen on stasis beds and even outside of medical at times. I would say a significant number of surgeries take places in unintended places.

i personally feel like it's fine for unintended places to do surgery to be less convenient overall

**Comment by iwishforducks** [comment]
It's hardly about convenience; it's all about metaknowledge. A lot of work has been put into making sure the wiki is needed less and less, and I see this as a good way to push people away from having to read wiki pages and instead easily interact with the game and learn.

**Comment by DATA-xPUNGED** [comment]
> It's hardly about convenience; it's all about metaknowledge. A lot of work has been put into making sure the wiki is needed less and less, and I see this as a good way to push people away from having to read wiki pages and instead easily interact with the game and learn.

You REALLY don't need to pull out the wiki to do surgery without an operating computer. There is no penalty like in goon to just try the tools

**Comment by Serxule** [comment]
> > It's hardly about convenience; it's all about metaknowledge. A lot of work has been put into making sure the wiki is needed less and less, and I see this as a good way to push people away from having to read wiki pages and instead easily interact with the game and learn.
> 
> You REALLY don't need to pull out the wiki to do surgery without an operating computer. There is no penalty like in goon to just try the tools

also yeah this entirely, i never once used the wiki for surgery, i learned via trial and error (and occasionally the operating table)

**Comment by WitherVictor** [comment]
> isnt 90% of the reason operating computers exist so you can perform upgraded surgeries? bruh?

One of the most important reason to use operating computer is advanced surgery, carbon-based need that

**Comment by MrMelbert** [comment]
@Mothblocks I know you said at one point you like Surgery Computers as the means of displaying surgery steps because it was "IC", is this a logical extension of that or do you still prefer the computers

image

**Comment by ExcessiveUseOfCobblestone** [comment]
Having a new player know they need to carry a health analyzer to prompt the next step is really a lot less intuitive than asking they go the surgery zone to learn how to do the surgery. Nothing about the health analyzer would suggest it has that functionality.

If we are strictly speaking about the obscure information piece, I think it should just straight up tell you the next step without any item needed in a narrative way IE "Looks like you need to _retract_ the muscles, opening the chest cavity" akin to construction steps. You're a doctor, you shouldnt need a device to tell you what your character can already see and know with their IC knowledge.

**Comment by Mothblocks** [comment]
> @Mothblocks I know you said at one point you like Surgery Computers as the means of displaying surgery steps because it was "IC", is this a logical extension of that (since it's still IC) or do you still prefer the computers as the primary method of surgery tutorials
> 
> image

i don't care about this change, but to answer your question strictly in a vacuum: this is IC and the message you're posting is in context to i believe in-UI overlays and such for helping the same thing

**Review by ExcessiveUseOfCobblestone — CHANGES_REQUESTED** [review]
The changelog being the only way to know this functionality exists is counter-intuitive to the point of this PR, needs to be reflected on the health analyzer or something.

**Comment by ZephyrTFA** [comment]
I still think this should be a dedicated item if you insist on disassociating it from the operating computer and not put on the health analyzer.
There is too much shit tacked onto it

**Comment by FlufflesTheDog** [comment]
I don't really disagree, but I think anything less convenient would be used drastically less. Even something available round start in the lathe would be very easy to overlook because of how many different items there are already. 

There was the option mentioned above not needing a tool at all, perhaps just by examining the patient. Mixed feelings on this, it would be great for accessibility, and further slow down the process for doctors that use it, rewarding actual knowledge. But it could destroy examine messages with clutter in the case of multiple surgeries, along with perhaps making the knowledge too accessible, eg for ghetto surgery.

Alternatively, perhaps I could move the functionality to wound analyzers? I had assumed they were a bit too "simple" to be describing operations, but their re-worked flavor of having holograms guiding the user through wound treatment, the functionality would sort of fit in. I can get behind this since it's still an item new doctors will randomly stumble across, and it would be nice to see them finally get some use.

**Comment by ZephyrTFA** [comment]
> 

I'll let @MrMelbert decide on that one

**Comment by Mothblocks** [comment]
> I still think this should be a dedicated item if you insist on disassociating it from the operating computer and not put on the health analyzer. There is too much shit tacked onto it

I don't agree at all--it would just make that item go completely unused and defeat the purpose

**Comment by ZephyrTFA** [comment]
> > I still think this should be a dedicated item if you insist on disassociating it from the operating computer and not put on the health analyzer. There is too much shit tacked onto it
> 
> I don't agree at all--it would just make that item go completely unused and defeat the purpose

so if the there was an item for showing surgery steps it wouldn't be used unless it also had twenty other things attached to it

**Comment by Jackraxxus** [comment]
What if
Skillchip
or do doctors already get one idk

**Comment by Mothblocks** [comment]
> > > I still think this should be a dedicated item if you insist on disassociating it from the operating computer and not put on the health analyzer. There is too much shit tacked onto it
> > 
> > 
> > I don't agree at all--it would just make that item go completely unused and defeat the purpose
> 
> so if the there was an item for showing surgery steps it wouldn't be used unless it also had twenty other things attached to it?

Correct because the exact people we're trying to teach won't know to use that item.

The best way to solve this is surgery computers should link to the stasis beds, not give bonus surgeries, and be placed automatically.

**Comment by Mothblocks** [comment]
I think I feel pretty strongly about that being the right solution for this because it's even more obvious than "hold out a health analyzer"

**Pull request closed without merging**
