### PR TITLE
Fixes warden hat leaving a space before message when in Canadian mode

### PR DESCRIPTION
**Pull request by Burgermancoding**
## About The Pull Request
This pull request fixes the warden's hat whilst it is in Canadian mode by stopping it leaving a space before your message, example if I were to say E it would show up in chat bar with a space before the e like " E", also fixes typos in canadian_replacement.json 
## Why It's Good For The Game
This is good for the game because it fixes an annoying bug/error in the chat and the typos will have made it so people didn't get the conversion after typing a message

## Changelog
:cl:John Burgerman
fix: warden's police hat now no longer leaves a space before your message and people should now get Canadian conversions when they did not previously, cigarette will now convert to dart and scuffle will now convert to kerfuffle 
/:cl:

### CODE REVIEW

**Comment by RaveRadbury** [comment]
image
Might want to pull the 'r' out of what I assume is "scuffle" here

**Comment by Burgermancoding** [comment]
Good spot thanks, fixed this too

**Comment by Mothblocks** [comment]
be more specific in the changelog about your change to cigarette and the other word

**Comment by Burgermancoding** [comment]
OK I did it

**Comment by tgstation-server** [comment]
Your Fix/Feature pull request delta is now above zero (0). Feel free to make Feature/Tweak/Balance PRs.

**Pull request merged**
