### PR TITLE
Adds A New Funny Emote. (April Fools PR)

### PR DESCRIPTION
**Pull request by Xymec**
## About The Pull Request

Uhh... April Fools? Jokes aside, this adds a new sound effect (The vine boom sound effect of course.) and a new emote that uses the sound effect.

## Why It's Good For The Game

It's april fools, why don't we just have a little fun, huh?

## Changelog

:cl:
add: Added a new emote
soundadd: Added A New Sound.
/:cl:

### CODE REVIEW

**Comment by MrDoomBringer** [comment]
@Xymec I think you forgot to add the actual emote

**Comment by Xymec** [comment]
> @Xymec I think you forgot to add the actual emote

Strange, I swore i had 2 commits coming in.

**Comment by Xymec** [comment]
> @Xymec I think you forgot to add the actual emote

wait, nevermind, yeah, i did, my bad.

**Comment by Fikou** [comment]
we already have the vine boom effect in the codebase

**Pull request closed without merging**
