### PR TITLE
Flushes Ling & Alien HUD info with the edge of the screen

### PR DESCRIPTION
**Pull request by Robustin**
While most of our HUD looks good, I can't help but feel that the stuff that looks like it should be growing in from the edge of your vision shouldn't detached from the edge like it is now.

Screenshots:
http://imgur.com/a/5IjnG
http://imgur.com/a/kBw0G

If anyone can think of other examples, let me know and ill add them

### CODE REVIEW

**Comment by ShadowDeath6** [comment]
Ling one kind of bugs me, can you do something more than just add that extending part? It feels out of place with the rest of the chemical storage icon. Might be because it's there by itself rather than part of a group of icons

Alien one looks good on that note though

**Comment by Robustin** [comment]
It was deliberately put on the left because it was already competing with the human's internals, health, and health doll. The sting icon also appears on the left.

I'm not gonna change that unless there's a large enough outcry about it.

**Comment by ShadowDeath6** [comment]
I know why it's on the left side, but it just looks weird with the ovals(?) on the left side of the icon. Could you maybe move the white parts of the icon further left to meet the side of the screen?

**Comment by Militaires** [comment]
the design on them is eh, if they could be more simplified tabs rather than tumors with bulges and shit that'd be great, they're fat rn.

**Comment by KorPhaeron** [comment]
@Wjohn up to you

**Comment by ChangelingRain** [comment]
do note that the alien hud has alerts for, like, fire and stuff, and you need to consider their positioning.

**Comment by Militaires** [comment]
Too Hot!

and 

Plasma

**Comment by Robustin** [comment]
I believe those are overlays for the health monitor but I'd have to double check

**Comment by ChangelingRain** [comment]
they use the actual alert system, and you can't change the positioning of that so you'll probably end up closing this pr

**Comment by Robustin** [comment]
Well not quite, its no different than the ling chem display and the ling sting popup.

It doesn't look awkward for there to be an organic part of the HUD and then in the vicinity you have traditional HUD elements. Its like saying you can flush the LING chemical tracker because its near the Head_Slot and Sting display.

**Pull request merged**
