### PR TITLE
adds the Delinquent Hat

### PR DESCRIPTION
**Pull request by hornedmoth**
## About The Pull Request
This is a reskin of the basic cap item, made to look like a certain Crusader of Stardust. 
It is sold by the Costume Vendor. 

## Why It's Good For The Game
We already have holoparasites, i believe it'd go along nicely with them.

## Changelog
:cl: Cephur sprites, Tralezab code
add: Added a new hat to the costume vendor
/:cl:

### CODE REVIEW

**Comment by PKPenguin321** [comment]
now do one with a goofy green headband with a heart on it

**Comment by SynnGraffkin** [comment]
yare yare daze

**Comment by Fikou** [comment]
good george melon grief...

**Comment by nervere** [comment]
Tralezab committed to master and this master branch is so far out of date that it's a huge headache trying to bring it up to speed with the latest spritesheet, I'm going to remake this on an updated branch.

**Pull request closed without merging**
