### PR TITLE
Crab Protocol Now has Limited Stock

### PR DESCRIPTION
**Pull request by wesoda25**
## About The Pull Request

You can now only buy one crab protocol. 
## Why It's Good For The Game

Spam sucks. Its honestly funny as shit, but each announcement blocks out the screen, and has the most fucking annoying sound. 

## Changelog
:cl: weeweesoda
balance: The CRAB protocol traitor item now has a maximum stock of 1 each round
/:cl:

### CODE REVIEW

**Comment by plapatin** [comment]
bzzz bzzz

**Comment by wesoda25** [comment]
@Qustinnus idk if you care or not or whatever but ill ping you anyways since its your brainchild or whatever

**Comment by PKPenguin321** [comment]
should be 1 imo

**Comment by necromanceranne** [comment]
I hope I get war ops before this is merged because I wanna convince my nukie team to spend the entire budget on crab phones

**Comment by wesoda25** [comment]
> I hope I get war ops before this is merged because I wanna convince my nukie team to spend the entire budget on crab phones

What do you think prompted me to make this PR?

**Comment by HomocidlePancakes** [comment]
>5 uplinks
2 phones per uplink
10 phones total

*laughs in dead currency*

**Comment by daklj** [comment]
dont forget infinite uplink implants

**Comment by Shapsy** [comment]
Honestly you'd probably be most successful only buying one anyway since I doubt most people would actually be willing to whack two of these things to death and would probably just ignore them

**Comment by Qustinnus** [comment]
seems fair

**Comment by necromanceranne** [comment]
bitcoin_assassin

@Shapsy you say that but I only redtexted because I wasn't paying attention to the shuttle time. I nearly killed all of sec and most of the crew that hunted me with the guns I brought with my bitcoins as the Bitcoin Assassin.

**Review by 81Denton — CHANGES_REQUESTED** [review]
Let's make this 1. As hilarious as this item is, nobody likes spam.

**Comment by wesoda25** [comment]
whyd it fail?

**Comment by TheSilverNuke** [comment]
> 
> 
> bitcoin_assassin
> 
> @Shapsy you say that but I only redtexted because I wasn't paying attention to the shuttle time. I nearly killed all of sec and most of the crew that hunted me with the guns I brought with my bitcoins as the Bitcoin Assassin.
> 
> They were ANGY. Because they really are annoying as fuck when spammed. It was really close to an early shuttle call.

Oh I remember that shift, that was on Sybil

**Comment by 81Denton** [comment]
@wesoda25 This Travis failure is unrelated to your actual PR

**Review by 81Denton — APPROVED** [review]

**Pull request merged**
