### PR TITLE
Strange reagent now works properly on simplemobs

### PR DESCRIPTION
**Pull request by ATH1909**
## About The Pull Request

Fixes a bug that was caused by strange reagent assuming that the mob that it reacts with is a carbon when it is not, in fact, a carbon.

This bug was causing strange reagent to make dead simplemobs (and other non-carbon living creatures, such as cyborgs) that met the conditions for revival convulse, but not actually return to life.

EDIT: Also, strange reagent now brings the blood level of a revived carbon (without the NOBLOOD species trait) up to a safe level.

## Why It's Good For The Game

As far as I'm aware, strange reagent is supposed to be able to bring non-humanoids back to life as well. If it wasn't supposed to do that, why would it allow them to convulse?

The only thing that strange reagent needed its target to be a carbon for was the regeneration of organs. After its target's organs get regenerated, strange reagent then returns to calling it by its non-carbon name (M instead of H), suggesting that non-carbons were intended to supposed to get past the organ regeneration stage.

Being able to revive cyborgs is admittedly an... odd side effect, but I think that this is within reason (or at least a feature instead of a bug), since strange reagent can revive fully augged people and androids anyway. I _could_ add a(n) !iscyborg() check, but honestly, I think that we should let the chemists have some fun. I mean, what's the worst that could come from allowing cyborgs to treat strange reagent like an emergency cyborg reboot board? About the worst thing that I can think of is a medical cyborg teaming up with an engineering, mining, or standard cyborg to resurrect a dead cyborg without human assistance, but honestly, if a medical cyborg manages to get its grubby mitts(?) on some omnizine and holy water without human assistance, find and notice the dead status of another cyborg (who actually left behind a "corpse" (which cyborgs don't do if they're blown)), and actually coordinate with another cyborg with a welder to bring a dead cyborg back to good enough condition to be brought back with strange reagent, I think that that amount of effort should be rewarded.

EDIT: See my first reply below for my explanation as to why I gave strange reagent the ability to return a dead carbon's blood level to a safe amount.

## Changelog
:cl: ATHATH
fix: Strange reagent properly resurrects non-carbons (it still can resurrect carbons, of course).
balance: Strange reagent now brings the blood level of a revived carbon (without the NOBLOOD species trait) up to a safe level.
/:cl:

### CODE REVIEW

**Comment by ATH1909** [comment]
Also, should I or shouldn't I make strange reagent return your blood level to an acceptable level (too) when it revives you? It already regenerates your organs so that you don't instantly die/start dying again when it revives you, so I feel like it should also regenerate your blood level for that same purpose/reason (in other words, it should regenerate your blood level so that you don't instantly die/start dying again when it revives you).

**Comment by 81Denton** [comment]
Yeah, restoring a certain amount of blood sounds good

**Comment by ATH1909** [comment]
> Yeah, restoring a certain amount of blood sounds good

@81Denton bam, done

**Comment by nemvar** [comment]
Time to revive space dragons a million times.

**Review by SpaceManiac — APPROVED** [review]

**Pull request merged**
