### PR TITLE
MetaMed 2: Return of the Frosty Saviour

### PR DESCRIPTION
**Pull request by EOBGames**
## About The Pull Request
Revamps Metastation medbay, again. We've had the old one for a year and it's about time it gets some attention again.
metamed_returns
Features include a more centralised design, focused on the Primary Treatment Centre.

While I stand by my work on the original design around a year ago, medical has moved on somewhat since then, and I've improved somewhat as a mapper. I've made this update to address the two main complaints I've seen about metastation's medical:
1. Surgery was too divorced from the PTC, meaning that it was rarely if ever used.
2. Cryogenics was much the same.

In addition, I've given it a fresh coat of paint, taking advantage of some of the cosmetic additions of the past year. Large tiles, sidings, the whole nine yards.
I've also attempted to place as many of the new wallmounts in Wallening friendly locations as possible, though without seeing the sprites in the editor it's hard to tell. Hopefully it should make it a bit easier come the Wallening actually hitting.

## Why It's Good For The Game
It's a fancy new medbay, which I think is an improvement over the last.

## Changelog
:cl:
add: Metastation's medbay has received another revision. Stop by the next time you get hurt, and marvel at the new design!
/:cl:

### CODE REVIEW

**Comment by Mothblocks** [comment]
u forgot the showers

**Comment by SmArtKar** [comment]
Med storage and surgery are too empty and open

**Comment by ATH1909** [comment]
I'd recommend replacing those reinforced windows in surgery with walls, or at least making them opaque.

**Comment by YakumoChen** [comment]
Three non-PTC surgery beds seems almost silly when usually everything is moved to the PTC anyway, but I like having the more discreet corner surgery regardless.

The main surgery room doesn't feel really usable for antags since it's harder to slip people in there and too close to the center of activity to get away with a lot but I guess it's fine.

**Comment by tralezab** [comment]
i like it a lot

**Comment by manofpepsi** [comment]
I am not a fan of this change as I feel that the current meta medbay if perfectly fine and is better than this. but some feedback/criticism never hurt anyone... right?

<details>
<summary>  inconsistent usage / oversights? of the tile variants </summary>

image
image
also it looks like there are some decals that werent deleted (next to the maint door)
image

i can see why you didnt put the big tiles there but you could have placed the edge tiles instead.
image
image

also this would look better with edge tiles
image
image
</details>
<details>
<summary>  grey tile accent </summary>

this is more on the subjective side of things but the usage of the normal tiles in the medical isnt very good, especially in the delivery zone, near the med lobby, it looked better before when it had white tiles and blue siding
image
the chem storage room also doesnt look that good
image
maybe something like this would look better?
image
and this cold room also doesnt look great, but also has a "creamsicle" which makes the list upon right clicking / alt clicking even longer. plus it also creates this weird maint between it and the medical storage.
image
</details>
<details>
<summary>  stuff I like </summary>

not a fan of this room, its just a medium sized room, but I do like the storage think with the wheelchairs, maybe it should be moved
image
the medical break room looks good, but it has a weird connection to the abandoned room, and the bloat computer placement is also good.
image
delta styled surgery room with everything ready in there + the old surgery room but finished, makes it less of a pain in the ass unlike what we have now which are 1 finished room and 2 unfinished pieces of junk.
image
image
</details>
<details>
<summary>  minor pipe + cable issues</summary>

image
the room doesnt look good because of the pipes and stuff
image
maybe something like  this would work better
image
</details>

**Comment by Zytolg** [comment]
Once again, you've outdone yourself Inept. A few rough areas here and there, but it's nothing that can't be fixed by shoveling some walls around. The main takeaway here is that I couldn't have redesigned the Medbay Core better if I tried. Excellent flow control, and it represents exactly where medical gameplay stands, while retaining everything players, and you, loved about the original design.

Now those rough spots? I'm not sure if the Location of the Psychologists office is Suitable anymore. Same could be said about the old Paramedics office and the Auxiliary Surgical Theater. The morgue is going to be a Legacy layout regardless of how we handle this design, so we don't really need to touch it (this will always be the best place for it in inept-med). Despite that, I think there is an opportunity to redesign this bottom area of Medbay, and bring it in line with the rest of your new Medbay. If it were me, I'd prioritize swinging up the Psychologists office to occupy the area where Auxiliary Surgery, and Abandoned Medbay sit, in order to facilitate better Psychologist Access to important departmental features. There will still be plenty of space leftover to rebuild Abandoned Medbay and then some, and perhaps a chance to clean up some of the newfound funk surrounding the (chem storage?) area. As for the Paramedics Room, it feels empty, but I'm sure you'll figure something out for that. 

Lastly, you could change the Evac leaning side of Medbay, which is just Chemistry, but I don't see how you'd do that in any meaningful way. At best, you change the dimensions of the involved rooms, but just to say it for the record, it isn't needed currently. Everything else has also been said at this point, and I'm confident you've got it in hand. Like I said, this is an amazing refit, and a tad bit more work is really going to send it over the top. Great job.

**Review by Maurukas — COMMENTED** [review]
Sorry this took so long:

This door is a science door, and it is set to public access. Could also use a touch of detailing - floors, light switch, intercomm. Also no fire alarm switch in the room
image

Plumbing door is also a public access science door:
image


As mentioned, there are currently no showers. Hall showers would be acceptable.

This table is sad and empty for a room that's supposed to store roundstart supplies. Clutter it up perhaps? ~A few power cells maybe?~ As mentioned below, the surplus medical belts and HUD should go here. You are also missing syringe guns.
image

You've manually done the tools in Surgery, but there are no bonesetters. Maybe here in the case next to the lonely bone gel?
image

Do a pass for fire alarms. They are missing from the exam room, surgery, storage, and the medical office.

**Comment by YakumoChen** [comment]
> This table is sad and empty for a room that's supposed to store roundstart supplies. Clutter it up perhaps? A few power cells maybe?

Add the supplies that were included in the storage room before as well. Belts, HUDs, syringe gun supplies, the basic chem-locker chems.

**Comment by Mothblocks** [comment]
@Maurukas Mark as "request changes" when you want the author to do so, and mark as draft so nobody merges it by mistake.

**Review by Maurukas — CHANGES_REQUESTED** [review]
Finished going through it this morning. Just a bunch of minor stuff:

Wrong rotation on cryo tank connector:
image
Surgery B has no APC in it:
image

Cold room has a vent, but no air alarm:
image


Extra fluid duct on this sink tile (sinks contain their own duct)
image

Minor decalling inconsistency. This set of vent and scrubbers are on floor/iron/white whereas all others are on /floor/iron/white/smooth_large:
image

Otherwise, this looks fantastic.

**Comment by Maurukas** [comment]
Beautiful.

**Pull request merged**
