### PR TITLE
Additional Reagent containers

### PR DESCRIPTION
**Pull request by xXPawnStarrXx**
## About The Pull Request
New condiment containers; With specific skins, giving you more option to differenciate or make fancy bottles for your fruit wines.
image
image

## Why It's Good For The Game
Helps chefs tell what reagents are in what container at a glance, looks pretty and adorable little wine bottles!

## Changelog
:cl:
add: Added new condiment containers and their sprites.

/:cl:

### CODE REVIEW

**Comment by SyncIt21** [comment]
Looks good. Feels like it could use some constructive critisism from the original spriter of condiments back in
- #75715 

Also you should rename your title to say you are specifically respriting condiment containers and not all reagent container as a whole

@MTandi thoughts?

**Comment by MTandi** [comment]
image

It's not a resprite, these are new ones.

I suggest to tune down the white on korta flour pack to more grayish-brown, too flashy.

Plastic mayo/ketchup bottle looks weird for korta nectar. It's supposed to be sweet, so I'd put it into something like the cherry jelly jar or a bottle.

Kinda like so:

image

The color choice for the cream is bad. And we already have a container for it in `boxes.dmi` I suggest adding that to chemmaster instead of adding a new one. 

image

**Comment by xXPawnStarrXx** [comment]
> @xXPawnStarrXx please use the `image` tag in the changelog, this kind of work is supposed to award GBP.
Oh, I wasn't aware I was able to get GBP for these, I was just adding new variations
> image
> 
> I suggest to tune down the white on korta flour pack to more grayish-brown, too flashy.
Yeah, I can 100% agree on that, I'll crank it down a little.
> Plastic mayo/ketchup bottle looks weird for korta nectar. It's supposed to be sweet, so I'd put it into something like the cherry jelly jar or a bottle.
I didn't want too many jars, I always invisioned Korta nectar being like an icecream syrup, which is why I used the squeezy bottle, I can try change it out for something.

> The color choice for the cream is bad. And we already have a container for it in `boxes.dmi` I suggest adding that to chemmaster instead of adding a new one.

> @xXPawnStarrXx add these juice containers along the way please, I forgot about them.

I didn't want to add these at first because they were 100u, instead of 50u like the other condiment containers. Do you want me to create alternates that hold 50u, or raise the others to hold 100u?

**Comment by MTandi** [comment]
> I didn't want to add these at first because they were 100u, instead of 50u like the other condiment containers. @MTandi Do you want me to create alternates that hold 50u, or raise the others to hold 100u?

I don't see any valid reason why they should be 100u, instead of 50u like all other condiments. What are they going to need so much cream for? So I believe it is fine to tune it down to the 50u which is consistent for all condiments.

**Comment by xXPawnStarrXx** [comment]
> > I didn't want to add these at first because they were 100u, instead of 50u like the other condiment containers. @MTandi Do you want me to create alternates that hold 50u, or raise the others to hold 100u?
> 
> I don't see any valid reason why they should be 100u, instead of 50u like all other condiments. What are they going to need so much cream for? So I believe it is fine to tune it down to the 50u which is consistent for all condiments.
> 
> Edit: Oh wait, they're subtypes of bar drinks... And they use those 100u bottles. Then not sure, we probably should just not add another cream container then... Not sure.

I could try make smaller versions of the cartons, rescale some or upscale the bigger ones?

**Review by Wallemations — CHANGES_REQUESTED** [review]
Rename your PR to be more specific

**Comment by xXPawnStarrXx** [comment]
> Rename your PR to be more specific

Done

**Comment by MTandi** [comment]
> I could try make smaller versions of the cartons, rescale some or upscale the bigger ones?

Still think that we should reduce them to 50u. They don't look like they have twice as much as other condiments. Let only the booze bottles have 100u. 

Though, there are some related prices that need to be halved.

**Comment by Wallemations** [comment]
> > Rename your PR to be more specific
> 
> Done

Still not specific enough.
If these are just condiments, then say they're for condiments.

**Comment by Wallemations** [comment]
Also, why not make the 4 similar containers into one GAGS container that swaps to the color of the reagent inside it? They all share the same desc anyways, I don't see much reason to keep them as different iconstates.

**Comment by xXPawnStarrXx** [comment]
> Also, why not make the 4 similar containers into one GAGS container that swaps to the color of the reagent inside it? They all share the same desc anyways, I don't see much reason to keep them as different iconstates.

I honestly don't have the mental capacity for GaGS

**Comment by Wallemations** [comment]
> > Also, why not make the 4 similar containers into one GAGS container that swaps to the color of the reagent inside it? They all share the same desc anyways, I don't see much reason to keep them as different iconstates.
> 
> 
> 
> I honestly don't have the mental capacity for GaGS

Doesn't even need to be GAGS now that I think about it.
You could easily use the existing reagent filling overlay functionality and instead of showing reagents inside just have the overlay completely recolor the bottle section of the container.

**Comment by MTandi** [comment]
Reagent filling for a random condiment bottle is not really easy nor is it necessary... though I doubt that we need 4 just for vinegar

**Comment by xXPawnStarrXx** [comment]
> Reagent filling for a random condiment bottle is not really easy nor is it necessary... though I doubt that we need 4 just for vinegar

They're "Vin" which is french for "Wine" I made them because it's a downstream request because people wanted little winebottles for the fruit wines they make in botany.

**Comment by MTandi** [comment]
> They're "Vin" which is french for "Wine" I made them because it's a downstream request because people wanted little winebottles for the fruit wines they make in botany.

Then these are not condiments and should be added to the cooking menu as follows:

image

**Comment by xXPawnStarrXx** [comment]
>Then these are not condiments and should be added to the cooking menu as follows:

I didn't want to add anything that was over 50u to the condimaster, because I didn't want to get whined at for powercreep, I had plans to adjust some of the containers of make variants when I had time off work. I was also going to look into the condimaster being upgradeable and requiring glass.

**Comment by scrunklershrungle932** [comment]
imo it'd be cool if the new colored bottled just had the color of the reagant inside.
regardless, it's still pretty cool.  I like it.

**Comment by MTandi** [comment]
I think that we can easily solve this if we let to reskin the empty 50u and 100u bottles with pen or something. We already have this logic for wall signs, chests, airlocks.

Add them to the service techfab and they can be removed from the crafting menu.

That would be the best solution IMO.

Though this requires a separate PR. @xXPawnStarrXx I suggest to assign these 4 bottles to some reagents like red for Fruit Wine, brown for Nutriments, Green for Vinegar, Violet for Vitamins, so that the auto-suggestion works correctly for them.

And we will provide a better solution for your use case by allowing to re-skin bottles in another PR.

**Comment by xXPawnStarrXx** [comment]
> Though this requires a separate PR. @xXPawnStarrXx I suggest to assign these 4 bottles to some reagents like red for Fruit Wine, brown for Nutriments, Green for Vinegar, Violet for Vitamins, so that the auto-suggestion works correctly for them. You can name them as you wish in CondiMaster anyway.

I can close this PR, then add them in just as a base. Then when the seperate PR is done, they're already in and can just be added.

**Review by Wallemations — CHANGES_REQUESTED** [review]
Just use the existing reagent_filling functionality to make the colors change automatically so we don't need to have 4 different versions of the same sprite, and I'll merge the PR then.

**Comment by xXPawnStarrXx** [comment]
I'm honestly not sure how to get it to be a singular item that switches colours. I'm not even sure if I wanna waste more time on this as is.

**Pull request closed without merging**
