### PR TITLE
Qbopper's Drone Flavortext Addition+

### PR DESCRIPTION
**Pull request by ExcessiveUseOfCobblestone**
:cl: Qbopper
spellcheck: Drones are now given OOC guidelines to follow as well as their IC lawset.
/:cl:

See #25472

Asking for this to ignore the feature freeze since it will hopefully alleviate people from getting banned [and I guess in that way is a fix]. 

img

### CODE REVIEW

**Comment by coiax** [comment]
Do we mention that drones can communicate with pAIs, or no?

**Comment by ExcessiveUseOfCobblestone** [comment]
I'll just let them figure that out :^)

**Comment by ExcessiveUseOfCobblestone** [comment]
i'm crying

**Comment by ExcessiveUseOfCobblestone** [comment]
no that is secret

**Comment by RandomMarine** [comment]
>Secret rulings that have no mention in policy that all admins somehow know to let slide.

**Comment by Qbopper** [comment]
jokes on you @RandomMarine I didn't know that either

thanks cobby, you even put my name in the changelog(!)

**Comment by anconfuzedrock** [comment]
remove the pai thing tbh

**Comment by ExcessiveUseOfCobblestone** [comment]
what do you take me for, ruler of the admins including the redditmin?!!

**Pull request merged**
