### PR TITLE
fixes styptic not working in patches

### LINKED ISSUE #13397: Styptic Powder patches don't immediately heal brute wounds
https://github.com/tgstation/-tg-station/blob/953becdfdc6171fabccb3ab86d1bc7cbae5b551c/code/modules/reagents/Chemistry-Reagents/Medicine-Reagents.dm#L210

should be getBruteLoss, not getFireLoss

### PR DESCRIPTION
**Pull request by Iamgoofball**
i'm too lazy to gitblame this and figure out who broke it but I'm gonna strangle them when I find out

Fixes #13397

### CODE REVIEW

**Comment by Zilenan91** [comment]
This kills the spaceman

**Comment by hornygranny** [comment]
@xhuis is responsible for this

**Comment by JJRcop** [comment]
Iamgoofball:*patch*-140

**Comment by Xhuis** [comment]
Yeah, this was me. Oranges recreated the PR back when I went on hiatus.

**Comment by optimumtact** [comment]
it's oranges and technically it was my fault.

**Comment by Iamgoofball** [comment]
how does this conflict

**Comment by neersighted** [comment]
@Iamgoofball I restructured the folder

**Pull request closed without merging**
