### PR TITLE
Fixes Boxstation's Rounstart Power Problems

### PR DESCRIPTION
**Pull request by Hanador**
Almost another first PR since the last one hasn't merged yet. God I hope I'm not accidentally deleting the work I did for the bridge+firelocks PR.

This basically moves some wires around in order to fix the roundstart APC charging issue for the AI + Gravity Generator. I've done a roughly hour long local test with solars wired and power seemed to function normally throughout the station in that timeframe.

**Grav Gen**
Moves an SMES and its terminal, an air alarm, and deletes a wire

GravGen

**AI Satellite**
In AI chamber mostly just moves the wires by the SMES up a tile.

AISat

### CODE REVIEW

**Comment by kriskog** [comment]
The AI smes is supposed to only output to the AI, no charging connected. If you put the output on the same powernet as the rest of the station, AI power will be drained by power sinks and AI will eventually die if its never found. In addition, AI APC has to fight with other APCs on the powernet for charge.

The grav gen one on box Im not that sure about, but on other maps there is a generator you can hook up to it to keep grav gen running if power drops without being affected by the entire station. This one, again, should probably not be connected roundstart to allow for grav to drop and have to be fixed.

**Comment by Hanador** [comment]
**Please do not merge until I'm certain I've fixed the PR**
**I just noticed I left a terminal in under the Gravity Generator SMES unit I'm working on fixing it now**

Yeah the AI and Grav gen are still in their own power grids with their own SMES units. 

**I did not connect the two rooms to the greater power grid.** The solars test was to check if the issue of box losing all power ~30 mins to 1-3 hours into the round still persisted. I'm uncertain if I have fixed that issue this [https://github.com/tgstation/tgstation/issues/48026] is the one I am talking about

**Comment by kriskog** [comment]
Is there no secondary SMES on the AI satellite? If you look at meta, there is one SMES exclusively for the AI APC, and one for the rest of the satellite. I guess box doesnt have to power tcomms as well, so it might not be a big deal.

The grav gen should be connected to the main station powernet roundstart. Powering it with the SMES will leave it less prone to sabotage and also requiring a rewiring if the SMES ever runs out. To be clear, the SMES should not be connected roundstart.

**Comment by Hanador** [comment]
Apologies if I misunderstood you.
Meta does indeed have an extra SMES to account for telecomms. Box may have a second SMES that is just outside of the screenshot range near the borg chargers but I'm not sure I haven't really looked closely at the AI satellite since it was changed into this long one we have today. As for connecting the grav gen to the main power grid I'm doing what is standard on every map as far as I can tell. I just checked Meta's grav gen and it isn't connected to the main power grid either unless an engineer takes the time to lay down a few dozen wires and put tiles over them.

When I work on revamping box's power grid I could connect it to the grid and remove the charged SMES so power sinks are more irritating if that's what people really want, but the main focus at the moment is just to get what is already in place functioning properly.

**Pull request merged**
