### PR TITLE
Monkey mode balances & tweaks

### PR DESCRIPTION
**Pull request by ghost**
:cl: More Robust Than You
tweak: Jungle Fever cannot be cured anymore
fix: The Monkey Leaders' virus are now un-detectable by health scanners and to the PANDEMIC now.
/:cl:

### CODE REVIEW

**Comment by The-clown-known-as-Pepe** [comment]
bad

**Comment by Xhuis** [comment]
this is rather silly

**Comment by Armhulen** [comment]
this is fucking amazing

**Comment by Armhulen** [comment]
YES PRE NERF MONKEY MODE WHERE IT WAS MORE THAN BOTANY DESTROYING THE MONKIES EVERY ROUND WHILE UN-INFECTABLE WITH HARDSUITS

**Comment by Xhuis** [comment]
oh, I misread the PR, I thought the virus was undetectable period
this is okay then, I suppose! I'm indifferent to it

**Comment by optimumtact** [comment]
I think at hte end of the day that's monkey mode lmao, just indifferent

**Comment by Xhuis** [comment]
:thonk:

**Comment by MoreRobustThanYou** [comment]
@Xhuis The initial leaders have an undetectable variant, but when they infect others, the virus will make itself detectable

**Comment by Armhulen** [comment]
everybody who has downvoted this pr has given no reason save for sherrie who just posted "bad"

??

**Comment by Buggy123** [comment]
fucking add back monkies mode already. Its not worse than revs god damn.

**Comment by lzimann** [comment]
It is worst, monkey mode has no goal at all, essentially an extended with a twist, with monkeys running around infecting people, and that's all. While rev, liking it or not, has a clear set objective. Right now, there's literally no reason to have monkey mode enabled on config except for "lol monkey mode so funny ecks dee".

**Comment by Buggy123** [comment]
So give monkey mode the goal of infecting a certain percentage of crewmembers or something.

**Comment by duncathan** [comment]
eh why not

**Pull request merged**
