### PR TITLE
Now Heading to: Turbine - A "new" CTF map

### PR DESCRIPTION
**Pull request by Jolly-66**
## About The Pull Request
Title.
Adds ctf_turbine from Team Fortress 2 (which is arguably the best ctf map because its just TDM)
I did jokingly talk with Namless in mapping gen back during FFF, and so, now its March so here we are.

image

## Why It's Good For The Game
<details>
<summary>Turbine Jumpscare</summary>

image
</details>

CTF doesn't have a lot of maps as is, so, one more shouldn't hurt!
Turbine is a Red vs Blue map, its small and could result in some quick games, or you can just hold out and defend middle (not like its possible in current CTF, but the sentiment is still the same!)

## Changelog

:cl: Jolly
add: CTF has a "new" map: ctf_turbine! I hope you like 24/7 TDM where the objective is secondary.
/:cl:

### CODE REVIEW

**Comment by D4C-420** [comment]
Those are HFR's not turbines day ruined. (also more ctf maps yay)

**Comment by VladinXXV** [comment]
do 2fort next :trollface:

**Comment by Pickle-Coding** [comment]
Why are the HFRs missing their corners while having two fuel ports?

**Comment by NamelessFairy** [comment]
You need to create a subtype of /datum/map_template/ctf for it to actually be selectable ingame.

**Review by Maurukas — APPROVED** [review]
Everything looks like it's working here.

**Pull request merged**
