### PR TITLE
Bad quirks no longer give points - everyone has 2 points instead.

### PR DESCRIPTION
**Pull request by XDTM**
:cl: XDTM
del: Negative quirks no longer give points and are now purely for RP or self-challenge purposes.
balance: Some negative quirks are no longer un-removable, and can be cured with in-game means. (Not always easily)
balance: The madness quirk now applies the hallucinations trauma instead. The hallucinations as a result are more frequent than before, but mindbreaker still blocks them.
add: Everyone starts with 2 points to spend on a major positive quirk or two minor ones.
/:cl:

Removes the minmaxing element from a system that's meant to let you customize your character to make them more unique or to give yourself a challenge. The current system has to be balanced to make sure negative quirks don't give too few or too many points, as can be seen in the discussion in #41130, and because of that the negative effects must be kept permanent (at the cost of consistency) to avoid them being free points.

For reference, the now removable traits are nearsightedness (genetics), pacifism (lobotomy-grade trauma) and madness (lobotomy-grade trauma).

### CODE REVIEW

**Comment by Mickyan** [comment]
Using quirks in any capacity is gimping yourself by some margin, there is not min maxing that will actually give you any kind of edge and that's by design and that's why their balance is quite loose. 
I am against people that keep pushing the point limits on quirks (brain damage/blind quirks) simply because it only makes things more complicated and nobody's going to pick either because of the points, but that's an entirely different discussion.

It's backwards to think this makes your character more customizable as people can no longer make their character the way they want, the only reason we need a point system is otherwise people will only pick positives, meanwhile there's nothing stopping them from picking a bunch of negatives as it is

This change is frankly absolutely awful and a great way to make sure negative quirks are never going to be used again. And this is apparently being done because of a flavor of the month quirk that nobody will be using 2 weeks from now, if other major negative quirks are anything to go by.

The only change I am not completely opposed to is giving everyone 2 free points by default

**Comment by XDTM** [comment]
I honestly thought the 2 free points were the issue, from the downvotes.

The reason i thought of this is so we don't have "magically unhealable" ailments that are somehow the same as existing ailments which are perfectly curable.

If bad quirks are not worth it to get good quirks then the only people who would reasonably take them are those who would not mind an extra challenge. Those people would still take them under the new system.
Those that wouldn't are the ones that try to pick the least impactful bad quirk in order to afford a good quirk they want. This effectively gives a hard cap on how unimpactful a bad quirk must be, since a minor inconvenience is worth at the very least one point and if it's not 'bad' enough people will take it for that reason.
Due to the free points, they would no longer need to bother minmaxing the system; they'd get their favourite bonus quirk either way without needing to find the optimal disability.

Removing this point balance system removes this limit when designing new negative quirks; for instance, quirks that can eventually be healed.

**Comment by Mickyan** [comment]
>The reason i thought of this is so we don't have "magically unhealable" ailments that are somehow the same as existing ailments which are perfectly curable.

Even though I wouldn't even care this is still not a good excuse to mess up the entire system like this. You can feel free to change/remove those quirks if that's what peeves you so much.

>If bad quirks are not worth it to get good quirks then the only people who would reasonably take them are those who would not mind an extra challenge. Those people would still take them under the new system.

No they wouldn't, the fun of quirks is having negatives to deal with while having interesting positives to make up for it that you can't otherwise get. I can make a character with a lot of negatives and a lot of positives if I want, with your system I can't because everyone gets a limited amount of free quirks and I get the privilege of purposefully gimping myself with nothing to show for it.

>Those that wouldn't are the ones that try to pick the least impactful bad quirk in order to afford a good quirk they want.

Those people will now have access to two current major quirks to powergame for free without having to worry about downsides. 

>Removing this point balance system removes this limit when designing new negative quirks; for instance, quirks that can eventually be healed.

And does the exact opposite for positives which will either be "meta quirks that every powergamer picks" or "gimmicks that nobody uses"

**Comment by Militaires** [comment]
bad change, everyone will just pick the few kind of good quirks, you cant minmax because even participating in quirks you have to pick some negatives, also i dont know what's with the "magically unhealable" thing who even cares, realism isnt and was never tg's strongsuit

**Comment by Mickyan** [comment]
If you really want to make the quirks healable you could make it so they are only healed temporarily and come back on their own after some time, blame it on bad genes

**Comment by XDTM** [comment]
> > The reason i thought of this is so we don't have "magically unhealable" ailments that are somehow the same as existing ailments which are perfectly curable.
> 
> Even though I wouldn't even care this is still not a good excuse to mess up the entire system like this. You can feel free to change/remove those quirks if that's what peeves you so much.

I cannot, because they'd become a must-pick due to healability.

> > If bad quirks are not worth it to get good quirks then the only people who would reasonably take them are those who would not mind an extra challenge. Those people would still take them under the new system.
> 
> No they wouldn't, the fun of quirks is having negatives to deal with while having interesting positives to make up for it that you can't otherwise get. I can make a character with a lot of negatives and a lot of positives if I want, with your system I can't because everyone gets a limited amount of free quirks and I get the privilege of purposefully gimping myself with nothing to show for it.

The way i see it quirks should be character traits that set you a little apart from the average. With my system you'd get a particular skill/bonus of your choice, any number of neutral quirks for flavor, and any number of disabilities for an extra challenge or for RP reasons.
If you don't see any reason to get disabilities beyond getting extra positives, you might have the powergamer mindset i mentioned. You can just not get them if you don't want them, or get them if you think it's fun to overcome a particular limitation or disability.

> > Those that wouldn't are the ones that try to pick the least impactful bad quirk in order to afford a good quirk they want.
> 
> Those people will now have access to two current major quirks to powergame for free without having to worry about downsides.

One current major quirk, or two minor. Also, since everyone gets one those people won't really have any edge over others.

> > Removing this point balance system removes this limit when designing new negative quirks; for instance, quirks that can eventually be healed.
> 
> And does the exact opposite for positives which will either be "meta quirks that every powergamer picks" or "gimmicks that nobody uses"

Positives already have a point cost, so this applies regardless of this PR.

**Comment by SouDescolado** [comment]
Just as a parallel, you can technically get a free positive quirk if you roll antag, because it removes pacifism. So get pacifism, get something else and pray.

**Comment by Militaires** [comment]
oh boy i really cant wait for our rp-interested playerbase to pick lots of negatives for roleplay!! i bet they also all wont pick just skittish or some shit!

**Comment by Mickyan** [comment]
>If you don't see any reason to get disabilities beyond getting extra positives, you might have the powergamer mindset i mentioned.

So you're going to gloss over the fact I said this is a powergamer dream and you're limiting people from picking the gimmicky quirks they want without limitation and just call me a powergamer instead

lol fuck off with that honestly

**Comment by XDTM** [comment]
Literally the only people inconvenienced would be people who want multiple positive quirks at once. I don't want to make it worse for powergamers, i only want to prevent that playstyle from gimping quirk creation.

@Militaires do we _need_ lots of people to take disabilities? Who wants them gets them, much like playing as plasmamen. As for everyone picking skittish, that's solved by giving more choice in positive traits. The current system is not really different on that, the best ones will be the most picked.

**Comment by XDTM** [comment]
My base train of thought was was this:
- Want to make quirks that are the same as existing game mechanics healable (nearsightedness, pacifism, etc)
- "If you do that people will just get them and get them cured, and keep the positive quirks for free" 
(this is my "issue" with powergaming, and by that i mean it restricts design due to the nature of the system, not that powergamers are bad per se)

Potential solution: Separate negative quirks from positive ones so there is no need to keep them point-balanced. People who like good quirks get one for free, people who like playing with bad quirks get as many as they want.

I'm clearly wrong about this, seeing the backlash, but i'm struggling to understand where i went wrong with the reasoning.

**Comment by Mickyan** [comment]
You're advocating to make the system less varied and turn it into a race to pick and make the most meta quirks because of limitations (???) that only seem to be a problem to you.
With your system quirks are no longer optional and you're gimping yourself if you don't pick the best ones, the exact opposite of what quirks are supposed to be: small changes that make your character more interesting in both positive and negative ways.

This is a kick in the balls of people like me that tried to make interesting quirks that aren't at the top of the meta but may still be worth picking an extra nagative for if you personally find them interesting (i.e. musician is hardly a worthy investment if you're after power, yet I see a LOT of people using it.).

Your reasoning went wrong when you tried to bulldoze a balanced system that's purposefully skewed towards negatives to fix an arguably minor consistency issue that could easily be hand-waved away with flavor text.

**Comment by XDTM** [comment]
The thing i don't understand is, if people pick musician over another better quirk now, why wouldn't they do so under the new system anyway? They are already 'gimping' themselves right now by not picking the optimal ones.

Also, the consistency thing is only what made me think of this system, not my single reason. I personally think that categorizing quirks into three sections might make them less rigid, since now you don't need to be a pacifist or blind or insane or have whatever combination of minor maladies in order to be good at climbing tables.

**Comment by Mickyan** [comment]
>The thing i don't understand is, if people pick musician over another better quirk now, why wouldn't they do so under the new system anyway?

Because you're not wasting one of two limited and mandatory positive slots for it.
Because say you really don't want to gimp yourself but you really like the idea of musician, you can pick that, family heirloom and you'll be all set and just about on the same level as anyone else who doesn't use quirks. 
If you add mandatory limited quirks, anyone who doesn't want to be gimped is going to be forced to pick two positive quirks that give them an edge and ignore everything else.

**Comment by XDTM** [comment]
I see your point now, whose who'd pick light traits like musician are unchanged, but everyone else gets bonuses, which disincentivizes the former.

Just to at least try and salvage this - what would you think it i further split it into major and minor positive traits, and gave one major and one-two minor picks instead of the two points? The major would (ideally) be a matter of preference, depending on whether you like hiding in lockers quickly, or climbing tables, or drinking to heal, and so on, and the minor would be used for things like photographer and musician, which is added flavor but not particularly mechanically beneficial.
I still like the idea of disabilities as an optional challenge mode, also to retain their uniqueness, because picking family heirloom only to afford being a musician strikes me as being against the spirit of the thing.

**Comment by Mickyan** [comment]
That doesn't really change the fact that if you try to make them mandatory you're pushing people towards optimizing; min maxing, if you will.
The negatives outweighing the positives are the only thing that stop quirks from being powercreep.

**Comment by Mickyan** [comment]
That'd be fine I think, gives people that wouldn't otherwise be interested a small incentive to use the quirk system

**Comment by XDTM** [comment]
I'll implement that instead, then.

**Comment by Shdorsh** [comment]
It looks like it's taken straight out of Misuterii High, in which it works well. That however, is a murder mystery game which focuses solely on this, while SS13 is SS13, tho I surely would like to spec all into robustness while being both blind and deaf like I used to do over there and make antags feel bad for being robusted by a completely handicapped person.

**Pull request closed without merging**
