### PR TITLE
Adds the "set round end sound" button to the fun tab

### PR DESCRIPTION
**Pull request by Incoming5643**
So admins can override the generic sounds to play something else if their wayward hearts so desire it.

https://www.youtube.com/watch?v=JjuzxiuIbjs

### CODE REVIEW

**Comment by Xhuis** [comment]
ONE DAY WHILE ANDY WAS...

:+1:

**Comment by WJohn** [comment]
:+1:

**Comment by Alek2ander** [comment]
Can this sound be carefully sent to all players in advance so there aren't 50 people downloading a 5Mb  mp3 all at the same time?

**Comment by Incoming5643** [comment]
The system probably shouldn't be used with large files to begin with, if the client window manages to connect to the rebooted server and something is still playing from the previous round, it stops.

**Comment by RemieRichards** [comment]
Do what the Global sound button does, prevent files over 1MB

**Comment by Incoming5643** [comment]
I don't see anything in play_sound that does that, maybe that's just something byond does automatically? I guess there's one way to find out.

**Comment by RemieRichards** [comment]
I doubt it'd be in play_sound, since that is the proc for playing all sounds in the game.
did you check the play global and play local admin buttons as I said?

Otherwise, please test your verb with a large (1MB+) file

**Comment by Incoming5643** [comment]
/client/proc/play_sound(S as sound)
	set category = "Fun"
	set name = "Play Global Sound"

But yeah I'm testing the verb right now, stand by to this comment for results

**Comment by RemieRichards** [comment]
Hilariously I was thinking of ```playsound()```

**Comment by Incoming5643** [comment]
AllowUpload() checks the file the same way play global sound does. It's safe :+1:

**Comment by RemieRichards** [comment]
Good to hear, :+1:

**Pull request merged**
