### PR TITLE
Makes Pete female, gives them udder again.

### PR DESCRIPTION
**Pull request by DaCoolBoss**
## About The Pull Request
Pete is now female, and can once more be milked. Their name has been changed into what I believe is the female form of "Peter".
## Why It's Good For The Game
Pete's udder was removed a while back for realism, and it's been bad for the game. The chef's supply of legitimate milk became highly limited, and it has led to chef players murdering pete at round start because they don't have a reason any more to tolerate Pete attacking them in the coldroom, and some chefs have made it part of their routine to steal the cow from the public garden to replace old pete - which takes the ability to produce non-biogen milk away from the rest of the crew entirely.

The realism argument was weak but whatever, here's your compromise. No male goats with udders since the goat is now female.
## Changelog
:cl:
balance: Pete has been made female. As a result, they are now named Peta and can once again produce milk.
/:cl:

### CODE REVIEW

**Comment by Mothblocks** [comment]
just give him an udder and we can call it a sex joke the name pete is a reference to an old coder

**Comment by TheRyeGuyWhoWillNowDie** [comment]
Space Station 13 if it was WOKE: Gay moth, Plasmama'am, Lizard

**Comment by optimumtact** [comment]
When discussed the first time we believed the right answer is to ensure every map has female cows in the public farm/park area so that is what mappers should be doing.

Otherwise i'm not really interested in the chefs lack of milk.

**Comment by DaCoolBoss** [comment]
I read that discussion, it hinged on the chef being able to mass produce milk at the biogen for an easier way to get the same reagent. That's no longer the case, since biogen-made milk now automatically downgrades food quality if it's in the recipe.

> just give him an udder and we can call it a sex joke the name pete is a reference to an old coder

Thought references like this were discouraged?

**Comment by optimumtact** [comment]
yeah I don't care about your first problem, they can steal the public cow or order a cow from cargo it's really not a major problem.

and on the references thing, it's just legacy and its' not properly enforced anyway.

**Comment by DaCoolBoss** [comment]
I also didn't find anything about cows in the pr discussion? #79722

**Comment by LSommers** [comment]
Peta
The DNM is here

**Comment by EricZilla** [comment]
LET PETE BE TRANS

**Comment by san7890** [comment]
> I also didn't find anything about cows in the pr discussion? #79722

it was likely discussed elsewhere. should still be done though

**Comment by Mothblocks** [comment]
> When discussed the first time we believed the right answer is to ensure every map has female cows in the public farm/park area so that is what mappers should be doing.

sgtm

**Comment by optimumtact** [comment]
I think it was discord sorry, my apologies

**Comment by CRITAWAKETS** [comment]
Give Pete HIS udder but keep him male, goddamit

**Comment by SyncIt21** [comment]
> the name pete is a reference to an old coder

https://github.com/tgstation/tgstation/pull/1#issuecomment-291888274

**Comment by GuillaumePrata** [comment]
Being an annoyance is a good reason already.

It is always fun to see Pete randomly beating up the chef, or anyone else, that forgets who really is the king of the kitchen.

**Comment by Inari-Whitebear** [comment]
> Being an annoyance is a good reason already.
> 
> It is always fun to see Pete randomly beating up the chef, or anyone else, that forgets who really is the king of the kitchen.

Well without any reason for Pete to be alive, Pete will just get butchered round start. No beating up for you

**Comment by GuillaumePrata** [comment]
That still is conflict because people love Pete and will antagonize chefs that just murder the lil guy.

**Comment by Jacquerel** [comment]
Pete has value in keeping around in that he eats kudzu

**Pull request closed without merging**
