### PR TITLE
Grungy Shirt

### PR DESCRIPTION
**Pull request by ghost**
Adds the grungy shirt to game and autodrobe
sprites by Chocobro

grunge

:cl: Chocobro
add: Added grungy shirt to the Autodrobe.
/:cl:

### CODE REVIEW

**Comment by PKPenguin321** [comment]
gross

**Comment by uraniummeltdown** [comment]
32x32 is hard to work with, if anyone can improve the sprite please do I can't sprite

**Comment by fludd12** [comment]
`s o f t    g r u n g e`

**Comment by Iamgoofball** [comment]
# life sucks

**Comment by Haevacht** [comment]
Giving your own PR a thumbs up is shit.

**Comment by xxalpha** [comment]
No it isn't, it means you agree with it.

**Comment by XDTM** [comment]
Who even PRs something they don't agree with?

**Comment by FantasticFwoosh** [comment]
Mr Rogers is more grunge than this, son.

**Comment by ShadowDeath6** [comment]
Thumbs upping your own pr/comment is bad because it fools people into thinking that someone other than yourself backs your opinion

**Comment by xxalpha** [comment]
You're taking this way too seriously, only a complete idiot is going to be fooled by that for long.

**Comment by KorPhaeron** [comment]
I don't see the point in this and neither do you apparently since you skipped out on justifying the change

**Comment by Chocobro** [comment]
the only reason for the sprite looking shit is size constraints
it's an issue of 7x13, not 32x32
try fitting an entire smiley face with tongue with detail yourself it can't be done it just can't
i tried to make it Better with slightly different colours but that's the best i got feller

also wow removing yourself from the changelog wow wow wow

**Comment by uraniummeltdown** [comment]
It lets you show off you're musically aware

**Comment by Cheridan** [comment]
niravna is a pleb band

listen to some real music 
like animal collective

**Comment by xxalpha** [comment]
So furry shit is acceptable but some random shirt isn't?

**Comment by Iamgoofball** [comment]
yeah pretty much

welcome to tg

**Comment by Iamgoofball** [comment]
@WJohn when are you spriting tajaran for tg?

**Comment by Iamgoofball** [comment]
@Cheridan please merge my vulpkanin PR

**Pull request closed without merging**
