### PR TITLE
[PORT] New carpets and wooden floors from Citadel

### PR DESCRIPTION
**Pull request by SmArtKar**
## About The Pull Request

Ports arcade carpets and 3 new versions of wooden floors from Citadel.

Original PRs:
https://github.com/Citadel-Station-13/Citadel-Station-13/pull/13461
https://github.com/Citadel-Station-13/Citadel-Station-13/pull/13443

## Why It's Good For The Game

It allows players to decorate their environments with new types of floors which is nice I guess.

## Changelog
:cl:
add: Added a new arcade carpet and 3 new wooden floors
/:cl:

### CODE REVIEW

**Comment by Serxule** [comment]
>arcade carpets

totally not cum covered

**Comment by SmArtKar** [comment]
> > arcade carpets
> 
> totally not cum covered

why do I associate with cum for you

**Comment by Serxule** [comment]
> why do I associate with cum for you

moth milk probably

**Comment by SmArtKar** [comment]
> > why do I associate with cum for you
> 
> moth milk probably

that was my biggest mistake ever

**Comment by Serxule** [comment]
> that was my biggest mistake ever

biggest goodtake

**Comment by necromanceranne** [comment]
The arcade carpet will need a damaged state.

**Comment by Farquaar** [comment]
The wooden floors look comfy

**Comment by wesoda25** [comment]
The arcade one is from vg

**Comment by maxymax13** [comment]
> 
> 
> > arcade carpets
> 
> totally not cum covered

i mean it is a citadel fork

**Review by Twaticus — CHANGES_REQUESTED** [review]
this is epic but diagonal_wood-broken is shifted a pixel to the right for some reason. the rest of the broken states line up fine its just that first diagonal one

**Comment by maxymax13** [comment]
i really want this merged please fix the pixel

**Comment by maxymax13** [comment]
redoing this with the titanium tile radial and a new better diagonal one

**Comment by Twaticus** [comment]
closing in favor of #58797

**Pull request closed without merging**
