### PR TITLE
Tidies up Clothesmate: h3h3 shirt removal

### PR DESCRIPTION
**Pull request by carshalash**
## About The Pull Request

I was reminded that this thing existed while strolling around the station, It's for the best it is removed. 

## Why It's Good For The Game

The sprite was really ugly and the source content is garbage.  It was slapped in along with the vape PRs just because. 

## Changelog

:cl:
del: Removed podcaster reference shirt.
/:cl:

### CODE REVIEW

**Review by LemonInTheDark — APPROVED** [review]
Have no opinions on h3h3, love me some dumb reference removals

**Comment by optimumtact** [comment]
sprite goes in https://github.com/tgstation/SS13-sprites

**Comment by Iamgoofball** [comment]
h3h3 sucks but make it an undershirt

**Comment by Kurgis** [comment]
> h3h3 sucks but make it an undershirt

The issue is that I don't believe that undershirts appear on examination, without examine text any observer will have zero clue or idea what this shirt even means or is. It's a "V.N." shirt, it means nothing to a viewer. Even with foreknowledge of "Vape Nashe", I'd have zero clue behind the meaning of this sprite without the description or name revealing the reference.

**Comment by Bawhoppen** [comment]
@Iamgoofball 
> h3h3 sucks but make it an undershirt

Hold on wait a minute you made the original PR to add it back in the day

**Comment by carshalash** [comment]
Gross.

**Pull request merged**
