### PR TITLE
[s]Fixes secbot construction dupe

### LINKED ISSUE #13527: Assembly/item duping
HELP: Shodansbreak/(JC Denton) (?) (PP) (VV) (SM) (FLW) (TP) (REJT): I just duped an item, somehow. I was attachinga  remote signaller to a helmet I had in my bag, and it put it in my bag and dropped a copy ont he floor 

Reply PM from-Shodansbreak/(JC Denton): I had 2(?|F) helmets, 2 signallers, now I have 3 assemblies 

Reply PM from-Shodansbreak/(JC Denton): I attached it while it was in my bag, it attached, then made a second copy on the floor 

Reply PM from-Shodansbreak/(JC Denton): now when I attempt to weld the assemblies, it instantly welds them shut as well, all 3 of them seem bugged, or I'm just double clicking somehow

### PR DESCRIPTION
**Pull request by tkdrg**
Removes one of the copy-pasted attackby()s.
Fixes #13527

### CODE REVIEW

**Comment by phil235** [comment]
For consistency's sake, we should keep all bot assemblies in construction.dm or move each assembly into the proper mob file, but not do a mix of both.

**Comment by tkdrg** [comment]
I suppose. Which one do you think makes more sense?

**Comment by phil235** [comment]
Probably all in construction.dm, otherwise the file would be pretty much empty. And some bot files are already 500+ lines, so making the files bigger and mixing bot code with construction stuff would be bad for code readability.

**Comment by tkdrg** [comment]
Alright, done.

**Pull request merged**
