### PR TITLE
Fixes the font issues, removes 3 mutations R.I.P

### PR DESCRIPTION
**Pull request by Iamgoofball**
apparently many people don't have microsoft word installed and I thought these fonts were default windows ones

### CODE REVIEW

**Comment by paprka** [comment]
>using microshill word

**Comment by Iamgoofball** [comment]
>not having microsoft word installed for PAPYRUS AND JOKERMAN GOODNESS

**Comment by Mloc** [comment]
you could just specify a secondary font in case the first one can't be loaded, unless BYOND doesn't like that

**Comment by Deantwo** [comment]
Fixing #7259 in this PR too?

**Comment by Iamgoofball** [comment]
no, still can't track down why the fuck that's happening

**Pull request merged**
