### PR TITLE
You can throw plungers into peoples faces

### PR DESCRIPTION
**Pull request by wesoda25**
## About The Pull Request

RN4OCHRR0n

## Why It's Good For The Game

its a tragedy this isn't in already

## Changelog
:cl:
add: You can now throw plungers into peoples faces!
/:cl:

### CODE REVIEW

**Comment by fatted50** [comment]
SPEEDMERGE SPEEDMERGE SPEEDMERGE SPEEDMERGE SPEEDMERGE

**Comment by RiskySikh** [comment]
beautiful

**Comment by Qustinnus** [comment]
you should make it lower visibility and take a while to take off so you can use it as a really shit distraction

**Comment by wesoda25** [comment]
I considered it, but decided to leave plunger based warfare out of this pr. Maybe another day

**Comment by necromanceranne** [comment]
We have pies, and now plungers. Comedy gold.

**Comment by ATH1909** [comment]
InB4 someone manages to kill someone by strapping c4 to a plunger and then throwing it at their face (it's already possible with sticky tape and the like, so this should be fine).

**Pull request merged**
