### PR TITLE
Fix mouse hover outlines applying to other people

### PR DESCRIPTION
**Pull request by Mothblocks**
## About The Pull Request
Instead of just checking if they're inside a bag, it will now be checked that it is *your* bag. 

## Changelog
:cl:
fix: Mouse hover outlines will now only show if the item is on your person.
/:cl:

### CODE REVIEW

**Comment by LemonInTheDark** [comment]
Could you make this use the filter api? it'll cause weird behavior as is

**Comment by LemonInTheDark** [comment]
How does it behave with irradiated objects? I'd assume you want it to outline around their ring, not within it

**Comment by Mothblocks** [comment]
If need be, it can be raised in priority in the future, but for now it works fine.

https://user-images.githubusercontent.com/35135081/111020077-1feef400-8378-11eb-85ba-600c97d1332e.mp4

**Comment by LemonInTheDark** [comment]
Glory be :)

**Review by LemonInTheDark — APPROVED** [review]

**Pull request merged**
