### PR TITLE
Makes vault safe slightly less explosion-proof

### PR DESCRIPTION
**Pull request by QualityVan**
[balance memes]
Three explosions of sufficient strength will render the vault safe door openable. 

Also fixes a bug where if a turf's contents were subjected to one explosion and then had c4 planted on them, half of the c4's explosion wouldn't work. 

:cl: QualityVan
balance: Due to budget cuts, the vault safe is now slightly less resistant to explosions.
/:cl:

Alternative to #33643 
ps send me thermal drill sprites

### CODE REVIEW

**Comment by kevinz000** [comment]
i still think nukeops should deal with it kill everyone and loot the stealthoscope, but w/e.

**Comment by jughu** [comment]
Bad change some vaults start with stuff like tasers and such (meta and pubby) this would allow traitors get a easy stun weapon and fast too

**Comment by InsaneHyena** [comment]
Loot it from whom? From space, where they were all thrown?

**Comment by jughu** [comment]
Time to add a stealthoscope pinpointer

**Comment by KomradeSpectre** [comment]
Downvoted because I like the idea of a thermal drill instead of blasting open the safe.

**Comment by Tlaltecuhtli** [comment]
>making the game easier because people dont know about x mechanic

**Comment by Bawhoppen** [comment]
Seriously, the safe is supposed to be a hard thing to deal with. It's hard for BOTH parties to open, so if someone manages to, it's supposed to be just as hard to REOPEN. Don't make this dumb destroyable hugbox crap.

**Comment by Cyberboss** [comment]
Unpopular it seems

**Comment by KorPhaeron** [comment]
@optimumtact probably the least silly and clunky of the options here

**Comment by optimumtact** [comment]
cut my life into pieces

**Comment by ExcessiveUseOfCobblestone** [comment]
Can someone explain the purpose of the safe should this be added in practical "when would you ever use the safe" situations?

**Comment by optimumtact** [comment]
it hasn't got any, like the vault, it's almost entirely an RP thing you dumb elf eared muppet

**Comment by ExcessiveUseOfCobblestone** [comment]
Unironically a great answer. Now fix mutant parts to have a skin-tone define so that I may add space elves.

**Comment by KomradeSpectre** [comment]
How did this get merged when it had more downvotes than upvotes?

**Comment by Cyberboss** [comment]
This isn't a democracy

**Comment by optimumtact** [comment]
We had to take action because the nuke ops meta was to put the disk in the vault every round and then just dispose of all stethoscopes on the station.

A couple of fixes were mooted but this seemed to make the most sense (blowing up a vault enough should break it open)

**Comment by Bawhoppen** [comment]
You guys didn't even change the description to reflect the change...
Also, actually opening the vaultsafe in a timely manner completely unfeasible without extreme luck. The code to open it sometimes is also literally impossible to get anyways.

**Pull request merged**
