### PR TITLE
Shrunk arrow from pointing at things. Command roles unaffected thanks to id trims (also new skillchip).

### PR DESCRIPTION
**Pull request by Ghommie**
## About The Pull Request
The new arrow icon from the wallening looks nice. However it feels juuuuust a little invasive due to their size, especially if you've to point at specific items or certain wall-related equipment that's become particularly tiny, so I decided to shrink them down. However, I also came with the idea of let command roles (and most non-station leader roles) have these bulkier arrows as a sign of authority (thank you CM-13 for the idea).

Basically, command id trims now grant large arrows, while the rest has smaller ones (about a few pixels bigger than the pre-wallening ones).

Furthermore, I've added a skillchip that lets you have large, **color-customizable** arrows, found inside the games vending machine at the library like the rest.
immagine

EDIT: That's how new, normal arrows look like (I've adjusted the offset and finetuned the shading for greyscale ones a bit btw):
immagine

As a bonus, ERT engineers now have the engineer skillchip; medics, the entrails reader, and the battlecruiser assault team, the disk verifier. All in the sake of some consistency.

## Why It's Good For The Game
The new wallening pointers are a smidge too big imo. Also, as they oft say: "improve, don't remove". I think it befits command roles to have bigger pointers tho, for commanding purposes.

## Changelog

:cl:
image: Shrunk the arrow shown when pointing at things to be less invasive.
add: Wearing an ID with the trim of a command/leader position gives you bigger arrows (about the size of arrows before this PR) which may also be of different colors.
add: Added a skillchip that does the same, but also makes the color of the arrow totally customizable.
fix: ERT engies and medics now come with the engineering and entrails-reader skillchips respectively, like their station counterparts.
fix: Fixed not facing atoms that you're pointing at.
/:cl:

### CODE REVIEW

**Comment by DaCoolBoss** [comment]
I don't think using the larger arrows ever is worth it. Doesn't draw more attention to what you're pointing at, it just obscures things.

**Comment by Ghommie** [comment]
Opinion aknowledged.

**Comment by TheVekter** [comment]
My ADHD ass actually likes the bigger arrows because it's easier to notice, but if I'm in the minority and everyone hates it, then go off I guess.

**Comment by Ghommie** [comment]
> Does it make more sense to put command's large pointer on loudmode rather than on their trim, since they serve the same purpose and trim right now only affects access? We can check for loud mode every time point is used, right?

That seems especially counter-intuitive, sorry.

**Comment by MrMelbert** [comment]
Actually really like the idea of putting it on loud mode

**Comment by Ghommie** [comment]
> Actually really like the idea of putting it on loud mode that makes a lot of sense

No, it doesn't, at least not by itself. That way there'd be no _visible_ (loud is more of a hearable one) cue to why an assistant wearing, let's say, a pumpkin helmet is pointing at things with large arrows. Headsets have a weaker connection to roles than an ID, and can be hidden by clothes.

We can have loud mode (de)activate the large arrows as long as the headset is worn, if that's the idea, but otherwise no.

**Comment by SomeoneYouProbablyKnow** [comment]
I feel like the big arrow is goofy and is a better fit for a library item than the colored arrows. Having colored arrows per department head (blue for cmo, black for hos etc) would make them very noticable and give em some much needed credibility. A big red arrow in a sea of red arrows has less impact than a purple arrow in a sea of red arrows (sorry colorblind players)

**Comment by Wallemations** [comment]
Can you put a pic of the smaller arrow please

**Review by Wallemations — APPROVED** [review]

**Pull request merged**
