### PR TITLE
Fixes some mapping issues with the Pubby SM

### LINKED ISSUE #43049: pubby station supermatter does not keep power during a blackout
## Round ID:

N/A

## Testmerges:

N/A

>go to any other station with a supermatter
>grid check
>engineering APC keeps it's power going

>go to the wiki
>"Shuts down all APCs stationwide for 30 to 120 seconds, **with the exception of Engineering**. Usually leads to stationwide looting once Assistants crowbar open airlocks.
Can be fixed early by hitting the APC's "Reset" button."

what

### PR DESCRIPTION
**Pull request by actioninja**
## About The Pull Request

Fixes a couple of mapping errors and small complaints people had on the Pubby SM:

- Cooling loop size has been reduced
- Layer manifolds start on top level instead of below the floor
- Emitters and Reflectors start anchored, positioning has been slightly changed
- Freezers have been rotated to connect to pipes properly
- Filters have been switched to critical filters to prevent the APC from shutting off during a grid check
- Heaters have been removed

Closes #43049 

## Why It's Good For The Game

Fixes errors and some complaints

## Changelog
:cl:
fix: Fixed a few mapping issues with the Supermatter on Pubbystation
/:cl:

### CODE REVIEW

**Review by ShizCalev — CHANGES_REQUESTED** [review]
make a /visible typepath for the manifolds, then set
		level = PIPE_VISIBLE_LEVEL
		layer = GAS_PIPE_VISIBLE_LAYER

**Comment by ShizCalev** [comment]
you hit the manifold in atmosia too, right? don't see it in the render

**Comment by actioninja** [comment]
I thought I had replaced it but apparently I hadn't

**Comment by ShizCalev** [comment]
image


was this caution stripe intentional?

**Pull request merged**
