### PR TITLE
Language icons

### PR DESCRIPTION
**Pull request by coiax**
:cl: coiax, WJohnston
del: Languages no longer colour their text.
add: Languages now have icons to identify them. Galatic Common does not have an icon if understood.
/:cl:

Shoutout to WJohnston for designing the adorable language badges.

Here are some screenshots of it.

image
image

- Modifies say code a bit, we now have a `say_mod` proc, since most modification of `say_quote` was just changing the say modifier. Makes it easier to move the icon around.

### CODE REVIEW

**Comment by Ausops** [comment]
could you please consider moving the icon to the very start of the line? With differing name lengths it's gonna look like a mess and it would look more tidy if it was at the start of the sentence.

**Comment by coiax** [comment]
@Ausops that's very easy to do codewise, but I hear a lot of different requests where to put the icons.

**Comment by Ausops** [comment]
please make it look tidy

do it for the people with autism and ocd

**Comment by Armhulen** [comment]
Didn't delet poly/10

eeeh I don't really like how this looks, the color adds life to speaking as a chimp

**Comment by coiax** [comment]
@Armhulen Not everyone likes the colours sadly. Particularly the maintainers

**Comment by Armhulen** [comment]
I know :(

**Comment by lzimann** [comment]
I think the icons at the start of the line would be better. And maybe before the name if you talk in radio.

**Comment by Tacolizard** [comment]
icons before the line is better, but colored text makes it seem more interesting. The best would be what VG does, their languages use different fonts.

**Comment by Thunder12345** [comment]
\>Observing
\>Every single message has galactic common icon

**Comment by Thunder12345** [comment]
(F) DEAD: Jazmin Malcovich Oh hey ghosts don't do "says," either

**Comment by XDTM** [comment]
> (F) DEAD: Jazmin Malcovich Oh hey ghosts don't do "says," either

I have no mouth and i must chat

**Comment by WJohn** [comment]
Galactic Lizard language icon. Apparently lizards get their own languages?

**Comment by coiax** [comment]
Gonna be another PR to introduce lizard languages. But may as well get the icons sprited now.

**Comment by Alek2ander** [comment]
This looks like something worthy of a client preference (color (and/or) icon before name (or) icon after name) because everyone has a preferred layout and hates all others

**Comment by Armhulen** [comment]
FUCK this pr SUKS.

**Comment by PKPenguin321** [comment]
wait this applies to common?
why?

**Comment by lzimann** [comment]
Common will only show the icon if you don't understand it.

**Pull request merged**
