### PR TITLE
Fixes lizards still speaking draconic after being turned into not-lizards

### LINKED ISSUE #34943: How to speak draconic as a head of staff
1. Set up a lizard character.
2. Late join into a head role.
3. ???
4. Profit.

### PR DESCRIPTION
**Pull request by ghost**
fixes #34943

### CODE REVIEW

**Comment by ACCount12** [comment]
Shouldn't people who were transformed by xenobio/wizard shenanigans retain their minds and languages?

**Comment by GunHog** [comment]
Hang on now, you do not magically forget how to speak your native language if you are changed into something else - and you do not magically learn to speak a language by becoming a new race, unless said language is an inherent trait of the body (like a jelly).

**Comment by MoreRobustThanYou** [comment]
@GunHog can't lizards only speak draconic due to their special lizard tongue?

**Comment by coiax** [comment]
No, human tongues are capable of speaking Draconic.

I don't know what you're doing in this PR, but it's wrong. Languages being tied to the mind and not the mob is kind of the WHOLE POINT of the languages system that I introduced.

**Comment by Dorsisdwarf** [comment]
Pretty sure this is not the proper way to fix the issue described

**Comment by BeeSting12** [comment]
thats not the way i want this fixed.

**Pull request closed without merging**
