### PR TITLE
Removes the bloodthirst mechanic from Highlander

### PR DESCRIPTION
**Pull request by ghost**
:cl: Nanotrasen Stress Relief Board
del: Claymores created through Highlander no longer thirst for blood or announce their wielder's location incessantly.
fix: Claymores should now properly absorb fallen foes' corpses.
fix: Losing a limb now properly destroys your claymore.
/:cl:
- Removed the bloodthirst mechanic. It was causing a plethora of problems and bugs, and I decided that if people want to be cowards and forfeit their chance at success, they can.
- Claymores now absorb the corpses of any highlander that's dead, instead of just the killing blow.
- Having your wielding arm chopped off now destroys your claymore.

I can't address any comments or suggestions about this starting tomorrow, as I have an intimate visit with Hurricane Matthew. Get your notes out of the way while my power's still on.

### CODE REVIEW

**Comment by nullbear** [comment]
could make claymores two-handed weapons,

**Comment by Militaires** [comment]
@nullbear but need pick up disk for highlander objective

**Comment by Shadowlight213** [comment]
@Xhuis readd the soul being absorbed into the sword and absorbed people being like pais in the sword when?

**Comment by Supermichael777** [comment]
needs a healing mechanic so you can fight and still win

**Comment by nullbear** [comment]
THIS!! ^^^ Reward fighters with healing. Kills heal maybe?

**Comment by nullbear** [comment]
Or swords leech 1/2 damage dealt?

**Comment by Xhuis** [comment]
All righto. Matthew's past and my power's on.
@Shadowlight213 Probably never.
@Militaires Claymores pick up the disk by hitting it. This is doable but I'd rather not. Two-handed weapons are clunky and odd.
@Supermichael777 @nullbear ...that's the exact mechanic that I have in place. Killing someone heals you for all your health.

**Pull request merged**
