### PR TITLE
Removes some rogue spaces

### PR DESCRIPTION
**Pull request by Anonmare**
:cl:
spellcheck: Removed some rogue spaces in the mechanical repair nanites program's checks
/:cl:

[why]: It bothered me

### CODE REVIEW

**Comment by Kagus** [comment]
👏 IMPROVE 👏 DON'T 👏 REMOVE 👏

**Comment by Jordie0608** [comment]
These spaces aren't rogue, `, argument` is preferred to `,argument`, change the other two calls on L14 and L22 if the difference bothers you.

**Comment by MrDoomBringer** [comment]
\>literally thousands and thousands of occurances of `, argument`
\>submits a PR that literally changes two of them
image

**Comment by ninjanomnom** [comment]
There's no reason to change this and this is honestly more the standard than not having spaces

**Pull request closed without merging**
