### PR TITLE
Mjolnir resprite

### PR DESCRIPTION
**Pull request by ProtivogaSpriter**
## About The Pull Request

Switches out the old Mjolnir sprites for the new ones, including inhands.
Mjollnir

## Why It's Good For The Game

Makes the Mjolnir look a lot nicer.

## Changelog
:cl:
imageadd: added new Mjolnir sprites
imagedel: removed old Mjolnir sprites
/:cl:

### CODE REVIEW

**Comment by MrDoomBringer** [comment]
honestly I don't see that big of an improvement over the old sprite

**Comment by optimumtact** [comment]
If you are leaving criticism that is so bare of information it can't be used to actually improve the sprite probably best to restrain yourself to a thumbs down @MrDoomBringer

**Comment by MrDoomBringer** [comment]
> If you are leaving criticism that is so bare of information it can't be used to actually improve the sprite probably best to restrain yourself to a thumbs down @MrDoomBringer

Good point @optimumtact, let me elaborate on my two-cents a bit:

Overall what you have now is a good start

image
- The old sprite's 'electric' overlay animation is IMO a tacky representation of something "crackling with barely-contained energy". The animation should be subtler - small, quick sparks around the hammer could look nice - especially if they were less garishly yellow.

image
- The new head looks like it was shaded without much thought, and looks to me more like a grey stick of butter than an iron hammer. Shade the outline a bit, experiment with lighter on the left and darker on the right, let yourself use more than 3 colors. The brown handle-grips are good, I want to see more of that.
- The old head, though simpler, has a shape that conveys more heft/weight. Less streamlined, more big-chunk-of-metal. 
- Do something with the connection between the handle and the head. Right now it looks like they're two separate objects.

Feel free to reach out to me on discord if you want anything clarified (MrDoomBringer#9147), or our sprite lead @Twaticus who has final say on this change.

**Comment by maxymax13** [comment]
the old one looked like a big spoon made out of the minecraft sea temple stuff but this one looks really flat, not really a big chubky hammer of death. give it some depth

**Comment by ProtivogaSpriter** [comment]
> > If you are leaving criticism that is so bare of information it can't be used to actually improve the sprite probably best to restrain yourself to a thumbs down @MrDoomBringer
> 
> Good point @optimumtact, let me elaborate on my two-cents a bit:
> 
> Overall what you have now is a good start
> 
> image
> 
> * The old sprite's 'electric' overlay animation is IMO a tacky representation of something "crackling with barely-contained energy". The animation should be subtler - small, quick sparks around the hammer could look nice - especially if they were less garishly yellow.
> 
> image
> 
> * The new head looks like it was shaded without much thought, and looks to me more like a grey stick of butter than an iron hammer. Shade the outline a bit, experiment with lighter on the left and darker on the right, let yourself use more than 3 colors. The brown handle-grips are good, I want to see more of that.
> * The old head, though simpler, has a shape that conveys more heft/weight. Less streamlined, more big-chunk-of-metal.
> * Do something with the connection between the handle and the head. Right now it looks like they're two separate objects.
> 
> Feel free to reach out to me on discord if you want anything clarified (MrDoomBringer#9147), or our sprite lead @Twaticus who has final say on this change.

Thanks for the criticism! I can't seem to correctly enter your discord username and/or tag, though. Is there any mistakes in there or am i just being dumb again?

**Comment by Greniza** [comment]
Something I'd say needs to be done is a fix of the lines on the head. For a hammer of that general shape, you'd never see a hitting face parallel to the shaft, as you swing a hammer in a circular motion; the lines on the hitting faces should point generally to the other end of the hammer's shaft, like a mallet. You can sort of see these lines on the old hammer, but they're sort of missing on the new one.

**Comment by MrDoomBringer** [comment]
> Thanks for the criticism! I can't seem to correctly enter your discord username and/or tag, ...

lmao oops
image

**Pull request closed without merging**
