### PR TITLE
Toolbox buff

### PR DESCRIPTION
**Pull request by yackemflam**
:cl:Toolbox Glory
tweak: GLOOOOOOORY
/:cl:

Because toolboxes should be robust

### CODE REVIEW

**Comment by ma44** [comment]
It needs to be 80 force

**Comment by PKPenguin321** [comment]
Oh look this pr *again*

**Comment by Cheridan** [comment]
This PR was already denied, like, yesterday.

**Comment by yackemflam** [comment]
Aye, denied without reason

**Comment by PKPenguin321** [comment]
I hope you're memeing

**Pull request closed without merging**
