### PR TITLE
Revert "Removes the gang gamemode" #26915 Final attempt.

### PR DESCRIPTION
**Pull request by LanCartwright**
:cl:
del: Removes gang gamemode.
/:cl:

Final PR. Dunc do not close this unless you prove a reasonable argument why the past year and a half we've benefitted from not having this should suddenly return in a buggy form you're calling features.

[why]: # 
Horribly buggy game mode; implants are not consumed on first break.
Implanted gang members retain gang status.
Gang members can be implanted and stay gang.
Gang round was not enjoyable.

https://github.com/tgstation/tgstation/issues/27003 - 'Implants don't deconvert gang'
https://github.com/tgstation/tgstation/issues/27004 - 'Implants are not consumed when breaking gang members' 
https://github.com/tgstation/tgstation/issues/27005 - 'Gang members can have implanted status on their SecHUD'

### CODE REVIEW

**Comment by kevinz000** [comment]
what good is opening a pr to revert something that was unsucessfully attempted to be reverted less than a week ago?

**Comment by coiax** [comment]
Honey, you don't reopen a PR that a maintainer has closed

**Comment by lzimann** [comment]
I hate doing this for something I would like gone, but hey, come on. PR was already closed before.

**Comment by jughu** [comment]
Sandbox is a horrible gamemode and code but we arent deleting all code for that anyways 😏

**Comment by Cyberboss** [comment]
Are you trying to get gitbanned son?

**Comment by LanCartwright** [comment]
Not quite, but I got an extremely unreasonable response by Dunc the first time I opened it.
It's now a buggy game mode that is absolutely atrocious to play. 
I stand by my decision and defiance to Dunc, but this one was final.

**Comment by lzimann** [comment]
Don't worry, it will eventually die.

**Comment by PKPenguin321** [comment]
If you want to remove an entire gamemode over three bugs instead of fixing the bugs you may as well delete the entire codebase for the same reason

**Comment by LanCartwright** [comment]
actually pkp;
I want to stop my friend taking drugs.

What you want me to do us produce those drugs and legalise them so my friend can enjoy free legalised drugs, or kill my friend entirely.

I do not want to go through such an effort for something so inherently bad, nor do I want to kill my friend.

I want my friend off the drugs like I want tgstation not to have gang.

**Comment by PKPenguin321** [comment]
You're retarded if serious I thought this was a joke PR

**Comment by LanCartwright** [comment]
Are you gonna address my argument or not?

**Comment by duncathan** [comment]
if you​ aren't self aware enough to be fully aware you're acting like a reet, there's not much I can do to help

**Comment by LanCartwright** [comment]
I'm only acting on what I think is the best for tgstation's SS13. I'm doing what is good for the game I play and the server I donate to keep up.

If you're not aware of the division of opinion, there's no reason why I would fix what I don't want, and help what I don't like.

**Comment by Iamgoofball** [comment]
@LanCartwright its ok, be patient, gang'll get axed again soon.

**Pull request closed without merging**
