### PR TITLE
CODE FREEZE

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
My Christmas gift to myself is no new feature or balance arguments for a couple weeks.

Bug fixes and refactors only. As always, PRs that were opened before the freeze are exempt from this rule.

I'll talk to the other maintainers about an official end date/bug fix count target and any potential prizes.

**As with last year, anyone who fixes at least one bug gets an antag token**

### CODE REVIEW

**Comment by KorPhaeron** [comment]
@kevinz000 

Plenty of time to fix flight suits and pAIs then

**Comment by dannno** [comment]
if borg blogs dont get fixed before this im coming for you

**Comment by KorPhaeron** [comment]
Your PR was open before the freeze started, so it is not frozen

**Comment by dannno** [comment]
ty

**Comment by Incoming5643** [comment]
http://pastebin.com/raw/PkERhAy9

**Comment by Cyberboss** [comment]
Yo what about refactors?

**Comment by lzimann** [comment]
>Bug fixes and refactors only. As always, PRs that were opened before the freeze are exempt from this rule.

**Comment by Okand37** [comment]
Does this apply to maps as well? If so, I originally had an omegastation PR up before the feature freeze was announced but had to close it and am reopening it due to a number of conflict issues that I need to resolve first. Will I still be able to get that in during the code-freeze period when I make the new PR later today after I resolve the conflicts?

**Comment by Cyberboss** [comment]
>Mfw i cant read

**Comment by KorPhaeron** [comment]
Yeah sure Okand, it was open beforehand

**Comment by AnturK** [comment]
Thanks kor.

@Okand37 Map changes are usually exempt.
@Cyberboss Refactors are fine as long as they do not add new functionality.

**Comment by Iamgoofball** [comment]
Fuck

Guess I'm on an extended vacation

**Comment by jughu** [comment]
Free antag tokens? HMMM

**Comment by Haevacht** [comment]
Goof just fix your shit for once if your life instead of meme prs.

**Comment by Iamgoofball** [comment]
I do design not tracking down bugs

**Comment by lzimann** [comment]
he's too good to fix bugs

**Comment by Iamgoofball** [comment]
This is true the antag tokens would be wasted on me

**Comment by Mervill** [comment]
TFW your not cool enough to be assigned to the task.

Pedantic question: what about bugs that get fixed by adding things? For example I was going to fix a bug with vending machines by adding the ability for them to be built as initially empty (new behavior). I guess it's just a case by case thing or ... ?

**Comment by jughu** [comment]
Now if you guys be nice to close bugs like teamling objectives dont work properly because these thibgs dont exist anymore do they

**Comment by Thunder12345** [comment]
Code freeze: Winter wonderland edition

**Comment by JJRcop** [comment]
Can I open a PR I've been working on for a few months, and just have it DNM until the freeze is over?

**Review by Razharas — APPROVED** [review]
Very nice 👌

**Comment by KingPhilipIII** [comment]
I wish I knew how to code. Dem antag tokens.

**Comment by Shadowlight213** [comment]
Do the merge token system again. That worked out pretty well last time.

**Comment by lzimann** [comment]
@KingPhilipIII it's a good time to learn then!

**Comment by KingPhilipIII** [comment]
@lzimann Well. I guess I have a few weeks to learn how to code completely from scratch.

**Comment by Cyberboss** [comment]
What JJRcop said, I'll have forgotten about the branch by the time the freeze is over

**Comment by KorPhaeron** [comment]
Yeah sure whatever

**Comment by Mervill** [comment]
so is it only the one antag token if you fix more then one bug? or is it one antag token _per_ bug?

not that anyone's counting

**Comment by AnturK** [comment]
The former.

**Comment by Shadowlight213** [comment]
Only the one.

**Comment by Mervill** [comment]
not like i was ever in it for antag tokens anyway

**Comment by Shadowlight213** [comment]
You totally were

**Comment by Mervill** [comment]
Notice I haven't made any new PRs since the news was broken to me

**Comment by calzilla1** [comment]
Can you please tell us the end date/fix goal

**Comment by optimumtact** [comment]
It's done when I say it's done

**Comment by calzilla1** [comment]
Hopefully never!

**Comment by Mervill** [comment]
Issues `799`

OwO

**Comment by MrStonedOne** [comment]
\>No warning
\>No end date

\>People are now going to have to wait up to a month (if not more) for the prs they wanted to do
\>No warning

\>People who were in the middle of coding something have to wait a month (if not more) before they can pr it
\>No warning

\>They will also have to deal with up to a month (if not more) worth of conflicts to fix
\>No warning

\>They could have had a chance to finish the pr before the freeze started but:
\>No warning

**Comment by MrStonedOne** [comment]
If you have a pr to make, go ahead and make, if it gets closed for being a feature, message me and i'll test merge it in.

In the mean time, until coderbus figured out what the fuck it's doing, I've disabled updates so that pr tests jobs won't go away.

**Comment by MrStonedOne** [comment]
>No warning
>No end date

>People are now going to have to wait up to a month (if not more) for the prs they wanted to do
>No warning

>People who were in the middle of coding something have to wait a month (if not more) before they can pr it
>No warning

>They will also have to deal with up to a month (if not more) worth of conflicts to fix
>No warning

>They could have had a chance to finish the pr before the freeze started but:
>No warning


If you have a pr to make, go ahead and make it, if it gets closed for being a feature, message me and i'll test merge it in.

In the mean time, until coderbus figures out what the fuck it's doing, I've disabled updates so that pr tests jobs won't go away.

**Comment by optimumtact** [comment]
mso does slapcrafting 2 electric boogaloo

**Comment by KorPhaeron** [comment]
Why does every disagreement have to start at 100% escalation scorched earth nuclear option and then slowly work back towards actually talking and working things out

The end date is January 31st or 600 bugs left, whichever happens first

**Comment by Mervill** [comment]
Now that I am informed of the intentions of the maintainers, I can make better decisions about what to focus my attention on next

huh

weird

**Comment by Mervill** [comment]
and I think that as the freeze goes on there's this kind of anxiety that builds up? I can't really explain it. I think the feature freeze has been a huge success ... but I also want it to end soon. This has always been a repository flying by the seat of it's pants, and we're eager to get back to falling with style

**Comment by calzilla1** [comment]
Couple=2
Jan31>2 weeks
Kor is bad at math

**Comment by MrStonedOne** [comment]
>and I think that as the freeze goes on there's this kind of anxiety that builds up?

Its because this freeze had no warning, no build up, no time to finish your projects, no preset ending date. everybody assumed it would be for a week or so, mainly because it says so in the op. when that turned into over a month overnight, that also didn't help

**Comment by calzilla1** [comment]
>xkcd
Please leave and never come back

**Comment by Mervill** [comment]
> github dot com, literally the center of open-source programming on the internet

> triggered by xkcd

**Comment by Cyberboss** [comment]
Fuckin rekt

**Comment by optimumtact** [comment]
xkcd is like babys first webcomic

**Comment by calzilla1** [comment]
What we need is another mass wiki edit

**Comment by bgobandit** [comment]
that was me, I should do another one

**Comment by Mervill** [comment]
\> tfw there are still two whole weeks left

**Comment by calzilla1** [comment]
Or 118 more issues! Or 69 issues a week

**Comment by MrStonedOne** [comment]
we are at 168 closed issues per week, so I think we might be able to thaw this early.

if we did 11 closed issues per day we would have this thawed out before the 20th

**Comment by GunHog** [comment]
But people keep making MORE! You failed to account for that variable!

**Comment by Mervill** [comment]
We're at 376 closed issues  and 83 new issues (Dec 10 - Jan 10), for a net count of 293 issues, so we're still closing at a very rapid rate

We're starting to approach that point there most of the easiest fixes have been found and submitted, soon there will only be weird/systemic/difficult bugs left

**Comment by calzilla1** [comment]
I say we bump the issue goal to 650!

**Comment by lzimann** [comment]
I say we bump to 500.

**Comment by optimumtact** [comment]
YOU WANT FEATURES? FUCK YOU, FEATURES ARE FOR CLOSERS

A - ALWAYS
B - BE
C - CLOSING

**Comment by Mervill** [comment]
Once Jan 24th rolls around, it will have been 1 month (in terms of # of days) and the pulse page on the project will show a pretty accurate picture of what's been done during the freeze. Right now it includes things from early December (which isn't much).

**Comment by calzilla1** [comment]
I say make make the goal 0 and not end the freeze until all the issues are closed!

**Comment by PKPenguin321** [comment]
none of the fixes are getting updated onto the servers live this freeze feels very counter productive for that reason

**Comment by Mervill** [comment]
> none of the fixes are getting updated onto the servers live

What?! That can't be true

**Comment by PKPenguin321** [comment]
Lost my lungs as a changeling and when I regenned they didnt grow back which was fixed and merged four days ago
*shrug*

**Comment by Cyberboss** [comment]
> The sound of all of coderbus except Kor hanging itself

**Comment by Mervill** [comment]
Changes are definitely being made live. Sometimes it takes a while though. Also changelings might just be broken still. I'd ask coderbus first

**Comment by optimumtact** [comment]
Sybil doesn't seem to update as regularly as basil

**Comment by calzilla1** [comment]
Holy shit were already at 668, we might close this before the 20th!

**Comment by JJRcop** [comment]
Let's make the goal 590

**Comment by MrStonedOne** [comment]
MrStonedOne Wrote:  
>we are at 168 closed issues per week, so I think we might be able to thaw this early.
>if we did 11 closed issues per day we would have this thawed out by the 20th

**Comment by KorPhaeron** [comment]
We really ought to do the cleaning out of old and duplicate issues prior to setting a freeze goal, cleaning the tracker is nice but it results in far less bugs actually being fixed

**Comment by Mervill** [comment]
```
December 12, 2016 – January 12, 2017
426 Merged Pull Requests
440 Closed Issued
```

Yeah I bet we haven't even fixed a single real issue!

We've done nothing short of phenomenal work during this freeze

**Comment by calzilla1** [comment]
Issues:666
Spooky

**Comment by Kromgar** [comment]
Issues: 649 this aint thawing till february

**Comment by Mervill** [comment]
We've run into a wall now that most of the straightforward issues have been dealt with. That being said, there are probably about 40 "not a bug" issues that could be closed today. That would put us in spitting distance of the goal

**Comment by calzilla1** [comment]
636 issues, if we can do 18 a day we can get this done before the 20th or 12 to be done ON the 20th

**Comment by Cyberboss** [comment]
Actually, we have enough fix PRs open to finish it right now. Maintainers need to jump on it

**Comment by calzilla1** [comment]
Make it so the person who does the most/ last fix gets another antag token

**Comment by Kromgar** [comment]
629 and going higher

**Comment by Cyberboss** [comment]
The fruit is AWOL and not merging.

**Comment by ChangelingRain** [comment]
599 IT'S TIME TO THAW

**Comment by PKPenguin321** [comment]
🤢 joan did this just to push his cuckwork agenda!

**Pull request closed without merging**
