### PR TITLE
Adds a public autolathe to all maps.

### PR DESCRIPTION
**Pull request by Iamgoofball**
remake of #12735 not on my alt

The two stations that already had public autolathes, Metastation and Birdstation, were left alone.

Ministation, due to lacking a Primary Tool Storage, had its autolathe placed in the maintenance cubby where the Youtool and other tool storage machines are.

All other stations had a public autolathe placed in its Primary Tool Storage.

### CODE REVIEW

**Comment by Zilenan91** [comment]
In before cries of, "B-buh muh scarcity!"

Either way, :+1:  good shit that's some good shit

**Comment by PKPenguin321** [comment]
:+1:

**Comment by Incoming5643** [comment]
You'll need to increase the cost of revolvers and/or remove the ammo

**Comment by optimumtact** [comment]
:+1: okay for this I guess, kinda pointless though since nobody ever needs them anyway

**Comment by TheNightingale** [comment]
I like it. Metastation already has one in the Science foyer, remember.

**Comment by Fox-McCloud** [comment]
Pics?

**Comment by Anonus** [comment]
I don't support this, mostly because meta is the station-based embodiment of excess availability and birdboat is, uh, birdboat.
Plus autolathes can shit out RCDs and RPDs if hacked, which I really do not want.

**Comment by Fox-McCloud** [comment]
Maybe a child of the autolathe that doesn't have everything the regular autolathe has? That is to say, common tools, but not super dangerous stuff like ammo, handcuffs, RCDs, etc.

**Comment by AlexCrimson** [comment]
Just remove Airlocks so everyone can get everything they need without relying on human interaction. 

0/10 terrible addition but will get merged anyways

**Comment by Metacide** [comment]
>Maybe a child of the autolathe that doesn't have everything the regular autolathe has? That is to say, common tools, but not super dangerous stuff like ammo, handcuffs, RCDs, etc.

That'd be very handy and I'd happily replace the MetaStation's public autolathe with one. 

Having a public autolathe really is very convenient, and I haven't heard much about it being used like people fear (though  I assume it happens).

**Comment by AlexCrimson** [comment]
What do you need so urgently that you cannot wait at Cargo for them to make it for you? I cannot imagine anything. Unless you are an Assistant fucking around.

**Comment by duncathan** [comment]
@AlexCrimson yeah sorry but I'm not particularly fond of waiting 15 minutes for my lightbulb because the cargo techs aren't doing their job/are nonexistent

**Comment by AlexCrimson** [comment]
Player problem, and a rare one. You want everyone to have access to Handcuffs and Circular Saws just because one round you couldnt repair a damn lightbulb?

**Comment by PKPenguin321** [comment]
@AlexCrimson 
oh yeah because waiting to get an item from cargo is always such a wonderful player interaction experience
"Please fill out the forms required to get an item from the autolathe. Note that they require a stamp from the HoP and QM, and the QM cannot stamp them until the HoP already has. Yes, this is me trying to bait you into breaking in so I can valid you."
Player interaction isn't inherently a good thing

**Comment by sirnat** [comment]
Please add, its so annoying having to deal with the shitty cargonians just for simple things. 

It also may add a way for traitors to do surgery in maint alot better. I like that idea, being able to print surgery tools and then set up in maint surgery

**Comment by Razharas** [comment]
All crew having RCDs sounds highly fucked up if you want to escape alone/rogue AI

**Comment by Fox-McCloud** [comment]
Why not give R&D an autolathe? Or Engineering? It makes sense that both of these locations would have them.

**Comment by AlexCrimson** [comment]
@PKPenguin321 Literally nobody does that on this server. Stop making up stupid shit.

R&D can easily make their own, and give Engineering the materials to make their own.

**Comment by PKPenguin321** [comment]
i'm really not making it up though

and if it's so easy to get an autolathe anyways like you claim it is, why not just cut out the middleman

**Comment by sirnat** [comment]
I actually had a small change in opinion now. 

Instead a full lathe, I say make it a baby lathe:
Ordinary tools only (No multi-tools)
Med stuff
No sec items (Hacked gives handcuffs)


Basically make it where its a staff goal of RND for assistants to not bother them/cargo to upgrade their tech and then a scientist can go decon the baby autolathe, and make a public autolathe. 

It adds more objectives for science to do, imo.

**Comment by AlexCrimson** [comment]
You are making it up. In all the time ive played on /tg/, ive never once seen a Cargo Tech or QM ask for signed forms just so you can have something made from the Autolathe. chances are if that ever happens, its just someone being a dick. Not enough of a reason to justify giving everyone on the station access to all that stuff.

The middleman is there for a reason. Same reason areas have access restrictions.

**Comment by Dorsisdwarf** [comment]
The middleman is an ass 90% of the time

**Comment by Fallcon** [comment]
No please, no.

**Comment by AnonymousNow** [comment]
You whippersnappers don't remember the public autolathe, where EVA is now?

Yesh, I shay.

**Comment by Nanotransistor** [comment]
:-1:  Why not make everyone start with all access and magic?

**Comment by optimumtact** [comment]
okay, equating a public auto-lathe to people starting with all access and magic is getting a little ridiculous

**Comment by Iamgoofball** [comment]
@optimumtact every discussion about machines and access changes goes down that route

**Comment by HankMoodyExperience** [comment]
@AlexCrimson you really havent even played long enough to see paperwork cargo?; are you also going to suggest the 'lathe be restricted to cargo technicians only to "encourage roleplay?"

**Comment by AlexCrimson** [comment]
Im not saying ive played for a long time, im saying that in the time i have played, ive never once seen cargo ask for signed documents for anything other than Crates or if they are being jerks.

Its not a regular enough occurrence to justify making the Autolathe public access. The only people who would want that are Assistants who want to fuck around.

**Comment by Nanotransistor** [comment]
It may be an extreme example, but my point is, not everything is supposed to be easy to get. And if today we add a public lathe, tomorrow more stuff like this will be added to the general public and we are left with a game where nobody speaks or interact with anyone. 

The last games i've played in cargo, i don't think anyone ordered any crate at all, the lathe was the only form of interaction between cargo and the crew.

**Comment by Core0verload** [comment]
:+1: I remember shitstorm when it was removed. Was it Erro?

**Comment by sirnat** [comment]
I've played TG for a year now, never have I ever had cargo tell me to fill forms to print something from the lathe.

**Comment by bgobandit** [comment]
I like the babylathe idea

**Comment by AlexCrimson** [comment]
Yeah a special machine for common items seems fine, however we have most of the stuff in machines already, no? There are plenty of public-access vending machines that have tools, and there are plenty of lightbulb boxes. What exactly does the Autolathe produce that makes everyone want a public one? Surgery Tools? If you were supposed to have them then you would be a Medical Doctor with access to them.

**Comment by Iamgoofball** [comment]
Beakers are a big one that the autolathe can make.

**Comment by AlexCrimson** [comment]
Beakers? Last i checked Chemistry started with two boxes of the things, with more in Med Storage. Large one? You get two of those, and shouldnt need more. Once again, not enough to justify making the Autolathe public. Hell, add a box or two to the Chemistry Closet if its that big of a deal.

**Comment by Iamgoofball** [comment]
Big beakers are the only beakers worth using.

**Comment by AlexCrimson** [comment]
Then like i said, add more. Why do you need to make the Autolathe public when you could easily add a few more Large Beakers to the map?

**Comment by Fallcon** [comment]
I agree with the others. Fuck small beakers, especially with the new chemistry. You NEED big beakers. And fucking 300 unit ones from R&D if possible. Add a fuck-ton more of them.

**Comment by Iamgoofball** [comment]
I'm tempted to do t4 500u beakers again.

**Comment by Iamgoofball** [comment]
someone lightly glanced at a map and now this conflicts so RIP

**Pull request closed without merging**
