### PR TITLE
Revert "Revert "Revert "Revert "Typos in syndicate uplink descriptions""""

### PR DESCRIPTION
**Pull request by iamafsh**
Reverts tgstation/tgstation#27991
is the citrus watching closely enough

### CODE REVIEW

**Comment by Bawhoppen** [comment]
oranges don't close because our downstreams will fail to be up to date if you do

**Comment by ma44** [comment]
REVERT CHAIN

**Comment by factoryman942** [comment]
merge and let oranges make another revert
we need to go deeper

**Comment by Cheridan** [comment]
y4ncjyq

**Comment by LetterJay** [comment]
Pls.

**Comment by kevinz000** [comment]
plz

**Pull request merged**
