### PR TITLE
Adds medical department medals (updated sprites)

### PR DESCRIPTION
**Pull request by RaidenKoizuma**
## About The Pull Request
This adds a medical lockbox to the CMO's locker which contains two medical department-centric medals. Exemplary Performance Medal is on par with a bronze/conduct medal while the Excellence in Medicine medal is on par with a silver medal. Please let me know if there should be any changes with the sprites or descriptions. Thank you!
image
image
image
image

## Why It's Good For The Game
Every other department in the game has medals that they can give out aside from engineering. Specifically,
Service: 1 dep. specific, 1 medal in lockbox ( Excel in Beuro.)
HOS: 1 dep. specific 3 medals total in lockbox
HOP: 1 dep. specific, 4 medals total in lockbox (Excel in Beuro. + Ordom, technically 2 HOP department-specific)
QM:  1 dep. specific, 1 medal in lockbox
RD:  1 dep. specific, 3 medals total in lockbox

This gives the CMO 2 department-specific medals at the cost of only having two within the lockbox. Medals are important for CMO to encourage employees to keep on task and to reward initiative within the department. It is also good for RP as being rewarded can be a significant event within the department among peers. It only makes sense that the medical department, which is imperative for most rounds, has the same features that are available within every other department. Also, the two medals are marked ABOVE_SUIT = TRUE as all medical employees wear some kind of lab coat which completely obscures all medals, defeating the purpose. Also, they can alt click the badge to set it to above/below the suit at will, so this doesn't really matter.

## Changelog
:cl:
add: Added a medical medal lockbox to spawn within CMO's secure locker which contains two medals
/:cl:

### CODE REVIEW

**Comment by JohnFulpWillard** [comment]
God those labcoat sprites...

**Comment by RaidenKoizuma** [comment]
Yeah the worn sprites may be a bit big, I'm honestly unsure. I've squished it down as small as possible without losing what its supposed to look like. If needed I can do it more.

**Comment by RaidenKoizuma** [comment]
Alrighty, I reworked the sprites, please look at the new images.

**Review by Mothblocks — APPROVED** [review]
Code ✔

**Comment by VladinXXV** [comment]
I think I'd rather them go beneath the labcoat, both for consistency and preference. And besides, who would wear a labcoat with sprites like those? The labcoat resprite was a mistake, god help us all.

**Comment by RaidenKoizuma** [comment]
> I think I'd rather them go beneath the labcoat, both for consistency and preference. And besides, who would wear a labcoat with sprites like those? The labcoat resprite was a mistake, god help us all.

In all honesty, it doesn't matter if ABOVE_SUIT is set to true or false, the player can alt click on any badge to have it appear above or below their suit. It's just the default setting is above. All badges can be above at will.

**Comment by VladinXXV** [comment]
Dare I suggest a third? Something along the lines of excellence in "experimental medicine". A medal for all the MDs making chimeras and Frankenstein's Monsters.

**Comment by RaidenKoizuma** [comment]
I originally had a third, a ribbon, but that would be pushing it since no other head has 3 dep. specific medals. And the current medals are broad enough, like the other medals, to be applicable to anyone within the department for anything.

**Comment by VladinXXV** [comment]
Fair. Are the sprites shown in the PR up to date?

**Comment by RaidenKoizuma** [comment]
Yes. The sprites in the pictures are current.

**Pull request merged**
