### PR TITLE
Fixes syndicate lava base access

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
:tada:

### CODE REVIEW

**Comment by Armhulen** [comment]
h-honk

**Comment by kilkun** [comment]
KOR = GOD

**Comment by Okand37** [comment]
The fun thing was that the doors were never truly broken, the ID's access was! Glad to see it fixed though!

**Comment by kilkun** [comment]
i ❤️ u kor senpai

**Comment by ExcessiveUseOfCobblestone** [comment]
give them access 150 [I think?] if you don't want them to have their own agent card.

**Comment by karlnp** [comment]
finally! again!

**Comment by RandomMarine** [comment]
May as well get rid of the comms guy's normal id too.

**Comment by Shadowlight213** [comment]
I probably fucked something up on my fix.
This is technically a bandaid solution, so I'll revert it once I fix it.
Good temp fix in the meantime.

**Pull request merged**
