### PR TITLE
Gsdfgsdfg

### PR DESCRIPTION
**Pull request by actioninja**
## Changelog
:cl:
add: Added new things
add: Added more things
del: Removed old things
tweak: tweaked a few things
balance: rebalanced something
fix: fixed a few things
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

### CODE REVIEW

**Comment by Buggy123** [comment]
:+1: a much needed change that we've all been waiting for.

**Comment by Couls** [comment]
you know its a bad omen when the first person to comment on it is named "buggy"

**Comment by actioninja** [comment]
god dammit

**Comment by Buggy123** [comment]
Damn, this was a perfect pr. I blame :INSERT_HEADCODER_HERE:

**Comment by Couls** [comment]
ninjanomnom man bad.. doesn't roll off the tongue the same though

**Pull request closed without merging**
