### PR TITLE
Updated the Nanite Dermal Button icon set

### PR DESCRIPTION
**Pull request by MTandi**
## About The Pull Request

The PR replaces the standard set of Nanite icons (number, plus, minus, power) in different colors with an extended set of icons in a single color.

### New set
Icons

### Backgrounds
dreamseeker_u7cOHRwkOZ

## Why It's Good For The Game

The current icon set is very limited, the numbers don't provide much context and some colors are barely visible on certain UI backgrounds (yellow in particular).

The new set has bigger variety of icons, but removes the color selection option to improve icon visibility.

## Changelog
:cl:
tweak: Nanite Dermal Button icon set now contains more icons, but without color options
/:cl:

### CODE REVIEW

**Comment by tgstation-server** [comment]
You currently have a negative Fix/Feature pull request delta of -2. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

**Comment by coiax** [comment]
> You currently have a negative Fix/Feature pull request delta of -2. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

Your opinion has been noted and disregarded, automatic bot.

**Comment by coiax** [comment]
@XDTM Give me your blessing, oh exalted nanite one.

**Comment by XDTM** [comment]
this is _absolutely_ blessed

**Comment by CRITAWAKETS** [comment]
Dude just... Grayscale it. Infinite colors, infinite possibilities.

**Comment by maxymax13** [comment]
> 
> 
> Dude just... Grayscale it. Infinite colors, infinite possibilities.

yeah but it looks bad

**Review by Twaticus — APPROVED** [review]
looks good!

**Pull request merged**
