### PR TITLE
Lowered disappointed.ogg by 5 decibels

### PR DESCRIPTION
**Pull request by PKPenguin321**
Fixes https://github.com/tgstation/tgstation/issues/25216

### CODE REVIEW

**Comment by Yoshmaster** [comment]
lower it by all decibels

**Comment by Penguaro** [comment]
Oh thank you!

**Comment by WJohn** [comment]
Thank god.

**Comment by Penguaro** [comment]
Who knew that submitting an issue could result in a solution! LOL How many of us have cringed at that sound file but never did anything about it?

**Comment by calzilla1** [comment]
>LOL

Not many

**Pull request merged**
