### PR TITLE
Makes it clear that command reports are IC.

### LINKED ISSUE #33936: Create Command Report should be IC
After a discussion in the administrator forums, the pop-up text when you press the Create Command Report says "Please enter anything you want. Anything. Serious."

This has been giving new admin candidates the wrong impression, and should be updated to reflect the new policy.

I'd suggest "Enter a Command Report. Ensure it makes sense IC."

### PR DESCRIPTION
**Pull request by BeeSting12**
Closes #33936

Why: Those who have access to the admin forum will understand this. The tldr is that admins are using the report as an OOC announcement to banter with the crew, mock them for losing, or just shitpost on the round behind the veil of Centcomm when such comments should be saved for OOC post round. The text that I removed gave candidates the wrong impression- No, you cannot write literally anything. There are limits and at bare minimum it should be kept IC.

### CODE REVIEW

**Comment by BeeSting12** [comment]
yes im merging from master because i forgot to make a new branch

**Comment by kevinz000** [comment]
:+1:

**Comment by RandomMarine** [comment]
I feel as if admins that can't tell that text's tongue-in-cheek shouldn't be admins in the first place.

**Review by Cyberboss — APPROVED** [review]

**Comment by BeeSting12** [comment]
@RandomMarine You're not entirely wrong there but the text does contradict what we tell the admins candidates so I can see how they're confused.

**Comment by optimumtact** [comment]
Hey look here we are coding around the admins again what fun

**Comment by Iamgoofball** [comment]
@optimumtact wanna place bets on who gets stickybanned this time?

**Pull request merged**
