### PR TITLE
Removes Stickers for being in violation of Goonstation's license.

### PR DESCRIPTION
**Pull request by Iamgoofball**
## About The Pull Request

Removes Stickers for being in violation of Goonstation's license.

## Evidence of License Violation
Discord_eOHoyFIzMy
Discord_iDnjK9HWTd
Discord_QnC6cfx17R

## Why It's Good For The Game

We like not being in violation of licenses, @JohnFulpWillard and the maintainers determined stickers to have been stolen from goon. We either need to remove or get signoff from the following committers for a port:
- [ ] mybluecorners
- [ ] vuonojenmustaturska
- [ ] mordent-goonstation
- [ ] tarmunora
- [ ] pali6
- [ ] kyle2143
- [ ] adharainspace
- [ ] zewaka
- [ ] disturbherb
- [ ] imnotjames
- [ ] primenumb
- [ ] azrun
- [ ] sovexe
- [ ] frawhst
- [ ] tobleroneswordfish
- [ ] thetyrant25
- [ ] flamearrow57
- [ ] cheffiegithub
- [ ] myliedaniels
- [ ] lynnecubus
- [ ] zwrh3
- [ ] nefarious
- [ ] ilysen

## Changelog
:cl:
del: Removes Stickers for being in violation of Goonstation's license.
/:cl:

### CODE REVIEW

**Comment by Jacquerel** [comment]
this is a sad day, but hopefully a hero will rise and recode this essential feature from scratch

**Comment by necromanceranne** [comment]
Damn what a shame

**Comment by Jackal-boop** [comment]
GOON JOIN THE TIMES GO OPEN SOURCE RAAAAAAA

**Comment by Zytolg** [comment]
pixel_x
pixel_y
You're killing me here

**Comment by bigfatbananacyclops** [comment]
lol

**Comment by JohnFulpWillard** [comment]
Nvm I think pipebombs are good actually

**Comment by JohnFulpWillard** [comment]
Someone's working on stickers so I'm gonna see how that goes

**Pull request closed without merging**
