### PR TITLE
Properly reverts dual wielding

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
As an alternative to my other PR, but without undoing the code improvements that dorisdwarfs PR does

Close #13912

### CODE REVIEW

**Comment by KazeEspada** [comment]
:-1:  Dual Wielding needs tweaks not removal.

**Comment by KorPhaeron** [comment]
@KazeEspada 

I don't want to work seriously on it right now and its game breaking in the mean time

**Comment by KorPhaeron** [comment]
@duncathan

Either this one or #13949

**Comment by duncathan** [comment]
Remove don't improve

**Comment by duncathan** [comment]
This is dorsidwarf's PR it just removes slightly less
Any issues it may have had would already have been caught

**Comment by PKPenguin321** [comment]
well shit

**Comment by MMMiracles** [comment]
KIA

**Comment by Iamgoofball** [comment]
:-1:

will revert soon

**Comment by duncathan** [comment]
@iamgoofball
Just make it not quite as ridiculously overpowered

**Pull request merged**
