### PR TITLE
Revert "Power Cell explosions are now log"

### PR DESCRIPTION
**Pull request by vuonojenmustaturska**
yikes

### CODE REVIEW

**Comment by vuonojenmustaturska** [comment]
image
for context

**Comment by F-OS** [comment]
@Iamgoofball FIX

YOUR

SHIT

**Comment by 81Denton** [comment]
See #35035

**Comment by KorPhaeron** [comment]
golfball does it again

**Comment by Iamgoofball** [comment]
I must of done my math wrong

My bad dudes

**Comment by Iamgoofball** [comment]
Someone told me potato cells capped out at 20k

**Comment by Noahnoah55** [comment]
Just as I get my integrated circuits powercell bomb working. No fun allowed.

**Pull request merged**
