### PR TITLE
Add new surgery tgui that provides a built in body zone selector and doesn't let you start surgeries if their body is covered. Replaces some stuff with balloon alerts

### PR DESCRIPTION
**Pull request by Mothblocks**
## About The Pull Request

https://user-images.githubusercontent.com/35135081/151780540-c27bfe9f-ac84-42cf-99ce-4a35710d7eb8.mp4

Also splits asset files into their own folder because it was getting really ugly.

## Why It's Good For The Game
The body zone selector is one of the shittiest core parts of the game that doesn't have an easy removal. It's super finnicky to click on, and numpads do not come on every keyboard anymore (I bought an external numpad literally just for SS13). I would like to reduce its necessity significantly. This provides a very clean and easy to use interface for it, as well as making it easy for this to go on other tguis, if there is ever a need for that.

Using drapes on someone, not seeing the tiny chat message that their body is covered, and giving them a bleeding wound from the impending scalpel has gotten old and I'm sick of it. This prevents that from happening entirely, both with balloon alerts and fat disabled buttons.

## Changelog

:cl:
refactor: Replaced the old surgery interface with one that is much better to use, and lets you choose the body zone within itself.
/:cl:

### CODE REVIEW

**Comment by Mothblocks** [comment]
The fact that #61503 is still a bug makes me so sad

**Comment by LemonInTheDark** [comment]
I used to have a lot of trouble with the strip menu, I'm unironically a little worried about making the game too intensive for older systems. My frame of reference might be mildly fucked there though

**Comment by Mothblocks** [comment]
At some point u gotta let go man

**Comment by stylemistake** [comment]
I have shown you at some point a way to improve / compactify the strip UI.

image

Strip UI is used a lot, and as of now it blocks a lot of view. And with this one, it is still intuitively laid out, and has enough space for everything. (It might be better to swap belt with backpack slots in this variant.)

Pls consider. Also, great surgery UI, I like it.

**Review by stylemistake — APPROVED** [review]

**Comment by exymian** [comment]
Wow, jaw dropping !!!!! Its so good !!!

**Comment by joybod** [comment]
With this, gone will be the day of stabbing patients as a mediborg and having a law/policy panic

**Comment by SuperNovaa41** [comment]
This is really cool

**Comment by EricZilla** [comment]
Would love to see 'Expose Chest' button on the surgery menu so that doctors stop stealing my pants instead of adjusting the uniform

**Comment by Mothblocks** [comment]
image

**Comment by cacogen** [comment]
I wanted a TGUI Pathologic/Operation-like window which would be a dummy with organ slots similar to the strip menu only with layers over the slots to hint at which step came next (e.g. pink, incise; white, saw) but this is pretty cool too

**Comment by Mothblocks** [comment]
I think something you suggested actually inspired this idea cacogen and it was probably that

**Pull request merged**
