### PR TITLE
Adds new sounds to the circuit sound synthesizer

### PR DESCRIPTION
**Pull request by TheBonded**
## About The Pull Request
adds Lizard Scream, Moth Buzz, Toy Squeak, Xenomorph Hiss, Warp Whistle, Poster Rip, Coinflip, Flash, Flashbang, Laugh Track, Whip, Gavel, and Megaphone to the circuit sound synthesizer
please comment other sounds you want to see in this since its easy to add and gives more creativity to circuit makers

## Why It's Good For The Game
more creativity for circuit coders

## Changelog

:cl: Bondismyname but I wish it wasnt
qol: Circuit Sound Synthesizers have a few more options of sounds they can play
/:cl:

### CODE REVIEW

**Comment by TheBonded** [comment]
there are so many sounds im sure im missing that would be cool to add

**Comment by Colovorat** [comment]
Flashbang sound?

**Comment by moocowswag** [comment]
The sound that plays when a cultist uses blood beam or when there is a "massive bluespace anomaly?" that teleports a bunch of syndie simple mobs to the station.

**Comment by TheBonded** [comment]
> The sound that plays when a cultist uses blood beam or when there is a "massive bluespace anomaly?" that teleports a bunch of syndie simple mobs to the station.
> 
> Or the sound that plays when a tesloose moves around.

too late it seems, though i wouldnt want to add long sounds because of their spammability

**Pull request merged**
