### PR TITLE
Fixes the other missing / in reactions.

### PR DESCRIPTION
**Pull request by Pickle-Coding**
Style

## About The Pull Request
Goof only fixed one. This PR fixes the others.

## Why It's Good For The Game
To read.

### CODE REVIEW

**Comment by Pickle-Coding** [comment]
I should've just suggested the changes in the goof PR so I guess GBP no update.

**Comment by TheBonded** [comment]
> I should've just suggested the changes in the goof PR so I guess GBP no update.

dont need the no GBP update since there is no changelog and thus no labels on this pr

**Comment by LemonInTheDark** [comment]
why leave the changelog if you're not gonna use it?

**Review by LemonInTheDark — APPROVED** [review]

**Comment by LemonInTheDark** [comment]
> > I should've just suggested the changes in the goof PR so I guess GBP no update.
> 
> dont need the no GBP update since there is no changelog and thus no labels on this pr

~~you sure you wanna add labels?~~

**Comment by Pickle-Coding** [comment]
I didn't think about removing it, but now I did.

**Comment by Pickle-Coding** [comment]
Fixing merge conflicts on mobile is pain.

**Pull request merged**
