### PR TITLE
Summer Thaw Patch

### LINKED ISSUE #10070: Stocking Drone dispensers with metal and glass doesn't use the metal, nor care about how much you have.
To reproduce:
Spawn drone dispenser
Spawn i metal and 1 glass sheet
Use a sheet on the fab, and type 50
It will add 50 sheets of metal worth to the dispenser, and you'll still have the 1 glass sheet
Repeat infinitely.

### LINKED ISSUE #10071: Drone dispenser cooldown cannot be modified
The dispenser cooldown is hardcoded rather than a var. This inconsistent with almost every other thing that has a cooldown, and makes it so the cooldown time between drones is impossible to modify.

### PR DESCRIPTION
**Pull request by ghost**
This PR fixes a lot of the issues that came with the Summer Thaw. Full changes can be found below.
- Preloaded drone dispensers have been added to MetaStation (beneath CE office) and Boxstation (Old incinerator).
- Drone dispensers can now be broken and must be repaired. Variables have been added so admins can change dispensers to make different things, be more efficient, or have less of a cooldown time.
- Airlock charges will now properly damage the station.
- Fixes #10071 
- Fixes #10070 

_Box_
**No screenshot available!**

_Meta_

### CODE REVIEW

**Comment by pudl** [comment]
screenshot

**Comment by Xhuis** [comment]
dream maker screenshots coming soon get h y p e

**Comment by pudl** [comment]
you should put those in maintenance, that way they dont get in the way/involve removing tables. they'll probably really easily fit in some random hallway.

**Comment by Xhuis** [comment]
I was considering making their own room. Not putting them in maintenance, though.

**Comment by WJohn** [comment]
Fixes #10071 then?

What about #10070?

**Comment by SconesC** [comment]
Looks so out of place on Box engineering

**Comment by Xhuis** [comment]
where do you feel like it should go

**Comment by SconesC** [comment]
Nowhere because drones are fucking disgusting resource gypsies that contribute nothing of value to the station

But in actuality, probably somewhere that isn't congesting a hallway? Put them in Maint or Misc Sci or something.

**Comment by pudl** [comment]
I'm pretty sure a lot of people can agree that maintenance is a fine place to put the spawners.

**Comment by Xhuis** [comment]
Boxstation drone dispenser was moved into the old incinerator. I like the spot in Meta currently.

**Comment by pudl** [comment]
@Xhuis the spot in meta removes tables, and it's in the lobby. It should be moved to maintenance.

**Comment by xxalpha** [comment]
@Xhuis kun

You could use the mineral container datum for this.

**Comment by Xhuis** [comment]
Closing for now because I can't be bothered to fix conflicts. Will work on this in a few days

**Pull request closed without merging**
