### PR TITLE
[WIP]Adds KIDNAP objectives!

### PR DESCRIPTION
**Pull request by silicons**
Adds a kidnap objective:
The person with it will start with a special syndicate bluespace body bag at roundstart. Identical to normal bluespace body bags, except for two things and the sprite.
Their objective is to have the person they're after alive, and for the most part, intact, in some form of storage on their person.
The syndicate body bag can only hold one mob.
The special syndicate body bag can not be resisted out of as long as it's kept moving (So no stuffing your target in naked and keeping them in maint!)
They have red sprites. Yes, they're codersprites. Yes, they suck shit. Yes, someone please get me new ones!
Note: If the person with the objective loses their bag, it isn't over for them, they just have to find another way of storing the mob in their mob! So, better go to science and raid them for bluespace body bags!
-Replaces all return 1/0 with TRUE/FALSE defines in the files I touched.

WIP stuff:
-The person inside being able to talk might be an issue for the traitor holding them
-If I make the person inside mute, it's no fun being in a bag for possibly the entire round. If the traitor knocks them out indefinitely with N2O air tank, it's still no fun being in a bag for possibly the entire round.
-Hopefully I'll add a way for the victim to communicate with whoever's holding them, or atleast give them something to do other than be a brain that you can't ghost out of freely.
------------MAKE IT WORK

### CODE REVIEW

**Comment by FantasticFwoosh** [comment]
> Most certainly you are going to be in the bag the entire round and people will either ignore this objective to murder-bone or forget to do it until the shuttle is called.

**Comment by adamkad1** [comment]
so you need to stuff em in the bag and then what? pick em up or something?

**Comment by kevinz000** [comment]
@adamkad1 Yes
@FantasticFwoosh Yes, it'll be a problem, but there's still cases where the traitor just outright REMOVES YOU FROM THE ROUND PERMANENTLY, so this is not one of my huge worries. I'll try to make it not as lame as to "You're out forever once you're in the bag if they feel like making you out forever", but traitors can be as murderboney as they want and remove people from the round instantly if they want, and this isn't nearly as bad as the other methods.

**Comment by Nilons** [comment]
Wouldnt this be a little unfun for the person in the bag?  The argument could be made its no less fun than being killed but when you get cremated by a traitor you can just get up go grab some food and wait for the next round, but with this youd have to stay there and wait to see if you get a chance to slip out for the whole round.

**Comment by jughu** [comment]
Make the bag highly flammable

**Comment by kevinz000** [comment]
@jughu thanks I forgot to make it fire-proof as per syndicate objectives
@Nilons I'm doing something to make it less boring.

**Comment by jughu** [comment]
>not making a whole rave room inside. It auctally is bigger inside then you van see outside

**Comment by Nilons** [comment]
@kevinz000 @jughu This is a good idea, if it was like a small room with a bunch of shit to do inside it so youre not just passed out that would be really cool actually.

**Comment by FantasticFwoosh** [comment]
Wouldn't this actually pre-date the inclusion of VR that's in the works/planned already? It's just a  inescapable VR pocket universe bag that can only be escaped from the inside when it is opened.

**Comment by jughu** [comment]
virtual reality bluespace bodybag

**Comment by RemieRichards** [comment]
@FantasticFwoosh it doesn't pre-date VR, it's been in for ages, just not mapped for use.

**Comment by PKPenguin321** [comment]
But what if your target suicides or spaces themselves or both

**Comment by Nilons** [comment]
@PKPenguin321 this could either be a good position for roleplay (If you be cool and let me kidnap you ill give you a double esword when we're off the shuttle) or a memestrat for denying greentext, he could make it so that if your target suicides you still get the greentext.  Or make it ahelpable not so that the other person can be punished but so that you can get a new target (in the event of hopline suicide)

**Comment by kevinz000** [comment]
@PKPenguin321 debrain objective suffers from that too. hmmmmmm maybe I should make it so if someone's suicided they count as kidnapped, but yeah, I'll have to think this over, because killing or getting rid of someone or something in ss13 is way harder than capturing that item or person alive and intact :/

**Comment by jughu** [comment]
Just make it so if they suicide in a bodybag their ghost bluespaces out so they are just catanonic

**Comment by PKPenguin321** [comment]
Debrain only had issues with spacing/gibbing not suicide which you can do literally as soon as the round starts

**Comment by octareenroon91** [comment]
@LanCartwright Got an exfil scenario for you

**Comment by LanCartwright** [comment]
shoot

**Comment by bgobandit** [comment]
don't ninjas' energy nets or whatever have this already

**Comment by blobbernaut** [comment]
No. Might as well be cremated honestly.

The bag, I like. Add it as a traitor item for, say, 7tc?

**Comment by kevinz000** [comment]
@blobbernaut explain. again if this is about the "Guy gets removed from round" I'm doing something for that to let them still semi-interact while they're in the bag.

**Comment by PKPenguin321** [comment]
Instead of kidnapping a specific target how about having to kidnap some number of people, like 2 or 3

**Comment by octareenroon91** [comment]
>Instead of kidnapping a specific target how about having to kidnap some number of people, like 2 or 3
Near-direct ninja clone then.

Anyhow, Syndie Fulton for kidnap maybe.

**Comment by ExcessiveUseOfCobblestone** [comment]
>objective where you do the equivalent to welderlocking someone the entire round

hmmm

>Wouldnt this be a little unfun for the person in the bag? The argument could be made its no less fun than being killed but when you get cremated by a traitor you can just get up go grab some food and wait for the next round, but with this youd have to stay there and wait to see if you get a chance to slip out for the whole round.

>Edit: this seems akin to n2o internals, which Ive seen regarded as worse than killing someone. I like the idea overall but I think there could be some idea workshopping done

Yes being indefinitely stunned is not fun, just kill them please.

**Comment by kevinz000** [comment]
several ideas
| The person inside will already be able to see outside due to how container code works
- Let the person inside talk to the person holding the bag
- Make the person inside unstunnable while inside so no N2O spamming
- Make the person inside always able to resist, so if you try to cuff them and throw them in a corner it won't work.
- Let the person inside ghost out if they wish to instead of doing the above/just being able to watch. I know you'll say they'll metagame, but the players who metagame with it when it's meant to make you less bored can eat a ban
- If your target suicides you win
- If your target ghosts you win

**Comment by tortellinitony** [comment]
I think this is a kind of silly idea, but you could maybe add something like have them restrained and in your sight.

**Comment by ExcessiveUseOfCobblestone** [comment]
Having the equivalent to handcuffs on with someone constantly moving you [because greentext] doesn't seem that much fun either, and this has the same mental trap that N2O internals does where you sit there indefinitely instead of ghost/suicide because of some hope that someone will save you, although it will prevent sore losers using it to deny greentext so +1 for that I guess.

**Comment by TehZombehz** [comment]
Why do we hate new things?

**Comment by Grazyn** [comment]
Being the equivalent of a MMI stuck in a backpack for the whole round is more boring than being dead, more so if you can't even talk/can only talk to the person carrying you. I'm quite sure players in that situation would rather be dead so they can at least observe and talk in deadchat and roll for ghost roles. Banning them if they ghost is silly, but if you make ghosting an auto-win for the traitor, traitors will find a way to put their target in a situation were they are forced to ghost out of boredom.

**Comment by FantasticFwoosh** [comment]
I still think my shrink ray & jar solution was funnier & more inclusive than this Kev. Yours relies on the person being stuck in the bag full bodied or otherwise occupied while still playing or being bored.

> Not to say people will use the bag to hold other things for entirely different meta purposes, such as a infinite bag full of the armory or all the people they have murder-boned before mass incinerating them, the bag could also be destroyed then you cannot get your objective.

Meanwhile my jar version on paper at-least would make them ghost out & act like a MMI/Intellicard without actually damaging their physical state, since the jar is a item the update to the jar in having the said target person inside it is all you need to greentext regardless of logged in/out state. Theres no necessity to have the full bodied person dragged around against their will without the option to ghost out & then pop back in again.

**Comment by kevinz000** [comment]
So, would this be better if it was changed to allow kidnapping by dragging and handcuffing them or some other method (The bag method would remain but they wouldn't start with the special bag.)? That DOES make more sense, bluespace magiks is more of a NT thing :/

**Comment by octareenroon91** [comment]
Red-and-black locking bodybag, with a comically large padlock?

**Comment by Armhulen** [comment]
I think it should be not resistable while held on a person, not while moving.

**Comment by lzimann** [comment]
are you finishing this

**Comment by kevinz000** [comment]
not until i get something that actually is a good idea

**Pull request closed without merging**
