### PR TITLE
Removes Tesla Revolver from RnD weapon designs

### PR DESCRIPTION
**Pull request by praisenarsie**
i'm actually making @kevinz000 angry and i have no idea why i did this pr anyway even though he explained why i shouldn't

teslavolver is like one of the worst rnd designs plus i've seen nobody use it. if you can provide enough justification to not remove this weapon, then speak you science powergamers. 

_also i hate rnd_

:cl: Frozenguy5
del: Tesla Revolver has been removed from RnD weapon designs.
/:cl:

### CODE REVIEW

**Comment by vuonojenmustaturska** [comment]
I've actually seen tesla revolver once. I made it, gave it to a sec officer with a firing pin and shuttle was called because "tesloose"

**Comment by KorPhaeron** [comment]
Please wait until the techweb is done to add or remove designs, we need the bloat right now to fill out the tree

**Comment by kevinz000** [comment]
why would I be angry though it'll be a design on a node silly!

**Review by Cyberboss — APPROVED** [review]

**Comment by Cyberboss** [comment]
Needs changelog

**Comment by GuyonBroadway** [comment]
The tesla revolver is rather powerful in the right hands, great at murdrizing crowds and a damn sight more interesting that the old stun revolver which was just "hurr durr R&D can now print tasers!"

**Comment by praisenarsie** [comment]
added changeloggu

**Comment by YakumoChen** [comment]
>crazy experimental gun that shoots bolts of wildly pathing electricity that can backfire on the user if used wrong

>printed as part of experimental research

>"it's shit pls remove"

**Comment by YakumoChen** [comment]
tesla revolver is a niche weapon that can be used to stun and damage crowds of people but it not very useful in 1 on 1 combat (the tesla bolt only works if it hits someone). It can also backfire and shock you if you don't have proper protection (like insulated gloves, notably).

It has good uses and it's cheaper to build then an advanced energy gun, an arguably superior weapon (which has a higher tech requirement anyway) so there's plenty of reasons not to axe it.

**Comment by kevinz000** [comment]
why do people always want to remove things they personally don't use hm

**Comment by KorPhaeron** [comment]
its been 14 hours which is kind of like 24

**Comment by The-clown-known-as-Pepe** [comment]
24 HOUR RULE

**Pull request closed without merging**
