### PR TITLE
Adds a bottle of sugar to the roundstart contents of the Virology smartfridge(s)

### PR DESCRIPTION
**Pull request by ATH1909**
## About The Pull Request

This PR adds a bottle of sugar to the roundstart contents of the Virology smartfridge(s), so that virologists won't have to beg chemists for a basic chemical (sugar) in order to make sucrose agar.

## Why It's Good For The Game

At roundstart, Virology has the chems needed to make every non-uranium-based virology chemical... except for sucrose agar, making it much harder/more time consuming (for a virologist) to make than the virology chems that are supposed to be of a higher chem tier than it. This PR fixes that inconsistency/annoyance.

## Changelog
:cl: ATHATH
add: A bottle of sugar has been added to the roundstart contents of the Virology smartfridge(s).
/:cl:

### CODE REVIEW

**Comment by necromanceranne** [comment]
Can't you just grind up sugary snacks from the vendor?

**Comment by Angustmeta** [comment]
Or use saline-glucose from vendor

**Comment by Krysonism** [comment]
Resource bloat

**Comment by Tlaltecuhtli** [comment]
the vendor already has most chem expect this one either have all (not mineral) or have none

**Comment by Krysonism** [comment]
>the vendor already has most chem expect this one either have all (not mineral) or have none

We don't have to make the problem worse. Virology is already a isolated fortress, anything that makes the viro go outside is good.

**Comment by OverlyGeneric** [comment]
> We don't have to make the problem worse. Virology is already an isolated fortress, anything that makes the viro go outside is good.

But isn't that the point of virology?

It's literally meant to be isolated because of the risk of spreading diseases to the station and promptly getting lynched because of you accidentally not washing your hands or forgetting to have your oxygen tank on when handling the monkeys.

**Comment by Farquaar** [comment]
Sucrose is a basic reagent for microbiologists. The idea that a virologist shouldn't start with a small bottle is like saying that engineering shouldn't start with metal.

**Comment by 81Denton** [comment]
Not including sugar really looks like an oversight. If virology was intended to be timegated by restricting available starter resources, the fridge would either have no chemicals or the plasma bottle would be missing instead.

**Comment by zeskorion** [comment]
the joke here is that level 4 symptoms suck so much ass this is unecessary

**Comment by 81Denton** [comment]
the real joke is that some guy from beestation keeps necro posting on 3 month old PRs

**Pull request merged**
