### PR TITLE
[READY] decorations loot crate!  +3 new fancy carpets!

### PR DESCRIPTION
**Pull request by Krysonism**
## About The Pull Request
This PR adds a new crate containing random decorative tiles, objects and the like to the maintenance loot site pool.
Some of the possible contents are three new types of carpet.

The all blue stellar carpet,
The gold and blue NT executive carpet,
and finally the orange and grey donk co promotional carpet.

image
image
image

## Why It's Good For The Game

My favourite part of engineering is decorating and renovating areas of the station. This PR adds a randomized pool of decorative items to  help facilitate this in a way that also ties into my efforts to improve maintenance loot and trade.

## Changelog
:cl:
add: Added 3 new types of fancy carpets.
add: A crate of decorative items now sometimes spawns in maintenance.
/:cl:

### CODE REVIEW

**Comment by spessbro** [comment]
[joke about star of david carpet]
wouldn't it make some sense for the donk pocket carpet to be craftable using a donk pocket cause it looks great

**Comment by Capsandi** [comment]
You should probably place these in the regular maints loot table instead of a separate loot table. That way, when new maps such as kilo are added, there won't be a chance of the loot crate drop and these carpets being overlooked and never being present.
These carpets look amazing.

**Comment by Farquaar** [comment]
Interesting how the design changes in the centre of the carpet. How do non-rectangular and L-shaped carpets look?

**Review by Twaticus — APPROVED** [review]
hell yeah

**Comment by Krysonism** [comment]
> Interesting how the design changes in the centre of the carpet. How do non-rectangular and L-shaped carpets look?

I can post a picture of that when I get home. The "big" designs only appear when all 4 corners are fill(when the tile is surrounded by tiles that it smooths with)

**Pull request merged**
