### PR TITLE
Battery acid pie

### PR DESCRIPTION
**Pull request by L0pz**
## About The Pull Request

I added a battery acid pie you make with 2 batteries and one plain pie

image

## Why It's Good For The Game

The game had a very noticeable and substantial lack of battery acid pies (plus I wanted there to be more dishes for ethereals)

edit: sorry I couldn't figure out how to add labels

## Changelog
🆑 
add: Added the battery acid pie
/:cl:

### CODE REVIEW

**Comment by DrDiasyl** [comment]
Potassium

**Review by Wallemations — APPROVED** [review]
Yummy

**Comment by L0pz** [comment]
> Your CL needs the opening and closing tags, otherwise It won't work

Oh I dunno what that is but I tested it in game and everything seemed to work perfectly

**Comment by mc-oofert** [comment]
> > Your CL needs the opening and closing tags, otherwise It won't work
> 
> Oh I dunno what that is but I tested it in game and everything seemed to work perfectly

the changelog

**Comment by L0pz** [comment]
> > > Your CL needs the opening and closing tags, otherwise It won't work
> > 
> > 
> > Oh I dunno what that is but I tested it in game and everything seemed to work perfectly
> 
> the changelog

oh lol

**Pull request merged**
