### PR TITLE
Hopefully adds enough security officer spawns that #19757 will never happen again

### LINKED ISSUE #19757: Sec spawned in mining dock?
image

### PR DESCRIPTION
**Pull request by ChangelingRain**
This is 15, count em, 15, security spawn points for dream, efficiency, meta, and box, because under normal circumstances we should never have more than 150 players.
Fixes #19757 at least hopefully send help
Also fixes the mining shuttle corners on efficiency, which I missed before.

### CODE REVIEW

**Comment by Bawhoppen** [comment]
our record for plays is like 140 isnt it

**Comment by PKPenguin321** [comment]
or just make them start spawning on top of each other in extreme cases. like how assistants did back when they spawned in tool storage.

**Comment by KorPhaeron** [comment]
can we put assistants back in tool storage yet

**Comment by PKPenguin321** [comment]
i'd be down

**Comment by Davdichan** [comment]
But mah greytide stationwide

**Comment by optimumtact** [comment]
Where are assistants currently spawning?

**Comment by Jordie0608** [comment]
Scattered around the map in public areas.

**Comment by Davdichan** [comment]
New antag type: Assistant mob. All assistants spawn on a single tile. Health is pooled into a single mob, and it's a 'twitch plays pokemon' theme for movement, but each individual user can attack or grab items  and maintains their own inventory. Late join assistants are automatically added to the mob, and corpses dragged into the mob also become merged and another set of hands.

**Pull request merged**
