### PR TITLE
rebalances armor values in the new MODsuits

### PR DESCRIPTION
**Pull request by azrael-x86**
## About The Pull Request

(reupload due to freeze)

literally, what is the use of having a quite frankly bulky space suit, that doesn't allow you to put on any other armor (besides, you know, that extra shielding that can't be printed)? feel free to mess with some of the armor values here, i only nerfed the melee values slightly to prevent it from being too terribly gamey. also, why is the wizard modsuit the only one with armor and laser protection (besides the admin suits?) 

## Why It's Good For The Game

when you have a bulky ass suit that defends you from literally no bullets or lasers (cough cough what security and command's job is full of), then what is the incentive to wear it over say a riot suit? old hardsuits had good armor. bring it back.

## Changelog

:cl:
balance: rebalanced MODsuit armor values
/:cl:

### CODE REVIEW

**Comment by JohnFulpWillard** [comment]
MODsuits dont have armor because they arent meant to be suits that do literally everything with all benefit no consequence
Nukie MODsuits have a module that gives armor at the cost of space protection
Wizards have it because theyre Wizards

**Comment by magatsuchi** [comment]
atmos protection + armor is not an unknown combination. just because i get an extra flashlight or jetpack module doesnt mean i should have to sacrifice my ability to not die from 3 bullets, what seccie or cap in their right mind would wear a modsuit instead of actual armor? this is a very popular complaint.

**Comment by magatsuchi** [comment]
side note: if it does not have the full armor capabilities of a hardsuit, it should atleast have a fraction of it.

**Comment by JohnFulpWillard** [comment]
Who is the one complaining about this, exactly? Most people I've spoken to in the coding channels have said this was more than a fair tradeoff.

**Comment by capsaicinz** [comment]
instead of pairing the two- that being complete space protection AND armor- i'd stay true to the MODsuit design and rather create a station version of the armor booster for the captain and security suits. slap them in the armory and captain locker or something, that way you still have to trade armor for space protection on deployment.

**Comment by magatsuchi** [comment]
i second @capsaicinz

**Comment by magatsuchi** [comment]
(at the bare minimum: also they complain on game, where else? of course other coders are receptive)

**Comment by Pickle-Coding** [comment]
Anyone who would want to go to space or live in an uninhabitable area would want a modsuit. They should not be better than riot suits or whatever in every way possible, otherwise why would someone want a riot suit?

**Comment by magatsuchi** [comment]
> 

hardsuits could do both with no complaints, its viable having them have not as much armor, but no armor is ridiculous.

**Comment by thgvr** [comment]
Swat suit is currently a better modsuit, and only needs a red slime potion so I agree

**Comment by moocowswag** [comment]
sec modsuit should have its insulation taken off of it and be replaced with at least some small amount of armor or some sort of special compatibility (with special armor modules?) that other build-able modsuits dont.

**Comment by optimumtact** [comment]
negative gbp and ignoring a design document without discussing it with relevant parties first.

closing in 24 hours

**Comment by magatsuchi** [comment]
> negative gbp and ignoring a design document without discussing it with relevant parties first.
> 
> closing in 24 hours

cringe

**Comment by Jackraxxus** [comment]
PRing from your master is bad practice, apparently.

**Comment by realthomas69** [comment]
> Who is the one complaining about this, exactly? Most people I've spoken to in the coding channels have said this was more than a fair tradeoff.

Its not a fair tradeoff, getting a quirky grappling hook or clamp or whatever isnt worth the tradeoff of being instant owned by like any antagonist weapon

**Comment by cacogen** [comment]
If armour needs to be a module for it to be balanced, then why isn't there just an armour module already on the suits with the same armour as the hardsuits they're replacing? Is it because it doesn't actually have anything to do with balance?

**Comment by Suspect-One** [comment]
I don't understand original armor values because it feels like they were chosen randomly. Say, previously we had a atmos hardsuit which was one of the hardsuits which actually gave you 100 fire resistance. Now fire resistance don't matter at all because almost every single MODsuit now has it. 

Besides, if you didn't want to make MODsuits all powerful and all then why did you make a PR which disables their slowdown then they are not deployed? Doesn't that make MODsuits basically a free hardsuit and a backpack with a lot of modules (most of them are not that useful) which you can activate at any given time? Isn't that OP? 

I'd rather trade that slowdown for some decent armor (just grab the values from old hardsuits and nerf them a little).

**Comment by SoreYew** [comment]
The only valid group of people to even have armor on their suits are sec/cap, both of which have no slowdown and robust armor anyway. If you want to be spaceproof you need to make a tradeoff. Nobody took the Captains carapace, Body armor, or the armored greatcoat. Hell, store them in your modsuit storage when you have to eva if you truly must carry every tool at once.

**Comment by Dorsisdwarf** [comment]
> The only valid group of people to even have armor on their suits are sec/cap, both of which have no slowdown and robust armor anyway. If you want to be spaceproof you need to make a tradeoff. Nobody took the Captains carapace, Body armor, or the armored greatcoat. Hell, store them in your modsuit storage when you have to eva if you truly must carry every tool at once.

good news, neither of those jobs have any armour on their modsuits. the security jumpsuit has more armour than the 2 suits the sec team is forced to share to fight all adversaries in depressurised conditions.

**Comment by Amrabol** [comment]
Why are you even trying to add armor to syndicate and elite modsuits? They have build-in module that gives them armor. Why do they need something that it's just a duplicate

**Pull request closed without merging**
