### PR TITLE
Pauses space drift during explosions

### PR DESCRIPTION
**Pull request by yoyobatty**
## About The Pull Request
What it says on the tin. I noticed during large explosions, items get thrown and a hole of space appears and items will space drift through them which can result in severe lag sometimes or sometimes awkwardness especially when objects drift into a queued explosion.

## Why It's Good For The Game
Hopefully reduces some explosion lag and cleans up awkwardness/unrealism of explosions?

### CODE REVIEW

**Comment by ninjanomnom** [comment]
Disabling a subsystem everywhere when a particular event happens seems a poor plan. 

Making space drift for things affected by the explosion only activate once the explosion is finished processing seems reasonable but then you get to some weird cases where it moves from other interactions before the drifting has begun.

I'm not a fan of this change. It makes the code more bug prone in many areas beyond just explosions and reduces the overall stability of the game to get some minor[1] performance improvements for a single aspect.

[1] Needs profiling

**Comment by yoyobatty** [comment]
Never thought about that, I did enjoy your rationale. I'm fiddling with ideas to make explosions work smoother and be less buggy overall

**Comment by Whoneedspacee** [comment]
probably would be better to address the post-explosion lag aka space atmos lag

yes i know how unreasonably hard that is but damn space leaks specifically make the server chug, if space was snowflaked somehow to just remove gas it’d probably be massively more efficient than just thousands of tiles sharing gas forever because they don’t leak fast enough.

**Comment by yoyobatty** [comment]
Right and space uses an immutable mixture so what if we just made it so space had zero air and adjacent plating and tiles just literally removed gas if next to a space tile at the rate at which it currently does? Literally just making the gas go nowhere aka into space.

**Comment by Whoneedspacee** [comment]
it can’t just be adjacent, it practically does that already with its basically nonexistant pressure

the problem is, it needs to be different than the current atmos system

so once the adjacent tiles have their gas removed, half of the gas of the ones adjacent to those is going to move in at best, so now those are at 75%, then the next at 87.5, etc.

once you reach the end of the chain like a long hallway for example, you realize that each process of atmos you’re removing 0.001% or whatever of the final one, which means it might take you hours to clear out the entire hallway, while each tile in the hallway is actively processing atmos the entire time, causing massive lag.

there needs to be some kind of high pressure system in atmos for faster movement / equalization, or space needs to effectively have tile pathing that pseudo manage atmos while still removing a constant amount of gas.

**Comment by cacogen** [comment]
yoyo are you still on hippie

**Comment by yoyobatty** [comment]
Yes sir, I just like talking to TG coders because they  all know how stuff like this works. It points me in the right direction.

**Comment by ninjanomnom** [comment]
I'm very against the concept of this change and don't think it's worth the trade. Do keep trying to reduce explosion lag though.

**Pull request closed without merging**
