### PR TITLE
[Boxstation Edit] Department Management Console

### PR DESCRIPTION
**Pull request by Ikarrus**
screenshot 2015-06-13 12 50 12
Originally conceived to manage department-specific budgets that can be used to buy things from cargo without their approval. But now it's just a limited ID console, but available in every Command Staffer's office. If I ever actually make department budgets I'll use this console for that.
- Can only modify access to their own department, regardless of what ID is used to log in
- Any department head can use these to promote/demote those in their department, including those who have access that you clearly do not remember authorizing
- Can be modified to change the access of other departments by using a multitool on the circuit board.

Crossed fingers for conflict-free merging.

### CODE REVIEW

**Comment by xxalpha** [comment]
Nice.

**Comment by Falamazeer** [comment]
very nice

**Comment by GunHog** [comment]
I have been asking for this for the LONGEST time! :+1:

**Comment by duncathan** [comment]
What's it look like in the other offices?

**Comment by Ikarrus** [comment]
>What's it look like in the other offices?
others

**Comment by Incoming5643** [comment]
There's an irrational sadness seeing that dollop of blue in the overwhelming redness of the HoS's office

**Comment by Dorsisdwarf** [comment]
Can you make it attatched to the wall?

**Comment by GunHog** [comment]
I did not even notice that all the office computers had a theme going. Wow.

**Comment by CorruptComputer** [comment]
I agree with @Dorsisdwarf something that was attached to the wall would be better.

**Comment by Ikarrus** [comment]
Then you wouldn't be able to construct them or modify their settings.

**Comment by CorruptComputer** [comment]
Why not? You just need to make a new computer type "Wall Mounted".

**Comment by Ikarrus** [comment]
You're leaving a lot of details out.

**Comment by CorruptComputer** [comment]
Not really, new computer type, get a sprite, make it use the same interface as these. I don't really see a problem here.

**Comment by Ikarrus** [comment]
Can't be assed. If you want to do it after the fact I invite you to do so.

I'm pretty sure one of the factors here is to make it visible, too, and not just hide it on the wall.

**Comment by CorruptComputer** [comment]
It would be placed like APC's, use a dir to see which way its going to go. And I don't know what you mean by "hide it on the wall".

**Comment by freerealestate** [comment]
I don't know about you, but I tend not to notice what's on the walls most of the time.

**Comment by Miauw62** [comment]
making them placed like APCs would require writing snowflake construction code instead of the standardized computer code we have now.

**Comment by Kromgar** [comment]
It would be nice to get custom sprites that match the themes of each department. So research keeps purple, sec is red, and engi gets light blue.

**Comment by hanshansenhansson** [comment]
Make the screen wall-black with hints of table-grey, fits in all themes.

**Comment by phil235** [comment]
:+1:

**Comment by Ikarrus** [comment]
Everyone looks like they're in agreement, Phil.

Could I ask you to review and merge this to avoid any map conflicts?

**Pull request merged**
