### PR TITLE
Bags no longer hide stacks when one instance is deleted

### LINKED ISSUE #21929: Bio bag visual bug
Bio bag contains multiple of a type of slime core, open bag, inject core, reaction occurs, bio bag now says there's none of those cores in there. Hit smartfridge with bio bag, the missing cores reappear.

Probably similar occurences with similar bags, but not sure where it'd happen.
Low priority.

### PR DESCRIPTION
**Pull request by Arianya**
:cl: Arianya
fix: Fixed a UI issue when bags had stacked items deleted out of them. Many thanks to Duke for help!
/:cl:

Fixes #21929 
Major credit to @XDTM who did the majority of the work and helped me break through my own lack of understanding of the relevant code!

### CODE REVIEW

**Comment by RemieRichards** [comment]
this only fixes it for slime cores, which yes, may be the only case to trigger the bug.
but I believe a true fix would be in the bag's RemoveFromStorage proc.

**Comment by Arianya** [comment]
@RemieRichards Admittedly I'm not very good at coding, but I don't see how removefromstorage can anticipate people calling qdel on an object.

**Comment by RemieRichards** [comment]
@Arianya yeah it's somewhere deep in the code iirc.
It'll be *something like* an object's ```Destroy()``` checking if it's location is a storage object, and if it is, it's ```loc.RemoveFromStorage(src)``` so that that location *knows* it's lost an object.

so rather, it doesn't anticipate, but is told.

**Comment by XDTM** [comment]
did i just fucking debug for two hours to miss such an easy solution

**Comment by XDTM** [comment]
i take it back it is definitely not fucking easy

**Comment by ChangelingRain** [comment]
I swear there's a proc specifically for this

**Comment by RemieRichards** [comment]
yes, it's RemoveFromStorage

**Comment by XDTM** [comment]
nevermind i found the issue

**Comment by XDTM** [comment]
also RemoveFromStorage wants a loc to move the item to, it's not for deletion i think

**Comment by XDTM** [comment]
does anyone know how to make something happen AFTER Destroy, instead of before? spawn() works but i feel like it's bad

**Comment by RemieRichards** [comment]
it doesn't matter where it's going, it's being deleted.
what matters is the storage item is told of the deletion.

**Comment by XDTM** [comment]
That's not the issue, although i've been calling orient2hud and show_to directly. The issue is that this happens before the item is deleted if i put it on Destroy, making it pointless. Is using a spawn(1) acceptable in this case or is there another solution?

**Comment by RemieRichards** [comment]
Actually we have ```handle_atom_del```, which handles when something inside it is deleted, just add an override of this for storage objects that calls ```remove_from_storage```

3 lines total
```
/obj/item/whatever/path/to/storage/handle_atom_del(atom/A)
    ..()
    remove_from_storage(A)
```

**Comment by Supermichael777** [comment]
can you also fix picking up stacks from inventory not properly calling their removal the gaps annoy me?

**Comment by XDTM** [comment]
The issue is now fixed in a more generic way in #22022

**Comment by Arianya** [comment]
As per XDTM, since a cleaner, general solution exists, closing this one. :+1:

**Pull request closed without merging**
