### PR TITLE
[BALANCE] Removes NoDrop Implants From Nuke Ops

### PR DESCRIPTION
**Pull request by Steelpoint**
This PR removes the Nuke Ops ability to buy the nodrop implant.

Feedback discussion on forum: https://tgstation13.org/phpBB/viewtopic.php?f=10&t=4202

After witnessing several in game rounds, as well as testimony's from players, the nodrop implant is simply too powerful a item for the ops to have. It means the only reasonable way you can kill a op is through a bomb of thrown spears if they are wielding a eshield.

### CODE REVIEW

**Comment by Steelpoint** [comment]
Someone else did one just as I did mine. Whoops.

**Comment by Steelpoint** [comment]
Re opened due to other PR being reverted due to a technicality.

**Comment by Steelpoint** [comment]
I'll fix merge conflicts when I get home.

**Comment by xxalpha** [comment]
Get on coderbus.

**Comment by Steelpoint** [comment]
Merge conflicts fixed.

**Comment by Anonus** [comment]
Zero files, zero lines changed. We can merge this.

**Comment by Steelpoint** [comment]
Ehhh this is what happens when I reopen a long closed PR.

**Comment by Aranclanos** [comment]
uhhh what is going on here 
where are the files
WHERE ARE THE FILES

**Comment by Steelpoint** [comment]
I'll fix it tomorrow. Promise.

**Comment by duncathan** [comment]
Well this is certainly a PR few can disagree with

**Comment by Steelpoint** [comment]
Appears the antidrop implant was already removed, so eh.

**Pull request closed without merging**
