### PR TITLE
Roasts (Now without plates)

### PR DESCRIPTION
**Pull request by xXPawnStarrXx**
## About The Pull Request
With the holiday season approaching, I noticed a distinct lack of foods suitable for those present on Christmas day.
I am providing three dishes! 
A Chicken roast, with peas, cabbage, parsnips, potatoes, gravy and stuffing for the normal crew.
A grain free version of the normal, with korta stuffing and korta-blood gravy.
A meat free version for those ~~who turned their backs on the ways and diets of our ancestors, the kin who raised them, the kin who suffered so they could strive, the kin who sent them to the very stars themselves where they could become gods!~~ ... who choose to live a meat free lifestyle.

image
image
image
image
## Why It's Good For The Game
Nothing better for roleplay than the chef getting everyone together on Christmas day for a big old roast dinner where we can share in eachother's company... ~~until someone does something dumb like a max cap.~~
## Changelog
:cl:
add: Added new roast dinners, able to be cut into smaller portions hopefully in time for the Christmas season.
/:cl:

### CODE REVIEW

**Comment by Dawnseer** [comment]
We must wholeroast pigs. It has to happen

**Comment by xXPawnStarrXx** [comment]
> We must wholeroast pigs. It has to happen

I'm looking into finding if I can use dead creatures for cooking recipes already. Hog roast is my intended plan.

**Review by MrMelbert — COMMENTED** [review]
Cool food but I'd be remiss to mention that we have real plates so we shouldn't add food that include plates in the sprites

**Comment by xXPawnStarrXx** [comment]
> Cool food but I'd be remiss to mention that we have real plates so we shouldn't add food that include plates in the sprites

Plates removed.

**Comment by san7890** [comment]
you don't have to keep hitting the "Update Branch" button if you don't have merge conflicts FYI

also you're going to go into some GBP debt with this PR, in the spirit of christmas I am electing to ignore this for this PR but you really should start doing some fix PRs or something

**Comment by xXPawnStarrXx** [comment]
> you don't have to keep hitting the "Update Branch" button if you don't have merge conflicts FYI
> 
> also you're going to go into further GBP debt with this PR, in the spirit of christmas I am electing to ignore this for this PR but you really should start doing some fix PRs or something

It kept failing a map check for some reason.

**Comment by san7890** [comment]
ah yeah that tends to happen. you can look into pushing an empty commit from your git client but ehh

**Comment by xXPawnStarrXx** [comment]
> ah yeah that tends to happen. you can look into pushing an empty commit from your git client but ehh

Yeah. I normally would, but it allowed me to refresh the checks here while I was already on the page by hitting the update button.

**Review by Wallemations — APPROVED** [review]
cut this shit like snoopy n' woodstock

**Pull request merged**
