### PR TITLE
fix icebox ahhh

### PR DESCRIPTION
**Pull request by Ghilker**
## About The Pull Request
i forgot to change layer3 to layer4 in icebox above

## Why It's Good For The Game
fix

## Changelog
:cl:
fix: Icebox pipe layering error
/:cl:

### CODE REVIEW

**Comment by Rohesie** [comment]
Hotfix. Speedmerged it due to it possibly breaking the game.
Please be more careful in the future and test it locally.

**Comment by MrStonedOne** [comment]
Can somebody explain to me why layers use different icons bloating shit up instead of pixel offsets?

**Comment by Ghilker** [comment]
@MrStonedOne it's because of mappers, but I'll try to make a pr to reduce the bloat on those by using pixel offset

**Comment by Dennok** [comment]
> Can somebody explain to me why layers use different icons bloating shit up instead of pixel offsets?

Becose pixel shifted pipes go beyond the turf boundaries

**Pull request merged**
