### PR TITLE
Change VV to order by higher level types first

### PR DESCRIPTION
**Pull request by coiax**
The aim is to order the variables in VV based on the most recent
definitions.

Most of the time when you open VV, you care about the top most, and very
rarely `gc_collected` on /datum.

---

This is work in process, opening this PR to allow for collaboration.

### CODE REVIEW

**Comment by Watermelon914** [comment]
http://www.byond.com/forum/post/2703249
feature request to make getting variables of parent types easier

**Comment by Watermelon914** [comment]
The problem with the currently implementation is that you have to load a massive file if you are accessing only 1 object.
A solution would be to move this all to tgui and to have a script that generates all the interfaces whilst .gitignoring them. This isn't a great solution but it'd likely be better than the current one.
I recommend waiting until the above feature request is implemented, whenever that is (could be a week, could be a year), since there isn't really any decent solutions to doing this yet.

**Comment by MrStonedOne** [comment]
VV can not be moved to tgui without leaving a non-tgui version.

**Comment by Watermelon914** [comment]
> VV can not be moved to tgui without leaving a non-tgui version.

maintaining two versions of VV might be kinda stupid in that case

**Pull request closed without merging**
