### PR TITLE
Bees can now vent crawl

### LINKED ISSUE #48281: Bees Can't Ventcrawl
Being some of the smallest creatures in SS13, you'd think they'd be able to slip into vents easily. But no, they can't.
Consistency issue.

### PR DESCRIPTION
**Pull request by Ty-the-Smonk**
## About The Pull Request
Bees can now fly into vents and explore the station.

## Why It's Good For The Game
Small bugs like roaches can vent crawl, so why not bees too? Also consistency issue as pointed out in #48281.

## Changelog
:cl:
fix: #48281 Bees can now vent crawl
/:cl:

### CODE REVIEW

**Comment by PKPenguin321** [comment]
Wouldn't air in the vents make it really hard to fly?

**Comment by Ty-the-Smonk** [comment]
Bees can crawl

**Comment by PKPenguin321** [comment]
Very slowy, sure

**Comment by cacogen** [comment]
'ate bees
simple as

**Comment by Ty-the-Smonk** [comment]
what about bats?

**Review by Cyberboss — APPROVED** [review]

**Comment by Tharcoonvagh** [comment]
Fight like a bee
Sting like a bee
irving_the_socially_awkward_bee_by_amalockh1_d7hqweu

**Comment by nemvar** [comment]
Is this tested? Do you now have to weld the vent in botany because bee AI starts crawling? How does this interact with the swarming component?

**Comment by Ty-the-Smonk** [comment]
@nemvar I did test this and the AI mostly just ignore vent crawling from what ive seen

**Pull request merged**
