### PR TITLE
Analyze Upgrade

### PR DESCRIPTION
**Pull request by Deantwo**
When I was updating the ChemMaster in https://github.com/tgstation/-tg-station/pull/7445, I fell over this little forgotten feature. It only showed the name and description of the analyzed chemical. So I thought it would be more useful if I added some more information to it.

**ChemMaster changes:**
- Analyze screen now displays more information about the reagent; _reagent_state_, _color_, _overdose_threshold_, _addiction_threshold_, and _metabolization_rate_.
- Analyze href changed to send a pointer to the target reagent. So it is easy to add even more information!
- _metabolization_rate_ is displayed as units/minute.

**Analyze screenshot:**
chemmaster analyzer 3

**Feedback needed:**
- Look and feel of the interface.
- Ideas for more information.
- Should the Analyze feature be disabled or limited on the CondiMaster?

### CODE REVIEW

**Comment by Xhuis** [comment]
:+1:

**Comment by GunHog** [comment]
The description text is not suitable for ingame use. It needs to be refined into medical technobabble to preserve the immersion.

**Comment by Deantwo** [comment]
Yeah I know @GunHog, but that is not really my area.
Ask @Iamgoofball to chamge them I guess, or maybe @q

**Comment by Iamgoofball** [comment]
idgaf about immersion so if someone wants to rewrite descriptions sure go for it

for now :+1: this regardless of descriptions

**Comment by Deantwo** [comment]
Well, the descriptions are there in the current version, I only added the other bits on information.
And yeah I didn't even know about this analyze feature before either.

**Comment by Deantwo** [comment]
Thinking about adding "var/category" or something to reagents, so we can give them a group.
Since goonchem changes medicines aren't all pathed "/datum/reagent/medicine" anymore, same with toxins that aren't "/datum/reagent/toxin".

Mostly of all I want this for this analyze feature and for use in the handheld reagent scanner I am fiddling with.

Ideas?

**Comment by AlexCrimson** [comment]
Honestly i am fine with the gamey descriptions. So long as they are accurate(there have been some balance fixes, so the wiki descriptions might not be up-to-date, not sure). Maybe add in metabolism rates. 

Most people do not even realise this is a feature. So maybe make the "Analyze" button more obvious in the UI?

**Comment by Deantwo** [comment]
Yeah I have been wondering about how I would make the "analyze" button more noticeable, but haven't thought up a good idea yet.

I actually don't know much about "metabolism rates" and how they work.

**Comment by AlexCrimson** [comment]
As i understand it, they change how fast chemicals are processed in your system. The old chems were mostly 0.4 units per tick i think? 

For example Venom has a metabolism rate of 0.2, which makes it decay rather slowly. Cyanide is 0.1, which is really slow. Helpful chemicals also vary. Saline-Glucose and Charcoal are 0.4. However Charcoal makes other chems metabolize faster. This is why Charcoal is so useful as it not only counters toxin damage, but also makes other chemicals metabolize much faster.

Its easiest to just host a private server and check it out by testing it. You can View Variables>Reagents to track whats in your system and how fast its decaying.

**Comment by Deantwo** [comment]
Ok I added metabolization_rate.
Picture in main post updated.

Also changed the text I was hiding under the color to something more useful.
It is not the actual hex value of the color.

**Comment by Tenebrosity** [comment]
Great feature. I had some feedback though.

- It's not clear what metabolisation rate means. 0.2u every how many seconds?
- Those descriptions are very codey. The LOSEBREATH thing in the epinephrine description is the main thing I take issue with, as it's obviously referring to a function in the code and not a medical condition.

**Comment by Deantwo** [comment]
I don't know how long a tick is, so, yeah.
I can change it to "0.2u/s" but I have a feeling that a tick isn't one second.

**Comment by Tenebrosity** [comment]
I don't know either, I'm afraid. Somebody in coderbus will though.

**Comment by AlexCrimson** [comment]
It could be per second. Ive just always heard people describe it as "per tick". Which has always been strange to me since in Minecraft there are 20 ticks in a second. Eh, im no coder so i assumed ticks were different in SS13.

**Comment by Deantwo** [comment]
From what @wild-billy told me, there are 4 life ticks per decisions.
So ```var/T = (metabolization_rate * 2.5)``` would be per second I think.
I think.

**Comment by Iamgoofball** [comment]
it's 0.2u every 3 seconds now

**Comment by Deantwo** [comment]
Ah ok thanks @Iamgoofball!

**Comment by Deantwo** [comment]
I would very much like some feedback on my use of words for the last three fields.
- ```Metabolization rate```
- ```Overdosage```
- ```Addiction```

Do that make sense like that or do I need to rename them?
Suggestions so far:
- ```Metabolize Rate```
- ```Overdose Threshold```
- ```Addiction Threshold```

Thoughts?

**Comment by Tenebrosity** [comment]
My first thought for overdosage was LD50 (lethal dose 50, the amount that 50 percent of the rats the drug has been tested on overdose from) but I doubt many people know what that is. Overdose threshold sounds good. So does addiction threshold. I would stick with metabolisation rate though, it's more grammatical.

**Comment by Deantwo** [comment]
Ok will do that in the morning.

I finished the metabolisation rate calulation though, it will show units/minute because that will yield none decimal numbers the most often.

```var/T = R.metabolisation_rate * 60 / 3```
"3" is the number of seconds between life ticks.

**Comment by Tenebrosity** [comment]
Neat. Maybe you could round the final number to get rid of the decimals so it doesn't seem so exact? It'd look less gamey, as realistically the decay rate would differ from person to person.

**Comment by Deantwo** [comment]
Wondering a little if there should be a type of *reagent database*, like we have the *virus database*.
Could even make the analyze screen here list the formula to make the chemical with the names being links to each chemical.

Then of course we will have to hide a few of them like holy water and so, but still.

Thoughts?

Also the question I asked @Iamgoofball on the forum here: https://tgstation13.org/phpBB/viewtopic.php?f=45&t=2876&p=67904#p67904

**Comment by Tenebrosity** [comment]
That sounds really good

**Comment by TheVekter** [comment]
@Deantwo I would -love- to see some form of reagent database. It'd make the transition to goonchem about a million times easier on everyone.

**Comment by Miauw62** [comment]
is this ready?

**Comment by Deantwo** [comment]
Yeah, let's merge this and I'll look at trying to make it into a database in another PR.

**Pull request merged**
