### PR TITLE
Puts files in single quotes like they belong

### PR DESCRIPTION
**Pull request by MrPerson**
This means they're included into the rsc and sent out although almost all of these files were already included elsewhere. Also DM will yell if the file couldn't be found for whatever reason like if someone moves or renames it.

I left out some file types for various reasons
dmis used in overlays: I have another pr I'll do later which will fix all of them and I don't want to conflict with myself
text files: they would get included in the rsc, which is completely unnecessary. However they're small, so they might be worth including anyway for the reasons above.

### CODE REVIEW

**Comment by Cyberboss** [comment]
IS THIS WHY I KEEP FUCKING FREEZING WHEN I JUMP ANYWHERE? REEEEE

**Review by Cyberboss — APPROVED** [review]
IS THIS WHY I KEEP FUCKING FREEZING WHEN I JUMP ANYWHERE? REEEEE

**Comment by optimumtact** [comment]
How much bigger does this make the DMB out of interest?

**Comment by MrPerson** [comment]
I don't think it does. Every single file was referenced elsewhere.

**Pull request merged**
