### PR TITLE
Fixes supermatter AC. Keeps max subtract below current power.

### LINKED ISSUE #42141: SM produces rads with negative intensity values at extreme power values.
SM Power calculation is fundamentally broken. There are 2 lines of code assigning a power value, using max(formula, 0) to ensure that it's not negative, and then:
power -= ((power/500)**3) * powerloss_inhibitor
Gas and rad production then scale with power.
https://www.desmos.com/calculator/de7keoqr1n

### LINKED ISSUE #47703: Its possible to make a negative energy supermatter that incinerates everyone around engineering instantly
Over half the station died, this was on kilo and people in cargo just instantly dropped dead, from 100 health to husked, I think it was atmos witchcraft of some form. I dont know how it happened but admins say power level was at -6.16072e+019. Thats pretty much all I can say, good fucking luck.

Issue reported from  Round ID: 123404 (/tg/Station Sybil [ENGLISH] [US-WEST] [100% LAG FREE])

Reporting client version: 512.1488

### PR DESCRIPTION
**Pull request by LemonInTheDark**
## About The Pull Request

Takes `(power/500)^3*powerloss_inhibitor` and transitions into `abs((power-100)*powerloss_inhibitor)`
Maxes power after loss at 1
Fixes #47703 
Fixes #42141
The function that gets transitioned into may need some tweaking, tested at -1 and little power growth was observed.

## Why It's Good For The Game

Removes alternating SM power values. transitions the exponential function into a linear one.
Future proofs against the revolving values of power.

Because of the exponential function, large initial jumps in power from fusion for instance would allow for large negative values.
This was both really weird and obfuscated the relationship between power and large and negative temperature.

Fixes a runtime or two in process_atmos() caused by negative power values.

## Changelog
:cl:
fix: Fixed negative power being generated by the supermatter engine. Some math has changed, time to find your new autism setup balance.
/:cl:

### CODE REVIEW

**Comment by LemonInTheDark** [comment]
Actually this time

**Comment by LemonInTheDark** [comment]
Here's a graph of the old formula and the one I'm using, gist of it is the exponential growth backfired, my proposed workaround is to add a linear function to transition into, but I'm not sure how that would effect high power sm setups. [https://www.desmos.com/calculator/ir8mby5smz](https://www.desmos.com/calculator/ir8mby5smz)

**Comment by Cyprex** [comment]
Seems like a lot of power loss for normal setups, you might want to test the default setup with and without your changes and check out power production.

**Comment by Cyprex** [comment]
Also, I feel like it would be more readable if you split up the expression, I was thinking something like
power_lost=....
power = max(power - power_lost, 1)

**Comment by LemonInTheDark** [comment]
In regards to the power loss I'm sorry for not being more clear.
The linear function only gets used when the amount it subtracts is less then the old function, which should only happened when the old function gets within 100 power of causing negative power.
I will test it with the round-start setup tho.

I was trying to keep the modifications to a minimum, but if you would prefer it be more clear I'm open to that.

**Comment by LemonInTheDark** [comment]
I've tested with the old and new code, I haven't seen any differences in a standard n2 setup or a 95% co2 delam.

The 2 gas mixes were not the same for the delams, which is why there's such a difference in power. The power growth rate between the new and old at the co2 levels is not quite the same, which may be causing higher power delams above 11000 power.

[Old N2](https://media.discordapp.net/attachments/458452245256601615/648692647212482581/unknown.png)
[Old Delam](https://cdn.discordapp.com/attachments/458452245256601615/648700299393105931/unknown.png)
[New N2](https://cdn.discordapp.com/attachments/458452245256601615/648692647212482581/unknown.png)
[New Delam](https://cdn.discordapp.com/attachments/458452245256601615/648678746185924628/unknown.png)

**Comment by kriskog** [comment]
I gave it a go, and negative power is a thing of the past. I would argue that this should be far above power 100 though, math needs some fundamental changes to prevent negative power values in the first place imo.
image

**Comment by LemonInTheDark** [comment]
Made the difference proportional, should make it better, here's a graph of power before and after. 
[Graph](https://www.desmos.com/calculator/9gkwocfznb).
I'm a bit concerned about how this interacts with high co2 counts, it might make co2 really op/dangerous, may need some tweaking.

**Comment by LemonInTheDark** [comment]
This is a good change-log. I approve.

**Comment by kriskog** [comment]
Changes some stuff around, but fixes some bad issues. Might unbalance (haha implying intentional balance) co2 setups, we'll see what people figure out.

**Pull request merged**
