### PR TITLE
Makes examines that show whole dmi file use costly_bicon()

### LINKED ISSUE #28322: Tables show the icon for the whole dmi file instead of the proper sprite when examining.

### PR DESCRIPTION
**Pull request by Cyberboss**
Fixes #28322

### CODE REVIEW

**Comment by RandomMarine** [comment]
Costly bitcoin

**Comment by optimumtact** [comment]
This seems like a hack that doesn't solve the underlying issue, which may or may not be a byond issue and should be reported.

**Comment by AnturK** [comment]
Whole bicon is one giant hack oranges, savefile conversion is not intended to be used like this so don't expect any results on that front. (Until 512 changes at least)

**Comment by optimumtact** [comment]
I haven't looked at what bicon actually is so

**Comment by RemieRichards** [comment]
@optimumtact it puts the icon into a byond .sav file, which automatically base64's it, then it reads out that base64 to send to the browser/output.

**Comment by ZVee** [comment]
Hello, short client freeze happens when you examine such icons? Because if it is, then thats probably what i lazy fixed in bicon() for our server some time ago.

**Comment by lzimann** [comment]
How laggy does this get though? Examine can be spammed(and there is no limit since it's a message to a single person only), and if this is indeed costly then we might have problems.

**Comment by optimumtact** [comment]
@RemieRichards hmm it's far worse than I could have ever expected :grin:

**Comment by AnturK** [comment]
@Cyberboss From what i can see in the code costly_bicon does not try for the cache before using getFlat which makes this very bad.

**Pull request closed without merging**
