### PR TITLE
Fix for meme names and cyborg keys

### PR DESCRIPTION
**Pull request by Cyberboss**
Clown + Mime pref names: Fixed

Cyborgs never getting assigned their key: Fixed
>There's a comment in job/equip saying not to override it but someone fucking did anyway

### CODE REVIEW

**Comment by Qbopper** [comment]
please god, let this work

**Comment by Cyberboss** [comment]
Don't merge this till I'm back from vaycay on Sunday

**Comment by lzimann** [comment]
Ping me when you get back then.

**Comment by Cyberboss** [comment]
Vacation till Sunday

**Pull request closed without merging**
