### PR TITLE
makes tank suicides leak the gas out

### PR DESCRIPTION
**Pull request by Fikou**
## About The Pull Request

when you suicide with a full tank the gas now leaks when you explode

## Why It's Good For The Game

fun interaction, allows you to make your death quite spectacular with gas combinations

## Changelog
:cl:
add: The gas tank suicide is now more spectacular!
/:cl:

### CODE REVIEW

**Comment by NoxVS** [comment]
I dont really think a suicide should ever be any threat to people around the guy doing it

**Comment by Dawson1917** [comment]
Not quite looking forward to plasmamen suiciding and leaking airborne toxin damage into the hallways

**Comment by Whoneedspacee** [comment]
i mean it’s no different than a grenade suicide or just breaking open a tank or a canister.

no real powergamey reason to not add this anyways since tanks put up to 3000 kpa or so pressure leak their gas automatically anyways, just a cool interaction.

**Comment by KomradeSpectre** [comment]
> I dont really think a suicide should ever be any threat to people around the guy doing it

Except C4/X4 suicides cause immense damage to people around the suicider. Even the tank gib suicide causes damage to those nearby, even if only slightly. Both are threats. I'm not sure where you're going with this. Now on the topic of the PR, I'm not sure this is a great idea because of plasma tanks, any combination of gas in a tank makes for a very very easy way to flood places in a last ditch suicide attempt, and pretty undetectable until it's too late (especially on rev rounds where you're completely expendable).

**Comment by nemvar** [comment]
It's not about what suicides currently do, it's about what they should do. I don't think that it's a good thing for suicides to murder the people around them.

It's a highly OOC action and as such the IC impact should be minimal.

**Comment by optimumtact** [comment]
they're right

**Pull request closed without merging**
