### PR TITLE
[WIP] Adds new locations for destination taggers

### PR DESCRIPTION
**Pull request by 81Denton**
:cl: Denton
tweak: New destinations have been added to destination taggers. 
/:cl:

I'm planning to add more destinations that you can mail packages to - for now it's Circuitry, Toxins, Dorms, Viro, Xenobio. Are there any others you can think of?

WIP since I want to collect ideas before I start mapping.

### CODE REVIEW

**Comment by Vidiveni** [comment]
I would actually like to be able to send packages to the public hallways. This way I'd be able to distribute stuff to nobody in particular.

**Comment by Dennok** [comment]
Meby make for this special tagger what inputs id of bin manually.

**Comment by 81Denton** [comment]
@Vidiveni Sounds good. I'll have to check out if all maps have disposal bins in similar hallway areas (or add them).

**Comment by 81Denton** [comment]
I'll reopen this after I'm done with a few small mapping PRs, otherwise this will be a merge conflict nightmare

**Pull request closed without merging**
