### PR TITLE
Adds support for clickdrag/clickholding on items

### PR DESCRIPTION
**Pull request by silicons**
# What it says on the tin, could have charged up items/wizard spells based on this later and or channeled things that aren't just "Click button stand still". (And I plan to add some!)
YES, I UNDERSTAND THE POTENTIAL OVERHEAD, BUT THIS DOES NOT TRIGGER UNLESS THE MOB IS ACTUALLY HOLDING AN ITEM THAT HAS BEEN MARKED AS CAN_MOUSE_DOWN, AND THE PROCS ARE ALREADY DEFINED.

### CODE REVIEW

**Comment by MrPerson** [comment]
The cost comes from the network spam of doing this for every possible thing. The actual code overhead is irrelevant.

**Comment by kevinz000** [comment]
yeah but you already check for if a mob can autoclick is this going to be much worse?

**Comment by Incoming5643** [comment]
We already have too many ways to interact with objects, not wild about adding another.

Kill click drag first tbh

**Comment by kevinz000** [comment]
@Incoming5643 this allows for clickhold charging items, instead of just a boring old "You click a button it channels and then you click and it releases". Could have more items that have higher skill ceilings using this.

**Comment by ShadowDeath6** [comment]
I can't really think of a situation where you'd want to hold your mouse down on something for more than a full second, honestly.

**Comment by MrPerson** [comment]
We could do melee attacking like this where you click and hold something distant to swing in that direction.

**Comment by optimumtact** [comment]
This has to come with something we're actually going to use it before I will merge it.

**Pull request closed without merging**
