### PR TITLE
Atmos Multifilter

### PR DESCRIPTION
**Pull request by TemporalOroboros**
Makes atmos filters capable of filtering multiple gases at once.

## About The Pull Request
Makes the atmos filter device capable of filtering multiple gases at once.
Clicking on one of the gases in the TGUI interface toggles the filter.
Clicking on the "Nothing" option clears all active filters.

## Why It's Good For The Game
Makes it possible to construct denser atmos setups. The turbine area is _really small_.

## Changelog
:cl:
tweak: The atmos filters can now filter multiple gases at the same time.
/:cl:

### CODE REVIEW

**Comment by LemonInTheDark** [comment]
I think atmos devices should be very single minded, and I think that stacking filters is an extension of that. While I do like the fact that filtering 2 gasses is twice as slow as filtering 1, I don't think that's enough. Space is a concern I understand, but working around that concern is part of the game, and I don't want to damage that.

**Comment by trerri** [comment]
Counterpoint: QoL good
ESPECIALLY if it's for atmos, it makes it less arcane

**Comment by Barhandar** [comment]
I would prefer that rather than messing with existing filter, you'd made a machine that can filter up to five gases into individual layers.

**Comment by Dennok** [comment]
> I would prefer that rather than messing with existing filter, you'd made a machine that can filter up to five gases into individual layers.

and up to 19 gases with individual directions
I think this better make like separate big(dense) machine with components.

**Comment by Misdoubtful** [comment]
> I would prefer that rather than messing with existing filter, you'd made a machine that can filter up to five gases into individual layers.

Would omni filters be a more realistic approach to this?

**Comment by Cyprex** [comment]
Part of the challenge is getting what you want with the limitations at hand. Atmos has 5 layers now which makes routing even easier. I've done many setups in the turbine room and have never really run out of space. Finding a compact way to arrange your pipenet is part of the challenge. As such, I'm against this PR.

**Comment by LemonInTheDark** [comment]
> 
> 
> Counterpoint: QoL good
> ESPECIALLY if it's for atmos, it makes it less arcane

To some extent sure, atmos isn't in the best place, but not all QOL is going to be good or sane

**Comment by TemporalOroboros** [comment]
Well, I tried.

@Barhandar I would try to do this, but I have neither the time nor energy at the moment with classes starting up to learn TGUI.

**Pull request closed without merging**
