### PR TITLE
Add bug (ci test, can't do this locally)

### PR DESCRIPTION
**Pull request by mokulus**
## Changelog
:cl:
code: add a bug
/:cl:

### CODE REVIEW

**Comment by Mothblocks** [comment]
you have your own fork you can test this locally

**Comment by LemonInTheDark** [comment]
Can't you test this locally? what exactly were you trying to break?

**Comment by mokulus** [comment]
Sorry for the problem. I managed to enable this in my fork.

**Comment by LemonInTheDark** [comment]
Godspeed

**Pull request closed without merging**
