### PR TITLE
Revives rust heretic rework

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request

Revives the https://github.com/tgstation/tgstation/pull/65361 rust heretic rework

Last time i was trying to do this i accidentaly pushed the wrong branch, so yeah...

## Why It's Good For The Game

Adds a new layer of progression to heretic. Removes RNG pain with trying to rust reinforced walls while still making them more of a challenge to get past. Allows rust heretic to actually function on shuttles while still having materials that you could use to trap a non-ascended heretic in a prison of silver with.

## Changelog

:cl: GoblinBackwards
add: Heretic now has its ability to rust turfs scale with knowledge.
balance: Heretics now start off with limited rusting abilities, but grow to be able to rust almost anything as they progress
balance: Reinforced walls/floors can be rusted after unlocking Mark of Rust
balance: Titanium and plastitanium can be rusted after unlocking Toxic Blade
balance: Rust heretics can spread rust to almost anything after ascending.
balance: When playing as a non-rust heretic your rusting ability improves when you learn aggressive spread, entropic plume, and when you ascend. You need at least two to rust reinforced walls, and all three to be able to rust titanium.
balance: Rusting reinforced walls is no longer RNG, and instead turns them into a regular rusted wall after being rusted twice.
/:cl:

### CODE REVIEW

**Comment by SuperNovaa41** [comment]
Alright if you want to make a large balance change like this you need to meet some conditions.

You need to explain every single change you've made. Doing this through the changelog alone is not sufficient.
As well, you need to describe why this is good for the game.

> Removes RNG shit from the rust heretic and adds more progression

is NOT enough.

Fix these and I will remove the DNM tag.

**Comment by necromanceranne** [comment]
You should also probably speak to @MrMelbert as they are actively developing Heretics.

**Comment by SuperSlayer0** [comment]
> Alright if you want to make a large balance change like this you need to meet some conditions.
> 
> You need to explain every single change you've made. Doing this through the changelog alone is not sufficient. As well, you need to describe why this is good for the game.
> 
> > Removes RNG shit from the rust heretic and adds more progression
> 
> is NOT enough.
> 
> Fix these and I will remove the DNM tag.

It is described in the original PR, to which i left the link

**Comment by SuperNovaa41** [comment]
> > original comment
> 
> It is described in the original PR, to which i left the link

**Comment by SuperNovaa41** [comment]
paste it here then

**Pull request closed without merging**
