### PR TITLE
Adds species override support for angel wings and gives it to the ert medic hardsuit

### PR DESCRIPTION
**Pull request by Shadowlight213**
The medic has also had their backpack be changed to a satchel.

THIS DOESN'T MAKE ERT MEDICS ANGELS.

### CODE REVIEW

**Comment by Cheridan** [comment]
what is the lore behind NT hiring angels to be medics for their ERT

**Comment by Armhulen** [comment]
is this because of the mercy we had in the ERT?

**Comment by optimumtact** [comment]
This doesn't fit because angels aren't common NT employees.

**Comment by Razharas** [comment]
>Overmeme references
They sure blast a fortune on advertising this shit
Shadowlight confirmed for bliz-shill

**Comment by Iamgoofball** [comment]
i am DONE

**Comment by GunHog** [comment]
Give them a jetpack item or something, Angels do not even make sense for a place like Lavaland (should be dragon/watcher wings instead).

**Comment by GeneralGoose** [comment]
wweeww  laaaadd
ffeetttiisshhiisstt  llaatteexx  ccoosstummees and fffuta   porn with harammbe when?

**Comment by RemieRichards** [comment]
Correct me if I'm wrong, but this just adds the system of species exceptions+lets angels wear ERT medic suits.

ERT medics aren't becoming Angels.

**Comment by Shadowlight213** [comment]
Remie s correct.
This also fixes stuff unequipping if it was in a restricted slot but had a species exception when using set_species

**Comment by Shadowlight213** [comment]
Whoops. Wrong buttn

**Comment by Shadowlight213** [comment]
@Razharas sorry, overmeme team is not possible until we get fat sprites back.

**Pull request merged**
