### PR TITLE
Prevents Voice of God from sleeping non-organics

### PR DESCRIPTION
**Pull request by BroseidonMOO**
[]: # Non-organics cannot be put to sleep, such as Silicons, but would still get the status effect incorrectly, the same applies for weaken, maybe others, but those were the only two obvious ones.

### CODE REVIEW

**Comment by PKPenguin321** [comment]
Not sure a changelog is necessary.

**Comment by BroseidonMOO** [comment]
It probably isn't. I wasn't sure what really needed them and what didn't. Do I just edit it out?

**Comment by PKPenguin321** [comment]
Yep!

Changelogs are just what we show to players, such as alerting them to a new feature. Minor bug fixes and touchups that don't really affect players majorly generally don't need one.

**Comment by XDTM** [comment]
Silicons have a Weaken proc, what's the issue with it?

**Comment by BroseidonMOO** [comment]
You're entirely correct XDTM, I didn't look into it properly and thought it was there, but unused, but I can see some instances where it is used, I'll fix that right now.

**Comment by XDTM** [comment]
L, not V

**Pull request merged**
