### PR TITLE
Pacifist can use wand of nothing

### LINKED ISSUE #49199: Wand of Nothing conflicts with Pacifism
## Reproduction:
Spawn in on Donut as a pacifist and pick up the wand of nothing from the theater. You can fire it at yourself but if you try to fire it at anything else you are informed that the wand is _"lethally chambered"_. It's literally a wand that fires a projectile that does nothing.

### PR DESCRIPTION
**Pull request by itseasytosee**
Fixes #49199 without breaking all the other wands
Replaces magic pool old wand with the new one.
## Changelog
:cl: itseasytosee
fix: Pacifists can now use the wand of nothing.
/:cl:

### CODE REVIEW

**Comment by knacker48** [comment]
So what you're saying is, instead of not doing anything, the wand will do nothing?

**Comment by itseasytosee** [comment]
100%

**Comment by Mickyan** [comment]
you need to replace ALL of the wands available ingame with your subtype or this is going to turn into an even bigger mess

**Comment by itseasytosee** [comment]
@Mickyan I made it a subtype and summon magic now summons it instead of the stock magic wand

**Comment by cacogen** [comment]
```
  C:\Users\cacogen\Documents\tgstation\_maps\map_files\Donutstation\Donutstation.dmm (1 hit)
	Line 38807: /obj/item/gun/magic/wand,
  C:\Users\cacogen\Documents\tgstation\_maps\map_files\generic\CentCom.dmm (1 hit)
	Line 13806: /obj/item/gun/magic/wand{
  C:\Users\cacogen\Documents\tgstation\_maps\RandomZLevels\Academy.dmm (1 hit)
	Line 3142: /obj/item/gun/magic/wand,
  C:\Users\cacogen\Documents\tgstation\_maps\RandomZLevels\SnowCabin.dmm (1 hit)
	Line 4114: /obj/item/gun/magic/wand{
```

**Comment by Mickyan** [comment]
You need to change all sources of the wand not just one

**Comment by itseasytosee** [comment]
I get it fix coming soon.

**Review by Cyberboss — APPROVED** [review]

**Comment by itseasytosee** [comment]
Wait this is not done
shit

**Comment by itseasytosee** [comment]
whatever secondary PR coming soon.

**Pull request merged**
