### PR TITLE
Genocides "_s" in icon states

### PR DESCRIPTION
**Pull request by Core0verload**
The "_s" suffix is an artifact from the times BYOND had no transforms and we had separate icons for standing and lying mobs, "_s" and "_l" respectively. Why these "_s" were still in code? Nobody knows.

This PR also adds "husk", "zombie" and "skeleton" icons back to `human.dmi` - they were used by hallucinations code.

This PR changes some obviously broken icon states to states that are just as broken, but lack "_s" suffix. Fixing them is out of scope of this PR.

### CODE REVIEW

**Comment by Core0verload** [comment]
Can I have a mini-freeze on human icons and uniform icons until this gets merged?

**Comment by dannno** [comment]
isn't this still used for things with toggles eg. rolling down jumpsuits, buttoning up labcoats
or am I mistaken

**Comment by Core0verload** [comment]
No, rolled down jumpsuits use "_d" suffix, buttoned suits use "_t"

**Comment by KorPhaeron** [comment]
@anturk see I saved the day by merging those human part changes early

**Comment by Core0verload** [comment]
Actually, no, it still conflicted in my branch.

**Comment by MrPerson** [comment]
\>nobody knows

I know. It's because I'm lazy and didn't want to do it.

**Pull request merged**
