### PR TITLE
Flypeople can now get wounds (This time im not stupid)

### PR DESCRIPTION
**Pull request by JohnFulpWillard**
## About The Pull Request

This allows flypeople to get wounds, thats all

## Why It's Good For The Game

Wound immunity just for being a certain race because of an unintended feature is bad

## Changelog
:cl:
fix: Flypeople can now get wounds
/:cl:

### CODE REVIEW

**Comment by tralezab** [comment]
👍

**Comment by Winterous** [comment]
On that note, flies (and all insects) are invertebrates, having an exoskeleton. That would be a mess to try and represent mechanically.

**Comment by JohnFulpWillard** [comment]
> 
> 
> On that note, flies (and all insects) are invertebrates, having an exoskeleton. That would be a mess to try and represent mechanically.

Flies, lorewise, is just a calibrated teleporter accident, we should be fine

**Comment by Farquaar** [comment]
Bone? Not an exoskeleton?
Lazy PR, pls do not merge

**Comment by JohnFulpWillard** [comment]
> 
> 
> Bone? Not a gross bone-exoskeleton hybrid? What's next, snailpeople with bones?

actually snails do have HAS_BONE

**Pull request merged**
