### PR TITLE
Yummy bugs

### PR DESCRIPTION
**Pull request by Wallemations**
## About The Pull Request
Adds a BUGS food flag, for bug-based foods. Lizards, Felinids, and Slimepeople all love bugs! Humans, Moths, and Podpeople don't.

As it stands there's 7 foods with the flag; the spider and ant foods.

## Why It's Good For The Game

46lvaa
 
There's no way I'm making a race immune to ants, that just makes them unbalanced. So instead, while not immune, they find them really yummy :)

It also makes sense that bugs would be eaten by other space cultures, since many cultures here on Earth today eat bugs too!

## Changelog

:cl: Wallem
add: Bug-based food items have been given their own foodtype. Lizards, Slimes, and Felinids love bugs! Humans, Moths, and Podpeople don't.
/:cl:

### CODE REVIEW

**Comment by Wallemations** [comment]
image

**Comment by VladinXXV** [comment]
Why have podpeople dislike bugs? I know plants commonly deal with pests, but that doesn't mean they don't like fighting back! Plenty of plants feast upon insects! Pitcher plants, venus fly traps, you know the type!

**Comment by Wallemations** [comment]
> Why have podpeople dislike bugs? I know plants commonly deal with pests, but that doesn't mean they don't like fighting back! Plenty of plants feast upon insects! Pitcher plants, venus fly traps, you know the type!

I did think about predator plants like that, but podpeople are made from mutated cabbages, which is why I made that choice.

**Comment by fippefi** [comment]
> Why have podpeople dislike bugs? I know plants commonly deal with pests, but that doesn't mean they don't like fighting back! Plenty of plants feast upon insects! Pitcher plants, venus fly traps, you know the type!

All the other food types they dislike (Meat, seafood, dairy) are proteinous like bugs, as well

**Comment by Bluedino1025** [comment]
You will live in the station and you will eat the bugs(literally 2564)

**Comment by the-orange-cow** [comment]
I don't know how this code works, and can't be bothered to learn, but just as a heads up jumping beans naturally have ants in them.

**Comment by Shadowflame909** [comment]
> You will live in the station and you will eat the bugs(literally 2564)

nanotransen is just real life lore

**Comment by Wallemations** [comment]
> Just as a heads up, jumping beans naturally have ants in them.

Damn really? You learn something new every day.
I'll slap that in tomorrow

**Comment by ilikesaying** [comment]
based?
image

**Comment by EOBGames** [comment]
This should also probably be applied to the canned larvae and nectar larvae in the lizard food category, both being bee larvae

**Comment by Farquaar** [comment]
> You will live in the station and you will eat the bugs(literally 2564)

I WILL NOT LIVE ON A STATION
I WILL NOT EAT THE BUGS

**Comment by ATH1909** [comment]
mothperson and flyperson meat should be given the BUG flag

**Review by Mothblocks — CHANGES_REQUESTED** [review]
Add this to the preferences menu.

Checklist:

Add `Bugs = "Bugs"` to https://github.com/tgstation/tgstation/blob/master/tgui/packages/tgui/interfaces/PreferencesMenu/data.ts#L5

Add something to `FOOD_ICONS` mapped to Food.Bugs, check font-awesome: https://github.com/tgstation/tgstation/blob/master/tgui/packages/tgui/interfaces/PreferencesMenu/SpeciesPage.tsx#L8

Add it to `FOOD_NAMES`: https://github.com/tgstation/tgstation/blob/master/tgui/packages/tgui/interfaces/PreferencesMenu/SpeciesPage.tsx#L25

Add it to `IGNORE_UNLESS_LIKED` (because it's obvious most don't like bugs): https://github.com/tgstation/tgstation/blob/master/tgui/packages/tgui/interfaces/PreferencesMenu/SpeciesPage.tsx#L42

Add it to FOOD_FLAGS (in code/__DEFINES/food.dm)

**Comment by bruhlookatthisdood** [comment]
when you eat ants from an ant pile it should remove the ants but just keep the pile of dirt for the janitor to clean up

**Comment by Wallemations** [comment]
> Add it to `IGNORE_UNLESS_LIKED` (because it's obvious most don't like bugs): https://github.com/tgstation/tgstation/blob/master/tgui/packages/tgui/interfaces/PreferencesMenu/SpeciesPage.tsx#L42

Actually, only three races really can't stand to eat bugs

**Comment by Mothblocks** [comment]
> Actually, only three races really can't stand to eat bugs at the moment. Would you prefer if all of them did?

It's more like, seeing "they don't like eating bugs" is just assumedly a given

**Review by Mothblocks — CHANGES_REQUESTED** [review]
Fix all the prefs menu stuff to be in alphabetical order (except FOOD_FLAGS)

**Comment by Wallemations** [comment]
> Fix all the prefs menu stuff to be in alphabetical order (except FOOD_FLAGS)

right, on it

**Comment by Wallemations** [comment]
image
how

**Comment by conk444** [comment]
What if, instead of having folks damage their insides in the pursuit of flavor, you make cooking kill the ants, rendering them completely harmless? Maybe heating ants above a certain temperature could have them form a reaction becoming "dead ants".

**Comment by Wallemations** [comment]
> What if, instead of having folks damage their insides in the pursuit of flavor, you make cooking kill the ants, rendering them completely harmless? Maybe heating ants above a certain temperature could have them form a reaction becoming "dead ants".

counterpoint: eating live ants is extremely funny

**Pull request merged**
