### PR TITLE
replaces 1s and 0s in boolean returns to TRUE/FALSE

### PR DESCRIPTION
**Pull request by silicons**
i would do everything else too but this is the limit of my attention span for today.

### CODE REVIEW

**Comment by Jordie0608** [comment]
RIP the codebase

**Comment by pubby** [comment]
```
/proc/Csc(x)
	return TRUE / sin(x)
```
:+1: :100:

**Comment by BeeSting12** [comment]
inb4 this breaks the whole game

**Comment by ShizCalev** [comment]
dear god you didn't

redo this with the proper regex for the love of god :(

**Comment by kevinz000** [comment]
i used a very crappy one because i was lazy then realized it'd be more work when i had to go through 700 files.

**Comment by AnturK** [comment]
This is nightmare to review. Just from the top few i can already tell you were just replacing everything that came up that require NONE or actual numbers. So i'll save you the trouble.

**Pull request closed without merging**
