### PR TITLE
Fixes an errant sanity check in slimeperson splitting

### PR DESCRIPTION
**Pull request by Incoming5643**
I accidentally double negatived a sanity check on the new slime ability (#12476), thus making it only work if you're NOT a slime anymore.

Please just merge this and don't look me in the eyes.

### CODE REVIEW

**Comment by Shadowlight213** [comment]
@Incoming5643 I tried changing species but that didnt fix it.

**Comment by SuperSayu** [comment]
I would remove the other ! myself

I can never remember whether !x == b means (!x) or !=

**Comment by RemieRichards** [comment]
example:
```
x = TRUE
b = FALSE

!x == b is FALSE == FALSE, which is true
!(x == b) is !(FALSE == FALSE) which is false
x != b is true != false, which is true
```

**Comment by Incoming5643** [comment]
Alright I've tested it, THIS works.

I swear it worked before all the conflict resolutions

**Comment by RemieRichards** [comment]
@Incoming5643 switch which ```!``` you remove please.

**Comment by Incoming5643** [comment]
Fair enough

**Comment by Incoming5643** [comment]
@Shadowlight213 it's looking for the species of the person you're swapping into, not out of.

**Comment by Shadowlight213** [comment]
@incoming5643 I know. I tried combinations of both. Still didn't work. You actually can't swap out of a different species as you lose the spell upon changing species.

**Comment by Incoming5643** [comment]
Oh well that's intended too. The way it's supposed to work is that both bodies need to be slimepeople. This check keeps track of the destination body, while losing the action on species change keeps the current body in check.

**Comment by Incoming5643** [comment]
I'd like if someone got to merging this sooner rather than later, the feature straight up doesn't work without this.

**Comment by Incoming5643** [comment]
kudos to yudos

**Pull request merged**
