### PR TITLE
Add lavaland escape shuttle

### PR DESCRIPTION
**Pull request by timothymtorres**
## About The Pull Request
This adds a special escape shuttle that is unlocked when the megafauna legion is beaten.  It is pretty large but players can navigate it using boats quite easily.

## Why It's Good For The Game
StrongDMM-2023-12-25 11 20 36

## Changelog
:cl:
add: Add lavaland escape shuttle.
/:cl:

### CODE REVIEW

**Comment by Fikou** [comment]
arena but less cool

**Comment by CRITAWAKETS** [comment]
this needs to be the new form of arena and given weapons so people can just do pirate duels on the boats

**Comment by SomeoneYouProbablyKnow** [comment]
Any turulence will result in a 1% survival rate

**Comment by Admiral-Gigaton** [comment]
Are those iron doors spaceport? Don't want entire shuttle to go tits up as me and John miner duel it out like a starters scene

**Pull request closed without merging**
