### PR TITLE
Extra detectives get guns and sunglasses too

### PR DESCRIPTION
**Pull request by cacogen**
## About The Pull Request

If you sign up as a detective and there is already at least one detective, an extra holster and pair of sunglasses with either spawn in the detective's locker or on your person.

## Why It's Good For The Game

A detective shouldn't be without his firearm. The sunglasses are relatively rare depending on the station too.

## Changelog

:cl: cacogen
add: Extra detectives will have guns and sunglasses appear in the detective's cabinet or on their person when they join
/:cl:

### CODE REVIEW

**Comment by optimumtact** [comment]
yeah god forbid you might have to actually play the game to get some of these items as a second detective.

**Comment by JohnFulpWillard** [comment]
Why not just copy https://github.com/tgstation/tgstation/pull/61598

**Comment by JohnFulpWillard** [comment]
> 
> 
> Aren't detectives still locked to one slot by default? is this just #61598 but again?

They are 1 by default, but not locked if the HoP opens another.

**Comment by optimumtact** [comment]
changed my mind, dont' think this is necessary, if you want to open slots, the crew should have to outfit that person beyond the basic clothing.

**Comment by optimumtact** [comment]
so add an individual item order for revolvers to cargo.

**Comment by optimumtact** [comment]
okay but I don't agree, no other job has snowflake support for adding extra equipment, detective doesn't deserve it.

adding it to cargo as individual item orders should be more than fine.

and the argument it can be broken open applies for any of the guns orderable by cargo, in practice it has not been a huge issue.

**Comment by cacogen** [comment]
There was a lot of additional information in that post, actually.

**Pull request closed without merging**
