### PR TITLE
Revert "Makes immerse use weakrefs", prioritizing some ref removal lines instead.

### PR DESCRIPTION
**Pull request by Ghommie**
## About The Pull Request
For a moment, I had forgot about saying I'd take a look into it, but it seems the new fix to hard dels is causing some runtimes with empty weakrefs. Beside, WEAKREF() doesn't work well with qdeleting atoms (so you'd have to access the weak_reference var directly).
How immersion works is quite confusing even for me who coded it, trying to work around some of the hefty limitations of the engine truly blows. I could even ask MrMelbert to make a proc-chain chart for it.

But yeah, long story short, I only have a bare idea where the uncleared refs would be. I suspect it could be `immersed_movables`. It's totally possible since the proc can early return in a few cases, thus skipping the ref removal, hence the title.

## Why It's Good For The Game
I didn't like the PR that implemented weakref usage into the element, but I let it pass because "hard dels = bad". However, the runtimes aren't that much more pleasant either.

## Changelog
N/A

### CODE REVIEW

**Comment by Arturlang** [comment]
Huh odd i tried checking for runtimes

**Comment by Majkl-J** [comment]
Immerse still causes issues downstream 
image

**Comment by Ghommie** [comment]
Well, I'll take once again a deeper look into it later. The fact it's causing hard dels downstream doesn't necessarily mean it's an issue here, but since the element is fickle, I'm confident it could as well be.

**Comment by Majkl-J** [comment]
> Well, I'll take once again a deeper look into it later. The fact it's causing hard dels downstream doesn't necessarily mean it's an issue here, but since the element is fickle, I'm confident it could as well be.

I have no idea, I just know that making it use weakrefs at least made it pass checks on the one map with water tiles

**Pull request merged**
