### PR TITLE
Readds BZ Cannisters for Xenobiology

### PR DESCRIPTION
**Pull request by YakumoChen**
:cl: YakumoChen
tweak: Nanotrasen has once again shipped BZ to its nearby stations. Check your local Xenobiology lab for your shipment.
tweak: Nanotrasen would like to remind you that BZ is meant for keeping slimes from moving or getting hungry. It is not for human use and may lead to hallucinations. Always practice workplace safety when handling dangerous gasses!
/:cl:

Features Allowed Edition

[why]: BZ has exactly one beneficial use. When it was created, it replaced Carbon Dioxide as the gas of choice for putting slimes into stasis, which pauses movement and hunger. Unfortunately, it was soon upended by Goof's Meme Freon and the canister you would find in Toxins was removed when Freon was made.
I have added a canister directly to the Xenobio labs on each map (except Omega) to encourage Xenobiologists to use them for their work. Currently, two maps (Meta and Pubby) also conveniently have a gas distribution system for their large chambers and the BZ Canister has been placed on top their respective connector ports, to again, encourage use. Box and Delta Xenoscientists will just have to make do and put on a gas mask to spread gas in their large containment.

And yes, of course, you could just open the canister in the hall and give everyone hallucinations. Nobody's stopping you from doing that either.

Currently nobody uses BZ and the one explicit use it has is not very visible. BZ should have some kind of use if it's going to continue to be in the code. It's never really ordered from cargo either (except mainly to grief, but I've never seen a single BZ release from cargo in all the time since Freon was merged).

### CODE REVIEW

**Comment by vuonojenmustaturska** [comment]
what is the benefit of putting a slime into stasis, does anyone do that ever

**Comment by optimumtact** [comment]
also why is it better than CO2?

**Comment by YakumoChen** [comment]
CO2 lost the functionality when it was moved to BZ, I believe?

Slimes in stasis do not get hungry, or angry, which means you can preserve backups of all the colors you make without having to worry about feeding them.

**Comment by YakumoChen** [comment]
``if(stat != DEAD)
-		var/co2_percentage =0
-		if("co2" in environment.gases)
-			co2_percentage = environment.gases["co2"][MOLES] / environment.total_moles()
-		var/stasis = (co2_percentage >= 0.05 && bodytemperature < (T0C + 100)) || force_stasis
+		var/bz_percentage =0
+		if("bz" in environment.gases)
+			bz_percentage = environment.gases["bz"][MOLES] / environment.total_moles()
+		var/stasis = (bz_percentage >= 0.05 && bodytemperature < (T0C + 100)) || force_stasis
 
 		if(stat == CONSCIOUS && stasis)
-			src << "<span class='danger'>High levels of CO2 put you in stasis!</span>"
+			src << "<span class='danger'>Nerve gas in the air has put you in stasis!</span>"
 			stat = UNCONSCIOUS
 			powerlevel = 0
 			rabid = 0``
Yeah here it is from the original BZ PR

**Comment by YakumoChen** [comment]
I mean I guess I could just revert it back to CO2 if I had to, but BZ is otherwise a completely useless gas, aside from the one interaction with lings that I only found out about specifically by searching BZ in the PRs list because it literally never comes up in game.

**Comment by 81Denton** [comment]
>It's never really ordered from cargo either

According to statbus, in January cargo ordered 2.999 nullcrates and only 2 BZ crates

People order more bicycles and toner crates than BZ oof

**Comment by YakumoChen** [comment]
I don't know if I should be more surprised that people have a reason to order BZ more then once a month or that people have ever had a reason to order the toner crate ever.

**Comment by Ordonis** [comment]
I am always in support of more chemicals I can release to cause chaos

**Comment by Barhandar** [comment]
BZ has another explicit function: mixing a bit of it into your airtank to experience hallucinations without having to take RDS.

Slimes already take ages to die from hunger but I do approve of more ways to cause chaos on station by accident or intention.

**Comment by YakumoChen** [comment]
The best part I find is that slimes in stasis don't move so I don't have to fiddle around with trying to catch them and I can keep them sorted out.

**Comment by praisenarsie** [comment]
@DaedalusGame quickly make BZ better before this gets merged so it will be too good to add to xenobio

**Comment by Cyprex** [comment]
BZ can also be used to create stimulum (Gunther has been trying do that recently for example.). I was unaware BZ prevents slimes from getting hungry, I would definitely use this on the long, lowpop terry rounds.

>Nanotrasen would like to remind you that BZ is meant for keeping slimes in stasis.
I would add ", preventing them from moving or becoming hungry".

>This is just going to be used to occasionally griff just like last time.
Nothing's stopping you from ordering it from cargo as is, and I have done so in the past.

**Pull request merged**
