### PR TITLE
Updates Kitchen Maints

### PR DESCRIPTION
**Pull request by Son-of-Space**
## About The Pull Request

Updates the maintenance areas on Meta and Delta to fit closer to modern development on the kitchen. Chefs can now use the areas to cook most things. Mostly added objects, but did some tweaking to the layouts on both to fit everything. Big things that were added were the oven and food processor.

Meta:
image

Delta:
image

## Why It's Good For The Game

Allows players to use these areas as intended, updated to fit with role design changes.

## Changelog

:cl:
qol: Contractors lost some appliances in kitchen maintenance on MetaStation, BoxStation, and DeltaStation
/:cl:

### CODE REVIEW

**Comment by Wallemations** [comment]
what are people meant to do with the two slabs of meat in delta?

**Comment by Wallemations** [comment]
Also, should Icebox's maint kitchen get an oven too?

image

**Comment by Son-of-Space** [comment]
Huh, I could've sworn when I checked it last it had it. I'll go back in now and make sure.

I was told by service mains that griddles are bad :tm: was I told wrong?

**Comment by Wallemations** [comment]
> I was told by service mains that griddles are bad ™️ was I told wrong?

Can't cook meat without them fron my understanding

**Comment by Dorsisdwarf** [comment]
> 

Well, you can with a grill.

**Pull request merged**
