### PR TITLE
Allows mulliganning into rev

### PR DESCRIPTION
**Pull request by Shadowlight213**
Mainly for testmerging to see how this goes.

:cl: optional name here
experiment: Rev is a possible option for the round to mulligan into
/:cl:

### CODE REVIEW

**Comment by Incoming5643** [comment]
:warning: Might work :warning: 

:grey_exclamation: But if all the heads die before conversion it'll probably end up a meme :grey_exclamation:

**Comment by KorPhaeron** [comment]
This just sounds like torment for security players and a punishment for working together in the only round types that ever mulligan (blob and wizard)

**Comment by jughu** [comment]
For a second i thought you was gonna add muligan on rev rounds
I mean people already hate rounds going into mulligan when the wizard/blob died and changeling memes traitortots everywhere its like using summoning gun 5x and you want add revmemes to it? They might aswell suicide

**Comment by jughu** [comment]
Inb4 crew offstation gets selected to be revhead and the round autoends anyways

**Comment by Shadowlight213** [comment]
I got tehsteveo to give the ok on it

**Comment by lzimann** [comment]
horrible idea, mulligan is already bad in blob/wizards, imagine in rev

**Comment by Aloraydrel** [comment]
good idea tbh

**Comment by KorPhaeron** [comment]
PR doesnt need to be open to be test merged, and "the crew you just gave guns and access to turns around and lynches you" sounds like a really sour way to end the round

**Comment by Thunder12345** [comment]
Instead of this, allow rev to mulligan into other modes, along with a button to allow admins to safely disable rev

**Comment by Shadowlight213** [comment]
@Thunder12345
We tried/looked into that. (By which I mean I accidentally turned mulligan for a rev round and promptly had to step away for a bit.) It's a far worse idea.
For one, the game doesn't de-Rev people if all the heads die, so all of them are antags with no purpose and they basically just kill new arrivals. Also, there's no indication that the opposing side has been defeated, so no one will call the shuttle because they'll believe it won't leave.

**Comment by Thunder12345** [comment]
Then make mulligan de-rev them if all the heads die, and send a CentComm message either congratulating the command staff on their victory, or inviting the crew to take on the task of running the station. Either way, it's not something that's going to happen if the round gets serious, it's more to stop the issue of the round being cut off 5 minutes in because the only revhead flashed a guy in front of sec and got his shit pushed in.

**Pull request closed without merging**
