### PR TITLE
Ghosts can now scan integrated circuits assemblies.

### PR DESCRIPTION
**Pull request by ghost**
When a ghost examines an assembly a "Get assembly scan." link will appear. The link opens a window like the circuit analyzer does with the code in it 

:cl:
add: Ghosts can now scan integrated circuits assemblies.
/:cl:

[why]: So that if someone spends a lot of time working on a circuit but gets killed before they finish it they can still get the circuit code and keep working on it in another shift.

### CODE REVIEW

**Comment by improvedname** [comment]
why even have circuit analyzers

**Comment by GunHog** [comment]
This will certainly increase circuit piracy significantly! (YARR!)

**Comment by improvedname** [comment]
>[why]: So that if someone spends a lot of time working on a circuit but gets killed before they finish it they can still get the circuit code and keep working on it in another shift.

Git gud

**Comment by kevinz000** [comment]
:-1: not for the feature but for the why.

**Comment by Bawhoppen** [comment]
Circuits were a mistake

**Comment by PKPenguin321** [comment]
I don't want ghost jews to steal muh circuits

**Comment by JStheguy** [comment]
It's perfectly balanced.
:+1: You can save your circuits even after death
:-1: Your circuitry designs are at risk of ghost piracy

**Comment by PKPenguin321** [comment]
Implying I die

**Comment by Ratvar** [comment]
Plus: you can copypaste suicide grenade wizzkill bots even if wiz gibs you.
Minus: everyone can copypaste suicide grenade wizzkill bots.
Result:  everyone can copypaste suicide grenade wizzkill bots.
Roll with it and see circuits slowly become another NTSL (aka removd), I guess?

**Comment by theo2003** [comment]
I'm starting to think this PR is not a good idea. It seems like it could make circuits gamebreaking. I may try to make it so that only players who built/edited the circuit can scan it if I can figure out how to do that but for now I'll close this.

**Comment by Ratvar** [comment]
they are alreeeady gamebreeaking

**Comment by PKPenguin321** [comment]
fuck u suicide grenades are already doable with signalers

**Pull request closed without merging**
