### PR TITLE
Hardsuit helmets protect against space again.

### LINKED ISSUE #45514: Hardsuits not protecting from pressure damage
Tested with CE's hardsuit and an engineer's hardsuit, we experienced pressure damage while in a vented room. Did not go into space so unsure if thermal damage is affected by this bug. This is new and may be caused by the test merges but I wouldn't know how to identify which of the three merges this is caused by.

Issue reported from  Round ID: 114264 (/tg/Station Terry [EU] [100% LAG FREE] [New-Dedi])

Reporting client version: 512.1464

### PR DESCRIPTION
**Pull request by TheChosenEvilOne**
## About The Pull Request
Fixes #45514

## Changelog
:cl:
fix: Fixed hardsuit helmets not protecting against space.
/:cl:

### CODE REVIEW

**Comment by MMMiracles** [comment]
😬

**Comment by Akrilla** [comment]
pls speedmerge it's kinda fucked

**Comment by 81Denton** [comment]
I suspect that removing this will let players knock off hardsuit/space helmets, but fixing the issue takes priority.

**Comment by TheChosenEvilOne** [comment]
> 
> 
> I suspect that removing this will let players knock off hardsuit/space helmets, but fixing the issue takes priority.
> It could probabaly solved by adding the SNUG_FIT trait during space helmet initialize().

The parent type already has SNUG_FIT.

**Comment by 81Denton** [comment]
Neat, even better

**Comment by MMMiracles** [comment]
yeah that was my bad when i was fixing the subtypes that had additional clothing_flags

**Pull request merged**
