### PR TITLE
Converts the atmos senstive component over to connect_loc

### LINKED ISSUE #56945: Atmos sensitive objects will get confused if the turf they're located on is deleted
## Round ID:

Not relevant, I'm doing this so I don't forget about the bug
## Testmerges:
See above

## Reproduction:
Place space vine on tile.
Delete tile, causing a plating to be created.
Set plating on superfire, so 1000000000k.
Watch as space vine sits unharmed in the chaos

### PR DESCRIPTION
**Pull request by LemonInTheDark**
## About The Pull Request

 Converts atmos senstive to connect_loc, does some general cleanup to the element, and makes it check the state of the tile the thing is on assuming creation didn't happen as a part of map loading

@Mothblocks This leads to a connect_loc element with about 5000 targets, will this cause trouble? 

## Why It's Good For The Game

Fixes #56945
Merges redundant code
Fixes a previously undocumented issue with atmos sensitivity and not testing stuff post mapload. I trust that mappers won't set up situations where things should be processing at mapload, as testing for it would do horrible things to init times.

## Changelog
:cl:
fix: Fixes some atmos senstivity stuff, it'll work more consistently now
/:cl:

### CODE REVIEW

**Comment by Mothblocks** [comment]
> This leads to a connect_loc element with about 5000 targets, will this cause trouble?

@ninjanomnom is adamant that it's not that big of a deal, so :shrug:

**Comment by LemonInTheDark** [comment]
the element is attached to some things that move quite often, like firebots. Guess it'll be ok then

**Comment by Mothblocks** [comment]
I don't know anything about BYOND, but if hash map writes aren't extremely cheap like in every other language, I'm going to cry.

**Comment by LemonInTheDark** [comment]
@ninjanomnom is there a way to do this without making a targets list that's 5000 entries long?

**Comment by LemonInTheDark** [comment]
it's trivial, thank the lord 
image

**Pull request merged**
