### PR TITLE
Items have a variable burn time

### PR DESCRIPTION
**Pull request by Ikarrus**
- Object burn times vary between 1x-2x the value set for var/burntime
  - This way they don't all burn up at the same time. For muh immersions.
- Examined ashes from burned objects will reveal what they used to be
- Plasma sheets can burn now

### CODE REVIEW

**Comment by optimumtact** [comment]
Wow we're apparently all expert forensic investigators  :P
:+1:

**Comment by Killbasa** [comment]
- Examined ashes from burned objects will reveal what they used to be

Heh, maybe just the material it was made out of would suffice.

**Comment by RemieRichards** [comment]
It should be consistent with Acid's grey goo drops, which tell you EXACTLY what they used to be.
so as it is now, it's good.

**Comment by Ikarrus** [comment]
if we want to refer to reality, burning most objects still makes it somewhat recognizable as the object it used to be. It just looks like ashes in game because we really can't be assed to make a destroyed/burned sprite for every item in the game.

**Comment by Razharas** [comment]
>Plasma sheets can burn now

Yep thats mergeble now

**Pull request merged**
