### PR TITLE
Fixed new charger power not working

### PR DESCRIPTION
**Pull request by carlarctg**
## About The Pull Request

Fixed new charger power not working

## Why It's Good For The Game

I think bugs are bad for the game sometimes

## Changelog

:cl:
fix: Fixed new charger power not working fior strange objects
/:cl:

### CODE REVIEW

**Comment by ZephyrTFA** [comment]
fix your WIGFTG

**Comment by carlarctg** [comment]
What

**Comment by KingkumaArt** [comment]
> What

the "why its good for the game" section ,he means

**Comment by carlarctg** [comment]
???????????????????????? ok lol?

**Comment by carlarctg** [comment]
i mean i made the og pr so im just insulting myself

**Comment by Jacquerel** [comment]
you can hoenstly just delete the why its good for the game section for simple bug fixes (mothblocks told me this in a dream) but you do have to explain what the bug was and how you fixed it in the PR body or maints will get suspicious

**Pull request merged**
