### PR TITLE
VR fix

### PR DESCRIPTION
**Pull request by DaxDupont**
[Changelogs]: # (Your PR should contain a detailed changelog of notable changes, titled and categorized appropriately. This includes, new features, sprites, sounds, balance changes, admin tools, map edits, removals, big refactors, config changes, hosting changes and important fixes. An example changelog has been provided below for you to edit. If you need additional help, read https://github.com/tgstation/tgstation/wiki/Changelogs)

:cl: Dax Dupont
fix: Fixes race condition caused by exiting the body while dying in VR.
/:cl:

[why]: Dying with no active mind in VR would cause a lack of clean up, allowing people to connect to bodies which are dead and thus ghost out when they move.

### CODE REVIEW

**Comment by DaxDupont** [comment]
@KorPhaeron this is the thing I was talking about i am a fucking idiot

**Comment by optimumtact** [comment]
that's not really a why

**Comment by AlexTheSysop42** [comment]
oh is that what caused that

**Comment by AlexTheSysop42** [comment]
one time this happened and when I came back my old body was catatonic and I was in someone else's body

**Comment by Grazyn** [comment]
What if your body dies while your mind is in VR? Would you be trapped in the cyberscape forever like in that one hellblazer comic?

**Comment by optimumtact** [comment]
you die in vr too

**Comment by praisenarsie** [comment]
IF YOU DIE IN THE GAME, YOU DIE IN REAL LIFE

**Pull request merged**
