### PR TITLE
Re-arranges Icebox Medbay to better facilitate multi-z

### PR DESCRIPTION
**Pull request by AlinaStarkova**
## About The Pull Request
It was something I was working on several months ago before I lost my home, and only now was able to do.
remaps Icebox medbay to put Virology and Morgue down below alongside Chemistry that was previously placed there, to fit with the theme: 
Chemistry below because of explosive hazard
Virology Below because of pathogen containment hazard
Morgue below because corpses icky

also added things that were seen on other maps but werent on icebox yet, such as the chemical storage (which i really love btw whoever added that to meta)

I discussed the design with Melbert and Potato Masher to fix some issues I initially glossed over, and they both seemed to like the redesign as well. Mothblocks as apparent med-main also looked at it and said it looked fine and lower level viro was a neat idea. everything discussed was in the discords mapping channel

## Why It's Good For The Game

because icebox despite all the flaws people keep criticizing it for, is basically our premiere multi-z map, yes there are others, yes the others tend to be liked more, but icebox is quite a good map for testing new multi-z department designs, as evidenced by the fact every department gets a multi-z overhaul every 3 months or so

MedbayIcePreviewTop

MedbayIcePreviewBottom

cute floor art:
MedbayIceBottomViro

## Changelog

:cl: Nari Harimoto
expansion: Centcom has approved the funds to re-arrange Icebox's medbay department with a new design that better facilitates multiple level functionality
/:cl:

### CODE REVIEW

**Comment by Edelor68** [comment]
That the main area with the beds is so unsymmetrical feels kinda weird for me, but maybe I just have to get used to it.

**Comment by AlinaStarkova** [comment]
> That the main area with the beds is so unsymmetrical feels kinda weird for me, but maybe I just have to get used to it.

symmetry is uncreative

**Comment by YakumoChen** [comment]
The unused space feels kind of wasted, just expanding medbay to be slightly more tediously _bigger_ without really making it _better_.

**Comment by YakumoChen** [comment]
image
kind of feel like there should be another door or entry here too.

**Comment by YakumoChen** [comment]
I can't say I like the stairs placement either but I can't think of a better place to put them for non-medbay morgue entry.

**Comment by YakumoChen** [comment]
image
I really think we should restore the little storage closet area that used this space with the box of lights and the heater, fire closet, etc instead of whatever this is

**Comment by AlinaStarkova** [comment]
> image I really think we should restore the little storage closet area that used this space with the box of lights and the heater, fire closet, etc instead of whatever this is with the CMO cubby

what? there was no storage closet there, that was the morgue...... which was moved down




> image kind of feel like there should be another door or entry here too.

nah, theres way too many doors around, we dont need to stagger a door or opening every 2 tiles in medbay, medbay is already the most open department on icebox

**Comment by YakumoChen** [comment]
> what? there was no storage closet there, that was the morgue...... which was moved down

Long before that there was a small public supply room just like the one in the port hallway, it contained things like a heater, spare lightbulbs, and a firecloset, IIRC

**Comment by AlinaStarkova** [comment]
> >what? there was no storage closet there, that was the morgue...... which was moved down
> 
> Long before that there was a small public supply room just like the one in the port hallway, it contained things like a heater, spare lightbulbs, and a firecloset, IIRC
> 
> >nah, theres way too many doors around, we dont need to stagger a door or opening every 2 tiles in medbay, medbay is already the most open department on icebox
> 
> Other departments don't have weird, elongated rooms with hallways wrapped around them. It feels awkward having to walk most of a screen to get into the treatment room from there.
> 
> The whole triage room kind of feels... pointlessly huge, honestly. Like, why does it take up that much space while having almost nothing there?

maptainers have mentioned in the past that they do NOT like straight hallways everywhere, a few small bends goes a long way of making a dept not square.

also the space is fine. room to setup more beds when theres lots of people to work with, or to store items and crap that inevitably comes through, especially when half the crew is loitering in medbay. its actually roughly the same floorspace as meta triage

**Review by Maurukas — CHANGES_REQUESTED** [review]
<details>
<summary> I really like this linear treatment center with various treatment areas and stations around it. This reminds me of actual ERs I've seen</summary>

image
</details>

<details>
<summary> This is a nice little touch </summary>

image
</details>

<details>
<summary> You've got pressure tanks here rotated to connect to pipes, but the pipes are not on layer 3, so the pressure tanks won't connect </summary>

These tanks are an utter pain and honestly need a complete refactor.
image
</details>

<details>
<summary> Doubled wire under a door in virology </summary>

image

</details>

<details>
<summary>
Missed bit of Mining area here in Viro. This is spawning a big chunk of active turfs.
</summary>

image

image
</details>

<details>
<summary> Medical secpost is in the CMO's office area </summary>
This is causing a duplicate APC warning as well.

image
</details>

<details>
<summary> Medical break room and bathroom are in the virology area </summary>

image
</details>

* The morgue needs an air alarm

Looks good otherwise. A much needed refresh for Icebox.

**Comment by AlinaStarkova** [comment]
map diff bot had a stroke, someone needs to restart it i think

**Review by Maurukas — APPROVED** [review]
Alright, looks handled.

With a big update like this please keep a look out for minor issues for a day or two. There's always something.

**Pull request merged**
