### PR TITLE
Fixes blood contract expiry

### LINKED ISSUE #22089: Blood contracts are temporary
Blood contracts and the bottle of mayhem both have the same duration, while blood contracts still keep someone marked for death even after the bloodbath effect runs off. This means that while missing the chainsaw and adminordrazine they normally have, the station still has the objective to kill them while they are marked.

### PR DESCRIPTION
**Pull request by Cyberboss**
Makes the bloodbath mineEffect waitfor = 0
Fixes #22089

:cl: Cyberboss
fix: Blood contracts now expire properly
/:cl:

### CODE REVIEW

**Comment by KorPhaeron** [comment]
Should probably make it not work on the user if it is gonna last forever

**Comment by Cyberboss** [comment]
This PR just expires the contract when the bloodbath expires. What do you
mean?

**Comment by KorPhaeron** [comment]
Oh I thought it made it not expire I should read. I would prefer it not expire personally

**Comment by KorPhaeron** [comment]
Unless that would make them invincible I guess

**Comment by Cyberboss** [comment]
yeah, it'd be kinda weird considering every single living player would be looking for that person forever

**Comment by KorPhaeron** [comment]
Having 60 seconds only would just encourage people to wait it out in a locker instead of doing anything though

**Comment by Cyberboss** [comment]
I could potentially refactor it to keep the effects for a given time period. Then we can tweak it in the future

**Comment by KorPhaeron** [comment]
Give me a bit to think about this

**Comment by KorPhaeron** [comment]
I'll try and rework this soon(TM)

**Pull request closed without merging**
