### PR TITLE
pAIs copy their master's languages, loses universal translator

### PR DESCRIPTION
**Pull request by JohnFulpWillard**
## About The Pull Request

This PR removes pAI's universal translator app. Instead they copy the languages of whoever imprints them, on top of their default languages (silicon ones, so Common, Uncommon and Robotic).

## Why It's Good For The Game

Universal Translator is seen as a necessity for pAIs to translate things for Foreigners, and I don't want to take that away, so instead pAIs will always know their base languages, and any languages their master knows.
The app itself essentially turns a pAI into a Curator, which kinda sucks as it takes away one of the main points of the Curator, being a translator for people who have no other option.
It also means pAIs can listen and talk in the native languages their master can, without having to buy the most expensive program in their shop. 

This is also the last agreed upon removal for language knowledge from the coderbus meeting, as far as I'm aware.

## Changelog

:cl:
balance: pAIs can no longer purchase the Universal Translator app.
balance: pAIs now copy the languages of their master upon imprint.
/:cl:

### CODE REVIEW

**Comment by TheVekter** [comment]
Lol double post but I talked to John a bit in coderbus and I get where he's coming from.

The idea is that he wants there to be a significant buy-in to knowing another language and "grabbing a pAI card to download a personality" doesn't fit that balance-wise. I'm explicitly for making it harder to learn languages cost-wise; I think that's generally a good idea and it provides a benefit for non-human players who are already at a disadvantage in other ways.

**Comment by YehnBeep** [comment]
> The idea is that he wants there to be a significant buy-in to knowing another language and "grabbing a pAI card to download a personality" doesn't fit that balance-wise.

With a large side helping of "punish anyone for not playing pAI or a pAI's master in minion style" as seems to be the other thing John wants to push very much in their recent PRs. Not everyone imprints/wants to imprint.

This also kills people getting pAIs to talk to spiders/pirates/etc that might want to RP a gimmick instead of going full combat mode and any other situation where such languages might arise. Not to mention if the gibberish-speaking permanent trauma is acquired and so on but I guess these will all be written off as "niche situations"?

👎

**Comment by JohnFulpWillard** [comment]
> With a large side helping of "punish anyone for not playing pAI or a pAI's master in minion style" as seems to be the other thing John wants to push very much in their recent PRs. Not everyone imprints/wants to imprint.

I've said again and again, I do not care for independent pAIs. I do not care if they continue to exist or die off, they are an unintentional creation and I do not consider it at all whatsoever in my PRs, as it is not what pAIs are made to do. I don't care that it exists, I just will not be bending over for them.

> This also kills people getting pAIs to talk to spiders/pirates/etc

You can speak to spiders by turning yourself into a flyperson with a Teleporter
You can speak to pirates by wearing a pirate hat from the Autodrobe
Alternatively you can play Curator

> Not to mention if the gibberish-speaking permanent trauma is acquired and so on but I guess these will all be written off as "niche situations"

They copy their master's languages so they should have it. If they get it mid-round then I suppose they'll have to wipe and download a new pAI, or maybe we should let it copy from requesting your DNA (if it's valid).

**Comment by YehnBeep** [comment]
> I've said again and again, I do not care for independent pAIs. I do not care if they continue to exist or die off, they are an unintentional creation and I do not consider it at all whatsoever in my PRs, as it is not what pAIs are made to do. I don't care that it exists, I just will not be bending over for them.

And this right here is basically the problem I have with your PRs and why I think they're bad for the game.

You don't care who you're running over. You don't have an eye towards how these things impact player experiences, so you're fine with just making things worse for many so long as it pushes your vision. Best case they might be neutral but these PRs are definitely worse than neutral.

Going to stop there since I could endlessly bring up situations we could quibble over but I think that's the core of it. And, well, I don't think "Oh you don't like it? Just play something else!" needs much explanation on why that's a nonconstructive attitude.

If the people playing matter at all, this PR and others like it are not good for the game. They're good for John's vision. Not the people on the ground floor.

**Comment by JohnFulpWillard** [comment]
> Going to stop there since I could endlessly bring up situations we could quibble over but I think that's the core of it. And, well, I don't think "Oh you don't like it? Just play something else!" needs much explanation on why that's a nonconstructive attitude.

Fact is, pAIs were made to be a personal AI. They were not originally meant to be independent mobs that people can infinitely respawn into. Players choosing to do that in-game is none of my concern, I just do not care if I obstruct anything from their experience of one when I am trying to make changes to the parts we actually do care about- pAIs who are actually personal AIs.

**Comment by YehnBeep** [comment]
> Fact is, pAIs were made to be a personal AI. They were not originally meant to be independent mobs that people can infinitely respawn into. Players choosing to do that in-game is none of my concern, I just do not care if I obstruct anything from their experience of one when I am trying to make changes to the parts we actually do care about- pAIs who are actually personal AIs.

But you affect people even that do play into the minion thing. But even for players that like doing this, pAIs are not always in a PDA (the issue with the PR previous), and do not always imprint (the issue here), and nuking the universal translator (with or without a master-language-copy) further limits the already-very-limited pAI role **even if they're playing the way you want them to play**.

These sort of things would be obvious if player experiences were a factor.

**Comment by JohnFulpWillard** [comment]
> do not always imprint (the issue here)

People playing a personal AI should imprint that is the first thing you do when you install a pAI, it's how you become the pAI's master. It's the whole point of pAIs. If a pAI is without a master then it is not how we are 'expecting them to play'.

**Comment by YehnBeep** [comment]
> > do not always imprint (the issue here)
> 
> People playing a personal AI should imprint that is the first thing you do when you install a pAI, it's how you become the pAI's master. It's the whole point of pAIs. If a pAI is without a master then it is not how we are 'expecting them to play'.

So, considering the PDA-plug-in PR as a parallel to this one. It would have been a good PR if it wasn't also nuking the messenger. This would be a good PR if it wasn't also nuking the translator.

In both cases, yes, they hurt people not playing in the way you want to them to play, but they both have a lot of bad effects even for those that are. I think consideration of player experiences would go a long way in bringing out the good of these PRs.

**Comment by SomeoneYouProbablyKnow** [comment]
The most common use case for Pai translators are captive xenos, the rest are unusual enough that the loss of the translator is not gonna be a big deal (it's gonna be a mess one way or the other and that's brilliant)

A potential lower efficiency replacement (Maybe a universal recorder module that needs tape aka other people) could be neat, after all as a pai (slaved or free one) talking is your biggest tool.

**Comment by TheVekter** [comment]
> > The idea is that he wants there to be a significant buy-in to knowing another language and "grabbing a pAI card to download a personality" doesn't fit that balance-wise.
> 
> With a large side helping of "punish anyone for not playing pAI or a pAI's master in minion style" as seems to be the other thing John wants to push very much in their recent PRs. Not everyone imprints/wants to imprint.

Somebody in Discord also mentioned this (might have been you? idk) and I actually went back in John's PRs to look into it; I can't find a single PR in the last few months that has anything to do with pAIs, so I have no idea where this concept comes from aside from confirmation bias.

**Comment by YehnBeep** [comment]
> > > The idea is that he wants there to be a significant buy-in to knowing another language and "grabbing a pAI card to download a personality" doesn't fit that balance-wise.
> > 
> > 
> > With a large side helping of "punish anyone for not playing pAI or a pAI's master in minion style" as seems to be the other thing John wants to push very much in their recent PRs. Not everyone imprints/wants to imprint.
> 
> Somebody in Discord also mentioned this (might have been you? idk) and I actually went back in John's PRs to look into it; I can't find a single PR in the last few months that has anything to do with pAIs, so I have no idea where this concept comes from aside from confirmation bias.

https://github.com/tgstation/tgstation/pull/76445

That's the one I was referring to. Not sure how you missed it as it's only a week old..? But it's a bit ancillary anyways. This PR is not good for players completely on its own merits; I just hoped drawing some parallels might lead to more constructive approaches.

> The most common use case for Pai translators are captive xenos, the rest are unusual enough situations that the loss of the uni translator is not gonna be a big deal (it's gonna be a mess one way or the other and that's brilliant)

pAIs don't have much going for them to begin with. Removing translator roles is a pretty big part of their identity, even if individual situations are niche. But also if you want to go down that line, pAIs in general are niche, there aren't many around and they don't see much use. ...But I would say that's all the more reason to not cut them down further.

**Comment by TheVekter** [comment]
> With a large side helping of "punish anyone for not playing pAI or a pAI's master in minion style" as seems to be the other thing John wants to push very much in their recent PRs. Not everyone imprints/wants to imprint.

I could only find one recent PR having anything to do with pAIs by John and it's generally unrelated to this one.

> You don't care who you're running over. You don't have an eye towards how these things impact player experiences, so you're fine with just making things worse for many so long as it pushes your vision. Best case they might be neutral but these PRs are definitely worse than neutral.

Just stop.

**Comment by YehnBeep** [comment]
Sorry, I am trying to be civil, but I am also going to be direct when these PRs have such negative effectives on players.

I also think they could be much more positive things with a bit more consideration. Hence my approach.

**Comment by SomeoneYouProbablyKnow** [comment]
> pAIs don't have much going for them to begin with. Removing translator roles is a pretty big part of their identity

You can so so much as a PAI. I've done so much as a Pai by just running my mouth. Being a glorified universal recorder is not integral to their identity. I mean it's neat but that's not even (idk all numbers are made up) 15% of what you can and should do as a pai.

**Comment by YehnBeep** [comment]
> I've done so much as a Pai by just running my mouth. Being a glorified universal recorder is not integral to their identity (Although gaslighting people who can't understand each other's languages is funny). I mean it's neat but that's not even (idk all numbers are made up) 15% of what you can and should do as a pai.

Not sure our points are contrary. Yes, pAIs are probably 80%+ chatbot/observer+ (made up number, likewise). So, again, taking away more from them doesn't make sense to me.

And with both this and the PDA PR, there just really doesn't seem to be a point to throw some little thing back in consolation for taking so much - even if the little thing is cool. If they were focused more on improving experiences, more on the "here's this cool thing", I think there's a lot of potential positive in them.

Wrapping it in so much negative, however, completely undoes it. And yes this is blunt and unkind. I'm sorry. Not really much choice when something with this much negative impact could be forced, though. (And for all I've done to argue against it, might be forced on us all anyways).

**Comment by SomeoneYouProbablyKnow** [comment]
I feel like this is just a reaction to something being removed or nerfed. I fail to see the negative impact. I don't think it's gonna prevent anyone from doing their thing as a pai and it might (might not but gotta wait and see) improve how people interact with languages.

The point of removing something is to give other cool things space to breathe, there's only so much game where they all have to fit. trimming; removing; streamlining are all important to making any cool thing actually cool.

Anyway imma go sleep but i gotta say you can be against the change without being "Blunt and Unkind" it really is a choice.

**Comment by YehnBeep** [comment]
Simply being against doesn't seem to do much here, many unpopular things get pushed anyways. So my only hope is to try to show where this is being negative, and hope that whomever might have authority other this will consider the people that the PR maker has said themselves they don't care about.

And, again, sorry for the bluntness, but that is their own words. If I got a little heated I'm sorry - but this sort of disregard for many people that would be affected does upset me.

**Comment by zxaber** [comment]
This ruins pAIs being used to communicate with xenobio xeno eggs, and that's about the only thing the xeno player has aside from standing still and waiting for containment to drop.

Yeah, "just play curator", but xeno eggs are so rare, and picking curator every round on the offchance that an egg spawns, is noticed by someone, and isn't immediately tided, sounds terrible.

**Comment by TheVekter** [comment]
> This ruins pAIs being used to communicate with xenobio xeno eggs, and that's about the only thing the xeno player has aside from standing still and waiting for containment to drop.
> 
> Yeah, "just play curator", but xeno eggs are so rare, and picking curator every round on the offchance that an egg spawns, is noticed by someone, and isn't immediately tided, sounds terrible.

I'm fairly certain being able to directly communicate with xenos was never actually intended and there's an argument to be had that it's not good game design. As much as people like being able to talk to them, we already get way too many instances of someone (understandably) killing a xenos that's gotten out and people griping that they weren't RPing with the giant human-murdering, face-destroying alien creature.

**Comment by GuillaumePrata** [comment]
> This ruins pAIs being used to communicate with xenobio xeno eggs, and that's about the only thing the xeno player has aside from standing still and waiting for containment to drop.

If this is a goal, it would be more interesting to have a physical object, like a Xeno Translator Helmet, spawn together with the egg.

The Xeno egg is a messy feature RP wise right now IMO, so some push towards a direction, Xenobiologists being tasked with communicating and teaching Xenos something while captive instead of Xenos just waiting to murderbone as an example, would be nice.

**Comment by TheVekter** [comment]
> The Xeno egg is a messy feature RP wise right now IMO, so some push towards a direction, Xenobiologists being tasked with communicating and teaching Xenos something while captive instead of Xenos just waiting to murderbone as an example, would be nice.

This isn't really related to this PR (so we should probably drop it after this), but we need more interesting things to do with the egg than "breeding a bunch of xenos that can eventually go apeshit on everyone when they inevitably get out".

**Comment by Ryusenshu** [comment]
at this point, you should really just come clear that you dont want languages being used anymore
cause doing it like this is just dishonest

**Comment by TheVekter** [comment]
> at this point, you should really just come clear that you dont want languages being used anymore cause doing it like this is just dishonest
> 
> edit: to clarify my point by removing people that speak languages you are also removing reasons to speak them in first place making them useless in the progress

This isn't a good faith argument. Why would this have anything to do with making languages used less often? If anything, it'll _increase_ their use because people will know others won't be able to eavesdrop on their conversations.

**Comment by SomeoneYouProbablyKnow** [comment]
> language use wont increase because this pr reduces the amount of people actually being able to use said languages (like the silicon one), taking away people that can be talked to in languages

Have you seen the incredibles? "If everyone is special, no one is", yeah the idea is to do this in reverse, if everyone has languages no one actually does. As to if it's going to work?? I don't think anyone can say with confidence but there's just one way to find out.

**Comment by Ryusenshu** [comment]
> > language use wont increase because this pr reduces the amount of people actually being able to use said languages (like the silicon one), taking away people that can be talked to in languages
> 
> Have you seen the incredibles? "If everyone is special, no one is", yeah the idea is to do this in reverse, if everyone has languages no one actually does. As to if it's going to work?? I don't think anyone can say with confidence but there's just one way to find out.

in my opinion, the problem is that there is no benefit in talking languages in the first place
the language menu is bad, and switching languages is a pain same with remembering all the prefixes
and then the limited application that happens now

even a mood buff if you are talking to a fellow lizard in lizard would be nice, just to have something going for it

the biggest issue with these language prs for me are that they are removing gimmicks left and right

**Comment by Ryusenshu** [comment]
> > the only thing this will possibly increase are "racegangs" , meta or not ... because you actually need to have lizards wanting to actually talk in lizard in the first place
> 
> Yes, that's the point? It's supposed to be a benefit of picking a non-human race that you can converse with other members of that race without people (usually humans) eavesdropping on you. This reads less like an actual complaint about the change and more like you're just upset that non-human players get something nice for once.

again, eavesdropping is a rumor and has nothing standing behind it

... and fun fact, i played non human for most of my playtime, so your "you hate non humans" dont work here

**Comment by SomeoneYouProbablyKnow** [comment]
> in my opinion, the problem is that there is no benefit in talking languages in the first place the language menu is bad, and switching languages is a pain same with remembering all the prefixes and then the limited application that happens now

True, that is also a problem, a radial menu would be nice, i love radial menus.

> even a mood buff if you are talking to a fellow lizard in lizard would be nice, just to have something going for it

Hey that could be neat, although mood can kindly fuck off entirely.
 
But both of those things are kinda out of scope of what's happening in this PR.

> the biggest issue with these language prs for me are that they are removing gimmicks left and right

Are you just scared of "removal"? Would adding a thing that would make languages totally redundant be a-ok since it doesn't say "remove"? The PR is removing some gimmick options and it's opening up space for other gimmick options (More and better ones i think)

**Comment by Ryusenshu** [comment]
> > in my opinion, the problem is that there is no benefit in talking languages in the first place the language menu is bad, and switching languages is a pain same with remembering all the prefixes and then the limited application that happens now
> 
> True, that is also a problem, a radial menu would be nice, i love radial menus.
> 
> > even a mood buff if you are talking to a fellow lizard in lizard would be nice, just to have something going for it
> 
> Hey that could be neat, although mood can kindly fuck off entirely.
> 
> But both of those things are kinda out of scope of what's happening in this PR.
> 
> > the biggest issue with these language prs for me are that they are removing gimmicks left and right
> 
> Are you just scared of "removal"? Would adding a thing that would make languages totally redundant be a-ok since it doesn't say "remove"? The PR is removing some gimmick options and it's opening up space for other gimmick options (More and better ones i think)

with the silicon pr we lost gimmick ais, that were speaking in languages here and then 
with this one we lose translator pais and "funny" ones

one pai example of mine is that i played a pun pun replacement and was speaking in monke in the bar
was pretty dope

if the gimmick will be "i speak something no one understands" and you find that funny, i guess thats your call

**Comment by SomeoneYouProbablyKnow** [comment]
> if the gimmick will be "i speak something no one understands" and you find that funny, i guess thats your call

But those are the examples you just gave me? Or do you think people just understand monkey language? 

In any case, i don't think i could change your mind on this and i've already said all i wanted to and more. Cheers and take care

**Comment by Ryusenshu** [comment]
> pun pun replacement

**Comment by TheVekter** [comment]
> again, eavesdropping is a rumor and has nothing standing behind it

???? How the fuck is it a rumor? Are you just wording this poorly?

> ... and fun fact, i played non human for most of my playtime, so your "you hate non humans" dont work here
> 
> edit: also did you just call the creation of metagangs the point? wtf

Metagangs aren't the same thing as natural groups that form within the game. A metagang is a specific group of people who know each other _outside_ of the game and intentionally group together in-game. I also don't really give a shit about them, it's natural that people who enjoy each others' company are going to interact more often in-game and as long as they're not using it for a mechanical advantage I don't give a shit.

What you're referring to is people of a specific race in-game interacting with one another without a human being involved.

**Comment by Ryusenshu** [comment]
> > again, eavesdropping is a rumor and has nothing standing behind it
> 
> ???? How the fuck is it a rumor? Are you just wording this poorly?
> 
Rumor as in "made up issue"

People dont talk about criminal things in the open, they either whisper or PDA 
But those points have been brought up before in the other pr
... not that it matters in the end

**Comment by chemistrymain2** [comment]
Has JohnFulpWillard ever made a good PR?

The answer is no, by the way. It was a rhetorical question.

**Comment by kinneb** [comment]
> Has JohnFulpWillard ever made a good PR?
> 
> The answer is no, by the way. It was a rhetorical question.

please refrain from acting like a hole was punched in your head

**Comment by ZephyrTFA** [comment]
> Has JohnFulpWillard ever made a good PR?
> 
> The answer is no, by the way. It was a rhetorical question.

Please refrain from making pointless and derogatory statements.

**Comment by AdipemDragon** [comment]
Instead of removing the whole thing, why not give the translator app exclusively the weird non-roundstart languages? That way it accounts for all those weird once in a while interactions some are grieving over this. 
(or something something tieing it to emagged pai's or whatever, unless that interaction is specifically only for stealing one's pAI and nothing else)

**Comment by Loafin34** [comment]
fuck them Pais, give them owner language so they can act as a translator for monke/foreigner, and galactic common. Pais are invincible talking boxes that serve no purpose than to be practically a ghost hanging over a crewmate's shoulder that can yell for help when they're too busy getting their ass beat. Holoforms are funny, but the fact that it's basically a positronic brain that can be made for less and does more is shit.

**Comment by Mothblocks** [comment]
I think pAI translation is on the same level as tape recorder translation, which I am fine with

I want other changes to pAIs (like forcing them to be more personal and removing their ability to detach from their owner and go anywhere they want) and I think that would solve the same problems this does for me. Also potentially requiring they download the specific languages rather than giving them a universal translator

**Comment by TheVekter** [comment]
> I think pAI translation is on the same level as tape recorder translation, which I am fine with
> 
> I want other changes to pAIs (like forcing them to be more personal and removing their ability to detach from their owner and go anywhere they want) and I think that would solve the same problems this does for me. Also potentially requiring they download the specific languages rather than giving them a universal translator

What about requiring the pAI's master to do an input in order to turn on free roaming mode? I like that feature and don't want to see it gone, but I'm also in agreement that it shouldn't be something the pAI should have control over.

**Comment by Mothblocks** [comment]
We talked over in Discord and I think I want the non-personal pAI gameplay to be split out into its own role that is not connected to any one person, we liked the idea of controlling the bots (configurable in their panel)

**Pull request closed without merging**
