### PR TITLE
fixes reclaim on dead hiveminds who have no client

### PR DESCRIPTION
**Pull request by ghost**
~~changelog: Reclaim works on dead hiveminds again.~~
No CL because this is only noticeable during code testing

### CODE REVIEW

**Comment by 4dplanner** [comment]
Just wondering, why didn't the previous version work?

**Comment by py01** [comment]
the .mind.last_death var didn't seem to update when a person dies, so i used .timeofdeath which worked correctly from my testing

**Comment by py01** [comment]
On further investigation: .mind.last_death only doesn't update for spawned humans without a client, so the live server actually doesn't have this as a bug. Though it makes testing easier so this should still be merged. .timeofdeath is identical to .mind.last_death just tied to the body instead of mind.

**Comment by 4dplanner** [comment]
ah cool, just worried I'd messed something up

**Pull request merged**
