### PR TITLE
Medullary Failure now has a maximum range

### PR DESCRIPTION
**Pull request by Kierany9**
Alt title: **Reduces levels of salt generated by Queen's third studio album**

## About The Pull Request

Gives Medullary Failure a maximum range of 7 (previously infinite) and prevents it from being used alongside Mind Control.

## Why It's Good For The Game

the people have spoken: it's not fun.
will probably replace with actual fun when life stops happening

## Changelog
:cl: Kierany9
balance: Medullary Failure now has a maximum range
/:cl:

### CODE REVIEW

**Comment by blessedmulligan** [comment]
this pull request has no weaknesses

**Comment by HomocidlePancakes** [comment]
Being able to make psy zombies from xcom instead of heart attacks when?

**Comment by ATH1909** [comment]
> Being able to make psy zombies from xcom instead of heart attacks when?

YES.

Maybe even ghost-controlled ones? If you wanted to make them carbons, maybe make the psi-zombies lose max health over time (until they turn to dust) (and/or be unable to be made from soulless corpses and/or have a visible beam connecting them to their hivemind host like in xcom?) as a balancing feature?

**Comment by GuyonBroadway** [comment]
As funny as it was forcing the captain ti hand in his alive club membership card from half the station away it sounds exactly as not funny as that one random heart attack event that someone tried to add.

**Comment by Shadowflame909** [comment]
First it was mind control. Now it's heart attacks.

This is a repeating trail that means one thing.

Maybe multiple offensive powers that are not game changing. Would be better for this mode

**Comment by ExcessiveUseOfCobblestone** [comment]
PR a removal for it, i'd be fine with that.

**Comment by anconfuzedrock** [comment]
I have been defeated

**Pull request merged**
