### PR TITLE
Revert "Removes emergency meetings"

### PR DESCRIPTION
**Pull request by Iamgoofball**
Reverts tgstation/tgstation#74437
# 24 HOUR RULE
# SELF-MERGE RULE
# CAP RULE
# ARMHULENN IS AN IMPOSTOR RULE

### CODE REVIEW

**Comment by Jacquerel** [comment]
among us

**Comment by RikuTheKiller** [comment]
maintainer battles do be unfolding

**Comment by Mothblocks** [comment]
After discussing with the player iamgoofball was permanently banned from the repository for this PR: https://github.com/tgstation/tgstation/pull/74435 and is no longger allowed to make ynay pull request

**Comment by tralezab** [comment]
## I see you too climb the ladder of chaos

littlefinger-baelish

**Comment by Iamgoofball** [comment]
@Mothblocks you can't keep the among us memes down

**Comment by RikuTheKiller** [comment]
> @Mothblocks you can't keep the among us memes down

except mothblocks tried reverting it, it was trez who goned it

**Comment by Jacquerel** [comment]
For the benefit of the maintainers, April Fools PRs will be labeled and closed. Key Holders are still able to test merge PRs that are closed, so this makes no difference to you, the author, assuming you were able to find a Key Holder to merge this PR in the first place. If you need to make updates to this PR, you can simply add to the branch, and when the TM updates it will use those changes, even if they do not show up to the PR.

**Pull request closed without merging**
