### PR TITLE
Adds NOT_QUITE_ABOVE_GAME_PLANE_BUT_JUST_ABOVE_EVERYTHING_ELSE_PLANE because of issues with FoV.

### PR DESCRIPTION
**Pull request by Iamgoofball**
## About The Pull Request

Adds NOT_QUITE_ABOVE_GAME_PLANE_BUT_JUST_ABOVE_EVERYTHING_ELSE_PLANE because of issues with FoV.

## Why It's Good For The Game

Maintainer request to "ship it". 
Discord_bc2wPEx0Ao

Will be used to properly fix https://github.com/tgstation/tgstation/pull/66620

## Changelog
:cl:
code: Adds NOT_QUITE_ABOVE_GAME_PLANE_BUT_JUST_ABOVE_EVERYTHING_ELSE_PLANE because of issues with FoV.
/:cl:

### CODE REVIEW

**Comment by LemonInTheDark** [comment]
This is a crime

**Comment by optimumtact** [comment]
it also doesn't have a purpose

**Comment by Y0SH1M4S73R** [comment]
You didn't even give this new value to anything.

**Comment by Iamgoofball** [comment]
did we figure out a better fix?

**Pull request closed without merging**
