### PR TITLE
Changes some << to to_chat

### PR DESCRIPTION
**Pull request by Core0verload**
Some `<<` used to send texts to chat have somehow escaped the extermination. This PR hunts down the last of their kind.

Would be really helpful when #26542 will get merged.

### CODE REVIEW

**Comment by lzimann** [comment]
thanks

**Comment by Core0verload** [comment]
I just really want to see a proper HTML chat in SS13 in my lifetime.

**Comment by Cyberboss** [comment]
We should really gitban << somehow

**Comment by lzimann** [comment]
@Cyberboss I don't think there's a way to effectively do that. You could block `<< "string"`, but it won't get variables/procs that would return a string. And the `<<` is also used in file operations, sounds, etc.

**Comment by Cyberboss** [comment]
What I'm thinking I'd we could whitelist 1 file that has the operator and
then do something like.

```
/proc/OutputRaw(target, data)
    target << data
```

So that way, future contributions can't accidentally slip in <<'s

**Comment by Core0verload** [comment]
Better make it a define then. We don't need any extra overhead. And make it detect only new `<<`s.

**Comment by BlueNexus** [comment]
You could do what baystation did.

**Pull request merged**
