### PR TITLE
Fixes the name conflict between the two different kinds of black powder in a different way

### LINKED ISSUE #47281: Black Powder is Impossible to Obtain.
For some reason, black powder has become black CRAYON powder. While it appears to be named Black Powder, it has the functionality of black crayon powder.

This means no black powder bombs and possibly cherry bombs outright don't work.

### PR DESCRIPTION
**Pull request by ATH1909**
## About The Pull Request

Closes #47286 (it's an alternative to that PR).

It takes necromanceranne's suggestion (from here: https://github.com/tgstation/tgstation/issues/47281) and renames the explosive kind of "black powder" to "gunpowder", so that its name won't conflict with the name of the kind of "black powder" that dyes things black.

## Why It's Good For The Game

Fixes https://github.com/tgstation/tgstation/issues/47281.

## Changelog
:cl: ATHATH
tweak: Renames the explosive kind of "black powder" to "gunpowder", to avoid confusion with the kind of "black powder" that dyes things black.
/:cl:

### CODE REVIEW

**Comment by Fikou** [comment]
wtf black powder is the soul name

**Comment by Krysonism** [comment]
> wtf black powder is the soul name

Agree, rename the dye powder instead.

Call it "Congo dust" or something.

**Comment by kriskog** [comment]
If you are doing opposing PR's, add a closes #otherPR

**Comment by ATH1909** [comment]
> If you are doing opposing PR's, add a closes #otherPR

How/where do I do that?

**Comment by kriskog** [comment]
Anywhere in the OP, just like the fixes keyword.

**Pull request merged**
