### PR TITLE
Remove a bunch of useless .0 in vars

### PR DESCRIPTION
**Pull request by bear1ake**

### CODE REVIEW

**Comment by RemieRichards** [comment]
Stupid decompiler.
All byond numbers are floats so the decompiler added .0 to EVERYTHING that wasn't already X.Y

**Comment by Core0verload** [comment]
Is the BYOND decompiler still available? I want to look at it's source code.

**Comment by RemieRichards** [comment]
@Core0verload don't believe it was ever released publicly, since it's only use in SS13 history was illegal

**Comment by Mloc** [comment]
the decompiler only worked for an older version of the dmb format anyway, wouldn't work at all on modern dmbs

**Comment by Core0verload** [comment]
Modern .dmb uses some sort of encryption. I think with encryption removed we could use decompiler from old version with minimal changes. And, as recent Goonstation sprites leak shows, BYOND's encryption isn't that hard to remove.

**Comment by Miauw62** [comment]
sprites and .dmb are VERY different.
sprites are stored in the .rsc, which is transmitted to all clients so they can actually show the sprites locally, so theyre super ez to get.

**Comment by Core0verload** [comment]
.dmb and clientside .rsc are encrypted with the same algorithm I think. Of cours BYOND wouldn't send server's code to client, but there are other ways to obtain compiled code.

**Comment by Chnkr** [comment]
> Is the BYOND decompiler still available? I want to look at it's source code if possible.

I'm not sure if the decompiler(s) have ever been made public, i know that Tobba used to have some tool somewhere to show opcodes and such.

>  BYOND's encryption isn't that hard to remove.

The encryption on the `.rsc` file is just to stop people from getting them without effort, it's not the best solution but it works, if you spend some time reverse engineering the internals using IDA or any other similar tool you can easily write a simple tool to extract all items inside the `.rsc` but if you really want to grab the files from the `.rsc` without any effort, find a server that has the webclient enabled and just see what's being sent to your client, since the server just sends you `.dmi` files.

**Comment by Xhuis** [comment]
conflict city yo

**Comment by bear1ake** [comment]
@Xhuis i'll fix it

**Comment by bear1ake** [comment]
Fixed. Codebase need it?

**Comment by Xhuis** [comment]
what i mean is that it'll probably conflict with most if not all of the open PRs once this gets merged
still it's a good change so :+1:

**Pull request merged**
