### PR TITLE
Removes salt-shaker from maint loot

### PR DESCRIPTION
**Pull request by Bawhoppen**

### CODE REVIEW

**Comment by WJohn** [comment]
We need more salt, not less!

**Comment by Bawhoppen** [comment]
why would you rename my PR this is madness

**Comment by as334** [comment]
:salt:

**Comment by Bawhoppen** [comment]
I made them (spawn) I can destroy them

**Comment by Cheridan** [comment]
Sorry bawhoppen but like all good creations, yours has gone rogue and now seeks to destroy you.

**Pull request merged**
