### PR TITLE
Adds prisoner ID's to gen pop lockers on northstar. Also renames the door to "Gen Pop"

### PR DESCRIPTION
**Pull request by rageguy505**
## About The Pull Request
Adds prisoner ID's 1-6 inside the gen pop lockers
Also renames the door to be more clear its genpop.
## Why It's Good For The Game
Its not obvious what you're supposed to do with northstar cell times. Theres no prisoner id's nearby to use for the genpop, the nearest being the prisoner ID's that are used for the gulag or perma.
Also cheshify said go ahead.
## Changelog
:cl:

fix: Adds prisoner ID's inside the gen pop lockers on the Northstar. Also renames the holding cells to Gen Pop.
/:cl:

### CODE REVIEW

**Comment by rageguy505** [comment]
im not sure why it says that Tcomms was changed, this is a freshly updated from upstream branch that I'm using.

**Comment by SyncIt21** [comment]
Put "North Star" somewhere in your PR title. from your title i assumed you were changing the gen pop closets all over.

**Comment by BlueMemesauce** [comment]
The PR is reverting my tcomms PR #74816
Not sure the best way to do it, but you could just remake it since it's a simple PR

**Comment by rageguy505** [comment]
> The PR is reverting my tcomms PR #74816 Not sure the best way to stop it from doing that, but you could probably just remake it since its only two changes

Yeah I'm confused why, I updated and made a branch right before just adding a couple id's. I'll see if I can deal with it somehow

**Comment by rageguy505** [comment]
ill draft it and then sleep on it then

**Comment by Jolly-66** [comment]
> Put "North Star" somewhere in your PR title. From your title i assumed you were changing gen pop closets all over.

To piggyback off this comment, you *should* include it in your CL as well, since CL is player-facing information. By saying "Added X to area", its vague and not super helpful.

**Comment by rageguy505** [comment]
thanks san for helping me fix it

**Pull request merged**
