### PR TITLE
[READY] Updates most lavaland ruins (now without syndi sleeper removal)

### PR DESCRIPTION
**Pull request by nemvar**
## About The Pull Request

Updates most lavaland ruins so they better fit with surrounding enviroments.

## Why It's Good For The Game

I tried to remove as many straight lines and other unimmersive weirdness as possible. The result should be a generally better look of the affected ruins.

## Changelog
:cl:
tweak: Tweaked most lavaland ruins to better merge with the enviroment.
/:cl:

### CODE REVIEW

**Comment by nemvar** [comment]
Wait a minute, I messed up the stasis bed sprites somehow...

**Comment by HomocidlePancakes** [comment]
Why removes sleepers from there? It’s a self-contained autism fort so they don’t have to be in line.

**Comment by nemvar** [comment]
I explicitly told you the reason. This ruin acts as a sort of tutorial to the normal station stuff. It's stupid to keep no longer supported mechanics around in tutorial ruins.

If we were to, for example, remove pacman from the station, I would also replace the pacman on charlie station. It only makes sense that tutorials get updated to the reality of current gameplay.

You are just going 'REEEEE, change bad' without considering why the change is being made. This is most obvious by asking for reasons even though I fucking stated them. Please refute the argument instead of deflecting.

**Comment by HomocidlePancakes** [comment]
I think I can write a paragraph or too about how it's a tutorial ruin for other things but meh. Just add a couple of extra medkits there and it will be good.

Also silently doing 👍  and 👎  is dumb.

**Comment by Daxxed** [comment]
If this makes the garbage ruins take up even more space and thus cost us tendril and megafauna spawns no thanks.
If it doesn’t apologies for misunderstanding.
Want my full support ? Remove honk & xeno ruin.
They have OP loot requiring 0 effort to get and are so HUGE they cost you a spawn or two guaranteed.

**Comment by Shadowflame909** [comment]
Still, stasis is unloved.

Fuck it.

**Comment by datorangebottle** [comment]
> Want my full support ? Remove honk & xeno ruin.
> They have OP loot requiring 0 effort to get and are so HUGE they cost you a spawn or two guaranteed.

b-but muh honk staff

**Comment by Daxxed** [comment]
> 
> 
> > Want my full support ? Remove honk & xeno ruin.
> > They have OP loot requiring 0 effort to get and are so HUGE they cost you a spawn or two guaranteed.
> 
> b-but muh honk staff

Yes your wall penetrating taser that travels +- 250 tiles and rechargers by itself fast enough to lock a person down and just requires you to walk in, pick it up and walk back out is defenitely balanced and should NOT be removed at all /s

**Comment by datorangebottle** [comment]
> Yes your wall penetrating taser that travels +- 250 tiles and rechargers by itself fast enough to lock a person down and just requires you to walk in, pick it up and walk back out is defenitely balanced and should NOT be removed at all /s

Twas humor, my friend.

But anyone using the honk staff to actually hurt people // validhunt should be gibbed.

**Comment by Daxxed** [comment]
> 
> 
> > Yes your wall penetrating taser that travels +- 250 tiles and rechargers by itself fast enough to lock a person down and just requires you to walk in, pick it up and walk back out is defenitely balanced and should NOT be removed at all /s
> 
> Twas humor, my friend.
> 
> But anyone using the honk staff to actually hurt people // validhunt should be gibbed.

Honestly if I could code I would put it behind a difficult megafauna like colossus or bubblegum, or even add a new fightable honkmother. But sadly I am clueless when it comes to that.
It frustrates me alot though that the best lavaland loot is not dependant on skill and requires little effort to get too ( Honk staff, hierophant, other ruin loot, etc )

**Comment by datorangebottle** [comment]
> It frustrates me alot though that the best lavaland loot is not dependant on skill and requires little effort to get too ( Honk staff, hierophant, other ruin loot, etc )

Are you seriously trying to tell me that the hierophant takes no effort to defeat?

Because I(and many, many other people) have never defeated it.

**Comment by Daxxed** [comment]
> 
> 
> > It frustrates me alot though that the best lavaland loot is not dependant on skill and requires little effort to get too ( Honk staff, hierophant, other ruin loot, etc )
> 
> Are you seriously trying to tell me that the hierophant takes no effort to defeat?
> 
> Because I(and many, many other people) have never defeated it.

I said little effort, seen people kill it consistently as ashlizard with a spear.
But my main point was that the boss is guaranteed to spawn every shift and it only has a single item as drop, meaning you can't be unlucky and get a shitty weapon ( unlike most megafauna ).

**Comment by datorangebottle** [comment]
> I said little effort, seen people kill it consistently as ashlizard with a spear.

Yes, because one or two robust as hell people being able to kill the hiero with a spear makes it take little to no effort.

> But my main point was that the boss is guaranteed to spawn every shift and it only has a single item as drop, meaning you can't be unlucky and get a shitty weapon ( unlike most megafauna ).

This is a much better point, yeah. It's a guaranteed drop, so you always get something good for defeating hiero. (IMO that's how it should be for all of them, because they're fucking hard to kill. Imagine getting ash drake potion and getting lava immunity, or Colossus and getting an anomalous crystal. FUCK. That's for another PR though.)

**Comment by BeloneX** [comment]
> 
> 
> > It frustrates me alot though that the best lavaland loot is not dependant on skill and requires little effort to get too ( Honk staff, hierophant, other ruin loot, etc )
> 
> Are you seriously trying to tell me that the hierophant takes no effort to defeat?
> 
> Because I(and many, many other people) have never defeated it.

blood drunk and hierophant are literally baby shit.

**Comment by FloranOtten** [comment]
Stealth syndi nerf tbh.

**Comment by Shadowflame909** [comment]
Syndicates are an auto-self sleeper people nemvar!

With this logic, we might lose the syndicate sleeper on the nukie shuttle. Which would be very silly considering the bomb implants inside those folks.

**Review by ShizCalev — CHANGES_REQUESTED** [review]
atomize it.

**Comment by CRITAWAKETS** [comment]
The hierophant is considered one of the hardest megafauna. The fuck yall on about?

**Comment by optimumtact** [comment]
can you open a new pr please, I don't want to merge this one and get yelled at by misinformed people

**Pull request closed without merging**
