### PR TITLE
Air Alarm O2 sensor settings change

### PR DESCRIPTION
**Pull request by kingofkosmos**
The air alarms used to notify if the air O2 somehow miraculously raised above 135 % and alert at 140 %, while getting it above 100 % was impossible.

Now it notifies mildly if it's 100%, which in practice is never. Which is fine imo since pure O2 isn't poisonous or flammable in itself so its overabundance is not a big danger.

**New air alarm O2 sensor settings:**
newairalarmo2sensor

### CODE REVIEW

**Comment by xxalpha** [comment]
100% O2 atmos is actually dangerous.

**Comment by Alek2ander** [comment]
These aren't percentages. Partial pressures are the the pressures individual gasses would have if there were no other gasses in the same volume.

**Comment by kingofkosmos** [comment]
Can you somehow get over 100 % in game? Because I couldn't.

**Comment by Cheridan** [comment]
These are indeed partial pressures, based on the comments.

**Comment by kingofkosmos** [comment]
Damn, I guess you're right. Before I tried opening a canister of O2 and it was just 75 %, but now that I tried spawning into the O2 atmos room, it was actually alerting about the O2! I stand corrected.
nimeton

**Pull request closed without merging**
