### PR TITLE
Updates self examine to properly show which limbs are bleeding

### PR DESCRIPTION
**Pull request by ghost**
30 damage is the limit on a limb for it to bleed, so self-examining will now say which limb is bleeding when it actually is. Also changed the burn values a bit higher so it's more obvious when you're seriously hurt on a limb.

Brute damage > 0: "bruised"
Brute damage > 30: "bleeding"
Brute damage > 50: "mangled"

Burn damage > 0: "numb"
Burn damage > 20: "blistered"
Burn damage > 40: "peeling away"

### CODE REVIEW

**Comment by Deantwo** [comment]
:+1:

**Comment by RemieRichards** [comment]
Conflicts with #7700 just to let you know.

**Comment by Jordie0608** [comment]
Changelog

**Comment by paprka** [comment]
Gonna let remie finish his thing first, this is a simple change

**Comment by Iamgoofball** [comment]
@paprka rip in pieces this pr ever being done

**Pull request closed without merging**
