### PR TITLE
Ascended cult icon no longer remains on deconverted cultists

### LINKED ISSUE #40631: Cult halo doesnt go away on deconvert
Issue reported from  Round ID: 94777 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 512

image

### PR DESCRIPTION
**Pull request by optimumtact**
Fixes #40631

### CODE REVIEW

**Review by ShizCalev — CHANGES_REQUESTED** [review]
This is all duplicated for cult/master. Clean that up too please.

**Comment by ShizCalev** [comment]
@AnturK

**Comment by optimumtact** [comment]
Ironic

**Comment by Cyberboss** [comment]
:big_brain:

**Comment by Cyberboss** [comment]
Your PR is getting old. Either Travis CI is failing, it is still labelled work in progress (change this by adding `[READY]` to the start of your title), or there are unaddressed change requests. This may be closed soon to free up space on our tracker if it remains idle. In the event that it is, please ask in #coderbus on Rizon for it to be reopened once you have resumed work on it.

**Comment by optimumtact** [comment]
Don't stale me thot I leave yoru stuff open for months

**Comment by Cyberboss** [comment]
💪

**Comment by subject217** [comment]
What's the way to move forward on this? It is actually a pretty big issue in cult lategame, as deconverted people are left with a huge VALID sign on their heads. The only thing I can do in the interim is manually rebuild the icons on people ingame when this happens to them, which is hardly a solution at all.

The same "fix" gets PRed and closed for the same reasons every time.

I took a glance at doing this with human overlay procs and it looked to me like you'd need a new proc entirely as none of the existing ones cover this sort of thing, and there's also the issue that it's not just used on human type mobs, the overlay is applied to every cult mob. 

Since this is technically "my thing" and it seems like I'm the only one who both understands it and actually cares I'm willing to put effort into learning how to get it working in a way that makes more sense code wise, but I'm not actually sure what that looks like, because of my lack of knowledge. So if someone could at least give me an idea of what to do I can give it a shot.

**Pull request closed without merging**
