### PR TITLE
Buffs the bioterror kit

### PR DESCRIPTION
**Pull request by 81Denton**
:cl: Denton
tweak: There are rumors of the Tiger Cooperative adding a "special little something" to some of their bioterror kits.
/:cl:

### CODE REVIEW

**Review by ShizCalev — APPROVED** [review]

**Comment by Qbopper** [comment]
I've received reports of armed attacks on shipments. There's not enough vaccine to go around, and the underclasses are starting to get desperate.

**Comment by QualityVan** [comment]
Of course they're desperate; they can smell their deaths, and the sound they'll make rattling their cages will serve as a warning to the rest.

**Comment by Kromgar** [comment]
This should have a mene tag

**Comment by Shadowflame909** [comment]
Even though this is a shitpost pr I can actually see this being useful. If you want to stealth ops, poison those pineapples with that one instant cuck disease. It'll be a joke inside of a joke. You ate pineapple pizza, and you got poisoned. Yeah, it works in some level of another. I'd merge it!

**Comment by Therapist1** [comment]
only a terrorist organization could stoop to such levels

**Comment by Anonmare** [comment]
Mmm. I hope you're not underestimating the problem. Intelligence suggest they're behind the problems in Sybil.

**Pull request merged**
