### PR TITLE
Station goals fixes

### LINKED ISSUE #20414: DNA Vault is uncompletable.
dna vault
failed

2 hours of extended as AI for this shit...

### PR DESCRIPTION
**Pull request by AnturK**
- Spelling and formatting fixes
- Better lasery beam for meteor shield

Fixes #20414

### CODE REVIEW

**Comment by Repukan** [comment]
How do you even set up the shields?

**Comment by AnturK** [comment]
Just order them,drag them out and click them to activate. Alternatively activate remotely through the console.

**Comment by RemieRichards** [comment]
@AnturK now is the time to fix the ```fillers``` bullshit.
like you were supposed to.

**Comment by Ergovisavi** [comment]
One piece of feedback for that round was that the amount of plants required for the DNA vault was excessive and seemed to take a really long time compared to the other tasks; But that's probably out of the scope of this PR.

**Comment by AnturK** [comment]
Was about to PR just that.

**Comment by AnturK** [comment]
Remie, it's kinda impossible to do the horseshoe shape without that ? Byond bounds are rectangular.

**Comment by RemieRichards** [comment]
when the heck did it become a horseshoe shape.

**Comment by AnturK** [comment]
I did the BSA using the bounds, the dna vault is the irregular one.

**Comment by A-t48** [comment]
Thank you.

**Pull request merged**
