### PR TITLE
Protolathe efficiency change

### PR DESCRIPTION
**Pull request by LatD**
Alternative to #16393
Fixes one nano manipulator upgrade to protolathe not doing anything.

Currently the reductions to original item costs are 25% (nano), 50% (pico) and 62.5% (femto).
This changes the reductions to 20% 40% 60%. A minor nerf but also allows easier change of these values if needed as now the efficiency is a multiplier: 1; 0.8; 0.6; 0.4 and not 2 4 6 8.

Also makes printing multiple items faster. Making 5 items takes as long as 3.6 single items and 10 items as long as about 6 single items. Single item build times are also slightly slower as they work with that same efficiency coeff. Making 5 or 10 items is mostly used when making tens of parts to upgrade the station and this is to make those long wait times a bit shorter.

I hope I did everything correct here. This is mostly to give a more realistic alternative to the massive R&D nerf and just to give an idea of using efficiency coeff as a multiplier which can easily be changed unlike those 2 4 6 8 values. This can later be changed in other machines as well.
That other PR also has the huge nerf of making every sheet give only 1000 units instead of 2000. 1000 is better than 2000 but would require a rebalance of nearly every items' cost. 

(I'm also thinking about making a bigger R&D level update in May/June/July if I get some other science players and coders to give feedback as well. This cost rebalance and making sheets only 1000 could be also changed at that time.)

### CODE REVIEW

**Comment by AlexanderUlanH** [comment]
:+1:
Honestly I wouldn't worry about rebalancing materials until we know what's happening with cargo.

**Comment by Core0verload** [comment]
Better than Kor's "remove the fuck out of it" approach to balancing.

**Comment by TheNightingale** [comment]
:+1: It's more balanced than Kor's. (I'd suggest 20%-35%-50% reduction, though; 60% isn't much off 62.5%.)

**Comment by KorPhaeron** [comment]
Yeah this is still more or less doubling materials that you already doubled from the ORM

**Comment by LatD** [comment]
Let's see the numbers. We're had protolathe upgrades for years, long before Goof made ORM upgrades and T4 last summer. 

Let's now consider upgrades to T3 since that's the most common one. ORM becoming upgradable gave 3 times more minerals than before.

Then ORM was nerfed and now it's 1.8 times more minerals. 
Then asteroid was changed to lavaland, causing the number of ores coming to station getting about halved. This is an estimate as a scientist who's been working a lot in R&D for the last 1.5 years. Exact numbers are really hard to give.
This PR makes everything 20% more expensive on T3.

When compared to pre-ORM nerf (ores going 3x), effective number of minerals drops to 24% (ores-to-sheets drops 40%, prices going up 20%, number of ores drops 50%).
When compared to ORM before Goof even added the upgrade thing (ores being 1x), effective number of minerals is 72% (ores-to-sheets going up 80%, prices going up 20%, number of ores drops 50%) of the number of minerals we were getting for years before that ORM became upgradable. So even with this PR we're going way below those values.

If the miners learn to be better on lavaland and it becomes easier to work we'd get closer to those original ORM numbers which would then be 100%.

**Comment by KorPhaeron** [comment]
http://i.imgur.com/2iAiZN7.png

It's still easy as shit to get all your materials in less than 10 minutes as one guy, never mind three.

>it's been in for years

Science has been powercreep for years. The prices have not changed in the recipes since they were added, and they were never designed around upgrades at all. You are doubling the materials, you've just been doing it for a very long time now.

**Comment by LatD** [comment]
That just sounds like you're never even played science. There are round all the time which have 3 non-antag miners and last +1 hour and miners never bring back any minerals. Like I've said, the average number of diamond ores 3 miners manage to bring back during one hour is about 5. And of course good miners bring minerals if they know what they're doing. Stop assuming every miner knows how to mine like the creator of lavaland or powergame like Mekhi and don't punish R&D when mining is bad.

**Comment by PKPenguin321** [comment]
The point is that R&D kinda needs to be "punished." It's been due for a serious nerf for ages.

**Comment by KorPhaeron** [comment]
>a good miner can mine really fast but not everyone is a good miner

Isnt that a good thing though? For there to be a learning curve and a reward if everyone is working competently?

"but what if the other guy isnt good!" has lead to ss13 being a series of enclosed, boring minigames that mean you never have to leave your box until you're killing someone

**Comment by duncathan** [comment]
Other one was merged

**Comment by Core0verload** [comment]
Unlike the other one, this doesn't suck.

**Pull request closed without merging**
