### PR TITLE
Double evacuation fix #54316

### LINKED ISSUE #54316: 2 escape shuttles arrived with some delay, the second one ended the round
## Round ID: 
#148075 [Round](https://sb.atlantaned.space/rounds/148075) 

## Reproduction:

A shuttle call happen, another shuttle was bought within about a minutes time, and then called later. The first one arrived, departed, and landed at centcom without ending the round, the second shuttle, which was the SSShuttles "emergency" shuttle, spawned after a delay, arrived, and ended the round.

### LINKED ISSUE #54334: Shuttle System Bug Early Launched and Early Docked with station before Round Ended
## Round ID: 
[148100](https://scrubby.melonmesa.com/round/148100) 
Manuel

## Reproduction:
PubbyStation - Secret Extended round. Long Duration as per average Manuel Rounds. No big important admin buttons were pushed to my understanding that warranted or caused what happened though some typically mild adminbus was present which will be described.
Shuttle Early leaves station (Time to Depart Countdown doesn't finish). And with a 1:40+ left on the ESC timer arrives at station prompting me to force end round early to prevent EORG

Close to round end the only admin pressed things included spawning a few mobs, popping a sentience balloon, and announcing a Command Message, intent was for d-chat to participate in some EORG after shuttle docked and round end had officially been declared. Round had to be ended Early to prevent EORG (and shuttle had officially docked by this point)

### PR DESCRIPTION
**Pull request by Dennok**
## About The Pull Request

Old shuttle removed now

fix #54316
fix #54334

Forgot to add `replace` flag to shuttle loading on buying.
Now it remove old shuttle when you buy new.

## Why It's Good For The Game

Bugs is bad

## Changelog
:cl:
fix: Double evacuation fixed.
/:cl:

### CODE REVIEW

**Review by Mothblocks — DISMISSED** [review]

**Comment by LemonInTheDark** [comment]
Kind of a hacky fix, but this would prevent that issue. I'm weary of closing the issue tho, cause this doesn't resolve whatever the source of that was

**Comment by Dennok** [comment]
I have zero idea about source,
but that i modified load proc and it don't replace old shuttle by default, one of it. 
I just return work to previous state where it replace shuttle, like intended before.

**Comment by Fikou** [comment]
can you fix merge conflict

**Comment by Dennok** [comment]
> can you fix merge conflict

Yes

**Review by Cyberboss — APPROVED** [review]

**Pull request merged**
