### PR TITLE
Reverts shitfuck typecache chain

### LINKED ISSUE #74907: Storage datum can_hold typecaches are incomplete.
## Commit thing was broken on:
https://www.github.com/tgstation/tgstation/commit/46b2319559c951c04bd2fd42f6542daa69a19756
image

## Commit thing was not broken on:
https://www.github.com/tgstation/tgstation/commit/addf5ae682c04894f4532f4cf7516f23ce387c70
image

## Reproduction:
Play on any server after the broken commit, spawn in a paramedic belt, watch as you probably can't insert any of its contents back into it.

Probably broken by https://github.com/tgstation/tgstation/pull/74769

### PR DESCRIPTION
**Pull request by LemonInTheDark**
## About The Pull Request

It broke stuff bad and I don't care about the save (0.005 seconds) enough to work on it

## Why It's Good For The Game

Closes #74907

### CODE REVIEW

**Comment by SyncIt21** [comment]
This should have the high priority label right?

**Comment by orthography** [comment]
Speed merge :3

**Comment by Mothblocks** [comment]
Sad this was not caught by tests

**Comment by orthography** [comment]
@Mothblocks Still broken.

**Comment by LemonInTheDark** [comment]
fuck (I can't test, in the middle of a merge conflict hell)
suck my nuts timber it wasn't the arcane for loop it was the -=

**Comment by LemonInTheDark** [comment]
> @Mothblocks Still broken.

are you seeing this locally or did someone force update the servers

**Comment by Timberpoes** [comment]
> fuck (I can't test, in the middle of a merge conflict hell) suck my nuts timber it wasn't the arcane for loop it was the -=

You need to be a little more fresh for that.

**Comment by LemonInTheDark** [comment]
ihateyouihateyouihateyou

**Pull request merged**
