### PR TITLE
Revert "adjusted default internet song volume to 25"

### PR DESCRIPTION
**Pull request by ghost**
Reverts tgstation/tgstation#32585

Tested locally, this will fix goonchat not loading properly no matter what you do

### CODE REVIEW

**Comment by Qustinnus** [comment]
guess this didn't remove your shadowban

**Comment by MoreRobustThanYou** [comment]
@Qustinnus no I was doing testing, and goonchat started working both with and without it!

**Comment by JJRcop** [comment]
#32705

**Comment by Qustinnus** [comment]
lol yeah i asked my associates to remove ur shadowban for now so I can add it again later and start this cycle again

**Pull request closed without merging**
