### PR TITLE
Fixes apple/banana/potato juicing

### LINKED ISSUE #33557: potato can't be juiced
But it should!

### PR DESCRIPTION
**Pull request by YPOQ**
Fixes #33557
The juice_results variable was put in the seeds instead of the plant itself.

### CODE REVIEW

**Comment by arsserpentarium** [comment]
Facepalm. I've tryed to fixed it. But didn't noticed,where was the problem.
Also, I ask you to make income from grinding bigger. Because ,for example, plàsma stack in chemistry supposed to be 100 u. But after refactor this values was sufficirntly reduced.

**Comment by FantasticFwoosh** [comment]
Increase the potency of the plant, there is no requirement to increase the output at the current time if you neglect the plant's statistics and don't either work with botany to grow bigger plants or supply them yourself.

- You can inspect the actual harvestable by hand also by scanning it with green botany plant analyser.

**Comment by arsserpentarium** [comment]
Problem is mostly with non-botany items.

**Comment by YPOQ** [comment]
I can't find any problems with plasma sheets. Grinding up the two plasma sheets that start in chemistry gave me 40 units of plasma.

**Pull request merged**
