### PR TITLE
Allows prisoners to retract skin and manipulate organs

### PR DESCRIPTION
**Pull request by Capsandi**
and extract organs
## About The Pull Request
Due to the only alternatives to retractors being engineering tools, inmates were barred from most round start surgeries, this PR adds the ability to use metal rods(the same way you would use a screwdriver) to complete the skin retraction step, allowing prisoners access to the following surgeries
- Organ manipulation, taking out organs may now be done using a fork
- Lobectomies
- Coronary Bypasses
- Hepatectomies
- Cavity implants
- Implant Removal, ditto, forks are the poor surgeon's best friend and can now remove implants
- Eye Surgery
and Fat Removal surgeries with varying levels of success. In testing i found that you will fail skin retraction almost every time unless you use sterilizer(see; alcohol) and work on a table.
Dental implants(though useless without pills) are now possible as you may now use a spoon to drill into teeth
## Why It's Good For The Game
 Though it doesn't help you escape, and botched surgeries may be fatal, ghetto surgery is the only way to heal yourself after a failed attempt at escape. Tracking implants may now, riskily, be removed in perma, and plastic surgery may help in escape if security cares about who should be behind bars 
## Changelog
:cl:
tweak: You can now use metal rods to retract skin during surgery if you are that desperate
tweak: forks are now viable alternatives to surgical instruments when extracting organs and implants
/:cl:

### CODE REVIEW

**Comment by Coastfront** [comment]
I thought this was erp until i clicked on it. please make the title less click baity i almost got happy

**Comment by Mickyan** [comment]
What kind of failed escapes attempts are you getting into that require ghetto organ transplants afterwards

**Comment by Capsandi** [comment]
Appendicitis could in theory just end your round, but in many rounds where I have gotten into small prison riots because some idiot security guard thinks he's immune to shoving, the department understandably slows our roll by beating the shit out of us, sometimes causing brain damage as we get harm batoned. Plus surgery is something to do in perma and ghetto surgery sees less use than I'd expect with the amount of ghetto surgical tools

**Comment by CRITAWAKETS** [comment]
me and the boys performing a coronary bypass while incarcerated

**Comment by XDTM** [comment]
fail brain surgery until you get teleportation powers

**Comment by FatCat919** [comment]
Me and the boys selling the organs of the "Fresh Meat" for our freedom in jail

**Comment by minichibis** [comment]
This seems like a quality addition to me, even more so when you consider the fact that future health systems might place even more credence on surgery

**Comment by cacogen** [comment]
the inevitable adding more to prisoners because it's boring and sucks ass i like it

**Review by spookydonut — APPROVED** [review]

**Pull request merged**
