### PR TITLE
Re-does #50315, which didn't make it over to Icebox

### PR DESCRIPTION
**Pull request by notfrying1pans**
## About The Pull Request
This PR recreates #50315 which was done _after_ icebox split from box but didn't make it into icebox. It also removes two useless windows from the original PR. Edits originally done by Hanador, I just recreated it and fixed a small thing.

## Why It's Good For The Game
was in box before icebox replaced it, never was ported

## Changelog
:cl: deranging
tweak: Icebox bridge floor tiles are now dark like they were in #50315
tweak: Icebox bridge airlocks have been moved over like they were in #50315
/:cl: deranging

### CODE REVIEW

**Comment by Jared-Fogle** [comment]
Please merge from upstream, there was a recent CI failure.

**Comment by notfrying1pans** [comment]
@Jared-Fogle not all too familiar with git, how does that work?

**Comment by Jared-Fogle** [comment]
You got it :+1:

**Comment by Jared-Fogle** [comment]
@EOBGames

**Comment by EOBGames** [comment]
@notfrying1pans conflicts, please resolve them and then ping me on either here or the discord

**Comment by notfrying1pans** [comment]
@EOBGames i'll redo these changes very soon hold on

**Pull request closed without merging**
