### PR TITLE
Revert "Fixes issues with packagewrap, trashbag, handlabeler, "

### LINKED ISSUE #20256: RPEDs and Bluespace RPEDs aren't picking up items
Basically the title. RPEDs just aren't grabbing the piles of manipulators or anything when clicked like they used to. They seem to work normally otherwise and you can still put items in there one at a time manually.

### PR DESCRIPTION
**Pull request by Kromgar**
Reverts tgstation/tgstation#20186

because it broke RPEDS and Ore Satchels... probably 

Fixes #20256

### CODE REVIEW

**Comment by xxalpha** [comment]
This revert meme needs to stop. If something is broken, fix it.

**Comment by Kromgar** [comment]
I dont know how to code

**Comment by TechnoAlchemisto** [comment]
same

**Comment by xxalpha** [comment]
Try opening an issue.

**Comment by Kromgar** [comment]
We did hours ago no one has responded

**Comment by optimumtact** [comment]
Ya

**Pull request merged**
