### PR TITLE
Rounds starting will now always inform the IRC

### PR DESCRIPTION
**Pull request by ChangelingRain**
I must know of all rounds of clockwork cult, even if in a roundabout way!

### CODE REVIEW

**Comment by KorPhaeron** [comment]
I think this takes away some trust that admins aren't cheating though.

I get plenty of people salty when I catch them, but I am able to point to the fact that I gave up admin powers before the round started and that public logs will show this

**Comment by PKPenguin321** [comment]
Just make a !ncheckmode [server]command in the IRC or something

**Comment by KorPhaeron** [comment]
I think Joan wants it to automatically alert them though

**Comment by KorPhaeron** [comment]
And perceptions aside we've had problems with admins using unlogged methods to check the round type and metagame before

**Comment by Niknakflak** [comment]
but yet you never did anything about that or even did anything with the names

**Comment by optimumtact** [comment]
Admins dont' play the game anyway

**Comment by KorPhaeron** [comment]
@Niknakflak 

I meant scones, who got deadminned for it

**Comment by Robustin** [comment]
Yea I'm against anything that would lend itself to cheating or undermine confidence in the administration.

**Comment by ExcessiveUseOfCobblestone** [comment]
you shouldn't be checking adminbus while you're playing anyways though?

**Comment by Haevacht** [comment]
IRC can have logs, people idle in there, get them to save em and pull them up if needed/suspicious.

And/or trust the people you make responsible for the server.

**Comment by Shadowlight213** [comment]
@Haevacht irc doesn't normally log people online. Someone would have to manually setup something that gets the names of everyone in the channel when the mode announce is triggered and log that.

World topic() already gives out the secret mode if the request is authed. It would be relatively simple to add it to the bot.

Anyways, I agree with what kor said. An unlogged, automatically announcing system that directly reveals round information hidden to the players is horrible.

Also, I think Joan is getting way too obsessed over CC. It's time to stop Joan. Let it go.

**Comment by Razharas** [comment]
Its pretty sad to realise that the obsession you joked about for the past half a year is actually real and progressing

**Comment by SweaterKittens** [comment]
If you can't be trusted not to metagame the roundtype to try and "win" at ss13 with your administrative powers, you shouldn't be an admin.

**Comment by KorPhaeron** [comment]
@SweaterKittens 

People always say "they shouldn't be admin if you can't trust them" but its not like we have any sort of way to magically vet people. We just make admins and hope for the best.

And again, there have been numerous admins in the past who have self antagged, unbanned their friends, checked game modes, etc, so the trust does get abused. Best we can hope for is to catch it.

**Comment by optimumtact** [comment]
Awaiting headmin feedback

**Comment by Haevacht** [comment]
Shadowlight join and depart messages are logged, typically, so if you have someone always online who's reliable, you can use those.

Or make the bot PM someone the roundtype when requested instead. If bots can do IRC PMs.

**Comment by KorPhaeron** [comment]
@Haevacht

Admins are generally required to be in irc though.

It'd be a pain in the ass to be required to have to enter and leave adminbus like that.

**Comment by lzimann** [comment]
I don't necessarily mind this, but Kor makes a really good point, there's no way of seeing if an admin checked the gamemode or not this way and will probably end up causing more drama than it's worth.

**Comment by Shadowlight213** [comment]
@Haevacht I can actually make the current bot pm Joan if there are no admins and a round of CC starts easily.
I'll add that right now actually.

**Comment by optimumtact** [comment]
@lzimann is that the headmin opinion as a group or just yours? I want basically a yes/no from you three

**Comment by ChangelingRain** [comment]
It will now only show "secret" if the mode is hidden.

**Comment by TehPear** [comment]
If the issue of it revealing the round is now resolved then there isn't an issue in having this merged as integrity is kept intact. So it has my approval and I'm sure @lzimann won't have any objections either as the issue is resolved.  With love; a dumb headmin.

**Pull request merged**
