### PR TITLE
Add a game log entry for damp rags

### LINKED ISSUE #10879: Damp Rag smothering is not logged
wow lol another damp rag issue

Considering it is a GG DEATH attack this really needs attack logging, which it does not have. Please fix this ASAP.

### PR DESCRIPTION
**Pull request by optimumtact**
Damp rags left no trace of their use, this adds logging of user and target and the reagents contained

fixes #10879

Still need to test if the reagents print properly yet.

### CODE REVIEW

**Comment by SconesC** [comment]
:+1:

**Comment by Iamgoofball** [comment]
that's not how you print reagents

for(var/datum/reagent/R in A.reagents.reagent_list)
pornhub << "[R.name] sponsored by BRAZZERS"

**Comment by Miauw62** [comment]
should probably also add something to the attack logs, also what goofball said.

**Comment by Razharas** [comment]
@optimumtact

**Comment by optimumtact** [comment]
on my todo list

**Comment by Razharas** [comment]
You are on my dodo list

**Comment by optimumtact** [comment]
Ready to go assuming travis builds

**Comment by optimumtact** [comment]
you know what travis, just get out of my life

**Comment by optimumtact** [comment]
@WJohn untag DNM and WIP and merge conflict plox plox plox

thanks

**Pull request merged**
