### PR TITLE
Revert "Removes material exports"

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
Reverts tgstation/tgstation#32926

This was too heavy handed and now cargo players are upset on top of science players being upset

Needs to be some kind of replacement for earning in place before this happens

### CODE REVIEW

**Comment by praisenarsie** [comment]
more materials???????????????????????

**Review by Cyberboss — APPROVED** [review]

**Comment by Jazaen** [comment]
More materials would inevitably lead to cargo exporting the new amount, and problem remaining in place.

**Comment by praisenarsie** [comment]
we port goon mats then

**Comment by Repukan** [comment]
Tech disks were fixed by kevinz, no?

Cargo players have no justification to being upset by this change when it was their own dickery in selling materials and keeping departments starved what caused such a heavy measure to take place.

If they can't play nice, then they shouldn't complain when they get heavy handed into playing nice.

**Comment by Buggy123** [comment]
Maybe award cargo points for _redeeming_ ores in the ORM, instead of selling them? A sort of "look Centcom, we're actually working, give us more stuff!" system.

**Comment by Repukan** [comment]
Cargo has plenty of ways of making money.

You can cooperate with botany to mass produce and harvest monkey organs or skins, or sell rare seeds and produce.

You can use the (now fixed) tech disks too for loadsamoney (which you'll hardly run out of unless you're mass ordering null crates like the pulsing mass of cancer you are, you know who you are, fuck you)

**Comment by Cyberboss** [comment]
Yeah, this feels like an I did PR.

**Comment by ma44** [comment]
While there is organ and monkey skin farming, there's always inflation memes for those, seeds are a one time thing only (unless you get better potency for next export) and produce cannot really be sold except for wood. 

Tho there could maybe be other ways of obtaining credits like selling energy from a engine or exporting super rare reagents like mutation toxins, corgium or strange reagent

**Comment by kevinz000** [comment]
#33063

**Comment by GuyonBroadway** [comment]
Bitcoin mining machines.

**Comment by Repukan** [comment]
W h y

I see through your ploy, lizmberg

**Pull request merged**
