### PR TITLE
Fixes tools hitting things

### PR DESCRIPTION
**Pull request by ghost**
:cl: Qustinnus
fix: When using tools you no longer smash the fuck out of whatever you're fixing.
/:cl:

In procs like multitool act etc, tools either return TRUE or FALSE (depending on if what you did was succesful). In tool_act we set whatever the tool returns as the return value, but then we do this:

if(. & COMPONENT_BLOCK_TOOL_ATTACK)

COMPONENT_BLOCK_TOOL_ATTACK = 1

if you returned true in for example multitool_act, that'd be 1

if(1 & 1) == true.

While this makes sense, it's not how the behavior should be used. To make it more clear I separated the two so it's not as much of a clusterfuck.

### CODE REVIEW

**Review by SpaceManiac — CHANGES_REQUESTED** [review]
doesn't compile

> In tool_act we set whatever the tool returns as the return value

not true

**Comment by Rohesie** [comment]
The `if(signal_result & COMPONENT_BLOCK_TOOL_ATTACK) return` should come before the `switch(tool_type)`

**Comment by Qustinnus** [comment]
I considered that but I have the feeling that will just break pre-existing behavior.

**Comment by Qustinnus** [comment]
I can do it, but it might introduce bugs.

**Pull request merged**
