### PR TITLE
Moves transit space to separate z level.

### PR DESCRIPTION
**Pull request by AnturK**
Pretty much what it says on the tin.

Fixes the issues with asteroid shuttle and other big ones failing to get enough space on maps with vertical docks. Also adds tracking of these failure states just in case. This also enables some things to be used on shuttles that were not allowed before due to centcom checks like wizard spells and few teleportation sources.

### CODE REVIEW

**Comment by ChangelingRain** [comment]
The nuke disc needs to not relocate if on the transit space Z

**Comment by AnturK** [comment]
That's added alrea.. Hum some commits are missing.

**Comment by Iamgoofball** [comment]
@PKPenguin321 @ChangelingRain @lzimann hey we can enable shuttles with this again I think

**Comment by lzimann** [comment]
We can certainly try. I don't know/never bothered to look what was causing the issues so can't say much.

**Review by Cyberboss — APPROVED** [review]

**Pull request merged**
