### PR TITLE
New book option for the chaplain

### PR DESCRIPTION
**Pull request by spessbro**
## About The Pull Request
Adds book of Insulationism to the chaplain's book options

## Why It's Good For The Game

adds the option for Insulationism as a choice for the chaplain's

## Changelog
:cl:
add: Added new chaplain book option
add: Added hypertool null rod option
imageadd: added Insuls book to storage.dmi
imageadd: added hypertool icon to device.dmi
/:cl:

### CODE REVIEW

**Comment by Tlaltecuhtli** [comment]
why not use the budget ones

**Comment by ATH1909** [comment]
pOWeR CReEp

In case it wasn't already obvious, the gloves given by choosing this religion aren't real insulated gloves.

**Comment by ATH1909** [comment]
> why not use the budget ones

If the gloves given were budget insulated gloves, a maintainer would close the PR because of "power creep", despite the fact that budget insulated gloves are really easy to acquire.

**Comment by spessbro** [comment]
nah it actually still doesn't work xd

**Comment by spessbro** [comment]
checking on it tomorrow i'm too tired

**Comment by AzureWildfire** [comment]
Somehow the null rod makes sense, but it doesn't feel like piercing, as if you think about it the screwdriver as the tip is now the multitool, so feels more like blunt/burn damage.
But after all the code says it's sharp, and is a tool that you cannot even imagine how to use so. A nice variant. For the holy engineers.

**Comment by spessbro** [comment]
> 
> 
> pOWeR CReEp
> 
> In case it wasn't already obvious, the gloves given by choosing this religion aren't real insulated gloves.

they're fake insuls now you get 99.999% of the damage though :P

**Comment by spessbro** [comment]
> 
> 
> Somehow the null rod makes sense, but it doesn't feel like piercing, as if you think about it the screwdriver as the tip is now the multitool, so feels more like blunt/burn damage.
> But after all the code says it's sharp, and is a tool that you cannot even imagine how to use so kinda has an excuse.
> A nice variant. For the holy engineers.
> 
> (Maybe add it to the change log)

what if i made it do brain damage 🤔

**Comment by spessbro** [comment]
alright it is finished, for now

**Comment by optimumtact** [comment]
What is this? 
random icon added to the diff seems accidental

**Comment by spessbro** [comment]
it was there when i updated icons/obj/devices.dmi because there was a merge conflict

**Comment by spessbro** [comment]
aaaaaaaaaaaa i did it
pls merge me mighty oranj

**Comment by RaveRadbury** [comment]
Isn't this the toolboxia meme?

Also, the hypertool is a wirecutter and a multitool?

**Pull request merged**
