### PR TITLE
Ghosts can start CTF on their own

### PR DESCRIPTION
**Pull request by coiax**
:cl: coiax
add: If enough people vote to start CTF (by clicking on a CTF controller
as a ghost), then CTF will automatically begin.
/:cl:

- CTF will no longer restart 30 seconds after it ends, it requires
people to vote for it.
- Victory messages are coloured with the team's colour.
- Current number of people required to start CTF is 4 people.

### CODE REVIEW

**Comment by Armhulen** [comment]
can we let the players name the teams yet

**Comment by Bawhoppen** [comment]
This will make it so CTF isn't a treat anymore though. That was the whole reason it was disabled by default.

**Comment by PKPenguin321** [comment]
Please don't allow this unless there are no admins on. Having no ghosts to put into special roles is actually becoming a major problem for me whenever I try to admin and a round is getting bad or I want to throw an event.

**Comment by F-OS** [comment]
suggested middle ground between @coiax and @PKPenguin321, allow admins to stop ctf/add a way to stop a vote so ctf won't happen

**Comment by coiax** [comment]
Admins can already disable CTF if it starts.

**Comment by BeeSting12** [comment]
Not a fan. Clock/blood cult will both be negatively affected by this change. Few enough people want to play those ghost roles as it is.

**Comment by coiax** [comment]
Then maybe they're shit ghost roles if people would rather play a side game than play them.

**Comment by Xhuis** [comment]
Coiax wanted me to post in this PR so I guess I don't care either way and if it causes problems I can raise concerns then

**Comment by PKPenguin321** [comment]
Please address my feedback instead of just saying "your roles are shit"

**Comment by coiax** [comment]
If it's a problem, then disable CTF.

**Comment by coiax** [comment]
No.

**Comment by optimumtact** [comment]
I'm putting this to the head admins

**Comment by coiax** [comment]
So this PR is SO controversial it's gone to headmin review, a la "new species"?

Wow.

**Comment by optimumtact** [comment]
no, it's because it directly affects the administration of the server and several admins have raised their concerns.

Feel free to continue being flippant though

**Comment by KorPhaeron** [comment]
Arm went to sleep when asked about it and I said yes and if its awful or they decide they hate it we can always revert

**Pull request merged**
