### PR TITLE
fixes pentetic acid dealing radiation damage instead of healing it

### LINKED ISSUE #32026: It is impossible to remove radiation from a mob via chemistry with pentetic acid/potassium iodide
title, mob gets peramfucked too. Seems kinda dumb that potassium iodide/pentetic acid aka the anti rad chems do nothing to stop radiation

### PR DESCRIPTION
**Pull request by silicons**
hahahahaha lmao im dying
Fixes #32026

### CODE REVIEW

**Comment by Cyberboss** [comment]
Put the issue in your desc

**Comment by Qustinnus** [comment]
it would deal rad damage if your radiation is below 300

**Comment by davethwave** [comment]
perhaps while while your working on this how about making anti-rad drugs more effective.

**Comment by Iamgoofball** [comment]
fucking phil

**Comment by CPTANT** [comment]
Lol, like someone ever makes this.

**Comment by YakumoChen** [comment]
@CPTANT it's standard in sleepers when upgraded

**Pull request merged**
