### PR TITLE
fixes magic mirrors letting you be robustin zombies

### LINKED ISSUE #28315: Wizards that make themselves zombies lose most of their abilities.
Since they have a mirror that does this, they can't even change back if they pick it. I think zombies also have generally very reduced interactions, so that's doubly bad.

### PR DESCRIPTION
**Pull request by evsey9**
title
the race id is "memezombies" while the blacklist list had "memezombie"
this is a fix and you cant disprove it :^)
EDIT: probably closes #28315

### CODE REVIEW

**Review by Cyberboss — APPROVED** [review]

**Comment by evsey9** [comment]
finally, my first pr that is going to be merged

**Comment by Kerbin-Fiber** [comment]
I don't like this PR, close it

**Comment by PKPenguin321** [comment]
Adminhelp from Wizard420: Help I picked zombie and can't pcik up my spellbook how could this have happened to me hurr

**Comment by coiax** [comment]
Why are they called "Robustin Zombies", I literally coded 90% of new zombie code.

**Comment by evsey9** [comment]
because thats what kevinz told me they are

**Comment by AnturK** [comment]
Should make these ID's defines in the  future

**Comment by coiax** [comment]
@AnturK or instead of using the string IDs, just use the typepaths

**Comment by evsey9** [comment]
yay first pr merged

**Pull request merged**
