### PR TITLE
Slightly changes the colours of the oxygen and burn medkits

### PR DESCRIPTION
**Pull request by Profakos**
## About The Pull Request

The recent medkit changes made the Oxygen Medkits be the same colour as the regular medkits. As the specialized healing medkits have always stood out via their colour coding, I feel like i had to touch it up a bit to bring back that feature. They are now slighty less green, and lighter. However, as I wanted to keep them in the same palette range as the other medkits, I didn't do anything too drastic.

image

This PR also tweaks the burn medkit, by request, making its orange less red.

image

Here you can see the recoloured Oxygen medkit, with a general medkit as comparison.

## Why It's Good For The Game

Its good for specialized medkits to stand out more, not just via their symbols. This would had to be done anyways in the future when the medibot sprites are updated.

By request, slightly lessens the Red in the orange of the burn medkit, preventing it from looking too similar to the pink of the brute medkit when looked at on highly saturated screens.

## Changelog

:cl:
image: Made the oxygen medkits different coloured from the general medkit colours, and tweaked the burn medkits to look a bit less orange
/:cl:

### CODE REVIEW

**Comment by Profakos** [comment]
> Can you make burn more of a yellow as well? It's too close to brute.

Hm, I checked brute and its pink, which doesn't seem close to the orange to me, but the Advanced Medkit's shade of red is indeed very similar? I'll think about it.

**Comment by lessthnthree** [comment]
> > Can you make burn more of a yellow as well? It's too close to brute.
> 
> Hm, I checked brute and its pink, which doesn't seem close to the orange to me, but the Advanced Medkit's shade of red is indeed very similar? I'll think about it.

At higher color saturations the pink and orange start to blend together.

**Comment by Profakos** [comment]
image
Would this slight yellowification work?

**Comment by lessthnthree** [comment]
> image Would this slight yellowification work?

Yeah, that's an improvement!

**Comment by Profakos** [comment]
Alright, I have pushed the change.

**Pull request merged**
