### PR TITLE
Changes doppler array point formula

### PR DESCRIPTION
**Pull request by DaedalusGame**
:cl:
tweak: NT Scientists have started looking into data from small-scale detonations and found that there's still potential data to be gathered from explosive yields lower than 4.184 petajoules
/:cl:

thanks @kevinz000 

Yes, bombs with non-nuclear yield should still generate points.
Other things of note is that the largest bomb detonated will diminish subsequent bombs, so there's already an anti-abuse mechanism in place.
[Also here's a graph](https://image.prntscr.com/image/PraCaPO5TFCUyUldvBRM3A.png) (XAxis explosion radius, YAxis generated technodes, Blue is what it was prior, Red is proposed change)

Do not merge until #35371
Feedback welcome

### CODE REVIEW

**Comment by ExcessiveUseOfCobblestone** [comment]
That's quite a bit for following the wiki.

**Comment by DaedalusGame** [comment]
Once

**Comment by ExcessiveUseOfCobblestone** [comment]
And?

Getting 2 free tech + extra or a >50% jump on the largest tech for literally just following the wiki is a bit much even for once. If you managed to up it by one (having more plasma in the tank) you get that plus a hint more for almost 3 free tech.

I honestly think Mekhi's formula which sets Maxcaps as a baseline and rewards you only for going byond is, while not necessarily RP sensible, certainly sensible from a balance perspective.

**Comment by DaedalusGame** [comment]
There's 88 techs, according to kevin. This is a change in line with the end goal of massively reducing passive generations.

**Comment by ExcessiveUseOfCobblestone** [comment]
How does making bombs = passive generating points, especially when this pr is giving points for doing less work (as in, you can now get points just by following the wiki)? I could understand if tech webs didn't have passive generation, but you're not hitting that (first). As of now, you're just giving them points for following the wiki.

Balancing around preemptive situations that may never come to fruition is how we end up with problems. If this is to go inline with passive regen as you say, hit passive regen first or in tandem with the PR. Then this change will totally make sense and i'd be onboard.

Side note: R&D is in a sore spot because everything of worth to science is nestled in its own tech so they'll just beeline that if we make points scarce (meaning the whole 88 tech point is null when they don't care about the full set of tech). We should probably consider having tech more generalized to give other departments goodies and proportionally increase the tech cost so tech webs do as designed: forced to make choices within a round and not (let science) get all the goodies.

**Comment by DaedalusGame** [comment]
The problem is that we first have to add point generation to enough things, and these changes need to be atomic, and atomically removing passive gen first and then later making prs to add active gens is galaxy brain stuff, it will just make people angry.

And R&D things are not nestled in their own techs, there's a lot of techs like biological engineering that give you 6 or 7 different things. The only techs that suffer from being cherrypicked are the bulk of mecha technology and, for some reason, lasers and capacitors.

**Comment by ExcessiveUseOfCobblestone** [comment]
Sorry I wasn't clear,

When I said "this pr is giving points for doing less work", I meant relative to what is currently done (Mekhi's formula).

As long as your shortterm goal is to proportionally nerf passive gen then ok. My problem is when people add all of this stuff and don't ever get around to fixing the issue all these other features were meant to compensate for.

As for R&D, most people are gravitating towards rushing certain techs. Getting what benefits science THEN getting everyone else's goodies was not the intention of tech webs.

**Pull request merged**
