### PR TITLE
Replaces the HoS's egun with a golden desert eagle

### PR DESCRIPTION
**Pull request by Iamgoofball**
nerfs golden deagle damage also

my hos gun is superior to both @paprka and @steelpoint hos guns, merge mine asap

### CODE REVIEW

**Comment by paprka** [comment]
>nerfs golden deagle damage also

Severe balance issue, hos should be able to 1deag people

**Comment by PKPenguin321** [comment]
U S A
U S A

**Comment by Chocobro** [comment]
1 deag or close he
also please make sure the reload comes with a spinny animation!!!

**Comment by Iamgoofball** [comment]
@PKPenguin321 he wants a stun, go grab one from the locker or the armory

**Comment by Iamgoofball** [comment]
rck070z

**Comment by Cheridan** [comment]
what's an asusa

also
time to hire gun directors to complement our art directors

**Comment by Steelpoint** [comment]
Energy weapons are kinda the shtick of NT personal, Detective withstanding cause he's a loose cannon.

**Comment by Chocobro** [comment]
>@Cheridan
>what's an asusa

![dongs] (http://images6.fanpop.com/image/photos/34100000/Nakano-Azusa-kawaii-anime-34102660-501-640.jpg)

**Comment by Miauw62** [comment]
The Trio for Violin, Horn and Piano by György Ligeti was completed in 1982. It is marked as an homage to Johannes Brahms who wrote one of the few other examples of this genre.

**Pull request closed without merging**
