### PR TITLE
Repaths/renames closets to lockers

### PR DESCRIPTION
**Pull request by Shadow-Quill**
## About The Pull Request

Everything relating to closets/lockers [`/obj/structure/closet` and subtypes] (minus WC and the janitorial closet room) has been repathed and renamed to be a locker!
They are, ostensibly lockers, and I think I can count the number of people who've actually called them `closets` on two hands.

This also repaths `/obj/structure/closet/secure_closet` to `/obj/structure/locker/secure` as reiterating that it's a secure_locker seemed a bit strange.

## Why It's Good For The Game

I believe that generally people call `closets` lockers, and there have been many times where I personally try to search for a `locker` before realizing that they're closets, for some reason.

## Changelog
:cl:
refactor: Closets have hereby been renamed to lockers.
/:cl:

### CODE REVIEW

**Comment by Shadow-Quill** [comment]
It appears CI is not happy.

**Comment by san7890** [comment]
this sounds useful but i don't think it's really needed? i'll need to think on it for a second

this isn't a refactor though, very time-consuming everything i'm sure- but it's just not altering code beyond the path update

**Comment by Shadow-Quill** [comment]
> this isn't a refactor though, very time-consuming everything i'm sure- but it's just not altering code beyond the path update

Wasn't sure what else to tag it as.

**Comment by SyncIt21** [comment]
This is a completely pointless and subjective PR. Nobody has complained about it for years why change it now?

> I personally try to search for a locker before realizing that they're closets, for some reason.

You literally admit it yourself you are doing this for your own convenience when literally no one else had a problem with it, seems like an lazy attempt to improve your GBP.

> very time-consuming everything 

It really isn't when you have update paths script and search and replace for your entire project, I bet it took just 10 minutes to make this PR as you have said sans 

@san7890 please DM this till #74754 gets merged. I cannot be asked to deal with a merge conflict on this scale just because one person has a problem with it. If anything just close this PR,  I don't see it adding any value to the code base,  it's one of those potato, potaatoo PR's where people just rename stuff based on how they feel about it

**Comment by Shadow-Quill** [comment]
> You literally admit it yourself you are doing this for your own convenience when literally no one else had a problem with it, seems like an lazy attempt to improve your GBP.

I don't care about how much GBP I have. If this PR was made GBP exempt.

> > very time-consuming everything
> 
> It really isn't when you have update paths script and search and replace for your entire project, I bet it took just 10 minutes to make this PR as you have said sans

The easiest parts was the find/replace paths and the map path updates. However, I had to go through every instance of `closet` in the code to change them as needed to `locker`.

> @san7890 please DM this till #74754 gets merged. I cannot be asked to deal with a merge conflict on this scale [snip]

Obviously, your PR should _ideally_ get merged first. I don't have any qualms deconflicting this PR.

**Comment by optimumtact** [comment]
it is generally frowned upon to change paths without a very good reason, and closet vs lockers is not it.

**Pull request closed without merging**
