### PR TITLE
Using a Plant Analyzer/Science Goggles on Planted/Packet seeds will show it's reagents.

### PR DESCRIPTION
**Pull request by ArcaneMusic**
## About The Pull Request

Very simple effect, now using a plant analyzer on a plant in a tray will tell you what reagents exist within the seed, and how much that reagent gene is producing.
image
## Why It's Good For The Game
Quickly put together through player feedback, and there was no easy way to get this info with no DNA Manipulator.

## Changelog
:cl:
tweak: The plant analyzer shows what reagents the plant contains as a seed, or when planted.
/:cl:

### CODE REVIEW

**Comment by ShibaInuLord** [comment]
amazing, strange seeds are better now

**Comment by ExcessiveUseOfCobblestone** [comment]
what about unplanted?

**Comment by ArcaneMusic** [comment]
> what about unplanted?

This can be arranged.

**Comment by ArcaneMusic** [comment]
Rolled into #50513.

**Pull request closed without merging**
