### PR TITLE
new pda sprites!

### PR DESCRIPTION
**Pull request by capsaicinz**
## About The Pull Request

hated the ones we got with the new pdas, so i've done us the favor of remaking them into more phone-like tablets, rather than whatever we have now. other than that, they all function the same, and all program screens have been fitted.

## Why It's Good For The Game

unknown
[ vibrancy has been upped! ]

## Changelog

:cl:
imageadd: replaced new PDA sprites with even newer, COOLER ones.
/:cl:

### CODE REVIEW

**Review by Imaginos16 — APPROVED** [review]
Yeah looks better

**Comment by Jolly-66** [comment]
The clown PDA is genuinely horrifying and scaring me

Everything else is terrific

**Comment by cacogen** [comment]
If you provided a side-by-side comparison with the current ones, which all sprite PRs should be required to do, it would be obvious these don't look as good as the current ones.

**Comment by capsaicinz** [comment]
> If you provided a side-by-side comparison with the current ones, which all sprite PRs should be required to do, it would be obvious these don't look as good as the current ones.

unknown

ok

**Comment by magatsuchi** [comment]
these sprites are better than the existing ones, i approve this

**Comment by cacogen** [comment]
>ok

No, a comparison in the PR body of every sprite you're changing. But it's obvious from the comparison you did provide that the original one looks better. The size is better, though.

**Comment by Farquaar** [comment]
> 
> unknown

Who are these people?

**Comment by magatsuchi** [comment]
> > unknown
> 
> Who are these people?

context clues: 0

**Comment by bluetshirtguy** [comment]
It's more like a tablet with a horseshoe on it or maybe that's a magnet.

**Comment by wesoda25** [comment]
This really surprises me, the current ones really seem at home to me. They have charm and look great, and it's not as if they're dated. These seem really bland and have a lot less heart.

**Comment by magatsuchi** [comment]
> This really surprises me, the current ones really seem at home to me. They have charm and look great, and it's not as if they're dated. These seem really bland and have a lot less heart.

the current sprites are the epitome of codersprite: these may seem mroe basic, yes, but i think itll grow on people much faster. i like them better, too

**Comment by capsaicinz** [comment]
unknown

i've updated the logo on the screens to be more vague, rather than an n (for nanotrasen)

**Comment by bluetshirtguy** [comment]
o?

**Comment by timothymtorres** [comment]
Why can't we have the old PDA sprites instead?

**Comment by OrionTheFox** [comment]
got some white pixels in the corners of some icon states, i'll quickly nab a list of all the trouble ones, expect an edit

**Comment by Twaticus** [comment]
> got some white pixels in the corners of some icon states, i'll quickly nab a list of all the trouble ones, expect an edit
> 
> ```nix
> comm_monitor
> alert-green
> smmon_1
> smmon_3
> air
> ```
> 
icondiffbot issue involving animations, doesnt appear on the actual sprites

**Comment by StoneMason** [comment]
I can't be the only one...

164372013-5f6f676e-98bd-4a30-8229-8ae2866bb24d (1)

**Comment by MrDoomBringer** [comment]
I think I speak for a lot of people when I say your saturation on the new sprites is too low, which contributes to the sentiment that they seem bland, washed-out, soulless, etc. Bumping S/L a little bit would help your sprites fit our artstyle.
image

**Comment by capsaicinz** [comment]
> I think I speak for a lot of people when I say your saturation on the new sprites is too low, which contributes to the sentiment that they seem bland, washed-out, soulless, etc. Bumping S/L a little bit would help your sprites fit our artstyle.
> 
> image
> 
> 

i do think i agree-- i'll get this done when i'n at my computer

**Comment by capsaicinz** [comment]
i think it looks way better now!

**Comment by EricZilla** [comment]
These look baller, glad to see the clown face has survived the modulating

**Pull request merged**
