### PR TITLE
Freeze starting the 24th march

### PR DESCRIPTION
**Pull request by optimumtact**
Notification PR only, exceptions will be allowed for april fools' pr's that admins are going to test merge.

NO FEATURE PR'S AFTER THIS DATE, FIXES AND REFACTORS ONLY.

TODO:decide end date/conditions.

### CODE REVIEW

**Comment by coiax** [comment]
Shouldn't you open this PR when the freeze starts

**Comment by optimumtact** [comment]
We're doing a thing called notifying people in advance

**Comment by XDTM** [comment]
Oh no i can only code on weekends :(

**Comment by Iamgoofball** [comment]
Can I still planet station

**Comment by SgtxRootbeer** [comment]
Will this affect wip stuff like robustin's work?

**Comment by optimumtact** [comment]
@SgtxRootbeer Pr's opened before the freeze have immunity, but if we suspect you're opening a bunch of pr's to avoid the freeze and they're not anywhere near finished we will close them.

**Comment by optimumtact** [comment]
@Iamgoofball no?

**Comment by BeeSting12** [comment]
@optimumtact 
Do we get antag tokens for fixing bugs during the freeze? If so do I get like 1/bug or do I have to fix a certain amount?

**Comment by PKPenguin321** [comment]
not up to the orange

**Comment by BeeSting12** [comment]
oh, is it up to you? in that case pls gib antag tokens

**Comment by PKPenguin321** [comment]
i'll have to consult the counsel

**Comment by kevinz000** [comment]
hey can we still do planetstation stuff :3c

**Comment by optimumtact** [comment]
no

**Comment by Iamgoofball** [comment]
im going to planetstation regardless

**Comment by optimumtact** [comment]
That's your funeral

**Comment by peoplearestrange** [comment]
What about April Fools PRs? (as in PRs to be quick merged for april fools ideas), will they still go through ok?

**Pull request closed without merging**
