### PR TITLE
Removes copyright infringing material.

### PR DESCRIPTION
**Pull request by AnCopper**
## About The Pull Request

Removes copyright infringing material.

## Why It's Good For The Game

I don't think that LLS was released under CC BY-SA

## Changelog

:cl:
del: removed ambispace.ogg due to copyright infringing material.
/:cl:

### CODE REVIEW

**Comment by Colovorat** [comment]
> BAD Apple!!

wait... WAIT, HOLY SHIT HE IS RIGHT HAHAHHAHAHAH

**Comment by necromanceranne** [comment]
How on earth did you find this out?

**Comment by AnCopper** [comment]
> How on earth did you find this out?

This is a pretty commonly known fact.

**Comment by Wallemations** [comment]
I thought Touhou in the public domain?

**Comment by Wallemations** [comment]
> > I thought Touhou is in the public domain?
> 
> No, ZUN (Jun'ya Ota) is the copyright holder.


Looked it up
> ZUN has granted blanket permission for fanworks distributed in the spirit of the original games, but explicitly forbids distributing arrangements of his music
Alright makes sense to me.

**Comment by Wallemations** [comment]
wait what about mining ambience, that's bad apple too.

**Comment by cacogen** [comment]
This has been in the game for over ten years now: a80f7c7. I think we're going to be okay. Isn't remixing a song like this to the point where it's almost impossible to recognise fair use anyway?

**Comment by Fikou** [comment]
> wait what about mining ambience, that's bad apple too.

yes and our other mining ambience is dorime ameno

**Comment by optimumtact** [comment]
we will take our chances and hope they respect our fan work

**Comment by Shadowflame909** [comment]
i love touhou

**Pull request closed without merging**
