### PR TITLE
Adds a Directional Flashlight

### PR DESCRIPTION
**Pull request by Robustin**
I think this was pretty much ready. It wasn't perfect and I kept trying to make it perfect, but I guess I'd rather see it attempted imperfectly than not at all.

image

### CODE REVIEW

**Comment by GunHog** [comment]
Add this to Oldstation!

**Review by vuonojenmustaturska — CHANGES_REQUESTED** [review]

**Comment by kingoftheautism** [comment]
Slender Station 13 when

**Comment by WJohn** [comment]
I think all flashlights should behave like this, but only when held in your active hand. Otherwise if stored on your belt or pockets, it would have greatly reduce (radial) lighting.

Also it'd mean you now have  to use up a hand to see further in the dark, and it could lead to cool situations like having a flashlight in one hand and a gun in the other.
image

**Comment by optimumtact** [comment]
I can't tell if you addressed @vuonojenmustaturska's comments

**Comment by kingoftheautism** [comment]
rip

**Pull request closed without merging**
