### PR TITLE
Hulks are now treated like cultists for ratvarian stuff

### PR DESCRIPTION
**Pull request by ChangelingRain**
or in other words they take more damage and may be set on fire

### CODE REVIEW

**Comment by PKPenguin321** [comment]
these are some of the i dediest PRs ive ever seen its time to stop

**Comment by Xhuis** [comment]
What? Why?! Joan, why have you made it your mission to remove every single weakness to this gamemode or to give them a tool to counter everything? It's seeming more and more like you're trying to give them the schoolyard everything-proof shield - if this keeps up, servants will just be able to say "Nuh uh, I used my everything-proof shield!" against anything that tries to attack them and there isn't anything anyone can do about it.

I handed off the gamemode to you, I know, so technically my word doesn't even mean anything. But as the gamemode's creator: __stop.__ You have gone _way_ over the line in the past few weeks.

**Comment by ChangelingRain** [comment]
Pah! The entire idea of clockcult is that they ARE everything-proof if they happen to use everything properly!

**Comment by Xhuis** [comment]
I realize that their schtick is "situational tools for everything", but I feel that there needs to be a line. A clever servant shouldn't be invincible; they should be powerful. If someone knows how to hack a door, they shouldn't be able to destroy the door with nothing but wirecutters and a screwdriver and then prevent any other doors from existing in that spot.

**Comment by ExcessiveUseOfCobblestone** [comment]
why are you drawing the line at green men who go ARRRRGGGGGG though

**Comment by TechnoAlchemisto** [comment]
stop

**Comment by Armhulen** [comment]
if you're that buttmad about hulks just add an application that dehulks someone or something, instead of this retarded shit

**Comment by MrAlphonzo** [comment]
Looking forward to the "Cultists get ling and wizard powers" PR. Can't have the powergaming assistants ruining our brass fun.

**Comment by AdamElTablawy** [comment]
at this point you might as well make hulks also suffer the downside of blood cultists as well so that being stunpapered as a hulk still stuns oh wait you're playing favorites nevermind

**Pull request closed without merging**
