### PR TITLE
Lets combat upgraded AIs hack their borgs

### PR DESCRIPTION
**Pull request by xenon-difluoride**
[Changelogs]: # (Your PR should contain a detailed changelog of notable changes, titled and categorized appropriately. This includes, new features, sprites, sounds, balance changes, admin tools, map edits, removals, big refactors, config changes, hosting changes and important fixes. An example changelog has been provided below for you to edit. If you need additional help, read https://github.com/tgstation/tgstation/wiki/Changelogs)

:cl: Astatineguy12 
add: Combat upgraded AIs can now hack their borgs too.
/:cl:

[why]: # (Please add a short description [two lines down] of why you think these changes would benefit the game. If you can't justify it in words, it might not be worth adding.)

The combat upgrade is supposed to give a normal AI the abilites of a malf AI, including hacking.

### CODE REVIEW

**Comment by ExcessiveUseOfCobblestone** [comment]
surprised this isn't reported issue-wise.

**Comment by AlexTheSysop42** [comment]
I was going to but I figured it'd be easier to just fix it myself

**Comment by KorPhaeron** [comment]
This was actually on purpose to avoid asimov AIs handing out stun prods to all their borgs

**Comment by Barhandar** [comment]
Why would asimov AI accept/use combat upgrade in the first place?

**Comment by davethwave** [comment]
Actually the combat upgrade is useful if you only use things like upgrading cameras and the mech over-ride to prevent rouge mechs from becoming a problem.

**Comment by AlexTheSysop42** [comment]
Borgs can flash unprepared traitors/lings as it stands, having stunprods would also give them tools to curb shitsec (and they can always have the cap change their laws or use existing borg hardcounters like flashes or the ion gun)

**Comment by Anonmare** [comment]
@KorPhaeron Re-add illegal tech for emag module when?

**Comment by AlexTheSysop42** [comment]
It's already there, under the illegal tech node

**Comment by optimumtact** [comment]
we don't want meta to become using this to make all the borgs into secborgs.

Based on kor's lukewarm response and my own dislike. I'm closing this

**Pull request closed without merging**
