### PR TITLE
Fixes rice turning into nutriments when grinded

### LINKED ISSUE #25461: Rice grown from hydro cannot be made into edible rice.
Grinding the rice stalks turns it into plain nutriment instead of normal rice.

### PR DESCRIPTION
**Pull request by Enlightening**
Fixes #25461

### CODE REVIEW

**Comment by Supermichael777** [comment]
¯\_(ツ)_/¯

**Comment by FantasticFwoosh** [comment]
You're forgetting this is also a issue for gathering doughnut sprinkles for other recipies since the doughnut converts to nutriment too. (meaning sprinked doughnuts are uncraftable but are instead RNG with regular doughnuts)

**Comment by Cyberboss** [comment]
donut/New??

**Comment by Enlightening** [comment]
yeah, that's the sprinkled donut

**Comment by KorPhaeron** [comment]
Thanks oldcoders

**Pull request merged**
