### PR TITLE
Makes swimsuits an underwear option

### PR DESCRIPTION
**Pull request by ShizCalev**
Closes #38348
Closes #38347

### CODE REVIEW

**Review by SpaceManiac — CHANGES_REQUESTED** [review]
Can't be male underwear because it does not cover the dixel.

**Review by SpaceManiac — APPROVED** [review]

**Comment by Iamgoofball** [comment]
@SpaceManiac Negative, we have other underwear options that are gender neutral and don't cover the Dixel™️

**Comment by ShizCalev** [comment]
@Iamgoofball that sounds unintended. What ones?

**Comment by Iamgoofball** [comment]
I'll have to check but if I recall correctly it was deemed okay because that was funny shit

Let's be fair here we don't need the dixel anyways

**Comment by SpaceManiac** [comment]
Male versions can be added later or the same sprites can be re-used but this is the best of the three PRs on this issue

**Pull request merged**
