### PR TITLE
adds a safety catch to spin()

### PR DESCRIPTION
**Pull request by silicons**
woops

### CODE REVIEW

**Comment by evsey9** [comment]
good job you broked the server

**Comment by WJohn** [comment]
woops

**Comment by kevinz000** [comment]
doesn't need testmerge it only happens if someone doesn't code properly or an admin fucks up
we can guess which one happened.

**Comment by evsey9** [comment]
so we blame the coders?

**Comment by kevinz000** [comment]
not really since i coded the proc lol

**Comment by MrPerson** [comment]
isnull(var) is a slower way of writing var != null or !var.

**Pull request merged**
