### PR TITLE
Removed some gas reactions

### PR DESCRIPTION
**Pull request by Ghilker**
## About The Pull Request
The PR removes:
stimball reaction (never used)
ammonia crystals (saw it made a few times, but not worth keeping)
hexane_n2o_filtering (made the hexane gas more plasma fire specific)
all three gas crystal_production (saw it a couple of times, not worth keeping tho)
proto_nitrate_plasma_response and proto_nitrate_freon_fire_response (not very useful and very rarely made)

## Why It's Good For The Game
Less reactions == better react() == faster atmos

## Changelog
:cl:
del: stimball reaction
del: ammonia crystals
del: hexane_n2o_filtering
del: all three gas crystal_production
del: proto_nitrate_plasma_response 
/:cl:

### CODE REVIEW

**Comment by Ghilker** [comment]
ah yes the "improve don't remove" squad is working good i see

**Comment by Ghilker** [comment]
@LemonInTheDark said that just cutting 3 would bring a 10% speed increase, i didn't do any profiling yet, but this should be quite faster now

**Comment by LemonInTheDark** [comment]
Note, react() preforms differently in different cases, it's going to experience a large slowdown in a plasmafire for instance, what I'm concerned about here is the case of gasses calling react with no reactions to preform, so they need to iterate through something to the tune of 37 reactions to exit the proc. React is called on every bit of processing gas every time it processes, so canisters, pipenets, and active turfs. It's currently our slowest proc when no reactions occur. This is magnified significantly by the sheer amount of calls it receives.

Any decrease in the amount of gas reactions we need to iterate through will help things significantly. There is a faster way to build the reaction list, but it breaks nobilium, and some other things. I don't want to neuter atmos, and any important reactions can and should stay, I just want to make sure that the ones we do have are looked over critically, as they aren't free to keep.

**Comment by Ghilker** [comment]
lol why the dislikes

**Comment by VolraSlava** [comment]
tenor

**Comment by MrFagetti** [comment]
> lol why the dislikes

Because holding backspace isn't coding, bud.

**Comment by VolraSlava** [comment]
> 
> 
> > lol why the dislikes
> 
> Because holding backspace isn't coding, bud.


All this guy knows to do is to remove shit, come on now.
8HMZIJ9

**Comment by LemonInTheDark** [comment]
Asking why all the dislikes won't exactly help your case, but come on, he's the guy who added all but one of the things he's removing.

**Comment by Ghilker** [comment]
Don't bother to answer them, is obvious that they see the removal tag and go apeshit without reading the body of the PR lmao

**Comment by Cw3040** [comment]
> he's the guy who added all but one of the things he's removing.
Tiny fans and Assistant Maint Access are two things, and unless you can prove that dentbrain here actually added either of them, he's just gonna be relegated to the backspace squad.

**Comment by VolraSlava** [comment]
> 
> 
> Don't bother to answer them, is obvious that they see the removal tag and go apeshit without reading the body of the PR lmao

I don't need a fucking Perception 10 roll to see that the majority of your PRs (Including this one) is about removing things only _YOU_ dislike or don't see used by anyone.

You're a backspace coder and actually try to justify it too by saying "Oh not all my PRs are about removing things!"
Yes, yes they are.

**Comment by Cw3040** [comment]
> Cutting 7 reactions ought to lower the cost of no reactions react by something close to 20%

And making it so that those reactions aren't all in one proc but still exist would lower the cost by 100%. But that requires effort and a sentient coder instead of a backspace monkey.

**Comment by VolraSlava** [comment]
8hAMEVU

This you?

**Comment by Ghilker** [comment]
> > Don't bother to answer them, is obvious that they see the removal tag and go apeshit without reading the body of the PR lmao
> 
> I don't need a fucking Perception 10 roll to see that the majority of your PRs (Including this one) is about removing things only _YOU_ dislike or don't see used by anyone.
> 
> You're a backspace coder and actually try to justify it too by saying "Oh not all my PRs are about removing things!"
> Yes, yes they are.
> 
> Ever heard of the phrase "Improve, don't remove" ?
> Cause I'm sure you're going to hear this phrase a lot down the line if you continue trying to justify the removal of things by saying "Waah nobody uses it" and "Waah, I don't like how this functions"

@VolraSlava AHAHAAHAH first thanks for the copypasta this is hilarious 🤣 
second, i have 52 closed PRs the majority of them are about adding features, if you bother to check the other 3 pages you'll see i added many things to the game.
third, i'm improving the code by removing some stuff that is bloating it too much slowing it down by a lot, if you want better stuff stop complaining and start coding ya bumbo

and yes that's me, want to complain more?



> > Cutting 7 reactions ought to lower the cost of no reactions react by something close to 20%
> 
> And making it so that those reactions aren't all in one proc but still exist would lower the cost by 100%. But that requires effort and a sentient coder instead of a backspace monkey.

@Cw3040 HOLY HELL YOU FOUND THE WAY HOLY SHIT! is not like react() proc was made to make atmos faster, but man you definetly have all it takes! Feel free to add them back and more once you coded this other proc!

**Comment by VolraSlava** [comment]
god im being baited so hard into this i cant believe im falling for it too

**Comment by Qustinnus** [comment]
"improve don't remove" is a cringy doctrine and most half decent game designers will tell you that removing things from gameplay is as important if not as important as adding things.

**Comment by Qustinnus** [comment]
besides that, the guy added most of these reactions so he has the right to remove it too, just like how maintainers have the right to reject this PR. If you want to code by not holding backspace feel free to submit a PR with some new gas reactions.

**Comment by actioninja** [comment]
lol @ the guy going "y-youre just baiting me!!!!"

**Comment by ExcessiveUseOfCobblestone** [comment]
@VolraSlava @Cw3040 @Ghilker 

Please keep contributor "qualifications" or how you personally perceive a contributor out of the PR messages, including PRs that said contributor makes. If it is not about the contents of the PR, the PR comments is not the place to comment it.

**Comment by VolraSlava** [comment]
RYjzGlD

oPU2GT8

certified tg moment

TGfku

**Comment by Qustinnus** [comment]
don't you code for a server thats about having sex with sentient animals?

**Comment by actioninja** [comment]
Wow, you're absolutely hilarious. Please post more shitty edits.

**Comment by VolraSlava** [comment]
tenor

**Comment by VolraSlava** [comment]
> 
> 
> don't you code for a server thats about having sex with sentient animals? 😳

kinda embarassing when the server where you get to sex sentient animals has better quality control than your server lmao

**Comment by wesoda25** [comment]
cool I made the sc

**Comment by actioninja** [comment]
> kinda embarassing when the server where you get to sex sentient animals has better quality control than your server lmao

kinda embarassing when the devs of one server come and make poorly informed stupid posts on the repo of another

**Comment by VolraSlava** [comment]
> kinda embarassing when the devs of one server come and make poorly informed stupid posts on the repo of another

kinda embarassing when a maintainer merges a pr that has an overwhelmingly negative response to it and ignoring their community

But hey, this is already daily routine for tg so who am i to point this out as i am sure many have done so before

**Comment by VolraSlava** [comment]
eFBfFU7J

**Comment by optimumtact** [comment]
take a chill pill my dude

**Comment by msgerbs** [comment]
> 
> 
> "improve don't remove" is a cringy doctrine and most half decent game designers will tell you that removing things from gameplay is as important if not as important as adding things.

Most half decent game designers are not making sandboxes where the only thing keeping it interesting is all the random shit you can do, tbf. That absolutely holds true if you're making an RPG or a shooter or something, but it's certainly not universal.

**Comment by Qustinnus** [comment]
If the random thing isn't used and requires one of the most taxing systems in the game it becomes valid to look at subtractive design.

**Pull request merged**
