### PR TITLE
Service Area Update

### PR DESCRIPTION
**Pull request by nightred**
## About The Pull Request

The service area on meta did not have a department feeling to it, the bar was of on it's own side, the back of house was not connected. 
The worst offender was that sad little room for the service TechFab.

This creates a better cohesive service department, all service areas have access to a proper service back hall with a proper delivery area. (OK the janitor is still left out but something had to give.)

In this setup the bartender has access to the kitchen, and cook has access to the bar.

change

## Why It's Good For The Game

This should create better traffic flow and create more active area for the crew in the bar.
The bartender, cook, botanist, even clown can now work as a team. or kill the clown you know, do you.

## Changelog
:cl:
tweak: Service department area update on Meta
/:cl:

### CODE REVIEW

**Comment by bluetshirtguy** [comment]
How is the chef supposed to interact with his patrons, seems like he's just alone in the kitchen.

**Comment by GunHog** [comment]
Agreed. The Chef currently has serving tables which face both the hallway and the main portion of the bar. This version cuts him off from all public contact. Even the cold room is detached now.

**Comment by Angustmeta** [comment]
Was botany's box of beakers removed or is it under the syringes?

Botany wants lots of space to separate all trays from each other, even diagonally. And probably an extra sink to the south.

**Comment by Fikou** [comment]
maint kitchen
maint kitchen

**Comment by LemonInTheDark** [comment]
maint kitchen is actually kinda fun, it's an interesting idea. maybe push the tables out a bit to the left so they're accessible from the main hallway or something?

I morn the loss of the theater room meta has, it's a semi public semi sneaky area. I do really like the cohesion here tho, good work

**Comment by Mycah142** [comment]
Nearly every station has this "doesn't feel like a department" feel to it then.

Bar bone is connected to the kitchen bone, and the kitchen bone is connected to the botany bone. This creates a logical flow to where the services are generally rendered, the bar, and promotes ease of communication between the three divisions.

If you're gonna try and make service to look like a department, why isn't the library or the chapel stuck in there too? They're Service as well. Just really muck it all up.

**Comment by Iatots** [comment]
- maint kitchen
- freezer room being separate and requiring to pass through common area
- theatre employees furthest away from theatre. 

The coldroom would have made the most sense to be in the theatre crew spot, switching them around could've had the kitchen and coldroom be a single thing OR require the chef to walk 3 tiles to go from one room to the other. I am thinking you added a common room and shuffles the backrooms around as an attempt to force the crew to interact. That's not going to happen.

**Comment by nightred** [comment]
> * Was botany's box of beakers removed or is it under the syringes?
> * Botany wants lots of space to separate all trays from each other, even diagonally. Optionally have some of the trays start pre-separated by directional windows.
> * Probably add an extra sink to the south or two.
> * The botany and kitchen grinders should be near the condimasters as they are usually used at the same time.
> * Botany holopad is missing.

The beakers were there, i made it clearer by shifting them over a bit so you can see. The holopad was under a spawn point. The grinder is closer on the kitchen side. this might clean things up a bit.


> maint kitchen is actually kinda fun, it's an interesting idea. maybe push the tables out a bit to the left so they're accessible from the main hallway or something?
> 
> I morn the loss of the theater room meta has, it's a semi public semi sneaky area. I do really like the cohesion here tho, good work

I hope I got the theater room a bit closer to the original, with some of the latest tweaks withmore maint access, and the backroom and theater are closer.


> * freezer room being separate and requiring to pass through common area
> * theatre employees furthest away from theatre.

Fixed up theater back room location, and the kitchen location.

I liked the idea of kitchen being in the middle with no direct access like you see in a restaurant. The much larger activity room makes up for it in my opinion.

**Comment by RaveRadbury** [comment]
Please allow the chef at least one counter that faces the public.

**Comment by Mickyan** [comment]
I like the general idea but I think it's important to give the chef a public counter, the satisfaction of seeing people eating the stuff you make is basically all there is to the job, this layout makes for a very lonely and depressing experience

I think if you wanted to shake things up you could make the public counter face inside the bar instead of the hallway to make chef and bartender feel a little more part of the same team

**Comment by nightred** [comment]
> Please allow the chef at least one counter that faces the public. It is a part of standard design to provide a publicly-accessible kitchen counter, so that crew can climb in to make things/have shenanigans in the kitchen.
> 
> Just switch botany's back room with the kitchen, make botany wide instead of tall, and give the Chef a counter on the west wall. Similar to the current set up.

This change has been made and the area flows better now, great suggestion.


> I like the general idea but I think it's important to give the chef a public counter, the satisfaction of seeing people eating the stuff you make is basically all there is to the job, this layout makes for a very lonely and depressing experience
> 
> I think if you wanted to shake things up you could make the public counter face inside the bar instead of the hallway to make chef and bartender feel a little more part of the same team

Counter access to the bar, and the hallway.

> maint kitchen
> maint kitchen

Sadly that was not to be :(


> I morn the loss of the theater room meta has, it's a semi public semi sneaky area. I do really like the cohesion here tho, good work

The theater is back to it's full glory with some buffs

**Comment by Pumpkinoe** [comment]
bartender has to walk half a mile to get to his backroom if he ever wants to seperate chems

**Comment by ATH1909** [comment]
the chef's gibber is concerningly far away from the main kitchen

**Comment by nightred** [comment]
> the chef's gibber is concerningly far away from the main kitchen

I honest thought you would handle meat, and meat related processing in the cold room so you could wash up. It is where the hooks are after all.

**Comment by bluetshirtguy** [comment]
alright, the changes are more acceptable now.

**Comment by Farquaar** [comment]
To be honest, this looks like a design you'd see on Delta, not Meta. Still, it's true that the bar lounge doesn't get used often, and provided that the chef can access the bartenders counter, we might see more interaction between the chef and the bartender.

**Comment by Yttriums** [comment]
As a compromise for separating the kitchen cold room, Chef should get CQC in all service-related areas.

**Comment by nightred** [comment]
Here is the shutters closed.
kitchen shutters

**Comment by carshalash** [comment]
This is horrible.

**Comment by optimumtact** [comment]
I dare you

**Comment by carshalash** [comment]
Sure is nice to only have one table between two jobs.

**Pull request merged**
