### PR TITLE
Lavaland looks crisper, and also hey look, it's Icemoon!

### PR DESCRIPTION
**Pull request by AdipemDragon**
## About The Pull Request
This PR aims to both raise the resolution of the currently 2x2 mixel'd Lavaland and also bring Icemoon into view as the planet's actual moon, instead of a half torn asteroid

## Why It's Good For The Game
I think people would enjoy the new view!
planet

## Changelog

:cl:
imageadd: When looking out into nearby space, your local planet might show off more cleanely, now! Check it out, next time you have a mandated break!
/:cl:

### CODE REVIEW

**Comment by GoldenAlpharex** [comment]
I think it's nice, although the moon in particular feels like it should really use some shading, it feels very much in fullbright compared to the big asteroid that was there previously.
Could probably give a bit more shading to the main planet too, while you're at it.

**Comment by LemonInTheDark** [comment]
If you make the moon shaded with darkspots you can brighten the rivers and make it really pop
Keep in mind asteroids are shaded up and to the left globally, so you'd likely want to follow that pattern

**Comment by CapybaraExtravagante** [comment]
isn't there already an icemoon sprite that you should replace instead? I'm pretty sure that's the one you'd see in space. (It also seems silly that an icey moon is orbiting a lava planet)

**Comment by tralezab** [comment]
I still think icemoon being the moon to lavaland is near nonsensical and I don't like how our setting is locked in this one location I don't actually care a lot for. Would rather we have a diverse range of space stations, in differing levels of Nanotrasen controlled space with unique solar system conditions as an excuse for cool station traits. For example, we'll never have a station over a black hole, because a black hole can't exist in the "hurr durr magic solar system that has two giant evil entities controlling two different planets and both causing massive ecological terraforming because of their corruption BUT also plasma"
But I'm not the loremaster, what say do I have

**Comment by Jacquerel** [comment]
Looks fantastic

**Comment by YakumoChen** [comment]
Mining asteroid...

You are gone now

Your barely edited base design smacked down onto lavaland has been demolished

But you still live on in the SOUL of miners

You are not forgotten

**Review by Imaginos16 — APPROVED** [review]

**Comment by bluetshirtguy** [comment]
> I still think icemoon being the moon to lavaland is near nonsensical and I don't like how our setting is locked in this one location I don't actually care a lot for. Would rather we have a diverse range of space stations, in differing levels of Nanotrasen controlled space with unique solar system conditions as an excuse for cool station traits. For example, we'll never have a station over a black hole, because a black hole can't exist in the "hurr durr magic solar system that has two giant evil entities controlling two different planets and both causing massive ecological terraforming because of their corruption BUT also plasma" But I'm not the loremaster, what say do I have

Just edit it when when someone codes all that juicy content

**Comment by AdipemDragon** [comment]
Honestly if it ever does get retconned that Icemoon _isn't_ Lavaland's sattelite? (or if that bitch gets flung out of lavaland's orbit or something) then I can very easely edit it out, I still got the project file so it's as easy as hiding 3 layers and filling in the missing asteroids in the belt
I thought about touching the asteroid layer too, just so it's not all omnidirectionally lit from the topleft no matter what but I kinda just wanted lavaland out there already, maybe another time with a [no gbp] to tie it into this pr.
as for the layer that's _just_ Icemoon? Literally not used yet, if it does get used i can jump on it and make it Look Good

**Comment by LemonInTheDark** [comment]
Wooooooo you want to add movement and animation to the parallax layers AHHHHHH you will add shooting stars and think it's your own idea, this is being implanted in your subconscious

**Comment by AdipemDragon** [comment]
> Wooooooo you want to add movement and animation to the parallax layers AHHHHHH you will add shooting stars and think it's your own idea, this is being implanted in your subconscious

don't even fucking Tempt me to animate this goddamn thing you'll see me working with it barely sketched out in 2026

**Comment by AdipemDragon** [comment]
Also... regarding its current Manuel testmerge... apparently it displays both overlays at once? That's not a problem I know how to fix, oh no.
image

**Comment by AdipemDragon** [comment]
Figured it out, it's because I was an idiot, it should be good now

**Comment by bruhlookatthisdood** [comment]
MONKEY MOON NOOOOOO

**Pull request merged**
