### PR TITLE
Continues to inch dismemberment threshhold downwards

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
Because I'm crazy

Also because as it stands you still could have usually just killed the guy/scored a knockout on him had you just targeted the chest or head rather than slicing at a limb.

Fixes a bug with the HF blade icon update as well

### CODE REVIEW

**Comment by PKPenguin321** [comment]
Give guns dismemberment

**Comment by Fox-McCloud** [comment]
As a codebase that had dismemberment for years before it was even remotely considered on TG...I think you're going to find this is eventually going to lead to scenarios where dismemberment is considered the primary combat intention as opposed to an aesthetic thing (not saying you're there yet). So I'd definitely urge caution in how this proceeds; dismemberment based combat can be really frustrating to play against, to say the least.

Guns dismembering is incredibly shitty though--especially considering how incredibly strong ballistics already are.

**Comment by Jalleo** [comment]
@KorPhaeron perhaps we need to rework how health is done to surface, muscle and bone damage? Its probably the easiest way to make more things not able to dismember and put a focus more on general damage and bleeding.

**Comment by Bawhoppen** [comment]
I'm pretty sure that people did in fact try to cut people apart in combat with swords and shit

**Comment by Dorsisdwarf** [comment]
@Fox-McCloud You can absolutely dismember heads

**Comment by Fox-McCloud** [comment]
@Dorsisdwarf 

You can, but it's at a point where it doesn't really matter much, since you're already in hard-crit, at that point, anyway

**Comment by Bobylein** [comment]
I would still love a health system that's more based on blood loss and pain than on hp but I think it overcomplicate things.

**Comment by AdamElTablawy** [comment]
pain is pretty awful as a part of a health system let me tell you, because either you load yourself up on pain supressants and become a juggernaut or you get a paper cut and shit out your internal organs

also yes, guns dismembering is a BAD IDEA-it'll boil down to point blank buckshot shotgun blasts tearing heads off

**Comment by GunHog** [comment]
Plasma cutters, despite being a gun, should _absolutely_ dismember! 
[Cut ALL the things!](http://www.youtube.com/watch?v=ACgK9DMy_RQ)

**Comment by Cheridan** [comment]
Kor are you going to do anything about the explosion dismember chances?

**Comment by KorPhaeron** [comment]
war is hell cheridan cant trust those arcade machines

**Comment by KorPhaeron** [comment]
I need to go find where that code actually is and sure

**Comment by PKPenguin321** [comment]
>point blank buckshot shotgun blasts tearing heads off

Fucking dope when will this get added

**Comment by LatD** [comment]
The explosion dismember should just get less likely to happen. Yesterday I saw a tiny explosion which didn't even make a hull breach but caused one human near it lose 2 limbs and others further away lose one. Normal brute damage cap getting still lowered is worth a try at least.

**Comment by KorPhaeron** [comment]
>dismemberment based combat is extremely frustrating to play against, to say the least

Can't be that much worse than stun combat, can it? People have been clamouring for a more involved medical and more deadly combat for a long time anyway.

**Comment by Fox-McCloud** [comment]
@KorPhaeron 

Perhaps I expressed myself poorly (likely), but I'm not saying that dismemberment shouldn't be a thing; I'm just urging caution on progression towards this, based off of dealing with it for a long time, elsewhere. It can definitely be balanced and definitely can be interesting, but it can also be ridiculous---getting one-hit dismemberment chances on arms/legs/heads from a single esword (or cleaver) blow isn't very fun.

You're nowhere near close to this, just urging caution s'all--once you start getting into the realm I mentioned *that* is when it becomes unfun.

**Pull request merged**
