### PR TITLE
Adds Autolathes to cargo bays lobby!

### PR DESCRIPTION
**Pull request by Boopideedoo**
This change comes with assurance that cargo wont be broken into for no reason when hooligans want to print tools.
## About The Pull Request
This pull request adds autolathes to most of the main maps so any assistant or vice versa may print tools without breaking into cargo.
## Why It's Good For The Game
This change is good for the game as it brings balance to cargo and the rest of the station since they nolonger need to break in to print tools or other items using the autolathe. The main reason this was added was to keep hooligans where they belong.
## Changelog
:cl:
add: Added Autolathe to most stations
del: Removed flipped chair
del: Removed table
del: Removed spare light box
/:cl:

### CODE REVIEW

**Comment by KittyNoodle** [comment]
okay now add the protolathes for all the departments outside too

**Comment by Boopideedoo** [comment]
> okay now add the protolathes for all the departments outside too

Ill see about doing that in a bit. finishing my coffee

**Comment by Boopideedoo** [comment]
> okay now add the protolathes for all the departments outside too

We need a public prolathe similar to the service prolathe

**Comment by Sealed101** [comment]
lmao

**Comment by Mothblocks** [comment]
Knowing that it's now been so long since we first removed public lathes, which was suuuuper controversial back in the day, that people are adding it back thinking it's a new idea has made me feel very very very old in a way I did not want to today

https://github.com/tgstation/tgstation/pull/41937

**Pull request closed without merging**
