### PR TITLE
[ON HOLD] Spacepods

### PR DESCRIPTION
**Pull request by ghost**
:cl: More Robust Than You
add: spacepods
/:cl:

see https://nanotrasen.se/wiki/index.php/Space_Pods for how they work

just making this  so i can reopen it after the freeze w/ one click (also so i don't forget about it and so people can discuss it)

yooray

### CODE REVIEW

**Comment by calzilla1** [comment]
Neat

**Comment by MoreRobustThanYou** [comment]
Opening/closing to force update the Files Changed section

**Comment by PraiseRatvar** [comment]
@MoreRobustThanYou 
Why not add the mechanic job too? (unless its already there)
Will you be able to fly inside the station?
why no small pods 😭

**Comment by MoreRobustThanYou** [comment]
1. that'd be a seperate PR
2. yes, i tested it
3. maybe later? (para didn't have them, this code was ported from paradise)

**Pull request closed without merging**
