### PR TITLE
Blocks changing AI laws via upload console for the first 5 minutes

### PR DESCRIPTION
**Pull request by tralezab**
## About The Pull Request

The upload console now rejects law changes if it hasn't been at least 5 minutes since roundstart.

## Why It's Good For The Game

The "alternate ai laws" config and station trait get really mogged by the fact that every captain immediately switches the AI back to asimov. This is bannable, as confirmed by the community meeting I'm in right now, but admins miss it really often and we have the code ability to block an action you'd only do in a context that would get you banned... so why not?

## Changelog

:cl:
balance: AI Uploads block law changes until at least 5 minutes pass past roundstart.
/:cl:

### CODE REVIEW

**Comment by tralezab** [comment]
I'm considering 10 minutes but I don't want to accidentally block any antagonist actions. Thoughts?

**Comment by GuillaumePrata** [comment]
I think 10 minutes would be better, it cuts on antagonists rushing tech storage to subvert Silicons before Security even geared up from their lockers.

**Comment by LemonInTheDark** [comment]
I'm not a fan of limits like this. they smell weird, and break the sandbox

**Comment by Shadowflame909** [comment]
should just send admins a ping that someone changed the laws before 10 minutes!

**Comment by Snowyypanda** [comment]
> I'm considering 10 minutes but I don't want to accidentally block any antagonist actions. Thoughts?

you're fine, no antag is ever gonna go for the hacked laws in the first 10 minutes unless they want to speedrun hacking ai which is rarely done

**Comment by tralezab** [comment]
> should just send admins a ping that someone changed the laws before 10 minutes!
> 
> Edit: or we let ai players know this is against the rules and have them bwoink the admin themselves

@LemonInTheDark better idea?

**Comment by LemonInTheDark** [comment]
image

**Comment by tralezab** [comment]
i was convinced otherwise

**Pull request closed without merging**
