### PR TITLE
Synthesizers and headphones can now have circuits!

### PR DESCRIPTION
**Pull request by Ghommie**
## About The Pull Request
A circuit and shell components have been added to Synthesizers (headphones and spacepods included, though with a reduced capacity because of their size), so they can now be used for wiremod. Just like for instant cameras, no shell design here. They are meant to be found in dorms or maybe ordered from cargo.

## Why It's Good For The Game
The station outside the sci department has plenty of USB ports stuff but is lacking when it comes to circuits shell. This is another small step toward a better and more applicable wiremod.

## Changelog

:cl:
expansion: Synthesizers and headphones can now have circuits installed.
/:cl:

### CODE REVIEW

**Comment by Ghommie** [comment]
> 
> 
> What is a synthetizer?

https://en.wikipedia.org/wiki/Synthesizer

**Comment by Farquaar** [comment]
This could be big.

**Comment by Nebulacrity** [comment]
Do Decker Headphones also get affected by this change? They're headphones, so that probably should be the case.

**Comment by TheBonded** [comment]
> Do Decker Headphones also get affected by this change? They're headphones, so that probably should be the case.

afaik all headphones that allow you to play music are subtypes of the main synthesizer and thus *should* be already included in this, as is.

**Comment by Nebulacrity** [comment]
> > Do Decker Headphones also get affected by this change? They're headphones, so that probably should be the case.
> 
> afaik all headphones that allow you to play music are subtypes of the main synthesizer and thus _should_ be already included in this, as is.

Fingers crossed!

**Comment by Ghommie** [comment]
> 
> 
> Do Decker Headphones also get affected by this change?

Currently no, but on second thought, I'll let it happen.

**Comment by Nebulacrity** [comment]
> > Do Decker Headphones also get affected by this change?
> 
> Currently no (that's a typo in the PR description), but on second thought, I'll let it happen. EDIT: done.

Thanks!

**Comment by Ghommie** [comment]
Uh, I forgot something important.

**Comment by Ghommie** [comment]
Super ready and super tested.

**Pull request merged**
