### PR TITLE
Removes old player panel

### PR DESCRIPTION
**Pull request by Jordie0608**
Old player panel is gone and the new one has been given it's name.

No real reason to keep the old one around, it's outdated and less functional.
# funremovalsquad

### CODE REVIEW

**Comment by tedward1337** [comment]
Muh fun

**Comment by MrStonedOne** [comment]
you forgot to change the name in hotkey help.

**Comment by Alek2ander** [comment]
:-1::-1::-1::-1::-1::-1::-1::-1::-1::-1::-1::-1::-1::-1::-1::-1::-1::-1::-1::-1::-1::-1::-1::-1::-1::-1::-1:
:-1::-1::-1::-1::-1::-1::-1::-1::-1: OLD PANEL IS BETTER :-1::-1::-1::-1::-1::-1::-1::-1::-1::-1:
:-1::-1::-1::-1::-1::-1::-1::-1::-1::-1::-1::-1::-1::-1::-1::-1::-1::-1::-1::-1::-1::-1::-1::-1::-1::-1::-1:

**Comment by Stickymayhem** [comment]
Thank you so much I misclick the old shit one too often.

**Comment by Cheridan** [comment]
Discussed with adminbus, support seems to be for removal. Statistics show that the old one is used much less, and often right before opening the new one (misclick)

**Pull request merged**
