### PR TITLE
Makes Grille code a bit more sensible and simpler

### PR DESCRIPTION
**Pull request by Firecage**
Basically what it says in the title says everything.

Though, I am still trying to figure out how to make it so that it only repairs grille if the rods you are using is the same as the rods_type, but also that if its rods_type is normal rods, that cyborg rods can still repair that grille.

### CODE REVIEW

**Comment by XDTM** [comment]
Is the borg rod type is something like metal_rod/cyborg you can use a normal istype, since it accepts subtypes

**Comment by Firecage** [comment]
XDTM. Thats not really what I mean though. Eh. Anyway.

**Comment by Supermichael777** [comment]
Byond has istype() but no is() as fat as i know. ¯\_(ツ)_/¯ you use the pipe | in a check as an or for some reason.

**Comment by optimumtact** [comment]
it's ||

**Pull request merged**
