### PR TITLE
Animated Animals

### PR DESCRIPTION
**Pull request by Nabski89**
:cl:
add: Some animals now move their legs when they walk.
/:cl:

I feel movement states add visual value to the game, so I have added them for the following simple animals. Chicken (3 colors), Tomato, 6 Species of spiders (Oh my god so many legs to move), Mice (3 colors), Frog (Only default one seen in game), Migo. I've VV tested all of these on the server over time and they work. 3 Frames per creatures (on .2 second delays). All four directions (except mi-go which does not have directional sprites).

### CODE REVIEW

**Comment by subject217** [comment]
tomato?

**Comment by BebeYoshi** [comment]
Video please? uwu

**Comment by Nabski89** [comment]
tomatoes
It's 15 dudes. They don't fit on the screen in the nice conga line needed to show animation.

**Comment by Therapist1** [comment]
vid or it wasn’t did

**Comment by Grazyn** [comment]
this when?

walk

**Comment by evsey9** [comment]
Never

**Comment by YakumoChen** [comment]
when you sprite animations for every single wearable or wieldable item that isn't a backpack or headwear

**Review by SpaceManiac — APPROVED** [review]

**Comment by nicbn** [comment]
Now animate hoomans

**Comment by nicbn** [comment]
You should make the animation stop when the mob is not moving

**Comment by SpaceManiac** [comment]
>You should make the animation stop when the mob is not moving

This is already the case

**Comment by nicbn** [comment]
oops

**Pull request merged**
