### PR TITLE
Choose your own Objective

### PR DESCRIPTION
**Pull request by Jacquerel**
## About The Pull Request

image
image

This PR adds the ability for solo antagonists (Traitor, Changeling, Heretic, Wizard, Malfunctioning AI, and Ninja) to "write-in" their own objectives in place of the ones the game gave them.
For traitors this is located on the uplink (though the button is not present if you aren't the owner of the uplink, thieves can't give you a troll objective) and for everyone else it is on the antagonist information panel.

Pressing this button will replace all of your objectives _except_ ones like "escape alive" or "survive" or "die a glorious death".
By default a player can only do this once per round, but the Traitor Panel admin tool contains a button which can display the prompt again.

Custom-entered objectives are not mechanically tracked in any way and do not report success or failure on the round end screen, whether they were successful or not is up to you the audience. Resultingly, doing this will make you ineligible for getting the hardcore random points from completing your objectives.

Admins are capable of using this button to show the prompt to _any_ antagonist, including team antagonists, but do so at their own risk. A single cultist changing their objective to something else only updates them, not their team.
Admins can also choose whether or not it replaces existing objectives or just adds a new one entered by the player.

When someone sets a new objective, it informs any active administrators of their choice and provides linked buttons to send them a syndicate radio message or immediately smite them, because unfortunately our players cannot always be trusted with arbitrary text entry.
I _didn't_ make this a system which requires approval because I don't think admins _want_ that level of micromanagement, although plausibly if it is thought to be a good idea I could add a time delay and reject button similar to the "rename the station" charter item.

Heretics work slightly differently and have an "Are you sure?" confirmation other antagonists lack.
This is because Heretic objectives are directly tied to ascension, thus by replacing the objectives you are locking yourself out from being able to do it.
I don't _necessarily_ think this is a terrible thing, because "try to ascend" _is_ the default objective. There's no point entering a new one if that is what you want to do anyway.

While I was in here I gave Ninjas a very rudimentary custom antagonist panel, because they didn't have one.
I also made their C4 display where it can be detonated on examine, in case you no longer have the relevant objective to reference.

<details>
  <summary>Other previews</summary>
  
  image
  image
  image
  image
  image
</details>

## Why It's Good For The Game

It's a reasonably frequent refrain that "Objectives are just guidelines" and that more interesting players should strive to ignore them and do something else, I would hope this would encourage that kind of behaviour.
If you _are_ going off and doing your own thing, now other players can actually see what it was that you were trying to do when the round ends (and judge you based on whether you actually did it).

## Changelog

:cl:
add: Traitors, Changelings, Heretics, Wizards, Malfunctioning AIs, and Ninjas can now all reject their original objectives and provide one of their own in its place. A Heretic doing this will no longer be able to ascend.
add: "Custom" objectives which aren't mechanically tracked will no longer report success or failure upon round end.
qol: Space Ninja spider charges will now display where they can be detonated when examined, if you are a ninja.
/:cl:

### CODE REVIEW

**Comment by Time-Green** [comment]
This probably should prevent hardcore random from doubling your points, considering you can give yourself free greentexts

**Comment by Livrah** [comment]
Even less paranoia-threat in game than after prog tot addition. Heretics now is the only ones who feels like antagonist for a random crew.

**Comment by DaydreamIQ** [comment]
This is great. Antags already had a pass to do whatever they want outside their objectives so now you can at least set yourself a personal goal. (And anything is better than current ninja goals)

**Comment by AdamElTablawy** [comment]
> Even less paranoia-threat in game than after prog tot addition. Heretics now is the only ones who feels like antagonist for a random crew.

Considering traitors ignored their objectives anyway to do what they wanted, typically, there’s no real change in the paranoia factor.

**Comment by zxaber** [comment]
Rather than always marking them successful, the round-end should just not give a verdict at all. Simply list the objectives that were written in, without the pass/fail.

**Comment by SimplySmiley123** [comment]
> Rather than always marking them successful, the round-end should just not give a verdict at all. Simply list the objectives that were written in, without the pass/fail.

Yeah.

**Comment by JoshAdamPowell** [comment]
This is an absolutely brilliant PR

**Review by Timberpoes — APPROVED** [review]
image

**Pull request merged**
