### PR TITLE
replaces gold bars in vault with gold coins

### PR DESCRIPTION
**Pull request by ghost**
~~shoutout to kevinz for powergaming endlessly as a roundstart vtec secborg and then pretending he's robust~~

### CODE REVIEW

**Comment by hornygranny** [comment]
things that should not be a problem and yet are

**Comment by kevinz000** [comment]
........................

**Comment by AlexanderUlanH** [comment]
I died nerf it: the PR :+1:

**Comment by kevinz000** [comment]
I vteced up to him and flashed him and killed him in a nookawps round.
Hey, better than the AIs who turn off env to prevent syndiborg

**Comment by optimumtact** [comment]
Administrative rather than technical issue and shouldn't be merged on those grounds unless our policy changes
 :-1:

**Comment by Iamgoofball** [comment]
this is an admin issue with the players on the server and not a code/mapping issue

:-1: this is valve-tier "bugfixing" which is "1 thing is broken, remove every trace of the feature"

**Comment by Cheridan** [comment]
No admin on /tg/station will ever take action against a borg just for removing the gold from the vault so he can powergame.

**Comment by Iamgoofball** [comment]
you raise a good point

so i raise you a better fix

**Comment by paprka** [comment]
Goofball's change doesn't properly address this issue.

**Comment by MrStonedOne** [comment]
<MrStonedOne> paprika, the silver ore in mining is not enough to make vtec
<MrStonedOne> paprika, the silver ore in mining is not enough to make vtec
<MrStonedOne> paprika, the silver ore in mining is not enough to make vtec
<MrStonedOne> paprika, the silver ore in mining is not enough to make vtec
<MrStonedOne> paprika, the silver ore in mining is not enough to make vtec
<MrStonedOne> paprika, the silver ore in mining is not enough to make vtec
<MrStonedOne> paprika, the silver ore in mining is not enough to make vtec
<MrStonedOne> paprika, the silver ore in mining is not enough to make vtec
<MrStonedOne> paprika, the silver ore in mining is not enough to make vtec
<MrStonedOne> paprika, the silver ore in mining is not enough to make vtec
<MrStonedOne> paprika, the silver ore in mining is not enough to make vtec
<MrStonedOne> paprika, the silver ore in mining is not enough to make vtec
<MrStonedOne> paprika, the silver ore in mining is not enough to make vtec
<MrStonedOne> paprika, the silver ore in mining is not enough to make vtec
<MrStonedOne> paprika, the silver ore in mining is not enough to make vtec
<MrStonedOne> paprika, the silver ore in mining is not enough to make vtec
<MrStonedOne> paprika, the silver ore in mining is not enough to make vtec
<MrStonedOne> paprika, the silver ore in mining is not enough to make vtec
<MrStonedOne> paprika, the silver ore in mining is not enough to make vtec
<MrStonedOne> paprika, the silver ore in mining is not enough to make vtec
<MrStonedOne> paprika, the silver ore in mining is not enough to make vtec
<MrStonedOne> paprika, the silver ore in mining is not enough to make vtec
<MrStonedOne> paprika, the silver ore in mining is not enough to make vtec
<MrStonedOne> paprika, the silver ore in mining is not enough to make vtec
<MrStonedOne> paprika, the silver ore in mining is not enough to make vtec
<MrStonedOne> paprika, the silver ore in mining is not enough to make vtec
<MrStonedOne> paprika, the silver ore in mining is not enough to make vtec
<MrStonedOne> paprika, the silver ore in mining is not enough to make vtec
<MrStonedOne> paprika, the silver ore in mining is not enough to make vtec
<MrStonedOne> paprika, the silver ore in mining is not enough to make vtec
<MrStonedOne> paprika, the silver ore in mining is not enough to make vtec
<MrStonedOne> paprika, the silver ore in mining is not enough to make vtec
<MrStonedOne> paprika, the silver ore in mining is not enough to make vtec
<MrStonedOne> paprika, the silver ore in mining is not enough to make vtec
<MrStonedOne> paprika, the silver ore in mining is not enough to make vtec
<MrStonedOne> paprika, the silver ore in mining is not enough to make vtec
<MrStonedOne> paprika, the silver ore in mining is not enough to make vtec
<MrStonedOne> paprika, the silver ore in mining is not enough to make vtec
<MrStonedOne> paprika, the silver ore in mining is not enough to make vtec
<MrStonedOne> paprika, the silver ore in mining is not enough to make vtec
<MrStonedOne> paprika, the silver ore in mining is not enough to make vtec
<MrStonedOne> paprika, the silver ore in mining is not enough to make vtec
<MrStonedOne> paprika, the silver ore in mining is not enough to make vtec
<MrStonedOne> paprika, the silver ore in mining is not enough to make vtec
<MrStonedOne> paprika, the silver ore in mining is not enough to make vtec
<MrStonedOne> paprika, the silver ore in mining is not enough to make vtec
<MrStonedOne> paprika, the silver ore in mining is not enough to make vtec
<MrStonedOne> paprika, the silver ore in mining is not enough to make vtec
<MrStonedOne> paprika, the silver ore in mining is not enough to make vtec
<MrStonedOne> paprika, the silver ore in mining is not enough to make vtec
<MrStonedOne> paprika, the silver ore in mining is not enough to make vtec
<MrStonedOne> paprika, the silver ore in mining is not enough to make vtec
<MrStonedOne> paprika, the silver ore in mining is not enough to make vtec
<MrStonedOne> paprika, the silver ore in mining is not enough to make vtec
<MrStonedOne> paprika, the silver ore in mining is not enough to make vtec
<MrStonedOne> paprika, the silver ore in mining is not enough to make vtec
<MrStonedOne> paprika, the silver ore in mining is not enough to make vtec
<MrStonedOne> paprika, the silver ore in mining is not enough to make vtec
<MrStonedOne> paprika, the silver ore in mining is not enough to make vtec
<MrStonedOne> paprika, the silver ore in mining is not enough to make vtec
<MrStonedOne> paprika, the silver ore in mining is not enough to make vtec
<MrStonedOne> paprika, the silver ore in mining is not enough to make vtec
<MrStonedOne> paprika, the silver ore in mining is not enough to make vtec
<MrStonedOne> paprika, the silver ore in mining is not enough to make vtec
<MrStonedOne> paprika, the silver ore in mining is not enough to make vtec
<MrStonedOne> paprika, the silver ore in mining is not enough to make vtec
<MrStonedOne> paprika, the silver ore in mining is not enough to make vtec
<MrStonedOne> paprika, the silver ore in mining is not enough to make vtec
<MrStonedOne> paprika, the silver ore in mining is not enough to make vtec
<MrStonedOne> paprika, the silver ore in mining is not enough to make vtec
<MrStonedOne> paprika, the silver ore in mining is not enough to make vtec
<MrStonedOne> paprika, the silver ore in mining is not enough to make vtec
<MrStonedOne> paprika, the silver ore in mining is not enough to make vtec
<MrStonedOne> paprika, the silver ore in mining is not enough to make vtec
<MrStonedOne> paprika, the silver ore in mining is not enough to make vtec
<MrStonedOne> paprika, the silver ore in mining is not enough to make vtec
<MrStonedOne> paprika, the silver ore in mining is not enough to make vtec
<MrStonedOne> paprika, the silver ore in mining is not enough to make vtec
<MrStonedOne> paprika, the silver ore in mining is not enough to make vtec
<MrStonedOne> paprika, the silver ore in mining is not enough to make vtec

**Comment by AlexanderUlanH** [comment]
:-1: This is a large sweeping nerf to R&D in the rounds where R&D is already least valuable, those when nobody is mining.  If the VTEC's too powerful to be built at roundstart, increasing the cost of the VTEC beyond the amount of resources available at roundstart is a much more sensible solution.

**Comment by Firecage** [comment]
Oooor, you know. You COULD just make Vtec require uranium instead of gold, and then leave the gold in the vault.

**Pull request closed without merging**
