### PR TITLE
Golems can wear labcoats

### PR DESCRIPTION
**Pull request by coiax**
:cl: coiax
add: Golems can now wear labcoats.
/:cl:

The creatures created in Science can now dress up as smart as the
scientists that created them. So it's cool.

image

### CODE REVIEW

**Comment by Repukan** [comment]
Slippery slope into making them a roundstart race.

Not being able to wear clothing is part of their identity and gameplay

**Comment by MoreRobustThanYou** [comment]
They should be able to wear "loose" clothing like labcoats

**Comment by duncathan** [comment]
I would love to make golems a roundstart race now exclusively to spite @Repukan

**Comment by vuonojenmustaturska** [comment]
roundstart catgolems when

**Comment by ma44** [comment]
Nothing can possibly go wrong with making a 55 armor, more thicc punches species that only has a slowdown and no human a round start race.

**Comment by FantasticFwoosh** [comment]
This PR is very typical of a smooth-brain coder; trying to alter a rock man to wear a tie & shirt like some cartoon where everyone wears clothes up until the waist down. Then adding them to roundstart just to abuse them until they get nerfed & cease to be important or special anymore.

This is the future liberal coders supporting this PR want.

**Comment by Iamgoofball** [comment]
@FantasticFwoosh are you going to stop mad-libbing r/the_donald

**Comment by JohnOxford** [comment]
goof your headmin slogan was literally make tg great again

stop

its not funny, its not ironic, its degenerate.

you are all degenerates

remove

**Pull request merged**
