### PR TITLE
Switches required version to 514

### PR DESCRIPTION
**Pull request by AnturK**
Switches minimum required version to 514.1554 and removes extools.
@tgstation/commit-access Too soon or not ? Speak up please if you have opinion.

Will need #58630 merged for compile to pass.
And seems SpacemanDMM needs minor version bump.

### CODE REVIEW

**Comment by maxymax13** [comment]
this is like the 3rd one

**Comment by celotajstg** [comment]
and hopefully the one that gets merged

**Comment by willox** [comment]
This should wait at least until we've seen a server running 514.1554 with https://github.com/tgstation/tgstation/pull/58630 merged. The minimum BYOND version can't be one we don't even know works.

**Comment by Mothblocks** [comment]
> this is like the 3rd one

i think its the 1st one from an actual maintainer though

**Comment by LemonInTheDark** [comment]
I'm a bit worried about stability, but that's what testing is for babyyyyyyyy

**Comment by MrStonedOne** [comment]
You can not bump the min compiler version until there is a reason to.

we can make linters/github action compiler use 514, but until we use a 514 specific feature, or run into a server bug only 514 fixes, the min version **MUST** remain 513

**Comment by MrStonedOne** [comment]
bump the compiler version used in dependencies/build scripts/github actions to 514.

revisit bumping the min version in a month or so.

**Comment by Mothblocks** [comment]
> bump the compiler version used in dependencies/build scripts/github actions to 514.

they did:

image

**Comment by Mothblocks** [comment]
it's not compiling because https://github.com/tgstation/tgstation/pull/58630 isn't merged

**Comment by MrStonedOne** [comment]
I was implying they should **only** do that

**Comment by MrStonedOne** [comment]
And leave the required compiled version at 513, along with the 513/514 ifdefs.

There should be a compelling reason to require a beta release to compile the game. Im not seeing one.

**Comment by LemonInTheDark** [comment]
it'll be nice to have access to send map profile logs, but that's most likely not gonna be stable for a hot second

**Comment by AnturK** [comment]
The compelling reason is removing extools, and stopping "How do i compile with latest stable?" questions.

**Comment by MrStonedOne** [comment]
> The compelling reason is removing extools, and stopping "How do i compile with latest stable?" questions. 

Do that in a seperate pr down the line. Step 1 to moving to a new major byond version has always been to first move tests/ci over to the new version.

then, later, move the game servers to the new version.

then, later, move the required compile version to the new version and allow widespread use of the new features.

You are trying to skip to the end here and im not going to let it happen.

**Comment by MrStonedOne** [comment]
> removing extools

extools is not nor has not been required to run the game servers.

Just do for 513 what extools does when it can't find the dll, and default the map tick value to `20` which is what the mc used before extools and maptick was a thing.

**Comment by LemonInTheDark** [comment]
Why remove extools if we still have a use for it? Shouldn't we just leave things as they are until 514 is stable and tested, and we have a feature we want to implement or make use of?

**Comment by tralezab** [comment]
I want to implement a feature from 514 :^(

**Comment by AnturK** [comment]
I'll need to do building SDMM as part of CI as separate PR first

**Pull request closed without merging**
