### PR TITLE
Removes the internals button

### PR DESCRIPTION
**Pull request by MrPerson**
There's already an action button for this.

### CODE REVIEW

**Comment by Bawhoppen** [comment]
brutal nerfs :-1:

**Comment by TechnoAlchemisto** [comment]
Please god no, they don't even need to be an action button in the first place

**Comment by Bawhoppen** [comment]
@TechnoAlchemisto actually action buttons are useful too so you can more easily select which tank you want to use

**Comment by TechnoAlchemisto** [comment]
They're so big!!

**Comment by Bawhoppen** [comment]
thats whats nice about them

**Comment by TechnoAlchemisto** [comment]
i love the internals hud icon and it it leaves I am going to cry

**Comment by bgobandit** [comment]
fuck this shit, no, if you have even a couple action buttons it's already hard enough to find shit, let alone when you're dying of oxyloss

**Comment by Supermichael777** [comment]
if oxyjetpack had a different icon for internals sure else duck of

**Comment by KazeEspada** [comment]
Personally, Id rather see the action button leave than the internals indicator.

**Comment by PKPenguin321** [comment]
i pretty much exclusively use the internals action button pls no

**Comment by kevinz000** [comment]
What does this change bring to our game that is beneficial? :) (no pls)

**Comment by Shadowlight213** [comment]
:-1: action buttons are sooo fucking ugly. just remove internals action buttons tbh. If you want to select a tank, use the tank inhand or something.

**Comment by Lumipharon** [comment]
Fuck off.

The hud button is useful. 
The action buttons clog up what is already the most crowded shit in the UI.

**Comment by demonfiren** [comment]
Hahaha, no.

**Comment by lzimann** [comment]
big :-1:

**Comment by peoplearestrange** [comment]
Why move something as vital as that from where we ALL know where it is and is on 99% of other speesmens code?

**Comment by CosmicScientist** [comment]
It's easier to understand when you're new and to build off of peoplearestrange's comment,
It's easiest to remember what to do by visual familiarity, if other code bases have it and we do not, that makes it harder for population migration.

Also I only realised what the tank action buttons did well after their addition and only understood how to use them to switch which tank I was using even further after. If I only had just that then I might have learnt it sooner but it's not exactly obvious when there's no breath mask or "using" and "switch" words written on the buttons. That and what everyone else already said about screen clutter. Oh and the button is closest to both breathing alerts for quick and intuitive reaction.

**Comment by Mercenaryblue** [comment]
Remove the action button not the HUD

**Comment by Niknakflak** [comment]
:-1:

**Comment by KorPhaeron** [comment]
This does not seem very popular

**Pull request closed without merging**
