### PR TITLE
Hatchets are now small instead of tiny.

### PR DESCRIPTION
**Pull request by DaxDupont**
[Changelogs]: 

:cl: Dax Dupont
balance: Hatches are now small instead of tiny.
/:cl:

[why]: Cultivators are small, hatches are tiny like a analyzer. 
This seems weird and was probably not intended.

### CODE REVIEW

**Review by ShizCalev — APPROVED** [review]

**Comment by ExcessiveUseOfCobblestone** [comment]
probably alright considering botany can make carrot shivs.

**Comment by Spaceinaba** [comment]
does this mean I cant shotgun people into crit with a pnumatic cannon full of hatchets

**Comment by DaxDupont** [comment]
I think you already can.
This actually makes hatchets BIGGER

**Comment by Bombpants** [comment]
@DaxDupont That means you can fit less in the cannon at a time

**Comment by Teepeepee** [comment]
RIP my 7 hatchet pneumatic cannon meme, it wasn't good anyways.

**Pull request merged**
