### PR TITLE
Decreases spookiness

### PR DESCRIPTION
**Pull request by Tacolizard**
the old sprite looked crappy so here's my try at it.

inhand, mask down
mask down

inhand, mask up
maskup

on player, mask down
pmaskdown

**old sprite**

inhand, mask down
blah

even worse, the bug-like player sprite
bladhsa

### CODE REVIEW

**Comment by Armhulen** [comment]
more in theme :+1:

**Comment by kevinz000** [comment]
this looks worse

**Comment by Armhulen** [comment]
I suppose the sprite could use some work yeah

**Comment by Tacolizard** [comment]
@kevinz000 you gotta be kidding me

**Comment by Qbopper** [comment]
can someone post the OG sprite for those of us who don't play

**Comment by ExcessiveUseOfCobblestone** [comment]
If you post the oldsprite then that little nostalgia feeling in your heart compels you to downvote tho!

**Comment by ExcessiveUseOfCobblestone** [comment]
also this is a tweak, in MY FEATURE FREEZE???

**Comment by Qbopper** [comment]
ah, thanks, had forgotten what it looked like

new sprite looks better theme wise but in execution I'm not a fan, maybe it could use some work

**Comment by Armhulen** [comment]
I know this is now in the feature territory but just call it reinforced gas mask and give it armor

**Comment by Tacolizard** [comment]
@ExcessiveUseOfCobblestone sprite change != feature

**Comment by Fox-McCloud** [comment]
This does look worse; I don't like it at all---I'm all for something fitting better, thematically, but this isn't it.

**Comment by PKPenguin321** [comment]
In game pics need

**Comment by Iamgoofball** [comment]
This adjusts hitboxes

:-1: close for freeze

**Comment by kevinz000** [comment]
I feel like the skull was part of the design :/

**Comment by GunHog** [comment]
The skill IS part of the design, it is why the description has "Looks like a skull - clearly designed by a nerd.". It is made in R&D, so that is quite fitting! The new one removes the item's flavor, making it bland and generic like all the other gas masks. I sometimes like to wear it because it looks cool.

:-1: from me on the grounds that it looks cool, and this one is boring.

**Comment by uraniummeltdown** [comment]
Actually looks pretty cool, the skull sprite was always pretty ehhh
Could use some work but 👍

**Comment by RemieRichards** [comment]
the skull is not part of the design at all, it's a reused sprite with a minor edit (cyborg visor or something, ancient ass sprite+item) so it has a window in it.
it's the height of laziness.

anything would be an improvement.

**Comment by Iamgoofball** [comment]
chrome_2017-03-30_01-13-54
?????????????????????????

**Comment by RemieRichards** [comment]
Yes goof, because a description, one singular string, surely proves something's legitimacy.
They took the cyborg visor sprite, edited it lightly, and covered their ass with a description, what about that don't you get?

**Comment by uraniummeltdown** [comment]
The skull is really lame, Taco's sprite is pretty cool

**Comment by FantasticFwoosh** [comment]
Just make a sec riot mask, but paint it white with purple eyes and a big N on the forehead or something.

Taco's sprite is alright, i can see why people might find the novelty of the skullmask but you do need something minimalistic since the facesprite matters more. The sec riot mask fits on the full face reliably, and i do like taco's sprite in part because its a upgrade to a gasmask you see nearly all scientists wearing.

**Comment by GunHog** [comment]
That sprite is actually an improvement that looks cool and stands out. I vote to replace the PR's sprite with that one.

**Comment by Tacolizard** [comment]
@FantasticFwoosh I like that sprite, but I feel like it's "over-cool" for something simple like the welding gas mask. It also looks too much like a secmask.

**Comment by GunHog** [comment]
That is rather boring, if you ask me.

**Comment by ExcessiveUseOfCobblestone** [comment]
Making something ugly as a means of diverting powergamers seems like 1) an odd way to go about it and 2) a balance issue :^)

**Comment by Cyberboss** [comment]
It's been like 3 days and this freeze is already a meme

**Comment by Tacolizard** [comment]
@ExcessiveUseOfCobblestone stop taking what I say and describing it badly ree

It's not intentionally "ugly". That's subjective, and I personally think it looks cool. The goal here is to get rid of a lazy reused ancient sprite and replace it with something that makes more logical sense.

**Comment by Haevacht** [comment]
Dumb.

**Comment by WJohn** [comment]
Yeah this sprite doesn't look terribly good. Our current one is dorky, sure, but I think we could do better than this. Admittedly our current one doesn't look like an actual GAS MASK more than simple a mask (that looks like a skull).

Still, 👎 for now. Maybe I'll try something myself if I'm feeling up to it, I dunno.

**Comment by xxalpha** [comment]
Why? You're just making it look like the existing gas mask, awful idea. :-1:

**Comment by Cheridan** [comment]
ppl no rikey

**Pull request closed without merging**
