### PR TITLE
Nuke UI Overhaul

### PR DESCRIPTION
**Pull request by actioninja**
I spent a ridiculous amount of time on this.

## About The Pull Request

Fancy title because I'm quite proud of this one.
image
Video demo: https://cdn.discordapp.com/attachments/326826573951008769/647273642937548800/2019-11-21_19-13-20.mp4

Arm order now works like:
input disk
input nuke code, press E
input time, press E
press ARM to activate
press ARM again to deactivate (with disk)
press C to clear code input while ready but not armed

## Why It's Good For The Game

hell yearh

## Changelog
:cl:
add: Nuke UI has been completely reworked for tgui-next
/:cl:

### CODE REVIEW

**Comment by Tharcoonvagh** [comment]
E

**Comment by nicbn** [comment]
`the bomb has been planted`

**Comment by Dorsisdwarf** [comment]
what happened to the delta level / nuke armed siren?

**Comment by actioninja** [comment]
I don't really know, I didn't (deliberately) change anything relating to that.

**Comment by TheVekter** [comment]
That is absolutely stellar.

**Comment by ATH1909** [comment]
This also applies to the beer nuke, yes?

Also, did you update the nuke op tutorial paper to account for these changes?

**Comment by Tharcoonvagh** [comment]
Put a  big red S on the syndie nuke ui instead of the nt logo

**Comment by TheChosenEvilOne** [comment]
> 
> 
> Put a big red S on the syndie nuke ui instead of the nt logo

The syndicate nuclear bomb is stolen from NT
see comment: https://github.com/tgstation/tgstation/blob/master/code/modules/antagonists/nukeop/equipment/nuclearbomb.dm#L73

**Comment by actioninja** [comment]
@ATH1909 I have no idea what you're talking about with nuke tutorial paper. It probably exists but I actually don't know what or where it is.

**Comment by TheVekter** [comment]
> @ATH1909 I have no idea what you're talking about with nuke tutorial paper. It probably exists but I actually don't know what or where it is.

There's a paper that used to spawn on top of the nuke in the Syndie shuttle explaining how to arm it. I don't know if it's still there or not.

**Review by stylemistake — DISMISSED** [review]
Looks and feels awesome, was able to detonate the showroom bomb as well (although I had to change the r_code to something enterable by the keypad, default is "ADMIN").

One minor thing which could be improved, is when one step away from arming, pressing "C" should go back to time entry mode instead of completely resetting, but this is just a minor inconveniece.

I'd merge it now, but I'm not sure if you'd like to commit more. I preemptively approve this.

**Comment by actioninja** [comment]
image
??

**Comment by MCterra10** [comment]
wasn't this from unitystation?

**Comment by actioninja** [comment]
No? This ui was made completely from scratch off of a concept sketch style made.

**Pull request merged**
