### PR TITLE
Changeling Tentacles are less lethal on harm intent

### PR DESCRIPTION
**Pull request by ChangelingRain**
:cl: Joan
tweak: Impaling someone with a sharp item by pulling them with a changeling Tentacle now does significantly less damage and stuns for less time.
/:cl:

From double damage, ie, 50 with an armblade, to normal damage, ie, 25 with an armblade. The damage still ignores armor, of course.
Stun from Weaken(4) to Weaken(2), which is from 6-8 seconds to 2-4 seconds.

### CODE REVIEW

**Comment by jughu** [comment]
Just remove the stun tbh

**Comment by XDTM** [comment]
I'm not sure if it's worth keeping it in; when i coded it i was influenced by dishonored 2's grab spell, but it doesn't translate too well to ss13. The stun on hit should be enough.

**Comment by Robustin** [comment]
Why should it ignore armor, I mean I get that its DESIGNED to impale people but someone wearing a security hardsuit shouldn't get their shit fucked quite as easily as someone in a jumpsuit.

**Comment by ShadowDeath6** [comment]
good branch name fam

**Comment by Robustin** [comment]
On 2nd thought, why not just make the tentacle "pure" to its intent?

Help: Ranged hug
Disarm: Ranged disarm and/or steal
Grab: Pull and (nerfed) stun
Harm: 25 damage

**Comment by XDTM** [comment]
Armor piercing was not intended; i misused the proc when coding it.
I like @Robustin's idea, although i saw help intent as a tentacle used to get someone out of trouble.

**Comment by Robustin** [comment]
Yea but the meme potential of ranged tentacle hug is too good.

**Comment by Haevacht** [comment]
Rule 8 banned CJS.

**Comment by Robustin** [comment]
Nah just make the emote "______ launches a tentacle and hugs ______ in a completely innocent manner. Awww!"

**Comment by kevinz000** [comment]
@Haevacht WORKING AS INTENDED!!!!!

**Comment by Nabski89** [comment]
You didn't change the description in the cellular emporium. It still says it stuns.

**Pull request merged**
