### PR TITLE
Adjustable goliath cloaks (Made some errors with the commits, made a fresh pr.)

### PR DESCRIPTION
**Pull request by Dawnseer**
## About The Pull Request
I've enabled goliath cloaks to be alt clicked to adjust it to neck slot instead of over clothing slot, and while in neck slot, it has no armor values for balance purposes, while in over clothing slot, it has the same armor values as usual.
Hood has the same values as usual, as it still inhabits the same slot as usual.

image
image
image
## Why It's Good For The Game
It enables a cloak to function like a cloak. It gives people the option to use it not for armor, but for fashion.
## Changelog
:cl:
add: Goliath cloak can be worn as a cloak that doesn't provide any armor benefits

/:cl:

### CODE REVIEW

**Comment by Mey-Ha-Zah** [comment]
okay I like this idea

**Comment by Dawnseer** [comment]
I have considered it, I have in fact done it while testing. And it doesn't really have any effect. Looks the same as wearing one, and you only have armor from the one on overclothing.

**Comment by Mey-Ha-Zah** [comment]
I have a question, could hooded cloak items, if in the cloak slot, also be used to pull a hood up IF you aren't wearing a helmet?

**Comment by Dawnseer** [comment]
Yes, while before the toggle only worked with oclothing slot, I've done so it functions on both oclothing and neck slot.

**Comment by Dawnseer** [comment]
I may have made some mistakes with  the commits.

**Comment by Dawnseer** [comment]
In fact, doing this over.

**Pull request closed without merging**
