### PR TITLE
Removes a sound

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
Don't think we're allowed to use that after all

### CODE REVIEW

**Comment by Iamgoofball** [comment]
@KorPhaeron i mean, we might be able to argue fair use in parody

**Comment by vuonojenmustaturska** [comment]
we can't CC-BY-SA a parody-only usecase, and our game and context aren't a parody.

**Comment by Iamgoofball** [comment]
ah crap

**Comment by KorPhaeron** [comment]
@Iamgoofball practicing the party line for your CM job app I see

**Comment by Iamgoofball** [comment]
!(crap)[http://i.imgur.com/mx2wZiU.jpg]

**Comment by Kromgar** [comment]
ah... no music  at all when slaughtering people in a blood rage? I am disappoint

**Comment by kevinz000** [comment]
@Kromgar pop me a bwoink and i'll play it for you

**Comment by MimicFaux** [comment]
really should have -something- replace it

**Comment by chaoko99** [comment]
replace it with a doom .mid

That is basically okay because you're essentially sending sheet music also e1m1 is in shareware doom.

**Comment by KorPhaeron** [comment]
Shareware means you can freely distribute the program, not that you can use it in derivative works

**Review by Cyberboss — APPROVED** [review]

**Pull request merged**
