### PR TITLE
Makes medbots unable to inject you if you are are fully covered with THICKMATERIAL.

### PR DESCRIPTION
**Pull request by ShizCalev**
This makes their syringes consistent in that there needs to be exposed flesh for them to be able to inject you. Don't want to be poking holes into space suits, now would you?
  
🆑 ShizCalev
tweak: Medbots are no longer able to inject you if you do not have any exposed flesh.
/🆑

### CODE REVIEW

**Comment by yorii** [comment]
There are already piercing syringes in the game that can do this perfectly well, I don't see any point in this tweak.

**Comment by 81Denton** [comment]
Balance label might be more appropriate since it affects fire/rad/EOD/SWAT/beekeeper suits etc. on top of hardsuits

**Comment by CosmicScientist** [comment]
Would it be better balanced to put it after the emagged check or is it fine to make this a defence against taking your medicine?

**Comment by Anonmare** [comment]
Emagged bots should be able to inject you even if you're wearing  THICKMATERIAL. Because emagged medibots will give your your medicine, by force if necessary.

**Comment by Iamgoofball** [comment]
https://github.com/ShizCalev/tgstation/pull/20

made proposed tweak

**Comment by Mark9013100** [comment]
thiccmaterial

**Comment by epochayur** [comment]
do un-magged medibots still OD you?

**Comment by GunHog** [comment]
No, I took **EXTENSIVE MEASURES** to prevent that. Believe me, it sucked. After that, it even ended up in a situation where someone with tox, burn, and brute damage would be injected with the respective trek chems, creating tricord in the patient. Of course, the medibot, no longer detecting the component chems in the patient, INJECTED MORE COMPONENT CHEMS, leading to an OD of Tricord.

**Comment by Iamgoofball** [comment]
It's almost like readding trekchems was a mistake

**Comment by CosmicScientist** [comment]
Sounds more like readding trekchems got medbots much needed functionality. That is if it does look at the component or reactive chemicals in the body.

**Comment by ExcessiveUseOfCobblestone** [comment]
> There are already piercing syringes in the game that can do this perfectly well, I don't see any point in this tweak.
Why not make it so you can upgrade them with piercing syringes as well to be actually consistent? Piercing syringes are late game tech.

**Pull request merged**
