### PR TITLE
Adds the syndicate lavabase to Icebox

### PR DESCRIPTION
**Pull request by FloranOtten**
## About The Pull Request

Adds the syndicate lavaland outpost to the Icebox map

## Why It's Good For The Game

It's a very neat tutorial, and icebox is exceptionally empty as-is.

## Changelog
:cl:
add: Recent syndicate activity indicates an outpost has been established a planet in your sector. 
/:cl:

### CODE REVIEW

**Comment by FloranOtten** [comment]
> What’s gonna stop people from just dropping into the syndicate base? Are they surrounded by lava/plasma or can they just walk into the station whenever?

They are surrounded by plasma, and if you have the RCD required to drop into it from above you have the RCD required to make a bridge across lava anyway.

**Comment by Doosteroni** [comment]
So the problem I see here is that now all it takes is a Small bomb to blow on the level above the base to simply fall into a chasm into the base

**Comment by Pumpkinoe** [comment]
The difference between breaking through the weak snow roof and bridging across is that there's no turrets shooting at you from above, though, Floran.

**Comment by Pumpkinoe** [comment]
Also you might want to replace the spacesuits with winter coats so that the syndicates can walk out into their outside area by the bar.

**Comment by FloranOtten** [comment]
> The difference between breaking through the weak snow roof and bridging across is that there's no turrets shooting at you from above, though, Floran.

There's no turrets anywhere except the part in front of the bar.

**Comment by FloranOtten** [comment]
> > The difference between breaking through the weak snow roof and bridging across is that there's no turrets shooting at you from above, though, Floran.
> 
> There's no turrets anywhere except the part in front of the bar.

**Comment by FloranOtten** [comment]
> So the problem I see here is that now all it takes is a Small bomb to blow on the level above the base to simply fall into a chasm into the base

You can print RCDs. This means that, unless you specifically carry around a bomb, having to write down coordinates, leg up to the station and then make a bomb is equally as much works as legging up to the station and grabbing an RCD.

**Comment by Doosteroni** [comment]
You can 1, easily get gibonite and 2, aren’t being shot at!

**Comment by FloranOtten** [comment]
> You can 1, easily get gibonite and 2, aren’t being shot at!

Again, the **only** place the base has turrets is the furthest point to bridge. It isn't an issue. And as far as I'm aware, gibtonite cannot breach icemoon's floors

**Comment by Doosteroni** [comment]
Change log grammar is bad

**Comment by Rohesie** [comment]
Can you add more turrets or something, to make invading it a bit harder?

**Comment by Doosteroni** [comment]
This shit stale as hell my dude fix the changelog before I have an aneurism

**Comment by optimumtact** [comment]
it's not lavaland

**Pull request closed without merging**
