### PR TITLE
Adds fidget spinners

### PR DESCRIPTION
**Pull request by RickDipper**
untitled

:cl: optional name here
add: Fidget spinners
/:cl:

Adds a Fidget Spinner to the code which spins when clicked on. Will eventually stop spinning.
Does minor brain damage if you're hit with a thrown one.

### CODE REVIEW

**Comment by Shihrt** [comment]
should deal brain damage on use, not hit

**Comment by lzimann** [comment]
We already denied a fidget spinner pr #27349

**Comment by Anonymous583** [comment]
It should cure brain damage while you spin it.

**Comment by obscolene** [comment]
this codersprite makes me think this guy has already had enough brain damage

**Comment by lzimann** [comment]
Actually I'll just go ahead and close this now. No maintainer liked before, probably none like it now.

**Comment by DoctoreMad** [comment]
Thank

**Pull request closed without merging**
