### PR TITLE
RPED can pick up & install circuit boards in machine frames

### PR DESCRIPTION
**Pull request by SyncIt21**
## About The Pull Request
Read Title

- RPED can pick up both computer circuit boards & machine circuit boards but can only install machine circuit boards. It only stores computer circuit boards for convenience. No other circuit boards are allowed in
- If the RPED has only 1 circuit board in its contents it directly installs it along with the stock parts necessary for that board if they are present in the RPED thus saving you time from clicking again
- If there is more than one circuit board in the RPED then an input list is displayed asking you to select which circuit board you want to install

https://user-images.githubusercontent.com/110812394/211160586-64745806-c58b-4fc1-bc4c-edb6df30eb46.mp4

## Why It's Good For The Game
- Don't need to put them in your backpack so you can save space
- Removes manual installation by hand so the process is much faster

## Changelog
:cl:
add: RPED  can now pick up & install machine circuit boards in machine frames
add: RPED can pick up computer circuit boards for storage convenience but doesn't install them
/:cl:

### CODE REVIEW

**Comment by Ryusenshu** [comment]
I dont really see the point
Boards are already small , there are construction bags they can be stored in and you need to screwdriver to finish it anyway

But i guess i can ask a few questions:
- How does it interact with using the Bluespace RPED via camera?
- Are Engi borgs affected? They do have a module just for picking up circuits after all
  With the RPED module it would double the capacity for boards, or even more

**Comment by SyncIt21** [comment]
> Boards are already small , there are construction bags they can be stored in

They are small but from my experience a duffel bag (the largest backpack a crew member can get) can carry a maximum of 15 circuit boards. Compare that with the maximum storage capacity of 400 inside the RPED it's definitely a bonus

> How does it interact with using the Bluespace RPED via camera

No difference it will just display you an input list prompt in the camera view if you have multiple circuit boards 

> Are Engi borgs affected? They do have a module just for picking up circuits after all
> With the RPED module it would double the capacity for boards, or even more

It works the same for them and yes they would get double the capacity which i see as a good thing.  If any maintainer has a problem with that it's very easy to impose a limit so its not a problem

**Comment by SyncIt21** [comment]
Review Anyone?

**Comment by YakumoChen** [comment]
Don't see the point besides storage creep + hiding contraband boards (uploads, comms) in places nobody will ever check

**Comment by SyncIt21** [comment]
> Don't see the point besides storage creep + hiding contraband boards (uploads, comms) in places nobody will ever check

You can hide the boards in your backpack as well and iwhy wouldn't people check your RPED what's stopping them?
Also unlike your backpack which can literally store anything it's easy to write checks to prevent storing contraband boards and also limit the number of boards stored in the RPED 
How do you not see the point without this PR you usually have to
-Click once to get the circuit board out of your backpack 
-Click again to install the board in the machine frame 
-Click one last time with the RPED on the machine frame to install all stock parts 
With this its an single Click operation to do all 3 of them plus you get the extra space to store boards. 

If any maintainer wants me to limit what type of boards to carry and how much of them I can do that easily.

**Comment by YakumoChen** [comment]
Saving a few mouse clicks doesn't  justify holding an infinite number of circuit boards.

Security is unlikely to search rpds because they only really contain stock parts

Plus you can bloat it with one of every kind of board and fill up someone's screen with useless boards just to make searching more annoying

The best use case I could see would be for boards you might want multiples of like airlocks or APCs, but the RCD already exists for that.

Consider if you actually really want people to be able to hold near-infinite AI uploads, SMESs, or Comms consoles in their bag

**Comment by SyncIt21** [comment]
> 

You literally ignored all the points I made in my previous comment and your repeating yourself again. I'm done arguing

**Comment by SyncIt21** [comment]
> Saving a few mouse clicks doesn't justify holding an infinite number of circuit boards

First stop the using the word infinite the maximum capacity is 400 and like I said if a maintainer wants me to limit the number of boards I can do that but I honestly don't see the harm in carying circuit boards cause you still need to carry metal,  cable and a screw driver to finish the machine in your bag which Security can easily frisk for

> Security is unlikely to search rpds because they only really contain stock parts

Then security is full of morons and need to either learn about my PR or they need to be banned for doing a lousy job. That's a human IQ problem and is not in the scope of this PR.

> Plus you can bloat it with one of every kind of board and fill up someone's screen with useless boards just to make searching more annoying
> 
> The best use case I could see would be for boards you might want multiples of like airlocks or APCs, but the RCD already exists for that.
> 
> Consider if you actually really want people to be able to hold near-infinite AI uploads, SMESs, or Comms consoles in their bag, the only storage cost becomes iron, glass, and cable coil.

My answer 

> If any maintainer wants me to limit what type of boards to carry and how much of them I can do that easily if they feel there is power creep somewhere

And if you checked my other PR #71102 you can carry cable and glass inside your RPED and maintainers were fine with that so I don't see what's the problem

**Comment by Ryusenshu** [comment]
> > First stop using the word infinite the maximum capacity is 400 and like I said if a maintainer wants me to limit the number of boards I can do that but I honestly don't see the harm in carying circuit boards cause you still need to carry metal, cable or RCD for both and then a screw driver and a wrench or a hand drill for both to finish the machine in your bag/toolbelt which Security can easily frisk for
> 
> The problem here was that it lets you carry a trivially large number of computers or machines with just a belt and normal size item (and a few stacks of metal / pocket slot for construction bag I guess)
> 
> There isn't much difference between being able to build 200 AI uploads / SMESs out of half your bag or 800, the point is that you can just build an insane amount of full machines with next to no space.
> 
> But whatever, I guess it'll be fun seeing how easy it'll be to grief with this.

Funny that this didnt even get a discussion or a Balance tag before it got merged
Just happened

**Comment by Sealed101** [comment]
good pr though

**Pull request merged**
