### PR TITLE
Removes ketrazine

### PR DESCRIPTION
**Pull request by optimumtact**
bye felicia

:cl: oranges
del: removes ketrazine
/:cl:

### CODE REVIEW

**Comment by Buggy123** [comment]
But I like Ketrazine, and if you didn't want it in the first place why the fuck was it merged?

**Comment by optimumtact** [comment]
bye felicia

**Comment by Buggy123** [comment]
Who is felicia?

**Comment by PKPenguin321** [comment]
Never heard of this chem before but this looks busted as fuck

**Comment by fludd12** [comment]
https://www.oglaf.com/potion-girlfriend/2/

**Comment by Buggy123** [comment]
I remain confused

**Comment by MMMiracles** [comment]
@Buggy123 anal doesn't count

**Comment by Buggy123** [comment]
THIS INFORMATION HAS ONLY INCREASED MY LEVEL OF CONFUSION.

**Comment by Darkgenerallord** [comment]
Ketrazine is overpowered as fuck, and really not risky to administer to yourself. The side effects either need to occur at any dosage, or it needs to be removed altogether.

**Comment by Kromgar** [comment]
What does ketrazine even do?

**Comment by Darkgenerallord** [comment]
It's near complete stun immunity, nanite level healing, and stim speed. In exchange it causes fairly minor brain damage, and if you take a dosage over 4~ units it's dangerous. 

However, it's pretty easy to just stay on a consistent low dosage and gain all the benefits with zero detriments forever. 

It's not that hard to mix, either, given that I can make sixty units in like two minutes at most.

**Comment by ExcessiveUseOfCobblestone** [comment]
The funny thing is if it wasn't used as some sort of chem self arms-race justification it wouldn't be an issue :thinking:

**Comment by Buggy123** [comment]
I stand by my actions.

**Comment by DaxDupont** [comment]
Yeah remove this crap

**Comment by improvedname** [comment]
Look the chem would have been fine if it didn't require every stun reducing chem and then some gold (which is an catylyst so just grind up some robust gold cigs)

**Comment by Tlaltecuhtli** [comment]
make it require gold

**Comment by AlexTheSysop42** [comment]
@optimumtact At least tell us why you think it should be removed

**Comment by JamesDenholm** [comment]
Surely it'd be fair if it either consumed the gold, or had another, rarer catalyst. Or both?

If the issue that it's quick to make -- and it is, for sure -- Make it *dangerous* to make. Something similar to how meth isn't trivial.

**Comment by ExcessiveUseOfCobblestone** [comment]
Do people not play/not chem enough to understand that reagents intended as helpful still have to be looked at from a malicious usage perspective?

**Comment by JamesDenholm** [comment]
You say that, but really, this thing is explicitly a combat drug and poison. Balancing it around the idea of it being a drug commonly used for healing folks is stupid -- the worst-case malicious use *is* the intended use it should be balanced around.

So, at the end of the day, yeah, it's a strong drug. Instead of nerfing or removing it, though, why not make it *very* difficult to produce, instead? Difficult specifically in the context of the current age of chemistry macros.

**Comment by ExcessiveUseOfCobblestone** [comment]
It was literally pr'd as a "combat stim with heavy downsides".

Regardless of how it was marketed though, it's a dumb drug when we have several flavors of anti-stuns already.

**Comment by Buggy123** [comment]
Dang

**Comment by banthebantz** [comment]
How was this ever added lmao

**Comment by OmegaShoots** [comment]
Was really boring seeing literally every antag using this to basically make any encounter with security a fucking nightmare.

>use your entire arsenal on them
>sorry they don't get stunned and even if you managed to do some decent damage they're at full again anyways
>you also can't outrun them

Yes as a poison it's nice but maybe it should ONLY be a poison with no combat abilities, we already have everything this chem does in other chems (also not as good) and an extremely easy to make "does everything but EVEN BETTER" chem wasn't the right way to add this

Give it a more difficult recipe, remove all the positives and it might be a good poison.

**Pull request merged**
