### PR TITLE
Nerfs changeling armblade

### PR DESCRIPTION
**Pull request by jughu**
I ded NERF PLS
Them being able to destroy plain bolted doors and such with a high damage weapon is TOO op

:cl: Jughu
tweak:Tweaks armblade damage from 25 to 20
/:cl:

### CODE REVIEW

**Comment by kevinz000** [comment]
Not really considering it's a hard tell for ling and a "please lynch me and cremate me" if you start hitting people with it.
Get good.

**Comment by jughu** [comment]
If they didnt destroy the cremator too

**Comment by Aloraydrel** [comment]
Have you tried NOT to die?

**Comment by jughu** [comment]
Have you tried killing a changeling which you cant kill without the use of bombs

**Comment by jughu** [comment]
YOU ARE RIGHT KEVINZ I KNOW A BETTER SOLUTION TO THE PROBLEM

**Comment by calzilla1** [comment]
Oh no

**Pull request closed without merging**
