### PR TITLE
adds the rest of the HFR boxes to birdshot HFR room, some xeno stuff, and a new gaming den

### PR DESCRIPTION
**Pull request by Jackal-boop**
## About The Pull Request

adds the rest of the missing HFR boxes to birdshot HFR room
adds some xeno environmental storytelling to the right-side maintenance of birdshot
adds a abandoned gaming den below arrivals birdshot
## Why It's Good For The Game

atmos techs being able to make their engine is good, some xeno story telling is fun, and a new place for assistants to play blackjack is always appreciated

## Changelog
:cl:
fix: birdshot HFR room now has all of its HFR boxes
map: new birdshot abandoned gaming den and some gross xeno story telling
/:cl:

### CODE REVIEW

**Comment by Maurukas** [comment]
Please add screenshots. Mapdiffbot is not cooperating.

**Comment by Jackal-boop** [comment]
> Please add screenshots. Mapdiffbot is not cooperating.

alrright

**Comment by Jackal-boop** [comment]
Screenshot (6738)
Screenshot (6736)
Screenshot (6737)

**Comment by Jackal-boop** [comment]
apparently theres already a gaming den on birdshot but i had literally never seen it with over 10 rounds played of the map. just gonna extend what i made as part of maintennence then!

**Comment by Jackal-boop** [comment]
alrighty this is rerady

**Review by Ghommie — APPROVED** [review]

**Pull request merged**
