### PR TITLE
Culls changelog to april

### PR DESCRIPTION
**Pull request by Jordie0608**
Shortens changelog to April 2015 from March 2014

.all_changelog.yml 183KB -> 61.6KB
changelog.html 233KB -> 88.9KB

Why April? Was going to be beginning of this year but instead I rolled a dice to decide.

Would anyone be opposed to just removing archivedchangelog.html? The Git history contains all it's contents anyway.

### CODE REVIEW

**Comment by Jalleo** [comment]
Only if it automatically backs up to the wiki

**Comment by optimumtact** [comment]
hmm, one one had git will keep it, on the other, it's kind inconvenient if you want to copy paste it all at once to a wiki (say if the wiki got deleted for some or another reason)

**Comment by Jordie0608** [comment]
All the formatting would have to be redone by hand were it to be put on the wiki (or most places tbh).

**Comment by optimumtact** [comment]
ah well in that case just trash it

**Pull request merged**
