### PR TITLE
Restores admin private log type

### PR DESCRIPTION
**Pull request by AnturK**
Closes #39667 

My bad, missed that in review.

### CODE REVIEW

**Comment by MrStonedOne** [comment]
@Palladinium ^^^

**Comment by optimumtact** [comment]
@AnturK was that really the only use of admin private?

**Comment by Palladinium** [comment]
Oops, my mistake. I didn't realize `log_adminsay()` was private. Perhaps it'd be good to rename it `log_adminsay_private()` or something.

@optimumtact That was the only use of `log_adminsay()` in the codebase. `log_admin_private()` is used in a dozen or so places but I didn't change any of them.

**Comment by Palladinium** [comment]
@AnturK You need to update the bitmasks under the `#define` as well, otherwise the `LOG_ADMIN_PRIVATE` logs won't show up in the individual logging panel. Otherwise the fix is good, thank you for taking care of it.

**Comment by MrStonedOne** [comment]
That was intentional. admin say should be seperate, its not ic.

**Comment by Palladinium** [comment]
Cool, I brought it up because the individual logging panel had a tab for OOC as well, but it makes more sense to keep it separate in the case of `ASAY`.

**Pull request merged**
