### PR TITLE
no caseless bouncing

### PR DESCRIPTION
**Pull request by actioninja**
## About The Pull Request
prevents caseless ammo from bouncing away
fixes some issues with guns that do not exist yet 👀

### CODE REVIEW

**Comment by MrFluffster** [comment]
thanks

**Comment by actioninja** [comment]
Thinking about it this is a bad way of doing this and I have a better idea

**Comment by actioninja** [comment]
yeah ok this is fine

**Comment by optimumtact** [comment]
I thought bounce_away was already controlled by the heavy_metal flag

**Comment by actioninja** [comment]
it seems like the only place that is actually used is for throwing the casing

**Comment by actioninja** [comment]
actually yeah good point, this would be an even better way of doing it.

**Pull request merged**
