### PR TITLE
Adjusts engine filter output to account for faster processing

### LINKED ISSUE #28443: Supermatter still needs adjustments for faster processing
Going to put this as an issue so people actually see this. The SM recently got added to the air subsystem which processes (usually) 4x as fast regular objects so some things have become unbalanced. A few were fixed but some other issues remain. The biggest one seems to be that the crystal now produces 4x as much heat and moles of waste which quickly overwhelms the pipes and makes most advanced gas setups either extremely hard or impossible.

### PR DESCRIPTION
**Pull request by ShizCalev**
Temporarily resolves #28443 by increasing filter air injector volume by 4x

Air injectors default to 50l/s output, increased output to 200l/s

### CODE REVIEW

**Review by Cyberboss — APPROVED** [review]

**Comment by Tokiko1** [comment]
You should just edit the supermatter.dm and scale down the waste/heat directly instead as this problem also effects non-roundstart shards ordered from cargo.

**Comment by CPTANT** [comment]
This doesn't solve anything anyway as the filter air injector is almost never the bottleneck.

The bottleneck is always cooling the output gasses fast enough.

**Comment by SgtxRootbeer** [comment]
i dislike this solution, mainly because it doesn't fix the core issue, and its a snowflake mapedit which can't be replicated in game...

**Comment by ShizCalev** [comment]
Feel free to dislike it. It's meant as an immediate stopgap (till someone balances the output of the SM) to relieve the fact that the engine will currently blow sky high if something goes wrong because it's outputting gases faster than the injectors can pump out.

Also the way to replicate the same thing ingame from scratch would be using four outlet injectors instead of just one.

**Comment by CPTANT** [comment]
I think it probably isn't even the air injector that is the bottleneck but the filters that can't pump fast enough.

**Comment by ShizCalev** [comment]
@CPTANT
Spent about three hours last night with the SM and simulating failure / recovery scenarios. 

Filters kept up fine for the most part, the outlet injector was the bottleneck I identified.

It currently cannot keep up with the amount of gas being sent to it, which is exacerbated greatly once the gases within the loop heat up. The SM on fire caused the output pipe to climb in pressure at a rate of roughly 350kPa/s - causing the pipes to get clogged completely within a span of mere moments, and the SM going critical with no chances of recovery as a result of the backed up pipes.

Increasing the output volume of the injector allowed for proper recovery in my testing, and the pressure within the output pipe to stay generally around the 300~400 kPa mark with the engine is on fire.

**Comment by CPTANT** [comment]
Can you manually set the injector speed higher while in game?

**Comment by ShizCalev** [comment]
Yes.
3lqpbui

**Comment by CPTANT** [comment]
In that case I don't really see the point of coding this in.

**Comment by Cyberboss** [comment]
This can be changed later if someone bothers to fix the core issue

**Comment by CPTANT** [comment]
This is seriously something that you can just set yourself ingame if you want it

**Comment by ShizCalev** [comment]
So are all the preset filters in the engine room, as well as the ones in atmos. Same with the scrubbers in command areas that are preset to filter N2O and Toxins in addition to CO2.

Having the injector preset at roundstart just means that the engine won't blow up two major areas of the station because two engineers fucked off at the start of the shift with the only hardsuits without setting up the engine (because that totally never happens, right?)

**Pull request merged**
