### PR TITLE
Fixes decal stacking

### LINKED ISSUE #8627: Acid blood and oil splatter decals stack on a tile, but human blood does not.
A long time ago, not long after footsteps got removed way back in ye olde 2nd medbay/research model, we had bloody footsteps and blood decals could stack. This was unbelievably laggy to have literally thousands of footsteps and blood spots, so someone opted to make it only have one decal per tile and it fixed the problem fine.

This was only ever done for humans blood, not acid blood or oil spots. While a much smaller issue, it's just for consistency's sake.

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
Fixes #8627

### CODE REVIEW

**Comment by phil235** [comment]
Does this mean there can now only be one bloody footstep per tile?

**Comment by KorPhaeron** [comment]
@phil235 

I thought that was already the case from WJs issue report.

I can override it for footsteps if you want

**Comment by phil235** [comment]
Actually, you need an override for footprints but not for the reason I was thinking. You need to be able to have both blood and oil footprints on the same tile. I was thinking of footprints in different direction but apparently these are already handled in a single footprint object.

**Comment by KorPhaeron** [comment]
>which share the same type path

Fucks sake

**Comment by tkdrg** [comment]
@KorPhaeron

**Comment by KorPhaeron** [comment]
@tkdrg 

Should be okay now

**Comment by tkdrg** [comment]
Looks fine now.

**Pull request merged**
