### PR TITLE
Adds changelog reminder to pull requests

### PR DESCRIPTION
**Pull request by Jordie0608**
This'll add a short reminder when opening a PR [that'll](https://github.com/tgstation/tgstation/pull/18739) [hopefully](https://github.com/tgstation/tgstation/pull/18802) [help](https://github.com/tgstation/tgstation/pull/18795) [with](https://github.com/tgstation/tgstation/pull/18632) [people](https://github.com/tgstation/tgstation/pull/18585) [not](https://github.com/tgstation/tgstation/pull/18537) [making](https://github.com/tgstation/tgstation/pull/18696) [changelogs](https://github.com/tgstation/tgstation/pull/18661).

This PR dedicated to Joan, Kor and oranges.

### CODE REVIEW

**Comment by optimumtact** [comment]
All 3 people who give the changelog window anything more than a snort of annoyance as it pops up to get in the way of their roundstart will be thrilled

:tada:

**Comment by Jordie0608** [comment]
I will acknowledge that flippancy when I stop receiving Ahelps asking about unlogged changes.

**Comment by MrStonedOne** [comment]
You should just put an example changelog in so they have to actively delete it.

**Comment by ike709** [comment]
>All 3 people who give the changelog window anything more than a snort of annoyance as it pops up to get in the way of their roundstart will be thrilled

four*

**Comment by GunHog** [comment]
The DARK LORD HAS SPOKEN.

**Pull request merged**
