### PR TITLE
Mo' tgui mo' commits

### PR DESCRIPTION
**Pull request by neersighted**
Port old interfaces to tgui; fix up some existing interfaces
## Air Alarms

Now support any gas and shorten the gas list when not present.

## Uplink

The new logo is from @YotaXP:

## Radios

dreamseeker_2016-01-18_13-28-22

### CODE REVIEW

**Comment by GunHog** [comment]
You just keep going!!!! :+1: 
Now, this might prevent me being able to fully maintain MULEbots or any others you might change to NanoUI (That is what I choose to call it!), but it really is splendid work that will solve several issues with the interface!

Note: Please make sure to test this with AIs, especially when the MULE itself is not on camera. It is intended that wireless control, for both PDA and AIs, be based on if the bot is currently accepting wireless functions. For MULEBots, those are the radio wires, for others, it is an option in the human version of the interface. Unless wireless is disabled for a bot, it should be controllable from any location within the Z-level.

**Comment by JJRcop** [comment]
Next: uplinks?

**Comment by neersighted** [comment]
This uses the default tgui interaction state, which allows AI to interact off camera. It is the same as every other 'default' tgui.

**Comment by Shapsy** [comment]
tgui is awesome, more pls :+1:

**Comment by AnturK** [comment]
I know this probably isn't finished, but i'd prefer if the common bot functionality like locked/power/emagging was put into a partial/whatever name reactive has for subtemplates. So we can standarize that a bit. Anyway :+1:

**Comment by GunHog** [comment]
@AnturK I had thought of doing this with the addition of remote interfacing with bots via PDA. I did not consider this before, because it simply never crossed my mind that anything more would be added.

**Comment by neersighted** [comment]
Factoring out duplicate parts of UIs is part of the plan, yes.

**Comment by neersighted** [comment]
Aaaand the moment you've all been waiting for!

**Comment by ChangelingRain** [comment]
We've spent some time pressing neersighted into making it even better(though I don't totally like the alternating bars they are good for ~clarity~)
cool shit, yo

**Comment by Shapsy** [comment]
hngggg

**Comment by neersighted** [comment]
Thanks @AnturK for helping out with the radio UI. He actually implemented it in parallel, I merged our implementations.

**Comment by nullquery** [comment]
:+1:

I like [the part where I'm still thanked for my changes](https://github.com/neersighted/-tg-station/commit/a1ff8e8783f270114c40d672141cc230427349b1), yet my contribution was only 4 lines of code. :sunglasses:

**Comment by neersighted** [comment]
wew lad

**Comment by GunHog** [comment]
You are still going to add more UIs, right?????

**Comment by neersighted** [comment]
Of course

**Pull request merged**
