### PR TITLE
Removes vorecode

### PR DESCRIPTION
**Pull request by vuonojenmustaturska**
## About The Pull Request
wtf? 

## Changelog
:cl:
del: Removed the ability of fat people to vore monkeys, and the ability of aliens to vore humans.
code: Removed stubbed out would-be functionality related to stomach contents
/:cl:

### CODE REVIEW

**Comment by FloranOtten** [comment]
>and the ability of aliens to vore humans.

Maybe I'm confusing /tg/ with TGMC again, but wasn't this a way to transport humans?

**Comment by vuonojenmustaturska** [comment]
yeah but why would you when you can just swipe

**Comment by FloranOtten** [comment]
> yeah but why would you when you can just swipe

It's a legitimate strategy. Why remove it?

**Comment by vuonojenmustaturska** [comment]
1. it's associated with a functionality that does nothing else (stomach contents), that has a running cost on every living carbon mob (handle_stomach())
2. it's unneeded and unused
3. it's vorecode
4. it's vorecode

**Comment by FloranOtten** [comment]
> 1. it's associated with a functionality that does nothing else (stomach contents), that has a running cost on every living carbon mob (handle_stomach())
> 2. it's unneeded and unused
> 3. it's vorecode
> 4. it's vorecode

1. Redo it so it doesn't check on all mobs, then. No reason to strip out a feature.
2. I use it. Fight me. Since when are we removing features that few people use? 
3. I'm going to catch so much shit for opposing the removal of 'vorecode', but come on. You're just stripping out features because ewwwwwww. I don't mind the monkey thing because what purpose does this have besides a joke but really? This?
4. See above

**Comment by blessedmulligan** [comment]
pls remove shoes I don't want foot fetish content in my game
pls remove strangling and buckling I don't want bdsm content in my game
pls remove food I don't want mukbang content in my game

**Comment by kriskog** [comment]
>
> and the ability of aliens to vore humans.

Huge xeno nerf. You eat them to ventcrawl back to nest with a host. For one, it allows you to block the doors and still get hosts in.

**Comment by vuonojenmustaturska** [comment]
Not like xenos couldn't do with a nerf

**Comment by Wilchenx** [comment]
My belly is round and full

🤰

**Comment by Suicidalpickles** [comment]
his grace is vorecode
morphs are vorecode
singulo is vorecode
clowncar is vorecode

remove all those too

**Comment by tralezab** [comment]
haha what would it be like if you got sucked up by a singularity guys haha wouldn't that be funny

**Comment by zeroisthebiggay** [comment]
eating monkies as a beno and crawling into the vents is a legitimate strategy to gather infections for stealthier hives when you don't want to crawl around in maintenance and get exposed resulting in your feeble hive committing die
it's exactly like this on cm and _(presumably)_ tgmc and is actually the meta for when before the marines drop

**Comment by Ghommie** [comment]
This sort of removal debate has been already previously brought up on #41001.
Nevertheless, I'm ok with whatever, though removing a feature because of a fetish ever-so-loosely associated with it often sparks up debates where we round. wherever an alternative is offered or not.

**Comment by AdamElTablawy** [comment]
the alien thing isn't fetish content and pretending that it is fetish content is nonsense, as there's nothing fetishy about it unless you deliberately make it out to be such

there are no detailed descriptions, nothing. it's not fetish content in the slightest.

it's just a way to transport humans through vents to your nest, and deleting it entirely means that aliens can't take facehugged people to their nest without dragging them through the fucking hallway-and can't do similar with monkeys, either.

instead of deleting that, if it really bothers you _that much_ that the literal analogy-of-rape alien which has insects that forcibly facefuck their victims and have penis-shaped larvae erupt out of their chests eats people as a mechanic to get them through vents, develop an alternative instead of instantly removing it because of your redditor tier reaction of 'haha ew a FeTiSh can be associated with this'

**Comment by Ty-the-Smonk** [comment]
I would like to be able to have a xeno transport as a xeonbio man please c e a s e

**Comment by optimumtact** [comment]
I have genuinely never once seen this used

**Comment by AdamElTablawy** [comment]
considering you don't play the game that's not surprising at all

**Comment by AdamElTablawy** [comment]
that's an awfully long time to have never played the game

**Comment by optimumtact** [comment]
join the server adam, it's waiting for you, we all miss you

**Comment by WJohn** [comment]
but this would mean you can no longer reverse chestburst out of a xeno so i'm super against this

**Comment by PKPenguin321** [comment]
Big -1 devouring monkeys is one of the funniest things you can do

**Comment by mattroks101** [comment]
Oh good this gets to come back again.
image

**Comment by PKPenguin321** [comment]
I can also guarantee this was not added with the intent to be fetish content. It's ancient functionality from when the code base wasn't full of spastics and catgirl fetishists. Xenos DO use this by the way, a lot

**Comment by HomocidlePancakes** [comment]
Is this a goof alt?

**Comment by Poojawa** [comment]
every contribute needs a weird flex PR I guess.

**Comment by Tlaltecuhtli** [comment]
its only usefull for "stealth" which happens in the 2 minutes between xenos spawned and the shuttle is called

**Comment by HomocidlePancakes** [comment]
You can use it to gib lings you tlaltenerd

**Comment by vuonojenmustaturska** [comment]
Yeah it's not strictly fetish content but I'm having a really hard time justifying the feature and all the special handling around it ("what if someone adds a feature for clowns where they can eat weapons, we have to check if a clown has eaten a ninja sword") all for the benefit of xenos. I've also never actually seen them use it, but I've also never seen stealth xenos either. I'm also not too worried about fat people voring monkeys being a useful feature.

**Comment by kriskog** [comment]
So move devour code to carbon/alien??

**Comment by FloranOtten** [comment]
> Yeah it's not strictly fetish content but I'm having a really hard time justifying the feature and all the special handling around it ("what if someone adds a feature for clowns where they can eat weapons, we have to check if a clown has eaten a ninja sword") all for the benefit of xenos. I've also never actually seen them use it, but I've also never seen stealth xenos either. I'm also not too worried about fat people voring monkeys being a useful feature.

So, move the handling to xenos. If you don't want the feature at all, redo the PR. Make it 'nerfs xenos by removing their devour ability' instead of riding the wave of ewww.

**Comment by anconfuzedrock** [comment]
I also want this around so I can keep reminding shadowflame that he was being stupid to oppose the slowdown dragging PR

If "I have never seen this used" as a personal anectode is relevant, oranges, I have used and seen it used several times by xenos, but I have never seen it used as a fetish.

**Comment by PKPenguin321** [comment]
B-but catgirls are cute and make my pp feel good!! >\\\<

**Comment by Tlaltecuhtli** [comment]
send me an e-mail when someone purposely drinks corn oil after killing a monkey ling to gib it

**Comment by HomocidlePancakes** [comment]
>Tlal talks about devouring being useless for xenos
I tell tlal you can use devour to gib lings
Tlal assumes that I am talking about fat people eating monkeys

Nice one tlaleneed

**Comment by Ty-the-Smonk** [comment]
Moths were added because of porn

**Comment by Wilchenx** [comment]
Lizards were added because of furries and multiple of them have f-lists

**Comment by optimumtact** [comment]
Can we stop with the offtopic comments please.

**Comment by subject217** [comment]
Based Naksu doing the justice the server needs, but doesn't deserve. 

In regards to xeno vore as a strategy: The situation in which it is the most useful is if you are a solo drone trying to capture people before you mutate into a queen. It lets you move easily through vents with a capture, without having to pry open airlocks and whatnot. It's also useful if you're trying to keep more than one person stunned.

As for why you "never see it", oranges, if I had to wager a guess I'd say it's because it's an obscure game mechanic that isn't immediately necessary to play xeno and uses an input method that is peculiar and unfamiliar (grab intent on yourself with an aggro grab on someone else). Nobody discovers this mechanic without being told about it because nothing else in the game works like it. Given that, I don't believe "I never see this" is a compelling argument for its' removal. You should focus on a few things:

\>Is this really vore code?  
I would say it is. The stomach rumbling nonsense, being handled on carbon for no good reason, etc.
\>Is this necessary for xenos, will removing it ruin them?  
It's not really necessary. It's a very useful tool but by no means is it a mandatory one. While it is definitely a xeno nerf, it doesn't really affect the major way that xenos end up actually losing rounds, it just makes their growth less convenient and stealth abductions harder.
\>Do xenos deserve a nerf?  
Honestly, I don't think xenos really deserve a nerf. Removing them from the lavaland ruin to stop "accidental" self antagging with ghost roles was a great help in making them less obnoxious and common as round enders. This getting merged wouldn't make them useless but it decreases the strategic depth of xenomorphs. The one circumstance in which this could reasonably affect round outcomes is the solo larva xeno spawn. But even then, that's so heavily dependent on the person playing, that it's unlikely to succeed anyhow. 

My suggestion would be to make all the procs, related code, etc xeno specific and remove all vore related flavor. What if xenos had a fun belly pouch like Kangaroos? 😉

**Comment by ATH1909** [comment]
Have you ever seen this being used to enable a fetish in an actual /tg/station server? If so, how recently?

**Comment by plapatin** [comment]
wait since when could obese people vore monkeys

**Comment by subject217** [comment]
Also for the record, this is a feature that lots of people use. It's not really explained anywhere (aside from like a tip, I think) and xenos are uncommon so it's harder to build experience with them. Usually only ever saw veteran players utilize this, but they were quite effective with it.

**Comment by RaveRadbury** [comment]
I don't understand why the monkey thing gets called a Monty Python reference. Mr. Creosote doesn't eat any monkeys, and I can't thing of another reference that would fit.

**Comment by OverlyGeneric** [comment]
> I don't understand why the monkey thing gets called a Monty Python reference. Mr. Creosote doesn't eat any monkeys, and I can't thing of another reference that would fit.

It might be a reference to another part of Monty Python or even be a joke about people saying:

"I'm so hungry, I could eat a horse!"

**Comment by Shadowflame909** [comment]
This really isn't all the vorecode though.

We have an antag based around eating people. It's currently broken as well.

**Comment by Timonkeyn** [comment]
People can punch xenos to death from within even when they are on a xeno weed (at least sentinels) but Muh fetish content remove remove remove

**Comment by optimumtact** [comment]
I honestly do not care one bit about xeno balance and this is just code we don't even need

**Comment by Shadowflame909** [comment]
If we can't convince the maintainer gamer. Then I guess we just have to play the waiting game.

Enjoy our Xeno internal gibber feature while it lasts. I guess.

**Comment by vuonojenmustaturska** [comment]
Consider what would happen if the situation was reversed, and someone PR'd the ability for xenos to vore people when previously they couldn't

**Comment by Mickyan** [comment]
Xenos have been around from long before people started getting obsessed with calling everything fetish content

If you had come up with an argument that wasn't so dumb most people probably wouldn't have cared, now it's going to be an endless shitfest

**Comment by bgobandit** [comment]
please remove cloning, we cannot have cryopod-human vore

**Comment by subject217** [comment]
>I honestly do not care one bit about xeno balance and this is just code we don't even need

Consider that the depth, balance, design, et cetera of a feature that a large number of people enjoy should generally be worth keeping in mind.

That being said, since you seem pretty sure about giving this PR mergies in its' current state, you should be open-minded if someone tries to address the core issues with it in a less voretastic way in a future PR.

**Comment by FloranOtten** [comment]
Since we're so focused on REEEEEEE REMOVE FEITISH CONENT, how about we instead replace the devour mechanic with a fucking purse? All the fun of abducting without the percieved fetish content.

**Comment by subject217** [comment]
When you code it tbqhf

**Review by Cyberboss — APPROVED** [review]
Only merging to get rid of shitcode.

Nothing against the vore stuff but w/e

**Comment by PKPenguin321** [comment]
Cringe

**Comment by Fikou** [comment]
cringe

**Comment by CrazyClown12** [comment]
Demons next! The vore war rages on

**Comment by Arianya** [comment]
More room in the code for my foxgirl race

**Comment by Shadowflame909** [comment]
oh boy. I can't wait when the removal of this feature brings about that enjoyable further Xeno nerf

When dragging gains a slowdown now Xenos won't have any way to bring people to facehuggers that isn't botched.

Thanks for ignoring the future @vuonojenmustaturska 

You killed xenomorphs!

**Comment by optimumtact** [comment]
they're a side antag that shows up once in a blue moon, the dramatic overreaction is not necessary.

The game will continue just fine irrespective of this feature existing or not shadowflame

**Comment by Shadowflame909** [comment]
Orangeman once in a blue moon is irresponsibly incorrect

**Comment by deadmomo69** [comment]
why don't you give an alternative than just removing the devour mechanic for xenos, they depend on hosts for more xenos..
also I don't understand why orange man doesn't care, just because its an antag that shows up rare doesn't mean you should discredit it, that's like saying nobody cares about ninja because how rare it is or etc. etc.

anyway give an alternative to the devour mechanic so people can actually get hosts back to their nest, Its not fetish content and was never intended to be, you guys are just blowing it out of proportion with that buzzword

**Comment by optimumtact** [comment]
It's a false equivalence to compare xeno to mining, one is a major job within the game and the other is a side antag, your whole argument rests on it being important enough to the game to justify carrying the extra code.

It's not, it never will be, if someone wants to add a new mechanic to xeno to allow them the same gameplay as before nobody is standing in their way, but im not going to keep the old code around for the sake of the side event.

**Comment by Timonkeyn** [comment]
I'll make a pr tomorrow that removes laughter demons since it is clearly vorecode

**Comment by TreyWJ** [comment]
Can we also remove caks? They are clearly fetish contact. I mean come on, eating cake? From a pussycat? Tg coders are sick. I'm glad we finally have a puritan coder who respects our right to chastity.

**Pull request merged**
