### PR TITLE
Adds a minimum drinking/smoking age

### PR DESCRIPTION
**Pull request by Ryll-Ryll**
## About The Pull Request
NT is finally cracking down on underage drinking and smoking on its stations, and you must now be at least 20 years old in order to purchase alcohol or tobacco at vendors. Underage ID's will be visible as such when shown or inspected. Bartenders below the age have discreetly had their IDs modified to be the minimum age, though if anyone cross references the station datacore records, they'll be exposed!

[](https://i.imgur.com/FRwbz4O.png)

You can adjust the registered age for an ID at the HoP's console, the same way you would adjust the registered name. You can also pulse the age restriction wire on vending machines to disable the age checking system if you want to hack the system. I chose 20 as the legal limit because I don't care to listen to people fighting about 21 vs 18 and America vs the world, and it still will affect a decent amount of people I figure.

[](https://i.imgur.com/RZZcawl.png)

## Why It's Good For The Game
Makes age a teeny bit relevant, you can now more easily identify and bully 17 year old Heads of Staff.

## Changelog
:cl: Ryll/Shaps
add: Due to pressure from various organizations, Nanotrasen is implementing a new ban on the purchase of alcohol and tobacco products for crewmembers under the age of 20 onboard its Spinward space stations. Please remember that providing alcohol or tobacco products to underage crewmembers is against Space Law, and remember to check those cards bartenders!
add: Standard Nanotrasen IDs now display the registered age of the holder, which you can change at the HoP's access console. 
/:cl:

### CODE REVIEW

**Comment by optimumtact** [comment]
Add a turret in the bar that shoots stun bolts at anyone underage

**Comment by Ryll-Ryll** [comment]
Stunstools hooked up to a button behind the bar that selectively shock underages

**Comment by HomocidlePancakes** [comment]
>tfw 18 y/o double D 9/10 female HoS is the first one to die in the round.

**Comment by Anonmare** [comment]
>tfw 17 year old bartender and can't serve anyone alcohol

i cri

**Comment by Dennok** [comment]
Need add ability to hack venders to disable age restrictions.

And maybe make restriction age some random?

**Comment by Dennok** [comment]
Maybe make restriction age some random?

**Comment by SomeoneYouProbablyKnow** [comment]
Make the spess drinking age 21 and not 18 to get more buck out of this mechanic

**Comment by Michael-Ashfield** [comment]
Drinking the "Old Timer" drink increases your character age by 1, does this apply to this age restriction system?

**Comment by Ryll-Ryll** [comment]
That's an alcoholic drink so it'd be illegal for an underage to have it in the first place! Either way the registered ID would have to be updated manually at a card console

**Comment by LordSaladin** [comment]
this will snowball into age restrictions on everything else then /tg/station will become real life station.

**Comment by ATH1909** [comment]
Eh, I think it'd be better if we made the legal drinking age 21, not 20, simply because people will think it's a bug if their 20 year old character is allowed to drink, but not their 19 year old character.

**Comment by Pumpkinoe** [comment]
Will agent cards allow you to modify the age on it?

**Comment by Ryll-Ryll** [comment]
Yes actually! That was the first thing I did

**Comment by spookydonut** [comment]
```
loading map_files/Deltastation/DeltaStation2.dmm
_maps/map_files/Deltastation/DeltaStation2.dmm:71141:error: undefined type: /obj/item/clothing/suit/jacket/letterman_nanotrasen
_maps/map_files/Deltastation/DeltaStation2.dmm:71153:error: unknown type
_maps/map_files/Deltastation/DeltaStation2.dmm:81447:error: undefined type: /obj/item/clothing/suit/jacket/letterman_nanotrasen
_maps/map_files/Deltastation/DeltaStation2.dmm:81456:error: unknown type

loading RandomZLevels/TheBeach.dmm
_maps/RandomZLevels/TheBeach.dmm:1057:error: undefined type: /obj/item/clothing/suit/jacket/letterman_nanotrasen
_maps/RandomZLevels/TheBeach.dmm:1059:error: unknown type
_maps/RandomZLevels/TheBeach.dmm:1062:error: undefined type: /obj/item/clothing/suit/jacket/letterman_syndie
_maps/RandomZLevels/TheBeach.dmm:1064:error: unknown type
_maps/RandomZLevels/TheBeach.dmm:1067:error: undefined type: /obj/item/clothing/suit/jacket/letterman_red
_maps/RandomZLevels/TheBeach.dmm:1069:error: unknown type
```

**Comment by jtroopa** [comment]
Suppose you could make a minor role as like some sort of... I dunno, frat boy wannabe or some shit, who tries to imbibe as much alcohol and tobacco as they can get their hands on. And then like @optimumtact mentioned, have a vice officer or some such who tries to identify and bust them.
I like the idea of more minor, less station-threatening I guess... semi-antag roles like that?

**Comment by Ryll-Ryll** [comment]
Alright coming back to finish this, I lost interest in the party aspects of this PR, so I'm narrowing it down to just the legal age. ID's no longer show the minor status in their name, you must examine or be shown the ID to see it's a minor's.

**Comment by Fikou** [comment]
i think its too much in your face to show in bold someone is a minor when you show your id for a meme feature

**Comment by Ryll-Ryll** [comment]
Having it always in the name in bright red like I did before was too much, but this is far, far more reserved. It's not even really a meme feature, the intention is that bartenders can start asking people to show ID as part of roleplay routines. How often are you walking around spamming showing people your ID that this would be disruptive?

**Pull request merged**
