### PR TITLE
Fixes the AI's shuttle call prompt lacking a 'Cancel' button.

### LINKED ISSUE #11109: AI cant cancel when they tey to call the shuttle
Instead they have to close their client and come back on

### PR DESCRIPTION
**Pull request by GunHog**
- The prompt for calling the shuttle now includes a cancel button.
- Fixes #11109.

### CODE REVIEW

**Comment by Anonus** [comment]
more ones than lines changed

**Comment by GunHog** [comment]
Welp, 11111 just got wasted. Sorry guys. I could always change it to something cool, though.

**Comment by PKPenguin321** [comment]
at least it wasn't a meme pr by goofball or aran

**Comment by MrStonedOne** [comment]
NO!

NO MORE COMMITS!

11111
1 commit
1 file changed
1 line changed
1 get that wasn't a meme get.

This pr shall known be known as get #31

**Comment by Miauw62** [comment]
still better than #10000

**Pull request merged**
