### PR TITLE
Removes 3 exclusive species from magic mirrors

### PR DESCRIPTION
**Pull request by tralezab**
## About The Pull Request

Species change permission:
image

Removes Vampire, Dullahan, and Nightmare from magic mirror and pride mirror.
Nightmare keeps pride mirror:
image

## Why It's Good For The Game

Vampires are being discussed as all year round content because wizards and miners can choose to be them when they are intended as an EXCLUSIVE halloween race, since they're not really in theme for ss13. They used to be picked for their bat form as a free shapeshift spell for wizards, but now that has been axed too, and there's not much advantage to picking them. Not that picking what is essentially admin races should be a meta anyways! ...Look, could come around to this but at least make it a wizard item, not a mistaken halloween containment breach.
Dullahans are hilariously broken and are only allowed to exist by nature of severely breaking for a day straight every 365 days, they are both incredibly debilitating to play as with near to no advantages and they bug out. While vampires I could make some argument for the future holding some more normal way to achieve them, Dullahans really should just be locked away.
Nightmares are a mistake, as in they are only available because they are inherited from shadowpeople. Nightmare wiz is a large free big set of bonuses as you assume the full antag power (upsides and downsides, but still) of nightmare itself. Same as vamp, at least put a price but I really don't think this fits wizard and all and just reeks of picking the most powerful set of things.

Generally, Halloween is so special because it's a bunch of content you don't get to see every day unpacked, it's something transformative. We don't have a lot of content in rotation for that same reason, we lock off holiday content for the rarity surprise. Halloween races mistakenly becoming a part of normal gameplay is unintentional and slowly kills the genuineness of the holiday.

## Changelog

:cl:
del: Vampires, Dullahans, and Nightmares can no longer be found in certain magic mirrors.
/:cl:

### CODE REVIEW

**Comment by ATH1909** [comment]
dio wizards are a god-given right, 👎 from me

**Comment by ATH1909** [comment]
also, unless someone changed it while I was gone, nightmare wizards can't cast robed spells (similar to going runic golem wiz or alien golem wiz), which is a pretty major downside. how many nightmare wizards are we actually seeing?

**Comment by moocowswag** [comment]
Okay but this doesnt make those races impossible to become

You can still become a dullahan if you roll the dice with genetics and a vampire/dullahan/shadowperson with xenobio

**Comment by JohnFulpWillard** [comment]
> Or you can roll vampire/dullahan/shadowperson (notnightmare) with xenobio

image

**Comment by bluetshirtguy** [comment]
booo

**Pull request merged**
