### PR TITLE
Removes fire alarm sound

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
Sounds like strange submarines and I generally find it annoying, especially when observing

### CODE REVIEW

**Comment by Ultimate-Chimera** [comment]
But why?

**Comment by GunHog** [comment]
Because the sound gets spammed. A lot. does not need to be REMOVED, it only needs a louder, more jarring sound, and to only play **once**.

**Comment by neersighted** [comment]
Kor, only make it play if the area alarm is 0. There we go, it only plays once. Also find a better sound.

**Comment by Iamgoofball** [comment]
yeah let's just make it play once and use an actual fire alarm sound

**Comment by KorPhaeron** [comment]
Well when someone gets an actual fire alarm sound they can add that then

**Comment by GunHog** [comment]
@KorPhaeron https://github.com/tgstation/-tg-station/pull/15149

**Comment by Xhuis** [comment]
FUN REMOVAL
:-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1:

**Comment by Cheridan** [comment]
https://github.com/tgstation/-tg-station/pull/15149#issuecomment-179646294

**Comment by KorPhaeron** [comment]
fine you bullies we'll have submarines

**Pull request closed without merging**
