### PR TITLE
Removes Mammaries from lizards

### PR DESCRIPTION
**Pull request by Ikarrus**
I basically just made them much less pronounced. They still have to keep the same silhouette because of female clothing.

Fixes https://github.com/tgstation/-tg-station/issues/10437

Old: old New: dmi

### CODE REVIEW

**Comment by Iamgoofball** [comment]
can't wait for the ERPers to whine

:+1:

**Comment by Incoming5643** [comment]
I feel bad I even have to comment on this

:-1:

**Comment by Incoming5643** [comment]
Also I thought we got rid of vengeance coding.

**Comment by Ikarrus** [comment]
How is this grudgecoding?

**Comment by Incoming5643** [comment]
I have no idea, I was just running through narratives in my head on how this became something worth correcting. Something to the tune of "shitting on the lizard players because fuck them" seemed like the most likely candidate.

I mean we literally just got these particular lizard sprites in #9808

**Comment by WJohn** [comment]
Oh no no, we had lizard tits long before that. I toned them down with my customizability and cleaned up sprites, but didn't remove them outright. I don't mind their removal, though.

**Comment by Razharas** [comment]
What is the reson for this change?

**Comment by Ikarrus** [comment]
No man, I put this up because I started playing lizards.

I thought about making a female lizard, but seeing them having breasts just turned me right off. It just fucked with my head that lizardpeople were somehow also mammals.

I just thought it was weird as fuck, and I certainly don't agree with putting breasts on everything just because they're female, especially if they're supposed to be alien.

**Comment by Incoming5643** [comment]
Well I mean the change itself is kind of a half measure here, you removed the shading under the breast but the actual shape of the body is the same. Meaning they still have them except in one really specific way if they happen to not be wearing a shirt and the player is paying very close attention to the lizards chest.

It just feels really arbitrary and designed to cheese off the three or four people who might really care about it. WJohn already removed the paradoxical lizard nipples in #9808 so I don't see why you jumped to "They're mammals my immersion is ruined". 

Wow there's so many sentences in this pull I never want to type again.

But I mean if the guy who made the sprites is ok with it fine, but I just don't see much a point.

**Comment by Ikarrus** [comment]
They just gross me out how pronounced they were.

Maybe it doesn't remove them completely, but they're considerably less in-your-face now.

But yeah I can probably fill in those two pixels for the side sprites to make this more consistent.

**Comment by Incoming5643** [comment]
Things like female outfit generation would have to account for any changes in the "base shape" of a sprite. It is probably not worth the trouble. I mean if you're happy with how far you've gone that's fine, it just seems so minuet a change.

**Comment by Ikarrus** [comment]
Yeah, changing the silhouette too much was what I was worried about.

I just made some adjustments so it's a bit more consistent with the side sprites. Maybe it doesn't remove all traces of them entirely, but they're certainly far more subtle.

**Comment by freerealestate** [comment]
I don't know what's more ridiculous, the pull or the reaction to it

**Comment by Dorsisdwarf** [comment]
The reaction. I don't even think any hardcore lizard players will seriously care.

**Comment by freerealestate** [comment]
I was just observing the amount of dialogue this one silly pull has spawned.

**Comment by daman997** [comment]
lizard double dong sprites when

**Comment by Cheridan** [comment]
i'm crying

**Comment by Incoming5643** [comment]
I don't really care that much it's just I had to look at lizard sprites like way too much during the sprite rewrite. War torn memories of things not looking quite right and layering.

Lizards, lizards have changed.

**Pull request merged**
