### PR TITLE
>unironically spelling unironically wrong

### PR DESCRIPTION
**Pull request by BeeSting12**
changes description of vape naysh shirt so that it's spelled properly

### CODE REVIEW

**Comment by ShadowDeath6** [comment]
https://github.com/tgstation/tgstation/pull/20629#discussion_r79965502

:thinking:

**Comment by BeeSting12** [comment]
huh they did do it ironically. beside the point though, it should be spelled properly it's like spelling colour or something wrong and it triggers me.

**Comment by dannno** [comment]
what if we removed it instead

**Comment by KorPhaeron** [comment]
Good idea mr brando

**Comment by lzimann** [comment]
Removing would be nice, but while that doesn't happen let's spell things correctly!

**Pull request merged**
