### PR TITLE
Fixes another instance of FIGHTVALE

### LINKED ISSUE #9258: Mulligan still produces ten million traitors.
So we had a traitor/ling round, and all the antags died. Then it got mulligan'd into TRAITOR. I emphasize this because unlike double agents there aren't supposed to be a dozen traitors in traitor mode.

Yet...

@Incoming5643

### PR DESCRIPTION
**Pull request by Incoming5643**
Because the replacementmode didn't realize that the lists of antags are kept in the ticker.mode gamemode and not itself.

Clears up some language issues that was making the check antag panel a little harder to read than it needed to be.

Fixes #9258

---

Mulligan will no longer mulligan a round into the same mode. Because of how scaling works this would at best only create one or two additional antags. At worst it wouldn't create any antagonists, and mulligan would get frustrated and reroll after its failure.

### CODE REVIEW

**Comment by Incoming5643** [comment]
This was going to be a part of #9235 but it was merged three minutes before I committed. Whoops.

Might be worth the speed merge cause mulligans are still silly without this bit.

**Comment by Cheridan** [comment]
2slo :turtle:

**Comment by Incoming5643** [comment]
That said given some people seemed to enjoy it I'll probably code a simple ANTAG EVERYONE button down the line for the sake of !!FUN!!

**Comment by PKPenguin321** [comment]
I could've sworn there was already a button that was called "Make Everyone the Traitor" in the secrets panel

**Comment by Incoming5643** [comment]
There's "there can be only one!" but that's very overt and impossible to miss.

It's a lot funnier when you don't immediately know everyone else is also in it.

**Comment by PKPenguin321** [comment]
just popped into a local test server to check
secrets panel
yooo i was right

but it'd be nice if you could choose what kind of antag to make everyone instead of them all being traitors

**Comment by Incoming5643** [comment]
Everyone is the nuke op: 50 people on a shuttle rush an empty station

They still lose

**Comment by astralenigma** [comment]
Make an admin possess the nuke disk and run around while spawning mobs.

**Pull request merged**
