### PR TITLE
removes farts

### PR DESCRIPTION
**Pull request by grungussuss**
## About The Pull Request
Removes farts from the clown car, including the sound file.
## Why It's Good For The Game
potty humor is childish and I don't think it's funny at all, with its history I'd say it's even fetish content.
## Changelog
:cl: grungussuss
del: removed farts
/:cl:

### CODE REVIEW

**Comment by mc-oofert** [comment]
why

**Comment by EEASAS** [comment]
do not merge

**Comment by SmArtKar** [comment]
Its not something overdone like goon or monke's farting, this is an unlockable function on a clown-only item, and I'd say stupid jokes are rather fitting for our clowns.

**Comment by btcbuster** [comment]
It is a CLOWN item, I am very surprised we don't have a whoopee cushion or something. Clowns make funny noises

**Comment by Jackal-boop** [comment]
the clown is a childish entity, he can make fart jokes as a treat

**Comment by Shoddd** [comment]
a world where https://github.com/tgstation/tgstation/pull/68312 is merged is a world where this is closed

**Comment by Jackal-boop** [comment]
https://github.com/tgstation/tgstation/pull/78470

one day

**Pull request closed without merging**
