### PR TITLE
Revert "Changes how robotics control console works". Test your code

### PR DESCRIPTION
**Pull request by carshalash**
Reverts tgstation/tgstation#64608

Malf AI's can in fact NOT detonate borgs. Test your shit.

### CODE REVIEW

**Comment by LemonInTheDark** [comment]
@Kylerace I don't know what's going on, help

**Comment by Kylerace** [comment]
no. you can add back that ability for malf ais but im not accepting a full revert

**Comment by AlinaStarkova** [comment]
> Reverts #64608
> 
> Malf AI's can in fact NOT detonate borgs. Test your shit.

as a stop gap measure until its fixed: malf AIs can blow up borgs whether dead or alive using their machine overload power, since borgs count as machines

otherwise this probably doesnt need to be completely reverted, malf AIs isnt super common, and even then malf AIs blowing up their borgs isnt common either since they usually just destroy the console and not care (and borgs can blow themselves up too in their interface). so it can last a day or 2 for the fix to merge

**Comment by carshalash** [comment]
> otherwise this probably doesnt need to be completely reverted, malf AIs isnt super common, and even then malf AIs blowing up their borgs isnt common either since they usually just destroy the console and not care (and borgs can blow themselves up too in their interface). so it can last a day or 2 for the fix to merge

Wow, you have no idea what you are talking about.

**Comment by carshalash** [comment]
> no. you can add back that ability for malf ais but im not accepting a full revert

It'd be better if you didn't condone people refusing to test their code.

**Comment by AlinaStarkova** [comment]
> > otherwise this probably doesnt need to be completely reverted, malf AIs isnt super common, and even then malf AIs blowing up their borgs isnt common either since they usually just destroy the console and not care (and borgs can blow themselves up too in their interface). so it can last a day or 2 for the fix to merge
> 
> Wow, you have no idea what you are talking about.

nice reply, good thing im actually objectively correct, hacked/emagged borgs get self destruct button, and the machine overload power does blow borgs just as they do a vending machine or holopad

**Comment by thgvr** [comment]
another horrible AI nerf merged

**Comment by Nistishere** [comment]
> as a stop gap measure until its fixed: malf AIs can blow up borgs whether dead or alive using their machine overload power, since borgs count as machines

Pay 20 Malfpoints to do something that was described as baseline in the PR and is not useful in the specific situation where blowing a borg is useful is not a good stop gap measure.

>makes borgs not unlockable by AI if human locks them. 
-From #64608 

Revert this shite too. Command players are dentheads that won't unlock your borgs, so may as well do it yourself.

**Comment by carshalash** [comment]
> > as a stop gap measure until its fixed: malf AIs can blow up borgs whether dead or alive using their machine overload power, since borgs count as machines
> 
> Pay 20 Malfpoints to do something that was described as baseline in the PR and is not useful in the specific situation where blowing a borg is useful is not a good stop gap measure.
> 
> > makes borgs not unlockable by AI if human locks them.
> > -From #64608
> 
> Revert this shite too. Command players are dentheads that won't unlock your borgs, so may as well do it yourself.

image

It doesn't cost 20 malf points to use. It doesn't work how they said.

**Comment by Mothblocks** [comment]
Call it a good reason to support stronger atomization, but you're reverting a PR that does several things because of a problem in one of it, and a non critical one at that. There's no reason to keep this up.

**Comment by carshalash** [comment]
> Call it a good reason to support stronger atomization, but you're reverting a PR that does several things because of a problem in one of it, and a non critical one at that. There's no reason to keep this up.

Why do you all keep saying its non critical? It's kind of essential to blow borgs that are dead when malf.

**Comment by Mothblocks** [comment]
Useful meta strategies do not fit the criteria for "critical", especially given how rare malf AI is.

**Pull request closed without merging**
