### PR TITLE
energy cakehat buff

### PR DESCRIPTION
**Pull request by imsxz**
## About The Pull Request
makes the energy cakehat sharp and do 30 damage instead of 18. Also gives it heat 1000 instead of 0, but this is only used for heating reagents, not combat related. Cakehat has 999 for instance.

## Why It's Good For The Game
Energy cakehat is criminally underused, for one. I believe that people seldom make it because of the massive downgrade compared to what it takes to make an energy cakehat. With this PR, the cakehat will at LEAST be as powerful as an energy sword, making it a much more appealing item to make for stylish murdering. Didn't add in the block chance as of yet, I wanted to gather opinions about how it should be implemented, if at all.

The simplest idea is to just make the energy cakehat have 50 block chance at all times. Alternatively, add a block chance on variable to either cakehat or energy cakehat so it only has the block chance while it's on. I'm not entirely sure how it would affect getting hit by stuff while it's on your head, either, I'll test it if/when a method of block chance is decided upon.

## Changelog
:cl:
balance: energy cakehat is now on par with energy swords.
/:cl:

### CODE REVIEW

**Comment by ArcaneMusic** [comment]
Dude, April fools isn't for another month and 3 weeks.
R... Right?
30 damage is fucking INSANE.

**Comment by imsxz** [comment]
it takes an energy sword to make it.....

**Comment by ArcaneMusic** [comment]
If you wanted to deal damage with it, you wouldn't be turning it into a hat.

**Comment by necromanceranne** [comment]
I mean, a 50% block chance while on the head is pretty powerful given you can be readily disarmed of it. Unless it has a chance of falling off or something I'd probably keep it to 50% in-hand.

**Comment by ArcaneDefence** [comment]
Energy cakes are also obtainable through xenobiology with silver slimes, so they're not even exclusive to situations where an energy sword is used to make it.

**Comment by imsxz** [comment]
@necromanceranne im not sure how it works when it's on head, if at all. that is why it is not implemented yet among other listed reasons.

**Comment by zxaber** [comment]
Does the energy cake hat block being knocked off if someone throws another hat at your head?

If not, it shouldn't, that sound funny.

**Comment by Krysonism** [comment]
> 
> 
> Energy cakes are also obtainable through xenobiology with silver slimes, so they're not even exclusive to situations where an energy sword is used to make it.

Yeah but the same type of slimes can already give you power crepe and gatfruit.

**Comment by Yenwodyah** [comment]
It's a meme item. It doesn't need to be combat-viable.

**Comment by imsxz** [comment]
sybil players need not reply, this PR only pertains to high elo servers

**Comment by Tlaltecuhtli** [comment]
buff the ecake slices too?

**Comment by SkeletalElite** [comment]
> If you wanted to deal damage with it, you wouldn't be turning it into a hat.

then why would anyone turn into the hat other than for the sake of saying you've done it.

**Comment by itseasytosee** [comment]
the sake of saying you've done it.
It's a meme

**Comment by carlarctg** [comment]
guys, you're being very dumb right now
there are two energy cakes:

1. energy cake (hat)
deals 18 brute damage
2. energy cake (cake)
deals 2 brute damage, gives you 30 dmg if you eat it (not including forcefeeding)

just blacklist 2 from xenobiology, or better yet, create a subtype you cant bake into a hat and only that can be xenobiologed

**Comment by Iatots** [comment]
fuck maint cakehatters

**Comment by CRITAWAKETS** [comment]
cakehats were a mistake and just encourage powergaming

if i was a maintainer i would just say nerf the damage of the cakehats and just have them be a novelty item

**Comment by imsxz** [comment]
> 
> 
> > If you wanted to deal damage with it, you wouldn't be turning it into a hat.
> 
> then why would anyone turn it into the hat other than for the sake of saying you've done it.

style 

> 
> 
> cakehats were a mistake and just encourage powergaming
> 
> if i was a maintainer i would just say nerf the damage of the cakehats and just have them be a novelty item

if you want to powergame you'd get cleaver/circular saw from autolathe for the same damage with much less effort.

**Comment by optimumtact** [comment]
imsxz is banned from making cakehat changes as of this comment.

**Pull request closed without merging**
