### PR TITLE
Remaps a part of NorthStar's medbay

### PR DESCRIPTION
**Pull request by EEASAS**
## About The Pull Request
Remaps the treatment part of Medbay, in NorthStar
68747470733a2f2f616666656374656461726330372e626c6f622e636f72652e77696e646f77732e6e65742f6d6462322f696d616765732f333233343938372f32343931343935313630312f6d2f5f6d6170735f6d61705f66696c65735f4e6f727468537461725f6e6f

## Why It's Good For The Game
This PR aims to increase the size of this part in NorthStar as it's kinda cramped, while retaining a familiar design.
Feel free to suggest in the comments about any changes you'd like to see
## Changelog
:cl:
add: Remapped NorthStar's medbay a little bit
/:cl:

### CODE REVIEW

**Comment by DaydreamIQ** [comment]
You can use the mapdiffbot to make better looking screenshots for the difference if needs be y'know
image

image

Also why'd you take away all the public stuff out of the lobby like the medical Kiosk, bell free bandages etc?

**Comment by EEASAS** [comment]
> Also why'd you take away all the public stuff out of the lobby like the medical Kiosk, bell free bandages etc?
the medical kiosk was always in the treatment room, this incentivizes the medical doctors to actually open the door and treat people, loitering people are to be kicked out as well

**Comment by DaydreamIQ** [comment]
Putting the Kiosk inside the medbay defeats the entire purpose of its existence. Its literally there so people can just scan themselves instead of banging on the doors to med

**Comment by Admiral-Gigaton** [comment]
I think this looks great, besides the kiosk, which should probably be more accessible considering its one and only function.

maybe some misc. emergency sutures and ointment at the front desk? emergency sutures have less sutures in a stack, and ointment takes longer to use, incentivizing players to walk into medbay and get treated instead of just sitting in front of it for a minute and then leaving. if its really an emergency, and no one can help, theres sutures and ointment to use while they wait.

**Comment by iwishforducks** [comment]
The walking space in the triage center feels off in every way possible. Here's a quick graph of (expected) walking traffic.
image
As you can see here, there's really only ONE way to get to the medical beds in the back. The other two possible ways to get into the triage center end up going right through the space of the couple medical beds in the front.
Overall the arrangement of the tables in the triage center make it feel like a labyrinth and that you're forced to bump into people.

The locker in the triage center is a really odd choice. Lockers are movable, which is why you usually see them tucked in corners or against walls.
image
This can end up causing the locker to be pushed right in front of the door way, leading to some really bad map congestion. Or it can be pushed into one of the beds, blocking the beds from being used.

I'm not really sure what purpose this area serves.
image

I'm not sure if four showers are needed.
image
Especially at the expense of a quick way to get into cryo... It's made further worse by the fact that the triage center has cramped pathing.

Sorry, this is kind of just negative feedback but hopefully you still find this useful.

**Comment by EEASAS** [comment]
> Sorry, this is kind of just negative feedback but hopefully you still find this useful.

i updated the images, look at them again

**Review by Maurukas — APPROVED** [review]

**Pull request merged**
