### PR TITLE
Update all of tgui's dependencies except ractive

### PR DESCRIPTION
**Pull request by Mervill**
Title

Updating to ractive 0.8.X breaks everything, still looking into that

### CODE REVIEW

**Comment by AnturK** [comment]
Good luck, there was some annoying issues with polyfills last time i tried.

**Comment by Mervill** [comment]
Polyfills are annoying since I can't test if a specific polyfill can be removed

**Comment by optimumtact** [comment]
@MrStonedOne I think may know about the ractive issue, but I dont' recall the details, some removed functionality that tgui was relying on

**Comment by Mervill** [comment]
@optimumtact I'm pretty sure I read somewhere that ractive 0.8.X introduced breaking changes that made 0.7.X templates invalid

**Comment by Iamgoofball** [comment]
If we check their repo they've probably got update instructions.

**Comment by Iamgoofball** [comment]
>Conflicting files
tgui/assets/tgui.js

**Comment by optimumtact** [comment]
Just requires a merge from upstream, replacing the minified tgui with upstream and then recompile your changes into it

**Comment by Mervill** [comment]
I'll be able to fix it when I get home today

**Comment by optimumtact** [comment]
I believe it's two way bindings but I don't know for sure

**Comment by MrStonedOne** [comment]
https://github.com/ractivejs/ractive/issues/2597#issuecomment-246400839 

https://github.com/ractivejs/ractive/pull/2331

https://github.com/ractivejs/ractive/pull/2722

**Comment by Mervill** [comment]
BY THE WAY -- Anyone whose developing for tgui right now needs to run `npm install` after this is merged or it wont take effect on their machines @MrStonedOne @ChangelingRain

**Comment by optimumtact** [comment]
Did you test any of these on an actual ie8 or ie9?

**Comment by Mervill** [comment]
No. Is there an easy way to do that?

**Comment by RemieRichards** [comment]
you can actually open tgui files in a browser, but 100% of the uidata is missing, obviously.

**Comment by Mervill** [comment]
This is related to https://github.com/tgstation/tgstation/issues/21981 then. As in, assuming I can open them in older browsers ... what am I actually looking for in terms of break/working? Other then obvious failures of course.

**Comment by optimumtact** [comment]
just a quick check for obvious failures is fine, there are not many people and they can report any issues they have after

**Comment by RemieRichards** [comment]
couldn't say to be honest, your best bet would probably be to take a tgui that exists, open it in a browser, and give it a fake version of the json data object (based on what that UI would expect, so look at it's ui_data() proc), and compare output to current.

**Comment by Mervill** [comment]
> Enough users to justify continued legacy support

> Not enough users to justify thorough testing

**Comment by optimumtact** [comment]
You can tell incoming in coderbus that he can no longer play the game.

I'll wait for you to deliver that news.

**Comment by Iamgoofball** [comment]
@optimumtact is he still refusing to let you buy him a new laptop?

**Comment by MrStonedOne** [comment]
@neersighted i wonder if you still check your email...

**Comment by AnturK** [comment]
The only important ones are html5shim and es2015 from babel so the breaks _should_(in theory) be fairly obvious

**Comment by MrStonedOne** [comment]
This get a script errors on ie8.

line 1, cher 5692: expected identifier, string or number

Then it displays nothing

**Comment by Mervill** [comment]
@MrStonedOne Is there a way to temporarily remove the minify step from the tgui pipeline?

**Comment by optimumtact** [comment]
Just run gulp instead of gulp --min

**Comment by optimumtact** [comment]
The new standard for minimum support is ie11, that locks out anyone not on windows 7 or higher. But those people are people I no longer care about.

**Comment by Mervill** [comment]
@optimumtact Merge this PR for now, and I'll depreciate stuff in another PR later

**Comment by MrStonedOne** [comment]
also, mervill, if you disable the minify step, ractive 0.8 "works" well enough that you can see whats wrong.

something about -min is breaking the javascript, we could skip it entirely if we wanted,

after you get past that, you can see that the components don't load right and the update of the data doesn't happen.

**Pull request merged**
