### PR TITLE
Reverts part of #32196 "Nerfs smoke machine + improves grammar"

### PR DESCRIPTION
**Pull request by Buggy123**
image

image

Reverts part of #32196

@praisenarsie was specifically asked to add upgrading range via components, he never did so. As well, the GUI is misleading and implies that you can upgrade it. I lack the knowledge or skill to easily make these changes myself, so unless someone else is willing to do so, I am simply reverting the change. The reduced chem capacity and improved grammar has not be changed.

### CODE REVIEW

**Comment by kevinz000** [comment]
Fix it properly or don't "fix" it by a revert.

**Comment by Buggy123** [comment]
I'm not able to revert it properly because I'm shit at coding, but the person who was supposed to do this didn't, and no one else seems to want to pick it up.

**Review by Cyberboss — CHANGES_REQUESTED** [review]
Do it right or don't do it at all, look at the cloner for a good example

**Comment by nicbn** [comment]
Ok ok I'm gonna do it

**Pull request closed without merging**
