### PR TITLE
Health analyzer can print results

### PR DESCRIPTION
**Pull request by Oxotnak**
## About The Pull Request
Adds det's scanner feature to health analyzer so it's able to print analyzed patient results. Show to your colleague how horribly was destroyed clown's body! Prove to sec that John Syndicate hurt you really badly!
Screenshot_21
## Why It's Good For The Game
It's good for when you want to roleplay in somethin' like a court and you able to prove that someone beat you up 'cause we can't always count on medic's words, people can lie you know
## Changelog
:cl:
add: health analyzer now able to print scanned results via Ctrl-shift-click!
qol: text from healthscan proc now use < br >
/:cl:

### CODE REVIEW

**Comment by Oxotnak** [comment]
Ok I dont get it. Why I can't create var inside of analyzer and then use it in print proc... It's the same way as in det's scanner
image
image

**Comment by Oxotnak** [comment]
Okay I was told what's wrong and since I can't use global var it will take MUCH time to figure out how to use list var from global proc healthscan in health analyzer's print ability

**Review by MrMelbert — COMMENTED** [review]
As a tip, to help out (since I implemented this for another server recently): 

Have `/proc/healthscan` return the html contents of the scan, then you can just use that to print directly

**Comment by MrMelbert** [comment]
Also you don't have to do it in this pr but putting the existing html directly on a sheet of paper looks very plain and I'd suggest spicing it up a bit 
image

**Comment by deathrobotpunch** [comment]
hooray I now as a lawyer main have a way of printing a report that my client was indeed assaulted by space

**Comment by DaCoolBoss** [comment]
Ctrl shift click is a little awkward, any reason why it can't be ctrl leftclick or ctrl rightclick instead?

**Comment by Oxotnak** [comment]
> Ctrl shift click is a little awkward, any reason why it can't be ctrl leftclick or ctrl rightclick instead?

It's combination that you can't press randomly. Maybe I'll change it, not sure

**Comment by Oxotnak** [comment]
Casting charm on code so it would work better and tell me his secrets

https://github.com/user-attachments/assets/c630ba94-de37-4922-865f-b1ccca83a27d

**Comment by Rhials** [comment]
Ambulance chaser lawyer gameplay stocks going way up.

**Comment by Oxotnak** [comment]
Okay I still want to qol text further but I'd prefer make it with another PR cause I was asked to add this feature and qol can wait. At least now it's readable and look kinda different ↓↓↓

image

**Comment by Xackii** [comment]
free papper

**Comment by Sakamoto4ka** [comment]
Where is scan date

**Comment by Oxotnak** [comment]
Scan date and some qol to prevent spam
Screenshot_22

**Review by Ghommie — APPROVED** [review]

**Comment by ExcessiveUseOfCobblestone** [comment]
cute

**Pull request merged**
