### PR TITLE
[EXPERIMENTAL] applies same optimization to maploader

### PR DESCRIPTION
**Pull request by Iamgoofball**
hmm

### CODE REVIEW

**Comment by KorPhaeron** [comment]
Will this save planetstation from itself?

**Comment by Iamgoofball** [comment]
possibly iunno

we'll want to do some testmerges and shit to see if this isn't just a fluke with atmos that makes this method 4 times faster

**Comment by KorPhaeron** [comment]
@AnturK Do you still have your giant z levels you used for testing laying about before I waste 5 minutes recreating them? I trashed them all because I'm lazy and silly

**Comment by Iamgoofball** [comment]
although DMM suite need some more touchup because it uses curly brackets and >verbs for some reason

**Comment by AnturK** [comment]
You mean the lavaland pasted around ? I didn't keep these either, sorry.

**Comment by KorPhaeron** [comment]
Guess I'll try later today then

**Comment by optimumtact** [comment]
I want a proper explanation of what is occuring here with more indepth explanation before we go cargo culting our code. Please just wait on these thanks.

**Pull request closed without merging**
