### PR TITLE
Fixes staff of change borgs recieving AI laws

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**

### CODE REVIEW

**Review by vuonojenmustaturska — DISMISSED** [review]

**Comment by vuonojenmustaturska** [comment]
rip

**Comment by ExcessiveUseOfCobblestone** [comment]
It should give them a random lawset tbh :^)

**Comment by Cyberboss** [comment]
@KorPhaeron Travis

**Comment by KorPhaeron** [comment]
@cyberboss

**Pull request merged**
