### PR TITLE
RLD inhand icons fix

### PR DESCRIPTION
**Pull request by Robustin**
No inhand, no icons, a month of merge conflicts will do that to a man

### CODE REVIEW

**Comment by KorPhaeron** [comment]
are you 100% sure you didnt overwrite anyone elses changes trying to solve conflicts

**Comment by KorPhaeron** [comment]
nevermind it has conflictd

**Comment by Robustin** [comment]
I literally just made a branch off the upstream master, imported my inhands, then had to manually upload them because Tortoise Git doesn't want to play with this branch for some reason arghhh.

**Comment by KorPhaeron** [comment]
I'll make the pr for you

**Comment by KorPhaeron** [comment]
In like an hour or two though my laptop is being borrowed

**Comment by Robustin** [comment]
I think I got it sorted, had to make another branch based on this one and just pulled from master. 

Still not sure why I couldnt make a branch based on master, import, then push here but Tortoise Git never ceases to surprise.

**Comment by Iamgoofball** [comment]
@KorPhaeron Official policy when it comes to icon conflicts is "plow over it, if the icons aren't noticed within 1 month no one probably used it"

this is at least relevant for costumes

**Comment by optimumtact** [comment]
that's not true at all

**Comment by Iamgoofball** [comment]
that's what we all do

**Comment by Iamgoofball** [comment]
ask anyone who's added a clothing item in the past 2 years and had a conflict

**Comment by Robustin** [comment]
Good thing its not relevant because I didn't delete anything (probably)

**Comment by KorPhaeron** [comment]
When I have a conflict I save the latest inhand dmi to desktop from master, put my new inhands into that file, move it into the correct icon folder, and then push said file to my branch

**Pull request merged**
