### PR TITLE
Increases TC cost of Bioterror darts

### PR DESCRIPTION
**Pull request by Dorsisdwarf**
Bioterror: 3TC
Taser darts: 3TC

Crew status: Wrecked every time

Bioterror darts have been increased to 6TC a mag (despite pressure to increase to 8), seeing as they're effectively 1-hit kills in the average combat situation.

### CODE REVIEW

**Comment by WJohn** [comment]
This doesn't fix the problem in that they're one hit kills. They need to be much slower acting, too, by using a different set of poisons.

**Comment by Lumipharon** [comment]
Didnt goof like, just nerf them?

**Comment by blobbernaut** [comment]
they still instantly stun and the coniine stays in your body for 250 tics during which time it poisons you and completely stops you from breathing. You have about 10 seconds before you get knocked out, during which time your vision is destroyed and you can't speak. After that, the breath loss will kill you guaranteed.

These might as well be wands of death because it's as much of a hassle to get the coniine out of your system as it is to defib someone.

**Comment by AlexanderUlanH** [comment]
Making bioterror rounds very powerful is especially bad design since they're also inconsistent, especially once security and the crew arms up to chase the ops in space.  Making them a disable/mute rather than a kill would probably be a better way to balance them.

**Comment by Lumipharon** [comment]
Being in a hardsuit/biosuit/mech/being a borg renders these completely useless, keep in mind.

How fucking slow does conine decay? 250 ticks is fucking long.

**Comment by Boredone** [comment]
Doesn't render them COMPLETELY useless, darts do a base damage of around 6 brute.
Also, Coniine decays at 0.06 units per tick, 5 Losebreath per tick, and around 1.75 Tox damage per tick.
Could probobly be mostly countered with salumbutal if you likely didn't suffocate to death before you recover from the neurotox and sodium thiopental.

**Comment by Iamgoofball** [comment]
Christ, can you guys consider that you can easily treat someone with one of these?

Calomel purge them, it'll knock all the chems out super-fast, then hit them with an epipen to keep them from dying and then apply styptic + salbutamol + charcoal and any other bonus meds

**Comment by Boredone** [comment]
Goof, I think the problem is that it puts them down and keeps them down till they suffocate to death.

And combat medics are rather uncommon, so people arn't going to get treated before they die unless someone drags them to medbay instead of grabbing their guns and shooting the nuke ops.

As a note, I haven't seen them in action since you messed with em, so could be wrong, but I think this should give an idea of why people arn't fans.

**Comment by SconesC** [comment]
goof nobody is carrying around calomel that's silly

nuke fighting and healing is balanced around standard medkits

**Comment by Iamgoofball** [comment]
or maybe instead we change standard medkits to be useful at treating things other than brute/burn?

**Comment by SconesC** [comment]
no?

**Comment by Iamgoofball** [comment]
give me a good reason why that's a bad thing

**Comment by Jalleo** [comment]
@Iamgoofball this is where your design fails medikits are specific and what you are suggesting is make them mini portable medbays the toxin dart needs changing to not be a instant death.

**Comment by Iamgoofball** [comment]
there's a difference between a mini portable medbay and some very basic shit to keep someone from dying while you transfer them to medbay

**Comment by Actionb** [comment]
NukeOps do not give you time to recover the wounded. When the ops strike, shit gets hectic and chaotic and everyone needs to act quickly. If you go down, you're dead - simple as that. You can't balance an item around the hope that one MD knows how calomel and salbutamol works.
Two days ago a strike team killed >50% of the crew (35-40 people) with the 'nerfed' bioterrors.

**Comment by Iamgoofball** [comment]
@Actionb 

Are you fucking kidding me? Fuck off with that "dey dunt knaw hauw da meeds wark!1!!" shit, you know it's not true. If a MD doesn't know what Salbutamol(the replacement for DEXALIN) does then why the fuck is he trying to heal people in the field?

Plus, we don't give a fuck or balance around bad players. Literally a case of get good with the meds.

I'll nerf bioterrors again and do the medkit buffs at the same time, the only reason to try and deny the medkit buffs will be if you don't play medbay and are trying to go after "muh balance", and you better fucking know that medbay balance is a non-existent thing because "balanced" medbay isn't fun. If it isn't fun, it's not good.

**Comment by Dorsisdwarf** [comment]
The problem with the darts is that, even if there are 100% competent MDs waiting around the corner to baby you back to health, /the nuke ops have already made off (usually after taking your guns) with the disk/.

Bioterror darts are essentially taser slugs which take a moment to kick in, then keep you stunned until a medic shows up. Which he probbably won't, because if he was in responding range to get there in time to do anything useful, the nuke ops shot him too.

**Comment by Actionb** [comment]
Haha, you think 'git gud' is an appropiate response to operatives massacring the crew with doom darts because most of the MDs are casual players that can barely operate a defib and don't know the mysteries of goofchem? Let alone the possibility that the medics themselves were shot and the fact that ops do not stop pursuing the disk throughout all that. Get a grip.
Why not restrict the death chemicals to the chemsprayer? Bulldog is good enough as it is.

**Comment by Iamgoofball** [comment]
you missed the 
>I'll nerf bioterrors again
part

**Comment by Dorsisdwarf** [comment]
Thats not the point. Nuke ops *need* strong gear, stuff which can take down the toughest enemies the station has to offer.

The problem is that this is one of the most powerful weapons available to nuke ops, and costs only 3TC as an option for the free starter gun. That's the real problem, not the fact that it's deadly.

Hell, the biotoxins sprayer is this but worse, and has an area of effect with a giant reservoir. But it's well-balanced because it's very expensive.

**Comment by Cheridan** [comment]
these clearly shouldn't be the same price as taser shots

**Comment by Lumipharon** [comment]
Taser shots are already overpriced and never used.
They now cost THREE TIMES as much as slugs, which are also OP as fuck.
6 tc = 12 kills with slugs, or 8 kills with biotox, that doesn't effect anything with thickmaterial, or borgs/mechs.

**Pull request merged**
