### PR TITLE
Resprites the Syndicate Infiltrator Modsuit

### PR DESCRIPTION
**Pull request by EnterTheJake**
## About The Pull Request
Resprites The Infiltrator Modsuit.

Infiltratorresprite

## Why It's Good For The Game

The infiltrator modsuit looks a bit dated, it's still mostly using the same model it had back when it was a regular suit, the colors are also kinda drab, point is, it doesn't look too great; this PR fixes that.

Sprites made by OrcaCora
## Changelog
:cl:
image: The Infiltrator Suit has received a new model, sleeker than ever!
/:cl:

### CODE REVIEW

**Comment by SinfulBliss** [comment]
Doesn’t look distinct enough from the syndie mod IMO. Also kinda reminds me of the old red miner hardsuit.

**Review by Wallemations — CHANGES_REQUESTED** [review]
move the pic into the `about` section, and fix your changelog to only have the `image:` section _inside the :cl: brackets_

**Comment by necromanceranne** [comment]
The cl entry needs to be formatted like this
```
image: The Infiltrator Suit has received a new model, sleeker than ever!```

**Review by Wallemations — APPROVED** [review]

**Comment by uaioy** [comment]
more of a nitpick but ill miss the visor being just as red as the suit

**Pull request merged**
