### PR TITLE
Changes blahaj description

### PR DESCRIPTION
**Pull request by TheVekter**
## About The Pull Request
I had a couple of trans folks come to me and say they felt the old description wasn't appropriate. That's a fair concern, so I'm changing it.

## Why It's Good For The Game
The whole point of adding a blahaj expy was as a fun nod to the trans members of our community. I'm not really succeeding at that if part of it is making some of them uncomfortable.

## Changelog
:cl: Vekter
tweak: Changed the description on the shark plush.
/:cl:

### CODE REVIEW

**Comment by mikederkan** [comment]
thats what you put the original description as...????? 

:(

**Comment by orthography** [comment]
Good change, glad you're keeping yourself honest. Love u

**Comment by ChungusGamer666** [comment]
this is so NOT wholesome you guys

**Comment by moonheart08** [comment]
what is the point of this, really.
i am trans and i'd be more insulted by the *removal* than anything.

**Comment by dessysalta** [comment]
> i am trans and i'd be more insulted by the _removal_ than anything.

Trans person here. I think the reference should be kept, but if there's more than a few people who think it's strange or wrong then I don't really care. Better to be all-inclusive with a reference like this; could potentially come off as stereotypical otherwise, so I can defy see the concerns past feeling offended.

**Comment by TheVekter** [comment]
> > i am trans and i'd be more insulted by the _removal_ than anything.
> 
> Trans person here. I think the reference should be kept, but if there's more than a few people who think it's strange or wrong then I don't really care. Better to be all-inclusive with a reference like this; could potentially come off as stereotypical otherwise, so I can defy see the concerns past feeling offended.

This is the decision I also came to. Keeping it has little benefit and the item itself is already pretty clearly a nod to trans culture, so if the description was making some people feel tokenized, I have zero issue removing it. I'm sorry if it bothers you that it's gone.

**Comment by cats4gold** [comment]
not losing much by taking this out so if its upsetting people i dont see why not. maybe the shark could be popular with/made by moths considering mothic is space-swedish

**Review by Mothblocks — APPROVED** [review]
I was the one that brought it up (but didn't necessarily ask for a change) because I see these as Reddit stereotypes that weird me out

**Comment by TheVekter** [comment]
> I was the one that brought it up (but didn't necessarily ask for a change) because I see these as Reddit stereotypes that weird me out

I'd had a couple others note it a few times, but yours reminded me about wanting to fix it.

**Comment by AviiCinders** [comment]
can we get pickle rick back while we're doing cringe stuff like this thanks

**Comment by TheVekter** [comment]
> can we get pickle rick back while we're doing cringe stuff like this thanks

No, oranges demanded it be removed also you're cringe

**Comment by AviiCinders** [comment]
> > can we get pickle rick back while we're doing cringe stuff like this thanks
> 
> No, oranges demanded it be removed also you're cringe

I can't figure out how to add an embed here so just pretend I posted that one picture of an emoji being dusted

**Pull request merged**
