### PR TITLE
Reduces the taser firing delay.

### PR DESCRIPTION
**Pull request by theOperand**
20 was really slow, 10 is really fast.

i don't play sec nor antag, i will not participate in the discussion.

### CODE REVIEW

**Comment by Kromgar** [comment]
Inb4 Not-Pap returns

**Comment by Mandurrrh** [comment]
Good luck! I think this is a fair compromise.

**Comment by AlexCrimson** [comment]
So when a PR is closed, all you need to do is make another with slightly changed numbers until its merged? Neat.

**Comment by Dorsisdwarf** [comment]
Yes, it's called "balancing".

**Comment by Miauw62** [comment]
fyi i will pre-emptively remove bullshit from this PR. I am a maintainer and want to encourage HEALTHY and CIVIL discussion about these issues.

There is a significant difference between complete removal of the firing delay and this adjustment (while small, the difference feels quite big when firing a taser). Imo the original PR should never have been closed in the first place but as it had already exploded this will have to take its place.

**Comment by SconesC** [comment]
Regular Security & Antag player thoughts on the matter:

Yes, please yes, the electrode delay is horrible. It can often mean the difference between life and death and electrodes are already a very finnicky projectile that only work sometimes. This is a huge QoL change for Security at this point, not even balance.

**Comment by Cheridan** [comment]
>Miauw:	btw im impressed
>Miauw:	[8283] hasn't even exploded yet

:boom: :older_man:  :boom:

**Pull request merged**
