### PR TITLE
Moves the massive obj layer up several times

### LINKED ISSUE #45669: Some screens render over Nar'Sie
APC screens, light tubes, some computer screens render over nar'sie and it looks weird
7ae1512f1017512801359297372f5915

### PR DESCRIPTION
**Pull request by tralezab**
fixes #45669

I'm gonna test this real quick to see if it doesn't make narsie jump out of my screen and kill me

### CODE REVIEW

**Comment by SpaceManiac** [comment]
please do test, I'm not convinced this will actually fix it

**Comment by tralezab** [comment]
you're right, it wasn't the fix. Any idea what would be the fix?

**Comment by SpaceManiac** [comment]
I don't think there is one, this is just part of all the other layering issues with the fullbright overlays. Putting them above the lighting plane means they are also above anything which is subject to lighting.

We are waiting on possible new BYOND features which may help.

**Comment by tralezab** [comment]
understood.

**Pull request closed without merging**
