### PR TITLE
Pickle Jars are now made of glass instead of cardboard and are now non-foldable.

### LINKED ISSUE #71083: Pickle Jar Folds Into Cardboard
Reporting client version: 514.1588

## Round ID:
[193733](https://scrubby.melonmesa.com/round/193733)

## Testmerges:
None

## Reproduction:
1. Aquire jar of pickles by crafting or ordering
2. Empty the jar
3. Activate in hand and watch as it magically turns to cardboard

I'm pretty sure this is because it is defined as a fancy box in the code.
~~Is it possible to change the fold_result to a large beaker?~~ When you activate it there is text that says "folded"
https://github.com/tgstation/tgstation/blob/35acc39763321ece6c83e519c38d152d6fd491fb/code/game/objects/items/storage/fancy.dm#L464-L474
https://github.com/tgstation/tgstation/blob/35acc39763321ece6c83e519c38d152d6fd491fb/code/game/objects/items/storage/fancy.dm#L30

### PR DESCRIPTION
**Pull request by san7890**
## About The Pull Request

This is done by making it impossible to fold a jar. You can not fold the jar, clicking on the pickle jar will do nothing and you will be stuck right back where you were before you tried to fold the jar. Because: what the fuck? Folding a glass jar? Huh?
## Why It's Good For The Game

Fixes #71083.

Come on, _folding_ a jar? What the hell? The jar seems to use the rest of the fancy_box API, so I think it's fine to just have nulls be valid in this context.
## Changelog
:cl:
fix: You can no longer fold a glass pickle jar into cardboard. It will also no longer recycle into cardboard as well.
/:cl:

### CODE REVIEW

**Comment by ZeroMODE0** [comment]
not my pickle juice cardboard!

**Comment by epicgamer545** [comment]
NOT THE PICKLE CARDBOARD!

**Comment by JohnFulpWillard** [comment]
anti-pickle propaganda

**Comment by Time-Green** [comment]
i fucking hate coders

**Comment by Wallemations** [comment]
I now understand what George Orwell meant when he wrote his critically acclaimed book "Animal Farm"

**Comment by Shadowflame909** [comment]
We live in a society where pickle jars are made out of unfoldable cardboard

**Comment by MTandi** [comment]
@san7890 maybe it should drop beaker/jar instead of nothing?

**Comment by D4C-420** [comment]
literally fahrenheit  451 getting rid of perfectly good paper and paper products.

**Comment by Profakos** [comment]
Another issue: its made of Large Beakers but the custom materials are not glass, so the recyclers can still cardboardize them...

**Comment by san7890** [comment]
> Another issue: its made of Large Beakers but the custom materials are not glass, so the recyclers can still cardboardize them...

I'll pass in that fix as well.

> maybe it should drop beaker/jar instead of nothing?

The inherent issue is in the word "fold". I added new behavior to fancy box's attack self which means that if the foldable result will yield nothing, it will become impossible to ever fold it. If you try and fold a pickle jar, nothing happens and you will retain the same pickle jar.

**Comment by optimumtact** [comment]
It's common knowledge that pickles come in cardboard jugs in canada san

**Comment by JohnFulpWillard** [comment]
bagged milk 2: cardboard pickles

**Comment by san7890** [comment]
BUT IT'S A JAR IN SS13!!! A JAR!!!

**Comment by zxaber** [comment]
Would folding a jar make it ajar?

**Comment by Bobthe28th** [comment]
It would be nice for some way to get the beaker back, or the ability to craft pickles with a large beaker OR an empty pickle jar.

**Comment by san7890** [comment]
> It would be nice for some way to get the beaker back, or the ability to craft pickles with a large beaker OR an empty pickle jar.

I mean, if you recycle it you'll get the glass, and you can use that recycled glass (now in the ore silo) to print out the beaker at a protolathe. Bit more roundabout, but it makes sense as opposed to using nothing but your hands to get a beaker back.

**Pull request merged**
