### PR TITLE
Buffs The Ecto-Sniffer Again

### PR DESCRIPTION
**Pull request by unit0016**
## About The Pull Request
Not even a louder sound got roboticists to pay attention to this machine, so I've done it.
This adds a a 'say()' to the ecto sniffer, along with a handful of silly (and spooky) phrases for it to say. 

## Why It's Good For The Game
Roboticists please just make cyborgs, I'm begging you. It's the whole point of your job. I don't want to make this even more absurd.

## Changelog

:cl:
accessibility: Ectoscopic Sniffers now shout a handful of silly phrases to remind robotics to not ignore them, and to accommodate deaf players.
/:cl:

### CODE REVIEW

**Comment by derekhearst** [comment]
Good change, its easy to miss the sniffer... hopefully this will teach roboticists to have posibrains laying about

**Comment by Cheshify** [comment]
Big accessibility bonus too, there's no way for deaf players to even really notice the sniffer

**Comment by Djaub** [comment]
Oh god I really hope it will be merged AND work.

Emphasis on "work" because as I said in #65065 ; I tested with other players on live server (Terry), and it wasn't only a volume problem. I couldn't even see the visual cue (green light), sounds didn't work either; you see them when you are dead and you activate it tho.

**Comment by unit0016** [comment]
> Big accessibility bonus too, there's no way for deaf players to even really notice the sniffer

I should've flagged this as accessibility immediately tbh

**Comment by iwishforducks** [comment]
in my honest opinion, the sniffer should just cut the crap and say "Ectoplasma detected. Consider constructing posi-brains." because the only nincompoops that don't build posi-brains at this point are complete newbies at roboticist. anyone that knows what "Clown levels of paranormal activity" means **already knows** that they need to build posi-brains.

**Comment by unit0016** [comment]
> in my honest opinion, the sniffer should just cut the crap and say "Ectoplasma detected. Consider constructing posi-brains." because the only nincompoops that don't build posi-brains at this point are complete newbies at roboticist. anyone that knows what "Clown levels of paranormal activity" means **already knows** that they need to build posi-brains.

My hope is they (new players) will examine the machines and read the blue text that explains it's purpose naturally without it feeling heavy-handed, and those actively, deliberately shirking their entire role to build big stompy mechs, three AIs, and modsuits will be caught in the excuse of *"I don't know what it does!"* not working.

**Comment by Addust** [comment]
DONT LET THE FLAME DIE OUT

**Comment by unit0016** [comment]
😔

**Comment by bruhlookatthisdood** [comment]
no stop
i need this ):

**Pull request merged**
