### PR TITLE
Buildable Display Cases

### PR DESCRIPTION
**Pull request by AnturK**
~~Makes display cases buildable with 10 metal (Don't ask where the glass comes from)~~
Makes display cases buildable with 5 wood and 10 glass sheets. (Chassis from wood then add glass)
Airlock electronics can be added to the chassis to let it be opened by ID card.

The cases without alarm (Lamarr cage and created) can now be opened with a crowbar.

### CODE REVIEW

**Comment by Chocobro** [comment]
yes this is good

**Comment by WJohn** [comment]
Why does it have to be built out of 10 metal? Why not out of glass instead?

**Comment by AnturK** [comment]
Mostly because i'm lazy and i'd have to add construction menu to glass. Which still uses the popup.

**Comment by Incoming5643** [comment]
You could also have just the base be constructible out of wood/metal then add glass to it as a finishing step

**Comment by GunHog** [comment]
Yes, that. Much better idea.

**Comment by AnturK** [comment]
Oh yeah, that's better. Will change it soonish.

**Comment by Lumipharon** [comment]
Should be able to make one using airlock electronics and maybe r-glass to make a somewhat more secure one with ID access.

Still smashable of course, but it seems pretty peasant to have to use a crowbar to open your own case.

**Comment by GunHog** [comment]
^Agreed with above. Being able to ID lock it would be awesome.

**Comment by Razharas** [comment]
@AnturK 
Merge conflicts

**Comment by AnturK** [comment]
Ugh. Maps.

**Comment by AnturK** [comment]
Should be good now.

**Pull request merged**
