### PR TITLE
Blacklists servant golems from the magic mirror

### PR DESCRIPTION
**Pull request by ghost**
:cl: Xhuis
balance: Servant golems no longer appear in the magic mirror race list.
/:cl:

This is absolutely not intentional and is grossly overpowered on a wizard!

### CODE REVIEW

**Comment by Buggy123** [comment]
Yes, its a power boost, but the entire game exists in a state of continuous, slow, completely unstoppable power creep, so this is to be expected.

**Comment by optimumtact** [comment]
If you make one more dumb comment along the lines of "things are already broken, so its fine if they break further" I will toss you on our shitlist

**Comment by Buggy123** [comment]
Okay fiiiiiiiine merge it I guess.

**Comment by Robustin** [comment]
Theres 2 clockwork golem species though

**Comment by Xhuis** [comment]
Normal clockwork golems have the drawbacks of other golems like not being able to wear clothing.

**Comment by AlexTheSysop42** [comment]
The thing is, it's definitely op for wiz and should be blacklisted from there, but I feel like it should be kept on the pride's mirror if possible as a reward for anyone who goes to the trouble to do that

**Comment by Iatots** [comment]
Shouldn't runic golems also be on the list?

**Comment by BeeSting12** [comment]
its downside is that theyre nonhuman if the wizard wants to forfeit their AI protection then let them.

**Comment by Xhuis** [comment]
Losing AI protection is extremely small compared to shock immunity, innate armor, spacewalking, no breathing, immunity to cold, high-damage punches with great stun chance, and syringe guns not affecting you.

**Comment by Mey-Ha-Zah** [comment]
Xhuis please don't remove my Pride Mirror Shenanigans.

**Comment by Xhuis** [comment]
As far as I'm concerned, there should never be a "best pick" for magic mirrors, including pride mirror. Picking servant golem removes the risk involved by making you immune to space, so when you're spaced it doesn't have any impact as long as you can navigate to the station by throwing things.

**Comment by Buggy123** [comment]
Well, being spaced can easily take you out of the rest of the round because of how _big_ space is. I've had instances where I've used the mirror without a jaunter/fulton and I never manage to find my way back to the station.

**Comment by Xhuis** [comment]
I feel as though you and others are dancing around the issue at hand of there being a race with *a single tiny downside* with *extreme upsides* being obtainable by wizards (who are already very powerful) and any crew if the pride ruin spawns. It is absolutely not balanced at all.

**Pull request merged**
