### PR TITLE
Makes swarmers immune to spacewinds

### PR DESCRIPTION
**Pull request by Cyberboss**
At the request of @Arianya

### CODE REVIEW

**Comment by coiax** [comment]
I feel like this should be a flag or something.

**Comment by optimumtact** [comment]
This is a rebalance and Kor said they were not allowed sorry

**Comment by KorPhaeron** [comment]
@Cyberboss 

Why is this needed

**Comment by ChangelingRain** [comment]
Swarmers shouldn't be anywhere near spacewind

**Comment by KorPhaeron** [comment]
I never got an answer on why this is needed and swarmers ideally shouldn't be causing atmos troubles

**Pull request closed without merging**
