### PR TITLE
Is that a fucking rocke-

### PR DESCRIPTION
**Pull request by Ryll-Ryll**
## About The Pull Request
Being hit directly by a rocket launcher now has a 1% chance to make you briefly try processing what's about to happen before exploding you.

[](https://i.imgur.com/APpswYr.png)

## Why It's Good For The Game
Famous last words, no?

### CODE REVIEW

**Comment by Mothblocks** [comment]
image

**Comment by Nobelium-XVIII** [comment]
speedmerge

**Comment by FernandoJ8** [comment]
Please hurry with the merge, there are nukies in cargo and I need reinforcem-... Is that a fucking ro-

**Comment by ATH1909** [comment]
eh, I feel like this is less funny if it's forced by the game instead of being natural.

**Comment by Imaginos16** [comment]
Holy moly this has me in tears, thank you shaps for making the best PR.

**Comment by JosephJomama** [comment]
> eh, I feel like this is less funny if it's forced by the game instead of being natural.

\*about to get shot by a rocket* 
\*hits T and types out "Is that a fucking rocket"*
DEAD: JosephJomama says, "Is that a fucking rocket"

**Comment by iwishforducks** [comment]
The obvious solution is to implement Trouble In Terrorist Town's corpse info screen fit with the "last words" info card so that this can happen naturally. 
image

**Comment by ATH1909** [comment]
> > eh, I feel like this is less funny if it's forced by the game instead of being natural.
> 
> *about to get shot by a rocket*
> *hits T and types out "Is that a fucking rocket"*
> DEAD: JosephJomama says, "Is that a fucking rocket"

I mean, that basically happened in the "Nukie cargo" image, which is part of why it's so funny.

**Comment by LemonInTheDark** [comment]
I think it's funny

**Pull request merged**
