### PR TITLE
Holiday changes

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request
This moves the Indigenous Peoples' Day holiday to the date on which it is celebrated in Brazil and adds the National Day of Spain holiday (October 12) and the International Day of the World's Indigenous Peoples.

## Why It's Good For The Game
More actually decent holidays, less skubby holidays related to american politics

## Changelog
:cl:
add: Added National Day of Spain
add: Added International Day of the World's Indigenous Peoples
tweak: Replaced US Indigenous Peoples' Day with Brazillian Indigenous Peoples' Day 
del: Skub amounts in the codebase have been reduced by approximately 0.02%. 
/:cl:

### CODE REVIEW

**Comment by Jared-Fogle** [comment]
hmm this feels low effort to me

**Comment by interestingusernam3** [comment]
>hmm this feels low effort to me

Is that a problem?

**Comment by Jared-Fogle** [comment]
yea, especially when you start removing tests

**Comment by optimumtact** [comment]
The american indigenous day should still be replaced with the UN holiday

**Pull request closed without merging**
