### PR TITLE
[👍 icebox] 🐝 tany Nerfs and other fixes/adjustments

### PR DESCRIPTION
**Pull request by Zytolg**
## About The Pull Request

The Apiary in Botany was mass producing 🐝 . Much to the chagrin of Icebox botanists, they swiftly took over hydroponics.

## Why It's Good For The Game

As much as the bees like the party, botany is a serious workplace.

## Changelog
:cl:
fix: Missing APC in Bar Maint
fix: 🐝 🐝 🐝  and 🐝 gone!!
fix: Disposals was unlinked under the bar table. This should fix that.
fix: It was stated that the new department lacks some visibility so I added some windows to Upstairs Botany to help with that. 
/:cl:

EDIT: **This is NOT a bee nerf. This is a fix addressing the usage of the incorrect Apiary Type mapped into Icebox Botany.**

### CODE REVIEW

**Comment by LemonInTheDark** [comment]
lmao bees

**Comment by dondonpow** [comment]
I fucking hate emojis

**Comment by SmArtKar** [comment]
You _**can't**_ shove a BALANCE change into a fix tag. That's not how it works.

**Comment by AndroidMK2** [comment]
Basically: Aaaa i died to bees one round! Bees too op I must remove them from the station they killed me at aaaaa!

**Comment by MrMelbert** [comment]
for those wondering: this pr doesn't actually remove the bees from icebox, the icebox service remap used the incorrect subtype for apiaries and this pr fixes it

it's a fix, there is no balance here

**Comment by Timberpoes** [comment]
To address an impending race to the bottom, I'm closing any PRs I see with emojis in either the changelogs or PR title.

You are free to open the same PR again without the emojis.

**Comment by interestingusernam3** [comment]
mso_photo

**Comment by optimumtact** [comment]
https://user-images.githubusercontent.com/2544323/128650868-44b8cc56-0b69-4b2c-9610-00c4f8a570d9.mp4

**Comment by MrStonedOne** [comment]
image
image

**Pull request closed without merging**
