### PR TITLE
Adds log parsing sql email alert script

### PR DESCRIPTION
**Pull request by Jordie0608**
Powershell script which reads through `.log` files from the current date to search for the SQL error keyword `SQL:`. If found an email is sent to user defined addresses. This requires a SMTP server but Gmail's can be used for that (although it replaces the from address with the gmail account).

This was basically entirely designed for our servers so I can't guarantee functionality if another server's directory structure is different for whatever reason. However the script is pretty configurable so that shouldn't be a problem.

Obviously not natively supported on Linux; it's possible to install a powershell package if you want to run this, but I figure if you're hosting off Linux you're probably competent enough to recreate the script yourself anyway. Plus I don't know shell.

@MrStonedOne

### CODE REVIEW

**Comment by Jordie0608** [comment]
For reference the email produced looks like this:

>This is the body of the mail.
	@{Path=D:\ss13\-tg-station\data\logs\2017\08\03\round-17.30.34\game.log; Line=[17:30:57]GAME: Derelict 4 loaded at at 26,193,6}
	@{Path=D:\ss13\-tg-station\data\logs\2017\08\03\round-17.40.54\game.log; Line=[17:41:13]GAME: Derelict Tradepost loaded at at 35,86,3}
	@{Path=D:\ss13\-tg-station\data\logs\2017\08\03\round-17.47.14\game.log; Line=[17:47:35]GAME: Derelict 6 loaded at at 126,97,7}
	@{Path=D:\ss13\-tg-station\data\logs\2017\08\03\round-17.57.51\game.log; Line=[17:58:12]GAME: Derelict Tradepost loaded at at 47,111,3}
	@{Path=D:\ss13\-tg-station\data\logs\2017\08\03\round-18.04.11\game.log; Line=[18:04:35]GAME: Derelict Tradepost loaded at at 70,155,9}
	@{Path=D:\ss13\-tg-station\data\logs\2017\08\03\round-18.24.48\game.log; Line=[18:25:07]GAME: Derelict 5 loaded at at 55,34,10}

**Comment by lzimann** [comment]
Doesn't seem to hard to make a shell script. One thing though, does SQL only happens when it errors? Also it will trigger for people saying SQL:(not that anyone ever says). 
This is a good idea nonetheless.

**Comment by Jordie0608** [comment]
It probably isn't.

Yes, `log_sql` is only called when there's an SQL error https://github.com/tgstation/tgstation/search?q=log_sql

Can't really prevent people forcing false positives without reasonable changes to the logging, if someone can say `SQL:` then they can say `[16:07:13]SQL: Table 'feedback.role_time' doesn't exist | Query used: SELECT job, minutes FROM role_time WHERE ckey = 'jordie0608'`. I don't think it'll come up enough to be a problem.

**Comment by lzimann** [comment]
Yea I doubt it will be much of a problem. I might try to do a quick shell script, but no promises on this.

**Comment by nfreader** [comment]
Would be cooler if it talked to something like an Amazon SNS topic or using Mandrill to alert interested parties. This also might be something to integrate into MSO's log-cleaner that was posted to the website repo yesterday. Still neat though!

**Pull request merged**
