### PR TITLE
Removes secborgs again

### PR DESCRIPTION
**Pull request by anconfuzedrock**
I love new flashes but I don't love the fact that a standard borg can flash people and ziptie them they are better at keeping peace than panda borgs

### CODE REVIEW

**Comment by anconfuzedrock** [comment]
huh why are those changes there

**Comment by KorPhaeron** [comment]
how are flashes real just cover your eyes hahaha

**Comment by anconfuzedrock** [comment]
I need to go fix this

**Comment by Kraseo** [comment]
😊

**Comment by Anonmare** [comment]
@anconfuzedrock getting dunked by flashes lmao

In all seriousness this is just going to fuck over malf AIs even more if they have the robot army objective. It's already hard enough coordinating an engiborg and a standard borg to stun and restrain someone but now you won't even be able to do that.

**Comment by ExcessiveUseOfCobblestone** [comment]
someone's been touching master!

**Pull request closed without merging**
