### PR TITLE
Dead things can't be used to open doors

### LINKED ISSUE #22334: Dead drones can be used to open doors
The following is for cyborgs and drones(PREFERBLY DEAD DRONES)

So today i killed a drone i wondered if i alt click the door pull the drone then click the floor so it forced it into a door and guess what IT OPENED! DEAD DRONES ARE THE ULTIMATE ALL ACCEED

### PR DESCRIPTION
**Pull request by Cyberboss**
Fixes #22334 

:cl: Cyberboss
fix: Dead things can no longer be used to open doors
/:cl:

### CODE REVIEW

**Comment by coiax** [comment]
But then I'll have no reason to cut off the captain's hand to use the thumb scanner

**Comment by XDTM** [comment]
We gotta add thumb scanning doors

**Comment by RandomMarine** [comment]
Just have drones lose their access on death.

**Comment by Arianya** [comment]
>Just have drones lose their access on death.

**Comment by coiax** [comment]
Just make sure to give them their access back if revived.

**Comment by jughu** [comment]
who even revives drones they just go to a new shell and get to their dead body

**Comment by PKPenguin321** [comment]
:-1: Using dead borgs on doors is a feature

**Comment by optimumtact** [comment]
It's not a feature it was an oversight.

Cry more powergamers.

**Comment by Cyberboss** [comment]
Based fruit

**Comment by PKPenguin321** [comment]
No, it was a feature

**Comment by Nanotransistor** [comment]
Wew more emergent gameplay gets pushed out.

**Comment by RandomMarine** [comment]
"State laws" to force a silicon to state every law.

**Comment by Alek2ander** [comment]
Please change it to dead silicons only, throwing human corpses at doors should be a thing.

**Comment by PKPenguin321** [comment]
Yeah that too

This needs to just apply to drones, this is tragic loss of actual emergent gameplay

**Comment by optimumtact** [comment]
Absolutely not, this was a bug, it has always been a bug A dead cyborg corpse is not supposed to be a license for all access

**Comment by PKPenguin321** [comment]
Bullshit

**Pull request merged**
