### PR TITLE
Lowers singulo lag by making it only pull half of the items in range per tick.

### PR DESCRIPTION
**Pull request by MrsTonedOne**
the set of items should properly randomize.

### CODE REVIEW

**Comment by Shadowlight213** [comment]
Does it still pull mobs every tick?

**Comment by MrStonedOne** [comment]
no, it would treat them the same as all other things, regardless.

**Comment by Shadowlight213** [comment]
Would be nice if it skipped the pull randomization for mobs so the sing isnt less deadly.

**Comment by MrStonedOne** [comment]
I might make it only apply to throwing items by moving it to item's singulo pull

**Comment by Aranclanos** [comment]
this is not how you fix lag
gay as fuck :-1:

**Comment by Bawhoppen** [comment]
when will it fucking pull ghosts again when are you fixing that

**Comment by optimumtact** [comment]
Don't think I don't see you meming about this pull @Clusterfack

**Comment by optimumtact** [comment]
Also the singularity isn't the cause of the LAG, it's the atmos triggering and the deletions

**Comment by duncathan** [comment]
This is a shitty bandaid fix to a problem that is really only a minute part of a larger whole :-1:

**Pull request closed without merging**
