### PR TITLE
New ghost role: Ancient Android Outpost

### PR DESCRIPTION
**Pull request by nyozzl**
## About The Pull Request

Adds a new ghost role the ancient android outpost... an outpost inside a SUPER-DENSE asteroid fitted with ordnance... circuit lab.. robotics.. and cytology

## Why It's Good For The Game
I believe the current state of ghost roles has gotten quite stale so I made this to add to the pool...

## Changelog

:cl: Nyozzl
add: New ghost role Ancient Android Outpost
/:cl:
android rnd ruin
corner 1
corner 2
corner 3
corner 4

### CODE REVIEW

**Comment by Livrah** [comment]
Looks like something from 2015.
I like the idea of messing with circuits/toxins as a ghost role, but there is nothing valueble enough to hide behind undestructable walls.

**Comment by Admiral-Gigaton** [comment]
This seems like content you could add to charlie station, and just make charlie a garunteed spawn like whiteship. Not saying its a bad pr, i have no grounds to say that in a case like this(see: lack of contributor icon) but i dont think this would work out, let alone pass maintainer standards.

Maybe replace the walls with regular stuff, get some botany jazz, and lower the anomally core count? Also, add experimentor item spawn locations, otherwise its nigh useless, and a whole RnD server so they have stuff to do that doesnt affect stationside? Also, whats their whole position on NT nerds, are they opposed, with, nuetral? Can they defend themselves? Do clarify that, as well as your "why its good for the game" (you know jaqc is gunna tell you to...) and what is actually IN the place, besides screenshots

**Comment by carlarctg** [comment]
> Looks like something from 2015.
you say that like it's a bad thing

**Comment by carlarctg** [comment]
i really like the idea of a robot outpost where they tinker with robot and other such stuff not covered in other ghost roles! this pr is fun. the unbreakable walls are a pretty lazy method of not allowing them to flood the station with ghost role content, but im unsure what'd theoretically replace it.

**Comment by mc-oofert** [comment]
Finally,,, I can play station roles without having to interact with the rest of the game

**Comment by Loafin34** [comment]
what if it wasn't invincible rock but they had bomb collars on them that detonated when they left to another z level?

**Comment by nyozzl** [comment]
right.... gotta work on it...

**Pull request closed without merging**
