### PR TITLE
Removes the Null Crate

### PR DESCRIPTION
**Pull request by Iamgoofball**
:clap: you :clap: dont :clap: need :clap: free :clap: traitor :clap: items :clap: every :clap: shift :clap: 

1. dont pretend money is hard to get even with the stock fix
2. dont pretend free traitor items is balanced
3. dont pretend this was a good idea
4. i added this garbage to the game so i can take it out of the game

### CODE REVIEW

**Comment by KomradeSpectre** [comment]
Can we get a label for 'Codebase/Player Separation'?

**Comment by uraniummeltdown** [comment]
You either die a hero or live long enough to see yourself become a villain

**Comment by MrDoomBringer** [comment]
look at the time

**Comment by iskyp** [comment]
null crates are shit but it's better to try and change something rather than nuke it

**Comment by Arianya** [comment]
There are better ways to solve null crate abuse (if its happening) then outright removal.

**Comment by Iamgoofball** [comment]
i don't believe there's ever been a time where end game cargo isn't swimming in traitor gear

**Comment by Arianya** [comment]
is that "i refuse to believe this because it would contradict my beliefs" or "i don't believe there has been such an instance based on this data i have"?

**Comment by Kraseo** [comment]
you don't believe it because you don't play the game

**Comment by AlexTheSysop42** [comment]
Both. He doesn't play and he also won't believe it.

**Comment by Iamgoofball** [comment]
@Arianya every time I have played and cargo isnt dead by the 60 minute mark, they've found a way to get a null crate or 15.

**Comment by Shadowflame909** [comment]
Goof hates fun confirmed. First we remove holoparasites from null crates. Now we remove them in general. My only response to this. 1. Dis butter not get removed for no reason other then "I hate fun" and 2. If you remove it replace it with something else we're losing features reee. Also 3. Cobby removed things they didn't like from null crates, romerol, and holoparasite injectors. Why can't you just remove individual things that you don't like? Oh, that's right. You don't play so you wouldn't even know what these do. Reeeeee

**Comment by Aloraydrel** [comment]
Goof is just mentally ill and needs her pills

**Comment by TheDreamweaver** [comment]
Remember when goof tried to remove hulk... for being unbalanced... by replacing is with laser vision... 🤔

**Comment by Iamgoofball** [comment]
>implying a shitty laser gun is better than stun immunity
🤔

**Comment by TheDreamweaver** [comment]
Wait please tell me you're still not arguing for that horribly thought out idea. Ya, unlimited lasers that are implanted directly you are powerful enough to not be considered a balance tweak. Speaking of lasers, last time I check, hulks aren't laser immune. But I digress, my point was to show that you're not above making rash, unvalidated (man do I want to see what your actual playtime is) "balance tweaks". Its a shame that it comes down to this, but even more so that you can't accept criticism, especially since you do occasionally have some good and creative ideas.

**Comment by Shadowflame909** [comment]
So what's supposed to happen when people reach the end of there roles. Shaft miners get op shit. Robotics gets op shit. Science gives everyone op shit. But for some reason cargo shouldn't have very far end game items. Honestly Everytime I've seen this happen is when everything is maxed out and xenos start to spawn.

**Comment by arsserpentarium** [comment]
Need to mention, that it's a little bit unhealthy situation, when endgame consists of crates of random traitor items and bycicles.
It's not reason to remove them, but cargo needs buff.

**Comment by Shadowflame909** [comment]
Medicals end game is romerol zombies now. End of the rounds are OP for any job.

**Comment by TheDreamweaver** [comment]
No point in arguing using real in-game experiences to someone who doesn't even play the game.

**Comment by Iamgoofball** [comment]
Cargo should have their own unique end game shit, not piggy backing off of traitors.

**Comment by Bawhoppen** [comment]
Merge this posthaste. It's about time we cut back on the creep.

**Comment by evsey9** [comment]
actually, better idea: make ordering null crates spawn a nuke ops team

because stop stealing from the syndicate

**Comment by arsserpentarium** [comment]
Cargo should. But it hasn't.
So go make some cool op crates, which costs fuckton of money.
Look, one more better idea to PR.

**Comment by RandomMarine** [comment]
If this gets merged bring back money trees because MUH NULL CRATES is no longer an excuse to not have fun ways to profit.

**Comment by evsey9** [comment]
Infinite c4s and grenades isnt really good either

Also infinite shotguns

**Comment by 81Denton** [comment]
I liked the medbay shitpost PRs better

**Comment by kevinz000** [comment]
Baw swat gear hoppen crying about creep

**Comment by Shadowflame909** [comment]
>cutback on the creep.                              This phrase makes me angry. Saying "oh no power creep!!!!!1" isn't an argument and isn't saying anything. It's as bad as the slippery slope meme. Secondly an item meant for risky and brave syndies to reveal themselves and essentially take over there department to use it to buy more syndies loot isn't power creep. It's the equivalent of a fluff game option or gimmick. This isn't a code problem bawhoppen. It's a goof problem. A player problem a hop problem and a security problem. On the lack of response to cargo being emagged. If a syndicate making risky moves for a rng reward is power creep. Then emagging the comma console and telling the syndicate/admins as the syndicate "ur mom gay" is about the same level of power creep. I'll say it again. Not a code problem. Just jobs and roles or safety checks. (QM, HOP, Cargos sec office) not being done. Please don't use power creep as an argument or you're being just as bad a meme as goof.

**Comment by Shadowflame909** [comment]
Fuck you can't edit comments on mobile.

**Comment by ExcessiveUseOfCobblestone** [comment]
@Bawhoppen please 36983, I look forward to your edits!

**Comment by Shadowflame909** [comment]
I mean the cmo has to watch over a rogue viro outbreak. Genetics giving the tide hulk. And chemistry blowing themselves up. RD has to watch out for rogue xenobio/an xeno egg spawning in xenobio and toxins flooding plasma into all of science. Also a robotics emag rampage. The hop just has to watch over the occasional null crate cargo takeover. And they get a qm to assist them. I don't think it's power creep I think it's called fairness. I say we should give cargo a bit more danger honestly. The hops just gotta watch ian and watch out for traitorous null crates. That's not much. But there is the occasional bubblegum on the mining shuttle...

**Comment by AlexTheSysop42** [comment]
Colossus crate

**Comment by bgobandit** [comment]
one of my favorite ss13 stories was being the clown and running a clownmart and suddenly getting this influx of syndicate goods and by round's end sitting in a miniature armory (until it got bombed inevitably)

:-1:

**Comment by Shadowflame909** [comment]
Now that I'm less salty and I've thought about this PR. Please close this goof, you agreed that cargo should be more dangerous. But I feel like we shouldn't remove the equivalent of a role restricted item for cargo techs. Instead, why not make it more dangerous? Someone gave an idea that you could spawn some syndicate mobs when a null crate is bought. Why not do that? You try to get a null crate, you can get very easily killed by an elite syndicate mob with a shield and an auto rifle. I like your ideas, just not this one. Let's try to make it more fun to get the spooky loot. Instead of removing the loot altogether. Another idea, if this is possible. Maybe ordering a null crate spawns some syndimobs and after you kill them all then the null crate appears. Just, y'know. Something to avoid removal.

**Comment by KorPhaeron** [comment]
>Cargo should have their own unique end game shit, not piggy backing off of traitors.

So make something cool for them first instead of axing this and leaving a void

>money too easy

would rather you make money more scarce and have things worth buying with it than to remove all the cool things to buy but keep infinite money

**Comment by Bawhoppen** [comment]
Creep is real. SWAT stuff was a little bit creep-ish, but more importantly, it was _cool_, so it was okay anyways.

My problem is this stuff is just way too easy to get. Each traitor round has an emag (which is like 50% of the round chances). Money isn't a problem either.
It also just recycles the existing traitor gear, making it all just seem regular and mundane, where if it were rare, it would be alot more interesting and cool to see and use when you actually got the chance to. 

If we were to fix the cargo-conomy so credits weren't as easy to get, and the add something new in its place (or in addition), then I'd be all for leaving it in.

**Comment by AlexTheSysop42** [comment]
Traitor and traitorchan odds got nerfed recently

**Pull request closed without merging**
