### PR TITLE
BoH bombs now forcefully stun anyone flying when they go off

### PR DESCRIPTION
**Pull request by silicons**
Prevents people from repeatedly bohbombing with angel's wings or flightsuits.

### CODE REVIEW

**Comment by PKPenguin321** [comment]
Maybe a var on chasms to ignore immunities such as flight would be cleaner?

**Comment by Tlaltecuhtli** [comment]
does it prevent TRAIT_STUNIMMUNE flags

**Comment by kevinz000** [comment]
@PKPenguin321 problem with that is people should eb able to fly over after it's already a chasm, so if someone is daring they can still cross
the problem i'm sovling here is people with flight infinitely bombing, maybe I could just make the bomber get stunned? looking for feedback on that.
@Tlaltecuhtli yes, it ignores canstun afaik

**Comment by Ratvar** [comment]
Scientists will fart in xenobio and use reproducing slimerace to BoH

Scientists will make telepad in hole to BoH

Jacob's ladder

**Comment by Spaceinaba** [comment]
just fucking dust anybody who does the bombing itself tbh

**Comment by Wilchenx** [comment]
just revert to old bohbombs

**Comment by Shadowflame909** [comment]
@Ratvar  At least you'll have to get out of the BOH or get gibbed before you can make another one.

**Comment by Grazyn** [comment]
@Ratvar they can just use the thing that prompted the nerf in the first place: autocloning. The nerf really does nothing to prevent the spam, if anything it's now more effective because a singularity could just fuck off in space

**Comment by Ratvar** [comment]
@Grazyn Well, at least alone BoHbomb won't eat whole station and hypothethically won't force shuttlecall

**Comment by ishitbyabullet** [comment]
Just make the BoH bomb kill you so hard that you're gibbed and it is impossible to clone you. Not even autocloning will work.

Only applies to bomber, though.

**Pull request merged**
