### PR TITLE
Makes weak alcohol not kill you

### PR DESCRIPTION
**Pull request by DaedalusGame**
:cl:
balance: changed the formula of liver damage so weak alcohol does barely anything while strong alcohol is still threatening
/:cl:

Closes #36088
Do not speedmerge this ~~I haven't tested this ingame yet, I only made a fancy graph and as we all know by now my graphs are usually not 100% accurate.~~

### CODE REVIEW

**Comment by yorii** [comment]
show us the graph!

**Comment by XDTM** [comment]
I kinda hate exponential formulas, they're complicated to both read and rebalance

**Comment by DaedalusGame** [comment]
ok i did testing ingame (i don't trust my own graphing)
5 bottles of spacebeer, 0.06 damage (basicly neglegible)
1 shot glass of absinthe, ~0 damage (decayed before I could see it)
1 glass of absinthe, ~15 damage
1 bottle of absinthe, ~30 damage
2 bottles of absinthe, deceased (took a lot longer than bacchus blessing)
1 shot glass of bacchus blessing, ~20 damage
1 glass of bacchus blessing, deceased
1 glass of hearty punch, this one is still ongoing because it takes so long to metabolize

**Comment by DaxDupont** [comment]
>water down
>not spike them so spessmen go horizontal

**Comment by DaedalusGame** [comment]
i like this furry guy

**Comment by arsserpentarium** [comment]
I suggest to make liver has stamina.So if you drink something, which can give you liver dmg, at first liver will spend stamina.Which is regenerating with rate, proportional to liver health.
So responsible drinking will not fuck you up.Just will lower amount of toxic abuse, which you can take right now.
I think, booze pwr also should be balanced around about 1.5-2.0 l of vodka.Barely it will kill you, or give permanent dmg.But only strong individuals could take more.

**Comment by yorii** [comment]
>I suggest to make liver has stamina.So if you drink something, which can give you liver dmg, at first liver will spend stamina.Which is regenerating with rate, proportional to liver health.

This is literally what it does right now and has always done. There are no ill effects from liver damage until you reach 0 liver health (or call it stamina if you want). And it regenerates every tick as long as it's still positive.

**Comment by arsserpentarium** [comment]
Difference is simple.
Liver health affects stamina regen rate. 
But liver can be damaged before will die completely.

**Pull request merged**
