### PR TITLE
oranges now have stems and leaves

### PR DESCRIPTION
**Pull request by Fikou**
## About The Pull Request

title

## Why It's Good For The Game

it just doesnt seem right without it...

## Changelog
:cl:
imageadd: oranges now have stems and leaves
/:cl:

### CODE REVIEW

**Comment by Iatots** [comment]
1 Doesn't fit with the other citrus fruits anymore
2 devalues 3d orange

**Comment by trollbreeder** [comment]
Call in optimumtact for orange inspection

**Comment by HomocidlePancakes** [comment]
@optimumtact captain come to dormitory for johnson inspection johnson inspection day WOOP WOOP

**Comment by cacogen** [comment]
i'm no expert but when picking oranges if you take the branch with it you fucked. nice sprite

**Pull request merged**
