### PR TITLE
chanoc - a friendly looking doll

### PR DESCRIPTION
**Pull request by chanoc1**
I added a friendly looking doll that could be used a reward from an away mission.

### CODE REVIEW

**Comment by TechnoAlchemisto** [comment]
WE OUT HERE

**Comment by KorPhaeron** [comment]
No hiding your shame shaps

**Comment by chanoc1** [comment]
GOD FUCKING DAMMNIT I CHOOSED THE WRONG BRANCH

**Comment by TechnoAlchemisto** [comment]
WE ARE THEM BOYS

**Comment by Shapsy** [comment]
I WAS NOT INVOLVED

**Comment by Mtbhoy** [comment]
tfw your meme branch accidentally gets exposed

**Comment by Qbopper** [comment]
holy fuck he pushed it to /tg/ and not the jaykin branch

help

**Comment by chanoc1** [comment]
this needs to fucking die please

**Comment by ike709** [comment]
this is beautiful

**Comment by Mtbhoy** [comment]
memes like this never die

**Comment by Qbopper** [comment]
the worst part of this pr is the tips edit

**Pull request closed without merging**
