### PR TITLE
the glove sounds are now only on some gloves [no gbp]

### PR DESCRIPTION
**Pull request by grungussuss**
## About The Pull Request
mistakes were made
## Why It's Good For The Game
god it's horrible, not only is it happening way too often because it's every glove, but also it doesn't fit any other glove other than insuls really, maybe nitriles but gosh just get rid of it for now, maybe later I will make a better sound for other gloves.
## Changelog
:cl: grungussuss
sound: only insulated,nitrile, enhanced retrieval, latex, boxing, improvised gripper gloves have an equip sound
/:cl:

### CODE REVIEW

**Comment by OuroborusReporter** [comment]
Understandable but sad, it was very fun to dramatically snap on my golden gloves as THE BOXING SYNDIE when fighting security

**Comment by Sadboysuss** [comment]
> Understandable but sad, it was very fun to dramatically snap on my golden gloves as THE BOXING SYNDIE when fighting security

if you have ideas what gloves should keep the sound - shoot

**Comment by Striders13** [comment]
> > Understandable but sad, it was very fun to dramatically snap on my golden gloves as THE BOXING SYNDIE when fighting security
> 
> if you have ideas what gloves should keep the sound - shoot


62cdd786f290433b9ed25154a9a429d7

**Comment by Loafin34** [comment]
nitrile, enhanced retrieval, latex, boxing, improvised gripper gloves, arguably biosuit (doesnt have it yet)

**Comment by Loafin34** [comment]
also krav maga, race gloves, dolphin gloves, and rocket gloves. forgot those. basically all the ones that give you something on equip. not counting north star because they dont look like theyd do that sound

**Comment by Sadboysuss** [comment]
> also krav maga, race gloves, dolphin gloves, and rocket gloves. forgot those. basically all the ones that give you something on equip. not counting north star because they dont look like theyd do that sound

**Pull request merged**
