### PR TITLE
Add auto-deadmin timegate option + pref for admins to ignore cult ghost summon

### PR DESCRIPTION
**Pull request by Ryll-Ryll**
## About The Pull Request
1 config change and 1 preference change:
1. Adds a config option AUTO_DEADMIN_TIMEGATE that, when defined, only enforces config force-deadmins for all roles/sec/command/silicon/antag for the first X seconds in the round. After this time expires, the game will defer to the individual's deadmin settings.
2. Adds a preference for admins to ignore being summoned by cult ghosts, starts disabled by default. Nice for when you're sitting around observing a cultist and don't want to be bugged by them suddenly summoning you!

I'm not 100% with dealing with prefs and configs but stock settings preserve previous functionality and must be manually enabled to have effect. Please look it over and offer advice if changes are needed!

## Why It's Good For The Game
I don't like the auto-deadmin config option being on in the first place since it's annoying to get deadmin'd when I'm testing antag stuff, but I spoke to @Twaticus who indicated they like having it for roundstart, but agreed it was annoying when trying to test stuff later in the round. This is a simple compromise that lets config-controllers still force people to deadmin at the starts of shifts where most of the proscribed roles are assigned, while not bothering other admins who make themselves a blob at the thunderdome an hour in to test something.
As for the cult ghosts, I hate suddenly getting summoned as a cult ghost while I'm adminning, but other people like being able to be summoned while currently admin'd, so pref time.

## Changelog
:cl: Ryll/Shaps
config: Added AUTO_DEADMIN_TIMEGATE which allows config force deadmin settings to only apply for the first X seconds in a round. Starts disabled
admin: New preference to ignore being summoned as a cult ghost while admin'd, starts disabled
/:cl:

### CODE REVIEW

**Comment by Fikou** [comment]
why not make it a pref for all players

**Comment by Niknakflak** [comment]
@Ryll-Ryll 
This time gating thing is weird as fuck.  For what purpose did you opt for this method instead of simply auto deadminning people who join the round through the button or have readied up?

This still potentially still fucks with admins who try to setup stuff before the round starts which I've done on numerous occasions.  Delaying a round to setup some event thing isn't uncommon and this method would either still inconvenience those people or not work at all?

**Comment by Ryll-Ryll** [comment]
Because there's no good way to check if someone got antag through the game normally vs traitor panel without adding checks everywhere and the headmin I spoke to said this might work as a compromise

**Comment by necromanceranne** [comment]
You watch the gamer summon his army, you get drafted into gamer ghost force. That just is what it is.

I kid I find it dumb that it forces orbiting ghosts to be summoned.

**Comment by Coconutwarrior97** [comment]
Looks good 👍

**Comment by Arianya** [comment]
@Fikou Different levels of impact. Admins having it as a pref affects a pretty small proportion of the population of a round, whereas having it as a player config could mean, for example, that everyone turns it on to fuck the cult, and then the ability becomes useless, even incidentally.

**Pull request merged**
