### PR TITLE
All of chaplains outfits have equivalent protection

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
So people can take stuff other than their crusader gear

### CODE REVIEW

**Comment by Zilenan91** [comment]
So his cloth hoodie now protects against swords and toolboxes like full platemail?

**Comment by KorPhaeron** [comment]
yes

**Comment by Zilenan91** [comment]
Ehh it'd be nice if the sprite looked like it had some armoring under it but whatever

**Comment by Incoming5643** [comment]
wouldn't it be easier to go the other way and just say the crusader armor is like larp gear that doesn't offer real protection from swords? The same thing happened to the roman armor in the costume vendor.

**Comment by KorPhaeron** [comment]
@Incoming5643 

Chaplain is gameplay critical against  cult/revenant/hand of god cults, he deserves a little extra protection

**Comment by Zilenan91** [comment]
Wait why does roman armor offer no protection when other jumpsuits in clothing vendors do

**Comment by Incoming5643** [comment]
most chaplains don't really know that though. Game balances has kind of evolved around the notion that the chaplain probably won't actively hunt the cultists.

**Comment by Zilenan91** [comment]
That's because the chaplain has no real way to punish heretics. No electric crosses, no flaming tables to strap them to, and no ritual knives to cleanse them of all their sins (and blood).

**Comment by Supermichael777** [comment]
power-creep intensifies

**Comment by Dorsisdwarf** [comment]
Because "Who cares its barely any armor it wont matter"

apparently.

Also get rid of the edited names/desc. If all chaplain gear is armored, then none needs "armored" stuck to the front.

You dont say "armored bomb suit" or call the HOS hardsuit the "armored hardsuit2

**Comment by Fox-McCloud** [comment]
50% universal melee damage reduction for the Chaplain.

sounds fair...

**Comment by Zilenan91** [comment]
80% it's riot armor

**Comment by Fox-McCloud** [comment]
@Zilenan91 

Armor rebalance was a thing---it's not that anymore.

**Comment by Zilenan91** [comment]
Riot armor still gives 80% melee protection here.

**Comment by KorPhaeron** [comment]
Why are you saying such things when its literally in this commit what the armour values are

**Comment by Zilenan91** [comment]
Wow what the fuck, riot suits/chaplain armor is completely useless at 50%, why are they so low, that does nothing.

**Comment by KorPhaeron** [comment]
>50% less damage, effectively double HP, for zero drawback, is nothing

Well memed

**Comment by Zilenan91** [comment]
Why would you wear riot armor when you could just wear a regular vest and get decent general protection in everything rather than amazing protection in one thing and no protection in any other thing. It's doesn't balance out because regular vests have around 20% melee, and actually not worthless protection versus lasers alongside it. Specialization.

**Comment by Anonus** [comment]
>no slowdown, half melee damage
>THE CRUSADER WE NEED, BUT NOT THE ONE WE WANTED

**Comment by Stenthus** [comment]
does this mean you can loot the chaplains locker for like 4 free riot armors?

i'm not sure if that should be a thing

**Comment by Stenthus** [comment]
also @Zilenan91 50% makes a huge difference

like if you're fighting a stand, or someone with a spear, or a fireaxe, or a chainsaw
the stand in particular may very well be doing 5!!! damage per attack depending on which one it is
the fireaxe would take nine hits to crit
the spear twelve

it's rather difficult to hit someone twelve times without using a stun

**Comment by GunHog** [comment]
Kor was the same person who nerfed most armor to paper in the first place. I cannot find the PR though (https://github.com/tgstation/-tg-station/commit/af89c59ed090c64bcbf57f09456c62778015d0a4). Riot armor is `armor = list(melee = 50, bullet = 10, laser = 10, energy = 10, bomb = 0, bio = 0, rad = 0)`

So the Chaplain does indeed have several suits of riot armor now.

**Comment by tkdrg** [comment]
Seriously, just nerf the crusader armor. HoG is disabled and Cult doesn't care about the Chaplain anymore (just the null rod and nothing else). This just means even more powergamers will pick chaplain for the free armor, which is already awful enough right now.

**Comment by LanCartwright** [comment]
kor why is the armour practically better than the hos armour when defending against assistants.
kor why is the armour practically better than roundstart sec armour

**Comment by Zilenan91** [comment]
Because he nerfed armor values to be really bad.

**Pull request closed without merging**
