### PR TITLE
Remove gender-specific preferences

### PR DESCRIPTION
**Pull request by Mothblocks**
## About The Pull Request
Makes hair (which already was, I think?), underwear, facial hair, and undershirts all available to all genders.

**Random character generation is not changed.** Eventually, I want to remake random characters to look more believable, but that is out of scope.

Approved by @ninjanomnom.

## Why It's Good For The Game
Gender-specific preferences are an outdated trope that make the code harder to work with.

This change is also important as a total makeover of the preferences menu *and* the preference internals are going underway. It is significantly easier to work with when a preference can simply be a list of things you can choose, rather than having to depend on *another* preference to decide what they can show. While I could make this change at that time, it is also important that the new preferences menu keep parity, and avoid bikeshed on a trifling detail.

## Changelog
:cl:
qol: Preferences are no longer dependent on gender.
/:cl:

### CODE REVIEW

**Comment by maxymax13** [comment]
refactor: abolished gender
also noo what will i do without my debug tools spawning neon blue catpeople with random socks and weird facial hair

**Comment by Pumpkinoe** [comment]
This is cool - Nothing like wanting to wear a modest pair of underwear but being gender-locked from doing so.

**Comment by interestingusernam3** [comment]
This exists?

**Comment by optimumtact** [comment]
is that not going to make the lists very large? I would hope we add some kind of categorisation, it's already a pain just to scroll through hairstyles for example.

**Comment by tralezab** [comment]
Since mothblocks is redoing preferences menu I'm sure they have a plan for making the prefs inside good

**Comment by Mothblocks** [comment]
I can't really comment too much about list size other than when I tested this locally, it didn't feel overwhelming or anything.

**Comment by Pumpkinoe** [comment]
List size is hardly much bigger - hair list was already huge

**Comment by SuperNovaa41** [comment]
I'm fairly certain hair was the same across both genders anyways

**Comment by Jack7D1** [comment]
Remove other gender

**Comment by ATH1909** [comment]
> Remove other gender

why

**Comment by maxymax13** [comment]
> Remove other gender

remove other gender? what other gender? female? got it, removing women right away

**Comment by optimumtact** [comment]
please don't be cringe on the repo

**Comment by interestingusernam3** [comment]
youngspessmenchristianassociationstation

**Comment by Iamgoofball** [comment]
i literally made this PR and you guys whined real hard and closed it, what gives?
https://github.com/tgstation/tgstation/pull/40935

**Comment by Mothblocks** [comment]
i didn't change random characters

**Comment by Iamgoofball** [comment]
should just change it, it'll be fine

**Comment by Mothblocks** [comment]
image

**Comment by Swiftfeather** [comment]
As a downstream dev, thank you

**Pull request merged**
