### PR TITLE
The mole counts in the min checks in reactions.dm will now be multiplied by the inverse of the consumption multiplier.

### LINKED ISSUE #61380: Reaction code doesn't use min() properly, leading to weird scaling deadspots in reactions
Alright. So there's this pattern in reaction code

Looks like this

https://github.com/tgstation/tgstation/blob/00154ae89b3c9ecba678d92c7bf9375f3185d660/code/modules/atmospherics/gasmixtures/reactions.dm#L597-L604

We take the minimum of a few values, theoretically because we want the reaction to run with the lowest amount feasible. 
So if there's 20 plasma, 10 o2, and 2 n2, and the reaction takes 4 parts plasma, 2 part o2, and 1 part n2, we'll only end up using  8 plasma, 4 o2, and 2 n2. Since we can't react without the n2 and all.

The if check is there to serve as a backup and prevent negative outputs, theoretically because they wreck havoc, though honestly they don't really, so long as the right bitflag is returned the whole mix is garbage collected anyway. Alright sanity check though. that's fine.

You notice how here, because he removes 5x nob formed from tritium, he includes that in the if check? If you scroll out to the right you'll notice that he multiplies the inputs in the min by the inverse of their scalar. At least that's what we want trying to do, mixed the two up.

You get the picture. The min serves to get the lowest possible amount to remove so the reaction can go through, and the if check serves as a sanity check wrapping around it.

The issue is people have been misusing it, for a good while. (Including in this instance)
They most commonly forget to include the inverse scaling in the min(), which leads to these weird fucked phantom gas minimums that aren't listed anywhere, but still stop the reaction.

See: 
https://github.com/tgstation/tgstation/blob/00154ae89b3c9ecba678d92c7bf9375f3185d660/code/modules/atmospherics/gasmixtures/reactions.dm#L690-L697

They need to be updated to not do this, and use min() properly. It leads to dumb graphs like this https://www.desmos.com/calculator/xufgz8piqw (Healium formation graphed out. p is freon, b is bz. if either are reduced below 0, the reaction stops. If you notice this leads to really strange scaling deadspots, and a lot of frustrating behavior)

Thanks to @GuillaumePrata for bringing this to my attention, love you man.

### PR DESCRIPTION
**Pull request by Pickle-Coding**
## About The Pull Request
The moles in the min checks in reactions.dm will be multiplied by the inverse of the consumption multiplier. This will allow reactions to fully react when it has available gasses. It also makes some of the code easier to read.

## Why It's Good For The Game
Closes #61380

## Changelog

:cl:
fix: Reactions will now properly fully react when it has moles to consume. Instead of the reaction stopping when one of the gasses is lower than reaction rate, it will instead adjust the reaction rate so that it consumes all of the gas.
/:cl:

### CODE REVIEW

**Comment by tralezab** [comment]
it's not a matter of if someone will ask you to change your name, it's a matter of when

**Comment by LemonInTheDark** [comment]
@170141183460469231731687303715884105727 change your name please. I know it's you, but you really do just look like a bot account

**Comment by 170141183460469231731687303715884105727** [comment]
Test.

**Comment by 170141183460469231731687303715884105727** [comment]
@LemonInTheDark how do I change my name?

**Comment by LemonInTheDark** [comment]
Wonderful thank you

**Comment by LemonInTheDark** [comment]
@Pickle-Coding I remember you mentioning using defines here so things are more clear, it'd be nice if the names aren't too long, thoughts?

**Comment by Pickle-Coding** [comment]
@LemonInTheDark I haven't thought of a concise way to name them all. Is it possible to define a list with defines in it?

**Comment by LemonInTheDark** [comment]
What you could do is make a define called INVERSE() that inverts its input or something, that way we don't need 2 defines per reactant scaling

**Comment by duncathan** [comment]
:+1:

**Comment by LemonInTheDark** [comment]
This is maybe a halfstep. it solves the key problem at least. defines would be nice here, but I have a feeling they'd clutter stuff too much to be sane

**Comment by LemonInTheDark** [comment]
Might want to make the cl a bit longer though, emphasize that reactions have changed, it'll make the atmos nerds happy cause they'll need to relearn their optimal setups

**Comment by Pickle-Coding** [comment]
Updated changelog.

**Pull request merged**
