### PR TITLE
Removes grab from foamed metal

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
I couldn't think of a way to replace this functionality but I doubt anyone uses it anyway

### CODE REVIEW

**Comment by ChangelingRain** [comment]
pfffhahaha I want this to stay in some form holy shit

**Comment by KazeEspada** [comment]
click drag

**Comment by PKPenguin321** [comment]
click dragging yourself onto foam is the most unintuitive thing i've ever heard aside from grabbing foam

**Comment by duncathan** [comment]
This exists?

**Pull request merged**
