### PR TITLE
Nerfs bluespace launchpads by making them more obvious and nerfing the range.

### PR DESCRIPTION
**Pull request by Watermelon914**
## About The Pull Request

Bluespace launchpad maximum range decreased from 60 to 40. Traitor launchpad unaffected.
Bluespace launchpads will now give a visual indication of the turf they are teleporting to/teleporting from as well as a noise notification. Does not apply to traitor launchpads.
Bluespace launchpads will now show a beam that fades out between the target turf and the launchpad after it has done the teleportation. Again, does not apply to traitor launchpads.

https://user-images.githubusercontent.com/37270891/136650247-1d08bfb5-cdf9-4a7e-991b-d648b8943b68.mp4

## Why It's Good For The Game

Bluespace launchpads are a bit too strong right now, especially now that you can teleport people with circuit guns without them knowing they're about to be teleported and no one having any clue where they're teleported. This nerfs that by making it more obvious where someone has teleported off to. Also just decreases the maximum range because a 60 range telescience pad is actually a 120*120 box because it can go to -60 too.

## Changelog

:cl:
balance: Bluespace launchpad maximum range decreased from 60 to 40. Traitor launchpad unaffected.
balance: Bluespace launchpads will now give a visual indication of the turf they are teleporting to/teleporting from as well as a noise notification. Does not apply to traitor launchpads.
balance: Bluespace launchpads will now show a beam that fades out between the target turf and the launchpad after it has done the teleportation. Again, does not apply to traitor launchpads.
/:cl:

### CODE REVIEW

**Comment by tralezab** [comment]
nerf: they look pretty as shit now

**Comment by LemonInTheDark** [comment]
is it just me or does your video not have any effects in it

**Comment by Watermelon914** [comment]
> is it just me or does your video not have any effects in it

might just be you

**Comment by Blevruz** [comment]
its gonna effectively destroy the whole "pull people by surprise" thing which is a shame
the particles before the pull look nice though
if you spam enough the whole station will be covered in the streaks so im not sure they're a great idea

**Comment by zxaber** [comment]
Not really a fan of the "Thor's Delivery Service" effect, but that's a pretty bikeshedy thing to get get hung up on.

**Comment by Watermelon914** [comment]
> its gonna effectively destroy the whole "pull people by surprise" thing which is a shame the particles before the pull look nice though if you spam enough the whole station will be covered in the streaks so im not sure they're a great idea

can't spam because it has a delay before teleporting.

> Make so it only affects circuits + launchpad, cos its a main reason of nerf.

no

**Comment by Blevruz** [comment]
> 
> 
> > its gonna effectively destroy the whole "pull people by surprise" thing which is a shame the particles before the pull look nice though if you spam enough the whole station will be covered in the streaks so im not sure they're a great idea
> 
> can't spam because it has a delay before teleporting.
> 
you can use multiple

**Review by Mothblocks — CHANGES_REQUESTED** [review]

**Comment by LemonInTheDark** [comment]
> its gonna effectively destroy the whole "pull people by surprise" thing which is a shame

Isn't this the point?

**Comment by Blevruz** [comment]
> 
> 
> > its gonna effectively destroy the whole "pull people by surprise" thing which is a shame
> 
> Isn't this the point?

these two statements are not mutually exclusive

**Review by Mothblocks — APPROVED** [review]

**Comment by Krysonism** [comment]
Finally a machine people actually think is worth building and it gets triple dip nerfed...

**Comment by moocowswag** [comment]
I think untrace-able is alittle too strong of a statement, the ai, the rd, engie borgs, and literally anyone wearing a diagnostic headset can see where the launchpad is targeting you can easily pinpoint the general location of the launchpad (especially as ai since they have the most info to work with)

**Comment by moocowswag** [comment]
> Make so it only affects circuits + launchpad, cos its a main reason of nerf.

Its not actually being nerfed because of circuits.

The vast majority of players that use launchpads simply use it with a diagnostic headset and camera console in order to manually and remotely teleport their prize/victims, its much simpler and easier than setting up a circuit launchpad.

**Comment by Blevruz** [comment]
> As an alternative suggestion, why not make the delay longer so it's harder to use against players? Also, the line is outright silly.
More delay wouldn't change much, as it stands getting someone who's moving is already mostly chance. 
It also wouldn't give people a chance to fight back agains the grinder strat, as you can just put the launchpad on a conveyor belt next to a grinder to give the victim no time to react if they're pulled by surprise.

**Comment by Gurkenglas** [comment]
I would like the sort of rebalancing that makes people use drones instead of launchpads at least some of the time. As it stands, launchpads even require less research.

**Pull request merged**
