### PR TITLE
Changed chemical heater and smoke machine sprites

### PR DESCRIPTION
**Pull request by nicbn**
[Changelogs]:
:cl: nicbn
imageadd: Chemical heater and smoke machine resprited.
/:cl:

31799000-2fb90224-b516-11e7-8186-2413dfc41b66

### CODE REVIEW

**Comment by praisenarsie** [comment]
improve the fan @nicbn fun fact the smoke machine is literally the cool/hot loop of the Thermo-Electric Generator sprite

**Comment by nicbn** [comment]
It's not a fan it's a centrifugue

**Comment by nicbn** [comment]
Does this look better?

image

**Comment by Iamgoofball** [comment]
the heater is good, i like it

**Comment by kilkun** [comment]
nah, it's still facing the camera. make it tilted downwards slightly.

**Comment by WJohn** [comment]
These don't look any different from your other PR. I'd like to see the chem heater improved a bit more. And it'll definitely be good enough to go in.

Smoke gen is an improvement over what we have in game but it still looks like ye-olde TEG or the turbine and that's not appealing in the slightest. Needs a complete remake, or a very significant upgrade over what you have now.

**Comment by nicbn** [comment]
I have no ideas on how to do so, sorry.

**Comment by KorPhaeron** [comment]
>Smoke gen is an improvement over what we have in game

Sounds like a yes

**Pull request merged**
