### PR TITLE
fixes clockcults appearing as grey box on sechuds until they reequip their id

### LINKED ISSUE #32117: clock cult IDs out you
they come up as a grey box instead of proper assistant assignment so you can pretty much tell who's cult by the irregular ID

### PR DESCRIPTION
**Pull request by silicons**
@YakumoChen 
fixes #32117

### CODE REVIEW

**Comment by Arianya** [comment]
I vaguely recall @Xhuis saying this was intentional. Well, the grey box part, not the re-equipped ID part.

I might be wrong though!

**Comment by Xhuis** [comment]
This is actually intentional as a way to distinguish servants, yes. I'm okay with this being added, but it would be a balance change, not a fix.

**Comment by kevinz000** [comment]
@Xhuis it becomes normal if you reequip

**Comment by Xhuis** [comment]
Then *that's* a bug!

**Comment by Supermichael777** [comment]
its generated on equip as part of adding hud elements. Its purely based on a hard coded job name list

**Comment by Supermichael777** [comment]
It needs a Rework

I would suggest that it be set at the id console as part of role assignment. Then the custom name doesn't affect it. Add another popup in the fake id to set it.

**Review by Cyberboss — APPROVED** [review]

**Comment by Cyberboss** [comment]
This does need a rework, but I'm going to merge this pure so that it's consistent for now

**Comment by Xhuis** [comment]
Works for me, I suppose

**Pull request merged**
