### PR TITLE
new coat of paint: colored jumpsuits

### PR DESCRIPTION
**Pull request by dannno**
:cl: Dannno
tweak: We've switched to a new brand of colored jumpsuit.
/:cl:

Testing the waters of redoing the game in a consistent palette.

I dunno. Might be too big of a task. 
How it goes from here will depend on if people like it and want it or not.
@WJohn is art director or something right?
Please review

### CODE REVIEW

**Comment by PKPenguin321** [comment]
Fine with all of these (love the new red) but leave grey alone, it's color is legacy

**Comment by Thunder12345** [comment]
Pink and purple looks like a bit too much contrast, imo

**Comment by Nienhaus** [comment]
Looks great.

**Comment by Thunder12345** [comment]
Shame it doesn't compile...

**Comment by dannno** [comment]
wtf it compiled for me

**Comment by Thunder12345** [comment]
Check ALL the maps

**Comment by dannno** [comment]
and if I leave the grey alone it kind of goes against the whole point
I understand what you mean though
maybe I'll add an "old grey jumpsuit" or something

**Comment by Thunder12345** [comment]
One of the removed paths might be in another map

**Comment by dannno** [comment]
i'm allergic to going near maps

**Comment by ChangelingRain** [comment]
Yeah the pink and purple bright shades contrast too much with the next lowest shade.

**Comment by dannno** [comment]
changed pink and purp


I loaded all maps and there were no problems. I dunno.

**Comment by JJRcop** [comment]
_maps/RandomZLevels/Academy.dmm:2861:error: undefined type: /obj/item/clothing/under/color/purple

turns out it was a lootspace place place

**Comment by WJohn** [comment]
I approve. This art palette is superior to mine.

**Comment by dannno** [comment]
if you really think so
something is still bothering me about it
I've never fucked with maps out of fear so I dunno what to do about this academy shit

**Comment by Jordie0608** [comment]
Open `_maps/RandomZLevels/Academy.dmm` in a text editor, go to line 2861 and replace `/obj/item/clothing/under/color/purple` with `/obj/item/clothing/under/color/lightpurple`

**Comment by chanoc1** [comment]
looks nice, but i thought we should be using wjs palette? im still confused on the whole thing

**Comment by Incoming5643** [comment]
It's a bit too vibrant for my tastes

**Comment by Supermichael777** [comment]
hands are rendered in layers the cutouts should be unnecessary now.

**Comment by RemieRichards** [comment]
@Supermichael777 wrong, still necessary

**Comment by dannno** [comment]
@chanoc1 There isn't any obligation (yet) to use any specific palette. Wjohn's palette and mine are both attempts at making a palette that could be reasonably enforced on the game.

**Comment by chanoc1** [comment]
@danno tbh i like your palette more, i feel like the colors are better suited for pixel art

**Comment by Niknakflak** [comment]
Some of the jumpsuits look great in the new pallet, others look garbage.
I never understood the need to have a pallet anyway and it discourages new spriters anyway.

**Comment by chanoc1** [comment]
a pallete helps to unify all the art, and in the case of me ( a new spriter), I like having the palette, as it makes coloring easy, as there are already colors that look good chosen

**Comment by Supermichael777** [comment]
why are hands rendered under cloths it looks so trash reeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee

**Comment by RemieRichards** [comment]
>looks so trash
>literally wasn't noticeable until dismemberment, and even then, still isn't that noticeable

**Comment by TrustyGun** [comment]
The pink and purple suits still need some work done to them. There is too much contrast

**Comment by dannno** [comment]
@Niknakflak If you could specify which ones you don't like, that would actually be useful.
A palette shouldn't discourage new spriters, it should only encourage more consistent sprites.
I doubt anyone that wants to contribute is going to go "Oh, you want me to use THESE colors? That's it, I'm OUT."

**Comment by KorPhaeron** [comment]
Art man said yes someone should probably revert the grey though because I hate change

**Comment by chanoc1** [comment]
nice

**Comment by dannno** [comment]
fck i'm going to eventually make a manual revert for this, since the idea was that it would be followed by more recolors, but since the palette isn't really at a good enough place to be workable the old uniforms should be returned
but i can't revert it with the revert button because changes have been made to the thing since then so it might be a while before i muster up the energy

**Pull request merged**
