### PR TITLE
Removes beachtongue

### PR DESCRIPTION
**Pull request by tortellinitony**
:cl: Tortellini Tony
del: Removed Beachtongue
/:cl:

Doesn't work. Nobody knows it exists, anyway.

### CODE REVIEW

**Comment by DoctoreMad** [comment]
I think I remember stranded people on mining beach's ruin getting ONLY this tongue you're removing. Are you giving them galactic common back?

**Comment by tortellinitony** [comment]
the mutation did that so yes

**Comment by FantasticFwoosh** [comment]
Its supposed to activate on stoners on the station, can't say i've seen that happen either.

**Comment by Cyberboss** [comment]
I'd rather see this fixed than removed tbh

**Comment by Anonmare** [comment]
I've gotten stoned and had it as my language but everytime I tried to speak it - I could only spam common with empty text that didn't even display my name.

**Comment by Fox-McCloud** [comment]
are you *sure* this is broken?

**Pull request closed without merging**
