### PR TITLE
Tape recorder revamp (TG edition)

### PR DESCRIPTION
**Pull request by Hopekz**
Yogstation closed this for some dumb reason so TG gets it instead.
Re-publishes my original under yogstation13/Yogstation#8446

Old way
---------
(Old way still works):
0YXgVcMNdv

New way:
------

**Context-sensitive buttons!**

WJBmNrbmGs

**While recording:**
image

**while playing:**
image

**And you can also alt-click a tape recorder to play it like in** yogstation13/Yogstation#8445
UEl2rkUv3y

## Changelog
:cl: Hopek
add: Tape recorder has been reworked.
/:cl:

### CODE REVIEW

**Comment by Doosteroni** [comment]
Yogstation closed this sexy shit because it was “stale?” What nerds. This looks super sweet my man!

**Comment by optimumtact** [comment]
there's a request for review from their developer that you just ignored?

**Comment by Jared-Fogle** [comment]
:+1: Kill all verbs

**Comment by Hopekz** [comment]
> there's a request for review from their developer that you just ignored?

Webp net-resizeimage (2)

**Comment by Tharcoonvagh** [comment]
add :clap: a :clap: replay :clap: button :clap: PLEASE :clap:

**Comment by Hopekz** [comment]
> add 👏 a 👏 replay 👏 button 👏 PLEASE 👏

the 👏 recording 👏 already 👏 replays 👏 when 👏 you 👏 hit 👏 play 👏

**Comment by wesoda25** [comment]
record button should be a bit more circular imo

**Pull request merged**
