### PR TITLE
Humans (and human based species) with tails surgically implanted can now wag them...

### PR DESCRIPTION
**Pull request by SuperNovaa41**
## About The Pull Request
allows any human based species to wag their tail...

## Why It's Good For The Game

image

## Changelog

:cl:
fix: All human based species can now wag their tails...
/:cl:

### CODE REVIEW

**Comment by optimumtact** [comment]
I don't agree with this, you require specialised muscles to wag, that are not present in non tail having species.

**Comment by optimumtact** [comment]
24 hours

**Comment by tralezab** [comment]
I vote to merge this instead

**Comment by optimumtact** [comment]
I'll allow this if you add a surgery for implanting and artificial muscle items that require research and creation.

**Comment by SuperNovaa41** [comment]
> I don't agree with this, you require specialised muscles to wag, that are not present in non tail having species.

**Comment by optimumtact** [comment]
ok

**Pull request closed without merging**
