### PR TITLE
Converts Gasmasks To GAGS

### PR DESCRIPTION
**Pull request by unit0016**
## About The Pull Request
What it says on the tin. This converts all of the gasmasks (Gasmask, Atmos Gasmask, Captain Gasmask, Centcom Gasmask*) To GAGS. ~~Had to crashcourse this, the HackMD document was the literal only thing saving me here~~

*CentCom gasmask also no longer is a big error when worn too.
image

## Why It's Good For The Game
We will kill all recolors. Slowly. Brutally. They will rue the day they were added to each and every .dmi in this gotdamn repo.

## Changelog

:cl:
fix: The CentCom gasmask is no longer a missing texture. Oopsies!
imageadd: Gasmasks have been converted to GAGS! Ask god to recolor yours today!
/:cl:

### CODE REVIEW

**Comment by unit0016** [comment]
Ah shit, welding gasmask is causing problems. Guess we going draft mode until I come back to that

**Comment by unit0016** [comment]
had to brute force it but hey it's better than nothing

**Comment by unit0016** [comment]
alright, tests aren't failing anymore. the way I've gone about this is stupid but oh well.

**Comment by Serxule** [comment]
they look really dim imo

**Comment by unit0016** [comment]
> they look really dim imo, also, what the hell is that syndi gasmask, i've never seen that

Did my best to pick the colors out so they'd be the correct shade but they're not exact

That's a demonstration of admin colors working and isn't actually in-game

**Comment by SkeletalElite** [comment]
the caps mask eye color seems a little too dark. The eyes kind of blend in with the resk of the mask.

**Comment by unit0016** [comment]
It's come to my attention the chameleon gasmask might look scuffed in it's current state so give me a bit for that

**Comment by unit0016** [comment]
It has come to my attention that this is implemented horribly and as amusing as that is I should route back to it some other time

**Pull request closed without merging**
