### PR TITLE
Adds the detective wardrobe

### PR DESCRIPTION
**Pull request by SomeoneYouProbablyKnow**
## About The Pull Request
This adds a det wardrobe vendor and puts it in the det office on Box Meta Delta and Pubby. Not kilo (which is out of rotation) and not donut (because the people have spoken).
The vendor itself has all clothing items from the det locker and a few extra like latex gloves and det flasks. Basically, I think if det gets to have extra outfits they shouldn't be clogging his equipment locker.

## Why It's Good For The Game
It’s a QoL change for the det round start routine. The only problem is that a mechanical vendor arguably clashes with the det office aesthetic. I don’t think that’s the case but here are the pictures from Delta and Pubby with said vendor.
Detoffice

## Changelog
:cl:
add: The detective now has all his extra clothes in a vendor and not their locker.
/:cl:

### CODE REVIEW

**Comment by ATH1909** [comment]
You might wanna check out this PR: https://github.com/TheSwain/Fulpstation/pull/319

**Comment by SomeoneYouProbablyKnow** [comment]
@ATH1909 i think moving all det things into one vendor kinda defeats its purpose. A clothes vendor is a step you can ignore if you don't want RP clothes. We do have a sec-drobe and a sec gear vendor

**Comment by Pugie** [comment]
Machine typod as "mechine" in the vendor description.

**Comment by Farquaar** [comment]
It's been a long time coming. Nice.

**Review by Twaticus — CHANGES_REQUESTED** [review]
not a huge fan of the matchy-matchy brown. i think the lawdrobe/curadrobe base with red stripes would fit well 

quick mockup
dreammaker_ykLNWhfclX

**Comment by Rohesie** [comment]
What about Donut and Kilo?

**Comment by SomeoneYouProbablyKnow** [comment]
@Rohesie Well i can add them but Kilo is out of rotation and donut is getting delted at the end of the mounth last time i heard.

**Comment by Rohesie** [comment]
Neither have been removed yet.

**Comment by SomeoneYouProbablyKnow** [comment]
That's fair. I'm gonna add them today then

**Review by spookydonut — CHANGES_REQUESTED** [review]
Pending change requests

**Comment by Rohesie** [comment]
Up to Twaticus now.

**Review by Twaticus — APPROVED** [review]

**Pull request merged**
