### PR TITLE
Adds aux mining base.

### PR DESCRIPTION
**Pull request by WJohn**
Remake of #19752 

:cl: WJohnston
add: Metastation and Boxstation now boast auxillary mining construction rooms in arrivals. These allow you to build a base and then launch it to wherever you want on lavaland.
/:cl:

### CODE REVIEW

**Comment by PKPenguin321** [comment]
still ugly

**Comment by Repukan** [comment]
It'll be fun to drag megafauna to the landing area

**Comment by Fox-McCloud** [comment]
Pleases don't reduce the pod count at arrivals from 2 to 1.

**Comment by GunHog** [comment]
> Pleases don't reduce the pod count at arrivals from 2 to 1.

The second pod has been moved, but there are still two!

image

**Comment by Fox-McCloud** [comment]
Thank you, @GunHog. Much appreciated.

Still think this does look kinda ugly though...

**Comment by Niknakflak** [comment]
Still ugly
Still tumor

**Comment by MMMiracles** [comment]
I don't think its actually possible to make a giant empty box that exists solely for building shit in any prettier.

**Comment by PKPenguin321** [comment]
you could make it way smaller for one, like R&D lab sized

**Comment by WJohn** [comment]
9x9 is already pretty damn tiny. You get, at most, 7x7 of interior room if you cover all the outside with walls. That's really not very much.

**Comment by Jalleo** [comment]
@PKPenguin any smaller and it wont work you have to make walls for the base inside that area.

**Comment by PKPenguin321** [comment]
Oh well that's dumb

**Comment by Core0verload** [comment]
I said it twice, and I'll say it again.

# Make it into a fucking area in fucking space.

It would make it less of a tumor, that's for sure.

**Comment by WJohn** [comment]
Not really no, also you'd have to deal with airlessness when trying to set it up which would make building it a huge pain. You still also have to deal with the limited box-shaped area, so that'll need to be outlined by grilles or a wall or something and then we're back at the box-tumor.

**Comment by Core0verload** [comment]
Use "warning strip" tiles at corner and make a small room with APC, SMES, power generator, air cans and launch console in center or close to side.

**Pull request merged**
