### PR TITLE
nerfs rodform

### PR DESCRIPTION
**Pull request by LanCartwright**
:cl: 
tweak: Rod form now costs 3 points (up from 2)
tweak: Rod form cooldown increased to 450 and 180 from 250 and 100
/:cl:

### CODE REVIEW

**Comment by YakumoChen** [comment]
It's already 3 points??????

**Comment by LanCartwright** [comment]
my bad. I made this during the freeze.

**Comment by KorPhaeron** [comment]
Yeah we just nerfed this a week ago

**Comment by LanCartwright** [comment]
do you think it needs an increase to cooldown kor, or we leave it at that?

**Comment by KorPhaeron** [comment]
I think we should wait and see if its still taken by every wizard and then decide what to do next

**Pull request closed without merging**
