### PR TITLE
Mining skill affects PKA again but only when used on rocks.

### PR DESCRIPTION
**Pull request by ghost**
:cl: Qustinnus
 add: PKA now gets exp and benefits of/for the mining skill again
/:cl:

this time no more ebow madness.

### CODE REVIEW

**Comment by Tlaltecuhtli** [comment]
why wouldnt using it on assistants give you more xp?

**Comment by ATH1909** [comment]
Can mining ore with a PKA give you EXP now?

**Comment by Qustinnus** [comment]
yes

**Comment by Rohesie** [comment]
Is this tested?

**Comment by Qustinnus** [comment]
yes but i forgot a push so dont merge this yet

**Comment by Qustinnus** [comment]
wouldve been very embarrasing otherwise

**Pull request merged**
