### PR TITLE
Explosive implant action button can always be activated

### PR DESCRIPTION
**Pull request by coiax**
:cl: coiax
add: Explosive implants can always be triggered via action button, even
if unconscious.
/:cl:

Makes it easier for newer players, who may not be aware of deathgasping
or whispering in crit.

### CODE REVIEW

**Comment by Cyberboss** [comment]
Where was the old button defined?

**Comment by AnturK** [comment]
While you're touching this fix, spamming the button to get multiple activation messages.

**Comment by RemieRichards** [comment]
@Cyberboss it wasn't, it just used the base ```item_action```

**Comment by kevinz000** [comment]
Wtf coiax I used this to strip ops by leaving them unconscious out of CRIT.

**Pull request merged**
