### PR TITLE
Adds ignored commit file for git blame

### PR DESCRIPTION
**Pull request by kriskog**
## About The Pull Request
Currently added the line ending PR. 

To setup your git to run this file for the tgstation project, navigate to the folder and run 'git config blame.ignoreRevsFile .git-blame-ignore-revs'

Makes use of blame --ignore-rev
https://git-scm.com/docs/git-blame

### CODE REVIEW

**Review by Cyberboss — DISMISSED** [review]

**Comment by Cyberboss** [comment]
Can you put that note about the git config in CONTRIBUTING.md please

**Comment by kriskog** [comment]
Sure. Whats a fitting place for it?

**Comment by Cyberboss** [comment]
I'd say wherever the notes about initial cloning/setting up map merge are

**Comment by kriskog** [comment]
Our git setup directions are embarrasing, and doesnt even really cover commandline: https://tgstation13.org/wiki/Setting_up_git
We should look into stealing the one TGMC has, but also do a cli guide so people are easier to help. This would fit there, but I cant really see a good place to put it - especially given we dont even recommend using our own git guide.

**Comment by Cyberboss** [comment]
Yeah, you're right. We really shouldn't be citing the wiki in our
development docs either. No reason it can't ask be contained in MD files.

For now, just put it _somewhere_ and we can look into making a better guide
in the future.

**Comment by kriskog** [comment]
Done

**Pull request merged**
