### PR TITLE
Fixes #25961 [Slice Names]

### LINKED ISSUE #25961: Slicing named custom pizzas loses the specified name
Name a custom pizza with a pen, slice it, receive item called custom pizza slice

Haven't tested other custom sliceables, which I think is only bread.

### PR DESCRIPTION
**Pull request by ExcessiveUseOfCobblestone**
Fixes #25961

### CODE REVIEW

**Comment by QualityVan** [comment]
Custom food can have custom descs as well, although I'm not sure if you'd want those to copy directly or what.

**Comment by ExcessiveUseOfCobblestone** [comment]
I have a feeling this is overwriting things so I'll probably have to do some sleuthing after class.

**Comment by ExcessiveUseOfCobblestone** [comment]
Yeah this is going to overwrite some of the default slice names and/or desc so ima have to do some magic

**Comment by PKPenguin321** [comment]
Why do you always use [[[brackets]]]

**Comment by ExcessiveUseOfCobblestone** [comment]
you can never have too many [brackets]

**Pull request merged**
