### PR TITLE
The honorbound trauma now makes use of the relay_attackers element.

### LINKED ISSUE #75904: Honorbound Chaplain strikes again (or rather, they don't strike at all)
## Reproduction: Be a chaplain, foolishly assume Honorbound works well enough to try and gimmick around it. Get attacked by a space carp during a carp swarm, and find yourself unable to defend yourself from the _fish that is actively biting you._

This also happened this round with a blood spider, which is by its very nature even less innocent than the carp.

I didn't get into any fights with humans in this round, unfortunately, so i'm just assuming it's a mob-based bug until it's revealed otherwise.

### PR DESCRIPTION
**Pull request by Ghommie**
## About The Pull Request
Whoever made the relay_attackers element, thank you for streamlining the bucketload of signals that had to be registered for everything that counted as an attack. It's very much needed.

Beside, I only had to add a few flags to be sent by the ATOM_WAS_ATTACKED signal, so that stamina and shoving doesn't automatically make the attacker guilty.

Oh, one more thing I have forgot to mention. Currently medical staff is immune to "guilt" altogether, while the comments suggest they should be affected by declaration but not attacking. This PR also covers that issue.

## Why It's Good For The Game
This will fix #75904.

## Changelog

:cl:
fix: Fixed the honourbound trauma not reacting to attacks from basic mobs
fix: Fixed the "Declare Evil" spell not working against the medical department.
/:cl:

### CODE REVIEW

**Comment by ATH1909** [comment]
Wait, why _shouldn't_ stamina damage and shoving mark an attacker as being guilty?

**Comment by Ghommie** [comment]
> Wait, why _shouldn't_ stamina damage and shoving mark an attacker as being guilty?

That's how it used to work. This is not a balance PR.

**Comment by Helg2** [comment]
Can you also check if it works on humans properly, because i tested it and was able to attack them, maybe it's just me, dunno.

**Comment by Ghommie** [comment]
Oh, then that's definitely an issue with the ClickOn proc honourbound uses!

**Pull request merged**
