### PR TITLE
Ripleys can no longer gib people

### PR DESCRIPTION
**Pull request by ghost**
wtf this is op

:cl: More Robust Than You
tweak: Ripleys can no longer gib people
/:cl:

[why]: # (Please add a short description [two lines down] of why you think these changes would benefit the game. If you can't justify it in words, it might not be worth adding.)

### CODE REVIEW

**Comment by kevinz000** [comment]
u ded son?

**Comment by Grazyn** [comment]
I checked recent round logs but I can't find instances of a ripley gibbing someone, I guess it must be current round. IC in PR

**Comment by MoreRobustThanYou** [comment]
naaa different server

**Comment by MoreRobustThanYou** [comment]
and btw i dont think ripleys log the fact that they gib

**Comment by Grazyn** [comment]
also what's with a coder saying "wtf is this" to something that has been there since Ripleys were added, it's almost like they never play

**Comment by kevinz000** [comment]
go change it on hippie if you're so salty dont change tg

**Comment by vuonojenmustaturska** [comment]
who the fuck uses ripleys

**Comment by Bawhoppen** [comment]
@vuonojenmustaturska They're the new meta

**Comment by SgtxRootbeer** [comment]
I do, and I like having an option of gibbing lings without having to drag them to the destroyed gibber/crematorium

**Comment by GuyonBroadway** [comment]
Potassium+water grenades, those are good because they actually HAVE logging.

**Comment by davethwave** [comment]
Instead of getting rid of gibbing just have the gibs contain the blood of their victims so you can at least 
be turned into a podperson, or at least make it so that if you decapitate a limb the limbs have actual blood in them from the victim.

**Comment by Armhulen** [comment]
or just add logging you numb nuts

**Comment by Armhulen** [comment]
https://github.com/HippieStation/HippieStation/pull/4252
there now go away

**Comment by Iamgoofball** [comment]
this is literally the most UP mech in the game and you're nerfing it?

**Comment by KorPhaeron** [comment]
Balance change with no justification in OP

**Pull request closed without merging**
