### PR TITLE
Fixes supply talisman spam

### PR DESCRIPTION
**Pull request by ChangelingRain**

### CODE REVIEW

**Comment by Robustin** [comment]
Should've stuck with RobustinCode(tm)!

**Comment by ChangelingRain** [comment]
This is RobustinCode(:tm:)

**Comment by Robustin** [comment]
Nah I didn't add supplytalisman/weak to the game, don't you pin this on me.

**Comment by coiax** [comment]
> Success has a thousand parents, but failure is an orphan.

**Comment by KorPhaeron** [comment]
Blacklists are disgusting

**Pull request merged**
