### PR TITLE
Better Chat Squashing

### PR DESCRIPTION
**Pull request by ghost**
No increasing the size of font with combined messages, it's obnoxious and chat squashing should be for less spam not more

### CODE REVIEW

**Comment by praisenarsie** [comment]
i'd prefer if ours was similar to goon's

**Comment by LetterN** [comment]
# OOC:letter_N: we dont want this big text happening x40

**Comment by JJRcop** [comment]
Downvoting for a similar reason to https://github.com/tgstation/tgstation/pull/32654#issuecomment-343775136

**Comment by Potato-Masher** [comment]
Drat, there goes the People's Megaphone.

**Review by Cyberboss — APPROVED** [review]

**Comment by Bawhoppen** [comment]
I liked it getting bigger though

**Comment by Tayyyyyyy** [comment]
Not to mention that the bigger text font size was hardcoded, so if your font size was set big enough, it wouldn't actually grow in size.

**Comment by uraniummeltdown** [comment]
@praisenarsie I have looked everywhere but can't find Goon's code for this, it's definitely in the 2016 release somewhere though

**Comment by Buggy123** [comment]
I like the growing text functionality as well tbh, serves to give it emphasis and almost no one does the
SPAM x8 thing anymore.

**Comment by praisenarsie** [comment]
@uraniummeltdown that's because it isn't in the goonstation2016 codebase, they added it as a feature in late 2017 and we copied them.

**Comment by uraniummeltdown** [comment]
@praisenarsie It is in goon2016
Compile it and play it for yourself, the chat squash thing is in there

**Pull request merged**
