### PR TITLE
Adds a new bar sign - The Lightbulb

### PR DESCRIPTION
**Pull request by ghost**
:cl: Xhuis
add: Added a new bar sign, The Lightbulb.
/:cl:

Someone in Discord gave me this idea when we were discussing moths, so I added a moth-themed bar sign. It looks like this, though the in-game version is slightly different and animates better.

The Lightbulb

The square at the top represents a common light fixture, with the blobs of fluttering light being cute fuzzy moffs flying around it.

### CODE REVIEW

**Comment by Qustinnus** [comment]
too soon

**Comment by Qustinnus** [comment]
can we have the kiki yaya cocktail bar too

**Comment by Xhuis** [comment]
is it ever too soon for moffs

**Comment by ShizCalev** [comment]
Whoops. How did this get in my 24 hours tabs

**Comment by ShizCalev** [comment]
@Xhuis Reopen this, sorry. :(

**Pull request merged**
