### PR TITLE
[READY]Fixes Peacekeeper Cyborg Chemicals

### PR DESCRIPTION
**Pull request by silicons**
The effects were running out for confusion toxin before it applied them again.
This should fix it, unless I fucked up the Clamp()s in which case please tell me.
I'm assuming Clamp is var = Clamp(value, min, max) 
PREVENTS STAMINATOXIN FROM STUNLOCKING
Weakens stamina toxin by a tiny bit.
:cl: Mekhi
tweak: Peacekeeper Cyborg Confusion Injectors now work properly.
tweak: Peacekeeper Cyborg Stamina Toxin are now completely unable to stun you. It is also just a tad bit weaker.
\:cl:

### CODE REVIEW

**Comment by kevinz000** [comment]
Actually I'm going to pack in a fix for harm alarms not making their noise when emagged.

**Comment by kevinz000** [comment]
ALSO FIXING STAMINA TOXIN STUNLOCKING PEOPLE WITH MORE THAN 50 DAMAGE, NEEDS TESTING TO SEE IF MY MATH IS SHIT OR NOT

**Comment by AnturK** [comment]
Use adjust_x procs for these ? And if they don't exist for confused/dizzy add them. Consistency is good.

**Comment by optimumtact** [comment]
are you going to test this at any point

**Comment by kevinz000** [comment]
Tested

**Pull request merged**
