### PR TITLE
Adds antag.log

### PR DESCRIPTION
**Pull request by ghost**
:cl: More Robust Than You
admin: All antags are now logged to antag.log!
/:cl:

### CODE REVIEW

**Comment by nfreader** [comment]
Is this not covered adequately by `manifest.txt` and `round_end_data.json` ?

**Comment by MoreRobustThanYou** [comment]
@nfreader 
```<oranges> can someone add antag status to the manifest.txt log
<oranges> or even better an antag.log
<oranges> that just lists all mobs that had an antag mind
<oranges> and the times they were antag```

**Comment by Jordie0608** [comment]
Kinda vapid but I guess there isn't really much reason to not have this. It'd be better as an investigate log however.

Also @MrStonedOne a brand new file for parsing.

**Comment by AnturK** [comment]
Seems bit redundant but i guess if if it's for ease of use.

**Pull request closed without merging**
