### PR TITLE
Dixon Buttes XXXXIV

### PR DESCRIPTION
**Pull request by Iamgoofball**
goof

### CODE REVIEW

**Comment by kevinz000** [comment]
you're abstract.

**Comment by Firecage** [comment]
Can you please change the changelog entry into what this PR actually does? Or remove it.

And can you please change the title so it says what the PR does?

**Comment by ChangelingRain** [comment]
I don't this this actually fixes being able to pick invisible stuff.

**Comment by Iamgoofball** [comment]
@ChangelingRain I'm literally working with the only part of the bug report which I was given, which is "you can pick clothing items with the ABSTRACT flag".

The other invisible items are clothing items which got removed but still have code entries. If you guys make me a list I'll fix those too, but don't you dare give me this crap about "this doesnt fix the bug :^)" when this literally fixes the only part of the bug people will tell me

**Comment by AnturK** [comment]
Don't care about about your hate campaign but don't leave bugs that can be fixed with one line in on purpose.
`if(!initial(I.icon_state) in icon_states(initial(I.icon))) continue`

**Comment by Iamgoofball** [comment]
Holy shit, we can do that?

**Comment by Jordie0608** [comment]
@optimumtact AnturK's comment?

**Comment by optimumtact** [comment]
it didn't meet our code standards because it was all on one line.

**Comment by Jordie0608** [comment]
You're smarter than that mate, you should know what i mean.

**Pull request merged**
