### PR TITLE
Tweaks the syndicate infiltrator so it's no longer lopsided.

### PR DESCRIPTION
**Pull request by WJohn**
This always was kind of annoying to me, and made mapping these things in slightly more difficult than necessary, so I changed that. Hurray!

:cl: WJohnston
tweak: Syndicate nuke op infiltrator shuttle is no longer lopsided.
/:cl:

### CODE REVIEW

**Comment by Bawhoppen** [comment]
Symmetry should be used in moderation. This isn't a good use of it.

**Comment by Spaceinaba** [comment]
your mom isnt good use of symmetry

**Comment by Bawhoppen** [comment]
Oh looks it's the endless drooling masses who will blindly defend symmetry at all costs

**Comment by Bawhoppen** [comment]
GO BACK TO MINECRAFT

**Comment by Bawhoppen** [comment]
image

^
BAD SYMMETRY USAGE

**Comment by Spaceinaba** [comment]
nice picture of your mom doofus

**Comment by WJohn** [comment]
i'll gladly redesign the whole syndicate infiltrator in the future, but right now this just makes it a little bit saner for mappers to play with since it doesn't have like the most obtuse docking port ever, it's conceivably possible to make it dock at an airlock other than the one it was designed for, now.

**Comment by Bawhoppen** [comment]
Oh docking port is a legitimate argument I guess

**Comment by Bawhoppen** [comment]
Then again, removing the unique design for something that isn't really typically going to be needed is kind of lame.

**Review by ninjanomnom — APPROVED** [review]
code seems fine

**Pull request merged**
