### PR TITLE
Adjusts blob ability costs down slightly, gives blobs a hud

### PR DESCRIPTION
**Pull request by ChangelingRain**
:cl: Joan
rscadd: Blobs now have a hud, with jump to node, create storage blob, create resource blob, create node blob, create factory blob, readapt chemical, relocate core, and jump to core buttons.
tweak: Manual blob expansion is now triggered by clicking anything next to a blob tile, instead of by ctrl-click.
tweak: Rally Spores no longer has a cost. Reminder: You can middle-click anything you can see to rally spores to it.
tweak: Creating a Shield Blob with hotkeys is now ctrl-click instead of alt-click.
rscadd: Removing a blob now refunds some points based on the blob type, usually around 40% of initial cost. Hotkey for removal is alt-click.
rscadd: Blobs now have the _Blob Help_ verb which will pull up useful information, including what your reagent does.
tweak: Storage Blobs now cost 20, from 40. Storage Blobs also cannot be removed by blob removal.
tweak: Readapt Chemical now costs 40, from 50.
/:cl:
space station 13 2015-11-20 191911

### CODE REVIEW

**Comment by Aloraydrel** [comment]
wew

**Comment by optimumtact** [comment]
POSTING IN A STICKY THREAD

**Comment by GunHog** [comment]
Deliberately labeling your PR in a false manner is a violation of---oh, he changed it.

**Comment by Zilenan91** [comment]
The blob attack/expand buff is huge, might even be an unneeded buff.

Everything else is :+1: :100:

**Comment by Robustin** [comment]
Blob already has a 44% win rate, compared to the abysmal ~10% win rates of wizards and malfs (the other 'solo' antags).

Keep the basic QoL stuff and buffs for unused abilities, but for the love of god do not throw in a 20% reduction of blob expansions.That's the single greatest consumer of blob resources and dropping it to 4 makes it much easier for a smart blob to just snowball really fast, being able to spam expansions is basically the "I win" phase of blob, these other changes are already enough to make blob even better than ever.

**Comment by Anonus** [comment]
Okay instead of reducing the expand cost I'm giving blobs a hud and better hotkeys, which should give about the same results anyway.

**Comment by RemieRichards** [comment]
@Anonus show hud

**Comment by Anonus** [comment]
It's simple but it works well enough, a lot better than a tab full of powers of dubious usefulness.
space station 13 2015-11-20 120958

**Comment by GunHog** [comment]
I recommend adding some borders and a background for the HUD, it currently blends in with the rest of the blob tiles.

**Comment by Anonus** [comment]
They actually do have a background but I can improve on that a bit.

**Comment by duncathan** [comment]
Definitely give them sa border

**Comment by Anonus** [comment]
Done!
space station 13 2015-11-20 124514

**Comment by GunHog** [comment]
Well, that is an improvement...

**Comment by Anonus** [comment]
It is worth noting that this is the only color that'll have this sort of conflict.

**Comment by Zilenan91** [comment]
@Anonus Is there any way for you to code one free chem reroll incase you don't get one you like?

**Comment by Anonus** [comment]
That'd be pretty easy but I'd like to see how fast the blob winrate jumps when blobs have useful info and buttons shoved at them.

**Comment by Zilenan91** [comment]
Significantly, It seems like 1/2 blobs don't know how RTS or Blob works.

**Pull request merged**
