### PR TITLE
removes a comment mentioning removing hulk

### PR DESCRIPTION
**Pull request by JohnFulpWillard**
## About The Pull Request

This comment was added when kapu redid limbs, and it bugs me because it makes it seem like it's some TO DO or wishlist, and not just something one contributor wants. Hulk's removal isn't (at least, as far as I'm aware) wanted by maintainers, so this comment seems kinda shitty to leave in since it confuses me and likely confuses others as well.

## Why It's Good For The Game

doesn't affect the game.

## Changelog

Not needed.

### CODE REVIEW

**Comment by Iamgoofball** [comment]
removing hulk is definitely still on the todo list, it's been on the todo list for decades

**Comment by magatsuchi** [comment]
> removing hulk is definitely still on the todo list, it's been on the todo list for decades

no

**Comment by JohnFulpWillard** [comment]
> removing hulk is definitely still on the todo list, it's been on the todo list for decades

https://github.com/tgstation/tgstation/pull/56116
https://github.com/tgstation/tgstation/pull/56184
https://github.com/tgstation/tgstation/pull/31576 (this one is yours)
https://github.com/tgstation/tgstation/pull/23468

idk man something tells me you're lying

**Comment by SuperNovaa41** [comment]
remove hulk instead

**Comment by Iamgoofball** [comment]
@JohnFulpWillard i'm not lying, it's just that removing hulk is contingent on us getting better genetics gameplay that isn't just hulk and/or xray

**Comment by Colovorat** [comment]
I would rather change comment to something else. Because if something actually happens to hulk, this line will be easier to find for a change

**Comment by Mothblocks** [comment]
meta comments suck

**Pull request merged**
