### PR TITLE
Nerfs xray gun

### LINKED ISSUE #6928: XRAY Lasers are kind of awfully balanced/maybe should exist at all
It's time we really think about just how fair Xray lasers are. They pretty easy to make, and they're basically just a win item.

examples:

>blob 
>become HUGE
>crew struggling to deal with even a bit of me
>cover all of brig
>a couple of guys stroll up with xray lasers
>2 seconds of shooting, 65-70% total mass is now gone

utter devastation

>hop 
>xeno outbreak
>get buttfucked in the pussy by xenos, fair cop
>watch xenos as ghost
>they're doing really well, taking on the crew pretty good
>1 person walks up with a laser and begins spray&praying through the wall
>queen dead, 2 babies dead, 1 hunter dead
>in one clip

### LINKED ISSUE #9923: Xray lasers OP
Right now, X-ray lasers are a bullshit level of overpowered. 
They can shoot through walls, and (unless I am mistaken), go forever. Meaning if you shoot them they go forever through Z levels and go through the station again. 
Combined with a X-ray implant, you're basiclly unstoppable unless someone else has the same thing.

On a side note, apparently it makes aliens very badly irradiated, because other day I shot an alien queen and it started shaking on the ground. :o.

### PR DESCRIPTION
**Pull request by phil235**
- Nerfs xray gun by giving it a shorter range Fixes #9923. Fixes #6928.
  Its range is now 15 tiles.
- Fixes projectile with a range having their range drop faster than it should when passing through things.
- Make vault airlock more explosion resistant (explosion_block var) for consistency.

### CODE REVIEW

**Comment by SconesC** [comment]
>high security airlocks

If I paint an airlock high-security, am I powergaming vs Science now?

**Comment by palpatine213** [comment]
:-1: to being completely blocked by rwalls. Xray lasers were a good way of killing a relatively bunkered down target or a rogue Ai without needing thermite or huge bombs. Especially not since bombs are getting nerfed with rwalls blocking the explosion more.
Also, Inb4 engie borgs get an airlock painter and malf AIs make xray proof door forts.

**Comment by Cheridan** [comment]
Look at the code, guys... Paint doesn't matter.

**Comment by SconesC** [comment]
fug u cheridan

**Comment by phil235** [comment]
If people aren't happy with reinforced walls blocking I can tweak the values pretty easily.

**Comment by Anonus** [comment]
Yeah rwalls and secure doors, like the ones for the AI core, should definitely block the beam.

**Comment by Kromgar** [comment]
How many blob tiles  can xray lasers go through

**Comment by phil235** [comment]
Five if you are right next to it or one tile away. Three if the blob tiles are just out of your sight or one tile further.

**Comment by palpatine213** [comment]
I don't get why it should be stopped by rwalls though. The xray laser isn't that cheap, and normal walls can be deconstructed or blown up pretty easily. It seems like a major nerf to be unable to shoot into the bridge or sec.

**Comment by SconesC** [comment]
they're fairly cheap iirc

**Comment by Lumipharon** [comment]
they only have a really high uranium cost BECAUSE  they're pants on head retarded strong in some situations.

**Comment by Deputi** [comment]
How will the crew win blob? Does blob really need another buff?

**Comment by Cheridan** [comment]
Xrays being this cheezy hard-counter to Blob isn't good balance. If blobs are too strong lategame then we should fix that directly. The mode shouldn't be determined solely by the crew's ability to rush production of a single weapon type.

**Comment by AlexCrimson** [comment]
Then maybe you should fix blobs lategame steamrolling rather than nerf the only thing in the game capable of stopping them.

**Comment by Durkel** [comment]
Don't merge this until you find a way to nerf blob, It's fucking ridiculous how powerful blobs are without a xray to counter it. Borderline impossible if you don't spot it immediately.

**Comment by PKPenguin321** [comment]
:-1: on making it blocked by things, but :+1: for the range decrease
:-1: overall, however

**Comment by Lumipharon** [comment]
Clusterbangs (if you can make xrays you can make these) also pretty much ggnore blobs but yeah, an anag shouldn't only be counterable by a high end R&D item.

**Comment by phil235** [comment]
Alright, people don't seem to like my proposition on the feedback forum, so here's a new one:
- still 15 tiles range
- passes through everything but its damage is reduced by solid obstacles (can't go below 33% of initial damage)

**Comment by WJohn** [comment]
I'm okay with this.

**Comment by phil235** [comment]
Don't mind Travis, he's being silly.

**Pull request merged**
