### PR TITLE
Created lantern in-hands

### PR DESCRIPTION
**Pull request by swankcookie**
lanterns used too turn into flashlights on mob sprites when picked up.  but no longer.
:cl: Swankcookie
rscadd: lanterns no longer turn into flashlights when you pick them up.  
/:cl:

### CODE REVIEW

**Comment by Zilenan91** [comment]
Is there any way to get lanterns normally? They don't spawn anywhere on any maps as far as I know.

**Comment by tkdrg** [comment]
miners get one roundstart i think

**Comment by Zilenan91** [comment]
They don't on any maps, they just have their hardsuit helmets and PDAs for light.

**Comment by swankcookie** [comment]
2 spawn in the chapel on meta.  Thats how i found the issue.

**Comment by Bawhoppen** [comment]
I think it was pap's fault miners don't have them any more, we could probably add them back

**Comment by swankcookie** [comment]
I would add some in this PR, but I still havnt figured out the mep merger yet

**Pull request merged**
