### PR TITLE
Adds screaming for burns

### PR DESCRIPTION
**Pull request by Cyberboss**
:cl:
tweak: NT now provides education on the proper response for experiencing the excrutiating pain of varying degree burns (You scream when burning)
/:cl:

Fire hurts, K?

### CODE REVIEW

**Comment by Bawhoppen** [comment]
My headcanon always was that considering how our humans are clearly genetically improved than modern day humans, is that they also blatantly couldn't feel pain, hence how nobody reacts when being shot

**Comment by SgtxRootbeer** [comment]
@bawhoppen then why does stypic powder, and silver sifulzidine cause screaming?

**Comment by Bawhoppen** [comment]
that was added way later (see goofchem) than other health mechanics

**Comment by dannno** [comment]
why not scream for more things like getting shot and taking serious damage and stuff

**Comment by Cyberboss** [comment]
@danno have to start somewhere

**Pull request merged**
