### PR TITLE
IDs can reveal if they've claimed a dorm

### PR DESCRIPTION
**Pull request by Tacolizard**
Examining and ID will tell you if it has claimed a dorm. Mabye in a future pr i'll make it so you can see which dorm was claimed, to help the det.

### CODE REVIEW

**Comment by kevinz000** [comment]
does the dorm value even do anything?

**Comment by coiax** [comment]
I'm not sure if we even have code that claims dormitories.

**Comment by Tacolizard** [comment]
I might be mistaken, but I'm pretty sure that IDs are used to claim the lockers inside dorms.

**Comment by Tacolizard** [comment]
I don't think the dorm value does anything acutally

**Pull request closed without merging**
