### PR TITLE
Plasmamen become humans in the deathmatch

### LINKED ISSUE #81858: Plasmaman Deathmatch Blues
## Issue Summary

If you have a plasmaman character you spawn as a plasmaman in deathmatch. Thus immediately being set on fire and suffocating.

## Reproduction:
1. Make a plasmaman character
2. Play deathmatch
image
image

### PR DESCRIPTION
**Pull request by Exester509**
## About The Pull Request

Does what #81629 intended by fixing a broken conditional.

## Why It's Good For The Game

People should be able to play the minigames.

## Changelog

:cl:
fix: Plasmamen will become human in the deathmatch so they don't instantly die
/:cl:

### CODE REVIEW

**Comment by Helg2** [comment]
You could maybe add the traits the same way basketball minigame gives them out, so plasmamen don't die.

**Comment by mc-oofert** [comment]
> You could maybe add the traits the same way basketball minigame gives them out, so plasmamen don't die.

That would make them completely immune to fire

**Comment by Exester509** [comment]
> You could maybe add the traits the same way basketball minigame gives them out, so plasmamen don't die.

It was agreed in the mentioned PR that the solution would be making them human. This is merely implementing that due to a small code issue with the previous PR.

**Comment by optimumtact** [comment]
Why not give them a suit? I'm confused as to the logic.

**Comment by mc-oofert** [comment]
this is a bugfix for a merged pr tried to do it

**Comment by Exester509** [comment]
> Why not give them a suit? I'm confused as to the logic.

All reasoning was/should have been discussed in the previously mentioned PR. This is fixing a bug with how it worked

**Review by Ghommie — APPROVED** [review]

**Pull request merged**
