### PR TITLE
Adds more multiz support

### PR DESCRIPTION
**Pull request by ShizCalev**
:cl: ShizCalev
qol: Added multi-z support to: Wizard teleporting, AI law upload computers, chemical / tracking implants, robotics control consoles, camera bugs, blob spores, and the apocalypse rune's visual effects.
/:cl:

### CODE REVIEW

**Comment by magatsuchi** [comment]
mso approved

**Comment by bruhlookatthisdood** [comment]
funny pull request number

**Comment by Ryusenshu** [comment]
Id argue its some balance change in that too
AI was able to get away from all those upload shenanigans by moving lower onto icebox, same with locking borgs

**Comment by ShizCalev** [comment]
@Ryusenshu Will pursuit a solution for that as well then!

**Comment by ShizCalev** [comment]
Drafting to finish testing.

**Comment by JohnFulpWillard** [comment]
I don't like the idea of Icebox's very bottom floor feeling the effects of the Supermatter's delam, but that's the default of the map and not your own. Thank you for this

**Comment by Helvetica8563** [comment]
Pull request #69420 nobody noticed?

**Pull request merged**
