### PR TITLE
Fixes xenobio console breaking with monkey numbers

### PR DESCRIPTION
**Pull request by LatD**
Making the console add +0.2 causes the console to have for example 0.9999998 monkies after 5 monkies and other weird numbers. This will fix it to get a full monkey properly.

~~Not tested yet. I'll test this soon.~~ Tested to work.

### CODE REVIEW

**Comment by coiax** [comment]
You're just trying to shortchange me out of my 4.35365346E-34 of a monkey, aren't you. ADMIT IT!

**Comment by RemieRichards** [comment]
you could just ```floor()``` the ```monkeys``` number in the display.

**Comment by LatD** [comment]
How do I use `floor()` there and what does it do? I can't find the original proc for `floor()` since searching for floor gives 27 pages of results.

**Comment by RemieRichards** [comment]
@LatD Turns out we don't have a version called ```floor()```, but just do ```round(monkeys)``` (a ```round()``` call with only 1 argument is identical to a ```floor()```) basically it rounds down to the closest whole number, eg: 4.7 monkeys is 4 monkeys, that's NOT a lie to the player as they can only use 4 monkeys, a ```round(monkeys, 1)``` however with 4.7 would tell them they have 5 monkeys! which isn't true!

Basically in the UI of the console, where it displays ```monkeys``` make it display ```floor(monkeys)```

**Comment by LatD** [comment]
That would solve the UI problem but would still leave the problem of actually having 0.99998 monkies after recycling 5 times.

**Comment by KazeEspada** [comment]
Latd, if you round(monkeys,0.1) You will always round to the nearest tenth.

**Comment by RemieRichards** [comment]
@LatD correct me if I'm wrong (I don't xenobio) but recycling is += 0.2 monkeys, and 5*0.2 is 1, so every 5 1/5ths is 1 (such maths, many science, wow), and yes a floor function rounds to the nearest whole integer (it's basically float -> int conversion downards)

**Comment by LatD** [comment]
That's what it's supposed to do but that's the bug I'm trying to fix here. Recycling 5 monkies can give 0.999998879 monkies or 1.0000... monkies. And then "you have 4.35365346E-34 monkies left" thing happens or you can't place a monkey if you only have 0.99999997 monkies in the console. Every xenobiologist probably knows this bug by now.

round(monkeys,0.1) might work though. I can use 0.2 there as well right?

**Comment by KazeEspada** [comment]
@LatD No, you can't. If you are adding .2 monkeys, and rounding to the nearest .1. Even if Byond fucks up, you will get a whole monkey.

**Comment by RemieRichards** [comment]
```round(monkeys)``` is fine, 0.2*5 is ALWAYS 1, always, it is never not one

**Comment by LatD** [comment]
http://puu.sh/on3IR/285fbb62e1.png

This happened just now when I recycled 5 monkeys and then used one. 5*0.2 isn't always 1 with float numbers. It can be a little above it or a little under it. If it was always 1 there would be no need to round anything.

**Comment by coiax** [comment]
@LatD, I think they mean to say round(0.2 * 5) is always 1

**Comment by LatD** [comment]
But if round(monkeys) rounds down then 0.9999998 monkeys would still be 0 monkeys

**Comment by KazeEspada** [comment]
That's why I suggested round(monkeys, 0.1) so it always rounds to the tenths place.  So, round(0.2*5, 0.1) == 1.0

**Comment by LatD** [comment]
Yeah, that's the version I've currently put in this PR. I'll still test it later to confirm it.

**Comment by JJRcop** [comment]
I think you're looking at it the wrong way. Wait for dismemberment, then give the scientists exactly how much monkey they are gonna get.

**Comment by KazeEspada** [comment]
Dismembermeme is human

**Comment by LatD** [comment]
I tested the round with 0.1 and it seems to work perfectly. This is ready.

**Comment by octareenroon91** [comment]
Would changing the `monkeys` var to `fifths_of_a_monkey` be poor form?

**Comment by LatD** [comment]
That would be a bit like the thing I originally did in this PR. "Problem" with that would be that then putting monkey cubes in would give 5 of those each and the output would need to be rewritten so show monkeys instead of fifths of monkeys. Overall this round() seems to be the cleanest way to do this.

**Pull request merged**
