### PR TITLE
Removes Romerol from the uplink

### PR DESCRIPTION
**Pull request by Iamgoofball**
```
<Iamgoofball> Joan, i would not be so angry if we didnt have a 2 hour round because >traitor viro buys romerol >releases, dies >traitor engi overloads the SM and destroys all consoles to call shuttle except one hidden in maint with rwalls >AI destroyed because it kept calling the shuttle
<Ergovisavi> Busy trying to figure out why this stupid mob won't behave the way I want it to
<Joan> I tried furi a while ago and it was... way too hard for me
<Ergovisavi> Furi is pretty notoriously difficult
<Ergovisavi> Did you dial it down?
<LeoZ> >try searching for furi on steam
<LeoZ> >doesnt show the game
<LeoZ> >steam crashes
<Iamgoofball> >90% of players are zombies, cant do anything because lol no free hands, moves super fucking slow, only humans left are AFK ones on the arrivals shuttle or hidden in maint
<Iamgoofball> suffice 2 say
<Iamgoofball> fuck romerol
<Iamgoofball> forever
<Joan> I did but it was still, uh, more difficult than I really cared for
<Iamgoofball> it's boring/downright fucking retarded as a zombie
<Iamgoofball> it's annoying as a huma
<Iamgoofball> and worst of all
<LeoZ> is the game just bullet hell(furi)?
<Iamgoofball> YOU CANT FUCKING GREENTEXT IF YOU HAVE THE DIE OBJECTIVE
<Iamgoofball> BECAUSE YOU CANT FUCKING DIE
```

### CODE REVIEW

**Comment by KingPhilipIII** [comment]
Muh zombies.

**Comment by outbools** [comment]
>[Feature Freeze!]: # We are currently not considering any balance or antagonist oriented pull requests. Full details, as well as ways to bypass this freeze, are available here #28223

**Comment by DoctoreMad** [comment]
It should not go without saying that this does not remove Romerol form, for example, being bought in a Traitor's PDA, so it doesn't properly remove romerol form the game.

**Comment by kevinz000** [comment]
WTF I LOVE GOOFBALL NOW?!!!

**Comment by Iamgoofball** [comment]
@DoctoreMad you're fucking retarded read the diff that's exactly what it removes

**Comment by DoctoreMad** [comment]
But its right there

**Comment by Iamgoofball** [comment]
http://i.imgur.com/Noap2ap.png

stop being autistic

**Comment by DoctoreMad** [comment]
Well this conversation is useless so I'll just leave.

**Comment by PKPenguin321** [comment]
goofball dies to zombie and suddenly IT IS op REMOVe it

**Comment by Iamgoofball** [comment]
not only did i die but

>zombies and humans smashed all the shuttle call methods

>kept recalling

>had my greentext for dying denied because ZOMBIES LITERALLY CANT FUCKING DIE

**Comment by PKPenguin321** [comment]
Just cut off their arms pussy

**Comment by Iamgoofball** [comment]
its hard to do that  AS A ZOMBIE

**Comment by FantasticFwoosh** [comment]
Why not just nerf zombie stun recovery & remove the gradual self healing unless  you're attacking something. Removing them is just a waste of not only yours but other people's effort.

Hell, make it 30 TC expensive or something.

I will admit, if you're wearing armor like a engineer suit with the hood up (rendering you immune to flashes) being or fighting a zombie like that is kind of bullshit, so most definitely make zombies ignore armor flags and resistances.

**Comment by Grazyn** [comment]
>ZOMBIES LITERALLY CANT FUCKING DIE

just throw yourself into the supermatter fam, like smash your way in and hug it lol

**Comment by Iamgoofball** [comment]
THE SUPERMATTER ALREADY EXPLODED

**Comment by Cyberboss** [comment]
Freeze

**Comment by Iamgoofball** [comment]
No. Fuck you. This needs to go. Go do your fucking job and fix the server bot instead of closing good PRs.

**Comment by lzimann** [comment]
I say we ignore, because romerol is garbage.

**Comment by ChangelingRain** [comment]
@KorPhaeron

**Comment by Supermichael777** [comment]
jump in the supermatter goofball

**Comment by Iamgoofball** [comment]
@Supermichael777 @GunHog 
the supermatter was destroyed by the same traitor who kept fucking recalling

**Review by Cyberboss — APPROVED** [review]

**Comment by Cyberboss** [comment]
People keep trying to do this. I can firmly say I'm not going to support it at this point

**Comment by Steelpoint** [comment]
>ignore the freeze

I have no strong opinion on this PR but if this ignores the freeze just because its convenient for a maintainer then why bother with the freeze at all? 

If this goes through can we merge my traitor tool PR as well?

**Comment by lzimann** [comment]
We are allowed to "ignore" if we think it will benefit the game more than having to wait until it is over. Which in my opinion, getting rid of these zombies is a massive improvement to the game.

**Comment by Armhulen** [comment]
noooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo

**Comment by KorPhaeron** [comment]
If someone can give me stats proving this is bought in a significant number of rounds/is actually ruining the game we can bypass the freeze but otherwise we can look at it later

**Comment by Armhulen** [comment]
thank you kor, i'm sorry that the one round every 15 days, two traitors actually meet up, coordinate, and successfully spread the disease without it getting stopped and wow a 25 tc item is GOOD!

**Comment by lzimann** [comment]
I can't see how a conversion mechanic in a traitor round is anywhere near good. Anyway, as soon as the freeze ends, romerol is going away.

**Comment by Balcore** [comment]
I personally like Romerol. I literally never see it used and when it is used it almost never spreads. I was on last night when this drama unfolded and I can safely say that was a 1 in 100 round. 

My solution keeps the system in play and tweaks it so we don't get Zomb-xtended rounds.
 
Introduce a check once romeral is used that monitors how many players are undead. Once more than 50% of active players are have an infected tag, a mandatory shuttle call is activated. Now you kill the issue of it delaying rounds.

Next make it so zombies degrade and have to keep eating or they slowly fall apart. WWZ that shit and make it so zombies move faster the closer they get to falling apart cause rigor mortis is a legt thing.

Removing it entirely seems like a knee jerk reaction and ultimately removes a unique feature from the game. Obviously I am no coder. I barely even sprite but I am a dedicated player so I think my opinion bares some semblance of weight here.

**Comment by BreadBurner** [comment]
I was the one who bought romerol that round, we were three tators working together, deadly virus + romerol took almost all the station, those alive had a great zombie survival experience, those who are unrobust and died to a mob that all it can do is run like a snail and bite you suffered from the worst fate.
Worth noting the console wasnt in maint, it was in our base of operations, virology. Icepax wioked both me and the virologist to NOT RECALL OR WE ARE SENDING DEATHSQUAD, he sent it anyway without a centcom message even thou we didnt recall. I hope he gets a note for that some day but hell knows he wont.

**Comment by Iamgoofball** [comment]
@BreadBurner If the engineer was one of your group I personally saw him recall the shuttle 2 times while alive and one time while waiting on the zombie revive timer

**Pull request closed without merging**
