### PR TITLE
Allow reflector construction

### PR DESCRIPTION
**Pull request by octareenroon91**
New reflector frames can now be built at will.

:cl:
add: Allow new reflector frames to be built from metal sheets.
/:cl:

This change was implied by the switch to supermatter #24447 .

### CODE REVIEW

**Comment by JJRcop** [comment]
Do we have pixel projectiles ricochet yet?

**Comment by GunHog** [comment]
No, they only work with emitters. This is kind of needed due to the move to the SM engine.

**Comment by jughu** [comment]
Dont forget reflector boxes are made of diamonds! Dern scientosts thieves!

**Comment by Bawhoppen** [comment]
Reflectors currently don't work properly with pixel projectiles, only with emitter blasts.
Remove the reflectors from the SM engine instead of trying to readd a currently broken feature.

**Comment by jughu** [comment]
>remove the reflectors from sm engine
ok go ahead bawhoppen map a new emitter fire placement from all 3 sides so you get a good power output

**Comment by Robustitron** [comment]
You could also just say they're only "tuned" for emitter wavelengths because science and put it in the inspection text.

Just an alternative to, you know, hobbling the whole engine.

**Comment by Bawhoppen** [comment]
not my fault we have gimmick engine as a standard engine now

**Comment by Tokiko1** [comment]
Consider lowering the diamond cost to just glass since they're emitter only reflectors for now.

**Comment by octareenroon91** [comment]
Maybe plasteel: the construction path is kind of fucked up as it stands, since the THREE sheet types glass, rglass, and diamond obtain the THREE different reflector types.

**Comment by JohnGinnane** [comment]
Hi, if you guys want to look, I wrote some pixel projectile reflection code:

https://github.com/HippieStationCode/HippieStation13/blob/bf944ceade1c911352a6db7b905bc4037fafe51c/code/game/objects/structures/mirror.dm#L359

This also handled emitters too!

**Comment by JohnGinnane** [comment]
https://github.com/HippieStationCode/HippieStation13/pull/3179 is the pull request. It has some videos of how it behaves

**Comment by Bawhoppen** [comment]
@JohnGinnane thanks for the help, will try and use it if I have the time

**Comment by JohnGinnane** [comment]
No problemo

**Pull request merged**
