### PR TITLE
Reactive Illusion Armour

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
When hit, there is a chance to briefly (3 seconds) turn invisible while an illusion/copy of you runs away. Admin only.

:cl: Kor
rscadd: Adds reactive stealth armor. Admin spawn only.
/:cl:

### CODE REVIEW

**Comment by duncathan** [comment]
Kickass :+1:

**Comment by WJohn** [comment]
Neato :+1:

**Comment by AlexCrimson** [comment]
Phantom Lancer?

**Comment by KorPhaeron** [comment]
@AlexCrimson 

This is more Dead Ringer, but Phantom Lancer is next

**Comment by GunHog** [comment]
All of these now armors are giving me much excitement!

**Comment by CosmicScientist** [comment]
But the dead ringer makes a dead not-you fall over?

**Comment by KorPhaeron** [comment]
I guess this is like Phantom Lancers escape then sure

**Comment by kevinz000** [comment]
Now if only it stunbreaks
(Reactive Adrenaline Armor)

**Comment by drynwyn** [comment]
What happens if the hit was a stun weapon? Does your illusion ignore the stun?

And is the sprite non-obvious? Be a lot less useful if it's super visible.

**Comment by KorPhaeron** [comment]
@drynwyn 

It looks exactly like you

**Comment by drynwyn** [comment]
I meant the armor's sprite, not the illusion of you that runs away. Right now it looks like it uses the Reactive Teleport Armor sprite.

Also, stun weapons?

**Comment by KorPhaeron** [comment]
@Cheridan @duncathan @Razharas @Jordie0608 @RemieRichards

Mergebegging, it's admin spawn only and doesn't touch anything else I promise it doesn't break the game

**Comment by KorPhaeron** [comment]
@drynwyn 

It can't realistically carry verbs. It does look like normal reactive

**Pull request merged**
