### PR TITLE
This adds the ability for simple animals to commit suicide.

### LINKED ISSUE #5764: simple_animals cannot suicide
Tested with corgis and spider, probably applies to all simple_animals.

### PR DESCRIPTION
**Pull request by Firecage**
As it says in the title. This PR adds the ability for simple animals to commit suicide. Now, imagine Ian suiciding in front of the HoP.

Fixes #5764

### CODE REVIEW

**Comment by ike709** [comment]
Now some admin is going to make Ian commit seppuku...

**Comment by Firecage** [comment]
But Ian comitting Sudoku is cool!

**Comment by Alek2ander** [comment]
No unique messages for every pet. :dog: :gun:

**Comment by Firecage** [comment]
Aleksander, there are to many simple animals. TO FUCKIN MANY

**Comment by Alek2ander** [comment]
They're not all pets :^)

**Comment by phil235** [comment]
:+1:

**Comment by Ergovisavi** [comment]
Tested, works fine.

**Pull request merged**
