### PR TITLE
Fixes xenomorph not being able to open their eggs.

### LINKED ISSUE #20997: Xenos can't open their eggs by clicking on them. Also other xeno related bugs
They instead attack them.
The alien queen smashes into the egg!

@phil235

### PR DESCRIPTION
**Pull request by phil235**
Fixes #20997

### CODE REVIEW

**Comment by FantasticFwoosh** [comment]
Phil you are aware thats a CM feature people haven't asked around about (ahelps/OOC community) and are now whining to implement? Its a community suggestion based out of not knowing, they were never intentionally meant to be that way in our TG brand xenomorphs, its not a issue with code inconsistency or missing features.

> Because our huggers are less static that CM's and actively jump on everything after about a second of wind up time as soon as they are out of the egg this will lead to ENORMOUS xenomorph powercreep with sentinels giving queens plasma for gg infinite eggs and fast manual opening for xenomorphs.

> Literally the reason why CM nerfed xenomorphs really hard.

This will end up being bad, i have a gut feeling.

**Comment by Militaires** [comment]
@FantasticFwoosh i understood nearly nothing of that

also it's a fucking bug, currently xenos just smash into their eggs until the eggs die and the facehugger dies aswell dude pls

**Comment by Supermichael777** [comment]
fwoosh this is a bug the code that did this is already there, xenos just got a different kind of attack at some point

**Comment by XDTM** [comment]
Yeah this was already a thing before the damage refactor, not a new feature

**Comment by GunHog** [comment]
I am not sure I understand the issue here. Xenos are able to manually open their eggs, _once matured,_ by clicking on them and picking up the hugger. That is how it is supposed to work!

**Comment by Shadowlight213** [comment]
@GunHog Except they can't.
The bug is that trying to manually open a <b>matured</b> egg will result in the xeno just smashing into said egg, and eventually destroying it and killing the hugger.

**Pull request merged**
