### PR TITLE
Adds 2 new sounds to the Synthesizer's 'Fun' category

### PR DESCRIPTION
**Pull request by NanoTrasen-Inc**
## About The Pull Request

Adds 2 new sounds to the 'Fun' category of the synthesizer
- MeowSynth
- Spaceman

### File size

All sound files are mono, and only take up a combined total of 141 KiB of space. For reference, Crisis Brass takes up 368 KiB, so I did a pretty damn good job on size reduction. No need to worry about bloat.

### MeowSynth
A synthetic sound font of a cat meowing. How cute!

MeowSynth is an old meme from back in the 2000s. It's slowly been slinking up into modern culture again, and I'd love to see it immortalized in SS13. If you haven't heard of it before, I strongly encourage you to [click here](https://www.youtube.com/results?search_query=meowsynth) and [do some listening](https://www.youtube.com/watch?v=cwyTleTL06Y).

Preview:

https://user-images.githubusercontent.com/1747249/183230334-1582b2cb-f19b-4f16-a807-2d7873ac68e3.mp4

([Kero Kero Bonito - Flamingo](https://www.youtube.com/watch?v=Tol7m6zw5p8))

### Spaceman
A sound font of DecTalk Paul, the TTS engine used in Moonbase Alpha.
[AIEOU!](https://www.youtube.com/watch?v=Hv6RbEOlqRo)

Preview:

https://user-images.githubusercontent.com/1747249/183229172-af853af2-f851-4ccb-9fdb-cdf6af00092e.mp4

(Fly me to the moon, obviously)

## Why It's Good For The Game

- Gives some life to the !!FUN!! category on the synth.
- Immortalizes the deceased MeowSynth cat in SS13 history. May he meow in peace, never knowing the impact he has had on all of our hearts.
- Finally adds a Moonbase Alpha reference. About time!

## Changelog

:cl: Nano
soundadd: Added 2 new sounds to the synthesizer's 'fun' category: MeowSynth and Spaceman
/:cl:

### CODE REVIEW

**Comment by NanoTrasen-Inc** [comment]
This is my first actual PR. Do let me know if goofball'd anything.

**Comment by Mothblocks** [comment]
we don't have the license to a single one of these (maybe the tts one if you can track down the source, and if it's not some very specific thing)

**Comment by NanoTrasen-Inc** [comment]
I'll look into licensing information when I wake up.

Will also be deleting sans

**Comment by NanoTrasen-Inc** [comment]
Eh, can't sleep. Digging into it now. I know nothing about licensing, so please correct any incorrect assumptions I make.

MeowSynth was released as a free VST plugin by a Russian person named Knobster. The original site has since disappeared from the internet, but an archive is located here: https://lostsoftwarearchives.neocities.org/Meow/

It was released as a free VST plugin for anyone to use. They haven't listed any restrictions, and it has been widely used on the internet in all forms of media.

I downloaded the plugin, threw it into VSTHost, tweaked the params to my liking, and recorded a C in each octave.

After that I cleaned them up in audacity and threw 'em in the folder.

Does this info change anything?



Regarding the DecTalk TTS samples:

DecTalk is released as MIT. The samples were recorded using the official DecTalk Demo software, also released under MIT. Same as MeowDynth, I cleaned em up and threw 'em in.

**Comment by Watermelon914** [comment]
> Eh, can't sleep. Digging into it now. I know nothing about licensing, so please correct any incorrect assumptions I make.
> 
> MeowSynth was released as a free VST plugin by a Russian person named Knobster. The original site has since disappeared from the internet, but an archive is located here: https://lostsoftwarearchives.neocities.org/Meow/

Be aware that just because something is available and free, does not mean you can use it. If no license is included with the sound/audio file, and there isn't any license linked to the audio file, then it means you cannot use it at all without explicit permission from the author.

**Comment by NanoTrasen-Inc** [comment]
Gotcha. If I created my own audio sample that sounds similar to MeowSynth, would that be okay to use?

**Comment by Watermelon914** [comment]
> Gotcha. If I created my own audio sample that sounds similar to MeowSynth, would that be okay to use?

yes, as long as it's not made using meowsynth

**Comment by NanoTrasen-Inc** [comment]
Knowing the licensing information, are the DecTalk samples alright to use?

**Comment by Mothblocks** [comment]
yes as long as you include the mit license for them (like putting LICENSE.txt in their folder)

**Comment by NanoTrasen-Inc** [comment]
Will do

**Comment by NanoTrasen-Inc** [comment]
Updated spaceman to use better samples. Video above has been updated.

**Comment by NanoTrasen-Inc** [comment]
Added MeowSynth license, as per https://discord.com/channels/326822144233439242/326831214667235328/1005295273628672060

**Comment by NanoTrasen-Inc** [comment]
Alright. Tweaking and licensing additions complete.

**Comment by NanoTrasen-Inc** [comment]
No longer needs -12 octave shift to sound good. Don't know why I missed this.

This is ready for review.

**Comment by NanoTrasen-Inc** [comment]
https://user-images.githubusercontent.com/1747249/183567592-66b102e1-0c35-4c9e-8dad-05f7ea020697.mp4

**Pull request merged**
