### PR TITLE
Spacepods

### PR DESCRIPTION
**Pull request by ghost**
SPACEPOD TIME

### CODE REVIEW

**Comment by praisenarsie** [comment]
@Cirrial !!!!

**Comment by Jalleo** [comment]
Haven't even converted or looked at vehicle datums before fixing conflicts and opening the PR......

**Comment by MoreRobustThanYou** [comment]
@Jalleo i just realize how horrid the new vehicle datum is

**Comment by praisenarsie** [comment]
not even 5 minutes

**Comment by Jalleo** [comment]
It was opened prematurely. Before even looking at was it suitable to do so.

**Comment by Cirrial** [comment]
well i gotta keep an eye on this mess now

**Pull request closed without merging**
