### PR TITLE
Removes Delta Station Roundstart Science Entrance Flash

### PR DESCRIPTION
**Pull request by Imaginos16**
## About The Pull Request

Does what it says on the tin. That funny flash that sits outside of science is going bye bye.
image

## Why It's Good For The Game

To reduce the funny roundstart gear powergaming that Delta reeeaaally loves. (Seriously though, a free flash just like that? Lame as hell.)
## Changelog
:cl:
del: Nanotrasen, after receiving many complaints, removed the flash that used to sit at the entrance of the science department.
/:cl:

### CODE REVIEW

**Comment by SuperNovaa41** [comment]
Flashes are pretty cheap and easy to get, this feels kinda pointless tbh

**Comment by Mothblocks** [comment]
If flashes are easy to get, then there's no reason to give one out for free that gets taken within 30 seconds of every round. While I don't like how easy to get into the abandoned robotics on Delta is, it's still enough of a barrier to entry that I often see it not broken into. 

But that's all irrelevant--the key focus is that all our maps, to some degree, give you way too much stuff round-start, whether it be tools, weapons, food (Tram is the only map we have that's good at food scarcity, and it's very fun), etc. I'm the one that asked for this PR along with the one that removed the power tools. Delta specifically is the worst offender, with a ton of stuff like this.

**Comment by maxymax13** [comment]
> (Tram is the only map we have that's good at food scarcity, and it's very fun)
tram is also the only map where people have to tide into the kitchen to make egg food roundstart, what a weird coincidence 🤔

**Comment by MrDoomBringer** [comment]
>  it's still enough of a barrier to entry that I often see it not broken into.

implying the real powergamers don't just wirecutter the hop line's flasher within 15 seconds of roundstard

**Comment by MrDoomBringer** [comment]
Should also probably specify that this only affects Delta station in the PR changelog

**Comment by Mothblocks** [comment]
> implying the real powergamers don't just wirecutter the hop line's flasher within 15 seconds of roundstart on every map

based as fuck

**Comment by Mothblocks** [comment]
> tram is also the only map where people have to tide into the kitchen to make egg food roundstart, what a weird coincidence 🤔

this is terry players when they are in serious danger of needing to talk to someone

**Comment by moocowswag** [comment]
Usually that flash is used for fake rev memes and ive never felt cheated when someone else uses it.

On lowpop ya i guess round start gear can add up when a single greytider manages to accumulate assets and can make a single person alot better off than they should be.

But on high pop I think it appeases that sandbox feel of the game by giving alot of people one or two things that they would otherwise need to greytide a bit to get.

**Comment by ArcaneDefence** [comment]
> 
> 
> Usually that flash is used for fake rev memes and ive never felt cheated when someone else uses it.

Faking  a revolution always causes grief, without fail. If someone is  pretending to be a revolutionary, feel free to murder them. If I find  someone faking a revolution as a non-antag, they can prepare to catch a  rule 1 ban for being a griefing shitter.
https://tgstation13.org/wiki/Headmin_Rulings

**Comment by Mothblocks** [comment]
We have an entire department for getting and delivering items, I'd rather greytiding and free map items be less effective than going through them.

**Comment by SuperNovaa41** [comment]
> > 
> > 
> > Usually that flash is used for fake rev memes and ive never felt cheated when someone else uses it.
> 
> Faking  a revolution always causes grief, without fail. If someone is  pretending to be a revolutionary, feel free to murder them. If I find  someone faking a revolution as a non-antag, they can prepare to catch a  rule 1 ban for being a griefing shitter.
> https://tgstation13.org/wiki/Headmin_Rulings
> 
> 

Will I get banned for saying viva immediately after being flashed

**Comment by optimumtact** [comment]
We have a whole forum for admin policy please confine yourselves to it.

**Comment by ATH1909** [comment]
reduces map diversity, smh

this isn't really a balance implication, since it's piss-easy to snip a flash anyway- I just think it's neat that newer players who don't know about flash snipping can acquire an easy flash from the front of delta sci

**Comment by Mothblocks** [comment]
image

i won my bet in any case

**Pull request merged**
