### PR TITLE
makes autolathe .357 print bullets individually instead of in speedloaders

### PR DESCRIPTION
**Pull request by imsxz**
## About The Pull Request

slightly modified one autolathe design
## Why It's Good For The Game

Revolverlathe murderboning is probably the lamest thing to play as and against. The only recourse is that it is rather cathartic to kill everyone without worrying about dying. This does not remove the ability to print .357 at lathes, mind you. you'll just have to load bullets as you would with a shotgun if you don't pony up 4tc for the speedloader.

4000 metal per bullet, because the original price was 30,000 metal for a speedloader divided by 7 is ~4300 and I rounded down and it's also consistent with the shotgun slugs and it looks nicer like that.

Get your ided comments out before the mods show up. I've used this strat more than I've died to it
## Changelog
:cl:
balance: autolathe no longer prints .357 speedloaders, but instead prints individual .357 bullets.
/:cl:

### CODE REVIEW

**Comment by SkeletalElite** [comment]
Reasonable nerf for a really strong item.
Will still be strong but you cant unleash a hail of bullets endlessly anymore.

**Comment by PKPenguin321** [comment]
While I usually hate nerfing by making the interface more obtuse, I do agree that this would be a reasonable nerf for how much it would slow them down without actually otherwise impeding them.

**Comment by Suicidalpickles** [comment]
i ded

**Comment by necromanceranne** [comment]
I love to reload during a battle! There's nothing like the feeling of slamming a long silver bullet into a well greased chamber.

**Comment by Ty-the-Smonk** [comment]
tbh make autoloaders a antag only item

**Comment by Ziiro** [comment]
Then at least give it one autoloader for baseline purchase. 13TC for a manually loaded gun is horseshit and you know it

**Comment by KetasDotepasto** [comment]
I agree with @Ziiro , It should be possible to buy a speedloader without bullets, which then can have bullets loaded in individually.

**Comment by Tlaltecuhtli** [comment]
clunky mechanics isnt a good way to balance tbh

**Comment by SkeletalElite** [comment]
> Then at least give it one speedloader for baseline purchase. 13TC for a manually loaded gun is horseshit and you know it

This gun crits in 3 shots. Meaning one magazine is enough to kill 2 people if you don't miss. I think having a nice long reload time if you don't choose to buy a speed loader (which you can get by buying ammo in the uplink) is fair. And even if you get the speed loader, you still have to load up the speed loader in between fights, this just means you can kill more people before you need to take a moment in between fights to prepare for the next one. This really only gets rid of the mass murder bone potential of the revolver since you cant just fill your bag with paper sacks full of speed loaders and have 50 instance reloads in your backpack to kill the entire station with.

**Comment by imsxz** [comment]
If this PR goes through, the 13tc revolver will amount to a normal sized combat shotgun assuming you don’t buy the speed loader. I think a lot of people can vouch for the capability of combat shotgun+slugs. Using that as a baseline, the combat shotgun is huge sized and only stored on back, hand, or in bag of holding. Revolver fits in bag/belt/armor slot which makes it a lot more convenient to use than a combat shotgun.

If you get a speed loader, you can click a pile of .357 casings to instantly put all of them into the speed loader, and click the revolver with the loader to instantly reload it, alllowing for an extremely deadly and convenient to use weapon.

I don’t think this change will gut the revolver in any way, people are already used to the clunky ass shotgun loading which is what loading single revolver shells will be exactly like.

I would like to note that you can get 357 speedloaders from the vault safe on metastation(easy to crack, the wiki guide is up to date and it’s what I used to learn it). I think there’s some speedloaders in some space ruins as well but it is possible that I am entirely misremembering.

**Comment by Ziiro** [comment]
>clunky mechanics isnt a good way to balance tbh

This actually a problem as well. If you're going to bring out the combat shotgun as a direct balance comparison, may I remind you that ss13 runs some pretty hardcore pixel perfect clicking, and compare the size of a shell to the size of a bullet.

Also I can totally forsee someone(myself) printing a shitload of bullets and then accidentally putting their hard-purchased speedloader into the autolathe. Whoops!

I understand your reasoning, but I think you are discounting the potential sources if you are going to think that a 357 should be as hard to handle as a shotgun. Any of the shotguns can come from security, cargo, etc. a 357 requires that you spend a fair amount of TC in order to do so.

**Comment by ExcessiveUseOfCobblestone** [comment]
Why shouldn't that be considered in terms of pricing though?

You not only pay for the REALLY STRONG WEAPON, you also pay for the fact that it doesn't require stealing/interacting with people that could prematurely thwart whatever plan you had in mind.

**Comment by SkeletalElite** [comment]
> > clunky mechanics isnt a good way to balance tbh
> 
> This actually a problem as well. If you're going to bring out the combat shotgun as a direct balance comparison, may I remind you that ss13 runs some pretty hardcore pixel perfect clicking, and compare the size of a shell to the size of a bullet.
> 
> Also I can totally forsee someone(myself) printing a shitload of bullets and then accidentally putting their hard-purchased speedloader into the autolathe. Whoops!
> 
> I understand your reasoning, but I think you are discounting the potential sources if you are going to think that a 357 should be as hard to handle as a shotgun. Any of the shotguns can come from security, cargo, etc. a 357 requires that you spend a fair amount of TC in order to do so.

If you go the extra mile and buy a speed loader you can drop the bullets on hte floor and click them with the loader in order to load them into the speed loader.

**Comment by ExcessiveUseOfCobblestone** [comment]
you could just alt click with empty hand then switch and click one of the bullets with loader

**Comment by necromanceranne** [comment]
While I was mostly joking with imsxz when talking about it, but they brought up garbage bags in the belt slot to carry bullets and that is actually fairly logical. Shift+E in the off hand then clicking lets you load a shell from the trash bag into the gun faster than doing inventory hopping.

**Comment by Tlaltecuhtli** [comment]
garbage bag + macro to shift+e pixel click

**Comment by actioninja** [comment]
conflict

**Comment by imsxz** [comment]
You don’t have to pixel click if you are clicking inventory slots. before I knew about shift e, if have shotgun shells in a box and id put shotgun on my exosuit storage for easy speed loading. You can click anywhere in the inventory square to click the item.

That’s how I’d go about using revolvers with the change

**Comment by necromanceranne** [comment]
Also makes revolvers more fun if you were to go on a shooting spree. Periods of vulnerability unless you are fast enough to reload mid fight.

**Pull request merged**
