### PR TITLE
Changes emergency toolbox's loot slightly.

### PR DESCRIPTION
**Pull request by GuillaumePrata**
## About The Pull Request
Removes the Mini extinguisher from the emergency toolboxes, swaps the crowbar for the medium sized version and adds a medium sized wrench too.

Utility fire closets get a medium crowbar too, as much as it is funny to calmly sit trapped behind firelocks in the middle of a plasma fire wearing the firesuit you got from the closet... it is the most logical place for an emergency crowbar...

## Why It's Good For The Game

The emergency toolbox (often spawn inside the blue O2 closets) is almost completely useless if you seek it mid emergency as people just loot half of it's useful content 2 minutes into the shift. Free crowbar in a box for the first person that finds it, free pocket slips if people wants it with the mini extinguisher.

So the idea of this PR is to improve it for emergency and nerf it's free tool status with some small changes:

1. The pocket crowbar is swapped for a medium sized one, it works faster and hits harder but if you want to carry a crowbar with you all shift it is more viable to ask cargo/eng to print you one, buy it at the vendor or loot the few ones that are map spawns.
2. The mini extinguisher is removed, it was basically useless in an emergency as extinguishers are on most hallways and O2 closets are often side by side with firefighting closets. It was mostly used as a pocket rechargeable slip.
3. Adding a medium sized version of a wrench to it, same goal as the crowbar with being something that has a more user friendly version if you ask at cargo but it also opens up for more mobility in emergencies as you can now deconstruct more obstacles, move some machinery around, deconstruct girders/tables instead of beating them, etc.

Toolboxes can carry medium sized items now so it is a good time to give them some medium sized items.

Utility fire closets get a crowbar too as that helps with the idea of a crowbar being in a consistent place when you need it mid emergency, hopefully another step to cut on players feeling like they need a pocket crowbar every shift.

Also if you have ideas of any other item that could be added following this goal, please tell me.

## Changelog

:cl: Guillaume Prata
balance: Emergency toolboxes loot was swapped around. The mini extinguisher and pocket crowbar got changed for medium sized versions of the crowbar and a wrench.
balance: Utility fire closets also get a medium sized crowbar to go along with it's fire fighting gear.
/:cl:

### CODE REVIEW

**Comment by VladinXXV** [comment]
Emergency toolboxes are just about the only way I can think of getting the red-handle crowbar. The speed of a crowbar makes very little difference in an emergency, as without nearly every other tool, the only thing it'll do for you is open firelocks and depowered airlocks, which happens instantly. Leave the red crowbar.

**Comment by Shadowflame909** [comment]
>The emergency toolbox (often spawn inside the blue lockers) is almost completely useless if you seek it mid emergency as people just loot half of it's useful content 2 minutes into the shift. Free crowbar for the first person that finds it, free pocket slips if people wants it with the mini extinguisher.

This is not true. It spawns in a firefighter locker for a reason. If its looted, that means its being used for its intended purpose. Even if its later in the round. 

This PR just makes plasma floods more deadly if you can't extinguish yourself nor free yourself. I don't see how a wrench would be useful in such a situation. If your still set on replacing the fire-extinguisher. Then replace it with some sort of burn neutralizer like an oxandrolone pill or tomato juice. Or a bucket full of water.. But that can be used to slip people too. So I still think its pointless to remove it.

**Comment by san7890** [comment]
What good is a wrench in an emergency? I read and saw that you were thinking about disassembling girders and beating tables (which you can do with a crowbar), but in a real, IC-based emergency: would anyone logically think "I'm trapped in a room with a fire/depressurization! Let's take apart the walls!"

**Comment by Fikou** [comment]
> The mini extinguisher is removed, it was basically useless in an emergency as extinguishers are on most hallways and blue lockers are often side by side with firefighting lockers. It was mostly used as a pocket rechargeable slip.

have u ever played on icebox

**Comment by GuillaumePrata** [comment]
> have u ever played on icebox

If you mean that Icebox doesn't have enough red lockers/wall extinguishers that is a map issue that shouldn't be patched with a 40% chance of a mini extinguisher inside an O2 locker.

**Comment by ATH1909** [comment]
>:(

**Comment by ATH1909** [comment]
I have an irrational attachment to red crowbars, please don't take them from me.

**Comment by ATH1909** [comment]
> The emergency toolbox (often spawn inside the blue lockers) is almost completely useless if you seek it mid emergency as people just loot half of it's useful content 2 minutes into the shift. Free crowbar in a box for the first person that finds it, free pocket slips if people wants it with the mini extinguisher.

> The mini extinguisher is removed, it was basically useless in an emergency as extinguishers are on most hallways and blue lockers are often side by side with firefighting lockers. It was mostly used as a pocket rechargeable slip.

If the mini extinguisher is "redundant with extinguishers in most hallways", why do you care that people are taking them?

**Comment by SinfulBliss** [comment]
No one is going to carry around an entire toolbox around in an emergency, even if it has all the useful emergency items in it. The issue being if it's an actual emergency then you are going to be trapped somewhere, and if there's no red toolbox you are simply boned.

People will still loot the crowbars from them, and put them in their bag if they don't fit in their box. Or if there are pocket-sized ones in cargo and elsewhere, they'll opt for these instead. Crowbars are just too essential to be walking around without them.

**Comment by GuillaumePrata** [comment]
> People will still loot the crowbars from them, and put them in their bag if they don't fit in their box. Or if there are pocket-sized ones in cargo and elsewhere, they'll opt for these instead. Crowbars are just too essential to be walking around without them.

People opting for the pocket sized version is the goal of the PR, if they want to carry the medium sized one for one reason or another they can still do that too.

> I think these toolboxes serve their intended purpose. If you are in a pinch and need a crowbar, but forgot to grab one earlier, you have them scattered around the map in lockers.

And that is exactly the goal of the PR, if you are in a pinch it is way more likely for the crowbar to be there waiting to save your life instead of being inside the box of a random that walked by the locker 2 minutes into the shift.

**Comment by Slurge00** [comment]
this is the worst pr ive ever seen

**Comment by ATH1909** [comment]
idea here: what if, instead of changing the contents of red toolboxes, we just added large crowbars as a 100% spawn in red firefighting lockers? that would satisfy the issues you've brought up here (and do so more consistently than your current solution), keep the red toolbox enjoyers happy, and make sense lore-wise (of course the firefighting locker would have a crowbar, firelocks close down when there's a fire).

**Comment by Shadowflame909** [comment]
having some sort of crowbar remain is cool

But that fire extinguisher.. That plasma flood damage buff is crazy. Especially for new arrivals.

A special snowflake version of the mini fire extinguisher that cant be dumped would work. But the issue is really just a simple slip that isnt even a hard stun, just a slowdown. So why put in the effort?

**Comment by GuillaumePrata** [comment]
> A special snowflake version of the mini fire extinguisher that cant be dumped would work. But the issue is really just a simple slip that isnt even a hard stun, just a slowdown. So why put in the effort?

Even a no slip mini extinguisher would still be taken by people, a medium sized extinguisher could work and won't be looted unless it is an emergency but extinguishers are almost everywhere and I don't think O2 closers really needs to be equipped to deal with fire.

**Comment by realthomas69** [comment]
Typo

**Comment by ShizCalev** [comment]
image
no thanks.

**Pull request closed without merging**
