### PR TITLE
Refactors projectile hitscan

### PR DESCRIPTION
**Pull request by silicons**
Moves beam rifle snowflake code up to projectile level for a proper hitscan system.

:cl:
rscadd: Chameleon laser guns now have a special firing mode, activated by using them in hand! Only certain gun disguises will allow this to work!
/:cl:
# THIS DOES NOT CHANGE THE GAME. NOTHING NEW EXCEPT FOR CHAMELEON LASER GUNS (WHICH DONT DO DAMAGE) WHICH WILL BE TOGGLEABLE WILL BE GETTING HITSCAN.

- [x] Add muzzle effects
- [x] Add impact effects
- [x] Toggleable hitscan chameleon lasers
- [x] Figure out why the fuck the tracers are sometimes one tile off.

### CODE REVIEW

**Comment by Cyberboss** [comment]
>Hitscan of any kind

:-1:

**Comment by MMMiracles** [comment]
counter strike 13

**Comment by ChangelingRain** [comment]
we need hitscan so I can give wizards ray of frost

**Comment by arsserpentarium** [comment]
Honestly,maybe it is fun to avoid lasers like Neo. But lasers basically hitscan. You can't avoid beam with speed of light.

**Comment by Qustinnus** [comment]
hitscan weaponry is shit especially in a game where avoiding projectiles is a big thing

**Comment by kevinz000** [comment]
@Qustinnus yeah and this is so the existing one has better /code/.

**Comment by yorii** [comment]
@kevinz000 you literally just clickbaited people, you should just have called it "fixes beam rifle"

**Comment by Bawhoppen** [comment]
You're getting downvoted because of slippery slope

**Comment by kevinz000** [comment]
ok less clickbait

**Comment by banthebantz** [comment]
>downvotes
hitscan is already in dummies

**Comment by AnturK** [comment]
Conflicts. Also was this testmerged.

**Pull request merged**
