### PR TITLE
The Hierophant is a little less chaotic and murdery on average

### PR DESCRIPTION
**Pull request by ChangelingRain**
:cl: Joan
tweak: The Hierophant is a little less chaotic and murdery on average.
/:cl:

I balanced this thing on ergovisavi, who is too good and should not be balanced around.

### CODE REVIEW

**Comment by ShizCalev** [comment]
Balancing during freeze, reeeeee #28223

**Comment by Repukan** [comment]
Hugbox.

Freeze.

**Comment by Kromgar** [comment]
You might actually see hierophant kills now

**Comment by octareenroon91** [comment]
>## Things that will be accepted during this freeze:
>>Improvements to civilian systems or gameplay

"Balancing during freeze, reeeeee"

**Comment by ShizCalev** [comment]
@octareenroon91 /s = sarcasm

**Comment by factoryman942** [comment]
If we makr megafauna all have  1 hp does that improve civilian gameplay

**Comment by Bawhoppen** [comment]
This is a clear balance change, it should be closed considering the freeze

**Comment by ExcessiveUseOfCobblestone** [comment]
I can kill hiero just fine.

Instead of nerfing the boss to make it in line with it's loot, why not buff the loot to make it in line with the boss difficulty :^)))))

**Comment by ChangelingRain** [comment]
I don't think the resulting item would be very fair, do you?

**Comment by Kromgar** [comment]
Killing the hierophant should give you a sphere of annihilation

**Comment by Iamgoofball** [comment]
@Bawhoppen it's not sec vs antag balance, it's civilian job balance

**Comment by kevinz000** [comment]
hugbox

**Comment by kevinz000** [comment]
if anything buff the rewards lmao

**Pull request merged**
