### PR TITLE
[FIX] Fixed Power Cable Layer Define [MDB IGNORE] [ICDB IGNORE]

### PR DESCRIPTION
**Pull request by ORCACommander**
why was cable layer 3 being put on cable layer 4?

## About The Pull Request

I was doing some mapping and I saw by default Power Cable (Layer 3) was defaulting to cable_layer 4.
traced the root and found the root of the problem in this define. Changing to level 3

## Why It's Good For The Game

Its not the most world shaking of edits. Should not affect much of anything unless someone has a custom overwrite

## Changelog

:cl:
fix: Blue Cables now properly now layer 3 like they were intended
/:cl:

### CODE REVIEW

**Review by Rohesie — CHANGES_REQUESTED** [review]
These values are bitflags, as you can see in `/obj/structure/cable/multilayer/update_icon()` and other places, and this change would break things.

You might want to change them to something like this, for clarity:
```dm
#define CABLE_LAYER_1 (1<<0)
#define CABLE_LAYER_2 (1<<1)
#define CABLE_LAYER_3 (1<<2)
```

**Comment by ORCACommander** [comment]
bit shifting... for clarity... right....
I'll see if i can track down any conflicts next week

**Comment by Rohesie** [comment]
In case you're not aware, these bitshifts are converted to 1, 2 and 4 by the pre-processor.
At first they may sound a bit more cryptic, but if I ask you what's the value of the 15th bitflag I'm rather confident you won't know it without using a calculator or similar. Now, `(1<<14)` is easier to remember than `16384`.

Here you have a little more info on bitflags: https://tgstation13.org/wiki/Binary_flags#The_idea_behind_bitflags

**Comment by ORCACommander** [comment]
image
image
Everything is connecting properly, power nets are propagating as designed. at least with the /connected varient

Only thing I had to do was remove Machine_Layer=Null
Every power creator and consumer uses machine layer 1 so i have no idea why cable layer 1 and 3 were nullified but the result was they will not connect to creators or consumers

Although now terminals are not offset properly on cable layers and 2...

I still don't see the point of using bit shifting here. it looks like it was originally set up for it but was never fully implemented. Still it is logically wrong for something called Cable Layer 3 to be in reality cable layer 4

the connect and disconnect is malfunctioning though. Currently when i place the hub, it auto connects L2 and L3 but not L1

the radial menu does not seem to be updating the layer list properly either

meta station edits will be deleted after debug

**Comment by ORCACommander** [comment]
I'm gonna revisit this after https://github.com/tgstation/tgstation/pull/62750 is done

**Pull request closed without merging**
