### PR TITLE
Rearranges mining vendor items and code, adds conscription kit

### PR DESCRIPTION
**Pull request by 81Denton**
:cl: Denton
tweak: Rearranged the mining vendor items by price and item group.
tweak: In order to promote back-breaking physical labor, Nanotrasen has additionally made conscription kits available at mining equipment vendors.
/:cl:

A) Rearranged mining vendor items by price, item group and fixed the ugly tabs/spaces. 

B) I made the mining conscription kit available at the vending machine for 1000pts. 

Why? Having the kit available only as a voucher limits its use to metafriends. This shows in the ~1.9% pick rate in January.

Making it available at the vendor lets miners help out members of other departments that want to go mining midround, instead of just hogging points as usual.
If anyone has a better idea about the kit price, let me know.

### CODE REVIEW

**Comment by Repukan** [comment]
If miners want to help someone they can ask the HoP to give that person access.

We shouldn't gate access to mining & Cargo behind points. Either make it more expensive or take it behind the barn and shoot it like the crippled idea it is

**Comment by PsyCommando** [comment]
Maybe allowing the HoP or QM to print vouchers for new miners would be a better idea than adding a kit for mining points in the vending machine? Honestly, usually when new miners come, we can expect that the other miners are dead, or left to do their own things imo.

**Comment by Tlaltecuhtli** [comment]
qm can already make miner conscription kits (there is a crate that has everything except the miner access id)

**Comment by 81Denton** [comment]
>qm can already make miner conscription kits (there is a crate that has everything except the miner access id)

Darn, I did not know that. I'll drop the conscription kit part of this PR if maintainers think that it would be a bad idea.

**Comment by vuonojenmustaturska** [comment]
Let's try it and see what happens

**Pull request merged**
