### PR TITLE
Adds several new back slot icons for guns, while also updating two existing ones.

### LINKED ISSUE #30900: Surplus Rifle has no on back sprite.
/obj/item/gun/ballistic/automatic/surplus

### LINKED ISSUE #43517: New gun sprites still use the old back icon when being worn
Title, new gun sprites brought in by #41804 and #43347 didn't include a change to the sprites when having a shotgun holstered on your back.
Forgoteverything
Combat shotgun on the left, riot shotgun in the middle, regular shotgun shown on the right for contrast.

-New combat shotgun doesn't match up with the old combat shotgun icon that has shells attached to it.
-Riot shotgun has wood parts that aren't part of the riot shotgun's old back sprite.

_(Presumably too late noticing this when those PRs were open, told to make this issue report instead.)_

### LINKED ISSUE #47882: PARTICLE BEAM RIFLE has no back sprite
Not sure if I'd call it a bug, but someone should probably make one.

image

### PR DESCRIPTION
**Pull request by Firecage**
## About The Pull Request
This PR adds icons for the Particle Acceleration Rifle(Beam Rifle) for when it is worn on someone's back. Additionally it also updates the back icons for the combat and riot shotgun to match their current main icons of them. Be warned, in both cases they are coder-sprites, so they may cause subjects to experience nausea, blindness, and lizardness.

Additionally this removes the separate bit of update_icon() code which beam rifles had, which I assume dated from before energy gun icons in general were updated to be more sane, since it in practice did nothing different than would be done with the update_icon() on energy guns itself. Everything still appears to work normally in regards to the icon updating, which were only the charged and empty icons really.

Update: The PR now also adds a back slot icon for the compact combat shotgun.

Update 2: The PR now also adds a back slot icon for the surplus rifle.

Update 3: Added back slot icons for the Mosin Nagant. Additionally it can now also be worn on the back. The only reason it could not be, was because it lacked an icon for being worn on the back, as per the now deleted comment which was next to its slot flags var.

Fixes #43517
Fixes #47882 
Fixes #30900

Please note, due to an issue which already exists with how the back icons of energy guns are handled, the beam rifle/particle rifle will appear to be fully charged on the back when worn there. The same issue happens in regards to Ion rifles, pulse rifles, and lasercannons(actually unsure if they use the lasercannon back icon at that). And I highly doubt I would be able to fix that one, so I will probably make an issue report about it later unless someone else does first.

Riot Shotgun:
image
Combat Shotgun:
image
Compact Combat Shotgun:
image
Particle Acceleration Rifle/Beam Rifle(empty sprite currently non-functional)
image
image
Surplus Rifle: (mag sprite currently non functional due to issues with gun back sprites not updating. Same is true of the existing Sniper mag icon)
image
image
Mosin Nagant:
image

## Why It's Good For The Game
For balance reasons, guns which goes on backs being invisible is bad.

## Changelog
:cl:
fix: Adds back slot icons for the Particle Acceleration Rifle, Surplus Rifle, Mosin Nagant(which can now be worn on the back as well), and Compact Combat Shotgun. Also updates the back slot icons for the Riot Shotgun and Combat Shotgun.
/:cl:

### CODE REVIEW

**Comment by TheVekter** [comment]
>No screenshot

**Comment by Firecage** [comment]
Well, can't quite recall what I used last time to put the images on github of icons.

**Comment by Couls** [comment]
diff bot will show the sprites added
image
image
image
image

**Comment by Firecage** [comment]
Thanks @Couls

**Comment by Quartich** [comment]
> diff bot will show the sprites added
 Yeah but they're smol

**Comment by Tlaltecuhtli** [comment]
can you add one for mosin nagat and give it a on back slot? it doesnt make sense that you cant wear it on back

**Comment by Firecage** [comment]
@Tlaltecuhtli Spriting these were already agony since I ain't a spriter, and they are but codersprites

**Pull request merged**
