### PR TITLE
Replaces the black-and-red spacesuit on the infiltrator with a normal syndicate red fatsuit

### PR DESCRIPTION
**Pull request by ghost**
:cl:
tweak: switched the type of the space suit on the syndicate shuttle
/:cl:

high effort important pr that really adds to the immersion of the game

### CODE REVIEW

**Comment by Shadowflame909** [comment]
Is this another bait PR to make people salty like your two other syndicate PR's? Please give me an actual answer. I do not dig lies!

**Comment by iskyp** [comment]
@Shadowflame909 yes it's an epic bait pr but this time it's actual bikeshed

**Comment by Shadowflame909** [comment]
Ok thanks for being honest at least. Stop memeing on my github though!! You will feel the anger of goof.

**Comment by iskyp** [comment]
never

**Comment by lordsaladin** [comment]
@iskyp add some new meme uplink items.

**Comment by Shadowflame909** [comment]
WHAT GOING ON WHY ARE WE MERGING BAIT PRS. AHHHHHH

**Pull request merged**
