### PR TITLE
Fixes wheelchairs [TESTMERGE ME :)]

### LINKED ISSUE #41703: Those without legs can't do certain actions, even when strapped to a chair
Issue reported from  Round ID: 97693 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 512

Those without legs cannot do specific actions, even when buckled to chairs. Actions include, but are not limited to:
Using PDAs
Operating holopads
Opening/unlocking lockers
Pulling things
Stripping others, or removing handcuffs
Using specific consoles (things like comms console and gulag console)

### PR DESCRIPTION
**Pull request by 4dplanner**
## Changelog
:cl:
fix: Buckle objects can now properly specify lying angle
fix: Wheelchairs and other such vehicles let you use UIs even if your legs don't work
fix: You can now pull objects while in a wheelchair even if your legs don't work
fix: You no longer have a chance of sleeping upside down in a bed
tweak: No longer randomises lying direction a second time on fall
/:cl:

code: simplified can_stand code

fixes #41703

### CODE REVIEW

**Comment by VileBeggar** [comment]
you're a hero 4d, a hero

**Comment by 4dplanner** [comment]
please ignore that tree bit wtf

**Comment by subject217** [comment]
if you don't want to put anything in the fancy schmancy sections just remove them that's what i do

**Comment by JMoldy** [comment]
I've already been able to pull things while in a wheelchair though?

**Comment by 4dplanner** [comment]
> I've already been able to pull things while in a wheelchair though?

Were you a paraplegic, though?

**Comment by anconfuzedrock** [comment]
hey sleeping prone is a genuine issue that leads to many infant deaths each year, removing it is denying it happens, you fucking babyphobe.

**Comment by ShizCalev** [comment]
Absolutely gonna need to testmerge.

**Comment by ShizCalev** [comment]
#41703

**Comment by ShizCalev** [comment]
How's this work with buckling someone to a mob? ie a borg

**Comment by 4dplanner** [comment]
Paraplegic on a borg new meta

**Comment by MegaEmpirical** [comment]
Does this make any changes that affect those not in chairs? Being unable to use your pda or even eject your ID from your pda just because you've no legs is pretty messed up.

**Comment by 4dplanner** [comment]
No, that's a separate consideration. I agree it's a bit lame, though.

**Comment by 4dplanner** [comment]
@ExcessiveUseOfCobblestone your cutesy title removed the test merge label >:(

**Comment by 4dplanner** [comment]
Slight edit to OP with no code changes removes label

**Comment by ExcessiveUseOfCobblestone** [comment]
if you touch this PR you lose challenge

**Pull request merged**
