### PR TITLE
Adds open and close sounds for crates and closets

### PR DESCRIPTION
**Pull request by nicbn**
We've been using the generic machine click for years.

[Cardboard box](https://raw.githubusercontent.com/nicbn/tgstation/033cf655f1238890010c3d82ae054328b430bc0e/sound/machines/cardboard_box.ogg)
[Open crate](https://raw.githubusercontent.com/nicbn/tgstation/033cf655f1238890010c3d82ae054328b430bc0e/sound/machines/crate_open.ogg)
[Close crate](https://raw.githubusercontent.com/nicbn/tgstation/033cf655f1238890010c3d82ae054328b430bc0e/sound/machines/crate_close.ogg)
[Open closet](https://raw.githubusercontent.com/nicbn/tgstation/033cf655f1238890010c3d82ae054328b430bc0e/sound/machines/closet_open.ogg)
[Close closet](https://raw.githubusercontent.com/nicbn/tgstation/033cf655f1238890010c3d82ae054328b430bc0e/sound/machines/closet_close.ogg)
[Open wooden closet](https://raw.githubusercontent.com/nicbn/tgstation/033cf655f1238890010c3d82ae054328b430bc0e/sound/machines/wooden_closet_open.ogg)
[Close wooden closet](https://raw.githubusercontent.com/nicbn/tgstation/033cf655f1238890010c3d82ae054328b430bc0e/sound/machines/wooden_closet_close.ogg)

## Changelog
:cl:
soundadd: New sounds for crates and closets.
/:cl:

### CODE REVIEW

**Comment by nicbn** [comment]
That change somehow broke all closets and crates by runtiming them. Isn't tg code beautiful?

**Comment by actioninja** [comment]
Where did you get these sounds from?

**Comment by nicbn** [comment]
I've got them all from freesound.org, all are CC0 except the one I credited, which is CC-BY. I've cropped and editted some of the sounds.

**Comment by coiax** [comment]
What about coffins? Can they use the wooden crate noises as well?

**Comment by nicbn** [comment]
They already do

**Review by actioninja — CHANGES_REQUESTED** [review]
use the normalize effect on audacity with the default -1 db settings on all these instead of just playing them at 100 volume

**Pull request merged**
