### PR TITLE
Revert "Fixed 2: Electric boogalo, gives lusty xenomorph maid reskin to DONORS (are you happy now)"

### PR DESCRIPTION
**Pull request by Niknakflak**
Reverts tgstation/tgstation#18545

Corruption of champion fetish shit please go
I'm sure that design lead @KorPhaeron and @Iamgoofball agree with me.  This is a serious revert and a serious debate that needs to happen.

### CODE REVIEW

**Comment by Archie700** [comment]
QUICKMERGE THIS

**Comment by Iamgoofball** [comment]
ONLY TIME I WILL AGREE WITH NIKNAK

**Comment by Militaires** [comment]
saddle up soldier, it's ground attack ;)

**Comment by optimumtact** [comment]
no

**Comment by WJohn** [comment]
The memes are now officially protected by TG's maintainers.

God bless america.

**Pull request closed without merging**
