### PR TITLE
Add support for specific sound channels and stopping them

### PR DESCRIPTION
**Pull request by Cyberboss**
@Robustin needs this for his jukebox in #25247

### CODE REVIEW

**Comment by Iamgoofball** [comment]
Please make Bicycles use this

**Comment by Dorsisdwarf** [comment]
I wonder if this could be used to fix the irritating bug where too many sounds at once cause horrible stuttering of admin music

**Comment by Robustin** [comment]
Excellent

**Comment by Shadowlight213** [comment]
@Dorsisdwarf I was under the impression that the stuttering was caused by one of byond's features where sounds would attempt to stay synchronized across all clients listening to it.
I might be wrong though.

**Pull request merged**
