### PR TITLE
voice of god is now affected by ear protection, its vomit command no longer stuns, fixes no big text

### PR DESCRIPTION
**Pull request by Fikou**
## About The Pull Request

voice of god is now affected by ear protection like the natural one by xenos or borgs or the one from security bowman headsets, so with bowmans commands will be half as effective, be it the bad ones like die or the good ones like heal
vomit is no longer a stun, it is hardcoded to be 8 seconds so i couldnt really rebalance it, cooldown reduced back to 30 seconds
from the code side: the commands are completely recoded, instead of the commands running a look through every victim, the main voice of god does that and calls the command on the target
in the vog refactor, accidentally the span function was broken, now it only changes your spans if youre a cultist, instead of always changing your spans to an empty list. since its fixed the cooldown for text messages has been heightened back to 10 seconds, like it used to be

## Why It's Good For The Game

ear protection: an aoe stun on the entire security team is bad and it makes sense for it to be protected against
vomit: an 8 second stun is kinda way too long, you literally need to be a cultist or chaplain to reach that amount of stun with the STUN command

## Changelog
:cl:
balance: voice of god is now affected by ear protection, its vomit command no longer stuns
fix: fixes voice of god not giving you big colossus text
/:cl:

### CODE REVIEW

**Comment by Iamgoofball** [comment]
:-1:

Bowmans don't make you deaf, so it shouldn't block Voice of God. This is just dumb security buffing again.

**Comment by rdragan** [comment]
> 👎
> 
> Bowmans don't make you deaf, so it shouldn't block Voice of God. This is just dumb security buffing again.

VoG is used more often for validhunting than antagging. Something you would know if you'd ever play.

**Comment by Iamgoofball** [comment]
It is better to nerf Voice of God itself rather than buff security directly.

**Comment by ExcessiveUseOfCobblestone** [comment]
VoG should not be blocked by bowmans, the bowmans should ONLY be protecting from flash bangs and any other security equipment that rely on hearing (because otherwise it’s useless if security can’t use their own equipment effectively)

**Pull request closed without merging**
