### PR TITLE
Compresses and monofiys all sounds

### PR DESCRIPTION
**Pull request by MrsTonedOne**
This lowers the sound folder from 30mb to 15mb, and the rsc from 43mb to 33mb

AI vox sounds not modified because those were already optimized as far as they could go.

### CODE REVIEW

**Comment by WJohn** [comment]
Jesus man. Is there any perceivable sound quality drop?

**Comment by xxalpha** [comment]
The ambience sounds really suffer, but the rest are very okay.

**Comment by phil235** [comment]
:+1:

**Comment by Incoming5643** [comment]
maybe the title tracks/ambience should be spared

Though I know saying this means losing probably 80% of the space saved

**Comment by MrStonedOne** [comment]
ehh, if a certain file loses a lot of quality, I can always go one or two steps up for that file... Monoifying them was a good chunk of the change, but since you have to re-encode to monoify, and every re-encode is a minor drop in quality no matter what you do, there is no sense in not upping the ogg compression level as well.

**Comment by freerealestate** [comment]
But why? Was the size of the download upon the joining the server really an issue?

**Comment by Fox-McCloud** [comment]
when you have a slow connection, 33 MB vs 43 MB is quit sizeable.

It also presumably saves the server money (if they pay per GB or what not).

**Comment by Anonus** [comment]
I want a smaller download but I don't want shitty sounds, especially not the iconic AI announcement sounds that we literally can't replicate the making of.

**Comment by Fox-McCloud** [comment]
@Anonus 

Where did those come from anyway? I've been attempting to track down who made them and how, but that info is ancient.

**Comment by Anonus** [comment]
Honestly I don't know more than "nobody knows how to replicate these"
We definitely shouldn't fuck with them.

**Comment by Dorsisdwarf** [comment]
The AI sounds have already been compressed as much as possible without them getting all shitty
(It's not that we don't know how to replicate them, it's that we don't have the person who recorded them anymore, IIRC)
and are also not touched by this PR as explicitly stated above.

**Comment by Fox-McCloud** [comment]
@Dorsisdwarf 

Yes, they are--he means he hasn't touched the AI Vox files because they're already properly compressed and generated...likewise, those were made using N3X15's own little generator---people could add words any time they so desire.

What Anonus and I are referring to are the clips for "Attention, enemy communication intercepted; security level elevated", "wow, this is just like one of those Japanese animes", and "the emergency shuttle has docked with the station"....etc, and those *most definitely* were touched and it's very obvious.

**Comment by duncathan** [comment]
:-1:
Surely you can find a quality that is compressed, but still decent? You said somewhere these are all ogg quality 1; that is a very noticeable difference from what we had them at before. Try quality 5, maybe even 3?

**Comment by Iamgoofball** [comment]
:-1: on the grounds that we really shouldn't be supporting people on dialup anymore

for fucks sake it's 2015 get an upgrade stop running windows 98

**Comment by Giacom** [comment]
The performance is not just for the client's benefit, servers will save on bandwidth and make it less expensive to host a SS13 server. Also the less amount of people spend time downloading to join the game, more the bandwidth the server can give to clients playing to update their game and reduce lag.

**Comment by Iamgoofball** [comment]
okay that makes sense

**Comment by Anonus** [comment]
I'm not referring to the AI vox sounds, I'm referring to the sounds for meteors, malf, radiation, etc.

**Comment by CorruptComputer** [comment]
@Giacom It's not going to be enjoyable if all the sounds sound like shit. Also 10mb of bandwidth is nothing, less than a second of download time.

**Comment by Miauw62** [comment]
10 megs every time someobyd has to download resources adds up over time.
reducing the size is good, but we should make sure the quality doesn't suffer too much.

**Comment by CorruptComputer** [comment]
title1.ogg sounds horrendous. I realize that less bandwidth is good, but at this cost of quality? Also, has anyone thought of using something other than .ogg's? I could see if I could get better compression and still the same quality with different file types.

**Comment by Miauw62** [comment]
depends on what filetypes byond supports. i dont think you can play mp3s through byond, for example.

**Comment by Incoming5643** [comment]
easy access
https://raw.githubusercontent.com/MrStonedOne/-tg-station/soundcompression/sound/ambience/title1.ogg
https://raw.githubusercontent.com/MrStonedOne/-tg-station/soundcompression/sound/ambience/title2.ogg
https://raw.githubusercontent.com/MrStonedOne/-tg-station/soundcompression/sound/ambience/title3.ogg

Titles 1 and 2 sound abysmal, but strangely title 3 seems almost as decent as it does now.

**Comment by RemieRichards** [comment]
yeah jesus fuck 1 and 2 sound DISGUSTING.

**Comment by stapler2025** [comment]
is it not possible to setup resources to download from a separate server?

Can setup a 3 location anycast setup for all of..12 bucks a month.

**Comment by xxalpha** [comment]
Doubt it.

Really think we should keep the titles and ambience as they are. If we're gonna have shitty sounds we might as well not have them.

**Comment by Niknakflak** [comment]
Yea they sound awful.  I'd take shilling out more cash for the server and longer load times for non-shit sounds.

**Comment by MrStonedOne** [comment]
Ya, ok, I didn't actually test lobby sounds that much.

I'll have to look at tweaking the compression ratios later

**Comment by Fox-McCloud** [comment]
Ideally, wouldn't it be best to losslessly monofy all the sounds, see how much space is saved that way, then go about possibly reducing their size, from there?

**Comment by duncathan** [comment]
Ambience should be left stereo.

**Pull request closed without merging**
