### PR TITLE
Allows admins to cancel random events

### PR DESCRIPTION
**Pull request by Cyberboss**
untitled

### CODE REVIEW

**Comment by Repukan** [comment]
Hugbox

**Comment by Kromgar** [comment]
But why?

**Comment by Cyberboss** [comment]
Avoid meteors while meming

**Comment by Iamgoofball** [comment]
:-1: stop

**Comment by PKPenguin321** [comment]
i would love this for testing
>be on a testing server
>forget to disable random events
>catastrophic meteors RNG

😢

**Comment by Cyberboss** [comment]
@Iamgoofball If admins want to stop events now they'll just varedit `SSevents`. I'd prefer if they didn't do that

**Comment by Kyep** [comment]
Or... open up events manager and hit 'pause' on the timers.

**Pull request merged**
