### PR TITLE
Supermatter sword can now be a proper surgery tool

### PR DESCRIPTION
**Pull request by jughu**
I want you to remain calm.

### CODE REVIEW

**Comment by jughu** [comment]
Now the joke is over if this is auctally favoured for muh realism i get back on it on a proper editor

**Comment by YakumoChen** [comment]
is it even sharp? It feel like it's better just to make it a chunk of Supermatter on a handle, the sharpness isn't the point.

**Comment by jughu** [comment]
The sharpnees is to make it a valid scapel :^)

**Comment by jughu** [comment]
Ill get on this later auctallyee

**Comment by jughu** [comment]
Yeah proper editor it is... oh well sorry for the messages folks!

**Comment by kevinz000** [comment]
the only joke here is you

**Comment by jughu** [comment]
Atleast i dont break citadel by using cyberboss script wrong kevinz

**Comment by Cyberboss** [comment]
LOOOOOOOOOOOLLLLLL!!!!

**Comment by kevinz000** [comment]
Fuck X D

**Pull request closed without merging**
