### PR TITLE
Food cart

### PR DESCRIPTION
**Pull request by Lobachevskiy**
An upgrade to icecream van. Inspired by vending machines storage compartment.

Features:
- Ability to make icecream is untouched
- Added ability to store and dispense food for easy distribution, 30 is the current capacity
- Added ability to store drinking glasses and make new ones from glass (4 per sheet, so 500 glass per drinking one, same as beakers, even though drinking glasses don't explicitly have glass in them)
- Added ability to dispense stored reagents (which includes drinks) in glasses, you can also pick how much do you want to put in the glass

Possible future improvements:
- Mixing reagents (cocktails) inside the cart
- Making UI less bulky (what it currently looks like https://i.imgur.com/MBEQEEV.png)

Known issues:
- Fucking Scaredy's beef jerky won't dispense! I suspect it has something to do with \improper macro in the beginning of its name, but other items (like donk pockets and raisins) work just fine after I started sanitizing their names, before that they also fucked up. Jerky used to just disappear before sanitizing (well, actually it just wasn't showing on the list), now it shows up, but won't dispense. Could use some advise on that one.
- Github is showing up changes from my recent PR in the diff for some reason (to human.dm), that PR is already merged and I used different branch, so I've no idea why that is the case, so yeah.

Note: doesn't seem to conflict with https://github.com/tgstation/-tg-station/pull/6706

### CODE REVIEW

**Comment by Miauw62** [comment]
You should really add hotdogs so I can play CMOT Dibbler.
Op 1-jan.-2015 00:34 schreef "tkdrg" <notifications@github.com>:

**Comment by Lo6a4evskiy** [comment]
> Perhaps it would be wise to change their glass amount to 500 for consistency.

I'll look into that, but may be I'll just save that to another PR that would add glass and metal to lots of things that lack it (bottles, for instance, also don't contain glass).

Kay, so current to-do list:
- [ ] Split food cart into separate cart, which would solve both clunky interface and conflicting with goofball's PR
- [ ] May be expand functionality to produce more things like trays, forks, bottles or something like that, basically making a food autolathe (so it would include adding glass and metal to produced items)
- [ ] Add mixing functionality (right now I'm thinking of just adding some container object into contents of the cart, do tell if there's a better way)
- [ ] Ask spritebus for different sprite of the cart (if we're gonna keep them both) and for hot dogs.

**Comment by Lo6a4evskiy** [comment]
I'm a bit worried about 5k lines changed in the map. First time I ever do a map edit, I basically deleted food_cart that before just replaced the vat, put vat back into its old place and put food cart into the kitchen.

**Comment by Miauw62** [comment]
Did you use the map merger?
Op 1-jan.-2015 14:06 schreef "Lo6a4evskiy" <notifications@github.com>:

**Comment by Lo6a4evskiy** [comment]
Okay, now it's good.

**Comment by Lo6a4evskiy** [comment]
All right, should be good to merge now, unless you want to wait for further improvements listed above or new sprites.
Here's where I put it:

**Comment by pudl** [comment]
thats a terrible place to put it, move it to above the processor

**Comment by Lo6a4evskiy** [comment]
It's not shown on the screenshot, but there's a hydroponics table/windoor over there. Above that is smart fridge.

It's honestly either there, or replace the goat in freezer. Kitchen is quite cramped up.

**Comment by pudl** [comment]
move fire extinguisher to the left of dinnerware vendor, move sink right, put cart to the right of vendor

**Comment by Lo6a4evskiy** [comment]
But that would mean extinguisher is blocked by vending machine.

I could put it near extinguisher, it can be moved if extinguisher's needed. Optionally sink and extinguisher could be swapped.

**Comment by pudl** [comment]
extinguisher wouldn't be blocked by the vending machine, you would still be able to grab it fine.

**Comment by Lo6a4evskiy** [comment]
Okay, so, commits and changes kinda fucked up for some reason, presumably because I had to reset my repo. Changes are supposedly already there, so it would only add food_cart.dm and put it on a map. Alternatively I could make a separate PR without this disaster. @tkdrg

**Comment by Jalleo** [comment]
I would make a new PR

**Comment by tkdrg** [comment]
You can probably salvage this PR with some clever git magic (reset, cherry-pick and force push), but yeah, it's probably easier to make a new one.

**Pull request closed without merging**
