### PR TITLE
[WIP] no blind flicker for full blindness

### PR DESCRIPTION
**Pull request by actioninja**
## About The Pull Request

removes the stupid flickering where you can see the whole screen while blinded

## Why It's Good For The Game

This always irritated me because it lessens the entire downside of being blind.

## Changelog
:cl:
tweak: blind overlay no longer flickers
/:cl:

### CODE REVIEW

**Comment by PKPenguin321** [comment]
Is this for actual blindness or is it the thing where you're in crit

**Comment by actioninja** [comment]
I think it might actually be both.

**Comment by PKPenguin321** [comment]
It should stay for crit but be removed for blindness

**Comment by actioninja** [comment]
blindness code is so bad, but I'll try.

**Pull request closed without merging**
