### PR TITLE
You can now non-violently place people on tables

### PR DESCRIPTION
**Pull request by XDTM**
:cl: XDTM
add: You can now place people on tables on Help Intent. Doing so takes a few seconds and makes the target Rest, instead of stunning them.
/:cl:

I saw a comment about how pacifists can't place people on tables, then wondered why we don't have a nonviolent option. Here we are.

Mekhi goes _gently_ on the table.

### CODE REVIEW

**Comment by Iatots** [comment]
*pomf*
what are we gonna do on the table peppermint-chan?

**Comment by LetterN** [comment]
Violently speedmerge this

**Comment by pubby** [comment]
Is forced rest not a stupidly good stun?

**Comment by XDTM** [comment]
Potentially, but you do have to stay still to be placed on the table, and you can unrest anytime.

**Comment by pubby** [comment]
I mean, slips last ~8 seconds, and it takes only 3.5 seconds to help-intent table someone. You don't even need an aggressive grab to do it, if I'm reading the code correctly.

I would be supportive of this if it didn't use rest.

**Comment by XDTM** [comment]
You can unrest at any time manually. Rest is necessary, or you couldn't perform surgery on a braindead patient without knocking them out.

**Comment by Jalleo** [comment]
I suggest not to force rest as it can easily be a forgotten feature until someone starts abusing this somehow.

**Comment by cacogen** [comment]
Can't you buckle people to surgical tables now? Or am I misremembering that. Either way, you could just add anaesthetic to robotics if braindead surgery by pacifists really is necessary

**Comment by XDTM** [comment]
The issue is ghetto surgery, since you'd need knockout chems or to crit the target to operate, pacifist or not.

**Comment by cacogen** [comment]
What about adding a check to see if the person is braindead? If they are, they'll rest, if they aren't they'll just end up standing on the table.

**Comment by XDTM** [comment]
Oh hey that's pretth what is coded here minus the already on the table bit

**Comment by Togopalis** [comment]
Pacifists dont need the ability to table anyone.

**Comment by XDTM** [comment]
This is not for pacifists, it's more useful to ghetto surgeons and surgeons in general

**Pull request merged**
