### PR TITLE
[MDB IGNORE] Reruns the `74517` UpdatePaths script

### PR DESCRIPTION
**Pull request by Jolly-66**
## About The Pull Request
Title.

## Why It's Good For The Game
I nuked a lot of these silly var edited window panes? directional windows? (I don't know what the fuck to call them) and they keep crawling up again. I'm making a map elsewhere, updated my branch and started running the scripts only to see some /tg/ maps pop up.

No me gusta. 

## Changelog

N/A since its much smaller this time around

### CODE REVIEW

**Comment by Mothblocks** [comment]
> I nuked a lot of these silly var edited window panes? directional windows? (I don't know what the fuck to call them) and they keep crawling up again

Make a maplint or else it's always going to keep happening

**Comment by Fikou** [comment]
> > I nuked a lot of these silly var edited window panes? directional windows? (I don't know what the fuck to call them) and they keep crawling up again
> 
> Make a maplint or else it's always going to keep happening

:(

**Comment by Jolly-66** [comment]
Fikou is this why you called me on discord

**Comment by Mothblocks** [comment]
What

**Comment by Jolly-66** [comment]
Fikou being Fikou don't mind my comment

I'll work on a lint when the week comes, I'm busy with work for the weekend (and I need to figure out how to write the lint)

**Comment by Mothblocks** [comment]
The existing maplints are hopefully pretty easy to understand

**Pull request closed without merging**
