### PR TITLE
added some decals to box as well as an extra carp spawn to scare the AI and a new xeno spawn in xenobio 

### PR DESCRIPTION
**Pull request by ghost**
[Changelogs]: added some decals to box as well as an extra carp spawn to scare the AI
:cl:
add: some detail to box
add: new spawns for xenos and carp
/:cl:

[why]: paranoia runs this game, so why not freak out the AI and create a lynch mob towards the science team?

### CODE REVIEW

**Comment by deranging** [comment]
⛳️ 🏌️

**Comment by Buggy123** [comment]
mapdiffbot is dead apparently, what exactly does this do?

**Comment by deranging** [comment]
i added some dirt, cobwebs, and various gibs throughout the station(mostly in research), added a carp spawn below the AI sat, and added a xeno spawn inside the xenobio kill room

**Comment by deranging** [comment]
wait fuck didnt mean to close and comment jsut comment

**Review by ShizCalev — CHANGES_REQUESTED** [review]
Mapmerge please.

**Comment by PKPenguin321** [comment]
Remove "optional name here" from changelog

**Comment by deranging** [comment]
did it @PKPenguin321

**Comment by Jalleo** [comment]
@deranging I think something messed up your line removal is way too large. Is it in TGM format?

**Review by ShizCalev — CHANGES_REQUESTED** [review]
TGM.

**Comment by ShizCalev** [comment]
Stale, conflicted, and is non compliant with mapping standards. Feel free to reopen when it's fixed.

**Pull request closed without merging**
