### PR TITLE
Introduces DarkMatter (because people are finicky about the factuality of meme PRs)

### PR DESCRIPTION
**Pull request by swankcookie**
It makes up 90% of the universe.  Come on.

### CODE REVIEW

**Comment by PKPenguin321** [comment]
there is nothing in this

**Comment by Incoming5643** [comment]
My parity has been violated

**Comment by Cheridan** [comment]
this is more like dark matter

we can hypothesize this pr's existence based on the effect it has on matter but we can't prove anything's there

**Comment by Zilenan91** [comment]
merge immediately

**Comment by swankcookie** [comment]
It would actually be super conveniant for this to be merged, as i accidentally Pushed to my master, and PRed from it...

**Comment by Shadowlight213** [comment]
2 many meme prs.
This isn't even a get. 0/10

**Comment by Supermichael777** [comment]
your thinking dark energy. antimatter (while proven real) is relatively rare.

**Comment by Zilenan91** [comment]
Actually doesn't dark energy only make up like 30% of the universe, while dark matter makes up 65%

**Comment by duncathan** [comment]
@Zilenan91 matter and energy are equivalent so the distinction isn't really that important

**Comment by Shadowlight213** [comment]
@swankcookie actually we already have antimatter in the form of the antimatter engine.

**Comment by MrPerson** [comment]
So this is a PR that does nothing?

**Comment by Cheridan** [comment]
By making you comment, it did something.

**Comment by Razharas** [comment]
Denied

**Pull request closed without merging**
