### PR TITLE
Tactical Energy Gun/ERT Sec Officer Change

### PR DESCRIPTION
**Pull request by Steelpoint**
This PR adds a new energy gun variant to the game. The Tactical Energy Gun.

The weapon is identical to a egun in all respects save it has a stun setting which can fire up to ten stun rounds before depleting the gun.

The gun is restricted to the ERT Security Officers only. It serves as an additional perk to the role. In compensation, their additional Adv Taser is removed.

specops egun

:cl: Steelpoint
add: ERT, non-red alert, Security Response Officers spawn with a Tactical Energy Gun. This is a military variant of the Egun that, in addition to laser and disable rounds, has access to stun rounds.
/:cl:

### CODE REVIEW

**Comment by InsaneHyena** [comment]
Well, at least it's not ballistics this time.

**Comment by banthebantz** [comment]
tacticool

**Comment by Steelpoint** [comment]
This is more aimed at buffing the Sec Response Officer, since every single ERT Officer spawns with a Energy Gun, this diminishes the Sec role in that he only really has cuffs and a riot sheild as a perk.

**Comment by Armhulen** [comment]
I like this pr.

**Comment by BeeSting12** [comment]
So basically the HoS laser

**Comment by Armhulen** [comment]
Yes

**Comment by Steelpoint** [comment]
A better version, this has ten stun rounds whereas the HoS laser only has five.

My lore reasoning is that the HoS's Laser is a first prototype of a gun that will eventually be able to recharge in the field, whereas the Spec Ops gun is a older model based on the cheaper to make Energy Gun series.

**Comment by banthebantz** [comment]
make it tacticool looking with a bunch of attachments please

**Comment by Steelpoint** [comment]
I'm no spriter. I can make it look a bit different tho.

**Comment by Steelpoint** [comment]
Here's my first alt sprite attempt, I do think it should look a little bit different but I want to ensure its a good sprite.

tacticool

**Comment by banthebantz** [comment]
looks nice, maybe make it start with a seclite attached as well

**Comment by Steelpoint** [comment]
With seclite

tacticool

**Comment by Steelpoint** [comment]
Paging @WJohn for sprite opinions.

**Comment by cebutris** [comment]
It needs a scope, a bayonet, a flashlight, laser sights, a bipod, a scope ontop of the scope, a bipod for the bayonet, and a forward grip.

**Comment by Steelpoint** [comment]
Here's a side by side comparison of a standard Egun and the sprite I made. I've also made a slight edit to the MOB sprites to put a scope on it, but I've only done it for one fire mode as I don't want to do them all if I'm going to not use the sprites in the end.

tacticool2

**Comment by banthebantz** [comment]
http://vignette2.wikia.nocookie.net/kweapons/images/0/03/1333065417378.jpg/revision/latest?cb=20120406093313

**Comment by GunHog** [comment]
Use the AusOps sprites from the failed Guncrafting PR!

**Comment by Steelpoint** [comment]
Only issue in using AusOps sprites is how its not consistant looking with the regular Egun sprites.

**Comment by GunHog** [comment]
Who cares? It can be a 'unique' gun. It looks cooler, it does not have to look like a regular E-gun! Just rename it!

**Comment by Steelpoint** [comment]
Here's a quick one I slapped down.

gun1

**Comment by Steelpoint** [comment]
Second.

gun2

**Comment by Steelpoint** [comment]
Or even attachments.

gun3

Its got quite a bit of customization.

**Comment by GunHog** [comment]
Needs a barrel.

**Comment by banthebantz** [comment]
add a barrel pls

**Comment by cebutris** [comment]
Yeah, that part at the top looks dumb without a barrel

**Comment by Bawhoppen** [comment]
How about you give it a less terrible name

**Comment by Steelpoint** [comment]
Version with the barrel, most of which is hidden but I think the end improves the look.

gun4

**Comment by Steelpoint** [comment]
In terms of a name I'm open to suggestions.

Here is what the three base Laser weapons would look like, before adding attachments and respriting the colour. Which one do you prefer people?

guncollection

Of course these are all using the same stock, there's a whole bunch of stocks to use.

stock

**Comment by GunHog** [comment]
I prefer the middle one!

**Comment by Steelpoint** [comment]
Ok, here are the variations of the middle version, using a preferred stock.

Base Model | Model + Foregrip | Model + Sights | Model + Grip + Sights
guncollection2

**Comment by Armhulen** [comment]
Don't like all these weird meh sprites, the egun with a taser setting is much enough

**Comment by GunHog** [comment]
I prefer B!

**Comment by Armhulen** [comment]
I prefer op sprites!

**Comment by Steelpoint** [comment]
I think Ausops energy gun sprites show a more accurate idea of how energy guns would be made to be used by Humans.

I'll wait for more people to comment on the sprites before I commit. Currently I am still using the sprite in the OP.

This will likely be the Ausops sprite I'll use if people want it over the original sprites in the OP.
finalsprite

**Comment by Bawhoppen** [comment]
wtf are you doing steelpoint, just use normal ass sprites

**Comment by Bawhoppen** [comment]
this will never get merged if you mess around with too much at once, just take your victory with the actual gun addition itself

**Comment by Steelpoint** [comment]
I'm entertaining suggestions to alter the sprite, the PR has not changed at all since I opened the PR.

**Comment by GunHog** [comment]
What is wrong with the new sprite? Just rename the thing and it would not HAVE to be just a plain energy gun.

**Comment by RemieRichards** [comment]
just call it a "Battle Energy Gun" if you're making it unique.

**Comment by GunHog** [comment]
How about "Combat" or "Tactical"? "Battle" seems to only go well with "Rifle", in my opinion.

**Comment by RemieRichards** [comment]
combat is just another word for battle really.
and tactical is a meme.

**Comment by Steelpoint** [comment]
I'll stick with the current sprite for now, if I want to add a new one I'll do that in a separate PR where the sprite can get the full attention.

**Comment by banthebantz** [comment]
Battle is only allowed for the battle rifle haloes ok

**Comment by GunHog** [comment]
>Battle is only allowed for the battle rifle haloes ok

Heh, that is exactly what I was referencing :stuck_out_tongue_closed_eyes:

**Comment by Steelpoint** [comment]
Battle Rifle would fit more with a weapon that deals more damage per shot but has less ammo overall.

**Comment by GunHog** [comment]
I am saying to NOT use it! I am saying you should use "Combat" or "Tactical". And RemRem, even though "Battle" and "Combat" are synonymous, "Combat" just sounds cooler!

**Comment by Steelpoint** [comment]
I'll rename it to Tactical Energy Gun.

**Comment by GunHog** [comment]
Steelpoint, in the event that you 'forget' to PR the sprite if this is merged, let me have a copy of the dmi so I can PR it about two weeks after.

**Comment by Steelpoint** [comment]
I won't forget I can assure you.

In the case I do, I simply took the sprites from gun-hogs 4th guncrafting attempt.

**Comment by GunHog** [comment]
I never made guncrafting, you Metal-Plated Goof, Iamgoofball did and Ma44 tried to take over for him!

**Comment by Steelpoint** [comment]
Well I posted the image in my above post.

**Comment by GunHog** [comment]
Do you have the base one without the mode overlay?

**Comment by Steelpoint** [comment]
I was planning to make it have four pips not five.

coolgun2ov

**Comment by Armhulen** [comment]
yay

**Comment by Steelpoint** [comment]
Excellent.

I'll be posting a PR in a day or so that includes my proposed sprites for the tac energy gun.

**Pull request merged**
