### PR TITLE
Pod shuttle -- Actually tested and working edition

### PR DESCRIPTION
**Pull request by FloranOtten**
## About The Pull Request
Adds the Pod shuttle, an Admin spawned shuttle consisting of two large escape pods. 

## Why It's Good For The Game
This shuttle is perfect for punishing the entire crew, or making them battle to the death over who gets a seat. 

## Changelog
:cl:
add: Added the Pod Shuttle
/:cl:

Tested this time. ~~If anyone knows how to fix the flying sideways part, do tell. I figure flying sideways is not a big issue, as it's only aestethic and an already existing shuttle suffers the same issues.~~

### CODE REVIEW

**Comment by SouDescolado** [comment]
Please add screenshots

**Comment by FloranOtten** [comment]
You can see the map in the mapdiff, under the 'new' catagory in the emergency_pod map.

**Comment by dr-bee** [comment]
Can this replace Oh Hi Daniel? It does the same job without being a shitty reference to a bad meme movie.

**Comment by FloranOtten** [comment]
This seats less than Oh hi, daniel.

**Comment by ExcessiveUseOfCobblestone** [comment]
This should be fine to add to the game (not just adminery) tbh.

**Comment by Shapsy** [comment]
Keep it admin only if you have to add it, it's blatant grief even more strongly than most of the meme shuttles

**Review by SpaceManiac — APPROVED** [review]
Approving as admin-only for now

**Pull request merged**
