### PR TITLE
Map Decals v.2

### PR DESCRIPTION
**Pull request by AnturK**
Redo of #22887

- Fixes caution tiles turning into space.
- Fixes flipped corner decals.
- Fixes gas list property whitespace on replacing.

### CODE REVIEW

**Comment by francinum** [comment]
Deltastation Engineering PA chamber.

**Comment by coiax** [comment]
DeltaStation, near Robotics. Looks like the same turf warning marks.

image

**Comment by francinum** [comment]
Deltastation's a great example of this, because it happens on EVERY SINGLE FIREDOOR.

**Comment by ChangelingRain** [comment]
turf decals can get stuck in crates and closets

**Comment by Kromgar** [comment]
image
image

**Comment by Kromgar** [comment]
I don't know if this is related but bagil crashed with this testmerged

**Comment by AnturK** [comment]
Delta issues are just someone was map_editing icon-state instead of using proper paths. I'll add skipping icon state on these

**Comment by coiax** [comment]
Also, the turf decals are a lot more yellow than they used to be.

**Comment by ChangelingRain** [comment]
Yeah well I yelled at @WJohn about that but he didn't listen; they should be a much more pale yellow and have some transparency.
As such, http://puu.sh/tE29j/841847a92d.dmi is appropriately recolored with transparency to match, roughly, what the decals are currently.

**Comment by coiax** [comment]
image
On birdboat.

**Pull request merged**
