### PR TITLE
Fixes pills -- Revert "Makes the stomach important part of eating (#53228)"

### PR DESCRIPTION
**Pull request by Mothblocks**
## About The Pull Request
This reverts commit 4e2dda164fa13b058e93ec4b2b7de7a94e9a6e4d. (#53228)

## Why It's Good For The Game
It completely broke pills and anything you INGEST. This has been a headache for me to wrap my head around and I'd rather @nightred fix this.

If you (or someone else, I suppose) are going to fix this, this is the test you want:

```
/datum/unit_test/pills/Run()
	var/mob/living/carbon/human/human = allocate(/mob/living/carbon/human)
	var/obj/item/reagent_containers/pill/iron/pill = allocate(/obj/item/reagent_containers/pill/iron)

	TEST_ASSERT_EQUAL(human.reagents.has_reagent(/datum/reagent/iron), FALSE, "Human somehow has iron before taking pill")

	pill.attack(human, human)
	human.Life()

	TEST_ASSERT(human.reagents.has_reagent(/datum/reagent/iron), "Human doesn't have iron after taking pill")
```

### CODE REVIEW

**Comment by Jared-Fogle** [comment]
From my understanding of this feature, it seems like it would completely screw over health analyzers too even if reagents were being processed properly, since I believe the health analyzer only checks what is in your blood.

**Comment by nightred** [comment]
Pills go in the stomach and the reagents metabolize to the body they never go to the body.
This interaction was intended.

If you wanted reagents in the blood you would have to inject or use a patch, IV drip.

**Comment by ATH1909** [comment]
I _told_ you so.

**Comment by nightred** [comment]
The new update works with health analyzers, medical kiosk, all interactions that check chems in body now support stomachs.
All this and more on 53440

**Comment by Jared-Fogle** [comment]
Are you sure it's working as intended?

I tried making a pill of tear juice, because it has a special chat message when a mob is exposed to it. I did not get that message.

**Comment by Qustinnus** [comment]
still broken as hell

**Pull request closed without merging**
