### PR TITLE
dragon's blood can't make you a skeleton anymore

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request
what it says on the tin

## Why It's Good For The Game
you can't heal with medipens as a miner if you are a skeleton

## Changelog
:cl:
tweak: dragon's blood can't make you a skeleton anymore
/:cl:

### CODE REVIEW

**Comment by Shadowflame909** [comment]
drink milk bro

**Comment by Doosteroni** [comment]
Just get a milk medipen bro

**Comment by TheMidnightRose** [comment]
Dont see a reason for this. Dragon's blood is a risk for reward. You take the risks of becoming a skeleton or a digigrade lizard for a chance of becoming a Ash Drake in power.

**Comment by necromanceranne** [comment]
Drink your goddang milk, skelly boy

**Comment by Tlaltecuhtli** [comment]
> 
> 
> Dont see a reason for this. Dragon's blood is a risk for reward. You take the risks of becoming a skeleton or a digigrade lizard for a chance of becoming a Ash Drake in power.

digigrade means you can still do your miner job, and drake potion is a reward not something you can find on floor and needs a chance of making your main heal tool useless

**Comment by IndieanaJones** [comment]
Skeleton > Lizard

**Comment by Whoneedspacee** [comment]
replace it with something else and id consider it because lesser ash drake rng is fine rn but tbh i dont see much of a reason to do this

**Comment by XDTM** [comment]
Kinda mind-boggling that becoming a skeleton is a downgrade for some players, with all the immunities they get.

**Comment by Fikou** [comment]
> Kinda mind-boggling that becoming a skeleton is a downgrade for some players, with all the immunities they get.

miners are the job that gets hit a lot, skeletons cant heal with anything except milk

**Comment by trexter555** [comment]
dragons blood is a gamble, removing skeleton because some people dont like it is stupid. if you dont want to risk becoming a skeleton, dont use the blood then.

**Comment by LoserWasTaken** [comment]
> 
> 
> dragons blood is a gamble, removing skeleton because some people dont like it is stupid. if you dont want to risk becoming a skeleton, dont use the blood then.

its a reward

**Comment by XDTM** [comment]
Doesn't mean it can't be a gamble, as long as the successful gamble is more valuable than standard rewards.

**Comment by GhostEcho** [comment]
I've done a lot of mining, this reeks of "ided plz  nerf" because someone took the risk and didn't get what they want.

**Comment by TheMidnightRose** [comment]
Whoneedspace is right in this and gets my point further across than my original post.

Replace it with something equally as punishing then. The whole point of it being a rng on whether or not you get Lesser Drake is because its stupidly powerful, yeah you might end up becoming a skeleton or a lizard out of this, just means you go kill another drake and hope it drops blood. 

The only way you could MAYBE get this to go through is to buff the change rate towards becoming a lizard to almost 2/3s of the time compared to what it is now. 50/50 shot of lesser drake is a surefire way to get it removed in the future by someone else due to how powerful it is.

**Comment by Shadowflame909** [comment]
> The only way you could MAYBE get this to go through is to buff the change rate towards becoming a lizard to almost 2/3s of the time compared to what it is now. 50/50 shot of lesser drake is a surefire way to get it removed in the future by someone else due to how powerful it is.

>powerful

does someone need to hear my lesser ash drake story again.

Also, RNGESUS does not favor you getting it. It's a 1/4 chance to get the ash drake potion. Then its another 1/4 chance to become an ash drake after using it.

Add in the RNG for an ash drake megafauna to even spawn during your round.

You get a nice rare loot thats actually kinda weak and looks more threatening then it actually is.

lesser ash drakes just a tanky flame thrower! toolbox it!

**Comment by IndieanaJones** [comment]
Lesser Ash Drake is shit-tier, don't know what you guys are on about.  The only thing going for it is corpse gibbing and swooping, it only has 200 health and is SUPER slow.  Worst of all, it's useless for actually mining, and can only enable you to go on a rampage against station brainlets who have an irrational fear of the thing.  What a proper change would actually be is making Dragon's Blood always make you a dragon, but none of this transformation bullshit, make the player stuck as it.  Then, actually make a useful mining utility, so then players have to make the choice whether to use it or not.  You're already fighting against the RNG for the other loot in the chest (you might just get the shitty broken ghost sword, how awful!), so you might as well make the damn thing useful.

**Comment by anconfuzedrock** [comment]
you can still do your miner job if you're a skeleton your job isn't kill the big mean thing that's just a thing you can do your job is mine

**Comment by Whoneedspacee** [comment]
i don't think anyone is argueing that lesser ash drake is unbeatable but it is certainly powerful. it does die very fast because of its low health and honestly 3 people running at it with two handed spears could kill it quite fast, but the utility for it is not something that should be present in every round.

lesser ash drake literally just swoops on a blob and kills it. it has the ability to basically break down many structures, having it on your side is a valuable boon. you literally cannot flash a lesser ash drake transformed person to convert them.

i could go on but these things alone make it something that should have a viable risk and not be present in every round.

**Comment by ExcessiveUseOfCobblestone** [comment]
really funny how skeleton is a boon for lavaland but in nearly every other combat situation it is a huge plus.

**Comment by ATH1909** [comment]
> really funny how skeleton is a boon for lavaland but in nearly every other combat situation it is a huge plus.

> boon

https://www.youtube.com/watch?v=G2y8Sx4B2Sk

**Comment by ATH1909** [comment]
I think the solution here, then, is to replace the result in the RNG "slot" for the current "you can't use survival medipens anymore, get fucked" result with some other "filler"/"mildly negative" effect, like the "turn into an ash lizard" effect. Perhaps it could, say, infect you with wizarditis (or a randomly generated custom disease, to simulate getting a space STD from literally chugging the blood of an alien creature)?

**Comment by ATH1909** [comment]
Alternatively, we can let skeletons process chems again (which would also mostly un-nerf Bind Soul, which is currently rarely taken because it's hard to heal yourself as a skeleton).

**Comment by XDTM** [comment]
They could also get an alternative healing method instead, which could be passive regeneration from being undead, or some manual method of repairing bones.

**Comment by IndieanaJones** [comment]
> i don't think anyone is argueing that lesser ash drake is unbeatable but it is certainly powerful. it does die very fast because of its low health and honestly 3 people running at it with two handed spears could kill it quite fast, but the utility for it is not something that should be present in every round.
> 
> lesser ash drake literally just swoops on a blob and kills it. it has the ability to basically break down many structures, having it on your side is a valuable boon. you literally cannot flash a lesser ash drake transformed person to convert them.
> 
> i could go on but these things alone make it something that should have a viable risk and not be present in every round.

Still, its power lies in on-station murder, its absolutely useless for mining.  Considering its something solely obtainable by miners, you'd think it'd have some use when mining.  Even for murdering fauna on lavaland, its way worse than a KA since the swoop can't one-shot enemies, you're too slow to dodge most megafauna, and you have a smaller healthpool than anything else there sans legions and watchers.

**Comment by Whoneedspacee** [comment]
you walk across lava in lesser drake form, it's pretty much the lava immune effect but just better so i don't see how it isn't obviously the best thing in the pool. either way it should remain at the same rarity.

**Comment by Pugie** [comment]
> > Kinda mind-boggling that becoming a skeleton is a downgrade for some players, with all the immunities they get.
> 
> miners are the job that gets hit a lot, skeletons cant heal with anything except milk

You can experience the precobbychem joys as skeleton woth no downside instant heal synthflesh beakers.

**Comment by kriskog** [comment]
No thanks. You roll the dice and drink the dragons blood, it might not always turn out favorable for you. And thats okay.

**Pull request closed without merging**
