### PR TITLE
Changes smes, cells, cell charger, terminals and apcs icons

### PR DESCRIPTION
**Pull request by nicbn**
[Changelogs]:
[]:
:cl:
imageadd: Nanotrasen redesigned the area power controllers!
imageadd: Thanks Xhuis for the contrast tweak on APCs
/:cl:

Does not close any other APC-sprite related PRs.

The SMESes perspective have been tweaked
The cell chargers and cells are now 3:4 perspective
APCs are no longer 3:4
APC colors are brighter
Terminals look more minimalistic
Cell chargers now show the cell sprite of the cell that is inside it
The APC screen still needs more contrast

apc2
apc
29334556-1ee5193a-81de-11e7-9ae1-5ee1db0f130e
smes

### CODE REVIEW

**Comment by WJohn** [comment]
really doesn't help that you're taking pics with screen stretch on. 

I do think the terminals and APCs could probably be a *little* 3/4th, but I understand the whole "walls and floors are top down" mess we've cornered ourselves in. At some point those are gonna need be moved to something more sane looking (as will windows, doors, and grilles) but that's a project for later.

**Comment by nicbn** [comment]
I think that making the wall-mounted objects not 3:4 makes them feel like in the wall rather than above the wall. The apc and cell charger pics are 200% stretched, the offline apc is 250%, the smeses are 250%, and the dmi preview one is not streched at all.

**Comment by WJohn** [comment]
Of course, this only applies right now because walls, too, are top down rather than 3/4th. This'll have to change *again* later on if walls are every made 3/4th (a huge project which will inevitably devolve into intense shit flinging on all sides).

**Comment by WJohn** [comment]
On another note, I think it would be best if we combine this with #29901 as these here don't fix the contrast problem on the screens themselves. I can send you an updated DMI in a bit, if you're cool with that.

**Comment by nicbn** [comment]
I'm fine with that, the screens are much better with more contrast.

**Comment by WJohn** [comment]
Alright, I touched nearly every single APC sprite there so it's best if you just use the whole .dmi. I haven't touched the SMES cells or anything.

http://www.mediafire.com/file/059epult7ljwtv7/power_%284%29.dmi

This effectively combines the increased contrast PR (with a bit of minor tweaking so it's not quite so jarring).

**Comment by WJohn** [comment]
Hmm, looking at this again, I'm not entirely keen on the SMES cells being made smaller and less indicative of how much charge they have. Could you undo that?

**Comment by nicbn** [comment]
They are not less indicative, they just have one less light.
There is the green light, the red light and the yellow-red light, which I removed.
Now, when there should be red on the yellow-red, there will be a blinking yellow light on the green and red lights. When there should be yellow, there will be blinking yellow in only one light.
I tested it and it does not look harder to understand, actually the blinking thing is kinda cool.

**Comment by nicbn** [comment]
But if you think this would damage the user experience, I'd have no problem with undoing this change.

**Comment by WJohn** [comment]
Two less, actually. That's beginning to get difficult to tell how charged it is.

**Comment by nicbn** [comment]
If you mean the power indicator lights, when the indicator should be a light that is not present, the light before it will blink. Is the power indicator lights the problem? If it is I can make them be a single bar.

**Comment by WJohn** [comment]
I think a single bar would be preferable, yeah. With it flashing when it's down to the last tick for when it's empty.

**Comment by nicbn** [comment]
This should do the work for now.

**Comment by GunHog** [comment]
Please revert the SMES, the new ones look awful! :-1:

**Comment by WJohn** [comment]
They look different than what's shown. They're actually a smooth bar so you get just as much detail. Other than that there's really very little actually changed over what we have now, just a slight perspective shift, you see more of the top.

**Comment by lzimann** [comment]
Then update the pictures to reflect what it actually looks in game. Otherwise everyone will probably consider this godly awful.

**Comment by nicbn** [comment]
Updating the pictures, no more stretching.

**Comment by MoreRobustThanYou** [comment]
I'd love to see them in game

**Comment by nicbn** [comment]
No recording software, sorry. You can download the DMI and test it yourself btw.

**Comment by WJohn** [comment]
Oh and one last complaint I have heard about new APCs:

Could you try and change the pixel x and y shifting so they're more centered and pretty much touch the edge of the wall better?

**Comment by nicbn** [comment]
I'm pretty sure that's a mapping problem, as there is no dir in the sprites.

I could add a dir, but that would require adding dir var in every APC already mapped, in the construction code etc. In other words, it would be a pain in the ass.

Also, changing the sprite by {x, y} in a dir would change by {-x, -y} in the 180-correspondent, and by {y, x} and {-y, -x} in the 90-ones.

**Comment by WJohn** [comment]
The dirs set the pixel shifting in game, actually.

**Comment by nicbn** [comment]
Oh.

I'll add rotation, let's see what happens.

**Comment by WJohn** [comment]
Oh no, definitely don't add rotation. The whole point of this is to make it easy to read regardless of where they're placed. Keep em all using one direction. I'm talking the map making dirs 1, 2, 4, 8 being used to affect their pixel shifting, and it seems slightly not aligned, and I'm asking you to tweak it so that it is.

**Comment by nicbn** [comment]
Ok so the problem is in the code right? How many pixels should I shift?

**Comment by nicbn** [comment]
Which one is the one?

```
apc.dm
pixel_x = (src.tdir & 3)? 0 : (src.tdir == 4 ? 24 : -25)
pixel_y = (src.tdir & 3)? (src.tdir ==1 ? 23 : -24) : 0
```

```
apc_frame.dm
if(pixel_shift)
	switch(ndir)
		if(NORTH)
			O.pixel_y = pixel_shift
		if(SOUTH)
			O.pixel_y = -pixel_shift
		if(EAST)
			O.pixel_x = pixel_shift
		if(WEST)
			O.pixel_x = -pixel_shift
```

**Comment by WJohn** [comment]
The first one, try messing with the 24: -25 and 23: -24 values there, see if you can get something better looking in game.

Maybe our old ones were just as badly shifted. Maybe players are bitching about something that was always bad and hasn't changed any.

**Pull request merged**
