### PR TITLE
Moves the robotic voiceboxes from one of my previous PRs over to the RoboDrobe

### PR DESCRIPTION
**Pull request by ATH1909**
## About The Pull Request
I had forgotten that the RoboTech vending machine doesn't actually spawn in Robotics roundstart. This PR moves the robotic voicebox over from that vending machine to the RoboDrobe vending machine, which DOES spawn in Robotics roundstart.

Unfortunately, this means that the price of techpriest robes has increased. Oh well, roboticists have large salaries anyway.

## Why It's Good For The Game
This moves the robotic voicebox over to a vending machine that's actually used/present on most maps.

## Changelog
:cl: ATHATH
tweak: Moved the robotic voiceboxes from the contraband section of the mostly-unused RoboTech vending machine to the contraband section of the RoboDrobe vending machine. Unfortunately, this meant that the price of techpriest robes had to be increased.
/:cl:

### CODE REVIEW

**Comment by carlarctg** [comment]
@ATH1909 u fucked up and did this in the dagoth ur branch

**Comment by ATH1909** [comment]
> @ATH1909 u fucked up and did this in the dagoth ur branch

Uh, it doesn't look like it.

The weird commit history is just because I'm using the W E B   E D I T O R . If you look at the branch names (and the files changed tab), they should be different/separate from each other (unless I'm missing something big here).

**Comment by Krysonism** [comment]
I am fairly certain you can set individual contraband prices for items.

**Comment by wesoda25** [comment]
Bro if your master is so littered with commits and you don’t wanna switch to desktop (i get it i waited forever) just delete your current fork and make a new one

**Comment by ATH1909** [comment]
> Bro if your master is so littered with commits and you don’t wanna switch to desktop (i get it i waited forever) just delete your current fork and make a new one

I don't think that I can without also deleting all of my open PRs.

**Comment by wesoda25** [comment]
you just cant update them

**Pull request merged**
