### PR TITLE
Make swarmers drop a bluespace crystal

### PR DESCRIPTION
**Pull request by YotaXP**
Because why the heck not?

### CODE REVIEW

**Comment by PKPenguin321** [comment]
:+1: thanks fam

**Comment by Bawhoppen** [comment]
should be a percent chance to drop random machine parts like manips, matter bins, the tcomms components, bluespace crystals, etc.

**Comment by bgobandit** [comment]
shouldn't these be artificial bluespace crystals

**Comment by RemieRichards** [comment]
Yeah it probably should be artificial ones.

**Comment by GunHog** [comment]
This with PKPenguin321's update means that the telefun will never end!

**Comment by YotaXP** [comment]
I had them drop normal ones since they were aliens, but it didn't occur to me that normal ones are supposed to be naturally-grown.  Fixed

**Comment by Cheridan** [comment]
sure why not

**Pull request merged**
