### PR TITLE
Added admin smite: Mark for Death

### PR DESCRIPTION
**Pull request by coiax**
:cl: coiax
admin: Admins can Mark For Death with the Smite menu, which functions
the same as someone being blood contracted.
tweak: The butcher knives and the red colouring of someone
marked for death will disappear after two minutes.
/:cl:

The primary use I see of Mark for Death? WGW readers. Saw some
other admins use it, but they had to manually spawn in a contract
and use it.

The cleaning up after two minutes is so the station isn't covered in
cleavers, and the RED GET THIS GUY fades, so people can be horrified/thrilled
at their actions appropriately.

### CODE REVIEW

**Comment by HomocidlePancakes** [comment]
There should be an option to not give the chainsaw and adminodrazine to the target

**Comment by Nabski89** [comment]
Smiting someone by making them valid to murder as many people around them isn't really a punishment for the kind of players you'd like to smite.

**Comment by 81Denton** [comment]
Biggest punishment would be requiring you to type *inhale, *exhale and *blink

**Comment by Cyberboss** [comment]
This is encouraging stirring too much shit with smite

**Pull request closed without merging**
