### PR TITLE
Snail achievement 

### PR DESCRIPTION
**Pull request by Time-Green**
Becoming a snail through genetics now gives you an achievement! Wow!
I suppose if you somehow get the unspawnable snail shot you could get it too, but yeah it's admin only.

:cl:
add: adds the snail achievement to genetics
/:cl:

Achievement icon:

image

### CODE REVIEW

**Comment by ATH1909** [comment]
But what about the dullahan result?

**Comment by Time-Green** [comment]
> But what about the dullahan result?

We believe in you

**Comment by HomocidlePancakes** [comment]
What if you become a snail through wiz events?

**Comment by Time-Green** [comment]
> What if you become a snail through wiz events?

You don't get it

**Comment by trollbreeder** [comment]
Gastrolisis is fetish content, speedmerge PR anyways

**Comment by HomocidlePancakes** [comment]
No, it’s a yog meme.

**Comment by Time-Green** [comment]
> No, it’s a yog meme.

I know they had a snail thing, but gastrolosis has always been a unique thing I made based on that one spongebob episode

**Review by kriskog — APPROVED** [review]

**Pull request merged**
