### PR TITLE
Makes mild traumas a bit less trivial to cure

### PR DESCRIPTION
**Pull request by XDTM**
:cl: XDTM
balance: Mannitol no longer cures mild traumas.
balance: Added a new reagent, Neurine, made with Mannitol, Acetone and Oxygen. Neurine can cure mild traumas in the same way Mannitol did, but does not heal brain damage.
/:cl:

With mannitol being extremely easy to produce, mild traumas mean nothing more than a quick trip to medbay instead of being, y'know, lasting traumas. Increasing the difficulty of producing the reagent a bit should make these traumas a little more meaningful if there aren't proper chemists around.

### CODE REVIEW

**Comment by ExcessiveUseOfCobblestone** [comment]
Looks like a pretty simple macro to me, if you want something more lasting I'd just say make a simple surgery for it.

**Comment by XDTM** [comment]
I didn't want to make it a steep requirement, and someone passable in chemistry with access to a dispenser won't have any issue, but roundstart mannitol pills will no longer be effective, and the recipe might be complicated enough to make curing the trauma slightly more annoying than keeping it if there's no chemist.

**Comment by Vidiveni** [comment]
Another big thing is that upgraded sleepers won't have neurine. 

Anyhow mannitol+neurine will heal 5 brain damage per tick, which lets you be perma-unstunnable with bath salts (4 brain per tick) or perma methed (avg 2.5 per tick). While I'd love to abuse this, I think you should reduce neurine brain heal to 0.5 or so for balance reasons.

**Comment by XDTM** [comment]
They're both somewhat hard to craft and require careful dosing to avoid overdosing, i think it won't be a problem compared to, for example, hulk.

**Comment by plapatin** [comment]
If this is is merged, bath salts will lose it's most massive drawback, though. How will that be fixed?

**Comment by XDTM** [comment]
Hulk: complete stun immunity AND 15 damage punches, along with the ability to destroy walls and objects. Downsides: no guns, nonhuman to silicons.
Bath salts: complete stun immunity, chance for 15 damage stun punches but also for completely ineffective attacks, with no structural damage bonus. Downsides: needs to be brewed with hard-to-get ingredients, and will still need to be paired with two different reagents. Dosage must be constant to avoid overdosing. Still causes hallucinations and random movement while active.

I think that someone who manages to make a stash of bath salts, mannitol, and neurine and apply them consistently has put in enough effort that it can get a similar reward to a geneticist getting the hulk gene.

**Comment by ExcessiveUseOfCobblestone** [comment]
> They're both somewhat hard to craft and require careful dosing to avoid overdosing, i think it won't be a problem compared to, for example, hulk.

I can think of a fairly recent PR that would make this extremely easy to manage.

I don't think difficulty in crafting should be a factor in chems UNLESS (!) it requires items outside the chem dispenser. Macros make it piss easy to make meth, the hardest part is heating it. Bath salts are a fair argument though.

**Comment by Vidiveni** [comment]
Another problem I see with neurine brain-heal id that neurine is simply "better" than mannitol. A tier 2 drug. Most all(?) other medicines come with different drawbacks (except maybe charcoal vs pentetic acid). 

I think straight upgrades of healing chems should be avoided for game design reasons, and as an experienced chemist the current neurine recipe is very easy to make. 

For a straight upgrade I think it should either be tedious as fuck to make (like pentetic acid) or require stuff from other departments/vendors, such as any of menthol (because lol-mental), or cooking oil, enzyme, dr. Gibb, toxin (the reagent), hell maybe even Vitrium Froth.

**Comment by XDTM** [comment]
I think the ideal solution then would be to remove the brain damage healing and only keep the trauma heal, making it a niche medicine instead of an upgrade

**Comment by ExcessiveUseOfCobblestone** [comment]
smart decision

**Comment by Tlaltecuhtli** [comment]
if u  want recipes less "trivial" add some potass water in there so macrofags explode

**Review by ninjanomnom — APPROVED** [review]

**Pull request merged**
