### PR TITLE
Refactor of catpeople mutant organs

### LINKED ISSUE #31204: Catpeople organs are broken as fuck
Here's why its shitcode

Cat tail is inside the groin, its not tail attachement/removal.

Removing the tail from inside the groin doesn't update the sprite and the tail is still there.

Catpeople that spawn as head still have those organs inside them (giving them 2.0 modifier on flashbang stuns)

Getting changed into another species via xenobiology toxins and back to human also removes your cat organs. (probably not a bug, but a ""feature"")

### PR DESCRIPTION
**Pull request by ACCount12**
Catpeople organs were a weird hack, so I tried to fix that. I managed to turn an inconsistent dysfunctional hack into a fully functional, consistent and entrenched hack. I'm sure that's refactor enough.

* Admin "purrbation" now properly puts the cat organs in and removes them.
* `remove_catshit` snowflake proc is removed in favor of extending and reusing `purrbation_remove`.
* Lizard tail is now an organ too, following the same rules and using the same surgery as cat tail. Yay for the consistency!
* Snowflake "tail removal" surgery is removed.
* Cat tail/ears no longer runtime in non-human mobs.
* Technically, the purrbation now works with non-baseline humans, but I don't feel confident enough in that to enable it.

The organs themselves are still stuck in the weird state of being "not-so-internal-organs", but they are clearly not limbs, I don't feel comfortable with trying to invent a third type of organs here, and adding a proper framework for internal organs with external features is something I'm already thinking about.

Fixes #31204. To be specific, it fixes issues 1, 2 and 4 there, and adjusts a fix of 3.

:cl: ACCount
tweak: "Tail removal" and "tail attachment" surgeries are merged with "organ manipulation".
/:cl:

### CODE REVIEW

**Comment by Grazyn** [comment]
If tails are organs, would it be possible to add some effects if they are removed? For example, dizziness/confusion that causes erratic movement like the drunkenness effect. I recall that @anconfuzedrock  was working on something like that.

**Comment by Supermichael777** [comment]
internal organs currently means not limbs no third type needed

**Comment by ShizCalev** [comment]
>adding a proper framework for internal organs with external features

Why am I cringing

**Comment by Repukan** [comment]
>Snowflake "tail removal" surgery is removed.

Does this mean the code for it is gone, or the surgery itself is recoded but still available for use?

**Comment by Arianya** [comment]
> Lizard tail is now an organ too, following the same rules and using the same surgery as cat tail. Yay for the consistency!

Would imply that its been recoded

**Comment by XDTM** [comment]
Why doesn't someone make catpeople a separate species before we implode in snowflake code

**Comment by DoctoreMad** [comment]
@XDTM There is no waking up
I feel it in my bones
Wake me up
Wake me up
Wake me up inside

**Comment by Hatfish** [comment]
>severed tails carry over spines now
my hero!

**Comment by ACCount12** [comment]
>If tails are organs, would it be possible to add some effects if they are removed? 

Yes, it's possible to slap on a temporary effect on organ removal.

**Comment by MoreRobustThanYou** [comment]
thumbs down for removing my precious ```remove_catshit```

**Comment by optimumtact** [comment]
these should be limbs if we're being honest.

Or a new concept of external organs

**Comment by KorPhaeron** [comment]
@optimumtact

How would targeting work? Groin?

**Comment by optimumtact** [comment]
how does it currently work?

**Comment by KorPhaeron** [comment]
@optimumtact Right now if you have groin selected when you attack people it just defaults to chest since groin isn't an actual targetable zone anymore

If you are targeting groin during surgery it shows tail adding/removal

If tails were added a limb you'd need to able to target them for real as a combat thing, since they'd be able to take damage from being set on fire etc (and so you'd need to be able to ointment them)

Groin attack = attacking tail if they have one is probably the sanest way to avoid making weird health dolls

**Comment by optimumtact** [comment]
I wasn't thinking fully simulted limbs, that's why I suggested a new class of "external" organs

**Comment by ACCount12** [comment]
So the third type of organs. That doesn't sound good.

**Comment by optimumtact** [comment]
why doesn't it sound good

categories are arbitrary and namespacing is a good thing

**Comment by Grazyn** [comment]
It would be neat if tails could be severed during a fight. After all, this is how lizards work IRL.

**Comment by ACCount12** [comment]
That doesn't sound good because it demands deep changes in icon rendering, an addition of all new snowflake surgical operations and even more shitcode, all to support a feature that's literally cat ears.

**Comment by AnturK** [comment]
Yeah, differentiating external and internal is good idea, but this is fine in the meantime.

**Comment by AnturK** [comment]
Add changelog about the surgery change please.

**Comment by ACCount12** [comment]
Changelog is in, ready to merge.

**Pull request merged**
