### PR TITLE
Blindfolds properly apply blindness

### LINKED ISSUE #36048: Having phobia of seeing yourself can't be prevented with a blindfold
84335 Sybil 511
PLUS using the tin foil hat gives you phobia of multiple things that can't be cured with mannitol.

### PR DESCRIPTION
**Pull request by XDTM**
Fixes #36048

All hail the trait system

### CODE REVIEW

**Comment by KorPhaeron** [comment]
Please apply the same fix to flashlight eyes

**Comment by KorPhaeron** [comment]
And then remove the check for tint blindless on carbons

**Comment by XDTM** [comment]
jesus there was a tint blindness check?

**Comment by KorPhaeron** [comment]
Prior to traits we didn't have a decent way of doing blind via glasses without curing genetic blindness

**Comment by XDTM** [comment]
Now if you have too much tint you're properly blind instead of only having an overlay. Also did the flashlight eyes as a separate source.

**Comment by KorPhaeron** [comment]
Thanks

**Pull request merged**
