### PR TITLE
You can only have one virus at a time

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
Death to triple stacking healing viruses

If someone can find a more interesting way of dealing with this problem by all means go ahead, but the entire crew having fleshmend 12 minutes in is getting old. I'll remove the DNM tag in a few days if nobody comes up with a good alternative (and I mean code one, @MrStonedOne and @Robustin have both mentioned competing virus strengths for spreading and that sounds like a good idea if someone is willing to put in the work)

### CODE REVIEW

**Comment by Buggy123** [comment]
PLEASE NO :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1:

**Comment by TechnoAlchemisto** [comment]
But wait this makes traitor viro worse because you can't stack negative viruses

**Comment by robbym** [comment]
Do NOT want. Makes Virologist less worthwhile.

**Comment by optimumtact** [comment]
Wouldn't it be more interesting if the way traits interacted when they appeared more than once was overhauled instead?

I.e two or three healing traits causes you to burn to death or some other such mechanism.

This provides another factor of depth where a virologist must consider the depth of virus stacking.

**Comment by Robustin** [comment]
A B S O L U T E L Y
M
A
D
M
A
N

**Comment by lzimann** [comment]
Why instead make so you can't stack symptoms? So this way you can still have multiple benefitial diseases but not triple healing memes

**Comment by ChangelingRain** [comment]
here's my opinion on this
fuck

**Comment by KorPhaeron** [comment]
@TechnoAlchemisto 

Traitor viro is already absolutely awful. The other (realistic) options are removing beneficial symptoms or removing viro as a job.

@optimumtact 

Problem is those 2-3 healing traits are in different viruses. Not sure how much reworking virus code would require to have each disease checking the symptoms of every other disease in the mob each  time they do something.

**Comment by Zilenan91** [comment]
Actually doesn't this make xenos completely worthless? Their implantation is classified as disease so if viros make even one healing virus or really any virus at all, wouldn't that mean they could never implant people?

**Comment by GunHog** [comment]
Terrible :-1: and unfun

**Comment by MrStonedOne** [comment]
>Actually doesn't this make xenos completely worthless? Their implantation is classified as disease so if viros make even one healing virus or really any virus at all, wouldn't that mean they could never implant people?

I do not think this is the case anymore.

**Comment by KorPhaeron** [comment]
@GunHog 

Throwing what little we have for a medical system out the window after 12 minutes of a guy sitting alone in a room hitting a button is terrible and unfun

**Comment by MrStonedOne** [comment]
Also, we would need to figure out a better way to deal with virus spreading then.

Mainly a way for one virus to overpower another out, depending on stage and other factors.

**Comment by GunHog** [comment]
Then make it reagent based and balance the healing on that reagent. The way you do this just slams the role into the ground.

**Comment by KorPhaeron** [comment]
The virologist role is not more valuable than the rest of the game, and everyone having infinite health is miserable for the rest of the game.

**Comment by hornygranny** [comment]
:+1:

**Comment by GunHog** [comment]
Stop using exaggeration to justify nerfs. You have health _regeneration_. "Infinite" health would imply having GODMODE enabled - Far from it. My point is valid and you have not addressed it. Your method hurts both good and bad viruses, and ones that do not heal either. Making it reagent based lets you balance the thing you seek to balance without hurting the rest of the system.

Unless you have some objection to other aspect of virology, this is not a proper way of handling this.

**Comment by KorPhaeron** [comment]
There is no limit to the heatlh regeneration, and it consumes no resources as a person regenerates nor as it spreads to other people to regenerate. If we had a magical computer that wouldn't crash you could stand your character in a vacuum and their regeneration would last until the heat death of the universe.

**Comment by Zilenan91** [comment]
Could always make it so that toxic comp drains a shitton of hunger, enough so that weight even or the fat symptom can't stop the nutriment, and that it can't convert damage to tox if you're out of nutriment.

**Comment by MrStonedOne** [comment]
Also, we would need to figure out a better way to deal with virus spreading then.

Mainly a way for one virus to overpower another out, depending on stage and other factors.

Edit: actually, have the viruses mix like they would if you mix them in beakers.

This means the viruses would ebb and flow as they randomize if there are more than 6 symptoms.

I like it.

**Comment by GunHog** [comment]
Your statement remains flawed. Unlimited _regeneration_ is not unlimited _health_. It means that someone can survive an ordeal if the source of the damage is removed. This is where it differs from infinite health. Also, taking my point outside the bounds of even the most extreme of rounds, then criticizing the result is also a poor refutation.

Ignoring the bad argument, my point still stands that there is a better way of balancing this. Even that nutriment draining one would be better. I still say that making it reagent based would address your original argument of stacking the virus symptoms. Why do you ignore a perfectly good solution to your original problems?

**Comment by Robustin** [comment]
Nerfing the .001% of traitors who actually try to go the viral route is nothing compared to the cost that healing viruses impose on the round.

Communicable fleshmend is never a good thing. In the long run viro should get a stat for the virus that will allow a virus to trump weaker ones. Might be an interesting tactic for fighting naturally occurring viruses too.

**Comment by KorPhaeron** [comment]
@GunHog 

I said in the OP that this is DNM for a few days if people want to PR alternate solutions, I'm not ignoring the solutions. I even listed my favourite ones in the OP

@MrStonedOne 

Have all the viruses merge into one virus inside the body?

**Comment by MrStonedOne** [comment]
yes

**Comment by MrStonedOne** [comment]
like they do with beakers

since a virus can only have 6 symptoms, it would pick a random 6 to merge

**Comment by GunHog** [comment]
Oh, I see, you only ignore _my_ solution. Fine.

**Comment by Zilenan91** [comment]
Yeah could have people be melting pots of symptoms and smaller viruses with them randomly appearing and having their symptoms occur over others.

**Comment by KorPhaeron** [comment]
@GunHog 

Reagant based would just murder you from OD/overlap with chem anyway

**Comment by GunHog** [comment]
They do not have to have an OD, they need not exist outside the virus itself. The majority of other symptoms work in this same manner, by producing a reagent. They usually do not cause OD, even when stacked (I believe stim one may have been an exception) due to giving low amounts.

Am I wrong to believe that you are actually against beneficial viruses as a whole, rather than just Toxic Filter + Toxic Compensation? It is the only conclusion that makes sense here.

**Comment by optimumtact** [comment]
WAIT
what if we made health regeneration consume nutriment?

**Comment by Zilenan91** [comment]
Yeah that's what I suggested

**Comment by KazeEspada** [comment]
Toxic Comp should dump plasma to the tile.

**Comment by KorPhaeron** [comment]
@optimumtact 

I think there's a symptom that gives you nutriment

@GunHog 

I think beneficial viruses are pretty bad on the whole yeah. Like I said though, if you like them, make a PR to fix them

**Comment by ToadStar** [comment]
Why not make it so that beneficial symptoms take up a "biostability" var, negative symptoms give them, neutral ones like the beard and aging ones give/take none, and every virus starts with 100. Low biostability makes beneficial viral syptoms have a chance of not working per tick as it goes below say, iunno, 39 or something, and then they start to malfunction below 20.

That way you're forced to balance out your healing virus by making it make everyone mute or blind or something stupid.

**Comment by Zilenan91** [comment]
@KorPhaeron Make Toxic Comp use up more nutriment than the viro symptoms that give nutriment give you. There are three nutriment symptoms, one that makes you drain nutriment, one that makes you be even on nutriment (weight even) and one that makes you fat.

Make toxic comp drain more nutriment than the one that makes you fat, the most severe nutriment system.

**Comment by ToadStar** [comment]
Zile, the virology symptoms that give you nutriment actually _set_ your nutriment levels to their unique levels. It wouldnt really do much.

**Comment by Zilenan91** [comment]
Seriously? That's pretty stupid. They should just give a flat nutriment addition or subtraction.

**Comment by KorPhaeron** [comment]
18<hornygranny18> [Medical] Bjorn Selander says, "You can triple stack stim, toxic filter and toxic tomp, and self resperation, and then add weight even, acid restore, and ocular restore to make them unique viruses."
18<hornygranny18> why is this allowed
18<hornygranny18> ban this sick filth

**Comment by Supermichael777** [comment]
create a list of all symptoms as vars in /carbon and just have viruses turn them on/off?

That way you can have multiple viruses but symptoms cant stack. Would probably make carbom/life hella long though but mabey another var to check if you even have a virus would cut down on the actual run length.

**Comment by Core0verload** [comment]
:-1:

**Comment by PKPenguin321** [comment]
:-1:

**Comment by KorPhaeron** [comment]
For everyone posting thumbs down, please explain how throwing out our entire medical/health system ten minutes into the round is a good thing.

How are healing viruses good/beneficial gameplay?

**Comment by Dawgas** [comment]
virology has never been good or beneficial gameplay though?

That can also be said of a lot of things.

**Comment by Core0verload** [comment]
>For everyone posting thumbs down, please explain how throwing out our entire medical/health system ten minutes into the round is a good thing.

Simply limiting amount of viruses in the body is a bad solution. Make symptoms effects reduce with increasing amount of viruses in the body, or make multiple viruses reduce the virus symptoms firing rate. So you could stack the viruses, but it wouldn't be very useful. Then buff symptoms to be more useful on their own.

**Comment by Zilenan91** [comment]
Another way of fixing healing viruses would be to remove toxic filter but make chems that heal toxin damage way easier to come by.

**Comment by LanCartwright** [comment]
Try test merging my mathematical fix.

**Comment by Grazyn** [comment]
As someone who plays viro a lot, I agree that the health regen thing is OP as fuck, but please for the love of God don't remove virus stacking. With our current system the only way to have a bad virus without shitty resistance/stealth is to add 1 bad symptom and 5 buff symptoms. And since bad symptoms take forever to become effective, if you want a disruptive (not even deadly) virus that won't be cured with sugar or orange juice, you have to double/triple stack (usually at least one virus with a damage dealing symptom like necro/combustion and another one with a disabling symptom like dna sab/deaf/blindness). Anything else and you're forced to bomb chemistry/rnd/steal all the pandemic boards, or get laughed at by the whole station.
Just remove tox comp/filter and the problem is fixed, the remaining good symptoms are already very good by themselves, and don't really benefit from stacking.

**Comment by PKPenguin321** [comment]
>For everyone posting thumbs down, please explain how throwing out our entire medical/health system ten minutes into the round is a good thing.

Sorry, I've been posting from mobile and haven't really been able to write out my full thoughts. My main reason is that this is not a good way to fix healing viruses being too good, since it ruins a lot of other parts of virology, IE releasing superpandemics (which are pretty fun)

**Comment by MrStonedOne** [comment]
Heres another idea.

Bodies only process one virus a virus tick, cycling between them.

**Comment by AlexCrimson** [comment]
Nerfing healing virus stacks is a very needed thing. Nerfing the virus limit is a terrible way to do it. I mean, you could circulate one harmless virus to the entire crew and they would be immune to every other virus? Screw that. It would also make the Anti-Bodies Symptom completely useless.

Also, if you are going to nerf healing, then non-traitor Viro needs a buff in some other way. Because making insanely strong healing viruses is the only reason to play non-traitor Viro.

**Comment by newfren** [comment]
@GunHog the way reagent symtpoms work is by replenishing the stock of the reagent inside you every time they detect you being below a certain amount, so there's never any risk of overdose unless you're eating a bunch of ephedrine pills while already having the stimulant virus or something. The only beneficial symptoms that actually benefit from being stacked at the moment are the two toxics, DAR, and I think weight even, maybe.

**Comment by LanCartwright** [comment]
https://github.com/tgstation/-tg-station/pull/15873

HOLD THE PHONE.

How about we port all current viruses to work on my mathematical system. This way, healing viruses are rebalanced (technically not nerfed) and deadly viruses are more powerful.

**Comment by Dorsisdwarf** [comment]
how about remove healing viruses

**Comment by LanCartwright** [comment]
how about you solve player problems by dealing with players than remove content and turn everything into a padded room

This isn't assfaggots you can't balance everything.

**Comment by AlexanderUlanH** [comment]
Healing viruses need a nerf but the way to do that isn't limiting the number of viruses to 1. It doesn't make sense, for example, that having a cough would immunize you against the death plague.

**Comment by CPTANT** [comment]
Stop removing every interesting thing in the game.

Why would virology even exist after this?

**Comment by TheNightingale** [comment]
The thing where you can only have one of each symptom sounds good. Triple-stacking healing virii will be no more effective than using just one.

**Comment by KorPhaeron** [comment]
@Cptant

How is passive, constant fleshmend for thr whole crew from the start of the game "interesting"?

**Comment by CPTANT** [comment]
How is nerfing everything to shit interesting?

Also please stop with the hyperbole, healing virusses are no where near fleshmend levels and are not roundstart, they take effort to make.

What is the virologist supposed to do all round if this gets merged?

**Comment by lzimann** [comment]
the "effort" is less than 10 minutes in viro

**Comment by ChangelingRain** [comment]
It's actually better than fleshmend because it heals 8-14 toxin damage every time the symptom activates(and fleshmend doesn't do anything to toxin)
The damage converter heals 1-2 brute and burn(both) and does 1-2 toxin every time it activates.

I'm pretty sure the problem here isn't damage converter, but the toxin filter symptom, because it's healing 4-14 times the damage the damage converter symptom can ever do.

**Comment by KorPhaeron** [comment]
>not roundstart

10 minutes is pretty damn close

>effort to make

Sitting in a room by yourself rolling the dice is not the kind of effort we should care about or reward

>What is the virologist supposed to do all round if this gets merged?

The virologist job is not more important than the game as a whole. I'd rather axe the job than continue having it be a healing virus farm

**Comment by CPTANT** [comment]
Than axe genetics and xeno while you are at it.

**Comment by optimumtact** [comment]
Genetics and Xeno aren't able to stack 3 heals on top of each other for the rest of the round.

**Comment by Lumipharon** [comment]
SO I didn't bother reading all 500 comments, but this is a dumb change considering the olny problem is the beneficial symptoms (mainly healing), being stackable, and making it OP.

Rather than nerfing every other use of viruses, wouldn't the logical thing to do, be to nerf the healing symptoms? If you're making beneficial viruses there is literally zero reason to make just 1 instead of 3, so if you slashed their effectiveness down to a third of current strengeth then bam, you only get the effectiveness of 1 for 3 viruses.

negative viruses are utterly shit if you can only apply one.

**Comment by optimumtact** [comment]
#15961 
#15963 
Are likely better approaches to this issue

**Comment by KorPhaeron** [comment]
Better PRs got merged

**Pull request closed without merging**
