### PR TITLE
Lavaland Chems Booster Pack I: More chems edition

### PR DESCRIPTION
**Pull request by Djiq**
## About The Pull Request
This PR changes a few things, first of all miners now recieve special meson scanners that can also function as science goggles, so they can scan what's inside geysers, making cooperation easier.

Secondly it adds a few chems that can be considered very good, but since they require you to go to lavaland and look for geysers, it balances out, since chemists have no incentive to go to lavaland as is, locking op shit behind geysers will force at least some of them to go there, which is my goal.

Chems:
- Penthrite now requires plasmium oxide instead of wittel

- Alphazine - a lot better omnizine crafted with lavaland chems

- Crank - crank now requires lavaland chems to be crafter, but i buffed it to be 50% better meth

Plasmium oxide can now also be aquired from emagged chem dispenser. Honestly emagged chem dispensers are useless, more reasons for emagging something is good, since we nerfed emag already im not considering this bloat.

## Why It's Good For The Game

Lavaland chems should be better than standard chems. Effort = OP chems. I'm just adding more 
chems so that there is more incentive to actually going to lavaland.
## Changelog
:cl:
add: Miners are outfitted with specialized science meson goggles, to identify geysers
add: Alphazine has been added, as a much better omnizine alternative that requires lavaland chems
tweak: Crank now requires protozine, but acts like 50% better meth.
tweak: Penthrite now requires plasmium oxide.
add: Plasmium oxide can now be aquired from emagged chem dispenser
/:cl:

### CODE REVIEW

**Comment by wesoda25** [comment]
>Secondly it adds a few chems that can be considered op

I'm going to stop you right there

**Comment by EdgeLordExe** [comment]
> > Secondly it adds a few chems that can be considered op
> 
> I'm going to stop you right there

read the whole damn pr, those are lavaland chems im talking about, not your standard cookie-cutter press button to get op pill chems.

**Comment by Angustmeta** [comment]
You don't need to rename crank. It just forces me to rename it on some wiki pages and add yet another "was originally named x" as bloat to chem description.

**Comment by EdgeLordExe** [comment]
> You don't need to rename crank. It just forces me to rename it on some wiki pages and add yet another "was originally named x" as bloat to chem description.

i wanted to rename it since, leaving it as crank might be confusing to that 1% of people that made crank, but sure i can rename it back into just crank

**Comment by Angustmeta** [comment]
Thanks. It's the opposite imo. Renaming makes things more confusing since you will have both names in memory. I'd say "crank was buffed" is simple enough.

**Comment by EdgeLordExe** [comment]
> Thanks. It's the opposite imo. Renaming makes things more confusing since you will have both names in memory. I'd say "crank was buffed" is simple enough.

done

**Comment by optimumtact** [comment]
look, another thing we don't need, more chems.

what we need instead is the same chems we already have, but more complex to make.

**Comment by optimumtact** [comment]
I can see you really like your fresh paint

**Comment by EdgeLordExe** [comment]
> look, another thing we don't need, more chems.
> 
> what we need instead is the same chems we already have, but more complex to make.

yeah these are more complex. Why? they are from lavaland geysers. No chemists go for these, so im adding incentives for them to do so.

**Comment by optimumtact** [comment]
They're not more complex, this is pathetic

**Comment by EdgeLordExe** [comment]
> They're not more complex, this is pathetic

the fact that the recipe doesnt require 30 diffrent chems doesnt mean it is not complex. To get any of these you have to get a geyser on lavaland, whichc is tricker than you might think.

**Comment by bluejack1** [comment]
Lavaland chems dont matter. You could put a chem that makes you immortal and I still wouldn't use it. If I have to go to lavaland and let chemistry be raided to get a reagent then it's not op.
The real problem is Crank: as it is it's the only combat drug that provides decent stun reduction without making you drop shit or causing brain damage, which is nice. It's a nice niche drug that I sometimes make and mix with other stuff like meth. 
If you wanna make a lavaland chem that is twice as effective as meth, go for it. Don't take away a decent on-station drug by locking it behind lavaland  and making it "OP" please.

**Comment by Tlaltecuhtli** [comment]
ah yes more lavaland DLC packs for crew jobs, when will the doctors have to go there and fight demons to get their patient's soul back from hell? what about bubblegum's curse that prevents janitor from cleaning blood until he defeats him?

**Comment by evilcyborgmrt** [comment]
> doctors have to go there and fight demons to get their patient's soul back from hell

I hate the idea of gating chemistry behind lavaland shit but this actually sounds pretty cool

**Comment by EdgeLordExe** [comment]
> Lavaland chems dont matter. You could put a chem that makes you immortal and I still wouldn't use it. If I have to go to lavaland and let chemistry be raided to get a reagent then it's not op.
> The real problem is Crank: as it is it's the only combat drug that provides decent stun reduction without making you drop shit or causing brain damage, which is nice. It's a nice niche drug that I sometimes make and mix with other stuff like meth.
> If you wanna make a lavaland chem that is twice as effective as meth, go for it. Don't take away a decent on-station drug by locking it behind lavaland and making it "OP" please.

crank is worse in every regard than meth currently. i dont care that 3 people made it in the past monh.

**Comment by GuillaumePrata** [comment]
If we are going to start having more stuff in lavaland for the crew to do, which I think its a good thing, we should need better ways for miners too cooperate with other jobs first, this new meson alone is great IMO.
I used the chat program on the tablets as a pseudo GPS map when exploring the place for geysers in the past, some way to easily share coordinates with others would be another great step to making exploring for geysers fun.

**Comment by EdgeLordExe** [comment]
> If we are going to start having more stuff in lavaland for the crew to do, which I think its a good thing, we should need better ways for miners too cooperate with other jobs first, this new meson alone is great IMO.
> I used the chat program on the tablets as a pseudo GPS map when exploring the place for geysers in the past, some way to easily share coordinates with others would be another great step to making exploring for geysers fun.

I'm planning on adding bluespace tanks and pipes, to make making plumbing setups with geysers even easier

**Comment by ExcessiveUseOfCobblestone** [comment]
if you start putting chems in lavaland to the point where they're commonplace but the path to acquire is tedious, isn't the next step be "streamlining" how these chems are acquired, effectively nulling the balance of said chems?

It would probably be more interesting and inline with oranges reagent pipeline to replace geysers with rare plants that can be seed-extracted and grown in botany. plumbing should be station-focused (although if you want to make one in lavaland ok).

**Comment by EdgeLordExe** [comment]
> if you start putting chems in lavaland to the point where they're commonplace but the path to acquire is tedious, isn't the next step be "streamlining" how these chems are acquired, effectively nulling the balance of said chems?
> 
> It would probably be more interesting and inline with oranges reagent pipeline to replace geysers with rare plants that can be seed-extracted and grown in botany. plumbing should be station-focused (although if you want to make one in lavaland ok).

yeah i agree, but till we have this rework, this sorta stuff has to do.

**Comment by ExcessiveUseOfCobblestone** [comment]
I would personally rather wait for that rework than start investing in this system I have little interest continuing to invest in which would only make the desired state harder for someone to deal with.

**Comment by EdgeLordExe** [comment]
> I would personally rather wait for that rework than start investing in this system I have little interest continuing to invest in which would only make the desired state harder for someone to deal with.

I mean after cheese making and guns rework i will be doing chemistry

**Pull request closed without merging**
