### PR TITLE
Luxury shuttle can no longer be bought

### PR DESCRIPTION
**Pull request by Bawhoppen**
:cl: Gameplay Sanity Committee
del: Luxury shuttle can no longer be bought without admin intervention.
/:cl:

While it's alright to have silly and wacky shuttles, the luxury shuttle is definitely just too much. It looks really bad, is completely indestructible, and is just nonsensical. Obviously it also doesn't make any sense as being something which would've been sent by NT. 

Just imagine being a new player who tries to get on, then are left wondering why you can't. 

Of course, I personally kinda like the idea of a shuttle where you need to pay for better conditions, but this current one is too unfinished and too silly.

### CODE REVIEW

**Comment by cacogen** [comment]
no i don't like

**Review by Cyberboss — DISMISSED** [review]

**Comment by optimumtact** [comment]
remove it

**Comment by TheVekter** [comment]
Hot take but I agree with Bawhoppen, if we're going to do a luxury shuttle option, let's at least make it look less garbage and not require a wallet account to enter.

**Comment by cacogen** [comment]
unless someone changed it it looks for cash in hand as well as dragged cash for armless mobs
it also looks at coins and regular cash (i.e. not holochips)

**Comment by optimumtact** [comment]
I mean remove the shuttle, not my review assignment.

There's no point in keeping it around if it's unused

**Comment by optimumtact** [comment]
bro and the map file

**Comment by Shadowflame909** [comment]
How is it unfinished.

If your a new player trying to get in that's what the broke section is for.

It's a great shuttle, and these reasons for removal aren't telling me much other then you don't like it.

It'd be like removing xenobio crossbreeding because it's unfinished and a new player potentially might not understand it.

This is wack and removal for the sake of it.

**Comment by Krysonism** [comment]
The poor section should really be at least one tile wider. Right now you get chain disarmed by people trying to reach the other side.

**Comment by Iatots** [comment]
Give the ship a butler ghost role then. And a cowboy to herd the back section.

**Comment by kriskog** [comment]
Yeah, get rid of it. Its the ultimate in anti-hijack tech, seeing as you are unable to get to both compartments. The scrubs being stuck in the shitty area was funny, but this never works without indestructible walls which is dumb.

**Comment by Farquaar** [comment]
Pretty sure a lot of the issues people are raising were fixed in #45084

**Comment by cacogen** [comment]
I'm going to make a PR that widens coach by one tile and adds a third barrier between coach and the rich section for hijackers.

**Comment by Moonman121** [comment]
The poor section could be fleshed out and expanded a little to make it a bit less shit and it would be handy to announce the entrance cost in the purchase announcement, perhaps even make it possible to smash the door barrier if you hit it enough.

**Comment by carlarctg** [comment]
this is a fun shuttle that doesn't ruin the round like meteor does when bought, its 10x worse why isnt it removed?

**Comment by Bawhoppen** [comment]
@carlarctg the meteor shuttle probably also should be removed

**Comment by Bawhoppen** [comment]
#48382 is good in my opinion, maintainers can decide though

**Pull request closed without merging**
