### PR TITLE
Windows part 2: Replace MetaStation reinforced windows

### PR DESCRIPTION
**Pull request by CPTANT**
## About The Pull Request

See part 1: https://github.com/tgstation/tgstation/pull/68817

This pull request changes all low security reinforced windows in low security  areas on Metasation with regular windows. I had to look at some things at a case by case basis because the mapping of the walls isn't 100% consistent either.

Areas with normal walls that still have reinforced windows:
Arrivals
Departures
Security stations
Heads of staff offices

## Why It's Good For The Game

The security between high security areas and low security areas is better differentiated so low security areas no longer have windows that are stronger than the walls. 

## Changelog

:cl:
balance: All low security reinforced windows on Metasation have been replaced with regular windows
/:cl:

### CODE REVIEW

**Comment by san7890** [comment]
@EOBGames had some thoughts on this and how we should structure window protections in maps so I'm going to leave this PR open for him to comment and give feedback on how we should proceed with it now. There were a few inconsistencies from what I've seen, but I'm going to kick the ball up to his court since he's already fleshed out a bit of research and design thoughts in regards to how this applies. Although the aforementioned PR did indeed give us that sort of "middle ground", we'll definitely have to take slow, cautious steps in rebalancing every single map to a new standard.

Other than that- I'm not certain this is a PR that should go through until you get some more GBP on your account (by doing fixes and the like), since it'll just plunge you further into depth. If you want to get better at mapping, there's definitely some things you can visually fix around the codebase (do reach out to me if you are uncertain where to start). Anyone else can merge it of their own volition, I just wanted to put my thoughts down thus far.

**Comment by CPTANT** [comment]
> Also, (even though I disagree with un-reinforcing solars) you only changed 3/4 of them.
> 
> image

The walls of the solars are currently inconsistent, 3 of them have regular walls and this one has reinforced walls. I put regular windows on the ones that have regular walls and reinforced windows on the one that has reinforced walls

**Comment by CPTANT** [comment]
Will make some changes later today

**Comment by CPTANT** [comment]
Could we please resolve this? We have already discussed this to death, everyone was in favour of this solution when this was discussed:

https://github.com/tgstation/tgstation/pull/66529

https://github.com/tgstation/tgstation/pull/68817#issuecomment-1200117260


>Other than that- I'm not certain this is a PR that should go through until you get some more GBP on your account

I would have really preferred it if you said this on part 1 and not halfway through, I would have just made one huge PR instead of splitting it up into multiple parts.

**Comment by san7890** [comment]
@EOBGames @Maurukas I am not in a position to where I can review this PR within the next week.

Anyone who believes this is worth merging may lift the DNM.

**Comment by EOBGames** [comment]
okay, right, sorry again for the delay, review follows:

for the most part, this is fine following our discussion on discord earlier, but there's a few parts I'd like addressed

- There's still a few areas where there are non-reinforced windows facing space:
Engineering Maintenance
image
Tech Storage
image
That's all I could spot, but please double check everything on your side to make sure there's no problems.

- More general changes:
image
I feel like normal windows on the holodeck is asking for some sort of burn-test related disaster- kindly switch these back over to reinforced windows.
image
The public facing windows here (specifically the one next to the clinic door and the ones at the top of the paramedic dispatch room should be made reinforced, just to make the public facing windows on the department stronger to attack.
image
Given the inherent value of the security lathe and how this area is generally higher security, I think the sec office should use r-windows.
image
Ditto here as with medbay- public facing windows made reinforced, such that departments are externally more secure.
image
Just while you're touching windows- these could do with being made plating underneath.

I think that's everything I personally feel needs fixed post our discussion earlier.

**Comment by CPTANT** [comment]
But that just means everything is once again reinforced windows. I'd much rather buff the regular windows more than having no distinction between departments again anyway.

**Comment by CPTANT** [comment]
I am buffing windows more

**Pull request closed without merging**
