### PR TITLE
Adds database tracking to maintenance pills

### PR DESCRIPTION
**Pull request by Time-Green**
I originally added maintenance pills, and while already perfect, I felt like polishing them a bit. I didn't do much, just:

- Maintenance pills now track a players score. Gotta eat em all to get that leaderboard highscore!
- More names and decriptions for maintenance pills, most of them suggestions from the old PR
- Renamed floorpill to pill/maintenance in code because that's what they are, no idea why I didn't originally do it

I've also polished the sprite a little bit, because it always looked a bit _too_ shady
image
(Below is old sprite, above is new sprite)

:cl:
add: Some assistants have started tracking everyones maintenance pill consumption. Will you hold the record?
/:cl:

### CODE REVIEW

**Comment by Tlaltecuhtli** [comment]
floor pill is more iconic

**Comment by Time-Green** [comment]
> floor pill is more iconic

floorpill is what chemists throw on the floor, maintenance pills are more mystical. The rename is just for my own code OCD, it doesn't affect a single player

**Comment by dragomagol** [comment]
Blessed be

**Comment by cacogen** [comment]
I know it's bikeshedding but the name string should be floorpill, not floor pill. I can let go the sprite change which is basically imperceptible and changing the bottle name from "bottle of floorpills" to "bottle of maintenance pills" (which is soulless). George Lucas.

**Comment by Fikou** [comment]
floor pill is more iconic

**Comment by Cyberboss** [comment]
> while already perfect

This negates any motivation for change

**Review by Cyberboss — APPROVED** [review]

**Pull request merged**
