### PR TITLE
Diseases will properly make new symptoms instead of sharing the same for everyone

### LINKED ISSUE #30009: Virus symptoms sometimes stop working in the middle of a round
In some rounds, when I make a healing virus it suddenly stops working in the middle of the round. So mid-round, if I get damaged and I have a symptom that should heal me, it would fail to do so even though earlier in the round the virus was working fine. I would check the PANDEMIC and it would say I  still have the virus.

I think this should be given some attention because that means in some rounds it pretty much nullifies a whole job.

Thank you!

Round ID: 74891

### PR DESCRIPTION
**Pull request by XDTM**
This seemed to work, for some reason. I'm not questioning it.

:cl: XDTM
fix: Viruses will now be able to affect more than one person at a time.
/:cl:

Fixes #30009

### CODE REVIEW

**Review by Cyberboss — COMMENTED** [review]
Only thing this was missing was copying the id. How does that fix it?

**Comment by XDTM** [comment]
On further testing it turns out that symptoms switch activate on a random infected instead of independently, so i thought it was fixed. Time to find the real solution

**Comment by XDTM** [comment]
Hey, turns out that blindly copying all the damn vars when transmitting a virus causes issues

**Comment by XDTM** [comment]
Blacklisting symptoms did the trick, since they're handled in New() already

**Review by Cyberboss — APPROVED** [review]

**Pull request merged**
