### PR TITLE
Fixes malf camera upgrade appearing on security camera consoles

### PR DESCRIPTION
**Pull request by MrMelbert**
## About The Pull Request

Wow that was easier than I thought

Malf AI camera upgrade no longer shows up camera consoles. 
Advanced Camera consoles probably still show it but those are harder to get so someone else can fix those

## Why It's Good For The Game

It is admittedly very funny to instantly valid a malf ai but probably not fun

## Changelog

:cl: Melbert
fix: Malf AI's xray camera upgrade no longer shows on station security camera consoles
/:cl:

### CODE REVIEW

**Review by ZephyrTFA — APPROVED** [review]

**Comment by Helg2** [comment]
I though it was a feature xd

**Comment by moocowswag** [comment]
It technically has been for a long time, an actual meta that people have consistently played around on terry and im surprised it took this long for the codebase to catch wind of it.

**Comment by san7890** [comment]
yea i still think that this should be an associated "give" in the balance relationship when you deploy this upgrade but i do also agree that it is kinda silly that you can be ousted in such a simple manner. i'm okay with this pr at the end of the day but i did truly feel like it was a great way to balance this malf AI ability (but it was never explicitly outlined so w/e)

**Comment by moocowswag** [comment]
At the end of the day if you bought the camera upgrade you got noob baited and probably arnt an experienced malf ai player, its not necessarily distinctly a balance issue and more like another reason why this game is hard on new players

**Pull request merged**
