### PR TITLE
Allows adminspawning of portals

### PR DESCRIPTION
**Pull request by silicons**
Anything that is making this should be setting its vars manually so this probably won't be an issue.

### CODE REVIEW

**Comment by Cyberboss** [comment]
>Buffing admins

**Comment by kevinz000** [comment]
:(

**Comment by Armhulen** [comment]
>24 hours

**Comment by Armhulen** [comment]
reopen this SHIT

**Comment by SgtxRootbeer** [comment]
>buffing admins

**Comment by DoctoreMad** [comment]
This PR should add 1 vitamin to the powercrepe while its here.

**Pull request merged**
