### PR TITLE
Fixes welding fuel tanks potentially exploding multiple times

### LINKED ISSUE #17112: Fuel tanks occasionally do WAY too much damage
I've deal with a couple ahelps where someone shot a welding tank from 5-7 tiles away and were crit (from full health) by it.

Couldn't reproduce it and the logs for that kind of stuff are really spotty, so I just wrote it off.

Was testing the mech missile launcher, comparing it to Fuel Tank explosions. 

Set off the fuel tank with a missile at ~4 tiles away in a 550hp Seraph and the Seraph instantly exploded. I've been able to reproduce it occasionally using missiles on fuel tanks.

Edit: Been having difficulty reproducing it but I'm convinced it has something to do with spotty explosion code where some confluence of factors results in stuff getting hit much harder than it should. I was able to observe a similar effect on a minibomb that was able to 1-shot a Seraph from 4 tiles away despite prior and subsequent tests showing it doing only 60 damage from 1-tile away.

### PR DESCRIPTION
**Pull request by ChangelingRain**
Fixes #17112

### CODE REVIEW

**Comment by KazeEspada** [comment]
Bad fix. The question is why is boom() being called multiple times per explosion.

**Comment by ChangelingRain** [comment]
Whoever did this didn't consider that explosions trigger the boom() proc, which triggers an explosion. It's only not infinite because it's being deleted.
And frankly this IS how you fix it, you can't make an explosion orange().

**Comment by KazeEspada** [comment]
I guess explosions are supposed to trigger on their own src... at according to the code. Seems kinda weird to do so.

**Comment by MrStonedOne** [comment]
no... something is up

the qdel() should be getting called first. thats why there is a sleep in explosion code. let me take a look at this.

**Comment by coiax** [comment]
I see this mention of orange() a couple of times. What does it do?

**Comment by MrStonedOne** [comment]
orange is like orange, but doesn't include the center turf.

**Pull request closed without merging**
