### PR TITLE
New Boxstation mining shuttle

### PR DESCRIPTION
**Pull request by WJohn**
## About The Pull Request
This adds a new, somewhat larger (7x10 as opposed to 5x7) mining shuttle for use on boxstation. Really though, the intent of this PR is to push for ninja's power cord fix, allowing for shuttles that can charge from docking with the station, should they have power cables to connect! This shuttle is all set up for that. It'll run out of power if you leave it sitting on lavaland for too long, so watch out!

Also, thanks to ninjanomnom for the code!

## Why It's Good For The Game
Paving the way for new shuttle mechanics is always good. In this case, it's to focus more on pods that fly off from their motherships now requiring power, and to eventually return home to charge. I plan to make another PR to further expand this to other shuttles.

## Changelog
:cl: WJohnston
add: New boxstation mining shuttle! It paves the way for little pod-like shuttles needing to return home where they can charge, though this needs to be expanded to other shuttles as well.
/:cl:

### CODE REVIEW

**Comment by ninjanomnom** [comment]
image

**Comment by MrDoomBringer** [comment]
Really sexy shuttle I love the idea of a criminal hiding in the cockpit or something.

@WJohn Do you think you could add this to another station, though? Box is gonna get removed from the rounds once #43876 gets merged <sup>(i think)</sup>.

**Comment by MrDoomBringer** [comment]
Really sexy shuttle! I love the idea of separating the cockpit from the rest of the shuttle, I feel like lots of fun shenanigans can take place aboard those things now.

@WJohn My only issue is, do you think you could add this to another station as well? Box is gonna get removed from rounds once #43876 gets merged (i think).

**Comment by Jalleo** [comment]
Box station is the standard until it isnt.

**Comment by MrFluffster** [comment]
Maybe make the airlock a glass one so it feels a little less cramped.

Besides that, I really dig it

**Comment by nemvar** [comment]
This is a nerf to the "10 ashwalkers hiding in the box and throwing spears at at the miner when he launches the shuttles" strategy. Downvote from me.

**Comment by Barhandar** [comment]
Also known as "ha ha, fuck you miners, you're forever stranded on lavaland" because the changes to lavaland seemingly don't accomodate for charging, only for increased shuttle size.

**Comment by Jalleo** [comment]
There is a teleporter beacon and pacman with smes threre.

**Comment by Barhandar** [comment]
Which is completely irrelevant to my point, which is that whole "shuttle can get stuck somewhere" is a bad idea, but if you're so intent on implementing it anyway, the base should be changed to be able to charge it without rewiring manually. Also, shuttles originally ran on oxyplasma burnmix, _that_ coming back when?

**Comment by MrDoomBringer** [comment]
@nemvar @MrFluffster I really like the opaque door, but I think it would be good if it was a normal shuttle door, one without mining access.

**Comment by zxaber** [comment]
The biggest issue is if all the miners die and like half an hour later somone decides to pick up the gauntlet and take over. Though, I suppose the teleporter is always an option, don't forget the inducer.

For stranded miners, they could call for help. Alternatively, there's a coil of wire in the toolbox on the outpost, right? In case of emergency, pop the floor tiles up and let the shuttle leach off your outpost grid.

**Comment by ninjanomnom** [comment]
Wjohn probably just forgot to actually cable up the lavaland side, when I requested the mapping of this from him we mainly talked about the shuttle potentially being unable to move if it sits at one side that had run out of power for a while.

**Comment by zxaber** [comment]
There's nothing wrong with the Lavaland side just not being set up for it. Let the players solve the issue. If nothing else, it's a good intro to wiring for the players that choose miner as their first or second role.

**Comment by ninjanomnom** [comment]
The goal of this was mainly to get a shuttle which made use of power cords across boundaries. I'd prefer to have as few gameplay changes resulting from that as possible.

**Comment by Barhandar** [comment]
@zxaber you can't wire powered networks without insuls, and miners WILL forget to turn power off.

**Comment by zxaber** [comment]
You *can* if you're lucky. There's a good chance you'll be shocked but it's not guaranteed. There's a medkit with ointment on the outpost, and by wiring backwards (shuttle to outpost) you can reduce it to a single dice roll.

**Comment by WJohn** [comment]
I quite intentionally did not leave any charging on lavaland, only on the station. There's a battery in the cockpit in case you run out of power for this exact situation, and the APC (and battery in question) are both 10k cells.

**Comment by zxaber** [comment]
if you intend to make the APC battery replaceable, make sure that the APC is default unlocked. Otherwise it requires hacking for miners to unlock (which carries shock risk)

**Comment by WJohn** [comment]
Done.

**Comment by SpaceManiac** [comment]
> allowing for shuttles that can charge from docking with the station, should they have power cables to connect!

:tada: :tada: :tada: :tada:

**Pull request merged**
