### PR TITLE
Improve extended examination text for many objects

### PR DESCRIPTION
**Pull request by SpaceManiac**
Plurality, capitalization, punctuation, and item icons have been improved. Status displays now show the same text on examination that they do visually. Inducers only show a success message when they actually succeed.

:cl:
spellcheck: Grammar when examining objects has been improved.
/:cl:

### CODE REVIEW

**Comment by nicbn** [comment]
Use parentheses like use(s)
Not slashes like use/s

**Comment by RemieRichards** [comment]
@nicbn ```\s``` is a byond macro that automatically adds an s if the last embedded variable (eg: ```[some_var]```) is plural.

**Comment by nicbn** [comment]
Fucking byonb memes

**Comment by Cyberboss** [comment]
Confrictur

**Comment by SpaceManiac** [comment]
Fixed

**Pull request merged**
