### PR TITLE
Sailor outfit

### PR DESCRIPTION
**Pull request by Militaires**
Added a sailor outfit to autodrobe

:cl: BASILMAN YOUR MAIN MAN
add: Added a new sailor outfit to the autodrobe, now you can play sailors vs pirates.
/:cl:

edit: made this different from the underwear version in terms of having a collar, pants and that sort of shit

### CODE REVIEW

**Comment by TehZombehz** [comment]
I was hoping I was able to say 'By the power of the moon, I shall robust you' but this is not that kind of reference, I am sad.

**Comment by Kromgar** [comment]
@TehZombehz we already have female sailor uniforms

**Comment by TehZombehz** [comment]
@Kromgar not good enough or magical ones.

**Comment by dannno** [comment]
thought it would be a cute girl one 👎

**Comment by Militaires** [comment]
@danno @Kromgar ~~anime sucks dick and so do you~~

we already have a sailor moon outfit 2 maybe

**Comment by Supermichael777** [comment]
add flintlocks

**Comment by Cheridan** [comment]
that doesn't look like a sailor at all

**Comment by dannno** [comment]
yeah just looks like a stripey shirt wth

**Comment by Militaires** [comment]
@cheridan @danno 
http://cdn.shopify.com/s/files/1/0070/1922/files/French-Sailors-in-Breton-Stripes_1.jpg?5624
that's what sailor outfits are, unregistered fishermen and seaman lackeys also wore similar stuff including vertical sprites and those pants instead 

@KorPhaeron 
what the hell

**Comment by KorPhaeron** [comment]
Someone is touching every human and clothing file right now

**Comment by dannno** [comment]
yeah well those guys clearly have a few things extra that actually identify them as sailors don't they
like you picked the least recognizable piece of the ensemble

**Comment by Militaires** [comment]
@danno maybe but those would be in the jacket and neck and hat slots and shit so yeah

**Comment by dannno** [comment]
I don't understand quite why that would stop you but ok

**Comment by FantasticFwoosh** [comment]
Looks like a football hooligan, sorry.

**Comment by Cheridan** [comment]
Those stripes are horizontal, not vertical. There's kind of a big difference, and as a matter of fact I'm pretty sure we already have a horizontally-striped tshirt as an underwear option rendering this moot.

**Comment by PKPenguin321** [comment]
Yeah, I was gonna say I'm like 99% sure we already have this

**Comment by Militaires** [comment]
@danno cause im making just the uniform now man

@PKPenguin321 @Cheridan different color and no pants but ill change the stripes direction

this is an awful lot of discussion for just a generic fukken costume for autodrobe

**Comment by MrPerson** [comment]
I've never seen a sailor, real or fictional, wear a shirt with vertical red and white candystripes before.

**Comment by Militaires** [comment]
@MrPerson yeah the stripe direction was fucked ill change the colour now too come to think of it, thanks.

**Comment by Militaires** [comment]
@Cheridan @MrPerson @PKPenguin321 
is this better fams

**Comment by dannno** [comment]
yeah thats better idk whats with the brown on the collar but whatever

**Comment by Militaires** [comment]
@dannno supposed to be buttons i see they're not working ill delet

also delet your dislike you massending shitfuck eat penis in your fuckface you cock fuck monkey ass wanker from the depths of shit - beepsky

**Pull request merged**
