### PR TITLE
Vitiligo Level Bugfix

### PR DESCRIPTION
**Pull request by Nabski89**
:cl: 
fix:  	Re-Vitiligo Levels to match wiki.
/:cl:

Matches the wiki now. Lvl 4 goes back to having 10 items, lvl 5 to 7.

### CODE REVIEW

**Comment by XDTM** [comment]
:+1: level 4 is overcrowded

**Comment by Nabski89** [comment]
If I get ambitious I'm going to combine some infections that have opposite effects where they do one or the other depending on positive or negative stage speed, and otherwise move some stuff around to even things out.

It takes longer to get weight even than a full healing virus because of how much was on 4. (assuming you don't care about stage speed).

**Comment by XDTM** [comment]
A lot of the issue is that byond's RNG is borked and gets stuck on the same set of numbers for a lot of time, or so it feels. Also healing virus don't scale with stage speed anymore so don't bother.

I kinda left the viro rework unfinished and as a result symptoms are severely underpowered, especially harmful ones.

**Comment by optimumtact** [comment]
What makes the wiki the source of truth?

**Comment by AnturK** [comment]
Spreading these around is fine, virology is rng hell anyway no need to reinforce it.

**Pull request merged**
