### PR TITLE
>2 cost for 4 second stun per sharp item held, instant aggro grabs, theft of items from hands into your own hand, 3 second stun on harm long distance, pudge hook on help

### PR DESCRIPTION
**Pull request by Iamgoofball**
what the fuck is this cancerous bullshit

fixes OP changeling bullshit

### CODE REVIEW

**Comment by kevinz000** [comment]
and this is how you get gitbanned

**Comment by ExcessiveUseOfCobblestone** [comment]
JUST MAKE IT MORE EXPENSIVE

**Comment by HankMoodyExperience** [comment]
daily reminder if you try grabbing a stun baton thats on out of someone's hand you will literally rek yourself due to throwcode

**Comment by Iamgoofball** [comment]
@kevinz000 I asked for a close reason and none was provided so I have to assume it's a mistake.

**Comment by Iamgoofball** [comment]
@HankMoodyExperience AAAAAAAAAA

**Comment by ChangelingRain** [comment]
Actually try fixing or tuning it maybe instead of doing ridiculous bullshit like this!

**Comment by Iamgoofball** [comment]
everything about this is broken and shit though, rip

**Comment by Haevacht** [comment]
Oh this PR again.

**Pull request closed without merging**
