### PR TITLE
[NO GBP] Fixes blindness icons on lower station z-levels

### LINKED ISSUE #70593: Typing indicators show over crit overlay
Reporting client version: 514.1583

## Round ID:
[192502](https://scrubby.melonmesa.com/round/192502)

## Testmerges:
- [Swaps sleep() to use SECONDS define](https://www.github.com/tgstation/tgstation/pull/70452)

## Reproduction:
image

### PR DESCRIPTION
**Pull request by Tastyfish**
## About The Pull Request

Fixes problem from #70276
Fixes #70593

I previously tested that footsteps worked when hearing them from a lower Z-level but forgot to test if you can see them while on a lower z-level.

It didn't occur to me that offsetted planecube planes wouldn't work with being over the fullscreen blindness mask past the top level but that makes sense in retrospect. 

So the blindness effects (via `play_fov_effect()`) are now on the fullscreen plane. Partially reverted doing this with manually talking bubbles as well so they look normal again, and then added a FOV effect as well for chat bubbles.

<details>
<summary>Chat FOV Effect</summary>

image

</details>

**NOTE:** Runetext is in general also only above the blind mask on the highest station level and below on others for the same planecube issue but that's a whole other can of worms.

## Why It's Good For The Game

Bugfix

## Changelog

:cl:
fix: Blind people can see footsteps again when on lower station levels.
/:cl:

### CODE REVIEW

**Comment by san7890** [comment]
Fixes #70593?

**Comment by LemonInTheDark** [comment]
ok so I missed the first pr, but 
why do we need a separate plane for typing effect exactly?

Also, why add an fov effect for typing? surely people shouldn't see that if they're blind

**Comment by Tastyfish** [comment]
> Fixes #70593?

Correct, you can't see the normal typing effect anymore while in crit.

However, you can see the FOV effect just as you can see all FOV effects, such as footsteps, while critted. I think you always could, unless I'm misremembering.

image

**Comment by LemonInTheDark** [comment]
> There isn't a seperate plane for the typing effect, as I moved that back to being a normal mob overlay.
> 
> The only separate plane involved is for the FOV (blindness) effects, such that they sit in front of the fullscreen blindness mask, which itself is over the normal game planes of course. Perhaps blindness has to be handled completely differently post-plane cube, I'm not sure.

Why could we not keep them on the same plane, but raise their layer?
Plane masters have a (small but existent) clientside cost and structural complexity, and I want to keep their count as low as is sane

> The logic of having a separate FOV effect for typing is that typing represents the person talking, which is conceptually heard. People can still hear the result when the talker presses enter. It helps a blind person know someone is talking to them, as with the other FOV icons.
> 
> Note that the sign language overlays do not create the FOV effect.

@MrMelbert please develop an option on this blind man
Thx LU

**Comment by Tastyfish** [comment]
> > There isn't a seperate plane for the typing effect, as I moved that back to being a normal mob overlay.
> > The only separate plane involved is for the FOV (blindness) effects, such that they sit in front of the fullscreen blindness mask, which itself is over the normal game planes of course. Perhaps blindness has to be handled completely differently post-plane cube, I'm not sure.
> 
> Why could we not keep them on the same plane, but raise their layer? Plane masters have a (small but existent) clientside cost and structural complexity, and I want to keep their count as low as is sane
> 
> > The logic of having a separate FOV effect for typing is that typing represents the person talking, which is conceptually heard. People can still hear the result when the talker presses enter. It helps a blind person know someone is talking to them, as with the other FOV icons.
> > Note that the sign language overlays do not create the FOV effect.
> 
> @MrMelbert please develop an option on this blind man Thx LU



> > There isn't a seperate plane for the typing effect, as I moved that back to being a normal mob overlay.
> > The only separate plane involved is for the FOV (blindness) effects, such that they sit in front of the fullscreen blindness mask, which itself is over the normal game planes of course. Perhaps blindness has to be handled completely differently post-plane cube, I'm not sure.
> 
> Why could we not keep them on the same plane, but raise their layer? Plane masters have a (small but existent) clientside cost and structural complexity, and I want to keep their count as low as is sane

Keep them on the fullscreen plane, you mean?

**Comment by LemonInTheDark** [comment]
I guess I don't understand why they aren't still on it

**Comment by Tastyfish** [comment]
> I guess I don't understand why they aren't still on it

They weren't before; they were on the high game plane, placing them underneith the fullscreen plane.

**Comment by LemonInTheDark** [comment]
god fucking damn it

**Comment by Tastyfish** [comment]
> god fucking damn it what? how did that get through

Hah, who knows. I can throw it on the fullscreen plane and remove my extra one though, one moment.

**Comment by Tastyfish** [comment]
@LemonInTheDark I've placed the FOV effects on the background plane, and used the EFFECTS_LAYER modifier to force them to go over the blind mask, since otherwise atoms that `screen_loc` go in front of non-screen_loc atoms regardless of layer.

**Comment by san7890** [comment]
> > Fixes #70593?
> 
> Correct, you can't see the normal typing effect anymore while in crit.

Can you add `Fixes #70593` to your PR body, please?

**Comment by Tastyfish** [comment]
> > > Fixes #70593?
> > 
> > 
> > Correct, you can't see the normal typing effect anymore while in crit.
> 
> Can you add `Fixes #70593` to your PR body, please?

Done.

**Comment by Tastyfish** [comment]
@LemonInTheDark Do you still have any hangups with the current state of this PR?

**Comment by LemonInTheDark** [comment]
Oh you already fixed it.
If you want to be really based document that aspect of layering in visuals.md, so people have an excuse when I get annoyed at them for no reason in future

**Pull request merged**
