### PR TITLE
Slowdown from inhand items

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
So we can have heavy weapons (like hammers or big guns or heavy shields)

### CODE REVIEW

**Comment by Supermichael777** [comment]
Bass cannon when.
a lot of meme items need this + clickdelay so you cant run around spamming gravity hammer.

**Comment by Incoming5643** [comment]
Held clothing probably shouldn't be exempt, both because it's kind of counterintuitive and it adds two istype checks every single time someone tries to move.

**Comment by KorPhaeron** [comment]
@Incoming5643 

Maybe this should be scrapped then because people got mad when clothing wasn't exempt

**Comment by Incoming5643** [comment]
Well I mean public opinion never stopped people from doing stuff like this before, but if has to be this way maybe a var would be better. I mean lets be real here, this is about spacesuits and pretty much nothing else.

**Comment by KorPhaeron** [comment]
We more or less removed all the slowdown on space suits anyway so maybe its not as big a deal now

**Comment by WJohn** [comment]
Now we just need someone to actually go through all the weapons in the game and make the whole one-handed, optionally-two-handed, forcibly-two-handed stuff consistent and frequently used, because it isn't at all consistent.

**Pull request merged**
