### PR TITLE
[DNM till #34243]Exchanges catpeople for moths

### PR DESCRIPTION
**Pull request by Iamgoofball**
Requires #34243

Making the PR for Joan,  proof of authorization
fugg

### CODE REVIEW

**Comment by Iamgoofball** [comment]
DNM till moths are merged

**Comment by The-clown-known-as-Pepe** [comment]
You crossed my design

**Comment by Kromgar** [comment]
Goofball for president

**Comment by idontwannasignup** [comment]
The hero we don't deserve but the hero we need.

**Comment by sawrge** [comment]
paintdotnet_2018-01-11_23-25-37

**Comment by sawrge** [comment]
paintdotnet_2018-01-11_23-40-11

**Comment by Kromgar** [comment]
Holy shit the memes are fucking kill me

**Comment by sawrge** [comment]
paintdotnet_2018-01-11_23-52-50

**Comment by sawrge** [comment]
paintdotnet_2018-01-11_23-55-51

**Comment by Mack3r3l** [comment]
ALL CHECKS HAVE PASSED

LET THE MEMES BEGIN

**Comment by CrackParrot** [comment]
> ALL CHECKS HAVE PASSED
   LET THE MEMES BEGIN

I am ready for this shitshow.

**Comment by KorPhaeron** [comment]
Going to regret saying this but this is not actually a terrible idea

Moths appeal to the same weeb crowd who wants to play a cute fuzzy thing while still plausibly being a sci fi bug monster while catgirls are just catgirls

**Comment by The-clown-known-as-Pepe** [comment]
@KorPhaeron 
image

**Comment by KorPhaeron** [comment]
I swear to god I'm going to unban you if you keep posting, posts from people who dont play are the worst

**Comment by The-clown-known-as-Pepe** [comment]
@KorPhaeron why not have both and save yourself some drama

**Comment by KorPhaeron** [comment]
cause catgirls are going to continue to be drama down the line

**Comment by The-clown-known-as-Pepe** [comment]
pretty sure all the drama i keep seeing is from people attempting to remove them, or being salty about them

**Comment by The-clown-known-as-Pepe** [comment]
remember last time they were disabled in config?

discord chat was comparable to a twitch chat

**Comment by SgtxRootbeer** [comment]
@KorPhaeron @The-clown-known-as-Pepe 
really simple, remove both kat and moth, add vox and keep lizzer, ok?


actually, remove human and flypeople while you're at it, just leave lizzer.

**Comment by The-clown-known-as-Pepe** [comment]
don't ping me and my design lead ever again

**Comment by Repukan** [comment]
Kiki Yaya

**Comment by uraniummeltdown** [comment]
based goof saving tg 👊🏽

**Comment by FantasticFwoosh** [comment]
Eh this is passable, i dont like moths but i dont like catpeople more, whilst it doesn't actively displease and remove the people who drafted in both, its a better result than the latter. Ill probably consider playing on the server again once this is merged so i can keep a eye on how its progressing.

**Comment by DaxDupont** [comment]
Kneejerk PRs are bad and you should feel bad

**Comment by KorPhaeron** [comment]
@Iamgoofball nevermind we cant risk fwoosh coming back

**Review by Tlaltecuhtli — APPROVED** [review]

**Review by lzimann — CHANGES_REQUESTED** [review]
You also need to remove admin verbs related to this.

**Comment by ike709** [comment]
Goofball once again tries to save TG from itself.

**Comment by imsxz** [comment]
just move the cat ears/tail option to moths instead of humans, so we can have catmoths. It keeps the cat players happy, while keeping the human race pure.

**Comment by Slignerd** [comment]
Even if you're gonna do this, wouldn't be it better to keep the code and simply change the config?

**Comment by KorPhaeron** [comment]
In all seriousness MSO made it pretty clear he doesn't appreciate PRs that delete config options

**Comment by Iamgoofball** [comment]
I didn't delete config options. The mutant parts option still works just fine, it just only enables/disables wings.

**Comment by Spaceinaba** [comment]
Now THIS is something I can get behind

**Comment by deep-fried-faceplant** [comment]
Cutesy features will promote the growth of lewd culture. Its upholders are already rooted deep enough in TG that outright removal won't get passed through. A compromise like this relies too heavily on removal, and while mothgirls are cutesy too, it's also definitely a step /d/eeper. Insect girls might be a elegantgentleman's classic, but this server is so far removed from the board that playing that card is about as good as a pair of twos.

Just reinstate slavery ffs, make it a part of the lore so people can whip the lewd out of these nerds.

**Comment by epochayur** [comment]
absolutely based

**Comment by Iamgoofball** [comment]
If you think whips won't increase the erp then I have a shuttle to sell you

**Comment by sawrge** [comment]
nothing can or will increase erp as erp is banned

**Comment by imsxz** [comment]
nothing can or will increase grief as grief is banned 
nothing can or will increase spam as spam is banned

adding fetish items will increase ERP my man, banned or not. that's why we have admins

**Comment by Xhuis** [comment]
I don't really get the point of this PR, removing cats is something that you have tried and failed a billion times and it's clear as crystal that this is just a veiled attempt to do to the same thing, removing them will cause *yet more* trouble because just because moths might get in doesn't mean people prefer them over the other thing they've fought for ages to keep

**Comment by Iamgoofball** [comment]
i dunno all the people who said they like cats are okay with moths instead so its a fair trade for everyone involved

**Comment by Xhuis** [comment]
why not just keep both?

**Comment by CrackParrot** [comment]
Out with the cats in with the moths.

**Comment by Bawhoppen** [comment]
Why do people feel the need to hate cats

**Comment by Xhuis** [comment]
small ears on a 32x32 sprite may constitute an XK-Class end of the world scenario

**Comment by Iamgoofball** [comment]
^

**Comment by Xhuis** [comment]
i was kidding they mean literally zilch except for people who are naturally inclined to be envious of people who can enjoy the game in small ways that aren't killing other players

**Comment by optimumtact** [comment]
dunno seems pretty popular

**Comment by Xhuis** [comment]
i am more referring to the small group of people that howl for the catpeople's removal citing outlandish reasons like fetish content despite not playing the game and having no intention to
other people who hate cats are fine

**Comment by Iamgoofball** [comment]
getting a friend into ss13:
"Why are there moth people?"
"oh they're the locals from some planet we crashed on lmao"
"Why are there lizard people"
"Same deal but it's the barren hellscape we mine ores on"
"Why are there catpeople"
"uhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh fuck"

**Comment by Xhuis** [comment]
when i talk to friends about it i usually just say that stuff like that is part of the silliness that the game encourages

**Comment by Iamgoofball** [comment]
"why is that person running into a lightbulb over and over again"
"oh it's a moth"
"why is that thing lisping"
"oh it's a lizard so people do TES memes with it"
"why is that person wearing a collar and screaming 'N-NYA~' while repeatedly hugging a very underclothed person"
"it's a ~~degenerate~~cat person i think idk could be costume which would be even worse"

**Comment by Bawhoppen** [comment]
I thought goof didn't care about lore...

**Comment by DaxDupont** [comment]
It's 2558, I'm 100% sure that people will be paying for DNA modifications for them or their future kids by then which will include weird cosmetic stuff.
People fucking tattoo their eyeballs the present day.
The spessmen universe has DNA modification already. If it can make animals, hulks and 30 copies of George melons it's not unreasonable that other functions exist. 
This is why that catgirls are freaks and don't get command roles like lizards.

**Comment by sawrge** [comment]
Goof finally reveals his sick twisted species change fetish by forcing all cats to transform into moths 

What a sick, sick fetish PR

**Comment by Potato-Masher** [comment]
Here we go. How about we remove roundstart cat parts, so if cat players really want their SICK TWISTED FETISH CONTENT they gotta get Cargonia to order cats for their parts, and then get the MD's to perform surgery to attach em. It gives Medbay and Cargonia something to do at the same time!

**Comment by Slignerd** [comment]
How about we remove roundstart IDs, so if players really want sick twisted station access, they gotta ask the HoP for job assignments.

**Comment by Qustinnus** [comment]
@slignerd how about we remove shitty strawman arguments, so if slignerd really wanted to prove their point, they gotta formulate a real argument

**Comment by kevinz000** [comment]
or how about we stop trying to get past config options with a PR removing the option to have certain mutant parts enabled?

**Comment by Iamgoofball** [comment]
Have you considered reading? The config is still there you dipshit and roundstart wings/lizard customizations are still a thing

**Comment by Slignerd** [comment]
@Qustinnus It was a shitpost, not an argument.

**Comment by Qustinnus** [comment]
@slignerd arent you the one that usually cries whenever anyone shitposts on PRs?

**Comment by KorPhaeron** [comment]
This PR is half assed but pending MSOs approval you can reopen your PR to make them donor only

**Comment by kevinz000** [comment]
@Iamgoofball you know what i mean, don't play dumb.
wait you're not playing dumb.

**Comment by BeeSting12** [comment]
Epic meme bro

**Comment by FantasticFwoosh** [comment]
Honestly @Iamgoofball could just bundle 'premium/alternative' roundstart config races into a donator pack like his *cough* last attempt #21991 if that is what @MrStonedOne  and you @KorPhaeron would be happy with.

- Admins would be able to adjust species for testing anyway and keep it exclusive.

```
		if(config.donator_races && unlock_content)

			if(!H.client.prefs.unlock_content)
				usr << "This player is not a BYOND Donator!"
				return
```

**Pull request closed without merging**
