### PR TITLE
Adds a coffee shop to more stations

### PR DESCRIPTION
**Pull request by nyozzl**
coffee
## About The Pull Request
Adds coffee shops to icebox.. delta.. and birdshot.

## Why It's Good For The Game
Adds coffee shops.. which allows people to... slurp on some wakey wakey juice...

## Changelog

:cl:
map: adds more coffee shops to stations..
/:cl:

birdshot
image

delta
image

Icebox
image

### CODE REVIEW

**Comment by sylvia-from-fulp-station** [comment]
forcing comissary to be a coffee shop kinda sad

**Comment by Aliceee2ch** [comment]
single vacant comissary on icebox and got moved to 3x3 room? booring, id prefer 3x3 coffee shop instead

**Comment by carlarctg** [comment]
mm yes make maps more homogeneous and less unique

**Comment by EmptyLullaby** [comment]
am i tripping balls or did we just get this pr with basically the exact same comments

**Comment by Loafin34** [comment]
what's the point of a cargo coffeemaker crate if it's just going to automatically spawn in anyways? i don't like it, it reminds me of those shuttles that just copy from original BYOS designs. construct a coffee shop on the station! That's way more fun.

**Comment by nyozzl** [comment]
yea... i quit

**Comment by Aliceee2ch** [comment]
> yea... i quit

not get us wrong, just coffee shops doesnt mean to be everywhere, plus on icebox its really look out of place. good pr tho.

**Pull request closed without merging**
