### PR TITLE
Auto load required nanoui files on client login

### PR DESCRIPTION
**Pull request by optimumtact**
Ready to go now
This is a port of code from baystation.

### CODE REVIEW

**Comment by optimumtact** [comment]
Long term goal here is to make nanoui as easy as possible to use

**Comment by Razharas** [comment]
Whats the difference?

**Comment by optimumtact** [comment]
You don't have to explicitly define the files to be sent to the client, it just autoloads the specified directories

**Comment by Razharas** [comment]
Now i understand

**Comment by optimumtact** [comment]
I just need to test this as working in game and then it's ready to go

**Comment by MrStonedOne** [comment]
@Razharas i just can't fucking take you seriously with that avatar.

**Comment by optimumtact** [comment]
Tested and ready to go

**Comment by RemieRichards** [comment]
@MrStonedOne I tend to just ignore it and see it as a yellow circle.
because otherwise I couldn't work with him without laughing.

**Pull request merged**
