### PR TITLE
Adds four new emojis

### PR DESCRIPTION
**Pull request by ghost**
image

In order:
:1997:
:rune:
:blob:
:onisoma:

Don't think a changelog is needed for something this small

### CODE REVIEW

**Comment by Iamgoofball** [comment]
>:1997:
i love it

**Comment by Jordie0608** [comment]
>Don't think a changelog is needed for something this small

Yeah but it can't hurt =P

**Comment by Incoming5643** [comment]
only everyone can stop changelog bloat

**Comment by optimumtact** [comment]
Please add a :paprka: emoji

I will leave it upto you to decide what the sprite does.

**Comment by Thunder12345** [comment]
OOC: Stan_Studnick: Actually somebody make a little puckered asshole
OOC: Stan_Studnick: That can be :paprika:

**Comment by Xhuis** [comment]
I got yelled at for alluding to players in my barsign PR, so as much as i would like to add a paprika emoji it's not gonna happen

**Pull request merged**
