### PR TITLE
Remove roundstart security camera headsets [DNM]

### PR DESCRIPTION
**Pull request by optimumtact**
If this still continues to be a problem we will introduce some R&D
requirements to be able to attach cameras, or consider removing them completely

See https://tgstation13.org/phpBB/viewtopic.php?f=10&t=3247&start=50

### CODE REVIEW

**Comment by RemieRichards** [comment]
:+1:

**Comment by WJohn** [comment]
Finally :+1:

**Comment by Steelpoint** [comment]
I'm still annoyed that my other PR that disallowed the AI to view Sec Helm Cameras was never merged. Either way I don't have much of a stance on the HelmCameras. 

You may as well just remove the whole feature as it was just a kneejerk addition that adds more problems than it solves.

**Comment by Supermichael777** [comment]
if were reverting based on that kind of vote we wold be reverting goon-chem. as a frequent sec player i like the added safety the cameras give. its especially helpful when your solocurity with none else on because the AI has your back and can get someone to come save your ass or open that maintenance door to let you get away. :-1: :

**Comment by Anonus** [comment]
Steelpoint, that pull never worked, I commented about that but you apparently didn't notice.

**Comment by Robustin** [comment]
Do it. 

There's nothing redeeming about helmet cams.

**Comment by optimumtact** [comment]
It seems like the consensus is to fully remove them

**Comment by Cheridan** [comment]
Yeah, if they don't come in default, then a few months from now it's going to be one of those "little things" that nobody knows you can do anyway.

**Comment by optimumtact** [comment]
kk, will do this soon (tm)

**Pull request closed without merging**
