### PR TITLE
Makes the noop turf less eyerapey

### PR DESCRIPTION
**Pull request by ShizCalev**
Changes it to a dark blue to match DM's voidspace color. This helps missing textures stand out better, and is ALOT easier on the eyes.

owzjvwr
The purple block in the lower left is the old appearance.

### CODE REVIEW

**Comment by Iamgoofball** [comment]
that's not the old appearance?

@ShizCalev If it was purple on your end you had an old version, the one in the codebase is grey and white

**Comment by ShizCalev** [comment]
@Iamgoofball Check on your end again. /turf/template_noop has no icon assigned, so it's inheriting the missing texture icon from /turf

urn5yvi

**Comment by Bawhoppen** [comment]
@Iamgoofball It is goof. I changed it so it'd be referential and helpful to identify broken floor sprites ingame

I didn't realise that it was also used for this though

**Comment by Iamgoofball** [comment]
Wtf

Just revert it back to the grey, the blue looks weird

**Review by Cyberboss — APPROVED** [review]

**Pull request merged**
