### PR TITLE
wawastation stand-in shuttle

### PR DESCRIPTION
**Pull request by mc-oofert**
## About The Pull Request
image
"Due to a recent clerical error in the funding department, a lot of funding went to lizard plushies. Due to the costs, Nanotrasen has supplied a nearby garbage truck as a stand-in. Better learn how to share spots."
## Why It's Good For The Game
every station has its shuttle

## Changelog
:cl:
add: wawastation stand-in shuttle
/:cl:

### CODE REVIEW

**Comment by mc-oofert** [comment]
> are the grinders emagged

no

**Comment by SmArtKar** [comment]
have you made the belt on by default?
also if you emag the console the grinders should also arrive emagged

**Comment by Xkallubar** [comment]
This will be absolute hell on highpop

**Comment by mc-oofert** [comment]
call this a tutorial on how to purchase a shuttle

**Review by Maurukas — APPROVED** [review]
Beautiful.

**Pull request merged**
