### PR TITLE
Station goals spawn a room on the station.

### PR DESCRIPTION
**Pull request by Nabski89**
[Changelogs]: # (Your PR should contain a detailed changelog of notable changes, titled and categorized appropriately. This includes, new features, sprites, sounds, balance changes, admin tools, map edits, removals, big refactors, config changes, hosting changes and important fixes. An example changelog has been provided below for you to edit. If you need additional help, read https://github.com/tgstation/tgstation/wiki/Changelogs)

:cl: Station Goal Loading
add: Added 3 new rooms to meta station, in one location.
del: The meta station cargo warehouse is no more.
tweak: Moved the fault to where cargo warehouse was. Increased the BSA build requirements.
/:cl:

Todo: Do something with extended.

[why]: # I feel like the station goals almost never get done, and I blame the fact that they are all gated by expensive cargo crates. By having them start on the station it is more likely that the crew will have more non antagonist related things to do. There are plans to add more goals after this, but I didn't want to do goals without having the system in place for them to work.
image
Equipment to help repair breaches, and an extra hardsuit to do it with. Likely the easiest goal.
image
Additional tracking implants, gulag IDs, and mini holding cells. The main extra material needed is glass. Send those pesky assistants to the gulag and get some real work done.
image
This one's got to change, it had a mini petting zoo for extra DNA samples, but the bees apparently have access to open that door and keep stinging me. Also WJohn hates it.

### CODE REVIEW

**Comment by ishitbyabullet** [comment]
why do bees have access to a door? didn't you give it locks?

**Comment by WJohn** [comment]
why did you keep the god damned zoo, man, it still looks unbelievably dumb.

**Comment by Nabski89** [comment]
Landmarks is because it has a new landmark.

Satellite had a new object that ended up not using so I need to clear out that change.

Area change is because it has a new area.

Library is something I'll have to fix.

Also if anyone knows how to fix the two things I said, I'd be appreciated.

**Comment by Wilchenx** [comment]
image
unreachable air alarm
apc in petting zoo
bees can open the airlock
disgusting white airlock as enternance
sideways double airlock as enternance to petting zoo instead of two windoors

image
doesn't even have a air alarm

image
the only problem with this one is that you used science colored tiles with engineering airlock

**Comment by Wilchenx** [comment]
also, what happens on extended round when all 3 objectives are avaible?

**Comment by Repukan** [comment]
If players want to do Goals, they'll cooperate and do it through any gates and so on. If players don't group to do it, then it is a playerbase issue, and no amount of coddling or hugboxing will fix that.

**Comment by Repukan** [comment]
Why don't you just make all research be unlocked roundstart since there's gates to that too.

**Comment by Nabski89** [comment]
Because there are goals I had in mind that would be balanced around having them in a stationary location, rather than able to be done anywhere you want.

I also like robustin's idea's related to dynamic map loading on the station and wanted to try my hand at it without all the robustin things in it.

**Comment by Tlaltecuhtli** [comment]
the bsa requires a big room and nothing on the right if you dont want to shoot yourself

**Comment by yoyobatty** [comment]
This is insane, a maintainer and I pitched a concept a while ago on hippie for having randomized maint rooms and this does almost exactly what I need.

**Comment by ExcessiveUseOfCobblestone** [comment]
@yoyobatty it will if you set the dimensions the same.

**Comment by Nabski89** [comment]
@yoyobatty See https://github.com/tgstation/tgstation/pull/35741 for the extended version of this. If I remember correctly the actual map spawning portion of this code was testmerged and worked correctly.

**Comment by Bawhoppen** [comment]
The mapping is not very questionable, and I don't see why we need them roundstart anyways.

**Comment by Wilchenx** [comment]
@Nabski89 do you need any help with the maps?

**Comment by 81Denton** [comment]
This is really good and I can see it being used for randomized maint areas like @yoyobatty said, or the much mentioned "let the CE pick the engine roundstart".

Map issues are no big deal since these are 7x8 tile areas that can be modified easily.

**Comment by Nabski89** [comment]
Wilchenx, I don't really need help and most of what you mentioned is minor easy fixes. I kinda liked the purple flooring on the station shield one but it's honestly cosmetic. I'm open and eager for any kind of suggestion on the first one. The offset door and non-symmetrical layout was just to try to do something different from the others.

I still need help getting it to not double load, which I suspect I'll ask around on coderbus on friday about.

Denton the maps are actually 9x9, but really could be any size you want them to be since it just loads centered on the landmark. An engine based system would likely be even easier to pull off than this, since you could just pick the engine type randomly and load from there. You'll want to look at the changes to the mapping subsystem, landmarks, lists, and the stationgoal files to see what you would want to grab to do it. In the station goal file look either under the spawngoal() proc or the machinery which was a holdover from testing loading since it didn't require a landmark for the location and is going to be deleted before this is ready.

**Comment by Ratvar** [comment]
Replace DNA vault ice biome with animal box thingie? Like wooden cargo cow box.

**Comment by yoyobatty** [comment]
The idea for random maint rooms would have a bunch of preset sized rooms stylized to different department themes or even look like a typical maint room or have one that looks like a torture chamber. The loader for those rooms could just be placed over designated rooms so size will always remain consistent.

**Comment by Nabski89** [comment]
Good news on this, the double spawning was because I was impatient and when the announce is used before on_report auto triggers with the command report it would also trigger on the command report!

The code works.

I'll likely have just one goal spawn during extended by setting a "spawned=false" flag and just setting it to true with something spawns. Disappointing, but it works. I suppose I could also just change how extended works.

Air alarm is fixed.

image
Added two clothing closets and backup generator room for when the power is out so the DNA Vault fulfills it's lore purpose of recloning the station power is easy and you don't run around nude. 

Unintended sprite changes are fixed.

**Comment by yoyobatty** [comment]
Is it map merged..?

**Comment by Nabski89** [comment]
I believe that's happening in someone elses PR.

**Comment by ExcessiveUseOfCobblestone** [comment]
everything ok anon?

**Comment by Nabski89** [comment]
I'm struggling with tgui trying to come up with something for extended. I'm considering dropping the "all goals are open on extended" part of it anyways. I'm also annoyed by the door keeping all the air out that sits there for the first two minutes until the goal is loaded on the station report.

Yes it could just be loaded instantly, but I rather like it being a touch later since there's some solid gear in each of these that I'd rather not see roundstart rushed by people.

I did at least fix the having 300 pulls part this weekend.

I'm also lazy so the stale tag is accurate.

**Pull request closed without merging**
