### PR TITLE
Resprites ventriloquist dummy

### PR DESCRIPTION
**Pull request by Horatio22**
## About The Pull Request

Resprites the ventriloquist dummy  #https://github.com/tgstation/tgstation/projects/6#card-2814241

## Why It's Good For The Game

The current sprite is just the assistant doll cut in half. This gives it a unique sprite and also makes it so that the hands line up with the item better than the current sprite. It's also a lot creepier (and animated!)

Current sprite:
image
(Note: this is the _left_ in-hand sprite)
image
image

Proposed change:

image
image
image

The eyes are a little darker in the final version due to the light blue being difficult to see in-game, but here's what it looks like with eyes moving and mouth opening
ezgif com-resize
ezgif com-resize(1)

## Changelog
:cl:
imageadd: gives the ventriloquist dummy a new, animated sprite
/:cl:

### CODE REVIEW

**Review by Mothblocks — APPROVED** [review]
Code ✔

**Comment by Twaticus** [comment]
please remove the old inhands since they seem to not be used for anything else

**Comment by Horatio22** [comment]
> 
> 
> please remove the old inhands since they seem to not be used for anything else

Would it be alright to fix the positions (and size) of those sprites so they can be used for the assistant doll in-hand, or would you rather me just remove it?

**Comment by maxymax13** [comment]
no soul

**Comment by Horatio22** [comment]
> 
> 
> > > please remove the old inhands since they seem to not be used for anything else
> > 
> > 
> > Would it be alright to fix the positions (and size) of those sprites so they can be used for the assistant doll in-hand, or would you rather me just remove it?
> 
> oh yeah that would be cool 👍

I ended up shrinking the sprite and just renaming it to assistant anyway so it's easier if anyone decides to add in-hand sprites for the other figures further down the road

**Review by Cyberboss — APPROVED** [review]

**Pull request merged**
