### PR TITLE
Further changes to the ranged stun system

### PR DESCRIPTION
**Pull request by ghost**
- Stamina damage no longer uses the inherited 'laser' flag to determine damage cutoff. Most armors in the game had a lot of laser protection, but very little stun (energy) protection, thus disablers were overall shit.
- Renamed advanced taser to hybrid taser.
- Hybrid taser now has 20 disable shots, like the egun. It still has 5 taser shots.
- Bulldog shotguns shoot actual taser shells again, complete with range nerfs etc instead of stamina
- Beanbag shells do significantly more stamina damage so the bartender can shit on looters again
- The detective's revolver does instastun again as well as stamina damage. Does less stun than it did before, however.
- Taser electrode hitsound has been changed to paradise's !REAL IMMERSIVE! taser clicking, but I shortened it to about 2 seconds.
- .45 ammo (C-20r mainly) buffed to deal even more stamina damage, does not instastun individually but will seriously shit on people's movement and will instastun if set on two round burst
- l6 saw now has an extremely slow firing but also immensely effective 5 round burst for suppression (5 rounds of 60 brute each, you do the math.)
- Adrenaline implants and epinephrine overdose changeling ability will now flush your body of around 70 stamina damage
- Automatic weapons (mag-fed pistols, smgs, rifles, lmgs) can now be tactically reloaded by hitting them with a magazine (it will replace the magazine with the new magazine, dropping the old one on the ground)
- Added an LMG and a 6-shot grenade launcher to the syndicate borg to replace the laser gun and ebow. The LMG will automatically regenerate ammo like the ebow did, does no stun, but does 35 damage and shits on anything with a nearly bottomless magazine. The grenades will also wreck people since the syndie borg's ez mode stuns have been removed for compensation and the borg still remains 40tc.
- Gave the detective a telebaton to help him in arresting perps so he doesn't have to fill them with so much lead.

**Ebow overhauled to a less ezmode 'pay for free unlimited stuns!' system:**
- Will now take ammo, doesn't regenerate
- Price reduced to 10tc, can buy two now for COOL ASS DUAL WIELDING i guess? Can also buy one with an implanted uplink, to show security who's boss if they put you in perma.
- Ammo costs 2tc for 4 bolts
- Bolts shot by xbow can be reused even if they hit targets.
- Default xbow has 10 shots before running out.

**Added seclite attaching for hybrid tasers/eguns**

jiff
- Smack a hybrid taser or egun to attach a seclite. Press action button to toggle on and off.
- Hit with screwdriver to remove, but why would you want to do that anyway?

**C-90gl renamed to M-90gl to avoid C-20r confusion**
- Now a three-shot burst
- Smack it with a 40mm grenade to swap the spent shell out for the new one (having to switch to grenade mode to unload the spent grenade was obnoxious)

### CODE REVIEW

**Comment by paprka** [comment]
Now featuring: Lots of bugs! Probably.

Fixes
https://github.com/tgstation/-tg-station/issues/6535

Countless other things too probably

**Comment by Steelpoint** [comment]
All good aside from the sprite change for the C90gl.

**Comment by Fox-McCloud** [comment]
I'll second Steelpoint's opinion--visually, the C90gl was a very attractive gun--the AK74u is kinda...ugly, but that's my subjective opinion.

Also glad to see our taser sound being utilized here; it goes very very well with the jitter effect.

**Comment by paprka** [comment]
TBH everyone interpreted the c90 like an SMG which it isn't

**Comment by Steelpoint** [comment]
To be fair pap, in SS13 the only difference between a SMG and a Assault Rifle is in the name. Simply renaming the C90gl Assault Rifle to the C90gl Carbine or SMG would work.

**Comment by Fox-McCloud** [comment]
Oh, one suggestion for flashlight attachments. If a gun can have a flashlight attached to it and it has a force less than 9, have it set the force of the gun to 9, as well; perhaps the w.class should also go up by 1 when the flashlight is attached?

**Comment by optimumtact** [comment]
AK is copyright, we cannot install to serb

**Comment by hornygranny** [comment]
👮 E ⏩

**Comment by Dorsisdwarf** [comment]
This is brilliant change, really cool, makes the L6 a rightly-feared heavy gun instead of a Huge Waste Of Your Time, encourages seclite use, fixes stuff

My only two dislikes are 1) That new sprite, ew. 2) Making the hybrid taser as robust as the eguns/dedicated disablers.

**Comment by Atskadan** [comment]
yeah like everyone else the only thing i dont really like is the new c90
also i dunno about the new ebow either, but if its cheaper it should be fine

**Comment by paprka** [comment]
It's not actually an AK, I should add, just modelled off of it.

**Comment by Incoming5643** [comment]
I don't see what's so stealth about a gun that leaves a unique bolt behind no matter what

**Comment by paprka** [comment]
"I don't see what's so stealth about a gun that's always used for infinite murderboner almost exclusively and not stealth"

We're way past that at this point incoming

**Comment by Steelpoint** [comment]
If you want to solve bloat, simply get rid of the see through magazine and make it solid so you don't need all those icons.

**Comment by Fox-McCloud** [comment]
@Steelpoint 

Agreed; I really dislike this AK look-alike sprite; it doesn't fit in with the theme of the other weapons and still doesn't exactly communicate to the player that it's a combat rifle.

**Comment by Lo6a4evskiy** [comment]
I agree that AK sprite not only makes ops look like muslim terrorists from the past, it also isn't very good in general.

**Comment by ExplosiveCrate** [comment]
The sprite looks like it's about to fall apart at the slightest touch.

Other than that :+1:, interested in seeing how everyone adapts to the new SAW firing rate.

**Comment by Miauw62** [comment]
the gun would look less bad if it didnt look like it had an orange banana
sticking out of it

**Comment by Steelpoint** [comment]
Even if the mag was black, it still looks like a lower quality sprite than the excellent C90 sprite, no offence.

Maybe make it a Wizard Summon Spell drop, make it some kind of cargo old earth surplus crate or a mining rare weapon find.

**Comment by Fox-McCloud** [comment]
Just stick with the C90gl, Pap, both in name and in appearance; I really do think it would be better.

Part of the reason some people are likely confused is the naming convention; we have a Syndicate pistol, but there's still names like "c20r" and "C90gl" on the uplink. If it's just called "Syndicate submachine gun" and "Syndicate Assault Rifle", then it will be more consistent with the naming standards and help cut down on confusion.

**Comment by Delimusca** [comment]
RIP my ebow+hyperzine driveby gimmix
tactical reload sounds delicious though

**Comment by vista-** [comment]
The new c90 looks really fugly, it gives me an impression that it was put together from 2 different sprites by 2 different spriters.

**Comment by paprka** [comment]
I'm the one who made the c90's sprites as well as the entire mechanic behind the gun by the way before people imply anything about me trying to ruin the game. This gun was always meant to be a full caliber rather than a smg/pistol caliber, and I'd rather we have a gun that looks more like a gun that shoots the 5.45 rather than a gun that's a ripoff of metro 2033's kalash 2012

**Comment by TheVekter** [comment]
:+1: if just for the brilliant ebow nerf.

**Comment by Atskadan** [comment]
i think ive noticed a pattern 
in that you violently defend your spritechanges and say "someone else can fix it" when clearly the option is to not change it at all because it looks worse

**Comment by Steelpoint** [comment]
I still don't understand why you would want to swap out the superior C90 sprites for that crappy AK74 sprite.

By your logic a AK74 is a far more memorable reference to any number of games such as Stalker or Metro 2033.

Again, when you contrast all the weapons the Nuke Ops have at their disposal, which all have a matching appearance and look similar in style and aesthetic, you then suddenly have this AK74 that stands out. Not only does it look subjectively worse than any of the other current Syndi gun sprites, but it's looks too different.

**Comment by paprka** [comment]
"in that you violently defend your spritechanges and say "someone else can fix it" when clearly the option is to not change it at all because it looks worse"
Well obviously I think my sprite change is a good idea so it's not 'clearly' or I wouldn't have done it.

I agree that the c90 is probably a better sprite in that I spent a long time meticulously editing it, but in the end it's a really shitty p90 in a rifle caliber with an underslung grenade launcher for no real reason. It also uses an absurd number of sprites that clutters the file which isn't a good idea. I've stated my reasons for changing it to something more resembling a rifle.

The option is to make it look more like a rifle, it does now, period. I also notice a pattern miggles, you coming into my PRs like clockwork to bikeshed about stupid sprites. I don't care at all, what matters is that it looks like a rifle/carbine now and not an SMG like the c20r. It does a lot more damage and has a much higher capacity magazine and that's a lot more evident from the sprite now.

But really, fuck off if you're going to keep up with this tradition of 'le the sprite looks bad i don't care about any other decisions you put into changing it' because clearly you think I'm out to simply make shit look worse. It looks passable by the rest of the guns in the game's standards so I don't particularly give a fuck.

**Comment by Steelpoint** [comment]
It's not just one person who dislikes the sprite.

Once again, if "bloat" is a real problem, simply get rid of the see through magazine.

**Comment by paprka** [comment]
If future aesthetics are an issue, i could always make it look space age like that ghost recon bullpup.

crye_mrc

Then again I'd also change the caliber to FREEDOM nato 5.56 which is pretty much the same shit anyway

**Comment by Atskadan** [comment]
no, you're not ignoring my suggestions because i have a tendency to make things worse or simply because im "bikeshedding" your issues, you're doing it because you have a personal bias against me. and unlike you, i actually know this as a fact because you've demonstrated as such before.
people who arent me (a bunch of them) have told you already that the AK looks like shit and the p90 design is better. just because you dont like me doesnt mean you cant listen to other people as well.
if theres an issue with the number of sprites, _cut down the number of sprites_. it's not hard.

**Comment by TheVekter** [comment]
Yeah, and did you hear? Amy pulled on Jill's ponytail yesterday and got
sent home before recess!

Christ, this isn't middle school, no one is "out to get you" or has a
"personal bias" against you.

**Comment by paprka** [comment]
No, really miggles, it is bikeshedding, you get really anal about any time I touch sprites even though you don't contribute to or play on this server, you are a self admitted shitposter and you start fights in my PRs all the time.

I do have a personal bias against you. The difference between you posting here and other people is the fact that your comment was almost entirely to start shit. Go take your holy opinion and share it with someone who gives a shit. I can't discuss these things with people if you're shitting up my PRs with your constant PAPRIKA YOU'RE SO BAD AT SPRITING LOLOL ALL YOU DO IS MAKE SPRITES WORSE AND CRY ABOUT IT when the real thing I have a problem with is you doing this inane bullshit and shitting up my PRs. I dislike you, if you have a problem with me not taking your opinion seriously, maybe you shouldn't have called yourself a shitposter and admitted you do this as a hobby and not actually because you care about any of these things?

**Comment by tkdrg** [comment]
Guys, please. Calm down a bit.

**Comment by paprka** [comment]
Reverted AK thing to C-90 again, renamed c-90 to M-90 to avoid confusion with the C-20, changed M-90 caliber to 5.56 instead of 5.45.

**Comment by Steelpoint** [comment]
Cool, cool. Worried we would be on that sprite forever, I even did up a alternative sprite just in case.

screenshot 2015-01-04 01 40 11

You know what would be cool on the topic of gun attachments? Making the C/M90's grenade launcher a separate attachment.

**Comment by paprka** [comment]
It's a real pain in the ass to code  for no real benefit, this gun is the only real one that can use it anyway. I guess you could use it separately as a break-action 40mm grenade launcher if you wanted, but that's a project for another time.

**Comment by Fox-McCloud** [comment]
:+1: 

PRLooks absolutely great now.

**Comment by paprka** [comment]
Just waiting on carn basically.

**Comment by Fox-McCloud** [comment]
This may be a problem unique to our codebase (as how guns handle firing bullets is different), but the range of 7 for the stunshot seems to want to actually behave as if it were 8.

**Comment by paprka** [comment]
Conflics fixed.

Added an LMG and a grenade launcher to the syndicate borg to replace the laser gun and ebow. The LMG will automatically regenerate ammo, does no stun, but does 35 damage and shits on anything with a nearly bottomless magazine. The grenades will also wreck people since the syndie borg's ez mode stuns have been removed for compensation.

**Comment by Steelpoint** [comment]
Love the borg change :+1:

**Comment by Fox-McCloud** [comment]
Yeah, borg changes are very nice.

Feel iffy about the detective's revolver though; the persistence of it still having a weaken on it makes it feel like bad, both on the giving and receiving end of it. As a detective, you shoot them, they go down, but you can't really do anything with the time they're down except shoot them again.

On the receiving end, you get shot, go down, then get shot again when you're already down--which just feels really bad, especially for a weapon that has a decent base damage (15). Aside from that, everything here feels pretty good, IMO.

**Comment by paprka** [comment]
Ideally the detective's role for shooting perps is so that cops can arrest them, but if he really needs to, he can use his telebaton.

Wait, you mean I never gave the detective a telebaton on /tg/?

Fuck, hang on.

**Comment by paprka** [comment]
Now you can be a true watch_dogs cosplayer!11

Really though the detective not spawning with any gear except scanner and bags is kind of lame, I like that his gun is in his cabinet so traitors can steal it but the detective really needed a niche weapon like the telebaton.

I'm afraid it might encourage 'detcurity' where the detective goes on arresting sprees and acts like an officer, but I have a bit of faith in our detective players to use their telebaton and handcuffs for the real threats, not petty thieves and shit.

**Comment by Fox-McCloud** [comment]
@paprka 

Quite frankly, he's going to do that anyway, telebaton or not (and I still kinda expect sec officer's locker raids even--I've seen this change), repeatedly, on just about every server except ultra-heavy RP servers. It's not something I see 24/7, but as long as detective can access the officer's lockers, he's going to arm up with the gear officer's have access to (tasers, baton, etc).

**Comment by paprka** [comment]
I don't htink he has access to officer lockers on /tg/, though, or permabrig/cell timers.

**Comment by Fox-McCloud** [comment]
@paprka 
You're absolutely right; my mistake!

**Comment by paprka** [comment]
Someone merge this please

**Comment by paprka** [comment]
Do I have to shill in IRC???

**Comment by TheVekter** [comment]
Go bitch at someone in coderbus

**Comment by hornygranny** [comment]
this better be good, spicyfruit

**Comment by TheVekter** [comment]
Much love, HG.

**Comment by AlexanderUlanH** [comment]
>Stealth removal of suppressed syndicate carbine

PAAAAAAAAP

**Pull request merged**
