### PR TITLE
Adds a tiny fan to Box's right engineering airlock

### LINKED ISSUE #28862: Box station has a fan in engineering
overwolf_2017-06-26_23-47-07
The left airlock in the supermatter area has a fan while the right one doesn't.

### PR DESCRIPTION
**Pull request by ghost**
:cl: Xhuis
fix: Boxstation's rightmost Engineering external airlock now has a tiny fan to prevent airflow.
/:cl:

While this wasn't initially there, the fact that there's a tiny fan on the leftmost airlock tells me that the lack of one is a bug rather than intentional. This adds a fan to the rightmost one, making the two consistent.

Fixes #28862.

### CODE REVIEW

**Comment by lzimann** [comment]
Remove the other tiny fan instead

**Comment by Xhuis** [comment]
How come? The left airlock has it very much intentionally, I believe, as it leads to the cooling loop for the supermatter.

**Comment by lzimann** [comment]
Fans are a lazy way to prevent atmos flow, these should be a cycle airlock if they still aren't.

**Comment by WJohn** [comment]
yeah we just had a PR that removed all the fans from delta station in favor of cycling.

**Comment by CPTANT** [comment]
Having a double airlock is pointless with a tiny fan anyway.

Tiny fans should be removed everywhere.

**Comment by Cyberboss** [comment]
Tiny fans are for non-station only

**Comment by Xhuis** [comment]
huh. weird. ah well!

**Pull request closed without merging**
