### PR TITLE
fixes syringes of perfuleracilen

### PR DESCRIPTION
**Pull request by Tlaltecuhtli**
:cl:
fix: syringes with the o2 medicine work
/:cl:

### CODE REVIEW

**Comment by kriskog** [comment]
perfluorodecalin

**Comment by ExcessiveUseOfCobblestone** [comment]
perflourokekalin

**Comment by Rowelll** [comment]
i like my o2 syringes!!!!!!!!!

**Comment by Ordonis** [comment]
HOW I INJECT THE PERSCRUNGULARTY?

**Comment by anconfuzedrock** [comment]
ig/sugg add perfuldexalin+ that instantly cures all oxygen damage but causes infinite toxin damage as well

**Pull request merged**
