### PR TITLE
Blood drunk eye gives ignoredamageslowdown

### LINKED ISSUE #43611: kinetic crusher immobilizing
Issue reported from  Round ID: 106091 (/tg/Station Terry [EU] [100% LAG FREE] [New-Dedi])

Reporting client version: 512

If you proc blood drunk crusher trophy effect when wounded (i think at the first slowdown) you get immobilized for the duration of effect

### PR DESCRIPTION
**Pull request by 4dplanner**
## Why It's Good For The Game
fixes #43611 
Technically also a minor balance change
warning: not tested yet

## Changelog
:cl:
fix: Blood drunk eye gives damage slowdown immunity rather than vulnerability.
/:cl:

### CODE REVIEW

**Comment by Tlaltecuhtli** [comment]
miner buff

**Comment by Daxxed** [comment]
You don’t play mining tlal stop shitposting on gamebreaking bug fixes

**Comment by 4dplanner** [comment]
Game 

Breaking

**Comment by ExcessiveUseOfCobblestone** [comment]
> You don’t play mining tlal stop shitposting on gamebreaking bug fixes

If I had to read this terrible post then so do you.

**Comment by ExcessiveUseOfCobblestone** [comment]
so what's causing this bug and why should I not consider full slow immunity a bandaid/creep

**Comment by 4dplanner** [comment]
> so what's causing this bug and why should I not consider full slow immunity a bandaid/creep

The amazing way the blood drunk eye works is by multiplying your health by 10 for the duration of the effect. Unfortunately, damage slowdown threshold doesn't scale with it, so 4 damage slows you down.

Honestly, it might well be better to tear down the whole thing and add in a proper damage reduction system, but this was a quick fix. It doesn't affect balance too much as miners have cores anyway, it's for a short duration, and it only procs against fauna.

**Comment by ExcessiveUseOfCobblestone** [comment]
ok i just wanted to btfo miner mains

**Comment by Daxxed** [comment]
The crusher is a meme anyway so no it didn't break miner gameplay at all.
Was the mod useable and functional though ? No.
Also calling it a buff only makes sense on paper, the effect lasts for like a second and you have to keep meleeing to get the slow immunity.
People are not gonna magically beat every megafauna with a crusher with this mod.

**Comment by ExcessiveUseOfCobblestone** [comment]
no one made that claim but lol'ing at the defense of such a mino(/e)r buff :^)

**Comment by adamkad1** [comment]
> The crusher is a meme anyway so no it didn't break miner gameplay at all.
> Was the mod useable and functional though ? No.
> Also calling it a buff only makes sense on paper, the effect lasts for like a second and you have to keep meleeing to get the slow immunity.
> People are not gonna magically beat every megafauna with a crusher with this mod.

i beat all bosses in vr boss rush with crusher tho

**Pull request merged**
