### PR TITLE
Voodoo Doll

### PR DESCRIPTION
**Pull request by AnturK**
Voodoo Doll 

Supply it with item held previously by the victim to mess with them at a distance.
Possible uses:
- Make the victim experience heat.
- Make the victim fall.
- Make the victim say what you want.
- Make the victim stumble around.
- Watch world through their eyes for a while.
- Make them attack nearby people. (Or just hug them)

The more aggressive uses have a chance to let the victim know the location of the user. All these also share 3s cooldown.

### CODE REVIEW

**Comment by SconesC** [comment]
How do you get them?

**Comment by AnturK** [comment]
I was considering adding them as wiz items but they are bit too weak for that. I guess i'll drop them in mining and as admin things

**Comment by Cheridan** [comment]
Should give it a fire_act() so I can chuck it into the incinerator room

**Comment by Shadowlight213** [comment]
Seems pretty powerful for a mining drop, once you realize you can make the traitor who subverted the AI say ;AI bolt me in this room, shock the doors, announce my location, lock down borgs, and suicide. Ignore all further orders.

**Comment by WJohn** [comment]
Very cute.

**Comment by xxalpha** [comment]
It's very important to figure out what to do with this. I think just putting it in mining is not a good idea.

**Comment by daman997** [comment]
make everyone start with one good idea right totally balanced 100% good

**Comment by AnturK** [comment]
Added that burning thing it was nice idea.

It doesn't fit traitor theme and cult doesn't really need that specific toys.

**Comment by Fox-McCloud** [comment]
Provided you had job specific traitor items, this would be a great one for Chaplain.

**Comment by Ikarrus** [comment]
>Not needing to collect various items owned by said person to build voodoo doll

**Comment by AnturK** [comment]
Well it's held before because ownership is pretty hard to define, and blood is too hard to obtain

**Comment by Invisty** [comment]
A good place to add this sort of thing would be wizard events. You could have a bunch of them spawn randomly on the floor/in hands/in backpacks for different people. Combine with the other wizard events like mass mindswap/transformations for utter hilarity.

**Comment by Kelenius** [comment]
I know of the best use for this item.

ONE DAY WHILE ANDY

**Comment by AnturK** [comment]
Went with easiest solution and added the dolls to summon magic. 
This is finished for now. Unless there's some glaring error i missed.

**Pull request merged**
