### PR TITLE
[wip] Changes labor camp, warrant system

### PR DESCRIPTION
**Pull request by jlsnow301**
### Design Doc
https://hackmd.io/@shadowh4nd/BygosvL-0

Incentivizes using labor camp and issuing citations to generate money for the sec department. 
Sec gets a payout for doing their job. Threat increases. Antags recycle back into shift.

<details>
<summary>pictures</summary>

**Process (sound)**

https://github.com/tgstation/tgstation/assets/42397676/3c8123a1-8f04-4e66-a8b6-8caeca4d223a

**Most end up in the labor camp!**
dreamseeker_ZhSjRLLCAE

Others... Unlucky
dreamseeker_seRjh56dpn

</details>

## Why It's Good For The Game
- Sec is underplayed and its systems are underused
- Labor camp is a single player adventure

## Changelog
:cl:
add: The gulag has been overhauled to provide funds to the security department.
add: Getting sent to labor camp will remove you from the round.
del: Removed "points" on prisoner cards, only time served. Labor camp is made permanent.
del: Labor camp redemption machines and vendors. There will be no redemption.
/:cl:

### CODE REVIEW

**Comment by Sadboysuss** [comment]
Labor camp is often used for non-antag shitters, this is removing a form of punishment, exchanging it for a form of RR, one of the reasons AI exists on asimov is to prevent RR, roleplay rules and space law allows RR only on capital crimes. This would be bypassing the AI gate on humans, and there would be zero reason to execute. Also, executing someone doesn't always mean removing their body from the round, this also doesn't allow for stealthy ling revive after execution.

**Comment by Sadboysuss** [comment]
Also completely round removing a player with the chance that they're not an antag seems very silly

**Comment by Time-Green** [comment]
please don’t drop massive changes like this with barebone PR bodies

I know you’re working on it, but people are not going to wait with forming their opinions until after you finish writing your PR body

also the title doesn’t reflect the main change you’re making: gulag roundremoving people (whatever that means)

**Comment by Fikou** [comment]
> I think the security department needs overhauled. Not fun enough. 

ok?
> Getting caught: Certainly not fun enough. 

your main mission is to not get caught, but i dont see how removing you from the round makes it more fun
> There is precisely zero chance I'm continuing playing if I'm caught and sent to labor camp or perma. This PR embraces this.

i continue playing if i get caught its fun to have a comeback story
> Death should be cheap. 

uhhh source?
> Rounds are 45-ish to 2 hours. I'm not spending 3/4ths of this RPing as prisoner until I die or escape.

ok then go into command bar and type suicide click enter twice
> Overhauls labor camp to be a better alternative than perma and execution.

and the way you do that is to make it execution but gives you money and avoids all issues with reviving antags and such by using the ghosting system? why even have an execution chamber at that point?

**Comment by AtomTheProphet** [comment]
Seriously?

> There is precisely zero chance I'm continuing playing if I'm caught and sent to labor camp or perma. This PR embraces this.

This is quite frankly one of the most ridiculous reasons for a change like this I've seen yet.
It can certainly be more interesting for the antagonist to escape the labor camp or permabrig, although the latter is fairly more difficult. 
It's your own problem if you don't want to make an epic comeback to keep things going.

**Comment by Livrah** [comment]
Round removing players via Space Law loopholes is such a bad idea, antags or not. 
Escaping the brig with the help of others / events / or just by breaking out creates a lot of good roleplay situations.
> There is precisely zero chance I'm continuing playing if I'm caught and sent to labor camp or perma.
>
sounds like a personal problem instead of why this is good for game

**Comment by jlsnow301** [comment]
> Escaping the brig with the help of others / events / or just by breaking out creates a lot of good roleplay situations.

Rest assured the brig remains fully intact

**Comment by Helg2** [comment]
Still gonna be used freely just to grief people ¯⁠\⁠_⁠(⁠ツ⁠)⁠_⁠/⁠¯

**Comment by Helg2** [comment]
Maybe instead of a complete round remove would be better to do something similar to kidnapping people or selling them as pirates, so you could get them back in some way.

**Comment by Pickle-Coding** [comment]
The labor camp is a pretty good option for making massive shitters work for their freedom, instead of afking in a cell. Why not just remove the point limit an officer can set, instead of limiting it as a permanent sentence?

**Comment by DrDiasyl** [comment]
> The warrant system is almost completely unused.

The warrant system is used. By placing a person on a warrant all of the Beepskies on the station will try to catch them, and anyone wearing SecHUDs can immediately notice a wanted person in their sight.

You pulled out "completely unused" out of nowhere, as it is used because it is already useful.

**Comment by jlsnow301** [comment]
> You pulled out "completely unused" out of nowhere, as it is used because it is already useful.

:| The warrant console. Citations.

**Comment by DrDiasyl** [comment]
> > You pulled out "completely unused" out of nowhere, as it is used because it is already useful.
> 
> :| The warrant console. Citations.

Well, you didn't specify what you meant under "Warrant" so your fault.

**Comment by jlsnow301** [comment]
> Well, you didn't specify what you meant under "Warrant" so your fault.

cool lol

**Comment by Higgin** [comment]
The basic idea of rewarding security for doing their jobs is good.

The implementation here is not.

Security, and policing more generally, should be judged by the following:

"[...] the absence of crime and disorder, and not the visible evidence of police action in dealing with them."

https://lawenforcementactionpartnership.org/peel-policing-principles/

Dynamic does a fine job as it is in creating disorder. Some rounds security will deal with it; in many others they will not.

If you wanted to do something to this effect, I might instead suggest tying it to some sort of in-game feedback mechanism that actually makes the game better for those affected: 

At regular intervals, check for the number of people currently dead, in cells, in perma, and in the gulag. Check for the safety of various high value targets like the nuke core, blackbox, and GOON drive. Maybe even put an in-game "security survey" on PDA or an automatic vote for people to say how satisfied they are with the security of the station. Don't specify where these checks come from in-round - if you want to involve antag status or checks in it, this makes it an unreliable test for players to figure out who's bad or not (or, in other words, who's been a use of threat in Dynamic.) You might be getting a better score because you jailed an antag - or, you might be getting it because all the dead people from the rage cage/blob/whatever got revived. This can be the "security rating."

If the station is secure and doing well, give a regular payout in a form that security can actually use - let's call it security points - and let them spend those to get the current cargo orders they get for free instead of just getting them for free. Maybe even give them an option to express order like the produce console uses at a major markup.

If the station is doing poorly in its rating relative to the last "sec check," give them an initial boost of security points which will be deducted going forward over time - basically a loan saying "it's rough right now, so get your shit together and get it squared away. You'll pay for it later."

If they're doing well, let them continue to accrue points as normal. 

Tie this back into Dynamic as you see fit - maybe if the security rating stays consistently high for too long relative to the threat level, decrease the time between injections, midrounds, heavies - so the remaining threat gets used and gets more time to cook in the same pot.

Don't increase the overall threat level because some rounds should be quieter and some should be louder overall. Sometimes, everyone should be able to go home saying it was a job well done - in spite of the odds or because of them - and sometimes, the crew should be able to snatch defeat from the weak jaws of victory without extra help.

**Comment by ButterChugger** [comment]
> I think the security department needs overhauled.

Great start.

> Not fun enough.

Honestly seeing a lot of sybil and manuel cops actually roleplay and have fun via arresting people for petty crimes, having ten second sentencing, donut inhaling competitions... Hell I watched a sec team chase down a man for being too fresh in their downtime (He did look too fly to be honest). I don't know where you're policing where you're not having fun, unless you consider the entirety of your round to be locked in combat with antagonists.

> Getting caught: Certainly not fun enough.

What do you mean by this? Do you need to have a spectacular firefight on both ends to properly satiate your need to be caught instead of slipping up and getting non lethally detained? Do you consider your new method of ultimately what is round removal for antags fun? Define.

>There is precisely zero chance I'm continuing playing if I'm caught and sent to labor camp or perma.

Then perchance you should of simply played better? In the end an antag that is swinging for the fences in terms of body count is going to be treated as a threat that gets removed from the round via execution or boredom.

>Death should be cheap.

Should it be? This is entirely a matter of opinion. If applicable this concept is not just to crew: so are antag lives. If you die, you die. If you get caught, you get caught. Everyone takes their lumps equally, a lot of these lads being hardcore removed via methods that do not allow them to ever come back. Lack of suit sensors, spaced off station, de brained and tossed in a box somewhere. Antags dusted or refusing to find a way (or die trying) out of their cages.  I don't see giving preferential treatment to those inclined to RR productive.  Why not make it both ways? If this gets put in you might as well add a method for jobs to be cleaned out and a shuttle to be added that allows players to respawn in every half an hour of gameplay with a new character ala TGMC.

**Comment by zoomachina** [comment]
I struggle to understand this: What kind of impact do you think these changes would have on the gameplay of security and traitors and why do you think it's good?

**Comment by Iamgoofball** [comment]
Please don't make the gulag always permanent; sending greytiders to the gulag with 1 point is the ultimate technique for shitter filtering and this would completely nuke that.

**Comment by Admiral-Gigaton** [comment]
even with the whole thing about it increasing threat, this is still incredibly ass, and should not be even thought of coming out of draft without 8 maintainers ripping it to shreds.

Round Removal should always be discouraged, and should rarely, if ever, get more sources to it. 

giving sec more money doesnt do squat, they can spend it on like maybe a few more guns but generally thats about it, doesnt give them special gear just more bland shit

**Comment by excalisword** [comment]
If you do implement innocents increasing threat even more so than antagonists getting gulagged like you said in the HackMD, then tiders will just start trying to get sec to gulag them or just ask for gulagging when they're bored. You get ghosted while you add more threat than an antagonist to the shift while also being eligible for the mid-round antagonists being summoned by the threat.

**Comment by Blacklist897** [comment]
I lack the words to describe how much of a bad idea this is

**Comment by DaydreamIQ** [comment]
This PR is just objectively off the mark. You want to make getting caught by security suck less when you're literally giving them an incentive for round removing antags on the spot rather than imprisoning them. Even if they get fined for using it on innocents you've literally given sec a built in antag checker

**Comment by Admiral-Gigaton** [comment]
> This PR is just objectively off the mark. You want to make getting caught by security suck less when you're literally giving them an incentive for round removing antags on the spot rather than imprisoning them. Even if they get fined for using it on innocents you've literally given sec a built in antag checker

witch hunting trials pretty much, barely even a checker:

"If the witch floats, then she is in fact a witch, and as such we burn her at the stake! if she drowns, then god rest her soul, for her sacrifice was great so we may continue to find more witches!" literally the exact same situation, minus the satisfaction of murdering the "witch" yourself

**Comment by Blacklist897** [comment]
this replaces a rp framework with gamifying sec, malding when sent to gulag/permaed is a issue of skill

**Comment by Astrogem2** [comment]
thumb up, no reason

**Comment by Jacquerel** [comment]
I think I have fundamental and probably unresolvable disagreements with the premise behind this PR.

- I disagree with the initial concept of "what we want security to be". 

I **don't** want Security to be focusing their time on defeating antagonists in order to protect the crew; I want them to be spending their time arresting people who are committing crimes.
We have large numbers of players who commit crimes and also aren't antagonists, and this is essentially an intended part of this being a sandbox roleplaying game.
Rewarding security for capturing antagonists and penalising them for penalising people who are not antagonists both encourage security players to increase the level of metagaming they are working on instead of just roleplaying as a law enforcement officer. 
As an example, this is an encouragement for security players to ignore people who are "greytiding" (breaking into departments to steal things that they want instead of asking for permission) because those people probably aren't antagonists so it's a waste of their time (if not actively detrimental) for them to spend time pursuing them.

- I don't care if there is no in-game mechanic rewarding security players for doing their job.

Security players are already doing their job without a reward. Most jobs function this way. We don't need intrinsic reward systems for every role, because we are making a sandbox roleplaying game and not a metric-driven engagement skinner box.
I would say that we're probably already _over_-reliant on progression systems and cannot see how Security automaticallyincreasing in power over the course of a round would be beneficial. 
If anything this would exacerbate your percieved issue of Security being abel to "roll over" all of the antagonists in a shfit and make it boring. Our game design is essentially that Security _should_ lose at some point- it is how the round ends.

- We use both perma (as genpop on tram) and the work camp as temporary punishments as well as permanent round removal, and in fact I don't think people give out permanent gulag sentences basically ever.
- The points required to complete the labour camp don't exceeed the entire round and I don't even know why you included that in your design document when you said you haven't even been monitoring how it works since Arcmining was merged. That part is just untrue.
- "Players ghost if this punishment occurs" is a choice made by (some) players. Automatically ghosting them is a bizarre solution to this problem because it automates it rather than solving it.
- Ghosting players and leaving catatonic corpses standing around in the middle of nowhere leads to really strange incentives and kills off RP opportunities. There's now no IC reason to bother transporting them at the end of a shift, or interact with them at all. In fact it'd be smarter to gulag someone and then immediately go and retrieve them so that you can leave them in Medbay as a limb and organ donor. It also just looks really silly.
- Creating nonlethal round removal interferes with the dynamic between Security and the AI. Now that you can "execute" people without harming them, there's no reason to ever execute anyone _for real_ at all. The AI doesn't have any grounds to object to a machine which OOC ghosts people without IC hurting them, so it removes the need to pretend you are doing anything else.

The salvageable part of this PR is potentially "some way of returning threat into a round when an antagonist is categorically defeated" (although to be honest I am not sure we need it, or that rounds really are ending in total security victories where no threats remain and the round continues until people get bored particularly often) but I do not think this is a good implementation of that concept as it ignores most of the most common ways that antagonists are removed from the round.

I don't think I would want almost any part of this to make it into the game.

**Comment by scrunklershrungle932** [comment]
having sec imprison and kill increase threat as well as gain money from it does seem cool, but making the labor camp round removing sucks imo.

**Comment by jlsnow301** [comment]
> having sec imprison and kill increase threat as well as gain money from it does seem cool, but making the labor camp round removing sucks imo.

i was quite flexible on this, and thought I could recycle these systems back into common usage at the same time

**Pull request closed without merging**
