### PR TITLE
Return old ore spawn

### PR DESCRIPTION
**Pull request by NeonNik2245**
## About The Pull Request
Some time has passed since the introduction of ore vents (PR #78524 from @ArcaneMusic). They have changed the work of the miners: now they must fight with fauna to capture vents and get resources. On my (and not only) opinion, this change should have been an addition to the shaft, so you could choose whether fight for resources or dig them old way.

This PR makes chances of ore spawn higher, if say fast. In detail:
* Ore have random number of ore in vein based on its proximity to vent (old-old was flat 1 to 5 for all veins)
* * 5 near vent (3 tiles) (as in vent update)
* * 4 to 5 in 6 tiles (4 in vent update)
* * 2 to 4 in 15 tiles (3 in vent update) 
* * 1 to 4 in 32 tiles (2 in vent update)
* * 1 to 3 in 64 tiles (1 in vent update)
* Ore vein have a higher chance of spawn (old-old was 10 flat percents)
* * 10% in 15-tiles radius (just as before)
* * 8% in 32-tiles (lower, than before)
* * 7% in 64-tiles (also lower)

## Why It's Good For The Game

Shaft miners will be able to chose either to fight or to dig. Amount of ore collecting with only old way is reduced for the sake of balance. Now mining explosion, cutter and drills useful again. It also will cause less deaths from novice miners, because they won't be need to fight with fauna. And vents still in the game, that's mean resources won't run off in long rounds. Also ashwalkers and other roles have access to resources without fighting.
## Changelog
:cl:
balance: Change ore spawn to be more old-styled.
/:cl:

### CODE REVIEW

**Comment by ArcaneMusic** [comment]
Could you record a few rounds worth of data from the `post_ore_random` list in `SSore_generation`? I'd like to see this compares to in-round live data on how many ores were spawned.

I'm imagining that the results from the tweak to  `VENT_CHANCE_FAR` are going to be the most significant change that it might be worth tweaking the spawn chances a bit, (And personally I liked the fact that ore quantities spawning served as a kind of ghetto "radar" to the nearest vent) but I'm not against raising it dependent on how significant the amount of ores spawned looks.

**Comment by NeonNik2245** [comment]
> Could you record a few rounds worth of data from the `post_ore_random` list in `SSore_generation`? I'd like to see this compares to in-round live data on how many ores were spawned.
> 
> I'm imagining that the results from the tweak to `VENT_CHANCE_FAR` are going to be the most significant change that it might be worth tweaking the spawn chances a bit, (And personally I liked the fact that ore quantities spawning served as a kind of ghetto "radar" to the nearest vent) but I'm not against raising it dependent on how significant the amount of ores spawned looks.
> 
> I'm going to want that data before moving forward with this.

To be honest, I don't know (or don't understand you) where to look data about `post_ore_random`...
But I need to say, that 7% might be a little too high with vents. But at this moment shaft can be a little empty sometimes, like this:
image
image

**Comment by NeonNik2245** [comment]
> Could you record a few rounds worth of data from the `post_ore_random` list in `SSore_generation`? I'd like to see this compares to in-round live data on how many ores were spawned.
> 
> I'm going to want that data before moving forward with this.

I compiled it a few times and probably have this data, but don't know where to find it, as I said. I will be glad to share data with different chances of ore spawning

**Comment by moocowswag** [comment]
There should at least be some decent amount of ore to mine for the sake of public mining being a thing, unless the vent fauna are meant to be beatable with ghetto weapons like toolboxes.

**Comment by NeonNik2245** [comment]
> Could you record a few rounds worth of data from the `post_ore_random` list in `SSore_generation`? I'd like to see this compares to in-round live data on how many ores were spawned.
> 
> I'm imagining that the results from the tweak to `VENT_CHANCE_FAR` are going to be the most significant change that it might be worth tweaking the spawn chances a bit, (And personally I liked the fact that ore quantities spawning served as a kind of ghetto "radar" to the nearest vent) but I'm not against raising it dependent on how significant the amount of ores spawned looks.
> 
> I'm going to want that data before moving forward with this.

Can it be this string: `"name":"/turf/closed/mineral/proc/Spread_Vein"..."calls":2847`?
Or "name":"/turf/closed/mineral/proc/Change_Ore"..."calls":3760

Then in new rounds that numbers is (2847 and 3760), (2865 and 3747)
Aaand.... 2865 and 3931 for old?
Anyway, shaft on local seems to be very similar with old one, maybe with less ore veins
<details>
<summary>Screenshots of ore spawn</summary>
image
image
image
image
Underneath previous picture:
image


</details>
Vents are still recognisable by amount of ore, but other places now don't look empty

**Comment by NeonNik2245** [comment]
@ArcaneMusic? I still can't give this data to you, simply because don't understand where to get it.
Amount of ore feels less, than long time ago, but it at least exist, I can not provide more information for you

**Comment by ArcaneMusic** [comment]
> @ArcaneMusic? I still can't give this data to you, simply because don't understand where to get it. Amount of ore feels less, than long time ago, but it at least exist, I can not provide more information for you

I started work on logging of this information more formally over the weekend, to make to easier to compare data against on live rounds. That said in interrum, if it works, it would be as simple as compiling, starting the round, going to the MC tab, selecting the Ore_generation subsystem, and lookimg at the post_ore_random list within it, the same as var editing an object.

**Comment by NeonNik2245** [comment]
> > @ArcaneMusic? I still can't give this data to you, simply because don't understand where to get it. Amount of ore feels less, than long time ago, but it at least exist, I can not provide more information for you
> 
> I started work on logging of this information more formally over the weekend, to make to easier to compare data against on live rounds. That said in interrum, if it works, it would be as simple as compiling, starting the round, going to the MC tab, selecting the Ore_generation subsystem, and lookimg at the post_ore_random list within it, the same as var editing an object.

Ok, sorry for late interrupting, though you was waiting for me, thanks for reply

**Comment by ExcessiveUseOfCobblestone** [comment]
even if we agree its lower than what we want, I dont think its ever going to be acceptable to simply just add back the ore and have the shafts also available with 0 changes, the ore income needs to be regulated which is why the vent system was added in the first place.

**Comment by ArcaneMusic** [comment]
I wound up running the numbers and collecting data manually as well as by checking out to your branch, and here was a 5 round dataset of both your changes listed on this PR versus the changes to the live game.
image
Each number in this list is attributed to a turf that was selected to produce ore, as designated by the `proximity_ore_chance()` proc on `/turf/closed/mineral`. In short, the distance to the nearest vent is what sets that probability for it to spawn ore based on the values tweaked in this PR, and the based on that same distance, we also call `scale_ore_to_vent()`, which sets how many of an ore will spawn when mined, which gets logged to `post_ore_manual`.

To summarize, this gives us both a total of how many turfs passed checks to spawn ore, (the sum of each list's right values, averaged over # of lists), as well as giving an average amount of ore added total in mapgen (left value times right value, averaged over # of lists again).

Basically, all this PR does is add 50% more ore to the map, without really adding a whole lot of nuance.

As to your why it's good for the game, It's not like there's zero ore still on the map. Miners still have a perfectly good ability to choose to do one or the other, and nobody's being forced to do ore vents or to fight fauna for round progression, we just offloaded some of the ore in rock walls over to vents as a way to better balance minerals entering the round by design. I think it's safe to say I'm not going to be convinced this is a change we want.

**Comment by NeonNik2245** [comment]
> Basically, all this PR does is add 50% more ore to the map, without really adding a whole lot of nuance.

Can I ask you to check how many ores (tiles) were generating with flat 10%, as at old version of generation? This PR is doing what said in title - tries to give more ore to map, that's why it only makes more tiles

**Pull request closed without merging**
