### PR TITLE
Cuter spiderlings

### PR DESCRIPTION
**Pull request by Jacquerel**
## About The Pull Request

I hate looking at spiderlings. Mostly because they're an extremely fast mob with no directional sprites or animations, so they appear to be a rapid floating overlay.
I made some new ones. I don't know if they're objectively better but _I_ like them more.

Before:
image

After:
image

Unlike the old sprites they also have directional states and movement animations so you can scurry around really fast without being a static image (maybe they shouldn't be so fast? A question for another PR).
I spent like 30 minutes looking at GAGs and then realised not only would the colours be a pain in the ass but it doesn't support movement states anyway.

Additionally I made the "dead spiderling" item inherit the dead spiderling icon state from that spiderling instead of always being the generic one.

Oh also I think a typo made baby tarantulas completely invisible.

## Why It's Good For The Game

I hate looking at spiderlings.

## Changelog

:cl:
image: New directional sprites for spiderlings, with movement animations.
fix: Dead spiderlings will be the same colour as they were when they were alive.
fix: Tarantula spiderlings are no longer invisible,
/:cl:

### CODE REVIEW

**Review by Wallemations — APPROVED** [review]
Instant approval, love These new lil guys
Might need to make some alpha pixels for their hitboxes though, but that's more a balance than sprite change.

**Comment by CoiledLamb** [comment]
these are so good! 100% an improvement in my eyes

**Comment by Singul0** [comment]
cute

**Comment by GuillaumePrata** [comment]
> Might need to make some alpha pixels for their hitboxes though, but that's more a balance than sprite change.

I think this should less of a balance decision and more of an art decision.

We should have good looking sprites, regardless of the size, that are easy to be interacted by the players.
No one likes pixel hunting unless it benefits themselves in combat.

**Comment by Jacquerel** [comment]
> Might need to make some alpha pixels for their hitboxes though, but that's more a balance than sprite change.

Easy enough to add and makes sense.

**Comment by Comxy** [comment]
What about slower movement instead of an alpha hitbox

**Comment by san7890** [comment]
their speed was wonky before i refactored them since they were `/obj/structure`s, not a regular simple animal mob, so I just decided to give them speed+ventcrawling for the tradeoff of being forced to be out in the open for 15 seconds/vulnerable while ventcrawling and being killable by literally anything due to how low their health is. no real precedent for them being that fast beyond my observations of them in the old framework and further guesstimation. this can definitely be tweaked but just sharing why it is the way it is.

**Pull request merged**
