### PR TITLE
makes gulag beacon indestructible

### PR DESCRIPTION
**Pull request by silicons**

### CODE REVIEW

**Comment by evsey9** [comment]
does destroying it render gulagging using teleport unuseable?

**Comment by juanototo2** [comment]
>no description
>not just making it a machine with board
>NOT MAKING IT REPLACEABLE
w h e w  L A D

**Comment by juanototo2** [comment]
also people gulagged without the teleporter before, learn the fact that it isn't a necessity. the tele was made by steel fucking point, you know the one.

**Comment by XDTM** [comment]
Maybe give it a threshold so it can't be pickaxed

**Comment by BeeSting12** [comment]
Giving it a threshold is the better solution, but this will work for now as the current fad seems to be destroying as much gulag equipment as you can because security bullied you.

@evsey9 
Yes, it does and is also irreplaceable.

**Comment by kilkun** [comment]
they should just steal their shit back

at any rate, if sec doesn't want gulag shit destroyed maybe they should post an officer there while they have a prisoner.

maybe we need to revert to old security because people have gotten really fucking hugbox when it comes to prisoner management. I'm surprised perma still has a bucket+sink and a bar of soap.

**Comment by kevinz000** [comment]
@kilkun no one's posting an officer on gulag isolated with greytiders all around don't even joke.

**Comment by juanototo2** [comment]
>what is warden competence

>what is using the AI

>what is beepsky

>what is backpacks of flashbangs

>what is opening sec officer jobslots

>what is robotics ED-209 production

sec has so many things to handle low amounts of people available to patrol that it's stupid

**Comment by kilkun** [comment]
I'll solve this problem. Don't worry.

**Pull request merged**
