### PR TITLE
PORT: Sparks and lasers no longer count towards turf's lumcount value

### PR DESCRIPTION
**Pull request by ItsTisme**
## About The Pull Request

Ports https://github.com/BeeStation/BeeStation-Hornet/pull/6092

all credit to original PR author I just copy pasted

## Why It's Good For The Game

Same reasoning as described in the original PR, figured id port it over

as a bonus, sparks wont interfere either with things that need darkness so thats nice

fun fact nightmare has a mechanic to dodge projectiles in the dark, but since lasers acted as a light source this bassicly didnt work. fixes that

nightdodge

## Changelog
:cl: PowerfulBacon
code: Overlay light sources can be set to not count towards get_lumcount calculations
code: Lasers and sparks no longer count towards get_lumcount calculations.
balance: Nightmares will now dodge lasers
/:cl:

### CODE REVIEW

**Comment by Autisem** [comment]
not sure if I did the CL credeting properly

**Comment by private-tristan** [comment]
I believe that nightmares are already supposed to dodge lasers (but it's been broken for a while)  #70760

**Comment by Autisem** [comment]
> I believe that nightmares are already supposed to dodge lasers (but it's been broken for a while) #70760

Yup like I said, but lasers create light. this will both cancel a jaunt if you shoot at them AND bypass dodging since they are not in the dark when the laser flys by

**Comment by Potato-Masher** [comment]
If they were intented to dodge lasers as well I doubt this needs to labeled as a balance change. Good change regardless, nightmare is just a punching bag if they can't darkjaunt to avoid unfavorable fights.

**Comment by moocowswag** [comment]
I think nightmare would be healthier if lasers kept the utility against them but nightmares lost their 1.5x burn damage multiplier which usually resulted in extremely fast deaths from full health.

**Comment by Autisem** [comment]
> I think nightmare would be healthier if lasers kept the utility against them but nightmares lost or had their 1.5x burn damage multiplier trimmed a bit because it usually resulted in extremely fast deaths from full health.

lasers are still really powerfull but now you cant just shoot fast enough and stop his jaunting even if you dont have a flash light

**Comment by JohnFulpWillard** [comment]
> I believe that nightmares are already supposed to dodge lasers (but it's been broken for a while) #70760

going on the PR that 'closed' that issue is linking to an issue report that was labeled 'not a bug' https://github.com/tgstation/tgstation/issues/53309

**Comment by Autisem** [comment]
> > I believe that nightmares are already supposed to dodge lasers (but it's been broken for a while) #70760
> 
> going on the PR that 'closed' that issue is linking to an issue report that was labeled 'not a bug' #53309

Looking at the original PR, quote from Rohesie
"However, this won't really solve the problem you intend to in the long run. Might want to change how the interaction between nightmares and light works if getting a brief exposure to light will have such a big effect on them. The problem will reappear whenever a new similar light source is introduced."

Dont quiet understand the "nog a bug" part thats not mentioned anywhere, the fix was just not a propper one

**Comment by Shirbu** [comment]
I was the shmuck who made the original "fix" to energy projectiles that made them dimmer. This is an infinite improvement to that one, and will allow lasers and whatnot to be bright and beautiful again without fucking balance up.

**Comment by Shirbu** [comment]
recommend merge. Good PR

**Comment by optimumtact** [comment]
This isn't a good fix, sparks and lasers should countt twoards lumcount values, they literally cause light.

The fix is to improve how the nightmare behaves in low light so it's not so easily cheesed.

I'm not fucking up the core game for a shitty midround event antag that I would prefer be deleted instead

**Comment by Autisem** [comment]
> The fix is to improve how the nightmare behaves in low light so it's not so easily cheesed.

the only solution to that is to have im inherently not be effected by light levels caused by sparks/lasers. or give him a "buffer" time he needs to be in the light before it counts as such

**Pull request closed without merging**
