### PR TITLE
'Server's Last Round' fix

### LINKED ISSUE #56805: "Show server last round" verb hasn't ever showed up as a usable verb (either in the OOC tab or via command bar)
image

## Reproduction:

"Show server's last round", added by https://github.com/tgstation/tgstation/pull/55646 , has literally never shown up to me in OOC tab a single time in the month it has been merged. It's in the code, the verb still exists, but you can't ever use it on live.

### PR DESCRIPTION
**Pull request by MrDoomBringer**
## About The Pull Request
Makes viewing the server's last round actually work

## Why It's Good For The Game
fixes #56805

## Changelog
:cl:
fix: The server's last round should be actually viewable now
/:cl:

### CODE REVIEW

**Review by LemonInTheDark — APPROVED** [review]
I find it funny that the verb was so underused it took a month for anyone to notice it didn't exist

**Comment by LemonInTheDark** [comment]
I assume this closes #56805?

**Comment by MrDoomBringer** [comment]
> I assume this closes #56805?

yes I meant to have that in the PR description

**Comment by Mothblocks** [comment]
@LemonInTheDark they had a bounty on it too :rofl:

**Comment by MrDoomBringer** [comment]
shh mothblocks don't tell them about my antag token collection fraud

**Comment by MrMelbert** [comment]
lemon, i've been trying to use this feature for the past month and i thought i was the problem :(

**Comment by LemonInTheDark** [comment]
That's even more sad, you got gaslit by the codebase

**Pull request merged**
