### PR TITLE
Fixes the pickup animation.

### PR DESCRIPTION
**Pull request by Iamgoofball**
I'm not certain if it was the static, the mutable appearance, or the JJR PR that broke it, but I'm going to assume all of the above.

@JJRcop

### CODE REVIEW

**Comment by JJRcop** [comment]
I tested my PR before the static and mutable appearance changes

**Comment by Iamgoofball** [comment]
they what

oh god fucking damn it byond

**Comment by zaracka** [comment]
the animation bugs out if you take something out of storage

**Comment by MrDoomBringer** [comment]
break the repo on purpose so you can reap the "priority:high" hotfix gbp, huh kid?
classic maneuver

**Pull request merged**
