### PR TITLE
fixes reviver implant looping players between soft and hard crit

### LINKED ISSUE #75139: Reviver implant doesn't work on androids?
## Round ID: [204977](https://scrubby.melonmesa.com/round/204977)

image

I was shot by beanbags and lasers and went into deep space in softcrit. I saw the above message, but it never again repeated, and I was stuck in softcrit eternally. I'm presuming it's a bug, and more specifically i'm guessing the reviver implant never recharged for some reason. Perhaps because androids might not have a heart?

## Testmerges:

[#75065: 'New Medical job: The Coroner' by JohnFulpWillard at commit 98557dd53f](https://www.github.com/tgstation/tgstation/pull/75065)

## Reproduction:

- Become Android / get fully auged
- Install reviver implant
- Softcrit
- Reviver implant only works once/doesn't work at all

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request

Currently the reviver implant stops working the first tick the player is above hard crit, meaning it leaves them right on the border between soft crit and hard crit. This, of course, means the player then falls right back into hard crit. And then the implant kicks in for a very short time, looping the player between hard and soft crit.

## Why It's Good For The Game

It doesn't seem like this could possibly be intended, so, bugfix that prevents the player from looping between soft and hard crit indefinitely.

closes https://github.com/tgstation/tgstation/issues/75139 (Thanks Sealed101 and timothymtorres)

## Changelog

:cl:
fix: The reviver implant will no longer leave its user looping between soft and hard critical states.
/:cl:

### CODE REVIEW

**Comment by Sealed101** [comment]
closes#75139

**Comment by timothymtorres** [comment]
> closes #75139

This needs to be included in the OP otherwise it won't autoclose.

**Comment by ExcessiveUseOfCobblestone** [comment]
Do you really want this firing off as soon as you get into crit? I guess it doesn't matter since you can cheese it w sleep but seems odd

**Comment by YehnBeep** [comment]
> Do you really want this firing off as soon as you get into crit? I guess it doesn't matter since you can cheese it w sleep but seems odd

I don't know, honestly. I just thought it wasn't working at first, and then in testing discovered it only works in hard crit, and that you'll loop between hard and soft.

Maybe an ideal would be 'starts in hard crit but then doesn't stop until you're totally out of crit'? Only I'm not sure how to do that.

**Comment by YehnBeep** [comment]
Hm. Excuse me a little bit, going to test something on local

**Comment by YehnBeep** [comment]
image

Ok that wasn't too hard... so I have a version that starts in hard crit but doesn't shut off for soft crit.

I'm not 100% sure how I feel about it since on the one hand it's a bit less intuitive but I can also kind of get that having it kick in at the first damage point into soft crit is a bit weird. But, anyways, looks like I can do it either way.

**Comment by Sealed101** [comment]
it's either a hardcrit start or some kind of timer that kicks in after you first enter soft crit, i guess

**Pull request merged**
