### PR TITLE
Mute Quirk

### PR DESCRIPTION
**Pull request by Orchian**
## About The Pull Request
Adds a quirk which makes the player completely unable to speak

## Why It's Good For The Game
Adds a quirk which will change how players approach various scenarios

## Changelog
:cl:
add: Due to crew shortages, the Organic Resources department has removed certain communicative minimums
/:cl:

### CODE REVIEW

**Comment by Fikou** [comment]
nice changelog bro bro

**Comment by Orchian** [comment]
> nice changelog bro bro

I can't find the fucking format, give it a moment

**Comment by RaveRadbury** [comment]
This has been suggested before, it steps on mime content. I'll try and find the last time this came up.

**Comment by Doosteroni** [comment]
Does this quirk give points? If so might want to restrict it from the mime...

**Comment by Orchian** [comment]
> Does this quirk give points? If so might want to restrict it from the mime...

I recieved the suggestion to make it a neutral quirk, though I am not married to either it giving points or not giving points

**Comment by RaveRadbury** [comment]
https://tgstation13.org/phpBB/viewtopic.php?f=9&t=24856&p=528781 Here's a forum thread about it, I could have sworn there was a PR in recent memory.

**Comment by MrDoomBringer** [comment]
makes the mime less cool and unique 👎

**Comment by Orchian** [comment]
> makes the mime less cool and unique 👎

I think if all that defines mime is that they don't talk, mime might need more work put in

**Comment by Pugie** [comment]
this is clearly a devastating quirk to make if worth the while it should reward 5 quirk points,

**Comment by PKPenguin321** [comment]
>I think if all that defines mime is that they don't talk, mime might need more work put in

this whole PR is defined by being unable to talk, put more work into it

**Comment by Jared-Fogle** [comment]
[Been there, done that.](https://github.com/tgstation/tgstation/pull/39504)

**Comment by RaveRadbury** [comment]
Ah, @Jared-Fogle was able to find it. Is it just me, or did the gitban mess up our search function?

**Comment by Orchian** [comment]
Temporary closing this PR to expand upon mimes

**Comment by Jared-Fogle** [comment]
@RaveRadbury Not sure. I just checked PRs under my name.

**Pull request closed without merging**
