### PR TITLE
[READY] Ctrl-clicking mobs is consistent in that it upgrades grabs

### PR DESCRIPTION
**Pull request by Chuckleberry-Finn**
:cl: Jittai
tweak: Ctrl+Clicking progresses through grab cycle on living mobs (not just humans)
/:cl:

[why]: consistency?

### CODE REVIEW

**Comment by nicbn** [comment]
Now the grab intent is useless

**Comment by ChuckTheSheep** [comment]
You can currently do it to only humans, seemed weird.

Also I could check later but the procs still need grab intent on to progress to strangling.

**Comment by nicbn** [comment]
Also CTRL+clicking twice used to stop the grab, when have this changed?

**Comment by ChuckTheSheep** [comment]
Probably cqc? No idea, but there's a ctrl click( humans proc in click.dm that mentions martialstyle

**Pull request merged**
