### PR TITLE
New mining mob icons

### PR DESCRIPTION
**Pull request by Jacquerel**
I made some icons to replace what were (I assume) leftover codersprites for the mining mobs for a downstream server, because we were tired of fighting floating squiggles and an unreadable toothy head.  
I didn't try at all to stay faithful to the original designs because I'm an egotistical asshole, and I wanted them to have a similar colour scheme/aesthetic.  
They might be a bit too bright or cartoony for /tg/ but I though I might as well make a pr here too anyway as they're still better than yours. Plus it's practice for if I ever code anything that isn't balanced entirely around the concept of having only 12 players and need to make a PR with code in it.  
Take them or leave them.  

Picture:  
miningmobs
Clockwise from top left; Basilisk, Goliath, Hivelord, Goldgrub
They have aggro/idle/readyattack(goliath) animations but I can't be bothered to record them.  

If there's some etiquette for icon PRs which I missed then I didn't see it on the wiki.

### CODE REVIEW

**Comment by WJohn** [comment]
SLUUUUGS

:+1:

So much better than the pitch black we had for shading and outlines.

**Comment by dannno** [comment]
I kind of liked the variety, the different colors and stuff tbh.
But these sprites are cool and I guess it's kind of cool if they're all related too.

**Comment by phil235** [comment]
I wish there were more color variety, but this looks really good nonetheless.

**Comment by dannno** [comment]
did you also change the goliath tentacles to be pink?

**Comment by paprka** [comment]
"did you also change the goliath tentacles to be pink?"

**Comment by dannno** [comment]
what

**Comment by paprka** [comment]
ss 2015-02-14 at 01 00 03

You need to change this and mech plating overlays as well, for ripleys.

**Comment by Jacquerel** [comment]
The tentacles animation's updated too, I'll have the poster and mech plating in a few minutes. Our server's not quite updated to live, so it didn't have ripley mech plating yet.

**Comment by paprka** [comment]
thanks dude, i like the aesthetic of these. they're a little goofier but the consistency is a really good thing i think.

**Comment by RandomMarine** [comment]
The overall quality of the sprites are a lot better, but I'm just not a fan of the designs, especially so for the flying testicle hivelords.

**Comment by Jacquerel** [comment]
miningsprites2 
I like the minimal armour more than the complete one, and unfortunately there's no tail, but it has sprites now anyway.

**Comment by WJohn** [comment]
Very nicely done :+1:

**Comment by paprka** [comment]
well done, i like it.

**Comment by Anonus** [comment]
The outlines on some of them really pop out at you, which isn't really good, and I don't like the red blood for death sprites.

**Comment by Deantwo** [comment]
Makes me wanna try mining again. :+1:

**Comment by AlexCrimson** [comment]
Do the Goliaths eyes flash when its about to spawn tentacles? Does the Basalisk change color when its attacking a player?

**Comment by paprka** [comment]
Why not look at the files yourself alex

**Comment by AlexCrimson** [comment]
I dont know a thing about coding, paprika

**Comment by Jacquerel** [comment]
image
Goliath attack
image
Basilisk attack

**Comment by RemieRichards** [comment]
I embedded your gifs, Also 10/10 love these sprites :+1:

**Comment by AlexCrimson** [comment]
Eh i kinda preferred the old Basilisks. They were like some kind of crystal entity, which i thought was pretty neat. The sprites for the Hivelord is great though.

Is it just me, or is there some kind of issue with the Goliath sprite? In the gif when it moves to the left, the bottom of the creature kinda overlaps the red asteroid tile below it. Not sure if thats intended or not.

**Comment by Jacquerel** [comment]
Asteroid borders will overlap anything in the tiles next to them, it's the price of not being exactly square. It's just more noticeable with a big mob. 
If you ghost and float through the sides of the asteroid walls right now, you can see yourself pass under the overlay!  
Nothing I can really do about that one myself.

**Comment by Miauw62** [comment]
I feel like the tentacles should be changed a little bit, they blend in with the terrain a lot right now, but apart from that, :+1:

@Ergovisavi

**Comment by Chocobro** [comment]
not a fan of the basilisk one, I feel like it should be blue still. could be nostalgia talking. the rest are fine.

**Comment by Kromgar** [comment]
I like Goliaths how they are now. The slug goliaths don't look intimidating at all.

I do like the gold grub and hive lord ones though. Perhaps  the Hivelords could be the females giving birth to new ones and Gold Grubs are the males gathering food for the baby hive babies

Goliaths look like a monster that grows its plates from eating asteroid materials and basilisk looks alien and unique.


Anything is better than the hivelord we have now. It looks like shit.

**Comment by Lumipharon** [comment]
The bottom edge of the FLESH SNAIL and the FLESH SLUG are both perfectly straight and clean, which looks a bit wierd. The dead sprites don't have that issue though.

**Comment by paprka** [comment]
Yeah they're kinda flat and it's noticible on some tiles

**Comment by Niknakflak** [comment]
I think these look odd and not with the style but yea, you are right, they are alot better than what we have now.

**Comment by WJohn** [comment]
Unfortunately it's not something we can exactly fix, the flatness I assume is due to their skin sagging off to the side, like a water balloon placed on the ground. Inevitably you'll get a lot of flatness on the bottom, and our flat-in-front view for mobs is just adding to that.

**Comment by Chocobro** [comment]
now that I look at it, the goliath does look a lot like a turd slug to me. my preference would be to only add the goldgrub and hivelord sprites.

**Comment by RemieRichards** [comment]
Current consensus on the forums is 10 Positive and 6 Negative unique* responses (Why the hell isn't it a poll? I have do count like a philistine!)

And here appears to be 7 Positive and 6 Negative unique* responses

*Each individual counted once and adjusted if their opinion changed.

**Comment by Fox-McCloud** [comment]
Don't like these at all; they're too similar---and it's kinda silly that a goliath is a giant snail (quick, smoke it with salt!)

**Comment by Lumipharon** [comment]
If these don't get used for mining mobs, because they're so 'themed', someone should use them for an away mission or something - swamp monsters, I unno.

**Comment by paprka** [comment]
Mining mobs should be themed imo, they look too different atm and it's silly as hell, like it's pokemon or some shit

**Comment by Stickymayhem** [comment]
I prefer the original goliath sprites to be honest. The original goliath looks like something that will smash down a fucking wall and beat you to death while the new one looks like a snail. The black tentacles are fairly important too. The hivelord sprite is actually amazing but I think the fleshy look overall blends into the asteroid a little too much.  I could swing either way on the basilisk. I liked how they went bright red when they aggroed before. The flashing eyes is a lot harder to read.

**Comment by Kromgar** [comment]
Why do people think these look better? The ones we have look unique and intereting. Goliaths look like they are plated with the asteroid mineral. Basilisks eat diamonds so they look crystalline. The only problem is the hive lord. Gold grubs should just be renamed to something to better fit that it eats EVERYTHING

**Comment by mikecari** [comment]
Remie doesn't care what you think, Kromgar, he'll keep shilling these sprites out of spite.

**Comment by Steelpoint** [comment]
:+1:

**Comment by dannno** [comment]
mikecari, you are hitting paprika/startoad levels of schizophrenia
take it down a notch

**Comment by paprka** [comment]
But startoad has never had a decent idea in his life

**Comment by RemieRichards** [comment]
@mikecari 
>he'll

Nope, I'll keep shilling because of this.

Anyway no, I'm "shilling" these sprites because I prefer them, to me, they're objectively better.

**Comment by paprka** [comment]
I like that they're all the same theme, sure it's harder to identify which kind they are but they feel like they're all kind of friendly to each other (because they don't attack each other iirc, and it makes sense if they're all the same kind of rock-eating slugbeasts)

**Comment by Jordie0608** [comment]
Changelog

**Comment by Miauw62** [comment]
@WJohn @Nienhaus

**Comment by RemieRichards** [comment]
@Miauw62 @WJohn has already given his opinion.

**Comment by WJohn** [comment]
I like these sprites plenty. They're well drawn, consistent with our flat-in-front mob perspective, have a limited color palette, and are all drawn to look like they come from the same place. :+1:

**Comment by Violaceus** [comment]
Are organisms living in forests look all the same? 

This argument is plain wrong.

**Comment by Lumipharon** [comment]
No, but all squirrels look similar. There's only 4 of them yo, they clearly have a common ancestor.

**Comment by paprka** [comment]
forests have diverse ecosystems and asteroids are literally just rocks

rekt status:

☐ Not REKT
☑ REKT

**Comment by mikecari** [comment]
>m-muh darwin

Paprika no one cares about realism in a fucking 2d spaceman game. They want sprites that are easily recognizable and have strong visual indicators: IE: the goliath's eye movement when attacking.

**Comment by Jacquerel** [comment]
They do actually have the same number of idle/aggro/attacking states as the previous sprites.

**Comment by dannno** [comment]
>trying to make this about realism

oh my god fuck off this is all about the aesthetic and the fact that they all resemble each other which hints to the fact that they might have come from a common ancestor is purely appealing, if anything

**Comment by dannno** [comment]
THAT BEING SAID; They could be slightly more distinctive. Even just by color, each mob could have a specific minor detail color (basilisks blues, goliaths red, etc) that would help in identifying a monster quickly.

**Comment by Jacquerel** [comment]
I'm quite happy to recolour things if people want, just not sure at the moment that would change the minds of enough of the people who just plain don't like them to make much of a difference. Will give it another look tomorrow.

**Comment by Razharas** [comment]
They look like something from early zelda games
Current ones looks grimdark and edgy, which is more fitting

**Comment by paprka** [comment]
who cares

**Comment by dannno** [comment]
he does
i mean it's a purely aesthetic change so all we HAVE are people's opinions

**Comment by paprka** [comment]
Aesthetic changes affect more than people's personal feelings and artistic opinions believe it or not.

**Comment by RandomMarine** [comment]
:+1: Basilisk. Distinct, look like they have some diamonds to harvest instead of the truckload that current basilisks do.
:-1: Goliath. Gross. Plated ripley looks like it just has feces smeared on it.
:+1: Goldgrub. Looks okay, not much else to say.
:-1: Hivelord. Current sprite is shit, yes. But I'll take it over flying testicles.

**Comment by AnonymousNow** [comment]
I'm not fond of any of these. I feel our current sprites need something, but generic slug & snail monsters isn't the way to go.

**Comment by Nienhaus** [comment]
I'm honestly not sure how I feel about this. The sprites look good but color is nice.

**Comment by Jacquerel** [comment]
I've been too busy to work on the changes I said I'd make and might be for a while, I'll reopen this or make it again when I'm done.

**Pull request closed without merging**
