### PR TITLE
removes a comment from malf modules 

### PR DESCRIPTION
**Pull request by TheWiznard**
Because the ///end doomsday device thing was below the /datum/AI_Module/large/fireproof_core thing, also removes double blank lines that weren't needed? I don't really feel proud about myself only changing the comment so I removed double blank lines, this is my first real merge pull thing hopefully nothing goes horribly wrong like before.

okay a monkey could have done this but everyone starts somewhere

### CODE REVIEW

**Comment by optimumtact** [comment]
DELETE IT

**Comment by TheWiznard** [comment]
Delete what?

**Comment by KazeEspada** [comment]
Its such a minor change that the maintainers are covering it in tags and shit for memes.

**Comment by Jordie0608** [comment]
He means you might as well delete the comment outright, it's basically pointless

**Comment by TheWiznard** [comment]
Okay @optimumtact I've done as you've requested

**Comment by duncathan** [comment]
this is a beautiful first pr

**Comment by optimumtact** [comment]
proud of you

**Comment by Supermichael777** [comment]
doomsday device needs to be tied to the ai mind. but that's way beyond first pr

**Comment by Jordie0608** [comment]
What

**Pull request merged**
