### PR TITLE
Buzz!

### PR DESCRIPTION
**Pull request by ExcessiveUseOfCobblestone**
:cl: Cobby
add: Finally, a way to relate to Bees!
/:cl:

Adds the Bee Suit, which not only looks cute [CUTE!], it also protects you from bees so you can wear it while managing them! 

Oh yeah pictures... Again I'm new to the spriting scene so feel free to let me know how I can improve on making a pixel bee suit.

### CODE REVIEW

**Comment by TehZombehz** [comment]
[Insert entire bee movie script here].

**Comment by ExcessiveUseOfCobblestone** [comment]
According to all known laws
of aviation,

  
there is no way a bee
should be able to fly.

  
Its wings are too small to get
its fat little body off the ground.

  
The bee, of course, flies anyway

  
because bees don't care
what humans think is impossible.

  
Yellow, black. Yellow, black.
Yellow, black. Yellow, black.

  
Ooh, black and yellow!
Let's shake it up a little.

**Comment by PKPenguin321** [comment]
BUZZ LOOK AN ALIEN

**Comment by ExcessiveUseOfCobblestone** [comment]
if this isn't the cutest/derpiest costume I don't know what is

**Comment by IcePacks** [comment]
https://youtu.be/2k0SmqbBIpQ

**Comment by ExcessiveUseOfCobblestone** [comment]
https://www.youtube.com/watch?v=8CvqmD0CZao

**Comment by kevinz000** [comment]
not cute

**Comment by PKPenguin321** [comment]
Mekhi stop talking to yourself out loud

**Comment by ExcessiveUseOfCobblestone** [comment]
We're talking about the bee suit, not mekhi

**Comment by ShadowDeath6** [comment]
black to yellow < yellow to black

**Comment by calzilla1** [comment]
Close.  ERP is banned

**Comment by Niknakflak** [comment]
Should change your speech to buzzes and ZZZzzzs stuff like the wrestling mask does.

**Comment by Cheridan** [comment]
The sprite's inconsistent. When the sprite is facing you the arms are black, when it's side-view there is no black and the arms are instead striped.

Some highlights would also go a long way towards making it look better

**Comment by ExcessiveUseOfCobblestone** [comment]
> Should change your speech to buzzes and ZZZzzzs stuff like the wrestling mask does.

Unfortunately that's only tied to masks, so I'd have to make a bee mask for that to work [or change it entirely].

**Comment by Militaires** [comment]
@ExcessiveUseOfCobblestone 
https://www.youtube.com/watch?v=jgVDOsNWiAU
https://www.youtube.com/watch?v=5o3x8CtcAqo

you have no style

**Comment by Chocobro** [comment]
e14

**Pull request merged**
