### PR TITLE
Red security

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
Ausops has disavowed grey security and I trust ausops with my life

Also the disgusting compromise to make them start uglier on purpose (helmets instead of caps) ruined grey sec anyway, so here is red security back.

Grey security stuff still exists so goof can pursue his zany project and so we can use them as uniforms for private security in ruins/away missions or something.

:cl: Kor
rscadd: Security is red again.
/:cl:

### CODE REVIEW

**Comment by TechnoAlchemisto** [comment]
I Would Die For You Kor Phaeron

**Comment by Iamgoofball** [comment]
:-1: do not touch icon state names

**Comment by KorPhaeron** [comment]
@Iamgoofball 

I had to because SOMEONE named the red security stuff the wrong thing in the uniforms file

**Comment by GunHog** [comment]
Sec Wars. War never changes.

**Comment by Shadowlight213** [comment]
FEATURE/BALANCE FREEZE

**Comment by ChangelingRain** [comment]
NO MORE SEC SPRITE WARS
also this is totally a feature and it should chill the fuck out

**Comment by KorPhaeron** [comment]
Sprites are immune to the freeze as per the terms of the freeze sorry

**Comment by Steelpoint** [comment]
This should probably be reviewed/merged since its unlikely Goof's PR will be merged until after the freeze.

**Comment by Iamgoofball** [comment]
nope, it'll conflict and my PR is a bugfix

**Pull request closed without merging**
