### PR TITLE
Graffiti no longer explicitly stated to be drawn with crayons.

### LINKED ISSUE #14498: Spray painted graffiti has "drawn in crayon" in its desc
spraycans just make the same thing that crayons do, so its called 'A graffiti drawn in crayon' which doesn't make much sense

Also gangtags place the graffiti on the wall tile itself so its visible on both sides of the wall which doesn't make much sense either

### PR DESCRIPTION
**Pull request by Buggy123**
Fixes #14498

### CODE REVIEW

**Comment by Bawhoppen** [comment]
why not just give all graffiti, whether spray painted or drawn by crayon, some neutral desc like "Graffiti. Damn kids."

**Comment by Buggy123** [comment]
I dunno, that could work too I guess. But a way of distinguishing between them might be desirable.

**Comment by AnturK** [comment]
This applies only to GANG signs not spraypainted ones.

**Comment by Bawhoppen** [comment]
thats what I thought but I wasn't sure aswell, so I didn't want to call it out

**Comment by Buggy123** [comment]
Ok, so I can't even find where normal crayons create a new decal, so I'm just gonna make the description generic and call it a day.

**Comment by Dorsisdwarf** [comment]
Is this ready for freddy?

**Comment by Buggy123** [comment]
Yeah, it should be ready to merge. I don't see why it wouldn't be.

**Pull request merged**
