### PR TITLE
Remove sanitize_ooccolor

### PR DESCRIPTION
**Pull request by j-mie**
Why would you not allow admins to have neon pink OOC colours :(

### CODE REVIEW

**Comment by lzimann** [comment]
>Why would you not allow admins to have neon pink OOC colours :(

Maybe because it would be awful to have super bright that no one can read colors.

**Comment by JamieH** [comment]
@lzimann i mean, admins should just pick colours which don't do that, rather then some arbitrary shit limit

**Comment by kevinz000** [comment]
lmao

**Comment by Bawhoppen** [comment]
@JamieH We can't encourage admins, they have been proven to not be trustworthy with stuff like this

**Review by Cyberboss — DISMISSED** [review]
Remove the proc too

**Comment by JamieH** [comment]
I assumed the proc was used else where, yay I was right.

**Review by Cyberboss — APPROVED** [review]

**Pull request merged**
