### PR TITLE
Removes cryostasis pods from the game pending creation of a proper design document

### PR DESCRIPTION
**Pull request by Timberpoes**
## Todo List
- [x] Axe the code
- [x] Axe the mapping changes

## What Is This Removal About?

At this point I have decided that Cryopods are a feature which has scope far beyond just "easy way to leave shift".

They touch upon enough areas of the game (heads of staff, antags, admin alerts, policy and more) to now require a design document to ensure:
1. It is done properly from the outset.
2. It documents all the goals it sets out to accomplish along with the rationales behind them.
3. It documents the problem areas and the agreed solutions to those problems.
4. The maintainer team has had appropriate input and discussion into which solutions are preferred for which problems.

I am **temporarily** removing Cryopods until such a design document is written for them. This design document must be backed by a maintainer before pods are reintroduced. It will form the backbone of design decisions taken around cryopods and allow issues to be highlighted with any planned implementations.

The design document **must** outline all key implementation including **but not limited to** what happens whan an antag cryos; what happens when a head of staff cryos; when admins should be alerted to a player leaving the shift via cryo; what happens to items when crew cryo; whether cyborgs can cryo; and whether you can cryo other people (and when).

It should justify reasons for cryo pods existing. Those reasons should be more than just "I don't want a body left behind when a player has no intention of playing the rest of the shift". Other methods of achieving the same outcomes should be addressed including what role we expect the HoP to play in managing job slots and why Cryopods are the superior choice from a game design perspective.

## About The Pull Request

Removes Cryostasis pods from the game, including their DMI and tertiary supporting code.

This is effectively a near-complete revert of #59742 and all PRs that have followed on from that fixing or tweaking Cryopods.

Retains changes to code/modules/antagonists/cult/cult.dm which received extensive code review and probably aren't broken.

## Mapping Adjustments

Icebox has been given Dorms 1 back.
image

Kilo has been given a little seating alcove in the locker room.
image

Delta has been given a new chunk of space. To make up for this, I did some cleanup with the nearspace areas around this part and made sure everything was reasonably neat and tidy
image

Meta has been given a pair of arcade cabinets with their backs to the void of space.
image

Tram has been given uh... Another 6 washing machines.
image

## Why It's Good For The Game

I was about to embark on my second partial rewrite/refactor of Cryostasis Pod code after https://github.com/tgstation/tgstation/pull/59098.

The Cryostasis pod code handling when antags cryo is terrible, including such wonderful sins as:

No early returns - Smelly code.
Accessing a variable member immediately after qdeletion - Terrible coding practice, undefined behaviour.
Causing hard deletions by qdeling objectives that are referenced in antag datums - Smelly code, causes secondary runtimes in admin traitor panel.
Logical errors such as qdeling objectives despite successfully re-assigning a target to them - Smelly code, logical errors.

I think enough is enough with hotfixing issues caused by Cryopods.

There are still questions about what we really want to do with cryoing antags, cryoing heads, cryoing cyborgs and cryoing gear. All these questions should be answered with appropriate maintainer approval **before** the feature is (re-)introduced. 

I want them gone until a proper design document is created to pave the way for their return.

## Changelog

:cl:
del: Cryostasis pods have been removed from all maps and code.
/:cl:

### CODE REVIEW

**Comment by Addust** [comment]
Might be useful but going SSD without committing intentional russian roulette failure will be harder

**Comment by jlsnow301** [comment]
I'm sure you don't **need** my approval but I did originally port cryopods to tg. With the removal of item storage and the ability to stuff afk's inside, they have strayed quite far from their original intent

**Comment by Mothblocks** [comment]
theres nothing more permanent than temporary

**Comment by Timberpoes** [comment]
> 
> 
> I'm sure you don't **need** my approval but I did originally port cryopods to tg. With the removal of item storage and the ability to stuff afk's inside, they have strayed quite far from their original intent

This is also an important part of needing a design document.

**Comment by Timberpoes** [comment]
> 
> 
> theres nothing more permanent than temporary

Truly we've been doing it wrong this whole time!

Instead of blocking features we don't want, we should just be requiring them to be well coded and well justified. It's practically the same thing with none of the political overhead.

**Comment by Mothblocks** [comment]
this but unironically

**Comment by CRITAWAKETS** [comment]
what even is the point of this aside from le trolling

you can just type ghost or suicide and you will have the same effect, the only change is that cryopods are more RP-oriented and dont leave a body. i guess you could just change it to have an empty body produced for medical if you really want it to be the rp-oriented way of round-ending yourself with the same consequences?

**Comment by Ghilker** [comment]
> what even is the point of this aside from le trolling (dont say there isnt a little bit of le trolling just read the branch name) ((this is totally not just so people read the branch name, nope))
> 
> you can just type ghost or suicide and you will have the same effect, the only change is that cryopods are more RP-oriented and dont leave a body. i guess you could just change it to have an empty body produced for medical if you really want it to be the rp-oriented way of round-ending yourself with the same consequences?

is shitcode, has no clear purpose and there is no design, haven't you read the PR?

**Comment by Bawhoppen** [comment]
👍 I mentioned this in Coderbus, but we could consider bringing back https://github.com/tgstation/tgstation/pull/49031. They pose none of the design problems regarding items/antags, and none of the code problems (in the fact they are effectively just lockers).

**Comment by Mothblocks** [comment]
the reason is because their purpose is confusing and their code is worse

**Comment by Acer202** [comment]
Well, the cryopods were really nice in that the hallways were less filled with assistant tomato paste. I guess I can see why it's not so easy when you need to consider antags/heads of staff but I'd rather patch that temporarily by just forbidding antags/heads of staff from cryoing for now.

**Comment by Mothblocks** [comment]
to be honest i think the cryo pods are nice, but not if they're going to cause so many issues

**Comment by Timberpoes** [comment]
> 
> 
> what even is the point of this aside from le trolling (dont say there isnt a little bit of le trolling just read the branch name) ((this is totally not just so people read the branch name, nope))
> 
> you can just type ghost or suicide and you will have the same effect, the only change is that cryopods are more RP-oriented and dont leave a body. i guess you could just change it to have an empty body produced for medical if you really want it to be the rp-oriented way of round-ending yourself with the same consequences?

Shitposty branch names is all I've got left in life. Don't take this away from me.

image

**Comment by Timberpoes** [comment]
Mapping adjustments:
Icebox has been given Dorms 1 back.
image

Kilo has been given a little seating alcove in the locker room.
image

Delta has been given a new chunk of space. To make up for this, I did some cleanup with the nearspace areas around this part and made sure everything was reasonably neat and tidy
image

Meta has been given a pair of arcade cabinets with their backs to the void of space.
image

Tram has been given uh... Another 6 washing machines.
image

**Comment by Bawhoppen** [comment]
>Delta and Meta tumors have been excised

Finally, nature is healing

**Review by Mothblocks — APPROVED** [review]
Pending maptainers

**Review by Maurukas — APPROVED** [review]

**Comment by Zytolg** [comment]
Meanwhile I'm working on a complete rework of Icebox's North Section. I suppose I'll turn the (new) Cryopod room into a Laundromat until Cryopods are back in, at which point the room will be used for cryopods again.

**Comment by tralezab** [comment]
consider the maptainers pent

**Comment by NanoCats** [comment]
Easy come easy go, I feel like this doesn't really solve anything, personally, if somebody elects that they're bored of the shift they could cryo.

Now they're just going to 

- A, commit suicide
- B, stand there uselessly as a comatose body decorating a room, stealing our oxygen

**Comment by Mothblocks** [comment]
Then someone should fix the code

**Pull request merged**
