### PR TITLE
changes intercom sprites

### PR DESCRIPTION
**Pull request by dannno**
ported from citadel station

they are much nicer than ours

### CODE REVIEW

**Comment by RussellTalbott** [comment]
danno, **AGAIN**, despite having numerous people giving **VERY CLEAR** and **CONCISE** criticism against his flouting of the artistic direction of the original game, has brought to us a (bad) sprite.  danno, you have been down thumbered, and i pray that

**Comment by dannno** [comment]
fartistic direction

**Comment by DoctoreMad** [comment]
^Not an argument.

**Comment by Hatfish** [comment]
This looks terrible with our current wall sprites.

**Comment by TrustyGun** [comment]
won't this look weird on the other sides of the walls? do they have directional sprites?

otherwise looks pretty good

**Comment by KorPhaeron** [comment]
Everything russell said but unironically

**Comment by WJohn** [comment]
I think they could be a little bit bigger, and perhaps a tiny bit thinner, too, they do look extremely chunky. More detail on the actual microphone/speaker area would be nice (a criss cross pattern would work fine, like ours is now).

**Comment by ExcessiveUseOfCobblestone** [comment]
WHY DOES EVERY OBJECT NEED TO BE 3/4th REEEEEEEEEEEEEEEE

**Comment by TrustyGun** [comment]
these directional sprites are awful. they are just rotated versions of the one shown

image

**Comment by SgtxRootbeer** [comment]
Can we fucking stop with 3/4ths? 
It's garbage and doesn't work too well.

**Comment by BeeSting12** [comment]
the three fourths sprites are shit. still salty about toolboxes tbh

**Comment by MMMiracles** [comment]
As long as the only person being assigned and directed to with sprite changes is in favor of these changes, no amount of negative feedback is going to do anything, if past PRs are anything to go by. 

Revolt against the man, don't let them take away 1/4th of our stations.

**Comment by dannno** [comment]
*farts on all your posts* ahahahaha lol

**Comment by Bawhoppen** [comment]
I actually don't know why we chose 3/4ths

**Comment by WJohn** [comment]
I'm not happy with those directionals. Until we get actual 3/4th walls, it's best not to mess with those, and to do them CORRECTLY instead of just lazily rotating them. Please change it to only have the south direction.

**Comment by Tacolizard** [comment]
>down thumbered

**Comment by MoreRobustThanYou** [comment]
this looks like it came out of my butt and REEEE 3/4

**Comment by Militaires** [comment]
danno, AGAIN, despite having numerous people giving VERY CLEAR and CONCISE criticism against his flouting of the artistic direction of the original game, has brought to us a (bad) sprite. danno, you have been down thumbered, and i pray thatdanno, AGAIN, despite having numerous people giving VERY CLEAR and CONCISE criticism against his flouting of the artistic direction of the original game, has brought to us a (bad) sprite. danno, you have been down thumbered, and i pray thatdanno, AGAIN, despite having numerous people giving VERY CLEAR and CONCISE criticism against his flouting of the artistic direction of the original game, has brought to us a (bad) sprite. danno, you have been down thumbered, and i pray thatdanno, AGAIN, despite having numerous people giving VERY CLEAR and CONCISE criticism against his flouting of the artistic direction of the original game, has brought to us a (bad) sprite. danno, you have been down thumbered, and i pray thatdanno, AGAIN, despite having numerous people giving VERY CLEAR and CONCISE criticism against his flouting of the artistic direction of the original game, has brought to us a (bad) sprite. danno, you have been down thumbered, and i pray thatdanno, AGAIN, despite having numerous people giving VERY CLEAR and CONCISE criticism against his flouting of the artistic direction of the original game, has brought to us a (bad) sprite. danno, you have been down thumbered, and i pray thatdanno, AGAIN, despite having numerous people giving VERY CLEAR and CONCISE criticism against his flouting of the artistic direction of the original game, has brought to us a (bad) sprite. danno, you have been down thumbered, and i pray thatdanno, AGAIN, despite having numerous people giving VERY CLEAR and CONCISE criticism against his flouting of the artistic direction of the original game, has brought to us a (bad) sprite. danno, you have been down thumbered, and i pray thatdanno, AGAIN, despite having numerous people giving VERY CLEAR and CONCISE criticism against his flouting of the artistic direction of the original game, has brought to us a (bad) sprite. danno, you have been down thumbered, and i pray thatdanno, AGAIN, despite having numerous people giving VERY CLEAR and CONCISE criticism against his flouting of the artistic direction of the original game, has brought to us a (bad) sprite. danno, you have been down thumbered, and i pray thatdanno, AGAIN, despite having numerous people giving VERY CLEAR and CONCISE criticism against his flouting of the artistic direction of the original game, has brought to us a (bad) sprite. danno, you have been down thumbered, and i pray thatdanno, AGAIN, despite having numerous people giving VERY CLEAR and CONCISE criticism against his flouting of the artistic direction of the original game, has brought to us a (bad) sprite. danno, you have been down thumbered, and i pray thatdanno, AGAIN, despite having numerous people giving VERY CLEAR and CONCISE criticism against his flouting of the artistic direction of the original game, has brought to us a (bad) sprite. danno, you have been down thumbered, and i pray thatdanno, AGAIN, despite having numerous people giving VERY CLEAR and CONCISE criticism against his flouting of the artistic direction of the original game, has brought to us a (bad) sprite. danno, you have been down thumbered, and i pray thatdanno, AGAIN, despite having numerous people giving VERY CLEAR and CONCISE criticism against his flouting of the artistic direction of the original game, has brought to us a (bad) sprite. danno, you have been down thumbered, and i pray thatdanno, AGAIN, despite having numerous people giving VERY CLEAR and CONCISE criticism against his flouting of the artistic direction of the original game, has brought to us a (bad) sprite. danno, you have been down thumbered, and i pray thatdanno, AGAIN, despite having numerous people giving VERY CLEAR and CONCISE criticism against his flouting of the artistic direction of the original game, has brought to us a (bad) sprite. danno, you have been down thumbered, and i pray thatdanno, AGAIN, despite having numerous people giving VERY CLEAR and CONCISE criticism against his flouting of the artistic direction of the original game, has brought to us a (bad) sprite. danno, you have been down thumbered, and i pray thatdanno, AGAIN, despite having numerous people giving VERY CLEAR and CONCISE criticism against his flouting of the artistic direction of the original game, has brought to us a (bad) sprite. danno, you have been down thumbered, and i pray thatdanno, AGAIN, despite having numerous people giving VERY CLEAR and CONCISE criticism against his flouting of the artistic direction of the original game, has brought to us a (bad) sprite. danno, you have been down thumbered, and i pray thatdanno, AGAIN, despite having numerous people giving VERY CLEAR and CONCISE criticism against his flouting of the artistic direction of the original game, has brought to us a (bad) sprite. danno, you have been down thumbered, and i pray thatdanno, AGAIN, despite having numerous people giving VERY CLEAR and CONCISE criticism against his flouting of the artistic direction of the original game, has brought to us a (bad) sprite. danno, you have been down thumbered, and i pray thatdanno, AGAIN, despite having numerous people giving VERY CLEAR and CONCISE criticism against his flouting of the artistic direction of the original game, has brought to us a (bad) sprite. danno, you have been down thumbered, and i pray thatdanno, AGAIN, despite having numerous people giving VERY CLEAR and CONCISE criticism against his flouting of the artistic direction of the original game, has brought to us a (bad) sprite. danno, you have been down thumbered, and i pray thatdanno, AGAIN, despite having numerous people giving VERY CLEAR and CONCISE criticism against his flouting of the artistic direction of the original game, has brought to us a (bad) sprite. danno, you have been down thumbered, and i pray thatdanno, AGAIN, despite having numerous people giving VERY CLEAR and CONCISE criticism against his flouting of the artistic direction of the original game, has brought to us a (bad) sprite. danno, you have been down thumbered, and i pray thatdanno, AGAIN, despite having numerous people giving VERY CLEAR and CONCISE criticism against his flouting of the artistic direction of the original game, has brought to us a (bad) sprite. danno, you have been down thumbered, and i pray thatdanno, AGAIN, despite having numerous people giving VERY CLEAR and CONCISE criticism against his flouting of the artistic direction of the original game, has brought to us a (bad) sprite. danno, you have been down thumbered, and i pray thatdanno, AGAIN, despite having numerous people giving VERY CLEAR and CONCISE criticism against his flouting of the artistic direction of the original game, has brought to us a (bad) sprite. danno, you have been down thumbered, and i pray thatdanno, AGAIN, despite having numerous people giving VERY CLEAR and CONCISE criticism against his flouting of the artistic direction of the original game, has brought to us a (bad) sprite. danno, you have been down thumbered, and i pray thatdanno, AGAIN, despite having numerous people giving VERY CLEAR and CONCISE criticism against his flouting of the artistic direction of the original game, has brought to us a (bad) sprite. danno, you have been down thumbered, and i pray thatdanno, AGAIN, despite having numerous people giving VERY CLEAR and CONCISE criticism against his flouting of the artistic direction of the original game, has brought to us a (bad) sprite. danno, you have been down thumbered, and i pray thatdanno, AGAIN, despite having numerous people giving VERY CLEAR and CONCISE criticism against his flouting of the artistic direction of the original game, has brought to us a (bad) sprite. danno, you have been down thumbered, and i pray thatdanno, AGAIN, despite having numerous people giving VERY CLEAR and CONCISE criticism against his flouting of the artistic direction of the original game, has brought to us a (bad) sprite. danno, you have been down thumbered, and i pray thatdanno, AGAIN, despite having numerous people giving VERY CLEAR and CONCISE criticism against his flouting of the artistic direction of the original game, has brought to us a (bad) sprite. danno, you have been down thumbered, and i pray thatdanno, AGAIN, despite having numerous people giving VERY CLEAR and CONCISE criticism against his flouting of the artistic direction of the original game, has brought to us a (bad) sprite. danno, you have been down thumbered, and i pray thatdanno, AGAIN, despite having numerous people giving VERY CLEAR and CONCISE criticism against his flouting of the artistic direction of the original game, has brought to us a (bad) sprite. danno, you have been down thumbered, and i pray thatdanno, AGAIN, despite having numerous people giving VERY CLEAR and CONCISE criticism against his flouting of the artistic direction of the original game, has brought to us a (bad) sprite. danno, you have been down thumbered, and i pray thatdanno, AGAIN, despite having numerous people giving VERY CLEAR and CONCISE criticism against his flouting of the artistic direction of the original game, has brought to us a (bad) sprite. danno, you have been down thumbered, and i pray thatdanno, AGAIN, despite having numerous people giving VERY CLEAR and CONCISE criticism against his flouting of the artistic direction of the original game, has brought to us a (bad) sprite. danno, you have been down thumbered, and i pray thatdanno, AGAIN, despite having numerous people giving VERY CLEAR and CONCISE criticism against his flouting of the artistic direction of the original game, has brought to us a (bad) sprite. danno, you have been down thumbered, and i pray thatdanno, AGAIN, despite having numerous people giving VERY CLEAR and CONCISE criticism against his flouting of the artistic direction of the original game, has brought to us a (bad) sprite. danno, you have been down thumbered, and i pray thatdanno, AGAIN, despite having numerous people giving VERY CLEAR and CONCISE criticism against his flouting of the artistic direction of the original game, has brought to us a (bad) sprite. danno, you have been down thumbered, and i pray thatdanno, AGAIN, despite having numerous people giving VERY CLEAR and CONCISE criticism against his flouting of the artistic direction of the original game, has brought to us a (bad) sprite. danno, you have been down thumbered, and i pray thatdanno, AGAIN, despite having numerous people giving VERY CLEAR and CONCISE criticism against his flouting of the artistic direction of the original game, has brought to us a (bad) sprite. danno, you have been down thumbered, and i pray thatdanno, AGAIN, despite having numerous people giving VERY CLEAR and CONCISE criticism against his flouting of the artistic direction of the original game, has brought to us a (bad) sprite. danno, you have been down thumbered, and i pray thatdanno, AGAIN, despite having numerous people giving VERY CLEAR and CONCISE criticism against his flouting of the artistic direction of the original game, has brought to us a (bad) sprite. danno, you have been down thumbered, and i pray thatdanno, AGAIN, despite having numerous people giving VERY CLEAR and CONCISE criticism against his flouting of the artistic direction of the original game, has brought to us a (bad) sprite. danno, you have been down thumbered, and i pray thatdanno, AGAIN, despite having numerous people giving VERY CLEAR and CONCISE criticism against his flouting of the artistic direction of the original game, has brought to us a (bad) sprite. danno, you have been down thumbered, and i pray thatdanno, AGAIN, despite having numerous people giving VERY CLEAR and CONCISE criticism against his flouting of the artistic direction of the original game, has brought to us a (bad) sprite. danno, you have been down thumbered, and i pray thatdanno, AGAIN, despite having numerous people giving VERY CLEAR and CONCISE criticism against his flouting of the artistic direction of the original game, has brought to us a (bad) sprite. danno, you have been down thumbered, and i pray thatdanno, AGAIN, despite having numerous people giving VERY CLEAR and CONCISE criticism against his flouting of the artistic direction of the original game, has brought to us a (bad) sprite. danno, you have been down thumbered, and i pray thatdanno, AGAIN, despite having numerous people giving VERY CLEAR and CONCISE criticism against his flouting of the artistic direction of the original game, has brought to us a (bad) sprite. danno, you have been down thumbered, and i pray thatdanno, AGAIN, despite having numerous people giving VERY CLEAR and CONCISE criticism against his flouting of the artistic direction of the original game, has brought to us a (bad) sprite. danno, you have been down thumbered, and i pray thatdanno, AGAIN, despite having numerous people giving VERY CLEAR and CONCISE criticism against his flouting of the artistic direction of the original game, has brought to us a (bad) sprite. danno, you have been down thumbered, and i pray thatdanno, AGAIN, despite having numerous people giving VERY CLEAR and CONCISE criticism against his flouting of the artistic direction of the original game, has brought to us a (bad) sprite. danno, you have been down thumbered, and i pray thatdanno, AGAIN, despite having numerous people giving VERY CLEAR and CONCISE criticism against his flouting of the artistic direction of the original game, has brought to us a (bad) sprite. danno, you have been down thumbered, and i pray thatdanno, AGAIN, despite having numerous people giving VERY CLEAR and CONCISE criticism against his flouting of the artistic direction of the original game, has brought to us a (bad) sprite. danno, you have been down thumbered, and i pray thatdanno, AGAIN, despite having numerous people giving VERY CLEAR and CONCISE criticism against his flouting of the artistic direction of the original game, has brought to us a (bad) sprite. danno, you have been down thumbered, and i pray thatdanno, AGAIN, despite having numerous people giving VERY CLEAR and CONCISE criticism against his flouting of the artistic direction of the original game, has brought to us a (bad) sprite. danno, you have been down thumbered, and i pray that

**Comment by ExcessiveUseOfCobblestone** [comment]
How the mighty have fallen l-m-a-o

**Comment by RussellTalbott** [comment]
### looked cute inside my toilet might delete this soon

**Comment by Yoshmaster** [comment]
1/2 + 1/3 - 1/12 = 1/2 + 1/3 - 1/5 + 7/60 = 1/2 + 1/3 - 1/5 + 1/7 - 11/420 = 3/4?
What did danno mean by this

**Comment by mattroks101** [comment]
Man what's with everyone taking Eris's sprites. Eris has a very specific art style that fits very well with Eris and not very well with everything else. These look weird and out of place. They look much better on Eris walls than they do TG's.

**Comment by dannno** [comment]
because we're changing everything it just has to happen over time

**Comment by MMMiracles** [comment]
slowly making it look like GARBAGE

**Comment by Cyberboss** [comment]
Reading this PR gave me cancer

**Pull request closed without merging**
