### PR TITLE
Tablet icon improvements

### PR DESCRIPTION
**Pull request by Razharas**
:cl: Improves tablets design
imageadd: Brings the tablet icons into the holy light of having depth
/:cl:
**Before:** 
image
**After:**
image

### CODE REVIEW

**Comment by WJohn** [comment]
90's clunky PDA style + modern ipad? Please stick to a consistent aesthetic. The rest of the game generally points to 90's style.

**Comment by Iamgoofball** [comment]
The RD wouldn't be caught dead using Dapple software

**Comment by Iamgoofball** [comment]
*Fapple AUTOCORRECT

**Comment by Razharas** [comment]
@WJohn 
Killed the inner steve jobs with cancer, now its much blockier like in the past

**Comment by Supermichael777** [comment]
why didnt they just overhaul the pdas rather then add inventory bloat

**Comment by Razharas** [comment]
Good question but im trying to fix this one problem at a time

**Comment by Razharas** [comment]
Added the current tablet for reference, against it new ones have better chances

**Comment by WJohn** [comment]
This is an improvement over what we had, yes, but neither one is great. I guess I'll accept these over what we have, perhaps until these functions get merged into PDAs whose whole purpose is to be tablets.

**Comment by Cheridan** [comment]
yeah i'm with WJ these being modern style tablets really irritates me

**Comment by RemieRichards** [comment]
WJ's ok with this (till PDAs and Tablets get merged functionality wise)
merge time.

**Comment by nullbear** [comment]
http://i.imgur.com/tEA25DF.jpg

http://i.imgur.com/UljmcHG.gif

http://i.imgur.com/gJSARk8.gif

REEE it's a shame they're made in 48x48. Sorry.

**Comment by ma44** [comment]
noice

**Comment by calzilla1** [comment]
Damn dude that's good.  You should do more

**Pull request merged**
