### PR TITLE
Set default client FPS preference to 100

### PR DESCRIPTION
**Pull request by Mothblocks**
## About The Pull Request
Sets the default FPS from 40 to 100.

image

## Why It's Good For The Game
It's smooth

## Changelog

:cl:
qol: Default FPS (if you have it unset) is now 100 instead of 40.
/:cl:

### CODE REVIEW

**Comment by Mothblocks** [comment]
image

**Comment by Colovorat** [comment]
we do a little bit of miss clicking

**Comment by Mothblocks** [comment]
Changed to 100 since it rounds right

**Comment by Mothblocks** [comment]
No that was intentional

**Comment by SkeletalElite** [comment]
As a person with a 240hz monitor, what is the highest frame rate that I can use that doesn't have this issue?

**Comment by AnCopper** [comment]
I've been playing on 100 fps for years, it's good.

**Comment by Bawhoppen** [comment]
Gosh whose PC can handle 100 fps in this game, I can barely do 30

**Comment by AnCopper** [comment]
> Gosh whose PC can handle 100 fps in this game, I can barely do 30

People with a PC from later than 2009

**Comment by Bawhoppen** [comment]
I was exaggerating a bit but I do genuinely get some lag or freezing when I try to go 60 or over. I think a lot of people play this game cause they don't have very good PCs, so I think the default fps oughtta be something smooth enough to be pleasant but won't cause lag to first time players. 40 seemed good to me already, 60 would be alright I guess... but a 100 default is awfully high...

**Comment by Bawhoppen** [comment]
I was exaggerating a bit but I do genuinely get some lag or freezing when I try to go 60 or over. I think a lot of people play this game cause they don't have very good PCs, so I think the default fps oughtta be something smooth enough to be pleasant but won't cause lag to first time players. 40 seemed good to me already, 60 would be alright I guess... but a 100 default is awfully high...

**Comment by Bawhoppen** [comment]
I was exaggerating a bit but I do genuinely get some lag or freezing when I try to go 60 or over. I think a lot of people play this game cause they don't have very good PCs, so I think the default fps oughtta be something smooth enough to be pleasant but won't cause lag to first time players. 40 seemed good to me already, 60 would be alright I guess... but a 100 default is awfully high...

**Comment by optimumtact** [comment]
100 or 60?

**Comment by Serxule** [comment]
40 is arguably the best

**Comment by Mothblocks** [comment]
@optimumtact MSO says 60 is still incorrect because of that weird BYOND bug

**Comment by Mothblocks** [comment]
Unless you meant the body in which case I fixed it

**Pull request merged**
