### PR TITLE
Removes self linging

### PR DESCRIPTION
**Pull request by Incoming5643**
Fixes a goofy bug(?) where if you let yourself be killed by an NPC headslug you, the dead guy getting gibbed, gain control of the resulting ling. While said ling would still technically be "station aligned" people could  use this to "add" changeling status to any other kind of antag, which is a really dangerous/hilarious situation.

Kudos and apologies to those that managed to figure this out.

---

Also fixes a misrepresentation the traitor panel where any changeling would be classified as an antagonist because the traitor panel is a close minded racist.

### CODE REVIEW

**Comment by Iamgoofball** [comment]
sign me the FUCK up good shit go౦ԁ sHit thats ✔ some goodshit rightth ere right✔there ✔✔if i do ƽaү so my selｆ :100: i say so :100: thats what im talking about right there right there (chorus: ʳᶦᵍʰᵗ ᵗʰᵉʳᵉ) mMMMMᎷМ:100: Н

**Comment by bgobandit** [comment]
fun removal

**Comment by Supermichael777** [comment]
feature. if you want to become the template for a whole new abomination disguising itself in the flesh of others why should code stop you?
so long as it makes you automatically valid(if quacks like a duck) I don't see the problem.

**Comment by KorPhaeron** [comment]
So can you still create station aligned lings by pulling a ghost or is xenobio incapable of making changelings at all?

**Comment by Bawhoppen** [comment]
I think its just to stop self linging, but not slavelinging.

**Comment by RemieRichards** [comment]
@KorPhaeron sentience potions would still work, yeah.

**Comment by PKPenguin321** [comment]
ladies and gentlemen: the saddest PR to ever come across this repo

incoming, i implore you to leave this in, because it is the most featurey feature we've ever had

**Comment by Incoming5643** [comment]
you guys really want any xenobiologist that lives for 40 minutes to have ling powers?

**Comment by Iamgoofball** [comment]
so like

are we going to ignore that I can use this to become an antag that admins cant track or what

**Comment by PKPenguin321** [comment]
go ahead and fix the antag panel stuff, but this itself is just too cool to remove

**Comment by Core0verload** [comment]
It's a feature. 100% feature feature. Do not remove.

I know it because it was me who added this.

**Comment by Bawhoppen** [comment]
As fun as it is, the functionality of how this bug works is definitely not good. If there was a new slime potion that transfers your brain into a simple mob though, that could work.

**Comment by Cookiesndip** [comment]
100% cool feature. Fix the antag panel stuff, sure, but this is some of the wacky hijinks I miss about SS13.

**Comment by Iamgoofball** [comment]
okay

then are we going to ignore the fact this is a way to become an antag and unbalance the round

because if this is okay we should totally add ways to become all the other antag types in a round

**Comment by KorPhaeron** [comment]
It doesn't even really make sense that getting killed and eaten by the headslug makes you into a ling it should put a ghost in control if anything

**Comment by PKPenguin321** [comment]
reeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee

**Comment by Core0verload** [comment]
nooooooooooooo

**Pull request merged**
