### PR TITLE
Makes the supermatter sword have a "better" sprite.

### PR DESCRIPTION
**Pull request by CRITAWAKETS**
## About The Pull Request

This PR changes the sprite of the supermatter sword to be like our currents sword sprites, which means diagonal.

## Why It's Good For The Game

Some change is good once in a while. Also this uses less frames of animation because BYOND can rewind animations.

## Changelog
:cl:
imageadd: The supermatter sword is a lot more diagonal now.
/:cl:

also if you thing making it cracked would look better, i felt it kinda looked bad for a sword when cracked.

### CODE REVIEW

**Comment by Fikou** [comment]
this should look like the new supermatter sprites

**Comment by CRITAWAKETS** [comment]
> this should look like the new supermatter sprites

tbh the reason it doesnt was because i made this before the new SM sprites and only PRed now

**Comment by YakumoChen** [comment]
This kind of breaks the logic of the sword's descriptive text. When it spawns it's "perfectly balanced in a single spot" until it's interacted with, which means stock upright.

**Comment by maxymax13** [comment]
nice gradient

**Comment by Learner10** [comment]
> 
> 
> this should look like the new supermatter sprites

So basically a shitty rock?

**Pull request closed without merging**
