### PR TITLE
Revert "remove human requirement for invisible_wall"

### PR DESCRIPTION
**Pull request by optimumtact**
Reverts tgstation/tgstation#83751

The person who added this has been abusing the shit out of it relentlessly, so they fail the vibe check.

### CODE REVIEW

**Comment by necromanceranne** [comment]
Working example of if you would like to see something added to the game, the worst thing for you to then do is to make use of it to be an obnoxious arsehole.

**Comment by lizelive** [comment]
I always open another mime slot before borg and have received generally positive feedback. Today I served an ai that decided to lock me down for not being able to talk in binary and then admin force broke vow, so I role played being emotionally destroyed by having my vow force broken while following laws as normal. A pr to make it so mime borg can break it's vow would be a better then reverting this. That way people can just law 2 break your vow.

**Comment by GPeckman** [comment]
I'm a little curious, how do you even abuse a feature like this without breaking your silicon laws?

**Comment by Dawnseer** [comment]
Unless he didn't listen to the ai saying knock it off, og no human law 2'd him to stop under asimov, then it's very easy to abuse. Especially as nobody expects invisible walls from borgs.

**Comment by lizelive** [comment]
nope. never broke my laws or refused order. always respected law 2 to fuck off / dont make walls. someone is prob salty i opened a door and put a wall in it. but there are a million ways to avoid that problem.

that being said, borgs should be able to break oath.

**Comment by GPeckman** [comment]
> Unless he didn't listen to the ai saying knock it off, og no human law 2'd him to stop under asimov, then it's very easy to abuse. Especially as nobody expects invisible walls from borgs.

Abuse _how_? I don't see a borg making invisible walls as abuse in and of itself, because if it was the original PR would never have been merged to begin with.

**Comment by davethwave** [comment]
I believe it's the case of a person only becoming mime to be borged with the wall ability. Thus wasting the role just so the guy can have a ability as borg instead of just trying to be a borg or an assistant if they wanted to be borged round start anyways.

**Comment by GPeckman** [comment]
Even if that counts as "wasting" the role (being a mimeborg sounds like a perfectly reasonable roleplay idea to me), shouldn't that be solved by the admins?

**Comment by necromanceranne** [comment]
It can be, but coders are free to handle it as they see fit if they suspect it was only added to then be abused.

**Comment by GPeckman** [comment]
That's fair. But I think the PR should at least explain how it's being abused, shouldn't it?

**Comment by Jacquerel** [comment]
I'll be honest I think it's silly for cyborgs to be able to do this anyway

**Pull request merged**
