### PR TITLE
Revenant's defile removes salt piles

### LINKED ISSUE #33291: Revenant's defile does not remove salt
This has happened every round I've played revenant. Wiki says that defile should remove salt piles but it doesn't. This means that anywhere with salt is permanently impassable to revenants. Even worse, if someone makes a cloud of salt on top of you you are permanently trapped without an admin helping you.

### PR DESCRIPTION
**Pull request by Garen7**
Fixes #33291

[Changelogs]: # (Your PR should contain a detailed changelog of notable changes, titled and categorized appropriately. This includes, new features, sprites, sounds, balance changes, admin tools, map edits, removals, big refactors, config changes, hosting changes and important fixes. An example changelog has been provided below for you to edit. If you need additional help, read https://github.com/tgstation/tgstation/wiki/Changelogs)

:cl: Revenant Defile ability
fix: Revenant's Defile now removes salt piles
/:cl:

[why]: # (Please add a short description [two lines down] of why you think these changes would benefit the game. If you can't justify it in words, it might not be worth adding.)

In order to keep consistency with what is on the [wiki](https://tgstation13.org/wiki/Revenant) the revenant's defile now removes salt piles as well.

### CODE REVIEW

**Review by ShizCalev — APPROVED** [review]

**Comment by davethwave** [comment]
Finally!

**Comment by scrubs2009** [comment]
Wowie! My issue report actually contributed to the game!

**Comment by Supermichael777** [comment]
Could you remove the window-smash, it really has been the bone to pick with griffghost.

**Comment by AverageJoe82** [comment]
I could easily but that seems to be a part of the original game design so I'm pretty sure I don't have permission to change that @Supermichael777

**Comment by scrubs2009** [comment]
Defile is kind of a Revenant's thing. Its a revenant's primary way of killing someone. A person can survive >20 lightbulb shocks without going into crit and I've never seen blight crit either.

**Comment by AdamElTablawy** [comment]
i've...never seen defile crit.

**Comment by AverageJoe82** [comment]
You can defile windows to siphon air and some windows have electrified grills which can insta kill someone who gets siphoned into it. I just killed about four people this way on Sybil.

**Comment by Kerbin-Fiber** [comment]
Ick Ock

**Comment by AdamElTablawy** [comment]
A malevolent spirit situationally using the environment to kill people is cool and all but it’s hardly the strongest ability the revenant has, so i’m still not seeing what that dude is on about

**Pull request merged**
