### PR TITLE
Fixes away mission loot station balance by removing loot drops from syndicate simple mobs.

### PR DESCRIPTION
**Pull request by Shadowlight213**
Probably controversial.
I've seen many rounds get fucked by people going into an away mission and coming out with energy shields, dual eswords, and syndie hardsuits.
With simple mobs being shitty like they are, once you kill one of them, the rest are easy to down and loot.

### CODE REVIEW

**Comment by MMMiracles** [comment]
what if instead of removing the loot from the mobs, we remove the missions that go overboard with the mobs that end up giving the entire crew the weapons.

**Comment by Zilenan91** [comment]
Yeah the problem lies in the away missions themselves, not with the mobs in them.

**Comment by Shadowlight213** [comment]
That would make too much sense.

**Comment by Zilenan91** [comment]
Not even trying to mask my hatred of this mission here, but Emitter Maze. Something really needs to be done about that mission, it's just so bad. You can cheese around the whole thing if you have tools and a wrench, and if you get to the end you can kill all of the mobs from exposure then get out with fucktons of explosive implants, guns, and no damage taken and then unbalance the whole round.

**Comment by Buggy123** [comment]
:-1: a lot of the away missions have next-to-no loot aside from what mobs drop, and would also be next to impossible to do without weapons from mobs.

**Comment by Firecage** [comment]
Fuck no fuck no fuck no :-1::-1::-1::-1::-1::-1:

**Comment by Shadowlight213** [comment]
You do know that you aren't supposed to be able to do the missions not pre-equipped, right? But whatever.

**Comment by Shadowlight213** [comment]
Kor thinks this is a good idea and wants me to reopen.

**Comment by Wyzack** [comment]
-1 for no more easy tactical turtlenecks, literally best loot

**Comment by Zilenan91** [comment]
Like I've said before the problem is the away missions themselves not the mobs

**Comment by PKPenguin321** [comment]
Very hesitant :-1:
Add more loot to the missions themselves and you'll get a thumbs up from me

**Comment by WJohn** [comment]
Yeah I blame the ultra shitty away missions we have that dump tons of free loot, like spacebattle.

**Comment by Firecage** [comment]
spacebattle is a fun awaymission though. Unlike the nearly pure exploration ones.

**Comment by borntohonk** [comment]
:+1: too many people rush into gateway mission and comes guns blazing immeadetly going validhunting with their new loot.

both from BSA away mission and the emitter maze away mission this happens almost everytime.

**Comment by Cheridan** [comment]
>:-1: a lot of the away missions have next-to-no loot aside from what mobs drop, and would also be next to impossible to do without weapons from mobs.

This. If you're trying to run through Wild West you're going to have a lot of difficulty without those additional drops. This doesn't really fix "away mission balance" like the title suggests. It probably messes it up pretty good. It fixes the station being imbalanced by the results of away missions, which is an away mission problem. This change is fine but it should be done alongside a balance pass of the mission maps.

**Comment by Shadowlight213** [comment]
@wjohn the main source of loot from space battle is the syndie mobs.
I guess an alternate would be to replace the hardsuits in the space syndie mobs with regular space suits, remove the eshields and esword from the melee mobs and replace with combat knives or something. People getting tons of nuke op gear is pretty insane. 
Could look at doing a balance pass as well. The main thing is here that people seem to assume you're supposed to be able to do the missions solely with the weapons you find, without needing to arm up. Alternately people seem to think that the gateway should be right next to the entrance. It shouldn't. The idea behind the missions is that you are supposed to be prepared beforehand and to expect anything on the other side. They aren't something you are supposed to just do on a whim and be able to pop out with no consequences if you don't like it. If you want to leave, then get an autocloner built and scan yourself before you enter.

**Comment by TheWiznard** [comment]
what if you could make a trigger pin that acted like an exile implant that made all guns equipped with it unable to come through the gateway?

**Comment by MMMiracles** [comment]
@TheWiznard Better off just making them the restricted version so people can still salvage them if they have the pins/a plasma cutter.

I'm gonna go look into making these missions less of a gun-fest because this PR is kind of a 'meh' way to fix the problem.

**Comment by Zilenan91** [comment]
The hole we've dug ourselves into here is to either make all the weapons the syndi mobs drop are either syndicate pinned, or we remove the missions entirely. It still won't stop people from getting Op hardsuits and all the other gear though.

I honestly don't see a way how we'd fix Emitter Maze, there's a ton of esword mobs and a room full of loot that has no other purpose than being a room full of loot. The best course here would be to remove it I think.

**Comment by Cheridan** [comment]
>This. If you're trying to run through Wild West you're going to have a lot of difficulty without those additional drops. 

actual i take it back, the point of away missions is to kill people horribly and people coming back with crazy arsenals to fuck up everyone is wrecking games

**Pull request merged**
