### PR TITLE
Restores the Nar-Sie sound to "I'm here"

### LINKED ISSUE #12002: Nar-Sie's epic new soundtrack is a bit loud
it frightens

### PR DESCRIPTION
**Pull request by ghost**
The feedback has been overwhelmingly in support of restoring the old sound, so here it is.
Fixes #12002

### CODE REVIEW

**Comment by PKPenguin321** [comment]
i'll miss "*unzips reality*"

**Comment by AnonymousNow** [comment]
Oh well, I guess my sound'll have to wait its turn. :<

**Comment by Aloraydrel** [comment]
:^) mush mush

**Comment by WJohn** [comment]
Thank you, many ears will be saved by this.

**Comment by Dorsisdwarf** [comment]
Fixes #12002

**Comment by Miauw62** [comment]
imo the nar-sie sound should be replaced by the microwave ding.

**Pull request merged**
