### PR TITLE
Animated Spellbooks

### PR DESCRIPTION
**Pull request by Nabski89**
[Changelogs]: # (Your PR should contain a detailed changelog of notable changes, titled and categorized appropriately. This includes, new features, sprites, sounds, balance changes, admin tools, map edits, removals, big refactors, config changes, hosting changes and important fixes. An example changelog has been provided below for you to edit. If you need additional help, read https://github.com/tgstation/tgstation/wiki/Changelogs)

:cl: Spell granting books are now animated.
imageadd: Spell granting books are now animated.

/:cl:

[why]: # I thought it would be fun for the magical books to be slightly more magical.

https://imgur.com/oeAYlST

Hmmm it looks like my commit isn't doing anything. Ideally I need to just be updating library.dmi.

### CODE REVIEW

**Comment by vuonojenmustaturska** [comment]
i think you goofed something

**Comment by Nabski89** [comment]
Yeah I noticed.

**Comment by ShadowDeath6** [comment]
is it possible to increase the number of frames / decrease the animation speed for knock and blind? they look kind of odd when they go that quickly

**Comment by Nabski89** [comment]
There was a semi-standard number of frames that most animations used (4). As far as I know there is no way to slow the animations down. See version 2 below.

https://imgur.com/N1eKZZl

**Comment by ChangelingRain** [comment]
you can edit the time values for each frame, which edits how fast/how often they happen.

**Comment by Nabski89** [comment]
Ah, I see it's a right click option. Any feed back on the other ones while I'm editing some more?

**Comment by 81Denton** [comment]
Those look great!

**Comment by Nabski89** [comment]
I am bad at this.

**Pull request closed without merging**
