### PR TITLE
Fixes two posibrain names

### PR DESCRIPTION
**Pull request by ChangelingRain**

### CODE REVIEW

**Comment by xxalpha** [comment]
Player references? We don't allow those here.

**Comment by duncathan** [comment]
References? These are arbitrarily arranged letters.

**Comment by Durkel** [comment]
Nice memes.

**Comment by PKPenguin321** [comment]
>tagging your own meme pr as a fix

Bannu

**Comment by Cheridan** [comment]
OOC says that Coders don't play.
Therefore, these are not player references.

Checkmate, athiests.

**Comment by xxalpha** [comment]
Can't argue with that logic.

**Pull request merged**
