### PR TITLE
Nukie Rework Part 2: Nuclear Operative starting gear rework

### PR DESCRIPTION
**Pull request by Fikou**
## About The Pull Request

PR Dedicated to:
image
Alan Edaggers

Replaces the nuke op Makarov with the Ansem, a clandestine pistol firing 10mm rounds which do more damage. Ammo costs more.
Replaces the nuke op survival knife with the energy dagger, as well as giving it a soft light, light armor penetration and a light wound bonus.
Replaces the diamond drill in their closet with an entrenching tool, which swaps between crowbar, pickaxe and shovel modes.
Gives the nuke op survival box the syndie box design, as well as a crowbar, screwdriver and mini welder.
Removes the nuke op leader's Krav Maga gloves.
Updates the esword and edagger sprites with ones i had lying around from 2019, they are more consistent.
Moves pistol sprites a bit up to center them.
image

## Why It's Good For The Game

Nukies having some essential tools they start with is nice, especially if they took any sort of borg that needs welding.
The krav maga gloves just got overridden by MODsuits, and they need a rethink as a whole if they even fit in the nukie arsenal.
Sprites are more consistent = good
The diamond drill being a bulky ass thing made it weird to use, a smaller entrenching tool seems better and also cooler for them.
The survival knife really doesn't cut it for nukies, 15 damage with no armor penetration is gonna be very hard to use. The energy dagger's slightly higher damage, armor penetration and respectable throw damage make it a more viable option in emergency situations where you're out of ammo.
The Ansem lets us balance nukie's starting pistol separately from the Makarov, and a more darkish weapon fits them well.

## Changelog

:cl: Fikou, NecromancerAnne, Wallem
qol: nuke ops emergency box now contains a crowbar, screwdriver and mini welder
del: nuke ops leader krav maga is removed
balance: nuke op survival knife has been replaced with an energy dagger
balance: energy daggers have light armor penetration and wound bonus
qol: energy daggers now emit a soft red light
balance: nuke op makarov has been replaced by the ansem, a 10mm clandestine pistol.
add: nuke op diamond drill has been replaced with an entrenching tool, a more compact wrench/pickaxe/shovel
/:cl:

### CODE REVIEW

**Comment by SinfulBliss** [comment]
Will there still be free ammo magazines in the lockers for the Ansem like there were for the makarov?

**Comment by Fikou** [comment]
> Will there still be free ammo magazines in the lockers for the Ansem like there were for the makarov?

i forgot about those thank you

**Review by Imaginos16 — APPROVED** [review]
Yea

**Comment by necromanceranne** [comment]
This also patches an issue with the Starfury crew having 10mm mags but nothing to use them with.

Maybe. I'll doublecheck that when I get home. I did notice they had the mags though

**Comment by Wallemations** [comment]
How significant is the esword & edagger sprite changes? I'm on mobile so I'm crippled to not be able to see the icondiffbot.

**Comment by Fikou** [comment]
> How significant is the esword & edagger sprite changes? I'm on mobile so I'm crippled to not be able to see the icondiffbot.

the edagger is recolored because previously it was a dark red and it looked like a cult thing
the esword handle is consistent with the extended eswords
deswords now have a part that attach it to the hand of the human mob

**Pull request merged**
