### PR TITLE
removes the FUCK outta Romerol holy shit i hope it gets removed forever

### PR DESCRIPTION
**Pull request by Iamgoofball**
see title

### CODE REVIEW

**Comment by ChangelingRain** [comment]
This was previously closed #29191

**Comment by BreadBurner** [comment]
I was the one who spread romerol that round you weeb cunt
Thanks for the all access

**Comment by Iamgoofball** [comment]
you're welcome but romerol is fucking garbage

**Comment by BreadBurner** [comment]
I mean it does require you to meet other tators and for they to spare tc which is rather unusual.
Maybe a good nerf to romerol would be taking out the stun inmunity from zombies.

**Comment by Iamgoofball** [comment]
you missed the point

the problem is not balance

the problem is that it's not fun for anyone

its not fun for the zombies

its not fun for the humans

**Comment by FantasticFwoosh** [comment]
I will say what gives you leverage to make such a vague assumption like that?

Objectively i can sympathise with trying to kill zombies, as much as being forced into a zombie role when otherwise you were minding your own business. Im not saying your wrong or right on the issue but present a working example of your hypothesis.

**Comment by YakumoChen** [comment]
it's against the rules now to have it removed

**Pull request closed without merging**
