### PR TITLE
Undoes /vg/ sabotage of PDA lights

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
Before:
blind

After:
light

### CODE REVIEW

**Comment by Poojawa** [comment]
It's a dinky little pen light, supposed to be more spoopy if that's the only light source on you at all.

**Comment by KorPhaeron** [comment]
Seeing only 1/7 of your normal view range is still pretty spooky, but this way the player isn't suffering physically from straining their eyes

**Comment by uraniummeltdown** [comment]
I think the nerf is good, if you want to really see in the dark just pick up a flashlight

**Comment by InsaneHyena** [comment]
This was a positive addition at the game, let it stay.

**Comment by Cheridan** [comment]
I'd like something in between "can't see shit captain" and this change which seems too bright.

**Comment by ShadowDeath6** [comment]
The before picture doesn't even look like you have lights on, it's like the basic human night vision

**Comment by anconfuzedrock** [comment]
honey nut cheridan has the right idea

**Comment by MrPerson** [comment]
\>play horror game
\>increase the gamma up to max

Does anyone not do this?

**Comment by KorPhaeron** [comment]
Yeah, keeping it half bright just punishes players for not fucking with their monitor. The actual value that matters for balance is that it only extends half a tile in every direction

**Comment by ChangelingRain** [comment]
Try 0.7, maybe?
It kind of doesn't matter as much to me, because the only thing that I have trouble seeing is range 1.4 power 0.1 lights, of which there are not many.

**Comment by KorPhaeron** [comment]
Even with power 1 having a PDA light is the equivalent of missing your eyeballs right now, don't know why it has to be even harder to see

**Comment by xxalpha** [comment]
what the fuck, grab a flashlight they're super common

more qol memes :-1:

**Comment by Steelpoint** [comment]
This is a good change. The current PDA light forces you to strain your eyes to figure out what's on screen and it may as well be removed if its kept as is.

Considering modern day phones have inbuilt lights that are pretty much as good as a flashlight, I fail to see why a PDA five hundred years in the future can't even do half as good.

**Comment by RemieRichards** [comment]
I dont see how it requires strain, it's easy to see the vent and scrubber, however I do agree it's just too dark anyway.

**Comment by Kraseo** [comment]
why use pdas when you can use pagers

**Comment by KorPhaeron** [comment]
@xxalpha 

How is reverting an undeclared balance change snuck into a 200 file refactor back to the state we have had for 7 years "qol memes"

**Comment by KorPhaeron** [comment]
Why are people seriously acting like seeing only one 1 tile is not a massive debuff and having a circlejerk about how hardcore they are for looting a flashlight roundstart I am genuinely confused

**Comment by Kromgar** [comment]
Gotta powergame @KorPhaeron get it right

**Comment by Xhuis** [comment]
This is a step in the right direction but juuust too bright for my tastes. Good change either way

**Comment by Intigracy** [comment]
https://github.com/tgstation/tgstation/pull/24846/files#diff-cd3191e0e98ac1c7cd49fdd64ff2cf73R31

lower this to 2 or 1

**Comment by Xhuis** [comment]
You know, this entire issue could be solved if you just made everyone blind at round start. They can't complain that it's too dark if they can't see anything.

**Comment by Xhuis** [comment]
Flashlight eyes work too. No excuse that it's too dark when they forcibly light up the entire planet.

**Comment by Iatots** [comment]
People playing to win will always up their gamma obscenely, but it might prove useful for future light development to point at one of those brightness test images and say "this is where you shouldn't be able to see anymore".

Me for example:
at gamma 1.0 I cannot see anything but steelpoints outline and the white part of the icon.
at gamma 1.1 I can sorta see the tile outline and the icon.
at gamma 1.2 I can definitely see the character and tile, with the outline of the scrubber and vent.
at gamma 1.3 I can see the vent and scrubber decently.
at gamma 1.4 I can see everything clear short of the wall outline.

**Comment by ChangelingRain** [comment]
My monitor's default gamma lets me see everything including the wall's outline, it's just right in the middle of the slider.

**Comment by Iatots** [comment]
What are your luminosity and contrast? Mine are 0 and 50, respectively. "Middle of the slider" for me is 2.5, and at that point I see the whole hallway, much like you seem to describe.

**Pull request merged**
