### PR TITLE
Removes Engorged Chemical Glands

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
Changelings recently had their base chemical regen doubled and storage increased to 75 (the old effect of chem glands), being able to still buy the skill and end up with quadruple chem production and 100 units of storage is overkill. Chemical consumption is more or less not a concern (which led to the fleshmend spam issues).

Or to rephrase it, lings get this power for free already, they don't need to be able to purchase it anymore.

### CODE REVIEW

**Comment by Anonus** [comment]
I'm obligated to [KEEP LINKING MY LING IDEA](https://tgstation13.org/phpBB/viewtopic.php?f=9&t=4158) so that it eventually gets coded.
This probably isn't a solution because lings have armblade, combat skills, and armor along with stealth abilities, which is a terrible combination designwise.

**Comment by Core0verload** [comment]
:-1:

**Comment by Dorsisdwarf** [comment]
:-1: nerf it harder/make it expensiver

**Comment by xxalpha** [comment]
:-1:

**Comment by chimerasable** [comment]
Good observation about the new change and ECG but I am not sure it effects lings too much in the grand scheme. It just allows for one or two more uses of an ability and if a ling is really caught that won't matter anyways. I think ling antagging is already pretty difficult so please consider nerfs carefully.

**Comment by Nanotransistor** [comment]
The 100 chemical change was a good change. It made lings more threatening again. And still they get rekt most of the times i see them though.

So far, the only lings that manage to murderbone are those that get a hand on a taser, not so much due to their abilities.

**Comment by KorPhaeron** [comment]
Doesn't seem very popular then

**Comment by KorPhaeron** [comment]
This is still very relevant after all.

**Comment by Razharas** [comment]
There were a few ling nerfs recenty i dont think we need any more

**Comment by KorPhaeron** [comment]
Since ling has been disabled for months now, can we reconsider this? People allegedly miss ling, but being able to shrug off the armory is silly.

**Comment by Dorsisdwarf** [comment]
Make a new PR that works first

**Comment by Jordie0608** [comment]
Being disabled for months isn't a good basis for balance

**Pull request closed without merging**
