### PR TITLE
Adds sidings floor decorations

### PR DESCRIPTION
**Pull request by Mickyan**
This was a frequent request from mappers ever since trimlines were added, they work similarly to trimlines but they have different use cases and don't necessarily work together, so I am calling them sidings to avoid confusion. 
Whereas trimlines are floor paint for plating, these are solid borders to be used either alongside walls, smoothing transitions between floor types or mark/split an area without having to use walls, and work with any floor type.

These are ALL greyscaled, so they're trivial to ~~bikeshed~~ customize and make new types for your mapping needs
-Colored (plastic/vinyl strips, standard departmental colors)
-Plating(metal, grey/white/dark)
-Wood(it's wood)

I've added them to meta's bar as a small example
## Changelog
:cl:
imageadd: Added new siding floor decals for mapping
/:cl:

Screenshot_5
Screenshot_6
Screenshot_7

### CODE REVIEW

**Comment by Barhandar** [comment]
Turn all maps into kilo

**Comment by Paxilmaniac** [comment]
Are there siding corners for the wood sidings, etc?

**Comment by Mickyan** [comment]
yes, corners and ends

**Review by Twaticus — APPROVED** [review]
very very cool

**Pull request merged**
