### PR TITLE
jumping into abandoned crates no longers causes them to go boom

### LINKED ISSUE #46239: Ctrl+shift+clicking to jump inside an abandoned crate using the skittish perk causes it to explode
Issue reported from  Round ID: 117361 (/tg/Station Bagil [ENGLISH] [US-WEST] [100% FREE LAG])

Reporting client version: 512.1471

Maybe this is intentional? But I would've thought the lock would've stopped it first?

### PR DESCRIPTION
**Pull request by ghost**
fixes #46239

### CODE REVIEW

**Comment by ATH1909** [comment]
What if the crate's already been unlocked, though?

**Comment by Qustinnus** [comment]
fixed that now

**Comment by OverlyGeneric** [comment]
rip cargo suicide bombers

**Comment by ATH1909** [comment]
> rip cargonian suicide bombers

They can still just whack the crate once with a wrench or the like to trigger it, no?

**Pull request merged**
