### PR TITLE
Fixes? Catsploision? [Maybe?]

### PR DESCRIPTION
**Pull request by Incoming5643**
Shuffles a line that could have potentially been delayed from running by rapid cat creation. The delay of reading said line might have allowed "deploy_the_cats" to fire more than once. Maybe.

:fried_shrimp:

### CODE REVIEW

**Comment by duncathan** [comment]
infinitely better than the alternative

**Comment by Shapsy** [comment]
Just as long as the cats are gone

**Comment by Shadowlight213** [comment]
>It takes the nuclear option being presented to get thus bug fixed

As shaps said, as long as the cats are gone I'm fine.

**Comment by Incoming5643** [comment]
It's far harder to fix a bug that some people find hilarious.

Also it's pretty much impossible to replicate locally, so that dissuading too

**Comment by lzimann** [comment]
nuke it

**Comment by bgobandit** [comment]
all of you are cat murderers

:cat:

**Comment by Jordie0608** [comment]
You could get a copy of the .sav file from the servers if you wanted to test locally.

**Comment by KorPhaeron** [comment]
May as well try

**Pull request merged**
