### PR TITLE
Removes virgin snailcrawl component and replaces it with chad snailcrawl element.

### PR DESCRIPTION
**Pull request by nemvar**
## About The Pull Request

See title. Also misc snail changes.

## Why It's Good For The Game

Elements are the new kool kids thing. Components go home.

## Changelog
:cl:
code: Snailcrawl element has been added.
/:cl:

### CODE REVIEW

**Comment by nemvar** [comment]
Oh lord, where have I fucked up...

**Comment by PKPenguin321** [comment]
what the frick, but i JUST learned components, gosh dang it

**Comment by Whoneedspacee** [comment]
> what the frick, but i JUST learned components, gosh dang it

me right now

**Comment by actioninja** [comment]
elements aren't a replacement for components they're a companion.
components store state per instance, elements do not and simply attach and provide functionality.
At least I think they do? I'm pretty new to this as well.

**Comment by ninjanomnom** [comment]
Actioninja is correct

**Pull request merged**
