### PR TITLE
Resprites deskclutter

### PR DESCRIPTION
**Pull request by pudl**
Old on left, new on right.
Looks less like the OpenSS13 sprite that it is, maybe people will use it now.

### CODE REVIEW

**Comment by Nienhaus** [comment]
:+1:

**Comment by Cheridan** [comment]
I think detective's deskclutter item was, over time, replaced by... actual desk clutter in the form of papers, folders, evidence bags, etc.

**Comment by pudl** [comment]
@Cheridan This item wasn't made for the detective, it predates detective. Still, that is kind of funny.

**Comment by GunHog** [comment]
I have never even seen this, before.

**Comment by pudl** [comment]
@GunHog It's used on Bay and Goon, and Efficiency Station 1 used it as trash in maintenance.

**Comment by WJohn** [comment]
Desk clutter is a completely useless item. We can simulate it by literally putting a bunch of items on his desk, and (making good use of pixel shifting) and that'll simulate plenty of clutter you can actually pick up and use.

**Comment by Iamgoofball** [comment]
attackhand()
new pick(typesof(/obj/item))(src.loc)

:^)

**Comment by Miauw62** [comment]
>prefixing things with src
>spawning abstract objects

**Comment by Iamgoofball** [comment]
ill prefix ur mom w/ src miauw!!!

**Comment by Cheridan** [comment]
well it is an improvement at any rate so away we go

**Pull request merged**
