### PR TITLE
Adds a new lavaland ruin, the ancient battle site.

### PR DESCRIPTION
**Pull request by ArcaneMusic**
## About The Pull Request
Adds a new ruin to lavaland, the Battle Site ruin. This ruin features the site of an old battle, with the only inhabitants now being goliaths and mushrooms. The cycle continues, one would imagine.

No new uniques or rewards or anything, as this just spawns in standard items found on or around lavaland already.

image

## Why It's Good For The Game

Full disclosure I just got bored this afternoon and decided to do a little mini project and bump up the lavaland ruin diversity a little bit. 
I'm of the opinion that we could always use new ruins on lavaland so that there's new things to explore and so that we can introduce some new elements to the map generation.

## Changelog
:cl:
add: A new ruin has appeared on lavaland, featuring the site of an ancient battle.
/:cl:

### CODE REVIEW

**Comment by githubuser4141** [comment]
Uh, wouldn't the humanoids be desiccated skeletons by now? It doesn't make sense that all the skin is still intact given lavaland's violent ashstorms which can kill a humanoid in one pass and husk them in another.

**Comment by mc-oofert** [comment]
> Uh, wouldn't the humanoids be desiccated skeletons by now? It doesn't make sense that all the skin is still intact given lavaland's violent ashstorms which can kill a humanoid in one pass and husk them in another.

those are skeleton spawners

**Comment by Pumpkinoe** [comment]
> Uh, wouldn't the humanoids be desiccated skeletons by now? It doesn't make sense that all the skin is still intact given lavaland's violent ashstorms which can kill a humanoid in one pass and husk them in another.

the dead body spawner sprite is generic for things outside of on-station jobs

**Comment by Pumpkinoe** [comment]
(that's why it looks like Peter Griffin)

**Comment by timothymtorres** [comment]
Looks very thematic.  Not every ruin should be filled with powergamer loot.

**Comment by Maurukas** [comment]
> (that's why it looks like Peter Griffin)

It is also a Homestuck reference.

**Review by Maurukas — APPROVED** [review]
Nice ruin.

**Pull request merged**
