### PR TITLE
makes centcom festive for 4th of july (testmerge only obv)

### PR DESCRIPTION
**Pull request by 81Denton**
:cl: USA
add: USA
/:cl:

capture

### CODE REVIEW

**Comment by ishitbyabullet** [comment]
Make it happen every 4th of july.

**Comment by optimumtact** [comment]
We possibly could do that, but then where do we draw the line? We'd have to add an EU flag etc etc

**Comment by ishitbyabullet** [comment]
@optimumtact we add that too

custom centcom docks are the future

**Comment by 81Denton** [comment]
I'm a little upset that I didn't replace this with a UK flag and tea cups right before it got testmerged

**Comment by Harcourt1** [comment]
Re-open this and make it every fourth. Thing is, the only holidays that count are american holidays. Every country in the world belongs to America.

**Comment by 81Denton** [comment]
Keeping this open will eventually cause merge conflicts when someone changes the area, but I will do another thing like this next year (swear on cheeseburger)

**Pull request closed without merging**
