### PR TITLE
Makes radiation related pluouxium only generate in cold conditions

### PR DESCRIPTION
**Pull request by LemonInTheDark**
## About The Pull Request

Pluoxium can currently be created in mico amounts on a lot of tiles, which creates a lot of unneeded activeturfs, and wastes processing time.
Let's only make pluox in cold mixes then, and since it's not gonna mitigate high power runaways quite as hard now, let's make it a net negative on waste gas output for the sm.

## Why It's Good For The Game

Radiation will be nicer to atmospherics, and pluox will more complex, ish.

## Changelog
:cl:
balance: Radiation related pluoxium will now only generate in gasmixes under 200K, remember to keep that sm cold
/:cl:

### CODE REVIEW

**Comment by Sethnov** [comment]
what about making pluxoium at the turbine though?

**Comment by LemonInTheDark** [comment]
> 
> 
> what about making pluxoium at the turbine though? could there be also a high heat requirement?
> would it be possible to make it a between thing like below 200 kelvin or above 2000 or 1000 kelvin?
> alot of atmos techs use the turbine for tritium and pluxoium production.

This didn't actually occur to me. There's a reaction for making plux outside of radiation, but it's also constricted to cold temperatures. I might raise the requirements to keep the behavior you're describing

**Comment by Sethnov** [comment]
thanks

**Comment by read-0nly** [comment]
Aha! It's your fault. This makes sense but I hate it. Lavaland pluox is a bit more complicated now.

**Comment by LemonInTheDark** [comment]
Hate to break it to you, but everything's my fault

**Comment by read-0nly** [comment]
Maybe but so far this is the only one I resent you for lol

**Pull request merged**
