### PR TITLE
[I GUESS THIS MIGHT BE TESTMERGED? I DUNNO] return of the ling action buttons

### LINKED ISSUE #41899: ling monkey form broke
1. Be ling 2. Buy lesser form 3. Activate lesser form 4. Activate human form 5. Be stuck as a monkey because goon genetics broke something. Bandaid fix in game is to DNA sting someone and human form into the fresh DNA.

### PR DESCRIPTION
**Pull request by ghost**
:cl: 0d0be32, PKPenguin321, Armhulen, epochayur
refactor: Changeling powers are now action buttons rather than verbs.
imageadd: Thanks to epochayur for creating and compiling sprites for every single changeling action button!
imageadd: Thanks to Armhulen for the changeling button background sprite!
/:cl:

original pr https://github.com/tgstation/tgstation/pull/35394

the two main bugs i saw are fixed. reviving works, monkeyform/humanform works

fixes #41899

### CODE REVIEW

**Comment by epochayur** [comment]
:D

**Comment by 0d0be32b607ee4ecbc2358f3dd4a27de** [comment]
moral of the story is that datums aren't types and can't be used as types

**Comment by Razharas** [comment]
Finally
I made my first pr to make ling stings into buttons for ease of use but then people corrupted my beautiful code by making all ling actions a children on sting_action since they cant code for shit and only copy existing code inappropriately

**Comment by 0d0be32b607ee4ecbc2358f3dd4a27de** [comment]
this should get a testmerge

**Comment by 0d0be32b607ee4ecbc2358f3dd4a27de** [comment]
also this fixes #41899

**Comment by 1fbff5f83b23d39d38b1dfcb4cac8d9b** [comment]
Nice name

**Comment by 0d0be32b607ee4ecbc2358f3dd4a27de** [comment]
@1fbff5f83b23d39d38b1dfcb4cac8d9b it's the SHA-something of `penis`.

**Comment by 0d0be32b607ee4ecbc2358f3dd4a27de** [comment]
@tgstation/maintainers

plez review this

**Comment by 0d0be32b607ee4ecbc2358f3dd4a27de** [comment]
wait why did it autoreview @ShizCalev

**Comment by 0d0be32b607ee4ecbc2358f3dd4a27de** [comment]
eat dingleberries, @tgstation-server

bad bot

**Comment by optimumtact** [comment]
@0d0be32b607ee4ecbc2358f3dd4a27de please keep an eye on the issue tracker for the next few days

**Comment by PKPenguin321** [comment]
dude holy shit, i only just now saw this but thank you so much for finishing this up! this was one of my bigger projects and i was so upset that i wasn't able to finish it to get it merged. this is great, thank you for real

**Comment by PKPenguin321** [comment]
what was it if you dont mind explaining
I warn you i am a bit very stupid

**Comment by 0d0be32b607ee4ecbc2358f3dd4a27de** [comment]
@PKPenguin321 you were treating objects as types.

you can't do `new instance_of_an_object`, you can only do `new type_of_object`

**Pull request merged**
