### PR TITLE
Pubbystation: Firelocks, shutters, fixes

### LINKED ISSUE #35957: pubby has no fire alarms in rd or library
if the burglar alarm goes off you just have red flash until the end of time

### PR DESCRIPTION
**Pull request by 81Denton**
:cl: Denton
fix: Burglar alarms in the Pubbystation library and RD office can now be disabled properly.
fix: Fixed Pubbystation's RD office shutters.
add: Added missing engineering and kitchen lockdown shutters on Pubbystation.
add: Pubbystation: Added privacy shutters to the CMO and RD offices. Added space shutters to the HoS office. Replaced the RD office's directional windows with fulltile ones.
add: Added a second blast door to the Pubbystation gulag shuttle lockdown.
tweak: Due to pressure from the space OSHA, Pubbystation has installed missing fire alarms and firelocks.
tweak: Split the Pubbystation library into two areas with their own APCs.
/:cl:

This PR covers a bunch of Pubbystation bugfixes (mostly missing firelocks and alarms) and additions (privacy shutters).

If it's a huge pain in the ass to review I can atomize this.
		
**Firelocks/alarms:**
- Added missing firelocks and fire alarms in almost all statíon areas minus the monastery - there, I only added them to the library to fix #35957.
- Half the station either had missing fire alarms, firelocks or both.

**Changes:**
- Replaced the RD office's directional r-windows and windoor with fulltile r-windows and an airlock. Even though the original design was pretty, this had to be done to fix #35957.
- Added privacy shutters to the CMO and RD offices. Added space shutters to the HoS office.
- Split the library into two areas - lounge and main area. Added an APC to the main area. This is partially to fix #35957, but also because it is one large area that was "magically" powered by a single APC.
- Changed the mail delivery room's area type to quartermaster/sorting.
Added a second blast door to the gulag shuttle entrance.

**Fixes:**
- Deleted duplicate fire lock at Robotics.
- Fixed defunct RD office shutters/buttons and their req_ids.
- Fixed a couple of area issues. For example: the burglar alarm would not affect all doors in the captain's office. RnD fire alarm would not trigger the server room firelock, etc.
- Placed missing shutters (kitchen and engineering).

Closes: #35957

### CODE REVIEW

**Comment by 81Denton** [comment]
ok looks like mapdiffbot is scared

**Comment by praisenarsie** [comment]
probably too big

**Comment by 81Denton** [comment]
Also yeah if this is too large to review properly I can atomize it into shutters/firelocks+areas/misc fixes

**Comment by pubby** [comment]
Nice.

IIRC, I think one of the kitchen's windows is missing a shutter.

**Comment by 81Denton** [comment]
The one on the very right? I got that one, just forgot to put it in the changelog.

**Comment by 81Denton** [comment]
@pubby By the way, I noticed that all other maps have shock grilles around head offices. Would you be against them getting added in a future PR?

**Comment by pubby** [comment]
Shocked grills were never really my style.

You can add them if you and others feel strongly about it, but if it's just for consistency sake then I'd say skip it.

**Pull request merged**
