### PR TITLE
New Camera Sprites from Eris!

### PR DESCRIPTION
**Pull request by Imaginos16**
## About The Pull Request
Resprites the old polaroid camera sprites into ones seen in CEV Eris by Watlerje! (in PR: [#3698](https://github.com/discordia-space/CEV-Eris/pull/3698) of Eris). It also changes the film roll into a film cartridge, akin to classic polaroid cameras.
image

## Why It's Good For The Game
A much better sprite that fits the 3/4ths perspective! It should also be noted that the film cartridge now makes sense, instead it being a roll, which is associated with film cameras rather than polaroids.

## Changelog

:cl: WatlerJe, PositiveEntropy
imageadd: Resprites the Polaroid Camera and the Film Cartridge!
/:cl:

### CODE REVIEW

**Comment by bruhlookatthisdood** [comment]
had me for a secnod thinking the AI's cameras were gonna finnaly get a resprite

**Comment by Imaginos16** [comment]
> had me for a secnod thinking the AI's cameras were gonna finnaly get a resprite

Probably gonna get one when the wallening releases.

**Comment by BlueMemesauce** [comment]
It's a more messy and unclear sprite

**Comment by Farquaar** [comment]
It doesn't really look like a camera at first glance. It should be more easily identifiable as a camera.

**Comment by Coastfront** [comment]
I was fully ready to fucking die on the hill of not respriting ai cameras, I will fucking DIE defending this ideal.
And then i realised its just normal camera sprites.

**Review by Twaticus — APPROVED** [review]

**Comment by tralezab** [comment]
conflict!

**Pull request merged**
