### PR TITLE
Remove Status Bar, Move Command Bar to Chat

### PR DESCRIPTION
**Pull request by ghost**
:cl: Qustinnus
refactor: makes the game screen bigger by removing the status bar and moving the chat bar
/:cl:

image
I might change how the chat buttons look, feel free to comment if u want them to look like they did before. (Also I renamed chat back to Say, I accidentaly renamed it when looking closely at some bee code)

also
image
he said it so

### CODE REVIEW

**Comment by Zytolg** [comment]
I was going to say that this would throw me off (I don't play widescreen because I love suffering) but then I realized that you're actually moving the command bar that's been annoyingly stuck to the bottom of our screens since the beginning of time. It's always bugged me, but in time it's just one of those things I've learned to ignore. This is a great change, although we might need to lower the main UI elements since they seem floaty in the provided screenshot.

**Comment by Qustinnus** [comment]
they have not changed position though, because they were attached to the game screen.

**Comment by cacogen** [comment]
They do seem floaty but I think it's an optical illusion from removing whatever was at the bottom. The button at the top has the same margin, so I think it's fine.

**Comment by Ryll-Ryll** [comment]
As a play and an admin I use the command bar with tab for the vast majority of my speaking/emoting, as well as for spawning things and a handful of admin verbs, and with a 1440p monitor, it would suck to have to drag my mouse all the way to the right quarter of the screen every time I want to edit what I'm saying or edit a command I'm entering. 

Not to mention that in that screenshot itself most of those messages are longer than one line. Do you really want to only be able to see ~10 words at a time whenever you're composing a message without having to do a janky clickdragscroll to go forward/back? For 20 pixels of extra game height?

**Comment by Tlaltecuhtli** [comment]
well instead of down left the mouse goes to  down right, i dont see how its different when its same mouse travel time

**Comment by cacogen** [comment]
>Do you really want to only be able to see ~10 words at a time whenever you're composing a message without having to do a janky clickdragscroll to go forward/back? For 20 pixels of extra game height?

I don't use the command bar outside of typing commands for testing and they're never very long so yes why wouldn't you use hotkeys

**Comment by Qustinnus** [comment]
Anti hotkey people are remains of a bygone era

**Review by stylemistake — APPROVED** [review]

**Comment by stylemistake** [comment]
Winset is no longer based, but I had to do it. I'll find a way to do it in even less code this weekend.

**Comment by TheBonded** [comment]
Did anyone else read the title and think we were removing the status tab and moving the chat?

**Comment by SplinterGP** [comment]
> 
> 
> Anti hotkey people are remains of a bygone era

funnilly i use hotkey but with the lower bar because the speaking popups are annoying and doenst allow me to move in mid of it with arrow keys, so i type on the lower bar while i walk with the arrow keys

**Comment by Ryll-Ryll** [comment]
Yeah I don't get how using tab to switch between focusing on the chat bar and the game controls is seen as some out of date control scheme that can be thrown aside compared to how ugly and uninterruptible popups are

**Comment by maxymax13** [comment]
people who play with nearest neighbor stretch instead of 2x have no soul anyways

**Comment by steppecist** [comment]
Change it back, i dont see any issue with where it was and frankly Coders need to stop fixing things that arent issues

**Comment by Time-Green** [comment]
Gonna take a bit to get used to, but I like it

**Comment by maxymax13** [comment]
oh wait it removes the lower left object name thing? what the fuck revert this, i don't want to enable the stupid fucking huge maptext one at the top of the screen

**Comment by Qustinnus** [comment]
;^) just make a pr to let you make it smaller easy clap

**Comment by Cyprex** [comment]
Would have much preferred this as an optional setting, I like having a wide chatbar for, e. g. SDQL2 Queries

**Comment by Pugie** [comment]
There's legitimate positives to having screentips at the bottom instead of the ones at the top (smaller, less distracting and more discreet) so losing even the option of having them sucks.

The real crime here is no border at the bottom, looks like a window you can't fully see and it's outright jarring.

**Comment by stylemistake** [comment]
I'll look into making a solution for the status text tomorrow, I think we need to remove the maptext thing and make it a semi-transparent byond skin pane, sort of like browsers do in the bottom left corner.

**Comment by wesoda25** [comment]
Yes please give our status text back

**Comment by Summoners** [comment]
Give me my long chat bar back, god dang its a pain.

**Comment by NanoCats** [comment]
I really hate how this looks please ctrl z 

make it an option or whatever.

I also miss "the lower left object name thing" too, I really dislike the big one in the upper middle as well.

**Comment by cacogen** [comment]
In my experience this afternoon looking in the right place to type requires adapting to but other than that I have no complaints.

**Comment by stylemistake** [comment]
I got used to it pretty quickly, so just move on with it.

**Comment by Thunder12345** [comment]
Should've been a pref option, I can see why it would benefit players with smaller screens but as the owner of a sizable monitor the smaller chat bar and missing status text really isn't worth the tiny increase in the size of the game window

**Comment by ishitbyabullet** [comment]
I feel fucking blinded without screentips at the bottom and I despise how the top screentips appear on screen.

**Comment by gryffinp** [comment]
Seventhing the sentiment that the on screen "tips" are obnoxious and obtrusive, and do not function as a replacement for the status bar. I won't weep for the long chat bar but for the love of god give back the status bar that I can look at when I need to and ignore otherwise.

**Comment by cacogen** [comment]
>I got used to it pretty quickly, so just move on with it.

Yeah

**Comment by NanoCats** [comment]
> I got used to it pretty quickly, so just move on with it.

I could get used to sticking my hand in a blender given enough time, that doesn't make it a good idea.

**Comment by optimumtact** [comment]
The screentips need customisation for people https://tgstation13.org/phpBB/viewtopic.php?f=9&t=28714&view=unread#unread

**Comment by stylemistake** [comment]
Stat panel fix: #57527

**Comment by stylemistake** [comment]
Status bar fix: #57531

**Pull request merged**
