### PR TITLE
Procedural Map Generator System

### PR DESCRIPTION
**Pull request by RemieRichards**
- Adds mapGenerator datum
- Adds mapGeneratorModule datum
- Adds some misc defines for objects that had sprites but never existed, for a test case

The mapGenerator datum takes a rectangular region defined by the user, and spawns atoms/turfs in that region based on certain settings. 
Admin (R_DEBUG) Test verb added using a nature themed generator.

The mapGenerator datum contains many mapGeneratorModule datums, which do the actual heavy lifting work. The system is organised in such a way that ordering your mapGeneratorModule(s) like layers in a graphics program is encouraged, to give people an existing concept to base off of using this.

Some template modules are included.

a Full Readme and Mapper Guide is included.

Using this on an entire Z level while the rest of the game is running (untested in lobby and world gen) will lock up the game for about 30 seconds, but small regions (20x20 -> 100x100) are fairly smooth.
I see this as a non issue because this isn't supposed to be run in such large sizes or atleast not while the rest of the game is running you butt. (if necessary I could have the main beefy generate() proc postpone all subsystems while it builds)

Example:
Procedural Forest

### CODE REVIEW

**Comment by Deantwo** [comment]
Kinda like https://github.com/Spoffy/LLA-Station-13/pull/193?

**Comment by RemieRichards** [comment]
@Deantwo not quite, that just loads predefined templates of engineering, sort of like the holodeck on a bigger scale.

This is completely customisable random generation, From Forests to (if you put in the effort to tinker and create modules) Entire stations.

**Comment by Deantwo** [comment]
Interesting! :+1:

**Comment by Thunder12345** [comment]
So if someone makes enough modules, we can have a procedural derelict to make space exploration more fun and challenging?

**Comment by RemieRichards** [comment]
Provided the modules are created <i>anything is possible!</i>

**Comment by Thunder12345** [comment]
What about procedural destruction of the modules, so we don't have to make modules pre-damaged?

**Comment by RemieRichards** [comment]
Well, there's no procedural deletion at the moment, but you could accomplish that with a module that just spawns bombs that immediately explode. alternatively add the damaged versions of tiles as splatter or dense layers.

**Comment by Steelpoint** [comment]
Very nice. :+1:

**Comment by xxalpha** [comment]
This might sound stupid, but have you tried dividing a big region into smaller ones so when generating a map it does one bit at a time, to prevent locking up?

**Comment by RemieRichards** [comment]
@xxalpha I'm not sure if that would have an effect. not to mention all usage of this outside of badminnery is lagless.

**Comment by WJohn** [comment]
I personally prefer hand-crafted maps, but hey I'm not going to get in the way of infrastructure. I'm really hoping that people really add a lot to this, as it's a pretty huge project by itself and needs tons of work to be usable.

**Comment by RemieRichards** [comment]
>needs tons of work to be usable

Excuse me >:/ hehe.

**Comment by ike709** [comment]
I'm still waiting on dismemberment

**Comment by Jalleo** [comment]
This would be a good system to base a mining meteor bluespace magnet off of. Would this be easily changable on the fly of what will be spawned? Aka a slight change of one input makes more iron ores appear etc etc.

**Comment by RemieRichards** [comment]
@Jalleo you'd have to manually alter the contents of the module's spawnableAtoms and spawnableTurfs lists, but yes, you can have other code dynamically change what is spawned by modules.

**Comment by Jalleo** [comment]
Sounds good I had a idea about one or two things that could be done at somepoint in the summer and this would be a good tool for its implementation.

**Comment by GunHog** [comment]
Is this still alive?

**Comment by RemieRichards** [comment]
Yes, and it's merge ready.

**Comment by Jalleo** [comment]
@Cheridan @phil235

**Comment by PJB3005** [comment]
Question, @RemieRichards, Can I port this to /vg/?

**Comment by RemieRichards** [comment]
@PJB3005 Feel free to do so.

**Pull request merged**
