### PR TITLE
gives three tiny buffs the knock heretic path

### PR DESCRIPTION
**Pull request by mc-oofert**
## About The Pull Request

burglars finesse range increased and it may loot any storage object on the back
caretakers refuge cooldown is only applied when exiting refuge
labyrinth handbook accepts any crayon instead of a white crayon

less balance related:
click on an id card with eldritch id card to make it consume it
eldritch id portals are slightly smoother

## Why It's Good For The Game

burglars finesse will immediately get you valided at max range anyway so lets make it longer
caretakers refuge is not that good to need a 2 minute total cooldown
the labyrinth handbook recipe is too bad to even consider making it ever, making it use a crayon makes it more accessible and its still not that good of an item anyway

## Changelog
:cl:
balance: burglars finesse spell range increased from 4 to 6 and it may loot any back storage object, caretakers refuge cooldown is only applied when exiting refuge, labyrinth handbook accepts any crayon instead of a white crayon
qol: you may click an id with the knock heretic id card to make it consume it
/:cl:

### CODE REVIEW

**Comment by EnterTheJake** [comment]
I don't think anyone will make the labyrinth book even with this change.

It should not get consumed after you use it 3 times, Why not have the charges generate over time?

**Comment by Xackii** [comment]
finally i don't need to kill detective for white crayon

**Comment by SomeoneYouProbablyKnow** [comment]
3 uses is fine, mostly because without the crayon making the book will be so so easy

**Comment by mc-oofert** [comment]
> I don't think anyone will make the labyrinth book even with this change.
> 
> It should not get consumed after you use it 3 times, Why not have the charges generate over time?

a crayon box contains like 8 or so crayons idk wheres the problem bro

**Comment by EnterTheJake** [comment]
> > I don't think anyone will make the labyrinth book even with this change.
> > It should not get consumed after you use it 3 times, Why not have the charges generate over time?
> 
> a crayon box contains like 8 or so crayons idk wheres the problem bro

The problem is that the item itself is fairly underwhelming.

Even with the recipe change, it's just not worrh the hassle IMO.

**Pull request merged**
