### PR TITLE
Escape broken name in changelog

### PR DESCRIPTION
**Pull request by optimumtact**
Fixes travis failing on all new PR's

### CODE REVIEW

**Comment by optimumtact** [comment]
@MrStonedOne might need escaping on the name field.

**Comment by optimumtact** [comment]
@Jordie0608 @Cheridan @ChangelingRain @KorPhaeron @WJohn @RemieRichards @MrPerson 
quick merge when travis is done

**Comment by Jordie0608** [comment]
Who needs to wait for travis

**Comment by optimumtact** [comment]
What could possibly go wrong :smile:

**Comment by MrStonedOne** [comment]
alright... i'll add this.

**Pull request merged**
