### PR TITLE
Felinids go meow

### PR DESCRIPTION
**Pull request by grungussuss**
## About The Pull Request
made at the request of a very annoying e-girl
### Starring:
- orangesnz as the male catboy
- Aoife Everwood AKA redemptionarc as the female catgirl

<details>

https://github.com/user-attachments/assets/d032aca9-8f45-4fc7-8643-fea2a3a5da9c

https://github.com/user-attachments/assets/dffe05cc-7766-4c5b-8279-25d64dfbd5e9

</details>

## Why It's Good For The Game
- I think it's really funny
- if people abuse it we can increase the cooldown or give them brain damage for every meow.
- Eventually I want to give every species 1-2 special emotes only for their race, it only made sense that felinids got *meow
## Changelog
:cl: grungussuss
add: felinids can now *meow
sound: added the felinid meow sound
/:cl:

### CODE REVIEW

**Comment by ZephyrTFA** [comment]
species changes need maintainer approval

**Comment by Livrah** [comment]
add OFF meow

**Comment by kawaiinick** [comment]
can we talk about god

**Comment by justricky21** [comment]
meow

**Comment by Helg2** [comment]
Peak degenereacy 👍

**Comment by CCC23** [comment]
mrrp meow :3

**Comment by JohnFulpWillard** [comment]
I am very strongly against this, with no prior maintainer approval either I don't actually see any reason to keep this up.

**Comment by CliffracerX** [comment]
Of all the things to veto in recent memory, letting people meow their sorrows away is not one of them.  TG has a massive lack of funky character emotes compared to most downstreams as it is & this at least has some actual effort put into it.

**Comment by Kiromaka** [comment]
As sun-tzu once said - "Waaow, you're meowing like a cat! That means you're one of them, right? Shut the fuck up. If you really want to be put on a leash and treated like a pet, then it's called a fetish, not "fancy" or "cute." What part of you seriously thinks that any part of feline behavior creates a cute impression of a person? Does your lack of any defining aspect of your personality encourage you to resort to crappy cat parodies to create the illusion of meaning in your worthless life? Wearing "cat ears" in the form of a headband on your head once again indicates a complete lack of a normal human quality to your fucked-up sense of personality, such as intelligence or charisma in any form or form. Where do you think this kind of thinking will lead you? Do you think you're funny, unpredictable, and even quirky? What makes you think that the behavior of a fucking cat will cause someone to have a fucking fit of homeric laughter? Personally, I feel boundless condescension and great sympathy "

**Comment by Hexflash24** [comment]
This can only be merged under one condition, meowing makes you valid

**Comment by thgvr** [comment]
its bleak

**Comment by DrDiasyl** [comment]
> This is so harmless why the fuck do people react so strongly against it

racism.

**Comment by MrMelbert** [comment]
> This is so harmless why the fuck do people react so strongly against it

The only reason I'm against it is people will bind it to their spin+flip+clap+snap+crack hotkey and be even more annoying

**Comment by DrDiasyl** [comment]
> > This is so harmless why the fuck do people react so strongly against it
> 
> The only reason I'm against it is people will bind it to their spin+flip+clap+snap+crack hotkey and be even more annoying
> 
> It doesn't serve for immersion if people spam it constantly

We should ban emote spamming ngl, its time to open a policy thread on forums.

**Comment by Ephemeralis** [comment]
> I am very strongly against this, with no prior maintainer approval either I don't actually see any reason to keep this up.

"I am very strongly against this for reasons that I will not spend 30 seconds of my time attempting to explain for fear of being criticized."

**Comment by LemonInTheDark** [comment]
> racism.

I am assuming this is serious rather then a joke, maligning someone's character because they don't want a pr you like is not acceptable. Do not do this again.

**Comment by DrDiasyl** [comment]
> > racism.
> 
> I am assuming this is serious rather then a joke (If I'm wrong disregard what follows), maligning someone's character because they don't want a pr you like is not acceptable. Do not do this again.

Felinid racism is a serious problem in modern TG society for real.

It was not serious and not targeted at anyone specific.

**Pull request closed without merging**
