### PR TITLE
Adds an id card to the free golem ship vendor

### PR DESCRIPTION
**Pull request by Supermichael777**
:cl:
add: Free golems can now buy new ids for 250 points.
/:cl:

So you can keep a spare or give new golems one.

### CODE REVIEW

**Comment by GunHog** [comment]
The crates in the northern end are full of IDs!

**Comment by Supermichael777** [comment]
they have 1 each

**Comment by Supermichael777** [comment]
and ususaly end up in memes like lava, chasms, and ash drakes

**Comment by Repukan** [comment]
They have like 8 IDs what the hell.

**Comment by Militaires** [comment]
your name isnt optional name here

**Comment by Onule** [comment]
Never seen free golems run out of IDs..
However, I would buy one if they had robotic's access, so I could do maintenance on mechs, that would be worth it imo.

**Comment by Supermichael777** [comment]
I have. they have enough ids for the base shells and when they run out they run out.

**Comment by octareenroon91** [comment]
Basic access and setting name once would be appreciated.
Agent ID would presumably be too much, but maybe a non-syndicate clone?

**Pull request merged**
