### PR TITLE
[DNM] chance is an illusion, everything is predetermined

### PR DESCRIPTION
**Pull request by Lett1**
## About The Pull Request

Just a stupid idea to see what would happen if you would make prob(x) always return True.

## Why It's Good For The Game

It's not.

## Changelog
:cl:
tweak: glued god's dice to the table
/:cl:

### CODE REVIEW

**Comment by Rowelll** [comment]
oh my OH MY

**Comment by Dennok** [comment]
Better if you make it configurable from ingame, on/off and predetermined 1/0, so admins or events can change it to make lucky or unlucky rounds.

**Comment by optimumtact** [comment]
that sounds nice in theory dennok but would almost certainly lead to a considerable amount of proc call overhead or var usage.

This is fine as a test merge but obviously would never make it in to the game.

**Comment by dr-bee** [comment]
Sounds like a fun test merge for april fools.

**Comment by nicbn** [comment]
You're a little late for April Fool's, bud

**Comment by Ziiro** [comment]
Just add the [57 leaf clover](https://riskofrain.fandom.com/wiki/57_Leaf_Clover) to SS13

**Pull request closed without merging**
