### PR TITLE
Fixes pets breeding with their own children.

### LINKED ISSUE #27550: Runtime is a magical redneck.
This is pretty simple, Runtime is able to reproduce with her own children and can even do it through windows.

Can be quickly reproduced by spawning Runtime a mate, deleting that mate after she has a child and then watching in horror as she reproduces with her own children.

### LINKED ISSUE #41044: lisa can have SEX with BABY IAN
Issue reported from  Round ID: 95794 (/tg/Station Sybil [ENGLISH] [US-EAST] [100% LAG FREE])

Reporting client version: 512

if the title doesnt explain itself i don't know what will
reproduction:
1. drag lisa to ian while they're a corgi puppy
2. make them have babby

### LINKED ISSUE #51030: Infinite Runtimes
Issue reported from  Round ID: [136736](https://scrubby.melonmesa.com/round/136736) (/tg/Station Manuel [ENGLISH] [US-WEST] [ROLEPLAY] [99% LAG FREE])

Reporting client version: 513.1513

Runtime spawns infinitely.
Runtime Error Hhahaha

The game had to be force started by an admin, as secret autostart errored out. I don't know if the two are related, but I'm noting it here just in case.

### PR DESCRIPTION
**Pull request by ShizCalev**
Fixes #27550
Fixes #41044
Fixes #51030

:cl: ShizCalev
fix: Pets will no longer breed with their children.
fix: Pets will no longer breed infinitely despite having a ton of children around.
/:cl:

_*cough*_

### CODE REVIEW

**Comment by Ryll-Ryll** [comment]
roll tide

**Comment by Tharcoonvagh** [comment]
CHRIST

**Comment by ArcaneDefence** [comment]
No more catsplosions? Sad.

**Comment by TheVekter** [comment]
No more LMAO 2CAT, sad tbh

> roll tide
That's an Arkansas thing, not Alabama.

**Pull request merged**
