### PR TITLE
Adds research-boosting programs for nanites

### PR DESCRIPTION
**Pull request by XDTM**
:cl: XDTM
add: Added the Distributed Computing nanite program, which slowly adds research points over time. 
add: Added the Neural Network nanite program, which adds research points over time as well, but scales in efficiency for each mob that is currently running the program, breaking even with Distributed Computing at 12 hosts.
add: All of these programs only work on complex mobs (humans, monkeys, xenomorphs) and only have 25% efficiency on non-sentient mobs.
/:cl:

Why:
- Gives science an incentive to spread nanites as much as possible.
- Gives non-science a small incentive to get nanites (more points = more chance of getting that research you need).
- Softens the blow when someone rushes nanites, since they can potentially get those points back over time.

### CODE REVIEW

**Comment by GuyonBroadway** [comment]
Third times the charm...

**Comment by CRITAWAKETS** [comment]
cant wait for someone to use this as an excuse to spread infectious nanites

**Comment by zxaber** [comment]
Also gives Sec a reason to perma people with this nanite over executing them (not that I expect it to weigh the decision much).

**Comment by Shapsy** [comment]
Signing my soul over to Nanotrasen was one thing, but using my brain to mine bitcoins is just adding insult onto injury

**Comment by CRITAWAKETS** [comment]
> Signing my soul over to Nanotrasen was one thing, but using my brain to mine bitcoins is just adding insult onto injury

holy moly a nanite program that drains nanites and gives you a tiny bit of brain damage that gives money to the RnD budget would be amazing

**Comment by 81Denton** [comment]
>Signing my soul over to Nanotrasen was one thing, but using my brain to mine bitcoins is just adding insult onto injury

Now we just need social credit and it's perfect.

**Comment by XDTM** [comment]
The old version of this PR had both bitcoin mining and brain-damage overclocking, but i left them out for now to avoid potential bikeshedding.

**Comment by OverlyGeneric** [comment]
aw, I was expecting this to be nanites randomly changing your organs and limbs to be a minor inconvenience like suddenly your feet turn digitigrade, or you spontaneously grow a fake armblade, or even suddenly your heart changes into a harmless abductor gland.

**Comment by optimumtact** [comment]
didn't I close this?

**Comment by XDTM** [comment]
after looking at it before resurrecting it, it was most likely because i claimed it required another PR of mine which got closed (the station budget one)

**Comment by ExcessiveUseOfCobblestone** [comment]
kinda blind on how nanites work, does they require some form of upkeep?

passive point regen is something i'd like to avoid including as the goal is still to replace our current passive forms w active methods.

**Comment by XDTM** [comment]
Trying to convince multiple people to get nanites seems like a fairly hard job, and on top of that running the research program costs a bit of volume, making them less efficient than without.

**Comment by HomocidlePancakes** [comment]
Looks a tad bit forced IMO. Don’t know how else to describe it

**Comment by actioninja** [comment]
This along with other new active point methods is probably going to throw rnd out of whack for a while. I think it's worth it to kill passive generation in the end.

**Comment by actioninja** [comment]
I thought I merged this.

**Pull request merged**
