### PR TITLE
the true psion experience.[READY] [Needs review] [100% lag free][tested in theory]

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request
I've set all human_requirement lines for hivemind powers to 0.

## Why It's Good For The Game
during a hivemind round i got mmied and noticed that due to my network being big enough before death i could use some abilities allowing me to sniff out another host and notify security, since hivemind is a psionic antagonist I've decided to allow hosts who have been mmied to fully help the crew while also being able to fight against other hosts and meme as a cak if turned into one. this deals with https://github.com/tgstation/tgstation/issues/42660
## Changelog
:cl:

tweak: all hivemind powers have their human_requirement lines set to 0 if they have them. 
/:cl:

### CODE REVIEW

**Comment by dr-bee** [comment]
My dreams of playing a psionic brain wired into a combat mech can now come true.

**Comment by Kierany9** [comment]
oh god

**Comment by lordsaladin** [comment]
cak memes intensify.

**Comment by HomocidlePancakes** [comment]
I love you

**Comment by ATH1909** [comment]
https://www.youtube.com/watch?v=P3ALwKeSEYs

**Comment by imsxz** [comment]
did you test mind controlling as a non humanoid mob? line 255 tells me that its gonna be fucked

**Comment by ATH1909** [comment]
> did you test mind controlling as a non humanoid mob? line 255 tells me that its gonna be fucked

Oh yeah, how do simplemobs handle the brain damage recoil from having someone whom you are mind controlling die while you are mind controlling them? Maybe they should just take a bunch of brute damage or be gibbed instead?

**Comment by ExcessiveUseOfCobblestone** [comment]
> did you test

`lordsaladin:patch-2`

hmmm

**Review by ExcessiveUseOfCobblestone — COMMENTED** [review]
human_req is a boo ergo should use `TRUE`/`FALSE` defines

**Comment by ExcessiveUseOfCobblestone** [comment]
If you are making a heavy change (such as enabling nonhumans to use spells meant only for humans) it should be properly tested in a local environment, even if it's just 2 line diff in code.

Please do not lie about testing in the future or your stay here will be brief. That said, let me know when you've properly tested this so I can reopen.

**Comment by lordsaladin** [comment]
@ExcessiveUseOfCobblestone a friend will test it, also this is allowing a host to use their full ability set as a mmi/mmi derived entity.

**Comment by ExcessiveUseOfCobblestone** [comment]
Once tested let me know.

I'm aware of what the PR does, including the implications that make me hesitant to entertain without testing.

**Pull request closed without merging**
