### PR TITLE
Adds a notice about the feature freeze to the pull request template

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
People are still opening PRs about balance/antags and in their defense its becoming increasingly likely people wont know we have a freeze as it falls into the stale PRs on the third page

### CODE REVIEW

**Comment by Xhuis** [comment]
🔫 👮 HOLD IT THERE PARTNER
IT LOOKS LIKE THAT PULL REQUEST OF YOURS HAS VIOLATED THE ❄️FEATURE FREEZE ❄️ 
CLOSE 🚪 THIS CODE 💻 BEFORE I CLOSE 🚪 YOUR LIFE 🔪

**Comment by Cyberboss** [comment]
Who actually reads the template though?

**Comment by KorPhaeron** [comment]
People might notice if its there before the changelog and they have to delete it

**Comment by Cyberboss** [comment]
@KorPhaeron edit the freeze pr to revert this

**Pull request merged**
