### PR TITLE
Revive's @CameronWoof's medkit sprites

### PR DESCRIPTION
**Pull request by astralloop**
breaking-news 1

:cl: Astral
spriteadd: remember @CameronWoof's medkit sprites? no? fuck you. anyways i readded them
/:cl:

### CODE REVIEW

**Comment by deathride58** [comment]
Yo, we have a more recent version of these over at Citadel, complete with some variance for the actual sprites.

https://github.com/Citadel-Station-13/Citadel-Station-13/pull/3800 Here, take this medkit.

**Comment by CameronWoof** [comment]
Ohey. Well, this was unexpected.

Thanks for liking these enough to dig them up! As deathride says, these aren't the final version of the sprites, but they're pretty close re:quality to the ones we went with.

**Comment by astralloop** [comment]
@deathride58 i honestly prefer these

**Comment by ShizCalev** [comment]
@deathride58 Not to put down the sprites or anything, but the smaller ones from that PR look like poop, and the large ones seem -way- too big.

Overall I prefer these ones over them myself.

**Comment by ShizCalev** [comment]
@CameronWoof sent me a message on discord is working on updating the medbot sprites, I'll open a PR with them on your branch when he is finished.

**Comment by ShizCalev** [comment]
https://github.com/astralloop/tgstation/pull/1

**Comment by WJohn** [comment]
While I *slightly* prefer the color schemes of the citadel ones, I don't like *any* of their proportions. They're either gigantic, or tiny, or far too wide. You could probably take the large medkit sprites from citadel and shorten them by 2-3 pixels and they'd be much better.

**Comment by CameronWoof** [comment]
Does that mean you do not like the ones proposed in the PR, or the updated medbot sprites, WJohn?

**Comment by WJohn** [comment]
Medbot sprites aren't even updated in either PR.

Ultimately I think it'd be best if more detailed medkit sprites are created. The shapes for the ones here is superior to the ones in the citadel PR if only because they're octagonal, but I feel you could add a lot more details like depressions and bumpy looking latches to it, probably a line where it opens, too.

I *do* appreciate the dithering on these, too.

**Comment by ShizCalev** [comment]
@WJohn astralloop#1 they're updated in this one which hasn't been pushed to his branch yet.

**Comment by ACCount12** [comment]
Those look like medical _toolboxes_, not box-sized medkits.

**Comment by WJohn** [comment]
Tweaked it a little bit as an example. They're larger now, and have latches.

**Comment by Xhuis** [comment]
I can't say I'm a fan of these, especially since the sprites we do have are fine as is and a lot of things use them, ala medbots and the fleshmend status effect icon.

**Comment by DaedalusGame** [comment]
this opinion but on basicly every sprite PR

**Comment by ShizCalev** [comment]
@WJohn Do keep in mind how these look on a table and all that too.

Your proposed changes:
image

Current PR:
image

Mix between the two (no scale change):
image

**Comment by praisenarsie** [comment]
can we not have medkit sprites that look like luggage please

**Comment by Xhuis** [comment]
They all look worse! 😭

**Comment by Bawhoppen** [comment]
I can see what they're going for, but I don't think it's the best execution of the sprite.

**Comment by astralloop** [comment]
@ShizCalev heh, your medibot sprites are cute

**Comment by CameronWoof** [comment]
Full disclosure: the original purpose of this PR, when I opened it months ago, was to get new medkit sprites to the downstream server I play on. We eventually found a sprite we were happy with locally and I took down this PR when it was apparent that it wasn't going to get merged.

I'm really flattered that someone liked them enough to open the PR back up, and I spent the extra bit of time to remake the Medbot sprites, but ultimately, _I don't play on /tg/ and, while it'd be nice if you wanted to use my sprites, I have no real desire to work on them for hours with no guarantee they'd get used anyway._

I think the sprites as-is are a huge upgrade to what we have now, even if they could be better (and literally everything 'could be better.') WJohn or anyone is more than welcome to make edits to them as they see fit, but I feel like I've done more than what should be expected of me as someone who has no vested interest in getting the sprites merged.

Best of luck, astral, and welcome to the github.

**Comment by ShizCalev** [comment]
Any further changes to these sprites I can do myself, thank you for what you've done so far @CameronWoof

**Comment by praisenarsie** [comment]
i don't get why you guys haven't done a simple thing to make it look like a medkit

just make it look a square/cube.

**Comment by Xhuis** [comment]
A little slow there, bot. Also, jesus, those medibot sprites look really weird.

**Comment by astralloop** [comment]
i find them cute

**Comment by Xhuis** [comment]
I think I'd probably just have to adjust for a while.

**Comment by WJohn** [comment]
Roouuuunnddd aaaaarrrrmmmssss

**Comment by epochayur** [comment]
i've never seen a medkit that looks like that

**Comment by ShizCalev** [comment]
@epochayur 
<details>
img_1929_1_1_2
2tray_closed_529
1505 1 8csso7

hd10_1986_txt_us_useng
hi-viz-450x450

</details>

**Comment by epochayur** [comment]
#roasted

**Comment by ChuckTheSheep** [comment]
Needs to be more boxy imo.

**Comment by ShizCalev** [comment]
I'll do a pass on all the sprites tonight to update them.

**Comment by ShizCalev** [comment]
https://github.com/astralloop/tgstation/pull/2

**Comment by astralloop** [comment]
@ShizCalev done

**Comment by WJohn** [comment]
What we have now isn't great, I don't think these are a significant enough improvement in quality to be worth adding.

I think that the way that perhaps air tanks or water/welding fuel dispensers compared to what they used to be is an example of the sprites being MAJORLY improved, and these just are not on that level. They're decent, but not enough. Sure, those are done by ausops and getting to his level is extremely hard, but at the same time I don't think it's good to settle for only "alright" and just eat another shitstorm as people lose their minds over this kind of thing again.

If majorly improved and redone sprites are brought forth in this PR, I'll re-open it.

**Comment by astralloop** [comment]
@WJohn I merged https://github.com/astralloop/tgstation/pull/2, was that not enough

**Comment by WJohn** [comment]
Yes, I saw. The long and short of it is that the amount of detail and quality of these sprites isn't sufficient enough to warrant merging in its current form. I think it needs something much higher quality. Think back to the water tanks, and what they were like when first proposed. Then ausops swooped in and made vastly superior ones. That's what this PR would need.

**Pull request closed without merging**
