### PR TITLE
hey it's been a week, time to Remove Secborg

### PR DESCRIPTION
**Pull request by Iamgoofball**
https://tgstation13.org/phpBB/viewtopic.php?f=7&t=13970
hey look at that, borg laws vs humans with a focus on the borg being security and able to remove players from a round that way
https://tgstation13.org/phpBB/viewtopic.php?f=33&t=13886
hey look at that 4 pages of people explaining why secborgs were garbage tier and awful

@korphaeron
module left in as per your request but the config and shit was removed with the option to pick them also removed

this is a reopen of #32540 which was closed due to compile issues

### CODE REVIEW

**Comment by Armhulen** [comment]
Hell yeah

**Comment by PKPenguin321** [comment]
>headmin promise to readd secborgs
>gets them removed even more

alpha male coming through

**Comment by Jalleo** [comment]
🌶 🌶 👾 👾

**Comment by epochayur** [comment]
like the seasons change and the sun rises, goof makes more mass-deletion PRs

**Comment by imsxz** [comment]
Don't agree, playing against infinite disablers and stunbatons while not having a reliable way to fight back is fun and engaging gameplay.

**Comment by Armhulen** [comment]
@PKPenguin321 
agenda accomplished, headmin promise fulfilled

**Comment by KorPhaeron** [comment]
Remove it from config text as well

**Comment by Supermichael777** [comment]
Looks like goof admining from the code chair once again.

the primary problem with secborg is that it has issues with control.  Its effectively a rouge sec officer that can suddenly and invisibly turn evil. The problem is that it also has a critical function for AIs as no other borg can be used to deescalate.

**Comment by Iamgoofball** [comment]
@KorPhaeron done

**Comment by jughu** [comment]
Imagine being able to spam emps yet lose to an secborg

**Comment by Iamgoofball** [comment]
>rare chemistry reaction is how you balance infinite ammo

fuck off

**Comment by jughu** [comment]
Ion rifles, flashes, emp grenades, flashbangs, laser pointers, emp chem, ion carbines, robotics console, being good and not get hit. Do i need to say more?

**Comment by jughu** [comment]
Besides said ammo of secborg used to be tasers with limited range

**Comment by XDTM** [comment]
The real issue with secborgs imo is not that they're op, it's that they can't do their job if they actually obey law 2, so they have to make up excuses every time for why law 1 trumps law 2 leading to endless salt and policy threads

**Comment by jughu** [comment]
Just make a special policy if player says that and they have no reason for it it can be ignored like telling them to suicide

**Comment by XDTM** [comment]
Yeah but someone who breaks the law is likely to harm people, right? If i let him go free it's harm!
That dude showed an ebow and told me not to report it, since he wasn't gonna use it! But the ebow means he's an antag, and antags harm people! Law 1!
This clown punched the HoS once fifteen minutes ago, he's clearly shown harmful behaviour and i shouldn't listen to him when he asks me to let him go, he might harm people!

**Comment by davethwave** [comment]
I would prefer that when you change to to the sec borg module you get a different set of laws that would not conflict with everything that sec is instead to fix this.

**Comment by davethwave** [comment]
Well that or either buff up the peacemaker module a bit so it can actually 'keep the peace' as it was intended rather than the meme bot that it is right now.

**Comment by Arianya** [comment]
@davethwave give up, pkborgs are orange's baby, he won't let anyone buff them

Also, as a point of order, you can also stun borgs from a distance by shining laser pointers in their "eyes", though I believe this is a RNG roll unlike flashing.

**Comment by Arianya** [comment]
And since it wouldn't be a secborg related PR/thread without me saying it

>why not just whitelist them

**Comment by davethwave** [comment]
ha ha, true

**Comment by GuyonBroadway** [comment]
Make it so you need to boop a borg with a secbot module and they get given the robocop lawset.  The armoury has 1/2 of these at roundstart and can order more via science and/or cargo. You need to swipe HoS level access (or an emag) on the module to activate it.

**Comment by CPTANT** [comment]
The main reason secborgs suck is that they turn the silicons into a bunch of antag dunking shits.

**Comment by jughu** [comment]
So can standard borg

**Comment by ExcessiveUseOfCobblestone** [comment]
>Also, as a point of order, you can also stun borgs from a distance by shining laser pointers in their "eyes", though I believe this is a RNG roll unlike flashing.

Yes it's RNG, but can be mitigated by upgrading the laser (screwdrive the pen). Higher Tier = higher chance of stun.

**Comment by ExcessiveUseOfCobblestone** [comment]
Also I think we should keep this in until people ahelp secborgs who aren't following their laws.

Using the player problem argument without making any notion to fix the player problem is unfair. Feature wise though, they really shouldn't have auto-recharging ranged slows/stuns.

**Review by ninjanomnom — APPROVED** [review]

**Comment by epochayur** [comment]
RIP

**Comment by davethwave** [comment]
At least we should have upgrade modules to buff the peacemaker...

**Pull request merged**
