### PR TITLE
Removes His Grace ascension

### LINKED ISSUE #24809: His Grace ascension is very bugged
tl;dr
1) An ascended His Grace who has bloodthirst HIS_GRACE_FALL_ASLEEP will stop attacking people.
2) An ascended His Grace never sleeps, technically, so lings, zombies and borerhosts cannot climb out no more.

HERE IS LINE https://github.com/tgstation/tgstation/blob/20f06bf820c8538223cde5d81811b24693cab1fa/code/game/objects/items/weapons/his_grace.dm#L101

Okay, so when His Grace has eaten a whole bunch of corpses, it "ascends", which makes it gold, gives it a special description, bonus damage, and most importantly means IT NEVER SLEEPS.

Normally a His Grace timeline looks like this.

- His Grace is woken, starts at 1 bloodthirst
- As time goes on, His Grace gets more thirsty, and the more he's eaten, the faster his thirst gain is
- Feeding bodies to His Grace lowers bloodthirst to len(number_of_bodies)
- Eventually, after the traitor has run around murdering people, they can't lower the thirst fast enough, and it crosses a threshold into FRENZY

- A His Grace in a frenzy will start 1) attack its owner, doing damage, stunning and making it be dropped, and 2) lunging at nearby people doing damage, and if they are unconscious or dead, eat them.
- People eaten while His Grace is in a frenzy will actually lower his bloodthirst, but never below the frenzy threshold

- Eventually, when His Grace passes a high level of bloodthirst, he falls back asleep. The toolbox stops shaking, and it can be picked up (and then possibly unlatched, and the cycle continues)

HOWEVER! When His Grace has consumed a body via someone attacking with it, and the number of bodies is >= 20, then he ASCENDS.

An ascended His Grace has `ascended` set to true, which means he will never sleep. This also has the effect of preventing people alive inside His Grace (generally changelings, zombies and borer hosts) from climbing out. The cycle continues normally until he reaches the threshold where he wants to sleep. But he is ascended, and thus cannot sleep. But since he's constantly returning at this section of code, he ceases attacking people.

### PR DESCRIPTION
**Pull request by ChangelingRain**
:cl: Joan
rscdel: Removed His Grace ascension.
/:cl:

At first I was going to just make it cosmetic, but, as it happens, losing 15 force when you'd normally already be at 92 force doesn't really matter that much.

### The big reason for this is that it should absolutely not become a permanent hazard if you kill enough people with it, and that's what ascension does, that's literally the entire point.

Closes #24809

### CODE REVIEW

**Comment by coiax** [comment]
Well, currently it's bugged where it'll stop being a constant hazard after a bit. But I think that's very much the intent

**Comment by ChangelingRain** [comment]
Yeah, it is bugged, but the intent was that it'd never sleep and that's, uh, not good. It shouldn't do that because it makes the people it killed nearly unrecoverable, and it's really hard enough with how lethal it is.

**Comment by PKPenguin321** [comment]
This only went through because the PR that added it in the first place was originally a different PR but instead of making a new PR he just changed it

**Comment by Tokiko1** [comment]
Couldn't you shoot at it though?

**Comment by ChangelingRain** [comment]
It's a toolbox and thus an item, you can't kill it without bombs, fire, or, like, the crusher or crematorium.

**Comment by ExcessiveUseOfCobblestone** [comment]
can't the dual esword burn brains from existence?

**Comment by Repukan** [comment]
Are there any stats on how often it reaches ascension?

**Comment by Militaires** [comment]
no that wasn't the entire point
it rarely ever reaches ascension, and you CAN actually laser it 3 times and it is dead.

i mean the purpose of this was to ascend and kill you with it because joan for fuck's sake

when you kill 20 people the hunger rate becomes instant and you almost immediately die

**Comment by jughu** [comment]
If you kill 20 people majority of the station is dead anyways

**Comment by Militaires** [comment]
if you guys are assblasted im changing my pr to immediately set the toolbox to hunger kill owner since joan cant understand how high the hunger rate fucking becomes

**Comment by ChangelingRain** [comment]
>you CAN laser it 3 times and it's dead

No you can't, what????
>when you kill 20 people the hunger rate becomes instant and you almost immediately die

It's JUST 11 bloodthirst a second, that's like 10 seconds of being able to murder people! If that's too fast, hey, you can tune that!
>you're talking like people dont bomb or space it already

Spacing it doesn't get the corpses back and I'm like 50% sure, since I haven't tested, that bombing it will also gib the corpses!

>it ADDS 15 force did you even check the pr's diffs fug sake joan
Yes I know, but at the point where you'd get the 15 force you're already at 92 and you seriously don't need more force.

**Comment by PKPenguin321** [comment]
>>you CAN laser it 3 times and it's dead

>No you can't, what????

I don't know Joan that GIF he posted of him doing just that was pretty convincing

**Comment by Iamgoofball** [comment]
i wonder if a his grace killed a clockcult member

@PKPenguin321 joan will just """fix""" it as a bug to push their agenda

**Comment by ChangelingRain** [comment]
>i wonder if a his grace killed a clockcult member

oh, fuck off. You know it's a traitor item and I murder anyone doing anything in clockcult that affects the round.

**Comment by Militaires** [comment]
@PKPenguin321 clearly i coded in object damage and refactored it just to make myself look right

yeah i was saying you're talking like people dont space it already; meaning that when you said that ascension makes it harder to get the corpses back isnt really that important because people bomb it or space it anyways

@ChangelingRain it's almost instantly gonna kill you yeah that's the point

**Comment by KorPhaeron** [comment]
If someone wants it readded they can fix it themselves

**Pull request merged**
