### PR TITLE
Revert "Vending TGUI"

### PR DESCRIPTION
**Pull request by Cyberboss**
Reverts tgstation/tgstation#33739

You fucking broke them @MoreRobustThanYou

### CODE REVIEW

**Comment by MoreRobustThanYou** [comment]
FIX IT

**Comment by vuonojenmustaturska** [comment]
@MoreRobustThanYou you're a big boy and can fix your own code

**Comment by kevinz000** [comment]
mature morty

**Comment by duncathan** [comment]
@MoreRobustThanYou let this serve as a lesson to carefully test any code you port directly from hippie, because even the slightest difference can cause major issues. Either you screwed up while porting or they were broken as is; either way you're at fault so be sure to test

**Pull request merged**
