### PR TITLE
Revert "Revert "adds alternate medborg sprites""

### PR DESCRIPTION
**Pull request by Fikou**
24
HOUR
RULE

### CODE REVIEW

**Comment by MrDoomBringer** [comment]
lgtm

**Comment by Jared-Fogle** [comment]
why is nobody telling me whats so special about this pr

**Comment by brotherbeyondd** [comment]
vore borg vore borg

**Comment by trerri** [comment]
idk man it seemed promising

**Comment by CoffeeDragon16** [comment]
@Jared-Fogle i think action has a dog allergy or something

**Comment by MrDoomBringer** [comment]
no idea but i'm fairly certain the PR this reverts was in violation of the /tg/station community codebase coding guidelines, I don't see any reason not to merge this

**Comment by ShibaInuLord** [comment]
isnt it like if 4 maintainers want it it skips 24 hour rule

**Comment by Jared-Fogle** [comment]
what is vore

**Comment by MrDoomBringer** [comment]
image

**Comment by Jared-Fogle** [comment]
i dont get what that has to do with this pr

**Comment by ShibaInuLord** [comment]
i am an omnivore

**Comment by LemonInTheDark** [comment]
It has to do with consumption. you wouldn't get it

**Comment by Jared-Fogle** [comment]
image

**Comment by MrDoomBringer** [comment]
In all honestly though - for anyone wondering, 'vore' is a term short for 'voracious', defined by Oxford Languages as "having a very eager approach to an activity."
When people say "Vore" in conjunction with this PR, they're saying that they're eager to see this activity in-game (Another way to ask for a merge).

**Comment by actioninja** [comment]
nah just kidding made you look

**Comment by Jared-Fogle** [comment]
@MrDoomBringer  really? guess i love vore then! 😄

**Comment by MrDoomBringer** [comment]
wussy

**Comment by MrDoomBringer** [comment]
@Jared-Fogle same here

**Pull request closed without merging**
