### PR TITLE
Resprites the Captain's Antique Laser Gun

### PR DESCRIPTION
**Pull request by Imaginos16**
## About The Pull Request
An alternative to the previous attempt, this one now made by yours truly. It changes the captain's antique into this more modern take of the sprite!
image

Its a bit more of a radical departure shape-wise, but fits better aesthetically to the direction we're moving towards in /tg/!

## Why It's Good For The Game
Its quite an old sprite, and the previous PR did not satisfy me and the rest of the playerbase when it was first attempted, so hopefully this take is more pleasing for all parties!

## Changelog

:cl: PositiveEntropy
imageadd: Resprites the Captain's Antique Laser Gun!
/:cl:

### CODE REVIEW

**Comment by theta060** [comment]
what the fuck is the art direction TG is trying to go for? this looks futuristic and good while other things look cartoony

**Comment by ATH1909** [comment]
despite being an "antique", this looks more modern/futuristic than our normal energy guns

whether or not that's a good thing is up for debate, I suppose

**Comment by bluetshirtguy** [comment]
Modern take indeed, looks like that antique was made today!

**Comment by realthomas69** [comment]
sprite quality is good but you've completely missed the point that its an antique, the old sprite looked weathered and retro and this one looks sleek and futuristic.

**Comment by Twaticus** [comment]
"weathered and retro" thats just an old sprite dawg

**Review by Twaticus — APPROVED** [review]

**Comment by tf-4** [comment]
It's a great sprite but yeah. Too sleek for something that's meant to be an antique imo.

**Comment by Dorsisdwarf** [comment]
> despite being an "antique", this looks more modern/futuristic than our normal energy guns
> 
> whether or not that's a good thing is up for debate, I suppose

Honestly thats pretty much lore compliant lol, consider TGMC vs TG art style

**Comment by Valorium-RB** [comment]
Maybe add a little etching on the "receiver" to indicate the engraving that's supposed to be on there? Otherwise, love the sprite!

**Comment by necromanceranne** [comment]
> what the fuck is the art direction TG is trying to go for? this looks futuristic and good while other things look cartoony

Nothing says we can't update those too

**Comment by anclandor** [comment]
I personally like the old sprite better, especially how it mirrors the HOS's gun, as the HOS's gun is meant to kind of be a modern version of the caps antique.  Could you please have the old one juxtaposed with the new one so we can see how it compares?

**Comment by YakumoChen** [comment]
The sprite looks much better than the goon one
Unfortunately I agree that it doesn't really look Antique?

Is there a way to make the sprite look more weathered?

**Comment by normie5-cell** [comment]
what about hoslaser?

**Comment by Comxy** [comment]
What about the about the inhand sprites?

**Comment by Spc-Dragonfruits** [comment]
I actually like that it's sleek, it gives it value. Firearms can be kept in good conditions for a good long while, see:
image
A Model 1717 musket (That was a bit over 300 years ago)

Now imagine whatever polymers the laser gun is made of, and any other modern alloys

**Pull request merged**
