### PR TITLE
Instrument tweaks

### PR DESCRIPTION
**Pull request by MrPerson**
The piano will stop playing once you walk away from it or get stunned.

The song BPM of the piano and violin will generally speaking be wrong because of discrepancies between the sleep between notes and world.tick_lag. I've solved this by locking BPM to points where the stated BPM will actually be the case because tempo == world.tick_lag.

Example
Current:
song @ 5 tempo - 120 BPM: w/ notes c, c/2, c -> note -> sleep(5) -> 6 ticks (5.4 time passes) -> note -> sleep(2.5) -> 3 ticks (2.7 time passes) -> note.

With this PR:
song @ 5.4 tempo - 111 BPM: w/ notes c, c/2, c -> note -> sleep(5.4) -> 6 ticks (5.4 time passes) -> note/2 -> sleep(2.7) -> 3 ticks (2.7 time passes) -> note.

I was hoping this would make the damn things sound better but then I realized this doesn't actually change anything, it just makes the UI not a big fat liar.

### CODE REVIEW

**Comment by optimumtact** [comment]
https://www.youtube.com/watch?v=SsNl9zaWJdQ

**Comment by Fox-McCloud** [comment]
:+1: to tempo fix

:-1: to requiring someone to be there to use it.

**Comment by optimumtact** [comment]
It's not a programmable piano buddy

**Comment by Dorsisdwarf** [comment]
Yes it is.

**Comment by Chocobro** [comment]
didn't it used to be like this a year ago???
:+1:

**Comment by MrPerson** [comment]
It's mostly an anti-griefer thing. If you want to griff with the piano, you have to listen to your own shitty song. Plus everyone has the oh-so-fun opportunity to beat your ass up if you insist on continuing to play.

**Comment by MrPerson** [comment]
Added a preference toggle for hearing musical instruments and a changelog entry. I decided not to piggyback off another preference and just added a new one.

**Comment by Giacom** [comment]
>It's mostly an anti-griefer thing. If you want to griff with the piano, you have to listen to your own shitty song

You just added the option to disable that.

**Comment by Fox-McCloud** [comment]
Yeah, no sense in having the local requirement now that people can toggle it--if barkeeps want to have music playing in their bar without being there, I don't see the downsides to this with the ability to toggle now.

**Pull request merged**
