### PR TITLE
Prevents immersion breaking speech without blocking words or characters.

### PR DESCRIPTION
**Pull request by Iamgoofball**
Closes #30946

### CODE REVIEW

**Comment by The-clown-known-as-Pepe** [comment]
replace * with asterisk

so we can have ASTERISK DAB

**Comment by DoctoreMad** [comment]
Hello oni-chan tilde.

**Comment by deathride58** [comment]
You can *still* get around this by using dashes---

Nyaaa!!!--------

**Comment by ExcessiveUseOfCobblestone** [comment]
NYAAAAA EXCLAMATION MARK EXCLAMATION MARK EXCLAMATION MARK DASH DASH DASH DASH DASH DASH

**Comment by kevinz000** [comment]
NYAAA--------------

**Comment by Iamgoofball** [comment]
looks like the problem is solved???

**Comment by DoctoreMad** [comment]
@Iamgoofball You're still here.

**Comment by msgerbs** [comment]
Goof stahp!

**Comment by Jordie0608** [comment]
https://github.com/tgstation/tgstation/pull/30946#issuecomment-331625861

**Pull request closed without merging**
