### PR TITLE
[s] makes chemical mob spawning log

### PR DESCRIPTION
**Pull request by silicons**
Whoever did this is really fucking upsetting me right now.

### CODE REVIEW

**Comment by DaedalusGame** [comment]
dumb cat this already happens

**Comment by kevinz000** [comment]
@DaedalusGame not to my knowledge no since i couldn't find it anywhere and it was really damn annoying when someone bombed with it on extended.

**Comment by kevinz000** [comment]
edit: confirmed, they don't log.

**Comment by Iamgoofball** [comment]
they used to log, I remember because I merged some of the code for this and had to add logging at request of admins, someone must of nuked it

**Comment by DaedalusGame** [comment]
yeah i checked aswell and it does not log, odd but ok

**Pull request merged**
