### PR TITLE
Fixed nyctophobia being triggered even if you have mesons

### PR DESCRIPTION
**Pull request by Aerden**
## About The Pull Request

Having meson scanners equipped will still make you scared of the dark when you have nyctophobia. This PR fixes that.

## Why It's Good For The Game

Being able to see in the dark should not make you scared.

## Changelog

:cl:
fix: Fixed being scared of the dark even if you have mesons.
/:cl:

### CODE REVIEW

**Comment by Sealed101** [comment]
mesons aren't like complete night vision tho right, you only see the turf existing there but nothing spooky thats occupying that turf

**Comment by Nebulacrity** [comment]
Good first PR. 🙃

**Comment by Sealed101** [comment]
at the very least your pr name and cl are misleading, mesons are not night vision

**Comment by Aerden** [comment]
> at the very least your pr name and cl are misleading, mesons are not night vision

My bad, fixed.

**Comment by Fikou** [comment]
this being based off see_turfs makes no sense, there are other items that give u semi-night vision like thermals, it should at least be based off light alpha/darkness view

also this makes no sense from a balance standpoint, if you take nyctophobia you now have a harder job jumping someone in maint because you need to be visible 
this doesnt seem like a fix at all

**Comment by Nebulacrity** [comment]
> this being based off see_turfs makes no sense, there are other items that give u semi-night vision like thermals, it should at least be based off light alpha/darkness view

I'd argue it makes sense, as SEE_TURFS (aka the vision mesons give you) causes an illusion to the wearer that they are, in fact, in a perfectly lit place, even if that's not actually true. Thoughts?

> also this makes no sense from a balance standpoint, if you take nyctophobia you now have a harder job jumping someone in maint because you need to be visible, now you will be able to counteract this with mesons that u can get roundstart with no effort, making this free quirk points this doesnt seem like a fix at all

It forces you to obtain and wear an item that can be removed, similarly to Nearsighted's glasses. Perhaps changing the value from -3 to -2 would balance things out?

**Pull request merged**
