### PR TITLE
PIXEL_SCALE Test [WIP]

### PR DESCRIPTION
**Pull request by AnturK**
Just for testmerge for now.

### CODE REVIEW

**Comment by octareenroon91** [comment]
Why not change `.travis.yml` to use a BYOND version that actually features this flag?

**Comment by Quardbreak** [comment]
@octareenroon91Because 511 still not stable?

**Comment by octareenroon91** [comment]
I think it would be nice to know what compiles before testmerging.

**Comment by lzimann** [comment]
511 is more stable than 510 already, and we already force everyone to be on 511(otherwise your game won't work properly). The only problem with 511 is that byond allows you to do `if(var = value)`, which we will need to block.

**Comment by PKPenguin321** [comment]
What will this do? Just curious

**Comment by lzimann** [comment]
`A new appearance flag, PIXEL_SCALE, has been added that will allow you to upscale icons without the default bilinear sampling for a more pixelated look.`
From [byond 511.1375](http://www.byond.com/docs/notes/511.html)

**Comment by Iamgoofball** [comment]
can we get some comparison pics

**Comment by chanoc1** [comment]
oh shit, ive been waiting for this

**Comment by AnturK** [comment]
With PIXEL_SCALE on the left, without on the right.

**Comment by chanoc1** [comment]
looks really goood!

**Comment by Iamgoofball** [comment]
HOLY SHIT

**Comment by MrStonedOne** [comment]
comparision pics should look exactly the same for both. clone the mob using the vv drop down and re-upload the pic

**Comment by MrStonedOne** [comment]
You can shim this into to working on 510 (and on earlier versions of 511) by doing a `#ifndef` and then defining it to `0`

**Comment by RemieRichards** [comment]
with Lummox's fix for the ```=``` thing being done now, there's no need to shim, we can just move forward to 511

**Comment by Cyberboss** [comment]
orly, well then

**Comment by MrStonedOne** [comment]
the `=` fix isn't live.

**Comment by Cyberboss** [comment]
I think we can manage until then

**Comment by RemieRichards** [comment]
@MrStonedOne but he has written it, and done it, as he said.

**Comment by AnturK** [comment]
I'll grab 1:1 picture.

**Comment by MrStonedOne** [comment]
alright, so all you have to do is shim this in using an #ifndef and it should be good to go

**Comment by RemieRichards** [comment]
I'm especially happy it fixes limb seams.

**Comment by AnturK** [comment]
I'll close it for now. I believe in lummox "soon" this time. If there won't be anything new next week i'll shim and reopen this.

**Comment by RemieRichards** [comment]
One moment

**Comment by RemieRichards** [comment]
Right, now we need a third maintainer to do the merge (since I'm involved now)
@tgstation/commit-access

**Comment by AnturK** [comment]
Oh well. I suppose we can do this now.

**Comment by RemieRichards** [comment]
I figured your worry antur was leaving in the shim when we wouldn't need it, so I just made it shout it's existence.

**Comment by AnturK** [comment]
Maybe we should put all these version compatibility changes in a seperate file/directory. Then again we don't have that many.

**Comment by RemieRichards** [comment]
I *WAS* actually going to do it half way through the definition for atom movables, I wanted it to be as gross as possible to encourage its removal, but I couldn't be bothered just in case it didn't compile right (cos you know byond)

**Comment by duncathan** [comment]
well idk how this works but it's only a few lines and two maintainers did it so

**Pull request merged**
