### PR TITLE
Adds a spraycan to robotics

### PR DESCRIPTION
**Pull request by Profakos**
## About The Pull Request

This PR adds a single spraycan to every roboticist office, and a screentip that should tell the player that they can restyle augments with it, should they hover over one. This spraycan has a new sprite, which is a small edit of the existing spray can, just wearing the colours of the roboticist jumpsuit. The can's description also mentions restyling robotic limbs.

image

This PR also fixes a bug: Peg limbs also brought up the restyling menu, albeit, every radial button was empty, and clicking on one runtimes. Now you can no longer do such a thing.

Future improvement: perhaps making augment restyling cheaper would be nice, but I did not want to add that into this PR.

## Why It's Good For The Game

This is a rarely used feature, some folks thought it has been removed when the augment painter has been removed from the game. Putting it in front of the players will make it used more often, and might result in new augment styles.

## Changelog

:cl:
add: Adds a roboticist spraycan, and adds one of them to robotics on every map
qol: adds a screentip to spraycans that tells you that it can restyle robotic limbs
fix: fixes peg legs bringing up the augment restyle menu
/:cl:

### CODE REVIEW

**Comment by necromanceranne** [comment]
I kept forgetting to do this myself, nice.

**Comment by scrunklershrungle932** [comment]
imo this spraycan looks very syndicate-y

**Comment by AdipemDragon** [comment]
finally won't have to run off halfway across the station to get my colored prosthetics whenever i do get the chance to

**Comment by Loafin34** [comment]
could you instead make it the color of the robotics labcoat?

**Comment by Profakos** [comment]
On retrospect, the colour is indeed too syndicate-y. But I actually did consider the roboticist labcoat, but it looked like that it is the same as the scientist labcoat. Maybe I could colour it after the base borg instead.

I don't want to add them to the robotics fab in this PR, at first I want to just make the mechanic seen.

**Comment by Profakos** [comment]
I will change the sprite in another PR then.

**Pull request merged**
