### PR TITLE
Resprites the spoon!

### PR DESCRIPTION
**Pull request by Krysonism**
## About The Pull Request

This PR resprites the spoon.
image

## Why It's Good For The Game

The old spoon is very flat and black. Having better looking utensils will compliment the upcoming floydkitchen reworks.

## Changelog
:cl:
imageadd: The spoon has a new  sprite.
/:cl:

### CODE REVIEW

**Comment by maxymax13** [comment]
only a spoonful

**Review by Twaticus — APPROVED** [review]

**Comment by cacogen** [comment]
End of the handle looks strange. Usually a spoon's handle tapers or stays the same size.

**Comment by MrDoomBringer** [comment]
> End of the handle looks strange. Usually a spoon's handle tapers or stays the same size.

have you seen a spoon before
most expand out near the end of the handle
image

**Comment by cacogen** [comment]
You're just making me want to double down on being critical of how it looks. I did the exact same Google search as you to make sure I knew what spoons looked like. Do you not know what taper means or something?

**Comment by MrDoomBringer** [comment]
taper means it gets smaller towards one end! not larger!!

**Comment by MrDoomBringer** [comment]
image
spoon handles don't do this!!

**Comment by cacogen** [comment]
Yeah, I mean the handle tapers towards the spoon end. It's like a teardrop.

**Comment by MrDoomBringer** [comment]
but that's what it's doing in OPs sprite
am I having a stroke

**Comment by cacogen** [comment]
That's not a taper. The handle looks bad, unlike a spoon. The inside of the head looks square rather than round. I am never going to try to couch my criticism again.

**Comment by MrDoomBringer** [comment]
all i know is i've participated in some weapons-grade bikeshedding

**Pull request merged**
