### PR TITLE
>literal rng chance to force a station ending event in botany

### PR DESCRIPTION
**Pull request by Iamgoofball**
lmao what
:cl: Iamgoofball
fix: botany can no longer spam station ending vines
/:cl:

### CODE REVIEW

**Comment by optimumtact** [comment]
kudzu is not very hard to beat, are you serious

**Comment by MoreRobustThanYou** [comment]
greytiders with welders can kill kudzu

**Comment by Iamgoofball** [comment]
See it's not hard to beat but players shouldn't be able to spam it

**Comment by MoreRobustThanYou** [comment]
players shouldn't be able to bomb cloning 30 seconds into the round but they can for 12 TC. (syndiebomb + C4)

**Comment by Iamgoofball** [comment]
That's a traitor item you literal autist
@KorPhaeron why is mrty not banned yet

**Comment by Tlaltecuhtli** [comment]
i ded tag pls

**Comment by MoreRobustThanYou** [comment]
@Iamgoofball codebase-server seperation

**Comment by praisenarsie** [comment]
@MoreRobustThanYou kor is owner of the org...

**Comment by 81Denton** [comment]
Hugbox

**Comment by Iamgoofball** [comment]
Sounds like I need to buff kudzu then

**Comment by optimumtact** [comment]
Please consider this a friendly warning, your PR's must have a properly descriptive title and body content that explains the purpose of the PR.

Your current title and or body content does not meet requirements, so please update it.

**Comment by ExcessiveUseOfCobblestone** [comment]
Why would you buff something you're trying to outright remove? Stop being subversive.

If you want to fix the spam, fix the spam. You have not fixed the spam in this PR, you have outright removed the ability for botanists to spawn it entirely.

**Comment by deathride58** [comment]
Good PR, but holy fuck at least make it a traitor uplink item instead of completely removing it outside of events

**Comment by Jalleo** [comment]
Please close this and bring a rework of Kudzu along with the removal from being a seed chance please. Thanks.

**Comment by DaedalusGame** [comment]
Reminder that a decision was made to not make kudzu a tc item because it's "botany progression"

**Comment by epochayur** [comment]
what happened to "git gud", goof? this shit takes literal seconds to clear

**Comment by davethwave** [comment]
If this gets removed it's better become a traitor item at least and if better buffed.

**Comment by KorPhaeron** [comment]
Basically every department has a way to achieve some horrible station ending event, and our game would be duller without them

**Comment by deranging** [comment]
morerobustthanyou is already permabanned, goofball

**Comment by Iamgoofball** [comment]
@oranges this does explain the changes being made

**Comment by optimumtact** [comment]
Your title:>literal rng chance to force a station ending event in botany
A sane persons title: removes the kudzu seeds event from botany

**Comment by Iamgoofball** [comment]
boring lame title, doesnt get people's attention as to what the actual problem is

marketing 101

**Comment by DaedalusGame** [comment]
your name gets people's attention

marketing 102

**Comment by optimumtact** [comment]
it will also get your pr's closed

**Pull request closed without merging**
