### PR TITLE
Anchoring machines onto tables gives them `IGNORE_TURF_PIXEL_OFFSET_1`

### LINKED ISSUE #87096: wawa xenobiology has a bugged grinder and doesnt have any plasma sheets
### Client Version:

_No response_

### Issue Summary:

the lower grinder on wawastation xenobio is not interactable, and there is no starting plasma unlike all other xenobios

### Round ID:

any

### Test Merge Information:

_No response_

### Reproduction Steps:

see above

### PR DESCRIPTION
**Pull request by Sealed101**
## About The Pull Request
Anchoring machines with `anchored_tabletop_offset` may lead to these machines to visually occupy another turf and, in code, to _kind of_ occupy another turf, when going through `ClickOn()` -> `IsObscured()` -> `get_turf_pixel()`. This PR fixes this by adding `IGNORE_TURF_PIXEL_OFFSET_1` during table mounting a machine, so these checks won't erroneously think a grinder is under a window that's north of the tile the grinder's _actually_ on.

## Why It's Good For The Game

Fixes https://github.com/tgstation/tgstation/issues/87096 (trexter i swear to god don't couple up so many issues on one report)

## Changelog
:cl:
fix: fixed table-anchored machines being inaccessible when there's a window or somesuch visually obscuring their sprite (e.g. wawastation south reagent grinder)
/:cl:

### CODE REVIEW

**Comment by mc-oofert** [comment]
thank god i turned that into a flag

**Comment by 00-Steven** [comment]
To note, this is only an issue due to a previous change to `anchored_tabletop_offset` causing an unintended doubled-up offset of mapped in `pixel_y` and coded in `pixel_z`.
Previously, `anchored_tabletop_offset` would manually set the `pixel_y` value on mapload if something were to be on a table. Now, it instead sets the `pixel_z` value, so tabletop mounted objects don't render below things to the north of them.

However! It seems certain tabletop mounted objects had a `pixel_y` value manually edited in in addition to their `anchored_tabletop_offset`. Under the previous behaviour, this would just get overridden on mapload, but currently this makes it double up both `pixel_z` and the mapped in `pixel_y` offset. This makes it visually offset more than intended, and causes some unintended behaviours.
Annoyingly, the logic we use for checking whether something can't be clicked on uses where it seems to be, using both `pixel_w/z` and `pixel_x/y`, rather than where it _is_ on `pixel_x/y`.

But like, putting aside for a moment that that feels problematic on its own, it's only an issue because of that unintended doubled up offset causing it to exceed a total visual offset of `16`.
If we go into wawastation and remove that erroneous `pixel_y` offset, it's both interactable _and_ renders in front of the window like intended.
image
It's not something caused by `anchored_tabletop_offset` on its own, as the pr body states.

While this _is_ a fix for the broken interactions resulting from this combination, it's a fix for something that shouldn't be as it is in the first place (doubled up offsets from `pixel_y` mapped onto `anchored_tabletop_offset` objects), so I feel _that_ should probably be addressed instead.


### That said!
This _would_ fix similar issues potentially caused if for some reason someone were to set the `anchored_tabletop_offset` of something to `>=16`. This isn't a thing currently, but it would cause such issues if it were.
While I feel like the ideal solution for that would be to decouple the click blocking check from `pixel_z` (as that's supposed to raise it without putting it below things to the north), there's ✨ jank ✨ to be found in there them `pixel_y/z` rendering mines, so like. Yeahhhhhhhhhhhhhhhh.

**Comment by Sealed101** [comment]
mappers use `pixel_y` for offsetting items in maps because that's what the map edit software is using for the offset. also no, those offsets don't stack on mapload and the grinder in this example isn't flinged completely off the table. also also the mapped-in offset used in this particular instance matches the table-mounted offset, and in your screenshot there is no offset whatsoever, so of course it would work even without the flag

**Comment by 00-Steven** [comment]
Sealed.
Please at least check before talking shit to someone just genuinely trying to talk code with you.

### Just Blatantly Wrong

> ~~also also the mapped-in offset used in this particular instance matches the table-mounted offset, and in your screenshot there is no offset whatsoever, so of course it would work even without the flag~~ yeag

This is with the current `anchored_tabletop_offset` and mapped in `pixel_y`, on mapload:
image
This is with the `pixel_y` varedited out such that there is only `pixel_z`, as per my screenshot:
image
THIS is what it looks like with no offsets whatsoever:
image

### Mapload Offset Stacking

> also no, those offsets don't stack on mapload (...)

If we boot up strongdmm to edit out specifically that `pixel_y` offset and let the `anchored_tabletop_offset` do its job:
image
Oh hey it's only offset on `pixel_z`!
In comparison to if we have both, where it stacks as I said:
image

> (...) and the grinder in this example isn't flinged completely off the table.

No, it isn't, that'd be a cumulative offset of 32. In case you don't believe me:
image
And that's also not something I claimed.
But it's at the cumulative offset of _16_, as I said, where it starts mattering for the blocking.

### Mapping Offsets?

> mappers use `pixel_y` for offsetting items in maps because that's what the map edit software is using for the offset.

I am _fully aware_ of mappers using `pixel_y` for offsetting items in maps, but in the case of objects with `anchored_tabletop_offset` it's supposed to do that codewise on its own, and as I said before these both existing at once is a holdover from changes to how this system works.
Before the changes on July 31st that made it use `pixel_z`, `anchored_tabletop_offset` would override any `pixel_y` edits made, and a decent chunk of machines on maps would still have a mapped in `pixel_y` offset- of course, what this was set to wouldn't matter in play, as they'd all get overridden on mapload.

In the case of wawastation xenobiology, this specific `pixel_y` offset has existed since before those edits, and hasn't changed since! This would previously get overridden, though it'd set it to the same value, but now they stack in gruesome ways.
There is no way in which I can call that intentional.

Notably, there were a few with other `pixel_y` offset values, which would previously also all get set to the same `pixel_y` on mapload. Of course, doing that makes sense from a mapping perspective where you can't _see_ that `anchored_tabletop_offset` will apply its own offset.
But yes, it _is_ a problem that the mapping software doesn't recognize `pixel_z` properly, and that it's not necessarily obvious `anchored_tabletop_offset` sets it itself.

**Comment by Sealed101** [comment]
yeah i deleted the comment, i wasn't really trying to talk shit, but i was wrong

**Comment by LemonInTheDark** [comment]
Ephe is correct about the actual issue here.
There's no reason we couldn't implement THIS change but it is a patch rather then a fix, so I am hesitant to do so until we have actually fixed these offsets.
Mappers should ideally not be pixel offsetting things, especially with `pixel_y` for sidemap issues as is demonstrated (layering with the window) though it would be the only way to move something like this around due to how `anchored_tabletop_offset` works.

The fix here is to set `anchored_tabletop_offset` with a macro in repo that also sets `pixel_z`, similar to the `base_pixel_[whatever]` macros. That will prevent this issue from appearing again in future.
Then we just need to find all the edited instances on maps that do this and set then back down to normal levels.

At that point a change like this wouldn't be covering up any existing bugs so you could in theory make it, am not inherently against it either though I question what items need that much shifting.

`pixel_z` mattering for clicks is weird and I know I added it intentionally but it could use re-examining, we will see tho problem for the future

**Pull request closed without merging**
