### PR TITLE
Portals now make sounds

### PR DESCRIPTION
**Pull request by grungussuss**
### New sounds:
https://drive.google.com/drive/folders/1vLoyxY93Qfe_GtCnetkEHLrkGYZ8S7nD?usp=sharing

Demo:

https://github.com/tgstation/tgstation/assets/96586172/2c468ab8-deea-4151-8d66-167b63fdda39

Changes teleporter,gulag teleporter, hand tele, bluespace teleport gun, cultist teleport, experimental syndicate teleporter teleport sounds.
## Why It's Good For The Game
I think sounds are an integral part of immersion and having no cool sci-fi noises for portals really spoils it.
## Changelog
:cl: grungussuss and Virgilcore
sound: portals now have a unique sound to them
/:cl:

### CODE REVIEW

**Comment by EricZilla** [comment]
Super cool!

**Comment by atlasle** [comment]
have you thought about adding a passive hum as well?

**Comment by Sadboysuss** [comment]
> have you thought about adding a passive hum as well?

nah

**Comment by Jacquerel** [comment]
I like these but I think the backwards sound when they despawn sounds a little bit silly

**Comment by VirgilCore** [comment]
> have you thought about adding a passive hum as well?

I considered making a sound for it. If Grungus wants me to make it, I can.

> I like these but I think the backwards sound when they despawn sounds a little bit silly

I think its partly because of Grungus's implimentation of my sound effects. They sound slowed down in game, so i'm going to adjust my closing sound to better accomidate this, and make it sound less like a reversed opening sound.

**Comment by Jacquerel** [comment]
It likely sounds slowed down in the example because frequency variance is enabled- meaning it has a slightly randomised frequency when it is played
This provides a bit of variety if you are likely to hear the sound repeatedly in a short span of time but also does of course make the sound less like how a sound engineer designed it

**Comment by NullDagaf** [comment]
Should make them sound like Portal portals.

**Comment by EricZilla** [comment]
These are super cool

**Pull request merged**
