### PR TITLE
Fixes several issues and a runtime with paper cutters

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request
Was meant to just fix a runtime in the context screentips for papercutters but now I've got several things fixed:
- Fixes context tips runtiming 
- Fixes some context tips that just didnt ever appear
- Fixes the icons not updating when removing papers/blades
- Moves the blade to an overlay
- Adds a list of blocked paper types that don't fit: paperslips, NSpect inspections, calling cards, pamphlets, and sparring contracts
- Fixes papers and blades not actually removing when removed
- Fixes being able to add papers when one is already inside

## Why It's Good For The Game
Fixes

https://github.com/tgstation/tgstation/assets/76465278/c30127d3-24b0-4a1d-8272-76af68b24469

## Changelog

:cl:
fix: fixed the context tips on papercutters
fix: fixes papercutters not properly updating their icons, removing their stored papers/blades, and eating papers when one is already stored
/:cl:

### CODE REVIEW

**Comment by ZephyrTFA** [comment]
The reason it wasn't setting blade and paper to null is because I used Exit instead of Exited by mistake. Please fix that instead of manually setting to null.

**Comment by ZephyrTFA** [comment]
gee thanks github, that wasn't the button I pressed but I guess it's too late now

**Comment by ZephyrTFA** [comment]
@OrionTheFox the arguments for Exited are wrong it should be (a/m/leaving, a/new_loc) can you fix that

**Comment by OrionTheFox** [comment]
> @OrionTheFox the arguments for Exited are wrong it should be (a/m/leaving, a/new_loc) can you fix that

on it

**Comment by OrionTheFox** [comment]
https://github.com/tgstation/tgstation/pull/76153

> @OrionTheFox the arguments for Exited are wrong it should be (a/m/leaving, a/new_loc) can you fix that

**Pull request merged**
