### PR TITLE
Energy Weapon Touch-up: Thermal Pistols Rework, X-01 Multiphase new shot type, DRAGnets are just gone 

### PR DESCRIPTION
**Pull request by necromanceranne**
## About The Pull Request

DRAGNets are just gone. In their place are thermal pistol holsters.

The bola snare trap...thing they did is now on the X-01 MultiPhase, or the HoS' special gun. He has four shot types now. He sure is special. The snares do 30 stamina damage, similar to a stamina shot, but the shot itself does no damage. The damage is reduced by energy armor. (Does not affect energy bolas)

Thermal pistols now work quite differently. In order to encourage keeping the holster around, and using them as a pair, the gun now recharges automatically after 1.5 minutes. 

However, you can actively recharge the gun by spinning it. Gun spinning is only something you can do with the holster, so you had best have one if you don't want to halve your ammo capacity per gun. 

Per gun, they have less shots (6 shots per reload, 12 between them), but if you reload by spinning, you have effectively doubled your ammo (12 shots per gun, 24 shots overall), and you have more ammo than from before this change (they had about 16 shots each).

In addition, the guns also do the same damage as the laser, and fire on a perfect bead while dual-wielded (they practically do already, it just looks cooler). Yee haw.

## Why It's Good For The Game

This PR touches some weapons that I think could use an update after the length of time they've been in the game.

I do not like the DRAGnet. It is outdated by at least a decade, and has somehow been ignored for quite some time. It used to be a secborg weapon, but somehow ended up being...not a secborg weapon. While the gun itself has an interesting premise, it is mostly used for one reason. It is a normal-sized disabler shotgun you can dual-wield and does about 60 stamina force per blast. That means you can incapacitate most opponents point blank with two of them in a single click the button.

It has a really neat teleport mechanic, but that isn't really utilized compared to it simply being an energy shotgun. It also lets you validhunt quite a bit harder by teleporting your victims to space while they are stunned. It might be a shame to lose this aspect, but honestly I think it is an acceptable loss. 

It also has a trap placing shot, which I think is the neater part of the gun conceptually, and I didn't want to lose that as a cool tool.

I wanted to keep that bit, so I've opted to give it to the HoS' unique gun. He can use it to ensnare people and make getaways easier or trick people in ensnaring themselves. Probably makes him quite a bit more formidable overall, and suits a role meant to be more tactically minded. Or just anyone who happens to have the gun.

Meanwhile, thermal pistols have been interesting but I'm noticing some trends I feel I'd like to resolve a bit. For one, people kind of just ditch the holsters and take the guns. Two, people aren't really thrilled about rechargers being the major way sec keeps up their ammo count on every single energy gun. Three, people really do think the guns aren't worth it on their own because you're not utilizing the special temp interaction, which seems to most (including myself) to be largely gimmicky and not really a selling point.

So I changed them to be more akin to current lasers without just increasing their ammo capacity. They have a cool flip mechanic that lets them keep up. And it encourages keeping them in the holster so you can pull that off. They're also much better in situations where sec lack access or power, which makes them a valuable tool to have in a very desperate holdout situation. The reliance on a holster also means they still effectively occupy the same inventory slots as energy guns and lasers.

A few things; Most of these values I think are subject to change and I honestly wouldn't mind test merging this just to get a feel for it. Are the timers on the flip recharge and actual recharge too short/too long? Is it better if they kept some of their old damage values or ammo capacity? Is the gimmick worth keeping? Should they have a slower fire-rate than the laser? These are the kinds of questions I'd like feedback on.

## Changelog
:cl:
del: The DRAGnet has evaporated. In the armory, there are now thermal pistol holsters.
balance: The HoS' gun now has a trap layer mode, like the DRAGnet did.
balance: Thermal Pistols have been reworked. They now recharge after 1.5 minutes, but can be preemptively recharged through gun spinning (once every minute).
balance: The actual damage values and ammo count has been adjusted to equate lasers slightly better.
/:cl:

### CODE REVIEW

**Comment by JupiterJaeden** [comment]
If you think the DRAGnet energy shotgun mode is unfair, then why not just nerf/remove that instead of removing the item altogether and placing yet another functionality into a gun that is already overcrowded with different modes. 

Also, the snares really do not need to deal stamina damage. I don't think they need to be removed but they are really strong already simply by applying slowdown. No need to buff them.

**Comment by SomeoneYouProbablyKnow** [comment]
Oh this is going to be prime git drama and i'm here for it.

Rip Dragnet, kinda wish the energy snare was still avaliable to beat cop seccies, potentially as a consumable but whatever. The shotgun mode, yeah fuck it, not even balance wise, just it can fuck off.

Don't like the idea of putting it on the hos gun, it'll both confuse more casual players (all 2 casual hos players) and give more power to capital G Gamer hos players (the rest of them)

Self Recharing pistols sound VERY strong. But maybe i'm overvaluing the convenience. At the very least it would make it easier to ignore your own department.

**Comment by SinfulBliss** [comment]
Interesting changes. I think it’s fair to remove the DRAGnet, since it sort of makes e-bolas obsolete. I like the idea of reserving it for HoS instead of whatever officer wants to nab them from armory.

Agree with all the stated issues with the tempguns currently. But not sure about the solutions. Spinning to charge seems a bit unintuitive, like something you’d really need to examine them for or else stumble upon by accident months later. Maybe that’ll be fun though.

The main issue IMO with the thermal pistols is the fact the blue is objectively better than the red because of bleed damage and wounding. Wounding/bigger punch is sorta the reason people chose thermals over laserguns to begin with — and the red thermal pistol will have bigger issues now that laserguns have been buffed for 20 ammo with increased wounding and 25 damage.

With 12 free shots I’d opt to keep a blue one in my bag and just use a lasergun on suit storage. If the ammo was lower - like 8 or so — then I’d run two with the holster since it’d be necessary, but I’d likely chuck the red and run two blue thermals for the juicy wounding.

**Comment by B00tz** [comment]
Hey there Necro could you expand abit on your rational for why thermal pistols need a recharge outside of the rechargers? Energy weapons being tied to them and being unable to "field reload" was a core reasoning for getting rid of the WT.

This fear of someone running around murderboning the station because they don't gotta stop to reload seems like an even bigger issue especially since as you said "fire a perfect bead when duel wield" since now these are 40 burn damage ranged weapons to doom that reload on their own.

**Comment by jughu** [comment]
I think it be better if we made snares act like beartraps security officers could print and set down to reserve the trapping part

Glad the dragnet is gone from that part it was orginally intended to teleport people to a set telebeacon

**Comment by Helg2** [comment]
The fourth mode for hos' gun seems like a problem because in some situations even 3 modes are an issue with fast switching.

**Comment by SinfulBliss** [comment]
It seems to me the main draw with these guns when released were those special temperature interactions — hence “thermal” pistols. But those interactions are super rare so the guns are being buffed to compete without them.

Which sucks because that’s what made them special and unique! It would be way cooler if they were buffed/reworked in a way that brought out their uniqueness.

The most common misconception with these is people think shooting with one triggers the special effect of the other. They think the guns themselves heat/cool people. That makes me wonder: WHAT IF THEY DID? Instead of only working with the tempgun, what if you could alternate shooting red vs blue at someone to heat/cool them, and trigger the special thermal effect with the other gun! I think that’s already how people THINK the guns work and it sounds super cool. Just a thought. Ideally it’d only require 3 shots (like the tempgun) to reach the desired temperature with either gun, and then one to trigger the effect with the other. 

Benefits to this suggestion:
+ You can keep the ammo in each low since the effect more than makes up for less ammo
+ Uniquely different from any other type of gun
+ HUGE benefit to keeping one of each gun instead of scrapping the shitty burn damage one for two cryos
+ Benefit to keeping a holster since it’ll be easier to swap and manage them

**Comment by SomeoneYouProbablyKnow** [comment]
I never actually got the design benefits of that effect, i mean it's COOL, can't deny but it's either a super niche gear punish on people who don't have space equipment OR it's consistent extra damage that you get by alternating shots which is gonna twist the balance around itself and force people to do it

**Comment by moocowswag** [comment]
Just nerf the stamina damage.

If the numbers are too high on an otherwise interesting weapon then the most reasonable thing to do first is to nerf the numbers.

**Comment by ATH1909** [comment]
I am the dragnet's strongest soldier, but I also respect that it's cracked. don't really have a strong opinion one way or the other on this pr.

> Interesting changes. I think it’s fair to remove the DRAGnet, since it sort of makes e-bolas obsolete. I like the idea of reserving it for HoS instead of whatever officer wants to nab them from armory.

dragnets didn't make e-bolas obsolete, imo, as they had an awful range (like, 4 tiles? maybe even 3?) and created a trap for the shooter to accidentally run into if they whiffed while chasing someone

the real money was in the shotgun mode, loved it dearly

> Just nerf the stamina damage.
> 
> If the numbers are too high on an otherwise interesting weapon then the most reasonable thing to do first is to nerf the numbers.

not a bad idea, was actually about to suggest it on discord.


if you do decide to keep the dragnet around, it'd really be nice to have a way to specify which beacon you're teleporting people to, maybe even making the gun not teleport your target at all if no teleporters are pointing at that beacon. cuffing them on teleport would also be nice?

currently, the core concept of the gun doesn't really work because if some space explorer used a space ruin's teleporter to get home, a captain teleported to the AI sat, a borg teleported out of the AI sat, etc., you can end up teleporting someone to the escape lounge or something and basically lose them. you also don't get enough time to cuff them before they're teleported, so unless you can get to sec within 10 seconds or the warden is on the ball and attentive, you can end up just teleporting them into sec with all of their gear still on them, ready to make mayhem.

**Comment by DATA-xPUNGED** [comment]
Interesting that you mention using the Dragnet only as a shotgun and not use the teleport aspect. I've always only really used the teleport

**Comment by CRITAWAKETS** [comment]
the dragnet always felt like the net mode was some sort of oversight, while the snare could fit well as like BEPIS tech but not as proper sec tech.

kind of feel like this isn't really the way of balancing thermal pistols, if anything ammo scarcity should kind of be a drawback to the gun having other new attributes, reinforces a sort of "cowboy ranger" aspect where you have to not miss to get some money shots. With that sort of balancing I'd have gun spinning instead make your next shot stronger for a small interval.

**Comment by DaydreamIQ** [comment]
Yeah I'm not convinced the Dragnet needs to be iced because one person doesn't like it, its an incredibly useful tool and limiting it to being the HoS gun only is stupid. On top of that making a lethal weapon self recharge without locking it behind some kind of tech sounds like a really stupid idea if you want people to be using non-lethals more.

**Comment by YuliceTheDruid** [comment]
None of these people above me have heard of the Advanced Energy Gun

**Comment by SomeoneYouProbablyKnow** [comment]
Why would we ever engange with the trashheap that is the science gameloop? 
Oh no 45 minites into the round you can go on a fetch quest to make a recharging gun, it's over lads guess we should make all guns self recharging shiftstart

**Comment by jughu** [comment]
those 45 minutes loop used to be 8 minutes

**Comment by DrDiasyl** [comment]
Okay how about instead of just deleting DRAGnets, you just:
- Replace them with the subtype that fires only snares, WHICH ALSO ALREADY EXISTS IN THE CODE!

**Comment by necromanceranne** [comment]
> Hey there Necro could you expand abit on your rational for why thermal pistols need a recharge outside of the rechargers? Energy weapons being tied to them and being unable to "field reload" was a core reasoning for getting rid of the WT.

Sure. Since that initial PR, I've had people pretty frequently talk about not liking the recharger loop. I want to find an alternative to that loop. Which means experimenting with some alternative reloading methods and seeing how things shake out. I'd consider much of this as theory-crafting as anything. Which is why it is very value reliant or probably reliant on redrafting entirely. 

The problem wasn't just field reloading. It was unrestricted reloading or just entirely bag space reliant reloading. Since this is now something you can once again experience, I invite you to go get yourself the space WT-550 or alternatively, as a traitor Cargonian, get yourself the WT-550 and ammo crates from the emagged console and just go blasting. Get as much ammo as you can fight in a box. You'll probably have a significantly longer longevity in an individual fight than anyone using energy. I would even argue longer than anyone using these guns while they're in their downtime.

But I can and could A) make them not autoreload on their own and the flip is a one and done for a little bit. This is very possible as it is currently.

B) Increase that timer by quite a bit. I don't want it being too extreme, but I'm conscious that if it is too short it'd be basically just as good as the cap's gun, and if it is too long people won't even be aware that it reloads.

I could also mess with ammo quantities. Either way, all an experiment. It's why I would like to see this testmerged.

> This fear of someone running around murderboning the station because they don't gotta stop to reload seems like an even bigger issue especially since as you said "fire a perfect bead when duel wield" since now these are 40 burn damage ranged weapons to doom that reload on their own.

This is true now really. The guns always had a pretty spot on dual-wield accuracy. A 10 variance wasn't usually enough to divert a bullet past targets where people would be engaging for the majority of cases, just really long range shots.

**Comment by necromanceranne** [comment]
> the dragnet always felt like the net mode was some sort of oversight, while the snare could fit well as like BEPIS tech but not as proper sec tech.

Since I've had even maints not necessarily happy with the net on the HoS gun, this might honestly not be a bad idea as an alternative. I put it on the HoS gun as A) I think the draw IS the large number of shot choices and B) I felt it fit their flavour well.

But as Waltermelon pointed out to me, the snares aren't terribly intuitive, and it wasn't obvious that this was how they were meant to be utilized.

As for the alternative spin mechanic....actually, it does give me a cool idea for how I replace the spin to reload if that's not going to pan out. I'll shoot it to ya if you're interested.

**Comment by SomeoneYouProbablyKnow** [comment]
I think the HoS Gun being so versetile is fun, the only problem is that it would be clunky to cycle between 4 modes (Blame combat speed). 

You could (and this is a large undertaking) change the whole UX of the HoS-Gun, maybe make those mods external, like clips or power cells that you put in the gun, or change the ui more customizable, so you can set your two prefered modes with an alt click or something and then quickly switch between them with Z. 
Essentially make it more customizable in some way instead of springing all those modes and mechanics on all hos players

**Comment by necromanceranne** [comment]
There are a couple of things I'm thinking about with it. I'm not even sure if it'll survive to the end of this PR's feedback cycle tbh :U

**Comment by SomeoneYouProbablyKnow** [comment]
I mean i'm not a fun of recharging thermals but it's something that would really benefit from a testmerge, we can guesstimate all we want but hard data is hard data

**Comment by necromanceranne** [comment]
My thoughts precisely. If this doesn't work, that's okay too.

**Comment by jughu** [comment]
I felt iffy about the hos gun having snare body i feel like this would fit better as a printable traps for area holding or trapping if you get chased(like some people do with beartraps)

**Comment by CCC23** [comment]
> Okay how about instead of just deleting DRAGnets, you just:
> 
> * Replace them with the subtype that fires only snares, WHICH ALSO ALREADY EXISTS IN THE CODE!

fuck snares

**Comment by TheVekter** [comment]
I'm not a fan of adding yet another mode to the HoS' pistol. I'd rather it be a separate gun than another thing that has to be tracked on that.

Also, do the thermal pistols still retain the temperature mechanic? I quite liked that.

**Comment by ChungusGamer666** [comment]
This should probably be cut into two separate PRs, one for the dragnet removal and another for the thermal pistol buff.

**Comment by EricZilla** [comment]
For folks talking bout the dragnet teleport being unreliable, I think it would be cool if the crate came with a dragnet beacon they could sync to, so you can set up a gay baby jail that multiple nets can use, or simply allow you to use the dragnet on any beacon to sync it

**Comment by jughu** [comment]
> For folks talking bout the dragnet teleport being unreliable, I think it would be cool if the crate came with a dragnet beacon they could sync to, so you can set up a gay baby jail that multiple nets can use, or simply allow you to use the dragnet on any beacon to sync it

that got removed because that just ended being teleported into a no2 filled room that was closed off

**Comment by DATA-xPUNGED** [comment]
> For folks talking bout the dragnet teleport being unreliable, I think it would be cool if the crate came with a dragnet beacon they could sync to, so you can set up a gay baby jail that multiple nets can use, or simply allow you to use the dragnet on any beacon to sync it

you know that the teleport teleports you to where the Teleporter in the teleporter room is setup, right?

**Comment by necromanceranne** [comment]
Very real possibility this pr is going to be atomized if and when I do some reworking on the concepts. But whatever I do in the dragnet pr, the thermal pr is always going to replace them in the armory as a part of its changes.

**Comment by Kendrickorium55** [comment]
i dont normally comment on the github anne but all i can tell you is that my dragnet is literally the only reason i ever survive past half an hour when i'm captain

words cant get you out of every situation and having a handy insta slow snare device has saved my life more times than rounds i've played.

**Comment by Loafin34** [comment]
^

you have the telescopic baton. you also have a hand teleporter, 20 damage sabre, and a hellfire laser that self-recharges. why you now need a dragnet that slows people to a crawl from one hit is beyond me.

**Comment by CCC23** [comment]
> i dont normally comment on the github anne but all i can tell you is that my dragnet is literally the only reason i ever survive past half an hour when i'm captain
> 
> words cant get you out of every situation and having a handy insta slow snare device has saved my life more times than rounds i've played.

skill issue

**Comment by Nidvex250** [comment]
My two cents. 
as you stated the shotgun blast teleporter thing is pretty dumb and I agree that it should be rebalanced or simply removed.
The snare however I found to be a lovely tool I can pull out and lay a quick trap with that has benefited me enough times to like it, so I'd definitely like if we kept the dragnet with simply the snare feature.
Otherwise, the Thermal Pistol rebalance intrigues me. Having to do a neat trick with the hostler gives energy weapons an option to even the playing field a little against kinetic weapons and their ability to carry an armory's worth of ammo in their bag to reload on the fly.

**Comment by Kendrickorium55** [comment]
> ^
> 
> you have the telescopic baton. you also have a hand teleporter, 20 damage sabre, and a hellfire laser that self-recharges. why you now need a dragnet that slows people to a crawl from one hit is beyond me.

because all of those situations initiate or escalate retaliation
one or two snaps of the dragnet instead, i walk away, situation is resolved
not everyone plays this to use all their deadly toys whenever they can

**Comment by SomeoneYouProbablyKnow** [comment]
You being a sane person is not an argument against trying to fix systems and items that people ARE abusing.

Now it's generally fucked up how using all your deadly toys is the path of least resistance in a game that is ostensibly not about that but... what can ya do

**Comment by SkeletalElite** [comment]
Just remove the shotgun blast mode from the dragnet, HoS gun is already a pain to mode cycle with just 3 modes, 4 will be a nightmare.

**Comment by necromanceranne** [comment]
Gonna close this for now since I'm gonna be redoing it from the ground up and atomizing, it can still be testmerged while closed. I think I got a lot of cool ideas and opinions, thank you for sharing them with me.

**Comment by OverwatchVoice** [comment]
I'd also be inclined to just removing the shotgun blast mode from the DRAGnet (Or the snares too, if those are too strong)
Using the teleportation mechanic on dragnets rarely comes into play, but was incredibly unique, and required a lot of preparation on security's part (Even if it's really clunky on deciding which teleport to actually use).

In my opinion, removing it outright would be a shame.

**Comment by Kendrickorium55** [comment]
> You being a sane person is not an argument against trying to fix systems and items that people ARE abusing.
> 
> Now it's generally fucked up how using all your deadly toys is the path of least resistance in a game that is ostensibly not about that but... what can ya do

yeah, i'm completely fine with the shotgun teleporting mode getting iced, as its caused way more problems than its solved
like another said though, it IS an incredibly unique mechanic to the dragnet
it would probably be a good idea to separate them into two devices maybe? 
leave the dragnet as a snare gun in the armory and maybe open up the other function if its emagged? or it could just be a traitor weapon.

lot of things we can do with it, I think

**Pull request closed without merging**
