### PR TITLE
Track admin observer time

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
For the record I hate this idea because I don't want to clock in for my pretend job but a head admin requested it

Someone who is smarter than me (Ned) will still need to make this easily readable from the database on the stat tracking site

### CODE REVIEW

**Comment by nervere** [comment]
They do it for free!

**Comment by MrStonedOne** [comment]
Its not, the proper way would be to make a mob/login version of the connection table, that records login/logout times for each mob type

**Comment by MrStonedOne** [comment]
or to add a roles log table

**Comment by Aloraydrel** [comment]
Does this mean I get overtime

**Comment by Magikarpet** [comment]
tfw no preemptive logging so i'll get harrassed for wanting to play instead of admin now

**Comment by nfreader** [comment]
Role time table should be replaced with a new table that logs datetimes as well. As it stands that data is only useful for aggregating total time spent as a role over all time.

**Comment by Durkel** [comment]
>When you get no perks for volunteering to administrate an online game about clowns and magic space gas while putting up with some of the most autistic people on the internet isn't enough so they start to log your hours to see how much time you're wasting doing nothing so they can try to take away your no perk job as "punishment" only to have them later wonder why no one wants to be an admin.

**Comment by CitrusGender** [comment]
tbh I have no reason to deadmin anyone over these results or anything like that.

Any belief that this will be used for corrective action is just gossip and it's more to show who is putting the hours in.

**Comment by Shadowflame909** [comment]
I bet nabski has the most admin observe time. Does he ever sleep.

**Comment by optimumtact** [comment]
mrstonedone is right, this is the incorrect approach. It needs it's own table

**Comment by KorPhaeron** [comment]
Alright

**Comment by MrStonedOne** [comment]
No, keep this, I'll make a role_log table that records changes. or better yet i could even farm it off to the dbms as a trigger

**Comment by KorPhaeron** [comment]
@tgstation/commit-access 

MSO said he is ready for this to be merged now

**Review by Cyberboss — APPROVED** [review]

**Pull request merged**
