### PR TITLE
Advanced surgeries are directly downloaded from the operating computers instead of using disks

### PR DESCRIPTION
**Pull request by XDTM**
:cl: XDTM
tweak: Operating Computers can now sync to the research database to acquire researched surgeries, instead of requiring installation by disk.
add: You can now review the full list of unlocked surgeries from the operating computer.
/:cl:

Removes needless back-and-forth with surgery disks, making advanced surgery a bit less annoying to set up.
Disks still work to install surgeries locally, although the only disk currently obtainable is the traitor brainwashing disk.

### CODE REVIEW

**Comment by Cyprex** [comment]
Having brainwashing listed in a menu leaves behind significant permanent evidence, is anything done about this?

**Review by SpaceManiac — CHANGES_REQUESTED** [review]
Functionality looks fine but I should point out that the surgeries no longer have an icon and are therefore not visible in the R&D console anymore.

Best way to fix this is probably to add `icon_path` or something to `/datum/design` alongside `build_path` and use it if it's set in `/datum/asset/spritesheet/research_designs/register()`.

**Comment by SpaceManiac** [comment]
Stale; ping a maintainer for re-open.

**Comment by XDTM** [comment]
@SpaceManiac added a system to replace icons in techwebs and fixed the conflicts

not sure why they aren't showing up here

**Comment by ishitbyabullet** [comment]
If the disks only cost metal and glass then that's fine.

If disks cost other materials like gold and such then I don't think you should remove disks.

**Review by SpaceManiac — APPROVED** [review]
Works in testing

**Pull request merged**
