### PR TITLE
Xenobio Slime Extract Nerfs

### PR DESCRIPTION
**Pull request by hyperjll**
Oil, Adamantine, Orange, and Gold slime extracts require 15 units of liquid plasma (up from 1 unit) to activate their plasma reaction. Yellow requires 15 units of blood to activate a blood reaction (up from 1 unit). Gold slime extracts spawn 4 hostile mobs (down from 5) during a plasma reaction. Yellow slime extracts have an EMP range of 5 (down from 7) during a blood reaction. Oil slime extracts have a 1,2,4 explosion range (down from 1,3,6). All of this is to compensate for xenobio effectively being sped up by 3x from a previous PR i made. Adamantine golem shells require 3 (up from 1) adamantine sheets to make.

(https://github.com/tgstation/tgstation/pull/84278)

## About The Pull Request

In the comments of the previous PR, a rather good point was made about how spamable a certain few of the extracts were, and i've taken the liberty of making a few nerfs to compensate.

## Why It's Good For The Game

Increasing the plasma cost of certain slime extracts to fifteen likely won't slow anyone down from using them, but it does ensure the user will drain their plasma supply quickly and limit how many slime cores they can use. Of course, restocking plasma isn't super difficult in xenobiology alone but it WILL ensure both downtime between assaults as the user will seek out a grinder for liquid plasma and force the user to spend time stocking up on plasma in the first place.

If that wasn't enough, i took the liberty of nerfing Gold, and Oil plasma reactions, also after some thinking, Yellow blood reactions. We also don't want golem armies (as fun as that was to fight).

Having an abundance of monster parties, explosive grenades, or emp grenades is likely frustrating to deal with, so more nerfs were necessary.

## Changelog

:cl:
balance: Due to selective breeding of slimes, some species require roughly 3x more plasma than normal to activate a plasma reaction. Slime extracts affected are: Oil, Adamantine, Orange, and Gold. Yellow slimes require 3x more blood to activate a blood reaction.
balance: Oil slime extracts have become less potent during a plasma reaction due to selective breeding conditions.
balance: Gold slime extracts give rise to one less monster during a plasma reaction due to selective breeding conditions.
balance: Yellow slime extracts have become less potent during a blood reaction due to selective breeding conditions.
balance: Adamantine golem shells require 3 sheets rather than 1, due to unknown circumstances.
/:cl:

### CODE REVIEW

**Comment by Livrah** [comment]
Good change. Xenobio has a lot of more interesting things to do, but people just spam cores instead of making extracts, because how easy it it.
I'd make gold core with plasma spawn only 1-2 hostile mobs. It takes full lasergun charge to deal with 1! core spawn, and spacemans usually don't have laserguns.

**Comment by carlarctg** [comment]
> Why though? As if xenobio wasn't tedious enough. Stripping even more potential from its combat capabilities will further cause the decline or need to actually do xenobio. I sure love sitting and working on something that takes the whole shift to get something useful out of only for the shuttle to get called (aka waste the entire round for yourself) and I sure do love when something I put the entire shift to work on is completely useless in combat (that's literally the only incentive to do xenobio, getting powerful toys to play with)

 He just fucking said he made a merged PR to make it less tedious my dude. It vastly speeds up slime split speed. Read before you comment

**Comment by carlarctg** [comment]
Changes are good though the emp range thing is effectively meaningless, almost a buff that reduces collateral damage. I really like the conservative method of increasing reagent activation cost in 1-15u, it's a smart way to handle it

**Comment by carlarctg** [comment]
image

**Comment by moocowswag** [comment]
200 golems just took a rev round hostage and the round was arbitrarily delayed by 20+ minutes because the revs were reliant on golems and the golems are no longer space immune so the result was the heads of staff hid in the ruins of the brig which was bombed where it was a vacuum

Meanwhile most of the revs and golems afkd on the shuttle or at evac

**Comment by hyperjll** [comment]
> 200 golems just took a rev round hostage and the round was arbitrarily delayed by 20+ minutes because the revs were reliant on golems and the golems are no longer space immune so the result was the heads of staff hid in the ruins of the brig which was bombed where it was a vacuum
> 
> Meanwhile most of the revs and golems afkd on the shuttle or at evac

Yes i participated in that round. Considering making golem shells cost 3x more adamantine too.

**Comment by Skebulba** [comment]
Making the extracts requite 15x more plasma will only make the xenobiologists use 15x more plasma to the detriment of the entire station.

**Comment by hyperjll** [comment]
> Making the extracts requite 15x more plasma will only make the xenobiologists use 15x more plasma to the detriment of the entire station.

Unless the xenobiologists use metal extracts or dark purple extracts.

**Comment by ZeroKelvn** [comment]
Considering automated plasma farming was essentially gutted by recent changes to plumbing grinders, this suddenly has a lot more meaning

**Comment by Xkallubar** [comment]
If this pr is merged we better get extended capacity droppers.

**Comment by hyperjll** [comment]
Updated, golem shells require 3x more adamantine for their shells.

**Comment by carlarctg** [comment]
> If this pr is merged we better get extended capacity droppers.

We do! They're called 'syringes'

**Comment by moocowswag** [comment]
Rainbow extracts

**Comment by hyperjll** [comment]
> Rainbow extracts, they take longer to get but once you get rainbow slimes splitting its not long until they become the round hostager.

How so?

**Comment by hyperjll** [comment]
This is... taking a while to get merged.

**Comment by Metekillot** [comment]
> This is... taking a while to get merged.

you must be new here

**Comment by Mothblocks** [comment]
> You currently have a negative Fix/Feature pull request delta of -10. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

**Comment by moocowswag** [comment]
This is a followup pr to fix/counter an unintended side effect of their last pr

**Comment by hyperjll** [comment]
> > You currently have a negative Fix/Feature pull request delta of -10. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

This is a sister PR to https://github.com/tgstation/tgstation/pull/84278

**Comment by adamkad1** [comment]
> > You currently have a negative Fix/Feature pull request delta of -10. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

Damn this is the first time I see anyone actually give a damn about this

**Pull request merged**
