### PR TITLE
Adds more box types to cardboard crafting

### PR DESCRIPTION
**Pull request by Derpguy3**
## About The Pull Request
5 more box types have been added into the cardboard's sheet crafting of "fancy boxes".
Specifically includes the following boxes;

- Drinking glasses
- Paper cups
- Medical gels
- DNA Injectors
- Cigar cases (The normal brown one)

Also fixes a typo involving the "perscription" glasses box.
## Why It's Good For The Game
When I've played as a bartender, I've found it quite annoying that I couldn't make a labeled box for spare drink glasses.
Adding these boxes will allow people to make those labeled boxes and use them for whatever they need. (Organizing!)

Also, if those boxes exist for use, why not let them be craftable by the player?
## Changelog
:cl:
qol: Additional box types can be crafted from cardboard. Happy organizing.
spellcheck: A typo in box crafting for prescription glasses has been fixed.
/:cl:

### CODE REVIEW

**Comment by Loafin34** [comment]
add cigar box

**Comment by scrunklershrungle932** [comment]
why can the cigar case be crafted with cardboard?  I thought it was wooden

**Comment by Derpguy3** [comment]
> why can the cigar case be crafted with cardboard? I thought it was wooden

I did some testing with the cigar cases earlier and I found they fold down into cardboard when empty.
Figured since you get cardboard from it, might as well be able to turn the cardboard back into a case too.

**Comment by scrunklershrungle932** [comment]
> > why can the cigar case be crafted with cardboard? I thought it was wooden
> 
> I did some testing with the cigar cases earlier and I found they fold down into cardboard when empty. Figured since you get cardboard from it, might as well be able to turn the cardboard back into a case too.

ah, alright.  makes sense then.  thanks for explaining

**Review by Ghommie — APPROVED** [review]

**Pull request merged**
