### PR TITLE
SSD Ethereals won't take tox damage based on their charge level

### PR DESCRIPTION
**Pull request by GuillaumePrata**
## About The Pull Request
Just a client check before applying the tox damage that ethereals take.

## Why It's Good For The Game
Playing at medbay and having to deal with SSD Ethereals is a chore and all the options you have are just bad:

1- Babysit them a lot if you want to be nice and keep them healthy in case they reconnect.
2- Slap them into a stasis bed.
3- Hide them in a corner and ignore the crew member at death's door.
4- Other more complicated strategies, like changing their stomach.

The third option is what happens on most rounds, but even that is annoying as you will have this near dead crewmember showing on the crew monitor, unless you strip them to disable their suit sensors but that brings other issues...

With this change, an SSD ethereal will be starving, depressed and will quickly take toxin damage when they reconnect so it is not removing one of their cons, but will end the need to babysit SSD ethereals.

## Changelog

:cl: Guillaume Prata
balance: Ethereals won't take Tox damage (but will still starve) based on their charge if they are SSD.
/:cl:

### CODE REVIEW

**Comment by zxaber** [comment]
Not that this is a bad idea, but how is it different to plasmamen and their plasma tank requirement?

**Comment by GuillaumePrata** [comment]
A need for breathable air (or plasma) is universal.
But the bad part would be that trying to add a system like this for plasmamen would be quite messy, do they stop breathing if they go SSD? Do they just don't take suffocation damage?

For Ethereals it is simple, and they don't actually die if they starve, it has a cap on how much toxin builds up.

**Comment by wesoda25** [comment]
I was under the impression that the easy toxin damage was the way of balancing the energy diet system. It's odd to me to completely exempt afk ethereals from this. Instead I think it'd be better to find a way to mitigate charge reduction, at the cost of mobility/something similar that afk folks don't need, but active players do.

**Comment by GuillaumePrata** [comment]
> the above comment doesn't make sense to me.

What part exactly?

> Completely exempting afk ethereals from a definitive part of their gameplay experience

I would not call taking damage while AFK a definitive part of a species gameplay.

They will still lose their charge and starve but will only start taking tox damage once they reconnect.
Tox damage that takes 2 minutes to cap. By the time they finish recharging they will already have enough tox damage to force them to go look for healing just like they did before.

> how long does an ethereal at full charge have until they begin to take damage 

33 minutes if they are at the cap of being full.

> and then die?

They simply can't die to the tox damage from starving, it will stop damaging them when they have 10 HP.
The only way to die "from the tox damage" is if you cap it at 90 damage and then something else harms you after that.

**Comment by LemonInTheDark** [comment]
I do not like this, if the issue is handling ssd ethereals we should give med more tools to do that. I generally really dislike ooc changes like this, we're a sandbox and all.
Do you have permission for this species change?

**Comment by GuillaumePrata** [comment]
> I do not like this, if the issue is handling ssd ethereals we should give med more tools to do that.

That still would be babysitting someone that might never reconnect, even with better means I don't think it would fix the issue.

> I generally really dislike ooc changes like this, we're a sandbox and all.

It's already an OOC issue because a player disconnected and now you either babysit or soft griefs them hoping they don't reconnect. It is the simple way to fix this.

> Do you have permission for this species change?

As I seen this as QoL change for medbay I didn't want to bother maintainers. I wasn't going to label this as QoL tho, it feels pretty scummy.
This won't change things for the ethereals themselves because it takes up to 33 minutes (probably half that on average) for them to start taking damage and if they didn't reconnect at that point they often won't.
It will change things for medbay as SSD ethereals are common, a lot of them just leave if they roll a bad trauma and you can't know if it was a rage quit or internet issues.

**Comment by LemonInTheDark** [comment]
I am not happy with this solution. I feel like your solution is making consumption vary with activity, or giving medbay more tools for this problem or whatever.

I realize why you want to fix this, it's this weird like midway obligation and it's a crummy position to put people in, but I do not like this method of accomplishing it. Too gamey

**Pull request closed without merging**
