### PR TITLE
Fixes not being able to install airlock electronics and card readers in closets

### PR DESCRIPTION
**Pull request by grungussuss**
## About The Pull Request
Fix
## Changelog
:cl: grungussuss
fix: fixed not being able to install airlock electronics and card readers into closets
/:cl:

### CODE REVIEW

**Review by 00-Steven — CHANGES_REQUESTED** [review]
Lack of description as to what the issue was and how it's fixed in the pr body led me to check out what was changed in more detail.
Here's a spreadsheet comparison of the old and proposed new behaviours for installing and removing airlock electronics and card readers.
image
Where `FALSE` means the proc returns early, and `TRUE` means it continues.
For good measure, I also booted up a local instance of the proposed new code and my own dev instance, and confirmed the noted behaviours.

As the spreadsheet shows, we were already capable of both adding and removing card readers and electronics, though if the locker _could_ be welded they required the locker be welded first.
So I don't believe "Fixes not being able to install airlock electronics and card readers in closets" is a correct description of this pr.

### The Actual Code

For posterity's sake, onto what the proposed new code actually does.
It instead makes it so:
- You can only add or remove airlock electronics while the closet is not welded.
- You can only add or remove card readers while the closet is both weldable AND not welded. You flat out cannot put card readers on closets or crates that are not weldable.
- Card reader and airlock electronics' installation/removal behaviours are now inconsistent.
- You cannot remove airlock electronics without first removing the card reader.
- Context is updated to match this. (Good)
- Attempting to put a card reader or airlock electronics into an open closet/crate instead attempts to install it.
- VVediting a closet to change its `can_weld_shut` value will always unweld it if welded, even if setting is to `TRUE`.

### The Takeaway/TL;DR

Putting the minor issues aside for a bit, this does not seem like a fix, just a behaviour change.
If these changes are intentional, I would suggest changing the pr title/body to reflect the changes you're actually making and why, and re-poking my ass for a proper review. o7

**Comment by Sadboysuss** [comment]
> Lack of description as to what the issue was and how it's fixed in the pr body led me to check out what was changed in more detail.
> Here's a spreadsheet comparison of the old and proposed new behaviours for installing and removing airlock electronics and card readers.
> image
> Where `FALSE` means the proc returns early, and `TRUE` means it continues.
> For good measure, I also booted up a local instance of the proposed new code and my own dev instance, and confirmed the noted behaviours.
> 
> As the spreadsheet shows, we were already capable of both adding and removing card readers and electronics, though if the locker _could_ be welded they required the locker be welded first.
> So I don't believe "Fixes not being able to install airlock electronics and card readers in closets" is a correct description of this pr.
> 
> ### The Actual Code
> 
> For posterity's sake, onto what the proposed new code actually does.
> It instead makes it so:
> - You can only add or remove airlock electronics while the closet is not welded.
> - You can only add or remove card readers while the closet is both weldable AND not welded. You flat out cannot put card readers on closets or crates that are not weldable.
> - Card reader and airlock electronics' installation/removal behaviours are now inconsistent.
> - You cannot remove airlock electronics without first removing the card reader.
> - Context is updated to match this. (Good)
> - Attempting to put a card reader or airlock electronics into an open closet/crate instead attempts to install it.
> - VVediting a closet to change its `can_weld_shut` value will always unweld it if welded, even if setting is to `TRUE`.
> 
> ### The Takeaway/TL;DR
> 
> Putting the minor issues aside for a bit, this does not seem like a fix, just a behaviour change.
> If these changes are intentional, I would suggest changing the pr title/body to reflect the changes you're actually making and why, and re-poking my ass for a proper review. o7
> 
> 
> 

I tried adding card readers and airlock electronics ingame and couldn't add them or pry either. Have you tested this on master?

**Comment by Sadboysuss** [comment]
> You cannot remove airlock electronics without first removing the card reader.

You cannot add a card reader without adding airlock electronics first so it doesn't make sense to be able to remove airlock electronics before removing the cwrd reader.

**Comment by Sadboysuss** [comment]
you're right, what I'm trying to do is something else, I'll reopen with a different pr

**Pull request closed without merging**
