### PR TITLE
Updates the free golem ship

### PR DESCRIPTION
**Pull request by EuSouAFazer**
## About The Pull Request

The free golem's ship now looks a lot better. They also got a lot more stuff so they can do a lot more whatever - they gained fishing equipment, a griddle, a harmonica and a bunch of other "go do whatever" things so they can do more whatever and less beeline for the station and fuck the round.

## Why It's Good For The Game

By the love of god stay in your ship doing whatever and don't go up the station I beg of you

## Changelog
image
image
image
image

:cl: Fazzie
add: The free golem ship has been swapped for a much better one, with fishing equipment.
/:cl:

### CODE REVIEW

**Comment by carlarctg** [comment]
Wow it actually looks like a ship instead of whatever the heck it was before. Great job!

**Comment by gueba14** [comment]
I like that someone actually cares for gosth roles like free golem, i stead of trying to get the out or crush them

**Comment by SyncIt21** [comment]
Update your branch with master to restart tests. The map diff bot test has hanged

**Review by Ghommie — APPROVED** [review]
A nice improvement. I don't see why the maptainers haven't merged this before.

**Pull request merged**
