### PR TITLE
Fix the faction for Araneus on Metastation

### LINKED ISSUE #15430: MetaStation's Sergeant Araneus has a string faction
`faction` is a list, this is a bad mapedit.

The following runtime has occured 2 time(s).
runtime error: type mismatch: "spiders" |= "\[mob_102]"
proc name: New (/mob/living/New)
  source file: living.dm,27
  usr: (src)
  src: Sergeant Araneus (/mob/living/simple_animal/hostile/retaliate/bat)

### PR DESCRIPTION
**Pull request by optimumtact**
Fixes #15430

### CODE REVIEW

**Comment by neersighted** [comment]
only the easiest of fixes

**Comment by optimumtact** [comment]
buffing my commit count for that sweet maintainer status

**Comment by KorPhaeron** [comment]
Why isn't Araneus an actual mob in the code if he is used in multiple stations anyway?

Do we have a maintainer ruling on map edit objects yet?

**Comment by optimumtact** [comment]
If you ask me to fix that I'm just going to close the PR

**Comment by Cheridan** [comment]
who knew that having a spider that's actually a bat would lead to retardation down the line 

(everyone)

**Comment by tkdrg** [comment]
yes it is retarded
its also out of scope here nad can be fixed later/by someo ne else

**Pull request merged**
