### PR TITLE
[reopen after freeze] Removes Security and Peacekeeper borgs

### PR DESCRIPTION
**Pull request by Iamgoofball**
# fuck secborgs, they leave now

:cl: Iamgoofball
del: Removes secborgs. Finally. Peacekeepers too.
/:cl:

### CODE REVIEW

**Comment by Iamgoofball** [comment]
whoops sorry feature freeze

**Comment by EricZilla** [comment]
Legally I dont think removal is a feature

**Comment by LemonInTheDark** [comment]
It is

**Comment by oklews** [comment]
aren't secborgs normally unobtainable?

**Comment by Jolly-66** [comment]
> aren't secborgs normally unobtainable?

They're a config option but are disabled on /TG/ primarily due to, being extremely validly, and also law conflicting issues. Probably more but thats the main takeaway I get.

**Comment by D4C-420** [comment]
The sec borgs I can understand but why the peace keepers?

**Comment by KittyNoodle** [comment]
If I cannot be a borg who goes around dispensing cookies and giving people hugs then I cannot live.

**Comment by KittyNoodle** [comment]
I don’t really see the point honestly, sec borgs are unobtainable and hugborgs are adorable and amazing.

**Pull request closed without merging**
