### PR TITLE
sloppily deletes free antag ruin (syndie space ship)

### PR DESCRIPTION
**Pull request by Timonkeyn**
#49597  About The Pull Request

deletes free antag ship

## Why It's Good For The Game

literally free antag, no one needs this. plus no policy, meaning they can invade the station with overpowered gear every. single. round.

## Changelog
:cl:
del: Central command has shot a BSA beam at a syndicate ship, that seems to always appear near our space, completely obliterating it. have a nice day!
/:cl:

### CODE REVIEW

**Comment by Timonkeyn** [comment]
oops. looks like i just deleted the NPCs

**Comment by Timonkeyn** [comment]
ok i think i got it now

**Comment by spookydonut** [comment]
> 
> 
> ok i think i got it now

nope you need to remove the dm from the dme

**Comment by Timonkeyn** [comment]
the ruin isnt spawning like this, does that cause errors?

**Comment by spookydonut** [comment]
tgstation.dme:2830:error: unable to open "code\modules\ruins\spaceruin_code\forgottenship.dm"

**Comment by Timonkeyn** [comment]
i gotchu fam

**Comment by Timonkeyn** [comment]
web editing be like

**Comment by spookydonut** [comment]
code/game/objects/structures/ghost_role_spawners.dm, line 684, column 2:
error: failed to resolve path /obj/structure/fluff/empty_sleeper/syndicate/captain

stop webediting and start actually trying to compile your changes

**Comment by Timonkeyn** [comment]
make me

**Comment by EgorDinamit** [comment]
Maybe wait for admin policy instead? They shouldn't invade station + I'm still balancing stuff so there is no real need in full removal.

**Comment by EgorDinamit** [comment]
You better just wait for official policy from headmins and final version of this ruin.
#50165

**Comment by Timonkeyn** [comment]
does this mean i can just add a busted ruin right next to the station with alotta antag ghost spawns but only on some round and say "just wait for the policy"?

**Comment by Timonkeyn** [comment]
also
>arent supposed to
haha good joke

**Comment by EgorDinamit** [comment]
> does this mean i can just add a busted ruin right next to the station with alotta antag ghost spawns but only on some rounds and say "just wait for the policy"?

Go and try it. Yet, 5 spawners isn't that much. It spawns in a random position in space so it can't be right next to the station whole time.

>also
>arent supposed to
>haha good joke

- Ashwalkers aren't supposed to raid station with no reason, yet they can ghost-scout area to find mining base first and then ruin someone's day.
- Lavaland syndies aren't supposed to leave their base, yet they can walk over 3 tiles of lava without dying and then raid the station.
- Golems aren't supposed to raid the station either, but self-antagging in absence of admins isn't a rare sight.

**Comment by wesoda25** [comment]
Can’t wait for the git ban for your commit name

**Comment by LordSaladin** [comment]
this is a ided so i'll delete it pr.

**Comment by Timonkeyn** [comment]
>this is a ided so i'll delete it pr.

im going to closethe PR if you can unironically explain how you can have fun VSing a bunch of super soliders every round, who can spread fungal TB by the way.

**Comment by EgorDinamit** [comment]
> > this is a ided so i'll delete it pr.
> 
> im going to close the PR if you can unironically explain how you can have fun VSing a bunch of super soliders every round, who can spread fungal TB by the way.

What, fungal TB, excuse me?

**Comment by Timonkeyn** [comment]
in the event hall round before this PR( a families round), there somehow was fungal TB on the station

**Comment by ExcessiveUseOfCobblestone** [comment]
Do it properly off the webbitor silly.

Also you're looking for a gitban that's byond our control when you literally put the N word in your commit.

**Comment by Timonkeyn** [comment]
oh god oh fuck

**Comment by Timonkeyn** [comment]
i cant change it

**Comment by EgorDinamit** [comment]
Banned for N-word.

**Comment by zxaber** [comment]
When I tell players they're not supposed to invade the station, I'm told that they have no idea what else they're supposed to do with the role. There's not an abundance of materials to mine like with golems, nor an abundance of enemies to fight like with Charlie station. 

There was one group that I stopped about moments before they finished a teleporter; their plan was to make and send borgs to fuck with the station. That certainly wouldn't be "abandoning your ship" but is still a bit much to allow for a ghost role spawn.

The role needs more content to be honest. All the gamer gear and they have like, what, five enemies to fight?

PS, Ash Walkers are (were?) actually allowed to invade (again) because they're at a disadvantage to anyone with firearms or glass. It's not the same as a ghost role with syndicate equipment.

**Comment by EgorDinamit** [comment]
@zxaber I believe there is still a way to fix it, and to be honest charlie station xenos are quite easy as enemies. It still needs a lot of polishing, sure, but I'd need some help/feedback to do it.
Most of the rounds(Manuel, Ehall) they actually either have a fight with curators/assistants/(rarely) sec or take all ships in space to their z-level and build something resembling a real station.

Charlie station doesn't have too much to do on it either. If you think about it - it's just a loop: Power, Atmos, Xenos, Singulo. It's really rare to see them even make a singulo engine or AI.

**Comment by optimumtact** [comment]
ok

**Comment by optimumtact** [comment]
and stop putting racist words in your commit messages, if github catches you, you will not be participating on their website any more, it's a violation of their ToS

**Comment by Tharcoonvagh** [comment]
retart

**Pull request closed without merging**
