### PR TITLE
Cargo shuttle takes 15 seconds to arrive instead of 0, compromise

### PR DESCRIPTION
**Pull request by Iamgoofball**
CERTAIN RETARDS seem to think that "lol 2 minute cargo is a good thing!!1!"

obviously these certain retards dont play cargo

so to prevent them I'm gonna cock block their PRs to put it back to 2 minutes with this one which is better because 1. its not instant, and 2. it's not super fucking long

### CODE REVIEW

**Comment by coiax** [comment]
You objected to 30 seconds. And I thought that was low.

**Comment by Iamgoofball** [comment]
30 seconds is way too long. 15 is the maximum it should be. Personally it should be instant but people throw fits over that.

**Comment by xxalpha** [comment]
It should be two minutes. Since when is two minutes too long to wait? You are just encouraging short rounds with this crap.

**Comment by xxalpha** [comment]
If you don't have time to wait two minutes, plan your orders better.

**Comment by francinum** [comment]
>encouraging short rounds

Please, tell me how that makes sense.

**Comment by Iamgoofball** [comment]
Arbitrary time limits are fucking stupid. Fuck off @xxalpha you don't know what you're talking about

re-opening to fix merge conflict

**Comment by ike709** [comment]
15 seconds is fine, cargonians won't need to stand around in the cargo bay jacking off waiting for shit to arrive.

**Comment by AdamElTablawy** [comment]
@xxalpha fuck off right out the door please

2 minute cargo fucking sucks and is the reason nobody played cargo and the round ends about fifteen minutes after cargo gets enough points to order anything with two minute cargo fuck off please

15 seconds is fine i guess

If you disagree please go play cargo for a round and realize it's super fucking annoying and boring and also FUCK OFF

**Comment by xxalpha** [comment]
Go back to feedback.

**Comment by francinum** [comment]
Go back to feedback yourself if you think 2 minutes is a good idea.

**Pull request closed without merging**
