### PR TITLE
Pushes travis testing back to the stable 509 release for now

### PR DESCRIPTION
**Pull request by Incoming5643**
preparing for 510 is fine, but changes that only work in the beta version keep slipping through!

### CODE REVIEW

**Comment by Iamgoofball** [comment]
We need to stop supporting 509.

The game servers all run 510.

**Comment by Shadowlight213** [comment]
@Iamgoofball 510 is the reason why the game servers crash all the time.

**Comment by Incoming5643** [comment]
the game servers are only running 510 because @duncathan 's turf change initially forced them to, he fixed that issue and they can go back to running stable whenever they want and should do so.

It's called stable for a reason.

**Comment by Iamgoofball** [comment]
no, we're running 510 because it has the omega lag fix, you idiots

**Comment by Shadowlight213** [comment]
@Iamgoofball is correct. We are running 510 because of the lagfix. However, the servers crashing literally multiple times per day was traced back to 510. It's possible it got fixed in the latest version however. But still. beta is beta. stable is stable. We shouldn't drop support.

**Comment by MrStonedOne** [comment]
am i missing something, since patching the server to the new byond version, there has only been one mid round crash

**Comment by MrStonedOne** [comment]
all pre-round crashes are minimaps triggering the cleanbot bug, I'm kinda ok with those crashes, as the round was gonna get fucked in some regard anyways.

**Comment by Incoming5643** [comment]
Well regardless of the servers there's no reason we shouldn't support the stable verison on the coding level. If MSO wants to run the beta for performance reasons that's his prerogative. I just think it's good practice to test against the stable instead of the beta.

**Comment by MrStonedOne** [comment]
you don't understand incoming, the "stable" version has a bug that causes it to lag for 1.6 seconds every time atmos has more than 3k active turfs

**Comment by MrStonedOne** [comment]
Like, its literally unplayable

**Comment by Incoming5643** [comment]
I thought my toaster was just choking to death on it.

**Comment by Incoming5643** [comment]
eh ok whatever but I still don't want to see needless 510 stuff until it goes stable :cop:

**Comment by coiax** [comment]
If Travis is testing for 510, but the coders are screening for 509 compatibility then this issue is going to keep happening. Build testing is supposed to screen this shit out, so it doesn't get merged in the first place. If we're going to speed revert something because it fails to build, maybe that should be flagged in the travis CI

**Pull request closed without merging**
