### PR TITLE
Adds various new stuff to ion law list.

### PR DESCRIPTION
**Pull request by harmonyn**
Mostly relating to new additions to the game such as drones lizards, ayys, gangsters, etc., as well as other things that might make for actually interesting ion laws.

P.S. There are a lot of dank maymays in this, they're not my fault
P.P.S. Yes that includes BANDITS that was there before

### CODE REVIEW

**Comment by MrPerson** [comment]
Don't actually call them AHHHPERATIVES please

**Comment by Fayrik** [comment]
>Gas the lizards

This is an administrative nightmare already.

**Comment by Iamgoofball** [comment]
@Fayrik they can already get worse laws

**Comment by MrPerson** [comment]
The shitty laws should be removed, not kept as proof that shit is ok

**Comment by Iamgoofball** [comment]
@MrPerson i meant that as in the AI laws can already be generated to kill players and be a bad guy, which as far as I can tell is intended

**Comment by bgobandit** [comment]
there's two delineations of "shitty laws" here:

1. Laws that allow the AI to cause harm. These absolutely have to be in here, otherwise there's no point to the ion storm event, the point is that it can be useless or dangerous and you don't know what you're going to get
2. DANK EPIC MAYMAYS, which, where do you draw the line? Seriously look at the fucking doc

**Comment by Iamgoofball** [comment]
@bgobandit the traitor ion law generator should really be a default uplink item

**Comment by bgobandit** [comment]
on the one hand I agree because it's the most fun thing traitors can get if/when they get it

on the other hand there are way too fucking many uplink items as it is

**Comment by Fayrik** [comment]
@Iamgoofball You clearly don't understand. It's not the AI being allowed to kill people that's the problem, it is literally that phrase.
It's been proven time and time again, that any time someone with the slightest bit of authority says that phrase, the round immediately becomes a fucking free for all, with everyone killing each other "b/c i wus told 2 gas teh lizarsd."
That issue aside, if that law ever triggers, it's telling the AI to *gas them* with no law one priority. This means humans can and will be caught in it too.
I can already hear the bwoinks of "HELP, AI FLOODING PLASMA".

**Comment by bgobandit** [comment]
@Fayrik

you clearly don't understand all the possibilities that can come of ion laws, trust me, there is worse shit 

idk I can remove it if it's really that much of an issue

fucking lizards

**Comment by Xhuis** [comment]
if we didn't add lizards we wouldn't have this problem :^)

**Comment by Dorsisdwarf** [comment]
The AI can already get "The crew are changelings" or "THE STATION REQUIRES PLASMA" and the like

**Comment by Aranclanos** [comment]
doesn't help a lot but here
https://github.com/tgstation/-tg-station/pull/11348/files?w=1

**Comment by Fayrik** [comment]
@Dorsisdwarf If the AI gets that then people know to go hit it with a reset board.
Put in a meme law and everyone gets all "MUH MEMES" and then admins have to get involved.
Needless effort.

**Comment by Iamgoofball** [comment]
or why dont they just hit it with a reset board?

**Comment by optimumtact** [comment]
>people actually getting upset about ION laws

what the fuck, did I just teleport into reddit?

**Comment by Razharas** [comment]
>Jordie> yeah why not

**Pull request merged**
