### PR TITLE
Adds more persistent photo albums

### PR DESCRIPTION
**Pull request by Mickyan**
This feature was criminally underused due to the only functional albums being buried in the mess that is heads lockers. I have added albums for the bar, chapel, library, permabrig and nuke ops base (meta and delta only atm)

Additionally, the photographer quirk now also gives you a personal photo album to save your photos in (testing this is beyond my means but I think it should work)

I've added a description to the photo album and a unique name for new and existing albums, and persistence loaded pictures have a slightly different icon to make them stand out from current round photos

:cl:
add: New persistent photo albums have been added to the bar, chapel, library, permabrig and nuke ops base
add: Cameras may be purchased at the library's games vendor
add: The photograper quirk now grants you your very own persistent album to document your adventures
code: the photographer quirk now checks for free slots when assigning the items locations
tweak: pictures that are not from the ongoing round will look visibly old
/:cl:

### CODE REVIEW

**Comment by Tlaltecuhtli** [comment]
as you can see from this photo, the captain gave me all these guns and all access

**Comment by MMMiracles** [comment]
the personal photo album alone is pretty fucking cool and has a lot of meme potential

**Comment by ishitbyabullet** [comment]
katty guillou buff

**Comment by Ratvar** [comment]
Can't wait for photo mass to lag the shit out of round

**Comment by nicbn** [comment]
Can you remove the photos from the album? If so, isn't someone using photos from past rounds as fake evidence a concern?

**Comment by PKPenguin321** [comment]
>If so, isn't someone using photos from past rounds as fake evidence a concern?

It's a feature actually

**Comment by Mickyan** [comment]
If it ever comes to that giving them a different icon or a suffix tag shouldnt be too difficult but this isnt a new feature so i dont see why it suddently would.

**Comment by bgobandit** [comment]
just add a note to the description that it's from a past shift

**Comment by Mickyan** [comment]
I'm just gonna nip this in the bud and save later headaches, persistence loaded pictures now have their own icon

**Comment by bgobandit** [comment]
honestly though I don't know why this should be prevented, we have deepfakes and stuff in real life in 2019 so why wouldn't people in 2559 be able to fake a photograph

**Comment by KomradeSpectre** [comment]
I mean we also have forgeries and stuff in the game that are really easy to pull off lmao, not to mention with wigs I can easily change my appearance into whoever I want to. I don't really think there should be any concerns with people using this to trick others.

**Comment by bgobandit** [comment]
actually I changed my mind, I forgot that we absolutely have the kind of players who will pre-emptively take alibi photos to use in case they roll antag in future rounds

**Comment by MMMiracles** [comment]
just change the name/desc of the photo so it's obvious it isn't from that round

if you want to forge photos as an alibi/evidence you should need to do it that round.

**Comment by Mickyan** [comment]
it's pretty metagamey and all the use case scenarios I can think of you would consider to be quite bullshit if you were on the receiving end so let's not open that can of worm over a feature that's only meant to be fun

**Comment by Tlaltecuhtli** [comment]
give detective scanner exif data extractor

**Pull request merged**
