### PR TITLE
Morphs SHIFT-CLICK not MIDDLE-CLICK

### PR DESCRIPTION
**Pull request by MMMiracles**
ruined my game experience never again

### CODE REVIEW

**Comment by Qbopper** [comment]
i mean he's not wrong

**Comment by optimumtact** [comment]
this should be restated when you become a morph

**Comment by Bawhoppen** [comment]
WE CHANGED IT TO MIDDLE CLICK BECAUSE SHIFT CLICK IS ACTUALLY USED RETARD

**Comment by Bawhoppen** [comment]
:^)

**Comment by MMMiracles** [comment]
Apparently not because middle click did jackshit which is why I made this PR. 

ALSO YELLING IS RUDE, ASSHOLE.

**Comment by Bawhoppen** [comment]
:stuck_out_tongue_winking_eye:

**Comment by Bawhoppen** [comment]
i totally comment before looking 

but I still firmly hate shift-click being used for it

**Comment by Bawhoppen** [comment]
merge this quickly so I can forget about my autism comments.

**Comment by duncathan** [comment]
@Bawhoppen :^)

**Pull request merged**
