### PR TITLE
Adds warning-spans

### PR DESCRIPTION
**Pull request by kingofkosmos**
## About The Pull Request
Some warning-spans were missing from messages that clearly were telling the player they can not do something.
Also removed some extra spaces from span classes and added a few 'error'-spans when I came across denying messages in consoles.

## Why It's Good For The Game
More consistent spans.

### CODE REVIEW

**Comment by optimumtact** [comment]
Good change

**Comment by kingofkosmos** [comment]
Cool, I'll add a bunch during the next few days and say when it's done.

**Comment by kingofkosmos** [comment]
Alrighty, this can be marked as ready for reviewing.
(Hopefully I solved that merge conflict correctly, never done it through a browser before.)

**Review by SpaceManiac — CHANGES_REQUESTED** [review]
I notice you add `<span='error'>` to some messages. However, I don't think this CSS class actually exists. What's the intended appearance?

**Comment by kingofkosmos** [comment]
Didn't realize there wasn't an actual class named that. I just looked example from here:

https://github.com/tgstation/tgstation/blob/3d7f06474d186f9e41a4b4cea98a28553d08b636/code/game/machinery/computer/card.dm#L414

I'll just remove the changes regarding error-spans.

**Review by SpaceManiac — APPROVED** [review]
lgtm

**Pull request merged**
