### PR TITLE
Removes the slur from a possible smoke bomb description

### PR DESCRIPTION
**Pull request by JohnFulpWillard**
## About The Pull Request

There's a slur as a possible smoke bomb description, this changes it to something more fitting.
I wasn't sure what tag to add, hopefully spellcheck is enough.

## Why It's Good For The Game

Slurs in item descriptions doesnt seem like a good idea.

## Changelog
:cl:
spellcheck: Slightly changed the smoke bomb description
/:cl:

### CODE REVIEW

**Comment by Sparkezel** [comment]
Seriously why do you want to remove "nyagger" from that?

**Comment by GuillaumePrata** [comment]
TG coders removing(Even the bot agrees) my free speech or something smdh head
I'm making a reddit post, be right back.

**Comment by Sparkezel** [comment]
It's not even tg coders, it's full coder doing stuff on main because they debased recently again, his tag is litteraly John full Willard

**Comment by JohnFulpWillard** [comment]
> 
> 
> It's not even tg coders, it's fulp coder doing stuff on main because they debased recently again, his tag is litteraly John fulp Willard

maybe im just a fan of tom fulp

**Comment by SgtHunk** [comment]
This is outrageous. I am a PROUD American citizen and this violates my right. The first amendment (i think) clearly states Freedom of speech, and this pull request is violating it. I will NOT stand for this. You are using GitHub, an american website, and posting this pull request on an american repository. This is simply an entire violation of my freedom, I can't believe someone would go out of their way to remove a variant of a racial slur from the codebase just to ATTACK my freedom.

**Comment by Jhyrachy** [comment]
I'm ok with changin Nyagger with Ligger.

But would be better to have both

**Comment by ishitbyabullet** [comment]
Gamer fits either way. include it if this PR gets closed somehow.

**Comment by SuperNovaa41** [comment]
Lol

**Comment by ChungusGamer666** [comment]
reddit

**Pull request merged**
