### PR TITLE
Revert "Hotkeys for target selection and run/walk"

### LINKED ISSUE #21343: You can no longer run and examine at the same time.
Using the shift + click hotkey will have you walk until you release shift, even with hotkey mode off. 

If it's intended cool, but I don't quite think it was when the walk hotkey was made.

### PR DESCRIPTION
**Pull request by MrsTonedOne**
Reverts tgstation/tgstation#21039

fixes #21343 

@Cyberboss

### CODE REVIEW

**Comment by lzimann** [comment]
did this break anything

**Comment by MrStonedOne** [comment]
yes, #21343

**Comment by ChangelingRain** [comment]
Shouldn't you just revert that part, then?

**Comment by MrStonedOne** [comment]
If somebody wants to make a PR before this one matures that properly fixes it they can. Nothing stops them.

**Review by ChangelingRain — CHANGES_REQUESTED** [review]
Just remove the offending/broken part of code, don't revert the entire thing.

**Comment by MrStonedOne** [comment]
I'll be keeping this test merged.

**Comment by ChangelingRain** [comment]
#21357
Don't make low-effort revert prs TM

**Pull request closed without merging**
