### PR TITLE
Loyalty Implants and Gangsters

### PR DESCRIPTION
**Pull request by Ikarrus**
- Experiment: Loyalty implants will no longer survive deconverting a gangster. Security now needs to use two of them if they want the permanent effects: The first to deconvert them, and the second to make them loyal.

### CODE REVIEW

**Comment by AndroidSFV** [comment]
If your going to do this, I think there needs to be some kind of feedback after putting in the first implant.

**Comment by Ikarrus** [comment]
There already is, and once #9291 is merged it should be more obvious.

**Comment by AlexCrimson** [comment]
Wont the gangsters just run off to find a boss and get converted again?

**Comment by Ikarrus** [comment]
Merging this with my other gang PR as a single gang update

**Pull request closed without merging**
