### PR TITLE
Hazard vest and rad suit resprite

### PR DESCRIPTION
**Pull request by VictorVow**
## About The Pull Request
This changes the hazard vest and rad suit sprites to better looking ones.

Old hazard vest:

New hazard vest:

Old rad suit:

New rad suit:

This is a port of [this PR](https://github.com/BeeStation/BeeStation-Hornet/pull/572). 

Edit: updated screenshots.

## Why It's Good For The Game

It look better than current sprites. 

## Changelog
:cl:
change: Changed hazard vest and rad suit sprites. 
/:cl:

### CODE REVIEW

**Comment by AffectedArc07** [comment]
Get someone to re-run the icondiffbot check, there were issues on my end

**Comment by HomocidlePancakes** [comment]
ERROR 666: “NO SOUL FOUND”
PLEASE RETURN THE SOUL TO RESUME PROPER FUNCTIONING

**Comment by HomocidlePancakes** [comment]
Also, side sprites are 1 pixel shorter than back/front sprites.

**Comment by Victor239** [comment]
@ShizCalev rerun the icondiff bot ples

**Comment by Bawhoppen** [comment]
I wonder how an additional layer of a darker shade of yellow might look in sections of the radsuit? Otherwise, good PR :+1:

**Comment by PKPenguin321** [comment]
Can you get a brighter picture of the new hazard vest? Looks like you took it during night lighting. The front sprite of it looks almost like an inflated life jacket but I'm not really sure if that's the sprite or the lighting.
Rest of the sprites are ace though

**Comment by Victor239** [comment]
Updated the screenshots so they're all using day lighting. Looks like the icondiff bot is happy now also.

**Review by actioninja — CHANGES_REQUESTED** [review]
Conflicts

**Comment by Victor239** [comment]
Uh that instantly failed for some reason, can you try rerun it?

**Comment by AffectedArc07** [comment]
Your PR has merge conflicts. Mere conflicted PRs cannot be ran on MapDIffBot or AppVeyor

**Comment by optimumtact** [comment]
gotta resolve thsoe conflicst

**Pull request closed without merging**
