### PR TITLE
Bot performance and PDA features update

### LINKED ISSUE #4087: MULE bot interface issues
I'm not sure how to describe this best. When using a MULE bot to look at it's controls/information interface, the popup window tends to act strangely. The popup will every few seconds, refresh and focus, as if the window was opened up anew. 

This makes some things difficult to do with the interface open. (Example: Right click menus are closed when the popup refreshes)
Additionally if the popup window has a scroll bar due to size, it will jump to the top of the scroll with each refresh.

Not a big issue as it can easily be worked around, but still annoying.

### LINKED ISSUE #6041: MULE pathing issue
Mules have a pathing issue, they get stuck after delivery

### LINKED ISSUE #9081: Mulebots are driving around unable to return home
Two shifts in a row the mulebots where driving around crazedly. From start of the shift. I was unable to send them back home, via PDA or by manual input.

### LINKED ISSUE #9273: HoS's PDA says medical bot access instead of securitron access
Reported for Malkevin

### LINKED ISSUE #9326: Mulebots bullet_act ignores projectile type
They don't check if projectiles do damage, leading to:
````
You fire the staff of healing!
Something shorts out inside the Mulebot (#1)!
````

### PR DESCRIPTION
**Pull request by GunHog**
Viciously rips radio code from bots, replacing it with something better and faster!
- Bot patrol logic redesigned, much faster.
- Gives all bots Robotics access for easy patrol activation.
- Bot navigation beacons are no longer radios. Instead, they are
  maintained in a global list.
- Navbeacons can now be accessed by Roboticists, and they use a better
  UI.
- PDA bot code rewritten. They no longer use radio objects at all!
- Captain now has all-access! His cartridge now has everything except
  Mime and Clown functions.
- There is now one button across all PDAs for accessing bots. Only bots
  you have access to control will show on the list.
- Buffed the signaler cartridge! It may now be used to signal on all
  valid frequencies.
- MULEbot interface refreshing may now be toggled.
- The AI's botcall interface now includes the bot's model, so it can
  always identify the type of bot it is controlling. PDAs have this as
  well.
- Spilled my blood to begin Jordie's dark ritual.
- <b>Edit:</b> Removed bots from the NPC Pool.

Fixes #6041
Fixes #9273 
Fixes #4087
Fixes #9326
Fixes #9081

### CODE REVIEW

**Comment by GunHog** [comment]
The maps? I do not understand, everything compiled and loaded for me just fine.

**Comment by optimumtact** [comment]
Changelog file has some missing end quotes

**Comment by Alek2ander** [comment]
#9081?

**Comment by RemieRichards** [comment]
@GunHog can you fix the NPCPool causing bots of different types trying to help each other?

For example:
A cleanbot is stuck, unable to clean a cobweb (for example, to cobweb in meta's show room)
It calls for help, which is fine, More cleanbots show up, this makes sense.
Then beepsky, and officer johnson, and the mulebots all show up... which makes no sense as they're not equipped for the job, at all.

**Comment by GunHog** [comment]
I missed 9081, but that is unlikely to happen again, as that was a radio code issue. And RR, what in the world are you describing? Bots do not, nor have they ever transmitted their cleaning target (excluding patrol, and it seems that removing filters caused MULEs to download patrol targets) to other bots. I do not know what NPCPool is or how it works. If this affects bots somehow, I am going to need an explanation on how.

**Comment by RemieRichards** [comment]
@GunHog A key aspect of NPCPool is that it makes anything in it call for help from other NPCPool NPCs, However it is to my understanding (AND HAVING SEEN WITH MEINE AUGEN) that they disregard what type of NPCs are being requested to "help".

Now originally, Bots were never a part of NPCPool, just SNPCs, but Bots have been in NPCPool for a while now, and they routinely call for help from the wrong type of bots.
Seriously, Observe metastation's showroom, a cleanbot will get stuck on the cobwebs it can't reach, call for help, and literally every bot on station will sit on the same turf trying to help.

There's 2 issues there really, 1. the fact they never give up 2. the fact that a MULE is trying to help clean a room, it can't do that, neither can beepsky, yet my god do they try.

**Comment by GunHog** [comment]
I do not understand. I have never seen this behavior. Now, a cleanbot that is on patrol getting stuck trying to scan the showroom (this can be fixed by map - editing the cleanbot's access card to that room) is something that makes sense, and others would, too. 

But there is zero code in bots.dm or the sub files that cause them to "request help", only a little edit to the call_bot() proc to let it be called to a place by whatever Sawu made.

Cleanbots have an ignore list, so they would be stuck for 2 ticks * number of stains in the room that it can see but not reach, with a limit of 50 ignored locations. I will have to run some tests to confirm that feature is working properly, but I see two possible scenarios for MULEs and other bot types trying to respond to cleanbots: The filterless radio code could disrupt other bot types (9081), which goes away once this is merged. The second is that some black magic in NPCPool is executing behavior code on bots outside of their own modules (bots.dm, the dm for the bot itself, cart.dm/radio.dm for PDAs, ai.dm for AI players). Kindly provide me example of how to activate NPCPool, because I do not see it active on a test environment.

**Comment by RemieRichards** [comment]
@GunHog What is the point? you're not even listening to me.

* Access is not an issue, Meta physically mapped cobwebs behind windows, the cleanbots can never reach it, and they sure else hell don't even give up.
* NPCPool is always active, it's a Subsystem, I'm assuming the request for help code is in there, because as I said they started doing this after being put in the pool, one of the key features of the pool was to allow NPCs in the pool to request help from each other, then bots were add, Put 2 + 2 together here GunHog, christ.

**Comment by optimumtact** [comment]
@GunHog the travis failure is unrelated to your code, it was unable to download a package, probably a transient network error

**Comment by optimumtact** [comment]
@RemieRichards GunHog didn't put bots on the NPC pool subsystem, someone else did, I think it's fair to excuse them for not knowing that happened. It was added by sawu here
https://github.com/tgstation/-tg-station/pull/8615

**Comment by RemieRichards** [comment]
@optimumtact omfg does ANYBODY listen to me?

**Comment by optimumtact** [comment]
If you're just going to be frustrated and leave unproductive comments then I suggest you need to take a quick break

@GunHog 
https://github.com/tgstation/-tg-station/pull/8615/files#diff-769b030a5dc6c3a9cad08aa56ee92baaR40 Bot handling is here.

**Comment by palpatine213** [comment]
Oh thank god. The Mulebots running around was getting ridiculous. Especially since the pool would ignore if a mule was switched off, and just have them switch themselves on to respond.

**Comment by GunHog** [comment]
Bots have been removed from NPCPool. After finally confirming what RR said about MULEbots and others, I just decided it would be much simpler and better to just rip them out of it, just like radio code. 

The call_bot() proc was created for AI players, and was not properly adjusted to account for automatic systems like NPCPool. I seriously thought that I was fighting another AI to stop the rogue MULEbots one round. call_bot() automatically switches on inactive bots to save the AI the time of having to do that itself.

**Comment by optimumtact** [comment]
:+1: that seems the best solution to me, a proper integration can be considered in future.

**Pull request merged**
