### PR TITLE
Crystallizer Hotfix 2 - Piping Boogaloo

### PR DESCRIPTION
**Pull request by Ghilker**
## About The Pull Request
Sooooo the piping layer didn't setup properly... now it is... also another minor fix for the UI where you couldn't set the moles/s over a certain amount

## Why It's Good For The Game
Fix

## Changelog
:cl:
fix: fix piping layer not being set, now it works, also UI value fixed for moles/s intake
/:cl:

### CODE REVIEW

**Comment by LemonInTheDark** [comment]
What was the exact issue with the molar count?

**Comment by Ghilker** [comment]
> What was the exact issue with the molar count?

In the UI didn't go over 50 because i changed it once and never reverted that part

**Comment by Sethnov** [comment]
when this getting merged?

**Comment by LemonInTheDark** [comment]
We'll get there when we get there, now be quiet or I'll turn this pr around

**Pull request merged**
