### PR TITLE
[EXPERIMENTAL] in which byond optimization gets high

### PR DESCRIPTION
**Pull request by Iamgoofball**

### CODE REVIEW

**Comment by Iamgoofball** [comment]
>code/controllers/subsystem/garbage.dm:39:warning: qdel_list: variable defined but not used
code/controllers/subsystem/garbage.dm:167:error: SSgarbage.qdel_list: undefined var
code/controllers/subsystem/garbage.dm:309:error: SSgarbage.qdel_list: undefined var

????

**Comment by Iamgoofball** [comment]
can someone force travis to restart?

it worked on the first so idk why its breaking on the second

**Comment by octareenroon91** [comment]
Thought you could poke travis but I forget

**Comment by AnturK** [comment]
Whoops testing, request review button sorry mso.

**Comment by octareenroon91** [comment]
Maybe check your code, close, reopen.

**Comment by Iamgoofball** [comment]
testing this

**Comment by Iamgoofball** [comment]
should refresh travis

**Comment by optimumtact** [comment]
I want a proper explanation of what is occuring here with more indepth explanation before we go cargo culting our code. Please just wait on these thanks.

**Pull request closed without merging**
