### PR TITLE
Fixes light explosions having 0 chance to delimb someone if they have no bomb resist

### PR DESCRIPTION
**Pull request by Watermelon914**
## Changelog
:cl:
fix: Fixed light explosions having 0 chance to delimb someone if they have no bomb resist.
/:cl:

### CODE REVIEW

**Comment by Mothblocks** [comment]
i wonder if this buffs pda bombs again

**Comment by Mothblocks** [comment]
also are you sure this is a bug

**Comment by Watermelon914** [comment]
> also are you sure this is a bug
if you scroll up a bit, you'll see that there's a check to see if they have no bomb resist or if the intensity is a big explosion.
Either way, this won't proc if it's a weak explosion and you have any explosive resistance. It is definitely a bug

**Comment by Mothblocks** [comment]
i looked at the diff from before this and i think you're right

image

**Pull request merged**
