### PR TITLE
Allows to climb over space heaters

### PR DESCRIPTION
**Pull request by praisenarsie**
:cl: Frozenguy5
tweak: You can now climb over space heaters.
/:cl:

### CODE REVIEW

**Comment by epochayur** [comment]
oh hey a good narsie pr

**Comment by Cyberboss** [comment]
A) This won't work consistently because heaters are unanchored
B) Freeze

**Comment by epochayur** [comment]
nvm

**Comment by praisenarsie** [comment]
to combat cyber's 1st point, crates are anchored and you can climb over them. 🎉

**Pull request closed without merging**
