### PR TITLE
Removes disappointed.ogg from the round end sounds

### PR DESCRIPTION
**Pull request by TheVekter**
## About The Pull Request

RIP

## Why It's Good For The Game

Not-Hippie made us remove the old one which was about a million times better. This one just sucks and is depressing. Let's make some better ones that don't try to copy what was arguably perfect. Seriously, I'd rather here TWENTY FUCKING GONDOLAS.

## Changelog
:cl:
sounddel: Removed disappointed.ogg from the round end sounds because the new version sucked.
/:cl:

### CODE REVIEW

**Comment by Jared-Fogle** [comment]
tough but fair

**Comment by TheVekter** [comment]
Truth be told, I'm of the mindset that we tell Not!Hippie to go pound sand, since they can't actually legally act on that, but I'm not a maintainer. So.

**Comment by cacogen** [comment]
I added petersondisappointed and I don't think it's very good and should be removed too

**Comment by necromanceranne** [comment]
We should the soundbite from Hercules.

https://youtu.be/cdEQmpVIE4A

**Comment by optimumtact** [comment]
no

**Comment by trerri** [comment]
what was the old one?

**Comment by optimumtact** [comment]
a fiverr dude shouting hilariously

**Pull request closed without merging**
