### PR TITLE
Megafauna and lavaland mobs will no longer spawn directly on top of the mining base

### LINKED ISSUE #27433: Tendril Spawned in mining base
image

### PR DESCRIPTION
**Pull request by ChangelingRain**
:cl: Joan
tweak: There is now a buffer zone between the mining base and lavaland where megafauna will not spawn.
tweak: Ruins will no longer spawn directly in front of the mining base.
/:cl:

Fixes #27433
@Core0verload hey look like 70 minutes of work you could have fixed it instead of complaining on an unrelated pr

### CODE REVIEW

**Comment by Core0verload** [comment]
>All checks have failed

40 minutes you say? Well memed.

**Comment by ChangelingRain** [comment]
Mapmerger broke on me let me double that

**Comment by kevinz000** [comment]
🤔

**Comment by Kromgar** [comment]
150 hours of testing

**Comment by Haevacht** [comment]
kromgar that's not how that works you nerd

**Comment by Repukan** [comment]
Were they actually spawning that close that often?

Usually they spawn at the 60- 80+ coords range

**Comment by Penguaro** [comment]
So I see the two new areas defined, what will the buffer area be? Just regular unexplored?

**Comment by ChangelingRain** [comment]
The buffer area is `/area/lavaland/surface/outdoors`, which neither ruins nor mobs will spawn in. `/area/lavaland/surface/outdoors/unexplored` allows mobs and ruins, while `/area/lavaland/surface/outdoors/unexplored/danger` also allows megafauna.

**Comment by Penguaro** [comment]
Ah I see, thanks!

**Pull request merged**
