### PR TITLE
Adds new graffiti

### PR DESCRIPTION
**Pull request by Mickyan**
:cl: Mickyan
add: After rigorous mandatory art training for the crew, many new graffiti styles are now available
/:cl:

You ever thought to yourself "Man I wish I could spend 20 minutes doing something just for the janitor to walk in and destroy it in 10 seconds"? Then boy do I have some news for you

I also removed a few icons that to the best of my knowledge were duplicates/obsolete. No idea what they were originally for.

Not all of them are shown here but you get the idea

screenshot_8

screenshot_3

screenshot_4

### CODE REVIEW

**Comment by MMMiracles** [comment]
oh my god

**Comment by MrDoomBringer** [comment]
fuck yes =

**Comment by JStheguy** [comment]
speedmerge this shit

**Comment by Bawhoppen** [comment]
I can't help but think we shouldn't add flavor of the month things like the bongo cat meme. Eventually with time, the meme itself will fade out of use and grow old, and all we'll be left with, is some graffiti of a long since passed fad.

**Comment by Bawhoppen** [comment]
Or am I dumb and that's something you manually sprayed with squares???

**Comment by FantasticFwoosh** [comment]
Welcome to janitor hell.

**Comment by MrDoomBringer** [comment]
@Bawhoppen that was manually created u silly man

**Comment by sagattyy** [comment]
cleaner grenade party

**Review by SpaceManiac — APPROVED** [review]
ell gee tee em

**Pull request merged**
