### PR TITLE
Adds a bar to the biogen to show how full a container is

### PR DESCRIPTION
**Pull request by Wallemations**
## About The Pull Request
Adds a bar to the UI of the biogen to show how full the container inside is

https://user-images.githubusercontent.com/66052067/194737046-12b9e6c1-5b76-47ae-8b0f-8c77945ab0fe.mp4

I tidied it up a little bit but forgot to record it so here's a screenshot of how it looks now
image

## Why It's Good For The Game
Helpful so you don't have to keep doing math over how many u's of reagents you'll have room for in a container

## Changelog

:cl: Wallem
qol: The Biogen will show how full the container inside it is
/:cl:

### CODE REVIEW

**Comment by msgerbs** [comment]
Can you add the name of the container on/under the bar so it's more obvious that's what it means?

**Comment by Wallemations** [comment]
> Can you add the name of the container on/under the bar so it's more obvious that's what it means?

I can **_try_**, but I make no promises

**Comment by Wallemations** [comment]
I'm learning so much

**Comment by Wallemations** [comment]
I'm confused why the checks failed

**Pull request merged**
