### PR TITLE
Fixes for cyborg stack using variant 1 #20521

### LINKED ISSUE #20521: Engineering Cyborg Metal/Glass/Rods Bug
As of right now as the engineering cyborg if you select the metal sheets, glass, or rods and attempt to construct anything through the menu it will not let you do that. Thus it makes the engineering cyborg unable to build things like wall girders, grilles, and various other items through the menu.

This is only affecting the cyborg's resources. Resources used by humanoids is unaffected.

### PR DESCRIPTION
**Pull request by bear1ake**
Fixes stack using by checking active held item.

Fixes #20521

### CODE REVIEW

**Comment by bear1ake** [comment]
@optimumtact

**Comment by optimumtact** [comment]
Why did you open two pr's for this?

**Comment by phil235** [comment]
Did you test your PR?

**Comment by bear1ake** [comment]
@phil235 yes.

**Pull request merged**
