### PR TITLE
Flashbangs auto-stun in radius 1

### PR DESCRIPTION
**Pull request by ghost**
This serves two purposes.
- No dragging armed flashbangs behind you. This is functionally the same as running around with one in your hand, which was specifically coded out to require you to throw your flashbangs.
- Nerfs locker combat. Currently, if someone has a baton and hides in a locker/crate/bodybag, they cannot be defeated without explosives or lethal guns, as you must open it with an open hand, while they get to have their baton out. You can still get the jump on people with lockers, but they are no longer a fortress.

It's a 3s paralyze if you're 1 tile away. (This also affects mech and flashbang lance users)

### CODE REVIEW

**Comment by optimumtact** [comment]
does this actually stun them if they're in a locker? I wasn't aware the flashbang act worked on locker contents

**Comment by py01** [comment]
I tested it, it stuns you even if you are in a locker.

**Comment by optimumtact** [comment]
neat

**Comment by kriskog** [comment]
Also makes flashbang lances useless, but at the same time makes anyone in a mech vulnerable to flashbangs in their neighboring turf?

**Comment by py01** [comment]
One side effect that I just realized, this will also 20s stun people in mechs if you get a flashbang to pop next to the mech, which might be a bit much. Though having a more accessible counter to combat mechs may not be that bad, considering you also can't drag the flashbangs onto the mech. Feedback?

**Comment by py01** [comment]
Flashbangs lances will always stun you now, but you also can miss a tile and still hardstun your target.

**Comment by Whoneedspacee** [comment]
20 second stun seems a bit extreme especially since this can happen to people who aren't just the one holding it now, and mechs as well.

**Comment by py01** [comment]
Changed how it works, if you're 0 tiles away it behaves the same, one tile away does a 3s paralyze in addition to the flashbang act.

**Comment by FloranOtten** [comment]
I'm pretty sure that flashbangs bypassing protection if on the same turf was just a janky way to prevent holding flashbangs and not intended. 

20s stun on mechs is retarded. Imagine standing holding a flashbang besides someone and stunning a mech that long.

**Comment by necromanceranne** [comment]
Does this also work with chemical flashbangs? That is, sonic/flash powder bombs.

**Comment by py01** [comment]
No, flashbangs are snowflake and are unrelated to flash powder/sonic powder

**Comment by PKPenguin321** [comment]
*All* flashes are snowflake fyi: https://github.com/tgstation/tgstation/issues/40144

**Comment by bigfatbananacyclops** [comment]
atleast let earmuffs fully block the stun, that will add a use for them, this is going to impact both mechs and ops because even with flash protection.

**Comment by actioninja** [comment]
mechs might be a concern but w/e if it ends up being a problem it can be resolved.
for ops, if you had thrown an explosive grenade, they would be dead.

**Pull request merged**
