### PR TITLE
Removes simple xenomorphs from gold slime cores

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
WJ has been asking me to do this because he finds them an insulting/pathetic mockery of xenos. I don't really care about this PR either way so I won't be replying to any arguments in the comments. Maintainers can do whatever with it.

### CODE REVIEW

**Comment by optimumtact** [comment]
Could be a salt harvest, could be nothing.

lets see

**Comment by WJohn** [comment]
Yay :+1: 
The real reason is that these things also cause just as much panic as actual xenos do, despite being totally harmless, and it'd be a much bigger shitfest trying to get real xenos to be spawned or have real xeno corpses be dropped in their place (xeno organs and implant research is crazy strong).

**Comment by Bawhoppen** [comment]
yea simple mobs are dumb especially for a sentient species

thats why I hate simple mob humans so much

**Comment by Core0verload** [comment]
:+1: for removal of snowflakey shit.

**Comment by Cheridan** [comment]
yeah this is fine

also i agree with @Bawhoppen 's sentiment on humanoid simple_mobs.

**Pull request merged**
