### PR TITLE
Smart Pipes (It's big brain time)

### PR DESCRIPTION
**Pull request by Ghilker**
## About The Pull Request
This PR adds smart pipes to the game that replaces normal piping placing.
Smart pipes are like the redstone from minecraft but with both layers and colors, so you can have separate multiple layers and different colors; 
All component are now color coded, so that they can only connect to the same color/layer
Pipes and component can coexist on the same layer if they are of different colors (will add some glasses to allow players to select what color to see and interact with)
There is a new manifold, called color adaptor, that can connect to each and everyone of the layers and colors at the same time, effectively connecting two separate pipenets
Example shown here:
https://streamable.com/ccqf52 video
MAPS ARE NOT YET CHANGED; THAT WILL COME TO A LATER PR
THIS WILL NEED TO BE TM A LOT TO IRON OUT BUGS

## Why It's Good For The Game
Smarter pipes = smarter players

## Changelog
:cl:
add: Smart pipes, they connect to each other redstone-like, they are color and layer coded, so that they connect to each other only if on the same layer and color
tweak: all components are now color coded too, so they can connect only to same colored pipenets
add: added color adaptor, a layer adaptor with the addition of being able to connect to every color too
/:cl:

### CODE REVIEW

**Comment by tgstation-server** [comment]
You currently have a negative Fix/Feature pull request delta of -4. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

**Comment by trerri** [comment]
This seems like a fantastic opportunity to merge the layer, color, and multiz adapters into a single smart adapter with a UI to choose which layers, colors, directions, and Z-levels to bridge.
Also, the magic atmos goggles or the RPD, or a separate tab in the component's UI, should allow the different nodes to behave on different layers or colors.
You should limit the amount of pipes on the same layer, or give some sort of indication that they're there to players that aren't chadmos techs.
Lastly, you should remove pipe fittings, they're redundant with this feature. If you keep the pipe fitting dispensers, turn them into a sort of cart that can be dragged around, with a toggle mode for placing down pipes when it is dragged, removing them, changing layer and color, and placing components.
This would give them a functionality after years of uselessness.

**Comment by Qustinnus** [comment]
@Armhulen ghilker really trying to be the armhulen of 2020

**Comment by cacogen** [comment]
This is beautiful

**Comment by silicons** [comment]
somewhat concerned it'll be hard to

**Comment by optimumtact** [comment]
I'll overlook the points deficit cause I want this

**Comment by Ghilker** [comment]
Should be doable, but it will require a bit of work, any idea on what the upper bound of networks we should have? and with this all layers will be gone in favour of only one layer right? or we'd still have multiple layers? stacked colored pipes should still be on the middle (like layer 3) or they should shift a bit for each color?

**Comment by Losenis** [comment]
Each color is separate? And there are five layers? With 12 colors, christ that'd turn out to be like 60 possible layers.

Also how would this affect HEs? Would this not end up killing double-layering a vertical and horizontal pipe of the same layer in the same tile?

**Comment by optimumtact** [comment]
> Should be doable, but it will require a bit of work, any idea on what the upper bound of networks we should have?

I don't have a good sense on this, wondering if skilled atmos players know? 7 seems a reasonable place to start
> and with this all layers will be gone in favour of only one layer right? or we'd still have multiple layers?

Just one layer, colours is the differentiator

> stacked colored pipes should still be on the middle (like layer 3) or they should shift a bit for each color?

They can shift a bit, but that could present quite a bit of sprite/coding work, I'm unwilling to push you too hard as I genuinely think this is an improvement for atmos staff and rebuilding exploded areas

**Comment by LemonInTheDark** [comment]
Lemme know when this is feature complete so I can give it a read-over.

**Comment by Cyprex** [comment]
I really like the decorative value color has as it allows making complex setups easier to understand. It's used extensively in mapped atmos, and i like to incorporate it into my own designs as well.
Screenshot_20180508_161759 rudimentary atmos setup: blue is o2 storage, green is n2 storage and brown is remaining storage. dark purple is gas input.

**Comment by kriskog** [comment]
I've never been a fan of smart pipes simply because a fuckup takes forever to clean up. For power cables, the power contents are cleared on the next tick. For an atmos pipe you accidentally connected, you might be spending the rest of the round cleaning it up. If you can solve this, then yeah sure this is nice.

**Pull request closed without merging**
