### PR TITLE
You can rename chemistry grenades with a pen.

### PR DESCRIPTION
**Pull request by Iamgoofball**

### CODE REVIEW

**Comment by jughu** [comment]
Does this include descriptions

Also WHEN DO WE GET TO RENAME HOLY WEAPONS WITH CUSTOM LORE

**Comment by Iamgoofball** [comment]
@jughu yes

**Comment by Anonmare** [comment]
>Re-name CL3 foam grenade to "Healing smoke grenade"

:+1:

**Comment by coiax** [comment]
Isn't this covered by the freeze though? @optimumtact

**Comment by optimumtact** [comment]
not a fix

**Comment by jughu** [comment]
Reopen REEEE

**Comment by jughu** [comment]
Thank u @iamgoofball fix da conflict

**Comment by KorPhaeron** [comment]
@jughu 

Just recreate this its one line

**Pull request closed without merging**
