### PR TITLE
Blue security jacket for sec's wardrobe

### PR DESCRIPTION
**Pull request by Malgover**
## About The Pull Request

Nanotrasen's "Swag & Fashion" department is back again with a fresh blue jacket to wear for the people who prefer blue security.
Original sprite from World Server, I only added the NT logo on the back.

cop1
cop1open
cop2
cop3

cop4
cop5

## Why It's Good For The Game

This PR gives something to wear to people who prefer blue sec without having to resprite the entire department. This is a nice compromise, in my opinion. 

## Changelog
:cl:
add: Adds a casual blue jacket to sec's wardrobe.
/:cl:

### CODE REVIEW

**Comment by Mothblocks** [comment]
your git fu is weak

**Comment by Malgover** [comment]
all this shit for a god damn jacket

**Comment by Malgover** [comment]
> You currently have a negative Fix/Feature pull request delta of -4. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

i know my social credit score is low but ill do anything for this pr to get merged i know an entire department resprite to change sec from red to blue will never get accepted so at least let me have this!!!!!!!!!!!!! thanks kindly

**Comment by optimumtact** [comment]
NO ALTENRATE DAMN UNIFORM SPRITES

IM GONNA LOSE MY FUCKING MIND

**Comment by Malgover** [comment]
tumblr_ov64ktQZlO1scam2vo4_1280

**Comment by optimumtact** [comment]
ok fiar enough

**Comment by Malgover** [comment]
Apparently you seem to be worried about Sec losing their uniformity and no longer looking like a team.
I understand the sentiment, but a simple blue jacket is not going to make Sec look any less like Sec. If you see someone wearing a helmet, a visible equipment belt and a pair of red sunglasses, it is extremely likely they are a sec officer.

If it's about the colors, I don't see the issue. The sec wardrobe already has three (four?) pieces of blue clothing and nothing's currently stopping security from wearing them, and I have yet to see someone complain about security officers wearing their parade jacket or the mall cop uniform.

**Comment by Twaticus** [comment]
no sorry

**Pull request closed without merging**
