### PR TITLE
Hey there everyone, it's cat planet

### LINKED ISSUE #10349: Players are still starting with cat ears with no way of removing them
If mutant_humans are off.

@ricotez
@Incoming5643

### PR DESCRIPTION
**Pull request by Incoming5643**
</src> Fixes a bug where cat features were defaulting to random: The preferences were being loaded but not saved.

</src> Fixes a bug where mutant body parts on humans could appear even if config.mutant_humans was off. The check has been made ironclad.
</src> Fixes #10349
</src>

I have tested this patch pretty throughly because if there's still problems I won't be able to throw another bubsy game on the pull commit
</src> </src> </src> </src> </src> </src> </src> </src> </src> </src> </src> </src>

### CODE REVIEW

**Comment by Ikarrus** [comment]
https://www.youtube.com/watch?v=sdtehRUfzWc

**Comment by Incoming5643** [comment]
https://www.youtube.com/watch?v=T9tvxnDTALY

**Comment by Firecage** [comment]
Just add cat-people as a seperate human species and remove the mutations from humans.

**Comment by GunHog** [comment]
> Just add cat-people as a seperate human species and remove the mutations from humans.

I agree with this, that way you can also give them saymods ("meows","purrs", etc)

**Comment by Ricotez** [comment]
This doesn't fix the source of the problem, which is uninitialized preferences from pre-existing savegames.

@Firecage People have tried to add cat races several times, and every time the shitstorm ensued. Even my PR had to be modified to be admin-only.

**Comment by Firecage** [comment]
Rico, kinda surprising, since even if a cat-people race got added, it would be admin only unless you somehow manage to convince everyone that it should be added to the roundstart options.

**Comment by Incoming5643** [comment]
Shouldn't need to be merged if  #10353 is merged.

Still though...
</src></src></src>

**Comment by Incoming5643** [comment]
Caaaaaaat plaaaaaa-NET
</src></src></src></src></src></src></src></src></src></src></src></src></src></src></src></src></src></src></src></src></src></src></src></src></src></src></src></src></src></src></src></src></src></src></src></src></src></src></src></src></src></src></src></src></src></src></src></src></src></src></src></src></src></src></src></src></src></src></src></src></src></src></src></src></src></src></src></src></src></src></src></src></src></src></src></src></src></src>

**Pull request closed without merging**
