### PR TITLE
Fixes a few typos

### PR DESCRIPTION
**Pull request by TheVekter**
Who put an extra L there?

Fixed it everywhere it was misnamed so this shouldn't cause any map issues, but let me know if it fucks up somehow.

### CODE REVIEW

**Comment by Razharas** [comment]
22 more hours and its good
For now our specdial trained alchohol connoiseurs will need to take a look at this pr

**Comment by paprka** [comment]
>alchohol

**Comment by kingofkosmos** [comment]
If this is the PR for removing extra l's could you fix "ghost chilli" too, pls.

**Comment by TheVekter** [comment]
I can just make this the typo PR. I'll fix it tonight.

**Pull request merged**
