### PR TITLE
Engitools resprite

### PR DESCRIPTION
**Pull request by intercepti0n**
## About The Pull Request

Title. The time has come to resprite one of the oldest and soulful sprites in the game. I really hope you'lll love 'em!

pleasedonthateme

## Why It's Good For The Game

Remade sprites for t-ray scanner, gas analyzer, geiger counter and hand drill to fit current art style. Now they look juicier and thicker, i guess.

## Changelog

:cl:
image: resprites t-ray scanner, gas analyzer, geiger counter and hand drill.
/:cl:

### CODE REVIEW

**Comment by mc-oofert** [comment]
the hand drill is much less detailed
geiger counter is ok
t-ray scanner barely communicates what it does
gas analyzers are a straight downgrade

**Comment by Rex9001** [comment]
I think the gas analyzers, whilst good in shape look a bit busy for me.

**Comment by zxaber** [comment]
I like the old drill better, it really just needs the lower half alone resprited for perspective.

Really *not* a fan of the new gas analyzers, they look like some sort of Simon Says game.

There's nothing really wrong with the new T-scanner (the active state could use a bit more flavor), it's just drastically different than the old one. But that's fine.

**Comment by Serxule** [comment]
i hate tiny drill sprite, i hate tiny sprites in general, small sprites are hell and anti-qol

**Comment by Sealed101** [comment]
drill could be larger i agree but otherwise it's good
tray is good though the active state could use more spazz since its palette is less prominent. all it does it add the crest locator thingy on its display and not much else, maybe moving the crest thingy around?
geiger is fine
analyzer is great, although could be noisy, perhaps a tad too overcooked on all the high-tech stuff. simplifying the shape and getting rid of a few details could work better
also hilbert's analyzer lost its doodad, very sad

**Comment by intercepti0n** [comment]
@Sealed101 , thanks for the feedback! I'll try to fix at least a half of the problems you've mentioned.

**Comment by Inari-Whitebear** [comment]
> the hand drill is much less detailed geiger counter is ok t-ray scanner barely communicates what it does gas analyzers are a straight downgrade

D-do you think the old t-ray communicates what it does?

**Comment by GuillaumePrata** [comment]
The sprite quality is a lot better on new ones.

I will miss the old analyzer color scheme, it is not a big deal now but we should pay attention for future resprites, swapping more tools to the engineering yellow hurts on how easy it is to recognize each.

**Comment by Inari-Whitebear** [comment]
@mikederkan Well it's a legit question. If the criticism is
"If you resprite this you should make the function more clear in the new sprite even if it wasn't in the old"
or
"I feel like the old one communicated it better"

Because I have no idea what the old one communicates other than it being some sorta device

**Comment by CoiledLamb** [comment]
> The sprite quality is a lot better on new ones.
> 
> I will miss the old analyzer color scheme, it is not a big deal now but we should pay attention for future resprites, swapping more tools to the engineering yellow hurts on how easy it is to recognize each.

yeag that's why i pushed for the t-ray to continue being blue, i think these don't step on each other's toes too much though.
it should give a good bit of consistency without overlapping too severely, but i guess we'll see when they're in game?

**Comment by optimumtact** [comment]
don't forget to maintain the retrofuture theme

**Comment by notfrying1pans** [comment]
Hilbert's Analyzer looks almost identical to the normal one

**Comment by EricZilla** [comment]
Keep up the good work, love these

**Comment by Dorsisdwarf** [comment]
The T-ray scanner looks incredible. 
I really don't like the analyser, its just a mash of random scifi shapes that doesn't remotely communicate its function.
The rest of the sprites are... fine.

**Comment by MrDoomBringer** [comment]
> don't forget to maintain the retrofuture theme

sweeter words have never been said
kissing my photograph of wjohn rn

**Comment by Wallemations** [comment]
In the screenshot you accidentally did wrench -> screwdriver & the other way around
I'm on mobile so I can't check, did you do that with the dmi too or just the little showcase screenshot?

**Comment by zxaber** [comment]
New screenshots, nice.

For the drill in screwdriver mode, you should consider extending out where the driver bit would be by a pixel or two; it currently looks like an empty drill.

For the atmos scanner, are the gauge and screen meant to be separated uints? It looks like the gauge is behind the screen. Looks a lot better, though.

**Comment by Serxule** [comment]
new sprites are definitely a lot better and i got no problems with them

**Comment by intercepti0n** [comment]
@Wallemations , really sorry. Seems i've messed up demo screenshot, dmi is okay tho.

**Pull request merged**
