### PR TITLE
Resolves #7167 - Redone shuttle corners on zlevel 2, yet again

### LINKED ISSUE #7167: Inside of shuttle corners shows space
http://i.imgur.com/W4NlQRA.png
@Carn 

Possibly related to #6972?

### PR DESCRIPTION
**Pull request by ghost**
STOP REVERTING FIXES FOR YOUR STUPID HURR LULZY CONTENT

### CODE REVIEW

**Comment by WJohn** [comment]
Also just curious: http://i.imgur.com/N5Tc1tY.png

What is that? The only instance I can find of this is on the two corners of the escape shuttle cockpit, it's not found on any other interior space.

**Comment by Carn** [comment]
dunno where those came from. They've been copied to ministation too.

**Comment by Steelpoint** [comment]
So Carn, how exactly do you fix ground tiles from showing space underneath them from here: https://github.com/tgstation/-tg-station/issues/7167

Cause I'm making the White Ship move but its got a lot of those tiles inside it.

**Comment by Steelpoint** [comment]
Nevermind, I found a solution to the internal corners by simply using a corner tile that shows the ground sprite as well as the corner sprite in the same image.

**Comment by Carn** [comment]
steelpoint, you've reverted these fixes twice. just leave the shuttles alone ffs.

**Comment by Steelpoint** [comment]
Implying I intentional revert fixes.

Whenever more than one person makes changes to the map, there's a chance another PR that is open at the same time might accidentaly revert those changes

**Comment by Carn** [comment]
I wasn't implying it was intentional at all.
It was supposed to infer a general observation of incompetence.

**Comment by Steelpoint** [comment]
If you honestly think anyone is intentionally reverting fixes then your delusional or frustrated. 

DM Mapmaker is notoriously buggy and shit to work with, especially so when it comes to merge conflicts and when more than one person is working on the map.

Its why Metastation only had one person working on it, or why Boxstation was, for the longest time, never updated. Because if there's more than one person working on the map than map PR's can break easily.

**Comment by Carn** [comment]
again, I didn't say it was intentional. read

**Comment by Steelpoint** [comment]
Merge please.

**Comment by paprka** [comment]
Tested this a few hours ago, forgot to comment. But yeah, shuttles are fixed. The solution of using a shuttle corner on top of a floor sprite is a consideration for another time

**Comment by Steelpoint** [comment]
I already fixed that in my White Ship PR. I made a new sprite that has both corner sprites and floor sprites in the same sprite.

**Comment by paprka** [comment]
Ah, okay.

**Comment by Steelpoint** [comment]
Merge please.

**Pull request merged**
