### PR TITLE
Makes more things use colored lights

### PR DESCRIPTION
**Pull request by Tacolizard**
I made the lights as dim as possible, so they are only visible in complete darkness.

It's really not many things right now, I'll add more stuff later

### CODE REVIEW

**Comment by coiax** [comment]
FREEZE IS DEAD

**Comment by Tacolizard** [comment]
this isn't adding any new feature to the game. It is only making use of an existing feature.

**Comment by GunHog** [comment]
Neat.

**Comment by KorPhaeron** [comment]
Freeze

**Pull request closed without merging**
