### PR TITLE
updates washing machine descriptions

### PR DESCRIPTION
**Pull request by PKPenguin321**
so that they mention actually mention that you have to alt click them to turn them on

### CODE REVIEW

**Comment by CosmicScientist** [comment]
Muh immurshuns!
Cannot imagine how players learn this if they didn't originally see its functionality in the drop down. :+1:

**Comment by PKPenguin321** [comment]
closed/reopened for travis btw

**Comment by KazeEspada** [comment]
Update your code, merge from upstream.

**Comment by PKPenguin321** [comment]
ugh

**Comment by PKPenguin321** [comment]
Remind me to remake this

**Pull request closed without merging**
