### PR TITLE
Wizards can now buy an upgraded voice of god

### PR DESCRIPTION
**Pull request by coiax**
:cl: coiax
add: Wizards have been attacking stations with magical voices that seem
similar to the vocal cords of Colossi, just far more powerful. Be on
your guard.
/:cl:

@XDTM

Some refactoring so we can have a cooldown_multiplier var.
Wizard voice of god is x1.5 stronger and has 0.75 cooldown. But it
does cost three points.

### Reasons

Because voice of god is cool.

### CODE REVIEW

**Comment by Cyberboss** [comment]
POWER CREEP

**Comment by lzimann** [comment]
\>2 points for aoe bullshit that is better than the original with half of the cooldowns

at least put like 6 points or more

**Comment by ShadowDeath6** [comment]
are you sure putting a voice of god that's technically 4x stronger than the regular one for 2 SP is a good idea

**Comment by ChangelingRain** [comment]
>doubling power AND halving cooldown

do you understand fuck all about balance? because this looks like you understand fuck all.

**Comment by Arianya** [comment]
This should be fun to extract out of the wizard and put in the chaplain.

**Comment by coiax** [comment]
Eh, it's about as strong as timestop. With a longer cooldown.

**Comment by ShadowDeath6** [comment]
it's a lot harder to dodge VoG than it is timestop though

**Comment by XDTM** [comment]
Reminder that the voice of god can be countered with an item that can be mass-produced at the autolathe, has a shared cooldown on everything it can do, especially stuns, and is usually less powerful than wizard spells (_cough one-hit-kill cough_).

That said, the cooldown modifier should at least be 0.75 if not higher, and the power multiplier could be ditched although cultists already have a 2x.

**Comment by ChangelingRain** [comment]
Timestop is a 50 second cooldown, has a much smaller range(if somewhat better utility for some situations), and lasts 10 seconds.
This is a 60 second cooldown on the stun commands, which will stun for 12~ seconds, and effectively screen-range.

In addition, it's effectively multiple wizard spells; one of the spells it includes is basically mob-only repulse, and with this, that mob-only repulse is on a 30 second cooldown as compared to the actual repulse spell's 40 second cooldown.

**Comment by ChangelingRain** [comment]
This is good just for sheer versatility+being robeless, even if it didn't have double effect and half cooldown.

**Comment by XDTM** [comment]
The stun lasts 6 seconds WITH the 2x mod. Also, unlike timestop, you can protect yourself with a cheam item.

**Comment by ChangelingRain** [comment]
Uh, no, Stun(3) is 5-6 seconds, because it's per life tick, which are every 2 seconds.

**Comment by XDTM** [comment]
Lasted about 3-3.5 seconds when i tested it.

**Comment by Aloraydrel** [comment]
Lavaland bosses was a power creep mistake

**Comment by AdamElTablawy** [comment]
who cares it's a wizard

**Comment by kilkun** [comment]
^

**Comment by kilkun** [comment]
this is still more balanced than the rod form

**Comment by optimumtact** [comment]
Stop adding everything to wizard 👎

**Comment by coiax** [comment]
Seems unpopular.

**Pull request closed without merging**
