### PR TITLE
PR number 5(?) on trying to get the stupid icon conflict fixed for TCG cards

### PR DESCRIPTION
**Pull request by genessee596**
Okay.

(Hopefully!!!!!) fixed version of this PR; https://github.com/tgstation/tgstation/pull/51448

It is now past midnight. I've been screwing with this stupid icon conflict for several hours now. I think I've finally got it. Due to my incompetence, I've made what was originally a standard icon conflict into something that involved nuking my origin master.

Twice.

So; this is the latest and greatest in genessee industries in attempting to output a functional PR that changes, quite literally, a dozen-ish pixels on every card sprite.

Or, y'know, it'll blow up in my face again. Who knows?

Edit:

_**YES! YES! YES! YES! YES! YES! YES! YES!**_
(it works)

## Changelog
:cl:
tweak: TCG brand trading cards now show their rarity on the card, with tiers of rarity attached to a background color on the 'N' box on the bottom right corner.
/:cl:

### CODE REVIEW

**Comment by Doosteroni** [comment]
Really shoulda used Mr. Pibb instead of doctor pepper

**Comment by wesoda25** [comment]
5 times a charm

**Comment by TheChosenEvilOne** [comment]
changelog?

**Comment by Doosteroni** [comment]
> changelog?

Change logs are for the weak

**Comment by genessee596** [comment]
> changelog?

Thanks for pointing that out. Cranked out this fix at 2AM, so I totally forgot to paste the changelog.
Fixed, obviously.

**Comment by MrDoomBringer** [comment]
Include your name in the changelog homie

**Comment by genessee596** [comment]
> Include your name in the changelog homie

I thought it automatically did that if it got merged?

**Comment by optimumtact** [comment]
it defaults to your github account

**Comment by genessee596** [comment]
Alright, that works for me

**Comment by MrDoomBringer** [comment]
frick im retarded

**Pull request merged**
