### PR TITLE
Gives ops pinpointers by default

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
:cl: Kor
rscadd: Operatives now get their pinpointers in their pocket when they spawn, meaning reinforcements automatically come with them (and hopefully people stop forgetting them in general).
/:cl:

### CODE REVIEW

**Comment by lzimann** [comment]
:+1: :100:

**Comment by tkdrg** [comment]
dont forget to remove them from the map if youre doing this

**Comment by KazeEspada** [comment]
@tkdrg Why bother? They are on the op shuttle?

**Comment by tkdrg** [comment]
Well why not? It doesn't make sense to have 6 spare ones in a locker

**Comment by lzimann** [comment]
Just remove it from the locker, easy enough

**Comment by KorPhaeron** [comment]
@tkdrg 

Fixed

**Pull request merged**
