### PR TITLE
Unique ambience for virology! NOW NOT BROKEN!

### PR DESCRIPTION
**Pull request by DrDiasyl**
**A literal re-upload of #69031 because of that rust DLL problem. I don't wanna fix it the hard way, so easy way it is.**

## About The Pull Request

Now virology has a new Plague Inc inspired ambience sound (Made by myself in FL studio so no licensing problems). It has it's own define, and is used in the virology area.
There is 3 sounds, you can listen to them there:

https://user-images.githubusercontent.com/42353186/183266002-b0a92f8e-ca70-4b9d-ba7d-2aabf0998c52.mp4

Each of them weights ~100 KB which is not alot.

## Why It's Good For The Game

First of all, medbay literally only has only one ambient sound, and only 1 area of medbay had unique ambience (Morgue). It's neat to have more areas with unique ambiences, especially when that area on almost every map is seperated from the rest of medbay.

With this mysterious ambient, every virologist will feel himself making something _dangerous and scary,_ even if it's a benefical virus.
## Changelog

:cl:
soundadd: Virology got new mysterious ambient sounds.
/:cl:

### CODE REVIEW

**Comment by DrDiasyl** [comment]
image
I will just leave amount of likes from the original PR

image
And also the labels it had

**Comment by DrDiasyl** [comment]
Ahh, more problems that wasn't there before. Maybe I can't escape the sleep deprivation. But those look fixable.

**Comment by dragomagol** [comment]
You accidentally removed all of your changes

**Comment by DrDiasyl** [comment]
> You accidentally removed all of your changes

That was actually intentional lol, now this should be fully fixed.

**Comment by DrDiasyl** [comment]
@dragomagol this PR was up (including the time of "previous version") for like 17 days. San said that it auto-asks review of him because he wants to make sure nobody messes with areas alot. I didn't mess with such so..

When this will be merged?

**Comment by MrDoomBringer** [comment]
patience grasshopper

**Comment by DrDiasyl** [comment]
> patience grasshopper

_patiently waiting_

**Comment by MrDoomBringer** [comment]
patience rewarded

**Pull request merged**
