### PR TITLE
Bags of Holding are craftable again. Also removes BoH bombing.

### PR DESCRIPTION
**Pull request by MarioWizard119**
## About The Pull Request

It’s been a month, and I’ve seen more wizards in play than bags of holding. 

The nerf was in anticipation for a rework that has had no progress made on it, and we were left with an extremely painful nerf that was a “kill poor people to end poverty” solution to extremely poor game design for the sake of a stupid Easter egg.

I’ve also disabled BoH bombing simply because it’s caused too much headache and balance feuds for what is essentially a crappy Dungeons and Dragons Easter egg. I understand why you shouldn’t be able to put BoHs inside of other BoHs, so I’ve strictly blacklisted BoHs from holding each other. Noob traps, like BoH bombing, are extremely bad game design since they are about as effective as the fake item box from Mario Kart, yet make extremely potent weapons. Ninety nine times out of a hundred, if you set off a noob trap, you know exactly what you are doing. The simple blacklist accomplishes the exact same thing balance wise without introducing deliberate suicide bombing tactics into the game.

Keep in mind that this is not a full reversion/removal. The framework for BoHs being made out of bluespace anomalies is still there for when the anomaly farming overhaul gets made and merged, but it needs to be made and merged first before we make things require ingredients that are otherwise nigh impossible to obtain, and BoH bombing being reenabled is just a line of code deleted away, for when it has a price tag proportional to its punch.

## Why It's Good For The Game

When jumping from roof to roof, if you jump half way, you’ll fall into the alley. Make the full leap or don’t jump at all.

## Changelog
:cl:
del: You can no longer insert a bag of holding into another bag of holding.
balance: Working bags of holding are craftable again.
/:cl:

### CODE REVIEW

**Comment by optimumtact** [comment]
we're still waiting on the change to anomaly production, but they're held up because of github.

it's like the last pr on the tracker at this point.

**Comment by optimumtact** [comment]
I suppose I bettter leave it open for 24 hours

**Comment by Rohesie** [comment]
Cheap BoH bad.

**Comment by MarioWizard119** [comment]
@optimumtact I understand that. This isn’t meant to be a permanent change. This is just a temporary reversion of an otherwise painful nerf until the anomaly farming pr gets merged. I will immediately revert this pr once it does.

**Comment by necromanceranne** [comment]
Actually I made the change to cut down on bag storage over-saturation. I didn't even know about the wider departmental changes at the time of making that pr. It just so happened that it aligned with the goals of the department.

Essentially, I made that change with an independent goal in mind, and it's worked. Which was that bag space was essentially redundant once you hit 30 minutes with the round allowing, and that wasn't good. Everyone and their mother would have a bag of holding and they would just carry an obscene amount of weaponry on them at a given time.

**Comment by ExcessiveUseOfCobblestone** [comment]
#50290 as the person who merged this I do not see any point where I gave the impression this merging was only acceptable due to an upcoming PR not even on the tracker.

As such, I plan on closing this at the 24 hour mark.

At worst the boh becomes a storage creep item that gets back in to the meta tech-rush.

At best the status quo is maintained and the dnd easter egg stays as an easter egg rather than an item people attempt to rush every round.

If you dislike the timeline, 

1) ask the person doing the rework to put the design on our hackmd and PR changes that aid their design so they can push their timeline closer to what you deem is appropriate
2) beat them to the punch and make your own rework that incorporates design points mandated on the hackmd.

Again, this is assuming I merged it for that reason, which I did not (unless I did on discord?)

**Comment by wesoda25** [comment]
>removes boh bombs

bad pr

**Comment by Pumpkinoe** [comment]
If you're removing BoH bombing entirely, doesn't it also make sense to entirely remove the singularity subtype used for a BoH bomb?

**Comment by MarioWizard119** [comment]
@ExcessiveUseOfCobblestone Though you do realize with bluespace anomalies being capped at 1 per round, BoH bombing is literally impossible without admin shenanigans?

**Comment by MarioWizard119** [comment]
@necromanceranne If I made BoHs not hold bulky items, would that alleviate your concerns? You still have the convenience of a large amount of storage space, but can’t pull 7 TTVs or combat shotties out of nowhere.

**Comment by Fikou** [comment]
> @necromanceranne If I made BoHs not hold bulky items, would that alleviate your concerns? You still have the convenience of a large amount of storage space, but can’t pull 7 TTVs or combat shotties out of nowhere.

that already exists its called a duffelbag

**Comment by Tharcoonvagh** [comment]
WAH

**Comment by trollbreeder** [comment]
just let them take any type of anomaly

**Comment by necromanceranne** [comment]
@MarioWizard119 If I thought that would fix anything why do you think I would not have done that myself? If anything that makes the BoH a glorified duffelbag. I didn't want to undercut the unique powers of the BoH itself. Just the availability.

**Comment by MarioWizard119** [comment]
Though come to think of it, you can still do everything that supposedly made the BoH busted without using the BoH. Sawn off shotguns exist for your two shot backpack combo (and last I checked, sawn off improv shotties don’t have in hands), and you can fit seven max caps in a bluespace body bag and then in a normal backpack.

**Comment by necromanceranne** [comment]
I hadn't got around to killing off bodybags of holding, but I've asked maintainers and they gave me the thumbs up on that. I'll probably do that later I guess. There are issues with bodybags of holding beyond just storage space.

**Comment by ExcessiveUseOfCobblestone** [comment]
Yes, I do not have an issue with that and i'm assuming you don't either since you tried to remove that interaction here anyways.

**Comment by tgsAvylaar** [comment]
I think this is a step in the right direction. I'm glad you fixed the banbaiting trap mechanic too.

**Comment by necromanceranne** [comment]
Also, on the sawn-off shotgun in-hands, that's a bug. I haven't gone to look into that myself but it's definitely a bug. The in-hands exist, they're just not properly being updated when you actually saw the weapon down.

**Comment by Tharcoonvagh** [comment]
Bohback mountain

**Pull request closed without merging**
