### PR TITLE
adds marksman rifle

### PR DESCRIPTION
**Pull request by LanCartwright**
adds dmrs
adds dmrs to nuke

what is DMR:
DMR, Or Marksman rifle is a semi-automatic weapon with zoom.
60 Brute per bullet.

Costs less than sniper rifle.
Shoots faster/less delay.
Stand in hallways and mow down people

LORE:
The sniper rifle found great success, Operators reported dismay at the slow fire rate of the Sniper rifle.
Building from the firepower of the L6 SAW, the C90gl Carbine, stolen ARG blueprints, captured surplus WT autorifles, and the sniper rifle a new weapon was born.

Accurate as a sniper rifle, powerful like a machine gun. This weapon trades the sniper rifle's signature rounds for a more optimised anti-personnel capability.

### CODE REVIEW

**Comment by tkdrg** [comment]
I don't know, this sounds OP to me. only 14 TC for a gun that's about as good as the c20r AND gets the very strong zoom of the sniper rifle. Also, you should untick "include FILE_DIR" in your byond preferences, as we don't use that option in this project.

(reminder: https://github.com/tgstation/-tg-station/pull/13716/files?w=1 to see the changes without whitespace issues)

**Comment by LanCartwright** [comment]
first pull. do forgive me.

Also you're right, thanks for giving me a second opinion on the price. I'm slightly drunk currently so I'll probably raise it to the same price as the sniper.

Problem I found is that how does the DMR compare to the sniper?
The sniper outmatches it in everything except fire-rate and magsize.

I'll definitely balance some maths when I sober up tomorrow morning

**Comment by ninjacha** [comment]
Zero downside to other nuke weapons, make it have a large fire delay and have to be held with two hands maybe.

**Comment by LanCartwright** [comment]
Gimme a few hours to sober up and I'll rebalance those numbers.

**Comment by optimumtact** [comment]
update to latest master
git rebase -Xignore-all-space upstream/master

**Comment by Shapsy** [comment]
Why not just use the bulldog with slugs? Sounds like it does the same stuff as the bulldog except maybe without the zoom

**Comment by Lumipharon** [comment]
nuke guns are fucked in general.
They get a super powerful gun for free - there's very little reason to ever want to waste tc's on another gun.

**Comment by WJohn** [comment]
This is basically a straight upgrade to our sniper rifle. :-1:

**Comment by Dorsisdwarf** [comment]
@Lumipharon Bulldogs were *never intended to be that powerful*

**Comment by LanCartwright** [comment]
I'm slightly more sober now.

I've changed it to 20 tc for rifle and 5 tc per mag.

If this is still too much, I wouldn't mind changing the zoom to be less powerful, but then you can see behind you.

**Comment by tkdrg** [comment]
Sounds fair to me. If it ends up being OP we can always nerf it later.
Still merge conflicts, though.

**Comment by tkdrg** [comment]
reminder: https://github.com/tgstation/-tg-station/pull/13716/files?w=1 to see the diff without the line ending changes

**Comment by Lumipharon** [comment]
@Dorsisdwarf yes, but they are.

**Comment by KorPhaeron** [comment]
>Stand in hallways and mow down people

Don't think being killed by a spammable weapon from off screen will be very fun for people.

Sniper is at least limited by the fire rate/recoil/weight class/hand requirements.

**Comment by LanCartwright** [comment]
This is hardly more spammable than the L6 saw, trading 40 bullets, fire rate and burst fire for zoom capability. 

Ideally once someone realises that bullets are flying offscreen they move behind cover which is the entire point of the weapon in the first place.

I'd say the sniper is far more powerful because dragging a glass panel around won't stop it's bullet.

**Comment by Cheridan** [comment]
stale, reopen upon request

**Pull request closed without merging**
