### PR TITLE
Buffs throwforce of the sabre

### PR DESCRIPTION
**Pull request by jughu**
Buffs the throwforce of the sabre

supplementary video:
https://www.youtube.com/watch?v=wTC_1HRgbuo

### CODE REVIEW

**Comment by GunHog** [comment]
If you want to throw your best melee weapon at a guy who might catch it and slice your limbs off one-by-one with it, you might as well be rewarded a little if you succeed. 

Freedom to make very stupid choices is appropriate for SS13!

**Comment by jughu** [comment]
Its tactical i swear

**Comment by lzimann** [comment]
hey i don't really care about the sabre at all but thanks for that youtube channel, watching about swords and medieval shit is fun

**Comment by Shadowlight213** [comment]
Why?

**Comment by jughu** [comment]
Because throwing swords should be a supported tactical move

**Comment by optimumtact** [comment]
This doesn't need to be any stronger than it is. Denied.

**Comment by jughu** [comment]
Booo

**Pull request closed without merging**
