### PR TITLE
Advanced virus infection vector changes

### PR DESCRIPTION
**Pull request by ATH1909**
## About The Pull Request

This PR does a couple of things:
1. Which infection vectors an advanced virus has is now determined by its raw transmission stat, not (transmission-[number of symptoms in the virus]). The thresholds that an advanced virus's transmission stat needs to meet to achieve certain infection vectors have changed to:
```
always: blood
3+: fluid contact
7+: contact
11+: airborne
```
Note that, as the case was before this PR, these thresholds are cumulative.

2. The sneezing symptom now spreads the virus in a cone (or, well, in whatever shape a sentient disease's voluntary sneezing would spread the virus in) instead of in a square (or a circle?) around the host. The sneezing symptom's transmission 9 threshold effect now sets the cone's range to 6 tiles (up from 4 tiles).

3. The sneezing symptom has been given a new stage speed 17(!) threshold effect that will fling the host backwards a few tiles whenever they sneeze. It's great fun while you're in low/zero gravity areas!

4. The coughing symptom now spreads the virus in a 1 tile radius square centered on the host upon each cough, regardless of what thresholds have been met. The item-dropping threshold effect now requires a resistance stat of 11 to become active (up from 3), making the coughing symptom much less annoying in most normal viruses. The coughing fit threshold effect now requires a resistance stat of 15 (up from 10) to become active, doesn't cause the host to make a "double-cough" on the first cough of a coughing fit, and produces coughing fits 3 times as often now.

5. Various descriptions have been updated.

## Why It's Good For The Game

Our current system for the transmission stat is awful. A virus with a transmission stat of 8 currently gets no extra infection vectors (from its transmission stat) than a virus with a transmission stat of -8. You almost always either go for transmission 11 or just dump transmission entirely (unless you need to meet a transmission threshold) and take sneezing.

Sneezing has been nerfed to only affect people in a cone because it currently spreads viruses too well, making pretty much all other virus-spreading symptoms obsolete. Now, it should infect people a bit less often (and smart infected people can try to face walls at all times to avoid infecting others).

Coughing has been buffed so that it will no longer be the symptom that only new/inexperienced virologists use. It serves as a close-ranged, omni-directional alternative to the sneezing symptom (with different stats) now. Before this PR, coughing's special airborne transmission threshold effect was almost entirely redundant, because an airborne transmission method would almost certainly infect people (who didn't have internals on) near a host near-instantly without needing the help of coughing to do so. The resistance thresholds for coughing have been bumped up so that viruses can use coughing without absolutely dumping their resistance stat without being labeled a "grief virus" (and so that newer virologists won't accidentally released a minor coughing grief virus throughout the station).

These changes should also increase the likelyhood that a miasma virus will have infection vectors other than just "blood", making resistance a more important stat for viruses (especially beneficial ones, which normally dump resistance because nobody should be trying to "cure" them).

## Changelog
:cl: ATHATH
balance: The way that a virus's transmission-based infection vectors are determined has been altered.
balance: The sneezing symptom now spreads the virus in a cone, instead of in all directions.
balance: The sneezing symptom now has a very special threshold effect that requires the virus to have a stage speed of 17 (yes, 17, not 7) in order for it to be activated.
balance: The coughing symptom now spreads the virus in a 1 tile radius square around the host without any thresholds needing to be met.
balance: The coughing symptom's resistance 3 threshold (the one that make hosts drop small items) is now a resistance 11 threshold.
balance: Other alterations have been made to the thresholds and threshold effects of the sneezing and coughing symptoms.
tweak: Various descriptions have been updated.
tweak: The name of the viral DNA activator symptom has been changed to "dormant DNA activator", to avoid confusion with the viral self-adaptation and viral evolutionary acceleration symptoms.
balance: The dormant DNA activator symptom now activates as often as it should.
/:cl:

### CODE REVIEW

**Comment by ATH1909** [comment]
To do: Check to see if the description of the voluntary sneezing sentient disease ability was actually correct (in other words, does the voluntary sneezing symptom actually spread the virus in a cone, or just in a rectangle?).

Oh yeah, I was gonna add that extra threshold effect to the sneezing symptom, wasn't I? Hold on.

**Comment by ATH1909** [comment]
Say,, while I'm at it, should I bring the "severity" stat of the sneezing symptom and the coughing symptom down to 0 so that healthHUDs can still consider a virus that has sneezing and/or coughing in it to be a blue/smiley face virus?

**Comment by ATH1909** [comment]
Just checked the code, and yeah, (voluntary) sneezing should spread the virus in a real cone.

**Comment by TheSilverNuke** [comment]
I dont think sneezing and coughing should have a severety of zero. They should definitely show up as a minor negative symptom on scanners.

Personally, I find it unbased when a virologist uses sneezing or coughing in their viruses.

**Comment by ATH1909** [comment]
Okay, how did making that fix break everything?

**Comment by ATH1909** [comment]
Y'know what? I'm gonna move the quick fixes to VDNAA to a separate PR, since they're a bit out of the intended scope of this PR.

**Comment by ATH1909** [comment]
Bam, done.

And hey, everything works now (I think)!

**Comment by TheSilverNuke** [comment]
Looking forward to the merge

**Pull request merged**
