### PR TITLE
if you can't beat them, join them: Adds Vulpkanin, Tajaran, Skrell, and IPCs to the game.

### PR DESCRIPTION
**Pull request by Iamgoofball**
# if you can't beat them, join them

dreamseeker_2016-12-11_00-03-59

Pictured from right to left: Vulpkanin, Tajaran, Skrell, IPC

# Vulpkanin

Vulpkanin are a species of sharp-witted canine-pideds residing on the planet Altam just barely within the dual-star Vazzend system. Their politically de-centralized society and independent natures have led them to become a species and culture both feared and respected for their scientific breakthroughs. Discovery, loyalty, and utilitarianism dominates their lifestyles to the degree it can cause conflict with more rigorous and strict authorities. They speak a guttural language known as 'Canilunzt' which has a heavy emphasis on utilizing tail positioning and ear twitches to communicate intent.

# Tajaran
The Tajaran race is a species of feline-like bipeds hailing from the planet of Ahdomai in the S'randarr system. They have been brought up into the space age by the Humans and Skrell, and have been influenced heavily by their long history of Slavemaster rule. They have a structured, clan-influenced way of family and politics. They prefer colder environments, and speak a variety of languages, mostly Siik'Maas, using unique inflections their mouths form.

# Skrell

An amphibious species, Skrell come from the star system known as Qerr'Vallis, which translates to 'Star of the royals' or 'Light of the Crown'. Skrell are a highly advanced and logical race who live under the rule of the Qerr'Katish, a caste within their society which keeps the empire of the Skrell running smoothly. Skrell are herbivores on the whole and tend to be co-operative with the other species of the galaxy, although they rarely reveal the secrets of their empire to their allies.

# IPC

Positronic intelligence really took off in the 26th century, and it is not uncommon to see independant, free-willed robots on many human stations, particularly in fringe systems where standards are slightly lax and public opinion less relevant to corporate operations. IPCs (Integrated Positronic Chassis) are a loose category of self-willed robots with a humanoid form, generally self-owned after being 'born' into servitude; they are reliable and dedicated workers, albeit more than slightly inhuman in outlook and perspective.

# Q&A
## i dont like furry crap in my game
Too bad, you sound TRIGGERED!!! LOL!!!!
## this doesnt fit the theme
Too bad, you sound TRIGGERED!!! LOL!!!
It's just cosmetic, why are you complaining? Why do you get to tell people how to play?
## these are unoriginal
No they aren't they have LORE
## this is just because you're :salt: over petting
Not really. The way I see it, if we can add those cosmetic RP features what's wrong with this cosmetic RP feature?

### CODE REVIEW

**Comment by Iamgoofball** [comment]
will fix conflicts soon

**Comment by Iamgoofball** [comment]
Why was this closed?

Patting was denied 3 times but got merged.

**Comment by Iamgoofball** [comment]
Requesting a response @AnturK

**Comment by feemjmeem** [comment]
[http://feem.net/~logan5/byegoof.png](url)

**Comment by Shapsy** [comment]
At least we know what you'll put in your fork first

**Comment by feemjmeem** [comment]
stick a fork in it it's goof

**Comment by Iamgoofball** [comment]
@feemjmeem quality meme will make it the banner image on the server

**Comment by WJohn** [comment]
there there goofball

it's okay

embrace your destiny

we go down this slippery slope

**_TOGETHER_**

**Comment by Iamgoofball** [comment]
They're even configs for server owners

**Comment by feemjmeem** [comment]
i know you put a lot of work into this and i think it's probably some valuable content but your branch is called fuck_you_all and you seem a little upset

**Comment by WJohn** [comment]
don't worry goofball does this at least once every day. he's not upset, it's just normal.

**Comment by feemjmeem** [comment]
i just don't want anyone to have a heart attack or stroke

**Comment by WJohn** [comment]
shit man yesterday he made at least 6 of these PRs in response to a PR allowing you to pet people if you aim for the head on help intent.

**Comment by Iamgoofball** [comment]
help I've fallen and I can't get up

**Comment by Arianya** [comment]
>tfw goof directly disobeys contributing.md

**Comment by RemieRichards** [comment]
contributing.md now points to some spooky gitmagic website where github are trying to enforce our rules for us. spooky, thoughts @tgstation/commit-access ?

**Comment by AnturK** [comment]
About what ? This PR ? Repeatedly states no more visuals only species. PR closed about 8 ? times already.
About contributing ? What what. What is github doing..

**Comment by RemieRichards** [comment]
obviously I mean about the magic bowtie robot, if you view contributing.md (I clicked it as a link in my emails) it takes you to gitmagic.io

**Comment by AnturK** [comment]
Not seeing that here, weird.

**Comment by RemieRichards** [comment]
@AnturK https://gitmagic.io/

get cheri to sign us up or w/e (any maintainer can from the looks of it but you know, permission and stuff)

**Comment by AnturK** [comment]
Some of these are cool, like requiring screenshot on filetype changes.

**Comment by RemieRichards** [comment]
and enforcing not-shit commit messages.

**Comment by CrAzYPiLoT-SS13** [comment]
Goof you're my idol sign my manboob

**Comment by Earthykiller127** [comment]
hi please merge this you fucKING idiots

**Comment by Doppeltongue** [comment]
@Iamgoofball if you bothered reading the merged PR changed files, oranges edited the PR to be a comment with an emoticon. headpatting did not actually get merged.

**Comment by Iamgoofball** [comment]
I'm aware

**Comment by ShadowDeath6** [comment]
where were you when goof ascended to heaven?

**Comment by Haevacht** [comment]
what attempt number is this, like 4?

**Comment by jughu** [comment]
Ipcs are already in game 😄
They are called synths

**Pull request closed without merging**
