### PR TITLE
Adds a standalone Civilian Modsuit model, available from robotics

### PR DESCRIPTION
**Pull request by GPeckman**
## About The Pull Request

I talked with Fikou on discord about #84801, and he said that it would be fine to make a standalone suit that is slowdown-free but also not spaceproof. So yeah, that's what this is. The civilian skin for the standard modsuit has been turned into a standalone model. It is similar to the loader modsuit that cargo has, in that it has no slowdown while active but doesn't protect you from space. It also has only a complexity limit of 12 instead of the usual 15, and it has abysmal armor values. It also doesn't protect you from pepper spray and the helmet doesn't allow you to use internals or block you from eating.

I tweaked the sprites for it as well, removing the visor from the inhand and mob overlay sprites, to better reflect it's lack of spaceproofing. I also whipped up a quick sprite for the civilian mod plating, based off of the medical mod plating since they have similar color schemes.
## Why It's Good For The Game

I'm going to just copy and paste what I said in the last PR, because all of it still applies to this one. There are a lot of really cool modsuit modules that are hampered by the other drawbacks that modsuits have. These drawbacks exist for a good reason; space proof suits should have tradeoffs, especially ones available at the start of the round like modsuits are. But that doesn't really solve the problem with the modules.

One of the biggest examples of this problem is the pepper shoulders module that comes on security modsuits. It's a very cool module conceptually, but it tends to have limited usefulness in practice. Out in space, whoever you're fighting is likely wearing a spacesuit of their own, which will make them completely immune to the pepper spray. On the station, the person wearing the suit has to deal with the slowdown from it, which will far outweigh any advantage granted by the pepper shoulders module.

Another good example is the medical modules, like the surgical processor, organ thrower/organizer, and thread ripper modules. All of these are great for a medical player trying to perform surgery, but who is going to be doing surgery in a depressurized room? All these modules don't mesh well with the design of modsuits as special spacesuits, and the new civilian model will hopefully give them more room to be used.
## Changelog
:cl:
add: Added the civilian modsuit module as a standalone model. It offers no slowdown while activated but does NOT protect you from the void of space. You can print the plating from an exosuit fabricator and build it like a normal modsuit.
del: Removed the civilian skin from the standard modsuit, as it is now a standalone model.
image: Tweaked the sprites for the civilian modsuit head, both in-hand and on the mob. Also added a civilian mod plating sprite.
/:cl:

### CODE REVIEW

**Comment by MTandi** [comment]
The visor is still present on the side sprites.

image

Maybe we should replace it with something like a big collar, rather than a visor-less helmet. It looks weird.

**Comment by GPeckman** [comment]
Whoops, I knew I missed something. I uploaded a hotfix for that. Here are some actual screenshots of what the sprites look like ingame:

item
plating
sealed
unsealed

**Comment by CRITAWAKETS** [comment]
i don't like this pr but just for the stupid reason that this suit is my favorite sprite out of all the robotics printable suits

**Comment by carlarctg** [comment]
it looks like doo-doo with that silly helmet

what if it just flat-out had no helmet. theres support for that

**Comment by Loafin34** [comment]
because it's white, do you think it's possible to greyscale it so that we could paint it any color?

**Comment by itseasytosee** [comment]
I have the concern that this will affect job readability and the general look of the game. It's not distinctive and presumably intending for any and all personnel.

**Comment by zxaber** [comment]
If it had no helmet where would you install diagnostics huds or weld protection?

**Comment by Jacquerel** [comment]
> I have the concern that this will affect job readability and the general look of the game. It's not distinctive and presumably intending for any and all personnel.

To be clear, generic modsuits & this sprite for a generic modsuit are both already in the game.

**Comment by carlarctg** [comment]
> If it had no helmet where would you install diagnostics huds or weld protection?

nowhere

just get real huds

not the end of the world. makes sense anyways

**Comment by GPeckman** [comment]
> it looks like doo-doo with that silly helmet
> 
> what if it just flat-out had no helmet. theres support for that

I think it looks fine. I'll wait for Fikou and the spritetainers to chip in before I start making major changes. 

> because it's white, do you think it's possible to greyscale it so that we could paint it any color?

The mod paint kit lets you do that already. It gives you control over how each original color (red-blue-green, to clarify) is changed to the new one, so it works well even without grayscale.

**Comment by Dawnseer** [comment]
Incredibly saddened by the civilian skin being taken from the standard mod.
Please make a new one instead of hurting us so.

**Comment by Singul0** [comment]
Can't you just make 2 types of civilian modsuit, an EVA-proof one and this one?

**Comment by DATA-xPUNGED** [comment]
Maybe use the refactor that Fikou did so this suit doesn't need a helmet at all and doesn't have anything on that slot?

**Comment by Jacquerel** [comment]
> Can't you just make 2 types of civilian modsuit, an EVA-proof one and this one?

The EVA-proof one is the one which already exists

**Comment by DrAmazing343** [comment]
+1 to helmetless MOD, esp. if it's not spaceproof. I hunger for suit without helmet...

**Pull request merged**
