### PR TITLE
Remove unused and probably misbehaving admin human manifest spawner

### PR DESCRIPTION
**Pull request by vuonojenmustaturska**
No-one uses it, it doesn't seem useful, out it goes?

:cl: Naksu
code: Removed unused effect object that could be used to spawn a list of humans
/:cl:

### CODE REVIEW

**Comment by vuonojenmustaturska** [comment]
it's a mystery

**Review by SpaceManiac — APPROVED** [review]

**Comment by Anonmare** [comment]
I think you just deleted the ability for ID consoles to print off crew manifests

**Comment by vuonojenmustaturska** [comment]
https://github.com/tgstation/tgstation/blob/master/code/game/machinery/computer/card.dm#L518 that code is here, the code that was removed is not used

**Comment by Anonmare** [comment]
Ah I see

**Pull request merged**
