### PR TITLE
[PET/FEATURE] Pets for the Captain/HoS/Librarian 

### PR DESCRIPTION
**Pull request by Steelpoint**
Adds a new pet fox for several people, these pets are...

Tywin the Pug: The Captains new Pet.
Renault the Fox: The Libarians new Pet.
Sgt Arachna the Spider: The Head of Security's new Pet.

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
This doesn't really make much sense; foxes are crafty, clever, and more of a "planning" creature than an animal that approaches a problem directly/head on--it's more fitting of that they belong to a more bureaucratic job.

Also, HoS already has a pet; a bat.

**Comment by pudl** [comment]
how about instead of outright editing renault to be the hos' pet, you just edit the desc var? he was literally made to be the captain's pet.

**Comment by RemieRichards** [comment]
@Fox-McCloud a bat-spider! So yeah no HoS has unofficial pets already, don't give them another.

**Comment by dannno** [comment]
if this is a fox related Pr can you also remove the awful meme from fox crates/generic fox mobs

**Comment by Nienhaus** [comment]
@danno Glloyd on Urist made the desc, I just didn't change it.

**Comment by dannno** [comment]
it gives me physical pain

ps. foxes don't spawn meat when knifed fix that too :)

**Comment by paprka** [comment]
Bat mob edited to be a giant spider or nothing. :-1:

**Comment by GunHog** [comment]
HoS has a pet, give the fox to the poor Captain, who has nothing! Also...we still need Fennec Foxes!

**Comment by optimumtact** [comment]
Cargo needs a pet

**Comment by RemieRichards** [comment]
Cargo has a pet, the QM.

**Comment by paprka** [comment]
or lisa

**Comment by pudl** [comment]
cargo has Tom on both Eff 3 and Metastation

**Comment by pudl** [comment]
and ministation

**Comment by ike709** [comment]
Give it to the librarian, I need muh Faux News

**Comment by paprka** [comment]
^ this

**Comment by Steelpoint** [comment]
I figured that a Fox looked more appealing to the HoS, its red/orange ish and it looks cool.

I personally never cared for the spider, and I think the HoP is the Captains pet.

**Comment by Fox-McCloud** [comment]
Red also complements blue well =p

**Comment by paprka** [comment]
If nien added it for the cap, give it to the cap. Artistic license!

Really though the HoS having a bitch ass annoying fox is retarded. Spider or nothing.

You also run on a different codebase/map Fox, if you want to give it to the cap you can do so

**Comment by Steelpoint** [comment]
Well I suppose this is a good PR to figure out which pet we should give the HoS. We have three choices.

A) A Spider
B) A Pug
C) A Fox

**Comment by paprka** [comment]
Give HoS spider
Give captain a pug
Give librarian a fox

Pugs are royal animals and should be treated as such. Foxes are fucking nasty and not even domesticated regularly, heads of staff keeping animals like that around isn't a great idea. I could add functionality for the pug to wear captain's hats, and add functionality for the fox to wear a reporter's hat. Etc.

:+1:

**Comment by Steelpoint** [comment]
Aw shit these names, give me a moment.

**Comment by Steelpoint** [comment]
We have three new pets, they are.

Tywin the Pug: The Captains new Pet.
Renault the Fox: The Libarians new Pet.
Sgt Steel the Spider: The Head of Security's new Pet.

**Comment by paprka** [comment]
Steel sounds kind of lame for a straight name, if you're going for player reference think pet name like Sgt. Steely which is also an adjective

**Comment by RemieRichards** [comment]
@Steelpoint Don't rename Sgt. Araneus, the spider is Sgt. Araneus.

**Comment by Steelpoint** [comment]
I renamed nothing, Sgt. Araneus died along with Metastation. Sgt. Steely is a entirely new spider.

**Comment by RemieRichards** [comment]
No. Sgt Araneus or bust.

**Comment by Steelpoint** [comment]
Of course I don't mind either way, I just felt steel was more in line with a HoS's pet name than Araneus.

If Steely is not good enough, what other hard hitting names could a spider use?

**Comment by RemieRichards** [comment]
Arachna?

**Comment by Nienhaus** [comment]
untitled
You confuse me sometimes Paprika. Do what guys what with the fox I added it for the captain though.

**Comment by dannno** [comment]
Araneus or bust. Don't want your dumb player refs bozo.

But why does the librarian get a pet anyways

**Comment by Steelpoint** [comment]
Faux News as expained earlier.

I never liked Araneus since it sounds like Anus.

Sgt Arachna sounds better.

**Comment by dannno** [comment]
just because you have an anal fixation doesn't mean the name is bad

**Comment by Steelpoint** [comment]
Changed the name to Sgt Arachna.

**Comment by paprka** [comment]
Araneus is shit and generic as hell

LOL IT'S A GENUS OF SPIDER WAT AN ORIGINAL NAME FOR A SPIDER!!! < pls think about names before randomly being dedicated to them because of metastation

Player refs for the guy who has admittedly been more dedicated to security than anyone barring ikarrus is fine

Like I made a player ref to myself with cayenne in the nuke op mother base, but then again i'm the master of subtle player refs

I think steely is an acceptable name, I should have warned you to ignore NTstation people since they'd come in droves bitching about muh metastation spider

**Comment by dannno** [comment]
m-metastation was around for ages before NT

Arachna is just as bad in that respect then 
but "Steely" sounds like shit i'd name a pokemon back when I was 6 years old
we can do better than this

**Comment by paprka** [comment]
Then make a better name, or fuck off and quit shitposting.

**Comment by dannno** [comment]
damn paprika chill

**Comment by paprka** [comment]
>THIS SHITTY NAME IS BETTER THAN YOUR SHITTY NAME BECAUSE METASTATION!

No, stop shitposting.

**Comment by dannno** [comment]
I never said that though

**Comment by paprka** [comment]
Pet names are really inconsequential. Remie should know better too, especially since she gets on my case about comment quality. I told you why araneus is an awful name. Saying "Your name for the spider is bad think of a better one" in response is low tier shitposting. Contribute a better name or don't say anything.

**Comment by RemieRichards** [comment]
@paprka there's having a joke + complaining about a potential rewrite, and there's shouting and balling at someone for no reason.

And I do know better, hence cleaning up these comments.

**Comment by paprka** [comment]
Meh. Steelpoint wanted to give the fox to HoS, we said spider. As far as I'm concerned the name is up to him. Araneus is bad because it's pretty uncreative imo, Steely is a player reference but it's not so referential that it's terrible (it's not literally 'sgt steelpoint'). In the end it isn't up to me, but I've given my 20 cents on the name. :+1: for pug for the captain though, and the GoT ref is pretty fitting.

**Comment by dannno** [comment]
oh god I just got the ref and it's actually pretty good
you're right about Araneus/Arachna being bad because too easy but I still think "Steely" isn't good either
The names I gave are more subtle references to spiders
What about Romanov? or even Natasha or Natalia

**Comment by Nienhaus** [comment]
I find it stupid the librarian gets a pet.

**Comment by dannno** [comment]
Agreed.

**Comment by Fox-McCloud** [comment]
I'll second what Nienhaus said--generally speaking, heads of staff have been the only ones to ever have pets---with the barkeep being a very very old exception.

**Comment by pudl** [comment]
name the spider Vitalia

**Comment by paprka** [comment]
well i don't care about the librarian getting the fox or not but pug > fog for cap forever

**Comment by Steelpoint** [comment]
If we don't want the Liberian having a pet then I'll just drop the Fox.

**Comment by Niknakflak** [comment]
Not every job needs a fucking pet.  The HoS pet should have its original name.  Steely sounds like a reference to you, so fuck that.  And the pug should be named pugsly or spaghetti. Because those are previous names.  Consistency people.

**Comment by Steelpoint** [comment]
Its name is Arachna, keep track of the PR please.

**Comment by dannno** [comment]
Which is still a pretty bad name, it's waaaaaay too easy.. What do you think of the ones I gave, any of those hitting a chord for you? I like Ragnus the most.

**Comment by Nienhaus** [comment]
@Steelpoint :|

**Comment by paprka** [comment]
niknak's underage fury is adorable when he gets jealous of self references

**Comment by Steelpoint** [comment]
I'll revisit when there's no other map PR's up.

**Comment by Steelpoint** [comment]
My mistake, I forgot to actually push the fix proper.

**Comment by Niknakflak** [comment]
I followed the PR fine, and I stand by the spider should get its very original name, not an off branch name of arachna.  Pay attention to my posts.

**Comment by Niknakflak** [comment]
And I'm not jealous of player references, they are stupid in general, especially in this case for the sole reason that Steelpoint prides himself as an HoS, and this would solidify himself forever in that position.  If you could not be aggressive and make passive insults paprika, that would be nice.

**Comment by Steelpoint** [comment]
Then I'll change his name to Sgt Robust.

**Comment by GunHog** [comment]
Sgt. Robust...I like that!

**Comment by Niknakflak** [comment]
Well the spider does robust someone every round

**Comment by Miauw62** [comment]
erro's law still holds true.

**Comment by Steelpoint** [comment]
Going to have to explain that law.

**Comment by Miauw62** [comment]
the community reponse to a thing is inversely proportionate to its importance.

**Comment by RemieRichards** [comment]
to be fair that law has had LOTS of opportunities to be tested and it always turns out *true*

**Comment by dannno** [comment]
I didn't know that we could come up with a name EASIER than <latin sounding word for spider>
:^)

**Comment by Niknakflak** [comment]
It's Spanish

**Comment by paprka** [comment]
sgt bikeshed is the new name

**Comment by Steelpoint** [comment]
Unfixable merge conflicts, going to wait for other map and my own PR's to be merged before I go ahead.

**Comment by dannno** [comment]
@niknakflak they call them latinos for a reason

**Pull request closed without merging**
