### PR TITLE
All font size spans scale

### PR DESCRIPTION
**Pull request by cacogen**
## About The Pull Request

Every span which changes font size now does so relative to the base font size, so when you change font size everything scales.

Did my best to keep the sizes as close to what they were as possible:
[unedited log](https://filebin.net/buxetwdti88jh0d4/ss13_chatlog_unedited.html?t=wht7vg0r)
[edited log](https://filebin.net/buxetwdti88jh0d4/ss13_chatlog_edited.html?t=l1w4aayd)

Changing text size doesn't show up in logs so here's a comparison between the white template and the unedited black one:

## Why It's Good For The Game

So when someone says the n word on high volume my grandma can't read it from across the room

## Changelog
:cl: cacogen
add: The font size of all text in the chat window now scales
tweak: High volume is a slightly smaller
tweak: Admins have slightly larger OOC text
/:cl:

### CODE REVIEW

**Comment by Dawson1917** [comment]
>tweak: Admins have slightly larger OOC text

what have you done

**Comment by cacogen** [comment]
What I would like one day is random OOC colours assigned roundstart but I'm not a good enough coder to assign hexadecimal values that are far enough apart not to be confused and between two ranges so they aren't too light or dark to be read in order to increase the legibility of OOC (I have pretty bad eyesight) without obscuring admin OOC so making their text slightly larger is a small paver in that direction

**Comment by AnturK** [comment]
Very good change, but why the base font size bump ?

**Comment by cacogen** [comment]
When you adjust font size for the first time it defaults to 13px. 9pt is 12px. I'm not sure what the effect of that is but the change is to make it consistent. I'd show you the relevant code but I'm on my phone

**Comment by Borisvanmemes** [comment]
Admins having bigger OOC text is terrible and i fucking hate it, yours truly, some admin who barely even admins.

**Comment by kriskog** [comment]
Announcement text feels a bit too big
image

**Comment by cacogen** [comment]
@kriskog 

i will compare to old to see if i've fucked

@Borisvanmemes 

i barely even notice it but maybe that's because i play on 9px. it's literally 10% bigger. but, i can get rid of it

**Comment by cacogen** [comment]
@kriskog 
I checked and there's no difference other than announcements now scale with the base text size rather than staying at 24px. The default base text size is 13px. So announcements are now size 185%. 13 * 1.85 = 24.05.

**Comment by kriskog** [comment]
Just look bigger, which they are. I am on 18px (high resolution), so the announcements that were previously 33% bigger are now 85% bigger. I'll get used to it.

**Pull request merged**
