### PR TITLE
Adds the NTSS Shadow Emergency Shuttle

### PR DESCRIPTION
**Pull request by DAKKA-WAAAGH**
## About The Pull Request

Adds another emergency shuttle to the game and also adds a new emergency shuttle area.

## Why It's Good For The Game

People like shuttle diversity and are generally positive about new additions to their Purchase Shuttle list.

## Changelog

:cl:
add: Adds the NTSS Shadow Emergency Shuttle
add: Adds the Emergency Shuttle Engine area
/:cl:

### CODE REVIEW

**Comment by Jackal-boop** [comment]
Could you add a gas monitor computer and a sensor to the burn chamber in the back?

**Comment by DAKKA-WAAAGH** [comment]
> Could you add a gas monitor computer and a sensor to the burn chamber in the back?

There's not really a point to it, the burn chamber is mostly fluff to make it look more technical than it really is 😂 . Feel free to do whatever you wish with the shuttle should it be merged.

**Comment by DAKKA-WAAAGH** [comment]
MDB is killing me here... 😧

**Review by san7890 — CHANGES_REQUESTED** [review]
image

The pixel-offsets on these aren't actually supported in code, they'll always show like this:

image

---

image

This looks kinda weird to my eyes, maybe try using `/turf/open/floor/catwalk_floor` (or a subtype of that) instead, and get rid of the external hull plating and the catwalk over that?

---

You need more fire alarms (especially one in the brig area) across the shuttle, sometimes when the shuttle rotates all the fire alarms will trip and it's especially annoying that the only fire alarm is at the very back of the shuttle. Remember: fire alarms are area based. If one goes off in an area, they all flip.

Strong mapping work otherwise. Feel free to mark your PR as "Ready for Review" when these are addressed.

**Pull request merged**
