### PR TITLE
Removes romerol from surplus crates

### PR DESCRIPTION
**Pull request by xenon-difluoride**
:cl: Astatineguy12
balance: Surplus crates no longer contain romerol
/:cl:

Romerol is supposed to be balanced around only being obtainable if traitors team up (it's also not discountable for this reason), and having single traitors being able to get it if they're lucky (or nontraitors, considering null crates exist) completely undermines it. ~~It also uses up a lot of value in the crate, which could be annoying if you don't like using it.~~

Edit: github doesnt have a strikethrough button and isnt obvious that you can strikethough anyway

### CODE REVIEW

**Comment by Robustin** [comment]
The whole points of creates is to have random shit, so saying "its annoying if you dont want it in a crate" is a silly argument.

**Comment by AlexTheSysop42** [comment]
Possibly so, but that isn't the main reason I'm removing it, I'll edit it to not draw focus away from that

**Comment by ExcessiveUseOfCobblestone** [comment]
It was PR'd as a reward for traitors teaming up so 👍

**Comment by Dorsisdwarf** [comment]
^ what cobby said. If you want zombie memes, make a friend over :t

**Comment by 81Denton** [comment]
i unded pls nerf

**Comment by Robustin** [comment]
Its still a reward for teaming up, but that doesn't mean it has to be exclusively for teaming up.

**Comment by Shadowflame909** [comment]
This exact same thing happened with holoparasite injectors, for surplus crates and the null crates on the cargo shuttle. More then half the time, I get the same exact surplus crate junk. a hardsuit, a stimpack injector, and a sketchin gun. Why remove these things from surplus crates? Doesnt that remove the potential randomness of the surplus crate? Or should we just expect the same pseudo-solo op junk that we always get?

**Comment by ExcessiveUseOfCobblestone** [comment]
@Shadowflame909 you shouldn't expect good traitor gear simply by buying the forever-coveted 6tc traitor item that doesn't delete on use. If you want the good traitor gear, spend your TCs on the item over the emag.

A round ruiner should not be because RNG favored you.

**Comment by Shadowflame909** [comment]
I for one don't really care too much about romerol, but like I said beforehand. Removing things from the surplus crate because potentially "He got something too good, Jesus christ no good things should be in the surplus crate." Will only lead to people either not buying the surplus crate. Or basically being able to meta what they'll get every time with the surplus crate, because everything keeps getting removed from there. Reee

**Comment by AlexTheSysop42** [comment]
This isn't because it's too good. This is because the whole point of _this one item_ is that you have to team up to get it.

**Comment by juanototo2** [comment]
13 downthumbs, too bad maintainers don't consider the emojicracy

**Comment by MimicFaux** [comment]
If you're removing it from surplus crates, be sure to keep it in Super Surplus crates, which require you to team up.

**Comment by AlexTheSysop42** [comment]
That would be cool, but seeing as super surplus crates are just surplus crates with a different starting value it would probably lead to snowflake code.

**Comment by ExcessiveUseOfCobblestone** [comment]
@MimicFaux pester me to do it post this PR if @AlexTheSysop42 doesn't want to

**Comment by ShizCalev** [comment]
image

**Pull request closed without merging**
