### PR TITLE
[READY]Fixes the horticultural waders sprite. No more hidden hands!

### PR DESCRIPTION
**Pull request by Krysonism**
## About The Pull Request
Adds handholes to the horticultural waders sprite, my bad for not understanding how suits work when i made the sprite.

## Why It's Good For The Game
The horticultural waders are one of the best clothing sprites I've ever made and i wear them every round instead of the shitty apron.

## Changelog
:cl:
fix: fixes the horticultural waders sprite by adding hand holes.
/:cl:

### CODE REVIEW

**Comment by bobbahbrown** [comment]
false positive on change? otherwise undocumented

image

**Comment by Twaticus** [comment]
looks like an accidental white pixel, many such cases!

**Comment by Krysonism** [comment]
> 
> 
> false positive on change? otherwise undocumented
> 
> image

I might have accidentally modified the sprite when checking where the hand holes go. I will fix this.

**Comment by ShizCalev** [comment]
bad pixel is south armor sprite's corner

**Comment by Krysonism** [comment]
> 
> 
> false positive on change? otherwise undocumented
> 
> image

Fixed

**Pull request merged**
