### PR TITLE
Ports fire blossoms

### PR DESCRIPTION
**Pull request by dragomagol**
## About The Pull Request
Adds fire blossoms from White Sands/Shiptest, a glowing lavaland plant. 

image

I wasn't able to find the original PR adding the flowers, so let me know if you find the proper source. The worn sprites were added in https://github.com/shiptest-ss13/Shiptest/pull/1233 by triplezeta. 

## Why It's Good For The Game
More diverse lavaland flora! And something for miners to wear to keep the dark away... 

## Changelog
:cl: tattle and triplezeta
add: fire blossoms from far off worlds have started blooming on lavaland
/:cl:

### CODE REVIEW

**Comment by Wallemations** [comment]
Isn't fire blossom a terraria flower?

**Comment by dragomagol** [comment]
I'm gonna be real I've never played Terraria 😔
But probably

**Comment by Shadowflame909** [comment]
Will pick them while the ash drake chomps on me. Very nice stuff and cute sprites!

**Review by ZephyrTFA — APPROVED** [review]
Honestly, I appreciate that you went through and cleaned up the entire file.

**Comment by AdipemDragon** [comment]
> But probably

oh no it's absolutely riffing off of the terraria fireblossom, and that's just cute
image

Also! I did find where shiptest added them, it's [this mining related pr](https://github.com/shiptest-ss13/Shiptest/pull/285), i think

**Comment by Wallemations** [comment]
If there's any concerns over the name being a direct rip we could always just rename them to something else like "Magma Blossoms"
I'm not a maintainer so I don't know the specifics on how directly referential something can be

**Comment by ZephyrTFA** [comment]
Based on how they look in game, an argument could be made that they are based on Fireblossoms from Terraria, but it is by no means a direct rip.

**Comment by Wallemations** [comment]
> Based on how they look in game, an argument could be made that they are based on Fireblossoms from Terraria, but it is by no means a direct rip.

I would 100% argue that they are a direct rip but again that's a maintainer issue not mine

**Comment by optimumtact** [comment]
if you're not directly copying the asset, which it doesn't appear to be

and the name fire blossom isn't trademarked, which it doesn't appear to be.

This should be fine.

**Pull request merged**
