### PR TITLE
plays a waterphone with every memorable event

### PR DESCRIPTION
**Pull request by Fikou**
## About The Pull Request

every memory created now plays a waterphone sound effect
https://streamable.com/a0wt1c

## Why It's Good For The Game

adds needed tension to the game

## Changelog

:cl:
soundadd: plays a waterphone with every memorable event
/:cl:

### CODE REVIEW

**Comment by ArcaneMusic** [comment]
Fikou NO

**Comment by squi1-rasb** [comment]
weeeeeeeOOOOOOOOeewwwww

**Comment by HugoOdaX** [comment]
SO TRUE

**Comment by AdipemDragon** [comment]
fikou, with all my heart i must say, this the Worst sound choice you could've selected, good job

**Comment by Jolly-66** [comment]
My eye twitches hearing this and I can hear the echos of an angry screaming brit (you get it if you get it)

**Comment by Mickyan** [comment]
YOU DONKEY

**Comment by MrMelbert** [comment]
does this play for everyone roundstart when they memorize their bank account information

**Comment by Ed640** [comment]
Time to start throwing kisses around and spam the waterphone!

**Comment by optimumtact** [comment]
you're a few months early for april fools

**Comment by Serxule** [comment]
maybe have it be different pitches instead of the same one? itd be less repetitive

**Comment by Fikou** [comment]
it is too cursed

**Comment by MrMelbert** [comment]
ironically this pr gave more player feedback to memories existing than the system has ever had

**Pull request closed without merging**
