### PR TITLE
Adds the ability to swap scanners and caps on mechs after they've been completed.

### PR DESCRIPTION
**Pull request by zxaber**
## About The Pull Request
Adds in the ability to remove and insert scanning modules and capacitors to mechs after they've been built. This is done by starting maintenance (via ID/PDA), using a wrench and then a crowbar to open the panel, and finally using the ID/PDA again to open the gui and drop the part you want to remove. A new part can be added afterwards while the panel is still open.

Removes the need for a screwdriver when replacing a power cell, and instead moves cells to the system that scanners and caps use.

## Why It's Good For The Game
Prior mecha code just ate the scanners/caps and assigned values. This allows you to make a mech with early-game parts, and then later upgrade it if you so choose.

## Changelog
:cl:
add: You can now replace the scanning modules and capacitors on a mech. Just use your ID on the mech after opening the panel during maintenance procedures to remove the part you want to replace, and then insert the new part afterwards.
tweak: Replacing a power cell on a mech no longer uses a screwdriver, and functions the same as the replacement steps for scanning modules and capacitors.
/:cl:

UI:
image
The dashed line borders and the content inside only show up if you have the mech's maintenance panel crowbarred open.

To-Do:
- [x] Ripley conversion needs to take the scanner and cap correctly now.
- [x] Autodoc compliance

### CODE REVIEW

**Comment by necromanceranne** [comment]
Thank fuck. zxaber coming in with the good content once again.

**Comment by CRITAWAKETS** [comment]
finally i can give miners firefighters before getting tier 4 parts

**Comment by cacogen** [comment]
that ui looks like a flash game a 14 year old made in 2005

**Comment by zxaber** [comment]
Making the UI look nicer is out of scope ‾\\\_(ツ)_/‾

**Pull request merged**
