### PR TITLE
Add appy slices

### PR DESCRIPTION
**Pull request by dragomagol**
## About The Pull Request
image

Delicious snacktime

## Why It's Good For The Game
Healthy snack good for kids

## Changelog
:cl:
qol: apples can now be sliced
/:cl:

### CODE REVIEW

**Comment by ZephyrTFA** [comment]
I want to be able to skin them too \:(

**Comment by dragomagol** [comment]
My spriting talents were really pushed to the limit with this one, I cannot conceive of a peeled apple sprite that doesn't just look like a shitty baseball

**Review by Wallemations — APPROVED** [review]
Finally a healthy alternative to fries for all the assistants on the station

**Comment by trexter5555** [comment]
how does this work with apples that contain custom reagents (from botany)

**Comment by CCC23** [comment]
apie sliceceasys

**Comment by admeeer** [comment]
speedmerge

**Comment by Loafin34** [comment]
> I want to be able to skin them too :(

should only be able to skin them with the heretic blade, as god intended

**Comment by nikothedude** [comment]
we're so back

**Pull request merged**
