### PR TITLE
NERFS BOOKS YES YOUR BOOKS LIBRARIAN NERF HIGH PRIORITY SPEEDMERGE

### PR DESCRIPTION
**Pull request by jughu**
rip bookbag storagecreeps

:cl: hyena
tweak:books can only hold 1 item now
/:cl:

[]: # (Please add a short description of why you think these changes would benefit the game. If you can't justify it in words, it might not be worth adding:)REMOVE STORAGECREEP

### CODE REVIEW

**Comment by coiax** [comment]
I don't really see what's wrong with this PR. I mean,  the classic fake book has a bottle of whiskey, not 7 first aid kits.

**Comment by ma44** [comment]
Imbalanced, counts as a ghetto storage implant

**Comment by Buggy123** [comment]
Okay but only if we can put books in books in books so we can force people to search through a endless matryoshka doll of WGW.

**Comment by Iamgoofball** [comment]
He's nerfing ALL storage

**Comment by jughu** [comment]
@iamgoofball i am the madmen

**Comment by ShadowDeath6** [comment]
why not make books only able to hold tiny items? I'd imagine a carved out hole is smaller than a box's storage capacity

**Comment by calzilla1** [comment]
Salt

**Comment by Kromgar** [comment]
@jughu is goof's alt i know it

**Comment by Iamgoofball** [comment]
Nope

**Comment by B00tz** [comment]
My plan to escape from perma with my toolbook is ruined.

**Comment by Core0verload** [comment]
reeeee the most useless job is good at something reeeeeeeeeee

**Comment by optimumtact** [comment]
yeah fix the bible carrying rediculous sized things

**Comment by jughu** [comment]
@optimumtact so sizing down what it can carry and keep the storage slots or size down and 7 slots?

**Comment by optimumtact** [comment]
7 slots is fine, the issue is the bible being hollowed out

**Comment by jughu** [comment]
@optimumtact i dont get exactly what you mean bibles always are hoĺlowed out

**Comment by optimumtact** [comment]
really? I thought it was a crafting action you had to do. anyway I"m saying nerf the amount thing sa bible can store and the problem goes away

**Comment by jughu** [comment]
@optimumtact bible is a subtype of hollowed books so if im right it should affect the bible too

**Comment by optimumtact** [comment]
oh I completely misunderstood this PR, I thought you were changing the storage slots of the book bag

**Comment by jughu** [comment]
Yeah this changes hollowed out books to 1 storage to prevent creep

**Comment by jughu** [comment]
Like i wouldnt nerf the bookbag itself i would do a sadness to ecbrd 😂

**Comment by jughu** [comment]
@korphaeron

**Pull request merged**
