### PR TITLE
Removes grab from disposal units

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
You can still disposal people by click+dragging

### CODE REVIEW

**Comment by PKPenguin321** [comment]
wasn't it changed to grabbing to stop cyborgs from disposaling people or something

**Comment by KorPhaeron** [comment]
@PKPenguin321 

Yeah but I fixed it months ago so that only carbons can clickdrag disposal

**Comment by bgobandit** [comment]
xenobiology is fucked by this :thumbsdown:

**Comment by KorPhaeron** [comment]
@bgobandit 

Not true

**Comment by Fox-McCloud** [comment]
Again, as with your other PR.

Why?

**Comment by Dorsisdwarf** [comment]
:-1

**Comment by Fox-McCloud** [comment]
...there was never an explanation for this.

**Comment by RemieRichards** [comment]
@Fox-McCloud there was, in the bus, Grab intent is going bai-bai

**Comment by Fox-McCloud** [comment]
Then...how will you table, or strangle, choke, etc?

**Pull request merged**
