### PR TITLE
Lets the Quartermaster send desk announcements

### PR DESCRIPTION
**Pull request by JohnFulpWillard**
## About The Pull Request

With the new mailing system, we have even more reason for the Quartermaster to be able to send announcements, especially when there's no one else working in cargo to manually deliver the mail.
The Quartermaster was recently added to Chain of command, so I thought this should be a cool thing to have. This doesn't bother ID trimming, Paramedics have the same kind of deal with EVA access.
Also fixes a potential problem with an Acting Captain Quartermaster getting Bridge access, but not being able to send Bridge announcements, which all heads of staff should get.

## Why It's Good For The Game

image

## Changelog
:cl:
add: The Quartermaster can now send announcements via the Requests console in their office.
/:cl:

### CODE REVIEW

**Comment by YakumoChen** [comment]
The Quartermaster is STILL not a head of staff though

**Comment by necromanceranne** [comment]
Let him yell over announcements, it's actually a useful tool for deliveries.

**Comment by ArcaneMusic** [comment]
Could you potentially make the text size of the QM's announcements smaller?

**Comment by JohnFulpWillard** [comment]
> 
> 
> Could you potentially make the text size of the QM's announcements smaller?

I dont know how I would go about doing that, it would either require making the QM's announcer a snowflake version, or QM's access specifically make it smaller, and even then I'm not sure how that would affect HoP/Captain using it

**Comment by maxymax13** [comment]
next you'll give him high volume headset and silver id and blue icon

**Comment by Fikou** [comment]
> Could you potentially make the text size of the QM's announcements smaller?

we already have a bridge announcement rc which is the same size as other announcements, i dont think its a big deal

**Comment by optimumtact** [comment]
QM is a head, by my eternal decree

**Comment by Zytolg** [comment]
Lizard QM

**Review by coiax — APPROVED** [review]
Code is fine. Shouting at people about Cargo special offers or to pick up their mail is fine.

**Pull request merged**
