### PR TITLE
[WIP] Adds the legendary spell AWOL

### PR DESCRIPTION
**Pull request by tralezab**
## About The Pull Request

Adds a system for spells that cannot be further improved to be turned into a new kind of spell, probably a very powerful one because it requires fully upgrading.

As an example, I added AWOL. it's the legendary version of disintegrate, and it puts the person hit in the absolutely-removed-from-the-freaking-universe-forever zone. If I want to promise one thing with this spell, it is that anyone hit with this isn't coming back.

## Why It's Good For The Game

Upgrading leading to stat changes are boring. Upgrading leading to transmuting the spell into new forms is not only cool but it makes wizard purchases more interesting, if you see a wizard running around with AWOL you know they put a lot of points into it (lets be honest you can't really work out if they upgraded it unless it's near instant level) and the wizard needs to consider if they want some cooldown upgrades, or go all the way for whatever the new spell is (for AWOL, it's just the extra perk of absolutely removing someone from coming back)

## Changelog
:cl:
add: New spell: AWOL! You can get it by fully upgrading disintegrate, and then upgrading it one more time...
/:cl:

### CODE REVIEW

**Comment by Whoneedspacee** [comment]
Stuff like this really makes me think the base wizard stuff should be nerfed but there should be ways to get wizard points mid round for your book.

**Comment by tralezab** [comment]
Would be really cool but would make people never play risky spells at the start to play safe, encourage a whole lot more camping waiting for spells to recharge so they can hit and run again, make the rare role even harder to play leading to new players flopping, and with that end up with even more 5 second wizard rounds

and yet i still kinda like the idea

**Comment by Whoneedspacee** [comment]
probably has its place in another gamemode tbh

**Comment by tralezab** [comment]
ragin mages says hello

**Comment by necromanceranne** [comment]
AWOL? Nah mate. Imprisonment is the spell name you're looking for. It's a 9th level wizard spell.

**Comment by Injazz** [comment]
also let it remove person from the crew manifest and any records for shit and giggles

**Comment by Tlaltecuhtli** [comment]
@Whoneedspacee maybe have one in random events

**Comment by daklaj** [comment]
Make staff of awol and wand of awol and add them to summon magic items

**Comment by ATH1909** [comment]
> AWOL? Nah mate. Imprisonment is the spell name you're looking for. It's a 9th level wizard spell.

But a single 8th level spell can bring them back.

This is a reference to a MtG card from one of the un-sets: http://gatherer.wizards.com/Handlers/Image.ashx?type=card&name=AWOL

**Comment by tralezab** [comment]
Okay okay it now removes from the manifest

**Comment by Arianya** [comment]
Looks interesting. Be fun to see what can be done for other spells "Super" form in future.

**Comment by tralezab** [comment]
I had a couple ideas, like blink becoming silent and placing a cardboard cutout, fireball becoming the world's shittiest boomerang and soul tap becoming a cooldown touch attack that siphons from others

**Comment by MrDoomBringer** [comment]
rod form becomes rod form but you can change direction mid flight

**Comment by MrDoomBringer** [comment]
forcewall becomming forcebubble where it just makes many more forcefields

**Comment by imsxz** [comment]
if the intention here is to make them 100% entirely unrevivable forever, consider pod cloning, wizard phylactery, and other such methods of revival.

**Comment by tralezab** [comment]
It deletes all pod records of you.

**Comment by Therapist1** [comment]
Spawn a jug of milk with the description: “There’s a small picture of [AWOL’d] on the side with the text “Have you seen me?”.” (secret synergy with bone mages)

**Comment by ATH1909** [comment]
You could roll my Shapeshift v2 idea (with superior forms to Shapeshift v1) into this, since I ran into issues trying to make a PR.

**Comment by tralezab** [comment]
I'll work on some more legendary spells once I get this merged.

**Comment by tralezab** [comment]
@Tlaltecuhtli maybe i'll make it place some milk somewhere on the zlevel with a special desc, sure

**Comment by tralezab** [comment]
Okay I didn't think about this but Disintegrate costs all of your points so in testing i can't afford AWOL... So I guess the Instant version will come with the spell change!

**Comment by tralezab** [comment]
will return if wizards get a way to gain points

**Comment by MrDoomBringer** [comment]
@tralezab are you sure disintegrate costs all of your points? That doesnt sound right

**Comment by Whoneedspacee** [comment]
Most of the max upgraded spells take all your points.

**Comment by MrDoomBringer** [comment]
ooooh, i didn't see that you had to max upgrade it

**Comment by MrDoomBringer** [comment]
just give wizards one extra spell point ez

**Comment by tralezab** [comment]
any 2 point spell that has the normal amount of levels will max out, This pr is perfectly fine to reopen and finish once there is a way for wizards to gain points through helping the crew

**Pull request closed without merging**
