### PR TITLE
Fixes being unable to buckle into chairs and beds

### LINKED ISSUE #11586: Janicart can't be ridden anymore
Steps to reproduce:
1. Have keys in hand and attempt to mount janicart
2. have your sprite move on to it but not buckle and can't drive it
3. cry
4. @Razharas  maybe ???

### LINKED ISSUE #11591: players can't buckle themselves to chairs
players can't buckle themselves to chairs

### PR DESCRIPTION
**Pull request by ghost**
Fixes #11591 
Fixes #11586 
Also changes buckling text to become present tense rather than past tense.
May want to speedmerge this after Travis is happy

### CODE REVIEW

**Comment by Dorsisdwarf** [comment]
Fixes #11586

**Comment by PKPenguin321** [comment]
pls speedmerge

**Comment by Xhuis** [comment]
### ___MERGE___

**Comment by Razharas** [comment]
Im so sorry
It was an accident

**Pull request merged**
