### PR TITLE
Moves backpacks into their own DMI and "standardize" some names

### PR DESCRIPTION
**Pull request by GuillaumePrata**
## About The Pull Request
I wanted to touch a backpack sprite and got mad with everything being on the same dmi file sooo... 
Creates a dmi for backpacks because we had everything shoved on the same `back.dmi` or `storage.dmi` which is a headache to work with.

I tried to standardize the name between backpacks, satchels and duffels and some minor clarity while I was there, stuff like:
`securitypack` -> `backpack-security`
`satchel-sec` -> `satchel-security`
`brokenpack` -> `bag_of_holding-inert`

Also made a new obj icon file for the ethereal backpack, it had it's own file for the mob worn icon so now both icons have their own dmi.
Probably should rename it to "species" if we ever add more species/lore related backpacks but that is a future issue. 

I didn't touch the inhand dmis or "standardize" their name, they are well split enough and just to avoid making a zillion changes on the same PR.
I might look into it if this PR is merged.

## Why It's Good For The Game
Giga DMIs are a pain to work with

## Changelog
Not player facing.

### CODE REVIEW

**Comment by GuillaumePrata** [comment]
Icondif bot showed me a stray pixel I added on an O2 tank sprite, I will fix in later today.

**Comment by Ebin-Halcyon** [comment]
image

Should move the grey backpack one pixel to the left so it's directly in the middle while you're doing this.

**Comment by GuillaumePrata** [comment]
> Should move the grey backpack one pixel to the left so it's level with the inventory outline while you're doing this.

Its not misaligned, the UI backpack is just 1 pixel wider.
Could change the backpack (and check if other backpacks are well centered while at it) to be fatter or the UI icon to be slimmer but that is for another PR.

**Review by dragomagol — APPROVED** [review]
Blessed

**Pull request merged**
