### PR TITLE
Moves Centcom Inspector to admin-only event

### PR DESCRIPTION
**Pull request by coiax**
No change in gameplay, Centcom Inspector is still an admin only event.

But this change will allow it to be easy to enable Centcom Inspector as
a random event, if this is decided in the future.

### CODE REVIEW

**Comment by kevinz000** [comment]
I'm sorry but I think you and I both know what will happen if this is EVER moved to a non-admin event..

**Comment by anconfuzedrock** [comment]
what the fuck is kevinz mad about lmao

**Comment by kevinz000** [comment]
I'm not mad about anything, but centcom inspectors, being adminspawned inspectors, have a lot of weight.
They shouldn't be EVER a random event, as then you might have people griefing with the role. Just my two cents?

**Comment by kevinz000** [comment]
ha lmao nvm @coiax i didn't read the top part. nvm go ahead but just saying this is going to be bad if it's ever made a random event.

**Comment by ExcessiveUseOfCobblestone** [comment]
There's no point of giving it the potential to be a random event.

**Comment by PKPenguin321** [comment]
Yeah, the way we spawn them right now works fine

**Comment by KingPhilipIII** [comment]
I've been a centcomm inspector before and actually did my job.
Roleplay?! *gasp
Heresy!

It was actually a lot of fun. I took notes on my clipboard, went around and inspected the department. I had a pAI that made snarky comments about the station. I made everyone address me as "Lord Inquisitor" and at the end after submitting my report I went back. I was graciously rewarded for my work with a meteor pen and a gyro jet pistol for round-end chaos.

**Comment by bgobandit** [comment]
I'm fine with this, it is very unintuitive for the way to spawn a CentComm inspector to be hidden behind the create antagonist "strike team" button

**Comment by coiax** [comment]
@bgobandit I'm not suggesting that we move Deathsquad to RNG, but I can also move ERTs and Deathsquads to the event list as well, if that's helpful.

**Comment by bgobandit** [comment]
Nah, those make sense being there, it's just a bit confusing to have a non-team non-death antagonist in that same list.

(I spawn inspectors from time to time, have been lucky enough to have people RP them well. I think I even left a note recently for someone who was particularly good.)

**Comment by Shadowlight213** [comment]
I would like to point out that making ANYTHING random event spawn on centcom is going to require a map redesign.
The new centcom has way too much stuff on it, and you can obtain access to an admin magic mirror, and deathsquad gear.
I'm gonna bet that random event inspectors will just use the centcom side console to send the ferry to the station, announce it to the crew, and bring them over to loot centcom.

**Comment by coiax** [comment]
Most of the time I see Centcom Inspectors, they get lost.

**Comment by optimumtact** [comment]
Admins don't want this and I know exactly where you think you are going with it and it's not going to happen.

Closing.

**Comment by coiax** [comment]
Where I'm going is opening it up to the possibility of making it RNG selectable with a one line change.

BUT FINE

**Pull request closed without merging**
