### PR TITLE
Resprites almost all the hair to modern standards by Crumpaloo

### PR DESCRIPTION
**Pull request by Iamgoofball**
## About The Pull Request
https://user-images.githubusercontent.com/4081722/169633427-1171b097-e107-473c-8b43-1faa6298f7c4.mp4

## Why It's Good For The Game

Hair resprite good. I also paid $250 for this hair resprite so it's even better.

## Changelog
:cl: Crumpaloo
imageadd: Resprites almost all the hair to modern standards by Crumpaloo
/:cl:

### CODE REVIEW

**Comment by necromanceranne** [comment]
They say icondiffbot is still compiling to this day...

**Comment by MrMelbert** [comment]
image

either joestar hair or sideburns seems to have artifacts when facing east.

**Comment by scriptis** [comment]
business hair 3 is now extremely unbusinesslike

before

image

after

image

i'm going to get fired from my business job for not getting a haircut

can you please give me a trim

**Comment by realthomas69** [comment]
pretty nice but the business hairs look worse

**Comment by AlamoTurtle** [comment]
Really not liking how some of them look, Wisp especially. Some things shouldn't be changed, some should. REALLY want further feedback before this gets merged.

**Comment by SethLafuente** [comment]
wisp hair cut looks like ass 
image
those are literary braids

**Comment by carshalash** [comment]
> business hair 3 is now extremely unbusinesslike
> 
> before
> 
> image
> 
> after
> 
> image
> 
> i'm going to get fired from my business job for not getting a haircut
> 
> can you please give me a trim

New business hair 3 sucks. Please allow the old one to be back.

**Comment by AlamoTurtle** [comment]
Like, legit, the best thing you could do if you really want these hairstyles which are questionable at best and awful at worst is to add an (alt) to each hairstyle you've added, so for example, Business Style 3 and Business Style 3 (Alt). Add, don't change/remove.

**Comment by Mooshimi** [comment]
A lot of what I'm seeing is looking like it meshes badly with the gradients. ex: Long Hair 3, Short Hair 80s(pictured) 

image

**Comment by Iamgoofball** [comment]
We're not going to be doing the alt thing, the replacements are staying replacements, but I'll talk to the artist about some touchups.

**Comment by AlamoTurtle** [comment]
Then a lot of people won't be happy to see their favorite hairstyles being merged in a way they don't like, Goof.

**Comment by SethLafuente** [comment]
> We're not going to be doing the alt thing, the replacements are staying replacements, but I'll talk to the artist about some touchups.

But why?

Pros
1.It fixes every possible player complain 

2.more options more diversity more customization

3.keeps people being able to use the drip they like

Cons

1.literary at worst 1 hour of coding

**Comment by Mothblocks** [comment]
The con is what would be essentially doubling the cost of hairs in the rsc, which *also* slows down the time it takes to generate preference assets (which is a regular huge contributor to round start initialization time)

**Comment by LemonInTheDark** [comment]
We are not going to just make alts of everything that you like until the end of time, making little snapshots of the game's art style so boomers can be happy.

If the new stuff is better use it. If it's not don't.
We code for tomorrow, not today. That's why we have the churn we do in the first place.

**Comment by SethLafuente** [comment]
> We are not going to just make alts of everything that you like until the end of time, making little snapshots of the game's art style so boomers can be happy.
> 
> If the new stuff is better use it. If it's not don't. We code for tomorrow, not today. That's why we have the churn we do in the first place.

this reasoning would be fine if the hairs didn't look nothing like before and literary didnt look good at all 

I want you to stare at me in the eyes and tell me that the wisp haircut looks good

**Comment by LemonInTheDark** [comment]
Brother I do not know pixel art from a dot between the spaceman's crotch. That's why we have spritetainers

**Comment by SethLafuente** [comment]
> Brother I do not know pixel art from a dot between the spaceman's crotch. That's why we have spritetainers

it isnt about knowing shit is about looking at a sprite before and then after and saying "yeah that looks better" and not saying "it looks so much worst" because if they looked better people wouldn't complain about it old or new players we love innovation and seeing the came change FOR THE BETTER nobody likes seen tiny little changes one by one for the sake of changes making the game worst but not affecting it that much that shit adds up

**Comment by AlamoTurtle** [comment]
Whatever the case, I feel some hairstyles really should not be changed from their original, Business Hair 3 and Wisp being two similars. Business Hair 3 is similar more to Business Hair 4 and CIA. Overall, I feel that with how divided the players are, merging this as is would only cause more complaints (especially from Seth and I). Also ensuring the gradients work with each hairstyle and the color maps are similar to the replaced hairstyle would also be important.

**Comment by CMDR-Gungnir** [comment]
I'm gonna be real with you chief, none of these really looked like an "improvement". There's no "visual quality" improvement in the vast majority of them. Half of them I can't tell the difference, and the other half people seem to dislike the change.

**Comment by Iamgoofball** [comment]
the spritetainers said they like it, so folks gonna deal

we're going to touch up the art a bit though on the broken assets

**Comment by carshalash** [comment]
These are completely different hairstyles. The greyscaling looks dreadful with lighter hairs and just makes it look grey. 
image

image
Why the fuck does it have cornrows?

**Comment by Iatots** [comment]
Put whatever advantage "modernizing" these sprites brings in the PR description instead of your tale of sunken costs.

**Comment by newfren** [comment]
why's business hair 4 look like I'm the frontman for my chemical romance

**Comment by carshalash** [comment]
image
greyscaling is jank on quite a few things.

**Comment by Twaticus** [comment]
these updates should be improving the quality of our hairs by fixing the jumbled flat pixel mess most of our hairs had and setting a sort of standard to build upon, which this pr accomplishes. they should still emulate the older hair, but cleaner. 

the reason this is TMd is to find the outliers which differ too far from its source. its a big visual change which affects everyones characters. comments with comparison photos and hair name included make things easier to fix. an explanation being included even better. less of "it looks stinky" more of "this hair is meant to look like xyz, but now looks like abc"

the greyscale may be affecting lighter hair colors in a negative way so its something to look into further

**Comment by NamelessFairy** [comment]
Using floor length braid #FFBBFF, as has been brought up a lot before the greyscale is really aggressive on lighter hair colors, the shading on this hair style in particular being pretty bad and feeling like it just has noise applied to it. Also the right and front views are not consistent, the right side and left side appear to be copy pastes and this causes the extended left side of the fringe of floorlength braid to cover the eye on the right side, where previously it did not. Overall, in my opinion are pure downgrade to the current hair for at least my own hair choice.

Comparison:
image

**Comment by Archie700** [comment]
Beehive looks completely different.
Old:
dreamseeker_ZddmsJZitL
dreamseeker_SS11yVVJh4

New:
dreamseeker_o6hhmyfU59
dreamseeker_vyaNyNuN8e

**Comment by AlamoTurtle** [comment]
> the spritetainers said they like it, so folks gonna deal
> 
> we're going to touch up the art a bit though on the broken assets

Well there's your problem: A vocal majority of players realize the issues with these hairstyles being changed for no particularly good reason and having their template greyscaled (Which fucks with many color options, mind you), and Spritetainers just give the "okay". $250 dollars well spent because a few people liked it and a lot more hated it. Good for you.

**Comment by MetalClone** [comment]
The spritetainers who constantly ignore player opinion to merge some of the most pillowshaded sprites ever approve of these, that checks out at least.
Also if we're all gonna complain and request changes, please revert the pompadour sprite it looks very different, and provides a very different feeling for the look.

**Comment by optimumtact** [comment]
mfw when this post will attract 250 individual MRP players who are deeply attached to a specific sprite for their static main to complain about how that specific sprite is worse.

FS-rIKnXsAcpgP6

**Comment by AlamoTurtle** [comment]
It takes looking at the sprite literally all the time to know it's a problem, so yeah, people who play will see an issue.

**Comment by itseasytosee** [comment]
Ponytails 1-3 look a little weird

**Comment by githubuser4141** [comment]
My 2c, it's a nice improvement to overall shading and makes a lot of hair styles look less 'flat' like cardboard for brighter colors especially. I like the new details from each angle especially, some of the old hairs blended in too easily with the skin or surroundings.

**Comment by Shadowflame909** [comment]
quiff still looks good.

**Comment by Cheshify** [comment]
90% of the old hairstyles look like solid blobs of colour slapped onto someone's head, these are better.

**Comment by Draggeru** [comment]
Give people an option to keep the old styles. Touch-ups can be good but some of these just look dreadful.

**Comment by conk444** [comment]
Screenshot (4)
What have you done to the Oxton hairstyle?! This is completely different from the original Oxton! My character is ruined, and I am outraged.

**Comment by optimumtact** [comment]
> Give people an option to keep the old styles. Touch-ups can be good but some of these just look dreadful.

defeats the point dumbass

**Comment by LemonInTheDark** [comment]
> Give people an option to keep the old styles. Touch-ups can be good but some of these just look dreadful.

https://github.com/tgstation/tgstation/pull/67184#issuecomment-1133822413

**Comment by SethLafuente** [comment]
As I see oranges approval I see this is gona merge or its gona get merged so please remove the braids from wisp hair cut 
image

and make the front top look like the wisp haircut
image

**Comment by Pandarsenic** [comment]
While we shouldn't keep the entire stable of both sprite sets, we _should_ definitely keep an eye on which old haircuts are **good** and **don't really resemble any of the new ones**. I don't think there are a lot, but there are definitely a few that we should hold over.

**Comment by MMMiracles** [comment]
you made the pompadour better so this is a good pr ignore everyone else

**Comment by Miczu555PL** [comment]
Nuke dis ples.

**Comment by AlamoTurtle** [comment]
> As I see oranges approval I see this is gona merge or its gona get merged so please remove the braids from wisp hair cut image
> 
> and make the front top look like the wisp haircut image

Old
oldwisp
The "Improved" version
newwisp

Like, cmon. Just don't touch haircuts that were good. Literally only change those which seemed problematic in the first place instead of letting a bad apple ruin the whole bunch.

**Comment by Jamarkus127** [comment]
@AlamoTurtle did grey-scaling give visible nipples through clothes?

**Comment by Iamgoofball** [comment]
@Jamarkus127 jesus christ i hope not

**Comment by Jamarkus127** [comment]
@Iamgoofball Nah I checked it. it only is with the midriff. it gives both guys and girls a pair of boobs with visible nipples.

**Comment by conk444** [comment]
> If the new stuff is better use it. If it's not don't. We code for tomorrow, not today. That's why we have the churn we do in the first place.

"if it's better". And it's not better. It's a replacement, and not a better one, at that. Sure, there were some hairstyles that could do with touchups, but these new sprites completely changed the hairstyles, and most of them don't even have the same style to them. Saying these sprites are better is like saying nobody should use car insurance because home insurance has better benefits for your house, or saying nobody should eat at Taco Bell because Olive Garden has better Italian food; it's not relevant when that's simply *not* what people want. These new styles are better at carrying a, while valid, entirely separate feeling. What the people want is tacos and Baja Blast, what the people want is saving on mechanics when their car gets struck into by the people who though this was a straight upgrade to the original hairstyles. The thing is, my analogy doesn't really work so good because people actually like Olive Garden and home insurance, whereas only five people like the new hairstyles, compared to the hundreds of people who downright hate them.

**Comment by necromanceranne** [comment]
On the topic of missing sprites, Half-Shaved is missing it's right facing sprite.
missing sprites half-shaved

**Comment by Wallemations** [comment]
image
Bro I'm in a goddamn emo goth band now, what happened?
This isn't even the same haircut it used to be.
image

**Comment by Arctrooper8** [comment]
As people such as Seth and Alamo turtle have already pointed out the Wisp still needs quite a bit of work, so please improve and fix the new wisp before merging it.

1. The wisp braids don't look right and there has never been any indication before that wisp was a braided style, this isn't an update but a complete design change one I feel is for the worse. (The braid stuff would be cool as it's own new hairstyle though!)

Before: (It is quite clearly presented as a ponytail with no indication via shape or shading that it might be braided)
image
image
image
image

After:
image
image
image
image


2. The north and south sprite appear to have had some pixels shaved off the top which lowers the overall quality of the sprite whilst making it feel oddly flat, please add them back.

Before:
image
image

After:
image
image

Overall I hope that you take the constructive criticism that many people are providing not as an attack, but merely your fellow players who also wish for the game to be its very best. Open source is a beautiful thing where anyone can contribute or comment, and we should always take care to listen to helpful detractions of our PRs which might expose flaws that we can fix for an even better product.

**Comment by Jamarkus127** [comment]
> Overall I hope that you take the constructive criticism that many people are providing not as an attack, but merely your fellow players who also wish for the game to be its very best.

this is a goof PR, hes just gonna call us sex pests.

**Comment by Arctrooper8** [comment]
> Brother I'ma be honest this seems really patronizing. Might just be the royal we but like...

I apologize if I came off as patronizing, that was not my intention. I do believe that this PR has a lot of potential, however as many people have pointed out it has issues (enough issues that it had to be drafted in fact).
There are many genuinely helpful comments, and although there are some unhelpful comments (even if some of them are really funny) that doesn't mean all criticism ought to be disregarded.
And with a game design such as Open source where anyone can contribute either thought or code, it is even more important to listen to others. This is why I used the we, it is supposed to represent the playerbase and also coders. I've made PRs for TGMC and comments often help me improve my code or make the PR itself more fun or interesting.
Goof has a history of disregarding criticism whether it is bad or good, it's why I put so much effort into my comment and implored him to take others comments into account too.

Also floor-length bedhead is obviously superior
image

**Comment by Mothblocks** [comment]
> Real talk, fuck happened here

THE POWER OF RUST

**Comment by Nabski89** [comment]
The Pompadour(Big) looks like shit.

The front has dropped onto the forehead, which I guess is how it is different from normal pomp now rather than being taller and the sideburns have done ??????
The side has lost most of the sideburns (mildly disappointing) but also has a floating **missing pixel** between the bottom right of the hair and the back of the head.
The back uses the **same** sprite as the normal Pompadour, which means the hair between the side and the back are different lengths.
image
image

**Comment by gitbirb** [comment]
What a good time to be bald in ss13.

**Comment by AffectedArc07** [comment]
@Mothblocks BEHOLD
image

THE POWER OF ~~AN ANGEL~~ RUST

**Comment by Iamgoofball** [comment]
chrome_9QbvxLo1Hw
@AffectedArc07 icondiffbot1 was still faster though

**Comment by AffectedArc07** [comment]
> chrome_9QbvxLo1Hw @AffectedArc07 icondiffbot1 was still faster though

No its just a glitch dw about it shhhhhh

**Comment by FlamingCheese** [comment]
image
ponytail 4 has a missing east facing sprite

**Comment by TheRealScarHomie** [comment]
easiest way to burn 250$ ever

**Comment by Mothblocks** [comment]
On pause until #67679 is merged (or if there's reason to believe it'll take too long to be merged)

@tgstation/sprite-team Have you formed an updated opinion on this? Has been up for a while

**Comment by theselfish** [comment]
Goof. What kind of job do you have that you can burn $250 on SS13?

**Comment by Twaticus** [comment]
> On pause until #67679 is merged (or if there's reason to believe it'll take too long to be merged)
> 
> @tgstation/sprite-team Have you formed an updated opinion on this? Has been up for a while

yeah just needs the broken/missing stuff fixed. we'll do whatever aesthetic fixes in post

**Comment by Mothblocks** [comment]
@Iamgoofball We merged screenshot tests, can you merge from master so it runs here?

**Comment by Mothblocks** [comment]
It's been 2 weeks and this still hasn't gone anywhere, let me know if you want to reopen

**Pull request closed without merging**
