### PR TITLE
why plus a minus value and not just minus the value...

### PR DESCRIPTION
**Pull request by silicons**
damnit jmad this has been triggering me for months

### CODE REVIEW

**Comment by ma44** [comment]
How to get good boy PR points the easy way

**Comment by Iamgoofball** [comment]
>when you want to merge conflict a revert PR

**Comment by ShizCalev** [comment]
i was looking at that and asking wtf too

**Comment by ShizCalev** [comment]
https://github.com/tgstation/tgstation/blob/8730cf2fa96a2c72ac8ce89c5bfc6218104349fc/code/game/turfs/simulated/floor/plating/asteroid.dm#L196

https://github.com/tgstation/tgstation/blob/ff3f84ab81761802f34310e65627c9ff591232a4/code/modules/mob/living/simple_animal/friendly/drone/visuals_icons.dm#L89

should probably hit these too

**Review by Cyberboss — CHANGES_REQUESTED** [review]
What Shiz said

**Comment by lzimann** [comment]
you really don't like making good titles huh

**Comment by kevinz000** [comment]
fixxed

**Review by Cyberboss — APPROVED** [review]

**Pull request merged**
