### PR TITLE
Refactors mothweek check

### PR DESCRIPTION
**Pull request by LemonInTheDark**
## About The Pull Request

Mothweek HAS SIDE EFFECTS
Checking it on a day that causes a week offset will currently cause that week offset to persist
That's dumb.

Also it's not very expansive, only covers a slim set of possibilities.

Instead, lets build something to generate all passing days over a period of time, maybe 3 months out of 2 years.
Then we'll crosscheck that against some predecided "ok" dates

If either list disagrees with each other, we'll fail. That way we can't miss an edgecase. or have issues with side effects

## Why It's Good For The Game

I like this pattern.

### CODE REVIEW

**Comment by timothymtorres** [comment]
Pretty sure this fixes #60623

**Comment by LemonInTheDark** [comment]
It doesn't, I couldn't replicate that even if I manually input the date. I actually made this test to catch it and it didn't.
I'm not actually changing mothweek's logic, just the unit test
Makes me think the time inputs were wrong, not totally sure tho.

**Review by Mothblocks — CHANGES_REQUESTED** [review]
Nit: You call it yyyy/mm/dd, but your tests suggest it's yyyy/m/d (it's not zero padded)

**Comment by LemonInTheDark** [comment]
> Nit: You call it yyyy/mm/dd, but your tests suggest it's yyyy/m/d (it's not zero padded)

oh is that the syntax? good point will fix

**Pull request merged**
