### PR TITLE
Robotics can print cybernetic organs (also new upgraded cybernetic heart)

### PR DESCRIPTION
**Pull request by coiax**
:cl: coiax
add: Robotics can print cybernetic hearts, lungs and livers at their exofabricators (along
with their upgraded versions).
add: Added upgraded cybernetic heart, just like the regular cybernetic heart,
that doses you with epinephrine when unconscious. But the upgraded version generates a new
dose after five minutes.
/:cl:

Robotics should be able to upgrade people with cybernetic organs. Medical want the organs
to save people's lives, Robotics want the organs for augmentation giggles.

Also, there was an upgraded cyberlungs and cyberliver, so I just made an upgraded
cybernetic heart as well.

### CODE REVIEW

**Comment by Tlaltecuhtli** [comment]
maybe make it give atropine instead of epi?

**Comment by zxaber** [comment]
[EMP vulnerability intensifies]

**Comment by necromanceranne** [comment]
> maybe make it give atropine instead of epi?

That will pull you out of crit, which would be absolutely disgusting. That said I guess if people wanna run around with cyber hearts they get what comes to them when someone EMP's them.

**Comment by Steelpoint** [comment]
Mechanical organs are more appropriate for their benefits since you need to get someone else to perform the surgery on you, leaving you vulnerable.

**Comment by anconfuzedrock** [comment]
Lmao dude nanites podpeople viruses and loadsa other shit can heal you outta crit including an implant, a goddamn heart transplant giving atropine aint gonna be cancer

**Comment by necromanceranne** [comment]
There is absolutely nothing stopping you from having all of these at once. Adding atropine to the heart pushes this ever further into ludicrous amounts of invulnerability to death to the point that you'd make a ling look like a joke (also gosh lings would have a hell of a time with all this and fleshmend). Epi is just fine. It does its job of keeping you alive longer while not necessarily making you ling-lite, which is already readily handled by nanites and viruses.

**Comment by MACIEKBAKI** [comment]
but can you eat it

**Comment by anconfuzedrock** [comment]
Lmao if they do all those things at once just finish em off once you crit em, but you won’t have to because that will never happen. At that rate a cavity implant with atropine would be just as realistic

**Comment by Ziiro** [comment]
@SpaceManiac It'd probably be a good idea to add robotic limbs to the medical lathe, now that you mention it.

**Comment by ExcessiveUseOfCobblestone** [comment]
If you're waiting to the point where someone has undergone surgery and has been sitting in chem getting chemstacked then you should have to prepare a bit better anyways than bruteforcing your way to victory.

**Comment by coiax** [comment]
@ExcessiveUseOfCobblestone Anything blocking the merger of this PR?

**Comment by ExcessiveUseOfCobblestone** [comment]
mmmm the conflicts.

**Comment by tgstation-server** [comment]
Your Fix/Feature pull request delta is currently below zero (-2). Maintainers may close future Feature/Tweak/Balance PRs. Fixing issues or helping to improve the codebase will raise this score.

**Pull request merged**
