### PR TITLE
Tweaks ripleys pressure requirements for mine/speed buff

### PR DESCRIPTION
**Pull request by Aloraydrel**
tweaks the pressure required from 20 to 40kpa since lava world is 37.9kpa.

### CODE REVIEW

**Comment by Cheridan** [comment]
i'm sorry sir but it seems this is a very unpopular pull request

**Comment by PKPenguin321** [comment]
the fuck why

reopen this

**Comment by Shapsy** [comment]
>half of the downvotes are goof
>no explanation
>this was a feature anyway

**Comment by Iamgoofball** [comment]
i only downvoted it once though?

**Comment by optimumtact** [comment]
I downvoted it to see if I could influence people without actually leaving a comment

**Comment by Shapsy** [comment]
iamgoofball iamgoofballsecondfork and andrewjacksonthesecond are all yours I thought

**Comment by Cheridan** [comment]
We have been made aware of possible emoji fraud and our team of analysts will be looking over the situation.

**Comment by Iamgoofball** [comment]
andrewjacksonthe2nd is a drinking buddy of mine

iamgoofballsecondfork is an imposter with similar views to mine

**Comment by Zilenan91** [comment]
TheAssistant is your holosexual twin brother from Taiwan I'm guessing?

**Comment by xxalpha** [comment]
Change the movement speed also?

**Comment by Fox-McCloud** [comment]
makes sense :+1: 

RIPLEYs are horrendously slow to begin with--this was added in so it's not a complete drag when doing mining with them.

**Comment by Iamgoofball** [comment]
@Zilenan91 yes

**Pull request merged**
