### PR TITLE
Makes (Allergy) Dogtags Tiny items, able to fit into wallets.

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request
Title.

~~For future thought: maybe examining (double-examining?) somebody with a tag in their wallet (in the ID slot) or attached to their uniform should show what it says? Would make it easier to read.~~
Okay so it DOES work on uniforms. But still, if somebody better at coding wants to try to make it also do that in wallet that'd be neat.
## Why It's Good For The Game
I mean, it's not like it hurts. 
Plus, you can fit a lighter, but not a little tag?
## Changelog
:cl:
qol: Allergy Dogtags (and any other dogtags, really) are now Tiny items and can fit into wallets.
/:cl:

### CODE REVIEW

**Comment by MrMelbert** [comment]
> maybe [double-examining] somebody with a tag [attached to their uniform] should show what it says? 

It, already does this. Unless i'm confused what you mean.

**Comment by OrionTheFox** [comment]
> > maybe [double-examining] somebody with a tag [attached to their uniform] should show what it says?
> 
> It, already does this. Unless i'm confused what you mean.

As in, without having to take the uniform and thus tag off of people, just examining the person to read it. Doesn't... seeeeem to let you do that. 
Was just a spitball idea, would pair well with letting it go into the wallet too.

**Comment by MrMelbert** [comment]
> As in, without having to take the uniform and thus tag off of people, just examining the person to read it. 

Like... this?

https://github.com/tgstation/tgstation/blob/54caaef1743729670bce69058bbc7fff852ca78b/code/modules/clothing/under/accessories/badges.dm#L141-L160

**Comment by OrionTheFox** [comment]
> > As in, without having to take the uniform and thus tag off of people, just examining the person to read it.
> 
> Like... this?
> 
> https://github.com/tgstation/tgstation/blob/54caaef1743729670bce69058bbc7fff852ca78b/code/modules/clothing/under/accessories/badges.dm#L141-L160

Oh. Neat. That just doesn't work downstream. Cool.

**Comment by MrMelbert** [comment]
(Could also be broken here, that would be funny)

**Review by MrMelbert — APPROVED** [review]

**Comment by OrionTheFox** [comment]
> (Could also be broken here, that would be funny)

Might be. I'll launch up a test server and check.

**Comment by OrionTheFox** [comment]
> > (Could also be broken here, that would be funny)
> 
> Might be. I'll launch up a test server and check.

Tested, it's just downstream. Somebody's overriding examine stuff. This is TG:
image

We don't even have the fun examine boxes :(

**Comment by projectkepler-ru** [comment]
wow that's foxed up

**Pull request merged**
