### PR TITLE
Fixes Plastic Surgery Grammar Issue

### LINKED ISSUE #23704: plastic surgery has grammar issues
Fishes-For-Work alters Joey Philips's appearance completely, he are now Morgan Fields!

>he are now

GRAMMAR BUGS REEEEEEEEEEEE

### PR DESCRIPTION
**Pull request by JohnTheDonut**
## **Fixes Plastic Surgery Grammar Issue**
Changes plastic surgery appearance changing from saying "Zion Murphy  are now Murphy Zion" to something that makes more sense within the English language "Zion Murphy  is now Murphy Zion"

## **Changelog**
:cl: Tofa01
Fix: Fixes grammar issue when changing someones appearance via plastic surgery.
/:cl:

## **Fixes #23704**

### CODE REVIEW

**Comment by Cyberboss** [comment]
Read your PR description XD

**Comment by Tofa01** [comment]
Errrrrrrrrrr, no one saw that _and if you did then attempt to remove it from your brain._

**Comment by Supermichael777** [comment]
Imgur

**Comment by Tofa01** [comment]
You know what, i think i might go get my eyes checked...... Yeah, i think that's a good idea.

**Pull request merged**
