### PR TITLE
buffs cat ears

### PR DESCRIPTION
**Pull request by ghost**
-screeches autistically-

I CANT FIND ANYTHING TO CODE SO I'LL JUST REEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE

im gonna close this in 5 minutes calm down

### CODE REVIEW

**Comment by Iatots** [comment]
tehee

**Comment by MoreRobustThanYou** [comment]
@Iamgoofball how come you have special shitposting privileges reeeee

**Comment by kevinz000** [comment]
you're not even funny or interesting

**Comment by MoreRobustThanYou** [comment]
@kevinz000 uehryu39iuj4hujuwijenrieojrhriejkrt6tredrt

**Pull request closed without merging**
