### PR TITLE
You can now disable automatic review dismissing

### PR DESCRIPTION
**Pull request by ghost**
FOR FUCKS SAKE THIS CAN BE SO ANNOYING, 'SPECIALLY ON HIPPIE

### CODE REVIEW

**Comment by ninjanomnom** [comment]
It's almost like you *want* people to merge unreviewed commits

**Comment by MoreRobustThanYou** [comment]
_fix spelling_ HAHAHA YOU HAVE TO REVIEW AGAIN

**Comment by JJRcop** [comment]
Put this in secret.php too, since that's where you pit config options

**Comment by JJRcop** [comment]
Right after this line https://github.com/tgstation/tgstation/blob/dfd9e58907ffbc849400426568784724782bef02/tools/WebhookProcessor/secret.php#L53

**Comment by JJRcop** [comment]
Also default to true please

**Pull request closed without merging**
