### PR TITLE
Removes Revolution gamemode and replaces it with secret extended.

### PR DESCRIPTION
**Pull request by Buggy123**
You know how literally every single Rev round, its shit and at least 1 person asks for it to be removed? Well here you go.

Apparently editing the config does nothing serverside so for this to work I had to literally replace it with extended.

Also its secret extended anyway so it'll basically end up exactly the same but with nations instead of revs.

### CODE REVIEW

**Comment by lzimann** [comment]
rev is good and this pr is really bad

**Comment by Buggy123** [comment]
24 hour rule reopen immediately.

**Comment by coiax** [comment]
This PR is really bad though...

**Comment by ishitbyabullet** [comment]
if you're gonna replace rev then replace it with space marine wars

**Comment by Buggy123** [comment]
Well i'd just disable it in the config but that's one of the shitty files that isn't synced with the git.

**Comment by Buggy123** [comment]
Also name one other roundtype where literally >50% of the time someone asks for it to be removed.

**Comment by PKPenguin321** [comment]
see: every round type
i've seen people complain that nuke ops should be removed after they die to them

**Comment by arsserpentarium** [comment]
Idea of gamemod.
Captain has objective to validhunt 4 traitors+clown. Hop has objective to deliver to brig 5 criminals.Rd has objective to bomb station. CMO have objective to inject someone with soporific hypospray and put on him straightjacket.
Objective of crew is notice, that commanders gone nuts and space the fuckers.
possibly not space, but call special penal shuttle and deliver them in brig room with shame.

**Pull request closed without merging**
