### PR TITLE
Srm-8 rocket pods missiles no longer spin in flight

### LINKED ISSUE #23470: srm-8 rocket pods missiles spin in flight
simple spriting error or something that happened once I made them into proper projectiles. I don't know how to fix it, but im sure the fix is simple

### PR DESCRIPTION
**Pull request by Supermichael777**
Fixes #23470

### CODE REVIEW

**Comment by vcordie** [comment]
thank you for doing what im too stupid to do.

**Comment by Militaires** [comment]
:-1: spinning rockets is funny keep it

**Comment by KorPhaeron** [comment]
You didn't test this did you

**Comment by Supermichael777** [comment]
yes

**Comment by Supermichael777** [comment]
also rocket pod>shoots missiles
at missile launcher>shoots rockets

**Pull request merged**
