### PR TITLE
The firelock on Box's circuit lab no longer covers up the room's airlock

### PR DESCRIPTION
**Pull request by ghost**
:cl: Xhuis
fix: The firelock below the Circuitry Lab airlock on Boxstation will no longer cover it up when the airlock is open.
/:cl:

This has been irking me for a bit, so I fixed it!

### CODE REVIEW

**Comment by Mark9013100** [comment]
This happens to all the circuit lab airlocks on the other maps too.

**Comment by Xhuis** [comment]
If I get a chance I'll move it on the others.

**Comment by Cyberboss** [comment]
Isn't firelocks appearing over airlocks the standard?

**Comment by Xhuis** [comment]
By my phrasing, I mean that while the firelock and airlock are both open, the firelock blocks you from being able to close the airlock because it was placed after the airlock was placed in the map maker. This just moves the airlock above it; when the firelock is closed it will still be over the airlock.

**Pull request merged**
