### PR TITLE
Fixes Wood Being Invisible.

### PR DESCRIPTION
**Pull request by Kerbin-Fiber**
:cl:
fix: Wood is no longer invisible
/:cl:

[why]: # Wood was invisible since someone somehow fucked up the Icon for wood. No clue how that happened.

See: #31361 and #31360

### CODE REVIEW

**Review by ShizCalev — DISMISSED** [review]

**Comment by praisenarsie** [comment]
@Bawhoppen possibly broke this

**Comment by Bawhoppen** [comment]
Yes I broke it you don't need to play the blame game

**Comment by Kerbin-Fiber** [comment]
Everyone makes mistakes from time to time, it's okay!

*Kerbin-Fiber hugs Bawhaoppen.*

**Comment by Kerbin-Fiber** [comment]
what no fuck
wrong thing ree

**Comment by Kerbin-Fiber** [comment]
See, now I made a mistake, reeee

**Comment by Kerbin-Fiber** [comment]
How the fuck do I take out that last commit, ree.

**Comment by Bawhoppen** [comment]
git reset --hard [commit hash]

Use this hash as your previous one: 7653b02167652ca77d2079fbec89cdfb12a3098f

**Comment by Bawhoppen** [comment]
That also works

**Comment by Kerbin-Fiber** [comment]
Yeah, it's weird, I'm weird

**Pull request merged**
