### PR TITLE
Removes phantom gas effects on space tiles

### PR DESCRIPTION
**Pull request by TetraK1**
## About The Pull Request
Previously destroying or deconning a turf with gas overlays into space leaves the overlays on the resulting space tile, which won't change until some other turf is made there.  Now overlays are removed when space turfs initialised, in the same way done in /turf.

No idea if what I've done affects anything like performance or other behaviour, expecting to get yelled at.  Done some testing though and seems fine.  However, there seems to be a second bug affecting this behaviour where sometimes the overlays still stay when explosions happen, which I think might be gc related?

## Why It's Good For The Game
Irritating gas overlays on space tiles, where there's no gas anyway.

## Changelog
:cl: Tetr4
fix: Turning a tile with gas effects into space now gets rid of the effects.
/:cl:

### CODE REVIEW

**Comment by SpaceManiac** [comment]
Original fix: #38447
Broken in: #38644

**Review by SpaceManiac — DISMISSED** [review]
Thank you for fixing this, I feel silly for breaking it given how much this bug annoyed me personally

**Review by SpaceManiac — CHANGES_REQUESTED** [review]
Actually, does this work with AI static? Might need to call `visibilityChanged()` to make sure the AI static is put back after the `.Cut()`

**Comment by optimumtact** [comment]
@TetraK1 please see above ^

**Pull request merged**
