### PR TITLE
RD traitors can now purchase an Omnilathe board.

### PR DESCRIPTION
**Pull request by ghost**
:cl: Awesine
add: Traitor Research Directors can now purchase an Omnilathe board.
add: An Omnilathe board is just a non-department locked Protolathe board.
/:cl:

[why]:
Thought it was a good idea. High-cost item to be able to print department-locked stuff.
Not exactly stealthy either. You have to build it somewhere, steal materials for it, and Security will probably arrest you for it. Unless you offer them items from the Lathe. Arr Pee.

### CODE REVIEW

**Comment by kevinz000** [comment]
Please stop coding things that I already specified as a joke.
 No one will valid you if they can get items from it.
There is no stealing materials when you're the Rd who can just take them all without suspicion.

**Comment by GunHog** [comment]
I would not hide it! I would just replace the old, inferior one. Not one Scientist would bat an eye. Sec might actually thank you for putting research into weapons tech.

**Comment by awesine** [comment]
>Please stop coding things that I already specified as a joke.

hi yes i acknowledge you think this is a joke

i took your joke, and thought the words,
"huh this is actually a good idea"
then i coded it

**Comment by awesine** [comment]
>I would not hide it! I would just replace the old, inferior one. Not one Scientist would bat an eye. Sec might actually thank you for putting research into weapons tech.

people are going to see you dismantling it

**Comment by Iamgoofball** [comment]
oh my god

@Cyberboss close this transparent garbage

**Comment by awesine** [comment]
@Iamgoofball 
why

**Comment by awesine** [comment]
would it be better if it was 20 TC?

**Comment by Iamgoofball** [comment]
R&D isnt getting their protolathe back

**Comment by awesine** [comment]
@Iamgoofball 

which is why this is 15 TC traitor itme

**Comment by FantasticFwoosh** [comment]
Doesn't seem thematic to just have something people will spend your unspent TC (open uplink etc) just to return to old RnD in a beneficial sense.

**Comment by awesine** [comment]
@FantasticFwoosh 

Which is why this is highly expensive.

**Comment by FantasticFwoosh** [comment]
> Which is why this is highly expensive.

So your reasoning is that it'll never be seen in use, wherin you just build & place down elsewhere from the captured traitor machine by deconstructing it down to its board & frame. Stations are a small place, either it'll be a 'friendly co-operative' traitor cop-out or the AI will just shut off the room APC power and put you in the dark once you're called out.

**Comment by awesine** [comment]
english please i don't understand anything in that paragraph

**Comment by awesine** [comment]
and from what I could understand, yes, those are the risks and challenges of buying this for sweet sweet RnD tech.

**Comment by DoctoreMad** [comment]
You didn't even describe this item in a antagonistic way. That's just how friendly and puffy puffy it is.

**Comment by awesine** [comment]
how is it antagonistic?
well, it lets you print all those powercreep and powergaming items that were removed from regular science. This time, you actually have a reason to print these. You're a traitor!

**Comment by DoctoreMad** [comment]
>it lets you print all those powercreep and powergaming items that were removed from regular science. 

Well at least THAT makes some sense.

**Comment by awesine** [comment]
Was going to put quotes around 'powercreep' and 'powergaming' but I thought it wouldn't look good.

**Comment by arsserpentarium** [comment]
well, at least traitors will get non humilating protolathe.

**Comment by awesine** [comment]
>well, at least traitors will get non humilating protolathe.

**Comment by Spaceinaba** [comment]
do not add something that gets me arrested for installing omnilathes please and thanks

**Comment by awesine** [comment]
sorry bud

**Comment by awesine** [comment]
pranked

**Comment by Cyberboss** [comment]
If @KorPhaeron doesn't support this I don't think I'm going to let it through. It seems to help the crew moreso than the traitor

**Comment by Repukan** [comment]
Lmao @ RnD babies trying to add old RnD back.

**Comment by awesine** [comment]
@Repukan 
except this isn't old RnD.

**Comment by Repukan** [comment]
https://github.com/tgstation/tgstation/pull/34227

Suuuure bud.

**Comment by Repukan** [comment]
Maybe next time try adding the omnilathe board as megafauna loot lmao

**Comment by awesine** [comment]
I'm not F-OS.

**Comment by awesine** [comment]
And this doesn't have **ANYTHING** to do with Old RnD.

**Comment by awesine** [comment]
This is just a Protolathe board that can access all designs.

**Comment by Bawhoppen** [comment]
Antags work with crew all the time. This encourages it even more

**Comment by GunHog** [comment]
@awesine This is a good PR, please do not ruin it with poor arguments!

**Comment by kevinz000** [comment]
image
image

**Comment by awesine** [comment]
so a board included with ye techwebs is ye old rnd?

**Comment by awesine** [comment]
i don't know if you're serious or not @LetterN

**Comment by FantasticFwoosh** [comment]
> A syndicate specialist lathe would have been much more appropriate.

Seperate syndicate node tree so you can equip yourself & your blood brothers/collegues without copping out and admitting that unrestricted omnilathe designs is OP

- Print out items you researched instead of bought with your 20tc spent for the 'long game' at exaggerated syndicate costs, high in valuable metals and materials like regular thermal huds to replace thermal eyeballs, the typical RnD syndie stuff (silencer, large ebow) and some other repurposed pieces at high tech like disposable vindicators.

Much of the actual research designs need restructuring which is something i intend to do so we can have more personalised and relevant departmental lathes that aren't a forced division of omnilathe meme.

**Comment by Buggy123** [comment]
Just add this FFS why does everyone think that omnilathes are literally shit straight out of the devils anus.

If you hate omnilathes so much then you better remove free golems because they can make a unlimited number of them, and any miner that happens by their ship can _also_ get omnilathe boards if they have spare mining points.

**Comment by FantasticFwoosh** [comment]
^ that's the golem loot and reason to valid golems, just chase golems instead for omnilathe.

**Comment by FantasticFwoosh** [comment]
No, wage a all out war if you want the machine so badly.

**Comment by JohnMcLaime** [comment]
Lmao 15 tc investment, extra time getting minerals and hoping that random greytiders will decide not to waste your points from other rnd consoles/thermite into server room to decon it, just to get "late" access to mediocre items (they dont give much advantage. especially when compared to how much time it takes you to get them)?
You can speedrun maxcaps in 5 mins for 0 tc (surpassess anything in rnd), not to mention other op (as in too easy to accuire and use, hard to counter) weapons like lube and explosive lances.

**Comment by Cyberboss** [comment]
Give it up

**Pull request closed without merging**
