### PR TITLE
Makes slime plushies slightly more texan.

### PR DESCRIPTION
**Pull request by Wilchenx**
:cl: optional name here
Due to PTSD traumas from Biohazard level 5 incidents nanotrasen decided to make slime plushies more American :us: .
/:cl:

### CODE REVIEW

**Comment by praisenarsie** [comment]
>rating your own pr

tbh it's not even funny :(

**Comment by Anonmare** [comment]
Rating your own PR is such a loser thing to do lmao

**Comment by The-clown-known-as-Pepe** [comment]
@JJRcop that is the joke dump ass

**Comment by ExcessiveUseOfCobblestone** [comment]
@JJRcop what the fuck are those emojis you sick sick man

**Comment by Anonmare** [comment]
@JJRcop I'd make some sort of excuse but I'm too distracted by those fucking emojis. Jesus Christ man what the fuck

**Comment by JJRcop** [comment]
Samsung

**Comment by CosmicScientist** [comment]
Emojis were a mistake.

**Comment by JStheguy** [comment]
Yeah, kaomoji are the patrician way to express emotions.
♪┏(・o･)┛♪┗ ( ･o･) ┓

**Comment by CosmicScientist** [comment]
Japan was a mistake.

**Comment by ninjanomnom** [comment]
try again closer to april fools

**Pull request closed without merging**
