### PR TITLE
Morphine recipe update

### PR DESCRIPTION
**Pull request by Ordonis**
:cl: Ordo
fix: Fixes morphine recipe to avoid conflicts
/:cl:

### CODE REVIEW

**Comment by 81Denton** [comment]
Can't wait for the countless N2O explosions when people attempt this lmao

**Comment by yorii** [comment]
Did you even test this at all? Two of those reagents are gases.

**Comment by Ordonis** [comment]
It worked on my private serb if you heated all the necessary components in
one beaker; also I won't be able to respond for a bit due to RL, apologies

**Comment by XDTM** [comment]
"burningcarbon" is a reaction, not a chem

**Comment by Ordonis** [comment]
oh shit I thought that was carbon dioxide, dammit, this is why I should not
code in a hurry

**Comment by Ordonis** [comment]
For the record it still worked when I tried it on my testserbian

**Review by DaxDupont — CHANGES_REQUESTED** [review]
tgstation.dme should not be included in this commit

**Comment by Ordonis** [comment]
Just close this dumpster fire of a PR, it was done in a rush out the door,
mea culpa, mea culpa, mea maxima culpa, I'll fix the recipe later

**Comment by Anonmare** [comment]
@yorii Nitrous oxide is also a chem.

Yes you can make nitrous oxide gas grenades.

**Comment by Ordonis** [comment]
Also I didn't touch the dme and have no idea why it's committed; if possible, closing this and opening a less screwed up one or having one of the powers that be remove that from the commit list would be peachy

**Pull request closed without merging**
