### PR TITLE
Shortens Hub Entry Descriptors

### PR DESCRIPTION
**Pull request by 13spacemen**
Short and sweet, the removed words are obvious and unnecessary

no changelog because it's just a very minor edit

### CODE REVIEW

**Comment by Mothblocks** [comment]
Honestly I would rather you just remove the "respawn: on, AI: enabled" text instead if you're trying to shorten length

**Comment by 13spacemen** [comment]
@Mothblocks It's not purely for shortening the hub entry (although that's a bonus, since there's a char limit)
It looks a lot cleaner saying Time: and Alert: rather than Round time: (of course its the round time) and Alert level: (of course its the alert level, saying level is superfluous


As for removing the AI allowed respawn enable stuff, I'll make a commit so it shows only if respawn is enabled and the AI disabled (or I could just axe that AI allowed thing entirely if you want I guess)

**Comment by Mothblocks** [comment]
This is a non-trivial web edit, can you confirm you have ran this in Dream Daemon and received no runtimes? (Debug > View Runtimes)

**Comment by 13spacemen** [comment]
@Mothblocks just fetched compiled ran it, no runtimes
runtimestg

**Pull request merged**
