### PR TITLE
Removes the fully-stocked free nanomed from mining capsules

### PR DESCRIPTION
**Pull request by vuonojenmustaturska**
## About The Pull Request

Removes the nanomed someone added that gives every miner 5 brute and burn patches, 2 charcoal pills and 2 brute and burn sprays for free. Not that they even needed it.
This leaves miners with survival medipens, donk pockets, cactus fruits, miner's salve, legion cores and ruins loot.

## Changelog
:cl: Naksu
del: Free nanomeds have been removed from mining capsules
/:cl:

### CODE REVIEW

**Comment by SgtxRootbeer** [comment]
>why this is good for the game:
>Nothing

It was added to replace the sleepers that were removed

**Comment by HomocidlePancakes** [comment]
>It was added to replace the sleepers that were removed

>Implying you can use sleepers solo

>Implying sleepers are equivalent to free 5 brute/burn patches and 2 brute/burn sprays

Getouttahere with your hugbox

**Comment by SgtxRootbeer** [comment]
you're right, having a buddy to operate the sleeper is a million times better than the spray, because you get infinite bicaridine/kelotane, whereas with this, you sorta just run out after a few bad encounters.

if you wanna nerf it, remove the donk pocket. we have tons of cactus fruit which does the same thing, the only issue is the donk pockets cant be eaten by lizards, and when you're already stuffed on cactus fruit, you can't eat donk pockets regardless. 

image

**Comment by QualityVan** [comment]
don't you have to buy mining capsules? that's a pretty weird version of for free

**Comment by FantasticFwoosh** [comment]
Hit the discord if you want a proper think-tank for ideas, but i think a bio-generator like machine to manufacture drugs from a set amount of fruity cactus's (another use to gathering them with provided plant bags) to heal yourself may be a alternative.

Also i :+1: this because for everyone who uses it, infinite nanomeds is strong enough if you're playing cult and just overlapping pods together for multiple endless patches.

> don't you have to buy mining capsules? that's a pretty weird version of for free

There's spare pod capsules in the extra-mining lockers in mining base planetside.

**Comment by FloranOtten** [comment]
In an ideal world, miners team up and sleepers are useful. Sadly, the sleepers really weren't used. The only time I, as a miner, used one was when we had a cult base in a pod and didn't yet have enough runed metal for a pylon. The nanomed is a buff because it only takes one man to operate it.

**Comment by vuonojenmustaturska** [comment]
@QualityVan the lockers containing the miners' roundstart equipment have a capsule each, there are also spare lockers in lavaland containing extras.

**Comment by anconfuzedrock** [comment]
Anyone who opposes this is batshit crazy, my secret to never needing chemistry as doctor is that I raid an entire small nanomed and have enough meds to heal people in the most chaotic rounds.

**Comment by HomocidlePancakes** [comment]
Oh boy I thought I could you brush you off with some meme arrows but it seems you are way to thick skulled for that.

>you're right, having a buddy to operate the sleeper is a million times better than the spray, because you get infinite bicaridine/kelotane.

Nice overexaggeration. How often do you actually see miners using sleepers? They have easy access to effective healing items thanks to their vendor which rendered sleepers obsolete. 

>Whereas with this, you sorta just run out after a few bad encounters

Nice downplaying. I am sorry, but how good are you at math? You get 5 brute/burn patches and 2 brute/burn sprays. Maybe you should calculate how much that can heal? I can't be arsed to do this to comfirm something so blatently obvious.

>if you wanna nerf it, remove the donk pocket.

Remove the weaker item in favour of a stronger one? How is that a nerf?

>we have tons of cactus fruit which does the same thing

Why not remove cacti then lol? They are the same anyway herp derp.

>the only issue is the donk pockets cant be eaten by lizards

1)Lizards can, in fact, eat donk pockets. They just can't eat more then one at a time or they will get too grossed out.
2)Why are you even mentioning such an edge case when we are discussing miners in general? Are you refering to miner lizards? If so then they've opted in for this. Or maybe you are talking about ashies? We are discussing miners here so they are irrelevant.

>may i add, that there should be 3 miners, checking eachother's GPS and whatnot.

Can agree that it's how it's supposed to be, but it won't always end up like this, so don't present it as an absolute truth.

>the sprays facilitate teamplay much better

1)See previous point
2)See point 2. Every miner will most likely have his own, thus nullifing any teamplay.

>asking your buddy to remove his mask so you can forcefeed him more cactus fruit.

Man... If only there was an easily ubtainable medipen that could would completly bypass this unecessairly complicated method. Oh wait... They do.

**Comment by necromanceranne** [comment]
I used this as an antagonist to heal up between fights in space.

It is pretty bullshit. Not gonna lie.

**Comment by bgobandit** [comment]
don't forget mushrooms, some of those heal too

**Comment by kriskog** [comment]
Just give them a limited nanomed. Pubby has a version for the patient rooms:
`/obj/machinery/vending/wallmed/pubby
	products = list(/obj/item/reagent_containers/syringe = 3,
					/obj/item/reagent_containers/pill/patch/styptic = 1,
					/obj/item/reagent_containers/pill/patch/silver_sulf = 1,
					/obj/item/reagent_containers/medspray/sterilizine = 1)`

**Comment by ExcessiveUseOfCobblestone** [comment]
They don't even need that stuff though.

They have strong heals from legion cores, cacti that heal, donk pockets that heal, survival medipens that heal, medikits at lavaland base, and all of these can be stacked. why do they need yet ANOTHER healing avenue that stacks as well?

**Comment by kriskog** [comment]
If you get fat as a miner, you die. You can currently not eat more than three donks roundstart-ish or you get fat. Explain to me how food is a good source of healing for a miner. If you wanna balance miner healing around food, you are going to have to change how food makes you fat first.

**Comment by vuonojenmustaturska** [comment]
@kriskog donk pockets can be used to make miner's salve, a nice little thing that heals burn and brute and reduces nutrition

**Comment by kriskog** [comment]
If I gotta go back to base to smelt and grind stuff for a salve so I can eat more stuff that slowly heals me, I may as well just go raid medbay supplies.

**Comment by vuonojenmustaturska** [comment]
why do you think the mining base has a kitchen with a grinder?

**Comment by ExcessiveUseOfCobblestone** [comment]
> If I gotta go back to base

here is the entire problem with mining

**Comment by adamkad1** [comment]
would be nice if you kept nanomed in luxury shelter tho, its 3k points

**Comment by Daxxed** [comment]
Anyone who disagrees with this PR needs to git gud.
The nanomeds were retarded.
Take it from someone who spend 200+ hours mining without them.

**Pull request merged**
