### PR TITLE
Adds a shift to z level stacking

### PR DESCRIPTION
**Pull request by nicbn**
## About The Pull Request

This adds a y axis shift to the z level shown using open space.

https://user-images.githubusercontent.com/20824501/107124182-08a47e80-6881-11eb-8343-90e1425c8678.mp4

## Why It's Good For The Game

This will be necessary when the new walls are done. I'm pushing this now so that the code can be reviewed, as there may be a better way to do what I want here.

Currently, the method makes use of an extra atom for each open space.

### CODE REVIEW

**Comment by Qustinnus** [comment]
`Currently, the method makes use of an extra atom for each open space.`

that's a bit much

**Comment by nicbn** [comment]
This is necessary as it is not possible to shift `vis_contents` but if there is a better method please let me know.

**Comment by Qustinnus** [comment]
I'd prefer you'd try to ask for support for something like this on the byond forums (Because shifting vis contents is possible right now, just not manually).

Also, have you tested what this does to glass floors, both on multiz and without multiz? I'm pretty sure it wont work.

**Comment by nicbn** [comment]
I'll try doing it the good way

**Pull request closed without merging**
