### PR TITLE
Fix heat-exchange manifold icons facing the wrong way

### LINKED ISSUE #32953: Heat Exchange Junction Pipes not functioning correctly... Again
Issue reported from Round ID: 79043 (Sybil)

image

They do not connect nor circulate air.
I've also tried connecting it with a 4-Way Manifold and it didn't work as well.

### PR DESCRIPTION
**Pull request by SpaceManiac**
:cl:
fix: Heat exchange manifold pipes facing east/west now work again.
/:cl:

Fixes #32953. Also tweaks the `manifold` and `manifold4w` sprites which appear only in DreamMaker to appear intact.

### CODE REVIEW

**Comment by WJohn** [comment]
fuckin' nice. how do people get this wrong?

**Comment by ShizCalev** [comment]
manifold4w's offset seems to be incorrectly offset down by 1 compared to the rest.

**Comment by ShizCalev** [comment]
manifold_center, manifold_center2, & manifold_center3's sprites doesn't extend to the edges as the rest do.

**Review by ShizCalev — CHANGES_REQUESTED** [review]
Still have incorrect stuff.

**Comment by SpaceManiac** [comment]
Addressed manifold4w being offset and manifold N/E/W not reaching the edge.

**Review by ShizCalev — APPROVED** [review]

**Pull request merged**
