### PR TITLE
gives mulebot wires some messages when cut

### LINKED ISSUE #87640: No feedback from pulsing MULEbot wires
### Client Version:

_No response_

### Issue Summary:

Trying to hack a MULEbot and pulsing wires with a multitool gives no chat messages, making it infeasible to actually hack one

### Round ID:

[214211](https://scrubby.melonmesa.com/round/214211)

### Test Merge Information:

[#83227: '[TM ONLY] Hijacked Revision Date for v3 TGS Api' by ZephyrTFA at commit bfecdb9b39](https://www.github.com/tgstation/tgstation/pull/83227)
[#84826: 'Adds new station map Nebulastation' by KikoWen0 at commit aac758d4e5](https://www.github.com/tgstation/tgstation/pull/84826)
[#87584: '[TM ONLY] The roundstart report will only ever show either Pulsar Star or White Dwarf' by TheVekter at commit 59299a5029](https://www.github.com/tgstation/tgstation/pull/87584)

### Reproduction Steps:

1. Get a MULEbot, unlock it and open its panel
2. Take a multitool and start pulsing wires, which normally gives chat messages
3. No chat messages

### PR DESCRIPTION
**Pull request by grungussuss**
## About The Pull Request
closes https://github.com/tgstation/tgstation/issues/87640
## Why It's Good For The Game
feedback is cool
## Changelog
:cl: grungussuss
qol: added feedback for cutting mulebot wires
/:cl:

### CODE REVIEW

**Comment by mc-oofert** [comment]
didn't these already have messages that got lost

**Comment by Sadboysuss** [comment]
> didn't these already have messages that got lost

idk

**Comment by mc-oofert** [comment]
yeah im pretty sure youre supposed to have a multitool to see what to cut

**Comment by DrAmazing343** [comment]
MULEbots are used so little I hardly mind making them more accessible to hack. Anything to get them usable for the general public.

**Pull request merged**
