### PR TITLE
Ethereals(and other NO_HUNGER carbons with blood) Can now regenerate blood.

### LINKED ISSUE #62492: ethereals do not regenerate blood
## Reproduction:

Loose blood as an ethereal, wait for regen, it never happens.

### PR DESCRIPTION
**Pull request by KittyNoodle**
## About The Pull Request
Fixes #62492 by giving a method for no hunger mobs to get blood

## Why It's Good For The Game
Bugs are bad, bugs that make bloodloss more painful are more bad

## Changelog
:cl:
fix: Ethereals and other hungerless species will now regenerate blood.
/:cl:

### CODE REVIEW

**Comment by LemonInTheDark** [comment]
I don't consider this a bug. it's been a facet of them for as long as they've existed.
I consider this a balance change more then a fix, and not one I'm really in favor of. Very tempted to close this without further reasoning

**Comment by VladinXXV** [comment]
I'd say give them the worst possible blood regen rather than best possible, if at all.

**Comment by Thaums** [comment]
I would be in favor of this since as it stands you're just encouraged to commit seppuku and get ahealed, which is strange.
Another adjustment you could give them is to make the regen based off how much power they got

**Comment by KittyNoodle** [comment]
the problem is that any carbon with NO_HUNGER cannot regen blood, not just ethereals.

**Comment by tralezab** [comment]
this isn't a bug, strictly part of ethereal design. I remember that part clearly

**Comment by KittyNoodle** [comment]
listen man the issue i am fixing is labeled a bug

**Comment by LemonInTheDark** [comment]
It's not a bug, at least not in how it applies to ethereals.

**Pull request closed without merging**
