### PR TITLE
Fixes #12611: Grabbing someone and washing them in the sink will wash the grab.

### LINKED ISSUE #12611: Grabbing someone and washing them in the sink will wash the grab.
What it says on the tin.

### PR DESCRIPTION
**Pull request by Dorsisdwarf**
Fixes #12611

Sinks now check for whether an object is abstract

### CODE REVIEW

**Comment by Dorsisdwarf** [comment]
Pay no attention to the ball-up retarded merge history. github was kind enough to fucking *import* the merge history from my old PC to the new

**Comment by Dorsisdwarf** [comment]
beware merge history

**Comment by KorPhaeron** [comment]
I think something went a bit wrong

**Comment by Dorsisdwarf** [comment]
oh you think?

**Comment by KorPhaeron** [comment]
I'm more concerned with the files changed than the merge history

**Comment by Dorsisdwarf** [comment]
That IS the merge history right there causing that anusreap of a fuckfest oh my god github why

**Comment by Dorsisdwarf** [comment]
Fix removed because it definitely wouldnt fix anything if you merged it

**Pull request closed without merging**
