### PR TITLE
Fix two sources of color_cutoffs runtimes, then give it a better error

### PR DESCRIPTION
**Pull request by Mothblocks**
50% of rounds.

`color_cutoffs` must always be a 3-item list. I couldn't find any more cases where this assumption could be wrong.

```
[2023-05-05 04:04:21.144] runtime error: list index out of bounds
 - proc name: blend cutoff colors (/proc/blend_cutoff_colors)
 -   source file: colors.dm,91
 -   usr: Varuna Maddox (/mob/living/carbon/human)
 -   src: null
 -   usr.loc: the plating (122,145,2) (/turf/open/floor/plating)
 -   call stack:
 - blend cutoff colors(/list (/list), /list (/list))
 - Varuna Maddox (/mob/living/carbon/human): update sight()
 - the pressure-resistant enginee... (/obj/item/clothing/glasses/meson/engine): toggle mode(Varuna Maddox (/mob/living/carbon/human), 1)
 - the pressure-resistant enginee... (/obj/item/clothing/glasses/meson/engine): attack self(Varuna Maddox (/mob/living/carbon/human))
 - the pressure-resistant enginee... (/obj/item/clothing/glasses/meson/engine): ui action click(Varuna Maddox (/mob/living/carbon/human), Toggle Mode (/datum/action/item_action/toggle_mode))
 - Toggle Mode (/datum/action/item_action/toggle_mode): Trigger(null)
 - Toggle Mode (/atom/movable/screen/movable/action_button): Click(null, "mapwindow.map", "icon-x=10;icon-y=15;left=1;but...")
 - Toggle Mode (/atom/movable/screen/movable/action_button):  Click(null, "mapwindow.map", "icon-x=10;icon-y=15;left=1;but...")
 - /datum/callback/verb_callback (/datum/callback/verb_callback): Invoke()
 - world: push usr(Varuna Maddox (/mob/living/carbon/human), /datum/callback/verb_callback (/datum/callback/verb_callback))
 - /datum/callback/verb_callback (/datum/callback/verb_callback): InvokeAsync()
 - Input (/datum/controller/subsystem/verb_manager/input): run verb queue()
 - Input (/datum/controller/subsystem/verb_manager/input): fire(0)
 - Input (/datum/controller/subsystem/verb_manager/input): fire(0)
 - Input (/datum/controller/subsystem/verb_manager/input): fire(0)
 - Input (/datum/controller/subsystem/verb_manager/input): ignite(0)
 - Master (/datum/controller/master): RunQueue()
 - Master (/datum/controller/master): Loop(2)
 - Master (/datum/controller/master): StartProcessing(0)
```

### CODE REVIEW

**Review by LemonInTheDark — APPROVED** [review]

**Comment by SyncIt21** [comment]
I'm confused i thought i fixed this in #75145?

**Comment by Mothblocks** [comment]
It still comes up in 50% of rounds this week

**Comment by Mothblocks** [comment]
...Also that's not a good fix, we don't want to allow empty lists

**Comment by SyncIt21** [comment]
I see.

**Comment by Mothblocks** [comment]
...That being said I do wonder why that didn't catch this. Eyes do still have nulls but they are from NV eyes and cannot possibly be on 50% of rounds.

Let me test merge this for a bit and see if the new error comes up.

**Comment by Mothblocks** [comment]
It hasn't

**Comment by SyncIt21** [comment]
> Uh, no as in there are no runtimes at all. This PR works.

:/  I need a drink

**Pull request merged**
