### PR TITLE
Tramstation Layering Fix (Minor)

### PR DESCRIPTION
**Pull request by san7890**
## About The Pull Request

On the tin. Fixes the order that a staircase shows up in to fix a minor issue.

## Why It's Good For The Game

image

This doesn't look good.

## Changelog

:cl:
fix: Nanotrasen finally realized that when spraying decals on TramStation to go UNDER any staircase accessories.
/:cl:

### CODE REVIEW

**Comment by DrDiasyl** [comment]
Nice, +3 GBP for such a minor fix. My man. 😎

**Comment by san7890** [comment]
> Nice, +3 GBP for such a minor fix. My man. 😎

If I did it for the GBP, it'd be pointless because I'd probably never spend it.

**Comment by DrDiasyl** [comment]
> > Nice, +3 GBP for such a minor fix. My man. 😎
> 
> If I did it for the GBP, it'd be pointless because I'd probably never spend it.

True 😔

**Comment by MrMelbert** [comment]
image

Bonus points

**Comment by san7890** [comment]
> image
> 
> Bonus points

i did it for free

**Comment by Maurukas** [comment]
There's always gbp in mapping.

**Pull request merged**
