### PR TITLE
No Man's Lava

### PR DESCRIPTION
**Pull request by Cheridan**
Revolutionizes the gaming universe with the literally infinite possibilities of procedural generation.

### CODE REVIEW

**Comment by PKPenguin321** [comment]
:clap: here's 60 dollars

**Comment by Jordie0608** [comment]
>literally infinite possibilities
>is actually just `2^24(255^2)x2^24(mobs)` possibilities

You disappoint me

**Comment by PKPenguin321** [comment]
closed why

**Comment by Jordie0608** [comment]
Cheridan lied to us

**Pull request closed without merging**
