### PR TITLE
New forensic content: Telecrystal Signal Tracker

### PR DESCRIPTION
**Pull request by GuillaumePrata**
## About The Pull Request
This PR adds a new branch of forensic work, focused on pinpointing the location that Syndicate agents buy items and complete objectives from their uplink.

The goal is simple, push traitors away from just using their uplink at the safety of their department.

The signal tracker program works like any other radar program (lifeline as an example)
A prototype laptop spawns inside the detective locker with the app preinstalled.
You cannot download the app so take good care of that laptop...

More details here: https://hackmd.io/@GuillaumePrata/telecrystal_signal_tracker
## Why It's Good For The Game

Forensic work is the best side of Detective's interaction with other members of security, but it is quite barebones now with just the forensic scanner.
I have a few ideas of new content to add, and this was my favorite so it was the first to be worked on.

This makes security interact with the uplink more and preemptively.
Triangulating the locations that a traitor likes to go to buy items, talking about possible suspects, setting up ambushes, etc.
Instead of the uplink being mostly a loot pool for security if they manage to secure one.

Traitors can play a cat and mouse game with security by being smart with their purchase locations.
Watching security blame and beat someone else for your crimes is the best part of stealth traitors after all...
## Changelog
:cl: Guillaume Prata
add: New Telecrystal Signal Tracker program. Purchasing items and having TC teleported to your uplink after completing an objective will leave a signal behind around your area after 2-3 minutes. This signal can be tracked by security so avoid purchases on an area that might raise you as a suspect. Inside your department as an example
add: A prototype laptop with this app pre installed spawns inside the detective locker. As the app can't be downloaded anywhere else, don't lose it!
/:cl:

### CODE REVIEW

**Comment by ATH1909** [comment]
do new traitor players get told that they have to buy all of their traitor items in one quick burst or else they'll have the FBI break down their door (if they purchased something and kept scrolling through the buy menu)


"Detectives can decide to stay glued to the tracker screen all game, the tool should be just one option in their arsenal, and not the most influential.
There are some drawbacks to using the laptop, it takes one hand and slow you down. Still if it becomes an issue, a harsh power drain could force detectives to put it down while it charges and to save power."

Then when IS it supposed to be used? What's the indicator supposed to be that you should turn the scanner on? Is turning the scanner on at roundstart going to count as a violation of roundstart validhunting/donking rules (the same way fortifying the armory or camping the bathrooms at roundstart would), since nobody's committed any crimes yet?

**Comment by ATH1909** [comment]
also, what's the point of making this an app if it's not supposed to be able to be transferred or downloaded anywhere? shouldn't it just be its own separate gadget?

**Comment by GuillaumePrata** [comment]
> also, what's the point of making this an app if it's not supposed to be able to be transferred or downloaded anywhere? shouldn't it just be its own separate gadget?

So it can reuse the radar UI which is familiar for players and interact with other systems like the NTnet.

It's simply easier that way (as long as there isn't any issue that I didn't think about)

**Comment by GuillaumePrata** [comment]
> do new traitor players get told that they have to buy all of their traitor items in one quick burst or else they'll have the FBI break down their door (if they purchased something and kept scrolling through the buy menu)

There are a lot of hidden mechanics that are not clearly informed to new traitors, fingerprints as an example.
I don't know what would be a good way to give the feedback to the traitors outside of some text in the uplink itself so it can definitely be improved on that end.

> Then when IS it supposed to be used? What's the indicator supposed to be that you should turn the scanner on? Is turning the scanner on at roundstart going to count as a violation of roundstart validhunting/donking rules (the same way fortifying the armory or camping the bathrooms at roundstart would), since nobody's committed any crimes yet?

These are for the admins to decide. I don't control policy and I can change values around if needed.
I wouldn't compare an item given by NT made for tracking traitors to camping bathrooms and fortifying rooms pre-emptively tho.

One is an IC device, the others are players abusing their metaknowledge for their advantage.

**Comment by ATH1909** [comment]
> > do new traitor players get told that they have to buy all of their traitor items in one quick burst or else they'll have the FBI break down their door (if they purchased something and kept scrolling through the buy menu)
> 
> There are a lot of hidden mechanics that are not clearly informed to new traitors, fingerprints as an example. I don't know what would be a good way to give the feedback to the traitors outside of some text in the uplink itself, it can definitely be improved on that end.

Fingerprints are at least, like, intuitive. "Sec gets told your location a few minutes after you buy something" isn't.


> I wouldn't compare an item given by NT and made for tracking traitors to camping bathrooms/fortifying rooms pre-emptively tho. One is an IC device, the others are players abusing their metaknowledge for their advantage.

But, like, the reason _why_ bathroom camping is forbidden is specifically so that traitors don't get donked by more experienced players before they can finish getting their things together. I don't see why that reasoning wouldn't also apply to this feature, so why should we add it?

**Comment by YakumoChen** [comment]
Feels very meta. Where is a safe TC spending spot for traitors? You can't go in deep maint or in secluded rooms because now your fingerprints are everywhere. You can't buy in public because you'll be spotted. Can't in your department because it'll narrow you down.

**Comment by necromanceranne** [comment]
I mean, there is so much that is wrong about this idea and the concept that it's pushing, but I think the biggest and worst offender is that it is deeply lazy detective work. At least for heretics, people need to find the activated rift, and there is a crime scene that now needs to be investigated, and people to be spoken with. Usually in a location that has no obvious tells, so you have to actually figure out who or how the heretic got in. (probably magic, but maybe they broke in, so that might leave fingerprints/fibres).

What spurs the detective to start following your trail shouldn't be during the prep stage, before you've actually accomplished anything. It should be once you've actually accomplished something and security is left to figure out how it happened at the crime scene itself. This takes away most of the guess work of what is happening in a round by giving you a straight pointer towards 'a valid was here', making it plainly obvious what threats you can encounter just from sitting in your desk, looking at your laptop, and where you might be able to find them.

**Comment by improvedname** [comment]
detective does not need it they are finding antags just as fine though you can make autospy surgery a thing and see what item hurted the body so you can seek information with what kind if antag/threat ur dealing with

**Comment by Wallemations** [comment]
The concept interests me but a 10x10 square of possibilities still seems too small and easy to pinpoint for me personally.

Something I was thinking to help convey how this works to players: once you buy an item on your uplink, start a countdown visually of how long the signal is "being jammed" by the syndicate, either a depleting progress bar or something. Mousing over it can explain that the syndicate is delaying security from pinpointing your telecrystal traces for that long or something.

**Comment by Mothblocks** [comment]
please stop nerfing traitors

**Comment by GuillaumePrata** [comment]
> But, like, the reason why bathroom camping is forbidden is specifically so that traitors don't get donked by more experienced players before they can finish getting their things together. That reasoning also applies to this feature, so why should we add it?

It is not about experienced players dunking on new traitors, else things like the shove+grab+cuff combo would be the real issue.
It's 100% about metaknowledge. There is no IC reason for anyone to go inside the bathroom/dorms and players know it is the spot antags go to be alone, if a player sits inside and assaults the first person that walks in after them, they will likely find an antag.

**Comment by GuillaumePrata** [comment]
> The concept interests me but a 10x10 square of possibilities still seems too small and easy to pinpoint for me personally.

Almost every number is guess work as I can't test it in game and see how effective the tool is, if it needs nerfs or buffs.

Range, delay, if the signals have the name of the area or a string of numbers, if only higher priced items create signals.

The only way to know if these are good is after some live testing because we simply don't have any tool to compare this to, unlike creating new weapons or armors where we have plenty of items to compare to, almost everything is guess work on how players will behave.

**Comment by GuillaumePrata** [comment]
>  This takes away most of the guess work of what is happening in a round by giving you a straight pointer towards 'a valid was here', making it plainly obvious what threats you can encounter just from sitting in your desk, looking at your laptop, and where you might be able to find them. The detective knowing you're valid from you pushing a UI button is basically the least user friendly experience, or the least engrossing security experience, I could have ever asked for.

We have so many 'valid was here' in the game already that I simply don't understand the point, it's the breadcrumbs security can use to find an antag eventually without someone seeing the antag doing something and screaming on radio.
From doormags, posters, your own example of rifts.

I simply can't come up with the idea of a forensics item that isn't "a valid was here" personally.

The detective won't know you are a valid from a simple UI button, it will know you have been to a location some time ago and opted in into buying something there.
Without going there personally while holding an item that slows them down and distracts them, they can't pinpoint the exactly source of the signal. A signal called "Science hallway" is mostly useless without you personally going there and figuring out the source's tile and the 5 tile range around it where the purchase was done.

It could have been from the hallway, maints, robotics, xenobio, the RD office, sometimes from another department like medbay.

**Comment by GuillaumePrata** [comment]
> please stop nerfing traitors

I agree with this, but any new item, tool or content we give security will be an traitor/antag nerf.
Unless we block new content which would be silly, the way to keep traitors/antags from being nerfed is by directly buffing them (which is just asking for powercreep issues down the line) or to let them have a direct way to interact/counter the new features.

This was what I had planned for this new tool, traitors can send security on a wild goose chase wasting their time with something as simple as hiding inside a public locker in a hallway before buying something, creating a signal in a public area or around departments they don't even have access to.

It is a nerf for traitors that don't interact with the new system, it's a buff for traitors that play smart and waste the detective/security's time or just set up ambushes to kill them in an isolated room.

**Comment by calliophis-maculiceps** [comment]
> also, what's the point of making this an app if it's not supposed to be able to be transferred or downloaded anywhere? shouldn't it just be its own separate gadget?

yeah seriously can we please stop using laptops and instead have more fun gadgets, this is sci fi not the apple store

**Comment by calliophis-maculiceps** [comment]
actually just make this be like a geiger counter instead of just a thing that literally tells you exactly where something was done, and then it will be clunky enough that it's balanced!

**Comment by GuillaumePrata** [comment]
> actually just make this be like a geiger counter instead of just a thing that literally tells you exactly where something was done, and then it will be clunky enough that it's balanced!

Balancing by making something clunky is just backwards, it works but we are making the players have a bad experience to keep something in check instead of just figuring out a better way to keep it in check.
Old Genetics console was like this and when it got a new TGUI that wasn't horrible to the end user, the issues popped up of people bruteforcing the strings in seconds.

**Comment by Shadowflame909** [comment]
I worry that if this is too strong we may be in for extended lite. Progression tator tots are already slowed down until 30 minutes into the round.

**Comment by KittyNoodle** [comment]
I really really hate the general idea of this.

1. It’s noob bait.  
This is completely untelegraphed to the uplink user and would fuck over people who don’t know about it, while doing nothing to those who do as they can simply just do uplink purchases in the hallway.

2. Invisible/Undetectable (to the antag) evidence is bad actually.  
One of my biggest gripes with the current forensics system is the fact that it’s very very hard for an antag to properly tell if they have cleaned an object of prints/fibires. The only way for antagonist to do this is to get a forensic scanner(need to sneak into sec) and scan everything in the crime scene. All this does is add another bullshit thing that antags need to cover up, in the form of a radar ping which can only be stopped by sabotaging comms(which gets shuttle called immediately because nobody bothers to fix it) or using the emag unlocked ddos program, making emag mandatory for any level of stealth

3. Forensics is already brainless and requires very little deduction. It doesn’t need more brainless “x job did y because y happened near x’s workplace.”
Picture this: captain’s office is bugged, detective scans bug, has black glove fibires and roboticist jumpsuit fibires, both roboticist are searched, one is the traitor, no deduction needed, just x=y=x. This is fun for nobody, traitor gets round ended over some bullshit they didn’t even know about, and detective has piss easy case.
this has the same issue as your idea.
scenario using your idea: There is one atmos tedh, that atmos tech is a traitor, the detective is somewhat near engineering for unrelated issues, the atmos tech gets some basic gear from their uplink then goes to do an objective, the detective sees the uplink use in atmos(a big enough space to ignore the 5 tile offset) and searches the one atmos tech, syndicate gear is found, and the atmos tech has not done anything antagonistic yet or ever will considering they are immediately executed.
At least our current system, no matter how bullshit it is sometimes, requires the antag to do something first before having to think of covering their tracks.

**Comment by moocowswag** [comment]
Didnt we remove xray/nerf thermal vision to prevent traitors from getting caught without knowing they were caught? Fingerprints is one thing but this is something you cant necessarily hide, only guess if someone is tracking you or not when you buy stuff.

My main issue is 2 things.

1 This is going to become a policy nightmare when sec players start random searching entire departments just cause someone bought something in x department. (Not even heretic influences toe this line because they are scattered randomly throughout the station so they are bound to appear anywhere as heretics are a very roamy antagonist)

2 This does not harm experienced traitors, infact, good traitors will probably buy cheap shit just to bait sec / valid hunting loot pinata captains to their location. (Actually im looking forward to abusing this) But newbie traitors are gonna get steamrolled.

**Comment by Inari-Whitebear** [comment]
> 2 This does not harm experienced traitors, infact, good traitors will probably buy cheap shit just to bait sec / valid hunting loot pinata captains to their location. (Actually im looking forward to abusing this) But newbie traitors are gonna get steamrolled and will be left asking deadchat why

Sounds like an upside actually, at least the part of baiting sec, less the newbie getting steamrolled

**Comment by fishingsman** [comment]
I dont approve this PR

**Comment by Pickle-Coding** [comment]
I think it would be better if it was generalised to any form of bluespace disturbance, such as teleportation. I feel like it being specified to telecrystals might encourage antag hunting a little too much, and I'm not sure about security knowing uplinks roundstart.

**Comment by private-tristan** [comment]
HOSes on their way to grab this roundstart and imnediately random search everyone when this thing picks up a single purchase so that they can kill 3/4ths of tots who just bought an emag 5 minutes into the round.

**Comment by SkeletalElite** [comment]
While not directly related the current design docs about stun combat state and batons state

"It is already a common issue that antagonists will play “loud”, where they are not secret about the fact they are an antagonist–stealth should not be further discouraged."

This just discourages being stealthy as a traitor

**Comment by flowercuco** [comment]
> > actually just make this be like a geiger counter instead of just a thing that literally tells you exactly where something was done, and then it will be clunky enough that it's balanced!
> 
> Balancing by making something clunky is just backwards, it works but we are making the players have a bad experience to keep something in check instead of just figuring out a better way to keep it in check. Old Genetics console was like this and when it got a new TGUI that wasn't horrible to the end user, the issues popped up of people bruteforcing the strings in seconds.

i think that friction can be fun and interesting, i dont think that turning it into a geiger counter or some other like, more inaccurate or difficult to parse thing is terrible with a tool as strong as this would be. this games setting is clunky and janky, and i do think it makes sense that it would be extremely difficult at this point.

anyway other idea regardless of what implimentation you go for is that you should be able to fuck with the signal by sending the syndicate faxes

**Comment by GuillaumePrata** [comment]
> This just discourages being stealthy as a traitor

Heavily disagree.

You can use the signals to send security on searches on a department while you achieve your goals in another, shift blame into other crew members by spamming signals on their department, setup ambushes against security by using radio jammers and maint rooms.

This enables stealth antagonists if used correctly and has nothing to do with going loud.
People don't go loud because it's hard to hide that there is a antag around, everyone knows there are antags every shift and I don't buy this "Security will search everyone!" people keep bringing up. Security doesn't do this when an airlock is emaged, posters are placed around or a rift shows up.

People go loud because if you are trying to hide as a normal crewmember you have no control on when some clown/greytider/officer decide to jump you, which if you win or lose, ends up with everyone knowing you are a traitor because the moment someone screams on comms "X is bad" more and more people will try to fight you.
When you play stealth, you are at the mercy of other players not being a shitter to you, when you go loud you can just murder everyone that gets near you and will never be surprised by a chef deciding to randomly CQC you when you walk into their kitchen to eat.

**Comment by KittyNoodle** [comment]
When I play loud I focus my tc towards offense and defense with some utility items.
These items are effective at their job.
It’s fun and makes you feel like a part of a story by being an antagonist.

when I play stealth I feel barely a part of anything because:
The available stealth tools are ass (looking at you infil modsuit with your 1 dollar mood debuff.)
Bullshit like the current forensics system removing any level of intrigue in figuring out who is doing the sabotage.
And with this what little I can do creates a bullshit radar ping at my location, to which the detective will say “ai bolt all the doors in engineering.” And get field executed while reminiscing on why ai is the worst thing for the game and servers without it are infinitely more fun.

**Comment by YakumoChen** [comment]
Me on my way to log purchases and create a public heat map of tc buying spots so I can use my metacampy IC item to dunk on the traitors

**Comment by calliophis-maculiceps** [comment]
> I think it would be better if it was generalised to any form of bluespace disturbance, such as teleportation. I feel like it being specified to telecrystals might encourage antag hunting a little too much, and I'm not sure about security knowing uplinks roundstart.

this would be very interesting actually, like a way to just know when teleportation happens, neatly tying together different things that canonically use teleportation

**Comment by moocowswag** [comment]
> how about make it track bluespace disturbances

I really like this idea.

**Comment by blackdav123** [comment]
add circuit functionality so that we can automate the validhunting instead of having to do it ourselves

**Comment by CMDR-Gungnir** [comment]
> Me on my way to log purchases and create a public heat map of tc buying spots so I can use my metacampy IC item to dunk on the traitors
> 
> There is no irony in this post because I can see this actually happening. Once players figure out the most likely spots to buy items the "range of error" becomes just a suggestion.

90% of what I'm seeing here just seems like admin issues. Especially this, this screams more Player Error than Code Thing Bad.

Anyway, as a Det Main/Enjoyer, I kinda don't like this because it's more fun to try and figure it out from actual evidence left behind. And people complaining about fingerprints/fibers are suffering from a major Skill Issue. Use disguises. Be clever. Don't just whine and cry that your antag round wasn't handed to you.

**Comment by CMDR-Gungnir** [comment]
> > > Me on my way to log purchases and create a public heat map of tc buying spots so I can use my metacampy IC item to dunk on the traitors
> > > There is no irony in this post because I can see this actually happening. Once players figure out the most likely spots to buy items the "range of error" becomes just a suggestion.
> > 
> > 
> > 90% of what I'm seeing here just seems like admin issues. Especially this, this screams more Player Error than Code Thing Bad
> 
> Taking an admong issue like people camping traitor buying spots and then making an item that explicitly encourages it isn't keeping it an admin issue

It doesn't encourage it to most people. With this I would feel absolutely zero reason to go map out all the most common places people buy things from. I'm gonna follow the radar slowly pointing me in the direction of Engineering and go "Hmm. Alright so it was done somewhere around here..." and start scanning stuff. Which will be covered in fingerprints and fibers, giving me very little to go on, because while fingerprints and fibers ARE in chronological order, I can't know if fibers were placed AFTER prints, except to possibly notice a pattern with another previously committed crime.

> > Anyway, as a Det Main/Enjoyer, I kinda don't like this because it's more fun to try and figure it out from actual evidence left behind. And people complaining about fingerprints/fibers are suffering from a major Skill Issue. Use disguises. Be clever. Don't just whine and cry that your antag round wasn't handed to you.
> 
> This is the absolute state of implying traitors go fetch a disguise so they can wear a disguise on the way to buy a disguise kit with tc

I didn't say that. I said that about the people complaining about fingerprints and fibers (IE, the current Forensics System), which there ARE people complaining about in here.

**Comment by Livrah** [comment]
I can't remember the last time I was playing a detective and captain\hos didn't take the second scanner from my office to take out all the antags before they brought anything to the round. Validhunters don't need more tools to "win the game".
Better make armory's tracking implants less awful if pinpointing somehow is a problem.

**Comment by CMDR-Gungnir** [comment]
> I can't remember the last time I was playing a detective and captain\hos didn't take the second scanner from my office to take out all the antags before they brought anything to the round. Validhunters don't need more tools to "win the game". Better make armory's tracking implants less awful if pinpointing somehow is a problem.

Sounds like the issue is with people misusing things, rather than the investigator job having ways to investigate things.

**Comment by KittyNoodle** [comment]
ive said this again, this is in no way explained to the uplink user, and just adds more unnecessary bullshit into traitor specifically as an antag, which has already gotten it fair share of unnecessary bullshit. however i do like the idea of a teleportation detector, an item that feels more like it belongs to the rd, maybe like an app on the rd's pda that locates bluespace teleports

**Comment by NamelessFairy** [comment]
Really not a fan of this, as far as I can see every reason why has already been given above. If this does have to be added it should not be a roundstart tool, imo it should be locked behind the syndicate tech node at a minimum. This resolves the issue of this device easily confirming if their are traitors on the station or not since you'd need to capture a traitor before it serves any purposes as well as allowing traitors who are usually very vulnerable early in the shift to actually buy gear to do their objectives before they have to arm up to fight off their pursuers.

**Comment by GuillaumePrata** [comment]
> If this does have to be added it should not be a roundstart tool, imo it should be locked behind the syndicate tech node at a minimum. This resolves the issue of this device easily confirming if their are traitors on the station or not since you'd need to capture a traitor before it serves any purposes

I honestly have no idea why people keep bringing this point up when almost every shift you have posters or a giant syndicate logo on the floor and everyone knows there is a traitor around 2 minutes in.

**Comment by Serxule** [comment]
not only does this not make any sense lore-wise (if NT has shit that can track telecrystals there would be no syndicate onboard), but its a shitty gameplay item thats only use is hunting antags down before they do anything

**Comment by GuillaumePrata** [comment]
> not only does this not make any sense lore-wise (if NT has shit that can track telecrystals there would be no syndicate onboard)

You are taking lore out of your ass there to make a stronger point, it tracks teleportation signals, not the telecrystals inside the uplink.

> but its a shitty gameplay item thats only use is hunting antags down before they do anything

Literally what forensics work is, get an evidence, follow it and get the perp before, or after, they have committed the crime/more crimes.

t's almost like security's job content is to go interact and work as a opposing force to antagonists.

**Comment by CMDR-Gungnir** [comment]
I do think one way you could make this more interesting is to make it so that the signal appears in a random spot on station, justified by the Syndicate scrambling it, and instead of being something that tells you where it was done from, it tells you what was bought. Doesn't have to proc every time someone makes a purchase, a lot of them probably shouldn't show up, but maybe you go and track down that signal and you find out a .357 was bought. Now you can warn your team that one of the tots, no fuckin' idea who, has a .357 and to be wary of that.

Neat way of letting the Det work as a support unit for the Sec Team.

**Comment by Serxule** [comment]
> Literally what forensics work is, get an evidence, follow it and get the perp before, or after, they have committed the crime/more crimes.
> 
> It's almost like security's job content is to go interact and work as an opposing force to antagonists.

no, thats not at all what this is, if an antag breaks into somewhere and takes, say, security gear, by using an emag, then they have done a crime, this just tells you where someone is when they havent done any crime

**Comment by GuillaumePrata** [comment]
> no, thats not at all what this is, if an antag breaks into somewhere and takes, say, security gear, by using an emag, then they have done a crime, this just tells you where someone is when they havent done any crime

You're talking like people don't get constantly permaed for doing no crime but confirmed as traitors.

Talking about crimes here is even sillier because Space Law is a suggestion on TG. Some rounds you get insta killed for holding a syndicate poster, on others sec just takes away your .357 and let you go vibe outside.

**Comment by Serxule** [comment]
> > no, thats not at all what this is, if an antag breaks into somewhere and takes, say, security gear, by using an emag, then they have done a crime, this just tells you where someone is when they havent done any crime
> 
> You're talking like people don't get constantly permaed for doing no crime but being confirmed as traitors.
> 
> Talking about crimes here is even sillier because Space Law is a suggestion on TG. Some rounds you get insta killed for holding a syndicate poster, on others sec just takes away your .357 and let you go vibe outside.

does the forensic scanner tell you the location of a traitor? does the forensic scanner tell you that a traitor bought something? no?

**Comment by GuillaumePrata** [comment]
> does the forensic scanner tell you the location of a traitor? does the forensic scanner tell you that a traitor bought something? no?

Why you are bringing another different tool to the discussion?

The scanner works in a completely different way, of course it can't track traitors, of course it doesn't tell purchases, it's not it's goal.

This conversation is so dumb.

**Comment by Serxule** [comment]
> > does the forensic scanner tell you the location of a traitor? does the forensic scanner tell you that a traitor bought something? no?
> 
> Why you are bringing another different tool to the discussion?
> 
> The scanner works in a completely different way, of course it can't track traitors, of course it doesn't tell purchases, it's not it's goal.
> 
> This conversation is so dumb.

you very clearly didnt read anything ive wrote or you completely lack braincells to make connections

**Comment by GuillaumePrata** [comment]
> you very clearly didnt read anything ive wrote or you completely lack braincells to make connections

I can say the exact same to you, as I say something and you don't answer, just go into a dumb tangent.

**Comment by Serxule** [comment]
> > you very clearly didnt read anything ive wrote or you completely lack braincells to make connections
> 
> I can say the exact same to you, as I ask something and you don't answer, just go into a dumb tangent.
> 
> If you're not going to give your points in a direct way and instead we need to go dig inside your skull to know what you are thinking or we just don't have enough brain cells to make connections, it is better to just not comment on PRs.

i literally gave points using existing ingame items to compare, and you call it "random tangents", do you hear yourself

**Comment by GuillaumePrata** [comment]
> i literally gave points using existing ingame items to compare, and you call it "random tangents", do you hear yourself

I literally asked you why you brought that up and you didn't answer.
Do you hear yourself?

**Comment by Serxule** [comment]
> > i literally gave points using existing ingame items to compare, and you call it "random tangents", do you hear yourself
> 
> I literally asked you why you brought that up and you didn't answer. Do you hear yourself?

you're honestly just baiting now

**Comment by GuillaumePrata** [comment]
> you're honestly just baiting now

You're honestly just not answering a simple question.

**Comment by GuillaumePrata** [comment]
I need to do a lot of work to polish a few issues I ran into the PR so I will close it and reopen it eventually if I can fix those.

Also Oranges said I should close this to open another PR that I want so perfect timing!

**Pull request closed without merging**
