### PR TITLE
Multisword fixes

### PR DESCRIPTION
**Pull request by ghost**
Removes colons.

Fixes the augmented guy not actually getting his augments and the soviet
one not spawning with a sword.

Adds officer and gladiator costumes as choices for the sword to pick from.

### CODE REVIEW

**Comment by Aranclanos** [comment]
what's the bug that you're trying to tackle?

**Comment by KorPhaeron** [comment]
The cyborg guy spawned naked because I forgot to include update_augments()

The soviet I just forgot to include a line giving him a sword originally. Nothing fancy just left out lines the first time around and figured removing colons would be a good thing while I was at it.

**Comment by KorPhaeron** [comment]
Line 419 and 452 specifically was what I was missing

**Comment by Aranclanos** [comment]
oh ok, I saw the pirate sword line changing possition so I thought there was something there.

**Comment by KorPhaeron** [comment]
Oh no I just realized it wasn't on the last line like everyone elses sword and wanted to make it prettier/consistent

**Comment by RemieRichards** [comment]
That's sort of like the unwritten rule of "new vars go to the bottom of the definition"
it's just prettier + logically organised

**Comment by Aranclanos** [comment]
I'll unwrite rule your face

**Comment by RemieRichards** [comment]
no u

**Pull request merged**
