### PR TITLE
Tramstation Wirenet rework + Maint tile changes

### LINKED ISSUE #61923: Tramstation's Wires (and some pipes)
## Testmerges:
The following pull requests are currently test merged:
#61400: 'Adds a second Detective slot.' by Iamgoofball at commit 85f60a731c
#61711: 'Buffs eye contact, adds "Shifty Eyes" quirk' by Ryll-Ryll at commit b2a33de31c
#61919: 'Undoes #58382' by LemonInTheDark at commit d84750d4f6

## Reproduction:
https://puu.sh/IgaeG/69095531b0.png
https://puu.sh/Igag7/316489214c.png
https://puu.sh/Igakn/813722e8e3.png
https://puu.sh/Igapf/ffa13de150.png
https://puu.sh/IgapC/2fc969ff67.png
https://puu.sh/IgapL/3fb27a8186.png
https://puu.sh/IgaCM/628e3e182d.png

Ones I REALLY want to point out are the missing wire from the maint power room on the far left which, does not actually seem necessary (both ends of the cut wire received power) still doesn't make much sense. Then the other main ones are outside of the courtroom, where the wires and pipes seem to completely miss a tile, and most importantly hydroponics, which is similarly missing a single tile of pipes and wires.

Tcomms runs off the engine, so it takes until the smeses fill up for it to start receiving power.

Emitters run off the engine, so every single round you need to throw shit at the engine or bust out the pacman for them to start at all. On other maps they are powered by the partially full smeses.

Additionally, the grid is very frail. Extremely frequently, one mice will take down the left or right third of the station by itself.

### PR DESCRIPTION
**Pull request by MMMiracles**
## About The Pull Request

Completely rips out the old wirenet and replaces it with a repathed one with more redundancies to reduce random acts of mice violence on the powergrid. Also renovates maintenance with the cool catwalk tiles since nowhere else uses them. Also a few misc fixes involving missing pipes and blast doors/buttons missing their counterparts.

## Why It's Good For The Game

Hopefully addresses the powernet complaints the map had.

## Changelog

:cl: MMMiracles
add: Tramstation's maintenance now has new catwalk tiles covering the various piping/wiring throughout.
fix: Tramstation's powernet should be slightly more resistant to bouts of power outages caused by rogue syndicate mice operatives.
fix: Patched up a few missed spots involving pipe/wiring for departments like Botany/Courtroom.
/:cl:

Fixes #61923

image
image

see it looks pretty cool

### CODE REVIEW

**Comment by tralezab** [comment]
image

note to self: object shadowing is doing these a disservice

**Comment by Zytolg** [comment]
Alternative to #61967

**Comment by EricZilla** [comment]
Thats the sexiest maintenance hallway I've ever seen

**Comment by newfren** [comment]
does this close #61923

**Pull request merged**
