### PR TITLE
Changes Fire Alarm Sound & Makes It Audible

### PR DESCRIPTION
**Pull request by JohnTheDonut**
## **Changes Fire Alarm Sound & Makes It Audible**
Did you know that the fire alarm makes a sound? Well i did not and upon further investigation it seems that the sound is so quiet that it is nearly impossible to hear over other sounds. This Pull Request changes the sound to a more "Alerting" sound and makes it actually audible to players.

UPDATE -  I have updated the fire alarm sound with the Goonstation sound because it is a good and alerting sound, and mostly because its an overall good sound it can be heard [here ](https://soundcloud.com/user-214797480/goonfirealarm/s-kY8y4)

## **Changelog**
:cl: Tofa01
Soundadd: Changes fire alarm to make new sound FireAlarm.ogg
/:cl:

### CODE REVIEW

**Comment by Jordie0608** [comment]
182KB is pretty large for a 7 second file, especially when it's replacing a 11 second 81KB one. It sounds quite shrill and, i'm not sure how to say, blocky? Commodore 64-ish?

**Comment by Tofa01** [comment]
Hold on i've got another one i was considering let me just upload it.

**Comment by Tofa01** [comment]
@Jordie0608 [How about this?](https://soundcloud.com/user-214797480/alarm/s-gghK7) Its only 32kb

**Comment by Tofa01** [comment]
Just lowered the file size to 60KB, personally i like the first one better but i also uploaded the second one that i made, Let me know what you guys think if the second one is liked more ill commit it instead.

**Comment by Militaires** [comment]
@tofa01 that sounds like an ambulance 

just use the goon ones

**Comment by Ultimate-Chimera** [comment]
Sounds gross imo.

**Comment by Tofa01** [comment]
Uploading the goon alarm soon it sounds pretty good in my opinion.

**Comment by Tofa01** [comment]
Here is the [goonstation alarm](https://soundcloud.com/user-214797480/goonfirealarm/s-kY8y4), its also pretty cool.

**Comment by optimumtact** [comment]
if it comes from goon, it must go in the goon folder

**Comment by Tofa01** [comment]
Of course going to commit it soon. Its a pretty good sound.

**Comment by Tofa01** [comment]
## Goonstation Fire Alarm Sound

It appears that i cannot edit my Original PR Post so i will put the message here instead, i have updated the sound with the Goon station sound because it is a good and alerting, its overall a good sound it can be heard here:

https://soundcloud.com/user-214797480/goonfirealarm/s-kY8y4

**Pull request merged**
