### PR TITLE
Updates the E-Sword sprites,makes them more like [REDACTED]

### PR DESCRIPTION
**Pull request by Lexorion**
Because glowing E-Swords are nicer if you ask me! Larger picture due to the lack of a gif but it's animated.
test
Not in the picture : old esword inhands

### CODE REVIEW

**Comment by PKPenguin321** [comment]
not sure how i feel about this

**Comment by Durkel** [comment]
They look kinda goofy, not too keen on the glow.

**Comment by TechnoAlchemisto** [comment]
theyre not LIGHTSABERS THEYRE ENERGY SWORD YOU FOODL

**Comment by Incoming5643** [comment]
Woah woah woah, are you looking to get us sued!

**Comment by Shadowlight213** [comment]
Needs rebalance tag, since eswords glowing in the dark is a nerf :^)

**Comment by Firecage** [comment]
.....I don't see the difference?

**Comment by Bawhoppen** [comment]
we do not have lightsabers in our game nor we were inspired by any lucasarts production

**Comment by Thunder12345** [comment]
These are so much better. Just put a bit of glow around the inhands like the item sprites and they'll be perfect

**Comment by Metacide** [comment]
These really are a lot better, neat. :+1:

Do they already emit light these days?

And what about the toy ones?

**Comment by Lexorion** [comment]
@TechnoAlchemisto Fixed the name of the weapon in the OP.
@Incoming5643 Hippie has actual light sabers while I kept the handle the way it is (mostly) so don't worry. I did not touch any names.
@Firecage Check the OP,I did not include the old inhands
@Metacide  Preeetty sure they emit light once you turn them on (welders aswell) Toy ones should look like the new esword,unless I'm wrong (I'll check it in a bit).

**Pull request merged**
