### PR TITLE
Brings Back Gaia

### PR DESCRIPTION
**Pull request by ghost**
It is impossible to do anything fun with Botany now, with both the DNA Manipulator being nerfed and now Gaia being removed. This also removed the route to Biotech 7 without having to do Xenobio for ages.
Nobody plays Botany to make boring food for the Chef all round or to tend to plants every 5 seconds

Shame on you Goof, I thought you were a man of the people

:cl:
add: Ambrosia Gaia is back
/:cl:

### CODE REVIEW

**Comment by GunHog** [comment]
You are probably too early for this, but I support the change nonetheless. A proper nerf, targeting the self-sustaining trays is what should have been done. Gaia is useful for other things!

**Comment by FantasticFwoosh** [comment]
At least give it a week of being removed from active play to leverage reaction, speed reverting this won't change the terrible way botanists were abusing this plant in the first place and the drama surrounding it leading up to its removal.

**Comment by unrealair** [comment]
Gaia was never the problem. If you're going to bitch about it give specific examples of ways it is "abused," including the specific plants that are "abusing" Gaia.

**Comment by Cruix** [comment]
You are still capable of doing everything you used to be able to, now it just takes more than AFKing and coming back every 5 minutes to harvest anything that grew.

**Comment by FantasticFwoosh** [comment]
If you want to leave your plants for a long amount of time, set weed growth to 0, upgrade the tray full of nutrients & water with RnD parts and it'll be fine, worst that can happen would be insects or the plant dying of old age (but that was a risk factor already with gaia)

**Comment by unrealair** [comment]
Fwoosh how about you answer my first reply you retarded long winded overly verbose barely English literate can't take a hint "I'm going to change things so I can feel like I'm contributing" limp brained bastard

**Comment by FantasticFwoosh** [comment]
Ill translate into caveman for you

> Ugg! Lazy botanist no do work! Coder make plant trays & actual plants consuming to make hydro work! Gaia gets around this and simply makes waiting game! Ugg!

**Comment by unrealair** [comment]
That's what I thought, you can't even state how it was "abused" or overpowered, you just changed things out of some autistic sense of "I think botanists should have to play the easiest, slowest paced game of whack-a-mole possible in order to do their job" without a lick of consideration as to whether it's fun or not, or whether it needed changing in the first place.  

you should be ashamed of yourself, what would your mother think of what you're doing to the poor botanists, think of the poor chefs who are no longer going to get a full smartfridge because growing a wide variety of plants now takes more effort than its worth

and the poor scientists who just want to max out research

leave this place never to return

**Comment by Repukan** [comment]
Knee jerk pr.

Use your salty tears to kill the weeds in your trays

**Comment by FantasticFwoosh** [comment]
**_Fun_**

Welcome to hydroponics, grab your trowel & plant seeds and make some food for kitchen, instead for the entire round you will get entirely sidetracked collecting all the mutations, and making super dead. Yeah it is slow and easy whack a mole because youre entire job is centric to getting 

> I swear to god ill remove all mutations / or make them require putting them through plant radiation machine (removing random/induced chemical mutation) that needs to be printed from RnD not on the map to blast the seeds with gamma waves, if this "fun charade" keeps up about botany just spamming mutagen to get bad balance plants.

> Maybe porting VG's biolabrotory machinery for sequencing the genetic code as to total alternative to the experimentor room while dissolving the gene machine while we are at it.

People forget that hydroponics is literally there to serve as the agricultural source of the station, not mad laboratory.

**Comment by unrealair** [comment]
Thanks for changing the subject and addressing none of the main points you absolute retard.  You can't even defend the statements you made, you waste of carbon.

**Comment by Jalleo** [comment]
@unrealair botany is a rubbish job that was originally made for one purpose and then had things tacked on all the time. This is how it ends up as.

**Comment by unrealair** [comment]
WAS a rubbish job.

**Comment by Jalleo** [comment]
This is where opinions get in the way. I am not going to end up making this PR a flamewar. If you want to continue the discussion go to the forums.

**Comment by unrealair** [comment]
If you don't want to be a mud wrestler don't post in the mud pit you wuss

**Comment by lzimann** [comment]
@KorPhaeron

**Comment by KorPhaeron** [comment]
>A proper nerf, targeting the self-sustaining trays is what should have been done. Gaia is useful for other things!

@GunHog then make a PR for it that brings it back without it automating botany

**Comment by Aloraydrel** [comment]
Do 👏 your 👏  job 👏

**Comment by unrealair** [comment]
whats it like having limited brain function

**Comment by Iamgoofball** [comment]
listen I'm about to push a cool botany feature so

**Comment by unrealair** [comment]
my beef with this is that botany is really strong but removing gaia does nothing to weaken it, it just reduces quality of life and makes trying to supply the chef(the intended job of botany) way more annoying

**Comment by kevinz000** [comment]
again goofball and others there's a difference between ah ealthy nerf to an overpowered department and taking away its fun completely and this seems like it'd take its fun completely just to deal with the wrong problem.

**Comment by Iamgoofball** [comment]
if removing a single plant "destroys" all the fun in botany, botany has some more serious flaws

**Comment by unrealair** [comment]
then are you going to hold the fun hostage until someone overhauls botany?

**Comment by FantasticFwoosh** [comment]
Just removing drugs from the seed vendor without actually reverting them was a rebalance too far for most people here, the actual 'Fun Brigade' arguement is that any change that is unfun is bad, which defeats the purpose when a PR topic is only fun for a group of people (botanists vs the station).

Fun = balance does not correlate, instead its actually a downward line-graph where without REAL precision balance changes. Often the fun comes from how absurdly unbalanced a thing is.

**Comment by unrealair** [comment]
okay fwoosh you **gigantic** retard, explain in what way gaia makes things less fun for non botanists.  I'll wait.

**Comment by FantasticFwoosh** [comment]
You aren't invested in it, there's no nurturing aspect and you're literally just in it for the produce. When you get all the plants you want, there's no process of keeping yourself busy and with gaia you can just ghost out or get a job change because you did everything the role offers.

**Comment by unrealair** [comment]
no listen

you just made an implication that gaia was only fun for the botanists and needed to be removed to make things more fun for everyone else

explain yourself thanks

**Comment by unrealair** [comment]
I swear your mouth is connected to your asshole because the only thing that comes out is verbal unrelated diarrhea and when you open it the smell of feces wafts from the atlantic to the pacific

**Comment by FantasticFwoosh** [comment]
It is, @Jalleo made a good suggestion earlier in IRC that removing the botanist job role completely and using remote harvesting robots/drones connected to a control panel accessible to service staff would mean that the kitchen grows what it wants & actually gets it. Chefs already have shared botany access on lowpop.

And i agree, because hydroponics are not obliged to work inter-departmentally, (even though its literally their job) so it should be a communally held job not by a group of selfish people assigned to the role to literally just grow meme plants. Remove the botanist job-role, they are a big part of the problem for being layabout stoners who don't provide services because nobody forces them to.

> Lol you doublepost just to flame me.

**Comment by Repukan** [comment]
Botany was still able to do dangerous shit before Gaia was added, not sure why automatization of it is necessary.

**Comment by FantasticFwoosh** [comment]
Least it'd go to the people who need it, botany grows the weapons/danger for themselves, and a lot of botany players are coders hence the terrible state it is in now with a lot of selfishly minded active coders making "Botanycreep" powerful plants and features.

> Chefs & bartenders plus anybody else in the department like the HOP will still need it on the side to do their jobs.

**Comment by unrealair** [comment]
Once again you abandon your own posts and don't even attempt to back up anything you're saying, to go for yet another subject dodge unrelated to the discussion.  I have to wonder how you survive day to day life, assuming you ever leave your house(doubtful)

At last you reveal your true intentions and why you won't have an actual logical discussion about it has been explained.  You're against the whole department and want it nerfed regardless of whether it should be or not and regardless of whether the right things are being nerfed.

Repukan I had my instant death plants already completed ten minutes into the round without gaia, the problem is that removing gaia is just a nerf to the ease of supplying the chef with plants and cargo with wood.

**Comment by Shadowlight213** [comment]
Gaia removal was a good change. It honestly should never have been added in the first place.
I mean, the DNA machine already took out most of the rng with getting perfect plants. Removing the maintenance on plants as well is just gutting entire gameplay mechanics in favor of QOL.

**Comment by unrealair** [comment]
the DNA machine is garbage now only good for swapping traits around, Cobby nerfed it a while ago if you didn't notice

**Comment by Shadowlight213** [comment]
I noticed. It was a good nerf. I was referring to the original dna machine.

**Comment by ExcessiveUseOfCobblestone** [comment]
> again goofball and others there's a difference between ah ealthy nerf to an overpowered department and taking away its fun completely and this (gaia removal) seems like it took its fun completely just to deal with the wrong problem.

Micromanaging the plants is half the fun though....

Botany was fun when you just messed around with plants, helped the chef, and became podpeople. Now people turn it into a weapons factory or medbay+ every round, which really wasn't [in my opinion] the direction botany should have taken.

**Comment by unrealair** [comment]
And it's not "removing the maintenance on plants" it's making it optional.  Apparently Fwoosh wants to "nurture" the plants and anyone who wants to do that can just not grow Gaia.

**Comment by ExcessiveUseOfCobblestone** [comment]
Upgrades should make them require less maintenance, not something you can get inhouse with 0 effort since the addition of Gaia came with never-dying plants when you add mutagen.

**Comment by unrealair** [comment]
Never dying plants is not a problem. The chef gets a shitload of wheat? The botanist gives the chef thirty different plants because he can grow them easily? Wow, clearly the chef's day is ruined. 

If you're going to bring up the overpowered shit botany grows, the problem is never that those plants live forever, it's that the plants are problematic in themselves.

**Comment by Repukan** [comment]
We should really get a word filter from QoL to powercreep tbh

**Comment by Aloraydrel** [comment]
Stop 👏  using 👏 powercreep 👏 crutches 🎬

**Comment by Qbopper** [comment]
i have the solution: instead of removing or readding anything to botany let's just scrap botany and make you fuckers grow the chef's food in dirt patches and remove any non-food plants

no fun allowed

**Comment by Repukan** [comment]
Let's hire space Mexicans to work botany at lowered wages.

**Comment by unrealair** [comment]
That doesn't work because the title botanist implies education

**Comment by Repukan** [comment]
😂

**Review by Cyberboss — APPROVED** [review]

**Comment by Ausops** [comment]
>dumb people who never went crazy having to click click click in old botany remove gaia
>same dumb people don't remove or nerf the plants that certain botanists abused and made botany so notorious
>every other department gets qol improvements and can step away from and resume their job whenever they want, but somehow removing botanys ability to do so hurts certain botanists specifically and not every botanist including the ones who just slowly grow food and autism projects

explain this without admitting to being dumb, you can't

**Comment by KorPhaeron** [comment]
ausops convinced me

**Comment by Lumipharon** [comment]
This is dumb. Botany was literally the first job I ever tried in ss13 and I've played the balls out of it. It has enjoyed more power creep then any other job except R&D, which recieved various nerfs because it was so terrible.
Botany lets you make 1 hit kill throwing/melee weapons that you can stack 50 per plant bag, among other hilarious shit.

Botany doesn't need afk buffs, it's already all but self sufficient and having to have 1 botanist actually be in your department every 10 minutes to keep your meme plants alive is literally a non issue. L I T E R A L L Y.
This is what keeping seeds are for. If you never bother to make seeds of your good plants you deserve to watch them all die.

Botany isn't like xenobio (unless it's changed, haven't played it for ages), where if your slimes die you literally have to start from grey slimes again.

**Pull request merged**
