### PR TITLE
Nerfs bombs by increasing the pressure needed to achieve bigger explosions.

### PR DESCRIPTION
**Pull request by Shadowlight213**
Ausops has backed this Pr and has offered to test it over the weekend. The idea is to make max caps harder to achieve even with fastmos rather than lower the bomb cap.

I'm not completely sure if I'm doing this correctly or if other values need to be adjusted, so feedback welcome.

### CODE REVIEW

**Comment by optimumtact** [comment]
how does this nerf bombs?

**Comment by Fox-McCloud** [comment]
Yeah, this doesn't really make them much harder, at all, to make.

Raising/lowering the bomb cap is the easiest way of buffing/nerfing bombs...currently the cap is a massive 5-10-20, IIRC....which...1 well placed explosion of that size pretty much screws over any chance of a decent round progression where that explosion went off.

**Comment by MrStonedOne** [comment]
I have an idea.

People want longer fires, but you can't mess with burn rate without nerfing bombs.

oh wait, people want nerfed bombs!

I'm gonna goof off with some numbers and see if I can't get a PR up that does the end goal of this one **and** has longer fires.

**Comment by Shadowlight213** [comment]
@Fox-Mcloud the idea was hopefully to make bombs harder to make for experienced players as well. If this doesn't do that, then I'll probably close this.
@MrStonedOne that sounds like a fantastic idea. Much better than my pr.

**Comment by Alek2ander** [comment]
This change is simple and direct. Take all bomb stats, divide by 3, without changing mechanics.
MSO's PR changes the required mixes for good booms (while reducing average power).
I think both should exist. Once the average blast radius with MSO's changes is clear, it should be nerfed to be slightly weaker than the sndie bomb, so that bombcap would only be reached by proficient toxin wranglers.

**Comment by as334** [comment]
Double nerfing toxin bombs while leaving the other much easier sources of explosions completely untouched is pretty stupid.

**Comment by Dorsisdwarf** [comment]
What "Much Easier" form  of explosion can hit dev 5 within 10 minutes of roundstart?

**Comment by Cheridan** [comment]
This pr seems to have been replaced by #12879 so i'll close this

**Pull request closed without merging**
