### PR TITLE
turns on the chat subsystem

### PR DESCRIPTION
**Pull request by tralezab**
I accidentally set it to not initialize, and it doesn't run if not initialized. So we've had it disabled for a good while... more than three months at least.

So here it is! the chat subsystem! tadaaa!

## About The Pull Request
This is just a subsystem that queues to_chats, so they cannot lag out your game. If the subsystem doesn't work, it will just revert back to the old system. <-- lol

~I really gotta test it more, because i'm not perfectly sure everything is alright yet!~ <-- you even knew  there would be trouble, past tralezab

### CODE REVIEW

**Comment by TheVekter** [comment]
If it makes you feel any better, Alien: Colonial Marines wouldn't have sucked if one coder hadn't made a single typo somewhere.

**Comment by actioninja** [comment]
Nah it still would have sucked it just would have sucked less

**Comment by PepperPrepper** [comment]
I'm interested in why you turned it off in the first place. Testing?

**Comment by actioninja** [comment]
Bad porting. Originally it didn't initialize but then issues with dropped messages were happening so it was made to check initialize, and if it wasn't initialized it would bypass it. trazelab forgot to remove the no init flag after this change was made.

**Comment by nemvar** [comment]
bye bye shotgun lag bye bye

**Pull request merged**
