### PR TITLE
Fixes the MetaStation Atmos table

### LINKED ISSUE #32105: You can't touch a table in atmos (MetaStation)

### PR DESCRIPTION
**Pull request by naltronix**
:cl: naltronix
fix: fixes #32105 
/:cl:

wew its my first pr

### CODE REVIEW

**Comment by duncathan** [comment]
Please use the map merger. Ask in #coderbus on rizon if you need help.

**Comment by duncathan** [comment]
Welcome to the codebase, by the way c:

**Comment by naltronix** [comment]
thanks. ill use map merger now and fix the pr for ya

**Comment by nicbn** [comment]
huh you did something wrong
it is showing thousands of changes

**Comment by nicbn** [comment]
Also no need for changelog

**Comment by Bawhoppen** [comment]
@praisenarsie We don't take kindly to those who use the discord dark theme around here.

**Comment by naltronix** [comment]
fuck i followed the wiki and still didnt do it
aaaaaa time to get irc

**Comment by naltronix** [comment]
oh im fucking retarded, i gotta do all those CHANGES AGAIN REEEE

**Comment by Bawhoppen** [comment]
Here's the shortened version of how to do it (starting from fresh):
1. Run prepare maps.bat
2. Make changes in DM and save
3. Run Map Merge TGM.bat
4. Select the file(s) you changed and run the process
5. Commit changes, push them Upstream, and then make your PR.

ALSO TO NOTE: Make a local branch off of your master to do these changes on. It will save you many headaches (allegedly, I never suffered any myself)

**Comment by Bawhoppen** [comment]
Goodluck

**Comment by naltronix** [comment]
fucked it up, sorry lads

**Pull request closed without merging**
