### PR TITLE
meteorslugs now knockdown instead of stunning

### PR DESCRIPTION
**Pull request by Fikou**
## About The Pull Request

replaces meteorslug 8 second stun with 8 second knockdown and 1.5 second stun
gives it 10 more damage as recompensation

## Why It's Good For The Game

meteorslug is one of the strongest slugs, with 20 damage and 8 second stuns and moving items wherever the fuck
ranged stuns supposed to be gone

## Changelog
:cl:
balance: meteorslugs now do a teeny tiny stun and a long knockdown instead of stunning for a long time, but do slightly more damage
/:cl:

### CODE REVIEW

**Comment by Fikou** [comment]
should i buff the damage a bit since i nerfed it to knockdown

**Comment by Shadowflame909** [comment]
Understandable

It bretty expensive to make though. Required 30k units of metal for the RCD mat, and end-game Weapons and Development research.

By the time you get it. You really don't have a use for it

**Comment by Tlaltecuhtli** [comment]
make it shoot meteors

**Comment by Shapsy** [comment]
Meteorshot is really underwhelming for how expensive they are to make and I don't think they even knock airlocks around anymore. Maybe set it up as a special breaching shotgun round?

**Comment by Fikou** [comment]
> Meteorshot is really underwhelming for how expensive they are to make and I don't think they even knock airlocks around anymore. Maybe set it up as a special breaching shotgun round?

they move anything that is movable

**Comment by Shapsy** [comment]
> > Meteorshot is really underwhelming for how expensive they are to make and I don't think they even knock airlocks around anymore. Maybe set it up as a special breaching shotgun round?
> 
> they move anything that is movable

Just double checked on the live server and airlocks must not be classified as movable cause they don't move



Being able to send airlocks and firelocks flying a few tiles (and preferably knock down and damage anyone in their way) would be a really flavorful and funny niche for meteorshot to occupy rather than just doing light damage and knockdown

**Comment by Fikou** [comment]
> Being able to send airlocks and firelocks flying a few tiles (and preferably knock down and damage anyone in their way) would be a really flavorful and funny niche for meteorshot to occupy rather than just doing light damage and knockdown

checks for ismovableatom, airlocks were probably changed to have big boy move resist or something without realizing it makes them not usable by meteorslug

**Comment by ExcessiveUseOfCobblestone** [comment]
should have a small upfront paralyze

**Pull request merged**
