### PR TITLE
Stops cloners from calling process() while autoprocessing is disabled, adds a config option to disable autoprocessing

### PR DESCRIPTION
**Pull request by vuonojenmustaturska**
:cl: Naksu
code: cloners will not waste processing time calling process() for no reason, only when autoprocessing is available and enabled
config: added a new config option to disable autocloning
/:cl:

### CODE REVIEW

**Comment by vuonojenmustaturska** [comment]
On a side note, this whole code needs to be rewritten from the ground up at some point; `src` is everywhere, as are ungodly amounts of jank and artisanal bespoke `RefreshParts` implementations that are not actually called `RefreshParts`

**Comment by Arianya** [comment]
Its artisanal code naksu

its more valuable then factory-made code

**Comment by KorPhaeron** [comment]
A config option to disable cloning is unrelated to this PR/something we shouldnt be putting in a config option at all

**Comment by kevinz000** [comment]
cloning disable is already in config, autolconing isn't though

**Comment by Iamgoofball** [comment]
Ah yes let's keep giving game design power to people who don't remember when Metastation got added, perfect

**Comment by Iamgoofball** [comment]
Remember guys, if you config option something, you will get stickybanned if you attempt to remove the feature even if **the headmins or kor say to remove it**. See: Secborg Removal and how that went down.

Direct quote from host:
"I don't care that the headmins voted to approve removal of the config, I don't fucking care that the head coder told you to do it. I am not going to enable your attempts to override admins, headmins, or host with code."
Source:
https://github.com/tgstation/tgstation/pull/32741

So please remember that configging something means **we can never remove it from the code**.

**Comment by Iamgoofball** [comment]
Archived just in case:
chrome_2018-05-31_10-56-38

**Comment by vuonojenmustaturska** [comment]
Kor said no

**Pull request closed without merging**
