### PR TITLE
Underwear Resprite

### PR DESCRIPTION
**Pull request by Twaticus**
## About The Pull Request

Resprites all our current underwear. Cleaner with a better greyscale. Tried to keep in the spirit of the old sprites, though some designs were changed.
Changed some underwear names.
Removed the 'Mens' and 'Ladies' prefix.
Fixed clipping on various underwear sidesprites.
erggadfdshhhghhhhhhh1
neko and kinky are unfortunately still static and uncolorable atm. having a bit of trouble with prefs so i'll revisit it in the future.

## Why It's Good For The Game

Underwear sprites were starting to show their age and there were a handful i'd never think twice about using because they were pretty ugly. Very happy with how these turned out :)

<details>
  <summary>cool thank you game</summary>

dreamseeker_KnCk2iREb0
dreamseeker_a4CJRkIJ8j

</details>

## Changelog

:cl:
imageadd: resprites all current underwear to a much cleaner look
/:cl:

### CODE REVIEW

**Comment by Shadowflame909** [comment]
Weirdo Alert: Everything looks great... but I feel like the heart on the heart lingere doesnt stand out as much with it being grey instead of a contrasting black.

Other then that, everything is +1 for being more defined. You can actually tell where the sprites begin and end.

**Comment by Twaticus** [comment]
> Weirdo Alert: Everything looks great... but I feel like the heart on the heart lingere doesnt stand out as much with it being grey instead of a contrasting black.

after looking at it again you're totally right i'll fix those colors

**Comment by CRITAWAKETS** [comment]
sorry but i just cannot see anything BUT a dixel in those men's underwear sprites

**Comment by Twaticus** [comment]
darker neko and kinky :)
image

**Pull request merged**
