### PR TITLE
Job landmarks now show the mob with the proper job outfit. 

### PR DESCRIPTION
**Pull request by lzimann**
Also adds a proc to generate these icons automatically.

The proc(which is acessible by enabling debug verbs -> mapping tab) is quite costly so it really shouldn't be used anywhere besides updating the icon when a job is changed. The generation also includes cyborg ,AI and X that are used on landmarks. 

Closes #33631

### CODE REVIEW

**Review by ShizCalev — CHANGES_REQUESTED** [review]
missing x3 & x4 from the .dmi

**Comment by ShizCalev** [comment]
might as well move the mapfixmarker into it too.

**Comment by Iamgoofball** [comment]
think we could maybe automate the generation of this? there's likely a way

**Comment by AnturK** [comment]
AI got split into frames

**Comment by lzimann** [comment]
Yea, for some reason it won't let me get only one frame

**Pull request merged**
