### PR TITLE
Premptively bans operator overloading

### PR DESCRIPTION
**Pull request by Cyberboss**
http://www.byond.com/forum/?post=2284516#comment23195678 
Let's not add spaghetti to spaghetti

### CODE REVIEW

**Comment by lzimann** [comment]
why are we banning something that doesn't even exist yet and who knows when it will

**Comment by ninjanomnom** [comment]
...this is a useful feature. Set up coding standards for how to use it, don't ban it outright. Overriding it for subtypes can be extremely useful.

**Comment by MrPerson** [comment]
Preemptive overloading is terrible and generally a waste of time. Correct use, however, can be useful.

**Comment by AnturK** [comment]
Is this a joke.

**Comment by MrPerson** [comment]
Lummox says he's going to add operator overloading for 512

**Comment by Iamgoofball** [comment]
what the fuck is operator overloading

**Comment by ninjanomnom** [comment]
Something that lets you override the default functionality of `+`, `-` etc for an object. So for example allowing you to do `pipenet+=pipe`

**Comment by Cyberboss** [comment]
Meme PR, but I still hate this with every fiber of my being

**Comment by Cyberboss** [comment]
512 is out, bringing this back

**Comment by lzimann** [comment]
banning it entirely is stupid

**Pull request closed without merging**
