### PR TITLE
Grand Ritual Finale: An end to death

### PR DESCRIPTION
**Pull request by Jacquerel**
## About The Pull Request

Adds a new Wizard Ritual Finale effect which makes everything immortal.
By this I mean, 10 seconds after death a ghostly image of them will appear somewhere near where the corpse was and then 50 seconds after that the mob will return to life at that location.
This applies to every mob, everywhere.
This is likely to cause a little bit of disruption to the rest of the round, so you can only do it after at least 30 minutes have passed. After that the crew will have to figure out how to deal with their new gift of immortality. It will involve throwing people into chasms and lava, probably.

dreamseeker_7SwMsSrnt1
Here's a gif sped up for example purposes.

You can escape from the cycle of death and rebirth via suicide, purely because it's pointless to try and force people to play the video game if they don't want to.

Also I split all of these effects into their own files, the only new code for those is in `immortality.dm`

shout out to Vekter for distracting Oranges while I posted this wizard-related PR so I didn't get disapprovingly reacted for posting magic shit (yet)

## Why It's Good For The Game

This might be _too_ much but I want to see what would happen.
It will allow us to simulate whether polite society can survive when violence has no consequences.

## Changelog

:cl:
add: Wizards who complete the grand ritual can now gift everyone with eternal life
/:cl:

### CODE REVIEW

**Comment by BlueMemesauce** [comment]
Do gibbed people get revived?

**Comment by carlarctg** [comment]
> You can escape from the cycle of death and rebirth via suicide, purely because it's pointless to try and force people to play the video game if they don't want to.

Does suicide stop revivals or does it just ghost the player while keeping the body alive?

If the former, it really really really shouldn't, it's a lot more immersive to see undying catatonic people that have gone mad from immortality than just the average suicided guy.

What happens if someone gets thrown into the SM?

**Comment by GPeckman** [comment]
> This applies to every mob, everywhere.

Infinite megafauna loot anyone?

**Comment by Sealed101** [comment]
> Infinite megafauna loot anyone?

this is a grand finale effect for a reason
___

did you intend to keep the cheese in the singularity basket or was that just an oversight

**Comment by SimplySmiley123** [comment]
Honestly this sounds funny as hell.

**Comment by the-orange-cow** [comment]
Idea:  completing this ritual additionally spawns a special super buffed nightmare/slaughter demon who's mission is to hunt down and permanently kill everyone.

**Comment by timothymtorres** [comment]
Yes please!  This is amazing

**Comment by Jacquerel** [comment]
> What happens if someone gets thrown into the SM?

They are revived on the tile next to the supermatter.

**Comment by ju45he** [comment]
> > What happens if someone gets thrown into the SM?
> 
> They are revived on the tile next to the supermatter.

If I threw 75 monkeys into the SM will they all create infinite energy for the station?

**Comment by Jacquerel** [comment]
> > > What happens if someone gets thrown into the SM?
> > 
> > 
> > They are revived on the tile next to the supermatter.
> 
> If I threw 75 monkeys into the SM will they all create infinite energy for the station?

They will continue respawning and pathing back into the crystal on a cycle, so probably yes.

**Comment by timothymtorres** [comment]
What about the singularity?

**Comment by moocowswag** [comment]
How does this work with blob and blobbernauts, i assume the blob wont get revived and will just die to infinitely respawning crew while blobbernauts it makes become independent antags afterwards

**Comment by Jacquerel** [comment]
> What about the singularity?

The singularity can eat the respawning ghosts and thus presents a kind of final death, you can assume that you're just stuck inside it if you want.

> How does this work with blob and blobbernauts, i assume the blob wont get revived and will just die to infinitely respawning crew while blobbernauts it makes become independent antags afterwards
> oh noo wait it might be able to flood the station with blob spores if they revive after death and the blob factories keep making them

The blob will die normally due to being a structure and not a mob, however you are correct that the crew killing a blob spore simply allows the factory to produce another one while the previous one then respawns later.
Leftover blobbernauts will probably get stuck in an endless cycle of dying from not having any blob tiles nearby and then coming back to life.

**Comment by Jacquerel** [comment]
> Okay so my assumption is this event can be gamed by beheading people and putting their brain in an mmi quickly to change where their soul is binded to

No power in the codebase can stop players from being boring
They would need to be real quick with their debraining though

**Comment by moocowswag** [comment]
Sorry if im bringing up too much im just trying to cover all of your bases you dont gotta answer all this its just something to think about

Does the brain respawn along with anything that its contained in? Like if an mmi gets blown up / dusted does it just respawn the brain? If the brain respawns with the mmi does this continue to circuit shells that the mmi was placed in? If so does it continue to what circuit shells are put in?

how does this interact spirit realm rune since it allows cultists to summon a semi limited number of players in and can instantly replace them (similar possibility to blob factory)

**Comment by Jacquerel** [comment]
> Sorry if im bringing up too much im just trying to cover all of your bases you dont gotta answer all this its just something to think about
> 
> Does the brain respawn along with anything that its contained in? Like if an mmi gets blown up / dusted does it just respawn the brain? If the brain respawns with the mmi does this continue to circuit shells that the mmi was placed in? If so does it continue to what circuit shells are put in?
> 
> how does this interact spirit realm rune since it allows cultists to summon a semi limited number of players in and can instantly replace them (similar possibility to blob factory)

Currently killing a brain in an MMI doesn't bring it back because its death proc doesn't call parent, though I am mildly interested to figure out why it doesn't and what would happen if I changed that I will probably leave this for now. There is no sensible way to revive a brain mob, because it's an abstract object placed inside an item. 
I guess I could spawn a new brain organ for it and put the mob inside that? You would probably end up with a talking brain though, which isn't ideal. And if you didn't it would just instantly die again and start spawning brains everywhere. No good alternative.

Cultist Spirit Realm is uh... interesting. As TimT says in the file:
```
		// Dear god, why is /mob/living/carbon/human/cult_ghost not a simple mob or species
		// someone please fix this at some point -TimT August 2022
```
Due to this, Summoning a dark spirit with Spirit Realm and then stepping off the rune essentially just turns ghosts into... regular humans. They don't even respawn with the cultist antagonist status.
I could fix this but I do think it's a little funny. I guess I'll apply the "don't revive" trait until such a time as someone does what this comment suggests. I will put that on my list.

**Comment by moocowswag** [comment]
Changeling headslug dies after biting a corpse to turn into a ling, would it revive the ling back in the headslug? What happens to the corpse that the ling infected? Etc

**Comment by moocowswag** [comment]
Xenobio being a department that works around the life and death of simple mob slimes and monkeys, the revival of dead monkeys means slimes are infinitely fed and split correct? Wouldnt that theoretically put the server on a timer before extreme lag takes place as the slimes continue to feed and split without player intervention?

**Comment by Jacquerel** [comment]
> im assuming what happens would be headslug bites corpse and dies, ling gets pulled back into revived headslug and the corpse gets gibbed and turned into a souless ling monkey
> 
> Oh wait how would the ling get a corpse? Does the event also work on the round start ones in morgue treys?

Correct. The changeling headslug can still infect corpses if it catches them before they are taken away, but will not be put into the monkey unless they tactically commit suicide at the right time.
The event doesn't revive anything which was dead before it triggers.

> Xenobio being a department that works around the life and death of simple mob slimes and monkeys, the revival of dead monkeys means slimes are infinitely fed and split correct? Wouldnt that theoretically put the server on a timer before extreme lag takes place as the slimes continue to feed and split without player intervention?

You can put one monkey in a pen to feed slimes indefinitely yes, this will start a cycle of feeding and rebirth, but as the corpse moves slightly every time it will probably eventually teleport out of the pen. It's also a very slow timer, you could achieve the same effect manually with much greater ease.

**Comment by moocowswag** [comment]
> 
> but as the corpse moves slightly every time it will probably eventually teleport out of the pen. 

And if slimes were to also die and teleport out the station could come into a grey goo scenario depending on the hunger level they respawn with and how likely they are to grow into an adult before crew kills thems and they respawn again (actually a funny eventual apocalypse scenario but would take a long time to snowball)

**Comment by moocowswag** [comment]
Goliath broodmother’s explosive baby goliaths

**Comment by moocowswag** [comment]
Are barbots that are successfully fed and going back through their portal considered dead and viable for revival? Potentially resulting in alot of barbots

**Comment by Jacquerel** [comment]
Legion minimobs don't respawn.
Customer mobs are deleted when they exit, rather than dying.
Broodmother mobs respawn but you can no longer summon them so they'll just sit where they respawn.
Holodeck mobs would respawn as normal, non-hololinked mobs. I've fixed that.

**Comment by moocowswag** [comment]
Animated things from that wizard wand / magic carp?

Worst case scenario it dupes items because when the mob dies the deanimated item is left but the mob itself revives as a new animated copy

**Comment by Jacquerel** [comment]
> Animated things from that wizard wand / magic carp spell?

Mimics in general won't know what they're supposed to be, so I'll have to make them non-reviveable because they would otherwise be invisible.

**Comment by moocowswag** [comment]
I think thats everything , i dont think items / special organs / implants  are kept on revival so should be safe from macro bomb implant on caynne the nukie fish or something silly like that

**Comment by Jacquerel** [comment]
> I think thats everything there is to worry about covered

Don't worry we will definitely find out about something we overlooked when/if this is merged.

**Comment by moocowswag** [comment]
Does it impact gamemodes like mafia

**Comment by Jacquerel** [comment]
> Does it impact gamemodes like mafia
image

**Comment by moocowswag** [comment]
Just have it ignore the centcomm z level

**Comment by moocowswag** [comment]
Oh right another neat interaction with this pr is the gene splicer since it kills and deletes the mobs you splice your genes with, they should still respawn and in theory you could give everyone fox ears c:

**Comment by wraith-54321** [comment]
> Legion minimobs don't respawn. 
Just checking but does this also apply to hivelord mobs?
Also how does this interact with malf AI living machines, or are those a type of mimic?
Also holoparas.

**Comment by Jacquerel** [comment]
> > Legion minimobs don't respawn.
> 
> Just checking but does this also apply to hivelord mobs? Also how does this interact with malf AI living machines, or are those a type of mimic? Also holoparas.

Yep, hivelord minimobs too. Animated machines are mimics.
Holoparasites and their attached players will both survive, but the holoparasite will become unlinked from its previous host. I consider this a feature.

**Review by ninjanomnom — APPROVED** [review]

**Comment by Admiral-Gigaton** [comment]
i know this was merged ages ago, but what about items? it looks like in the gif the corpse disappears, with the items they had, and then revives with the items back. what about when john rev kill bob captain and tries to take their ID, anything we can do for that? make it so john rev can loot the ghost?

**Pull request merged**
