### PR TITLE
Hotfixes need to breathe

### LINKED ISSUE #84698: You no longer need to breathe.
## Issue Summary
Post #84529, if you do not have internals enabled, you will not need to breathe. Turning on your internals will resume the need to breathe.

## Round ID:
Local on [master](https://github.com/tgstation/tgstation/commit/a13d142badbcdd9663bbd650c81495f2aa8657d8), no runtimes

## Reproduction:
Walk into space
Forget internal tank
- Die, but without taking oxygen damage (no suit)
- Don't die (suit)

### PR DESCRIPTION
**Pull request by SmArtKar**
## About The Pull Request

Closes #84698
#84529 accidentally removed check_breath ***which was where all breathing code was located***

## Changelog
:cl:
fix: You require breathing once more.
/:cl:

### CODE REVIEW

**Comment by MrMelbert** [comment]
Why didn't `/datum/unit_test/breath/breath_sanity` catch this?

**Comment by FlufflesTheDog** [comment]
It moved check_breath into the new try_breathing_sound proc, this will call it twice when internals are active

**Comment by MrMelbert** [comment]
^

**Comment by MrMelbert** [comment]
It should be `if(check_breath() && internals) try_breathing_sound()`, and remove `check_breath` from `try_breathing_sound`

**Comment by GoblinBackwards** [comment]
> Why didn't `/datum/unit_test/breath/breath_sanity` catch this?

https://github.com/tgstation/tgstation/blob/0f1c43379dc740d5363783650cbadd3ad4404f1a/code/modules/unit_tests/breath.dm#L25

check_breath is what would give these failing values, if check_breath never gets called then this assert will always pass

**Comment by SmArtKar** [comment]
why does this make you suffocate now

**Pull request merged**
