### PR TITLE
Mech-dominating Malf AIs will have their Doomsday timer stopped when their deactivated core is destroyed

### PR DESCRIPTION
**Pull request by Rhials**
## About The Pull Request

When a Malfunctioning AI dominates a mech, the Doomsday timer will still tick down like usual. With the changes made in this PR, however, the destruction of their deactivated core will disable the Doomsday timer.

So, if you're dominating a mech while doomsdaying and your empty core gets destroyed, the Doomsday countdown will stop. You will remain alive in your mech, and can shunt out to APCs if upgraded.

This PR was brought to you by poorly written signals and pointless trial-and-error. Like usual.

Also, this removes an unused variable from blobs, `fire_based`, which has become deprecated due to how blob strains handle temperature in modernity. This was kind of just in here from another thing I was looking at.
## Why It's Good For The Game

Doomsday has always been a final, dramatic point-defense battle for the crew to besiege wherever it is the AI has sheltered itself. When there's a single mech running around playing keep-away for eight minutes while everyone runs around in confusion, it leads to a pretty disappointing outcome for everyone involved.

By forcing the AI to protect its horcrux, it limits how much you can cheese the intended Doomsday experience. Despite this, it will still allow you to defend yourself from being stomped by robotics, whether it be a single renegade in a mech (free mech!) or three of them (cool! Mech-on-mech combat!).

Even if the core is mulched, you can still continue your malf round. It just means you lost the Doomsday gambit.
## Changelog
:cl: Rhials
balance: When dominating a mech as a Malfunctioning AI, the core you shunted from will disable your Doomsday Counterdown when destroyed. Make sure to protect that core!
/:cl:

### CODE REVIEW

**Review by Metekillot — COMMENTED** [review]
https://github.com/tgstation/tgstation/pull/88528/files#diff-d0f0a7615451517cc352bf10fc47216bbe9100510383e235d81dfdb8d28a7f49L25-L26

https://github.com/tgstation/tgstation/pull/88528/files#diff-423981845ca9ba6e374d3e34a23c52ec027092daf6e97dfa5005e5697100c4d3L15

It seems like it would be more appropriate to atomize this even if it's a small change.

**Comment by Vect0r2** [comment]
> https://github.com/tgstation/tgstation/pull/88528/files#diff-d0f0a7615451517cc352bf10fc47216bbe9100510383e235d81dfdb8d28a7f49L25-L26
> 
> https://github.com/tgstation/tgstation/pull/88528/files#diff-423981845ca9ba6e374d3e34a23c52ec027092daf6e97dfa5005e5697100c4d3L15
> 
> It seems like it would be more appropriate to atomize this even if it's a small change.

It's free GBP.... comeon rhials you should...

**Review by MrMelbert — COMMENTED** [review]
I would have just had it disable the doomsday device upon shunting to mech, like it does for shunting to APCs, but this is a clever solution 

To which does the pinpointer point to, the mech or the core? If not the core, it should be

**Comment by moocowswag** [comment]
I think it points to the mech currently, i recall seeing an ai that stole a mech to defend its core and the timer moved to the mech.

**Comment by DaydreamIQ** [comment]
Thank god, no longer will we have some shitass AI shunt into a phazon and then noclip into some wall nobody would be able to reach for five minutes

**Comment by MrMelbert** [comment]
> I personally disagree with this pr because moving to mech is one of the only ways to 100% stop someone from just hand teleporting or launchpadding onto the same tile as your core and carding you, having to kill a mech is much more exciting.

I think killing the mech is far more boring since most of the time the AI just takes the mech to some corner and hides, besieging the AI core is much more fun

**Comment by moocowswag** [comment]
> I think killing the mech is far more boring since most of the time the AI just takes the mech to some corner and hides, besieging the AI core is much more fun
> 
> On the other hand the prospect of the AI taking over a mech to _actually use it to fight people_ sounds way more fun

couldnt you just have the mechs position be more obvious? Like mech domination + doomsday = the mech itself starts releasing non damaging electric shocks or something because the ai is doing things with the mech’s hardware that it wasnt designed to be able to handle.

**Comment by Rhials** [comment]
> I would have just had it disable the doomsday device upon shunting to mech, like it does for shunting to APCs, but this is a clever solution
> 
> To which does the pinpointer point to, the mech or the core? If not the core, it should be

Haven't tested but logic indicates it would point towards the mech since the AI is moved "into" that. Will work on a solution.

> It's free GBP.... comeon rhials you should...

It's not always about the money spiderman.

**Comment by Rhials** [comment]
> Anything is better than making the ai helpess against teleport + card cheese (or in this case teleport ontop of ai core and wrench it so your spaceman sprite is hidden under it then start bashing and now ai mech cant hurt you)

This PR isn't meant to address the launchpad issue, this is trying to address mech stalling and present a clearer vision of what Doomsday "should" be.

While the opportunity is here, however, I would like to speak pretty plainly on it. I'm saying this not as an "own" or personal argument, I'm just providing my input -- If the station is in a state where a single renegade with a launchpad is an existential threat, you shouldn't be popping Doomsday to begin with.

**Comment by Metekillot** [comment]
> > I would have just had it disable the doomsday device upon shunting to mech, like it does for shunting to APCs, but this is a clever solution
> > 
> > To which does the pinpointer point to, the mech or the core? If not the core, it should be
> 
> Haven't tested but logic indicates it would point towards the mech since the AI is moved "into" that. Will work on a solution.
> 
> > It's free GBP.... comeon rhials you should...
> 
> It's not always about the money spiderman.

My concern is primarily to do with searching for things in the repository and the inevitable confusion of someone looking into the diabolical behemoth of AI and malf code, and getting results for blob code files instead

**Comment by Rhials** [comment]
Nuke tracker now points at the former core when mech dominating. Neato.

**Comment by SmArtKar** [comment]
CI dead

**Pull request merged**
