### PR TITLE
mice and its derivatives (rats and such) now swarm visually

### PR DESCRIPTION
**Pull request by mc-oofert**
## About The Pull Request

2023-09-18 16_58_34-Yo-ho-ho Factory Tau

## Why It's Good For The Game

improves visual clarity

## Changelog
:cl:
qol: mice and rats now are visually spaced out from eachother for visual clarity
/:cl:

### CODE REVIEW

**Review by Ghommie — APPROVED** [review]

**Comment by pilotmans** [comment]
uh oh

**Comment by IndieanaJones** [comment]
I think rats and mice should be confined to the tile they're actually on as to avoid issues of visual clarity.

**Comment by mc-oofert** [comment]
> I think rats and mice should be confined to the tile they're actually on as to avoid issues of visual clarity. If all those little guys are on the same tile, you can see how some of them visually are on the next tile over.

there are roughly 50 rats in that image

**Comment by SimplySmiley123** [comment]
> I think rats and mice should be confined to the tile they're actually on as to avoid issues of visual clarity. If all those little guys are on the same tile, you can see how some of them visually are on the next tile over.

At same time it would be great to actually see that it's a horde of rats and not just a singular rat just so you don't unknowingly walk into near instant death.
Though agreed that they shouldn't go _out_ of the tile they are on.

**Comment by Yttriums** [comment]
hell yeah

**Pull request merged**
