### PR TITLE
Properly reverts timed injectors

### PR DESCRIPTION
**Pull request by duncathan**
Fixes #12975 
This keeps the good changes and restores the injectors to how they were before. I did this on my phone so if it doesn't compile that'd be why.

My bad for merging the original PR; I didn't look closely enough at the comments. I'll make sure not to let it happen again.

:cl: Dunc
rscdel: DNA injectors have been restored to their original permanent RNG state from the impermanent guaranteed state.
/:cl:

### CODE REVIEW

**Comment by TheNightingale** [comment]
I quite like the original PR. It doesn't stop you getting powers permanently, it just stops you getting them /from injectors/ permanently. You have to use the console properly if you want them forever.

**Comment by MrStonedOne** [comment]
Change log pls =P

**Comment by Jordie0608** [comment]
code/game/machinery/computer/dna_console.dm:372:error: I.duration: undefined var

**Comment by Razharas** [comment]
This is just bad

**Comment by duncathan** [comment]
For the record this has been a wonderful lesson for me and I promise not to merge controversial shit again

**Comment by ike709** [comment]
"Razharas No Razharasing" tag please

**Comment by Jordie0608** [comment]
@MrStonedOne It looks like the auto-gen of a changelog was incorrectly triggered when this was closed in #12991

**Pull request merged**
