### PR TITLE
[WIP] Throw/Pick Up Drones/Various Animals! (Pick up /living/ framework + Throw mob_holders)

### PR DESCRIPTION
**Pull request by Chuckleberry-Finn**
:cl: Jittai
add: Thrown mob_holders transfer the throw to the mob. You can now throw drones (and corgis).
fix: You can now pick up Corgis again (alt+click)
fix: Placing a held drone (or mob holder) in a disposals bin actually works.
/:cl:

iuyb1eg

Note: Throwing operational drones into doors does open them.

[why]: Noticed you could throw held drones but due to how mob holders worked they'd just fall to the floor; while trying to fix this I noticed corgis had a broken pick up code. So I combined the two for easier expansion later.

### CODE REVIEW

**Comment by SgtxRootbeer** [comment]
can you also let me pick up and throw tables (at mekhi?)

**Comment by Grazyn** [comment]
David Motari approves this PR

**Comment by ChuckTheSheep** [comment]
Ok, so I fixed a pesky run-time and that fixed table/closet placement. It doesn't work with the meat-rack or grinder but it doesn't cause any issues either- you just have to put them on the floor first.

I can't think of anything else that you can stick items straight into by default like disposals.

**Comment by ChuckTheSheep** [comment]
Going to do the held icons, forgot about those.

**Comment by ChuckTheSheep** [comment]
All holdable mobs have held icons (except for mice).

**Comment by ChuckTheSheep** [comment]
@kevinz000 Just figured out you started this. lol

**Comment by ChuckTheSheep** [comment]
Found some monkey/mice held icons but in a different format. Going to redo the way holders are generated and hopefully eliminate the extra .dmi's.

**Comment by ChuckTheSheep** [comment]
Ok, all the behavior is tested and works.

Just need to fix two issues regarding monkeys:
1. They suffocate if on your head (and I presume hand)
2. They don't seem to respect the drop-release of mob_holders (they can pull corgis out of your hands and actually drop the itemized mob_holder)

**Comment by SpaceManiac** [comment]
The suffocation thing is not unique to mob holders, carbons also suffocate if placed inside a bluespace bodybag which is subsequently carried.

**Comment by ChuckTheSheep** [comment]
I know, carbons suffocate with in mobs and in objects inside mobs. Still trying to fix it.

**Comment by optimumtact** [comment]
ping for repopen when you figure it out or make a new pr

**Pull request closed without merging**
