### PR TITLE
Miscellaneous balance changes

### PR DESCRIPTION
**Pull request by ghost**
- Biodegrade now costs 2 DNA points
- Biodegrade now deals 10 changeling genetic damage and can only be used with 0 (effectively giving it a lengthy cooldown)
- Geiger counters, when emagged, can now only absorb up to 25 radiation at a time

### CODE REVIEW

**Comment by Core0verload** [comment]
Biodegrade must be fully removed. We have monkey and a bunch of stings to escape secs.

**Comment by Firecage** [comment]
Xhuis, since you are touching the changeling file aswell, can't you also fix the changeling transformation sting? Considering it does 100 genetic damage(who thought this was a good idea?) it literally makes the sting useless and punishes you for taking it, since it is a waste of points.

**Comment by Xhuis** [comment]
@Core0verload I feel like changelings shouldn't need to become almost useless to escape a pair of measly handcuffs when, logically, turning your arm into a _sword_ would be enough to shatter them anyway.

**Comment by Nanotransistor** [comment]
Also monkey is completely useless as an escape ability.

**Comment by Core0verload** [comment]
Just add armblade cuffs breaking and remove biodegrade. Breaking cuffs with armblade is very obvious - it's basically screaming "I'M LING BURN ME". Make it deal some genetic damage so ling remains weak for a while and can't spam other abilities.

**Pull request merged**
