### PR TITLE
Adds Proof of Testing to PULL_REQUEST_TEMPLATE.md

### PR DESCRIPTION
**Pull request by Iamgoofball**
## About The Pull Request

Adds Proof of Testing to PULL_REQUEST_TEMPLATE.md

## Why It's Good For The Game

When people show photographic or video evidence of testing their work, 

## Optional: Proof of Testing

This is an example of where you'd put proof of testing of your change. As a placeholder, here's my new favorite DBD build.

DeadByDaylight-Win64-Shipping_lVRTu7karf

## Changelog

:cl:
spellcheck: Proof of Testing is now in the PR template by default.
/:cl:

### CODE REVIEW

**Comment by zxaber** [comment]
I'm mostly upset that your proof isn't just a screenshot of the PR

**Comment by DATA-xPUNGED** [comment]
What does those new perks even do? I only know of the ghostface one

**Comment by MrMelbert** [comment]
@tgstation/commit-access Thoughts

**Comment by Jacquerel** [comment]
Skrat does (did?) this and I don't hate it
Problem is I feel like the majority of bugs in merged PRs that we have are a result of not retesting following refactoring, which a field in the PR body would not actually solve, so I am not sure there is much of a net gain here apart from more bureaucracy

This is a "we can have both" sort of issue but currently people don't even always bother filling in why their change is good for the game and I'd like us to have that down first before adding more fields I'm not sure necessarily solve very many problems

**Comment by lessthnthree** [comment]
I don't see what it really adds given the bugs that tend to pop up aren't things that would be visible in a screenshot or 5 seconds of video.

In reality people just take a screenshot to show "it compiled and I can start runtime station without it catching fire." which doesn't add a lot.

**Comment by CRITAWAKETS** [comment]
We have had pretty bad cases of PRs outright just not working when attempting to work in their intended role (arcmining...) so this isn't the worst idea out there.

**Comment by Jacquerel** [comment]
> We have had pretty bad cases of PRs outright just not working when attempting to work in their intended role (arcmining...) so this isn't the worst idea out there.

Wouldn't have caught anything in that PR for reasons stated above.

**Comment by CRITAWAKETS** [comment]
> Wouldn't have caught anything in that PR for reasons stated above. The Arcmining PR, IIRC, even _had_ a video attached so it already fulfils this criteria.

It would've, actually, since the boulder retrieval mechanic was completely broken by the time the PR was merged. Considering boulders are the entire point of the PR that's pretty much just the PR itself being fundamentally broken.

That said there _is_ something to be said about there being an outdated video where the PR was actually working then, but wasn't after some changes to the PR. Maybe the proof of testing has to be done on the latest commit after undrafting, or something of the sort?

**Comment by Jacquerel** [comment]
> It would've, actually, since the boulder retrieval mechanic was completely broken by the time the PR was merged. Considering boulders are the entire point of the PR that's pretty much just the PR itself being fundamentally broken.
> 
> That said there _is_ something to be said about there being an outdated video where the PR was actually working then, but wasn't after some changes to the PR. Maybe the proof of testing has to be done on the latest commit after undrafting, or something of the sort?

The PR body is filled in when the PR is posted.
At the time the PR was posted there was an attached video in which the boulder transfer worked.
This is why this method would be ineffective at catching these issues.

**Comment by LemonInTheDark** [comment]
> It would've, actually, since the boulder retrieval mechanic was completely broken by the time the PR was merged. Considering boulders are the entire point of the PR that's pretty much just the PR itself being fundamentally broken.
> 
> That said there _is_ something to be said about there being an outdated video where the PR was actually working then, but wasn't after some changes to the PR. Maybe the proof of testing has to be done on the latest commit after undrafting, or something of the sort?

I would hide this comment but it is useful as an example against itself. Kick rocks asshole

I'm not interested in this. We operate based off trust, nothing is going to change that at the end of the day, All this does is prompt people who don't know any better to test their shit, and I don't want people like that making large changes that would justify this. Outside of that it's just busywork.

**Pull request closed without merging**
