### PR TITLE
UFO cow abduction

### PR DESCRIPTION
**Pull request by Fikou**
## About The Pull Request

adds a helper for if something is a COW
makes abducting cows instantly

## Why It's Good For The Game

ufo abduct cow 

## Changelog
:cl: Fikou
add: NEWS REPORT: The latest alien technology allows them to abduct cows instantly, this is a great tragedy for all farm owners, better watch the garden!
/:cl:

### CODE REVIEW

**Comment by loserXD** [comment]
abductor buff

**Comment by AarontheIdiot** [comment]
speedmerge pls

**Comment by ishitbyabullet** [comment]
[footage of abductors abusing their new buff](https://www.youtube.com/watch?v=DHMDrhBREXU)

**Comment by HomocidlePancakes** [comment]
Can I surgery cow?

**Comment by Fikou** [comment]
> Can I surgery cow?

cow is a pet surgery is illegal

**Comment by HomocidlePancakes** [comment]
>Cow is pet

But I eat cow

**Pull request merged**
