### PR TITLE
Tinkerer's Caches cost one of each non-alloy component for every three existing caches

### PR DESCRIPTION
**Pull request by ChangelingRain**
:cl: Joan
experiment: Tinkerer's Caches now cost an additional one of each non-alloy component to construct for every three existing Tinkerer's Caches, up to a maximum of 5 of each non-alloy component.
/:cl:

Tactically inaccurate but accurate enough unless someone legit manages to make 100 caches math

### CODE REVIEW

**Comment by Amemelius** [comment]
What's the point? It doesn't change anything in terms of infinite stacking of resource production, so the same problem will be present, it'll just be slowed down very slightly, and I mean very slightly, since by the time you have three surrounded by walls, resources are really not much of a problem.

Now, if the cost exponentially increased, that would fix it, but I don't think it's as clean or sensible as just making resource acquisition logarithmic, meaning you get the most bang out of your buck for the first few tinkerer's caches, and the additional ones won't have as much of an effect. An effective soft-cap on resource acquisition so everything isn't effectively free.

**Comment by ChangelingRain** [comment]
Caches only generate components from one wall, more walls don't produce more components. See also #19378 which makes each cache require its own wall.

**Comment by Amemelius** [comment]
Hm, in which case I'll have to see it in action. If it's still too crazy, we can change it.

**Comment by Robustin** [comment]
Caches should work like this:

The cache must be on station (use dominator code or whatever) and it will automatically convert everything nearby into clockcult walls/doors/floors. There wont be a "wall" bonus anymore but it will operate at a fairly high rate of production. Caches dont have to be in a base or anything but they should be discrete so they dont get instadunked. Caches cannot be built within X tiles of another cache. Slabs should get their component generation buffed to compensate for the lack of cache spam.

This will force the clockcult to be strategic about where they drop caches and force them to either conceal or protect them. No more cache spam, no mores caches in space. Caches will have more meaning to them instead of just being a tedious requirement where you sit in space or a sealed off secret maint room spamming the cache button waiting for components next to an interior clockcult wall corner.

**Pull request merged**
