### PR TITLE
Improves Deadchat

### PR DESCRIPTION
**Pull request by Iamgoofball**
:cl: Iamgoofball
experiment: Deadchat has been made more realistic and immersive.
/:cl:

### CODE REVIEW

**Comment by Xhuis** [comment]
This is like the third PR for this holy moly

**Comment by RemieRichards** [comment]
meme PR

**Comment by Iamgoofball** [comment]
*realistic PR

**Comment by JJRcop** [comment]
"mumbles"

**Comment by RemieRichards** [comment]
can't be a realistic PR because your PR is in one of the most un-mergable forms the idea could exist in.

**Comment by Iamgoofball** [comment]
abuse

**Comment by RemieRichards** [comment]
Come back when the PR's actually ready with a proper implementation.

**Pull request closed without merging**
