### PR TITLE
Makes the Mining Asteroid Spikier

### PR DESCRIPTION
**Pull request by Strathcona**
This change is almost entirely cosmetic. I haven't touched any of the Mining outposts, their relative positions or the Gulag. I've redone the old outpost but there's really not much there. The biggest play difference is that navigating around the outside of the asteroid is slower but more varied and with recognizable landmarks.

Basically it was bugging me how the asteroid was all blobby and ugly when really there's so many cooler shapes for asteroids to be.

Before:
image

After

image

Fun fact, this was all done in about an hour with a simple little python script that converts an image like this:

image

into a .dmm. It's much easier to create organic shapes with an image editor than with DreamMaker tools.

### CODE REVIEW

**Comment by Bawhoppen** [comment]
Cool except for the change of the gulag and abandoned mining outpost locations
put them back closer to where they were originally

**Comment by Strathcona** [comment]
Abandoned outpost is the same distance from the northern outpost. I can move the Gulag over easy though.

**Comment by Bawhoppen** [comment]
Not quite what I meant, 
I mean, move the abandoned outpost to the left and restore its original design. And move up gulag further north.

**Comment by AnturK** [comment]
Post some screenshots of the jagged edges, i'm not sure how that looks outside minimap.

**Comment by Strathcona** [comment]
@Bawhoppen, I didn't want to have the gulag and the abandoned outpost so close. I guess I could recreate the chasm that was there before and try to make it look good.

@AnturK 
image

image

image

I can get some in game shots later tonight but keep in mind you'll only ever see 15x15 making most of the change unnoticeable.

**Comment by Steelpoint** [comment]
I think it looks great!

Shame we can't have the more Goonstation approach to asteroid layout, but that's another kettle of fish.

:+1:

**Comment by AnturK** [comment]
Looks good :+1:

**Comment by Supermichael777** [comment]
you mean where you dump so much super secret content in you cant actually fit mining anymore?

**Comment by Strathcona** [comment]
@Supermichael777, what super secret content?

**Comment by Jordie0608** [comment]
@Anonus jokes on you nerd i was right

**Comment by bgobandit** [comment]
how does this affect the possible locations for secret mining rooms?

also there's an issue related to that open while you're at it, fuck if I can find it though

**Comment by Zilenan91** [comment]
Do you mind giving the layouts of how things have changed on the abandoned mining station? I want to see how exactly it was changed so I can maybe run a few gimmicks off of it. By layouts I mean the actual in-game look if it's not too much trouble

**Comment by Niknakflak** [comment]
:-1:  This makes the asteroid a fucking porcupine and if it's purely for cosmetic reasons, why change away from what actual asteroids look like?  Most asteroids are not fucking spike balls

**Comment by Strathcona** [comment]
I certainly wasn't trying to be realistic. I just thought having some macroscale structure would be more interesting than a blob which isn't what real asteroids look like either. Real asteroids would be oblong, bumpy and probably not have any interesting features like canyons or craters. For gameplay reasons real asteroids wouldn't work as well.

**Comment by AlexanderUlanH** [comment]
Does this change preserve things like the distribution of high- and low-chance tiles?

**Comment by Strathcona** [comment]
There are slightly fewer (~2%) low chance tiles now compared to random tiles and slightly more tiles total (~2.5%). There are more high chance tiles total but they're spread out over a larger area. There's also a few more 2 tile clusters than before. I figure this is well within acceptable ranges seeing how you'll never get close to depleting the asteroid usually.

**Comment by Incoming5643** [comment]
why are changes to tgstation.2.1.3.dmm in this commit?

**Comment by Strathcona** [comment]
@Incoming5643  There shouldn't be. I've probably mixed up changes meant for another one of my branches in here.

**Comment by Niknakflak** [comment]
>asteroids dont have canyons or mountains
>asteroids are not blobs

Do some research first

**Comment by Steelpoint** [comment]
You can imply that the "canyons" are either man made or dug out by the monsters living in them.

**Comment by Strathcona** [comment]
Removed the random box changes and does some cosmetic work on the asteroid (diagonal single blocks and the like). 

@Niknakflak I was referring to bodies around the size of the mining asteroid which is pretty small, not larger objects like Ceres or what have you. The asteroid already has gravity so again, it's not like we're trying to be realistic anyway. If it'll be an inconvience we can close this since it was more a test of my little map making program than anything.

**Comment by Bawhoppen** [comment]
I want to see what your remap of the abandoned outpost was, because that thing is a classic and shouldn't be changed willy-nilly.

**Comment by Strathcona** [comment]
@Bawhoppen is that thing historic? If so, I'll just put it back in unchanged.

**Comment by Bawhoppen** [comment]
Eh, sorta historic. I remember it being like that as long as I've played or cared to look there. Kinda like the white ship I guess.

**Comment by Jalleo** [comment]
@Strathcona its the original one for TG i think ask @Korphaeron about it

**Comment by Strathcona** [comment]
Readded the old mining station. Horray for nostalgia. Not much interesting in there though to be honest.

**Comment by Zilenan91** [comment]
Can you post pictures?

**Comment by Iamgoofball** [comment]
Do you think you could supply that python script and throw it in the tools area of the repo? It seems pretty cool.

**Comment by Strathcona** [comment]
@Zilenan91  Course, I keep forgetting. It's the same thing as before on the old asteroid though.

image

@Iamgoofball If you guys would like. It's pretty basic and hacky. I'll clean it up and put it in a separate pull.

**Comment by Anonus** [comment]
I never actually saw what the new mining outpost would have been, what was it?

**Comment by Strathcona** [comment]
@Anonus It wasn't anything special, it just fit the geometry a little different

image

**Comment by Dorsisdwarf** [comment]
I like that one more

**Comment by Strathcona** [comment]
@Dorsisdwarf  there's so many misc mapping changes we can do / should probably do. I'll save it for another PR to keep this one focused purely on asteroid geometry.

**Comment by Niknakflak** [comment]
Muh realism

**Pull request merged**
