### PR TITLE
Meta fixes for several locations

### LINKED ISSUE #53654: light fixtures for supermatter south wall are misplaced on metastation
## Round ID:
n/a found locally

## Reproduction:
Walk to supermatter room. Locate light fixtures. be mildly annoyed
image

### PR DESCRIPTION
**Pull request by nightred**
## About The Pull Request

The console was deleted in a final fix up.
Also a newscaster.
And renamed the kitchen counter shutters.
Light in sm chamber moved
door to bar tweaked
another decal that bugged me
a light switch was just wrong
better bar flow
kitchen tweak
widened the hall in a notable way for like no loss
I will stop one day
but not today
some more decals
a waypoint was moved for better pathing
engineering lobby desk shifted

Fixes #53654

## Changelog
:cl:
fix: Meta Engineering lobby fixes and tweaks, added missing machine, moved lights in SM
fix: Meta The bar and kitchen have had several updates to objects
fix: Meta The service hall was widened by one tile
fix: Meta Atmosia has a fancy new control room and a bigger storage room for projects
/:cl:

### CODE REVIEW

**Review by Timberpoes — DISMISSED** [review]

**Review by Timberpoes — APPROVED** [review]

**Comment by kopoba** [comment]
image

**Comment by kopoba** [comment]
this is how you fix lights?
also whas it you who made this?
image

**Comment by nightred** [comment]
How did i fail to fix that light again....

**Comment by nightred** [comment]
nope this is fixed just not on your server yet.
Glad you like the new lobby it has been well received, i am always open to feedback if you have any.

**Pull request merged**
