### PR TITLE
Removes the multiverse and its sword

### PR DESCRIPTION
**Pull request by pubby**
We have enough TDM variants/admin memes and this is one of the weakest. It's currently holding up the gang removal, which is ironic considering gang has actual gameplay while this mode has none.

See #27872 for more rationale.

:cl: Pubby
del: The multiverse sword is toast
/:cl:

[why]: # (Please add a short description [on the next line] of why you think these changes would benefit the game. If you can't justify it in words, it might not be worth adding:)

### CODE REVIEW

**Comment by ExcessiveUseOfCobblestone** [comment]
Multiverse is hot garbage

**Comment by alexkar598** [comment]
Even if you remove this there will still be a universe where the multiverse has not been removed ERRoR ParADoxxx.$!;!,!.  Mul-$;:$&tiverse NoT FOUnd !

**Comment by KorPhaeron** [comment]
@tgstation/commit-access can correct me if I'm wrong about the code quality but multiverse aside I think its better to preserve the closest thing we have to flexible group antag datums until we have a better replacement

**Comment by optimumtact** [comment]
no

**Comment by BeeSting12** [comment]
I like the multiverse as a meme event occassionally though :(

**Comment by Hatfish** [comment]
if we can't have ragin mages then we can't have any nice things.

**Comment by AnturK** [comment]
Eh, not much systems value to preserve here. I don't think that's relevant. Just the question if it's not fun enough.

**Comment by Armhulen** [comment]
I really enjoy it

**Comment by lzimann** [comment]
It's just a gang , nothing really special about multiverse code. It is, however, one of the most annoying things in the game, won't be sad at all if this goes.

**Comment by Arzion5** [comment]
The question is : Why. Why would you want to remove something for the only reason that it is a weak "admeme"? Leave it in just for shits and giggles, there is no need to make the game more barebones than it is.

**Comment by XDTM** [comment]
It uses gang code to run

**Comment by megatiger78** [comment]
Merge copy summoning sword into holoparasites when

**Comment by ExcessiveUseOfCobblestone** [comment]
hahaha soulbound sord where you can summon clones but if the "boss" dies you all die

**Comment by MoreRobustThanYou** [comment]
gang datum is hard to preserve without preserving the entire gang mode

**Comment by lzimann** [comment]
@KorPhaeron i need an answer on this

**Comment by lzimann** [comment]
he said ok

**Comment by Armhulen** [comment]
make a me very sad

**Comment by optimumtact** [comment]
Add it back post gang them

**Pull request merged**
