### PR TITLE
Adds the experimental dissection surgery, a way for medbay to contribute to research

### PR DESCRIPTION
**Pull request by XDTM**
:cl: XDTM
add: Added the experimental dissection surgery, which can be performed once per corpse to gain techweb points.
add: Rarer specimens are more valuable, so xenos and rare species are more efficient subjects.
/:cl:

The surgery can only be performed once per body regardless of success or failure. If it fails, the point gain is drastically reduced (400 instead of 2000). Scalpel has a 60% base success rate.
Cyborgs cannot perform this surgery since they have a hardcoded 100% success rate.

Point gain is not final, i'll adjust based on feedback.
I might add point customization based on species or mobtype (monkeys would be worth little, xenos a lot, esoteric species more than base humans).

### CODE REVIEW

**Comment by coiax** [comment]
I didn't know that cyborgs have a 100% success rate.

**Comment by Poojawa** [comment]
Can/will this be cheesed by someone bluespace body bagging a dozen legion corpses from mining?

**Comment by XDTM** [comment]
Y'know, being able to spam human-grade mobs at little to no cost is a balancing issue that keeps coming up; i'm wondering if something should be done about it.

**Comment by Tlaltecuhtli** [comment]
make them ash

**Comment by Tlaltecuhtli** [comment]
@poojew having 3 department wasting their time farming seems intended gameplay

**Comment by Poojawa** [comment]
maybe just check if the body had a ckey at some point, then you can't cheese the system

**Comment by ExcessiveUseOfCobblestone** [comment]
I like the idea of incorporating surgery into the research point system but I'm not sure how much I like this system in particular. Cyborgs should definitely be able to play a role since they benefit from techwebs as well.

Perhaps a system where augments and upgrading organs gives points under the fluff that they gather data that can be used to further medical technology or something. Would be an incentive to getting them since any benefit is surpassed by the awful long wait inherit in all surgeries.

Hell, tech-organs upping the passive gen alone (if it's a non-afk player) would be nice.

**Comment by epochayur** [comment]
more things for medbay to do so it's a +1 from me

**Comment by Tlaltecuhtli** [comment]
i would say, make active borgs and ai give some points so ppl have incentive into borging

**Pull request merged**
