### PR TITLE
Pepper Mint cardboard cutout

### PR DESCRIPTION
**Pull request by francinum**
Pepper: arm wants you to make the pr

:cl: Keekenox
imageadd: Added a new pepper mint cardboard cutout sprite.
/:cl:

[why]: # (Please add a short description [two lines down] of why you think these changes would benefit the game. If you can't justify it in words, it might not be worth adding.)

### CODE REVIEW

**Comment by Wilchenx** [comment]
24hr rule

**Comment by optimumtact** [comment]
it's a guideline and I'm quite confident the other maintainers will agree

**Comment by Keekenox** [comment]
OOF

**Comment by iskyp** [comment]
30 S E C O N D S

**Comment by Stealthkibbler** [comment]
now the ca/tg/irls will form a lobby.

**Comment by RogueSteampunker** [comment]
For once, I agree with oranges

**Pull request closed without merging**
