### PR TITLE
Deltastation Trams Stress Testing

### PR DESCRIPTION
**Pull request by tralezab**
## About The Pull Request

Horribly modifies deltastation to have a tram run through it, from sec to engineering. It goes through a very dark tunnet. Spooky!

This does not come with tramstation itself, just some assets and left over stuff

## Why It's Good For The Game

Tramstation needs time to iron out mapping and multi-z bugs, I need to make sure trams are 100% working without subjecting people to it. Obviously don't merge this hahaha

### CODE REVIEW

**Comment by tralezab** [comment]
dubs and dubs!

**Comment by Qustinnus** [comment]
>Obviously don't merge this hahaha

unless?

**Comment by TemporalOroboros** [comment]
> > Obviously don't merge this hahaha
> 
> unless?

Incoming speedmerge?

**Comment by tralezab** [comment]
I'm serious this is a CANCEROUS map edit

**Comment by optimumtact** [comment]
Not a fan of how this acts like a multitile vehicle but doesn't use vehicle code, someone convince me otherwise

**Comment by TemporalOroboros** [comment]
> I'm serious this is a CANCEROUS map edit

You say that but it actually looks functional in mapdiffbot.

**Comment by Zytolg** [comment]
This must be speedmerged. 
For Science.

**Comment by tralezab** [comment]
Tests went well!

**Pull request closed without merging**
