### PR TITLE
Mapping changes to BoxStation's science

### PR DESCRIPTION
**Pull request by nicbn**
[Changelogs]: #
:cl:
tweak: BoxStation science changes: Circuitry lab is closer to RnD now; cannisters, portable vents, portable scrubbers, filters and mixers have been moved to Toxin Mixing Lab. There is now a firing range at the testing lab!
/:cl:

Circuitry lab is no longer isolated from the rest of science, being moved to the RnD section;

> Because circuitry was too isolated and actually felt out of place.

There is now a firing range;

> Because without the circuity lab there was extra space and as Box didn't have a firing range in science so I added it.

Atmos machinery moved to the place that uses atmos machinery (toxins);

> Because everytime you'd like to mess with toxins using machinery you'd have to grab the cannister of gas mix at temperatures hotter than the surface of the sun and take it to the area that was supposed to be used for testing guns and other non bomb things.
> Like in real life, dangerous things are supposed to be contained in the dangerous area so that damage can be minimized.
> And like in real life, things should be near the places that require such things to be used.

Experimentator is a little less isolated as now it's more like a part of the RnD section.

### CODE REVIEW

**Comment by cyclowns** [comment]
this feels like a lot more than just simple QOL changes
more like a complete remapping of boxstation science

**Comment by nicbn** [comment]
Ok I'll move the freezer to the toxins lab and remove the heater

**Comment by cyclowns** [comment]
that sounds like the opposite of QOL

**Comment by WJohn** [comment]
I'm seeing flooring beneath the experimentor room's window next to the door instead of plating.

Overall I'm really not happy about how the experimentor room looks right now. Feels very tacked on. But the experimentor has always looked and felt that way since its very addition. It could probably be removed in its entirety, or come back with a proper rework in the future, but right now it looks messy.

**Comment by ExcessiveUseOfCobblestone** [comment]
The experimentor room hasn't changed it seems from the image lol.

You could however make that maint and make old toxin storage an experimentor chamber.

**Comment by ExcessiveUseOfCobblestone** [comment]
Also you need to explain the purpose of doing these changes in your PR description please

**Comment by nicbn** [comment]
It is in the PR desc, right above the picture

**Comment by ExcessiveUseOfCobblestone** [comment]
You explained _what_ you did, not _why_ you did it.

**Comment by nicbn** [comment]
>Circuitry lab is no longer isolated from the rest of science, being moved to the RnD section;

Because circuitry was too isolated and actually felt out of place.

>There is now a firing range;

Because without the circuity lab there was extra space and as Box didn't have a firing range in science I added it.

>Atmos machinery moved to the place that uses atmos machinery (toxins);

Because everytime you'd like to mess with toxins using machinery you'd have to grab the cannister of gas mix at temperatures hotter than the surface of the sun and take it to the area that was supposed to be used for testing.
Like in real life, dangerous things are supposed to be contained in the dangerous area so that damage can be minimized.
And like in real life, things should be near the places that require such things to be used.

**Comment by ExcessiveUseOfCobblestone** [comment]
Thanks now put it in ur desc lol

**Comment by nicbn** [comment]
I'm keeping the heater actually

**Comment by nicbn** [comment]
Gonna resolve the conflicts after a review

**Comment by SpaceManiac** [comment]
Not an expert but it looks good enough to me, if you resolve the conflicts I'll test it out

**Comment by nicbn** [comment]
I'm going to resolve them tomorrow
kinda tired now

**Comment by nicbn** [comment]
@SpaceManiac

**Comment by SpaceManiac** [comment]
Judging by the map diff, it was broken before, but I wasn't able to get anything done in toxins because the burn chamber contains a scrubber which only removes carbon dioxide rather than a vent which removes everything. While you're already in here, that ought to be fixed. See Meta and Delta for examples.

**Comment by ExcessiveUseOfCobblestone** [comment]
Just need an air alarm to manage that.

**Comment by SpaceManiac** [comment]
Yes, the alternative would be to leave the air alarm for the area unlocked or set to toxins access (I checked and it wasn't).

**Comment by nicbn** [comment]
I think it was #39299 that broke the chamber
Yeah it needs an extra fixture too

**Comment by nicbn** [comment]
@SpaceManiac

**Review by SpaceManiac — APPROVED** [review]

**Pull request merged**
