### PR TITLE
security officers and the bartender now get a normal armor vest instead of the snowflake one

### PR DESCRIPTION
**Pull request by ghost**
## Why It's Good For The Game

:cl:
tweak: security officers and the bartender now get a normal armor vest instead of the snowflake one
/:cl:

### CODE REVIEW

**Comment by ATH1909** [comment]
Good change, but, uh, you do know that these two types of vests have no mechanical differences from each other (apart from differing sprites and dog fashion stuff), right?

**Comment by carlarctg** [comment]
👍 the one you start with looks like shit

**Comment by Tharcoonvagh** [comment]
FINALLY

**Comment by nemvar** [comment]
soul?

**Comment by ExcessiveUseOfCobblestone** [comment]
I personally am for a cobblestone-built bikeshed

**Comment by anconfuzedrock** [comment]
if you think the vest is ugly put on the other one lmao

**Comment by CRITAWAKETS** [comment]
if you remove the vest that you start out with, they have no way of actually getting the alternate vest

**Review by ExcessiveUseOfCobblestone — CHANGES_REQUESTED** [review]
I'll accept this if you make it 50/50 in all instances where it spawns, otherwise bikeshed.

**Comment by SkeletalElite** [comment]
What about just removing the alt vest from the game completely since its ugly AF and people only use it because its the one they spawn with and don't care enough to swap it.

**Pull request closed without merging**
