### PR TITLE
[READY] Plasma envirosuit resprites.

### PR DESCRIPTION
**Pull request by pireamaineach**
Resprites the new plasmaman envirosuits, adding some extra details to otherwise bare sprites and fixing the clashing colour-schemes of them.
Do note the clipping on the hands is a layering issue, can't do anything about that myself.

### CODE REVIEW

**Comment by Gousaid67** [comment]
i think the glove issue can simply be fixed by adding a simple variable to the base plasmaman suit.
> flags_inv = HIDEGLOVES

**Comment by VileBeggar** [comment]
these look really nice :+1:

**Comment by pireamaineach** [comment]
> i think the glove issue can simply be fixed by adding a simple variable to the base plasmaman suit.
> 
> > flags_inv = HIDEGLOVES

Would suck to have to make the suit hide gloves, ideally I'd like for the hands to be hidden behind the suit but the gloves go o'er the suit.

**Review by terranaut1 — APPROVED** [review]
upvoted 👍

**Comment by MegaEmpirical** [comment]
Do any of these sprites fix the suit being too big (side view width) for all jackets? There is always that one line of pixels on the back that extends beyond the trenchcoat or lab coat and so on.

**Comment by pireamaineach** [comment]
> Do any of these sprites fix the suit being too big (side view width) for all jackets? There is always that one line of pixels on the back that extends beyond the trenchcoat or lab coat and so on.

No, they just improve the overall look of them. It's notable that the detective's envirosuit doesn't stick out in the back, so it'd be safe with his trenchcoat.
That's not an error, just a side effect if the design. If nothing else they make the suits better integrated with the uniforms.

**Comment by nicbn** [comment]
You could add an extra overlay to show the gloves over the suit but below real gloves

**Comment by pireamaineach** [comment]
All been addressed before, the atmos and engineering suits mimic their normal counterparts in that sense.

**Comment by lmwevil** [comment]
so how do you get a new suit or recolour what you're wearing though (putting more suits around is dumb please don't do that)

**Comment by pireamaineach** [comment]
Been addressed before, see the original P.R.

**Comment by pireamaineach** [comment]
I don't think you understand what this is. These are resprites, not additional suits. The resprites are far, far better than the originals.

**Comment by nicbn** [comment]
Also you could make plasmamen spawn with gloves just for aesthetics

**Comment by MegaEmpirical** [comment]
> the atmos model is hard on the eyes, a few others are too - can these be changed in any way if a plasmeme wanted a new job?

Currently only spawned by joining as said job.

**Pull request merged**
