### PR TITLE
Buffs Lasers

### PR DESCRIPTION
**Pull request by optimumtact**
## About The Pull Request
This increases laser wound chance, increases the damage and also makes them use less energy.

## Why It's Good For The Game
Lasers cannot reload so they're not as convenient as a gun, so this will maybe make them more cool, honestly I just want to try this to see what happens.

## Changelog
:cl: oranges
balance: increased laser damage, decreased energy cost and increased wound chance
/:cl:

### CODE REVIEW

**Comment by Iamgoofball** [comment]
based oranges changes as usual #orangesIsMyBoss

**Comment by carlarctg** [comment]
lasers took a huge Hit in power vs ballistics when blood loss became so important

**Comment by BlueMemesauce** [comment]
> i think adding more shots is enough. more wound chance may be a bit overkill? but the armoury only has 3 lasers so maybe it wont be that bad

Lasers are pretty cheap compared to ballsitics, you can order a ton of them at cargo especially if its late in round. They're not really balanced by being limited.

**Comment by Fritzlschnitzel** [comment]
this will probably make them too strong but it will be fun to play either way, good change.

**Comment by Borisvanmemes** [comment]
How many shots can a laser gun fire with this change?

**Comment by DrDiasyl** [comment]
Finally a word "gun" in "laser gun" will mean something.

**Comment by CRITAWAKETS** [comment]
finally, the seclites wont be more powerful than the laser guns

**Comment by ExcessiveUseOfCobblestone** [comment]
lasers r the way to go anyways, they offer much more creative liberty when you dont have the gun bros from 4chan or whatever they use nowadays forcibly code 500 flavors of rifle/pistol ammo to maintain realistic standards

**Comment by YuliceTheDruid** [comment]
> lasers r the way to go anyways, they offer much more creative liberty when you dont have the gun bros from 4chan or whatever they use nowadays forcibly code 500 flavors of rifle/pistol ammo to maintain realistic standards

Listen I can respect both having "pistol ammo, rifle ammo, and smg ammo" and so on, and I can also respect "this is 7.62x25 made specially for the durgisburgis gun" but the latter kind of needs the entire game designed around it, which is why it (sort of) works for TGMC

**Comment by necromanceranne** [comment]
> How many shots can a laser gun fire with this change?

19

**Comment by moocowswag** [comment]
I would actually argue wound chance of lasers needs to stay the same or lowered because wound chance is based on the damage that you take.

But it does mean if i get hit a single time on accident I can probably kill whoever shot that laser since burn wounds are eventually debilitating and pretty hard to treat in certain circumstances.

**Comment by SethLafuente** [comment]
This change is gona be horrible for crew to antagonist balance you'll see

**Comment by nukularpower** [comment]
this change has been proven to be negative and shoudl frankly be reverted.   the buff was too high - now every antag needs to be refactored for this, when a much simpler solution is to simply revert this buff.   The benefit it provides is not worth the cost.

**Comment by optimumtact** [comment]
nobody cares

**Comment by DrDiasyl** [comment]
Average Orange man W, this man is too cool for this world.

**Comment by nukularpower** [comment]
I mean, judging from the conversations in game, a lot of people care.  I get the feeling YOU don't care, since this was shoved in with no testing or real consideration of how it would affect the game.  It almost seems irresponsible, in fact.

Or are you saying nobody cares because this is github, and there is there a better place to provide feedback on these idiotic changes?

**Comment by optimumtact** [comment]
l + ratio + touch grass

**Pull request merged**
