### PR TITLE
Adds a chemistry manual.

### PR DESCRIPTION
**Pull request by phil235**
Links to the wiki guide to chemistry.
It's currently not spawned in chemistry, cause I suck at map edit, so someone will have to add it in later.

### CODE REVIEW

**Comment by MrPerson** [comment]
It should read the recipes programattically, not statically

**Comment by Giacom** [comment]
What MrPerson said.

**Comment by PKPenguin321** [comment]
could always make it one of those books that opens the wiki page

**Comment by phil235** [comment]
Making some code to create a list of all the relevant recipes is too much work. I guess I'll just link the book to the wiki page, even though the page is huge and has non essential stuff.

**Comment by Razharas** [comment]
@phil235

**Pull request merged**
