### PR TITLE
[WIP, PRing to resolve atmos bugs] Delta Gas: Delta floating above a Gas Giant

### PR DESCRIPTION
**Pull request by Iamgoofball**
PR'd to review code for the gas giant atmosphere stuff

https://user-images.githubusercontent.com/4081722/177380405-53e14ac9-17cc-4418-8a84-0644be50cb25.mp4

### CODE REVIEW

**Comment by private-tristan** [comment]
https://user-images.githubusercontent.com/54422837/177393045-aca2bd6c-3807-4c71-bb04-82241ea0879c.mp4

**Comment by EOBGames** [comment]
Just marking this as draft since it's WIP

**Comment by Iamgoofball** [comment]
thanks

**Comment by Wallemations** [comment]
I'm concerned over how the hell the station is floating if moving outside of it instantly kills you

**Comment by TheBoondock** [comment]
Sm about to get a nice warm sauna

**Comment by Pickle-Coding** [comment]
The gravity generator could get replaced with a thruster to keep the station orbiting through the thick atmosphere.

**Comment by LemonInTheDark** [comment]
just to be clear I think this is a bad idea, but you could in theory manhandle atmos to make it work

**Comment by Wallemations** [comment]
I like the idea of different stations having different outer-atmospheric conditions and visuals, but this does seem a bit drastic lmao

**Comment by Miczu555PL** [comment]
Nukies on such station should have ship's equipment on their station and not have the ship.

**Comment by Mothblocks** [comment]
We have too many open PRs and this does not appear to be TM'd on any server

**Pull request closed without merging**
