### PR TITLE
Adds linting guidelines to CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by spookydonut**
## About The Pull Request
Signal handlers need the lint, new/changed ones shouldnt sleep.

Root procs that send signal should have call parent turned on.

### CODE REVIEW

**Comment by spookydonut** [comment]
@tgstation/commit-access

**Review by Cyberboss — APPROVED** [review]

**Review by Rohesie — APPROVED** [review]

**Review by ShizCalev — APPROVED** [review]

**Review by AnturK — APPROVED** [review]

**Comment by RuneQuester** [comment]
Comment

**Review by tralezab — APPROVED** [review]
code looks good 😋

**Comment by Kylerace** [comment]
KylerAce approved these changes 69 seconds ago

**Review by Mothblocks — APPROVED** [review]

**Review by LemonInTheDark — APPROVED** [review]

**Review by stylemistake — APPROVED** [review]

**Review by 81Denton — APPROVED** [review]

**Pull request merged**
