### PR TITLE
Fixes storage deletion bug, again

### LINKED ISSUE #30318: Using up objects (slimecores) in the biobag directly makes the bag appear empty until reopened.
Put in, say, two grey slimecores into a biobag. Inject one with blood, directly from the bag.

The other one will appear to vanish. It'll only reappear if you reopen the bag, dragging it to yourself etc.

This is a big timewaster for xenobiology when they're trying to process a lot of slimecores at once (which is basically every time they're producing monkeys). In an ideal world, it should show one less slime core in that position when you use it.

This may be tied with how slimecores act in regular bags - when you use one up there, it'll remove it from that slot without correcting the other objects in the bag, but only the first instance. So for example, I tend to put a bunch of slimecores in my satchel, then inject the first one, which vanishes from that slot without moving the others. I then inject the second one, and from there I can keep injecting the second slot as the cores I inject get used up and the next one is moved into that slot as normal.

### PR DESCRIPTION
**Pull request by XDTM**
Fixes #30318

Apparently it updates before the item properly deletes

### CODE REVIEW

**Comment by AnturK** [comment]
This looks like a hack, what's the core issue here ?

**Comment by XDTM** [comment]
Basically items call remove_from_storage (along with the visual update), _then_ actually get deleted removing their icon.

I guess some of the stuff above the update procs should be taking care of removing the item from the inventory, but it's not doing it, and i didn't find any modifications that may have caused that in the file history.

**Comment by RemieRichards** [comment]
How about:
```
		for(var/obj/O in contents)
			O.mouse_opacity = MOUSE_OPACITY_OPAQUE //This is here so storage items that spawn with contents correctly have the "click around item to equip"
			O.screen_loc = "[cx]:16,[cy]:16"
			O.maptext = ""
			O.layer = ABOVE_HUD_LAYER
			O.plane = ABOVE_HUD_PLANE
			cx++
			if(cx > (4+cols))
				cx = 4
				cy--
```

In ```standard_orient_objs()```

Becomes:
```
		for(var/obj/O in contents)
			if(QDELETED(O))
				continue
			O.mouse_opacity = MOUSE_OPACITY_OPAQUE //This is here so storage items that spawn with contents correctly have the "click around item to equip"
			O.screen_loc = "[cx]:16,[cy]:16"
			O.maptext = ""
			O.layer = ABOVE_HUD_LAYER
			O.plane = ABOVE_HUD_PLANE
			cx++
			if(cx > (4+cols))
				cx = 4
				cy--
```

?

**Comment by AnturK** [comment]
Yeah, something similar to that would be better, just check if there's no assumptions about the number of items somewhere else.

**Comment by RemieRichards** [comment]
There's no assumptions, layout is ordered by the cx cy vars, which as you can see I don't increment if the item ""doesn't exist""

**Comment by AnturK** [comment]
Inventory code is pretty mediocre,  so i wouldn't be surprised with some random contents.len's

**Comment by XDTM** [comment]
Alright, i'll try that

**Comment by XDTM** [comment]
Works properly, thanks!

**Comment by RemieRichards** [comment]
Good to hear.

**Comment by AnonymousNow** [comment]
This'll speed up xenobiology considerably. Ta much.

**Pull request merged**
