### PR TITLE
changes name of trait "STUNRESISTANCE" to trait "BATON_RESISTANCE", changes some descriptions 

### PR DESCRIPTION
**Pull request by private-tristan**
## About The Pull Request

see above
## Why It's Good For The Game

it will make a whole lot more sense when you look at the trait and see what it does, instead of assuming what it does based on its very clear name
## Changelog

🆑 
code: changed the name of TRAIT_STUNRESISTANCE to TRAIT_BATON_RESISTANCE
spellcheck: changed some descriptions of chemicals and heretic lore to be truthful
/:cl:

### CODE REVIEW

**Comment by private-tristan** [comment]
I am being told the merge conflict is caused by a rat

**Comment by moocowswag** [comment]
I always assumed stun resistance only affected the stun from stun batons and not stamina as well just because of the name, this is a good name change.

**Comment by private-tristan** [comment]
> I always assumed stun resistance only affected the stun from stun batons and not stamina as well just because of the name, this is a good name change just for clearing that up alone.

actually, the trait changes NOTHING other than the knockdown from telebatons/stunbatons, doing nothing to the stam damage that they inflict

**Comment by moocowswag** [comment]
> actually, the trait changes NOTHING other than the knockdown from telebatons/stunbatons, doing nothing to the stam damage that they inflict

oh so its being made into noob bait and people are gonna think that having baton resistance means they wont get 2 shot.

**Pull request merged**
