### PR TITLE
Adds webbing

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
By which I mean makes the silly red belts nuke ops have into chest rigs

I've taught you this enough times kor

### CODE REVIEW

**Comment by FantasticFwoosh** [comment]
This is really reminiscent of the points made on @Steelpoint webbing PR https://github.com/tgstation/tgstation/pull/27429#issuecomment-302692539 but this looks nicer on the syndicate commando commando theme.

> Kor just drag the image to the PR over the tabs (or from another window to make it pop up) but here's the OP picture for people too lazy to click on links.



Seemingly inspired by the below picture.

**Comment by QualityVan** [comment]
Brown on red isn't tacticool.

**Comment by FantasticFwoosh** [comment]
It is in a urban or martian enviroment.

**Comment by Steelpoint** [comment]
Isn't the webbing meant to be below the suit layer, then again if that was the case no one would ever see it.

**Comment by coiax** [comment]
Can we not meme, when other servers have webbing as "inventory attached to jumpsuits".

**Comment by KorPhaeron** [comment]
It'd be kind of hard to access your webbing if it was below your sealed space suit

**Comment by Steelpoint** [comment]
I don't think this is a issue, its a sprite change of the belt into webbing.

Perhaps offer both to Ops so they can chose what they look like.

**Comment by KorPhaeron** [comment]
@coiax 

Miners on our server already have belt slot webbing so its not like its without precedent

**Comment by FantasticFwoosh** [comment]
The only jumpsuit attachables we have anymore are waistcoats if memory serves and we don't particularly maintain that part of the code hence its very difficult if not actually not possible to use that system effectively.

**Comment by Steelpoint** [comment]
You can take off attachables using alt (or shift) click, I found that out with my webbing proposal PR.

**Comment by FantasticFwoosh** [comment]
@Steelpoint Its not exactly advertised as a common game fact nor do we really do anything with attachables currently to warrant putting webbing ontop of webbing when we can put alternative attachables on (like the waistcoats)

**Comment by Repukan** [comment]
@coiax we're not other servers 😏

**Comment by TehZombehz** [comment]
Maybe we can come in later and give them nuke op specific webbing. Brown doesn't seem to fit in with their color scheme.

**Comment by FantasticFwoosh** [comment]
I think it fits on ok, if it was black, it would be inconsiderate to the alternative black syndicate hardsuit in being too hard to see, i think this is being considered pallete wise too linearly.

Could we get some pictures with a ops wearing alternative suits with the rigging?

**Comment by BeeSting12** [comment]
Will this change traitor's military belt sprites? Buyable for 1 TC in uplink.

**Comment by FantasticFwoosh** [comment]
By definition @BeeSting12 it will because the old army belt was phased out.

**Comment by Bawhoppen** [comment]
:-1: x :100: seriously the military belts looked cool and made sense on their own, this is just dumb looking and makes no sense

if you're going to force it through, atleast add it as a subtype instead of replacing the military belts

**Comment by ShadowDeath6** [comment]
gonna repeat everyone else and say that brown on red looks really awful :-1: 
I'd prefer you take the webbing sprites from steelpoint's PR over these

**Comment by Durkel** [comment]
Ugly as sin tbh.

**Comment by jughu** [comment]
>the military belt looks cool

I call this story 50 shades of job belts

**Comment by kevinz000** [comment]
wtf no kor character sprites look fat without belts!!! REE!!

**Comment by PKPenguin321** [comment]
Looks kinda dumb and convers the really good syndie suit sprite

**Comment by KorPhaeron** [comment]
The guy who sprited it (Cheridan) likes it but I guess it is ultimately up to you @WJohn

**Comment by ChangelingRain** [comment]
should not be brown like jeez, brown is not a syndicate color

**Comment by optimumtact** [comment]
it's up to me

**Comment by coiax** [comment]
I have no words

**Comment by jughu** [comment]
Make it BLACK

**Pull request merged**
