### PR TITLE
Fixes bad atmos on lavaland

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
@duncathan 

Forgive me for my sins this is the best I can do

### CODE REVIEW

**Comment by lzimann** [comment]
will this fix gibtonite/hyper KAs or what

**Comment by KorPhaeron** [comment]
Yes

**Comment by duncathan** [comment]
you do need to call AfterChange() at some point

**Comment by KorPhaeron** [comment]
Why is that needed/where should I do it?

**Comment by KorPhaeron** [comment]
@duncathan 

Done

**Pull request merged**
