### PR TITLE
Fixes hot coco / Gives hot coco milk healing [READY]

### PR DESCRIPTION
**Pull request by OnlineGirlfriend**
## About The Pull Request

The hot coco recipe previously yielded "a glass of chocolate". This PR fixes it to result in "a glass of hot coco". Hot coco now inherits milk's chance for brute heal. I added a more unique glass description. I also re-categorized hot coco, tea, and coffee as drink recipes/reagents rather than foods.

## Why It's Good For The Game

The hot coco recipe will now function as intended.

## Changelog
:cl:
fix: hot coco glass name and description
fix: hot coco, tea, and coffee are now drink recipes (not food)
tweak: hot coco now has 20% chance of healing brute damage
/:cl:

### CODE REVIEW

**Comment by Iatots** [comment]
Ay still missing the 20% chance of healing brute per tick.

**Comment by kriskog** [comment]
Coffee and tea should probably also be moved, for the same reasons.

**Comment by OnlineGirlfriend** [comment]
Will update tonight.

**Comment by OnlineGirlfriend** [comment]
I have added the healing properties of milk to hot coco (I do like this for consistency) and recategorized tea and coffee.

**Pull request merged**
