### PR TITLE
Floors get dirty when used a lot

### PR DESCRIPTION
**Pull request by coiax**
:cl: coiax
add: Janitors rejoyce! When a floor has been used a great deal,
it may become dirty.
/:cl:

- It looks cool
- It makes thematic sense, have you seen the stuff that everyone stands
in
- It provides a visual indication of people actually walking places
- Provides an explanation of where the mapstart dirt comes from

### CODE REVIEW

**Comment by RemieRichards** [comment]
We had this before.
It was not liked.

**Comment by TrustyGun** [comment]
This reminds me of animal crossing 

The issue is that I hate that mechanic in animal crossing.

**Comment by coiax** [comment]
Hopefully not as ugly as in Animal Crossing.

**Comment by Niknakflak** [comment]
We had this before.
It was not liked

**Comment by ChangelingRain** [comment]
#11351

**Comment by Supermichael777** [comment]
[dejavu](http://www.youtube.com/watch?v=dv13gl0a-FA "dejavu")

**Comment by coiax** [comment]
I'm not hearing any support that would overcome @optimumtact's veto.

**Comment by xxalpha** [comment]
We had this before
You are now paprika

**Comment by coiax** [comment]
I like how it's attracting :-1: after it's been closed.

**Comment by optimumtact** [comment]
I don't recall explicitly vetoing it, I just don't like the idea

**Pull request closed without merging**
