### PR TITLE
New Fire Alarm Sound

### PR DESCRIPTION
**Pull request by Capsandi**
## About The Pull Request

Consolidates the 4 slightly different fire alarm sounds into a new alarm sound which no longer sounds like bass boosted farts
Reverb is no longer baked in, so it should sound better when game reverb is applied atop it.
All sound present is synthesized without sampling.
Listen to it here!
https://voca.ro/1j1jae1nFsm0

## Why It's Good For The Game

My first attempt at the fire siren was much better than the shrill beep of years past but is still very grating on the ears.
This new sound is unquestionably an alarm, but not one you can't listen to for an hour after a minor breach cools half the station below the alarm threshold.
Firelock hell should be slightly more bearable.
## Changelog

:cl:
soundadd: New fire alarm sound, go smash some exterior windows to hear it
/:cl:

### CODE REVIEW

**Comment by castawaynont** [comment]
droning is better than high pitched for how long fire alarms are going off

**Comment by Pumpkinoe** [comment]
ima be real with you
this sounds worse

**Comment by Zonespace27** [comment]
To my ears, this sounds *really* high-pitched and grating, and while the current fire alarm noise is annoying, this one is down-right "I don't want to hear this ever", to me at least. While it is more "realistic" that alarms would be loud, shrilly, and generally awful to hear, I don't feel like this'd be a good replacement.

**Comment by lessthnthree** [comment]
This is more grating than the existing alarm, I'd be muting the game before listening to this on loop for an hour.

**Comment by ZephyrTFA** [comment]
Couldn't even make myself listen to it more than three times

**Pull request closed without merging**
