### PR TITLE
Fixed TGchat volume control

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Review by Cyberboss — APPROVED** [review]

**Comment by JJRcop** [comment]
I... I ...
Well, I guess... yeah... oopsie.

**Comment by MoreRobustThanYou** [comment]
>Calling it tgchat

**Comment by deathride58** [comment]
Merge it merge it merge it merge it merge it merge it

**Comment by optimumtact** [comment]
I cannot figure out why this caused jquery to jump the shark

**Comment by JJRcop** [comment]
I know the volume property is 0-1 so maybe that's it?

**Comment by optimumtact** [comment]
yeah I suppose so

**Pull request merged**
