### PR TITLE
Cyborgs are now locked down until they pick a module.

### PR DESCRIPTION
**Pull request by Iamgoofball**
## About The Pull Request

Cyborgs are now locked down until they pick a module.

## Why It's Good For The Game
Headmin slash maintainer request.

Discord_PQvBKxqsUn

## Changelog
:cl:
qol: Cyborgs are now locked down until they pick a module.
/:cl:

### CODE REVIEW

**Comment by LemonInTheDark** [comment]
Timber kicks himself in the balls episode one: standard borg edition

**Comment by ArcaneDefence** [comment]
This request reads more like a shitpost than anything else to me.

In a further shitposting means-
Would a skilled robo not be able to disable this with a multitool before letting the borg run off anyway?

**Comment by MrMelbert** [comment]
Why is it good for the game?

**Comment by newfren** [comment]
quality of life?

**Comment by Iamgoofball** [comment]
@MrMelbert It is not my place to question a Headmin and a Maintainer.

**Comment by Vekzie** [comment]
I use the default borg without picking a module when the AI doesn't tell me what department needs help, so I go looking around before picking a module. Locking it down just makes it that much harder to pick a module, logically, as asimov from my perspective. I can only see this as a way to grief silicon players, unless you can give some really good reasons for why they would start as locked down, because I don't see the benefit. It would also heavily annoy robotics players, cause then they'd have to deal with locked down borgs asking for what module to go. Im not a coder or maintainer or anything, im just someone who plays silicon and robotics a lot.

**Comment by Ghommie** [comment]
> Why is it good for the game?


Exactly my thoughts, why is this good for the game? The screenshot itself doesn't really elaborate it either, might have likely been a shitpost as hinted by previous participants.

To begin with, there's a difference between the now removed default module and not having picked a module yet. The former was a module that had no specific departmental function or job assigned to them, while the latter is simply for borgs that have yet to pick a module, with no items or redeemable advantage over actual modules. If anyone is ever protesting against the years old removal of default borgs, let them rue over it as a toolless robot, which is already a punishment by itself.

> @MrMelbert It is not my place to question a Headmin and a Maintainer.

But you aren't obliged to do their bidding either. Hey, that doesn't even make you exempt from this sort of criticism.

**Comment by BlueMemesauce** [comment]
> I use the default borg without picking a module when the AI doesn't tell me what department needs help, so I go looking around before picking a module. Locking it down just makes it that much harder to pick a module, logically, as asimov from my perspective. I can only see this as a way to grief silicon players, unless you can give some really good reasons for why they would start as locked down, because I don't see the benefit. It would also heavily annoy robotics players, cause then they'd have to deal with locked down borgs asking for what module to go. Im not a coder or maintainer or anything, im just someone who plays silicon and robotics a lot.

This is something that we are trying to prevent. Silicons are meant to be specialized, but if they can just chose whatever module they want at any time it nullifies any specialization. Although Goofball probably did it as a joke, there is a legitimate reason that this PR should be merged.

**Comment by JohnFulpWillard** [comment]
quality of life?

**Comment by unit0016** [comment]
> This is something that we are trying to prevent. Silicons are meant to be specialized, but if they can just chose whatever module they want at any time it nullifies any specialization.

Isn't that already covered by the fact they need a human to reset their module, let alone all the per-module upgrades?

**Comment by Timberpoes** [comment]
Since this is based on me shitposting, I will take the L for this.

My bad, sorry for getting everyone's hopes up. I hate silicons but I don't hate them that much.

If they want to roam around as the default module to protest silicon changes, I will give them that freedom. It keeps silicon players' tiny little minds occupied so they're not elsewhere causing hurt and heartbreak in our community.

**Comment by Timberpoes** [comment]
Also I learned nothing and I would shitpost the same thing again.

**Pull request closed without merging**
