### PR TITLE
Adds a lead-in time, a warning and thus a possible response to Detomatix bombing.

### PR DESCRIPTION
**Pull request by Ghommie**
## About The Pull Request
Adds a lead-in time, a warning (under the form of a pda message with randomized name, job and text chosen from a plethora of weird, silly or referential text stings) and thus a possible response to Detomatix bombing. Also adds a STRINGIFY_PDA_TARGET macro because I don't trust the current way pda message targets are made.

## Why It's Good For The Game
An alternative to #62484. I don't share most of zxaber's view (who I mistakenly called Ghilker in the commit because their avis look fairly similar when thumbnailed) on detomatrix not being a source of interactions. He's right to say that the lack of warnings and time sucks for the receiving end, but outside that specific context, detomatix cartridges can, mostly indirectly, influence the way people interact in game. It gives nuclear operatives a way to invest TCs into screwing with the crew before they deploy. It helps keeping medical busy. It adds a thin layer of paranoia to the game that makes it a little more interesting because you know you aren't completely safe with a PDA with text messaging on. etc. etc.

TODO: add overlays for when a PDA is set to explode for a better visual warning. But Please merge #62259 first.

## Changelog

:cl:
balance: PDA bombing will now have a 2.5 seconds delay and will send a warning the receiving end (in the form of a silly, anonymous pda message) 
/:cl:

### CODE REVIEW

**Comment by Fikou** [comment]
can you remove the rng-ness from pda bombs if you are giving them such a huge time

**Comment by Ghommie** [comment]
> 
> 
> can you remove the rng-ness from pda bombs if you are giving them such a huge time

I can reduce the time value if you want. Just give me a number.

**Comment by NamelessFairy** [comment]
The messages got a chuckle out of me and I think this brings PDA bombs more in line with the AIs detonate RCD ability, certainly my preferred option out of the two PRs.

**Comment by optimumtact** [comment]
closing this simply because your commit shows you didn't even read the PR before raging about it.

**Comment by Coastfront** [comment]
literally 1984

**Comment by Ghommie** [comment]
> 
> 
> closing this simply because your commit shows you didn't even read the PR before raging about it.

That's two assertions you are doing there.

**Comment by optimumtact** [comment]
@Ghommie I didn't read your PR before raging about it, only seemed fair.

**Comment by Ghommie** [comment]
It's ok. We all know never do.

**Comment by Draggeru** [comment]
I'm really sad an actually interesting idea is just automatically binned because none of y'all can act like adults

**Comment by maxymax13** [comment]
oranges strikes again

**Comment by Technical-l** [comment]
god damn it'd be funny to use a pda messaging console to prank people with fake detomatix messages

**Pull request closed without merging**
