### PR TITLE
Temporarily disables stickyban

### PR DESCRIPTION
**Pull request by Buggy123**
Because banning half the server every day is bad, mmkay.

### CODE REVIEW

**Comment by Shadowlight213** [comment]
You do realize that all this does is prevent admins from removing the rogue stickybans? It won't fix anything.

**Comment by optimumtact** [comment]
This only affects basil so :-1:

**Comment by Buggy123** [comment]
Fuck i thought i commented out the right shit.

**Comment by Shadowlight213** [comment]
The actual problem behind stickyban has NOTHING to do with the ban panel. MSO and lummox already figured out what probably causes it.

**Comment by tkdrg** [comment]
no meme PRs please

**Pull request closed without merging**
