### PR TITLE
Mediborg Improvement Drive: Roller Robo Da

### PR DESCRIPTION
**Pull request by Incoming5643**
Adds an onboard roller bed dock that the mediborg can deploy wherever they need for on the spot triage/transportation/surgery/kidnapping. It can only hold one roller bed, but starts with one. This isn't regeneratable, so you can be a dick and steal the borg's bed and they'll have to go back to medbay for a replacement.

Related to #7694

### CODE REVIEW

**Comment by Deantwo** [comment]
Ooh, I like this idea.

PS: Why can't I put a body bag onto a rolling bed?

**Comment by phil235** [comment]
:+1:

**Comment by Jordie0608** [comment]
Changelog

**Comment by Incoming5643** [comment]
I was just going to push one with all the mediborg stuff that made it together

**Comment by Jordie0608** [comment]
If you make log message for each PR then when compiled it'll get grouped together as if you made for all afterwards.

See: https://github.com/tgstation/-tg-station/pull/7805/files#diff-edc089cab34d266b1ecb81c6c8342a62R88

**Comment by Miauw62** [comment]
pls changelog

**Comment by Incoming5643** [comment]
@Miauw62 @Jordie0608 Changelogged all my shit :heavy_check_mark:

**Pull request merged**
