### PR TITLE
Brain Damage: Revenge of the Salty Goofball (Meme PR)

### PR DESCRIPTION
**Pull request by Cuboos**
Goofy meme PR based on a salty rant @Iamgoofball had on #coderbuss last night. Adds a few extra lines to brain damage. 

This was just made for fun, i don't care if it gets merged or not.

### CODE REVIEW

**Review by Cyberboss — CHANGES_REQUESTED** [review]
58, 60, and 61 are 3 meta

**Comment by Iamgoofball** [comment]
:+1:

**Comment by ExcessiveUseOfCobblestone** [comment]
Leave the meta related messages to cult chants 😉

**Comment by optimumtact** [comment]
I think we have plenty of these already and I'm not sure about this as it's just making fun of someone who was legitimately angry at earlier handling of freon.

**Comment by Cuboos** [comment]
Darn, oh well, it was worth a shot.

**Comment by Iamgoofball** [comment]
but I thumbed it up

**Comment by Cuboos** [comment]
Sorry @Iamgoofball i guess you're just not memey enough to make a PR about.

**Pull request closed without merging**
