### PR TITLE
fixes some weird shading on the plasma tank sprite

### PR DESCRIPTION
**Pull request by CoiledLamb**
## About The Pull Request
a little bit ago, i resprited a lot of basic tanks. well, the plasmatank i had to do from the ground up, and it wasn't perfect by any means. so ryerice kindly did some shading corrections and gave it a cool new symbol... 
image
and it's a definite step up! 
## Why It's Good For The Game
my plasmatank resprite was fairly mid, so hopefully this brings it a little bit up to snuff.
## Changelog
:cl: CoiledLamb, RyeRice
image: cleans up shading on plasmatank sprite, gives it a cool new symbol.
/:cl:

### CODE REVIEW

**Comment by TheVekter** [comment]
What's the new symbol supposed to be?

**Comment by CoiledLamb** [comment]
> What's the new symbol supposed to be?

a flame! there was also an exclamation point but this one was my favorite

**Comment by CRITAWAKETS** [comment]
should've replaced it with the crescent and star

**Comment by TheVekter** [comment]
> should've replaced it with the star and crescent

... Why that?

**Pull request merged**
