### PR TITLE
Making Space Great Again (implying it ever was): Part Uno

### PR DESCRIPTION
**Pull request by MMMiracles**
:cl: MMMiracles
add: Adds space ruins. Balance not included.
tweak: Simple mob ghosts actually work now.
del: Puzzle1 ruin removed due to issues with projectiles.
/:cl:
People complained about too much space garbage so now I'm adding space garbage with LEWT

AWAY MISSIONS 2.0 LETS GO

ambush
_A caravan route used by tradestations was ambushed by a syndicate salvage team looking for easy profit. Turns out some space pirates had the same idea._

censoredtrade
_A once-bustling tradestation recently went eerily silent. A distress signal was sent off by one of the on-board officers but further attempts of contact has proven unsuccessful._

hotel1
_The Twin-Nexus, an interstellar hotel resort where the weary spaceman can rest their head and relax while the on-board staff caters to them. On-board hotel staff was screened ahead of time to make sure any subconscious urges for bloodlust were properly subdued before being hired._

Also includes a ship from ancient times, see it as a homage to the spaceman's ancestors.

Puzzle1 ruin removed because pixel projectiles ruin everything.

Blue shift sprites for the hotel security officer are @Nienhaus , all credit goes to them.
5ejnffn

### CODE REVIEW

**Comment by Armhulen** [comment]
This is so cool.

**Comment by Bawhoppen** [comment]
I'll say original assets but you'll never care enough to use them, atleast you added SOMETHING new

**Comment by MMMiracles** [comment]
Your complaint has been noted. Thank you for your time and we want to let you know how important your criticism is to us here.

**Comment by Armhulen** [comment]
I didn't notice this before, six people is a lot for the hotel. Eventually we're going to have to make a way to limit the amount of ghost roles on lavaland and hotel combined

**Comment by MMMiracles** [comment]
Hotel staff are a completely passive role like the space bartender, except they might actually get visited. They have explicit instructions in their flavor text and even an objective to stay on the hotel and cater to guests. 

I really hope admins step in and deal with shitlers who try to abuse it for valids.

**Comment by WJohn** [comment]
Huge :-1: 
I've said it before and I've said I'll say it again.
Put some detail into your maps, this is not even close to the detail on box station, and that's not a particularly high bar considering metastation exists.

You're giving me more work when I inevitably come back to these and remap all of them.

**Comment by MMMiracles** [comment]
Why would an asteroid field with some ships or a small trade post need the detail level of an entire station? 

Like how would I even give the caravan the same "detail" level? Map in departmental sections with a fully-functional atmos? 

Gotta love those unrealistic standards.

**Comment by Bawhoppen** [comment]
hey look I'm not the only one who thinks that its bad
also space bartender ruin was not finished and never meant to be added, please strip it from the code in this pr

**Comment by WJohn** [comment]
I'm not saying put in an entire atmos department like it would have to be a full space station, that's not the problem here.

The problem is that your rooms are empty. They have nothing in them, it's like with most away missions which lack damaged floor tiles, lights, power, wiring, ventilation, wall-mounted objects, firelocks or anything to look at.

And it annoys me to no end.

**Comment by MMMiracles** [comment]
I don't know if you're just bullshitted me or not because every ruin I added in this situation PR that'd make logical sense to have stuff like damaged turfs and wiring DOES have it. The only thing I skimped out on was a vent system as there's rarely an actual need for most ruins to require a separate atmos system. 

I won't ignore VALID critism (COUGH), but if you're just gonna accuse me of shit without actually looking at them fully, then I'm not going to respond nicely.

**Comment by Bawhoppen** [comment]
Take a step back and look at the ruins. They're extremely boring and generic. You can mitigate that with original assets, but I will concede the core of fixing that is mechanically. Add some interesting ideas to it, not just maps for the sake of mapping.

**Comment by xxalpha** [comment]
I wouldn't use smooth shuttle walls when making these damaged shuttles.

**Comment by MMMiracles** [comment]
@Bawhoppen 

Why would I make O R I G I N A L  A S S E T S for something that would literally not benefit from it past "oh look new decor sprites!!"?

Literally none of these ruins being suggested are remotely like current ruins already in the system (barring the hotel to an extent). All assets that were actually required to flesh out these ruins were already in the game barring a few minor details in the tradepost and hotel, which I did put something together to fit the criteria I needed. I'm not pulling extra sprites out of my ass for the sole purpose of "NEW ASSETS EVERYBODY HORY SHEET".

@xxalpha The shuttle walls looked fine enough to me in-game, but I'll see about adjusting some of the weirder angles the walls seem to take.

**Comment by xxalpha** [comment]
The problem is that smoothing makes it so they don't look damaged where they are supposed to look damaged.

**Comment by Durkel** [comment]
I noticed that you placed in those syndie turrets on the caravan map, Those things are going to cuck people instantly if they stumble upon on the map without a jetpack. They do like 60 brute a hit if they're functional.

**Comment by MMMiracles** [comment]
@Durkel They're the nerfed version that the drop-pod uses, which do 20 brute per hit.

I mean, you probably still shouldn't wander near the active shuttles but you're going to have a few warning hits to back off if you do.

**Comment by WJohn** [comment]
Here's an example of mapping that I did with an away mission, this is MO19 V2 (before damaging it).



Keep in mind, even this is not station levels of detail. But this should be the minimum level of detail for space content. I could go much further with placing all kinds of detailed floors, and then proceed to tear the station apart with damaged floors, smashed windows, air leaks, enabled fire alarms/firedoors, and xeno infestation on and on.

This is *before* I add all that extra detail, and it's already much further along.

**Comment by MMMiracles** [comment]
@WJohn 

The big difference between that and what I currently have is you're attempting to recreate an outpost meant to host a crew for months/years, similar to how a station would work.

The only ruin I have that may require a somewhat similar level of detail is the hotel one, which is expected to host a number of people for awhile. Everything else, such as the caravan and the tradepost literally do not require the near level of detail when it comes to design. One is literally just a group of cargo freights that were intercepted mid-route by small syndicate pods and the other is a small tradepost that was meant to handle imports/exports or just generally be short-term storage between routes.

I'll take your words into consideration and rework the hotel, but the rest literally can't supply that level of detail because it wouldn't make any sense for them to have it considering what they are.

**Comment by Iamgoofball** [comment]
ALSO you ruined all suprise by showing images of the entire map fullbright

**Comment by WJohn** [comment]
There's no such thing as surprises in an open source game whose community is full of powergaming tryhards. In any case hiding shit from the maintainers and anyone else who wants to criticize it would just make reviewing it a pain in the ass. We'd all have to download the map and spend a good 15 minutes loading it up.

**Comment by Yiu113** [comment]
The transport shuttle could be made better, though. Make them a bit bigger, then divide up the rooms, into a cockpit, a medical area, and the main cargo area. It's not the same as the dedicated cargo shuttle, but it's also a manned spacecraft, so it makes sense to have at least a medbay and a cockpit.

**Comment by MMMiracles** [comment]
Hotel has been given some more fluff (room signs in front of the proper doors, some decor filler to get rid of some empty space) as well as a basic atmos system. Air goes in, bad stuff gets sent into space. Also sports functional fire airlocks incase someone somehow manages to actually start a fire here.

Caravan ambush was modified a bit to give the shuttles a cockpit and pirates no longer want to brutally murder their own parrot.

Tradepost derelict had some minor fixes because I no powernet so good.

**Comment by Iamgoofball** [comment]
@WJohn That's a fat crock of bullshit WJ, and you know it.

MOST of our players don't follow the github, and MOST of our players won't be digging through map files looking for the optimal speedrun to the loot. Stop assuming all of our players are powergaming codediving shitlords, because in reality only a small percentage are.

**Comment by MMMiracles** [comment]
I mean honestly the only map that had anything worth censoring was the trade station one, which I did. The rest are extremely straight forward and have the context of their loot hidden still anyway. 

Also Goof has a point, the only person who really did look up missions in the editor and then try to speed run them were J_Mad.

 Half of the player base doesn't even know what github is, let alone how to download a branch and look at the maps (sadly enough).

**Comment by Bawhoppen** [comment]
wait are you also using simple animal humans? thats also a huge no-no

**Comment by MMMiracles** [comment]
@Bawhoppen ...why?

You know most of your 'feedback' would be much more helpful if you actually explained why you said what you said.

**Comment by Bawhoppen** [comment]
because simple animal humans are bad for so many reasons I don't need to explain

**Comment by MMMiracles** [comment]
@Bawhoppen So, you don't have any feedback past 'its bad because reasons'.

Your complaint has been noted. Thank you for your time and we want to let you know how important your criticism is to us here.

**Comment by Bawhoppen** [comment]
did you ever think to try and figure out why I'm saying they are?

**Comment by MMMiracles** [comment]
I don't see the issue with them considering they are exactly the same as any other simple mob enemy that we widely use, except it uses a different sprite for theme visuals.

Thank you for your feedback and criticism, no really. You are extremely helpful and I hope you keep commenting on future PRs.

**Comment by Bawhoppen** [comment]
its because simple animals dont act like how a human would and its dumb to have npcs that are supposed to be as smart as you or I (even in other games I hate it unless everything is heavily scripted)

**Comment by MMMiracles** [comment]
I mean, they are called 'simple animals' for a reason. Also considering they've existed and been mainly used for literal years as stand-ins for away missions and other admin events, I'm going to assume that 'big no-no' is just you sperging out over the fact for whatever reason.

**Comment by Bawhoppen** [comment]
I'm slowly trying to purge them from the game and this doesnt help

**Comment by MMMiracles** [comment]
Sounds like a personal issue unless a maintainer feels like backing up your point.

And don't even tell me to use SNPCs because those things are god-awful for actual combat.

**Comment by optimumtact** [comment]
We have to balance the quality of art vs the need to evolve as a game.

personally I think these look mostly fine, perhaps the hotel could use a little bit more customisation to make each room look more unique, but there's no reason someone else couldn't pick up and improve this work.

**Pull request merged**
