### PR TITLE
Service Jobs have Servicelathe access.

### PR DESCRIPTION
**Pull request by RaveRadbury**
## About The Pull Request
Added access to the service hall for Chaplain, Curator, Lawyer, Clown, and Mime.

## Why It's Good For The Game
It's weird not having access to your department's protolathe. How will the clown get an airhorn or pass out sad trombone implants if they can't get to their department's lathe? It also makes some pretty basic things that service jobs would appreciate having access to.

This is in line with and expands upon #43601 and the Tenets of Servicia: Happy, Full, Clean. 

## Changelog
:cl:
tweak: Service Halls now allow all Service dept. jobs.
/:cl:

### CODE REVIEW

**Comment by Mickyan** [comment]
it's pretty inconsistent (which is a problem in itself) but those are technically civilian jobs, not service

**Comment by Fikou** [comment]
i think this also prevents assistants from accessing the service lathe on delta so now they be DESTROYED

**Comment by Fikou** [comment]
> it's pretty inconsistent (which is a problem in itself) but those are technically civilian jobs, not service

the jobs got a service radio from a recent pr made by this guy and its merged, so now civilian jobs are becoming service leaving assistants alone

**Comment by RaveRadbury** [comment]
@Mickyan #43601 happened SO THE FUTURE IS NOW, OLD MAN.

**Comment by Mickyan** [comment]
Their listed department is still civilian

**Comment by RaveRadbury** [comment]
> i think this also prevents assistants from accessing the service lathe on delta so now they be DESTROYED

Servicia must be secure!

**Comment by necromanceranne** [comment]
No bear traps for the grey menace! Except that which is clamped firm upon their skinny, useless legs!

**Comment by habader** [comment]
Servicia banner better be next

**Comment by RaveRadbury** [comment]
One remaining issue here is that some of the lathes are in a part of maint that some jobs don't default have access to. Should I provide snowflake access for a maint door, or should people be expected to handle that?

**Comment by necromanceranne** [comment]
I'd suggest granting them access to that maint. Seems it is either that or moving the lathe to somewhere closer to public access.

**Comment by ExcessiveUseOfCobblestone** [comment]
if you post the lines of access code defines that you added/removed i'll merge this, I'm too lazy to doubletab it.

**Comment by RaveRadbury** [comment]
@ExcessiveUseOfCobblestone Still not quite sure how I screwed up all of this but the files are fine now.

**Comment by ExcessiveUseOfCobblestone** [comment]
quick before it goofs up

**Pull request merged**
