### PR TITLE
Fixes temperature guns to respect armor/dodge

### PR DESCRIPTION
**Pull request by vuonojenmustaturska**
The temperature values will likely have to be adjusted to account for small baseline armor, though I have in mind to revisit these and make them more juicy if I can source some sprites for my small security special weapons refactor/redesign.

In my mind this PR is a fix as it doesn't make sense that a bullet that didn't hit you still affects you, but it's been that way for at least 7 years so a balance tag is warranted on those grounds alone. But I am also adjusting the effect based on armor as well, so it would not be a pure fix even if you accept my logic.

:cl: Naksu
balance: Temperature gun projectiles now respect armor/dodge, and will no longer freeze you if they don't hit you.
/:cl:

### CODE REVIEW

**Comment by Bluespace** [comment]
no more shooting through double eswords

**Comment by Tlaltecuhtli** [comment]
i ded

**Comment by vuonojenmustaturska** [comment]
impossible, i don't play roles that are affected by these

**Comment by imsxz** [comment]
thank you kindly

**Comment by Borisvanmemes** [comment]
Hah, kev is going to flip over this

**Comment by Aurantiaco** [comment]
Thank jesus

**Comment by kevinz000** [comment]
finally someone sees the truth

**Comment by kevinz000** [comment]
also by the way i told you nerds so
https://github.com/tgstation/tgstation/pull/32181

**Comment by 81Denton** [comment]
Darn, at least you can still bully slimepeople with it.

**Comment by Incomptinence** [comment]
Is the double esword going to work as a spacesuit next also? 

Would really fit with deflecting all energy including the drat temperature.

**Comment by PKPenguin321** [comment]
I can't believe this

**Comment by AnturK** [comment]
Just think of it as keeping meta from getting stale.

**Pull request merged**
