### PR TITLE
Removes Spears and Stunprods.

### PR DESCRIPTION
**Pull request by Iamgoofball**
They're so fucking stupid. It's just greytide encouraging and a source of grief every round. Fuck 'em.

### CODE REVIEW

**Comment by kevinz000** [comment]
fuck you.

**Comment by DoctorPork** [comment]
fuck you.

**Comment by Armhulen** [comment]
fuck you.

**Comment by ExcessiveUseOfCobblestone** [comment]
fuck the admins

**Comment by Iamgoofball** [comment]
fuck you.

**Comment by kevinz000** [comment]
anyways this is dumb as fuck we do not need a one click method of permanently disposing of items.
fuck you.

**Comment by DoctorPork** [comment]
you should replace them with an intricate system to attach all sorts of shit to sticks

**Comment by Razharas** [comment]
Spears and stunprods are good
Denied

**Comment by Iamgoofball** [comment]
@kevinz000 
space
incinerator
recycler
explosions
fire

need I go on?

**Comment by GunHog** [comment]
This is what you get for deceptively naming your PRs!

**Comment by Haevacht** [comment]
Space doesn't delete your items,
Incinerator is in a sort of restricted area and there's one of them,
Recycler I havent used but can't it only break small w_class shit? Without emagging?
Explosions are, surprisingly, not easy to come by, the ones with a devastation radius anyway. Without bluespace beakers and that's more than one click,
it has to be a good fire to break shit

Anyway dumb meme.

**Comment by PKPenguin321** [comment]
recycler's actually easy to use i use it all the time
and one time i held a book burning in the library by making a bonfire

**Comment by Iamgoofball** [comment]
Space can strand your item in one of 8*255*255 random tiles.

**Comment by Haevacht** [comment]
Not deleted. Effectively removed from the round, barring a GPS, but not deleted.

**Comment by Iamgoofball** [comment]
Don't be a retard, it amounts to the same thing.

**Comment by Haevacht** [comment]
Techincally different.
There's a chance of recovery, its infintesemal, but it's there.

**Pull request closed without merging**
