### PR TITLE
Nerfs Critical Hits

### PR DESCRIPTION
**Pull request by Cheridan**
:cl: Cheridan
tweak: Nerfed Critical Hits
/:cl:

Instead of RNG chance of knocking you out forever GG faggot, a head hit makes you dizzy.
Chest hits still knock you down but for a shorter period. Chance reduced equal head hits since head/chest hits are more on par now.

hi ergo

### CODE REVIEW

**Comment by KorPhaeron** [comment]
@Jordie0608 you're the one who removed the "i ded" tag aren't you?

**Comment by KorPhaeron** [comment]
I feel like I should just close any PR that touches any stun at all until someone figures out how to redo tasers/stun batons because anything else is avoiding the heart of the issue

**Comment by Xhuis** [comment]
Maybe throw in a little blurriness too, to reflect "ouch my head just got slammed by a fucking extinguisher/what have you". I still massively favor this change though.

**Comment by PKPenguin321** [comment]
:-1: Getting KOd and dragged into maint when your would-be killer  thinks you're dead then getting up and whooping him is neat and also seeing random people get KOd by one hit from a crowbar is funny as fuck

Also this is i ded and imo conflicts with the unpredictable spirit of the game. If youre going to nerf it then make it not happen if you have adequate armor (so nuke ops don't get KOd through their tacticool suits and the round is ruined)

**Comment by Supermichael777** [comment]
pk stop memeing
you know the modern murderer dosnt stop untill they decapitate their foe

**Comment by Cheridan** [comment]
PK that doesn't happen, ever. They just keep beating you until you're dead. The duration is so long there's absolutely no hope of you coming back without someone coming to your aid or if the guy is new or something and just doesn't know any better.

**Comment by PKPenguin321** [comment]
Wrong, I have both done it and have had it happen to me on more than one occasion. Of course it doesn't happen every time, that is not my point.

**Comment by TechnoAlchemisto** [comment]
I've been knocked out in a situation where someone was fighting multiple people, they assumed I was in crit so they killed the other guy, then I got up and beat their ass to death, one of the most satisfying things in the game to be quite honest. 

Personally I take issue with knockdowns working purely off of force because piercing / slashing weapons shouldn't be knocking you back

**Comment by Ergovisavi** [comment]
Although I do think that this PR is in the right direction I am opposed to changing this portions at a time. If we're going to do this, we need to go whole hog.

**Comment by Supermichael777** [comment]
Demanding a massive overhaul misunderstands how development for this game works best:
small self contained changes which help shape the experience and smooth out the rough spots. You fools have gotten used to goofs memes. Big prs are for adding features.

that said your essentially demanding that stuns be removed from the game. That's not what this pr is about and your actually i ded yourself. Everyone gets wrecked by tasers, that's the point.  The problem is without that sec has no way of non-lethally detaining people. 

That said, I feel disarm needs to got the way of grab objects anyway so that ruing at someone with your bare hands is no longer biter then spears.

**Comment by optimumtact** [comment]
Confused should have replaced 99% of our knockdowns a long time ago.

It fits much more thematically with what they were trying to convey

**Comment by Cheridan** [comment]
PK that's the same thing people said about parapens: "Oh but in 1/10000 rounds someone uses it to do something interesting like kidnapping someone and hosting them hostage and dressing them in mime clothes"

Ok that's nice but the other 9999 rounds it sucks.

**Comment by kevinz000** [comment]
:+1:

**Comment by AnturK** [comment]
With crits being not immediately obvious (text message is not really that noticeable) with this they could use some different attack animation/effect. Or i guess leave that as is since it will have bigger effect on the fight this way ?

**Comment by PKPenguin321** [comment]
Alright, well you've still only addressed the first point in my original post

**Comment by ChangelingRain** [comment]
This should maybe also apply the actual dizziness effect?

**Comment by Fox-McCloud** [comment]
Pap tried this a long time ago, but it never happened because he got Git banned.

We've ran this on Para for a while, and it really does help out the whole "one hit, dead forever" thing.

**Comment by Durkel** [comment]
I know people hate this mechanic, but isn't this what ss13 is about? The rare chance that even while you're decked out in your best murderbone gear that some assistant can just fuck your shit up with a lucky hit. I know I've been fucked over plenty of times by this, but that's just ss13 to me, shit happens, you die.

**Comment by KorPhaeron** [comment]
Also a bit concerned about what Durkel brings up. Anyone being dangerous at any time and ridiculous rng wins can be frustrating, but a rigid meta and set power levels where the math says the guy with a better weapon (that is irreversibly locked to his role) will win sounds boring.

Maybe it is bad game design, but the ridiculous die roll is often the best story, at least in traditionall games.

**Comment by Cheridan** [comment]
Except even in D&D, rolling a 20 doesn't make you win instantly.

**Comment by Xhuis** [comment]
You clearly haven't seen me use Inflict Wounds.

**Comment by AdamElTablawy** [comment]
i mean on one hand it's fair enough that the guy with the better weapon will statistically win is boring and so that spice of risk to combat is a thing

but on the other hand when you're running down the halls in fucking SWAT gear and a random naked clown hits you in the head with a scapel and you go unconcious you might as well just throw your computer across the room and jack off in front of your kinect shouting BOMB THE PRESIDENT until the police show up

**Comment by Supermichael777** [comment]
armor does need to be more then a cosmetic

**Comment by KorPhaeron** [comment]
@Cheridan 

DnD is a better designed game where the core of the combat system isn't one hit kills

Which is really what this comes down to, I think, is that crits are bullshit because our regular combat is bullshit

**Comment by PKPenguin321** [comment]
Every day this game strays further from what it was

**Comment by TechnoAlchemisto** [comment]
so much for the design lead i guess

**Pull request merged**
