### PR TITLE
[Box] Area Power Fixes

### PR DESCRIPTION
**Pull request by Penguaro**
:cl: Penguaro
fix: Centcom Engineering has reviewed the plans for the Box series station and has addressed some concerns related to some APCs not affecting their designated section. APCs for the Detective's Office, Cargobay, and Gateway, now control those rooms. The Bridge Maintenance APC has been removed from future construction as it serves no purpose and thus is an unnecessary construction cost.
fix: The pipe from the station to the AI Satellite has been completed. 
/:cl:

[why]: # (Please add a short description [on the next line] of why you think these changes would benefit the game. If you can't justify it in words, it might not be worth adding:) 
There are several APCs that do not affect power in their sections. Changes as follows

Corrected the Areas for the APCs locations for Gateway, Detective's Office, Cargobay/Warehouse.
Removed the Bridge Maintenance APC as it controls nothing
Renamed the Locker Room Maintenance APC to Aft Port Maintenance APC as the lights affected by it are not near the Locker Room and could confuse someone as to what this APC actually controls.

As a miscellaneous fix, there was a missing atmo pipe going from the station to the AI Sat. I put it back in.

### CODE REVIEW

**Comment by octareenroon91** [comment]
Ok, that supermatter area change. Is that going to buff power sinks?

**Comment by Penguaro** [comment]
This doesn't change the area for the supermatter. That was done last month to add the air alarm that only controlled those scrubbers in the chamber. At the time, I didn't add an APC. This finishes that.

**Comment by octareenroon91** [comment]
Giving it an APC is giving it a weakness. I haven't looked at all the possibilities, so maybe we may as well just run with it.

**Comment by Penguaro** [comment]
If you can tell me where the code for buffing the engineering apc is, I'll look into extending it for this.

**Comment by Dorsisdwarf** [comment]
Its the cell type isnt it? Engineering APC starts with a highcap rather than a lowcap like normal APCs

**Comment by Penguaro** [comment]
Okay I cam change that. I knew there was something special, just had no idea what. I'll look in a little bit when I get to my computer. This APC was made as a new instance of the Engineering APC so it may alrrady have it. I agree that it should be buffed to the power sink.

**Comment by Penguaro** [comment]
@Dorsisdwarf @octareenroon91 I've doublechecked and the APC does have the high capacity charge that the engineering APC has.

**Comment by Penguaro** [comment]
I've removed the APC that I added to the SM core. I'm going do a separate PR for that because I want to make some other adjustments to engineering that may elicit discussion.

**Pull request merged**
