### PR TITLE
Public PDA (Weapons) chargers

### PR DESCRIPTION
**Pull request by zxaber**
## About The Pull Request
Companion PR for #78580. Adds two (or four) public-accessible weapons chargers, for charging PDAs *and nothing else*. These have been placed with the intention of being spread out and fairly accessible. In all cases, one exists in the dorms/locker room area.

- Birdshot has been given one charger in the arrivals lounge, and one in the main dorms area.

- For Delta I have added an extra table to the arrivals statue area for the charger. It's also now symmetrical with the opposite side, which has a coffee vendor in the same spot. A second charger is in the dorms locker room.

- Ice Box unfortunately has dorms in the arrivals hallway. Putting both public chargers so close wouldn't be ideal, so one has been placed in dorms, and the second in departures instead.

- Meta has been given a new table in arrivals hallway, just after the public shuttle, for the arrivals charger. A singular plant has been lost. The second is in dorms, as normal.

- North Star, being our designated big boi map, has four chargers. One per floor. Floor one has the charger just next to the holodeck. Floor two's charger is in the locker room. Floor three, in Dorms 1A (but not in Dorms 1B). The floor four charger is just outside the mid-ship stairwell door, making it fairly accessible but also within view of security.

- Finally, Tram, which also has dorms sitting close to arrivals. The first has been placed in the Fitness Room (lower floor), while the second is in Departures (upper floor).

@Zytolg for Birdshot considerations
@Cheshify for North Star considerations
## Why It's Good For The Game
Gives the crew public charging options for their PDAs, with the secondary use of charging weaponry for those of ill-intent.
## Changelog
:cl:
balance: All maps now have two public "PDA" (weapon) chargers (except one particular map with four). You'll find one in the dorms or locker room area.
/:cl:

### CODE REVIEW

**Comment by RedBaronFlyer** [comment]
I feel like it is a massive missed opportunity to not have chargers in the bar and kitchen if the reason for the PR in the first place is to get people out of their departments. Walking halfway across the station to a random part of dorms to charge your PDA sounds tedious and not really interesting. Like, yeah it gets you out of your department, but so does a radiation storm.

**Comment by zxaber** [comment]
Part of the goal was to introduce chargers that are public in nature but not necessarily in busy locations. Trying to charge a PDA while surrounded by kleptomaniac assistants sounds excessive stressful, and charging firearms is a similar story.

Also, the bar area already has food as a reason for people to gather. This gives other locations a reason to be visited, at least occasionally.

**Comment by MrMelbert** [comment]
Ngl I think it looks super awkward to have rechargers throw around on random tables, especially the North Star ones which just slaps tables in the middle of the hall. I would much prefer if they were more purpose-placed, or maybe at least give them a unique sprite to designate them as "pda rechargers" (even though they're functionally the same as rechargers)

**Comment by zxaber** [comment]
I'll grant you the Northstar table (floor 4, I assume). I wanted it outside of Sec, but I can move it.

Most of the others, though, already had a table there. I think the only other table I placed is on Delta.

**Comment by thgvr** [comment]
> Ngl I think it looks super awkward to have rechargers throw around on random tables, especially the North Star ones which just slaps tables in the middle of the hall. I would much prefer if they were more purpose-placed, or maybe at least give them a unique sprite to designate them as "pda rechargers" (even though they're functionally the same as rechargers)

A machine's function shouldn't be obfuscated, if all feedback indicates they are "pda chargers", that's all they should be. Hiding weapon charging functionality behind that isn't really good design.

Regardless, the PR does not add pda chargers, it adds weapon chargers to maps and should reflect that.

**Comment by zxaber** [comment]
Northstar Floor 4 no longer has a new table. Instead, the charger has been moved to an already-existing table outside the bridge.

**Comment by Mothblocks** [comment]
PDA power shouldn't have been nerfed and people feeling the need to clutter maps with confusing shit is a great reason why

**Comment by Mothblocks** [comment]
To be clear making these specifically PDA chargers would be even worse, we shouldn't have bespoek shit like that cluttering the map

**Comment by Mothblocks** [comment]
Also if the point of PDA power nerfing was to make people interact with each other then putting in a bunch of things around the map that don't require another person completely defeats the purpose and makes it more obviously just pointless tedium

**Comment by Mothblocks** [comment]
Basically I think this is dumb whether you're for or against PDA power

**Comment by JohnFulpWillard** [comment]
These aren't PDA chargers, they are regular chargers. PDAs charging the same way batons and guns do means that this becomes a public area you can charge your stuff as an antagonist and whatnot without having to go get tools to hack into areas, at the cost of it being more public than in your department and people will be able to notice more easily what is being charged.

**Comment by Mothblocks** [comment]
The primary motivation in the why it's good for the game is PDA charging and this PR wouldn't have been made without it. At the same time it trivializes PDA charging and invalidates the argument for it not being just tedium--the task of getting a power cell is a much more interesting one than walking to a charger.

If you want to add more rechargers to the map for the sake of environmental emphasis (which is always a noble one) then I want that to be done in a way that isn't mindlessly putting them on tables, but I don't have trust that is going to be the goal here for a long time

**Comment by Mothblocks** [comment]
I don't think we can have this and PDA power being something people are expected to care about at the same time is my point

**Pull request closed without merging**
