### PR TITLE
Adds drones as a roundstart job

### PR DESCRIPTION
**Pull request by Tacolizard**
:cl: Tacolizard Forever: Autism Fort Overdrive
add: NanoTrasen has decided to ship drones to the station to help maintain it! Drones are now a selectable job.
/:cl:

[why]: I've heard many people asking for this during my time playing and to my surprise, this PR was easier to make than I expected. Yes, the drones in this PR still have the same laws as normal drones.

**lore**
NT decided that drones are useful enough that they now supply them to the station instead of requiring them to be built.

### CODE REVIEW

**Comment by Bawhoppen** [comment]
inb4 "PEOPLE ARE HAVING THE WRONG KIND OF FUN"

**Comment by FantasticFwoosh** [comment]
This half intrigues me, but most of the drone's appropriate reactions comes from ghost meta-knowledge.

Sort of reminds me of ghost roles like VG's vox traders, not station affiliated but roundstart.

**Comment by BeeSting12** [comment]
Where's the spawn positions? I think you have to place those on the map, right?

**Comment by Tacolizard** [comment]
Hopefully having drones as a roundstart job will encourage them to do their jobs more instead of using meta-knowledge to mess around with the round.

**Comment by Anonmare** [comment]
I suppose it's fine. If people want to play drone then they'd just hit observe instead of join and find empty shells and it's better they do that then take up job slots+suicide

**Comment by Tacolizard** [comment]
@BeeSting12 No, there are spawn locations

**Comment by SgtxRootbeer** [comment]
Yes fwoosh, but the drone can listen to binary for the express purpose of seeing what threat the ai is aware of and going to fix it.

**Comment by Tacolizard** [comment]
@Anonmare It's also good because suiciding to become a drone is taking the risk that someone filled the drone dispenser

**Comment by Tacolizard** [comment]
@FantasticFwoosh this will also hopefully get people to use the drone phone more often. 

Since drones usually join when the station is already falling to pieces, now they'll be able to actually do their job.

**Comment by Penguaro** [comment]
It's nice when the Derelict spawns since you can kinda roundstart drone that way through the Observe route but it's always a risk that the derelict isn't there.

@Tacolizard So I don't see any map changes. Are these piggy-backing on a different jobs spawn point?

**Comment by FantasticFwoosh** [comment]
No i explicitly mean literally sitting in the round for 10 minutes deciding to spawn or not because if you turn up in the middle of a blob or nuke op round you're not actually going to be able to fix any damages without getting bwoinked for interference and may as well destroy yourself.

**Comment by Tacolizard** [comment]
@Penguaro ((((((((yes))))))))))

**Comment by coiax** [comment]
Why have you added the +x flag to all the files, undo this immediately

**Comment by Penguaro** [comment]
So with this, you cannot late join as a drone. Is that intentional? And the spawn point is randomly selected from the available points then?

**Comment by optimumtact** [comment]
No thanks I don't like drones as a roundstart job.

**Comment by coiax** [comment]
image

**Comment by coiax** [comment]
@Cheridan @RemieRichards @KorPhaeron @Cheridan please control your fruit

**Comment by Penguaro** [comment]
@optimumtact I find your directness refreshing. Please do not ever change that about your approach.

**Comment by Tacolizard** [comment]
@Cheridan the fruit says you need to give permission for this PR

**Comment by optimumtact** [comment]
@Tacolizard you left before I could reply but yes obviously my word is not final, I'm happy to let either @KorPhaeron or @Cheridan overrule me

**Comment by RandomMarine** [comment]
I say this as someone who's pretty damn pro-drone.
I feel that drones need some changes before they become available roundstart. Since it's easy for them to set up a lathe with a design disk and endlessly replicate themselves.

Almost every round will have imperfect drones doing imperfect things that are nigh-impossible to stop unless someone sits at the robotics console to blow every drone that activates.

**Comment by XDTM** [comment]
Without this people just queue as scientists to suicidrone anyway. Might as well have them not take sci slots.

**Comment by optimumtact** [comment]
do you have any names, surely that's a bannable thing

**Comment by Anonmare** [comment]
@optimumtact It's not bannable to suicide at roundstart unless you're a head/important role. Plus it's practically unenforceable

**Comment by RemieRichards** [comment]
It is enforceable, I wrote a thing that if someone suicides within the first 10 or so minutes they get reduced antag chances, though at the time Rocktdnben wanted me to make it non-automated, and a thing for admins to use but never got around to it.

could always bring that back.

**Pull request closed without merging**
