### PR TITLE
Adds Wumborian Fugu to the gold core spawn

### PR DESCRIPTION
**Pull request by ghost**
my reasoning was in the watcher pr but i'll copy it here.

Xenobio is here for exotic creatures but the roster is so small it feels like you get the same garbage every time. Lets spice it up, yeah?

### CODE REVIEW

**Comment by KorPhaeron** [comment]
Do these even work when player controlled

**Comment by Armhulen** [comment]
Yes

**Comment by Repukan** [comment]
Should remove the drop they have or else you're gonna have xenobiologists with invisible powers

**Comment by YakumoChen** [comment]
I thought the drop only worked on simple mobs

**Comment by YakumoChen** [comment]
`/obj/item/asteroid/fugu_gland/afterattack(atom/target, mob/user, proximity_flag)
	if(proximity_flag && isanimal(target))
var/mob/living/simple_animal/A = target`
yeah it only works on simple mobs, there's even a banned mob list

**Comment by Armhulen** [comment]
I'll make the verb an action button if this gets merged

**Comment by MoreRobustThanYou** [comment]
flip it to WUMBO

**Review by Cyberboss — APPROVED** [review]

**Pull request merged**
