### PR TITLE
Adds a new full hair gradient, smoothes out the split gradients a tad.

### PR DESCRIPTION
**Pull request by DATA-xPUNGED**
## About The Pull Request

Adds the option to spray your ENTIRE hair, not just a part of it, also makes the splits be less harsh on the transition, being now similar to the short fades
image image

## Why It's Good For The Game

Always puzzled me why you couldn't color your WHOLE hair in-game with a hair spray, now you can! I'm not sure why you would dye your hair fully in the character setup, but that is an option too (maybe your character dyes their hair blonde or something?).
As for the splits, the fact that the gradient was that harsh stopped me from using it before as it looked jarring.
## Changelog
:cl:
add: You can now fully color your hair with a hair spray!
qol: splits hair sprays are now smoother on the transition, similar to the short fades.
/:cl:

### CODE REVIEW

**Review by Wallemations — APPROVED** [review]
image


I mean, yea.

**Review by Ghommie — CHANGES_REQUESTED** [review]
> image
> 
> I mean, yea.

Hold on, why is the vsplit icon state equal for all directions now? Also, can we see how it looks in-game and in the character menu? Hair styles are not particularly wide, and people may want to use the original, harsher contrast in some cases.

On a sidenote, you could add a front/rear version of the vertical split while you're at it, if we don't already have one, but that's not part of the review.

EDIT: Ok, I've checked the .dmi and it shows the new vsplit is monodirectional, while the previous had different states for all four directions. That ought to get fixed.

**Comment by DATA-xPUNGED** [comment]
> > image
> > I mean, yea.
> 
> Hold on, why is the vsplit icon state equal for all directions now? Also, can we see how it looks in-game and in the character menu? Hair styles are not particularly wide, and people may want to use the original, harsher contrast in some cases.
> 
> On a sidenote, you could add a front/rear version of the vertical split while you're at it, if we don't already have one, but that's not part of the review.
> 
> EDIT: Ok, I've checked the .dmi and it shows the new vsplit is monodirectional, while the previous had different states for all four directions. That ought to get fixed.

I don't understand what you mean by front/rear version, but sure i'll fix it

**Comment by EricZilla** [comment]
I like to dye my hair when running clown so this pleases me greatly

**Comment by Ghommie** [comment]
> I don't understand what you mean by front/rear version, but sure i'll fix it

Oh, I just meant a vertical split, but instead of being left / right, it's front / back.

**Review by Ghommie — CHANGES_REQUESTED** [review]
You still have to fix the icon state for the vsplit (try rotating the character preview in the character menu if you don't understand what I mean).

**Comment by Wallemations** [comment]
> Hold on, why is the vsplit icon state equal for all directions now? 

Oh I'm stupid lmaooo

**Review by Ghommie — APPROVED** [review]
Nothing more to say.

**Pull request merged**
