### PR TITLE
Items inspired by Hotline Miami

### PR DESCRIPTION
**Pull request by ghost**
Take 2.

This PR adds weapons, clothing, and a device inspired by the game Hotline Miami. Quite a few weapons are added (although most of these are not currently available without admin intervention), plus a letterman jacket and a phone. The phone will say a random name, location, and instruction; that's just for fun and also to inspire murder sprees in Hotline Miami style.

All items have sprites and inhands. The weapon and phone sprites are taken from WalterJe's sprite thread on the forum; the letterman jacket sprites were by killerfgs on GitHub.

Also adds a new traitor bundle, which contains the following items:
1. A chicken head mask
2. A letterman jacket
3. Classic jeans
4. An emag
5. A random weapon: pocket knife, lead pipe, frying pan, or machete
6. A murderphone
7. A syndicate pistol

Also removed the old unused sledgehammer sprite to make room for the new one.

sprities

### CODE REVIEW

**Comment by Xhuis** [comment]
uhh what

**Comment by SconesC** [comment]
so now shady criminals can have proper gang weapons

radical

**Comment by Jordie0608** [comment]
Changelog
:+1:

**Comment by Xhuis** [comment]
Huh. Could've sworn I had one. No problem, gimme a minute

**Comment by Iamgoofball** [comment]
what happened to the tape recorder setup?

**Comment by Xhuis** [comment]
scrapped it, didn't really like it

**Comment by Chocobro** [comment]
>frying pan

finally my dream of a realistic kitchen is already coming to fruition

**Comment by Jordie0608** [comment]
Sledgehammer should probably be a two-handed weapon.

Other than that, :+1:

**Comment by Xhuis** [comment]
I can easily make it a two-handed weapon

**Comment by Xhuis** [comment]
Update: I tried making it a two-hander (I had sprites and stuff) but byond wasn't willing to cooperate and just threw errors. When I defined it as two-handed, it said that 'wielded' was not defined. When I added a definition for it, it would just say 'duplicate definition'.

**Comment by Xhuis** [comment]
Gonna hold off on fixing the conflicts here due to multiple PRs of mine that will conflict anyway, once those get merged I will fix the stuff on this branch.

**Comment by Man-Shroom** [comment]
Xhuis you have GOT to buff the damage and throwforce on the weapons that are available. Some of these things are less dangerous than a fire extinguisher, AND having them means you are valid, so they should be more powerful. That, or you get two of them/more items are added to the pool. Preferably all three solutions.

**Comment by Xhuis** [comment]
The weapons you can get from the bundle (that's the only way to acquire these) are all good. The machete does high damage and embeds. The knife has a 100% chance of embedding. The frying pan has great damage for a small weapon. Each weapon has an upside to it. I'll being doing more work on this when some of my other things get merged so I'll balance them then.

**Comment by Xhuis** [comment]
Will re-open this when I decide to finish it.

**Pull request closed without merging**
