### PR TITLE
Disc station hotfix

### PR DESCRIPTION
**Pull request by Strathcona**
- Added Ian
- Fixed Theater APC
- Fixed Bar Air Alarm
- Fixed Botany APC
- Fixed Arrivals Camera
- Fixed broken scrubbers
- Fixed turfs in library
- Fixed Janitor Closet access
- Fixed Robotics Charging Bay access
- Fixed Gulag Shuttle
- Fixed Xenobio pen
- Fixed Disposals Stacking
- Fixed a few missing pipes and pipes set to visible
- Fixed Medbay exit button
- Fixed Tech Storage access
- Added AI core turret control
- Added flashes to Robotics
- Added extinguishers, newscasters and intercomms around the station
- Added docking ports for white ship in observation pod northeast of arrivals (holy shit that thing is awkward to fit in)
- Added docking port for ferry just below transit tube main station on starboard arm
- Removed one r-wall from AI core from space
- Added the 2% spawn xenos

### CODE REVIEW

**Comment by WJohn** [comment]
Map meeergeeer!

**Comment by Shadowlight213** [comment]
@Strathcona Did you fix all the wiring issues?
There's a few wires missing from under doors and such.
If you want, I can list off the wiring issues I can recall.
The one I'll mention here is that the emitter wires aren't connected to the SMES outputs, meaning they have no power at round start.

**Comment by Strathcona** [comment]
Feel free to list them. I need to go back and try map merger again anyway.

**Comment by Shadowlight213** [comment]
@Strathcona Alright.
Missing wire locations:
Under west HOP door
Under west Warden door
Under the door that leads to the maint hall where the escape APC is
One tile down and to the left of the arrivals EVA access button
In medbay there's two wires missing along the scrubber pipe 4 tiles above the getmore chocolate vending machine.
The wire under the top airlock for the right side emitters isn't connected to the wire above it.
That's all the wiring issues I see for now. There's still some area issues I think. But those are a bit harder to describe.
If you don't mind, after this hotfix is merged, I can try and fix up the remaining area stuff.

**Comment by Strathcona** [comment]
I got all of those and a few more as well as a few more rouge single tile areas and another few minor areas like port aft solars.

I also map merged again but I also ended up moving the map over 3 tiles to make the white ship fit. I dunno if that explains the horrific linechange count.

**Comment by Jordie0608** [comment]
If you did it after you used the map merger then yes, you'll need to use it again anyway to fix the linediff.

**Comment by Strathcona** [comment]
Oh, who edited discstation? Damn it, these were supposed to be a hotfix.

**Pull request closed without merging**
