### PR TITLE
Fails travis on stacked turfs

### PR DESCRIPTION
**Pull request by ShizCalev**

### CODE REVIEW

**Comment by Cyberboss** [comment]
This is the sort of thing I think we could handle with unit tests, considering dmm_suite knows much more about map structure than a grep

**Comment by lzimann** [comment]
I was thinking in attempting to do a map lint(probably python), so we can move all these checks into an actual script instead of putting all of them together in the travis .sh

**Comment by optimumtact** [comment]
Two people who have only ideas and not working code

one who has working code

JOGS
THE
ALMOND ACTIVATED
NOG

**Comment by Cyberboss** [comment]
I'm just concerned about false negatives/positives. grep seems kind of weak for this job

**Comment by ShizCalev** [comment]
Travis isn't picked it up anyway, it should be failing. :(

**Pull request closed without merging**
