### PR TITLE
Goof has 48 hours to fix the chameleon kit

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
Letting you pick invisible stuff is bad and it's been like half a year now

### CODE REVIEW

**Comment by PKPenguin321** [comment]
@Iamgoofball

**Comment by TechnoAlchemisto** [comment]
Now this is the kind of ultimatum I go onto github to see!

**Comment by optimumtact** [comment]
Sorry but we need to fix the cargo balance before we do this.

**Comment by JJRcop** [comment]
did you write the PR title with magazine clippings, or is it a transcript of a heavily distorted voicemail message?

**Comment by Iamgoofball** [comment]
Invisible stuff is a problem with broken outfits with no sprites, not the kit.

**Comment by Iamgoofball** [comment]
Also you know NO ONE TELLS ME THESE THINGS

TRY MAKING BUG REPORTS

OR LISTING BROKEN ITEM NAMES

**Comment by KorPhaeron** [comment]
Abstract items are not broken, being able to choose them is

**Comment by Iamgoofball** [comment]
This is an easy fix and you should of said this in the OP

**Comment by Bawhoppen** [comment]
:clock1:

**Comment by GeneralGoose** [comment]
ＴＩＭＥ ＩＳ ＲＵＮＮＩＮＧ ＯＵＴ
ＭＡＫＥ Ａ ＭＯＶＥ

**Comment by Bawhoppen** [comment]
:clock2:

**Comment by Iamgoofball** [comment]
So are these items marked as abstract via flags or specific items? I need to know this to fix

**Comment by Bawhoppen** [comment]
:clock3:

**Comment by GunHog** [comment]
@Iamgoofball Try checking for both the ABSTRACT flag, and its icons. If it is ABSTRACT or lacks an on-mob or held icon, then do not include it in the choice list.

**Comment by Bawhoppen** [comment]
:clock4:

**Comment by ExcessiveUseOfCobblestone** [comment]
Are you saying I shouldn't be allowed to murderbone as a nudist?

**Comment by KorPhaeron** [comment]
@ExcessiveUseOfCobblestone 

I mostly care about abusing an invisible voice changer or scanning an invisible item with a chameleon projector

**Comment by kevinz000** [comment]
@KorPhaeron is hating on them because I used a cigarette as a stealthop in warops.

**Comment by Iamgoofball** [comment]
https://github.com/tgstation/tgstation/pull/19857
https://github.com/tgstation/tgstation/pull/19857
https://github.com/tgstation/tgstation/pull/19857
https://github.com/tgstation/tgstation/pull/19857
https://github.com/tgstation/tgstation/pull/19857
https://github.com/tgstation/tgstation/pull/19857
https://github.com/tgstation/tgstation/pull/19857
https://github.com/tgstation/tgstation/pull/19857
https://github.com/tgstation/tgstation/pull/19857
https://github.com/tgstation/tgstation/pull/19857
https://github.com/tgstation/tgstation/pull/19857
https://github.com/tgstation/tgstation/pull/19857
https://github.com/tgstation/tgstation/pull/19857
https://github.com/tgstation/tgstation/pull/19857
https://github.com/tgstation/tgstation/pull/19857
https://github.com/tgstation/tgstation/pull/19857
https://github.com/tgstation/tgstation/pull/19857
https://github.com/tgstation/tgstation/pull/19857
https://github.com/tgstation/tgstation/pull/19857
https://github.com/tgstation/tgstation/pull/19857
https://github.com/tgstation/tgstation/pull/19857
https://github.com/tgstation/tgstation/pull/19857
https://github.com/tgstation/tgstation/pull/19857
https://github.com/tgstation/tgstation/pull/19857
https://github.com/tgstation/tgstation/pull/19857
https://github.com/tgstation/tgstation/pull/19857
https://github.com/tgstation/tgstation/pull/19857
https://github.com/tgstation/tgstation/pull/19857
https://github.com/tgstation/tgstation/pull/19857
https://github.com/tgstation/tgstation/pull/19857
https://github.com/tgstation/tgstation/pull/19857
https://github.com/tgstation/tgstation/pull/19857
https://github.com/tgstation/tgstation/pull/19857
https://github.com/tgstation/tgstation/pull/19857
https://github.com/tgstation/tgstation/pull/19857
https://github.com/tgstation/tgstation/pull/19857
https://github.com/tgstation/tgstation/pull/19857
https://github.com/tgstation/tgstation/pull/19857
https://github.com/tgstation/tgstation/pull/19857
https://github.com/tgstation/tgstation/pull/19857
https://github.com/tgstation/tgstation/pull/19857
https://github.com/tgstation/tgstation/pull/19857
https://github.com/tgstation/tgstation/pull/19857
https://github.com/tgstation/tgstation/pull/19857
https://github.com/tgstation/tgstation/pull/19857
https://github.com/tgstation/tgstation/pull/19857
https://github.com/tgstation/tgstation/pull/19857
https://github.com/tgstation/tgstation/pull/19857
https://github.com/tgstation/tgstation/pull/19857
https://github.com/tgstation/tgstation/pull/19857
https://github.com/tgstation/tgstation/pull/19857
https://github.com/tgstation/tgstation/pull/19857
https://github.com/tgstation/tgstation/pull/19857
https://github.com/tgstation/tgstation/pull/19857
https://github.com/tgstation/tgstation/pull/19857
https://github.com/tgstation/tgstation/pull/19857
https://github.com/tgstation/tgstation/pull/19857
https://github.com/tgstation/tgstation/pull/19857
https://github.com/tgstation/tgstation/pull/19857
https://github.com/tgstation/tgstation/pull/19857
https://github.com/tgstation/tgstation/pull/19857
https://github.com/tgstation/tgstation/pull/19857
https://github.com/tgstation/tgstation/pull/19857
https://github.com/tgstation/tgstation/pull/19857
https://github.com/tgstation/tgstation/pull/19857
https://github.com/tgstation/tgstation/pull/19857
https://github.com/tgstation/tgstation/pull/19857
https://github.com/tgstation/tgstation/pull/19857
https://github.com/tgstation/tgstation/pull/19857
https://github.com/tgstation/tgstation/pull/19857
https://github.com/tgstation/tgstation/pull/19857
https://github.com/tgstation/tgstation/pull/19857
https://github.com/tgstation/tgstation/pull/19857
https://github.com/tgstation/tgstation/pull/19857
https://github.com/tgstation/tgstation/pull/19857
https://github.com/tgstation/tgstation/pull/19857
https://github.com/tgstation/tgstation/pull/19857
https://github.com/tgstation/tgstation/pull/19857
https://github.com/tgstation/tgstation/pull/19857
https://github.com/tgstation/tgstation/pull/19857
https://github.com/tgstation/tgstation/pull/19857
https://github.com/tgstation/tgstation/pull/19857
https://github.com/tgstation/tgstation/pull/19857
https://github.com/tgstation/tgstation/pull/19857
https://github.com/tgstation/tgstation/pull/19857
https://github.com/tgstation/tgstation/pull/19857
https://github.com/tgstation/tgstation/pull/19857
https://github.com/tgstation/tgstation/pull/19857
https://github.com/tgstation/tgstation/pull/19857
https://github.com/tgstation/tgstation/pull/19857
https://github.com/tgstation/tgstation/pull/19857
https://github.com/tgstation/tgstation/pull/19857
https://github.com/tgstation/tgstation/pull/19857
https://github.com/tgstation/tgstation/pull/19857
https://github.com/tgstation/tgstation/pull/19857
https://github.com/tgstation/tgstation/pull/19857

**Pull request closed without merging**
