### PR TITLE
New uplink item: Unholy Water

### PR DESCRIPTION
**Pull request by coiax**
:cl: coiax
add: Syndicate agents have obtained a new toxin that overwhelms the
victim's speech centres with visions of dark gods and impending doom.
add: Adds Unholy Water flask to uplink for 2 TC. All the fun of mute
toxin while spooking everyone else!
/:cl:

Metabreaker traitor item, you know, if you feel like it. Can be used as
a mute in a pinch, although they'll still cry for help.

### CODE REVIEW

**Comment by RemieRichards** [comment]
image

**Comment by kevinz000** [comment]
I'd actually recommend putting this at more units as 100 runs out fast. This isn't that strong if you think about it, if someone screams while cultslurring everyone will swarm their location.
ALSO IMPENDING ROOM
Also, metabreakers are good.

**Comment by coiax** [comment]
I just really don't get what people like sometimes.

**Comment by FantasticFwoosh** [comment]
Add it as a component for hell ramen (which already exists)

**Comment by kevinz000** [comment]
@coiax I like this because it's 1. a metabreaking item that doesn't interfere with admins 2. unique and interesting 3. has more use than KILL KILL KILL.

**Comment by Haevacht** [comment]
How fast is this metabolised? Could you forcefeed to leave someone a gibbering mess for minutes?

**Comment by coiax** [comment]
It's metabolised at the standard rate, which I think is 0.4 units a tick. Which means one 100u bottle is worth 250 ticks. Giving someone a 50u pill would leave them cultslurring for at least 125 ticks, which is like 3-4 minutes?

**Comment by Robustin** [comment]
Unholy water doesn't give visions though... does it?

**Comment by coiax** [comment]
Look, I don't know why people who drink it go "GLGUghglglGHG IT COMES gflglglglg NO HOPE" but I assume it's terrifying visions.

**Comment by Haevacht** [comment]
Neat, I'll fuck around with it on a local for application methods, because muting smoke grenade.

**Comment by scoopscoop** [comment]
This is going to be a bit confusing, as cult already has a flask of unholy water that's a fuel subtype, except theirs has effects on health.

I mean they both have nearly the same name save for an underscore

**Comment by Cheridan** [comment]
i don't really like all the spooky cult shit that used to be contained in its own mode bleeding into other modes. secret agents running around with devil juice is incredibly off theme

**Comment by coiax** [comment]
@scoopscoop can you come up with a better name? I couldn't think of anything, except maybe "Diluted Unholy Water",and that was a bit of a mouthful.

**Comment by KorPhaeron** [comment]
I agree with Cheridan

**Comment by coiax** [comment]
:/

**Comment by scoopscoop** [comment]
Maybe label it as some kind of MKULTRA type drug. We already have mindbreaker and space drugs though...no idea what to call it.

**Comment by KorPhaeron** [comment]
Also the idea of adding metabreaker to confuse people over something that was explicitly added as a meta tell is kind of silly

**Comment by XDTM** [comment]
Why do we have meta tells in modes that are played around stealth and paranoia tho

**Comment by KorPhaeron** [comment]
@Robustin added it as a way to balance the stun paper being so absolutely silent and idiot proof

**Comment by KorPhaeron** [comment]
No other maintainers have come along to save this yet sorry

**Comment by coiax** [comment]
:(

**Pull request closed without merging**
