### PR TITLE
More clockcult tweaks [oranges This Isn't Stale Edition]

### PR DESCRIPTION
**Pull request by ChangelingRain**
🆑 Joan
balance: Sentinel's Compromise now uses Vitality to heal, and healing done without enough Vitality will be much less effective, converting 75% of the damage healed to toxin damage.
tweak: Vitality is now tracked in the global alert.
balance: Vanguard now lasts for 25 seconds, from 20, and no longer stuns for double the time if a large amount of stuns were absorbed.
bugfix: Fixes Vanguard never stunning for more than 2 seconds.
balance: All cyborg Servants now have a cyborg fabricator, a ratvarian spear, and a normal, not-limited slab that has two cyborg-unique scriptures bound.
balance: Cyborg Servants can no longer bolt and unbolt airlocks.
balance: Cyborg Servants are unable to recite several scriptures; Judicial Visor, Vanguard, Sigil of Submission, Integration Cog, Wraith Spectacles, Replica Fabricator, and Clockwork Arnaments[sic].
wip: Of those, only Sigil of Submission is removed for balance reasons; the rest are either unusable by the cyborg or have a replacement scripture or tool.
/🆑

@KorPhaeron @Xhuis I did figure out a solution to borgs being a one-way trip to the AI, and that solution is keeping them from bolting and unbolting airlocks, which means, as a way to get to the AI, they're much less effective.

### CODE REVIEW

**Comment by CPTANT** [comment]
An engineering borg will still just RCD the reinforced wall and walk straight into the core.

**Comment by ChangelingRain** [comment]
Blame kor for that #29235

**Comment by CPTANT** [comment]
Meh that should have been merged.

Engineering borg RCD just instant deleting reinforced walls just makes keeping them out of anywhere impossible. And it's not like they can't deconstruct Rwalls the regular way.

**Comment by Xhuis** [comment]
Servant borgs' inability to unbolt airlocks is a good solution, but it runs the risk of falling into the "non-obvious mechanics" trap that so much of clockcult already does. As for the rest of the PR being merged, I maintain that it isn't necessary, although the cyborg changes are good overall.

As always, the choice falls to Kor here.

**Comment by YakumoChen** [comment]
RCDing rwalls isn't even a problem if you can just RCD the doors, or even easier still, just hack them.

**Comment by Anonmare** [comment]
At least RCDing the doors requires running through the motion alarms and past the flashers. Most maps also have shutters on the main airlock (which can be depowered and crowbarred but it can still slow them down). Slow them down enough to get a warning out or, if all else fails, buy time to suicide.

Perhaps I ought to make a strawpoll and see about re-opening  #29235 with a "player vote to see if it's really what the community wants"

**Comment by Arianya** [comment]
Would it be unreasonable to change #29235 to specifically remove r-wall capability from culted cyborgs? It's not an outright nerf for nerf's sake since cult borgs are getting several new tools per this PR, and it makes some sense that the old-fashioned brass nerd degrades some high tech gear in the process.

Though per @Xhuis, we'd probably want some method of advising the borg of this change to his RCD and his bolt capability. The RCD could probably be modified in some obvious wasy (brass RCD with a description alluding to its reduced capability). Not sure how you'd make the bolt loss obvious other then a addition to their on conversion message which is bleh. Maybe a error message when they try to bolt/unbolt along the lines of:

> %%AUTHENTICATION INVALID##GREAT314ENGINE4NOT20RECOGNIZED&&CYBORGNOTRECOGNIZED

except less awful

**Comment by ChangelingRain** [comment]
I'm actually somewhat tempted to remove deconstruct as an option from the borg RCD entirely, since it makes engiborgs so much more powerful than is reasonable in a lot of other situations, and they already have tools to decon stuff.

**Comment by Anonmare** [comment]
The downside to that is that emagged airlocks will be impossible to repair for them since they *require* an RCD to be fixed

**Comment by ChangelingRain** [comment]
Emagged airlocks can be repaired by replacing the electronics, so you don't technically have to RCD the entire door.
However, #30464, which should have given them the ability to repair emagged airlockss in that manner, did not actually include airlocks, so they can't as of yet.

**Comment by Iamgoofball** [comment]
@KorPhaeron 
This PR should be closed on the grounds that the OP abused their powers to destroy the competing coders with different ideas on a rework.

I would rather ask Xhuis to redo his base defense PR or just remove CC entirely again.

**Comment by ChangelingRain** [comment]
I have a counterargument. 
[This is the counterargument.](https://github.com/tgstation/tgstation/pull/29741)

**Comment by Bawhoppen** [comment]
wtf is this drama even about

**Comment by SgtxRootbeer** [comment]
and the post-blorble-now-kat-thingy has won.
#29741

**Comment by Iamgoofball** [comment]
@optimumtact 
Considering the game mode just got completely revamped entirely this PR is obsolete

**Comment by ChangelingRain** [comment]
Incorrect, but funny.

**Comment by Iamgoofball** [comment]
You're a lying sack of shit who sabotaged PRs with your powers.

Why the fuck would anyone trust you?

**Comment by KorPhaeron** [comment]
>Servant borgs' inability to unbolt airlocks is a good solution

@Xhuis 

Do you still believe this/like the rest of the changes here

**Comment by Xhuis** [comment]
I think the borgs' airlock-bolting ability isn't nearly as relevant anymore because converting the AI doesn't give you access to a more secure base; only an AI that can change things stationside but can't do anything on Reebe.

I think the rest are either unnecessary or irrelevant with the new clockcult, and because they were developed with the oldcult in mind I don't think they should still try to get into the new one without some time for it to play out and see what needs changing in the new iteration.

**Comment by KorPhaeron** [comment]
I think this (or something like it) will eventually be needed because hacking the AI is such a big deal in any mode since it can trash the station on its own, but everyone seems pretty happy with the mode right now so if you want I guess we can see how it plays out for a little while and revisit it later

**Pull request closed without merging**
