### PR TITLE
Fixes note/message interface flooding the string tree.

### PR DESCRIPTION
**Pull request by MrsTonedOne**

### CODE REVIEW

**Comment by SpaceManiac** [comment]
```
code/modules/admin/sql_message_system.dm:306:warning: output: unused label
code/modules/admin/sql_message_system.dm:306:warning: Join: unused label
```
???

**Comment by Jordie0608** [comment]
Technically this is much more performant because you can't reach the all button now.
capture2

**Review by Cyberboss — DISMISSED** [review]
I believe we can't name the var `output` anymore

**Comment by Jordie0608** [comment]
Tested with 33k rows, hung my DD for only a few seconds as opposed to ~30 or so previously.

**Review by SpaceManiac — APPROVED** [review]
works on ~~my~~ jordie's machine

**Pull request merged**
