### PR TITLE
Changes venus human trap's sprites

### PR DESCRIPTION
**Pull request by TehZombehz**
Changes the venus human trap's sprites. At the very least, they are
different.
venustrap

### CODE REVIEW

**Comment by RemieRichards** [comment]
Keeps the theme I was going for but with a nicer sprite, definite :+1:

**Comment by Iamgoofball** [comment]
# PILLOW SHADING

**Comment by TehZombehz** [comment]
@Iamgoofball 
>Implying you care
>At the very least, they are different.

**Comment by newfren** [comment]
p i l l o w s h a d i n g
i
l
l
o
w
s
h
a
d
i
n
g

**Comment by Cheridan** [comment]
its not perfect but it's **_better_**

**Comment by KorPhaeron** [comment]
༼ つ ◕_◕ ༽つ

**Pull request merged**
