### PR TITLE
Remove efficiency station

### PR DESCRIPTION
**Pull request by optimumtact**
Unmaintained and unliked, there are better options

### CODE REVIEW

**Comment by Keekenox** [comment]
YES

**Comment by Iamgoofball** [comment]
Inb4 wj close

**Comment by dannno** [comment]
isn't this version of efficiency basically just allura's work though

**Comment by Kromgar** [comment]
FUCKING YES

**Comment by Firecage** [comment]
This is one of the good stations though

**Comment by peoplearestrange** [comment]
Again why remove? Just remove the map from the rotation list. There are others downstream

**Comment by Cheridan** [comment]
We don't need a bunch of mothballed maps, any path changes need to be mirrored on any maps or else they'll fail travis

**Comment by WJohn** [comment]
As the creator of this map, thank you for removing it.

**Pull request merged**
