### PR TITLE
Lets prisoners be most antag types

### PR DESCRIPTION
**Pull request by ATH1909**
## About The Pull Request

Prisoners can now be traitors, cultists, changelings, and monkey fever patient zeroes without needing to be converted. They still can't be revheads (without being converted first), blood brothers, or devils, though.

Prisoners can no longer be chosen to be revheads midway through the round on dynamic mode.

The command reports for the cult and changeling gamemodes have been slightly updated for further clarity.

I also added Wardens to the enemy_roles list of dynamic mode midround wizards, but I'm not sure that that even does anything, seeing as how both normal wizards and dynamic mode roundstart wizards don't seem to use that enemy_roles list

## Why It's Good For The Game

It's kind of dumb that a prisoner is (mechanically) more likely to be trustworthy than a head of staff.

Traitor prisoners can break out of prison using emags, syndicate space suit kits, c4, chameleon kits, etc.

Cultists can break out of prison using Twisted Construction, a teleport rune (or Teleport spell), or a Summon Cultist rune.

Changelings can break out of prison using Lesser Form (monkeys can ventcrawl), organic space suits, and I think their armblades, IIRC.

Monkey fever patient zeroes can just ventcrawl out of prison.

Head revs don't get any special equipment to break out of prison with, and they can't exactly flash very many people from within prison. Also, it'd be kinda lame if the round suddenly ended because a headrev fucked up their suit-less spacewalk prison escape attempt.

Blood brothers don't get any special equipment either, and if a blood brother team gets unlucky enough, both members (or even all three members!) of the blood brother team could be prisoners. Even if one member of a pair of blood brothers is a prisoner and the other isn't, the prisoner could commit suicide out of boredom before his blood brother gets to him. Furthermore, the non-prisoner blood brother gets ganked, the prisoner blood brother could be stuck waiting in prison for a rescue that will never come.

I think devil prisoners can technically break out by spamming hellfire on the doors to Perma (since hellfire projectiles have a base brute damage of 10), but that would be really noisy and really slow/tedious to do. While I do like the idea of a devil prisoner making a deal with a sec officer so that they can be let out of prison, there's no guarantee that sec will even interact with said devil prisoner or won't just validhunt them as soon as they display infernal powers.

The cult command report didn't make it clear that mindshielding a cultist DOESN'T deconvert them, so I made a slight modification to it to fix that. The changeling command report also implied that there was only one changeling on the station, so I slightly modified that command report as well.

While making this PR, I noticed that sec officers, HoSes, and even detectives were on the enemy_roles list of midround wizards, but not wardens, so I assumed that wardens not being on that list was an oversight.

## Changelog
:cl: ATHATH
balance: Prisoners can now be traitors, cultists (without needing to be converted), changelings, and monkey fever patient zeroes.
fix: Prisoners can no longer be midround revheads on dynamic.
tweak: Slightly modified the cult and changeling command reports for extra clarity.
/:cl:

### CODE REVIEW

**Comment by ATH1909** [comment]
... what the fuck? why has appveyor gone ballistic?

**Comment by ATH1909** [comment]
Ah, I found the problem.

**Comment by 81Denton** [comment]
Do you have other arguments that prisoners should be able to roll antag other than "I think it's dumb"? In the original PR, @Cyberboss requested that they should be excluded from antag roles after all.

**Comment by SkeletalElite** [comment]
> Do you have other arguments why prisoners should be able to roll antag other than "I think it's dumb"? In the original PR, @Cyberboss requested that they should be excluded from antag roles after all.

I think the fact that they are mechanically more trustworthy than a head of staff who isn't the HoS or Captain is a good enough reason. Its legitimately safer bet to give the prisoners guns than it is to give to anyone else who isn't sec/cap. It doesn't make any sense.

**Comment by Cyberboss** [comment]
This is why I said prisoners need to become fugitives with an escape
greentext when released

**Comment by Iamgoofball** [comment]
@81Denton Yeah, what SkeletalElite said, I've observed players deputizing the Prisoner(s) while keeping an eye on Families testmerges since they know that the prisoner isn't a gangster by default and can be mindshielded. It's basically turned into an extra security slot.

**Comment by Iamgoofball** [comment]
HOWEVER, please keep gangster or undercover cop rolling excluded from Prisoner still bc the mode stagnates balance wise if one of the gangs can't try to recruit(a three way gang war plays way better than a two way gang war in my eyes).

**Comment by Cyberboss** [comment]
Station also needs a greentext for keeping prisoners in confinement

**Comment by Arianya** [comment]
The fact is that a prisoner shouldn't get antagonist because they already lost. We treat being perma'd as death for the purposes of most antagonists. To say "The Syndicate recruited someone who's already in jail as a sleeper agent!" is pretty silly.

If the Prisoner is getting treated as a soft safe pick then that's an issue with the crew's motivations in relation to the Prisoner, which can be fixed by what Cyberboss said - give Security/the Warden/The Station as A Whole a objective to keep the Prisoner imprisoned.

Doing something like this is just liable to get the role policy'd into being unappealing because administrators can't expect security to reasonably take it easy on Prisoners when there's a very real possibility they're an antagonist, let alone giving the prisoner an uplink/changeling powers/etc.

About the only antagonist I could see this maybe being reasonable on is bloodbros, and even then I think it'd be better to defer to Cyberboss' view.

**Comment by SkeletalElite** [comment]
> Doing something like this is just liable to get the role policy'd into being unappealing because administrators can't expect security to reasonably take it easy on Prisoners when there's a very real possibility they're an antagonist, let alone giving the prisoner an uplink/changeling powers/etc.

Good, security shouldn't be taking it easy on prisoners, they're prisoners, in prison. If security is killing the prisoners fnr they should be banned for grief like any other person. Unreasonably fortifying perma should be treated the same as making atmos AI proof round start/hiding the entire armory fnr.

**Comment by Arianya** [comment]
> > Doing something like this is just liable to get the role policy'd into being unappealing because administrators can't expect security to reasonably take it easy on Prisoners when there's a very real possibility they're an antagonist, let alone giving the prisoner an uplink/changeling powers/etc.
> 
> Good, security shouldn't be taking it easy on prisoners, they're prisoners, in prison. If security is killing the prisoners fnr they should be banned for grief like any other person. Unreasonably fortifying perma should be treated the same as making atmos AI proof round start/hiding the entire armory fnr.

This is all well and good in the abstract, but you have to realize the outlook from the administrative side when a prisoner ahelps getting killed, and security has a not-implausible argument for killing them. At this point you're either forced to rule against the security officer and irritate them into not playing security, or irritate the prisoner and they stop playing the prisoner role. Neither is ideal.

Also that's without getting into the fact that the prisoner is in a camera'd up area from roundstart - they can hardly do anything without being caught by Security or the AI - meaning that the "optimal" strat for antagonist prisoners would be to rush an escape or security, depending on their role.

**Comment by SkeletalElite** [comment]
> This is all well and good in the abstract, but you have to realize the outlook from the administrative side when a prisoner ahelps getting killed, and security has a not-implausible argument for killing them. At this point you're either forced to rule against the security officer and irritate them into not playing security, or irritate the prisoner and they stop playing the prisoner role. Neither is ideal.

I don't see how this is any different from security killing literally anyone else who ahelps. Rule 10 exists, sometimes you die and that's part of the game. It's not like security has a free pass to valid all prisoners round start on the off-chance they're an antag. I also think you're overestimating how much the AI/sec keeps an eye on them and they have plenty of chance to escape. I can't speak for other people but as warden/sec/AI I do not keep an eye on the prisoners at all times. Usually as warden my focus is to keep the armory safe more than anything else. As an AI the only time I even bother with prisoners is if they law 2 me using paper on cameras.

**Comment by Arianya** [comment]
> I don't see how this is any different from security killing literally anyone else who ahelps. Rule 10 exists, sometimes you die and that's part of the game. It's not like security has a free pass to valid all prisoners round start on the off-chance they're an antag. I also think you're overestimating how much the AI/sec keeps an eye on them and they have plenty of chance to escape. I can't speak for other people but as warden/sec/AI I do not keep an eye on the prisoners at all times. Usually as warden my focus is to keep the armory safe more than anything else. As an AI the only time I even bother with prisoners is if they law 2 me using paper on cameras.

The point is this is a role with near-100% chance of having to interact with Security. One search because the prisoner is somewhere they shouldn't be, or one AI glance at the prison, is enough to basically leave a confirmed antagonist already in a failure state, rather then having the possibility of escaping while in transit/getting caught up in other confusion/etc. You're literal feet from the "transfer centre". It's not a good idea to give this role a chance to be antagonist since it will only end with a general outcome of 1) antagonist prisoner decimates security near roundstart because they have to to "win" or 2) security catches antagonist prisoner and puts them down for good. 

Neither is good for the respective roles. And this is a case of taking a nuclear-powered hammer to fix a small nail.

**Comment by ATH1909** [comment]
> HOWEVER, please keep gangster or undercover cop rolling excluded from Prisoner still bc the mode stagnates balance wise if one of the gangs can't try to recruit(a three way gang war plays way better than a two way gang war in my eyes).

Yep, prisoners still won't be able to roll roundstart gangster.

> Also that's without getting into the fact that the prisoner is in a camera'd up area from roundstart - they can hardly do anything without being caught by Security or the AI - meaning that the "optimal" strat for antagonist prisoners would be to rush an escape or security, depending on their role.

just smash the cameras 4head

**Comment by ATH1909** [comment]
> To say "The Syndicate recruited someone who's already in jail as a sleeper agent!" is pretty silly.

Perhaps the Syndicate just hid uplinks inside of cakes?

**Comment by ATH1909** [comment]
> Do you have other arguments why prisoners should be able to roll antag other than "I think it's dumb"? In the original PR, @Cyberboss requested that they should be excluded from antag roles after all.

I do, but SkeletalElite has explained them all much better than I ever could.

**Comment by lordpidey** [comment]
>I think devil prisoners can technically break out by spamming hellfire on the doors to Perma

Devils get a jaunt at 3 souls.  If they can make their way to 3 souls they can escape.

**Comment by RaveRadbury** [comment]
@itseasytosee It might be time to implement the detain+breakout objectives as non-admeme only

**Comment by Victor239** [comment]
It also incentivises choosing combat-heavy spending for whatever antag role you get, so very quickly security is going get wary enough of prisoners with carp/desword/armblade and fortify perma to extreme levels to ensure prisoners can't easily escape or interact with any outsiders.

**Comment by AdamElTablawy** [comment]
If they can spawn as an antagonist, then as a traitor they should spawn with 0 TC. I don't like the idea of ling prisoners, lings eat a person before they get to the station and arrive wearing their skin. Why would they have eaten a random convict?

Like, if you are signing up as a prisoner, you have already decided that you will likely be spending your whole round in Perma. If you roll antag prisoner, you should also be up shit creek and have to make your own paddle to get out.

**Comment by Fikou** [comment]
> I don't like the idea of ling prisoners, lings eat a person before they get to the station and arrive wearing their skin. Why would they have eaten a random convict?

as a strategic way to get into a place with another guy that won't ever scream and having very close access to security

**Comment by necromanceranne** [comment]
I would prefer if prisoners couldn't beeline into security fully equipped with an emag while security is still gearing and there is quite literally nothing else worth doing as a prisoner as likely all your objectives are outside.

**Comment by wesoda25** [comment]
Like adam said, traitors shouldn’t get an uplink, and have special objectives that tell them to escape, and maybe certain assassination objectives. Making prisoners blood brothers would also work really well, with a similar escape objective. Blood cultists would work well, lings might be a bit op.

**Comment by ExcessiveUseOfCobblestone** [comment]
Prisoners being unable to receive antag was a stipulation for their addition, not to mention this will ruin the current dynamic.

If you don't plan on doing what Cyberboss has suggested, I would rather the metagame of "let them help out they can't be antags" exist instead of every round they have to act in a particular way because someone is doing a prisoner emag any% speedrun.

**Comment by ATH1909** [comment]
> Like adam said, traitors shouldn’t get an uplink, and have special objectives that tell them to escape, and maybe certain assassination objectives. Making prisoners blood brothers would also work really well, with a similar escape objective. Blood cultists would work well, lings might be a bit op.

I literally explained in the opening post why prisoners being eligible to become blood brothers would be cancerous.



> Prisoners being unable to receive antag was a stipulation for their addition, not to mention this will ruin the current dynamic.
> 
> If you don't plan on doing what Cyberboss has suggested, I would rather the metagame of "let them help out they can't be antags" exist instead of every round they have to act in a particular way because someone is doing a prisoner emag any% speedrun.

Alright, fine, I'll close this PR, then.

**Comment by Bokkiewokkie** [comment]
Even though this is closed I still wanted to add that prisoners don't spawn with an uplink in their possesion already, because they don't have a pda or headset. I've had a few rounds on dynamic (before it was fixed) where I rolled traitor prisoner and my uplink was just a random pen in maintenance somewhere.

**Pull request closed without merging**
