### PR TITLE
Organs are stored inside mobs

### LINKED ISSUE #26426: Organs are stored in nullspace
This is just dumb.

### PR DESCRIPTION
**Pull request by Cyberboss**
This needs to be finished. Help would be appreciated.

Fixes #26426.

#### Bugs
- [ ] Roundstart AI spawns are a pile of organs
- [ ] Roundstart borg spawns are a pile of organs
- [ ] Nuke ops spawning seem to leave behind tongues of their original race
- [ ] Someone died after being turned into a monkey?

### CODE REVIEW

**Comment by Cyberboss** [comment]
Passive aggressive @tgstation-server

**Comment by Supermichael777** [comment]
roundstart borgs steal a brain from a mob  you can tell by the name on the brain

**Comment by Fox-McCloud** [comment]
I don't see what's so bad about this, to be honest.

As far as I know, aren't components for machines also stored in nullspace?

As long as all references are cleared and they're stored in some list *somewhere*, this doesn't seem to be something that explicitly has to be done.

**Comment by lzimann** [comment]
i think this has been tried twice(?) already, and it's not that much of an issue not being in the mob tbh

**Comment by Cyberboss** [comment]
There's a bunch of functionality people want to add to organs that relies on them being located inside the mob. I'd rather those not all use several different kinds of hacks

**Comment by RemieRichards** [comment]
What functionality, give examples.
I literally can't think of any, at all.

organs are accessible from the mob via ```mob.internal_organs```, and the mob is accessible via organs using ```owner```, both references required are there, they don't need to be in mobs at all.

**Comment by Fox-McCloud** [comment]
Not only that, but there's also `getorgan` and `getorganslot` which makes accessing it *even* more convenient

**Comment by Cyberboss** [comment]
@RemieRichards glowing organs for example. Also, a downstream wanted to do storage in organs which wouldn't work with failing Adjacency checks

**Comment by RemieRichards** [comment]
@Cyberboss You have the organ modify the mob on Add and Remove, you allow the adjacency to be skipped.

Use some creativity, this is going to cause far more problems than good.

**Comment by Fox-McCloud** [comment]
@Cyberboss 

I'll echo what Remie has said. Paradise stands in the unique position of being an originally Baystation codebase that has migrated *very strongly* towards TG. 

Baystation store its organs in the mob instead of null space, and I can tell you the amount of problems it caused was astronomically high when organs went from being datums to an actual object.

**Comment by tortellinitony** [comment]
I figured out how to fix the silicon issues, but one still stands that is very confusing: if you spawn a human, they will drop duplicate organs (not ones inside of the head, but stomach, liver, etc.)

**Comment by Cyberboss** [comment]
Opinion from maintainers is against so

**Pull request closed without merging**
