### PR TITLE
RCLs can no longer go inside you

### LINKED ISSUE #29616: Rapid Cable Layer ended up INSIDE the CE
yes
notice the entry on the very bottom

He said in ahelps that this happened when he went to put more wire into it

### PR DESCRIPTION
**Pull request by ghost**
:cl: More Robust Than You
fix: RCLs can no longer go inside you
/:cl:

Fixes #29616

### CODE REVIEW

**Comment by bgobandit** [comment]
fix the title before this gets closed

**Comment by PKPenguin321** [comment]
OwO

**Comment by qbmax32** [comment]
hot

**Comment by deathride58** [comment]
The evil seed of what you've done germinates within you.

**Comment by Anonmare** [comment]
Was it not your sin that killed the Unicorn

**Comment by alexkar598** [comment]
All of this pr description for 3 characters of changed code

**Comment by OneOneThreeEight** [comment]
The burning you feel?

It is shame.

**Comment by Cyberboss** [comment]
Banned for ERP

**Review by Cyberboss — APPROVED** [review]

**Pull request merged**
