### PR TITLE
Adds noir ambiance to the detective's office

### PR DESCRIPTION
**Pull request by TrustyGun**
"It was only 15 minutes since the start of the shift, yet I could already hear trouble over the radio..."

### CODE REVIEW

**Comment by Bawhoppen** [comment]
link to the soundfile?

**Comment by lzimann** [comment]
:+1:

**Comment by TrustyGun** [comment]
I took it from [this video](https://www.youtube.com/watch?v=uwvVhXItl1w) because I couldn't find any noir.

**Comment by kingofkosmos** [comment]
2.36 MB is quite a big file.

**Comment by duncathan** [comment]
What's the license?

**Comment by WJohn** [comment]
Yeah that's a bit big for a sound file. See if you can't shrink it a bit and keep the quality up.

**Comment by TrustyGun** [comment]
I changed the sound file to a [different song. It's under CC BY-NC-ND](http://freemusicarchive.org/music/Studio_Noir/Sunset_Boulevard/Studio_Noir_-_Sunset_Boulevard_-_16_Isadora_Duncan), and is still rather large (1.336 mb), but it is at least lower.

**Comment by tkdrg** [comment]
Correct me if I'm wrong, but I think NC-ND is incompatible with out license. I believe that as far as creative commons go, we can only accept either CC BY or CC BY-SA (plus of course public domain and other more liberal licenses).

**Comment by TrustyGun** [comment]
Here are the new ambiance sounds. They are both CC BY.

[ambidet1.ogg](https://www.dropbox.com/s/nuqiofro53fjuyc/ambidet1.ogg?dl=0) ("Dances and Dames" by Kevin MacLeod)

[ambidet2.ogg](https://www.dropbox.com/s/0pdx1opaehp0k9a/ambidet2.ogg?dl=0) ("Night on the Docks - Sax" by Kevin MacLeod)

**Comment by tkdrg** [comment]
Looks good to me. Not completely sure if it's worth adding 1.5mb to our rsc just for the det's office, but eeh not that big of a deal imo.

**Comment by duncathan** [comment]
D: I liked those ones what happened

**Comment by TrustyGun** [comment]
It didn't work for some reason. Maybe I'll try some other time?

**Pull request closed without merging**
