### PR TITLE
Adds Renault to Box and Pubby

### PR DESCRIPTION
**Pull request by Cyberboss**
:cl: Cyberboss
add: Renault can now be found on Boxstation and Pubbystation
/:cl:

### CODE REVIEW

**Comment by Cheridan** [comment]
killing the fox adds 5 seconds to my roundstart captain routine, please don't nerf me

**Comment by RemieRichards** [comment]
@Cheridan simple: don't kill the fox

**Comment by Mark9013100** [comment]
solution: devise new strats to kill the fox

**Comment by lzimann** [comment]
less pets

**Comment by RemieRichards** [comment]
less of you

**Comment by Fox-McCloud** [comment]
👍 

This was supposed to be added, what? Literally 2 years ago?

**Comment by Shadowlight213** [comment]
@Cheridan the solution is obviously to add button to the captain's desk that kills the fox.
Bam. Extra time cut down to about 1 second.

**Comment by Armhulen** [comment]
@Shadowlight213 :+1:

**Comment by optimumtact** [comment]
Stupid foxes

**Pull request closed without merging**
