### PR TITLE
Monkey Head-revs can now properly convert people, you can now convert player-monkeys to rev

### LINKED ISSUE #40836: monkey headrevs cant convert people
this is so sad

i might have made an issue for this in the past but i cant recall if i did and just remembered about this issue now. headrevs probably cant convert monkeys either.

### PR DESCRIPTION
**Pull request by Iamgoofball**
Fixes #40836

:cl: Iamgoofball
fix: If you are somehow a revolutionary head as a monkey, you can now properly teach others the plight of the working class.
fix: A monkey with superior intellect can also now be taught the way of Marx.
/:cl:

### CODE REVIEW

**Comment by PKPenguin321** [comment]
revs arent communist wtf

**Comment by PKPenguin321** [comment]
the revolution exists to overthrow the monarchy of nanotrasen and implement a republic reeeeeeeeeeeeee

**Comment by Anonmare** [comment]
Render unto Caesar the things that are Caesar's; and unto God the things that are God's.

**Comment by Iamgoofball** [comment]
@PKPenguin321 but NT isnt a monarchy anymore they're hyper-capitalists

**Comment by CosmicScientist** [comment]
Time for a banana massacre.

**Comment by PKPenguin321** [comment]
>but NT isnt a monarchy anymore they're hyper-capitalists

a hyper-capitalistic society structured like a monarchy is still pretty much a defacto monarchy

**Comment by CosmicScientist** [comment]
The Captain has a crown.

**Comment by Anonmare** [comment]
A literal bannana republic

**Review by AnturK — COMMENTED** [review]
This part looks fine but i'm positive there's checks against nonhuman headrevs counting as dead and such in code along with no checks against automatic promotion of nonhumans, so this is not enough.

**Comment by Iamgoofball** [comment]
I'll go dig around the gamemode.

**Pull request merged**
