### PR TITLE
Resprites Catwalk Tiles to match TG's floortiles

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request
Forgive me Maintainers, for I have sinned.
Months ago, a year ago, maybe longer, I PR'd some new and improved sprites for the Catwalk Tiles here to TG. And when I did, I did not use the right tile palettes for reference.

I have come to atone.

image
image
image
image
image

Additionally, I removed a duplicate white catwalk tile (flat_white - the one left is iron_white) and changed the `none`/error icon in the file to double as both an error marker, and a template of the catwalk mesh for future catwalk tile sprites.
## Why It's Good For The Game
Consistent matching tile sprites are much, much nicer to look at.
## Changelog
:cl:
image: re-sprited Catwalk Floor Tiles to fit with TG floor tiles
/:cl:

### CODE REVIEW

**Comment by theselfish** [comment]
Gonna miss the yellow rim. Damn.

**Comment by Jacquerel** [comment]
> Gonna miss the yellow rim. Damn.

I don't think those are removed, afaict there is no `before/after` example in the OP, that's all "after".

**Comment by SomeoneYouProbablyKnow** [comment]
They look nice, they fit in, the purists won't rip your arms off for this, it's actually a noticable improvement, perfect sprite pr i think

**Review by Wallemations — APPROVED** [review]

**Comment by SyncIt21** [comment]
Fixes #84789

**Comment by Sadboysuss** [comment]
> Fixes #84789

It does? How does a resprite fix that issue?

**Comment by OrionTheFox** [comment]
> Gonna miss the yellow rim. Damn.

The plating-catwalks still have the hazard trim, don't worry! As was mentioned, the screenshots are only the new sprites, not before/afters.
I actually touched it up a bit so the yellow should appear more reflective instead of just being the flat color pattern.

> Fixes #84789

I knew this would come up and intended to clarify in the body but forgot - This does not fix that bug. That is a layering issue (as I mentioned in that bug it's likely from the floor plane thing recently.)
This PR is only a resprite, nothing more. I wish I knew how to fix it but I'm not experienced in layers and planes and stuff.

**Pull request merged**
