### PR TITLE
Increases the GBP value of sprite PRs to 3.

### PR DESCRIPTION
**Pull request by Krysonism**
## About The Pull Request

This PR changes the GBP value of the sprites label from 1 to 3.

image

## Why It's Good For The Game

You currently need to make 8 sprite PRs to gain enough GBP to do a simple balance change.

That is a lot of sprite work, especially if the PRs contain more than a single sprite each.

By increasing the reward, we can encourage spriters to resprite old lackluster sprites, making the game prettier.

### CODE REVIEW

**Comment by Qustinnus** [comment]
yeet up audio too pls

**Comment by maxymax13** [comment]
the spriter nation shall rise again

**Comment by MrDoomBringer** [comment]
image
politically motivated

**Comment by Paxilmaniac** [comment]
> image
> politically motivated

he cant keep getting away with this

**Comment by necromanceranne** [comment]
WHERE IS MY MONEY, LEBOWSKI?

**Comment by Cyberboss** [comment]
> 
> 
> > image
> > politically motivated
> 
> he cant keep getting away with this

I see nothing wrong here

**Review by Cyberboss — APPROVED** [review]

**Pull request merged**
