### PR TITLE
Changes minimum players to get a surpluss crate in uplink

### PR DESCRIPTION
**Pull request by lzimann**
TBH I would prefer removing this for crates(don't care at all about the rest), but i'm keeping the same as everything else

### CODE REVIEW

**Comment by jughu** [comment]
well if you remove no slips on player pop also remove cham box since it includes

**Comment by Niknakflak** [comment]
Nah. :-1: :-1:  you just want the crates and dislike how kor barred it

**Comment by lzimann** [comment]
maybe because it is stupid to begin with?

**Comment by Zilenan91** [comment]
Nah :-1:  it's fine how it is

Crates should be available at anything less than 30 otherwise traitors roll over everyone with infinite shit.

**Comment by lzimann** [comment]
They still can even without a crate(and it's not hard)

**Comment by Zilenan91** [comment]
They actually have to try if they want to munchkin super hard at that point, with the crates just drowning them in shit.

**Comment by lzimann** [comment]
Try what? Emag into armory, get all guns and kill everyone? Get an ebow + esword and kill everyone with ease? The only solution to low pop murderbone is a policy change.

**Comment by Niknakflak** [comment]
Not with that attitude it isn't

**Comment by Bawhoppen** [comment]
CONFIG THIS IS DIFFERENT FOR BASIL GODDAMNIT

**Comment by KorPhaeron** [comment]
I should probably redo this limit so it takes into account latejoin players

**Comment by KorPhaeron** [comment]
Alright this can be merged until I get around to doing the limits properly I guess

**Pull request merged**
