### PR TITLE
MultiZ basics + tile atmospherics

### PR DESCRIPTION
**Pull request by silicons**
WIP

- [x] Basic multiZ mob movement procs (Observers can always move)
- [x] Open space, showing what things are below it, and everything that entails. No complex support for dynamic generation just yet.
- [x] Decide how openspace should look :/
- [x] Atoms falling through open space (NO MOB SUPPORT/DAMAGE/ANYTHING YET.)
//CANCELLED FOR ANOTHER PR - [ ] Being able to see upwards? Downwards is going to be handled by open space.
- [x] MultiZ tile atmospherics - EDIT: Working demo! https://puu.sh/B7mUs/3f6274740f.mp4
- [x ] Bugtest the heck out of this trainwreck.

### CODE REVIEW

**Comment by kevinz000** [comment]
@duncathan 🤗

**Comment by kevinz000** [comment]
@cyclowns our zlevel controller supports grouping zlevels as multiz. Pipes shouldn't be as hard as environmental tbh, at least, for pipenet stuff. What's more worrying is making automatically generated pipe sprites and actaully acquire sprites for pipes.
hoping to do this in a way that doesn't hit performance too hard.

**Comment by Qustinnus** [comment]
@cyclowns

"why are you making PRs to finish multiz if it isn't even done yet" 🤔🤔🤔🤔

Anyways yes we are working on multiz stations and multiz linkage works fine

@kevinz000 ask KMC he offered to help with planetatation he might want to help with pipes

**Comment by cyclowns** [comment]
@Qustinnus pipenets being able to pass through multiz isn't really my definition of 'finishing multiz'. again, I wasn't aware of the progress that was already made on having them implemented and working.

**Comment by ike709** [comment]
I never thought kevinz would be the one to make this PR. I'll be even more shocked if dunc signs off on it.

**Comment by outbools** [comment]
@cyclowns DYOR before reviewing please.
You're not helping with review if you don't know what are you talking about.

**Comment by davethwave** [comment]
Nice to see we are going another step forward toward multiz mapping possibilities.

**Comment by deathride58** [comment]
Holy fuck you're actually doing it, you absolute madman

**Comment by deathride58** [comment]
Keep in mind that vis_contents has layering issues, meaning lighting, catwalks, lattices, etc, might look a little odd on openturfs if you aren't very careful with it. It's pretty much the only reason codebases supporting multiz don't make use of vis_contents yet.

**Comment by Razharas** [comment]
You can take my multiz explosion code if you want, its somewhere among my branches and in rrs old pr

**Comment by Razharas** [comment]
And multiz vines too, all in the same branch

**Comment by BlueNothing** [comment]
So we're coming up on the day when you can blow someone up without them even being able to possibly see the bomb responsible?

**Comment by kevinz000** [comment]
doing multiz explosions/vines/other stuff in another pr, this pr's already hellish as it is with the atmos bullshit tbh

**Comment by Dennok** [comment]
@BlueNothing You can make it now by hidden bomb in closet, underfloor or in walls. Use your imagination.

**Comment by kevinz000** [comment]
As a clarification I will NOT be doing multiZ atmos pipes, only environmental, in this PR. I don't as of yet have sprites for it/to generate it dynamically, and if I can't codersprite 2d stuff properly there's no way I'm coderspriting 3d stuff in our art style.

**Comment by deathride58** [comment]
Baystation has vertical pipe sprites, should be easy enough to just take those.

**Comment by kevinz000** [comment]
Openspace visuals are.. "working", but making it work for lighting and similar would be a challenge.

**Comment by kevinz000** [comment]
still working on looking up and openspace visual lighting, computer is a tad dead so might take a bit.

**Comment by Cyberboss** [comment]
Your PR is getting old. Either Travis CI is failing, it is still labelled work in progress (change this by adding `[READY]` to the start of your title), or there are unaddressed change requests. This may be closed soon to free up space on our tracker if it remains idle. In the event that it is, please ask in #coderbus on Rizon for it to be reopened once you have resumed work on it.

**Comment by ike709** [comment]
rip

**Pull request closed without merging**
