### PR TITLE
Removes __DATASTRUCTURES

### PR DESCRIPTION
**Pull request by Cyberboss**
Most are unused and globals don't belong there. The one thing that is used, /Heap, has been moved to __HELPERS

### CODE REVIEW

**Comment by Iamgoofball** [comment]
do we gain anything from removing them aside from angering remie

**Comment by Cyberboss** [comment]
Faster compile times

**Comment by Iamgoofball** [comment]
can you get us stats

**Comment by JJRcop** [comment]
Here you go goof
bloat

**Comment by RemieRichards** [comment]
@Iamgoofball why do you give a shit about angering me now, when you never did in the past, and when my anger is more meaningless than it's ever been. I don't care about this PR, DM just doesn't support (classic) custom structures well at all.

>globals don't belong there.

Well maybe [YOU](https://github.com/tgstation/tgstation/pull/25325) shouldn't have put them there then??

**Comment by Cyberboss** [comment]
¯\_(ツ)_/¯

**Comment by Iamgoofball** [comment]
consider chilling out

i suggest marijuana

**Comment by Iamgoofball** [comment]
@JJRcop legit graph

**Comment by ShizCalev** [comment]
conflict.

**Comment by Cyberboss** [comment]
Own dick in ass

**Comment by MrStonedOne** [comment]
The issue with `_datastructures` was that 90% of the time were you would care about using the right data structure, was performance cases where the overhead of a framework and the related proc calls is too much

**Pull request merged**
