### PR TITLE
Nicotine No Longer Tastes like Smoke

### PR DESCRIPTION
**Pull request by wesoda25**
## About The Pull Request

title

## Why It's Good For The Game

pop pill, tastes like smoke, hmmmmmmmmmmmmmmmmmmmmmmmmmm

## Changelog
:cl:
tweak: nicotine no longer tastes like smoke
/:cl:

### CODE REVIEW

**Comment by wesoda25** [comment]
idk what nicotine tastes like since im not stupid so lemme know if it does have a particular taste

**Comment by Arathianen** [comment]
"Tastes like addiction"

**Comment by wesoda25** [comment]
actually did consider that but did not put to code good sir

**Comment by bgobandit** [comment]
smoke does have a taste though, what do you think liquid smoke is supposed to be

**Comment by wesoda25** [comment]
nicotine =/= liquid smoke

**Comment by MCterra10** [comment]
When smoking a cigarette ingame, the "you can taste smoke" comes from the nicotine, and this would remove that

**Comment by WaterStBlues** [comment]
Tastes like you're in flavour country

**Comment by wesoda25** [comment]
> When smoking a cigarette ingame, the "you can taste smoke" comes from the nicotine, and this would remove that

I'd rather have that fluff message gone than have nicotine taste like smoke

**Comment by fludd12** [comment]
>I'd rather have that fluff message gone than have nicotine taste like smoke

...Why...?

**Comment by wesoda25** [comment]
> > I'd rather have that fluff message gone than have nicotine taste like smoke
> 
> ...Why...?

I use smoker quirk pretty often so i smoke pretty often in game and i find the message kinda annoying

**Comment by wesoda25** [comment]
also ignore the sprite thing its for another pr ill revert it when i can

**Comment by wesoda25** [comment]
ahh fuck ill be back

**Pull request closed without merging**
