### PR TITLE
removes security borgs

### PR DESCRIPTION
**Pull request by Iamgoofball**
see title

kor said he was going to do it this weekend anyways, making sure there's a 24 hour already PR up

### CODE REVIEW

**Comment by Pascal125** [comment]
Kneejerk PR.

**Comment by Iamgoofball** [comment]
@Pascal125 thanks for not reading the OP

**Comment by Dorsisdwarf** [comment]
iamgoofball trying to steal korphaerons thunder 0/10 would not vote for headmin

**Comment by ishitbyabullet** [comment]
Why do we need a 24 hour already pr for something that is supposed to last a week?

Is coderbus, adminbus, or both so autistic that it can't do anything without the holy PR guiding them?

**Comment by Iamgoofball** [comment]
@ishitbyabullet

read the OP

**Comment by praisenarsie** [comment]
wtf i like goof now

**Comment by ishitbyabullet** [comment]
@Iamgoofball I know, goofball, but why do we need it in the first place?

Just remove it like a normal person jesus christ

**Comment by Iamgoofball** [comment]
@ishitbyabullet

thats what this PR does

**Comment by Robustin** [comment]
No no, your title needed to be "Disentangles borg subtypes"

**Comment by DoctoreMad** [comment]
joke PR

**Comment by praisenarsie** [comment]
@DoctoreMad that's what you think, kiddo.

**Comment by DoctoreMad** [comment]
Still a joke PR.

**Comment by feemjmeem** [comment]
this is stupid, server admins should just disable or enable them in the config options if they don't or do want them

**Comment by praisenarsie** [comment]
@feemjmeem except the headmins/design lead is dumb!!!!!!!! 😀

**Comment by Iamgoofball** [comment]
Read the OP again, you misread it

@doctoremad cease reposting deleted comments

**Comment by feemjmeem** [comment]
that leaves two options goof

1) your pr is a meme saying that kor won't follow through with it
2) you actually intend for kor to follow through with it

in either of those cases this is still stupid

my comment stands

**Comment by KorPhaeron** [comment]
It should just remove the config option and the secborg from the selectable modules, it is still used for wizards (and maybe one day some malf power or whatever)

@feemjmeem Leaving such a giant balance change as roundstart antag hunter with infinite disabler ammo as a config option was always silly and a transparent ploy to dodge codebase drama

**Comment by feemjmeem** [comment]
i certainly don't think it should be enabled, but i agree that the module shouldn't be removed because it still has uses outside of allowing players to access it directly

i see no problems with kor's suggestion here

**Comment by Iamgoofball** [comment]
@KorPhaeron i don't want it to be easy to re-add

**Comment by KorPhaeron** [comment]
It wont be because I can just close it

**Comment by Iamgoofball** [comment]
Okay

**Comment by Pascal125** [comment]
After having played 3 consecutive shifts as a Security Borg. I can safely say. You're all stupid for having removed it in the first place. More so for wanting it removed again.

Literally how do people use it. You have no fucking battery charge and you get killed so quickly by random EMPs everyone seems to have. it's a playerbase issue. Not a code one.

**Comment by Iamgoofball** [comment]
Is a furry hub player trying to tell us that the hub is the reason a shit mechanic is bad

**Comment by jughu** [comment]
Ironically pascal is right

**Comment by Dorsisdwarf** [comment]
@feemjmeem yeah but that means that headmins can enable them whenever they want, bypassing kor's grand design for ss13 or something

**Comment by Pascal125** [comment]
"Furry Hub Player"

ss 2017-11-08 at 07 51 59

Atleast _try_ to sound like you know what you're talking about.

**Comment by Iamgoofball** [comment]
go home you're drunk

**Comment by AnonymousNow** [comment]
They should still pop up in staff of change and adminspawn situations.

**Comment by Partheo** [comment]
You can replace them with eggborgs that transform into sec borgs on code red.

**Comment by KorPhaeron** [comment]
@Iamgoofball remove the config but not the module ping me when it compiles

**Comment by calibraptor** [comment]
How to keep security borgs in whilst limiting how OP having them in is:

- Code in an upgrade board a cyborg has to get installed before they can pick the security module
- Lock it behind R&D
- Place a single secborg board in the armory

**Comment by KorPhaeron** [comment]
@Iamgoofball remove the config from the game options text as well

**Comment by Bawhoppen** [comment]
I just wish we could trust our administration enough to not reenable stuff like this, so we could leave it in for the downstreams who still use it.

**Comment by Iamgoofball** [comment]
@Bawhoppen downstreams can easily revert

**Comment by Bawhoppen** [comment]
I know but it's still unfortunate that we have to add another minor annoyance for them because we can't rely on our people not being dumb

**Comment by Iamgoofball** [comment]
additionally none of our downstreams use secborgs

**Comment by Bawhoppen** [comment]
Well Yog does atleast but they don't actively update but I thought some did.

**Comment by Partheo** [comment]
Can confirm, Yog uses secborgs but they don't update. Not an issue for them.

**Comment by Shadowlight213** [comment]
Felt I should point out that according to statbus, goof hasn't connected since September 4th, and I dunno when he last actually played, so treat his view of the game state with as much credit as the people on the forums who don't play.
As of writing this, he hasn't even seen secborgs live on the server.
I hate secborgs as well, but considering that pascal has actually played them recently, and you haven't even seen them goof, you're full of shit.

**Comment by Iamgoofball** [comment]
@Shadowlight213 read the OP

**Comment by BeeSting12** [comment]
Stop censoring the people

**Comment by Incomptinence** [comment]
We can trust the administration more than coders really.
Evidence above ^^^

**Comment by KorPhaeron** [comment]
Lazy doesnt compile someone else should do this

**Comment by optimumtact** [comment]
It's not censorship, the posts are just garbage and offtopic, this isn't the shed

**Pull request closed without merging**
