### PR TITLE
Lawyers have special speech bubbles

### PR DESCRIPTION
**Pull request by TrustyGun**
:cl: TrustyGun+Pubby
imageadd: Lawyers now have unique speech bubbles.
/:cl:

Lawyers now have new speech bubbles that is a reference to a popular video game series about lawyers.

**NEW SPRITES by @pubby**:
image

### CODE REVIEW

**Comment by Ninja137** [comment]
But why

**Comment by optimumtact** [comment]
Did you even read the PR?

**Comment by Jordie0608** [comment]
I thought this was silly but then I saw the icons; still silly but great.

**Comment by ma44** [comment]
Undocumented change: this also makes TrustyGun a Game Master

**Comment by TrustyGun** [comment]
I'm fairly certain that doesn't change anything for me on the actual server. It is just for easier testing locally.

**Comment by PKPenguin321** [comment]
Perfect :+1:

**Comment by ExcessiveUseOfCobblestone** [comment]
cute and quirky!

**Comment by Incoming5643** [comment]
Hilarious but job intrinsics are bad. 

Make it extrinsic somehow.

**Comment by ExcessiveUseOfCobblestone** [comment]
You could make it a organ, call it the silvertongue or something.

**Comment by Incoming5643** [comment]
That's still an intrinsic. It needs to be something that can be removed from a layer without major surgery.

**Comment by Iamgoofball** [comment]
:+1:

**Comment by Cheridan** [comment]
Intrinsics are fine

**Comment by Incoming5643** [comment]
well if he doesn't do it I probably will later

**Comment by TrustyGun** [comment]
I'm not doing it in this project, considering that this is just a small cosmetic change to a barely played job.

**Comment by pubby** [comment]
Sprite tweak suggestion
objection

**Comment by ike709** [comment]
>ma44 not understanding how admins.txt works

**Comment by Iamgoofball** [comment]
Use @pubby sprites those are A++

**Comment by PKPenguin321** [comment]
Yeah do that

Also I like incomings idea of tying this to a lawyer badge, you could put a few extras into the courtroom locker and disguising as a lawyer wouldn't be too impossible

**Comment by optimumtact** [comment]
I didn't even think about this but it makes disguise impossible as a lawyer, so if you could tie it to something they can change that would be ideal.

**Comment by pubby** [comment]
Just tie it to lawyer suits.

**Comment by Iamgoofball** [comment]
yeah what he said

make lawyers start with it by default on them

you can impersonate it via a lawyer's suit

**Pull request merged**
