### PR TITLE
[Pubby] Re-Arranges And Extends Pubby Escape Hallway

### LINKED ISSUE #24131: [pubby] Docking area isn't large enough
If it can't handle the Meta shuttle, there's no way in hell it'll fit the delta shuttle
_datasstoofat_

### PR DESCRIPTION
**Pull request by JohnTheDonut**
##  **Re-Arranges And Extends Pubby Escape Hallway To Allow Larger Shuttle To Dock**
Re Arranges the Pubby escape/departures hallway to allow larger shuttles to dock without causing damage to the station which may leave players in harm. In order to do this the escape hallway was extended more to the west this lead to the west solar to be moved more to the west and the syndicate shuttle to be moved more to the north west in order to accommodate for the escape hallway changes.

## **Images**
dep

## **Changelog**
:cl: Tofa01
Fix: Re-Arranges And Extends Pubby Escape Hallway To Allow Larger Shuttle To Dock
/:cl:

## **Fixes #24131**

_I got a message telling me things were trimmed when using map merge TGM this would explain the large amount of deletions and additions._

### CODE REVIEW

**Comment by jughu** [comment]
Atleast add some windows to that walled in space area

**Comment by Tofa01** [comment]
Good idea, would not want people to accidentally break that wall and open a hole into space doing that now.

**Comment by WJohn** [comment]
i completely forgot pubby even existed

does this map even get run anymore?

**Comment by Tofa01** [comment]
I have played on it a few times, and it had to be run recently for the original issue to exist.

**Comment by Tofa01** [comment]
Ready for merge whenever.

**Pull request merged**
