### PR TITLE
Bug Test [Do not Merge]

### PR DESCRIPTION
**Pull request by XRandomXManX**
testing something, will close soon

## About The Pull Request

bucket costs 100 iron now, also a bug test

## Why It's Good For The Game

if this bug works then I can become the god you've always wanted

## Changelog
:cl:
add: bucket costs 100 iron
del: all other items from the maint trash pool except for raisins
/:cl:

### CODE REVIEW

**Comment by XRandomXManX** [comment]
am waiting for tests to go through to replicate what happened b4

**Comment by XRandomXManX** [comment]
one of the tests is failing for no reason, not what I was checking 4 but okay I guess

**Comment by XRandomXManX** [comment]
im jsut gonna try this even though a check failed

**Comment by XRandomXManX** [comment]
maint should now contain an abundance of rasins in a while if this works

**Comment by optimumtact** [comment]
who are you and what are you trying to do?

**Comment by ArcaneMusic** [comment]
This is a baffling amount of effort to make buckets cheaper and mait to only spawn rasins.

**Comment by XRandomXManX** [comment]
guess we'll never know. i'll leave it to someone more evil to figure out.

**Comment by XRandomXManX** [comment]
oops, I forgot to update the changelog

**Comment by XRandomXManX** [comment]
there we go

**Comment by optimumtact** [comment]
When you want to stop being cryptic you can contact me on discord to get an unban

**Comment by XRandomXManX** [comment]
Wowie, looks like I got banned... 4 r a i s i n s !

**Pull request closed without merging**
