### PR TITLE
Removes vox

### PR DESCRIPTION
**Pull request by neersighted**
Must... reduce.. RSC... size...

### CODE REVIEW

**Comment by duncathan** [comment]
NOOOOOOOOOO

**Comment by neersighted** [comment]
But 10 mb of rsc savings

**Comment by MrStonedOne** [comment]
could compress them to be honest, they are at like the highest ogg quality, in fact, i have a branch where i did just that, but all sounds (and people didn't like this)

**Comment by optimumtact** [comment]
:+1:

**Comment by MrStonedOne** [comment]
but why?

**Comment by optimumtact** [comment]
I never hear people using it

**Comment by GunHog** [comment]
No, use compression or something, do not just axe fun features! :-1:

**Comment by RemieRichards** [comment]
Somebody invent a complex algorithm to generate these sounds on the fly instead of having them in the resource! yeah that'll be worth the time and effort! YEAH! YEEEAAAA!H
*flails madly*

**Comment by GunHog** [comment]
TTS for AI and Head of Staff announcements would be amazing.

**Comment by neersighted** [comment]
http://responsivevoice.org/

**Comment by RemieRichards** [comment]
@neersighted can we customise the voice on that? it sounds too human atm.

**Comment by neersighted** [comment]
@RemieRichards Probably, haven't delved too deeply into it.

**Comment by RemieRichards** [comment]
well I only made it say "Johnson inspection in medbay" but still.

**Comment by Alek2ander** [comment]
http://demo.codesamplez.com/html5/webspeech

**Comment by Shadowlight213** [comment]
:-1: Vox is part of tg culture.

**Comment by neersighted** [comment]
> tg culture

**Comment by TrustyGun** [comment]
>I never hear people using it

Are you mad, every other time there's an AI that uses it. Find a way to compress them or something. :-1:

**Comment by LanCartwright** [comment]
how about i counter offer
i find an actress to voice it
then we have 600mbs worth of mp3/wav files (or 3 gigs or FLAC) instead of 10mbs of vox.

**Comment by MMMiracles** [comment]
anything that removes my ability to spam 'ass blast usa' into the general comms is a big :-1: to me.

**Comment by Aloraydrel** [comment]
Why would you do something like this? Please stop.

**Comment by freerealestate** [comment]
no complaints
clunky garbage
:)

**Comment by neersighted** [comment]
I'd much rather remove it and replace it with TTS than have a list of hardcoded sounds to create a new UI for.

**Comment by Iamgoofball** [comment]
Hey faggots why don't we just get a new text to speech engine and find a way to use DLLs to interface with and generste shit on the fly

**Comment by MMMiracles** [comment]
@neersighted 
I mean that's great but usually you want to push the replacement for the thing your removing in the same PR.

**Comment by Chnkr** [comment]
You could always load vox on-the-fly from a CDN and use a `<audio>` tag inside a hidden skin element to play them.

**Comment by vista-** [comment]
bring back old HL vox tbh

**Comment by TheRealGLH** [comment]
@Chnkr 
How would that work in regards to lag?
Usually when admins upload sounds for players to hear, it causes slight (but noticeable) lag. Won't you get the same thing when trying to load a bunch of .ogg files at once? It's not like most VOX commands are short, they're usually full sentences.

**Comment by Chnkr** [comment]
@TheRealGLH Zero to no lag, since the work is done by the browser and not BYOND, it works fine over at Goonstation for things like TTS and i did some small tests myself with using `<audio>` tags for audio and music.

**Comment by PKPenguin321** [comment]
FUN REMOVAL
DON'T DO IT NORMIE

**Comment by Jazaen** [comment]
TTS would be great. We could then re-entact https://goo.gl/iOO7hk IN SPAC... ON SPACE STATION.

**Comment by Razharas** [comment]
We can make a nice icon handling system for mobs that would get us rid of inhands icons
Maybe then rsc wont be as big, who knows

**Comment by optimumtact** [comment]
Vox is cox

**Comment by PKPenguin321** [comment]
DROP THE CODE NORMIE LEAVE THE FUN IN THE BAG

**Comment by Alek2ander** [comment]
https://www.youtube.com/watch?v=Hv6RbEOlqRo

**Comment by optimumtact** [comment]
replace vox with https://github.com/optimumtact/50shadesofpython

**Comment by neersighted** [comment]
I surrender. I'll come back when I have some time to implement TTS, but tgui takes priority now.

**Pull request closed without merging**
