### PR TITLE
Rebalances clockwork marauders

### PR DESCRIPTION
**Pull request by ghost**
:cl: Xhuis
balance: Clockwork marauders now move more slowly below 40% health.
balance: Instead of a 40% chance (or more) chance to block projectiles, clockwork marauders now have three fixed 100% blocks; after using those three, they cannot block anymore without avoiding projectiles for ten seconds. This number increases to four if war is declared.
balance: Projectiles that deal no damage DO reduce marauders' shield health. Use disabler shots to open them up, then use lasers to go for the kill!
/:cl:

First point: marauders now move slowly when below 40% health, making them more easy to finish off instead of being zippy, tanky constructs until zero. Self-explanatory here.

Second point: marauders don't have an RNG chance to block projectiles anymore. Instead they have "shield health", maxed at 3, that decreases by 1 for every projectile absorbed. If it reaches zero, a loud sound and message will show that the marauder can no longer block projectiles, and they will take any hits like normal. This amount refreshes to its max (3 by default, 4 with war) every 10 seconds that goes by without being hit by a projectile.

While marauders can still be strong in the right hands and even buffed if played effectively, this makes them far less durable and forces them to play more carefully in order to stay alive. They can no longer take a barrage of lasers, and their blocks are more of a "second-chance" mechanism now. This also opens up strategies like the crew firing disabler shots to break the marauders' guard before using lethals that it's vulnerable to.

(Projectiles that deal no damage reducing shield health is intentional, and meant as a way to allow interesting counterplay.)

### CODE REVIEW

**Comment by DoctoreMad** [comment]
>Projectiles that deal no damage reducing shield health is intentional, and meant as a way to allow interesting counterplay.

Please detail this in the changelog, it'll still be a esoteric hidden knowledge change but less so.

**Comment by Xhuis** [comment]
Good point.

**Comment by MMMiracles** [comment]
New meta strat: run in with laser tag gear to drop their shields with zero possible threat to fellow siege members.

**Comment by Xhuis** [comment]
That's a legitimate tactic! The drawback comes from that the crew are using weapons that are useless against normal servants, meaning that if a servant catches them unawares they're as good as dead or converted.

**Comment by AnturK** [comment]
Should lose the shield on the icon when they can't block but i guess bit late on this suggestion.

**Pull request merged**
