### PR TITLE
donut outreach initiative

### PR DESCRIPTION
**Pull request by MMMiracles**
## About The Pull Request
make donut great again

## Why It's Good For The Game
make donut great again

## Changelog
:cl: MMMiracles (Donutstation)
tweak: The southern/north-west parts of maintenance has been revamped to include more things to dig through and places to hide from authority.
tweak: The atmos tanks have had an extra layer of space added between the windows between them and maintenance.
tweak: The permabrig has had a small B-ball court added as well as an N2O release system.
tweak: Tweaks and additions to the various department excess storage rooms through-out maintenance.
tweak: The AI core now has a more proper internal defense against ranged attacks, the tri-ai spawns have gotten similar treatment as well.
tweak: The few maintenance-facing windows have been beefed up to their stronger plasma variants.
tweak: More directional signs to help those in finding some departments.
/:cl:

Hey you, yeah **YOU**:
Got any criticism of the map? Post it here! Don't have a github? Post it in the forum feedback thread [!here!](https://tgstation13.org/phpBB/viewtopic.php?f=11&t=20050) Don't have a forum account? @ me on discord ("ememem" or "not a g'nome#2914")! Don't have anything? Go make one and voice your complaint somewhere that isn't the cesspool of OOC! I can only fix problems if I know about them in the first place!!!

Updated map with all changes as of 8/22:
[Big o' map](https://affectedarc07.co.uk/TGStuff/MapGen/Images/117.png)

**Changes so far**:
- Permabrig has a separate pipeline and canister port for the N2O canisters. These vents start off but officers have access to the permabrig's air alarm.
- Permabrig now has a small ball court to practice your free throws and dunking the warden in it.
- Permabrig has a small set of gym equipment to get swole while you do hard time.
- Removed some rogue R-walls near the back side of security maintenance.
- Unfucks cargo's conveyor belts.
- Chemistry now has 2 large beakers.
- The few remaining maintenance shocked grilles that managed to slip through the first pass have been removed.
- The gateway maintenance room has been renovated into a theatre excess storage and some extra misc sections.
- The space maintenance room has been renovated into a miscellaneous tool storage with some basic building material for tiders and autism-fort builders alike.
- The north-west section of the station has had it's maintenance extended to be able to reach the top of departures. Includes a toggable blast-door bridge for the shuttle ferry and some extra maintenance rooms.
- The south-western part of maintenance near Atmospherics has been redone to allow a space gap between the atmos tanks, also includes some extra rooms.
- Added a small maintenance tunnel leading into Engineering on the most-left maintenance side, branching off from Hydroponics maintenance. The Engineering Storage room has had a few extra windoors added for security to compromise.
- Small excess storage in the most-right maintenance for Engineering.
- Small bits of fluff scattered around.
- The maintenance-facing windows of areas like Genetics have been reinforced to their plasma variant.
- Bits of additional maintenance loot in various areas.
- The camera outside the upload has been changed to a normal one due to complaints about motion detecting.
- The vault access now has a camera so the AI can actually see the turret controls (oops)
- Vault now has to be initially accessed through the public hall normally with an extra airlock.
- All on-station windows have been replaced with structure spawners for said windows.
- The gateway has been moved to where the commissary currently sits due to becoming active in rounds again.
- The commissary has been moved between tool storage and the vault, in front of the vault. the maintenance areas that once sat here have been renovated as excess storage rooms for the tool storage/commissary. 
- The upload and captain's office now has an extra layer of R-walls due to complaints about ease of break-in via space.
- The AI core now has some basic frontal defense against ranged weapons as well as emergency blast doors to lock down around it's central cubby-hole. The tri-ai spawns are set up to be the same as the main AI spawn spot.
- Added a couple extra EVAC directional signs since there was some apparent confusion about where it was.
- Medical now has a couple roundstart wheelchairs because why not
- Xenobio has been given an extra slime
- Xenobio has been shifted around, removing the 2nd freezer and moving the slime consoles besides the rest of their equipment.

**Non-station related changes**:
- Airlock Note Placer mapping helper. Allows mappers to easily place paper notes on airlocks, whether they be custom or pre-made from one of the subtypes.

### CODE REVIEW

**Comment by wesoda25** [comment]
The maintenance is restricted and kinda boring. Upload shouldn’t be in maint.

**Comment by MMMiracles** [comment]
Anything more specific regarding maintenance? I purposefully tried to keep things like loot randomized and lower than usual, with the exception being the excess storage rooms which are meant to be where a tider should look for department-specific loot. If the issue is a lack of hiding spots/diverging points, I can look into that.

**Comment by Tlaltecuhtli** [comment]
put disposals near cargo
remove shockgrilles in maint
add transport tubes in the main hall

**Comment by MMMiracles** [comment]
disposals near cargo is gonna require a lot of disposals reworking and i never heard any actual issues with it being there
shock grilles have been gone for the map for over a month now
transport tubes are unironically bad for anything past singular between A and B movement (i.e ai sat and back)

**Comment by Striders13** [comment]
As a greytider, I feel that this map needs more hiding spots in maint. I like making my own little maint base and I just couldn't find any decent spot for it.
Also I don't like the location of the armory. It's especially bad if you're a pirate, since your best chance of getting there is through permabrig, which would require 4 explosives in total.
As an AI, your core really lacks protection, especially glass in front of your core, anyone can just hack open a door and shoot you with laser gun through it. Those privacy shutters are pretty useless too. Also your upload in maint with a single camera which isn't even motion-sense (or no camera at all? not sure) in front of it, which, when deactivated, makes you unable to control upload turrets.

**Comment by TerraGS** [comment]
I know the whole theme is the station being round, though many people complain about having to walk down angular hallways, so I propose considering a means of mitigating the curvature of the main access corridors to make travel a tad bit more user friendly. I don't hold my breath on this, as I realize this may require significant thought on what to shift around to make it work.

**Comment by MMMiracles** [comment]
is travis having a stroke or

**Comment by halitosisman** [comment]
The more popular stations have fairly direct and straight routes between most locations. This map is objectively worse for players who don't enjoy walking simulators. 

When I last played this map, it lacked either the white ship or its GPS, which is a huge annoyance for persons like me who love working with it.

**Comment by MMMiracles** [comment]
This map is literally a circle that leads to every department how is this not a direct path to wherever you want to go?? You literally cannot get lost and distances between departments is on par if not shorter???

White ship was added in an earlier PR and has its docking port on the south side of the station near the satellites.

**Comment by halitosisman** [comment]
> This map is literally a circle that leads to every department how is this not a direct path to wherever you want to go?? You literally cannot get lost and distances between departments is on par if not shorter???
> 
> White ship was added in an earlier PR and has its docking port on the south side of the station near the satellites.

example: On metastation, it takes about 83 steps to travel between cargo and engineering. The same trip on donutstation requires 109 steps, a 30% increase from meta.

If one is in a travel heavy job, simply being on donut can result in a 30% productivity loss. The diagonal distances on donut can mitigate that factor, but certain other trips, like the frequent sec to dorms trek are significantly worse than the example I just described. 

Does the Donut white ship have a GPS in it?

**Comment by MMMiracles** [comment]
If we're gonna get real anal about travel distance: From the front desk of science to the lobby of cargo is around 35~ turfs, meta being around 45~, and box being around 90-95~. Every map has different department placements and that is going to change their travel time, where one map has shorter distance between one department it makes it up in taking longer to get another. 

I apparently forgot to add a GPS to the white shuttle, I'll fix that in this PR.

**Comment by Learner10** [comment]
I think the last time I was on Donut, I noticed some lacking options for available destinations for MULE Bots. I'd probably give that a look real quick.

**Comment by optimumtact** [comment]
hurry

**Comment by MMMiracles** [comment]
oh yeah this was done when i removed the [DNM] tag

**Pull request merged**
