### PR TITLE
Adds golem ship to lavaland main map

### PR DESCRIPTION
**Pull request by coiax**
In addition to copying in the free golem ship, also fixed that pesky
door with a wall behind it.

:cl: coiax
rscadd: Free Golems have now become a permanent fixture of lavaland
/:cl:

There may be other things that may need to be changed, but this here's the map changes.

### CODE REVIEW

**Comment by Core0verload** [comment]
I don't like it. Ghost roles mustn't be guaranteed. Maybe you will get some, maybe the ruins generator spawned none.

**Comment by coiax** [comment]
There's a decent ghost population who ghost at the start of the round to play golems.

Instead of making the ship a permanent feature, we could hook it into the job selection code. If that's even possible. Means people would ready up, get the lavaland roles if they're there, and get normal shift stuff if it's not.

**Comment by Dorsisdwarf** [comment]
:-1:

**Comment by TrustyGun** [comment]
No, for the reasons Core specified. :-1:

**Comment by coiax** [comment]
But how do you solve a problem like people observing in the hope that golems are there? Golems are very popular, this isn't deadchat saltiness demanding participation, this is people wanting to do this before the round has even started.

**Comment by lollerderby** [comment]
👌👀👌👀👌👀👌👀👌👀 good shit go౦ԁ sHit👌 thats ✔ some good👌👌shit right👌👌there👌👌👌 right✔there ✔✔if i do ƽaү so my self 💯 i say so 💯 thats what im talking about right there right there (chorus: ʳᶦᵍʰᵗ ᵗʰᵉʳᵉ) mMMMMᎷМ💯 👌👌 👌НO0ОଠOOOOOОଠଠOoooᵒᵒᵒᵒᵒᵒᵒᵒᵒ👌 👌👌 👌 💯 👌 👀 👀 👀 👌👌Good shit

**Comment by coiax** [comment]
QUALITY MEMES.

**Comment by Dorsisdwarf** [comment]
>But how do you solve a problem like people observing in the hope that golems are there? Golems are very popular, this isn't deadchat saltiness demanding participation, this is people wanting to do this before the round has even started.

This is a self-solving problem.
They observe, they get golem because its there, they're happy.
They observe, there is no golem, other observers make fun of them/ they get Ash Walkers / go for a drone

**Comment by duncathan** [comment]
/ wait for someone to buy a stand / wait for positronic brains / wait for adamantine runes / all the other observer jobs we have

**Comment by Durkel** [comment]
I loathe the idea of people observing/ghosting just to get ghost roles.

**Comment by coiax** [comment]
Then how do you solve a problem like people wanting to play FREE GOLEMS? Modify the job code stuff?

**Comment by octareenroon91** [comment]
Ruins are meant to be random. Guaranteeing a random ghost spawner is one thing. Guaranteeing a specific spawner is pretty crummy.

**Comment by jughu** [comment]
Its not like you want every round with a traitor miner with a army

Or like in vault growing 375. One of the strongest weapons in game

**Comment by coiax** [comment]
Traitor miner with an army? I supposed technically, a miner could come in and take the design disk, but there's generally a sizeable population of free golems at that point, especially at the time it takes to mine that distance.

Gatfruit isn't a guaranteed spawn in the botany vault either, and I swear its stats are fucked up, and it needs voodoo botany magic to actually bear fruit. But I'm not a botanist so I wouldn't know.

**Comment by jughu** [comment]
>magical voodoo botany magic

Just hack the vending machine and dunk dietylm on it and then mutate yield/stats with the flomatray gun

**Comment by coiax** [comment]
> > magical voodoo botany magic
> 
> Just hack the vending machine and dunk dietylm on it and then mutate yield/stats with the flomatray gun
Hack the vending machine with what tools? Can you grow multitools with botany now?

**Comment by Impisi** [comment]
People already ghost at round start to play derelict drones. I don't see the problem with having round start golems.

**Comment by TrustyGun** [comment]
Roundstart golems have a much heavier effect on the round; drones can't talk or interact with miners; plus it's usually like a couple of drones, golems grow exponentially.

**Comment by octareenroon91** [comment]
Drones could also grow exponentially. They just tend not to.

**Comment by coiax** [comment]
Drones can mass produce shells very easily and cheaply. A full stack of metal and glass would produce enough drone shells for a full server of drones. A full stack of metal for free golems will give you, slightly less than two golems, unless you have other materials on hand to finish the shells.

**Comment by optimumtact** [comment]
Golems are too powerful to be roundstart for ghosts

**Comment by KorPhaeron** [comment]
I might code to ensure at least one respawn point spawns each round, but I don't think it should be a 100% thing for any one ruin on lavaland. Sorry.

**Pull request closed without merging**
