### PR TITLE
[MAP] Security Mini-Medbay

### LINKED ISSUE #17747: Box armory is missing its medkit again

### PR DESCRIPTION
**Pull request by Steelpoint**
Since I'm annoyed by the constant removal of the security medkit I'm instead porting over a variant of Metastation's security medbay.

screenshot 2016-05-23 13 54 57

(The sliding doors are all access)

I would argue this is a minor map change considering how little of the map is changed but I'll accept waiting for the end of the freeze if need be.

This PR was created thanks to discussion in game.

E: Also fixes #17747

### CODE REVIEW

**Comment by pudl** [comment]
Nice try shitcurity.

**Comment by Shapsy** [comment]
You were the one who stealth-removed the medkit to begin with

**Comment by pudl** [comment]
I was the one who stealth-added it as well

**Comment by xxalpha** [comment]
Review your map to make sure nothing is out of place.

**Comment by optimumtact** [comment]
@xxalpha is there something wrong?

**Comment by Cheridan** [comment]
does the warden still get one in his office too?

**Comment by Steelpoint** [comment]
@Cheridan No I didn't re add that. I can if you want.

@xxalpha The only thing I noticed that was off is that two of the chairs in the integ room are MIA. Though that was not me I can re add them.

**Comment by hornygranny** [comment]
ban this sick filth

**Comment by KorPhaeron** [comment]
No Cheridan, see above about the stealth removal

**Comment by Niknakflak** [comment]
**Metastation medbay**
debunksteelpoint
Notable things

- Two medkits (both standard)
- IV drip
- Medical laptop
- Morgue tray
- 1 antitox bottle
- one epinephrine bottle
- Med scanner
- Space cleaner

-------------------------------------------------------------------------------------------------------------------

**Steelpoints new Medbay**
image

- Four medkits, two standard, one bruise, one burn.
- IV drip
- Two morgue Trays
- Space cleaner
- Med Scanner
- I can see a epinephrine bottle but who knows whats underneath it


Yea these sure are balanced.  The two extra different medkits sure bring out the steelpoint security powergame

**Comment by Steelpoint** [comment]
Is that a joke or?

The main difference between the two is the addition of two extra FAK's, one extra morgue tray and that's it.

(There's a anti-tox bollte under the epi bottle)

**Comment by Niknakflak** [comment]
four medkits with a burn and bruise is vastly different from two standard medkits

**Comment by Steelpoint** [comment]
If its that game breaking I can remove them.

**Comment by Niknakflak** [comment]
I'm just not sure why you didn't just copy metastation brig medbay exactly.  There wouldn't be any controversy and no one could accuse you of adding extra stuff to buff security, but yet, here we are.

**Comment by Steelpoint** [comment]
Not everything I do has a nefarious intent, I simply wanted to make it look like a extension of medbay hence the addition of a proper rack of supplies.

I honestly did not expect having one or two extra kits to be that controversial.

I also didn't want to carbon copy meta's sec med bay.

I'll remove the extra FAK's then.

**Comment by xxalpha** [comment]
@Steelpoint I meant in the entire map with the merged file.

**Comment by Niknakflak** [comment]
Everything you do has pretty much always buffed security, so It's easy to see when another thing obviously buffs security, even past the point of something someone else already got in, that your intent was to buff it even more than what was already deemed acceptable.

**Comment by Steelpoint** [comment]
I've removed the specialist FAK's and re added the extra integ chairs to security.

**Comment by Bawhoppen** [comment]
reee steelpoint just give up ruining sec please

**Comment by PKPenguin321** [comment]
Why do they even need this just put the medkit back in the wardens office also feature freeze

**Comment by Steelpoint** [comment]
>adds minor medbay to sec that most other station's have

>steels ruining security

Come on. The only bad thing with this was the extra FAK's but I removed those.

**Comment by Bawhoppen** [comment]
no but you always overdo everything, "oh lets give 30 brute rifles to security, and 2 shot drop pistols" "oh man security needs all these medkits and supplies to heal screw medbay"

**Comment by Steelpoint** [comment]
If I do overdo things people tend to point it out, hence why I took their word and reduced the FAK's down.

Hence why now the PR is better for it thanks to these discussions.

**Comment by Eaglendia** [comment]
can we just get like, a medkit

**Comment by TrustyGun** [comment]
I don't really see an issue with this. :+1:

**Comment by Core0verload** [comment]
Just add a medkit to warden's locker.

**Comment by Steelpoint** [comment]
This is a far more permanent solution and it provides several additional benefits to security, aside form a accessible medical holding pen (Straightjacket) but also some quick to access (and view) morgue trays for corpses. 

I've added a medkit to the armoury/warden's locker around three to five times.

**Comment by Anonmare** [comment]
I like how everyone dog-piles Steelpoint and accuses him of power game everytime he adds a minor change to security.

**Comment by Niknakflak** [comment]
Im ok with this now.

**Comment by Steelpoint** [comment]
test

**Comment by GunHog** [comment]
I would replace the morgue trays with more beds/roller beds. It should not encourage Sec to kill people and store the bodies within the department. It should appear as an area for keeping prisoners alive. Morgue trays should be in places where corpses are encouraged to be (Morgue, Kitchen, Robotics, Detective Office).

**Comment by PKPenguin321** [comment]
I mean I'm okay with this I guess but I don't get why it's necessary?

**Comment by optimumtact** [comment]
@Anonmare That's called having a reputation, and they take a long time to shake.

**Comment by lzimann** [comment]
should remove the metastation's mini-medbay instead of adding one to box

**Comment by Steelpoint** [comment]
I don't think the addition of two morgue trays would encourage security to execute more people.

Also sometimes Security does not want to take a corpse out of security, since they don't want to risk them being cloned or akin.

**Comment by lzimann** [comment]
My biggest problem is how much healing stuff there is, one of my biggest problems with metastation is this, you can find a medkit every 10 steps. Security doesn't need 3 medkits, 2 of which are the brute/burn patches...

**Comment by Steelpoint** [comment]
There are only two medkits in this PR.

Meaning there will only be two Medkits in the brig at all.

**Comment by lzimann** [comment]
I still don't see why it is needed, at all

**Comment by Steelpoint** [comment]
Its been twenty four hours, requesting a review of this PR.

**Comment by PKPenguin321** [comment]
Freeeeeeeeeeeeeeze

**Comment by Core0verload** [comment]
I repeat, just add a medkit to warden's locker. If you need something more, use epipens and medbay.

**Comment by Steelpoint** [comment]
I belive this would be not only a solution to the medkit issue for security, but a good quality of life additon to the brig and security in general.

At the end of it its just two medkits, the rest is nice fluff that will be a good addition.

**Comment by xxalpha** [comment]
>quality of life

That's the issue, isn't it?

**Comment by pudl** [comment]
remove the bottom right table and move the first aid kit on it to the table with the other one. remove the redundant health analyzer. move the bed to where the table was, remove the straight jacket (sec already has two in the asylum). remove the table with the pointless paper bin/pen, put the iv there so there's no ugly stacking going on. remove the window pane next to the morgue trays, border objects suck and pointess/aesthetic ones are being phased out.

**Comment by Metacide** [comment]
Looks great, it's clearly a neat idea for fluff and interaction in the brig, and two standard medkits really isn't anything to worry about.

Ignore anyone screaming powergaming reeee, this is a good idea and should clearly be added sometime, freeze notwithstanding.

:+1:

**Comment by Hatfish** [comment]
I don't understand why anyone would be against this, it's literally just a 4x4 room with some easily obtainable medical gear inside.

**Comment by ChangelingRain** [comment]
I dislike the easier access to the straitjackets and removal of the sanitarium

**Comment by TrustyGun** [comment]
I mean, honestly, tell me ONE thing people used the sanitarium for.

**Comment by optimumtact** [comment]
I will merge this at midday today nz time unless someone has a very strong reason not to

**Comment by PKPenguin321** [comment]
...it was opened and is still open during a freeze?

I mean I'm not opposed to this but can we please stop making this freeze more of a joke than it already is

**Comment by optimumtact** [comment]
map edits are explicitly allowed by head coder during the freeze

**Comment by PKPenguin321** [comment]
oh ok

**Comment by PKPenguin321** [comment]
yeah go ahead then

**Comment by Steelpoint** [comment]
Also this dosn't add in any additional straight jackets, considering the insane ward had two and I removed the insane ward.

One jacket is in the med ward, the other is in the brig main hallway.

Thanks oranges.

**Pull request merged**
