### PR TITLE
Damage Converter symptom now does toxin damage for each limb healed

### PR DESCRIPTION
**Pull request by ChangelingRain**
:cl: Joan
tweak: The Damage Converter virology symptom will now do toxin damage for each limb healed.
/:cl:

This means it'll heal up to 6 or 12 brute and burn both, but also do up to 6 or 12 toxin damage based on the number of healed limbs.

### CODE REVIEW

**Comment by WJohn** [comment]
So this means healing viruses will still be useful against healing targetted damage on one limb, but will be very dangerous to use if you want to traverse space since everything gets hit, right?

**Comment by ChangelingRain** [comment]
More or less, though they will slow down how fast space kills you, as it's doing brute and burn both.

**Comment by Buggy123** [comment]
Good, you all got your virology nerf, now please stop trying to ruin the department.

**Comment by newfren** [comment]
When you name shit like this can you actually use the name of the symptom?

**Pull request merged**
