### PR TITLE
un-ruins one of my sprites

### PR DESCRIPTION
**Pull request by Cheridan**
qi30i2x

### CODE REVIEW

**Comment by WJohn** [comment]
ok

**Comment by optimumtact** [comment]
eww Cheridan that looks gross, do you need glasses?

**Comment by xxalpha** [comment]
left: a mouse cursor

**Comment by coiax** [comment]
which is the unruined one

**Comment by PKPenguin321** [comment]
wait which is the new ones

**Comment by Nienhaus** [comment]
According to my email, the left one.

**Comment by Jalleo** [comment]
The left is better but you cant really do much with a red ball.

**Pull request merged**
