### PR TITLE
"Medium" tier of explosions won't make breaches on floor tiles.

### PR DESCRIPTION
**Pull request by GuillaumePrata**
## About The Pull Request
Explosions are split into 3 tiers right now, Devastation, Heavy, Light.

Devastation deletes almost everything it touches, people, walls, windows, machinery, floor, etc.
Light does chip damage to humans, structures and the important part, never breaches the floor.
Heavy is the core of my issue with the system, it does heavy damage to mobs, break airlocks, destroy walls and if my math is correct it makes a breach on the floor more than 90% of the times.

This PR adds some granularity to our explosion system by changing Heavy explosions to never cause floor breaches (they still easily delete walls/windows, so you can create atmos issues with proper placement.) with the goal to give more control to future bomb balance.

This also nerfs a lot of explosives while making others more valuable, but rebalancing all of them here would be a silly attempt and best suited for future PRs after we get more feedback from players.

## Why It's Good For The Game
It is a balance lever, if you want an explosive to create a floor breach and trigger atmos issues, like the weak point explosive goal, give it devastation value.
If you want a bomb to heavily damage people, airlocks or walls without creating breaches, give it heavy value.

We can now design bombs with the goal of destroying walls for entry points and killing people directly without triggering a station wide firelock hell which is often followed by an early shuttle call.

## Pictures
<details><summary>Delta's Medbay before a syndicate bomb</summary>
<p>

medbay_before_bomb
</p>
</details>
<details><summary>Medbay bombed without changes</summary>
<p>

medbay_live
</p>
</details>
<details><summary>Medbay with changes</summary>
<p>

medbay_PR

Firstly, this is ugly, I was working on moving this behavior only to the hull plating itself and searching for other issues that might pop up, but I gave up, I will give more details in a closing comment.

Secondly, you might be thinking: "Guillaume they are almost the same, what are you even changing?"

The way our explosive code works (And again, I didn't read all of it so I might say something wrong here) makes our 90+% chance of a breach be a lot lower because if there is something on top of the tile and it survives the explosion, the tile under it can't be broken into space.

This includes things like girders, windows, airlocks, machinery, disposal pipes, atmos pipes, lockers, and even wires...

So here, the last example of a syndicate bomb where there isn't anything on top of a tile:

pure plating hole

This is the 225 area breach I talked about in comments, but it is actually 249 because I'm shit at math.
</p>
</details>

## Changelog

:cl: Guillaume Prata
balance: NT has reinforced the station floor tiles against explosions. While high tier explosives still create breaches easily, most explosives will be unable to breach the floor hull unless designed with that intent.
/:cl:

### CODE REVIEW

**Comment by Colovorat** [comment]
chemistry nerf

**Comment by exymian** [comment]
great pr, most of the time i wouldn't use explosives because i don't want to cause breaches. thanks

**Comment by timothymtorres** [comment]
Great PR writeup but I disagree that Heavy explosions should _never_ cause explosions.  90% seems really high and that amount should probably be lowered to 25%-35% so there is still a decent chance.

Also you should do screenshots of before and after for different explosions since this will affect a wide range of things.  I'd suggest: C4, X4, Syndicate Bomb, SM delam, etc.

**Comment by GuillaumePrata** [comment]
> Also you should do screenshots of before and after for different explosions since this will affect a wide range of things. I'd suggest: C4, X4, Syndicate Bomb, SM delam, etc.

Pictures for each explosive would take time but the number values (Devastation/Heavy/Light) are easy to follow as the range is the number of tiles away from the epicenter, creating a circle. (A 3 range explosive makes a 5 wide circle)

C4 is 0/0/3 meaning nothing will change to it as it couldn't make breaches already.
X4 is 0/2/5 so it lost it's floor breach potential fully. It is the perfect example of an explosive made for safe entry as you will destroy airlocks and walls but never make a hole on the floor and create atmos issues, making it a lot more viable for non space proof criminals.
Syndicate bombs are 3/9/17 so it is the biggest change. It went from making a breach of 225 tiles down to 21
It will still destroy windows and walls on a 225 area so it will still create breaches anyway, just easier to repair as you cut from 225 floor tiles (55 metal sheets) + iron rods to an affordable 21.

SM, chemistry and gas explosions are variable but somewhat linear so if it made a breach in the past, it will still make a breach now, just smaller as each one has their own ~~magic number~~ math.

> Great PR writeup but I disagree that Heavy explosions should never cause explosions. 90% seems really high and that amount should probably be lowered to 25%-35% so there is still a decent chance.

The syndie bomb is why a low chance still wouldn't help, it affects a total of 225 tiles, even at 25% that would still make 50+ random breached tiles.
25% on the X4 would meant that you are still almost guaranteed to make at least 1 breached tile when used, completely negating the new advantage of it being a safe explosive for antagonists that do not have a space suit.

**Comment by Palpetinus** [comment]
Amazing. Firelock hell is one of the biggest issues I have with the game, usually you just get a 3-9 tile hole that's quickly fixed but now you have atmos problems that never get fixed and don't actually impact the round in any way besides maybe denying an (easily bypassed) hallway. It was only outright chaos-inducing in large numbers but that happened very rarely.

**Comment by LarissaMayrink** [comment]
> Amazing. Firelock hell is one of the biggest issues I have with the game, usually you just get a 3-9 tile hole that's quickly fixed but now you have atmos problems that never get fixed and don't actually impact the round in any way besides maybe denying an (easily bypassed) hallway. It was only outright chaos-inducing in large numbers but that happened very rarely.

chaos is good, it adds to the sense of danger without actually removing people from rounds, which is very good to make people feel uncomfortable and on their toes


x4 rarely ever does more than a single tile of hull breach, it takes a literal second to fix, and its not like you can't ignore it and do your object even without being spaceproof, the damage is minimal

and even syndiebombs damage gets fixed in under a minute, those are only problems in extremly low pop rounds and tg shouldn't revolve around expecting that eight people are playing

**Comment by ATH1909** [comment]
eh, I kind of feel like explosions *should* be dangerous to use on a space station, no?

**Comment by Jackal-boop** [comment]
I think the chance for it should be lowered, instead of removed

**Comment by GuillaumePrata** [comment]
> eh, I kind of feel like explosions should be dangerous to use on a space station, no?

While I agree with you, there are smarter ways to make explosions threatening and engaging than instant hole on the floor that is an early shuttle call on most shits.
Our explosive balance is non existent, a lot of magic numbers everywhere because the 2 upper tiers of explosions works basically the same and the lower ones do basically nothing.

Reinforced walls are weaker to explosives than windows, it's all silly right now, but if this is merged I will do more PRs to fix these weird behaviors.

**Comment by LarissaMayrink** [comment]
> While I agree with you, there are smarter ways to make explosions threatening and engaging than instant hole on the floor that is an early shuttle call on most shits. 

then advocate for shuttle calls for minor things to be treated differently on the policy, on manuel and campbel rounds routinely go for close to two hours even though the bombings still happen due to simply more will to repair instead of heads hoping to get a new roll for antags as soon as possible

**Comment by private-tristan** [comment]
if this gets merged, shouldn't syndiebombs and syndicate minibombs get their prices reduced to compensate? their main use was reducing a department/area into nothing but a hole into space that is hard to repair.

**Comment by GuillaumePrata** [comment]
> if this gets merged, shouldn't syndiebombs and syndicate minibombs (and I guess macrobomb implants) get their prices reduced to compensate?

Possibly depending on player feedback. Another option is to just swap the heavy damage for devastation instead so it goes back to a strong and expensive way to delete a department.
But as I said in the PR body, adding extra balance changes on top of this will just make people try to guess what is balanced without experiencing the change.

**Comment by msgerbs** [comment]
What if there was a 4th radius for explosions that functioned like what you're proposing? Destroy walls, windows, doors but not floors? That would _actually_ add a new balance lever. For example X4 would become 0/0/2/5, syndiebomb might be 3/9/9/17, etc.

**Comment by GuillaumePrata** [comment]
> What if there was a 4th radius for explosions that functioned like what you're proposing? Destroy walls, windows, doors but not floors? That would actually add a new balance lever. For example X4 would become 0/0/2/5, syndiebomb might be 3/9/9/17, etc.

We would need to edit 200+ files for what? To keep heavy and devastation damage being the same towards floor tiles 90% of the time?
What is the point of having both "Destroy floor tiles 100% of the time" and "Destroy floor tiles 90+% of the time"?

**Comment by msgerbs** [comment]
Heavy damage doesn't gib people, at least I don't think it does. That at least makes it different from devastation.

**Comment by GuillaumePrata** [comment]
> Heavy damage doesn't gib people, at least I don't think it does. That at least makes it different from devastation.

If you're going to the effort of editing 200+ files to add an option of "Breach with Gib" and "Breach without Gib" it would be better take the extra step and change explosives to have a Gib range, Breach range and Damage range.

**Comment by LarissaMayrink** [comment]
> Why should we ignore poorly designed features and just throw the issue on the lap of admins when we can fix it code wise? Having a granular system for explosions just benefits every server and future developer that works with explosives.

how is having a 11tc item making damage that takes a minute to fix bad design? you're just complaining of the unwillingness of lowrp players to do their jobs

**Comment by msgerbs** [comment]
> > Heavy damage doesn't gib people, at least I don't think it does. That at least makes it different from devastation.
> 
> If we are editing 200+ files to add an option of "Breach with Gib" and "Breach without Gib" it would be better take the extra step and change explosives to have a Gib range, Breach range and Damage range.

Yeah, I don't disagree. It would be better.

**Comment by GuillaumePrata** [comment]
> how is having a 11tc item making damage that takes a minute to fix bad design?

I'm talking about devastate and heavy damage being the same 90% of the time.

**Comment by Kapu1178** [comment]
good pr

**Comment by itseasytosee** [comment]
Making syndie bombs devastating would make them exceptionally lethal, especially with quick detonations.

**Comment by Dorsisdwarf** [comment]
Can the post include before and afters of syndie bomb detonations in a couple of areas? I've never, ever seen a syndiebomb delete 225 floor tiles, they're usually like, 20 or 30 or so

**Comment by Mothblocks** [comment]
> While I agree with you, there are smarter ways to make explosions threatening and engaging than instant hole on the floor that is an early shuttle call on most shifts.

THE👏PROBLEM👏IS👏RECONSTRUCTION👏NOT👏BREACHES

IF NOBODY FIXES BREACHES BECAUSE THEY ARE ANNOYING TO FIX THAT IS THE PROBLEM NOT EXPLOSIONS

**Review by MrMelbert — COMMENTED** [review]
I think this PR needs demo pictures of what explosions look like with this pr

Just reading the code it seems like this removes a lot of aesthetic from explosions - no tier of severity will leave behind just lattice, so instead of blending from space -> lattice -> floor it'll just be space -> floor.

**Comment by GuillaumePrata** [comment]
> I think this PR needs demo pictures of what explosions look like with this pr

Added them.

**Comment by msgerbs** [comment]
Heavy should at least destroy the tiles completely (leaving the plating underneath) with more regularity so the damage to the floor matches better with the damage to everything else.

**Comment by GuillaumePrata** [comment]
> THE👏PROBLEM👏IS👏RECONSTRUCTION👏NOT👏BREACHES

IF NOBODY FIXES BREACHES BECAUSE THEY ARE ANNOYING TO FIX THAT IS THE PROBLEM NOT EXPLOSIONS

I agree that fixing breaches is annoying and boring but we just can't make them be interesting, it will always be "Click the space tile and it is a floor tile now" either by using rods + tiles, RCD or a future RAT.

Now what is fun about reconstruction is what comes after you fixed the floor as it goes different from player to player and round to round.
1- You can flex your map knowledge and rebuild everything the same way it was.
2- You can do the bare minimum and move to another area, leaving people to deal with a half build medbay as an example.
3- You can flex your creative muscles and build an improved version of what exploded.
4- You can do a gimmick, enjoy your bananium medbay doctors!

This PR just skipped the boring part and would *hopefully* make engineers be more willingly to do repairs.
No one wants to click 50+ space tiles because it is a chore, we are not a Clicker game, we are not a Chinese mobile game, we shouldn't force our players to do something mind numbly boring first so they can have fun later.

**Comment by Mothblocks** [comment]
> I agree that fixing breaches is annoying and boring but we just can't make them be interesting, it will always be "Click the space tile and it is a floor tile now" either by using rods + tiles, RCD or a future RAT.

Your creativity is dangerously lacking

**Comment by GuillaumePrata** [comment]
> Heavy should at least destroy the tiles completely (leaving the plating underneath) with more regularity so the damage to the floor matches better with the damage to everything else.

Yes, I fixed this and was looking on why pipes can break under surviving floor tiles but this PR went way out of scope, I already spend hours fiddling with explosion, floor and pipe code and I just don't want to spend more hours on this project this week.

I might tackle this again in another cleaner PR.

**Comment by GuillaumePrata** [comment]
> Your creativity is dangerously lacking

Feel free to come up with a creative way to turn a space tile into a floor tile then that isn't "Click with the mouse once" or giving every engineer 20 foam grenades, I'm looking forward to it.

**Comment by Mothblocks** [comment]
Make refilling a room with atmos not require rebuilding every pipe and making sure the distribution is set up in a way that eliminates 99% of people from ever doing it

**Comment by GuillaumePrata** [comment]
Why? Rebuilding pipes and refilling a room are interactive and actually fun now that smart pipes exist.
Each room has different pipe footprints that you need to link with your new pipeline, you can opt to use canisters, space heaters, crystal grenades, etc.

It's not even what I touched in this PR either, my issue is with the chore non gameplay of turning a space tile into a floor tile.

**Comment by itseasytosee** [comment]
The cold is the problem make space hot again!

**Comment by msgerbs** [comment]
The cold is both annoying and nonsensical. Space should drain the air, it should not magically cool the air that it hasn't drained.

**Comment by exymian** [comment]
yesterday i spent most of my round trying to fix a syndie bombed cargo and i couldnt even finish it, i am now convinced that manuel players dont even play the game. 

Reconstruction does suck but id say if the explosions arent that devastating then its acceptable.

**Comment by timothymtorres** [comment]
The problem is that the SM cooling loop uses space as a freezer.  Possible solution might be to restrict temperature from space tiles that transfer onto regular tiles.  We should only want the pressure to change, not the temperature.

**Comment by Jackal-boop** [comment]
Perhaps we could use reinforced floors across the station more? It's harder for them to get cold

**Pull request closed without merging**
