### PR TITLE
Engineering Market (IEVs) - Power, Atmos, Vendor ~ATOMIZED EDITION~

### PR DESCRIPTION
**Pull request by Robustin**
Atomization was creating a fuss and even though it would've been nice for a maintainer to suggest atomization in my design document thread or before I put 160 hours into the PR, I'm going to see this through.

This PR only contains the "market" items, power, atmos, and alarms - the infrastructure, no rewards.

The atmos system provides a rotating series of orders for custom canisters. The orders range from "Budget" which requires a simple mix within a modest temperature range to "Premium" which requires an advanced mix with extreme temperatures and pressures. The vouchers received for the canisters scales with difficulty.

The voucher manager collects the output of these auxiliary machines are exports them on an intergalactic energy market that exchanges energy and simple matter at FTL speeds. The nature of this market requires a non-traditional currency. Vouchers allow engineers to tap into this market to concentrate the vast amount of energy and matter available into a pre-set template of items, machines, and vehicles. 

The power exporter allows engineering to export surplus power.  The vouchers received for that power are a square root function (diminishing returns) that rewards high power output but without scaling getting too crazy. 

The alarm system provides periodic bonuses, but reduces or eliminates the bonus if too many air/power/fire alarms are detected.

🆑 Robustin
add: Added the Power Exporter, beam away power from the grid for Engineering points.
add: Added the Engineering Point Vendor, receive rewards that will be added in another PR. 
add: Added the Atmos Canister Exporter, receive points for filling a rotating set of orders of various difficulty.
/🆑

These are also the most tested and reviewed machines so hopefully there won't be much more reviewing required.

### CODE REVIEW

**Comment by jughu** [comment]
Inb4 ce be like every round
Lenald put plasma in the coolant

**Comment by coiax** [comment]
Sorry Robustin, but we can't merge this without rewards. HONK HONK HONK.

**Comment by Robustin** [comment]
*Honks despondently*

**Comment by MMMiracles** [comment]
Why do we need a point system for people to do their jobs? This kind of system just feels like a lazy way of making the department feel more fulfilling, rather than actually putting in actual content to keep engineers busy and actually doing their job.

Like, why even have Cargo for shipping/selling if we're just gonna go the route of these specialized per-department vending machines? Why not just make methods for departments to help cargo earn more credits so they in turn are much more willing to spend credits on the department? K'now, DEPARTMENT SYNERGY?

**Comment by kevinz000** [comment]
If anything I don't like it being a point system and a vendor.

**Comment by ExcessiveUseOfCobblestone** [comment]
I think Kor alluded to this, but what if some machines were better at higher power than others? Sorta like a RND upgrade but something RND can't put their slimy hands on

**Comment by Robustin** [comment]
1) This isnt a reward for doing your job. If it it was I would've added the alarm system, added the vendor, and called it a day.

2) The majority of points earned, if they are earned, is through utilizing the deep mechanics of engineering and atmos. These mechanics are some of the most complex in the game but are never leveraged because the most "good" you can accomplish is done with roundstart tools+RCD and the most "bad" you can accomplish is done by switching on 2 valves, stealing Tcomms parts, or breaking the SM 20 seconds into the round. 

There is a vast untapped system that is 100% without purpose. Your job as an atmosian is to maintain air and yet as long as you keep the mix pipe off theres a 0% chance you will be legitimately needed during the round. The only other dept. that can flood gas is science but their scrubbers are also stronger than anything else atmos gets so... they really don't have a purpose. Engineers can do a braindead SM setup within seconds of roundstart and keep the station powered indefinitely. There is 0 purpose to adding power above the station's very limited needs. 

As for the alerts, that is currently engineering's only "job" beyond not fucking up their own department. That's fine but currently sitting around waiting for someone to whine on the radio about a broken window or a bomb to go off is really unengaging gameplay, its purely reactionary, and even for Good Samaritans it is utterly dull. 

This gives Engineers something to do with their massive amount of downtime in a way that provides unique rewards that focus on being fun and rewarding, not like cargo/mining/genetics/chemistry/RND/robotics/xenobio/toxins where you are given rewards in the form of combat utility so you can valid your salads 100% faster. As a bonus it does give non-Samaritan engineers an incentive to leave engineering and fix power/atmos situations. 

Currently the state of engineer/atmos is awful. So many people commenting in my last PR have probably have engineering set to "NEVER" and have no sense for the state of the department. It's been an issue for years and I guarantee you that the actual players who select those roles will deeply appreciate something to add new mechanics and depth to their job.

**Comment by Robustin** [comment]
@kevinz000 

It's technically not a vendor anymore, its a computer and a delivery machine that tries to fit the lore of this being a market "woven into the station" and not just a Soda machine that poops out vehicles. As for points, everything uses points. Its just those points are called "Cash", "Symptoms", "Powers", "Minerals", "Slime Colors" they are all numerical outcomes gated behind RNG and its worked for almost every department since I started playing in 2010. It's not always perfect but its a way to say "Hey! Here's what you can do when people don't actively need your help, you spend time on this and you'll get something neat out of it!"

@ExcessiveUseOfCobblestone 

That creates a huge risk of the RND problem where we have to nerf machine's default state to accomodate their "high power" state. It also runs into a big overlap problem with RND since most machine upgrades already fall under their territory. It's an idea but I would need concrete concepts.

**Comment by optimumtact** [comment]
lol

**Comment by Iamgoofball** [comment]
would this be more acceptable if it tied into the station budget instead of engineering GBPs oranges?

**Comment by KorPhaeron** [comment]
Reopening PRs that just got rejected by a maintainer is poor form, appeal to @Cheridan if you want it reopened

**Comment by Iamgoofball** [comment]
He got told to atomize it by Cheridan's plant maintainer

**Comment by coiax** [comment]
Sorry @Robustin, the coderbus just hates you.

**Comment by Robustin** [comment]
>Get it closed by someone who isn't a maintainer shortly before testmerging
>Cheridan and his memetainer both tell me I need to atomize
>Jordie offers to help atomize but Oranges literally bullies them out of it
>Spend the entire day atomizing my PR
>LOL JK WERE GONNA CLOSE THE ATOMIZATIONS TOO

What the fuck

**Comment by coiax** [comment]
Hey @Cheridan reopen this plz.

**Comment by Robustin** [comment]
Kor thought Oranges closed my PR, when it was only the meme PR. I want off Coderbus's wild ride.

**Comment by juanototo2** [comment]
Listen, Cheridan. Keep the MR MAINTAINER'S WILD RIDE at least remotely sane and you won't have as much problems.

Is that too much to ask?

Also, Kor. Jesus christ have some fucking THOUGHT in actually pressing the "View changed files." button.
Like holy shit.

**Comment by optimumtact** [comment]
It's oranges

and b I didn't tell jordie to not help you he probably just didn't want to help you.

**Comment by Robustin** [comment]
Jordin volunteered to help so that would be weird,  whatever it's in the past now.

**Comment by Robustin** [comment]
Sooo, pretty quiet in this PR, the entire backbone for my system, really no thoughts about improving this?

**Comment by jughu** [comment]
Add a bycicle voucher to it for a million points 😄
Which gets you a free bycicle from cargo

**Comment by optimumtact** [comment]
I have a thought.

delete it

**Comment by Iamgoofball** [comment]
I already told you what to do last night

Do it

**Comment by kevinz000** [comment]
please no points system
i don't know why you think points is such a good thing to base it on
hell make it a fucking lathe that takes huge amounts of energy
make there be other benefits for the station for the other stuff
don't care what else but why do you want points so badly?

**Comment by Robustin** [comment]
Because part of this is atmos having something to do besides hope they get an antag roll. 

Part of this is making a strong incentive to minimize power and air alarms, again, power tracking does nothing there and I didn't want to create a system that encouraged people to never leave their dept. and do part of their actual job. 

I think the better question is why you're so up in arms about it. We haven't even tested it yet and despite every mechanic in this game being gated behind a effort+knowledge+RNG formula, this one is untenable to you. I could literally replace every single job progression mechanic in this game with a functional currency that would be indistinguishable from their current mechanic, the only difference is that some jobs are already well suited to RNG and there's no reason to change them, however this is a system and department that has no reason to depend on RNG for its rewards... congrats you exported a premium canister, rolling (weighted RNG mechanic ensues) REWARD: RAPID LIGHT GENERATOR. 

The moment I hear an alternative better than mine that rewards: 1) Engineering during a quiet round, 2) Atmos during a quiet round and 3) Both departments during a more chaotic round... I'm all ears.

**Comment by Robustin** [comment]
Closing so I can get my final PR into a mergable state, any remaining feedback is welcome there.

**Pull request closed without merging**
