### PR TITLE
helmet sprite update

### PR DESCRIPTION
**Pull request by ghost**
updates the normal grey helmet to have better shading (like the ausops bulletproof helmet)

also makes the visor lighter instead of darker blue, so HUDshades are more easily visible and stuff.

OLD / NEW
ss 2015-01-24 at 06 05 30

### CODE REVIEW

**Comment by as334** [comment]
Sprite wars, a new hope.

**Comment by paprka** [comment]
but the old sprites were mine too

**Comment by ike709** [comment]
Sprite Wars: Paprka Strikes Back

**Comment by paprka** [comment]
return of the grudgecoding

**Comment by Steelpoint** [comment]
Can we get rid of the small white dot in the centre of the sprite?

**Comment by Cheridan** [comment]
@Steelpoint what is lighting

**Comment by paprka** [comment]
it looks better from a distance to convey a sense of roundedness.

**Comment by Miauw62** [comment]
@Nienhaus @WJohn

**Comment by Lumipharon** [comment]
Woo, the grey rectangle is gone.

**Pull request merged**
