### PR TITLE
Alternative grille sprite update

### PR DESCRIPTION
**Pull request by psykzz**
Don't like the proposal in #32629, so my take on it.

image

Edit: Added a broken sprite
image
image

:cl: psykzz
imageadd: Grilles have new damaged and default sprites
/:cl:

### CODE REVIEW

**Comment by The-clown-known-as-Pepe** [comment]
bait pr name

was expecting hot girls

**Comment by uraniummeltdown** [comment]
Grilles sprites are still unequal, take pictures of the new grilles under single windows
From your picture grilles are still sticking out of windows awkwardly, look at the window under the man

**Comment by psykzz** [comment]
So sure, it hangs out a tiny bit, but the other proposal creates an even weirder experience when the grilles combine.

As im happy with it as it is now, i also added a damaged grill sprite, for under 50% integrity.
image
image

**Comment by psykzz** [comment]
@IconDiffBot do your thing

**Comment by RemieRichards** [comment]
he's a slowboi.

**Comment by MoreRobustThanYou** [comment]
I prefer the first one.

**Comment by Xhuis** [comment]
I like this more than the other change! The damaged sprite seems a little weird to me though; almost like you're carefully poking holes in it rather than actively trying to destroy it. I don't know of what else to use though.

**Comment by psykzz** [comment]
I agree it could use work, but the focus here was to just have the sprite in so that you could see the damage. Ideally i'd like to have 3 variations (maybe just rotations) so it keeps it a little random, but thats above what im able to do in this PR.

**Comment by WJohn** [comment]
Damaged sprite doesn't look spectacular, that definitely needs work. Otherwise this adds more crisscrossing which I suppose is nice.

Fix up the damaged sprites to have a gigantic hole in the middle or something to that effect, and I think it'd be pretty nice.

**Comment by psykzz** [comment]
@WJohn thoughts?
image

**Comment by ACCount12** [comment]
It's a damaged sprite, not a destroyed one, right?

**Comment by psykzz** [comment]
yeah

**Comment by psykzz** [comment]
Forgot to save the last design before moving on.
I made 4 varients that are just mostly rotations (although 4 actual images) 
image

**Comment by Bawhoppen** [comment]
@uraniummeltdown We use unequal sprites for stuff all the time. Look at floor tiles on their own some time and you'll see.

**Comment by ninjanomnom** [comment]
I can't unsee the damaged parts looking like dicks

**Comment by ACCount12** [comment]
@ninjanomnom what have you done to my perception

**Comment by AnonymousNow** [comment]
Better than what we have now, but I do like the first proposal's borders.

**Comment by psykzz** [comment]
If someone knows the right way to merge sprites to stop the border happening between two sprites then we can just add a border to these, otherwise we should just continue as we are now.

**Comment by WJohn** [comment]
Hole STILL needs to be bigger, psykzz. Check out our current grille damage, the hole is basically most of the entire grille gone. Leave only a few remaining strands, really-- barely able to hold onto itself, not multiple layers sticking together.

**Comment by DoctoreMad** [comment]
Guys, what?
This "damaged" isn't the one you know. This is a **new** one for when the grille is halfway damaged but not destroyed.
Currently we have two stages, "Grille is blocking passage", "Grille is not blocking passage due to damage".
After this update we will have "Grille is blocking passage and is undamaged", "Grille is blocking passage but is damaged", "Grille is not blocking passage".

**Comment by DoctoreMad** [comment]
@WJohn Post above is for you.

**Comment by WJohn** [comment]
Huh, I wasn't aware of that, that's good.

This can be merged then, though I'll let someone else clear if the code is good.

**Comment by duncathan** [comment]
Can we make grilles smooth so that we can give a good border?

**Comment by AnturK** [comment]
Actually, sorry i didn't realize grilles use horrible code to spawn copy of themselves for no real reason on breaking so this should work.

**Comment by Qustinnus** [comment]
making the VG grilles smooth would look about 10 times as good as this IMO

**Pull request merged**
