### PR TITLE
Reworks the mining resonator

### PR DESCRIPTION
**Pull request by ChangelingRain**
:cl: Joan
balance: Reworked the mining resonator: Resonator fields disappear after 5 seconds and will burst 1 second after being crossed or being placed on a mob.
rscadd: Resonator fields do increased damage and immediately burst if struck in the 1 second after being crossed or placed on a mob.
tweak: Resonator fields have animations showing when to strike: if the field is slowly expanding, hit it to cause it to burst for bonus damage. 
/:cl:

This thing sucks, but this should suck less and be more interactive.

For a simple explanation of how it works now:
You can place a field as a weak trap which does 20 damage if it bursts without being struck, or as a setup to go in and strike when a field is triggered and begins to expand, which does 60/80(normal/upgraded resonator) damage plus the resonator's 15.

### CODE REVIEW

**Comment by octareenroon91** [comment]
Can you reduce the resonator's click delay?

**Comment by ChangelingRain** [comment]
clicks in mining turfs are no longer slow as shit, but clicks that burst fields are still slow. it should overall feel better to use.

**Comment by Armhulen** [comment]
Make the trap instantly pop as soon as someone steps on it, it's 20 damage. Right now you're cruising on release crusher levels of gimmicky garbage

**Comment by ChangelingRain** [comment]
the point is you have to go in to get more damage; all mining mobs will remain on the field until it pops if they move onto it, though I'm pretty sure most megafauna won't, maybe barring colossus.

**Comment by Kromgar** [comment]
@ChangelingRain IS there any way to get a super resonator now other than the golem ore redemption machine?

I don't think you can make resonators at science anymore

**Comment by ChangelingRain** [comment]
I honestly don't know offhand.

**Comment by Hatfish** [comment]
@Kromgar You can still make them i

**Comment by Hatfish** [comment]
In R&D
>phoneposting

**Comment by GunHog** [comment]
Not once has a miner asked for one! I actually had to check the code to verify that the design even worked!

**Comment by KorPhaeron** [comment]
Does this need to be done? It works fine as a fast pickaxe replacement/is good for golems to use. Hell I'd rather just remove it from the station miners who clearly have no need for it and just keep it as a golem thing

Trying to make it viable for miners as a primary combat weapon vs the KA will just start an arms race between the crusher and the resonator

**Comment by ChangelingRain** [comment]
I'm trying more to make it fun/interactive, as trying to make three possible choices when one of them is the KA and can be modded/is literally the safest and most effective base tool would be silly.

I don't really expect it'll get used MORE, but people using it won't feel like they literally want to die.

**Comment by 4dplanner** [comment]
Honestly, I'd use it with this change - but alongside the KA for double power

**Comment by Bawhoppen** [comment]
Resonator is already best default mining tool, don't buff it even more

**Comment by KorPhaeron** [comment]
4dplanner has a good point, people will just use this in their offhand and spam fields if they dont have any need to time them

**Comment by ChangelingRain** [comment]
They do need to time them somewhat, as they don't usually last long enough that you can place them not directly adjacent to your target and still have them trigger.
Even then, you're doing like 20 damage if you don't go in, and I could definitely lower that.

**Comment by KorPhaeron** [comment]
@repukan @Kromgar you are the most active mining players on github what do you guys think

**Comment by Repukan** [comment]
Not everything needs to be equal/viable. You're better off making each fill it's niche better than just making them try to accomplish the same thing equally 👎

**Comment by adamkad1** [comment]
meh, i like that thing, would make golems decent vs all mining mobs off beggining (right now you need to beat legions to death with it cause its not easy to field them if you dont have a proper tunnel and goliaths is just placing field and waiting for it to go in. But with people seemingly complaining, mayby make something like this into mod system for resonator?

**Comment by ChangelingRain** [comment]
>You're better off making each fill it's niche better than just making them try to accomplish the same thing equally

What counts as trying to fill the niche? What IS the resonator's niche? From my point of view, I'm trying to do that!

**Comment by Repukan** [comment]
Resonator is better at mining high amount of tiles in short time. Maybe try adding a module upgrade by RnD that makes adjacent fields blow at the same time, and so on.

**Comment by ChangelingRain** [comment]
It's actually better at that now, since this makes its fields blow slightly faster(2 sec instead of 3/5 sec) than they did before.

It just happens to also work as a combat weapon at the same time.

**Comment by Repukan** [comment]
I think it would benefit from being a module system too rather than going to the old "super/hyper" ka thing

**Comment by ChangelingRain** [comment]
Well yeah, modules let you do way more cool stuff. They're also kind of out of scope of this PR, honestly...

**Comment by adamkad1** [comment]
also putting resonator in backpack now sets off a field on you

**Comment by KorPhaeron** [comment]
I would rather this stay kind of shitty and be a golem only thing, I dont think miners need two viable melee weapons that badly

**Comment by ChangelingRain** [comment]
it's not golem only though! @KorPhaeron can I reopen this if I DO make it golem only?

**Comment by Repukan** [comment]
Are you doing this for miners or for ghost roles

**Comment by ChangelingRain** [comment]
I'm doing this because it's ostensibly a weapon and I'd rather have it be, you know, actually a weapon, instead of a joke item that newbie miners get and then die with.
If such requires that I remove it FROM miners so it's golems/encounter with golems only, well, so be it.

**Comment by Repukan** [comment]
Newbie miners will die with a ka too because being new spells death as well. The main problem facing a drop in use in other weapons is that they're outclassed by either plasma cutters or proto kas.

If you want it to be more used then buff it's damage and activation or make it more modular based so it actually it's worthwhile to have one. Otherwise instead of solving the "this weapon is not used enough" or "new miners die with this" you'd only be net buffing golems (who get an advanced version with no effort.)

I guess I am just ranting at this point but no amount of buffing something will make newbies die less. That's a whole another thing and kinda the charm of lavaland.

**Comment by ChangelingRain** [comment]
If I'm going to add modules to it, I want it actually have GAMEPLAY first. That's this PR.

**Comment by Repukan** [comment]
But 👏 it 👏 has 👏 gameplay 👏

**Comment by ChangelingRain** [comment]
Really bad and unintuitive gameplay!

**Comment by Repukan** [comment]
Gameplay 👏 nonetheless 👏

**Pull request closed without merging**
