### PR TITLE
Makes blue cherry more blue

### PR DESCRIPTION
**Pull request by Jordie0608**
Because to be fair it was kinda a teal color really.
capture

### CODE REVIEW

**Comment by Bawhoppen** [comment]
my best friend :heart_decoration:

**Comment by WJohn** [comment]
n o n   i s s u e

But okay, whatever. :+1:

**Comment by Chocobro** [comment]
i intended it to be a very light (touching on grey) blue, on account of it being a mutated crop
but sure!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! don't ask me about my babies!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
:angry:

**Comment by Ricotez** [comment]
daba dee daba daa

**Pull request merged**
