### PR TITLE
Prescription hudglasses

### PR DESCRIPTION
**Pull request by Paxilmaniac**
## About The Pull Request
Adds prescription hudglasses, prescription glasses with a hud built into them.
image
These can be crafted similar to hudsunglasses.

## Why It's Good For The Game
You can already make hudsunglasses for all the main types of hud, meanwhile people with bad eyes don't get any options for eyewear than their glasses, so it made sense to allow them to have huds added.

## Changelog
:cl:
add: three types of prescription glasses with huds built into them, as well as a way to craft all three
/:cl:

### CODE REVIEW

**Comment by RandomGamer123** [comment]
at this point we'll actually get space ada soon

**Comment by Fikou** [comment]
the entire point of the nearsighted trait is that you cant use other glasses like huds without vision impairment, if you can just craft glasses its a free quirk for anyone except miners and engineers

**Comment by AlinaStarkova** [comment]
> 
> 
> the entire point of the nearsighted trait is that you cant use other glasses like huds without vision impairment, if you can just craft glasses its a free quirk for anyone except miners and engineers

the difference is that these are not flash protected, so while you can use the huds to actually be able to do your job you get no actual protection you would normally get from hudsunglasses

**Comment by GuillaumePrata** [comment]
> would normally get from hudsunglasses

That is only important for sec, other jobs shouldn't be balanced around sunglasses and we already have implants if you want your hud.

Being a doctor without hud because of your negative quirk is interesting, if you want the hud roundstart, just remove the negative quirk.

**Comment by RaveRadbury** [comment]
It's my understanding that you pick nearsighted as a quirk so you can't use anything other than prescription glasses without a penalty.

This is a balance change.

**Comment by AlinaStarkova** [comment]
> 
> 
> It's my understanding that you pick nearsighted as a quirk so you can't use anything other than prescription glasses without a penalty.
> 
> This is a balance change.

the problem is that it isnt just those with the quirk who need glasses, you CAN damage your eyes, either permanently or temporarily but long lasting, i once got blown up and my eyesight was blurry for 20 mins since no docs were around and nobody wanted to do surgery to replace my eyes.

maybe make it so you cant make hudglasses, you have to print them after researching a tech for it, that way you cant just instantly make them roundstart with the roundstart huds and glasses

**Comment by Mickyan** [comment]
To essentially merge together the advantages of two separate items should really take more than just tying them together with cable coil but there's precedent for it with sunglasses so I guess that ship has sailed

(they are both a bad though)

**Comment by LemonInTheDark** [comment]
I don't like this. If you make the choice/end up in a position where you need to wear prescription glasses, that should matter and impact your round past needing to combine them with your hud. They should be unique. 

Cacogen's right, sunglasses have the same issue, but they're too far gone

**Comment by AlinaStarkova** [comment]
> 
> 
> I don't like this. If you make the choice/end up in a position where you need to wear prescription glasses, that should matter and impact your round past needing to combine them with your hud. They should be unique.
> 
> Cacogen's right, sunglasses have the same issue, but they're too far gone

what if each dept. head had a pair so if your promoted to being head you can get the bonus of it, but they cannot be crafted and only one of their kind exists (kinda like how CMO starts with the belt defib and medimplant)

**Comment by LemonInTheDark** [comment]
If I'm honest I'm not sure there's any value to that, since they're a very rare usecase, unless this is a fashion statement or something.

Heads of staff aren't gonna be played by better players even if we give them  more loot, so I'm not sure there'd be any value in that avenue in the first place

**Comment by AlinaStarkova** [comment]
> 
> 
> If I'm honest I'm not sure there's any value to that, since they're a very rare usecase, unless this is a fashion statement or something.
> 
> Heads of staff aren't gonna be played by better players even if we give them more loot, so I'm not sure there'd be any value in that avenue in the first place

i was thinking these could be an alternative to hudsunglasses, the hudglasses DO look way nicer than normal huds, so this would be a better looking alternative to having hudsunglasses for medics for example. as only security and heads of staff should have access to flash protection, atleast easily. tbh i like these more for their aesthetic value than anything, even if the prescription part of it is removed

**Comment by oklews** [comment]
> the problem is that it isnt just those with the quirk who need glasses, you CAN damage your eyes, either permanently or temporarily but long lasting, i once got blown up and my eyesight was blurry for 20 mins since no docs were around and nobody wanted to do surgery to replace my eyes.

You shouldn't be able to just find another excuse to laugh at doctors, they should do more than just revive the dead. That'll just remove more substance from a job that is just tend wounds and defib.

**Comment by ExcessiveUseOfCobblestone** [comment]
Lemon is incorrect, sunglasses combining should definitely be more work than getting some cable coil l and I don't have to settle 😏

**Comment by LemonInTheDark** [comment]
Never said they shouldn't just don't have the time to change it.
Assert dominance, drive the sunglasses rushers out before you

**Comment by Mothblocks** [comment]
i agree with fikou

**Pull request closed without merging**
