### PR TITLE
Fix a dirtboy coder null pointer

### PR DESCRIPTION
**Pull request by Nirnael**
🆑 Nirnael
fix: Fixed a runtime relating to hygiene processing
/:cl:

This month:
> The following runtime has occurred 27201 time(s).
runtime error: Cannot execute null.adjust hygiene().
 proc name: attacked by (/mob/living/carbon/attacked_by)
 source file: carbon_defense.dm,98

Dirtyboy-meme coder forgot to assign a pointer.

### CODE REVIEW

**Comment by Qustinnus** [comment]
we dont have pointers in DM but thanks I couldnt find the file that did this

**Comment by fizzle7** [comment]
well...you know

**Review by Cyberboss — APPROVED** [review]

**Comment by optimumtact** [comment]
imagine not being able to find it

**Comment by Qustinnus** [comment]
i never said i looked very hard

**Comment by SpaceManiac** [comment]
speedmerging b/c obvious

**Comment by Cyberboss** [comment]
> imagine not being able to find it

> carbon_defense.dm

**Pull request merged**
