### PR TITLE
The light replacer can now consume glass shards

### PR DESCRIPTION
**Pull request by Mervill**
:cl: Mervill
add: The light replacer can now create bulbs from glass shards
add: Click a light replacer while holding a glass shard to add the shard to the replacer
add: Click a glass shard while holding a light replacer to consume the shard
/:cl:

_powercreep_

### CODE REVIEW

**Comment by RandomMarine** [comment]
Turning 2000cm glass into 25cm.

Power creep? More like huge fucking waste.

**Comment by Mervill** [comment]
Hmm. I suppose I could buff this considerably then

**Comment by XDTM** [comment]
Keep it wildly inefficient, though, since glass shards are very easy to obtain and autolathes are not.

By the way, you don't need to weld a glass shard to insert it into an autolathe, it's still worth 2000 glass even if you insert it as is.

**Comment by Shadowlight213** [comment]
Just make it count as a regular glass sheet since it holds the same material value.

**Comment by XDTM** [comment]
i never even knew you could just load it with glass

**Comment by Shadowlight213** [comment]
@XDTM that was the original way to refill it I think

**Comment by Mervill** [comment]
I'm thinking I'll make glass sheets and glass shards equivalent, since a shard can be turned to glass with a welder

**Comment by ExcessiveUseOfCobblestone** [comment]
Why not make it slightly less so you are encouraged to turn it into glass instead of keeping it as shards?

**Comment by Mervill** [comment]
ok

**Comment by Mervill** [comment]
Glass shards are now worth %75 precent of a glass sheet (currently 3)

**Pull request merged**
