### PR TITLE
Grill replaces second deep fryer, nerfs monkey energy

### PR DESCRIPTION
**Pull request by carlarctg**
## About The Pull Request

Adds grills to kitchens.
As punishment for @Fikou's hubris in adding inhands to it, i'm doing that and nerfing the monkey energy sprite by standarizing it with the rest of the soda cans in the vendor.

## Why It's Good For The Game

Grills are a good joke and are ordered very often, but that's really just due to it being a recent fun addition. I feel like over time it'll cease to be ordered and just sit there to be ordered once every 300 rounds, then forgotten.

So this PR adds them to the kitchen, making them a lot more common than just when a griller joins as QM
Plus, the original pr creator only didn't add them to kitchens because he was lazy.

## Changelog
:cl:
add: Grills are now available on the kitchen, replacing the secondary deep fryer.
imagedel: The intern that's been surrepitiously pouring Growth Serum into monkey energy cans has been fired.
/:cl:

### CODE REVIEW

**Comment by carlarctg** [comment]
fuck i fucked up the commit names

more maps coming

**Comment by lolman360** [comment]
i just want to for

**Comment by ArcaneMusic** [comment]
Hey, if you want to go the extra mile, Monkey Energy Drinks are missing a Crushed Can sprite as well (from using harm intent and clicking yourself aimed at head).

**Comment by nemvar** [comment]
Something is wrong with the delta station diff. Pls fix.

**Comment by carlarctg** [comment]
> Something is wrong with the delta station diff. Pls fix.

goddamnit. how do i revert that file?

**Comment by carlarctg** [comment]
monkey energy is now looks like grey bull because it is an energy drink

**Comment by optimumtact** [comment]
I'd prefer to leave them orderable so someone actually goes to cargo from time to time.

plus they’ve literally been in the game like 3 days, you don't have enough evidence to say that this is needed yet.

**Pull request closed without merging**
