### PR TITLE
Adds a sprite for the "quit vr" action button[cast ur mf votes inside]

### PR DESCRIPTION
**Pull request by MrDoomBringer**
for some reason there wasnt an icon for the "exit sleeper" action button, it was just using the default giant red "A" icon. this fixes that.

:cl: MrDoomBringer
imageadd: the VR sleeper action button has a sprite now
/:cl:

also: should i do something visually interesting like the one on the right, or something simple and slightly more clear like the one on the left? vote today
the two choices
THIRD CHALLENGER APPROACHES! howabout a power button?
third_challenger

### CODE REVIEW

**Comment by Armhulen** [comment]
RIGHT

**Comment by MrDoomBringer** [comment]
holy fucking merge branch 'master' batman

**Comment by Tayyyyyyy** [comment]
The left icon makes way more sense than the right

**Comment by davethwave** [comment]
I think the door looks better.

**Comment by epochayur** [comment]
left

**Comment by optimumtact** [comment]
the door is the obviously clearest

we don't want mystery meat navigation too much where icons are not exactly aligned with their purpose

**Comment by JStheguy** [comment]
Yeah, just go with the door, it's a clean and clear design, the IEC would be proud.

**Comment by Shadowflame909** [comment]
I really dig the brain. But yeah the door makes the most sense. If someone somehow causes problems in VR people can be like "literally click the door"

**Comment by newfren** [comment]
Power button > Door > Brain

**Comment by SpaceManiac** [comment]
All the sprites look good but the door is the most logical one.

**Comment by ma44** [comment]
>Tfw no voting via emotes

**Comment by Nabski89** [comment]
Brain!

**Comment by SpinnerMaster** [comment]
Power Button

**Review by SpaceManiac — APPROVED** [review]

**Comment by SpaceManiac** [comment]
The other sprites don't look terrible, maybe they can end up being used for something else, but the door is definitely clearest.

**Pull request merged**
