### PR TITLE
Adds miniature energy gun

### PR DESCRIPTION
**Pull request by Core0verload**
This PR adds a pistol-sized version of energy gun. It fits in pockets or boxes, has a smaller cell and fires taser shots instead of disabler beams. It also has a built-in gunlight that can't be removed.
guns
It's small cell limits it to 6 laser or 3 taser shots. Not enough to validhunt or stop grey tides, but enough to stop a clown from stealing your stuff, or to fight simple mobs such as carp.

It doesn't spawn anywhere yet, but I intend to make it a self-defense weapon for low pop CE/RD/CMO in upcoming PR.

### CODE REVIEW

**Comment by Shapsy** [comment]
Gun itself looks fine, but would you include the CE with the CMO and RD?

**Comment by Core0verload** [comment]
I just forgot to include CE in list. Fixed.

**Comment by TechnoAlchemisto** [comment]
Looks cool I like it

**Comment by Aloraydrel** [comment]
Looks nice

**Comment by Bawhoppen** [comment]
why does it fire taser instead of disabler

**Comment by Core0verload** [comment]
Because disabler sucks overall, and having even less shots with it? Fuck no.

**Comment by Bawhoppen** [comment]
I thought you'd have an actual argument because disablers are quite OP

**Comment by Core0verload** [comment]
Only if you have enough beams to disable-spam. If you don't, you are fucked.

**Comment by kevinz000** [comment]
RD used to have stun revolvers
*cries and looks at Kor*

**Comment by PKPenguin321** [comment]
2 taser shots would be better imo, 0 chance of lethal taze'n'lase that fits in your pocket that way

**Comment by Core0verload** [comment]
It's already 0 chance of taze'n'lase. After you fired a single taser shot, 1/3 of your power cell is gone, and you have only 4 lasers left. That's 80 damage, not even a crit. And that's only if your first shot made it to the target.

**Comment by Bawhoppen** [comment]
just make them miniature tasers than instead of even having a laser

**Comment by Core0verload** [comment]
Pure tasers are useless for wildlife encounters.

**Comment by Bawhoppen** [comment]
>WILDLIFE ENCOUNTERS

># WILDLIFE ENCOUNTERS

**Comment by Core0verload** [comment]
Ah, Bawhoppen, as helpful as ever. Now fuck off, I'm already sick of your bullshit.

**Comment by Bawhoppen** [comment]
>says Core0verload

**Comment by PKPenguin321** [comment]
Junglestation when

**Comment by Bawhoppen** [comment]
maybe hippie should just rebase with us those fuckers

**Comment by blobbernaut** [comment]
maybe you should rebase with hippie, HUH EVER THINK ABOUT THAT HUH

**Comment by RemieRichards** [comment]
@blobbernaut no cos you're the downstream here.

**Comment by blobbernaut** [comment]
join us instead remie we have danker memes

**Comment by PKPenguin321** [comment]
Take your dildos and get out reeeeeee

**Comment by blobbernaut** [comment]
those aren't even a thing anymore

**Comment by Man-Shroom-** [comment]
>taser shots

# Heavy breathing

**Comment by AdamElTablawy** [comment]
i feel like that's too many tazer shots

the ideal tazer shot amount is 0 and it should be at disablers instead

**Comment by Desucake** [comment]
I think this is a much needed defense for the more peaceful heads, to deal with any random greytider from breaking into their workplace, without needlessly killing or drugging them to death.

**Comment by PKPenguin321** [comment]
eh i mean its kinda powercreep though since that can already be done with telescopic batons

**Comment by Cheridan** [comment]
yeah as cancer as the current gun meta is (oh u dodged my 5 taser shots? lmao good thing i have 3 more tasers in my backpack) this is less cancer than stunlockascopic batons

**Pull request merged**
