### PR TITLE
Sentinel's compromise nerf

### PR DESCRIPTION
**Pull request by ghost**
Sentinel's compromise now returns 70% as toxin instead of 50% due to the easy treatability of toxin damage for ratvar's servants,

It also purges unholy as well as holy water for...obvious reasons.

:cl: Adam
tweak: Sentinel's compromise will return 70% of the healed damage as toxin damage, but also now purges unholy water.
/:cl:

### CODE REVIEW

**Comment by ChangelingRain** [comment]
This is 70%!

**Comment by AdamElTablawy** [comment]
whoops

**Comment by ChangelingRain** [comment]
Also given *how* they're healing it it might be a better idea to nerf that, because increasing the ratio doesn't do much if they still have the easy heal.

**Comment by AdamElTablawy** [comment]
I would but the thing is that I find sentinel's compromise is more often used in a fight to get someone up on the spot and have them keep coming while spamming the brute patches they misclicked and went into crit for.

Instead as this way, for one, they're going to be vomiting-AKA stunned-and not immediately back up in the fight tanking more damage until they go down again and get an easy heal. Instead, they'll still be extremely slow and while toxin damage heals when they're on brass tiles it heals slowly.

Altogether, this makes it less effective in the way that I want it to be. A cultist back at base surrounded by friendlies shouldn't die. But sentinel's compromise as a fast-invoke heal all brute patch sucks.

**Comment by ChangelingRain** [comment]
Maybe make sentinel's compromise stun(vomiting) if it heals more than X damage?

**Comment by ChangelingRain** [comment]
Anyway when I get back from :canada: i'm gonna reduce clockwork floor heal speed a bit and maybe make sentinel's compromise stun briefly

**Pull request closed without merging**
