### PR TITLE
Examine atmos machinery will tell the piping layer

### PR DESCRIPTION
**Pull request by Ghilker**
## About The Pull Request
Atmos component and the pipes will now tell on what piping layer they are on examine

## Why It's Good For The Game
Less pain when trying to understand the position just by the sprite

## Changelog
:cl:
qol: atmos components and pipes now show the piping layer on examine
/:cl:

### CODE REVIEW

**Comment by LemonInTheDark** [comment]
What does this look like in practice?

**Comment by Ghilker** [comment]
> What does this look like in practice?

Just a normal examine text nothing more, nothing less. I'm adding it because I feel that sometimes players can be confused by seeing a pipe on a different layer and is not clear on what it is, could be 2/4 or 1/5, so just shift click and see it for yourself

**Comment by LemonInTheDark** [comment]
How does it effect things like vents or the crystalizer? could you post an example printout?

**Comment by Ghilker** [comment]
Nothing much changes, this is how you see the examine 
image

**Pull request merged**
