### PR TITLE
More clockcult tweaks

### PR DESCRIPTION
**Pull request by ChangelingRain**
:cl: Joan
balance: Sentinel's Compromise now uses Vitality to heal, and healing done without enough Vitality will be much less effective, converting 75% of the damage healed to toxin damage.
tweak: Vitality is now tracked in the global alert.
balance: Vanguard now lasts for 25 seconds, from 20, and no longer stuns for double the time if a large amount of stuns were absorbed.
bugfix: Fixes Vanguard never stunning for more than 2 seconds.
balance: All cyborg Servants now have a cyborg fabricator, a ratvarian spear, and a normal, not-limited slab that has two cyborg-unique scriptures bound.
balance: Cyborg Servants can no longer bolt or unbolt doors.
balance: Cyborg Servants casting Geis will have bright purple eyes.
balance: Cyborg Servants are unable to recite several scriptures; Judicial Visor, Vanguard, Sigil of Submission, Wraith Spectacles, Replica Fabricator, Function Call, Fellowship Armory, and Memory Allocation.
wip: Of those, only Sigil of Submission and Memory Allocation are removed for balance reasons; the rest are either unusable by the cyborg or have a replacement scripture or tool.
bugfix: Fixes the Hierophant Network and Function Call action buttons lacking proper icons.
/:cl:

Cyborgs are rapidly losing a lot of tools so let's just make them actual Servants instead of super weak.
Also, I made scriptures that aren't yet unlocked due to tiers(or being a borg) have unusable buttons, because fancy.

### CODE REVIEW

**Comment by ChangelingRain** [comment]
I should never have closed all of these for one large PR why did I even think that'd help
@KorPhaeron @Xhuis hey

**Comment by Xhuis** [comment]
Geis was a huge issue, but as-is I think that live clockcult is much better with the merge and any further changes would fall into "changing the mode out of wanting to change it and not necessity."

I don't see a reason to merge this, but the final decision falls to Kor.

**Comment by ChangelingRain** [comment]
Well, Sentinel's Compromise doesn't really need the change, but cyborg servants kind of suck to play right now, or at least the ones that had most of their scriptures cut do, plus there's a couple of bugfixes.

**Comment by Xhuis** [comment]
Bugfixes could easily be put into their own PR. I view cyborg servants as very powerful already due to their inability to be stunned with tasers etc. and all-access; a single converted cyborg usually makes converting the AI a breeze, and so I think they're okay as-is.

**Comment by ChangelingRain** [comment]
I agree that they're powerful in that they're cyborgs with all access and such, but playing one doesn't feel like you're doing anything different from normal cyborgs unless you're a mediborg.

Like, I think it's a problem that they're the most reliable way to get the AI while being not particularly good for anything else, but I'm not entirely sure how to make it harder for a borg to get the AI and easier for the cult to get the AI without a borg.

**Comment by KorPhaeron** [comment]
@Xhuis @ChangelingRain 

Did you two ever come to any sort of understanding on whats going on with this

**Comment by ChangelingRain** [comment]
My take on it is that cyborg servants are cyborg first and servant second and that's where all the balance issues are coming from, since cyborgs are pretty dang strong, and cyborg servants get all the borg abilities without losing anything to get servant abilities.

I'm not sure what xhuis's take is on it, but it appears to be that he thinks borgs are fine because they're strong, and while I don't disagree that borgs are strong, I think they're strong in a way that they shouldn't be in this mode.
If it wasn't such a hamfisted solution, I'd make getting close to unconverted AIs just stun them/push them away from it or something similar.

**Comment by Xhuis** [comment]
My own opinion is that converted borgs serve primarily as cyborgs with some servant features added on, instead of primarily as servants with being a cyborg as a bonus. Both are strong in their own ways; my own personal opinion is that the one they're in now is fine.

**Comment by ChangelingRain** [comment]
I think that's why servant cyborgs are such a balance issue; they should be more difficult-to-stun servant and less one-way-trip-to-the-ai-core cyborg.

**Comment by KorPhaeron** [comment]
Flashing a single borg and then the round is over because there is an AI sat clockbase is pretty dull I agree

**Comment by Xhuis** [comment]
I do agree, but what does this PR do to fix that? They're still essentially an all-access pass with a snarky personality on wheels.

**Comment by ChangelingRain** [comment]
I'm reasonably sure it'd make borgs strong enough to do something like the previously stated hamfisted nerf.
Also, I'm not actually sure what to do for the nerf that's reasonable and preferably *not* that hamfisted.

**Comment by ChangelingRain** [comment]
So like, if either of you have ideas for making borgs worse at ai grabbing that isn't "they get automatically pushed away from unconverted AIs" please just say what your idea is.

**Comment by Xhuis** [comment]
I'm not really sure myself. If servanting borgs makes them immune to lockdowns and detonations, I think that making them non-immune to lockdowns but still undetonable might be a good solution; a fast AI can depower the airlocks on their satellite as the borg rushes to get them, and lock them down, giving the AI enough time to call for help.

**Comment by ChangelingRain** [comment]
unfortunately crude; that solution requires that the AI observe the borg and co before they get into the core, and in most cases by the time the AI knows something is off, they're already in the core(and, if competent, have disabled its APC) and it is thus probably fucked if they have a single servant's worth of conversion ability between them.

**Comment by optimumtact** [comment]
No maintainer is going to merge this while xhuis is overhauling clockcult with Kor's support

you should do the right thing and close your own clockcult rework pr's instead of making us go and get cheridan to agree to close them

**Comment by optimumtact** [comment]
stale ping for reopen etc etc, or make new pr bla bla you know what you did

**Comment by ChangelingRain** [comment]
@optimumtact neither of these are actually stale, they're both in a ready state

**Comment by ChangelingRain** [comment]
@optimumtact

**Comment by ChangelingRain** [comment]
@optimumtact

**Pull request closed without merging**
