### PR TITLE
Adds backpack shells

### PR DESCRIPTION
**Pull request by SmArtKar**
## About The Pull Request

Adds backpack shells. These are large shells that you can carry around on your back only, I think this is enough of a drawback. They also allow you to check whenever they are put on/taken off and get a ref of the wearer.

## Changelog
:cl:
expansion: Added backpack shells
/:cl:

### CODE REVIEW

**Comment by KittyNoodle** [comment]
This feels kinda useless, could be improved by adding storage space and triggers when something is added/removed. Putting a remote in your backpack currently serves the same function, however adding storage space and triggers based on that could allow for some pretty cool theft alarms.

**Comment by Mothblocks** [comment]
I agree with KittyNoodle, though at the same time adding storage makes it a bit confusing to put a circuit inside it, or to use a screwdriver on it. It's not unsolvable, but it'll be unintuitive.

**Review by Mothblocks — CHANGES_REQUESTED** [review]
You forgot to make it researchable, it looks like.

**Comment by Farquaar** [comment]
Great, and here I was thinking we would be making a turtle race that had a shell on its backslot.

**Comment by tohg7** [comment]
What if you could add an ID-lock shock component that's exclusive to backpack shells so anyone that tries to pick them up or open them without sliding your id through it to disable the shock component, gets shocked and hardstunned for a few seconds.

**Comment by Mothblocks** [comment]
circuit components should make clever use of their environment instead of unimaginative bespoke weapon components

**Comment by Mothblocks** [comment]
I'm going to pass on this for now, for the following reasons: I think you're going to need to make this more unique, I can't particularly find great use cases for this.

Making it a real backpack would be fine, but it would need to have right-click-screwdriver-deconstruction instead of the left-click it is now for normal shells, which might cause some problems in shell code (which is already getting large as is). Same with placing the integrated circuit, which I think would all feel very clunky and not particularly worth it.

**Comment by Mothblocks** [comment]
Normally I wouldn't just flat out close it for something like that, but we have 120 PRs as I speak and I want to clean up the tracker a bit 😄

**Pull request closed without merging**
