### PR TITLE
Removes anomaly cores from Cargo; they are now only available via the random events.

### PR DESCRIPTION
**Pull request by Iamgoofball**
## About The Pull Request

Removes anomaly cores from Cargo; they are now only available via the random events.

## Why It's Good For The Game

Players are reliably constructing the black hole gun and using it to delete the nuke during nuke ops. This is bad gameplay when it's happening every single round.. As such we're making anomaly cores only available via the event. This ensures that anomaly equipment can remain powerful without being a cause for concern when it comes to players optimizing the fun out of the game.

## Changelog

:cl:
balance: Removes anomaly cores from Cargo; they are now only available via the random events.
/:cl:

### CODE REVIEW

**Comment by Dawnseer** [comment]
I guess the Nukies could stop taking their sweet time if they give the crew enough time to make the gun.

**Comment by Metekillot** [comment]
How about increasing the cost to an obscene degree, or making availability randomly determined singular type of core?

Money talks!

**Comment by TheVekter** [comment]
I'm going to do an alternative after work that just removes some of the more rare ones from Cargo instead, I **really** don't think removing everything from cargo is necessary here.

**Comment by carlarctg** [comment]
one day goof will learn how to balance things without destroying everything

**Comment by necromanceranne** [comment]
For the love of god, goof, could you not have waited a few hours for vekter to do their own pr before you tried the thermonuclear method? 

I will literally kill the gun itself than let the only actual relevant contribution ordnance has to the game get thrown in the trash because of it.

**Comment by CopperCrow9** [comment]
Ordnance is never used as it is, and this just kills it and returns it to the old "If someone is in there and they aren't doing the gas tank experiment they're 100% bad and are gonna bomb the station" scenario. Also, people don't defuse anomalies as is. Also, if the main problem is the black hole gun just... maybe nerf it or throw a couple more cores as a requirement?

**Comment by TheVekter** [comment]
I asked goof to let me handle this and at least one maintainer has said they're not merging this, so I think everything will be okay

**Comment by Sadboysuss** [comment]
I think removing the individual core orders and instead making the order give you a random core would be a much better solution

**Comment by optimumtact** [comment]
You clearly didn't read the anomaly cores document, they are not a difficulty gate, they are a way to control how many of an item exists.

It is prevalent upon the person adding something to ensure that relevant difficulty and timegates are added.

Cores are not that mechanic.

**Comment by CCC23** [comment]
Skill issue

**Pull request closed without merging**
