### PR TITLE
Adds advanced mop inhand

### PR DESCRIPTION
**Pull request by ShizCalev**
Adds a new inhand for the advanced mop.
(It currently uses the regular mop one seen on the left)

3mwdmsy

### CODE REVIEW

**Comment by GunHog** [comment]
Yosh! That will do!

**Review by Cyberboss — APPROVED** [review]

**Comment by GunHog** [comment]
Are you remaking this?

**Comment by ShizCalev** [comment]
merged it into #29910

**Comment by ShizCalev** [comment]
@Cyberboss can you remove this from Sprites Needed and add #29910 instead

**Pull request closed without merging**
