### PR TITLE
Adds gorilla cubes to the uplink

### PR DESCRIPTION
**Pull request by 81Denton**
:cl: Denton
add: Geneticist and Chief Medical Officer traitors can now purchase a box of gorilla cubes for 8TC.
spellcheck: Changed the clown car uplink description to mention emag interaction.
/:cl:

It's like monkey cubes, except they rehydrate into big, angry gorillas. As a side effect, admins can now edit what mob gets spawned by messing with a monkey cube's `spawned_mob` var.

### CODE REVIEW

**Comment by 81Denton** [comment]
Oh hey, and here I thought I had it at 8TC already

**Comment by 81Denton** [comment]
>Why role-restrict these, though?

Genetics is the only real source of gorillas; it also makes sense to restrict them so A) players know who is to blame and B) they're not seen every single traitor round.

>So, how is this going to reflect on the magillitis injector

The injector is absolute trash, you either turn yourself into a simplemob or waste 15TC on turning someone else into a simplemob. These do neither.

**Comment by Barhandar** [comment]
>it also makes sense to restrict them so A) players know who is to blame 

But framing the geneticist for gorillas is good roleplay, while "there are gorillas on station, GENETICIST/CMO A TATERTOT" isn't. So I think "players know who is to blame" is _counter_point to role-restricting these.
>B) they're not seen every single traitor round.

How are gorillas any more potent than emag-ebow-esword or the syndie bundle?

**Comment by Therapist1** [comment]
You fucking did it, you absolute madman.

**Comment by Bawhoppen** [comment]
Clever change. :+1: 

Speaking of gorillas, do radstorms still turn all of genetics into a gorilla swarm?

**Comment by BebeYoshi** [comment]
I can now make gay cubes to spawn the g a y, good change

**Review by ShizCalev — APPROVED** [review]

**Comment by Tlaltecuhtli** [comment]
radstorms fuck  your dna but give you 0 radiations so no

**Comment by pubby** [comment]
Do cubes take like 30 seconds to activate or am I misremembering? It seems kinda weak to have to stand still for so long to get a single gorilla. And that gorilla will be hostile to you.

I kinda wonder if the injector should just be redesigned instead. Give it multiple uses, but have the chemical only affect monkeys. That would allow you to self-gorrila and create gorilla armies, but it would remove the ability to 1-click simplemob people (IMO an unfun feature).

**Comment by 81Denton** [comment]
@pubby They create gorillas/monkeys instantly, so you can drop one and spray it with a fire extinguisher.

I like your idea about the gorilla injector, that would make it a lot more fun than it is right now.

**Pull request merged**
