### PR TITLE
Replaces the engineering skillchip with a new blueprint multitool.

### PR DESCRIPTION
**Pull request by GuillaumePrata**
## About The Pull Request
Engineers, the Chief Engineer and the CE's locker won't spawn with the engineering skillchip anymore. Instead they have a blueprint multitool replacing the default on in their toolbelt/spawned inside the locker.

The multitool just reads basic wires like the skillchip did (Airlocks and APCs) and is medium sized.
blueeeebig
Yes, I just slapped a screen and the default Blueprint design into a default multitool as it makes it easier to understand how it works at a glance.

## Why It's Good For The Game
Skillchips are passive and "invisible", they work well on some situations but for the wire system it is a lot more beneficial to have a physical tool that new players can see on the world and shift click for details.

Stealing chips was something quite cumbersome, the new BP multitool stays as a medium sized item to change it from something annoying to steal/install but free to carry into something easy to do, as long as you have inventory space.

Another goal of the PR is that this add more granularity for tools outside of the power tools, a goal I want to keep working on over the next PRs by giving Engineers/Atmos Techs improved, but job content related versions of their basic tools.
With more tools, players can decide which version fits their goals on the shift, instead of the basic toolset inside a box helping them on everything that isn't forcing an airlock open.

## Changelog

:cl: Guillaume Prata
add: Engineers, the CE and the CE locker will spawn with a Blueprint Multitool. While holding it, players can see the effects of wires on airlocks and APCs, just like how their skillchip (which they don't spawn with anymore) used to work.
/:cl:

### CODE REVIEW

**Comment by Time-Green** [comment]
I’m really not a fan of this. Knowing all wires is an extremely strong power reserved for engineers who actually need it, but this just makes it another easily stealable meta gamer item

**Comment by Helg2** [comment]
Why wont you make something better than useless resprite of chips? Play a game, or something

**Comment by GuillaumePrata** [comment]
>  Knowing all wires

It is just Airlock and APCs, just like the old skillchip

**Comment by NamelessFairy** [comment]
Not a fan of this, imo this nerfs the station blueprints too hard as that are supposed to be the object you steal in order to see all wires without needing to kill someone. This is going to be on every engineer and its much easier to steal then a skillchip.

**Comment by GuillaumePrata** [comment]
> imo this nerfs the station blueprints too hard as that are supposed to be the object you steal in order to see all wires

Again, just airlock and APCS wires...

**Comment by Time-Green** [comment]
> > Knowing all wires
> 
> It is just Airlock and APCs, just like the old skillchip

The distinction is extremely minor and does not change my point. Knowing all airlock wires basically gives you all acces

**Comment by GuillaumePrata** [comment]
> The distinction is extremely minor

For antagonists that want to break into places instead of fix the station, yes. But it still confuses people reading the PR and why I wanted to clarify it.

**Comment by GuillaumePrata** [comment]
> Knowing all airlock wires basically gives you all acces

Knowing all wires costs 1 cerulean core at Xenobio so I don't see it as that big of a deal.

**Comment by Iamgoofball** [comment]
nerfs engineers and buffs greytiders

:-1:

**Comment by YakumoChen** [comment]
> > Knowing all airlock wires basically gives you all acces
> 
> Knowing all wires costs 1 cerulean core at Xenobio so I don't see it as that big of a deal.

That sounds like an oversight, not intended behaviour
You can't equate a niche science job with a large timesink to engineering anyway

**Comment by GuillaumePrata** [comment]
> That sounds like an oversight, not intended behaviour

No? It is literally a blueprint item.

> You can't equate a niche science job with a large timesink to engineering anyway

Now I don't even know what you mean with this.

**Comment by zxaber** [comment]
Xenobio is not a good anchor for balance discussions.

Does this at least fit in a toolbelt? It's hard enough getting engineers to go and fix things without them needing another bag space taken up.

**Comment by GuillaumePrata** [comment]
> Xenobio is not a good anchor for balance discussions.

That is a fair point, but it is something antagonists have access and never explore right now so I didn't consider it to be a balance issue.

> Does this at least fit in a toolbelt? 

Yes, like power tools, they are medium sized but fit on toolbelts, easy for engineers (and whoever has a toolbelt) to carry around while using 1/7th of someone's inventory without a toolbelt.

**Comment by YakumoChen** [comment]
> No? It is literally a blueprint item.

It existed far before blueprints had wire info and other functions, it's only intended use is to rename rooms (to make them usable from the xeno console)

**Comment by GuillaumePrata** [comment]
> It existed far before blueprints had wire info and other functions, it's only intended use is to rename rooms (to make them usable from the xeno console)

The PR was merged with that feature and has been used like this for years and years, I would consider it a core feature and only a PR reworking the xeno blueprints would change that.

**Comment by SkeletalElite** [comment]
can't wait to have grey tiders and antags murdering me to take my multitool

**Comment by Mothblocks** [comment]
I don't like this, it just feels a lot clunkier and the benefits are not obvious to me

> Skillchips are passive and "invisible", they work well on some situations but for the wire system it is a lot more beneficial to have a physical tool that new players can see on the world and shift click for details.

Teachability of skillchips is a separate issue that could be solved a few ways, like hover tooltips over the wire descriptions. What you have made is far less intuitive as now new players need to make sure they're using the right item that they've never seen before.

> Stealing chips was something quite cumbersome, the new BP multitool stays as a medium sized item to change it from something annoying to steal/install but free to carry into something easy to do, as long as you have inventory space.

Engineers already have plenty enough to steal

> Another goal of the PR is that this add more granularity for tools outside of the power tools, a goal I want to keep working on over the next PRs by giving Engineers/Atmos Techs improved, but job content related versions of their basic tools.
With more tools, players can decide which version fits their goals on the shift, instead of the basic toolset inside a box helping them on everything that isn't forcing an airlock open.

This sounds insanely clunky to me, especially given how horrible our construction tools in general are, and I would be impressed if you could make a PR with this concept that actually excites me

**Comment by GuillaumePrata** [comment]
> This sounds insanely clunky to me, especially given how horrible our construction tools in general are, and I would be impressed if you could make a PR with this concept that actually excites me. I want engineering to become drastically simpler

Just to clarify, the tools are meant to make things simpler, just like how this multitool worked by simplifying the skillchip system into a tool that works like the wire reading behavior we already have in game, holding a blueprint/abductor multitool while interacting with the airlock.

**Comment by Farquaar** [comment]
I don't like the change, but I like the sprite. Maybe there's room for a different kind of multitool upgrade in the future.

**Comment by Mothblocks** [comment]
yeah pop this in https://github.com/tgstation/SS13-sprites

**Pull request closed without merging**
