### PR TITLE
Allows admins to enable much more fully featured roleplaying

### PR DESCRIPTION
**Pull request by optimumtact**
This is closely aligned with a bay station style of play and would be
suitable for a server like manueal

## About The Pull Request
This enables fully immersive roleplaying as a global configuration option, so we can add bay station style code

hulk hogan exhorting his brothers to sell sell

### CODE REVIEW

**Comment by trollbreeder** [comment]
This is april fools prep isn't it?

**Comment by interestingusernam3** [comment]
oh no

**Comment by HomocidlePancakes** [comment]
I don’t get it.

**Comment by trollbreeder** [comment]
> I don’t get it.

<details>
  <summary>Spoiler warning: Explanation of PR</summary>
  It fully immerses everyone when this config is turned on. Being fully immersed means you have to manually blink and manually breathe in and out. The joke is that the baystation stereotype is one that reaaaallly loves roleplay, to the point of being ridiculous.
</details>

**Comment by cacogen** [comment]
11:30's a little early isn't it

**Comment by HomocidlePancakes** [comment]
Oh, that. I thought we already had it in config, but I guess it just was a funny button to press

**Comment by Timonkeyn** [comment]
manueal

**Comment by trollbreeder** [comment]
mister manwell

**Review by spookydonut — APPROVED** [review]

**Comment by Ryll-Ryll** [comment]
God that was probably the worst PR I've made

**Pull request closed without merging**
