### PR TITLE
Port of Blood'O'Matic bloodpacks vendomat

### PR DESCRIPTION
**Pull request by kopoba**
## About The Pull Request

So this is Blood'O'Matic vendomat that sell bloodpacks. Icons and description borrowed from TauCetiClassic project.
Mappers can use them to replace bloodpacks crates on maps or just add this vendomat somewhere. Salin glucose moved to Blood'O'Matic.

## Why It's Good For The Game
Blood is essential thingy and must be not obtainable that easy like sand on beach.
Makes medical department staff more important they have department discount on bloodpacks(easy to access by doctors and hard to access by greytide). This encourage people to play medical department i think. 
Blood loss traumas nowadays is deadly and very robust so blood vendomat will be popular. 
Choosing specific bloodpack in vendomat interface is more easy then crawling thru pile of bloodpacks on floor. 
Its increase aesthetic variety of specialized vendomats.
Boost up capitalism pressure in our arconomics making it more realistic(muh murica).
It can be refiled by refile cartridge that cargo can order this leads to more interactions between departments.
Prices adjusted to show how unique our species are in ss13 world(or how NT is racist against nonhumans).
Mappers now can add this vendomat to maps.

 

## Changelog

:cl:
add: Nanotrasen has developed new vendomat Blood'O'Matic. Vampires receive this news with delight!
fix: Bloodbags don't break vendomats interface.
qol: Crew have a shiny interface with listed named bloodbags that can be easily navigated.
/:cl:

### CODE REVIEW

**Comment by ArcaneMusic** [comment]
Do note: This means that blood will need to be purchased in department if stored this way. While it will be relatively cheap for medical crew, regular crew will have a steeper price to purchase blood for treatment purposes.

**Comment by Time-Green** [comment]
> Its better then just crate with bloodpacks.
I don't really see how this is better than a crate with bloodpacks. Blood is essential and putting it in an unmoving machine behind a pricetag instead of an incredibly easy to move and use crate doesn't really feel better

There's also plenty of times you dont need a whole bloodpack, and this just adds more litter since you can never put it back

**Comment by Time-Green** [comment]
> Its better then just crate with bloodpacks.

I don't really see how this is better than a crate with bloodpacks. Blood is essential and putting it in an unmoving machine behind a pricetag instead of an incredibly easy to move and use crate doesn't really feel better

There's also plenty of times you dont need a whole bloodpack, and this just adds more litter since you can never put it back

**Comment by rellyreri** [comment]
america

**Comment by TheBonded** [comment]
perhaps you could have both a blood freezer for roundstart blood packs, and a vendor as well for when medical runs out?

**Comment by tralezab** [comment]
Doctors gonna start charging me for what i use hahahahahahah

**Comment by tralezab** [comment]
AMERICA SIM

**Comment by MrDoomBringer** [comment]
not every mapped in item needs to be replaced with a vending machine

**Comment by ExcessiveUseOfCobblestone** [comment]
Your PR is missing proper format, an inappropriate title, or contains incorrect/missing information in your PR body.

Please look over your PR and make sure all items are filled out in a way that someone looking back years from now can easily access and understand.

_your why its good for the game is doodoo_

**Comment by ExcessiveUseOfCobblestone** [comment]
I'm not sold on this, It makes it more difficult to access necessary medical items versus say the medivend which is nice-to-haves

**Comment by newfren** [comment]
four hundred and sixty fucking credits for lizard blood? no thanks you get an iron pill and a slap on the ass on the way out

**Comment by kopoba** [comment]
> 
> 
> Your PR is missing proper format, an inappropriate title, or contains incorrect/missing information in your PR body.
> 
> Please look over your PR and make sure all items are filled out in a way that someone looking back years from now can easily access and understand.
> 
> _your why its good for the game is doodoo_

i changed description

**Comment by jughu** [comment]
> > Its better then just crate with bloodpacks.
> 
> I don't really see how this is better than a crate with bloodpacks. Blood is essential and putting it in an unmoving machine behind a pricetag instead of an incredibly easy to move and use crate doesn't really feel better
> 
> There's also plenty of times you dont need a whole bloodpack, and this just adds more litter since you can never put it back

Nobody will be bothered to put a blood bag back.
Vending machine can be moved with screwdriver wrench
Pricetag isnt that extreme for doctors, its not lile they dont pay for medvendor chemvendor anyways(why does doctors need to buy shit anyways cant this just be drained off the cmo's medical budget when it comes from a doctor, since the budgets are only used when purchasing shit from cargo and not vendors)



> I'm not sold on this, It makes it more difficult to access necessary medical items versus say the medivend which is nice-to-haves

The vendor does stand out more then the crate and is easier to notice then a freezer sticked somewhere on white.medbay flooring and you know immediatly that vendor has bloodbags

**Comment by InsaneRed** [comment]
completely useless pr that makes medicals job harder for no literal reason ((and for some reason the actual blood bags are still there in crates in MD freezers, so what is the point))

**Comment by kopoba** [comment]
Premium blood price was adjusted to be more afordable
image
image

I dont why it cost less on second screenshot economics is magic maybe some deflation in action.

**Comment by ExcessiveUseOfCobblestone** [comment]
> The vendor does stand out more then the crate and is easier to notice then a freezer sticked somewhere on white.medbay flooring and you know immediatly that vendor has bloodbags

You can change the sprite?

You’ll definitely know the bloodbag will have bags in it because people arent going to want to have to pay to give people proper treatment. Blood is the primary treatment for bloodloss, so there really should be no gating to it’s accessibility.

if the issue is it should be organized better, we can change it to a fridge instead.

**Comment by jughu** [comment]
Is it still possible for vendors to vend free stuff for x department personnel

**Comment by ArcaneMusic** [comment]
Keep in mind that currently this PR does not replace blood crates, only adding the blood-stocking vending machine, which would need to be purchased and built through cargo.

**Comment by MrDoomBringer** [comment]
> Mappers can use them to replace bloodpacks crates on maps or just add this vendomat somewhere

The intention of this PR was to have the possibility of replacing bloodcrates.
However, I would _really_ rather not replace cargo-ordering-bloodpacks with vending machines, so I'm still 👎 on having this machine exist at all.

**Comment by kopoba** [comment]
> 
> 
> The intention of this PR was (in part) to have the possibility of replacing bloodcrates in the future, which many people seem to have latched onto.
> I'm still against adding this machine in any case because it takes away from what cargo already does.

Cargo still have alternative option to fulfill blood shortage.
1. Buy Medical Vending Crate that Contains one NanoMed Plus refill, one NanoDrug Plus refill, one Blood'O'Matic refill and one wall-mounted NanoMed refill. (if this pr got merged adding NanoMed refill)
2. Buy Blood Pack Variety Crate that Contains ten different blood packs of blood to patients 1 of each type.

**Comment by ExcessiveUseOfCobblestone** [comment]
Make it a smartfridge instead and I’m on board.

don’t want blood to have a cost as it’s a primary treatment method for bloodloss

don’t want it to be refilled with a simple refill pack and want the ensure the ability to mislabel is retained.

**Comment by kopoba** [comment]
Sad

**Comment by ExcessiveUseOfCobblestone** [comment]
The smartfridge would make it nicer to organize still :waaa:

**Pull request closed without merging**
