### PR TITLE
North Star Large Fix Quantity (And Also Some Design)

### PR DESCRIPTION
**Pull request by Cheshify**
## About The Pull Request
aisat
carg

I was just going to fix the cargo shuttle but I noticed that there were more minor issues I could easily fix
- Opens the cargo bay up slightly
- fixes and reworks broken conveyors on the cargo shuttles
- moves a floating camera in atmos
- adds the correct exoscanner boards to the drone bay
- adds missing restaurant and bar portals
- gives the warden their desk and crew monitor
- gives virology more signage and the public quarantine room starts open
- gives medbay an organ storage fridge
- vault bolted roundstart
- AI upload bolted roundstart
- adds more monkey cubes to encourate alternate xenobio playstyle (specific goals instead of broad goals)
## Why It's Good For The Game
Well they're all just change to further make the map more enjoyable while staying in-line with design elements I had in mind.
- The big cargo ones just make it more streamlined for miners to interact with the station and fix some issues with the shuttle.
- Exoscanners having the right boards is good for that side content.
- Floating cameras are bad and ugly
- The warden having a front desk and crew monitor help them interact with both sec and the crew more often.
- Virology was apparently a little hard to find, and to further encourage people to use the public isolation room, it's shutters start up so people can see it.
- Medbay should probably have a place to store gibbed things.
- The xenobio changes are probably going to be the most controversial ones. XB is small, not to discourage it's use, but to encourage (experiment with?) an alternate style of play where xenobiologists target down specific slimes/crossbreeds and then move on to interact with the crew (whether that be antagonizing the crew, or helping them out with neat slime stuff). I think these changes can possibly remedy the issue of "wahh wahhh xenobio small" by making it more effective at it's intended alternate design. (random slime now a part of #75126)
## Changelog
:cl:
fix: The North Star's cargo shuttle has working conveyors.
fix: The North Star has had a slew of missing and improperly done content added and reworked, see the PR for more!
/:cl:

### CODE REVIEW

**Comment by Timonkeyn** [comment]
From what I can tell, the slime spawner can currently spawn the rainbow slime too if i am not mistaken. It is supposed to be a rare curated slime and as such it can spawn any extract, which would go against your design philosophy (on top of being supposed to be rarer than the other ones)

Also 3 monkey boxes is the most of any map(?)

**Comment by Cheshify** [comment]
Added some discussion in the thread but basically trying to make a T1 random slime spawner seems to be a little out of scope, so I've removed the random slime spawn for now. If anyone has any ideas on how to keep the design choice without altering code too much, I'd love to hear it.

**Comment by Cheshify** [comment]
#75126

**Review by Maurukas — CHANGES_REQUESTED** [review]
Your cargo shuttle docking port is broken:
image

Other than that I see no issues.

**Comment by Cheshify** [comment]
Update: I also redid the cargo shuttle AGAIN because it just wasn't as cool as I wanted it to be
aisat

**Comment by Cheshify** [comment]
Oh yeah the Dwidth issue was fixed as well

**Review by Maurukas — APPROVED** [review]

**Pull request merged**
