### PR TITLE
Moves "sprite accessories" (e.g. Hair, Undergarments, Mutant Bits) from `GLOB` to a subsystem

### PR DESCRIPTION
**Pull request by san7890**
## About The Pull Request

On the tin, basically demotes everything related to setting up and storing these bulky lists generated from reading `/datum/sprite_accessory` subtypes from living in a global space that will instead be in a compartmentalized subsystem for accesses.

## Why It's Good For The Game

Same exact expected results, just accessed in a different way.

image

There's a few reasons why I want this to happen.
* The `GLOB` space is too clogged. There are at least a thousand variables on `GLOB`, and it's extremely painful to access stuff on production/local through view variables when you're debugging stuff like this. It's also painful when there is stuff that _should_ live on `GLOB` that you might want to see in VV/Debugger but are forced to either have to scroll a mile to find what you want or wait a long while for it to load. The less bulky lists we have of stored initialized datums, the better.

* `make_datum_reference_lists()` is a consequence of wack stuff like this where we're reliant on certain things being initialized in the `GLOB` portion of world initialization _before_ subsystems/static variables load. Although we can't leverage this right now, making these subsystems allows us to give these a proper and set `INIT_ORDER` so it gets set up with the rest of everything else - most of these datum lists in the aforementioned proc doesn't _really_ need to be ready to go before `world.New()` for example.
  *  Caveat to this is that we still are reliant on this proc firing when it does as of the time of this PR and therefore can't do the subsystem `Initialize()` (could probably do this stuff on `PreInit()` but that feels like nasty work), the code is just structured like this in the "transitionary" period as I plan to move whatever is feasible out of this proc and elsewhere.

* We don't have to have the procs live in a global namespace either. Instead of passing in `GLOB.XList` or `SSstorage.XList` every single time, we can instead just move the proc setup on the subsystem and use `XList` in a more native fashion.

* It's easier to find what you need. To me, it's a lot nicer to ctrl+click the SS and go to the variables to find something I'm looking for instead of having to scavenge around for any footprint/trace of the global I want to look for. This is more trivial than the other two, but that's something I like to think about when I go to bed.

## Changelog

Not relevant

---

Also nothing should have broken but it's a good thing we have screenshot unit tests to prove me wrong.

### CODE REVIEW

**Comment by san7890** [comment]
@Cyberboss fyi

**Comment by Kapu1178** [comment]
You will never be able to put this inside of a subsystem really as players can open character creation before subsystem init.

**Comment by san7890** [comment]
True but we can probably just do a combo of set the init order to be as early as reasonable and then just prevent opening the menu for those few seconds (have a tgui alert explaining it)

**Comment by Kapu1178** [comment]
> True but we can probably just do a combo of set the init order to be as early as reasonable and then just prevent opening the menu for those few seconds (have a tgui alert explaining it)

But like, why? Nothing is actually practically gained by doing that, subsystem init is CHECK_TICK'd and all you're accomplishing is interrupting the player experience.

**Comment by san7890** [comment]
The prefs menu is already really laggy when you open it up during subsystem initialization (and might not even load well) - I sincerely doubt that putting a hold on it at the time when most players are downloading the rsc and reconnecting for the next round for a few seconds at most (or before the world even starts will genuinely matter in the long run

**Comment by san7890** [comment]
In fact we can even move the work to PreInit() on the SS and it wouldn't even matter in the first place but that feels ugly

**Review by ZephyrTFA — APPROVED** [review]

**Pull request closed without merging**
