### PR TITLE
Small map loader update

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
Reviving the old PR from lavaworld. It allows you to load smaller maps at a specific coordinate.

I had another proc that randomly seeded landmarks at set up then loaded maps to them as well, and I think something similar could be used by @Incoming5643 to fill the empty bits of space.

Remie told me to fix the as num thing for vars so I gotta do that as well.

### CODE REVIEW

**Comment by Incoming5643** [comment]
could definitely be useful

**Comment by WJohn** [comment]
Lavaworld is slowly but surely being made with this. Little bits and bobs of infrastructure's pretty neat.

**Comment by Dorsisdwarf** [comment]
I don't understand how this works. Is it ready, @KorPhaeron ?

**Comment by KorPhaeron** [comment]
@Dorsisdwarf 

More or less yeah

**Pull request merged**
