### PR TITLE
Bandolier quality of life and minor buff

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request

Gives the bandolier the ability to quick gather, adds .357 ammo to the items it can carry and increases the capacity from 18 to 24

## Why It's Good For The Game

The bandolier feels a bit underwhelming to use with how it currently is, Giving it quick gather and a higher carry capacity will make it worth the belt slot, Also carrying .357 on it for a revolver is cool.

## Changelog
:cl:

qol: Bandolier can quick gather items now.
balance: Bandolier capacity increased to 24 and can carry .357 ammo now.

/:cl:

### CODE REVIEW

**Comment by SkeletalElite** [comment]
Just so you know the trash bag was actually nerfed due to the ability to carry .357 shells on the belt slot because it enabled "trashbag gunslinging" where you could use the quick access belt hotkey to reload the .357 extremely quickly which negated the main downside of .357. Huge .357 buff

**Comment by starrm4nn** [comment]
> Just so you know the trash bag was actually nerfed due to the ability to carry .357 ammo on the belt slot because it enabled "trashbag gunslinging" where you could use the quick access belt hotkey to reload the .357 extremely quickly which negated the main downside of the revolver.

yeah but that's a trashbag, it wasn't meant to be a bandolier++, also the capacity is lower than the trashbag and its nowhere near the trashbag of holding, also reloading a .357 fast without a speedloader is achievable by dumping your box/smuggler's satchel in your backpack and using the bag hotkey

**Comment by jughu** [comment]
its belt for shotgun not communist gun

**Comment by Loafin34** [comment]
cowboy belt.... very cool

**Comment by starrm4nn** [comment]
> cowboy belt.... very cool

traitor cowboy rp upgraded

**Pull request merged**
