### PR TITLE
Ports Paradise error handler, with in game runtime viewer!

### PR DESCRIPTION
**Pull request by lzimann**
Ports ParadiseSS13/Paradise#4679 for in-game runtime viewer and error handler.
This also gets some code from d3athrow/vgstation13#10571

ss 2017-02-12 at 10 35 09

ss 2017-02-12 at 10 43 53

This also adds a `world.log` wrapper so everything is displayed both in DD window and the runtime file.

### CODE REVIEW

**Comment by MrStonedOne** [comment]
I need example runtime file output so i know if i have to change the log parser or the runtime condenser

**Comment by lzimann** [comment]
Yea hold on let me activate file logging here and get it for you.

**Comment by MrStonedOne** [comment]
oh ya, this seems to do a pretty decent change to runtime format over what they are now,

I'm not going to want to rewrite the runtime condenser to support it, so we'll just have to make it leave the normal runtime output alone

**Comment by MrStonedOne** [comment]
Oh hey! Now, what you actually do, is make it so log_runtimes doesn't change world.log (so that it always goes to DD)

log what ever fancy runtime you want to world.log, and only log the original format to the runtime file via a normal file handle (like dairy/the main log uses)

This way logging runtime's doesn't disable the output in DD.

**Comment by JamieH** [comment]
Holy shit, we were looking at porting this, thanks ❤

**Comment by AnturK** [comment]
Very nice.

**Comment by Cyberboss** [comment]
Memo for myself. #24075 Needs updating once this is merged

**Review by ChangelingRain — APPROVED** [review]

**Pull request merged**
