### PR TITLE
Improves hydroponics jumpsuit, apron and backpack colors

### PR DESCRIPTION
**Pull request by Oiobi7**
:cl: Oiobi7
imageadd: Botany clothing no longer sears your eyes with horrible neon hues.
/:cl:

Botany apparel has always been hideous compared to every other department's in my eyes, mostly due to being disgustingly oversaturated. This fixes that.

Comparison image
(Old human sprite and different backpack but the difference is still noticeable.)

### CODE REVIEW

**Comment by DaxDupont** [comment]
I love the bright colors, it fits botany well imo.

**Comment by WJohn** [comment]
Lower saturation is nice, but also try to fix some of the pillow shading (on the apron, most notable) and add some highlights, would you?

**Comment by Iatots** [comment]
Nature is colorful, that's why everyone and their mother oversaturates pictures of it. Don't fix what isn't broken.

**Comment by ExcessiveUseOfCobblestone** [comment]
this dreary color scheme accurately reflects what happened to me and other cozy ~~kudzu spammers~~ botanists after powergamers wanted to make botany quote "not boring".

**Comment by zamolxius** [comment]
looks dirty

**Review by SpaceManiac — APPROVED** [review]
Fix conflicts

**Comment by KorPhaeron** [comment]
Let me know if you fix this

**Pull request closed without merging**
