### PR TITLE
Tgui input checkboxes

### PR DESCRIPTION
**Pull request by jlsnow301**
## About The Pull Request
A request from @NamelessFairy: A tgui window that gives the user multiple items to select. The window returns the list of items selected.

The ui design is open to critique, reviews, etc. Pretty simplistic.
Screenshot 2023-04-07 174056

## Why It's Good For The Game
Sequentially asking yes/no is pretty ugly
## Changelog
:cl:
ui: Adds a new tgui input window for checkboxes.
/:cl:

### CODE REVIEW

**Comment by san7890** [comment]
if you could fit in an arg that only allows a set number of inputs (e.g. maximum of three inputs out of five options) and have the other buttons grey out when that threshold is met that would be fantastic

**Comment by jlsnow301** [comment]
> if you could fit in an arg that only allows a set number of inputs (e.g. maximum of three inputs out of five options) and have the other buttons grey out when that threshold is met that would be fantastic

This is now implemented

**Comment by stylemistake** [comment]
fluid?

**Comment by jlsnow301** [comment]
> fluid?

wym?

**Comment by Watermelon914** [comment]
> > fluid?
> 
> wym?

the checkbox buttons should probably be fluid and fill up the entire horizontal width

**Review by stylemistake — APPROVED** [review]

**Pull request merged**
