### PR TITLE
RLD and RCD fixes

### PR DESCRIPTION
**Pull request by Robustin**
1) Test code for hours until its 100% bugproof

2) Maintainers eviscerate my code for week, eventually stop testing and just blindly follow

3) Code is now more elegant but completely broken

4) Now I can fix the bugs added by the reviews more effectively thanks to the reviews

### CODE REVIEW

**Comment by coiax** [comment]
Robustin, you need to learn how to rebase and squash your commits. It would also be helpful if you said what you were fixing.

**Comment by coiax** [comment]
You've got 36 commits for 12 lines of diff, Robustin.

**Comment by Robustin** [comment]
Next time fam I promise

**Comment by coiax** [comment]
BUT WHAT ARE YOU FIXING

**Pull request closed without merging**
