### PR TITLE
Removes modular DOOM armor, resprites DOOM armor and 3 other armors

### PR DESCRIPTION
**Pull request by githubuser4141**
## About The Pull Request

Removes the modular variants of DOOM armor (doom armor plates, head, visor, detail) and replaces it with a regular non-modular armor sprite. Resprites 3 other armors: berzerker (space marine), adamantine and godslayer.

## Why It's Good For The Game

Better sprites! I'm unsure if the DOOM armor changes are wanted so I'll cut that out if people aren't happy.
image

## Changelog

:cl: sprites by INFRARED_BARON
del: Removes modular/GAGS sprites for DOOM armor
image: Resprites godslayer, DOOM, berzerker and adamantine armors.
/:cl:

### CODE REVIEW

**Comment by Sadboysuss** [comment]
adamantine armor kinda looks like diamond armor, other than that - I really like it.

**Comment by Fikou** [comment]
> adamantine armor kinda looks like diamond armor, other than that - I really like it.

our adamantine looks way closer to the blue in that armor than the blue in the current armor

**Comment by githubuser4141** [comment]
> why make the HECK suit not colorable anymore? And why does the godslayer armor have wood growing out of it?

That's how spriter did it, it's a tad odd that only the HECK armor is modular and none of the others are. Godslayer armor is supposed to be half composed out of the megafauna's flesh

**Comment by improvedname** [comment]
atleast make the doom ones gag

**Comment by githubuser4141** [comment]
> atleast make the doom ones gag

well, spriter said it'd not look good - so I'll wait for a sprite authority to have their say

**Comment by Jacquerel** [comment]
Like I said on Discord I really don't like how explicitly "this is the DOOM armour" that changed suit is.  
The rest are improvements. I think the wendigo flesh on the godslayer armour is cool.

**Comment by githubuser4141** [comment]
> Like I said on Discord I really don't like how explicitly "this is the DOOM armour" that changed suit is. The rest are improvements. I think the wendigo flesh on the godslayer armour is cool.

Mh, got any suggestions for how/what it should be changed or represent?

**Comment by rasepretep** [comment]
HECK suit looked heckin' cool with the black and red color scheme. The new one makes it look like the bobblehead from Doom 2016, it's just goofy. And calling it DOOM armor is just a bit too on the nose, innit?

**Comment by Blacklist897** [comment]
the heck suit is washed out and looks like its made out of foam
you are removing armor that was a reference but looked unique in favor of just the armor from doom
the berserker hardsuit looks baller but i dont see how the icemoon one relates to ice moon

**Comment by Razurath** [comment]
The godslayer armor is made of brass alloy, crystalline ice, and reinforced with the magic infused wendigo skull. It's not a half metal, half flesh thing with the worst helmet I've ever seen. Maybe give the godslayer armor a better helmet, maybe based around the wendigo skull with antlers, and make it more slim since it doesn't need to be bulky, but don't turn it into that. Please.

**Comment by LePiromano** [comment]
i like the general knight idea of the godslayer armor but it would be cool to see more of the components used to make it on the sprite, outright removing the modular spraycan-able pieces off the hecksuit removes a part of what makes the suit special, but i kinda do like this new doom slayer suit, the other 2 are pretty much perfect imo

**Pull request closed without merging**
