### PR TITLE
Adds eyeball soup and spaghetti to the game: not feature frozen edition

### PR DESCRIPTION
**Pull request by harmonyn**
A request by FantasticFwoosh, just in (early) time for space halloween. What it adds: something to do with all the eyes from assistant suicides, making the players feel heard

spaghetti

### CODE REVIEW

**Comment by RandomMarine** [comment]
Just like brain-based foods have mannitol, these should have some oculine.

**Comment by Bawhoppen** [comment]
WAIT
DO FLOATING EYEBALLS DROP EYES AS LOOT OR NOT 

BECAUSE THEY SHOULD

**Comment by coiax** [comment]
Frozen because you opened it in the freeze.

**Comment by FantasticFwoosh** [comment]
Im pretty sure they would only drop 1 eye @Bawhoppen, them having loot would be nicer than just dissapearing. Unless you want to go full reference and have them drop copper silver or gold coins.

Time to implant a cycloptic eye into your forehead.

**Comment by KorPhaeron** [comment]
PRs that violated the freeze have to wait a week longer to be PRd or else people will keep opening their feature PRs during freezes

**Comment by FantasticFwoosh** [comment]
This was made 7 hours ago, while the freeze was lifted in IRC more than 12 hours ago (i know, i was there) and isn't a re-opening of a mid freeze feature. What?

**Comment by KorPhaeron** [comment]
They recreated the PR

**Comment by bgobandit** [comment]
ok kor I know you have some sort of vendetta against me for some inexplicable reason, but seriously, what the fuck

**Comment by KorPhaeron** [comment]
You caught me, I closed a dozen other PRs by half a dozen other people for the exact same reason just so I'd have plausible deniability to irritate you.

I also talked about doing this weeks ago in coderbus to @optimumtact before you'd even opened this PR because I play the long game

**Comment by coiax** [comment]
Man Kor, you're such a smart villan.

**Comment by optimumtact** [comment]
lol

**Pull request closed without merging**
