### PR TITLE
Soulifies hygienebots by giving them several voicelines. (Feat. SovietWomble)

### PR DESCRIPTION
**Pull request by dopamiin0**
## About The Pull Request

The medbots had it too good for too long.
Fully voices every single hygienebot line. Voices done by the man himself SovietWomble.
image
Total size of all the voicelines put together is about ~280KB. I hope that's alright? If not, let me know what an appropriate size would be. Quality is fine at the moment.

## Why It's Good For The Game
https://user-images.githubusercontent.com/112458553/209766362-db9f51cb-e368-4b62-b606-0c10d1874aa1.mp4

## Changelog
:cl: SovietWomble, dessysalta, dopamiin
soundadd: the hygienebots speak now
/:cl:

### CODE REVIEW

**Comment by dessysalta** [comment]
Helping make this was a blast, and a huge thank you to dopa and SovietWomble for humoring me on this project. Hope this gets merged quick!

**Comment by castawaynont** [comment]
nice!

**Comment by dopamiin0** [comment]
i am frankly not certain why this has failed, can someone smarter than me tell me if this is an issue and if so what i did wrong

**Comment by JohnFulpWillard** [comment]
It's not your fault and you can ignore it

**Comment by Wallemations** [comment]
Imo the voice could use some sort of subtle robotic filter

**Comment by ArthuroPep** [comment]
I agree with Wallemations, this needs some robotic filter

**Comment by Mothblocks** [comment]
this seems like a huge downgrade tbqh, giving them an actual audible voice is way too cheesy

**Comment by Mothblocks** [comment]
would need to be on the same level as beepsky where you cant even tell its a human (cuz its not)

**Comment by Sealed101** [comment]
i love how the high pitched beep kind of censors _fucking_
giving it an actual voice could be a good leeway for adding wires/access panel stuff to it to toggle aggressiveness and the voice itself or more

**Comment by Draggeru** [comment]
I 100% approve of this and it very much should be speed merged

**Comment by dessysalta** [comment]
> would need to be on the same level as beepsky where you cant even tell its a human (cuz its not)

I had a few ideas for voice effects, but dopa used the original unedited files "because it's funnier". 

That being said, I planned from the start to only have the filter be part of the voice, not all of it--it defeats the purpose of having Soviet voice it if most of his voice is drowned out by filters. Kind of like Big Band from Skullgirls, if you're familiar, who was given a very slick and slight robotic tinge to sell the main voice actor rather than risk butchering his voice for the sake of style points.

I'll see if I can't make a video that features a voice with a filter on it in a bit. I'm headed back to sleep for a couple hours before I do anything.

**Comment by dessysalta** [comment]
Here's some of the iterations I went through, from least to most robotic. I was thinking something like the Working Joes from Alien: Isolation. Do keep in mind that I chose to use the more emotional lines Soviet sent me because I figured the anger warranted it (plus, it's what initially drew me to him). 

https://user-images.githubusercontent.com/117083785/209850096-fdfaf915-a322-44c4-bd96-9f3fd514dc1e.mp4

And the low emotion variants (tell me which of these sounds better both in tone and in effects):

https://user-images.githubusercontent.com/117083785/209851600-bc1863d4-33b3-4089-b0ef-718d9bd11b8d.mp4

**Comment by skylord-a52** [comment]
I like the slight tube sound on the first robot edits (is that a minor bitcrush? just eq?), but I think the amplitude modulation on the later ones is a bit too much. I would recommend instead a bit of bitcrush, and potentially something pitch-altering -- heavy autotune or light vocoding might give a good effect here.

**Comment by Jezzared** [comment]
My vote is the first iteration for normal lines and the really crunchy filtered ones for angry bots. Really lends it that sense of the hygienebot being slightly unhinged.

**Comment by MrDoomBringer** [comment]
that sovietwomble knows about ss13 is crazy
cool and soulful change

**Comment by dopamiin0** [comment]
updated all the voicelines. total size increased by a bit.
image
the two nice lines now have a faint robotic tinge, as if pre-recorded and played through a shitty speaker. similar to the very beginning of highemotion video.
all the other lines have heavy distorted robotic filtering, like at 41 seconds in dessysalta's highemotion video posted above. 

hope this is fine. if it isnt i will cry

**Comment by dessysalta** [comment]
Posting a video below soon.

**Comment by dessysalta** [comment]
womp
ignore the shitty quality i had to compress it + my PC is about as good as a strawberry connected to a power source
https://user-images.githubusercontent.com/117083785/210157827-105452e7-cfd4-4998-b0ae-a0e14f59eba7.mp4

**Comment by Jezzared** [comment]
Absolutely in love with this. Womble did a good job and i think the audio effects sell it hardcore.

**Comment by Toastgoats** [comment]
Incredibly based pr, can't wait to build 20 of them and make the server hate me

**Comment by Mothblocks** [comment]
the more i listen to this the more i think my biggest concern was that hes british

**Comment by Mothblocks** [comment]
...that being said a Human Ass voice still feels REALLY off.

**Comment by dessysalta** [comment]
> ...that being said a Human Ass voice still feels REALLY off.

I don't think either of us can say much to this, but I tried to come from my heart when I made this PR. Even if the human voice is a little off, I feel the tone and execution is halfway decent--and I think Soviet fits the bill perfectly. It's up to you whether or not it gets merged, but consider this the "pretty please" on my end.

**Comment by Jezzared** [comment]
I don't really think it's odd at all. It really seems to be a personal preference thing.

**Comment by tralezab** [comment]
i like it, mothblocks should try the one week in british isles challenge, lets merge

**Comment by Timberpoes** [comment]
Nothing wrong with a adding a little English to your stroke.

**Comment by jlsnow301** [comment]
wish this sounded slightly more robotic

**Pull request merged**
