### PR TITLE
Datum-Based Gangs [Ready]

### PR DESCRIPTION
**Pull request by Ikarrus**
A refactor of gangs to put each of the gangs into their own datum. Aside from cleaner code, this has a number of benefits, including **support for up to six gangs** (limited only by crayon colors).

Other changes include:
- (EXPERIMENTAL) Gang mode now has a chance to start with a third gang
- Reintroduction of promotions; Gangs only start with one boss again.
- Every lieutenant promoted will lengthen the gang's recruitment cooldowns by one minute
- Only gang bosses will be able to recall the shuttle from their gangtool.
- A recruitment pen that has not been used for a while will accumilate charges, so you are no longer punished for waiting to convert people.
- Fully functional gangs outside of gang mode
- Admins may add additional gangs to any round, including the martial gang

### CODE REVIEW

**Comment by Incoming5643** [comment]
Simultaneously more and less horrifying than I imagined

Fuck minds though.

**Comment by PKPenguin321** [comment]
>A recruitment pen that has not been used for a while will accumilate charges, so you are no longer punished for waiting to convert people.

you actually used my idea yay :smile:

**Comment by Lumipharon** [comment]
Cool stuff, but if you let pens accumulate (which is a good change probably) you might want to increase the charge time, since this will easily be a net buff to recruitment.

**Comment by Ikarrus** [comment]
That's the whole reason why pens cost 50 influence now. It's meant to speed up recruitment.

**Comment by Miauw62** [comment]
GANG SCALING WHEN

**Comment by Ikarrus** [comment]
That comes later, after a bit on hands-on testing with badminning

**Pull request merged**
