### PR TITLE
Restores NT logo for Loyalty Implants

### PR DESCRIPTION
**Pull request by Ikarrus**
And moves antagonist icons to the lower right corner.

space station 13 2015-07-13 201502

I didn't expect the original PR to be merged so fast and frankly I wasn't too fond of it.

### CODE REVIEW

**Comment by Incoming5643** [comment]
I couldn't tell you why, but my absolutely objective tastes are telling me it'd look better if the antag icon and the loyalty implant swapped corners.

Probably because I never play sec

**Comment by Ikarrus** [comment]
Everything else in the sec hud appears over the head so I figured it'd be better to group them together at the top.

**Comment by WJohn** [comment]
I actually rather like our new loyalty implant, as it saves on space. Give the players some time to adapt, they're always slow to like changes. In the meantime you could do stuff like changing chem and tracking implants to also be less intrusive.

**Comment by Cheridan** [comment]
I've seen lots of comments that they like the new one, and though of course I was partial to my sexy -N- I think it's better now.

**Comment by optimumtact** [comment]
I'm going to have to deny this as the lead designer.

The newer icon fits better with the new UI we will be rolling out in the coming months

**Comment by duncathan** [comment]
:-1:

**Comment by Steelpoint** [comment]
The icon gets distracting when your staring at it for the entire round, unless you take off your sec huds.

**Comment by Robustin** [comment]
I just love all the supershits here who never play security, who probably only saw it on the .gif attached to the original, and then they go on to lecture us "plebs" who actually play the damn game about whether it's good or not.

When you play sec in a busy brig, it's not fucking cool having HALF YOUR SCREEN FLASH AT YOU THE ENTIRE SHIFT. Stop subjecting people to something to awful changes because oh my god sometimes in .0001% of games you have cult, gangster nukeop sec officers and they had trouble seeing which of them was implanted.

**Comment by Ikarrus** [comment]
You would get better results without the hyperbole, robustin

**Comment by Steelpoint** [comment]
Robustin is correct though.

**Comment by Jalleo** [comment]
I prefer the change that occured to help save space

**Comment by CPTANT** [comment]
The flashing implant icon is horrible, this is fine.

**Comment by WJohn** [comment]
I think we could come to a happy medium, and instead removed the flashing effect in favor of just the blue outline.

**Comment by Steelpoint** [comment]
I don't see why the original N positioning was such a bad thing? 

Of all the things to change this was one of the last things that needed to change. 

If you want to make a pref option (which I predict is going to become a meme of "Make it a Pref!") then do that, but otherwise I personally think it ain't broke.

**Comment by Ikarrus** [comment]
@wjohn Would blend in too much with medical and command Huds

**Comment by phil235** [comment]
I'm with WJohn, the permanent blue outline would be fine, it doesn't obstruct the job icon that much.

**Comment by Jalleo** [comment]
Tbh i did suggest to lower the brightness of the flashing in the last PR WJohns idea can also work

**Comment by Supermichael777** [comment]
what about moving it under the sec logo to the left
it would fit in under the job indicator and would not have that jarring space like the sechuds designers intended for them to be worn by angtags

**Comment by Ikarrus** [comment]
@Supermichael777 That's where the arrest status goes

**Pull request closed without merging**
