### PR TITLE
Makes rainbowtide a config option.

### PR DESCRIPTION
**Pull request by MrsTonedOne**
Defaults to enabling rainbowtide, even if the config entry is absent from the config file.

I had to name it in a such a way that it it was a enabling a negative to have it make sense for a default of on even if absent from the config.

### CODE REVIEW

**Comment by RemieRichards** [comment]
Grey > Gray

**Comment by TZK13** [comment]
Grey is the standard with more than double the results for it when you search the code and grey tide is far more prevalent than gray tide, just look at the bar sign.

**Comment by RemieRichards** [comment]
Grey :gb: :gb: :gb: :gb: :gb: :gb: :gb:

**Comment by TZK13** [comment]
>No Canadian flag emoji.

The fuck is this.

**Comment by RemieRichards** [comment]
:maple_leaf:

**Comment by Cheridan** [comment]
@TZK13 The standard for creating config options is that the previous behavior is made the default.

**Comment by RemieRichards** [comment]
@Cheridan I believe TZK was talking about the word, not the actual option...

**Comment by TZK13** [comment]
Yeah what Remie said, I was only talking about the spelling standard.

**Comment by WJohn** [comment]
I am in support of this if only so we can return to grey.

**Comment by ike709** [comment]
:us: :us: :us: 
we need to Americanize this codebase
:us: :us: :us:

**Comment by PKPenguin321** [comment]
return of the tide 2k15

**Comment by paprka** [comment]
Nice grey tide meme mso upvoted m8 :+1:

**Comment by iamgoofballsecondfork** [comment]
t e s t
e
s
t

**Comment by GunHog** [comment]
GREY TIIIIIIIIIIIIIIIDE!

**Comment by Steelpoint** [comment]
:+1: 

Assistants just don't look right in coloured jumpsuits. Also the decrease in greytiding is due to a admin lead effort to cut it down, not due to coloured jumpsuits.

**Comment by paprka** [comment]
you're actually delusional if you don't think i didn't have a hand in all of this steelpoint, including the admins doing their job more and getting rid of particularly bad grey tiders

they'll act like i didn't of course, but making assistants rainbow tide went hand in hand with an administration ramp up towards assistant grief, months ago

**Comment by PKPenguin321** [comment]
i agree that greytide literally never happens and that's mostly definitely because of multicolored jumpsuits and random spawn points
but that has nothing to do with this pr

**Comment by MrStonedOne** [comment]
No, I was in admin bus when it happened. You, your prs, or graytiding as a word had nothing to do with the conversation. IT was strictly about line towing griffers, what made somebody a line towing griffer, and what options we had to solve the issue.

This was when it was decided to add that MOTD. Stop trying to make everything about you.

Odds are sos isn't going to even disable this config, meaning rainbow tide will live on at tg, but guess what:

/tg/Station 13 isn't the only server that runs this code base. Hence why we make things config options in the first place.

This is all besides the point, you literally are obsessed that a fucking color is going to turn people in to rabid lunatics. I read what you wrote on /vg/ about us all being man children, So I can see why you might think that we are, but that doesn't make it so.

**Comment by paprka** [comment]
Singular colors makes assistant more attractive because it's easier to be anonymous as a traitor.
Singular colors leads to mob mentality because there's usually a lot of assistants iwth the same jumpsuit.

You're dead wrong. These are facts, observed facts.

Don't get me wrong though, you can definitely just ban the retards that come out screaming GREY TIDE S BACK LOL GREEEY TIIIIDE!, but the reason I took action against this behavior with the jumpsuit colors was because the admins were doing NOTHING ABOUT IT on /tg/ or any other branch of /tg/. The admins didn't start to do anything until I've already made these changes, because instead of #yesallassistants it was a lot easier to observe players on a case-by-case basis since they're much easier to identify as 'that assistant in yellow/pink/blue' and see what their name is instead of the grey enigma you saw scurry out after stealing from medbay storage.

**Comment by PKPenguin321** [comment]
ok ok
please guys lets be friends here please
this is a bretty good config option, config options are bretty good
this is a good pr and we should use the comments to talk about the pr
config options
let's talk about those okay
**please**

**Comment by paprka** [comment]
But it's not, it just readds the potential for what is nothing but a problem for the game that I had to work on getting removed for a long while.

The only argument for this PR to exist or even get considered is the re-addition of epic maymays. Assistants can easily get a grey jumpsuit from the locker room if they like the jumpsuits. I added more variety to assistants as both an aesthetic thing, to break up the notion that they're a pseudo department, and to make them less attractive for antag rolling.

**Comment by MrStonedOne** [comment]
>This PR is essentially a butthurt baby revert PR
nope

Nice try, but nope.

>Absolutely pathetic.

Says the guy making fun of somebody getting molested

And the guy making fun of somebody trying to commit suicide.

Why are you still here?

**Comment by TheVekter** [comment]
@paprka Funfact! Greytide didn't get virtually eliminated because you put in random suits, it got eliminated because us admins busted our ass banning everyone who was fucking around like an idiot.

**Comment by MrStonedOne** [comment]
>Unlike you, I know what the fuck I'm talking about. I'm not even referring to the recent advent of the grey tide policy being in the MOTD, this was months and months ago when I removed the grey jumpsuits.

>I'm not even referring to the recent advent of the grey tide policy being in the MOTD, this was months and months ago when I removed the grey jumpsuits.

> the recent advent of the grey tide policy being in the MOTD, 

>months and months ago when I removed the grey jumpsuits.

If removing graysuits was sooooooooooooo fucking effective, why did we have to make the policy?

**Comment by paprka** [comment]
Because of scaredy, basically

**Comment by Cheridan** [comment]
ironic pr lock :ice_cream:

**Comment by hornygranny** [comment]
:salt:

**Comment by RemieRichards** [comment]
The gates are ## <B>CLOSED</B>

**Comment by RemieRichards** [comment]
The gates are <B>CLO-</B> oh, apparently they're open again.

**Pull request merged**
