### PR TITLE
Stops hydroponics tray from wasting piped in water

### PR DESCRIPTION
**Pull request by SuperSayu**
## About The Pull Request

As currently implemented, hydroponics trays will draw water in from a duct network every processing tick and then discard it if the water is full but the nutrient tray has space in it--which is extremely common.  This was capable of wasting thousands of units of water in minutes, emptying water tanks and leaving only tears behind.

To make this work, I made the duct network act a little smarter than it actually is--drawing water and nutrients separately from separate sources.  Ultimately, it would be better if the duct network acted as storage and you could draw out a sample and put back what you don't use, only for it to refill later or in the next cycle, but I'm not willing to try that refactor and find out what it does to all of chemistry.

I also decided that I wanted to support an edge case where a single source on the network (a storage tank of some kind) contained both water and nutrients, which is about the most complicated edge case we can have here.  Doing so without wasting egregious amounts of stuff required me to work around the duct network's use of round robin reagent transfer, or else add some kind of "transfer all reagents except X" to reagent holders, which was not going to happen.  This workaround will cause ugly floating point numbers to show up in that edge case, but works, and the workaround does not seem to affect the nominal use case.

The nominal test case, though, was with pure water in one source and all non-water reagents in another.  This is handled just fine.

## Why It's Good For The Game

This is mostly a fix for functionality already there.  Arguably there's not a whole lot of reason for you to pipe in nutrients, unless you really know what you're doing or only want bog-standard plants, as it leaves no room in the nutrient tray for you to add things yourself.  (I guess I could add a cap to piped-in nutrients to fix this, if asked)  As it stands, however, there is no reason to pipe anything into hydroponics.  If you have a regenerating supply, it will have so little on hand that it can't fill up very many trays, and if you have a fixed supply, the leaking water will waste it.

## Changelog

:cl:
fix: Using ducts to connect a water tank to one or more hydroponics trays is no longer a monumental waste of resources.
/:cl:

### CODE REVIEW

**Comment by dalmationer** [comment]
thank GOD this'll make plumbing so much easier

**Comment by SuperSayu** [comment]
I'm thinking about it again this morning and I realize that, as I said in the main pr comment, there's not a whole lot of reason to be piping in nutrients.  If we assume that the whole point of it is to put in water, and nutrients are a by-product, instead of assuming that we have to fully handle both, well, I guess I would probably just have the duct network only be triggered by the water level, filter all other reagents into the nutrient tray but not care whether or not that overflows and wastes nutrients.  That would use the ducts the way they are intended, and for the normal everyday use case of just adding water, you'd hardly even notice.  It's only when you try to get creative and add a chemistry set to it that it would be inefficient, and even then, water usually gets consumed faster than nutrients so it would keep flowing in anyway, right?

Any thoughts?

**Comment by BangingDonk** [comment]
I'm really interested in seeing what this will do, because I've noticed some weird behavior in the past with using the plumbing gun (both service and regular) to create hydroponics setups, where it felt like reagent generators just WOULDN'T keep up with tray needs until they mysteriously did, and when I threw up my hands and tried to pipe in an expanded water tank, was horrified that it was draining multiple hundreds of water a second.

I do admit that I am a little concerned by what you mean by nutrient waste overflow, because I do sometimes either use a chem plumber to create reagents and/or an input gate connected to the ductwork to add standard fertilizers, but quite honestly, I'm willing to take a potential hit on the ability to auto-fertilize plants in exchange for MUCH easier auto-watering.

**Comment by SuperSayu** [comment]
As the PR is now there shouldn't be any real nutrient waste.  I was seeing waste in my test case when I tried to have a plumbed dispenser full of mixed stuff (which is fixed currently, but it's ugly), and the alternate version I'm thinking of might waste a little bit, but the biggest wastes that we see currently would be avoided either way.  The current waste is all because the water flow isn't triggering correctly, leading to it draining when it shouldn't.

I may yet just redo the PR with the other version that is focused on water, but if this were merged today it would support plumbing in a water tank and also a chemical source into the same duct network with no problem.  Unfortunately I have been busy and also kind of sick so it may take a little bit.

**Comment by SuperSayu** [comment]
yeah I am going to redo this in a way that isn't cringe

**Pull request closed without merging**
