### PR TITLE
Fixes multiple issues related to suicides

### LINKED ISSUE #55777: You can "charge" suicides by spamming them in the type box, then unleash them all at once if your type of suicide isn't instant.
## Reproduction:
1. get a nuke auth disk
2. "charge" suicide
3. hold enter on yes
4. almost crash the server

### LINKED ISSUE #58151: Signaller Suicided Ethereals can be revived via crystal
## Round ID:
[159595](https://scrubby.melonmesa.com/round/159595)

## Testmerges:
#58038 #58096 #58136 

## Reproduction:
1 - suicide with a signaller in-hand as an ethereal
2 - use a different signaller to kill yourself
3 - die
4 - get revived via crystal
5 - be able to fully rejoin the game

### LINKED ISSUE #58171: Ethereals can suicide and revive with the janny key to clean whatever they walk on
## Reproduction:

Suicide with janitor cart key as ethereal
Get revived by crystal 
You are now a demigod of cleaning and will clean whatever you walk over

### PR DESCRIPTION
**Pull request by ArcaneDefence**
## About The Pull Request
fixes https://github.com/tgstation/tgstation/issues/58171
fixes https://github.com/tgstation/tgstation/issues/58151
fixes https://github.com/tgstation/tgstation/issues/55777

## Why It's Good For The Game
Puts a restriction on suicides to create more sane conditions, preventing unpredictable and unintended behavior.

## Changelog
:cl:
fix: Suicidal ethereals are less likely to fail to kill themselves from unexpected revivals trapping them
del: You can no longer attempt to commit suicide multiple times at once.
/:cl:

### CODE REVIEW

**Comment by SuperNovaa41** [comment]
hugbug...

**Comment by ArcaneDefence** [comment]
https://www.youtube.com/watch?v=LSNVoAVm6lc

**Comment by wesoda25** [comment]
Lame

**Comment by ArcaneDefence** [comment]
I dream of a world where aspiring feature coders can code their suicide acts to be funny without being picked apart alive under the scrutiny of shitcode.

A world where a man can have a desword cut your head off and have you run around like a chicken because it is funny, and not be terrified of introducing a means to separate the brainmob from a mob. No longer living in fear of people abusing renaming salt shakers, using the salt shaker suicide to change their mob's name to a specific mob faction, to then use xenobiology to strip a faction from a mob that is supposed to have it.

I aspire for people to be able to add a suicide to a jannycart key that checks what level of a janitor you are and plays some silly things for all to see, have them realize that it doesn't remove the cleaning element, decide that it's funnier to leave it in as the mental idea of someone scrubbing the floor with the janitor's corpse is hilarious. Not have their efforts wasted as it can be input cancelled through the effects of other suicides because it is simply "the most optimal effect to abuse" and then lead to a madman's rants in an issue report they didn't make where they brainstorm ways to further abuse other funny features.

We do not live in that world, and for that, I am sorry.

**Comment by ATH1909** [comment]
NOT THE NUKE DISK SUICIDE SPAM

**Comment by AlinaStarkova** [comment]
I do not see whats wrong with the janicart suicide thing, its not exactly OP, especially since its something anyone can get roundstart just by becomming a borg anyway. and its complicated to pull off anyway so it will rarely happen, i dont see anything wrong with leaving in little tricks for people to aspire to do if they get bored

**Comment by ATH1909** [comment]
> I do not see whats wrong with the janicart suicide thing, its not exactly OP, especially since its something anyone can get roundstart just by becomming a borg anyway. and its complicated to pull off anyway so it will rarely happen, i dont see anything wrong with leaving in little tricks for people to aspire to do if they get bored

I believe that Hugbug's concern here is future-proofing.

**Comment by AlinaStarkova** [comment]
> > I do not see whats wrong with the janicart suicide thing, its not exactly OP, especially since its something anyone can get roundstart just by becomming a borg anyway. and its complicated to pull off anyway so it will rarely happen, i dont see anything wrong with leaving in little tricks for people to aspire to do if they get bored
> 
> I believe that Hugbug's concern here is future-proofing.

i get that, doesnt mean i have to like it

**Comment by ATH1909** [comment]
> > > I do not see whats wrong with the janicart suicide thing, its not exactly OP, especially since its something anyone can get roundstart just by becomming a borg anyway. and its complicated to pull off anyway so it will rarely happen, i dont see anything wrong with leaving in little tricks for people to aspire to do if they get bored
> > 
> > 
> > I believe that Hugbug's concern here is future-proofing.
> 
> i get that, doesnt mean i have to like it

same

**Comment by Serxule** [comment]
we literally need suicides to be limited, for example, someone spammed the nuke disk suicide **216** times, that froze the server entirely for about 5 seconds. you shouldn't be able to suicide ddos

**Comment by Sparkezel** [comment]
Dunno how about you but its basically a non-issue, iirc you can't kill a server with that

**Comment by SuperNovaa41** [comment]
> we literally need suicides to be limited, for example, someone spammed the nuke disk suicide _**216**_ times, that froze the server entirely for about 5 seconds. you shouldn't be able to suicide ddos

I have done this numerous times, (as have probably hundreds of players), and I have never once seen slowdown

**Comment by TheVekter** [comment]
I don't think the idea is to kill folks' fun, I think it's to remove this in the event it causes an edge case somewhere that's significantly worse than just "make noise a bunch of times".

**Comment by Mothblocks** [comment]
:-1:

**Comment by ShibaInuLord** [comment]
I cant believe you would do this

**Pull request merged**
