### PR TITLE
Blob nerf

### PR DESCRIPTION
**Pull request by LanCartwright**
Naut health from 240 to 150
Price from 30 (some reason says 20) to 40.

### CODE REVIEW

**Comment by WJohn** [comment]
Thank christ.

**Comment by LanCartwright** [comment]
gunhog mentioned it's ridiculously overpowered

**Comment by Zilenan91** [comment]
I feel like this is too much of a nerf, and there's still gonna be the problem of them being able to pull things.

Also Anonus already has a blob balance pr up, might consider getting in touch with him and having him add this to his pr since he's basically the blob guy

**Comment by LanCartwright** [comment]
alright.

**Comment by CPTANT** [comment]
Blobbernauts being sentient is still a bad idea.

**Comment by LanCartwright** [comment]
solved irc with anonus

**Pull request closed without merging**
