### PR TITLE
Revert "Fixes emptied shot glasses having the drinking glass filling icon."

### PR DESCRIPTION
**Pull request by carshalash**
Reverts tgstation/tgstation#62920 Broke the bar VERY hard.

### CODE REVIEW

**Comment by LemonInTheDark** [comment]
Is there an issue report? what broke and how?

**Comment by carshalash** [comment]
> Is there an issue report? what broke and how?

I left the common of what's broken in the original PR.

**Comment by LemonInTheDark** [comment]
Is there an issue report? what broke and how? Also why not just fix the issue

**Comment by tralezab** [comment]
@LemonInTheDark ghommie is going to fix it properly this time, i'm gonna just make this a tm candidate

**Pull request closed without merging**
