### PR TITLE
ICEBOX arrivals: Reworks EVA to make more sense for a snow planet, featuring cool unique coats. Also updates the style and layout of various rooms along the arrivals hall.

### PR DESCRIPTION
**Pull request by MrMelbert**
## About The Pull Request

image

Iceboxstation's EVA has been remapped.
Within the EVA room now contains multiple kits of unique equipment that better help people who wish to brave the wilderness. 

EVA suits have been replaced with EVA coats - these coats are a bit closer to EVA suits in their stats and usage. 
- They're bulky sized. 
- They apply a bit of slowdown while worn. 
- They can carry a full sized oxygen tank in their suit storage slot. 
- They have armor (about half the armor of EVA suits), and are inflammable 

Additionally, it also comes stocked with EVA boots, which are a subtype of the miner's snowshoes that slow you down while worn. 

The command section of EVA contains an old EVA suit if one is needed for some odd reason. 

(But what about xeno protection ahhhh) (It still has welding helmets I guess)

<details>

<summary> EVA picture within (click the triangle) </summary>

image

</details>
To not stick out like a sore thumb, the arrivals hallway in general has been dolled up, updated, and modernized. 

<details>
<summary> Here's the gateway and vault. </summary>

image

</details>
<details>
<summary> Tool storage and garden. </summary>

image

</details>
<details>
<summary> Art storage and emergency storage. (Bonus: The commissary has a maint airlock again.) </summary>

image

</details>

Other miscellaneous changes:
- Cleaned up the pipenet that goes around arrivals and into cargo. 
- Same with cables, but to a lesser extent. 
- One maint room has been added. 
- Port maint and lesser port maint has their area definitions swapped around, and less port maint gained a little size. 
- Intercom coverage around the place has been improved. 
- Some greenery was added to the snow pockets around the bridge. 
- Vault has a small moat on the right side of it that goes to the lower levels. Watch out. 

Todo: 
- [ ] Get some unique sprites for the EVA coats, maybe. 

## Why It's Good For The Game

Icebox's EVA was a bit uh... well it stuck out for what it was used for. 
EVA suits were entirely outclassed by winter coats, and magboots I think didn't even do anything to being slipped on ice. 
By adding some unique coats, ideally people have more of a reason to need to visit EVA instead of just grabbing a coat from dorms / the locker room. 

On top of it, the entire hallway had some very dated design and lacked decalling and style. Updating it makes it a lot more visually appealing and less drab. 

## Changelog

:cl: Melbert
add: Iceboxstation's EVA now comes kitted out with equipment that may actually help you out if you want to go outside. Including special winter coats that can carry big oxygen tanks and boots to prevent you from slipping on ice. 
add: Iceboxstation's arrivals hallway, and many of the rooms around it, have had their style and layouts updated slightly. 
/:cl:

### CODE REVIEW

**Comment by san7890** [comment]
FYI: IceBox failing CI due to the following reasons.
image

**Comment by Fikou** [comment]
these wintercoats feel very much a downgrade to eva suits, a full 1.5 slowdown (slower than a research modsuit) if you are wearing the suit with the boots, they don't have sting/syringe protection, pressure protection, their cold protection is just like normal coats, they dont have any relevant armor, no unique sprite or anything
you would have way better results just putting on a firesuit and a fire helmet, stopping any potential pressure damage, having minor armor, protecting you from syringes (at least in the chest and legs area), as well as a free flashlight and fire protection, their only downside being you don't get protected from ice slips (well you can put on the boots from eva, and you'll just be 0.25 slower)

i would suggest:
raising the winter coat's heat protection to eva suit level, cold protection too maybe? (they don't have pressure protection so seems fair)
lowering the shoe slowdown to 0.25, so wearing it with the suit brings you to 1, like a firesuit/evasuit
make it thick material at least in the suit area, and gloves should be thick too like the botanist ones

after that it would be a fair option i think

**Comment by GuillaumePrata** [comment]
> current human temp code significantly screws over the dangers of Icebox's outdoors.

This but also for space. It is hard to make balance decisions around the system when it is so lenient with letting you survive against the cold.

**Comment by Fikou** [comment]
looks good 👍

**Review by san7890 — CHANGES_REQUESTED** [review]
Big fan of all of this, just a few concerns/nitpicks.

<details>
<summary>Images Within</summary>

image

Would be nice to have holopad here.

image

Holopad also here (so the AI can yell at the captain for deltaing)? 

image

I know it works out in game, but for some reason that railing implies that you "can't" or "shouldn't" be able to reach for that table? I'm not sure if this is like... a valid concern, but it definitely conjured itself in my mind.

image

Maintenance should own these walls.

image

I know this was present before you arrived, but now you're touching that space so you get to fix it :). Just thin out the vent/scrubber placement (maybe have one of them be a bit more south)? Just goofy that they're sorta like that in a longer hallway space.

image

Obtuse to have the pipe under machinery.

image

Probably a better place in this room for the newscaster than behind a big-ass vending machine, I'm eyeing that "bomb assembly table" on the right.

image

Missing scrubber.

image

Missing scrubber- could this room also benefit from having a glass airlock to let people know it's a "public" space? Up to you though. Also lacks camera.

image

I saw you innervate this room with a vent on the mapdiff, but you still need an air alarm for it to be useful beyond just being headless at 101kpa. Also, scrubber innervation would be nice.

image

Flatten these tile decals (into anticorner) please 🥺 

image

Scrubber innervation would be very nice (I know you're going to have to run a long line), if you want brownie points flatten the stylization to opposing_corners.

image

Is "Secure Area" the right choice for this sign on the exterior wall? Screams more "Sudden Drop!" to me.

image

No real reason to have these walls be reinforced IMO.

image

You seem to like having electrical warnings next to every window- this section lacks one. Prime real estate.

image

While you're in the area, those intercoms out of the firelock "crush" zone, and move the screens off the windows. Much appreciated.

image

Feels kinda weird to have the button for the shutters so disconnected, I had a hard time finding it during my walkthrough. Probably fine to leave it as-is, just sharing a thought.

image

Another "in the space" thing- can you turn all of these to normal walls? No sense in them being reinforced.


</details>

Two other things: The maintenance surrounding the areas you touched feels too "sterile" now in contrast to your nice-looking changes. Not sure if there's a practical way to fix this, but it would be nice if you could look into that.

This should be good to go when the review is addressed and you figure out the spriting stuff. Thank you!

**Review by san7890 — CHANGES_REQUESTED** [review]
image

Non-connected scrubber.

Since you have to change that, a few more nitpicks :evilgrin:

image

These two walls (red straight arrows) shouldn't be reinforced, please normalize. Also, those lightswitches (green curved arrows) are in the same @!#$ing crush zone as the firelocks, maybe place them on the same tile as the intercoms? I dunno.

Other than that, should be good if sprites are good. Thank you!

**Review by Imaginos16 — APPROVED** [review]
Fwiw, the sprites are fine! Would be interesting to revisit them in the future when winter coats get inevitably redone.

**Pull request merged**
