### PR TITLE
EMP range is no longer capped

### PR DESCRIPTION
**Pull request by ChangelingRain**
frankly this should do it like explosions do but that'd be more work

### CODE REVIEW

**Comment by Robustin** [comment]
:+1: 

Requested this, the EMP rune in my cult PR would go beyond the current range of 34 with enough cultists chanting the rune. Could be useful for other modes too since we don't have an in-between for "fuck this room in particular" EMP's and "fuck this entire station" power-sinks. Looking forward to see this play out in-game.

**Comment by xxalpha** [comment]
I was going to do this with a feature I had planned but I never completed it. I only wrote this proc because of EMPs. :+1:

**Comment by Jazaen** [comment]
So, 300u/300u Uranium/Iron FUCK-YOU-TECHNOLOGY grenades are reality now? Neat.

**Comment by ChangelingRain** [comment]
300/300 would produce a 25/42(heavy/light) range EMP pulse, so even at that extreme this wasn't affecting much.

**Pull request merged**
