### PR TITLE
Removes fresh oil from all stations

### PR DESCRIPTION
**Pull request by nicbn**
[Changelogs]: #

:cl:
del: Nanotrasen sucked all oil from station using oil sucking bots
/:cl:

Spawned oil sucks.
It makes cargo and engineering a footprint mess 10 seconds into the round, and it makes you so used to seeing oil footprints you won't stop to investigate even if you are a detective.
Now, if you see oil footprints somewhere, you know someone is doing bad things. Like the feature was always supposed to be.

### CODE REVIEW

**Comment by WJohn** [comment]
why not add a (somehow) dried version like with dried blood so it doesn't spread?

**Comment by nicbn** [comment]
If anyone dares to sprite a dried version I'd be okay with adding it
However removing this isn't too much of a deal
The greytiders will smash the beepsky anyway so it's a matter of time for oil to paint the station black.

**Comment by 81Denton** [comment]
I gotta agree with you, people don't pay attention to oil footprints from smashed bots exactly because they're everywhere roundstart.

**Comment by SgtxRootbeer** [comment]
last i checked, oil doesnt dry too easily IRL. I'm not sure a dried version of oil spills would be realistic (yes, i know, realism in an autism simulator)

**Comment by Iatots** [comment]
How about no more dirtstation?
Every stain will have a story that way and we'll reach our RP quota for the year.

**Comment by Bawhoppen** [comment]
@Iatots I agree for stains, but we should still have some random dust and crap, so the janitor has some stuff to do roundstart,

**Comment by lordpidey** [comment]
The ability to scour maint for oil is a big part of ghetto chem.

**Review by ChangelingRain — CHANGES_REQUESTED** [review]
Replace the fresh oil with 'dried' oil, or a version with greatly reduced footstep amount.

**Comment by nicbn** [comment]
Later, on another PR

**Pull request closed without merging**
