### PR TITLE
Gives the ashlizards a puddle.

### LINKED ISSUE #44308: Oversight - Ash walkers cannot make leather
## Reproduction:

Ash walkers are unable to make leather for goliath cloaks as they do not have a puddle or sink in order to wash leather in to wet it.  You are unable to wet leather using their water tank, bucket, or water bottle.

### PR DESCRIPTION
**Pull request by nemvar**
## About The Pull Request

Replaces the water tanks in the ashlizard base with a puddle.

Fixes #44308

## Why It's Good For The Game

Makes farming and making leather more attractive to the ashies. Both of which primal activities, so it fits pretty good. It also looks less silly than a modern water tank.

Damn, with all these small ashlizard buffs, they are soon going to dominate the station every round.

## Changelog
:cl:
tweak: Replaced the water tank in the ashlizard base with a puddle.
/:cl:

### CODE REVIEW

**Comment by WJohn** [comment]
why is there water on lavaland

it's a burning hellworld

**Comment by nemvar** [comment]
Well, we got oxygen and plant life on lavaland. The plants you can get even require water if you want to grow them in a tray. The hermit also already got a puddle.

I would presume that, while water is rare on lavaland, it's not completely devoid of it. It got small pools if highly acidic water at certain locations where it gathers due to lithographic conditions. These places are gathering spot for those unfortunate enough to live down there. Ashlanders are probably not native to lavaland but rather survivors of a failed colony (or something else) and have been partly consumed by the influences of the necropolis, but not enough to where they don't require nutrition or water.

If you want my full headcanon, you can buy it for 4.99$ on amazon. The audiobook is 9.99$.

**Comment by habader** [comment]
Give them fukken wheat seeds too so those retards can make torches

**Comment by SgtxRootbeer** [comment]
I've seen Ash lizards try growing crops, only to fail because they ran out of water. This puddle would solve that. I like it.

**Comment by nicbn** [comment]
You could make it a geyser or something like that

**Comment by FantasticFwoosh** [comment]
> 
> 
> I've seen Ash lizards try growing crops, only to fail because they ran out of water. This puddle would solve that. I like it.

Water isn't nessecary to grow lavaland mushrooms; besides the fruity cactus plant because ash from objects burnt from the fire is nutritious enough to weeds to let them thrive and survive.

**Comment by Daxxed** [comment]
> 
> 
> > I've seen Ash lizards try growing crops, only to fail because they ran out of water. This puddle would solve that. I like it.
> 
> Water isn't nessecary to grow lavaland mushrooms; besides the fruity cactus plant because ash from objects burnt from the fire is nutritious enough to weeds to let them thrive and survive.

Proper savages only eat cacti and use the garbage mushrooms as fertilizer, the other PR changing nicotine's effects on plants will help this.
The water tank lasts quite a while but this will make them 100% self sufficient without needing technologically advanced tools spawned in their nest roundstart.

**Pull request merged**
