### PR TITLE
The pneumatic cannon now takes 50 instead of 300 ticks to craft

### PR DESCRIPTION
**Pull request by Tlaltecuhtli**
:cl:
tweak: crafting a pneumatic cannon no longer takes an eternity
/:cl:
literally a guillotine takes 150 and the crappy meme gun 300??
obviously a misspell of 50

### CODE REVIEW

**Comment by WaterStBlues** [comment]
This fucking thing requires like 20+ player actions to actually load, so this seems fiiiine

**Comment by VileBeggar** [comment]
image
image

**Review by Cyberboss — CHANGES_REQUESTED** [review]
Change the title or change the value

**Comment by ExcessiveUseOfCobblestone** [comment]
Please don't abuse the bot function to get specific labels on your PR that aren't accurate to the PR's contents (This is not a fix). I'll just close them if this happens again.

**Pull request merged**
