### PR TITLE
Ports parallax along with some improvements!

### PR DESCRIPTION
**Pull request by MrsTonedOne**
:cl: FTL13, yogstation, Iamgoofball, and MrStonedOne
add: Space is pretty.
tweak: You can configure how pretty space is in preferences, those of you on toasters should go to low to remove the need to do client side animations. (standard fanfare as job selection, left click to increase, right click to decrease) (Changes are applied immediately in most cases, on reconnect otherwise)
/:cl:
https://www.youtube.com/watch?v=iiMz5X1blg4&feature=youtu.be 

Ports yogstation13/yogstation#1297 (it itself is a port of FTL13/FTL13#283)

Makes it faster, now it no longer does an animate() if it's only moving 1px. (mostly the outer layer, the closer layer generally almost always is moving enough for an animate() call)

Comes in 5 modes:
Insane - no throttle to update rate, 4 layers supported
High - only one update per byond tick, 3 layers supported (default)
Medium - one update per ds, 2 layers supported
Low - one update per 2 ds, only 1 layer.
Disabled

Can be expanded with more layers, currently supports 4 layers but only has 2 layers. Adding 2 more is a object define and 4 icon states per layer. Adding more then 4 would just require re-balancing the modes for the layer amounts. 

@Iamgoofball 

Closes #22070

### CODE REVIEW

**Comment by RemieRichards** [comment]
Damnit!

**Comment by MrPerson** [comment]
Not that anyone cares, but this technique is awful.

First off, it eats two planes for something that only needs to use one. Second, it might as well be the lowest plane because the parallax texture is global. Anything on a lower plane is going to have space multiplied onto it. Third, as you can imagine, this means that we can only have one parallax texture, period.

None of this needs to be the case.

**Comment by MrStonedOne** [comment]
@MrPerson you assume too much about what we know about planes

**Comment by MrStonedOne** [comment]
Gotta fix an issue with ai mobs that's haunting me

**Comment by MrPerson** [comment]
My best guess is that it was a user on a fairly old 510 beta from before FLOAT_PLANE was added. So byond was rendering the image's FLOAT_PLANE value literally. FLOAT_PLANE is like ~= -32,000 for reference. 

If it's happening to everyone, then I dunno.

**Comment by MrStonedOne** [comment]
happening to me in test on latest beta on my desktop.

also my laptop displays space as super dark with random pixels coming in as proper brightness, not sure what thats about

**Comment by Iamgoofball** [comment]
@MrStonedOne the back of space is actually #000000 now

**Comment by MrStonedOne** [comment]
@MrPerson static is done as an image on the turf, space turf is plane -10, parallax is plane -9.

I tried to change the plane, but I only changed the line of code that re-adds the static to a turf recently obscured turf, not the line of code that actually generates the initial set.

**Comment by ChangelingRain** [comment]
The shuttle leave/move animation doesn't properly adjust based on the direction the shuttle's leaving in.

**Comment by MrStonedOne** [comment]
I figured that out @ChangelingRain, and why it seemed to act odd. I'll be refactoring that entire section of code to make more sense and be less shit tomorrow after work.

**Comment by Cyberboss** [comment]
Pls, this PR too good to get memed

**Comment by MrStonedOne** [comment]
Been busy with work this week, I'll see what I can do the next few days.

**Comment by optimumtact** [comment]
Stale, reopen or make a new pr, when you're good to go

**Comment by PKPenguin321** [comment]
REEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE

**Comment by MrStonedOne** [comment]
Blocking byond bug:
http://www.byond.com/forum/?post=2188467
I can most likely figure a work around.

**Pull request closed without merging**
