### PR TITLE
Makes Paralyse() respect stunmods

### PR DESCRIPTION
**Pull request by silicons**
Not sure if this is intentional or a bug..?
if it's intentional this is a tweak/rebalance.

### CODE REVIEW

**Comment by PKPenguin321** [comment]
sounds like somebody got dunked

**Comment by kevinz000** [comment]
^ he's lying i didn't get blown up in the last few days so no :^)

**Comment by Fox-McCloud** [comment]
👍 

Make sense; "anti-stun" has always meant stun+weaken+paralysis (but not sleeping).

**Comment by XDTM** [comment]
Fun fact: before mineral golems it didn't even affect weaken

**Pull request merged**
