### PR TITLE
simplifies firelock deconstruction / construction and other tweaks

### PR DESCRIPTION
**Pull request by Tlaltecuhtli**
:cl: Tlaltecuhtli
balance: firelocks now have less steps ( weld wrench screw crowbar weld to remove and frame circuit wrench to make)
balance: firelocks steps now all take the same time of 2s
balance: destroying a firelock only has 40% chance of creating the frame
balance: lowered the hp of firelock and frame a bit
/:cl:
firelocks are literal satan, they are useless and a pain to make and ugly now it takes like 10s to remove or place which helps rebuilding places as they usually confuse/annoy people and never get made 

https://user-images.githubusercontent.com/33834933/87551678-ff6b7e80-c6b0-11ea-88e5-47add74b2e3e.png
^ this picture is why i set the 70% to not create a frame when destroyed, its ugly to see all these random frames around

### CODE REVIEW

**Comment by Acer202** [comment]
All you need to do to fix the firelocks when they're bombed is crowbar and wrench it. I think people just don't know that! Having to actually rebuild them would take longer, I think.

**Comment by ShizCalev** [comment]
not a fan of the change to deconstruction myself due to the reason Acer stated.

**Comment by Tlaltecuhtli** [comment]
> All you need to do to fix the firelocks when they're bombed is crowbar and wrench it. I think people just don't know that! Having to actually rebuild them would take longer, I think.


they also get deleted by bombs dev tiles and when they do you need to build them anyway so we are back to take 1 whole minute to build a single firelock, i dont see why we need this much complexivity on the most common machinery

**Comment by Acer202** [comment]
> > All you need to do to fix the firelocks when they're bombed is crowbar and wrench it. I think people just don't know that! Having to actually rebuild them would take longer, I think.
> 
> they also get deleted by bombs dev tiles and when they do you need to build them anyway so we are back to take 1 whole minute to build a single firelock, i dont see why we need this much complexivity on the most common machinery

Ah, my issue isn't with firelocks taking less steps and time to construct and deconstruct; that's a welcome change. My issue is with firelocks being deleted when broken 70% of the time, since that adds labor to a repair. Instead of just crowbar + wrench to set a damaged, draggable frame back to a working firelock, now I'd need to go get metal, coil, electronics, then replace a firelock 70% of the time, no?

**Comment by Tlaltecuhtli** [comment]
i set it to 40% and make it drop a circuit on destroy so you just have to craft the frame out of metal to rebuild, the problem i m trying to solve with the chances is that  any explosion would create a mess of firelock frames like picture in OP which looks ugly and have cleaner explosions

**Comment by kriskog** [comment]
Honestly, I preferred high chance of destruction. If they blow up they dont necessarily need to be easy to fix.

**Review by kriskog — CHANGES_REQUESTED** [review]
You seem to have the same line ending issue as in #52180, fix that

**Comment by ShizCalev** [comment]
mk2 #52689

**Pull request closed without merging**
