### PR TITLE
Readability Pass to Advanced Medical Tools

### PR DESCRIPTION
**Pull request by Alecksohs**
## About The Pull Request

Update the sprites of the advanced surgical toolset, giving them distinct colors and updating their lighting to reduce shades and increase visual readability at normal resolutions.

image
image
image

## Why It's Good For The Game

Currently, the advanced surgical toolset over-relies on the tooltip to communicate item state quickly and accurately. This PR adds both color differentials, and enhances the shape of the existing tools to help a player tell them apart quickly and accurately. Additionally, it assists in defining the general shape of the item with cleaned up shading to decrease noisy patterns in the sprite.
## Changelog
:cl:
image: Updated the Advanced Surgical Tool's sprites
code: Updated the Advanced Surgical Tool's light code
/:cl:

### CODE REVIEW

**Comment by JohnFulpWillard** [comment]
Lookability?

**Comment by Alecksohs** [comment]
> Lookability? Readability makes it seem like code improvement not respriting

Readability was used due to sprites being a conveyer of information that you have to read, but if it is a problem I can use "lookability"

**Comment by JohnFulpWillard** [comment]
It's not a real word I just don't know what the right one is

**Comment by Sadboysuss** [comment]
hell yeah I love this

**Comment by EricZilla** [comment]
Readability is being used correctly here.

**Comment by Wallemations** [comment]
> Lookability? Readability makes it seem like code improvement not respriting

Don't get semantic, readability conveys the idea fine

**Pull request merged**
