### PR TITLE
[WIP] Allows mining drills to crack open safes

### PR DESCRIPTION
**Pull request by deathride58**
Title. Alternative to #34327 

:cl: deathride58
balance: Mining drills and sonic jackhammers are now capable of forcing safes open
/:cl:

Safe code is shitcode, it's in desperate need for a rewrite, but that's outside of the scope for this PR.

TODO: add specialized safe-cracking drill to nukeops shuttle, testing.

### CODE REVIEW

**Comment by praisenarsie** [comment]
no, make a new drill which only newcops get

**Comment by deathride58** [comment]
I'd need sprites if we wanna go full payday and add that fukken drill

**Comment by Supermichael777** [comment]
add an angle grinder, a cutting only welder that also does this. "Banned on NT stations due to excessive corner cutting."

**Comment by KorPhaeron** [comment]
Is a payday meme really worth forcing the ops to carry even more crap

We already gave them basically two backpacks because they have so much inventory trouble

**Comment by Iamgoofball** [comment]
@KorPhaeron just take drill skills lol

**Comment by Iamgoofball** [comment]
aka:

just make it so that when they empty-hand a safe, they place a drill on it

**Comment by deathride58** [comment]
If I had sprites for it, that's exactly what I would've done, goof

This is basically 100% manual drilling right now, so the payday memes aren't exactly in full force here

**Comment by optimumtact** [comment]
we're gonna go with #33699 for now

**Pull request closed without merging**
