### PR TITLE
Makes Plastitanium Windows deconstructable and children of Reinforced Windows.

### LINKED ISSUE #45926: Plastitanium windows are unable to be decontructed
## Round ID: 116025

Went through every tool in the toolbox (including welder on harm intent) and was unable to deconstruct a plastitanium window.

### PR DESCRIPTION
**Pull request by Firecage**
## About The Pull Request

Previously Plastitanium windows were completely undeconstructable. Despite as many people originally thought, this was not a bug, but instead an intended feature.

This PR changes that and makes them deconstructable, but they are not deconstructed as normal windows are. Due to them basically being intended as stronger reinforced windows(due to having more health and higher brute armour), they will have the same long deconstruction process which Reinforced Windows currently has. Due to their path being changed to being children of reinforced windows, I have decided to keep another attribute of reinforced windows on them, hopefully to make them slightly more useful. They will have heavy radiation insulation just like normal reinforced windows do.

Update: They are now children of Plasma Reinforced Windows instead due to people wanting that. They will keep the heavy rad insulation which Reinforced Windows gave them though, due to Plasma Reinforced Windows lacking radiation insulation.

Closes #45926 

## Why It's Good For The Game

Because you can now deconstruct and move around Plastitanium Windows which you fastened to the floor instead of having to spend time smashing them into shards. Also because them having heavier radiation insulation would both make them more useful and maybe more likely for people to actually build them.

## Changelog
:cl:
tweak: Plastitanium Windows can now be deconstructed, but by the same process which Reinforced Windows are. They also now offer heavier radiation insulation.
/:cl:

### CODE REVIEW

**Comment by CRITAWAKETS** [comment]
Make them a child of reinforced plasmaglass windows. They are supposed to be kind-of military grade and they cost effectively more to make than reinforced plasmaglass.

**Comment by Firecage** [comment]
Kind of annoying to change paths though. Not difficult, just annoying. Especially the first time around when you go through every map file one by one.

To be honest though, I don't really see any benefit to moving them to plasma/reinforced though, while keeping them exactly the same as they are right now.

**Comment by actioninja** [comment]
tbh I knew about this and have not had the effort to actually fix it considering how rare these windows are.

**Comment by ShizCalev** [comment]
@Firecage You can use visual code to just control F the entire codebase to change paths at once.

image

**Comment by Firecage** [comment]
@ShizCalev So should I then make them plasma/reinforced/plastitanium, or leave them as is?

**Pull request merged**
