### PR TITLE
Some gun recharger fixes

### LINKED ISSUE #8064: Rechargers breaking on power loss
If you detach a recharger from a area that got depowered with it attached inside, and try to use it again outside the depowered area, and attach it, it won't be powered by the powered APC, just shows charging animation but doesn't charge. Annoying as hell in blob when theres a lot of rechargers, blob just breaks the APC and they are all paperweights now.

### PR DESCRIPTION
**Pull request by feemjmeem**
allow borgs to un/wrench rechargers
disallow putting a gun in an unwrenched charger
rechargers no longer stop working forever if you unwrench them from an unpowered area

Fixes #8064

### CODE REVIEW

**Comment by WJohn** [comment]
What happens if you try to unwrench a charger with a gun in it? Does the gun pop out or keep charging or what?

**Comment by feemjmeem** [comment]
Same thing that happened before, that behavior hasn't changed. It says "remove the gun first."

**Comment by feemjmeem** [comment]
Obviously silicons can't do that, but.

**Comment by kevinz000** [comment]
Can you fix the thing where if it was unwrenched in an unpowered area it won't work ever again?

**Comment by feemjmeem** [comment]
@kevinz000 Iiiiinteresting. Yeah, I'll look at that.

**Comment by feemjmeem** [comment]
@kevinz000 Fixed. Thanks!

**Comment by AnonymousNow** [comment]
Probably a little late, but IIRC unpowered chargers will flash like they're charging when a gun is inside them instead of offering visual indication that they're not working.

**Comment by feemjmeem** [comment]
@anonymousnow, missed that. This one's merged but I can do another. Thanks.

**Pull request merged**
