### PR TITLE
Adds moodlets for being covered in blood

### PR DESCRIPTION
**Pull request by ghost**
:cl: Qustinnus
add: You now get upset when covered in blood
/:cl:

No cloud sprite, no hardcore shower expectations, just don't be covered in blood.

Forgot to add it but will do now; antags arent affected as it's their job to be covered in blood.

### CODE REVIEW

**Comment by trollbreeder** [comment]
what about sec getting blood on their clothes?

**Comment by Qustinnus** [comment]
they shower

**Comment by HomocidlePancakes** [comment]
Hey, hey, hey! I love smearing clown blood all over myself after our daily 4PM clown beatings in brig. Why should I suddenly feels sad about it?

**Comment by MrDoomBringer** [comment]
Antags, chefs, and sec should get a mood buff from having blood on their clothes

**Comment by Qustinnus** [comment]
oh yeah chefs shouldnt be affected either

**Comment by trollbreeder** [comment]
Should the janitor DESPISE blood, or be indifferent about it?

**Comment by RaveRadbury** [comment]
> oh yeah chefs shouldnt be affected either

You should go all the way with it. Chef's can wash their exosuit wear in the sink, the apron/chef coat exists for this reason, mechanically. People should feel bad and deal with it. There are enough positive moodlets to balance this out.

**Comment by Tlaltecuhtli** [comment]
will this ignore bloody shoes? because having to clean the shoe every 10 steps isnt fun and will be disliked as the stink pr

**Comment by Qustinnus** [comment]
it wont trigger if you only have bloody shoes as you need 2 dirty clothing pieces for a negative moodlet

**Comment by Daxxed** [comment]
what about miners ?
soon they'll have to take antidepressants for every mob they kill on lavaland with how many mood debuffs they have

**Comment by HomocidlePancakes** [comment]
Antags, sec, chefs, janitors, doctors, clowns and mimes shouldn’t feel bad over getting a bit of red on to their hands. Hell, clowns should probably feel excited by it, since death isn’t real and being covered in strawberry jelly is pretty honkular.

**Comment by wesoda25** [comment]
You should make sure that ghosts can't figure out if people are antags by checking their mood, if you haven't already.

**Comment by Qustinnus** [comment]
ok yea miners are a snowflake job for everything but we might as well make a special server / codebase for mining soon :^)

**Comment by necromanceranne** [comment]
'Hey guys this fella is gutting people left and right and is covered in blood, you think he's an antag?'

**Comment by cacogen** [comment]
the empath trait lets you gauge mood so if someone's covered in blood but their mood is fine you'll know they're an antag won't you

**Comment by Qustinnus** [comment]
the difference in mood from this is miniscule.

**Comment by Learner10** [comment]
Sec doesn't take debuffs because they don't notice the blood on their red uniforms.

**Comment by ATH1909** [comment]
Could you maybe add a "bloodthirsty" 2 point quirk or something that'd remove the mood penalties from this moodlet? That way, chaplains of Khorne and the like won't be punished with negative moodlets for bathing themselves in blood if it's a part of their gimmick (instead, they'll be "punished" with the negative quirks of their choice that they took to pay for the bloodthristy quirk's point cost), but normal people who don't have two spare points to spend on a somewhat situational quirk will still get this moodlet?

**Comment by Qustinnus** [comment]
good idea

**Comment by Victor239** [comment]
Blood cultists should get a positive moodlet for being covered in blood.

**Comment by Shadowflame909** [comment]
So many jobs get bloody on this game

This is too cruel!

**Comment by gitbirb** [comment]
stealth blood tomato buff. Good pr.

**Comment by Qustinnus** [comment]
bit too busy with IRl stuff to keep maintaining this and I want to make sure that the little time i do have i can focus on xenobio

**Pull request closed without merging**
