### PR TITLE
ChangeTurf CHANGETURF_INHERIT_AIR flag fix

### LINKED ISSUE #45279: Shuttles have no atmosphere
Issue reported from  Round ID: 113532 (/tg/Station Terry [EU] [100% LAG FREE] [New-Dedi])

Reporting client version: 512.1471

they dont have an atmosphere. its the same Thing on the 2 rounds before that.
you also cant create one if you vent canisters into them. the gas just disappears.

my assumption is that the shuttle tiles are somehow not replacing the space tiles when they arrive. ->no atmos

### PR DESCRIPTION
**Pull request by Dennok**
## About The Pull Request
Change turf CHANGETURF_INHERIT_AIR flag no more keeps air type, only gases.
fix#45279

## Why It's Good For The Game
Turfs with invalid air type is bad.

## Changelog
:cl:
fix: Fix CHANGETURF_INHERIT_AIR flag. Now this flag dont keep air type, only gases.
/:cl:

### CODE REVIEW

**Comment by Cyprex** [comment]
Does this fix creating plating via RCD, buildmode etc. too?

**Comment by Dennok** [comment]
Yes, all.

**Comment by Dennok** [comment]
Problem in core, on turf changing it keep it air with type, but space have it own immutable air type that cant be changed.
Now turf on change always create new air, kept only gases.
And all ways of turf change call ChsngeTurf, so it fix all.

**Comment by Dennok** [comment]
Sorry. But this can break something. @81Denton

**Comment by Dennok** [comment]
Before last space placed over space break.

**Comment by Cyprex** [comment]
To mirror MSO's comments on #45280:
> The main issue is space turfs don't just have no air, they have a special air datum that can not actually hold gases.
> 
> Snowflaking that away could work, but shuttle code will still need to also be modified to have it clear this flag if you make it default because shuttle code expects the changed turf to have no air so it can copy over the air from the old location.


>Construction intentionally leaves a null air datum so that tile atoms init will create one by averaging the air around it.

**Comment by Dennok** [comment]
In old variant turf on init creates it default air, if you have unpressured room it creates air in that room.

Variant with averaging the air around created turf exist, but this another flag, that can be used.

About shuttle, it replace new air, by old after turf creation, and any flags dont influence on it.
If all work right and nothing dont keep old air type.
Also shuttle use CopyOnTop with copy_air = TRUE, that copy old air too (so we have copying in 2 places). And here realy copy air, not transfer air datum like it be in ChangeTurf

There was a bug in the very use of the flag CHANGETURF_INHERIT_AIR, but here I fixed it.

**Comment by Cyprex** [comment]
This might conflict due to the revert being merged now. You can also remove the "closes#45280" from the first comment now.

**Comment by Dennok** [comment]
This PR fix ChangeTurf CHANGETURF_INHERIT_AIR flag work.

**Comment by Dennok** [comment]
Or make new flag special for inheriting gases?

**Comment by optimumtact** [comment]
Mirroring comment from your previous PR

Don't add an unused flag, just flip the meaning of the flag if you're making it the default. Which I don't recommend at all because it will likely create a lot of atmos-related bugs. The real fix would be to find the floortile's placeontop and put the flag in there.

**Comment by Dennok** [comment]
It creates bugs becose CHANGETURF_INHERIT_AIR work wrong, or not intended to work with space in any way.

This PR just make flag CHANGETURF_INHERIT_AIR work propertly with space. It dont keep space (any) air type of tile, it now keep only gases.

I really do not want the floor created by people to create the air from nowhere in any way.
Shuttles copy the air from the last tile.
The templates used round start initialization or try to make like round start init after.

**Comment by Dennok** [comment]
Sadly but this dont fix it. 
I find problem here,
https://github.com/Dennok/Dennok_tgstation/blob/5af3d38f66d6f454bcd0e2843a3ecf01af84107c/code/game/turfs/change_turf.dm#L144-L145
It always true and replaces air datum completely. 
This creates all this airlose problems.

**Pull request merged**
