### PR TITLE
Change the AI status display by clicking one

### PR DESCRIPTION
**Pull request by Mervill**
:cl: Mervill
add: As the AI: Click an AI status display to bring up the prompt for changing the image
/:cl:

This seemed like a no-brainier QoL improvement

### CODE REVIEW

**Comment by GunHog** [comment]
Test this with a borg to make sure you do not get runtimes! (You may need to check that the user is an AI first)

**Comment by Mervill** [comment]
> /mob/living/silicon/ai/

> You may need to check that the user is an AI 

😓

**Comment by MrPerson** [comment]
Lots of things just forward robot clicks as AI clicks. Sillycons ho

**Comment by Mervill** [comment]
Can confirm that I need to check if the user is an ai inside `attack_ai()` or it will runtime

😓 😓

**Comment by GunHog** [comment]
Testing is the most important thing! :)

**Pull request merged**
