### PR TITLE
Airlock improvements, mainly external [MDB IGNORE]

### PR DESCRIPTION
**Pull request by Cyberboss**
## About The Pull Request

Improvements to cycle-linking operation, minuscule map fixes, default cleanups, public external airlocks (arrivals, escape, pods) now respond to the presence of shuttles, and airlocks closing when shuttles depart now crush mobs. See changelog for details.

[!(Demo Vid Won't Embed)](https://cdn.discordapp.com/attachments/493119635319947269/899039403782070312/airlock_changes.webm.mp4)

## Why It's Good For The Game

You're in space, unauthorized personnel should not be allowed to instantly jump ship, especially if doing so could vent parts of the station. At the same time, we allow self reentry in "man-overboard" scenarios. The aim is to reduce the potential for accidents without reducing crew safety as well as increase the significance of these exterior airlocks. Also makes antags think a bit as they can't simply yeet themselves into space super easily as a braindead getaway tactic.

## Changelog

:cl:
fix: Prying open one of a pair of cycle-linked airlocks will now always close the other (if it is powered).
expansion: Arrivals, escape, and pod airlocks now restrict those without access from exiting directly to space. Use is unrestricted when entering the station or a shuttle is docked.
tweak: Shuttle departures will now force exterior airlocks closed on both the shuttle and docking bay. The lives of your fellow crew members are more important than your tardiness and limbs, employee!
fix: Fixed the numbering of escape pods in certain maps.
/:cl:

- External airlocks now have a base req_access of `ACCESS_EXTERNAL_AIRLOCKS`. This is a non-functional change.
- Removed airlock's `safety_mode` var.
- Added external airlock's `space_dir` var. Indicates the direction anyone can enter from, but only those with access can exit to (unless the other side is considered "safe" (breathable, dense, or shuttle docked)). Cyclelinked airlocks share this value.
- Created `proc/is_safe_turf` from `proc/find_safe_turf`.
- Cycle-link operations now happen in `proc/open` rather than `proc/bumpopen` which was causing several triggers to be missed (AI activation, prying, etc...).
- `proc/try_to_activate_door` now takes an argument allowing for a bypass of access requirements.

Downstreams, to port this to your maps, check every public access external airlock has the `safety_mode` var override removed and the outermost airlock should have `space_dir` set to the hazardous direction number.

### CODE REVIEW

**Comment by Colovorat** [comment]
i might be wrong, but we don't have tweak tag anymore @Cyberboss 😢

**Comment by SuperNovaa41** [comment]
> Also makes antags think a bit as they can't simply yeet themselves into space super easily as a braindead getaway tactic.

This doesn't really make sense to me. Sprinting out of an airlock to dodge a sec chase/whatever it may be, is far more dangerous than continuing the chase inside. Unless you are equipped with a space suit (or space adaptation), finding another entrance that is safe from the initial danger will lead to pretty high amounts of damage.

**Review by Watermelon914 — CHANGES_REQUESTED** [review]

**Review by Watermelon914 — APPROVED** [review]
looks fine

**Review by Maurukas — APPROVED** [review]

**Comment by MrStonedOne** [comment]
> Cycle-link operations now happen in proc/open rather than proc/bumpopen which was causing several triggers to be missed (AI activation, prying, etc...).

This was intentional. There was suppose to be a way to override cycle link operations, and clicking on them was that way. Just like how windoors work.

**Pull request merged**
