### PR TITLE
Fixes active turfs with icebox mining station 

### PR DESCRIPTION
**Pull request by MrMelbert**
## About The Pull Request

Fixes some active turfs caused by #64561
Updates some decal work around some of the changes 
Reworks the drone bay shutters because they were set up incorrectly

## Why It's Good For The Game

active turfs go brrr

## Changelog

:cl: Melbert
fix: Fixes some active turfs + airlock issues on the icebox mining outpost
/:cl:

### CODE REVIEW

**Comment by cacogen** [comment]
The shutters aren't set up incorrectly, because I tested them. They alternate, to prevent the drone bay being opened to the outside. By returning them to how they were, you just create atmos issues with it again. I see there's an extra button that shouldn't be there, but that's the only problem.

**Comment by MrMelbert** [comment]
> The shutters aren't set up incorrectly, because I tested them. They alternate, to prevent the drone bay being opened to the outside. By returning them to how they were, you just create atmos issues with it again. I see there's an extra button that shouldn't be there, but that's the only problem. If you'd just reported it, I could've fixed it.
> 
> https://streamable.com/58tmuo

They were set up incorrectly because there was no way to access the drones without exposing yourself to the outside atmosphere (as evidenced by the active turfs it created by starting opened)

Either way, I originally intentionally designed it with Icebox atmos problems in mind - that's what the windoor is for, to stop atmos problems. It was also designed such that you never had to open the shutters in the first place.

**Comment by cacogen** [comment]
I see. I don't want people leaving the shutters open. What about something like this?

**Comment by MrMelbert** [comment]
I don't mind moving it out one tile for a little more room. 

However I don't like the whole triple-button shuttle dance thing, and in that layout it still will immediately cause a ton of iceland atmos to rush in as soon as you toggle the shutters once (Also the windows backed up against the shutters is a bit icky design wise).  I'd sooner rather delete the button all together and just have the shutters be decoration.

**Comment by MrMelbert** [comment]
(I'll also apologize for calling your fix "incorrect" and rushing forward with a PR on this without noting you, I appreciate the contribution nevertheless!)

**Comment by cacogen** [comment]
I agree my design with the windows up against the shutters and overlapping the drone launchers looks bad. But it prevents people leaving the station open to bad air and (provided the windoor stays on autoclose) keeps most of it in that 6 tile space in front of the shutters. Otherwise, the room loses pressure and becomes cold, the fire alarm activates and eventually the air leaks out into the cargo bay and beyond.

**Pull request merged**
