### PR TITLE
[WIP] OutpostStation

### PR DESCRIPTION
**Pull request by sergeirocks100**
## About The Pull Request

s23

OutpostStation is a map i'm working on.

It, apparently, originally came from Unitystation.

Over on Skyrat, unit0016 ported the map over, and this is the map i am working on.

Considering TramStation got in, i think that the strict in-repo limit of 4 maps might be loosening, which means there might be room for another map.

I don't think it's very good right now, but i think it could be a pretty good map with some work.

## Why It's Good For The Game

I think it wouldn't hurt to have a bit more map variety.

## Changelog
:cl:
add: Added new things
add: Added more things
del: Removed old things
qol: made something easier to use
balance: rebalanced something
fix: fixed a few things
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

### CODE REVIEW

**Comment by Mothblocks** [comment]
image


Did you get permission from the Maptainer?

**Comment by Pumpkinoe** [comment]
I believe tram got in because (like icebox) It's quite a bit different from most of the standard maps, what with it being both multi-z and centering around an experimental form of tram-sportation. What makes this station unique? It looks like quite a boxy regular map without much else to it. A lot of the map already feels quite empty as well, without much decoration or such...

**Comment by Mothblocks** [comment]
Closing pending approval from maptainer.

**Comment by sergeirocks100** [comment]
Dear god, the PR got closed in no time.

Concerning me getting permission,no, i didn't.

I didn't have to when i made the Omegastation PR, so i didn't think i would have to now.

I will go ahead and message EOB for permission on the forums.

**Comment by notfrying1pans** [comment]
this map is very open and empty, look at command to see what i mean

**Comment by notfrying1pans** [comment]
oh god why do like 90% of all plating tiles have multi-layered dirt on them? WHY DOES EVERY SINGLE PLATING TILE  THAT IS UNDER A WINDOW HAVE MULTI-LAYERED DIRT? WHY DOES SEC HAVE A MASSIVE EMPTY ROOM?

**Comment by notfrying1pans** [comment]
wait are those floor tiles under windows???

**Comment by interestingusernam3** [comment]
Cursed map

**Pull request closed without merging**
