### PR TITLE
Changes up the Bulldog Bioterror Dart

### PR DESCRIPTION
**Pull request by Iamgoofball**
Initro replaced with Coniine.

After the buff to initro it became very good with these darts, and needed a bit of a nerf.

The morphine was removed for being really useless and kind of counterproductive with the Sodium Thiopental. The 5u of this was spread out among the other reagents, with 1 extra unit for each one, extending their duration by a few more ticks.

### CODE REVIEW

**Comment by Xhuis** [comment]
I can agree with this. The neurotoxin stun should also be replaced with something more slow-acting, like chloral.

**Comment by MMMiracles** [comment]
Get rid of the stun and mute, it doesn't even matter if kils with the stun because all the op needs is the disk off your grubby little body and to fuck off. The difference between a guaranteed death and a few minutes of stun is that one leaves you alive for when you blow up with the nuke.

**Comment by Iamgoofball** [comment]
That's not the point of this ammo type, really, I think it's for when you run into assistants creeping around in maint and don't want them to screech ops when they see you.

**Comment by MMMiracles** [comment]
Yeah, but all you need is 1 clip to down an entire security team + the captain + someone else. The only hard counter against this is wearing biosuits/hardsuits, which I doubt majority of the people will be wearing.

Even in the nerfed form, its still superior in 90% of situations an operative is going to get into, considering the bulldog is free and the mag itself cost 3 TC. At least remove the stun so the person shot can't immediately scream but has some slim chance of at least doing SOMETHING instead of lying on the floor to die.

**Comment by Iamgoofball** [comment]
I think we should see how it goes with these tweaks first. 1 nerf at a time.

**Comment by Steelpoint** [comment]
Currently these darts are hilariously overpowered, I was lucky to spawn as a Op and witness how insane these things are against even security.

**Comment by Lumipharon** [comment]
I hilariously got dunked by a viro once, while using these. He was the only guy that had a reason to have a biosuit on when we attacked, so my shotgun was useless against him, and he disarmed me and ran off with my gun.

I would honestly sodium theo - you've already got mute + stun + rape poisons, putting them to sleep after a bit seems pretty redundant.

**Pull request merged**
