### PR TITLE
More food effects

### PR DESCRIPTION
**Pull request by MTandi**
## About The Pull Request

In #77887 I have introduced a food buff system with placeholder buffs to not bloat that PR with balance-related things to allow people to add their own effects and discuss the particular effects in separate PRs.

The goal is to have:

- Some default buffs for all food. Currently there's only Haste that scales with food complexity.
- Some interesting buffs tied to food categories or specific dishes

This PR is a first part of this change.

- Adding an indicator to Cooking UI that food does something special
- Added **Spaghetti Carbonara** dish that gives Italian speech.
image

- Added **Jupiter Cup Cake** that gives shock immunity instead of it being randomly given by high-complexity dishes.
image

- Made **Omelette Du Fromage** give French speech.
- Made **Mime Tart** give Mute trait
- Made **Clown Cake** give Waddle Walk trait
- Made **Stuffed Legion** give Ashstorm Immune trait

## Why It's Good For The Game

Foodening PR was incomplete, this PR is a step towards the completion.

## TODO

- [X] Pick a certain dish to give the French speech
- [X] Pick a certain pasta to give the Italian speech
- [X] Pick a certain dish for the shock immunity buff
- [x] Add an indicator to the cooking UI that a dish has a special effect
- [x] Add more food effects per suggestions

## Changelog

:cl:
qol: Dishes with a special food effect are marked in the Cooking UI
add: New Spaghetti Carbonara dish that makes people Italian temporarily
add: Omelette Du Fromage makes people French temporarily
add: Shock Immunity is no longer a random level 4-5 food buff, but a buff given by a new Jupiter-Cup-Cake
add: Mime Tart gives Mute trait
add: Clown Cake gives Waddle Walk trait
add: Stuffed Legion gives Ashstorm Immune trait
/:cl:

### CODE REVIEW

**Comment by Jacquerel** [comment]
I know that [no gbp] has got trendy but im going to be honest I think adding more content to a feature that was merged almost a year ago is probably past the statute of limitations and becomes "I am just adding more features to the game" as in any other normal PR 😅

**Comment by CRITAWAKETS** [comment]
Randomly getting a speech impediment for eating _very_ common types of food sounds incredibly annoying, especially for RP environments. I don't want to do a spaghetti date night and end up speaking like Chef Boyardee...

Also if you're going to be removing shock resistance from the level 4/5 generic buff, it should probably be replaced with something else to still make those high levels desirable in some capacity. Maybe something like brave bull where it makes you tougher? Of course, there's a pun there about you being heartier from a hearty meal.

**Comment by carlarctg** [comment]
energry cake reeequires aen esword man!!!!

**Comment by Loafin34** [comment]
keep grounded on the circuit board cake and 24-volt fish please

**Comment by Wallemations** [comment]
*all* pastas making you speak Italian sounds messed up, I can understand 1 or 2 subtypes doing it
And maybe just leave the French for the baguette
Neither of those are really "buffs"
They're pretty much debuffs for no extra benefit

**Comment by MTandi** [comment]
I'll redo this, thanks for the feedback.

**Comment by Loafin34** [comment]
can high tier meaty dishes increase your skill gain?

**Comment by alien3301** [comment]
You should probably make the special effect thing actually tell you the special effecf

**Comment by alien3301** [comment]
Stuffed legions should give you fire, lava, heat and pepper spray (the chemical comes from hot peppers so the heat resistance dish should probably protect from it) immunity. The food requires lavaland stuff and you can already get permanent fireproofing with xenobio so it doesn't sound too op.

**Comment by alien3301** [comment]
The mime tart could mute you for some time. It requires the deserts cooking book (no clue where to get it), nothing and if you want to use it offensively you need to forcefeed it to someone so it should be fine.

**Comment by alien3301** [comment]
And the wizard burger could either give you one charge of real einath or a fake einath spell which does everything the real one does except actually gibbing people.

**Comment by jughu** [comment]
high sugar items should give you sugar rush which lets you able to craft items faster in the crafting menu

**Comment by jughu** [comment]
> And the wizard burger could either give you one charge of real einath or a fake einath spell which does everything the real one does except actually gibbing people.

should increase your spell level by 1 across the board temporary 😈

**Comment by alien3301** [comment]
> > And the wizard burger could either give you one charge of real einath or a fake einath spell which does everything the real one does except actually gibbing people.
> 
> should increase your spell level by 1 across the board temporary 😈

That would be useless since you need to sacrafice your garb hat so half your spells are gone. Plus it's gonna be difficult to cook shit when everyone including the chef with CQC is out for your ass

**Comment by alien3301** [comment]
The energy cake should definetely do something super strong to make it worth giving up an esword but I have no ideas that would fit it :/

**Comment by alien3301** [comment]
Make honk pockets and other clown foods give you the funny wobble walk

**Comment by MTandi** [comment]
> high sugar items should give you sugar rush which lets you able to craft items faster in the crafting menu

I think it should be rather some specific trait of a chef, rather than a food buff.

Like eating leftover food (bitten by other people) making you cook faster. Or whatever chefs usually eat.

**Comment by jughu** [comment]
> > > And the wizard burger could either give you one charge of real einath or a fake einath spell which does everything the real one does except actually gibbing people.
> > 
> > 
> > should increase your spell level by 1 across the board temporary 😈
> 
> That would be useless since you need to sacrafice your garb hat so half your spells are gone. Plus it's gonna be difficult to cook shit when everyone including the chef with CQC is out for your ass

are we gonna ignore that wizards have a whole vendor of clothes and they start with 1 burger aswell

**Comment by jughu** [comment]
> > > > And the wizard burger could either give you one charge of real einath or a fake einath spell which does everything the real one does except actually gibbing people.
> > > 
> > > 
> > > should increase your spell level by 1 across the board temporary 😈
> > 
> > 
> > That would be useless since you need to sacrafice your garb hat so half your spells are gone. Plus it's gonna be difficult to cook shit when everyone including the chef with CQC is out for your ass
> 
> are we gonna ignore that wizards have a whole vendor of clothes and they start with 1 burger aswell

**Comment by alien3301** [comment]
> > high sugar items should give you sugar rush which lets you able to craft items faster in the crafting menu
> 
> I think it should be some specific trait of a chef, rather than a food buff.
> 
> Like eating leftover food (bitten by other people) making you cook faster. Or whatever chefs usually eat.

I don't know about others but I don't eat leftover food. Maybe the kiss skillchip could make you craft food much faster?

**Review by Wallemations — APPROVED** [review]
Sprites for the new dishes look fine

Also much better selection for the speech traits, makes them feel very intentional and silly compared to before

**Comment by Wallemations** [comment]
also If you were polling for ideas;

Goliath steak giving a small defense boost of some sort in low-pressure or high heat
Some of those mushrooms you can find in lavaland could also give you low-pressure buffs

That dish that uses bear meat could slightly reduce the amount of slowdown you receive from stuff like pulling lockers/corpses

Sushi could make you butcher animals faster (originally was gonna just say fish but I figured all animals would be better)

I can't remember if there's a dish with rats in it besides the burger & kebab but if there is, it could increase night vision range by 1 tile

Hope any of these are good

**Comment by MTandi** [comment]
These ideas are great, but I've already moved to another thing. Won't add any more for now. 
We may need some repository for good food buff ideas, so that these aren't lost.

**Pull request merged**
