### PR TITLE
Adds a Touchy quirk

### PR DESCRIPTION
**Pull request by JohnFulpWillard**
## About The Pull Request

Adds a new quirk for -2 points that requires you to be next to something to examine them, like blindness but without the timer or actual blindness itself.

## Why It's Good For The Game

For the player using the quirk, it's 2 points for losing the ability to simply examine everything around you, making it harder to tell what someone has in their hands when they are charging at you, for example. You need to get up and close to things to see what they are.
For people being examined, it's just another possible excuse to be near them, opening up plausible deniability for actions such as sleepy pens, changeling stings, etc.

## Changelog

:cl: Atlasle, JohnFulpWillard
add: Adds the Touchy quirk, you need to be next to something to examine it, for 2 extra quirk points.
/:cl:

### CODE REVIEW

**Comment by Admiral-Gigaton** [comment]
this affects examining people i assume

**Comment by JohnFulpWillard** [comment]
people and items, anything you can examine

**Comment by Jezzared** [comment]
Now THIS is the only cure to my obsessive shift-clicking. Now i can finally play characters who are supposed to be fucking stupid and dont notice things.

**Review by Ghommie — APPROVED** [review]

**Comment by EricZilla** [comment]
Why the name touchy?

**Pull request merged**
