### PR TITLE
Disallow effects from being scanned by the chameleon projector

### LINKED ISSUE #38015: Scanning a chameleon projector disguise with a chameleon projector turns you invisible
[Round ID]:  88379

[Reproduction]: Person A becomes literally any object with their chameleon projector.
Person B scans person A, while person A is disguised.
Person B will now be completely invisible and impossible to click on, or otherwise interact with short of bombing the place you think they're in.

This is particularly bad with nuke ops, as they can now instantly [*teleports behind u*] the disk holder.
You can't even right click the tile. They don't even show up on that. They're completely untouchable.

### PR DESCRIPTION
**Pull request by vuonojenmustaturska**
Fixes #38015

Originally I was only going to blacklist temp_effect and the chameleon effect but none of the effect types are free from sin.

:cl: Naksu
tweak: Chameleon projector can no longer scan (often temporary) visual effects like projectiles, flashes and the masked appearance of another chameleon projector user
/:cl:

### CODE REVIEW

**Comment by Alexch2** [comment]
H-hayai!

**Comment by ExcessiveUseOfCobblestone** [comment]
Being sparkles you get from the arcade machine is a FEATURE!!!!!

Also this will make it stop you from scanning decals such as oil spills/footprints/etc. 👎 

Again, the DEFAULT option for this thing is 2 pixels. I agree invisibility shouldn't be ok, that was never intended. Anything else should be completely fair game.

**Comment by davethwave** [comment]
Scans the mimes invisible wall...

**Comment by AlexTheSysop42** [comment]
Sparkles are an object

**Comment by ExcessiveUseOfCobblestone** [comment]
@AlexTheSysop42 https://github.com/tgstation/tgstation/blob/3553c12d0bfa4ce2eb75fd2dd0b2d410c167521c/code/modules/reagents/chemistry/reagents/other_reagents.dm#L1772

**Comment by AlexTheSysop42** [comment]
Never mind then

**Comment by ExcessiveUseOfCobblestone** [comment]
#27513 stupid kevinz

**Comment by PKPenguin321** [comment]
Malformed :cl:

**Comment by vuonojenmustaturska** [comment]
invisible wall is an effect

**Review by ShizCalev — DISMISSED** [review]

**Review by ShizCalev — CHANGES_REQUESTED** [review]
plenty of things use this same istype check for obj/effects, make it a helper

**Comment by cyclowns** [comment]
feels like there should be a typecache for stuff blacklisted from cham projectors since that if statement is getting pretty long

**Comment by vuonojenmustaturska** [comment]
i don't really want to pay the cost of a typecache for something that shows up once a week tops, an effect typecache is possible

**Pull request merged**
