### PR TITLE
Fixes pkborg fields not updating location or draining power

### LINKED ISSUE #27410: Projectile dampener fields broken in multiple ways.
These things do not follow the cyborg, are PERMANENT (even after cyborg death), and can be made screwy looking by moving while clicking the device to activate it.

Did you test this at all?

### PR DESCRIPTION
**Pull request by silicons**
OH MY FUCKING GOD I FORGOT THE GET_TURF WHY DO I KEEP DOING THIS
fixes #27410
IM SORRY OK DONT BULLY

### CODE REVIEW

**Comment by GunHog** [comment]
Kev...I asked you why the field does not move with the borg! Why did you ignore me? :disappointed:

**Comment by kevinz000** [comment]
Wait what

**Comment by kevinz000** [comment]
Well shit :(

**Comment by Repukan** [comment]
Is kevinz, dare I say it, /ourgoof/

**Review by Cyberboss — CHANGES_REQUESTED** [review]
There's something wrong with this, I know there is

**Comment by kevinz000** [comment]
@Cyberboss hmmmmmmmmmmmmmmmmmmmmmm

**Pull request merged**
