### PR TITLE
Easier Medipen Identification, Medipen Box

### PR DESCRIPTION
**Pull request by Owai-Seek**
Adds a box for medipens, and gives each of the "common" pens a new look.

## About The Pull Request

Adds a box decal for medipen boxes, and makes gives each of the "common" medipens a different color to easily distinguish them from each other.

## Why It's Good For The Game

I like having an easy way to (visually) identify different things, and it's good to know you're injecting a body with formaldehyde to preserve it, instead of a first-aid or blood-clot pen that's basically doing nothing.

dreamseeker_zwSvLtLm0L

Now Craftable!

image

Color Changes after pinging Twaticus

image

## Changelog
:cl:
tweak: medipen boxes have their own box icon.
imageadd: You can tell first aid, blood clot, and formaldehyde medipens apart. 
/:cl:

### CODE REVIEW

**Comment by ATH1909** [comment]
is it possible to make these boxes out of cardboard?

**Comment by cacogen** [comment]
Wow, order and systems, my fetish

**Comment by trerri** [comment]
Could you please make this even more obvious? It's still hard to tell.

**Comment by Tlaltecuhtli** [comment]
can you make the colored part bigger like on other medicine medipens?

**Comment by cacogen** [comment]
You could add a reagent overlay like other reagent containers

**Comment by ExcessiveUseOfCobblestone** [comment]
this is waiting on twat just ping her on discord if you havent already.

please ping me once approved (twat or op)

**Review by Twaticus — APPROVED** [review]

**Pull request merged**
