### PR TITLE
tgui-next ntos chat

### PR DESCRIPTION
**Pull request by actioninja**
## About The Pull Request

I put way too much effort into this.
image

Also some new generic components

## Why It's Good For The Game

Who cares nobody uses this

## Changelog
:cl:
add: tgui-next ntos chat
/:cl:

### CODE REVIEW

**Comment by GuillaumePrata** [comment]
At least the 1 in 100 rounds I get to play with the tablet chat it will have a pretty lit interface.

**Comment by Tharcoonvagh** [comment]
Mostly bloodbros use it

**Review by stylemistake — DISMISSED** [review]

**Comment by cacogen** [comment]
looks really good
nobody will use this

**Comment by optimumtact** [comment]
that's incredible wow, almost makes me want to put some kind of bigger role for this.

**Pull request merged**
