### PR TITLE
Age Restrictions for Antagonists

### LINKED ISSUE #7978: Request: Age Restrictions for Antagonist Roles
Feature Request

Similar to how we restrict new players from playing heads or sec, I'd like to restrict them from playing antags as well.

Not just so newbies don't play as them and ruin everything, but so it can act as a deterrent to people ban evading all the time.

I'd like to suggest at least a week before they can play any antag, and two weeks for team antag roles.

### PR DESCRIPTION
**Pull request by Ikarrus**
screenshot 2015-03-01 20 35 33

Closes #7978

### CODE REVIEW

**Comment by Lumipharon** [comment]
Why was this not implemented years ago? +1

**Comment by flazeo25** [comment]
I think Oprertive, Wizard and Blob should be either 20 days instead of 7 and 14 since blob requires to know alot and 14 days seems like bad idea for wizards and opertives

**Comment by Ikarrus** [comment]
What's there to learn about blobs that you can't do without actually playing blob?

**Comment by Incoming5643** [comment]
Node placement mostly. I STILL see a lot of blobs get ruined because they just manually spread/attack the whole time and refuse to use resource nodes at all.

**Comment by Ikarrus** [comment]
I don't see how not being able to play blob is going to teach you to do these things.

**Comment by Incoming5643** [comment]
I was kind of implying I was hoping said newbie would get his shit pushed in by a good blob and then take a good look at what the blob was doing.

**Comment by Ikarrus** [comment]
I fight against blobs all the time but I'll still have no clue what to do if I actually play as one (I have it disabled)

**Comment by Incoming5643** [comment]
#BringBack #2791

**Comment by Ikarrus** [comment]
Everyone has to start somewhere. Everyone was shit and inexperienced at one point.

Minimum age restrictions just helps ensure that they at least know the very basic controls and mechanics of this game. (And acts as a deterrent against alt keys)

**Comment by AlexCrimson** [comment]
Personally i just made an offline server and fucked around as each of the different antags to get used to how they work.

**Comment by SconesC** [comment]
Fucking awesome.

There is the issue that a lot of antags just take experience to learn but I wouldn't complain if the minimum age for ops/cult was bumped up seeing as while they have their own mechanic, actually playing them requires you to be fairly adept at the game.

**Comment by Xhuis** [comment]
:+1: x :100: x :100: x :100:

**Comment by Iamgoofball** [comment]
i dunno man

maybe traitor at the least should be unrestricted

because if a newbie rolls traitor it means he has a free pass to play with some of the more dangerous stuff and learn how to kill or be killed and shit

**Comment by Razharas** [comment]
Its not fun to become traitor when you dont know how to take off clothes

**Pull request merged**
