### PR TITLE
Fixes #38875 - Destroyed non-human bodies cloning as humans

### LINKED ISSUE #38875: Cloning console doesn't save species
[Round ID]: # 90372

[Reproduction]: # I was a moth and at round start I had myself scanned in the cloning consoles. When I was revived through it, I was cloned as a human.

https://github.com/tgstation/tgstation/blob/ce2d7900052522578624b66e9723ebf12a549d6a/code/game/machinery/computer/cloning.dm#L471 The race is saved and used here: https://github.com/tgstation/tgstation/blob/ce2d7900052522578624b66e9723ebf12a549d6a/code/game/machinery/computer/cloning.dm#L76

### PR DESCRIPTION
**Pull request by Mothblocks**
I really don't like my way of doing this but I don't know if there's something more obvious I'm missing...

[Changelogs]: 

:cl:
fix: Fixes destroyed non-human bodies cloning as humans.
/:cl:

### CODE REVIEW

**Comment by ExcessiveUseOfCobblestone** [comment]
If you're going to do it like this have the argument on the proc vs on the datum

**Comment by Jared-Fogle** [comment]
@ExcessiveUseOfCobblestone How? The DNA object is already made at the point when the code gets there.

**Comment by ExcessiveUseOfCobblestone** [comment]
oh github made it look like it was in New() hmm....

**Comment by optimumtact** [comment]
How are you cloning a deleted body? This doesn't make much sense

**Comment by ExcessiveUseOfCobblestone** [comment]
Why does it even call delete on the dna?

**Comment by Jared-Fogle** [comment]
Maybe just to clear up memory?

**Comment by ExcessiveUseOfCobblestone** [comment]
ugh you're suppose to know EVERYTHING.

I'll take a look this evening (maybe, I have a nice rimworld base atm so I want to play that).

**Comment by SpaceManiac** [comment]
I'm not necessarily against this as a stopgap fix until this code is otherwise cleaned.

Clone data should really be its own datum rather than a big list that we then subsequently hardcode indices into anyways.

**Review by SpaceManiac — APPROVED** [review]

**Comment by SpaceManiac** [comment]
This code needs a redo but it's not reasonable to require you to do it at this time

**Pull request merged**
