### PR TITLE
Nerfs gang turrets by preventing rotation while firing

### PR DESCRIPTION
**Pull request by silicons**
yadda yadda too overpowered yadda yadda no i didn't die to one everyone else did yadda yadda.
there's a difference between defending your lawn and having an overpowered weapon to massacre with.

### CODE REVIEW

**Comment by Robustin** [comment]
Fuck off Kev jesus christ if you can't figure out to take out a fragile stationary machine that has a forced 5 second cooldown in a mode that gives you access to frag grenades and a sniper rifle for less influence then there's no helping you.

This is the epitome of shitty kneejerk coder PR's and I'd hoped that as a player you wouldn't devolve into such base tendencies knowing that the first fucking round an item makes an appearance isn't the best time to judge it.

**Comment by PKPenguin321** [comment]
Give it more of a chance, yeah

**Comment by Robustin** [comment]
As a note I've only seen this in one round too, apparently not the same as Kevs, where one turret got smashed by Telekinesis and the other blew up to a frag grenade, and they racked up about 2 kills between the two of them.

**Comment by kevinz000** [comment]
Eh fair's fair

**Pull request closed without merging**
