### PR TITLE
Gives abductees a message saying they can't remember the abduction

### PR DESCRIPTION
**Pull request by XDTM**
:cl: XDTM
balance: Abductors have learned how to properly delete the memories of their test subjects.
/:cl:

Discussion Thread: https://tgstation13.org/phpBB/viewtopic.php?f=33&t=11399

It seemed like everyone agreed with the idea so far.

### CODE REVIEW

**Comment by XDTM** [comment]
What's this failing check and how do i fix it

**Comment by Repukan** [comment]
What if the abductors go loud, someone else sees them abduct someone, and then they get told they were abducted?

**Comment by bgobandit** [comment]
Then they RP that out, this is to prevent people getting abducted and immediately screaming I'VE BEEN ABDUCTED over comms, and to try to get people to at least try to do their objectives, i.e. the entire point of the ayy mode

**Comment by Cyberboss** [comment]
@XDTM Push you have to push another commit to clear it

**Comment by 4dplanner** [comment]
One problem I have with this is that it wipes any cool interactions you have on the spaceship while being operated on, which is sad rp-wise

**Pull request merged**
