### PR TITLE
Removes drag slowdown from Harvester mob

### PR DESCRIPTION
**Pull request by Cenrus**
## About The Pull Request

Quick one liner to make NarSie's harvesters ignore the movement speed penalty when dragging corpses.

## Why It's Good For The Game

Removes some tedium from the fun little minigame at the (bad) end of cult rounds

## Changelog

:cl:
balance: Harvesters are now not affected by drag slowdown.
/:cl:

### CODE REVIEW

**Comment by the-orange-cow** [comment]
Wouldn't this be a balance change, seeing as it affects how effectively players are able to resist being converted?

**Comment by CRITAWAKETS** [comment]
> Wouldn't this be a balance change, seeing as it affects how effectively players are able to resist being converted?

i don't think its much of a "balance" change considering this only happens in round end, otherwise harvesters don't appear.

**Comment by Fikou** [comment]
tweak is not a changelog label we use.

**Comment by jlsnow301** [comment]
disagree that this is really truly a balance change but w.e

**Pull request merged**
