### PR TITLE
Adds a self-destruct function to Syndicate cyborgs

### PR DESCRIPTION
**Pull request by ghost**
I heard people wanted an explosive implant equivalent for Syndicate cyborgs, so here it is. Syndicate cyborgs can now detonate themselves after three seconds, destroying all traces of the body as well as the MMI.

### CODE REVIEW

**Comment by GunHog** [comment]
Use of this module is a violation of Law 3. It would only be valid to use if directly ordered by an agent, or if self-destructing would serve to protect one.

**Comment by Lumipharon** [comment]
Neat. Does it work while stunned?

**Comment by Xhuis** [comment]
@Lumipharon It works in all cases, even if you're dead.

**Comment by CosmicScientist** [comment]
:+1:
Will probably be interesting to play mind games with syndiborgs to see if you can flash them to get them to explode even if you have no hope of meleeing them to death.

**Comment by Shadowlight213** [comment]
Please no. Subverting a syndie borg is a legitimate strategy for the crew and isn't as easy to do as stripping a dead op. This removes the only risk that buying a syndie borg had. :-1:

**Comment by daman997** [comment]
by the time the borg is subverted the ops are either a. leaving while the nuke is armed or b. all dead. the real 'risk' with the borg is spending 50 TC on a potentially shitty player

**Comment by KorPhaeron** [comment]
Borg doesnt really need a buff.

Crew gaining badguy stuff used to be one of ky favourite things as well (like the chaplain using constructs or unlinking a borg to fight the malf AI) so taking it away makes me sad.

I'm not sure what issue this fixes.

**Comment by Shadowlight213** [comment]
I've seen op rounds last long enough to subvert it. Also, the nuke op explosive implant serves as equipment denial. You can't take a borg's equipment from it. Only purpose it serves is to fuck with someone using a flash, aka the one stun for the borg that isn't locked in the armory and is melee range only. Plus, unlike op implants, the borg can activate it ANY TIME even if they have been dead for a while.

**Comment by AnonymousNow** [comment]
This seems pointless, other than to stop a canny crew from subverting the cyborg. It doesn't make sense lore-wise, and serves only to amuse a small number of players who don't know what the explosive implant is for, from what I've heard.

**Comment by Xhuis** [comment]
I can see your feedback, and it has a valid point. Closing this because people don't want it!

**Pull request closed without merging**
