### PR TITLE
Credits Put Into PDAs/Modular Computers Go Into Inserted IDs

### PR DESCRIPTION
**Pull request by SpaceDragon00**
## About The Pull Request

If a PDA or Modular Computer is attacked by something, it now checks to see if it can insert the object into the contained ID

## Why It's Good For The Game

It is now easier to deposit cash, credits, or otherwise for people who put PDAs or Tablets into their ID slot. (It also does this for laptops if you're that kind of sicko)

## Changelog
:cl:
qol: Using credits on a PDA, Laptop, or Tablet now inserts the credits into the contained ID card, if there is one
/:cl:

### CODE REVIEW

**Comment by maxymax13** [comment]
finally no more akward alt click dance

**Comment by maxymax13** [comment]
> 
> 
> Just reminding that ID-removing was an intentional design choice (IIRC), akin to having to take your wallet out of your pocket. Made players more vulnerable to theft during transactions, etc.
> 
> Probably a fine change tho

assistants already disarm us to steal every single other object in the game let us at least keep our id

**Comment by ArcaneMusic** [comment]
Parroting off what mothblocks was saying last night, this should really be an element or component, So you can just add credit-adding behavior to objects instead of implementing multiple `istype` checks to more and more objects that could potentially hold your ID.

**Comment by SpaceDragon00** [comment]
After the extensive conversation which destroyed my soul, I decided to take Orange's advice and just make iscash (Which I didnt even have to, it already existed, fuck me)

The element was (Mostly) completed but simplicity is strength here

**Comment by ArcaneMusic** [comment]
In hindsight, this is probably a fairly simple solution and looks good. 👍

**Review by ninjanomnom — APPROVED** [review]

**Pull request merged**
