### PR TITLE
fixes chameleon laser guns blowing up welding tanks for real this time

### PR DESCRIPTION
**Pull request by silicons**
is this an acceptable pr name maintainers?

### CODE REVIEW

**Comment by obscolene** [comment]
>be sec
>arrest traitor and get chameleon gun
>go around shooting people with it disguised as rapid syringe gun
>miss and hit a welding tank
>kill 2 people
>happens again 10 minutes later

it's a feature

**Comment by kevinz000** [comment]
>use antag items
>fucks up
>go fix your shit


hm

**Comment by obscolene** [comment]
i'm not one of the innocent people who got blown up by a sec officer due to an unintended feature of the chameleon gun. no skin off my back :0)

**Comment by UncleBourbon** [comment]
Don't add it, the faster klara is perma banned cause she tabled me one time the better!!!! <:^(

**Comment by obscolene** [comment]
only 3 more PRs to go before he actually finally fixes it (for real this time guys). keep up the good work kevinz

**Pull request merged**
