### PR TITLE
[READY] Making selfreferences finally reference themselves

### PR DESCRIPTION
**Pull request by Shdorsh**
[Changelogs]: # Hey folks, remember #39394 ? This is the continuation of it, in a much better and automated way. Besides, it was tested on my homeserver and it is fully functional. It also removes those horrid brackets from the printer interface and adds a copy data mode to the debugger, allowing you to copy any data and paste it in a pin accepting the same type.

:cl: Shdorsh
fix: Made the self reference pins for reagents reference themselves automatically.
tweak: Made it possible to copy datas frop pin to pin with the debugger.
spellcheck: Removed ugly useless brackets from printers.
/:cl:

[why]: # First, because that's what it was supposed to do. Secondly, it makes handling reagent circuitry easier. Thirdly, this gives new options for new circuits.

Tested and working.

### CODE REVIEW

**Comment by Shdorsh** [comment]
There seems to be something that needs a slight fixing, but my whole apartment got a power shortage and I can't code from my phone.

**Comment by ahkent** [comment]
basic QoL etc yes pls

**Comment by Shdorsh** [comment]
It's done.

**Comment by Shdorsh** [comment]
Well, since no one checks circuit PRs a lot, I guess I can add more onto this. Time for a small modification.

**Comment by Shdorsh** [comment]
For reagent circuits' self reference. That way, you can easily wire it onto the right place and it works. However, keep this open for a bit, I need to add something to this.

**Comment by Shdorsh** [comment]
Not entirely tested yet, give me a second, I'll tell you all when it's good.

**Pull request merged**
