### PR TITLE
Revert "Removes title4.ogg"

### PR DESCRIPTION
**Pull request by Niknakflak**
Reverts tgstation/tgstation#28882

@Cheridan 

I sent you a formal letter, please respond.

### CODE REVIEW

**Comment by PKPenguin321** [comment]
why do you like this song, curious

**Comment by Niknakflak** [comment]
How do you not like this song?  It's eery with violins and hard cello 
It blends beautifully and has cemented itself with traitors in my brain for the game

**Comment by lzimann** [comment]
Because he added it

**Comment by Niknakflak** [comment]
Well normally you like the things you add, that's kind of how it works

**Comment by PKPenguin321** [comment]
I think it doesn't work very well, I always pictured the lobby as a place where you were led in with cheery upbeat tunes, almost like where Nanotrasen is giving promise of good pay and a luxurious workspace, before arriving at the station and then finding it's essentially a deathtrap filled with idiots and murderers.

Plus the sound itself is pretty poorly done, especially when compressed to such levels: It runs 2x the lobby's 2 minute timer (although with initialization it's more like 1 minute over), and the very first sound (the "SCREEEEEE") comes off like a horrible squeal that only builds up in volume and repeats throughout the entire song. I'll give that a lot of it isn't bad, but it's just too violent and squeal-y for the lobby in my opinion.

**Comment by Niknakflak** [comment]
Its not even compressed much, I personally sound edited it, I dont really remember what exactly are the specifications. I should check

**Comment by Tacolizard** [comment]
@Niknakflak kind of off topic, but what software do you use for sound compression?

**Comment by Tacolizard** [comment]
I mean I thought this song was good enough not to be reverted, but I'm not sure it's good enough to be re-added.

**Comment by SgtxRootbeer** [comment]
Meh, it isn't good enough to be re-added, imo.

**Comment by Niknakflak** [comment]
If everyone who downvoted the last PR could upvote this one, that'd be great because according to Cheridan, I have to win a vote twice.

**Comment by Niknakflak** [comment]
who are those mysterious other people

**Comment by Iamgoofball** [comment]
you dont get to know because you'll target them

**Comment by Niknakflak** [comment]
I inspected the webpage too to see if the data was explored anywhere but its literally stored in the html as "4 others" as well, what is this cheap data user experiences here github

**Comment by Iamgoofball** [comment]
maybe you should stop stalking people who disagree with you

**Comment by Niknakflak** [comment]
That's not stalking, it's public information.  I'm a web dev, of course I'm gonna look at the guts of the webpage to see if there's anything good in it

**Comment by JJRcop** [comment]
Hi stalk me I downvoted. I think the song is neat but it's not for SS13

**Comment by Cyberboss** [comment]
Thumbs don't lie

**Comment by Niknakflak** [comment]
Never forget that I got cheated out of a vote because leoz powertripped

**Pull request closed without merging**
