### PR TITLE
Tilening V2 Part 2: KrysonWood Edition

### PR DESCRIPTION
**Pull request by Imaginos16**
## About The Pull Request
Hey there! Didn't expect me to be back so soon? Well, that's because I had yet *another* project on the backburner: A Sequel to Tilening V2!

Where we last left off, we redid a huge majority of the sprites related to iron floors, but another big culprit was left untouched: Wood Floors!

So, what did I do? I asked @Krysonism for the wood tiles they've used for a majority of their Wallening mockups, and finalized their work! Behold:
image
image
image
image

As a result, I felt that as I was touching up those wood sprites, I should've addressed a few more tiles while on the way, which is when I decided upon retouching the titanium and plastitanium tiles as well!
image
image
image
image
image

Decals related to these two tile types were also changed!

<details><summary>Here's some highlights of it during a few test screenshots on localhost!</summary>
<p>

image
image
image
image
image
image

</p>
</details>

This PR also changes the appearance of plating, making it smoother as some people complained about the waffle pattern and I agree, it was excessive!
image

Finally, this PR very minorly adjusts a few tiles, such as the black and white tiles, diagonal, black and grey tiles, etc, as well as removing unused damaged icons, and replacing them with the better ones we have. Said unused/old icons will be dumped onto the spriting depot.

## Why It's Good For The Game
A continuation of my work, as well as being the intended vision Kryson desired for the upcoming wallening project! There's still a lot to go, but its a good step in the right direction of visual progress!

## Changelog

:cl: PositiveEntropy, Kryson
del: Removes old and unused titanium, plastitanium and plating damaged states.
imageadd: Resprites the wooden, titanium and plastitanium-related floors!
imageadd: Decals related to the resprited tiles have been adjusted accordingly.
imageadd: Updates the appearance of plating to be smoother!
/:cl:

### CODE REVIEW

**Comment by newfren** [comment]
aren't there white titanium tiles too?

**Comment by Imaginos16** [comment]
> aren't there white titanium tiles too?

You're right! I forgot to post them, haha. Here you go!

image

**Comment by Imaginos16** [comment]
Gave an update to how wood sidings look like, over some problems regarding how they interacted with the newer wood floors.
image

**Comment by Nabski89** [comment]
Nice job with splitting off the damaged as an overlay.

**Pull request merged**
