### PR TITLE
fixes #25754 [what is this new meme title req]

### LINKED ISSUE #25754: [s] Wizard's Magic Mirror allows memezombie race
Memezombies get the zombie claw stuck in each hand, so they can't use the mirror to change back: this is a way to render Wizard unwinnable before even teleporting to the station. Any blacklisting for the magic mirror has likely fallen out of date relative to the variety of races added.

### PR DESCRIPTION
**Pull request by ExcessiveUseOfCobblestone**
fixes #25754

### CODE REVIEW

**Comment by Repukan** [comment]
But it was a feature

**Comment by Cheridan** [comment]
>they're literally called memezombies

😦

**Comment by ExcessiveUseOfCobblestone** [comment]
goofzombies, memezombies, and zombies

goofzombies are reskinned humans
memezombies are BRAINNZZZZZZ
zombies are shitty skeletons [the ones people complained about on Halloween]

**Comment by coiax** [comment]
Why can't wizards be angels?

**Comment by optimumtact** [comment]
@ExcessiveUseOfCobblestone wrong

goofzombies are goofs method of handling krokdil addicts

@Cheridan memezombie is just the internal id, it doesn't show outside the code or viewvar

**Comment by Kromgar** [comment]
Please no remove. Wizards could make apprentices to spread zombie plague and thats totally a wizard thing to do

**Comment by coiax** [comment]
@Kromgar the problem is that the wizard, once they have taken infectious zombie form, is incapable of leaving the den, or even changing back.

The only sequence of events I can see having an infectious zombie wizard leaving the den is if they take Summon Events and Teleport, and then wait for the Robeless Casting event to fire.

**Comment by ExcessiveUseOfCobblestone** [comment]
@optimumtact yes but they are reskinned humans in terms of their magical flags, right?

**Comment by coiax** [comment]
@ExcessiveUseOfCobblestone each species has an internal "id" used for the mirror or admin species selection. Goofzombies, memezombies and zombies are just their internal names.

**Comment by ExcessiveUseOfCobblestone** [comment]
Yes but goofzombies are, in terms of function, reskinned humans, correct?

It's how we simulate krok addicts without giving them actual zombie.

**Comment by coiax** [comment]
Yes, goofzombies are about as human as lizards are.

**Comment by Tacolizard** [comment]
misleading PR title

**Comment by optimumtact** [comment]
Please consider this a friendly warning, your PR's must have a properly descriptive title and body content that explains the purpose of the PR.

Your current title and or body content does not meet requirements, so please update it.

**Pull request merged**
