### PR TITLE
Holy whip now deals more damage to vampires.

### PR DESCRIPTION
**Pull request by Militaires**
## About The Pull Request
they don't belong in this world

:cl: Basilman
add: Chaplain's holy whip now deals more damage to vampires.
/:cl:

image

vampire killer.

### CODE REVIEW

**Comment by Shadowflame909** [comment]
I knew the curator could use Hermit Purple

**Comment by nicbn** [comment]
Don't forget that the vampire must transform into a giant bat after you behead him

**Comment by Potato-Masher** [comment]
>Die, monster! You don't belong in this world!

**Comment by Militaires** [comment]
it was not by my hand that i am once again given flesh

**Comment by wesoda25** [comment]
What is this a reference to

**Comment by Shadowflame909** [comment]
Castlevania

**Comment by daklaj** [comment]
do we have vampires?
thats nice

**Comment by knacker48** [comment]
Don't vampires only appear on halloween?

**Comment by habader** [comment]
now someone hurry up and finish vampires

**Comment by ExcessiveUseOfCobblestone** [comment]
https://www.youtube.com/watch?v=0KTmREodeFI

**Comment by Therapist1** [comment]
Don’t forget the holy whip null rod skin!

**Comment by Militaires** [comment]
@Therapist1 good idea, doesn't make sense to be curator whip so i just changed it to holy whip

**Comment by Militaires** [comment]
@ExcessiveUseOfCobblestone that proc doesn't return booleans, it returns 29 for 30x damage, 2 for 3x damage, so 1 for 2x damage etc

**Comment by ExcessiveUseOfCobblestone** [comment]
wtf the base proc is literally "return FALSE"

**Comment by ExcessiveUseOfCobblestone** [comment]
https://github.com/tgstation/tgstation/blob/732b94093525282c2e3dd49f9d864995913a2cf3/code/modules/mob/living/carbon/human/species.dm#L965-L966

REEEEEEEEEEEEEEEEEEEEEEE

**Pull request merged**
