### PR TITLE
changes the cyborg hat blacklist to include all space helmets and the broken chameleon hat

### PR DESCRIPTION
**Pull request by Fikou**
## About The Pull Request

i dont really get why the eva helmet was blacklisted but if it was blacklisted all spacegear should really
the chameleon hat literally doesnt work on borgs,

## Why It's Good For The Game

why can you put something that doesnt work on a borg, it just doesnt make sense skipper

## Changelog
:cl:
tweak: you can no longer put broken chameleon hats or any space helmets on borgs
/:cl:

### CODE REVIEW

**Comment by ATH1909** [comment]
Have you tested what happens when a borg wears a normal (or unusual) space helmet? Maybe the problem's just with the default kind?

**Comment by Fikou** [comment]
> Have you tested what happens when a borg wears a normal (or unusual) space helmet? Maybe the problem's just with the default kind?

eva isnt default kind

**Comment by zxaber** [comment]
EVA helmet was blacklisted because the sprite didn't look very good on borgs.

I heard the chameleon hat on a borg was funny because it would change every time the borg's cover was opened and closed. That sounds like a neat and harmless interaction.

**Comment by Fikou** [comment]
> EVA helmet was blacklisted because the sprite didn't look very good on borgs.
> 
> I heard the chameleon hat on a borg was funny because it would change every time the borg's cover was opened and closed. That sounds like a neat and harmless interaction.

yeah but the intended function of the broken/empd chameleon hat is to switch randomly, it doesnt switch randomly, it switches when you open the cover

**Comment by zxaber** [comment]
That still seems funny enough. Does it actually break anything gameplay-wise?

**Review by kriskog — APPROVED** [review]

**Pull request merged**
