### PR TITLE
DiscStation Pull Take 2

### PR DESCRIPTION
**Pull request by Strathcona**
This time with the absolute minimum amount of files and changed stuff.

### CODE REVIEW

**Comment by Tokiko1** [comment]
If you want map specific custom objects on your map, you could add the files like ministation does it.

**Comment by Strathcona** [comment]
There's nothing that I needed to do more than var-editing for fortunately. A few paths changed and it was easier to remove them.

**Comment by MrStonedOne** [comment]
<Mrs_Sybil> AUTOMATIC ANNOUNCEMENT : PR test job started. Updating master then merging PR #12111 locally

#12111 includes this map as well as map rotation

**Comment by Giacom** [comment]
I was looking at the image of the station and I could not find the gravity generator. Am I blind or is there not one?

**Comment by Jordie0608** [comment]
@Giacom Right side of the central void, in line with the escape pods and xenobio

**Comment by Giacom** [comment]
Ah thanks.

**Pull request merged**
