### PR TITLE
Ports some plant sprites from Shiptest

### PR DESCRIPTION
**Pull request by dragomagol**
## About The Pull Request
Original PR: https://github.com/shiptest-ss13/Shiptest/pull/1509

Ports over some sprites (by nefarious6th) with some minor modifications by me. 
image

Also killed off a pair of unused sprites.

## Why It's Good For The Game
Killing of soul

## Changelog

:cl: tattle, nefarious6th
imageadd: updated a bunch of plant sprites
/:cl:

### CODE REVIEW

**Comment by epicgamer545** [comment]
Looks smoother, cool and good

**Comment by Wallemations** [comment]
Please tell me the holymelon and bluespace tomato sprites are animated normally, otherwise they look so weird to me

**Comment by dragomagol** [comment]
The holymelon and bluespace are animated, as is the fairygrass

**Comment by Imaginos16** [comment]
Sure, I definitely wanted it here.

**Pull request merged**
