### PR TITLE
Log telemetry connections in DB

### PR DESCRIPTION
**Pull request by Mothblocks**
## About The Pull Request
Logs tgui telemetry connections into the database. Useful since they are normally capped to 5.

Does not change the fact that the "banned account in connection history" part is still based on your history at that time. I figured it could potentially be very slow to go through your entire database history.

### CODE REVIEW

**Comment by Mothblocks** [comment]
I want to add first round ID seen and last round ID seen.

**Review by stylemistake — APPROVED** [review]

**Comment by Jordie0608** [comment]
> I want to add first round ID seen and last round ID seen.

That's already recorded in the player table, it is useful to duplicate here as well?

**Comment by Mothblocks** [comment]
Yeah, because these aren't *connections*, they're telemetry logs. 

The round IDs seen correlate to the specific telemetry entries, not to the player in general.

**Comment by Jordie0608** [comment]
ok spidey

**Comment by optimumtact** [comment]
```
MariaDB [tgstation13]> DESCRIBE telemetry_connections;
+-----------------+------------------+------+-----+---------+----------------+
| Field           | Type             | Null | Key | Default | Extra          |
+-----------------+------------------+------+-----+---------+----------------+
| id              | int(11)          | NO   | PRI | NULL    | auto_increment |
| ckey            | varchar(32)      | NO   | MUL | NULL    |                |
| telemetry_ckey  | varchar(32)      | NO   |     | NULL    |                |
| address         | int(10)          | NO   |     | NULL    |                |
| computer_id     | varchar(32)      | NO   |     | NULL    |                |
| first_round_id  | int(11) unsigned | YES  |     | NULL    |                |
| latest_round_id | int(11) unsigned | YES  |     | NULL    |                |
+-----------------+------------------+------+-----+---------+----------------+
7 rows in set (0.142 sec)
MariaDB [tgstation13]> select * from schema_revision order by major desc, minor desc limit 3;
+-------+-------+---------------------+
| major | minor | date                |
+-------+-------+---------------------+
|     5 |    21 | 2021-12-19 21:13:23 |
|     5 |    20 | 2021-11-12 02:29:09 |
|     5 |    19 | 2021-11-10 19:26:10 |
+-------+-------+---------------------+
3 rows in set (0.141 sec)
```

**Pull request merged**
