### PR TITLE
makes rad crates a little more usefull

### PR DESCRIPTION
**Pull request by jughu**
Because i want to know with how much radition i got struck with and it would make sense if centcom ships it with the suits so you can check the radition if the area is safe so you can take your suit off

:cl: Hyena
Tweak: adds 2 geiger counters to radition protection crates and a gift from the russians
/:cl:

### CODE REVIEW

**Comment by Firecage** [comment]
Mmm, personally wouldn't mind if it also came with a bottle of vodka.

**Comment by PKPenguin321** [comment]
Is your name "optional name here"? Because that's the name in your CL

**Comment by jughu** [comment]
Pk you aare my hero

**Comment by ShadowDeath6** [comment]
I wish my name was optional name here

**Comment by Cheridan** [comment]
i'm not seeing any vodka jughu
where's the vodka i was told there'd be vodka

**Comment by jughu** [comment]
@cheridan Cyka blyat

**Pull request merged**
