### PR TITLE
Slightly nerfs borers

### PR DESCRIPTION
**Pull request by Shadowlight213**
:cl:
tweak: Borers now have a 10 second delay before waking up after sugar leaves the host system
tweak: There is a chance for borers to lose control, based on brain damage levels
/:cl:

### CODE REVIEW

**Comment by jughu** [comment]
New meta make yourself retarded to stop mind control

**Comment by Cyberboss** [comment]
HIT ME CHAPPY

**Comment by GunHog** [comment]
Borer request: Borer HUD. I cannot tell if another guy is a borer or not. Apparently heath HUDs can? In that case, possibly give borers health HUDs?

**Comment by CPTANT** [comment]
Seriously, sugar should just force them out with a high enough dose.

**Comment by GunHog** [comment]
Borers need to be able to tell who is infested, as well as talk while controlling a host.

**Comment by Shadowlight213** [comment]
@gunhog talked with @ChangelingRain
Borer antag huds is kinda impossible since antag hud code really really doesn't play nice with other antag huds, and adding the hud would overwrite any other hud their host had. Plus since borers enter and leave hosts at a whim, it's not worth it.

If you want to rework antag hud code, you're welcome to try.

**Comment by ChangelingRain** [comment]
Worse yet, borers don't actually swap minds when they take someone over, meaning while they're in someone they have that person's mind.
They shouldn't work like this, but.

**Comment by Shadowlight213** [comment]
Oh god, that's even worse

**Pull request merged**
