### PR TITLE
adds a config folder for off-repo modular ruins

### PR DESCRIPTION
**Pull request by MMMiracles**
## About The Pull Request
Adds a location to load in off-repo modular maps/config files.

## Why It's Good For The Game
Sticking with the theme of away missions being revitalized, we have a system in place for off-repo away missions but not off-repo modular maps. This allows for randomization in these missions while still keeping the actual map contents a secret to the regular playerbase.

this just adds a config folder location to throw modular maps/their config files.

### CODE REVIEW

**Comment by san7890** [comment]
It's an interesting concept sure, but I'm not certain about how we can implement maintainability into maps that might be out of our control... I'll leave it up to someone who may feel more strongly on the subject than I do, but it would be a damn shame if whatever external service we use for secrecy breaks and there's no way for the codebase to fix it.

**Comment by optimumtact** [comment]
This is a very high risk operation and I am undetermined on this

cc @tgstation/commit-access

**Comment by LemonInTheDark** [comment]
I don't like this

**Comment by MMMiracles** [comment]
My main thing is that mappers can already load in custom sounds and icons from external links, so I figured this wasn't a big stretch.

**Comment by Mothblocks** [comment]
@optimumtact We can set up repos in-org FWIW, but I don't think it's an unreasonable request design-wise to want some hidden gateway stuff, as long as the maintainability is kept responsible by the people working on the maps. Extremely similar to off-repo maps.

**Comment by san7890** [comment]
How does this work from the gameserver end? If it's a private repository, does TGS need to access it somehow (since direct linking won't work if it's a private repository)? Or- do we host the DMM links server-side? At a location where only the gameservers can access it? If it's externally hosted, could someone sneakily change the DMM on us and load in something _bad_? There's a lot that we should try and unravel.

One simple solution is to retain this mechanic is some level and add checks to ensure it loads the DMM from a trusted source? There is a small concern with something like this slipping through on a massive PR with a huge line differential- I would feel easier about this if we had an alert or something during the review process so _we absolutely know_ if there's a feature like this in a PR (rather than be undeclared and unwittingly skip the eye of the maintainer).

**Comment by LemonInTheDark** [comment]
I fundamentally disagree with the idea of hidden content being hosted by our repo. I don't think it's a good idea, and do not like the extra maintenance cost it places on us

**Comment by Maurukas** [comment]
I am no longer convinced that out-of-repo mapping is viable, given how fast the map_depot diverges from the tgstation master. Maps become borderline unloadable within weeks, if not days of being updated. There is no CI validation for anything out of repo.

In theory these would be small snippets - single rooms and ruins where this would be less of a problem, but this also adds in the problem of hosting those maps, organizing them and controlling access to them. 

Then there's the concern of this being used maliciously. It would be entirely too easy to slip in a link that points somewhere not under the control of the org. Every URL would need to be checked each time a map that uses this feature has changes made to it. At the moment I believe that would have to be done manually.

**Comment by optimumtact** [comment]
Sorry I wasn't clear but 
>Then there's the concern of this being used maliciously. 

this was the concern I am worried about.

**Comment by san7890** [comment]
> I am no longer convinced that out-of-repo mapping is viable, given how fast the map_depot diverges from the tgstation master. Maps become borderline unloadable within weeks, if not days of being updated. There is no CI validation for anything out of repo.

I definitely agree with this. I was interested in the concept from the start... but it would be naive to assume that we wouldn't have an immeasurably massive technical debt. At times I felt willing to sort of take this shot to retain whatever secrecy we could potentially extract from having said missions... but the more I sit and think about it, the more the logical mind rejects it.

**Comment by MMMiracles** [comment]
> Sorry I wasn't clear but
> 
> > Then there's the concern of this being used maliciously.
> 
> this was the concern I am worried about.

If an official repo is setup to store these 'hidden' maps, something like hard coding the first half of the url in while you fill in the second half to actually direct to what you want. I.E:

"https://raw.githubusercontent.com/tgstation/tgstation/master/" is part of the expected url link by default, while the mapper fills in the rest, like "_maps/shuttles/arrival_kilo.dmm".

**Comment by Mothblocks** [comment]
That's not possible if the repo is private, which is likely what you are intending this for.

**Comment by Fikou** [comment]
This should be a subfolder in the config gateway folder that you just load stuff from. URLs are pretty unsafe for a large scale thing like a map, having a map on an URL doesnt give us any control over it (the headmins cant disable it or whatever).

**Comment by Y0SH1M4S73R** [comment]
> This should be a subfolder in the config gateway folder that you just load stuff from. URLs are pretty unsafe for a large scale thing like a map, having a map on an URL doesnt give us any control over it (the headmins cant disable it or whatever).

this, but also for image/sound/circuit loaders

**Comment by MMMiracles** [comment]
I honestly didn't think about the fact you can't pull files from private repos so I'll just change this PR into a config folder similar to off-repo away missions when I get home.

**Comment by Fikou** [comment]
> > This should be a subfolder in the config gateway folder that you just load stuff from. URLs are pretty unsafe for a large scale thing like a map, having a map on an URL doesnt give us any control over it (the headmins cant disable it or whatever).
> 
> this, but also for image/sound/circuit loaders

no those have admin event uses why would you want it config

**Comment by MMMiracles** [comment]
Unless there's some external extra steps needed I'm missing, the config var is literally just a file path to config file and the config itself handles where it should be looking for the map file directory. I don't think this actually needs any additional code work.

**Pull request merged**
