### PR TITLE
ill be fixing this later when i decide my choice of 4 poisons or someone does for me[DNM] fixes portals teleporitng anchored things

### PR DESCRIPTION
**Pull request by silicons**

### CODE REVIEW

**Comment by ChangelingRain** [comment]
Megafauna are anchored.

**Comment by ChangelingRain** [comment]
Projectiles are anchored.

**Review by ChangelingRain — CHANGES_REQUESTED** [review]
You need a better way to check this, since there are a number of anchored things that might expect to be teleported.

**Comment by XDTM** [comment]
I can't think of non-projecile anchored atoms that need to pass through portals, if that's actually the case the solution would be to specifically not block projectiles.

Megafauna used to be blocked before the rework, so them being blocked again is fine, megafauna portaling  should have its own discussion before being enabled again.

**Comment by Supermichael777** [comment]
the discussion is NO

**Comment by kevinz000** [comment]
So what was even the bug about them? If it's only megafauna I can either add a var or have a hard check for it? IIRC there's also tendrils? What's up?

**Comment by XDTM** [comment]
It would also teleport pushed machinery right now, like with meteorshot. Anchored is a good check, i think, if you exclude projectiles.

**Comment by lzimann** [comment]
What is even the issue here?

**Comment by kevinz000** [comment]
@XDTM that's kinda intended as the machine jus tflew through the portal.

**Comment by Jalleo** [comment]
It is intended to prevent megafauna being teleported to the station last I heard.

**Pull request closed without merging**
