### PR TITLE
[ready]replaces ointment and bruise packs with mini medsprays

### PR DESCRIPTION
**Pull request by Tlaltecuhtli**
:cl:
removal: ointment and bruise packs have been removed for mini medsprays
tweak: minimedsprays have 50u volume and normal one have 100u volume
tweak: styptic,silverf,synthflesh heal simplemobs on touch,patch,etc
tweak: patches work on simplemobs (but most chems wont do stuff on em)
tweak: first aid kit content has been changed
tweak: bruise/burn aid kits have +1 medspray
tweak: garze heals 10 brute when applied on a bleeding person
/:cl:

bruise packs and ointment are shit code and suck for balance and code design
>person with 180 damage on head -> bruise pack on head 5 times and now he is fine
>we have chems and stuff but this thing just flat heals with magic
>having to swap to every limb and click to heal 1 brute on all limbs

wip:

- [x] find n replace on all maps

- [x] find n replace gauze things

- [x]  test more?

code works fine

### CODE REVIEW

**Comment by Rowelll** [comment]
cool

**Comment by Shapsy** [comment]
Medsprays and chems are good for general healing spread over the body and brute packs/ointment are good when you take a lot of damage in one area, making medical even more "click once then stand around" is silly

**Comment by Ratvar** [comment]
I think that 'Click once then stand around" is better then "click twice and run" because you actually have to wait

**Comment by anconfuzedrock** [comment]
if we're going to fucking remove the way to heal locational damage why the fuck are we going to keep locational damage? for disabled limbs? those never come into play since the thresholds are so high and generally the massive injury it's related to is more pressing.

**Comment by Ratvar** [comment]
You still can, just not instantly?

**Comment by Teepeepee** [comment]
remove synthflesh too while you're at it if only slow healing is acceptable

**Comment by knacker48** [comment]
Why stop there? Just remove Medical. Healing is OP

**Comment by MrPerson** [comment]
Reminder that if you just want to peanut gallery about the general state of Medbay and healing, there's a thread for that: https://tgstation13.org/phpBB/viewtopic.php?f=9&t=21360

**Comment by HomocidlePancakes** [comment]
I don’t think first aid kits should have enough meds to last you the whole shift(they are for the FIRST AID ffs). With bruise packs/ointment you there was high chance you would end up using them inefficiently(small amounts of damage on every limb resulting in alot of damage overall). Either lower the volume of the minisprays to 20 or replace them with one brute/burn patch.

**Comment by necromanceranne** [comment]
Yeah stypic/silver sulf is pretty good not just because it's a burst of healing but a small trickle of regeneration over time while in your system. You practically have all the healing you'll need in a round right there.

While brute packs and ointment aren't that good they're not meant to be good. They're supposed to be used in an emergency and quickly expended if that's all you have. Also, why the heck do these medkits have bottles of tricord? Are we really at the point where we're okay with just liberally giving out chem healing reagents to everyone for anyone to get their hands on with zero effort?

**Comment by HomocidlePancakes** [comment]
(50/4)*2+5 = 31 damage healed per one 5u burst. And you have 20 bursts. 620 damage per bottle with 100% efficiency. Might aswell remove medbay lol.

**Comment by 81Denton** [comment]
I like this idea in general since bruise/burn packs work outside of the healing reagent system and might as well be magic.
Have you checked that the replacement medsprays heal as much as packs and not less/more?

**Comment by HomocidlePancakes** [comment]
Medkits have 12 bruise packs/ointment. Each heals up to 40. So it’s 480 damage each. You won’t use it efficiently most of the time so lets say you loose around half of the value. 240 of each healing type.

**Comment by Tlaltecuhtli** [comment]
most of the times you need healing  the damage is concentrated in 1 or 2 limbs (meele damage, gun shots, fire) leaving just generic pressure damage as "bruise pack sink" the problem is it heals better strong damage over what a bruise pack is supposed to be aka healing light damage

**Comment by HomocidlePancakes** [comment]
The metab rate is same as bicord

**Comment by HomocidlePancakes** [comment]
Also in regards to melee damage. You do not always hit the limb you are targeting, so most of the time (if you survive that is) you will end up with roughly 15 or 25 damage on most limbs

**Comment by Mickyan** [comment]
the stuff inside medkits is locational and has a do_after for self application because it's not supposed to be efficient and it encourages cooperation, this is another nail in medbay's coffin

**Comment by optimumtact** [comment]
>suck for balance and code design
You never actually justified this so there's no chance im going out on a limb (heheh SEE WHAT I DID THERE) for a PR this heavily disliked

**Pull request closed without merging**
