### PR TITLE
Donk Co. now owns the rights to design and manufacture shuttles

### PR DESCRIPTION
**Pull request by ninjanomnom**
Shoot me if I turn this into another major rework

Adds Donk Co. branding to the shuttle consoles

important fluff

### CODE REVIEW

**Review by Cyberboss — APPROVED** [review]

**Comment by optimumtact** [comment]
Lore do not match my personal lore reeeeeeeeeee

**Comment by ChangelingRain** [comment]
I don't like this lore nanotrasen would never trust a syndicate corporation to supply working shuttles that aren't just huge bombs

**Comment by ninjanomnom** [comment]
And yet there are donk pockets.

In the end these are all megacorps and thus willing to use each other's services if it helps their bottom line.

**Comment by pubby** [comment]
Makes the UI worse for the sake of... what exactly?

**Comment by AnturK** [comment]
Not my lore.

**Comment by RemieRichards** [comment]
#notmylore

**Comment by Arianya** [comment]
Put a bangin' donk on it!

**Comment by Repukan** [comment]
Not my lore

**Comment by Cyberboss** [comment]
:( I liked this...

**Comment by ninjanomnom** [comment]
You can't stop me now, this is now part of the approved lore

**Comment by Swiftkor** [comment]
absolute madlad

**Comment by ArcaneMusic** [comment]
Now that's what I call classic

**Comment by optimumtact** [comment]
dude lmao just make a new pr

**Comment by ninjanomnom** [comment]
Ok but now my merge:close ratio is better

**Comment by cacogen** [comment]
NT are notoriously big on health and safety

**Comment by Couls** [comment]
I thought we already had zombies in the code why was this merged?

**Comment by optimumtact** [comment]
it's part of the common lore

**Pull request merged**
