### PR TITLE
MGL third edition

### PR DESCRIPTION
**Pull request by LanCartwright**
One for crew (not added to maps) is the 4W40 MGL, which is pump action.
Adds 6B40 MGL to nukeops
Adds new 40mm grenades.

Will do changelog later.
Will post icons later.
Everything is tested.
This weapon is very fun to use.

:cl: 
rscadd: Adds semi-automatic Multiple Grenade Launcher.
rscadd: Adds pump-action Multiple Grenade Launcher.
rscadd: Adds 40mm Buckshot grenade shell.
rscadd: Adds 40mm Rubbershot grenade shell.
rscadd: Adds 40mm EMP-FSD grenade sabot.
rscadd: Adds 40mm Pipe bomb grenade.
rscadd: Adds 40mm Incindiary shell.
rscadd: Adds 40mm EMP grenade.
rscadd: Adds fins trash item.
rscadd: Adds strong ion bolt.
rscadd: Adds 40mm grenades to Uplink.
rscadd: Adds semi-automatic Multiple Grenade Launcher Uplink.
/:cl:

image
6B40 MGL (left) and 4W40 MGL (right).
Left to right.
40mm HE, Rubber, Buck, EMP-FSD, Incindiary.

image
Destroyed machines caused by EMP-FSD sabots. EMP emitting fins are scattered across the floor.

image
Warden suppresses assistants using 40mm rubbershot.

image
Syndicate sweeps several crew using 40mm buckshot.

image
Syndicate disables his wingman, the HOS, HOP, and Captain with several grenades.

image
image

### CODE REVIEW

**Comment by Bawhoppen** [comment]
:-1: pls don't do this

**Comment by drynwyn** [comment]
Fun to use, very not fun to have used ON you. The EMP burst in particular is just a big ol fuck you sillicons.

**Comment by PKPenguin321** [comment]
more guns wew

**Comment by Niknakflak** [comment]
Awful ammo sprites

**Comment by AlexanderUlanH** [comment]
:-1: give it a rest lan

**Comment by Steelpoint** [comment]
Grenade launchers are fun, you just need to get better sprites.

Try using the old M90 Grenade sprites.

**Comment by LanCartwright** [comment]
Better sprites for what, the grenades or?

**Comment by Steelpoint** [comment]
The Grenade Launcher, the grenade sprites seem fine (sans the one's just copying half of another grenade ontop of it).

**Comment by LanCartwright** [comment]
i'll talk to nienhaus

**Comment by Bawhoppen** [comment]
the problem with this is the nukeops don't need any more guns, it just seems pretty uninspired and generic, not to mention how OP this might be

**Comment by duncathan** [comment]
@LanCartwright

**Pull request closed without merging**
