### PR TITLE
Adds a 2.5 second fire delay to beam rifles

### PR DESCRIPTION
**Pull request by silicons**

### CODE REVIEW

**Comment by davethwave** [comment]
Wondering if someone was going to do this after what happened to those blobs, by the way. Any chance of increasing the power cost per shot from 5000 to 7500?

**Comment by 81Denton** [comment]
🆑

**Comment by Shadowflame909** [comment]
These are the new blob x-rays. Will we stop making weapons that ohko blebs?

**Comment by Tlaltecuhtli** [comment]
>overminds are too dumb to send blobbernauts to kill the gun wielder so it needs to be nerfed

**Comment by rustledjimm** [comment]
Considering they could kill the blob in near seconds once they reached them I feel like they are a bit over powered.

**Comment by Shapsy** [comment]
Yeah but consider this:

Blob sucks

**Review by ShizCalev — APPROVED** [review]

**Comment by Xhuis** [comment]
Ur mom sucks

**Comment by improvedname** [comment]
Ur code sucks

**Comment by optimumtact** [comment]
this item should be removed

it's a single purpose weapon that's used only for fighting blobs and defeating them easily due to it's AOE

**Comment by optimumtact** [comment]
actually there is a counter, switch to expanding foam

**Comment by Magikarpet** [comment]
It's replicating foam, the issue with replicating foam though is that it can be finicky. At times it just explosively splits in the presence of fire, other times it does nothing. It's not a complete counter I believe but it is honestly the best blob at resisting the beam rifle. Rifles are kinda absurd though, you need blobbernauts who are madlads to charge them constantly or you lose, and if the station has enough resources and is smart enough they can kill you as quickly as a scientist with 5 x-ray laser guns in his bag staring at your core from space.

**Comment by optimumtact** [comment]
agreed, it's not good

**Pull request merged**
