### PR TITLE
Adds a Sniper crate for 20K Credits

### PR DESCRIPTION
**Pull request by Iamgoofball**
challenging work

coded for ma44

### CODE REVIEW

**Comment by KorPhaeron** [comment]
for what purpose

**Comment by TheColdTurtle** [comment]
>challenging work
dude you just need 20 max potency money fruits. Botany does that every other round

**Comment by ma44** [comment]
Make it contraband/emag
@KorPhaeron for killing stuff

**Comment by lzimann** [comment]
shouldn't we first make cargo not easily have infinite points before adding stuff to it

**Comment by KorPhaeron** [comment]
^

**Comment by Iamgoofball** [comment]
putting a hit out on you all

**Pull request closed without merging**
