### PR TITLE
Fix pre_attack, fixing RPEDs

### LINKED ISSUE #56791: RPEDs are broken, BRPEDs are effectively broken
Reporting client version: 513.1542

## Round ID:
[156038](https://scrubby.melonmesa.com/round/156038)

## Testmerges:
- [Upgrade marked to 2.0.0, along with the other deps](https://www.github.com/tgstation/tgstation/pull/56767)

## Reproduction:

If you print an RPED or BRPED as usual from a techfab or protolathe, it will not pick up items from the floor. They can only manually be loaded by clicking on them with a single part in hand at a time.
In addition, attacking a finished machine with an RPED will not give you a part readout, and attacking a screwed machine with a loaded RPED will not upgrade its parts.

The BRPED, on the contrary, will successfully poll and upgrade machines. However, it inherits its inability to mass collect parts from the floor from the RPED.

### LINKED ISSUE #56804: Clicking on portals adjacent to you with hand tele now teleports you, instead of closing the portal.
on a server after my hand tele update, basically i suck

### LINKED ISSUE #56824: Plantbag click plants to pick up broke
## Testmerges:
BYOND Version: 513.1536
Server revision compiled on: 
Master commit: e3f80621bd3a61c2fb626975b8b6efffebc1c6ea
The following pull requests are currently test merged:
#56571: 'space is more realistic, exchangers unchanged' by Sparkezel at commit cdf456051b
#56797: 'Simplified Node Bootstrap mk. II' by stylemistake at commit 514cf0b48f

Local commit: e5d1eac44790151008f75a2f7790032de0f51eac
TGS version: /tg/station 13 Server v3.2.6.2
DMAPI version: 3.2.1.3

Current Informational Settings:
Protect Authority Roles From Traitor: 1
Protect Assistant Role From Traitor: 0
Enforce Human Authority: 1
Allow Latejoin Antagonists: 1
Enforce Continuous Rounds: 10 of 21 roundtypes
Allow Midround Antagonists: 5 of 21 roundtypes
Game Mode Odds for current round:
traitorbro 7.3%
traitorchan 7.3%
traitor 21.8%
nuclear 7.3%
cult 7.3%
dynamic 21.8%
extended 1.8%
secret_extended 3.6%
revolution 10.9%
wizard 10.9%
All Game Mode Odds:
traitorbro 7.3%
traitorchan 7.3%
traitor 21.8%
nuclear 7.3%
cult 7.3%
dynamic 21.8%
extended 1.8%
secret_extended 3.6%
revolution 10.9%
wizard 10.9%

## Reproduction:

Get plantbag. Click plant on ground with plantbag. Suffer becaause it doesnt work

### PR DESCRIPTION
**Pull request by Mothblocks**
## About The Pull Request
Fixes #56791. 
Fixes #56804.
Fixes #56824.

## Changelog
:cl:
fix: Fixed pre_attack, fixing RPEDs and similar.
/:cl:

### CODE REVIEW

**Comment by Jared-Fogle** [comment]
Untested, I'll test it later today.

**Review by LemonInTheDark — APPROVED** [review]

**Comment by Jared-Fogle** [comment]
Tested, works fine.

**Comment by rdragan** [comment]
RPDs are also broken, they will not place or delete pipes. Does this fix them too?
Also, this affects all mass pickup items, so it's pretty high impact for many jobs.

**Comment by Jared-Fogle** [comment]
Yes.

**Pull request merged**
