### PR TITLE
Adds logs for admins to kudzu.

### LINKED ISSUE #9004: Kudzu could benefit from adminlogging
@Cheridan 

feature request

There's currently no way to find this via logs (To my knowledge) and it causes some annoying witch hunts in certain situations

### PR DESCRIPTION
**Pull request by Firecage**
1. When Kudzu is planted, it will both message the admins and make a game log.
2. When Kudzu is planted in the Hydrotray, it will make a game log.

Fixes #9004

### CODE REVIEW

**Comment by SconesC** [comment]
Awesome, thanks a bunch

**Comment by optimumtact** [comment]
You might want a cooldown on this because if someone starts spamming Kudzu it would be pretty annoying

**Comment by Jordie0608** [comment]
Could you make this go into an Investigate log instead?

**Comment by Firecage** [comment]
Sure, will do so in a bit.

**Comment by Firecage** [comment]
@Jordie0608 Okay, done. Took so long because I was watching anime.

**Comment by Jordie0608** [comment]
Travis took so long I had time to manually download this branch and test it myself.

**Comment by Firecage** [comment]
HOOOOONK!

**Pull request merged**
