### PR TITLE
everything can climb on ladders

### PR DESCRIPTION
**Pull request by Fikou**
## About The Pull Request

larvas, slimes and simplemobs can now climb ladders

## Why It's Good For The Game

FLOOR STUCK!! FLOOR STUCK!! CANT MAKE IT SON!!

## Changelog
:cl:
fix: every mob can climb on ladders
/:cl:

### CODE REVIEW

**Comment by TemporalOroboros** [comment]
I would argue that this should require hands or something. I can't really see how a goliath or sentient tree could climb a ladder. How do they grab the rungs?

**Comment by TemporalOroboros** [comment]
Larva at least sort of make sense. I can see how a sufficiently motivated snake could climb a ladder and they sort of look like snakes.

**Review by coiax — APPROVED** [review]

**Comment by ilikesaying** [comment]
goliath uses it's tentacles to lift itself up?

**Comment by TheBonded** [comment]
I don't see how a sentient tree doesn't pop up through the ceiling so climbing a ladder should be fine

**Review by Rohesie — APPROVED** [review]

**Pull request merged**
