### PR TITLE
Prevents wizard from gaining infinite skeletons with a 3-use Necrostone

### PR DESCRIPTION
**Pull request by Robustin**
Turns out you can use a staff/wand of healing to make a new skeleton and then revive the old one.

Not anymore!

### CODE REVIEW

**Comment by kevinz000** [comment]
aha lmao.

**Comment by Repukan** [comment]
I ded

**Comment by PKPenguin321** [comment]
Sad I didn't get to see that it sounds funny

**Comment by FantasticFwoosh** [comment]
I can't see why you couldn't have made the first three skele's fully armed but then afterwards had skeles spawn naked by simply changing the state of the necrostone. Im not in favor of nerfing this wizard item that gets played a little bit too rarely, though i approve of a attempt to balance.

**Pull request merged**
