### PR TITLE
Update fancy.dm

### PR DESCRIPTION
**Pull request by CandyClownTG**
Replaced Doctor's Delight with Omnizine to make Syndicate Smokes useful again.

### CODE REVIEW

**Comment by Iamgoofball** [comment]
:+1:

**Comment by xxalpha** [comment]
Changelog.

**Comment by Iamgoofball** [comment]
@xxalpha it's a bugfix

**Comment by xxalpha** [comment]
It's an important bugfix. People know that it's broken and they won't buy the syndie smokes until they know it's fixed.

**Comment by Iamgoofball** [comment]
good point

**Comment by Jordie0608** [comment]
I'll make one for it.

**Pull request merged**
