### PR TITLE
Adds back GPS functionality to the teleportation console

### PR DESCRIPTION
**Pull request by MrLostman**
## About The Pull Request
Adds back the ability to insert the GPS into the teleportation console and use its stored coordinates as a target. The GPS stores the coordinates by being set to manual update.
Capture

## Why It's Good For The Game
Adds more functionality to the teleporation console, allowing more intresting things to be done with it.

## Changelog
:cl:
add: GPS functionality back to the teleportation console
/:cl:

### CODE REVIEW

**Comment by Cyprex** [comment]
telescience bad
Do you at least have to be at a location once to get a manual GPS of it?

**Comment by Fikou** [comment]
just print a damn teleport beacon if you want to get to the location
this is just risk free no effort teleportation

**Comment by FloranOtten** [comment]
> just print a damn teleport beacon if you want to get to the location
> the literal purpose of the beacon is to be where you teleport with, why add it to another item, why make the beacon useless at its one job??

beacon is useful for location travel, this is useful for when you want to go there just once.

**Comment by MrLostman** [comment]
@Cyprex you can't enter cords into the GPS. It works by being set to manual this stops it from updating, storing the current location. This is explained in the PR but if you don't know how GPS's work I could understand the worry.

@Fikou It has the advantage and disadvatage of not being able to move. Better for public teleporation systems for example.

**Comment by optimumtact** [comment]
This was indeed removed for a reason

**Comment by MrLostman** [comment]
@optimumtact it wasnt removed it was broken and no one ever fixed it and when gps's where updated the relating code was removed

**Comment by optimumtact** [comment]
Hmm, Im not sure about this

**Comment by MrLostman** [comment]
Really the only reason not to have it is that its to similar in function to beacons. I would dissagree having a static target quite useful to things like public teleportation systems, and being able to organise your own targets free huge list of beacons.

**Comment by MrLostman** [comment]
@Fikou
> why make the beacon useless at its one job

Pffffttttt, I don't know how you could get to this conclusion. You think carrying around boxes of GPS's would be better to having a list of beacons? The GPS's only advantage over beacons is that it cant be messed with on the teleporting end.

**Comment by nemvar** [comment]
I hate this because I hate how clunky this is. Just add an extra button instead of using manual update for this. Anyways, this will be one of those obscure features that nobody uses/maintains or otherwise interacts with.
The future of this feature will be that it gets removed in 2 years because nobody could remember why it was even added and some newcoder wants to fix turfs hard deleting sometimes.

**Comment by ExcessiveUseOfCobblestone** [comment]
we have quantum pads for reliable point A/B teleportation.

on top of the clunky nature of it i'm of the opinion it should have been removed since quantum pads fill the niche.

**Pull request closed without merging**
