### PR TITLE
Fix build mode preview spawning atoms needlessly

### LINKED ISSUE #80125: Selecting `/obj/narsie` with advanced buildmode will end the round
## Reproduction:

This is essentially a dupe of #80124 , but I'm creating a separate issue to highlight the importance of this:

Because selecting an object with build-mode instantiates one of that object in nullspace to create a preview image of it, selecting Nar'sie will.. run the whole 'round end' thing. And end the round. Without actually spawning it. This is not ideal.

### PR DESCRIPTION
**Pull request by MrsTonedOne**
Before the large icon fix, it would use a mutable_appearance, get_small_overlay wants atoms but it only does appearance things with them so images and mutable appearances should work. There is no need to spawn the atom itself.

We will at some point need a way to specify interfaces as argument types, many such cases of atom or image or mutable_appearance in icon related procs.

closes #80125

### CODE REVIEW

**Comment by san7890** [comment]
is this the one that closes #80125

**Comment by MrStonedOne** [comment]
yes

**Review by Fikou — CHANGES_REQUESTED** [review]
i feel like `get_small_overlay` should just accept an arg of a mutable appearance instead? it converts the atom immediately to a mutable appearance anyway in that proc. then you just plop a converted atom in or just an image as the arg

**Comment by MrStonedOne** [comment]
Its stupid and can't be fixed

Mutable appearance, atom, and image, are used interchangeably in icon procs because we don't have interfaces in byond which is how you handle this kind of edge case cleanly.

**Pull request merged**
