### PR TITLE
The Kevin De-cleodening: Custom elevator music

### PR DESCRIPTION
**Pull request by TheSmallBlue**
## About The Pull Request
I got the idea while riding an elevator the other day to make a remix of Title2 but Elevator-style. So I downloaded FLStudio, spent a couple of hours fighting with it, made a song, and opened this PR up. Later on, @cats4gold contacted me saying they had the same exact idea, Title2 and all, and after I suggested the ide of combining both versions, we get the status of this PR today!

Here's a video of me riding an elevator (Exciting!):

https://youtu.be/BNQmTe553lU

Also our current looping sound system is very very bad, the problem people have with hearing elevator music outside the elevator is because the checks for stuff like volume falloff only happen when an audio starts playing, so if you stand besides an elevator button and hear the music, if you go far away you'll still hear it as if you're next to it. I don't know how to fix this so I didn't touch it, so hopefully someone else that does, does! :)

Here's a link to the full track:
https://vocaroo.com/1idoRor8G1xY

## Why It's Good For The Game
Way more charming, way more immersive.
## Changelog
:cl: TheSmallBlue and cats4gold
sound: Recent research concluded that the new elevator music was upping crewmate's morale a bit too much, this has now been corrected via the replacement of said music.
code: Added a new "in_order" variable to the looping sound datum, for when you need sounds to play in order
/:cl:

### CODE REVIEW

**Comment by TheSmallBlue** [comment]
The current elevator music also cuts, part of the whole "looping system being bad" thing

**Comment by Sealed101** [comment]
much more fitting, though it may need some more work and direction from a person that is more versed in music(which i am not). imo the percussion (?) is a bit overbearing

**Comment by TheSmallBlue** [comment]
https://youtu.be/n4uP2UzHxP0

Here's a video of the more updated version

**Comment by Dorsisdwarf** [comment]
music is extremely charming tbh

**Comment by Farquaar** [comment]
This is awesome. I love it!

**Comment by DrDiasyl** [comment]
Of course this is not as memey as the original elevator music, but it's totally being more unique.
Great job.
~~Also as a creator of original elevator music PR, I'm really surprised by amounts of chaos that has unfolded in the Manuel discord by the Cheshify~~

**Comment by BlueMemesauce** [comment]
> much more fitting, though it may need some more work and direction from a person that is more versed in music(which i am not). imo the percussion (?) is a bit overbearing

the percussion is fine, i just think its too accented. maybe a softer percussion instrument like the [marimba](https://www.youtube.com/watch?v=3v7QC6Bl_7E)

**Comment by TheSmallBlue** [comment]
This is with a marimba instead of a vibrophone:
https://vocaroo.com/1lzaRrjdqKtn
If it does sound better I'll replace it, but I think it sounds MORE accented than the vibrophone

**Comment by BlueMemesauce** [comment]
Yea just leave it as the vibraphone

**Comment by BlueMemesauce** [comment]
I made it sound more crappy by just applying a filter curve preset https://vocaroo.com/1c0c5dKEgL3n 
I think cutting out the highs and lows also helped make it sound less harsh. You could probably make it crappy in a good way but I just made a demonstration using this preset. 

<details>
  <summary>The Audacity!</summary>

image
</details>

**Comment by TheSmallBlue** [comment]
I don't think its that necessary, the song already has a high pass filter, and in game its also filtered to hell and back

**Comment by MrDoomBringer** [comment]
massive massive amounts of soul

**Comment by JohnFulpWillard** [comment]
I like this but I still can't stand the fact it's only being played in one ear holy crap

**Comment by TheSmallBlue** [comment]
Doesn't change much im afraid

**Comment by DrDiasyl** [comment]
> I like this but I still can't stand the fact it's only being played in one ear holy crap
> 
> The fix to this I believe is the ``direct`` var on sound loops

#75464 will deal with this

**Comment by TheSmallBlue** [comment]
Ok so funny story, turns out I wasnt the only one that came up with this idea, @cats4gold came up with literally the same thing, title2 and all, so I suggested the idea of combining both songs, and they did! So here's an even MORE updated video:
https://youtu.be/BNQmTe553lU
And here's a link to the NEW song:
https://vocaroo.com/1idoRor8G1xY

Huge shoutouts to them they're awesome as fuck this sounds sick

**Comment by DrDiasyl** [comment]
> Ok so funny story, turns out I wasnt the only one that came up with this idea, @cats4gold came up with literally the same thing, title2 and all, so I suggested the idea of combining both songs, and they did! So here's an even MORE updated video: https://youtu.be/BNQmTe553lU And here's a link to the NEW song: https://vocaroo.com/1idoRor8G1xY
> 
> Huge shoutouts to them they're awesome as fuck this sounds sick

Hell yeah, bossa nova

**Pull request merged**
