### PR TITLE
(!!!) FEATURE FREEZE FOR THE MONTH OF DECEMBER IS ---> ACTIVE <--- (!!!)

### PR DESCRIPTION
**Pull request by Mothblocks**
We are instituting a code freeze for the month of December. This PR will be updated when the code freeze is underway, as well as being paired with a message in #maintainer-bus.

# Da Roolz

- New PRs with Mechanic, Content Expansion, QoL, or balance will be closed.
- Bug fixes, refactors, code improvements, etc are allowed. Pure sprite changes should also be fine.
- Pull requests before the freeze are exempt from the freeze. Please do not use this to bombard November 30th with last-minute PRs.
- No large map changes, other than improvements to existing content.
- Converting old UIs to tgui is considered a refactor, and allowed. Look at this picture Armhulen took of me saying it with my cute Aspev profile picture:

image

- Don't use the feature freeze to work on features and just wait until January 1 to upload them
image
image

### CODE REVIEW

**Comment by MetalClone** [comment]
no christmas gifts I see

**Comment by Mothblocks** [comment]
for christmas i want the traits and signals files split into folders

**Comment by timothymtorres** [comment]
What happens if all the issues get fixed before Christmas

**Comment by Mothblocks** [comment]
Then u get a prize

**Comment by LemonInTheDark** [comment]
So true

> 
> 
> for christmas i want the traits and signals files split into folders

Muh workflow

**Comment by MetalClone** [comment]
is the prize a christmas gift?

**Comment by Iamgoofball** [comment]
What is this freeze's goal like the other freezes?

**Comment by Timberpoes** [comment]
The goal is just a breather to keep burnout at bay over the Christmas period. It was discussed in a (now archived) thread in maint-bus on Discord.

Less need to debate game balance, game design and design documents.

More PRs that are just pure code review and merge with less mental floss required afterwards.

Give the team's batteries a chance to recharge over the Christmas period.

**Comment by TheBonded** [comment]
The feature freeze should be frozen for december 24 and 25 to let people make cool features and stuff. Consider it a christmas gift to the coding community?

**Comment by JohnFulpWillard** [comment]
> The feature freeze should be frozen for december 24 and 25 to let people make cool features and stuff. Consider it a christmas gift to the coding community?

Maintainers should be spending christmas merging my PRs, not spending time with their families.

**Comment by Mothblocks** [comment]
If your PR is substantially interesting enough to warrant bypassing the freeze, you can contact maintainers, but it's unlikely Christmas will be an exception.

**Comment by Tennessee116** [comment]
> > The feature freeze should be frozen for december 24 and 25 to let people make cool features and stuff. Consider it a christmas gift to the coding community?
> 
> Maintainers should be spending christmas merging my PRs, not spending time with their families.

Families? Those only exist in the game.

**Comment by Orchian** [comment]
GBP didn't do its job then eh? Who'd've thought.

**Comment by LemonInTheDark** [comment]
The prices will rise until the features stop

**Comment by Bawhoppen** [comment]
> The prices will rise until the features stop

I'm excited for us to finally be feature-complete

**Comment by SweptWasTaken** [comment]
> 

Then we can start implementing microtransactitons

**Comment by Mothblocks** [comment]
ezgif-2-e4c770e578cb

**Comment by LemonInTheDark** [comment]
We could just keep going you know. It's been so nice

**Comment by OrionTheFox** [comment]
> We could just keep going you know. It's been so nice

no please I need to add the Hat Stabilizer module for MODsuits

**Comment by Mothblocks** [comment]
The balls in your court Lemon

**Pull request closed without merging**
