### PR TITLE
Modifies the electrocution damage cap and scaling

### PR DESCRIPTION
**Pull request by Kierany9**
zippity zappity get off my praperty

[Changelogs]: # (Your PR should contain a detailed changelog of notable changes, titled and categorized appropriately. This includes, new features, sprites, sounds, balance changes, admin tools, map edits, removals, big refactors, config changes, hosting changes and important fixes. An example changelog has been provided below for you to edit. If you need additional help, read https://github.com/tgstation/tgstation/wiki/Changelogs)

:cl: Kierany9
tweak: Electric shocks are no longer capped at a measly 90(+-5) damage, with a proper engine setup and hotwiring, electric shocks can now do up to 195(+-5). However, for the most part, shocks do less damage than before at charges under 2 MW.
/:cl:

[why]: # (Please add a short description [two lines down] of why you think these changes would benefit the game. If you can't justify it in words, it might not be worth adding.)

Gives rogue engineers, CEs and AIs more to do with the engine other than immediately cause a delamination or plasma flood and actually engage with the mechanics of their department beyond "open all the plasma valves" or "close all the coolant valves". The old cap is now reached at exactly 2 MW (Up from 900 KW), and the new cap is 195 damage(with a +- 5 modifier, meaning that there's 1/11 chance to instantly die at the new cap) at around 4.3 MW. The minimum shock damage has been upped to 20 and at very low wattages it deals more than before to keep the formulas simple(sorry greytide), but with the safest possible engine setup, the damage is more or less the same than it used to be.

~~It's a web edit, sue me~~

### CODE REVIEW

**Comment by Barhandar** [comment]
Nerf to hacking on pubby because of massive disparity between engine outputs

**Comment by subject217** [comment]
it's not really a big problem with the SME or Singulo because of the radiation collector caps, but with tesla engine this is easily reached.

**Comment by XDTM** [comment]
with enough power in the network you can build electrified grilles around as bootleg supermatter traps

**Comment by BebeYoshi** [comment]
Literally every CE wet dream

**Comment by Kierany9** [comment]
reminder that the SMES (of which there are three between the engine and the grid, four on box) can only output 200 KW each, and that solars don't provide enough power to sustain a 200 KW output, meaning that unless the engineers hotwired the engine to grid, then you're probably not even going to hit the old damage cap.

and if they hotwired the engine, they're either rogue, incompetent or just want to watch the world burn

**Comment by kriskog** [comment]
Do keep in mind that _**unupgraded smes**_ output a max of 200kW. T4 smes output 800kW. Solar smes are also quite likely to gain excess charge so long as the solars are wired and are not the sole supplier of power to the station. 

I had been considering changing the shock cap since I did the powersink changes, making wiring the engine directly to grid more punishing. I decided against it, because shocks are quite honestly just not very fun. Still, I don't fully oppose this as it allows for some shenanigans.

**Comment by Kierany9** [comment]
>Do keep in mind that unupgraded smes output a max of 200kW. T4 smes output 800kW.

>Solar smes are also quite likely to gain excess charge so long as the solars are wired and are not the sole supplier of power to the station.

local man has terrible lapse in judgement
either way, the scaling being lower _should_ prevent baby's first engine from doing too much damage, but if a baby engine plus some shit gotten by waiting around for techweb points to generate is doing more than a hotwired plasma/co2 madman mix, then it seems like t4 SMES are the problem.

>Always hardwire only cowards use smes cells

this is the kind of attitude i wanna see

**Comment by Barhandar** [comment]
SMES aren't the problem, pathetic returns on rad collectors, alternately, ultra insane ones on tesla coils, are the problem. Given how horribad rad collector techweb point generation is, I think the former is more likely.

**Comment by deathride58** [comment]
Just re-add dusting. Make it possible for your arm to straight-up explode when you touch an exposed wire after the engineers flex their collective 'tism

Also @Barhandar rad collector point generation is only pathetic when your setup is pathetic. A tritium hellburn setup combined with numerous ways to maximize radiation can net you an insane amount of research points pretty fast.

**Comment by Barhandar** [comment]
>can net you an insane amount of research points pretty fast.

Can it do that before 20 minutes in the round (read: time to get the actually relevant researches)? Reminder that bombs take 5.

**Comment by YakumoChen** [comment]
Toxins has been a mistake for the entire history of ss13

**Comment by XDTM** [comment]
i think this was fully intentional, instacrit is often as good as death anyway

**Comment by Kierany9** [comment]
@kriskog 
jesus christ i think i pushed the wrong branch or something
> CLAMP(20 + round(avail/25000), 20, 195) + rand(-5,5)
is indeed the intentional formula

@XDTM 
no it's not

**Comment by XDTM** [comment]
My bad i misread the comment

**Pull request merged**
