### PR TITLE
gives SOUL to ancient jumpsuits

### PR DESCRIPTION
**Pull request by Fikou**
## About The Pull Request

the ancient jumpsuit assistants can buy for 20tc instead of being literally just the grey jumpsuit but with a different name and description, has the OLD grey jumpsuit sprite from 2010 goonstation, which also makes sense considering the description

## Why It's Good For The Game

you pay 20tc for a different name and desc

## Changelog
:cl:
imageadd: gives SOUL to ancient jumpsuits
/:cl:

### CODE REVIEW

**Comment by ArcaneDefence** [comment]
I won't respect your attempt to readd soul to the ancient jumpsuit until it makes you say glorf again.

**Comment by Fikou** [comment]
> I won't respect your attempt to readd soul to the ancient jumpsuit until it makes you say glorf again.

dont care didnt ask

**Comment by Ratvar** [comment]
But does it work as a soulstone

**Comment by SweptWasTaken** [comment]
Fuck you

**Comment by anconfuzedrock** [comment]
This suit was supposed to make you say glorf, yes.

**Review by Twaticus — APPROVED** [review]
soul

**Comment by MMMiracles** [comment]
if the suit don't say glorf it has no soul

**Pull request merged**
