### PR TITLE
Goggle resprites... with sovl?

### PR DESCRIPTION
**Pull request by Youtubeboy139**
## About The Pull Request

Two years ago, Onule created fancy looking sprites for the HUDs, Goggles, and NVGs of Space Station 13 which initially popped up in a CEV_Eris `eu_devlog` but were never really used. I decided that they should get some use so with a bit of tweaking and some elbow grease I've created the most sovlful goggle resprite I can accomplish.

Also included are some new sunglasses sprites including fancy aviators for the Bartender as opposed to standard sunhud glasses.

New Goggle Sprites in a Test Session
Screenshot 2023-06-30 205336

New Goggle Sprites
Screenshot 2023-06-30 152856

Hot and Cold Goggle Sprites
Screenshot 2023-06-30 204226
## Why It's Good For The Game

No more legacy sprites, it's the modern age. New sprites for all.
## Changelog
:cl:
image: Added new HUD sprites
image: Added new Goggle Sprites
image: Added new Sunglasses Sprites
image: Added new NVG sprites
image: Removed unused/depreciated sprites in `glasses.dmi`
/:cl:

### CODE REVIEW

**Comment by LemonInTheDark** [comment]
do you have permission from the original author to use their work? was it ever pr'd (and thus properly licensed under cc-by-sa?

**Comment by Youtubeboy139** [comment]
> do you have permission from the original author to use their work? was it ever pr'd (and thus properly licensed to be used/adapted) under cc-by-sa?

Screenshot_20230630-233055_Discord

**Comment by LemonInTheDark** [comment]
pogged

**Review by Wallemations — APPROVED** [review]

**Comment by Wallemations** [comment]
I'm honestly still confused over why the hot & cold goggles don't have any real use
I would have expected them to do something like make it easier to see through ash/snow storms


Either way nice work

**Comment by githubuser4141** [comment]
> I'm honestly still confused over why the hot & cold goggles don't have any real use I would have expected them to do something like make it easier to see through ash/snow storms
> 
> Either way nice work

I think it's supposed to be reminiscent of those really cheap crappy plastic sunglasses that probably don't even have UV protection
eyeglass1
It's like a civilian item mainly for RP/if you want your character to have a specific appearence

**Comment by Youtubeboy139** [comment]
> pogged

I will also say, while the original Goggle sprite I used for reference was created by Onule, I did create custom Goggle sprites so I didn't totally rip from them. NVGs were still made by them however.

Screenshot 2023-07-01 101054

**Comment by SomeoneYouProbablyKnow** [comment]
I was afraid you were going to touch welding goggles, the most soulfull and perfect sprite on the branch. But these are some good looking glasses

**Comment by Youtubeboy139** [comment]
> I was afraid you were going to touch welding goggles, the most soulfull and perfect sprite on the branch. But these are some good looking glasses

Thought about it, couldn't bring myself to change em

**Comment by TheVekter** [comment]
sovl

**Comment by atlasle** [comment]
can we get screenshots of the new sunglasses sprites

**Review by axietheaxolotl — CHANGES_REQUESTED** [review]
is there a specific reason you just. didn't use onule's ones?

i'll be genuine here, Onule's ones were just better, and all you seemed to do was trimmed a pixel (which causes issues we'll get into later), and made the shading on the visor worse.

re: trimming a pixel. the shading was done with those little "stick-outs" in mind, so now there's just a little dark line for ???. aswell, you've turned the highlights into outlines by removing the, actual outlines.
image

and with the visor, you've just removed all the shape and intricacies of onule's one, and made it a directionally shaded blob. the old one had flow, and a defined shape, the new one is just an treading-on-banded mess.

overall, these are "better", but hesitate to say they're "good". hopefully wallem/any other spritetainer will back me up on this but like. I feel like you've turned a great sprite into a kinda meh one. idk.

**Comment by Wallemations** [comment]
Why'd you close this? It was looking alright, just needed the lenses swapped back.

**Comment by Youtubeboy139** [comment]
> Why'd you close this? It was looking alright, just needed the lenses swapped back.

The sunglasses were split from this while I redo this. Wanted to get something pushed.

**Pull request closed without merging**
