### PR TITLE
Corrects Duplicate Key + Location Logging in Suicides and Deaths

### PR DESCRIPTION
**Pull request by bobbah**
## About The Pull Request

denton's change broke these logs, by running them through log_message() they get a second set of key and location tagged on before calling to log_attack() regardless. (https://github.com/tgstation/tgstation/pull/45779)

## Why It's Good For The Game

fixes bug in logging

what it looks like with the bug:
```
[2019-10-31 00:26:25.278] ATTACK: Syruse Eln/(Bob Oakland) Syruse Eln/(Bob Oakland) (job: None) committed suicide at Cloning Lab (94, 94, 2). (Cloning Lab (94, 94, 2))
```

what it should look like:
```
[2019-10-31 15:25:30.724] ATTACK: Bobbahbrown/(Joel Judge) (job: Atmospheric Technician) committed suicide (Atmospherics (146, 89, 2))
[2019-10-31 15:25:30.726] ATTACK: Bobbahbrown/(Joel Judge) has died (BRUTE: 0, BURN: 0, TOX: 0, OXY: 200, CLONE: 0) (Atmospherics (146, 89, 2))

```

## Changelog
:cl:
fix: Fixed duplicate client and location logging for suicides and deaths.
/:cl:

### CODE REVIEW

**Comment by bobbahbrown** [comment]
@nfreader i doubt this breaks anything for you, but worth noting

**Comment by AnturK** [comment]
This will not add them properly to round-only logs.

**Comment by Cyprex** [comment]
Round-only individiual logs are accessed via Player Panel->View Logs

**Comment by bobbahbrown** [comment]
fixed

image

**Comment by nfreader** [comment]
No effect on Statbus but thanks for the heads up :)

**Pull request merged**
