### PR TITLE
Adds Icons to Crew Monitor Console

### PR DESCRIPTION
**Pull request by E231kei500bandai**
## About The Pull Request

Ports this Pull Request from Skyrat: https://github.com/Skyrat-SS13/Skyrat-tg/pull/12744
They said it wouldn't work on TGStation for some reason but I don't know why they said that because everything works and there's no reason it shouldn't. 

My test picture on TG:
image
Skyrat picture which neatly shows all the icons:
image

- Replaces the vague ColorBox in the Crew Monitor Console with icons that are more descriptive 
- Centers the title text in the Crew Monitor Console
- Replaces the N/A text with a Question Mark

## Why It's Good For The Game

The ColorBox was vague and unclear to understand. Adding icons will make it simpler to understand the state of people tracked on the Crew Monitor Console.

## Changelog

:cl:
expansion: Replaces the ColorBox in Crew Monitor Console with various Icons
expansion: Replaces the N/A for unknown locations in Crew Monitor Console with a Question Mark
spellcheck: Centers title text in the Crew Monitor Console
/:cl:

### CODE REVIEW

**Comment by Zergspower** [comment]
In Reference to why, we have robotic code that puts additional icons present 
image

**Comment by Zergspower** [comment]
> 

And you may want to move it to 25/5 to fit TG's health pool - else you may not get the critical heart icon (dated screenshot I dont have sadly, but it replaced the crutch)

**Comment by BlueMemesauce** [comment]
I just copied over everything except the robot parts and it works

**Review by stylemistake — APPROVED** [review]

**Comment by OrionTheFox** [comment]
> I just copied over everything except the robot parts and it works

It would have worked fine, that wasnt the issue.
The issue would have been due to skyrat's modular file overwriting this. So even with a mirror PR, skyrat'd just have to change their modular file again regardless.

**Comment by iprice** [comment]
The column width allocation is bad, the location column is always very thin and wraps people on to multiple lines.

No matter how wide you make the window, all free space is allocated to the name column, which ends up looking kind of silly.

Ultimately fits less people on one "vertical page" than it did before which unfortunately makes this a downgrade in functionality.

I'll attach a relevant screenshot after the round.

**Pull request merged**
