### PR TITLE
New Fire Alarm Sound

### PR DESCRIPTION
**Pull request by san7890**
## About The Pull Request

New Fire Alarm Sound! You can listen to the original OGG file by downloading it.

A special thank you to @Capsandi for creating this new sound.

## Why It's Good For The Game

I'm going to be real, the "ping ping ping ping" sound is a shrill sound that mimicks the fire alarms that we have in the present day. Fire alarms are meant to be annoying, and the old sound did do a good job at that. However, I think that a deeper, bassier, rattley, and perhaps even a bit haunting of a sound fits the sci-fi setting. When I was discussing it with the author of the sounds, I likened it to turning off an annoying ringtone that you have and just putting your phone on vibrate. It's a substitution that I think works for the better.

I don't find it annoying (personally), but it still does elicit the same sense of urgency. I don't think there's any way to abate Alarm Fatigue with the sound itself, because the alarm sound itself doesn't cause fatigue, it's just triggering it that sets it off (which needs to be fixed with fire lock behavior, which is currently being worked on by Zxaber).

## Changelog

:cl: san7890, sounds courtesy of Capsandi
soundadd: Nanotrasen has sourced fire locks from a new vendor, on the cheap, and nearly identical to the ones on past stations. Assistants describe the new sound as "throaty" and "bassy".
/:cl:

### CODE REVIEW

**Comment by TheSilverNuke** [comment]
Not certain about this one. While the current one is relatively high pitched this one goes in the complete opposite direction and honestly sounds like it has broken audio. I'd say clean it up a bit and it might be viable.

**Comment by san7890** [comment]
> Not certain about this one. While the current one is relatively high pitched this one goes in the complete opposite direction and honestly sounds like it has broken audio. I'd say clean it up a bit and it might be viable.

The broken audio is probably due to the mp4 embed. I'm going to delete that from the PR body, please listen to the original OGG.

**Comment by Dorsisdwarf** [comment]
A third of the runtime of this sound is dead space at the end.

I also just dont really like the idea of turning the piercing "FIRE TIME" noise into a soft low buzz that's only slightly off-key

**Comment by ComboTombo** [comment]
May I recommend something similar to the idea you're trying to achieve? https://archive.org/details/GeneralQuartersBattleStations

**Comment by EricZilla** [comment]
Replacing annoying beep beep with a sound that feels like the station is gonna explode

I like it

**Comment by san7890** [comment]
We've updated and standardized the sound in this latest commit. Please re-listen if there was some confusing noises/gappage to the alarms.

**Comment by wesoda25** [comment]
Could you post a video/audio of it in game? I don't think the sound file alone really accurately portrays what it will be like.

**Comment by san7890** [comment]
> Could you post a video/audio of it in game? I don't think the sound file alone really accurately portrays what it will be like.

https://user-images.githubusercontent.com/34697715/148634348-7f6d3879-dcd1-4bdc-b2b9-1814a94ce222.mp4

I'm unsure if it's too quiet, now.

**Comment by TheSilverNuke** [comment]
Honestly I don't really think this sound fits thematically with the kind of codebase TG has. It sounds like it might be more appropriate for something like, CM or Bay. I think a test merge would be appropriate personally before it's full merged considering just how frequently fire alarms go off in-game.

**Comment by san7890** [comment]
> Honestly I don't really think this sound fits thematically with the kind of codebase TG has. It sounds like it might be more appropriate for something like, CM or Bay. I think a test merge would be appropriate personally before it's full merged considering just how frequently fire alarms go off in-game.

It would probably have to be done in conjunction with future TMs of #62055 (or however they're going through it).

**Comment by Dorsisdwarf** [comment]
man, that video has the _fire alarm_ barely audible with the sound maxed out (Also the tone change still sucks and is worse than the same tone repeating would be). It's the same volume as the footsteps.

**Comment by san7890** [comment]
I'm away from my computer, but newer sounds are pending (can't mark as draft on mobile GitHub)

**Comment by san7890** [comment]
Capsandi got back to us with a louder volume. Each of the four buzzes are now the same tone rather than have two different tones cycle in-and-out (we can change if you guys actually liked that). Video below for new reference.

https://user-images.githubusercontent.com/34697715/148703200-3dcf79dd-bf89-46af-a09a-084ad814e1ce.mp4

**Comment by Likteer** [comment]
https://user-images.githubusercontent.com/68878861/148799381-26757139-417a-4e9b-8da5-725f0af8391a.mp4

**Comment by LemonInTheDark** [comment]
You made it an actual alarm. Thank you.

**Pull request merged**
