### PR TITLE
TGUI input conversions 3: Say/Me/Whisper/OOC

### PR DESCRIPTION
**Pull request by jlsnow301**
## About The Pull Request
You read the title
This could really go one of two ways...

- Say, me, whisper, and OOC are converted to TGUI input
- This also ensures the text input modal (itself) sizes appropriately when the prompt is null
- Text input now responds to the escape key

## Why It's Good For The Game
Input in SS13 is pretty ugly and TGUI is just more thematic
Much more flexibility for filtering input if ever needed

## Changelog

:cl:
refactor: Speech verbs have been converted to TGUI.
/:cl:

### CODE REVIEW

**Comment by JohnFulpWillard** [comment]
holy shit its happening

**Comment by tralezab** [comment]
@Mothblocks isn't home right now but told me to close this for a serious issue that I also see. That issue is the fact that this introduces a delay of ping to chatting, and that's... unsolvable right now. If you have a solution for how to solve that, you should let mb know

**Comment by Iamgoofball** [comment]
For the record, I've had absolutely zero lag issues with any of the tgui input conversions so far. Every single time I've hit a button or clicked a thing or did anything that popped up a tgui input box of some kind, it's been instant and I've felt absolutely no delay, both on having it pop up and on sending the input I've entered.

Even on our downstream with the lag problems.

**Comment by stylemistake** [comment]
There is a way to make tgui open up with no lag, and that involves byond macros and using the output verb to send a message to tgui.

This requires a specially crafted tgui window to live in background and listen for such messages, and you really only need one, because you almost never type multiple messages at once. But it's going to end up with a lot of code, no doubt.

**Comment by Mothblocks** [comment]
It's not unsolvable, no. 

I'd rather a serious structure be done for sending these verbs from the client, completely predicted, so that we can at least have some reason to want them aside from them being a black box

**Comment by stylemistake** [comment]
can be coded on byond global, smth like `Byond.output(id, str)` or higher level `Byond.sendMessage(id, { ... });`.

**Pull request closed without merging**
