### PR TITLE
removes Just Xrays

### PR DESCRIPTION
**Pull request by Iamgoofball**
haha yeah these ruin everything

if all R&D gun removal doesnt go through this should be fine

### CODE REVIEW

**Comment by evsey9** [comment]
should make blob/clock cult take ACTUAL SKILL to beat, so.

**Comment by Kromgar** [comment]
Blob unstoppable now if it gets too big

**Comment by evsey9** [comment]
thats what the nuke is for

**Comment by Kromgar** [comment]
@evsey9 9/10 times captains corpse gets blobbed and his corpse is running around in the blob with the disk

**Comment by Iamgoofball** [comment]
Sounds like a player problem

**Comment by kevinz000** [comment]
Eh yeah sure x-rays are retarded op with new radiation and they're unfun most of the time

**Comment by kevinz000** [comment]
Also get good if you can't take out a blob without xrays

**Comment by nicbn** [comment]
Didn't even compile

**Comment by GuyonBroadway** [comment]
Back in mah day we sent armies of durands to stomp out a blob!

**Comment by ExcessiveUseOfCobblestone** [comment]
Why not give xray decreasing damage for every item it passes through an item or just lower their clip to like 1 shot per recharge?  

It's a pretty standard sci-fi theme weapon.

**Comment by Iamgoofball** [comment]
@ExcessiveUseOfCobblestone 
thats just a bandaid for the underlying issue of being able to bypass the only limit on projectile weapons

**Comment by ExcessiveUseOfCobblestone** [comment]
what limit are you referring to?

**Comment by Iamgoofball** [comment]
the fact they can't go through solid objects like walls/people

**Comment by ExcessiveUseOfCobblestone** [comment]
That's the whole point of the gun?

It's not bandaid to ask for it to do decreasing damage as it passes through objects, that's called balancing it over outright removing it.

**Comment by Iamgoofball** [comment]
It's almost like it's a bad gun concept or something

**Comment by nicbn** [comment]
What if we nerf it to do like 1/10 th of the damage?

**Comment by Iamgoofball** [comment]
Missing the point

**Comment by nicbn** [comment]
It's not useless if you gear up 10 people with them
In this case you have the equivalent to today's xray gun

**Comment by Iamgoofball** [comment]
Once again proving it's a shit concept

**Comment by ExcessiveUseOfCobblestone** [comment]
It's a staple Sci-Fi gun and other games have balanced them just fine.

**Comment by Iamgoofball** [comment]
No other game is like ss13

**Comment by feemjmeem** [comment]
what problem are you trying to solve

just make them harder to get

what the hell goof

**Comment by Iamgoofball** [comment]
Time delays aren't a fix

**Comment by KorPhaeron** [comment]
Its a gun with no counterplay that just nukes people through walls and ruins one antagonist type so hard it couldn't function as its own mode anymore what do people find redeemable about that

**Comment by XDTM** [comment]
>There is _no possible way_ they could ever be balanced except for removing

What if they got absorbed by organic targets, meaning they could pierce walls et cetera, but at most one or two mobs? it'd make it not instawin against a blob, but keep a niche as an advanced weapon, as it would let you shoot people who would normally be unattackable from range

**Comment by XDTM** [comment]
Remove rads tho

**Comment by KorPhaeron** [comment]
Someone should open a competing PR then

**Comment by PopNotes** [comment]
haha no

**Review by imtakingabreakdontatme — APPROVED** [review]
If nobody figures out a way to balance xrays within the next few days I'll be merging this

**Comment by DoctoreMad** [comment]
@KorPhaeron B L E S S E D

**Comment by jughu** [comment]
Heres a idea blob chem titanium blob reflects ALL energy ptojectiles but takes 4x brute

**Comment by AnonymousNow** [comment]
X-rays are cool, and removing them outright is silly. However, they are the bane of blob rounds, and even the smartest blob with the best start can get fucked over by them.

Better solution than removal: gate them better. Ridiculous amounts of materials. Special high-security firing pin required. Require literally maxed (as is possible in a round without admin intervention) research to manufacture. Make them unprintable, and put one in a random space ruin.

**Comment by duncathan** [comment]
all these idea guys spouting nonsense instead of making alternative PRs smh

remove, don't improve.

**Comment by Iamgoofball** [comment]
👏time👏gates👏arent👏a👏bugfix👏its👏a👏delay👏on👏the👏bug

**Comment by AnonymousNow** [comment]
Ugh, "remove, don't improve" is a pretty nauseating heel-turn on the mantra.

X-ray lasers aren't bugged, as far as I can see - they're just disproportionately powerful for the effort it takes to get them. Better gating is a logical response to this. Or the notion of it getting weaker over multiple targets, or against organic targets.

Radiation, and its interaction with it, could be considered a bug. But that's not being addressed here, just glossed over.

**Comment by duncathan** [comment]
Improve don't remove is a meme proliferated by idea guys and powergamers, not the maintainer team.

**Comment by Bawhoppen** [comment]
@ExcessiveUseOfCobblestone It already works like that I believe actually. There was a PR to make it work like that atleast at one point.

**Comment by Qbopper** [comment]
improving things is cool because then it means we get more cool shit instead of taking things out at the first sign of a problem, it's not a power gamer thing

that being said you need to know when something needs to be removed and not refuse to take anything out

**Pull request closed without merging**
