### PR TITLE
Fixes being unable to merge full stacks

### LINKED ISSUE #31984: Borgs unable to pick up full cable coils
Issue reported from Round ID: 77762 (Sybil)

Engiborg can't refill it's wire module by clicking on cable coils with 30 wires on it, any less works fine, so they have to alt-click it to take a few off before being able to pick it up. No error message shows up when you try to pick up a full coils.

### PR DESCRIPTION
**Pull request by YPOQ**
Fixes #31984

### CODE REVIEW

**Review by Cyberboss — APPROVED** [review]

**Comment by ShizCalev** [comment]
Does this fix the issue #31742 closed since it's reverting it?

**Comment by YPOQ** [comment]
Yes, the message will only print if some of the stack is transferred.

**Comment by YPOQ** [comment]
Wait I didn't actually read this issue. I don't think #30055 should have been closed since it's an issue with new items being merged and has nothing to do with attackby().

**Comment by YPOQ** [comment]
Okay I was wrong again.  #30055 was indeed fixed and this PR will not re-open it.

**Comment by praisenarsie** [comment]
90% sure it was fixed considering i am praiseratvar and i tried crafting it ingame recently.

**Pull request merged**
