### PR TITLE
Add station trait for varying colored assistant jumpsuits

### PR DESCRIPTION
**Pull request by Mothblocks**
## About The Pull Request
Adds a new station trait to color the assistant jumpsuits semi-randomly.

There are several styles for it to choose from, including some especially colored ones, and some randomized ones. This includes the current alternative rainbow jumpsuits, but if `GREY_ASSISTANTS` is not enabled, then grey jumpsuits will be a valid random option.

I don't really want to hear too much more about the config, I got the OK on this from head admins.

## Why It's Good For The Game
Adds more variety to look at on assistants, while still mostly preserving a consistent style if `GREY_ASSISTANTS` is enabled (as it is a station trait).

## Changelog

:cl:
add: Added a station trait for varying colored assistant jumpsuits.
/:cl:

### CODE REVIEW

**Comment by optimumtact** [comment]
this is a config though

**Comment by Mothblocks** [comment]
For extra context--Rave specifically requested this, and it was the resolution on the "[Turn rainbow assistants on](https://tgstation13.org/phpBB/viewtopic.php?f=33&t=30264)" policy thread

**Comment by optimumtact** [comment]
this is a config though

**Pull request merged**
