### PR TITLE
Moves fake emag close inspection message from desc to close examine

### PR DESCRIPTION
**Pull request by cacogen**
## About The Pull Request

I saw this and given we have close examines (which I learnt making this are barely used) I thought it'd make more sense to add it to that.

## Why It's Good For The Game

Without using the emag, you have to actually look at it closely to determine whether it's fake.

## Changelog
:cl:
balance: Fake emags have to be examined closely to determine whether they're fake (you can still test them, obviously)
/:cl:

### CODE REVIEW

**Comment by coiax** [comment]
I'm not sold on this, examine more isn't... really used that much.

**Comment by Ryll-Ryll** [comment]
The idea behind examine_more (which let's face it, I only really made for showing scars) is that you'd get some kind of line in the normal examine saying that there's more info available if you look again (the extra info presumably being more than the 1 line it took to tell you this).

That said, if you did put a line in the normal examine telling you to look closer just for it to tell you it's fake, that'd be pretty funny in a meta way

**Comment by Qustinnus** [comment]
examine more isn't used much because using it is unwieldy.

**Comment by cacogen** [comment]
I agree it's clunky and could be better but I don't think that's an issue preventing this being merged

**Pull request closed without merging**
