### PR TITLE
Punpun's waiter uniform sensors will be off by default now

### PR DESCRIPTION
**Pull request by strandsofivy**
## About The Pull Request

Does what it says on the tin.

## Why It's Good For The Game

Fixing CMS clutter

## Changelog

:cl:
qol: Punpun's sensors will be off by default now.
/:cl:

### CODE REVIEW

**Comment by GuillaumePrata** [comment]
The best part of the waiter uniform PR is this, ~~valid hunt people that harm Pun Pun~~ having Pun Pun on the CMS and going out of your way to keep them alive for the entire shift.

So while I agree that this change would be good to keep things clean in the CMS, we will lose all the funny interactions that would happen around a dead Pun Pun on the sensors.

**Comment by 13spacemen** [comment]
Agree with @GuillaumePrata, treating Pun Pun like a real person leads to cool and funny interactions

**Comment by ShizCalev** [comment]
I agree with Guillame, it's vital to keep /all/ members of the crew alive!

**Comment by distributivgesetz** [comment]
why protect the creation of game soul as a coder, wth?

**Comment by JohnFulpWillard** [comment]
I find Pun pun being on suit sensors to be funny enough to keep around. It's currently the only station 'pet' that does this, so it's unique to them and isn't really bothering Medical much or being just clutter.

**Pull request closed without merging**
