### PR TITLE
[MAP] Security Morgue | Minor Armoury Reshuffle

### PR DESCRIPTION
**Pull request by Steelpoint**
This PR adds or changes three items.

(Inb4 "Lol he codes 4 buff himsefl :)")

1:) A new Security Morgue has been added to the brig, located outside the 'Prisoner Transfer Centre' this morgue holds two trays and is also off the record.

screenshot 2015-07-07 22 46 47

(Missing are the vent's and the hallway light)

2:) The Armoury's Security Hardsuits have been moved away from the external space facing wall and moved inwards. The main reason here is that in many circumstances where the hardsuits are needed, odds are they have been destroyed from a explosion or are inaccessible due to space exposure. Stealing of the hardsuits is a non-issue since anyone who can get to them from the outside already has a space suit and anyone who can get to them from the inside don't really care where the hardsuits are.

screenshot 2015-07-07 23 00 05

3:) Adds one First Aid Kit to the Warden's office, this is a oft requested feature and I'm happy to oblige. Not to mention that someone else made it their mission to sprinkle medkits around the station but ignored the brig.

Its not uncommon for me to witness a Warden leave the brig to nab one of the 'public' medkits, so this should help in that regard.

### CODE REVIEW

**Comment by Ikarrus** [comment]
Security is even too lazy to go to medbay to store their murders?

Why dont we just give security their own station at this rate

**Comment by Ikarrus** [comment]
It doesn't need to be r-walled either.

>Vault for storing bodies

**Comment by Steelpoint** [comment]
Its a more official place to store executed prisoners instead of leaving the body to rot in a bodybag somewhere in the brig.

Also I added r-walls to replace the r-walls that the insanity wall had.

**Comment by Steelpoint** [comment]
Taking executed prisoners to the medical morgue is just asking for them to be cloned, I should not have to explain that concept.

**Comment by bgobandit** [comment]
Metastation already has a security morgue IIRC, this isn't that major or unprecedented a change

**Comment by Steelpoint** [comment]
Metastation does, in fact their morgue is actually a mini medical centre, though the only functional difference is that MetaBrig has one morgue tray and two medkits while we (may) get two morgue tray's and one medkit.

**Comment by Cheridan** [comment]
Lol he codes 4 buff himsefl :)

**Comment by Alek2ander** [comment]
>off the record
>glass airlock

**Comment by Steelpoint** [comment]
I should clarify off the record meaning there's no security camera.

**Comment by Steelpoint** [comment]
I'm also tempted to follow Metastation's lead and just move the hardsuits out of the armoury, but I'll stick to one thing at a time.

**Comment by SconesC** [comment]
Armory reshuffle is nice because that's an actual issue

**Comment by whodaloo** [comment]
the medkit and suits being moved are good but putting a morgue in sec is a really really dumb idea

**Comment by PKPenguin321** [comment]
i always figured the suits being blown up in armory explosions from space was like, half the reason you'd even bomb the armory from space (instead of just breaking in), so that sec couldn't chase you out

**Comment by Steelpoint** [comment]
The Hardsuit issue is akin to placing the sole fire extinguisher right next to a dangerous fire source.

The only way to solve the issue would be to go for the meta way and make a small Hardsuit storage room that's not connected to the armoury.

**Comment by Dorsisdwarf** [comment]
Hardsuit storage sucks.

**Comment by Steelpoint** [comment]
Why was a PR that was put up after mine merged ahead of mine?

Come on guys, what's the point of getting in first if someone else ahead of you gets merged.

**Comment by Steelpoint** [comment]
Merge conflicts fixed.

**Comment by WJohn** [comment]
Also I forgot to ask: Did you change the area for the security morgue to be part of permabrig or whatever area governs most of that whole area?

**Comment by Steelpoint** [comment]
Morgue uses the normal perma brig area.

**Comment by xxalpha** [comment]
No to morgue.

**Comment by Steelpoint** [comment]
Why exactly?

**Comment by xxalpha** [comment]
You can just throw people out and also silicons can look in there and figure out that the prisoner transfer room is not an actual transfer room.

**Comment by Steelpoint** [comment]
Taking a executed prisoner to the medbay morgue will guarantee them being cloned.

This morgue at least offers a official way of storing executed prisoners.

**Comment by xxalpha** [comment]
Nobody cares about morgue. You can also use the chapel services of body disposal. We don't need yet another morgue.

**Comment by Steelpoint** [comment]
If nobody cares then why did I put up this PR?

This is not a major addition and to be frank many other maps have a sec morgue. This is a nice feature that offers a official place to store the dead in a secure location instead of just chucking their corpses off the station.

**Comment by xxalpha** [comment]
Because you like security to have everything. Security can't have everything. Security is part of a whole station.

Use chapel if you're afraid of cloning. Incineration or spacing.

**Comment by Steelpoint** [comment]
Again, this is not a major change that many other maps use. The alternative is that the body rots in the execution chamber or is chucked off station, at least here the body has a chance of being stored away properly. 

Also please avoid attacking my character, it makes your argument weaker.

**Comment by xxalpha** [comment]
At the very least change the airlock to solid and remove the space rwalls.

**Comment by xxalpha** [comment]
All the rwalls, in fact. Morgue doesn't need rwalls.

**Comment by Steelpoint** [comment]
The Rwalls are a replacement for the Insane Ward's space facing Rwalls.

**Comment by xxalpha** [comment]
Okay but those can go.

**Comment by Miauw62** [comment]
yeah make the door solid and remove the rwalls.

**Comment by Steelpoint** [comment]
That should fix the merge conflict, as well as swapping the door and removing the excess Rwalls.

**Comment by Steelpoint** [comment]
Inb4 merge conflicts

**Comment by Steelpoint** [comment]
Can someone at least remove the "merge conflict" tag? Though at this rate this PR's going to be more about fixing merge conflicts than actually merging it.

**Comment by Ikarrus** [comment]
@Steelpoint I take issue with your way of resolving map conflicts by reverting other people's changes.

**Comment by Steelpoint** [comment]
I don't intentional remove anything, I resolve my merge conflict by letting git override any of my own changes with the most recent code, then I copy+paste my changes to the map as needed.

**Pull request merged**
