### PR TITLE
Security Aesthetics Improvement Finale (LAP 2)

### PR DESCRIPTION
**Pull request by Imaginos16**
## About The Pull Request
No parts to this, no bullshit, straight to the point.

This PR finishes respriting things that weren't tackled by either me or Viro recently, with the exception of the riot and bulletproof gear.

image

Head of Security outfits received a general upgrade (including a global redo of the beret to fit better shading standards)

image

The same goes for warden clothing (Obj sprite now properly reflects the appearance of the mob sprite)

image

image

Security officer clothing (including jackboots and vest) have also received upgrades, with either minor reshades, or complete overhauls to their styling.

image

Aerostatic Suit has been edited into a shirt, to better reflect the reference character's default outfit, which is a plain white shirt, and not a button-up. The vest has also been resprited into a flak vest!
## Why It's Good For The Game
They're definite improvements three months in the making. I hope to god that this time, they actually last, in this never-ending race to out-do myself and the competition!
## Changelog
:cl: PositiveEntropy
imageadd: Tweaked, Overhauled and Resprited a variety of garments related to the security department, particularly its alternate clothes! Check it when possible!
/:cl:

### CODE REVIEW

**Comment by CRITAWAKETS** [comment]
i just have one singular comment about all of this
DONT YOU DARE PUT RED ON JACKBOOTS

**Comment by Imaginos16** [comment]
Those were jackboots that are specific to security only and have existed for six months already, while a regular version is still readily available and easily accessible. Please play the game to know that they've already been around, and don't post in all caps. Thank you.

**Comment by CRITAWAKETS** [comment]
oh right, forgot about those since i dont play sec like at all

**Review by Twaticus — APPROVED** [review]

**Comment by ERCERCER** [comment]
These are all really good, EXCEPT the detective armor vest, i don't even know what its supposed to be, some weird plate thing, the old sprite was superior in every way.

**Comment by SinfulBliss** [comment]
It looks like sec lost one of their types of beret colors also. The light blue is the corporate one but it's nice having the dark blue to match the dark armor vest (if you don't want to wear corporate but still want a beret).

**Pull request merged**
