### PR TITLE
Community PR 1, without the crates

### PR DESCRIPTION
**Pull request by coiax**
It's just like #16773 except without the abandoned crates, and no merge conflicts.

:cl: Iamgoofball, Lati, Geo_Jerkal, Tanquetsunami25
rscadd: Lati requested that the Slime Processor will now automatically scoop up any dead slimes into itself for processing.
rscadd: Geo_Jerkal requested that you be able to mix Arnold Palmers with Tea and Lemon Juice.
rscadd: Tanquetsunami25 requested that cyborg be able to boop.
/:cl:

### CODE REVIEW

**Comment by PKPenguin321** [comment]
RIP goofball

**Comment by ChangelingRain** [comment]
rip goof

**Comment by Iamgoofball** [comment]
>both were merged

What is this foul sorcery

**Comment by coiax** [comment]
Goof, I'm pretty sure it's because my PR contains all the commits that your PR does. So by having mine merging into master (which I literally only did because I thought you were like away or something, apologies, didn't mean to step on any toes), merges yours also effectively.

**Pull request merged**
