### PR TITLE
Fixes phobia word recognition

### LINKED ISSUE #35533: Issue with saying certian words after being abducted
Issue reported from  Round ID: 83421 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 511

[Round ID]: # (If you discovered this issue from playing tgstation hosted servers:)
[Round ID]: # (**INCLUDE THE ROUND ID**)
[Round ID]: # (It can be found in the Status panel or retrieved from https://atlantaned.space/statbus/round.php ! The round id let's us look up valuable information and logs for the round the bug happened.)

[Testmerges]: # (If you believe the issue to be caused by a test merge [OOC tab -> Show Server Revision], report it in the pull request's comment section instead.)

[Reproduction]: # (Explain your issue in detail, including the steps to reproduce it. Issues without proper reproduction steps or explanation are open to being ignored/closed by maintainers.)

[For Admins]: # (Oddities induced by var-edits and other admin tools are not necessarily bugs. Verify that your issues occur under regular circumstances before reporting them.)
Got abducted, was "afraid of security" afterwards and couldn't say security related words like "hos" but this also included words with "hos" in them, like "those".

### PR DESCRIPTION
**Pull request by Tacolizard**
:cl: Tacolizard Forever
fix: phobias will no longer recognize trigger words inside of other words
/:cl:

fixes #35533

### CODE REVIEW

**Comment by XDTM** [comment]
This will mess with verbs, since "slip" will no longer catch slipping, slipped, and so on. Also i'm rusty on regex, will that check catch words with punctuation around? ("Slip.")

**Comment by Tacolizard** [comment]
@XDTM yes, it captures everything that isn't a letter

**Comment by Tacolizard** [comment]
Okay I went through and changed the phobia words list so now it includes verbs. I also made it so that the regex catches plurals

**Comment by XDTM** [comment]
It's not appearing in the changes list

**Comment by Tacolizard** [comment]
@XDTM strange. lemme redo it

**Pull request merged**
