### PR TITLE
HoS, warden and officers no longer spawn with a stunbaton in their bags.

### PR DESCRIPTION
**Pull request by Ghommie**
## About The Pull Request
The HoS, warden and officers no longer spawn with a stunbaton in their bags.

## Why It's Good For The Game
More often than not, we end up with every security role (minus det) having two stunbatons since both their outfits and their closets have a stunbaton. This entails situations in which power cell drainage or losing the first stunbaton in a way that doesn't result in them becoming the receiving end of the stick would hardly impact their gameplay because of the backup one in their bag. It's also worth mentioning stunbatons are pretty powerful (the nerf they received 2 years ago helped, but the time window between the first and second hit is damn short) and most of their supposed counters (like stims, maint pump-up) barely help against the stamina loss and the knockdown right now.
In short, getting in a melee scuffle an officer can be tough, disposing his baton only for him to whip out another is just frustrating.
This also means they won't be as battle-ready but the chances are they'll take a walk to the brig and gear up anyway. It also adds a scarcity factor. Any extra security baton taken is a baton deprived from new officers, so that security and his officers have a reason to order stunbatons from cargo and interact with one another, but i'm just speculating here.
Here's Orange's blessing:
citrus hath spoken

## Changelog

:cl:
balance: The HoS, warden and officers no longer spawn with a stunbaton in their bags.
/:cl:

### CODE REVIEW

**Comment by JohnFulpWillard** [comment]
the massive hos buff was uncalled for but generally this really feels needed. Is cargo still the only way to get new batons?

**Comment by Ghommie** [comment]
> 
> 
> the massive hos buff was uncalled for but generally this really feels needed.

>Is cargo still the only way to get new batons?
Well, you can craft stunprods.

**Comment by ATH1909** [comment]
who tf actually takes/keeps both batons

**Comment by BlueMemesauce** [comment]
> 
> 
> the massive hos buff was uncalled for but generally this really feels needed. Is cargo still the only way to get new batons?

Can't they be printed in protolathe after they are researched?

**Comment by ATH1909** [comment]
> and most of their supposed counters (like stims, maint pump-up) barely help against the stamina loss and the knockdown right now.

gee it's almost like we should be buffing pump-up

which I've tried to do before, btw

**Comment by optimumtact** [comment]
there are not meant to be counters to stunbatons, other than staying out of melee distance.

**Comment by RegJackson** [comment]
Stunbatons don't spawn in the armory. Your PR and your blessing implies they do. This is wrong.

**Comment by anconfuzedrock** [comment]
Note that there are not, in fact, batons in the armory. or maybe there are on like one map so I'm going to have people insulting me.

**Comment by RegJackson** [comment]
The stunbaton you spawn with has always seemed more to me as a tool to prevent getting spawncamped during revs and as a fallback when all of sec has been bombed after a late arrival (A situation that I have actually been in and only won because of my starting equipment.)

I think a better fix would be to simply remove the baton from the belts in lockers. This in itself nerfs the usual locker break-ins that happen with arrivals, but personally I don't think that's too bad.

**Comment by LemonInTheDark** [comment]
Hey this means departmental lockers might actually get used. Nice

**Comment by iprice** [comment]
Inclined to agree, remove the station spawns and keep it as a player spawn if you want to limit.  Otherwise people will loot multiple at shift start in a race (like insuls) and then you have seccies without a baton.  Particularly late joins.  Concerns about how seccies without the staple non lethal tool end up interacting, and while cargo can order more, getting them to actually do so is a whole other kettle of fish (have very poor experiences of inter departmental dependencies with atmos/cargo/science as CMO main)

**Comment by BlueMemesauce** [comment]
I think it makes more sense to have the stun removed from the lockers and instead spawn in bags.
Otherwise sec could just loot the lockers and take two stun batons from the belts.

**Comment by BlueMemesauce** [comment]
> 
> 
> who tf actually takes/keeps both batons

Everyone?

**Comment by optimumtact** [comment]
I'm very much okay with the impact of secs having to deal with some limits on their stunbatons, and that inviting some decision making.

I'm also okay with rev's having an upperhand on late join sec who join after sec is blown up.

Neither strike me as completely unbalancing for security and present only minor inconveniences.

**Comment by cacogen** [comment]
>there are not meant to be counters to stunbatons, other than staying out of melee distance.

It's clear that you don't know what you're talking about with this. https://github.com/tgstation/tgstation/blob/master/code/modules/reagents/reagent_containers/hypospray.dm#L293

**Comment by optimumtact** [comment]
it may shock you but i'm aware of pump up, and it's heavily nerfed from it's previous incarnations for a reason cacogen.

**Comment by BlueMemesauce** [comment]
It doesnt actually impact Security as much as it seems. Because of the new update, now security has a cargo console that they can use to order free stun batons.

**Comment by anconfuzedrock** [comment]
> It doesnt actually impact Security as much as it seems. Because of the new update, now security has a cargo console that they can use to order free stun batons.

they're not free, taking those batons means you won't be able to buy anything else, and most options are better than batons.

**Comment by optimumtact** [comment]
oh no you have to make a tradeoff? that's gonna hurt the gameplay

**Review by Mothblocks — APPROVED** [review]
I always thought this was weird when a sec-belt is basically always needed anyway

**Comment by Ghommie** [comment]
> 
> 
> Stunbatons don't spawn in the armory. Your PR and your blessing implies they do. This is wrong.

Someone has also told me a few maps have up to 11 or so closets with batons in them. I may work on lowerin the number to 6 or 7 (whichever is the number of maximum officer slots, unless more are opened by the HoP) and add some of them to the armory if given the chance later.

**Comment by CRITAWAKETS** [comment]
sec still spawns with a disabler and armor when the armory has disablers and the closets have armor.

you know what to do

**Comment by wesoda25** [comment]
Could be interesting

**Comment by GuillaumePrata** [comment]
We already have officers that loot multiple Flashbangs (and in the past, flashes) from all belts in the lockers, I assume the same will happen with the baton and this won't fix the issue of backup baton, just make things annoying if you have some selfish officers around.
The way to stop backup batons is the same way the bag of guns was fixed, making them bulky, that will make things quite hard for traitors that like to loot them tho.
Regardless of both, scarcity alone is good so this is a nice step.

**Comment by Draggeru** [comment]
Antags already have a massive advantage in a one-on-one situation, I see this fucking over late join officers. Who might I add have no idea what's going on in the round until they actually join. I would be more okay with this pr if it took the stun batons and put them in the armory so they could still be claimed but a straight removal makes me fear for balance and potentially removing sec mains desire to play security if they get screwed over too often because they don't have a melee counter. Disablers don't really do shit especially if your aim is bad.

**Comment by ExcessiveUseOfCobblestone** [comment]
Skill issue but actually

**Comment by ATH1909** [comment]
> Antags already have a massive advantage in a one-on-one situation, I see this fucking over late join officers. Who might I add have no idea what's going on in the round until they actually join. I would be more okay with this pr if it took the stun batons and put them in the armory so they could still be claimed but a straight removal makes me fear for balance and potentially removing sec mains desire to play security if they get screwed over too often because they don't have a melee counter. Disablers don't really do shit especially if your aim is bad.

maybe we could make latejoin sec officers start with batons, but not roundstart officers?

**Comment by Lauwma** [comment]
Just the fact that you lied in order to get maintainer approval should get this PR closed
The armory does not start with batons, the only batons are the ones in the closets.

Removing batons from bags makes so late joins officers won't have anything because of every heads of staff tiding for belt + huds glasses

You should probably play the game before making PRs to be honest

**Comment by JohnFulpWillard** [comment]
> 
> 
> Just the fact that you lied in order to get maintainer approval should get this PR closed The armory does not start with batons, the only batons are the ones in the closets.
> 
> Removing batons from bags makes so late joins officers won't have anything because of every heads of staff tiding for belt + huds glasses
> 
> You should probably play the game before making PRs to be honest

The person who says there are stunbatons in the armory, in the screenshot provided, isn't even the person opening the PR.

It wouldn't affect latejoin security officers much, as only the Captain, HoP and HoS (within Command) have access to the security lockers, and HoS spawns with their own equipment, so only Cap/HoP would realistically take from it.

I would suggest you actually contribute to the game before leaving shitty comments on PRs to be honest.

**Comment by Sheits** [comment]
Pretty sure you can just print batons without cells, a sci officer could make plenty

**Comment by necromanceranne** [comment]
> We already have officers that loot multiple Flashbangs (and in the past, flashes) from all belts in the lockers, I assume the same will happen with the baton and this won't fix the issue of backup baton, just make things annoying if you have some selfish officers around. The way to stop backup batons is the same way the bag of guns was fixed, making them bulky, that will make things quite hard for traitors that like to loot them tho. Regardless of both, scarcity alone is good so this is a nice step.

I think given some stuff, including flashbangs and batons, could be replaced via cargo, scarcity isn't too much of a problem, it's just pointing people to cargo to get help.

**Comment by LukasBeedellCodestuff** [comment]
This does nothing but encourage officers to go via the lethal route. Having a back up stun baton incase you get shoved or slipped or w/e is handy because it means you don't need to go straight to lethality. With this change people will go straight to lethality. Expect armoury to be opened at the start of every round. 🤷

**Comment by SinfulBliss** [comment]
I have over 800 sec hours on TG and I think this PR will be a very strong security nerf and really hurt sec.  

Officers lose their batons _all_ the time to tiders. It just takes being slipped with your baton out, shoved into someone while making an arrest, and someone picks it up - now it's out of security's hands and into the crew's. On every single highpop shift officers get their batons stolen. Fortunately they have a second one as backup if this happens to them, so they can still do their jobs (or have a way to stop the guy that stole it). But after this PR they won't. Not having a baton as an officer essentially means you can't do your job until you get another one.

This will remove officers from play for several minutes while they sit in cargo and wait for the stunbaton crate - provided they can accomplish this (on LRP rounds, this is actually quite a chore and many times impossible due to the conditions of cargo, station, etc).

As far as batons being too strong: the solution is to give better anti-stunbaton measures to antagonists. Disarming security with weapons they need to fight against the hoard of tiders, shitters, etc. that will mob them is not the solution. Consider the officer that latejoined, brig is blown up, sec office was looted, etc., the officer will essentially be useless for the entire shift. This happens fairly often.

To clarify also, there are no batons shiftstart except the ones in the secbelts and the one you spawn with. The only way to get more is to order them from cargo.

**Comment by UnokiAs** [comment]
Another alternative would be security still spawn with their batons but :
- Stun baton become bulky.
- Only fit on suit slot/belt slot.
- Security belt get a energy bola instead.

**Comment by SuperNovaa41** [comment]
> This does nothing but encourage officers to go via the lethal route. Having a back up stun baton incase you get shoved or slipped or w/e is handy because it means you don't need to go straight to lethality. With this change people will go straight to lethality. Expect armoury to be opened at the start of every round. 🤷

Or, alternatively, you could just get better at the game. What kind of sec players lets himself get shoved with his baton out?

**Comment by SinfulBliss** [comment]
> 
> 
> > the massive hos buff was uncalled
> 
> Is it? Talking from experience, telebatons are kinda slow.
> 
HoS doesn't get telebaton shiftstart, he gets stunbaton in bag like officers. Only difference shiftstart is he comes with sechuds and an egun instead of a disabler.

**Comment by SuperNovaa41** [comment]
> > > the massive hos buff was uncalled
> > 
> > 
> > Is it? Talking from experience, telebatons are kinda slow.
> 
> HoS doesn't get telebaton shiftstart, he gets stunbaton in bag like officers. Only difference shiftstart is he comes with sechuds and an egun instead of a disabler.

this pr originally gave HOS telebaton

**Comment by Ghommie** [comment]
> 
> 
> Another alternative would be security still spawn with their batons but :
> 
>     * Stun baton become bulky.
> 
>     * Only fit on suit slot/belt slot.
> 
>     * Security belt get a energy bola instead.

For that scenario, I'd recommend making the security belts bulky but still able to fit _one_ stunbaton (the storage component has a ton of variables but i'm not sure there's one that puts a cap on how many items of specific types can be inserted) to avoid diminishing their usefullness or increasing the tedium of inventory management more than necessary.

**Comment by SuperNovaa41** [comment]
> Another alternative would be security still spawn with their batons but :
> 
>     * Stun baton become bulky.
> 
>     * Only fit on suit slot/belt slot.
> 
>     * Security belt get a energy bola instead.

or, they could just get a sec belt, and get their baton that way, like they always do???

**Comment by redsunoverparadise** [comment]
Give secoffs belts shift start then, remove em from closets

**Comment by SinfulBliss** [comment]
> 
> 
> > Another alternative would be security still spawn with their batons but :
> > ```
> > * Stun baton become bulky.
> > 
> > * Only fit on suit slot/belt slot.
> > 
> > * Security belt get a energy bola instead.
> > ```
> 
> For that scenario, I'd recommend making the security belts bulky but still able to fit _one_ stunbaton (the storage component has a ton of variables but i'm not sure there's one that puts a cap on how many items of specific types can be inserted) to avoid diminishing their usefullness or increasing the tedium of inventory management more than necessary.

Ghommie, brother, pal. What sec will simply do is carry the second baton in bag so they can toggle it out as if it were the first baton. It's really just added tedium that sec will have to work around to get a setup that's practical for the round.

**Comment by GuillaumePrata** [comment]
> Ghommie, brother, pal. What sec will simply do is carry the second baton in bag so they can toggle it out as if it were the first baton. It's really just added tedium that sec will have to work around to get a setup that's practical for the round.
>
> If only suit/belt, simply put disabler in bag and baton in belt and suit storage. Energy bola shiftstart is pointless since they can be bought for 7 credits from a vendor.

You're ignoring the massive buff it would be for sec if randoms can't just shove you and bag your baton.
I would gladly trade the tedium or loss of multi baton meta if we get traitors and randoms having to make a choice between trading their belt/exo slot for a visible baton or not instead of just having one in the bag whenever it is possible.

**Comment by TheBonded** [comment]
I play security often enough and I rarely if ever see the extra baton come into use. Sec officers nearly always just go and grab a belt, and either leave the extra baton in security or forget about it in their bag. 

In fact, the ONLY time I've ever seen a security officer use the second baton was when they rigged the battery on it with plasma and would throw it at criminals, but intentionally miss, so when the criminal picked it up and tried to stun the officer they would explode and die, with minimal harm to the officer.

Besides, if an officer wants a second baton, what's stopping them from just grabbing another from one of the other lockers? There's almost always a few extra belts, so this change really wouldn't nerf sec all that much, if at all.

**Comment by adamkad1** [comment]
HURR DURR IM GONNA STEAL ALL THE BATONGS

**Comment by borb197** [comment]
There are no extra batons in the armoury, although there are security belts with one baton each in the lockers outside it. Honestly, just remove the batons inside those and let officers keep their roundstart batons, also cargo still remains a super easy way to get batons, all this PR does is grief sec offs / hos / warden roundstart or when they latejoin they're already vulnerable enough, let alone without a baton.

**Comment by timothymtorres** [comment]
> In fact, the ONLY time I've ever seen a security officer use the second baton was when they rigged the battery on it with plasma and would throw it at criminals, but intentionally miss, so when the criminal picked it up and tried to stun the officer they would explode and die, with minimal harm to the officer.
> 
> Besides, if an officer wants a second baton, what's stopping them from just grabbing another from one of the other lockers? There's almost always a few extra belts, so this change really wouldn't nerf sec all that much, if at all.

This is pretty robust.  

Having an extra baton isn't that big of a deal.  There are plenty of useful stuff you can replace it with.

**Comment by wesoda25** [comment]
Having a (mostly) static supply of materials to manage - which all crewmembers can potentially get their hands on - is more interesting to me than just giving one to every member of security. The latter just seems to provide a lot less agency for the crew. Creating a scarcity is an interesting dynamic to me, especially considering how powerful batons are. Hopefully this encourages a different approach to security for some people, although as Lukas said the concern is that it could just be resorting to lethals sooner than later.

**Comment by cacogen** [comment]
inb4 stun baton crate every single round

**Comment by TheBonded** [comment]
> inb4 stun baton crate every single round

@cacogen, the stun batons secoffs spawn with are rarely used as is, since they have sec belts in their lockers that contains a baton already in them. taking the time to buy a baton crate would be a huge waste since it would always be faster to walk into security and just grab a belt, which officers already do every round. this effectively changed nothing, except making departmental secoffs slightly more vulnerable (but still less vulnerable than normal crew) during the first 30 seconds of a round while they walk to sec to get a belt (which they already did before this change anyways).

**Comment by optimumtact** [comment]
> inb4 stun baton crate every single round

you say this like it's somehow a bad thing, it's not, it's actually better than cargo going unused.

**Comment by cacogen** [comment]
@TheBonded 

My understanding and correct me if I'm wrong is that if anybody grabs a baton out of one of these belts or the belt itself, then security is now down a baton and provided enough officers join someone will miss out. This means on highpop rounds it's likely somebody will not get a baton without having to spend the best part of ten minutes getting one from cargo. Once you have to do this over multiple rounds it adds up to a huge chunk of downtime mucking around waiting on somebody else to do their job.

>you say this like it's somehow a bad thing, it's not, it's actually better than cargo going unused.

People would use cargo more if it were consistently staffed and faster. The shuttle takes too long and loading and unloading crates takes too long and is not enjoyable to do. Most people do not load crates or stamp manifests and cargo techs are often absent from their jobs. I myself enjoy cargo and always load and unload crates and stamp manifests but it's tedious as fuck and I'm usually the only one doing it. 

As an aside, stamping manifests has been hugely disincentivised by a recent change that makes it penalise you I think 600 points for erroneously approving a manifest while correctly approving one only gives you 80. Almost nobody checks manifests and it would grind cargo to a standstill if they did. It's also difficult to check a manifest for a crate that somebody else has to open. It just leads to people not stamping them at all. In which case, why even have the mechanic? It was added as a reference to Papers, Please and I thought it was tedious to the point of being unrealistic to expect people to do it then and I feel similarly now.

**Comment by optimumtact** [comment]
>     People would use cargo more if it were consistently staffed and faster. 

and it won't be staffed until it's relevant, don't try to tie me up in a chicken and egg problem, because i've already picked a side.

**Comment by LemonInTheDark** [comment]
I have been in this place before, flying down the street

**Comment by NanoCats** [comment]
This is kind of dumb, if they truly want more batongs, they can get them, this is just going to lead to people coming in as latejoin sec officers finding lockers with belts looted of their extra batons.

Personally I really think secoffs should spawn with their fucking belts anyways because what the fuck kind of secoff doesn't want/have a secbelt?

Shoutout to the lads with their nose to the grindstone to crank out pointless annoying nerfs to things at seemingly random.

**Comment by SinfulBliss** [comment]
> > inb4 stun baton crate every single round
> 
> @cacogen, the stun batons secoffs spawn with are rarely used as is, since they have sec belts in their lockers that contains a baton already in them
Completely incorrect.. Every experienced security officer I know keeps two batons on them. It's so easy to lose one of your batons or have the charge run out on the other. But the real reason is because, in a baton-joust, you will likely drop your baton after being stunned, and being able to whip out your backup and get the second hit in to stamcrit will save your ass.

Likewise if you're shoved with a baton out, your baton drops, you can whip out the second and stun whoever is trying to loot it. This happens _super_ often by the way.

**Pull request merged**
