### PR TITLE
Completely removes unused caution sign from code

### PR DESCRIPTION
**Pull request by maxymax13**
## About The Pull Request
Tiny atomic pr that zaps the old unused caution sign out of both its icon file, the code, that one random map file it was still in, metastation, and rearranged metastation. You can now properly wear caution signs from all sources!

## Why It's Good For The Game
One less unused thing being processed means less time spent processing redundant unused garbage means more time spent playing the game. Also reduces the chances of an admin spawning the wrong one when you pray for a caution sign to use as armor on your holy crusade.

## Changelog
:cl:
code: completely cleaned up all traces of old unwearable caution signs
/:cl:

### CODE REVIEW

**Comment by maxymax13** [comment]
oh god wait why does metastation still have so many wtf

**Comment by maxymax13** [comment]
🙂

**Comment by Fikou** [comment]
soulless

**Comment by maxymax13** [comment]
are you suggesting being able to wear wet floor signs as utterly ineffective armor is soulless

**Review by Twaticus — APPROVED** [review]

**Comment by maxymax13** [comment]
why do people not want the metastation wet floor signs to be the correct type 🙁

**Comment by BlueMemesauce** [comment]
> why do people not want the metastation wet floor signs to be the correct type 🙁

i was playing as janitor and was annoyed at this . i appreciate your change coder

**Pull request merged**
