### PR TITLE
Drone Balance Patch

### PR DESCRIPTION
**Pull request by chesse20**
Makes drones workable and adds some extra health
New Drone Laws:
1. You are crew sided
2. You are not a bad guy
3. Your goals are to build, maintain, repair, improve, and provide power to the best of your abilities, but you can also just hang out and do whatever.

:cl: 
tweak: gave drones 10 more health (interacting with crew more means they might get shot more)
tweak: gave drones new laws that don't suck
tweak: changed the pop up that appears when you are a drone to reflect the law changes
/:cl:

[why]: Drones got removed for no good reason

### CODE REVIEW

**Comment by subject217** [comment]
The nature of silicon laws also flew over his head.

>2. You are not an antag

This is comedy gold.

**Comment by praisenarsie** [comment]
yet another time-waster pr only serving to get a few :laughing: ratings by chesse20

**Comment by Jord1081** [comment]
As much as I want drones to return, this feels poorly thought out and implemented. And those laws are  ridiculously OOC.

**Comment by iskyp** [comment]
most dumb pr of 2018

**Comment by GuyonBroadway** [comment]
The issue with drones was never thier lawset, its the fact they could be taken over by a ghost and ruin someones round before admins can step in.

Even if the drone gets dronebanned after welderbombing a summon narsie rune and killing four cultists that cult round is ruined because of one salty fucklord who could just get back into the round with all the abilities of a human in two clicks plus free all access and greif people in no time flat.

**Comment by AlexTheSysop42** [comment]
Would giving all non-free drones pacifism work/help?

**Comment by ishitbyabullet** [comment]
@AlexTheSysop42 That actually would help, to be honest, but it wouldn't save drones.

It's not like people try and metagame on whether or not a drone is free. You can usually tell if they have a human name or can start speaking galactic common instead of drone language.

**Comment by GuyonBroadway** [comment]
But by that point they've probably whipped out a gun and killed you.

**Comment by AlexTheSysop42** [comment]
Well the other important part is that free drones basically only are created when polymorphed, and are also bound by server rules

**Comment by kevinz000** [comment]
as bad as this is this is hilarious

**Comment by SpaceManiac** [comment]
good meme

**Pull request closed without merging**
