### PR TITLE
Resprites the All-In-One-Grinder!

### PR DESCRIPTION
**Pull request by Imaginos16**
## About The Pull Request
Done by @Krysonism, but finally PR'd.
image
## Why It's Good For The Game
Way less crusty, 3/4ths compliant, looks nice on a table :)
## Changelog
:cl: Krysonism, PositiveEntropy
imageadd: Resprites the All-In-One-Grinder!
/:cl:

### CODE REVIEW

**Comment by DrDiasyl** [comment]
It looks too of a industrial now, not really like a blender.

**Comment by Imaginos16** [comment]
You do know those are also used by science and chemistry for things other than blending right?

**Comment by DrDiasyl** [comment]
> You do know those are also used by science and chemistry for things other than blending right?

Yes, but they're also used at kitchen, bar, and botany

**Comment by Googles-Hands** [comment]
Change bad, soul gone

**Comment by AtomTheProphet** [comment]
> > You do know those are also used by science and chemistry for things other than blending right?
> 
> Yes, but they're also used at kitchen, bar, and botany

Yeah but shouldn't it look industrial, since it's capable of grinding things like uranium or silver?

**Comment by MTandi** [comment]
Too many hard edges in the middle.

**Comment by Helg2** [comment]
It looka like self-made blender.

**Comment by MTandi** [comment]
Maybe adjust it a bit?

image

**Comment by BlueMemesauce** [comment]
The design still looks odd and doesn't really make me think of a blender, but the smooth edges and colors are much better

**Comment by Imaginos16** [comment]
> Maybe adjust it a bit?
> 
> Smoother edges image
> 
> And maybe less high image

I don't like it. The shading is completely off and the lack of edges makes it look worse.

**Comment by Iamgoofball** [comment]
>Yeah but shouldn't it look a bit more industrial, since it's capable of grinding things like uranium or silver?

chrome_LyXi8r0idm

**Comment by Loafin34** [comment]
too small of a beaker sprite, 👎  for me.

**Comment by MTandi** [comment]
> too small of a beaker sprite, 👎 for me. also, the original grinder's 3/4th compliant as well.

Agree with the small beaker, I drafted out this too actually, but It looked worse than the original.

image

**Comment by Dorsisdwarf** [comment]
> > Maybe adjust it a bit?
> > Smoother edges image
> > And maybe less high image
> 
> I don't like it. The shading is completely off and the lack of edges makes it look worse.

The shading in yours is way too harsh and combined with the edge highlight make it look like those machined slabs of metal with razor sharp edges that metalwork shops make to show off their precision lasercutters, rather than a piece of foodware

**Comment by BlueMemesauce** [comment]
My main complaint is that the whole top part is supported by just one rod, looks like the thing is going to topple over or snap off.
I agree the shape and colors make it look like an industrial machine, but keep in mind it's also used in places like chemistey to grind metals so that actually makes sense in some cases.
Overall it has some issues but its better than the original which was kind of indecipherable and didn't really look like anything.

**Pull request merged**
