### PR TITLE
Fixes 2 issues with the unbanning panel and adds a reban button.

### PR DESCRIPTION
**Pull request by Timberpoes**
## About The Pull Request

Issue 1: In the big while loop in `/datum/admins/proc/unban_panel`, the player_key, player_ip, player_cid and admin_key variables were inherited from outside of the while loop's scope.

`var/unban_href = "<a href='?_src_=holder;[HrefToken()];unbanid=[ban_id];unbankey=[player_key];unbanadminkey=[admin_key];unbanip=[player_ip];unbancid=[player_cid];unbanrole=[role];unbanpage=[page]'>Unban</a>"` used these vars in the first iteration of the while loop before they were set by the actual ban information. At this point in time, these vars contain what was in the search query in the unbanning panel.

As a result, when the banned player's key wasn't filled in attempting to unban a player...
image

Would result in a message like this:
image

The worst case scenario is that the href would use the player_key, player_ip, player_cid and admin_key from the previous iteration of the while loop in this off-by-1 error.

As a result, the unbanning panel could list a confirmation prompt that confirmed incorrect ban details (for a ban next to the selected one). This was purely a visual bug, since the banid would always be set properly so unbanning would apply to the ban selected, it would just mislead in the confirmation dialog and make it look like it was for another ban.

I've stopped using these parent scope vars and now use only local scope vars. I've also moved creation of this href to later on in the code as part of fixing issue 3.

Issue 2: The tgui_input with the Yes/No prompt can return 3 states: Yes if the Yes button is pushed, No if the No button is pushed and null if the input is X'd out of. The check only early returned if `No` was returned and would continue as normal with the unban if `Yes` or `null` were returned.

4LTNr2oqYL

We only ever want to proceed if the admin selects Yes, so I modified it to now early return if any non-Yes input is returned.

Issue 3: If you do the wrong unban by accident (as highlighted by Issue 1 and compounded by Issue 2) there is no way to reactivate the ban. You have to place a whole new ban.

As a result, I have added a reban button that nulls the unbanned_ keys in the database.

image

The re-banned ban at the bottom matches the stats for all the banned variations.

4XmINmUmvy

I have added edit tracking for unbanning and rebanning to support this new feature more fully.
image

Review adjustments:

The check for placing additional admin bans has been pulled into its own proc, `/datum/admins/proc/can_place_additional_admin_ban()`

Creating, editing and rebanning now use this proc to ensure that admin bans can only be placed if the appropriate criteria is met.

Notifying a banned player of their ban as well as kicking for server bans has been pulled into its own proc, `/datum/admins/proc/notify_all_banned_players()`

Creating, editing and rebanning all use this proc. This proc is pretty much universal and incorporates all behaviours of all other procs that used to have their own bespoke handling.

This means that editing bans now displays the appeal URL alongside the edit reason to players thanks to this unified behaviour. Editing server bans where the changes include CID, IP or ckey will now kick any players matching the new details similar to creating a new ban.

Rebanning will kick any players matching the ban details if the ban was a server ban.

## Why It's Good For The Game

Makes admins happy.

## Changelog

:cl:
fix: Fixed an issue where the unbanning panel would give inaccurate information about the ban in the unban confirmation prompts.
fix: Fixed an issue where clicking the X to close out the confirmation popup on the unbanning panel acted as if you'd pressed Yes.
admin: Added a reban button to the unbanning panel. This allows an admin to quickly and easily re-apply a ban they've removed and replaces the unban button when a ban has been removed. As a result, accidentally removing the wrong ban no longer requires the admin to place a second brand new ban on top of the old one.
admin: Editing the IP, ckey or CID of a server ban will now kick any players matching the edited ban's new details.
/:cl:

### CODE REVIEW

**Comment by Iamgoofball** [comment]
Does rebanning restart the timer or does it respect time served?

**Comment by Timberpoes** [comment]
Yup. The purpose was to add an undo button for accidental unbans.

I don't add the time spent unbanned onto the ban duration when rebanning. I just NULL out the optional fields that are used to determine if and when the player was manually unbanned.

This restores the ban go the same state as before the unban. Minus some extra edit logging since I'm deleting information about an admin action from the DB at that point.

**Review by Jordie0608 — CHANGES_REQUESTED** [review]
This code looks fine but there's two things it doesn't cover:

There's no check for adminbans count, someone could add and then unban every admin one-by-one then reactivate all of those bans. https://github.com/tgstation/tgstation/blob/master/code/modules/admin/sql_ban_system.dm#L496-L517
Probably best to split that bit off into a proc and call it in `create_ban()`, `edit_ban()` and `reban()`

This could have a situation where someone who was unbanned is on the server when their server ban is reapplied so this should do a check for them and kick if needed like is done at the end of `create_ban()`. https://github.com/tgstation/tgstation/blob/master/code/modules/admin/sql_ban_system.dm#L573-L594
This looks like it also can just be a proc. It's not done in `edit_ban()` but probably should be since you can edit a ban's ip/cid/ckey etc.

**Comment by Timberpoes** [comment]
> 
> 
> This code looks fine but there's two things it doesn't cover:
> 
> There's no check for adminbans count, someone could add and then unban every admin one-by-one then reactivate all of those bans. https://github.com/tgstation/tgstation/blob/master/code/modules/admin/sql_ban_system.dm#L496-L517 Probably best to split that bit off into a proc and call it in `create_ban()`, `edit_ban()` and `reban()`

The check for placing additional admin bans has been pulled into its own proc, `/datum/admins/proc/can_place_additional_admin_ban()`

Creating, editing and rebanning now use this proc to ensure that admin bans can only be placed if the appropriate criteria is met.

> This could have a situation where someone who was unbanned is on the server when their server ban is reapplied so this should do a check for them and kick if needed like is done at the end of `create_ban()`. https://github.com/tgstation/tgstation/blob/master/code/modules/admin/sql_ban_system.dm#L573-L594 This looks like it also can just be a proc. It's not done in `edit_ban()` but probably should be since you can edit a ban's ip/cid/ckey etc.

Notifying a banned player of their ban as well as kicking for server bans has been pulled into its own proc, `/datum/admins/proc/notify_all_banned_players()`

Creating, editing and rebanning all use this proc. This proc is pretty much universal and incorporates all behaviours of all other procs that used to have their own bespoke handling.

This means that editing bans now displays the appeal URL alongside the edit reason to players thanks to this unified behaviour. Editing server bans where the changes include CID, IP or ckey will now kick any players matching the new details similar to creating a new ban.

Rebanning will kick any players matching the ban details if the ban was a server ban.

Was this the kind of thing you were looking for?

**Comment by Jordie0608** [comment]
pacha just right

**Review by Jordie0608 — APPROVED** [review]

**Pull request merged**
