### PR TITLE
Gun sound revamp

### PR DESCRIPTION
**Pull request by actioninja**
## About The Pull Request
https://www.youtube.com/watch?v=ObnTvcIzRB0&feature=youtu.be
https://www.youtube.com/watch?v=eMhp4WHeTSE&feature=youtu.be
I was going to edit these together then got too lazy to do that.

What started as an experiment with some new samples I got turned into a complete replacement for every ballistic gun sound.

Gun sound revamp: take 2: I know a little bit more what I'm doing this time edition, Or, I played the new Modern Warfare and now feel inadequate with my existence

Also some small non-critical bugfixes

## Why It's Good For The Game

big shoot

## Changelog
:cl:
soundadd: New gun sounds take 2: consistency and clarity edition
bal: suppressed gunshots are no longer audible through walls
/:cl:

### CODE REVIEW

**Comment by cacogen** [comment]
how do you make these?

**Comment by actioninja** [comment]
image
many samples + lots of saturation and compression

**Comment by necromanceranne** [comment]
I feel like, even though this is a sound change and it does actually make it more realistic, the suppressor does actually seem easier to hear being fired, which is less likely with the current sound.

This might actually nerf silencers. So...it's an indirect antag nerf.

**Comment by cacogen** [comment]
his suppressor sounds are very similar in terms of max amplitude to the old one and he can easily adjust them so it's the same


the reason it's easier to hear is he changed suppressor volume from 10 to 60 
https://github.com/tgstation/tgstation/blob/280741a839a2c974cbc47cfc0446d39115efe525/code/modules/projectiles/gun.dm#L27-L28
https://github.com/tgstation/tgstation/blob/8947b7d06c145be286b7456c377f3dd8df7151d7/code/modules/projectiles/gun.dm#L27-L28

**Comment by actioninja** [comment]
> I feel like, even though this is a sound change and it does actually make it more realistic, the suppressor does actually seem easier to hear being fired, which is less likely with the current sound.
> 
> This might actually nerf silencers. So...it's an indirect antag nerf.

suppressed shots were made louder but also no longer are audible through walls to compensate.

**Comment by CRITAWAKETS** [comment]
These just all sound the same but at different speeds or pitches. You cant differentiate guns at all. It also sounds less impactful than the old gun sounds. Why do we need this?

Don't fix what isnt broken.

**Comment by actioninja** [comment]
They quite literally are not "just different speeds or pitches." I have no problem telling the difference.

**Comment by necromanceranne** [comment]
> suppressed shots were made louder but also no longer are audible through walls to compensate.

In that case no worries. That seems more of a reasonable change to me.

**Comment by carlarctg** [comment]
all of these sounds are honestly very samey, i'd find it hard to differentiate a sound from another

it could just be unfamiliarity though

**Pull request merged**
