### PR TITLE
Smoking (for like 15-20 minutes straight, out of low grade tobacco) kills!

### PR DESCRIPTION
**Pull request by Tacolizard**
:cl: Tacolizard Forever
add: Smoking now harms your lungs. Avoid prolonged exposure to unfiltered smoke, such as cigars and rollies.
/:cl:

smoking damages your lungs, dealing oxyloss over time. 

**I'm trying to balance it so that you will only have health complications if you smoke nearly the entire round. Also I don't want people to worry about death when smoking. Even for the heaviest smokers, the most you should experience is a little oxy damage that heals over time.**

**Estimates for how long to start taking noticeable damage from smoking ("noticeable" is around 10 oxyloss):
Cigarettes: ~20
Cigars: ~12-15
**

I can't provide exact figures as the math behind the damage is pretty convoluted and I would probably mess up the calculations. The above figures are based off of observation.

Note: this PR only affects human (including human-derived races) lungs. Plasmeme and cybernetic lungs are unaffected.

### CODE REVIEW

**Comment by ma44** [comment]
You could always scale off the deadliness of the smoking by all the reagent's toxic power, so you could make even more deadlier smokes.

**Comment by QualityVan** [comment]
doesn't give you lung cancer 0/10

**Comment by Tacolizard** [comment]
@QualityVan i imagine that lung damage includes all possible harmful effects of smoking, including lung cancer.

**Comment by Durkel** [comment]
They're space cigs, they don't cause cancer.

**Comment by arsserpentarium** [comment]
you need to smoke REALLY hard to notifically damage lungs along one shift, which lesser, than week.
So fuck it.

**Comment by Tacolizard** [comment]
yeah I'm trying to balance it so that you will only have health complications if you smoke nearly the entire round.

**Comment by arsserpentarium** [comment]
you need to be tortured with cigs to damage lungs.
Well, you know.Buckle guy to chair, put on gas mask.Shove pack of cigs instead of filter,lit them and kick him in chest/kidney to force deep breathing.

**Comment by Bombpants** [comment]
Detectives, bartender, qm, captain, his, and botanists should have some sort of buff against lung damage. 

Detective and bartender loves their smokies 

Captain, hos, and qm all have cigars to smoke. 

And botanists should be able to get high all shift

**Comment by Tacolizard** [comment]
@Bombpants honestly, they shouldn't need buffs. Smoking really doesn't do much damage.

**Comment by TechnoAlchemisto** [comment]
smoking doesn't need to do damage at any point

**Comment by PKPenguin321** [comment]
👍 to having organ damage for each individual organ (like how eyes have eye damage).

**Comment by Tacolizard** [comment]
@TechnoAlchemisto but smoking without damage is literally a free buff?

**Comment by Tacolizard** [comment]
alright the balance is pretty much where i want it right now.

@PKPenguin321 can you give a thumbs up on the changelog so people can see the support better?

**Comment by Therapist1** [comment]
Smoking may seem free, but just wait until someone throws booze/welding fuel at you in the act.

**Comment by Repukan** [comment]
Would be interesting if burning things or plasma fires made smoke fill the hallways too.

**Comment by Cyberboss** [comment]
>smoking less cigars gives you as much damage as smoking more cigarettes


spongebob_boi 1


Can't say I'm interested, smoking any amount of cigarettes within the context of round time wouldn't hurt anyone except Kif

**Comment by Iamgoofball** [comment]
drop this to reagent-level

**Comment by JStheguy** [comment]
@Cyberboss 
But what about that free minor reduction to stun time?
And the free +2 Space Station 13 Quantified Happiness Points?
Literally ruins the game tbh.

**Comment by Tacolizard** [comment]
i might close this if people unless more people upvote, as i've got another pr in the works that may conflict with this one

**Comment by Shadowflame909** [comment]
so what your saying is, if im the detective and the round ends instantly. I instantly die?

**Comment by Tacolizard** [comment]
@Shadowflame909 ok let me revise the title

**Comment by Tacolizard** [comment]
@Iamgoofball no, because nicotine itself doesn't cause lung damage, and also the liver is responsible for processing reagents. you can get lung damage from smoking without a liver

**Review by ExcessiveUseOfCobblestone — CHANGES_REQUESTED** [review]
This should be reagent-based and not on the cigarettes themselves.

**Comment by ExcessiveUseOfCobblestone** [comment]
The lung damage is from the inhalation of the contents of the cigarette. There's awful stuff in cigs, not just nicotine.

**Comment by Bombpants** [comment]
I have an idea for an easy way to heal this damage. Spend some time in the machines in the gym or run around a lot (cardio for days)

If there was a somewhat easy way to heal this lung damage (from exercise) then maybe more people wouldn’t mind the pr

**Comment by BeeSting12** [comment]
Not a fan of this as someone who smokes for the whole round. Realistically you wouldn't get cancer from smoking cigs for a couple hours

**Comment by epochayur** [comment]
I also smoke for the entire round because >muh immersions. Playing engi just doesn't feel right without it. If this did SOME damage, ala MGS, sure, but having it kill you is just dumb.

**Comment by arsserpentarium** [comment]
You'd better to add stuffing gas mask with cigarettes.

**Pull request closed without merging**
