### PR TITLE
Atmos overalls take 2

### PR DESCRIPTION
**Pull request by GuillaumePrata**
## About The Pull Request
This is a reinmagining of #72768 as I never was never given a chance and feedback to polish the sprites or remake it as a suit item as was suggested before the PR was closed.

This adds Atmos Overalls that ATs will spawn with, the sprite is based on the GAGS overalls we already have, but I dodged the GAGS system and made it a standalone item following the AT firesuit palette and design to fit in.

It can carry the same gear as the wintercoat and the overalls themselves have fire and acid armor in parity with the firesuit, but that is for the clothing itself and not the wearer.

This is first and foremost a fashion item, as with how our game manages fires, being fireproof on your legs and torso won't do anything with your arms exposed...

atmos overall

<details><summary>This is how ATs looked at spawn before as reference</summary>
<p>

before_atmos_overalls

</p>
</details> 

## Why It's Good For The Game
The only "fashion" suit atmos have is their wintercoat, if an AT is not using their "functional" clothing (MOD/Firesuit) they all default to the wintercoat and look mostly the same and even their functional uniform makes everyone also look the same as it covers everything (That is something I like to be clear)

There is also the "issue" that AT and Engies have the same jumpsuit and wintercoat with small changes, and that their department bags use orange instead of yellow as a second color, which makes them look weird on ATs and the CE.

So now we have something that ATs can use to look different from each other while still keeping their job identity.

And, as I said in my previous PR, I just really want the pumbler job to look like a plumber, when they are not firefighting at least.
## Changelog
:cl:Guillaume Prata
add: Atmos Tech now have new drip and will spawn with Atmos Overalls to protect their clothing from gas leaks! (It will actually not protect you against fire or leaks, but hey! It's the thought that counts!!)
/:cl:

### CODE REVIEW

**Comment by GuillaumePrata** [comment]
I don't remember how to fix the error with `/datum/unit_test/outfit_sanity` so if anyone can help, here or on discord, I would appreciate it.

**Comment by Pickle-Coding** [comment]
I always found it annoying having to wear a wintercoat as the only option for casual exosuit slot availability. I hope the CE's overalls could be a separate item like this one day. The wintercoat is their only CE option, and it does not look good with their hard hats.

**Comment by GuillaumePrata** [comment]
> I hope the CE's overalls could be a separate item like this one day. The wintercoat is their only CE option, and it does not look good with their hard hats.

I personally always wanted the CE to use a proper suit, just because I think of IRL engineers in construction sites with a full suit + Hazard vest and Hardhat to be such a unique clothing "design"

Would remind them that they are meant to be the boss, and not just another workhand.

**Comment by Serxule** [comment]
> > I hope the CE's overalls could be a separate item like this one day. The wintercoat is their only CE option, and it does not look good with their hard hats.
> 
> I personally always wanted the CE to use a proper suit, just because I think of IRL engineers in construction sites with a full suit + Hazard vest and Hardhat to be such a unique clothing "design"
> 
> Would remind them that they are meant to be the boss, and not just another workhand.

i mean yes but also very much no, the CE isnt a supervisor or coordinator, they're a chief engineer, an engineer of higher skill and ranking

**Comment by FernandoJ8** [comment]
> I always found it annoying having to wear a wintercoat as the only option for casual exosuit slot availability. I hope the CE's overalls could be a separate item like this one day. The wintercoat is their only CE option, and it does not look good with their hard hats.

There *is* the safety vest, but it's a bit underwhelming and has the issue of being the same for engies as well.

**Review by Wallemations — APPROVED** [review]

**Comment by RedBaronFlyer** [comment]
These look stylish as fuck while also not being a censor bar like the V1, nice job!

**Comment by EuclidianGeometer** [comment]
yeah, after revisions this looks excellent, excited to wear this when atmosing about.

**Review by Ghommie — APPROVED** [review]
Where did the sprite-tainers go?

**Pull request merged**
