### PR TITLE
Training in heavy gravity gives you more experience points

### PR DESCRIPTION
**Pull request by Jacquerel**
## About The Pull Request

If you use exercise equipment in an area with unusually high gravity, you will get tired faster but will also earn a greater amount of fitness experience points.
As far as I am aware the only particularly reliable way for regular crew to gain access to high gravity is the bone-crushing strength (and radiation?) of the gravity generator, but you could also use gravitational anomalies or gravitational holoparasites for this if they are available.

Conversely, if you lift weights when there's no gravity it won't cost you any stamina at all!

## Why It's Good For The Game

I'll be honest this is a largely pointless and trivial change which interacts with a similarly useless system, but I thought it would be a cute interaction.
Training by wearing heavily weighted clothing or in an area where gravity is increased are _somewhat_ common tropes in fiction (I have no idea if people do this in real life) and I think our players would appreciate the incredibly niche circumstances where they can benefit from this.

I also think if even one round features someone building a gym in the gravity generator room and encouraging people to get buff while it crushes them into paste then this was a good addition.

## Changelog

:cl:
balance: If you work out under heavier-than-earth gravity, you will get gains faster.
/:cl:

### CODE REVIEW

**Comment by deathrobotpunch** [comment]
cue the buff bros working out in the gravity generator

**Comment by ArcaneMusic** [comment]
FYI this does not help you get any stronger in real life, but it makes for PEAK fiction
https://www.youtube.com/watch?v=crKohKpVoAM

**Comment by Vect0r2** [comment]
It would be fire if you could add custom workout messages to working out in high grav.

**Comment by Dawnseer** [comment]
Time to move the gym equipment.

**Pull request merged**
