### PR TITLE
Adds 3 Simplebot Plushies

### PR DESCRIPTION
**Pull request by Blockaboo**
## About The Pull Request
Adds 3 Simple bot plushies, a Cleanbot, a Medibot, and a Securitron
cleeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
image
Beepsky PRIME
the gang

## Why It's Good For The Game
Plushies are Funny and this adds plushies for the 3 most iconic simplebots
## Changelog
:cl:
add: added 3 simple bot plushies obtainable from arcade machines
/:cl:

### CODE REVIEW

**Comment by atlasle** [comment]
aren't the sprites a bit too big

**Comment by Blockaboo** [comment]
It's a plushie though
also the sprites are 32x32, I'm not sure if i can make a smaller sprite while keeping the same details

**Comment by dragomagol** [comment]
I think it's a cute idea, but these don't really look plushie to me.

**Comment by Jacquerel** [comment]
> It's a plushie though
> also the sprites are 32x32, I'm not sure if i can make a smaller sprite while keeping the same details

These sprites don't have more details than the actual bots, which are smaller.

**Comment by Blockaboo** [comment]
i am not a very good spriter so i might close this

**Comment by Blockaboo** [comment]
image
image
I have updated the medibot sprite to look more plushie like and be smaller. I am working on the others and will undraft it when they are all improved, thank you for the feedback.

**Comment by Blockaboo** [comment]
All of the plushie sprites have been updated and are ready for review.

**Comment by Wallemations** [comment]
I really don't think those sprites are gonna work for this

The outlines are mostly one color, and your palettes are really desaturated

**Comment by Blockaboo** [comment]
> I really don't think those sprites are gonna work for this
> 
> The outlines are mostly one color, and your palettes are really desaturated

Could you please elaborate? I must confess I've never done anything with spiriting before and I made this with Paint.net

**Comment by Wallemations** [comment]
> > I really don't think those sprites are gonna work for this
> 
> > 
> 
> > The outlines are mostly one color, and your palettes are really desaturated
> 
> 
> 
> Could you please elaborate? I must confess I've never done anything with spiriting before and I made this with Paint.net

Going into that would mean going into the basics of color theory, but to put it as simple as possible saturation is how far away from greyscale a color is. The closer to grey, the less saturated something is. Your colors are very close to grey, which makes them feel dull.
Don't over-saturate them either, since that can look just as bad. It sounds like a lot but you learn to get better at it with practice.

**Comment by ZephyrTFA** [comment]
Not interested in more plushies. A spritetainer may reopen this if they feel otherwise

**Pull request closed without merging**
