### PR TITLE
Re-adds the joy emoji to emoji.dmi

### PR DESCRIPTION
**Pull request by nervere**
:cl: Nervere
add: re-adds the joy emoji.
/:cl:

[why]: Joy emoji was previously removed in #27448 by lzimann. I don't disagree with his PR - the taco emoji was a self-insert and should have been removed. The joy emoji, however, was perfectly fine, loved by the community, and should have been kept in our emoji list.

### CODE REVIEW

**Comment by ExcessiveUseOfCobblestone** [comment]
Thanks for using the joy mask, I prefer that we keep our emojis related to the game world.

**Comment by deranging** [comment]
I HAVE AIDS
a98

**Comment by ExcessiveUseOfCobblestone** [comment]
should have been a .45 with the words 'tacolizard forever'

**Comment by Tacolizard** [comment]
\>no player references allowed
\>station is literally named pubbystation

there is no justice in this world

**Comment by ExcessiveUseOfCobblestone** [comment]
metastation is a player ref

**Pull request merged**
