### PR TITLE
Holodeck mapping revamp

### PR DESCRIPTION
**Pull request by pubby**
Adds several new holodeck programs and updates the old ones to be less boring.

Pictures of the changes can be found in this album: http://imgur.com/a/Jo929

:cl: Pubby
add: The holodeck has been upgraded with new programs. Try them out!
/:cl:

<s>This conflicts with #21176 and so it can't be merged until that PR gets sorted out.</s>

### CODE REVIEW

**Comment by PKPenguin321** [comment]
While you're at it, can you put a health analyzer on the emergency medical?

**Comment by PKPenguin321** [comment]
Also winter wonderland needs to be an emag module if it already isn't and the bees one could have a bee suit in it or something

**Comment by pubby** [comment]
Those changes are in.

I did a merge so it should be ready.

**Comment by Iamgoofball** [comment]
:+1: I like it

**Comment by Iamgoofball** [comment]
The medical one should have an SNPC doctor

**Comment by CyberbossJHCB** [comment]
Why does winter have to be an emagged one?

**Comment by Iamgoofball** [comment]
Freon

**Comment by nullbear** [comment]
Should be assistants vs sec+heads. Colorvarred looks cheap, imo.

**Comment by Metacide** [comment]
Really nicely done :+1:

**Pull request merged**
