### PR TITLE
SPECIES NUKING 2023: Head flags 3 & Knuckles: Fixes some growing pains with head flags 

### PR DESCRIPTION
**Pull request by ChungusGamer666**
## About The Pull Request

Fixes https://github.com/tgstation/tgstation/issues/76422
This was caused by me somehow not using the wrapper there and not noticing it

Also fixes hair gradients and facial hair gradients. I am pretty sure they were uhh, being hidden behind the actual hair/facial hair. Oops.

Also also fixes spawning yourself as a human as admin and getting random hair colors. That was just a failure to update the icon after updating everything, I think?

Additionally, to totally babyproof all of this, ensures that head_flags involved stuff gets applied AFTER species by creating a new preference priority, and uses two separate wrappers to apply gradient style and color.

Here's this absolute hellspawn to prove that everything works.
image
image
image
image

Sorry for being so damn good at breaking this codebase.

## Why It's Good For The Game

Bugs are bad they make you mad

## Changelog

:cl:
fix: Hair and facial hair gradients work again now
fix: Facial hair colors apply properly again
fix: Admin spawned characters will get hair color preferences applied properly
/:cl:

### CODE REVIEW

**Comment by ChungusGamer666** [comment]
I can already tell the external organ removal is going to be an absolute fucking disaster

**Comment by Fikou** [comment]
thanks i thought the random hair color was for pride week and i was gonna get upset

**Comment by TheVekter** [comment]
> I can already tell the external organ removal is going to be an absolute fucking disaster

It won't be if you actually test your shit instead of just asking for mergies as soon as you're done with it

**Comment by Time-Green** [comment]
> I can already tell the external organ removal is going to be an absolute fucking disaster

This does not inspire confidence

**Pull request merged**
