### PR TITLE
fugitives event exists now

### PR DESCRIPTION
**Pull request by tralezab**
fugitive_spawning

whoops

special thanks to @Shadowflame909 or i might have never caught this, just wondered how rare this even t could possibly be

### CODE REVIEW

**Comment by AnturK** [comment]
You still didn't commit dme change. :thinking:

**Comment by tralezab** [comment]
ahem

**Comment by Fikou** [comment]
oh thank god almighty

**Comment by habader** [comment]
lmao

**Comment by RaveRadbury** [comment]
I noticed this and thought it was dummied out for some reason. Good to see it in!

**Comment by tralezab** [comment]
i understand why you'd think that i mean have you read that file? i totally wanna go back through it and improve some things. i'm also eventually going to add those bounty hunters, and I know doombringer had a really cool idea with the fugitive containment device working like the ninja net

**Comment by MrDoomBringer** [comment]
Whew, glad this got noticed

**Comment by Shadowflame909** [comment]
I would have told you sooner but I don't know your discord

**Comment by subject217** [comment]
lol, I meant to tell you about this like a month ago, I didn't think it was as simple as a missed .dme inclusion, oops

**Comment by MrDoomBringer** [comment]
also yeah @tralezab ytf dont you have a discord

**Comment by tralezab** [comment]
i joined now so this doesn't happen anymore (for ~ 3 months, anyway. dread it, run from it, my code still arrives)

**Pull request merged**
