### PR TITLE
Fixes the broken plasma tank north left hand sprite.

### LINKED ISSUE #22418: Plasma tank inhands are fucky
untitled

### PR DESCRIPTION
**Pull request by TechnoAlchemisto**
Fixes #22418
Reasoning for this change: I was wondering if I should buy our design lead a game on steam for Christmas, any ideas? 

http://prntscr.com/dnkerd

### CODE REVIEW

**Comment by Haevacht** [comment]
Got any screenshots?

**Comment by TechnoAlchemisto** [comment]
Yeah 1 sec

**Comment by TechnoAlchemisto** [comment]
Also I meant north

**Comment by XDTM** [comment]
Buy him SS13 i heard it's cool

**Comment by TechnoAlchemisto** [comment]
There is the image

**Comment by KorPhaeron** [comment]
Inhands are a busy file

**Pull request merged**
