### PR TITLE
Added bluespace versions of the bio, chemical, and plant bags.

### PR DESCRIPTION
**Pull request by bobbah**
:cl: Bobbahbrown
rscadd: Added bluespace versions of the bio, chemical, and plant bags.
/:cl:

Adding bluespace versions of the various satchels/bags to allow research and development more utility in various departments. Will hopefully bring more productivity and use of the bluespace and non-bluespace versions of these bags.

### CODE REVIEW

**Comment by YakumoChen** [comment]
>Plant Bag with infinite amounts of exploding tomatoes

**Comment by YakumoChen** [comment]
They already hold 50-100 items each, you really, honestly don't need more then that.

**Comment by jughu** [comment]
I never ever came at a time that i got an full chemical/bio bag so this isnt needed

**Comment by Ratvar** [comment]
Due to normal bags being tiny items and ability to make boxes out of biogenerator/ library "bible print" console, this makes no big change. Nerf normal capacity (not mining one, thank)? They go in pockets, after all. No sense to have 50 tomatoes in pocket. Why was it that big?

**Comment by Incomptinence** [comment]
Encouraging botonists to stock even more ridiculous amounts of weaponized plants more than they will ever use in an infinite bag

Making them spend more time growing and less time using their creations, I like it

**Comment by banthebantz** [comment]
this is unnecessary

**Comment by kevinz000** [comment]
no.

**Comment by FantasticFwoosh** [comment]
I disagree with adding them to the protolathe, they could already be just importable designs though for the biogenerator with less tech value & no mineral input, maybe just exaggerated biogen cost.

**Pull request closed without merging**
