### PR TITLE
Makes get_area faster

### PR DESCRIPTION
**Pull request by MrsTonedOne**

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
Profilin' pleasee.

**Comment by MrStonedOne** [comment]
http://pastebin.com/N0GPrR17

**Comment by MrStonedOne** [comment]
The formula is the one we use on get_turf

lummox_jr designed it for get_turf: http://www.byond.com/forum/?post=1860571#comment15256505

**Comment by Fox-McCloud** [comment]
Yeah, I figured that's what it was. Thanks @MrStonedOne!

**Pull request merged**
