### PR TITLE
crates pt. 2 | locker version

### PR DESCRIPTION
**Pull request by axietheaxolotl**
## About The Pull Request

image

todo:

- [x] weird fucky tac and armoury lockers and shit (do these even exist)
- [x] generic wooden lockers look weird w/ the new locked icons
- [x] contemplate whether or not I re-do wooden closets now or later in a second part
- [ ] figure out some layer fuckery

281937057-8ea61faf-10c9-46d8-9700-f642f553e244

the weird wooden closets have received a minor bandaid 'till they get redone completely in a upcoming pr.

## Why It's Good For The Game

~~it's really not.~~ i've been informed by janitorial staff that I must write a proper pr body; the old ones were crusty as fuck and were covered in old, dull, desaturated and unappealing colours. this brings them up to date w/ everything else.

image

## Changelog
:cl: axietheaxolotl/viro
image: brand new locker sprites
/:cl:

### CODE REVIEW

**Comment by breadcrombs** [comment]
what happened to the vertical stripes

**Comment by BlueMemesauce** [comment]
how do they look like opened (i checked icon diff bot and they look good opened but why wouldnt you show that in the pr)

**Comment by EricZilla** [comment]
That is a Brave title to go with lmao

**Comment by axietheaxolotl** [comment]
image

the wooden closets have been changed slightly to fit the new lock icons, should be too weird, it's placeholder until I finish the full closet resprite in a pt. 2

**Comment by Sakamoto4ka** [comment]
Goon sprite & tg light

**Comment by chemistrymain2** [comment]
i like the sprites themselves but somehow they feel a little too tall for the floor tiles and i don't know how or why that's the case because they're the same actual size as the old sprites

idk

i dont like that the biohazard lockers are orange

**Comment by Loafin34** [comment]
i'm worried the emblems for the jumpsuit lockers (with all the varied clothes) look too vague, could you try and tidy them up?

**Comment by excalisword** [comment]
I don't know if it's just me, but the lighting on the lockers look inconsistent. Like a third of the way down they just look like they are in shadow for the rest of the sprite.

**Comment by FlamingIceGolem** [comment]
Can there be a direct old and new comparison image?

**Comment by Time-Green** [comment]
The departmental lockers look really depressing, they’re just the grey lockers with a colored horizontal line now. Can they be more colorful?

**Comment by Striders13** [comment]
really hard to tell what kind of engi locker you're looking at at a glance

**Comment by SinfulBliss** [comment]
The second to bottom row—not sure what any of those lockers are. I imagine one is a medical locker? The colors should be a bit more differentiated.

The O2 locker should be bluer, it’s not easy to tell it’s O2 at a glance. I also am not a fan of the fact they’re taller than one tile.

**Comment by Rex9001** [comment]
The text and symbols are really hard for me to read

**Comment by mc-oofert** [comment]
these shouldnt be taller than the tile theyre on
if you still want that please for the love of god just pr your shit to the wallening branch

**Comment by kinneb** [comment]
image
the syndicate s on this isnt readable
image
these engineering lockers need better icongraphy

can i suggest adding in horizontal stripes to them; (blue for the atmos black on the syndie locker etc etc whateva..)

i did like them before but looking at them now im not so sure

dont pushmerge this spritetainers plz <3

**Comment by BlueMemesauce** [comment]
idk why the pr didnt include a comparison but the engineering locker icons look like way better than the old ones so idk why multiple people are complaining about that
image

**Comment by iwishforducks** [comment]
> idk why the pr didnt include a comparison but the engineering locker icons look like way better than the old ones so idk why multiple people are complaining about that

to me the old icons on the lockers are more readable. the colors on the new lockers just look “blurry”- i dont know how best to describe it. the icons themselves arent bad but the color choice could be definitely be improved upon

**Comment by excalisword** [comment]
I do think some of the icons for the engineering lockers are better like the fire one, but the electrical one is kinda worst in that it kinda just looks like a zig zag to me instead of a clear lightning bolt like the old sprite. Also, looking at the engineering locker comparisons made me realize that the light representing whether or not the locker is locked is just at the center of the locker rather than where the actual locking mechanism would be like in the old sprites which I think makes more sense than it being right in the middle of the locker in the new sprites.

**Comment by justricky21** [comment]
I don't hate it, but the logos are barely readable.

**Comment by TheVekter** [comment]
Same criticism I had with the crates in that I think the shading looks a little weird with how our lighting is, but I can't tell if that's because everything else is eventually going to be shaded like this in the future or not.

These are fine, I don't see any issues. Maybe lighten up the Syndicate locker so the big "S" is easier to read. Otherwise I have no issues.

**Comment by OmegaDarkPotato** [comment]
The icons on the closets is a little hard to read, but the real stand-out for me is the biohazard closets. Maybe it's just my own eyes, but it's difficult to mesh the white biohaz symbol with the very pale lower coloration and the orange top. (looks really weird imo)

**Comment by axietheaxolotl** [comment]
image

As several asked, here's a side-by-side of the old ones, and the new ones. (Note- this isn't actually 100% accurate 'cause it's from my .ase, not the .dmi of this PR, which does have some minor fixes/colour changes.)

I believe a lot of the thoughts on them being "unrecognizable" are just people's brains being ingrained from playing this game too much, so anything different is "unrecognizable". Especially with the engi lockers, the new icons, at least in my opinion, stand out a lot more than the current ones. But, of course, I am biased.

> The departmental lockers look really depressing, they’re just the grey lockers with a colored horizontal line now. Can they be more colorful?

I will say, however, that this is just objectively incorrect. A. They're not departmental lockers, they're wardrobe lockers and B. They're just straight-up brighter and more saturated than they were before.

> i dont like that the biohazard lockers are orange

They were always orange.

**Comment by Jacquerel** [comment]
Write a real PR body and don't court people to argue with you next time you make some sprites or I'll just close the next one so we don't have to bother doing janitorial work dealing with the consequences of your own actions.

**Comment by axietheaxolotl** [comment]
should have fixed everything that was scuffed, should be ready for spritetainers to look over.

**Comment by TheVekter** [comment]
> should have fixed everything that was scuffed, should be ready for spritetainers to look over.

I'm not a spritetainer, but there seemed to be some relatively valid concerns about readability, did you address those?

**Comment by CPTANT** [comment]
Lack of readibillity both in the logos and outline.

**Comment by DATA-xPUNGED** [comment]
> image

The Hydroponics and Blue Medbay(?) Lockers are super hard to read now, the colors blend together

**Comment by necromanceranne** [comment]
The readability issues are not all the sprites, but where they show up are very problematic. The blue used for the medical lockers is extremely blendy with the locker's white, you really have to squint to see what locker you are looking at (ignoring the chemist locker, which actually contrasts appropriately). The science locker has this problem as well to an extent. This lack of proper contrasting is a significant issue, and can be solved with a brighter, less washed out colour choice. The colored clothing lockers also have this problem, I'm having to squint to look at the finer details

The security and syndicate lockers aren't fairing much better in terms of being distinguishable . At a glance, it would be difficult to distinguish the tac locker (used for armory lockers that hold the shotgun ammo) from the generic security lockers unless you already knew what they were, and it would simply be impossible if they were opened. This was something that wasn't an issue with the previous sprites because they had meaningfully different sprites. Normal security and the warden locker already had readability issues, and those issues haven't been solved here either. 

If I opened a security locker, armory locker, a syndicate gear locker and an emergency firefighting locker right next to each other in-game right now, I can easily tell which one is which by just looking, but it would be a lot harder with this resprite. I have trouble even seeing that the secure lockers have locks because of the blending color of the lock.

I'd argue that, if I cannot tell what a locker is when it is opened, and I have trouble even identifying the difference between a secure and unsecure locker, but I could before even with very subtle differences like the stripes along the locker extending over the roof of the locker, then I think we've lost more than gained from a redesign. It isn't just a color issue, but an overall design issue. There simply isn't enough distinguishing qualities between the lockers beyond the doors, and the features are too disguised in amongst the rest of the locker. And those distinguishing qualities are lost if the doors are swung open, obfuscating the locker entirely beyond a potential handful of similar lockers that it could be.

The best improvements in these designs are the engineering lockers, which are all readable up until the atmospheric locker, which just needs a better color of blue, and the command lockers which are instantly recognizable as being different and the logos are very apparent to their meaning. It would maybe be only hard to distinguish the captain and HoP lockers for the aforementioned problems when the locker is somehow altered. The CE locker is literally the worst example of all the problems I've brought up, however, as not only does the logo blend into the locker itself, but it would be difficult to tell it is even a command locker and not actually a generic medical/research locker.

**Comment by justricky21** [comment]
The sprites are good dgmw, but the engineering logos are awful (aside from the rads locker, I can barely tell the others apart).
Both the CE locker and, plus Researcher and RD, look like the number 13 is there rather than the letter. The H in the hydro locker is pratically invisible.

The rest of the lockers are fine I think. Do please try and improve your attitude 'cos it makes it hard to like your work when you behave like a kid looking for internet arguments.

**Comment by YakumoChen** [comment]
Sprites look way too visually busy, and I can't actually read the text on most of them. The hazard lockers are a prime example, the "line and dots" lettering makes them extremely hard to read.

**Comment by Thunder12345** [comment]
The L3 and L4 lockers are also especially hard to read. Using a lighter shade of the main colour in the gaps in the lettering might help it read better.

**Comment by YakumoChen** [comment]
Colours on some could also be much better, like the janitor locker uses way too dark of a purple.

**Comment by axietheaxolotl** [comment]
> The readability issues are not all the sprites, but where they show up are very problematic. The blue used for the medical lockers is extremely blendy with the locker's white, you really have to squint to see what locker you are looking at (ignoring the chemist locker, which actually contrasts appropriately). The science locker has this problem as well to an extent. This lack of proper contrasting is a significant issue, and can be solved with a brighter, less washed out colour choice. The colored clothing lockers also have this problem, I'm having to squint to look at the finer details of their color bands. At that point, why even include those details? It would look stronger without them, if a bit flat.

yea, I got nothin' for this.

> The security and syndicate lockers aren't fairing much better in terms of being distinguishable. [...]

The syndicate locker only ever appears consistently inside the nukie base, and I'm genuinely not sure how either a syndicate locker or a security locker would be put together in a place where you'd have to differentiate them.

> At a glance, it would be difficult to distinguish the tac locker (used for armory lockers that hold the shotgun ammo) from the generic security lockers unless you already knew what they were, and it would simply be impossible if they were opened. This was something that wasn't an issue with the previous sprites because they had meaningfully different sprites. [...]

I think you're being disingenuous if you believe that the old armoury and generic security lockers were more different before/currently than they are with this.

image


> Normal security and the warden locker already had readability issues, and those issues haven't been solved with this change, and possibly made more confusing. [...]

See what I said before about the tac locker. Your memory is giving you bias if you genuinely believe that they were more distinctive before than they are now.

image


> If I opened a security locker, armory locker, a syndicate gear locker and an emergency firefighting locker right next to each other in-game right now, I can easily tell which one is which by just looking, but it would be a lot harder with this resprite. I have trouble even seeing that the secure lockers have locks because of the blending color of the lock.

What is the circumstance in which this would happen? This is a nirvana fallacy and just seems like an attempt at an appeal to consequence. Again—the only reason they were "distinct" before, was due to palette bloat, Discounting the weird door of the fire extinguisher closet—which looks more like an error than anything else—the only one of these distinguishable beyond the stripes at the top is the syndicate one, which I don't think should be considered because I've yet to see a syndicate locker next to anything besides another syndicate locker.

image


> I'd argue that, if I cannot tell what a locker is when it is opened, and I have trouble even identifying the difference between a secure and unsecure locker, but I could before even with very subtle differences like the stripes along the locker extending over the roof of the locker, then I think we've lost more than gained from a redesign. It isn't just a color issue, but an overall design issue. There simply isn't enough distinguishing qualities between the lockers beyond the doors, and the features are too disguised in amongst the rest of the locker. And those distinguishing qualities are lost if the doors are swung open, obfuscating the locker entirely beyond a potential handful of similar lockers that it could be.

This was just as present before, as it was with this. The only reason they were more distinguishable was because there were seventy different styles of reds, blues, whites, and every other colour within the RGB spectrum. The only noticeable distinctification before was that of the stripes, which I don't consider that important as it was usually just one or two pixel-wide lines of varying colours.

image

image

> The CE locker is literally the worst example of all the problems I've brought up, however, as not only does the logo blend into the locker itself, but it would be difficult to tell it is even a command locker and not actually a generic medical/research locker.

Again—as I said before regarding the sec/arm/ext/whatever-the-fuck example, the only differential before was the stripes, the yellow one I am not even sure is recognizable as the CE. And—conjecture alert—I'm not sure the last time I saw the CE locker ever leave the CE's office, let alone be put next to something like a medical locker or science locker. I understand that your point is they are similar, and you are giving an example, but the times when this could be an issue seem far off and not worth considering.

image

A lot of the cruxes of your arguments seemed to be based on what they looked like opened, but I am not sure when lockers that are radically different in functionality, but similar in design are placed next to each other in a way where quick misidentification is possible. And, while this is entirely conjecture, very rarely do I see lockers kept open all the time. Doubly so next to other lockers that are also being kept open.

I will concede tho, that some of the colours, notably I believe the medical ones do blend in, I can't deny that one.

**Comment by YakumoChen** [comment]
I feel like a horizontal stripe along the locker roofs would solve most "clarity whole open" issues

Personally would like to see the CMO and HoP locker use a palette closer to their uniform colours again as well

**Comment by TheVekter** [comment]
> I will concede tho, that some of the colours, notably I believe the medical ones do blend in, I can't deny that one.

Is that something you intend on addressing, or is this the final version and you don't intend on changing anything?

**Comment by necromanceranne** [comment]
> I think you're being disingenuous if you believe that the old armoury and generic security lockers were more different before/currently than they are with this.

The white stripes are a genuinely distinguishing component. It's a heavily contrasting color from the red. I can recognize that locker immediately (yes, even when open), and most people will know it is different from the security locker. I'm not sure why you would think I can't distinguish these, I have eyes.

> See what I said before about the tac locker. Your memory is giving you bias if you genuinely believe that they were more distinctive before than they are now.

I think you may be misinterpreting me because you are proving my point about these particular lockers for me. I said they already had distinguishing problems; the extremely faint orange stripes are barely distinguishable against the locker itself and against each other. I do currently have problems telling the difference between a normal security locker and the warden's locker. The new sprites still have that problem and maybe worse.

> What is the circumstance in which this would happen? This is a nirvana fallacy and just seems like an attempt at an appeal to consequence. 

You seem incredulous that these might appear in proximity, but three of the four lockers I mentioned are station lockers. The fourth, the syndicate gear locker, do actually appear in a few places in the game world beyond the nukie base. Away missions, space ruins, etc. Very rare to show up on station but not impossible. Space explorers like to drag them onboard sometimes.

Anyway, my main point is that, despite your insistence that I'm somehow unable to distinguish them and I'm being disingenuous, the only one I do have problem distinguishing is the security locker and firelocker if only because that orange stripe is so poorly contrasting against the red. But I would actually be able to point it out once I see that. As I said, that is a present issue with the sprites. I can, in fact, otherwise tell the difference between the syndicate, armory and either the firelocker or security locker at a glance and always have been because they either use a different palette, or they have distinguishing marks that stand out on the sprite.

(Additionally, the armory sprite and syndicate lockers appear near each other on the battlecruiser, but that isn't really the crux of my argument)

> This was just as present before, as it was with this. 
> A lot of the cruxes of your arguments seemed to be based on what they looked like opened, 

My point is that with a redesign, you have an opportunity to make significantly more distinguishing features of the whole body of the sprite to help alleviate these issues I've brought up. Something as simple as a strong contrasting highlight on the entire body of the sprite (both open and closed) can go a long way to helping telegraph to players 'Yes, this one is different'. Maybe the warden has a yellow band along the bottom of the locker (and on the inside). Maybe the armory locker has a white one. Maybe it would be a good idea to look for a different color palette for the CE locker. There is no reason to keep everything consistent to what it was before if it would benefit greatly from an entire redesign. Hell, you have separate entire sprites for these bases despite them just being copypasted sprites, so take the opportunity to make them more noticeably unique.

> I will concede tho, that some of the colours, notably I believe the medical ones do blend in, I can't deny that one.

It's maybe my biggest gripe, so I would be most happy to see this addressed at least.

**Comment by LSommers** [comment]
... why don't the resprites all open on the same side?
Why are the locks and handles in the _middle_ instead of at the side?
What do the backs of the resprites look like?
Why are the new ones so difficult to tell apart, and generally just visually overly busy?

**Comment by Timonkeyn** [comment]
how can you hide in a closet with a seperation in the middle

**Comment by anclandor** [comment]
These proportions seem very odd.  All the lockers are taller and you can see far more of the tops than on the old sprites.  Its as though you stretched out the lockers.  What was the reasoning behind this change?  It is very jarring that they reach into the tile above them. 

 Another issue with the tops of the lockers, it seems like you tried to give them a fillet effect, which is cool, however on some of the lockers it gives the impression there is a ridge sticking out on the top.  I recommend you get try and rework that effect or just make the tops have sharp corners between them and the body.

**Comment by YakumoChen** [comment]
> how can you hide in a closet with a seperation in the middle

That was already there on the current locker sprites in many cases

**Comment by Timonkeyn** [comment]
> > how can you hide in a closet with a seperation in the middle
> 
> That was already there on the current locker sprites in some cases

Where

**Comment by YakumoChen** [comment]
> > > how can you hide in a closet with a seperation in the middle
> > 
> > 
> > That was already there on the current locker sprites in some cases
> 
> Where

Hydro and chemistry lockers
It's not like you can't cram spacemen in with the divider anyway, and it's actually not a bad design?

**Comment by Timonkeyn** [comment]
> > > > how can you hide in a closet with a seperation in the middle
> > > 
> > > 
> > > That was already there on the current locker sprites in some cases
> > 
> > 
> > Where
> 
> Hydro and chemistry lockers It's not like you can't cram spacemen in with the divider anyway, and it's actually not a bad design?

Honestly never noticed. But I feel like it would take me out if I got into a locker with an obvious divider. Also since these sprites are brand spanking new shouldn't they address this and not repeat it on almost every locker type

**Review by MrMelbert — CHANGES_REQUESTED** [review]
You need to update `door_anim_angle`, I believe.

The animation is currently goes too far, and has to jump to accommodate. 

https://github.com/tgstation/tgstation/assets/51863163/e80acad9-be4f-4774-b7a6-8da5c3304346

**Comment by MoffNyan** [comment]
I can see that you worked really hard on these sprites, and they do look nice but they have a lot of glaring issues outside of just "nostalgia lenses". I asked a few outside art friends who don't even know about SS13 for help in writing this critique, and I hope that it can help you in the future as you continue to learn!

First of all, I love how you used contrast in the shading, it makes your sprites pop and really stand out! However, it is slightly over-shaded which not only causes it to look very dark and out of place within the game itself - it also causes some strange visual effects because of the inconsistencies of the shading.

If we were to imagine the locker in a 3D plane, the way you have shaded it would imply a strange dent in the front like this;
a
I don't believe this was your intention, but the door does not appear "flat" as a door would be. It's important to remember that when spriting - every pixel has the ability to change the entire outcome of the piece.

Next, when the door opens up it leaves a small gap on the bottom as if there is supposed to be an area between the bottom and the inner contents of the locker. That is a very nice idea, and if executed well I'm sure it would look lovely! However, on the closed door sprite it is obvious that the door extends all the way down;
b
Also I chose these two sprites in particular because the colours chosen are contrasting colours, meaning that if you were to take a colour wheel you would find that they're close to being on the opposite side of the wheel. There is nothing wrong with these colours, it just takes a little extra work to get them to work together! This starts getting into colour theory, of course...

The orange on the top of the locker is very saturated, it's a very lovely orange but orange and red's tend to attract the eyes because they are very bold colours. This means that the viewers eyes are going to be more focused on the top of the locker than on the green/purple of the locker or the decals that decorate the front. When it comes to designing sprites for games, we would want there to be a "focal point" of each sprite. You have to ask yourself; "What is the main purpose of this sprite? What do I want to convey within a short cursory glance?"

The answer in this case would be; "The decal which conveys the most important information of what this locker is and what it is for."

But with the very eye-catching orange, it takes your attention away from the decal, which also starts to get very muddy and hard to see within the dull dark green and purple you used. Maybe you have some sense of colour theory, which is great! Making one contrasting colour brighter and the other duller to balance the two colours out can definitely work - but in this case it is actually making the sprite lose it's overall impact.

I am not a fan of taking an artists work and changing them to fit my own idea of what's "good", however I decided to hue shift the colours very slightly to give a demonstration of what I mean;
c
(This is not to fix problems of the sprites, it is simply to demonstrate my words with examples. I could've also made the biohazard decals brighter/more white for a bigger effect.)

I've de-saturated and lightened the orange to be less eye-catching, and brightened the green/purple to be more balanced with the orange and less "muddy". At a cursory glance you would be able to see the biohazard symbol a lot easier than before, if nothing else.

Also; one of the questions I asked myself when I was thinking is; "What did the old sprites get right, when they have contrasting colours as well?" I had to ask around a bit, because it wasn't really easy for me to figure out right away either.

It's true that colours on opposite sides of the colour wheel are contrasting colours, but another name for them are "complementary colours" - because when they're used well together they can look very striking! Red/green and purple/yellow are directly opposite from each other, but they have been slightly dulled in such a way that they don't seem unpleasant to the eyes. The yellow has been reduced to a very cute stripe across the front of the locker to not muddy the appearance of the biohazard symbol. None of the colours used fight for your attention or take attention away from the most important part - the decal.

I would also like to bring up one last point; that you shouldn't focus on making all sprites look perfectly uniform either. If you look at the old sprites there are many variations in the designs, mixing stripes, decals, and the banners of the locker-room lockers. Uniformity seems nice as a concept but appears quite dull when everything looks the same. Patterns and "sameness" should be used to enhance the main focus that draws your attention in a design, not take it away! This is why people may complain about a lack of "soul", it is not only nostalgia lenses - but the removal of what made the sprites unique in the first place.

Sorry this was a long read, but I honestly do feel like you have the ability to make great sprites! If you continue to study colour theory and the design principals of picking out "focal points" you should be able to improve and make sprites that can make both yourself and others happy!
gratefulroach

**Comment by dalmationer** [comment]
I agree with most of @MoffNyan 's feedback above, but I wanted to outline some of my own crit on these!
All in all, I like the chunkiness of them and the fact that they feel like they have weight. They look big and bulky, and that feels right to me.

Some feedback: 

1. I feel that all logos on lockers should be in flat colour, with a good amount of contrast with the colours around them. This helps to work out at a glance what type of locker it is, E.G the old biohazard and old engineering lockers both have very distinctive logos. Your designs do still have logos, but they are smaller and harder to see with the shading. For hazard equipment such as biohazard suits, firesuits and bomb suits, it should be VERY obvious (note that the old bomb suit locker does NOT do a good job of portraying this, and should probably have some variation on the GHS hazard pictogram for explosives. Or maybe a funny cartoon bomb). I also feel that the sec lockers, Chem lockers and botany lockers are unclear on what they're meant to be, as they no longer as obviously match the departmental colours due to the removal of the famous Stripe.
2. I feel that many of these sprites are afraid to commit to high brightness. Bright sprites with less shiny shading can sometimes be looked down on as 'amatuerish' but I feel for the artstyle of SS13 brighter is often better, especially as the dynamic lighting system in the game already tends towards quite dark once you get more than 30 minutes into a round.  The O2 and fire lockers especially I feel should be brighter so that they stand out, as they're a very important aspect of gameplay, especially for newer players who will often arrive late on the station and need them to leave arrivals if it's been vented.
3. My most substantial criticism: I feel that the locking light does not have much contrast with the pixels around it on some lockers. This was a problem in previous locker sprites, and the last resprite went a good way to fixing it. Note the sec and botany lockers in particular: the red and green lights will be difficult to see against the middle of the locker. The lock is also not near where the 'latch' of the locker would be, though this is less of an issue than the colour. I can see folks who are new to the game not understanding when a locker is or isn't locked. One way to fix this would be to have some darker pixels around where the locking light is.

Overall, I think the shading is somewhat too dark, but I like the new shape of these lockers and the new door. I think the main thing to focus on is gameplay/user design. How can you be clear at a glance what's inside them, how can you tell them apart, how can you tell when they're locked. If one gets stolen and found in maint, where would you try to return them? Etc.

Hope this helps!

**Comment by Colovorat** [comment]
Color choice on some of the lockers is very bad. Like it actually hurts my eyes to see so many colors on one locker. Sprites are too heavy on the color amount. Old sprites are simple, easy to distinguish. Plus the new color you picked for departaments lockers feels conflicting with the color of the departaments themselves, like medical

**Comment by AGasCanister** [comment]
GOOD MORNING TG GITHUB!!♥♥♥ MAKE SURE TO CREATE GOOD DRAMA TO READ!! :D 

https://github.com/tgstation/tgstation/assets/55928412/12f5e1ce-c0f3-4d26-8865-9f269f680102

**Comment by justricky21** [comment]
@MoffNyan's hue change made it WAY easier in the eyes to read the logo. I'd experiment with a tone lighter so the logo pops a bit more IMO, but I'm not an artist.

**Comment by kinneb** [comment]
can we just spritetainer @MoffNyan it basically summed up all i had to say with pictures for the illliterate (v considerate :-) )

**Comment by Fikou** [comment]
color selection is really wack here, the muted colors of the wardrobes are now half muted and half really popping out, stuff like the transition between the green on the green wardrobe is incredibly contrasted, the symbols on the medical lockers meanwhile are incredibly hard to tell apart

**Comment by saprasam** [comment]
image
i presume this is the opening handle/latch/lock, which raises the question of why it's in the middle. this seems a bit odd & uncomfortable for somebody to realistically use, as locker doors don't swing open like the delorean, while also blocking space for the sprite itself as it's smack-dab in the middle of the sprite.

moffnyan has already pointed out the strange shading on the locker making it look like it would have a dent, and i agree with that. it's odd

the new resprite for the captain's locker does not even remotely fit the captain's actual colour scheme. the captain is blue with a bit of yellow and it appears as if this was completely thrown out of the window for a colour scheme that represents the head of personnel more(infact, the two lockers are the exact same[!!!] besides the initial on the locker), while also looking more dull & sovlless.

overall i think that there needs to be changes on where the locks are on the lockers, the colours need to be less dull & gray, and the captain's locker needs differentiating from the head of personnel.

**Comment by anclandor** [comment]
Where are the handles on the lockers that don't have locks?  Am I just blind?

**Comment by CMDR-Gungnir** [comment]
The old engineering lockers are definitely much more readable. The fire's good, and I can see the wrench, but the biohazard feels kinda blurry, like I'm looking at it without my glasses on, and the lightning bolt is just a diagonal line.

I don't know why the Lock light is in the middle instead of at the lock, but it's not unbearable, even if I think it's a downgrade.

I don't know why half of the lockers open to the left, and the other half to the right, though. I feel like "Most of these lockers are the same except they've just been painted for what they're used for" is very fitting and good.

I also agree with Anne about the red lockers. The stripes, when they were used, were very good for helping make lockers stand out. Even if it wasn't done the *best* every time with the old sprites, isn't the point of updating them to make them better?

**Comment by SimplySmiley123** [comment]
Not gonna lie but this to me is a situation of "More complex isn't always better."
It's hard to make out what the lockers are supposed to be for honestly with all the fancy details.
No, it's not bias from "playing too much" before you say it again, it's simply the fact these sprites are too busy for what they are to recognise them at a glance, if anything it makes the lockers that already aren't the easiest to tell apart from each other, somehow worse to tell apart (engineering lockers, which with current ones you can at least tell apart regular engineer and atmos tech lockers from each other at a glance thanks to the stripe that sticks out way more then a tiny icon with colours blending together especially in case of the atmos one).


_Also to be honest your "security" lockers look more Syndicate then Security._

**Comment by Fikou** [comment]
> color selection is really wack here, the muted colors of the wardrobes are now half muted and half really popping out (like the pink one standing out incredibly among the others), stuff like the transition between the green on the green wardrobe is incredibly contrasted, the symbols on the medical lockers meanwhile are incredibly hard to tell apart

**Comment by Draggeru** [comment]
I am partially red green colorblind, a lot of these sprites are near impossible to decode with all the cluttered details.

**Comment by Timonkeyn** [comment]
> I am partially red green colorblind, a lot of these sprites are near impossible to decode with all the cluttered details.
> 
> Edit: I physically cannot tell the difference between the security and syndicate lockers, the medical lockers all look the exact same, and so do the engineering lockers unless I squint really hard.
> 
> These sprites are not visually accessible

Deuter
This is what it may look like to dragmeme. of course its not a 100% accurate depiction of Deuternopia (what im guessing you have) but it comes close.

i dont want to sound albeist, but to me as a normal vision person this doesnt look THAT bad. but i do agree if you look at it with complete color blindness youre going to have a pretty hard time.

**Comment by TheVekter** [comment]
@axietheaxolotl Are you going to address any of the feedback you've been given in this PR or just concentrate on the ones being mean to you? There's a lot of good stuff here and it's really frustrating seeing you actively talking on the forums about one specific person being a jerk while ignoring the 10+ comments telling you the sprites need to be changed.

**Comment by Howluinb** [comment]
> i dont want to sound albeist, but to me as a normal vision person this doesnt look THAT bad.
I'm sorry but these are literally unreadable, you are not able to tell what locker is what *at all*.  While wanting to make lockers look better is a nice intent, making them literally impossible to tell apart without thorough learning as a colorblind person is not at all a good thing.
The first thing these should accomplish is being visually distinctive enough to be able to be distinguished by *anyone*, especially with their importance in game. Aesthetics should be second.

**Comment by mc-oofert** [comment]
kinda doubt anything is getting addressed here considering author got permad

**Comment by axietheaxolotl** [comment]
yeah, ok. gonna come back to this, I'd post this in /tg/discord but I am banned, and most likely will be banned here sooner then later: I am not gonna make a spiel about this, because it's boring, but a friend talked to me recently and has regarded me as being a massive fucking asshole, so. gonna work on some stuff.

player's club, since I know you are watching this: yes, I am an asshole, you can post your ripbozo memes now. to @MoffNyan: I apologise for how I spoke to you, and I apologise for misinterpreting what you said. I am sure this comment will be trolled and made fun of in the forums, but it is sincere. 

so, i'mma take a break for like, two months, and i'mma come back later. shit's been goin' on, and I should prob' reassess how I act.

anyway >inb4 post hidden due to being marked as off-topic

**Comment by TheVekter** [comment]
@axietheaxolotl I hope you get things sorted out.  You don't seem like a bad person, just someone who's going through it. Hopefully this helps for the better.

**Comment by mc-oofert** [comment]
good riddance

**Comment by TheVekter** [comment]
Phone fucked up and made me hit reopen my bad

**Comment by Time-Green** [comment]
@axietheaxolotl good luck bro

**Pull request closed without merging**
