### PR TITLE
Autoprocessing for the dead [READY]

### PR DESCRIPTION
**Pull request by 4dplanner**
:cl:
add: Re-added autoprocessing function on the cloner
balance: records now have an associated last death time, which must sync with the mind to clone. This means you need a new record every time someone dies.
add: diskette records can be partially applied to records in the cloner, for instance to overwrite a name.
add: you can still scan living people to obtain their records for disk use, but these records can't be cloned from.
fix: cloning records are no longer based upon ckey
tweak: ghosts are no longer required for scanning
balance: Head access is no longer needed to delete records
balance: genetics access is required to alter (but not delete) records
add: do not resuscitate verb added for ghosts (can be toggled on and off)
/:cl:

Previous changes done in a neater way. Helps medics clone large piles of bodies, but doesn't provide a safety net.

Ghosts are no longer required for scanning so if you miss the prompt you're not screwed over, but you can set Do Not Resuscitate if you don't want to be cloned.

todo:
- [x] label GCAT mutations
- [x] allow partial modification of cloning record, i.e. put in a different UI/SE
- [x] restrict modification to genetics access
- [x] make cloning disks compatible with genetics machines

"Features" that may need to be removed:
As before, this acts as a changeling test. Pre-scan someone, then scan them again when you think they might have been replaced - if they're a changeling, it'll create a new record instead of updating the old one.

Decisions to be made: 
should being placed in the cloner give you a notification?
should autocloning prompt the ghost instead of the DNR system?
should you receive a detailed "cannot clone from outdated record", or should the extra information gained be limited?

### CODE REVIEW

**Comment by 4dplanner** [comment]
Basically, whenever you die your mind updates it's last_death variable. Scans will only revive mobs with the same last_death as the scan itself. By examples:

Grey Tide dies, and is scanned. He then autoclones normally.
Grey Tide is scanned while living. You can get his UI, SE, and so forth, (useful for podcloning), but you can't clone him if he dies.
Grey Tide dies, is scanned, is defibbed, then dies again. The record is outdated, and so cloning fails.

**Comment by Trazen4** [comment]
So wait, if someone tries to prescan /at all/ that person can't be cloned ever? 
If so, that's fucking retarded.

**Comment by Tlaltecuhtli** [comment]
wat

**Comment by 4dplanner** [comment]
> whats the point of prescanning if it doesnt work when you die? giving a blood sample to doctors is more interesting




The main reason is that various attributes from the record can be applied to other records, so you could replace everyone's name with yours while you clone them/apply a stored race/give mutations to everyone cloned. I think this could be cool, and so is reason enough to have live scanning.
Genetics can also look at your data to help build mutations. This is a minor bonus.

I'll update the title.

**Comment by kingoftheautism** [comment]
Huh, this is gonna be just like one of the rounds on russian servers where one dude replaced entire crew DNA with his own, resulting in entire crew turning into traps, chaos, and blaming each other

**Comment by 4dplanner** [comment]
I can't tell whether you think that's a good thing 👌

It might be worth adding in an access check, so that only geneticists and CMO can alter records.

**Comment by Cyprex** [comment]
Fantastic, thank you for this!

**Comment by kingoftheautism** [comment]
Are you saying this to me, because I'm assisted/prevented some trap CMO replacing entire crew UI and UE with his own to turn everyone who will die into traps?

**Comment by adamkad1** [comment]
So i dont need to buy a emag to remove records now? Also it doesnt make sense you need acess to modify but not delet

**Comment by 4dplanner** [comment]
> So i dont need to buy a emag to remove records now? Also it doesnt make sense you need acess to modify but not delet

I actually changed this but messed up the changelog, check #41988

**Pull request merged**
