### PR TITLE
Delta Departures Streamlining AKA Delta Departures Desouling

### LINKED ISSUE #62922: Pubbystation EMS shuttle docking with Delta Station causes purest form of comedy
## Testmerges:

Server-Side Code Modifications: https://tgstation13.org/parsed-logs/sybil/server_side_modifications.dm

Round ID: [173214](https://scrubby.melonmesa.com/round/173214)
BYOND Version: 514.1557
Server revision compiled on: 
Master commit: a41c00426dbb63f1e88b512fd9270b29ff1e4926
The following pull requests are currently test merged:
#62711: 'Allows players to send more visible adminhelps when no admins are on, which'll definitely alert admins' by Watermelon914 at commit dc963ca82a

Local commit: 46c7e5c4f6d3f0b859b9fdd5dbf315382e8a8ecd
TGS version: /tg/station 13 Server v3.2.6.2
DMAPI version: 3.2.1.3

## Reproduction:
1. Have Pubby EMS shuttle dock with Delta station
2. Listen for the [laugh track](https://www.youtube.com/watch?v=J83lw0eFIJA) as it gibs an innocent chemist upon docking because it intersects the station (I feel like unless the station is rocking a meme shuttle that it should be avoided to have the shuttle crush parts of the station, no?)
image

### PR DESCRIPTION
**Pull request by MassacreDemigirl**
## About The Pull Request
Makes Delta Evac and Delta Shuttle more inline with rest of the evacs by moving the security post to the right side. This is achieved by making the Evac Dock to the Aft side of the Departures rather then the starboard and also flipping and remodelling the Delta Emergency Shuttle. 

This is a soulless version of #64381

## Why It's Good For The Game
Makes other shuttles work far better with Delta Station and also the Delta Station Emergency Shuttle work well with the other stations. This prevents the Delta from or the Delta Shuttle on other stations to hog one of the civilian entrances thus making only 2 Airlocks out of 4 usable. 

Also closes #62922

## Media
delty

delty

## Changelog

:cl:
qol: Expands the Delta Station Evac to make it in line with other shuttle designs.
qol: Makes Delta Shuttle in-line with rest of the station designs
Fix: Pubby Emergency Shuttle no longer impales into the station.
/:cl:

### CODE REVIEW

**Comment by jlsnow301** [comment]
finally virology will stop getting obliterated by weird shuttles

**Comment by Mothblocks** [comment]
Changelog: Makes Delta even more like Meta

**Comment by ErdinyoBarboza** [comment]
I mean #64381 existed but people found it too freakish

**Comment by BlueMemesauce** [comment]
image

there is chair in front of the door

**Comment by ErdinyoBarboza** [comment]
@BlueMemesauce fuck. yeah fixed it thanks

**Review by san7890 — COMMENTED** [review]
Looking at the screenshots, I just noticed that your stasis dir is off. Would you mind pointing this easternly?

image

**Review by Maurukas — CHANGES_REQUESTED** [review]
While the shuttles crashing through the station is an issue, I can't say I like this as a solution. There's large amounts of unused space at the north and sound end of departures - no objects, no decals, no use.  The rest of the decal work here isn't that spectacular - hazard stripes everywhere, around things that aren't actually hazardous - the chapel, the north side of the room. Security, even most of the south. The rest of the decals are heavily repeated.

If you want to take another crack at this give me a ping when it's ready.

**Comment by ErdinyoBarboza** [comment]
@Maurukas It has been done, waiting feedback

**Comment by ErdinyoBarboza** [comment]
i fucking hate git

**Comment by EOBGames** [comment]
Sorry for not getting to this before the merge conflict hell- I've meant to drop in and explain the issues for the past week or so but keep getting caught up in different things.

Anyway, I know it's not ideal to hear at this point after you've fixed it a few times, but I wasn't particularly happy with the overall design presented here. While I appreciate that it was attempting to fix an issue with larger shuttles, and while I do think there's merit in making the brig fit better, I don't think this design goes about it right. The security office feels slapped on, it doesn't mesh well with the rest of the station around it. The changes to the shuttle also don't flow well. Overall, I think to fix the issue it'll require more than a quick reshuffle like this PR presents and something more akin to a full redesign of the departures area of Delta.

**Pull request closed without merging**
