### PR TITLE
[MDB Ignore] Remaps KC13 + Mapper Terminals

### PR DESCRIPTION
**Pull request by unit0016**
## About The Pull Request
Remaps KC13 from the ground up - It's now based on Ministation rather than Oldstation, has a bunch of extra detailing, terminals, additional things to do... Oh, and the gameplay loop is different now. Setup time is both drastically shorter and slightly more involved.

In addition: This PR Introduces a new mapper object: Terminals! They're weirdo computers that display text for their reader, but can't be edited in game. They're meant for ruin and away mission mappers primarily.
<details>
<summary>The Map Itself</summary>

oceea94

</details>

<details>
<summary>Terminals In-Game</summary>

image

</details>

## Why It's Good For The Game
KC13, ironically, is aging fast. I tried my darndest to get it up to standards originally, but I ultimately decided a full remap was in order. This *also* gives derelict drones more to do in the bounds of their laws with some setup, so drone players don't speedrun getting bored as they seem want to do.

## Changelog

:cl:
add: KC13 Has been entirely remapped! Don't ask me how this one works out in context, I have no answers.
add: Mappers can now play with a new object: Terminals! You can now do "the lore dump" in "the video game" and work at "the company with gears in the logo that makes the bugs".
/:cl:

### CODE REVIEW

**Comment by bruhlookatthisdood** [comment]
Its uh...
quite uh.... 
Intact.

**Comment by Serxule** [comment]
maybe add a bit more destruction, but looks 100x better than the runtime station/maze the current kc13 is

**Comment by unit0016** [comment]
The people have spoken, time to carve out medbay since that's completely useless to drones lmao.
and a bit of central primary for flavor

**Comment by unit0016** [comment]
> Why is the malf AI locked in the bathroom? If you knew your own reference, you know they'd upload themselves to the invading ship.
> 
> * Sincerely, Durandal.

they're just taking a wee man let them be

**Comment by unit0016** [comment]
I have updated it to carve biggun holes all over, delete the dust in spaced areas, and medbay is GONEZO.
I'm now gonna fix that linter.

**Comment by unit0016** [comment]
Linters fixed.
I would like to state I am totally cool if the remap itself gets shot down (It's looking like it's going to go that way as two maintainers have given the thumbs down) - But I would like the terminal to stick around, it's got potential independent of this.

**Comment by Fikou** [comment]
> Linters fixed. I would like to state I am totally cool if the remap itself gets shot down (It's looking like it's going to go that way as two maintainers have given the thumbs down) - But I would like the terminal to stick around, it's got potential independent of this.

neither me nor thunder are maintainers nor maptainers

**Comment by unit0016** [comment]
> neither me nor thunder are maintainers nor maptainers

💀

**Comment by Valorium-RB** [comment]
Meh. Most of the equipment that made the previous version of KC13 interesting (red space suit, syndie toolbox, EMP grenade, swat helmet, old protolathe boards, Mother Drone lawset board, etc. etc.) is gone in favor of generic gear you can get on station much more easily. With old KC13, I'd at least be willing to navigate the labyrinthine halls to try and grab some of the more esoteric gear, but now it's just...a station. Go figure. Don't get me wrong, it's not poorly mapped – it looks quite nice, really – but I'd rather it be added alongside KC13 rather than replace it.

**Comment by bruhlookatthisdood** [comment]
TheDerelict
MiniDerelict

**Comment by unit0016** [comment]
> Meh. Most of the equipment that made the previous version of KC13 interesting (red space suit, the massive jumpsuit locker package, EMP grenade, strange objects, old protolathe boards, Mother Drone lawset board, etc. etc.) is gone in favor of generic gear you can get on station much more easily. With old KC13, I'd at least be willing to navigate the labyrinthine halls to try and grab some of the more esoteric gear, but now it's just...a station. Go figure. Don't get me wrong, it's not poorly mapped – it looks quite nice, really – but I'd rather it be added alongside KC13 rather than replace it.

I completely forgot to readd the mother drone lawset board thank god someone caught that

That being said, most of that is already gone. Minus the detective baton, TEG board, EMP grenade, and SWAT helmet. The old lathe stuff's still here, though ~~I definitely need to readd the hat crate too~~

That being said I wouldn't mind converting it to a generic ruin either, but from what I've heard in-game from admins offstation content isn't a want right now.

**Comment by unit0016** [comment]
> The drones dont speak galactic common, but they can read the terminal?

They can read the papers too, it's wacky. So can people with the foreigner quirk. Just part of the game as far as I'm concerned.

**Comment by unit0016** [comment]
> couldve sworn that last time i played when i examiend a paper it said "you cant make out the words!" or something like that

That wasss. Probably a thing when shy~~t~~ drones were made a part of existence. I'm. Not a fan, but I can say at least before that you could prior to that.
..That change somewhat makes papers irrelevant.
And honestly should cascade into drones being completely byebye, but.

Out of scope 🤡

**Comment by notfrying1pans** [comment]
isnt the point of kc13 that it was nuked

**Comment by Addust** [comment]
if KC13 was nuked then it wouldn't be there, a nuke can cause a shitton more damage than what we see ingame, which is just a few explosions around the tele, shuttles are gone, and toxins is the hole it always is anyway.
i believe the point is it was evacuated after a series of syndicate attacks INCLUDING a failed nukeop team

**Comment by Addust** [comment]
also you may have forgotten the whiteship KC13 docking port

**Comment by unit0016** [comment]
> also you may have forgotten the whiteship KC13 docking port

Nahh, it's where the engine usually is. Made sure to transfer that over.

As for the gravity generator, it'll never not be broken as hell but at least I got the APC working there so everything besides the gravgen doesn't have magic power

**Comment by Addust** [comment]
yea i didnt notice the tiny white dot that was the docking port because my vision is kinda shit

**Comment by Addust** [comment]
also i like how it looks like the station had actually gone through some aesthetic work done by the crew, mainly in the bar

**Comment by EOBGames** [comment]
Alright, I've given this some consideration, and I'm not interested in merging this. The ruin isn't bad, but it doesn't accomplish what the derelict is, in my eyes, meant to- providing a relatively blank slate which can be repaired and rebuilt to the drones liking. This is much more akin to a complete ruin, which isn't providing the same experience. Sorry for having taken so long on making a decision, life has been _very_ hectic on my end for the last month or so.

I would like to see the terminals atomised out and added independently of this PR, however- I think they have good potential as a mapping tool.

**Comment by unit0016** [comment]
👍 

I gotta implement HTML formatting properly in the things anyways. Expect them to come back in a month Ish ~~if I don't get preoccupied trying to mod the fallout 4 companion app~~

**Pull request closed without merging**
