### PR TITLE
make able reading paper in folder

### PR DESCRIPTION
**Pull request by hack-wrench**
## About The Pull Request

QoLed the ability to read papers in a folder

## Why It's Good For The Game

Conveniently store photos and papers in a folder without having to reach in and disorder them

## Changelog

:cl:
qol: make able reading the paper in the folder
/:cl:

### CODE REVIEW

**Comment by ZephyrTFA** [comment]
Please raise your gbp.

**Comment by hack-wrench** [comment]
done, pls reopen

**Comment by necromanceranne** [comment]
this seems like a consistency issue, not a full feature

**Comment by ZephyrTFA** [comment]
This is not a fix.

**Comment by hack-wrench** [comment]
Ok, its QoL

**Comment by ZephyrTFA** [comment]
Yeah no. 
Because you continue to try and abuse tags I'm placing you on a week long restriction

**Pull request closed without merging**
