### PR TITLE
SM Sound Tweak

### PR DESCRIPTION
**Pull request by ninjanomnom**
Naksu complained enough at me so I changed 2 lines of code

:cl: ninjanomnom
tweak: Reduced the max volume of sm by 1/5th and made the upper bounds only play mid delamination.
/:cl:

### CODE REVIEW

**Comment by ninjanomnom** [comment]
The length is almost certainly going to make this play badly with lag, we'll have to see how much it breaks up

**Comment by Repukan** [comment]
Hugbox

**Comment by Repukan** [comment]
>Code solution when you can just reduce your volume

Vev lad

**Comment by JJRcop** [comment]
@vuonojenmustaturska

**Comment by vuonojenmustaturska** [comment]
You can't individually reduce the fucking annoying SM sound that's about 200x louder than everything else in the game.

So thank you.

**Comment by Armhulen** [comment]
@Repukan I wasn't that much against this comment, but poster appears to be retarded. That earns a solid 👎 from me.

**Comment by Spaceinaba** [comment]
about time

**Pull request merged**
