### PR TITLE
Kills obj/item/projectile in favour of obj/projectile

### PR DESCRIPTION
**Pull request by nemvar**
## Why It's Good For The Game

item and projectiles shared exactly TWO variables (being armour_penetration and hitsound). They don't use the same procs. They don't share other behaviour. It makes no sense to have the extra overhead from the item path for projectiles.

Somewhat tested. Didn't seem to cause issues.

### CODE REVIEW

**Comment by Time-Green** [comment]
Alternatively make people able to catch bullets and lasers from the air

**Comment by nemvar** [comment]
Just a preemptive warning. I am moving right now so if this gets stale, I'm sorry.

**Comment by Rowelll** [comment]
> Alternatively make people able to catch bullets and lasers from the air

sleeping carp feature

**Comment by ATH1909** [comment]
> > Alternatively make people able to catch bullets and lasers from the air
> 
> make it sleeping carp feature

A N T A G   F R E E Z E

Give it to CQC instead so you can say that it's a chef feature.

Also, does this PR make projectiles unable to get deep-fried in midair by sprayed (hot) cooking oil?

**Comment by ShizCalev** [comment]
conflict.

**Comment by ExcessiveUseOfCobblestone** [comment]
todo: this

**Comment by nemvar** [comment]
Testmerge of this would be neat.

**Comment by ExcessiveUseOfCobblestone** [comment]
todo: this still

**Comment by nemvar** [comment]
Read like three logs that had this testmerged. Seems to work (or at the very least it's not throwing any runtimes for whatever that's worth.

**Comment by ExcessiveUseOfCobblestone** [comment]
yeah i haven't seen any issues with this even in nuke ops (projectile heavy rounds)

**Pull request merged**
