### PR TITLE
A bunch of new tile variants and dark tile decal.

### PR DESCRIPTION
**Pull request by manofpepsi**
## About The Pull Request

The 3 rows on the left were all sprited by twat, while I made the corner variants for the rest, and the dark corner decal present on top of some of those tiles.
image

## Why It's Good For The Game
makes working with the edge tiles easier 
image

## Changelog
:cl:Pepsiman0, Twaticus
imageadd: New corner variants for the textured and smooth tiles
imageadd: New normal, white and dark tile variants
imageadd: New dark corner decal
/:cl:

### CODE REVIEW

**Comment by maxymax13** [comment]
i wish the texturing on the white ones wass less harsh and the texturing on the black ones more darker, it's kinda weird that one has really visible texturing and the other it's nearly invisible

**Comment by manofpepsi** [comment]
> i wish the texturing on the white ones wass less harsh and the texturing on the black ones more darker, it's kinda weird that one has really visible texturing and the other it's nearly invisible

yeah, and they also need some little shading.

**Comment by Dorsisdwarf** [comment]
I like this set of variations (quibbles about new tiles aside) Do you have a use-case in mind for where you'll want to add these once they're added to the codebase?

**Comment by manofpepsi** [comment]
> I like this set of variations (quibbles about new tiles aside) Do you have a use-case in mind for where you'll want to add these once they're added to the codebase?
<details>
<summary> yeah </summary>

image

**Comment by manofpepsi** [comment]
image

**Review by Twaticus — APPROVED** [review]

**Comment by Mothblocks** [comment]
oh i shouldve removed feature before i did that huh, oops

**Comment by maxymax13** [comment]
corrupt mantainers KNOWINGLY STEAL GBP of POOR SPRITE LEAD (exposed?)

**Pull request merged**
