### PR TITLE
 Refactors spider directives completely into objectives, progenitors and ancestors

### PR DESCRIPTION
**Pull request by Militaires**
[bruh](https://www.youtube.com/watch?v=P2eqx_IPeRY)

closes #44099 
image
explanation
- complete rework of directives: are actual objectives now
- all nurse spiders can change their directive
- matriarchs are always independent
- nurses are subordinate to matriarchs if made by a matriarch
- matriarchs can control an unlimited amount of generations, however, if their descendant is a matriarch
they can not control it or its descendants
- nurses who are subordinate to matriarchs are freed when the progenitor dies.
- renamed midwives to matriarchs (seriously bro tf is that)

:cl: Basilman
fix: Fixed set directive action breaking on 2nd generation spiders
tweak: spiders can now change their directive
tweak: matriarchs are now gold spawnable instead of nurses
tweak: midwives renamed to matriarchs 
code: removed directive variable in eggs and spiderlings, spider antag datum
refactor: changed how directives work to use actual objectives
balance: matriarchs are now rarer from eggs
/:cl:

### CODE REVIEW

**Comment by optimumtact** [comment]
can't wait for the inevitable "spider mode"

**Comment by Militaires** [comment]
that already exists it's called xenobio sentients a nurse spider

**Comment by HomocidlePancakes** [comment]
Add the progenitor in objectives too

**Comment by Militaires** [comment]
already shows you progenitor

**Comment by Arathianen** [comment]
Hi, 

I don't like this change. I do like the new name for midwifes to matriarchs, but what this change would do is make spiders COMPLETELY uncontrollable by anyone. If you actually wanted to control them, you would have to actually order the original matriarch to sit back and do nothing all game and even then, the new matriarchs would fuck shit up.

Also, matriarchs never spawn from xenobiology (as far as I know), only nurse spiders do and with this change they can only control 1 gen. 

This would effectively change spiders from something that is mostly an antag tool with the very occasional patrol/security/roleplay spider option to the biological equivalent of a bomb that will inevitably kill everyone, including the guy creating them. All spiders would automatically be aggressive because no other option would be available long term and everyone familiar with them would know it.

The current situation with directives being permanent is a preferable situation and allows for more flexibility of spider use. Also, splintering spider directives would be a NIGHTMARE for mods. Is a spider with "friendly" directives with sets antag directives breaking the rules? Who the fuck knows.

But really, I really do like the matriarch name. Can we change that?

**Comment by Arathianen** [comment]
Also, quick note, we recently had a great tweak in 

https://github.com/tgstation/tgstation/pull/44099

which made directives bolder and added them to memory already. In that regard, the memory change is vestigial.

**Comment by Militaires** [comment]
>Also, matriarchs never spawn from xenobiology (as far as I know), only nurse spiders do and with this change they can only control 1 gen.

### they already only control one gen 

>I don't like this change. I do like the new name for midwifes to matriarchs, but what this change would do is make spiders COMPLETELY uncontrollable by anyone. If you actually wanted to control them, you would have to actually order the original matriarch to sit back and do nothing all game and even then, the new matriarchs would fuck shit up.

read the pr, the matriarch thing only happens if there's even a matriarch who gave birth to the nurses

**Comment by Arathianen** [comment]
>they already only control one gen

That is incorrect. It was changed roughly 2 weeks ago. Right now, all spider gens keep their directive. You are effectively reversing that change.

>read the pr, the matriarch thing only happens if there's even a matriarch who gave birth to the nurses

I read it. What this does is that a nurse spider who will become sentient in xenobio will give birth to 100 spiders, 2-3 of which will be matriarchs. Those will give birth to X number of spiders, all of which will be completely rogue as far as anyone is concerned.

The only way this change can work is if you add a real tier above nurse/matriarch spider (broodmothe type) similar to an alien queen that would have absolute control while it lives. That way spiders wouldn't break down instantly unless they broodmama died, which would at least make RP sense.

Otherwise, as I stated above, you change spiders from, CURRENTLY, a controllable situation to a biological bomb. It's a step backwards.

**Comment by Militaires** [comment]
#43864 made the first generation of nurses able to change their directive which actually results in LESS homogenous spiders than a nurse making 50000000000 spiders then 1 matriarch giving birth to a new strain, instead the nurses in every single batch the progenitor lays effectively have their own strain

**Comment by Arathianen** [comment]
Okey, here is the usual xenobio scenario which I have done literally a dozen times:

you use 20 slimes. You find your future broodmama. You make her sentient and feed her 20-30 monkeys. She sets up your directive.

Spidertide begins, all future spiders follow the same directive of the original broodmama.

If a xenobiologist makes like 10 broodmothers directly sentient and doesn't give them a directive to implement, that is on the xenobiologist, not the code. If you make 1-2 broodmothers sentient and just tell them to set your directive, all future generations CURRENTLY follow 1 directive. It's not confusing unless (for whatever reason) you give 2 different directives.

**Comment by Militaires** [comment]
well kek then looks like you'll have to spend more effort in xenobio filtering through spiders, giving sentience to a nurse, making it give you a matriarch then commanding THAT matriarch, having an instant and infinite army of spiders is a dumb thing for xenobio anyhow

**Comment by Arathianen** [comment]
>well kek then looks like you'll have to spend more effort in xenobio filtering through spiders, giving sentience to a nurse, making it give you a matriarch then commanding THAT matriarch

Any player can jump on any player-spawned spider. Aka you can't make a matriarch sentient if it's sentient already.

The next matriarch could just instantly give itself antag directives and have it go on a murder spree because this change makes spiders completely uncontrollable.

Again, what your change does is make spiders effectively a station-wide bomb and directiveless. Why is that an improvement over them having a directive? If having spiders being directiveless is better in your opinion, why go through this overly complicated system and not just delete their ability to set directives? Are you honestly telling me that the 12th gen spider spawned is gonna remember to properly set directives? What is the xenobiologist supposed to be doing in this situation?

**Comment by Militaires** [comment]
>The next matriarch could just instantly give itself antag directives and have it go on a murder spree because this change makes spiders completely uncontrollable.

almost as if matriarchs are rare, and almost as if you'll need to spend actual effort on your spider army weeding out newborn matriarchs instead of spawning 1 nurse and having an instant unstoppable power

**Comment by Arathianen** [comment]
> > The next matriarch could just instantly give itself antag directives and have it go on a murder spree because this change makes spiders completely uncontrollable.
> 
> almost as if matriarchs are rare, and almost as if you'll need to spend actual effort on your spider army weeding out newborn matriarchs instead of spawning 1 nurse and having an instant unstoppable power

Almost as if that is completely impossible because SPIDERLINGS VENTCRAWL TO HALF THE STATION.

Dude, seriously. Just say you wanna remove directives to spiders. This is what this change does. Simple as that.

Spiders already take about 50m of setup. ANY security or AI intervention can and will kill them all. Any breach to xenobiology will stop them at their tracks. Spiders are not even close to unstoppable and the vast majority of times I have attempted them I have failed because someone bombed half the station, because someone broke xenobio, because a sec guy remember to patrol xenobio once in a blue moon etc

**Comment by Militaires** [comment]
1 cluster of eggs can spawn a shitton of spiders so them being weak doesn't matter they spawn in the actual hundreds

xenobio mains SEETHING about not being able to have an army the moment u get gold slimes n a few monkeys

**Comment by Arathianen** [comment]
> 1 cluster of eggs can spawn a shitton of spiders so them being weak doesn't matter they spawn in the actual hundreds
> 
> xenobio mains SEETHING about not being able to have an army the moment u get gold slimes n a few monkeys

Yeah, code changes should be based around making people mad. Top trolling bud. I am reeing over here. Le epic troller u r XD

A cluster is 5-6 spiderlings. To make a proper spidertide, I feed at least 30 or so monkeys to the broodmother. That would still be the case, with the only difference being that then I would get an eva suit and evacuate the fuck out if I wanted to live. 

Because again, your change REMOVES DIRECTIVES. That's all it does currently. You do this consciously and it's a bad change.

You wanna le epic troll le fail xenobio mains. I want spiders to be more fun for both the spiders, station and xenobiologist. So I think we are at an impasse here. I hope this change doesn't go through as it currently is.

Have a great day!

**Comment by Militaires** [comment]
wasn't even shooting for trolling xenobio mains, this just means you wont be just feeding a nurse spider monkeys (the pinnacle of difficulty) and getting an army, but instead will have to filter out nurses and matriarchs from each batch is gives.

image

**Comment by Arathianen** [comment]
> but instead will have to filter out nurses and matriarchs from each batch is gives.

Which is not possible because spiderlings crawl. Which I believe you know since we clarified that above. So you are just bsing me now.

Also you seem to be under the impression that xenobio spaws with like 10 matriarchs ready to go. I gotta inform you that this is not the case. Getting a matriarch/nurse actually takes a ton of work needing a t3 golden slime and a different path t4 pink slime and a lot of luck to get a green eyed spider over any other spawn of which there are dozens. Then you gotta feed them monkeys while protecting them from AI and security investigation.

All of which takes roughly 50m before the first batch spawns.

**Comment by Militaires** [comment]
getting gold slimes isnt hard at all man

**Comment by Arathianen** [comment]
> getting gold slimes isnt hard at all man

Gold slimes aren't the only thing needed for SENTIENT spider.

You need light pink for sentience potions. You also need to spend 10m spamming blood on gold slimes to actually get a nurse spiders and another 10m feeding them monkeys before the first batch.

Nothing is "hard" but if you add 10 "not hard" things together, then it becomes fairly challenging. Which it is. Why don't you see a spider apocalypse every round?

**Comment by Militaires** [comment]
yea you need a sentience potion but xenobio isn't hard it's the same routine every round that just takes time, you don't see people reaching shit like xenoling (probably removed) often since the shuttle lands 0.5 minutes into the round

**Comment by Arathianen** [comment]
> yea you need a sentience potion but xenobio isn't hard it's the same routine every round that just takes time, you don't see people reaching shit like xenoling (probably removed) often since the shuttle lands 0.5 minutes into the round

Yes, exactly. It takes time. I didn't say it needs a PHD in rocket science to get spiders. It needs time and a set-up and to be uninterrupted for 50m. Which is a lot to ask in a game where the station regularly explodes 30 minutes in. Which is what inherently balances spiders. 

Making spiders directiveless would make spiders _less fun_, it wouldn't nerf them. That is what I am trying to impress here. You aren't nerfing the spiders, you are nerfing their ability to be used as anything other than a directionless murderbone tide.

**Comment by Militaires** [comment]
yeah i think they should be time consuming to get and impossible to acquire on a normal round that is by design, ultimately this is up to maintainers whether they close or merge this pr but that's how i want it to be.

**Comment by Arathianen** [comment]
ah if you don't spend effort on removing egg layers

Which is, again, impossible. Even if you somehow have the first gen entirely inside the monster pit (in which you just spawned 100 random monsters to get your spider and is currently crowded as fuck) then 2nd gen will then spawn all over the station as spiders spread out to do your bidding. You are literally advocating an impossibility here.

>yeah i think they should be time consuming to get and impossible to acquire on a normal round that is by design

But you aren't changing their timing. You are just nerfing the ability to have them be directed. You aren't nerfing their power levels. You aren't nerfing the time needed to spawn them. You just (essentially) remove spider directives with this change.

I feel like we are talking past each other on this issue. Is your design meant to increase time to get spiders/nerf their power or simply remove their ability to be directed? Because, as it currently is, it only does the 2nd thing.

**Comment by Militaires** [comment]
>then 2nd gen will then spawn all over the station as spiders spread out to do your bidding

just kill em dude, get a nurse, clear the chamber, sentient the nurse, have it lay eggs and also direct it and its descendants to kill any other nurses or matriarchs that spawn, it's not hard

**Comment by Arathianen** [comment]
> > then 2nd gen will then spawn all over the station as spiders spread out to do your bidding
> 
> just kill em dude, get a nurse, clear the chamber, sentient the nurse, have it lay eggs and also direct it and its descendants to kill any other nurses or matriarchs that spawn, it's not hard

It's hard. It's literally impossibly hard. What you are describing is literally an impossible, will-never-happen, dreamland scenario. NONE of that will happen. Ever.

Our default current time is 50m. What you propose is

>clear the monster pit

+10m if you are lucky and get a spider with fewer spawns.

>have the nurse lay a few eggs to hatch, wait for them to hatch, be lucky and get a matriarch

+10m

>instantly sentience the new matriarch before a player jumps on it

>set a directive to kill ALL other matriarchs

I won't even comment on this because lol. We must be playing 2 different games. It's currently hard to make spiders not kill people with explicit no murderbone directives. Plus, the average player has no fucking clue how a matriarch looks like.

>go around in the middle of a spider apocalypse attacking spiders

None of that is feasible. None of that is reasonable. None of that will EVER happen. This change removes directives for spiders. The end. It does nothing else.

**Comment by Militaires** [comment]
ok then if you think it takes too long what if i make the matriarchs directly goldspawnable?

**Comment by Arathianen** [comment]
> ok then if you think it takes too long what if i make the matriarchs directly goldspawnable?

I believe the appropriate thing to do is make them goldspawnable (instead of normal nurses, not both else most people will be confused)

Then remove the ability for other matriarchs to become independent UNLESS the original matriarch dies. That way spiders are still possibly unstable/unreliable while also removing the need to hunt down other matriarchs, because seriously.

I am not sure if what I am proposing above is codable. I have never coded in my life.

-----

One thing I mentioned in discord and I will mention again is maybe adding a level above matriarch. Maybe as a special ability for sentienced spiders if they eat like 10 monkeys to be able to "level up" similar to alien queen. But maybe that is too similar to aliens as they currently are.

**Comment by Militaires** [comment]
i'll make them goldspawnable but i disagree with making other matriarchs subordinate, it doesn't make sense and i actually want there to be infighting between different strains of spiders, that's the point of this PR.

maybe in the future i can give spiders color indicators for which strain they belong to

**Comment by Arathianen** [comment]
I still believe this is the wrong thing to do, but thank you at least for adding the gold slime change. That one's really important.

**Comment by Militaires** [comment]
if this pr is even merged and you still think that's wrong then you can open your own pr i guess

**Comment by Arathianen** [comment]
> if this pr is even merged and you still think that's wrong then you can open your own pr i guess

I don't know how to code. That would be bad for everyone involved.

**Comment by Militaires** [comment]
dont worry it's piss easy i think you'll have to erase part of a line

**Comment by XDTM** [comment]
In my opinion all spider spawns should retain the original objective, but matriarchs and maybe also nurses should be able to add further directives on top of it for their own spawns (making it possible to have spider squads dedicated to different goals). The objective system would work nicely for that.

Resetting the law as you're currently proposing will turn spiders back into a fire-and-run-away murderbone tool, removing any nuance to their use.

**Comment by Militaires** [comment]
if i do this then what's even the difference between matriarchs and nurses? i feel like there isnt much distinction aside from the global spider thing, what do you suggest?

**Comment by XDTM** [comment]
I mean, being able to coordinate with all descendants, which normally have no radio and are usually spread out through the whole station, is a pretty good ability on its own.
If you want to add something new, you could perhaps give them a way to see what other spiders see, to reinforce their commander role.

**Comment by Arathianen** [comment]
> edit: i also think every single "special" spider doesnt have much of a difference too but i think midwives-nurses are the worst case

Add a heal ability to matriarchs. Make them the support role. Spiders currently have no way to heal.

**Comment by XDTM** [comment]
Spiders should probably eat bodies to heal in general, it shouldn't be relegated to a specific role i think

**Comment by habader** [comment]
Im so confused

**Comment by Militaires** [comment]
up until a few weeks ago all nurses only had command of 1 gen, then it was powercreeped so that you only need 1 nurse to make an instant and 100% loyal army, this pr makes that harder to achieve while also letting it be possible.

i've already made matriarchs gold core spawnable, now all you'd need is sentient the matriarch and have it direct its descendants to be loyal to you, and to manage each batch of spiders it produces in the xenobio mob pit, to remove nurses and matriarch.

some people are complaining, "oh no but some of your spiders might go rogue, risk or difficulty = bad", like yeah, obviously, you should spend effort to grow your army not just rng roll 1 nurse and then split a pink.

**Comment by XDTM** [comment]
Only one gen? The original intention was to have hereditary directives, if it wasn't that way it was due to a bug

**Comment by Militaires** [comment]
yea im p sure when directives were first added it was a 1st gen dealio

**Comment by Militaires** [comment]
ah fuck it ill close this pr whatever

**Comment by Militaires** [comment]
psyke actually ill leave this up for the maintainers to decide

**Comment by XDTM** [comment]
I mean, i made the original PR, the intention was always to have 100% control over the spider's descendants. It wasn't mechanically enforced for nurse descendants which could override it (since i thought that obeying the directive also meant not giving a contrasting directive), but in retrospect i should have made directives stack like i suggested earlier.

**Comment by OverlyGeneric** [comment]
image

**Comment by 4dplanner** [comment]
I think IF this route is taken, spiders would need something like a HUD so they could detect whether other spiders were following the same directive as them. This would make the "kill all rebels" plan possible and maybe even fun.

If you don't have this, it'll just be impossible. One matriarch definitely will spawn, given ventcrawling. You can't just keep spiders in containment forever or they can't do anything. This then means that your spiders won't be able to tell which spiders they're meant to be killing. As it stands, I don't think it's fair to say that a culling-based approach would be viable.

**Comment by Militaires** [comment]
well obviously if you free your sentient matriarch and have it lay eggs all over the station instead of just in the containment chamber you're gonna get fucked

**Comment by XDTM** [comment]
Having to keep all spiders in containment and painstakingly checking them on every egg laying is not fun for neither the scientist, who'd rather be leading his army, nor the spiders, who have to stay in an isolated room for god knows how much. 
Spider civil war has its own problems, since it's almost guaranteed to happen and will rapidly break most organized efforts involving spiders, going back to "uncontrolled murder army, release and run away" instead.

If you leave them hereditary we might actually see rounds with more creative spider use; potentially station-aligned as well, making them more than just a mass murderbone tool.

**Comment by Militaires** [comment]
if you're that afraid of not having completely loyal spiders the moment you sentient 1 nurse how about i make matriarchs rarer to come from eggs so that the chances of you having a splinter faction is smaller

**Comment by Militaires** [comment]
i've decided to lower the chance of a matriarch spawning from eggs from 3% to 1%.

**Comment by Arathianen** [comment]
> i've decided to lower (disregard commit name) the chance of a matriarch spawning from eggs from 3% to 1%.

Isn't the current spawn rate about 3% already though? Why nerf it?

**Comment by Militaires** [comment]
>someone complains about spider armies being too hard to maintain

>lower chance for matriarch to spawn from eggs so splinter groups are rarer

>complain about matriarch egg spawn rate instead

by the way, the spawn rate from gold slime is unrelated to the egg spawn rate

**Comment by Arathianen** [comment]
I completely misread the change. My bad.

**Comment by ExcessiveUseOfCobblestone** [comment]
While I like making it clear to the player what their goals are, there's no point if we have admins that are going to ban you for making spiders regardless tbh.

**Comment by optimumtact** [comment]
@ExcessiveUseOfCobblestone what are you talking about

**Comment by ExcessiveUseOfCobblestone** [comment]
See policy discussion "Spiders as nonantag".

Admins will ban you for making spider-armies if nonantag regardless if you tell them to not do anything evil (source: an admin said they would in the thread).

**Comment by FantasticFwoosh** [comment]
Such a shame to see people can't have a intelligent and constructive conversation on one of our little known playable side-antagonists/mobs. I think this proposed system is ok, but players might be prone to ignoring what was presented to them simply by means of misunderstanding the importance of x matriarch for "who said what" when messages start contradicting each other.
> In this day and age there are people who still don't understand the messages when they spawn into a ghost role in the largest capital block letters that it is important information for them. They are just eager to play

**Comment by ExcessiveUseOfCobblestone** [comment]
And THEY should be banned for it rather than the scientist, although this is a bleeding policy discussion.

**Comment by optimumtact** [comment]
realistically then we should remove spiders from the xenobio spawn

**Comment by XDTM** [comment]
Xenobio gold spawn should probably be removed in general, spawning random mobs out of a slime is kind of senseless and i'd rather have a separate system of collecting, studying and replicating existing mobs (from mining, botany, or random events), where you would have to encounter them before being able to make more, which would be closer to the ideal of a xenobiology department, which is currently more of a slimeology department.

**Comment by Arathianen** [comment]
Oranges, removing spiders from xenobiology spawn would remove something fun for a lot of people though. Just because we have some rule discussion about it doesn't mean it requires a coding nuke.

**Comment by XDTM** [comment]
Tbh xenobio is already absolutely packed with content compared to other departments, transferring the whole spider thing somewhere else wouldn't be much of a loss.

**Comment by Arathianen** [comment]
Well, who would be making monsters besides xenobiology?

Is someone willing to go make a new sci department?

**Comment by ExcessiveUseOfCobblestone** [comment]
> Oranges, removing spiders from xenobiology spawn would remove something fun for a lot of people though. Just because we have some rule discussion about it doesn't mean it requires a coding nuke.

It becomes a code issue when admins punish for something regardless of intent/circumstance. It may be fun does not negate the fact that people can get banned for it even if they don't have malicious intentions.

**Comment by Arathianen** [comment]
> > Oranges, removing spiders from xenobiology spawn would remove something fun for a lot of people though. Just because we have some rule discussion about it doesn't mean it requires a coding nuke.
> 
> It becomes a code issue when admins punish for something regardless of intent/circumstance. It may be fun does not negate the fact that people can get banned for it even if they don't have malicious intentions.

The problem with spiders (to re-iterate) is that their directives are written in small letters in plain text, shown only when they spawn and not kept in the mind.

If you got a big "traitor text" and you could check on them, spiders could be reasonably controlled, admins could reasonably hold them accountable etc

When there is an obvious fix waiting to happen, nuking them is not necessary.

**Comment by ExcessiveUseOfCobblestone** [comment]
This wasn't the feedback I got from the thread from the admin(s) that said they would ban for making spiders, where are you getting this from?

The feedback I got which you can read at your leisure word for word on the "Spiders as nonantag" policy thread is that spawning them is inherently antagonistic because they can make an army and spiders do nothing but grief. Making the current flavor text bigger or replacing OOC enforce flavortext with OOC enforced objectives does not fix this.

**To be clear, I think it's a silly train of thought and I agree with you that it should be an option**. I don't have the power to overrule other admin's decisions however in either my position as a maintainer or admin. The hyperspecific "I have a spider army" situation this creates <<<<< players ending up getting banned even when they do everything they're suppose to.

**Comment by Arathianen** [comment]
Aha. I understand what you mean now.

I don't think it is a common admin policy as of now, and it depends heavily on context.

As a reference though, I personally won't make spiders as non antag until the text and memory is fixed, regardless of directives.

Would an admin outright ban someone who made spiders with positive directives though right now? Probably not, it's not an established thing that happens.

**Comment by ExcessiveUseOfCobblestone** [comment]
I certainly wouldn't hehe

**Comment by ExcessiveUseOfCobblestone** [comment]
Spoke with at least 1 headmin regarding the admin pains of spiders and I think it should be changed so that if a mommy spawns a mommy the second mommy is just not able to touch their directive-objective. That way the instance of a nonantag scientist who spawns a mommy spider who makes an army and an issue arises goes to 3 endings:

1. The spider who is being naughty not following obj
2. The mommy who didn't set a directive-objective in line with what the scientist wanted
3. The scientist who okayed the spider to be naughty

**Comment by Militaires** [comment]
that's what we have already you dingus

**Comment by ExcessiveUseOfCobblestone** [comment]
Splinter groups are what makes the admin nightmare.

**Comment by XDTM** [comment]
I'd suggest to make splinter groups not possible by random chance, but possible with outside intervention in some way, maybe by sabotaging unguarded eggs.

**Comment by Militaires** [comment]
@ExcessiveUseOfCobblestone i've already made it easy for admins to tell the difference though, just look at the progenitor var to know which or look in the objectives like you would with any traitor, previously you had to look in its logs and shit which is trash

**Comment by Militaires** [comment]
and on top of that i've made splinter groups rare so there will only be like at most 3 (of varying size) during an infestation round

**Comment by optimumtact** [comment]
That wasn't a request, it was a command

**Comment by Militaires** [comment]
here's a command: suck my dick and balls BITCH :sunglasses:

**Comment by Militaires** [comment]
image

**Pull request closed without merging**
