### PR TITLE
Fixes become_husk's update_body placement

### LINKED ISSUE #45647: Husking doesn't always update body to be grey
Burn damage husking successfully applies the visual, but changeling husking or using human/become_husk() does not work.

Running update_body() on the husked person makes the visual correctly 
appear

### PR DESCRIPTION
**Pull request by RandolfTheMeh**
## About The Pull Request

So the original become_husk called update_body only when the body became a husk, and it did so before it assigned the husk trait to the body. Whoops! Fixes #45647 

## Why It's Good For The Game

People won't spend half an hour on a corpse that's actually just an overcooked sausage

## Changelog
:cl:
fix: Husking now properly makes the body look like a husk
/:cl:

### CODE REVIEW

**Comment by py01** [comment]
#45648 also exists, not sure which is better solution

**Comment by PKPenguin321** [comment]
Have you tested this to confirm that it works?

**Comment by RandolfTheMeh** [comment]
> 
> 
> Have you tested this to confirm that it works?

Yeah

**Comment by RandolfTheMeh** [comment]
> 
> 
> #45648 also exists, not sure which is better solution

Didn't notice that one, but it really shouldn't run update_body() twice. Running it unconditionally is one thing, but the only problem with the previous implementation was, as stated, the HUSK trait wasn't added until after update_body() was run, and so wasn't given the husk visualization.

This implementation keeps the amount of times update_body() is called to a minimum, but despite that I apologize for not having noticed that PR!

**Pull request closed without merging**
