### PR TITLE
You can buckle yourself or somebody else into a chair, if you're next to the chair.

### PR DESCRIPTION
**Pull request by uomo91**
## About The Pull Request

You can now buckle yourself, as well as others, into a chair as long as you (and the other person, if you're not buckling yourself) are Adjacent to said chair, and being on the same tile as the chair is no longer required.

## Why It's Good For The Game

No more god-awful pixelhunt to accomplish a very simple task.

## Changelog
:cl:
tweak: You can buckle yourself and others into chairs that you're right next to, instead of needing to be on top of the chair to do it.
/:cl:

### CODE REVIEW

**Comment by optimumtact** [comment]
this buffs combat buckling

**Comment by Couls** [comment]
this buffs combat buckling

**Comment by SkeletalElite** [comment]
make it require being grabbed or cuffed

**Comment by uomo91** [comment]
I put a visible warning and a do_after delay for buckling.

Also while testing this PR I discovered two fun bugs I didn't cause.

https://github.com/tgstation/tgstation/issues/53257
https://github.com/tgstation/tgstation/issues/53256

**Comment by LemonInTheDark** [comment]
this buffs tactical sitting

**Comment by ATH1909** [comment]
> I put a visible warning and a do_after delay for buckling others.
> 
> Also while testing this PR I discovered two fun bugs I didn't cause.
> 
> #53257
> #53256

Yeah, I had made plans for using the second one to actually manage to kill someone as an armless, legless, headless changeling, but I still haven't gotten around to executing them yet.

**Comment by wesoda25** [comment]
What sort of absurd world do I live in where a PR that kills tactical buckling excites me?

**Comment by Angustmeta** [comment]
3 seconds to buckle someone is a massively long delay

**Comment by Dennok** [comment]
I think about this, and someone code this. Great!

**Comment by Iatots** [comment]
I just drag my sprite onto the thing i want to buckle to from an adjacent tile, and release the mouse 1 millisecond after I start moving towards it.

**Pull request merged**
