### PR TITLE
[NO GBP] Music Request Credits changed to CKEY

### PR DESCRIPTION
**Pull request by SomeRandomOwl**
## About The Pull Request

I was requested by one of the game admins over in the TG discord to change the credit from character name to ckey.

## Why It's Good For The Game

It's mostly a OOC thing, personally I don't know of a good enough reason to put here other than its a PR someone requested of me.

## Changelog

:cl:
fix: Music Request Credit shows CKEY instead of character name
/:cl:

### CODE REVIEW

**Comment by BlueMemesauce** [comment]
People were trying to tell you why to use ckeys in the last PR, but I'll try to explain the reasons to you again. 
While it may work for crew with static names that people know them by, people with random names or animal names like "monkey (123)" won't be able to credit themselves.
The reason about OOC you said the admins told you is that it's mixing IC and OOC, which should be separate. It doesn't make sense for your characters name to show up like he requested it IC, since the music only exists OOC.

**Comment by SomeRandomOwl** [comment]
I know, i just have seen a few people who get upset from their CKEY being displayed to others and just eh i dunno, i was trying to appease both sides since i really personally dont care either way

**Comment by ZephyrTFA** [comment]
This never should have been mob name and always ckey regardless.
I understand that certain downstreams want to have your ckey and who you are be not linked, but requesting music is literally an OOC thing.

**Comment by TheVekter** [comment]
I was the one who originally requested this and did so because I played a song where the person wanted to request it and it said "Wraith (539) requested..." which had the lovely effect of telling literally everyone there was a cult.

Thankfully, the cult was already exceedingly loud at this point, but this PR fixes the issue wholesale. Thank you for doing this.

**Pull request merged**
