### PR TITLE
Borgs buckle instantly

### PR DESCRIPTION
**Pull request by alien3301**
## About The Pull Request

Whenever a borg buckles anyone to anything it will be instant

## Why It's Good For The Game

This is an interesting borg-only strengh that also makes it so that they can always do at least something to you.
Currently if someone has flash protection and is a human they are invincible to borgs and because of mood run faster then them.
It's not cool that you can garantee a win against a borg with two items.
Their throw no longer stuns so it's not very useful outside of the situation where you can't use anything else.
Even with this they still have plenty of counters that arent affected by this PR (flashbangs, ion guns and grenades, lockdown, etc).

## Changelog
:cl:
balance: Cyborgs now always buckle instantly
/:cl:

### CODE REVIEW

**Comment by alien3301** [comment]
It lets you disarm and get away from a flash protected human. Right now you have no way to do it which sucks. Also you can still instantly buckle someone if they're on the same tile as whatever you're buckling them to so the "We made only self buckling instant" is just not true.

**Comment by Jacquerel** [comment]
Why would specifically cyborgs, who generally speaking have no arms or hands, be better at buckling people to far-away objects than humans? If you want to add more benefits to cyborgs I think they should be thematic in some way, this seems completely random.

**Comment by alien3301** [comment]
But they do have arms. Their tools have to be able to move freely for complex tasks like surgery. They just don't have hands. This isn't random because borgs used to be able to instantly buckle people to themselves but it was nerfed because the spin throw stunned back then. I decided to make them instantly buckle to everything because that's not that big of a deal.

**Comment by alien3301** [comment]
If anyone has a better idea for buffing borgs to be able to deal with flash protected humans then I would love to hear it but to me it seems like this is the best way.

**Comment by Metekillot** [comment]
Borgs have immunity to damage slowdown until they are completely destroyed or stunned, and when emagged they get other stun tools. Non-emagged borgs are supposed to be quite stifled in their direct actions against humans. They have absolute control of the environment against humans alongside their tools.

**Comment by zxaber** [comment]
Everyone gets hung up on this being a combat thing. Back when we lost insta-buckling, the biggest casualty was being able to quick-extract a human from plasma fires and other stage hazards.

**Comment by Sadboysuss** [comment]
> Everyone gets hung up on this being a combat thing. Back when we lost insta-buckling, the biggest casualty was being able to quick-extract a human from plasma fires and other stage hazards.

what about throwing bodies at people

**Comment by zxaber** [comment]
>what about throwing bodies at people, that's combat

That it *can* be used for combat doesn't mean it necessarily would. This is true for basically any borg balance change; 90% of the time the borgs are crew (or at least human) aligned and are trying to keep you alive.

Anyway, I had proposed an alternative to the original buckle delay PR where humans had to be buckled for a number of seconds before they could be tossed. It seemed to me to be the best middle-ground of allowing borgs to rescue a human but preventing a very specific combat mechanic they could once do. 

--

>I'm quite happy for cyborgs to be able to quickly buckle people to themselves again, but not to random other objects

Fair, I don't know what's up with that.

**Comment by Dawnseer** [comment]
Is this a return towards that one pr that wanted to make cyborgs do combat via grabbling moves?

**Comment by MrMelbert** [comment]
Not particularly interested, being randomly instantly bucked to something sounds unfun, and cyborgs already have existing strengths unique to them

**Comment by alien3301** [comment]
> what about throwing bodies at people, that's combat

That's not a thing. The borg throw just treats another human like an obstacle and the body does nothing to them.

When this is used for combat this is pretty much entirely useless except for one situation: You're an asimov borg and you want to run away from someone with sunglasses. In EVERY other situation you already have much better things to use. I just want to make killing asimov borgs harder even if you are human.

> Not particularly interested, being randomly instantly bucked to someone sounds unfun, and cyborgs already have existing strengths unique to them

If they're buckling you for no reason you can just law 2 them to not do it. I don't see why it would be an issue in the first place because you can just press whatever button resist is bound to for you and instantly unbuckle.
Borgs do have strengths but in the situation this pr affects none of them matter.
Not getting slowed down by damage is cool but you become blind and confused (pretty much a slowdown) on the first hit and virtually die on the second. Having a flash is cool but they have flash protection. Not having to manage mood is cool except it's not hard and in the end just gives them a free speedboost. Having AA is very cool except they get AA too since they're 3 tiles behind.

This PR really just makes asimov borgs not die for sure if a human has glasses and makes it easier to rescue someone but I'm sure everyone would appreciate that. I can make it be instant only when buckling to yourself if that's what everyone wants.

**Comment by LemonInTheDark** [comment]
I like borgs being hard-countered actually I think it's soul

**Comment by MrMelbert** [comment]
> If they're buckling you for no reason you can just law 2 them to not do it. 

What if they're not asimov

> Not getting slowed down by damage is cool but you become blind and confused (pretty much a slowdown) on the first hit and virtually die on the second. 

A mediborg needs a single injection to incapacitate someone

**Comment by alien3301** [comment]
> I like borgs being hard-countered actually I think it's soul, you have not sufficiently elaborated on why it is a problem.

They still are. If you got a flash, sunglasses and are a human you have a HUGE advantage. You're likely to win with how easy they are to stun and you can't lose because they are asimov. It's just that you don't get a guaranteed win, now it's a garanteed tie. You can still lock the borg if you really suck at the game.

**Comment by alien3301** [comment]
> > If they're buckling you for no reason you can just law 2 them to not do it.
> 
> What if they're not asimov

Then they just use the strongest thing their model gets to just kill you and this PR does nothing for them.
> 
> > Not getting slowed down by damage is cool but you become blind and confused (pretty much a slowdown) on the first hit and virtually die on the second.
> 
> A mediborg needs a single injection to incapacitate someone

First: Literally not true. It takes about 7 units so two stabs. Also they need the expanded hypo upgrade.
Second: It takes 80 FUCKING SECONDS. That's ages for you to hit them twice and kill them before the halo gets you. Also with changes to halo and stam crit it doesn't even keep you in stam crit if the borg keeps injecting you. Also it does brain damage so it's a no no.

**Comment by alien3301** [comment]
Borgs getting hard countered like that is bad because it's not fun to fight when you're not just at disadvantage but literally unable to retaliate or even escape. This is pretty much the same as borgs not being asimov, having flash, flashbang, emp and regular damage immunity as well as flashes that ignore flash protection and a 10% speedboost. That's how it is to have a human with a flash and sunglasses fight you.

**Comment by chemistrymain3** [comment]
> > If they're buckling you for no reason you can just law 2 them to not do it.
> 
> What if they're not asimov
> 
> > Not getting slowed down by damage is cool but you become blind and confused (pretty much a slowdown) on the first hit and virtually die on the second.
> 
> A mediborg needs a single injection to incapacitate someone

it's kind of a rocket tag situation

you melee them and they melee you and you both walk away from that dead- they haloperidol'd you and you got obliterated with a flash

**Comment by alien3301** [comment]
> > > If they're buckling you for no reason you can just law 2 them to not do it.
> > 
> > 
> > What if they're not asimov
> > > Not getting slowed down by damage is cool but you become blind and confused (pretty much a slowdown) on the first hit and virtually die on the second.
> > 
> > 
> > A mediborg needs a single injection to incapacitate someone
> 
> it's kind of a rocket tag situation
> 
> you melee them and they melee you and you both walk away from that dead- they haloperidol'd you and you got obliterated with a flash

Not really. Say it took them about 30 seconds after your first stab to get you so now they have 50. They beat you to death with literally anything and spent 20 seconds at most on it. Fall on the ground for 5-10 seconds and then get up like nothing happened. Also halo is human harm because of brain damage.

**Comment by nikothedude** [comment]
> > what about throwing bodies at people, that's combat
> 
> That it _can_ be used for combat doesn't mean it necessarily would. This is true for basically any borg balance change; 90% of the time the borgs are crew (or at least human) aligned and are trying to keep you alive.

its not like it doesnt happen, i mean i for one have bodythrowing as a large aspect of my borg combat, its basically the same as a human-performed bodythrow and it can be really strong

**Comment by optimumtact** [comment]
this is a weird kind of bait.

**Pull request closed without merging**
