### PR TITLE
Adds a clown shooting target.

### PR DESCRIPTION
**Pull request by harmonyn**
HONK

clown

(first draft sprite left, actual sprite right)

Finally, security and others can be prepared to handle the most common threat to the station.

Also adds these to the map.

### CODE REVIEW

**Comment by Thunder12345** [comment]
Description fail

**Comment by Core0verload** [comment]
Can it throw a banana peel, steal shooter's ID, use it to open armory and Yakety Sax away? 

Anyway, :+1:

**Comment by daman997** [comment]
do it

**Comment by GunHog** [comment]
Add a honk sound to its bullet act. It should honk and squeak when you shoot at it!

**Comment by bgobandit** [comment]
HOLY SHIT DONE

also made the sprite suck less, before and after in OP

**Comment by ike709** [comment]
HONK :+1:

**Comment by CosmicScientist** [comment]
:+1: Will put to use in the darkest corners of maint to make people think the Clown is a serial killer.

**Pull request merged**
