### PR TITLE
add dwarf race

### PR DESCRIPTION
**Pull request by ghost**
adds a playable dwarf race that can be customized in game settings like any other playable race

### CODE REVIEW

**Comment by kevinz000** [comment]
uh sir

**Comment by optimumtact** [comment]
this pr is not sensible, learn to seperate out commits and do it properly

**Comment by ShizCalev** [comment]
Wrong repo?

**Comment by fluxcapacitor1337** [comment]
this my first time doing this here github thingy please close and delete this thanks

**Pull request closed without merging**
