### PR TITLE
Wood Datum Materials now have a wood grain texture.

### LINKED ISSUE #54917: Datum material wood floor tiles lack wood texture
## Round ID:
#150093

## Testmerges:
#54702 #54483 #54379

## Reproduction:

1. Unintentionally make datum material wood floor tiles instead of regular wood floor tiles in sheet construction menu for wood planks
2. Observe the different object sprite and turf sprite for them (plain brown)

### PR DESCRIPTION
**Pull request by ArcaneMusic**
## About The Pull Request
image
Woodgrain now has a basic texture to break up just being a brown blob. 

Image showcases datum material objects, against several untextured hardcoded "wooden" objects.
## Why It's Good For The Game

Fixes #54917, provides visual clarity to things made from the wood datum material, as well as prevents stock wooden "floor" tile from appearing like brown metal tiles when crafted as opposed to when you wanted to use the hard-textured floor as seen on the right of the image.

## Changelog
:cl:
imageadd: Basic wooden texture is visible to wood, material crafted objects.
/:cl:

### CODE REVIEW

**Review by ghost — APPROVED** [review]

**Comment by Fikou** [comment]
nice feature pr

**Comment by nightred** [comment]
It is likely not be simple but if the wood grain rotates with the object it would make the E/W chair look better.

**Comment by cacogen** [comment]
This should look like old wood, including the unique sprites for chairs and tables

**Comment by ArcaneMusic** [comment]
> It is likely not be simple but if the wood grain rotates with the object it would make the E/W chair look better.

Well, this would be easy enough with just a mutable_appearance overlay, but the main issue is that material textures all use filters, which can't be made respective to a direction or translated to a 90 degree angle.

**Pull request merged**
