### PR TITLE
SimpleMed: Built from the Ground Up for /tg/station

### PR DESCRIPTION
**Pull request by TheAssistant**
This is a medical system to combat goofball's retarded autistmed shit. It's built from the ground up with /tg/station player concerns in mind. 

:cl:
rscadd: Medical has been redesigned from the ground up for a /tg/station audience.
/:cl:

### CODE REVIEW

**Comment by KorPhaeron** [comment]
>can see commits from goofs account

**Comment by Iamgoofball** [comment]
thats not my account?

**Comment by Man-Shroom-** [comment]
>TheAssistant  wants to merge 1 commit into tgstation:master from Iamgoofball:simple

**Comment by Iamgoofball** [comment]
oh github's reporting some IP in europe was inn my account

fucking britbongs

**Comment by Man-Shroom-** [comment]
goof you goddamn MEME

**Comment by Shapsy** [comment]
FALSE FLAG MEMES

**Pull request closed without merging**
