### PR TITLE
Changes the Disintegrate spell's name to "Smite"

### PR DESCRIPTION
**Pull request by ATH1909**
## About The Pull Request

This PR has been made as an alternative to another one of my PRs: https://github.com/tgstation/tgstation/pull/45782

It simply changes the name of the "Disintegrate" spell (and some references to it) to "Smite" (and slightly edits the description of the Disintegrate spell).

## Why It's Good For The Game

The new name more accurately reflects what the spell does.

## Changelog
:cl: ATHATH
tweak: Changed the name of the "Disintegrate" spell (and some references to it) to "Smite" (and slightly edits the description of the Disintegrate spell).
/:cl:

On a side note, are we supposed to capitalize spell names in our changelogs/normal use of them, or are we suppose to leave them uncapitalized? In other words, are spell names proper nouns?

### CODE REVIEW

**Comment by ishitbyabullet** [comment]
Does the semantics here really matter? Disintegrate sounds more wizardy than _**gib**_ anyways. Gib just sounds like i'm speaking like a moron on the internet.

**Comment by ATH1909** [comment]
> Does the semantics here really matter? Disintegrate sounds more wizardy than _**gib**_ anyways. Gib just sounds like i'm speaking like a moron on the internet.

Do you have a better name that I could use?

**Comment by ishitbyabullet** [comment]
What if we just call it Ei Nath? That's the most basic idea.

Besides that, we could just make it turn you into dust or something instead. Disintegrate is a DnD spell. This is /tg/station. /tg/ likes tabletop roleplaying. DnD is a tabletop roleplaying game. https://www.dndbeyond.com/spells/disintegrate

However if we REALLY have to change it then call it smite? Still a /tg/ reference since smite is the basic spell that all psykers have in w40k.

**Comment by ATH1909** [comment]
> Besides that, we could just make it turn you into dust or something instead. Disintegrate is a DnD spell. This is /tg/station. /tg/ likes tabletop roleplaying. DnD is a tabletop roleplaying game. https://www.dndbeyond.com/spells/disintegrate

> This PR has been made as an alternative to another one of my PRs: #45782

https://ih1.redbubble.net/image.338340721.3909/mp,840x830,matte,f8f8f8,t-pad,750x1000,f8f8f8.jpg

**Comment by ishitbyabullet** [comment]
I was more worried about the name change when i saw it adverted during a round of /tg/station instead of reading for the blue number text. My bad.

**Comment by ishitbyabullet** [comment]
oh yeah also the other PR has a good name suggestion too.
> i get it but maybe you should make it called explode or implode or something because it's much better gameplay for this to gib than to dust and gibbing is way more fun

it's kinda dumb to me however explode does sound better than gib as a magical spell name.

**Comment by ATH1909** [comment]
> oh yeah also the other PR has a good name suggestion too.
> 
> > i get it but maybe you should make it called explode or implode or something because it's much better gameplay for this to gib than to dust and gibbing is way more fun
> 
> it's kinda dumb to me however explode does sound better than gib as a magical spell name.

Explode (or Explosion) implies something like Fireball, IMO. Implosion, on the other hand, implies that the victim's body should be compacted in some way, not detonated and spread all over the place/outwards.

**Comment by ishitbyabullet** [comment]
What about Butcher? I still don't like it however it gets the job done imo.

**Comment by ATH1909** [comment]
> What about Butcher? I still don't like it however it gets the job done imo.
> 
> **But yeah I think smite may be a good name. Admins CAN gib you with smites afterall.**

Alright, done.

**Pull request merged**
