### PR TITLE
Removes force from slappers

### LINKED ISSUE #31786: Slappers can break windows
They can also be used to break stuff you normally couldn't barehanded (windows for example)

0/10

### LINKED ISSUE #32138: Slappers Breaking windows.
Issue reported from Round ID: 77982 (Sybil)

So I decided to mess with slapper and found they can break windows on harm intent, not sure how this can be fixed in the code but just reporting it, it could allow inmates to break out of perma or something with nothing else on them but their arms.

### PR DESCRIPTION
**Pull request by Cyberboss**
Fixes #31786

### CODE REVIEW

**Comment by WJohn** [comment]
why do we even have slappers they seem like infinitely more trouble than they're worth

**Comment by deathride58** [comment]
Hugbox, no fun allowed, slippery slope, etc etc etc

It should be plausible to just apply the 1 damage directly if the target is a human mob instead of removing the scratch damage force entirely. It'd keep the emergent gameplay of a clown being able to robust a squad of nukies with nothing but a slapper and soap, while ensuring people can't meme out of their brig cells with the force of a slap.

**Comment by Ratvar** [comment]
Slappers are slippery slopes on their own

**Comment by Supermichael777** [comment]
just give glass a force threshold. I could swear it already had one.

**Comment by PKPenguin321** [comment]
Actually this fix might break their hitsound but I'm not sure, check how clown horns do it

**Comment by Cyberboss** [comment]
Nah their hitsound is hard coded

**Comment by deathride58** [comment]
Harmslaps just call the original attack proc, meaning they use the sound defined in the item instead of the sound hardcoded in the proc.

**Comment by SyruseEln** [comment]
Fun removal.

**Comment by optimumtact** [comment]
bye bye fun

**Pull request merged**
