### PR TITLE
Weakrefs

### PR DESCRIPTION
**Pull request by silicons**
Adds weak references and makes camera tracking use them.

### CODE REVIEW

**Comment by Iamgoofball** [comment]
what is the point

**Comment by kevinz000** [comment]
I'll fix it later.

**Comment by kevinz000** [comment]
@Iamgoofball see integrated electronics PR and to avoid having to use textrefs.

**Comment by Iamgoofball** [comment]
ah

**Comment by Iamgoofball** [comment]
:-1: >space-tabbing

**Comment by kevinz000** [comment]
fucking hell somehow a pr on a surface 3 turned out worse than prs with webeditor on a phone
what the fucking fuckity fuck is this.

**Comment by arsserpentarium** [comment]
I hope, it wouldn't be pain in ass to merge this in 2 separate PR's

**Pull request merged**
