### PR TITLE
Stop singularities from consuming themselves

### PR DESCRIPTION
**Pull request by Mothblocks**
## About The Pull Request
Singularities seem to be consuming themselves. My evidence for this is the fact that in a video I saw of it happening there was an explosion, and SM explosions are skipped, while the singularity explodes in `singularity_act`. Additionally, `singularity_act` is the one place where deletion wasn't logged (this has been addended).

~~However, I  have no idea *why*. None of the `consume` calls should be doing this. Thus, I added a `stack_trace` to help us isolate it.~~

Okay, we know why now. `COMSIG_ATOM_ENTERED` is being called on the singularity itself, making it consume itself.

## Changelog
:cl:
fix: Singularities can no longer consume themselves.
/:cl:

### CODE REVIEW

**Comment by Mothblocks** [comment]
May have found the cause, actually, stand by.

**Comment by Mothblocks** [comment]
This is gonna spam runtimes until the crossed signals themselves are fixed, but it is a *real* bug (with something unrelated to singularities), so I don't think it's a good idea to hide it because of that.

**Comment by Sparkezel** [comment]
https://youtu.be/533dR0thEmQ?t=270
the video in question

**Comment by Mothblocks** [comment]
This bug was fixed by one of the connect_loc PRs, but this is still useful as it contains a `CRASH` for when it happens if this bug comes back again.

**Comment by LemonInTheDark** [comment]
sure why not

**Pull request merged**
