### PR TITLE
Adds a Crew Control console, places it in the CMO's office

### PR DESCRIPTION
**Pull request by zxaber**
## About The Pull Request
Places a console in the CMO's office that allows for remote lockdown or detonation (gibbing) of all crew members on the same Z level. User must have CMO access. Detonating a crew member will leave their brain behind.

## Why It's Good For The Game
Gives extra options for security to handle traitors or changelings. Grants some traitor use in itself.

April 1st shenanigans.

## Changelog
:cl:
add: The CMO now has the ability to remotely lock down or detonate crew members via a new console in their office.
/:cl:

image

The changelog file had a stroke, gonna fix that.
Also, if I get around to it, I'll make hypno'd crew members not drop a brain.

### CODE REVIEW

**Comment by trollbreeder** [comment]
CAPTAIN ROGUE, BLOW THE ASSISTANTS!

**Comment by DinkleNH** [comment]
Based

**Comment by wesoda25** [comment]
Based

**Comment by Mickyan** [comment]
should have left this for badminnery

**Pull request closed without merging**
