### PR TITLE
Buffs blob [READY]

### PR DESCRIPTION
**Pull request by 4dplanner**
:cl:
balance: blobs now receive a 50% cost refund on attacks that don't spread
balance: blobs receive a free chemical re-roll every 4 minutes
balance: reflector blobs are considerably tougher
fix: attempting to turn a damaged strong blob into a reflector blob now refunds points
fix: fixed an intregrity
/:cl:

I think Blob is a great midround antag. It provides a threat that forces the station to work together as a whole, adds excellent drama, and has a cool design. However, it's currently very weak. I think it needs both a buff of the core antag, and then some buffs/nerfs to bring all the different variants into line. This PR deals only with the former.

One thing blob is currently lacking in is kill power. To actually attack someone, or smash through a wall, takes a crippling amount of chemicals (usually 16-20). This means that if the blob fights back through spreading instead of factories it cripples itself. I believe attacking should be cheap to make blob a more dangerous enemy to fight, while not allowing it to reach critical mass more quickly while not in combat.

Re-rolls are very cool and make fighting blob more dynamic. They also help combat the current terrible balance between blob variants so RNG doesn't force you to watch yourself die to fire extinguishers. However, you have to pass up 80 chemicals to get one after your first. In fact, I believe any chemical cost makes re-rolling clunky to use - re-rolls work best as an attempt to throw off a crew that's beating you too easily, and sinking yourself into low points plays actively against that. 

Reflector blobs are also rarely used. As they are now, you pay 15 points just to have a reflecting strong blob tile with 1/3rd health, and FOUR TIMES BRUTE DAMAGE. This means that the blob tile dies TWELVE TIMES quicker to brute than it did before! This buffs it to die a mere three times quicker to brute, and 1.5x quicker to burn.

### CODE REVIEW

**Comment by adamkad1** [comment]
well that seems like a balanced improvement

**Comment by 4dplanner** [comment]
BTW I pressed enter too early, will update description.

**Comment by 4dplanner** [comment]
Description updated

**Comment by 4dplanner** [comment]
Nerfed to 50%, because it's easier to buff again later than fix an overbuffing.

**Comment by subject217** [comment]
Eh, buffing blob endlessly doesn't really solve the intrisnic issues with the mode.

If you just keep buffing it you'll make them nonstop round enders. You can still win current blob pretty easily, it's just dependent on your location and rolling well on the blobbernaut ghost role choice.

**Comment by FrostyFridge** [comment]
I really like the free rerolls, seems like it would make fighting a bit more dynamic and interesting for both the crew and the blob.

**Comment by kingoftheautism** [comment]
@FrostyFridge Yeah, once I was a blob that getting damaged by water, when one dude finally figured out and other ones were bullying me I was able to reroll chemical and screw them over

**Comment by Tlaltecuhtli** [comment]
4 min FREE reroll is aids at this point just make it choose the chem

**Comment by Daxxed** [comment]
More I ded PRs. Maybe get better at playing blob ?
Do you even play the game ?
All jokes aside good balanced buff, can't wait to see it in action.

**Comment by yoyobatty** [comment]
Weren't half of the nerfs/buffs done here a result of blob?

**Comment by GuyonBroadway** [comment]
Yeah it seems every other week we get a "I died as blob to kinetic crushers, nerf pls" pr.

The highlight was nerfing beam rifles which are by and large one of the most useless, albiet cool, things you can get from a protolathe that has litterally killed more blobs than it has people.

**Comment by 4dplanner** [comment]
I personally disagree with nerfing items which are strong against Blob generally instead of making blob resistant to them, but I'm not set on that point. Nonetheless, that's a separate issue to the core strength of blob, which is low due to being better adapted to a roundstart gamemode with multiple blobs than a solo antag lategame when tech is abundant.

**Comment by GuyonBroadway** [comment]
In all the time we've had the bean rifle you'd think we'd have seen one sucessful station depopulation using it by now by sheer weight of numbers.

To my knowledge its been used to kill less people than the temperature gun.

**Comment by 4dplanner** [comment]
> Anyway, I support this PR. The changes seem good, but moderate. Could you look into expansion onto space turfs as well? Is the difficulty/cost due to a bug, or intentional design?

I believe it's intentional, to force the blob to attack the station to get its win.

**Comment by kriskog** [comment]
Expansion on space turfs don't give you progress and you don't autoexpand there. You can manual expand to bridge gaps, but you often have to hit the turf many times to build a blob tile there which is quite costly. That's the part I meant, is that intentional?

**Comment by GhostEcho** [comment]
Tbh if you really want to make blobs good, nerf engi borg self repair

**Comment by GuyonBroadway** [comment]
Lets not rebalance the rest of the game just to fit around one sub-par random event whos main problem is it shows up half an hour into the round where everyone either has their powergaming tools or is calling the shuttle.

**Comment by 4dplanner** [comment]
> Tbh if you really want to make blobs good, nerf engi borg self repair

If blob can only be removed by messing up the balance of everything else, it should just be removed. I believe it can still be fun with some tweaks, however.

**Pull request merged**
