### PR TITLE
Fire breath properly updates when lacking power chromosome.

### PR DESCRIPTION
**Pull request by moocowswag**
## About The Pull Request

Basically, if you put a power chromosome in your fire breath and then lose the mutation and got a new fire breath mutation (without a power chromosome) you would still retain the benefits of the power chromosome and could stack it with energetic.

This pr fixes that by reverting to initial values when lacking power chromosome.
## Why It's Good For The Game

Because if it isnt merged i`m going to abuse this.

## Changelog

:cl:
fix: Firebreath can no longer benefit from both power and energetic chromosomes at the same time
/:cl:

### CODE REVIEW

**Comment by ATH1909** [comment]
based??

have you tested to make sure this bug happens in actual play yet

**Comment by moocowswag** [comment]
> based??
> 
> have you tested to make sure this bug happens in actual play yet

Yes, it was aggravating me because I copy pasted code and found the bug when testing it for my own mutation code, then found out that was it.

**Comment by ATH1909** [comment]
does this bug also happen with the cooldown reduction from energetic chromosomes?
```
/datum/mutation/human/proc/modify()
	if(modified || !power_path || !owner)
		return
	var/datum/action/cooldown/spell/modified_power = locate(power_path) in owner.actions
	if(!modified_power)
		CRASH("Genetic mutation [type] called modify(), but could not find a action to modify!")
	modified_power.cooldown_time *= GET_MUTATION_ENERGY(src) // Doesn't do anything for mutations with energy_coeff unset
	return modified_power
```

**Comment by moocowswag** [comment]
> does this bug also happen with the cooldown reduction from energetic chromosomes?
> 
> ```
> /datum/mutation/human/proc/modify()
> 	if(modified || !power_path || !owner)
> 		return
> 	var/datum/action/cooldown/spell/modified_power = locate(power_path) in owner.actions
> 	if(!modified_power)
> 		CRASH("Genetic mutation [type] called modify(), but could not find a action to modify!")
> 	modified_power.cooldown_time *= GET_MUTATION_ENERGY(src) // Doesn't do anything for mutations with energy_coeff unset
> 	return modified_power
> ```

i dont know this seems to be a generic code that is for every mutation that supports energetic, if it`s broken it was broken for a long time.

**Comment by Fikou** [comment]
does this happen with other mutations

**Comment by moocowswag** [comment]
> does this happen with other mutations

No and take this with a mountain of salt because i might be talking from the deepest reaches of my ass because this is my second time touching anything code related outside of zybooks.

But from what I can tell, firebreath is the only actual spell mutation that uses power. The rest of the mutations that are modified by power chromosomes do not require updating a var and instead constantly check if one is present.

Here is an example of a body effecting mutation that uses power chromosomes

```
/datum/mutation/human/cough/on_life(delta_time, times_fired)
if(DT_PROB(2.5 * GET_MUTATION_SYNCHRONIZER(src), delta_time) && owner.stat == CONSCIOUS)
		owner.drop_all_held_items()
		owner.emote("cough")
		if(GET_MUTATION_POWER(src) > 1)
			var/cough_range = GET_MUTATION_POWER(src) * 4
			var/turf/target = get_ranged_target_turf(owner, turn(owner.dir, 180), cough_range)
			owner.throw_at(target, cough_range, GET_MUTATION_POWER(src))
```


Meanwhile spell mutation(s) (fire breath) requires modifying the spell`s vars which would require setting and resetting those vars.

**Pull request merged**
