### PR TITLE
Latejoin borgs (without the powercreep edition)

### PR DESCRIPTION
**Pull request by TiviPlus**
## About The Pull Request

Nice one

## Why It's Good For The Game

https://github.com/tgstation/tgstation/pull/52358#pullrequestreview-454274031

## Changelog
:cl:
add: Borgs can latejoin
/:cl:

### CODE REVIEW

**Comment by zxaber** [comment]
As I said in the last PR:
We should make sure the borg links to the station AI, if any. Since borgs no longer sync to AIs on other Z levels (except for multi-Z stations), this may end up with borgs syncing if they joing while the shuttle is parket at the station, but not syncing if they join while the shuttle is in flight.

**Comment by optimumtact** [comment]
Unfortunately I actually disagree with skog, two borg slots is fine, and we should have grown the number of borgs some time ago.

I strongly disagree with them being latejoin.

So this PR is the opposite of what I want.

**Comment by ATH1909** [comment]
Eh, okay, that PR was getting stale and I was procrastinating putting in the work to make syncing work properly with latejoiner borgs.

**Comment by Kaffe-work** [comment]
Why have borgs not being latejoin? You dont know if robotics is dead or just not doing their job, or if mining isn't doing it before you press observe. This would also enable players to play AI easier as well, instead of having to go pester robotics to borg them simply to accumulate cyborg playtime.

**Comment by Cyberboss** [comment]
I just want to point out that having borgs arrive on the shuttle may cause issues and thematically kinda doesn't make sense.

**Comment by optimumtact** [comment]
Okay I'm making an executive decision

no late start borgs

but an extra slot at roundstart for all maps if the population is > than midpop or whatever

**Pull request closed without merging**
