### PR TITLE
Adds an achievement for saving a cascading SM from the final countdown.

### PR DESCRIPTION
**Pull request by strandsofivy**
## About The Pull Request

Adds the "All Within Theoretical Limits" achievement. You get the achievement for standing inside the engine room at the time where the SM crystal heals from 0% health (when the crystal says "Crystalline hyperstructure returning to safe operating parameters. Harmonic frequency restored within emergency bounds. Anti-resonance filter initiated"), and waiting until the SM heals to at least 25% health.

## Why It's Good For The Game

This rewards engineers who stay behind and try to save the engine even in the most dire circumstances. 

## Changelog
:cl: distributivgesetz
add: Add an achievement for saving a cascading engine from the final countdown.
/:cl:

### CODE REVIEW

**Comment by distributivgesetz** [comment]
sorry for the sprite vomit that you have to witness, im extremely bad at art

**Comment by zxaber** [comment]
Can borgs get achievements? As an engineer borg, I was once part of a two-man team that saved a SM at the 2 second mark.

**Comment by distributivgesetz** [comment]
> Can borgs get achievements? As an engineer borg, I was once part of a two-man team that saved a SM at the 2 second mark.

No, but I can add that in

**Comment by distributivgesetz** [comment]
> No, but I can add that in, because you make a good point

done

**Comment by distributivgesetz** [comment]
gotta do more badge memery i got a new idea

**Review by Ghommie — APPROVED** [review]

**Comment by Ghommie** [comment]
It took me a moment to realize, staring at the icon, that the thing beneath the supermatter is a sofa with three people sitting on it and not an altar, but despite the ambiguity, it's still better than most.

**Pull request merged**
