### PR TITLE
switches lobes for grammar n shit

### PR DESCRIPTION
**Pull request by ghost**
Unread postby Grazyn » Fri Dec 08, 2017 7:28 am #364528

Nitpick but the visual cortex is in the occipital lobe

(not frontal!!)

### CODE REVIEW

**Comment by praisenarsie** [comment]
@Cyberboss can we make grammar prs a quarter a gbp

**Comment by Armhulen** [comment]
every pr i go he follows to make up a way to fuck me or my pr!

**Comment by praisenarsie** [comment]
because it's lazy gbp

**Comment by Armhulen** [comment]
ok well to be clear:


optimumtact commented 15 days ago
It's a valid method of getting points Think of it this way, if the system didn't exist, these things would never get done. They improve the overall polish of the game

**Comment by Armhulen** [comment]
if you're going to make it not worth even fixing then why would anyone fix it

**Comment by imsxz** [comment]
I don't understand all the fuss about lazy GBP. It's improving the codebase regardless of how little and all these small improvements add up.

**Comment by Armhulen** [comment]
imsxz is right can we b friends @praisenarsie

**Comment by Cyberboss** [comment]
Ignore the lesser frog

**Comment by Armhulen** [comment]
@Cyberboss can you add the grammar tag

**Review by Cyberboss — APPROVED** [review]

**Pull request merged**
