### PR TITLE
Circuitry upgrades and fixes

### PR DESCRIPTION
**Pull request by arsserpentarium**
HO-HO-HO!Merry X-mas!
And I present to you some fixes and upgrades in circuitry:
1.make plant module kill vines
2.xenobio scanner
3.drag component
4.fix smoker
5.heater module
6.damage for bot and machines(?)
7.improved pathfinder circuit
8.NTnet scaner(takes ref to thing.returns adress of NTnet adress if there is one)
9.fix work of arithmetic pins
10.object scaner. attack assembly with something on help intent and obtain it's ref.
11.Reagent juicer and grinder. When ACCount will remove possibility to drain fruits via injector, it could help.
12.fixed some runtimes in juicing.
image
image
reupload.sorry.

### CODE REVIEW

**Comment by arsserpentarium** [comment]
uhhh...fuck.looks like I won this battle with github.

**Comment by ACCount12** [comment]
No, Github wins this one.

**Comment by arsserpentarium** [comment]
There is problem. Code for pulling in atom/moveable has broken light. Not sure, how is better to fix it.

**Comment by arsserpentarium** [comment]
How I suppose to fix it, dammit?!

**Pull request closed without merging**
