### PR TITLE
Made plumbing roundstart and made Genetics no longer require xeno & hydro tech/experiments

### PR DESCRIPTION
**Pull request by carlarctg**
## About The Pull Request

Plumbing has been made roundstart.

Added a new middleground 40-point tech that includes some msicellaneous midtier reagent items like the scanner and metamaterial beaker.

Genetics no longer requires Xenobiology and Hydroponics, two custom-experiment-locked techs. Instead, it costs 120 points which are discounted by sampling two people who have a sequence mutation enabled.~~

Moved Advanced Watering Can from bluespace tech (?) to Node Selection.

Removed the middleground hydroponics technology and made its contents default.

## Why It's Good For The Game

Plumbing being ~~an 80~~ even a 40 point unlock is ~~really just bad~~ still pretty bad. Like, there's no point for it. Techwebs are for locking content behind timegates, and Plumbing by its own sheer design already locks the content behind the timegate of needing to set up, which always takes quite a while. 

Chemistry has plumbing roundstart, but what really screws this over is Service's plumbing tool. To access a niche, clunky subfeature now they need to ask for ~~80~~ 40 points to be blown on a tech nobody cares about. Even if it's low, there's no need. The timegate exists in the tech itself.

Similarly, Genetics being locked behind cytology and botany, two unrelated departments, scans is just kind of ridiculous. I get some of the point - no public consoles until later on. But now it's no public consoles EVER! You can't repair genetics! Maybe my current shuffle is too lenient, but I'm open to alternatives that don't make it unresearchable.

> Moved Advanced Watering Can from bluespace tech (?) to Node Selection.

It's advanced botany equipment, that's where it should be!

> Removed the middleground hydroponics technology and made its contents default.

This has the effect of making trays and biogenerators roundstart, which, again, I don't see how it benefits the game to restrict behind technology. Both have plenty of places where they can appear ingame anyway. Additionally, it once more makes experiments something the botanists can do roundstart rather than need to wait a tech for.

And speaking of, playing botanist it's just a hassle to have two techs when one of them is literally completely useless and its sole purpose is to make experiments undoable. No reason for it to exist and be annoying.

## Changelog

:cl:
balance: Plumbing has been made roundstart.
balance: Added a new middleground 40-point tech that includes some msicellaneous midtier reagent items like the scanner and metamaterial beaker.
balance: Genetics no longer requires Xenobiology and Hydroponics, two custom-experiment-locked techs. Instead, it costs 120 points which are discounted by sampling two people who have a sequence mutation enabled.
balance: Moved Advanced Watering Can from bluespace tech (?) to Node Selection.
balance: Removed the middleground hydroponics technology and made its contents default. This has the effect of roundstart biogen/tray boards & immediately-unlockable plant experiments.
/:cl:

### CODE REVIEW

**Comment by EricZilla** [comment]
You forgor...
(Good change)

**Comment by MTandi** [comment]
There's a research queue now, and we made plumbing a tier 1 tech, yet you're still unhappy. You can just add the  40 point chem synth node to the queue and it will be researched in no time.

As for public consoles, I thought we agreed that you will try to add circuit boards to the tech storage for this purpose, and we'll see if people use them. Did that not work? 

You say that genetics were under unrelated nodes. Why did you put it under medbay?

Why would cryostasis require plumbing?

**Comment by MTandi** [comment]
There's a research queue now, and we made plumbing a tier 1 tech, yet you're still unhappy. You can just add the  40 point chem synth node to the queue and it will be researched in no time.

As for public consoles, I thought we agreed that you will try to add circuit boards to the tech storage for this purpose, and we'll see if people use them. Did that not work? 

Also this is bad use case. We need something like gas vendor instead of public consoles.

You say that genetics were under unrelated nodes. Why did you put it under medbay?

Why would cryostasis require plumbing?

**Comment by carlarctg** [comment]
> There's a research queue now, and we made plumbing a tier 1 tech, yet you're still unhappy. You can just add the 40 point chem synth node to the queue and it will be researched in no time.

Yeah, no time. So why bother with the limitations that weren't there beforehand?

>  Do a couple of drinks for the counter during these 40 seconds. Your beer factory is bad for the current roundstart power situation.

That.... is out of scope.

> As for public consoles, I thought we agreed that you will try to add circuit boards to the tech storage for this purpose, and we'll see if people use them. Did that not work?

I don't know when we agreed to this. I don't think we have.

> Also this is bad use case. We need something like gas vendor instead of public consoles.

I agree that'd be the best possible solution, but there was a healthy-enough solution to this pre-techwebs rework that went away, which I want to bring back.

> You say that genetics were under unrelated nodes. They were related thematically, because they are about mutations of plants and slimes. Why did you put it under medbay?

They were under unrelated nodes, but crucially, they were behind unrelated departments' EXPERIMENTS. Needing to do hard cytology and hard botany experiments for genetics is wild and wrong.

I meant to put it under bioscan, I'll fix that.

> 
> Why would cryostasis require plumbing?

It's a roundstart tech, it doesn't matter. Because i felt weird to just add it as a thing unconnected to anything.

> What is the purpose of the new mid tier node?

I fugged up and didn't rebase, need to fix this.

> What's the new experiment mentioned in the changelog? Genetics already had an experiment with a scan of people with mutations (edited in consoles, or when they drink mutagen)

I fugged up and didn't rebase, removed that bit.

**Comment by ExcessiveUseOfCobblestone** [comment]
I think i recommended just putting the boards in tech storage, although I do think that techwebs should be for gating progression of the round, and ultimately having to sink point for things you get roundstart that should be replaceable roundstart does seem a bit yucky from a game perspective even though I understand the reasoning behind it.

**Comment by zoomachina** [comment]
> I think i recommended just putting the boards in tech storage, although I do think that techwebs should be for gating progression of the round, and ultimately having to sink point for things you get roundstart that should be replaceable roundstart does seem a bit yucky from a game perspective even though I understand the reasoning behind it.

There's one of every genetics related board in the tech storage already
image

**Comment by carlarctg** [comment]
image

Extremely circumstantial evidence but this is a RD main in manuel where rounds last upwards of 90 minutes and even he said genetics is just not a tech that gets researched. its proof there is indeed a problem even if you think this is not the solution

**Comment by MTandi** [comment]
> Extremely circumstantial evidence but this is a RD main in manuel where rounds last upwards of 90 minutes and even he said genetics is just not a tech that gets researched. its proof there is indeed a problem even if you think this is not the solution

>Evidence

Just ask a random mutated plant from botany and get a slime biopsy in xenobio to grow one with the roundstart protein powder bottle.

This is not harder than gas shells, this is not an evidence of anything.

**Comment by RafRoq** [comment]
> > Extremely circumstantial evidence but this is a RD main in manuel where rounds last upwards of 90 minutes and even he said genetics is just not a tech that gets researched. its proof there is indeed a problem even if you think this is not the solution
> 
> > Evidence
> 
> Just ask a random mutated plant from botany and get a slime biopsy in xenobio to grow one with the roundstart protein powder bottle.
> 
> This is not harder than gas shells, this is not an evidence of anything.

With some effort from the botanicist, artifical selection get researched at around 40-60 minutes into the round, not the botanicist fault because getting a wild mutation is not hard, sometimes the experiment is not even unlocked for botanicists to do at 40 minutes into the round because scientists don't care 80% of the time, unless you break in and do it yourself the powergamey way also asking borgs and AI to unlock the experiment for you, i do not think artificial selection should cost 120 points

**Comment by carlarctg** [comment]
Moved Advanced Watering Can from bluespace tech (?) to Node Selection.

It's advanced botany equipment, that's where it should be!

Removed the middleground hydroponics technology and made its contents default.

This has the effect of making trays and biogenerators roundstart, which, again, I don't see how it benefits the game to restrict behind technology. Both have plenty of places where they can appear ingame anyway. Additionally, it once more makes experiments something the botanists can do roundstart rather than need to wait a tech for.

And speaking of, playing botanist it's just a hassle to have two techs when one of them is literally completely useless and its sole purpose is to make experiments undoable. No reason for it to exist and be annoying.

**Pull request closed without merging**
