### PR TITLE
Added away missions to travis testing.

### PR DESCRIPTION
**Pull request by Shadowlight213**
Don't actually try to run a server with this. It will probably break. This is only for travis.

### CODE REVIEW

**Comment by optimumtact** [comment]
:-1: I hate how many things we are testing, it adds so much overhead to testing and makes changes harder if they have to touch maps.

**Comment by Shadowlight213** [comment]
@optimumtact it's better that it's tested than it silently runtiming to hell. Also, adding it to travis was requested by @Miauw62

**Comment by optimumtact** [comment]
I still hate it, along with having to build correctly like 71 billion maps that we will see maybe once a month.

**Comment by KorPhaeron** [comment]
We should scrap all the away mission maps and make a single dungeon/modular thing

**Comment by Jalleo** [comment]
@KorPhaeron we have remies map creator as a start.

**Comment by Shadowlight213** [comment]
@Jordie0608 @Miauw62 @Razharas @RemieRichards 
Ready for review/merge

**Comment by Razharas** [comment]
All of them?
Is this ok?

**Comment by KorPhaeron** [comment]
Don't worry I'm gonna remove some bad away missions soon

**Comment by Shadowlight213** [comment]
Since what missions we keep and what we remove seems to be controversial, I'm going to close this and redo it once its been decided.

**Comment by Shadowlight213** [comment]
The irony is, we added every single space and lavaland ruin to travis later. :laughing:

**Comment by optimumtact** [comment]
you were right

**Comment by Jordie0608** [comment]
Goof and his slippery slope doom-saying was right.

**Pull request closed without merging**
