### PR TITLE
Removes the ants reagent as it is in violation of the Goonchem port rules we all agreed to.

### PR DESCRIPTION
**Pull request by Iamgoofball**
Did nobody read the readme.md in chemistry? Fuck. We can't break these rules, it's not cool. Ants are a goon in-joke chemical, if I recall correctly it was literally one of the example ones told to me by the gooncoders back in the goon coding IRC channel when I was hashing out the terms of the port. I'm sorry guys, this is a fun easter egg and all but it just cannot be represented as a reagent in this way.

If this wasn't a direct port of ants from goon as laid out in the original PR (https://github.com/tgstation/tgstation/pull/59634) then this wouldn't be an issue, but it is a direct port with some extra stuff added on.

If you want to do goon ports, you *need* sign off from the OG coder that added it, which generally is not hard to get, but just porting Goon features without asking permission first is not okay. The original developer of ants wasn't even credited in the changelog!

## About The Pull Request
See title.

## Why It's Good For The Game

Wrath of the goons will kill our codebase if they find out about this. Sorry guys, we'll need to represent ants in a way that doesn't include reagents.

## Changelog
:cl:
del: Removes the ants reagent as it is in violation of the Goonchem port rules we all agreed to.
/:cl:

### CODE REVIEW

**Comment by Watermelon914** [comment]
I don't see why goon gets to have ideas that must be exclusive to them. As long as the implementation isn't the same.

**Comment by tralezab** [comment]
And nearly all ant code is new anyways, I feel like due diligence was done to make it unique

**Comment by Iamgoofball** [comment]
To summarize what I brought up in VC, we have methods and procedures for goon ports and they were not followed here.

**Comment by TiviPlus** [comment]
Verified ✔️

**Comment by Iamgoofball** [comment]
i did a real commit from there

**Comment by Thunder12345** [comment]
Can you lay out what the legal issues here are? Even if this used parts of goon's ant code, the only issues would be attribution and those parts belonging in a seperate file so they can remain under the same license as the original (https://creativecommons.org/licenses/by-nc-sa/3.0/). The orignal PR text says "This started off as a port of Goon's ants, but ended up taking on a mind of its own.", so this certainly doesnt appear to be a direct port, can you show which sections of code are taken from the Goon repo?

**Comment by Iamgoofball** [comment]
The description on goon:
chrome_3oq3E0F2Eu
The description from our code:
chrome_GoSGWk3EEs
The writing was stolen verbatim without any credit given to the original author, alongside the gameplay concept and execution. This is a huge breach of the standards for goon ports, and is ethically, morally, and potentially legally a liability.

Additionally, this is a violation of the agreement regarding goonchem specifically as this is a reagent, outlined in the chemistry readme.md
chrome_IcnCvsD2CO

As the person who was there when this agreement was stated, I recall Ants specifically being one of the examples given to me by the goon coders of "goon in-joke chems".

When porting from goon, there is an accepted standard that we all go through.
1. You inquire with the goons as to who the original author is.
2. You ask for permission from the original author.
3. You credit the original author in the PR and the changelog.

None of this was done for the PR, and that's the big issue here. We can re-add ants once we've gotten approval from the original author, and more importantly identified the original author.

**Comment by Thunder12345** [comment]
The description certainly needs to be changed, yes. Apart from this the code appears to be very different, so unless goon owns the gameplay concept behind ants I'm not sure why the rest is an issue. Can we see a copy of this agreement that was made, so we can understand what it entails and how it relates to gooncode's license?

> I'm also the person who's on the hook if this agreement is violated
What do you mean by this, exactly?

**Comment by ChungusGamer666** [comment]
rename name and description for epic win

**Comment by tralezab** [comment]
> rename name and description for epic win

maintainers HATE blants.

**Comment by Iamgoofball** [comment]
The goons have investigated, and it is impossible for us to get an official signoff on a port of ants, due to the coder being unreachable.
Discord_mRkOcr9Sxq

**Comment by tralezab** [comment]
or we could just add an attribution and change the desk omg guys

**Comment by Iamgoofball** [comment]
No. We cannot get proper approval for ants from the original author because the original author does not wish to be associated with Space Station 13 anymore. It's not acceptable to keep this in.

**Comment by tralezab** [comment]
approval for what though? it isn't the code, and the concept is generic.

**Comment by LemonInTheDark** [comment]
God damn it I missed this line
`This started off as a port of Goon's ants, but ended up taking on a mind of its own.`

**Comment by Wallemations** [comment]
If I were to change the desc & the ant decal sprite, would that make this not a "port" anymore? Those are the only two things I can think of that aren't my code.
I understand that the original coder doesn't wish to be associated anymore, so if _**none**_ of it is his code, that shouldn't be a problem, right?

**Comment by tralezab** [comment]
original coder from 7 years ago stopped playing i guess we can never have ants in the game anymore 😋

**Comment by coiax** [comment]
Maintainers are discussing this, and what our response is.

**Comment by Mothblocks** [comment]
These rules are from a time long ago when Goon was closed source, and when the relevant parties were still involved in SS13.

The code is effectively all ours, and we are free to use whatever ideas we want. I'm fine changing the description to not exactly match the one before, but unless someone like ZeWaka actually speaks out, this is just pearl clutching.

**Pull request closed without merging**
