### PR TITLE
[Ready]Adds fireworks to contrabrand lootpool(WE SMUGGLIN FIREWORKS BOIS)

### PR DESCRIPTION
**Pull request by improvedname**
It adds fireworks to the contrabrand pool, giving it some more love for people who want go all illegal and shit, maybe blow their own finger off with the firecrackers too. with a chance to spawn with a frag grenade

## Changelog
:cl: Improvedname
tweak: Contrabrand lootpool can now include fireworks
/:cl:

### CODE REVIEW

**Comment by optimumtact** [comment]
It's not rare at all, it's a 1 in 5 chance

**Comment by improvedname** [comment]
@optimumtact Its a normal box now without the spawn chance

**Comment by optimumtact** [comment]
well I didn't think it was gonna be a big deal, just pointing out it wasn't rare.

**Comment by ATH1909** [comment]
Maybe this should be in its own special crate, in case people want to make huge firework displays?

**Comment by Krysonism** [comment]
> 
> 
> well I didn't think it was gonna be a big deal, just pointing out it wasn't rare.

It was only like 7% chance(?) to get a frag grenade for 3000 credits.  Not a problem in my opinion unless you are able to get like several hundreds of thousands of credits.

I say make it use the dangerous box again.

**Comment by Krysonism** [comment]
> 
> 
> Maybe this should be in its own special crate, in case people want to make huge firework displays?

I think the dangerous box should have chance to spawn in the contraband crate, and a separate crate with safe firecrackers and sparkler boxes.

**Comment by improvedname** [comment]
Why would NT sell fireworks when it isnt new years

**Comment by Tlaltecuhtli** [comment]
oh i thought you were adding it to the blackmarket pool

**Comment by necromanceranne** [comment]
Smuggler satchels pull from this too. Out of the uplink they're like 2 tc, but they're primarily grabbed for storage space expansion. 

I get that the likelihood of getting a frag grenade out of this is low, but smuggler satchels are going to end up giving out frag grenades at some point and that's a pretty exceptional reward every now and again. Also the roundstart frag grenades in satchels under the floor are going to make explosions above them even stronger.

**Comment by necromanceranne** [comment]
I also just tested the strength of the grenade on an elance.

The answer is 'oh yeah that'll kill just about anyone'. So frankly, it's up to you to decide if a free easy elance from out of the floorboards is acceptably balanced or not.

**Comment by Krysonism** [comment]
> I also just tested the strength of the grenade on an elance.
> 
> The answer is 'oh yeah that'll kill just about anyone'. So frankly, it's up to you to decide if a free easy elance from out of the floorboards is acceptably balanced or not.

Like 1.5% to get a frag grenade from a satchel. I don't think we will see these that often.

**Comment by improvedname** [comment]
And even then saying a grenade on a elance isn't anything special since you can easily create wayyyy stronger explosions with grenades

**Comment by necromanceranne** [comment]
Not necessarily a matter of strength but a matter of availability. It doesn't have to be the strongest for an elance and in some regards it probably shouldn't be the strongest.

Also, there are more than one satchel usually on the station, so it's 1.5% per satchel spawn, which is a little more likely. Still low, but possible.

**Comment by improvedname** [comment]
Chances are just small. and in the future they be more in contrabrand likely anyways so it doesn't really matter

**Comment by Jordie0608** [comment]
I'm ok with this, could be fun.

**Pull request merged**
