### PR TITLE
Fixes bad oversights on Charlie Station

### LINKED ISSUE #46028: Charlie rework issues
## Charlie Station ruin problems as introduced by the rework (#45838)

- Two Charlie Station APCs: Kitchen and Engineering, start disconnected from the grid. It looks like an oversight rather than something that can be explained by the wear of the station since you have to pry up the floor tiles to fix it in an otherwise largely intact space and the APC terminals lacked wiring which may be easily overlooked on an overview
image image

- Two hivebots surrounding the weapons crate in Delta remain from the old iteration, their replacement with benos was presumably stated to be absolute.

- Speaking of benos, they are completely braindead. They didn't fight back against the hivebots' nor any attacks nor when they saw me and neither did they move at all from their spaces

- The three Delta Vault/AI doors past the airlock with double doors didn't have anything below them, the tile being completely open to space once they were opened.

- This wasn't a problem when the xenos weren't in the picture, but there's no welding fuel tanks in what's presumably the main engineering area when you may want to repair/tear down walls, attack downed aliens, weld vents shut or just clean up resin floors for aesthetic purposes

- May not be easy to fix, but since the Beta/Charlie/Delta complex lacks roundstart telecom machinery, the radio headsets in the two locked closets by you when you spawn are essentially unusable

### PR DESCRIPTION
**Pull request by redmoogle**
### About The Pull Request

Fixes #46028 

## Why It's Good For The Game

- Fixes Xeno AI
- Fixes Unlinked APCS
- Adds a Welding Tank(in delta maint)
- Removes the personal closet error
- Fixes the floor tiles in AI core

## Changelog
:cl:
bugfix: Fixed bad mistakes on Charlie Station
/:cl:

### CODE REVIEW

**Comment by redmoogle** [comment]
hold up some of these changes may have affected some unwanted sutff

**Comment by actioninja** [comment]
For future reference, [s] isn't for hotfixes or patches it's for security issues. You're not in trouble but avoid using it like this from now on.

**Comment by redmoogle** [comment]
ah ok I mean I know it means [silent]

**Comment by redmoogle** [comment]
alrighty looks fine

**Comment by Timonkeyn** [comment]
make the xeno queen a simplemob

**Comment by redmoogle** [comment]
> make the xeno queen a simplemob

It already is dingus

**Pull request merged**
