### PR TITLE
Draft pull requests? neat.

### PR DESCRIPTION
**Pull request by MrsTonedOne**
Work in progress, can not be merged.

https://github.blog/2019-02-14-introducing-draft-pull-requests/

@tgstation/commit-access

### CODE REVIEW

**Comment by sabiram** [comment]
lol

**Comment by Caiggas** [comment]
Nice, gonna use this

**Comment by MrStonedOne** [comment]
https://help.github.com/articles/changing-the-stage-of-a-pull-request/ said:
>Pull request authors and anyone with admin permissions for the repository can mark a draft pull request as ready for review.

Also github:
image

**Comment by optimumtact** [comment]
okay so literally anyone can mark it as ready and it's now mergable so it's pretty useless???

**Comment by MrStonedOne** [comment]
Its a bug, I reported it.

**Comment by Jordie0608** [comment]
I wonder if we'll be able to get a separate PR template for drafts.

**Comment by Cyberboss** [comment]
ahh ffs laddie, muh webhooks ain't gonna like this

**Pull request closed without merging**
