### PR TITLE
Both cult revive runes will now replace braindead/AFK cultists

### PR DESCRIPTION
**Pull request by Robustin**
:cl: Robustin
add: The blood cult revive rune will now replace the souls of braindead or inactive cultists/constructs when properly invoked. These "revivals" will not count toward the revive limit.
add: The clock cult healing rune will now replace the souls of braindead or inactive cultists/constructs when left atop the rune. These "revivals" will not drain the rune's energy. 
/:cl:

Thinking of creative ways to improve the cults without provoking balance memes. Both cults have long suffered when you risk life and limb to pull off a conversion only to find out your victim ragequit or went AFK because they didnt want to be an artificer. Or sometimes shit happens.

Either way everyone understood the frustration of seeing their conversion go to waste. This gives the cults an IC-solution while taking the burden off admins and players alike.

### CODE REVIEW

**Comment by Supermichael777** [comment]
MBA elder god: Cultists are interchangeable balls with no individual traits outside of required talents.

**Comment by davethwave** [comment]
You are doing a great work here. This one pr will improve cult win rates by at least 10% in my opinion.

**Comment by Xhuis** [comment]
Might be a bit too kneejerk of me, but if it's possible to make the vitality matrix require no vitality when resurrecting a suicide, it would offset the setback caused by someone instantly offing themselves when they're converted. Assuming that's possible to do reasonably, of course!

**Comment by kevinz000** [comment]
people should ahelp anyways because people who afk/logout/suicide after conversion are the fucking worst.

**Comment by Robustin** [comment]
@XDTM ive glanced around for a suicide var, havent found it, if theres a way to ID suicides I would add it

**Comment by Xhuis** [comment]
Mobs have a var called `suiciding` that sets to `TRUE` when they commit suicide.

**Comment by Cyberboss** [comment]
@KorPhaeron @Armhulen @ausops

**Comment by Ausops** [comment]
im ok with this, in case you haven't just make sure people who DC for just a few moments due to whatever don't get replaced

**Comment by Robustin** [comment]
@Ausops 

That was the only issue I had with this approach. Ultimately I figure it won't be a big deal since people aren't likely to use it on someone who was active recently and unless you DC on top of one of these runes you'll probably be back before someone goes through the effort of dragging you off and using one on you. 

If it does happen then you've got Ahelp as a remedy.

The only other solution would be to have a message come up when they reconnect but I can't think of any way to "leave a message". Since the AFK timer is tied to the client I don't know how I could utilize that before DC'd players who no longer "have" a client.

**Comment by JJRcop** [comment]
I think it's an unfortunate but acceptable edge case.

**Comment by Cyberboss** [comment]
@Armhulen @KorPhaeron

**Comment by KorPhaeron** [comment]
Indifferent I guess. Don't really like the idea of other people playing under my name and I'm not sure incentivizing kidnapping braindeads to win is good but I understand having people go afk in conversion modes sucks

**Comment by davethwave** [comment]
Yeah, I remember a round a day or two on bagil. It was blood cult and at least 4 out of the 11 or so people we had were braindead.

**Comment by Robustin** [comment]
I understand that discomfort but at the end of the day when conversion requires a very serious effort it's more than a fair trade. 

Also @KorPhaeron I don't think it adds any "incentivize" to kidnapping those people since your shard changes years ago made it impossible to turn braindead/catatonics into ghost-controlled constructs. That remains a far better deal in my mind.

**Pull request merged**
