### PR TITLE
Fixes supermatter extraction again

### LINKED ISSUE #42301: You can make infinite supermatter slivers
You can repeatedly take slivers off the SM without harming it, allowing you to make dozens or hundreds of slivers, which are highly radioactive and dust anyone who attempts to pick them up.

### PR DESCRIPTION
**Pull request by DaxDupont**
[Changelogs]: # (Your PR should contain a detailed changelog of notable changes, titled and categorized appropriately. This includes, new features, sprites, sounds, balance changes, admin tools, map edits, removals, big refactors, config changes, hosting changes and important fixes. An example changelog has been provided below for you to edit. If you need additional help, read https://github.com/tgstation/tgstation/wiki/Changelogs)

:cl: Dax Dupont
fix: The supermatter scalpel now isn't infinite usage.
/:cl:

[why]: # (Please add a short description [two lines down] of why you think these changes would benefit the game. If you can't justify it in words, it might not be worth adding.)

fixes https://github.com/tgstation/tgstation/issues/42301

### CODE REVIEW

**Comment by DaxDupont** [comment]
@denton81 Included your message change for the scalpel so it wont conflict later

**Comment by DaxDupont** [comment]
@81denton Included your message change for the scalpel so it wont conflict later

**Comment by 81Denton** [comment]
Thanks!

**Comment by Cyprex** [comment]
Why, this bug was fun!

**Comment by Cyprex** [comment]
On that note, can you pull supermatter shards around?

**Comment by SpaceManiac** [comment]
code\modules\power\supermatter\supermatter.dm:580:error: scalpel.usesLeft: undefined var
code\modules\power\supermatter\supermatter.dm:584:error: scalpel.usesLeft: undefined var
code\modules\power\supermatter\supermatter.dm:585:error: scalpel.usesLeft: undefined var

**Comment by DaxDupont** [comment]
I think I committed the wrong version ill fix it in a bit

**Review by Cyberboss — APPROVED** [review]

**Pull request merged**
