### PR TITLE
Adds Cannoli

### PR DESCRIPTION
**Pull request by RiskySikh**
## About The Pull Request
image

Ciao, the PR adds cannoli which is a Sicilian dessert that was made popular by Italian American immigrants in the late 19th century, and is a filling of a fried pastry which is filled with sweetened ricotta. It's a delicious treat that is guaranteed to give the average working man at the station, a delight.

## Why It's Good For The Game
Well, it provide a bigger variety of foods, and an opportunity for chefs to create more creative dishes, as well as an opportunity for mobsters or families to have a delicious treat while whacking rival mobsters. Oh Marone, even Paulie Walnuts supports this. 

## Changelog
:cl:
add: Chef's now can make another type of pastry which is the world famous cannoli which originates from the land of Sicily. 
/:cl:

### CODE REVIEW

**Comment by RiskySikh** [comment]
Credits to Twaticus for making this wonderful sprite without them, I wasn't able to make this PR.

**Comment by Mickyan** [comment]
Leave the disk, take the cannoli

**Comment by ArcaneMusic** [comment]
...Who's paulie walnuts?

**Comment by RiskySikh** [comment]
> 
> 
> ...Who's paulie walnuts?

image

**Comment by optimumtact** [comment]
what kind of redemption arc is this

**Comment by Pugie** [comment]
Free him

**Comment by wesoda25** [comment]
@Twaticus sexy fucking sprite good job

**Comment by cacogen** [comment]
>who's paulie walnuts
OH!

**Comment by tralezab** [comment]
what a great pr! keep up buddy!

**Comment by Tumesuo** [comment]
What if I only want to eat one cannoli at a time and not 5...

**Comment by actioninja** [comment]
conflict

**Comment by RiskySikh** [comment]
> 
> 
> conflict

i fixed the merge conflict, it works now

**Pull request merged**
