### PR TITLE
Space dragon resprite

### PR DESCRIPTION
**Pull request by actioninja**
## About The Pull Request

Proxy PR

image

Looks like this:
image

## Why It's Good For The Game

It looks better

## Changelog
:cl: Meyhazah
imageadd: New sprite for the space dragon
/:cl:

### CODE REVIEW

**Comment by Mey-Ha-Zah** [comment]
Thanks.

**Comment by IndieanaJones** [comment]
Nice.

**Comment by ArcaneMusic** [comment]
...But it's more like a worm now.
And I don't mean like a wyrm or a wyvern or whatever dragon semantics  anyone wants to get into.
I mean it looks like a Noodly Golbat with wings.

I mean, it's fine by all means but it doesn't give the same dragon vibe as the Ashdrake does, ya know?

**Comment by actioninja** [comment]
This is what it looked like before, it's just a cleaned up sprite.

**Comment by Mey-Ha-Zah** [comment]
Space Dragon isn't ash drake. It's a sorta... morphed Carp... but yeah I only cleaned up the sprite, its not a new one.

**Comment by ecronogist** [comment]
im wormy

**Pull request merged**
