### PR TITLE
Makes the admin bomb list a bit more useful

### PR DESCRIPTION
**Pull request by lzimann**
It now tracks C4s and welding fuel explosions aswell

### CODE REVIEW

**Comment by Saegrimr** [comment]
Add in:
Firebombs
Molotovs
Pizzabombs
Lemons
EMPs
X4 I guess if that isn't already covered by C4
Rad pulses maybe?
Chemical grenades with the reagents listed if possible.

List has been completely empty aside from TTVs and singletanks for far too long.

**Comment by ma44** [comment]
Lemons are already logged

**Comment by nullbear** [comment]
Pretty sure chemgrenades were already listed at some point. If not check chemsplash code.

**Comment by nullbear** [comment]
Yeah chem grenades have it.

**Comment by lzimann** [comment]
This is not regular logging. We have a verb(access with secrets -> bombing list) which, currently, shows TTVs and single tanks interactions. I'm expanding this to include a few other things to this.

**Comment by lzimann** [comment]
Alright should be all good now.

**Pull request merged**
