### PR TITLE
Tweaks stun baton cell drain as a rebalance.

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request

Lots of argumentation about stun combat in the game, this is an experimental change in response to that. Urge it as a testmerge, wait and tweak it as an actual merge.

## Why It's Good For The Game

I was thinking about discourse over "stun combat", and thought that this would be an interesting change to experiment with. I'm not crazy about it, I actually think it would need some tweaking to find the optimal values, but as a test merge candidate, it really interests me. It's basically lowering the _presence_ of stuns. The amount of weapons available and stun damage done remains completely the same, all it's doing is making the window of batons smaller. Tele batons remain the same, you can stack multiple batons in your backpack, there's counterplay, but that doesn't matter.

You can just upgrade your batons cell.

I've literally seen so few people actually upgrade their batons cell when it's a fully functional, useful feature in the game, it boggles the mind. And if people DO do that, then this change just means that roundstart batons are weaker than later in the shift, which is a cool dynamic to have. 

Anyways, this is a minor PR that I went for while looking into sprite design and messing around on VScode, I know nothing about the world of github drama or if this completely goes over some guideline that was created about game balance. Bless. And please, PLEASE, give me feedback.

## Changelog

:cl:
balance: Cell drain for normal stun-batons changed from 1000 to 2000. (10% to 20%)
/:cl:

### CODE REVIEW

**Comment by tommysalami3** [comment]
how did my one line PR that's synced with master fail northstar integration tests

**Comment by itseasytosee** [comment]
I doubt this change will fix stamina combat, but it might teach us something.

**Comment by Helg2** [comment]
To cuff your victims?

**Comment by Jackal-boop** [comment]
i think cutting down a round start officers baton to about 5 swings is a huge cripple, you often need more than that if you are dealing with a group or a stun resistant enemy

**Comment by tommysalami3** [comment]
> i think cutting down a round start officers baton to about 5 swings is a huge cripple, you often need more than that if you are dealing with a group or a stun resistant enemy

Yes, it is crippling! But that shift in power makes the rest of the kit all the more useful. Security teams have so many options at their disposal, flashbangs, dragnet, armory, disablers, not to mention simply moving in grouped patrols. I think it would be very interesting to see them utilize those unique advantages instead of forgoing them in favor of the baton. Currently, most power-based weapons are balanced around the amount of power demanded by them being pretty inconsequential (barring the ion HoS gun.), therefore making recharging them a mechanic that punishes you for forgetting to recharge them, not for managing your cell power between many different weapons. I think swapping it to a more strategic setting, even for a testmerge, would be very interesting, not to mention raising the skillcap on sec in general!

**Comment by timothymtorres** [comment]
This is a great idea!  Could even lead to some interesting scenarios where people purposefully sabotage power cells by filling it with plasma and gifting it to security.

**Comment by Livrah** [comment]
1(2) hit stun combat will be a same, but security will have a harder time dealing with a wave of non-antag shitters.

**Comment by tommysalami3** [comment]
> I think for me to sub to the idea the sprite needs to reflect the charge.
> 
> If we're expecting charge be an important balancing act then it needs to be extremely visible when the alternative could mean the person is now sitting out of the round. Other items of this nature do this, I think batons just have examine or a buzz when it's too late

Batons make an audible noise and switch off when they run out of charge. Or are you suggesting there be a warning when you're running low on juice?

**Comment by ExcessiveUseOfCobblestone** [comment]
if the indicator for charge is only an examine and when its literally useless the indicator is pretty poop.

There should be a visual indicator that represents the amount of charge on the item that doesnt require constant shift clicking. This is especially true if we want the charge to have a huge impact, such as halving the amount of uses.

**Comment by tommysalami3** [comment]
> if the indicator for charge is only an examine and when its literally useless the indicator is pretty poop.
> 
> There should be a visual indicator that represents the amount of charge on the item that doesnt require constant shift clicking. This is especially true if we want the charge to have a huge impact, such as halving the amount of uses.

I assume people would just adapt to thinking "5 hits" instead of "10 hits", which is how i keep track of stuns right now, but that would be a nice quality of life change in general. The current cell drain is just a placeholder though, I want to see it in game to measure player response and how much of an impact it has.

**Comment by MrMelbert** [comment]
Could be neat to apply the gun fire sound pitch effect to baton stun sounds. 
Simultaneously giving the user an alert of when they're almost out and should back off, while giving opponents a sign when they should press the attack.

**Comment by tommysalami3** [comment]
> Could be neat to apply the gun fire sound pitch effect to baton stun sounds. Simultaneously giving the user an alert of when they're almost out and should back off, while giving opponents a sign when they should press the attack.

That would be fantastic! Sadly, I have zero talent at coding and understand nothing beyond changing vars, copy pasting, and pushing commits.

**Comment by jughu** [comment]
i think batons having a passive drain would help aswell when they're on if you keep it at default numbers ans then 100 charge every tick in the end this wouldnt do too much for combat but if the scenario drags out long enough while the baton is on you might lose a charge or two

**Comment by EricZilla** [comment]
Sec use your peppers pray challange, love the idea

**Pull request closed without merging**
