### PR TITLE
Fix wire feedback sound; fix tanks valve

### LINKED ISSUE #14831: Autolathe hacking lights are broken
Please revert this, knowing that the green light is always contraband is such a helpful thing. I don't know why on Earth somebody ever changed it when it was completely fine how it was.

They also sometimes don't even show the contraband light at all, meaning you literally have to randomly cut wires until you get it right like on an autolathe.

### PR DESCRIPTION
**Pull request by neersighted**
Apparently wires used to play a default windows chime when cut, adding audible feedback
It was the windows 'bong' sound, and I'd rather not try to replicate it, so instead
we play the wirecutter sound very softly

Fix tank valves not showing up as connected.

Also fixes a bugged autolathe check (Fixes #14831)

### CODE REVIEW

**Comment by xxalpha** [comment]
It did?

**Comment by tkdrg** [comment]
They did, probably due to the default window refresh event sound.

**Comment by neersighted** [comment]
Yeah it was some windows BS; this is more elegant

**Comment by neersighted** [comment]
If someone would please restart the build, it appears that travis goofed.

**Comment by xxalpha** [comment]
Close and reopen yourself for it to rebuild.

**Pull request merged**
