### PR TITLE
Kronkus seeds are now available via the black market uplink

### PR DESCRIPTION
**Pull request by the-orange-cow**
## About The Pull Request

Adds kronkus seeds to the black market uplink.

## Why It's Good For The Game

Currently, the only way to obtain kronkus vines is as a rare maintenance spawn that is determined at shiftstart.  Even if it spawns, it would require taking a considerable amount of time to search for(not even knowing if it exists) or being lucky enough for an assistant to bring some in.

This seems to be an overly severe level of restriction with regards to the actual effect of the drug it can produce.  This rng scarcity also penalizes cytology, which already suffers from a lack of content without having certain species locked behind a rare drug made from a rare spawn.

By providing another method of obtaining via black market uplink, it will still take time ,effort, and cash to obtain but without a brutal shiftstart rng dependence.

## Changelog

:cl:
balance: Kronkus seeds are now available via the black market uplink.

/:cl:

### CODE REVIEW

**Comment by carlarctg** [comment]
It'd be nice to have something botany can and will do by themselves that isn't directly related towards murdering or healing.

**Comment by DaydreamIQ** [comment]
Hooray, illegal narcotics that aren't just WEED!

**Comment by Time-Green** [comment]
This is very blatant feature creep. I don't disagree that kronkus vine is weak and it should be more available, but making it a mutation from a vendor-available plant reduces it from being **the** maint plant to just another plant botany can make without leaving their room. This goes against what the Kronkus vine is supposed to be.

I would be okay with buffs or adding it to other 'ghetto' sources

@Krysonism thoughts?

**Comment by the-orange-cow** [comment]
> This is very blatant feature creep. I don't disagree that kronkus vine is weak and it could be more available, but making it a mutation from a vendor-available plant reduces it from being **the** maint plant to just another plant botany can make without leaving their room. This goes against what the Kronkus vine is supposed to be. Not everything has to always be available.
> 
> I would be okay with buffs or adding it to other 'ghetto' sources
> 
> @Krysonism thoughts?

The intent of this PR was less about kronkus absolutely needing to come from mutagen weed mutation, and more just that it seemed reasonable to have there be some kind of semi reliable method of obtaining it.  I had actually considered ordering it via exotic seed crate first, but then figured that the description mentioning it as being hyper illegal would counter that.  At the time, making it available via mutagen weed mutation merely seemed at the time to be a reasonable and intuitive way such a plant could be obtained.

Do you have other preferences about what alternate methods of obtaining kronkus should exist?  It really does seem too inconsequential as is to justify such a unreliable and laborious method of obtaining it, objectively more powerful/deadly chems can be far more easily obtained as things already stand.

You mention buffing it's effect;  I'm not as confident at making that kind of change with this PR, not really the purpose, but if you have something you'd like to see done I can try and implement.

**Comment by Yttriums** [comment]
Really don't feel a mutation from liberty caps feels right. I think it should instead be added as a random item in the contraband crate (which is available from the service order console). You could also add odious puffball there as well.

That would give botanists a way of rolling for these plants that's lore appropriate and doesn't ruin the magic of the rare moon rocks.

**Comment by the-orange-cow** [comment]
Per @Time-Green request, I've altered the pull to make the seeds available via a black market uplink.



> I think it should instead be added as a random item in the contraband crate (which is available from the service order console). You could also add odious puffball there as well.
> 
> That would give botanists a way of rolling for these plants that's lore appropriate and doesn't ruin the magic of the rare moon rocks.
> 
> Honestly I don't think of Kronkus as botany content and I don't think botany should be able to make it super on-demand. It's one of those things that can be grown by anyone who finds it, requiring only a single tray and some basic chem equipment. To me it's better as crossover content for assistants/janitors/engis who happen upon the seeds (and who can benefit more from the effect). There's no reason it needs to be grown in botany when every station has public gardens/ghetto botany spots.

Understandable.  It was recommended that I make it a black market item, which I feel still satisfies what you seem to be looking for.  For balance reasons, I'm reluctant to touch the puffball in the PR, but I like the idea.

**Comment by optimumtact** [comment]
I think this is the worst kind of lazy feature dev work where you take one item and just make it available easier because you can't be bothered to think up some new genuine features
:-1: from me.

**Comment by Time-Green** [comment]
After a lot of deliberation, I'm going to close this. I was a bit on the fence about adding it to more sources (since the sanctity of available item is especially important, especially in round-based games), but I agree with Oranges that I'd rather see cool new ghetto plants than make an existing one more reliably available

**Pull request closed without merging**
