### PR TITLE
Makes the katana not fit in backpack

### PR DESCRIPTION
**Pull request by jughu**
IM PRETTY SURE IT WASNT INTENDED MAKING A KATANA THAT IS 40 BRUTE AND CAN DEFLECT PROJECTILES WITH 50 CHANCE WAS TO FIT IN A BACKPACK

:cl: Hyena
fix: Brings the katana to its proper size
/:cl:

[]: # (Please add a short description of why you think these changes would benefit the game. If you can't justify it in words, it might not be worth adding: its toooooo tiny!

### CODE REVIEW

**Comment by jughu** [comment]
@KorPhaeron thoughts on this? im pretty sure this wasnt intended

**Comment by Kromgar** [comment]
Katanas fit in backpacks?

**Comment by Kromgar** [comment]
Also why the fuck are Katanas not dual wielding weapons?


They are supposed to be dual-wielded

**Comment by jughu** [comment]
yeah katanas fit in backpacks 40 brute weapon 50 block chance(flipping coin galore!) and comes in a syndie bundle with adrenals and a cham

**Comment by KorPhaeron** [comment]
I think Yack made them fit in bags because people called their bundle dumb

**Comment by jughu** [comment]
but its basically claymore class with 50 block chance and 40 brute thats like instant limb removing tier and half double esword tier

**Comment by jughu** [comment]
it be too OP if it fits in a backpack and makes no sense TBH

**Comment by KorPhaeron** [comment]
Feature freeze, sorry

**Comment by jughu** [comment]
@KorPhaeron i just checked yack's ninja pr he didnt change it

**Comment by KorPhaeron** [comment]
Either way, reoepen this when the freeze is over

**Pull request closed without merging**
