### PR TITLE
Removes catpeople and all code related to the species

### PR DESCRIPTION
**Pull request by nervere**
:cl: Nervere
del: Catpeople (felinids) have been removed.
del: All code related to felinids, including a moodlet, laserpointer check, purrbation, etc. have been removed.
/:cl:

[why]: Catpeople are a species that have existed purely as anime/weeb bait since their conception.
It has acted as a pervasive force in the code and in the game, bringing in unwanted PRs like #33841 #39098 and #40294 just to name a few. It's best to gut the meme race while we still can as to preserve our integrity.

### CODE REVIEW

**Comment by BeeSting12** [comment]
can we not do shit just to make large groups of players mad? thanks.

**Comment by Arianya** [comment]
2 player polls have had this as something the playerbase wants to remain in the game. Have you run a new poll that proves otherwise?

**Comment by CosmicScientist** [comment]
\>remove catgirl PR
\>not by goofball

\>we have integrity

I wonder what the ratio of PRs that follow the request first for races rule to PRs that don't is.

**Comment by vuonojenmustaturska** [comment]
You already have a config setting you can use to toggle the availability of catpeople on the server you are a headmin on

**Comment by BeeSting12** [comment]
@vuonojenmustaturska He knows the other two headmins won't let him do that so he's going to remove it from the codebase instead.

**Comment by Iamgoofball** [comment]
@nervere As much as I approve this PR, this is fast tracking your way to a blacklist if this gets merged and MSO finds out. Something something subverting configs.

**Comment by DaedWren** [comment]
nyaaaa~ :3

**Comment by Borisvanmemes** [comment]
My god he really is purging anime.

**Comment by Qustinnus** [comment]
OH SHIIIT

**Comment by BeeSting12** [comment]
What would be really funny is if a maintainer just immediately shut this and locked conversation so Nervere doesn't get the joy of seeing people arguing about it.

**Comment by callanrocks** [comment]
Leave it open and then just don't do anything with it for dramas sake ok

**Comment by Cyberboss** [comment]
>Code adding, removing, or updating the availability of alien races/species/human mutants without prior approval. Pull requests attempting to add or remove features from said races/species/mutants require prior approval as well.

Neither @optimumtact, or I, or any maintainers were consulted on this

**Comment by optimumtact** [comment]
Actually I was consulted and I said I was happy for them to make the PR, so it's weird for you to claim otherwise.


As to actually merging it /shrug

**Comment by Barhandar** [comment]
10/10 "you're free to make the PR but I ain't merging it"

**Comment by optimumtact** [comment]
who said I wasn't gonna merge it?

He seemed to want to put it up to community opinion so I was like why not, it doesn't cost me anything to let him argue with the 300 or so furries who play cats

**Review by Cw3040 — CHANGES_REQUESTED** [review]
travis does not like the code, fix it so we can actually remove catpeople

**Comment by ishitbyabullet** [comment]
@BeeSting12 sadly this is the only place we can argue about it.

**Comment by nervere** [comment]
This PR was meant to be more of a lighthearted goof parody than anything else.
It was stupid of me to think that this would translate well at all. But let it be said that I _did_ have oranges' approval before posting the PR. Aside from the undue grief its caused, even if I did want this merged I'm not going to go through hundreds of weebs and furries to get it through, so I'm closing this.

**Comment by GuppyLaxx** [comment]
pussy

**Comment by epicmemename** [comment]
faggot

**Comment by Qustinnus** [comment]
shut up guppy

**Comment by mkl-0** [comment]
NO BALLS

**Comment by Thunder12345** [comment]
Cats win again

**Comment by wesoda25** [comment]
disgusting

**Comment by Wilchenx** [comment]
image

**Comment by epochayur** [comment]
lame

**Comment by Potato-Masher** [comment]
You will never achieve the ultimate goal if you don't grow a pair.

Open the PR. There is much at stake here.

**Comment by sagattyy** [comment]
gay nigga

**Comment by Militaires** [comment]
you showed me a weakness

**Comment by Carbonhell** [comment]
This is why you should have voted me tbh
I would have got this merged :^)

**Comment by fluxcapacitor1337** [comment]
open the PR and merge it

**Comment by DaydreamPuppeh** [comment]
Merge this shit

**Comment by bobbahbrown** [comment]
fastmerge

**Comment by sagattyy** [comment]
speedmerge

**Comment by Nilons** [comment]
worth a poll

**Comment by Wilchenx** [comment]
itt: delusional anti-weeb crusaders think this is still considered

image

**Comment by Fikou** [comment]
speedmerge

**Comment by optimumtact** [comment]
light hearted goof parody

**Pull request closed without merging**
