### PR TITLE
Fixes unnecessary references.

### PR DESCRIPTION
**Pull request by TechnoAlchemisto**
I think that the "ashwalker" title to the absinthe is fitting and is a nice compromise.

### CODE REVIEW

**Comment by Zilenan91** [comment]
sign me the FUCK up :ok_hand::eyes::ok_hand::eyes::ok_hand::eyes::ok_hand::eyes::ok_hand::eyes: good shit go౦ԁ sHit:ok_hand: thats ✔ some good:ok_hand::ok_hand:shit right:ok_hand::ok_hand:th :ok_hand: ere:ok_hand::ok_hand::ok_hand: right✔there ✔✔if i do ƽaү so my selｆ :100: i say so :100: thats what im talking about right there right there (chorus: ʳᶦᵍʰᵗ ᵗʰᵉʳᵉ) mMMMMᎷМ:100: :ok_hand::ok_hand: :ok_hand:НO0ОଠＯOOＯOОଠଠOoooᵒᵒᵒᵒᵒᵒᵒᵒᵒ:ok_hand: :ok_hand::ok_hand: :ok_hand: :100: :ok_hand: :eyes: :eyes: :eyes: :ok_hand::ok_hand:Good shit

**Comment by Armhulen** [comment]
good

**Comment by PKPenguin321** [comment]
:-1: There is no need for even a compromise

**Comment by TechnoAlchemisto** [comment]
:)

**Comment by Mercenaryblue** [comment]
I like it

**Comment by Jordie0608** [comment]
Niknak threatened me unless i closed this

**Pull request closed without merging**
