### PR TITLE
Removes references to "valid" from purrbation

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
Separation between code and server is absolute etc.

Some people are arguing they get to murder based on these lines and it should be up to the head admins to decide

### CODE REVIEW

**Comment by optimumtact** [comment]
cats being valid is a codebase decision sorry.

**Comment by RemieRichards** [comment]
:+1:

**Comment by bgobandit** [comment]
:cat:

**Comment by optimumtact** [comment]
Actual valid point from irc - you should replace the message with something for the user so they have some textual feedback of the event occuring.

**Comment by RemieRichards** [comment]
More valid points from irc: the new message should have as many nyaa puns as possible.

**Comment by Steelpoint** [comment]
Catpeople are a meme race and should be referenced to as such, and they should remain as is.

As such :-1:

**Comment by GunHog** [comment]
Coders do not have the authority to overrule admins on policy. This only creates confusion if the administration is not in agreement with the hard-coded statement.

**Comment by Steelpoint** [comment]
If some people are so fucking moronic that they think a text referencing valid for a admin only race, that I hope never gets made into a public selectable one, gives them carte blanche to kill anyone and everyone then just ban them or make them a retarded flyperson.

We have a PR that adds race banning for good reasons if this is a real problem, but since Cat people should be a admin only race then its going to be hard for a player to not get the attention of a admin who has to give them the race in the first place.

**Comment by GunHog** [comment]
"Valid" in this context means that people have the right to kill the catperson, not the other way around. Furthermore, Cat-people are enabled on Basil.

**Comment by Cebasiz** [comment]
isn't this supposed to be a joke anyway

if people who get turned into catpeople are really so confused why don't they just ahelp

who even plays catpeople anyway is this even a thing

**Comment by Shapsy** [comment]
nyaa :+1:

**Comment by MMMiracles** [comment]
s l i p p e r y s l o p e

**Comment by optimumtact** [comment]
also this isn't even a valid descriptor other people can see, it's internal to that mob only, so whoever tried to argue this let them kill people should be thrown under a bus.

**Comment by Cheridan** [comment]
this is stupid

Do other servers even use the term "valid kill"

**Comment by KorPhaeron** [comment]
@RemieRichards 

I made the shittiest pun I could think of I dunno that it really translates well to text though

**Comment by RemieRichards** [comment]
good enough :+1:

**Comment by YakumoChen** [comment]
catbeast furries are literally a Bay-tier race and it's a tradition to murder any you see. This is how /vg/ does it and I've never actually seen one on tg before, probably because it's almost exclusively a /vg/ meme to spawn and murder catbeasts.

**Comment by Memendia** [comment]
@YakumoChen hippie does this too yknow

**Pull request merged**
