### PR TITLE
Peacekeeper Sprite fixes

### PR DESCRIPTION
**Pull request by RemieRichards**
- Peacekeepers now use Eye overlays, which means they close their eyes when they die :(
- Peacekeepers now have Eye overlays for being servants of Ratvar
- Peacekeepers now have Eye overlays for lights but you really can't see them anyway because >white
- Redid some of the shading and lineart colours for Peacekeepers (Some of them bizarrely changed colours between the Animation/Static versions, I don't remember this but probably my fault)

three_eggmigos

### CODE REVIEW

**Comment by xxalpha** [comment]
The eggborg should glow to emit light instead of eye lights.

**Comment by Dorsisdwarf** [comment]
The only way to fix these sprites is to download them onto a USB stick and ritually burn them

**Comment by Zilenan91** [comment]
They still look like they come from a parallel universe and the sprite doesn't fit but fixing it is good

**Comment by coiax** [comment]
Is the eye closed going to be used for stun and death, or just death?

**Comment by Midaychi** [comment]
replace the chest thing near the bottom with a heart

**Pull request merged**
