### PR TITLE
Fixes issue with protected word in MySQL version > 8.0.2

### PR DESCRIPTION
**Pull request by MCterra10**
## About The Pull Request
Fixes small issue that causes MySQL requests regarding admins to fail on MySQL version > 8.0.2.
"rank" is one of the column names in the admin table, but the word "rank" was reserved in recent versions of MySQL. This just adds backticks around the word, and I'm surprised that it wasn't already fixed, so here I am upstreaming it.

## Why It's Good For The Game
Working code is good

## Changelog
:cl:
fix: database requests for admins no longer fail on MySQL version > 8.0.2
/:cl:

### CODE REVIEW

**Comment by optimumtact** [comment]
we dont' use mysql though

**Comment by MCterra10** [comment]
Downstreams, like mine. Also there's literally no downside to having code that works correctly with other database solutions

**Comment by MCterra10** [comment]
Basically, why refuse a change that fixes unintended behaviour for others just because you personally don't come across that issue

**Comment by nfreader** [comment]
The readme specifically states the MySQL is not supported and to use MariaDB.

**Comment by optimumtact** [comment]
I never said I was refusing it

**Comment by MCterra10** [comment]
Mysql works perfectly with this fix, and in my experience I could never get MariaDB to work properly. For me, mysql works BETTER than MariaDB

**Review by SpaceManiac — APPROVED** [review]
We don't test against MySQL and so can't make any promises that the problem won't recur, but this seems fine to me.

**Comment by MCterra10** [comment]
Yeah, mysql works fine if you just change the default charset. I think that's where a lot of people trip up and the reason why it "doesn't work" (correct me if I'm wrong). Good to have this merged to avoid merge conflicts down the road

**Pull request merged**
