### PR TITLE
resprites all soda cans, adds wellcheers juice

### PR DESCRIPTION
**Pull request by CoiledLamb**
## About The Pull Request
this one was a labor of love. all the existing soda cans have been resprited, with the help of @retlaw34 (new top palettes), @Imaginos16 (new top shapes, can palettes), and some original sprites done by @Krysonism (monkey energy, the 13 loko).
you can see the before and afters here: 
image
(now includes crushed cans, and inhands!)
let me know if there's any promotional stuff i should also include in this PR, like if sol dry has a poster somewhere, and i'll go update that with any changes made.

also adds a new drink, idea courtesy of @YesterdaysPromise: 
wellcheers juice!
image
it will make you drowsy, and has a variable affect on your mood
if you are unhappy, it will deal stamina damage
if you are neutral, it will give you a mood boost
if you are happy, it will heal some brute damage

also, six packs of cans have been resprited. can i interest anyone in an alamo? or just a space beer?
image

## Why It's Good For The Game
old can sprites were _crusty_. it was nearly impossible to tell what some of the logos were, and the palettes were dated as well. this tries to keep the logo similar where possible, giving them new life where i can, and sometimes reimagining them. the result is still internally consistent, but much more polished.
## Changelog
:cl:
add: Added wellcheers, a contraband soda with various side effects.
image: resprites all cans in the drinks icon file
image: resprites the canholder sprite in storage.dmi
/:cl:

### CODE REVIEW

**Comment by CoiledLamb** [comment]
> The six pack sprite has definitely needed some love, thank you for your service

shit i should've had a before after for that one too lmao

**Comment by Serxule** [comment]
a lot of these i dont get the changes. changing the 4th one to be some weird symbol rather than steam coming out of a drink? changing the 6th one to be fire? changing the 9th one to remove the balloon and just have a random line? changing the 11th one to just be like a sun rather than what appears to be something implying a race? the 16th one is too boring now.

**Comment by CoiledLamb** [comment]
> a lot of these i dont get the changes. changing the 4th one to be some weird symbol rather than steam coming out of a drink? changing the 6th one to be fire? changing the 9th one to remove the balloon and just have a random line? changing the 11th one to just be like a sun rather than what appears to be something implying a race? the 16th one is too boring now.
> 
> these ones are just downgrades or misinterpretations of what it was, not even arguing for "soul" (although the old sprites arent even bad)

the ones you're mentioning are literally so vague i could not parse them when redesigning them. i'm not even sure you know what they're meant to represent?
the 13 loko and monkey energy were done by kryson, so i'm gonna disregard those if you mentioned them (though 4 lokos generally have cans more like the former)
the pwr game is now shaped like a joystick than a random white line over a yellow bowl
the sol dry one is a sun to draw back to the sol in it's name, rather than whatever the hell it was before (genuinely incomprehensible)
the starkist one had the red bar for some time, but ultimately it didn't fit with the new shading and... wasn't readable at all as a balloon if that's even what it's supposed to be.
the new logos won't hurt you, almost every company changes their logos and can designs with time

**Comment by Dorsisdwarf** [comment]
which is the before and which is the after genuine question

**Comment by RaveRadbury** [comment]
> the ones you're mentioning are literally so vague i could not parse them when redesigning them. i'm not even sure you know what they're meant to represent?  the sol dry one is a sun to draw back to the sol in it's name, rather than whatever the hell it was before (genuinely incomprehensible) 

image

It's Canada Dry, it looks like the can. The creator of the ginger ale would prefer that it remain modeled after Canada Dry

**Comment by CoiledLamb** [comment]
> It's Canada Dry, it looks like the can. The creator of the ginger ale would prefer that it remain modeled after Canada Dry

no offense to the creator but i'm personally much more fond of the sun design than i would be making it a reference to a real world product.

**Comment by RaveRadbury** [comment]
> > It's Canada Dry, it looks like the can. The creator of the ginger ale would prefer that it remain modeled after Canada Dry
> 
> no offense to the creator but i'm personally much more fond of the sun design than i would be making it a reference to a real world product.

the new one looks lower effort.

**Comment by Fikou** [comment]
why the shamblers juice became neon green

**Comment by Serxule** [comment]
> > > It's Canada Dry, it looks like the can. The creator of the ginger ale would prefer that it remain modeled after Canada Dry
> > 
> > 
> > no offense to the creator but i'm personally much more fond of the sun design than i would be making it a reference to a real world product.
> 
> the new one looks lower effort. it stands out as being plainer than all of the other new cans. a lot of the sodas are based on real drinks and have designs that reflect that. it's part of the point of it all, making signs and symbols that relate to irl things so they are comprehendible.

yeah i agree, i didnt want to be the one that said it but it looks very lazy and low-effort, its barely even a design, its just some dots and a circle and doesnt look like itd resemble anything, maybe some cleaning spray i guess (i get that its very limited pixels but its not an excuse)

**Comment by carlarctg** [comment]
Big + on the new drink, it has cute effects that change depending on the mood. I'm a big fan of small little tricks you can pick up like that, and having it have small yet so variable effects on your mood just feels right and satisfying. Honestly makes me want to add effects to all the other bland, boring space cola cans that don't do anything.

**Comment by carlarctg** [comment]
The 'new' sol dry sprite is fine. It looks nice and clean, if maybe a bit lacking in detail, but the old one is pretty much completely unintelligible and a pixellated mess because, shocker, real life elaborate can designs designed to catch your attention don't translate to tiny 4x8 pixel art.

Let's not nitpick what every single Can looks like?

**Comment by CoiledLamb** [comment]
> why the shamblers juice became neon green

it's the eldritch version, the og shamblers is still ourple

**Comment by CoiledLamb** [comment]
also the sol dry is my favorite new logo of the lot so callin' it low effort is not really swaying me on redesigning it, i'll be honest. sometimes a simpler design is better. not everything has to exactly resemble an irl product in this sci fi game set 500 yrs in the future

**Comment by potato1234x** [comment]
why are a few slightly different cans so controversial

**Comment by Serxule** [comment]
> also the sol dry is my favorite new logo of the lot so callin' it low effort is not really swaying me on redesigning it

"i like it" isnt really an argument, at all, just because you like it doesnt make it good, or change the fact that its boring and low-effort

**Comment by potato1234x** [comment]
> also the sol dry is my favorite new logo of the lot so callin' it low effort is not really swaying me on redesigning it, i'll be honest. sometimes a simpler design is better. not everything has to exactly resemble an irl product in this sci fi game set 500 yrs in the future

I think it's pretty neat tbh canada dry looks boring

**Comment by CoiledLamb** [comment]
> > also the sol dry is my favorite new logo of the lot so callin' it low effort is not really swaying me on redesigning it
> 
> "i like it" isnt really an argument, at all, just because you like it doesnt make it good, or change the fact that its boring and low-effort
since I did the resprite, you would have to convince me that it's worth changing due to your complaints for me to actually bother with it. and like I said, no matter how boring or low effort you think it is, I like it. as long as y'all keep trying to tear it down, I'll be satisfied with it, so maybe change your plan of attack or take up sprite art if you want something different.

**Comment by Jacquerel** [comment]
> "i like it" isnt really an argument, at all, just because you like it doesnt make it good, or change the fact that its boring and low-effort

"I don't like it" isn't an argument either, ultimately when it comes down to who does or doesn't like a sprite then there's no further point to the discussion and the spritetainers will decide. You can always submit your own can later.

**Comment by RaveRadbury** [comment]
> as long as y'all keep trying to tear it down, I'll be satisfied with it,

Bizarre take, good luck making friends around here with the attitude you've demonstrated in this PR.

Anything anybody dislikes will get changed in a month or two anyway.

Great work on most of the new cans.

**Comment by CoiledLamb** [comment]
> > as long as y'all keep trying to tear it down, I'll be satisfied with it,
> 
> Bizarre take, good luck making friends around here with the attitude you've demonstrated in this PR.
> 
> Anything anybody dislikes will get changed in a month or two anyway.
> 
> Great work on most of the new cans.

i have plenty of friends here :P and i don't want to make friends with people that don't value the work i put in to my sprites. if you think my work is boring and low effort, so be it.

**Pull request merged**
