### PR TITLE
Unused Traitor Items: Powerfist

### PR DESCRIPTION
**Pull request by Iamgoofball**
not enough damage tbh, 3% usage

### CODE REVIEW

**Comment by KorPhaeron** [comment]
target.apply_damage(force * fisto_setting, BRUTE)

So that means 60 damage a hit on the higher settings

**Comment by Cheridan** [comment]
I believe that esword is also 60 damage, and it doesn't require refilling and is also a shield.

**Comment by KorPhaeron** [comment]
it's only 30 you baka

**Comment by Cheridan** [comment]
That's weird, I swear I got put into crit in two hits by one the other day.

**Comment by PKPenguin321** [comment]
This thing is now a gas powered revolver and I'm okay with that

**Pull request merged**
