### PR TITLE
Makes is_type helpers inline

### PR DESCRIPTION
**Pull request by AnturK**

### CODE REVIEW

**Comment by AnturK** [comment]
Alright, how to solve this hmm

**Comment by phil235** [comment]
Just change the issilicon() and iscarbon() in that one file into istype(A, /mob/living/carbon). It's the easiest solution.

**Comment by MrPerson** [comment]
This is realistically going to have no gains so I dunno why you bothered

**Comment by AnturK** [comment]
Someone was complaining about lookup overhead on these, which is kinda silly thing to worry about but it's 10 min of work so eh.

**Comment by AnturK** [comment]
```
/mob/guy
	name = "Guy"

/proc/isguy(A)
	return istype(A,/mob/guy)

#define inline_isguy(A) (istype(A,/mob/guy))

/mob/verb/test_standard()
	var/mob/A = new/mob/guy
	var/result
	for(var/i=1,i<9999999,i++)
		result = isguy(A)
	world << result

/mob/verb/test_inline()
	var/mob/A = new/mob/guy
	var/result
	for(var/i=1,i<9999999,i++)
		result = inline_isguy(A)
	world << result
```

Profile results (average time)

Proc Name           |       Self CPU   | Total CPU  |  Real Time   | Calls
-----------------------  |  ---------  |  ---------  |  ---------  |  ---------
/mob/verb/test_standard  | 12.299   |    15.833   |    15.833     |       2
/mob/verb/test_inline      |    5.275    |    5.275     |   5.275     |       2
/proc/isguy         |           0.000    |    0.000  |      0.000    | 19999996

**Comment by AnturK** [comment]
This obviously not a realistic use case

**Comment by MrPerson** [comment]
Source: http://pastebin.com/raw.php?i=Cc3m9Agd

Objects SS fired 2040 times. It fires once every 2 seconds, so this covered 4080 seconds. Our framerate is 11 frames/second so this was 4080 * 11 = 44880 frames. ishuman was called 321963 times. 321963 / 44880 ~= 7.1 calls per tick.

The only other helpers to register:
isAI()
166725 ~= 3.7
isliving()
940295 ~= 21
isobserver()
74693 = 1.7

At 0.000 000 764 95 seconds per call  for a proc vs 0.000 000 263 75 seconds per call for inline, the savings per call is 0.000 000 501 20 per call. With 33.5 calls per tick, that's an average of 0.000 016 8 seconds saved per tick. Since some ticks are worse than others and we care more about worst-case scenarios, let's say some tick has 100 times the normal workload. That's still merely 0.001 68 saved total.

I probably spent more time doing all that useless ass math than it took you to do this whole PR.

**Comment by Dorsisdwarf** [comment]
TL:DR Mrperson spent more time writing that out than this would save computer time in *the entire probbable lifespan of tgstation*

**Comment by Cheridan** [comment]
A very small performance gain is still a performance gain, though

**Comment by Razharas** [comment]
Nothing wrong with this

**Comment by KorPhaeron** [comment]
And now I gotta fix merge conflicts as well aaaa

**Pull request merged**
