### PR TITLE
Add halite mining types

### PR DESCRIPTION
**Pull request by octareenroon91**
Halite, commonly known as rock salt, is a type of salt, the mineral (natural) form of sodium chloride (NaCl).

:cl:
add: Miners may now find rock salt among other mineral wealth.
/:cl:

Proposing to add rock salt (sodium chloride) types to the mineral turfs. They will yield salt piles and/or white, salt-yielding ash piles.

More is needed but my battery is close to dying.

Also I want to know if anyone truly hates this idea.

### CODE REVIEW

**Comment by Potato-Masher** [comment]
>Down here, salt is a way of life.

Good way to get more salt on the station I suppose. Also, your a monster for making it have the same texture as diamonds, you know that?

**Comment by DaedalusGame** [comment]
I'm not really sure how salt is a limited resource on the station so I'm gonna assume this is a joke pr that just adds fake diamond ore?

**Comment by AdamElTablawy** [comment]
>shoot what looks like diamond

>get salt

fund it

**Comment by ExcessiveUseOfCobblestone** [comment]
someone wanted to hide the gibtonite as diamond ore as well, that didn't go over so well.

**Comment by Kromgar** [comment]
@Potato-Masher fuck you

**Comment by Kromgar** [comment]
@AdamElTablawy Fuck you

**Comment by epochayur** [comment]
alright but why

**Comment by Hatfish** [comment]
one step closer to making lavaland proper dorfy, unique rock strata when?

**Comment by Tlaltecuhtli** [comment]
for what purpose

**Comment by ACCount12** [comment]
No. We have enough salt in SS13 as it is.

**Comment by Buggy123** [comment]
Only do this if it has some value in the ORM and it doesn't have the diamond sprite.

**Comment by Teepeepee** [comment]
New rev fighting meta, just dump your saltload on station. Is this a sister PR with #35369?

**Comment by octareenroon91** [comment]
The salt-mine shuttle inspired me.


> Also, you're a monster for making it have the same texture as diamonds, you know that?

It's terribly cruel. I mostly copied diamond so blatantly because I was in a hurry, though.

>value in the ORM

Yes I like that.

**Comment by ChangelingRain** [comment]
salt should look like diamonds, but greyscale, which I think would be fair since then it only looks sort of like diamond, and thus only salty for unobservant miners.

**Comment by Kromgar** [comment]
I really don't see the point of it. What use is anyone but chem going to have for bricks of salt?

**Comment by improvedname** [comment]
Maybe the chef???

**Comment by kevinz000** [comment]
:-1: dilutes mineral spawns unless i'm understanding this wrong i didn't read mineral spawning code.

**Comment by Hatfish** [comment]
Minerals spawn so frequently that it's a nonissue catboy.

**Comment by ExcessiveUseOfCobblestone** [comment]
just upgrade orm to t4 :^)

**Comment by Kromgar** [comment]
But yeah it does dilute mineral spawns. I'd be cool if it was something that ACTUALLY HAS A USE. 


Like maybe copper ore so that now cable coils need copper to be made

**Comment by Buggy123** [comment]
But cable coils are superconductors, they're probably _not_ made from (just) copper.

**Comment by DaedalusGame** [comment]
yeah no they're made from glass and iron

**Comment by Teepeepee** [comment]
according to this https://tgstation13.org/wiki/Guide_to_Ghetto_Chemistry they grind into copper, what kind of transmutation from iron and glass to copper has nanotrasen discovered!?!?

**Comment by KorPhaeron** [comment]
Dilutes mineral spawns for a silly joke

**Comment by octareenroon91** [comment]
I hadn't even touched the spawn parameters yet.

**Comment by KorPhaeron** [comment]
I just cant imagine it ever being worth digging up salt. Cant you make it in chem dispensors?

**Comment by octareenroon91** [comment]
I mean, yeah, it's a joke, and you can make it easily in the chem lab. Might be good thematically for the gulag though.

>Before the advent of the modern internal combustion engine and earth moving equipment, mining salt was one of the most expensive and dangerous of operations, due to rapid dehydration caused by constant contact with the salt (both in the mine passages and scattered in the air as salt dust), among other problems borne of accidental excessive sodium intake. While salt is now plentiful, until the Industrial Revolution it was difficult to come by, and salt mining was often done by slave or prison labor and life expectancy among those sentenced was low.

https://en.wikipedia.org/wiki/Salt_mining

**Pull request closed without merging**
