### PR TITLE
New Morgue Icons and Display Screens + New Crematorium Icons

### PR DESCRIPTION
**Pull request by Chuckleberry-Finn**
:cl: Jittai
New Morgue Tray sprites: Color coded lights now bigger, better, and with displays.
New crematorium sprites.
/:cl:

A continuation of: #2242 and improvement on: #12898.

lirijmh
morgue

crema old
crema

chapel

### CODE REVIEW

**Comment by KomradeSpectre** [comment]
>Inb4 someone complains about this ruining their traitor gimmicks.
I like the look, much more noticeable than the tiny lights only.

**Comment by uraniummeltdown** [comment]
This is kind of ugly
You should make the cross the morgue light

**Comment by ChuckTheSheep** [comment]
Changed the green to match ingame colors more.
yhmkixo

**Comment by ChuckTheSheep** [comment]
Rather than butcher the old messy icons I tried to redo them while maintaining the look + the displays. CC welcome.

**Comment by ChuckTheSheep** [comment]
Going to tweak them later a bit more. Also noticed crematoriums have identical artifacts/noise so I'll try to clean those up too.

**Comment by LetterN** [comment]
it looks a bit more blocky than a cylinder.

**Comment by ChuckTheSheep** [comment]
I'm not sure how to fix the conflict, but I downloaded the latest file and replaced my dmi with it, then imported my changes. Also updated the morgue icons a bit- preview updated above.

**Comment by ChuckTheSheep** [comment]
Happy with the results.

**Comment by ChuckTheSheep** [comment]
I messed up the commits. I'll fix it later today.

**Pull request closed without merging**
