### PR TITLE
Fixes space movement

### PR DESCRIPTION
**Pull request by MrsTonedOne**
Fixed some issues with space movement, namely that it didn't trigger when something moved of its own accord after it was already scheduled to get space moved.

:cl: 
fix: Fixed space/nograv movement not triggering when atoms moved twice quickly in space/nograv
/:cl:

### CODE REVIEW

**Review by MrsTonedOne — COMMENTED** [review]
10/10

**Review by MrsTonedOne — COMMENTED** [review]
You can't actually delete or edit reviews can you?

**Comment by Jalleo** [comment]
Nope. I think.

**Review by Razharas — COMMENTED** [review]
image

**Comment by Razharas** [comment]
The possibilities for the prgriff are ENDLESS

**Comment by optimumtact** [comment]
They literally can't stop breaking things

**Pull request merged**
