### PR TITLE
Revert "Excellent Goof Change"

### PR DESCRIPTION
**Pull request by lzimann**
Reverts tgstation/-tg-station#16421

There is no reason to change this and we are perfectly capable of TEST MERGING
[Forums thread about this](https://tgstation13.org/phpBB/viewtopic.php?f=10&t=6307)

### CODE REVIEW

**Comment by Supermichael777** [comment]
their is no reason to revert before rounds are actually played. quit memeing

**Comment by Cheridan** [comment]
>There is no reason to change this

grabs were literally broken, bugged and escapable.

**Comment by Lumipharon** [comment]
What was that thing coders always say...?

Don't try merge balance changes with bug fixes?
Yeah, ok, lets just ignore that to sneak in huge ass nerfs.

**Comment by duncathan** [comment]
OK there's no need to knee jerk revert
We can give this another chance after we've actually had time for feedback

**Comment by Iamgoofball** [comment]
@Lumipharon 
the bugfix was a side effect of the balance changes, where was it pretending to be a bug fix

**Comment by duncathan** [comment]
We didn't ignore that
You can't try to tell me that the bug fix wasn't a nerf in the first place

**Comment by Lumipharon** [comment]
Wait what, he removed the perma stun on the actual CHOKE hold? Literally what is the point of it even existing if it doesn't stun then?

Literally
For
what
purpose

**Comment by Iamgoofball** [comment]
@Lumipharon uh, there's permastun on the choke-out still

permastun on the neck grab is not though

**Comment by PKPenguin321** [comment]
good luck ever getting the choke out with 4 quadrillion years of GOOFBALL™ GRAB DELAY on top of the already existing 8 gorillion years of delay between chokehold and choke-out

why goofball why do you do these things? i had more faith in you than this

**Comment by Lumipharon** [comment]
if only we could like, test terrible changes so we can realise that they're terrible and not merge them.
Oh well, that would be crazy.

**Comment by PKPenguin321** [comment]
for the record i'd rather have this merged than https://github.com/tgstation/-tg-station/pull/16468

**Comment by Iamgoofball** [comment]
@phil235 Merging this will unfix grabs being inescapable after you hit neck grab stage.

**Comment by Lumipharon** [comment]
Then don't put bug fixes in with balance changes.

Also I thought, and probably most other people thought, that that was a feature, not a bug - atleast it's not 100% useless prenerf.

**Comment by Iamgoofball** [comment]
then why don't we just use @PKPenguin321's rebalance PR instead of this

**Comment by PKPenguin321** [comment]
Because grabs will still be garbage with that, the only reason I didn't completely undo your garbage values is so it wouldn't get instaclosed

**Comment by Iamgoofball** [comment]
no, grabs wont be garbage with that PR, they'll be good still

**Comment by Lumipharon** [comment]
Well if you say so goof.

**Comment by Cheridan** [comment]
#16468 got merged

**Pull request closed without merging**
