### PR TITLE
Reduces roundstart paycheques from 5 to 1

### PR DESCRIPTION
**Pull request by cacogen**
## About The Pull Request

There's too much money on the station. This means it has no leverage over other players. This aims to alleviate that to some degree.

Basically means it takes 20 minutes longer to 'earn' the same amount as before.

| Five Roundstart Cheques |            |            |            |            |            |
|-------------------------|------------|------------|------------|------------|------------|
| **Paygrade**                | **Pay cheque** | **Roundstart** | **20 minutes** | **40 minutes** | **60 minutes** |
| PAYCHECK_ASSISTANT      | 25 cr      | 125 cr     | 225 cr     | 325 cr     | 425 cr     |
| PAYCHECK_MINIMAL        | 75 cr      | 375 cr     | 675 cr     | 975 cr     | 1275 cr    |
| PAYCHECK_EASY           | 125 cr     | 625 cr     | 1125 cr    | 1625 cr    | 2125 cr    |
| PAYCHECK_MEDIUM         | 175 cr     | 875 cr     | 1575 cr    | 2275 cr    | 2975 cr    |
| PAYCHECK_HARD           | 200 cr     | 1000 cr    | 1800 cr    | 2600 cr    | 3400 cr    |
| PAYCHECK_COMMAND        | 250 cr     | 1250 cr    | 2250 cr    | 3250 cr    | 4250 cr    |

| One Roundstart Cheque   |            |            |            |            |            |
|-------------------------|------------|------------|------------|------------|------------|
| **Paygrade**                | **Pay cheque** | **Roundstart** | **20 minutes** | **40 minutes** | **60 minutes** |
| PAYCHECK_ASSISTANT      | 25 cr      | 25 cr      | 125 cr     | 225 cr     | 325 cr     |
| PAYCHECK_MINIMAL        | 75 cr      | 75 cr      | 375 cr     | 675 cr     | 975 cr     |
| PAYCHECK_EASY           | 125 cr     | 125 cr     | 625 cr     | 1125 cr    | 1625 cr    |
| PAYCHECK_MEDIUM         | 175 cr     | 175 cr     | 875 cr     | 1575 cr    | 2275 cr    |
| PAYCHECK_HARD           | 200 cr     | 200 cr     | 1000 cr    | 1800 cr    | 2600 cr    |
| PAYCHECK_COMMAND        | 250 cr     | 250 cr     | 1250 cr    | 2250 cr    | 3250 cr    |

## Why It's Good For The Game

Makes money more scarce. Scarcity adds value. Value gives money leverage over other players.

## Changelog
:cl: cacogen
balance: Roundstart paycheques are now 1 instead of 5
/:cl:

### CODE REVIEW

**Review by Cyberboss — APPROVED** [review]
I maintain spessmans to avoid real life problems reeee

**Comment by TiviPlus** [comment]
Implement inflation when

**Comment by Bokkiewokkie** [comment]
Rip the dream of buying insulateds at the machine as an assistant

**Comment by RaveRadbury** [comment]
How do you think this is going to affect usage of the coin press?

**Comment by cacogen** [comment]
My hunch is not by a lot. I never see anyone taking advantage of it and this only puts you 20 minutes further back at roundstart. Something should be done about the values of certain not very rare yet still valuable minerals (e.g. plasma) to make the coin press cause less inflation, but not in this pull.

**Comment by Shadowflame909** [comment]
Reminder that Botany Mains are the ones who are affected by PRs like this

They already can only buy 1 strange seed.

What do you want them to do, rob the captain?? Because yet again 20 minutes later still no cash to buy the ammonia/strange-seed/diethylamine

Bump them up to paycheck hard please.

**Comment by gitbirb** [comment]
> Reminder that Botany Mains are the ones who are affected by PRs like this
> 
> They already can only buy 1 strange seed.
> 
> What do you want them to do, rob the captain?? Because yet again 20 minutes later still no cash to buy the ammonia/strange-seed/diethylamine
> 
> Bump them up to paycheck hard please.

I agree with this, it's absolutely gonna crush botany's will to live with how expensive seeds are now if this change goes through.

**Comment by SkeletalElite** [comment]
> > Reminder that Botany Mains are the ones who are affected by PRs like this
> > They already can only buy 1 strange seed.
> > What do you want them to do, rob the captain?? Because yet again 20 minutes later still no cash to buy the ammonia/strange-seed/diethylamine
> > Bump them up to paycheck hard please.
> 
> I agree with this, it's absolutely gonna crush botany's will to live with how expensive seeds are, if this change goes through they wouldn't even be able to have much in the first place.

Maybe just reduce the price of seeds

**Comment by trollbreeder** [comment]
Bump up the paycheck of assistants. They get way too little. I'd suggest making them minimal and removing the assistant paycheck type.

**Comment by Fikou** [comment]
ah yes, assistants now at 1 hour will have as much money as clown and mime had at roundstart

**Comment by Time-Green** [comment]
This is also a massive kick in the gut to chemists getting the reinforced plunger for lavaland. It used to be a 10 minute moment for them to make some basic meds before they could fuck off, now they need to wait around 40 minutes 

There are quite some vendor items that need adjusting, or it’s gonna be an in-game burning rollercoaster

**Comment by Pugie** [comment]
Haha yes lets take money out of circulation so economy is bolstered by....

People not having money to trade without raiding vault or using coin press?

**Comment by ATH1909** [comment]
> Haha yes lets take money out of circulation so economy is bolstered by....
> 
> People not having money to trade without raiding vault or using coin press?

I mean, to be fair, they could just trade proportionally less money? Or just give up on being able to buy anything from vendors and donate all of their money to other people who really want to buy things?

**Comment by Tlaltecuhtli** [comment]
cargo will be less interested into selling items instead of communism because now there will no one able to afford anything without selling with loss  if you want to  half how much everyone gets then half all the prices  
for example the cheapest crates like 1 single glov cant be bought by even the cap within 30 min this just gives more reasons for crew to steal shit or expect to be free 
expecting "yeah this man is gonna sell bananas to 20 people to afford a insul crate" was hard  when you had to sell them to 2 people imagine now, you are better off bartering steel cubes to cargo  like a fucking primitive
if you are balancing it over coca cola cans in the vendors then i ll just lmao at you

**Comment by interestingusernam3** [comment]
>Maybe just reduce the price of seeds

Maybe, instead of that, just don't. Maybe then competent botanists will actually grow food/actually cool plants and do cargo bouties instead of growing deathnettles and bluespace tomatos with random shit from strange seeds in them every round because le funny anteg plant xdddddddd.

**Comment by cacogen** [comment]
@Shadowflame909 
@Time-Green
I'm not concerned if 'luxury' or optional items are harder to get given that the entire point is to make money have value between players. Right now money is mostly unused and becomes completely superfluous after a certain point in the round.

>Reminder that Botany Mains are the ones who are affected by PRs like this

Figure out ways to make money to afford the strange seeds that you don't actually need, even to make fun plants. Sell things to the crew instead of giving them away. Diethylamine and ammonia can be made with the mandatory chem dispenser anyway.

@Pugie 
It's a 20 minute setback. There'll still come a point where players' bank accounts are filled with thousands of credits they have no reason to spend. Just 20 minutes later.

@trollbreeder 
Based on experience, I agree assistants should be paid more. I definitely do not feel that way about PAYCHECK_MEDIUM jobs or higher. I'll have to think about whether adjusting assistants' pay cheques is in the scope of this pull or not.

@interestingusernam3 
Your dislike of hydroponics having fun instead of just growing produce for the cook is irrelevant.

**Comment by Mickyan** [comment]
> It's a 20 minute setback. There'll still come a point where players' bank accounts are filled with thousands of credits they have no reason to spend. Just 20 minutes later.

I'd rather you lowered the paychecks to actually solve this. If the problem the money intake being too high that's what needs to change, not the amount of money you start with

**Comment by Tlaltecuhtli** [comment]
@cacogen as example for  medbay means you dont even need to buy the "luxury" vendor items cause the lathe can print em for free, you ll need 6 people paycheck to buy a pinpointer so instead of having to choose a better round start pinpointer but no money to get nuka cola / grey bull / etc you just wait for magic lathe to have everything for free; 

20 min is pretty much the reason there are some items printable items on vendors so you can pay for em instead of the timegate lathes have

**Comment by nianjiilical** [comment]
has anybody ever floated the idea of quadrupling the paychecks, making them only happen every 10 minutes, and giving everyone different amounts of roundstart money

just throwing that out since people talk about time gates a lot

**Comment by Shadowflame909** [comment]
>Why don't you just sell things to the crew bro... Just increase the economy

Hmm..good idea.

Maybe it'd work if I could actually afford all the cool contraband items to sell, like fly amanita, or cannabis.

**Comment by cacogen** [comment]
You don't need premium items to make valuable produce as hydroponics.

**Comment by MrPerson** [comment]
If botany is actually unable to buy what they "need", the proper solution would be decreasing the cost of that shit, not giving them more money. That's how power creep happens.

**Comment by Shadowflame909** [comment]
> 
> 
> You don't need premium items to make valuable produce as hydroponics.

You're just saying "Departmental Cooperation so you can actually buy seeds"

We both know no one's paying 250 bucks for that watermelon! (The price of a seed)

300 for a bottle of diethylamine.

Especially not after this PR's great money nerf.

**Comment by ExcessiveUseOfCobblestone** [comment]
If the issue is "at some point money becomes useless", that probably says more about the money/paycheck moreso than the roundstart paycheck.

**Comment by Spepbuthewranglesgithub** [comment]
my poor, poor roundstart techpriest robes.

**Comment by cacogen** [comment]
Originally I was going to adjust pay cheque values but I'd assumed this would be easier to get merged and that the values @Mickyan had arrived at in #48174 were pretty set in stone due to balance. Given they're okay to see them change and that I agree with @ExcessiveUseOfCobblestone that nerfing roundstart pay cheques won't do a lot of solve the problem I'm going to close this in favour of trying to reduce pay cheques at some point in future (assuming someone else doesn't beat me to it). Roundstart pay cheques could be increased to compensate for the reduction (although I believe the amount most jobs start with is too much).

**Comment by Mickyan** [comment]
Increasing the amount of starting paychecks and reducing paycheck amounts seems like the best way to go forward as it flattens the curve of how much money is available on the station but leaves people with a decent amount of money to spend in the early round

If you need a spreadsheet for calculations you can use this, just make a copy to edit it
https://docs.google.com/spreadsheets/d/1lTshSWkaCmrQ7O9Fw6aUXx7XeRkKrMZkpow3qBSuumw/edit?usp=sharing

I put in some numbers to show how you can have roughly the same current roundstart cash and hit the amount you listed at the 60 minutes mark with your adjusted paychecks. It's only a quick example though I haven't put too much thought into this

**Pull request closed without merging**
