### PR TITLE
[speedmerge] Repairs A Handful Of Issues With Icebox

### PR DESCRIPTION
**Pull request by unit0016**
## About The Pull Request
I booted up strongdmm to try to find something to improve, and instead I got a waking nightmare.

It turns out somewhere along the lines in Icebox's underground section, someone didn't find out that hollow reinforced window spawners existed, and it SPREAD. So every single hollow window down there was using handplaced grilles under handplaced windows under...
That's bloat. And annoys me. And makes it harder to see under the tile.

*And*.

All planetary turfs under airlocks? Gone. Firelocks under airlocks? Gone. Weird shit with how /area/s were defined? That's right, gone. Icebox's middle z-level moat? Back, actually - doesn't get cut off by generation anymore thanks to /area/ issues. Airlocks without cyclelinks? Gone. The nukie ship navigation console? Functional again. That SPACE TILE underneath Port Quarter Solars? Yeah. Gone. The walls underneath the windows in the locker room? Gone.

I need a drink and some sleep, this was *not* the PR to work on at this hour.

## Why It's Good For The Game
I would prefer if the standby "This is /tg/ or /tg/-derived" map actually worked, thanks

## Changelog

:cl:
fix: A handful of issues on icebox, pertaining to /area/s, firelocks, airlocks, mapping helpers, mapping mistakes, a literal space tile, and more have been squashed!
fix: You can actually move the Syndicate Infiltrator's docking position on icebox again. Yeah. I know.
/:cl:

### CODE REVIEW

**Comment by Son-of-Space** [comment]
Looks good - thanks for the fixes!

Next time please come prepared with feedback instead of a rant, we all want to make the game better.

Having cyclelinks in the brig checkpoint is not my intent. Having them on the door to the bridge and the warden's office is a good add, though.

**Comment by unit0016** [comment]
> Having cyclelinks in the brig checkpoint is not my intent. Having them on the door to the bridge and the warden's office is a good add, though.

I'll drop the one on the front door, then.

**Comment by unit0016** [comment]
Thank you merge conflicts, very cool!
image

**Comment by unit0016** [comment]
I made a fun discovery: Public mining storage was off by one tile. And also distributed it's power to an absurd amount of the wastes while it was at it, through what I'm not unconvinced was a reused icon moment.

That's fixed.

**Comment by unit0016** [comment]
I'd like to thank god for mapmerge2 because without it this PR'd be even more of a trainwreck than it already has been

**Pull request merged**
