### PR TITLE
Adds Trigger guard mod to free golem vendor

### PR DESCRIPTION
**Pull request by Supermichael777**
:cl:
add: Free golem vendor now sells trigger guard mods for 100 mining credits
/:cl:

Having a whole list of things that are worthless to you sucks.

### CODE REVIEW

**Comment by Xhuis** [comment]
triggered

**Comment by GunHog** [comment]
I am fine with this, but please do note that golems can already access this item once they construct their own R&D.

**Comment by Repukan** [comment]
>Giving the creatures with extra armor and brute resistance ranged damage

They can already gimp the Colossus with sand, why are you making it easier for them to just become cheap second lives?

What's next, re adding the stimpacks to their vendor only so they don't have to suffer slowdown by 500 points?

**Comment by Supermichael777** [comment]
its because half the fucking list is ka mods yet they can't use them untill they get 3000 points and go all the way up science

**Comment by Repukan** [comment]
Wow you mean the role to learn fucking RnD is gimped when they don't do RnD?

Color me.fucking surprised

**Comment by Supermichael777** [comment]
if you want to learn rnd play science

**Comment by Repukan** [comment]
Cool, then we can drop the pretense of ghost roles being created to learn and remove pod people, golems and the space bar?

**Comment by Repukan** [comment]
Syndie base too since it was added to learn Virology and chemistry.

**Comment by XDTM** [comment]
Hold up, they used to have it in the vendor even before it got into rnd, when were they even removed?

It definitely should not cost 100 credits tho, that's basically free.

**Comment by KorPhaeron** [comment]
Repukan is right

**Comment by Thunder12345** [comment]
Go do RnD you lazy shit

**Comment by Supermichael777** [comment]
@XDTM your paying for the KA anyway and its literally a waste without this.

@KorPhaeron im dumb a super overpiced version is avalible

**Pull request closed without merging**
