### PR TITLE
fixes issue with ghosts being able to affect the world, oversight from the crossed refactor

### LINKED ISSUE #59009: Ghosts are seemingly able to interact in ways they shouldn't
## Round ID:
[161960](https://scrubby.melonmesa.com/round/161960)

## Testmerges: 
#58983 

## Reproduction:
So currently, you can do two very annoying things as ghost. First, you can walk up and down bananium tiles as a ghost, and it'll produce the honk sound effect as if you're walking over it. You can also stand around motion-sensitive cameras to prank poor AIs for some unknown reason.

### PR DESCRIPTION
**Pull request by Kylerace**
## About The Pull Request
fixes #59009

abstract_move() is meant to replace dumb overrides of forceMove() for things that arent supposed to affect the world, camera mobs had this already but ghosts didnt, now they do!

repurposed branch btw

## Why It's Good For The Game
fix

## Changelog
:cl:
fix: After a series of thorough exorcisms, Nanotrasen would like to assure Space Station 13 that ghosts both do not exist and if they did exist can no longer affect the material plane by spamming the fuck out of squeaky noises from bananium floors
/:cl:

### CODE REVIEW

**Comment by Kylerace** [comment]
not a refactor

**Comment by Kylerace** [comment]
also i caused this bug

**Comment by ATH1909** [comment]
that changelog is kind of a bruh moment- the chaplain literally starts with a camera that can take pictures of ghosts to provide hard evidence of their existence

**Comment by Kylerace** [comment]
> that changelog is kind of a bruh moment- the chaplain literally starts with a camera that can take pictures of ghosts to provide hard evidence of their existence.

Wow what a mystery! Why would nanotrasen continue to deny the existence of ghosts?

**Comment by NanoCats** [comment]
Sad, I kinda wish we could have ghosts that subtly haunt the station, and you can like, periodically do a couple small things to freak people out like flicker lights.

**Comment by Kylerace** [comment]
> 
> 
> Sad, I kinda wish we could have ghosts that subtly haunt the station, and you can like, periodically do a couple small things to freak people out like flicker lights.

that used to be in the game until people realized you could use ghosts to find out who the traitors are

**Review by ninjanomnom — APPROVED** [review]

**Review by ninjanomnom — APPROVED** [review]

**Pull request merged**
