### PR TITLE
Replaces the obsolete alien brain necropolis loot with a new artifact.

### PR DESCRIPTION
**Pull request by DreamwalkerSisyphe**
:cl: The Dreamweaver
del: The obsolete alien brain has been removed from the necropolis chest loot.
add: Nanotrasen's lavaland research team has discovered that in it's place is a mysterious new artifact with the ability to project the user's soul. Nanotrasen advises against any attempted use until they can fully research the effects of the artifact on the mind.
/:cl:

This replaces the obsolete alien brain in the necropolis loot table with a new item that allows the user to "project their soul" out of their body at the cost of periodic and semi-random brain damage. Right now its balanced so using it for an amount of time long to gather any significant info can seriously fuck your head up. I'm open to balance tweaks. The sprite is also a WIP so if someone has a better one, i'll take it.

[why]: This takes care of #35942 without simply just shortening the loot table, and by extension adds some new life to mining.

### CODE REVIEW

**Comment by Repukan** [comment]
Too OP.

**Comment by RandomMarine** [comment]
Discount scrying orb available in any game mode.
That's just going to cause a lot of problems.

**Comment by TheDreamweaver** [comment]
Given that by the time you gather any useful information you have a good chance of having severe, debilitating, surgery-needed-to-remove traumas, I' d say its not as OP as you think. But i'm open to balance tweaks.

**Comment by Repukan** [comment]
Just make another eye of God esque item that gives you the ability to see in the dark or see ghosts.

A miner with a couple of legion souls can instantly hunt for valids easily with this item.

**Comment by TheDreamweaver** [comment]
What if I upped the damage amount? Right now youre taking on average one damage per second. An alternate, but more complex solution, would be to create my own custom spirit mob instead of using ghostize(), which would allow the user to still "project their spirit" without getting access to dead chat.

**Comment by Repukan** [comment]
You could still see through walls, see what people are wearing, see mob list, and such and so on.

I don't know much about coding but it seems like a pain in the dick to code what you're suggesting.

**Comment by TheDreamweaver** [comment]
It would essentially be like the Imaginary Friend mob from the special braintraumas, but without the distance limit.

**Comment by Repukan** [comment]
Maybe make it dust you if you die with the soulless effect so it becomes a double edged sword when you use it.

Either you work with someone to make the most of the limited time available to use it (or prepare accordingly) or you lose yourself to the extreme strain of incorporeal gazing.

**Comment by XDTM** [comment]
Idea: make it so it lets you possess simple animal instead of ghosting you

**Comment by TheDreamweaver** [comment]
@Repukan That could also work. Especially since many if not all of the brain traumas can leave you in a very vulnerable position, especially the severe ones. If enough people really think it needs rebalancing, I think I'll implement that and also bump up the brain damage threshold.

**Comment by TheDreamweaver** [comment]
Also in case it wasn't clear, this was suppose to be astral projection themed.

**Comment by TheDreamweaver** [comment]
I just had a better idea. By default, if used, the item will do brain damage to you so fast that you'd be beyond a complete vegetable within a moment. But, by feeding it brains, you can "stabilize the soul projection". So the more brains you feed it, the less damage it does per cycle.

Is it possible to pass additional parameters to a status effect?

**Comment by TheDreamweaver** [comment]
Even with legions souls, they'd still need to get at least a brain or two, otherwise they'd be paralyzed vegetables before they could even apply the legion soul.

**Comment by XDTM** [comment]
Ghosting isn't a great mechanic no matter how much you cripple the user, it is not meant to be accessed by anyone but observers. Every time ic ghosting is added it becomes harder to add observer qol features, like seeing borg laws, since it becomes a significant buff to ic ghosting.

**Comment by TheDreamweaver** [comment]
@XDTM If I went the custom spirit approach in order to avoid ghost issues (think imaginary friend style mob) do you think you could help me figure it out, since Im still fairly new to Byond code and wasn't expecting to touch custom mobs, and since you had a part in the Imaginary Friend creation.

**Comment by TheDreamweaver** [comment]
Im think of making a mob that looks like transparent version of the user (fitting with the astral projection aesthetic) and isnt bound nor effected by the world around it (nor can it effect said world). It would also need an ability that returns the user back to its original body.

**Comment by PKPenguin321** [comment]
so like the scout guardian spirit but it's yourself

**Comment by TheDreamweaver** [comment]
@pkpenguin321 not familiar with it, but it sounds like yes, that. I'll have do more research tommorow after I get some rest.

**Comment by ExcessiveUseOfCobblestone** [comment]
It doesn't matter how crippled the miner is if he ; GEORGE MELONS IS A LING when the rest of the station also benefits from the ghost knowledge.

make it a discount legionaire tele like Leoric's E on HoTS where you're immune to stuns and can teleport but not through terrain.

**Comment by TheDreamweaver** [comment]
Since I don't know how to add new commits to an already open PR, and there is quite a few tweaks to be made, I'm going to close this PR, and create a new one once I have things worked out better.

**Comment by praisenarsie** [comment]
> I don't know how to add new commits to an already open PR

find out sooner rather than later

**Comment by AlexTheSysop42** [comment]
just commit to the branch you're pulling from I think

**Comment by DaedalusGame** [comment]
this but unironically

**Comment by TheDreamweaver** [comment]
Oh it's that easy? Wowzers

**Comment by TheDreamweaver** [comment]
As Gandalf stated before the great /tg/ meme wars, "True courage comes not from knowing when to open a PR, but when to close one..."

**Comment by TheDreamweaver** [comment]
Either way this guy is remaining closed since the new idea is different enough from the current state.

**Pull request closed without merging**
