### PR TITLE
Supermatter tong with shard inhands

### LINKED ISSUE #34729: Tongs and tongs with supermatter shards have no inhands.
This is kind of important because you can walk around and instantly dust someone in one click without anyone being able to see this coming.

### PR DESCRIPTION
**Pull request by itseasytosee**
## About The Pull Request
fixes #34729 two years later
## Changelog
:cl: itseasytosee
fix: supermatter tongs holding supermatter shards now have working in hand sprites
/:cl:

### CODE REVIEW

**Comment by Jared-Fogle** [comment]
The supermatter_tongs state seems to have a flashing white pixel, is that intentional?

**Comment by itseasytosee** [comment]
Let me check I thought I looked for that

**Comment by itseasytosee** [comment]
If there was it's fixed now, I had an extra animation frame because I wanted the shard to glow a little

**Review by Twaticus — CHANGES_REQUESTED** [review]
seems to still be a stray pixel on items_lefthand supermatter_tongs

**Comment by itseasytosee** [comment]
I added that one while fixing the last one

**Comment by Tharcoonvagh** [comment]
Supermatter thongs? Kinky

**Review by Twaticus — APPROVED** [review]

**Pull request merged**
