### PR TITLE
Skillchips are now copied to bitrunning avatars, plus a new chip to dodge bullets while flipping.

### PR DESCRIPTION
**Pull request by Ghommie**
## About The Pull Request
Active skillchips are now copied on bitrunning avatars. To celebrate this, I've made a skillchip, which can be ordered through the bitrunning vendor, that lets you dodge projectiles for the duration of your flips plus 1/10 of a second (so 8/10 of a sec), at the cost of stamina (if you think 20 is a bit too low, tell me).

I've also renamed the files containing the orderable bepis disks and bitrunning tech because they inconsistent with the names of their sections shown in the UI.

## Why It's Good For The Game
I think (active) skillchips being copied to bitrunning avatars makes sense as after all they're both tech-y, brainy stuff. It's a bit of a shame that no one thought of doing that.

## Changelog

:cl:
add: Active skillchips are now copied on bitrunning avatars.
add: To celebrate it, a skillchip is now available from the bitrunning order console, which lets you dodge projectiles for the duration of your flips, at the cost of stamina.
/:cl:

### CODE REVIEW

**Comment by JohnFulpWillard** [comment]
How similar is this to mining’s combo hud thing’s projectile deflection ability?

**Comment by Ghommie** [comment]
> How similar is this to mining’s combo hud thing’s projectile deflection ability?

Quite **dis**similar. Here, you're merely unhittable for 0.8 seconds when the flip emote runs (stumble and failing to flip doesn't count), which means projectiles just pass through you. There's no deflection going on.

**Comment by ATH1909** [comment]
can any weirdness result if the skillchip is somehow deleted (e.g. with c4) mid-flip?

**Comment by Ghommie** [comment]
> can any weirdness result if the skillchip is somehow deleted (e.g. with c4) mid-flip?

I don't think so. The caller of the callback responsible for removing the bullet dodge trait is the mob, so that shouldn't be an issue.

**Comment by deathrobotpunch** [comment]
>Active skillchips are now copied on bitrunning avatars. To celebrate this, I've made a skillchip, which can be ordered through the bitrunning vendor, that lets you dodge projectiles for the duration of your flips plus 1/10 of a second (so 8/10 of a sec), at the cost of stamina (if you think 20 is a bit too low, tell me

 
7908A500-C5E1-41C6-A0A6-FC3351C4A31C

**Comment by Ghommie** [comment]
> might make goon mad

I know it's a thing there too, however the code is different, it doesn't block melee attacks and was conceived as a skillchip rather than a quirk. I cannot digest well the mix of relative and absolute pathing of their code tbh.
The inspiration was also minimal at best, but that is something that cannot be hard-proofed.

**Comment by moocowswag** [comment]
Me on my way to dodge disablers and get stam critted anyway.

**Comment by Ghommie** [comment]
> Me on my way to dodge disablers and get stam critted anyway.

I'm waiting for the man that will combine this with hulk and golden bikehorns.

**Comment by starrm4nn** [comment]
> > Me on my way to dodge disablers and get stam critted anyway.
> 
> I'm waiting for the man that will combine this with hulk and have someone else constantly spamming golden bikehorns.

gloves of the northstar with *spin as the battlecry

**Pull request merged**
