### PR TITLE
Fixes nearsighted cost

### PR DESCRIPTION
**Pull request by Mickyan**
## About The Pull Request
Multiplies the cost by 4 to fit with the latest rebalance, it wasn't adjusted along with the rest

## Why It's Good For The Game
Making lemonade

## Changelog
:cl:
fix: Adjusted the cost of the nearsighted quirk to its intended value
/:cl:

### CODE REVIEW

**Comment by Qustinnus** [comment]
that was intentional.

**Comment by Mickyan** [comment]
#56037
Screenshot_8

tenor

**Comment by Qustinnus** [comment]
I missed listing it because I did the listing post-change (As cyber asked me to), by going through changed files. Any of them that are still -1 were left as it intentionally I just didn't notice them when going through the changes, as they were not listed as changes.

**Comment by Qustinnus** [comment]
Either way, I definitely intended them to be -1

**Comment by Mickyan** [comment]
Then I'll do a full sweep of these when I have time

**Pull request closed without merging**
