### PR TITLE
Adds superlube to the clown ruin.

### PR DESCRIPTION
**Pull request by nemvar**
## About The Pull Request

The lube in the lavaland clown ruin now slips you, even if you are crawling or have the hulk mutation. Only snails are immune to it right now.

## Why It's Good For The Game

This ruin was a joke ever since crawling got added. It's still pretty easy, but at least it slips you all over the place.

## Changelog
:cl:
tweak: The lavaland clown ruin has some new pranks ready.
/:cl:

### CODE REVIEW

**Comment by datorangebottle** [comment]
What about magboots?

**Comment by nemvar** [comment]
Probably overrides magboots, although I haven't tested it.

**Comment by Daxxed** [comment]
You can still jackhammer or gibtonite your way in and slip like 3 times with no brainpower needed

**Comment by ExcessiveUseOfCobblestone** [comment]
at the end of the day puzzle ruins without randomization will always be gameable to people who care to game it.

**Comment by bgobandit** [comment]
hopefully fixes https://github.com/tgstation/tgstation/issues/41590

**Comment by HomocidlePancakes** [comment]
All lube should slip like that tbh

**Pull request merged**
