### PR TITLE
Increases super power manifestation chance.

### LINKED ISSUE #7385: Manifest Chance for powers is absurdly low
You go through a ridiculous amount of SE injectors before manifesting ANYTHING, even with all power blocks above E
I'll probably buff this if I ever figure out how the fuck genetics works but that might not be VERY LIKELY HNNNHNH

(yes it's bad luck but holy fuck genetics is composed entirely of RNG we should change this)

### PR DESCRIPTION
**Pull request by Firecage**
This increases the manifestation chance of super powers.

Hulk: 5 -> 15
TK: 10 -> 20
Cold Res: 10 -> 25
Cloak of Darkness: 10 -> 25
Chameleon: 10 -> 20
Xray: 10 -> 25

Fixes #7385

### CODE REVIEW

**Comment by GunHog** [comment]
Yes pl0x :+1:

**Comment by WJohn** [comment]
Thank god.

**Comment by Supermichael777** [comment]
fixes bug of never geting super powers

**Comment by Dorsisdwarf** [comment]
Xray should be a bit less common (it's really good, especially with meson goggles), say, 20, and CoD is pants so make it higher.

**Comment by Firecage** [comment]
Mmm, sure, but I think It would then be best to atleast lower it to 25

**Comment by Iamgoofball** [comment]
:+1:

**Comment by Cheridan** [comment]
IMO this should be some diminishing-returns thing.

So like, if you have 1 power possible it's 100%
2 is 60% 
3 is 30%, etc 

but this should be ok

**Pull request merged**
