### PR TITLE
Renames chaplain vending machine

### PR DESCRIPTION
**Pull request by Bawhoppen**
This felt like a perfect pun for the vending machine name. 
(Less perfect for the desc though maybe)

### CODE REVIEW

**Comment by RaveRadbury** [comment]
For a second I thought this was `Removes chaplain vending machine` and I was confused and sad

**Comment by norill** [comment]
good pun, but doesn't beat holy driver

**Comment by tralezab** [comment]
Good work Bawhoppen

**Comment by Bawhoppen** [comment]
> Good work Bawhoppen

thank you friend



> good pun, but doesn't beat holy driver

I don't think I get it

**Comment by norill** [comment]
> > good pun, but doesn't beat holy driver
> 
> I don't think I get it

the mass driver in chapel is called holy driver, which i think is a reference to the song holy diver by dio

**Comment by interestingusernam3** [comment]
el deus vend machina

**Pull request merged**
