### PR TITLE
Jetpacks no longer have an action button for setting them as internals

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
It's annoying to have 3 identical buttons at the top of the screen and two of them are related to flying and one of them kills you instead. 

And for those of you curious no it didn't kill me because I realized right after I clicked but I realized how mad it would have made me and how pointless having the button is

### CODE REVIEW

**Comment by GunHog** [comment]
# What is carbon dioxide!?!?!?!

**Comment by kevinz000** [comment]
WTF IS CARBON DIOXIDE?!!

**Comment by PraiseRatvar** [comment]
100% of the time the first jetpack button is the set internals one, plus you can just mouse over the action buttons to see whaddya they do
just make the action button a different image and everyone will be happy.

**Comment by lzimann** [comment]
Make the icons unique instead of removing what can be useful.

**Comment by SgtxRootbeer** [comment]
kor, this is an actually useful feature...
wait, you dumbshit, THIS APPLIES EVEN TO THE CAPTAIN'S JETPACK. THE REASON ITS SO VALUABLE IS BECAUSE IT STARTS OFF WITH O2 IN IT. WE EVEN GOT A FEW PARAGRAPHS ON THE WIKI ABOUT THIS SPECIFIC JETPACK AND HOW OTHERS DONT USE O2

**Comment by lzimann** [comment]
Spoilers: you can put o2 in any jetpack and it works fine

**Comment by Steelpoint** [comment]
It would be better if the Jetpack to Internals was a unique button. Right now you have three Jetpack icons that are all identical that require you to hover over them and read the text desc to figure out what they do.

**Comment by Supermichael777** [comment]
you can still toggle the internals by clicking the internals indicator right?

anyway using your jetpack as your airsource is not the best idea

**Comment by lzimann** [comment]
@Supermichael777 Yes, but iirc that gets the last tank you touched/interacted, not so sure on how that works. The action buttons on the other hand, let's you easily toggle the internals between each tank you have equipped, and that SHOULD include jetpacks, even if most of the times it is not a good idea to use them as internals.

**Comment by KorPhaeron** [comment]
Having a way to connect a jetpack to a breath mask while flying it is also weird in the first place but if someone wants to change the action icon I guess that works as well

**Comment by RemieRichards** [comment]
This is not the solution, as has already been discussed.

**Comment by KorPhaeron** [comment]
It's bloat left over from inheritance

**Comment by RemieRichards** [comment]
you're bloat.

**Pull request closed without merging**
