### PR TITLE
Fixes people in fire resistant suits never getting hot when on fire

### LINKED ISSUE #42839: heat_protection flag does not interact properly with FIRE_IMMUNITY_MAX_TEMP_PROTECT (or otherwise fire resist on armor)
## Issue:
FIRE_IMMUNITY_MAX_TEMP_PROTECT is 35000K. Any gas you are in the environment of that is hotter than this will cause you to take damage, this is the very maximum an atmospherics protective suit is supposed to protect you to, such as the atmospherics hardsuit. Somewhat seperately, these same suits also have you be immune to fires, which does make sense. However, there is an odd interaction here. When you are on fire, FIRE_IMMUNITY_MAX_TEMP_PROTECT stops functioning practically entirely, and you become immune to gas of any temperature. Simply by being on fire, completely regardless of what's causing it, you can stand in gas of any temperature. You can survive a fusion fire so long as you are on fire, but if you're not on fire while being exposed to these kinds of temperatures, you will start taking damage.

## Reproduction:
Equip a suit that has heat protection, such as the atmopsherics hardsuit, CE's hardsuit, atmospherics firesuit and helmet, etc. Create a fusion fire and stand in it, take no damage. Heat exchange some random gas with the fusion levels of temperature (or just raise the temperature to a ways above 35000K), ensure you're not on fire, start taking damage from the gas' heat. Light yourself on fire in this same gas, don't take damage anymore.

## Vidya:

https://puu.sh/CO996/1c868f7fa7.mp4

### PR DESCRIPTION
**Pull request by Unit2E**
## About The Pull Request

People in atmospherics resistant suits are immune to being on fire, and also resist gas up to 35000K in temp. However, if they're on fire (and not already getting hot), the 35000K limit would never apply, never heating them up. When otherwise, they would heat up when not on fire but in the prescence of 35000K gas. This corrects that by making them heat up, even if on fire, when temps are over 35000K.

If there's better ways to do this please tell me, I'm extremely fresh and this seemed the easiest solution to me.

## Why It's Good For The Game

Fixes an oversight that's been around for way too long. Also somewhat nerfs firesuits / makes extremely hot fire floods more effective (plasma floods don't tend to reach high enough).

Closes #42839 

## Changelog
:cl:
fix: people in fire resistant now get properly hot in fires they shouldn't resist (temps of 35000K and over)
/:cl:

### CODE REVIEW

**Comment by Arianya** [comment]
The surface of the sun only reaches 5778 Kelvin

What on earth even reaches 35000 K?

**Comment by Unit2E** [comment]
Nothing on earth, but in space, fire, fire burns much brighter when oxygen is the supplier.

Jokes aside, tritium can reach in 500,000s, and higher. Fusion can reach ridiculous levels, well over e12 and much higher. Even plasma, when optimally burned, might break the number. (Again, rarely happens in floods)

**Comment by DaxDupont** [comment]
Fucking steam powered giraffe reference

**Comment by ExcessiveUseOfCobblestone** [comment]
this proc is poop so give me 24 hours to rewrite it.

**Comment by ShizCalev** [comment]
waiting on cobble

**Comment by ExcessiveUseOfCobblestone** [comment]
whoops lol 1 sec

**Comment by ExcessiveUseOfCobblestone** [comment]
ugh one day....

**Pull request merged**
