### PR TITLE
/mob/dead no longer has a throwforce

### LINKED ISSUE #39846: a whole new level of adminbus
You can use buildmode's telekinesis to throw ghosts at stuff.
*And break stuff.*

**oh god no**

the saga of ghostbusting: https://imgur.com/a/rk5miaG
[~12mb and looks ugly af because of compression]

lite version of the gif above

~~this is too good to be fixed~~

### PR DESCRIPTION
**Pull request by MrsTonedOne**
fixes #39846

closes #39849 (@Iamgoofball)

This pr is the same as goofs only without the sass.

### CODE REVIEW

**Comment by Iamgoofball** [comment]
My PR was correct though

**Comment by Iamgoofball** [comment]
le 24 hour rule

**Comment by Iamgoofball** [comment]
Also stealing my gbp

**Comment by Cyberboss** [comment]
551c794068991

**Comment by MrStonedOne** [comment]
Your pr was an assault on the admins sovereignty. Mine just fixes a bug.

**Comment by Anonmare** [comment]
Will probably just edit the throwforce back to what it was again if it's time for adminbus. Don't really see the need considering it's a non-issue for players but whatever

**Comment by fludd12** [comment]
>Admins do not deserve sovereignty

I can never tell if you're serious about something or not, goof. This made me giggle.

**Pull request merged**
