### PR TITLE
Un-breaks various kinds of ethereal energy feeding [FIX]

### LINKED ISSUE #86985: Ethereal's cannot feed from APC's
### Client Version:

515.1643

### Issue Summary:

When tried to feed from an APC, it simply doesn't work. According to Ian0 it is caused because APC's have 10 million power and ethereals only have maximum 20.000. So game automaticaly sees it "too much for the ethereal to consume".

### Round ID:

[239440](https://scrubby.melonmesa.com/round/239440)

### Test Merge Information:

- [Adds the NT BR-38 Battle Rifle. A sci-fi hybrid gun (that can critically fail on existence). Throws combat shotguns (the big ones from cargo) into the bin. Other changes. (SPRITES WIP)](https://www.github.com/tgstation/tgstation/pull/86853)
- [[TESTMERGE READY] The Torment Nexus: The future of Security brigging and prisoner rehabilitation!](https://www.github.com/tgstation/tgstation/pull/86106)

### Reproduction Steps:

Go to any charged APC as an ethereal
Try to charge your energy
Observe how it responds and doesn't work.

### PR DESCRIPTION
**Pull request by KingkumaArt**
## About The Pull Request

Fixes #86985. Also, since the higher numbers of megacells made overcharging from apcs more frequent, the do_after is twice as quick, but gives half as much charge. The players still feed at the same speed, but wont blow past "full" instantly to "overfed".

## Why It's Good For The Game

Etherials can eat from APCs/Voltaic Wine again! 

## Changelog

:cl: WebcomicArtist
fix: Un-breaks etherial apc charging and charge from ethereal wine.
/:cl:

### CODE REVIEW

**Comment by SyncIt21** [comment]
This isn't a fix. It just re opens #86908.

Read 
https://github.com/tgstation/tgstation/issues/86985#issuecomment-2384000911 carefully. The main solution is to scale ethereals to use batterues which is why no one wanted to fix the issue because it's a balance change

**Comment by KingkumaArt** [comment]
> This isn't a fix. It just re opens #86908.
> 
> Read all the comments following [#86985 (comment)](https://github.com/tgstation/tgstation/issues/86985#issuecomment-2384000911) carefully.
> 
> The main solution is to scale ethereals to use batteries which is why no one wanted to fix the issue because it's a balance change

It _does_ scale them to use batteries.

**Comment by SyncIt21** [comment]
> Unless runtimestation's APCs dont use megacells, of course. Will test on metastation.

Definitely test on meta cause I think runtime station was ignored during the Megacell PR. I'm sure this doesn't work on any other map

**Comment by KingkumaArt** [comment]
> Definitely test on meta cause I think runtime station was ignored during the Megacell PR. I'm sure this doesn't work on any other map

Ah, if so I think I know how to fix it, then.

**Comment by KingkumaArt** [comment]
Also I remembered to buff the voltaic wine, was wondering why I couldnt use booze as food anymore

**Comment by SyncIt21** [comment]
Yup this is the correct fix although now this has become a balance PR because ethereals now hold more charge overall so we have to assess the implications of that

**Comment by KingkumaArt** [comment]
> Yup this is the correct fix although now this has become a balance PR because ethereals hold more charge overall so we have to assess the implications of that.
> 
>I tried to keep everything proportional, but if theres something I've missed, let me know.

**Comment by necromanceranne** [comment]
> Yup this is the correct fix although now this has become a balance PR 

It's not a balance pr if it wasn't using the correct defines in the first place, mate. It is at most an oversight, which people are entirely entitled and the _the original person who made the oversight in the first place_ is usually obliged to _correct_.

**Comment by Sealed101** [comment]
obligatory issue autolinking reminder

_For future reference, [these](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) are all the keywords that can be used to link issues/PRs._

**Comment by KingkumaArt** [comment]
Bump

**Comment by KingkumaArt** [comment]
Bump

**Comment by KingkumaArt** [comment]
If this bug fix dies to the stale bot I'm gonna lose it

**Pull request merged**
