### PR TITLE
Adds luminosity to lasers and sparks.

### PR DESCRIPTION
**Pull request by TechnoAlchemisto**
Looks nice, I promise.

Listen if you wanna know what it looks like throw a lit lighter down a dark hall

pewpew

### CODE REVIEW

**Comment by optimumtact** [comment]
screenshots

**Comment by Shadowlight213** [comment]
Needs balance tag due to being a nerf to stealth lasering from the dark.

**Comment by xxalpha** [comment]
While neat, this will probably be laggy and not look so good.

**Comment by TechnoAlchemisto** [comment]
It looks pretty peachy on my low performance test server.

**Comment by Jalleo** [comment]
@MrPerson

**Comment by GunHog** [comment]
Need examples, perhaps gifs. Would this even look good, given our visually simplistic lighting system?

**Comment by TechnoAlchemisto** [comment]
I'll work on that, give me a bit to figure it out.

**Comment by GunHog** [comment]
That is actually not bad, considering our system.

**Comment by Lumipharon** [comment]
This is neat, I've wanted to see this for a while now.
I recommend adding this to the muzzleflash of gunpowder based weapons (not suppressed weapons) also.

**Comment by KorPhaeron** [comment]
Only one way to find out how it looks on server

**Comment by TechnoAlchemisto** [comment]
oh FUCK

**Pull request merged**
