### PR TITLE
All hivemind powers now ignore antimagic

### PR DESCRIPTION
**Pull request by Kierany9**
# I swear to god I will smack someone if you mofos don't learn how to ping me or make issue reports

### CODE REVIEW

**Comment by coiax** [comment]
Last time I did any testing with anti-magic, it seemed pretty broken.

**Comment by Kierany9** [comment]
In what sense is it broken? Right now all this PR does is set antimagic_allowed to true for all the spells that aren't under the "target_hive" subtype (which already had it set to true). And from what I gather, when set to false, the spells don't work under the effects of antimagic.

**Comment by necromanceranne** [comment]
antimagic actually doesn't work presently. So...

**Comment by ATH1909** [comment]
> In what sense is it broken? Right now all this PR does is set antimagic_allowed to true for all the spells that aren't under the "target_hive" subtype (which already had it set to true). And from what I gather, when set to false, the spells don't work under the effects of antimagic.

It just flat-out doesn't work/doesn't protect you from magic, as far as I can tell.

**Pull request merged**
