### PR TITLE
adds the duffel pai holomob

### PR DESCRIPTION
**Pull request by Detective-Google**
## About The Pull Request

people on discord came up with the idea of a duffel bag with cute little wheels as a pai holomob so I made it, but I couldn't get anyone to make half decent sprites so I made my own shitty ones

## Why It's Good For The Game

more holomobs and flavor for pais is fun, @Niknakflak cat demands it

## Changelog
:cl: Detective Google, TheTeenyTiny for much improved sprites
add: pAIs can now transform into cute little duffel bags! (with wheels!)
/:cl:

### CODE REVIEW

**Comment by Detective-Google** [comment]
https://cdn.discordapp.com/attachments/558114256940433419/622250203981938688/2019-09-13_20-58-49.mp4
I can't believe icondiffbot is dead this is so sad

**Comment by optimumtact** [comment]
if someone doesn't add a luggage antag or special round event i'll commit the long die

**Comment by davethwave** [comment]
Would be funny that if someone tries to drag the sprite to them it will show 1 empty slot and the PAI in it, if you attempt to put something in it, the item falls through the bag onto the floor.

**Comment by PKPenguin321** [comment]
>if someone doesn't add a luggage antag or special round event i'll commit the long die

antag freeze

**Comment by Detective-Google** [comment]
> > if someone doesn't add a luggage antag or special round event i'll commit the long die
> 
> antag freeze

**Comment by optimumtact** [comment]
Do not cite the Deep Magic to me, Witch. I was there when it was written

**Comment by Ty-the-Smonk** [comment]
Can I see these sprites mate

**Comment by OverlyGeneric** [comment]
> if someone doesn't add a luggage antag or special round event i'll commit the long die

so what like a worse variant of the morph that eats whatever is put inside it?

bag of devouring kind of thing?

**Comment by Detective-Google** [comment]
> Can I see these sprites mate

I... literally linked a video since the diffbot is dead.

**Comment by TheTeenyTiny** [comment]
Did you want the sprites re-done or something?

**Comment by Detective-Google** [comment]
> Did you want the sprites re-done or something?

if someone makes better ones I'll totally implement them

**Comment by TheTeenyTiny** [comment]
Here you are my friend, I just added them to the sheet. Let me know if you like it/want to use it : D

[dufflebag pai.zip](https://github.com/tgstation/tgstation/files/3634176/dufflebag.pai.zip)

**Comment by Detective-Google** [comment]
> Here you are my friend, I just added them to the sheet. Let me know if you like it/want to use it : D
> 
> [dufflebag pai.zip](https://github.com/tgstation/tgstation/files/3634176/dufflebag.pai.zip)

these are great! hopefully you don't mind if I swap these out right away

**Comment by TheTeenyTiny** [comment]
I don't mind at all : D Glad I could help. The little guy was fun to make

**Pull request merged**
