### PR TITLE
Fixes and speedups to spraycans/crayons

### PR DESCRIPTION
**Pull request by vuonojenmustaturska**
## About The Pull Request

This PR removes the buttons for individual letters and punctuation, speeding up the UI considerably. Those buttons are generated from data that is shipped between client and server for every spray, and the text mode is much faster than using the hunt & pecker routine with a cursor on a bunch of small buttons.

It also fixes the text buffer display on the UI.

**DO NOT MERGE BEFORE #44420** due to tgui.js conflicts, it's much much easier for me to rebase this thing than for them to rebase a 1000 line PR.

## Changelog
:cl: Naksu
del: Removed individual buttons text in crayon/spraycan UI, speeding it up.
fix: Text mode buffer is actually visible in the UI.
tweak: Last letter of a text mode buffer no longer rotates out to be replaced with "a", allowing the text mode to be used for individual symbols.
/:cl:

### CODE REVIEW

**Comment by Akrilla** [comment]
🙏

**Comment by MrPerson** [comment]
Man when byond supports unicode I can't wait to spraypaint some emojis!

**Comment by datorangebottle** [comment]
I pretty much always used the text buffer for writing stuff, and the hunt and peck keyboard for spamming 'h' all over the station, so I'm very okay with this. Spraycans/crayons have needed a speed update for a long time now; I got tired of the game borderline crashing whenever I tried to open up the menu.

**Comment by Akrilla** [comment]
#44420 is merged in now so feel free to rebase/fix conflict.

**Pull request merged**
