### PR TITLE
Generates messages when xeno eggs are delivered

### PR DESCRIPTION
**Pull request by coiax**
:cl: coiax
add: The egg spawner on Metastation will generate a station message and
inform the admins if an egg is spawned. (It's only a two percent chance,
but live in hope.)
/:cl:

Metastation has a 2% egg spawner. If it picks the xeno egg, it does so
silently, telling no one. Now it ~~informs the station~~ prints a command report
and also admins and the game log.

- I've also refactored `print_command_report` so  you can just have the "COMMAND REPORT CREATED"
announcement built in

To reiterate, this behaviour is already in the map, I'm just generating
logging and messages. If admins want to simulate this, they can spawn a
`/obj/effect/spawner/xeno_egg_delivery` in any location they like.

Here is a screenshot from testing. Turns out that 2% is a very slim chance.
image

### CODE REVIEW

**Comment by WJohn** [comment]
Honestly this'll probably result in WAY MORE released xenos simply because people will rush to xenobio, traitors included, to try and release them.

**Comment by coiax** [comment]
You're saying that like it's a bad thing. Honk.

**Comment by WJohn** [comment]
I MEAN I GUESS I'M NOT COMPLAINING

**Comment by GunHog** [comment]
Is the message normal or classified?

**Comment by coiax** [comment]
Normal. Want it to be classified?

**Comment by KorPhaeron** [comment]
Why?

**Comment by GunHog** [comment]
I would vote for it being classified, but that is up to you. Kor, are you asking me or Coiax?

**Comment by KorPhaeron** [comment]
Asking what the point of the change in general is

**Comment by RandomMarine** [comment]
I think more often than not powergamers will just try to break into xenobio to kill the xenos.

**Comment by PKPenguin321** [comment]
Yeah I was gonna say this will just result in a dead facehugger one in 50 rounds

**Comment by coiax** [comment]
@KorPhaeron because it'd be a shame if the egg spawned and no one knew about it. It also generates an admin message so they know what's up.

I was also thinking of adding the spawner to all maps, but that's for another PR.

**Comment by GunHog** [comment]
Having it be classified would at least limit the knowledge to players with comms console access, allowing them to decide whether or not to have a Xeno round. The heads will be able to argue and negotiate with each other, which is nigh impossible if the entire station knows!

**Comment by coiax** [comment]
@GunHog will do.

**Comment by coiax** [comment]
@GunHog in practice, everyone's like WHATS THE COMMAND REPORT SAY. But you know, barrier to entry and all that

**Comment by GunHog** [comment]
Yes, but that can enable me to LIE :smiling_imp:

**Comment by Kromgar** [comment]
Why dont you add this to delta and box too?

**Comment by coiax** [comment]
@Kromgar that is for another PR.

**Comment by coiax** [comment]
I am just changing an EXISTING feature to notify the command staff when it happens.

**Pull request merged**
