### PR TITLE
Gives the pod people's dispenser all the chemicals they could ever want.

### PR DESCRIPTION
**Pull request by Expletive**
:cl: 
tweak: The Seed Vault's chemical dispenser now has all the chemicals a pod person could want.
/:cl:

We've already added saltpetre, so I thought why not go whole hog? The seed vault was already set up to produce botanical wonders beyond the dreams of most station botanists, and now it can be even more so.

### CODE REVIEW

**Comment by FantasticFwoosh** [comment]
But you dont need anything BUT saltpetere & mutagen, everything else you get form bottles within the bio generator.

**Comment by Kromgar** [comment]
@FantasticFwoosh Can't you only get sugar from sugarcane? Or am i wrong?

**Comment by octareenroon91** [comment]
Table salt, or the full chem dispenser options...

**Comment by Expletive** [comment]
@octareenroon91 Does Saline-Glucose solution have an effect on plants? I didn't see it in hydroponics.dm so I didn't add it.

**Comment by octareenroon91** [comment]
>hydroponics.dm

Why omit holywater? Also we should probably go for a different approach in providing chemical variety to lifebringers.

Possibly a database of plant-gene disks of reagent-production.

**Comment by fludd12** [comment]
That's actually a really good idea, @octareenroon91. It'd require a pretty big refactor of the chem dispenser, but you could have energy cost for the chemicals based on the %yield of the reagent disc.

**Comment by octareenroon91** [comment]
I'd just go for an extra-impenetrable disk fridge that only opens for plantfolk.

**Pull request merged**
