### PR TITLE
Lock mark now causes the victim to drop their items when triggered

### PR DESCRIPTION
**Pull request by ViktorKoL**
## About The Pull Request

Out of all heretic's mark effects, the lock path is the only one with no effect on trigger. This is odd, because it seems like we would want to reward the heretic for triggering the mark, but in lock mark's case, all this does is cancel the ongoing effect and give no reward in exchange, actively discouraging using the sickly blade and triggering the mark. Other marks with an ongoing effect all have a trigger effect too, to give a reward for ending the former. This PR adds an effect that makes the victim drop most of their items (50% chance for each item, but only a 25% chance for jumpsuits, because dropping a jumpsuit usually means dopping several other items too).
## Why It's Good For The Game

Heretics should want to trigger their marks, or at least get something out of it apart from just cancelling a beneficial effect. Dropping items thematically fits with lock's theme of burglary and access.
## Changelog
:cl:
add: Mark of the lock now causes the victims to drop most of their items when triggered.
/:cl:

### CODE REVIEW

**Comment by SomeoneYouProbablyKnow** [comment]
50% to drop headset? Pretty high chance for something so spooky

**Comment by ViktorKoL** [comment]
When it comes to balance, I looked at rust mark as a reference (75% chance to deal 100 damage to any given item). Though I have not considered that a majority of items has more than 100 max health, meaning the mark does not often actually destroy useful items... Maybe the chance should be lowered further. On the other hand, the items are just dropped, so the victim can, in theory, grab them right away, unlike when they are destroyed...

> 50% to drop headset? Pretty high chance for something so spooky

I can add a check to make the chance lower for headsets too, but maybe it will not be necessary if the overall chance lowers.

I will also say here that if this is not a feature we want, it's still stupid that the lock mark loses its only effect when triggered, so an alternaitve change I would do in that case is simply making the existing no access effect start on the trigger and end after a fixed amount of time.

**Comment by SomeoneYouProbablyKnow** [comment]
> On the other hand, the items are just dropped, so the victim can, in theory, grab them right away, unlike when they are destroyed...

Yea but combat is just a tad too fast for that barring a select few capital G gamers sadly. Especially since it's gonna be a pile of items abd you have to notice what you dropped before you go picking it up.

I do like the idea, maybe just limit it pockets and hands or something?

**Comment by HoodMilk** [comment]
Just make it drop their bag and or items in their hand.

**Comment by GuillaumePrata** [comment]
Since lock has some access related features, I think a good angle could be to reaply the mark, so people can't just walk away and discourage its use, and make it 100% drop their ID item or add it to the Heretic's offhand, so it forces them to choose between staying in the fight a little longer to get their ID back or fleeing while forfeiting their access to the Heretic.

I personally hate having your combat related items dropped on the floor, pixel hunting items is not a good balance never, now if it is just their ID, it is a lot more manageable.

**Comment by SomeoneYouProbablyKnow** [comment]
I didn't wanna suggest ID because it can lead to you being locked in a room with a heretic with no way out. You can't always run away without an id

**Comment by ViktorKoL** [comment]
> Just make it drop their bag and or items in their hand.

Dropping only all (or most) of items in the backpack sounds interesting too, and lets you keep your combat items if you stored them anywhere else, or pulled them out before the mark got triggered.

> Since lock has some access related features, I think a good angle could be to reaply the mark, so people can't just walk away and discourage its use, and make it 100% drop their ID item or add it to the Heretic's offhand, so it forces them to choose between staying in the fight a little longer to get their ID back or fleeing while forfeiting their access to the Heretic.

I like this idea as well, it gives heretics a way to easily steal ID cards without killing, at the cost of being very obvious to the crew, which sounds fun.

> I didn't wanna suggest ID because it can lead to you being locked in a room with a heretic with no way out. You can't always run away without an id

Is that necessarily an issue? If the heretic really wants you to not be able to escape the room, they can just not trigger this mark at all.

**Comment by SomeoneYouProbablyKnow** [comment]
> Is that necessarily an issue? If the heretic really wants you to not be able to escape the room, they can just not trigger this mark at all.

Maybe not. But NOT removing the mark is a deliberate choice the heretic gotta think about and make. 
I'd rather the path of least resistance be something that harms more geared and more aggressive players (which is why i said hands and pockets) and not undergeared people trying to run, if that make sense

**Comment by moocowswag** [comment]
> Since lock has some access related features, I think a good angle could be to reaply the mark, so people can't just walk away and discourage its use, and make it 100% drop their ID item or add it to the Heretic's offhand, so it forces them to choose between staying in the fight a little longer to get their ID back or fleeing while forfeiting their access to the Heretic.


Dropping your id especially in your own workplace 100% results in them not being able to run away anyway.

This would pretty much encourage to go valid hunt the heretic in the hallways or maintenance since they allow access out atleast it you fail. Rather than getting jumped on in your own department.

**Comment by MLGTASTICa** [comment]
Having played against heretics making use of this , its preety much horrid on the target. It removes most if not all of their armor instantly and weaponary too. It'd be perhaps a little bit more balanced for them to have it thematically lock up all guns and stunbatons for a few seconds instead and make them unuseable.

**Comment by ViktorKoL** [comment]
I see that this feature does not seem very liked in its current form. I will make changes to make it into something better and retry sometime in the future.

**Pull request closed without merging**
