### PR TITLE
Adds sound effect to hitting with violin.

### LINKED ISSUE #7030: Space violin has no hitsound
It has 10 force but no hitsound. I can easily see this being abused (i.e. ebow + violin = silent kill)

### PR DESCRIPTION
**Pull request by Firecage**
This adds a hitsound to the violin so it is no longer a silent tool of !DEATH!

Fixes #7030

### CODE REVIEW

**Comment by WJohn** [comment]
Ask cuboos for a custom sound, this deserves something with wood chipping and strings twanging.

**Comment by Firecage** [comment]
I still don't know if its a good idea to make the sound folder even bigger....

**Comment by KazeEspada** [comment]
obviously its hitsound needs to be a random note.

**Comment by Firecage** [comment]
@KazeEspada I tried that, the notes just comes out to softly. It just won't work used for this.

**Pull request merged**
