### PR TITLE
Removes S

### PR DESCRIPTION
**Pull request by Contrabang**
## About The Pull Request
Removes S

## Why It's Good For The Game
Removes S

## Changelog
:cl:
code: Removes S
/:cl:

### CODE REVIEW

**Review by DGamerL — APPROVED** [review]
👎

**Comment by MrMelbert** [comment]
```
   ^
  / \
 /   \
/     \
|  |  |
|  |  |
\  \  /
 \  \/
 /\  \
/  \  \
|  |  |
|  |  |
\     /
 \   /
  \ /
   v
   ```

**Comment by Y0SH1M4S73R** [comment]
Have ye heard not the tale of the load bearing s?
Ye'll bring ruin down upon us all.

/s

**Comment by CCC23** [comment]
NOT S

**Comment by Striders13** [comment]
improve don't remove

**Comment by necromanceranne** [comment]
Can we fucking ban this guy already?

**Comment by SmArtKar** [comment]
that s is our coconut, do not toy with powers beyond your comprehension oh traveller

**Review by optimumtact — APPROVED** [review]

**Comment by deathrobotpunch** [comment]
I can’t believe the c*ders would allow such a controversial change to get merged

**Comment by snailomi** [comment]
> that s is our coconut, do not toy with powers beyond your comprehension oh traveller

so THAT is why the servers are down

**Pull request merged**
