### PR TITLE
Fixes a cooking proc that had a misplaced parenthesis

### PR DESCRIPTION
**Pull request by Ketrai**
Title

### CODE REVIEW

**Comment by jlsnow301** [comment]
Wait what... why are you no gbp'ing fixing someone else's code

**Comment by Ketrai** [comment]
> Wait what... why are you no gbp'ing fixing someone else's code

Oh, I felt weird about getting GBP about a single parenthesis, hence I got confused!

**Comment by FlufflesTheDog** [comment]
also #82782

**Comment by jlsnow301** [comment]
dupe

**Pull request closed without merging**
