### PR TITLE
Adds chaplain hoodie and nun robe to autodrobe

### PR DESCRIPTION
**Pull request by TheVekter**
By popular request.

### CODE REVIEW

**Comment by Deantwo** [comment]
Didn't fix the nun's hood as you were just talking about on IRC?

**Comment by TheVekter** [comment]
I'm still trying to figure out how to do that, to be honest. I need a sprite with both the nun hood AND the nun outfit I think. I'll work it out and get it committed.

**Comment by Deantwo** [comment]
May need @Perakp's new hood system?

**Comment by paprka** [comment]
Don't touch the nun hood, it's meant to be separate from the robe. The chaplain hoodie is one thing.

**Comment by TZK13** [comment]
Yeah the nun outfit shouldn't be one thing like the chaplain hoodie is, it should stay separate.

**Comment by xxalpha** [comment]
I don't agree with this at all, might as well start putting job jumpsuits in there.

**Comment by TheVekter** [comment]
@xxalpha This adds the oversuits for both jobs, mainly for clown chaplain gimmicks. I don't think there's much harm in letting them get them, since there's nowhere else on the station you can get a chaplain hoodie.

**Comment by xxalpha** [comment]
That's the point, I think. They're clothes for a specific job. If you want new clothing you can order them from cargo.

**Comment by TheVekter** [comment]
@xxalpha makes a good point, putting this on hold.

**Pull request closed without merging**
