### PR TITLE
Moves all the custom AsteroidStation areas

### PR DESCRIPTION
**Pull request by CorruptComputer**
There's problems with dmmrender and this is the only way I know to fix it.

### CODE REVIEW

**Comment by tkdrg** [comment]
This will conflict with carn's PR I'm pretty sure.

**Comment by CorruptComputer** [comment]
Oh forgot about that, yeah it conflicts.

**Comment by ike709** [comment]
will this speed up the process of updating asteroid steshun?

**Comment by tkdrg** [comment]
It doesn't really affect anything. I'd rather this not be merged to be honest, since all it does is make asteroid less modular and mix asteroid's files with the main code.

**Comment by CorruptComputer** [comment]
But it make it easier to edit the map, if you try to open the map before ticking the .dm it gives errors.

**Comment by Miauw62** [comment]
That's because you're not supposed to tick the .dmm, it's #included in
AsteroidStation.dm
Op 2-jan.-2015 05:17 schreef "CorruptComputer" <notifications@github.com>:

**Comment by CorruptComputer** [comment]
I never said to tick the .dmm, also I'm not talking about compiling, when you just open Asteroidstation.dmm in dream maker it gives errors, but if you open tgstation.dme first and tick asteroidstation.dm you dont get any errors when you open Asteroidstation.dmm.

**Comment by Miauw62** [comment]
yes, i dont see the issue here.

**Pull request merged**
