### PR TITLE
HARDSUIT POWERCREEP ENDS -NOW-

### PR DESCRIPTION
**Pull request by Militaires**
removed hos hardsuit, CMO hardsuit, RD hardsuit.

RD hardsuit is still available BUT only on stations where it's in the toxin test site zone accessible to all scientists.

# hardsuit powercreep ends now.

### CODE REVIEW

**Comment by lzimann** [comment]
Reason for this?

**Comment by lzimann** [comment]
Know what, I'll just close this, I don't think heads having a hardsuit is even a powercreep, it barely affects the round overall.

**Comment by Militaires** [comment]
heads having hardsuits was just a snowball effect from x has hardsuit let's give y

@optimumtact requesting reopen on grounds of invalid close reasoning.

**Comment by lzimann** [comment]
You claim "invalid close reasoning" but still didn't give a valid reasoning to have this opened besides saying "it's powercreep".

**Comment by Militaires** [comment]
exactly @lzimann, hence i gave it in the above post to answer your needs

**Comment by kevinz000** [comment]
@Militaires fuck off ty

**Comment by Militaires** [comment]
@kevinz000 expected and calculated reaction kebab

**Comment by PKPenguin321** [comment]
Hop hardsuit incoming

**Comment by octareenroon91** [comment]
HoP can spend telecrystals for a hardsuit just like everybody else.

Also steal from cap or mining

**Pull request closed without merging**
