### PR TITLE
Lore accurate Felinids - Replaces Felinid blood with Felinid mutation toxin

### PR DESCRIPTION
**Pull request by NamelessFairy**
## About The Pull Request

This PR makes felinidism contagious via exposure to felinid blood. 

This is a code solution to a lore issue. The new lore for felinids is as follwos:
Felinids are no longer born. Adult felinids inject their blood into healthy members of other species causing them to morph into another felinid.

I think this is the best way to represent the felinid community within the lore as OOCly they tend to spread through subliminal brainwashing. Now ICly felinids will need to over many months encourage other players to take some of their blood. I am absolutely certain that not one felinid player would turn someone else into a felinid without their consent.

<details>
<summary>Spoiler warning</summary>
If you hadn't guessed, this is a slightly early April fools day joke

But its not April fools yet I hear you say
The actual joke is merging it tomorrow (joke implied)
</details>

## Why It's Good For The Game

A lore master said that they didn't want to write lore for species reproduction so I made a code solution for felinid reproduction.
image

## Changelog
:cl:
qol: Made felinid lore intresting
/:cl:

### CODE REVIEW

**Comment by interestingusernam3** [comment]
It's april fools in New Zealand

**Comment by Pugie** [comment]
Idk man felinid sex is probably an easier addition

**Comment by BootlegBow** [comment]
it's april fools in at least 20 countries so you're right on time

**Comment by Mothblocks** [comment]
For the benefit of the maintainers, April Fools PRs will be labeled and closed. Key Holders are still able to test merge PRs that are closed, so this makes no difference to you, the author, assuming you were able to find a Key Holder to merge this PR in the first place. If you need to make updates to this PR, you can simply add to the branch, and when the TM updates it will use those changes, even if they do not show up to the PR.

**Comment by adamkad1** [comment]
Do this with all species tbh

**Comment by NamelessFairy** [comment]
> Do this with all species tbh

Maybe next year

**Pull request closed without merging**
