### PR TITLE
Resprites The Heretic Ash Blade.

### PR DESCRIPTION
**Pull request by EnterTheJake**
## About The Pull Request

Gives the Ash blade a new coat of paint.

Ash Blade

Screenshot 2024-08-01 002532

Ingame demonstration https://www.youtube.com/watch?v=lQPPh8CH9Ag&t=1s

## Why It's Good For The Game

The og Heretic blades are showing their age, this pr  grants the Ash blade a shiny new animated sprite.

Sprites made by OrcaCora.

## Changelog

:cl:
image: Ash Blade has received a new sprite.
/:cl:

### CODE REVIEW

**Comment by Jacquerel** [comment]
The inner curve at the top looks oddly flat, probably need some in-game screenshots too though.

**Comment by kawaiinick** [comment]
would be cooler if i was constantly on fire, instead of reigniting every second

**Comment by arnociiroc** [comment]
yummers

**Comment by Wallemations** [comment]
> would be cooler if it was constantly on fire, instead of reigniting every second

I agree, the ignition animation looks really cool but it's kinda distracting

**Review by Wallemations — CHANGES_REQUESTED** [review]
Should have made this a change request; please make it so the startup doesn't loop
If you wanna keep the animation you can make it so it flicks the ignition sprite on initialize, and then make the loop the pulsing

**Comment by EnterTheJake** [comment]
Updated to have the animation on initialize and made the reigniting take much longer so it's not constant.

**Pull request merged**
