### PR TITLE
Birdshot Secure Tech Storage now requires Command Access

### PR DESCRIPTION
**Pull request by Eronymun**
## About The Pull Request

Adds Command Access helpers to the Secure Tech Storage doors on birdshot as to prevent everyone from walking into secure tech storage and taking the AI upload board.

Before and After: 
Before
After

## Why It's Good For The Game

Because the AI doesn't need a law telling it to do work on the genetics console - it has a tough enough life as it is.

## Changelog

:cl:
fix: You can no longer walk into Birdshot's secure tech storage like you own the place - unless you do own the place.
/:cl:

### CODE REVIEW

**Comment by Eronymun** [comment]
Oopsies I added this wacky /cl thing to my pr and I don't know how to get rid of it.

**Comment by GPeckman** [comment]
Honestly its a good thing that the autotag bot is broken right now.

> Oopsies I added this wacky /cl thing to my pr and I don't know how to get rid of it.

Basically, the CL thing lets a bot scrape the changelog so that it can be displayed in game, and is also used to automatically tag your PR. The thing you see is a template: Just delete lines that don't relate to this PR and change the ones that do. So for example you could have:

> fix: Birdshot Secure Tech Storage now requires Command Access

And delete everything else. Keep the lines with the CL emoji though, those are necessary to so the bot can understand which part of the PR is the changelog.

**Comment by Ghommie** [comment]
Proprely set the CL section for you, just don't forget to edit it yourself next time by clicking the three dots on the top right of your own post.

**Comment by Eronymun** [comment]
> Proprely set the CL section for you this once, just don't forget to edit it yourself next time by clicking the three dots on the top right of your own post.

Will do!

**Pull request merged**
