### PR TITLE
Fixes missing functionality in metal boxes

### LINKED ISSUE #47944: the relaymove proc is defined twice for large cardboard boxes
https://github.com/tgstation/tgstation/blob/master/code/game/objects/structures/crates_lockers/closets/cardboardbox.dm

```
/obj/structure/closet/cardboard/relaymove(mob/living/user, direction)
	if(!istype(user) || opened || move_delay || user.incapacitated() || !isturf(loc) || !has_gravity(loc))
		return
	move_delay = TRUE
	if(step(src, direction))
		addtimer(CALLBACK(src, .proc/ResetMoveDelay), CONFIG_GET(number/movedelay/walk_delay) * move_speed_multiplier)
	else
		ResetMoveDelay()
```

```
/obj/structure/closet/cardboard/relaymove(mob/living/user, direction)
	if(!istype(user) || opened || move_delay || user.incapacitated() || !isturf(loc) || !has_gravity(loc))
		return
	move_delay = TRUE
	var/oldloc = loc
	step(src, direction)
	if(oldloc != loc)
		addtimer(CALLBACK(src, .proc/ResetMoveDelay), CONFIG_GET(number/movedelay/walk_delay) * move_speed_multiplier)
	else
		move_delay = FALSE
```

Note that both of these are /obj/structure/closet/cardboard/relaymove(mob/living/user, direction), with neither of them being /obj/structure/closet/cardboard/metal/relaymove(mob/living/user, direction).

### PR DESCRIPTION
**Pull request by TheVekter**
### **THE COWARDS! THE FOOLS!**

Fixes #47944

### CODE REVIEW

**Comment by TheVekter** [comment]
What the fuck is wrong with my git

**Comment by ATH1909** [comment]
Honestly, just cut that block of code out. It basically just does what the large cardboard box version of that proc does, just in a slightly different way.

**Comment by py01** [comment]
this causes regular cardboard boxes to go hyperspeed when moving diagonally against a wall, the first section of code needs to be completely removed

**Comment by TheVekter** [comment]
#47967 fixes this better

**Pull request closed without merging**
