### PR TITLE
Starts the reconquer of the changelog from the profane infidels

### PR DESCRIPTION
**Pull request by nicbn**
*sighs*

### CODE REVIEW

**Comment by F-OS** [comment]
we yog now

**Comment by Iamgoofball** [comment]
freedom of speech

**Comment by Iamgoofball** [comment]
freedom of speech

**Comment by F-OS** [comment]
> freedom of speech

We america now

**Comment by DaedalusGame** [comment]
:us:

**Comment by nicbn** [comment]
> We america now

No entendo compadre

**Comment by Buggy123** [comment]
>We america now

So we should merge this and also silently flag Goof for more random searches by security?

**Comment by nicbn** [comment]
Yes

**Comment by F-OS** [comment]
yes

**Comment by epochayur** [comment]
this is a christian codebase

**Comment by nicbn** [comment]
The ancient Rome failed because they allowed profanity

**Comment by Iamgoofball** [comment]
"the ancient Rome"
chrome_2018-02-05_15-16-48

**Comment by MoreRobustThanYou** [comment]
fuck

**Comment by nicbn** [comment]
WATCH YOUR MOUTH YOU FUCKER

**Comment by MoreRobustThanYou** [comment]
_pulls out megaphone_ WOULD YOU LIKE TO SUCK MY COCK, MR @nicbn.

**Comment by PsyCommando** [comment]
If an item called the "fuck" had been added, you'd just have made it hidden from view D:

**Comment by nicbn** [comment]
Why would we add an item called fuck
I mean
# FUCK YOU MRTY

**Comment by MoreRobustThanYou** [comment]
@nicbn 
https://www.youtube.com/watch?v=yHfJcMwPXG0

**Pull request merged**
