### PR TITLE
remove hulk ignoring damage slowdown

### PR DESCRIPTION
**Pull request by Mooshimi**
## About The Pull Request
Removes assignment of trait that causes hulks to ignore slowdown from damage, and the removal when critted.

## Why It's Good For The Game
The ease of getting this mutation and it being given out to all and sundry who bust into genetics is a big issue if even one hulk in the shift is a shitter. This makes them a bit less of a threat.

## Changelog
:cl:
balance: Hulks no longer ignore slowdown from damage
/:cl:

### CODE REVIEW

**Comment by tralezab** [comment]
ah yes the monthly hulk nerf

**Comment by tralezab** [comment]
You know looking at this I realized i'm mostly sad that all hulk buffs are the most boring nerfs imaginable

**Comment by necromanceranne** [comment]
Why not just remove it? What's the actual point of hulk in the hands of crew?

**Comment by D4C-420** [comment]
> Why not just remove it? What's the actual point of hulk in the hands of crew?

The main reason I personally  take hulk is because of the stun immunity, slip immunity and Occasionally to break down some walls. I said it before but the only real way to get proper stun protection is hulk. Bath salts are the only chem which does anything against stuns and they have their own host of downsides to contend with.

**Comment by ATH1909** [comment]
> Why not just remove it? What's the actual point of hulk in the hands of crew?

forcing sec officers to use more than just bola -> batong to solve all of their problems

**Comment by ATH1909** [comment]
I'd like to remind everyone that hulks are melee-only, outside of thrown items. melee-only + damage slowdown + no bolas on hand = get kited bro gg ez

**Comment by AndroidMK2** [comment]
Hulks are unironically about to be worse than regular humans

**Comment by InsaneRed** [comment]
hulk is the most garbage mutation gameplay wise as good as it may be, i think @KathyRyals  is already working on changing it so this seems unuseful

**Comment by necromanceranne** [comment]
> > Why not just remove it? What's the actual point of hulk in the hands of crew?
> 
> forcing sec officers to use more than just bola -> batong to solve all of their problems
> 
> and also being a cult, xenomorph, and malf AI counter

That's its current use cases, but that's consequential and not deliberate design. What I'm asking isn't 'why don't you do this', it's more 'if this does get merged, what do you expect of this, and what difference does this change make in the current game compared to outright removal?'. I think we both can agree it mostly just makes it a waste of time to ever use and actively hurt you, since the damage slowdown ignoring was in response to the game changing away from stuns and into stamina. With this PR, batons and disablers work on hulks again (they don't get knocked down but they get held completely in place, allowing someone to kinda just bash them to death), so they lose a major upside compared to normal humans.

If you want something removed, bashing it with a stick and throwing a tarp over it is going to leave a rotting mess someone else inevitably has to come clean up isn't how you do it. I'm no fan of hulk, but I would think if you want to do something, it should be done properly.

**Comment by AndroidMK2** [comment]
Hulk is a good concept and should not be removed like literally everything that coders deem too op couse they got killed by such a feature, better idea is to make it relatively adjusted. Tbh hulk mutation should get a overhaul or basically morph into something different to fit more.

**Comment by jughu** [comment]
> > Why not just remove it? What's the actual point of hulk in the hands of crew?
> 
> forcing sec officers to use more than just bola -> batong to solve all of their problems
> 
> and also being a cult, xenomorph, and malf AI counter

Bola batong just becomes bola lasergun

**Comment by Krysonism** [comment]
Disabler and batong are already some of the very best weapons in the game, free and roundstart. 

They don't need to also be able to take down any convievable enemy with ease.

**Comment by Mooshimi** [comment]
> Why not just remove it? What's the actual point of hulk in the hands of crew?

Because then there'd be no chance of merging.

**Comment by moocowswag** [comment]
What about instead giving hulks some form of acceleration mechanic so they are fast when running in a straight line and slower when forced to turn alot?

**Comment by 170141183460469231731687303715884105727** [comment]
Hulk is only used for griefing, so this is a good change.

**Comment by jughu** [comment]
Give hulks melee blockchance so hulks stand superior melee :muscle:

**Comment by Watermelon914** [comment]
> Why It's Good For The Game
> All my homies hate hulk. I don't think they need damage slowdown ignore, they get great buffs even without it.

I don't think this is a good justification for removing hulk. Can you please improve this to suggest why it is better to remove this from hulk?

**Comment by Mooshimi** [comment]
> > Why It's Good For The Game
> > All my homies hate hulk. I don't think they need damage slowdown ignore, they get great buffs even without it.
> 
> I don't think this is a good justification for removing hulk. 
This isn't removing hulk. :eyes:

**Comment by Watermelon914** [comment]
> > I don't think this is a good justification for removing hulk.
> 
> This isn't removing hulk. 👀

Was tired when I wrote this, fixed.

**Comment by moocowswag** [comment]
> Hulk is only used for griefing, so this is a good change.

How does this change help stop non antag hulks from griefing.

**Comment by moocowswag** [comment]
> Why not just remove it? What's the actual point of hulk in the hands of crew?

Because the existence of hulk is the only thing keeping xenos and stun batons in check and if it goes they both need a new hard counter.

**Comment by Mooshimi** [comment]
I don't actually feel that strongly about this pr, so I'm just going to close it based on all the negative feedback.

**Pull request closed without merging**
