### PR TITLE
Xenos no longer delay round end.

### PR DESCRIPTION
**Pull request by nemvar**
## About The Pull Request

Wizard rounds can now end even if there are xenos.

## Why It's Good For The Game

This fixes staff of change wizard delaying roundend.

## Changelog
:cl:
fix: Staff of change xenos no longer delay the end of wizard rounds.
/:cl:

### CODE REVIEW

**Comment by Dawson1917** [comment]
What about when admins spawn a xeno and put a ghost's mind into it or transform someone into a xeno?

**Comment by nemvar** [comment]
In that case the admin will have to go the extra step and add the datum manually. Or just don't do that because xeno antag datums do nothing except prevent ending the round and make them show up on the roundend/antag screen. All of them are not needed in *most* cases.

It's also silly to create antag mechanics around what an admin *might* do with them.

**Comment by ishitbyabullet** [comment]
Most people who become a xenomorph get the point of their existence anyways. Only a voluntarily polymorph will make them go "guess i have to be friendly or else i get banned"

**Review by AnturK — CHANGES_REQUESTED** [review]
Bad. Just toggle `prevents_roundtype_conversion` if that's the effect you want.

**Pull request merged**
