### PR TITLE
Removes the xeno maid from tg

### PR DESCRIPTION
**Pull request by optimumtact**
TODO:
remove from donators alien queen
remove from DMI's

### CODE REVIEW

**Comment by Expletive** [comment]
Close this, dupe of #27848

**Comment by optimumtact** [comment]
? I'm allowed to open a pr someone has tried before, that's not against the rules

**Comment by Expletive** [comment]
I think everyone still hates the idea. The last PR was only a week ago

**Comment by lzimann** [comment]
This is a fantastic idea.

**Comment by KorPhaeron** [comment]
No thank you!

**Comment by KorPhaeron** [comment]
Remove the stupid donor one though

**Comment by Expletive** [comment]
Better yet, make it available to everyone.

**Comment by optimumtact** [comment]
@KorPhaeron 24 hours please

**Pull request closed without merging**
