### PR TITLE
redpills the armory

### PR DESCRIPTION
**Pull request by pudl**
:cl:
rscadd: The armory has been redesigned.
/:cl:

Before

After

the only major change is that there are only 3 sec gasmasks in the warden's office now

you don't like it? beat it! and don't let the door hit you where the good lord split you

### CODE REVIEW

**Comment by pudl** [comment]
fyi the screenshot has a scrubber where an air vent should be, i fixed that

**Comment by KorPhaeron** [comment]
Please post the before picture as well

**Comment by pudl** [comment]
what the hell

**Comment by Shapsy** [comment]
meh, having the sec hardsuits be right in the blast radius for any bombs going off seems like it would defeat the point of them, plus wouldn't the storage containers act like a barricade?

**Comment by PKPenguin321** [comment]
Why must we have a weekly armory remap
Armory fags kindly exit

**Comment by Bawhoppen** [comment]
:-1: 
this is stupid and we've had similar discussions about gun placement before
it was always decided that they're best next to the warden's office

**Comment by Bawhoppen** [comment]
actually I retract that statement it does actually seem better but remove that chair and just remove the shitty steelpoint locker full of lethal shells and put the lethal shell boxes with the other ammo

**Comment by Bawhoppen** [comment]
actually add another rack to the right of the other guns and put the tasers there and then put the lethal ammo in the old taser's spot

**Comment by Bawhoppen** [comment]
actually after several hours of thought I don't like it anymore

**Comment by Steelpoint** [comment]
What a ride there Baw.

Only thing I care about with this is how the Suit Storage Lockers have been moved north, this is a bad change. Prior at least a bomb won't blow up the suits and a looter has to break into the armoury proper to space the suits instead of deconing one wall and throwing both suits into deep space.

:-1:

**Comment by pudl** [comment]
i'll change it later today

**Comment by Steelpoint** [comment]
If that change is reverted then I see no problems with this armoury design from the image provided.

**Comment by pudl** [comment]
does anyone have any other requests

**Comment by Iamgoofball** [comment]
put a WEEWOOWEEWOO helmet in there

**Comment by pudl** [comment]
would it be a big deal if i made it so there was only 1 windoor into the armory?

**Comment by pudl** [comment]
@Steelpoint @Shapsy how do you like it now

**Comment by ChangelingRain** [comment]
Windoor to armory no longer aligned with the main brig door to warden's office would not use/10

**Comment by pudl** [comment]
fixed!

**Comment by pudl** [comment]
asking players on sybil, i've gotten 100% positive feedback. just merge it now tbh

**Comment by Robustin** [comment]
2 rechargers please

**Comment by pudl** [comment]
fixed

**Comment by pudl** [comment]
@Steelpoint still waiting on your opinion

**Comment by Steelpoint** [comment]
I kinda liked the original way the racks were set up, they allowed for more freedom of movement.

But otherwise I have nothing against this change now.

**Comment by pudl** [comment]
nice try shitcurity

**Comment by Steelpoint** [comment]
Meaning?

**Comment by pudl** [comment]
i hate when people say they feel me

**Comment by Cheridan** [comment]
it's horrible

**Comment by Dorsisdwarf** [comment]
What is it with pudl PRs and speedmerge.

**Comment by Bawhoppen** [comment]
the thing that pisses me off the most is the changelog

**Comment by pudl** [comment]
@Bawhoppen what should it have said

**Comment by Robustin** [comment]
>2 days old

Well I'll get around to commenting on it when...

>Merged

Only thing this armory does different is suck the guns out of a hull breach in record breaking time.

**Comment by pudl** [comment]
@Robustin better make a revert pr

**Comment by Shapsy** [comment]
Why is the medkit absent when it was in the picture

**Comment by pudl** [comment]
apparently map merge ate it since it also broke the shuttle

**Pull request merged**
