### PR TITLE
Removes Aux base from several jobs, moves it away from Engineering.

### PR DESCRIPTION
**Pull request by JohnFulpWillard**
## About The Pull Request

People who currently have access to aux base, with people whose accesses are removed in this PR, crossed out:

sci
~~Research Director~~
~~Scientist~~
~~Roboticist~~

sec
~~Head of Security~~
Supply officer
~~Science officer~~
~~Engineering officer~~

supply/service
Head of Personnel
Quartermaster
Shaft Miner
Curator

eng
~~Chief Engineer~~
~~Atmospheric Technician~~
~~Station Engineer~~

## Why It's Good For The Game

- Removed Science/Roboticist/RD because Science is unrelated to exploring/Lavaland, sure there's gasses for ordnance, but that can be done through public mining (and still leaves Roboticists)
- Engineering was removed because it encourages Engineers to spend their round hiding in a base and sending themselves to Lavaland rather than interact with the station, taking up a job position for someone who would otherwise use the equipment (insuls, modsuit, skillchip) to interact and repair the station.
- Security's access was removed because there's not much reason for them to enter there, it's Mining's business, so for the same reason officers don't have access to Mining, they shouldn't have to Aux base. The exception is the Supply officer, who DOES have access to mining.

That leaves just Curator (the exploration job), Shaft Miner (Lavaland is their business) and QM/HoP (their bosses).

come on...
image

## Changelog

:cl:
balance: Auxiliary base access has been removed from all jobs except Curator, Shaft Miner, Quartermaster, and Head of Personnel.
/:cl:

### CODE REVIEW

**Comment by Fikou** [comment]
engineers (the building job) not having access to the building area is dumb as hell

**Comment by JohnFulpWillard** [comment]
The aux base is an exploration thing for Lavaland, and is mostly something the Curator does.
The room spawns with an RPD, and the aux base console handles all the building part itself, removing the need for stuff like RCDs and other tools for manual work. It's well made to work as a mini-engineering outside of engie like ordnance is to atmos.

**Comment by castawaynont** [comment]
I have never seen engineers hide themselves away on the aux base ever. Also, this thing is criminally underused anyhow, why bother gating the access at all? If it's the mining locker that's the problem, just make it start locked or something.

**Comment by Farquaar** [comment]
Why though? I want to aux bases more often- its a cool feature that's tragically underused.

**Comment by Shadowflame909** [comment]
Why lock more people out of this underused feature?

I mainly use it when im a cultist scientist though so...

**Comment by Comxy** [comment]
As engineer, one of the only good ways you can still farm gasses from lavaland is though the aux base since you cannot create areas anymore on lavaland with all the misc tiles.

**Comment by Son-of-Space** [comment]
If it's supply business why wouldn't the supply officer have access to it?

I know we talked about it in discord but the more I think about it and the more feedback I see the more I'm feeling it's not a good idea to limit access to it.

**Comment by JohnFulpWillard** [comment]
The public mining area exists, Atmos techs could easily go there instead.

I do not understand the argument behind "its underutilized so we should let everyone and their mothers have access to it", should Construction, the Library, Psychology, and Law Office also be accessible to everyone?
Underutilized doesn't mean we should just let anyone access it, it makes the problem worse because then you don't even know who is/isn't supposed to be operating it.

Aux base is a lavaland exploration thing, a mini-engineering job where all the engineering work is already done for you, through the console. If Engineers/Atmos techs/Scientists/ect want to use it to farm gasses, then they can ask for access in-game, like any other access they would want to do their jobs better but aren't necessary.

**Comment by Shadowflame909** [comment]
Okay but what's the point of miners being able to locate a safe place for base building, the game announcing it to everyone, only for miners to be the only one to use it?

Literally just remove it at that point. It was the pre public mining before public mining

**Comment by Edelor68** [comment]
All updates should serve somehow to make the game more enjoyable. The only argument for that in the "Why It Is Good For The Game" section is: 

> Engineering was removed because it encourages Engineers to spend their round hiding in a base and sending themselves to Lavaland rather than interact with the station, taking up a job position for someone who would otherwise use the equipment (insuls, modsuit, skillchip) to interact and repair the station.

Which I have never seen or even heard of. 
Yes, technically it makes the game a tiny bit more realistic but only at the cost of removing gameplay options from people which is something that definitely makes the game LESS enjoyable.
If it were a balance issue that too many people have access it would be a different story but I don't really see that here.

**Comment by Fikou** [comment]
> > engineers (the building job) not having access to the building area is dumb as hell
> 
> atmos techs (the gas job) not having access to the gas building area is dumb as hell, should we give them ordnance access?

But they do. They have access to atmos. Ordnance is also a part of science, while Aux Base is a general area.

**Comment by Pickle-Coding** [comment]
It's weird that engineers don't have access to a yellow airlock. The aux base is rarely used, but it does make lavaland and miners less separated from crew when crew wants to do a project in lavaland.

This PR just makes mining even more isolated from the rest of the game, and miners will get even worse social skills than they already do because they will be even less likely to interact with crew.

**Comment by JohnFulpWillard** [comment]
> But they do. They have access to atmos. Ordnance is also a part of science, while Aux Base is a general area.

Ordnance is gas-making, atmos techs don't have access to it, they do it elsewhere instead (atmos)
Same can be said for engineers, they are still able to build things, aux base isn't the only place where construction is possible.

> It's weird that engineers don't have access to a yellow airlock

You commented this after I had already made all aux base doors mining-colored

> This PR just makes mining even more isolated from the rest of the game

I don't think aux base had an effect on Shaft miner isolation from the game, all it does is isolate yet another player from the rest of the station, and if it is a Curator (an exploration role) it is fine, but if it is an Engineer, especially one who took insuls/modsuit and has a skillchip, that's equipment and a job slot lost that could've instead been repairing and improving the station/engine.

**Comment by GuiltyNeko** [comment]
> atmos techs (the gas job) not having access to the gas building area is dumb as hell, should we give them ordnance access?

I think this is a thing that should happen, yes, because then atmos techs would actually contribute to the round instead of sit in atmos and make funny gasses that never leave the room. This is a bit off-topic though, to be fair.

**Comment by Son-of-Space** [comment]
I think locking most of the crew who might reasonably have access to an alternative exploration or gameplay option is probably not the way to go about this change, especially when that access is low-impact to the course of normal rounds.

**Comment by ATH1909** [comment]
> that's equipment and a job slot lost that could've instead been repairing and improving the station/engine.

imo, setting up an aux base _is_ improving the station.

**Comment by datorangebottle** [comment]
This PR is attempting to address a player issue by pretending it's a code issue, and completely fails to actually do anything about it.

If someone is faffing about in an engie modsuit instead of fixing one of several holes in the station, you're not going to fix it by removing their aux base access. At best, they'll break open the doors. They are now mildly inconvenienced. At worst, they'll just pick an empty room in maint somewhere instead, which means the equipment is now a drain on the station's power and is far less likely to benefit anyone except that engineer in any way. At least if they build the base in aux mining, you can launch it and let the miners get some use out of it.

People will always take and misuse limited equipment. Modsuits. Spacesuits. Batons. Insuls. Fireaxes. The game is designed around incompetence, greed, and paranoia. You aren't going to fix equipment shortages by removing access to a room. 

_Also, most of the roles you're trying to lock out of the room have roundstart access to tools they can use to just break in and build the base anyway._

**Comment by JohnFulpWillard** [comment]
> If someone is faffing about in an engie modsuit instead of fixing one of several holes in the station, you're not going to fix it by removing their aux base access.

They can still get access sure, but at least that means they got access (so approval) to leave the station by HoP/Cap/QM if they become command.

> At best, they'll break open the doors. 

And not be able to use the console, sure.

> At worst, they'll just pick an empty room in maint somewhere instead

Then they can't go down to lavaland with it, which is the whole point of the aux base, and on-station it means maint explorers can run into it which I find more worthwhile than a goliath.

> Also, most of the roles you're trying to lock out of the room have roundstart access to tools they can use to just break in and build the base anyway.

That's none of my business, and again no computer access.

> People will always take and misuse limited equipment. Modsuits. Spacesuits. Batons. Insuls. Fireaxes. The game is designed around incompetence, greed, and paranoia. You aren't going to fix equipment shortages by removing access to a room.

Again, what players do in-game is none of my business. I just don't think we should be encouraging them to abandon the station with it, though.

**Pull request closed without merging**
