### PR TITLE
Adds 15-force edaggers that look and function like pens when off.

### PR DESCRIPTION
**Pull request by theOperand**
They cost 3 TC. Currently only comes in red, cant be bothered to make more colors tbh.

Sprites are a bit ugly but surprisingly passable.

They fit in PDAs and all that jazz.

### CODE REVIEW

**Comment by Chocobro** [comment]
oooh this is fancy :+1:

**Comment by Steelpoint** [comment]
I like it, cheaper alternative to the Esword :+1:

**Comment by Anonus** [comment]
Why not make them multitools or at least use bits of these sprites?
http://puu.sh/jBgq2/705f8b5601.dmi

**Comment by SconesC** [comment]
I guess they're supposed to be throwing weapons

Cool

**Comment by Miauw62** [comment]
not really supposed to be throwing weapons, but rule of cool.

**Comment by SconesC** [comment]
I'd rather finish someone with THROW FORCE 35 and an embed than bother to stab them 7+ times

**Comment by Miauw62** [comment]
i still consider 15 a decent amount of damage. same as fire extinguishers, and this is extremely concealable. i can reduce the throwforce if you like, i really dont have much of an idea of how much damage embeds do.

**Comment by Anonus** [comment]
Embedding does 10 damage but hey throwing stars are still better than this would be

**Comment by SconesC** [comment]
Anonus are you talking 10 for embed or also removal damage

I guess this is a SUPER small esword that hides in PDA/clipboard 

Cool?

**Comment by Miauw62** [comment]
basically the point, yeah.
people do seem to like it.

inb4 surplus crates with 15 daggers

**Comment by PKPenguin321** [comment]
yes and make it so you can also fit ninja stars and floor tiles into the belts

:+1: :+1: :+1: this is great

**Comment by Stenthus** [comment]
love the idea

it is odd though that an ENERGY DAGGER does 15 damage vs a switchblade's 20 or a spears 18

**Comment by SconesC** [comment]
Just put Military Belts in traitor uplinks at a decent price

They can hold pretty much any antagonistic item, I'd love to be able to buy a handgun, emag, and then have something that can conveniently hold all my spare magazines

Fuck I'll do that in like twenty minutes

**Comment by Cebasiz** [comment]
should also probably work as scalpels at like 80% or something

**Comment by Stenthus** [comment]
yeah fair enough pens are really easy to be sneaky with this (I don't think I've ever seen an officer search pda for sleepypens so I imagine this'll be the same)

what role would this functionally serve for traitors, though? personally I'm not sure if a 15 force melee-weapon is that valuable of an asset in the stun/ranged weapon based combat that defines the game at the moment

**Comment by Cebasiz** [comment]
apply a short term stun and have at them, with a little luck you'll probably be able to get them below the point where they started to slow down, just keep stabbing after that and you'll get 'em.

it's 3tc anyway, it'll probably see a little use by people buying syndibombs, as you can get it, a pen and an emag.

**Comment by PKPenguin321** [comment]
>what role would this functionally serve for traitors, though?

i wont need to steal the fire axe when i try to murderbone anymore

**Comment by Ikarrus** [comment]
Why not just give them switchblades. 

Mix up the meta

**Comment by SconesC** [comment]
@Ikarrus I think the intent was to give a SUPER cleverly concealable weapon

Isn't a switchblade a lesser esword? Less damage, same size.

**Comment by Cebasiz** [comment]
switchblades are robust but only really because every gangster and their mother is carrying them, the same reason why the stech is really pretty poor as a traitor weapon but very effective during gang.

i don't think the switchblade would be terribly effective as a traitor weapon.

**Comment by Lumipharon** [comment]
the only advantage in this over just carrying an extinguisher/other moderate robust item is that it is small.

Sec doesn't give a shit if you carry an extinguisher, and almost never care even if you have something like a saw or hatchet.

**Comment by Jalleo** [comment]
Can it be hidden in a pda?

**Comment by phil235** [comment]
@Jalleo  yes

@Lumipharon @Miauw62  Extinguisher are force= 10 apparently.

**Comment by Fox-McCloud** [comment]
bit late, but the force on this should have probably been higher.

15 base damage is the same as a welder--really no point in getting this for attacking people when you can just get a welder. If you want to throw stuff that sticks into people, then throwing stars are a a better niche for that.

**Comment by Fox-McCloud** [comment]
Another thing worth pointing out...pretty sure this will just "stab" the victim and do no damage at all.

**Comment by phil235** [comment]
@Fox-McCloud Oh crap, you're right, thanks for pointing it out. @Miauw62

**Comment by SconesC** [comment]
yep

**Comment by Lumipharon** [comment]
Why did this get merged?

I mean seriously, get a extended welder from the vendor - it's also a small item that does 15 damage, but doesn't cost tc's, won't get you perma'd or executed, has enough fuel to murder more then one person, and can be refueled almost anywhere on the station.

**Comment by PKPenguin321** [comment]
aside from the fact that it straight up doesnt work codewise, lumi, the reason is "why not"
if it's bad then don't buy it, nobody will force you to
not to mention the welder has limited ammo and does burn, and the only items that do 15 brute that fit in pockets are the circular saw and null rod (both of which can't really be concealed the way you can conceal a pen)

**Comment by Lumipharon** [comment]
The reason "why not" is because there is a free version of this item that anone canget regardless of being a traitor/having spare tc's, that won't get you executed for possessing.

And unless you're murderboning with your penknife so hard that you literally can't stop stabbing people, then fuel on a welder is not an issue.

You can use the same logic of "why not?" to clog the uplink full of every random possible item - lets add cable cuffs, syringes, igniters etc etc, because "why not?"

This is very different from (for example) c4 vs thermite. Thermite is not readily accessible, and c4 still has utility that thermite does not.

With this pen, you would have to go out of your way to make it more 'useful' then a welder or a null rod.

**Comment by Miauw62** [comment]
wait fuck i didnt think of the fact that pens have a snowflake attack() fff

**Pull request merged**
