### PR TITLE
USE SIGNAL_HANDLER REEEEEE

### PR DESCRIPTION
**Pull request by Kylerace**
## About The Pull Request
makes as many procs as i can find use the SIGNAL_HANDLER define which i assumed they all already did 😔 

## Why It's Good For The Game
its in contributing guidelines for a reason

### CODE REVIEW

**Comment by Mothblocks** [comment]
loool what was my script even

**Comment by Kylerace** [comment]
i think most of them came after you made SIGNAL_HANDLER but im not sure

**Comment by Cyberboss** [comment]
How'd you find these?

**Comment by Kylerace** [comment]
@Cyberboss i searched for something like `RegisterSignal\(.*.proc/` in vsc and searched for the registered proc manually across ~1100 instances of RegisterSignal(), skipping files with the number of instances of SIGNAL_HANDLER >= the number of registered signal procs because i spammed this out in 2 hours, so i definitely didnt get everything

**Review by Cyberboss — APPROVED** [review]
Seems legit

**Pull request merged**
