### PR TITLE
Adds autoimplanter to R&D designs

### PR DESCRIPTION
**Pull request by Spess-Rando**
:cl:
add: Autoimplanter designs can now be researched at R&D.
/:cl:

Adds the possibility to print an autoimplanter at high research levels. While the ability to self-implant might seem overpowered, you're still gonna need a looot of time and cooperation from other crew to get it.

### CODE REVIEW

**Comment by Kromgar** [comment]
Wait how the fuck do you get engi 7?

**Comment by GunHog** [comment]
I do not recommend this. Surgery exists to make sure all the implants require help (and this vulnerability to others).

 (Btw Engi 7 is gotten from the Machine Prototype in Cargo OR Genetics syringe with all powers)

**Comment by Repukan** [comment]
Power creep

**Comment by ShadowDeath6** [comment]
make it 7 every research level and people will still say powercreep

**Comment by Repukan** [comment]
What's the trade-off of the implants if you can just implant them yourself?

**Comment by Sligneris** [comment]
The fact that it takes a lot of work to get it, I believe.

What's the trade-off of the miner loot? What's the trade-off of a virology healing virus? What's the trade-off of genetics powers?

It's a dumb question, imo.

**Comment by ShadowDeath6** [comment]
I guess the trade off is that you need to get an extra however many research levels and the time needed to unlock it rather than getting it implanted by a doctor when you get it

**Comment by Repukan** [comment]
Well in mining you can die and have your body permanently gone if the server so much as hiccups. Even then it is random and you could get total thrash, but I don't see a scientist going through any danger to get implants.

Genetics and Virology are flawed concepts that I will not comment on, but Virology needs an experienced person and chemical materials and mining cooperation to get the strongest stuff. If they fuck up they run the risk of infecting themselves or the station.

Where's the *risk* in doing RnD?

**Comment by Repukan** [comment]
*comment on extensively

**Comment by ShadowDeath6** [comment]
just make it 7 everything so people have something else to complain about

**Comment by GunHog** [comment]
Seriously, consider the Auto-Doc idea. It is self surgery, but slow, public and potentially risky self-surgery. Surgery itself sucks because it takes so long and requires someone else to help. If self-surgery is to exist, it needs to have a similar vulnerability to normal surgery. Either you let this other guy help you, or spend a few minutes asleep where someone else can loot or kill you easily.

**Comment by Sligneris** [comment]
> Where's the risk in doing RnD?

A traitor can kill you to loot your researched items. if you try to be strict on what you do and don't distribute to the crew.  That, or in your absence, a traitor gets that stuff and uses it against the crew.

**Comment by Hatfish** [comment]
It might be a bit better if you upped the bio requirements to 7 so it would require something like an alien brain to obtain.

**Comment by optimumtact** [comment]
power creep

**Comment by Sligneris** [comment]
Saying "power creep" over and over is not an argument

**Comment by Kromgar** [comment]
Power crepe

**Comment by Sligneris** [comment]
You guys are driving me mad

**Comment by SgtxRootbeer** [comment]
The risk in rnd is similar to the chemist, or virologist. They are sitting in one place where everyone expects them to be, making them extremely vulnerable to traitors and the like.

**Comment by Supermichael777** [comment]
more specifically to get power they have to sit in one place. Genetics being a smoking crater is typical and viro is trash and both can loose all their powers to a syringe gun.  RnD is comparatively powerful but needs other jobs to pull through to get the real fun stuff.  Xeno is griffjuice and rnjesus death grenades. Toxins is on fire.

**Comment by PKPenguin321** [comment]
They warned me to put a comment about not adding them to R&D in the original PR when I first made these before these PRs to do so were made

I didn't listen


These were merged on the condition that they would never be added to R&D, they're for nuke ops so they can buy implants without adding another 10 minutes of surgery to their rollout. This PR was made before and rejected, please stop.

**Comment by GunHog** [comment]
Again, @Sligneris. AutoDoc. Seriously. You and I both know this PR will be denied. Consider my alternative! It is better than nothing.

**Comment by SgtxRootbeer** [comment]
it should be biotech 7 and engineering 7.
biotech 7 seems like a basic idea, because like, its a medical device.
also, implants are rarely used anyways. i could count on 1 hand, the amount of times that i saw someone get an implant.

**Comment by Repukan** [comment]
Phazons are rarely built too, doesn't mean buffing them or decreasing their construction cost wouldn't be ridiculous power creep.

**Comment by SgtxRootbeer** [comment]
tell me, does an auto-implanter allow you to literally phase through walls?

on a side note, the mecha teleporter needs a buff. one round, a few months ago, i got it (bluespace anomoly) and it is quite shit. non-accurate teleportation of a max distance of 7 tiles, plus a lengthy ass cooldown. for all the diamond it costs, i was more offended by it.

**Comment by XDTM** [comment]
Implantation is a major drawback used to balance items, adding an item to trivialize it would mean that anyone trying to add more implants to science will be met with "They can autoimplant it anyway".
@GunHog's autodoc is better since it still has many of the drawbacks, and the benefit can be justified with a high cost/research requirement.

**Comment by SgtxRootbeer** [comment]
dont get me wrong, i like gunhog's idea too. but being realistic, that idea requires someone to actually do work and code/sprite it. if we want automatic 1 person implanters in the game, this is the simplest way to go about it.
another easy alternative is to do something like we did with tech disks, and have 4 tiers of auto-implanters. each with higher rnd costs and maybe mat costs.
maybe tier 3 and 4 can be re-usable, etc.

**Comment by XDTM** [comment]
That'd be even worse! You could just mass-print low tier ones.
I get that it would be simplest, but it just worsens gameplay as it is now. It has to have a proper implementation.

**Comment by PKPenguin321** [comment]
Also autoimplanters are really broken since the eyes update and are pending a rework, they're not suitable to be added even more to the game, this is coming from the creator of autoimplanters

**Comment by Sligneris** [comment]
I mean, @GunHog, your idea's fine, but it's too complex for me to code, so you're gonna just have to make your own PR. My suggestion involves an existing item, and if you wanna make a different item for that, I'm fine with that.

**Comment by xxalpha** [comment]
Power creep, and yes it's an argument chucklefuck.

**Comment by Sligneris** [comment]
Except not really, because you're not saying anything to support it, just throwing buzzwords.

**Comment by xxalpha** [comment]
Why are you ignoring what more experienced people here are saying?

#14879
https://github.com/tgstation/tgstation/pull/14879#issuecomment-174757004
https://github.com/tgstation/tgstation/pull/14879#issuecomment-175008370

We predicted this very PR, who the fuck do you think you are to tell us we're just throwing buzzwords?

**Comment by Sligneris** [comment]
As usual, other players are why we can't have nice things. I guess that holds true for the code.

**Comment by xxalpha** [comment]
I don't even play this game.

**Comment by SgtxRootbeer** [comment]
You bet your ass. It's why the Mecha teleporter is shit and is impossible/expensive to get

**Pull request closed without merging**
