### PR TITLE
Shields can now block stun batons

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
The code is probably not the best in the world but stun baton code in general is a horrible mess and I'm not quite ready to rewrite all of attack code to be nice and modular like projectiles.

### CODE REVIEW

**Comment by PKPenguin321** [comment]
how would you even beat a shield short of chemicals or bombs after this change

**Comment by duncathan** [comment]
Hey Kor this is awfully snowflake; I think you should rewrite attack code to be more modular :^)

**Comment by duncathan** [comment]
Also why can't you just use hit reaction for this?

**Comment by KorPhaeron** [comment]
@duncathan 

This is what it's checking. check_shields checks the hit_reaction of all applicable items.

But stun batons have this shit snowflake code that bypasses armour and shields entirely and stuns them before the attack is even resolved

**Comment by Amemelius** [comment]
I thought the idea of shields was that stunbatons were their sole major counter. They add substantial ranged defense, but are weak to a batonning. I think it's too much of a buff.

I mean, how do you even kill an eshield op after this PR other than slip spam? 75% effective bullet resistance (50% hardsuit, 50% shield), syringe immunity, stun immunity, etc.

**Comment by KorPhaeron** [comment]
>I mean, how do you even kill an eshield op after this PR 

I have another PR up making their shields energy only

>I thought the idea of shields was that stunbatons were their sole major counter. They add substantial ranged defense, but are weak to a batonning. I think it's too much of a buff.

It was never the idea of shields, just bad stun baton code. I agree it might be too much of a buff though.

**Comment by PKPenguin321** [comment]
>It was never the idea of shields, just bad stun baton code.

*[citation needed]*

**Pull request closed without merging**
