### PR TITLE
Fixes access problems with the supermatter air alarms.

### PR DESCRIPTION
**Pull request by Tokiko1**
Quickfix for the air alarms not being able to be unlocked by engineers.

Also, please review the changes that map merge did here because I am not sure why there are so many changed lines here.

### CODE REVIEW

**Comment by ChangelingRain** [comment]
while you're at it can you make all the airlocks into the SM `heat_proof = 1`

**Comment by ChangelingRain** [comment]
Also yeah it's clearing unused keys that's normal

**Comment by Tokiko1** [comment]
Would be great to have this fix merged as soon as possible. @KorPhaeron

**Comment by sawrge** [comment]
The door to the supermatter SMES room is access restricted for engineers as well. It would be nice to have that changed so engineers can get in.

**Comment by Tokiko1** [comment]
That's fixed in this PR aswell.

**Pull request merged**
