### PR TITLE
Count gorilla transforms

### PR DESCRIPTION
**Pull request by ninjanomnom**
Because I kinda need the data to balance some numbers

### CODE REVIEW

**Comment by Iatots** [comment]
unrelated but can wizard turn into gorillas yet?

**Comment by pubby** [comment]
just curious - is this mostly for balancing rad storms?

**Comment by ninjanomnom** [comment]
Yeah and it's also an interesting enough number

**Comment by Cyberboss** [comment]
Wasted get

**Comment by Iatots** [comment]
I just realized, I have never witnessed a mirror get, damn. Not even a screenshot.

**Pull request merged**
