### PR TITLE
Fixes some SM piping issues across stations

### PR DESCRIPTION
**Pull request by scrubs2009**
## About The Pull Request

Delta station has internal SM pipes on layers 2 and 4 unlike every other station which has them on 3. This is a pain in the ass and makes it so you have to disassemble all internal parts before adding radiators on 2/4 or anything like that. I've moved them all to layer 3. I've also fixed some piping issues on other stations like omni-pipes being used on icebox and tram (bad idea) and the placement of scrubbers being right next to the pumps leading to the cooling loop on kilo so that if you replace a pump with a layer adaptor (the standard procedure on all other stations) it just pumps the SM exhaust into disposals.

## Why It's Good For The Game
Generally makes things that are much greater ass pains on specific maps no longer ass pains.

## Changelog

:cl:
qol: made something easier to use
/:cl:

### CODE REVIEW

**Comment by Ghilker** [comment]
Delta piping was on purpose, what is the reason to change it? No calling it a pain to deal with is not a reason

**Comment by scrubs2009** [comment]
> Delta piping was on purpose, what is the reason to change it? No calling it a pain to deal with is not a reason

Like I said, to enable you to work on layers 2 and 4 without having to disassemble all internal parts. This is much more dangerous and increases the likelyhood for a round start fucky wucky when on other stations it's far more simple. There's no reason to split the internal parts to two layers aside from the fact that the piping on the north side of the SM runs too close to have the internal pipes run along the walls like normal. Instead of just using a color adaptor (which I did) they redesigned the internals and fed both pipes through the same door tile. It didn't make much sense back then and just means that one station has an annoying and risky part of required setup for an optimized SM the others don't.

**Comment by Ghilker** [comment]
Hugbox pr.
The SM is a bit harder but is not a straight copy paste of meta setups. It allows you to learn about how other layers work.
What you want to do is to change a different looking SM setup to make it conform to the meta stamp because it slightly inconvenience you. Changing pipes is not hard.

**Comment by scrubs2009** [comment]
> Hugbox pr. The SM is a bit harder but is not a straight copy paste of meta setups. It allows you to learn about how other layers work. What you want to do is to change a different looking SM setup to make it conform to the meta stamp because it slightly inconvenience you. Changing pipes is not hard.

Nah. Rads was a hugbox PR. This is just making something less annoying and dumb. It wasn't done this way to add an interesting challenge. It was done this way because the mapper couldn't figure out a way to route pipes past the other side of the scrubber loop.

**Comment by Ghilker** [comment]
Lmao no it was made like that on purpose, to add a challenge and to differentiate it from other station's SMs

**Comment by vincentiusvin** [comment]
I agree with ghilker here, there was a conscious design decision made behind the layout and removing it feels out of place. Bringing some maps up to parity with the others because of an older oversight is a good idea, but this is all intentional.

**Comment by GuillaumePrata** [comment]
The SM is something you learn and then it just translates semi flawlessly from one map to another.
Now while I agree that this is good for new players, having some maps having their small differences to push players into experimenting with new ideas and issues is good, we don't need the exact same 2 minute speedrun SM on every map.

**Comment by scrubs2009** [comment]
I feel that the original setup only adds difficulty during a very small window of a player's experience. Players first starting work on the SM won't even bother with it as diverting that much from the original setup will just get them killed. Experienced players eager to experiment and tinker with the SM just see it as an annoying hassle to remove before they can add interesting things to those other layers. 
Only for a short window of time is a player experienced enough to be working with this and also new enough for it to present any sort of an interesting challenge to overcome. For everyone else it's either nonexistent or tedious.

**Comment by Ghilker** [comment]
> I feel that the original setup only adds difficulty during a very small window of a player's experience. 

That's how you feel, but is not like that

> Players first starting work on the SM won't even bother with it as diverting that much from the original setup will just get them killed. 

Good learning experience

> Experienced players eager to experiment and tinker with the SM just see it as an annoying hassle to remove before they can add interesting things to those other layers. 

It requires less than 5 minutes to change the internal setup

> Only for a short window of time is a player experienced enough to be working with this and also new enough for it to present any sort of an interesting challenge to overcome. For everyone else it's either nonexistent or tedious.

Stop trying to hugbox and conform every station to each other. Engineering and atmos already suffer from heavily copy-pasted setups. This one has a little bit of variation. Also you didn't post any pictures

**Comment by Maurukas** [comment]
This was not opened in a mergeable state, mapdiffbot has not been able to run, and you have not filled out your changelog. It's not clear what you're changing. Of the issues you list, Kilo is the one I feel might need fixing.

Station engines are the centerpiece of a department, and in some cases entire stations. I do not want to enforce uniformity on them.

**Pull request closed without merging**
