### PR TITLE
Security Biosuit Sprite/Armour Change

### PR DESCRIPTION
**Pull request by Steelpoint**
This change effects two changes on the singular Security Bio Suit in the security equipment room.

---

Change 1: The sprite for the suit has been changed to resemble a more security themed sprite, and to fit with the next change.

screenshot 2015-09-22 23 10 58

---

Change 2: The biosuit has had its armour buffed to match the exact same armour values the normal security vest has, barring the increased Biological and Radiation protection.

Values are: melee = 25, bullet = 15, laser = 25, energy = 10, bomb = 25, bio = 100, rad = 20

Do note the suit retains its slowdown.

Link to feedback thread: https://tgstation13.org/phpBB/viewtopic.php?f=10&t=4734

### CODE REVIEW

**Comment by Razharas** [comment]
>Another sec buff from steelpoint

No

**Comment by Miauw62** [comment]
raz pls

**Comment by duncathan** [comment]
@Razharas Jesus Christ man this one's at least reasonable
I have literally never seen this thing used

**Comment by Miauw62** [comment]
tbh the slowdown alone makes it a pretty bad thing to wear, i dont really see any issues with this.

**Comment by Steelpoint** [comment]
The only time this suit is worn is when someone is dragging a supermatter shard around or some clown made a bunch of radiation statues in the escape wing.

Aside from those biological or radiation situations, its a detriment to wear this suit. Akin to why no one wore riot armour until its slow down was removed.

**Comment by xxalpha** [comment]
Don't give it phys armor.

**Comment by Steelpoint** [comment]
Worst case scenario I at least want to keep some of the sprite changes.

**Comment by Dorsisdwarf** [comment]
Make the bombsuit security have be a sec bombsuit (A normal bombsuit but it looks cooler)

**Comment by Steelpoint** [comment]
What suit do you mean? There's only two bomb suit sprites in the game and the alt sprite is just whiter.

**Comment by optimumtact** [comment]
This makes zero sense to me. Like why give it armour, it's a biosuit for biohazard situations, you shouldn't wear it in general duty because thats memetastic

like the sprite though

**Comment by Steelpoint** [comment]
Military and other personal use NBC or MOPP suits to defend against Toxic or Radiation based threats even today, being essentially normal body armour with the benefit of protection against those elements.

This is a biological suit designed for security usage, meaning its only going to be prelevant when someone is doing something bad in a hostile environment that requires a biological suit. 

No one ever wears the suit for general duty ever, and the slowdown this suit has (can it even hold tasers in the suit slot?) means it'll never be used outside of very specific circumstances, armour or none.

**Comment by Steelpoint** [comment]
Ok I admit this has one advantage over normal armour aside from the biological protection in that it covers all external limbs.

But I think that's a bit of a edge case as people rarely aim for the limbs, usually only hitting the chest or head.

**Comment by Razharas** [comment]
Fine if it cant be closed lets merge it

**Pull request merged**
