### PR TITLE
RPD pipe autowrenching

### PR DESCRIPTION
**Pull request by Dennok**
:cl:
add: RPD can automaticaly wrench printed pipes to floor.
/:cl:

[why]: i like pipes.
helps build with wind and singulo pulls,
removes the need for pipe pixel hunting.

ezgif com-video-to-gif

### CODE REVIEW

**Comment by adamkad1** [comment]
science!

**Comment by Dennok** [comment]
I was thinking about making it hybrid of advanced drill and RPD

**Comment by Cruix** [comment]
This makes things a bit too easy. Maybe put it on an advanced RPD in the engilathe after some research.

**Comment by Dennok** [comment]
But it dont make many advantage. It cant greatly increase speed of pipe layering., just more comfortable,

**Comment by ExcessiveUseOfCobblestone** [comment]
Showcase eating.

**Comment by Cyberboss** [comment]
This should be an upgrade over the regular RPD

**Comment by Supermichael777** [comment]
add a toggle

**Comment by ExcessiveUseOfCobblestone** [comment]
That's actually ok then awesome.

**Comment by nicbn** [comment]
This closes and is closed by #36354

**Comment by DaxDupont** [comment]
hella cool

**Comment by Grazyn** [comment]
toolcreep disguised behind a thin veil of QoL

creating pipenets is extremely powerful and the wrenching timesink is much needed for balance

**Comment by ExcessiveUseOfCobblestone** [comment]
@Grazyn the wrenching time is still there.

**Comment by ExcessiveUseOfCobblestone** [comment]
yes because the wrench act is almost instant.

It's only slightly faster than middle mouse button click, which I don't think has any **practical** balance implications.

**Comment by DaxDupont** [comment]
It's not neigh-instant.
It is instant. There's no delay.

**Comment by ExcessiveUseOfCobblestone** [comment]
damn here I was trying to avoid gotcha since I forgot the exact time (well lack there of) and someone still gets me!

**Review by duncathan — CHANGES_REQUESTED** [review]
Either remove the unwrenching feature or make this a researchable upgraded RPD. I'll be happy with either one though I would prefer the latter.

**Comment by AlexTheSysop42** [comment]
if it's changed to a researchable one, make it also weld disposal pipes down

**Comment by ExcessiveUseOfCobblestone** [comment]
@duncathan can I ask why?

**Comment by duncathan** [comment]
it currently takes 3 clicks to lay a pipe including the middle click, reducing 3 clicks to 1 is a very sizeable speed improvement

@AlexTheSysop42 I'd be fine with that yeah

**Comment by Dennok** [comment]
@duncathan the unwrenching feature removed. Toggle added.

**Comment by ExcessiveUseOfCobblestone** [comment]
@duncathan then just add another (small) do_after fluffed up as the RPD switching to "wrench mode" to simulate the length to click?

**Comment by nicbn** [comment]
My bad, this actually doesn't close the other PR

**Comment by cacogen** [comment]
I think the code will conflict but yeah they do different things. This is autowrench, the other removes the need for separate paint and eat modes to cut out clicks and interface lag

**Comment by chesse20** [comment]
Add this pleas with no changes, auto wrench on start game rpd nao!

**Comment by optimumtact** [comment]
clearly nobody wants this change

**Comment by chesse20** [comment]
the op has 10 upvotes unlock this pleas i whant it so bad

**Comment by AlexTheSysop42** [comment]
Not exactly dennok's fault dunc didn't change his review once they made the changes

**Comment by nicbn** [comment]
10 = nobody to orange

**Pull request merged**
