### PR TITLE
Fixes non-dynamically lit areas being pitch black

### LINKED ISSUE #25164: Areas that don't need lights are dark
moon colony phi 2017-03-16 122507

### PR DESCRIPTION
**Pull request by MrPerson**
Fixes #25179 (Legitimate closing of a pull request, thanks for this bug github)
Fixes #25164

### CODE REVIEW

**Comment by OtherDalfite** [comment]
Awesome, thanks for writing this fix.

**Comment by MrPerson** [comment]
LeoZ pointed out another bug I need to fix. It never ends.

**Comment by MrPerson** [comment]
There, should be good to go unless there's a 5th issue

**Comment by Cyberboss** [comment]
There's a 5th issue #25199

**Pull request merged**
