### PR TITLE
Any restraints can be used to craft a spear now

### LINKED ISSUE #44309: Watcher sinew restraints not useable for crafting
## Reproduction:
Sinew restraints can not be used for crafting recipes, thus ashlizards are forced to powergame cable coil from other ruins or the mining station in order to craft more spears or bolas.

### PR DESCRIPTION
**Pull request by FrankFo**
## About The Pull Request

Fixes #44309 

## Why It's Good For The Game

Consistency

## Changelog
:cl:
tweak: Any kind of handcuffs, sinew included, can be used to craft spears now.
/:cl:

### CODE REVIEW

**Comment by Razharas** [comment]
nice, more content for lavaland natives

**Comment by HomocidlePancakes** [comment]
Why the fuck can you make a spear with handcuffs?

**Comment by Daxxed** [comment]
No bola ? 😭

**Comment by Tlaltecuhtli** [comment]
now perma prisoners can make a spear

**Comment by nemvar** [comment]
@Tlaltecuhtli If you haven't been able to make a spear before this, you were lacking in creativity.

**Comment by Daxxed** [comment]
They can literally smack the secbot for a baton lmfao

**Comment by habader** [comment]
Literally prisoners can already make spear

**Comment by ExcessiveUseOfCobblestone** [comment]
I don't think this makes sense for a handcuff to be craftable with the spear.

If you want you can make the sinew a child of `restraints/cable` or make sure just cables/sinew are whitelisted as acceptable selections for spear crafting.

**Comment by 81Denton** [comment]
I'm going to close this in favor of #44354

**Pull request closed without merging**
