### PR TITLE
Medhuds allow you to see the remaining damage on tend wounds surgeries.

### PR DESCRIPTION
**Pull request by TJatPBnJ**
## About The Pull Request
Medhuds let you see the remaining damage while doing tend wounds.

## Why It's Good For The Game
This makes a somewhat obscure feature more accessible and easy to use. 

## Changelog
:cl:
qol: Medhuds allow you to see how much damage remains in tend wounds surgeries, like medical analyzers do when held in the offhand.
/:cl:

### CODE REVIEW

**Review by Mothblocks — APPROVED** [review]
neat

**Comment by Ryll-Ryll** [comment]
I don't think this is a good change on account of it essentially QOL'ing away the original purpose of this feature, which was to give you little fluff-friendly feedback on your surgery progress rate. Making it default to giving you the updating number readouts removes the point of trying to dress it up. It also defeats the purpose of approximating how much longer it'll take, cause you have to do the math on the numbers in your head

**Comment by Mothblocks** [comment]
@Ryll-Ryll They're not talking about the "they are mangled up" etc text, they're talking about the health analyzer in the other hand, which is pretty obscure (I'm not actually sure how many people other than me know it's a thing), and isn't really something any MD won't have access to anyway.

**Comment by TJatPBnJ** [comment]
Medhuds do actually let you scan people, but it's barely used. It's used in the same way as sechuds let you set people to arrest.

**Comment by godspeedfunnyman** [comment]
this is a cool feature
thank you

**Comment by Ryll-Ryll** [comment]
> @Ryll-Ryll They're not talking about the "they are mangled up" etc text, they're talking about the health analyzer in the other hand, which is pretty obscure (I'm not actually sure how many people other than me know it's a thing), and isn't really something any MD won't have access to anyway.

I looked at the files changed and understand, I still am against this change

**Comment by coiax** [comment]
Eh, it makes it too easy; all doctors wear medHUDs. 😕

**Comment by Mothblocks** [comment]
@Ryll-Ryll Can you expand on that? What's the difference fundamentally between requiring a health analyzer but not wanting med HUDs to perform the same thing, considering all doctors have both?

Merge pending on your thoughts.

**Comment by Ryll-Ryll** [comment]
> @Ryll-Ryll Can you expand on that? What's the difference fundamentally between requiring a health analyzer but not wanting med HUDs to perform the same thing, considering all doctors have both, except a health analyzer requires some more fiddling?
> 
> Merge pending on your thoughts.

Because I like having that little extra bit of fiddling and description, and having some small pocket of the medical system that doesn't hit you over the head with raw numbers. This was supposed to be a little bit of helpful set dressing, with holding the health analyzer in hand being a side compromise to make it easier to see when a body could be defibbed, and I really don't appreciate being told by several people who didn't make the PR what my original intention apparently was in making it.

**Comment by Mothblocks** [comment]
Eh, I'll just stick with your guns on it then.

**Comment by godspeedfunnyman** [comment]
SAD!!

**Pull request closed without merging**
