### PR TITLE
Moves the "Targeting Module" for combat mechs from the science circuit imprinter to the Security techfab

### PR DESCRIPTION
**Pull request by Detective-Google**
## About The Pull Request

This PR simply takes the third circuit board required for creating combat mechs and moves it into the security lathe, meaning that Combat mech construction has to go through Security, similar to firing pins and other weapon restrictions

## Why It's Good For The Game

Mechs are some of the strongest weapons in the game, especially when utilized well, and unlike even simple laser guns, have no real access restriction, as anyone with a circuit imprinter can make them, this PR intends to balance this out by making the "Weapons targeting module" for combat mechs only available through security

## Changelog
:cl:
Moves the Durand, Gygax, and Phazon "Weapon and Targeting Module" circuits to the security techfab under "Electronics"
/:cl:

### CODE REVIEW

**Comment by Detective-Google** [comment]
fucking enter key, sorry

**Comment by optimumtact** [comment]
wrong repo?

**Comment by Detective-Google** [comment]
Not the wrong repo, hit enter while I was still writing like a jackass

**Comment by zxaber** [comment]
Toxins can create bombs that will wipe out a department, but robotics can't make a combat mech?

Also, the few times a combat mech is useful outside of tatoring (blob and xeno fights), having to make your way to sec to get the boards is just going to stack on time and possibly make it impossible to do.

**Comment by datorangebottle** [comment]
To be fair, most people don't know how to make toxins bombs because they change how they work every other month. Mechs are far easier to get, almost brainless, and you can stick a rocket launcher on it and instantly kill someone of your choosing

**Comment by zxaber** [comment]
I guess I shouldn't be worried because it'll mean less people taking my robo job and so I can just make borgs in peace, but it still feels like a needless gutting of a department.

**Comment by Barhandar** [comment]
The guns are an issue, why are you touching mechs instead?

**Comment by py01** [comment]
This will probably have a similar effect as that of moving all guns to the sec techfab, in that since science can't print them they will never research them, so they will almost never get used.

**Comment by Daxxed** [comment]
>they will almost never get used.

This is bad why ?

**Comment by py01** [comment]
> This is bad why ?
If we don't want them to be used, why not cut to the chase and remove combat mechs entirely?

**Comment by optimumtact** [comment]
Shouldn't this be available to the RD, so he can print it for his roboticist if he trusts them?

While I acted a long time ago to remove a lot of the guns from science, neither am I happy to give security control over all offensive weapons alone.

This really is, or should be, the domain of the Heads of Staff, as oversight and authorization staff.

**Comment by Detective-Google** [comment]
> Shouldn't this be available to the RD, so he can print it for his roboticist if he trusts them?
> 
> While I acted a long time ago to remove a lot of the guns from science, neither am I happy to give security control over all offensive weapons alone.
> 
> This really is, or should be, the domain of the Heads of Staff, as oversight and authorization staff.

That makes enough sense, _but_ right now there's no real "ID locked circuit imprinter" or similar as far as I know, perhaps have one for each combat mech spawn in the RD's locker...

 I also think if Science can't be trusted with normal guns there's no way they should have combat mechs that make them near stun immune, force security to use lethals to detain them, have weapons with incredibly strong damage values (the SRM-8 has 100 armor pen, shit even works on deathsquaddies), have really strong abilities, a good pilot in a gygax is nigh unstoppable so while maybe it doesn't make sense to be security only, there's no way just anyone with a circuit imprinter should be able to get their hands on these. Right now there's simply no effective way to take down a rogue mech, their "hard counter" of EMPs barely scratch them. There's also the issues of roboticists not doing their job and just making a durand and validhunting the entire round, the idea is to make mechs harder to get your hands on

Science isn't able to print normal guns, they got their firing pins taken away, if they can't be trusted with that, I don't think they should be trusted with free access to combat mechs, it's not like it's super hard to break in and get to the seclathe if you were determined, but it does mean you need command staff's approval before pumping out death machines.

**Comment by YakumoChen** [comment]
Mech weapons like the rocket launcher are hilariously overpowered and as HoS I will often take measures during rounds just to have a contingency against mechs, almost solely due to the rocket launcher. It's a taser that also takes away 80 health.
As a RD/Robo main I also won't be sad to see this happen, it is annoying to have Robotics waste a miner's entire load on a combat mech just to joy ride around in / find an excuse to escalate and destroy security as non-antag / and/or kill half the station as antag.

**Comment by zxaber** [comment]
So the two issues mentioned so far are "mechs aren't weak enough to EMPs", and "rocket launchers are overpowered". Seems like those would be easy nerfs that don't require locking half of Robotics' content behind somehow convincing the resident powergaming department to let you make weapons platforms.

Mech EMP resistance is, in part, governed by how good of a capacitor you put into the mech during construction. This was nerfed a bit once, it can be nerfed again if it's still too strong.

Mech rockets could be changed to fit better as an anti-mech weapon instead of a general-purpose damage weapon.

personal weapons are concealable and somewhat discrete. A mech is not, and until the mid/late game, the only combat mech available is extremely slow. Mass murder with a mech is nowhere near as easy as with a few small arms or some traitor gear, and the moment you do something you'll be surrounded by people that call out your big stompy obvious murdersuit for what it is.

Meanwhile, again, the legitimate good use of mechs (crew vs blob/xeno/whatever) will have you locked behind trying to get anyone on security to listen while they're all busy, and with xenos, you might be cut off from even getting to security in the first place.

**Comment by Detective-Google** [comment]
> So the two issues mentioned so far are "mechs aren't weak enough to EMPs", and "rocket launchers are overpowered". Seems like those would be easy nerfs that don't require locking half of Robotics' content behind somehow convincing the resident powergaming department to let you make weapons platforms.
> 
> Mech EMP resistance is, in part, governed by how good of a capacitor you put into the mech during construction. This was nerfed a bit once, it can be nerfed again if it's still too strong.
> 
> Mech rockets could be changed to fit better as an anti-mech weapon instead of a general-purpose damage weapon.
> 
> personal weapons are concealable and somewhat discrete. A mech is not, and until the mid/late game, the only combat mech available is extremely slow. Mass murder with a mech is nowhere near as easy as with a few small arms or some traitor gear, and the moment you do something you'll be surrounded by people that call out your big stompy obvious murdersuit for what it is.
> 
> Meanwhile, again, the legitimate good use of mechs (crew vs blob/xeno/whatever) will have you locked behind trying to get anyone on security to listen while they're all busy, and with xenos, you might be cut off from even getting to security in the first place.

Mechs are blatantly stronger for murderbone, especially mechs like the gygax, where the station gets wiped by them, ask people who are known for their antag murder sprees, (imsxz comes to mind) and they'll tell you, mechs like the gygax are ridiculous in their current state.

that being said, I believe in trying to balance the content we have, not just unga remove mechs.

It's also a stretch to say moving combat mechs is wiping out half of robotics, combat mechs are, and should be an absolute minority of what robotics builds,  as for giving them to the "resident powergaming dept.", you're implying that combat mechs aren't currently built by roboticists for the sole purpose of powergaming the best validhunt equipment.

It simply doesn't make sense, and doesn't line up with the rest of weapon balancing that Science has access to super lethal death mechs, whereas a normal laser is locked behind both the seclathe and a firing pin. Combat mechs have a solution, of equal or higher power to just about every weapon security can make, except extra niche things like temp gun, and dragnet.

I mained robotics, and I know for sure cutting out combat mechs isn't half of robotics' content, and most of the roboticists who only make combat mechs should be demoted and tossed in disposals anyway, because they usually _don't do their job_.

I talked to people before I made this PR, and everyone agreed that mechs needed some kind of nerf, and when I was talking about _how_ to nerf them this was what people seemed to agree with the most. I'd also highly consider a rocket launcher nerf separately, once I'm done with this, because 100 armor pen 80 damage sleep rockets are pretty wonk.

**Comment by zxaber** [comment]
>Mechs are blatantly stronger for murderbone, especially mechs like the gygax, where the station gets wiped by them, ask people who are known for their antag murder sprees, (imsxz comes to mind) and they'll tell you, mechs like the gygax are ridiculous in their current state.

Gygax mechs are really good because of their speed, I agree with that. Durands are pretty meh, though, and are what you see robotics producing most of the time when they want a weapons platform mech. The thing about mechs is that they're really awkward to use in close quarters, because you have to intentionally spin to fire behind you. You're a lot less mobile and it can lead to a quick loss of mech (and with the recent mech nerf we just had, the resulting sleep can easily lead to your death).

>It's also a stretch to say moving combat mechs is wiping out half of robotics, combat mechs are, and should be an absolute minority of what robotics builds, as for giving them to the "resident powergaming dept.", you're implying that combat mechs aren't currently built by roboticists for the sole purpose of powergaming the best validhunt equipment.

Mechs are about half of what a Robo can do based on their job. Borgs are a big part, and if you ask me they should be the highest priority. Apart from keeping them upgraded and alive, what else do you do? Make a few medibots and sit around waiting for positronics to pop online? Go through the "fun", tedious process of augmenting people? Combat mechs are the late-game/end-game content for robos, and locking them away from robotics isn't really great. As for "you're implying that combat mechs aren't currently built by roboticists for the sole purpose of powergaming the best validhunt equipment", well, it's not one hundred percent wrong, but I have already given a valid reason to be making them for the better of all crew, and why locking them behind a door on the other side of the station is detrimental to that. Anyway, there's a difference between robotics making a weapons platform that _can_ be used for validhunting, and a whole department that has half a playerbase thriving on cracking down on every little hint of antag activity (including, perhaps, asking for a mech weapons board).

>It simply doesn't make sense, and doesn't line up with the rest of weapon balancing that Science has access to super lethal death mechs, whereas a normal laser is locked behind both the seclathe and a firing pin. Combat mechs have a solution, of equal or higher power to just about every weapon security can make, except extra niche things like temp gun, and dragnet.

Again, personal firearms can be stashed in a bag and hidden until you're ready. Mechs (especially the combat mechs) can leave people a bit on edge and ready to react if it causes issues. And also again, we should probably look at the EMP damage for the mechs and adjust there first, so that Sec has a way to somewhat melt the mechs down. Maybe even making EMP damage force (or at least have a higher chance to cause) internal malfunctions like cabin fires.

>I mained robotics, and I know for sure cutting out combat mechs isn't half of robotics' content, and most of the roboticists who only make combat mechs should be demoted and tossed in disposals anyway, because they usually don't do their job.

I said half, not sit there and hog all the mats and _only_ do mechs. There's only so many players willing to play borg each shift, even with positronics. At some point, you've built all the borgs you can and have done all the upgrades and _now what_? Beg the HoS to print you a weapons board?

It is worth noting that just because Sec would rather a non-officer not have a gun doesn't mean the code solution is to prevent players from having that gun. Otherwise, why allow assistants that find cash in space to order guns from cargo?

>I'd also highly consider a rocket launcher nerf separately, once I'm done with this, because 100 armor pen 80 damage sleep rockets are pretty wonk.

An idea I had earlier when typing the other post was perhaps making the rockets only explore when they hit something solid. That would mean full damage when hitting mechs, walls, and perhaps an augmented body part, but otherwise the rocket fizzles and turns to ash and only does a tiny bit of brute damage.

**Comment by YakumoChen** [comment]
As someone who plays HoS very frequently I'd be willing to print boards for mechs if you built sec one or two first, like how they're intended for.

**Comment by PKPenguin321** [comment]
should be some sneaky sabotage-y way to get them anyways that doesnt require breaking into the brig/an emag

maybe some kind of R&D server hacking thing

**Comment by Detective-Google** [comment]
> should be some sneaky sabotage-y way to get them anyways that doesnt require breaking into the brig/an emag
> 
> maybe some kind of R&D server hacking thing

hidden weapons bay exists for this, otherwise it's not super difficult to emag your way to the seclathe

**Comment by zxaber** [comment]
>say "I didn't authorize that" and tell them to get out

Who is the HoS to authorize robotics making mechs? Captain, RD, sure, but HoS is not in charge of science. If the mech starts causing issues (even breaking in), then yeah, ion it down (and lets give sec tools _to_ kill it if they need the buff), but otherwise why are you involved? It's like the HoS running into engineering and batoning/killing the engineers because they didn't "authorize" a CO2 supermatter setup that _can_ delam into a tesla.

Maybe that's why I have so much issue with this PR even though I rarely make combat mechs. It's taking a large chunk of robtics content and saying "Sure, but only if security authorizes you, they're your boss too, now."

**Comment by Detective-Google** [comment]
> > say "I didn't authorize that" and tell them to get out
> 
> Who is the HoS to authorize robotics making mechs? Captain, RD, sure, but HoS is not in charge of science. If the mech starts causing issues (even breaking in), then yeah, ion it down (and lets give sec tools _to_ kill it if they need the buff), but otherwise why are you involved? It's like the HoS running into engineering and batoning/killing the engineers because they didn't "authorize" a CO2 supermatter setup that _can_ delam into a tesla.
> 
> Maybe that's why I have so much issue with this PR even though I rarely make combat mechs. It's taking a large chunk of robtics content and saying "Sure, but only if security authorizes you, they're your boss too, now."

In practice, sec is your boss for combat mechs, spoken or not, security will just kill mechs they don't like. the lack of being able to stun a mech means it's lethals or nothing, and if you don't do what security says it's gonna be lethals.

In terms of making it the captain's perogative? just because the armory is in security, doesn't mean the captain can't authorize or hand out weapons, but there isn't a "command fab", nor enough use for one, so it goes in security, because weapons need to be secured.

**Comment by zxaber** [comment]
How about if we instead just have the weapons board auto-add a tracking beacon? That way if need be, people (or even the AI) can just EMP-spam the mech to death from a safe distance.

**Comment by Detective-Google** [comment]
> art of their job, then that should be it. Allowing sec to hold power over other departments and not just o

Seems like the same arguement as "mechs shouldn't need materials because they shouldn't have to rely on mining" - First and foremost, this is a people game, the best gear should require cooperation, less silently making a super death mech and more "Hey hos, can I have a board for mech? yeah sure, but if we catch you with weapons other than [list] we're gonna fuck you up"

Tracking beacons are, and have been useless, I stopped even bothering to add them to mechs because they're so shit.

(also you should still PR the ideas you have because what this PR addresses is by far not the only problem with mech balance)

**Comment by YakumoChen** [comment]
Security is the authority over weaponry and I will gladly destroy any mechs I don't like for the same reason I'll organize raids in cargo it they're buying more guns then sec has in the armoury

**Comment by YakumoChen** [comment]
The comparison with the engine is also dumb. The CE is the authority on engines and can do what he wants in there, as long as it doesn't explode the station. It would be his authority to (get security to) stop any engine building in cargo, for that matter.

**Comment by optimumtact** [comment]
nobody asked you Yakumo "JLP2.0" CHen

**Comment by optimumtact** [comment]
Anyway, I've made my stance clear.

Printable by the Head and available in the RD lathe.

Someone will have to add that functionality but im not handing the game over to sec just because.

**Comment by Cw3040** [comment]
How about we differentiate a science targeting module from a security targeting module, giving the former a sort of test range firing pin that can be shorted out with EMP or emag

**Comment by Barhandar** [comment]
Again, the weapons are the issue. Just make weapons print in a box that requires head-level access, emag, or slapping it on the concealed bay mech to open.

**Comment by optimumtact** [comment]
we also don't need to go back to lockboxes thank you barhandar

**Comment by Barhandar** [comment]
Too bad printability by head alone is literally lockboxes but with more code changes.

**Comment by datorangebottle** [comment]
> How about if we instead just have the weapons board auto-add a tracking beacon? That way if need be, people (or even the AI) can just EMP-spam the mech to death from a safe distance.

This would be great if tracking beacons actually did anything. They don't currently do enough damage to even cause a malfunction in the mech. AFAIK they still break after one use, too. It would have to add about twenty tracking beacons for this to be effective.




> Anyway, I've made my stance clear.
> 
> Printable by the Head and available in the RD lathe.
> 
> Someone will have to add that functionality but im not handing the game over to sec just because.

That doesn't make your stance good. Security already has control over most other non-ghetto weapons on the station, and the majority of roboticists only join to make big stompy combat mechs and do absolutely nothing for the AI.  Security has a big issue with people randomly having combat mechs, since there are very few situations that warrant them they're generally used for the roboticist to wave his e-peen around and threaten people with rockets. They're unarrestable outside of lethal force and they tend to do a lot of collateral damage, besides being turned on the wrong people by a validhunting roboticist who thinks his job is 'Security 2.0' and not 'fix, create, and upgrade bots'. 

Traitors who want to murderbone can still install a hidden weapon compartment on an odysseus or ripley, or use the syringe gun along with random chems(that they can get on their own through various means) to shoot people full of lethal toxins.

Google has a solution that is immediately ready, plus nothing is stopping people from breaking into security and stealing the mech board- it just makes combat mechs require more effort and/or cooperation than they do now, while also allowing security to have an input or get mechs to add to their armory without having to argue with a guy who already has his own instant death rocket mech and has no reason to make any additional ones.

**Comment by zxaber** [comment]
My issue with this change isn't _solely_ that it would complicate traitor robo (I quite enjoy the hidden bay, myself), it's that it would make combat mechs hard to make during legitimate usage events such as blob or xenos, and possibly impossible even if you have all the other ingredients (mats, tech, an exofab). And there's almost certainly a better way to leash combat mechs besides locking them behind a different department.

We can change the tracking beacon. We can make it a not one-use item, so that it actually _is_ worthwhile to use. We can also look into EMPs dealing more damage to mechs, or having them cause other effects (Inability to move/fire for a short time after an EMP?).

**Comment by shellspeed1** [comment]
I would add it to the sec lathe to encourage sec to actually come and get an exo once in a while. Locking it behind having head access just seems like its going to make them harder to get when you actually need them as a nonantag. Zxaber also brought up some valid points with improving the tracking beacons in exos. Might be worthwhile to have them function as a lockdown feature.

**Comment by Ty-the-Smonk** [comment]
I mean mechs can be stunned, timestop

**Comment by datorangebottle** [comment]
> My issue with this change isn't _solely_ that it would complicate traitor robo (I quite enjoy the hidden bay, myself), it's that it would make combat mechs hard to make during legitimate usage events such as blob or xenos, and possibly impossible even if you have all the other ingredients (mats, tech, an exofab). And there's almost certainly a better way to leash combat mechs besides locking them behind a different department.

The entire point is making it so that mechs are only made when they're necessary, and sec can have a few pre-made so that if such a crises occurs they already have the stompy firepower that's completely overpowered. Current proliferation of mechs make antagging almost impossible after a certain point, and people going robo just to make big stompy for themselves so they can validhunt is a huge problem that wastes job slots.

> We can change the tracking beacon. We can make it a not one-use item, so that it actually _is_ worthwhile to use. We can also look into EMPs dealing more damage to mechs, or having them cause other effects (Inability to move/fire for a short time after an EMP?).

That'd be nice if people actually used tracking beacons. Ion gun can be tided pretty easily. Chemists never make emp grenades and the only other reliable source of EMP, afaik, is xenobio, which can also be dealt with pretty easily. On top of that, all of these methods rely on you seeing the mech first, which turns it into a game of rocket tag- do you get your stun off, or do they instantly kill you?

**Comment by zxaber** [comment]
>That'd be nice if people actually used tracking beacons. Ion gun can be tided pretty easily. Chemists never make emp grenades and the only other reliable source of EMP, afaik, is xenobio, which can also be dealt with pretty easily. On top of that, all of these methods rely on you seeing the mech first, which turns it into a game of rocket tag- do you get your stun off, or do they instantly kill you?

The point about beacons came up because I had suggested an alternative change where adding a weapons board auto-adds a beacon. Couple that alongside a change to make beacons more useful and we'd be in a good place, I think

As far as I know, the only weapon that has a guaranteed drop with one hit is the rocket launcher, and that weapon really could be nerfed to be less great against people on-foot.

**Comment by datorangebottle** [comment]
> The point about beacons came up because I had suggested an alternative change where adding a weapons board auto-adds a beacon. Couple that alongside a change to make beacons more useful and we'd be in a good place, I think

There's definitely a power issue with mechs as a whole, but even with those changes mechs are still pushed to be made without the approval of security.

> As far as I know, the only weapon that has a guaranteed drop with one hit is the rocket launcher, and that weapon really could be nerfed to be less great against people on-foot.

The rocket launcher should just be removed. Its point is anti-mech, anti-xeno, anti-blob combat and nerfing its damage makes it more useless in those roles. Removing the stun makes absolutely no sense, because it's a goddamn explosion, it should knock you on your ass. 

Besides that, all these other[non-rocket] changes could be avoided by making sure that security has a mech before the roboticist gets to run off with theirs.

**Comment by zxaber** [comment]
>There's definitely a power issue with mechs as a whole, but even with those changes mechs are still pushed to be made without the approval of security.

I still don't think it should be Security's place to "approve" robotics making a mech. No other job has to ask permission from security to make their dangerous shit.

>The rocket launcher should just be removed. Its point is anti-mech, anti-xeno, anti-blob combat and nerfing its damage makes it more useless in those roles. Removing the stun makes absolutely no sense, because it's a goddamn explosion, it should knock you on your ass.

Ideally, I think, the rocket shouldn't explode if it hits someone directly. Make it sorta poof and do a bit of chip brute damage, and cite the rockets being on a magnetic sensor trigger. This would also mean rockets don't explode on Xenos either, but in my experience they're not really great against Xenos already.

Though, honestly, I suppose I wouldn't be too sad if we just removed the rockets altogether.

>Besides that, all these other[non-rocket] changes could be avoided by making sure that security has a mech before the roboticist gets to run off with theirs.

I think focusing on the point of Sec getting a mech to counter other mechs is the wrong way to go about it. EMPs, Ions, and the mech control computer should counter mechs. Rock-Paper-Scissors is a lot more interesting than Rock-Rock.

**Comment by ExcessiveUseOfCobblestone** [comment]
Just make a different PR if you get around to it, this isn't the appropriate solution.

**Pull request closed without merging**
