### PR TITLE
Make plant analyzers into regular analyzers

### LINKED ISSUE #17039: Plant analyzer can analyze gas pipes and canisters.
because it's a child of analyzer

### PR DESCRIPTION
**Pull request by MrPerson**
Resolves #17039 technically

:cl:
rscadd: You can now analyze plants with any analyzer.
tweak: Plant analyzers are now regular analyzers. They still use the same sprites.
/:cl:

### CODE REVIEW

**Comment by xxalpha** [comment]
I think the proper way to fix this is not let plant analyzers analyze things that aren't plants.

**Comment by MrPerson** [comment]
There's no real reason to have a device that exists just to analyze plants. Expanding the general analyzer gives everyone more options, which is generally a good idea in a game like this.

**Comment by xxalpha** [comment]
Streamlining isn't inherently the right thing to do MrPerson.

**Comment by MrPerson** [comment]
No, but there wasn't any gain from having a distinct plant analyzer either.

**Comment by xxalpha** [comment]
The gain is not confusing people with a device that analyzes the gaseous contents of the atmosphere and gas containers and also delivers detailed reports about plants.

**Comment by PKPenguin321** [comment]
i support this but you may as well make a child of scanners that simply has the plant scanner sprite to make it a bit more intuitive

**Comment by bgobandit** [comment]
why would a gas analyzer do anything for plants, logically

**Comment by PKPenguin321** [comment]
wait hold on the thing i just described is what we already have isnt it

**Comment by phil235** [comment]
This is asking for confusion. How are players supposed to know this analyzer can analyze plants if neither name or description mention that functionality? :-1:

**Comment by xxalpha** [comment]
They are two completely unrelated functionalities, it makes no sense to join them in the same device like this.

**Comment by MrPerson** [comment]
The eventual goal would ideally to just have people use their analyzer on stuff to get more info.

The same logic applies to how someone is supposed to know you can wrench a table or use rods on a welder. And since that argument is moot, the entire logic chain is moot.

**Comment by Bawhoppen** [comment]
Thats really dumb, theres nothing wron with having seperate items

**Comment by Cheridan** [comment]
What if we called it a BUFF TO BOTANY instead

**Comment by Fox-McCloud** [comment]
This is dumb, Why remove a unique hydroponics item instead of fixing the issue itself?

**Comment by Ausops** [comment]
isn't a bad idea, like when grinders were merged

just name it the uni-analyzer or multi-analyzer or all-in-one-analyzer

**Comment by LatD** [comment]
If the analyzers are getting united, add xenobio slime analyzer in there too

**Comment by optimumtact** [comment]
This is just lazy

**Pull request closed without merging**
