### PR TITLE
Updated clownbox sprite to better match others.

### PR DESCRIPTION
**Pull request by Mercenaryblue**
[Changelogs]: #

:cl: 
imageadd: Updated Clown Box sprite to match the others.
/:cl:

[why]: # 
Consistency.

### CODE REVIEW

**Comment by PKPenguin321** [comment]
Pictures needed

**Comment by PKPenguin321** [comment]
Wait if you click the bots thing it show you
Dude that is awesome I had no idea

**Comment by darkpaladin109** [comment]
woah you can that?!!

**Comment by praisenarsie** [comment]
LOCAL MAN DISCOVERS GOD

(oranges joke:tm:)

**Review by WJohn — APPROVED** [review]

**Pull request merged**
