### PR TITLE
reverts offical grep

### PR DESCRIPTION
**Pull request by Fikou**
## Why It's Good For The Game
we're not the dictionary, i very much dislike this precedent and https://github.com/tgstation/tgstation/pull/78762#issuecomment-1750351247 another maintainer seemed to agree

### CODE REVIEW

**Comment by Isratosh** [comment]
but i am thesaurus

just kidding, no problem from me

**Comment by Iamgoofball** [comment]
it's an extremely common misspelling, why should we remove it?

**Comment by ZephyrTFA** [comment]
i did not intend check grep to be a spellcheck.

**Review by ZephyrTFA — APPROVED** [review]

**Comment by optimumtact** [comment]
> it's an extremely common misspelling, why should we remove it?

https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker

**Pull request merged**
