### PR TITLE
Wizards can now buy magic guardians for 2 points

### PR DESCRIPTION
**Pull request by ChangelingRain**
:cl: Joan
rscadd: Wizards can now buy magic guardians for 2 points. They are not limited to one guardian, meaning they can have up to 5. If that's wise is an entirely different question.
experiment: Wizards cannot buy support guardians, but can buy dexterous guardians, which can hold items.
/:cl:

This seems like a fun idea! Guardians are, in general, pretty bad for wizards because they give the wizard another point of attack, making them easier to kill. With no support guardian, by default wizards will also require a bit more creativity for self-healing.

### CODE REVIEW

**Comment by coiax** [comment]
Why can't they buy holocarp Joan. Surely this is the best time to deploy holocarp

**Comment by coiax** [comment]
Discount random type holocarp for 1 point, it's the fun thing to do

**Comment by XDTM** [comment]
Mindswapping sounds hilarious, you'd get actual magic stands

**Comment by dannno** [comment]
nice

**Comment by d4n0w4r** [comment]
if you can have a dexterous spirit hold an item, does that mean you could give it a staff of healing to keep you going?

**Pull request merged**
