### PR TITLE
Revert "Revert "Updates irc link in the readme.md""

### PR DESCRIPTION
**Pull request by optimumtact**
Reverts tgstation/-tg-station#14494

### CODE REVIEW

**Comment by Memendia** [comment]
This is a dumb change :-1: 

I am a meme :^)

**Comment by coalescentwinter** [comment]
Fucking stop, the OOC is being flooded.

**Comment by Bawhoppen** [comment]
oranges wins again!

**Comment by ktccd** [comment]
Yes, please stop, why even do this >_<.

**Comment by francinum** [comment]
Can you fucking not?

**Pull request closed without merging**
