### PR TITLE
Revamps derelict1.dmm into a proper derelict

### PR DESCRIPTION
**Pull request by Son-of-Space**
## About The Pull Request
Replaces the barren derelict1.dmm with something of substance.

<details>
<summary> This is the old version for those of you who were curious. </summary>

image

</details>

<details>
<summary> And here is the new. </summary>

image

</details>

This gives the ruin a little bit of extra panache, ties the world a bit more together, and is a nice homage to our sister server.

## Why It's Good For The Game

Adds substance to a previously non-substantive ruin.

## Changelog

:cl:
add: derelict1.dmm was overhauled into a derelict version of the Sulaco bridge
/:cl:

### CODE REVIEW

**Comment by Son-of-Space** [comment]
> > duelling pistol and megaphone added
> 
> map power creep spotted

image

**Comment by Son-of-Space** [comment]
Checks should be successful after they are re-ran

**Comment by wesoda25** [comment]
Looks great and should be merged, but it's worth saying that simple ruins have a place just like complex ones do.

**Review by san7890 — CHANGES_REQUESTED** [review]
Few thoughts.

<details>
<summary>Images Within</summary>

image

Should have like _some_ shower here, feels silly to just have nothing. I believe showers without plumbing store some water? Just have one or axe the curtain, up to you.

image

The issue with these is that since Fire Alarms are area-based, if someone were to activate/de-activate a fire alarm in another `/area/ruin/unpowered/`, you would have these open up as well (I am like 99% certain that's how it could end up working). Just make a subtype of the ruin area and map that in instead.

image

image

Move these lights elsewhere so they doesn't conflict with the directional windows.

image

Would be nice if you could do them for these two, too.

image

Would you mind centering your map template if you're using a larger one? Just sorta scoot everything one tile to the right to be more central.

image

These cause active turfs- but so do all closed directional firedoors right now. Just letting you know in case you weren't aware.



</details>

Might be nice to have an (unusable) intercom on the bridge, up to you on that.

**Comment by san7890** [comment]
Undraft if ready for review.

**Pull request merged**
