### PR TITLE
hair resprites (the beginning)

### PR DESCRIPTION
**Pull request by Sheits**
## About The Pull Request

I have decided to start respriting the hairs using a standardized palette & better god damn bangs.
This is HOPEFULLY the first of a few of these PRs as I want to add them little by little to get more player & spriter feedback without just dumping everything all at once. While i did struggle with a couple of these (ponytail 2 and jensen) I think these are still a step up from the originals.

I'm going to be working from the top of the file to the bottom (oldest to newest) & ignoring facial hair (its gross anyways) but please let me know if you want me to do a hairstyle earlier, or change a specific hairstyle to a reference to something (like how ponytail 2 is supposed to be Geralt or whatever). Feedback is welcome & hopefully easily applied at this stage so please let me know what you think!

Also can someone tell me how to make collapsible menus in the PR 

Screenshots of hairs in the character creator:

Dreads (complete redesign)
image

Bedhead (mostly unchanged, fixed inconsistency in turnaround)
image

Ponytail
image

Ponytail 2
image

Ponytail 5 (complete redesign)
image

Kusanagi
image
image

Half Bang
image

Jensen (i struggled with this so not much changed)
image

Very long
image

Flow Hair
image

Shorthair5 (barely changed)
image

Shorthair4 (barely changed)
image

Cut Hair
image
image

Shoulder length hair
image
image

## Why It's Good For The Game

image

## Changelog

:cl:
image: Re-sprites some of the oldest hairstyles
/:cl:

### CODE REVIEW

**Comment by CoiledLamb** [comment]
> Please comment which hairs you want me to do in the next PR, I wanna do some of the more popular ones

did i already ask you about gentle? that's one i use a lot...
80's hair might also be good

**Comment by HoodMilk** [comment]
All versions of long hair and very long hair have some pretty ugly shading right now.

**Review by Wallemations — APPROVED** [review]

**Comment by Cheshify** [comment]
Let's ACTUALLY fucking go. A lot of these flat color hairs were always annoying since they were so out of date. Great work so far!

**Comment by Donglesplonge** [comment]
i like that some of the hairs are getting reworked but i'm gonna miss ponytail 1s 70s-80s dudebro stoner guitarist looks like you walked outta a journey concert off of some really mediocre LSD with a couple of dudes you never met before kinda feel, otherwise looks good 👍

**Comment by Likteer** [comment]
Mega eyebrows 💪

**Comment by atlasle** [comment]
please keep comet's shape

**Comment by Sheits** [comment]
> i like that some of the hairs are getting reworked but i'm gonna miss ponytail 1s 70s-80s dudebro stoner guitarist looks like you walked outta a journey concert off of some really mediocre LSD with a couple of dudes you never met before kinda feel, otherwise looks good 👍

Yeah it looked like comic book guy from the Simpsons, though I wanted to have some more "normal" male ponytails because I felt like there wasn't any

**Comment by troytroy400** [comment]
> please let me know if you want me to do a hairstyle earlier, or change a specific hairstyle to a reference to something

The "bun" hair could really use early a resprite, especially since so many people use it.

As for changing/adding hairstyles, a low military style bun would be cool. The only options we have right now are high or have weird over-eye emoesque portions.

**Pull request merged**
