### PR TITLE
Update alternate_byond_versions.txt to 515.1603

### PR DESCRIPTION
**Pull request by MrsTonedOne**

### CODE REVIEW

**Comment by san7890** [comment]
image

I think we'll have to change up the "required" checks in the repository settings when this is merged it seems

**Comment by MrStonedOne** [comment]
thats fucking stupid. the requiredness of the check shouldn't be tired to the minor version.

@Mothblocks

**Comment by MrStonedOne** [comment]
Require it give each test a "name" and tie the requiredness of the test to just that given identifier. so the details like map or version can be changed live without requiring an admin merge

**Comment by Mothblocks** [comment]
ya will get to it later

**Comment by Mothblocks** [comment]
In the meantime I've removed the requirement

**Comment by Mothblocks** [comment]
Ugh, this requires serious overhauls because GitHub is not good

Right now we're using matrix tests, because it means we can run multiple at once. Matrix tests automatically create their name based on their parameters, with no way to change it. I'm figuring out a hack

**Comment by Mothblocks** [comment]
https://github.com/tgstation/tgstation/pull/74380

**Pull request merged**
