### PR TITLE
Fixes Devil Antaghud [maybe]

### PR DESCRIPTION
**Pull request by ExcessiveUseOfCobblestone**
Changes the hud "demon" into "devil" and changes sin to sintouched in the antaghud generators.

### CODE REVIEW

**Comment by phil235** [comment]
You did something wrong somewhere (478 files changed)...

**Comment by ExcessiveUseOfCobblestone** [comment]
totally devil antag hud refractor ;-)

one sec

**Comment by phil235** [comment]
I'm a bit confused, you're just renaming two procs, and those two procs are never used in the code :confused:

**Comment by ExcessiveUseOfCobblestone** [comment]
I have no idea daddio, I'm under the impression that if I made them consistent with the other antag huds it would magically work.

**Comment by lordpidey** [comment]
Yeah, I originally implemented them, but then I found out that due to how antaghuds worked, it would BREAK other antaghuds.

Basically, if I did implement it, and a gangster sold their soul or got sintouched, they would no longer appear as a gangster to the rest of their gang, and that's a problem.  (The rest of the gang would see the sintouch hud on the sintouched though.)

**Comment by ChangelingRain** [comment]
antag huds are horrible shitcode and actually legit need a refactor to support multiple huds

**Pull request merged**
