### PR TITLE
Proselytizing a window will automatically proselytize the grille under it

### PR DESCRIPTION
**Pull request by ChangelingRain**
:cl: Joan
rscadd: Proselytizing a window will automatically proselytize any grilles under it. This is free, so don't worry about wasting alloy.
rcsadd: Trying to proselytize something that can't be proselytized will try to proselytize the turf under it, instead.
/:cl:

### CODE REVIEW

**Comment by ChangelingRain** [comment]
@KingPhilipIII complained about this so here we are

**Comment by KingPhilipIII** [comment]
Great. Now I can have my nice looking windows that border space without getting sucked into the void or venting the base.

**Comment by Supermichael777** [comment]
window farm new meta

**Review by JJRcop — APPROVED** [review]
Code's good, nice QoL change. :+1:

**Pull request merged**
