### PR TITLE
Adds a new 'upper tier' .38 pistol to RnD

### PR DESCRIPTION
**Pull request by StuAhpla**
So a couple of years ago I had an idea for an alternative pistol for the detective that was a semi-automatic along with some ammo variants. I finally decided to actually put the idea to code.

The new gun uses the existing unused 'secpistol' sprite along with a new edited one for when it is empty. It is an upgrade to the existing detective's revolver, having 12 round magazines.

It requires level 5 combat and level 5 materials for the gun and magazines. The gun requires metal and silver, while the .38 magazines also require silver but are offset with a much cheaper metal cost (5000 metal/500 silver vs 30000 metal)

Further research levels gives two alternate types of ammo that can work in both the new pistol and the existing detective revolver if you are willing to pull the bullets out:
Less-than-lethal: More stamina damage, less brute damage, no knockdown effect
Full-metal-jacket: Straight 25 brute damage, requires a little bit of uranium

Speedloader versions of the new ammo types exist but are unused for now. 

:cl: StuAlpha
add: A new firearm is available for prototyping in Research and Development.
/:cl:

Why: There are currently no 'security' ballistic weapons that can be made in RnD since the SMG was removed from the list while at the same time there's no 'upgrade' to the .38 revolver like there is for the e-gun and the laser rifle (nuke e-gun and accelerator respectfully)

I tried to take balance into consideration regarding damage and material costs though they are still open for tweaking

### CODE REVIEW

**Comment by PKPenguin321** [comment]
detectives pistol but mass producible and stronger

hmmmm

**Comment by StuAhpla** [comment]
I might bump up the gun's cost, and or make it require titanium as well

Also you can already pump out advanced/nuke eguns, and those come with the same fire settings as the HoS's gun but with more ammo. I know they have a chance to irradiate or explode but in the four or so years I played this game I never seen either occur once

**Comment by optimumtact** [comment]
You're funny

**Comment by optimumtact** [comment]
Also this might be suprising to you but

>Why: There are currently no 'security' ballistic weapons that can be made in RnD since the SMG 

is by design

**Comment by Repukan** [comment]
Power creep

**Comment by Dorsisdwarf** [comment]
Hey do you know why R&D doesnt have ballistics any more?

Because they were deliberately removed.

**Comment by StuAhpla** [comment]
FYI I'm going back to the drawing board for this one

**Pull request closed without merging**
