### PR TITLE
remove thy slap

### LINKED ISSUE #31786: Slappers can break windows
They can also be used to break stuff you normally couldn't barehanded (windows for example)

0/10

### LINKED ISSUE #32044: You slap Unknown in the r_arm!
1. *slap
2. aim at arm
3. You slap Unknown in the r_arm!

### PR DESCRIPTION
**Pull request by praisenarsie**
@JJRcop i didn't know how to use your patch thing so i just did it via webeditor

:cl: Frozenguy5
del: Removed slapping.
/:cl:

closes #32044
closes #31786
closes #32045

@optimumtact only a wise fruit can save me now.

### CODE REVIEW

**Comment by Anonmare** [comment]
It's :clap: a :clap: feature

**Comment by jughu** [comment]
image

**Comment by The-clown-known-as-Pepe** [comment]
🍇 👏 

FEATURE

**Comment by JJRcop** [comment]
To clarify I don't want this to happen but the revert button didn't work so I helped out.

**Comment by deathride58** [comment]
Github was a mistake

**Comment by praisenarsie** [comment]
🚶

**Comment by Alecw155** [comment]
why remove it tho

**Comment by praisenarsie** [comment]
@Alecw155 Why do you need it? It serves no point but it's just there to give 'personality' to catpeople.

**Comment by Alecw155** [comment]
What does this have to do with catpeople? For that matter, why do we need *flip? Or Megaphones? Or anything else fun that doesn't serve a concrete, utilitarian purpose? If the issue is the quality of the code, isn't that already being addressed?

**Comment by deathride58** [comment]
The sole purpose of *slap is to prevent lizards and cats from wagging their tails
Groinslapping was an emergent feature

**Comment by praisenarsie** [comment]
@deathride58 what the fuck is wrong with them waggling their tails????????????????????????????????????????????????????????????????????? it's literally a bunch of pixels on their sprite moving

**Comment by Alecw155** [comment]
@deathride58 I can't tell if you're being facetious or not, but this is a fun feature that shouldn't be removed just because of a tenuous connection to furries. I think the thumbs down on the OP speaks volumes.

**Comment by Cyberboss** [comment]
If your going to make the catpeople argument just remove the tail wag stuff

**Comment by Cyberboss** [comment]
Slapping bodyparts other than the face a bug and is being removed, I see no other reason to remove this

**Comment by JJRcop** [comment]
It's not a bug if it was intended behavior.

**Pull request closed without merging**
