### PR TITLE
LOGGING CODE IS GARBAGE (SPEEDMERGE) ~~FIXES FREON LAG~~

### PR DESCRIPTION
**Pull request by Iamgoofball**
disables logging for freon ice slips, good thing we got profiling and witness testimonies

### CODE REVIEW

**Comment by MrPerson** [comment]
Something still had to get stuck in a loop to make this a problem

**Comment by Durkel** [comment]
I warned you about those slips bro.

**Comment by kevinz000** [comment]
kek.

**Comment by Saegrimr** [comment]
If someone releases freon, it's pretty obvious who and what was affected.

I can't think of any situation where finding out exactly which tile out of the hundred frozen that someone slipped on would help.

**Comment by optimumtact** [comment]
I'm gonna merge this but I'm planning to rewrite most of the slip code this weekend.

**Comment by Iamgoofball** [comment]
"this weekend"

**Pull request merged**
