### PR TITLE
Medical HUD indicator for broken suit sensors

### PR DESCRIPTION
**Pull request by lessthnthree**
## About The Pull Request

Improves feedback for broken suit sensors and simplifies repair.

- MedHUD and crew monitor can now see if a uniform's suit sensors are broken

## Why It's Good For The Game

Beyond some easily missed examine text, there is no real easy way to find out which players have broken suit sensors. This allows medbay to be able to tell at a glance, and rectify vs. staring at the crew monitor comparing who walked in with what the sensor status is on the console. (And then yelling at them to fix their suit sensors, which half the time they don't know how to do with the cable)

There's no change to the player's selected suit sensor level (off, vitals, full data, etc.) this is only applicable to suit sensors in the BROKEN_SENSORS status that are needing to be repaired with cable coil.

image

## Changelog

:cl: LT3
qol: Medical HUD and crew console can now detect broken (shorted out) suit sensors needing repair
/:cl:

### CODE REVIEW

**Comment by SomeoneYouProbablyKnow** [comment]
Wouldnt this make more sense for the diagnostic hud? Med hud could show you if they have sensors turned off (so i can deny service to unsensored plebs)

**Comment by Wallemations** [comment]
I agree this should not be a medhud visual, since it blocks the little health state icon, which doesn't have anything to do with your suit sensors.

**Comment by lessthnthree** [comment]
> Wouldnt this make more sense for the diagnostic hud? Med hud could show you if they have sensors turned off (so i can deny service to unsensored plebs)

I put it on med because med are the ones who care if your sensors are working or not. Can't find your dead ass on the crew monitoring console with broken sensors.

**Comment by SomeoneYouProbablyKnow** [comment]
Medical cares if your sensors are on or not, so an element for someone without sensors would make sense. It's a lot of info to give out to medhud users but it'd be more useful. The only person who should care about sensrs being broken, not off, broken should be the wearer.
Maybe it should give you an alert bubble like wounds or oxy instead of relying on medhuds

But that's some of my hatered of huds seeping in. Honestly broken sensors... are just so rare compared to people forgetting to turn em on in the first place. *shrug

**Comment by lessthnthree** [comment]
> Medical cares if your sensors are on or not, so an element for someone without sensors would make sense. It's a lot of info to give out to medhud users but it'd be more useful. The only person who should care about sensrs being broken, not off, broken should be the wearer. Maybe it should give you an alert bubble like wounds or oxy instead of relying on medhuds
> 
> But that's some of my hatered of huds seeping in. Honestly broken sensors... are just so rare compared to people forgetting to turn em on in the first place. *shrug

Yeah I didn't want to add yet another HUD element, that's why my thought was that the broken sensors icon would be the lowest priority. Anything such as a virus, health state below 100% etc would of course occupy the space first.

**Comment by carlarctg** [comment]
This is half fine, half unnecessary qol. If someone doesn't realize their sensors were destroyed it's on them - sensors are randomized on purpose each shift to give plausible deniability and traitor opportunities.

I think jumpsuits with broken sensors should have their item sprite (the one you see on your hud, or on the floor) occasionally spark, if at all.

Something that would be pure qol without design considerations would just be having the broken sensor examine text tell you how to repair it. 'The sensors are fried. Use a cable to fix them!'

**Comment by SimplySmiley123** [comment]
> Medical cares if your sensors are on or not, so an element for someone without sensors would make sense. It's a lot of info to give out to medhud users but it'd be more useful. The only person who should care about sensrs being broken, not off, broken should be the wearer. Maybe it should give you an alert bubble like wounds or oxy instead of relying on medhuds
> 
> But that's some of my hatered of huds seeping in. Honestly broken sensors... are just so rare compared to people forgetting to turn em on in the first place. *shrug

And why would robotics, the only crew that cares about diagnostics hud whatsoever (and even then, not that much unless they go for mechs), care about someone not having functional sensors?

**Comment by SimplySmiley123** [comment]
> Wouldnt this make more sense for the diagnostic hud? Med hud could show you if they have sensors turned off (so i can deny service to unsensored plebs)

And why would robotics, the only crew that cares about diagnostics hud whatsoever (and even then, not that much unless they go for mechs), care about someone not having functional sensors?

**Comment by Wallemations** [comment]
> sensors are randomized on purpose each shift to give plausible deniability and traitor opportunities.

This was really my main concern tbh

**Comment by lessthnthree** [comment]
> > sensors are randomized on purpose each shift to give plausible deniability and traitor opportunities.
> 
> This was really my main concern tbh

Yeah, I agree with this. The sensor mode is a player decision and it's nobody's business what they decide to set it to. The indicator would only be in the event that the sensors have been broken due to EMP and require repair.

Sensor OK/broken however, a player is often completely unaware their sensors broke 15 minutes ago, and it's not something you notice until you're dead and medical can't find you because of it.

**Comment by lessthnthree** [comment]
> I think jumpsuits with broken sensors should have their item sprite (the one you see on your hud, or on the floor) occasionally spark, if at all. This change will make more people max out their sensors after hassling and repairs, which isn't necessarily healthy for the game when helicopter AIs monitor the sensor console all shift.

Sparks was an alternate idea to do, yeah. At the end of the day I just want to see people less wandering around with broken sensors. By medbay hounding them or if they have some visual indicator works either way.

I think just examine text on the uniform isn't enough, as that's what's currently in place.

**Comment by lessthnthree** [comment]
For the helicopter AI, Medical HUD data is also only supposed to be displayed for people who at least have sensors turned to Basic, according to the comments in the code. Not sure if that's actually the case right now. I will have to test.

**Comment by lessthnthree** [comment]
Trimmed out everything except the icon and crew monitor update, for the icon made it just a subtle change to the normal healthy icon instead of an entirely new icon:

image

**Comment by Ghommie** [comment]
Conflicts.

**Comment by lessthnthree** [comment]
> Conflicts.

Done.

**Pull request merged**
