### PR TITLE
Fixes DiscStation

### PR DESCRIPTION
**Pull request by Strathcona**
Lots of fixes this time around. Renamed the map to avoid future hassle. Apologies for the line change spam.

[Latest Version of the map](https://www.dropbox.com/s/bpgq3bvycw3taeg/DiscStation20.png?dl=0)
- Gave some extra room to the Chapel
- Added Hardsuit to R&D
- Added a few new AI holopads
- Added a Canister port to Prisoner Transfer
- Added Lights to some areas that needed them
- Added a bunch more signs
- Added a SMES to telecoms
- Fixed observer spawn
- Fixed Shuttle
- Fixed misplaced arrivals area (unpowered airlocks)
- Fixed gaps in Fore Port maint (random space areas)
- Fixed Bridge area
- Fixed Misplaced Escape Shuttle areas
- Fixed Mixing Room Vents
- Fixed Pod Areas
- Fixed visible pipes in Janitors Closet
- Fixed Med Research Chem Shutters
- Fixed Mechbay Shutters
- Fixed Research Shutters
- Fixed Eng APC situation
- Fixes Singulo Engine wires
- Fixes AI Turret control
- Electrified a few grilles that should be electrified
- Found a few areas where maint was set to space
- Removed an APC from Bar Backroom (inconsistent)
- Removed Tinted windows
- Remodeled Gravity Generator
- Remodeled Medbay (lowered lobby)

### CODE REVIEW

**Comment by Anonus** [comment]
Did you make sure to do a basic test with dream daemon?

**Comment by Strathcona** [comment]
I did. I also ran through the departments, checked out shutters, doors, things that were broken before. Rode the shuttle to centcom at the end. Whole shebang. Looks like BYOND ate my z2 though... I'll fix that in a second.

**Comment by Shadowlight213** [comment]
Did you fix telecomms having the wrong area? The actual chamber was set to the abandoned satellite, meaning telecomms was pulling power from the apc over there.

**Comment by Strathcona** [comment]
Yeah, I ended up fixing that just now along with the Brig Backup Power and a few more spots in maint. The area icons are terrible and should be redone at some point since both Tcoms server and abandoned Tcoms use the same icon. I'd love to rename the maint to "Fore Port" or what have you instead of "Bar Maintenance" and the like since it's all based on Box and not any other map.

**Comment by Shadowlight213** [comment]
Not sure if it's worth it just for renaming, but if you need extra areas, you can define some new ones in a code file and make that file only be loaded when your specific map is loaded.

**Comment by Jordie0608** [comment]
You can just rename areas with the mapping tools.
Also you'll need to update the map.dm file to the new map.dmm name.

**Comment by Miauw62** [comment]
pls no rwalls for medbay, that's just dumb.

also merge conflicts.

**Comment by Strathcona** [comment]
Yeah, Medbay walls are getting fixed. I have no idea about merge conflicts. I've literally only edited three files and I'm sure no one else has touched them.

**Comment by Strathcona** [comment]
Redoing the PR from scratch. I'll get a hang of git eventually.

**Pull request closed without merging**
