### PR TITLE
Malt liquor fixes.

### PR DESCRIPTION
**Pull request by sergeirocks100**
## About The Pull Request

This improves malt liquor some.

It makes it a bit cheaper in the Booze-O-Mat.

It also adds malt liquor to the booze dispenser.

## Why It's Good For The Game

At its current price of 66 credits, there's no reason to actually drink it when other alcoholic beverages are the same price and are stronger, this fixes that.

With it being in the booze dispenser, it's also now in pretty much limitless supply, rather than only the 6 bottles that come in the Booze-O-Mat.

## Changelog
:cl:
add: Malt liquor is now available in the booze dispenser.
balance: Reduces the price of malt liquor in the Booze-O-Mat to give some reason to buy it over other equally priced drinks that are stronger.
/:cl:

### CODE REVIEW

**Comment by CRITAWAKETS** [comment]
wait malt liquor wasnt ridiculously cheap? the hell

**Comment by wesoda25** [comment]
PR title isn’t exactly accurate

**Comment by ExcessiveUseOfCobblestone** [comment]
Dont be dishonest in PR title

**Comment by ExcessiveUseOfCobblestone** [comment]
also isnt this garbage on the item :omegalol:

did you test the change to see if it worked

**Comment by sergeirocks100** [comment]
I don't see the issue with the title, there were issues with malt liquor, and i at least attempted to fix them.

I did test it now, and the price wasn't actually changed, but i fixed that.

**Pull request merged**
