### PR TITLE
Makes a thing use a define

### PR DESCRIPTION
**Pull request by Cyberboss**

### CODE REVIEW

**Comment by Cruix** [comment]
What about that comment right above it

**Comment by Cyberboss** [comment]
TICK_CHECK != CHECK_TICK

**Comment by Cruix** [comment]
You should remove or reword the comment because it no longer applies

**Comment by Cyberboss** [comment]
It does apply though, what's happening is we need to make the call into
SSatoms before and after stoplag, it's still custom.

The define is literally the exact same thing as the text it replaced

**Comment by RemieRichards** [comment]
```
 //custom CHECK_TICK here because we don't want things created while we're sleeping to not initialize
 if(TICK_CHECK)
 	SSatoms.map_loader_stop()
  	stoplag()
  	SSatoms.map_loader_begin()

#define TICK_CHECK ( world.tick_usage > CURRENT_TICKLIMIT )
#define CHECK_TICK if (world.tick_usage > CURRENT_TICKLIMIT)  stoplag()
```
SO Cyberboss' code is not exactly ```CHECK_TICK```, but contains most of the code of ```CHECK_TICK```, therefore it is a "custom ```CHECK_TICK```", so the comment is valid.

**Comment by Cruix** [comment]
If it is a define it is not custom anymore

**Comment by RemieRichards** [comment]
Yes it is.

```CHECK_TICK``` is defined as calling ```stoplag()``` when a certain threshold is met, that threshold is ```TICK_CHECK``` (though ```CHECK_TICK``` chooses to simply rewrite it out.

Cyberboss' code is defined as calling ```SSatoms.map_loader_stop()```, ```stoplag()```,```SSatoms.map_loader_begin()``` when a certain threshold is met, the threshold being ```TICK_CHECK```

So, all of ```CHECK_TICK```'s code is in Cyberboss' code, but Cyberboss' code also contains two proc calls necessary to start and stop the maploader, so things initialise correctly.

It is in essence, a modified ```CHECK_TICK```

Now shush.

**Comment by Cruix** [comment]
There are multiple instances in the code where TICK_CHECK is used. The comment could say something like "TICK_CHECK her instead of CHECK_TICK because ..." instead of implying that this is the only custom instance of this define in the entire code, or the comment could be removed and anyone who sees it can look up the define to see what it does.

**Comment by Cyberboss** [comment]
I made TICK_CHECK I know where it's used

```
git grep [^_]TICK_CHECK
__DEFINES/tick.dm:#define TICK_CHECK ( world.tick_usage > SLOTH.CURRENT_TICKLIMIT )
game/objects/explosion.dm:              if(TICK_CHECK)
game/objects/items.dm:          if (TICK_CHECK)
game/objects/items/weapons/storage/storage.dm:          if (TICK_CHECK)
game/objects/items/weapons/storage/storage.dm:          if (TICK_CHECK)
```

It's used to indicate that something wants to know if its lagging, but wants to do something instead of just alling `stoplag()`. The comment isn't invalid, it's just verbose

**Comment by ExcessiveUseOfCobblestone** [comment]
who cares it is beneficial to the game?

**Pull request merged**
