### PR TITLE
Removes the gang gamemode

### PR DESCRIPTION
**Pull request by lzimann**
Alright, so where do I start with this?
Gang is a gamemode that in theory would add fights between factions, but in practice it's just a rev with a different objective(dominate the station instead of killing the revs).
The mode is not maintained or has improved for the last year, and I honestly doubt it will change anything.

If anything, this mode should be reworked from scratch other than being rev 2.0.

### CODE REVIEW

**Comment by XDTM** [comment]
If it gets us datum antags faster i'm ok with this

**Comment by ExcessiveUseOfCobblestone** [comment]
gang is already datum based though :^)

**Comment by Kromgar** [comment]
gang is shit. It's unequivocally shit.

Its decided on which department the gang heads start in. It just results in endless shuttle recalls until somebody waits until the last secodn to drop their dominator that takes 10 minutes to win the round in a room made entirely of rwalls

**Comment by coiax** [comment]
I mean, you could have removed it when it got taken out of rotation, you're only making this PR because current headmins have brought it back.

**Comment by lzimann** [comment]
Could've and should've. But the reasons would be the same as now.

**Comment by lzimann** [comment]
Plus, I was, probably, going to do this with datum antags PR, but that took way longer than I expected, so I decided to just do it now.

**Comment by PKPenguin321** [comment]
It could be improved and a large number of players already like it as is. Hating the mode evolved from some people not liking it and removing it from rotation to hating it being the popular thing to do. I don't want this to go the way of shadowling. :-1:

**Comment by lzimann** [comment]
"Could be improved". Sure it could, but no one has ever done it.

**Comment by Kromgar** [comment]
>Could be improved 

it hasn't been improved ever its fucking garbage

**Comment by bgobandit** [comment]
someone put the lziard back in its cage it's acting agitated

**Comment by CPTANT** [comment]
I have already said this before but there are several easy ways to fix certain problems with the gangs gamemode:

1. remove lieutenants and let each gang spawn with multiple leaders. This prevents gangs from dying early by having an incompetent leader or getting fucked by bad job rolls.

2. Remove implants breakers. They are a snowball item that only makes the leading gang stronger.

**Comment by CPTANT** [comment]
Another idea is making gang graffiti only visible to gangs, so security doesn't go berserk and implant the entire crew at the first sign of paint on a wall.

**Comment by ChangelingRain** [comment]
Take improvements from clockcult; 3x3 dominator, some global announcement/indicator, reasons to not just hide it in a big box(clockcult doesn't actually have this but they're oddly fond of displaying it)

**Comment by CPTANT** [comment]
I would say these are easy to implement changes that will have a significant effect and trying them out is certainly preferable to just removing the gamemode.

**Comment by lzimann** [comment]
So someone go and improve the gamemode, personally I don't think it will make it any better(it still has one huge downside: it is a conversion gamemode) so I won't waste my time on it, instead, I believe the game will be in a better place without gangs.

**Comment by NikKirstein** [comment]
For once, Coiax said it perfectly.  You are only making this PR now because the current headmins brought it back.

**Comment by Niknakflak** [comment]
Coiax said it perfectly.

**Comment by InsaneHyena** [comment]
>The gamemode could be improved!1111
Then go on and fucking improve it. No one did for a year.

**Comment by PKPenguin321** [comment]
Hard to do that when people are so focused on removing it

**Comment by Robustin** [comment]
I'll make some basic improvements but I've literally spent the last 3 days dealing with you completely breaking cult while I was working on a cult PR when I had meant to put up a semi-final Heist PR, which in turn delays any attention I could give to this.

I agree that GW deserves a chance. I legitimately think we should consider making a drastic change to how we approach it. I'd consider Kevinz000 suggestion of flat out disabling sec + weapons production for the round and making the round a fast-paced decent into anarchy without the constant dependence on loyalty implants for deciding the outcome. Pretense: NT has stopped deploying security personnel + weaponry on select stations in order to save on costs, various employee unions have reacted in violent protest to these changes, these unions have taken on codenames and started operating more like gangs and collective bargaining units... rumor has it they've been forcefully recruiting other crew and attempting to seize these "cost cutting" station in order to send a powerful statement to NT. 

Or the simpler solution: Cut dom times by 50% since its the biggest source of cancer gang rounds. With 6+ minute timers gangs only attempt to win when they've already won or out of sheer desperation (because theyve already lost). 

Sharpen the come-back mechanics, make LT's exist at roundstart and automatically assume the boss position when the boss dies (promotion is a snowball mechanic, good players promote people they know are robust, newbies sit around not even realizing promotion exists and/or hand it out to other randos). Make the dominator fights short and sweet but have a simple dominator requirement for no closed turf within 3 tiles of the dominator (blah blah signal interference).  Gang tool recalls would be very limited, maybe one per gang. 

GW rounds should be short and sweet, dragging them out has almost never produced a close or exciting round. Eventually one gang (or Sec Gang) gets the upper hand because they have superior players which gives them superior numbers which gives them an insurmountable advantage. Keeping the round short prevents snowballs from materializing and ensures multiple factions are still competitive when the dominators drop.

**Comment by lzimann** [comment]
I guess one year is not enough time to make improvements. Just like telescopes, when someone finally pulls the trigger, or wants to, you get a lot of people that suddenly have the "great" solution to it.

**Comment by CPTANT** [comment]
-"Suddenly" have the solution to it-

yeah, no. This shit was all communicating long before.

https://tgstation13.org/phpBB/viewtopic.php?f=10&t=9146

https://tgstation13.org/phpBB/viewtopic.php?f=2&t=8397&start=50

The ONLY thing that is missing is a maintainer.

**Comment by lzimann** [comment]
You don't need a maintainer to make a PR, anyone can do it.

**Comment by Robustin** [comment]
It's not like you guys make it really extremely stressful and risky to try and overhaul a mode when your name doesn't rhyme with More-Hair-On.

**Comment by KorPhaeron** [comment]
>I'd consider Kevinz000 suggestion of flat out disabling sec + weapons production for the round and making the round a fast-paced decent into anarchy without the constant dependence on loyalty implants for deciding the outcome. 

Unironically I would merge this at 24 hours in if you made sec/armory not spawn

**Comment by coiax** [comment]
I'm not sure if job code is flexible enough to allow that, but it sounds like a bemusing idea.

**Comment by lzimann** [comment]
Well, removing security and armory is more than possible, did it myself already.

**Comment by Robustin** [comment]
The only part I wouldn't know how to do is redirect sec players to other roles. Keep in mind that RND and Cargo would need treatment too. 

I haven't kept track of the RND powergame lately, without access to roundstart firing pins RND would have significant difficulty in producing viable weapons right?

**Comment by CPTANT** [comment]
Seriously what kind of fucking bullshit is this. 

Instead of even trying the improvement PR's that are up you just remove the gamemode

**Comment by KorPhaeron** [comment]
@ChangelingRain @ausops @PKPenguin321

**Comment by PKPenguin321** [comment]
Dude what the fuck

**Comment by Kromgar** [comment]
hahaha

**Comment by Robustin** [comment]
How to be absolutely shit:

LeoZ: Takes gang out of rotation so nobody wants to develop it.

New headmin takes interest and queries players about adding GW back, sees wide support for the proposition

GW finally gets reintroduced, people's start expressing fresh ideas about improving the mode now that it's not pointless

LeoZ: Hooooold the fuck up nobody gets to save is this mode! Nobody is even trying to improve it!

 Me: Because you fuckers tend to screw people over as soon as they invest some effort

 LeoZ: Nuhuh

Me: OK fine, here's the first steps to making it into a better...

Oranges: HAHAHA, you fell for this shit again? GET FUCKED.

**Comment by duncathan** [comment]
remove don't improve

**Comment by FantasticFwoosh** [comment]
I would have preferred if this was commented out rather than removed if its possible to do that cleanly until we actually have a plan what to do rather than in a weeks time of really intense brainstorming we have to slowly revert this controversial pr again.

**Comment by coiax** [comment]
No, commenting code is evil. This is git, it's not like we've lost the code.

**Comment by McBawbaggings** [comment]
Real fucking question here: Why are you removing an entire gamemode and not making a changelog entry about it? Is that not such a substantial change to the server that it warrants letting the playerbase know when they log in? 

You have players here offering feedback about changing the mode and instead of addressing the points, you go through with a removal of the mode. 

This is poor behavior lads. At the end of the day, the server should be fun for the players and the players invested enough to talk about code changes on the github have been neglected while the rest of the playerbase might not even be aware of this change.

**Comment by McBawbaggings** [comment]
I'd also add while /tg/ is a different beast from hippie, and I might not have a grasp of how your players feel about gang, this PR comment chain here shows it's at the very least controversial and I can see the PR has been merged without an explanation from those who do think it's a good idea as to why people's insights here are unfounded.

**Comment by lzimann** [comment]
Oh, changelog, right, honestly forgot about it. I'll push/open a pr to include it.

**Comment by McBawbaggings** [comment]
A step in the right direction about this change, good on you lad. Although, it's still shocking that several of your maintainers had seen this PR and not a single one of them said "Please add a changelog."

**Comment by optimumtact** [comment]
@McBawbaggings go back to hippie

**Comment by coiax** [comment]
@McBawbaggings ignore Oranges. Welcome to /tg/.

**Pull request merged**
