### PR TITLE
Removal of Secret Extended

### PR DESCRIPTION
**Pull request by Ty-the-Smonk**
## About The Pull Request
Removes Secret extended
Oranges is gay

## Why It's Good For The Game
I don't think I've ever heard a player honestly say they liked secret extended, just announcing that its extended can make the whole atmosphere of the game flip from a "who is gonna murder me in 2 seconds." to "hey why don't I try to RP and have a good time." extended is also when you get the 6 SM crystal autism project.

## Changelog
:cl:
del: Secret Extended
/:cl:

### CODE REVIEW

**Comment by carshalash** [comment]
image

**Comment by SpaceManiac** [comment]
Secret extended can be useful in running events, the configs already exist to remove it from random rotation.

**Comment by kriskog** [comment]
Extended > secret extended. Headmins should work the current secret extended % into extended. No balls.

**Comment by nemvar** [comment]
ZVBP

**Comment by carshalash** [comment]
Secret extended encourages people to actually play the game instead of instant suicide after the announcement because "unga no antag"

**Comment by Ty-the-Smonk** [comment]
> Secret extended encourages people to actually play the game instead of instant suicide after the announcement because "unga no antag"

and thats how you get banned for antag rolling

**Comment by kriskog** [comment]
Secret extended is nothing but a waste of time. If you manage player expectation properly by making it a proper greenshift instead, sure the people who arent interested in extended might off themselves. But they werent going to add anything to the shift anyway. The ones who are interested can keep going and have fun, without 20 gamer-geared validhunters getting bored and turning to griefing.

**Comment by wesoda25** [comment]
Secret extended is good. Its one of our gamemodes most fitting to the idea of SS13. Paranoia is a huge element, and sextended is a shift in which your paranoia is baseless. It encourages roleplay and lets people have fun in their own way. Just because it doesn’t cater to the demands of valid hunters doesn’t mean it should be removed. 

If anything announced extended is worse since it removes the paranoia aspect of SS13. Its only good for projects, and I don’t think many older players like it very much, since we’ve done everything thats available numerous times. Still both should remain in the game.

**Comment by Whoneedspacee** [comment]
> Secret extended is good. Its one of our gamemodes most fitting to the idea of SS13. Paranoia is a huge element, and sextended is a shift in which your paranoia is baseless. It encourages roleplay and lets people have fun in their own way. Just because it doesn’t cater to the demands of valid hunters doesn’t mean it should be removed.
> 
> If anything announced extended is worse since it removes the paranoia aspect of SS13. Its only good for projects, and I don’t think many older players like it very much, since we’ve done everything thats available numerous times. Still both should remain in the game.

/tg/ is not a roleplay server. most people won't roleplay outside of just talking to people unless they're explicitly told "hey its the round where we roleplay and build shit together"

**Comment by wesoda25** [comment]
You fucking chimp if you do more than ignore everyone you’re roleplaying. Its a low degree of roleplay, but its roleplay none the less. People create their own issues on secret extended rounds, so most of them aren’t boring. Its a good round type that allows people to be spacemen without the threat of an antag. Just IC interactions.

**Comment by PKPenguin321** [comment]
Used for admin events, already a config option. Start a policy discussion if you want the mode out of the rotation

**Comment by kriskog** [comment]
> 
> 
> People create their own issues on secret extended rounds, so most of them aren’t boring.

But thats the fucking problem. Don't go calling other people chimps when you haven't even grasped the core of the issue.

**Comment by carshalash** [comment]
> > People create their own issues on secret extended rounds, so most of them aren’t boring.
> 
> But thats the fucking problem. Don't go calling other people chimps when you haven't even grasped the core of the issue.

Shitters will be shitters no matter what.

**Comment by Ty-the-Smonk** [comment]
> Used for admin events, already a config option. Start a policy discussion if you want the mode out of the rotation

Admin events are usually dumb and disrupt rounds, they only usually cause problems from what I've seen in the past

**Comment by wesoda25** [comment]
> > People create their own issues on secret extended rounds, so most of them aren’t boring.
> 
> But thats the fucking problem. Don't go calling other people chimps when you haven't even grasped the core of the issue.

I’m not referring to tiding. I’m referring to gimmicks gone wrong, arrogant heads, etc. Antags are not mandatory to propel a round and make it interesting, simply a guiding factor. Secret extended is a breath of fresh air in the sense that it allows things to move along at a slower pace while keeping paranoia in the mix. 

I’ve grasped beyond the core of the issue, fuck I used to agree with it. But I no longer agree because I can see sextended for the good gamemode it is. If player abuse is an issue, the solution is the same as always, admins.

**Comment by Shadowflame909** [comment]
I think it needs to be removed from rotation. Not from existence

**Comment by Dawson1917** [comment]
One of the most iconic and important aspects of SS13 is the paranoia it instills in players. Being suspicious of the people around you all round only to learn you had nothing to worry about the whole time when you dock at centcom is never not interesting. Announced extended and secret extended pair well together because one is for throwing away any sense of paranoia about other players and doing long projects whereas the other is maintaining paranoia without there being an actual threat. 

There's no need to divide the game between two modes of "unga bunga which antag am i gonna kill this round!!" and "there is nothing to worry about so the next two hours are going to be my personal sandbox".

**Comment by Tlaltecuhtli** [comment]
he died to secret extended :joy:

**Comment by YakumoChen** [comment]
>People create their own issues on secret extended rounds, so most of them aren’t boring.
>>But thats the fucking problem. Don't go calling other people chimps when you haven't even grasped the core of the issue.

how is that a problem? the most interesting rounds are often Secret Extended simply because the station will organically create its own problems.

**Comment by FancyCyclops** [comment]
Just disable sextended you monkey.

**Comment by Detective-Google** [comment]
What I will add in terms of this PR is that- from all the admins I've talked to about this, Sextended is **hell** to moderate, which can pretty obviously be seen from the amount of people that end up dead during a round with no antags.

the joke that secret extended is the deadliest gamemode is not without base and I am sure admins would prefer to not deal with it

that being said, this is what configs are for, don't try and remove it from the code, start a policy thread

**Comment by PKPenguin321** [comment]
>>Used for admin events, already a config option. Start a policy discussion if you want the mode out of the rotation

>Admin events are usually dumb and disrupt rounds, they only usually cause problems from what I've seen in the past

!!! holy moly! how new are you?

**Comment by Ty-the-Smonk** [comment]
> > > Used for admin events, already a config option. Start a policy discussion if you want the mode out of the rotation
> 
> > Admin events are usually dumb and disrupt rounds, they only usually cause problems from what I've seen in the past
> 
> !!! holy moly! how new are you?

since 2016, I have yet to see a admin event that people haven't gotten pissed off at

**Comment by wesoda25** [comment]
Mans removing sextended bc he doesn’t like admin events shits fucking wild

**Comment by Shadowflame909** [comment]
I guess he's never seen the Admin Trader/ Centcomm Trader event.

That one so far has recieved 0 complaints. Other then that its too easy to rob the traitor

**Comment by MCterra10** [comment]
As a server owner, I can indeed agree that secret extended is _very_ helpful for running admin events, like donk ops and others. Removing a legitimately helpful feature from the game instead of from rotation is a real dick move. Secret Extended can easily be removed from rotation with a simple one line config change, and at the end of the day that's up to MSO and the admin team to decide upon.

**Comment by ishitbyabullet** [comment]
Don't actually remove secret extended unironically.

It's a config option.

**Comment by FancyCyclops** [comment]
> downstreams exist. They shouldn't be fucked over because you decided that it was a bad idea.

just branch off lmao like walk away from the codebase lmao

**Comment by necromanceranne** [comment]
Removing secret extended only enforces the fact that if the alert occurs there are valids to be had. It literally lets you meta the round as being ONE of the antagonist rounds. Secret extended keeps the uncertainty, prevents metagaming to an extent, and maybe keeps people either apprehensive or cautious enough to create tension.

**Comment by dee-dubya** [comment]
I'd sooner get rid of confirmed extended than secret extended. All a greenshift causes is mass suicide and occasionally a full on greytide. Whereas with secret extended, people still play the game the same as they usually would, with the normal suspicion of traitor activity. In other words, the way the game was meant to be played.

**Comment by SkeletalElite** [comment]
> One of the most iconic and important aspects of SS13 is the paranoia it instills in players. Being suspicious of the people around you all round only to learn you had nothing to worry about the whole time when you dock at centcom is never not interesting. Announced extended and secret extended pair well together because one is for throwing away any sense of paranoia about other players and doing long projects whereas the other is maintaining paranoia without there being an actual threat.
> 
> There's no need to divide the game between two modes of "unga bunga which antag am i gonna kill this round!!" and "there is nothing to worry about so the next two hours are going to be my personal sandbox".

Thats actually about as uninteresting as it gets.
"Welp I just sat around for 30 or more minutes and wasted my time when I could have actually done something fun instead"

**Comment by Jordie0608** [comment]
Ask the headmins to change the config if you want to see this change realised, there's no good reason to remove the gamemode entirely.

**Comment by cacogen** [comment]
extended is fucking cancer

**Pull request closed without merging**
