### PR TITLE
Updates the wizard's den

### PR DESCRIPTION
**Pull request by EuSouAFazer**
## About The Pull Request

I am the mapping demon, the mapping vampire, the mapping LICH. I am going to suck the soul out of every single map in the game. I've sucked the beach away mission's soul now I'm going for the wizard's den.

## Why It's Good For The Game

The wizard's den no longer looks like a giant flying cucumber, also it looks a lot better and has a lot better themeing. The wizard also has a book directing them to their wiki page to help them.

image
image
image
image
image
image

## Changelog
:cl: Fazzie
add: The wizard's den now has a book with the guide to wizard. Hope that helps their winrate!
qol: The wizard's den no longer looks like a flying cucumber and has received a major overhaul. Hooray!
/:cl:

### CODE REVIEW

**Comment by dwasint** [comment]
straight up wizard nerf, don't you know wizards primary power source are cucumbers. Jokes aside its missing the iconic wizard statue. Also it feels weird to see actual loot spawners on the wizards ship.

**Comment by EuSouAFazer** [comment]
> straight up wizard nerf, don't you know wizards primary power source are cucumbers. Jokes aside its missing the iconic wizard statue. Also it feels weird to see actual loot spawners on the wizards ship.

The wizard was removed for looking too much like an NPC and not enough like an actual statue (also it was really just thrown on a corner of the spaceship with no rhyme or reason)

If a PR passes that makes it look like a statue and not like a guy I'd add it but I don't think it fits the vibe or look of the new den

**Comment by DaydreamIQ** [comment]
Out of curiosity where's the cheese book supposed to spawn now that there's about a dozen more bookcases?

**Comment by EuSouAFazer** [comment]
> Out of curiosity where's the cheese book supposed to spawn now that there's about a dozen more bookcases?

In the kitchen bookcase of course

**Review by MrMelbert — CHANGES_REQUESTED** [review]
Wiz shouldn't get tools on their shuttle, makes it too easy to hack the magivend.

**Comment by SimplySmiley123** [comment]
Any images for what changed and all that?

**Comment by carlarctg** [comment]
> Wiz shouldn't get tools on their shuttle, makes it too easy to hack the magivend.

How the fuck are you meant to hack it then? Spam EMP?

**Comment by Jacquerel** [comment]
> Go to checks, mapdiffbot. It automatically generates images for every mapping PR.

It does but they're no substitute for in-game screenshots with sightlines.

**Comment by EuSouAFazer** [comment]
> > Go to checks, mapdiffbot. It automatically generates images for every mapping PR.
> 
> It does but they're no substitute for in-game screenshots with sightlines.

Images added. May I re-open the PR?

**Comment by Jacquerel** [comment]
> May I re-open the PR?

you never needed to draft it in the first place

**Comment by SomeoneYouProbablyKnow** [comment]
Definition of soul removal. Better quality map but some ethereal quality is missing. Some goofiness or some fun detail idk maybe i just liked the green hue. 

Lacking meaningful criticism, good map i say.

**Comment by EuSouAFazer** [comment]
> Definition of soul removal. Better quality map but some ethereal quality is missing. Some goofiness or some fun detail idk maybe i just liked the green hue. 
> 
> Since i can't manage any actionable criticism, i say good map and godspeed.

Joke answer: I am the mapping archlich. I will suck the soul out of every and each map in the repo and no one can stop me.

Real answer: There are a lot of goofy and fun details, even more than in the original map - the map literally starts with a gelatinous cube killing a gondola roundstart. There's a kitchen with colorful burgers and a shelf with the Summon Cheese spell. The firing range is Nanotransen themed, and you can find curator clothes on a coffin in the basement. 

I've said and always will say this that soul =/= quirkiness but rather anchoring bias, the feeling that something is better because we're used to it. There's a lot of quirky and fun details here, many more than in the OG ship which had barely any that weren't still kept and preserved in this new version. Once you get used to the new ship you'll start growing this feeling of "soul" again on it, it's just how used people are to the map.

**Comment by Sealed101** [comment]
wait does this pr encourage gondola violence? 
sorry chief but that's a bad image for us, literally unplayable, stupid, evil, stupid.

**Comment by Loafin34** [comment]
make at least the bridge green, it's more mystical than just wooden walls

**Comment by EuSouAFazer** [comment]
> make at least the bridge green, it's more mystical than just wooden walls

Uranium feels like the opposite of magic and mystical to me. I feel wood works a lot better to make a sense of wonder and "woah how is this ship flying" than "why are the walls made out of fucking URANIUM"

Also I'm not varediting the window's color var to be green like the old ship, color varediting is the road to ruin

**Comment by Jacquerel** [comment]
To be fair you can have green windows without varediting it just requires you to write two lines of code

**Comment by Serxule** [comment]
i mean you could atleast use plasmaglass to make it look wizardy than just... wooden structure with engines (this really isnt uncommon or wacky gonna be honest)

**Comment by Serxule** [comment]
also, honestly, stone walls (the rod ones i think) would look a lot better, wizards live in like castles and towers n shit, what wizard lives in a cabin

**Comment by improvedname** [comment]
my beloved quarterwizard statue... i will miss you

**Comment by Momo8289** [comment]
> How the fuck are you meant to hack it then? Spam EMP?

You're not ¯\_(ツ)_/¯

**Comment by setaciocascarudo** [comment]
The uranium walls added a mystique and wacky magical look to the ship why must it be fully taken away it can be incorporated into the current design

**Comment by notfrying1pans** [comment]
I prefer the green look, but this looks nice

**Comment by Googles-Hands** [comment]
You need to add a dead experiment 52 in the cage, don't just delete it. Show that the slime has proven dominant.

**Comment by EuSouAFazer** [comment]
image
He's back.

**Pull request merged**
