### PR TITLE
Replaces Servant cyborg emagged modules with some limited scripture and tools

### PR DESCRIPTION
**Pull request by ChangelingRain**
:cl: Joan
rscdel: Servant cyborgs no longer have emagged modules.
rscadd: Servant cyborgs now have a limited selection of scripture and tools, which varies by cyborg type.
/:cl:

this happens to replace the cyborg module vars with use of `held_items` so that cyborgs with slabs interact properly with scripture

By module, things unique to cyborgs marked in **bold**;
- Standard; **Judicial Marker**, Sentinel's Compromise, Sigil of Transgression, Vitality Matrix, Ratvarian Spear
- Engineering; Tinkerer's Cache, Ocular Warden, Tinkerer's Daemon, **Cyborg Proselytizer**
- Medical; **Linked Vanguard**, Sentinel's Compromise, Fellowship Armory, Mending Motor
- Security; Belligerent, **Judicial Marker**, Ocular Warden, Ratvarian Spear
- Peacekeeper; Belligerent, **Judicial Marker**, Taunting Tirade, Mania Motor
- Janitor; Belligerent, Volt Void, Sigil of Transmission, Interdiction Lens, **Cyborg Proselytizer**
- Service; Replicant, Fellowship Armory, Spatial Gateway, Clockwork Obelisk, **Truesight Lens**
- Miner; **Judicial Marker**, **Linked Vanguard**, Spatial Gateway, **Truesight Lens**

New stuff, in order of appearence;
- Judicial Marker; Creates a Judicial Marker at the target location; 4 second invoke time, requires one BE.
- Cyborg Proselytizer; As a normal proselytizer, but can use cyborg power if out of alloy. Costly!
- Linked Vanguard; Gives yourself and a target ally Vanguard; 4 second invoke time, requires one VC.
- Truesight Lens; Gives the borg xray vision with no downside besides using a module. Very powerful.

### CODE REVIEW

**Comment by ShadowDeath6** [comment]
does the linked vanguard give the borg complete stun immunity as well

**Comment by ChangelingRain** [comment]
For 20 seconds, and it gets stunned afterwards like normal vanguard.

**Comment by kevinz000** [comment]
YES!!!

**Comment by KingPhilipIII** [comment]
Wow. Really getting the borgies in on it now.

**Comment by SgtxRootbeer** [comment]
so, if my clockcult has a few slime cells and engi-borgies, we can go nuts with the prosletizer?

**Comment by ShadowDeath6** [comment]
the charging sigils probably work better than charging cells, just get a standard cyborg to slap a bunch down

**Comment by GunHog** [comment]
WOW. I must say, WOW! 10/10 on this, Joan. It looks like each borg will be able to contribute in their own way, Really beautiful stuff here.

**Comment by TehPear** [comment]
Would you still be able to use the illegal modules upgrade on the borgs to get the standard emag modules? Also what would happen if you used that board on a borg and it was converted? Would the module just go kaput?

**Comment by GunHog** [comment]
That is worth testing!

**Comment by ChangelingRain** [comment]
Yes, you can give them emagged modules with that borg and it'll work and stick around.

**Comment by GunHog** [comment]
Intended? :D

**Pull request merged**
