### PR TITLE
Lowers nuclear emergency min population

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
From 45 to 35

I did not account for the strange people who don't ready up to avoid being an antag target, yet join at roundstart anyway.

### CODE REVIEW

**Comment by GunHog** [comment]
This PR increases fun.

**Comment by Zilenan91** [comment]
I don't much see the point in joining at round start but not at the start since antags are just going to target you anyways.

**Comment by GunHog** [comment]
There is also the ability to choose your job instead of relying on RNG. Of course, you have much more limited possibilities than at roundstart, but being able to choose is a powerful motivator.

**Comment by Fox-McCloud** [comment]
>I don't much see the point in joining at round start but not at the start since antags are just going to target you anyways.

I would venture to guess antags are more likely to kill you if you're on their target list than if you're not--even if they *can* kill you any time they please.

**Comment by kevinz000** [comment]
Arrivals Shuttle is way closer primary tool storage in box.  You know where the toolbelt spawns.

**Comment by PKPenguin321** [comment]
Latejoining can guarantee a job you want if you don't want to deal with priority RNG

**Comment by GunHog** [comment]
I have not seen Ops in a long time. This is too good a mode to restrict too much! Please merge this ASAP

**Pull request merged**
