### PR TITLE
Adds a bronze dimensional theme

### PR DESCRIPTION
**Pull request by carlarctg**
## About The Pull Request

Adds a bronze dimensional theme
image

## Why It's Good For The Game
There are a lot of bronze objects and it makes an excellent candidate. It even has a funny sound

## Changelog

:cl:
add: Adds a bronze dimensional theme
/:cl:

### CODE REVIEW

**Comment by Jacquerel** [comment]
For completion's sake, maybe an image? This also isn't a very good "why it's good for the game".

**Comment by Singul0** [comment]
Trash items to various ratvar cult trash? if those things still exist in the codebase anyways.

**Comment by carlarctg** [comment]
> For completion's sake, maybe an image? This also isn't a very good "why it's good for the game".

ok man

**Comment by EricZilla** [comment]
Wouldn't the bronze gear make a better symbol for it? Then again we see the spear more than anything else. IDK

**Pull request merged**
