### PR TITLE
Buffs lizardmen to be more resistant to heat.

### PR DESCRIPTION
**Pull request by Firecage**
But makes them more vulnerable to cold. Also makes them fall asleep if the temperature is below 150.

As a side note, temperature guns are now unusually effective against lizardmen.

### CODE REVIEW

**Comment by TechnoAlchemisto** [comment]
Hmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm

**Comment by optimumtact** [comment]
HELL NOHELL NOHELL NOHELL NOHELL NOHELL NOHELL NOHELL NOHELL NOHELL NOHELL NOHELL NOHELL NOHELL NOHELL NOHELL NOHELL NOHELL NOHELL NOHELL NOHELL NOHELL NOHELL NOHELL NOHELL NOHELL NOHELL NOHELL NOHELL NOHELL NOHELL NOHELL NOHELL NOHELL NOHELL NOHELL NOHELL NOHELL NOHELL NOHELL NOHELL NOHELL NOHELL NOHELL NOHELL NOHELL NOHELL NOHELL NOHELL NOHELL NOHELL NOHELL NOHELL NOHELL NOHELL NOHELL NOHELL NOHELL NOHELL NOHELL NOHELL NOHELL NOHELL NOHELL NOHELL NOHELL NOHELL NOHELL NOHELL NOHELL NOHELL NOHELL NOHELL NOHELL NOHELL NOHELL NOHELL NOHELL NOHELL NOHELL NOHELL NOHELL NOHELL NOHELL NOHELL NOHELL NOHELL NOHELL NOHELL NOHELL NOHELL NOHELL NO

**Comment by Shadowlight213** [comment]
The code only nerfs them in cold though...

**Comment by PKPenguin321** [comment]
noooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo

\>lizards are just cosmetic aside from hulk and asimov, guys!
\>they won't become any more than that, saying that they will is le slippery sloap fallecy!

**Comment by hornygranny** [comment]
if this gets merged lizardmen are going off on /tg/ like all the races with nonstandard attributes

**Comment by Firecage** [comment]
>HG making threats as a headmin to keep something from being merged.

>Now praised by anti-lizard lovers for trying to get the PR merged.

**Comment by optimumtact** [comment]
Just reopen this please

HG can't set policy on his own for much longer

**Comment by KazeEspada** [comment]
No lizard hulk is a shitty bandaid fix.

**Comment by CPTANT** [comment]
It has already been determined long ago that non-human races would never get non standard bonusses or penalties.

**Comment by Firecage** [comment]
Well, flymen are a roundstart race, they have a nonstandard penalty of pest killer being even more toxic to them. Most other non-roundstart races has their own penalties and buffs, and most of those races can be gotten during the round.

**Comment by Incoming5643** [comment]
The rules of race balance are:

1. There is absolutely nothing taboo about making a race more or less robust than humans.
2. If a race is closely associated with an antag, they shouldn't be a roundstart race.
3. If a race is more robust than humans, they probably shouldn't be a roundstart race.
3. If a race is less robust than humans, they can still be a roundstart race.
5. Roundstart flypeople are a meme.

**Comment by Buggy123** [comment]
:+1: I like it, it's a really small change, enough to make it so lizards aren't radically different from humans, and overall its a nerf more than a buff.

**Comment by Shadowlight213** [comment]
Does heatmod affect energy weapon damage?

**Comment by Incoming5643** [comment]
it does

**Comment by KazeEspada** [comment]
One extra beam! Holy shit. Let's completely forget the fact that after cryo, they will sleep for days. Or they will pass out if they pass by a broken window.

**Comment by Incoming5643** [comment]
yeah stacking drowsy/sleep has a huge potential to just keep people asleep for absurd amounts of time

**Comment by Shadowlight213** [comment]
One extra beam can do a lot. Also lizards could just get the anti cold mutation and ignore the debuffs completely.

**Comment by PKPenguin321** [comment]
also they could like, wear a winter coat or something, idk

**Comment by Zilenan91** [comment]
It'd be nice if you added some extra winter coats to the locker rooms or something to compensate for this.

**Comment by GunHog** [comment]
:-1: This is not needed, and will probably end up giving the anti-lizard players exactly what they want: Removal. Roundstart races should be _cosmetic_. Anyone supporting these changes, in my opinion, deserve to have them applied to their own characters. Perhaps then people would not be so eager to hurt the experience of other players.

**Comment by Incoming5643** [comment]
yeah to reiterate, it's a pretty garbage idea

**Comment by octareenroon91** [comment]
Inviting @LanCartwright to weigh in here.

https://github.com/Zaers/-tg-station/blob/master/code/modules/mob/living/carbon/human/species_types.dm#L66

```
/datum/species/lizard/spec_life(mob/living/carbon/human/H)
	if(H.bodytemperature < T0C+5)
		hiberncounter++
		hiberncounter += max(round((cold_slow-10 - H.bodytemperature)/10),3)	//each 10 degrees below 15 increments by one
	else
		hiberncounter += max(round((cold_slow-20 - H.bodytemperature)/10),-3)	//each 10 degrees above 5 decrements by one
	hiberncounter = min(max(hiberncounter, 0), hibernmax)

	if(hiberncounter && !hibernating)
		H.eye_blurry = max(round(hiberncounter/4), H.eye_blurry)

	if(hiberncounter >= hibernsleep)
		if(!H.sleeping)
			H.sleeping += 1
		H.sleeping += 1
		if(H.sleeping)
			hibernating = 1

			//Good temperature resistance when hibernating
			coldmod = 0.5
			heatmod = 0.5

	if(hiberncounter < hibernsleep && hibernating)
		H.sleeping = max( H.sleeping - 1, 0)
		if(!H.sleeping)
			hibernating = 0
			coldmod = 1
			heatmod = 1
```

**Comment by Iamgoofball** [comment]
This is absolutely not OK.

You know how paradise and bay have the super overpowered alien races?

This is where that starts.

Alien races are one of the few places in SS13 where the slippery slope argument always works.

**Comment by Iamgoofball** [comment]
>Most other non-roundstart races has their own penalties and buffs, and most of those races can be **gotten during the round**

Yes, gotten during the round is the key word here. You have to put in work and effort to get those buffs. This just lets me go "roundstart i can survive fire easier just because".

**Comment by JJRcop** [comment]
New subspecies called "earth lizards", who are rare due to the extreme [#lorebus], and can only be gotten if you discover their UE from somewhere.

**Comment by Zilenan91** [comment]
Yeah but
>go into space for .2 seconds
>instantly fall asleep and die
or
>use cryo
>be asleep for 9 million years

For most people the disadvantages far outweigh the advantages unless they're ALWAYS wearing insulation, which isn't something everyone will do all the time.

**Comment by Incoming5643** [comment]
This PR is kind of a bait and switch, putting the buff in the title and putting the (much stronger) nerfs in the description. I'll say for a third time that this really probably isn't a good idea.

**Comment by vista-** [comment]
I frequently play as a ligger, and I disapprove of this PR. :-1:
Liggers only deserve negative discrimination and no asimov protection.

**Comment by LanCartwright** [comment]
Do it. Nothing can go wrong. I've tested this before. Lizards are more likely to get lynched than anything else.

**Comment by Shadowlight213** [comment]
:-1: I don't like this. Lizards are supposed to have no mechanical differences. Only lack of asimov protection. If getting lizards disabled is your goal, then this PR certainly pushes for it.

**Pull request closed without merging**
