### PR TITLE
Omega station

### PR DESCRIPTION
**Pull request by Okand37**
Omega Station, contrary to the latest Delta Station, is a lowpop map intended for crowds between 20-to-30, give or take. 
Full-scale map : https://drive.google.com/file/d/0B67Y0cE3wQneMWx0M2REOGxxbTQ/view
Forum thread : https://tgstation13.org/phpBB/viewtopic.php?f=11&t=8916&view=unread#unread

Lets see if I PR'ed this right and included only the files I meant too!

### CODE REVIEW

**Comment by Cyberboss** [comment]
I think you fucked up

**Comment by Mindustry** [comment]
How about you fix the problems with delta first? You know, the things like cargo conveyer not working properly, the gateway being all access, etc etc

**Comment by Mindustry** [comment]
Are you still going to maintain Delta?

**Comment by Okand37** [comment]
I already did, hence why I had a PR that fixed abunch of things with delta, mindustry. Its not hard to maintain two maps. I'll see what I can do about fixing the conflicts, however.

**Comment by Mindustry** [comment]
If you say you can do it, then go ahead and do it. It's just not uncommon for mappers to drop support once something else catches their attention.

**Comment by Okand37** [comment]
No worries. I'm going to close the PR and try again in a moment, however.

**Pull request closed without merging**
