### PR TITLE
Buffs Head of Security's Hardsuit

### PR DESCRIPTION
**Pull request by Steelpoint**
This PR improves upon the design of the Head of Security's Hardsuit by changing the sprites to be more similar to the, subjectively superior, standard Security Hardsuit sprites.

Comparison image below. New HoS Suit sprites to the right.

comparison

Also below are several alt sprites being discussed below.

comparions2

comparions3

Sprite change only. There is no new jetpack in the hardsuits storage.

### CODE REVIEW

**Comment by Haevacht** [comment]
Misleading PR title 0/10.

**Comment by juanototo2** [comment]
Brace yourselves, because almost every PR Steelpoint makes about Sec is going to involve several pages of shitposting and saying No.

**Comment by ChemicalRascal** [comment]
IDK, I don't mind the current one. Kind of makes sense that it's very distinct from the normal sec officers, given that the HoS standard uniform is very distinct from the officer uniform. As in, their trenchcoat thing, because you never see them out of that.

**Comment by Steelpoint** [comment]
The current one is a very ugly looking sprite in comparison, and the newer sprite was intended for the HoS but never got to him.

**Comment by Thunder12345** [comment]
B-but that's not the HoS hardsuit

**Comment by Steelpoint** [comment]
The sprite with the red shoulders is the newer sprite put into the game. It was intended originally to be for the Head of Security as his own unique sprite, however it was instead made to be the new sprite for the standard Sec Hardsuits while the old, fat, one was given to the HoS.

I think the old hardsuit, the current HoS Hardsuit, is unappealing. Thus I'm proposing this change to swap the HoS's current Hardsuit sprites with the newer one but to distinguish it slightly.

**Comment by Thunder12345** [comment]
Current HoS one is better tbh. The regular sec hardsuit isn't that appealing already and the HoS recolour looks like a space wasp

**Comment by KingPhilipIII** [comment]
A space wasp is a pretty apt comparison when you think about it.

**Comment by Thunder12345** [comment]
The HoS is not SUPPOSED to be a demonic terror that stings everyone in sight. They just act like they are.

**Comment by Shapsy** [comment]
Wasp? My first thought was bumblebee

**Comment by ChemicalRascal** [comment]
My first thought was a sec officer with rubber duckies on their shoulders.

**Comment by XDTM** [comment]
I like it, i currently can't really tell if it's a HoS or normal sec hardsuit at a glance, unlike other heads' hardsuits.

**Comment by Davdichan** [comment]
It looks like an engineering guard sec suit tbh... why not just recolor the helm or give it some decal to maintain the red color theme?

**Comment by InsaneHyena** [comment]
> Color yellow

No!

**Comment by darkpaladin109** [comment]
Mm, the yellow color scheme doesn't suit the HoS very well. Yellow's Engineering's color scheme, not Security's. The shoulders also look strange.

**Comment by WJohn** [comment]
Yeah I don't like the bright yellow against a near black background at all. Clashes badly due to eye burn and doesn't fit with sec's scheme.

**Comment by Steelpoint** [comment]
Then suggest alternative colours, I tried messing around with changing the colour of the visor but that seemed to come out wrong.

**Comment by ChemicalRascal** [comment]
What about red with a yellow highlight? Or adjusting the shade of the black section of the hardsuit? There's admittedly not much room on the pauldrons, it might be best to add some colour to the rest of the suit, kind of like how the CE's hardsuit is obviously the same form, but a radically different colour, to the standard Engineering suit.

**Comment by Steelpoint** [comment]
I'm coming up with one alt design, give me a bit.

**Comment by Steelpoint** [comment]
Here's a different design, with both actors having their backpacks removed.

redesign

**Comment by KorPhaeron** [comment]
The current hos suit is great though

Reminds me of the Chinese guys in deus ex

**Comment by KorPhaeron** [comment]
You should be posting comparisons to the sprite you are replacing

**Comment by Steelpoint** [comment]
Comparison.

5cca5392-ee4e-11e6-9451-64a0f35b5f78

**Comment by TrustyGun** [comment]
If we have to replace it, I will go with the middle sprite.

**Comment by Steelpoint** [comment]
Alternatively, here's another varient I made.

This one's a more direct edit of the current HoS hardsuit sprites, instead of using the body of the newer sprites.

newversion

**Comment by ShadowDeath6** [comment]
initial commit

**Comment by Ausops** [comment]
>cutting one pixel off the height of the suit

NEVER going to make it, literally made the hos a 5'11 king of manlets instead of the 6'4 medbay pussy slayer and validdestroyer he was before

**Comment by Steelpoint** [comment]
I have not changed the height of the suit, at least intentionally.

**Comment by PKPenguin321** [comment]
Wow that yellow sprite is awful

**Comment by KorPhaeron** [comment]
I don't see the sense in removing a unique design  (created by a professional video game artist no less) and replacing it with another generic hardsuit recolour

Wjohn is in charge of art and doesn't like it either.

Finally the majority of dumb emojis and comments seem against this

**Pull request closed without merging**
