### PR TITLE
Wizard's wound spell costs 2 points

### PR DESCRIPTION
**Pull request by JohnFulpWillard**
## About The Pull Request

Increases the wound spell by 1 to the default offensive spell cost of 2.

## Why It's Good For The Game

This spell causes you to die in about a minute from blood loss alone, I don't think it should be worth as little as it does now, considering other spells don't mess you up as much as this one does (the other offensive spells is blind and shock, the latter doesnt even stun).

I also lowered its timer by 20 seconds to make up from it, so it isn't running the same stats as Smite.

## Changelog

:cl:
balance: Wizard's wounding spell now costs 2 spellbook points, and its cooldown has been decreased from 1 minute to 40 seconds.
/:cl:

### CODE REVIEW

**Comment by ATH1909** [comment]
yeah but your victim can still kill you during that minute before they go down

doesn't this PR make wound almost strictly worse than smite, which kills your target instantly?

**Comment by carlarctg** [comment]
Why the fuck would anyone pick this over smite or any of the offensive spells? 

Wizards are already underpowered and keep dying in five to ten minutes round after round. Don't nerf their kit, especially rarely used spells like this....

**Comment by JohnFulpWillard** [comment]
> yeah but your victim can still kill you during that minute before they go down

The problem with it is that is kills you in a minute, it's not enough time to kill a Wizard but also a Wizard doesn't need to be easily killable so I don't think the spell should be nerfed.

> especially rarely used spells like this....

What's the stats on how often this is purchased? It's been in the game for 5 months at this point, and I'm trying to balance this on what makes sense over how often something is used, and comparing death in a minute and requiring a ton of medical work to "being blind" and "getting some burn damage", I don't think this makes sense to be as cheap as it is.

**Comment by necromanceranne** [comment]
Have you tried using your epipen to not die from bloodloss?

**Comment by Ghommie** [comment]
Good, nice, great, amazing, but then there's no reason for picking this over the smite. Both are spells with a 60 seconds cooldown and same method of delivery. The difference is that Smite kills you on the spot, while Scream For Me takes a while, and you can use the epinephrine medipen in the emergency box to counter it as it comes loaded with a bit of coagulant.

That said, halve the spell cooldown.

**Comment by ATH1909** [comment]
> What's the stats on how often this is purchased? It's been in the game for 5 months at this point, and I'm trying to balance this on what makes sense over how often something is used, and comparing death in a minute and requiring a ton of medical work to "being blind" and "getting some burn damage", I don't think this makes sense to be as cheap as it is.

blindness works from a screen away and is robeless

**Comment by ATH1909** [comment]
> Have you tried using your epipen to not die from bloodloss?

I dunno if an epipen would actually stop you from dying to this; didn't coagulant get nerfed to only affect one bleeding wound at a time or something?

**Comment by JohnFulpWillard** [comment]
testing it locally and, with epinephrine, it kills in ~35 seconds.

**Comment by carlarctg** [comment]
Let wizard spells be strong. I don't understand how this is 'too strong'. We don't have stats for how often spells are used, at least none that I know of, but I've never seen anyone use this. Like, 2 points gets you frickin mjolnir. The most broken weapon in the entire game. Why in the ever loving shit would anyone pick this over mjolnir?

Wizards aren't meant to be easy to fight. The only times spells should be 'walanced' is when they are staggeringly strong to the point of the community vocally speaking out about it, or literally broken.

> testing it locally and, with epinephrine, it kills in ~35 seconds.

Smite kills in 0 seconds and leaves them unfixable.

Why not just lower the amount of wounds and make it a ranged ability? That'd be interesting.

**Comment by necromanceranne** [comment]
> testing it locally and, with epinephrine, it kills in ~35 seconds.

Did you use the pen? The bit that stops the bleedout is Sanguirite.

**Comment by Jackal-boop** [comment]
It's fine as is. Leave it be

**Comment by necromanceranne** [comment]
> Smite kills in 0 seconds and leaves them unfixable.
> 
> Why not just lower the amount of wounds and make it a ranged ability? That'd be interesting.

You know I was thinking 'oh but surely this spell has a higher frequency'

No, it has the same frequency. Damn, this spell sucks.

**Comment by IndieanaJones** [comment]
Making it cost 2 points just makes it a worse version of smite with the same cost. Doesn't seem like a smart move.

**Comment by Singul0** [comment]
40 seconds is still crazy long

**Comment by CCC23** [comment]
this spell was littearly diet smite why would it be the same cost of smite with no extra power

**Comment by AtomTheProphet** [comment]
> this spell was littearly diet smite why would it be the same cost of smite with no extra power

Because "balancing" obviously.

**Comment by JohnFulpWillard** [comment]
> Why not just lower the amount of wounds and make it a ranged ability? That'd be interesting.

This is literally just a heretic spell

> 40 seconds is still crazy long

Like I said earlier, 35 seconds is enough to kill someone from lack of blood (just straight-up dropping dead) WITH epinephrine, I think it is reasonable that we should expect the first victim to be dead before letting them do it on a second.

**Comment by Time-Green** [comment]
You can wipe blood wounds pretty quickly with just a welder though

**Comment by JohnFulpWillard** [comment]
> You can wipe blood wounds pretty quickly with just a welder though

https://github.com/tgstation/tgstation/assets/53777086/bc426134-acca-4bc3-8818-fb73b31b6e43

**Comment by JohnFulpWillard** [comment]
Just for fun, I minmaxxed this
I used the spell on someone already lying down (which helps with blood loss), immediately used epinephrine medipen, then grabbed the chest. Then I started welding the bodyparts to try to stop the bleeding with an alien welder.

43 seconds in the person fell unconscious, 1m09 seconds in they died from no blood.

Keep in mind this is someone who is not fighting back against the Wizard, they are lying down on the floor (immobile since that causes more blood loss) constantly trying to clog up their own bleeding.

When, AT BEST, 43 seconds of life is all you have, not talking about the fact that you do not have time to talk, move, or otherwise get help, I think this is insane to be a 1 point spell on par with blindness and minor burn damage.

**Comment by Vect0r2** [comment]
Imagine trying to balance the wizard.

**Comment by Exester509** [comment]
> Just for fun, I minmaxxed this I used the spell on someone already lying down (which helps with blood loss), immediately used epinephrine medipen, then grabbed the chest. Then I started welding the bodyparts to try to stop the bleeding with an alien welder.
> 
> 43 seconds in the person fell unconscious, 1m09 seconds in they died from no blood.
> 
> Keep in mind this is someone who is not fighting back against the Wizard, they are lying down on the floor (immobile since that causes more blood loss) constantly trying to clog up their own bleeding.
> 
> When, AT BEST, 43 seconds of life is all you have, not talking about the fact that you do not have time to talk, move, or otherwise get help/resist further attacks from the Wizard's arsenal of tools they got from their 9 other points, I think this is insane to be a 1 point spell on par with blindness and minor burn damage.
> 
> video (ignore the timer at the top right, its hotkeyed to the same buttons used for limb targeting so i messed it up)
> 
>  8mb.video-qDI-7HPVsG6z.mp4

And yet, you're missing the entire point. No matter how long it takes to kill, even if it's just five seconds, it'll be worse than the melee 2 point alternative, which takes 0 seconds to kill, has the same cooldown, and it makes it way harder to fix than bloodloss.
And besides, it's a wizard, it's not like it's meant to be weak

**Comment by JohnFulpWillard** [comment]
> it's a wizard, it's not like it's meant to be weak

I said above that my goal isn't to make this spell weak, I think it works fine. I just do not think it is on the same level as blinding someone.

Also I already lowered the timer by 20 seconds, so it now has that over smite instead, which can be lowered by 10 seconds each with each upgrade. With all 10 points put in Smite, you can get it lowered down to 10 seconds between each smite, which you can get the same result for Scream for me with 6 points instead.

Also reminds me to put a cap on it so you don't reach negative timers.

**Comment by CRITAWAKETS** [comment]
Bleeding someone out is honestly extremely useless for the glass cannon that is wizard, especially given every single other weapon that allows basically knocking someone out of a fight instantly, sometimes even at range _and_ with no cooldown.

Honestly a buff or a nerf doesn't really matter, because this spell just isn't designed properly.

**Comment by zoomachina** [comment]
Even ignoring the fact that blind is robeless, bro really said "We should balance spell costs based on the weakest spells in the game"

**Comment by necromanceranne** [comment]
> Honestly a buff or a nerf doesn't really matter, because this spell just isn't designed properly.

Well, in all honesty, at a value of 1 it's not bad for the cost. Especially since it interacts nicely with splattercasting, which is what this spell is meant to be used alongside.

**Comment by JohnFulpWillard** [comment]
> Even ignoring the fact that blind is robeless, bro really said "We should balance spell costs based on the weakest spells in the game"

Those are the only 2 spells to compare it to because they are the ONLY other offensive spells at 1 cost.

**Comment by Time-Green** [comment]
> Just for fun, I minmaxxed this I used the spell on someone already lying down (which helps with blood loss), immediately used epinephrine medipen, then grabbed the chest. Then I started welding the bodyparts to try to stop the bleeding with an alien welder.
> 
> 43 seconds in the person fell unconscious, 1m09 seconds in they died from no blood.
> 
> Keep in mind this is someone who is not fighting back against the Wizard, they are lying down on the floor (immobile since that causes more blood loss) constantly trying to clog up their own bleeding.
> 
> When, AT BEST, 43 seconds of life is all you have, not talking about the fact that you do not have time to talk, move, or otherwise get help/resist further attacks from the Wizard's arsenal of tools they got from their 9 other points, I think this is insane to be a 1 point spell on par with blindness and minor burn damage.
> 
> video (ignore the timer at the top right, its hotkeyed to the same buttons used for limb targeting so i messed it up)
> 
>  8mb.video-qDI-7HPVsG6z.mp4

You know what, you kinda got me there, and I now agree that it can't stay like this. I still don't see it getting used that much as long as 'ei nath' exists (even with reduced cooldown, you would still be helpless against plasmamen and borgs). Wouldn't it be preferable to lean more into the wounding aspect of the spel? Just reducing the bleed and adding fracture wounds seems fair, it would take people out of combat but not outright kill them, leaving it as a neat "fuck you and leave me alone" option

**Comment by Exester509** [comment]
> I said above that my goal isn't to make this spell weak, I think it works fine. I just do not think it is on the same level as blinding someone.
This is pretending that it is on the level of gibbing someone

> Also I already lowered the timer by 20 seconds, so it now has that over smite instead, which can be lowered by 10 seconds each with each upgrade. With all 10 points put in Smite, you can get it lowered down to 10 seconds between each smite, which you can get the same result for Scream for me with 6 points instead.
Though this does adress the issue, to an extent. I still don't feel like having this spell as a 2 point offensive is better than the others. Flesh to stone only really is two points because with staff of animation you can make a sentient minion as many times as you want. Scream for me lacks the versatility of flesh to stone or the destructive potential of smite. At least with the cooldown reduction you can make some interesting stuff

**Comment by zoomachina** [comment]
> > Even ignoring the fact that blind is robeless, bro really said "We should balance spell costs based on the weakest spells in the game"
> 
> Those are the only 2 spells to compare it to because they are the ONLY other offensive spells at 1 cost.

Why shouldn't blind be buffed, then?

**Comment by JohnFulpWillard** [comment]
Because that's not what im making a PR on

**Comment by YuliceTheDruid** [comment]
Balance Coders were a mistake

**Comment by Rex9001** [comment]
As someone who tried to make 'scream for me' work it sucks, like even at 1 point you are better off getting anything else instead of a hand spell which maybe kills someone, at 2 points and a 40 second cooldown its still terrible smite is 2 points and 60 seconds but that instantly kills whilst this according to the pr maker still takes 35 seconds to kill. Why would you ever use this spell, if anything it needed a buff.

**Comment by SkeletalElite** [comment]
I have literally never seen a wizard use this spell, I don't think it needs to be nerfed.  

Killing someone with a 40 second delay isn't really that bad. In those 40 seconds they can run to medbay and reviving them is as simple as fixing the wounds sticking them to a blood bag and then defibbing.

Compared to the wizard's other options, this will make this spell useless. Frankly, the options that you are comparing this to as justification to nerf, are also not strong spells and I don't see people use them either. 

Even on a lower cooldown, this is objectively worse than smite at 2 points. Smite is much, much more difficult to fix and is an instant kill, which does not give the person youre casting it on an opportunity to potentially kill you or escape to medbay where they can be easily saved. 

I will note that I don't think the spell is weak in it's current state, but I don't think it is strong enough to justify nerfing this hard to where it's just objectively worse than smite. If you're absolutely convinced this spell is too strong though, perhaps wizard spell points should be "decompressed." ie. double the points to 20 but also double all current spell costs. Set this spell as a 3 point cost.

**Comment by JohnFulpWillard** [comment]
I do not understand why I have to keep repeating that I do not think the spell needs a nerf because it's too strong. I think it's good as a wizard spell, and I find it dumb to say it has to be as good as smite or else it has to be worth 1 point. Without minmaxxing on the spot, you have about 20 seconds to live, while you're actively being attacked by a Wizard. We shouldn't expect people to actually reach medbay, but that's fine, it should just not be on the same level as the only 2 other 1 point spells, when other Offensive spells are "Fireball", "Spell cards", "Flesh to Stone", etc.

**Comment by SkeletalElite** [comment]
> should just not be on the same level as the only 2 other 1 point spells,

then either buff the other 2 1 point spells (they suck)
or decompress the point costs so you can make this more expensive without making it as expensive as smite

People are comparing this spell to smite because they are similar. They are both long cooldown touch spells. Spell choice should be a meaningful decision. With this spell costing 2, there is no meaningful decision to be made here because it's basically always better to choose smite over this spell.

Making the good 1 point spell more expensive because its better than 2 bad 1 point spells doesn't make the 1 point spells less bad. It just leaves you with 3 bad spells people aren't going to use.

**Comment by necromanceranne** [comment]
I feel like you should be putting far less value in the arbitrary category standards and consider the spell as it exists in the content around it. And even if we must compare categories, it struggles to even outclass a defense spell (duffelcurse slap) in comparison to it as a killing tool because it so conservative in its power. 

I think this needs a redesign, not number tweaks. Splattercasting and sanguine spells as a whole could do with the same.

**Comment by Loafin34** [comment]
ided

**Comment by ExcessiveUseOfCobblestone** [comment]
The spell looks like its only good if you dump more than just 1 point in it anyways, if youre going for super bleed funzone youre losing 1 point (5>6), and if youre not youre still losing at least 1 point lol(1>2).

The problem with the spell is you can very easily trade after casting it so it sucks since its a single target skill, versus other skills of the cost you wish to change it to that instantly btfo the individual.

I think if we really had to change the spell maybe a slight nerf to the actual mechanics of the spell rather than playing with levels/costs. It would be more detached from other 2 pointers than it is currently detached from existing 1 pointers imo, even w the lvl1 CD change.

**Comment by JohnFulpWillard** [comment]
i played the game sadly

**Pull request closed without merging**
