### PR TITLE
Removes a src.

### PR DESCRIPTION
**Pull request by ChangelingRain**
Got it!

### CODE REVIEW

**Comment by Cyberboss** [comment]
...How? >.>

**Comment by ChangelingRain** [comment]
Well Thats A Good Question
I Dont Know Though

**Comment by Cyberboss** [comment]
Okay Kanaya

**Comment by MrStonedOne** [comment]
Oh, this bug!

**Comment by MrStonedOne** [comment]
http://www.byond.com/forum/?post=2124784#comment20560627

**Pull request merged**
