### PR TITLE
Added sign with slime mutation map for xenobio

### PR DESCRIPTION
**Pull request by MTandi**
## About The Pull Request

Added xenobio sign that is a miniature of the slime genealogy map from the wiki.

image

## Why It's Good For The Game

It's an important infographic for xenobio, and it is nice when it is available without the need to open wiki.

## Changelog

:cl:
imageadd: Added xenobio guide sign
/:cl:

### CODE REVIEW

**Comment by Jolly-66** [comment]
Nitpick but can we *please* try and not put this on windows? I know we do it in some instances (IceBox arrivals) but it would be better if we could try to avoid it

**Comment by coiax** [comment]
Should this be a poster instead of a sign?

**Comment by MTandi** [comment]
> Should this be a poster instead of a sign? 🤔

Posters are just fluff, while signs are functional. You can always place it with plastic if you need it, but posters need to be obtained.

**Comment by MTandi** [comment]
> You can print posters from the curator console. Previously it was random, but these days you can choose the exact poster you want. I'm in favor of making this a poster (like the periodic table poster), on the off chance it results in even one or two people trying to interact with the curator.

Anyway this sounds like a hassle as you have to go somewhere and rely on availability of some console from non-sci department, I was not even aware of. Periodic table fits this better as it's a more general graphic and historical one.
And this is not really a poster but something rigid. I imagined it as a board with magnets as slimes and lines drawn by scientists with markers. The variants were green board with chalk marks or a corkwood board with pins.

image

**Review by Twaticus — APPROVED** [review]

**Comment by san7890** [comment]
Shouuuld be good to merge when merge conflicts resolve, ping me (`san7890#7890`) when ready.

**Comment by san7890** [comment]
:(

**Comment by MTandi** [comment]
😢

**Pull request closed without merging**
