### PR TITLE
Adds "Suspected" to available sec record tags

### PR DESCRIPTION
**Pull request by AtoriBirb**
## About The Pull Request

First upstream pull, go.

Have you ever looked to your fellow sec officers and thought to yourself "Geeze we know this dude is valid but we don't have any evidence to put the warrant tag on them and just have to be highly suspicious I wish we could just tag them to keep an eye on them for the future."

 Has your team ever gone "Hey there's a guy we want to bring in for questioning but we don't have a good tag for this what do we do, do we label him as discharged or warrant him and deal with them screaming shitsec on coms while being bodied by beepsky?"

If you or a loved one have been diagnosed with 'I've been bound and gagged by beepsky because I touched a door' syndrome, then this is the PR for you.

In all seriousness, it adds another tag you can set people to with sec huds/security console, and intermediate state when you want to either question someone, or are suspicious of someone but have no legal evidence to warrant them yet. 

image

## Why It's Good For The Game

Provides a way to keep track of your suspects without having beepsky body them. Keeps assistants from instantly hating sec.. more than usual.

I hope there is some instant bwoinks the moment the HoS tells the warden to set the clown to 'Sussy'

## Changelog

:cl:
add: A new intermediate tag for sec huds called "Suspected" that allows officers to identify peoples of interest without raising their threat to where beepsky will chase and attempt to apprehend them. Shows up as an orange '!'.
/:cl:

### CODE REVIEW

**Comment by kopoba** [comment]
Excellent change i was always using Paroled status but this is better!

**Comment by ProfessorSniff** [comment]
this looks like it could be confusingly similar to the scientist job icon

**Comment by AtoriBirb** [comment]
> this looks like it could be confusingly similar to the scientist job icon

Only sec officers will see it, and if they can't tell pink from orange, and would not question why someone has 'two job icons' I'd say it makes sense why they chose to play sec.

**Review by Mothblocks — CHANGES_REQUESTED** [review]
Please edit your changelog only to have `add: ` and explain the mechanic being added, not imageadd/code.

**Comment by AtoriBirb** [comment]
> Please edit your changelog only to have `add: ` and explain the mechanic being added, not imageadd/code.

How's that

**Comment by Likteer** [comment]
> Only sec officers will see it, and if they can't tell pink from orange, and would not question why someone has 'two job icons' I'd say it makes sense why they chose to play sec. Naw but for real if they want it to be an orange S I can do that too, I just figure that is closer to the syndicate icon sooo..

@AtoriBirb We all just be messin' and conspiring to trick you into making the icon "SUS".

**Comment by AtoriBirb** [comment]
> > Only sec officers will see it, and if they can't tell pink from orange, and would not question why someone has 'two job icons' I'd say it makes sense why they chose to play sec. Naw but for real if they want it to be an orange S I can do that too, I just figure that is closer to the syndicate icon sooo..
> 
> @AtoriBirb We all just be messin' and conspiring to trick you into making the icon "SUS".

I may have sorta made a version for such as a joke..
image

**Review by Mothblocks — APPROVED** [review]

**Comment by TheBonded** [comment]
> > > Only sec officers will see it, and if they can't tell pink from orange, and would not question why someone has 'two job icons' I'd say it makes sense why they chose to play sec. Naw but for real if they want it to be an orange S I can do that too, I just figure that is closer to the syndicate icon sooo..
> > 
> > 
> > @AtoriBirb We all just be messin' and conspiring to trick you into making the icon "SUS".
> 
> I may have sorta made a version for such as a joke.. image

make it a 0.1% chance to be that instead of the normal exclamation point

**Comment by SuperNovaa41** [comment]
This is awesome :+1:

**Pull request merged**
