### PR TITLE
Altered miasma stats

### PR DESCRIPTION
**Pull request by maxphillipsdev**
:cl:
balance: Increased miasma's specific heat.
/:cl:
Altered Miasma Stats

Miasma seemed to be lacking useful non-antag applications outside of being something for atmos techs to deal with, so I increased the specific heat to make it more useful for engineers as a coolant for example.

### CODE REVIEW

**Comment by Barhandar** [comment]
The main station engine literally produces better coolant as _waste byproduct_, this ain't gonna make miasma useful. And it's not supposed to be useful either.

**Comment by MrDoomBringer** [comment]
@Barhandar i kinda like the idea of a SM cooled by the corpses of dead bodies tho

**Comment by chilisource** [comment]
@MrDoomBringer okay yeah you got me. I'm a sucker for a good genocide engine.

**Comment by chilisource** [comment]
@Barhandar with this change it would make miasma slightly better in terms of specific heat than pluoxium, considering that it has a higher rareness. It's still no match for plasma or nobil of course but I think it's the kind of balance that would let people do some cool stuff with their sm mixes. Honestly though, I don't see any point in it being useless. All the other gasses got their pros and cons but miasma seems to only be useful to antags at the moment, which kinda seems a shame since there are only a handful of gasses in the game.

**Comment by kingoftheautism** [comment]
though even if this pr going to be merged, which i doubt, miasma doesn't have (as far as i know) any reaction with SM, including either stabilizing it or making it go apeshit. So it will be useful in TEG, or something else (though even then if you need high heat capacity you go for plasma), and possibly in SM (and you still will need N2 to negate plasma and oxygen heat penalty.

**Comment by Cyprex** [comment]
Pluoxium, which is easy to make in the SM chamber, is the exact same but better at 200 heat capacity, with no interaction with the SM either. The only way I could see this being used is for huge tritium bombs if you put the heat capacity above 200.

**Comment by Bawhoppen** [comment]
Miasma is supposed to be disease gas, not industrial bomb gas.

**Comment by Cyprex** [comment]
Yes, I agree.

**Comment by chilisource** [comment]
@Cyprex I think your thinking of plasma since pluoxium only has a heat capacity of 80, I checked this when making the edit you can see for yourself if you want. Plasma has a capacity of 200 however it also has SM interactions. This change also only boosts the heat capacity to 100, making it more ideal as a coolant but really if you were making a bomb, tritium or not, you would be using something like plasma or hyper nobil anyway since they still have a better heat capacity. Your not gonna make any better sorts of bombs with this than you can already with just o2 and plasma, it's really just a small change to make it somewhat useful as a coolant in the SM.

**Comment by Bawhoppen** [comment]
But why should it be useful for anything (other than shenanigans)? It's a disease gas, that's supposed to be avoided and viewed as a nuisance.

**Comment by optimumtact** [comment]
Yeah I'm not sure this makes much sense sorry.

**Pull request closed without merging**
