### PR TITLE
Box airlock cyclelink

### PR DESCRIPTION
**Pull request by 81Denton**
:cl: Denton
tweak: Cyclelinked three airlock pairs on Boxstation (port bow solars and the area that connects RnD with medical).
/:cl:

I cycle linked three airlock pairs on boxstation, looks like that was an oversight.
Now with 90% less Travis errors

### CODE REVIEW

**Comment by Cyberboss** [comment]
I'm gonna intentionally make this fail to compile for a sec, pls forgiff

**Comment by Cyberboss** [comment]
Stealing this for a sec

**Review by ShizCalev — DISMISSED** [review]

**Review by Cyberboss — DISMISSED** [review]
Signed off by: @Cyberboss

**Comment by Cyberboss** [comment]
Merge process interupted! Error:\n```\nOctokit.PullRequestMismatchException: Head branch was modified. Review and try the merge again.
   at Octokit.PullRequestsClient.<Merge>d__29.MoveNext() in C:\projects\octokit-net\Octokit\Clients\PullRequestsClient.cs:line 295
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at TGWebhooks.Core.AutoMergeHandler.<MergePullRequest>d__8.MoveNext()
{"message":"Head branch was modified. Review and try the merge again.","documentation_url":"https://developer.github.com/v3/pulls/#merge-a-pull-request-merge-button"}\n``` your old HEAD commit was 81e8949061a1e32fb17e384ffdc6d09c40fbd87a

**Pull request merged**
