### PR TITLE
More robust dorfs.

### PR DESCRIPTION
**Pull request by nemvar**
## About The Pull Request

Replaced unmanly weak hobbit dorfs with stout manly normal dorfs.
dorf

## Changelog
:cl:
tweak: Dwarfs are now more robust.
/:cl:

### CODE REVIEW

**Comment by PKPenguin321** [comment]
This is cursed

**Comment by nemvar** [comment]
scared?

**Comment by Whoneedspacee** [comment]
finally i can be my true self

**Comment by PKPenguin321** [comment]
>scared?

yes

**Comment by MMMiracles** [comment]
squasj

_welcome to the hydraulic press channel_

**Comment by actioninja** [comment]
I just keep looking at this and laughing at it, beautiful pr

**Comment by Alek2ander** [comment]
This is actually a nerf because dorfs get more clickable pixels

**Pull request merged**
