### PR TITLE
Belt Toolboxes?

### PR DESCRIPTION
**Pull request by maxymax13**
## Why It's Good For The Game
I know this change is big, but hear me out:
Right now, there exists 3 options for the average player in terms of tool storage:
Putting your small-weight tools in a normal-weight cardboard box in your bag, and throwing the toolbox away
Light, convenient, easy to obtain.
Putting your tools in a toolbelt (and putting it in your bag if your job needs its own belt), and throwing the toolbox away
Light, extremely convenient, moderately harder to obtain
Keeping the tools in the box of tools
Bulky weight class, inconvenient to use

By keeping the toolbox in a bulky size but letting you wear it on your belt:
You won't have to look for a piece of cardboard that is magically so much better at holding tools than a box **meant for tools**
Tool storage won't be full of nothing but empty discarded toolboxes literally every fucking round
People looking for the complete convenience of a toolbelt can still go seek one out
**You can literally just buy an inconspicuous 12 force normal weight item somewhere on the station and put it in your bag and you will have better chances at beating someone up with it by surprise than carrying around an obviously dangerous bulky size piece of shit ever will, belt slot or not.**
The bigger problem is that these huge ass tools are small size class for some reason which instantly nullifies any item for holding tools, but that would create even more problems that it would solve.

## Changelog
:cl:
balance: Toolboxes, although as bulky and unmaneuverable as ever, can now be strapped to your belt.
/:cl:

### CODE REVIEW

**Comment by tralezab** [comment]
One question for you: What is the purpose of the toolbelt if toolboxes work on the belt?

**Comment by tralezab** [comment]
Also >qol tag come aaaahn we both know this is a huge balance change

**Comment by maxymax13** [comment]
> 
> 
> One question for you: What is the purpose of the toolbelt if toolboxes work on the belt?

Toolbelts are great because you can easily juggle them around between your slots at any time if you need to wear another belt item.

**Comment by Sparkezel** [comment]
Toolboxes are stylish 12 brute weapons, while you COULD use a welder instead, its stylish

**Comment by Ziiro** [comment]
> One question for you: What is the purpose of the toolbelt if toolboxes work on the belt?

Maybe make it so you have to pull the toolbox off of your belt in order to actually open it, making the toolbelt slightly better.

**Comment by maxymax13** [comment]
> 
> 
> > One question for you: What is the purpose of the toolbelt if toolboxes work on the belt?
> 
> Maybe make it so you have to pull the toolbox off of your belt in order to actually open it, making the toolbelt slightly better.

I wanted to make it drop all of its contents on the floor with a message along the lines of "You open the latch, before realizing that the toolbox's lid is what's latched onto your jumpsuit, rather than the other way around..." but I'm not sure on what way to go about that while catching any ways that the storage menu might stay open.

**Comment by ATH1909** [comment]
> > One question for you: What is the purpose of the toolbelt if toolboxes work on the belt?
> 
> Toolbelts are great because you can easily juggle them around between your slots at any time if you need to wear another belt item.

note that toolboxes can hold non-tool items as well, so this PR would basically turn them into boxes that you can wear in your belt slot and use as decent bludgeoning weapons

**Comment by YakumoChen** [comment]
Powercrepe

**Comment by YakumoChen** [comment]
This also has the cascading effect that all of our meme toolboxes like Plastitanium, TC=Power, etc all become Belt slot items too

**Comment by Qustinnus** [comment]
not falling for it

**Comment by LemonInTheDark** [comment]
Thank you floyd

**Comment by Paxilmaniac** [comment]
:trollface:

**Comment by ExcessiveUseOfCobblestone** [comment]
No thank you

**Comment by ExcessiveUseOfCobblestone** [comment]
Closing at 24 hrs

**Comment by Twaticus** [comment]
image

**Comment by maxymax13** [comment]
image

**Comment by interestingusernam3** [comment]
:trollface:

**Pull request closed without merging**
