### PR TITLE
Yes, I ded

### PR DESCRIPTION
**Pull request by Iamgoofball**
pls nerf

### CODE REVIEW

**Comment by optimumtact** [comment]
This does make sense, the carp doesn't have arms

**Comment by KorPhaeron** [comment]
They have mouths though!

**Comment by Repukan** [comment]
Haven't you seen finding Nemo?

They can hold stuff with their little fins.

**Comment by lzimann** [comment]
title

**Comment by Anonmare** [comment]
Cayenne is a good carp, you leave him alone

**Comment by DoctoreMad** [comment]
It only affects Cayenne?
Come on this is high level salt

**Comment by FantasticFwoosh** [comment]
For the sole fact that they could drag the nuke around to juke this is okayish albeit a very blunt _fix_

**Comment by RandomMarine** [comment]
>Space carp - Space immune, simple mob, relatively fast and unhindered by stuns etc, has working hands during a nuke op round on the team. Why?

25 health

**Comment by Anonmare** [comment]
>How to counter Cayenne
>Step 1: Switch to nay intent except help
>Step 2: get a welder
>Step 3: Use welder on Cayenne 2 times
>Step 4: Fish and chips all around

**Comment by Cheridan** [comment]
get wrekt

**Comment by Iamgoofball** [comment]
>simple mobs move through you regardless of intent

**Comment by PKPenguin321** [comment]
@Anonmare https://github.com/tgstation/tgstation/issues/26839

**Comment by PKPenguin321** [comment]
For how much you guys hate stuns I'm surprised you're okay with allowing a basically free player controlled mob that stuns you instantly by just running into you and can kill you off of one stun with no counterplay unless you have a gun

But I guess it's okay because it's a purple fish right

**Pull request closed without merging**
