### PR TITLE
Slime Management Consoles no longer run on the energy of the monkeys you force to run on the hamster wheels inside of it.

### LINKED ISSUE #39348: You can use slime management consoles even when they're unpowered
Issue reported from  Round ID: 91519 (/tg/Station Sybil [ENGLISH] [US-EAST] [100% LAG FREE])

Reporting client version: 512

Pretty much what it says in the title. Console was visibly depowered, and the APC said equipment was offline, but I was still able to use the consoles. 

Station was Pubby, if that's relevant.

### PR DESCRIPTION
**Pull request by ghost**
:cl: Floyd / Qustinus
fix: Slime Management Console (And other Camera_Advanced objects) no longer work if theyre out of power
:cl:
fixes #39348

### CODE REVIEW

**Comment by Qustinnus** [comment]
you guys should thank github theyre basically paying me to fix issues. works better than feature freezes

**Comment by BeeSting12** [comment]
how are they paying you to fix issues

**Comment by Qustinnus** [comment]
theyll give me a tshirt if i make 2 more

**Review by SpaceManiac — APPROVED** [review]

**Comment by 81Denton** [comment]
GBP bandit strikes again

**Comment by Qustinnus** [comment]
github shirt bandit*

**Pull request merged**
