### PR TITLE
Captain and HoP lockers now contain zipties

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
> But they're not security!

They are, however, high value targets that start with guns and generally have an admin expectation to not straight up murder people. They also both have access to cuffs (and wire because so does everyone) already.

### CODE REVIEW

**Comment by Niknakflak** [comment]
I'll probably still use the shutters as my main form of weapon tbh

**Comment by Steelpoint** [comment]
Good change, means they can viable shut down someone who broke into their quarters/room without having to either stun lock them forever or kill them.

**Comment by Dorsisdwarf** [comment]
Anyone breaking into the captain's office is totally fine to laser to death tbh.

Ask sec for your zipties.


If you must add restraints, just put a box of them on the bridge

**Comment by Steelpoint** [comment]
Just because you can does not mean you have to. Its fine to offer a effective non-lethal option of subduing someone for the two people outside of security who most need said item.

A box of zip-ties in the bridge in addition to the zip tie in their lockers seems good.

**Comment by CosmicScientist** [comment]
I hope this doesn't encourage more HoPs and Captains to be security.

**Comment by Nanotransistor** [comment]
This just encourage them to behave like sec. They have weapons that allow them to either escape from trouble or subdue someone until security arrives. Let security do the arresting.

**Comment by CosmicScientist** [comment]
Also just because they have access to cables and handcuffs (arguably the HoP shouldn't ever get to touch handcuffs as part of their normal routine) already doesn't mean you should give them a short cut.

**Comment by KorPhaeron** [comment]
Asteroid has a full box of zip ties on the bridge and meta has multiple pairs of handcuffs on the bridge for years.

So either those maps are horribly imbalanced and encouraging a plague of batman HoPs to hunt down and kill every last antag or a single pair of zipties is really not a big deal.

**Comment by Fox-McCloud** [comment]
I don't see the big deal,e specially since both can waltz straight into sec and get some anyway...and even if sec is all "NO!"---they'll just grab some cable and make cablecuffs.

**Comment by Dorsisdwarf** [comment]
I still say not in their lockers, but leave a set of cuffs on the bridge

That makes it a resuseable solution for removing donkheads from your office, but not for becoming the pixelated blue line.
meta has it sussed out, man

**Comment by AnonymousNow** [comment]
It makes sense thematically for a captain to have zipties in their locker because if anyone on a station is likely to have some sort of freaky kink behind closed doors it's the captain.

**Pull request merged**
