### PR TITLE
CRAB ROCKET (requires #33436)

### PR DESCRIPTION
**Pull request by Iamgoofball**
https://www.youtube.com/watch?v=2Cv963aXxKs

Requires #33436

### CODE REVIEW

**Comment by Iamgoofball** [comment]
>Setting up build cache
$ export CASHER_DIR=$HOME/.casher
129.63s$ Installing caching utilities
0.01s
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
The build has been terminated

**Comment by Iamgoofball** [comment]
fucking travis

**Comment by Buggy123** [comment]
Missing tags:
priority: critical

**Comment by MrDoomBringer** [comment]
excellent pr

**Comment by deathride58** [comment]
~~Look, sir! Free crabs!~~

>doesn't delete fucking everything in existence the moment it spawns

>doesn't contain at least 100 crabs

Do you even cortex command, goofman

**Comment by LetterN** [comment]
>dosen't crash on the station with a rocket pod

Do you even cortex command

**Comment by Armhulen** [comment]
>they aren't free crabs

**Comment by Buggy123** [comment]
Free crabs and a _very_ expensive deluxe crate.

**Comment by awesine** [comment]
CRAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBB ROOOCKEEETTTT

**Comment by awesine** [comment]
i have a better idea:
make this a syndie item for 20 TC
you can buy it and plant a launchpad somewhere
in the next 10 seconds a crab rocket will come down, launching 50 crabs everywhere and killing everything in a 10 mile radius and causing a single tile hull breach

**Comment by davethwave** [comment]
Basically the background on the crab rocket is that in the game cortex command of which the game comes from there is a physics engine which can allow you to crush your enemies and the like with space ship parts or any body part going fast enough and so on and so forth but in the game the crabs are FREE. Allowing you to buy so many that when they are released the shear amount of them in a small space kills them instantly and turn them into gibs, those gibs since they are so compressed kind of explode everywhere in the general area crushing the enemies underneath with crab guts. There is another strange thing with them that kind of instakills enemies/allies like a shockwave effect but it's a bug that has to do with the spawn limit and all the crabs that were just spawned I believe.

**Comment by arsserpentarium** [comment]
If you want to make Travis to fuck of, rebase your master onto TG/master.Then rebase your branch onto your master.
Now travis don't wanna work without up to date branch. IDK,why.

**Comment by Bawhoppen** [comment]
Not sure if adding old memes from 2010 nobody remembers is better or is worse than adding new flavor of the day memes that will be forgotten about in a week.

**Comment by MrDoomBringer** [comment]
dont forget your DropPodOnly = TRUE var

**Comment by Buggy123** [comment]
Remember, drop pods can only buy toy crates when emagged. Be sure to set it so that you can also buy crab crates, otherwise you won't be able to crabbomb other departments!

**Comment by Iamgoofball** [comment]
>can only buy toy crates

what is this pussy shit

**Comment by Bawhoppen** [comment]
Isn't it supposed to be sabotaged and made useless? 
Not all sabotage has to result in cool flashy fireworks.

**Comment by KorPhaeron** [comment]
Stale

**Comment by Buggy123** [comment]
REEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEOPEN

**Pull request closed without merging**
