### PR TITLE
Magnitis is more aggressive, uses throw_at instead of Move at higher stages

### PR DESCRIPTION
**Pull request by Rhials**
## About The Pull Request

I got this disease yesterday and was super disappointed by the actual effects. Rather than suffer an unending waves of metal objects being thrown at my head, I noticed that stuff on the bridge kept getting disorganized, shrugged, and moved on.

Now, stages 3/4 of Magnitis will use throw_at instead of just moving objects to the infectee. This can hurt or even kill the victim in extreme cases. Remember to duck!

The messages about electrical shocks will now appear when a magnetic pulse occurs. Some of the disease messages have been slightly altered to fit this. 

Also, while we're on the subject -- Is there a joke behind Magnitis' agent "Fukkos Miracos"? Why does Magnitis make you ponder upon the nature of miracles? Why did it make you feel like "clowning around"? This stuff was written over a decade ago and I get the feeling it's referencing something that is beyond me.
## Why It's Good For The Game

Gives an old disease a bit of a facelift. Makes it more _dynamic_ and _engaging_.
## Changelog
:cl: Rhials
balance: The Magnitis disease will now hurl objects at infectees at higher stages. Watch your head!
/:cl:

### CODE REVIEW

**Comment by Serxule** [comment]
wait it was supposed to throw objects to you... are you telling me coders did a moment and made it so it just moved objects instead

**Comment by Jacquerel** [comment]
I believe the clown and miracle stuff is an Insane Clown Posse “magnets, how do they work?” joke

**Comment by ArcaneMusic** [comment]
> wait it was supposed to throw objects to you... (pretty sure some flavortext somewhere or a description says it) are you telling me coders did a moment and made it so it just moved objects instead

Old throwcode was cursed, it's still cursed nowadays but it's more managable now.

**Comment by private-tristan** [comment]
Infecting the station with magnitis and then opening up a locker with 30 circular saws in a hallway >:).

Wait doesn't magnitis still effect dead people? Wouldn't it keep throwing stuff at you even after hitting damage cap? (I can't remember if it does/doesn't)

**Comment by YakumoChen** [comment]
> Also, while we're on the subject -- Is there a joke behind Magnitis' agent "Fukkos Miracos"? Why does Magnitis make you ponder upon the nature of miracles? Why did it make you feel like "clowning around"? This stuff was written over a decade ago and I get the feeling it's referencing something that is beyond me.

https://youtu.be/8GyVx28R9-s

**Pull request merged**
