### PR TITLE
The Humanening?! But cheeked up (enlarged posterior) on a Sunday night?!?! As per our sprite lead's review?????

### PR DESCRIPTION
**Pull request by tralezab**
## About The Pull Request

Old pr: #67298

It was closed because the last spriter was too afraid to add back asses as per twat's request, and so it died. But I really do want the humanening! Not because I care about ass or assn't but because I like the face and better visuals in general. So I've elected to be the ass restorer and save the pull request, god bless america

## Pictures

My pr, only the side sprite was changed

image

Old pr so you can see the full thing

image

## Why It's Good For The Game

Taken from the old pr

Currently humans are one of the oldest sprites in the game, dating in-part to R4407. This is very obvious if you look at it for more then second. But this, this is brand new! Better looking sprites straight for your eyeballs to enjoy.

This'll prob take some getting used to, which is fair. But I feel this is an important step. So, yeah.

## Changelog

:cl: axietheaxolotl for the human, armhulenn for the butt and nothing else
imageadd: Brand new human sprites!
/:cl:

### CODE REVIEW

**Review by Imaginos16 — APPROVED** [review]
We're all down bad and should be ashamed.

Good PR.

**Comment by tralezab** [comment]
Guys I know it looks bad but what if I told you I just want the face

**Review by axietheaxolotl — APPROVED** [review]
arm is a confirmed ass man

good taste my friend

**Comment by tralezab** [comment]
> arm is a confirmed ass man
> 
> good taste my friend

I just wanted a two phase boss fight of a pr

**Comment by Twaticus** [comment]
ok arm the assening is cool and all but wheres the boobening hm?

**Review by Twaticus — APPROVED** [review]

**Comment by Acer202** [comment]
> ok arm the assening is cool and all but wheres the boobening hm?

This. No compromises!

**Comment by bluetshirtguy** [comment]
Is there a purpose to adding asses?

**Comment by tralezab** [comment]
> Is there a purpose to adding asses?

sprite lead was unhappy without them, that's really it. I just want the pretty new heads tbh

**Comment by Arctrooper8** [comment]
The heads still look weird, mostly the darker pixels near the bottom and the fact that both male and female heads are exactly the same.

**Comment by VladinXXV** [comment]
> The heads still look weird, mostly the darker pixels near the bottom and the fact that both male and female heads are exactly the same.

I second this about the darker pixels at the bottom. Ghoulish and bony lookin face.

**Comment by Likteer** [comment]
@tralezab Just a quick reminder that @Ghilker is the codeowner of asses now, you need to consult it with them!

**Comment by iwishforducks** [comment]
tom holland lookin ass cheekbones
image

**Comment by RedBaronFlyer** [comment]
Yeah, the faces still kind of throw me off. They look really "sharp" for a lack of a better word. Honestly it reminds me of Agent 47 for some reason with the chin and cheeks (for the face).

Regardless I still like them more than the current ones, which just don't look good at all and definitely look the worst out of all the playable species. I'd love to see some more examples of how they would look in uniform and how they would look in gameplay since you'll rarely see the sprites this close up.

**Comment by BlueMemesauce** [comment]
> tom holland lookin ass cheekbones image

image

**Comment by Imaginos16** [comment]
Yeah good enough. Guess the spacemen get to keep their cake

**Comment by Megamaw** [comment]
Put it back.

**Pull request merged**
