### PR TITLE
Surrounds transit space with rivet walls

### PR DESCRIPTION
**Pull request by Cyberboss**
Because if you manage to break free somehow you shouldn't be able to reach the rest of z2

### CODE REVIEW

**Comment by coiax** [comment]
Transit space should be more of a barrier than indestructible walls... :/

**Comment by coiax** [comment]
I'm not sure if there any methods of teleportation that work on Z2? Wasn't wizard jaunting reenabled?

**Comment by kevinz000** [comment]
fixes the effects instead of the cause.

**Comment by Cyberboss** [comment]
It's more so that if people find a way to get out. They should still be contained somehow to prevent them from reaching centcom

**Comment by coiax** [comment]
What if we had a Centcom tracking subsystem, which alerts admins if anyone who isn't on the "list" is on Z2. The list would include any ERT, inspectors, wizards, ninjas, abductors, that sort of thing.

**Comment by coiax** [comment]
Alternatively, we just have transit space be its own zlevel. How expensive would that be?

**Comment by Bawhoppen** [comment]
there are definitely ways to get out if you try hard enough

**Comment by optimumtact** [comment]
https://www.youtube.com/watch?v=9Deg7VrpHbM

**Comment by Militaires** [comment]
you can still get past those walls.

**Comment by lzimann** [comment]
This is really not the way to go.

**Pull request closed without merging**
