### PR TITLE
Belt sprites for the syndie screwdriver and alien tools

### PR DESCRIPTION
**Pull request by Ebb-Real**
## About The Pull Request

The syndie screwdriver was using the wrong belt sprite and the nukie sprite only got used for the alien screwdriver for some reason. This PR fixes that and adds new belt sprites for the nukie screwdriver and all of the alien tools which had none before.

Before:
Belt Before

Belt Before Abductor

After:
Belt After Traitor

Belt After Abuctor

Belt After Abductor+

## Why It's Good For The Game

Less things without sprites and less bugged sprites.

## Changelog

:cl:
fix: Fixes the syndie screwdriver using the wrong belt sprite.
imageadd: Added belt sprites for the syndie screwdriver and all alien tools.
/:cl:

### CODE REVIEW

**Comment by Ebb-Real** [comment]
did i break the tag bot

**Comment by SmArtKar** [comment]
> did i break the tag bot

you broke ALL THE BOTS

**Comment by Ebb-Real** [comment]
how did i manage this haha

**Comment by Ebb-Real** [comment]
the commit fixed them cool

**Comment by Ebb-Real** [comment]
is this what fucks up the check

**Comment by Ebb-Real** [comment]
checks my beloved

**Pull request merged**
