### PR TITLE
Adds non-clothing item equipping others feedback messages

### PR DESCRIPTION
**Pull request by ArcaneDefence**
## About The Pull Request
Things like pens weren't giving any feedback messages when you put them on someone else, and I ran into this while working on another PR so I've dealt with that

Renames `worn_dangerous` to `show_visible_message` as it was only used to confirm if there would be visible messages or not 
The `DANGEROUS_OBJECT` clothing flag is a trait now, so it can be put on non-clothing items too
Removing non-clothing items from someone has been unchanged.

## Why It's Good For The Game
People should be able to identify that someone is putting something on them, and recognize what that is if they pay attention.
This means that a player cannot reverse pickpocket a grenade onto someone else without giving any indication of doing so

## Changelog

:cl:
balance: Putting a non-clothing item onto someone else creates a visible message the same way a clothing item would.
/:cl:

### CODE REVIEW

**Review by Mothblocks — APPROVED** [review]

**Comment by blackdav123** [comment]
> This means that a player cannot reverse pickpocket a grenade onto someone else without giving any indication of doing so

coders removing FUN again 1984 1984 1984

**Comment by ArcaneDefence** [comment]
> coders removing FUN again 1984 1984 1984

I'm trying to make it so you can put a trashbag on your own head and suffocate and die, or force that bag on someone else's head.
Go away.

**Comment by AlamoTurtle** [comment]
I thought not seeing when someone picked your pocket was intended, regardless of item danger.

**Comment by Mothblocks** [comment]
Correct, I didn't see this affecting that though, am I wrong

**Comment by ArcaneDefence** [comment]
> I thought not seeing when someone picked your pocket was intended, regardless of item danger.

This pr is about putting things on other mobs, not removing them.
`This proc calls at the begining of anytime an item is being equiped to a target by another mob.`

Pickpocketing is unchanged in `start_unequip()` and handles its own warning with `warn_owner()`

**Pull request merged**
