### PR TITLE
Pacman small rework - less power, more consumption - no more super

### PR DESCRIPTION
**Pull request by Ghilker**
## About The Pull Request
This change reworks how pacmans works. The changes are:
- Pacmans no longer require stock parts (no more upgrade memery)
- Base pacman power generation ranges from 2500 W to 10000 W
- Base pacman max held sheets is 10
- Base pacman sheet consumption speed has been quintupled
- Super pacman no longer exists, the circuit board now switches between a low production - low consumption mode to high production - high consumption mode and viceversa
- This new mode has a max held sheet of 5, power generation goes from 15000 W to 60000 W and consumes sheets ~3 times faster than the base pacman

Current pacman generation:
-at t1 they are able to make from 10 kW to 40 kW, quadruple that at t4 so from 40 kW to 160 kW.
-a superpacman will produce from 30 kW to 120 kw at t1, from 120 kW to 480 kW at t4.
New pacman generation:
-ranges from 2.5 kW to 10 kW for normal one
-ranges from 15 kW to 60 kW for the more powerful version

## Why It's Good For The Game
With the power rebalance done the SM keep on becoming more and more important as supplier of power for the station.
The pacman is a small machine that can outshine the SM quite easily without any effort whatsoever. This change turns it into a portable power provider that can output enough juices to power a couple of rooms, instead of being this huge power supplier (yes a super pacman could output over 480 kW of power, half of what a basic SM can produce!). It works well enough to kickstart the emitters or any non-power-hungry room when there is a lack of power.

## Changelog

:cl:
balance: Pacmans no longer require stock parts (no more upgrade memery)
balance: Base pacman power generation changed from 10-40 kW (t1) and 40-160 kW (t4) to 2.5-10 kW 
balance: Base pacman max held sheets is 10
balance: Base pacman sheet consumption speed has been quintupled
balance: Super pacman no longer exists, the circuit board now switches between a low production - low consumption mode to high production - high consumption mode and viceversa
balance: This new mode has a max held sheet of 5, power generation changed from 30-120kW (t1) and 120-480kW (t4) to 15-60 kW and consumes sheets ~3 times faster than the base pacman
/:cl:

### CODE REVIEW

**Comment by cacogen** [comment]
Have you tested how this impacts Charlie Station, given they need it to keep the station going until the solars are set up, which takes about 15 - 20 minutes depending on who's doing it?

**Comment by Ghilker** [comment]
> Have you tested how this impacts Charlie Station, given they need it to keep the station going until the solars are set up, which takes about 15 - 20 minutes depending on who's doing it?

charlie (oldstation) has a smes connected to the pacman (that is a high power mode too), once they start producing and charging the SMES, with proper setup (in/out power) it should last around 15-20 minutes

**Comment by Jolly-66** [comment]
> charlie (oldstation) has a smes connected to the pacman

The generator is **not** wired up directly to the SMES. Players need to either move it around or have it hot wired into the main powernet.

**Comment by Ghilker** [comment]
> The generator is **not** wired up directly to the SMES. Players need to either move it around or have it hot wired into the main powernet.

image
uh is like right there, you just need to connect it

**Comment by Jolly-66** [comment]
> Ghilkers reply

You pointed out it was already wired up, I was just correcting a misunderstanding.
I also pointed out the current set up isn't ideal and could be managed better, but that's a gameplay pov not a mapping pov.

**Comment by Ghilker** [comment]
ah yes, you're right in that aspect

**Comment by JohnFulpWillard** [comment]
> edit:also they have a couple of low power rtgs

😦

**Comment by Colovorat** [comment]
Maybe button in UI instead of switching mode on circuit? Plus it's totally not a small rework, it's a huge balance rework to it

**Comment by moocowswag** [comment]
Is the goal of this pr to force the shuttle to be called everytime the sm gets delammed because engineers selfantagged/experimented with the sm.

A nerf to pacmans is justify-able but they consume plasma and uranium while the sm just consumes..its own power output to run... so it makes sense as to why they would be able to compete with the sm, although max power output of each pacman could be halved or more due to cut down on their space efficiency.

**Comment by GuillaumePrata** [comment]
> balance: Pacmans no longer require stock parts (no more upgrade memery)

This alone makes it good for me.

**Comment by CRITAWAKETS** [comment]
honestly pacman values were fine, just halve the effect of upgrades

this is way too much of a nerf to have pacmans really be useful past anything but starting a few emitters up

**Comment by Ghilker** [comment]
> honestly pacman values were fine, just halve the effect of upgrades
> 
> this is way too much of a nerf to have pacmans really be useful past anything but starting a few emitters up

That's the point, they are to power up a room or two, not the entire station with two or three of them.

**Comment by ZerVexon** [comment]
Oh boy, another thing that's being nerfed in your quest to force people into doing what you want. What a surprise from a Ghilker PR. 

I found removing Tesla and Singulo engines as a good move, since they were undeveloped compared to the sm. Both of them really couldn't be experimented with, the way the SM has gas interactions, and it going south was an immediate shuttle call since re-containing either was a fool's errand, but a delam only blew Engineering. A dedicated squad could rebuild and restart an SM engine. It was too easy to just sabotage the station by just letting the tesla or singulo loose, so they were removed in the hope that someone later might reimagine them, which is totally fine.

This is not that.

Purposefully nerfing all the other options so that only one is worth using is a form of pigeonholing. It's removing player agency, and it's making the game even more unapproachable (which is already an issue) by forcing that "only one worth using" to be one of the more complex mechanics available. A basic N2 SM should be able to power a normal station, for the simple fact that the majority of players cannot do more than that. Forcing people is not going to make them understand and forcing them to do something they dont want to is going to cause resentment, not encourage growth. 

At the end of the day, this is supposed to be a game. You need to act like you're developing for a game, not for some thesis study. You need to make exceptions to reality to promote both balance and fun, and this really doesn't strike me as being either.

**Comment by Shadowflame909** [comment]
Why is there a want for increasing reliance on a functional engineering team in a game all about sabotage.

Didn't the codebase want longer shifts?

Maybe I could see it if portable pacs were findable in maint, like how you dont have to be a doctor to find medkits and such.

**Comment by private-tristan** [comment]
I guess the moment SM gets sabo'd by 1 person/an incompetent engi a shuttlecall is forced because there's no feasible way to power the station without spending 30 minutes setting up an SM shard for power?

**Comment by thgvr** [comment]
turbine makes power

**Comment by Colovorat** [comment]
Despite comment above being minimized as disruptive content it has a point

>The way you would actually inspire growth? You incentivize learning, instead of punishing for not knowing.

Honestly yea, delamming SM is the meta to call the shuttle, and now? it's even more punishing if you lack capable engineers. With the increase of power consumption solars are not gonna power station. In the current time, if SM is delammed, station dead. And no ghilker, people are not gonna go set up a turbine if SM is blown up

**Comment by private-tristan** [comment]
> turbine makes power

atmos is literally like, 50 tiles from SM, if SM gets delam'd and goes boom, there's a very high chance that atmos is also rendered unusable, meaning no gas for turbine, and a forced shuttlecall because the flux anomalies spawned from delam will also render the station completely spaced along with killing wire connections even if turbine gets set up.

**Comment by MrStonedOne** [comment]
I just don't understand why you are nerfing the power generation of pac mans to 1/100 of the old value. couldn't you do less.

**Comment by Ghilker** [comment]
> I just don't understand why you are nerfing the power generation of pac mans to 1/100 of the old value. couldn't you do less.

because they generated 100 times more power than they needed to, i'm designing them with the ability to power up a couple of rooms without heavy machinery (or have them disabled) instead of half the station. You can still spam them easily and generate more power if needed. I'll add some pre-loaded ones in maint

**Comment by MrStonedOne** [comment]
Actually, looking at the code, I think you made it a 1:100,000 reduction??? wtf?

**Comment by Ghilker** [comment]
> Actually, looking at the code, I think you made it a 1:100,000 reduction??? wtf?

Current pacman generation:
-at t1 they are able to make from 10 kW to 40 kW, quadruple that at t4 so from 40 kW to 160 kW.
-a superpacman will produce from 30 kW to 120 kw at t1, from 120 kW to 480 kW at t4.
New pacman generation:
-ranges from 2.5 kW to 10 kW for normal one
-ranges from 15 kW to 60 kW for the more powerful version
no idea where you took the 1:10000 reduction

**Comment by MrStonedOne** [comment]
> no idea where you took the 1:10000 reduction

no where, i just wanted to force you to mention the old values in the pr.

which you should have done from the start btw. =P

**Comment by Ghilker** [comment]
> no where, i just wanted to force you to mention the old values in the pr.
> 
> which you should have done from the start btw. =P

Not even mad that's based

**Comment by Richie9999** [comment]
Late to the party I know, but is anything planned to be done to rebalance the white ships that rely on the pacman to keep their SMES running? As is, short of the explorer bringing fuel or finding the right kind of rocks they're gonna run out of power before too long.

**Comment by RikuTheKiller** [comment]
This kinda sucks ass, figured out you could no longer use pacmans.

Honestly just kind of makes it useless, after a delam I just kind of call shuttle without even thinking twice, even if it was a good round there's just no way to save it.

**Comment by DAKKA-WAAAGH** [comment]
Is there even a point in keeping these in the game anymore except for the off-station ruins and shuttles that use them?
I've rarely even used them on the station before and now I don't see a purpose in even mapping them in anymore.

I wish I hadn't been told about this PR.

**Pull request merged**
