### PR TITLE
Adds an Improvised Riot Shield, adds block_chance, and fixes a small nuisance.

### PR DESCRIPTION
**Pull request by Firecage**
1. This adds an Improvised Riot Shield, sprites for it, and a way to craft it. It is made via tablecrafting. The items requiered to craft it is a single metal sheet, a single cable coil, and 2 cable cuffs. The tools required is a welder and a wirecutter.
2. Adds a block_chance thing. Currently everything is on the 50% chance they normally were, though the Improvised Riot Shield has a 20% chance. On that note, the strongest guns would render it obsolete though due to how blocking works.
3. THis removes the annoying thing of projectiles still hitting you even if you do successfully block them. 

Tested and everything appears to work. if I screwed something up, please inform me.

### CODE REVIEW

**Comment by SconesC** [comment]
But for what purpose? Who is the intended usergroup? We don't need MORE improv weapons, especially ones that can't even be purported as 'self defense' like a SHIELD TO BLOCK PROJECTILES.

**Comment by Lumipharon** [comment]
Make it plasteel so they require atleast a small amount of effort (aka: partially decon an random r-wall, or loot eva).

Honestly don't see the point in this though, since you can just get roman shields already.

**Comment by Firecage** [comment]
Scones. Its only a 20% chance though, which is even further decreased by a weapons damage / 3. So for all intents and purposes, they aren't even very useful.

**Comment by SconesC** [comment]
But I'm not questioning how good it is - Rather, the intent behind it existing at all.

I'd much rather have you answer my questions, which are founded in concern that tools like this, especially ones that /have no applicability in self defense/ will just be used for antag hunting by assistants. While I don't think we should be removing things that already do that (Spears, Prods, etc.) I don't think adding more of these things is a good idea. At all.

I think you're also missing a serious point here. Riot shields stop electrodes. A 20% chance is honestly actually somewhat serious. These are cheap and are only going to be used by revs/crew in nuke/shitters trying to get that free block to evade sec.

**Comment by ike709** [comment]
>tablecrafting

no

**Comment by PKPenguin321** [comment]
>tablecrafting

no

**Comment by Fox-McCloud** [comment]
Greysec

Stunprod? Check
Cable restraights? Check
Makeshift Shield? Check

**Comment by SconesC** [comment]
Except this is something that head coders and admins alike have agreed upon in regards to trying to cut down on it, and not encourage it.

**Comment by freerealestate** [comment]
>I don't think people are grasping the gravity of "1/5 nonlethal projectile shots will not hit you".

That it's nothing, and the shield is basically useless?

**Comment by duncathan** [comment]
It means you have a chance to make a stun not stun. 20% chance to not immediately lose the fight is a significant thing.

**Comment by Dorsisdwarf** [comment]
This is intended for revs and shit, isn't it?

**Comment by freerealestate** [comment]
Immediately losing the fight because you were shot once is dumb in the
first place. 1/5 is a very small chance.

I'd never waste my time with this shield because as it is, it's a
paperweight. Giving it a practical chance to block (e.g. more than a coin
flip) and limited uses would be better.

**Comment by SconesC** [comment]
Currently /tg/station combat is decided in absolutes and shields are a shitty RNG diversion from that.

You get the first hit

"lol i shield"

He hits you. You are stunned.

You lost to a 1/5 random chance.

It's shit. RIOT GEAR equivs should NEVER be craftable.

**Comment by KorPhaeron** [comment]
I think validhunting assistants are more exciting than sec officers personally.

Random crew armed with makeshift weapons and stolen guns facing off vs some unknowable horror in a burned out hallway because the entire security force died half an hour ago is one of my favorite situations in the game.

**Comment by Firecage** [comment]
Scones. Honestly I don't mind them being able to block electrodes with a 1/5th chance, since being instantly dropped due to a single shot in itself is extremely stupid. And honestly I don't see how antaghunters would even frequently use these shields since they are very unreliable, while things like stunprods again are very reliable, that's why they get used. Also. I do kinda think I should perhaps change the requirement to a plasteel sheet, or maybe 2, instead of normal sheets, since it is kinda to cheap. Or follow Cheridans idea to use wood for the wooden bucklers.

Besides. Would be cool for Rev to have makeshift shields.

**Comment by PKPenguin321** [comment]
\>trading a whole half of your precious hand slots for a 1/5 chance at blocking a stun
the tradeoff is seriously huge for something that will only save your ass 1/5 of the time. no matter how much you want to deny it, this is far from unbalanced (if it ever gets used at all, as it stands it looks a little underpowered)

**Comment by SconesC** [comment]
Rev-specific recipes are a good idea.

@KorPhaeron 'Cept there are no unknowable horrors because antags are underpowered and sec is overtuned, no need to buff auxiliaries

**Comment by Miauw62** [comment]
>encouraging validhunting
>a good thing

in what way does this shield add something to the game.

**Comment by Firecage** [comment]
It adds a shield to the game.

**Comment by palpatine213** [comment]
Having a makeshift version of something that sec officers don't spawn with, and have to go ask the warden to get one from the armory seems like a terrible idea. 1/5 chance to block taser shots means a lot when you're a sec officer with a 0% chance to block taser shots chasing an assistant with a stolen taser.

**Comment by Saltycut** [comment]
I don't like it, sorry. Next step from this is makeshift taser :-1: Group antags strenght should be in quantity not quality.

**Comment by Tokiko1** [comment]
What if the shield only blocked melee attacks? You could probably even raise the blockrate if that was the case.

**Comment by pudl** [comment]
I feel like if people stop replying to this, then it will eventually stagnate until it's forgotten about and someone will yolomerge it like the HoS sidearm. Can we talk about how bad it is again?

**Comment by Cheridan** [comment]
@Firecage Make a poll, I guess.

**Pull request closed without merging**
