### PR TITLE
These things also belong in a museum

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
:cl: Kor
add: Added the treasure hunter's hat, coat, uniform, and whip. These aren't available on the map yet, but will be available to the librarian soon.
/:cl:

http://i.imgur.com/Kuz21uw.png

Please merge this sooner rather than later as it touches every clothing file thanks

Why I think this is a good idea: Librarian is the least popular job. Every job should have some gimmicky special object (or objects) that make players feel special, and not want to kill themselves when they get assigned said job.

### CODE REVIEW

**Comment by RandomMarine** [comment]
Now librarians can tide with a special weapon too.

**Comment by ExcessiveUseOfCobblestone** [comment]
Girls should get lara croft outfits

**Comment by Fox-McCloud** [comment]
I'm guessing this is a joke...given the ridiculous armor values and strength of the whip.

**Comment by Archie700** [comment]
why not just make a locker or a container for them

also why add a whip

**Comment by ExcessiveUseOfCobblestone** [comment]
> not getting the reference

**Comment by RandomMarine** [comment]
I think a plain whip should do negligible brute damage but also deal a chunk of stamina loss.

**Comment by Incoming5643** [comment]
If nothing else, we should make this a ruin of some kind and put the clothing in a fridge.

**Comment by PKPenguin321** [comment]
shouldn't have been closed, although maybe the whip shouldn't disarm.

**Comment by KorPhaeron** [comment]
It's gonna be part of goofs pr now

**Comment by KorPhaeron** [comment]
Goof's PR is dying

**Comment by coiax** [comment]
Splitting PRs into smaller parts, especially when part of them are controversial are fine.

**Comment by optimumtact** [comment]
Nerf it so I can merge it

**Comment by KorPhaeron** [comment]
There are no balance concerns though. The librarian has no access, no gear, nothing. A single pseudo baton won't break the game.

**Comment by PKPenguin321** [comment]
yeah honestly whip's probably fine, people will for sure bitch about it though

ps make the reach weapon system and put the whip into it

**Comment by KorPhaeron** [comment]
People will bitch about anything that kills them, doubly so if it is something new

**Comment by Chocobro** [comment]
>Librarian is the least popular job.
Lawyer
:)

**Comment by KorPhaeron** [comment]
Librarian is least popular when measured by number of people with the job set to high, Lawyer is least when you account for high+medium

**Comment by LarissaMayrink** [comment]
Has someone made a new sprit for that whip?

**Pull request merged**
