### PR TITLE
Mymap

### PR DESCRIPTION
**Pull request by mr0wnpie**
## Changelog
:cl:
add: Added new mechanics or gameplay changes
add: Added more things
expansion: Expands content of an existing thing
del: Removed old things
qol: made something easier to use
balance: rebalanced something
fix: fixed a few things
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

### CODE REVIEW

**Comment by CRITAWAKETS** [comment]
are you a bot

this map legit looks like what a terrible neural network would make for a map

badly placed decals, improper design, rnd being in a chemistry room, parts straight copy and pasted from other maps

**Comment by LemonInTheDark** [comment]
> 
> 
> are you a bot
> 
> this map legit looks like what a terrible neural network would make for a map
> 
> badly placed decals, improper design, rnd being in a chemistry room, parts straight copy and pasted from other maps

For the record, this was what we might call in the business a mistake
Please stop being such a dick

**Comment by Bamhalazam** [comment]
someone told me that you were merging yourself as a host.

the beestation general channel loves you. based.

**Comment by EOBGames** [comment]
> someone told me that you were merging yourself as a host.
> 
> the beestation general channel loves you. based.

Tell the beestation general channel that the codebase's admins.txt doesn't actually affect anything on the live servers for me, would you? I want to make sure theyre not getting the wrong idea about that.

**Comment by RandomGamer123** [comment]
> > someone told me that you were merging yourself as a host.
> > the beestation general channel loves you. based.
> 
> Tell the beestation general channel that the codebase's admins.txt doesn't actually affect anything on the live servers for me, would you? I want to make sure theyre not getting the wrong idea about that.

Although now you say that I recall seeing somewhere that many smaller / more obscure tg downstreams actually keep the admins.txt for the most part so people on there just have admin on random servers

**Pull request closed without merging**
