### PR TITLE
Resprites the Pizzas, Mothic Pizzas and Pizza Boxes

### PR DESCRIPTION
**Pull request by AdipemDragon**
## About The Pull Request
This PR makes pizzas look nicer looking and, frankly, easier on the eyes. Yes, it touches two variables, but it's for making the new pizzas fit into the new pizza boxes, so it's for a good cause.

## Why It's Good For The Game
Come on, you're gonna tell me having nicer looking pretend food for our pretend space jobs is bad for the game somehow? Just take a look for yourself!
image

## Changelog

:cl:
imageadd: Chefs got a whole lot better at making visually apealing pizzas! Their boxes got spiffied up to match, too.
/:cl:

### CODE REVIEW

**Comment by optimumtact** [comment]
picture of spiderman deliveirng pizza from the original spiderman movie, it is captioned with pizza time

**Comment by DragonTrance** [comment]
These look really fucking outstanding. Also love the background where you actually took time to make the tables look good

**Comment by cacogen** [comment]
If I flip the pizzas, Mr. Aziz will flip out!

**Comment by AdipemDragon** [comment]
> -On the now old, the "open pizza box that has a pizza" sprite had some details on the top side of the box making it look delicious, i think it would be a great addition to this. What do you think?

Well, I Did rough up the bottom of the top flap when a pizza is in the box, I just made them only really be a grease stain, to account for the fact that there's... really no universal color for all the pizzas, minus the crusts, and how are the crusts gonna stick to the top now? 
image

> -These pizza boxes give the feel that they are made of hard material and its solid in my opinion.

I tried to go for the same feel the other cardboard boxes have, and nobody really complained about the look when I showed it off in the discord, so I dunno.

**Review by Krysonism — APPROVED** [review]
Looks excellent. Good job!

**Comment by Imaginos16** [comment]
Amazing job, god bless.

**Comment by AdipemDragon** [comment]
God, I was almost ready to pull a "haaaaa you let the pizza get stale" joke on this pr, I was kinda losing it waiting for that

**Comment by optimumtact** [comment]
if we let it go stale u would have eaten it all tubs

**Pull request merged**
