### PR TITLE
Morphs now take the entire tile regardless of their current form

### PR DESCRIPTION
**Pull request by silicons**
Yeah uh, itś pretty dumb when morphs transform into a very tiny object and youŕe force to either use a gun which not everyone has, or click on the 3 pixels that it is at the moment while itś still able to smash everything and attack you.

### CODE REVIEW

**Comment by 81Denton** [comment]
>while itś still able to smash everything and attack you

Isn't that why disguised morphs only deal 5 damage per hit

**Comment by ExcessiveUseOfCobblestone** [comment]
This is a pretty big nerf to have 0 compensation.

**Comment by ChangelingRain** [comment]
wouldn't it be better to reduce or remove transformed morph damage instead of making them both obvious and easy to attack while transformed

**Comment by PKPenguin321** [comment]
Yeah this is the wrong way to go about this

**Comment by PKPenguin321** [comment]
Forcing them to drop disguise if they attack while disguised would probably be fine

**Comment by Shadowflame909** [comment]
Good idea PK, that fits even lore wise as well. "The Thing" never attacks disguised!

**Comment by Barhandar** [comment]
Why not have janitor do its job for lack of 3pix cigarette butts for morph to eat?

**Comment by kevinz000** [comment]
@Barhandar it can transform into one the moment it sees one and stay that way for a potentially infinite amount of time i don't see how that is a valid argument tbh, this applies to any item. 
@PKPenguin321 wouldn't that nerf it harder than this? that slows it down immediately instead of still allowing it to hit at full speed. also, that doesn't solve the issue of 3px bullet casings/cigarette butts being practically unhittable in melee.
@ChangelingRain ^
@Shadowflame909 this will not ruin morphs i assure you, they still get their full speed movement and hitting a mouse opacity 2 object is harder than you think if it still gets to move at full speed.

**Comment by ExcessiveUseOfCobblestone** [comment]
You can miss the unchanged sprite, you can't miss the morph when you hardcode it to take the entirety of the tile.....

**Comment by PKPenguin321** [comment]
>wouldn't that nerf it harder than this? that slows it down immediately instead of still allowing it to hit at full speed. also, that doesn't solve the issue of 3px bullet casings/cigarette butts being practically unhittable in melee.

The thing is that attacking while disguised is laughably useless unless you're cheesing it like how you described in the OP, so we're not losing anything my removing it. Plus, if disguised morphs are now mostly harmless, then you don't have to worry about whether or not you're able to click/catch them anyways. Solves both issues at once.
Meanwhile, your change makes their disguise much easier to notice and gives a hard passive nerf 24/7 to all morphs, even ones that don't attack while disguised.

**Comment by ShadowDeath6** [comment]
making it an obvious tell that a morph is on a tile is the exact opposite of their disguise nature and anyone with a brain will immediately be able to tell that a morph is disguised by hovering their mouse on the floor where they think the morph is

**Comment by Shadowflame909** [comment]
You were convincing me Kev, but pk penguin brings up a good point. disguises should be an advantage, speedy and makes you blend in. I say let the bullets have less of a chance to hit transformed morphs. Just force them out of there transformation when attacking, don't let them cheese with there speed. Force them to be a glass cannon in both forms.

**Comment by kevinz000** [comment]
You would always be worried because they can always undisguise and break everything. Side antags shouldn't be nearly unkillable.

**Comment by Shadowflame909** [comment]
Have you played as a morph Kev? They can be shot from range with lasers, bullets and everything. There real strategy is gtfoing before the guy with the gun pulls it out. They still get hit with them in a long corridor anyways. Why increase the chances of them getting hit. It's not that hard to kill a morph. Especially since it only fights in it's SLOW form. That has a cool down to go into it's fast one.

**Comment by optimumtact** [comment]
I'm perfectly happy to merge a morph removal, or this pr

pick your poison cobby

**Comment by Shadowflame909** [comment]
>This PR or morphs get removed.             SMH you can't just say you want the BASED better ling more cannon to there source material removed. Das lame.

**Comment by Shadowflame909** [comment]
Github needs a sad emoji. What a sad comment oranges has left!

**Comment by PKPenguin321** [comment]
Would be nice if kevinz replied to my post instead of just ignoring it and leaving the PR open
Morphs are not hard to kill btw, here I made this way back: https://tgstation13.org/phpBB/viewtopic.php?f=2&t=55&start=1700&hilit=kill+morphs#p243730

**Comment by optimumtact** [comment]
yes, I can say that and I will

**Review by ChangelingRain — CHANGES_REQUESTED** [review]
Reduce their transformed melee damage to 3-1 instead of this, or alternatively remove it entirely.

If complaints about lethal transformed morphs persist when they do that little damage, remove them.

**Comment by Shadowflame909** [comment]
Morphs aren't even OP and PK Penguino had the perfect solution, why make them do any damage at all in there transformed states. If people didn't try to melee morphs alone, (BASICALLY PRETEND MORPHS ARE NIGHTMARES. WHY WOULD YOU 1V1 THEM) We wouldn't have this issue..

**Comment by PKPenguin321** [comment]
I can look into coding my version of the change tomorrow

**Comment by ExcessiveUseOfCobblestone** [comment]
@optimumtact given those options I'd just go for removal, although I'd prefer lower damage output while transformed.

Or just make it undisguise with a cooldown when it eats/attacks like how most morphs in games (I'm thinking Terarria and Dark Souls) work.

**Comment by Shadowflame909** [comment]
Oranges, why do you gotta deadlock us with a non-solution to any problem. The real problem is the one inaba complained about, that I agree with. That pretty much everyone here agrees with, using the meth speed gettaway form to hit and run shouldn't be a thing. That's a problem that everyone agrees needs a solution. This has nothing to do with that, and Will just bring around another nerf pr if this one gets merged. I mean everyone also agrees on what the proper solution is as well. Nerfing "gotta go fast" forms damage to 0. Or having you swap into the tank slug like armblade damage form your supposed to attack in, when you do attack. Giving you a cool down before you can swap back to the fast form, and making it fair to fight. IE the simple strategy of throw shit at it until it dies, and Don't try to punch it to death. Even a floor tile will kill it.

**Comment by optimumtact** [comment]
Well shadowflame, it's because there are too many people who do the following

1) see a change they dont' like
2) suggest two or three throwaway ideas
3) scream improve don't remove
4) do absolutely nothing at all to actually code or implement any of those ideas
5) expect people to take them seriously or listen to what they're saying

so yeah, I'm gonna be a hardass about it, and those people can either put up or shut up

**Comment by Shadowflame909** [comment]
I say all of those fit me very well. But what if instead of ignoring the idea man...You trusted and listened to what the community is saying because they expect you to have the communities interest? I blame codebase separation!

**Comment by optimumtact** [comment]
There are over 3000 unique players on this server every month, you represent a vanishingly small portion of them, it's not enough to just say "I believe it should be this way", you need to be willing to do the work too.

I do listen to what people say, but when it's the same 10 people with the same 10 comments doing the same zero amount of work, why should I credit them with anything?

**Comment by improvedname** [comment]
3000 unique player alts*

**Comment by improvedname** [comment]
Besides
@kevinz000
Cant you do some invinsible overlay thing so if you click on the tile the morph is on it still tatgets them and if you dont it just go over em

**Comment by optimumtact** [comment]
that wasn't so hard was it

**Comment by Shadowflame909** [comment]
Wow I goofed. It didn't actually get merged kev! The more you learn

**Pull request closed without merging**
