### PR TITLE
IT'S TIME FOR SHAFT MINERS TO STOP

### PR DESCRIPTION
**Pull request by Iamgoofball**
NO MORE

WHERE THE FUCK ARE YOUR ADMINS

### CODE REVIEW

**Comment by YakumoChen** [comment]
I don't think we need to restrict that, miner headrev causing a loss happens so infrequently that it's not worth patching.

**Comment by kilog** [comment]
lol ok

**Comment by Iamgoofball** [comment]
kx0htbp

**Comment by YakumoChen** [comment]
yeah it happens once in a blue moon, most headrevs are competent enough to see the giant red antag text at the beginning of the round.

**Comment by Iamgoofball** [comment]
isnt there a shaft miner spawn on lavaland though

**Comment by YakumoChen** [comment]
no

**Comment by Jalleo** [comment]
*sigh

**Comment by xxalpha** [comment]
Another goofy "fix".

**Comment by AlexCrimson** [comment]
Not really needed. If the Shaft Miner is dumb enough to leave the station as a head rev, then they probably would not do very well in the first place.

**Comment by KingDairy** [comment]
to be fair, in the age of everyone loves lavaland, a shaft miner staying on the station all round is pretty rare too

**Comment by Jalleo** [comment]
Perhaps we should make it so a shaft miner cantbe the only rev head?

**Comment by jughu** [comment]
Just make it so on the outpost they are oke but if they go outside lavaland they get a warning which takes 1 minute if they dont go back end round

**Comment by DfourC** [comment]
Just have admins warn/ban miners who end a rev round super-early by leaving the z-level. If you aren't paying attention to your own antag status you shouldn't have that shit enabled.

**Comment by Iamgoofball** [comment]
@DfourC thats fucking retarded and so are you, banning people for easily fixed code issues is absolutely batshit fucking insane and you need to rethink your entire goddamn life thesis

**Comment by DfourC** [comment]
It's literally not a code issue though, it's the players acting on it.

**Comment by KingDairy** [comment]
the job that does everything off-station getting the antag role that requires you to always be on-station sounds like an issue to me

**Comment by Aloraydrel** [comment]
this is kinda dumb tbh

**Comment by Saegrimr** [comment]
Don't be stupid.
Also.
>3 minute round
>92% survival rate

**Comment by bobdobbington** [comment]
Literally the hero viva rounds needed

**Comment by Midaychi** [comment]
Move the station to lavaland when?

**Comment by optimumtact** [comment]
This is an administration/player problem, so unless the headmins come to us and request this I don't see any reason to include it.

**Pull request closed without merging**
