### PR TITLE
Revert "Removes singularity, tesla, TEG and Mrs. Pacman. Changes supermatter overcharge delam."

### PR DESCRIPTION
**Pull request by Terra1**
### About The Pull Request
Reverts tgstation/tgstation#52873

### Why It's Good For The Game
Literally nobody wanted this merged. Absolutely nobody. It makes the game fundamentally less interesting for absolutely zero gain.

### Changelog
:cl: Terrariola
rscadd: MRSPACMAN generators as well as all Particle Accelerator-based generators have been re-added to Nanotrasen's catalog.
/:cl:

### CODE REVIEW

**Comment by LittleNyanCat** [comment]
A small glimpse of hope that is sure to be crushed by orange's hate for the concept of fun, but we appreciate the effort anyway

**Comment by Featherfield** [comment]
TG coders are retarded lmao

**Comment by trexter555** [comment]
coders are bad at communicating but i have to hope they actually cared about the massive dislike ratio on that pr

**Comment by MarkSuckerberg** [comment]
Not to be the asshole, but I'm pretty sure there's a policy against revert PRs being done so quickly after the thing being reverted was merged. This isn't going to make things any better whether it's for the best or not. Just don't blame the maintainer who closes it for following policy.

**Comment by Iamgoofball** [comment]
i wanted it merged with changes

**Comment by FloranOtten** [comment]
How To Get Banned Off The Repo: With Pictures!

**Comment by Detective-Google** [comment]
regardless of whether this is a good idea or not kneejerk reverts are always closed.

**Comment by LemonInTheDark** [comment]
I wanted it merged with the tesla readded

**Comment by wesoda25** [comment]
Keep TEG gone it sucks

**Comment by AlucardHellsingChapel** [comment]
Teg is awesome Just make things that will require more energy to use or make everything use more

**Comment by francinum** [comment]
As a pseudo-downstream trying to make power more important to the central balance of the game...

The TEG is a pain in my side. I fully support it's removal, the rest I believe justify their existence *with power output tweaking*

**Comment by Fabian272** [comment]
The PR basically made engineering without atmos just repair and build new non power making stuff

**Comment by msgerbs** [comment]
> 
> 
> As a pseudo-downstream trying to make power more important to the central balance of the game...
> 
> The TEG is a pain in my side. I fully support it's removal, the rest I believe justify their existence _with power output tweaking_

Surely you should be removing them in your downstream instead and not here voting for PRs nobody in this community wants? Somebody literally already did the work for you.

**Comment by msgerbs** [comment]
> 
> 
> regardless of whether this is a good idea or not kneejerk reverts are always closed.

Then maybe we shouldn't merge changes nobody wants without taking into account any of the feedback, doing any polls, or, ya know, listening to the community in any way?

**Comment by MarkSuckerberg** [comment]
> Surely you should be removing them in your downstream instead and not here voting for PRs nobody in this community wants? Somebody literally already did the work for you.

It does actually affect downstreams, positively as it could lead to the development of new features or improvements of existing ones that haven't been removed, and negatively by dropping support for features. Just saying that it should be ignored and changed back by all the downstreams is a lot easier said than done.

**Comment by msgerbs** [comment]
> 
> 
> > Surely you should be removing them in your downstream instead and not here voting for PRs nobody in this community wants? Somebody literally already did the work for you.
> 
> It does actually affect downstreams, positively as it could lead to the development of new features or improvements of existing ones that haven't been removed, and negatively by dropping support for features. Just saying that it should be ignored and changed back by all the downstreams is a lot easier said than done.

Unless of course there's a downstream that wants to use them. Speaking from experience, it's much easier to not use something that's in an upstream than it is to re-add something removed from one.

**Comment by Archanial** [comment]
So just because something was "unbalanced" we will remove it, even though it adds lots of cool mechanics and depth to the game?
Stop trying to balance everything, this is cringe.

**Comment by MarkSuckerberg** [comment]
> Unless of course there's a downstream that wants to use them. Speaking from experience, it's much easier to not use something that's in an upstream than it is to re-add something removed from one.

And that's why I'm saying that there's both a positive and negative side to this. They likely very well may have removed them later on, but this is just speeding up the possibly inevitable. I'm just saying that downstreams should be able to say what they want, regardless of if it's support for or against a feature/removal of a feature.

**Comment by TheFakeElon** [comment]
Time to shill for bee station

**Comment by LittleNyanCat** [comment]
amazing

**Comment by Tharcoonvagh** [comment]
Wasnt there a pr that removed tesla lag

**Comment by optimumtact** [comment]
goof still working on it

**Comment by actioninja** [comment]
Since oranges is in peak oranges mode right now, this was closed because immediate reverts get closed. The PR in question is debatable, but wait a couple of days at least to open reverts.

**Comment by optimumtact** [comment]
Not sure what you mean by peak oranges mode, the engines are free to be readded if and when we have got power into a state where it's meaningful, as per the hackmd

**Comment by JenqaDev** [comment]
goof could add what crita removed and also include his optimizations
peak oranges mode indeed, never seen a PR closing this quickly with so few feedback. you could've given the other PR a few more days otherwise you will always expect us, the angry mob, wanting you to leave :)

**Comment by optimumtact** [comment]
angry mob's gotta be the angry mob, orangeman's gotta be the orangeman

**Comment by JenqaDev** [comment]
then I'll be part of it, down with the orange!

**Comment by JenqaDev** [comment]
i prefer lemonman

**Comment by LemonInTheDark** [comment]
not sure how I feel about that, but so long as you shill my atmos prs I don't really care

**Comment by cacogen** [comment]
at least you tried

**Pull request closed without merging**
