### PR TITLE
Herald nerf 

### PR DESCRIPTION
**Pull request by TTNT789**
## About The Pull Request
halves heralds Armor penetration because he can take out most miners in one spell of shotgun
## Why It's Good For The Game
makes an encounter with herald slightly more survivable
## Changelog
changes heralds death bolt armor piercing to 25 instead of 50
:cl:
heralds death bolt armor piercing to 25 instead of 50
/:cl:

### CODE REVIEW

**Comment by optimumtact** [comment]
Heh

**Comment by optimumtact** [comment]
Hello to monkeystation users.

**Comment by JohnFulpWillard** [comment]
🎃

**Comment by dwasint** [comment]
now this, this is a pr i can get behind

**Pull request closed without merging**
