### PR TITLE
Fixes baseturf

### LINKED ISSUE #19954: There is space on lavaland
image

I think this is the construction site

### LINKED ISSUE #24155: Pod Capsule Issue
Using the pod capsule, 5x5 with you in center, when used at the edge of lavaland as such giving enough space but the side of the pod is the further tile you can go will use the capsule, small animation of smoke and red dust (ash storm? dont know) but no pod will be created.

Visual because im bad at explaining.
oooooN
oooooN
ooXooN
oooooN
oooooN

o empty space
X you 
N outside the physical map

### LINKED ISSUE #25018: Detonating the self destruct charges in the syndicate base breached lavaland to space
Lavaland is never supposed to breach to space, just to the volcanic floor

### LINKED ISSUE #25231: Bluespace Shelter Capsules deleting rocks on lavaland create space tiles
See title. I used a bluespace shelter capsule without all the tiles cleared of rocks and the corner pieces have space tiles under them. I'm pretty sure this didn't happen before.

### LINKED ISSUE #25361: RCD tiles turn Lavaland tiles into space
https://github.com/tgstation/tgstation/commit/37a325d8971f75136aae2c7f87c74b94ff12d9c9
Playing as an Ash Walker, picked up the RCD to remove a wall. Misclicked a few extra times. Suddenly, space. Fortunately, as ashwalker, suddenly venting what little air existed in the lair to space didn't affect much. Still seems like an oversight?

### PR DESCRIPTION
**Pull request by AnturK**
What is says on the tin. Was just removed by mistake in vg lighting. No idea why it was in the lighting part of ChangeTurf really.

Fixes #25361 
Fixes #25231 
Fixes #25018
Fixes #19954 
Fixes #24155

### CODE REVIEW

**Comment by Cyberboss** [comment]
Fixes 
#25361 
#25231
#25018
PROBABLY #25145

**Comment by KorPhaeron** [comment]
https://github.com/tgstation/tgstation/issues/19954

https://github.com/tgstation/tgstation/issues/24155

https://github.com/tgstation/tgstation/issues/25018

https://github.com/tgstation/tgstation/issues/25231

https://github.com/tgstation/tgstation/issues/25361

**Comment by AnturK** [comment]
Too many issues aah

**Comment by XDTM** [comment]
we're gonna be out of the freeze by tomorrow if we go like this

**Comment by KorPhaeron** [comment]
antur is a hero

**Comment by Cyberboss** [comment]
#24826 and #25145 need to be tested against this

**Comment by PJB3005** [comment]
Welp.

**Pull request merged**
