### PR TITLE
Horizontalizes The Coffin Sprite

### PR DESCRIPTION
**Pull request by ghost**
OCEAN MAN
dreamseeker_2018

:cl:
imageadd: The coffin sprite is horizontal again
/:cl:

[why]: I did this because some people complained that the direction of the new sprite is radically different, I don't mind the vertical one myself

### CODE REVIEW

**Comment by Spaceinaba** [comment]
the lack of proper 3/4ths present here makes me physically nauseated

**Comment by Cyberboss** [comment]
This definitely needs work to 3/4 it

**Comment by praisenarsie** [comment]
all he did was rotate it

**Comment by Spaceinaba** [comment]
I know that's why it sucks mcdonalds straws

**Comment by nicbn** [comment]
L O L

**Comment by nicbn** [comment]
Dudes you realise we already had a horizontal, 3:4 coffin before the goon sprite got in right?

**Comment by epochayur** [comment]
this looks hilariously bad

**Comment by DaxDupont** [comment]
the spessmen don't even fit like in the old coffins

**Comment by WJohn** [comment]
No. This is not how you rotate a 3/4th sprite to  be on its side.

**Pull request closed without merging**
