### PR TITLE
[READY]Bubblegum Buffs

### PR DESCRIPTION
**Pull request by Whoneedspacee**
:cl: Joe Berry
add: Reverts back to the bubblegum before [#38306](https://github.com/tgstation/tgstation/pull/38306), was an unfinished pr and generally this bubblegum has more stuff to work with.

add: Enrage mode, while in this mode bubblegum is colored a deep red, moves faster, doesn't retreat, and is immune to projectiles. All while throwing out ground slam attacks around him that throw people around.

add: Clones, basically fake bubblegums that do one attack and disappear afterwards.

add: Ground slam attack, only happens when bubblegum is enraged, throws enemies around. Beware being thrown into a wall or you might be stunned because this is how throws work in this game.

add: Bubblegum can now continue to charge through enemies without stopping.

del: Bubblegum's anger modifier no longer determines his movement speed, instead having a constant speed and changing on enragement.

tweak: Blood spray is now a directional move and can move diagonally towards its target

tweak: Bubblegums charge no longer uses throws to calculate being hit.

balance: Bubblegum now retreats in his standard phase while not using moves, generally he was hard to get hit by in this phase anyways so this is a much smarter play on his part.

balance: Blood spray can now move through walls and goes further, this was pretty easily cheesed because it couldn't move through walls with just hugging the edges of walls and just made him too hard to balance.

balance: Bubblegum now procs melee checks much more often, though he has the same cooldown for his melee attacks. This means you're much less likely to stand next to him and not get hit.

balance: Bubblegum now charges 2 tiles past you, makes it slightly more difficult to predict where he's going to go and makes it so he can catch up to you easier.

balance: Bubblegum now moves faster during his charge.

balance: Bubblegum now only takes 50 damage from explosions, taking many bombs to kill him instead of just 10.
/:cl:

[why]: # Because bubblegum is, to be fair, a boring boss at the moment. He also has some of the best, and even borderline overpowered loot. Another thing to consider is that lore-wise he's meant to be the king of the slaughter demons and only one of them is allowed to spawn per round. For all of these things he should really just be stronger and more of a challenge to take down.

Current version video : (Note that this is using a move speed of 1.5 as will be the standard in the near future) - [Bubblegum v6](https://youtu.be/uXtZ3Un2hV4?t=43)

### CODE REVIEW

**Comment by Shadowflame909** [comment]
>All of a sudden 4 bubblegum clones sprout out of the ground and charge at you.

As long as blood contract and bottle of mayhem stay in as items. This is a good change.

**Comment by carshalash** [comment]
>Current version video : (Note that this is using a move speed of 1.5 as will be the standard in the near future) - Bubblegum v5

I hate the change that's going to happen but I appreciate you putting the foresight into testing it with this speed, good work.

**Comment by ATH1909** [comment]
Should any of these changes to Bubblegum have any effect on those Bubblegum-related hallucinations that you can sometimes get while hallucinating?

**Comment by Whoneedspacee** [comment]
> So wait do pkas not damage him when enraged? That seems a bit needless does it not?
> 
> Good changes though.

They don't but generally you aren't able to hit him with a PKA anyways without range upgrades during this form anyways. Also it's good against guns and just makes a melee boss more intimidating which is why I added it.

> Should any of these changes to Bubblegum have any effect on those Bubblegum-related hallucinations that you can sometimes get while hallucinating?

It shouldn't, the bubblegum clones are completely different things.

**Comment by 4dplanner** [comment]
Why does bubblegum walk away after downing you at 1:23?

**Comment by 4dplanner** [comment]
And again at 2:17, seems to walk away after hitting you

**Comment by 4dplanner** [comment]
And again at 2:35 - is this deliberate?

**Comment by 4dplanner** [comment]
I'm guessing this is due to the 

>balance: Bubblegum now retreats in his standard phase while not using moves, generally he was hard to get hit by in this phase anyways so this is a much smarter play on his part.

But it seems not much smarter if he is actually in the middle of beating the shit out of you

**Comment by Whoneedspacee** [comment]
> I'm guessing this is due to the
> 
> > balance: Bubblegum now retreats in his standard phase while not using moves, generally he was hard to get hit by in this phase anyways so this is a much smarter play on his part.
> 
> But it seems not much smarter if he is actually in the middle of beating the shit out of you

His throw I didn't want to stun you anyways so this is fine. Throws work just by when you hit a dense object though so :man_shrugging:, also lore-wise we can just say bubblegum can't see, fuck it.

**Comment by Steelpoint** [comment]
I'm disappointed because I love wearing the HECK Suit, but I also agree that Bubblegum needed a buff, poor lad was not doing so well nowadays.

**Comment by Whoneedspacee** [comment]
Hold off on merging this for now, I've had another spurt of creativity :man_shrugging:

**Comment by Whoneedspacee** [comment]
https://youtu.be/uXtZ3Un2hV4?t=43

Always appreciate feedback.

**Comment by HydroFloric** [comment]
So is the attack that throws you gone now? Didn't see it happen during the video. Besides that maybe make the distance between the halucinations during that barrage attack a tile or two farther away since it looks like you were trapped at 3:13. Of course it might just be the perspective.

**Comment by Whoneedspacee** [comment]
@HydroFloric working as intended.

**Comment by Whoneedspacee** [comment]
Good enough, couldn’t get a new attack concept to be not shit so I’m done with this.

**Comment by miniusAreas** [comment]
Looks nice. People downstream will take it if this isnt merged upstream.

**Comment by adamkad1** [comment]
Gotta love them mining souls 13, bubblegum decoys so much you can barely hit him

**Comment by Whoneedspacee** [comment]
@adamkad1 you have pee pee breff

**Pull request merged**
