### PR TITLE
Adds security roles to the HUMAN_AUTHORITY list

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
Meaning lizards can not be security positions if the option is enabled.

### CODE REVIEW

**Comment by Shapsy** [comment]
:-1: I'd rather have liggers die in the line of duty than waste human lives

**Comment by Incoming5643** [comment]
it's hard enough to get people to play security

**Comment by xxalpha** [comment]
Might as well remove lizard.

**Comment by KorPhaeron** [comment]
>Might as well remove lizard.

I wish

**Comment by Zilenan91** [comment]
:-1:

**Comment by WJohn** [comment]
I'm personally okay with this, since it's a config option that won't affect here. Besides, MSO is physically capable of removing basically any chunk of code he wants and can run an entirely separate version of the game on his own already. If he wants to remove lizards we'd have seen them removed by now.

**Comment by GunHog** [comment]
Security is an extremely unpopular and stressful job. Excellent solution to that problem! Restrict more players from it!!

**Comment by KorPhaeron** [comment]
It'd be less stressful without lizard coworkers

**Comment by GunHog** [comment]
That is a ridiculous statement, how could you possibly justify that?

**Comment by KorPhaeron** [comment]
Their hissing grates on the ears

**Comment by Dorsisdwarf** [comment]
:+1: 

Now I don't have to get into extreme pissing fights with security every time a greyshirt realises the person arresting them is nonhuman.

**Comment by bustygoku** [comment]
:+1: 

ss 2015-10-08 at 01 15 32

**Comment by Supermichael777** [comment]
has this ever been a problem?
Borgs are really easy to flash as an officer.  If a Borg keeps giving you problems ask hos/cap to robocop their asses.
lizard is a willful disadvantage stop hate coding away the fun.

**Comment by Steelpoint** [comment]
While I dislike Lizard people in a OOC fashion, and hence would usually support this, but I really don't want to turn away people who would play security just because they are a Lizard.

I can support keeping command staff positions Human only due to it being thematic but also to prevent Silcion conflicts (Rev would be obnoxious against a non-human command staff).

If your a Lizard player and you go into Security as one, you should be fully prepared to be at a slight disadvantage when it come's to Silicon's and Human prisoners.

**Comment by Dorsisdwarf** [comment]
The problem is that lizard officers aren't at any sort of disadvantage, because :s halp borgs rogue and the IRON FISTS OF THE LAW blow the borgs, reset the AI, then kill it for good measure

**Comment by Miauw62** [comment]
Make this a separate config option that starts off. We already have a lack of sec players.

**Comment by CosmicScientist** [comment]
What Miauw said. It's worse to lump things together.

**Pull request closed without merging**
