### PR TITLE
Removes a bunch of unusued code, sprites, and sounds

### PR DESCRIPTION
**Pull request by ghost**
A list of stuff removed can be found below.
- The liberation station vending machine: I haven't ever seen this used.
- The chronosuit: I only saw this used once - then it wasn't even used as an admin gimmick.
- Sounds:
  - AI sounds such as `animes.ogg`: These are not used anymore.
  - "Compiler", "desecration", and "splort" sounds: I'm not sure why these existed in the first place. They appear to have never seen use.
  - `bloblarm.ogg`: This isn't used anywhere.
  - `Heart Beat.ogg`: This isn't used anywhere.
  - `-adminhelp.ogg`: This isn't used anywhere and is only played by bored admins who are then embarrassed because they didn't know what the sound was.

### CODE REVIEW

**Comment by KorPhaeron** [comment]
I've definitely seen all that code used, and animes is used as well. Not sure about the other sounds.

In any case I'm not sure why any of it needs to be removed. It's used rarely, but it isn't hurting anyone by existing.

**Comment by Incoming5643** [comment]
Barely used doesn't mean unused, I thought this pull was a bunch of unused iconstates and unreferenced sounds.

**Comment by TechnoAlchemisto** [comment]
animes ogg is used, chronosuit is used, liberation station vending machine is used

**Comment by Xhuis** [comment]
Well, it pains me, but if all if this stuff is used once per millennium, it's still used, so I'll let them stay.

**Pull request closed without merging**
