### PR TITLE
Show-server-revision tells if test pr is merged

### PR DESCRIPTION
**Pull request by Jordie0608**
Using show-server-revision while there is a PR currently test merged will now show a link to the PR and which the latest upstream commit which it was merged onto. Obviously only works when the tgstation-server tools are enabled and won't be checked otherwise.

:cl:
rscadd: Show Server Revision will now tell you if a PR is test merged currently.
/:cl:

### CODE REVIEW

**Comment by Iamgoofball** [comment]
We have support for multiple test merges at once, make sure that this has compatibility

**Comment by Jordie0608** [comment]
We do? @MrStonedOne

**Comment by MrStonedOne** [comment]
ya, the support is a bit hacky, but you can chain them now.

I'll make it append to that file when you chain them, you would just have to parse it as lines.

**Comment by Jordie0608** [comment]
This wasn't finished but ok

**Comment by duncathan** [comment]
If only there were some method of informing the people that a pr isn't ready

**Comment by duncathan** [comment]
;)

**Comment by Jordie0608** [comment]
I feel it should've been clear from MSO's comment and the lack of a commit after it

**Pull request merged**
