### PR TITLE
Adds some more weapon and armour sprites

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
Rather just commit them on their own instead of dealing with merge conflicts if the PR runs into BALANCE arguments.

This includes

Inquisitor Hardsuit

A glowing sword, with on/off sprites and inhands

A glowing hammer, with on/off sprites and inhands

A chainsaw sword, with on/off sprites and inhands

All of them were sprited by Ausops.

### CODE REVIEW

**Comment by PKPenguin321** [comment]
Clever

**Comment by WJohn** [comment]
Very nice looking.

If you need more artifact sprites for lavaland, there should be some available here:
http://www.mediafire.com/download/90q0n055cz691wy/VOLCANO_LAND_1.1.3b.rar

**Comment by GunHog** [comment]
I am lazy to download each .dmi to look at new sprites. Post pictures of each item, please.

**Comment by Fox-McCloud** [comment]
pics?

**Comment by Cheridan** [comment]
>sprite pr with no pics

**Pull request merged**
