### PR TITLE
Funds are no longer safu

### PR DESCRIPTION
**Pull request by wesoda25**
## About The Pull Request

fixes an undocumented (afaik) spelling error on crab phone

## Changelog
:cl:
fix: Funds are no longer safu
/:cl:

### CODE REVIEW

**Comment by actioninja** [comment]
funds are in fact safu

**Comment by wesoda25** [comment]
what the FUCK

**Comment by wesoda25** [comment]
wait wtf does antag freeze include fixes? or was it just closed cause my shit name?

**Comment by CRITAWAKETS** [comment]
Antag freeze should not affect any fixes.

**Comment by JJRcop** [comment]
Funds safu confirmed
https://github.com/tgstation/tgstation/pull/43338/files#r272571332

**Comment by wesoda25** [comment]
Wow ive never seen a random meme video used to justify an immersion breaking spelling error before, tg code gets more interesting by the day!

**Comment by wesoda25** [comment]
(reopen this)

**Comment by actioninja** [comment]
no

**Comment by wesoda25** [comment]
Why? You realize most players have no idea its a reference and interpret it as a bug?

**Comment by JMoldy** [comment]
It doesn't make any much more sense than the original CRAB-17 reference, if you're going to keep that then why not one of the other videos?

**Comment by Tharcoonvagh** [comment]
Dump it

**Pull request closed without merging**
