### PR TITLE
Improves the uplink poison kit

### PR DESCRIPTION
**Pull request by 81Denton**
:cl: Denton
balance: Tiger Cooperative specialists have made the poison kit even deadlier! Fentanyl, Formaldehyde and Histamine have been replaced with Neurotoxin, Entropic Polypnium and Krokodil.
/:cl:

Two of the poison kit chemicals are both easily mixed and mediocre at best (fentanyl/formaldehyde). The third one (histamine) will only really affect someone if you manage to get the whole bottle into their system at once.
I replaced those three with neurotoxin, entropic polypnium and krokodil.

Not that it matters terribly much if you can use initropidril and coniine anyway.

### CODE REVIEW

**Comment by Ordonis** [comment]
Ketrazine would be another candidate for a medicine/drug toxin

**Comment by PKPenguin321** [comment]
Doesn't this make histamine unobtainable

**Comment by DaedalusGame** [comment]
itching powder decays into it

**Comment by Xhuis** [comment]
`81Denton:ExcessiveUseOfCobblestone-commented-3-minutes-ago-No-one-reads-branch-names!`
I do. 😏

**Comment by DaedalusGame** [comment]
gotteem

**Comment by YakumoChen** [comment]
Isn't it deadly enough? All you have to do is mix every chem into a beaker for a instant kill death mix

**Comment by 81Denton** [comment]
You can already make comparable deathmixes with access to botany or a minute at a chem dispenser. Makes the poison kit kind of pointless, really.

**Comment by evsey9** [comment]
why neurotoxin? it's the easiest toxin to make to be honest

**Comment by 81Denton** [comment]
It has very good utility with its knockdown. Mute toxin would also be good, but I feel that it might be too close to the bioterror syringe kit or sleepypen.

**Comment by Robustin** [comment]
Not every poison in the kit needs to be a fucking all-star poison, its already one of the best syndie items why buff it more?

**Comment by 81Denton** [comment]
>why buff it more?

Why keep useless items in an uplink kit?

**Comment by Robustin** [comment]
They arent useless they just aren't uber-lethal.

Their existence is one of the only things holding back the "mix the entire poison kit together, stick it in a syringe and 1-shot everyone" meme.

**Comment by 81Denton** [comment]
>stick it in a syringe and 1-shot everyone

You can already do that with a syringe that has only about 5u of initropidril, coniine or curare. Or just walk over to chemistry, mix some lexorin/blackpowder+phlog and oneshot kill people without any TC investment.
Not to mention botany.

**Comment by ExcessiveUseOfCobblestone** [comment]
“it has other bad chems” is an odd argument when you consider that they’re in limited supply and your addition increases this supply.

**Comment by optimumtact** [comment]
Is there any argument for this actually needing a buff?

**Comment by 81Denton** [comment]
@optimumtact IMO chemistry macros have devalued the poison kit since you can just walk up to a dispenser, click twice and receive a beaker full of deathmix.

Instead of lowering the TC cost I'd rather remove the junk chems from it.

**Comment by GhostEcho** [comment]
Replace a poison or two in the kit with Skewium, Skewium would be such a great meme and make buying the poison kit more useful than just instadeath mixes

**Comment by duncathan** [comment]
i don't think this is necessary

**Comment by davethwave** [comment]
Honestly I think that replacing one of the numerous sleepchems with a vial of mute toxin could be nice.

**Pull request closed without merging**
