### PR TITLE
pirate suit storage unit now has pirate space suits

### PR DESCRIPTION
**Pull request by Fikou**
## About The Pull Request

pirate suit storage unit now has pirate space suits also moves the unit from the pirate file into the suit storage unit file

## Why It's Good For The Game

why do pirates get old eva suit instead of piratesuits why do they get breathing masks they dont even BREATHE
also gives them a buff in the form of jetpack but i think its fine since everyone always arms up for pirates and they are 3 or less against whole crew

## Changelog
:cl:
balance: pirate suit storage units now have the pirate space suits and a jetpack
/:cl:

### CODE REVIEW

**Comment by Dawson1917** [comment]
Don't they spawn wearing the coat and hat that'll be in this locker?

**Comment by Fikou** [comment]
probably
why even have suit units at all what the fuck

**Comment by Dawson1917** [comment]
> 
> 
> probably
> why even have suit units at all what the fuck

They've been running their crew since when they were still alive, that's why the space suits are still there and why the ship is so run down (both sides had large barrels for a weapon but are barricaded off and empty). That's my headcanon at least. The suits are useless outside of possible lore. The jetpacks would be useful if sitting somewhere in the EVA section of the ship. Pirates need some kind of a buff now that it's effectively impossible for them to heal

**Comment by Shadowflame909** [comment]
Pirates don't need space suits tho. I believed the suits were there just to blend in? I guess?

**Comment by ExcessiveUseOfCobblestone** [comment]
> jetpacks

cringe

**Comment by Fikou** [comment]
gay

**Pull request closed without merging**
