### PR TITLE
laughter demons now use the honk demon sprite on april fools

### PR DESCRIPTION
**Pull request by Fikou**
## About The Pull Request

on april fools now laughter demons use the clown demon sprite
its basically a slaughter demon with a clown outfit

## Why It's Good For The Game

fun

## Changelog
:cl:
add: on april fools laughter demons embrace their clown nature to the fullest degree
/:cl:

### CODE REVIEW

**Comment by LordSaladin** [comment]
honk

**Comment by Fikou** [comment]
@ExcessiveUseOfCobblestone why close...

**Comment by ExcessiveUseOfCobblestone** [comment]
click the april fools tag

**Comment by Fikou** [comment]
> click the april fools tag

the colorful tile pr works at any april fool by checking the holiday in the game and got merged
this uses the same system so i dont see why it needs to be a closed testmerge only

**Comment by ExcessiveUseOfCobblestone** [comment]
Sure, this is tame enough.

**Comment by RigglePrime** [comment]
gaming

**Pull request merged**
