### PR TITLE
Makes a crapload of new cardboard boxes craftable.

### PR DESCRIPTION
**Pull request by nemvar**
## About The Pull Request

Closes #44651

It's like that PR. Only slightly better sorted. I mean, it's kinda rude to do... I feel bad now.

Also fixes an inconsistency with large cardboard boxes. You can now only craft one of them on the same tile, like with all other closets.

## Why It's Good For The Game

cardboard
It's a bit more flavourful. Gives cardboard more stuff to do.

## Changelog
:cl: Trilbyspaceclone and nemvar
add: You can now craft more fancy boxes with cardboard.
/:cl:

### CODE REVIEW

**Comment by Tumesuo** [comment]
This seems good to be honest, i've always been a bit dissapointed when I have to use normal boxes to hold shotgun rounds as sec

**Comment by MegaEmpirical** [comment]
Will this make it so you can break a donut box down into cardboard?

**Comment by habader** [comment]
Cardboard walls and floor tiles exclusive to cardboard golems

**Comment by Trilbyspaceclone** [comment]
***Sad cat sounds***
It is better, as well as has the same idea. Even gave credit to the idea. 10/10 ^_^

**Comment by fludd12** [comment]
Can you add monkey cube boxes to the list? They have a nice aesthetic.

**Comment by SpaceManiac** [comment]
@fludd12 they are already on the list

**Review by SpaceManiac — APPROVED** [review]

**Pull request merged**
