### PR TITLE
[ready] Adds discord webhook support to the github webhook processor.

### PR DESCRIPTION
**Pull request by MrsTonedOne**
This allows you to give an array of discord webhook endpoints to announce pr open/close/merge events to.
Github's built in virgin embed:
image

/tg/'s chad embed:
image

### CODE REVIEW

**Review by chesse20 — APPROVED** [review]
the code looks fine to me

**Comment by optimumtact** [comment]
90% wasted space, hate it
```
bot: <authorname> <action> - title
<link no embed>
```

**Comment by MrStonedOne** [comment]
The embed is staying as a tribute to how stupid they are.

I might consider making it controllable per webhook endpoint, so #bots-general can have it but not #coding-general.

**Comment by Cyberboss** [comment]
Something is currently busted, prs aren't getting labelled

**Pull request merged**
