### PR TITLE
Syndicate borg/reinforcement spawners have a Never For This Round option.

### PR DESCRIPTION
**Pull request by harmonyn**
Does not exactly take care of https://github.com/tgstation/tgstation/issues/25254 but at least mitigates it.

Also gives a feedback message so at least players won't spam by accident.

### CODE REVIEW

**Comment by coiax** [comment]
Not even a fix. By the time you click never for this round, you'll have 20 windows open.

**Comment by BeeSting12** [comment]
thanks for the feedback message. one time i spammed it 50 times not realizing it would spam deadchat so bad and got two bwoinks from two different admins... embarrassing.

**Comment by bgobandit** [comment]
@coiax what would you do instead/how

**Comment by XDTM** [comment]
this + a minor cooldown i guess

**Comment by coiax** [comment]
Well just have it unable to send new notifications while it's polling deadchat.

**Comment by lzimann** [comment]
@bgobandit pls

**Comment by coiax** [comment]
Why would you merge this

**Comment by optimumtact** [comment]
it's better than waiting for bandit to do something they're not going to get around to

**Pull request merged**
