### PR TITLE
Hermit roles no longer defensless

### PR DESCRIPTION
**Pull request by Boopideedoo**
## About The Pull Request
This pull request is made to make a ghost role for 2 different 
It adds 3 new items to both roles and takes away one item from the role on lavaland

## Why It's Good For The Game
It makes the hermit role a bit easier on Icemoon and lavaland so you arent defensless
## Changelog

:cl:
add: Added an autolathe
add: Added a golem mining vendor board
add: Added a ore redemption machine board
del:crowbar
/:cl:

### CODE REVIEW

**Comment by dragomagol** [comment]
Your changelog doesn't describe where you've added or deleted these things from the game. 

Also not sure if I'm a big fan of this. The point of the hermit role is ingenuity and improvisation (you can forge your ores on the fire, and make a cooking pit), and this seems like it's making it another golems/drones lite but on your own.

**Comment by Boopideedoo** [comment]
> answer, they're lazy, which is why they want to upgrade the ghost role with extra stuff in the first place.

Its not laziness its more towards getting weapons to fight mobs, and I found the crafting system so I think I can easily add a few things that should be craftable instead of even needing an autolathe. sorry I didnt reply I was asleep

**Comment by CursedBirb** [comment]
Since i do not know your discord and do not know how to make a pull request on your code im just sending you code for 5 cable coil recipe and fuel_pond variation of water_source with infinite welding fuel

code/game/objects/structures/watercloset.dm
https://pastebin.com/C2LEi72v

code/datum/components/crafting/recipes.dm
https://pastebin.com/YdG0jeZ9

**Comment by weesnaw-ops** [comment]
if u want golem gear play golem. like. what? why

**Comment by san7890** [comment]
I don't particularly see why the hermit needs such a skewed balance change, and the negative concerns are mounting in relation to this PR (which I find myself agreeing with). Can you justify your changes in another way, or try rebalancing it in another matter that isn't just adding more machinery? I just properly do not see _why_ this should be merged beyond "being defenseless".

**Comment by Boopideedoo** [comment]
> if u want golem gear play golem. like. what? why

Golem was removed due to griefers sadly

**Comment by weesnaw-ops** [comment]
oh damn :(

**Comment by Mothblocks** [comment]
Neither maintainers nor players seem to be interested in this PR

**Pull request closed without merging**
