### PR TITLE
Allows you to launch pods before round end on Boxstation

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
Adds escape pod computers to each pod and destinations (which randomize to somewhere in the asteroid roundstart). The pod computer can only be used during Red or Delta alert, or if you emag it.

If a pod has been launched early, it won't go to centcomm at round end.

Each pod also has a safe with 2 sets of (very slow) space suits and pickaxes. The safe can only be opened during Red or Delta alert.

EDIT: I could also make some of the pods go to the derelict instead if people think that would be interesting. Asteroid is kind of a dull location but there is no lavaworld for them to launch to right now.

pod

### CODE REVIEW

**Comment by Zilenan91** [comment]
Pictures?

**Comment by KorPhaeron** [comment]
What do you need pictures of its a pod on station and then its a pod in the asteroid

**Comment by Zilenan91** [comment]
Where would you put the safe and consoles for these things on the tiny-ass pods we have now. I need to see what it looks like.

**Comment by Anonus** [comment]
What's the process to add these to a map? Anything special?

**Comment by KorPhaeron** [comment]
@Anonus 

The asteroid port automatically randomizes itself roundstart, so just place 4 of them anywhere on your map (I did it in front of each pod) and set all the shuttle computer IDs/port IDs correctly

**Comment by Zilenan91** [comment]
Hang on, since those are wall safes, can't you just multitool them to reset the passwords.

**Comment by KorPhaeron** [comment]
@Zilenan91 

Read the OP

**Comment by newfren** [comment]
It says the safe can be only opened during red or delta alert, but does that mean it's possible for it to happen outside to delta/red alert by hacking, or that anyone can open it during delta/red alert and not at all outside that, or that there's some id lock/preset code/whatever that allows you access during red/delta alert that anyone with a mutlitool can hack their way past only during the alert?

**Comment by kevinz000** [comment]
Spelling/grammer: "This safe will only unlock during a RED OF DELTA ALERT"

**Comment by KorPhaeron** [comment]
@kevinz000 

Thanks

@newfren 

Fixed

**Comment by KorPhaeron** [comment]
@WJohn

Are you allowed to merge this since its a map thing/remie already reviewed the pod code months ago?

**Comment by Razharas** [comment]
>KorPhaeron> @Razharas merge https://github.com/tgstation/-tg-station/pull/13186 remie already reviewed it months ago I just finally put it on the map

**Pull request merged**
