### PR TITLE
Frog fixes and updates

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
Frogs wont cause themselves to scream anymore. They also don't scream as loud.

The rare frog can actually spawn, and is now purple (it's just hue shifted, there is not really a new sprite).

Added a butcher result.

### CODE REVIEW

**Comment by PKPenguin321** [comment]
Tendies yes

**Comment by FantasticFwoosh** [comment]
Having some frogs legs for the chef would have been more amusing a butcher result.

**Comment by kevinz000** [comment]
@KorPhaeron please explain how a frog can smash apart an airlock.

**Comment by Cheridan** [comment]
@kevinz000 froggos have very strong legs

**Comment by ChangelingRain** [comment]
>oranges keeps merging DNM prs

**Comment by Anonmare** [comment]
Gimme gimme a chicken tendies PR soon

**Comment by Niknakflak** [comment]
we have chicken tendies already anonmare gosh

**Comment by KorPhaeron** [comment]
@kevinz000 

Apparently simple animals (and maybe anyone with a weapon?) can smash down airlocks now with the changes @phil235 did for destructible objects.

**Comment by ShadowDeath6** [comment]
have giving a frog tenies have a chance of making it a rare frog

**Pull request merged**
