### PR TITLE
The station explosion cinematic now uses the old "far explosion" sound

### PR DESCRIPTION
**Pull request by ghost**
:cl: Xhuis
soundadd: The station's explosion now uses a new (or old) sound.
/:cl:

The current "far explosion" sound effect just never really seemed to fit to me, and I liked the old one a lot more in the nuke's context; it had a lot more impact behind it for the distance that was conveyed (very far from the station.) The explosion cinematic now uses the very old explosion sound.

[Here's what it sounds like, for anyone new or who needs a refresher.](https://www.dropbox.com/s/uh6siu4rn0ytzz3/explosion_distant.wav?dl=0)

### CODE REVIEW

**Comment by calzilla1** [comment]
Neat

**Comment by GunHog** [comment]
I always preferred this one as well.

**Comment by ShizCalev** [comment]
but there's no sound in space

**Comment by GunHog** [comment]
> but there's no sound in space

It is computer simulated! Seeing a silent boom is not as interesting in comparison.

**Comment by NewSta1** [comment]
It makes total sense, though.

**Comment by optimumtact** [comment]
name it farfarboom.ogg

**Review by Cyberboss — CHANGES_REQUESTED** [review]
You need to mute the actual explosion() that happens

**Comment by nicbn** [comment]
Name it slender.ogg

**Comment by Xhuis** [comment]
Looks like it's already silent.
`explosion(epi, 0, 256, 512, 0, TRUE, TRUE, 0, TRUE)`
`/proc/explosion(atom/epicenter, devastation_range, heavy_impact_range, light_impact_range, flash_range, adminlog = TRUE, ignorecap = FALSE, flame_range = 0 , silent = FALSE, smoke = FALSE)`

**Review by Cyberboss — APPROVED** [review]

**Pull request merged**
