### PR TITLE
Tweaked Sandbox Panel 

### PR DESCRIPTION
**Pull request by Chessus**
## About The Pull Request

As the sandbox spawning shuts off/doesn't work for some people I made a couple of important items available to the Sandbox panel such as CentCom tech disk, adminordrazine pill and box of materials (50 of each material in the box). 
I removed the welding tank to stop welder-bomb griefing but added the experimental welding tool

## Why It's Good For The Game
See about section

## Changelog
:cl:
tweak: tweaked Sandbox Panel
/:cl:

### CODE REVIEW

**Comment by Shadowflame909** [comment]
Good PR. I hope some mad lad figures out how to keep spawning for all though.

**Comment by Chessus** [comment]
I'll have a closer look over xmas and new years and tweak it a bit. I'm sure that admin check thingy can go also, I think it was made at a time when people were griefing with it plasma/n2o tanks. Admins still have that ability to spawn the canisters in through the game panel so seems unnecessary for now.

**Comment by Timonkeyn** [comment]
I wanna spawn shit but sandbox said no

**Comment by PKPenguin321** [comment]
Would be nifty to make the sandbox spawner use the game-panel spawner

**Comment by Chessus** [comment]
Yeah,would be easier although you'd have to black list items like the fusion cannister to avoid griefing. Or not, I think it's up to the maintainers whether they'd want that sort of power to non-admins.

**Comment by Chessus** [comment]
https://github.com/tgstation/tgstation/pull/48262#issuecomment-566254046

Yeah that's an issue that's been around for ages. 
https://github.com/tgstation/tgstation/issues/38836
https://github.com/tgstation/tgstation/issues/32807

**Review by Cyberboss — APPROVED** [review]

**Pull request merged**
