### PR TITLE
Allows energy-based guns to serve as lighters (Winter Thaw 2017)

### PR DESCRIPTION
**Pull request by ghost**
_This feature was created as part of the [Winter Thaw of 2017](https://tgstation13.org/phpBB/viewtopic.php?f=10&t=9307) regardless of consensus or if it gets merged._

:cl: Xhuis
add: Energy-based weapons can now light cigarettes.
/:cl:

As requested by BeeSting12.

### CODE REVIEW

**Comment by coiax** [comment]
What about wands and staves? Should a wand of fireball light the cigarette

**Comment by Xhuis** [comment]
No, that would blow your head off. I could easily code an interaction for it, though.

**Comment by Cyberboss** [comment]
More sec buffs

**Comment by Xhuis** [comment]
You know it

**Comment by improvedname** [comment]
Make it also light plasma if it can light cigs it also should light plaama

**Comment by Xhuis** [comment]
Maybe, but that's not for this PR.

**Comment by AdamElTablawy** [comment]
if you suicide with an egun, it should also light the cigarette

**Comment by Xhuis** [comment]
This is ready

**Comment by Tacolizard** [comment]
didn't goof already do this

**Comment by Xhuis** [comment]
Hell if I know

**Pull request merged**
