### PR TITLE
Add grind reagents for lavaland fauna

### PR DESCRIPTION
**Pull request by timothymtorres**
## About The Pull Request
This gives some chemical reagents when grinding lavaland fauna drops:
- Bileworm hide - 5u Nitric acid
- Brimdust sac - 5u Gunpowder
- Regenerative core - 5u Omnizine
- Rush gland - 5u Muscle stimulants

## Why It's Good For The Game
More ways to interact with chemistry.

## Changelog
:cl:
add: Add grind reagents for lavaland fauna drops. Bileworm hide gives nitric acid, brimdust sac gives gunpowder, regenerative core gives omnizine, and rush glands give muscle stimulants.
/:cl:

### CODE REVIEW

**Comment by Loafin34** [comment]
>mfw ash walker creates bombs from several thousand brimdemons
>mfw revert pr 2 seconds later

**Comment by timothymtorres** [comment]
> why would the sacs of brimdust grind into gunpowder and not brimdust

I wasn't aware it was a reagent until now, however Brimdemons already drop brimdust on the floor.  My goal with this PR is to make the reagents related to the organ effects:

- Regenerative core heals so omnizine
- Rush gland has speed effects so muscle stims
- Brimdust sac cause explosions so gunpowder

It's even in the description - `"A strange organ from a brimdemon. You can shake it out to coat yourself in explosive powder."`

**Comment by Jacquerel** [comment]
> It's even in the description - `"A strange organ from a brimdemon. You can shake it out to coat yourself in explosive powder."`

To be fair it does also identify the "explosive powder" in the name of the organ as "brimdust"

**Comment by SuperNovaa41** [comment]
Fix your consistency issues

**Comment by timothymtorres** [comment]
Brimdemons already drop 15u brimdust. No point in this PR then.

**Pull request closed without merging**
