### PR TITLE
Cobbduceus: TW Changes (Missing HP Bonus/ Less Base Healing/ Less Penalty for Clothes)

### PR DESCRIPTION
**Pull request by ExcessiveUseOfCobblestone**
Too many numbers so now we will just be using Cobbduceus to denote medical stuff.

## About The Pull Request

- TW now scales with missing HP and can easily be set within the appropriate surgery step
- TW upgrades now have less base healing but scale better
- TW's Clothes adjustment has went from 40 to 55

## Why It's Good For The Game

Basically this increases the healing thoroughput of TW via humans and makes it desirable.

Agreed upon here
https://tgstation13.org/phpBB/viewtopic.php?f=10&t=23712&p=514620#p514591

## Changelog
:cl:
add: Tend Wounds now scales with missing health!
tweak: All Tend Wound Upgrades (bar Alien Tech Combo Surgery) do same base healing but scale with missing health differently. They should all heal more than they usually do in most cases though.
tweak: The penalty for keeping clothes on has gone down 15%
code: Medibots were NOT changed and will continue to NOT scale with missing HP to make humans more desired.
/:cl:

### CODE REVIEW

**Comment by FloranOtten** [comment]
>TW's Clothes penalty has went from 40 to 55
>40 to 55

>tweak: The penalty for keeping clothes on has gone down 15%
>down 15%

**Comment by ExcessiveUseOfCobblestone** [comment]
the penalty DID go down, the healing went up.

**Comment by Difrit** [comment]
"I want people to use surgery so I nerfed chemicals and buffed surgery, but forgot nobody trusts anyone enough to let them perform surgery while alive so this has been a net loss"

**Comment by ExcessiveUseOfCobblestone** [comment]
but kill and clone is okay 🤔

**Pull request merged**
