### PR TITLE
replaces REVIRT GON CHEM with a more topical reference

### PR DESCRIPTION
**Pull request by carlarctg**
## About The Pull Request

image

## Why It's Good For The Game
game improvement

## Changelog
:cl:
add: Nanotrasen psychologists have noticed a minor fluctation in the inexplicable hate of chemicals some psych ward patients hold.
/:cl:

### CODE REVIEW

**Comment by evsey9** [comment]
tyrannical orange man denies the people of their wishes once again

**Comment by optimumtact** [comment]
The brain damage lines are way too meta already, it was a mistake (as the author of most of them)

**Comment by cacogen** [comment]
most of them predate /tg/station and are goon references

svn revision 2, 24 Aug 2010
https://github.com/tgstation/tgstation/blob/662c08272acd7be79531550919f56f846726eabb/code/modules/mob/living/carbon/human/life.dm#L132-L140

**Comment by optimumtact** [comment]
you know there's like 68 now right?

**Comment by PKPenguin321** [comment]
some deep lore for you
image

**Pull request closed without merging**
