### PR TITLE
Adds cryopod areas to every map.

### PR DESCRIPTION
**Pull request by sergeirocks100**
## About The Pull Request

This, well, adds cryopod areas to every map.

Meta:
Screenshot_336

Ice Box:
Screenshot_337

Delta:
Screenshot_338

Kilo:
Screenshot_339

Tram:
Screenshot_340

Credits:

Skyrat: The areas themselves.

Me: For copying them over, and slightly modifying a few of them because the /tg/ cryogenics oversight consoles only support one direction.

## Why It's Good For The Game

Cryopods don't do much good if they aren't on any of the maps.

## Changelog
:cl:
add: Adds cryopod areas to every in-rotation map. Expect to find them in dorms or recreation areas.
/:cl:

### CODE REVIEW

**Comment by Fikou** [comment]
image
balance pr, removes the meta water cooler

**Comment by jlsnow301** [comment]
> Ice Box:
Looks like you left the camera on the door

other requests: 
- reinforced walls for the cryo consoles. these should NOT get destroyed and any measure you can to protect them is good
- maybe some floor tile variation or decals?
- (if you haven't already) ensure the cryo consoles are actually on the floor tile and moved up, not on the wall itself

**Comment by Farquaar** [comment]
> 
> 
>     * reinforced walls for the cryo consoles. these should NOT get destroyed

Why?

**Comment by jlsnow301** [comment]
> Why?

Without a console the cryopod has no place to store items, code wise this starts messaging admins if it's missing

**Comment by KathrinBailey** [comment]
Please change the dirs of the pods so they don't look so jankily placed.
image
They should either be facing each other like this, or the back of the pods should be touching the walls.
Same deal on all of the maps.
They shouldn't be like this.
image
It just looks janky.

**Comment by itseasytosee** [comment]
We become a little more like paradise every day.

**Comment by interestingusernam3** [comment]
why

**Comment by Zytolg** [comment]
Personally, I'd like to see a little bit more added to these rooms to represent their function better. Currently they come across as "Cryo Closets", and I don't feel that it's necessarily a good look for our stations.
Matching the intention of the Cryo Pods, each room should ideally provide closets, motivational posters, and perhaps some privacy separators, the more to help our spacemen ease into their newfound sleep. It'd be better if the Cryosleep rooms were somewhere adjacent to the Locker Room, but given the current layout of most stations, I don't see how that can be done without reworking a majority of the dorms area, so I'll not request that here.

**Comment by EOBGames** [comment]
@sergeirocks100 are there atmos vents/scrubbers in the meta and delta rooms? I can't see anything based on the map diff images.

**Comment by sergeirocks100** [comment]
No.

**Comment by sergeirocks100** [comment]
@EOBGames

**Review by EOBGames — CHANGES_REQUESTED** [review]
In that case, could you please add atmos to the rooms that are missing them? Vents at the very least, although I'd prefer both vents and scrubbers.

**Comment by JJRcop** [comment]
@itseasytosee Is this a joke? You can just not map them

**Comment by LemonInTheDark** [comment]
> 
> 
> Can we make this a config?

lmao what

**Pull request merged**
