### PR TITLE
Elite Syndicate Hardsuit

### PR DESCRIPTION
**Pull request by ghost**
Elite Syndicate Hardsuit added.
Fireproof, with melee = 60, bullet = 60, laser = 50, energy = 25, bomb = 55, bio = 100, rad = 70 
resistances (20 more than a normal operative hardsuit, but just +10 in energy and bullet.).
10TC, Operatives only.
Operatives can now use throwing stars and Syndicate playing cards.

:cl:
rscadd: Nuclear operatives can now buy the Elite Syndicate Hardsuit for 8 TC that has better armor and fireproofing.
tweak: Added throwing stars and Syndicate playing cards to nuclear operative's uplink.
/:cl:

### CODE REVIEW

**Comment by WJohn** [comment]
So uh, maybe some custom sprites?

**Comment by TheNightingale** [comment]
The extent of my spriting knowledge ends at recolouring Pokémon. If anyone wants to make some, please do.

**Comment by RemieRichards** [comment]
Take one of the syndi rig sprites that were used on NT

**Comment by Niknakflak** [comment]
Arent throwing stars supposed to ninja snowflake only.  And what is the purpose of this change

**Comment by Niknakflak** [comment]
Oh wait no, syndicates can buy stars anyway, second point stands though

**Comment by TheNightingale** [comment]
I'm not too sure how to put the sprites on the thing, but the purpose is because Ops have flamethrowers and dragonsbreath rounds available - but using them burns them to death more often than not. It's just a slightly snazzier suit (and Ops get playing cards and throwing stars because there's no reason they shouldn't).

**Comment by Supermichael777** [comment]
inb4 140 decks of cards wins an ops round

**Comment by Lumipharon** [comment]
Flamethrower is pretty robust now, but not sure I would spend 10tc just to get a better suit.

**Comment by Zilenan91** [comment]
I'd spend that much on a better suit, these armor values are fucking whack.

Also allows some pretty rad crowd control options with the Ops all buying these and flamethrowers, then going on a purging spree. Would also be nice if this pr added some plasma tanks to their ship for flamethrower fuel, unless there are some already.

**Comment by Xhuis** [comment]
Proper back-mounted flamethrowers with ridiculous amounts of ammo and a firelock opener would be amazing for a PURIFYING FLAME operative team.

**Comment by Lumipharon** [comment]
Back mounted flamethrower akin to the janitor/atmos backpack sprayers would be fucking 10/10.

**Comment by TheNightingale** [comment]
I'm working on the back-mounted flamethrower now; it's basically just a bioterror spray full of (10,000 units of) ClF3 (and a ridiculous spray range), because I can't into flamethrower code.

**Comment by Steelpoint** [comment]
This item seems fine but worthless.

More protection is nice, but at 10 (or 8) telecrystals your better off investing into a Energy Shield, which is far more useful than a stronger Hardsuit.

The difference between 40 melee and 60 melee is meaningless if your stunned by a Officer with a Taser.

You may as well just make the Syndicate Commander spawn with the Elite hardsuit for identification purposes, would be pretty cool.

**Comment by bear1ake** [comment]
:+1: for fire protect!

**Comment by Lumipharon** [comment]
>I'm working on the back-mounted flamethrower now; it's basically just a bioterror spray full of (10,000 units of) ClF3 (and a ridiculous spray range), because I can't into flamethrower code. 

An actual flamethrower is way more robust then a ClF3 sprayer, because with the new way fire works, people running through fire tiles will get more and more fire stacks.
With ClF3, the fire tiles don't spread, and vanish quickly. With an actual flamethrower, the fire spreads and lingers, as well as heating up the room.

**Comment by Zilenan91** [comment]
It shouldn't be too hard to make a back-mounted flamer with a robust burn mix in it.

**Comment by Dorsisdwarf** [comment]
Yeah, backpack mounts can have anything in them.

**Comment by duncathan** [comment]
That would be so kickass
I'd be up to code it if someone wants to tell me a good burn mix for it

**Comment by Zilenan91** [comment]
Also fun fact with the armor values, it's technically 80 melee because of the tactical turtlenecks the Ops have.

**Comment by Dorsisdwarf** [comment]
They'd be like every other backpack item - nodrop or automatically holstering when pushed over

**Comment by TheNightingale** [comment]
I tried to make a backpack flamer, but I can't work out how to use the flamethrower code with the mister/backpack code. If anyone wants to give it a try, go ahead.

**Comment by Zilenan91** [comment]
So is this gonna get merged or are we waiting to add a backpack flamethrower to the pr.

**Comment by Lumipharon** [comment]
as hilarious as the flamethrough could be, it's not really related to this pr.

**Comment by Dorsisdwarf** [comment]
Should still use remie's tacticool syndiesuit sprite though

**Comment by TheNightingale** [comment]
I'm not entirely sure how to do that; are the sprites in the code already?

**Comment by Steelpoint** [comment]
Likely no.

Here's what you need to do if you want to use the proposed above sprites.

1:) Save the image to your computer, put it in your desktop screen or something.

2:) Right click the image and open it with 'Dream Maker'. This will open a new session of DM. You'll be presented a screen showing the icons of the Syndi Suit in all stages.

3:) Copy and paste the icons into their respective file types, rename them if you wish but the default names should suffice. The Helmet icons go into the 'hats.dmi' found at 'icons\obj\clothing\hats.dmi
, the suits themselves go into a file just beneath the hat.dmi called 'suits.dmi'.

4:) In your elite syndi hardsuit spacesuit/hardsuits file you've added in this PR, change the respective icons on the descriptions from the default syndi-helm/suit into the names of the new one's you added.

That should be it.

**Comment by RemieRichards** [comment]
you can just rename the .png I posted above so it's a .dmi, it still has all the .dmi junk in it from when I converted it to a .png to post here.

**Comment by Zilenan91** [comment]
Is this merge ready?

**Comment by TheNightingale** [comment]
I tried to put the NTstation sprites on it, but it turned out horribly wrong and now it's got the 'worn' sprite in the HUD and no sprite when worn... probably just best to merge it now, unless anyone more competent than me wants to take a look at the sprite stuff.

**Comment by swankcookie** [comment]
likely the sprite is incorrectly named, or in the wrong file, as its not being called correctly,

**Pull request merged**
