### PR TITLE
[READY] New bluespace floor tiles

### PR DESCRIPTION
**Pull request by WJohn**
Because having loads of these *flashing green* was fucking obnoxious.

https://dl.dropboxusercontent.com/s/11v4dimiicajzts/2018-09-06_23-49-20.mp4

:cl: WJohnston
imageadd: Added new bluespace floor tile sprites.
/:cl:

### CODE REVIEW

**Comment by nicbn** [comment]
Removed asteroid plating, vault, barber and ateroid floor. Why?

**Comment by ChangelingRain** [comment]
No longer matches bluespace slimes, terrible.

**Comment by Iamgoofball** [comment]
hey nerd you removed icons, check the icon file

**Comment by GunHog** [comment]
These floors look great, but do not seem to match the effect. This looks more like a _shielded floor_ than a floor that makes things go faster!

**Comment by MrDoomBringer** [comment]
wjohn and his sensitive eyes strike again
the green flashing really isnt that obnoxious my guy

**Comment by Iamgoofball** [comment]
yeah these sprites kinda such fam

replace it with the above or bust

**Comment by octareenroon91** [comment]
That sprite is super cool but the rippling/pulsing looks more ominous than hyperactive.

Existing bluespace tile is also undirected, while new tile flows in a particular direction.

**Comment by TheDreamweaver** [comment]
Maybe make it faster?

**Comment by Poojawa** [comment]
Just speed up the animation, there ya go.

**Comment by WJohn** [comment]
Made it twice as fast, how's this?

**Comment by Poojawa** [comment]
Much better. Would it support directional as well, or is that just being ambitious about tiles?

**Comment by WJohn** [comment]
On second thought, the whole moving thing is quite obnoxious to look at when a huge amount of tiles use it, so I think I'll scrap that and go for something a bit less annoying, like pulsing or something. Maybe try a different style entirely.

**Comment by Poojawa** [comment]
Pulsing inside to outside edges, rebounding back into inside, waiting a bit, then doing it again would be nicer on the eyes and be good for connected, omni-directional I'd say

**Comment by nicbn** [comment]
this looks more like a wall

**Comment by WJohn** [comment]
It's hard to see here, I'm not sure how to take a video of it.

**Comment by MrDoomBringer** [comment]
https://i.imgur.com/NhCoyTP.gifv

**Comment by WJohn** [comment]
There we go, I have jumped through the hoops and can now record videos :v

**Comment by WJohn** [comment]
I went for 32x32 pixel tiles like this because the flashing effect only gets more obnoxious the more of it you see, and because I plan to introduce these types of floors in the future if I can get around to completing that.

**Review by ChangelingRain — COMMENTED** [review]
These still don't match the bluespace slimes!

**Comment by XDTM** [comment]
to be fair bluespace slimes don't really reflect the bluespace theme, being green and all

**Pull request merged**
