### PR TITLE
Fixes a bunch of map issues

### LINKED ISSUE #41128: wizard ship intercoms are useless
What it says, he cant hear whats said on station with them and he cant speak to station using them, why are they even there?

### LINKED ISSUE #43276: On Delta, atmostechs don't have access to lock radiation collectors despite SME on it belonging to atmos
Locking radiation collectors prevents changing their state without unlocking, i.e. disabling them; hence, allows players who know about that to prevent relatively fast power sabotage.

### LINKED ISSUE #43491: MULEbot gets stuck behind double windoor access
Issue reported from  Round ID: 105495 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 512

Metastation

Pauses to make a sighing buzz just long enough for one to close after the other opens.

### LINKED ISSUE #43595: Various Science map issues.
-Metastation: Has a white locker in Toxins that contains 2 full science outfits, rather than having 2 sci lockers with one set in each.

-Boxstation: No spare sci equipment sets or lockers

-Pubbystation: No spare sci equipment sets or lockers

-Deltastation: Missing roundstart headset in robotics, no spare sci equipment sets or lockers

-Donutstation: No sci drobe, no spare sci equipment sets or lockers

### LINKED ISSUE #43937: Amber ERT's can C4 Centcom vault room to get pulse guns/mateba
## Round ID:
108320

## Reproduction:

image

Amber ERT's get C4 which allows them to enter the Administrative Office room above their spawn gear room, then blast their way through the locked Vault door and get free shit like a Pulse Carbine, 3 packs of X4, and a Mateba autorevolver. ERT's probably shouldn't be encouraged to blast their way through centcom for loot, and pulse guns are kept to Red alert for a reason

### LINKED ISSUE #44638: Metastation medbay intercoms have the wrong configuration
## Round ID:
110934

## Testmerges:

All the medbay intercoms on metastation are set to the medical frequency (148.5) with speaker off and microphone on. This makes them useless, as they cant actually broadcast to the medbay channel and require fiddling to use for common.

### LINKED ISSUE #44862: Smart Cable incorrectly links AI sat to power grid roundstart
AI sats are now wired to the grid at roundstart, which leaves them vulnerable to power sinks. This is especially dangerous on Meta where telecomms becomes directly powered by the grid with no airlocking.

## Reproduction:
look at a map, like meta

### PR DESCRIPTION
**Pull request by 81Denton**
## About The Pull Request

This PR fixes a bunch of map issues; if you have detail questions feel free to ask.

Closes: #41128
Closes: #43276
Closes: #43491
Closes: #43595
Closes: #43937
Closes: #44638
Closes: #44862

## Why It's Good For The Game

gottado

## Changelog
:cl: Denton
tweak: Delta: Atmospheric technicians are now able to lock/unlock the SM engine's rad collectors with their IDs.
fix: Donut: Added a missing SciDrobe vending machine to the RnD "Excess Storage" area.
fix: Meta: Fixed the AIsat being connected to the station's power grid by round start. Fixed Medbay intercoms with faulty presets. Removed a duplicate windoor in the cargo bay that kept MULEbots from leaving their area.
fix: Mining station: Fixed unconnected air supply pipes.
fix: Replaced the CentCom admin storage vault door with bomb-proof shutters (require CentCom Captain level access to open). Removed broken intercoms from the wizard shuttle and replaced them with two headsets.
fix: Deleted random duplicate and broken atmos piping in most maps.
/:cl:

### CODE REVIEW

**Comment by HomocidlePancakes** [comment]
>Replaced the CentCom admin storage vault door with bomb-proof shutters (require CentCom Captain level access to open). Removed broken intercoms from the wizard shuttle and replaced them with two headsets.

B-but... Muh pulse rifle....

**Comment by 81Denton** [comment]
If someone has spare time, feel free to hit the check plumbing verb on Donutstation. None of the /tg/ servers were running the map earlier.

**Comment by TerraGS** [comment]
The hero we deserve

**Comment by 81Denton** [comment]
Ah shit here we go again

**Review by SpaceManiac — APPROVED** [review]
aight

**Comment by GravitronBlue** [comment]
Issue #43937 does not seem fixed by this PR.
Following some brief testing with the Centcom armory blast door and button, here's a quick list of discoveries.

- The new armory shutters does not stop C4 from destroying it
- ERTs have access to the shutter button
- The Centcom ID card right next to the button that has access to the button

**Comment by 81Denton** [comment]
Looks like I used the wrong subtype and access level for the shutters, darn. I'll open a fix PR today or so.

**Pull request merged**
