### PR TITLE
Dynamic hair!

### PR DESCRIPTION
**Pull request by RemieRichards**
<B>What:</B>
Hair State + Dynamic Hair Suffix = Dynamic Hair!
Eg:
```"long_hair1"``` + ```"+winterhood"``` = ```"long_hair1+winterhood"``` in ```'hair_extensions.dmi'```

Supports Masks and Head items (though only ones that are actual ```/clothing``` subtypes), and facial hair.
In terms of head hair, the head item's suffix takes priority.
In terms of facial hair, the mask's suffix takes priority.
The two variables (for hair and facial hair) override the HIDE flags, this is because the HIDE flags are used in certain situations due to visual weirdness, which can be eliminated differently using this new system.

This allows you to do things like having a person's hair pop out of their hood (requires a new hair sprite)
No examples included because I can't sprite, especially not our whitescale hair sprites.

<B>Why:</B>
You can look p.weird without your hair in certain clothing  items.

### CODE REVIEW

**Comment by Thunder12345** [comment]
Does this cover looking pretty weird with hair in some cases as well?

**Comment by GunHog** [comment]
I love RemRem feature PRs! They add such nice touches!

**Comment by RemieRichards** [comment]
if you make sprites for them, and assign the variables on those head/mask items, yes @Thunder12345

**Comment by Thunder12345** [comment]
Now we just need someone willing to sprite hair related things

**Comment by WJohn** [comment]
Does this fix #3583, or just allow it to be fixed?

**Comment by coiax** [comment]
Does this fix people becoming bald when they put on a sombrero

**Comment by Niknakflak** [comment]
Sweet jesus this is amazing

**Comment by ChangelingRain** [comment]
It doesn't, @coiax, but it adds the ability to!

**Comment by RemieRichards** [comment]
@WJohn read the op, no examples included, but yes it's a system that can fix that.
@coiax @ChangelingRain is correct.

**Comment by xxalpha** [comment]
So...hair specific sprites for hats? For each hat?

**Comment by RemieRichards** [comment]
@xxalpha Yes.
For example, the sombrero, this hat looks bad with certain hairstyles (lets say, 20% of them), so what does it do? it hides all hair! that's 80% of hairstyles being hidden when they work fiiiine. The new way of doing it would be to remove the HIDEHAIR flag, and give the sombrero a ```dynamic_hair_suffix``` (probably ```"+sombrero"```), then the 20% of hairstyles that don't work can simply add a new icon in ```'hair_extensions.dmi'``` called ```"HAIRSTYLE_ICON_STATE+sombrero"```

It's a niche feature, but it's a visual nicety (provided spriters get off their lazy bums *cough* @WJohn *cough* @ausops)

**Comment by xxalpha** [comment]
Sounds like it needs someone obsessed with this problem to be programmed for all hats that need it. Good to have either way.

**Comment by RemieRichards** [comment]
Most likely, yeah.
It was just an idea I thought up on the bus home yesterday.

I was specifically thinking about winterhoods, and how it'd be cool+cute if people's hair stuck out the front of the hood, as opposed to making them bald!

**Comment by Hatfish** [comment]
How would this affect mutant races?  Would lizards finally be able to wear hooded clothing without getting most of their faces lopped off?

**Comment by RemieRichards** [comment]
It is for Hair/Facial Hair only.

**Comment by Militaires** [comment]
this goes well with #24859 meaning you can both offset AND switch out hair as you need to

**Comment by Bawhoppen** [comment]
praise

**Comment by KorPhaeron** [comment]
https://github.com/tgstation/tgstation/issues/3583

**Comment by RemieRichards** [comment]
@KorPhaeron bit late.

**Pull request merged**
