### PR TITLE
Remaps toxins

### PR DESCRIPTION
**Pull request by pudl**
:cl: wrist
add: Toxins is different now.
/:cl:

Toxins room now:

Old toxins storage:

### CODE REVIEW

**Comment by WJohn** [comment]
Neat.

**Comment by MMMiracles** [comment]
Is it really wise to make a section of maintenance part of the mix exhaust?

**Comment by pudl** [comment]
@MMMiracles You can survive the walk if youre fast enough and wearing oxygen

**Comment by pudl** [comment]
Also its funny

**Comment by WJohn** [comment]
It might be best if it was a bunch of blast doors instead of girders, but either way it's pretty funny.

**Comment by Niknakflak** [comment]
Thats dumb

**Comment by TechnoAlchemisto** [comment]
i feel like this is a very inefficient use of space

**Comment by pudl** [comment]
@TechnoAlchemisto Who cares

**Comment by ChangelingRain** [comment]
I don't really like how this makes maint have more long singletile straight sections and less bendy bits where hiding is an option.

**Comment by pudl** [comment]
It removes a single 2x3 area for hiding, the rest was still a long straight area

**Comment by MMMiracles** [comment]
I mean the connector between maint, mixing, and the test range is literally just an empty 7x3 room which looks really out of place.

Also the disposal bin has no pipe connected to it.

**Comment by PKPenguin321** [comment]
this could be funny but the girders to space need to also be blast doors with maybe grilles under them

**Comment by ChangelingRain** [comment]
Not just long and straight, the section that was there wasn't singletile.
For contrast purposes, here's the same(visible) area before changes;


Does it look like there's more changes here than what's visible? Hmmmmmm.

**Comment by pudl** [comment]
Sorry i didnt see the singletile. I dont think its a big deal personally. You can already lose someone just by crossing through the vacuumed area since theyll have to put on a oxygen mask to go through it.

**Comment by kevinz000** [comment]
Could use a better reasoning then "who cares"

**Comment by pudl** [comment]
@kevinz000 I dont see why everything has to be perfectly allocated to a certain amount of space between objects and things cant sometimes be more open or a little more cramped than usual, it creates variation. Mappers should be allowed to have actual fun.

**Comment by Supermichael777** [comment]
put some stulf in the empty room, like a table with a desk lamp, roller chair, and crumpled papers.

Make it a bit more then a dead space.

**Comment by pudl** [comment]
The room has space for the purpose of being used to possibly set up more machines

**Comment by ChangelingRain** [comment]
>You can lose someone by going through the three airless tiles

exCUSE ME, what the fuck are you talking about that's three tiles and the oxygen damage isn't even a threat unless you're hilariously low on health

**Comment by KorPhaeron** [comment]
Muhammad maint loop

**Comment by KorPhaeron** [comment]
Anyway is there a reasoning/goal behind this change?

**Comment by TechnoAlchemisto** [comment]
Those airlocks are maint not external access I imagine, right?

**Comment by KorPhaeron** [comment]
Also: Does changing the size of the mix chamber change how atmos mixing works? Would lower the pressure of the plasma this way, right? All maps seem to use the same size mix chamber currently

**Comment by AdamElTablawy** [comment]
tbh i like inefficiency of space-contributes to the theme of the station being a barely functional deathtrap cobbled together by an uncaring corporation

**Comment by Militaires** [comment]
i like the old one better

**Comment by KorPhaeron** [comment]
We have not had "cobbled together death trap" as a theme for years, and everyone seems to hate the only map that still does that (birdboat)

**Comment by Jalleo** [comment]
Thats because atmos and the AI was too heavily nerfed where other types of things weren't.

**Comment by pudl** [comment]
Biggest reasons for this PR are to move toxins storage to be connected to toxins, and to make the burn chamber 3x3. Also cool that i got to add the new freezer and pipe exhausts.

**Comment by pudl** [comment]
Made some improvements
- Added a table with cards to the big empty transit area, so maybe assistants and scientists can chill together
- Gave toxins room a metal foam grenade and a tape recorder for fun
- Gave the exhaust port a blast door
- Added a table with more useful tools in the gas storage
- Extended the maint nearby to 2 wide, added more items to it as well
- Fixed a couple of errors i made

**Comment by GunHog** [comment]
Storage room needs an atmos hookup!

I half-way wanted to ask for shutters for the entrance windows so accidents (actual accidents) do not break the windows and spill out into the halls, but since the storage room is no longer separate, deliberate plasma flooding would be made difficult :/

**Comment by Bawhoppen** [comment]
too sleek and efficient though to be fair I do like some aspects of it like the maint door through space

seems like it would be more suited for a map like meta as opposed to box, box is supposed to be very basic, also the deck of cards is dumb

**Comment by as334** [comment]
Would it be possible to get add a pipe dispenser in there?

**Comment by pudl** [comment]
@as334 That's a good idea, I think I'll ask people what they would think about it first, though.

@Bawhoppen Glad that you like some of it, I didn't necessarily go into the remap aiming for something more efficient though. I wanted to make something different in pace from what tg normally uses in toxins, and have a more unique concept. I don't think that the design being less traditional makes it any more efficient, you could say that the space freezer is less efficient really. I dunno.

**Comment by GunHog** [comment]
I gave it a quick comparison, and here are the things I noted.

- The entrance has been moved up.
- :+1: The Triple canister mixer has valves now.
- :confused: The primary burn chamber is now larger (not sure if that is good, though)
- :question: There is now a one-tile thing with an intake vent. I am not sure what its purpose is, though. (Unless it can be reversed?)
- :+1: There is a H/E space loop now, although its tiny length is probably not effective. I recommend removing the grilles and extending the loop.
- The new burn chamber intersects maintenance, and now exposes to space. 
**Recommendations: Replace the girders with a second set of blast doors (on the same button).** This way, people can still ""safely"" travel through that area _until someone opens the exhaust doors._  :smiling_imp: 
- :-1: The new 4-way junction room is missing its camera.
- :+1: The launch room's design now appears to seat two people, for a teacher/student feel.
- :+1: There is now a firefighter's closet near the entrance.
- :-1: The bomb suits are now outside the room, making them easier to steal for people without toxins access, I cannot find the biosuit or spare wardrobe closets. Were they moved out of sight or simply deleted?
- :+1: Additional huge scrubber in storage.
- Some maint loot spawners appear to have been lost.
- Missing some "SPACE" warning signs in the launch room, burn chamber, and maintenance external airlocks. 
- :+1: Disposals shute has been added. Nice for escaping a fire or mailing bombs!
- :+1: Tile markins for input/output spaces. Adds some color and a nice touch.
- Grenade casing added (and recorder). I am not sure what the point of that is, Toxins has nothing to put into them, and the other assemblies are for bombs.

Overall, I would prefer the new map to the old one, even if it is merged as it currently is. I would say it is a good bit of work.

**Comment by pudl** [comment]
New changes
- The intake vent was changed to an injector
- Girders replaced with blast doors
- Access room now has a camera
- Biosuit added to the room
- Wardrobe readded (out of sight in screenshot)
- Space sign added in launch room

@GunHog The grenade casing is a metal foam grenade

**Comment by GunHog** [comment]
FANTASTIC! Looking forward to the merge!
Oh, that second chamber is for emptying canisters? Coolio.

**Comment by PKPenguin321** [comment]
one issue i have with it that i failed to mention sooner what that this actually makes the station slightly less lethal, as previously science had windows directly to space, which are now r-walls. now it exposes maint to space, which is a much lower priority area.

i don't really care *too* much but it's something to point out

**Comment by FantasticFwoosh** [comment]
Could the blast doors have (non electrified please because space wind is awful) grilles behind them to stop objects put inside the chamber floating away into space. (dont forget the doors to the actual test chamber that you've omitted from the picture else the entire lab is going to flood with fire/atmos problems)

This is a definite upgrade to the original. That interim 'waiting area' above still bugs me though, if you could make it dimmer (1 light over the table) and more in line with shoddy maint (oil spills, lockers) you might be able to get away with it though. Glass doors between bomb range and toxins lab kills the immersion too, please remove those, as the line of sight doesn't really blend with other station interim areas like genetics/science maint on box (beside being a security risk for people lasering through the glass to shoot open canisters/bombs).

Apologies for the nitpick, i hope the feedback is useful.

**Comment by pudl** [comment]
@FantasticFwoosh Lots of the things you're bringing up are just things that DM does. There arent any glass doors in the pic, DM just shows all doors as glass because of an overlay thing. And the doors are there, the sprites are just broken in DM.

The waiting area thing is already extremely dim, I dont want to make it any worse.

**Comment by Bawhoppen** [comment]
ss 2016-10-09 at 11 10 22

is that a bug on my end or because of conflicts

**Comment by optimumtact** [comment]
Stale and conflicting

**Comment by pudl** [comment]
@optimumtact Remove the stale tag, I spent a couple hours today fixing the conflict, I'm just at work now.

**Comment by pudl** [comment]
Wtf more conflicts?

**Comment by GunHog** [comment]
Did you merge to an outdated version?

**Comment by pudl** [comment]
Conflicts fixed @optimumtact

**Comment by Shadowlight213** [comment]
@pudl there needs to be an air alarm and vent or something for the part of maint below the space bridge. With fastmos, that area of maint is going to be quickly depressurized by anyone going through with nothing to repressurize it.

**Comment by pudl** [comment]
@Shadowlight213 If you added those, air being added and scrubbed from the burn chamber would damage the toxins burn.

**Comment by optimumtact** [comment]
Fix the build and get this test merged so we can get some more feedback

**Comment by Shadowlight213** [comment]
@pudl No. not IN the bridge. in maint below it.
The area of maint past the southern airlock.

The northern room has scrubbers and an air vent, but the south doesn't.

**Comment by CPTANT** [comment]
Personally I have always wondered why the heaters/piping in the testing lab isn't part of the toxins lab, because that's what it is actually useful for.

**Comment by pudl** [comment]
I am going to close this PR unless I can get someone to merge it for me next time I fix conflicts.

**Comment by GunHog** [comment]
I do not want this one to die :(

**Comment by yackemflam** [comment]
I like this don't close their reeee

**Comment by Shadowlight213** [comment]
@pudl If you don't want to add atmos for the bottom maint, then at least make the airlocks there actual 2 door airlocks so air doesn't immediately vanish from maint.

**Comment by GunHog** [comment]
Use that MSO lazy airlock system, that would work perfectly for this.

**Comment by pudl** [comment]
Conflicts owned hard @optimumtact

**Comment by KorPhaeron** [comment]
Did anyone ever test if bomb making is different with a bigger mix chamber?

**Comment by yackemflam** [comment]
You guys really don't know how bombs works do you?

A larger chamber does help plasma burn faster BUT most people go with in-cannister burning anyhow.

Also bombs go boom when hot plasma + cold oxygen mix.

The tank transfer valve just makes the bigger booms because it's all compressed into a single 'square'

So the answer to your question kor, 'meh'.

**Comment by GunHog** [comment]
Things I note from playing it:
- The Scientist wardrobe locker is gone, meaning transfers to the Science staff cannot get a uniform (short of killing a spawned one and taking his...)
- The Toxins APC is not connected to the grid. The wire abruptly terminates in the hallway.
- The toxins burn chamber portion of eastern maintenance lacks double "lazy" airlocks. In theory, it should be safe to cross at roundstart until a toxins player opens the chamber to vent his burn mix.

**Pull request merged**
