### PR TITLE
adds ion rifle to cargo for 8000 points without vcordie's memery

### PR DESCRIPTION
**Pull request by jughu**
A EXPENSIVE RIFLE

:cl: Hyena
rscadd:Adds ion rifle crate to cargo for 8000 points
/:cl:

[]: # (Please add a short description of why you think these changes would benefit the game. If you can't justify it in words, it might not be worth adding:)apperantly people dont use the TONS of counters and want this i guess...

### CODE REVIEW

**Comment by kevinz000** [comment]
Uh...
No.

**Comment by jughu** [comment]
mekhi pls stop turning cyborgs into segways

**Comment by jughu** [comment]
AUCTALLY MEKHI AND MY IMMERSION IS RIGHT 
CARGO CAN INDEED BUY SILICON SUNTS
THEY ARE CALLED FLASHES SO GIT GUD

**Comment by jughu** [comment]
Auctally nevermind...

**Comment by ma44** [comment]
There's no point if cargo can just give materials to RnD for infinite ion carbines anyway

**Comment by AdamElTablawy** [comment]
i mean

if combat shotguns are available in cargo for relatively cheap

why not ions

**Comment by Davdichan** [comment]
Don't ion's also drain tasers/e-guns and emp doors to shock them/open them? Seems like a bad idea to give cargo that level of bullshit.

**Comment by AdamElTablawy** [comment]
Seems like a bad idea to give cargo automatic rapid fire shotguns that can be loaded with whatever fuck you set you like for cheap.

Seems like a bad idea to give miners overpowered lavaland loot like fucking holoparasites and justify it with 'but it's in a dangerous place.'

Seems like a bad idea to give changelings invisible one-shot tazers.

Seems like a bad idea to give botany exploding rapid-spreading fire immune vines.

Sure didn't stop any of that though

**Comment by jughu** [comment]
if they really wanted to emp shit up they could build RnD console and protolathe from tech storage and broke up a shotgun crate and make emp shells

**Comment by optimumtact** [comment]
Look just stop touching cargo, it's properly fucked at this point in time thanks to exports.

**Pull request closed without merging**
