### PR TITLE
>2 cost for 4 second stun per sharp item held, instant aggro grabs, theft of items from hands into your own hand, 3 second stun on harm long distance, pudge hook on help

### PR DESCRIPTION
**Pull request by Iamgoofball**
what the fuck is this cancerous bullshit this is as bad as the wrestling belt I added

### CODE REVIEW

**Comment by GunHog** [comment]
I took the liberty of posting this in OOC, as this is an inappropriate use of the [s] tag.

**Comment by Iamgoofball** [comment]
@GunHog i'm preventing a rule breakage

**Comment by KorPhaeron** [comment]
freeze

**Comment by kilkun** [comment]
this is definitely a fucking fix

**Comment by kilkun** [comment]
you _cant_ slice it any other way

**Comment by kilkun** [comment]
this is a fix like the bomb cap was a fix

**Comment by Haevacht** [comment]
No. This is a removal. Doesn't fix a bug. Also falls under rebalance.

**Comment by kilkun** [comment]
it does fix a bug

the bug that is this horrible shit existing in the first place

**Comment by PKPenguin321** [comment]
:salt:

**Comment by Cyberboss** [comment]
Tentacles are fucking shit

**Comment by XDTM** [comment]
Welp, any way i can make them better before straight removal?

**Comment by kilkun** [comment]
no

give it to another antag that isn't changeling. thats about all you can do.

**Pull request closed without merging**
