### PR TITLE
Adds a mini fire extinguisher to janitor and service borgs

### PR DESCRIPTION
**Pull request by BeeSting12**
:cl: BeeSting12
tweak: Janitor and service cyborgs now get pocket fire extinguishers for fire suppression and space propulsion.
/:cl:
why: getting stuck in zero gravity or space sucks

### CODE REVIEW

**Comment by ShizCalev** [comment]
creep

**Comment by alexkar598** [comment]
I stuck in specs please buff?

**Comment by Repukan** [comment]
I thought all bots included some form of fire extinguisher?

Regardless, don't they have a spray bottle module?

**Comment by alexkar598** [comment]
I stuck in spess please buff???????

**Comment by Anonmare** [comment]
@Repukan Not every module has an extinguisher. The only thing every module has, including the syndie ones, is a flash

**Comment by Repukan** [comment]
Huh, never noticed.

Should probably include service if it doesn't have one too.

**Comment by Anonmare** [comment]
Personally I'd prefer to make fire extinguishers standard on all modules but I'd probably get yelled at

**Comment by octareenroon91** [comment]
>Personally I'd prefer to make fire extinguishers standard on all modules but I'd probably get yelled at

Do it. It helps crew with negligible balance change.

**Comment by pubby** [comment]
They already have anti-slip spray, which works for space propulsion.

**Comment by MimicFaux** [comment]
Also gives janiborgs a passable melee weapon.

**Comment by BeeSting12** [comment]
Yeah, they do have antislip spray- I was tired and didn't notice last night. Woops! I still think it's a good idea to give all the cyborgs some kind of fire supression system/space propulsion thing though. I'll check if the service borgs have one, I believe every other kind has either a full fire extinguisher or a mini one.

**Comment by BeeSting12** [comment]
Now each type of cyborg has some kind of fire extinguisher. The ones I added or miniature ones, I believe the damage is negligible or at very least no better than any other weapon they have so not much of a balance issue.

**Comment by KingPhilipIII** [comment]
I see borgies more often than not extinguishing moronic crew members.

**Comment by BeeSting12** [comment]
Is Travis still running?

**Comment by ShizCalev** [comment]
3mqsfyv

travis said fuck your borg powercreep pr

**Comment by BeeSting12** [comment]
anyone know why Travis is failing? I couldn't really view the log

**Review by Cyberboss — APPROVED** [review]

**Pull request merged**
