### PR TITLE
Fixes a hilarious copypasta-based bug

### LINKED ISSUE #20836: On some level all blood cultists are still clock cultists
@ChangelingRain 

When using the check antagonist screen during a blood cult round the cultists are listed both as Cultists and Servants of Ratvar.

This means on some level the assignment is still confusing them. Hopefully just on a cosmetic level at this point.

### PR DESCRIPTION
**Pull request by ChangelingRain**
Fixes #20836

### CODE REVIEW

**Comment by Shapsy** [comment]
oh dear

**Comment by WJohn** [comment]
Oh dear

**Comment by Incoming5643** [comment]
Fixes #20836

21 second turn around time :+1:

**Comment by Cheridan** [comment]
yare yare daze

**Comment by ChangelingRain** [comment]
I'm good at coding

**Review by phil235 — APPROVED** [review]
:+1:

**Comment by Shadowlight213** [comment]
Headcoder when

**Comment by lzimann** [comment]
joan really likes clock cult huh

**Pull request merged**
