### PR TITLE
Allows atmos techs to harness lava power

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
By running heat exchange pipes over lava to heat up gas.

I need help with the actual numbers, I don't know what is appropriate.

:cl: Kor
rscadd: Running HE pipes over lava will now heat the gas inside.
/:cl:

### CODE REVIEW

**Comment by Zilenan91** [comment]
How will they place these

**Comment by KorPhaeron** [comment]
With their RPD

**Comment by Zilenan91** [comment]
The RPD has more range than right next to you?

**Comment by KazeEspada** [comment]
You stand on land next to lava, you click lava tile, you pray spacewind no push you.

**Comment by octareenroon91** [comment]
>How will they place these beyond one tile over the lava

- one tile around the perimeter could be enough.
- lava boats.

**Comment by Jalleo** [comment]
Could be used to potentially make a infinite powering turbine for mining stations. (Gives a way to actually sabotage power there and remove the smes cells)

**Comment by coiax** [comment]
So are heat exchange pipes exchanging heat with space yet? (which is apparently intentional despite being physically impossible)

**Comment by fizzle7** [comment]
> So are heat exchange pipes exchanging heat with space yet? (which is apparently intentional despite being physically impossible)

.
> Playing SS13

> Not being an aerospace engineer

Heat exchange pipes exchange heat through radiation.

**Comment by drynwyn** [comment]
It should be possible to turn lava to rock if you can get the atmosphere cold enough.

**Comment by coiax** [comment]
.> Radiation pipes that work equally well in atmospheric conditions because they also conduct

Sure.

**Comment by fizzle7** [comment]
Conduct what?

**Comment by KazeEspada** [comment]
Conduct heat!
Radiation heat: Imagine sticking your hand under a heat lamp. You feel the warmth? That's mostly radiation heat from the heat lamp(and some heat conducting through the air).
Conduction Heat: Touch the heat lamp. Feel your skin burning off? That's heat conducting out of the heat lamp and into your skin.

The thing about space is that it's a vacuum, which means its the ultimate insulator so the pipes wouldnt conduct heat at all to space... so they must be radiating out the heat into space.

Well, with lava, its touching the lava, so its conducting heat from the lava and into the pipe.

**Comment by CosmicScientist** [comment]
Earth level space heat when? Then we'll have an excuse to have a temperature department trying to keep the station cool with ~radiators~!

**Pull request merged**
