### PR TITLE
[DNM] Revert move type refactor, fixing the constant server crashes

### PR DESCRIPTION
**Pull request by Mothblocks**
Disabling gravity causes too many parallel animations, crashing the server.

Someone else can figure out how to fix this (Lemon seems to want to), but I would just like to stop being pinged for being a key holder, it's discrimination.

Reverts  #55444

### CODE REVIEW

**Comment by optimumtact** [comment]
you signed up for CBT, now you get it and you look away?

**Comment by LemonInTheDark** [comment]
Most likely related https://github.com/tgstation/tgstation/issues/55912

**Comment by LemonInTheDark** [comment]
Also way to throw me under the bus

**Comment by sqnztb** [comment]
> Most likely related #55912

Amusingly, I posted the bug report right before the testmerge hit and, yes, it does fix the issue.

**Comment by MrStonedOne** [comment]
what pr does this revert?

**Comment by optimumtact** [comment]
the move type refactor

**Comment by MrStonedOne** [comment]
@Jared-Fogle could you add #55444 to the pr op so people know what pr this reverts.

**Comment by Jared-Fogle** [comment]
Fix has been merged.

**Pull request closed without merging**
