### PR TITLE
Resprites (desouls) HoP's uniform

### PR DESCRIPTION
**Pull request by axietheaxolotl**
## About The Pull Request

Does what it says on the tin. Old sprites were cringed peepee poopoo, these are better.

image

image

## Why It's Good For The Game

haha Jonathon, you are desouling the codebase

## Changelog

:cl: axietheaxolotl
imageadd: new and redone HoP uniforms
/:cl:

### CODE REVIEW

**Comment by axietheaxolotl** [comment]
> You currently have a negative Fix/Feature pull request delta of -1. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

I DON'T CARE

**Comment by Bawhoppen** [comment]
Growing/losing breasts depending on which version you wear, haha
 👍

**Comment by axietheaxolotl** [comment]
> Growing/losing breasts depending on which version you wear, haha
👍

yes :trollface:

**Comment by GuillaumePrata** [comment]
It looks like the skirt version is missing or the bot is drunk.

**Comment by ArcaneMusic** [comment]
> Growing/losing breasts depending on which version you wear, haha 👍

It's called a padded bra, MOM

**Comment by axietheaxolotl** [comment]
> It looks like the skirt version is missing or the bot is drunk.

nope I just got brain damage

**Comment by optimumtact** [comment]
> > You currently have a negative Fix/Feature pull request delta of -1. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.
> 
> I DON'T CARE

image

**Comment by cacogen** [comment]
You should have to add a before and after for sprite changes. The IconDiffBot's output is too small to make out the details and I'm too lazy to resize them myself.

**Comment by axietheaxolotl** [comment]
> 
> 
> > > You currently have a negative Fix/Feature pull request delta of -1. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.
> > 
> > 
> > I DON'T CARE
> 
> image

memegenerator.net

**Comment by Twaticus** [comment]
the waist height + skirt length combo looks a little frumpy, if you make it 1/2(might be pushing it) pixels shorter it looks pretty cute 
image

**Pull request merged**
