### PR TITLE
glorf jumpsuit

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
https://tgstation13.org/phpBB/viewtopic.php?f=9&t=5929&view=unread#unread

### CODE REVIEW

**Comment by PKPenguin321** [comment]
:+1:

**Comment by Thunder12345** [comment]
I approve of th- **GLORF**

**Comment by duncathan** [comment]
Is it obtainable in game

**Comment by PKPenguin321** [comment]
according to the lines changed, no

**Comment by octareenroon91** [comment]
That's going to be a 100% glorf rate, but it looks like they will all just be saying "-GLORF" etc.

**Pull request merged**
