### PR TITLE
Adds a chemical reaction to stabilize plasma

### PR DESCRIPTION
**Pull request by XRandomXManX**
## About The Pull Request

With Stabilizing Agent as a catalyst, Plasma can become Stable Plasma.
Keep in mind that there are no reactions that require both Stabilizing Agent and Plasma, and there are no reagents that need to be stabilized that contain Plasma.
Previous PR for all those that watched its 7 minute lifespan #53074 

## Why It's Good For The Game

Currently there is no ghetto chemistry way to get Stable Plasma (Which is completely non-reactive).
You cannot get Stable Plasma from the Chemical Starter Kit from Cargo either.
This will allow smart players to finish their Ghetto Chemistry Sets!

## Changelog
:cl: Radacitus
add: Added a chemical recipe for Stabilizing Plasma
/:cl:

### CODE REVIEW

**Comment by optimumtact** [comment]
what is stable plasma useful for?

**Comment by ATH1909** [comment]
> what is stable plasma useful for?

Cryoxadone, phlogiston, pyrosium, cryostylane, liquid dark matter, teslium, colorful reagent, drying agent, and anything that uses those chems.

**Comment by optimumtact** [comment]
OP could you please expand on why this is hard to get in a ghetto fashion and what gap you're filling here?

**Comment by ATH1909** [comment]
> OP could you please expand on why this is hard to get in a ghetto fashion and what gap you're filling here?

Nothing grinds into stable plasma, resulting in a few chems being un-ghetto chem-able.

**Comment by optimumtact** [comment]
wouldn't that give chemists the exact same problem? How do they get it?

**Comment by ShibaInuLord** [comment]
chem dispenser

**Comment by GuyonBroadway** [comment]
You get stable plasma from the chem dispenser and aside from mix with stuff it does literally nothing.

**Comment by TemporalOroboros** [comment]
Apparently stable plasma is a holdover from when goonchems were ported. Some of their recipes used plasma, and whoever was doing the porting thought it would be overpowered if the chem dispenser could dispense free plasma. So we got stable plasma.

Apparently, it was goof.

**Comment by Spepbuthewranglesgithub** [comment]
a net improvement to ghetto chemistry that actually makes sense, wonderful to see.

**Comment by optimumtact** [comment]
This seems perfectly okay then

**Comment by XRandomXManX** [comment]
> OP could you please expand on why this is hard to get in a ghetto fashion and what gap you're filling here?

Ghetto Chemistry is a way of making Chemicals without a Chemical Dispenser.
You cannot get Stable Plasma without a Chemical Dispenser, it's not only hard to do, but completely impossible, even if you have access to Cargo. The PR is mostly for Cargo to make bounties that might require it, but also useful for the Janitor to get Drying Agent and for Clown to get Colorful Reagent.

**Pull request merged**
