### PR TITLE
Merges lizard screams

### PR DESCRIPTION
**Pull request by ModDownloading**
## About The Pull Request

Merges the lizard screams super12pl made from Beestation, since the ethereal screams were merged not too long ago and I thought it would be a good idea to do this too. Also, all the sounds have been confirmed to be under the creative commons license, so no worries about copyright (https://github.com/BeeStation/BeeStation-Hornet/pull/2407 for copyright info, it's near the bottom).

## Why It's Good For The Game

image

Ok, but seriously, ethereals and moths already get unique scream sounds and since lizards currently make no sound when screaming this should do the trick.

------------------------

## Changelog
:cl:
add: Added lizard scream sound effects, because that's exactly what we need.
/:cl:

### CODE REVIEW

**Comment by Serxule** [comment]
send sounds i wanna hear the screm

**Comment by Qustinnus** [comment]
these sound really bad

**Comment by coiax** [comment]
Yeah, you're going to need to get approval from maintainers for this.

> Code adding, removing, or updating the availability of alien races/species/human mutants without prior approval. Pull requests attempting to add or remove features from said races/species/mutants require prior approval as well.

Ask in Slack for maintainer approval to do this.

**Comment by Qustinnus** [comment]
hit me up with that slack invite link bro

**Comment by coiax** [comment]
Fuck, I mean discord. 😭

**Comment by coiax** [comment]
image

I served both as executioner and midwife?

**Comment by Mothblocks** [comment]
look at coiax with an actual job where he needs to be on slack

**Review by Mothblocks — CHANGES_REQUESTED** [review]
lizard_scream_1 currently cuts off very abruptly.

**Comment by ModDownloading** [comment]
@Mothblocks Yeah, that scream does that in the original file too for some reason. I didn't notice too much with that ingame, but if you think it's a problem I can exclude it and just have the other 3 be ingame.

**Comment by Mothblocks** [comment]
works for me

**Comment by ModDownloading** [comment]
Ok it looks like Github doesn't want to cooperate and won't let me rename the .ogg files so it's time to do this the manual way, hold on to your hats everyone!

**Comment by ModDownloading** [comment]
Alright it's fixed now, deleted all the sound files and reuploaded 2, 3 and 4 as 1, 2 and 3 (effectively getting rid of the first sound file without throwing off the rest). Fixed up emotes to get rid of the extra file and credits to remove the first sound file from being mentioned. Should be all good to go now unless there's something else you want me to do.

**Comment by Mothblocks** [comment]
Have you tested it in game?

**Comment by ModDownloading** [comment]
Tried to do that, but it gave me the error "build.bat: Failed to bootstrap Node! Press any key to continue..."

I don't see any real difference between this and the ethereal scream PR, so it should work anyway, but I would appreciate some help on figuring out why the .bat file isn't working.

**Comment by Mothblocks** [comment]
PRs require testing on the part of the contributor, I recommend asking in #coding-general about your issue.

**Comment by ModDownloading** [comment]
@Mothblocks Got it, will go onto the discord right now. Sorry about trying to submit without testing.

**Comment by ModDownloading** [comment]
@Mothblocks Alright, after going on to the discord and getting help (thank you stylemistake!) I was able to compile it properly and can confirm it works as intended.

**Pull request merged**
