### PR TITLE
[RFC] The noop template turf uses a sprite that makes its behaviour more obvious

### PR DESCRIPTION
**Pull request by Mervill**
RFC - Request for Comment

This idea popped into my head randomly; the "Turf Passthrough" tile used in ruins is given a spite that resembles the transparency pattern used by the dmi editor (and most editors, actually).

I tried two variants:

%0 transparency (in this pr)

%50 transparency, blending with the blue of editor's default fill color

The argument: It's a bit more visually obvious what the behavior of these tiles might be. It's a small dev QoL thing.

The "honk" tile is preserved for posterity

### CODE REVIEW

**Comment by monster860** [comment]
Just make the sprite solid BYOND-purple.

**Comment by Iamgoofball** [comment]
I like the 0% transparency

**Comment by optimumtact** [comment]
not a fix

**Comment by PKPenguin321** [comment]
What happened to sprite tweaks being allowed during a freeze

**Comment by Jordie0608** [comment]
oranges did.

**Pull request merged**
