### PR TITLE
The escape pod emergency safes now contain oxygen tanks instead of air mix tanks

### LINKED ISSUE #14650: Oxygen Tanks in the pod safes are set at 101 pressure
Instead of at 16

### PR DESCRIPTION
**Pull request by Buggy123**
Fixes #14650

They're also a nice emergency-red now.

### CODE REVIEW

**Comment by Zilenan91** [comment]
You're on the ball today

**Comment by Buggy123** [comment]
I realized that I'm not actually that far behind the guy in the lead for the freeze. I just gotta fix a bunch of trivial stuff no one else bothered with.

**Comment by xxalpha** [comment]
This shouldn't count for the cheribucks as the issue was opened after the freeze started.

**Comment by RemieRichards** [comment]
Yeah this isn't worth any Cheribucks.

**Comment by duncathan** [comment]
This is definitely worth cheribucks
Read the rules guys

**Comment by Bawhoppen** [comment]
#formalityfreeze

**Comment by xxalpha** [comment]
Well if this is worth cheribucks then it just means less people will address the old issues that have piled up.

**Comment by Zilenan91** [comment]
Yeah. It's all quantity over age of issues in the freeze, that's just how the format is.

**Comment by KorPhaeron** [comment]
I kept saying the scoring format was screwy and prioritized stuff like this not all of my rambling is insane.

**Comment by Buggy123** [comment]
I'd fix old issues but 99% of that is beyond my expertise.

**Pull request merged**
