### PR TITLE
Completely FIX Hilbert's Hotel and its associated ruin to the game.

### PR DESCRIPTION
**Pull request by Dennok**
## About The Pull Request

Fix hilbertshotel stored room loading
Broken in #53586

Revert to #53790

because `turfNumber++` must be incremented on turf, not on every ATOM it EVERY TURF
and anyway it don't trigger since first turfs don't have atoms in it.

And i test it

fix Hilbert's Hotel peephole runtime Closes #53794
fix hhmysteryRoomNumber generates only once. Closes #53795

Changed some spaces to tabs

## Why It's Good For The Game

Bugs is bad

## Changelog
:cl:
add: Add back Hilbert's Hotel, which once again correctly loads its stored rooms.
/:cl:

### CODE REVIEW

**Comment by Timberpoes** [comment]
Same again Dennok.

Why was the indentation causing the issue and what is the new behaviour?

**Comment by Dennok** [comment]
> Same again Dennok.
> 
> Why was the indentation causing the issue and what is the new behaviour?

because `turfNumber++` must be incremented on turf, not on every ATOM it EVERY TURF
and anyway it don't trigger since first turfs don't have atoms in it.

**Comment by SpaceManiac** [comment]
oof, thanks for the catch

**Comment by cacogen** [comment]
i love dennok

**Comment by ShizCalev** [comment]
@SpaceManiac Look good?

**Comment by SpaceManiac** [comment]
Your fixes look good.

I figured while I already had my eyes on this feature I would touch it up as well.

**Review by SpaceManiac — APPROVED** [review]

**Pull request merged**
