### PR TITLE
Adds a monument to Toolboxing For a Cause 2019

### PR DESCRIPTION
**Pull request by GuyonBroadway**
## About The Pull Request
This adds a stone monument to the arrivals sections of Box, Meta, Delta, Doughnut and Pubby to commemorate the achievement that was Toolboxing for a cause 2019

## Why It's Good For The Game
The Toolboxing for a Cause event raised over $4000 for charity, this is an outstanding achivement for a community as small as SS13's and not to mention only TG interested parties would have participated so good job everyone!

I'm happy to edit it['s description to be less explicit and more lore friendly if required but as it stands TFAC 2019 is probably one of the higher points in the history of ss13 and I think it's worthy of a direct mention.

:cl:GuyonBroadway
add: Added a statue to the arrivals of most stations to commemorate Tooboxing for a Cause 2019.
imageadd: Statue sprite by Satoun
/:cl:

To cut to the point, you all lost to Pepper fucking Mint... over one hundred space men, women and whatever else people here may identify as and they all LOST to reddit and 4chan's definition of "why ss13 has gone down the fucking shitter" and as such, I ported the Giant Stone Ass from hippiestation because it's honestly what you deserve.  (the celebration of raising over $4000 is genuine though, well done!)

This butt is based directly on the glorious and immortal buttocks of Billy Herrington, BEHOLD HIS BRILLIANT BUTTCHEEKS AND DESPAIR AT YOUR OWN INADEQUACY! 

If requested I will port the feature of "this statue farts in the same way a clown statue honks" from hippie. 

image

### CODE REVIEW

**Comment by actioninja** [comment]
I like the idea but I don't know if a giant stone ass is the proper monument to this

**Comment by TheRespectedMan** [comment]
> I like the idea but I don't know if a giant stone ass is the proper monument to this

Yes it is, tg has made an ass of itself for letting peppermint win.
May every single member of this community be etched upon this ass for eternity

**Comment by Qustinnus** [comment]
This should be in centcom. We shouldn't flood maps with statues and we did the same for the coder that passed away

**Comment by optimumtact** [comment]
this isn't hippie station

**Comment by ecronogist** [comment]
oranges more like orang

**Comment by GuyonBroadway** [comment]
Image added to OP for reference. 

https://youtu.be/F4qFC0nOSto

**Pull request closed without merging**
