### PR TITLE
Updates the Mafia UI

### PR DESCRIPTION
**Pull request by JohnFulpWillard**
## About The Pull Request

The player currently on the stand has a yellow color behind their name.
Players who have had their roles revealed now has that stated in the player list
Votes no longer show up to people who are on trial

image

Minor edit: It no longer says 'ON STAND', it instead has their name in yellow background
image

## Why It's Good For The Game

Mafia UI's a little better now.

## Changelog

:cl:
qol: Mafia panel no longer shows vote buttons if you're on stand, shows the roles of revealed players, and list out who is on the stand, if any.
/:cl:

### CODE REVIEW

**Review by Ghommie — APPROVED** [review]
All great, but this warrants a slight nerf to the "Universally Hated" achievement since you can no longer vote yourself, therefore it's technically impossible unless you've two HoPs, which is never the case in any standard setup we currently have, a la #78422.

**Comment by JohnFulpWillard** [comment]
They shouldn't be able to vote themselves even if it does show up in the UI because the ``ui_act`` code should prevent that

**Comment by Dorsisdwarf** [comment]
Wait, why can you not vote for yourself? That's a standard part of Mafia.

**Comment by Dorsisdwarf** [comment]
Oh i forgot, we dont run mafia we run town of salem, never mind.

**Pull request merged**
