### PR TITLE
Revert "Mekhi goes on the table"

### PR DESCRIPTION
**Pull request by silicons**
:(

### CODE REVIEW

**Comment by Buggy123** [comment]
no

**Comment by epicmemename** [comment]
no

**Comment by ACCount12** [comment]
no

**Comment by DaedalusGame** [comment]
no

**Comment by TheDreamweaver** [comment]
no?
no

**Comment by Thunder12345** [comment]
Get back on your table 

no

**Comment by deathride58** [comment]
He ded

**Comment by SgtxRootbeer** [comment]
No

**Comment by Xhuis** [comment]
As funny as this joke is, it *is* reverted for a good reason, because you are now able to table silicons which knocks them completely unconscious. I'm indifferent for the most part about passive tabling, but that in particular is an oversight that should be corrected.

**Comment by deathride58** [comment]
Emergent gameplay

**Comment by Iamgoofball** [comment]
Ah yes instant stun batons great design

**Comment by PKPenguin321** [comment]
This *should* go through but then we need to revert the old nerf to tabling stun times

**Comment by GunHog** [comment]
Am I a bad person for checking every new PR since the first one for when Kev would try to revert it?

**Comment by Hatterhat** [comment]
i ded pls restart

**Comment by Anonmare** [comment]
no

**Comment by MrStonedOne** [comment]
I was actually shocked my original pr got merged.

**Comment by Plapatin** [comment]
no

**Comment by Doppeltongue** [comment]
As funny as tabling kevinz is, passive grab tabling shouldn't have been merged in that state.

**Comment by Cyberboss** [comment]
I was surprised it took this long tbh

**Comment by F-OS** [comment]
add i ded tag

**Pull request merged**
