### PR TITLE
Families Update 1: Preference for roles, Space Cop Ballistics, Balance Tweaks, Fixes

### PR DESCRIPTION
**Pull request by Iamgoofball**
:cl:
balance: There is now a preference for Families Antagonist roles.
balance: There is now one Undercover Cop per Family.
balance: Police can no longer join Families. They will, however, fake join it if they use the induction package to get the uniform to stay undercover.
balance: The Space Cops are reminded that they are NOT Nanotrasen employees.
balance: Dead gangs or gangs with 1 member no longer count towards the auto-balance to avoid issues with AFK players or dead gangs limiting the rest of the active gangs.
balance: The Space Cops now have ballistic weaponry outside of 5 stars.
balance: The shuttle will now no longer take off in Families until after an hour and 10 minutes.
/:cl:

### CODE REVIEW

**Comment by Pumpkinoe** [comment]
is there a toggle for round-starting as a family member yet

**Comment by Pumpkinoe** [comment]
oh noooo
nononono
you took the non-lethal ability away from standard beat cops
now they have to shoot gang members to death and the AI will hate them

**Comment by Iamgoofball** [comment]
They have flashbangs and handcuffs.

**Comment by HomocidlePancakes** [comment]
**NOOOO YOU CAN’T SHOOT THE GANGERINO YOU ARE SUPPOSED TO STUN AND CUFF THEM NO YOU CAN’T DO IT YOU CAN’T!!!**

**Comment by trollbreeder** [comment]
flashbangs are for crowd control

give them a box of flashes for individual gangsters, or give them a riot dart toy SMG

**Comment by Pumpkinoe** [comment]
troll has the right idea
flashbangs can also affect the coppers themselves and are a lot less useful if you're trying to arrest like  one gangster

**Comment by LemonInTheDark** [comment]
I agree with troll, this seems like it would force cops into violent conflict resolution.

**Comment by Iamgoofball** [comment]
I'll give em batons

**Comment by trollbreeder** [comment]
Good enough, goof

**Comment by TheMidnightRose** [comment]
Question. Is it now possible to assign undercover cop via the Traitor panel?

**Comment by Iamgoofball** [comment]
All forms of police are ERT. Assign them as you would an ERT role.

**Comment by NanoCats** [comment]
Suggestion: please clarify what the space cops are to do (read:kill) gang members, there's been some confusion about things like lethal force. Especially on servers like Manuel.

**Comment by Iamgoofball** [comment]
I'm not spoonfeeding you exact instructions. Crack down on gang activity be it violent or non violent. It's up to the cops. Work with your Undercover Cops to figure out the preferred approach method.

**Comment by NanoCats** [comment]
> I'm not spoonfeeding you exact instructions. Crack down on gang activity be it violent or non violent. It's up to the cops. Work with your Undercover Cops to figure out the preferred approach method.

Got it, apply shotgun to face of anyone with a gang symbol, unga fucking bunga mate.

**Comment by Iamgoofball** [comment]
I've seen people do things non-lethally, and I've also seen people do things lethally. It's not impossible.

**Comment by Pumpkinoe** [comment]
i still don't like how nobody gets their objective put into their notes like what seems to be standard for objectives

**Pull request merged**
