### PR TITLE
Lets non-global href tokens work across rounds in the same day

### PR DESCRIPTION
**Pull request by Cyberboss**
Deterministic tokens based on ckey, cid, and date

### CODE REVIEW

**Comment by ShizCalev** [comment]
@Cyberboss compile

**Comment by AnturK** [comment]
Uh, doesn't this kinda defeat the point of them ?

**Comment by lzimann** [comment]
@Cyberboss 
also what @AnturK said

**Comment by Cyberboss** [comment]
Shit fix

**Pull request closed without merging**
