### PR TITLE
Revert "Reverts the PR that fucks travis"

### PR DESCRIPTION
**Pull request by Cyberboss**
Reverts tgstation/tgstation#40786

@kevinz000 fix pls

### CODE REVIEW

**Comment by Qustinnus** [comment]
this reminds me of that bee pr

**Comment by Cyberboss** [comment]
cursed remembrance

**Comment by TMTIME** [comment]
~~do it or im porting old ftls lag~~

**Comment by SpaceManiac** [comment]
do you actually want the unit tests to be failing or this an elaborate kevinz bait because if so he's said he doesn't receive github @ notifications

**Comment by Iamgoofball** [comment]
@SpaceManiac the bypass is you go yell at him on citadel

**Comment by SpaceManiac** [comment]
I have no more access to kevinz than you do

That said, the actual issues have been reopened, this PR doesn't need to be

**Pull request closed without merging**
