### PR TITLE
Supermatter Sword no longer gets bloody

### PR DESCRIPTION
**Pull request by swankcookie**
Fixes https://github.com/tgstation/-tg-station/issues/13157
please don't berate me if this isn't right.
I swear i tried my best.

### CODE REVIEW

**Comment by optimumtact** [comment]
Yay!

**Comment by Incoming5643** [comment]
I wouldn't be shocked if there was a var for things that shouldn't get bloody

**Comment by swankcookie** [comment]
full disclosure: i deleted all my local files and  Repo, and started over.

**Comment by swankcookie** [comment]
I couldn't find one

**Comment by optimumtact** [comment]
Surprisingly there isn't, but then I guess we've never needed it.

**Comment by Iamgoofball** [comment]
:+1:
Congratulations on your first PR. I hope you go on to make many successful ones in the future.

**Comment by swankcookie** [comment]
much thanks

**Pull request merged**
