### PR TITLE
[april fools] the buff we needed but you were all too afraid of doing

### PR DESCRIPTION
**Pull request by ghost**
buffs cleanbots

## Changelog
:cl: Cleanbot.
tweak: Cleanbot.
/:cl:

### CODE REVIEW

**Comment by adamkad1** [comment]
instamerge plz

**Comment by Ordonis** [comment]
No objections, make it permanent and make fluorosulphuric acid the normal cleaning agent

**Comment by GunHog** [comment]
Emagging that would be glorious...

**Comment by JJRcop** [comment]
The only way to stop them is the gibber

**Comment by Shadowflame909** [comment]
I guess Cleanbot is a megafauna now

**Comment by ATH1909** [comment]
New wiz meta: Acquire a robotics ID, turn off AI control for a cleanbot, put a pAI in said cleanbot, mind transfer into the pAI/cleanbot, then run around fireballing people while laughing at their puny attempts to kill/damage you.

**Comment by ShizCalev** [comment]
it's over anakin

**Comment by Suicidalpickles** [comment]
F

**Pull request closed without merging**
