### PR TITLE
Refactors dbcon into a subsystem

### PR DESCRIPTION
**Pull request by Cyberboss**
Orphaned procs for adoption!

@Jordie0608 

Datumized DBQuery and DBColumn too. I know this fucks with a lot of undocumented shit so it's gonna need approval

### CODE REVIEW

**Comment by Jordie0608** [comment]
It's a bit hard to be sure with the diff as it is but this shouldn't break anything, these are all implicit datums already iirc.

But...why?

**Comment by RemieRichards** [comment]
yeah um these are already datums.

**Comment by Cyberboss** [comment]
I can change them back to root objects if you guys have objections with them being "datums". @Jordie0608 this allows us to use subsystem/Shutdown to properly close the connection instead of just letting it die. Also it lets us create it before other shit that might use it.

**Comment by Jordie0608** [comment]
Was just wondering why make the change, I don't have objections (especially since there's no functional change).
And maybe then mention that in your PR nerd =P
That said we can already call `Disconnect()` as `Shutdown()` does so I don't really think that's a difference.

**Comment by MrStonedOne** [comment]
but, wouldn't moving the primary singleton to this allow admins to run arbitrary sql commands using atom proc call.

I suppose they always could if they could brute force the ref, but this just makes it a click away.

**Comment by Cyberboss** [comment]
It's already in GLOB. But yeah, I'll do that advanced proc call check before this is merged

**Comment by MrStonedOne** [comment]
add `[dnm]` to this for now so oranges can go all oranges on it

**Comment by Cyberboss** [comment]
Mergable after #26191

**Comment by Cyberboss** [comment]
Ready

**Pull request merged**
