### PR TITLE
Adds a new endround sound

### PR DESCRIPTION
**Pull request by ghost**
https://dl.dropboxusercontent.com/s/y17o5r997i6l4rp/leavingtg.ogg

Taken from http://sam.wileycomputerworks.com/SS13/

(I'm pretty sure @cuboos did these)

### CODE REVIEW

**Comment by ike709** [comment]
I like it

**Comment by GunHog** [comment]
You removed the best part! D:

**Comment by Steelpoint** [comment]
:+1:

**Comment by ike709** [comment]
After hearing the entire thing, I do agree with GunHog. You removed the best part.

**Comment by paprka** [comment]
These are meant to be relatively short

**Comment by Iamgoofball** [comment]
Re-add the full thing.

**Comment by TheVekter** [comment]
No, the whole thing is like 20 seconds and only moderately funny.

**Comment by paprka** [comment]
It's funny on its own without the baystation bashing.

**Comment by tkdrg** [comment]
Can you clear up the licensing with Cuboos? I assume he won't mind releasing it under a license we can use, I just want to be sure.

**Comment by Cuboos** [comment]
Uh... go ahead? i'm cool with it.

**Comment by TheVekter** [comment]
Doesn't get much easier than that. :+1:

**Comment by pudl** [comment]
haha this is great

**Comment by YotaXP** [comment]
I like the full thing, but I'd agree that the shorter version would be more appropriate for its role.

**Pull request merged**
