### PR TITLE
Adds Gondola and Tarzan Grenades

### PR DESCRIPTION
**Pull request by wesoda25**
## About The Pull Request

Adds Tarzan (which spawns 3 gorillas) and Gondola Delivery Grenades (which spawns 3 gondolas). Gondola is craft-able via 3 gondola hides and one empty grenade casing. 

## Why It's Good For The Game

Just some cool stuff. I'm gonna use tarzan for a later PR, got the idea for Gondola, and decided to make them into one together. 

## Changelog
:cl:
add: Gondola delivery grenade
add: Tarzan Grenade
:cl:

### CODE REVIEW

**Comment by MrDoomBringer** [comment]
??????

**Comment by wesoda25** [comment]
> ??????

yes umm hello maam what is it?

**Comment by MMMiracles** [comment]
this feels like a minecraft mod

**Comment by Shadowflame909** [comment]
I'd add one more thing to that gondola grenade, Teslium.


Frankenstein, it to make things come to life. That or strange reagent

**Comment by drderp3635** [comment]
>3 hide to make a grenade that can spawn the creatures to obtain 7 hide

**Comment by dr-bee** [comment]
Hides are worth a significant amount of dosh to cargo. This basically makes infinite money.

**Comment by wesoda25** [comment]
Yeah I never thought about that, one sec.

**Comment by Tlaltecuhtli** [comment]
not anymore, there is a chance of you getting a single use cargo bounty for the hide else they are worthless

**Comment by FantasticFwoosh** [comment]
Gondola Hides have value upon themselves Tlaltecuhtli, like xenomorph hides, just slap them inside a crate to send off, i dont think they were referring to the bounty.

- More grenades are great but this feels like scraping the bottom of the barrel, here's a on the fly gorilla grenade that's long-term availible but hard to get and properly regulate without it blowing up in your face as a experienced chemist/scientist without atleast cryo beakers & access to cubes.

```
        /datum/crafting_recipe/tarzangrenade
	name = "Rumble In-the Jungle Grenade"
	result = /obj/item/grenade/spawnergrenade/tarzan
	reqs = list(/datum/reagent/strange_reagent = 12
                                /datum/reagent/synthflesh = 12
                                /datum/reagent/blood= 12
                                /obj/item/reagent_containers/food/snacks/monkeycube = 12,
				/obj/item/grenade/chem_grenade)
	time = 60
	category = CAT_WEAPONRY
        subcategory = CAT_WEAPON

**Comment by Tlaltecuhtli** [comment]
oh i tought it was converted to a bounty a while ago? nvm

**Comment by wesoda25** [comment]
I don’t even want to make tarzan grenade craft able.

**Comment by wesoda25** [comment]
Also @FantasticFwoosh that recipe is far too easy, given it spawns 3 angry gorillas, who have a high chance of stunning each hit.

**Comment by optimumtact** [comment]
these make no sense and are weird.

**Comment by wesoda25** [comment]
reeeeeeeeeee but i need one for something I wanna do later

**Pull request closed without merging**
