### PR TITLE
Small audio fixes

### PR DESCRIPTION
**Pull request by actioninja**
## About The Pull Request

pitch of the pda/newscaster/etc beep has been fixed
incorrect grenade arm sound has been corrected
flesh impacts have been fixed to not be a weird thunk for small bullets

## Why It's Good For The Game

fix bahg

## Changelog
:cl:
soundadd: PDA beep, grenade arm, and flesh impact sounds have been fixed
soundadd: When you get a quick rundown, your ears bleed less.
/:cl:

### CODE REVIEW

**Comment by Tlaltecuhtli** [comment]
i think the beeping effect was too loud, does it fix that?

**Comment by actioninja** [comment]
> i think the beeping effect was too loud, does it fix that?

It wasn't any different in volume. Perceived volume differences due to differences in pitch yada yada yada.

**Comment by optimumtact** [comment]
please for the love of christ reduce the volume on the bogdanoffs

**Comment by actioninja** [comment]
> please for the love of christ reduce the volume on the bogdanoffs

he bought?

**Pull request merged**
