### PR TITLE
darkens grey jumpsuits

### PR DESCRIPTION
**Pull request by dannno**
Thanks everyone for coming to me with your constructive feedback

before after whatever

pissant

### CODE REVIEW

**Comment by chanoc1** [comment]
looks good <o/

**Comment by PKPenguin321** [comment]
no just put the old sprite please

**Comment by chanoc1** [comment]
re

**Comment by dannno** [comment]
no, the old sprite is poorly made

**Comment by PKPenguin321** [comment]
no you are

**Comment by dannno** [comment]
someone please merge so people can stop screaming

**Comment by chanoc1** [comment]
^+1

**Comment by ChangelingRain** [comment]
constructed feedback tm

**Comment by Haevacht** [comment]
Why not voice your dislike when he asks for feedback, dicknogglers.

**Pull request merged**
