### PR TITLE
Fixes some problems with some virology symptoms

### PR DESCRIPTION
**Pull request by ATH1909**
## About The Pull Request

17 days ago, I made this PR: https://github.com/tgstation/tgstation/pull/45741.

15 days ago, I made my last comment in that PR (before cobby posted in it, at least).

3 days ago, cobby reviewed my PR, suggesting that I make sure that the symptoms won't make people who are EXTREMELY confused, dizzy, etc. LESS confused, dizzy, etc. I received no pings or other notifications that he had reviewed my PR.

2 days ago, oranges closed my PR for being "stale", which prevented any of my future changes to the virologypatch branch that I had made from showing up in my PR's "Files changed" section.

This PR is literally just my previous PR, but with CLAMPs used instead of mins (which should fix the issue that cobby asked me to fix/deal with).

If you want to see a proper "About The Pull Request" section about/for this PR, go see the one in https://github.com/tgstation/tgstation/pull/45741.

## Why It's Good For The Game

If you want to see a proper "Why It's Good For The Game" section about/for this PR, go see the one in https://github.com/tgstation/tgstation/pull/45741.

## Changelog
:cl: ATHATH
tweak: The confusion symptom now noticeably confuses you.
tweak: The confusion symptom's transmission 6 threshold effect now actually affects how much the symptom increases your confused value by (instead of affecting the cap that the symptom can bring it to, which is plenty high enough by default).
tweak: The dizziness symptom now actually makes you noticeably dizzy (and has a cap for how dizzy it can make you).
tweak: The dizziness symptom's transmission 6 threshold effect now makes your screen look "druggy" all of the time (only once its virus reaches a high enough stage, of course), instead of only occasionally.
tweak: The hallucigen symptom's stealth 4 threshold effect now continues to give you positive messages instead of bad ones at stage 5. Before this tweak, meeting that stealth threshold would actually cause bad messages to appear MORE often at stage 5 than if you hadn't met it.
tweak: Pretty much completely reworked the narcolepsy symptom so that it now uses the "drowsyness" (yes, that's how it's spelled in the code; no, I don't know why it's misspelled like that in the code) status effect instead of a confusing mess of ticking counters that rarely actually put you to sleep.
tweak: The narcolepsy symptom's transmission 7 threshold effect now only requires transmission 4 no longer causes its virus to occasionally deal negligible amounts of stamina damage. Instead, it now causes the host to periodically yawn, spreading its virus whenever they do so.
tweak: The narcolepsy symptom's resistance 10 threshold effect is now a stage speed 10 threshold effect.
tweak: The narcolepsy symptom's activation frequencies have been tweaked a bit to make the symptom less threatening (albeit still quite potent) without its stage speed 10 (formerly a resistance 10) threshold effect.
balance: The nacrolepsy symptom now adds 0 to its virus's transmission stat (upped from -4).
fix: Fixed a bug that could cause the confusion symptom to lower your confusion value if you had a high confusion value when it activated.
/:cl:

### CODE REVIEW

**Comment by wesoda25** [comment]
Bro u gotta work on your pr names

**Comment by ExcessiveUseOfCobblestone** [comment]
fix your github notifications bro

**Comment by ExcessiveUseOfCobblestone** [comment]
Also my review applies here as well since it wasn't fixed.

You cannot cap confusion/dizziness/etc. from the mob on the virus because these viruses do not have exclusive access to manipulating these variables (AKA other sources exist).

If you want to make a GENERAL cap that's fine, although that should be for a separate PR since, again, not exclusive to viruses.

**Review by ExcessiveUseOfCobblestone — CHANGES_REQUESTED** [review]
^^

**Comment by ATH1909** [comment]
> Also my review applies here as well since it wasn't fixed.
> 
> You cannot cap confusion/dizziness/etc. from the mob on the virus because these viruses do not have exclusive access to manipulating these variables (AKA other sources exist).
> 
> If you want to make a GENERAL cap that's fine, although that should be for a separate PR since, again, not exclusive to viruses.

So the virus is not allowed to set these variables to specific values?

I see; I'll go edit the PR (again) now.

**Comment by ATH1909** [comment]
... Wait a minute.

So, uh, funny story: Some people in the #coding_general section of the Discord server finally convinced me to delete and remake my tgstation fork so that my new PRs wouldn't have extremely long commit lists anymore.

Unfortunately, this means that the virologypatch branch doesn't exist anymore. While it's fortunately still present here in this PR, I can't seem to actually EDIT it (it's named "unknown repository" now).

This, uh, could be a problem, especially since I recently made another PR (the plasma fixation one) that might also need some edits in the future.

**Comment by ATH1909** [comment]
So apparently, I was supposed to delete my master BRANCH, not my entire fork.

Welp. I now can't edit this PR or my plasma fixation PR, and will likely have to remake them in a new branch (unless you can still use your maintainer powers to alter this PR?).

https://www.youtube.com/watch?v=Ag1o3koTLWM

Will the closure of this PR delete the code in it, or will it still be accessible even if this PR is closed?

**Comment by ExcessiveUseOfCobblestone** [comment]
you can pull commits but you can't pull the branch (because it doesn't exist anymore).

**Comment by ExcessiveUseOfCobblestone** [comment]
This PR can be remade btw, I closed it because it needed changes that you can't make.

**Pull request closed without merging**
