### PR TITLE
Adds a json validator to travis

### PR DESCRIPTION
**Pull request by lzimann**
Now that we are using JSONs, it's a good idea to have a check and validate them.

### CODE REVIEW

**Comment by optimumtact** [comment]
please dont' use a node dependency, I want node gone

package a local copy.

**Comment by optimumtact** [comment]
@lzimann please

**Comment by AnturK** [comment]
Please, we already have to use npm for tgui, and that's not going away any time soon. If you're worried about delays add a travis cache for this.

**Comment by lzimann** [comment]
Yea I am going to change this for a python script later.

**Comment by lzimann** [comment]
I'll get to this one day

**Comment by Cyberboss** [comment]
>one day

**Pull request closed without merging**
