### PR TITLE
lobby image

### PR DESCRIPTION
**Pull request by epicgamerben**
me big dumb boy

### CODE REVIEW

**Comment by Qustinnus** [comment]
nice

**Comment by nemvar** [comment]
Offical sequel to https://github.com/tgstation/tgstation/pull/44540

**Comment by MacBlaze1** [comment]
Why dont you follow the proper format. I could get behind this if he did, but he doesnt and on top of his title he changes other parts of the code. He doesnt expect people to read the code. SAD!!!! 😂 👀

**Comment by Qustinnus** [comment]
@MacBlaze1 he accidentaly PRed to the TG repo, he was most likely trying to PR to his own.

**Comment by PKPenguin321** [comment]
This has nothing to do with lobby images what the heck

**Comment by Fikou** [comment]
even if it was for a different place
>changing runtime's name

**Comment by cacogen** [comment]
wholesome pr, very nice lobby image erased in edited op too

**Pull request closed without merging**
