### PR TITLE
Revert "DCS Continued"

### PR DESCRIPTION
**Pull request by MrsTonedOne**
Reverts tgstation/tgstation#29324

Undocumented changes in pr.

Seriously @optimumtact what did you think would happen.

### CODE REVIEW

**Comment by Qustinnus** [comment]
this is gonna go on for weeks and I'll never be able to continue on my project. this makes me a sad panda.

**Comment by MrStonedOne** [comment]
You are free to take the changes and make your own pr with proper documentation in the pr body about what the change does.

Its super easy to do.

**Comment by ike709** [comment]
Watch as MSO falls from grace in this latest installment of SS13 drama.

**Comment by MrStonedOne** [comment]
Here's the thing: If getting contributors to specify what their prs do in the pr body is my fall from grace, then ss13 doesn't deserve me.

This is such a basic fucking requirement that it shouldn't have ever gotten to this point.

**Comment by ChangelingRain** [comment]
I don't disagree, but I think you're going about it in such a way that you're just going to get mocked at every turn.
Like, tell them to do the thing, no other conditions, and if they don't just close the PR.

**Comment by lzimann** [comment]
To be fair, it is what he did, pr was merged regardless though.

**Comment by Jalleo** [comment]
This is where I feel MSO is in the right especially since its something maintainer should stick to.

**Comment by Cyberboss** [comment]
The desc for the previous PR was updated, can we end this now please?

**Comment by dannno** [comment]
i mean just imagine how this would have gone if instead of being hostile and combative from the outset, you just asked the OP politely to properly document their changes

like
think about it maybe

**Comment by MrStonedOne** [comment]
I mean, just imagine how shit this codebase would be if people were just given a free pass to disobey the guidelines because somebody didn't dot their Is and cross their Ts and kiss between both cheeks.


like
think about it maybe.

**Comment by dannno** [comment]
what about what I said was any kind of justification for that behaviour

**Pull request closed without merging**
