### PR TITLE
[s]I'll build my own cid randomizer detector! with blackjack! and hookers!

### PR DESCRIPTION
**Pull request by MrsTonedOne**
CID randomizer detector, non-~~stolen~~ported edition!

Closes #20056

When a user's cid doesn't match their last cid, we open a new game window to the server, and close the old one, if it changed again, we disallow the connection.

They are free to try again once they remove the randomizer dll.

Admins are notified on first match for the user, and it will leave a note on the user as long as it hasn't left one recently.

It is a config, defaults on, but requires db before actually activating.

### CODE REVIEW

**Comment by RemieRichards** [comment]
does this drop them every time their CID changes? I was worried because mine likes to jump around a lot on it's own (or did last I checked the DB), but I saw the admin rank skip, so I know -I'm- safe.

**Comment by MrStonedOne** [comment]
You only have one cid in the database remie.

**Comment by RemieRichards** [comment]
wat.

**Comment by MrStonedOne** [comment]
your ip has a lot of variance, but that's to be expected.

**Comment by RemieRichards** [comment]
weird, guess I was wrong.
Carry on then.

**Comment by MrStonedOne** [comment]
Made the reconnect automatic.

**Comment by Shadowlight213** [comment]
I guess denying connection is better than a ban.
Would be nice if it automatically placed a note on them so admins could know something was fishy.

**Comment by MrStonedOne** [comment]
This has been test merged on sybil for about an hour, so far one catch, and they removed it so they could play.

I'm gonna look at expanding it to a config, and add a note about it (with a cooldown)

**Pull request merged**
