### PR TITLE
Removes smugglers satchels

### PR DESCRIPTION
**Pull request by lilacrhododendron**
:cl: 
del: Smuggler's satchels have been removed from the game.
del: The Miracle ruin has also been removed from the game, because it was disabled and it used Smuggler's satchels.
/:cl:

Closes https://github.com/tgstation/tgstation/pull/42170
This item is broken in principle. It enables people to have access to things they should never have been able to acquire within a round. This item is never used for anything interesting, it is just used to get wizard spellbooks and captain's spares and weapons at roundstart in any round with no effort required. It circumvents any IC obstacle by hiding it behind the "random chance" of the satchel spawning. It doesn't matter how many times this item is "fixed" or nerfed, being persistent is bad on principle.

### CODE REVIEW

**Comment by Razharas** [comment]
Round-separation is not a setting, its a game type we have thus any kind of "carrying over" from one to another is strictly bad design

**Comment by RogueSteampunker** [comment]
I'd like to remind everyone that the case Subject is basing this off of is entirely reliant on a wizard having gotten a smuggler's satchel, stowing their book, and potentially finding it later.

It rolls on a random basis, and there's a good chance an item you placed is never gonna show back up for you cause of bad luck. There is a million factors that have to align, and we're attempting to suddenly remove the goddamn item after it's been in the code for years cause it happened once. We're making a mountain of an anthill.

**Comment by subject217** [comment]
lol

**Comment by Kierany9** [comment]
>make useful if uninteresting traitor item that lets you hide shit under floorboards
>somebody adds persistence to said item, whose main point was never persistence
>hurr let's remove it

every time
it's almost as bad as when the c90 got removed because people couldn't stop messing with the SAW and suddenly you've got two guns with similar price, role and damage output, so the solution taken was to remove the actually interesting gun instead of the one nobody had any idea what to do with

**Comment by subject217** [comment]
fun fact kierany i actually rebalanced and re-added the m90 to the uplink again

**Comment by coiax** [comment]
I'll just make a PR to straight up remove the persistence.

**Comment by necromanceranne** [comment]
Smuggler satchels can be gamed in a reliable way, so long as you are the only person doing so. This means a few individuals can quite easily ensure they get the satchels they want, and a few people have been doing that for a while.

It's not been particularly egregious short of a few really notable instances of it. One being someone getting a scrying orb and finding every single cultist in a round with perfect precision because they could go ghost and find them all. I was chaplain that round, so I got to sit front seat and even do some ghosting myself.

If enough people were willing to use the satchels regularly enough they could dilute the pool and screw up the people gaming them. But there isn't so it doesn't happen.

**Comment by Teepeepee** [comment]
I always make sure to replace smuggler satchel's contents with my favourite adult section books, I'm doing MY part!

**Comment by coiax** [comment]
Books won't even transition properly across with smuggler's satchels anyway

**Comment by FloranOtten** [comment]
this specific example happened exactly once and is unlikely to happen ever again. The randomness ensures that you will rarely get anything good and if this is such a problem, #42170 is a FAR better solution.

**Comment by necromanceranne** [comment]
Actually, due to a multitude of reasons, namely because they were persisting over multiple rounds, the person could actually get it multiple times. They also got spellbooks on multiple rounds too.

It doesn't work like that anymore but it was, as I said, able to be gamed because nobody else was using them.

**Comment by kriskog** [comment]
The more moderate solution to removal of either satchels or persistence, is using the built in replacement system to prevent problematic items from carrying over. Simply add a "persistence_replacement = replacement/typepath" to the item.
This is already the case for nuke disk which gets replaced with a fake, and takes minimum effort.

Why? I find satchels to be interesting, and they are just one of those unique things you can play with to break the monotony. 


Of course, this PR does nothing really since 9-10 empty satchels spawn on the station every round and those are the most common ones used to hide shit.

**Comment by subject217** [comment]
it's really one particularly bad example in a long line of abusive examples.

the real point is that smugglers' aren't used for ANYTHING else. just this sort of shit. they only ever make the game worse, unless you're the powergamer who is abusing it. at any rate, coiax's PR is objectively superior so.

**Comment by AdamElTablawy** [comment]
i've routinely seen one mime buy a ton of smuggler's satchels every tot round and stuff them in random places then load them up with as many guns and traitor items as they can get their hands on and then immediately routinely check all their satchel spots constantly for free loot 

it's kind of stupid because they get traitor shit and free all access constantly because of it

**Comment by HomocidlePancakes** [comment]
I haven't actually bought satchels once as traitor. I just found the empty ones on station. There are like 9 of them and only 1 as stuff in it so it's not hard to find. I just get a fuckton fo satchels on my non-antag rounds, then i powergame my ass to get loot and stash it. End up stashing around 4 good items per round.

**Review by Cyberboss — CHANGES_REQUESTED** [review]
Remove ALL satchel code. You left in the SSpersistence stuff and the actual item

**Comment by subject217** [comment]
Yah, in case someone wants to rework it. But if you say so. I think https://github.com/tgstation/tgstation/pull/42170 is a better solution but I'll still update this PR.

**Comment by PKPenguin321** [comment]
RIP, these things were great for stashing your steal objective

**Comment by Incoming5643** [comment]
In the future if there's a problem with one of my legacy projects and people remember it was one of mine I'd appreciate the mention. Disappointed to see this go, but I am happy that it found enough use to force the conversation.

The undertone of salt here feels pretty thick though. Rare occurrences are things that keep the game fresh to even the most jaded veteran, you shouldn't try to quash them!

**Pull request merged**
