### PR TITLE
Slung improvised shotgun now properly updates its sprite.

### PR DESCRIPTION
**Pull request by harmonyn**
Fixes https://github.com/tgstation/-tg-station/issues/12576.

there's probably a less dumb way to do this

### CODE REVIEW

**Comment by Zilenan91** [comment]
Wow how was this bug even found

**Comment by bgobandit** [comment]
I would guess by someone trying to saw off an improvised shotgun they were slinging

**Comment by Zilenan91** [comment]
No I mean how did they even get an improvised shotgun

**Comment by bgobandit** [comment]
top tier acts of assistantry

**Pull request merged**
