### PR TITLE
Restricts Romerol to medical roles

### PR DESCRIPTION
**Pull request by ghost**
:cl: Xhuis
tweak: Romerol can now only be purchased from the uplink by medical staff. The price has been reduced to 20 telecrystals to compensate.
/:cl:

Non-medical roles were very unlikely to get use out of the virus, as they lacked an effective delivery mechanism and it was difficult to find a subject to pool telecrystals with. Now zombies can be traced back to medical, but not to just the virologist, and they don't rely on another person to be lucky enough to help.

It should be noted that I was not around for the brief stint of 20-TC Romerol. If this was removed for a _very_ good reason, then I'll increase the price.

### CODE REVIEW

**Comment by anconfuzedrock** [comment]
yea that makes it better heres a better idea remove romerol

**Comment by Xhuis** [comment]
Something something emergent gameplay

**Comment by Grazyn** [comment]
Meh, what about botanists and their Romerol bees

**Comment by kevinz000** [comment]
bad chemical please don't.

**Comment by jughu** [comment]
@xhuis could you keep romerol for the non medic at 25 because requiring 5 extra tc or a discount or cargo requires a little effort

**Comment by FantasticFwoosh** [comment]
Obviously traitor cooks aren't putting it on food with shittons of bites required or require forks (omlettes)
OR
Aren't putting it on food that can be sliced to infect multiple people at once.

Put this down to lack of player competency rather than squirrel it away where people will forget it. Medical chems are under more scrutiny and suspicion rather than a vaguely invisible extra topping on food.

**Comment by Xhuis** [comment]
@jughu I tried to let other people use these items for a cost, over and over and over, but it got rejected and I had to merge it as-is.

@FantasticFwoosh Wow, I actually never considered that. Maybe I'm the incompetent one here.

Given the feedback I've received I'm tempted to close this and might do so at some point.

**Comment by RemieRichards** [comment]
Just leave it alone.

**Pull request closed without merging**
