### PR TITLE
Virtually Visualized Microwave Holodeck Hell

### PR DESCRIPTION
**Pull request by san7890**
## About The Pull Request

Hello there,

Do you ever wake up and find yourself thinking: I need more microwaves? Well, look no further.

image

Now, you have a holodeck full of them! Enjoy!

## Why It's Good For The Game

Sometimes you really need a microwave, you know? Adds interesting flavor to the holodecks, and helps assuage the people who _need_ that microwave fix.

## Changelog

:cl:
add: Nanotrasen has installed a new holodeck subroutine, cleverly termed: Microwave Paradise. Enjoy those microwaves.
/:cl:

### CODE REVIEW

**Comment by ArcaneDefence** [comment]
image

**Comment by nianjiilical** [comment]
is it at all possible to add a new ambience sound purely for this holodeck thats just deafening microwave noises

**Comment by san7890** [comment]
> is it at all possible to add a new ambience sound purely for this holodeck thats just deafening microwave noises

you could overlay whatever sound WHZHZHZHZHZ calls into a new .ogg file and create new ambience based off that, but i don't know how to apply it to the holodeck area when this is loaded in specific. funny thought though

**Comment by Mothblocks** [comment]
you can/should make it so the microwaves just randomly turn on, and turn on so frequently that youre mostly just hearing them constantly turn on and finish

most crucially, they would not be synchronized with each other

**Comment by Mothblocks** [comment]
and if you dont im going to

**Comment by Shadowflame909** [comment]
Remember when you could put meat in the microwave and it'd come out as a steak?

Memories...

**Comment by san7890** [comment]
> you can/should make it so the microwaves just randomly turn on, and turn on so frequently that youre mostly just hearing them constantly turn on and finish
> 
> 
> 
> most crucially, they would not be synchronized with each other

I have no idea where to even start on that code-wise.

**Comment by MrDoomBringer** [comment]
image

**Comment by san7890** [comment]
The microwave loops infinitely if you just call the whzhzhz proc so I added a 95% chance to that run forever on Initialize.

**Review by Maurukas — APPROVED** [review]
Only about two of the microwaves are usable due to the auto activation, but standing in the middle of this is an experience.

**Comment by Mothblocks** [comment]
@san7890 No the point is for it to keep going Ding Ding Ding unsynchronized from each other, if they're just ON that's boring

**Comment by Mothblocks** [comment]
I will fix this

**Pull request merged**
