### PR TITLE
Resprites the Heretic Flesh Blade

### PR DESCRIPTION
**Pull request by Tramzz**
Gives the Flesh path a new and improved blade, comes with a custom animation.

## About The Pull Request
Resprites the flesh blade to give it more charm and make it a little more similar to the existing blades. Also gives it more personal twists such as an animation for the eye to make sure its not too similar. Has now been updated so that the handheld sprites are more consistent with the flesh blades new design!

Old:
image

New:
image

Featuring an all new animation by me:
new_flesh_blade

Main inspiration is pulled from the game the idea for heretics came from, **Cultist Simulator**. More specifically, the design is very much inspired from this specific lore segment from the Heart principle: "**One who watches does not sleep, one who sleeps watches not.**" Also inspired by the in-game lore referring to the blade as alive, hence the new animation.

## Why It's Good For The Game
Makes the flesh blade more visually appealing and more defined in comparison to the old blade design. 

## Changelog

:cl: Tramz
imageadd: Adds new icons and a new animation for the Bloody blade.
/:cl:

### CODE REVIEW

**Comment by Miczu555PL** [comment]
Fat inhand sprite.

**Comment by Jackal-boop** [comment]
with all these new sprites. maybe we should rename the blades to "crescent blades"? it would be a bit more fitting

**Comment by Jacquerel** [comment]
I think the eyes are maybe a little big on the inhand sprite, but it’s nice nevertheless.

**Comment by Tramzz** [comment]
> with all these new sprites. maybe we should rename the blades to "crescent blades"? it would be a bit more fitting or maybe sickles

Yea I think that would be fitting honestly. Not sure if the other blades would need touched up though if something like that does happen. 


> I think the eyes are maybe a little big on the inhand sprite, but it’s nice nevertheless.

I can probably go back in and edit the size of the eyes once I'm home tonight. The size of the eyes appear to be closer to the old blade which is why it looks wonky.

**Comment by Tramzz** [comment]
Apologies for letting this get stale, have been extremely busy with IRL matters, I need to have the icebox test rerun and then it should be good to go.

**Comment by Imaginos16** [comment]
nice

**Pull request merged**
