### PR TITLE
Fix police and telebatons ignoring shields

### PR DESCRIPTION
**Pull request by Lobachevskiy**
Fixes https://github.com/tgstation/-tg-station/issues/14713

Had you awful people done this before today I would not have died during my Phantom Cancer round. I didn't even manage to farm Diffusal Blade. Feel free to add i ded tag.

### CODE REVIEW

**Comment by Lobachevskiy** [comment]
Ideally batons should be refactored - the separation to .../melee/baton and .../melee/classic-baton doesn't seem to serve any purpose other than creating bugs like this. But it is half past 3 am and I'm not gonna do it now. May be in a couple of days.

**Comment by Shapsy** [comment]
So what's the best way to beat someone with a riot shield now that they're stronger against melee and projectiles?

**Comment by Lobachevskiy** [comment]
If you mean stuff that negates shields, then it's slips, grenades, chemicals, gases, fires. Basically anything that doesn't attack directly. Also armor penetrating weapons, don't know which weapons have that, but some might, it reduces the chance of block. Or just spam your attack, unlike reactive armor, shields have no penalty for being blocked with it.

**Comment by Steelpoint** [comment]
Last time I checked basic Riot Shields only had a 50% projectile blocking rate.

**Pull request merged**
