### PR TITLE
Fire will now impair or inhibit many changeling abilities, and will affect them more intensely (also adds a sound for mobs igniting!)

### PR DESCRIPTION
**Pull request by ghost**
:cl: Xhuis
add: Changelings can now purchase the Thoughtsteal evolution, which allows them to see the memories of anyone they sting. The victim will be notified of it within one minute after the initial sting.
balance: Many changeling abilities are now inhibited or crippled by fire, including Revive, Strained Muscles, and others.
soundadd: Mobs catching on fire now plays a sound.
/:cl:

With the Fleshmend nerf establishing a thematic sense of fire weakness to changelings. I decided to expand on it by making fire affect them more harshly. Now, being on fire will affect changelings in the following ways:
* Arm Blade, Organic Space Suit, and other "body-morphing" abilities are unable to toggle while on fire, meaning that if you have an arm blade you cannot cancel it and vice-versa
* Adrenaline Sacs will cause confusion when on fire
* Revive will not extinguish fires, and you will revive with 50 burn damage
* Strained Muscles will gain stacks twice as fast and each stack will have twice the effect while on fire
* Fire affects changelings around ~40% more in terms of temperature

Also adds a sound that plays when mobs ignite. In addition, changelings will receive a different message and a local sound to reflect their newfound fear of flames:
Normal: **"You're set on fire!"**
Changeling: **"FIRE! OUR SKIN! PUT IT OUT! *PUT IT OOOUT!"***

I also added a new ability, called Thoughtsteal, that lets the changeling view the memory/notes of anyone they sting, giving them a notice of the sting anywhere between 30 and 60 seconds afterwards.

Suggestions on individual abilities and quirks are welcome!

### CODE REVIEW

**Comment by Buggy123** [comment]
This should all check to make sure the ling isn't wearing fireproof clothes.

**Comment by Xhuis** [comment]
I ensured that Fleshmend still didn't work while they had fireproof clothes on for the same reason I did here; making them not take the drawbacks from fire if they have fireproof clothing is only a band-aid fix, because they can acquire that clothing and continue their murderbone, but this time they also light people on fire by walking into them. It can be fluffed as their primal fear of fire disrupting their thought and shapeshifting ability, but it's primarily for balance.

**Comment by Buggy123** [comment]
I mean, completely fireproof clothes aren't actually that common. Unless firesuits actually protect against all damage from burning, but last i checked they didn't.

**Comment by XDTM** [comment]
I'd go with consistency over balance here. Imagine playing as a ling, feeling clever because you thought to break into atmos to get the fireproof suit, only to find out later it didn't protect you and losing a fight because of it.

Also, unlike shadowlings, that had light as a balancing trait from the start, lings have been fought so far without them being weakened by fire, so they won't be unbeatable even if they use fireproof clothing.

**Comment by Xhuis** [comment]
My main reason for making the PR to begin with is because changelings have no real weakness, downside, or drawbac.k They are, simply put, better traitors; it rewards thoughtless play due to their heals, stun recovery, inability to die permanently, and undetectable arm blades. If I was to make fireproof clothing protect from the downsides, then I would need to include some other drawback.

The alternative is to give more generalized nerfs to changelings to bring them in line with other antagonists, but I thought that taking them as they are now and applying large drawbacks to them would be more interesting to try.

**Comment by XDTM** [comment]
I agree with those points, but a suit that protects against fire should not let it pass regardless of who's wearing it.
A better way to avoid that would be either adding another limiting factor, or making it so prevention costs something else. That cost, in this case, is time (slime potions) and/or movement speed (firesuit, hardsuit).

That said, i think the ideal way to tacke the changelings' nigh-immortality would be to give them a limited resource, biomass, to use their skills with, especially revival. Eating would be a safe, but slow, way to replenish it; eating corpses would replenish it greatly, and fire would consume it at a rapid rate. That way lings can't just chain revive until they manage to escape, as they'd rapidly deplete their biomass; you could keep shooting a rogue ling to death, although it would still be much harder than a normal human.

**Comment by KorPhaeron** [comment]
Changelings are the only remotely scary solo antag, giving an auto win button that turns off all their powers is kind of dull

**Comment by Xhuis** [comment]
They have the potential to be scary, but right now they're more or less unstoppable killing machines with a built in hivemind and the inability to die permanently unless you destroy their body in ways that other changelings can sabotage via cutting power, etc. A weakness to fire doesn't make them terrible - they're still powerful in the right hands - but it allows people to have a way to defend themselves when the changeling would otherwise use their inbuilt, unremovable, concealable armor, arm blade, and stun removal to win against everything.

**Comment by ma44** [comment]
breaking news: local powergamers seen lighting everyone on fire with a zippo lighter to find out if they can acquire ling valids.

**Comment by Spaceinaba** [comment]
@KorPhaeron not to be that guy but like lings are not solo antags there are 5-6 of these fuckers like every round they show up

**Comment by Armhulen** [comment]
@Xhuis if you want them to have downsides while still staying top dog antag, finish thingling!

**Comment by Jordie0608** [comment]
What is the source of the ignite oggs?

**Comment by bunny232** [comment]
https://www.youtube.com/watch?v=i0IAwe_mxSY

**Comment by GuppyLaxx** [comment]
cool, time to bust out my clf3 spray and flamethrower, fire is the new meta :DDDD

**Comment by PKPenguin321** [comment]
Fuuuuuck i need to hurry up and finish my changeling overhaul thing

**Comment by Kawaii-Big-Boss** [comment]
It has been thirty thousands years, but it finally happened. Someone actually nerfed changelings in a way that isn't secretly a buff, and gave them an actual counter.

**Comment by KorPhaeron** [comment]
@xhuis

If you really think they are invincible this is the absolute worst way to go about changing that

They win if you dont have X item that counters all of their abilities, you lose if you dont have X item

The last fire PR gave you an edge for being well prepared, this one fully cripples the ling and determines the fight

Where is the fun in that?

**Comment by Xhuis** [comment]
My intention here isn't to make changelings annihilated by and completely unable to counter fire. They can still just carry an extinguisher on them. My main goal is to give them something to actually fear!

For normal antagonists, that's stuns, deadly chemicals, mobs of people, and the like. Changelings have to worry about none of those. This weakness to fire gives them something that they *can't* laugh off, because it makes them mortal, like werewolves to silver bullets. The only ability made completely nonfunctional by fire is toggling mutations like the arm blade. I don't intend to make them completely useless on fire, which is why I still let them *use* their super powerful abilities like removing all stuns, I just give them a drawback. Like the Thing, fire is meant to make them fearful and lick their wounds if it's used against them, rather than keel over and find themselves sitting in front of an oncoming labor shuttle.

If you think this doesn't do that well, then I'm welcome to hear your thoughts on how it could be made more into that.

**Comment by KorPhaeron** [comment]
I had a pr I never finished about cancelling their revive stasis while on fire which mitigated the most obnoxious part of lings (they smashed the gibber gg) without making them run in circles if they try and use their escape, if you are interested in that

**Comment by Xhuis** [comment]
I remember you closed that. I can redo it, but what induced you to stop working on it that I should know about?

**Comment by Kawaii-Big-Boss** [comment]
R.I.P. the dream
killing self 2

**Pull request closed without merging**
