### PR TITLE
fixes everyone being able to meow [no gbp]

### PR DESCRIPTION
**Pull request by grungussuss**
## About The Pull Request
so turns out `/datum/emote/living/basic/pet/cat/meow` doesn't work the way I thought
## Changelog
:cl: grungussuss
fix: fixed all mobs being able to meow
/:cl:

### CODE REVIEW

**Comment by Hardly3D** [comment]
Soul removal

**Review by ZephyrTFA — APPROVED** [review]

**Comment by EuSouAFazer** [comment]
And on that day, TGStation was given a grim reminder

**Comment by carlarctg** [comment]
they just use their mothus to mmeow like how people use their mouths to scream its canon

**Comment by DATA-xPUNGED** [comment]
Ah, this PR reminds me of a great novel by a famous writer, George Orwell if i recall it. I think the book was called... 1984...

**Review by Likteer — CHANGES_REQUESTED** [review]
That's uncool don't do that

**Pull request merged**
