### PR TITLE
[centcom] Centcom Expansion And Private Security Force

### PR DESCRIPTION
**Pull request by Steelpoint**
This PR sees two additions.

Firstly, some areas of Centcom have been expanded to help give the illusion that the station is much larger than what you can access, this is done in areas the player cannot normally access, and is detailed below.

Secondly, some NT Private Security Officers have been stationed around the docking area for incoming escape ships. These officers will only open fire IF they themselves are attacked, however once the order to fire is given they will open fire on anyone and everyone they see. They will also summon backup when attacked, so all nearby officers will be alerted and converge on their position. 

In addition, these Officers will not move unless attacked. Furthermore the officers who are unarmed have a much smaller visual range, but they'll still come to help if summoned from a alert.

The only areas these Officers spawn in are the docking area and a few in a inaccessible area near the ERT ferry area. 

-----

Areas that have been added.

Also of note, any extra ships or shuttles seen are non-functional, and are just for decorative purposes.

Docks

ERT Ferry

Centcom Cargo

-----

If you have any suggestions for other additions to Centcom, either from more Private Security/Non-Sec NPCs or from further expansions. Feel free to suggest them.

Thanks for reading.

-----

:cl: 
add: Central Command has seen some minor expansion, more so to help give the illusion that Central Command is a extremely large space station.
add: Central Command has seen fit to station armed Security Officers at Centcom docks. These officers are authorised to employ lethal force.
/:cl:

### CODE REVIEW

**Comment by PKPenguin321** [comment]
Map expansions look good but I'm not sure why we're putting mobs in there

**Comment by Steelpoint** [comment]
Helps make Centcom look actually populated.

I'm half tempted to fill it with non-hostile NPCs but I think just a few Security Officers at the entrance is best, since 99% of the time people will only be in the docking area.

**Comment by KingPhilipIII** [comment]
I'm more or less in favor of the fluff, but I feel like bloating Central further considering very little of it is actually utilized just puts more strain on the server for little benefit outside of ghosts watching or the very rare admemes on Central. 

One has to wonder what a station constructed in CentComm style would be like to play on though. Yknow. Maximum security facility.

**Comment by Steelpoint** [comment]
The main areas I'm expanding are common areas that players will see even during the normal course of events.

The docks since 99.5% of rounds end here, baring the exception of a traitor hijacks the shuttle, also the ferry area since ERTs/Deathsquads will spawn here.

**Comment by Steelpoint** [comment]
Pushed a minor update, these new Officers are now apart of the 'nanotrasenprivatesecuirty' faction, meaning they are also allied with their far more aggressive counterparts.

In addition, I've added a in game cyro sleeper spawner that lets ghost spawn in as Nanotrasen Private Security Officers, given the full loadout and Centcom access. They are also part of the NT faction so they won't be shot at, even if they friendly fire.

The spawners are not anywhere on the map currently, while I admit the idea of having some ghosts being able to spawn in as NT Sec is amusing, but I'm dubious as to its effects in game due to access to the shuttles.

**Comment by KorPhaeron** [comment]
Having hostile mobs that you have to delete whenever you're doing something admin related on centcomm sounds like a bit of an annoyance

**Comment by Steelpoint** [comment]
They will only attack if attacked, so they will only interfear if you are spawning hostile mobs. Which may actually enhance the scene since the arriving players will see the dead Centcom Security personal alongside whatever you spawned in.

**Comment by calzilla1** [comment]
RANDOM CENTCOM DOCKS

**Comment by Steelpoint** [comment]
???

**Comment by optimumtact** [comment]
Not sure it's worth it considering most people spend all of 60 seconds at centcomm at round end

**Comment by Jalleo** [comment]
It gives people a thing to kill when the shuttle docks. Beyond that its just RP.

**Comment by RemieRichards** [comment]
Ditch the guards, make the ones that sit in the little office-y part just fake cardboard cutouts that look like guards.

**Comment by Steelpoint** [comment]
I should note that the Officers are mediocre attackers. More to do with the bullet time, a fast moving enemy can easily dodge their attacks and they have a pretty low rate of fire.

I've fixed the access issues for the officer IDs so they have general access to Centcom, though they cannot get into certain areas.

**Comment by Steelpoint** [comment]
What is the "cost" of a few Centcom guards?

Considering we have dozens upon dozens of NPCs spawn on lavaland, lavaland ruins and on space ruins, I don't think barely a dozen Centcom guards is going to stretch the limits of the server.

**Comment by RemieRichards** [comment]
@Steelpoint not very high, but they're an unneeded cost mobs on lavaland and ruins serve a distinct purpose, player content, whereas yours are only going to play a role in the last 60 seconds of the round, and admins have already stated they'll be annoyed having to delete them to do things.

**Comment by Steelpoint** [comment]
Fair point, but I disagree it'll be a big issue considering they will not attack anyone unless they are attacked first. They also won't offer a lot of resistance against enemy NPCs, Aliens tend to chew through them very quickly.

**Comment by Jordie0608** [comment]
Spawn them only at round end? Could be a bit ugly and admins would still have to delete them if they wanted, if they're savvy they could remove the spawner but that isn't a good excuse.

**Comment by Steelpoint** [comment]
That's beyond my ability to do.

**Comment by dannno** [comment]
4 just for that one little ship seems like a lot
looks crowded
maybe just 1 or 2 for the little one?

**Comment by Steelpoint** [comment]
The implication is that they are getting ready to go on a mission, considering the ERT can fit six people in the same ship I think its ok.

**Comment by Niknakflak** [comment]
Gonna have to delete em almost every round
Map changes don't even particularly look very good
Remie's idea is way better?

**Comment by PKPenguin321** [comment]
Yeah nix the mobs do cardboard

**Comment by Steelpoint** [comment]
If Niknak wants to delete them every round then that's his prerogative. 

The most admin interaction I see with centcom is spawning the death squad or syndrones.

PR is good as is, it can either be rejected and closed or merged.

**Comment by Militaires** [comment]
admins dont have to delete those they dont attack you if you dont fuck with them guys can you even el reado

**Comment by Niknakflak** [comment]
>If niknak wants to delete them

More like all admins will HAVE to

I'm not the only admin who stated this so don't act like it's a witch hunt of mine, that's incredibly short sighted and rude.  Make sure your grudge isn't making you see things hazy.

**Comment by PKPenguin321** [comment]
Fuck off steelpoint, what's with you and non compromise

If you're gonna be like that then I hope this PR is just rejected altogether

**Comment by Steelpoint** [comment]
I just have a hard time believing that admins are going to need to delete them every round when the only admin interaction I've ever seen is spawning hostile NPCs rarely.

**Comment by KorPhaeron** [comment]
Admins (at least in this PR) don't seem to like this, sorry

**Pull request closed without merging**
