### PR TITLE
New plating and walls

### PR DESCRIPTION
**Pull request by MTandi**
## About The Pull Request

image

image

image

The current plating looks like something you'd trip over often when you walk on it. Decided to try out smoothed plating, and liked it.

Walls are going to be replaced by wallening soon anyways, so just bundling it in because whatever. Please let me know if I should exclude them.

## Why It's Good For The Game

Newer sprites. 

## Changelog

:cl:
image: New plating sprite with smoothing
image: New wall sprites
/:cl:

### CODE REVIEW

**Comment by SmArtKar** [comment]
You should probably split plating and walls into separate PRs, since there is a rather significant chance walls get DNMed due to wallening

**Comment by Dorsisdwarf** [comment]
This plating looks like just another kind of floor tile, not an industrial underfloor layer that you attach actual flooring into.

**Comment by Kapu1178** [comment]
the walls being tiled exactly the same as the floors is jarring and hurts my eyes

**Comment by GhostPlayer6942** [comment]
looks nice but the current apc and air alarm sprites dont really fit in that well on the walls

**Comment by Dirt-Dweller** [comment]
The inner walls look nice, although I can't help but feel like the wall slopes look off when next to things the walls are meant to support, like airlocks and windows.

**Comment by Inari-Whitebear** [comment]
Better wallening, might also not cause nausea issues

**Comment by avaster303** [comment]
so this gives the illusion of having tall walls without actually hindering gameplay. can't believe this wasn't considered over the gameplay hindering current ones we have

**Comment by nukularpower** [comment]
sad this was not used instead of wallening

**Pull request closed without merging**
