### PR TITLE
Fixes targeted scripture not allowing valid name input

### LINKED ISSUE #18459: You cannout use the Formless Pariah invocation on people with apostrophes in their names
I tried using it to mind control captain Q'ara Fayne, both with the apostrophe and omitting it, and all it did was close the prompt without a message. This probably affects Justiciar's Gavel as well.

### PR DESCRIPTION
**Pull request by ChangelingRain**
Fixes #18459

### CODE REVIEW

**Comment by coiax** [comment]
Did I mention that "enter the name of the person you want to fuck over" is really clunky? I understand not giving them just a list of all living minded mobs, but having to type someone's name exactly is just... weird.

**Comment by coiax** [comment]
Is it Mehki? Or Mekhi?

**Comment by ChangelingRain** [comment]
It's really weird yeah

**Comment by Cheridan** [comment]
"JyyuLlI|li Vvwavwrvvililil has signed up as Assistant."

**Comment by PKPenguin321** [comment]
LlIlIrnmnrnmlIl Mc0OO0lIllIlIIlllrnmmrnrnm

**Pull request merged**
