### PR TITLE
[DNM]Replaces head of staff telescopic baton with special energy varient

### PR DESCRIPTION
**Pull request by silicons**
**I know you guys think this is a horrible idea, but hear me out here.**
This PR replaces the roundstart telescopic baton heads of staff get with an energy varient. 
This varient stuns for longer (same duration as a taser) , and has no clickdelay.
**HOWEVER:** It runs on energy charges that refill automatically. You'll get one stun about every 10 seconds. It stores 3 in total. When you attack someone with it, you beat them AND stun them at the same time. For those of you who think this is overpowered, you could beat someone to death with the regular telescopic baton just by stunlocking on help intent and then using harm intent. What makes this not as good for direct stunlock-killing is that it automatically retracts when it runs out of charge, and it can not be extended without having enough charge to stun, so if someone only has this weapon, they can not easily stunlock and kill someone with it alone. The maximum amount of time you can stun with this is about 20 seconds, if you manage to time the stuns PERFECTLY (holds 3 charges, when you use third one it will recharge 1 charge, for a total of 4 * 5 = 20 ticks). This makes the telebaton more of an emergency self defense weapon rather than something to be used at a whim. IF this is still overpowered/whatnot I can make the recharge time higher.
So yeah, thoughts?

:cl:
experimental: Heads of staff now have limited-charge energy telebatons instead of their normal varients. These are harmful so use them sparingly.
/:cl:

### CODE REVIEW

**Comment by PKPenguin321** [comment]
Sounds stupid
Doesn't do anything to address the underuse of flashes (which was the topic of the thread that this PR was born from)
You claim it works the same but the extra long stun will make murdering people with it almost impossible to mess up, whereas people could get out of regular telebaton stunlocks all the time. Not to mention it will be better than a regular stunbaton considering the infinite charge and small size.

Not sure what made you think this was good?

**Comment by kevinz000** [comment]
@PKPenguin321 You could murder people just the same with the regular telebaton unless you were lagging, and this actually has limited uses, and you can't stunlock someone all the way to the brig/forever and strip them at the same time.

**Comment by PKPenguin321** [comment]
Oh, my bad. I misread the charge part and thought it gave +1 charge every three seconds while holding 10.

I guess it's okay

**Comment by kevinz000** [comment]
@PKPenguin321 I just realized while calculating the numbers to justify this that I should raise the charge duration to 15-20 seconds because stun(5) is apparently 10 seconds due to mobs processing every 20 ds instead of 10 ds.

**Comment by ExcessiveUseOfCobblestone** [comment]
you can nerf telebatons if my pr goes through, they don't need 2 reliable stun options :^)

**Comment by ExcessiveUseOfCobblestone** [comment]
oh provide me sprites

**Comment by kevinz000** [comment]
I'm making them recharge 1 charge every 20 seconds and stun for 5 mob/life()s which is about 10 seconds due to mobs subsystem having a wait of 20ds.

**Comment by kevinz000** [comment]
Alright actually
I have two choices here.
1. Make it stun for EVEN SHORTER. Infact, short enough to basically be a disarm-push, as in weaken(2) or something, but make its recharge rate/max capacity higher, so it becomes useful to make someone drop their weapon, but quickly runs out if you try to stunlock someone to death with (If I do this ofcourse the damage per hit will be made way lower)
2. Current values, long recharge and moderate stun, it stuns for long enough for you to run away/kick them out of your department, but its recharge is really long, so if you get attacked by any amount of people thati sn't 1 person, you'll wish you had a real weapon.
@PKPenguin321 @ExcessiveUseOfCobblestone

**Comment by PKPenguin321** [comment]
Shorter stun is probably better, save longer stun for flash

**Comment by kevinz000** [comment]
alright yeah I'll edit this a bit when I get back.

**Comment by kevinz000** [comment]
Actually, I have an interesting mechanic to propose here(and because I like watch dogs)
Make it do weaken(1), and do 2 brute per hit, with 2ds clickdelay. HOWEVER, it can only be used on a single target. If you try to attack multiple targets you'll incur normal clickdelay. After 3 hits on the same target you do the energy stun for (5), and do 4 burn for the rest of the 10 damage, as well as MAYBE 20-30 stamina. That makes it have the best of both, a short stun to make people drop their weapons, and a long weapon on a single target if you manage to stay on them for ~half a second to throw them out of your department.

**Comment by Arianya** [comment]
> Make it stun for EVEN SHORTER.

No, the point of the telebaton is self defense and removing someone from the department if need be, this harms that use

> Current values, long recharge and moderate stun, it stuns for long enough for you to run away/kick them out of your department, but its recharge is really long,

My preference.

> @ma44 suggested stamina based combat

I dunno how the numbers shake out on stamina based combat, but can't you counteract it very strongly by just downing coffee beforehand? I'd need to do the maths on this one to figure out how good/bad it'd be.

> Make it do weaken(1), and do 2 brute per hit, with 2ds clickdelay. 

Mixed damage types tend to be a pain to deal with (brute and burn). Play me through how long it would take to get to the "throw them out" stun compared to the existing telebaton?

I'm not a fan of the telebaton doing damage because AIs/borgs are going to kick everloving shit about it but I can live with that.

Also

> they don't need 2 reliable stun options :^)

Too bad flash isn't a reliable stun option :^)

**Comment by GunHog** [comment]
I was writing a response to this, but Aria-nya's post sums things up nicely.

**Comment by Arianya** [comment]
I forgot to mention this

> Doesn't do anything to address the underuse of flashes (which was the topic of the thread that this PR was born from)

You don't have to touch telebatons to try and make flashes relevant.

**Comment by ExcessiveUseOfCobblestone** [comment]
Flashes are being made relevant in #24111 though what part of 

> you can nerf telebatons if my pr goes through, they don't need 2 reliable stun options :^)

was difficult to where you had to misquote it?

anyways mekhi if you're going to be a memer base the baton around slowing [stamina] into stun [meaning telebaton is better with consecutive hits but flash is 1-n-done] instead of turning every break into apartment into a fight with the AI.

**Comment by XDTM** [comment]
With longer stuns comes the ability to cuff while they're down, don't forget that. It doesn't matter if you can't keep them beaten down all the way to the brig if you can cuff them and drag them all the way to the brig.

**Comment by Arianya** [comment]
@ExcessiveUseOfCobblestone Flashes, even with your suggested buffs, are not reliable stuns. They're easily negated entirely by sunglasses (which are obtainable even by non antagonists just by trawling maint) and have a random chance to break, let alone the fact that flashes break from EMPs, which in some cases (the CE) can mean they'll lose their flash through pure poor luck getting sideswiped by things like singulo emp bursts.

We don't have a piece of equipment that negates stunbatons, tasers or disablers available to any staff.

**Comment by kevinz000** [comment]
Entire idea being redone

**Comment by PKPenguin321** [comment]
Go read the OP of the forum thread advocating for their removal.

**Comment by PKPenguin321** [comment]
Oh that was at arianya, my replies didn't refresh whooooops

**Pull request closed without merging**
