### PR TITLE
Removes the old guitar ship space ruin.

### PR DESCRIPTION
**Pull request by WJohn**
**Only merge after #39351 is merged!**

Since the newly proposed white ship is designed as a remake of this old design, there's no reason to really keep the homage with its *extra* set of medical rigsuits when the new one does all that already and looks much better and won't confuse people anymore.

:cl: WJohnston
del: Removed the old guitar ship space ruin, since it only ever confused people for why it couldn't fly (it was never meant to) and was obsolete since a proper new boxstation white ship was mapped as a remake for it.
/:cl:

### CODE REVIEW

**Comment by Cyprex** [comment]
Needs to be tagged Do not merge

**Comment by JStheguy** [comment]
you've gone too far wjohn

**Comment by Bawhoppen** [comment]
I would be very sad to see the guitar ship go. That thing really is a relic.

**Comment by Deepfreeze2k** [comment]
Why not blow the hell out of it and make it VERY clear the thing won't fly?

**Comment by zamolxius** [comment]
just crash the front part into the derelict

**Comment by SpaceManiac** [comment]
Hopefully the difference between this derelict (and its now obviously non-working computers) and the completely different-looking working whiteship means the confusion will be solved without having to remove the guitarship ruin.

**Pull request closed without merging**
