### PR TITLE
Elance no longer transcends space and time

### LINKED ISSUE #44848: Elances are missing proximity check
Issue reported from  Round ID: 111691 (/tg/Station Sybil-2 [ENGLISH] [US-WEST] [LOWPOP] [100% LAG FREE])

Round ID: 111691
BYOND Version: 512.1471
Server revision compiled on: 
Master commit: a83087788b0e3d084984e65170a50b2f19a1bbf5
The following pull requests are currently test merged:
#44310: 'Removes Hygiene' by Garen7 at commit 3a37d0322c
#43148: '[s]Temp workaround for admins matching stickybans because of a byond bug.' by MrStonedOne at commit e34fa30ce1

Explosive lances call their afterattack() on a target regardless of proximity, only sight is required.

### PR DESCRIPTION
**Pull request by optimumtact**
Closes: #44848

### CODE REVIEW

**Comment by optimumtact** [comment]
https://github.com/tgstation/tgstation/pull/41466 was the cause as it removed the parent call and it's proximity check

**Comment by Pugie** [comment]
[https://www.youtube.com/watch?v=o27rYQdJPY8&feature=youtu.be](url)
No man should wield so much power.

**Comment by Fikou** [comment]
congwatuwations!!

**Comment by PKPenguin321** [comment]
can u believe this shit

**Comment by Shadowflame909** [comment]
Tempted to see an Admin Only teleport E-Lance.

WITH A TARGET IN MIND MY E-LANCE TRANSCENDS SPACE AND TIME

**Comment by Dennok** [comment]
Yes, need to make bluespace e-lance, that use b-crystals

**Pull request merged**
