### PR TITLE
Metaops box set 2: Deleting a branch like a dumbass

### PR DESCRIPTION
**Pull request by yackemflam**
:cl: Yackemflam
add: You can now buy a box for a chance to mess with the stations meta for ops.
/:cl:

### CODE REVIEW

**Comment by kevinz000** [comment]
The TRavis CI build failed.

**Comment by JJRcop** [comment]
That changelog is a something something... as in not descriptive, the contents of it should not be a changelog.

**Comment by KorPhaeron** [comment]
>That changelog is a something something... as in not descriptive, the contents of it should not be a changelog.

**Comment by Ninja137** [comment]
Just to make sure that I'm not retarded, does this add the sniper for normal traitors, or what?

**Comment by yackemflam** [comment]
It's a cheap nuke ops set with bloodred hardsuit, bulldog, ammo, microbomb, emag, and some c-4
It's to give the crew a bad scare and break the OOOOOOOPS meta that we have.

**Comment by Ninja137** [comment]
Alright, but it also mentions the sniper. Is the sniper actually accessible for traitors through this or anything else? I need my fix, man. I need something to break up the monotony of normal traitor items.

**Comment by yackemflam** [comment]
But the boxes then
The sniper kit is there it's just to lowercase the S in sniper to keep it in line.

**Comment by Ninja137** [comment]
So there IS a box that has the sniper now?

**Comment by yackemflam** [comment]
Yep, already in the game.
It's a random chance though.

**Comment by Ninja137** [comment]
It's something, at least. It'd be nice if you got some sort of "Choose a category" thing for the package, at least. Like you click the box kit, it pops up a thing going "Choose: Stealth, Direct, X, or Y" or something, so you could get a vague idea of what you might get, and keep an option for just random.

Does the sniper show up in the Crate, at least? Can ammo be crafted for it yet?

**Comment by yackemflam** [comment]
No and no.
I'm thinking of making a pr for the sniper and give it more ammo.

**Comment by Ninja137** [comment]
If you can't make ammo, then what's the point, even? Doesn't it start with only like 5 shots?

**Comment by yackemflam** [comment]
You also get some goggles and penetrator rounds.

**Pull request merged**
