### PR TITLE
Quartermaster Now has a minimum hour requirement 

### LINKED ISSUE #68810: There are no minimum hour requirements for Quartermaster
Reporting client version: 514.1583

## Round ID:
[187391](https://scrubby.melonmesa.com/round/187391)

## Testmerges:
- [Adds the Mothroach](https://www.github.com/tgstation/tgstation/pull/68763)
- [Revamped Away Mission: Caves (needs testing)](https://www.github.com/tgstation/tgstation/pull/68686)
- [Refactors SM Delaminations to be strategies](https://www.github.com/tgstation/tgstation/pull/68599)
- [Drastically improved the USB connection for air alarms. Any airlock can now be made into a shell](https://www.github.com/tgstation/tgstation/pull/68632)

## Reproduction:
Encountered a player with 1 hour of playtime joining as an intern quartermaster. As they are now considered a head of staff, this seems like an oversight to let brand new players join as it.

### PR DESCRIPTION
**Pull request by ANAME593**
## About The Pull Request
fixes https://github.com/tgstation/tgstation/issues/68810

## Why It's Good For The Game
it solves https://github.com/tgstation/tgstation/issues/68810 + qm is a command role now so it should have a hour requirement 

## Changelog

:cl:
add: quartermaster Now has a hour requirement 
/:cl:

### CODE REVIEW

**Comment by optimumtact** [comment]
The quartermaster doesn't have an hour requirement because it's the first command role many people will try out.

**Comment by ANAME593** [comment]
> The quartermaster doesn't have an hour requirement because it's the first command role many people will try out.

it had no hour requirement because it was never a command role for a long time.  

while i agree that cargo is a easy job i think it should have some sort of hour req especially since qm can be  the acting cap.

**Comment by optimumtact** [comment]
it wasn't up for debate

**Comment by Mooshimi** [comment]
> it wasn't up for debate

then pls close this or mark it as intended https://github.com/tgstation/tgstation/issues/68810

**Pull request closed without merging**
