### PR TITLE
Riot armor buff

### PR DESCRIPTION
**Pull request by actioninja**
## About The Pull Request

Halves the value of riot armor slowdown. Because of how slowdown works, if you are running at full speed (1.5 movement delay) this changes it from a 40% slowdown to a 25% slowdown.

## Why It's Good For The Game

40% slowdown was a lot more than I intended.

## Changelog
:cl:
balance: Riot armor slows you down less.
/:cl:

### CODE REVIEW

**Comment by HomocidlePancakes** [comment]
Wat. It doesn’t give you a slowdown.

**Comment by actioninja** [comment]
> Wat. It doesn’t give you a slowdown.

It does.

**Comment by HomocidlePancakes** [comment]
That hasn’t been a thing for years. Iam so confused right now.

**Comment by WJohn** [comment]
It's something actioninja here added in his disarm rework, but it was more than intended. He's toning it down. 0% -> 40% -> 25%

**Comment by Barhandar** [comment]
>the armor made for melee, where the faster opponent will be able to deal more damage or just run the fuck away while throwing deadly stuff at you, slows you down

**Comment by Shapsy** [comment]
Riot armor has always been a questionably useful meme but this version of it is more interesting now that it stunts disarms

**Comment by ATH1909** [comment]
Ah, so THAT'S why my chaplain armor slows me down so much now?

**Comment by actioninja** [comment]
I thought I fixed that part, I'll include that in this PR.

**Comment by ExcessiveUseOfCobblestone** [comment]
> I thought I fixed that part, I'll include that in this PR.

update?

**Review by ExcessiveUseOfCobblestone — APPROVED** [review]
Fine on it's own, pending update from author.

**Comment by actioninja** [comment]
> Fine on it's own, pending update from author.

Yeah I had already fixed it actually. No change needed.

**Comment by anconfuzedrock** [comment]
fuck chaplains tbh

**Pull request merged**
