### PR TITLE
War declaration gives 600 research points

### PR DESCRIPTION
**Pull request by MTandi**
## About The Pull Request

Made the Nuke Ops war declaration give 600 points to the station tech web.

image

## Why It's Good For The Game

To let the station prepare more varied countermeasures.

## Changelog

:cl:
balance: War declaration gives 600 research points to the station
/:cl:

### CODE REVIEW

**Comment by Jackal-boop** [comment]
very very meh on this, i dont think this would really be an issue if random people didnt bust into sci for their own research, instead of science decided beforehand and focusing on specific techs

**Comment by MTandi** [comment]
> very very meh on this, i dont think this would really be an issue if random people didnt bust into sci for their own research, instead of science decided beforehand and focusing on specific techs

I've increased the delay for the high-tier node unlocking with the recent techweb change, so consider this as a counter-balance for that.

Also this is a request by @ZephyrTFA

**Comment by IsaacExists** [comment]
Might be better to pop up from an experi-scanner or PDA notification to science personnel regarding the increase in points, rather than the big blue announcement.

**Comment by EEASAS** [comment]
unrelated but what is your chat font

**Comment by moocowswag** [comment]
I dont think this is very fair to do in the case of nukies, yes crew is locked on some techs vs nukies now but they also get adv grenades and i think implants and tech shells alot more quickly and the tech changes did not just effect warops.

You also have other shit that ends the round early that crew would like to use against like cult or wizards.

**Comment by Loafin34** [comment]
war ops is specifically "reinforce station until 20 minute mark when ops wreck the town", so it makes sense. also, it doesn't mean they get the MATERIALS for it, just that they get the RESEARCH for it. if you really want to, you could pump out a gygax with a lot of effort, instead of being physically unable to make a gygax in 20 minutes.

**Comment by SomeoneYouProbablyKnow** [comment]
This is fine no one ever uses things rnd researches on war, the 4 people in a round who actually care will be very happy about these points and good for them

**Review by Ghommie — APPROVED** [review]

**Pull request merged**
