### PR TITLE
Rice (pudding) is no longer a salad.

### PR DESCRIPTION
**Pull request by DaxDupont**
[Changelogs]: 

:cl: Dax Dupont
fix: After 3 years of intensive research by Nanotrasen's elite team of chefs, rice dishes such as rice pudding are no longer considered salads. 
/:cl:

[why]: I know these are codewise a salad subtype but who's fucking bright idea was to put these under salads in the crafting menu jesus christ what is wrong with you

### CODE REVIEW

**Comment by Buggy123** [comment]
I don't know what you're talking about, _clearly_ these two must be the same kind of food!

**Comment by nicbn** [comment]
image

GROWS IN A PLANT

IS A SALAD

**Comment by Buggy123** [comment]
But you can put meat on a salad and its still a salad. Ergo, these are all salads:

**Comment by nicbn** [comment]
Yeah but the animals which meat are made of eat grass and salad, so they are also salad, therefore meat is salad.
Also pizza is salad as it grows in pizza plants, you know.

**Comment by CosmicScientist** [comment]
>in
shows it growing on a branch

Stop lying. The pizza blossom matures outside of the bark, not inside!

**Comment by nicbn** [comment]
Everybody knows it grows inside the bark and then pops out via quantum tunneling.

**Pull request merged**
