### PR TITLE
Defib changes

### PR DESCRIPTION
**Pull request by ghost**
- Added compact defib which equips to the belt
- Made combat defib a child of compact defib
- Gave combat defib infinite cell that can't be removed
- Combat defib starts hacked, or 'safeties off' so you can zap people with it
- Combat defib can revive through space suits (it's mainly for ERT or nuke op medics)
- Added combat defib to nuke op medical kit and ERT locker
- Doubled defib times (10 minutes before a body becomes permadead, 5 minutes before full brain damage when reviving)
- Removed defib restriction when it comes to armor (people can be wearing armor when reviving them now, because sec officers always have armor on and it's a pain to strip it due to armor's high strip times)
- Removed defib steal objective
- Removed defib from RnD
- Added some restrictions to some steal objectives that should have been there forever (cargo/CE having steal objectives for RCDs? the fuck?)

### CODE REVIEW

**Comment by Iamgoofball** [comment]
idea 4 defib stealing:

give CMO a solid gold defib

make it the steal objective

like we did with magboots

**Comment by paprka** [comment]
No

**Comment by paprka** [comment]
This will compile once https://github.com/tgstation/-tg-station/pull/7596 is merged

**Comment by fj45** [comment]
"Combat defib starts hacked, or 'safeties off' so you can zap people with it"

https://www.youtube.com/watch?v=V9AkvnSYO8s

**Comment by Lumipharon** [comment]
Unlimited long stun melee weapon for ops... Sounds set for hilarious gimmicks. +1
I still don't like regular compact defibs bein available to the crew however, it makes death real trivial when anyone can stick one on the belt. Also supposedly on touch shit still works on corpses, so you can heal corpses then defib them, and 10 minutes is a long time.

**Comment by phil235** [comment]
Why remove the defib from RnD?

**Comment by paprka** [comment]
I don't like it being available to scientists, at most it should be available to cargo as replacements but I don't particularly like R&D making more of something they already have. This is also why I dislike magboots being in the protolathe as well. It wasn't a good idea to put it in there in the first place, pretty sure the only reason why I did it was so that people could make them for their steal objectives anyway.

The compact defib is only a CMO item and those get lost easily and stuff. I don't want it to be a steal objective right now.

Death isn't trivial, it's just less massively unfun and murderboning is harder. You can revive people just about as fast as a murderboner can kill them, which is good. Plus, if you don't want people to be revived, just hit them a bunch while in crit until they deathgasp. Defib doesn't undo tissue damage and the brain damage it gives can be really obnoxious.

**Comment by Iamgoofball** [comment]
okay, makes sense
:+1:

**Comment by Dorsisdwarf** [comment]
But styptic powder still heals the dead, which can bring them back below the limit for defibbing, right?

**Comment by Lumipharon** [comment]
^ That's what I was referring to. You can heal corpses before defibbing.

**Comment by paprka** [comment]
I thought reagents aren't processed on dead people though.

**Comment by Dorsisdwarf** [comment]
Styptic powder, synthflesh, and silver sulfidazine are all specially designed to work on the dead. It's how Strange Reagent used to work before goof nuked it.

**Comment by Fox-McCloud** [comment]
Dorsisdwarf is right, Pap--though I don't know if that's necessarily a bad thing, but it does have quite the implications for balance of defibs.

**Comment by paprka** [comment]
*Sigh* goonchem once again rears its ugly head into my fucking features designed for MEDICAL DOCTORS

**Comment by Fox-McCloud** [comment]
@paprka 

That's pretty much why I don't personally think it'll be a huge issue; people that are found with huge amounts of brute damage that were killed by a traitor are usually well past the point anyway and just get cloned.

People who are within the "safe time zone" but can be healed up with styptic/silver sulfa will likely be few and far between

**Comment by Lumipharon** [comment]
10 minutes is a long time you know. One clever chemist with a defib and some patches could revive assloads of people during say, a nuke op round.

Also after watching that hilarious shock trooper video, I feel as though safety off defibs should push people back a tile or two when they stun them.

**Comment by paprka** [comment]
I don't see the problem, medics being useful during combat is a good thing. Nuke ops should be in and out and not waste time mowing people down and killwhoring anyway. It's extremely easy for nuke ops to kill the crew, so it should be easy for them to get back into the round due to medics.

Medics need to be stronk, and antag needs to be hard mode.

**Comment by Dorsisdwarf** [comment]
I love the idea of just running around as the syndie medic assblasting security with my infinite undisarmable stunbaton while the rest of the ops grab the disk.

**Pull request merged**
