### PR TITLE
Makes the server compile and push TGUI

### PR DESCRIPTION
**Pull request by Cyberboss**
> Generated files in the repo

Basically, if you push a ract update, the server can take care of compiling it for you

### CODE REVIEW

**Comment by lzimann** [comment]
This will be a major pain to anyone that just wants to download the code and test something, since they will have to download jsnode and the tgui dependencies(and sometimes it gets REALLY annoying to set up).

**Comment by Incoming5643** [comment]
Not all computers can even compile TGui, including mine.

Note this is unrelated to the IE11 requirement (which also needs to be fixed by someone who can actually compile TGui >:( )

**Comment by Cyberboss** [comment]
DEVS DON'T HAVE TO COMPILE IT! WHY DOES EVERYONE THINK THAT

**Comment by Incoming5643** [comment]
Oh, THAT server. Nevermind.

**Comment by Shadowlight213** [comment]
How much extra time is this going to add to the update? Does it compile even if no one made a tgui change?

This really really needs to be a Web thing. Not something that is run after a pr is already merged.

**Comment by Cyberboss** [comment]
Remove tgui pls

**Pull request closed without merging**
