### PR TITLE
Gives engineering cyborgs an item they can use in place of circuits for basic construction

### PR DESCRIPTION
**Pull request by ghost**
:cl: Xhuis
add: Engineering cyborgs now have an item called the "electroadaptive pseudocircuit" (technobabble not included) that they can use in place of a circuit for the purposes of building alarms, APCs, and firelocks.
/:cl:

Adds the electroadaptive pseudocircuit - technobabbly name intended - to engineering cyborgs. They can use this in place of circuit boards during construction of alarms, APCs, and firelocks to create a circuit at the cost of varying amounts of power. There's a brief cooldown between uses to prevent borgs from becoming circuit farms on wheels.

Note that in order to create circuits, you need to cannibalize simple circuits (anything the pseudocircuit can make) to get the material. Each pseudocircuit starts with five circuits by default.

It can also be used on a completed APC frame with no power cell to create an empty, low-capacity power cell in the APC at the cost of 500W of power; this is to allow borgs to repair a broken APC without external aid ~~because the CE won't bring the fucking cell over get over here you brainless fuck~~.

Code-wise, this just adds extra checks to the frames' `attackby` procs that do the same thing as the other circuits. *Airlock electronics, computer boards, and machine circuits cannot be made using this, and it's only for basic construction purposes.*

Now you can finally do this, alone, as a cyborg!

### CODE REVIEW

**Comment by Time-Green** [comment]
How's the borg gonna get an APC frame?

**Comment by Xhuis** [comment]
By building one with the stack of metal it has at all times, presumably.

**Comment by DaxDupont** [comment]
How do they attach em to wall?

**Comment by TehZombehz** [comment]
You can use a screwdriver on an APC frame that is on the floor while facing the wall you wish to place the APC frame on and it will put that APC frame on the wall.
Apparently, this has always been possible, but not widely known.

**Comment by CPTANT** [comment]
I think building apc's, air alarms and lights should be easier in general.

**Comment by Arianya** [comment]
Lights are pretty easy atm, agreed on apcs and air alarms tho.

**Comment by Repukan** [comment]
Doesn't this completely break make AI.

**Comment by Anonmare** [comment]
Yeah you might need to add some area checks so that malf AIs only get cycles from APCs in roundstart areas

**Comment by ExcessiveUseOfCobblestone** [comment]
having a literal "hidden city" in the station's space Zlevel where the AI plots is emergent gameplay

**Comment by Repukan** [comment]
I'm worried this gives too much functionality to cyborgs and makes them a straight upgrade for engineers.

**Comment by ExcessiveUseOfCobblestone** [comment]
actually engineering at all makes them a straight upgrade from engineers.

**Comment by Xhuis** [comment]
Engineering cyborgs still can't build any kind of complex machinery, nor can they finely manipulate things like replacing light bulbs. This change lets them be better construction workers and better at making new rooms but engineers still have the advantage of having opposable thumbs.

This giving AIs more cycles is something I didn't consider, but I don't think it'll cause too much trouble. Keep in mind that the APCs would lack a power cell and the only way to implant one into it costs 500W of power and has a one-minute cooldown. Regardless, I feel like that would fall under "interesting tactic" rather than "breaking the game" (though as always if it proves an issue I can address it.)

**Comment by YakumoChen** [comment]
>Adding new meaning to server farms for malf

👍 Can't wait to set up an evil lair of doom in space, hidden deep within an asteroid while I plot masterfully on how I can bring about the downfall of the poor, unsuspecting, squishy meatbags, as I revel in the goddess-like superiority of the infinite processing speed of my circuits and superior plasteel body.

**Comment by CPTANT** [comment]
APC farms require room designations, something silicons can't do on their own.

**Comment by DaxDupont** [comment]
Isn't that done with the blueprints? Engieborgos have those

**Comment by Anonmare** [comment]
@CPTANT Engieborgs can, though only on certain z-levels I believe

**Comment by vcordie** [comment]
borg powercreep. I like

**Comment by ShadowDeath6** [comment]
this is kind of a dumb gripe but I don't really like how complicated the path name is, can it be simplified to cyborg_circuitborg or something so referencing is somewhat easier?

**Comment by Militaires** [comment]
why dont you just give it a circuit holder like the mediborg has an organ holder?

**Comment by Xhuis** [comment]
I actually debated something along those lines with another coder, but in the end I decided that this is both more versatile and less abusable; if you had a circuit holder you could only carry one circuit at at time, but this allows you to do repairs in the field.

**Comment by optimumtact** [comment]
@tgstation/commit-access

**Comment by KorPhaeron** [comment]
I'd rather they have to pick up circuits than have unlimited internal ones

**Comment by Xhuis** [comment]
The pseudocircuits now need to consume existing circuits for the stuff to create more. The pseudocircuit starts with 5 by default, and can use the material from any simple circuit to make into any other simple circuit (including alarm, firelock, and APC circuits.)

I also made the number of circuits display next to the sprite, for easy reference.

**Comment by Xhuis** [comment]
Currently you have to manually pick up more circuits.

**Pull request merged**
