### PR TITLE
trendie (water and fuel) tankies

### PR DESCRIPTION
**Pull request by Militaires**
:cl: Ausops
imageadd: New sprites for water, fuel and hydroponics tanks.
/:cl:

last column

### CODE REVIEW

**Comment by jughu** [comment]
If we change everthing into this perspective we are like gods... controlling the mere humans which is auctally trie

**Comment by WJohn** [comment]
Needs tweaking on the proportion of the top half versus the front half, as that has a major impact on the angle the object is presented at.

Otherwise pretty cool, I'd say you need to fix a bit of the lighting on the actual water container of the water/hydro tanks (they're differing light sources, right and left?), but otherwise these are pretty nice.

**Comment by Militaires** [comment]
tweaked according to what wj wanted all accordingly


colours on top of this specific tank are fixed

**Comment by ChangelingRain** [comment]
These seem, uh, like their perspective isn't quite the same as, say, the vending machines? It's unnerving.

**Comment by PKPenguin321** [comment]
yeah you can see too much of the top

**Comment by Thunder12345** [comment]
Maybe they're just very deep

**Comment by WJohn** [comment]
My take on these. Bman says that the tank on the left is supposed to be a big amorphous bag held together by straps, but it never came across that way to me. I always thought it was like some sort of big gallon jug type of deal, plastic, not rubber.

**Comment by GunHog** [comment]
WJ's version seems nicer than the ones proposed. I still do not understand the move to this new perspective. I do not think it looks better at all. I do agree that we should revise our sprites and update them, but I do not see why it was decided that this new orientation is required.

**Comment by Militaires** [comment]
i borrowed some elements of wj's which i initially didnt want cause it makes the edges uneven from the border BUT whatever here's the new one

**Comment by Chronitonity** [comment]
The upper part of the right tank looks way too stretched out imo

**Comment by dannno** [comment]
just do wjohn's edit

**Comment by Militaires** [comment]
k

**Comment by RandomMarine** [comment]
So, uh? Where'd the faucets go?

**Comment by dannno** [comment]
Oh holy shit.
Those were faucets.
Wow. TIL. I thought this entire time they were just T's for some reason.
That's fucked up

**Comment by Jordie0608** [comment]
I'm just going to edit your changelogs instead of telling you to make better ones.

**Comment by RandomMarine** [comment]
Also, I'm not too keen on how wide the base of the unit is, makes it look fat instead of tall.
tanks

**Comment by WJohn** [comment]
@RandomMarine You gave the camera a much lower angle of the trolley, but didn't adjust the tops of the tanks. The only way this would make sense is if the tops are slanted at a 45* angle, lighting problems aside. Please fix.

Also still has the same problems I outlined in my first post.

**Comment by optimumtact** [comment]
you need to actually take photos of things in the game, becuase these are in no way representative of the final products

**Comment by optimumtact** [comment]
same goes for every other new sprite pr

**Comment by BeeSting12** [comment]
Old ones were better

**Comment by Ausops** [comment]
https://imgur.com/a/vrrJi

**Comment by Xhuis** [comment]
Can we just get ausops to resprite everything

**Comment by PKPenguin321** [comment]
answer the following:

why do we still allow not-ausops to make any executive spriting decisions?

**Comment by Ausops** [comment]
this may seem odd but basilman if you have the time can you meticulously go through your thought processes when making your sprites

**Comment by Militaires** [comment]
@ausops okay sure but if you're gonna hijack my pr atleast send me the files so i can replace them with the better ones :/

**Comment by Ausops** [comment]
https://file.house/Z702.dmi

**Comment by Iamgoofball** [comment]
answer the following:

why dont we just clone ausops

**Comment by WJohn** [comment]
Those are pretty.

But it's ausops so of course.

**Comment by Kromgar** [comment]
Seriously can we start a kickstarter for ausops to sprite the game?

**Comment by Incoming5643** [comment]
This is trending dangerously close to collusion

**Pull request merged**
