### PR TITLE
Removes download restrictions for NIRN tablets and allows QMs to buy things directly

### LINKED ISSUE #58430: QMs can't use the NIRN to make cargo purchases using a tablet
The Nanotrasen Internal Requisition Network tablet program requires you to have ACCESS_HEADS to make actual purchases instead of just requests, so QMs can't do that without an access upgrade or something, even though making Cargo purchases is, like, their primary job.

### PR DESCRIPTION
**Pull request by RandomGamer123**
## About The Pull Request
Everyone can now download the NIRN program on computers which allows you to buy or request to buy stuff. QMs now also get to buy things directly. All other people will still only be able to request to purchase something.

## Why It's Good For The Game
Fixes #58430 , makes the program useful for people other than department heads who used to be the only one to be able to download it, also doesn't really make sense for the QM to be unable to access the program given that their job is to be ordering stuff.

## Changelog
:cl:
fix: QMs can now use the Nanotrasen Internal Requisition Network program on modular computers to order things remotely.
qol: All people may now download the Nanotrasen Internal Requisition Network program on modular computers to request to order things remotely.
/:cl:

### CODE REVIEW

**Comment by optimumtact** [comment]
Fill out the justification for why properly or this PR will be closed

**Comment by RandomGamer123** [comment]
> Fill out the justification for why properly or this PR will be closed

This good enough for you?

**Comment by ArcaneMusic** [comment]
Can you verify that this will still maintain first right of refusal on cargo with civilian purchased goods? It wasn't necessary when the restriction was on heads, because they were purchasing straight from their departmental budgets. Crew should be purchasing more or less from their own bank accounts, and have limited power over existing purchases if they're not in cargo.

**Comment by lordScrubling** [comment]
> Can you verify that this will still maintain first right of refusal on cargo with civilian purchased goods? It wasn't necessary when the restriction was on heads, because they were purchasing straight from their departmental budgets. Crew should be purchasing more or less from their own bank accounts, and have limited power over existing purchases if they're not in cargo.

civilians can only request but not approve them with this change

**Comment by RandomGamer123** [comment]
Just started up a test server to make sure, and yep, assistants etc. can only be able to request to buy items. @ArcaneMusic

**Pull request merged**
