### PR TITLE
centers hydroponic sprays

### PR DESCRIPTION
**Pull request by Fikou**
## About The Pull Request

all the hydroponic spray sprites arent centered for some reason idk if this is 200 million years old and was used because you couldnt pixel shift or something i dont care

## Why It's Good For The Game

it looks SHIT

## Changelog
:cl:
imageadd: centers hydroponic sprays, adds new sprites for plant-b-gone
/:cl:

### CODE REVIEW

**Comment by tralezab** [comment]
░░█░░░█▀█░█▀▀░█▀█
▀▀█▀▀░█▀▄░█▀░░█▀▀
░░█░░░▀░▀░▀▀▀░▀░░

**Review by tralezab — APPROVED** [review]
░░░░░▒░░▄██▄░▒░░░░░░
░░░▄██████████▄▒▒░░░
░▒▄████████████▓▓▒░░
▓███▓▓█████▀▀████▒░░
▄███████▀▀▒░░░░▀█▒░░
████████▄░░░░░░░▀▄░░
▀██████▀░░▄▀▀▄░░▄█▒░
░█████▀░░░░▄▄░░▒▄▀░░
░█▒▒██░░░░▀▄█░░▒▄█░░
░█░▓▒█▄░░░░░░░░░▒▓░░
░▀▄░░▀▀░▒░░░░░▄▄░▒░░
░░█▒▒▒▒▒▒▒▒▒░░░░▒░░░
░░░▓▒▒▒▒▒░▒▒▄██▀░░░░
░░░░▓▒▒▒░▒▒░▓▀▀▒░░░░
░░░░░▓▓▒▒░▒░░▓▓░░░░░
░░░░░░░▒▒▒▒▒▒▒░░░░░░

**Comment by tralezab** [comment]
┈┈┈╱╲╱╲╱╲
┈▕▔┊┊┊┊┊┊▔▔▏
▕▔┊┊┊┊┊┊┊┊┊╲
╱┊┊┊┊╮╮╮╭╭╭╱
╲┊┊┊╮╱▔╲╱▔╲
╱┊┊┊▕▕▍▕▕▍▕
╲┊╭╮┈╲▂╱━╮╱
┈▏╰┓┈┈┈┈┏╯┃
┈▔┗┫┈╰━(̅_̅_̅_̅((_̅_̲̅oranges, add this please!!_̅_̅_̅() ڪے
┈┈┈┃┈┈┏╯
┈┈┈◯◯◯◯
┈┈╱┈┣━┫

**Review by Twaticus — COMMENTED** [review]
cant find any code for nolabelspray, deathspray, or sprayparts so you can remove them

**Comment by Fikou** [comment]
i kept the unlabeled spray because i think it still can be useful if someone would like to add new sprays or something, removed a bunch of unused icons and resprited the spray bottle

**Review by Twaticus — APPROVED** [review]
even better

**Pull request merged**
