### PR TITLE
Wizards set dna name properly

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
Fixes https://github.com/tgstation/tgstation/issues/27751

### CODE REVIEW

**Comment by optimumtact** [comment]
Hey kor while you are here, can you add a reset camera view to call to when someone is made a wizard? every time they spawn they're not getting their camera view reset properly so it looks like they're at the shuttle

**Comment by KorPhaeron** [comment]
Sure

**Comment by AnturK** [comment]
I'm 90% sure we have a helper to set names properly.

**Comment by lzimann** [comment]
do the things

**Comment by AnturK** [comment]
@KorPhaeron cmon

**Comment by lzimann** [comment]
Just reopen when you do it

**Pull request closed without merging**
