### PR TITLE
Adds a new shuttle loan event, tweaks others

### PR DESCRIPTION
**Pull request by 81Denton**
:cl: Denton
add: A new shuttle loan event has been added. Hope you like bees!
tweak: The pizza delivery shuttle loan event now has some of each flavor and no longer pays the station for accepting it.
balance: Syndicate shuttle infiltrators now carry suppressed pistols.
spellcheck: Added a missing period to spent bullet casing and pizza shutte loan text.
/:cl:

I added a new shuttle loan event, where NT asks you to clean up the mess after one of their freighters got hit by eco-terrorists:

yeet01

beeeees

This pays more than regular events since you'll have to deal with a swarm of god damn toxin bees.

Other changes:
- The pizza shuttle loan event contains one of each box type and no longer pays cargo. Getting paid to receive free pizza is a bit odd.
- Mobs in the syndie infiltrator shuttle loan event fire .45 bullets at a very slow rate. Right now they're melee simplemobs without any weapons - really underwhelming considering you get to keep their armor, combat gloves and the specops crate.

### CODE REVIEW

**Comment by Ratvar** [comment]
Not adding actual beehive with syndiebees in it? Eh

**Comment by Tlaltecuhtli** [comment]
2 free sketchins?

**Comment by 81Denton** [comment]
They don't come with magazines, so they'll be completely useless until you get a magazine from a traitor or uplink. Both guns are just for decoration, so it doesn't matter much to me if they're left in or not.

**Comment by Tlaltecuhtli** [comment]
sketchin are syndicate tech put a no mag m1911 instead

**Comment by GuyonBroadway** [comment]
Considering you can loot syndietech from some space ruins on an rng basis anyway having it as a once every few rounds rng shuttle event isn't that bad.

**Comment by Bawhoppen** [comment]
@GuyonBroadway Not that this specific instance is very bad, but I don't think you should use powercreep to justify more powercreep.

**Comment by Dorsisdwarf** [comment]
Also specifically the issue is that NT guards have a syndicate weapon instead of the NT version

**Comment by ExcessiveUseOfCobblestone** [comment]
the beesuit protects from bees, poor guy if only he activated his hood!

**Comment by 81Denton** [comment]
@Dorsisdwarf The event spawns one 1911 and a stechkin without magazines, turns out I just uploaded an older screenshot. One sec

**Review by Cyberboss — APPROVED** [review]

**Pull request merged**
