### PR TITLE
Makes nukes immune to explosives

### LINKED ISSUE #27608: The nuke can be blown up by a maxcap, defusing it
there goes that greentext

### PR DESCRIPTION
**Pull request by silicons**
Fixes #27608

### CODE REVIEW

**Comment by obscolene** [comment]
its a feature

**Comment by PKPenguin321** [comment]
Actually is a feature. Hide your nuke, leave somebody to defend it, etc

**Comment by Alek2ander** [comment]
The nuke has resistance_flags = INDESTRUCTIBLE
That's supposed to prevent it from getting blown up.
If it doesn't, the problem is on a higher level, and overriding ex_act is spaghetti.

**Comment by kevinz000** [comment]
can't be assed to finish this

**Comment by BeeSting12** [comment]
If it was meant to be destroyed then it would be allowed to hit it with an object until it gets destroyed. Which would be a lot funner than getting within three tiles and GG.

**Pull request closed without merging**
