### PR TITLE
Puts Tesla engine on the map, tesla gen and singulo gen are equal

### PR DESCRIPTION
**Pull request by Iamgoofball**
@Aranclanos @Cheridan @duncathan @Jordie0608 @Razharas @RemieRichards @tkdrg @WJohn 
daily reminder to
M E R G E
E
R
G
E

I want this merged ASAP, because I'm gonna be gone in 4 days, there's gonna be a code freeze in a few weeks, and if this isn't merged and in the game by the code freeze that's ANOTHER FUCKING MONTH before I get to start collecting feedback and bug reports. There is no downside to merging this.

It has only upsides.

It lets me collect feedback and data on tesla engine.

Singularity engine is still there and available, and not any harder to set up than before. You don't even have to enter secure storage to get the spare.

This is the same setup procedure as when we were testrunning, and it works out well.

### CODE REVIEW

**Comment by optimumtact** [comment]
THE FIRE RISES BROTHER

**Comment by GunHog** [comment]
ACCEPTABLE.

**Comment by MrStonedOne** [comment]
The best you can hope for is a 24 hour merge.

Not every change needs a asap merge because you are lazy and/or impatient

**Comment by Iamgoofball** [comment]
I'm okay with a 24 hour merge.

I'm not okay with 2 weeks of this PR sitting stale because "hm i dunno maybe we want singulo/tesla to be more dominant".

**Comment by Incoming5643** [comment]
Also I'm pretty sure the way we do freezes is that feature PR's that are opened before the freeze started can still be merged during the freeze.

**Comment by Iamgoofball** [comment]
@Incoming5643 thats not a guarantee, and even then you need the maintainer willing to risk merging it

**Comment by Zilenan91** [comment]
@Iamgoofball The specific rules of feature freezes is that anything opened before the freeze happened can be merged during it, only features pr'd after the freeze starts get denied immediately.

**Comment by Iamgoofball** [comment]
>implying maintainers will want to merge big changes-a-lot feature/map PRs during a freeze
>implying maintainers will want to merge goofball PRs during a freeze
>implying maintainers will want to deal with the fallout of merging a goofball PR

**Comment by GunHog** [comment]
If maintainers are having a problem merging your PRs, perhaps you should evaluate what you are attempting to do with them? In this particular case, I feel you are justified in having your PR merged, but I cannot say this is the case with your usual ones.

**Comment by optimumtact** [comment]
maintainers are known bitchbabies

**Comment by YotaXP** [comment]
I was under the impression that only Metacide should be pushing updates to Metastation.

**Comment by GunHog** [comment]
Others are free to do map updates that affect the entire codebase, such as path changes or new, essential equipment. This counts as that.

**Comment by tkdrg** [comment]
I dunno, I kind of agree with Yota with this, HOWEVER meta hasn't updated his map in months, and he can always remap the engine as he wishes.

**Comment by optimumtact** [comment]
Box wins again

**Comment by KorPhaeron** [comment]
@YotaXP 

I updated his map yesterday so

**Comment by Jalleo** [comment]
It is really meta updates when meta wants to apart from that code changes to stuff is fine

**Comment by Dorsisdwarf** [comment]
Anyone has always been free to update meatstation, we just didn't because it was his baby

**Comment by Supermichael777** [comment]
supermater singularity eating a teslaball needs to end the universe.

**Comment by Shadowlight213** [comment]
Metacide has stated that others are free to edit metastation.

**Comment by Zilenan91** [comment]
@Supermichael777 I know on Goon they have it where if a supermatter explodes it literally ends the universe via a creeping tide of blackness deleting everything until there's nothing left.

**Comment by Iamgoofball** [comment]
@Aranclanos @Cheridan @duncathan @Jordie0608 @Razharas @RemieRichards @tkdrg @WJohn 
daily reminder to
M E R G E
E
R
G
E

**Comment by Iamgoofball** [comment]
@Jordie0608 is officially MVP of the millenium

**Comment by duncathan** [comment]
>If maintainers are having a problem merging your PRs, perhaps you should evaluate what you are attempting to do with them? 

Hahahahha right that's it, for sure
Gonna be honest, half the time the only reason is cuz it's goofball
Most of the time I think people go overboard with the goofball hate meme tho

**Pull request merged**
