### PR TITLE
Fixes medigun description

### PR DESCRIPTION
**Pull request by Iamgoofball**

### CODE REVIEW

**Comment by SkowronX** [comment]
that's a rather arbitrary reference.

**Comment by Iamgoofball** [comment]
Literally the gimmick of the medigun

**Comment by ExcessiveUseOfCobblestone** [comment]
There's already a description somewhere [I think in the awwp pda] that references crossing the streams, it's just being reiterated it in the gun's description.

**Comment by PKPenguin321** [comment]
this should have been the description when the gun was first made

**Comment by Fox-McCloud** [comment]
It's not arbitrary when it's already an actual mechanical gimmick.

I've also seen people accidentally kill their entire team because they didn't know that this was a thing, so...having a hint at it in the description is probably a good thing.

**Comment by TechnoAlchemisto** [comment]
superior PR

**Comment by ExcessiveUseOfCobblestone** [comment]
Arguably the best PR goof has ever put out besides Runescape Genetic text.

**Comment by Cheridan** [comment]
Mehki didnt fix his so oops

**Comment by TechnoAlchemisto** [comment]
E P I C

**Pull request merged**
