### PR TITLE
Resprites the implant action buttons.

### PR DESCRIPTION
**Pull request by CRITAWAKETS**
## About The Pull Request

This PR resprites the implant action buttons to look better. That's about it really.

Old:
Old

New:
New

## Why It's Good For The Game

Better sprites are kinda automatically better.

## Changelog
:cl:
imageadd: The action button sprites for implants look better and less placeholder-y now.
/:cl:

also maintainer permission
maintainer permission

### CODE REVIEW

**Comment by CRITAWAKETS** [comment]
this was a pain to make since i really, really cannot use gitkraken properly

it took me around an hour to fix an issue that only required logging out and back in

**Comment by PKPenguin321** [comment]
Hate to be a bummer but imo the only improved one is the freedom implant

**Comment by HomocidlePancakes** [comment]
New adrenals look more placeholdorish then the old ones.

**Comment by necromanceranne** [comment]
I mean at least it uses in-game sprites and not literal stickman art which is very placeholder.

**Comment by Tharcoonvagh** [comment]
Storage implant still looks like shit

**Comment by MrPerson** [comment]
You don't like the sprite I made for the adrenal implant? What's not to love?

On a serious note I fully intended someone to replace it quickly because of how bad it was. I can't believe it's still in use.

**Comment by nightred** [comment]
I like the new adrenal sprite and freedom sprite, but the coder sprite from MrPerson for adrenal is funny.

**Comment by anconfuzedrock** [comment]
stickman looks good though, naked human from in-game seems far more placeholdery. Freedom implant looks way more like a biodegrade.  I don't know where you got the idea that red xes are horrific but I for one think an x over a zappy is far more clear than what looks like a penlight marker.

**Comment by gryffinp** [comment]
> Edit: Emp looks like it will cause an emp, i thought it blocked emp's?

[EMP implant causes EMPs.](https://tgstation13.org/wiki/Syndicate_items#EMP_Kit) If Crit's sprite looks like it causes rather than prevents EMPs, then that's a good argument in favor of replacing that one, at least.

**Comment by CRITAWAKETS** [comment]
I mainly just changed the EMP icon and the adrenals icon to look more consistent with other antag action buttons (and non-antag now that automony or whatever its called is now in).

**Comment by cacogen** [comment]
loogs bedder

**Comment by itseasytosee** [comment]
Adrenal
_fast_

**Comment by itseasytosee** [comment]
Also, I don't like it Adrenal to clarify but find it humorous

**Comment by ninjanomnom** [comment]
the old adrenal definitely looks better

**Comment by nightred** [comment]
Why is go fast man naked? put a shirt and shoes on him, let him have his dignity.

**Comment by SpinnerMaster** [comment]
Lightning bolt looks noticeably worse. It shouldn't look curvy.

**Comment by SpaceManiac** [comment]
Is the new lightning bolt now inconsistent with the HUD icon for shocked doors, or does that HUD icon reference this sprite?

**Comment by CRITAWAKETS** [comment]
The lightning bolt is unused because no implants actually reference it. The shocked door icon is a different one (which also looks identical)

**Comment by Cyberboss** [comment]
Wake up IDB

**Comment by kriskog** [comment]
The others seem fine, but I am also not a fan of the adrenals icon. Mind you, adrenals is much less about the speedup now, and more about resisting damage and fatigue.

**Comment by Cyberboss** [comment]
Merging cause why not.

**Pull request merged**
