### PR TITLE
Lowers the cold temperature activation threshold for fire alarms/firelocks

### PR DESCRIPTION
**Pull request by Yenwodyah**
## About The Pull Request
Fire alarms and firelocks currently activate when the temperature drops below 270 K. This PR changes that value to 240 K.

## Why It's Good For The Game
A lot of players have been complaining about how often firelocks activate after recent atmos changes (https://tgstation13.org/phpBB/viewtopic.php?f=10&t=29086, https://tgstation13.org/phpBB/viewtopic.php?f=9&t=28353). In my experience most of these "firelock gridlock" situations happen after a hull breach has occurred and been fixed, but pockets of air in locked-down areas remain cold enough to trigger the fire alarms (but not cold enough to actually harm players - if players notice that they're taking cold damage, they usually try to warm up the area). Based on my testing, humans won't take cold damage until temperature reaches 235 K or lower, so lowering the activation temperature to just above that should reduce the number of "false positive" firelock activations without hampering the system's ability to respond to actual atmos incidents.

## Changelog
:cl:
balance: The cold temperature activation point for firelocks has been reduced from -3°C to -33°C
/:cl:

### CODE REVIEW

**Comment by TheBonded** [comment]
I think lizards take damage from cold at that temperature.

Then again, why would Nanotrasen care about lizards? Humans are the only species allowed as command staff for a reason

**Comment by LemonInTheDark** [comment]
> Based on my testing, humans won't take cold damage until temperature reaches 235 K or lower

This isn't strictly true, but might be technically true. Firelocks will currently close as soon as the temperature on their tile gets below the damage threshold for humans, which is the body temp at which cold starts to hurt.

It might be true in practice however, since bodytemp can take a very long time to move down, or may even require a low temperature in the first place to even drop to that point, since humans will constantly reheat themselves.

All that said, I don't think this is a good way to solve this problem.

An important part of firelocks is their prevention of station wide cold snaps, like you might have seen before #57381
They need to get cold enough to close before temperature and gas starts to even out. This is especially important with small holes.

The way I see things currently the main issue with firelocks is their scope. They're area based, and that's really hurting them here. Sealing off cold areas isn't the primary problem, it's sealing off the area 20 tiles away for no reason.

As far as the pockets of air problem sits, I think disabling fire alarms is a serviceable solution to that. It's not documented anywhere though, so I can see why it would be a headache to deal with.

**Comment by Yenwodyah** [comment]
>Firelocks will currently close as soon as the temperature on their tile gets below the damage threshold for humans, which is the body temp at which cold starts to hurt.

Well, it's the *internal* body temperature at which cold starts to hurt, which is usually a lot warmer than the external/skin temperature that fire alarms go off of. In practice, you have to get a lot lower before you start taking cold damage. You can take damage from inhaling cold air below 270, but if there's a hole in the station lowering the temperature you usually have internals ready anyways.

What do you mean by disabling fire alarms? I don't know of any way to turn them off besides emagging them...

**Comment by interestingusernam3** [comment]
>What do you mean by disabling fire alarms? I don't know of any way to turn them off besides emagging them...

Click with toolbox until effective.

**Comment by LemonInTheDark** [comment]
> Well, it's the _internal_ body temperature at which cold starts to hurt, which is usually a lot warmer than the external/skin temperature that fire alarms go off of. In practice, you have to get a lot lower before you start taking cold damage. You can take damage from inhaling cold air below 270, but if there's a hole in the station lowering the temperature you usually have internals ready anyways.

Yeah that's kinda the trouble. Internal body temp is very rarely the same as the temperature of the area, and it takes a good while to move down so areas that ought to be dangerous don't feel it

> What do you mean by disabling fire alarms? I don't know of any way to turn them off besides emagging them...



See that's kinda what I mean by undocumented. If you hit a unscrewed fire alarm with a multitool it'll stop caring about cold/heat
image

**Comment by Yenwodyah** [comment]
Oh, I see. But yeah if you have to carry a screwdriver and a multitool to turn it off that's not really a good solution, you might as well just drag a space heater over at that point.

**Comment by Pugie** [comment]
Lemon doesnt think anything is a good way to solve atmos problems :)

**Comment by Ryll-Ryll** [comment]
Just please god do something, some rounds I spend the entire shift having to fight the firelocks every time I want to pass one just because some pocket of medbay briefly became cold

**Comment by RaveRadbury** [comment]
> I think lizards take damage from cold at that temperature.
> 
> Then again, why would Nanotrasen care about lizards? Humans are the only species allowed as command staff for a reason

This is solid reasoning, don't bring the firelocks down until human health is threatened.

**Comment by GuillaumePrata** [comment]
In my experience the firelocks became an issue because everyone is walking around opening them with crowbars or breaking the fire alarms and just expect someone else to fix the issue.
Which... no one does... 
And with this change people still won't, they will just take longer to realize they are even more fucked than before because now you won't be trapped by firelocks, bored and screaming for help in common if you don't have a crowbar, you might just die.

Fire alarms is what engineers can use to quickly find breaches with the tablet and fix them, pushing them forward will slow down response time.
I know this is a horrible example... but it's like if people complained about the SM screaming at 94% and wanting it to only start to alert people when it was on the exploding stage, yes it's less annoying but also harder/late to fix properly.

At this point I wonder if it would be smart to have some heaters that are turned ON at roundstart in some more public/accessible locations like inside the medbay or dorms to hold back the cold.

**Comment by Maurukas** [comment]
The firelocks will continue until the crew learns the incredibly difficult task of dragging space heaters out of maint and turning them on.

I think LemonIntheDark has a good point though. Area based fire alarms are always going to be a problem since they inherently are going to all activate at once. I'm not sure this will solve the problem, or just make the station lose more heat before the problem occurs.

**Comment by RaveRadbury** [comment]
Testmerged on Bagil and Manuel

**Comment by SinfulBliss** [comment]
This is extremely necessary. Sure there are better ways to deal with cold atmosphere to fix the firelock problem, but no one uses them and people will continue to not use them, because they're tedious and it's much easier to just use a crowbar unless you're an atmos tekkie. Great change

**Comment by LemonInTheDark** [comment]
I don't want this for the reasons outlined above. The 0C temperature threshold is helpful, and lowering it doesn't solve the actual issues here, which is a lack of feedback from standing in a cold area, and firelocks being area based

**Comment by Technoturnovers** [comment]
> 
> 
> In my experience the firelocks became an issue because everyone is walking around opening them with crowbars or breaking the fire alarms and just expect someone else to fix the issue.
> Which... no one does...
> And with this change people still won't, they will just take longer to realize they are even more fucked than before because now you won't be trapped by firelocks, bored and screaming for help in common if you don't have a crowbar, you might just die.
> 
> Fire alarms is what engineers can use to quickly find breaches with the tablet and fix them, pushing them forward will slow down response time.
> I know this is a horrible example... but it's like if people complained about the SM screaming at 94% and wanting it to only start to alert people when it was on the exploding stage, yes it's less annoying but also harder/late to fix properly.
> 
> At this point I wonder if it would be smart to have some heaters that are turned ON at roundstart in some more public/accessible locations like inside the medbay or dorms to hold back the cold.

This is a bad comparison, the supermatter deteriorating will not immediately cripple the entire station's ability to get from point A to point B in a potentially fatal manner

**Comment by cacogen** [comment]
He won't solve it himself but everybody else's solutions or temporary fixes are not adequate

**Pull request closed without merging**
