### PR TITLE
[READY]Drastically raises Rod Form cooldown, changes rod form distance scaling

### PR DESCRIPTION
**Pull request by silicons**
Initial cooldown to 40 seconds, full upgraded cooldown still down at 10 seconds
Distance scaling changed to 10 tiles at level 1, and 30 tiles at level 5 with 5 tile increments.
This spell puts Fireball to shame.
EDIT: Pixel projectile fireball aiming pretty much raised its power by a whole bunch as earlier you had to use your body to physically position yourself in a direction to aim it.

### CODE REVIEW

**Comment by Ninja137** [comment]
To be fair here, that's because Fireball is fucking trash, and the only reason it's worth a shit is because of the RNG knockout.

**Comment by kevinz000** [comment]
yes we get it you like m- I mean, we get it, you still think low cooldown high AOE damage and incendiary properties with its clothes shredding isn't powerful without the RNG knockout which this PR doesn't even remove and the high speed which this PR does remove.

**Comment by KorPhaeron** [comment]
Fireball is on a 6 second cooldown and explodes if it comes within a tile of anyone, it's pretty damn strong especially now that you can aim it like a gun

**Comment by kevinz000** [comment]
we get it ninja likes murderboning with the most powerful 1-2 hit kill weapons and thinks that 3x3 aoe fast low cooldown spammable artillery 50 tile range explosives aren't strong enough untill they have 50% knockout chance too.

**Comment by KorPhaeron** [comment]
Also why do we always double or halve values, can never balance things slowly

**Comment by kevinz000** [comment]
korphaeron because old values are BARELY outrunnable but you can't most of the time due to lag impacting your movement speed (fuck that if only someone could fix it but that's probably not possible) and new values are as close to hitscan as we'll get. short of my sniper rifle buff which made it speed = 0

**Comment by KorPhaeron** [comment]
Maybe you should open a PR with a middle ground for speed then

**Comment by KorPhaeron** [comment]
give it another week or two, let people get over it and learn it

**Pull request closed without merging**
