### PR TITLE
Revert "Kinetic Accelerator Overhaul [Not WIP]"

### PR DESCRIPTION
**Pull request by Dorsisdwarf**
Reverts tgstation/tgstation#19870 , because while it's a really great-looking system and I'm excited to see the final product, it would be lovely if it was DONE before cheridan merged it and left miner weapon progression neutered.

edit: and changing the name to NOT WIP after you merge it doesn't count as "finished"

### CODE REVIEW

**Comment by Ergovisavi** [comment]
USE THE CRUSHER REEEEEEEEEEEEEEEEEEEEEEEEE

**Comment by KorPhaeron** [comment]
no KA progression is better than dual HKA progression honestly

**Comment by optimumtact** [comment]
Kor should just finish their work

**Comment by lzimann** [comment]
this is a great incentive so he finishes that :^)

**Comment by Kromgar** [comment]
>Removes hyper kas and super kas

REEEEEEE

**Comment by TechnoAlchemisto** [comment]
You could just remove the mod kit if it's causing issues

**Comment by KorPhaeron** [comment]
I'll just finish my work

**Comment by AnonymousNow** [comment]
Didn't we have a system like this before for a while? Diamonds and uranium and plasma for extra punch and reach?

**Comment by Dorsisdwarf** [comment]
That was on ntstation, I think

**Comment by callanrocks** [comment]
Nope it was definitely here, someone changed it because "balance" even though mining was suffering after for a while until goofcrusher came in.

**Pull request closed without merging**
