### PR TITLE
Allows felinids to wear collars

### PR DESCRIPTION
**Pull request by SmArtKar**
## About The Pull Request

See title

## Why It's Good For The Game

We need to show human dominance over filthy, dirty felinids. Also, collar wiz lepi

## Changelog
:cl:
tweak: Felinids now can wear collars
/:cl:

### CODE REVIEW

**Comment by Low3** [comment]
ihorny pr

**Comment by necromanceranne** [comment]
They already can. Just use the cheat codes.

**Comment by TemporalOroboros** [comment]
I am sorry for the impending close, but I've seen things like this pass through a few times. It never has a happy ending.

**Comment by TemporalOroboros** [comment]
@SmArtKar Also I'm pretty sure you need permission from at least one maintainer to make changes to species.

**Comment by SmArtKar** [comment]
> @SmArtKar Also I'm pretty sure you need permission from at least one maintainer to make changes to species.

I didn't change anything connected to species yknow...

**Comment by ExcessiveUseOfCobblestone** [comment]
Species specific interactions require maintainer approval.

**Comment by TemporalOroboros** [comment]
@SmArtKar While this is not a change to the species directly it is still a change to the abilities or properties of the species. Its similar to how adding moth mutation toxin is considered a species change.

**Comment by MrDoomBringer** [comment]
original pr the hedgehog do not steal

**Comment by Coastfront** [comment]
Don't.
Just Don't.

And if you do atleast phantom add lockable schoolgirl outfit.

**Comment by wesoda25** [comment]
You make me physically ill

**Comment by Potato-Masher** [comment]
I think there was a good reason the last PR for this was closed.

**Comment by PolishUser** [comment]
why

**Comment by ShibaInuLord** [comment]
based

**Comment by itseasytosee** [comment]
#45022

**Comment by necromanceranne** [comment]
Man wtf happened to shadowflame anyway

**Comment by Bawhoppen** [comment]
I knew it was only a matter of time until wearing collars got readded

**Comment by Cenrus** [comment]
I am going to projectile vomit

**Comment by CRITAWAKETS** [comment]
against god and nature here we go

**Comment by Qustinnus** [comment]
you need maint approval to make bad species PRs, I'm guessing you didn't get that?

**Comment by Timberpoes** [comment]
You need maintainer approval for opening this PR. It doesn't look like you have it.

If you can get a maintainer to sign off your change, feel free to ask them to re-open this PR.

Also this entire PR is bait.

**Comment by interestingusernam3** [comment]
I'm coooooooooooooooooooooooooooooooodiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiingggggggggggggggggggg

**Pull request closed without merging**
