### PR TITLE
Follow link for dsay

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
Not sure if people want this or not, it'd be nice if I could tell people to jump to me though.

### CODE REVIEW

**Comment by PKPenguin321** [comment]
Does nobody else have the issue where the (F) links do literally nothing
Like, you can click on them, but all that happens is you select them as if they are normal text

**Comment by lzimann** [comment]
Maybe having a toggle for the admin?

**Comment by MrStonedOne** [comment]
pk, upgrade byond version

**Comment by PKPenguin321** [comment]
Ohhhh, thanks MSO

**Comment by Shadowlight213** [comment]
@KorPhaeron make the link not show up on stealthmin dsay.

**Comment by tkdrg** [comment]
You sure you don't need show_message here? Also what shadowlight said.

**Comment by KorPhaeron** [comment]
I have too many PRs open

**Pull request closed without merging**
