### PR TITLE
Fix missing disposals segment on Delta

### PR DESCRIPTION
**Pull request by SpaceManiac**
:cl:
fix: The disposals pipe out of Delta's primary tool storage is functional again.
/:cl:

This segment got deleted somewhere along the line:
image

### CODE REVIEW

**Comment by ACCount12** [comment]
Can you please update this to new disposals format introduced in #32435? Update your branch, remove icon_state, change dir to one of the diagonals. If you can see the map icon after doing that, it worked.

**Comment by SpaceManiac** [comment]
I can look into it but it might be more appropriate to just update the whole map at once as a separate step, given that every other disposal pipe on the map is still using the old format.

**Comment by ACCount12** [comment]
I am preparing this right now. Going to be one hell of a pull request, but the conflicts with this one are unlikely.

**Comment by ShizCalev** [comment]
Closing in favor of AC's

**Pull request closed without merging**
