### PR TITLE
Makes venusflytrap mobs take fire and cold damage

### LINKED ISSUE #53854: Kudzu in icemoon wastes is pretty much unstoppable
Also known as: literally junglebox

Issue reported from  Round ID: [146637](https://scrubby.melonmesa.com/round/146637) (/tg/Station Sybil [ENGLISH] [US-WEST] [100% LAG FREE])
Reporting client version: 513.1532

It can grow over them in all directions, and there's a lot of big open areas around icebox that allow it to spread MUCH faster than it can be dealt with.

Also, venus human traps are overpowered - RANGED HARDSTUN, 25 melee damage, 60 object damage, no damage from wrong atmos, and being a simplemob it's also effectively fireproof.

### PR DESCRIPTION
**Pull request by timothymtorres**
## About The Pull Request

This PR fixes #53854 so that venus flytraps now take atmos damage from hot and cold areas.  

## Why It's Good For The Game

Venus flytraps were formerly _immune_ to fire and cold damage.  Now plasma fires and the coldness of space can hurt them.  Fire does double the damage compared to cold.  

At full health a Venus Flytrap will die in:

**~5 seconds inside of a fire**
**~10 seconds inside of space**

## Changelog
:cl:
balance: Venus Flytraps now take burn and cold damage.
/:cl:

### CODE REVIEW

**Comment by Fikou** [comment]
this is the wrong "fix" (the thing is intended apparently, so its more of a balance change), you should look how handle temperature damage works on simplemobs and look how venus traps change a factor, not hardcode a shitty proc for no reason

**Comment by IndieanaJones** [comment]
The reason why they're temperature immune is because space vines can do things like start fires and become temperature immune, which would then screw over the venus human traps when the vine they were made from was temperature immune and probably blazing but they weren't.  Now, the real chad-class move here is to possibly let venus human traps get in on inheritance from the vine which creates them, but if you try to do what you're doing right now you're going to cuck a bunch of venus human trap scenarios imo.

**Comment by timothymtorres** [comment]
> The reason why they're temperature immune is because space vines can do things like start fires and become temperature immune, which would then screw over the venus human traps when the vine they were made from was temperature immune and probably blazing but they weren't. Now, the real chad-class move here is to possibly let venus human traps get in on inheritance from the vine which creates them, but if you try to do what you're doing right now you're going to cuck a bunch of venus human trap scenarios imo. Also, the rate at which you made temperature damage kill them is stupid.

I think you are overestimating the effects of this small change.  Venus fly traps will have to play smart and avoid plasma fires.  (which is pretty easy to do, just don't be dumb)  I agree that inheritance would be nice to implement but that is more complicated functionality that I'm not concerned with.  My changes are a simple solution.  And the damage they receive from fire is because _they are plants_.  They are also `simple_mobs` that have 50 hp. (that also heal with every attack)

**Comment by tgstation-server** [comment]
Your Fix/Feature pull request delta is currently below zero (-3). Maintainers may close future Feature/Tweak/Balance PRs. Fixing issues or helping to improve the codebase will raise this score.

**Comment by MrStonedOne** [comment]
This pr is now the subject of research efforts at a university in the uk. lol.

**Pull request merged**
