### PR TITLE
New directional beach sprites and corners for the 2018 Summer Ball

### PR DESCRIPTION
**Pull request by CitrusGender**
New directional beach sprites! This is for the ball but it could be used for other things as well. 

firefox_2018-06-03_02-22-47

:cl: Beachsprites
imageadd: added directional beach sprites
/:cl:

[why]: # The only sprites we have previously were downwards beach sprites and this adds all directions and corners. Also makes beachstation possible.

Credit to twaticus for sending the sprites. I think I did it right but I guess I'll find out soon.

### CODE REVIEW

**Comment by msgerbs** [comment]
Beachstation when?

**Comment by Repukan** [comment]
I don't like sand. It's coarse and rough and irritating and it gets everywhere.

**Comment by SpaceManiac** [comment]
You don't need different icon states for each direction. The water, for example, is currently eight states. It could be combined into one state with eight directions. The sand will need two states but that's still more manageable than twelve. Once that's done you don't need a separate type for each direction either.

**Comment by CitrusGender** [comment]
oh someone lied to me then. Yeah I got that right now.

**Comment by octareenroon91** [comment]
>I don't like sand. It's coarse and rough and irritating and it gets everywhere.

Bio/EVA suits

**Comment by CitrusGender** [comment]
https://feen.us/l9ssb0on.mp4
Okay it works now.

Remind me to never do that at 4 am ever again.

**Review by SpaceManiac — APPROVED** [review]

**Comment by Bluespace** [comment]
I pray for a day when we'll have wavy water sprites.

**Comment by octareenroon91** [comment]
I imagined you said "heavy water" sprites and wondered if deuterium would ever be added.

**Pull request merged**
