### PR TITLE
Buffs viscerators

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
They now ignore armor and projectiles pass through them.

I never see these bought and they're little razor blade swarm things it'd make sense for them to be sharp/fly around riot shields and juke gunshots.

Projectiles going through them forces you to engage in the (sometimes tricky) pixel hunt of meleeing the tiny things, as well as ensures they can actually be used by nuke ops without immediately blasting them to pieces. A screen of razor death that you can fire through might actually be worth buying.

### CODE REVIEW

**Comment by Lumipharon** [comment]
100 armour pierce is pretty gud

**Comment by Zilenan91** [comment]
The grenades for these are like 6 TC right? If they're any more than that they're way overpriced.

**Comment by WJohn** [comment]
If people wanted these things to be worth a little more, I think it'd be nice to add some sort of "cowardly" melee AI, where they back out immediately after hitting you, before going for you again. It'd make hitting these guys in melee much harder.

**Comment by KorPhaeron** [comment]
Make shooting them a hell of a lot easier though.

I could make them jump a tile over rather than outright fleeing though

**Comment by Zilenan91** [comment]
Like actual manhacks from HL2. They hit you and kinda bounced away, making them really hard to hit and emphasizing timing so you could hit them with your crowbar before they hit you.

**Comment by KorPhaeron** [comment]
I think making projectiles automatically miss them (or having a very high chance) would be more of a buff than the melee juking honestly. A single laser kills them and you dont have to pixel hunt when shooting them

**Comment by Zilenan91** [comment]
That could work. They're not too good statistically.

**Comment by Steelpoint** [comment]
I thought the original intent with these Manhacks was to disperse normal crew members quickly and harass Security, not to be able to bypass all armour in the game and just as easily kill Sec/Capn as it does for a Assistant.

:-1:

**Comment by KorPhaeron** [comment]
Well currently they don't do shit to anyone you just walk away from them or hit/shoot them at your leisure.

Maybe I should have made them fast instead of armour piercing.

**Comment by Steelpoint** [comment]
If the problem is that they are not doing well even against non-armoured civilians then I would agree that making the Manhacks faster is better.

Giving them 100 AP does nothing to help kill civis better.

**Comment by KorPhaeron** [comment]
Remie made this whole AP system though and we have a grand total of one ninja katana and maybe some obscure RD ammo that uses it though. I'd like to see it in other things.

Figured flying razor blades that are never used currently would be a good place to put it.

**Comment by Steelpoint** [comment]
Does the Revolver still have some AP to it?

Just because we have some system in place does not mean we need to shoe horn it in to something else.

I don't want to drag out a argument but I've always held the Manhacks to be a area of denial tool against crew members, since they can do a lot of damage to them. Not something that can shred anyone with armoury apart.

Ops have their one hit stun/three hit crit weapons to do that.

**Comment by KorPhaeron** [comment]
I just don't see the ops needing that niche though. Greyshirts really aren't a huge threat, not enough to warrant spending 8 telecrystals on 5 shitty mobs that die in a single gunshot each.

And whatever they were intended for they're not effective at that role right now because they're not effective at anything.

**Comment by Steelpoint** [comment]
I just think buffing the Viscerators to have 100 AP is just shitting even more on Security and the Captain.

They already have to surmount a mountain to tango with Nuke Ops, now toss in a grenade that dispenses little shits that will not only out run you but completely ignore your (pathetic) armour.

If Sec/Cap armour was at the pre-nerf levels I would not be so negative towards the AP change, but as it stands I think its really just too much.

The speed buff is good, but the AP change is bad.

**Comment by Steelpoint** [comment]
Also please tell me that Density still allows for projectiles to hit them without having to click the sprite.

Cause if not then what the fuck are you doing.

**Comment by Firecage** [comment]
God no Kor. They are annoying as is. Sure, they are easy to kill, but a swarm of them can seriously would you in a closed space.

I don't mind the armour piercing at all, but projectiles passing through them? Even if they only had a high chance to do it? I don't want to bloody pixel hunt a tiny moving sprite while possibly moving myself.

**Comment by Dorsisdwarf** [comment]
idea: remove AP, give a 50% projectile juking chance, and make them faster than humans

**Comment by Lumipharon** [comment]
Why not just make them cheaper?

Honestly, manhacks are ok currently, it's just they're not very economical.

**Comment by Shapsy** [comment]
I've seen manhacks tear shit up, no pun intended, give them a shot, they're pretty good. No one smart it gonna stand there and attack them one by one when they're getting attacked by three hacks at once

**Comment by Shapsy** [comment]
Fuck I can't edit my last comment, but I was also under the impression that these were made to attack unarmored crew members primarily, over hard armored targets

**Comment by KorPhaeron** [comment]
I mean yeah the other option is that they're cheap.

"Area denial vs assistants" for half of an ops crytsal makes zero sense when you can buy 4 bulldog drums for the same cost and just kill both security and assistants.

**Comment by wflagg** [comment]
Could the AP be made a % chance? 1/4th of all hits are AP and have alternate text message.  Wiould make them much more dangerous in packs, but not buff singletons much.

also, making the projectile dodge Chance is good too. Most people just fire wildly anyway.

Having them bounce 1-2 squares immediately after a hit would also make them a bitch to deal with.

Collectively these changes should make only a minor difference if a group of people are fighting them, but would make it much more deadly to try and run in and solo them.

**Comment by PKPenguin321** [comment]
this is pretty cool :+1:

**Comment by Zilenan91** [comment]
Why'd you close this?

**Comment by KorPhaeron** [comment]
Don't want to argue so much over such a minor thing people didn't like the proposed change

**Comment by Zilenan91** [comment]
There wasn't that much opposition to it, you could probably merge this with little complaint.

**Pull request closed without merging**
