### PR TITLE
Adds the purple skirt; Changes some bad paths

### PR DESCRIPTION
**Pull request by Niknakflak**
image
Sprite recolor by Nienhaus

There's only three sprites that are the same and because it has a base black skirt part, they can't be done with the color var easily.  Otherwise I would, color var only works for completely one color sprites.

Changes paths from under/blackskirt and under/blueskirt/redskirt to just
under/skirt/color

### CODE REVIEW

**Comment by KorPhaeron** [comment]
more bloat

**Comment by PKPenguin321** [comment]
you know kor if you think about it why do we even have traitors or a space station for this atmos simulator? we need to remove everything but atmos features to remove bloat and go back to essentials

**Comment by KorPhaeron** [comment]
traitors enhance gameplay

a million costumes detract both from the aesthetics and the gameplay (good luck disguising as that lizard whole always wears a purple dress when you are a human)

obviously I'm just shitposting and this going to get merged, but I can't pass up this prime opportunity to grumble about it

**Comment by RemieRichards** [comment]
Go to bed Kor.

**Comment by Niknakflak** [comment]
Yea.

**Comment by PKPenguin321** [comment]
i agree that it making disguising a pain in the ass is bad but it's kind of been like that for a long time already and if we're not gonna go back we may as well go forward
purple skirts are the future you see

**Comment by Niknakflak** [comment]
I added them for a person who likes purple

**Comment by Niknakflak** [comment]
Begone haters

**Comment by ExcessiveUseOfCobblestone** [comment]
so where's that bee suit nik

**Pull request merged**
