### PR TITLE
normal sec headset

### PR DESCRIPTION
**Pull request by pudl**
adds sec headsets back into their locker, why would they be forced to wear the bowmans. i care more about aesthetics than the rare times i legitimately use a clusterbang (since a flashbang isnt enough to damage my ears permanently)

### CODE REVIEW

**Comment by Cheridan** [comment]
Uh, the bang protection also causes you to be stunned less, I believe. 

also jeez it's like 2 pixels does it really chafe you that much either way

**Comment by pudl** [comment]
yes

**Comment by WJohn** [comment]
More variety. MORE COSTUMES.

**Comment by Fox-McCloud** [comment]
Uh, it protects you against the stun+weaken duration unless you're on the same exact tile as it; not taking these is asking to get wrecked by fellow officers (accidentally) or antags.

Better question: why doesn't detective start with a bowman?

**Comment by pudl** [comment]
he gets one in his locker

**Comment by Jordie0608** [comment]
Changelog

**Comment by WJohn** [comment]
You should at least make the regular sec headset have the properties of the bowman, so you can choose your style and not be punished for it, like the warden and HoS's clothing alternatives have the exact same armor values.

**Comment by optimumtact** [comment]
Nah, this game is getting more and more boring with the lack of choices that have meaningful results.

if the player wants to use a substandard headset let them, let them make a meaningful choice for once.

**Comment by WJohn** [comment]
Watch how 99% of them go for the better headset because it is way better in powergaming terms.

At least TELL the players that the bowman headset is resistant to flashbangs.

**Comment by SconesC** [comment]
what the fuck lol why would you not wear bowmans

you flashbang stun yourself if you don't, there is literally no reason not to wear them

this could be cool if y'know this was about aesthetics, you had just made bowman properties on the normal-looking headsets

@Fox-McCloud Det starts with one in their locker

**Comment by pudl** [comment]
i just want to wear a normal headset, i dont care if bowmans made me fucking immune to all damage. i want the normal headset and there zero reason to not give the option

**Comment by Firecage** [comment]
Besides, I still say that the sprite of bowman headsets doesn't fit well with me.

**Comment by dannno** [comment]
"why wouldn't you wear bowmans"
why wouldn't you give someone the option not to

**Comment by SconesC** [comment]
i'd rather not have to consider if my flashbang will hurt my own team

but i mean if you want to option to hamstring yourself and the security team by all means go ahead

**Comment by Atskadan** [comment]
wow its almost like not everyone is in it to win it huh scones
looking cool precedes everything else

**Comment by Fox-McCloud** [comment]
@Atskadan 

After a player gets wrecked by a traitor a few times because they didn't have flashbang protection---well, it changes the way one can view things, and suddenly those few tiny pixels becomes....less important.

Either case, if officers want to gimp themselves, so be it, but giving bowman's a normal on character or object sprite is bad, IMO; it's an important gameplay mechanic and should be communicated to the player as such.

**Comment by Lumipharon** [comment]
Headsets aren't the only thing that provides flasshbang protection, you can just wear a helmet.

Also seriously who cares if normal headsets don't have the protection? ALL Bowmans have the protection, that's their gimmick. If you care about fashion, then who cares about buffs?

I used to (still do) wear a beret and no armor as a sec officer, back when berets weren't armored. Sure, it made me less robust, but that's the choice I made for FASHION.

**Comment by dannno** [comment]
@SconesC

**Comment by Atskadan** [comment]
fashion > powergaming

**Comment by Fox-McCloud** [comment]
living > fashion =p

**Comment by dannno** [comment]
are you suddenly under some kind of obligation to make sure that every player in the game has maximized their chances for survival?
if I want the normal headset give me the normal fucking headset
why would anyone care

**Comment by Fox-McCloud** [comment]
@dannno 

Nah, I'm just making a silly little jab at @Atskadan is all =p

**Comment by Jordie0608** [comment]
There's really nothing harmful about this, it's up to the officer to use which headset.

**Pull request merged**
