### PR TITLE
tgui numpad keycode defines

### PR DESCRIPTION
**Pull request by ZeWaka**
## About The Pull Request

tgui numpad keycode defines

## Why It's Good For The Game

tgui numpad keycode defines

### CODE REVIEW

**Comment by jlsnow301** [comment]
Keycode is deprecated, is there another solution?
https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyCode

**Comment by ZeWaka** [comment]
idc, just updating upstream with what we've added - not super interested in recoding stuff

**Comment by jlsnow301** [comment]
I don't want to encourage anyone to use this system given its deprecation. If you want to add these to keys.ts, that's fine

**Comment by ZeWaka** [comment]
ok

**Pull request closed without merging**
