### PR TITLE
Nerfs shocker circuit power usage

### PR DESCRIPTION
**Pull request by JJRcop**
Alternative to #32758
closes #32758
:cl: JJRcop
balance: Shocker circuits now take 120000 cell charge at max intensity.
/:cl:

### CODE REVIEW

**Comment by jughu** [comment]
there is no point buffing the power usage when you have a litteraly tesla pulling power out of apcs for you denying the whole power cost

**Comment by arsserpentarium** [comment]
Maybe restrict maximum intensity?

**Comment by arsserpentarium** [comment]
Or add cooldown

**Comment by Buggy123** [comment]
120,000 power per shock? Using 5 bluespace power cells per shock might be a _little_ excessive.

**Comment by ACCount12** [comment]
IC power consumption is kind of fucked up now, it's not that high.

**Comment by Buggy123** [comment]
Ah, weird.

**Comment by JJRcop** [comment]
Going to admit I am not great with numbers in this game.

**Comment by jughu** [comment]
it is fucked up because tesla module 
LOL

**Pull request closed without merging**
