### PR TITLE
Adds Allergic reactions to a few things (Bee stings, Beer)

### PR DESCRIPTION
**Pull request by MrMelbert**
## About The Pull Request

The following effects will trigger allergic reactions for the "Food Allergy" quirk
- For Alcohol allergies:
   - Drinking any ethanol (beer, wine, etc) 
- For Bug allergies:
   - Drinking ants
   - Getting stung by a bee
   - Getting bit by a (giant) ant
   - Getting bit by a (giant) spider 
- For Sugar allergies:
   - Drinking Sugar

Other notes
- Any mob undergoing surgery will benefit from ethanol speeding it up, rather than just carbons

## Why It's Good For The Game

I saw a random discord comment that said "Bee stings should trigger bug allergies" and I thought it was funny, so I added it, then I thought I could add similar triggers to a few other things. 

Important to note for the reagent based effects, they only trigger on ingestion. And on top of that, it's a % chance to trigger, scaling with the amount you drink at once. So you can sneak a sip of alcohol if you want to roll the dice (I figure if I made syringes kill you, I'd have to up the point reward, which I don't want to bother with)

## Changelog

:cl: Melbert
add: Drinking any ethanol (beer, wine, etc) will trigger alcohol allergies 
add: Drinking ants will trigger Bug allergies
add: Getting stung by a bee, or bitten by a (giant) ant or (giant) spider, will trigger bug allergies
add: Drinking plain sugar or caramel will trigger sugar allergies
qol: Ethanol can speed up the surgeries of any mob type applied to, rather than solely humans.
/:cl:

### CODE REVIEW

**Comment by Loafin34** [comment]
what about getting bit by a giant ant?

**Comment by MrMelbert** [comment]
I didn't advertise that as a quality of life

**Comment by the-orange-cow** [comment]
Bee/spider/bug sting/bite allergic reactions are rather distinct from food injection.  Just a thought, but might this be better served as a distinct trait?

**Comment by YakumoChen** [comment]
The alcohol food type is only in like two foods total, so this makes the allergy a lot less free, which is good

Same for bugs, another free allergy trait, good add.

**Comment by MrMelbert** [comment]
> Just a thought, but might this be better served as a new trait?

I can just drop the "Food" part of the quirk name but I think that messes with saves

**Comment by Deadgebert** [comment]
I'm assuming getting bit by ants means walking over them? That might be a little bit too common of an occurrence and a bit too unavoidable at times. You'll get bit regardless of walking/running and I believe crawling over them. Other things look great but that alone might be a bit too debilitating to be usable

**Comment by MrMelbert** [comment]
Does not trigger on ant (decal) no, just ant (mob)

**Comment by DaCoolBoss** [comment]
Sugar reagent allergy could be expanded to cover caramel reagent too. Also saline-glucose solution, but that might be a little too disruptive.

**Review by Ghommie — APPROVED** [review]
Looks good to me, though I'd lower the odds of getting instant anaphylaxis from a bug attack and add some itching powder / histamine per attack instead. Also what DaCoolBoss said about caramel.

**Comment by Ghommie** [comment]
@MrMelbert he's kinda right. It should be renamed to just Allergy I guess.

**Comment by MrMelbert** [comment]
image

**Pull request merged**
