### PR TITLE
REVERT: Changes fireman carrying from a trait on gloves to a skillchip

### PR DESCRIPTION
**Pull request by SuperNovaa41**
## About The Pull Request

Reverts the moving of nitrile gloves quick carry to a skill chip

## Why It's Good For The Game

This gives some genuine purpose back to the nitrile gloves, as well as gives more than just paramedics and the CMO the ability to gain this trait. 

Also a nice moth maint said he wanted this ok? 

## Changelog
:cl:
add: Nitrile gloves have the quick carry trait again.
del: The quick carry skill chips have been removed.

/:cl:

### CODE REVIEW

**Comment by SuperNovaa41** [comment]
> 
> 
> Nitrile and Latex gloves don’t really have much difference irl to my knowledge (the two that come to my head are allergies and some reactions you might prefer one over the other for safety), why do the gloves REQUIRE a genuine purpose outside of vanity (compared to latex) in game?

I personally liked having the trait built into gloves rather than relying on a skill chip, plus like I said it allows for more than just paramedics, and who ever raids the CMOs locker to actually get this quirk, it's very useful to have in medbay

**Comment by Mickyan** [comment]
You're making arguments in favor of making the skillchips more available, not why they should be removed for the gloves

**Comment by necromanceranne** [comment]
There are like seven Quick Carry chips in a box in each medical locker, and four Quicker Carry chips from the CMO's locker. I'm not even sure nitrile gloves are more abundantly available than that, so surely it isn't an availability problem.

Quite frankly, if mothblocks wants to start reverting the transition of job skills into skillchips, he probably should make some more formalized statement about why he is telling people to do that. 

Because I ALSO have been told by other maintainers to start moving away from introducing gear based skill stuff and putting it into skillchips instead, and have been blocked on some changes as a result. That's why I made the original PR.

**Comment by SuperNovaa41** [comment]
> 
> 
> There are like seven Quick Carry chips in a box in each medical locker, and four Quicker Carry chips from the CMO's locker. I'm not even sure nitrile gloves are more abundantly available than that, so surely it isn't an availability problem.
> 
> Quite frankly, if mothblocks wants to start reverting the transition of job skills into skillchips, he probably should make some more formalized statement about why he is telling people to do that.
> 
> Because I ALSO have been told by other maintainers to start moving away from introducing gear based skill stuff and putting it into skillchips instead, and have been blocked on some changes as a result. That's why I made the original PR.

As for the quick carry chips, I was completely unaware of those being there, I've never seen them myself.
Mothblocks didn't really give me a reason as to why HE wanted them reverted, I just mentioned I wanted them back and he said he wanted to revert the PR.

**Comment by necromanceranne** [comment]
I'll be honest, the traits being split between Quick Carry and Quicker Carry was mostly because latex gloves were very, very widely available and there is maybe three nitrile gloves, maybe four, in and around the station beyond the pair paramedics spawn with. I would have just combined them into a single trait but I didn't want to make too many radical changes all at once.

**Comment by necromanceranne** [comment]
> Mothblocks didn't really give me a reason as to why HE wanted them reverted, I just mentioned I wanted them back and he said he wanted to revert the PR.

Sure, but if your goal is just to make quicker carry more available to medical staff as a whole (spoiler, it doesn't, there are extremely little nitriles), you can accomplish that task by just removing the redundant ant haul and quick carry and keeping the actual useful trait in RES-Q/Quicker Carry. All medical staff have ant haul shift start, so it isn't a major departure from what they have already.

If mothblocks wants a revert he can do it himself. It probably won't accomplish what you want to accomplish.

**Comment by SuperNovaa41** [comment]
> 
> 
> > Mothblocks didn't really give me a reason as to why HE wanted them reverted, I just mentioned I wanted them back and he said he wanted to revert the PR.
> 
> Sure, but if your goal is just to make quicker carry more available to medical staff as a whole (spoiler, it doesn't, there are extremely little nitriles), you can accomplish that task by just removing the redundant ant haul and quick carry and keeping the actual useful trait in RES-Q/Quicker Carry. All medical staff have ant haul shift start, so it isn't a major departure from what they have already.
> 
> If mothblocks wants a revert he can do it himself. It probably won't accomplish what you want to accomplish.

Hmm yeah actually that's a fairly good point. I also wanted this reverted for another feature I had planned, but other than that I genuinely can't think of another reason as to why these should be removed.

**Pull request closed without merging**
