### PR TITLE
Fixes drones being unable to be revived by other drones

### PR DESCRIPTION
**Pull request by ghost**
Also allows dead drones to have their laws reset and adds spans to some of the messages that lacked them.

### CODE REVIEW

**Comment by JJRcop** [comment]
Whoa whoa I added that for a reason, what's the problem?

**Comment by Xhuis** [comment]
@JJRcop The variable was causing some issues. If you want it added back, please tell me how you want it implemented since I didn't understand the old code very well and I will do my best to add it.

**Comment by JJRcop** [comment]
eh trying to fix it doesn't really... work... ok i guess its ok

**Comment by Xhuis** [comment]
This is merge-ready

**Comment by JJRcop** [comment]
You know what I might give it another shot. Apparently the problem is that you must update brute damage, not health, because life will make health match brute damage, not the other way around like I remember.

**Pull request merged**
