### PR TITLE
Unlocks AI Multicamera Mode

### PR DESCRIPTION
**Pull request by Cruix**
See #37695

:cl:
add: AIs can now use multicamera mode freely.
/:cl:

It has been in the game as an admin-only feature for three months now, it is time for it to be actually added or completely removed.

### CODE REVIEW

**Comment by MrDoomBringer** [comment]
wait this hasnt been in game this whole time? huh

**Comment by Potato-Masher** [comment]
The time is now or never.

**Comment by WJohn** [comment]
Isn't this feature still fundamentally a huge pain in the ass for traitors who are trying to be sneaky by making the AI even more omnipresent than it already is?

**Comment by Potato-Masher** [comment]
Yeah. I will admit, this will definitely complicate some things for traitors or other antags.

But, as noted many times in the original PR, there are quite a number of ways to deal with it, not even including the buffs to the AI Detector Multitool.

Not sure. I really do want to see this cool feature in action, but at the same time, I wonder what the overall effects will be. If it does end up being super disruptive to the original game flow then we can always back up and restrict behind R&D or something.

**Comment by JJRcop** [comment]
Shoot out cameras!

**Comment by Daundra** [comment]
Changelings have an EMP scream, tators have EMP nades, that camera multitool, the woefully underused camera bug, gosh darnit, just buy a damn hacked AI upload board and rob tech storage in less than 10 minutes if you absolutely are that worried about an AI messing with you. 

consider that by using multicamera feature the AI is restricting their field of view between these separate cameras, and that's the balance of it. you're looking at best an AI might catch you with their 3x3 camera zooming around the armory in space, you could just cut the camera before they can examine you, or even just have your ID off! literally the only downside I see is that sec might get alerted quicker which if you know what you're doing you've already planned for this. 

I fully hope this gets added and plan to use it myself in conjunction with normal camera mode. they both have their ups and downs (seriously, I got multicam mode turned on once and trying to track a person running around with only like 3x3 or 4x4 camera size is fucking awful)

**Comment by CRTXBacon** [comment]
Having used multicamera a few times I feel that it is well balanced as it is. The field of view you'll have to use to fit 6 cameras on one screen does mean you won't be able to see much in that particular area without leaving multicamera view. Most admins are also happy to enable your multicamera when asked anyway.

**Comment by BeeSting12** [comment]
It takes two clicks and under a second to disable a camera.

**Comment by ExcessiveUseOfCobblestone** [comment]
Enable it so the demise is faster.

**Comment by ExcessiveUseOfCobblestone** [comment]
Memes aside, I think if people played AI with this activated they'd see it's not THAT bad.

**Comment by AdamElTablawy** [comment]
having used this several times it's pretty situational and not altogether that great, especially since you're blind to everything else while using it. should be fine.

**Comment by optimumtact** [comment]
This is a server config.

**Comment by optimumtact** [comment]
Apparently it is is not, please make it a server config instead of enabling it to on.

**Comment by Cruix** [comment]
I don't feel like spending more time on this feature, for a game I almost never play, when a maintainer has made it clear that they will close it without even bothering to look at it.

**Comment by optimumtact** [comment]
your loss

**Comment by ExcessiveUseOfCobblestone** [comment]
lol

**Pull request closed without merging**
