### PR TITLE
Makes nicotine kill pests.

### PR DESCRIPTION
**Pull request by nemvar**
## About The Pull Request

Makes nicotine kill pests. It's just as effective as bug spray, but more toxic.

## Why It's Good For The Game

Nicotine is used as a pest killer IRL and this adds a ghetto way of removing pests from plants.

Especially ashwalkers *surprise surprise* are effected by this since they can now use mushroom to remove the pests.

Maybe I make PRs a bit too atomic.

## Changelog
:cl:
add: Nicotine now kills pest and add toxicity when added to a plant tray.
/:cl:

### CODE REVIEW

**Comment by vuonojenmustaturska** [comment]
nicotine is afaik not particularly toxic to plants, you could even reduce the toxicity to below that of pest spray

**Comment by nemvar** [comment]
Yeah, but I don't want to powercreep on pest spray.

**Comment by FantasticFwoosh** [comment]
So nicotine wouldn't have toxicity towards insect player races? (Another time, with maintainer approval)

**Comment by necromanceranne** [comment]
more ashwalker buffs yay! Maybe it will eventually be tolerable to play. They really do need it now that they can't invade the station.

**Comment by Tlaltecuhtli** [comment]
they need more ghetto shit

**Comment by JStheguy** [comment]
> Yeah, but I don't want to powercreep on pest spray. Why have specialised tools when they are worse than the ghetto version?

Because the label on the pest spray bottle is, like, wicked cool and says it has Electrolytes, what the plants crave!

**Comment by ExcessiveUseOfCobblestone** [comment]
> 
> 
> So nicotine wouldn't have toxicity towards insect player races? (Another time, with maintainer approval)

so in other words we need ANOTHER way to btfo moths and flies lol?

**Review by ninjanomnom — APPROVED** [review]

**Pull request merged**
