### PR TITLE
Space vines can no longer spread on transit turfs

### PR DESCRIPTION
**Pull request by coiax**
:cl: coiax
fix: Spacevines can no longer spread on space transit turfs.
/:cl:

Transit turfs aren't actual locations, they're the hyperspace whizzing
past the shuttle. Otherwise there's a strong possibility of being able
to grief Z2 with vines by planting them on a shuttle.

### CODE REVIEW

**Review by Cyberboss — CHANGES_REQUESTED** [review]
You should reattempt each direction because this proc expects something to be spawned because of it

**Comment by KorPhaeron** [comment]
Just make it call entered() on the turf it spreads to and the transit will throw it/lava will burn it/chasms will drop it and you won't need a snowflake turf

**Comment by Razharas** [comment]
This is the oipposite of what i wanted to accomplish

**Comment by KorPhaeron** [comment]
Razharas why

**Comment by coiax** [comment]
No, he made the changes, it's just not showing up.

**Pull request merged**
