### PR TITLE
Improved chemistry tips, fixed Holy Explosion oversight

### PR DESCRIPTION
**Pull request by carlarctg**
## About The Pull Request

Plastic sheets chemist tip is more in-depth and clear

Added holy explosion chemist tip

## Why It's Good For The Game

Tips good!

## Changelog

:cl:
qol: Plastic sheets chemist tip is more in-depth and clear
qol: Added holy explosion chemist tip
/:cl:

### CODE REVIEW

**Comment by the-orange-cow** [comment]
Meta way to verify whos a heretic.

**Comment by carlarctg** [comment]
> Meta way to verify whos a heretic. 

Not sure how you think using a niche explosive reaction that will breach the hull will somehow become a meta way to run around unmasking heretics? People don't use this in cult rounds, they won't use it in heretic rounds.

**Comment by AtomTheProphet** [comment]
> > Meta way to verify whos a heretic.
> 
> Not sure how you think using a niche explosive reaction that will breach the hull will somehow become a meta way to run around unmasking heretics? People don't use this in cult rounds, they won't use it in heretic rounds.

Why would a holy explosion ignite heretics? They're not influenced by holy water and chaplains aren't usually their enemy unless they're a sacrifice target.

**Comment by the-orange-cow** [comment]
I'm not veey code savvy, but will any size holy explosion ignite heretics?  If so, he's what will happed:

A heretic rift will be sighted.
Sec asks chap to bless a water cooler, then grabs a few beakers of potassium.
Anyone who does anything remotely sus will be arrested, and a sec officer wearing the sec bombsuit will stand over them and mix 1u holy water with 1u potassium.

Cult is different to heretics, in that it very quickly becomes obvious very early that heretics are a thing due to rifts, where as an even remotely competent cult will keep their existance under wraps for as long as possible.

**Review by MrMelbert — CHANGES_REQUESTED** [review]
Yeah igniting heretics ain't it chief, you can add a unique reaction for heretics being hit by it but it can't be an obvious tell (being lit on fire)

**Comment by ZephyrTFA** [comment]
What they don't tell you is that it only works for a reaction amount of 150.

**Comment by mikederkan** [comment]
i'm really sorry but did anyone read the tip? it says "If at least 75 units of both are used, the explosion will reveal, ignite, and paralyze any cultists, heretics, and revenants in sight. Do it!" 75 units of both is huge... that's not gonna be a meta check

**Comment by carlarctg** [comment]
> I'm not veey code savvy, but will any size holy explosion ignite heretics? If so, he's what will happed:
> 
> A heretic rift will be sighted. Sec asks chap to bless a water cooler, then grabs a few beakers of potassium. Anyone who does anything remotely sus will be arrested, and a sec officer wearing the sec bombsuit will stand over them and mix 1u holy water with 1u potassium.
> 
> Cult is different to heretics, in that it very quickly becomes obvious very early that heretics are a thing due to rifts, where as an even remotely competent cult will keep their existance under wraps for as long as possible.

Please read the, uh... basically anything next time? THE TIP says it needs a goddamn EXPLOSION? that BREACHES THE HULL? Come on.

> Edit: if a larger amount is required, they can get a similar effect by forcing the heretic to wear the bomb suit, cuff them to a chair on reinforced floor, and chuck a holy grenade at them.

This won't happen. This will never happen. The same thing can be done right now by doing surgery on a heretic and seeing if they have a living heart or not. Or putting their brain in an MMI and forcing them to say if they were one or not. You are doing mental gymnastics.

@MrMelbert I would like to request a re-review because a hull-breaching grenade isn't going to be a easy way to look for heretics

**Comment by carlarctg** [comment]
big gay

**Comment by GPeckman** [comment]
Looking at the code, to affect someone one tile away from the explosion you need to have a created_volume of at least 48. This much created volume would give and explosion power of (0, 1, 2). Not quite enough to cause a breach, but certainly enough to cause severe injury. Doing it with just 1u of each would work on the same tile, however (holyboom would call get_hearers_in_view with radius 0, and that function is specifically designed to check the center turf if the radius is 0). Given that small doses of normal water and potassium can be used to purge chems, I don't think this would be dangerous to anyone involved.

Its possible that seccies could abuse this, but they already do things like scan rifts for prints and treat poppies and harebells as highly illegal contraband. I don't think this will change things much.

**Comment by ExcessiveUseOfCobblestone** [comment]
i just saw the other tag is qol u r very sick man.

**Pull request merged**
