### PR TITLE
Fixes MMI's hearing cult chat sometimes.

### PR DESCRIPTION
**Pull request by AnturK**

### CODE REVIEW

**Comment by actioninja** [comment]
`|=` is a lot more complex than `+=`, gets a _lot_ slower the bigger the list is. You sure this isn't going to cause lag issues for deaths in late round?

**Comment by Fikou** [comment]
does it fix MMI's hearing holopara chat

**Comment by loserXD** [comment]
yes it does

**Comment by AnturK** [comment]
If anyone feels like doing boring work, you could turn this into assoc list.

**Pull request merged**
