### PR TITLE
Buffs OOC ban

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
Now applies to deadchat

### CODE REVIEW

**Comment by lzimann** [comment]
Is it even necessary..

**Comment by xxalpha** [comment]
Dead chat?

**Comment by CPTANT** [comment]
But why?

 OOC bans are almost always for IC in OOC, deadchat doesnt have IC/OOC rules so whats the point.

**Comment by Zilenan91** [comment]
Can't admins ban people from deadchat already?

**Comment by MrStonedOne** [comment]
ya, it seems like it would make sense to just make a ban from deadchat, to extend the mute from deadchat to more rounds

**Comment by KorPhaeron** [comment]
>OOC bans are almost always for IC in OOC

Not in my experience. They're for people like punches or deathhoof that rile OOC up, and deadchat is basically an extension of ooc

**Comment by Zilenan91** [comment]
Just ban those people

**Comment by Cheridan** [comment]
Yeah, IC in OOC is a server ban. OOC bans are for attention whores.

**Comment by Cheridan** [comment]
Kor's mergebegging at me, so I'm going to merge this on the basis that persistent OOC Bans are rare, and if you're that obnoxious then we probably don't want you ranting in deadchat either. I don't think we need separate bans for each and every little thing.

**Pull request merged**
