### PR TITLE
Adds the ability to soft filter words, also fixes some word filter bugs

### PR DESCRIPTION
**Pull request by NamelessFairy**
## About The Pull Request
This PR allows config editors to be able to set strings to be soft filtered, soft filters ask players to confirm that they want to send the message after they enter it, selecting yes notifies admins incase the soft filter is being passes illegitimately. 

Also fixes an issue with deadchat being unfiltered and filters being case sensitive when giving their reasons

MSO said they wanted this but did not directly request it
CC @MrStonedOne

## Why It's Good For The Game

Allows filters to be created for words that are not 100% filterable
Makes sure players are aware of the risks before sending a message that is soft filtered
Allows admins to be alerted when phrases that may require intervention are said

## Changelog

:cl:
qol: Word filters now support soft filtering, allowing players to say a word only after they confirm wanting to say it after a warning.
fix: Deadchat is now effected by OOC word filters
fix: A reason for a word being filtered will now be displayed nomatter what case the word is in
config: Adds new config options for soft filters
admin: Admins will get notifications when a soft filtered word is said
/:cl:

### CODE REVIEW

**Comment by NamelessFairy** [comment]
> Snip
I did also add a bit of text in the config to warn people that they must always be lowercase as an additional temporary solution

**Comment by Colovorat** [comment]
I'm not sure filtering dead chat is a good idea. you sometimes just wanna speak with some leet speak or whatever, because it makes it a lot easier. Ghosts are literally OOC, why block them out of those words

**Comment by NamelessFairy** [comment]
> I'm not sure filtering dead chat is a good idea. you sometimes just wanna speak with some leet speak or whatever, because it makes it a lot easier. Ghosts are literally OOC, why block them out of those words

The ghost chat fix only filters using the OOC term filter, things that are filtered ICly but not OOCly can still be said

**Review by Mothblocks — CHANGES_REQUESTED** [review]
I would not be shocked if `say` was never meant to truly yield like this, I'll look into that later.

**Comment by ATH1909** [comment]
time to ensure that my name includes one of these words so that it'll take slightly longer to call me out as I gank you

**Comment by optimumtact** [comment]
stupid fucking filter, stupid fucking PR

**Comment by Mothblocks** [comment]
i'm gonna get on this just have not been able to put the time into it

**Review by Mothblocks — CHANGES_REQUESTED** [review]
Some last needed changes to the logs

**Pull request merged**
