### PR TITLE
(for real this time) changes kilo xenobio, botany, upload, and changes kilo sci floors

### PR DESCRIPTION
**Pull request by Dabger1**
## About The Pull Request

this is an update to my previous PR (now closed) about making some edits to kilo's xenobio, botany, and genetics, now including floor edits for all of sci, and a smaller upload room

## Why It's Good For The Game

kilo is held in low regard in general, this aims to (hopefully) improve its standing while making some minor adjustments to (in my opinion) the worst areas to work in which hopefully makes them nicer places to work overall.

## Changelog

changes in kilo station science: replaced the showroom floor to normal floor tiles to make the markings look better and more clear, added a new DNA scanner to genetics, added 2 new pens to xenobio, moved the xenobio disposal chute, biohazard closets from xenobio maint, a slime management console, the monkey recycler, and added a slime processor into the new space. moved the chem master to where the moved console was and placed a second fridge where the monkey recycler was.
changes in kilo station botany: removed the wall to the closet, opening up the space a bit.
changes to kilo station upload: made ai upload smaller and moved the west turret to the southeast corner.
changes to kilo station botany maints: as a result of shrinking ai upload, maints got wider by two tiles, and added loot to populate the new space.
added cable runs to the reinforced windows in botany maints to fix a powernet issue i was having 

##screenshots of edits
ai upload new kilo
botany new kilo
genetics new kilo
sci floors
xenobio new kilo

:cl:
add: added two new xenobio pens to kilo xenobio and expanded the kill room in kilo xenobio to a 2x3 instead of a 2x2
add: changed kilo science floors to normal iron floors (purple didnt look good on showroom flooring)
add: added a new DNA scanner to kilo genetics
del: shrank kilo upload a little
del: removed the wall in kilo botany to the closet
del: shrank the kilo monkey pen by a 1x3 size
qol: did some shuffling of kilo xenobio disposal chute and a slime management console
/:cl:

### CODE REVIEW

**Comment by LemonInTheDark** [comment]
Botany changes make me sad, I liked how it felt unique, sorta curved with the shape of the station

**Review by Maurukas — CHANGES_REQUESTED** [review]
Looks good. Glad to see someone working on the map. I have two things:

Would you take a look at this blobby decal bit in the middle of xenobio? This looks irregular and like it may be a mistake:

image

Second, please merge master to pull in the Byond 515 changes. Then we're good to go.

**Comment by Dabger1** [comment]
> Looks good. Glad to see someone working on the map. I have two things:
> 
> Would you take a look at this blobby decal bit in the middle of xenobio? This looks irregular and like it may be a mistake:
> 
> image
> 
> Second, please merge master to pull in the Byond 515 changes. Then we're good to go.

what do you mean by blobby decal?

**Review by Maurukas — CHANGES_REQUESTED** [review]
Can you double check your merge? It looks like something has gone wrong and this is reverting #70983 on Kilo.

It may be easier just to add the APC and area back to the evidence room.

**Comment by Dabger1** [comment]
> Can you double check your merge? It looks like something has gone wrong and this is reverting #70983 on Kilo.
> 
> It may be easier just to add the APC and area back to the evidence room.

did that just now, matching the screenshot best i could

evidence fix

**Comment by Maurukas** [comment]
I apologize. I completely missed this before it got conflicted again. One more time?

**Pull request closed without merging**
