### PR TITLE
Revert "Revert "Smooth out gliding so movement isn't (as) jerky""

### PR DESCRIPTION
**Pull request by optimumtact**
Reverts tgstation/-tg-station#11467

will work correctly given fps set to multiples of 10

### CODE REVIEW

**Comment by bgobandit** [comment]
first

**Comment by optimumtact** [comment]
hey, why do I get the fuck tag

**Comment by Steelpoint** [comment]
I think cause its a revet of a revert of a feature.

**Comment by MrStonedOne** [comment]
There is still the issue that with the gravgen turned off, or if you are in space, you insta move to the rate of fps, meaning higher fpses cause you to move way to fucking fast.

**Comment by Steelpoint** [comment]
Are we sure this is working because I just loaded this and its really weird.

**Comment by MrStonedOne** [comment]
go to the config and set the fps to 10fps or 20fps

**Comment by Steelpoint** [comment]
I am but the movement is, I can't put a word to it but its very jittery even more so than prior.

At 30+ its fine but at that point everythings moving very fast, or more accuratly its very very smooth to a fault.

**Comment by Miauw62** [comment]
>complains about game being jittery
>game made smooth
>too smooth

**Comment by MrPerson** [comment]
Mmm... I'll have to do some more testing, I suppose. Don't merge this just yet.

**Comment by Steelpoint** [comment]
@Miauw62 If you stopped shitposting for more than 30 seconds maybe you can try out the PR and see the problem yourself.

**Comment by bgobandit** [comment]
don't forget to test grabs and pulls

**Comment by optimumtact** [comment]
it takes a while to get used to it because you're so used to the janky movement believe me.

**Comment by MrPerson** [comment]
Pulling is a trivial fix, I just don't want to bother until I'm sure the system as a whole is viable.

**Comment by Razharas** [comment]
I tested this with many fps from 10 to 20 and it feels like theres no gliding on
This is not good enough, even jitteriness is better than this
Verdickt - denied

**Comment by optimumtact** [comment]
You're doing something wrong then

**Pull request closed without merging**
