### PR TITLE
Module duplicator has cheaper costs for circuit duplication

### LINKED ISSUE #77158: Circuits are way too expensive in the module duplicator.
## Round ID:

[211137](https://scrubby.melonmesa.com/round/211137)

## Testmerges:

None as far as I can tell.

## Reproduction:

Make a circuit. Put it into a module duplicator. It will be extremely overpriced compared to the cost of remaking it from scratch.

### PR DESCRIPTION
**Pull request by SyncIt21**
## About The Pull Request
Fixes #77158

> this is pretty clearly a relic of the resource cost rebalance.

Yes it is. `cost_per_component` var had a fixed value of 1000. Now it's value is 1 /10th of `SHEET_MATERIAL_AMOUNT `

Also added some autodocs for vars

## Changelog
:cl:
fix: Module duplicator has cheaper costs for circuit duplication
/:cl:

### CODE REVIEW

**Comment by Watermelon914** [comment]
You can probably decrease the value even more, it should more or less be 1/10th the cost of a material sheet.

**Comment by Terra1** [comment]
> You can probably decrease the cost even more, it should more or less be 1/10th of a material sheet.

The "economy of scale" of mass-duplicating an IC would probably make them more attractive to learn, yeah.

**Comment by AtomTheProphet** [comment]
> > You can probably decrease the cost even more, it should more or less be 1/10th of a material sheet.
> 
> The "economy of scale" of mass-duplicating an IC for dirt cheap would probably make them more attractive to learn, yeah.

I support this idea. Materials would be much less of a concern for circuitry and would make things easier to work with.

**Comment by SyncIt21** [comment]
Done

**Pull request merged**
