### PR TITLE
Revert "Skin Rework"

### PR DESCRIPTION
**Pull request by MrsTonedOne**
Reverts tgstation/-tg-station#14963

I told you @neersighted you need something to indicate it's a button on the buttons.

Also, apparently people don't like the new font for the input box.

### CODE REVIEW

**Comment by ChangelingRain** [comment]
>kneejerk reverts instead of feedback

**Comment by MrStonedOne** [comment]
@neersighted has like 24 to 48 hours to fix it before this gets merged anyways.

**Comment by Shapsy** [comment]
Please merge this, the text in the text bar is bigger and gets cut off at the bottom, and the grey color when hotkey mode is active keeps throwing me off because I keep thinking that I'm still in typing mode

**Comment by Iamgoofball** [comment]
do you guys not have any concept of "things can be fixed" or is kneejerk reaction the only language you speak

**Comment by Incoming5643** [comment]
!!should have just been a test merge!!

**Comment by neersighted** [comment]
[!FIXED](http://i.imgur.com/bNU5lxn.png)

**Comment by swankcookie** [comment]
honestly the only problem for me is the font.

**Pull request closed without merging**
