### PR TITLE
Makes drinking glasses smash when thrown

### PR DESCRIPTION
**Pull request by ShizCalev**
The bottles which could smash were inconsistent, this corrects it.

🆑 ShizCalev
fix: Throwing drinking glasses and cartons will now consistently cause them to break!
/🆑

### CODE REVIEW

**Comment by ACCount12** [comment]
Weren't bartenders able to throw glasses around without breaking them?

**Comment by ShizCalev** [comment]
Spilling, it seems. Thanks for pointing it out, fixed.

**Comment by nicbn** [comment]
Can we make beer bottles break too while you are in it?

**Comment by ShizCalev** [comment]
They do smash.

**Comment by nicbn** [comment]
The beer ones don't.

**Comment by YPOQ** [comment]
Minor issue: The shard from breaking a drinking glass is worth more than the cost to produce a drinking glass from an autolathe. Of course there’s already several ways to replicate metal/glass so it’s probably not worth worrying about.

**Comment by ShizCalev** [comment]
https://imgur.com/LbSs2MO

**Pull request merged**
