### PR TITLE
Taunting Tirade is more true to its intent

### PR DESCRIPTION
**Pull request by ChangelingRain**
:cl: Joan
experiment: Taunting Tirade now leaves a confusing and weakening trail instead of confusing and weakening everyone in view.
/:cl:

Okay massive aoe confusion is dongs and needs to go i really should have done this sooner

### CODE REVIEW

**Comment by coiax** [comment]
Just increase the cost or tier, don't take away the AOE confusion. It is fun and hilarious.

**Comment by ChangelingRain** [comment]
The AOE confusion is just too strong. If you want AOE disables, try belligerent instead; this was never intended to be a 'fuck every enemy in the area' skill.

**Comment by coiax** [comment]
Well instead of this move and chant thing, can't you just poop out a confusing rainbow trail for 15-30 seconds?

**Comment by scoopscoop** [comment]
I've never even seen anyone use tirade before and it's getting nerfed

**Pull request merged**
