### PR TITLE
Fixes a BUNCH of atmos shit

### LINKED ISSUE #11624: Atmos is broken at roundstart
Atmospherics is broken at roundstart, there is no air flowing in or out of the N2, O2, or Air supply in atmosia (the harmful gas tanks are also broken). All the gas flow meters to the tanks show 0 kPa. Distro loop is at 600 something kPa with a 50/50 mix of O2 and N2. There is no new air moving into distro.

broke

### PR DESCRIPTION
**Pull request by duncathan**
Fixes a race condition causing roundstart runtimes with certain atmos components.
`/obj/machinery/New()` called `power_change()`, which one certain components called `update_icon_nopipes()`. `update_icon_nopipes()`, on those components, included a check for `NODE1` before `nodes.len` was set in `/obj/machinery/atmospherics/New()`. The solution was simple; I just moved the list initialization to /before/ `..()` was called.

Also fixes two separate but related issues regarding manual valves and the TEG.

I ALSO fixed roundstart atmos.(Fixes #11624)

### CODE REVIEW

**Comment by bear1ake** [comment]
You have some runtimes.
I'll show log later, i'm a bit busy now.

**Comment by duncathan** [comment]
Ugh

**Comment by bear1ake** [comment]
https://dropmefiles.com/7are1

**Comment by duncathan** [comment]
Okay, I think I got it @bear1ake.

**Comment by bear1ake** [comment]
atmos doesn't work
scrnshot1
i'm trying find errors in code

**Comment by duncathan** [comment]
OK that's bizarre
Steps to reproduce please; is that always happening? Because it never showed up in testing on my end

**Comment by bear1ake** [comment]
@duncathan 
Yes, problem with vents in atmos happening always.

**Pull request merged**
