### PR TITLE
Fix sleep status effect not processing

### PR DESCRIPTION
**Pull request by FlufflesTheDog**
## About The Pull Request
Some fixes in #77219 brought up some weirdness with the sleep status effect. Healium would perma-sleep people, and sleeping in general lost the ability to heal minor wounds. 
## Why It's Good For The Game
Fix bugs, wow healium is abusable right now
## Changelog
:cl:
fix: Taking a nap can once again heal minor wounds
fix: A breath of healium will no longer knock you out for eternity
fix: Healium sleep now respects sleep immunity
/:cl:

### CODE REVIEW

**Comment by MrMelbert** [comment]
It looks like it's supposed to set `tick_interval = -1` if they ARE sleep immune, not if they are NOT

**Comment by MrMelbert** [comment]
That makes me wonder just how long this has been broken

**Comment by FlufflesTheDog** [comment]
> It looks like it's supposed to set `tick_interval = -1` if they ARE sleep immune, not if they are NOT

Hmm. That would make sense. I admit I didn't test to confirm it was the linked pr that broke things, but I know sleep-healing for example worked sometime much more recently than whenever that line was added.

**Comment by CCC23** [comment]
sleep immunity has always been broken it only seems to like to work if you have a stun immunity granting thing such as hulk for some reason to make it work

**Review by MrMelbert — CHANGES_REQUESTED** [review]
Can you put
```
if(HAS_TRAIT(owner, TRAIT_SLEEPIMMUNE))
    tick_interval = -1
else
    ADD_TRAIT(owner, TRAIT_KNOCKEDOUT, TRAIT_STATUS_EFFECT(id))
```
and test that it still works? 

We still need to respect sleep immunity in some way (see: `on_owner_insomniac`)

**Comment by FlufflesTheDog** [comment]
I need to do more testing, but it seems like that largely works fine?
Though I'm confused. My assumption that the cause of healium's permasleep was caused by the the status effect not being put in the processing queue, due to having both duration and tick interval set to -1, so the eventual change in duration never kicked in. The new change continues to not start processing on the sleeping status effect if you are immune to sleeping, however it does eventually remove it. But I don't understand what's removing it or how that change results in that.

Also, healium seems to set unconsciousness in addition to sleeping, the former of which doesn't respect the sleep immunity trait. I can't find any indication this is intentional, so wondering if I should make sleep immunity catch that as well.

**Comment by MrMelbert** [comment]
> Also, healium seems to set unconsciousness in addition to sleeping, the former of which doesn't respect the sleep immunity trait. I can't find any indication this is intentional, so wondering if I should make sleep immunity catch that as well.

Er, how does it set unconscious? That doesn't seem right, from what I can see it's only supposed to set sleeping. Can you check the trait sources?

> The new change continues to not start processing on the sleeping status effect if you are immune to sleeping, however it does eventually remove it. But I don't understand what's removing it or how that change results in that.

That is curious, you assumption as to why it wouldn't be working sounds correct

**Comment by MrMelbert** [comment]
Actually, looking at it now - the only time Healium's sleep effect would not be processing is if applied to someone with sleep immunity 

Non sleep immune:

- `PermaSleeping` is called
- Sleeping effect is created with -1 duration and 20 tick interval
- `on_creation` is called: Tick interval + world.time is greater than world.time so it begins processing

Sleep immune:

- `PermaSleeping` is called
- Sleeping effect is created with -1 duration and -1 tick interval
- `on_creation` is called: Duration + world.time and Tick interval + world.time is less than world.time, so it doesn't process

So, we can solve this by not relying on sleep processing 

Replace this
```dm
/datum/reagent/healium/on_mob_end_metabolize(mob/living/breather)
	breather.SetSleeping(10)
	return ..()
```
with this
```dm
/datum/reagent/healium/on_mob_end_metabolize(mob/living/breather)
	breather.remove_status_effect(/datum/status_effect/incapacitating/sleeping)
	return ..()
```

**Comment by MrMelbert** [comment]
...Or, honestly, just remove `PermaSleeping` and have healium `breather.SetSleeping(INFINIFTY)` /  `breather.SetSleeping(0 SECONDS)`.

**Comment by FlufflesTheDog** [comment]
> Er, how does it set unconscious? That doesn't seem right, from what I can see it's only supposed to set sleeping. Can you check the trait sources?

Healium's snowflake lung code
https://github.com/tgstation/tgstation/blob/de7b05e44a0d9ff1a8daec973981c762f3ea0040/code/modules/surgery/organs/internal/lungs/_lungs.dm#L422
> That is curious, your assumption as to why it wouldn't be working sounds correct

That was a bit of a journey
IsSleeping() only returns the status effect if present AND the user isn't sleeping. And that is used by SetSleeping to determine if a new status is made or if it should adjust the old one. So specifically in the case of permasleep with sleep immunity, the status effect DOESN'T get added to the processing queue until a new status happens to overwrite it, working out by what appears to be luck

This doesn't feel very proper, and I realize now that all the other mob status procs don't respect either a negative duration, or how IsSleeping handles the effect, so will usually end up removing the status effect

Switching to SetSleeping(INFINIFTY) is tempting, however that means that healium's sleep can be canceled with anything with any other SetSleep value. Perhaps if that (or something with a more sane value at that point) was put in reagent/healium/on_mob_life instead?

**Comment by MrMelbert** [comment]
> Switching to SetSleeping(INFINIFTY) is tempting, however that means that healium's sleep can be canceled with anything with any other SetSleep value. 

I'd think that is the point, no? We don't want Healium permasleep to be cancelled any way besides Healium ending itself. 

However, 

> Perhaps if that (or something with a more sane value at that point) was put in reagent/healium/on_mob_life instead?

This is another option, I was going to mention it with my other comments even. 
Just calling `AdjustSleeping(10 SECONDS)` or something every life tick of Healium, and `SetSleeping(0 SECONDS)` when it expires. It's not the most elegant but it works.

**Comment by FlufflesTheDog** [comment]
> > Switching to SetSleeping(INFINIFTY) is tempting, however that means that healium's sleep can be canceled with anything with any other SetSleep value.
> 
> I'd think that is the point, no? We don't want Healium permasleep to be cancelled any way besides Healium ending itself.

I think you misread, SetSleeping(INFINITY) can be instantly(ish) countered using anything that calls SetSleep with any other value.
Voice of god's "wake up" for example, calls SetSleeping(0). Among a couple other things.

**Comment by MrMelbert** [comment]
> I think you misread, SetSleeping(INFINITY) can be instantly(ish) countered using anything that calls SetSleep with any other value. Voice of god's "wake up" for example, calls SetSleeping(0). Among a couple other things.

Ah I see, in that case yeah best bet is probably ticking it up on life.

**Comment by FlufflesTheDog** [comment]
I think the functionality is pretty much there, though I'm wondering if perhaps instead of switching to sleep over unconscious (specifically in the lung code), perhaps sleep immunity should just also grant immunity to unconsciousness?

Also with how sleep immunity is handled, being asleep will still show the "asleep" screen alert.
And with how the status effect is handled, having sleep immunity AND something constantly trying to put you to sleep, the screen alert will regularly flicker. Doesn't seem to have a mechanical effect but worth noting.

**Pull request merged**
