### PR TITLE
Cult structures that emitted light now have colored light

### PR DESCRIPTION
**Pull request by ChangelingRain**
:cl: Joan
rscadd: Cult structures that emitted light now have colored light.
/:cl:

why did this not use tabs who the fuck uses spaces for spacing augh

### CODE REVIEW

**Comment by Repukan** [comment]
What if I want to hide them in the dark though

**Comment by optimumtact** [comment]
I think we should be more sparse with our coloured lights, too many colours looks tacky and ruins the aesthetic of the game

it's a no from me :-1:

**Comment by Xhuis** [comment]
cover them with a cloth or something idfk

**Comment by Repukan** [comment]
>cover constructs and structures with a bedsheet
>Sec breaks in 
>They take off the bedsheet
>Three juggernauts were hiding under it
>CREEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEED

**Comment by MMMiracles** [comment]
if everything in the game doesn't have a unique light color then we aren't fully utilizing the new lighting, obviously.

**Comment by Ninja137** [comment]
Doesn't this act as a stealth-nerf to Cult because they've usually got their whole Zealot's Blindfold thing for nightvision, but this ruins it?

**Comment by ChangelingRain** [comment]
Cult structures already have lighting; this only adds colors to it.

**Comment by coiax** [comment]
> too much lighting ruins the asthetic

GLOWSHROOMSGLOWSHROOMSGLOWSHROOMSGLOWSHROOMSGLOWSHROOMSGLOWSHROOMSGLOWSHROOMSGLOWSHROOMSGLOWSHROOMSGLOWSHROOMSGLOWSHROOMSGLOWSHROOMSGLOWSHROOMSGLOWSHROOMSGLOWSHROOMSGLOWSHROOMSGLOWSHROOMSGLOWSHROOMSGLOWSHROOMSGLOWSHROOMSGLOWSHROOMSGLOWSHROOMSGLOWSHROOMSGLOWSHROOMSGLOWSHROOMSGLOWSHROOMSGLOWSHROOMSGLOWSHROOMSGLOWSHROOMSGLOWSHROOMSGLOWSHROOMSGLOWSHROOMSGLOWSHROOMSGLOWSHROOMSGLOWSHROOMSGLOWSHROOMSGLOWSHROOMSGLOWSHROOMSGLOWSHROOMSGLOWSHROOMSGLOWSHROOMSGLOWSHROOMSGLOWSHROOMSGLOWSHROOMSGLOWSHROOMSGLOWSHROOMSGLOWSHROOMSGLOWSHROOMSGLOWSHROOMSGLOWSHROOMSGLOWSHROOMSGLOWSHROOMSGLOWSHROOMSGLOWSHROOMSGLOWSHROOMSGLOWSHROOMSGLOWSHROOMSGLOWSHROOMSGLOWSHROOMSGLOWSHROOMSGLOWSHROOMSGLOWSHROOMSGLOWSHROOMSGLOWSHROOMSGLOWSHROOMSGLOWSHROOMSGLOWSHROOMSGLOWSHROOMSGLOWSHROOMSGLOWSHROOMSGLOWSHROOMSGLOWSHROOMSGLOWSHROOMSGLOWSHROOMSGLOWSHROOMSGLOWSHROOMSGLOWSHROOMSGLOWSHROOMS

**Comment by Robustin** [comment]
Only if you nerf the pylon turf spread, its kind of unrelated, but its also not... that shit spreading out the from 4 tiles away and leaving evidence of my base is on my todo list.

**Comment by Robustin** [comment]
Im kind of serious, colored lighting is a huge "red" (in this case literally red) flag that is way more obvious than previous lighting showing through walls... having a sinister red glow coming from a room in maint is a dead giveaway and ruin any potential these things have.

1) Shrink the glow
2) Turn off the glow if the pylon is disabled
3) Reduce the range of the turf spread 

Any 2 of these 3 would make me happy. Otherwise I'm just going to have to do it myself and you might not like my version :)

**Comment by coiax** [comment]
@Robustin light being visible from the other side of a wall is something that @MrStonedOne says he's gonna fix

**Review by PJB3005 — CHANGES_REQUESTED** [review]
Tabs for indentation, spaces for alignment.

Why in the name of god would you actively ruin the alignment of this file you monster.

**Comment by PJB3005** [comment]
> This was merged

Quality code standards boys.

**Pull request merged**
