### PR TITLE
Possibly fixes SQL connection issues, adds SQL automatic reconnecting

### PR DESCRIPTION
**Pull request by optimumtact**
Stolen from https://github.com/tgstation/TerraGov-Marine-Corps/pull/1515

### CODE REVIEW

**Comment by Rohesie** [comment]
Outrageous. Expect a DMCA.

**Review by Jordie0608 — CHANGES_REQUESTED** [review]
@DominikPanic This works, but a better solution would be to attempt reconnect only when a query fails to connect instead of every 10 minutes.

You can do something like: when `Execute()` fails run use BSQL's `GetErrorCode` to check for 2006, the mysql has gone away code, and if found attempt reconnect then rerun `Execute()` Essentially a try/catch wrapper for queries.

Not sure that exactly will work but it should be possible.

**Comment by Rohesie** [comment]
Might be interested in the reviews, @DominikPanic

**Comment by Cyberboss** [comment]
Writing anything new in C++ in 2018 is a mistake tbh. What I'd do to be able to move BSQL into rust_g

**Comment by DominikPanic** [comment]
tgstation/TerraGov-Marine-Corps#1606

**Comment by Jordie0608** [comment]
Superseded by #44144

**Pull request closed without merging**
