### PR TITLE
Additional CTF maps

### PR DESCRIPTION
**Pull request by NamelessFairy**
## About The Pull Request
This pull request adds a map loader as well as new maps to CTF. When a game starts a CTF map will be selected at random and will be playable by ghosts.

As well as this new functionality CTF now fully supports 4 teams. A green and yellow team have been added complete with both standard and instagib gear.

At current five maps are planned:
Classic - the original map we all know and love
Four Side - A four team CTF map where all teams compete over one flag
Downtown - Terrestrial city themed map
Limbo - Wizard themed map featuring portals and uses KOTH rather than CTF
Cruiser - Space themed map utilizing the powerup system

- [x] Random maps are selected on game load
- [x] Support for four teams added
- [x] Map 2 creation
- [x] Map 2 playtesting
- [x]  Map 2 final polish
- [x] Map 3 creation
- [x] Map 3 playtesting
- [x] Map 3 final polish
- [x] Map 4 creation
- [x] Map 4 playtesting
- [x] Map 4 final polish
- [x] Map 5 creation
- [x] Map 5 playtesting
- [x] Map 5 final polish
- [x] Final checks

## Why It's Good For The Game
CTF has been more or less the same on the surface since its creation. This PR allows for some much needed map variety which will increase replay value. CTF is far more regularly played then mafia due to its fast rounds and common use during round end delays and I believe that it deserves a boost in content.

## Changelog
:cl:
add: CTF can now selects a random map at game start
add: CTF now supports four teams
add: Gear for yellow and green CTF teams has been added
add: CTF ID cards for all 4 teams have been added - courtesy of maxymax13
add: a new CTF map, Four Side has been added
add: a new CTF map, Downtown has been added
add: a new KOTH map, Limbo has been added
add: a new CTF map, Cruiser has been added
fix: KOTH capture points retain their sprites after being claimed
/:cl:

### CODE REVIEW

**Comment by CRITAWAKETS** [comment]
By the way, i recommend adding in population-based map selection for CTF and adding in smaller maps for lower population matches. Also, when making the maps, i would recommend making styles different from those of central command in order to have  the different maps stand out.

**Comment by itseasytosee** [comment]
If blue is centcomm, and red is syndie. Then what are green and yellow?

**Comment by D4C-420** [comment]
green- old gods(heretics)
Yellow - honk mother

**Comment by NamelessFairy** [comment]
> If blue is Nanotrasen, and red is syndie. Then what are green and yellow?

This is more of a lore question but currently based on the assets I'm using, green is "military" death squad and yellow is prisoners.

**Comment by NamelessFairy** [comment]
> By the way, i recommend adding in population-based map selection for CTF and adding in smaller maps for lower population matches. Also, when making the maps, i would recommend making styles different from those of central command in order to have the different maps stand out.

Population based selection is a little out of the scope of this PR ~~and my ability~~ since the CTF map is loaded right away, likely before people have a chance to join. I would truly love to implement mapvotes at the end of each round but thats something I'm unsure of where to start with.

As for different styles thats fully my intention. At current I want to do a wizard themed map and a map which uses the bus sprites. Both of which should have a unique style to them

**Comment by NamelessFairy** [comment]
Update on the current state of the project.

High Street is coming along nicely and has received very good feedback on both Sybil and Terry during test runs, I'll be adding the finishing touches onto it soon.

Four Side on the other hand has started gaining more criticism, the conveyor belts which I believed was an un-impactful gimmick is being treated similarly by players and there for I don't see any reason to keep them around. I would have like to replace them with another feature. Four Side is also suffering for a size issue. I'm currently testing both a large and small version of the map and both are quite mixed.

**Comment by NamelessFairy** [comment]
A comment on tags briefly.
Since PRing one bug has been fixed involving the capture points for CTF not having sprites after being captured.
And I don't think this qualifies as a UI PR as the only UI changes made involve adding some new colored text in the chat for green and yellow team radios

**Comment by NamelessFairy** [comment]
What next?

I'm not finished with the CTF system and would like to have the map change after each round of CTF, I've looked into this and I think the best way of doing this is to refractor CTF into a controller similar to Mafia. This is, at present, something outside of my coding ability but I shall continue researching into the feasibility of doing this.

Maps?
Of the 4 additional maps, I'm happy with where they're all at but I want to improve them and continue to maintain them after getting wider feedback assuming these maps are merged. Downtown in particular has been a fan favorite from what I've witnessed in my playtests.

More Maps?
I want to encourage the mapping community to try at take a swing at making their own maps to expand the roster, and later to rotate maps in and out of the pool to keep them from getting stale. As for my own maps I still have ideas for other map concepts but assuming future maps will be added individually I want to make something particularly special before I choose to PR a new map all together

**Comment by Twaticus** [comment]
seem to be missing the right inhands for instagibgreen & instagibyellow
is there a reason the dominator colors were capitalized? if im not mistaken we generally try to have it all lowercase

**Comment by NamelessFairy** [comment]
> seem to be missing the right inhands for instagibgreen & instagibyellow

Nice catch there, this completely slipped my mind, I'll make right inhands for them right away.

> is there a reason the dominator colors were capitalized? if im not mistaken we generally try to have it all lowercase

When the CTF control points are claimed their icon states are changed to "dominator-[CTF.team]". "CTF.team" is the name of the team and is capitalized, these team names are also displayed to players. I decided that it was more important to preserve the player facing grammatical correctness of the team names rather than preserving the names of icon states, if this is an issue though I can change them.

**Review by Twaticus — APPROVED** [review]
sounds gud to me

**Comment by maxymax13** [comment]
how about i make you some CTF id card sprites instead of using random other id card items

**Comment by NamelessFairy** [comment]
> how about i make you some CTF id card sprites instead of using random other id card items

That would certainly be nice. I'll take a look into the ID card code for adding new ID cards

However this also might just be considered sprite bloat since they'll presumably only be used in CTF and have no proper functionality. So I'd be happy to include them but I'm not certain if they'd be allowed

**Comment by maxymax13** [comment]
cardz
here you go, i tried to keep them with a similar palette and design as the banners
i took some inspiration (read: ripped off) the departmental budget card designs since i didn't want them to just look like a regular NT station ID with a changed icon on them
as for defining the items, you could probably just make them retro card subtypes
whether you feel like adding a couple sprites and items to replace some very offputting item reuse is sprite bloat, is up to you

**Review by EOBGames — APPROVED** [review]
Maps look fine to me, just needs code review now.

**Pull request merged**
