### PR TITLE
Revise tgui folder structure; fix up syndicate theme

### PR DESCRIPTION
**Pull request by neersighted**
Syndicate Theme

Fix up the folder structure and merge scripts and styles as well; generally improve variables and remove cruft.

### CODE REVIEW

**Comment by ChangelingRain** [comment]
:+1:, Syndicate theme is good.
is there an easy way to change the green color for it, too?

**Comment by neersighted** [comment]
Yep, its trivial.

**Comment by WJohn** [comment]
Very pretty looking :+1:

**Comment by ChangelingRain** [comment]
In that case, I suggest using `#80FF80` which should look pretty good(and satisfy my urge to theme shit properly)

**Pull request merged**
