### PR TITLE
Fixes ERTs not spawning with correct stuff

### PR DESCRIPTION
**Pull request by Bawhoppen**
medics in specific

### CODE REVIEW

**Comment by Niknakflak** [comment]
Not really a fix but I have no objections

**Comment by KorPhaeron** [comment]
They already have these in the armory on high alert though

**Comment by KorPhaeron** [comment]
feature freeze

**Comment by coiax** [comment]
Not even a Feature Freeze tag?

**Comment by Bawhoppen** [comment]
no kor this was a fix, they don't get them on high alert, while they do on low alert (not in the lockers even)

**Comment by optimumtact** [comment]
feature or fix?

**Comment by Bawhoppen** [comment]
I already said a fix so remove frozen tag

**Comment by Bawhoppen** [comment]
that works too

**Pull request merged**
