### PR TITLE
Plant Refactor: Revenge of the Grown

### PR DESCRIPTION
**Pull request by Core0verload**
This PR splits the 2k lines monster file known as `grown.dm` into a set of smaller subfiles. It also changes how defining reagents in plants works, and how plant scanner scans the plants. All changes are aimed at reducing amount of repeated code in `grown.dm` and making plant code more condensed. If everything is done right, players shouldn't notice any changes.

This PR is a part of update line that will greatly reduce amount of clutter in plants code and, at the last stage, will add **bio-engineering** - system similar to Bay's xenobotany, except aimed at non-autistic playerbase.

### CODE REVIEW

**Comment by PKPenguin321** [comment]
RIP goofbotany

**Comment by Core0verload** [comment]
It woudn't be missed.

**Comment by duncathan** [comment]
Gonna be honest

Goofbotany > "bio-engineering" (assuming it's like xenobotany like he said)

**Comment by Iamgoofball** [comment]
hi

goofbotany delibrately doesn't touch plants

these can coexist

**Comment by xxalpha** [comment]
It's not botany if it doesn't touch plants, then.

**Comment by Shapsy** [comment]
goofzoo

**Comment by KazeEspada** [comment]
Goofranch

**Comment by Supermichael777** [comment]
Goofdew Valley

**Comment by phil235** [comment]
Looks promising.

**Comment by Chocobro** [comment]
@Core0verload :+1: hydroponics always needs compression

**Pull request merged**
