### PR TITLE
Wraith Spectacles will now slowly repair the eye damage they do

### PR DESCRIPTION
**Pull request by ChangelingRain**
:cl: Joan
rscadd: Wraith Spectacles will now slowly repair the eye damage they did to you as long as you aren't wearing them.
experiment: You can now see how much eye damage the spectacles have done to you overall, as well as how close you are to being nearsighted/blinded.
/:cl:

### CODE REVIEW

**Comment by KingPhilipIII** [comment]
I never use Wraith Spectacles because I'm always terrified of being blinded. Hooray.

**Comment by ShadowDeath6** [comment]
This is good :+1:

**Comment by KingPhilipIII** [comment]
Wait. So do you toggle the glasses on or off and it heals while off, or does the damage just heal over time when the spectacles are taken off?

**Comment by KingPhilipIII** [comment]
Saying that the spectacles do the healing is confusing.

**Comment by ChangelingRain** [comment]
They just heal the damage they did to you, as long as you happen to not be actively wearing them.
Confusing, but literal. If they're destroyed you won't have your eye damage healed.

**Comment by optimumtact** [comment]
this is ugly code

**Comment by optimumtact** [comment]
the wraith spectacles should add an effect to the user on equip, that every tick checks if they're wearing the specs and deals damage, or heals them, when fully healed eye damage it removes the effect, only being added back if the spectacles are put back on, then you don't need to store a list of wraith users on the glasses

14:26 <%oranges> it's less coupled and uses standard preexisting frameworks
14:27 <%oranges> it will be more maintainable in the long term
14:27 <%oranges> plus it promotes use of good design patterns in the code

**Pull request merged**
