### PR TITLE
Revert "Removes explosion delays"

### LINKED ISSUE #26957: Not always getting killed by bombs
I was defusing a bomb and I hit the wrong wire, second try. I was right next to the bomb when it exploded and I waited a second and said RIP, thinking I was in deadchat. Imagine my surprise when I am alive and now taking low pressure and oxygen damage. I think I was either on the tile the bomb exploded on or right next to it. Anyways I got back to medical, put on some brute patches, and then cucked an esword traitor with a pie. Fun stuff. The only damage I took was from the pressure/lowtemps btw.

### LINKED ISSUE #27209: I detonated a maxcap in my hands and survived unharmed
Nice

### PR DESCRIPTION
**Pull request by Cyberboss**
This reverts #27120 
Fixes #27209 
Fixes #26957

Fucking these sleeps, need to NOT EXIST REEE

### CODE REVIEW

**Comment by lzimann** [comment]
well, something did go wrong after all

**Comment by MrStonedOne** [comment]
why is this revert needed? what is sleeping?

I'd like to keep this change in if we can.

**Comment by Cyberboss** [comment]
Same here but apparently this is allowing people to dodge bombs somehow, even though that makes no sense

**Comment by Cyberboss** [comment]
No clue what is sleeping specifically

**Comment by Lumipharon** [comment]
I could dodge bombs even before this pr though?
Explosions have been different since I started playing again.

Usually~ the explosion isn't instant, it slowly sort of expands, so even when the bomb goes of pretty much right next to you, often you can just run away from it.

**Comment by Robustin** [comment]
Yea that was just shitty bomb processing before, you could also dodge by "running into" the blast and getting lucky.

This is just straight up "Im holding the bomb, opening the valve, and I survive unscathed while the bomb destroys everything around me".

**Comment by Lumipharon** [comment]
wat.

**Comment by MrStonedOne** [comment]
What i'm not seeing is any explanations as to why adding this `set waitfor = 0` is leading to the causes its leading to.

To answer that, finding the sleeps would be needed, and this is actually easy enough to do that you should really focus your efforts there cyberboss

**Comment by duncathan** [comment]
is this ready @Cyberboss

**Comment by Cyberboss** [comment]
I swear I closed this

**Comment by duncathan** [comment]
ok

**Pull request closed without merging**
