### PR TITLE
Adds a new round end sound.

### PR DESCRIPTION
**Pull request by Iamgoofball**
A very exasperated assistant complaining about the end of the shift.

## Changelog
:cl:
add: The remake better sure as hell make up for this, I'm tellin' ya right now, because I'm stuck in nowhere space. You ran out of pixels too, didn't you ya bastards.
/:cl:

### CODE REVIEW

**Review by ShizCalev — DISMISSED** [review]

**Comment by TheVekter** [comment]
Bless Spike Spencer's heart, he's hilarious.

Do we need permission from him on this or do you reckon we're good?

**Comment by kriskog** [comment]
As its a snippet from an anime (?), its probably subject to licensing. 

also a 1 minute round end sound is over the top

**Review by Cyberboss — CHANGES_REQUESTED** [review]
Round end sounds cut out when DD finishes rebooting, this is way too long

**Comment by Iamgoofball** [comment]
the sound has been replaced and the trigger time has been changed

**Comment by TheVekter** [comment]
> As its a snippet from an anime (?), its probably subject to licensing.
> 
> also a 1 minute round end sound is over the top

This might be a moot point now but it wasn't from the show, it was from a gag reel Spike Spencer did after Eva finished. So while it probably sits under fair use somewhere he technically owns it.

**Comment by PKPenguin321** [comment]
wait are we STILL hosting endround sounds in the code and not the server-side config? wtf

**Comment by PKPenguin321** [comment]
also this sux as a roundend sound, too long and annoying

**Comment by nemvar** [comment]
Tintin on the moon and fly me to the moon don't mix.

**Pull request closed without merging**
