### PR TITLE
Moves Flightpotion wings from species datum to chest bodypart, other flightpotion tweaks

### PR DESCRIPTION
**Pull request by GPeckman**
## About The Pull Request

Flightpotion wings have for a long time been on the species datum, rather than being tied to a specific bodypart. This means that, for example, a lizard who had all of their bodyparts turned human due to a freak bioscrambler accident would still get lizard flightpotion wings, not the human ones. Now its based solely on what chest bodypart you have. A human chest means angel wings, a lizard chest means dragon wings, a skeletal chest means skeletal wings, etcetera.

All flightpotion wings can now be ground up to get the flightpotion back. If a lizard (or rather, someone with a lizard chest) mugs a human and surgically steals their angel wings, then the lizard can now actually get cool dragon wings instead of being stuck with lame angel wings.

## Why It's Good For The Game

Moving species-level behavior to bodypart/organ level has been a general design goal for some time now, and it just makes sense to tie the flightpotion to the chest.

Being able to grind wings up to get the flight potion back is nice for allowing people to get different wing variants and can lead to interesting IC interactions in much the same way that lizard wine can.

## Changelog
:cl:
refactor: The wings you get from a flight potion (if any) are now determined by your chest bodypart, not your species.
qol: Functional wings can now be ground up to get the flight potion back, if you want to get a different wing variant.
/:cl:

### CODE REVIEW

**Comment by moocowswag** [comment]
the wings making you nonhuman i think is for consistency that major structural mutations are considered their own species, kind of like hulk or the telepathic brain coconut head thingies

buuuuut the dna splicer machine thingy doesnt nonhuman you so why should wings, apparently we are moving away from that.

**Comment by GPeckman** [comment]
> the wings making you nonhuman i think is for consistency that major structural mutations are considered their own species, kind of like hulk or the telepathic brain coconut head thingies
> 
> buuuuut the dna splicer machine thingy doesnt nonhuman you so why should wings, apparently we are moving away from that.

Hulk is actually the only mutation that makes you nonhuman, and that's mainly to balance out hulk making you immune to stuns. The only other way for the health analyzer to list you as nonhuman (aside from actually changing your species, of course) is for something to alter the organs in your species datum. This is not the same as changing the organs present in your body, to be clear, and I don't know of anything that actually does change your species datum like that.

**Comment by moocowswag** [comment]
> > the wings making you nonhuman i think is for consistency that major structural mutations are considered their own species, kind of like hulk or the telepathic brain coconut head thingies
> > buuuuut the dna splicer machine thingy doesnt nonhuman you so why should wings, apparently we are moving away from that.
> 
> Hulk is actually the only mutation that makes you nonhuman

Hulk is the only genetics mutation yes but fly people, telepathic walnut head people, felinids, and even wizards are considered to be mutants (with wizards not actually being recognized as mutants for asimov or health analyzer purposes) just not ones used by the mutation system.

**Comment by zxaber** [comment]
>balance: Having functional wings no longer makes the health analyzer list you as non-human.

Damn shame. Losing Asimov protection in exchange for buffs is a neat trade, and at the very least opens the door for law manipulation shenanigans.

**Comment by GPeckman** [comment]
> Damn shame. Losing Asimov protection in exchange for buffs is a neat trade, and at the very least opens the door for law manipulation shenanigans.

That's a fair point, but I think it only makes sense to do that consistently. As it stands, surgically attaching regular moth wings won't make you nonhuman, but drinking a flight potion (Or removing them from someone else and attaching them to yourself surgically) _will_ make you nonhuman, and that just doesn't make sense. And there is no other organ or bodypart than makes you nonhuman under any circumstances, full stop.

**Comment by zxaber** [comment]
>As it stands, surgically attaching regular moth wings won't make you nonhuman, but drinking a flight potion (Or removing them from someone else and attaching them to yourself surgically) will make you nonhuman,

The potion making you non-human would be more akin to genetics than simple surgery. So having the wings shouldn't make you non-human, but drinking the potion should (even if the wings are later removed).

For surgery, we really ought to just work off the chest part. Whatever the "core" part is, that's your species.

**Comment by GPeckman** [comment]
> The potion making you non-human would be more akin to genetics than simple surgery. So having the wings shouldn't make you non-human, but drinking the potion should (even if the wings are later removed).
> 
> For surgery, we really ought to just work off the chest part. Whatever the "core" part is, that's your species.

Drinking the flight potion _used_ to change your species, but it doesn't anymore. Making it change your species again, while also keeping the wing variants for lizards, moths, and so on is a lot of work that I am not particularly interested in doing. Ditto for totally overhauling species to work based off of your chest.

**Comment by Fikou** [comment]
why would i get android wings from a potion

**Comment by GPeckman** [comment]
Because android limbs (chest included) are nigh-identical to augmented limbs. In fact, they were _actually_ identical until #74580 added android subtype. The only thing was the subtype changed was (and still is) that they get replaced on species change, while normal robolimbs don't.

If it really matters that much, I could move the android wings down the the android subtype.

**Comment by Time-Green** [comment]
> Because android limbs (chest included) are nigh-identical to augmented limbs. In fact, they were _actually_ identical until #74580 added android subtype. The only thing was the subtype changed was (and still is) that they get replaced on species change, while normal robolimbs don't.
> 
> If it really matters that much, I could move the android wings down the the android subtype.

Nah that’s cool. I don’t like the balance change though, I’d rather you split it of

**Comment by GPeckman** [comment]
Alright, I got rid of the balance change. I'll probably remake it as a separate PR sometime tomorrow.

**Comment by Time-Green** [comment]
Will the grinding let people make infinite wing potion using cryo?

**Comment by GPeckman** [comment]
As I understand it, cryotubes only transfer a maximum of 0.5u per tick to the occupant no matter how good the parts are. But just to be safe, I made it so that the flightpotion reagent only works if ingested or applied via touch (necessary for androids, they can't eat or drink anything).

**Comment by Time-Green** [comment]
Yeah that’s probably fine?… I don’t really care for the grinding but I doubt it’ll come up much

**Comment by moocowswag** [comment]
Cant oddy still replicate flight potion chem? If so grind isnt a big deal

**Comment by Time-Green** [comment]
> Cant oddy still replicate flight potion chem? If so grind isnt a big deal

Yeah it could, at least it’s a bit harder to do. Flight potion being an actual reagent is kind of weird considering how abusable reagents are

**Comment by GPeckman** [comment]
The reagent actually doesn't have the REAGENT_CAN_BE_SYNTHESIZED flag, which means that the Ody can't replicate it and you can't even grind up dead monkeys to get it out of them.

**Comment by moocowswag** [comment]
Must have been changed cause i remember people using oddy with syringe to mass flight potion the crew

**Pull request merged**
