### PR TITLE
Tweaks and opens up Science on Icebox, adds new SciChem area

### PR DESCRIPTION
**Pull request by tf-4**
## About The Pull Request

(yeah i'm aware it's very conflicting, I'll sort it)

Makes some small QoL changes to science, opens it up into a more publically accessible department, and adds a SciChem area.

entrance
Most noticeably, makes the science corridor publically accessible, letting people walk in and around deeper in science, to additional desks.

rnd

scichem
South of RnD is the new SciChem. Basically a slightly more reinforced chemistry, to be focused more on "chemical research" (read: making great big fuck off grenades), as well as providing robotics with any chems they might need. Grenade crafting items have been moved here from chemistry roundstart.

robotics
Expands surgery in robotics, moves the fabs to a less space-consuming area. I did remove one of the mech chargers, because I wanted more space in surgery and honestly both are rarely used at the same time.

xenobio_north
North of xenobiology. Added a desk and fridge for slime cores. Moved the xenobio consoles to be in line with each other so you actually have some vague level of interaction with your coworker.

xenobio_south
South of xenobiology. Expanded the area for cytology, including a small pen so your blobbernauts don't go on a rampage (or at least a delayed one)

xenobio_lower
The lower floor of xenobio now has scrubbers in the pens in an attempt to stop the miasma floating up and making you sick.

test_lab
Testing lab, all the way at the bottom. Moved nanites down here, giving them a monkey pen for testing whatever wacky shit they want _rather than doing it on the public cloud_.

## Why It's Good For The Game

One of the biggest problems in science is isolationism. They sit in their lab, ignore the RnD desk, and generally just do their own thing. Opening up science will do two things - it will encourage interaction as people don't have to go sit at the front desk that nobody checks for 20 minutes, ignoring the radio. It'll also hold scientists a little more accountable, as it's gonna be harder to sit in your lab accruing power if everyone can see what you're doing.

SciChem will give chemist antags a little more leeway, as destructive chems won't lead to sec knowing the culprit is in main chem instantly. Also lets them focus on plumbing and healing a little more as making grenades will *ideally* be the sole responsibility of SciChem - science has access to the testing lab after all, whereas chemists don't particularly have anywhere to test whatever they make.

## Changelog
:cl:
tweak: Various QoL changes within all areas of science.
tweak: Science is for the people - you can now enter science, with more desks for you to stand at waiting for scientists.
add: SciChem is here for production of totally scientific grenades and other dangerous substances, moving the pressure away from chemistry-proper.
/:cl:

### CODE REVIEW

**Comment by optimumtact** [comment]
R&D powercreep

**Comment by nianjiilical** [comment]
i like a lot of this but im not a huge fan of moving the roundstart grenade supplies out of medical and into the department that already has so much shit

sure it isnt hard to make more grenade cases or anything but at least leave the ones in chemistry there

**Comment by zxaber** [comment]
Opinions on Robotics:

The existing "Two row" layout of the ExoFabs is probably one of the better layouts for robotics. It keeps things mostly orderly, and when working solo you can decon one of the tables and make it a "borg shell station" or something. The "Pubby layout" here isn't terrible but I feel it's a step down from what we currently have; working with a partner is going to mean constantly trying to walk past each other because both projects will default to being on adjacent tiles. You could solve this somewhat by moving the left ExoFab one tile westward (and extending the floor decals to match), so that there's a single row of empty space between the two work areas.

Two operations tables in robotics is unnecessary. It is quite rare that you'd have multiple pending surgeries outside roundstart debraining, and I'm not convinced that both robos will jump into that when a single robo can debrain at a decent pace and the other could be making the shells. But I guess the second table *is* free silver and I should probably just shut up about it.

Meanwhile, two mech chargers are nice to have mostly because it's not uncommon to park a mech on the charger while you're not using it, and I'd hate to do that and block the solo charger off from someone who needs it. I'm fairly sure we have more rounds with multiple mechs than we do with multiple simultaneous robotics surgeries.

Three borg chargers is cool, though.

**Comment by RaveRadbury** [comment]
Chem in sci roundstart? Massive powercreep. Terrible idea.

**Comment by AlinaStarkova** [comment]
i like the door blocking access to RnD though, paramedics have sci halls access and so RnD needs to be removed from being open to sci hall else paramedics has two jobs its capable of

**Comment by D4C-420** [comment]
lets face it adding in chem to sci will just result in them basically never having go to medbay

**Comment by JohnFulpWillard** [comment]
> 
> 
> lets face it adding in chem to sci will just result in them basically never having go to medbay becuase its not just going to be used to make grenades. They are going to make pills and use them to heal. bad idea

Yeah Im really not a big fan of chemistry being in science. It will just be used to do chemistry rather than "Science" and will just remove basically any need for any Science personnel to go to medbay.

**Comment by tf-4** [comment]
Gonna add a new chem fridge type for non-medicine reagents only. Should alleviate that issue.

**Comment by LemonInTheDark** [comment]
Do not just give the chemistry job to sci, if they really want to do chemistry they can build the machines themselves.

Additionally, if you are going to open up the sci hallway put airlocks at the entrance. It helps with containing toxins, and lessens the potential load on the atmospherics system

**Comment by Jared-Fogle** [comment]
What purpose does science need chemistry for anyway? I think they used to need sulphuric acid, but nowadays its...what? Mannitol for robotics (which can be supplemented with brain surgery anyway) and Mutadone for genetics, which they already have a crap ton of pills for?

**Comment by Jared-Fogle** [comment]
Minor nitpick, but I also kinda don't like the robotics surgery room looking like a mini-medbay, I haven't thought about it until now but I quite like the aesthetic of a rundown mad scientist's surgery room.

**Comment by RaveRadbury** [comment]
>Most noticeably, makes the science corridor publically accessible, letting people walk in and around deeper in science, to additional desks.

Why? Science is the kind of department that gets double airlocked. It's not medbay.

**Comment by usnpeepoo** [comment]
> R&D powercreep

this

**Comment by vkalls** [comment]
I liked a lot of it until I got to RnD chemistry...

**Comment by notfrying1pans** [comment]
there are space tiles northeast of the station

**Comment by notfrying1pans** [comment]
wait did you not save it in tgm

**Comment by notfrying1pans** [comment]
SciChem shutters aren't connected to anything it seems

**Comment by notfrying1pans** [comment]
[Nevermind I found it, it's buried under the sign](https://cdn.discordapp.com/attachments/473989208411734030/801094740522565632/unknown.png)

**Comment by notfrying1pans** [comment]
Just a little nitpick but the smartfridge is on a floor tile while in medbay's chemistry it's on a wall

**Comment by tf-4** [comment]
Closing this for now due to my total inability to use git efficiently. Will reopen when it's in better shape and feedback has been addressed.

**Comment by EOBGames** [comment]
I know this has been closed, but I have no interest in adding a chemistry area to R&D without some serious code adjustments to accompany it. If you reopen it with those changes, I won't be merging it.

**Pull request closed without merging**
