### PR TITLE
[WIP]  New brain trauma: Pirate Slang; Space Pirates have this

### PR DESCRIPTION
**Pull request by coiax**
:cl: coiax
add: Space pirates now speak in a piratey way. Some
sufferers of brain trauma will also speak in a more
nautical fashion.
/:cl:

### CODE REVIEW

**Comment by Spaceinaba** [comment]
Yes should be changed to Aye
No should be Nay
Hello should be Ahoy
etc etc etc
there's so much more stuff you can do other than just replacing insults

**Comment by Armhulen** [comment]
^^

**Comment by JStheguy** [comment]
Yeah this is weak.

**Comment by optimumtact** [comment]
ahoy sailor

**Comment by TheRealGLH** [comment]
You should also consider adding filters for job titles, eg. Captain/ Cap > Cap'n and HoP > First Mate.
Or just look at TF2's medieval mode text parser and just apply that to SS13, but with pirates:
https://wiki.teamfortress.com/wiki/Medieval_mode#Chat_parser

**Comment by Spaceinaba** [comment]
assistants should be scalawag and if they aren't I will come to your house and maroon your mom

**Comment by Potato-Masher** [comment]
Just insults? I want my pirates to be saying "Yar" and "Ahoy" instead of "Yes" and "Hello". Looking at TF2's medieval parser is a good idea

**Comment by LordFowl** [comment]
`			message = replacetext(message," gun "," blunderbuss ")
			message = replacetext(message," heaven "," davy jone's locker ")
			message = replacetext(message," die "," off t' davy jone's locker ")
			message = replacetext(message," dead "," on 'is way to davy jone's locker ")
			message = replacetext(message," I "," aye ")
			message = replacetext(message," my "," meh ")
			message = replacetext(message," yes "," yargh ")
			message = replacetext(message," are "," rgh ")
			message = replacetext(message," yeah "," yarrrh ")
			message = replacetext(message," captain "," cap'n ")
			message = replacetext(message," hos "," first mate ")
			message = replacetext(message," head of security "," first mate ")
			message = replacetext(message," commander "," first mate ")
			message = replacetext(message," hop "," crewmaster ")
			message = replacetext(message," head of personnel "," crew master ")
			message = replacetext(message," ai "," navigator ")
			message = replacetext(message," money "," treasure ")
			message = replacetext(message," cash "," booty ")
			message = replacetext(message," friend "," matey ")
			message = replacetext(message," station "," vessel ")
			message = replacetext(message," shuttle "," rowboat ")
			message = replacetext(message," engine "," sails ")
			message = replacetext(message," space "," sea ")
			message = replacetext(message," dock "," port a' call ")
			message = replacetext(message," nanotrasen "," Blackbeard's mighty fleet ")
			message = replacetext(message," nt "," Blackbeard's mighty fleet ")
			message = replacetext(message," centcomm "," Blackbeard's cove ")
			message = replacetext(message," central command "," Blackbeard's cove ")
			message = replacetext(message," odin "," cove a' Blackbeard ")
			message = replacetext(message," security "," blackguards an' buggers ")
			message = replacetext(message," medical "," sawbones ")
			message = replacetext(message," r&d "," 'em thinky types ")
			message = replacetext(message," rnd "," 'em thinky types ")
			message = replacetext(message," sick "," 'thick with scurvy ")
			message = replacetext(message," the "," th' ")
			message = replacetext(message," you "," ye ")
			message = replacetext(message," and "," an' ")
			message = replacetext(message," am "," be ")
			message = replacetext(message," is "," be ")
			message = replacetext(message,"ing ","in' ")`
Did something like this for Aurorastation before it was decided that it was too memey a brain trauma.

**Comment by arsserpentarium** [comment]
Huh fuck. I had this problem. You've rebased master on wrong branch. Try to rebase it on remote/master.

**Comment by optimumtact** [comment]
actually it's because cyberboss force pushed a two week old commit over master and then fixed it up afterwards.

The extra commits/fake diffs will vanish once you do an updated commit and github triggers the update.

**Comment by ShizCalev** [comment]
@coiax conflict.

**Comment by coiax** [comment]
Yeah, I'll get back to this in a bit.

**Comment by ShizCalev** [comment]
Conflict.

**Comment by ninjanomnom** [comment]
@coiax ping for re-open if you ever start working on this again

**Pull request closed without merging**
