### PR TITLE
New wizard shuttle (temporary PR)

### PR DESCRIPTION
**Pull request by ghost**
This is just a temporary PR and I do not expect it to be merged. I would like feedback on the shuttle itself, though. The mirror in the bedroom is a magic mirror, and the scroll in the cockpit is a lesser scroll of teleportation, for allowing the wizard to get to the station without using a charge on his own scroll.

### CODE REVIEW

**Comment by Anonus** [comment]
Shuttle wings not vertically symmetrical :-1:

**Comment by Xhuis** [comment]
be serious pls

**Comment by Anonus** [comment]
Implying I'm not

**Comment by Xhuis** [comment]
b i a s e d

**Comment by as334** [comment]
I prefer the aesthetics's and sorta neat fluff with the current shuttle. This one just seems boring.

**Comment by Xhuis** [comment]
but it's ___green___

**Comment by Incoming5643** [comment]
Needs more ARCANE MIGHT and GIMMICKLY FLUFF STUFF

**Comment by Xhuis** [comment]
LIKE WHAT AAAAAAAAAAAAAAAAAAAAAA

**Comment by SconesC** [comment]
Put that comms machine by the vendors somewhere... Else

**Comment by PKPenguin321** [comment]
xhius i love you and in general all the changes you do have really made me love you even more
so please understand that i say this with utmost compassion and respect despite how critical it may sound
this shuttle will never, no matter how many changes it has, live up to the glory of our current, awesome, green, atmospheric, wonderfully designed wizard shuttle, and i would be sad if this one replaced the one we currently have

only notable thing is that lesser teleportation scroll on the desk, you should consider just adding that to the current shuttle but not change the current shuttle otherwise
sorry :frowning:

**Comment by vista-** [comment]
Suggestion for pizzabox desc: "You've already had ei nath of this."

**Comment by pudl** [comment]
i infinitely prefer a minimalist design like this to the shit we have now. i love this, i just would prefer if the wings weren't weird like anonus said

**Comment by ike709** [comment]
It isn't symmetrical :-1:

**Comment by Anonus** [comment]
And he thought I was kidding about the wings!

**Comment by xxalpha** [comment]
I think the current one is more fun.

**Comment by Xhuis** [comment]
Thanks for the feedback everyone. I'm gonna close this since it was temporary.

**Pull request closed without merging**
