### PR TITLE
[READY]Scrooge McDuck'ing it! Money bag resprites.

### PR DESCRIPTION
**Pull request by Krysonism**
## About The Pull Request

I have resprited the money bag, a couple versions are available, i might include both or i will choose the one you like the most. I have also included the blank bag sprite for future use.

## Why It's Good For The Game

If this gambling project I am working on is implemented and works as intended money bags will be needed to collect cash winnings, this is not only a QoL improvement but also a greytide mitigating mechanic. 

No one is going to play if George Melons shoves them and takes all their winnings every time
 
Of course if these bags are going to be used they deserve a better sprite.

MoneyBagComparasion
## Changelog
:cl:
imageadd: added new money bag sprites.
imagedel: deleted the old money bag sprite.
/:cl:

### CODE REVIEW

**Comment by Dawson1917** [comment]
+1 for hybrid, looks nice. The $ in New seems too thick and obvious for the bag, in my opinion

**Comment by knacker48** [comment]
I'd go with the hybrid

**Comment by Fikou** [comment]
hybrid

**Comment by necromanceranne** [comment]
Hybrid looks best

**Comment by ExcessiveUseOfCobblestone** [comment]
the new would look best if it was tilted, it's the only one straight up/down while the other 2 are slightly /

**Comment by wesoda25** [comment]
combine new and hybrid

**Comment by Krysonism** [comment]
I will put the hybrid as the main sprite, with new having a 20% chance to spawn or something. 

I might take a crack at distorting the sprite of the new version if i get time.

**Pull request merged**
