### PR TITLE
removes griefProtection() from RND code

### PR DESCRIPTION
**Pull request by silicons**
I've never seen a case in 3 months where admins had to rely on this to recover broken levels, and they can varedit /datum/research's /datum/levels anyways.
also if we care about "what level they had prior to being wiped" well just look at the level of parts on the station and the items, this seems needless.

### CODE REVIEW

**Comment by kilkun** [comment]
why would this even be a thing in the first place

destroying RnD's research is literally an intended function and a little used tactic for revtides and the like to severely cripple loyalist force projection by limiting their access to more advanced equipment. moreover, it's the RD's job to protect his servers, that's marked as a high security area for a reason.

like damn why would that nessecitate admin intervention in the first place? will admins respawn the armory if a greytiding shitter breaks in through space and destroys all the guns?

:+1: pr for removing hugbox garbage

**Comment by BeeSting12** [comment]
If this doesn't get merged, can we have an armory grief protection?

**Review by Cyberboss — CHANGES_REQUESTED** [review]
You should remove the centcom servers too

**Comment by kevinz000** [comment]
@Cyberboss sure give me a bit
@kilkun it's more of the fact that admins back then likely had less methods to fix the grief as admins now with all the tools we have and a debug disk, and this is likely left in by oldcode not being refactored for ages.

**Comment by kevinz000** [comment]
rnd techweb pr covers this

**Pull request closed without merging**
