### PR TITLE
Removes the ERP poster

### PR DESCRIPTION
**Pull request by Dorsisdwarf**
ERP is bad do not talk about ERP ic

## About The Pull Request
Removes sanctioned poster 34

## Why It's Good For The Game

Currently we cant stop people from talking about "erp" ic because someone made it an IC term as a joke and apparently it being in the game justifies that.  

## Changelog
:cl:
del: Removed the very concept of ERP
/:cl:

### CODE REVIEW

**Comment by Exavere** [comment]
Muh ERP Poster.

**Comment by Fikou** [comment]
no erp poster is a great tool for any admin or mapper alike, this pr is dumb

**Comment by SweptWasTaken** [comment]
Muh immersion

**Comment by Timberpoes** [comment]
I'd be kind of sad to see changes like these happen.

These kind of little fluff things and references are a all about the SS13 lore and culture, the station vibes and general atmosphere of playing the game. Ultimately, these kinds of things ARE all about a part of SS13 culture. A very tongue-in-cheek reference to a different time, done in a humourous way.

This is still a quirky and cool spacemans game. We're here to have fun at the end of the day. Little things like this remind you that you're playing a game and to have fun. That the ideas behind the game have a good-hearted sense of humour underpinning them.

**Comment by kriskog** [comment]
At the very least, leave it as admin only. Its widely used to podbomb dorms. 🙂

**Comment by Tharcoonvagh** [comment]
Just make it admin only lol

**Comment by Dorsisdwarf** [comment]
> 
> 
> I'd be kind of sad to see changes like these happen.
> 
> These kind of little fluff things and references are all about the SS13 lore and culture, the station vibes and general atmosphere of playing the game. Ultimately, these kinds of things ARE all about a part of SS13 culture. A very tongue-in-cheek reference to a different time, done in a humourous way.
> 
> This is still a quirky and cool spacemans game. We're here to have fun at the end of the day. Little things like this remind you that you're playing a game and to have fun. That the ideas behind the game have a good-hearted sense of humour underpinning them.



> 
> 
> I'd be kind of sad to see changes like these happen.
> 
> These kind of little fluff things and references are all about the SS13 lore and culture, the station vibes and general atmosphere of playing the game. Ultimately, these kinds of things ARE all about a part of SS13 culture. A very tongue-in-cheek reference to a different time, done in a humourous way.
> 
> This is still a quirky and cool spacemans game. Weird and wacky. Nonsensical. Mimes. Wizards. Clowns. Clown nuke ops. Aliens. Other aliens. More other aliens. Immersion breaking stuff everywhere. We're here to have fun at the end of the day. Little things like this remind you that you're playing a game and to have fun. That the ideas behind the game have a good-hearted sense of humour underpinning them.

On the one hand I get where you're coming from, but on the other hand the ERP poster is only 3 years old and spamming it at people is a recent shtick it isnt ancient cultural history

**Comment by 81Denton** [comment]
I agree with what @Timberpoes said. If we'd remove everything slightly ick ocky, we might as well run a no fun allowed HRP codebase.

**Comment by Mickyan** [comment]
By law if you remove this ERP is legal again, think about what you're doing

**Comment by necromanceranne** [comment]
> By law if you remove this ERP is legal again, think about what you're doing

All according to keikaku 

(cat note: 'keikaku' means plan in poptart)

**Comment by Qbopper** [comment]
I'd like to see this at least taken off of maps because I'm a huge stickler about netspeak IC, but I doubt anyone will seriously be mad if it gets made admin only or something; you'd probably get more traction there

> These kind of little fluff things and references are all about the SS13 lore and culture, the station vibes and general atmosphere of playing the game. Ultimately, these kinds of things ARE all about a part of SS13 culture. A very tongue-in-cheek reference to a different time, done in a humourous way.
> 
> This is still a quirky and cool spacemans game. Weird and wacky. Nonsensical.

I get this logic but you can still be weird and wacky without acknowledging stuff like ERP in character with items, even though actually saying ERP in character is just as dumb as saying "lol" or whatever

**Comment by LemonInTheDark** [comment]
Timber is right, I don't think this is the source of netspeak either, the erp poster isn't gonna make someone spam gamer constantly. I do get the argument about consistency in game, but I don't think this is a big offender, and the joke outweighs the realism imo

**Comment by optimumtact** [comment]
This is stupid, you're stupid.

**Comment by Timberpoes** [comment]
In response to everyone who has commented towards my opinions:

I don't want to gatekeep what is and isn't part of SS13 culture. These posters didn't influence the players, the players influenced the game in such a way that these posters were put in. This whole PR sparks of removal for the sake of removal. In no way will their removal impact the behaviour of the players.

SS13 is a game, first and foremost. And it's about have fun. These posters a fun. They're silly. They're Saturday morning cartoon levels of wacky. They represent the spirit of what SS13 is about as a game. Fun, crazy spessman adventures with a side plot of murder and mystery.

I stand behind what I said. Things like this add flavour and atmosphere to the game as a whole. In my opinion as both a player and a maintainer, the game itself would be lesser for their removal, however slight and insignificant that would be.

I have far too much respect for Rohesie and other maintainers who may support it to say I'm blocking this PR, but by God am I going to vocalise my sadness at their possible removal and argue my justification for keeping them in hopes that what I have to say has even any impact on the powers that are supporting this to change their course, even slightly.

**Comment by itseasytosee** [comment]
In-game it now stands for Employee "Romance" Practices congrats no more occ in icc, no need to thank me.

**Comment by Dorsisdwarf** [comment]
Again I agree with 90% of what you're saying @Timberpoes but fundamentally disagree that this is in any way a fair comment on the PR. You can in fact copy and paste that precise comment and attatch it to any removal PR the game has ever had and it will be equally as valid.

**Comment by optimumtact** [comment]
@Dorsisdwarf please make a policy thread instead of continuing the argument here. I'm not interested in this change unless the headadmins agree it's a problem and it needs fixing at the code level.

**Pull request closed without merging**
