### PR TITLE
Magic Mania 1.855: Appearances are everything

### PR DESCRIPTION
**Pull request by Incoming5643**
Adds a magic mirror to the wizards shuttle. The magic mirror has greatly expanded functionality compared to the normal one, and can additionally change a wizards name, gender, race, hair color and eye color.

Additionally this fixes up some rogue simulated airless tiles on the wizards shuttle (these tiles were why the creature would always end up dead).

### CODE REVIEW

**Comment by Incoming5643** [comment]
A unique sprite for the magic mirror might be useful to show it off to wizards that it's different.

Changelog coming at not 4 am :sleeping:

**Comment by Chocobro** [comment]
so it's a portable mirror for stealth wizards??
might be good to make another one for randomised maint that can't change name, skin or race imo.

**Comment by Incoming5643** [comment]
it's not portable, it's just in the den so wizards can attack the station who don't happen to look exactly like crew members from the station

**Comment by babinsquared** [comment]
Finally you can play other rounds as your normal self but change yourself into female blonde-braided Marisa Kirisame when the game selects you for wizardry.

**Comment by Xhuis** [comment]
Nice. :mag: :woman:
:+1:

**Comment by Incoming5643** [comment]
There we go, I am now happy with this, wizerp away :+1:

**Pull request merged**
