### PR TITLE
New Gas Flow Meter Sprites

### PR DESCRIPTION
**Pull request by ghost**
With temperature overlays, blue is below 0, green is below 100, red is 100+
gas

From Oracle

:cl:
imageadd: Gas flow meters have new sprites
/:cl:

### CODE REVIEW

**Comment by Tlaltecuhtli** [comment]
make the treeshold custom

**Comment by uraniummeltdown** [comment]
that's genius

**Comment by uraniummeltdown** [comment]
There's a time and place for everything, but not now.

**Comment by DaxDupont** [comment]
Don't fix what ain't broke

**Comment by DaedalusGame** [comment]
gas meters look like shit i'm pretty sure they're the only remaining sprite from openss13

**Comment by DaxDupont** [comment]
>using analog meters
>in 2558

**Comment by DaedalusGame** [comment]
>cameras that need film

**Comment by DaxDupont** [comment]
>what is instant printing

**Comment by DaedalusGame** [comment]
>it doesn't just eat a whole metal sheet like every other instant printing device in the game

**Comment by DaxDupont** [comment]
Though good point I should remove the film requirement from cameras

**Comment by GunHog** [comment]
I find these less easily readable, especially the maximum state. I do not care for the style, either. It simply feels like a downgrade.

**Comment by Jalleo** [comment]
I agree it reduces functionality.

**Comment by WJohn** [comment]
What everyone else has said. These are worse than our current ones.

**Comment by Poojawa** [comment]
I wouldn't say worse, but they're not the right replacements. this could probably be used as actual HUD icons for personal tank gauges determining how much "air" is left in your internals, rather than having to look at the status tab and mental math percentages.

**Comment by CosmicScientist** [comment]
Could these have the needles spin around really really fast and crack the glass under high flow?

**Comment by ACCount12** [comment]
How about we port the ones used on Eris?

**Pull request closed without merging**
