### PR TITLE
[Ready] Tweaks some R&D levels

### PR DESCRIPTION
**Pull request by LatD**
Removes tech levels from some traitor objectives. They had tech levels even before the remake but apparently now that the levels got raised that became a problem. Also some small tweaks to other items to make some early levels easier to get.

~~DNM until I can figure out some other item that gives high electromagnets level. Any suggestions?~~

### CODE REVIEW

**Comment by GunHog** [comment]
> They had tech levels even before the remake but apparently now that the levels got raised that became a problem.

They had tech levels that did not interest anyone previously. The problem now is that they are seen as a requirement to reach tech levels that previously were much easier to attain. Admins bwoink people for stealing these items as a non-antag.

A consideration you need to make here is that whatever tech change you make to require another department's help, you need to make sure that Science can provide something that department wants more than than what it has to give up. _Return on investment._

A great example is Mining <-> Science. Science gets minerals they need to do just about anything interesting, and in return, they provide superior gear (NV Mesons, Satchel of Holding, Jackhammer, Super KA, Bag of Holding). Both sides are happy with this. Science can provide nothing to the CE worth his magboots, and Sec does not seem to care about Science guns that much. I guess they are happy with what they have?

Anyway, what I am saying is that Science needs to be able to give departments things they **want** so hard that they will get into a routine of providing it to Science, just like miners tend to do. One-way dependence will only result in break-ins and thievery. Observe any assistant/clown to see proof of what happens when one guy ones something strongly, but has nothing to provide in exchange.

**Comment by LatD** [comment]
That's how it's working with genetics and botany now, both can give good stuff to each other. Engineering just has nothing it can give to science and science has nothing it can give to engineering. All the machine upgrades in there are useless. I really hope someone adds some cool machine to engineering that has progression and can be upgraded. But that's not happening in this PR.

**Comment by Kromgar** [comment]
Why oh why does making a bag of holding require you have plasma 7 and to research a phazon  torso?

Sure some people make boh singulos but some people ACTUALLY USED THOSE TO STORE SHIT.

Including satchels of holding.


Getting materials 7 and engineering 4 is fucking horrible. I can only make nano manipulators thats fucking retarded. I should be able to make femto manipulators.


Oh and what happens if Genetics is braindead and does nothing? Oh and why is Genetics a source of engineering and not BIO?

This interdependence shit is retarded in a game that only lasts 30 minutes to an hour

**Comment by kevinz000** [comment]
I find this whole thing a bigger middle finger to science then all @KorPhaeron did combined.

**Comment by Kromgar** [comment]
@KorPhaeron made slimes. If anything Kor is a god/dess

Oh and question?

What the fuck do you plant to do to let free golems do research on lavaland? They had a whole thing where they could setup their own little research station but now they are utterly fucked

**Comment by Lumipharon** [comment]
You can't, and shouldn't, balance features around random off station side gimmick shit. It's the other way around.

**Comment by LatD** [comment]
Someone is mad, honk. You can get engineering to 5 in less than 2 minutes without even leaving the R&D room if you're really trying to get it up fast. Have you tried for example deconstructing items from the ENGINEERING section to get ENGINEERING levels up? It shouldn't require much brain activity to figure that out.

Genetics giving engineering is a bit weird yes, but we can't have all xenobio, botany and genetics giving only biotech. Bioengineering is what they do so it's close enough and I'm adding other ways of getting high engineering tech in the other PR.

I'm removing BoH engineering 6 because it was too hard to get for an item that is actually useful (and deadly). It also wasn't possible for golems to get BoH with engineering 6 but it's very easy to get plasma 6. Golems can get all mining tools easily but that's because I made it that miners can get their tools without any other departments helping science. Yes, there are levels that the golems can't get but most items behind those levels are some guns or other items the golems can't even use.

**Comment by Firecage** [comment]
While I disliked the rushed version of R&D, honestly....

Considering how short round lengths are often times, and how soon some people try to get the shuttle called, I just can't see myself liking how R&D is now, but I digress, thats for the feedback thread>

As for this PR, mmm. I disagree with removing the tech levels from the traitor objectives. It honestly just feels like a lazy fix to go: "Nope, now you can't deconstruct them at all." Instead of looking at why people were rushing to steal to deconstruct them now.

**Comment by LatD** [comment]
If people are getting bwoinked just for hiding those items it's easier to remove the tech levels. Rare, good items having high tech levels is a good idea but it's better to keep them away from this if they're unique traitor objectives.

**Comment by Firecage** [comment]
LatD. Then you should make them acid-proof. And unspaceable like the nuke disk. And that explosions don't effect that. And that the singulo can't destroy them.

I think leave them deconstructable, but just lower their tech levels so deconstructing them is as relative in importance as it was before the RD change you did. I just mean that there are already plenty of ways to destroy or permanently get rid of unique traitor items(even by something as simple as you said by hiding them, like putting them inside lockers in maint). So in that regard it would be nonsensicle to make it impossible to deconstruct them

**Comment by Core0verload** [comment]
No. Just no the fuck no. Current tech levels are way too low, they need to be increased on more mundane stuff, not dropped on rare items. Having no way to get T4 unless there is a full competent crew and no antag ruins genetics is fucked up up and away.

**Comment by kevinz000** [comment]
The amount of time required to do research is now often over the round time limit

**Comment by LatD** [comment]
All the admins I've spoken to seem to want the origin techs gone from the unique traitor items so I'll leave them like this. I still have to change some other items in this PR. If you're having trouble getting some certain tech levels I can check if I can make them easier to get. All the early levels should be pretty easy to get.

**Comment by Kromgar** [comment]
The issue is your making research even more tedious than it was before. When a round resets after 30 minutes and you have to do another 20-25 minutes of research who wants to do that? Is it fun or engaging?

It's just a gated system

**Comment by LatD** [comment]
Most of the things you've said aren't even true and they aren't related to this PR in any way. Teleporter boards or BoHs have never needed plasma 7, not before this PR or after this. I've seen people getting high tech items with co-operation much faster than with the old system so the time isn't a problem here either. 

Anyway, after this PR it should be even easier to get the early tech levels up. Main reason I'm lowering tech levels of some items is that there are lots of lvl ~3 items but very few lvl ~2 items so dropping their lvl to 2 should make it easier to get the levels. Now I just need something to electromagnets and this PR is ready.

**Comment by Kromgar** [comment]
Why do ghost chilis give emp 5? How does that even make sense.

ITS A PEPPER

**Comment by PKPenguin321** [comment]
they're high energy that's why they're so deadly

**Comment by GunHog** [comment]
Please return the ability to skip tech levels! I cannot even use the debug research item (The thing with origin tech 8 on all levels). It is one of the things that enforce an artificial delay, ensuring that Science is always likely to exceed the round length, despite having rare, high origin tech level items available.

**Comment by Kromgar** [comment]
Skipping tech levels should be a thing now that this shits more tedious

**Comment by LatD** [comment]
I'll think about it but I'll leave it be for a while at least. Biggest "problem" I see with it is that if you get lucky and find an anomaly core early you just suddenly jump from 1 to 7. And it makes getting high illegal tech really easy which might or might not be a problem, I'm not sure. I'll see how it's going with these tweaks first.

**Comment by optimumtact** [comment]
@Kromgar research was like that before, if anything this just exposes how boring research actually is.

people are literally only dragging themselves through it for the rewards, not because it's engaging.

That in a nutshell is the real issue with RnD

**Comment by Lumipharon** [comment]
Are you implying that like, 50% of the jobs are anything more than 'dragging themselves through it for the rewards, not because it's engaging'?

I don't play chemist because it's fun making chemicals - that's just following fixed instructions. I play it to USE fun chemicals.
Same with robo, xenobio, genetics, viro, botany, sortofchef, cargo, etc.

**Comment by Kromgar** [comment]
Oranges how the fuck do you plan to make Research engaging? There is nothing enjoyable or fun about running around and grabbing items to research. You solely do it for the rewards.

Mining is engaging BUT you still want your damn reward for surviving hell world. Which is a lot harder to get with this research system

**Comment by Core0verload** [comment]
>I don't play chemist because it's fun making chemicals - that's just following fixed instructions. I play it to USE fun chemicals.

Making new chem mixes is fun. More fun than doing RnD routine, and a thousand times more fun than doing _new_ RnD routine.

**Pull request merged**
