### PR TITLE
Adds the 40 player minimum to Families, my bad.

### PR DESCRIPTION
**Pull request by Iamgoofball**
Totally forgot to re-add this. My apologies.
:cl:
fix: families now actually has a player minimum
/:cl:

### CODE REVIEW

**Comment by Tharcoonvagh** [comment]
No cl gang

**Comment by Qustinnus** [comment]
can you also fix the really dumb report you added for families

**Comment by feemjmeem** [comment]
Are you going to make it so that you can opt out of this game mode, or just subject everyone to it forever?

**Comment by Iamgoofball** [comment]
Be less rude.

**Comment by nianjiilical** [comment]
are you sure 40 isn't too high? i mean obviously 40 is probably needed for 3 gangs, but given that 20-30 pop feels more common (antecdotally) it might be worth having a 2-family version that only needs 30~ pop

im just spitballing though im probably entirely wrong

**Comment by Iamgoofball** [comment]
2 families doesn't play well.

**Comment by Iamgoofball** [comment]
when this is merged I'll get on the other changes that need done, otherwise it'd >conflict

**Comment by kriskog** [comment]
This wont be merged until you add a changelog.

**Review by kriskog — CHANGES_REQUESTED** [review]
This wont be merged until you add a changelog.

**Comment by Iamgoofball** [comment]
@kriskog Families having a player limit is already in the changelog. from the original pull request. I literally just forgot to add it.

**Comment by kriskog** [comment]
I dont care. You are making a change, add the changelog.

**Comment by Iamgoofball** [comment]
Whatever, it's "fixed" now.

**Pull request merged**
