### PR TITLE
Add a few more ruins to icebox

### PR DESCRIPTION
**Pull request by EEASAS**
I added a few more ruins to icebox.
Lizard's Gas and Rusky Bar
## About The Pull Request
I added a few ruins to Ice Box Station. Mainly the Lizard's Gas Station and Rusky Bar.
first pr lets go
## Why It's Good For The Game
I feel like it's a bit important for the lore of the game since the lizard's gas station actually exists, but in space.
Think of Moffuchi's Pizzeria.
## Changelog
:cl:
add: A new Lizard's Gas Station building opened up in the Icemoon. An abandoned bar has also been spotted in the Icemoon too.
/:cl:

### CODE REVIEW

**Comment by EEASAS** [comment]
what is mapdiff 2 and why is it angry

**Comment by EEASAS** [comment]
i am waiting for #78917 to be merged so i can add russian troopers in the bar

**Comment by Boopideedoo** [comment]
You could add them now and have it merged with it

**Comment by san7890** [comment]
> i am waiting for https://github.com/tgstation/tgstation/pull/78917 to be merged so i can add russian troopers in the bar

A) I don't think we should have hostile mobs on the surface of icebox. I don't think we have any and I think it should stay that way.
B) Please split this up into two separate PRs then, so we can work on reviewing each map independently of any requirements the other may need

**Comment by EEASAS** [comment]
> > i am waiting for https://github.com/tgstation/tgstation/pull/78917 to be merged so i can add russian troopers in the bar
> 
> A) I don't think we should have hostile mobs on the surface of icebox. I don't think we have any and I think it should stay that way. B) Please split this up into two separate PRs then, so we can work on reviewing each map independently of any requirements the other may need

okay, is it fine if i close this one

**Comment by DaydreamIQ** [comment]
> A) I don't think we should have hostile mobs on the surface of icebox. I don't think we have any and I think it should stay that way.
Hivelords and ancient goliaths can spawn on the top level, which leads to some rare occasions of them immediately aggroing and killing Lia but they do exist

**Pull request closed without merging**
