### PR TITLE
Trubbles & Fur/Fur Clothing

### PR DESCRIPTION
**Pull request by Adrinus**
Trubbles reproduce every 30 Life() ticks or so, until their global numbers are 20.
They can be picked up and turn into an item upon doing so, when this item is dropped() the trubble is placed as a mob again on the floor.
Trubbles can also be neutered with a scalpel to stop them from reproducing, but they must be held as an item or else they "move too much" and you kill them. Neutered trubble may also be "un-neutered" with a cautery.
Butchering a trubble will yield a "pile of fur"

Fur 

After you collect some fur, you can attack_self() it to make fur clothing.

You can make:
-fur gloves
-fur hats
-fur boots
-trubble earmuffs
-fur coat
-fur cape

### CODE REVIEW

**Comment by MrStonedOne** [comment]
@Aranclanos @Giacom 

Still waiting for that answer

**Comment by optimumtact** [comment]
@MrStonedOne performs an ancient necromantic ritual

The PR is alive again

**Comment by Giacom** [comment]
Sure why not, merge it. Though you might want to ask a current maintainer.

**Comment by RemieRichards** [comment]
If the Toy and the Mob were pooled (given they del() (needs to be qdel() also) each other a lot) and the stuff with the cages was sorted out and the fur crafting remains stack recipes (No point in a machine really) I'd be happy with this.

**Comment by FloranOtten** [comment]
Speedmerge

**Pull request closed without merging**
