### PR TITLE
adds netspeak filter

### PR DESCRIPTION
**Pull request by spessbro**
## About The Pull Request

adds a janky netspeak filter when you talk

## Why It's Good For The Game
we've been having lotsa issues with rule 3 so i thought of doing that

## Changelog
:cl:
code: added the filter to say.dm
/:cl:

### CODE REVIEW

**Comment by spessbro** [comment]
yes it is jank as fuck but for all i know it works ok and is much better than what we have right now which is nothing

**Comment by daklj** [comment]
Make it disable itself when there are no admins online. No one but admins gives a shit about people saying lol ic

**Comment by optimumtact** [comment]
Better implementation for performance than #44668 I would say

please make the list a configurable list

**Comment by optimumtact** [comment]
actually never mind currently this is garbage, repeated calls to findtext, unnecessary loops with copytext

**Comment by willox** [comment]
i like that the 'u' checks were changed to if statements to avoid the infinite loop

**Pull request closed without merging**
