### PR TITLE
AIs and Cyborgs have NTnrc, AIs lose PDA and aren't admins anymore.

### PR DESCRIPTION
**Pull request by JohnFulpWillard**
## About The Pull Request

* AIs no longer have direct PDA messaging, but both AIs and Cyborgs now have the NTnrc application in their integrated tablets. They also have a default name of Silicon_[random numbers], similar to humans' "DefaultUser[random numbers]"
* AIs are also no longer 'Admins', and follow the same rules as everyone else using the application.

I'm open to discussion on AI's PDA removal, I wrote this down at 5 in the morning so I likely forgot some things and probably am wrong on some others. I would like to see them get NTnrc applications though.

## Why It's Good For The Game

1. The NTnrc client is pretty much unused, and I thought allowing Silicons to use it would be a nice way to encourage its use, though if AIs have both, I don't see an AI who uses NTnrc over PDA, nor do I think it's a good idea for them to have both at once, as then it splits their attention to two separate applications to check.
2. PDA messages are seen by the CE, while NTnrc messages are seen by the RD. I think that, since the RD is the head of Silicon, they should be the ones that are able to see their messages. Basically, I want to move the jurisdiction of Silicon messaging from the CE to the RD, while also giving Cyborgs the ability to use it for the first time.
3. I thought PDA'ing the AI was a lame way to contact them, unless the CE goes out of their way to check logs, there's no way for anyone to know what you've law 2'd the AI to do, until it's way too late. This now at least makes their actions more visible to people. Now people need to use alternative methods to get the AI to do what they need quickly, and usually it is in a way that is more visible to those around them, or can backfire.
4. Cyborgs don't have any way to contact people, and I don't like the idea of them getting a PDA, so I thought this was a nice alternative, with the AI being there as a benefit.

For the removal of AI as an admin, since Admin mode is generally used to snoop in rooms that are password locked, I would like to see the people who can use it, restricted. Outside of the AI, only the RD and Captain can use Admin mode, which I think is fair.

## Changelog

:cl:
balance: AIs are no longer NTnrc Admins.
balance: AIs no longer have the PDA app
balance: AIs and Cyborgs now have the NTnrc application by default.
/:cl:

### CODE REVIEW

**Comment by carshalash** [comment]
No.

**Comment by JohnFulpWillard** [comment]
> No.

very thought provoking argument right here, my openness to discussion on the topic has concluded. You have proven all my arguments biased and incorrect, and you are the sole decider of everything. I apologize for ever doubting you.

**Comment by Pumpkinoe** [comment]
PDAing is something that's a big part of AI and their communication - all crewmembers (with some exceptions) can PDA each other freely and tell one another about their evil plans or collude to do something terrible, and the CE _can_ see these messages just as much as the AI getting law 2'd via PDA
I'd say honestly it might be better to incentivize the CE checking the PDA device, rather than removing the AI's ability to PDA - since the 'nobody can see your communication this way' also applies to all other crewmembers
sometimes it's nice to have a little bit of sneaky beaky, and there's still a way to get the AI to carry out your law 2 request without using common (holopads, except this one is undetectable by the CE's PDA messaging machine)

**Comment by carshalash** [comment]
> > No.
> 
> very thought provoking argument right here, my openness to discussion on the topic has concluded. You have proven all my arguments biased and incorrect, and you are the sole decider of everything. I apologize for ever doubting you.

Attempting to make more people use the chatrooms by limiting the AI to rely on that as their messaging method ranges from being odd to sadistic. The PDA private messaging system is easy to handle as an AI, it allows precision for important messages to be sent to specific crew members. It enables quick messages to crewmembers who need the info there and then, is sec trying to catch someone that is evading them and you can see them? Quick PDA so only specific officers can know. 

There are still going to be other methods of screaming "AI DO X FOR ME" by using cameras and paper or holopads, it's not really fixing that issue at all and just pushing it onto other methods.

I'm really confused about your 2, 3 points being listed. You're concerned about CE's needing to go out of their way to see messages, but you expect that RD's will always be monitoring chatroom messages? I really don't understand what you mean by this at all.

Is that what you wanted?

**Comment by JohnFulpWillard** [comment]
> PDAing is something that's a big part of AI and their communication - all crewmembers (with some exceptions) can PDA each other freely and tell one another about their evil plans or collude to do something terrible, and the CE can see these messages just as much as the AI getting law 2'd via PDA

That's fair, however as @carshalash pointed out, there's other ways of communicating with the AI through papers on cameras and holopads, while something like the NTnrc client can be used for long-conversations, like a full subversion where planning is needed.

> I'd say honestly it might be better to incentivize the CE checking the PDA device, rather than removing the AI's ability to PDA - since the 'nobody can see your communication this way' also applies to all other crewmembers

That was my point, the CE can still see PDA messages of crewmembers, but it would be nice if the RD can see the messages of Silicon, being their head of staff and all.

> is sec trying to catch someone that is evading them and you can see them? Quick PDA so only specific officers can know.

In this scenario, the AI can use the holopad to tell them, or the security radio. If the person in question has security radio, then it sounds like a good idea that they have an advantage in that scenario.

> There are still going to be other methods of screaming "AI DO X FOR ME" by using cameras and paper or holopads, it's not really fixing that issue at all and just pushing it onto other methods.

Those are alternatives that generally are better because they are limited in one way or another. Paper is quick but you only have so many sheets and you need to get rid of it quick. Holopads are cool but people can walk in. These are all more interesting to me, than just sending PDA messages. From experience, I find contacting AIs to be way more interesting as a Prisoner because of that.

> I'm really confused about your 2, 3 points being listed. You're concerned about CE's needing to go out of their way to see messages, but you expect that RD's will always be monitoring chatroom messages? I really don't understand what you mean by this at all.

I'm not concerned, I just think that it should be the RD's jurisdiction since they're Silicon, not the CEs.

> Is that what you wanted?

Yea

**Comment by GuillaumePrata** [comment]
This removes the easy privacy the AI has with PDA messages and forces the crew to put more effort on their law 2 orders.

I'm all for ~~removing silicon's rights~~ making silicons interact differently from carbons on their "day to day" operations.

**Comment by Pumpkinoe** [comment]
maybe the solution is to not remove PDA messages for AI, but add a way for the RD to see both who they've been contacting/contacted by, and what holopads they've been using? it creates an interesting dyanmic where the AI *might* be getting told certain orders, but the RD has to pursue fun alternate means (the pda server for example) to get to the bottom of it

**Comment by carshalash** [comment]
A lot of crewmember's tablet size can't support the chat client along with everything else, it's a whopping 8gb which is unpleasant. So now let's go into the actual chat client itself, we have two options with how this work. Either the AI makes the room, in this case they must keep the room open at all times as there is no alert for when somebody says anything, in this case the screen for playing AI will look like this.

image

Now, if the AI joins a room created by a player and stays in it, they may be alerted to messages through pings. Surely, **SURELY** this is a good thing right?

image

There is no cooldown to this, you just get flooded with constant **audible** pings, you get the joy of being accosted by the spamming of pings whenever there will be even seconds of delay for **shitheels** and opens up just general griff. 

Another issue is AI shells, they are not connected to the original AI, so you will just have a bunch of different extra accounts. 

image

This is just, an incredibly unfun system at best and a far too EZ way to griff silicons at worst. I still see 0 reasoning in why this should replace PDA's for AI.

**Comment by carshalash** [comment]
image

**Comment by JohnFulpWillard** [comment]
> Now, if the AI joins a room created by a player and stays in it, they may be alerted to messages through pings. Surely, SURELY this is a good thing right?

You can go to your file manager and mute it, or leave the channel, or ask the channel operator to mute the guy. You know there's a whole muting system right?
And even then, it's basically on par with just spamming over PDA.

> Another issue is AI shells, they are not connected to the original AI, so you will just have a bunch of different extra accounts.

That's funny, is that problem for PDAs too?

**Comment by necromanceranne** [comment]
When you were talking about whether or not AI's should be chat admins, I didn't think you were forcing them to use the half-arsed messaging system. Jesus dude.

So carsh has mentioned a few problems with the program already, but another is that the refresh rate of the messaging program seems to reload the window every time a message is sent in the chat client. This means it is really hard to follow a conversation in the program.

I think the program needs some love before it can be considered a fundamental tool for a roles communication. It is deeply outdated.

**Comment by CMDR-Gungnir** [comment]
> You can go to your file manager and mute it, or leave the channel, or ask the channel operator to mute the guy. You know there's a whole muting system right? And even then, it's basically on par with just spamming over PDA.

You can only ping if you ARE the channel operator. Also as the person doing the spamming in that screenshot, let me tell you I can spam the absolute shit out of that ping button infinitely faster than I can spam a PDA.

**Comment by carshalash** [comment]
> You can go to your file manager and mute it, or leave the channel, or ask the channel operator to mute the guy. You know there's a whole muting system right? And even then, it's basically on par with just spamming over PDA.
> 
image

What file manager?

**Comment by CheeseWizard2** [comment]
I feel like this would just make it harder to have private correspondence with the AI
PDAing is simple, gives notifications, and everyone knows it exists.
Console messaging requires you to be at a console, doesn’t give notifications as far as I’m aware, and the majority of people either aren’t aware that it exists or don’t bother with it because nobody ever uses it.
Overall I think this just makes things more complicated, but the reasoning you give is sound so maybe some sort of middle ground would work. Maybe some other ways to bring people’s attention to the existence of the chat client?

**Comment by RikuTheKiller** [comment]
Just got linked here by Jimmyl, and no, I don't approve of this.
1. I play AI and people frequently use their PDA's to grab my attention by using the ringtone beep.
2. Being able to privately converse with the AI through PDA messages seems fair enough to me. You went through the trouble of subverting the AI, why wouldn't you be allowed to have private messaging with them anyways? And if you want to be in even more contact with the AI, simply get the robotic talk implant, you'll get the ability to communicate with cyborgs on top of it.
3. I have literally never heard of NTnrc and I don't think moving it to THIS obscure of a feature is a very good idea, people are just going to not use it, that's how it'll be. You can't teach newbies how to do that kind of stuff very easily until they've grasped almost everything else communications related.

**Comment by Jackal-boop** [comment]
> Fixing this issue is as simple as giving the RD a copy of the pda server code, and or storing it in the vault or secure tech storage

Now that I think about it this doesn't even address an issue what the fuck is this pr

**Comment by thgvr** [comment]
Adding a computer interface to AI and allowing them to use programs on it is a great step and very thematic for the role.

That should be it, that should be the PR. There's not a real reason I can see to restrict communication for a role nearly completely based on communication and exchange of information. Trying to force players to use the IRC apps is never going to work. Forcing players to do things NEVER works - there are many examples from previous prs, even.

**Comment by Jackal-boop** [comment]
Alternatively.  Log all silly cone PDAs in the silicon logs. So rd can read them

**Comment by YakumoChen** [comment]
This seems like a change to the game designed to be extremely cumbersome.

The messaging client is not default to tablets, so one has to go out of their way to communicate with the AI.

It is generally unused by anyone and the AI will have to do needless setup at the start of the round to allow said communication.

The removal of AI from administrator makes little sense. The AI is deeply rooted in all but the most sensitive station machinery, having it be in control of the network seems like a natural privilege for the AI.

**Comment by SkeletalElite** [comment]
This practically a complete removal because no one is going to use ntNRC

**Comment by Shadowflame909** [comment]
the chatroom is really bad and the pda is better to use

forcing the ai into chatroom only status will just lose one method of subtly asking the ai to do something

**Comment by carshalash** [comment]
> the chatroom is really bad and the pda is better to use
> 
> forcing the ai into chatroom only status will just lose one method of subtly asking the ai to do something

Tbh I'm just not gonna use it, it's clunky and obnoxious.

**Comment by Kapu1178** [comment]
was this thought out at all? nobody uses NTnrc because its directly worse than tablets. Just add back messaging groups like the old PDAs.

**Comment by GuillaumePrata** [comment]
> was this thought out at all? nobody uses NTnrc because its directly worse than tablet messaging.

This is just a wrong way to put it. Both have their own pros and cons.

Direct message is well, direct conversation between 2 people, perfect to talk with someone in private and that is it. Most of what other people praise about PDA message can be transferred to chatrooms the moment we decide to do it code wise.

Now chatrooms will be better to communicate with a full department at once. Silicons work perfectly for this, join their chatroom, ask them for something.
Smoother than what we have now, screaming on common for a borg's help or PDA messaging the AI and hoping they manage to wrangle the borgs to assist.

**Comment by CMDR-Gungnir** [comment]
> Now chatrooms will be better to communicate with a full department at once. Silicons work perfectly for this, join their chatroom, ask them for something. Smoother than what we have now, screaming on common for a borg's help or PDA messaging the AI and hoping they manage to wrangle the borgs to assist.

How, exactly, will this get any more success out of getting people to pay attention to you than you could get with the old system? I'm not saying this to be a dick, but to me it genuinely sounds like a "This car will go faster because it's green and I like green."

**Comment by carshalash** [comment]
> Now chatrooms will be better to communicate with a full department at once. Silicons work perfectly for this, join their chatroom, ask them for something. Smoother than what we have now, screaming on common for a borg's help or PDA messaging the AI and hoping they manage to wrangle the borgs to assist.

We already have a method for crewmembers to talk with borgs in their departments.

image

**Comment by GuillaumePrata** [comment]
> How, exactly, will this get any more success out of getting people to pay attention to you than you could get with the old system?

Send a message in the chatroom, if a borg is distracted now, the message will stay there instead of being lost in the common spam. The simple fact that the messages stay logged outside of the chat tab on the right makes communication a lot smoother.

> We already have a method for crewmembers to talk with borgs in their departments.

Radio still is spamville, chat rooms keep things logged and you can follow along on old conversations.

**Comment by CMDR-Gungnir** [comment]
> Send a message in the chatroom, if a borg is distracted now, the message will stay there instead of being lost in the common spam. The simple fact that the messages stay logged outside of the chat tab on the right makes communication a lot smoother.

This assumes the borg is looking at it, but I'll give you that. At least having the opportunity for a Borg to see messages is an improvement. But why can't we simply have AIs and Cyborgs gaining NTnrc without  AI's losing PDA.

**Comment by carshalash** [comment]
No sane silicon is going to play with this thing constantly obscuring half their screen.

**Comment by GuillaumePrata** [comment]
> But why can't we simply have AIs and Cyborgs gaining NTnrc without AI's losing PDA.

Personally I like when Silicons work as a single unit and play by the same rules and having the AI bypass silicon redesigns is just silly.
AI keeping direct messages would make crewmembers use the chatroom a lot less too and then we go on that spiral of "No one uses it so I won't either" that multiple features fall into.

**Comment by Spookuni** [comment]
good to see silicons gaining inherent access to the NTnrc chatrooms, but I'll add my voice to the chorus on PDA messaging - I'm not sold that taking PDA access away from silicons is actually good for the game. Seems like it would be better for them to have access to both.

**Comment by JohnFulpWillard** [comment]
> good to see silicons gaining inherent access to the NTnrc chatrooms, but I'll add my voice to the chorus on PDA messaging - I'm not sold that taking PDA access away from AIs is actually good for the game. Seems like it would be better for them to have access to both.

I'm gonna try to do this gradually, first I'll improve the NTnrc client, then merge it with the PDA app under different tabs, then I'll give another shot at this PR depending on how well it all goes.

**Pull request closed without merging**
