### PR TITLE
Removes voxtest 2, removes /tg/ culture

### PR DESCRIPTION
**Pull request by ghost**
"guys i pressed voxtest 2 again xD"

"trolled ;)"

### CODE REVIEW

**Comment by pudl** [comment]
first!

**Comment by Delimusca** [comment]
there we go TG destroyed mission accomplished

**Comment by xxalpha** [comment]
thank you

**Comment by Deantwo** [comment]
I am just gonna pretend I know what that is.

**Comment by pudl** [comment]
FUCK YOUR CUNT YOU SHITEATING COCKSUCKER MAN EAT A DONG FUCKING MASS ENDING SHITFUCK. EAT PENISES IN YOUR FUCK FACE AND SHIT OUT ABORTIONS OF FUCK AND DO SHIT IN YOUR ASS YOU COCK FUCK SHIT MONKEY ASS WANKER FROM THE DEPTHS OF SHIT.

**Comment by Kraseo** [comment]
/tg/station culture:

FUCK YOUR CUNT YOU SHITEATING COCKSUCKER MAN EAT A DONG FUCKING MASS ENDING SHITFUCK. EAT PENISES IN YOUR FUCK FACE AND SHIT OUT ABORTIONS OF FUCK AND DO SHIT IN YOUR ASS YOU COCK FUCK SHIT MONKEY ASS WANKER FROM THE DEPTHS OF SHIT.
FUCK YOUR CUNT YOU SHITEATING COCKSUCKER MAN EAT A DONG FUCKING MASS ENDING SHITFUCK. EAT PENISES IN YOUR FUCK FACE AND SHIT OUT ABORTIONS OF FUCK AND DO SHIT IN YOUR ASS YOU COCK FUCK SHIT MONKEY ASS WANKER FROM THE DEPTHS OF SHIT.
FUCK YOUR CUNT YOU SHITEATING COCKSUCKER MAN EAT A DONG FUCKING MASS ENDING SHITFUCK. EAT PENISES IN YOUR FUCK FACE AND SHIT OUT ABORTIONS OF FUCK AND DO SHIT IN YOUR ASS YOU COCK FUCK SHIT MONKEY ASS WANKER FROM THE DEPTHS OF SHIT.
FUCK YOUR CUNT YOU SHITEATING COCKSUCKER MAN EAT A DONG FUCKING MASS ENDING SHITFUCK. EAT PENISES IN YOUR FUCK FACE AND SHIT OUT ABORTIONS OF FUCK AND DO SHIT IN YOUR ASS YOU COCK FUCK SHIT MONKEY ASS WANKER FROM THE DEPTHS OF SHIT.

**Comment by Miauw62** [comment]
rip ;_;7

**Comment by Miauw62** [comment]
also >not removing the sound file

**Comment by Razharas** [comment]
Think about the downstreams

**Comment by Fox-McCloud** [comment]
That's not even TG station culture in originality, as far as I know; pretty sure that line is Goon in origin

**Comment by pudl** [comment]
it's tg in origin

**Comment by Fox-McCloud** [comment]
@pudl 

The Voxtest, yes, I have no doubt, the the actual line is definitely Goon in origin.

**Comment by Miauw62** [comment]
ass blast usa is better anyway

**Comment by paprka** [comment]
i'm pretty sure the voxtest2 thing has always been a beepsky thing, and beepsky is a goon thing

**Comment by Firecage** [comment]
Papppiiikkaaaa is right.

**Comment by HoaxIT** [comment]
> 09-Nov-2014 | Warned for pushing voxtest2 ~an0n3

**Comment by Cheridan** [comment]
fun allowed

**Comment by Cheridan** [comment]
Nvm, An0n3 says it gots to go. Blame him.

**Comment by PKPenguin321** [comment]
:+1: now i can play ss13 with the window open without the neighbors wondering if there's some kind of robotic domestic abuse going on in my house
also, >removes /tg/ culture
kek

**Comment by An0n3** [comment]
Thank you.  Please direct all loathing for your lack of ability to push a button and fill everyone's ears with the same tired bullshit at me personally.  Don't shoot the messengers.

**Comment by GunHog** [comment]
:-1: This is bad, you should feel bad.

**Comment by Ikarrus** [comment]
Feel free to direct hate at me for this too. I support anon's decision in this matter. 

Fuck stupid vox spam and fuck your idea of muh culture.

**Comment by dannno** [comment]
if you still giggle when you hear this for the 2000th time you don't deserve an opinion on the matter because you are obviously under the age of fetus years old

**Comment by paprka** [comment]
i literally laughed out loud

**Comment by MrPerson** [comment]
Please actually remove the ogg from the repository and then this'll get pulled.

**Comment by paprka** [comment]
oh okay

**Comment by paprka** [comment]
dunn

**Comment by AnonymousNow** [comment]
Ehh.

I want to keep a hold of it. Though it should only be accessible to malfunctioning AIs.

**Pull request merged**
