### PR TITLE
Science lathe prints everything again

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
Techwebs are still messy and unbalanced with bad UI and no documentation and the ore distribution is a mess and we're in a weird awkward situation where every department is supposed to print their own stuff but only science picks which stuff and cargo never gives security minerals anyway

It's a one line change to let science build everything again while we clean up techwebs and once techwebs are nice and functional and people are used to them we can try the decentralization thing and maybe everyone will stop being so salty in the mean time

### CODE REVIEW

**Comment by Buggy123** [comment]
THIS PLEASE NOW YES FUCK ME

**Comment by Buggy123** [comment]
NO!

**Comment by vuonojenmustaturska** [comment]
is there anything in the service or medbay lathes that science wants? i know they really want to deconstruct the engineering lathe, and presumably the security lathe if they wouldn't get spaced for doing that

**Comment by GunHog** [comment]
Please re-open :(

**Comment by optimumtact** [comment]
no

**Comment by F-OS** [comment]
This was closed without allowing reasonable discourse, please reopen this as I feel this is an abuse of maintainer power, 
see "Maintainers are quality control. If a proposed pull request doesn't meet the following specifications, they can request you to change it, or simply just close the pull request. **Maintainers are required to give a reason for closing the pull request.**"

**Comment by Cyberboss** [comment]
Maintainers are required to give a reason for closing the pull request: 

Science is on death's row
Research is being decentralized
We aren't reverting techwebs
This is the direction development is going

**Comment by Hatfish** [comment]
>Techwebs are still messy and unbalanced with bad UI and no documentation and the ore distribution is a mess and we're in a weird awkward situation where every department is supposed to print their own stuff but only science picks which stuff and cargo never gives security minerals anyway

this still hasn't changed in over a month

**Comment by GunHog** [comment]
I would almost pay money to have this back. Science has become so lonely for me since this happened.

**Pull request closed without merging**
