### PR TITLE
Moved grav gen on runtime station

### PR DESCRIPTION
**Pull request by grungussuss**
## About The Pull Request
This mfer keeps buzzing when I'm trying to demo my sounds, so I moved him.
Added a pod testing area in the hallway to the grav gen

I know I could just move to a different room but the main experimentation room is affected to it so I'd say better move it.
## Why It's Good For The Game
I'd like to showcase my sounds without the grav gen buzzing.
## Changelog
no player facing changes.

### CODE REVIEW

**Comment by Sadboysuss** [comment]
> Just add a debug subtype that doesn't buzz.

I wanted to do that but I realized you might want to listen to the thing buzz in debug, so I just moved it

**Comment by projectkepler-ru** [comment]
> > Just add a debug subtype that doesn't buzz.
> 
> I wanted to do that but I realized you might want to listen to the thing buzz in debug, so I just moved it

smart

**Comment by Ghommie** [comment]
Merge conflicts.

**Comment by Ghommie** [comment]
You didn't properly clean out the conflicts.

**Comment by Sadboysuss** [comment]
> You didn't properly clean out the conflicts.

yeah I'll be honest I just hit upstream merge and forgot about it, second

**Pull request merged**
