### PR TITLE
Away missions runtimes fixing

### LINKED ISSUE #16046: Maploader assigning vars to the wrong atom
An *unmodified* version of the Maploader is trying to assign vars to the wrong atom, which results in a buttload of runtimes.

I suspect a preloader ```load()``` call is happening before a preloader ```setup()``` call, but I was unable to find evidence of this.

<B>Example:</B>
Undefined variable /obj/machinery/suit_storage_unit/mining/var/isbroken  <B>//this is a newscaster var, which is super odd</B>
runtime error: 
[18:41:49]
[18:41:49]proc name: load (/dmm_suite/preloader/proc/load)
[18:41:49]  source file: reader.dm,356
[18:41:49]  usr: null
[18:41:49]  src: /dmm_suite/preloader (/dmm_suite/preloader)
[18:41:49]  call stack:
[18:41:49]/dmm_suite/preloader (/dmm_suite/preloader): load(the suit storage unit (/obj/machinery/suit_storage_unit/mining))
[18:41:49]the suit storage unit (/obj/machinery/suit_storage_unit/mining): New(the floor (215,72,8) (/turf/simulated/floor/plasteel))
[18:41:49]the suit storage unit (/obj/machinery/suit_storage_unit/mining): New(the floor (215,72,8) (/turf/simulated/floor/plasteel))
[18:41:49]the suit storage unit (/obj/machinery/suit_storage_unit/mining): New(the floor (215,72,8) (/turf/simulated/floor/plasteel))
[18:41:49]the suit storage unit (/obj/machinery/suit_storage_unit/mining): New(the floor (215,72,8) (/turf/simulated/floor/plasteel))
[18:41:49]/dmm_suite (/dmm_suite): instance atom(/obj/machinery/suit_storage_un... (/obj/machinery/suit_storage_unit/mining), /list (/list), 215, 72, 8)
[18:41:49]/dmm_suite (/dmm_suite): parse grid("/obj/machinery/suit_storage_un...", 215, 72, 8)
[18:41:49]/dmm_suite (/dmm_suite): load map(_maps/RandomZLevels/caves.dmm, 0, 0, 8)
[18:41:49]new map instance(/datum/map_instance/caves (/datum/map_instance/caves))
[18:41:49]createRandomZlevel()
[18:41:49]Master (/datum/controller/master): Setup(null)
[18:41:49]world: New()

### PR DESCRIPTION
**Pull request by Menshin**
Fixes #16046.

Also fixed the wrong `filter_type` on `undergroundoutpost45.dmm`, which causes runtimes at each atmos ticks.
Fixed Snowdin runtimes too.

### CODE REVIEW

**Comment by RemieRichards** [comment]
So it was the MAP MERGER

**Comment by Menshin** [comment]
Suspecting a rogue mapmerger too.

**Comment by xxalpha** [comment]
It wasn't the new map merger and I can guarantee that.

**Comment by AnturK** [comment]
Could use try catch in preloader to catch these but it's probably gonna be performance hit.

**Comment by RemieRichards** [comment]
@AnturK 
HUGE performance hit:
1. Try/Catch performance is terrible anyway in DM
2. We'd be doing it on every single atom.

Here's at an estimate for a 255x255 map (which atm loads in 1-1.5 seconds which is not /bad/):
255x255 Turfs = 65025
255x255 Areas = 65025
GOD KNOWS how many other atoms, but lets assume like Boxstation the center is mostly dense with atoms: 100x100 = 10000

So roughly 140050 Atoms are being messed with for a simple 255x255 Box-like map.

**Pull request merged**
