### PR TITLE
Not so fucked outpost45 update

### PR DESCRIPTION
**Pull request by Yobrocharlie**
## About The Pull Request

Second PR of my attempt to make an outpost-45 PR because the first one got fucked, i hope what im doing is okay and if you want to see the original PR please go to ---> https://github.com/tgstation/tgstation/pull/75744

Outpost45 is as of now, over eight years old, and after so much time it has gotten very, very little attention, this fixes that and completely changes the gateway destination to have much more than it currently does both in terms of area to explore, story to learn, and stuff to grab.
## Why It's Good For The Game

As of right now outpost45 sat at a spot where people would wait to see what the gateway destination is, see its outpost45 by the ominous purple glow, and then immediately back away knowing that outpost45, in a casual conversation in a ticket I was talking with an admin and they said "Well then if you don't like it anybody can contribute" and so I did. (Extreme thank you to pumpkin0, vekkter, and jolly for helping me learn how to PR, how to github, and how to map.)
## Changelog

Adds two new areas complete with their own threats and rewards,
Adds an old crowbar to the engineering storage
Generally makes the gateway have a much more engaging story
:cl:
add: More stuff to outpost 45 including two new areas full of hostiles
/:cl:

### CODE REVIEW

**Comment by Pumpkinoe** [comment]
You still have merge conflicts

**Comment by Yobrocharlie** [comment]
> You still have merge conflicts

**Yea i kind of noticed**

**Comment by Yobrocharlie** [comment]
i also want to say that if this does not get merged within like 24 hours it will probably just go stale and then nothing for four or so weeks, I am going to be disappearing off of the face of the earth for a month or two tomorrow,

The only issue i have in my mind as of right now would be if the ladders work which i have no confidence in if they work or not

**Comment by Pumpkinoe** [comment]
Test it instead of praying that they work!!

**Comment by Yobrocharlie** [comment]
I would if I could

**Review by Maurukas — CHANGES_REQUESTED** [review]
You can check this map by editing two files:
In gameoptions.txt uncomment `ROUNDSTAR_AWAY`
In awaymissionconfig.txt uncomment `_maps/RandomZLevels/undergroundoutpost45.dmm`

Compile and launch the server. The map will load at roundstart and you can jump to it.

There are a number of piping issues, doubled up and disconnected pipes. I recommend running the 'Check plumbing' verb in the mapping tab, and correcting any issues you find on the map (there will be some false positives and ruins in the list as well).

image
image
image

These are throwing quite a few runtimes at startup.

**Comment by YuliceTheDruid** [comment]
Damn, that means this isn't gonna be in for at least a couple months given what he said earlier in the comments

**Comment by Yobrocharlie** [comment]
What is given right now is a nigh almost finished product with few touch ups, sadly I have begun travel so I will not be able to make any edits henceforth for like, maybe a month and a half

**Comment by Spookuni** [comment]
Adding three active alien eggs to an away mission seems like a very bad idea.

**Comment by YuliceTheDruid** [comment]
> Adding three active alien eggs to an away mission seems like a very bad idea.

We literally already have an away mission that has 3 active eggs.

**Comment by Spookuni** [comment]
> We literally already have an away mission that has 3 active eggs.

That seems like a really bad idea to keep around or propogate

**Comment by YuliceTheDruid** [comment]
> That seems like a really bad idea to keep around or propagate

I mean it's subject to self antag rules; anyone who starts abusing them will be obliterated by admins. And the fact that they've been around so long and not even been noticed by the admin team should suggest that the playerbase does have restraint in this singular aspect at least.

**Review by Maurukas — CHANGES_REQUESTED** [review]
Still a number of broken pipes: 
image

**Comment by Yobrocharlie** [comment]
> Still a number of broken pipes:
> image

I will fix these when I get home

**Comment by Yobrocharlie** [comment]
> Adding three active alien eggs to an away mission seems like a very bad idea.

Generally the playerbase is not stupid enough to
1: Get hugged in the first place
2: To let it burst

As a final point, quite literally regardless of what antag you are, unless you have a hive node or some way to reasonably control them, getting anything including yourself hugged on purpose and letting it hatch is a good way to get your balls busted

(However I do see borgs on purposefully getting a monkey hugged all the time on normal TG, because borgs are shitters)

**Comment by Yobrocharlie** [comment]
I might just close this and re-build the entire map from the bottom up after san’s PR is merged

**Comment by Yobrocharlie** [comment]
Next week:tm:

**Comment by Yobrocharlie** [comment]
Sisyphus-e1557869810488

**Comment by Yobrocharlie** [comment]
Can somebody remove the stale, I will get to getting around to fix this,

once I’m actually able to that is

**Comment by Yobrocharlie** [comment]
okay lets finish this

**Pull request closed without merging**
