### PR TITLE
Fixes pugs not following their tail.

### PR DESCRIPTION
**Pull request by Aranclanos**
The staff of change won't create invisible pugs anymore, same with the experimentator relics.
Removes a leftlover pug typepath.

### CODE REVIEW

**Comment by Aranclanos** [comment]
This fails to compile because there's a pug of the wrong path in metastation, but I can't edit the map because metacide is currently changing it.

**Comment by Metacide** [comment]
Ah, sorry - I've gotten rid of that old path in https://github.com/tgstation/-tg-station/pull/11553

**Comment by Aranclanos** [comment]
how do i make it try to compile again

**Comment by duncathan** [comment]
close then reopen I think

**Comment by Aranclanos** [comment]
should be good to go

**Pull request merged**
