### PR TITLE
Fixes antaghud for ninjas

### LINKED ISSUE #15973: Admin antag hud doesnt work for ninja
No antag hud icon is shown.
@lordpidey

### PR DESCRIPTION
**Pull request by lordpidey**
Also fixes a related runtime.
Fixes #15973

### CODE REVIEW

**Comment by coiax** [comment]
THE NINJAS KNOW IF YOU DON'T HAVE A SOUL

**Comment by lordpidey** [comment]
@coiax just to be absolutely sure:  You're joking right?  I had halfway implemented a hud for soulsellers, and then removed it because it didn't work right (or at least HOPE I removed all of it).  If ninjas are seeing soulsellers, that's a problem.

**Comment by coiax** [comment]
I have no idea, I'm not an admin so I don't get AntagHUD on a live server, but I saw sprites for soul sellers HUD in the icon files, so I thought it was already a thing. My mistake.

**Comment by Shadowlight213** [comment]
@Coiax ling antag hud seems to be broken as well if you want to take a shot at that.

**Comment by coiax** [comment]
Changelings have antag hud?

**Comment by Shadowlight213** [comment]
Oh woops. meant @lordpidey 
Admin antag hud for lings doesnt work.

**Comment by lordpidey** [comment]
Huh.  I'll have to look into that one, it's probably not going to be a simple fix.

**Comment by optimumtact** [comment]
Ninjas :snowflake: :no_good:

**Pull request merged**
