### PR TITLE
Revert "Removes fucking gangs"

### PR DESCRIPTION
**Pull request by Iamgoofball**
Players didnt want it removed, check le vote.

Closes #30323

### CODE REVIEW

**Comment by MoreRobustThanYou** [comment]
fuck off goof

**Comment by The-clown-known-as-Pepe** [comment]
fuck o-

oh wait you're permabanned already @MoreRobustThanYou

**Comment by PraiseRatvar** [comment]
ITS FUCKING 2%, PLUS THE VOTE HAD AN EXTRA MEME ANSWER AS A CHOICE.

**Review by Cyberboss — APPROVED** [review]

**Comment by PraiseRatvar** [comment]
OK HERE'S AN IDEA

DO A PROPER POLL WITH NO MEME ANSWERS AS A CHOICE. JUST THE BASIC YES OR NO PLEASE

**Comment by KorPhaeron** [comment]
Half of players disliked it strongly enough to want it outright removed

If half the players online are not having fun at all the mode is a failure

**Comment by MrStonedOne** [comment]
>ITS FUCKING 2%, PLUS THE VOTE HAD AN EXTRA MEME ANSWER AS A CHOICE.

That extra meme answer kept non-serious people from voting. If you don't care enough about the issue to resist the meme option, your vote wouldn't have mattered.

Trust me, that meme option kept randoms who don't care from voting.

**Comment by GuyonBroadway** [comment]
TO quote the hippie discord a moment. 
> The mere fact that people can't handle the occasional round where things aren't as they like is evidence that it's either the community with a manchildren minor vocality or the coders grudge-coding
It's the same behavior that turned HRP servers into the shit pools they currently are. The few who yell and yell and screech to everyone and everything on how they don't like this and they want this removed and they want it removed right now
Gang was one of the better gamemodes and they are codebase-unique. No other server except Goon has them, and they are an adminbus-only gamemode on Goon that never appears
"Hey, let's work on improving gang based on community feedback"
"REEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE"

**Comment by Robustin** [comment]
Ok I will make this pitch one last time. 

Kor wanted the no-security version, it never got added because it was controversial. The only thing that changed between this poll and the previous 2 is Gang got left in an unfinished and unbalanced state for 3 months. Support for Gang back in rotation always came with an * - *As long as it gets updated, fixed, and improvements. 

The no-security/vigilante version was divisive though. Over 70% of the community wanted Gang in rotation but it was split between half who just wanted it AS IS and half who wanted some significant changes. It's not clear if there's a middle ground that can satisfy most people. 

I'd still finish it if I had any realistic path forward.

**Comment by GunHog** [comment]
Let Robustin fix it, at least.

**Comment by Robustin** [comment]
I regret not separating the fixes and balance stuff from the Vigilante stuff but since the former was being done in the context of the latter it would've been even more time consuming to try and balance the live version while also balancing the test version. 

It still wouldn't resolve the underlying issue though, and frankly nobody, myself included, should even consider touching the mode until we can reach a single bloody decision about whether we keep security around during Gang War.

**Comment by KorPhaeron** [comment]
Anything short of removing security will just condemn the mode to being another mediocre "security kicks down every door and implants every crew member before anything happens" rehash like the other conversion modes play (or security doesn't do that, they get murdered, and they go vote for the mode to be removed)

**Comment by Robustin** [comment]
I understand your position Kor, thats why I made vigilantes... it definitely was unique and I think it would've been good with enough balancing to make sure the mode felt coherent. I still have fond memories of forming a loose alliance of vigilantes and holing up in the Chapel.

The problem is that I could open a PR for that and it would spend months sitting around as everyone rehashed the same debate about TDM or whatever - the idea of a "(safe) home base" might have addressed some of those concerns but its just more of the same "code first, test second, sit around for weeks trying to get it merged while waging a PR battle that ultimately goes nowhere... third".

**Comment by KorPhaeron** [comment]
In two weeks I'll be headmin again so that will somewhat consolidate the number of people you need to convince to get a game mode on server

**Comment by MoreRobustThanYou** [comment]
@Robustin no offense, but _maxcapping_ sec at roundstart and literally **letting the greytide be "sec"** is an extremely shitty idea.

**Comment by kevinz000** [comment]
not really

**Comment by DoctoreMad** [comment]
>TO quote the hippie discord a moment.

I slightly considered closing my ears for a minute but hey maybe there's something special...

>The mere fact that people can't handle the occasional round where things aren't as they like
Gang was one of the better gamemodes and they are codebase-unique

Okay nevermind, not at all. 
You could legitimately use this non-argument on any game mode you like. Seriously, try it.

**Comment by Robustin** [comment]
Weren't the headmins already in favor of keeping it around? Regardless I've got no problem sitting on it until there's a more definitive goal for the mode.

**Comment by KorPhaeron** [comment]
@DoctoreMad

Its funnier when you realize a hippy coder is the one who removed it as well

**Comment by Robustin** [comment]
@MoreRobustThanYou 

You did illustrate one of the difficulties in testing. The last ~2 weeks that it was getting tested the roundstart was no longer "maxcap sec" but rather just sec being stripped bare, you could still pry open the doors and make it into your own hideout and I really liked it. 

The underlying issue is true though. "Everyone is sec now" isn't inherently a bad idea, players can still choose if they want to be neutral like they would during a normal round or if they want to validhunt. I think it promotes more interesting conflict than [Security v. Man with Spraycan]. My biggest issue is that the violence kicks off a little TOO fast, I don't want Gang Wars to drag out but at the same time I'm not too keen on having a half-dozen dead a few minutes in. 

If I tried another PR I would delay the bosses' getting their equipment for maybe 2-3 minutes so people have time to prepare and people who simply don't want to get involved can take steps to secure their workplace without people getting penned right off the bat. I recall turning down this idea before because I felt it wouldn't add anything to the round, just a few minutes of mass-looting but in hindsight I don't think it could be any more chaotic than the previous tests and a few minutes of people not murdering would give all sides a chance to communicate and strategize without the immediate pressure of MUST CONVERT, MUST TAG, MUST KILL.

**Comment by lzimann** [comment]
Gang is dead, its shitness will never shit on this codebase again, or maybe someone will act stupid and merge this even though it would be a bad idea.

**Comment by KorPhaeron** [comment]
I don't think the PR needs to be merged as is without any rework plan

@Robustin If you plan on doing it again you should start with a complete design document and we can try to mostly agree on everything before you burn a bunch of time coding it

**Comment by DoctoreMad** [comment]
>you should start with a complete design document and we can try to mostly agree on everything before you burn a bunch of time coding it

Why don't we do that by default again @KorPhaeron

**Comment by KorPhaeron** [comment]
Its hard to get people to take your design document seriously because it just gets lost in the mess of all the other ideas guys talking about things that will never be coded

**Pull request closed without merging**
