### PR TITLE
Move autoadmin to a protected config datum

### PR DESCRIPTION
**Pull request by optimumtact**
This prevents any admin with permission to debug controller being able to edit this setting

### CODE REVIEW

**Comment by MrStonedOne** [comment]
Technically speaking, if you don't enforce it in VV then an admin can still var edit it by brute forcing the \[ref] address. And since its created after the config controller, this would actually be easy to guess, it will (99% of the time) be the ref of the config control +4

**Comment by MrStonedOne** [comment]
I've had an idea for a way to OOP the way vv restricts reads and writes.

There is no need to restrict reads on this, just writes.

**Comment by optimumtact** [comment]
yeah I did think about that, but I was going for the low effort approach

**Comment by Ricotez** [comment]
if an admin bruteforces their way into a higher rank like that it might be time to reconsider their status as an admin in the first place

**Comment by optimumtact** [comment]
Well yeah, but no harm in making in harder for them to do it.

**Pull request merged**
