### PR TITLE
Fixes ephedrine not making you go faster. This also fixes stimpacks.

### PR DESCRIPTION
**Pull request by Iamgoofball**

### CODE REVIEW

**Comment by GunHog** [comment]
Will this cause OD in a stim virus?

**Comment by Fox-McCloud** [comment]
technically speaking, this belongs to Meth--Ephedrine is just a stun reducer.

of course, if you're not planning on implementing Meth, then this is the best solution.

**Comment by Miauw62** [comment]
tbh it'd be more efficient to just add a "gofast" variable to reagents and "only" loop through the reagent list once.

**Comment by Iamgoofball** [comment]
yeah, i'll look into it

**Comment by phil235** [comment]
@Iamgoofball still working on this?

**Comment by Razharas** [comment]
I thought it was fixed by adding noslowdown to epinephrine, no?

**Comment by paprka** [comment]
this is basically fixed

**Pull request closed without merging**
