### PR TITLE
Revert "Changes to DNA Injectors"

### PR DESCRIPTION
**Pull request by ghost**
Reverts #12067. Negative feedback was massive, and @duncathan refused to utilize the test merge functionality. Even phil235, an experienced maintainer, disagreed with the changes.

### CODE REVIEW

**Comment by Bluespace** [comment]
Can we keep the UI + UE thing though

**Comment by Xhuis** [comment]
That's actually a good feature, but I used GitHub's easy revert system rather than making a new branch and PRing that. I'll contact AnturK after the initial changes are removed to make an initial UI+UE, or just not at all if people end up liking them.

**Comment by Iamgoofball** [comment]
can we keep UI+UE injectors at least

**Comment by duncathan** [comment]
I said I would revert it myself at the end of the week if feedback remained negative on live
there are features that came with the PR that are good; a flat out revert like this isn't good either

denied

**Comment by Iamgoofball** [comment]
whoa now dunc you dont understand maintainer protocol

**Comment by duncathan** [comment]
no reverts for a week :^) it's a rule I swear

**Comment by Lumipharon** [comment]
And this is why shit never gets reverted.

>we'll compromise guis

**Comment by duncathan** [comment]
@Lumipharon people don't want everything reverted tho. They want to keep the UI/UE thing. A stright up revert doesn't accomplish that; you've gotta have more finesse.

**Comment by Lumipharon** [comment]
Which is why you dont yolomerge pr's to begin with.

**Comment by duncathan** [comment]
@Lumipharon you're absolutely right. this was my fault, which is why I want it to be fixed properly. see #12977

**Pull request closed without merging**
