### PR TITLE
Allows captains to organize a shuttle build event

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
:cl: Kor
add: The captain may now purchase an unfinished shuttle chassis, which will dock immediately when bought, but will not launch until the end of the regular shuttle call procedure. The shuttle is empty and devoid of atmosphere however, so you'll need to do some work on it if you want a safe trip home.
/:cl:

### CODE REVIEW

**Comment by RandomMarine** [comment]
Will this instakill anyone who happens to be loitering in the shuttle zone on purchase?

**Comment by KorPhaeron** [comment]
Probably

**Comment by Incoming5643** [comment]
1. What happens if you later buy a new ship?
2. Can this be used to rush a round end? (Does it respect refueling times?)

**Comment by KorPhaeron** [comment]
@Incoming5643 

1. You can't buy a second ship after the first. If you did it would delete the shuttle and everyone on it though when the new one was loaded (back at  centcomm though I think)

2. You still need to call the shuttle normally after this even though it's sitting physically at the station

**Comment by Crushtoe** [comment]
It has to rev up its engines first, duh.

**Comment by KorPhaeron** [comment]
@Crushtoe 

Probably, I'm a bit hesitant about adding so many snowflake checks for this though

**Comment by Iamgoofball** [comment]
can you make it start with only 1 plating since we can't remove it easily

**Comment by Bawhoppen** [comment]
I swear I'll finish proper shuttle building sometime

**Comment by jughu** [comment]
Kor only of you make thrusters makeable by using plasteel

**Comment by KorPhaeron** [comment]
@jughu 

It comes with thrusters

**Comment by jughu** [comment]
Tfw we are limited to designs

**Comment by jughu** [comment]
@korpaeron is it also marked how big the shuttke wil be?

**Comment by TehZombehz** [comment]
Rolling for antag is overrated. The best way to griff is to roll captain and order this ~~when there are no engineers~~ / ~~because no engineer is competent enough to construct a livable one~~ ever.

Still love it, though. 👍

**Comment by Jordie0608** [comment]
Reconvert the map file to TGM.

**Comment by PKPenguin321** [comment]
I think this would work better if it started with an atmosphere and didn't have any breaches

**Comment by optimumtact** [comment]
Test merge please, I'm not sure if this would work very well with our ticker

**Comment by KorPhaeron** [comment]
Not sure why it'd work differently live on server than locally, but sure

**Comment by kevinz000** [comment]
Actually it's more of "How do we know shitlers will just buy it just to fuck the round over in an emergency by ordering an empty shuttle when half the station's destroyed"

**Comment by kevinz000** [comment]
@KorPhaeron please make frame bigger so I can put more stuff

**Comment by KorPhaeron** [comment]
Just how much stuff do you need?

**Pull request merged**
