### PR TITLE
Standardized CENTCOM spelling

### PR DESCRIPTION
**Pull request by ShizCalev**
1257 instances of CENTCOM
26 instances of CENTCOMM (+12 comments)

https://tgstation13.org/wiki/Centcom_Official
https://tgstation13.org/wiki/Emergency_Response_Team
https://tgstation13.org/wiki/Centcom

Standardized capitalization from Centcom to CentCom

### CODE REVIEW

**Comment by KingPhilipIII** [comment]
I support the varient with two m's.

**Comment by PraiseRatvar** [comment]
@optimumtact @Qbopper loremasters!!

**Comment by ShizCalev** [comment]
The real question; Centcom or CentCom

**Comment by Xhuis** [comment]
Centcom feels cleaner imo, but that's just me.

**Comment by KingPhilipIII** [comment]
CentComm is a shortenting for Central Command. So the two C's should be capitalized.

**Comment by tortellinitony** [comment]
CentComm looks better than Centcom

**Comment by DoctoreMad** [comment]
Truly the autism of ages

**Comment by optimumtact** [comment]
It's almost certainly intended to be Centcom, and that's backed up by the pages on the wiki and also Goon's wiki

**Comment by KorPhaeron** [comment]
CentCom is the real life spelling so makes sense

**Comment by Qbopper** [comment]
technically CentCom makes more sense but my personal preference is Centcomm

**Comment by Qustinnus** [comment]
CentCom looks way better.

**Comment by Qbopper** [comment]
yeah this isn't as big a deal as nanotrasen to me

**Comment by pubby** [comment]
make it a hyperlink

http://cent.com

**Review by Cyberboss — APPROVED** [review]

**Pull request merged**
