### PR TITLE
directional AI hologram sprites!

### PR DESCRIPTION
**Pull request by azrael-x86**
## About The Pull Request
(big thanks to @Azarak for the coding help, and @Dorsisdwarf for the suggestion!)

Animation

with the latest advances in holotech, you can now use the block movement keys (alt + movement key) to change the facing direction of your AI hologram! spin on security while they're trying to work, and spin on the captain when he asks you if you're malfunctioning!

Capture

only drawback: the latest pr that introduces AI custom characters has been changed slightly, refactoring the AI hologram system to use the mutable appearance of the character instead of the flaticon (only when custom character is selected). this means the scanline effects will no longer works, unless a maintainer can point out any way to get the dynamic icon of a mutable appearance without using the inefficient getFlatIcon system.

## Why It's Good For The Game

we all know that directional sprites are important to roleplay experience, being a visual indicator of who you're talking to, where you're aiming a weapon, or your intent of direction of travel. generally just a nice and fun things to have for the AI.

## Changelog

:cl:
expansion: adds the ability to change directions as an AI hologram! yippee!
/:cl:

### CODE REVIEW

**Comment by magatsuchi** [comment]
> GBP >:(

have mercy

**Review by Ghommie — CHANGES_REQUESTED** [review]
Question. Does the direction of the hologram automatically match the movement direction akin to standard movables movement or not? Having it only bound to alt+movement key doesn't seem quite purposeful.

**Comment by magatsuchi** [comment]
> Question. Does the direction of the hologram automatically match the movement direction akin to standard movables movement or not? Having it only bound to alt+movement key doesn't seem quite purposeful.

not as of yet. once i find out how to because im dumb

**Comment by MrPerson** [comment]
If this PR makes getHologramIcon() unused, you should go ahead and remove it.

**Review by Kylerace — CHANGES_REQUESTED** [review]

**Comment by Dorsisdwarf** [comment]
> 
> 
> I thought we had this but then it got changed or something

We did but it got removed for more customisability in ai chars

**Pull request closed without merging**
