### PR TITLE
Super Surplus Crate

### PR DESCRIPTION
**Pull request by Iamgoofball**
Idea stolen from leddit
:cl: Iamgoofball, Anuvkh from Reddit
experimental: Super Surplus Crates are now available for 40 TC. They come with 125TC of shit. Have fun with teamwork!
/:cl:

### CODE REVIEW

**Comment by GunHog** [comment]
Now THIS is a PR I can REALLY love!

**Comment by Armhulen** [comment]
goodball

**Comment by 81Denton** [comment]
That's how you get people to use codewords

**Comment by Buggy123** [comment]
Can nuke ops buy this?

**Comment by Iamgoofball** [comment]
God, no.

**Comment by Buggy123** [comment]
Damn.

**Comment by ma44** [comment]
When can I order it for -valid hunting- making cargonia even better

**Comment by Iatots** [comment]
Too bad the good shit has shit weights appended, enjoy 125tc of duplicates.

**Comment by ExcessiveUseOfCobblestone** [comment]
@Iatots what weighting?

**Comment by Ratvar** [comment]
Hyper surplus crate for 50 tc when

**Comment by ExcessiveUseOfCobblestone** [comment]
Super Ultra Contraband Crates (formerly known as SUCC)

**Comment by Armhulen** [comment]
give me the succ

**Comment by Robustin** [comment]
It sounds crazy but it's really not that strong. You're teaming up with another traitor and risking the rare backstab for what will typically pan out to be an extra 12.5TC for your "cut". Even without an overt backstab you still run the risk of them just taking something you wanted and insisting on keeping it. 

Decent compromise but hardly something I would go rushing to team up with someone over. I'd typically try it out if it was something where I shouted my words and contacted another traitor and our mutual feeling was "meh, I dunno". Even then you'd probably getting a better payoff with using one crate and then using the remaining 20TC to fill out any needs (thermals, noslips, emag).

**Comment by ExcessiveUseOfCobblestone** [comment]
It sounds crazy but it's really not that strong. You're teaming up with another traitor and risking the rare backstab for what will typically pan out to be you throwing out your round assuming the zombie is competent and can infect someone, else you just threw 25 tc down the drain. Even without an overt backstab you still run the risk of them just leaving you for dead later in the round or keeping the remainder of the TCs to themselves.

Decent compromise but hardly something I would go rushing to team up with someone over. I'd typically try it out if it was something where I shouted my words and contacted another traitor and our mutual feeling was "meh, I dunno". Even then you'd probably getting a better payoff buying a surplus crate and then using the remaining 20TC to fill out any needs (thermals, noslips, emag).

**Comment by Nabski89** [comment]
Can we have a 60 TC version that also gives nuke-op gear?

OH LOOK MY CRATE HAS A MAULER!

**Comment by Iamgoofball** [comment]
That would be funny

**Review by Cyberboss — APPROVED** [review]

**Pull request merged**
