### PR TITLE
Moves medical laptop from inside the psych locker on Kilostation

### LINKED ISSUE #66253: Kilo psych has a floating medical laptop hidden under a locker
## Testmerges: 

#66123
#66220

## Reproduction:

-Move locker out of the way
-Suffer as you cannot put the locker back into place

Screenshot from ss13 webmap
image

### PR DESCRIPTION
**Pull request by Rhials**
## About The Pull Request

Moves the medical laptop on Kilostation from inside the psychologist's locker to a desk near the sofa area. No chair to use with it though -- Kilo is the budget station, and expenses need to be cut somewhere.

Had to move some stuff around a little to make space in maintenance and expanded the psych office by a teensy bit as a result. I'm not sure I'm happy with how the rearrangement of stuff turned out or if it looks good and will probably sleep on it, so please leave feedback/advice.

Before:

image

After:

image

## Why It's Good For The Game

Closes #66253

## Changelog

:cl:
fix: Kilostation psych office no longer has a stationary laptop crammed into it.
/:cl:

### CODE REVIEW

**Review by san7890 — DISMISSED** [review]
Few things:

image

This action figure was originally on the bookshelf... is putting it on the water cooler intentional? Just let me know.

image

Also, remove the "bot" turf decal if you aren't going to put something there. Alternatively, if you want to add something... you can go ahead.

image

While you're in the area, would you mind moving this vent out from under the table (preferably onto that tile)? Don't have to if you don't want to.

Otherwise, thank you for fixing this issue!

**Comment by Rhials** [comment]
Alright -- here's what it looks like now. The psych action figure on the water cooler wasn't intentional, I think I just had a late night brain fart.

image

Also, placed a rack and stethoscope on the bot decal.

**Review by san7890 — APPROVED** [review]
Thank you!

**Comment by Rhials** [comment]
jesus fucking christ what did I just do

**Comment by san7890** [comment]
It happens sometimes.

**Comment by notfrying1pans** [comment]
thanks? hope you get the weird git stuff sorted lol

**Comment by Rhials** [comment]
this really is the dark souls of making prs on the tgstation github

**Pull request closed without merging**
