### PR TITLE
Add undelivered departmental order crates and syndicate bombs to the shuttle cannot be sent message.

### PR DESCRIPTION
**Pull request by RandomGamer123**
## About The Pull Request
Makes it even more clearer that, you can't send the shuttle when either
a) A department has ordered crates and those need to be delivered (or more likely just moved off the shuttle), or
b) You accepted the bomb defusal shuttle loan and now have a bomb on the shuttle

## Changelog

:cl:
qol: The cargo shuttle cannot be sent message has been updated to remind people that you also cannot send the shuttle when there are undelivered departmental order crates or syndicate bombs on it.
/:cl:

### CODE REVIEW

**Comment by RangerIT** [comment]
I agree. This would add a small-but-good RP improvement. 
1- if a department orders something, you must accomplish the order
2- CentComm wont probably take a crate full of explosive and such.
So, yeah, this PR must definitly be merged

**Comment by RandomGamer123** [comment]
Oh as a clarification, these things are already banned from the shuttle, its just that the message you get doesn't include them, which I've seen has caused confusion at times, especially among non-cargo techs that try to send the shuttle.

**Comment by cacogen** [comment]
Imagine the INCENTIVE if you couldn't send the shuttle until all the departmental crates were delivered

**Comment by drIcepop** [comment]
> Imagine the INCENTIVE if you couldn't send the shuttle until all the departmental crates were delivered

so cargo techs would just tide into departments?

**Pull request merged**
