### PR TITLE
Removes exosuit repair droids

### PR DESCRIPTION
**Pull request by Metekillot**
## About The Pull Request

This PR removes repair droids for exosuits. The effect would be that mechs aren't able to spend power to repair themselves passively; the pilot or someone nearby has to serve a support role and repair the mech.
## Why It's Good For The Game

Sole mechs with massive power cells, immense amounts of weaponry, fantastic armor, and passive self repair are no fun to fight against or alongside of. The mech becomes the protagonist of any encounter, either as an enemy or an ally. This change makes it so that mechs require more support -- either by someone nearby, or the pilot themself -- to maintain effectiveness.
## Changelog
:cl: Bisar
del: Removed self-repair droid for mechs.
/:cl:

### CODE REVIEW

**Comment by uaioy** [comment]
strongest mech when matched against the weakest EMP/ion

**Comment by DaydreamIQ** [comment]
Very ided pr, I was literally in the round that this happened. They lost to a phazon as a Xeno and therefor -1

**Comment by Vect0r2** [comment]
Wait were they the uhh spider who was malding that a phazon boinked them in dchat?

**Comment by githubuser4141** [comment]
why even remove it totally instead of just lowering the amount a mech can hold, or limiting what type of mech can hold it. do you realise this fucks over Clarke/Ripleys that mine, having to exit a sealed mech (Clarke/Ripley mk2) and re-enter is about 10 seconds in itself, plus the welding time which is another 30 seconds, why just why

**Comment by projectkepler-ru** [comment]
What fucking mech can self repair

**Comment by san7890** [comment]
needs to compile first.

**Comment by Metekillot** [comment]
> needs to pass unit tests first.

@san7890  cat: ci_test/data/logs/ci/clean_run.lk: No such file or directory
Error: Process completed with exit code 1.

I'm not sure how to fix this one.

**Comment by Metekillot** [comment]
> strongest mech when matched against the weakest EMP/ion

The mech can withdraw and repair even as it continues staying functional with no down-time. This PR is meant to force them to take a few moments of downtime for healing in exchange for the immense power that mechs provide.


> Instead of removing, why don't you just restrict either the mech type or the amount of droids a mech can equip. Something tells me you don't play Mech Miners a lot, and you don't know the massive convenience even a single droid is for a mining clarke/ripley.
> 
> It takes a whopping 4 seconds to exit a clarke/ripley and another 4 seconds to re-enter, and any air you might've been enjoying is also voided (which is why it's vital to include a firesuit + oxy tank when mech mining) and replace with lavaland/icebox's air. Having even one droid means you don't have to do any of that.

I play miner a lot. But you make a good point. Perhaps making the repair droid a channeled ability that you need to sit still and spend time for would be fair for cases like this.


> What fucking mech can self repair

Uh, all of them.

**Comment by Metekillot** [comment]
> > Very ided pr, I was literally in the round that this happened. They lost to a phazon as a Xeno and therefor -1
> 
> I was the phazon pilot.
> 
>     1. I didn't even have a full loadout.
> 
>     2. I was unable to get out in most locations due to a freon flood (very uncommon, but it happened!)
> 
>     3. The self-repair wasn't as significant as several xenos choosing to take a fight with me in 0G in space while my mech had RCS.
> 
>     4. Because of the flood the mech wasn't fully equipped, and finally,
> 
>     5. I still had to spend a good amount of time charging even with a 40MJ battery!

I'm not basing this entire PR around one single round with a mech. Mechs become the center of attention in every single conflict they become a part of. Sure, fine, whatever (I guess?). Letting them passively heal throughout conflict and as they're meandering about is something that should be done away with. Mechs should require downtime to rest and repair.

**Comment by CRITAWAKETS** [comment]
> The mech can withdraw and repair even as it continues staying functional with no down-time. This PR is meant to force them to take a few moments of downtime for healing in exchange for the immense power that mechs provide.

You can actually repair active mechs. Someone can just stand behind and repair the mech, and yes it's as bullshit to fight against as it sounds. The healing rate from the repair droid is very very low, and this is uh, not low.

**Comment by githubuser4141** [comment]
> > strongest mech when matched against the weakest EMP/ion
> 
> The mech can withdraw and repair even as it continues staying functional with no down-time. This PR is meant to force them to take a few moments of downtime for healing in exchange for the immense power that mechs provide.
> 
> > Instead of removing, why don't you just restrict either the mech type or the amount of droids a mech can equip. Something tells me you don't play Mech Miners a lot, and you don't know the massive convenience even a single droid is for a mining clarke/ripley.
> > It takes a whopping 4 seconds to exit a clarke/ripley and another 4 seconds to re-enter, and any air you might've been enjoying is also voided (which is why it's vital to include a firesuit + oxy tank when mech mining) and replace with lavaland/icebox's air. Having even one droid means you don't have to do any of that.
> 
> I play miner a lot. But you make a good point. Perhaps making the repair droid a channeled ability that you need to sit still and spend time for would be fair for cases like this.
> 
> > What fucking mech can self repair
> 
> Uh, all of them.

I'm talking about mech mining, as someone who plays that almost every time I play it's a huge boon to have a repair droid or two on the mech, it's just a lot of time saving really and it gets you out of dodgy situations, like how fun is it to die to a single legion or goliath because you got outside, looked around, welded the mech (takes a LONG time btw) and got snuck up on? Having it require the mech to be stationary - why? The idea of mech mining is you don't have to stop, you just keep going, take damage? Turn a droid on, and keep going. Having to stand still is just wasting time.

**Comment by Metekillot** [comment]
You're making my point for me about how you don't need to stop and do any sort of maintenance on your hulking mech even if you take damage.

> > The mech can withdraw and repair even as it continues staying functional with no down-time. This PR is meant to force them to take a few moments of downtime for healing in exchange for the immense power that mechs provide.
> 
> You can actually repair active mechs. Someone can just stand behind and repair the mech, and yes it's as bullshit to fight against as it sounds. The healing rate from the repair droid is very very low, and this is uh, not low.

The healing rate from the repair droid is 0.5 per tick, or 1 per tick if you have 2. That would be about on par with omnizine. Having two would be, you know, twice that. As I've said before, the repair of a mech is something that should require downtime. Having passive healing like that should remain the realm of organics who are using reagents, and cyborgs who need consistent support from roboticists to install these parts in them.

**Comment by Metekillot** [comment]
> take damage? Turn a droid on, and keep going. Having to stand still is just wasting time.

Yes, that's my entire point. One of the most powerful combat options in the game shouldn't be able to just keep going without having to stand still for even a moment if it takes damage.

**Comment by Jackal-boop** [comment]
Mecha units are supposed to be the big bad fella in any encounter with them. It's why jt costs half a station just to build one of the sucker's. I am okay with increasing power draw for the auto repair though, and perhaps placing it with the combat mecha research instead of just adv mech research. Maybe swap it out with paddy?

**Comment by zoomachina** [comment]
> The healing rate from the repair droid is 0.5 per tick, or 1 per tick if you have 2. That would be double the rate of omnizine. As I've said before, the repair of a mech is something that should require downtime or outside assistance. Having passive healing should remain the realm of organics who are using reagents, and cyborgs who need consistent support from roboticists to install these parts in them.

so this droid's healing is less than that of one of the weakest healing chems? At least omnizine can heal 0.5 of multiple damage types, is this really your justification for removing this mech module?

**Comment by SimplySmiley123** [comment]
> > What fucking mech can self repair
> 
> Uh, all of them.

None of them can self repair without the repair droid, at all.

**Comment by DoomAngelBlade** [comment]
Make Droid usuable preferrably in non-combat / retreat situations, with a scale of repairs.

Repair Drone will not repair if damage taken during last 10 seconds.
Repair Drone repairs 0.5 health per tick, which increases up 1.5 per tick after 30 seconds of not taking damage.
Repair Drone repair rate increases up to 4x if stationary for 40 seconds(1x at 0 seconds, 2x at 20 seconds, 3x at 35, 4x at 40)
Repair Drone is disabled for 30 seconds if mech is damaged during repairing
Repair Drone can be toggled on and off at will.
Repair Drone activation / deactivation takes couple of seconds. When attacked during activation / deactivation, it is disabled for 30 seconds.
Repair Drone repairs up to 75% of mech health.

This will remove constant regen of 0.5, as you SEEK
Will not remove a module from game
Will add risk / reward mechanic for mech users
Will force them out of combat for repairs, as you SEEK.

That will be better than removing repair drone, imo..

**Comment by SimplySmiley123** [comment]
> You're making my point for me about how you don't need to stop and do any sort of maintenance on your hulking mech even if you take damage.
> 
> > > The mech can withdraw and repair even as it continues staying functional with no down-time. This PR is meant to force them to take a few moments of downtime for healing in exchange for the immense power that mechs provide.
> > 
> > 
> > You can actually repair active mechs. Someone can just stand behind and repair the mech, and yes it's as bullshit to fight against as it sounds. The healing rate from the repair droid is very very low, and this is uh, not low.
> 
> The healing rate from the repair droid is 0.5 per tick, or 1 per tick if you have 2. That would be double the rate of omnizine. As I've said before, the repair of a mech is something that should require downtime or outside assistance. Having passive healing should remain the realm of organics who are using reagents, and cyborgs who need consistent support from roboticists to install these parts in them.

The repair rate from it is, frankly, _pathetic_, you still end up having to get out of the engagement if you sustain too much damage, all the droid does is help deal with stray chip damage and mining.
It's not gonna save a mech on it's own, nor help much in saving the mech regardless of the situation. You'll still have downtime from real fights and will still get forced to get out and repair it yourself or require someone else to repair you. EMPs and Ion guns still own the everliving hell out of you.

Play around with mechs for a while and try to actually use them in combat yourself, this seems like peak Idead PR.

**Comment by zxaber** [comment]
I'll be honest, the self-repair drone is already so nerfed that I rarely bother with it. It's basically a wasted slot in almost every situation.

**Comment by EnterTheJake** [comment]
This won't solve the problem one bit.

Mechs are too strong because they can stack modules

Just make them unable to do so and they'll remain powerful without turning into complete nonsense.

**Comment by githubuser4141** [comment]
> > take damage? Turn a droid on, and keep going. Having to stand still is just wasting time.
> 
> Yes, that's my entire point. One of the most powerful combat options in the game shouldn't be able to just keep going without having to stand still for even a moment if it takes damage.

I'm talking about a ripley mk2/clarke ffs. To actually repair one manually is a possibly minute-long process of standing still. A person can inject chemicals with pen and continue to walk around and mine when they're healing. Most non-veterans already think mining mechs are underpowered, now you want to get rid of their quality of life features. If you want to just nerf the COMBAT functionality, then just do that.

**Comment by githubuser4141** [comment]
> I'll be honest, the self-repair drone is already so nerfed that I rarely bother with it. It's basically a wasted slot in almost every situation.
> 
> You could better justify it's removal as dead code.

This is actually not true because it doesn't use any slots. It uses UTILITY slots which for combat mechs are pointless: the other options are oxytank + RCS (only good if you're CERTAIN spacetravel/space combat will be a thing), radio (useless) or droids. So unless you're 100% certain you're gonna fight in space there's no reason to not just add 3 repair droids to your durand or gygax.

Air tank is otherwise a fairly poor choice as you can simply don a firesuit + oxy tank, close cabin and you're pretty much good forever.

**Comment by Exester509** [comment]
Why are people still trying to nerf one of the worst combat tools in the entire game

**Comment by moocowswag** [comment]
We should resprite the repair droid to being a blue cat on a book named yuumi and have it give the mech a temporary forcefield when triggered

**Comment by GuillaumePrata** [comment]
This passive healing is just too slow and boring on top of soft removing one of the fun sides of the mech gameplay looping, going out to repair your mech or have others assist you.

The only way the repair drones could be salvaged as a good feature IMO is if they were a "gun" and had "ammo" so you could deploy 1 drone to heal a big burst of health, and then have to field reload it.

Basically, we eat the cake and keep it too.

**Comment by SimplySmiley123** [comment]
> This passive healing is just too slow and boring on top of soft removing one of the fun sides of the mech gameplay looping, going out to repair your mech or have others assist you.
> 
> The only way the repair drones could be salvaged as a good feature IMO is if they were a "gun" and had "ammo" so you could deploy 1 drone to heal a big burst of health, and then have to field reload it.
> 
> Basically, we eat the cake and keep it too.

The only thing repair droids do are heal up chip damage that would be annoying to repair after every single time you get mildly damaged.

**Comment by githubuser4141** [comment]
> This passive healing is just too slow and boring on top of soft removing one of the fun sides of the mech gameplay looping, going out to repair your mech or have others assist you.
> 
> The only way the repair drones could be salvaged as a good feature IMO is if they were a "gun" and had "ammo" so you could deploy 1 drone to heal a big burst of health, and then have to field reload it.
> 
> Basically, we eat the cake and keep it too.

It's a quality of life tool when mining and perhaps when fighting in combat mechs. Mech mining is supposed to be fast, furious and full of convenience you shouldn't have to go outside and do anything because that negates the whole point of mech mining which is complaining the miners aren't mining (with their hands) while you mine by sitting in a chair and pressing buttons. Which is what a mech is, you sit down, push buttons and complain

**Comment by Admiral-Gigaton** [comment]
Worst PR of the year by far, maintainers rip this man's gbp from their grasp and send them back to -1 gajillion Gbp for their crimes

Also, mech wounds can't be healed by them, the drones heal slower than old people fuck, and this is still an ided pr

Maybe, I dunno, make it cost more power? Take up the power slot (too?)

**Comment by Metekillot** [comment]
> Also, mech wounds can't be healed by them

They can actually 



They will damage you if you use them while short circuiting but you can... Just turn it off and repair the short circuit before reactivating

**Comment by Jackal-boop** [comment]
You could just increase the energy use of the repair Droid and move it up the research tree

**Comment by Stoopler** [comment]
idedplsuncode.  saying someone can exit to repair and then get back in is moot when you have to also consider that posimechs are a thing, and those helpless little cubes can't exit to repair their mech.

**Comment by Jacquerel** [comment]
I'm not really interested in this change and it doesn't seem like anyone else is either.

**Pull request closed without merging**
