### PR TITLE
Overlay/Roundstart fixpack

### LINKED ISSUE #24359: Roundstart crew does not appear on the crew manifest
Roundstart crew does not appear on the crew manifest and has no records, security or medical.

### PR DESCRIPTION
**Pull request by Cyberboss**
\> Invisible characters
\> Empty datacore
REEEE
Fixes #24359 

:cl: Cyberboss
fix: The graphical delays with characters at roundstart are gone
fix: The crew manifest is working again
/:cl:

### CODE REVIEW

**Comment by AnturK** [comment]
Aah mixing new features with fixes.

**Comment by Cyberboss** [comment]
There's no feature?

**Comment by AnturK** [comment]
Please, photo defer is new.

**Comment by Cyberboss** [comment]
It is the needful to fix the bug

**Comment by Cyberboss** [comment]
Actually, it's not, I made it simple

**Pull request merged**
