### PR TITLE
Add the message argument to can_speak in the cult runes speaking check so that cultists are able to be played again. This is a small bugfix I coded on the 19/01 to fix issue #7172 as reported by tkdrg

### LINKED ISSUE #7172: Nobody can use runes
Cult is completely broken now.
This happened due to #7165 (coded by @optimumtact and merged by @miauw62), which used can_speak() with no argument (it's supposed to be a string), meaning that it always returns 0.

### PR DESCRIPTION
**Pull request by optimumtact**
It is needed for _raisans_

Fixes #7172

### CODE REVIEW

**Comment by vista-** [comment]
More descriptive title, please.

**Comment by optimumtact** [comment]
There, nice and descriptive

**Comment by ike709** [comment]
This needs to be merged fairly quickly so runes work again

**Comment by tkdrg** [comment]
Speedymerge cause cult is 100% borked

**Comment by vista-** [comment]
Get Sosjerky to update ASAP.

**Comment by optimumtact** [comment]
But nobody likes cult anyway

**Comment by as334** [comment]
...I like cult

**Pull request merged**
