### PR TITLE
Replaces the Singularity Engine on Dreamstation with a Tesla Engine

### PR DESCRIPTION
**Pull request by ChangelingRain**
Yup, a tesla engine.
oh god yes

### CODE REVIEW

**Comment by Anonus** [comment]
Bonus; some airlocks are now glass versions, and the cameras in the containment chamber are properly `ctag`ed

**Comment by Iamgoofball** [comment]
merge this ASAP btw

**Comment by MrStonedOne** [comment]
This does not need to be merged asap.

It doesn't matter how long its in PR form, it can only conflict if another PR edits the same parts of the same file and is merged before this one.

This would only need to be merged before that pr.

Quick overreacting goof

**Comment by Iamgoofball** [comment]
no @MrStonedOne this would have been in the tesla engine PR itself if map files didn't cause unresolvable conflicts at the slightest breath

**Comment by MrStonedOne** [comment]
Not every map change needs to be merged asap.

What you are basically saying, is you would rather cause conflicts for other people, then wait in line and solve your own conflicts.

and hell, this isn't even your PR

**Comment by Anonus** [comment]
I did this one myself because the singularity is too dangerous for dreamstation and I can't trust goofball to map it right.

**Comment by Anonus** [comment]
And I'm rather glad I did this myself because goof is causing boatloads of drama.

**Comment by tkdrg** [comment]
Sure whatever who cares about dream anyway

**Comment by Man-Shroom-** [comment]
damnit i was gonna ask if the space tiles could be replaced with floor tiles since there is no point in the tesla engine being an 'outside' engine (like singulo or solars) and not an 'inside' engine (like TEG or supermatter)

**Comment by Anonus** [comment]
It looks cooler if it's space, which is why it's set up like that.

**Comment by Man-Shroom-** [comment]
how am i supposed to throw people into it tho or stand around eating popcorn watching it

**Pull request merged**
