### PR TITLE
Brings back clowncars to the price they originally were

### PR DESCRIPTION
**Pull request by ghost**
:cl: Floyd
 tweak: Clown cars are now 15 tc again
/:cl:

this change was dumb and its not hard to counter clown cars anyway. They're in no way worth as much as they are now

### CODE REVIEW

**Comment by SynnGraffkin** [comment]
He has a point, just lay down and clown cars can't suck you up. Also a decent AI could probably catch one with firelocks.

**Comment by carshalash** [comment]
You'd be surprised how often retards open up firelocks in the main hallway during clown car lock ins.

**Comment by Detective-Google** [comment]
People have an annoying habit of cycling the firelocks to get through somewhere even if theyre down for a fuckin reason

Even though it takes -0 seconds to find a crowbar instead

**Comment by Ziiro** [comment]
An AI can fucking wreck a clown car in two stupid ways: Turning off gravity and shocking doors (if you run into a shocked door, it shocks the driver). Definitely not a 20TC item anymore.

**Comment by Qustinnus** [comment]
ill fix the shocking doors thing later

**Comment by Shadowflame909** [comment]
Make it 13 tc gamer it's still too weak

**Comment by optimumtact** [comment]
This was done for good reason

**Pull request closed without merging**
