### PR TITLE
Fixes infinite grilled naming bug

### PR DESCRIPTION
**Pull request by ShizCalev**
fixes
image

## Changelog
:cl: ShizCalev
fix: Food can no longer be grilled repeatedly to the point of breaking their name with an endless string.
/:cl:

### CODE REVIEW

**Comment by PKPenguin321** [comment]
It's been grilled. It's been grilled. It's been grilled. It's been grilled. It's been grilled. It's been grilled. It's been grilled. It's been grilled. It's been lightly grilled. It's been lightly grilled. It's been lightly grilled. It's been grilled. It's been grilled. It's been grilled.

**Comment by ArcaneDefence** [comment]
pizza
Forbidden knowledge cookery will only ever evolve.
Custom foods are a sin

**Comment by MrDoomBringer** [comment]
image

**Comment by trollbreeder** [comment]
I need to know the double grill technique

**Comment by TiviPlus** [comment]
o7

**Pull request merged**
