### PR TITLE
Removes 1-shot Stamstuns From Shotgun Ammos

### PR DESCRIPTION
**Pull request by Tlaltecuhtli**
:cl:
balance: rubbershot does 66 stamina  + 18 damage instead of 150 stamina + 18 damage
balance: beanbang does 55 stamina + 5 damge instead of 80 + 5 damage
/:cl:
rubber no longer 1 shot crit from <3 tiles
rubber needs 2 shots on fully healthy man to knock them down

rubber gg no re shot from grog tide is bad gameplay

### CODE REVIEW

**Comment by ATH1909** [comment]
Now even more bartenders and sec officers are going to load lethals into their shotguns instead of rubbershot, resulting in even more needless deaths/crittings. Is this what you want?

**Comment by Nickkoranda** [comment]
sec can use disablers anyway. bartender uses his shottie to defend himself, not validhunt. in any case this is still 66 stam damage point-blank instead of being 150

**Comment by Teepeepee** [comment]
why are you standing within one tile of a shotgun and complaining about gettinfñg stunned, it's the same as a stunbaton

**Comment by ExcessiveUseOfCobblestone** [comment]
I stunned

What's the issue here?

**Comment by ExcessiveUseOfCobblestone** [comment]
update OP with `why it's important for the game?`

**Comment by knacker48** [comment]
Your telling me you can take a point blank shotgun blast and stay standing?

**Comment by anconfuzedrock** [comment]
warden niggas be like "hey hos can you open the lethal injections locker so I can make some shotgun darts if you don't have time to open it that's ok I'll just laser it open depending on the map I have access anyways"

**Comment by HomocidlePancakes** [comment]
:joy: :ok: HE DIED :eyes: TO RUBBER SHOT :fire: :cat: :clap:

**Comment by FloranOtten** [comment]
So why use a rubber loaded shotgun? Disablers do the job better now. A Bartender can't shottie you out anymore. Why even have these guns if they're weaker than just making a stunprod?

**Comment by Tlaltecuhtli** [comment]
@knacker48 neither being hit by buckshot ammo one shots you  from range and thats good for balance

@teepeepee yeah cause stunbaton does 150 stamina + 18 brute within 5 tiles around you, thanks for the comment eggplant juice drinker 

 im gonna stop respond to redditors without contributor tags cause they arent real

**Comment by KrabSpider** [comment]
So why use rubbershot at all when beanbag slugs are a lot more reliable with that 80 no dropoff stamina damage?

**Comment by Tlaltecuhtli** [comment]
i ll change em too dont worry

**Comment by Nickkoranda** [comment]
>dae rubbershot bad???

no, you just need to click more than once to stun somebody now

**Comment by davethwave** [comment]
But why nerf the beanbag shells? A 2 shot weapon with expendable bullets seem fair since despite needing 3 shots from a disabler. For a disabler you can just charge it and has 20 something shots while a shotgun has a limited amount of which you can carry and each shot is slow to make and don't forget the reload time as well. at most you can carry about 14 extra shells with the belt slot and such and takes a large amount of time to create said shells as well(perspective wise at least). Also I don't seem to remember hearing any big complaints about the beanbag or rubber shots for my time of play in tg.(about 2017-now) So tell why it's necessary to nerf it.

**Comment by Tlaltecuhtli** [comment]
because it insta stuns within 3 tiles with 100+ stamina damage overshadowing even the lethal version  of itself. it has always been a broken ammo type but it was fine when other cheaper insta stun solutions existed and now it sticks out of the game balance

**Comment by Tlaltecuhtli** [comment]
because it insta stuns within 3 tiles with 100+ stamina damage overshadowing even the lethal version  of itself. it has always been a broken ammo type but it was fine when other cheaper insta stun solutions existed and now it sticks out of the game balance

**Comment by davethwave** [comment]
Talking about the beanbag slug more than the rubber shot. Understand why you nerfed that, just think beanbag slugs are in a right place right now.

**Comment by ExcessiveUseOfCobblestone** [comment]
> 1 shot stamstun PR
>> nerfs a bullet type that doesn't 1 shot stam stun

nani

**Comment by Tlaltecuhtli** [comment]
consistence

**Comment by OverlyGeneric** [comment]
bruh, how you die to a shotgun. just stunbaton that fool while on morphine. :moyai:

**Comment by Barhandar** [comment]
Idedplsnerf

Literally more useful to load beanbags with this PR because both are two-click stuns but beanbags don't need you to be in their face and don't lag the game (and if you want lag, you'll load real buckshot anyway).

**Comment by Tlaltecuhtli** [comment]
then why do you use buckshots over slugs? oh right cause one does 50% more when close

**Comment by subject217** [comment]
i'm not doing myself any favors here but tlal has the right idea.

rubbershot is one of the most powerful things in the game currently, moreso than it has a real right to, being the common choice for improv shotguns and riot shotguns and available in autolathes. notorious gamer scuff gerald could school you about it.

beanbags have to be nerfed to keep them from being objectively superior to rubbershot with this change.

**Comment by anconfuzedrock** [comment]
guess I'll just switch to shotgun darts full of lethal chems then, goofchem makes that extremely easy to do so

**Comment by ExcessiveUseOfCobblestone** [comment]
So post this change the idea is for rubber to, at best, do what buckshot does with more actual damage?

**Comment by Tlaltecuhtli** [comment]
yep, you use rubber to not lethally take people down and buckshots for lethal

**Comment by ExcessiveUseOfCobblestone** [comment]
I thought slug was 1 bullet (5damage/55stam) and pellets were multiple (3x num/11 x num)

**Comment by Tlaltecuhtli** [comment]
well stamina regen exist so i slighty added some value

**Comment by Tlaltecuhtli** [comment]
what

**Comment by necromanceranne** [comment]
Beanbags genuinely don't work right now because of the way stamina damage is applied and bullet deviation into limbs. Which means even hitting them twice does not cause someone to flop. You can hardly slow them down. At that point, you might as well give the bartender the new rubbershot since even if technically they still drop people in two shots, it won't.

That said I have been abusing rubbershot a lot. You can validhunt literally everything with it in a improvised shotgun, since one shot is all you need unless they had hefty bullet armor. Even then, they're in a bad way and unlikely to be able to fight back.

**Comment by ExcessiveUseOfCobblestone** [comment]
> what

Slug - 1 bullet with a lot of power
Pellets - Many bullets with a bit of power

am I wrong???

**Comment by Tlaltecuhtli** [comment]
well in game reasoning:
slug (60 damage): long range medium damage
buckshot: higher damage when close almost nothing when far

beanbang ( 5 + 55 stam): long range 
rubber: close range => higher damage

**Comment by Tlaltecuhtli** [comment]
if you hit the same limb twice with beanbang it wont work (same for anything as damage is capped ) but limb + anywhere else will stun

**Comment by subject217** [comment]
Remove limb stamina dmg btw

**Comment by Tlaltecuhtli** [comment]
@necromanceranne i now read ur message fully instead of the first 5 words so i ll say that you can use bean bag aiming legs intentionally to cause a limb crit 100% at rnage
i may look again at the damage and test it to see if it actually does that with 55 +5

**Comment by Swiftkor** [comment]
I mean, warden typically only gives out shotguns when some antag stuff is going on, so it's not like sec mains are going to walk around with a shotgun roundstart to oneshot tiders (At least I hope wardens will be smart enough not to do this). Sec is just going to use lethals instead, taking people out of the round instead of getting the chance to actually process them. 

I don't like the idea of tasers are nerfed so now rubber slugs are best nonlethal so nerf those, looks like sec are only using lethal slugs so we gotta nerf those now.

**Comment by ExcessiveUseOfCobblestone** [comment]
um... they still have disablers anon.

**Comment by ExcessiveUseOfCobblestone** [comment]
Is the issue genuinely the ammotype or is it the assistant shotgun?

If it's the ammotype I don't mind seeing this merged, if it's the shotgun I'd rather nip that instead of dancing around otherwise sane ammo's.

**Comment by necromanceranne** [comment]
Rubbershot in improvised shotguns is pretty powerful. But at its core the problem is with the ammo and not the gun. Any other ammo type is pretty balanced by the fact that it has one shot.

Combat shotguns and riot shotguns are better with rubbershot due to being able to floor a whole room with ease. One click victories (per person) are very possible at the moment with rubber shot because of the overkill on the stamina damage.

**Comment by ExcessiveUseOfCobblestone** [comment]
@necromanceranne if this was your PR would you change anything?

**Comment by necromanceranne** [comment]
Honestly the change is healthy. But it is symptomatic of the problems with stamina damage as a mechanic. Especially with regards to beanbags, which have been somewhat lackluster since the stamina rework due to how stamina works with limbs. And stamina crit, which under normal circumstances slower to apply from most sources, but there are edge cases like rubbershot and dual-wielded DRAGnet that make it worse than tasers. But that is a problem that must be solved outside the scope of this PR (or is only partially solved), and this a good step in the right direction for the current state of the game. I actually support it.

**Pull request merged**
