### PR TITLE
Fixes syndicate crates using wrong lock icons, plus minor tweaks

### PR DESCRIPTION
**Pull request by DaCoolBoss**
## About The Pull Request
 - Donk Co. crate previously was unlocked, but the sprite had a lock on it. Now the lock is removed.
 - There's a new secure Donk Co. crate using the old sprite. 
 - S.E.L.F.'s crate had no lock on it, but it was a secure crate. The lock overlay was present and it didn't look good. Now the lock is fully on the sprite.
 - There's a new unsecured S.E.L.F. crate using the old sprite. I gave it a new description since the description mentioned locks.
 - Interdyne's freezer was unlocked but had a lock on the sprite. Now the freezer is secure. No unsecure variant this time.
 - The names of the crates now use proper nouns, and the names of corporations are capitalised.
 - All syndicate crates with a lock now require syndicate access by default.
 - The Interdyne blood freezer no longer spawns the same contents as a normal blood crate (a list of 9 blood packs plus 1-3 extra random packs), now it spawns 13 random packs of blood.
 - Typepaths were moved around to make the crates easier to find in mapping tools.
 - Fixed a dang TYPO in the Donk Co. fridge's description.
## Why It's Good For The Game
Lock issue is solved now. The mismatching sprites didn't look good, and now they match and look good.

Kept sprites for lockable Donk crate and lockless SELF crates and made them their own crate types.

Repathed stuff to make it tidier. As a side effect the interdyne blood crate is no longer a subtype of the regular blood crate, so instead of copy+pasting the long list of contents it used to have it just has a bunch of random bloods in it. Feels more on-flavour this way I think.

Access changes are because that makes sense for syndicate crates. Most of these are going to end up mapped in as syndicate-access crates, makes sense to make that the default. Can always be overwritten.

yea and I fixed that fuckin typo
## Changelog
:cl:
fix: Donk Co. and S.E.L.F. crates now properly display their lock (or lack therof).
image: New sprites for unlocked Donk Co. crates and locked S.E.L.F. crates.
spellcheck: The names of syndicate-branded crates now use proper nouns.
spellcheck: Fixed a typo in the description for Donk Co. fridges.
/:cl:

### CODE REVIEW

**Comment by Ghommie** [comment]
d

**Comment by YesterdaysPromise** [comment]
hi, I made them crates. I figured I'd rather have a lock that can be functional or not, than don't have one at all.

**Review by Wallemations — APPROVED** [review]

**Comment by Wallemations** [comment]
Fix the failed checks first obviously

**Comment by DaCoolBoss** [comment]
Finally got round to finishing this. Sorry for the wait.

I noticed there's a variable for the volume of the sound when opening and closing the crates, so I made the MI13 crate noticably quieter. Going to sneak that in if you don't mind, I find it a little bit funny.

**Pull request merged**
