### PR TITLE
Makes the conversion jobban replacement use the new antag flags

### PR DESCRIPTION
**Pull request by Shadowlight213**
Also adds replacement for thralls.

### CODE REVIEW

**Comment by duncathan** [comment]
:+1: I was gonna do this as soon as I got home

**Comment by KorPhaeron** [comment]
Respecting prefs got lost in the merge conflict/tag change shuffle as well, could you please re-add them?

**Comment by Shadowlight213** [comment]
DNM for now, because the jobbans use completely different strings from prefs.

**Comment by Shadowlight213** [comment]
Actually nevermind. This should actually work.

**Comment by Shadowlight213** [comment]
@RemieRichards @Jordie0608 @phil235 @Razharas Ready for review/merge.

**Pull request merged**
