### PR TITLE
Makes Delta Station EVA Toolbelt Actually A Toolbelt And Also The Ashwalker Ruin and Also Makes It More Obvious That The Base Type Of Belt Is Not A Toolbelt

### PR DESCRIPTION
**Pull request by Jackraxxus**
## About The Pull Request

In this PR I replace the simple "belt" in Delta's EVA with the /utility (toolbelt) subtype, as well as the ashwalker nest, and also updates the name and description of the base belt to make it clearer that its purpose is purely as a base type, and not as a usable item. A case where the base type is also an item that can be intentionally used in game is the police baton.

## Why It's Good For The Game

The current belt can hold basically everything and assistants should not be given an operative belt at roundstart.*
Also makes it easier to tell the difference between a "belt" and a toolbelt" when they both look the same.

## Changelog

:cl:
fix: Deltastation's EVA now contains a real toolbelt, that can only hold tools.
fix: The Ashwalker Nest now contains a real toolbelt, that can only hold tools.
spellcheck: The base type of /belt is now more obviously NOT a toolbelt.
/:cl:

*I don't have any evidence that this is the case.

### CODE REVIEW

**Comment by msgerbs** [comment]
lavaland_surface_ash_walker1.dmm also has one of these which is (probably?) not intentional as it just looks like a toolbelt and can't be obtained any other way. If it is indeed the cast that the base type should not be obtainable, you may want to remove it from that map as well and probably change the name/description to make it more obvious it isn't supposed to exist like some other base types do.

**Comment by ATH1909** [comment]
ash walker nerf smh my head my head

**Comment by msgerbs** [comment]
I did some digging, the only exact equivalent is `/obj/item/storage/belt/military` AKA the chest rig and `/obj/item/storage/belt/military/army` AKA army belt. Those are both 7 unrestricted slots, but the army belt is literally never used anywhere and would be a bit out of place. There's also /obj/item/storage/belt/military/assault which is 6 slots but can be randomly found in maint and spawns with battlecruiser crew, meaning if we want to stick with a belt this is likely the best. Otherwise, giving them a chest rig isn't entirely out of place given that, as mentioned, they have a syndicate toolbox so they could've taken both from some syndie.

Personally I'd just make it a regular toolbelt since I doubt the person who mapped it in realized what they had given them, and I doubt most players realize either. But if we insist on being held to maintain the balance of what seems an obvious mistake, I say go with the chest rig.

**Comment by Jackraxxus** [comment]
I think it's intended to be a toolbelt tbh. If the original author had intended to give them a military or assault belt equivalent they would've given them a military or assault belt, not the simple "belt" that looks like a toolbelt.

**Comment by msgerbs** [comment]
Works for me. (don't forgot to update your changelog though!)

**Comment by Ryusenshu** [comment]
If there is a need to change that then i would recommend the hunters belt , its already tribal themed and fits well in there.
Also currently uncraftable and can only be found on legion corpses as far as i know.

**Comment by Jackraxxus** [comment]
Switching the ash walker's belt to a hunting belt is probably a good idea, but it seems out of scope of this fix PR imo. I don't think it was the author's intention, so it'd probably slide into the dark realm of b*lance.

**Pull request merged**
