### PR TITLE
Service Protolathe Tweaks, Paint Cleaner and Trashbags in Protolathe

### PR DESCRIPTION
**Pull request by Owai-Seek**
## About The Pull Request

Moves Light Replacer to Equipment Tab
Adds Trash Bag as a printable item (Plastic, Service Lathe)
Adds Paint Remover as printable item (Needs Advanced Sanitation)
Fix: Allows you to print broom in Service Lathe

## Why It's Good For The Game

Tiny Fix and QoL improvement for janitors. You can now get all of the items you (generally) need from advanced sanitation in a single tab. In addition to that, it gives a janitor who's lost his paint cleaner a way to get more. You can now get it by asking a chemist for help, -or- from the cargo order.

zrVizeFyXR
5ALMYoyexQ
dreamseeker_n7LtSVwsD8

## Changelog
:cl:
add: Garbage Bags and Paint Remover now available in service protolathe.
tweak: Light Replacer is now in "Equipment" tab of service protolathe.
fix: Push Broom can be printed at Service Lathe
/:cl:

### CODE REVIEW

**Comment by Farquaar** [comment]
Good stuff.

**Comment by spookydonut** [comment]
@Owai-Seek rebase/merge commit for working CI

**Comment by Ratvar** [comment]
I am not very sure about super toolbelt being printable

**Comment by Owai-Seek** [comment]
From what I can tell you can already find trashbags in maintenance (via trash bins), buy them from cargo, or wait/request trashbags of holding,  the "bad" version being printable doesn't seem all that bad to me.

**Review by kriskog — APPROVED** [review]
They arent super toolbelts anymore though, since you cant wear them anymore.

**Pull request merged**
