### PR TITLE
Cryo Cell changes color depending on temperature

### PR DESCRIPTION
**Pull request by T-for-Tea**
## About The Pull Request
Depending on temperature of the gas mix, the Cryo Cell will change its colors from the regular icy blue to a vibrant fiery orange
## Why It's Good For The Game
Currently there is almost zero visual indication whether the Cryo Cell is running hot or cold. Thermomachine's tiny indicator is telling, but it is usually not noticable. This change will make it very apparent that someone has changed the temperature (and has likely added pyroxadone to the mix) Normally this would require the Medbay to get some slime jelly, I'm hoping this visual change will help foster more cooperation between xenobio and medbay. When your involvement is clearly visible, it comes with recognition from your fellow crew members. Being helpful is nice, but being recognized for it is better.

**Currently it will change color if it is above 460K,** i picked this temperature due to the fact that it is the optimum temperature for pyroxadone.
**Also, I've noticed a bug, when you remove the beaker from the Cryo Cell, it just disappears. At first i thought this was my bad, but i checked my master, and just to be sure downloaded a fresh clone and tested it there too. It doesnt appear to be related to my changes. Since this is my first PR i wanted to make sure i did not break anything, if anyone else can verify it that would be appreciated.**

I dont usually do any coding, so i tried to keep everything as clean as I possibly can, if you notice any issues/redundancy I would appreciate the feedback.

here be some videos showing how it all looks and works:

https://github.com/tgstation/tgstation/assets/124678540/c33398d6-5625-42e7-a6ef-94411654b843

https://github.com/tgstation/tgstation/assets/124678540/39a2bf91-bc07-4312-a654-d9fa11203376

https://github.com/tgstation/tgstation/assets/124678540/94198dde-dc3b-4c21-aa1e-7240022a4029

https://github.com/tgstation/tgstation/assets/124678540/cc4ca1b4-13fe-446b-ba43-b1bccdfb2dd2

## Changelog
:cl:Loon_Cheser
add: Cryo Cell now checks for temperature, and updates its sprites if it is above 460K
add: Cryogenics.dmi updated to include hot versions of sprites

/:cl:

### CODE REVIEW

**Comment by LemonInTheDark** [comment]
what happen? it'd be cool to do this with a greyscaled object so you could transition, but this seems like a fine idea why'd you kill it?

**Comment by T-for-Tea** [comment]
I will PR it again when i can fix it, it seems i used a variable that causes a problem when the Cryo cell is destroyed, the tests didnt go very well :)

**Comment by LemonInTheDark** [comment]
if you want to just push the fix commits to this branch and then reopen that'd be fine. don't need to close a pr if tests fail or anything, tho if you're busy and won't be able to attend to it for a while then I understand

**Comment by T-for-Tea** [comment]
> what happen? it'd be cool to do this with a greyscaled object so you could transition, but this seems like a fine idea why'd you kill it?

so, i might actually try this instead, can you please give me any pointers, like a piece of code where i can inspect a similar effect (greyscale sprite changes color according to a condition)? 

how I plan to go about it if i can figure out the code, is to remove the glass tube from the stationary sprites (pod-on, pod-off etc) and instead use overlays and underlays. so it will basically be a "pedestal" and an underlay beneath it, and an overlay above them all i will tint only the overlay and underlay sprites - saving a lot of time .not sure if it will work but sounds good to my untrained self :D

**Comment by LemonInTheDark** [comment]
Best place to ask this stuff is the coding channel of tgcord, should be a link in the main readme
What you're thinking is sane, yes that's what I'd do too 

You can run unit tests by uncommenting the UNIT_TEST define in _compile_options.dm. You likely don't really need to tho, it is perfectly fine to just push commits to your branch and see if that passes or not.
Uhhhhhhhhh sus

**Pull request closed without merging**
