### PR TITLE
Revert "Makes supermatter dusting independent of the reference frame."

### PR DESCRIPTION
**Pull request by Fikou**
Reverts tgstation/tgstation#66395
Can we not have supermatter launching murderbones? This was merged with 0 comment or discussion from the maintainer, with a literal 1 word "Why it's good for the game section". The PR was opened literally like 3 minutes after a discord discussion on why doing that would be a fucking bad idea

:cl:
balance:  The supermatter running into you is no longer just as deadly as you running into the supermatter.
/:cl:

### CODE REVIEW

**Comment by zxaber** [comment]
Make it deal flat brute damage as you get smacked by the iron base instead

**Review by tralezab — APPROVED** [review]
image

Maddening, isn't it

**Comment by LemonInTheDark** [comment]
Don't let the things throw the supermatter.
It makes sense for it to dust on throw, it just shouldn't be throwable.

**Review by LemonInTheDark — CHANGES_REQUESTED** [review]
Damn you arm

**Comment by funman816** [comment]
wouldnt this kinda remove the power of the supermatter, since everyone already knows it the greatest power to fucking kill you. I'd suggest maybe adding a shield around the SM or something, that deals brute, but if hit too much it breaks and dusts things.

**Comment by tralezab** [comment]
> Damn you arm

honestly after talking with you on discord it does make sense to make player sources have a catastrophic fail condition

**Comment by Fikou** [comment]
> wouldnt this kinda remove the power of the supermatter, since everyone already knows it the greatest power to fucking kill you. I'd suggest maybe adding a shield around the SM or something, that deals brute, but if hit too much it breaks and dusts things.

what are you talking about this was added literally 5 hours ago

**Comment by MrDoomBringer** [comment]
huh why is this closed

**Comment by Fikou** [comment]
> huh why is this closed

i dont want to hardcode supermatter checks to 20 different things and the maintainers want that

**Comment by MrDoomBringer** [comment]
image

**Comment by optimumtact** [comment]
Fix the conflict.

**Comment by LemonInTheDark** [comment]
still think this is a bad idea

**Comment by optimumtact** [comment]
I don't agree the original PR should ever have been merged in the first place, so I'm ok wiht a revert.

if someone wants to rebalance the SM later around the kinesis module or whatever, then sure go ahead.

**Pull request merged**
