### PR TITLE
Fixes being able to stand on chasms

### LINKED ISSUE #26955: People with wings can land on chasm turfs without falling down
1. Get wings somehow.
2. Start flying and move on top of a chasm turf.
3. Stop flying.
4. Notice that you are now standing on top of a chasm turf without falling down.

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
With both wings and flight suits.

Fixes #26955

### CODE REVIEW

**Comment by ChangelingRain** [comment]
A more general fix would to just have chasms process constantly, because I'm pretty sure there's one or more edge cases this won't catch.

**Comment by KorPhaeron** [comment]
I'd rather have dumb edge cases of "haha I can stand on a chasm" than a punch of turfs processing needlessly forever

**Comment by Tokiko1** [comment]
Why not put the turf.Entered in the toggleflight proc in angel.dm?

**Comment by KorPhaeron** [comment]
I think toggleflight just calls closewings anyway

**Comment by Tokiko1** [comment]
Doesn't that slip people who emote flapping on a wet floor? Might be considered a feature, but seems odd to put the call in here instead of the proc where all the flying related flags are handled. Or maybe I'm completely wrong, I don't even know coding.

**Comment by lzimann** [comment]
Don't think it will matter that much, but yea, it really should be where the flight flag is handled to prevent any potential issue.

**Comment by RemieRichards** [comment]
@ChangelingRain Absolutely not.
This is the better fix.

**Comment by duncathan** [comment]
She's correct to call it more general but it's certainly far from ideal

**Comment by RemieRichards** [comment]
You should never poll when you can react.

**Comment by duncathan** [comment]
especially with something like turfs where there can be a heckton of them

**Comment by RemieRichards** [comment]
quite.

**Comment by FantasticFwoosh** [comment]
Why not have it gravity based, if you were floating in gravity or flying you wouldn't be able to fall into the chasm anyway.

**Comment by octareenroon91** [comment]
Downdrafts

**Comment by FantasticFwoosh** [comment]
The only way to barely ever get that reasoning to work is that the ash storm on-purposefully grounds you due to high winds. We have a lot of screwy turfs that depend on people actively entering or standing on the tile, if you could just float/fly over lava or a chasm its not so much of a issue.

**Comment by KorPhaeron** [comment]
@Tokiko1 

Good point

**Comment by RemieRichards** [comment]
@KorPhaeron Don't change that.
Think about it.
If your bullshit jetpack turns off, or you fold your wings, and put your feet on the floor, not shit you're going to slip on water/peels!

**Comment by KorPhaeron** [comment]
Does opening your wings cause you to fly always? I thought tokiko meant you could flap them without flying

**Comment by RemieRichards** [comment]
p.sure you always fly (assuming you have wings and aren't just a normal human aflapping)

**Comment by lzimann** [comment]
Having wings doesn't mean you always fly. And the *flap emote opens and closes your wings without changing you fly state(99% sure on this)

**Pull request merged**
