### PR TITLE
Space Ruin - Mech Transport Ship redux

### PR DESCRIPTION
**Pull request by Zergspower**
## About The Pull Request

After coming across it in space again i felt it sorta clashed with the other ruins visually a _bit_ too hard, this keeps the same theme without really any major redesign but makes it a little more... realistic?

Given it's a mech transport i added in bays for charging and shackling them down, i moved the loot into a secure closet as the ship gives a more apt appearance of being raided by pirates with the pilot being executed among other things. The cockpit would be raised in the case of being a transport so it could oversee everything moving out below, which is why stairs are there now.

image

## Why It's Good For The Game

Better interpretation of what a mech transport would look like and of course exploded partially.

## Changelog
:cl:
qol: Space Ruine Mechtransport - more modern redesign
/:cl:

### CODE REVIEW

**Review by Maurukas — CHANGES_REQUESTED** [review]
You have active turfs. It looks like you are using some turfs that do not have airless variants:
image

You can check for active turfs via Debug Tab->Mapping Verbs - Enable which will give you the mapping tab.

**Comment by Zergspower** [comment]
oh shit i had to emergency travel for something and forgot i had this open

**Comment by Zergspower** [comment]
> You have active turfs. It looks like you are using some turfs that do not have airless variants: image
> 
> You can check for active turfs via Debug Tab->Mapping Verbs - Enable which will give you the mapping tab.

better to swap to airless or make new variants?

**Comment by Maurukas** [comment]
> better to swap to airless or make new variants?

Whichever you prefer. Both are acceptable solutions. Swapping is probably easier, but won't retain the look.

**Comment by Zergspower** [comment]
alright i made them all airless tiles and pushed it - dealin with a sync issue with git across all my builds for some reason though so will push when that's cleared

**Review by Maurukas — APPROVED** [review]

**Pull request merged**
