### PR TITLE
Refactors add_fingerprint to be called mainly by clickcode

### PR DESCRIPTION
**Pull request by Cyberboss**
Also suicide_act and inventory shit

I held off on Topic because Topic is terrible

### CODE REVIEW

**Comment by MrPerson** [comment]
Why does attack_self() need a wrapper to add fingerprints? Why not just add fingerprints in the base attack_self()?

**Comment by Cyberboss** [comment]
>Expecting coders to call the base

**Comment by ChangelingRain** [comment]
attack_self rarely, if at ALL, calls ..() and even then it's mostly calling a parent that doesn't. It's nearly exclusively overridden, in fact.

**Comment by MrPerson** [comment]
I know it's more work to implement that way, but I strongly encourage you to reconsider. This kind of stuff makes the code significantly more complicated than it needs to be because you added another link into the attack chain that everyone has to follow down when they need to reread the code. Imagine if this kind of stuff was commonplace. You'd have shit like this:

obj/proc1()
   var1 = foo
   var2 = bar + 2 * foo
   proc2()

obj/proc2()
    var3 = baz
    proc3()

obj/proc3()
    var4 = world.time


With each proc being in different files. When the whole thing could have just been 4 lines in a single proc. Granted in the attack chain there has to be override for each actor in the chain, but still, you don't need two overrides for the same thing.

**Comment by Cyberboss** [comment]
Eh I'll let a maintainer decide on this cause I don't have the energy to do em all

**Comment by optimumtact** [comment]
Mr Person is right, better to leave this in a mess until it's fixed properly

**Pull request closed without merging**
