### PR TITLE
[WIP] Reverts Goofchem

### PR DESCRIPTION
**Pull request by Iamgoofball**
I'm still going through trying to remove all traces of the chems, and it'll take awhile, but here goes nothing.

Putting my money where my mouth is, I'm doing a goofchem revert to see if the **majority** of people actually do really want a goofchem revert still now that its been 2 years.

I'll have a test merge of this ran sometime after I get everything fully swapped back out for trekchems.

### CODE REVIEW

**Comment by Lexorion** [comment]
I like goofchem,please don't revert it.

**Comment by KorPhaeron** [comment]
I don't think we should make the game worse because of bad feelings about the awful debut of goof chem from 2 years ago

**Comment by kevinz000** [comment]
BUT I ACTUALLY LIKE GOOFCHEM NOW. STOP BULLYING US GOOF!!

**Comment by Iamgoofball** [comment]
some would argue this makes the game better

**Comment by KorPhaeron** [comment]
Some would be wrong though, please don't waste your time on this

**Comment by Iamgoofball** [comment]
welp you heard it from the boss man

**Comment by ike709** [comment]
holy shit it's been two years since I've played SS13

**Comment by Man-Shroom-** [comment]
cherry 'flavored lube' dan

**Pull request closed without merging**
