### PR TITLE
Adds eyeball soup to the game.

### PR DESCRIPTION
**Pull request by harmonyn**
https://tgstation13.org/phpBB/viewtopic.php?f=9&t=32&p=273797

>FantasticFwoosh wrote: Eyeball soup, tomatoes & organic eyeballs combined. Looks gross, has text saying that it looks back at you.

:cl: optional name here
add: Eyeball soup may now be made from tomatoes and... well, you know.
/:cl:

What this adds to the game: Following up on a player suggestion. Doing something with all those eyeballs lying around from assistant suicides. Deliciousness.

### CODE REVIEW

**Comment by coiax** [comment]
freeze is dead(tm)

**Comment by bgobandit** [comment]
there are two Feature tagged PRs up

**Comment by coiax** [comment]
Those are autotagged by the bot, and @KorPhaeron said they were fine.

**Comment by octareenroon91** [comment]
Postfreeze, I suggest you put oculine in bonus reagents.

**Pull request closed without merging**
