### PR TITLE
[MDB IGNORE] Hydroponics tray, shower, and sink improvements

### LINKED ISSUE #54226: Hydroponics trays treat water as nutrient when pumped in through ducts
If you pump Water into a Hydroponics Tray using fluid ducts from a synthesizer you can see that the water fills up nutrient space, but then empties into the water space whenever the plant ages, this makes fertilizing the plants with the chemicals you want hard if you have a plumbing system set up to keep them all watered

### LINKED ISSUE #66359: Hydroponics tray plumbing bugs!
Reporting client version: 514.1566

## Reproduction:
Hydro trays and plumbing don't interact well.
Let me explain.
First off, get a plumbing constructor and head down to botany. You're looking to build something like this. 
trays1
Set the synthesizer to 'water' and '5u'.
trays2
Take a plant analyzer, and right click to scan any of your connected trays. 
trays3
Notice how the nutrients are filling up with water? This is bad. This will starve your plants of nutrients/water if you try to pump water into them automatically using plumbing.

Secondly, and this is a very different bug: the plumbing port on hydroponics trays isn't visible unless you pry up the floor. Also, it's offset weirdly; see last screenshot for details.
image
image
image
This makes it very hard to position the trays properly so that they're connected to the pipe network, especially when you have to wrench them down to see if they connect and wrench them back up to rotate them if you're wrong.

### LINKED ISSUE #67584: Plumbing - Showers and sinks connect from bottom only
image

Showers and sinks seem to work with plumbing only when the duct is available below it, regardless of the sink/shower rotation.

It seems like AddComponent(/datum/component/plumbing/simple_demand) doesn't work for showers properly. Not sure if related.

```
[11:07:13] Runtime in stack_trace.dm,3: Incompatible /datum/component/plumbing/simple_demand assigned to a /obj/structure/sink! args: [null]
  proc name: stack trace (/proc/stack_trace)
  src: null
  call stack:
  stack trace("Incompatible /datum/component/...")
  /datum/component/plumbing/simp... (/datum/component/plumbing/simple_demand): New(/list (/list))
  the sink (/obj/structure/sink):  AddComponent(/list (/list))
  the sink (/obj/structure/sink): Initialize(1, null)
  Atoms (/datum/controller/subsystem/atoms): InitAtom(the sink (/obj/structure/sink), 0, /list (/list))
  Atoms (/datum/controller/subsystem/atoms): CreateAtoms(null, null)
  Atoms (/datum/controller/subsystem/atoms): InitializeAtoms(null, null)
  Atoms (/datum/controller/subsystem/atoms): Initialize(292280)
  Master (/datum/controller/master): Initialize(10, 0, 1)
[11:07:13] Runtime in stack_trace.dm,3: Incompatible /datum/component/plumbing/simple_demand assigned to a /obj/structure/sink/kitchen! args: [null]
  proc name: stack trace (/proc/stack_trace)
  src: null
  call stack:
  stack trace("Incompatible /datum/component/...")
  /datum/component/plumbing/simp... (/datum/component/plumbing/simple_demand): New(/list (/list))
  the old sink (/obj/structure/sink/kitchen):  AddComponent(/list (/list))
  the old sink (/obj/structure/sink/kitchen): Initialize(1, null)
  Atoms (/datum/controller/subsystem/atoms): InitAtom(the old sink (/obj/structure/sink/kitchen), 0, /list (/list))
  Atoms (/datum/controller/subsystem/atoms): CreateAtoms(null, null)
  Atoms (/datum/controller/subsystem/atoms): InitializeAtoms(null, null)
  Atoms (/datum/controller/subsystem/atoms): Initialize(292280)
  Master (/datum/controller/master): Initialize(10, 0, 1)
```

### PR DESCRIPTION
**Pull request by Tastyfish**
## About The Pull Request

General to all 3 appliances:
- Generally improved visual behavior of the plumbing connections coming out of offset machines/structures, including sinks, showers, and hydroponics trays so that they visually link up to everything else but still connect to the machine too.
- Level-start plumbing appliances' connections now visually work like atmos machines:
  - If they spawn on a floor tile, the pipe is hidden, if built on a floor tile in-game, the pipe is visible.
  - Un-wrenching an appliance reveals the pipe, placing a fresh floor tile hides the pipe.
  - However in the specific case of showers and sinks, un-wrenching now deconstructs them to be consistent with other structures. Rebuilding them will reveal the pipe.

image
image
image
image

As promised in my other plumbing PR, I'm fixing the plumbing behavior of hydroponics trays:
- The pipe connecting to hydroponics trays now sends water to the mystical water tray correctly.
- Note that if the nutrient level is less than full, but the water level is full, the extra water will be deleted instead of preserved, but this behavior is in parity with using a beaker so I'm not really concerned.
- Note that this will rapidly drain the stationary water tank, but you can also quickly drain that with a bucket in the first place. So if you pipe water, use a chemical synthesizer.
- Fixes #66359
- Fixes #54226

Several shower and sink construction improvements as their code had rotted:
- Showers can now be dismantled with a wrench to match most sinks and most structures.
  - The thermostat adjustment behavior is now down with a screwdriver, and there's an examine tip to indicate that.
- Dismantling showers and sinks now actually drops the water recycler.
- You can now remove the water recycler from sinks and showers with a crowbar, and add one by attacking the appliance with a water recycler.
- As you can now *remove* the water recycler from showers, the function to toggle recycling was removed.
  - Now, the multitool switches between 3 modes, as requested below. The 3 modes are:
    1. The classic and default mode of running until manually turned off, or running out of liquid.
    2. Run until turned off, running out of liquid, or if 15 seconds has passed since turning on.
    3. Run forever, until water has turned off, but turn back on again if there is liquid again.
- In testing this, I found out that showers drop more iron than they cost. That is now fixed.
- I've flipped the facing behavior of placing sinks and showers so you now face the wall instead of away from it. This seems far more intuitive to me, and matches the construction of most other wall-facing/mounted things.
- Sinks are now placed at the same offset as they are in the maps, instead of being inconsistently centered.
  - When figuring out the offsets, I realized the pixel offsets for the sinks were wildly inconsistent between maps and many times within the same map, almost always for no apparent reason and off by 1 pixels.
  - As such, showers and sinks now have directional versions. *This is what all the map changes are.* I've included the update script.
  - I think my big plumbing PR actually is what fixed the backend part of this, but noting this as being fixed regardless:
    - Fixes #67584
  - Sinks and showers are now positioned correctly when rotated on shuttles.
    - Partially Fi*es #39347: Fixes the sinks and showers part, but I haven't checked or changed urinals, since they're out of scope of this PR due to not being plumbing related.

## Why It's Good For The Game

Construction QOL, hydroponics tray plumbing input working as people expect, improved visuals.

## Changelog

:cl:
fix: Shower and sink dismantling is now consistent.
fix: Hydroponics tray plumbing connections now accept water without clogging.
add: Showers now have 3 selectable auto-shutoff modes.
qol: Sinks and showers are now constructed with the player facing the wall.
imageadd: Visuals improved on plumbing connections for offset appliances, like sinks and showers.
/:cl:

### CODE REVIEW

**Comment by Colovorat** [comment]
68747470733a2f2f66696c652e686f7573652f75665a502e706e67

**Comment by Tastyfish** [comment]
> @Tastyfish awesome! I even started looking into by myself, these were so annoying.
> 
> Can I request a couple of things I wanted to do myself, while you're at it?
> 
>     1. Can you make sinks and showers not require water reclaimer? Give the option to insert and extract it from them with crowbar instead of multitool. I'ts annoying that you need to print it when you plan to disable it for plumbing anyway.
> 
>     2. Let people switch the shower mode with multi-tool instead:
> 
> 
>     * Flow until empty - current behavior
> 
>     * Flow for 10 seconds  - so that people won't waste the chems if they forgot to turn it off
> 
>     * Flow constantly - even when it dries out, it should continue flowing when chemicals are available again - to act as constant chemical output (I used this to farm NO2 gas - one reaction chamber is not enough for constant flow, and two are too much)

Yeah sure, I'll look into adding those features.

**Comment by Tastyfish** [comment]
Note that I added those suggested features.

Sadly, the map diffs are slightly less clean and pretty because I had to mapmerge changes that have since happened. Mapdiffbot panicked for probably reasonable reasons. Since the map changes are easily repeatable with the update script I made, I can reset the changes at any time.

**Comment by MTandi** [comment]
@Tastyfish right now you can't turn it off when it is on and has less than 5 units inside - it says the shower is dry when you click on it while it is on. It makes it impossible to turn it off in the continuous flow mode, because when the contents reach 5u, they're used.

Can you please allow to turn it off when it has less than 5 minutes?

**Comment by notfrying1pans** [comment]
you should've [MDB IGNORE]'d this

**Comment by Tastyfish** [comment]
> [MDB IGNORE]

Right, forgot about that.

**Comment by MTandi** [comment]
@Tastyfish the shower is not interactable for some reason if mounted with its back to the window.

**Comment by Tastyfish** [comment]
> @Tastyfish the shower is not interactable for some reason if mounted with its back to the window.

Ah, I see what you were talking about, yeah layer issue that's easy to fix.

**Comment by Tastyfish** [comment]
Big shout-out to whoever made the UpdatePaths script because it would not otherwise be remotely viable to keep the maps synced on stuff like this. Anyway, everything should be working without weird hiccups.

Had to completely refactor the processing logic for showers but that's how it is sometimes.

**Review by Twaticus — APPROVED** [review]

**Comment by Mothblocks** [comment]
@Tastyfish Please fix conflicts ASAP

**Comment by Tastyfish** [comment]
@Mothblocks Conflicts fixed.

**Pull request merged**
