### PR TITLE
Increases hatchet throw range to 7 and allows them to embed

### PR DESCRIPTION
**Pull request by Sparkezel**
## About The Pull Request
what it says on the tin

## Why It's Good For The Game
I think it would be fun if you could throw hatchets and get them embedded in your victims, I was surprised that it wasn't a thing in the first place.

## Changelog
:cl: SparkezelPL
balance: Hatchets have longer throw range and can embed
/:cl:

### CODE REVIEW

**Comment by wesoda25** [comment]
Axe thrower skillchip when?

**Comment by coiax** [comment]
Speaking to @Ryll-Ryll, it seems that the default throw speed is 3, and the required speed for embedding is 4. So a hatchet thrown by a person will never embed. If it was thrown by an explosion, it'd be thrown at speed 4.

If you look at spears or throwing stars, both have a throw speed of 4, which is how they reliably embed.

**Comment by coiax** [comment]
Could I have some comparison numbers for the other major easily accessible embeddables? Spears, and traitor throwing stars?

I don't have a good feel for the balance of these weapons.

**Comment by Sparkezel** [comment]
from the top of my head I can say that on meta and delta there is a small chance for traitor box to spawn, other than that, there isn't any traitor loot iirc. 
About spears you can make them, they deal 21 damage, and if they embed its pretty much guaranteed weeping
And about hatchets, you can print more and there is guaranteed 2 on each map
image
you can also print cult blades at library if you emag it, while they don't embed, they deal 25 brute on throw and pretty much guarantee a T1-2 slash wound

**Pull request merged**
