### PR TITLE
Allows heretics to rust titanium/plastitanium + ascended rust heretic spread on indestructible tiles

### PR DESCRIPTION
**Pull request by GoblinBackwards**
## About The Pull Request
Allows heretic to rust titanium and plastitanium walls/floors.
Also allows the spreading rust from rust heretics ascention to rust indestructible floors.

## Why It's Good For The Game
Considering how reliant rust heretics are on having rusted tiles for most of their combat power, and the fact that almost nothing else in the game is immune to being rusted, it makes no sense that the most common shuttle material should just completely invalidate   all of rust heretics passive benefits.

Indestructible floors can already be rusted using rust heretic spells, as far as I can tell there's no reason for them to be blacklisted from the ascended heretic rust spread as well.

## Changelog

:cl:
balance: Allows heretics to rust titanium and plastitanium
balance: Allows the spreading rust from heretic ascension to rust indestructible floors
/:cl:

### CODE REVIEW

**Comment by SuperNovaa41** [comment]
This is not a fix. The comments you removed clearly stated that it was intended.

**Comment by VladinXXV** [comment]
Titanium (and presumably plastitanium) are incredibly resistant to corrosion, this doesn't make much sense. It's also very niche, you only really see titanium flooring/walls on existing shuttles.

**Comment by NoxVS** [comment]
> Titanium (and presumably plastitanium) are incredibly resistant to corrosion, this doesn't make much sense. It's also very niche, you only really see titanium flooring/walls on existing shuttles.

it also doesn't make much sense for someone to be able to perform esoteric rituals to be able to conjure up corrosion to rust the whole station

**Comment by VladinXXV** [comment]
> I like there being materials that can be used to counter rust, i think it's a neat interaction - it lets clever players counter rust, makes rust heretics have to be more aware of their surroundings, and allows people put rust heretics in shame cubes
> 
> If you're gonna remove titanium because it's commonly used (i assume this was made because "i ded, couldn't rust the shuttle floor") replace it with something like silver or gold (specifically make it an effect of the material datum cause that's fun) image

image
titanium is RIGHT UP THERE with gold and silver in terms of resistance

**Comment by MrMelbert** [comment]
> titanium is RIGHT UP THERE with gold and silver in terms of resistance

yeah i'm not saying it makes any less or more sense, i'm just saying if you WANT to remove titanium's resistance it should be given to something else

**Pull request closed without merging**
