### PR TITLE
[DNM] MGR Security: Straight Out of Denver

### PR DESCRIPTION
**Pull request by Paxilmaniac**
## About The Pull Request
This is entirely a shitpost, testmerge it for like one round and then never let it see the light of day again

Essentially, turns security into these guys:
image

LiveLeak image of police brutality:
image

## Why It's Good For The Game

Current security? Red? Stun batons? Disablers? You ever hear of anything lamer than that?

What we REALLY need is our security team to look like these motherfuckers.
image

## Changelog

:cl:
add: New security themed sword sheath, for holding your patent pending security high frequency blade
add: Several new, blue colored security outfit options, which everyone will start with (Though I guess if you really hate them the vendors are still there) ((Sprites for the cap and vest are from skyrat))
balance: The security team now spawns a gun and a sword, as god intended
fix: Every security related balance issue has now been resolved
/:cl:

### CODE REVIEW

**Comment by Paxilmaniac** [comment]
> You currently have a negative Fix/Feature pull request delta of -1. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

NOOOOOOOOOOOO -1 GBP MY PR IS DOOOOOOOMED

**Comment by castawaynont** [comment]
This fixes every single problem with sec, speed merge

**Comment by necromanceranne** [comment]
Oh so it's okay is SHE ADDS SECURITY KATANAS

**I SEE HOW IT IS**

**Comment by RuneQuester** [comment]
The greatest shitpost to grace the TG github

**Comment by Wallemations** [comment]
Nukies/Lone Ops should get access to the admin HFBlade variant.
Also the HOS should clearly have permanent Hulk.
Warden boutta bust out with dual pincer machetes.

**Comment by Spc-Dragonfruits** [comment]
I'm so sorry officer, I was just so busy making a content PR for TG Station!

**Comment by Paxilmaniac** [comment]
I KNEW A MErgE CONFLICt WOULD HaPPEN DAMNIT

**Comment by axietheaxolotl** [comment]
i will be the lone disenting opinion

you are like a week too late for this to be funny
still a good pr tho

**Comment by RuneQuester** [comment]
Only 5 force, lame

**Comment by Paxilmaniac** [comment]
> Only 5 force, lame

5 force, which is multiplied by up to 4.5 if you use the sword right

**Comment by ATH1909** [comment]
> > Only 5 force, lame
> 
> 5 force, which is multiplied by up to 4.5 if you use the sword right

and able to be used 8x as often a normal melee attack, IIRC

**Comment by Paxilmaniac** [comment]
Kill me, every day I come back to get this testmerged there's a merge conflict. Doing this again in exactly three months when mgr memes get popular for literally no reason again.

**Comment by drIcepop** [comment]
MGR memes will always be popular

**Comment by Iamgoofball** [comment]
the worst part is she predicted the timing perfectly re: MGR memes getting popular again

**Pull request closed without merging**
