### PR TITLE
Kills `/obj/shapeshift_holder`, replaces it with `/datum/status_effect/shapechange_mob`, also does a lot of Wabbajack refactoring

### LINKED ISSUE #52786: if you get change bolted while shapeshifted, your original body dies
Steps to reproduce:
1. Be a wizard with the Shapeshift spell, a friend, and a staff of change.
2. Use Shapeshift to become an ED-209 or a bat or something.
3. Have your friend change bolt you while you're in your Shapeshift form.
4. You'll be turned into a random creature, as normal, but your old body (the non-shapeshifted version) will fall over dead.
5. Casting Shapeshift again will turn you into your Shapeshift form.

wizardbug3

### LINKED ISSUE #59127: shapeshifting + holoparasite bugs
acquiring a holoparasite, shapeshifting, and then returning to your normal form kills your holoparasite.

acquiring a holoparasite, shapeshifting, and then damaging your holoparasite damages your original form inside of you, not your shapeshifted form. acquiring a holoparasite, shapeshifting, and then damaging your shapeshifted form does not damage your holoparasite's host, according to its status panel.

acquiring a holoparasite, shapeshifting, and then casting mind transfer on your holoparasite puts you in control of your original body inside of your shapeshifted one. casting fireball while in this state makes you shout ONI SOMA, but doesn't appear to actually fire any projectile. knock appears to be uncastable while in this state. casting shapeshift again while in this state kills you. I haven't tested what happens if you try to cast blink or jaunt while in this state.

### LINKED ISSUE #65653: Magic Polar Bear Transformation removes the ability to hear
Reporting client version: 514.1582
## Round ID:
[180443](https://scrubby.melonmesa.com/round/180443)

## Testmerges:
- [Adds mob bleeding overlays, tweaks some bleeding balance](https://www.github.com/tgstation/tgstation/pull/65371)
- [Pingbus changes and improvements](https://www.github.com/tgstation/tgstation/pull/65625)
- [Almost halves airlock auto close delay](https://www.github.com/tgstation/tgstation/pull/65349)
- [Action button refactor/rework: Enhanced Dragging](https://www.github.com/tgstation/tgstation/pull/65180)

## Reproduction:
Using the ability to transform into a magic bear gained from the wendigo blood bottle causes you to lose the ability to read text after returning to your prior form. Going from your prior form back to your bear form causes you to regain the ability to hear text. The ability to talk and hear over radio is unhindered, you just can't see any local chatter, including your own, in both rune text and in the chat menu. I've noticed this issue persisting through several rounds as miner on icebox.

### LINKED ISSUE #69117: Cannot see/hear local runechat after using a transformation ability
## Round ID: 
[188225](https://scrubby.melonmesa.com/round/188225)

## Testmerges:
#69023 #69088

## Reproduction:
Obtain a transformation ability (The issue was observed with the dragon transform ability from the ash drake boss). Use it, then shapechange back into a human. 

You'll get a bunch of 'Your previous action was ignored because you've done too many in a second' and you lose the ability to hear/see any emotes or speech around the area you're in for a few minutes. You can still hear the sound effects, however, and you can also hear any chatter in telecomms. The runechat does appear for any telecomm chatter.

### PR DESCRIPTION
**Pull request by MrMelbert**
## About The Pull Request

- Deletes `/obj/shapeshift_holder`, replaces it with `/datum/status_effect/shapechange_mob`
- Refactors Heretic worm form into a shapeshift spell
- Refactors Wabbajack, and associated code

Fixes #69117
Fixes #65653 
Fixes #59127 
Fixes #52786

## Why It's Good For The Game

`/obj/shapeshift_holder` was one of the worst remaining abuses of `/obj` direct subtypes, so I replaced it with a cool fancy datum. 

This also decouples the shapeshifting behavior entirely from the shapeshifting spell. So we have support for shapeshifted mobs not sourced from a spell. Which is neat, we could technically swap Wabbajack to use this in the future. 

## Changelog

:cl: Melbert
fix: Wabbajacking a shapeshifted mob no longer runtimes horribly. When a shapeshifted mob is wabbajacked, they'll now be removed from their shapeshift and stunned.
fix: Transforming via a shapeshift should no longer rob you of your hearing / runechat awareness. 
fix: Shapeshifting plays nicer with holoparasites. 
fix: Being polymorphed from a xeno to a non-xeno correctly makes you a non-xeno
refactor: Refactored shapeshifting, the shapeshift holder is now a status effect instead of an object.
refactor: Heretic worm form is a shapeshift spell now, this might have some minor behavioral changes but should overall be the same. 
refactor: Refactored Wabbajack (+ cursed pool). Overall a bit more clean / consistent behavior. 
/:cl:

### CODE REVIEW

**Comment by timothymtorres** [comment]
Would you be able to rename all wabbajack names to polymorph?  I think more people are familiar with the latter and it confused me when I first encountered it a while back.

**Comment by tralezab** [comment]
wabbajack is well known enough, keep it as is

**Comment by Fikou** [comment]
> If it's not too much to ask, would you be able to rename all wabbajack names to polymorph? I think more people are familiar with the latter and it confused me when I first encountered it a while back.

https://www.youtube.com/watch?v=qYHXsa5AaY4

**Comment by RazorManager89** [comment]
Could this perhaps fix #69117?

**Comment by timothymtorres** [comment]
Things you may want to consider:

- **Changeling Transform** - [1](https://github.com/tgstation/tgstation/blob/952c3ee0d3075d94edc6f1af2954408f7edd15c1/code/modules/antagonists/changeling/powers/lesserform.dm#L1-L37) [2](https://github.com/tgstation/tgstation/blob/04f43d6d45825b1095c868e79c7b6fb17f59e06f/code/modules/antagonists/changeling/powers/humanform.dm#L37-L54) [3](https://github.com/tgstation/tgstation/blob/04f43d6d45825b1095c868e79c7b6fb17f59e06f/code/modules/antagonists/changeling/powers/tiny_prick.dm#L66-L107)
- **Envy's Knife Transform** - [1](https://github.com/tgstation/tgstation/blob/a3343c5a3ece5fd3156b9a6e5bc7d17780fb2e0c/code/modules/mapfluff/ruins/objects_and_mobs/sin_ruins.dm#L124-L138)
- **Malf AI Robotic Factory Transform** - [1](https://github.com/tgstation/tgstation/blob/8c7e4ef6ee0b6e60783ccb084d60138353b2e2be/code/game/machinery/transformer.dm#L74-L106)
- **DNA Injector Transform** - [1](https://github.com/tgstation/tgstation/blob/fd9bdf8c01a71ec9620445eb9650d5435047f1c7/code/datums/dna.dm)
- **Other Transform Procs** - [1](https://github.com/tgstation/tgstation/blob/2843f6c188cbae95a95a79bcd08b2e553a18ee00/code/modules/mob/transform_procs.dm)

We need a transform proc that is called by every type of polymorph transformation that handles all the references to shapeshifting, holoparasites, organs, mood events, antag status.  Right now several different procs implement their own version of shapeshifting that leads to bugs like the following:

- #53048
- #59127
- #25287
- #52786
- #55153
- #54817
- #60994
- #40040
- #35539
- #42098
- #42308
- #53758
- #45821
- #31732
- #29360
- #64122
- #65037
- #42685
- #32074
- #65653
- #67574
- #61342
- #55394
- #56374
- #52095
- #50908
- #50804
- #44349
- #23234
- #31529
- #39130
- #61727
- #57011
- #59128
- #47048
- #68894
- #68416
- #66626
- #64466
- #67767

Polymorph code is like playing whack-a-mole with the issue tracker.  It generates so many extreme edge cases that causes a ton of issues.  I'm sure you're PR will fix a lot of these Melbert.  However these will keep appearing in the future if all these different procs do their own custom polymorph implementations.  

This might be out of scope to fix all of this in your PR, but I've always wanted a spot where I could track all the polymorph issues in one place.  It is **the worst** thing on the issue tracker that creates the most problems I have ever seen since I became an issue jani.

**Pull request merged**
