### PR TITLE
lowers the max radstorm duration to 1000 from 1500 ticks

### PR DESCRIPTION
**Pull request by Tlaltecuhtli**
:cl:
balance: lowers the max radstorm duration to 1000 from 1500 ticks
/:cl:
boring event that lasts painfully long and no one likes it

### CODE REVIEW

**Comment by pireamaineach** [comment]
I unironically like radstorms.

**Comment by subject217** [comment]
radstorm creates interesting opportunities and restrictions tbh, it's a good event

**Comment by ArcaneMusic** [comment]
Radstorms are what purged the good new players from the old. If they couldn't figure out that radiation was bad, what a "Maintenance" is, or how to ask in OOC what was happening in round, well then they were fucking dead kiddo. By lowering this value, we allow for more "Strategic Diversity" in ways for new players to die.

**Comment by Tlaltecuhtli** [comment]
@subject217 i m not removing it but removing the insane max timer, if you wanted to kill someone during the storm you have 1000 ticks at least while everyone goes afk because you have enough time to check your twitter, email, discord and ntr hut

**Comment by Shapsy** [comment]
>alt tabbing instead of chatting and engaging with the other people locked in maint with you

Good Lord is this how boring you people are to be around?

**Comment by ExcessiveUseOfCobblestone** [comment]
> > alt tabbing instead of chatting and engaging with the other people locked in maint with you
> 
> Good Lord is this how boring you people are to be around?

this just makes my murderbone easier

**Comment by anconfuzedrock** [comment]
Because I’m not gay(unlike you) I prefer my murderbone to be rock hard.

**Comment by ShizCalev** [comment]
image

**Pull request closed without merging**
