### PR TITLE
Adds a second version of the witch hat

### PR DESCRIPTION
**Pull request by dootdoom**
## About The Pull Request

Recently the old witch hat was replaced with a different one. This pr just makes it so its a second version of the hat instead of it just being flat out replaced.

## Why It's Good For The Game

Because a lot of people like the old hat and it shouldn't just be flat out replaced when its a nice lookin' hat.

## Changelog
:cl:
add: There is now a secondary witch hat thats purple
/:cl:

### CODE REVIEW

**Comment by necromanceranne** [comment]
You could just add the purple ribbon back onto the new sprite, there is more to that sprite than just the ribbon.

**Comment by Tharcoonvagh** [comment]
Just... why

**Comment by necromanceranne** [comment]
Also this is an alt costume so I now realize this might not be kosher in the first place. You should double check with a maintainer about that.

**Comment by optimumtact** [comment]
the bikeshed should be blue

**Pull request closed without merging**
