### PR TITLE
removes OP and cheap swat crates

### PR DESCRIPTION
**Pull request by optimumtact**
These are better left as ERT/Admin content

Removes swat crate
Removes combat knife crate

### CODE REVIEW

**Comment by Bawhoppen** [comment]
>OP >CHEAP

6000 is not cheap for 2 moderately armored space suits, they're nowhere near as good as ERT/admin equipment. 6000 is a fuckton man

**Comment by optimumtact** [comment]
Swat suit
	armor = list(melee = 40, bullet = 30, laser = 30,energy = 30, bomb = 50, bio = 90, rad = 20)

riot suit:
	armor = list(melee = 50, bullet = 10, laser = 10, energy = 10, bomb = 0, bio = 0, rad = 0)

captains carapace:
	armor = list(melee = 50, bullet = 40, laser = 50, energy = 10, bomb = 25, bio = 0, rad = 0)

they're better in nearly every category but melee to the riot suit and almost as good as the captains carapace.

Lets not even figure the fact that combat knifes have nearly as much brute as a fireaxe.

**Comment by Bawhoppen** [comment]
the combat knives are now in a completely seperate crate, which makes the SWAT crate way less valuable
the swat armor itself is a pain to use  and not super useful due to the huge slowdown, have you ever tried to actually use it?

**Comment by optimumtact** [comment]
all spacesuits have that slowdown

**Comment by Bawhoppen** [comment]
yes but combat in this game is about mobility, that makes it not that good to use compared to other stuff

**Comment by KazeEspada** [comment]
SPACE SUIT! Its armor beats nearly any on station armor and you can fuck off INTO FUCKING SPACE.

**Comment by Bawhoppen** [comment]
It has a large cost associated with it, and when in use it doesn't perform as well as you may think just from looking at the stats.
Have either of you actually used it?

**Comment by Supermichael777** [comment]
if its as good as you say it is no captain will ever get dunked in their armor. oh wait that happens all the time.

**Comment by Zilenan91** [comment]
Yeah because armor doesn't matter in this game, at all. That's why this pr is kinda ridiculous, stun > any armor.

**Comment by Robustin** [comment]
Yea I don't get it. Armor can matter when you're sec and most of your opponents rely on damage as much as stuns to take you out.

But when you're an antag, you're 90% concerned with stuns. They're sec's bread and butter and running around as an overt antag with a slowdown is a death sentence if there's any competent sec aboard. Not sure I see the point of this.

**Comment by optimumtact** [comment]
If the armour is so shit then it won't matter anyway right :^)

**Comment by Bawhoppen** [comment]
don't be retarded oranges, it still clearly has a use, just not nearly as good as you try to paint it as

**Comment by Iamgoofball** [comment]
okay whats the use then

**Comment by Bawhoppen** [comment]
its still useful in general but its not extremely useful like you tried to make it sound like

**Comment by Iamgoofball** [comment]
that wasn't a use, that's a vague "its still useful"

whats the use then

**Comment by Bawhoppen** [comment]
the use is for some combat situations, hence why i said in general
stop being retarded goof and picking semantics

**Comment by Iamgoofball** [comment]
i'm picking semantics because we're having a debate, and your argument point was "it still clearly has a use", as you're referring to a specific use with "has **A** use"

**Comment by Bawhoppen** [comment]
thats called you picking semantics and not the general intent of the message

**Comment by optimumtact** [comment]
Death to swat crates

**Comment by optimumtact** [comment]
Also if #19760 goes through they'll be even more rediculous


armor = list(melee = 55, bullet = 40, laser = 35,energy = 40, bomb = 55, bio = 90, rad = 20)

It makes them better than the captains armour in nearly every respect, which is just rediculous considering they can be ordered for so cheap. There is zero reason for security to not order them every single round

captains carapace:
armor = list(melee = 50, bullet = 40, laser = 50, energy = 10, bomb = 25, bio = 0, rad = 0)

**Comment by Iamgoofball** [comment]
6K is children's dosh

**Comment by Bawhoppen** [comment]
not my fault prices are so fucked nowadays

**Pull request closed without merging**
