### PR TITLE
[READY AND TESTED]Projectiles now properly delete themselves if they try to move and their trajectory is at an invalid turf

### LINKED ISSUE #35890: Bullets are interacting weirdly with map edge on lavaland
Issue reported from  Round ID: 84004 (/tg/Station Sybil [ENGLISH] [US-EAST] [100% LAG FREE])

Reporting client version: 511

image

#34713: '[READY]Astar improvement' by arsserpentarium at commit 33cd64
#35775: '[READY]Randomized Station Time + Night Shifts' by kevinz000 at commit b1b186

### PR DESCRIPTION
**Pull request by silicons**
title
Fixes #35890

### CODE REVIEW

**Comment by Poojawa** [comment]
You should probably test this.

**Comment by kevinz000** [comment]
also don't forget my fix label ;)

**Comment by AnturK** [comment]
I'm confused, does this mean projectiles won't be able to pass z boundaries ?

**Comment by kevinz000** [comment]
No it means they won't never delete and keep runtining when there's no boundary to cross. Lavaland anyone?

**Pull request merged**
