### PR TITLE
Adds skeleton and robot wings from Yog

### PR DESCRIPTION
**Pull request by tralezab**
## About The Pull Request

sprites from https://github.com/yogstation13/Yogstation/pull/11511

image

image

## Why It's Good For The Game

All species in our codebase have wings, except some species get unique sprites if they are available. There are now skeleton and robot wings in existence so we must do the needful of letting robots and skeletons ascend from basic bitch angel wings.

## Changelog
:cl: Mqiib's spritework
imageadd: Skeletons and Robots now have unique wing sprites
/:cl:

### CODE REVIEW

**Comment by JohnFulpWillard** [comment]
> All species in our codebase have wings

Not true, Flypeople/Ethereals/Plasmamen dont get anything, I dont think they even get an effect when they drink the potion.

**Comment by EgorDinamit** [comment]
> > All species in our codebase have wings
> 
> Not true, Flypeople/Ethereals/Plasmamen dont get anything, I dont think they even get an effect when they drink the potion.

They said in **their** codebase, not /tg/'s.

**Comment by EgorDinamit** [comment]
Correct me if I'm wrong, but I don't see you assigning robotic wings anywhere.

**Comment by SmArtKar** [comment]
what are robot wings supposed to be? Just asking, I am just curious what those 8 yellow blobs are

**Comment by D4C-420** [comment]
> what are robot wings supposed to be? Just asking, I am just curious what those 8 yellow blobs are

MACHINE 
image

**Comment by tralezab** [comment]
> Correct me if I'm wrong, but I don't see you assigning robotic wings anywhere.

oops, got it


> > All species in our codebase have wings
> 
> Not true, Flypeople/Ethereals/Plasmamen dont get anything, I dont think they even get an effect when they drink the potion.

I find this really hard to believe i'm gonna test it

**Comment by dragomagol** [comment]
Let's GO

**Comment by Fikou** [comment]
not sure but i think the wings dont use the same color palette as the skeleton?

**Comment by tralezab** [comment]
image

**Comment by RuneQuester** [comment]
> ## flies get wings all the same
> image

I know for a FACT that plasmaman do not have wings currently,because I've drunk a flight potion and nothing happened

**Comment by tralezab** [comment]
flight potion doesn't give those species wings, but they can have wings through alternate ways

**Review by Krysonism — APPROVED** [review]
I think the sprites are good enough given how uncommon these wing types are.

**Comment by Mqiib** [comment]
How nice of you to consider my shitty sprites good enough to add.

**Pull request merged**
