### PR TITLE
fixes trays not going on belt slot

### PR DESCRIPTION
**Pull request by Tlaltecuhtli**
🆑 
fix: tray now goes on belt again
/:cl:

### CODE REVIEW

**Comment by Tumesuo** [comment]
does it have sprites dat work

**Comment by ArcaneMusic** [comment]
I removed belt slots from trays because otherwise they'd need on-mob sprites, which I felt wouldn't even make sense functionally in the first place.

**Comment by nightred** [comment]
> I removed belt slots from trays because otherwise they'd need on-mob sprites, which I felt wouldn't even make sense functionally in the first place.

I was going to comment that this needs a on-mob sprite also.
This is to fix #54058

**Comment by BigGrease** [comment]
you can add straps if u want so you hang it off ur shoulders or something butits an apron and im assuming you just hang it off your apron. just make a little tray on the hips and waist if you want a sprite

**Review by ShizCalev — CHANGES_REQUESTED** [review]
needs sprite

**Pull request closed without merging**
