### PR TITLE
Isometric Station

### PR DESCRIPTION
**Pull request by tralezab**
## About The Pull Request

Finally, SS13 looks AWESOME.

## Why It's Good For The Game

Setting client.dir works now

## Changelog
:cl:
add: Swept is DONE.
refactor: client dir works now
/:cl:

### CODE REVIEW

**Comment by notfrying1pans** [comment]
WOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO

**Comment by maxymax13** [comment]
epic

**Comment by LemonInTheDark** [comment]
lmao

**Comment by unit0016** [comment]
meme PR aside I genuinely think a 2.5-ish lookin spessmans would be neat.

**Pull request closed without merging**
