### PR TITLE
prevents spawners being teamkilled

### PR DESCRIPTION
**Pull request by 4dplanner**
:cl:
fix: spawners check allegiance
/:cl:

closes #41709

### CODE REVIEW

**Comment by ExcessiveUseOfCobblestone** [comment]
sentient lavaland mobs will still carry the faction I think

**Comment by 4dplanner** [comment]
They do, but I put an &&!M.client in there as well

**Comment by 4dplanner** [comment]
Am I missing something obvious?

**Comment by ExcessiveUseOfCobblestone** [comment]
Yes, you're missing a very clear opportunity to call me dumb.

**Comment by 4dplanner** [comment]
> Yes, you're missing a very clear opportunity to call me dumb.

Would be a better opportunity if this PR wasn't based on your advice ;)

**Review by ExcessiveUseOfCobblestone — APPROVED** [review]

**Pull request merged**
