### PR TITLE
Removes ishuman() check for beekeeping

### PR DESCRIPTION
**Pull request by coiax**
:cl: coiax
bugfix: Non-humans are now able to interact with bee boxes.
/:cl:

### CODE REVIEW

**Comment by phil235** [comment]
So which mob can now interact with bee hives? Did you test it?

**Comment by RemieRichards** [comment]
@phil235 ```bee_friendly()``` automatically blacklists all invalid mobs, to be valid they must return 1 in ```bee_friendly()```, this simply allows Drones to beekeep.

**Comment by PKPenguin321** [comment]
Technically bees are living so drones shouldn't do that anyways

**Comment by coiax** [comment]
We shouldn't enforce in code what is policy. Silicon policy suggests that AIs shouldn't have the ability to open and close doors with no safeties crushing people horribly. But we do, because sometimes they don't play by the rules. I've heard discussion of a lavaland ruin featuring wild beekeeping drones.

**Comment by RemieRichards** [comment]
@PKPenguin321 drone laws are editable by admins and coders.

**Comment by PKPenguin321** [comment]
that will probably not ever happen at least in terms of bee memes but i guess so

**Comment by Zilenan91** [comment]
I don't know why admins would ban drones for beekeeping, that just sounds like a shitty thing to do even if it is technically against the rules

**Comment by octareenroon91** [comment]
I don't see the drone problem here. How is this 'involving yourself in the matters of another beeing"?

**Comment by PKPenguin321** [comment]
>I don't know why admins would ban drones for beekeeping, that just sounds like a shitty thing to do even if it is technically against the rules

Well I mean there's that and the fact that bees are pretty much designed to sting and inject humans with chems, not something drones should be doing

**Pull request merged**
