### PR TITLE
tgui-next: useBackend edition

### PR DESCRIPTION
**Pull request by stylemistake**
## About The Pull Request

A massive pull request which does very little, but is still very important.

- **Input is now compatible with IE8**. It can be considered safe for mainstream adoption. Most of the bugs were squashed.
- `useBackend` is now a thing (which provides an implicit `act` function).
- Most of the code was changed to use `useBackend`.
- Micro CSS fixes for Tabs component.
- Improved Collapsible component: reduced nesting, reused a Button component, and made appearance a lot more predictable (native tables have unwanted spacing).
- Unfucked code style on most interfaces.
- General improvements to Uplink code.
- General code cleanup, migrate old interfaces to some newer API.
- Blue screen now stacks multiple errors instead of printing the latest one, which was not very informative.
- You can now set an IP address of your machine through environment variables to enable remote logging/debugging (e.g. of IE8 behind a virtual machine).
- BlockQuote got a separate CSS component, and uses a "label" color by default.
- Redesigned KitchenSink, which uses a tabbed view for each component type.
- Other things which I forgot to mention.

It took way too long to migrate everything to `useBackend` and I went absolutely crazy from this repetitive work. Worst thing about this, is that `useBackend` is still a transitional solution, which we will have to replace with a proper React hook in the future.

Oh right, I advise to testmerge it for at least a day, since it touches so much code. I could not test everything.

### CODE REVIEW

**Comment by PKPenguin321** [comment]
>Blue screen now stacks multiple error instead of printing the latest one, which was not very informative.

Can this cause issues with large amounts of errors?

**Comment by stylemistake** [comment]
In practice, no, because I shut down all updates, and I only ever got two errors at maximum.

**Comment by TheVekter** [comment]
What does this change for TGUI dev in general? Should we be using `useBackend` instead of `act`?

**Comment by stylemistake** [comment]
Yes, `useBackend` will be the new way.

**Review by actioninja — APPROVED** [review]
looks good, is this ready/done?

**Comment by stylemistake** [comment]
It is done, just untested.

**Comment by actioninja** [comment]
Been testmerged for like a day and people seem to have not even noticed so it's most likely fine. This is blocking any currently open tgui pr so I'm going to fullmerge so we can deploy to all of our test servers:tm:

**Pull request merged**
