### PR TITLE
Secret panel once again improved

### PR DESCRIPTION
**Pull request by tralezab**
## About The Pull Request

New NEW secrets:

new_secrets

Miscellaneous old garbage I caught:
For some reason, monkey and only monkey button sent a to_chat to the world of your sins. I cut that, that's unacceptable
I accidentally left out species change from my last pr, it's back in.

## Why It's Good For The Game

Much easier to add to this panel, before with flexboxes it was nearly impossible but stacks are a lot more friendly.

image

## Changelog
:cl: General Bazelart Haffaz Aladeen
admin: Sorry I changed secrets panel again, it's more organized and has open spaces for some new buttons
admin: Making everyone monkey from secrets panel no longer snitches to the entire server
admin: Readded change all species button to only fun for you
/:cl:

### CODE REVIEW

**Comment by tralezab** [comment]
Fellow coders, if you haven't tried out the new stacks, you gotta. Changes the whole damn tgui game

**Comment by MrDoomBringer** [comment]
Can you make the fun panel look like this 
image

Also, I get what you're trying to do in the Helpful Tab with organizing rows by functionality, but that will probably fall apart as soon as a new button is added to the menu. Maybe consider a different way of sorting that doesn't involve a bunch of placeholder buttons

**Comment by MrDoomBringer** [comment]
but also yes the UI looks much better in a grid system👍

**Comment by davethwave** [comment]
What the heck does chinese cartoons button even do.

**Comment by MrDoomBringer** [comment]
@davethwave makes everyone a felinid

**Comment by davethwave** [comment]
Thought that was mass purrrbation.

**Comment by cacogen** [comment]
without bothering to look it up if i remember correctly the female announcement voice says 'hey this is just like one of those japanese animes' and everyone's jumpsuit is changed to one of those japanese schoolgirl outfits

also the amount of editorialising/cutesy bullshit in this menu is agonising

**Comment by tralezab** [comment]
Had to respect how soulful the old one was you know

**Comment by Jared-Fogle** [comment]
linters

**Comment by Mothblocks** [comment]
LINTERS

**Pull request merged**
