### PR TITLE
switches book binder and scanner to 3/4th perspective

### PR DESCRIPTION
**Pull request by Militaires**
:cl: basilman
add: new book binder and scanner sprites
/:cl:

mspaint_2017-02-18_16-10-49
mspaint_2017-02-18_16-10-25

### CODE REVIEW

**Comment by Jordie0608** [comment]
Stop making dumb changelog entries.

**Comment by WJohn** [comment]
They're not BAD, but they could be better. I guess they're roughly equal in terms of actual quality, and maybe it's just dumb nostalgia clinging to the old style. But whatever, we're pushing to 3/4th, so I'm okay with this.

**Comment by Militaires** [comment]
only because it was you who told me to do it @jordie0608

also this conflict wont go reeeeee

**Comment by Thunder12345** [comment]
Scanner looks like some sorta console tbh

**Comment by Militaires** [comment]
@thunder12345 in the future everything's a console

**Comment by WJohn** [comment]
How did this get conflicts??? No one touches these sprites.

**Comment by Supermichael777** [comment]
I still think these suffer from poor volume and definition. 3/4 was a cheap trick to get depth, these just feel flat. Hell the scanner looks more like an interior corner.

**Comment by Militaires** [comment]
@supermichael777 these look pretty 3/4th to me

@wjohnston mime kit

**Comment by Militaires** [comment]
@supermichael777 they look pretty 3/4th to me

@wjohn mime kits

**Comment by dannno** [comment]
thanks dude, this is a huge help

**Comment by ExcessiveUseOfCobblestone** [comment]
art majors taking over my precious 2d auti... i mean atmos simulator....

**Comment by Militaires** [comment]
@WJOHN @SUPERMICHAEL777 @THUNDER12345

el tweako http://i.imgur.com/VBNJAGa.png

**Comment by Supermichael777** [comment]
not three fourths what we had before.

These are too flat

**Comment by Supermichael777** [comment]
still not a fan.  It just looks flat.

**Comment by PKPenguin321** [comment]
These look really flat compared to the old ones and just a lot worse

**Comment by Militaires** [comment]
tbh true screw this

**Pull request closed without merging**
