### PR TITLE
ports sprites from Endless-Horizon/CEV-Eris

### PR DESCRIPTION
**Pull request by Lexorion**
# Ports a bunch of sprites from https://github.com/Endless-Horizon/CEV-Eris/tree/master/icons
(with their permission,thanks Bloodpriest!)

## medkits/tcomm/goonsprites are no longer part of the PR
**EDITED!** Picture below shows the majority of the sprites

1: Washing machine
2: Seed extractor , biogenerator
3: Microwave
4: Photocopier, binder
5: Powersink, forensic scanner 
6: Mechfab, autolathe, pipedispenser
7: Modular laptop
8: Rack, plasma/oxygen dispenser
9: Portable generators
10: Stacker, unloader (corner), furnace , unloader (corner 2), unloader
11: Stock parts (box_0-2,vbox_0-2)
12: Circuit imprinter, protlathe, analyzer, server, tdoppler
(13:) Charger

### CODE REVIEW

**Comment by Wutnold124** [comment]
oh hell yes

**Comment by lzimann** [comment]
medkits and the recharger are ugly

**Comment by PKPenguin321** [comment]
We've rejected the book binder one already, and the t ray is nasty

**Comment by MMMiracles** [comment]
3/4 perspective is uggggggghhhhhh

**Comment by GunHog** [comment]
What are the machines in the bottom left three rows? I recognize only the recharger and Doppler array.

**Comment by Lexorion** [comment]
@PKPenguin321 https://github.com/tgstation/tgstation/pull/24230? Did not take the sprites from there
@GunHog  Circuit imprinter,protolathe and analyzer and server (from left to right) , sorry I didn't take gifs since they'd make it more obvious

**Comment by PKPenguin321** [comment]
It would be nice if you could go in MS paint or something and put text under the sprites saying what they are since a lot of these look almost nothing like the old sprites so we don't even know what's being replaced

**Comment by ShizCalev** [comment]
I agree that the medkits and recharger are kinda meh compared to the current ones.

**Comment by ShadowDeath6** [comment]
R&D machinery looks bad imo

**Comment by ike709** [comment]
Rip out the medkits and recharger.

**Comment by DoctoreMad** [comment]
@PKPenguin321 Where's the downvote on the PR? We will kind of need it in the long run someone will point out the votes.

**Comment by Chronitonity** [comment]
Those medkits are awful please

**Comment by WJohn** [comment]
I like parts of it, and don't like other parts.

I DO like that it's aiming for 3/4th
I DON'T like how the medkits look, too thin and vertical, badly placed handle.
I DO like the mining equipment (loaders, redemption machine)
I DON'T like how bright the telecomms equipment is (needs to be darker).

So I dunno, needs some work. Should not merge as-is.

**Comment by GunHog** [comment]
The ones on the second row from the bottom left look plain and similar. Please make them more distinct. While I dislike 3/4, I would be okay with it if the sprite is a vast improvement!

**Comment by Bawhoppen** [comment]
Why did we agree on 3/4ths as what we should be aiming for? I think most people don't like that as a general style, and it looks especially dicks on many things.

**Comment by dannno** [comment]
>I think most people don't like that as a general style, and it looks especially dicks on many things.

Don't care, stupid.

>:)

**Comment by MMMiracles** [comment]
your avatar's face is stupid

**Comment by tortellinitony** [comment]
I'm not a fan of ruining more machinery with these kind of sprites, but at least have the decency to put the sprites stolen from Goonstation in the goon/ folder please?

**Comment by dannno** [comment]
FUCK YOU MIRACLES

**Comment by Expletive** [comment]
>Why did we agree on 3/4ths as what we should be aiming for?
[Cause wjohn likes it apparently.](https://youtu.be/eAgUoSIG3Jo?t=32s)

**Comment by Iamgoofball** [comment]
@tortellinitony 
The OP likely wasn't aware.

@Lexorion 
A lot of these sprites are actually goon sprites, in specific all the kitchen/chemistry related sprites.

**Comment by dannno** [comment]
hmmmm our art director is deciding on what sprites get in??


HMMMMMMMM

**Comment by dannno** [comment]
not a democracy! stinky!

**Comment by WJohn** [comment]
I mean I would appreciate if they were simply refined...

**Comment by dannno** [comment]
I think the medkits need changing as well
I can kind of tell just by looking which machines are probably goon (the blue-grey outlined ones top right) and those can definitely be changed to be more fitting with our stuff, along with tcomms machines stuff (why is it so fucking bright)

**Comment by Iamgoofball** [comment]
@Lexorion 
Keep the goonsprites, they're the good ones.

**Comment by dannno** [comment]
I think they should be revised at least a bit regarding the colors, they are liable to look out of place otherwise

**Comment by Iamgoofball** [comment]
ye

**Comment by Tacolizard** [comment]
I like 3/4ths

**Comment by tortellinitony** [comment]
@Lexorion Can you please make a list of what these all are so I don't have to go through and find them manually to revert them on Hippie?

**Comment by Lexorion** [comment]
Give me a minute,I need to update the image anyway. I reverted the chemical.dmi, telecomms.dmi and storage.dmi (medkits) changes and everything but the microwave from kitchen.dmi, I'll handle those in a different PR.

**Comment by Iamgoofball** [comment]
Why did you remove the goonsprites they were good

**Comment by Lexorion** [comment]
Well this wasn't ment to be a goon port but I'll bring them back (properly) in a different PR. Sorry!

**Comment by Iamgoofball** [comment]
They're  good just readd them and have danno touch them up

**Comment by WJohn** [comment]
Alright, that's a better selection. Even if these could use more refinement, they're passable for now. I do hope you improve these ones, as well as readd the (later improved) sprites you removed.

**Comment by PraiseRatvar** [comment]
IT WAS DO NOT MEEEEEEEEEERGE

**Comment by DoctoreMad** [comment]
>Was DNM
>Merged

Fuck sakes

**Comment by calzilla1** [comment]
OH GOD THESE SPRITE LOOK AWFUL WHY WJOHN WHY

**Comment by GunHog** [comment]
WJ is the one who merged it. WJ was the one who placed the tag on it.

**Comment by WJohn** [comment]
I'm the one who put the DNM tag on it though?

**Comment by TrustyGun** [comment]
I like the washing machine, botany stuff, the plasma/oxygen container, or basically anything that is just a straight 3/4 transformation of the original sprite

I hate the racks, the chargers because they are too flat. I hate the forensic scanner and the powersink, not because of any spriting flaws but because they are basically unrecognizable  as a forensic scanner and powersink

also merge ree

**Comment by Kraseo** [comment]
>OH GOD THESE SPRITE LOOK AWFUL WHY WJOHN WHY

shut up retard

**Comment by DoctoreMad** [comment]
>12 downvotes, 9 upvotes
Merged

Metaclub confirmed

**Comment by WJohn** [comment]
I expect lexorion to touch up most of the sprites in this PR, as well as readd the improved versions of the ones he already removed.

**Comment by TrustyGun** [comment]
lol i like the sprites and i even upvoted the PR, im just voicing my dissatisfaction of some of the sprites

**Comment by dannno** [comment]
Look at them
They really think it's some kind of democracy

ahahahahahahahahhahaha

**Comment by Goodstuff123456** [comment]
These sprites look like shit.

**Comment by Militaires** [comment]
they literally took my book binder sprite that got rejected and used it and didnt let me know rude as fuck

**Comment by Lexorion** [comment]
Not the same despite similarities! (both look like the original anyway so...)

**Comment by Militaires** [comment]
@Lexorion they edited it, i know it's mine because the yellow hazard symbol is exactly where i put it

it wasnt on the original sprite i added that

**Comment by Militaires** [comment]
im cool with that i just wish they had told me so i can feel not wasted effort

**Comment by Militaires** [comment]
also power sink looks like a fidget spinner

**Comment by Lexorion** [comment]
The yellow hazard symbol is ooooold, https://github.com/tgstation/tgstation/blob/12bd728f192f033a1c2e9e0efc8e30dc3d261270/icons/obj/library.dmi is from 2013 and has it but

**Comment by MMMiracles** [comment]
in the future you won't be able to tell the difference between SS13 and something made in RPGmaker

**Comment by Militaires** [comment]
@lexorion oh looks like it's just  a mad coincidence of similarity tho

**Comment by PKPenguin321** [comment]
I actually do like these except for the book binder (sprite we already had was better, more detail), power sink (just a confusing mess of a sprite, shading makes it look weirdly shiny and inconsistent with other sprites), and PACMAN generators (they are mostly solid colors and lack detail, pretty bad sprites by any standard).

I implore @WJohn to look at these three in particular.

**Comment by GunHog** [comment]
The power sink should be reverted, that thing looks more like a bomb or some sort of atmos device than it does a power drain device. 

The modular laptop looks really armored and weird to me.

The mech fab should be swapped for something that looks more "heavy duty". It looks more like some sort of testing machine.

**Comment by WJohn** [comment]
Clearly the laptop was built by alienware and their stupid god damned chunky spiky design bullshit.

I think I'll take a crack at these soon, if lexorion doesn't.

**Comment by PKPenguin321** [comment]
Also the book binder looks gross and the charger has less detail with this perspective, forgot to mention those

**Comment by RocKeD** [comment]
These sprites are SOOO inconsistent. I do not like any of them except for the plasma/oxygen dispenser. TG has amazing sprites that are consistant. I don't think this consistency should be broken. Merge this and the game will look like the clown got hold of it.

**Comment by dannno** [comment]
:)

**Pull request merged**
