### PR TITLE
THIS CONTAINS STAR WARS SPOILERS DON'T OPEN

### PR DESCRIPTION
**Pull request by optimumtact**

### CODE REVIEW

**Comment by optimumtact** [comment]
also checkem

**Comment by Shadowflame909** [comment]
Revolutions all the time people changing the world with crime, violence, hunger or whatever. I find that ridiculous, if not meticulous. I do the best to guard my own premises.

**Comment by Wutnold124** [comment]
really good joke

**Review by Cyberboss — APPROVED** [review]

**Comment by Buggy123** [comment]
>Luke dies at the end of the new starwars
I will murder your internal organs

**Comment by arsserpentarium** [comment]
Starwars, made by disney is shit. It is the main spoiler.

**Comment by ShiggyDiggyDo** [comment]
>watching Star Wars
I bet you even play video games, fucking manchilds

**Comment by nicbn** [comment]
Jar Jar Binks is cloned by Palpatine, who did not die when Vader threw him at the pit, and kills Luke with the force. Sorry for the spoiler

**Comment by HeyBanditoz** [comment]
What the fuck.

**Comment by nicbn** [comment]
Absolute madman

**Comment by optimumtact** [comment]
it's a real pr ignoring the thing

**Comment by nicbn** [comment]
It's a real madman ignoring the thing he actually did

**Comment by Robustin** [comment]
>Make a big event for watching Star Wars:TLJ tonight
>Avoid spoilers like the plague
>See the stupid fucking title edit
>Are you fucking serious? Ugh, maybe its just a shitty joke
>Oranges changes title again to reinforce that its not a joke

Either you're playing 5d troll chess or you can just ship me a replacement priceless experience in exchange for fucking up the one I had planned tonight.

**Comment by optimumtact** [comment]
enjoy your day

**Comment by optimumtact** [comment]
24 hours have elapsed, this pr is now closed

**Comment by ike709** [comment]
The Last Jedi was disappointing anyways.

**Pull request closed without merging**
