### PR TITLE
gives syndimedborg a fucking medigun so it's not useless

### PR DESCRIPTION
**Pull request by ghost**
>BE SYNDIBORG

>SEE DYING OP

>RUSH TO INJECT

'no he has a harsduit'

FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF-

well now you can fucking medigun your operatives instead of begging them to take off their hardsuit in a firefight

oh fuck right i forgot to credit @ShadowDeath6 because he's the only one who knows how to code

:cl: ANGRY CODER
tweak: NT news reports the clandestine criminal organization known as the syndicate may have upgraded one of their illegally stolen cyborg modules with additional healing technology.
/:cl:

### CODE REVIEW

**Comment by MrAlphonzo** [comment]
Are you telling me it was inconvenient for a mediborg to strip an op in the middle of central primary when they're surrounded by heavily armed assistants shooting wildly?

**Comment by AdamElTablawy** [comment]
it was mildly irritating to beg an operative to stop moving so i could remove his hardsuit as he fought with two security officers with a riot shotgun as they shot at him and me before the op saw me removing his hardsuit shouted 'gRIEFING BORG' and killed me

**Comment by GunHog** [comment]
### YOU NEED TO TEST THIS.

The gun has checks that might prevent a cyborg using it correctly, as well as working when stowed. You cannot just plop it into a borg and expect it to work!!

**Comment by AdamElTablawy** [comment]
i asked for help and the help i got was someone sending me an ascii penis so

**Comment by optimumtact** [comment]
They're not here to spoon feed you

**Comment by Anonmare** [comment]
Couldn't you copy the cyborg overrides from something like the cyborg LMG.

Also shouldn't hypo sprays ignore syringe protection

**Comment by AdamElTablawy** [comment]
they should but they don't for some reason

**Comment by Boredone** [comment]
I get the feeling the check isn't working right, the tag to make it ignore protection ONLY shows up in the borghypo file

**Comment by kevinz000** [comment]
or just buff their hypos to be piercing.

**Comment by TehZombehz** [comment]
Both would be nice. Syndi medborgs are rarely used.

**Comment by GunHog** [comment]
So I just tested this myself, my fears were unfounded, the medgun is working just fine.

**Comment by AdamElTablawy** [comment]
albiet it could be made better by changing

if(!mounted && !ishuman(source))

to if(!mounted && !isliving(source))

but it should work anyway

i test my PR's gunhog

**Comment by GunHog** [comment]
As for the hypo bug, I will post a fix for that soon. It will not conflict with yours.

**Comment by ShadowDeath6** [comment]
thanks for crediting the original creator of the pr, adam, appreciate it. 
https://github.com/yogstation13/yogstation/pull/921
https://github.com/yogstation13/yogstation/pull/1144

@GunHog I did actually run into trouble with the ishuman check, I just changed that to isliving. I couldn't find any issues with it, but...

**Comment by jughu** [comment]
Inb4 medibeams get crossed between a medic op and a medic borg

**Comment by optimumtact** [comment]
closed for being a yogpull am I right

**Comment by KingPhilipIII** [comment]
I eagerly await the day medibeams are used as a combat tactic by a pair of syndieborgs and an op dragging around welding fuel to repair them.

**Comment by Fox-McCloud** [comment]
Just make an override on the syndicate hypospray that can pierce `THICKMATERIAL`; regular hyposprays can do this.

**Comment by AnturK** [comment]
Already done in #21811

**Comment by ExcessiveUseOfCobblestone** [comment]
@GunHog is the medgun check still an issue?

**Comment by AdamElTablawy** [comment]
No, it wasn't from the start.

**Comment by AdamElTablawy** [comment]
Tested. No bugs on my side. Shouldn't be an issue. 

If one does turn up I know where to look.

**Pull request merged**
