### PR TITLE
prisoners are now command

### PR DESCRIPTION
**Pull request by ATH1909**
## About The Pull Request

see title

## Why It's Good For The Game

image

## Changelog

:cl: ATHATH
fix: Prisoners are now members of the command department.
/:cl:

### CODE REVIEW

**Comment by JohnFulpWillard** [comment]
SO TRUE!!!

**Comment by Addust** [comment]
El Mao

**Comment by JohnFulpWillard** [comment]
don't forget to change prisoner.ts

**Comment by tralezab** [comment]
oranges you know he know not what he do

**Comment by Bawhoppen** [comment]
really makes you think who *truly* is in charge....

**Comment by Pickle-Coding** [comment]
Closed before 24H, sad.

**Pull request closed without merging**
