### PR TITLE
Gives all non-HoS heads of staff disabler pistols

### PR DESCRIPTION
**Pull request by ghost**
🆑 More Robust Than You
add: All heads of staff, except for the HoS, now spawn with a disabler pistol
/🆑

Why: telebatons aren't that good of a self defense. Mini e-guns seem pretty balanced for this. And if your bad guy is running away, a telebaton won't do shit.

Disabler pistols can only disable, not taze/laser

### CODE REVIEW

**Comment by MoreRobustThanYou** [comment]
Apparently energy pistols were too OP, so... 
capture

**Comment by GunHog** [comment]
What if you placed these in the lockers of each head, instead of if his/her backpack? Both the Captain's and HoP's energy guns are located in their respective lockers.

**Comment by Slignerd** [comment]
As said in the other PR:

- Captain and HoP should start with an energy gun. You should also remove energy guns from their lockers.
- You should add rechargers to CE, CMO and RD offices.

**Comment by Spaceinaba** [comment]
we dont need rechargers every department has a security office

**Comment by Slignerd** [comment]
I don't believe heads of staff have access to the security checkpoints.

**Comment by Spaceinaba** [comment]
only the ones in their departments

**Comment by GunHog** [comment]
Each head does have access to the Security checkpoint and the recharger in his/her respective department, so recharging is not an issue.

**Comment by Spaceinaba** [comment]
ALSO THIS PR IS AN EXCUSE TO ACTUALLY USE THOSE SEXY PISTOL SPRITES

**Comment by OmegaShoots** [comment]
Heads of staff have access to sec checkpoints across the station, it's just brig access level if I'm not mistaken.

**Comment by Xhuis** [comment]
>Upthumbing your own PR
I was considering giving this some more thought, but now I won't!

**Comment by Bawhoppen** [comment]
Two things: Replace the HOP's for one of these. Have them be in the lockers.

Balance-wise who knows how this pan out, so it'll just need to be tested.

**Comment by YakumoChen** [comment]
Heads of staff all have basic security access, allowing them to access the brig and any basic security checkpoint on the station (while including the one in their department, also including any in other departments they can find a way into).

-I don't believe the HoP needs to have their gun changed, HoP is already the second in command and also has very easy to acquire all access, they demand a basic level of protection above the other heads of staff (which is why they also get armor and flash protection)
-Guns in the lockers allow interesting antag things to happen, and lockers are also relatively difficult to break into / creates noise / costs TC (via emag)
-I do not believe the other heads of staff actually need a gun on a basic level. 
-The standard telebaton, while a melee range weapon, is pretty damned powerful and can be used to stunlock and kill any one person. It doesn't let them hold up against more then one target, and doesn't make things super bad in revolution mode (where giving all the heads a gun can turn the scales extremely easily to one side or the other)
-Powercreep

**Comment by Shapsy** [comment]
Telebaton is pretty powerful when used correctly (self defense against single targets, maybe two people, any more and you should be disengaging and calling for help), and it discourages the heads from using it since it's easy to lose it if you don't use it quickly. Disablers seem like they'd encourage more aggro heads, which is eh

**Comment by Tlaltecuhtli** [comment]
this nerfs the greytide

**Comment by CPTANT** [comment]
Because HOPcurity wasn't enough we now want CMOcurity, CEcurity and RDcurity as well?

**Comment by Bawhoppen** [comment]
HOP really should just stay as a bureaucrat, rather than getting their own gun like they're a big deal, which is why it would make sense to give the HOP one of these instead.

**Comment by Potato-Masher** [comment]
Head of Personnel is a big deal; he controls access on the station, manages job openings, and is usually the Captain's second in command after something puts him out of action. This is why he gets the armor and e-gun in his locker for self defence.

**Comment by Potato-Masher** [comment]
Also, I'm pretty sure that _none of the heads have weapons permits on their ID_, which will most likely cause Beepsky to go full Gung ho on the heads when he is set to arrest for unauthorized weapons.

This should be the department's sec guards/Head of Sec'. issue to arrest, not Head-of-Staffcurity. The telebatton is already powerful enough to have a guy stun locked indefinitely.

**Comment by Dorsisdwarf** [comment]
If you're adding these, remove the telebatons theyre supposedly replacing

**Comment by JJRcop** [comment]
I thumbs'd down because mrty upthumbed his own pr again.

**Comment by CosmicScientist** [comment]
Please reconsider balance ramifications.

You're touching the Captain's inventory (who has two guns, one in his locker, the other in his trophy case and then a sword on the side) whilst you're not touching the HoP's (who has one gun in his locker). Both do have the ability to armoury raid and the HoP can become the Captain with little effort.

>Why: telebatons aren't that good of a self defense. Mini e-guns seem pretty balanced for this. And if your bad guy is running away, a telebaton won't do shit.

More weapons to disable crew or antags through windoors and glass windows/airlocks without risking engagement is just power creep. The telebaton is already a death sentence to most players provided there's someone to beat them up whilst the telebaton owner is knocking them down.

A ranged weapon will also encourage heads of staff to forgo their job to pursue antags. Desk man should stay at his desk, not don yellow gloves, a toolbelt and ignore Ian.

I am confused why you think if telebatons are bad at self defence, *you want a weapon that works against a bad guy running away.*

I feel this is also inventory bloat. The touched roles already suffer for being heads with toys.

Could you please explain which antags are causing what problem, why it is a problem and how adding disabler guns is going to change that dynamic for the better. I am also concerned what happens if an antag kills a head and obtains the gun, though I imagine at that point it'll be akin to killing an officer.

**Comment by PKPenguin321** [comment]
>Why: telebatons aren't that good of a self defense.

no, dude

**Comment by Cyberboss** [comment]
I personally think this is terrible and the downvotes agree, any other maintainer is free to disagree

**Pull request closed without merging**
