### PR TITLE
Revert "Rearranges the antagonist panel, cleans it up code-wise and a…

### PR DESCRIPTION
**Pull request by Cyberboss**
Reverts tgstation/tgstation#30255

Doesn't open at all. Ya broke it @Xhuis

### CODE REVIEW

**Comment by Cyberboss** [comment]
```
[16:52:28] Runtime in mind.dm, line 549: Cannot execute null.isloyal().
[16:52:30] Runtime in mind.dm, line 549: Cannot execute null.isloyal().
[16:52:33] Runtime in mind.dm, line 549: Cannot execute null.isloyal().
[16:52:34] Runtime in mind.dm, line 549: Cannot execute null.isloyal().
[16:53:07] Runtime in mind.dm, line 549: Cannot execute null.isloyal().
[16:54:28] Runtime in mind.dm, line 549: Cannot execute null.isloyal().
[16:57:40] Runtime in mind.dm, line 549: Cannot execute null.isloyal().
[16:57:40] Runtime in mind.dm, line 549: Cannot execute null.isloyal().
[16:57:41] Runtime in mind.dm, line 549: Cannot execute null.isloyal().
[16:57:43] Runtime in mind.dm, line 549: Cannot execute null.isloyal().
[16:58:05] Runtime in mind.dm, line 549: Cannot execute null.isloyal().
```

**Comment by KorPhaeron** [comment]
150 hours

**Comment by Xhuis** [comment]
Dang it! That didn't actually occur with me. Sorry about that. I'll see what I can do.

**Comment by Xhuis** [comment]
@Cyberboss Do you know who was using the panel and on what? I'd like to know what caused this.

**Comment by JamieH** [comment]
It works fine on Hippie 🤷‍♂️

**Pull request merged**
