### PR TITLE
extinguisher is now caught up with fastmos.

### PR DESCRIPTION
**Pull request by yackemflam**
:cl: Yackemflam
tweak: extinguishers now spray faster
/:cl:

The fire extinguisher can't fight a fire at all with how fast fire spread vs how long the recharge is.

### CODE REVIEW

**Comment by Shadowlight213** [comment]
nice changelog

**Review by Shadowlight213 — APPROVED** [review]

**Review by Cyberboss — APPROVED** [review]
Who needs jetpacks?

**Comment by Cheridan** [comment]
nerf to slimes :^)

**Comment by ChangelingRain** [comment]
As if slimes were any sort of threat anyway, given that they don't aggro with any speed and can't aggro if you spray them to death.

**Pull request merged**
