### PR TITLE
The Labcoat Resprite

### PR DESCRIPTION
**Pull request by Imaginos16**
## About The Pull Request
Alternative Titles Include: The Labcoatening, or How One Man Put Every Lab Coat In A Washing Machine To Remove Asbestos And Charcoal Grime

In a more serious note however, this PR aims to resprite all the labcoats to be of a better quality than previously. One thing very noticeable is how much cleaner they look! The labcoats are a hybrid between a design from BeeStation and one from Shiptest.
image
(Sometimes I wonder if the sprites themselves or the screenshot construction are more tiresome)

Credits:
@TripleZeta for helping with the colors and shading of the labcoat
@Agameofscones (AKA: Triiodine) for making the shape of the labcoats from PR: [Resprites MedSci uniforms & backpacks, sorts icon files internally #1663](https://github.com/BeeStation/BeeStation-Hornet/pull/1663) on BeeStation

## Why It's Good For The Game
Looks cleaner, more refined, and you will no longer contract mesothelioma from wearing the old labcoats.

## Changelog

:cl: Triiodine, TetraZeta, PositiveEntropy
imageadd: Resprites the labcoats, removing the asbestos and charcoal grime from them!
/:cl:

### CODE REVIEW

**Comment by CRITAWAKETS** [comment]
Not a fan of how these look, especially the robotics labcoat.

I'd say the biggest issue though is the color banding, maybe a little bit of dithering could help in that regard.

**Comment by necromanceranne** [comment]
I had some initial concerns with the robocoat, but I've  come aorund, I think it stands out nicely and does what I was trying to do much better.

They're otherwise overall a sound improvement upon the coats in general. I'm maybe still not a super big fan of the double parallel back stripes only because it looks like the coat is open at the back to a white shirt to me. Maybe that's just me. Not a major issue all the same.

**Comment by Colovorat** [comment]
sorry if i mess up some words, but why labcoats are so narrow on waist???? isn't it's kind of clothing that should be sitting pretty free on a person? 
plus personally i don't like how dark are edges on these suits
image

**Comment by cacogen** [comment]
nah looks worse

**Comment by Dorsisdwarf** [comment]
Agreed, they remind me of our previous labcoat sprites (which is probbably what theyre derived from)

**Comment by Valorium-RB** [comment]
Any Shiptest-derived content gets a vote of confidence from me.

**Comment by Mosslick** [comment]
"One thing very noticeable is how much cleaner they look!"
Yeah no

**Comment by JohnFulpWillard** [comment]
holy shit based

**Comment by cacogen** [comment]
why does the person in charge of sprites have such bad taste

**Comment by SethLafuente** [comment]
I was hopping so bad this didn't get merged because to be honest they look like shit

**Comment by necromanceranne** [comment]
Already talking with imaginos about redoing them. I found them to be too flat ingame as I initially feared.

**Pull request merged**
