### PR TITLE
Adds de_dust2 to SS13.

### PR DESCRIPTION
**Pull request by Iamgoofball**
The most popular map.

### CODE REVIEW

**Comment by Ergovisavi** [comment]
Please ensure that the default map vote is for de_dust2, thanks

**Comment by Iamgoofball** [comment]
It is with this.

**Comment by Armhulen** [comment]
goofball can you turn the CTF into de_dust2

**Review by Cyberboss — APPROVED** [review]

**Comment by GunHog** [comment]
You have greatly disappointed me, Goof. I was expecting an actual new map :disappointed:

**Comment by optimumtact** [comment]
this is the truth and the best map I support it :heart:

**Comment by Cheridan** [comment]
meme pr

**Pull request closed without merging**
