### PR TITLE
Revert "hotspot_expose() will now heat the turf's air if it fails to create a hotspot"

### PR DESCRIPTION
**Pull request by Winterous**
https://github.com/tgstation/tgstation/pull/37426

This causes way too many problems in its current state, simply using an inducer heats a room up enough to burn you.

The idea is fine, but this is something that needs to be very carefully managed, and should probably operate on a whitelist system for what will heat the air. A great many theoretical heat sources in the game would produce utterly negligible amounts of heat, like lit cigarettes, lighters, and sparks.

Even more powerful flames like welders wouldn't heat the atmosphere much, they're just too small. A bonfire would put out a lot of heat, of course, but that's about the only thing that really suits this idea.

### CODE REVIEW

**Comment by Cyberboss** [comment]
We knew this would happen, but it's not a reason to revert it imo. Heat has always been out of balance in this game because (like power) it has barely any consequences. The action to be taken should be tweaking the offending items to acceptable levels instead,

**Comment by zxaber** [comment]
Do what it takes, but please fix it. I spent a round with this as AI last night, and had to start panic-syphoning main hallways because they were constantly overpressurized and overheated. Meta's robotics lab also, for whatever reason, is constantly harmful to stand in without a hardsuit; could be the occasional welding to patch up borgs.

Maybe all crew should just be issued hardsuits, if the station's atmosphere is going to be harmful by default.

**Comment by Winterous** [comment]
Alright, fair enough. I guess the appropriate steps, then, would be to implement a scale modifier. Default it to something low, and have larger values for anything appropriate. And any temperature changes resulting from this exposure would be simply multiplied by that factor.

**Comment by Mickyan** [comment]
Heat producing items should have a set temperature cap they can reach to simulate heat dissipating at a faster rate than they can produce it (i.e. no matter how many lighters you stack in one room they'll never make the atmosphere hot enough to burn you, whereas too many bonfires might but still won't get as hot as a plasma fire)

Somewhat unrelated but that's also an issue with reagents, using a lighter you can make beakers hotter than the sun

**Comment by DaxDupont** [comment]
dreamseeker_2018-06-01_18-37-23
lmao it's real

**Comment by DaxDupont** [comment]
@deathride58 lmao

**Comment by 81Denton** [comment]
Did that PR not get testmerged? I said that I tested it, but that was only for edge cases like „will everyone entering the library die if Urist McTide builds 10 camp fires inside it“

**Comment by Winterous** [comment]
Thing is, Mickyan, you're in an enclosed environment floating in space, heat doesn't just dissipate, it has to go somewhere, so if an item is producing heat, that heat will continue to build. The cap is how hot the item is, which is usually 1,000+ degrees.

From my fucking around I found that welder on the floor don't produce that much heat, but bonfires do. Sparks seem to be by far the main issue.

From rummaging in the code I think I've found why they're so crazy; sparks seems do do hotspot_expose like, when they spawn, and every time they move; in addition, their exposed volume is 100, compared to the 50 of the welder for example, and there's like 5 of them spawned at once.

Sparks need to very simply NOT PRODUCE HEAT from this system, sparks are minuscule flecks of hot metal, they have almost no energy to impart, the only thing they can ignite is fuel vapours almost. If we make this one change, I think that there will be almost no issues with this system. Unfortunately I only have a general idea of how to fix this, but I'll throw it together in a new PR.

**Comment by Cyberboss** [comment]
Your efforts are appreciated

**Comment by Winterous** [comment]
I'm stuggling more with how the fuck to manipulate my fork of the code than with anything, this interface is really confusing.

**Comment by Cyberboss** [comment]
Check the readme for a web link to the coderbus IRC channel. I'm currently
away from my desk at lunch but I'm sure someone can help you out there. If
not I'll be back in an hour

**Comment by 81Denton** [comment]
@Winterous The git web interface is notoriously shitty; if you're new to git the free version of Gitkraken has a pretty intuitive interface.

**Comment by Winterous** [comment]
GOOD NEWS EVERYONE, I SOLVED THE PROBLEM.
BY DELETING MY FORK, WOW SURE WOULD BE NICE IF THERE WAS FUNCTIONALITY TO UNDO CHANGES WITHOUT HAVING TO DOWNLOAD SOME PROGRAM MY AUTISM IS UNCOMFORTABLE WITH!

**Comment by optimumtact** [comment]
you're gonna go short kid

**Comment by deathride58** [comment]
Dude just tweak the values for things that call hotspot_expose(). The maximum heat something can produce is capped to the first argument of the var.

**Comment by msgerbs** [comment]
Trying to dehack a shocked door, with insulated gloves, almost killed me. Seriously why isn't this merged yet?

**Comment by deathride58** [comment]
@msgerbs #38232 will resolve that issue. This PR isn't merged yet because this codebase has a thing known as standards. Y'know, those restrictions that stop the place from becoming a warzone.

**Comment by iskyp** [comment]
this was a bad change and keeping it is a bad idea, +1

**Comment by Winterous** [comment]
As explained on your new PR, while I approve of balancing the heating power of things, I think it's important for sparks to not have any heating effect at all, outside of ignition.

**Comment by subject217** [comment]
This PR was merged in a horrific state. It should be reverted until a fixed version can be merged. THAT is the shameful degradation of standards, not this revert PR.

**Comment by RandomMarine** [comment]
If this is a feature that's going to exist in the future then there needs to be a ubiquitous solution for dealing with heat buildup that also doesn't have a strong affect against fires.

And then what's gained from it? An assload more atmos processing?

**Comment by msgerbs** [comment]
I mean, space heaters are that solution, but the problem is that it's a massive pain in the ass to drag space heaters everywhere, and that's really the extent of the gameplay created. I think if atmos equipment actually slowly cycled the air out like a real air handling system does it would make the heat buildup much more tolerable, or if scrubbers and vents simply acted like heaters and slowly brought the air around them to 20C. That way small heat buildups can be dealt with automatically and only large buildups of heat require manual intervention.

**Pull request merged**
