### PR TITLE
Shield blocking stuff

### LINKED ISSUE #6246: Wooden barricades do not block tableclimbing
How to reproduce: Place a barricade on top of a table tile (in my round, admins did this, because honk). Attempt to climb the table. Watch yourself phase through the goddamned barricade.

Why this is bad: immulsions

I haven't tested this with windows or other kinds of barricade.

### LINKED ISSUE #6469: Misleading tableclimbing message when failing to climb
What happened: Attempted to climb on table with someone already standing on it. Because of this I was not actually able to climb the table, but still received these messages:

You start climbing onto the wooden table.
You climb onto the wooden table.

And also received the accompanying short stun.

Why this is bad: Misleading.

NOTE: This also happens when blocked due to shutters.

### LINKED ISSUE #8633: Energy Shields are useless vs xenos
Riot shields can block tackles but these can't? Lame

### PR DESCRIPTION
**Pull request by phil235**
- You now have a chance to block things thrown at you with a riot/energy shield (defaults at 80% for thrown items) or  the teleport armor (50%), including xeno leap(50% chance). Fixes #8633. Will conflict with #11677 @xxalpha

### CODE REVIEW

**Comment by Steelpoint** [comment]
I think it should be about 80% block rate, it should be reliable in a given situation but not a guarantee to block a leap so you don't want to rush in blindly.

**Comment by xxalpha** [comment]
No rates.

**Comment by WJohn** [comment]
I too want 100% block chance from thrown items (including aliens) so that these things are very reliable. You're sacrificing an entire hand here, and these things are few and far between, they should absolutely be reliable in a fight.

**Comment by Durkel** [comment]
40% is fine, Anything higher is just silly.

**Comment by xxalpha** [comment]
It practically covers your entire body, it should easily block thrown things. 40% is too low, anything lower than 100% is too low.

**Comment by GunHog** [comment]
Shields should block Xeno leap all the time. Xenos can easily counter by leaping near the target and tackling. Throwing stuff at the RD to force him to tele is hilarious.

**Comment by chimerasable** [comment]
I hate chunks off features.  Wish each feature/fix had it's own pull

**Comment by phil235** [comment]
@chimerasable you're right, I moved the fixes to another PR, so this PR is now only shield blocking stuff.

**Comment by xxalpha** [comment]
Direction specific block is not RNG, having direction specific block and no block chance would be zero RNG.

Like it is now, it's just another feature ruined by RNG. "If I bring a shield I can block attacks, MAYBE". Throw preparation out the window, it's all down to luck.

**Comment by Jalleo** [comment]
@xxalpha when it comes to byind and lag it is too rng

**Comment by blobbernaut** [comment]
direction specific -> rng
actual rng -> not rng 

???

**Comment by Miauw62** [comment]
direction specific block is RNG if you are running away from somebody but clicking in their direction to maybe block a few shots.

**Comment by Cheridan** [comment]
This is an improvement to the code as-is, directional blocking is its own can of worms and I don't think it's a very good idea to be honest.

**Pull request merged**
