### PR TITLE
Replaces the radiation storm overlay with a less visible effect

### PR DESCRIPTION
**Pull request by NoxVS**
## About The Pull Request

Radiation storms are no longer just a mass of green that covers your screen, instead being green particles that trickle down. Previously we just had a green ash storm. Please ignore the fact that this is actually also just a green ash storm.

[Example](https://cdn.discordapp.com/attachments/384235877615927297/673738689763082250/Screenshot_23.png)

## Why It's Good For The Game

No more giant green square from radiation storms. I mean it was literally just a green ash storm.

## Changelog
:cl:
imageadd: added a new radiation storm effect to replace the green ashstorm
/:cl:

### CODE REVIEW

**Comment by NoxVS** [comment]
Honestly while I like this better than the original "radiation storm" we had, I still am not entirely happy with how it turned out. Any feedback?

**Comment by itseasytosee** [comment]
Could be better but I don't have any ideas.

**Comment by NoxVS** [comment]
It looked better when making it. It was a bit brighter but the lower opacity of it in game makes it darker than I was wanting

**Comment by zxaber** [comment]
I think the existing one fits better. Despite the ceiling memes, the station *is* supposed to be sealed on the top too. Plus, it makes it easier to quickly tell safe areas from not-safe.

**Comment by NoxVS** [comment]
I just hated the massive green effect covering your entire screen. And all just one color, obscured everything under it. You think an effect that takes up the entire tile would be better?

**Comment by Whoneedspacee** [comment]
I personally like the current effect, it's more intimidating and it's not something that you'd see normally so you know something is up. What you have here looks like some sparkles or some leaked atmospherics gas or something, not like an actually damaging radiation effect. When your entire screen is covered with green waves you know something's fucked.

**Comment by NoxVS** [comment]
Screenshot (25)
How does something more like this look?

**Comment by NoxVS** [comment]
Eh, I cant really get it to look good. My problem with it is its too blinding, to the point you can't really see anything else. I make it too small and it is harder to notice, make it lighter and it doesn't look good. I dont like what we have now but I dont think I can fix it well

**Comment by zxaber** [comment]
You could make it a pulse effect, so that there are moments where it's obvious, and moments where you can through it.

**Pull request closed without merging**
