### PR TITLE
Fixes dummy humans having a Life

### PR DESCRIPTION
**Pull request by Cyberboss**

### CODE REVIEW

**Comment by coiax** [comment]
What is a dummy human

**Comment by RemieRichards** [comment]
just a human that spawns with GODMODE.

**Comment by coiax** [comment]
And no Life() apparently.

**Comment by Cyberboss** [comment]
It's used for mugshots and such

**Comment by Iamgoofball** [comment]
*fixes coders

**Comment by RandomMarine** [comment]
Get a life()

**Comment by AnturK** [comment]
Why is this a problem ?

**Comment by Cyberboss** [comment]
It will runtime in Life because it's missing a heart or something

**Pull request merged**
