### PR TITLE
Makes it so xenos make a hissing sound with the *hiss emote.

### PR DESCRIPTION
**Pull request by Razoozle**
I just found it strange that xenos made a sound for *roar but not *hiss so I made them make a hissing sound. :)

### CODE REVIEW

**Comment by phil235** [comment]
:+1:

**Comment by GunHog** [comment]
I am sure @WJohn would enjoy this.

**Comment by Ultimate-Chimera** [comment]
I think i would enjoy it more. <3

**Comment by WJohn** [comment]
Basically a fix.

Also :+1:

**Comment by Ultimate-Chimera** [comment]
I love xenos too @GunHog

**Comment by Ultimate-Chimera** [comment]
Does the "or" operator work in byond code, because I could add the other hissing sounds minus the roar and deathgasp one. But in all honesty, hiss3.ogg sounds better for this emote.

**Comment by WJohn** [comment]
Hell if I know, I only sprite and map. I can't code for shit.

I'm only a maintainer because I'm the art director.

**Comment by Ultimate-Chimera** [comment]
Oh, thought you were a code maintainer.

**Comment by Dorsisdwarf** [comment]
Or operator is || in dm, if I'm not misunderstanding you.

**Comment by Ultimate-Chimera** [comment]
Oh, I can look later. I might leave it as is. Thanks.

**Comment by WJohn** [comment]
If you want to contact me, the easiest and most responsive way is to talk to me on IRC. I'm on Rizon #coderbus pretty much all day.

**Comment by Ultimate-Chimera** [comment]
Cool, never used IRC before but I will. Oh, it actually looks more like C++ another thing I plan on learning.

**Pull request merged**
