### PR TITLE
Adds a holodeck to Birdshot Station

### PR DESCRIPTION
**Pull request by TheVekter**
## About The Pull Request
Nanotrasen has heard your requests and dispatched a Porta-Jump Optional Holodeck Nexus (Porta-JOHN) to Birdshot Station!

image
StrongDMM screenshot.

image
In-game screenshot

Not the cleanest landing, but it's nothing you folks can't fix up. Props to zxaber for the genius idea of making it a shuttle Centcom just flew into the side of the station.

This is north of Crew Facilities. I feel bad about having to take out the little cave that was there, but this was really the only place that would be publicly accessible, wouldn't require crawling through maints, and would work with how holodecks work. Tested multiple times, appears to be working just fine as far as generating holodeck tiles.

## Why It's Good For The Game
Feature parity good, every map should have roughly the same things available, at least in a broad, general sense.

## Changelog
:cl: Vekter
add: Added a holodeck to Birdshot Station. It can be reached via the Crew Facilities hallway.
/:cl:

### CODE REVIEW

**Comment by TheVekter** [comment]
I'm gonna draft this until I hear from Zytolg if they want any changes made.

**Comment by mc-oofert** [comment]
that is so horrible the doors arent even centered and the room prior to the holodeck is otherwise bland

**Comment by TheVekter** [comment]
> that is so horrible the doors arent even centered and the room prior to the holodeck is otherwise bland

The doors can't be centered unless I make the room the full height of the holodeck, which I can do, but there's only so much I can put in that room and it will suffer the same issue as the room you already dislike.

**Comment by mc-oofert** [comment]
that is the same screenshot

**Comment by TheVekter** [comment]
> that is the same screenshot

It is literally not.

image

**Comment by mc-oofert** [comment]
image
anyway id suggest moving the doors like this or any other way that they arent just vaguely stuck to the north side of the foyer

also you could move the bench west and add some tables or vendors or closets or something

**Comment by TheVekter** [comment]
> anyway id suggest moving the doors like this or any other way that they arent just vaguely stuck to the north side of the foyer
> 
> also you could move the bench west and add some tables or vendors or closets or something

Okay, you meant the room with the holodeck console in it. Yeah, I'll spruce that up a little in the morning. As for the doors, I literally cannot do that.

image

There are holodeck programs that rely on the doors being in that exact place.

**Comment by mc-oofert** [comment]
> > anyway id suggest moving the doors like this or any other way that they arent just vaguely stuck to the north side of the foyer
> > also you could move the bench west and add some tables or vendors or closets or something
> 
> Okay, you meant the room with the holodeck console in it. Yeah, I'll spruce that up a little in the morning. As for the doors, I literally cannot do that.
> 
> image
> 
> There are holodeck programs that rely on the doors being in that exact place.

fair

**Comment by TheVekter** [comment]
Okay, updated. Added a bunch of stuff to the foyer.

**Comment by carlarctg** [comment]
Birdshot is meant to be a dumpster. I think it makes sense that it has no deck

**Comment by TheVekter** [comment]
> Birdshot is meant to be a dumpster. I think it makes sense that it has no deck

I'm all for us leaning on the concept of Birdshot being an old, decrepit piece of junk, but we have to balance that with what works best for players as well. There's certain aspects of a station that you expect to be on every map, hence "feature parity". One of the biggest non-engineering complaints I heard was that Birdshot doesn't have a holodeck, so I think it's better that we add one.

**Comment by BlueMemesauce** [comment]
The emergency holdout program also spawns with a wall of foam on the left side, so you wouldn't be able to use it without breaking down the walls
not that its really that important of a program or ever used

**Comment by TheVekter** [comment]
> The emergency holdout program also spawns with a wall of foam on the left side, so you wouldn't be able to use it without breaking down the walls not that its really that important of a program or ever used

There's nowhere else for me to put the damn thing on this station and that program is so not used that I didn't know it existed so fuck it

**Comment by TheVekter** [comment]
Okay, I made a few changes based on Zytolg's feedback. Mostly they just wanted me to remove a few windows and reintroduce some of the rock that I took out to keep the whole "built into an asteroid" aesthetic. We're good to go on this pending any maintainer feedback.

**Comment by TheVekter** [comment]
> > Birdshot is meant to be a dumpster. I think it makes sense that it has no deck
> 
> As per above, you should add some thrusters to the top and damaged walls below, as if a holodeck was just flown in and jamed into the station.

That is extremely funny, let me ask Zytolg first

**Comment by TheVekter** [comment]
alright boys we're good

**Review by Maurukas — APPROVED** [review]
Excellent addition. Fits the station very well.

**Pull request merged**
