### PR TITLE
Overlays System Update [GIANT HATS!]

### PR DESCRIPTION
**Pull request by RemieRichards**
## Code Changes:
- Expanded my large-inhands system to a large-anything-you-can-wear system
- Added a system to allow items to put overlays on their inhand image, allowing for overlays on overlays (so meta), this allows for things like inhand gun ammo counters (in a nicer way) and I also moved the blood overlays icons to this system, since they used to hardcode themselves into the overlays list
- Moved almost all of the `update_icons()` logic into one central `build_worn_icon()` proc, that removes a LOT of copy paste from `update_icons()`
- Drones now use `build_worn_icon()` so they get all the benefits of `alternate_worn_layer`, `alternate_worn_icon`, large inhands, etc. with no copypaste
- added `worn_x_dimension` and `worn_y_dimension` so that they can have seperate values to `inhand_x_dimension` (eg: a 32x32 back sprite and a 96x96 inhands)
- fixed an ancient (2012) typo that made uniforms try and make an icon out of the HUMAN's icon state, no idea what this has been breaking for 3 years, but there you go
## Changes for players:
- THIS SYSTEM LETS YOU HAVE OBNOXIOUSLY LARGE CLOWN SHOES, EXTRAVAGANTLY LARGE HATS, GLOVES BIGGER THAN YOUR FACE, etc.

### CODE REVIEW

**Comment by WJohn** [comment]
AW YE

**Comment by PKPenguin321** [comment]
massive strapons when

**Comment by TheDreamweaver** [comment]
Now @PKPenguin321 , now...

**Comment by Iamgoofball** [comment]
# does this mean i can have hats stacked on top of other hats

**Comment by RemieRichards** [comment]
@Iamgoofball no but you can have a hat the size of the universe.

**Comment by Iamgoofball** [comment]
# :-1: until i can get my towering pillar of hats

**Comment by RemieRichards** [comment]
@Iamgoofball oh actually!
if you give hats a "hat" var, you can recursively put a hat in the hat var, and have their worn_overlays() proc draw their hat var a few pixels above them, then you CAN have a hat stack!

**Comment by Iamgoofball** [comment]
# :+1: MERGE WHEN

**Comment by Anonus** [comment]
RAISE HAT LEVEL

**Comment by RemieRichards** [comment]
hats

**Comment by PKPenguin321** [comment]
support for this PR just increased x10,000

**Comment by GunHog** [comment]
STACK DRONES :+1:

**Comment by CosmicScientist** [comment]
:+1:

**Comment by JJRcop** [comment]
This screenshot appears to not be in the PR at the moment, might want to hold off on those +1's until it definitely is in.

**Comment by Fox-McCloud** [comment]
@RemieRichards 

Remie, Remie why!?

Hahahah.

**Comment by optimumtact** [comment]
>Added a system to allow items to put overlays on their inhand image, allowing for overlays on overlays (so meta), this allows for things like inhand gun ammo counters (in a nicer way) and I also moved the blood overlays icons to this system, since they used to hardcode themselves into the overlays list

Thats nice as hell

**Comment by SkowronX** [comment]
Cool

**Comment by RemieRichards** [comment]
@JJRcop it's just a test case, I can add it IF I can get some other maintainers to agree that hats having a hat var is acceptable, and even then it'd probably only be for badmins.

@Fox-McCloud Hats, that is all.

@optimumtact glad you like it, the original goal of this entire refactor was just a simple little overlay overlay system, it just kinda scope creeped into a big cleanup and expanding some of my other features lol.

**Comment by RemieRichards** [comment]
Ok, that's everything:
* Removed the extra ```center_image()``` argument as Byond already handles this internal
* Fixed some dodgy logic with caching female uniform sprites

Can be merged at 24hrs.

**Comment by Dorsisdwarf** [comment]
we tf2 now

**Comment by WJohn** [comment]
You know, it's PRs like this that are making me more and more tempted to add unusual effects to hats. And also golden hats. And really just more hats in general.

You monster.

**Comment by Jalleo** [comment]
@Wjohn when we can put hats on xenos.

**Comment by RemieRichards** [comment]
@Jalleo via badminnery... Xenos already can wear hats.
I had to move hats to carbon when I gave monkey's hats, and Xenos are also carbon.

**Pull request merged**
