### PR TITLE
Adds The Geisha Outfit

### PR DESCRIPTION
**Pull request by ExcessiveUseOfCobblestone**
:cl: Cobby
add: Adds the Geisha suit. Space Ninja Senpai not included!
/:cl:

Pictures soon [tm]

### CODE REVIEW

**Comment by ExcessiveUseOfCobblestone** [comment]
WHY

**Comment by Armhulen** [comment]
PICTURES PICTURES PICTURES

**Comment by Nienhaus** [comment]
I got you Cobble.
hxb5dcl

**Comment by Tacolizard** [comment]
SOYOUWANTOBEAGEEEEEEIIIIISHAAAAAA?????

**Comment by Nienhaus** [comment]
Actually looking at the sprite again I do like it.

**Comment by ExcessiveUseOfCobblestone** [comment]
they've been updated slightly to have a more appealing collar

**Pull request closed without merging**
