### PR TITLE
Removes that stupid fucking sound from pais

### PR DESCRIPTION
**Pull request by MrsTonedOne**
AHHHHH I CAN HEAR IT IN MY DREAMS

### CODE REVIEW

**Comment by GunHog** [comment]
I like the sound! It is so cheerful and cute!

**Comment by anconfuzedrock** [comment]
fuck you gunhog

**Comment by optimumtact** [comment]
I let that slip through - that's my bad, alerts to the ghost players should never ever make a sound.

**Comment by francinum** [comment]
Remove the sound from the cloning alert and defib alter.

**Comment by GunHog** [comment]
>Remove the sound from the cloning alert and defib alter.

No. If I am not watching the screen because I am not expecting to be cloned, that is the only way I will know!

**Comment by francinum** [comment]
Then add something similar to DNR, which shuts it up.

**Comment by Mervill** [comment]
> I let that slip through - that's my bad, alerts to the ghost players should never ever make a sound.

Do you mean just pAI? A sound plays for ghosts when a drone shell is created, for example.

**Comment by XDTM** [comment]
Every alert that asks for ghost action has a sound already, @optimumtact

**Comment by Kromgar** [comment]
Well the fucking pai one is fucking annoying i havnt noticed it for the others

**Comment by JJRcop** [comment]
The other ones are a simple ping, the same one when any of the heads makes an announcement.

**Comment by Haevacht** [comment]
One of them is a weird ghostly noise. THink it's golem shell?

**Pull request merged**
