### PR TITLE
Small Box things that were annoying me

### LINKED ISSUE #11502: Incinerator Output Pump is unpowered
The pump leading to space from the incinerator/turbine is turned off when the game starts (I assume it's supposed to default to on, IIRC), and attempting to turn it on gives a message like "the pump seems unpowered." This makes it unusable. Bug has been in for a while.

### LINKED ISSUE #12624: Box station warden desk has a leftover tac shutter button
@steelpoint

### PR DESCRIPTION
**Pull request by lzimann**
- Adds the correct area for Turbine Area(the part with pipes in space, they were not powered since the area was space, now it will use the turbine APC for power).
- Removes the extra armory shutter button below the shutter itself.
- Also adding myself to admins.txt

Also fixes #12624 and fixes #11502

### CODE REVIEW

**Comment by TehZombehz** [comment]
I noticed your PR. :)

**Comment by KorPhaeron** [comment]
fixes #12624

**Comment by Anonus** [comment]
That's a different issue to what's getting fixed, there's a button on the ARMORY desk that's hidden under the shutter most of the time and this removes that.

**Comment by lzimann** [comment]
@KorPhaeron Ok, I removed that button too now. I didn't notice it before, since I barely play warden.

**Comment by francinum** [comment]
@lzimann Add Fixes #12624 to the OP to autoclose the issue on merge.

**Comment by joonoro** [comment]
Fixes #11502

**Pull request merged**
