### PR TITLE
Alien weeds no longer smooth with walls

### PR DESCRIPTION
**Pull request by ChangelingRain**
dank

### CODE REVIEW

**Comment by RemieRichards** [comment]
Wasn't this deliberate? to make it look like they spread on the inside of walls (ala the movies)?

**Comment by KorPhaeron** [comment]
Guess WJ can decide

**Comment by Zilenan91** [comment]
What did it look like before this? Nothing really jumps out for me here

**Comment by Fox-McCloud** [comment]
What did it look like before this? Nothing really jumps out for me here you know how there's edges when it's spreading on the floor? The edges protruded onto the walls.

**Comment by WJohn** [comment]
I thought weeds were changed so it works like tables, rather than like mineral walls. If so, it shouldn't be able to clip onto other tiles.

I personally like it when it smoothly connects with walls, as long as it isn't spilling over on top of them.

**Comment by KorPhaeron** [comment]
>I personally like it when it smoothly connects with walls

Okay unless I misunderstood this the art director says no sorry, take it up with him when he's back in a couple of days

**Pull request closed without merging**
