### PR TITLE
Massively lowers the alpha of the phantom screen object for equipping

### PR DESCRIPTION
**Pull request by MrsTonedOne**
Should fix some of the confusion

closes #39819

### CODE REVIEW

**Review by Cyberboss — APPROVED** [review]

**Comment by BeeSting12** [comment]
Make it a preference

**Comment by Iamgoofball** [comment]
@BeeSting12 No. Stop throwing a hissy fit whenever a feature you don't like is added. It's not your call. Become a maintainer if you want a say.

**Comment by Stickymayhem** [comment]
@Iamgoofball What is the downside of making it a preference when a large portion of the playerbase doesn't want it and definitely doesn't need it?

**Comment by Iamgoofball** [comment]
@Stickymayhem Get over yourself lmao stop demanding configs for everything

**Comment by ExcessiveUseOfCobblestone** [comment]
What's the purpose of the feature?

**Comment by Stickymayhem** [comment]
@Iamgoofball I have literally never asked for a config before you are literally a worthless troll at this point.

**Comment by ExcessiveUseOfCobblestone** [comment]
@Stickymayhem should have used your non-admin account.

**Comment by Stickymayhem** [comment]
@ExcessiveUseOfCobblestone Do you think he was born smooth-brained or did the wrinkles recede along with his ability to code anything decent?

**Comment by subject217** [comment]
>What's the purpose of the feature? Why was it added?
The intent is to make it easier for new players to understand what items go in which slots.

**Comment by ExcessiveUseOfCobblestone** [comment]
If you have to scroll through every bit for a delay equivalent to a click then how is that better than just clicking on each part lol

**Comment by Iamgoofball** [comment]
@Stickymayhem configs == preferences

**Comment by BeeSting12** [comment]
@Iamgoofball Preferences are for the player, config is server side.

ie Whether players can be a catgirl is a serverside config, and whether your character is a catgirl is your preferences.

**Comment by optimumtact** [comment]
acceptable

**Comment by optimumtact** [comment]
The downside of preferences is we end up carrying code paths that are used by only old players who refuse to adapt to a minor interface change.

**Comment by ExcessiveUseOfCobblestone** [comment]
True, but for this feature in particular it doesn't help ANY "tier" of player anymore than the click-test, apart from the non-practical difference of "one less click" due to the delay.

MSO's fix should not close the pull unless it also cuts down on the delay. The alpha level wasn't even mentioned in the OP of the pull he's wanting to close, and only as a "oh and also" issue brought up when asked to be more descriptive about why the feature was not good.

Hell, I think an examine text telling you the various places you can wear the item given your current outfit in the same format as the construction/deconstruction cues would add more value than this feature in its current state.

**Comment by optimumtact** [comment]
It helps people who are new to the game, and I care about them far more than I care about anyone else here.

It being slow is a problem but it should be trivially fixable.

**Comment by ExcessiveUseOfCobblestone** [comment]
Not in it's current state, nor does this PR combat that hence why I think the `closes #` should be removed.

**Comment by optimumtact** [comment]
I've already closed those PR's myself

**Comment by ExcessiveUseOfCobblestone** [comment]
All is well then

**Comment by ExcessiveUseOfCobblestone** [comment]
Thanks, I have removed the irrelevant posts :^)

**Comment by Jared-Fogle** [comment]
Pic?

**Comment by Iamgoofball** [comment]
@BeeSting12 a headmin throwing a hissy fit and disabling something they dont like is at its core the same as a player throwing a hissy fit and disabling something they dont like

**Comment by ExcessiveUseOfCobblestone** [comment]
real admins meteor when they don't get what they want

**Pull request closed without merging**
