### PR TITLE
Removes deprecated arrivals, cargo etc shuttles

### PR DESCRIPTION
**Pull request by TiviPlus**
## About The Pull Request

Specifically:
arrivals donut
arrivals kilo
cargo birdboat
cargo kilo
labor kilo
mining kilo
mining_large
cere whiteship
donut whiteship
kilo whiteship
Aux_base_small (was this ever used)

## Why It's Good For The Game

These cant even be gotten anymore due to their respective maps being removed so

## Changelog
:cl:
del: Removed unused specialized station shuttles
/:cl:

### CODE REVIEW

**Comment by Spookuni** [comment]
The unused whiteships can still be pulled in via admin shuttle manipulation, not sure if it's great to be reducing the availability of cool whiteship trades by removing them.

**Comment by Dennok** [comment]
For whiteships , i think, need make random whiteships , instead of hardcoded for maps.
I hate some maps because it whiteships is uncool.

**Comment by Cartographer-D** [comment]
Having these in as tools for inspiration and copying is great for a mapper. I just used the kilo cargo shuttle the other day. The real question is the resources they're currently taking up being in the files. If they aren't taking up much, leave them in.

**Comment by 81Denton** [comment]
Honestly, I prefer leaving these in for admin events as well as inspiration for mappers. Unless I'm wrong, removing these shouldn't make the RSC download noticably smaller either.

**Pull request closed without merging**
