### PR TITLE
Bulletproof helmets seclight attachment

### PR DESCRIPTION
**Pull request by Isratosh**
:cl: Isratosh
rscadd: Security flashlights can now be attached to the bulletproof helmets.
/:cl:

### CODE REVIEW

**Comment by GunHog** [comment]
Pic please?

**Comment by Supermichael777** [comment]
its overlays so probably just the bulletproof sprite with the lights sprite.
Anyway at this point you may as well move canflashlight to the base helmet. Not like flashlights are a major part of any game-modes balance...... oh wait.

**Comment by GunHog** [comment]
Well, I hope you **tested** it...

**Comment by Isratosh** [comment]
There's gotta be icons for every helmet with a flashlight attached if you want to add can_flashlight to every helmet, else it won't show up at all. Unless you change the update_icon to just not change the icon_state if there isn't a flashlight one available. I included some sprites for the riot helmet flashlight, but the riot helmet is a bit different in the fact that it has two states that can be toggled. Visor up or down, and I'm not exactly sure where I'd go with the code to get it to to work with the flashlight sprites. I'm not really much of a coder, so if anybody wants to throw some code at me I can make it work for the riot helmet as well.

**Comment by Supermichael777** [comment]
Holy shit this actually swaps sprites. Why the fuck doesn't this use overlays?

**Comment by Isratosh** [comment]
No idea, I just wanted to add a bit more functionality for the flashlight thing. I don't have a clue how to mess with the overlays, so again if anybody wants to throw some code at me or make their own PR I'll gladly modify or close mine.

**Comment by Isratosh** [comment]
Bulletproof helmet flashlights

**Comment by Cheridan** [comment]
powercreep

**Comment by KazeEspada** [comment]
I just put the flashlight on my gun anyways, and everyone has a PDA. Hell, if its slings, I have two flashlights, a hardsuit helm, a flare, and my pda just so I can become the sun.

**Comment by Steelpoint** [comment]
This is fine, there's no real powercreep here since not only do base helmets already do this but most energy based weapons like teasers allow for attachements.

**Comment by Supermichael777** [comment]
actually only taser and hos gun take lights

**Comment by TheNightingale** [comment]
The standard energy gun, as well as pulse carbines (used by Sec ERTs) accept flashlights, not just tasers and the HoS's gun. The only non-R&D energy weapon that doesn't is the laser gun, I think.

**Comment by Cheridan** [comment]
dunc i was joking this isn't a balance issue c'mon

**Comment by duncathan** [comment]
oops

**Pull request merged**
