### PR TITLE
removes an unused var from radio code

### PR DESCRIPTION
**Pull request by ghost**
ez gbp into my gbp bucket pls =>   \___/

### CODE REVIEW

**Comment by Qustinnus** [comment]
hey my bucket broke :(

**Comment by ShizCalev** [comment]
ftfy

**Comment by Qustinnus** [comment]
what the hell are these tags you GBP stealing robber!!

**Comment by Qustinnus** [comment]
:^)

**Comment by ShizCalev** [comment]
♥

**Review by Cyberboss — APPROVED** [review]

**Comment by Anonmare** [comment]
What purpose, if ever, did these var serve?

**Comment by ShizCalev** [comment]
They're as old as the repo is, don't think they were ever used.

**Pull request merged**
