### PR TITLE
Adds an abandoned kitchen to Metastation

### PR DESCRIPTION
**Pull request by Mickyan**
:cl: Mickyan
add: Added an abandoned kitchen to Metastation maintenance
/:cl:
Maint gimmicks are fun and Meta was the only map that didn't have a kitchen. Also, there's donk pocket boxes all over the place but no way for an industrious assistant to actually cook them!

This is the room next to the abandoned robotics lab, I moved the borg recharging station and powercell charger into the lab itself since those are pretty important.

### CODE REVIEW

**Comment by Bluespace** [comment]
Could you stick a normal kitchen knife in there for slicing dough?

**Comment by Mickyan** [comment]
@Bluespace there is one, you just have to look closely (or look at the map diff)

**Comment by Repukan** [comment]
I dislike adding presets of robotics/kitchen/science to main because if someone wanted to run the gimmick of running a kitchen they'd be willing to ask for boards and instruments. Instead everything gets added to main because God forbid people ask around for stuff.

**Comment by Bawhoppen** [comment]
Repukan speaks the truth. Adding free abandoned places in maint just takes away any challenge and the associated feeling of accomplishment when making your own.

**Review by SpaceManiac — CHANGES_REQUESTED** [review]
I don't hate this but I'm also not sure it's necessary.

At a minimum the meatspike situation is pretty awkward, does it need to be tucked in a corner?

**Comment by Mickyan** [comment]
@SpaceManiac I tried to make some sort of makeshift cold room but didn't quite work I guess, changed it

Aside from the reasons I already mentioned, functional rooms in maint are very handy as backup if your department gets blown up or set on fire and they also give assistants more opportunities to practice and keep busy doing something useful. 
If anything, it's not like we have a shortage of empty storage rooms, adding some variety can only make things more interesting.

**Review by SpaceManiac — APPROVED** [review]

**Pull request merged**
