### PR TITLE
Adds alternate_worn_layer

### PR DESCRIPTION
**Pull request by RemieRichards**
## Feature
- Allows items to specify what layer they render on, instead of adhering to the defaults, this works for badminnery and items that want to render on a different layer
- Gun holsters now render underneath the suit, as they logically would
## Code
- Adds `alternate_worn_layer`, a var like my previous alternate, `alternate_worn_icon`
  this allows items to specify what layer they render on.
- DOES NOT MODIFY THE OVERLAYS_STANDING INDEXES, BECAUSE THAT WOULD BREAK THINGS
- A belt item on a different layer is still in the belt section of `overlays_standing`, so that it still responds to update_belt(), etc. this is true for all items, not just belts.
- Adds a bunch of #define shortcuts for `ABOVE_X_LAYER` and `UNDER_X_LAYER`, because I know some people will read layer+1 as "above", when it really means "under"

### CODE REVIEW

**Comment by Anonus** [comment]
OH MY GOD REMIE :+1:

**Comment by bustygoku** [comment]
Can I buy you a pizza for this

**Comment by Jalleo** [comment]
This sorts the detective holster and other inconsistent stuff :+1:

**Comment by Supermichael777** [comment]
now all that needs to happen is a conceals hidden belts var that makes belts that render under not appere on examin. for example space suits don't because the belt needs to be outside the suit.

**Pull request merged**
