### PR TITLE
Reverts explosion shaking

### LINKED ISSUE #34004: SME Delamination gives weird blackscreen visuals then returns to normal.
Round ID: 81184

Server revision compiled on: 2018-01-01

The following pull requests are currently test merged:
33979: 'Implements the Ballmer Peak: Now the bartender can help R&D!' by Iamgoofball at commit aeae5e
33766: '[READY FOR TESTING] Refactors shuttles to be loaded in, rather than be on the station maps' by coiax at commit 49f8a0

Based off origin/master commit: e84a7f

### PR DESCRIPTION
**Pull request by praisenarsie**
:cl: Frozenguy5
del: Explosions causing camera shake now have been removed.
/:cl:

Fixes #34004
[why]: visually unappealing and ~~clearly untested~~

### CODE REVIEW

**Comment by MrMaclang** [comment]
they're too shakey

**Comment by Cyberboss** [comment]
>clearly untested

Don't put words in my mouth

**Comment by WJohn** [comment]
Explosion shaking simply has no upper limit, sufficiently powerful (or numerous) explosions can cause your screen to shake so badly it's literally sent flying from one end off screen to another end off screen.

Just put a cap on it.

**Comment by vuonojenmustaturska** [comment]
Also put a minimum in it so that it doesn't turn your screen black when you're fixing the AI sat and some chemist kills themselves with potassium. Also fix byond so that the shaking doesn't crash the client.

**Comment by Cyberboss** [comment]
It already has an upper limit, hence the mins, why it's not being respected
is beyond me

**Comment by deathride58** [comment]
@Cyberboss The mins are respected. The issue is that they were way, way too high.

Spawn a gun, and varedit the recoil value to see how insanely high you set the minimum values.

**Pull request closed without merging**
