### PR TITLE
Using command headsets makes you have larger radio speech

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
big words

So your text stands out from your subordinates. Inspired by the handful of rounds I played on Colonial Marines.

Nuke op leader gets a commander headset as well.

### CODE REVIEW

**Comment by Bawhoppen** [comment]
kinda weird but ok I guess

**Comment by RemieRichards** [comment]
it's... triggering on their normal speech...
That needs sorting before this is considered.

**Comment by KorPhaeron** [comment]
>it's... triggering on their normal speech...

It's triggering on their italicized "just spoke into a radio" speech yeah. Don't think anyone can see that other than people right next to you anyway.

Their truly normal, non radio speech, is regular however.

**Comment by ike709** [comment]
Yeah, I've definitely seen this help when 90 players talk at once on Colonial Marines.

**Comment by Robustin** [comment]
Yea, can't count the number of times I've died as captain/HoS shouting into my radio just for everyone to miss it in the green meme waterfall cascading down everyone's screens.

**Comment by KorPhaeron** [comment]
@tkdrg @Jordie0608 

Forgot a changelog please send help

**Comment by Bawhoppen** [comment]
its probably small enough to not matter

**Comment by tkdrg** [comment]
ok i can push one to master whatever

**Comment by tkdrg** [comment]
https://github.com/tgstation/-tg-station/commit/527b13264e00fb55a0d07543be902e5c2f242d30

**Comment by KorPhaeron** [comment]
Thanks

**Pull request merged**
