### PR TITLE
Adds a Hal 9000 themed AI Display

### PR DESCRIPTION
**Pull request by wesoda25**
## About The Pull Request

on da tin

## Why It's Good For The Game

So I made all these changes back in November, but i kept from pring it bc I didnt think it was interesting or different enough to be added to our cores. But I personally want it and would like to play with it, and when I showed it to others they told me I should make a pr. I know its very simplistic, but thats what I was going with. I want that cold piercing stare like in the movie, and the HADES display isnt really like that. so yeah, here it is

## Changelog
:cl:
imageadd: adds a HAL 9000 themed AI display

/:cl:

### CODE REVIEW

**Comment by trollbreeder** [comment]
Open the mech bay doors, HAL.
I'm sorry clown, i'm afraid i can't do that.
[Assumes direct control of durand]

**Review by Cyberboss — DISMISSED** [review]

**Comment by GuyonBroadway** [comment]
Ss13 has actually had a Hal9000 display setting for those monitors that show the shuttle time and messages that the AI usually sets to "GAY CAPTAIN!"

**Comment by wesoda25** [comment]
yeah ik it does

**Comment by GunHog** [comment]
It seems to need more detail. 
Hal 9000
The red eye part should fill more of the screen, else this will just similar to the "Hades" Hades AI screen without the animation.

**Review by Cyberboss — DISMISSED** [review]
@GunHog is right, make it slightly bigger

**Comment by wesoda25** [comment]
Current: 

image


Proposed: 

image

Not really willing to go bigger than this - good enough?

**Comment by ATH1909** [comment]
I think the red dot should be, like, twice that size.

**Comment by wesoda25** [comment]
imo it looks worse the larger its gets though, which is why I'm hesitant to do so. I for one don't like the look of the hal status displays, its much too big. Its a different idea just as mine is.

**Comment by wesoda25** [comment]
No one responded so I'll just use this which is slightly larger.

**Pull request merged**
