### PR TITLE
Moth eyes now have their own obj and mob sprites

### LINKED ISSUE #56315: moth cultists with glowing red eyes still have black eyes on their sprite
Their glowing red eyes still show up on examine, of course, but still, it's kind of disappointing.

### PR DESCRIPTION
**Pull request by GuillaumePrata**
## About The Pull Request
Moth eyes had the same object sprite as the basic human one as an organ even if they are a nerfed version of it and moth eyes were glued on their head sprite.
Having different sprites for different organs is nice, even more when they actually have different advantages/drawbacks.

The sprite now reflects on the mob and will likely make moth players cherish their unique eyes a lot instead of rushing to medbay/robotics to get better ones.

## Why It's Good For The Game
Fixes #56315

Local powergaming moth after speedrunning stealing eyes from the morgue and bullying their coworkers into doing surgery 2 minutes into the shift.
<a href="https://imgur.com/Cdoil7Q"></a>
Please, point and laugh.

## Changelog
:cl: Guillaume Prata
imageadd: Moth eyes now have a unique sprite that reflects on your mob. Take care and cherish them, unless you want to look silly.
fix: Moth cultists can have their red eyes now.
/:cl:

### CODE REVIEW

**Comment by Time-Green** [comment]
Very blessed PR. Can you do the same with flypeople?

**Comment by GuillaumePrata** [comment]
> Very blessed PR. Can you do the same with flypeople?

It was the plan but fly organs have random icons to make it harder for medbay to patch them back up and I didn't want to it now and turn this into a "rebalance" PR by removing that feature from their eyes.
One way or another I know someone is working on small changes to fly people and I will bully them to do the same if this get merged.

**Comment by ATH1909** [comment]
can we get images of other species with moth eyes, and of the sprite for moth eyes outside of someone's head?

**Comment by ATH1909** [comment]
also, if this makes it so that cult glowing red eyes actually show up on the sprites of cultist moths, you could probably sneak a :fix: into the changelog for some extra GBP.

**Comment by bluetshirtguy** [comment]
How will this effect cybernetic eyes? will they look like the moth eyes on the sprite or the weird little ones

**Comment by Mothblocks** [comment]
put Fixes #56315

**Comment by GuillaumePrata** [comment]
> How will this effect cybernetic eyes? will they look like the moth eyes on the sprite or the weird little ones

It will have the base eye icon so no cute mote eye for you.

**Comment by ATH1909** [comment]
can we get a picture of what a moth cultist with glowing red eyes looks like now?

**Review by coiax — APPROVED** [review]
Code. ✅

**Pull request merged**
