### PR TITLE
blueprints status on photographs is no longer persistent

### LINKED ISSUE #83092: Having a photo of the blueprints while having the photographer quirk carries it over to the next round
## Issue Summary
Taking a photo of the blueprints allows you to carry it to the next round with photographer quirk. which allows you to use the photo to check the wiring.

## Reproduction:

1. Take photo of blueprints
2. Put the photo in your photographer album
3. Wait for next round
4. Use the photo in the next round to check for wires
5. it works...

### PR DESCRIPTION
**Pull request by Fikou**
## About The Pull Request
Bro it's a different station with different wires!
Closes #83092

## Changelog
:cl:
del: You can no longer use another station's blueprint photo to look at wires or do the traitor objective with.
/:cl:

### CODE REVIEW

**Comment by atlasle** [comment]
thats a really funny meta bug

**Comment by Helg2** [comment]
Would be cool if it showed fake wires instead, but that's quite hard to code properly i guess.

**Comment by necromanceranne** [comment]
Imagine already completing your traitor objectives _before the round has even started_. You're just that good an agent.

**Comment by ZephyrTFA** [comment]
boo!

**Comment by Exester509** [comment]
> Imagine already completing your traitor objectives _before the round has even started_. You're just that good an agent.

You're a responsible Syndicate who does their homework in the arrival shuttle

**Comment by necromanceranne** [comment]
Those Warthunder leaks are hitting Nanotrasen pretty hard

**Comment by moocowswag** [comment]
Dont secret documents also allow you to take a picture of them?

If so this pr only fixes blueprints.

**Comment by Fikou** [comment]
if that is the case feel free to fix it

**Pull request merged**
