### PR TITLE
Adds the Lusty Xenomorph Maid

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
It is a simple animal "xeno" that is obtainable in xenobiology cores.

It polishes things it clicks on.

I need the sprite for it now.

:cl: Kor
rscadd: A certain hygiene obsessed alien is now obtainable via xenobiology gold cores.
/:cl:

### CODE REVIEW

**Comment by KazeEspada** [comment]
You need to enable robust searching and make it search for objects.

**Comment by francinum** [comment]
Requires a maids outfit added to the sprite.

**Comment by KorPhaeron** [comment]
@KazeEspada 

That sounds like a waste of time/processing power for a joke.

If they want it to clean, they can use a sentience potion on it.

@francinum 

@WJohn has one but I'm waiting for him to upload it separate of his xenoporn trove because I have no interest in downloading that stuff

**Comment by WJohn** [comment]
I would like to point out that none of the other xenos can be spawned from xenobio cores, though I guess we can let this one slide since it's pretty harmless.

It doesn't plant any weeds, right?

**Comment by KorPhaeron** [comment]
@WJohn 

Yeah only the drone plants weeds

**Comment by Iamgoofball** [comment]
:-1:

**Comment by PKPenguin321** [comment]
if you support this pr you're no longer allowed to hate goof's "meme prs" to be very honest

**Comment by Fox-McCloud** [comment]
I know @Nienhaus sprited a maid costume Xenomorph. You could use that.

**Comment by KorPhaeron** [comment]
I'll use whichever xeno maid sprite can be delivered to be without 10gb of xenomorph porn attached

**Comment by GunHog** [comment]
@WJohn can provide you all the lewd you could ever handle.

**Comment by KorPhaeron** [comment]
@GunHog 

Without godamnit

**Comment by Zilenan91** [comment]
Do hostile lusties aggressively clean you?

**Comment by KorPhaeron** [comment]
@Zilenan91 

yeah they run after you caressing and polishing

**Comment by Zilenan91** [comment]
interesting, most interesting

**Comment by Nienhaus** [comment]
@Fox-McCloud I actually sprited the original maid outfit then guilt @WJohn into making it fit for xenos. 
@WJohn ♥

**Comment by Dorsisdwarf** [comment]
:-1:

**Comment by Anonmare** [comment]
@KorPhaeron  Where can I find xenomaid sprites WITH 10GB of xenoporn attached?

**Comment by KorPhaeron** [comment]
@Anonmare 

<WJohnston> KorPhaeron: http://www.mediafire.com/download/s268vh0zc24jjsc/Away_Mission_Terrain_1.RAR
<WJohnston> it's in the test10 folder, horrible5.dmi

**Comment by WJohn** [comment]
I gave you the wrong link back then. You can even see the link's name being wrong.

Here's the custom sprites I often load up onto the server, and it's in the location mentioned above.
http://www.mediafire.com/download/yqkgpd72j7cgyk5/custom_sprites.rar

**Comment by francinum** [comment]
Test10, Horrible.dmi

**Comment by WJohn** [comment]
That's the outdated one, horrible5 is done with the new xeno sprites.

**Comment by KorPhaeron** [comment]
Pull request remains mired in a standoff over 32×32 xenomorph pornography where did my life go wrong

**Comment by Nienhaus** [comment]
:+1:

**Comment by drynwyn** [comment]
:+1:

**Comment by Zilenan91** [comment]
so how's the xenoporn

**Comment by KorPhaeron** [comment]
@Zilenan91 

Still waiting on someone to salvage those lusty xeno maid sprites for me

**Comment by Nienhaus** [comment]
But @KorPhaeron WJohn linked the file already.

**Comment by KorPhaeron** [comment]
@Nienhaus 

With all his lewd stuff in it yeah

**Comment by YotaXP** [comment]
Maybe the Xenobiologists will now learn there are consequences for their actions :+1:

**Comment by optimumtact** [comment]
screenshot

**Comment by KorPhaeron** [comment]
http://i.imgur.com/D6u0QHN.png

**Comment by optimumtact** [comment]
okay I guess :neutral_face:

**Comment by KorPhaeron** [comment]
@tgstation/commit-access

Ready

**Comment by PKPenguin321** [comment]
wew

**Pull request merged**
