### PR TITLE
Halves ssair run rate and kills lag comp

### PR DESCRIPTION
**Pull request by MrsTonedOne**
## Changelog
:cl:
balance: Halved atmos run rate. Atmos no longer tries to run sooner the following tick to make up for it taking longer then a tick to run the previous tick.
/:cl:
@LemonInTheDark - made you look.

### CODE REVIEW

**Comment by LemonInTheDark** [comment]
Rat bastard 👍

**Comment by Ghilker** [comment]
But with this machines will run slower

Can't we have them run on a separate system so that we'd still have pumps, scrubbers, vents and such still work at the normal double times per second speed?

**Comment by Qustinnus** [comment]
that's what delta time is for

**Comment by LemonInTheDark** [comment]
Please don't link atmos and delta time, flow depends directly on mols per process, and maintaining that ratio is what's important here

**Comment by cacogen** [comment]
It feels like nobody is going to ask what this actually means for the average player

**Comment by LemonInTheDark** [comment]
Oh also could you explain what `SS_POST_FIRE_TIMING` does here? Does it just mean we wait at least wait before trying to fire again?

**Comment by MrStonedOne** [comment]
https://codedocs.tgstation13.org/code/__DEFINES/MC.html#define/SS_POST_FIRE_TIMING

> Calculate its next fire after its fired. (IE: if a 5ds wait SS takes 2ds to run, its next fire should be 5ds away, not 3ds like it normally would be) This flag overrides SS_KEEP_TIMING

**Comment by LemonInTheDark** [comment]
Could you elaborate on why you're doing that? It seems a bit counter productive to me

**Comment by TheBonded** [comment]
> It feels like nobody is going to ask what this actually means for the average player

What does this actually mean for the average player?

**Comment by Kylerace** [comment]
> What does this actually mean for the average player?
@TheBonded 

gas should spread the same amount when SSair fires but the time between spreads should double from half a second to 1 second (also the other internal things that SSair does each fire). note: idk much about atmos code this is just what i could gather from looking at it for a few minutes

**Comment by TheBonded** [comment]
> > What does this actually mean for the average player?
> @TheBonded 
> 
> gas should spread the same amount when SSair fires but the time between spreads should double from half a second to 1 second (also the other internal things that SSair does each fire). note: idk much about atmos code this is just what i could gather from looking at it for a few minutes

So half speed slower fastmos?

**Comment by LemonInTheDark** [comment]
No, because of how much atmos dies under load. The bitflag change does impact things somewhat tho, @MrStonedOne I'd still like to know more about why you're doing that, it seems somewhat counterproductive to me, but maybe that's cause I'm fighting for every faster process I can get at highpop.

**Comment by MrStonedOne** [comment]
I was just thinking of ways to slow atmos down given the feedback thread, but i think we would need to look at otherways of doing this, like limiting how often air spreads

**Pull request closed without merging**
