### PR TITLE
Tweaks meta brig and vault area to expand the Warden's Office

### LINKED ISSUE #50909: Warden office in metastation has no APC and machines are magically powered
Issue reported from  Round ID: [136335](https://scrubby.melonmesa.com/round/136335) (/tg/Station Manuel [ENGLISH] [US-WEST] [ROLEPLAY] [99% LAG FREE])

Reporting client version: 513.1513

image

As the title says. Turning off Brig and Armory APC did not effect the Warden office. They are the only two APC nearby.

### PR DESCRIPTION
**Pull request by msgerbs**
## About The Pull Request
This change slides the vault and surrounding areas over by 1 tile, giving room to slide the brig cells area over 1 and give that tile to the Warden. Warden's office (Brig Control) becomes its own area with an APC and air alarm, where previously it had neither of these things and received power from an APC in the Gear Room which was technically Brig Control. This does not add or remove any items from anywhere on the map (except some office supplies in the Warden's Office), although it does make a small part of maint (to the east of cargo) slightly smaller. It also gives the warden his own charger and controls for the brig doors like Ice Box and Delta have in the front checkpoint area.

Before:
image

After:
meta_after
meta_after_noareas

And an in-game closeup of the Warden's Office:
2020-08-31 23_25_46-Space Station 13

## Why It's Good For The Game
Brig Control on meta currently is absolutely tiny and can't even fit an APC or air alarm. It's the smallest Brig Control of any current map by far. It's still the smallest, but at least now it's a proper area and doesn't piggyback strangely off another part of the brig.
Fixes #50909 

## Changelog
:cl: VexingRaven
tweak: Tweaked MetaStation's vault and brig cells area.
tweak: MetaStation's Brig Control has been remodeled.
/:cl:

### CODE REVIEW

**Comment by msgerbs** [comment]
You know what, hold off on merging this for a couple days, I want to see if I can come up with a better way to lay out this whole area. The Warden is still lacking in a lot of things he usually has in his office and the layout is still not great IMO.

**Comment by Cartographer-D** [comment]
I like this change insofar. Good edits.

**Comment by msgerbs** [comment]
I have updated the PR. I did some remodeling of the Warden's office based on some feedback from Discord. The Warden's Office is now less of an empty rectangle and has some additional items which were missing, and no longer has that bizarre out of place showroom tile floor.

**Comment by msgerbs** [comment]
I finally fixed the merge conflicts. Again. Can somebody please review this relatively soon so I don't have to redo this again 5 days later?

**Pull request merged**
