### PR TITLE
Users can now see their own prayers in the chatlog

### PR DESCRIPTION
**Pull request by JohnGinnane**
[Changelogs]: Changes the message players see when praying so they know what they prayed

:cl: JohnGinnane
add: Users can now see their prayers (similar to PDA sending messages)
/:cl:

Why: Feedback for prays was lacking 

Screenshot:
image

### CODE REVIEW

**Comment by nfreader** [comment]
Can/should we add a similar function to headset messages?

**Comment by ExcessiveUseOfCobblestone** [comment]
ghosts should be able to see prayers and subtle messages tbh.

**Comment by JohnGinnane** [comment]
@nfreader headset messages?

**Comment by Ratvar** [comment]
Centcomm admin headset messages, answers to bridge console centcomm talk function.

**Comment by Jalleo** [comment]
I have used pray before for better definition on a reply to a centcom headset feedback.

**Comment by subject217** [comment]
I didn't say that you can't do it, or that the admin shouldn't reply. Making a prompt for it will make it the default choice, which is stupid.

**Comment by JohnGinnane** [comment]
The thinking behind the reply button was to just make it a little faster
for someone like chaplain to 'communicate with God' rather than having to
go to IC tab and select pray each time. I can take it though

Should I do anything with headset messages?

**Comment by subject217** [comment]
There is a hotkey for prayers, and if you don't use hotkey mode you can just type the verb in. The hotkey is P, IIRC.

**Comment by PKPenguin321** [comment]
why do people use hotkeys

**Comment by cyclowns** [comment]
pressing 1 key is better than pressing 4-6

**Comment by Kagus** [comment]
why do people type pray when you can just let Jesus into your heart

*Ahem*... Seeing your own prayers (possibly even with the recoloring from chaplain/cult/spiritual) = Yay! This is Good Thing(tm), and maybe, just maybe, it will make people think twice about abusing the verb when they see their own stupidity in writing.

Reply link to subtle messages? Ehh... I'm not sold on it. The whole point is to be a subtle message, not necessarily a "NIKO! IT'S YOUR COUSIN!". If you sense the hair on your neck start to stand up, it's not generally considered common practice to initiate a conversation with the follicles in question.

**Comment by JohnGinnane** [comment]
Okay I'll take it reply link later today

**Comment by JohnGinnane** [comment]
Okay reply is removed, added a screenshot

**Review by SpaceManiac — APPROVED** [review]

**Pull request merged**
