### PR TITLE
Adds an End of Round Sound Toggle Preference

### PR DESCRIPTION
**Pull request by KomradeSpectre**
## About The Pull Request

Full disclosure, I got sick of hearing the constant ear shattering volume sounds that played at the end of the round. I couldn't find a way to mute them other than my hardware switch on my headset. Personally, I find them all to be obnoxious and unfunny. So, I coded this.

## Why It's Good For The Game
Allows you to never hear the **_hilarious_** end of round sounds ever again if you so choose to. Adds the toggle to the verb tabs, and in the Game Preferences Menu -> OOC Preferences.

## Changelog
:cl: TheMythicGhost
add: Adds a way to turn off end of round sounds. Finally, peace has returned to eardrums everywhere.
/:cl:

### CODE REVIEW

**Comment by Twaticus** [comment]
oh my good god thank you for this im so sick of fumbling with my mixer every round end

**Comment by PKPenguin321** [comment]
Does this stop the music that plays when the shuttle docks at centcom because if so that's epic
 Round end sounds are based though

**Comment by KomradeSpectre** [comment]
> 
> 
> Does this stop the music that plays when the shuttle docks at centcom because if so that's epic
> Round end sounds are based though

image

**Comment by PKPenguin321** [comment]
That'd be a no then, sad

**Comment by Fikou** [comment]
yee haw

**Comment by wesoda25** [comment]
Why are people even downvoting this

**Comment by KomradeSpectre** [comment]
I have no clue.

**Comment by PKPenguin321** [comment]
Now that I think about it, why aren't these Mute preferences just Volume preferences? playsound has an arg for volume, so you could just let the user input a number from 0-100 for things like lobby music, midis, round-end sounds, etc. Or is that not how playsound works?

**Comment by KomradeSpectre** [comment]
> Now that I think about it, why aren't these Mute preferences just Volume preferences? playsound has an arg for volume, so you could just let the user input a number from 0-100 for things like lobby music, midis, round-end sounds, etc. Or is that not how playsound works?

Because I specifically just made it to toggle mute similar to Lobby Music. If you want volume changing, you can by all means do it.

**Comment by spookydonut** [comment]
dont you need to increment the prefs version and write a converter?

**Comment by KomradeSpectre** [comment]
Do I? I tested this locally, and it worked fine. If there is need to do what you're mentioning, I can do that.

**Pull request merged**
