### PR TITLE
Fixes injecting radimmune mobs with the cloner

### LINKED ISSUE #33999: golems' genetics are fucked up
their dna doesn't match humans', so they can't use the genetics console/use the occupant button on buffers.
however, the occupant:delayed function still works on them, and gives them powers
i think one of these is unintended, but i don't know which

### PR DESCRIPTION
**Pull request by ShizCalev**
Fixes #33999

Also cleans up some excess spaces.

🆑 ShizCalev
fix: radimmune mobs will now be properly respected by the cloning scanner.
/🆑

### CODE REVIEW

**Comment by ShizCalev** [comment]
Just realized something, hold on this.

**Comment by ShizCalev** [comment]
Fixed.

**Comment by FantasticFwoosh** [comment]
@ShizCalev Before you go ahead, might you think that rad-immune mobs might be more interesting to remain as they are without the benefit of cloners? Nobody loses anything by not implementing this fix.

- Because being a telekinetic and x-ray eyes golem is really a powergaming issue (or similar comparison) when you can stunpunch people to death too

**Comment by ShizCalev** [comment]
They were already blacklisted from being experimented on, this just fixes the Occupant:Delay button injecting them despite the Occupant button being grayed out. It was unintended behavior.

**Pull request merged**
