### PR TITLE
Adds a new costume to the autodrobe + spotted fringe hair

### PR DESCRIPTION
**Pull request by tralezab**
## About The Pull Request

the costume is radically different when adjusted, so see which version you like more!

I'm also probably going to add the better stardust costume than what we have right now

## Why It's Good For The Game

as with the delinquent hat, it's really goofy and fun to get into a jojo costume with a holoparasite

## Changelog
:cl: memager for the stardust sprites
add: A new reference has been stuck in the autodrobe
/:cl:

### CODE REVIEW

**Comment by PKPenguin321** [comment]
This is getting kind of blatant

**Comment by tralezab** [comment]
usually that's what i would say, i like adapting ideas and not taking them, but i got no ideas on how to do that here and most costumes are just straight references including some other jojo outfits so idk

**Comment by fludd12** [comment]
I mean, to be fair, the Dr. Scratch costume and troll horns mutation weren't exactly subtle either. I won't advocate for one reference above another, considering.

**Comment by wesoda25** [comment]
I mean I guess dude

**Comment by optimumtact** [comment]
no more jojo references

**Comment by loserXD** [comment]
why not

**Comment by shellspeed1** [comment]
Is that a jojo reference?

**Comment by optimumtact** [comment]
because we have plenty already and too many references is lame

**Pull request closed without merging**
