### PR TITLE
New gibber and food/slime processor sprites

### PR DESCRIPTION
**Pull request by MTandi**
NVIDIA_Overlay_VCO7E2sm4a

## About The Pull Request

Updated gibber sprite and  food/slime processor sprites.

image

Also it had an unused "dirty" var. Now it becomes dirty again.

## Why It's Good For The Game

It was old.

## Changelog

:cl:
image: New gibber sprite
image: New food/slime processor sprite
/:cl:

### CODE REVIEW

**Comment by Jacquerel** [comment]
It looks like it moves one pixel to the side when you turn it on, is that intended?

**Comment by MTandi** [comment]
> It looks like it moves one pixel to the side when you turn it on, is that intended? I personally think it'd be nice if there was a bit more delay between those drips from the little tube.

Yeah it didn't shake. I looked at the reagentgrinder shaking and it looks like a mess. We need someone to extract shaking into a component.

**Comment by ZephyrTFA** [comment]
> > It looks like it moves one pixel to the side when you turn it on, is that intended? I personally think it'd be nice if there was a bit more delay between those drips from the little tube.
> 
> Yeah it didn't shake. I looked at the reagentgrinder shaking and it looks like a mess. We need someone to extract shaking into a component.

it... is

**Comment by MTandi** [comment]
It shakes with the puddle now though, but that's fine.

**Comment by MTandi** [comment]
> the new blood doesn't look good, far too bright, and the random static splotches that have way too much pattern consistency and no consistency to what grinding a person would do make it look like someone painted it to look like a red and steel cow

image

**Comment by Loafin34** [comment]
this might be a bit out of scope, but what if it had varying decals depending on how much it was used? for one monkey it's a bit bloody, for five monkeys it's pretty crusted, and after ten it should look like an eldritch machine instead of a gibber.

**Review by Wallemations — APPROVED** [review]

**Pull request merged**
