### PR TITLE
Resprites IDs, Random Sprites in the Cards DMI, and Fixes Prisoner Coloring

### PR DESCRIPTION
**Pull request by EricZilla**
## About The Pull Request
These sprites have been adapted from a person who wished to remain anonymous with their blessing for tg

Take the old IDs and make them look a little more fancy and sci-fi, I think they look really nice! This makes the job marker into a cute little screen too, but this is totally optional, if maintainers want the animation gone It wont take long at all.
Also resprites a few random other items in the cards.dmi, such as emags, doorjacks, hack-o-lanturn, budget cards, and one touch up on the red team ID for laser tag for consistency.
Also prisoner IDs had black symbols and black department but orange trim on an orange card, so it was just a huge mess.

all the small things

## Why It's Good For The Game

I'm gonna be real IDs are kinda crusty, and its something EVERYONE has to look at at least once a shift. Poor HOPs may even look at two. God forbid three. Now they will look pretty neat.
As for the other changes, the hack-o-lantern looks like it was made in 2001 its OLD. I don't even know if we use it, but now its updated. The red laser tag team got a nerf so now all team letters are white, instead of red being orange for no reason.

## Changelog
:cl:
image: We have received a new shipment of IDs, as the old ones were found out to be haunted.
image: Laser tag red team ID has received a massive nerf
image: Station budget cards have gotten a facelift
image: Emags and Doorjacks
fix: Numbered prisoner IDs will now be legible
/:cl:

### CODE REVIEW

**Comment by SomeoneYouProbablyKnow** [comment]
Dude those are awesome, the job icon having those screen lines is inspired. 
I still like how ss14 made ids smaller but these look too good.

One thing, maybe change the base colour of the doormag or the emag while you're working on ids, the current ones are just too similar and you carry that right over. I guess you can say that's intentional but just consider it

**Comment by zxaber** [comment]
Ah, the yearly ID resprite.

They look very cool, for sure, but they're a bit visually busy. The indentation oval makes them appear chunky, like a cartridge. I'm not sold on them fitting into a wallet, for example. I'd almost want to rename them to badges.

**Comment by necromanceranne** [comment]
I like em.

Just to double check, the icon diff bot seems to be displaying the cards very incorrectly. Is that just a problem with the bot? Many of the icons seem incorrect.

**Comment by Loafin34** [comment]
For the doormag and Emag, could you put a little airlock symbol on the doormag and an X or something on the Emag? looks like a lot of visual clutter for me, personally.

**Comment by unit0016** [comment]
Looks like this'll leave the `COLOR_PRISONER_ORANGE` define unused? Maybe?

**Comment by SomeoneYouProbablyKnow** [comment]
I was thinking of changing the color of the card itself to red or something. It got plenty of visual elements already but still blend together because the colors used are pretty much the same

**Review by Wallemations — APPROVED** [review]
static screens look far better than the animated ones you had before imo

**Comment by EricZilla** [comment]
That seems to be the consensus, so I'll snip the animations and see what I can do about the emag being more syndicate styled. Also gotta probably make a new wallet.

**Comment by Fikou** [comment]
i dislike the animation i dont want something that is visible for my entire round to flash in my eyes

**Comment by EricZilla** [comment]
Okay working on removing the animations next, but here are the new emag and doorjack

mags
And here is what I had to do to make the wallet not look like absolute trash
wallet
I'm not really good with like, leather or natural materials so PLEASE don't ask me to do a complete new wallet I'll die

**Comment by EricZilla** [comment]
> Looks like this'll leave the `COLOR_PRISONER_ORANGE` define unused? Maybe?

Forgot to mention, bounty hunter still uses it, so its not pointless to have, plus i'd rather have people have the option to use it again later

**Comment by EricZilla** [comment]
OKAY all the requested changes are done PLUS one special new addition
bit avatar
READY FOR REVIEW and hopefully merge

**Review by Wallemations — APPROVED** [review]
What would you do if you had the Security Credit Card

**Pull request merged**
