### PR TITLE
buffs multiver to have a lung damage rate of 0.1 per chemical per tick from 1.0

### PR DESCRIPTION
**Pull request by MacBlaze1**
## About The Pull Request

Buffs multiver to have a lower lung damage per chemical

## Why It's Good For The Game

Multiver is not very good, and Cobby approves these changes. He said he forgot to change the rate.

## Changelog
:cl:
balance: Multiver now has 0.1 lung damage * the number of positive medicines in the body
/:cl:

### CODE REVIEW

**Comment by ExcessiveUseOfCobblestone** [comment]
image

**Comment by ATH1909** [comment]
Could you make it not purge itself too?

**Comment by Tlaltecuhtli** [comment]
tea heals 0.2 with no downsides and lasts longer as it doesnt purge itself

**Comment by Anonmare** [comment]
I prefer to use tea, iced tea and lime juice as toxin heals before multiver due to the self-purge+organ damage, it desperately needs more positives

**Comment by Krysonism** [comment]
The only reason to use multiver is to mix 0,5u of every vendor chem to make a syringe that purges 5u+ of every reagent per injection as a anti-syringe powergaming tech.

**Comment by MacBlaze1** [comment]
@ExcessiveUseOfCobblestone What should It be then? 0.3? 0.4?

**Pull request closed without merging**
