### PR TITLE
SAVES THE PENGUIN FROM KNOWN PENGUIN HATER/MAPPER CHESHIFY (Fixes #78084)

### LINKED ISSUE #78084: The penguin chick on the west side of the medsci floor on northstar always dies inside its pen.
Reporting client version: 514.1589

## Round ID:
[213911](https://scrubby.melonmesa.com/round/213911)

## Testmerges:
- [Revert "Bumps rust-g to `3.0.0` "](https://www.github.com/tgstation/tgstation/pull/77307)

## Reproduction:
Join on Northstar, notice that the poor penguin dies every single time due to something inside its cage.

### PR DESCRIPTION
**Pull request by xPokee**
## About The Pull Request
Fixes https://github.com/tgstation/tgstation/issues/78084
## Why It's Good For The Game
I saved this weird looking dog from freezing to death 
image
## Changelog
:cl:
fix: Fixed the air inside of a penguin pen being way too cold
/:cl:

### CODE REVIEW

**Comment by Jacquerel** [comment]
but penguins like being cold

**Comment by xPokee** [comment]
> but penguins like being cold

He was TOO cold!!

**Comment by Sealed101** [comment]
edit the penguin's temp thresholds instead, should be `minimum_survivable_temperature` i think

**Comment by Fikou** [comment]
WHY WOULD CHESH DO THIS

**Pull request merged**
