### PR TITLE
Buffs syndicate bombs to fit the new explosion mechanics.

### PR DESCRIPTION
**Pull request by theOperand**
2, 5, 11 to 3, 9, 17.

### CODE REVIEW

**Comment by AlexanderUlanH** [comment]
Does this mean a guaranteed kill on the tcomms APC?

**Comment by Miauw62** [comment]
i havent tested it. it probably does, i think?

**Comment by Ikarrus** [comment]
Can you make the beeping lounder? It's supposed to be obvious to anyone nearby, but the 3D sound update made it very, very quiet unless you were right there.

**Comment by Fox-McCloud** [comment]
Bit too big.

3-7-16 would be better, in my opinion.

Why? Mathematical consistency.

Normally they had 66%-71%-78% (dev-heavy-light) correlation to the bomb cap; having the heavy and light being that high isn't just and adjustment, it's quite a sizeable buff, as well.

**Comment by Miauw62** [comment]
Mathematical consistency may be a thing, but it's not like bombs were reduced by a flat ratio to get the new system.

**Comment by Dorsisdwarf** [comment]
Minibombs are an anti-personnel weapon, Fox, so they don't really need a rebuff.

**Comment by Cebasiz** [comment]
no objections, they need the help.

**Comment by Fox-McCloud** [comment]
@Miauw62 

True. Not like reactionary explosives behave properly anyway; the explosion STRONGLY favors a blast radius in the north-east.

**Pull request merged**
