### PR TITLE
Changes the crystallizer's supermatter shard recipe to require extreme temperatures with an extreme endothermic reaction. Supermatter formation will now generate anomalies nearby.

### LINKED ISSUE #70307: It is impossible to create a superMatter crystal shard inside crystallizer
**Round ID : N/A**

**Description:**

Creating the gases to make a supermatter crystal shard[Plasma,O2,BZ,Hyper-Nob,Anti-Nob] is not the difficult part. These are possible via a fusion reactor or quad ultra micro lasers but maintaining the Temperature[2-5 kelvin] range for the reaction is impossible.

To illustrate the point here is my setup

Screenshot (21)

On the left i have 3 tier 4 freezers[bluespace matter bins and quad ultra micro lasers] and this is what the horizontal omni pipe and the vertical red coolant pipe contains

Screenshot (22)

I cant physically fit any more gas in these pipes and my entire plasma tank in atmospherics is running out. Even with hyber-noblium we would need to create an mental amount of it via the dangerous fusion reactor to reach a heat capacity of 20 MJ and even then it fails to keep the gas cool enough

Screenshot (23)

Temps still spike to 63 kelvin and i don't have enough time to cool down the gas before the progress goes down to 0 again. Even with admin tools after spawning like 50+ canisters of Hyper-Nobelium i still couldn't get it to cool down fast enough.

The wiki dosen't offer any advice and nobody has even tried to use the crystallizer as the shard can be ordered through cargo bay i get it but this process should be made easier. Expand the temp requirements or decrease the amount of energy this reaction releases

### PR DESCRIPTION
**Pull request by Pickle-Coding**
## About The Pull Request
Closes #70307.

Changes the minimum temperature for supermatter formation to 10MK, and maximum temperature to 210MK, and the energy release to -30GJ. It will also create anomalies during formation. The worse the quality loss, the more frequent and destructive the anomalies are.

## Why It's Good For The Game
Makes the recipe actually possible. The energy release was just too extreme for the tiny temperature range. Shakes things up for this recipe by requiring temperatures that need a HFR running at the most dangerous power levels. The supermatter is moody, so it makes sense that it will release some destructive anomalies if it was made at poor quality.

## Changelog

:cl:
balance: Changes the crystallizer's supermatter formation minimum temperature to 10MK, maximum temperature to 210MK, and energy release to -30GJ.
add: The supermatter will get moody if it is getting synthesized at poor qualities, releasing anomalies.
/:cl:

### CODE REVIEW

**Comment by Jackal-boop** [comment]
I liked how it's original thought was to use very low Temps and balance an exothermic reaction. Why don't you just lowe the energy release instead of turning the recipe on its head?

**Comment by Jackal-boop** [comment]
Also this makes having to produce a shard when you don't have a power source basically impossible

**Comment by Pickle-Coding** [comment]
> Also this makes having to produce a shard when you don't have a power source basically impossible 

The supermatter is an experimental and advanced power source. Start small with some solars to power a gas turbine, run a gas turbine and charge up some SMES, then build a HFR, max SMES and do your usual stuff to heat the crystallizer.

**Comment by Muffindrake** [comment]
It's not quite true that the cold recipe is impossible to make, but it requires some mechanics abuse to pull off. Namely, it can be done with a single T4 thermomachine by toggling the Crystallizer power on and off such that the crystallization loses minimal progress while the heat medium is cooled down. I have done this multiple times.

I do agree that it should probably be made more interesting than this. I do not agree that requiring the HFR to do this is the way to go.

**Comment by SyncIt21** [comment]
After experimentation the maximum temperature I could achieve by transferring heat from the HFR output gases to the crystallizer via temperature pumps was 10 MK at fusion level 6 with 54% failing integrity and 100% iron content. The heat exchange between the crystallizer gases & the HFR won't allow my temps to go any further even after I reached 8.5e+7 kelvin the highest temp available for tritium+H2 mixture.  Furthermore the pipes get clogged with very little amount of extremely hot gases, so it doesn't efficiently transfer the heat to the crystallizer

The temp requirement must definitely be lowered.

**Comment by Pickle-Coding** [comment]
> After experimentation the maximum temperature I could achieve by transferring heat from the HFR output gases to the crystallizer via temperature pumps was 10 MK at fusion level 6 with 54% failing integrity and 100% iron content. The heat exchange between the crystallizer gases & the HFR won't allow my temps to go any further even after I reached 8.5e+7 kelvin the highest temp available for tritium+H2 mixture.  Furthermore the pipes get clogged with very little amount of extremely hot gases, so it doesn't efficiently transfer the heat to the crystallizer
> 
> 
> 
> The temp requirement must definitely be lowered.

Got to prepare the heat before transferring it to the crystallizer if you want to do it safely. Antinob HFR and hypernob has a higher specific heat so it stores more energy, and heat up some plasma too.

**Comment by SyncIt21** [comment]
Yup I'll give it a try. Also i noticed the UI displayed on the crystallizer for the super matter shard hasn't changed. It still says requires 2k to 5k.

**Comment by Jackal-boop** [comment]
Using the highest level HFR fuel type seems like its just not worth it for a single SM shard.

**Comment by Ghilker** [comment]
You should balance it to a level of trit/H2 fuel instead of antinob/Hypernob

**Comment by SyncIt21** [comment]
2nd attempt tried creating hypernobelium and electrolyzing it to antinobelium which was VERY time consuming. Had to create a ton of tritium first then create H20 and later cool it down and electrolyze it to H2. then run the reactor for at least 15 minutes to give me sufficient Hypernob to electrolyze to antinob. At the end i didn't make enough fuel to maintain fusion level 6 so i just went back to regular tritium & h2. 

Found a little more success this time reaching 47MK after gradually increasing the magnetic constrictor to allow for more fuel reaction. Overall, i find this process very tiring and would rather just order a shard from cargo and wait 20 minutes to order another shard. Personally setting the temps to fusion level 5 amounts would be far better.

**Comment by Jackal-boop** [comment]
> You should balance it to a level of trit/H2 fuel instead of antinob/Hypernob

I second this. If you really want to incorporate the HFR into this process it should be a middle ground fuel

**Comment by Pickle-Coding** [comment]
I balanced it to make it possible with a trit/h2 HFR without anomalies destroying it. Preheating 10,000 moles of plasma to 40MK would be recommended. It's not feasible to mass produce supermatter shards with a trit/h2 HFR, but an antinoblium HFR might make that easier, but preheating is still recommended and it will be dangerous. An antinoblium HFR is still required if you want a masterwork quality supermatter shard.

**Comment by Mothblocks** [comment]
As we have an abnormally large number of open PRs, I am closing all ones that have been marked stale. Please find an interested maintainer over Discord to reopen and merge the PR.

**Pull request closed without merging**
