### PR TITLE
AI VOX Sound File Fixes

### PR DESCRIPTION
**Pull request by Davidj361**
[Changelogs]:

:cl:
fix: Fixed 'vox_login' for AI VOX
tweak: Made the AI VOX airhorn quieter to 25% of its original volume
/:cl:

The VOX airhorn is now 25% of its original volume, and the 'vox_login.ogg' was cut off from encoding and restored to its original file before #36492

### CODE REVIEW

**Review by Cyberboss — APPROVED** [review]

**Comment by Bluespace** [comment]
tweak: Made the airhorn quieter to 25% of its original volume

lol my bad

**Comment by Davidj361** [comment]
It's just for the AI VOX.

**Comment by Bluespace** [comment]
> It's just for the AI VOX.
me, everytime I get AI: welcome to the station crew Sairhorn Sairhorn Sairhorn

**Comment by Anonmare** [comment]
>not using scensor to go on a rant at shift start

Bad player

**Comment by Bluespace** [comment]
Swhitenoise Swhitenoise Swhitenoise

**Pull request merged**
