### PR TITLE
Tramstation Fixes pt.1

### PR DESCRIPTION
**Pull request by MMMiracles**
- Added hangover spawns
- Moved incinerator pipeline to maintenance for easier access, added maintenance access to the atmos testing room
- Slight pipe shifts to remove redundant pipes
- Fixed a few areas that weren't connected to the main waste/distro loop
- Added firelocks to the lower tunnel
- Power closet for bridge is now only bridge access instead of being engineer access
- Removed the SMES from the power closets
- Multi-deck pipe adapters are moved back to their original spots in power closets since the pipe bug with them was fixed
- Medical's treatment center doors have their interior access unrestricted so patients can freely leave
- 1-2 extra blob/xeno spawns on the lower level
- Removed duplicate pipes/cables

### CODE REVIEW

**Comment by Zytolg** [comment]
Did you fix the duplicate pipe on layer 2 around (84,92,2)?

**Comment by TheBonded** [comment]
Did you fix lower service apparently not being connected to the grid? I've heard people say it's unconnected, and last I checked it loses power 10 minutes into the shift

**Comment by TheVekter** [comment]
Can you add some way to discourage people just jumping in front of the tram because LOL XD SUICIDE? I haven't seen a single round on this map not descend into a bloodbath.

**Comment by Bluedazzled** [comment]
where muh wheelchair support

**Pull request merged**
