### PR TITLE
Deletes code that has a comment stating that it should be deleted after an issue that is now closed is resolved.

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request
#39770 is resolved therefore what I'm deleting should be deleted.

## Why It's Good For The Game
It told me to delete it.

## Changelog
Not player-facing.

### CODE REVIEW

**Comment by Cyberboss** [comment]
You'll find that hacks become depended on and your tests will fail.

**Review by Cyberboss — CHANGES_REQUESTED** [review]
That issue was closed because the idea was abandoned. This function is now a prerequisite for various early game routines that require the map config to be loaded when it _potentially_ could not be (Before SSmapping is initialized). Not to mention you're removing the only spot where the map config is actually loaded with this which is used internally by SSmapping. The reason your CI ran for 6 hours is because there are too many runtimes for the game to tick even once.
image

The code is probably best moved to `subsystem/mapping/New()`. The `if (!config)` can be dropped in that case.

**Comment by Cyberboss** [comment]
It needs to be loaded in New not Initialize

**Comment by interestingusernam3** [comment]
Moved, now it works.

**Review by Cyberboss — APPROVED** [review]

**Pull request merged**
