### PR TITLE
Adds plugsuits as a pack cargo can purchase

### PR DESCRIPTION
**Pull request by MadoFrog**
## About The Pull Request

Adds the ~~plugsuits~~ mech pilot suits featured in Neon Genesis Evangelion as costumes cargo can purchase.
~~[Preview](https://i.imgur.com/qH3LHyS.png)~~
[Preview](https://i.imgur.com/6ClJJpj.png)
Any further commits will make the sprite look less bad.

## Why It's Good For The Game

More costumes are always fun.

## Changelog
:cl:
add: Red, white, and blue mech pilot jumpsuits now available in the Mech Pilot's Suits Crate, under Costumes & Toys.
/:cl:

### CODE REVIEW

**Comment by Tlaltecuhtli** [comment]
🤔

**Comment by ishitbyabullet** [comment]
this is /tg/ not /a/ why should plugsuits just be added

**Comment by Shapsy** [comment]
Feels a bit too on the nose, especially having them in a plugsuit crate

**Comment by fludd12** [comment]
Given how plugsuits work in the anime, you could make them jumpsuits, and call them "mech pilot suits," or something similarly genericized. Perhaps give them some less meme descriptions, too - though, not entirely meme-less; we have the `sord,,,,`, after all.

**Comment by Wilchenx** [comment]
roboticist jumpsuit is supposed to be plugsuit

from what i know the person that added rolling down jumpsuits didn't know that and people think they are coveralls

**Comment by Wilchenx** [comment]
also the sprites are really not good

**Comment by Detective-Google** [comment]
I mean other than being a bit on the nose (usually the items ripped from pop culture aren't *that* obvious), looks good

**Comment by Dorsisdwarf** [comment]
I cant believe you used my joke descriptions, 10/10 pr

**Comment by fludd12** [comment]
Excellent! I like your choice of subtle references, they fit the tongue-in-cheek nature of descriptions perfectly.

**Comment by YakumoChen** [comment]
GET IN THE GOD DAMN ROBOT SHINJI

**Review by SpaceManiac — CHANGES_REQUESTED** [review]
Paths should be prefixed: `/obj/...` instead of `obj/...`.

Since they share many variables, I would encourage putting these under a shared parent, e.g. `under/mech_suit/red`, `under/mech_suit/blue` etc.

**Review by SpaceManiac — APPROVED** [review]

**Pull request merged**
