### PR TITLE
Removes Hygiene

### PR DESCRIPTION
**Pull request by Garen7**
## About The Pull Request

Removes Hygiene and every interaction it has with other parts of the game.

## Why It's Good For The Game

[The majority of players don't want it in anymore](https://tgstation13.org/phpBB/viewtopic.php?f=10&t=21067&hilit=hygiene&sid=73c4cbeec006288db6f71de6bd843639). I didn't want to PR this for  a while because I feel that it's important to be able to experiment with new ideas and give those ideas enough time to settle in, however this has had time and it still isn't in a form where people enjoy it. I understand that some people who voted for removal just wanted hygiene to be imporved/fixed however after all the tweaks it has had I don't see an iteration where it would be good for the game. I could understand if there was a small penalty for not taking a shower while being dirty(i.e. covered in blood) for a long time, however that should really be handled through a simple moodlet, not a whole system spanning over a ton of different files. One of the reasons original creator of moodlets made the PR was so that the showers would see more use, however they already had the use of getting rid of blood on you so you don't look like you just murdered someone. I think he just didn't consider that when making the PR so that really should be taken into consideration when trying to decide whether we should have hygiene or not. I can't see any way that keeping hygiene in the game really benefits the experience of the game and I honestly believe that people trying to keep it in are doing so because of sunk cost fallacy. If you disagree and can explain to me in what way that hygiene benefits the game please explain how in the comments.

## Changelog
:cl: Garen
del: Removes Hygiene
del: Removes NEET and neat quirks
del: Removes the ability for scangates to scan for hygiene
tweak: Garlic no longer makes you stink
tweak: Replaced the penalty on transcendent olfaction with the inability to use it when in any amount of miasma.
imagedel: Removed Stink Clouds
/:cl:

### CODE REVIEW

**Comment by HomocidlePancakes** [comment]
You glorious bastard I fucking love you

**Comment by optimumtact** [comment]
rude of you not to ask

**Comment by HomocidlePancakes** [comment]
I hate oranges

**Comment by Garen7** [comment]
sorry i didnt mean to over step any boundaries, I asked and were cool now

**Comment by spessbro** [comment]
keep hygiene we want to make it better

**Comment by Qustinnus** [comment]
I have a branch with a variety of improvements ready but I havn't finished it up because I've been getting constant harrasment about hygiene so opening the PR will result in me getting more colorful messages from all kinds of people ranging from perma-banned players who havnt seen hygiene anyways to people who unironically think every PR is about some personal kink I have for that specific mechanic.

**Comment by granpawalton** [comment]
You dont have to victimize yourself because 70% of the players still dont like hygiene, if the PR lowered the impact hygiene has on the game then im sure theyll love it

**Comment by Qustinnus** [comment]
every PR I make to improve features I work on results in harassment because suddenly its relevant again

**Comment by kriskog** [comment]
Stink clouds made me take off my memento mori in the shower. Begone, stink clouds.

**Comment by Qustinnus** [comment]
people always egg to nerf things into non-existence but I'll try nonetheless

**Comment by granpawalton** [comment]
Maybe it does need to be nerfed if so many people want it, i dont see a reason someone should be punished for getting his shoes bloody when its almost impossible not to

**Comment by Qustinnus** [comment]
removing / changing that is on the list of changes, but its arguably still a nerf (mind you; not a bad one. the bloody shoes thing is a bit too hard to avoid)

**Comment by kriskog** [comment]
I don't really see how small "nerfs" is going to make this much better. Stink clouds are annoying at best, but not for any rp or mood reason. They are just visually annoying.
Add to that the need to undress in the shower, dropping all your shit. The game isn't built around this, and dropping shit on the ground is the same as asking someone to steal it. 

So to summarize: its unfun, it's annoying, its clunky. I am for removal.


You also didn't make felinids able to self groom, so..

**Comment by Qustinnus** [comment]
because felinids are deprecated code.

besides that, having to store your items is relatively interesting because it makes you vulnerable for a moment, I think giving sec the ability to shower in sad seperated locker rooms would be a good solution to the sec robbery problems atleast (I'm bad at mapping though so I'd leave that to someone with better talents for that). Lockers in the shower area should also alleviate some problems, but again I'm not great at mapping.

Something I also thought of was a robotic gate that takes off your clothes, hands you a ticket, and stores them until you walk through it again with the ticket. Solving most problems and possibly allowing for some funny interactions where you sprint through the gate to switch clothes. Basically a robotic, dumb, garderobe.

**Comment by kriskog** [comment]
You and I are operating with very different definitions of interesting.

**Comment by Garen7** [comment]
I play sec a lot and I’d rather just not shower than drop my baton in the shower

**Comment by HomocidlePancakes** [comment]
Add deodorants when?

**Comment by Qustinnus** [comment]
thats a good one @HomocidlePancakes

**Comment by HomocidlePancakes** [comment]
Just re-suggesting featurs from yog

**Comment by ExcessiveUseOfCobblestone** [comment]
i'd rather it not be nerfed, just have some indirect QoL improvements such as a way to easily store all your items in a locker w/o having to play click whack-a-mole and ofc a showerroom for sec (we need more restrooms in all maps anyways for ROLEPLAY).

I'm certainly going to need a better reason than "I/we/the players don't like it" if anyone is serious about PRing a removal in the future.

**Comment by Qustinnus** [comment]
@ExcessiveUseOfCobblestone the automatic wardrobe is in progress right now, as well as some RnD unlockables that will give the janitor some new work as well

**Comment by Garen7** [comment]
@ExcessiveUseOfCobblestone an overwhelming vote for the removal of something is a very good reason to remove it, can you explain why you say its not?

As for my own reason, the green smoke is immersion breaking and interrupts the flow of the game, like I'll just be talking to someone and then green smoke will erupt from me and we'll just awkwardly say goodbye while I go to shower alone doing zero roleplay or anything interesting, or just spray myself with space cleaner because like I said people are trying to nerf hygiene into nonexistence.

Beyond that I don't see any benefit that it gives to the game. No one will roleplay in the showers because its awkward to talk to someone while naked and in the showers and like I said people already used the showers to get rid of blood on clothing. Can you tell me what you see in it that helps the game? And how the same cant be achieved with a simple moodlet?

**Comment by wesoda25** [comment]
You can tell its a bad feature when it takes a mountain of PRs to make it bearable. If you are going to make it so pointless that it has nearly no effect on a player in a round, literally what is the point in not removing it. Garen please reopen this, and if not, can I copy your code and open it separately?

**Comment by optimumtact** [comment]
no wesoda u cant

**Comment by Garen7** [comment]
@wesoda no let qustinnus work in peace, he’s trying to fix it and if he doesn’t someone will try to remove it later, he has a good bit of stuff already coded so just wait to see how it affects hygiene

**Comment by ExcessiveUseOfCobblestone** [comment]
> @ExcessiveUseOfCobblestone an overwhelming vote for the removal of something is a very good reason to remove it, can you explain why you say its not?

Popularity should be used to reinforce an opinion, not act as your basis for one.

> As for my own reason, the green smoke is immersion breaking and interrupts the flow of the game, like I'll just be talking to someone and then green smoke will erupt from me

Tangible feedback and can be fixed. not an excuse to remove.

> doing zero roleplay or anything interesting

Sorta tangible feedback, The situation is not roleplay, the situations that can arise from having to go from (your current location) to (another location) allows for opportunities to have conversations with different people / roleplay. We can QoL the process to make it less clunky but otherwise I think it's fine.

> or just spray myself with space cleaner because like I said people are trying to nerf hygiene into nonexistence.

Tangible feedback and can be fixed. not an excuse to remove

> Beyond that I don't see any benefit that it gives to the game.

Can't do anything with this, look harder.

> No one will roleplay in the showers because its awkward to talk to someone while naked and in the showers

tfw doesn't flinch with blood and gibs everywhere but having the dixel out somehow makes everyone act incharacter?

> like I said people already used the showers to get rid of blood on clothing. Can you tell me what you see in it that helps the game?

look at the hygiene thread in NTR hut before it deletes, I don't want to retype it.

> And how the same cant be achieved with a simple moodlet?

Because you can negate moodlets in various ways (still butthurt about antag moodlet but too lazy to fix), if the point is to get you to move around the station then something that can be ratified from anywhere in the station is probably not a good solution.

**Comment by habader** [comment]
orange man says no

orange man keep stink stink in code box

**Comment by wesoda25** [comment]
We shall wait oranges

**Comment by Garen7** [comment]
Reopening this at the request of Nervere and also because cobby said it was slated for removal, I'd rather qustinnus's tweaks for hygiene be tested first before anyone tries to merge this.

**Comment by wesoda25** [comment]
Poll: https://sb.atlantaned.space/polls/213

Poll Results: 
**579 Votes** Hygiene was a negative change
**349 Votes** Hygiene was a positive change
**178 Votes** Abstain

**Comment by nervere** [comment]
The /tg/ community has voted twice, overwhelmingly, to remove hygiene.
<https://sb.atlantaned.space/polls/205>
<https://sb.atlantaned.space/polls/213>
I sincerely hope the maintainers will respect the community's wishes on this matter.

**Comment by Qustinnus** [comment]
bit dissapointed that you won't even let the pr with changes be tested but then again you've only been able to be a toxic prick on discord for the last few weeks.

**Comment by nervere** [comment]
You had 5 months from the first poll to fix hygiene, Qustinnus.
Enough is enough.

**Comment by Qustinnus** [comment]
Except you started the second poll /after/ I made the PR, which clearly means you don't give a fuck about me trying to resolve the problems.

**Comment by optimumtact** [comment]
can you reopen this PR as a new one it's hard to see with all the nonsense being posted on it.

**Comment by Ziiro** [comment]
grunge code

**Comment by wesoda25** [comment]
while I wont miss it, admins disabling hygiene was not a good idea in the slightest

**Comment by optimumtact** [comment]
it's test merged you feral ape

**Comment by wesoda25** [comment]
ok idiot

**Comment by Garen7** [comment]
@oranges sure

**Comment by datorangebottle** [comment]
image
image


You were given several months you dingus. Rest in peace stench fetish code. We never wanted you and still don't. Never come back.

**Pull request closed without merging**
