### PR TITLE
Fix piping in Northstar Ordinance

### PR DESCRIPTION
**Pull request by Boopideedoo**
## About The Pull Request
I fixed a minor issue on northstar The issue was there was a piping disaster in toxins and I reworked it to be countered so it could work as intended now it works as its supposed to.
## Why It's Good For The Game
Pipe rework in northstar toxins
## Changelog
:cl:
Piping rework to fix an error
:cl:

### CODE REVIEW

**Comment by Boopideedoo** [comment]
> bwuh what's changed???

I fixed the main part that explains it but its essentailly a pipe rework in toxins

**Comment by Cheshify** [comment]
Oh yeah no worries you just gotta be clear about what's being done.

**Comment by Boopideedoo** [comment]
Im currently making a map ruin for something else that ill use placeholder ruin tiles for now

**Comment by Boopideedoo** [comment]
But northstar I fixed an annoying thing that will finally let toxins work

**Review by Maurukas — APPROVED** [review]
Good stuff. Having the burn chamber plumbed into waste loop was probably not a good thing.

**Pull request merged**
