### PR TITLE
[EXPERIMENTAL] applies some weird fucking BYOND memes to speed up Chemistry

### PR DESCRIPTION
**Pull request by Iamgoofball**
did I do it right @duncathan

### CODE REVIEW

**Comment by kevinz000** [comment]
Nice

**Comment by Iamgoofball** [comment]
also for reference some of the chemistry procs for add/remove and shit become pretty costly over time and like 75% of atoms have reagent holders so this helps i swear

**Comment by Jalleo** [comment]
How did we learn about this?

**Comment by Iamgoofball** [comment]
https://github.com/tgstation/tgstation/pull/25771#pullrequestreview-30617736

**Comment by Jalleo** [comment]
The next holy grail for SS13 coding has been discovered.

**Comment by Razharas** [comment]
Even if this is true(i doubt) this is a horrible way of doing it
The proper way is macro to define procs that resolves to two proc defines

**Comment by Iamgoofball** [comment]
idk how that works and we should test that

**Comment by RemieRichards** [comment]
```
#define DOUBLE_PROC_DEF(type, procname, ...) \
##type/proc/##procname(...)\
##type##procname(...)

eg:
DOUBLE_PROC_DEF(/obj/item/bodypart, dismember, damtype)
->
/obj/item/bodypart/proc/dismember(damtype)
/obj/item/bodypart/dismember(damtype)
```

but don't actually do this, if we do commit to this it should be a travis tool or something.

**Comment by Razharas** [comment]
Id prefer defines to side tools tbh

**Comment by RemieRichards** [comment]
I'd prefer the gamecode remain readable, I don't feel:
```
DOUBLE_PROC_DEF(sometype, somename, arg1, arg2, arg3)
    for(var/blah in 1 to 7)
        world << "blah"
```
is very readable.

**Comment by Razharas** [comment]
Looks fine to me
Not much worse than current byonds way

**Review by duncathan — CHANGES_REQUESTED** [review]
Use this opportunity to standardize documentation. It'll take care of how terribly ugly it looks the way it is RN.

**Comment by Cyberboss** [comment]
https://pastebin.com/5RTqKMuX

**Comment by Iamgoofball** [comment]
@duncathan 
This was already done.

Docs are on the overridden procs.

75% of procs here did not have docs, I'm not going to design docs for every single proc in here.

**Comment by duncathan** [comment]
@iamgoofball why not

**Comment by Jalleo** [comment]
Get on IRC testing is revealing discrepancies.

**Comment by Iamgoofball** [comment]
will do soon

**Comment by Iamgoofball** [comment]
@duncathan 
Because I don't have the time or patience to do that. It's not my job to document other people's code. This is all shit that shouldn't be touched unless you know what you're doing, and the shit that actually needs docs
1. already has docs
2. works just fine

**Comment by optimumtact** [comment]
I want a proper explanation of what is occuring here with more indepth explanation before we go cargo culting our code. Please just wait on these thanks.

**Comment by Cyberboss** [comment]
http://i.imgur.com/YX7jStr.png

**Comment by Iamgoofball** [comment]
Proven better???

**Pull request closed without merging**
