### PR TITLE
You can now quickbind up to 5 scriptures

### PR DESCRIPTION
**Pull request by ChangelingRain**
:cl: Joan
rscadd: You can now quickbind up to 5 scriptures from the recital menu, and the recital menu has less empty space.
tweak: Clockwork slabs now only start with only Geis pre-bound.
/:cl:

### CODE REVIEW

**Comment by jughu** [comment]
WHAT ABOUT TO GET RID OF THE SHITTY UI AND HAVE IT COMPRESSED

**Comment by ChangelingRain** [comment]
You are incoherent. Please become coherent.

**Comment by jughu** [comment]
Ok you have my vote

**Comment by Chnkr** [comment]
I still think that it would be better to automatically quick-bind all scriptures and use the tooltip system to show information about said scripture when the user hovers its mouse over the scripture.

Much easier than the clunky UI.

**Comment by ChangelingRain** [comment]
Binding all scriptures would result in a silly amount of buttons unless you had a button for each tier, for easy swapping, but even then that'd be 14-15 buttons per tier, which would be, uh, kind of a massive use of screen space.

**Comment by jughu** [comment]
Just have 5 buttons opening the tier UI

**Comment by ExcessiveUseOfCobblestone** [comment]
i'd actually be in favor or just reverting quickbind if I could be promised the old recollection.

**Pull request merged**
