### PR TITLE
Makes Breathmasks and (normal) Gasmasks printable at Auto/Protolathes

### PR DESCRIPTION
**Pull request by genessee596**
## About The Pull Request

Breath masks (the ones you start with in your internals box) can now be printed at all Autolathes and Protolathes for half a plastic sheet. (1000 cm2)

Gas masks (the ones you find in red lockers and maintenance) can now be printed at hacked Autolathes and the Science, Cargo, and Engineering Protolathes for one metal sheet. (2000 cm2)

That's it. Really.

## Why It's Good For The Game

I thought it was weird that the 'lathes can make gas tanks, but not masks. I also thought it was weird that the only type of gas mask that you could print was the fairly niche Welding Gas Mask after a fair amount of research.

Sure, for the most part breath/gas masks aren't that hard to find, but it's nice to have the consistency of being able to replace your old mask at the Autolathe instead of digging around the various blue/red lockers littered around the station.

## Changelog
:cl:
add: Spare breath masks can now be printed at all Autolathes and Protolathes.
add: Standard gas masks can now be printed in hacked Autolathes plus all Science, Engineering, and Cargo Protolathes.
/:cl:

### CODE REVIEW

**Comment by wesoda25** [comment]
Unlimited gas masks is bad

**Comment by zxaber** [comment]
Full-face masks should cost some glass for the eye lenses.

**Comment by genessee596** [comment]
> Unlimited gas masks is bad

Science already gets unlimited gas masks.

**Comment by genessee596** [comment]
> Full-face masks should cost some glass for the eye lenses.

I will consider this!

**Comment by ExcessiveUseOfCobblestone** [comment]
I want gas masks to be less common, they are perhaps the easiest item in the game that not only disguise you but completely negate certain items like pepperspray (citation needed) and smoke.

**Comment by genessee596** [comment]
> I want gas masks to be less common, they are perhaps the easiest item in the game that not only disguise you but completely negate certain items like pepperspray (citation needed) and smoke.

Science can already print infinite welding gas masks with basic research, which are better than normal ones.

**Comment by ATH1909** [comment]
why do these cost glass instead of plastic?

**Comment by Shadowflame909** [comment]
plastic cost would be the perfect middle ground.

Not too easy to get, but there roundstart for anyone willing to put the time into it.

**Comment by MrDoomBringer** [comment]
make it plastic

**Comment by Fikou** [comment]
we have a bunch of items that use glass/iron instead of plastic which would make more sense

**Comment by trollbreeder** [comment]
Aren't gas masks made out of rubber or something? Plastic would be the best stand-in for that.

**Comment by ExcessiveUseOfCobblestone** [comment]
> 
> 
> > I want gas masks to be less common, they are perhaps the easiest item in the game that not only disguise you but completely negate certain items like pepperspray (citation needed) and smoke.
> 
> Science can already print infinite welding gas masks with basic research, which are better than normal ones.

not really a justification to expand the problem to every fab.

**Comment by genessee596** [comment]
> > > I want gas masks to be less common, they are perhaps the easiest item in the game that not only disguise you but completely negate certain items like pepperspray (citation needed) and smoke.
> > 
> > 
> > Science can already print infinite welding gas masks with basic research, which are better than normal ones.
> 
> not really a justification to expand the problem to every fab.

It's not in every fab. It's in science (read above), Cargo (who can already get infinite breath/gas masks from orders) and Engineering (who actually use gas masks). Hacked autolathes are initially Cargo-only and sometimes engineering (assuming they bother to hack it) - while anyone can make an autolathe if they get the parts, gas masks are so plentiful (every red locker, everywhere in maint) that it wouldn't make any sense to do so solely for a mask.

**Comment by wesoda25** [comment]
Bad game design doesn’t justify making it worse. If anything we should find some way to limit science gas masks as opposed to extending the problem to half of the departments.

**Comment by genessee596** [comment]
> Bad game design doesn’t justify making it worse. If anything we should find some way to limit science gas masks as opposed to extending the problem to half of the departments.

I don't think it's bad game design in the first place.

**Comment by wesoda25** [comment]
I guess that’s the argument then. IMO its bad because firemasks are really useful - they completely negate a very powerful (if used correctly) security weapon, disguise a persons face, and fare well with fire and what not. I think that since they are way better than normal masks, if crewmembers were given a potentially infinite supply, they would always opt to wear them.

**Comment by necromanceranne** [comment]
Make it use plastic, not glass.

**Comment by Megarop** [comment]
> I want gas masks to be less common, they are perhaps the easiest item in the game that not only disguise you but completely negate certain items like pepperspray (citation needed) and smoke.


I think people easially being able to make themselves immune to tear gas and pepper spray with a gas mask is completely warranted, I always assumed they were _supposed_ to have their effectiveness balanced out by the fact that most people are immune to them anyway.

I don't know about chem grenade smoke, but pepper spray and tear gas in their current state would be busted if people couldn't easily make themselves immune to them.

**Comment by Fabian272** [comment]
Greytiders have never been more happy

**Comment by gitbirb** [comment]
noting the plastic comments, plastic aint easy to get no matter how much you try and will it because chem is stingy and wont do shit fast nor let you into do it. If your just going around looking for gas masks and cant find one, you're not gonna find plastic either.

**Comment by necromanceranne** [comment]
'The department that makes plastic doesn't make plastic enough' is not even remotely an excuse and makes me question the point of this even more if you want it so easily handed to you that you are willing to jump through such a massive logic hoop to enable it without inconvenience even on a minor level (there are sources of plastic on the station if you know where to look). 

Chemistry being the sole source of plastic is maybe the real issue here.

**Comment by ExcessiveUseOfCobblestone** [comment]
I'm fine with breath masks in every department, but gas masks should be made rarer given the value of one compared to other items you could put in that slot so i'm not sold on those even in the 3 departments.

If they are so abundant already then there's really no reason to make them mass printable. If you really need one you can always private order from cargo (I didn't see a gas mask buyable except as part of a set since I was curious how the material cost compared to the print cost).

**Comment by genessee596** [comment]
Breath masks now cost half a plastic sheet instead of half a glass sheet.

Gas masks remain unchanged at the moment.

**Comment by genessee596** [comment]
>  and fare well with fire and what not. 

Standard Gas Masks do not provide any protection against fire. You're thinking of either the Explorer Gas Mask or the Atmospherics (or Captain) Gas Mask.

**Pull request closed without merging**
