### PR TITLE
Emergency Tanks resprites

### PR DESCRIPTION
**Pull request by chanoc1**
:cl:
tweak: New sprites for the emergency oxygen tanks.
/:cl:

New sprites for the emergency oxygen tanks. I thought the old sprites were flat, I tried making these new ones more interesting visually, and they have some shading.
oxy
oxyengi

### CODE REVIEW

**Comment by anconfuzedrock** [comment]
change is bad, tbh I love it except for the fact that it doesn't fit so we'd need more changed

**Comment by chanoc1** [comment]
yeah that seems to be the big meme, a lot of the art clashes because of the lack of a palette. im planning on respriting a lot of things, and hopefully giving the station a unified look

**Comment by Kromgar** [comment]
Danno and chanoc1 are respritng so itll be cool

**Comment by chanoc1** [comment]
<o/ <-- thats a dab

**Comment by PKPenguin321** [comment]
grey bit on the bottom looks too flat

**Comment by chanoc1** [comment]
flat is in shading or flat as in shapewise

**Comment by PKPenguin321** [comment]
shapewise like it doesnt seem to curve with the bottom of the tank

**Comment by chanoc1** [comment]
ah, yeah i see

**Comment by chanoc1** [comment]
bottom is rounder now 
oxy
oxyengi

**Comment by Dorsisdwarf** [comment]
the orange is okay, even if it breaks all consistency with other atmos tanks and cans for no reason, but the blue looks horrible.

**Comment by chanoc1** [comment]
the orange one is orange like the extended ones??? also thanks for saying why the blue one is horrible, althought it could be purely subjective

**Comment by Dorsisdwarf** [comment]
Its just like, super flat ultra-bright blue next to deepest-dark night blue looks incredibly strange. Why is there this thick black line on the tank for no reason?

**Comment by chanoc1** [comment]
i can see where you're coming from, but it's just a consequence of the palette. i dont know what "thick black line" you're talking about though

**Comment by ExcessiveUseOfCobblestone** [comment]
give me a DMI with the palette so I can sprite like a big boy

**Comment by chanoc1** [comment]
i can just give the palette

**Comment by Kromgar** [comment]
Didn't Wjhohnston make the pallette? OR did Danno Finish

**Comment by chanoc1** [comment]
wj had his own palette, danno made his own as well

**Comment by MrPerson** [comment]
wake me up inside

**Comment by chanoc1** [comment]
??

**Comment by ExcessiveUseOfCobblestone** [comment]
PICK ONE

**Comment by chanoc1** [comment]
PICK ONE WHAT

**Comment by Supermichael777** [comment]
the blue range seems a bit stunted on that pallet

**Comment by Supermichael777** [comment]
as in their are literally 4 of them

**Comment by chanoc1** [comment]
ye

**Comment by Nienhaus** [comment]
WJohn has said himself that Danno's palette is better. Also the argument that it looks out of place or too good for SS13 is a bad one.

**Comment by Kromgar** [comment]
>only 4 blues

>9 different shades of green

**Comment by Ausops** [comment]
https://i.imgur.com/3Cgs77I.png
??

**Comment by chanoc1** [comment]
uhhh

**Comment by Ausops** [comment]
I noticed you used deep dark saturated fantasies/colours for your outlines, imo darker colours and outlines should be less saturated. Linework that isn't part of the outline of the sprite can be less dark, since you run into things like too much contrast between it and lightly shaded areas. Darker outline linework compared to inner linework also gives the sprite a nicer feel, best example of this abstract feel is pokemon sprites, who use dark outline linework iirc.

**Comment by chanoc1** [comment]
ill try a version with dark outlines

**Comment by Ausops** [comment]
Your outlines are dark enough, things that would improve your sprite would be more fidelity to existing sprite colours. I say this because the very pale blue you have for shading clashes badly with your dark and saturated choice of blue for the outline. The colour hues are also warmer for your outline and colder for your shading which feels very topsy turvsy for me.

Using a blue colour similar to the current tank would at least excuse the dark saturated colour for the outlines, since the current one is fairly saturated and not cold like your pale blue.

The same thing goes for the extended tank, if you want to make a theme change from yellow to orange that's ok but the dark saturated orange clashes against the less saturated orange shading you have going on.

The white banding also seems badly placed, as it is, the dark saturated outline might just be ok if it wasn't disrupted but especially for the normal emergency tank, the outline for the white part is overpowered by the dark blue. Different placing or darker outlines for the white part would alleviate this.

I'm not ripping into you, in case you are taking it that way

**Comment by PKPenguin321** [comment]
o-oh ausops sprites~ 😍

**Comment by xxalpha** [comment]
Can we please use ausops sprites instead

**Comment by Thunder12345** [comment]
Yeah just use the ausops sprites
Then tie him down and make him resprite the whole game

**Comment by WJohn** [comment]
Oh dear. Ausops came in to kick this PR's ass.

He really likes to do that sometimes.

Just so we're clear I'm not complaining. Ausops sprites pls <3

**Comment by KorPhaeron** [comment]
ausops made better ones sorry

**Comment by chanoc1** [comment]
<o/

**Pull request closed without merging**
