### PR TITLE
Fixes #25208[blob overminds getting sent to lobby on death] in theory

### LINKED ISSUE #25208: Dying as blob closes your connection and returns you to lobby when you reconnect
Upon dying you, get the "you're a blob!" message once again and your connection is closed.

### PR DESCRIPTION
**Pull request by silicons**
In theory.

### CODE REVIEW

**Comment by AnturK** [comment]
What was the cause here ?

**Comment by RemieRichards** [comment]
@AnturK looks like the overmind was never ```Destroy()```'d, just GC'd.

**Comment by RemieRichards** [comment]
also this won't fix it, as it'll qdel the overmind whenever any core it owns is destroyed.

**Comment by AnturK** [comment]
Mobs shouldn't get GC'd though ? We still tag them.

**Comment by RemieRichards** [comment]
@AnturK give me another explanation then.
go on.

**Comment by AnturK** [comment]
? I don't know, that's why i'm asking kevinz.

**Comment by RemieRichards** [comment]
No offence is meant here, but I very much doubt he understands what's happening here either.

**Comment by Cyberboss** [comment]
Do you guys have repro steps for this? Because I tried before and I couldn't figure it out

**Comment by optimumtact** [comment]
I don’t' buy this is the cause and you don't seem sure either.

**Pull request closed without merging**
