### PR TITLE
Lets chaplain use changeling tentacle as a weapon skin

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
:cl: Kor
add: The Chaplain may now choose the Unholy Blessing as a null rod skin.
/:cl:

I didn't add any special abilities to it, same attribute as the arm blade skin

### CODE REVIEW

**Comment by TechnoAlchemisto** [comment]
Often, when I'm playing chaplain, I've been looking at the list of nullrod skins, and felt like there was something missing. I love changelings, but the arm blade(a reference to my favorite game, prototype, and prototype 2) is just getting stale! Once again, KorPhaeron(awesome name btw) you've read my mind! Good to see our codebase is in good hands! 

Kerblam!
TechnoAlchemist

**Comment by GunHog** [comment]
When do Chaplains get (cosmetic only) skins for his armor?

**Comment by jughu** [comment]
change attack messages to tentacling

**Comment by Xhuis** [comment]
Might want to toss nodrop on there.

**Comment by FantasticFwoosh** [comment]
No thanks, i've seen chaplain's get dunked on downstream servers for having dark energy blade rod skins and the such because it triggers their valid salad sensors that we as a coderbase like to make fake antag sprites and it confuses their little noggins.

**Comment by Arianya** [comment]
Does it vibrate?

**Comment by Dorsisdwarf** [comment]
>

No thanks, i've seen chaplain's get dunked on  downstream servers for having dark energy blade rod skins and the such  because it triggers their valid salad sensors that we as a coderbase  like to make fake antag sprites and it confuses their little noggins.
--

thats the whole point of giving those to the chaplain, lets be honest.

**Comment by ExcessiveUseOfCobblestone** [comment]
you know you don't HAVE To select the skin if you're afraid of being considered a ling.

**Comment by pubby** [comment]
KOR I know you dislike PRs that are stupid weapon bloat with no rationale so why are you posting a stupid weapon bloat with no rationale PR KOR

**Comment by ExcessiveUseOfCobblestone** [comment]
it's a cosmetic difference

**Comment by KorPhaeron** [comment]
What cobby said

**Comment by FantasticFwoosh** [comment]
But it will be nessecary to hugbox & disable certain skins because they are fourth wall breaking and antag transcendent for that round where people get banned for not enunciating "Its a rev" properly and screaming ITS REVS.

- What next a pocket flash chaplain weapon?

Most lings and traitors i know actively target the chaplain first because nobody can tell the difference between the disguise & the (besides from destroying/abusing the crematorium) real thing without seeing it working.

**Comment by Iamgoofball** [comment]
the point of this is to metabreak fwoosh dont be an idiot

**Comment by FantasticFwoosh** [comment]
Metabreaking is bad because it never actually targets the problem as much as rubs salt in the wound with the hopes that when the swelling goes down it'll fix itself.

- I bet hippie will atleast ban the eldritch dark sword skin witihin the next two months

**Comment by optimumtact** [comment]
@TechnoAlchemisto I will gitban you

**Comment by Xhuis** [comment]
Would you make him *git* out?

**Comment by evsey9** [comment]
Next step: ERP verbs

**Comment by DoctoreMad** [comment]
You realize that while you're using a homestuck avatar we can't tell if you're being ironic?

**Comment by Ratvar** [comment]
Allow chaplain nullrod to take appearence of every item with force over 10, do et.

**Review by Cyberboss — APPROVED** [review]

**Pull request merged**
