### PR TITLE
Merges Malf AI and traitor AI into a single antag type, no longer has its own mode

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
oranges lied he didn't even fix merge conflicts properly the code didn't work anymore so here it is again, this time without touching prefs so I can test merge it.

And adds malf powers to traitor AIs. Malf is a dull mode that is usually 20-40 minutes of nothing followed by a few minutes of the same AI core assault by the handful of people with enough gear or access to do anything. Then the round ends. It's also a redundant mode considering AIs can and do go rogue and murder everyone in every other mode.

Pseduo-malf AI in traitor/DA rounds will open up possibilities like the AI working with badguys, badguys helping to stop the AI from nuking everything, stuff actually happening while the AI is hacking APCs, etc. It will also mean that AIs without cyborgs are not completely fucked.

Traitor AIs start with only 50 points to spend, but gain 10 more for every APC they hack.

For 180 points they can buy a nuke on a 400 second timer and blow the station up (if they live through the timer). This power triggers the usual malf sounds/runtime alert/ANGRY RED TILES.

TODO:

-Balance starting points/APC point gain/module cost. @GunHog please help with this you're the malf power guy

-Possibly tie cyborgs in with points (lose points upon borg activation, but allow you to sac them for points, make it cost points to hack them, etc). Cyborgs are a huge advantage for an AI but they're usually pretty helpless as an antagonist without them, so trading powers for borgs makes sense in my mind.

-Traitor/RD item to allow normal AIs to pick modules?

:cl: Kor
rscadd: Malfunctioning AIs have been merged with traitor AIs. They no longer appear in their own mode.
rscadd: Hacking APCs now gives you points to spend on your modules. Save up enough points and you can buy a nuke on a 500 second timer.
/:cl:

### CODE REVIEW

**Comment by KorPhaeron** [comment]
Oh christ those commits how do I squish everything

**Comment by Incoming5643** [comment]
Remain extremely ambivalent on this.

**Comment by Bawhoppen** [comment]
0/10 still

**Comment by Anonmare** [comment]
Still Supporting this tbh fam

**Comment by Aloraydrel** [comment]
tbh it sounds pretty good. though borg hacking should be free tbqfhmn

**Comment by Ricotez** [comment]
:+1:

**Comment by GunHog** [comment]
I still do not support removal of Malfunction as a mode :-1: 

It is similar to how blobs have to be toned down and weakened to happen as a random event, as the blobs in the game mode are designed to be standalone.

That is what will happen here, A Malf AI is too powerful to be placed with traitors. It will no longer be the focus and accordingly weakened.

To make my stance clear, I like the idea of a Traitor AI getting a bit more leeway, but I do NOT support removing the Malfunction mode entirely.

Try doing this as its own mode, <b>before trying to remove Malfunction</b>. Your PR as it is now is unacceptable and will need serious adjusting to still be fun for the AI player, AND the other traitors.

**Comment by KorPhaeron** [comment]
>A Malf AI is too powerful to be placed with traitors

Why?

It has a 17% winrate, malf is weak as shit.

And it isn't a question of pure strength, since it will be malf vs crew vs traitors, with different strategies/paths to victory available for all sides instead of the same tired meta strategies for two rigid teams

http://www.ss13.eu/tgdb/tg/stats_2015-10-29_to_2015-11-28.html#mode_AI_malfunction

**Comment by Nanotransistor** [comment]
Yea i agree, a traitor AI almost always ends up dead. With malf powers it could have a higher chance to not getting rekt instantly as well as making the round more interesting.

**Comment by newfren** [comment]
:+1:

**Pull request closed without merging**
