### PR TITLE
Edits the description of the Pirate Dutchman's mast

### PR DESCRIPTION
**Pull request by Jackraxxus**
## About The Pull Request

So I was observing the video game and then there were pirates cuz prog traitors n stuff and then I went over to the pirate boat and I was like "boy oh boy I sure to love this map it's a very unique take on space pirates" and then I examined the ship's mast and my immersion was destroyed beyond hope of recovery. This PR stops that.

## Why It's Good For The Game

It helps hide that the masts are just another item being reused for this purpose.

## Changelog

:cl:
fix: Examining the pirate Dutchman's mast will no longer shatter your immersion.
/:cl:

### CODE REVIEW

**Comment by timothymtorres** [comment]
The-thing-that-must-not-be-named

**Comment by timothymtorres** [comment]
We do not speak it’s name.

**Comment by Jackraxxus** [comment]
You will summon a great evil if you do.
Also idk how to change it ngl

**Comment by Mothblocks** [comment]
image

top right

**Comment by Jackraxxus** [comment]
I see

**Comment by Ryusenshu** [comment]
Immersion restored

**Comment by Ghommie** [comment]
Someone got to make it their own structure and not a varedited festive pole. I kinda despite it.

**Comment by tralezab** [comment]
> image
> 
> top right

just one like guys? lets get thiose nubmers up

**Pull request merged**
