### PR TITLE
disables the chameleon gun from use

### PR DESCRIPTION
**Pull request by ghost**
:cl: armhulen
del: chameleon guns are disabled for breaking the server
/:cl:

They're breaking the server right now, kevinz said they'd look into it but that's not now, so until then lets stop it from crashing

"why don't you fix it"
if neither of us are fixing it then it's still just sitting there crashing the server

sorry about the commits, blame oranges

### CODE REVIEW

**Comment by Shadowflame909** [comment]
Rip best meme gun. It's fun to prank people, but It seems there's no one who knows how to fix it. Or what the problem is.

**Comment by PKPenguin321** [comment]
nice commits

**Comment by Armhulen** [comment]
@PKPenguin321 yeah i gotta fix that, my bad

**Comment by CitrusGender** [comment]
correlation != causation

that being said though, this probably won't do much harm

**Comment by Armhulen** [comment]
@CitrusGender freon

**Comment by CitrusGender** [comment]
@Armhulen oxygen

**Comment by kevinz000** [comment]
at this point I'd believe people that said it's causing crashes unless anyone can figure out why the serve crashes when it's being heavily used and is fine when it's not being used. :man_shrugging: 
Regardless it'll be a bit until I can confirm what's doing it so temporarily disabling it is good.

**Pull request merged**
