### PR TITLE
Fixes vines damage

### LINKED ISSUE #20901: vines are invulnerable
i'm too shit to be reading @phil235 code so im just going to make a bug request while i try reading it

### PR DESCRIPTION
**Pull request by Cyberboss**
By @phil235 's recommendation
Fixes #20901

:cl: Cyberboss
fix: Kudzu now takes damage properly again
/:cl:

### CODE REVIEW

**Comment by phil235** [comment]
That's not what I meant, the error is the "force" argument.
It's awkward timing since I'm fixing that bug myself just now..

**Comment by CyberbossJHCB** [comment]
wait that WAS supposed to be '='? What's wrong with force?

**Comment by CyberbossJHCB** [comment]
Ahh fuck it I'll leave it to you @phil235

**Comment by phil235** [comment]
the force is the VINE's force, which I didn't know the var was even defined for structures... and that force is probably equal to zero. so you do zero damage in the end.

**Pull request closed without merging**
