### PR TITLE
Opening someone's inventory no longer gets blocked by buckling

### LINKED ISSUE #55933: opening someones inventory [drag person to self] tries  to buckle him to you with a loading bar
on fail it opens the invetory as it should

### PR DESCRIPTION
**Pull request by Yenwodyah**
## About The Pull Request
fixes #55933 
Basically just sets humans' can_buckle var to FALSE, this stops anything from buckling to a human without passing force = TRUE to buckle_mob, which we were doing anyways for the two ways of buckling to a human (piggyback rides and fireman carrying).

## Changelog
:cl:
fix: You no longer try to buckle a person to yourself when you open their inventory
/:cl:

### CODE REVIEW

**Review by Mothblocks — APPROVED** [review]

**Comment by optimumtact** [comment]
This is a garbage fix lol stop it @Jared-Fogle why would you approve this

**Comment by Yenwodyah** [comment]
@optimumtact You mean like, showing a popup to the player? That wouldn't make sense here since just dragging a human to another human to buckle them isn't supposed to work, you're supposed to do fireman carrying or piggybacking if you want to carry another player. 
It's just that having can_buckle set to true was making the game go through the do_after in user_buckle_mob before getting to human/buckle_mob where there's a check to stop normal buckling, so players would just see the buckling progress bar pop up before they could open someone's inventory.

**Comment by Jared-Fogle** [comment]
I don't think they mean literally, I think they mean the code of the human should decide whether the buckle action should result in a buckle. The problem with the fix is humans *can* buckle, and this code lies that they can't.

**Comment by Yenwodyah** [comment]
> The problem with the fix is humans _can_ buckle, and this code lies that they can't.

But human's can't buckle, really - not in the normal way. Humans are only supposed to be buckled to in their special snowflake ways of firemanning and piggybacking. Setting it to false makes sense because it just blocks off the normal buckling code path that humans don't use.

**Comment by EgorDinamit** [comment]
Oof, wouldn't this block _every_ buckling attempt? Including to chairs and such.

**Comment by Timberpoes** [comment]
I'm quickly drawing up a PR to fix this myself as the issue is a little bit more complicated and this is not the appropriate fix.

**Pull request closed without merging**
