### PR TITLE
updated icons for carrotcake, carrotcake_slice, tornado, raw_frenchtoast, bone_axe0, bone_axe1, meatballspaghetti

### PR DESCRIPTION
**Pull request by rlee595**
## About The Pull Request

I updated several icons to improve the aesthetics and make the make the icon more clear.

**Artwork Edits**
carrotcake original:

carrotcake updated:

carrotcake_slice original:

carrotcake_slice updated:

tornado original:

tornado updated:

raw_frenchtoast original:

raw_frenchtoast updated:

bone_axe0 & bone_axe1 original:

bone_axe0 & bone_axe1 updated:

meatballspaghetti original:

meatballspaghetti updated:

## Why It's Good For The Game

This improves the game because they make the icons more readily identifiable (and prettier).

## Changelog

:cl:
image: Changed the artwork for carrotcake
image: Changed the artwork for carrotcake_slice
image: Changed the artwork for tornado
image: Changed the artwork for raw_frenchtoast
image: Changed the artwork for bone_axe0
image: Changed the artwork for bone_axe1
image: Changed the artwork for meatballspaghetti
/:cl:

### CODE REVIEW

**Comment by rlee595** [comment]
Here are the old models in game:
oldspritesingame

Here are the new models in game:
newspritesingame

**Comment by rlee595** [comment]
I just realized I have to fix the bone_axe in hand stuff, will work on that.

**Comment by Wallemations** [comment]
I don't think Spaghetti and meatballs require tomatoes to craft
Also I'm pretty sure the tornado is a reference, which is why it's sprite is like that

**Comment by Pumpkinoe** [comment]
Yeah the tornado is a reference to mario bros 3/zelda's warp whistle, changing it kinda removes the reference
Rest of it looks good though!

**Comment by san7890** [comment]
i know it's your first time in github but we really would rather that you split up your PRs (Pull Requests) into multiple chunks (via multiple branches) because there's no real reason to bundle in a bone axe resprite with all of these food resprites (and might be the reason why this PR has lingered so long without a review). it's what we call being "atomic". it'd be silly to make a PR for every single icon state change but it would be appreciated in the future (or even right now) if you have three PRs that are like:

"Resprites some food (spaghetti, cake, and toast!)"
"Resprites tornados"
"Resprites bone axes"

because in case a maintainer decides that they don't like your cake re-sprites at all (just an example), it would be really silly to close out the entire PR especially if they liked your bone axes.

if you want to, you can probably just keep this PR as the "food PR", and then split out the tornado and bone axe sprites into their own branches and PR those. up to you of course but it might speed things up a bit.

**Comment by san7890** [comment]
also your changelogs are really cold and could be considered confusing to the average player. could you kindly change your changelog from something like

```txt
sprite: resprites bone_axe0
sprite: resprites bone_axe1
```

to

```txt
sprite: Resprites bone axes.
```

It doesn't have to be so cold, you can add your own personal flavor, but it just shouldn't really be overtly technical and head-scratching outside of the context of this PR (which is where changelog entries show up). If you like technical writeups, you're free to do those in your commit titles/descriptions

**Comment by san7890** [comment]
you're gonna want the git hooks to resolve this merge conflict, you can read about installing those here: https://github.com/tgstation/tgstation/tree/master/tools/hooks

**Comment by MTandi** [comment]
@rlee595 it seems like you've changed fireaxe icons by accident. Please fix these: 

image

**Comment by potato1234x** [comment]
please dont remove the tornado reference :(

**Comment by Mey-Ha-Zah** [comment]
I didn't realize someone already had a new bone axe design, I was in the middle of updating lavaland items and happened to check through github. While I like your design, there are some things I would do to it. Like so:
image

**Comment by Mey-Ha-Zah** [comment]
I do like your axe base design, so if you find yourself unable to finish the PR or unable to do inhands (I know they are a BITCH) I would like to use it with your permission.

**Comment by CoiledLamb** [comment]
> I got a concussion so I haven't been able to work on the project, go ahead!

omg! hope you are feeling better soon. good work on the PR so far!!

**Comment by Mey-Ha-Zah** [comment]
Yeah I feel that, head injuries are the worst, don't know the circumstances, but I feel you.

**Comment by san7890** [comment]
Yeah, this has been conflicted for two weeks now. Sorry to hear that you haven't been able to get any work done, but I'm going to close the PR now in order to allow other people (or yourself at a later date) to start cracking away at PRing these sprites to the repository. Do come back when you feel better though!

**Pull request closed without merging**
