### PR TITLE
Crafting recipes without an explicit name are now named after their results.

### LINKED ISSUE #77379: Raw mothic cheese pizza blanks out its construction text
Reporting client version: 514.1589

## Round ID:
[211744](https://scrubby.melonmesa.com/round/211744)

## Testmerges:
- [Feature: bitrunner, a new supply role](https://www.github.com/tgstation/tgstation/pull/77259)

## Reproduction:
image
those sure are [       ]'s that I've made

unsure if just a problem with Items With Long Names or just this being a specific case, but

### PR DESCRIPTION
**Pull request by FernandoJ8**
## About The Pull Request

What it says on the tin. The code comment accompanying the "name" var suggests this was already the case, but it was only true for the crafting UI.
Adjusted some other code that gets recipe names to account for this change.
## Why It's Good For The Game

Convenient, both as a fallback and for the sake of avoiding repetition where it isn't necessary. That said, I haven't gone out of my way to remove pre-existing names that match the result, in case that practice is still considered desirable. 
It also fixes #77379 and similar issues. 
## Changelog
:cl:
fix: crafting recipes without a name, such as the mothic pizzas, will inherit the name of the item they make
/:cl:

### CODE REVIEW

**Comment by Sealed101** [comment]
`It also fixes #77379 and any similar issues.`
reword so fixes is before the issue link so it auto-links the pr to the issue 

_For future reference, [these](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) are all the keywords that can be used to link issues/PRs._

**Comment by FernandoJ8** [comment]
> `It also fixes #77379 and any similar issues.` reword so fixes is before the issue link so it auto-links the pr to the issue
> 
> _For future reference, [these](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) are all the keywords that can be used to link issues/PRs._

Thank you!

**Comment by FernandoJ8** [comment]
This is currently causing the crafting window to crash when you try and search by name while having "Cook" selected. Drafting until I figure out how the hell to debug this.

**Comment by FernandoJ8** [comment]
Alright, it was the chemical recipes turned cooking recipes. They ran their parent's New proc before their own, so they added their resulting reagents to the result list of the recipe AFTER the parent proc already tried and failed to give them a name (since they had no listed results at that point). That made toLowerCase() runtime in PersonalCrafting.tsx when it tried to make the nonexistent name of the recipe lowercase. Old code avoided this by setting the recipe name to the result name when passing data in the crafting.dm file, after all the recipes have been initialised.

Fun!

**Pull request merged**
