### PR TITLE
Xenomorph sprites and tweaks!

### PR DESCRIPTION
**Pull request by GunHog**
Added new Xeno sprites by @WJohn!
- New small xeno sprites!
- New blood trails!
- New Xeno blood and gibs!
- Removed walk/run mode from Xenos.
- Alien sneaking is now an action button, small delay when sneaking.
- Fixed NPC xenos missing sprites
- <b>EDIT:</b> Royal Xenos now produce more meat and hide!

screenshot 2015-10-27 22 55 24

### CODE REVIEW

**Comment by PKPenguin321** [comment]
they look like they're wearing plastic muscles on their chests

**Comment by RemieRichards** [comment]
Pose is janky.

**Comment by WJohn** [comment]
Literally almost identical to what we have right now, except with lots of fixes and consistency tweaks.

**Comment by PKPenguin321** [comment]
I agree with Remie, their arms are so bent it looks like they're doing the chicken dance
also their tails seem to be coming from their feet, idk if the current sprites do that too but either way they shouldn't do that

**Comment by WJohn** [comment]
We literally have that for our current sprites, except even more so! Likewise with the tail, it already very nearly reaches the feet.

**Comment by Supermichael777** [comment]
the blood doesn't look bright enough. flat neon green was bad, but at least it said CARTOONISH ACID rather than vomit.

**Comment by Metacide** [comment]
Bloods looks much better. Any chance of gib pictures?

**Comment by WJohn** [comment]
Our vomit color is considerably more sickly pale yellow than this. I wanted to move the blood color to something closer to the movies, and lime green was just an eyesore.

**Comment by Dorsisdwarf** [comment]
Blood needs to be a tad more saturated. sleeping xeno sprite looks too square

other than that who give a fuck

**Comment by WJohn** [comment]
The squariness of the sleeping xeno is specific only to the sentinel, as it has dorsal tubes pointing in just the way that makes it look more square. This isn't the case with drones or hunters. I guess I could try and draw the head in a different way, though?

**Comment by GunHog** [comment]
Oh god, the critics are swarming! I was asked for a picture of xeno gibs...I tossed in some human ones for comparison:
image

**Pull request merged**
