### PR TITLE
Revert "Makes the TEG deconstructable"

### LINKED ISSUE #38526: TEGs are broken
Issue: TEGs are not working. You see, this is how working TEG before #38056 looks like
teg
It's generating 2 MW. Only admins can spawn it, and you can't get them, since all in rotation maps does not have TEGs. "Free power" issue solution? Maybe.

PR #38056 basically added three more sprites for TEG, and they can be constructed and deconstructed. You still need to get circuit boards from somewhere, and they also not require anything. But, now TEG is not working. Why?

Look. I'm recreating TEG. To prevent confusions, left loop = cold loop, and right loop = hot loop.
teg-new

Okay, it's recreated, and... Hey, what the hell, it's not even connecting with pipes.
teg-broken

I think this is because sprites for HORIZONTAL circulators ARE NOT the same. You, maybe, can say "Well, try to change loops, so input will be not on south but on north", and this can make sense, but, hell, it's not making sense since LEFT circulator not connecting to cold loop, but it supposed to, and input is supposed to be on south.

Even if i will put some gas in loop, it will still not work, you know why? Yeah, because circulators are not connected to pipes.
bandicam 2018-06-16 18-05-47-103

Possible solutions:
1) Revert #38056 
2) Add option to mirror circulators, then fix them so they will see and connect to pipes
solution
3) Just fix issue when they can't connect to pipes. I'm mostly fine with changing loop direction

How to recreate: Just try to make TEG

### PR DESCRIPTION
**Pull request by Amelia0010**
Reverts #38056

Basically, I unintentionally broke the atmos component of the circulators, and I've been trying to fix it over the last few days but can't for the life of me figure out how. If anyone wants to help before it's reverted, my attempt is right here: https://github.com/nichlas0010/tg-rebase/commit/0572c91ad32bb5f0abfa4e5fb79548aa81a7f259

I basically got as far as making it initialize in the right directions, and disconnecting and joining pipenets but I keep getting runtimes related to null gasmixes that I can't solve, so 🤷‍♂️ 

closes: #38526

### CODE REVIEW

**Comment by davethwave** [comment]
Once you are able to fix the problem please readd the TEG deconstruction pr.

**Comment by Cyberboss** [comment]
@duncathan

**Comment by praisenarsie** [comment]
...

**Comment by Cyberboss** [comment]
Is this loss?

**Pull request merged**
