### PR TITLE
borg tip time changes

### PR DESCRIPTION
**Pull request by SkeletalElite**
## About The Pull Request
It takes 2 more seconds to tip borgs and they self right in 20 seconds instead of 60

## Why It's Good For The Game
1 minute is a long time to immobilize someone and it takes no special items just a 3 second do after.
20 seconds is still a really long stun and it takes a couple more seconds so the no items required 20 second stun is a little harder to pull off

## Changelog

:cl:
balance: It now takes 5 seconds to tip a borg (from 3) and they self right in 20 seconds (from 60)
/:cl:

### CODE REVIEW

**Comment by JohnFulpWillard** [comment]
as the person who added it, I hate this idea.
3 seconds is how long it takes to handcuff someone, and 60 seconds is how long it takes to uncuff.
You can't stop a borg from untipping themselves either, like you can to humans via bucklecuff/moving them/stunning.

**Comment by SkeletalElite** [comment]
> as the person who added it, I hate this idea. 3 seconds is how long it takes to handcuff someone, and 60 seconds is how long it takes to uncuff. You can't stop a borg from untipping themselves either, like you can to humans via bucklecuff/moving them/stunning.

hand cuffs dont immobilize you

**Comment by JohnFulpWillard** [comment]
> > as the person who added it, I hate this idea. 3 seconds is how long it takes to handcuff someone, and 60 seconds is how long it takes to uncuff. You can't stop a borg from untipping themselves either, like you can to humans via bucklecuff/moving them/stunning.
> 
> hand cuffs dont immobilize you unless someone is dragging you or buckle cuffs you

Handcuffs do prevent you from interacting with stuff. being flipped over doesn't, you can still open/close/bolt/shock doors, you can still mess with nearby bots and APCs, you can still use your modules (including a flash)

**Comment by rdragan** [comment]
cope

**Comment by SkeletalElite** [comment]
> > > as the person who added it, I hate this idea. 3 seconds is how long it takes to handcuff someone, and 60 seconds is how long it takes to uncuff. You can't stop a borg from untipping themselves either, like you can to humans via bucklecuff/moving them/stunning.
> > 
> > 
> > hand cuffs dont immobilize you unless someone is dragging you or buckle cuffs you
> 
> Handcuffs do prevent you from interacting with stuff. being flipped over doesn't, you can still open/close/bolt/shock doors, you can still mess with nearby bots and APCs, you can still use your modules (including a flash)
> 
> Edit to your edit: 15 cables make cablecuffs

cable restrains only take 30 seconds rather than 60 and is still more than nothing

**Comment by SuperNovaa41** [comment]
> > > > as the person who added it, I hate this idea. 3 seconds is how long it takes to handcuff someone, and 60 seconds is how long it takes to uncuff. You can't stop a borg from untipping themselves either, like you can to humans via bucklecuff/moving them/stunning.
> > > 
> > > 
> > > hand cuffs dont immobilize you unless someone is dragging you or buckle cuffs you
> > 
> > 
> > Handcuffs do prevent you from interacting with stuff. being flipped over doesn't, you can still open/close/bolt/shock doors, you can still mess with nearby bots and APCs, you can still use your modules (including a flash)
> > Edit to your edit: 15 cables make cablecuffs
> 
> cable restrains only take 30 seconds rather than 60 and is still more than nothing and immobilization is even worse than preventing interaction in terms of how fun it is to have happen to you

Then make it 30 seconds?

**Comment by SuperNovaa41** [comment]
> cable restraints take 45 seconds just for general info

cable cuffs take 30, ziptie cuffs take 45

**Comment by MrDoomBringer** [comment]
Mild reminder that cuffing and immobilizing humans for a full 90 seconds EVEN LESS effort and preperation than tipping a borg, and makes them FULLY unable to interact at all for the first minute. A tipped borg can still interact, etc. 

This kind of nonlethal combat has been a part of the game with humans for years. Don't complain and make a kneejerk PR just because borgs can have consequences for their actions other than flash + kill with a toolbox.

**Comment by ATH1909** [comment]
> as the person who added it, I hate this idea. 3 seconds is how long it takes to handcuff someone, and 60 seconds is how long it takes to uncuff. You can't stop a borg from untipping themselves either, like you can to humans via bucklecuff/moving them/stunning.

60 seconds is how long it takes to undo sec-grade handcuffs. imo, 30 seconds should be used instead, since that's how long it takes to undo cable cuffs.

**Comment by thgvr** [comment]
should just remove borgs tbh

**Comment by Mothblocks** [comment]
Sorry Im listening to the people 14 dislikes

**Comment by optimumtact** [comment]
wtf democray?

**Pull request closed without merging**
