### PR TITLE
Fixes spelling errors in misc.dm

### PR DESCRIPTION
**Pull request by Imaginos16**
## About The Pull Request
Does what it says on the tin.

## Why It's Good For The Game
Spelling mistake stupid, good grammar good.

## Changelog
:cl:
spellcheck: Now CentCom cap, french beret and coordinator cap don't have spelling mistakes.
/:cl:

### CODE REVIEW

**Comment by notfrying1pans** [comment]
i think Centcom Commander would be proper, no?

**Comment by Imaginos16** [comment]
> i think Centcom Commander would be proper, no?

Its improper capitalization, CentCom is spelt like this, commander should be lowercase.

**Comment by celotajstg** [comment]
Found another one on line 429:
`A quality beret, infused with the aroma of chain-smoking, wine-swilling Parisians. You feel less inclined to engage military conflict, for some reason.`

Should be "engage **_in_** military conflict".

**Comment by Imaginos16** [comment]
> Found another one on line 429:
> `A quality beret, infused with the aroma of chain-smoking, wine-swilling Parisians. You feel less inclined to engage military conflict, for some reason.`
> 
> Should be "engage **_in_** military conflict".

Nice catch, fixed that one as well.

**Pull request merged**
