### PR TITLE
Gives meatballs the right name for inhand sprites

### PR DESCRIPTION
**Pull request by Hoolny**
## Why It's Good For The Game
Makes it so you can see when someone is holding a cooked meatball yummy
dreamseeker_bXP6P0cmh8

## Changelog
:cl:
fix: fixes meatballs not having inhand sprites
/:cl:

### CODE REVIEW

**Comment by jughu** [comment]
Old meatball sprite... soulfull

**Comment by jughu** [comment]
Though not a fix

**Comment by Ghommie** [comment]
> Though not a fix

The name of one of the icon states for held meatballs used to be lingo not complainant with github ToS (something that escaped #50488). Since we cannot have such lingo anywhere in the (readable) code lest we have a deathwish, you better believe it's a fix, since those sprites weren't being used.

**Comment by SethLafuente** [comment]
> Though not a fix

It is the name of the meatball sprites didn't fit with the name of the current meatballs someone probably forgot to updated it also there was nothing to relay back to hand holding item

**Comment by jughu** [comment]
> > Though not a fix
> 
> The name of one of the icon states for held meatballs used to be lingo not complainant with github ToS (something that has escaped #50488). Since we cannot have such lingo anywhere in the (readable) code lest we have a deathwish, you better believe it's a fix and that those sprites weren't actually being used.

i forgot that part. this is surely a memory trip back guh

**Pull request merged**
