### PR TITLE
Adds a new lizard-exclusive martial art, Tribal Claw.

### PR DESCRIPTION
**Pull request by Zonespace27**
## About The Pull Request
Ports (with some edits) BeeStation/BeeStation-Hornet#3011 and associated fix PRs

This PR adds a new martial art to traitor uplinks for lizards for 13 TC.
The martial art of tribal claw is a lizard-exclusive marital art that lets lizards utilize their tail and claws to do extreme damage to their opponents with combos.

## Moveset
**Disarm, Disarm, Grab, Harm**: Tail Sweep
Tail sweep is a combo move that lets a lizard spin around, sending anyone within 1 tile of them flying 4 tiles away. Mechanically, this move operates very similarly to the xeno tail spin.
**Harm, Disarm**: Face Scratch
Face scratch is a very simple combo move that deals an extra 10 (non-armor piercing) brute damage, on top of 5 confusion and 5 eye blur (spraying someone with a spray can applies 3, for reference).
**Harm, Harm, Grab**: Jugular Cut
Jugular cut is one of the stronger moves that Tribal Claw grants, dealing 15 (non-armor piercing) brute damage to the head, on top of applying a severe wound to the head and the "slit throat" status effect. The pre-requisite to being able to use this ability is that the target either needs to: be in critical condition, be in a neck choke by the attacker, or be asleep.
**Disarm, Harm, Grab, Grab**: Tail Grab
Intended to combo with jugular cut, the tail grab is a strong move at allows the attacker to disable the defender with ease. On executing this move, the defender will be instantly put in a chokehold by the attacker, in addition to being silenced for a short period of time.

## Why It's Good For The Game
Martial arts are good and fun, and this one has enough flavor that I felt like it was worth adding to the game. In addition, there's not much in the way of race-restricted items (a whole **1**), and this helps increase the amount by double.

## Changelog

:cl:
add: Added tribal claw martial art to lizard traitor uplinks for 13 TC
/:cl:

### CODE REVIEW

**Comment by optimumtact** [comment]
welcome to the repo, species changes require **Prior** maintainer approval, have a ~~nice~~ day

**Comment by optimumtact** [comment]
also, I don't want any species specific martial arts, I don't even like our martial arts implementation

**Comment by Zonespace27** [comment]
> welcome to the repo, species changes require **Prior** maintainer approval, have a ~nice~ day

Apologies, misunderstood that policy as "direct changes to species" instead of "changes pertaining to species, directly or not"

**Comment by Hamurlik** [comment]
here goes another cool feature down the drain, thanks trannies

**Pull request closed without merging**
