### PR TITLE
Adds cameras to emergency shuttles

### PR DESCRIPTION
**Pull request by Ical92**
## About The Pull Request

Adds cameras to each of the five emergency shuttles, which are linked to the consoles in the bridge of each, as well as adding a telescreen to the KiloStation shuttle to view the new cameras.
### Mapping March
Ckey to receive rewards: N/A

## Why It's Good For The Game

The emergency shuttles for the five stations all had consoles to view cameras (other than KiloStation), but no cameras of their own, and were not properly linked to any other camera network. Now the shuttles have their own camera network that can be accessed properly from the shuttle console.
## Changelog
:cl:
add: Added security cameras to the five "default" shuttles
add: Added camera telescreen to KiloStation Emergency Shuttle
/:cl:

### CODE REVIEW

**Comment by SgtHunk** [comment]
How does this interact with AI? Does it mean AIs can now look at the shuttle from anywhere? And if so, wouldn't this mean that AIs can now look at CentCom when the shuttles spawn at roundstart or are bought?

**Comment by Ical92** [comment]
> How does this interact with AI? Does it mean AIs can now look at the shuttle from anywhere? And if so, wouldn't this mean that AIs can now look at CentCom when the shuttles spawn at roundstart or are bought?

Haven’t had the chance to test with AI but I believe it lets the AI see from it, but not jump to it (Such as when it’s in CentCom)

**Comment by SomeoneYouProbablyKnow** [comment]
We'd need a good samaritan who plays malf to assess this change from a balance viewpoint probably

**Comment by Loafin34** [comment]
malf AI buff. i don't quite like it, the whole point of the emergency shuttle is that it's made for emergencies-- no need for cameras IC, since there's the brig and it's quite small (usually)

**Comment by Dorsisdwarf** [comment]
I think this will make boarding-the-shuttle doorshock-doorcrush for bad AIs much easier, but these days its much less of a showstopper with the proliferation in ways to smash doors down and knock out cams with toolboxes.

**Comment by zxaber** [comment]
It's probably not a huge deal, since the AI can already just send a borg to do it.

If you really want to be fancy, though, you could make these cameras a subtype that don't enable until the shuttle arrives at the station. That'd prevent AI nonsense on the Centcomm level.

**Comment by Ical92** [comment]
> It's probably not a huge deal, since the AI can already just send a borg to do it.
> 
> If you really want to be fancy, though, you could make these cameras a subtype that don't enable until the shuttle arrives at the station. That'd prevent AI nonsense on the Centcomm level.


Testing how it works with the AI right now, but based on what other people have said, I don't think the cameras on CentCom will be too much of an issue since, (again, according to what I've read) cameras that aren't on the ss13 network might only provide vision but are not able to be jumped to, meaning they wouldn't have any use for the AI until the shuttle is on a Z-level it can already view.

**Comment by Ical92** [comment]
Alright so yeah, the AI is able to view the cameras while it's still in CentCom, however there's also no way for it to access those cameras normally because you would need to jump to the network, and the emergency_ss13 network isn't included in the list of networks the AI can jump to.

Once the shuttle arrives at the station the AI is able to see from the cameras, but can't jump to them like they would be able to with other cameras on the station.

**Comment by SgtHunk** [comment]
> Alright so yeah, the AI is able to view the cameras while it's still in CentCom, however there's also no way for it to access those cameras normally because you would need to jump to the network, and the emergency_ss13 network isn't included in the list of networks the AI can jump to.

this does remind me of the oversight (maybe fixed? haven't tried) where the jump to mob function doesn't check for network, so it'd be possible if there was a mob on the camera's sight
Only occurrence I've seen of this is when trade route spawns (because the fighters have a camera to see outside)

**Review by Time-Green — CHANGES_REQUESTED** [review]
You blocked off the table on the kilo shuttle with the camera console, could you unblock it or move things around somehow?

**Comment by Ical92** [comment]
> You blocked off the table on the kilo shuttle with the camera console, could you unblock it or move things around somehow?

image
Would something like this work? Having either the camera console or shuttle console in the middle?

Also, tested the AI tracking, seems like it isn't able to track the mobs on a different network, so that shouldn't be an issue either.

**Comment by Time-Green** [comment]
> > You blocked off the table on the kilo shuttle with the camera console, could you unblock it or move things around somehow?
> 
> image Would something like this work? Having either the camera console or shuttle console in the middle?
> 
> Also, tested the AI tracking, seems like it isn't able to track the mobs on a different network, so that shouldn't be an issue either.

Yeah thats fine, issue is when the table is blocked from all sides with solid objects

**Comment by Ical92** [comment]
Ended up using the wall space there to instead add a telescreen there to save space, meant to mention that earlier but I guess it didn’t send.

**Pull request merged**
