### PR TITLE
Traitor Cooks now have access to the CQC manual

### PR DESCRIPTION
**Pull request by Iamgoofball**
:cl: Iamgoofball
add: Traitor chefs now have access to the CQC manual in their uplink
/:cl:

### CODE REVIEW

**Comment by Qustinnus** [comment]
God bless

**Comment by Ordonis** [comment]
I wholeheartedly support this. After all, he is the cook.

**Comment by outbools** [comment]
Close quarter cooking????

**Comment by arsserpentarium** [comment]
Why traitor?

**Review by Cyberboss — APPROVED** [review]

**Comment by Anonmare** [comment]
Chef, try to remember the basics of CQC

**Comment by KorPhaeron** [comment]
I like how naksu is doing it more

**Comment by Iamgoofball** [comment]
agreed

**Pull request closed without merging**
