### PR TITLE
Security Webbing Vest

### PR DESCRIPTION
**Pull request by Steelpoint**
A new alternative armour vest is avaliable to security officers. This 'webbing vest' offers almost no protection (10 melee only) but instead offers four extra inventory slots to hold most security items (sans Stun Batons).

Pick between protection or a expanded inventory.

altvest

:cl: Steelpoint
add: A new alternative armour vest is avaliable in security officer lockers. This 'webbing vest' offers no protection, but lets you carry up to four extra security items on you. Protection or storage? You decide!
/:cl:

### CODE REVIEW

**Comment by optimumtact** [comment]
oh you know how cheridan feels about storage creep steelpoint, this one is dead in the water

**Comment by kevinz000** [comment]
awesome, i can carry more 15x15 aoe stun grenades!
ily steelpoint <3

**Comment by Steelpoint** [comment]
Either way if this is accepted or denied I hope to expand this to other items that could use this. At minimum the Detective's Holster, maybe the Miners Webbing.

I'll wait and see what the powers that be have to say on this particular addition.

**Comment by jughu** [comment]
S T O R A G E. C R E E P.

**Comment by jughu** [comment]
And why does hos get a cool tactical black one and officers get a gay brown looking one

**Comment by jughu** [comment]
Basically pr. Job belts 2.0

**Comment by Steelpoint** [comment]
I did not realise this was attempted before. 

I'm using the sprites we already have plus the bay version for the officers. I could trim down the black version and use that as the standard sprite.

**Comment by lzimann** [comment]
The storage creep is real

**Comment by Grazyn** [comment]
This is arguably worse than the job belt PR creep-wise, since this adds plain extra storage in addition to the belt and not just more belts for other jobs

**Comment by Steelpoint** [comment]
I don't believe this is horrible nor will it pave the way for suddenly allowing you to cram handcuffs into every nook and cranny of your uniform.

Security almost never seems to get any kind of alterations of any form. I believe this change will be a positive one that gives Officers slightly more room to hold extra equipment.

**Comment by FantasticFwoosh** [comment]
@Steelpoint it literally will though, its functionally the reason for it existing.

If this was a higher capacity belt slot item & also only availible in limited supply from crates & warden/armory/hos locker in line with how mining uses theirs it would be more acceptable

**Comment by Dorsisdwarf** [comment]
I dont even like the idea of the item, you're an armed security guard not a commando infiltrating syndicate HQ. If you cant fit it in your belt put it in your backpack.

**Comment by FantasticFwoosh** [comment]
@Dorsisdwarf 's point rings true, it might be better as a sprite replacement for the ugly red (or just pushed into traitorous usage) army belt.

**Comment by Steelpoint** [comment]
Most law enforcement use a form of chest rigs/webbing.

**Comment by FantasticFwoosh** [comment]
We already have belts, unless you want to a make belts better, the chest rigging will basically make security belts redundant and lead to more security item hoarding creep.

> Critical problem where adding more space will mean people gearcheck obsessively for every eventuality and hoard security items.

**Comment by Dorsisdwarf** [comment]
Maybe thats a US thing -shrug- most coppers in the UK carry their shit in/on their belt *or* on pouches built into their stab vests

**Comment by Steelpoint** [comment]
I fail to see how the webbing will make belts redundant.

The webbing only holds two items and it can't fit medium or larger items like a baton.

If I want to "inventory creep" my way out I can just get a ton of cardboard boxes and carry as much handcuffs and flashbangs as possible.

**Comment by Steelpoint** [comment]
This seems unpopular and unlikely to go anywhere.

I'll revisit the idea at a later date, I'll also eventually get around to the second part of adding this function to the holster.

**Comment by Steelpoint** [comment]
I was thinking before I closed if I should instead change the webbing into a alternative armour vest.

The idea being you chose between a armour vest that grants you armour (currently), or a tac vest that provides NO armour whatsoever, but lets you hold a few extra items.

**Comment by Steelpoint** [comment]
I've restyled this PR.

Now its a alternative armour vest. This vest offers no protection (sans 10 melee) but it can hold up to four security items (sans Stun Batons).

I think this is more fair.

altvest

**Comment by Mark9013100** [comment]
black vest looks ugly as fuck

**Comment by SgtxRootbeer** [comment]
>inb4 every officer uses it because normal armor is shit, and every serious threat the officers deal with has weapons with stupidly high armor penetration.

**Comment by Steelpoint** [comment]
Not my fault armour is so ineffective you only wear it to hold your Taser.

**Comment by SgtxRootbeer** [comment]
Ya, but this is practically a straight buff...

**Comment by BeeSting12** [comment]
Does this vest still get the taser slot

**Review by Cyberboss — APPROVED** [review]

**Comment by Steelpoint** [comment]
Yes it does.

**Comment by Steelpoint** [comment]
I'll leave this for now, maybe I'll revisit it as a alt belt but that's unlikely.

**Comment by kevinz000** [comment]
lmao

**Pull request closed without merging**
