### PR TITLE
Adds an aesthetic new space ruin with original content (hi bawhoppen)

### PR DESCRIPTION
**Pull request by Cheridan**
:cl: Cheridan
add: Added an aesthetic new space ruin
/:cl:

nqxhnm1

### CODE REVIEW

**Comment by Cheridan** [comment]
Shoutout to the Anon on singulo who requested this like a year ago.

I never forgot. I never forget.

**Comment by coiax** [comment]
"I've looked everywhere but can't find anything to eat... or a clue to get me off the ship. Just more audiologs. They're everywhere! For some reason, I listen to every minute of every one of them thinking there'd be some useful information; but it's like they're just FILLERS! USELESS FILLER... THEY'RE FILLER THAT'S DRIVING ME TO MADNESS!"

**Comment by Incoming5643** [comment]
I only upload high quality ruins

**Comment by RemieRichards** [comment]
We can only go so far.

**Comment by optimumtact** [comment]
I only want your highest quality ruins ruin seller.

**Comment by Incoming5643** [comment]
We need to debate if the special hipster glasses should spawn here

**Comment by MMMiracles** [comment]
special hipster earwear that makes it so all you hear is a e s t h e t i c.

**Comment by Bawhoppen** [comment]
hi

**Comment by PKPenguin321** [comment]
those statues with the toolboxes are godly

**Comment by AnturK** [comment]
So uh, you forgot to add the map itself.

**Comment by TheWiznard** [comment]
wait are those slow-time floors? it would be cool if it affected instruments

**Comment by Cheridan** [comment]
@AnturK 
hqdefault

**Comment by optimumtact** [comment]
The ruin is so asthetic it maps itself, no dmm required.
An incredibly asthetic image, it makes you weep tears of joy

**Comment by optimumtact** [comment]
Closed until Cheridan adds the dmm

**Comment by Incoming5643** [comment]
Unless it's changed recently you won't be able to tell that updates have been pushed to the PR until it's reopened, so closing it is a bit of a headache.

**Comment by optimumtact** [comment]
That's Cheridan's problem, not mine

**Comment by Alek2ander** [comment]
:-1: Unable to pry the precious toolbox from the statue's dead marble hands.

**Comment by HankMoodyExperience** [comment]
but theres nobody here
[https://www.youtube.com/watch?v=sR7eADGQYg8]

**Pull request merged**
