### PR TITLE
What if meteorslugs were mini cannonballs

### PR DESCRIPTION
**Pull request by necromanceranne**
## About The Pull Request

Meteorslug shells fire effectively mini cannonballs. They're not as strong, but they tear through everything they shoot, including walls and airlocks. They're not as lethal as the real deal or go nearly as far (range of 7, not even a screens length), but they are still pretty destructive. They don't fling people, but they could potentially barrel over several people, which I think is a good trade-off.

Meteorslugs need gunpowder (for a bigger shot) and rum (yarr) to construct.

## Why It's Good For The Game

Only through sleep deprivation do I get such diabolical ideas.

Also, the original functionality wasn't very interesting except for like, maybe a few niche silly things, but the real value was using them to get into places. This version still definitely does that. But it's _cooler_. 

(The object displacement was pretty jank and I think this accomplishes a very similar effect without actively harming why people would look to use meteorslugs)

## Changelog
:cl:
balance: Meteorslugs are now miniature cannonballs. They also need more gunpowder and rum to be constructed.
/:cl:

### CODE REVIEW

**Comment by GuillaumePrata** [comment]
Meteor slug had a funny niche as a crowd control + break in ammo that was "easy" to get.

Now this cannonball version need chemistry while we already have an ammunition that needs chemistry (hence almost never made), the frag12.

IMO it would be a lot more interesting to turn the frag12 into cannonballs than the meteor slugs. The frag12 is too annoying to make and is not fun to use either.

**Comment by necromanceranne** [comment]
It still is a crowd control and B&E projectile. If the chem limit is offputting, then that limits doing its job weeding out anyone unwilling to go past the low barrier of entry of 'I don't want to talk to chemistry for some gunpowder'.

Frag-12 is annoying because waiting on corn takes a little bit. Gunpowder you can make roundstart with the multiver supplies and saltpetre. A chemist can wipe it together fairly quick.

**Comment by Livrah** [comment]
Sounds like pulse rifle slugs, which exists and reasearchable.

**Comment by necromanceranne** [comment]
I think there actually is value in a precision demolition ammo. This just flattens everything in front of you. Pulse stops at first dense object. (Also easier to make)

(This is true even currently, pulse is just easier to make and does meteorslugs job a lot more reliably)

**Comment by GuillaumePrata** [comment]
> (This is true even currently, pulse is just easier to make and does meteorslugs job a lot more reliably)

Not really, it delete walls, but if the target is not a wall it only does low damage
Pulse has no crowd control, you can't shoot a vending machine into someone's head, can't shoot a mech away from you, can't shoot a window or airlock out of the frame to block people into a corner

To say that Pulse does Meteor's job but better you need to ignore all of it's funny features.

**Comment by necromanceranne** [comment]
That's all cute, but it's only that.

**Comment by GuillaumePrata** [comment]
And so is the version you are suggesting, cute, but I doubt we will see it being used after the novel dies.
I could understand changing meteor slugs because it is poorly designed but it really looks like you had a cute idea and didn't think much of the best way to implement it. Meteor slugs are definitely the most interesting tech ammo we have while Frag12 is there in the corner being boring 1 hit kill ammo. Only held back by the fact no one uses it to realize how poorly designed it is.

**Comment by necromanceranne** [comment]
I'm not even going to disagree with your opinion on Frag-12, it really is shit, but besides the chemical recipes, what does it matter what Frag-12 is or isn't? If you want to change Frag-12, please go do that yourself. This isn't the place to talk about it.

I just want to shoot literal meteors at people with my gun. Let's not overcomplicate the intent here. It's goofy and fits the name better (meteors do fairly similar things, flattening everything in their path). Maybe you should just go reintroduce this functionality with Frag-12, make it a bit easier to make (nobody would blame you), and get the best of both worlds.

**Comment by GuillaumePrata** [comment]
The issue is that if your PR replaces meteor slugs with a new ammo completely while keeping the name.

I love how our meteor slugs work right now so I will be disappointed if it is removed, but if I/someone else just replaces Frag12 or introducing a new ammo that is the old meteor slugs with new name, we shit on the codebase/players by doing confusing circular changes and that is just worse IMO.

You're right that I shouldn't be rambling here and that your PR goal is simple and good, so I apologize for that.

**Comment by necromanceranne** [comment]
Don't stress it man, I get where you're coming from.

(Honestly I think you could maybe pull off a name swap, always worth a try)

**Pull request merged**
