### PR TITLE
New egun sprite

### PR DESCRIPTION
**Pull request by actioninja**
:cl: memager/actioninja
imageadd: New sprite for the Energy Gun
/:cl:

Memager made a new egun sprite that I thought was pretty good so I actually implemented it in game.
Looks like this:
egun_base
Here's in game and with all the states:
image

### CODE REVIEW

**Comment by Steelpoint** [comment]
Not to comment on the aesthetics but do the attachments (light) line up properly with the new sprite?

**Comment by actioninja** [comment]
I forgot about that, let me go test it.

**Comment by actioninja** [comment]
It's a little wonky looking, but not too bad:
image

**Comment by Borisvanmemes** [comment]
It looks good but the E-gun sprite doesn't need changing tbh.

**Comment by lolman360** [comment]
these are some sexy eguns

**Comment by Militaires** [comment]
man i never understand this argument, HEY THIS SPRITE LOOKS BETTER THAN THE OLD ONE BUT THE OLD ONE "DOESNT NEED CHANGING", nigga what

**Comment by Steelpoint** [comment]
You could appeal to sentimentality that its a necessary change over something that's good enough.

Either way, I'm fine with new or old sprites.

**Comment by anconfuzedrock** [comment]
I don't like it not because it's new, but because it's harder to tell if the flashlight is attached.
I don't see how this is an improvement either though, the old design was sleek and simple, you could tell it was an egun, it didn't disgust your eyes, blah blah. this thing has a black toblerone stuck to the bottom of it for no real reason, it's like if skyrims intro started with a confusing carriage ride where you can't move OH WAIT

**Comment by actioninja** [comment]
The old one doesn't match the art style of practically every newer sprite.

**Comment by Arianya** [comment]
Remember when people were losing their mind over toolbox sprites changing

Me neither because it was dumb and I discarded the memory.

**Comment by Memager** [comment]
> I don't like it not because it's new, but because it's harder to tell if the flashlight is attached.
> I don't see how this is an improvement either though, the old design was sleek and simple, you could tell it was an egun, it didn't disgust your eyes, blah blah. this thing has a black toblerone stuck to the bottom of it for no real reason, it's like if skyrims intro started with a confusing carriage ride where you can't move OH WAIT

the taser had the toblerone too

https://media.discordapp.net/attachments/481034325849276416/506752542793793539/unknown.png

**Comment by GuyonBroadway** [comment]
I think it looks too much like a rifle when Eguns are usable one handed.

**Comment by Memager** [comment]
pretty sure some warops guns can be used one handed

**Comment by GuyonBroadway** [comment]
Ye but all of those are smg sized at best (cept maybe the shotgun but terminator 2 has shown us that read bad dudes use shotguns 1 handed)

**Comment by actioninja** [comment]
If you can find a rifle with these proportions, tell me. This is SMG sized at best, it pretty closely matches the size of the old sprite.

**Comment by actioninja** [comment]
I stand corrected.
To be fair though, that thing is shorter than an MP5.

**Comment by JStheguy** [comment]
> the taser had the toblerone too
> 
> https://media.discordapp.net/attachments/481034325849276416/506752542793793539/unknown.png
Toblerones are the height of tacticool weapon design, donchaknow.

**Comment by anconfuzedrock** [comment]
Jokes on you I don’t care for the taser sprites either and they were first created to distinguish it from non hybrid tasers

**Pull request merged**
