### PR TITLE
Material datum color update, plus touching up some material items (knight armor, tiles)

### PR DESCRIPTION
**Pull request by necromanceranne**
## About The Pull Request

Tries to bring the material datum colors in closer approximation to the stacks they're attached too. I literally used the colors on the stacks. some might need to be lighter or darker, but for the most part they'll look...closer to their actual material hues.

material datum stuff 2

I've also tweaked the sprites of both the tile object and the actual material tile turf to give it the right shading.

image

In addition to the tiles, I've also updated the knight armor and helmet to look closer to the much higher quality plate armor already in the game. 

## Why It's Good For The Game

It bothered me that the material datum coloring was inconsistent with the actual colors used for the material stacks. When they were updated, and even before they were updated, material datum stuff just never looked _right_. I wanted to change that so that it looks just right.

I did not like the old material knight armor whatsoever. It was a dithered mess, and seemed to already use parts of the standard plate armor but with all the actual shading removed or replaced with the wrong colors. This fixes that so that the armor is actually readable for what it is.

## Changelog
:cl:
image: Updates the colors of various material datum to bring them closer in-line with their actual material stacks
image: Improves the sprites for the material knight armor and helmet.
/:cl:

### CODE REVIEW

**Comment by Likteer** [comment]
Armor is very nice, uranium is ok, but I think gold looks even worse than before. Used to be cheese, now it's pyrite.

**Review by Wallemations — APPROVED** [review]
We must have forgotten to update those color values when we updated the material sprites

**Comment by Wallemations** [comment]
I realize it might be a bit out of scope, but do you think there's any way we could apply a shine overlay onto the gold/silver floors?

**Comment by necromanceranne** [comment]
I'll give it a shot, but it might apply to anything made of the material. Some other material already do this.

**Comment by Wallemations** [comment]
> I'll give it a shot, but it might apply to anything made of the material. Some other material already do this.

That's fine, it might actually help make them look more like they're precious metals compared to the normal mats

**Comment by necromanceranne** [comment]
I'll throw it onto gold, silver, titanium (I know thats already really close to silver but it is a shiny material) and maybe we'll see if it works for diamond? Maybe bluespace too. See how it goes.

**Comment by necromanceranne** [comment]
image

I did that

**Comment by necromanceranne** [comment]
image

Another update to the shine per request

**Review by Wallemations — APPROVED** [review]

**Pull request merged**
