### PR TITLE
Use actions github token for push

### PR DESCRIPTION
**Pull request by optimumtact**
This works for beestation, so I hope it works for us.

### CODE REVIEW

**Comment by actioninja** [comment]
The issue is that master is a protected branch for us and for whatever reason actions don't have perms to push to a protected branch. I don't think this will help.

**Comment by Crossedfall** [comment]
> 
> 
> The issue is that master is a protected branch for us and for whatever reason actions don't have perms to push to a protected branch. I don't think this will help.

This is correct. It's kind of one or the other. If I recall correctly, you still can't add the github actions bot to the list of authorized users that are exempt from that. 

The reason makes sense, here's a quote from github staff on it. 

> If we enabled GitHub Actions to push to a protected branch then any collaborator in your repo could push any code to any branch they wanted simply by creating a branch and coding the workflow to push to to some other branch.

https://github.community/t5/GitHub-Actions/Allowing-github-actions-bot-to-push-to-protected-branch/td-p/34367

**Comment by optimumtact** [comment]
I'm getting rid of branch protection, I knew it was worthless

**Comment by Crossedfall** [comment]
> 
> 
> I'm getting rid of branch protection, I knew it was worthless

If you haven't already, add the code owner protections to the workflow directory. It'll prevent contributors from manipulating things around. If that's a worry of yours, anyways.

**Comment by Neo-0** [comment]
Just make a token with your PAT (assuming you have push access), works on Hippie and they still have a protected branch
https://github.com/HippieStation/HippieStation/blob/e9e3cc6d229f97d8d2e899122530be40a2b5354e/.github/workflows/compile_changelogs.yml#L43

**Pull request merged**
