### PR TITLE
Fix chain pull through space issue (fixes unit test failure)

### LINKED ISSUE #69238: Spurious test failure: Charlie did not teleport to the destination z-level
## Reproduction:

```
Error: Expected 15 to be equal to 5. Charlie did not teleport to the destination z-level. Current location: (129, 126, 15)
FAIL: /datum/unit_test/chain_pull_through_space 0s
	REASON #1: Expected 15 to be equal to 5. Charlie did not teleport to the destination z-level. Current location: (129, 126, 15) at code/modules/unit_tests/chain_pull_through_space.dm:54
```

https://github.com/tgstation/tgstation/runs/7851197680?check_suite_focus=true

Fix was already explained at one point (reserving z levels for unit tests, I believe? using ``add_new_zlevel()``), leaving this here for the tracker.

### PR DESCRIPTION
**Pull request by KirbyDaMaster**
## About The Pull Request
Fixed a plaguing false flag for PR automatic checks. Unit test should no longer fail spontaneously when running the chain pull unit test.

Issue vvv
Fixes #69238
^^^^^^

## Why It's Good For The Game

Makes the checks more reliable for PRs

## Changelog

**qol: made maintainers jobs easier by improving code checking
fix: fixed erroneous code check fails
code: adjusted some parameters in chain_pull_through_space.dm**

### CODE REVIEW

**Comment by KirbyDaMaster** [comment]
**Funny thing i noticed as an asside, how in the hell did my PR fix end up being 69832 to fix 69238???**

**Comment by Mothblocks** [comment]
reserve a z-level instead, i don't like us mutating the world outside of just a test envrionment

**Comment by LemonInTheDark** [comment]
I don't think we actually mutate anything here. The unit test just points the space tile it creates at the empty space z, rather then actually changing anything.

That said, this is potentially risky, because other things can use that z level. It exists to have things spawned in it.
It would be better to use /datum/controller/subsystem/mapping/proc/RequestBlockReservation to request a block of space, with no specified z.
This will hand back a /datum/turf_reservation you can use to pull out GUARENTEED usable coordinates. Then you just qdel the reservation datum later to clear it

**Comment by DaedalusGame** [comment]
> I don't think we actually mutate anything here. The unit test just points the space tile it creates at the empty space z, rather then actually changing anything.
> 
> That said, this is potentially risky, because other things can use that z level. It exists to have things spawned in it. It would be better to use /datum/controller/subsystem/mapping/proc/RequestBlockReservation to request a block of space, with no specified z. This will hand back a /datum/turf_reservation you can use to pull out GUARENTEED usable coordinates. Then you just qdel the reservation datum later to clear it

this seems fine to me because the test gets rid of its components afterwards, the test functions as it always did it just points to an honest to god should be empty z level instead of lavaland

**Comment by Mothblocks** [comment]
ok just reserve a tile then

**Pull request merged**
