### PR TITLE
THE GOOSE IS LOOSE

### PR DESCRIPTION
**Pull request by WJohn**
image

## Changelog
:cl: WJohnston, Antur, and Arcane
add: THE GOOSE IS LOOSE
/:cl:

### CODE REVIEW

**Comment by Ziiro** [comment]
https://www.youtube.com/watch?v=q81ptFSA4mk

**Comment by VileBeggar** [comment]
that is a goose alright

**Comment by Borisvanmemes** [comment]
I'm going to launch geese at the station in supply pods for a event and i will laugh as i do it.

**Comment by Ziiro** [comment]
Can we get a Canadian subtype

**Comment by dr-bee** [comment]
Needs to be hostile. Little shits know no fear.

**Comment by knacker48** [comment]
Can the goose break peoples arms and legs? That's the real question

**Comment by fluffe9911** [comment]
We need a Canadian goose as well honk

**Comment by Shadowflame909** [comment]
Can the Goose fly when gravity turns off?

**Comment by Therapist1** [comment]
Can we have a small chance for a goose to be in the xenobio containment pen roundstart instead of a xeno?

**Comment by IndieanaJones** [comment]
> 
> 
> Can we have a small chance for a goose to be in the xenobio containment pen roundstart instead of a xeno?

Give the goose good structure damage in that case, so it requires them to keep the electric barrier up to contain it.  Failure to do so will result in their termination.

**Comment by Fikou** [comment]
i have literally never seen a better pr
image

**Pull request merged**
