### PR TITLE
Adds new atom and new datum options to viewvars

### PR DESCRIPTION
**Pull request by Thunder12345**
WARNING: Some forms of this may not work as expected, using new atom on an existing list element is confirmed not to work, but then, the rest of VV is no less reliable, use with caution.

Allows for creating new atoms directly into a list/var, for things like spawning directly into an atom's contents. Not sure how many uses there are for creating datums, but the option exists if wanted.

### CODE REVIEW

**Comment by ChangelingRain** [comment]
You could use this to replace a blob overmind's chemical, probably.

**Comment by Thunder12345** [comment]
There's that. I tried adding hoods and changing the uplink's things, but couldn't make either work.

**Comment by MrStonedOne** [comment]
you could already do this to some degree with atoms using game panel -> create object. just mark the object you want to spawn it inside of, and then change the spawn drop down that says "on current mob" To "Inside marked object"

**Comment by RemieRichards** [comment]
@MrStonedOne life is only so short.

**Pull request merged**
