### PR TITLE
Cleans up CENTCOM morgue/chapel/library doors

### LINKED ISSUE #37150: [Meta] Morgue doors are too high security for no reason
The morgue doors in meta's medbay are Centcomm doors, have a gigantic health pool for no reason, they aren't even guarding anything that interesting (corpses?), it doesn't make any real sense.

### PR DESCRIPTION
**Pull request by ShizCalev**
Fixes #37150

### CODE REVIEW

**Review by Cyberboss — DISMISSED** [review]
Personally I'd rename /centcom/ to something else and then add /centcom for the centcom versions. But this is fine

**Comment by iskyp** [comment]
change the airlock type to /obj/machinery/door/airlock/reinforced or something

**Comment by ShizCalev** [comment]
switched it back to your way @Cyberboss

**Comment by uraniummeltdown** [comment]
@ShizCalev add the new airlocks to the RCD and metal recipes list please

**Review by Cyberboss — APPROVED** [review]

**Pull request merged**
