### PR TITLE
[DNM]Removes war ops.

### PR DESCRIPTION
**Pull request by KathyRyals**
## About The Pull Request

Removes war ops and (I THINK) all mention of it from code.

## Why It's Good For The Game

image

## Changelog
:cl: Rohesie & Kathy Ryals
del: Removed war ops.
/:cl:

### CODE REVIEW

**Comment by Misha600** [comment]
WHY THE FUCK
1

**Comment by KathyRyals** [comment]
Rohesie baited me, need to contact headmins.

**Comment by trexter555** [comment]
war ops is 1000% more fun on both sides than blitz ops that rush the captain and drag him into maint 5 minutes into the round and end it.

**Comment by zxaber** [comment]
Remove Nuke Ops.

Stealth and Blitz aren't really fun either. War just lets everyone play rather than restricting the game mode to the antags and Sec.

**Comment by Fikou** [comment]
> Rohesie baited me, need to contact headmins.

thats not what they meant

**Comment by trexter555** [comment]
do a player vote for removing nukeops coward

**Comment by uomo91** [comment]
The only problem with this PR is that it only removes war ops, and not nuke ops completely.

**Comment by Rohesie** [comment]
I'd gladly remove war ops but this is a config so the headmins are involved.
Some people should be poked before even considering this.

**Comment by ExcessiveUseOfCobblestone** [comment]
reopen and merge

**Comment by Jared-Fogle** [comment]
Remove all of ops, actually. Stealth ops isn't fun for anyone other than the ops, whoever the disk holder is, and maybe security. Blitz ops has a lot of the same problems as war ops except now the crew just isn't prepared and the nukies don't get to have a ton of fun crap.

**Comment by Jared-Fogle** [comment]
also wizard next

**Comment by Tharcoonvagh** [comment]
Oh shit things went from 0 to a hundred real quick

**Comment by LemonInTheDark** [comment]
config was a mistake

**Comment by Fikou** [comment]
😬

**Comment by wesoda25** [comment]
Please stop getting my hopes up I can't take much more of this

**Comment by Pugie** [comment]
moments like this I wish actionninja didn't close his pr that would have been dope.

**Pull request closed without merging**
