### PR TITLE
Turn Nettles into reagent_containers

### LINKED ISSUE #39682: (Death) Nettles contain (fluoro)sulph. regardless of removing production gene
[Round ID]: Not entirely sure, but I think 92409, give or take 2. I play exclusively on Sybil.

[Testmerges]: Branch in use at Sybil at the time of writing

[Reproduction]:
- Grow death nettle
- Remove fluorosulphuric acid and sulphuric acid production
- Replace with anything (I believe I used morphine, coniine and cyanide)
- Plant the experimental death nettle 
- Harvest
- Grind the death nettle
- See the beaker contain fluorosulphuric acid and sulphuric acid

I'm not sure if this happens with regular nettles as well.

### PR DESCRIPTION
**Pull request by intrnlerr**
:cl:
refactor: Refactored nettles to be reagent_containers
/:cl:

Turns nettles into reagent_containers
Fixes #39682

### CODE REVIEW

**Comment by Ziiro** [comment]
So can you just straight up pour reagents into them them to make them apply on attack? Maybe just put them into chem dispensers to put stuff inside of them? 🤔

CFL3 Deathnettle?

**Comment by intrnlerr** [comment]
they're the grown/food/snacks thing that a lot of other plants have

**Comment by octareenroon91** [comment]
You have to give them other-chem genes or use a needle.

Can you confirm that using nettles on someone still strikes instead of feeding?

**Comment by intrnlerr** [comment]
if you hit them while in harm intent then they still get strung, but you can also eat them on help

**Comment by ExcessiveUseOfCobblestone** [comment]
Figured as much.

**Comment by Kagus** [comment]
At last! Now I can finally slap people with a healystick!

**Comment by ExcessiveUseOfCobblestone** [comment]
It still does 15 brute

**Comment by Kagus** [comment]
What good is a healystick if they're not injured? This just provides the whole package.

But yeah, it probably doesn't transfer... Last I checked, hypodermic prickles only activated on throw, not on slap, and a cursory glance doesn't reveal any special snettleflake code for transfer of reagents. Man can dream though, eh?

**Comment by Ziiro** [comment]
someone make lifenettles

**Pull request merged**
