### PR TITLE
Metalgen imprinted things don't recycle for anything

### PR DESCRIPTION
**Pull request by spessbro**
## About The Pull Request
This keeps metalgen's material altering abilities but removes the material amount from it making them recycle for nothing.

## Why It's Good For The Game
no more fucking up the economy ^-^

## Changelog
:cl:
fix: metalgen imprinted things don't recycle for anything
/:cl:

### CODE REVIEW

**Comment by Jared-Fogle** [comment]
Can you make the PR title more clear on what you're actually doing? "fixed metalgen" is very broad.

**Comment by spessbro** [comment]
done

**Review by Mothblocks — DISMISSED** [review]

**Comment by Time-Green** [comment]
This just makes an extremely rare chem completely cosmetic. It can’t even change the economy since material selling was removed

**Comment by Jared-Fogle** [comment]
yes it can, search metalgen in #coding-general.

**Pull request closed without merging**
