### PR TITLE
Revert "Removes title4.ogg"

### PR DESCRIPTION
**Pull request by Niknakflak**
Reverts tgstation/tgstation#28882

### CODE REVIEW

**Comment by SgtxRootbeer** [comment]
Can you not?
We've had multiple people explain that title 4 was a poor choice, and a GitHub vote that was a resounding failure

**Comment by TrustyGun** [comment]
if this didn't succeed the past three times, why would it succeed now

**Comment by PraiseRatvar** [comment]
https://tgstation13.org/phpBB/viewforum.php?f=9

you see this, go do stuff on there instead of wasting your time with reverting title4

**Comment by Iamgoofball** [comment]
he finally became what he despised

me

**Comment by lzimann** [comment]
This is the third(?) time that you opened this. Please stop after a pr has already been denied.

**Comment by Niknakflak** [comment]
I like annoying leoz

**Pull request closed without merging**
