### PR TITLE
remove y##f in h##l spray, adds furry pride spray

### PR DESCRIPTION
**Pull request by chesse20**
## About The Pull Request
Replaces one of the rude/vulgar spraypaint/crayon large arts to something more appropriate 

Discord_2UD9Pzy57q

## Why It's Good For The Game
Hatred of furries is often rooted in/ vieled homophobia (i would reccomend the reads https://soatok.medium.com/if-you-hate-furries-youre-anti-lgbt-cce35a948a57 and https://archive.ph/fX8Jo The statement "y## in h##l" wasn't okay in the past, and its not okay now. That is why I have replaced this old goonstation era art (which as far as i know, no longer exists in modern gooncode) with a more positive message of furry pride. 

## Changelog

:cl:

add: Furry Pride Spraypaint added to spray cans
del: Y##f In H##l Sprapaint removed from spray cans
/:cl:

### CODE REVIEW

**Comment by Iamgoofball** [comment]
:+1: :shipit:

**Comment by optimumtact** [comment]
I lied

**Comment by castawaynont** [comment]
YEAHHHHHHH

**Comment by chesse20** [comment]
aewsome sauce

**Comment by axietheaxolotl** [comment]
image

**Comment by dendyd00m** [comment]
we did it

**Comment by RegJackson** [comment]
pissing off r/ss13 is always based.

**Comment by RedBaronFlyer** [comment]
Furries4
Furries2
Furries3


Could we at least have both sprays? This isn't going to stop anyone from writing "Fuck furries" or whatever with the spraycan.

**Comment by Jan-Blasiak** [comment]
nice, will be easier to identify and bully furries

**Comment by carlopault** [comment]
no wonder tg died hahahaha

**Comment by Mothblocks** [comment]
> no wonder tg died hahahaha

image

**Pull request merged**
