### PR TITLE
Prettifies adminmoreinfo into a neater Examine Block

### PR DESCRIPTION
**Pull request by san7890**
## About The Pull Request

Hey there,

I might be the only one who uses the (?) button, but man it doesn't look good:

image

So, let's dust it off a bit and wrap it in an examine block, while also including some better formatting, cleaner syntax, and getting rid of confusing single-letter variables on the back-end. A splash of color is nice too!
## Why It's Good For The Game

image

Much nicer looking, and now you don't have that weird blank `Antagonist: ` thing that plagued me when I was starting adminning.
## Changelog
:cl:
admin: "adminmoreinfo", or the read-out of a mob that you can get when you hit the (?) button next to the name of a given mob has been cleaned up a bit to make the data-at-a-glance much more presentable.
/:cl:

### CODE REVIEW

**Comment by MrStonedOne** [comment]
I don't like making it take up even more of the scrollback by giving each damage type a newline.

putting the whole `damage:` line on its own line would be cool, but try not to wreck the information density by putting each item on its own line. it looks nicer until you try it on a 768 monitor and you have to choose between seeing the whole mob info or having a scroll bar on the verb panel

**Comment by Kapu1178** [comment]
colorize the damage types
brute = red
burn = orange
tox = green
suffocation = light blue
stamina = baige

**Comment by san7890** [comment]
> colorize the damage types brute = red burn = orange tox = green suffocation = light blue stamina = baige

i wanted to do this but we don't have the spans and i didn't feel like updating those for this PR

**Comment by san7890** [comment]
> I don't like making it take up even more of the scrollback by giving each damage type a newline.

image

I tightened up a bit, this look better?

**Comment by MrStonedOne** [comment]
:+1:

**Pull request merged**
