### PR TITLE
holographic esword doesnt have blockchance

### PR DESCRIPTION
**Pull request by manofpepsi**
## About The Pull Request

fixes the holosword having inherited block chance from its parent after the transforming weapons refactor.

## Why It's Good For The Game

no more rng

## Changelog

:cl: Pepsiman0
fix: holosword doesnt have blockchance 
/:cl:

### CODE REVIEW

**Comment by Mothblocks** [comment]
this isnt a fix

**Comment by manofpepsi** [comment]
> this isnt a fix
the holosword didnt have a blockchance before the transforming weapons refactor

**Comment by Mothblocks** [comment]
then put it in the description

**Comment by Mothblocks** [comment]
thanks

**Review by Mothblocks — APPROVED** [review]

**Pull request merged**
