### PR TITLE
Hopefully fixes shuttle baseturfs but in a really crude way because I have no fucking idea what's actually wrong with them

### PR DESCRIPTION
**Pull request by Buggy123**
Its terrible but it works kindaishprobably.

### CODE REVIEW

**Comment by vuonojenmustaturska** [comment]
Have you thought about asking? A lot of people on #coderbus could tell you exactly what the problem is

**Comment by Buggy123** [comment]
If the problem is both

A: easy for me to understand
B: possible for me to fix

then there is no reasonable explanation for why it remains unfixed.

**Comment by Poojawa** [comment]
You should test this, just to prove a point

**Comment by Buggy123** [comment]
Fair enough

**Comment by Spaceinaba** [comment]
we should just start autoclosing untested prs

**Comment by Poojawa** [comment]
Kevinz would never get anything merged then.

**Comment by ExcessiveUseOfCobblestone** [comment]
Not being able to test does not give you immunity to not testing. You can edit branches without making PRs using webbitor then compile/test when you're on a usable computer.

**Comment by Buggy123** [comment]
I plan to test, I just have a legitimate excuse for not doing it immediately when I code.

**Comment by Buggy123** [comment]
IT DUN WORK

**Comment by Buggy123** [comment]
FUCK THIS I'LL JUST REVERT THE PR THAT CAUSED THIS IN THE FIRST PLACE

**Comment by optimumtact** [comment]
it's like watching a child try to eat food but they dont' know how to use their hands so they just sort of smush their face about in the food

**Comment by Buggy123** [comment]
:(

**Pull request closed without merging**
