### PR TITLE
Refactor plasmaman stomach typepath

### PR DESCRIPTION
**Pull request by coiax**
:cl: coiax
refactor: Skeleton and plasmaman stomachs now share the same code.
fix: Skeletons now heal brute and burn damage from drinking milk, plasmamen
only heal brute damage.
/:cl:

The plasmaman stomach functions identically as a skeleton/bone stomach,
apart from being better at digesting food. Their reaction to milk (and
excess milk) is the same, so they should share a type path.

### CODE REVIEW

**Comment by ATH1909** [comment]
the thing is, it's not SUPPOSED to be the same reaction

skeletons and bone golems are supposed to use milk to heal both brute AND burn damage, while plasmamen are supposed to only be able to heal brute damage with it. unfortunately, because nightred just copy+pasted the code for plasmaman milk reactions, it's now a real bitch to heal your burn damage as a skeleton, because regenerative mesh, milk, and most healing chems won't work on you (to heal your burn damage, anyway) as a skeleton.

**Comment by LemonInTheDark** [comment]
> 
> 
> the thing is, it's not SUPPOSED to be the same reaction
> 
> skeletons and bone golems are supposed to use milk to heal both brute AND burn damage, while plasmamen are supposed to only be able to heal brute damage with it. unfortunately, because nightred just copy+pasted the code for plasmaman milk reactions, it's now a real bitch to heal your burn damage as a skeleton, because regenerative mesh, milk, and most healing chems won't work on you (to heal your burn damage, anyway) as a skeleton.

Will you fix this issue?

**Comment by coiax** [comment]
> Will you fix this issue?

Fixed.

**Comment by LemonInTheDark** [comment]
I meant ath, but that's kind of you

**Pull request merged**
