### PR TITLE
Make chem dispenser reagent search better

### PR DESCRIPTION
**Pull request by Gorock**
## About The Pull Request
Improving the chem dispenser reagent search by using a List.

This is my first Pull Request for tgstation. I would like to know how to add Test for this change.
I would like to Test. if the list is complete and if all entrys are valid

Screenshots:

Before:
image

After:

image
## Why It's Good For The Game
Make the Input more fun to Use by letting the player search in a reagent list. Helps  for typing complicated chemical names.
## Changelog
:cl:
qol: Improved Chem Dispenser Reagent Search
/:cl:

### CODE REVIEW

**Comment by Teleported-Bread** [comment]
I hate to say that this isn't fulpstation  XD
image
Looks like a really useful PR though, and TG could definitely benefit from it

**Comment by Gorock** [comment]
I corrected the Description 

 I made a pull request on fulpstation first but got the answer that i should make it here 

Respone from Fulpstation Repo
> This is good but PRs should be made upstream (aka on tg) when possible.

hope this is correct this time

**Comment by JohnFulpWillard** [comment]
Thank you for taking the time to port this here and thank you for the contribution

**Comment by JohnFulpWillard** [comment]
>  I would like to Test. if the list is complete and if all entrys are valid

We have a unit test that ensures all chemicals have unique names, and ``GLOB.chemical_name_list`` is populated with all chemicals, it is fine and accounted for.

**Pull request merged**
