### PR TITLE
Removes xenomaid

### PR DESCRIPTION
**Pull request by lzimann**
Bad meme, bad content, it's time to axe these kind of things.

### CODE REVIEW

**Comment by evsey9** [comment]
its time to axe you

**Comment by KorPhaeron** [comment]
/tg/ culture

**Comment by lzimann** [comment]
""""""""""""""culture""""""""""""""

**Comment by kevinz000** [comment]
i remember watching a greytider get married to a lusty xeno maid
never remove.

**Comment by optimumtact** [comment]
just so I can close it too

**Pull request closed without merging**
