### PR TITLE
Removes the "Cook" spawning uniform for code maintainability reasons.

### PR DESCRIPTION
**Pull request by optimumtact**
If you want a head chef, make a head chef job role, just like there is a quartermaster.

We have code standards for a reason people.

### CODE REVIEW

**Comment by MrStonedOne** [comment]
:-1:

don't hide a bug by removing the code that tirggers the bug. fix the bug,

**Comment by optimumtact** [comment]
The bug is orthogonal, this is just shit code and has no redeeming value

**Comment by MrStonedOne** [comment]
Sure it does. or it wouldn't have gotten merged.

**Comment by Fox-McCloud** [comment]
Just port Bay's alt title system...it completely avoids the problem and ensures that alt title jobs still use the parent's icon---not to mention it allows for some interesting/fun titles and some minor aesthetic modification to equipment based on titles (ie: coroner doctor starts with black scrubs, etc).

**Comment by MrStonedOne** [comment]
This isn't even fucking snowflake code, it has to be mucking up some bigger unrelated piece of code to qualify for the title of snowflake code

**Comment by optimumtact** [comment]
>exists for one purpose
>not generalised
>only works for one job role
>reaches into the internals of another system
>Makes assumptions about how the job subsystem works
>QED mate

**Comment by Cheridan** [comment]
Isn't this the exact same way the 2 lawyers have different outfits? The code here isn't great but yeah this seems like more of a rugsweep by taking the feature out entirely than a real fix.

**Comment by optimumtact** [comment]
:cry:

**Pull request closed without merging**
