### PR TITLE
Fixes TramStation's Ordnance APC Cable Connectivity (GASLIGHTING EDITION)

### LINKED ISSUE #65345: TramStation Ordnance APC is not cabled
## Round ID:
N/A

## Testmerges:
N/A

## Reproduction:
Screenshot_1

### PR DESCRIPTION
**Pull request by san7890**
## About The Pull Request

My bad, I blame #64933 for this one (ALTHOUGH GIVEN NEW INFORMATION I CAN NOT BE 100% CERTAIN).

Fixes #65345.

Addendum: It appears that somehow the changes I made with the areas to the Ordnance area... are missing? I swore I touched this area to apply the changes in the above PR. I've re-applied the intended area pathing (I believe I meant to redefine the Launch Area and fix that weird ownership of space Ordnance Mixing had in the above PR, so I just remapped those). How odd.

Addendum 2: Ok, this is seriously weird. I did do that above change back in #65138. Also, look at this!

image

The changes I made back in #65015 are completely gone? What????? Huh????? What the fuck happened? The area turfing I introduced in there still exists. I remapped those again and passed this through in the PR.

## Why It's Good For The Game

image

It's important to have this spot be powered, I think.

## Changelog

:cl:
add: A mix-up in blueprints meant that TramStation didn't have a formally defined Ordnance Launch Area. This has now been rectified.
fix: TramStation's Ordnance Mixing no longer owns that bit of space that the waste gas is meant to exit the burn chamber from.
fix: TramStation's Ordnance Launch Area's APC now has connectivity to the grid.
/:cl:

### CODE REVIEW

**Comment by san7890** [comment]
(MMM explained to me why this was, and it does make sense now. I'm leaving behind the insane mutterings since they do a decent job of explaining the wider purpose of this PR.)

**Comment by AlinaStarkova** [comment]
@san7890 
"Duplicate APC created at Ordnance Mixing Lab (191,101,2)"

image

**Comment by san7890** [comment]
> @san7890 
> 
> "Duplicate APC created at Ordnance Mixing Lab (191,101,2)"
> 
> 
> 
> image
> 

Did you debug on this branch? One of the points of this PR (that I didn't visually represent, sorry) is remaking the changes that I did in another PR that makes that room (Ordnance Launch Area) it's own area since my mapping changes on that PR were deleted. It should already be fixed.

> also while your at it, these two cycle helpers have been screaming for quite a long time now, they dont connect to anything and should be removed
> 
> image

I could take a look at it or I could leave it for another day. I'll see when I'm back home later today.

**Comment by san7890** [comment]
FUCK wait a second i accidentally

**Comment by san7890** [comment]
this whole branch is fuck

**Pull request closed without merging**
