### PR TITLE
Makes Zombies 2 spooky

### PR DESCRIPTION
**Pull request by Robustin**
Stun capped at 2 ticks (4s), zombifying no longer drops your mask/helmet, and zombies now heal 4 brute/4 burn per tick. 

Romerol purchases were down to 6 last month(of which I was probably 4 of them), I called it months ago. Fully stunnable zombies that move slowly are never going to be a serious threat unless everyone already died from other causes.

Edit: Yes zombies were so pathetic people would run to medbay and ask for surgery. Headmins have ruled that to be INVALID so please report your local shitty zombie to the nearest authorities.

:cl: Robustin
balance: Zombies now have a 4s cap on stun durations 
balance: Zombies now regenerate 4 brute/4 burn every 2 seconds.
balance: Zombies will no longer drop their mask/helmet upon turning, making them harder to identify
balance: Zombies will randomly moan/groan/wail which can be heard from far away, greatly enhancing their spookiness but preventing them from being too sneaky. 
:cl:

### CODE REVIEW

**Comment by kevinz000** [comment]
lets keep buffing a meme item that shouldn't exist

**Comment by VeryRealAccount** [comment]
By that logic we should just remove Xenos then, Kevinz.  The variety makes the game more fun, but they do need to be threatening.

**Comment by Grazyn** [comment]
I just wish that zombies couldn't talk because the few times that I've seen romerol being used, half the zombies rushed to medbay and asked for surgery.

**Comment by Kromgar** [comment]
Lets give zombies their own language

**Comment by kevinz000** [comment]
@VeryRealAccount who are you again? 
@Grazyn didn't we have policy discussion against that?
@Kromgar lol

**Comment by Kromgar** [comment]
@kevinz000 Why not? Prevents zombies from asking medbay to remove their zombie organ

**Comment by ShadowDeath6** [comment]
Not sure how race changing works but wouldn't it be a better idea to tie healing to the organ itself?

**Comment by XDTM** [comment]
people have the organ when they get infected even before dying, it would lead to extreme powergame

**Comment by WJohn** [comment]
jesus christ that's some mad healing.

**Comment by Robustin** [comment]
Its the same as what Viro can dole out to ordinary crew. Its there to resolve the issue of "lol im at 20hp and slower than a fucking juggernaut im just going to crit myself so I can revive at full health".

**Comment by ShadowDeath6** [comment]
It could just have an iszombie() check in the organ, I think it'd be more consistent with stuff like legion souls

**Comment by DoctoreMad** [comment]
>heal 5 brute/5 burn per tick.

Holy shit lower it to 2 brute/burn and it'll be better

**Comment by Anonmare** [comment]
Zombies shouldn't be able to speak or understand galcommon tbh. Heck, they shouldn't be communicative at all

**Comment by Cyberboss** [comment]
This isn't per tick. It's every 2 seconds.

**Comment by Repukan** [comment]
Why would zombies be affected by stuns?

Their nerves are fucking dead. Watch any zombie movie and a taser would never work.

**Comment by Repukan** [comment]
Or I guess they work enough for movement but wouldn't be affected due to decaying flesh not being conductive enough and shit.

**Comment by RemieRichards** [comment]
@Robustin the mask/helmet thing was deliberate so you can tell zombies apart.
Please don't revert that.

**Comment by XDTM** [comment]
>Its the same as what Viro can dole out to ordinary crew

No, viro does 1 per tick. 3 with uranium lategame symptoms, if people bother to cure the first virus, and get the second one.

>This isn't per tick. It's every 2 seconds.

Also known as life tick.

**Comment by kevinz000** [comment]
itt robustin gets rekt by xdtm

**Comment by Robustin** [comment]
I thought a tick was roughly 2 seconds?

**Comment by XDTM** [comment]
1 + 2 = 3, @Robustin, i coded the damn symptoms

**Comment by Robustin** [comment]
Fine I'll bring it to 4 since I respect you brining facts.

**Comment by RemieRichards** [comment]
@Robustin it was done for balance robustin, I dont think removing it is a good idea.
UNLESS, you add something like, forced groans every rand(20, 50) so that you can still tell.

either way, the above should be priority one if another zombie balance PR is needed.

**Comment by XDTM** [comment]
I didn't actually have an issue with the healing, i just don't like viro being overestimated.

Also i love the random moaning idea, it works for its purpose and it's more immersive than helmets not fitting.

**Comment by Shapsy** [comment]
"Zombies being added to the uplink is fine because they won't be super strong and they'll happen very rarely"

"Hey zombies are too weak, no one buys them and they happen very rarely, we need to buff them to make them more viable!"

playing the long game

**Comment by lzimann** [comment]
Healing every tick is stupid, we already have viro using this and it's far from ideal.

**Comment by Robustin** [comment]
Its hard to imagine other solutions that doesnt encourage zombies to kill themselves in order to heal

**Comment by lzimann** [comment]
Healing on eating people.

**Comment by Robustin** [comment]
I thought about that but it doesnt solve the issue of "Im at 20hp, im slow as fuck, theres no way im going to find a body before someone finishes me off I better just hit myself in this dark corner of maint and wake up at full HP in 60 seconds or so".

**Comment by Robustin** [comment]
I made zombies noisier and that noise can be heard from a significant distance so that should abate some of the concerns about sneeky breeky zombies.

**Comment by fludd12** [comment]
How about, instead of healing, zombies are simply completely immune to any damage slowdown and crit- They'll keep on going until they die, and then get back up again.

**Comment by Robustin** [comment]
The damage slowdown immunity is one thing (I felt it was unnecessarily with regeneration existing), but I have no idea what you mean by immune to crit.

**Comment by fludd12** [comment]
Instead of regenerating, they are immune to damage slowdown, and instead of going into crit at 100 (0 from an in-game perspective) health, they simply keep on going until they hit 0.

**Comment by ShadowDeath6** [comment]
They already die when they enter crit.

**Comment by AnturK** [comment]
@KorPhaeron decision on this please.

**Comment by optimumtact** [comment]
Make decisions yourself @AnturK

**Comment by Robustin** [comment]
@AnturK 

Kor supported removing damage slowdown on Zombies and generally felt they weren't threatening enough. I think he would support this PR over the status quo.

**Comment by KorPhaeron** [comment]
Can't hurt to try it, will just revert it if it sucks freeze or not

**Comment by Cheridan** [comment]
you heard the man

**Pull request merged**
