### PR TITLE
Fixing zero damage items with set attack verbs not showing chat messages anyway.

### LINKED ISSUE #55219: Items that deal zero damage don't get an attack verb shown in chat.
## Round ID:
/////

## Testmerges:
/////

## Reproduction:

Get a bee plushie and smack your nearest moth with it.
See nothing appear in chat!
Give the bee plushie one (1) force.
See you begin to sting the helpless moth in chat!

I believe this is unintentional as why else would these plushies (and other items that deal 0 damage) have custom attack verbs, if not to be shown in chat?
I want to sting my moths god damn you!
image
That's it with 1 force. Without any force, it doesn't appear in chat.

### PR DESCRIPTION
**Pull request by Ghommie**
## About The Pull Request
Borked exactly five months ago by #52890.

## Why It's Good For The Game
This will close #55219.

## Changelog
:cl:
fix: Fixed zero damage items with set attack verbs not showing chat messages anyway.
/:cl:

### CODE REVIEW

**Comment by LemonInTheDark** [comment]
Tested?

**Comment by Ghommie** [comment]
Ok, now I tested it. Please make sure all labels but fix are removed, I did a fucky wucky with git.

**Comment by optimumtact** [comment]
```

Checking for space indentation
code/_onclick/click.dm:  * Middle click
code/_onclick/click.dm:  * Mainly used for swapping hands
code/_onclick/click.dm:  */
space indentation detected
```
fix your comment format

**Comment by Jared-Fogle** [comment]
@optimumtact That was from a botched master--OP needs to merge from latest.

**Review by SpaceManiac — APPROVED** [review]

**Pull request merged**
