### PR TITLE
Fixes AIs being unable to interact with unscrewed airlocks

### PR DESCRIPTION
**Pull request by YPOQ**
:cl:
fix: AIs and cyborgs can interact with unscrewed airlocks and APCs.
/:cl:

### CODE REVIEW

**Comment by YPOQ** [comment]
Tempted to do this with APCs too so people can't instantly disable AI control with just a screwdriver.

**Comment by ShizCalev** [comment]
do it.

**Review by ShizCalev — CHANGES_REQUESTED** [review]
https://youtu.be/FQRW0RM4V0k

**Review by ShizCalev — APPROVED** [review]

**Comment by Dorsisdwarf** [comment]
Do it with APCs, there's an AI control wire for a reason

**Pull request merged**
