### PR TITLE
Re-organizes survival box code to be less horrendously ugly.

### PR DESCRIPTION
**Pull request by Firecage**
This PR re-organizes the code for survival boxes a bit so they aren't all separate objects unrelated to each other with copy-pasta for their PopulateContents(), but instead with the basic survival box being the parent and the rest being its children. It is a bit cleaner and easier to modify for future survival box changes now. The exception would be the clown's survival box, which is a special snowflake as clown are, and is still box/hug for its special interaction features. If you want, I can just make it a normal survival box with the hugbox sprite.

Everything still appears to work as intended.
## About The Pull Request

For the first bit. Simply because the code for survival boxes is now less ugly to look at, and slightly easier to work with.

### CODE REVIEW

**Comment by Dawson1917** [comment]
If your mask gets destroyed you're supposed to _interact_ with cargo and order a replacement. You're meant to be inconvenienced by your mask being burnt off or stolen, not just reach into your backpack and pull out a replacement.

**Comment by HomocidlePancakes** [comment]
@Dawson1917 It’s just a mask bro, who cares?

**Comment by Firecage** [comment]
@Dawson1917 If we could get cargo to do their job most of the time, sure. It tends to be a struggle to convince them to even order useful job-related crates(medical, hydro, etc.), and most of the time you would get laughed at for asking for any costume crate. It is the same age old issue of cargo loving their own personal toys and opening said crates via emitters.

**Comment by Dawson1917** [comment]
Maybe there'd be a change of attitude for cargo players to do their job if there was anything for cargo to do besides "buy guns it's nukies", "buy mindshields it's revs", "buy guns and mindshields it's cult", and "please buy me a viro crate".
Giving them less reasons to do their job and hugboxing mimes/clowns doesn't make things better.

**Comment by Firecage** [comment]
True, that is a good point you make.

**Comment by Firecage** [comment]
@Dawson1917 True, that's a good point.

**Comment by Learner10** [comment]
@Dawson1917 There is literally no point in interacting with Cargo just to get a new mask, when every air supply cabinet and fire locker contains a gas mask. When all is said and done, a well-populated station probably carries enough gas masks both in storage and on person to equip every person two-fold.

**Comment by HomocidlePancakes** [comment]
>hugboxing
>pretty mask to play dress-up with
While analyzing your thought process on this topic, I have came to a profound realization that this is fucking stupid.

**Comment by actioninja** [comment]
you're delusional if you don't think the clown mask carries a specific weight and value to it.

**Pull request merged**
