### PR TITLE
Fridge UI adjustments [NO GBP]

### PR DESCRIPTION
**Pull request by MTandi**
## About The Pull Request

Made a few adjustments to the Smart Fridge UI per feedback. See CL for the list of changes.

eZXChptv1X

image

## Why It's Good For The Game

Better UX

## Changelog

:cl:
qol: smart fridge UI now groups items by type+name instead of just type
qol: smart fridge UI now shows item names next to the images
qol: smart fridge UI has a list view option (default for chem and viro versions)
fix: fixed smart fridge stacking sounds when dispensing multiple items
/:cl:

### CODE REVIEW

**Comment by lessthnthree** [comment]
Is there something up why the reagent bottles/tubes don't show the color of the liquid?

**Comment by MTandi** [comment]
> Is there something up why the reagent bottles/tubes don't show the color of the liquid?

DMIcon only retrieves the atom icon+icon_state. Thus, overlays are not displayed. Not sure if there is a way to show the full icon with DMIcon as of now.

**Comment by Gaxeer** [comment]
> > Is there something up why the reagent bottles/tubes don't show the color of the liquid?
> 
> DMIcon only retrieves the atom icon+icon_state. Thus, overlays are not displayed. Not sure if there is a way to show the full icon with DMIcon as of now.

Right now it's only possible using 'getFlatIcon', or new 'RenderIcon' proc, which is useless because we have 'emissive_blockers' so all items will be just black

**Comment by SyncIt21** [comment]
Don't like how the text of these items are getting clipped. Makes it difficult to recognize reagent bottles since they don't have a visual indicator.

Maybe display them vertically?

**Comment by lessthnthree** [comment]
Yeah that doesn't look great. What if it listed them vertically and had their icon at the left?

**Comment by MTandi** [comment]
Text is secondary and having bigger icons is better for UX than giving more emphasis to the text, since most can chose the needed items by glance at the icon, like they already do when they open backpacks.

This interface has faster user response time than our current/previous vending UI. 
Player sees an icon, and clicks on it VS Player sees a small icon, reads the text if the icon is too small, then locates the amount input, then the vend button and clicks on it.

And you select items by looking at the big glass window of the smart fridge, the big icons resemble this feel.

The text with ellipsis is just for the cases when there are items of the same icon (tubes for example). And most of the time, the first word is enough to pick the item without opening a tooltip, since our reagent containers mention the reagent at the beginning.

I also have adjusted the seed display in #85370 for this.

**Comment by Lutowski** [comment]
Looking much better now! Shame about the reagent colours not showing though, shouldn't be too disruptive since most chems are output in pills or patches.

**Comment by trefoils** [comment]
Still feel over all this is just a downgrade for medical. This is amazing for service where its like oh that's a pumpkin grab it. For medical? You still have to read it you are still just using the text and now with a bloated mostly useless icon taking up more space. Making it take longer to read. I'd love there to be an option to just toggle text only.  As it stands this isn't useful for medical and it was never intended for medical it feels. At least its useable now so I guess that is something.  You say it has faster response time and I can see that for service, I can't see that for medical. I feel this is either slower or about the same. Very mixed on this.  Cause I love this for service its amazing. For medical this is awful and in no way helpful it hinders more then helps.

**Comment by lessthnthree** [comment]
> Text is secondary and having bigger icons is better for UX than giving more emphasis to the text, since most can chose the needed items by glance at the icon, like they already do when they open backpacks.
> 
> This interface has faster user response time than our current/previous vending UI. Player sees an icon, and clicks on it VS Player sees a small icon, reads the text if the icon is too small, then locates the amount input, then the vend button and clicks on it.
> 

Different use cases for different players. I, like the previous comment view it from the medical angle. It's not a good UX for medical and the players are not happy with it whatsoever.

What if the Smartfridge when set to chemicals/virology mode uses the old style text based menu.

A viro fridge filled with bottle icons that doesn't even show contents is not a good UX. The short text means you need to hover to find out what each pill is.

**Comment by MTandi** [comment]
353213007-1d6ba3fa-f370-4a8d-b534-4779d96a0c50

**Comment by Lutowski** [comment]
this-peaks-memes

**Comment by lessthnthree** [comment]
> 353213007-1d6ba3fa-f370-4a8d-b534-4779d96a0c50

There we go, this is good.

**Comment by Lutowski** [comment]
Small issue I've found while playing kitchen/botany - you can't vend bluespace tomatoes once you put them in.

**Comment by MTandi** [comment]
> Small issue I've found while playing kitchen/botany - you can't vend bluespace tomatoes once you put them in.

Uh... 

```
	name = "\improper bluespace tomato"
```

Thanks for reporting

**Pull request merged**
