### PR TITLE
Fixes random VV crashing.

### LINKED ISSUE #10881: Client crash on radio/headset VV
Attempting to use VV on a radio/headset will reliably crash your DS client.

It it only crashes on the obj/item/radio/headset type. Parent types do not cause the crash, neither do child types.
The only conditions known (so far) to prevent the crash, is if the headset is on a wooden floor tile, or has been previously picked up by a human.

What the hell

### PR DESCRIPTION
**Pull request by lordpidey**
Fixes #10881

I have no idea why it works.  But it does work.

what
the
**fuck**

### CODE REVIEW

**Comment by optimumtact** [comment]
can you reproduce the crash when the spawn is removed?

**Comment by lordpidey** [comment]
Yes, I can reliably reproduce the crash on the nullrod SORD as of the parent to this commit, and it no longer happens as of this commit.

This leads me to believe the crash has something to do with network code.

**Comment by MrStonedOne** [comment]
Can confirm. I discovered this as well when i was looking into #10881, I didn't pr it because it seemed hacky, but hey, it works.

**Comment by AnturK** [comment]
Make that comment adress what it fixes please. Also this is weird.

**Comment by optimumtact** [comment]
what the zog

**Comment by RemieRichards** [comment]
Shame, Phil and me had narrowed it down to ```attack_verbs``` being 8 or more elements long (Equally as voodoo but feels more like the true issue to fix)

**Comment by MrStonedOne** [comment]
odds bugs have a tendency to connect.

I'm calling it now, this and cleanbot are related.

**Comment by Robustin** [comment]
Does this fix all VV crashing? Either way, good work.

**Comment by lzimann** [comment]
what the actual fuck...

**Comment by optimumtact** [comment]
Well I mean I guess we can do this for now

**Comment by lordpidey** [comment]
Yeah, I figure even if it's hacky, and we don't understand it, it's a bad idea to have admins crashing and unable to do their job.

**Pull request merged**
