### PR TITLE
Remaps the crashed ship space ruin into something that isn't the second worst ruin we have

### PR DESCRIPTION
**Pull request by Paxilmaniac**
## About The Pull Request
Your honor, my client pleads:
image
(old)

Death:
image
(new)

## Why It's Good For The Game
image
image
image

Well, can't argue with that

## Changelog

:cl:
expansion: the crashed ship space ruin has been remade in a new style, and is no longer using ancient map objects from god knows how long ago
/:cl:

### CODE REVIEW

**Comment by Paxilmaniac** [comment]
Mapping prs haven't been the same ever since the default options for the changelog were changed

**Comment by EOBGames** [comment]
Man I look really hostile when I get going about old bad maps.

From a cursory look this looks nice, I'll do a deep dive sometime tomorrow.

**Comment by Livrah** [comment]
So, Accelerator Laser Cannons are gone?

**Comment by Paxilmaniac** [comment]
Realized there's a few things missing, turrets and some crate loot, etc, but I don't think I'm keeping the turrets as accelerator lasers.

**Comment by Livrah** [comment]
It's only way to get it without admemery and it comes without a firing pin. 
It was fun to see the cannon being used in the round due rarity.

**Comment by newfren** [comment]
Removal of the superpacman for like a million magic power machines hurts, they take up way more room, but it's not a huge issue. Curious about the removal of teleporter and introduction of what looks like a comms relay? Also, is that a drone machine next to it, and does that effect the balance of drones?

Echoing that the removal of the heavy laser turrets is lame

**Comment by NanoCats** [comment]
I liked this ruin

**Comment by CRITAWAKETS** [comment]
what the hell? this isnt the same theme at all and should probably just be called a replacement

also saying the crashed ship is the second worst ruin is _really_ underestimating how many bad space ruins we have. Wanna know how many? The crashed ship is one of the best ruins, despite being crap.

**Comment by Acer202** [comment]
I feel like the ship could have used an interior redesign instead of a total removal/re-design, but I'll admit it did have a peculiar "old" feeling to it. Also put the accelerator lasers in somewhere! They were a really unique part of this ruin, and there was enough of them that you had a decent chance of getting one for nefarious use (if you happened to also find a firing pin.)

**Comment by NanoCats** [comment]
now that other people bring it up I see how this is basically an entirely new ruin lol

**Comment by Ghommie** [comment]
We have deep space ruins that are only rocks, platings and weed, another crashed shuttle full of nothing, a boarded up room that only has a few abandoned crates (not to be confused with the one with .45 gun and critters), some asteroid with a pickaxe inside it, a teleporter ruin with NO beacon (not to be confused with the abandoned teleporter which has a beacon), the lizard gassing station that used to be ok back when it had a security hardsuit in its suit storage slot, a half-assed space library ship with a medibot in it, the not-so-dj station...
The old crashed ship space ruin isn''t even the second worst ruin we have from what I see. Maybe that's your personal opinion, but I have a hunch you're exaggerating it to get more approvals.
Sure, it's average to subpar and may need some refurbishing but it got the "crashed" theme right. The new one has a more generic derelict spaceship collision look. It also had a teleporter and a nice laser gun (If you have a grudge against it, consider sanitizing it by putting a cap on the projectile size and damage), a few RNG strange seeds and probably some dosh so yea, it wasn't as terrible as the maptainer guy tries to portray it.

**Comment by Zytolg** [comment]
Where's the rock?

I DEMAND A ROCK!

**Comment by EOBGames** [comment]
> We have deep space ruins that are only rocks, platings and weed, another crashed shuttle full of nothing, a boarded up room that only has a few abandoned crates (not to be confused with the one with .45 gun and critters), some asteroid with a pickaxe inside it, a teleporter ruin with NO beacon (not to be confused with the abandoned teleporter which has a beacon), the lizard gassing station that used to be ok back when it had a security hardsuit in its suit storage slot, a half-assed space library ship with a medibot in it, the not-so-dj station... The old crashed ship space ruin isn't even the second worst ruin we have from what I see. Maybe that's your or EOBgames' personal opinion, but I have a hunch you're exaggerating it to get more approvals. Sure, it's average to subpar and may need some refurbishing but it got the "crashed" theme right. The new one has a more generic derelict spaceship collision look. It also had a teleporter and a nice laser gun (If you have a grudge against it, consider sanitizing it by putting a cap on the projectile size and damage), a few RNG strange seeds, laser turrets that can lead to !!FUN!! times for newbies and probably some dosh so yea, it wasn't as terrible as the maptainer guy depicts it.

I said that it was one of our absolute worst ruins. I don't care what loot's inside, what I care about is that it looks like a shoebox hit another, rockier shoebox. We have so many of these kinda ruins and I'm not shy about saying that they're all terrible. I'll say that this is also worse than the ruins that are upfront about just being asteroids, or single rooms- this tries and fails to look like something more interesting. That's what makes it so bad- it's got potential that isn't being realised in this package. Please attempt to view it as more than a loot pinata and perhaps you'll see what I mean.

**Comment by Ghommie** [comment]
Say what you want but I'm not merely looking at it from a loot pinata perspective. Half of my previous post was about how the ruin is not worse than a bunch of others overall and not just from a looter's pov, otherwise I'd have included a lot more ruins in that list, but I aknowledge there has to be a quantity of "bad" ruins to make the non-dull ones more interesting and that after all it's derelict space and that it has to have a few rocks and scraps to convey that feeling. I have played hundred of rounds getting a jetpack, space suit and throwing my mob out into deep space to the point you could say it's grown old on me, and I know the enjoyement of it cannot be narrowed down to getting gamer loot every single time, or just a free-roaming rooms and ships exhibition for that matter...
Yes, the ruin sucks hard from a strict aestethic perspective as you said: It has a lot of badly used space. It's boxy. But it's clear to me from your message that you haven't understood that this is an entirely different ruin.

> what I care about is that it looks like a shoebox hit another, rockier shoebox

There's no trace of asteroid rocks in the new ruin. It's completely different. It looks like a spaceship with its stern section (the engine, which has a plastitanium walls instead of plasteel) torn from the rest of it. It can't be a collision between two different ships also because the stern of what would be the front ship is intact. To further confirm my hypothesis the two pieces fit together. I was wrong when I said it looked like "derelict spaceship collision" simply because I hadn't finished scrutinized the outline of the new one back then. It doesn't look like a crashed ship, and the hole in the port section could have been an explosion.

> it's got potential that isn't being realised in this package.

If it has got potential, then that potential should be fulfilled, not junked in favor of a new map that doesn't look in any way like the old one. I would say more but I don't want to sound ponderous about it. I hope it's clear enough that if this has to be merged, it should be considered a new ruin and not a revamp of the old one.

**Comment by Paxilmaniac** [comment]
I've already had plans to make this a bit closer in theme to the original one, in reality this was a little rushed due to the fact that the freeze started today, so give me a bit to see what I can do with it

**Comment by ATH1909** [comment]
I dunno, the large spaces have a sort of charm to them. It makes you feel like you're in a ship that could practically be its own station, like the derelict.

**Comment by Ghommie** [comment]
> I've already had plans to make this a bit closer in theme to the original one, in reality this was a little rushed due to the fact that the freeze started today, so give me a bit to see what I can do with it

If that's the case, you may want to re-PR the current one after the feature freeze is over. It's not that bad and it has a bull terrier in it.

**Comment by BlueMemesauce** [comment]
Why does the back part of the ship syndicate walls??

**Comment by Paxilmaniac** [comment]
I'll come back to this with something better

**Comment by TheBonded** [comment]
I really did like the ruin you had here, but if anything it should be added alongside a new crashed ship instead of as a replacement

**Comment by timothymtorres** [comment]
This looks amazing.  I'm sad to see it was tossed in the garbage...

**Comment by TheBonded** [comment]
> This looks amazing. I'm sad to see it was tossed in the garbage...

... 4 months ago

**Pull request closed without merging**
