### PR TITLE
STRANGLING YOURSELF WITH HANDCUFFS!!

### PR DESCRIPTION
**Pull request by ghost**
and also replacing some .s with !s

:cl: 
tweak: you can now strangle yourselves with handcuffs/zipties/whatever
/:cl:

### CODE REVIEW

**Comment by ShizCalev** [comment]
how does that work with a straightjacket?

**Comment by thefastfoodguy** [comment]
I was thinking it was kinda pushing like, with cuffs for example, the chain between them into your neck until you suffocate. But I dunno for a SJ.

**Comment by Dorsisdwarf** [comment]
Dont straightjackets tie your arms *behind* your back

**Comment by PKPenguin321** [comment]
:-1: Being unable to suicide while restrained is intended to prevent people from being able to just kill themselves. This will break things. Just ghost if you're restrained and no longer want to play.

**Comment by FantasticFwoosh** [comment]
Pure-fact people will suicide out of cuffs to avoid conversion antagonists (if admins dont act on it) is precisely the reason this gets a big fat 👎 from me.

**Comment by thefastfoodguy** [comment]
I just wanna be able to suicide in cuffs at a traitor when being dragged to the brig

**Comment by octareenroon91** [comment]
suicide pill dental implant or put a voice-activated C4 on your PDA

**Comment by MMMiracles** [comment]
I don't see the point of preventing suicide when ghosting is a thing, or just, like, hitting the 'X' button on the window.

**Comment by Repukan** [comment]
This could be doable if it had a check for being pulled. If you're not being pulled then make it have a one second delay before it kills you, if you're being pulled then you can't pull it off (since your arms are being restrained.)

**Comment by coiax** [comment]
Suiciding or ghosting to avoid being converted is bannable. Why are you giving this PR a hard time?

**Comment by FantasticFwoosh** [comment]
Because this is banbaiting coiax, cuffs preserve life but suiciding is worse because your worldly body is dead.

**Comment by Cheridan** [comment]
doesnt seem popular

**Pull request closed without merging**
