### PR TITLE
Ports bay's pickup mobs system, with modifications (WIP DNM ETC)

### PR DESCRIPTION
**Pull request by harmonyn**
DONE:
- Ported Bay's system for picking up mobs
- Refactored drones into this system (as one of the mobs in bay's system was drones.

TODO:
- Sprites. Either I do some wizardry mentioned in #coderbus where sprites are automatically generated, or (more likely) manually generate inhands and obj sprites for all supported mobs
- Fix known bugs with throwing and probably tabling/disposaling/putting in containers
- Add more mobs

### CODE REVIEW

**Comment by PKPenguin321** [comment]
the ability to lift corpses over your shoulders and put monkeys under your arms when

**Comment by Shapsy** [comment]
Firemans carry when

**Comment by bgobandit** [comment]
- Corpses -- Probably prohibitive, dragging by hand simulates this well enough
- Monkeys -- Bay has this, if I can figure out issues with disposals/etc we will have this too

**Comment by Fox-McCloud** [comment]
If it makes it any easier for you, I might recommend checking out Paradise. It has this system in place, and Para is far closer to TG than Bay is, so it may make it easier to port for ya.

**Comment by bgobandit** [comment]
oi @Fox-McCloud 

you still have processing_objects though, which we don't

**Comment by RemieRichards** [comment]
@bgobandit ```SSobj.processing```

**Comment by MrStonedOne** [comment]
Please make a changelog,

You can add it to the PR's body rather then as a file now, see here: https://tgstation13.org/phpBB/viewtopic.php?f=5&t=5157

**Comment by duncathan** [comment]
@bgobandit

**Comment by Razharas** [comment]
No activity for over a month - death

**Comment by PKPenguin321** [comment]
rip

**Comment by bgobandit** [comment]
the fuck re-open this shit

**Comment by duncathan** [comment]
Push another commit and we'll talk

**Pull request closed without merging**
