### PR TITLE
icebox incinerator revamp and some quality of life changes

### PR DESCRIPTION
**Pull request by Red-byte3D**
## About The Pull Request
Revamps the icebox incinerator room
Adds microwave and food to engi/cargo

## Why its good for the game
Adds food to cargo lobby and engi foyer because the lack of food in general on icebox can be very annoying.
Incinerator looks better, less messy and overall better for more advanced setups also giving it a thermomachine waste output will make setting up incinerator way easier and faster
Before 
image
After
image

## Changelog
:cl:
Cleaned up unneeded gas filters in icebox atmos
Changed up icebox incinerator to be cleaner.
Removed Mix to AI Sat pipeline as it was never used.
Added microwave and food to cargo / engi lobby
Moved engi tools vendor from lobby to engineering
Removed unnecessary vendors
/:cl:

### CODE REVIEW

**Comment by Ghilker** [comment]
You removed vendors from engi foyer and stuff from atmos itself

**Comment by Ghilker** [comment]
also don't use grey pipes in the incinerator, they'll connect

**Comment by InsaneRed** [comment]
> You removed vendors from engi foyer and stuff from atmos itself

added those too thanks for the reminder

**Comment by InsaneRed** [comment]
> also don't use grey pipes in the incinerator, they'll connect

the pipes are bridged so they dont connect

**Pull request closed without merging**
