### PR TITLE
Spacesuits now will obscure your neck

### PR DESCRIPTION
**Pull request by SmArtKar**
## About The Pull Request

Spacesuits obscure your neck, thats all.

## Why It's Good For The Game

There's literraly no fucking point why they should not. Like literraly, you put something(for example: scarf) around your NECK and then put a spacesuit. How is it visible?

## Changelog
:cl:
fix: Spacesuits now obscure neck stuff
/:cl:

### CODE REVIEW

**Comment by Angustmeta** [comment]
This will hide head cloaks I assume.

**Comment by Fikou** [comment]
if we look at https://github.com/tgstation/tgstation/blob/master/code/__DEFINES/misc.dm#L15
we see neck items are layering above suit items like space suits
this means you put your scarf/cloak on the suit and it looks badass
there is no reason to make them invisible under the suit

**Comment by SmArtKar** [comment]
> This will hide head cloaks I assume.

Yeah but still, being able to kill people through removing memento mori FROM THEIR NECKS UNDER THE SPACESUITS is bullshit

**Comment by Fikou** [comment]
flags_inv is for making stuff invisible not for making stuff uninteractable

**Comment by SmArtKar** [comment]
> flags_inv is for making stuff invisible not for making stuff uninteractable
> and memento mori is bullshit it deserves to be able to be removed without going through the pain of removing a hardsuit for 50 seconds
Look at the fucking code, it conseals stuff from inventory as well

**Comment by Fikou** [comment]
no

**Comment by Fikou** [comment]
ok sorry
still dumb

**Comment by Winterous** [comment]
If someone's murderboning in the spess mahrin armour with memento mori, and you can't remove it without first removing their armour which takes like 20 seconds, that's ridiculous.
If you want to buff memento, buff memento, not this.

**Comment by SmArtKar** [comment]
> If someone's murderboning in the spess mahrin armour with memento mori, and you can't remove it without first removing their armour which takes like 20 seconds, that's ridiculous.
> If you want to buff memento, buff memento, not this.

Wanted to bring some sense. However, I am still not sure about this PR so it will be fine if coders decide to close it

**Comment by necromanceranne** [comment]
Do we really need to buff memento mori in the first place? It's gimmick is really volatile in the first place, and it was buffed already when beheading was made a little harder to achieve without first heavily wounding the head.

**Comment by Dennok** [comment]
Dullahan genetick power. Headless body with mind.

**Comment by Pugie** [comment]
Memento thing is probably intentional balance wise, makes sense because it can be ridiculously OP mori and stand already kills blob with no counterplay

**Comment by actioninja** [comment]
This feels like an ided pr

**Comment by Pugie** [comment]
Worsened by the fact they didn't even mention that this was really about mori in PR description...

**Comment by brotherbeyondd** [comment]
ided

**Comment by optimumtact** [comment]
ided

**Comment by optimumtact** [comment]
stay on carp station dude

**Pull request closed without merging**
