### PR TITLE
[WIP] Holoparasite Rework

### PR DESCRIPTION
**Pull request by Iamgoofball**
todo:

- [x] Drop price from 18 to 10 telecrystals
- [x] Disable manifesting, manifest via creator/summoner item for 25 stamina on use
- [x] Make holopara abilities de-summon
- [ ] Let you name your holopara

- [ ] Leveling and Experience for Holoparasites
- [ ] Damage increase over levels
- [ ] Abilities become stronger over levels
- [ ] Maybe new abilities unlocked over levels too? optional

new way of using parasites:
1. get injector, use injector
2. get holoparasite deployer from box
3. use in-hand to summon holoparasite

featuring: codersprites

### CODE REVIEW

**Comment by Tlaltecuhtli** [comment]
is this monk but its anime

**Comment by Ziiro** [comment]
I feel like persona memes and jojo guardian memes should be different things filling different niches

**Comment by evsey9** [comment]
for an item that is an obvious traitor tell, it shouldn't require constant use for it to actually become useful.
also it should much rather be something different from a guardian, because as Ziiro said - persona and jojo are different

**Comment by Repukan** [comment]
Go to bed, Joker

**Comment by Iamgoofball** [comment]
i'd argue that the reason it's unused is more due to it costing 18 out of 20 telecrystals to use tbh

**Comment by XDTM** [comment]
The leveling idea is sound, since it lets the user have a choice in keeping the holoparasite as an ace up their sleeve or if they want to trade the surprise factor for an increase in power. The challenge is making it not easily grindable.

**Comment by evsey9** [comment]
it's an OBVIOUS TRAITOR TELL HOW WOULD IT BE "EASILY GRINDABLE"
HOW would you even level this thing without getting the entire station on your tail???

**Comment by Grazyn** [comment]
Just murderbone lol

**Comment by XDTM** [comment]
Go in a secluded room in maint or space or whatever, spam monkeys (with mutadone if it checks for human), proceed to slaughter them till you get levels

**Comment by ChangelingRain** [comment]
*client checks* are the solution!

**Comment by Iamgoofball** [comment]
agree w/ joan, likely to lock it to clients only like I did with monk

**Comment by anconfuzedrock** [comment]
As much as I like holoparas it kinda fucking sucks to stun a baddy only for him to unzip his ggnore holopara and then you're fucked unless you have a combat shotgun on you or something.  Holoparas, especially healing, are the closest traitors can get. I guess I haven't seen how the deployer works but I don't think them being an item you have to carry is a good idea, though. then it's basically just a shade but beefier. And as cool as levelling could be, I can't think of any time it's gonna be used outside of mass murderbone (which can be done with a good holo already)

**Comment by Bawhoppen** [comment]
This is the first time I've ever seen a Goof PR I have no stance on.

**Comment by Iamgoofball** [comment]
I'm going to shove levels into a followup PR and leave this as just the manifest change + price drop. Maybe I'll drop the price even more, idk.

**Comment by ChangelingRain** [comment]
this makes assassin holos pretty bad since they can't follow up their strike with more attacks, and just increasing the damage of that strike probably isn't a good idea since then you edge towards just one-hit crit

**Comment by Potato-Masher** [comment]
Holoparasite love was needed, but I don't think this is the way to do it. At all.

**Comment by XDTM** [comment]
This should definitely be paired with a rework of holoparasites' abilities, right now they're mostly punchghosts with an extra gimmick

**Comment by evsey9** [comment]
This will only be good if the guardian gets the ability to use stuff like Agi or Dia depending on their guardian type and when the guardian user deploys the guardian they see everyone else as a shadow

**Comment by Iamgoofball** [comment]
i wonder if we could achieve that effect with the system we use for drones to swap people

**Comment by Borisvanmemes** [comment]
The best part about holoparasites is that they can pop out on their own while the user is stunned, removing that is a HAAAAARD nerf imo.

**Comment by XDTM** [comment]
On the other hand given this limitation you could buff them a lot. Although i'd go with an action button that can't be used while stunned instead.

**Comment by Shadowflame909** [comment]
Good attempt at a holoparasite revamp. But it needs to be less punch ghost and more jojo RNG.

For Example: A holoparasite that kills you whenever people are standing directly behind you. Instant 300 damage kill. Thats the worst thing. You waste all your tc on this rng machine, and now you're fucked.

Best thing without being too broken: A holoparasite that allows you to write directives onto people very obviously and sort of slowly. Sort of like how long it takes for a ling to absorb a person

**Comment by sentientloaf** [comment]
HEAVEN’S DOOR

**Pull request closed without merging**
