### PR TITLE
Standardizes a majority of the GAGS configs for Clothing

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request
Yikes this stuff is messy to work with...

Fairly comprehensive changelist:
- Removed a LOT of redundant .json files, huzzah!
- Moves the Large Scarf into the normal Scarves .json since they're both 2 component states and can thus share a file
- Renamed almost every single config to have the same naming schemes ("Name (Type)")
- Subtyped a majority of the configs to related ones, inheriting where possible
- Renamed some icons to account for now-inherited .jsons where needed

---

**A relevant question for coders/maintainers:**
As of now, the .json configs are structured with a few rules in place:
- a .json config's states MUST have the same amount of colored component states
- a .json config can not have states that are not buildable via a linked .dmi

The second one is proving troublesome; namely, for toggleable clothing. The object sprites of a majority of these don't change, but the worn sprites have _d added to the end. For a majority of the cases I've been able to just share a .json for the object and worn GAGS configs, but for every toggleable item (such as jumpsuits) they need to keep their own separate .json just to add a new state.
I'm not knowledged in coding proper systems like this, so I was just wanting to ask, is there a way that GAGS's .json configs can have toggle-states without assembling one for the objects?
## Why It's Good For The Game
Code standardization and legibility yahoo
## Changelog
:cl:
refactor: refactored some code relating to greyscale clothing - please report relevant issues on github!
/:cl:

### CODE REVIEW

**Comment by OrionTheFox** [comment]
Opened as a Draft for now if somebody happens to review it, shut it down fully, whatever; I'll do a full-full test tomorrow but as of now there are no runtimes at least (broken gags, as I've learned, causes LOTS of runtimes actually)

**Comment by OrionTheFox** [comment]
Full tests complete. Every single item changed has been checked and works without visible issue.

**Review by Wallemations — APPROVED** [review]
the only sprite changes are those state name changes so that's all good, when it comes to the code that's WAY over my head so you'll need to get one of the code maints on that.

**Comment by OrionTheFox** [comment]
Re-added the buttondown worn .jsons to prevent a conflict with https://github.com/tgstation/tgstation/pull/76865, which needed to split it back up

**Pull request merged**
