### PR TITLE
Suit sensors are maxed by default.

### PR DESCRIPTION
**Pull request by Iamgoofball**
This will make many medical players happy, because now they don't have to screech about sensors.

"But people will be able to find me easier round start if im their objective!"

They already have your Job Name, so they know where to look already. Just shut off your sensors at round start if you really don't want them.

90% of non-antags might as well have their sensors up anyways.

### CODE REVIEW

**Comment by xxalpha** [comment]
No, let the stupid people be forgotten.

**Comment by Iamgoofball** [comment]
That's fucking retarded reasoning and you know it. What if a new player gets killed and can't be found because his sensors were set to 0 by default and he didn't know about it?

**Comment by optimumtact** [comment]
:-1: I prefer to have mine off to metabust

**Comment by Ikarrus** [comment]
Safety Station 13

**Comment by MrStonedOne** [comment]
>"But people will be able to find me easier round start if im their objective!"

Thats not why they aren't maxed by default

Meta.

If they start maxxed by default, then people with them off will be under suspicion.

**Comment by Iamgoofball** [comment]
you can't see their name if their sensors are set to 0

@optimumtact then shut them off

**Comment by xxalpha** [comment]
Open up PDA, look at messenger crew list.

Or crew manifest in the bridge.

**Comment by optimumtact** [comment]
Did you miss the poll where people said more lethal not less?

**Comment by Incoming5643** [comment]
If having your sensors off suddenly becomes suspicious behavior instead of sheer not giving a fuck you've turned the CMO into Security's personal snitch.

**Comment by Iamgoofball** [comment]
@xxalpha manually cross referencing all 60-70 crewmembers to the sensors list to see which ones have their sensors off seems like a chore no one would ever do

**Comment by Iamgoofball** [comment]
oh fuck it i don't care

**Comment by peoplearestrange** [comment]
Wow closed already... I thought this was actually a good idea. *le shrug*

**Comment by Miauw62** [comment]
"george melons doesnt have his sensors on hes a traitor!!!!"

**Comment by Kelenius** [comment]
I'd rather they started fully off.

**Comment by freerealestate** [comment]
Would've been nice not to have to do a suit sensors announcement every round. Unfortunately though, in low pop rounds it'd be very easy for heads to cross-reference the manifest with the suit sensors console to figure out who the suspicious people are.

**Comment by peoplearestrange** [comment]
AH yes, thats true. Hadn't thought about that.

**Pull request closed without merging**
