### PR TITLE
Moves the new HoS winter trenchcoat from the wintercoat file into the proper armor file

### PR DESCRIPTION
**Pull request by GuillaumePrata**
## About The Pull Request
The last security resprite reworked the HoS wintercoat into a subtype of their armored trenchcoat, basically removing the original HoS wintercoat from the game but still left the icon and code of the new trenchcoat inside the old files.

Since I had done multiple clean ups around the wintercoat files I was not going to let it sit there and be confusing, so I moved them into the default armor file together with the base trenchcoat.

Also, ABC'd some lists while I was touching the winter coat file.

## Why It's Good For The Game
Cleaner code with less confusion and maybe avoid some future issues with the winter trenchcoat unsycing from it's base armored trenchcoat because it is on a different file.

## Changelog
Not player facing

### CODE REVIEW

**Comment by TheGreatValvatorez** [comment]
lukas nerf!!

**Comment by Sealed101** [comment]
actually sec resprite was a shadow lukas buff because the armor values were changed and went undocumented
before #69948 it had its unique armor
```	armor = list(MELEE = 35, BULLET = 25, LASER = 40, ENERGY = 50, BOMB = 35, BIO = 0, FIRE = 0, ACID = 55)```
after #69948 it is now taking the values from the parent greatcoat
```	armor = list(MELEE = 30, BULLET = 30, LASER = 30, ENERGY = 40, BOMB = 25, BIO = 0, FIRE = 70, ACID = 90, WOUND = 10)```

**Comment by GuillaumePrata** [comment]
> buff

It also has better resistances against the cold than the default Trenchcoat as it uses `FIRE_SUIT_MIN_TEMP_PROTECT`

**Comment by tgsAvylaar** [comment]
Damn, coders found out the stealth buff...

**Pull request merged**
