### PR TITLE
Adds a retractor to roundstart MD medkits

### PR DESCRIPTION
**Pull request by Toastgoats**
## About The Pull Request
Exactly what it says on the tin.

## Why It's Good For The Game
In it's current state, the Medical Doctor starts with a kit containing the bare minimum tools for surgery, being only able to tend wounds.

Adding a retractor will serve as a good quality of life improvement for doctors, allowing them to quickly respond to any lost limbs or gouged eyes without having to run to the techfab.

## Changelog
:cl:
tweak: Doctors' medkits now contain a retractor. Remember, you can gain experience by dissecting!
/:cl: Doctor Moffy

### CODE REVIEW

**Comment by ATH1909** [comment]
That medipen is actually SUPER useful for preserving corpses (when all of your stasis beds are occupied, unpowered, or otherwise not available); I'd DEFINITELY take it over a retractor.

**Comment by Doosteroni** [comment]
Yeah.....I'll take the medipen over a retractor

**Comment by Toastgoats** [comment]
Makes sense, maybe I could change it to just add?

**Comment by Toastgoats** [comment]
I apologize, I guess I jumped the gun in making changes.

**Comment by ATH1909** [comment]
Does the improved medkit have enough space to hold this additional item?

**Comment by Toastgoats** [comment]
I tested it without removing the medipen earlier, and it seemed to work.
I could test it a bit further just to be sure.

**Comment by ATH1909** [comment]
> I tested it without removing the medipen earlier, and it seemed to work.
> I could test it a bit further just to be sure.

That'd be nice, yeah. You can put the items back into the medkit after taking them out, right?

**Comment by Toastgoats** [comment]
Yes, even after removing all items from the bag, they can all be placed back in the kit with no problems.

**Comment by ATH1909** [comment]
>  remember to send your dissection notes to science!

didn't that get removed?

**Comment by Toastgoats** [comment]
Huh, seems it did. How long ago did they revert that?

**Comment by Angustmeta** [comment]
Dissection wasn't reverted but it was recently changed to give medical skill instead of science points.

**Comment by ExcessiveUseOfCobblestone** [comment]
There are 2 sets of surgery tools in nearly every map. Roundstart is perhaps the most balanced moment for materials where people collectively have to watch out for what they buy, so I'm not keen on just supplying them with free stuff they are already partially supplied under the guise of QoL.

The doctor white kit is meant to supply you with items you can use in a pinch when you've drained all your roundstart supplies (libital/aiuri reserves) like sutures/meshes, with the FINAL stand being the ever-so-enjoyable Tend Wounds. I have no plans to expand the white kit's surgical contents to support more than that (especially since I can already see the saw/drill coming next).

**Comment by Learner10** [comment]
For some reason, I remember a discussion about this exact issue quite some time ago, and I _think_ they decided not to include a retractor since MD's weren't really suppose to start out with a well kitted surgery kit. It was designed specifically to carry just the tools for tend wounds.

**Comment by ATH1909** [comment]
> There are 2 sets of surgery tools in nearly every map. Roundstart is perhaps the most balanced moment for materials where people collectively have to watch out for what they buy, so I'm not keen on just supplying them with free stuff they are already partially supplied under the guise of QoL.
> 
> The doctor white kit is meant to supply you with items you can use in a pinch when you've drained all your roundstart supplies (libital/aiuri reserves) like sutures/meshes, with the FINAL stand being the ever-so-enjoyable Tend Wounds. I have no plans to expand the white kit's surgical contents to support more than that (especially since I can already see the saw/drill coming next).

how is making medical doctors go to the medilathe and print off a retractor at roundstart an intentional part of medbay design

how have we gotten to this point

**Comment by ATH1909** [comment]
> For some reason, I remember a discussion about this exact issue quite some time ago, and I _think_ they decided not to include a retractor since MD's weren't really suppose to start out with a well kitted surgery kit. It was designed specifically to carry just the tools for tend wounds.

they still won't have a saw, which is needed for head/torso organ manips (unless you want to try to use your scalpel as a ghetto saw, but that will take aaaaaaaages and have a really high chance to straight up fail, even on a proper surgery table)

**Comment by optimumtact** [comment]
seems like a buff for buffs sake

**Pull request closed without merging**
