### PR TITLE
Stops revheads from being metagamed with healthscanners & medical HUDs.

### LINKED ISSUE #31101: Revheads can be spotted MedHUD
pretty much what the title says, tried it out on a test-server. Made a revhead dummy, then plucked on Medical HUD as another dummy.

### PR DESCRIPTION
**Pull request by ShizCalev**
150 hours.

Fixes #31101

### CODE REVIEW

**Comment by BeeSting12** [comment]
@ShizCalev Make it not change your eye color

**Comment by SgtxRootbeer** [comment]
what about eyes being recolored?

**Comment by ShizCalev** [comment]
I'm not seeing the implant recoloring eyes ingame. Is it actually happening?

**Review by Cyberboss — APPROVED** [review]

**Comment by kevinz000** [comment]
itt robustin

**Pull request merged**
