### PR TITLE
Makes step var not editable by admins

### PR DESCRIPTION
**Pull request by lzimann**
There's no reason this var should ever be edited so...

### CODE REVIEW

**Comment by MrStonedOne** [comment]
Actually I have intentionally edited this variable to create this effect during meme rounds.

So there is a legit reason =P

**Comment by lzimann** [comment]
you can still probably do that by a sdql2 query

**Comment by Incoming5643** [comment]
They're already VVlocked vars

**Comment by lzimann** [comment]
VVlocked only prevents if you don't have +DEBUG

**Comment by Incoming5643** [comment]
The implication here is that if you have +DEBUG you'd know not to touch step_xyz

**Comment by optimumtact** [comment]
hah, that would imply that the roles are setup sensibly

**Comment by lzimann** [comment]
the permissions are all messed up and could probably use a rework(that i won't do)

**Comment by MrStonedOne** [comment]
A better solution might be to make it give some warning pop up if you have +debug and not allow it without that.

Then we could expand it to other shit.

Anywho, this is all moot if i ever finish my vv refactor.

**Comment by kevinz000** [comment]
>heeding warning popups
wew

**Comment by optimumtact** [comment]
This isn't the right solution

**Pull request closed without merging**
