### PR TITLE
Delete the path compatibility tree

### PR DESCRIPTION
**Pull request by Cyberboss**
@AnturK told me to

### CODE REVIEW

**Comment by Iamgoofball** [comment]
:-1: using this for goofanimals

**Comment by RemieRichards** [comment]
Overruling @AnturK, there's nothing wrong with this.

**Comment by optimumtact** [comment]
>goof using this

concern.gif

**Comment by Iamgoofball** [comment]
I'd rather not edit 50 dmms

**Comment by AnturK** [comment]
Killing code readability to save 30 seconds of repathing time is not fair trade. I added the repath script for this exact purpose, if you feel it's too slow that's another matter but this file is just pure laziness.

**Comment by xxalpha** [comment]
I don't get it, there's no code in that file.

**Comment by AnturK** [comment]
Because it was already cleaned up, no need to encourage it further.

**Comment by KorPhaeron** [comment]
@Cheridan

**Comment by Cheridan** [comment]
I agree with Anturk but I'll give some time to let others weigh in

**Comment by Cyberboss** [comment]
Personally, I dislike the parent_type business. It's a crutch and bad
practice. It's not hard to `git grep -l $path | xargs send -i -b
's/$path/$newpath/g'`

**Comment by coiax** [comment]
I didn't know that we had this. And this is some serious bad practice.

Also @AnturK does your script work at repathing maps?

**Comment by AnturK** [comment]
Yes, it's for when you need more fine-grained replace than 1:1 path replacement. Uses simple rule system. It's under mapmerge/path_update

**Comment by lzimann** [comment]
Repathing things by using this is pretty awful and confusing, if you want to repath, do it properly.

**Comment by ChangelingRain** [comment]
As frustrating as map edits are, you have to do them sometimes and this file will only result in confusing mess bullshit if actually used.

**Pull request merged**
