### PR TITLE
Make screwdrivers able to be inserted into the destructive analyzer through left-click

### LINKED ISSUE #62456: You can't deconstruct alien screwdrivers
trying to put them in the destructive analyser just opens the panel on the machine.

### PR DESCRIPTION
**Pull request by RandomGamer123**
## About The Pull Request
See title

## Why It's Good For The Game
Fixes #62456

## Changelog

:cl:
fix: Screwdrivers can now be inserted into the destructive analyzer through left-click
/:cl:

### CODE REVIEW

**Comment by Ghilker** [comment]
How you deconstruct it?

**Comment by RandomGamer123** [comment]
you right click with a screwdriver

**Comment by Ghilker** [comment]
> you right click with a screwdriver

Every other deconstruction action uses left click, why this is special?

**Comment by SuperNovaa41** [comment]
maybe add insertion on right click

**Comment by RandomGamer123** [comment]
> > you right click with a screwdriver
> 
> Every other deconstruction action uses left click, why this is special?

Its the same behavior as the autolathe (left click: inserting, right click: open panel) and the tank frame (for some reason) (right click: deconstruct)

got it from the issue request: `A check should be made that allows you to insert a screwdriver by left clicking (and open the maintenance hatch by right clicking, since right clicking is used for deconstruction generally)`

**Comment by Ghilker** [comment]
The issue report is wrong as every other machine uses left click (except the ones you mentioned that also should be changed)

**Comment by zxaber** [comment]
On the flipside, things like tables have to be deconstructed using right-click as a sort of override, since left-click places the item onto the table. So it's more consistent with *that* if insert is left and deconstruct is right.

**Comment by RandomGamer123** [comment]
Changed back to left click for insert, right click for deconstruct

**Comment by Mothblocks** [comment]
> Every other deconstruction action uses left click, why this is special?

We're trying to fix that, a lot of stuff is on RMB already

**Pull request merged**
