### PR TITLE
Honked moodlet updates

### PR DESCRIPTION
**Pull request by Mickyan**
:cl:
imageadd: Coming into contact with -HONK- may have additional effects, do not be alarmed
tweak: For safety reasons, the administration of -HONK- may only be performed by trained professionals
fix: Self-application of -HONK- is now forbidden 
/:cl:

The moodlet from being hit with a bike horn now has its own overlay.
Screenshot_3
Changed the description to not make assumptions about the quality of local entertainers.
The moodlet can only be applied by clowns, as they are the only ones capable to unlock the bike horn's true hidden power.
You can no longer get a mood boost by hitting yourself with a bike horn.

### CODE REVIEW

**Comment by Tlaltecuhtli** [comment]
how does it look like when you have suicidal moodlet and you get honked?

**Comment by fludd12** [comment]
Honksturbation while on the job is against company policy and the honkppocrattic oath.

**Comment by tralezab** [comment]
FINALLY someone used my special moodlet overlays

**Comment by Ziiro** [comment]
Can a clown just get that moodlet overlay 24/7 anyway then for their own screen?

**Comment by ATH1909** [comment]
Aw, I liked being able to cheer people up by whacking them with a bible, honking them with a bike horn, and then hugging them with the friendly quirk...

**Comment by Nickkoranda** [comment]
speedmerge

**Comment by msgerbs** [comment]
I don't like the idea of having this tied to your roundstart job. Is there any other way this could be balanced? Require the full clown suit or something?

**Comment by nemvar** [comment]
This requiring the clumsy trait would be perfect.

**Comment by HomocidlePancakes** [comment]
I want to increase peoples mood by hitting them with a baguette as a mime

**Comment by GuyonBroadway** [comment]
Doesn't this mean two clowns can honk eachother for a boost?

**Comment by fludd12** [comment]
Company policy says nothing about honktercourse.

**Comment by optimumtact** [comment]
Yeah we're trying to move away from mind checks.

Either add a clown trait or rely on the clumsy trait

**Review by SpaceManiac — APPROVED** [review]

**Pull request merged**
