### PR TITLE
Allows Cultists to draw runes in the Library

### LINKED ISSUE #48118: You can't draw cult runes in library
#### Round ID:
124992 Sybil and confirmed locally. 

#### Reproduction:
* Be cultist. 
* Go to library and activate dagger in hand. 

Result:

You're probably supposed to be able to draw runes in the library.

### PR DESCRIPTION
**Pull request by TheVekter**
## About The Pull Request

Fixes #48118.

## Why It's Good For The Game

Iä! Iä! Cthulhu fhtagn! Ph'nglui mglw'nfah Cthulhu R'lyeh wgah'nagl fhtagn!

## Changelog
:cl:
fix: The Cult should now actually be able to draw runes in the Library.
/:cl:

### CODE REVIEW

**Comment by Angustmeta** [comment]
From ctrl-F'ing that file it seems same issue exists with these areas:
* Chapel
* Abandoned Library
* Atmospherics
* Solars
* Virology
* Custodial Closet

**Comment by TheVekter** [comment]
Pretty sure the Chapel is intentional due to, y'know. Chaplains. I'll test in these other areas.

**Comment by Firecage** [comment]
Mmm, you can probably just remove the line for the flag from the abandoned library perhaps due to the parent having it?

**Comment by 81Denton** [comment]
Solars (the space part) and chapel are intentional, the rest not

**Comment by Naloacisamazing** [comment]
The chapel still counts as a Nar-sie summon site which probably shouldnt be a thing either.

**Comment by TheVekter** [comment]
> Solars (the space part) and chapel are intentional, the rest not from what I recall.

Since that kinda bleeds into balance related stuff I'm not gonna touch it, that's kind of out-of-scope for this PR.



> The chapel still counts as a Nar-sie summon site which probably shouldnt be a thing either.

PFFFFT, that's pretty funny. I'll look and see what I can do about that and add another PR for it.

**Pull request merged**
