### PR TITLE
Adds Vulpkanin, Tajaran, Skrell, and IPCs to the game.

### PR DESCRIPTION
**Pull request by Iamgoofball**
Original PR at #22115 

If all the other snowflake buffs are allowed why can't we have these

### CODE REVIEW

**Comment by Haevacht** [comment]
Haha merge conflicts on a meme pr, are you even trying?

**Comment by Arianya** [comment]
Feature Freeze

**Comment by theOperand** [comment]
>goofball

**Comment by Cyberboss** [comment]
100$ The diff on the dmis is shit too

**Comment by kilog** [comment]
u could also not

**Comment by Iamgoofball** [comment]
>Miauw renamed his account

**Comment by Ninja137** [comment]
Can we at least get /vg/'s jewish birdpeople if we're doing this?

**Comment by RemieRichards** [comment]
@Iamgoofball he's operand in a few places, so Miauw was the odd one out really.

**Comment by kol1th** [comment]
solid PR, approved

**Comment by Iamgoofball** [comment]
sure I guess I'll port them later

**Comment by Gef21** [comment]
can we have them as well pls

**Comment by Bawhoppen** [comment]
:+1: goof gets it right

**Comment by dannno** [comment]
what set you off this time, buddy

**Pull request closed without merging**
