### PR TITLE
Adds the Organ Preservation nanite program

### PR DESCRIPTION
**Pull request by XDTM**
## About The Pull Request

Added a new nanite program, Organ Preservation. While the host is dead, it consumes 0.4 volume per tick to prevent organ decay, like formaldehyde would.

_Bonus: added nanite machinery to runtimestation, since testing nanites requires the full set of machinery and spawning it every time gets old really fast_

## Why It's Good For The Game

Modern problems require modern solutions! This program allows nanites to serve as "death insurance" for those who are willing to risk having nanites in their bloodstream to achieve it. The cost will allow this program to run by itself indefinitely, but it's enough that it will strain nanite volume if you're also using nanites to attempt to heal the body at the same time.

## Changelog
:cl: XDTM
add: Added a new nanite program, Organ Preservation. While the host is dead, it consumes 0.4 volume per tick to prevent organ decay, like formaldehyde would.
/:cl:

### CODE REVIEW

**Comment by TemporalOroboros** [comment]
Do nanites generate volume while the host is dead?

**Comment by XDTM** [comment]
Yes, the replication rate is unchanged

**Comment by Tharcoonvagh** [comment]
_I solve practical problems_

**Comment by optimumtact** [comment]
seems overpowered

**Comment by InvalidArgument3** [comment]
this is incredibly useful for medical. Spending 10 minutes replacing the organs of a long dead body that still has a soul only for them to be SSD on revival is the most painful experience in the game

**Comment by XDTM** [comment]
My initial thought was that the regular nanite risks would counterbalance it (after all you can already use them to self-defib and potentially regenerate from crit), but if it is still unbalanced it could be nerfed by making its cost higher, limiting the duration of its effect

**Comment by optimumtact** [comment]
I doubt nanite risk is even a real thing

**Comment by XDTM** [comment]
I've heard from multiple sources that many players refuse nanites outright after getting screwed over one time too many

**Comment by ATH1909** [comment]
I was gonna ""eventually"" make this a threshold effect for the necrotic metabolism symptom, but this also works.

**Comment by ATH1909** [comment]
Maybe increase the nanite cost per tick to be 0.6/tick or 0.7/tick, so it can't preserve your organs indefinitely without some trickery/cooperation with viro?

**Comment by carshalash** [comment]
> I doubt nanite risk is even a real thing

Chain detonation still exists.

**Comment by CRITAWAKETS** [comment]
HAHAHAHAHAHAHAH **FUCK NO**

this makes it so you can pretty much defibrilate out of any situation that doesnt give you constant damage if you just give it enough time

**Comment by InvalidArgument3** [comment]
But can't a necrotic metabolism + any healing virus already do that?

**Comment by moocowswag** [comment]
Nanites definitely do have a risk, once empd there is a very high chance of your nanites killing you and you losing all of the benefits of having them... also this does not give someone invulnerability, the nanite defib does NOT work against oxyloss damage unlike normal defibs so youll get unrepairable damage just from being in crit, and you take a massive oxyloss hit if you succumb which pretty much gimps nanites from ever being able to revive you without putting you into a death loop.

That and someone could just you know...hit you until your organs spill out....or put you literally anywhere youll take passive damage faster than the nanites can repair you (space, somewhere without air, etc) Saying this will make someone invincible is  extremely overdramatic at best.

In general this doesnt make nanites that much easier to defib someone, bio reconstruction is still preferable to horde all of the excess nanites into reviving yourself faster and if youre augmented / have bionic organs you dont even need this program in the first place, just a brain healing program that switches itself on and off to keep up with the damage your brain takes while youre dead would be more efficient than this.

But this definitely does synergize with medical staff and will definitely make medbay able to go through corpses alot quicker.

Back to nanite risk though yes it is real, a single corrupt program is capable of killing people, almost any of the weaponized programs being slotted into the cloud is capable of killing everyone connected to the cloud, even the ones that dont require illegal tech will have most of the connected population drop dead before people realize whats going on.

Even the cloud controller being destroyed/losing power puts everyone at risk because now everyone is going to roll the dice for corruption while their programs are randomly triggered and toggled off/on. Based on that fact alone, nanites almost always require both the engineering and science department to remain safe and functional for nanites to remain beneficial, unless someone decides to make their own satellite with its own power source to hold the cloud or something.

**Comment by XDTM** [comment]
> 
> 
> HAHAHAHAHAHAHAH **FUCK NO**
> 
> this makes it so you can defibrilate much more easily since THAT is a program.
> 
> Also, if a timer program is ever added, enjoy basically invincibility!

Hold on, why would anyone wait enough time for organ damage to be a factor before nanite-defibbing?

**Comment by Winterous** [comment]
I would say that it should consume at least as much as the natural increase rate. And should have a corrupted counterpart that damages your organs.

**Comment by Hadzabadza** [comment]
> HAHAHAHAHAHAHAH **FUCK NO**
> 
> this makes it so you can defibrilate much more easily since THAT is a program.
> 
> Also, if a timer program is ever added, enjoy basically invincibility!
> 
> EDIT: wait with a nanite volume sensor you can actually get invincibility because nanite regen is 0.5/0.6

Bio-reconstruction, the most important nanite program, takes 5.5 nanites per second to heal 2 damage. Max amount of nanites is 500 and the default threshold past which you can't even use them is 50. Default nanite growth is 0.6. 450 nanites divided by 4.9 consumption and multiplied by 2 HP is 182 hit points healed over 90 seconds (the heart takes 4 minutes and about 20 seconds to completely die and to defib you need to have less than 180 of each type of damage). You can kill someone in less than 15 seconds even with nanites on if you shove stun and use a toolbox AND on top of that most people on station have 0 idea how to properly program a defib that will actually work. If you have a fire axe or two beakers with iron and uranium, your adversary is super-dead. One EMP destroys 20-40 percent of nanites instantly and on top of that corrupts them.

**Comment by CRITAWAKETS** [comment]
> > Also, if a timer program is ever added, enjoy basically invincibility!
> 
> This is literally proof that you`ve never even touched nanites. signal repeaters and trigger delays exist and you can make loops/timers/clocks that send signals, and even turn the loop/timer/clock on and off when recieving a signal

No, its proof that you never even made a real nanite setup and have only been doing theoreticals in a powergamer discord. If you didnt know, nanites have a program cap. And one thing you want with nanites is to have a lot of programs. A clock takes a lot of programs. Do the math.

**Comment by CRITAWAKETS** [comment]
> Hold on, why would anyone wait enough time for organ damage to be a factor before nanite-defibbing?
> If it's to accumulate enough volume to regenerate your damage enough to revive, the 0.1 regen rate you get while running this program will probably end up not reviving you before the round ends, even assuming your body is undisturbed

The problem is not about slowness of healing or whatever even if that may come in the future if cobby ever finds out nanites exist. The problem is more about the fact that unless you get rid of that person's nanites or give them constant damage for the whole round, they will always come back up. Even if you give them constant damage, unless they are husked you can bring them back to life by just removing the source of the damage and waiting.

**Comment by moocowswag** [comment]
> No, its proof that you never even made a real nanite setup and have only been doing theoreticals in a powergamer discord. If you didnt know, nanites have a program cap. And one thing you want with nanites is to have a lot of programs. A clock takes a lot of programs. Do the math.

I literally have videos of me doing nanites, even one dedicated to displaying the "risk" of getting nanites when someone is a traitor, its not hard to crunch down on program count by using rules and restart timers, ive even been able to do trivial games involving people having buttons pop up that activate passive effects if they press the right one.

Even with organ preservation added im confident i wont hit that program limit.

And seriously, organ preservation isnt going to be the end all counter to murder, it doesnt take that many clicks after someone goes horizontal to make their innerds become outterds.

**Comment by XDTM** [comment]
>The problem is more about the fact that unless you get rid of that person's nanites or give them constant damage for the whole round, they will always come back up.

My point was that even if that's true in theory, in practice it takes too much time to realistically rely on. Aside from evisceration and beheading, you can also expose the corpse to damaging temperatures or space to damage it faster than the nanites can help it. And the healing, at a 0.1 regen rate (default is 0.5 and reduced diagnostic no longer exists), is _not fast_.

**Comment by Hadzabadza** [comment]
>  Even if you give them constant damage, unless they are husked you can bring them back to life by just removing the source of the damage and waiting.

This is ridiculous and can never actually happen. Even if you beg cargo to get you bepis protocols. Also wounds are a thing

**Comment by spookydonut** [comment]
doesn't even pass travis, @XDTM may want to fix this

**Comment by XDTM** [comment]
Whoops, didn't notice

**Comment by XDTM** [comment]
The travis runtimes don't seem to be related to this PR this time

**Comment by ArcaneMusic** [comment]
Looks fine, could you send a blank new commit so we can see the map edits?

**Comment by XDTM** [comment]
@ArcaneMusic should be visible now, i added them in the gulag shuttle corridor northwest of the research room where they shouldn't bother anyone

**Comment by cacogen** [comment]
botssassinated

**Comment by XDTM** [comment]
smh

**Pull request closed without merging**
