### PR TITLE
Moths now have weak eyes

### PR DESCRIPTION
**Pull request by Shadowlight213**
:cl:
balance: Moths are now more susceptible to bright lights
/:cl:

The current moth downsides are a joke in exchange for free magboots.

### CODE REVIEW

**Comment by coiax** [comment]
Does that mean that they can't be protected even with a welding helmet now?

**Comment by ma44** [comment]
If you manage to secure both a welding mask and goggles, this bumps you up into flash_protect = 2, or just wearing a space suit helmet (yes they provide flash protection) and welding goggles should also work.

**Comment by Kromgar** [comment]
I have no qualms with this

**Comment by Potato-Masher** [comment]
Wew, another issue to think about when playing moth engineer. This will certainly be a more frequently appearing downside than instantly dying to SM zaps.

Trust me, the last time I saw a moth try to fix a failing SM didn't end too well.

**Comment by coiax** [comment]
Wearing both welding goggles AND a welding helmet drops your visibility to BLIND level. But I guess that's a feature in this case.

**Comment by Shadowlight213** [comment]
@potato-masher
Moths do not take extra burn damage. I don't know why everyone thinks they do, but if you could point me to the code saying they do, that would be great.

**Comment by Shadowlight213** [comment]
@coiax sunglasses are a thing.
They don't drop visibility.
Spacesuit helmets are a thing, etc

**Comment by Shadowlight213** [comment]
Also promotes departmental cooperation because moths can go to science/medbay and get new eyes.

**Comment by Iatots** [comment]
Not sure if this is possible, but could moths be more sensitive to darkness? As in, every tile below X in brightness they see as half as bright, meaning the station becomes much darker to them and they are forced to stay around light fixtures or hoard shiny lights in their workplace.

Also, make them jump at laser pointers like cats too.

**Comment by ma44** [comment]
@coiax technically you can weld stuff perfectly fine as long as you have a hardsuit helmet (that's not med related) or a space suit helmet that is then combined with some welding goggles. A welding gas mask combined with goggles should also mostly solve any of your problems.

**Comment by DaxDupont** [comment]
It's probably better to nerf the flying with a slowdown than making them almost blind.

**Comment by calzilla1** [comment]
Make them have to wear contacts/ glasses

**Comment by ChangelingRain** [comment]
@Iatots it's technically possible but it's also a pain in the ass so it's unlikely anybody is going to do it.

**Comment by KorPhaeron** [comment]
@Iatots @MrStonedOne was talking about doing that for people in general, don't know if he is still planning on it though

**Comment by coiax** [comment]
Making all moths short sighted sounds like kind of a neat idea, actually.

**Comment by MrStonedOne** [comment]
@kor its on the todo list, atm i'm working on replacing tgui thou, so it would have to wait for that.

**Comment by Shadowlight213** [comment]
The funny thing is, when originally making this pr, I didn't consider welding at all. I was just wanting ti make them more susceptible to flashes.

I didnt realize that flashing had been nerfed to the point where having weak eyes didnt do much.

I mean, I could look into finding some hopefully not snowflake way to make welding helmets work, thay doesn't result in a complete rework of flash protection as a whole.

**Comment by Tlaltecuhtli** [comment]
u can make a blindfold with bedsheets

**Comment by ma44** [comment]
If moths someone become security personal, then their starting sechuds cannot protect them against flashbangs or flashes unless they get another item that provides flash protect.

**Comment by Spaceinaba** [comment]
we should still slow the flight down tbh
this is an interesting way to do the light weakness gimmick though

**Comment by ExcessiveUseOfCobblestone** [comment]
>  i'm working on replacing tgui thou

Thank you @MrStonedOne

**Comment by 81Denton** [comment]
>Also, make them jump at laser pointers like cats too.

If anything moths should flutter towards tesla engines, like a humongous bug zapper.

**Comment by Xhuis** [comment]
geez I'm sure gonna love not being able to reasonably play any engineering role as moth now

**Comment by Xhuis** [comment]
with this PR a welding helmet will not protect from welding, and sunglasses are inconsistent to find; even with chances being decent i don't want to put being able to effectively do my job to a guessing game or a random number generator.

**Comment by Bawhoppen** [comment]
There's something surprisingly refreshing about how open and blatant Leo is with his moth hatred.

**Comment by lzimann** [comment]
I don't know, having weaker eyes in favor of flight(which gives you plenty of benefits) is not really a big deal.

**Comment by Xhuis** [comment]
I'm not in support of flight either and I think it was silly that it was merged with such a massive upside on what was touted as a race similar to humans

**Comment by AcuteCircle** [comment]
i played sec officer moth and flashbang stunned me with sechud sunglasses + protective headset. feature?

**Pull request merged**
