### PR TITLE
Added Banana Peels Inhand Sprites [Partial Fix - #30081]

### PR DESCRIPTION
**Pull request by Mercenaryblue**
:cl: Mercenaryblue
imageadd: added some in_hands for banana peels.
/:cl:

[why]: Because every item need their own in_hands, and peels were without one for way too long.
[Imgur](https://i.imgur.com/RC935HB.png)

### CODE REVIEW

**Review by ShizCalev — APPROVED** [review]

**Comment by calzilla1** [comment]
This is a major nerf to clowns

**Comment by Mercenaryblue** [comment]
Not quite - you can still hide the peel behind your body, if you angle it well.

**Comment by Supermichael777** [comment]
Only copper teir clowns abuse a lack of inhands for their HONKS 📯

**Comment by Bawhoppen** [comment]
>powergamers thumbsing down a blatant immersion break fix

**Pull request merged**
