### PR TITLE
Plants don't get their positions ruined when dropped

### PR DESCRIPTION
**Pull request by maxymax13**
## About The Pull Request
Tiny atomic one line change that makes plants stay in the same place when you drop them.
https://user-images.githubusercontent.com/38844529/116613578-d72ed280-a906-11eb-9db3-d0fd17927b3a.mp4

## Why It's Good For The Game
What's the point of being able to hide in a plant if anyone with basic object permanence can see that a plant that used to be offset off the tile is now centered?
Also I was tired of seeing all the plants in the bar turn really ugly and offset the second Pun Pun gets to them with no way of centering them again.
image
This looks awful.

## Changelog
:cl:
qol: Pun Pun can no longer ruin all the tile alligments of the plants in the bar, as plants no longer get offset when dropped.
/:cl:

### CODE REVIEW

**Comment by TemporalOroboros** [comment]
Thank you. I'm tired of building racks to center things.

**Comment by maxymax13** [comment]
@Krysonism why not

**Comment by TheBonded** [comment]
> Thank you. I'm tired of building racks to center things.

or you can just alt click a table and put something on it through the object menu

**Comment by maxymax13** [comment]
> 
> 
> > Thank you. I'm tired of building racks to center things.
> 
> or you can just alt click a table and put something on it through the object menu

that is the most obtuse interaction i've ever seen for what is already a buggy obtuse menu

**Pull request merged**
