### PR TITLE
Removes gas destabilizing the supermatter for @GunHog bodies only now

### PR DESCRIPTION
**Pull request by Iamgoofball**
capture

### CODE REVIEW

**Comment by Qbopper** [comment]
what does the image in the OP have to do with the change

**Comment by kevinz000** [comment]
Dumb goofball cat

**Comment by GunHog** [comment]
I said **MOST RELIABLE**, not **ONLY WAY**. I know you are just meme-ing at this point, but it is kind of fun!

**Comment by Iamgoofball** [comment]
capture

**Comment by GunHog** [comment]
This PR is not replacing it with the singulo!

**Comment by kevinz000** [comment]
Meme PR.

**Comment by Iamgoofball** [comment]
oh sorry gunhog

**Comment by kevinz000** [comment]
Gun hog don't bother he's just getting popularity for the next headmin elections.

**Comment by GunHog** [comment]
But this is _FUN!_

**Comment by lzimann** [comment]
Come on goof.

**Pull request closed without merging**
