### PR TITLE
Boots redux v2

### PR DESCRIPTION
**Pull request by ghost**
Inb4 this is opposed more than changing the sprite from grey UGG boots is.
- Renames jackboots to simply 'boots'
- Adds unique SWAT/combat boots laceup sprites (for death squads and syndicate nuke ops respectively)

ss 2014-12-27 at 12 12 09
(sprite updated 12/27/14)

Gonna leave the work boots out of this one for reasons of my sanity.

### CODE REVIEW

**Comment by WJohn** [comment]
Personally I'm fine with both our current unchanged boots, and with what atskadan did there with your sprites as they have a nice, visible outline. They also in my opinion have a better shading, as it feels more from the front rather than way off to the side, and makes the boots seem wide (and I do like bulky boots).

If it still doesn't satisfy you I think I'll try my hand at this when I get back home from visiting family in a couple of days.

**Comment by paprka** [comment]
Conflicts fixed.

There seems to be some confusion as well.

This PR doesn't change the sprites of jackboots, simply renames them. It only changes the sprites of combat/swat boots that syndicates use. That's it. If someone wants to improve the sprites later I don't fucking care but please stop bikeshedding about simple unique sprite replacements, I'm tired of it.

**Comment by paprka** [comment]
Conflicts fixed

@Nienhaus

**Comment by Nienhaus** [comment]
@paprka "Merge with caution" I don't feel safe about that.
Also, @Cheridan It's cool to merge this correct?

**Comment by tkdrg** [comment]
Pretty sure that this one breaks mini because of the repath.

**Comment by Steelpoint** [comment]
The sprite is bad, just keep the current combat boot sprites.

**Comment by paprka** [comment]
They're the same as jackboots even though combat boots have a lot more armoring than jackboots and swat are noslip, so no.

**Comment by paprka** [comment]
It can be changed later then, because my opinion on it apparently doesn't matter to you art geniuses. But I'm not changing it any more in this fucking PR.

**Comment by pudl** [comment]
den close da pr bruh

**Comment by paprka** [comment]
Sure thing

**Comment by paprka** [comment]
Conflicts fixed

**Comment by Steelpoint** [comment]
Sprites are still very, very sub-par.

**Comment by paprka** [comment]
Fun tip about the project: you can change them after this PR is accepted and there's literally nothing I can do about it since these sprites/this code doesn't belong to me at that point

**Comment by pudl** [comment]
you talk like some maintainer is actually willing to be blackmailed, like
"IF YOU WANT THE BOOT NAMES CHANGED, YOU HAVE TO TAKE THIS SHITTY SPRITE!!"
lmao

**Comment by pudl** [comment]
also no map merge bro

**Comment by paprka** [comment]
pretty sure the map is just broken because of the new shitty merger system

**Comment by pudl** [comment]
the new merge system works perfectly fine, i used it for my chemistry pr. but i do agree that it's harder to use.

**Comment by paprka** [comment]
i'll redo this eventually

**Pull request closed without merging**
