### PR TITLE
[s] Fixes nasty cleanbot bug

### PR DESCRIPTION
**Pull request by PKPenguin321**
Turns out that as it would happen, testing your code doesn't always account for things like this
That being said, this is tested and still strong, but not 1200 damage strong

### CODE REVIEW

**Comment by Shapsy** [comment]
Clean bots have no chill

**Comment by KorPhaeron** [comment]
That's still 80 damage, isn't it?

**Comment by phil235** [comment]
yeah, still 80 damage, use toxinpwr = 2, just like facid.

**Comment by PKPenguin321** [comment]
it only does that if you're completely naked, with almost any amount of clothing you'll take 0 damage and have plenty of time to run away as it cleans the goo
acid is really *really* weak if you're wearing clothing

**Comment by KorPhaeron** [comment]
Maybe clothes provide too much acid protection if the choice is between 0 and 80 damage

**Comment by phil235** [comment]
We're talking about effects on non-carbon mobs. toxpwr has no incidence on human damage but it is used to calculate damage at the living level.

**Comment by PKPenguin321** [comment]
turns out this isn't as big of a deal as i thought, as cleanbots only target carbon mobs, and the value i'm changing does nothing against carbon mobs. still though, it's a worthy fix

**Comment by duncathan** [comment]
Only off by like two orders of magnitude

**Comment by PKPenguin321** [comment]
hey man, that value doesn't even technically do anything since it's never called on noncarbons, don't blame me for not catching that it's 60x higher than it's supposed to be during testing

**Pull request merged**
