### PR TITLE
Readds the syndicate comms officer

### PR DESCRIPTION
**Pull request by ShizCalev**
With a 10% chance of existing.

🆑 ShizCalev
add: The Syndicate Comms Officer ghost role has been readded with a minor chance of actually existing.
/🆑

### CODE REVIEW

**Comment by DaedalusGame** [comment]
ok i guess

**Comment by 81Denton** [comment]
I'm surprised this wasn't done in the first place tbh

**Comment by WJohn** [comment]
This should instead be a simple revert of jalleo's change, and instead make use of antur's new system in #35209

**Comment by Plapatin** [comment]
make up your fucking mind

**Comment by KorPhaeron** [comment]
@WJohn 

Why? How would it improve the game if the syndicate lava base is periodically cancelled by a stripped down version with less to do for ghosts and a lesser chance of the crew ever being able to counter?

**Comment by WJohn** [comment]
Antur's system does not strip them down to their basics, it lets you instead reduce the chances of these things spawning which is what people had a problem with.

**Comment by DaedalusGame** [comment]
I think he was trying to insinuate that if lavabase and listening post are made mutually exclusive, listening post spawning in space would prevent the lavabase from spawning, and the listening post is objectively less interesting than the lavabase, while also being harder to find and harder to destroy.

**Pull request merged**
