### PR TITLE
TASER BALANCING

### PR DESCRIPTION
**Pull request by ghost**
:cl: More Robust Than You
balance: Two electrodes to the asshole are now required to down a fully energized person, down from 1.
balance: Disabler beams now take slightly less energy, to encourage security officers to realize that hybrid tasers also shoot disablers.
/:cl:

### CODE REVIEW

**Comment by ExcessiveUseOfCobblestone** [comment]
Reasoning please.

**Comment by PKPenguin321** [comment]
Stop reopening this

**Comment by qbmax32** [comment]
learn to dodge tasers then

**Comment by MoreRobustThanYou** [comment]
you do realize how frantic running from a guy with a taser is, right? sometimes you are unlucky enough to move onto a tile JUST AS an electrode moves onto it. RIP u.

**Comment by BeeSting12** [comment]
ahhahahahhahahaha what

**Comment by BeeSting12** [comment]
you do realize how frantic running from a guy with a stetchkin is, right? sometimes you are unlucky enough to move onto a tile JUST AS a bullet moves onto it. RIP u.

**Comment by BeeSting12** [comment]
you do realize how frantic running from a guy with an ebow is, right? sometimes you are unlucky enough to move onto a tile JUST AS a bolt moves onto it. RIP u.

**Comment by BeeSting12** [comment]
you do realize how frantic running from a guy with a shotgun is, right? sometimes you are unlucky enough to move onto a tile JUST AS a pellet moves onto it. RIP u.

**Comment by MoreRobustThanYou** [comment]
you do realize how frantic running from a guy with a massive dick is, right? sometimes you are unlucky enough to move onto a tile JUST AS a semen moves onto it. RIP u.

**Comment by MoreRobustThanYou** [comment]
you do realize how frantic running from an angry monkey is, right? sometimes you are unlucky enough to move onto a tile JUST AS the monkey residue moves onto it. RIP u.

**Comment by MoreRobustThanYou** [comment]
point is, dont give sec officers 1HKO weapons

**Comment by F-OS** [comment]
STOP NERFING EVERYTHING I HOLD DEAR

**Comment by Buggy123** [comment]
I HAVE NO STRONG OPINION BUT I LIKE SCREAMING AND EXCLAMATION POINTS!!!!!!!!!!!1!111!!!11!1ONE!

**Comment by PKPenguin321** [comment]
>he still thinks tasers are op when disablers are in the game

Disablers:
- stupid amount of ammo means they can be spammed freely
- can pass through things tasers can't, such as windows
- deal absolutely stupid amounts of slowdown due to "le epic balanced stamina damage" that essentially make dodging any shots after getting hit once a herculean exercise in luck
- stun for longer once youre on the ground
- stack with any other type of damage
- can chainstun by just dealing regular damage once you're on the ground because of the above point (meaning disabler -> bashing with a rod is more of an instant kill than a taser shot to basing)
- can chainstun for longer than tasers thanks to more ammo and longer stuns
- effectively ignore stun reduction due to operating by stamina damage

Tasers:

- faster to stun by a few seconds assuming the target is at full health with no stun reduction

In summary, you're stupid

**Comment by Cyberboss** [comment]
Low effort shitpost

**Comment by Incomptinence** [comment]
In disablers defence the wounded should fuck off and heal up instead of expecting to be in prime fighting shape.

**Comment by Fox-McCloud** [comment]
Just re-introduce the delay between taser shots.

Also consider reducing stamina damage's slow; it's absolute cancer.

**Comment by PKPenguin321** [comment]
Just leave tasers alone, christ

**Comment by ACCount12** [comment]
[Meme PR]

**Comment by Repukan** [comment]
*Unzips harmbaton*

**Comment by Jordie0608** [comment]
You know a PR is good when the changelog mentions a value being decreased to a higher number.

**Comment by Armhulen** [comment]
Disabler beams now take slightly less energy, to encourage security officers to realize that hybrid tasers also shoot disablers.

BWAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHA

**Comment by kevinz000** [comment]
lol you don't play here fuck off mrty don't touch our balance.

**Comment by WJohn** [comment]
I hate tasers how they are now, and I hate this change. If you're gonna massively shit on tasers and make disablers even more viable, then just get rid of the taser function from those guns entirely.

This in no way fixes stun batons, either.

**Comment by pantherpusher** [comment]
What if instead of nerfing via numbers you nerfed it by making the electrode able to be blocked by thick clothing?

**Comment by Jordie0608** [comment]
I forgot to actually close this.

**Pull request closed without merging**
