### PR TITLE
LAVA_IS_SMALLER

### PR DESCRIPTION
**Pull request by Jalleo**
Same with the SPACE_IS_SMALLER but only with smaller maps

### CODE REVIEW

**Comment by ShizCalev** [comment]
I was under the impression that the extra size was so that lava pools wouldn't completely surround ones like the golem ship

**Comment by Cyberboss** [comment]
@Jalleo i think @MapDiffBot is acting up, can you confirm?

**Comment by Jalleo** [comment]
@ShizCalev they were only NOOP area and tiles

**Comment by Iamgoofball** [comment]
wait wtf we have a mapdiff bot??? holy fuck thats cool

**Comment by Jalleo** [comment]
@Cyberboss sorry I dont know how mapdiffbot works or even how it can act up.

**Comment by ShizCalev** [comment]
It probably doesn't like size changes. :p

**Comment by Kromgar** [comment]
@ShizCalev I've seen golem spawns still get fucked by being surrounded by lava

**Comment by ShizCalev** [comment]
@Kromgar probably because it had no land border on the map kek

**Comment by Jalleo** [comment]
To be honest that is not going to change by adding a bunch of tiles around the spawn itself because you will always get a edge case where it gets blocked off due to it happening.

**Comment by Jalleo** [comment]
Anyhow I can in a later PR add multiple exits if you want me to. Kinda no time at the moment and it is easy to do.

**Pull request merged**
