### PR TITLE
replaces hivelord stands with new ones

### PR DESCRIPTION
**Pull request by Fikou**
## About The Pull Request

now miner stands are power miners instead of hivelords, you get them with a dusty shard obtainable like always from tendril chests, their fluff string names are based on minerals of various kinds
video here: https://streamable.com/5ql4g
also fixes a bug that i detailed in changelog

## Why It's Good For The Game

i rushed out hivelords without really thinking about how good they would be with their sprites
this should be nicer and more fit in the theme

## Changelog
:cl:
add: hivelord stands are replaced with new mining ones, they spin!
fix: fixed being able to change your stand name/color on every reconnect
imagedel: removed most of the old holopara/guardian spirit sprites except for 2 example ones since they aren't used anymore
/:cl:

### CODE REVIEW

**Comment by Fikou** [comment]
what happened to my friend icondiffbot

**Comment by Shadowflame909** [comment]
Time to kill funny valentine with my infinite rotation

**Comment by ATH1909** [comment]
What about the sprites for wizard stands and the like?

**Comment by Fikou** [comment]
> What about the sprites for wizard stands and the like?

what about them

**Comment by Michael-Ashfield** [comment]
I'm a bit confused, does this change the holoparasite sprite for traitors and the normal guardian sprite for wizard/miners lucky deck? If so, why is it necessary? The distinction between guardian and holoparasite is important to not get murdered by every sec officer on the station when you just want to heal your miner summoner.

**Comment by Michael-Ashfield** [comment]
I'm a bit confused, does this change the holoparasite sprite for traitors and the normal guardian sprite for wizard/miners lucky deck? If so, why is it necessary? The distinction between guardian and holoparasite is important to not get murdered by every sec officer on the station when you just want to heal your miner summoner.

**Comment by Fikou** [comment]
> I'm a bit confused, does this change the holoparasite sprite for traitors and the normal guardian sprite for wizard/miners lucky deck? If so, why is it necessary? The distinction between guardian and holoparasite is important to not get murdered by every sec officer on the station when you just want to heal your miner summoner.

the title and the description says it all, hivelord stands are replaced with new ones, doesnt say anything about wizard stands or traitor stands

**Comment by spookydonut** [comment]
@Fikou merge conflict

**Pull request merged**
