### PR TITLE
Print custom amount of stuff for protolathe

### PR DESCRIPTION
**Pull request by SyncIt21**
**About the pull request**
Just like the autolathe print a custom amount of stuff from the protolathe[and all its subtypes like circuit printer etc]

https://user-images.githubusercontent.com/110812394/205935622-f1bf4fa8-85b2-4167-a16a-61e88f944039.mp4

**Why its good for the game**
If i want to print say 7 matter bins i want to just type 7 and not print 5 then click 2 more times. This or any other amount between 1 & 50 that aren't multiples of 5 or 10

**ChangeLog**
:cl:
add: Custom print button for protolathe just like the autolathe
/:cl:

### CODE REVIEW

**Comment by Serxule** [comment]
time to drain the entire ore silo via printing a mass amount of junk

**Comment by SyncIt21** [comment]
> time to drain the entire ore silo via printing a mass amount of junk

Sure if you find that fun I guess.  Or maybe just click 10x and do the same thing.

**Comment by Troxonater** [comment]
Why would you use bandicam when OBS is free and open source.

**Comment by SyncIt21** [comment]
> Why would you use bandicam when OBS is free and open source.

Old habits :D

**Comment by antropod** [comment]
now stress test it by printing 9999999 of an item that costs virtually nothing, watch how long it would take

**Comment by SyncIt21** [comment]
> now stress test it by printing 9999999 of an item that costs virtually nothing, watch how long it would take

Probably should write a unit test for that 
```
while(silo.has_materials())
 var/junk_printed = print_junk()
 if(junk_printed > 9999999)
   to_chat(usr,"Congrats you officially dont have a life and should probably do something else")
 if(admin.is_gonna_ban_you === TRUE)
  continue
```

**Comment by Overuseddart** [comment]
> time to drain the entire ore silo via printing a mass amount of junk

You can already just take out all the mats and throw them into the recycler

**Comment by CocaColaTastesGood** [comment]
This is just a UI change, as far as I know you could already "enter" custom amounts. It just wasn't shown to the client.

**Comment by SyncIt21** [comment]
> This is just a UI change, as far as I know you could already "enter" custom amounts. It just wasn't shown to the client.

True . The back end already had this feature but the UI never caught on

**Comment by SyncIt21** [comment]
Anyone maintainer wants to review & merge this? I have no pending changes to make

**Pull request merged**
