### PR TITLE
Makes armsky/pingsky not pAI controllable

### LINKED ISSUE #65406: pAI can currently be placed into a securitron (wiki says disabled for balance reasons)
Reporting client version: 514.1581

## Round ID:
[179810](https://scrubby.melonmesa.com/round/179810)

## Reproduction:

Straight forward but for an example see round above

Jazzle inserts the personal AI device into Sergeant-At-Armsky!

### PR DESCRIPTION
**Pull request by JohnFulpWillard**
## About The Pull Request

I assumed they would inherit beepsky removing the flag because I’m stupid.

## Why It's Good For The Game

Closes https://github.com/tgstation/tgstation/issues/65406

## Changelog

:cl:
fix: Armsky and Pingsky aren't pAI controllable anymore.
/:cl:

### CODE REVIEW

**Comment by JohnFulpWillard** [comment]
god damn it wrong branch

**Comment by TheSilverNuke** [comment]
Boo! Boo! pAI POWER!!

**Comment by 1glitchycent** [comment]
THIS PR WAS MADE BY THE **"BALANCE"** METAGANG, THEY SEEK TO REMOVE FUN IN ALL OF IT'S FORMS, AND REPLACE IT WITH TOTALLY SYMETRIC TEAM DEATH MATCH GAMEPLAY!

**Comment by JohnFulpWillard** [comment]
> THIS PR WAS MADE BY THE **"BALANCE"** METAGANG, THEY SEEK TO REMOVE FUN IN ALL OF IT'S FORMS, AND REPLACE IT WITH TOTALLY SYMETRIC TEAM DEATH MATCH GAMEPLAY!

🤨

**Pull request merged**
