### PR TITLE
Buffs robotic limb healing

### PR DESCRIPTION
**Pull request by XDTM**
:cl: XDTM
tweak: Repairing someone else's robotic limb is instant. Repairing your own robotic limbs will still take time.
tweak: Repairing limbs with cable or welding will now heal more.
/:cl:

Trying to heal wounds is usually extremely hard when you get augmented; only two items in the game can fix your wounds, and they take five seconds to heal, while _also_ having to target the correct limb. Add in the fact that doctors often won't notice that your limbs are robotic and that the standard bicaridine won't work, and getting your limbs augmented becomes a downgrade over normal ones.

Making others healing you instant is in line with bruise/burn packs, which share the same behaviour; overall it encourages cooperation with others.
I felt that number buff was necessary due to the huge disparity in organic and robotic healing speed. With this it'll still be a downgrade over organic, which is fair enough since robotic limbs have other benefits. To compare, cyborgs heal 30 per use.

### CODE REVIEW

**Comment by optimumtact** [comment]
These are meant to be less effective than your usual arms, as a punishment for losing your arm in the first place.

:-1: from me

**Comment by XDTM** [comment]
They used to be upgrades until dismemberment came along, and considering the material and time investment they still should be.

**Comment by GunHog** [comment]
What XTDM said. Robotics limbs predate dismemberment, and were an upgrade to normal limbs with the tradeoffs including needing tedius surgery to install, and healing limited to welding tool/wires. They are by no means a punishment for losing limbs.

**Comment by optimumtact** [comment]
How are they an upgrade

**Comment by XDTM** [comment]
10% armor, spaceproofing if fully augged and i think that welder/cable healing was initially considered easier than meds. Also how would you explain chest/head augs if they were only replacements.

**Comment by optimumtact** [comment]
Then they defintely don't need a buff

**Comment by PKPenguin321** [comment]
No, this is fine. Maybe make it only heal 10 per use, though, not 15.

**Comment by XDTM** [comment]
Bruise and burn packs heal 40 a hit, and are pretty much the worst way to heal yourself. Between the delay, the single-limb targeting and nobody knowing how to uncrit you, i feel it could even go higher than 15.

**Comment by PKPenguin321** [comment]
The difference is that those come in packs of six while wire comes in 30 and welders can have absurd amounts of fuel.

**Comment by XDTM** [comment]
The other points still stand, especially the ones about doctors not knowing how to revive you. Sometimes when i play with full augs i'll fall in crit due to some random EMP, then someone drags me to a sleeper, injects bicaridine, and forgets about me.

**Comment by optimumtact** [comment]
@tgstation/commit-access if nobody else decides what to do with this in two days I'm going to close it because personally I don't think it's a good change

**Comment by Jordie0608** [comment]
This sounds fine; The healing amount is just ~balance~ and a 5 point difference isn't that significant to quibble about here.
Doctors not knowing how to heal augments is aside to this, if they're dumb they're dumb.

**Pull request merged**
