### PR TITLE
Kitchen resprites

### PR DESCRIPTION
**Pull request by MelokG000**
## About The Pull Request
Resprites grinder, processor and deepfryer.
## Why It's Good For The Game
~My friend said old sprites are dogshit and he did that~
New sprites look more in TG style.

image

image

image

## Changelog
:cl: MelokGleb and KREKS
image: Changed sprites of some kitchen machines (xenobio variants too)
/:cl:

### CODE REVIEW

**Comment by MrMelbert** [comment]
It's hard to tell with IDB but it looks like you added an in-sprite shake to the processors active icon state? If so you should remove that

**Comment by Loafin34** [comment]
deep fryer doesn't really look like a deep fryer.

**Comment by mc-oofert** [comment]
i cant tell why but these look really flat

**Comment by xKREKSx** [comment]
For everyone, here's what the old sprites looked like
image
image
image

**Comment by mc-oofert** [comment]
> For everyone, here's what the old sprites looked like -image-

the fryer is outright better and the grinder and processor were ok

**Review by Wallemations — CHANGES_REQUESTED** [review]
The frier looks like a box with dials and tiny holes rather than a proper frier, though I'm not so sure how you'd fix that one without just redoing most of it.
As for the other two, I actually like their designs and palettes but the perspective is left the same as before which leaves it feeling flat and strange.
This can be fixed by just elongating the "top" part of the sprite upwards and shifting the whole thing down a little.

**Comment by xKREKSx** [comment]
> The frier looks like a box with dials and tiny holes rather than a proper frier, though I'm not so sure how you'd fix that one without just redoing most of it. As for the other two, I actually like their designs and palettes but the perspective is left the same as before which leaves it feeling flat and strange. This can be fixed by just elongating the "top" part of the sprite upwards and shifting the whole thing down a little.

image
something like this?

**Comment by xKREKSx** [comment]
> The frier looks like a box with dials and tiny holes rather than a proper frier, though I'm not so sure how you'd fix that one without just redoing most of it. As for the other two, I actually like their designs and palettes but the perspective is left the same as before which leaves it feeling flat and strange. This can be fixed by just elongating the "top" part of the sprite upwards and shifting the whole thing down a little.

now they look something like this.
image
image

**Comment by DaydreamIQ** [comment]
Would this change the monkey recycler / Slime processor sprites? Since they're literally the same as their kitchen counterparts

**Comment by Wallemations** [comment]
> Would this change the monkey recycler / Slime processor sprites? Since they're literally the same as their kitchen counterparts

Yes

**Comment by Wallemations** [comment]
> 
> image
> 
> something like this?

More

Think about the perspective a lot of other machines are in, like the griddle for example.

Not saying to make it exactly as wide as the griddle but definitely look at it as an example of perspective

**Comment by Dorsisdwarf** [comment]
My issue w/ the deepfryer is it goes from looking like a big industrial one to a dinky tabletop one, its the toaster dials that do it.

The sprite itself looks much nicer though.

**Comment by ZephyrTFA** [comment]
I like the grinder and processor, but the fryer needs a redo

**Comment by EEASAS** [comment]
muh soul

jokes aside, the processor and grinder looks fat, you should do them in the perspective of the fryer

**Pull request closed without merging**
