### PR TITLE
Updates the Reagent Name unit test to also ensure searching by reagent name returns the correct reagent

### PR DESCRIPTION
**Pull request by pizie11**
## About The Pull Request

This PR updates the reagent names unit test to also test if the reagent returned by the proc get_chem_id() is the correct one. This proc is used in the reaction search window as well as some plumbing machines to find a reagent from an inputted name.

Example of the proc returning incorrectly:
image

When running this unit test, it fails for only one name, so I have changed the name of that reagent.

This unit test takes an extra 1.6s to run which I hope is acceptable.

## Why It's Good For The Game

When you search for a reagent with it's exact name you should get that reagent and nothing else.  The changed reagent name will fix this and the unit test will help ensure that.

## Changelog

:cl:
fix: Changed the name of the fake beer dispensed by E-magged service cyborgs
/:cl:

### CODE REVIEW

**Comment by Mothblocks** [comment]
> This unit test takes an extra 1.6s to run which I hope is acceptable.

At work my CI times are 2-3+ hours I could not care less about a few seconds

**Review by Mothblocks — APPROVED** [review]
New name kinda cringe but oh well

**Comment by pizie11** [comment]
if someone can come up with a better name I can change it again, this was just the second idea in my head after just naming it "Fake Beer"

**Comment by JohnFulpWillard** [comment]
Bear

**Pull request merged**
