### PR TITLE
Puts the icon state randomization back on non-parallaxed space.

### PR DESCRIPTION
**Pull request by Iamgoofball**
Reverts tgstation/tgstation#71746

I fully agree with oranges, this does look like absolute dog vomit. We do not need to ruin the visuals of our video game for not even a full second of initialization time.

We have a variety of other, far more expensive things to cut down on before we need to make the game look like shit for anyone who has an older computer that can't handle parallax very well. I objected to this in discord when Mothblocks first proposed it and I can't believe we literally downgraded to an oldstation-tier space sprite.

### CODE REVIEW

**Comment by Kapu1178** [comment]
Best alternative:

in `world/New()`, grab the config value for `PRODUCTION SERVER` and store it in a global variable. Then, you can cut all `config.Get()` calls in lighting and space/New down to an `if(isnull())`.

This is not very slow and keeps the feature entirely.

All sane development cycles seperate prod vs dev. This is not a high ask of TGstation developers.

**Comment by Mothblocks** [comment]
You can replace the sprite but this was okayed with by the sprite team and okayed with by me, Lemon, and implicitly MSO. 

We are explicitly not going to separate dev from prod environments where possible for the purposes of the optimizations. Under 30 seconds, NOT CONFIG'd.

**Comment by Kapu1178** [comment]
> You can replace the sprite but this was okayed with by the sprite team and okayed with by me, Lemon, and implicitly MSO.
> 
> We are explicitly not going to separate dev from prod environments where possible for the purposes of the optimizations. Under 30 seconds, NOT CONFIG'd.

Then remove starlight.

**Comment by Mothblocks** [comment]
End goal is to get starlight to be enabled in dev config

**Comment by Iamgoofball** [comment]
@optimumtact @ninjanomnom requesting a headcoder vote on this change, the PR I am reverting here drastically compromises the visual quality of space when parallax is disabled to save not even a full second of initialization time, space looks like dogshit and this change isn't worth it

**Comment by Mothblocks** [comment]
Then fry them

**Comment by LemonInTheDark** [comment]
> End goal is to get starlight to be enabled in dev config

I'd like to do this yeah, I've always wanted to clean up starlight so the station looked better and such.

**Comment by Mothblocks** [comment]
"Not even a full second" is absurd especially when this is 0.707s. We have saved literally more than a minute of init time from doing stuff like this. If you're not willing to take gains that are "not even a full second", then you will never get any gains except for the random fluke cases like space init

**Comment by LemonInTheDark** [comment]
> @optimumtact @ninjanomnom requesting a headcoder vote on this change, the PR I am reverting here drastically compromises the visual quality of space when parallax is disabled to save not even a full second of initialization time, space looks like dogshit without this revert and this change isn't worth the frankly pitifully low savings in initialize when we have significantly bigger fish to fry on that front

goof why are you jumping to a revert instead of just talking to moth and oranges about this. you're doing the most hostile thing possible in this situation

**Comment by Iamgoofball** [comment]
@LemonInTheDark It's mothblocks, they don't have conversations, they smile and nod and go "ok" then do what they were going to do anyways. It's a waste of time to bother making a case to mothblocks about why this is a bad idea because they're never going to listen and never have listened every time I've tried to make a case to them in the past.

**Comment by Mothblocks** [comment]
image

**Comment by Iamgoofball** [comment]
i don't think he had downgrading the space visuals in mind when he said that, given this comment:
chrome_1wgACuuUPx

**Comment by Ghommie** [comment]
You could still change the icon to a black square if you want, no problem with it.

**Comment by winterboekje** [comment]
please merge i want old space back

**Comment by Mothblocks** [comment]
no

**Comment by optimumtact** [comment]
don't look conversations becuase people are posting, just unsubcribe

**Comment by Mothblocks** [comment]
i would react with :+1: but it wont let me

**Pull request closed without merging**
