### PR TITLE
Adds Title3

### PR DESCRIPTION
**Pull request by ghost**
https://dl.dropboxusercontent.com/s/vakxe5ryg857dox/title3.ogg?dl=0

Remix of an old game's theme by cuboos.

### CODE REVIEW

**Comment by WJohn** [comment]
:+1:

**Comment by pudl** [comment]
its still just as bad as its always been

**Comment by S0ldi3rKr4s0** [comment]
it's still shit. :+1:

**Comment by d3athrow** [comment]
Sounds like crap :+1:

**Comment by Jalleo** [comment]
I dont like it either really get some people from the server to listen to see if they like it.

**Comment by tkdrg** [comment]
Some admin played it on the server at some point and people enjoyed it. I can do it again I guess.

**Comment by dannno** [comment]
it's cool but it's very unfitting and grating and abrasive and it's not that cool actually

**Comment by paprka** [comment]
do you have adhd dannos

**Pull request closed without merging**
