### PR TITLE
Exotic Corgis 2 Electric Boogaloo 

### PR DESCRIPTION
**Pull request by fluffe9911**
🆑 Fluffe9911 (Credit to KMC for coding help and cheese20 for the idea!)
add: Exotic Corgi Crate to cargo
add: New type of corgi called Exotic Corgi that has a completely random color
/🆑
Based off this pr https://github.com/tgstation/tgstation/pull/38276
I really liked cheeses idea but since the original pr got reverted decided to redo it so now the exotic corgi is its own type of dog so hopefully it should look slightly less like it ate a crayon also no talking corgi so the maintainers don't get angry hope I did this right!

### CODE REVIEW

**Comment by Jared-Fogle** [comment]
This will be the 2nd PR that just takes something @chesse20 makes, alters it a little, and will inevitably get merged while chesse20 stays unfairly git banned.

**Comment by cyclowns** [comment]
i'm not sure if i'd call chesse20's gitban unfair
remember #38310?

**Comment by Jared-Fogle** [comment]
It's a good PR

**Comment by epochayur** [comment]
chesse had that ban coming, he'd pull something that kinda made sense until you read the line that includes piss fetishism

**Comment by Jared-Fogle** [comment]
unatomic

**Comment by fluffe9911** [comment]
oh shet didnt realise that would add this to this one moment

**Comment by Jared-Fogle** [comment]
Make different branches for all your features when you work on them.

git branch new-branch-name

Do all your work on there, git add, git commit, the usual. Then git push origin new-branch-name.

**Comment by fluffe9911** [comment]
yeah still new to github sorry

**Comment by Jared-Fogle** [comment]
Easier than reverting every commit individually:

`git reset 04690d9`
`git push origin master`

**Comment by praisenarsie** [comment]
This adds nothing of value to the gameplay and it barely acts as fluff. The mob does not act any differently from other corgis, it's literally just an rgb change. I know it's harmless but it just feels out of place and stupid. I'm giving my honest opinion.

**Comment by fluffe9911** [comment]
I respect your opinion and agree that yeah theirs not much point in it but as you said its harmless and I just like the idea of having multi color corgis for some reason lol

**Comment by optimumtact** [comment]
I hope chesse shouts me out in his next roblox mod

**Pull request merged**
