### PR TITLE
Asteroid Station - Starlight

### PR DESCRIPTION
**Pull request by lzimann**
Just adding the new starlight system.

### CODE REVIEW

**Comment by optimumtact** [comment]
Ass was fat :+1:

**Comment by lzimann** [comment]
If I missed any spot let me know. But I'm 99% sure that it was everything.

**Comment by KorPhaeron** [comment]
@lzimann 

As long as you're doing a map PR for asteroid, could you please add two of the new xenobio consoles to the lab?

**Comment by lzimann** [comment]
@KorPhaeron I'll have to make a new PR I think, I did the branch/PR before the xenobio console was merged. I kinda suck with git, so I don't know if I can just update the branch and make a PR here or I would have to make a new brach to do it.

**Comment by Jordie0608** [comment]
@lzimann You can just update the existing branch and make a new PR

**Pull request merged**
