### PR TITLE
1 AM Leather Jackets

### PR DESCRIPTION
**Pull request by axietheaxolotl**
## About The Pull Request

image

image

Brand new leather jackets.

The old leather overcoat was deleted cause it was peepee poopoo and has been replaced by the biker leather jacket, shown second above. If you still really want the leather overcoat, play HoS.

## Why It's Good For The Game

these look good, and the old leather overcoat was poopoo, this biker jacket though? Not poopoo, very epic.

## Changelog

:cl: axietheaxolotl
imageadd: brand new sprites for the curator explorer jacket, and regular leather jacket.
del: Non-HoS leather overcoat.
add: Biker leather jacket.
/:cl:

### CODE REVIEW

**Review by Imaginos16 — APPROVED** [review]
Immensely based

**Comment by Wallemations** [comment]
Not a big fan of getting rid of the leather overcoat, how am I supposed to cosplay the living embodiment of a 14 year old's edgy fanfiction as a traitor now?

The sprites are good though

**Comment by VladinXXV** [comment]
you remembered
image

**Comment by rasepretep** [comment]
If it's just a more or less cosmetic item, I'd be more in favor of adding a new one, instead of replacing an old one some people might enjoy, since both can coexist just fine.

**Comment by Sealed101** [comment]
Not Important cosplayers lie in shambles after this PR

**Comment by Shadowflame909** [comment]
Is this one craftable like the leather overcoat was from a biogenerator

Does it have slight space protection like the leather overcoat???

Powergamers and Perma prison break attemptors must know!

**Review by Mothblocks — APPROVED** [review]

**Comment by Mothblocks** [comment]
@axietheaxolotl

**Pull request merged**
