### PR TITLE
The DNA vault now modifies your physiology, not your species

### PR DESCRIPTION
**Pull request by ATH1909**
## About The Pull Request

See the title. In layman's terms, you'll keep your vault abilities even after changing species- before, some of them would go away when you changed species, but you'd still be locked out of using the DNA vault again (with that body) to get replacements for them.

In addition, the DNA vault now uses multiplication in more places instead of just directly setting values. Previously, if you were, say, a glass golem and chose the fireproofing option, you'd actually become MORE vulnerable to burn damage (because the dna vault would set your species's burnmod to 0.5).

Also, you could extract someone's lungs after they chose the toxin adaptation option and stick them in a new body, and those lungs would still have their ability to ignore plasma in the air.

... And, uh, I _kind of sort of_ realized that some of the vault options are just really, really sad and underwhelming (especially considering the amount of effort required to construct and collect the required samples for a DNA vault), so I _may_ have gotten a bit carried away and FIXED this ISSUE by adding a few more abilities to most of the options. This most certainly is NOT a balance change PR in No Nerf November, no sir.

## Why It's Good For The Game

Feex good.

Also, a DNA vault option should not be able to be replicated with a single virus symptom (seriously, what the fuck?), nor should it actively hinder you by making you immune to the good virus that the virologist made or by making you unable to be directly healed by sutures, ointment, etc.

## Changelog
:cl: ATHATH
fix: DNA vault options should play more nicely with resistances that you already have from your species now.
fix: Some of the DNA vault options should no longer be incredibly underwhelming, or even be (much of) an active hinderance to you.
/:cl:

### CODE REVIEW

**Comment by ATH1909** [comment]
I'm considering giving the ability to ignore damage slowdown to the vault speed option, but I think that that'd be a bit TOO good, no?

**Comment by ArcaneDefence** [comment]
image

**Comment by actioninja** [comment]
discord comment was a joke not an instruction manual

**Comment by ATH1909** [comment]
damnit.

**Pull request closed without merging**
