### PR TITLE
Removes stronger alcohol penalty

### PR DESCRIPTION
**Pull request by BonChoi**
:cl: BonChoi
del: bugged liver failure code that would cause extreme damage from weak alcohols
/:cl:
One bottle of beer shouldn't give you permanent liver damage.

### CODE REVIEW

**Comment by Tlaltecuhtli** [comment]
i ded

**Comment by praisenarsie** [comment]
@DaedalusGame 

also make the changelog actually reflect the changes you are making

**Comment by Spaceinaba** [comment]
so that's why my liver shat itself after I drank a bottle of whiskey

**Comment by DaedalusGame** [comment]
this reverts the entire pr, which also had fixes.

**Comment by yorii** [comment]
remove fix label, no GBP deserved for literal reverts.

**Comment by davethwave** [comment]
Why not just lower the amount of liver damage alcohol does or make the bartender start with a bottle of anti-alcohol or whatever it was called?

**Review by Cyberboss — CHANGES_REQUESTED** [review]
This isn't how you changelog

**Pull request closed without merging**
