### PR TITLE
Lizard mobs can now be picked up.

### PR DESCRIPTION
**Pull request by SerenHighwater**
## About The Pull Request
Wags-His-Tail and lizard mobs are now able to be picked up and stored.

## Why It's Good For The Game
Wags loves being picked up, now you can!

## Changelog

🆑 
fix: Wags-His-Tail (and general lizard mobs) can now be picked up like any other pet.
/🆑

### CODE REVIEW

**Comment by Son-of-Space** [comment]
Good job, excellent first PR. Wags does indeed love to be picked up.

**Comment by LemonInTheDark** [comment]
Use /:cl: at the end of your changelog, or it will break when we try and process it

**Comment by Slurge00** [comment]
> Use /🆑 at the end of your changelog, or it will break when we try and process it

fixed now?

**Review by LemonInTheDark — APPROVED** [review]

**Comment by Slurge00** [comment]
> Use /🆑 at the end of your changelog, or it will break when we try and process it
> 
> ~Also it's not a fix~

i assumed it was a fix because every other pet and friendly mob can be picked up, so.

**Comment by TheBonded** [comment]
cant pick up poly or paperwork, and I dont think you can pick up mcgriff(can you?), only some friendly simplemobs can be picked up

**Comment by JohnFulpWillard** [comment]
> cant pick up poly or paperwork, and I dont think you can pick up mcgriff(can you?), only some friendly simplemobs can be picked up

Paperwork and McGriff can be picked up

**Pull request merged**
