### PR TITLE
Changes lizard heat and cold damage

### PR DESCRIPTION
**Pull request by anconfuzedrock**
:cl: rock
tweak: lizards are hurt slightly more by cold but less by heat. this does not mean they are more resistant to being lasered, fortunately.
/:cl:
shitty testing showed the dude with the advantage lasted like 2 seconds longer under temperatures so this is pretty minor tbh fam 
examples of how this effects stuff(tested before the lizard buff from resistance of 0.75 to 0.67
THINGS THIS EFFECTS MAJORLY:
lizards being set on fire (roughly 4 seconds)
being frozen to death by a cold shower (like 10 seconds)
being frozen by a temperature gun (does 6.75 damage on one hit instead of 4.5)
THINGS THIS EFFECTS MINORLY
being attacked by a basilisk/watcher (I didn't even have to test this with humans, on a straight hallway I was able to run out of its range and escape with 38.5 burn damage despite it shooting me at least a half dozen times)
unloading a tempgun as fast as possible on somebody on cold (does roughly 30 damage instead of 20)
being burned by a tempgun (does 2 damage on hit to humans, 1.5 to lizards)
being unloaded with a burning tempgun (does 15 dmg instead of 18)
a few missed spurts with a flamethrower (like 1 second)
being spaced with no internals (less than a second)
boiling to death in a hot shower (almost exactly 1 second)

### CODE REVIEW

**Comment by Qbopper** [comment]
it's flavorful so i want it merged

**Comment by optimumtact** [comment]
REEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEvv

**Comment by anconfuzedrock** [comment]
ok

**Comment by anconfuzedrock** [comment]
I mean it was even hard to TEST heat damage with them because of how shit heat damage is I think cold is gonna pop up more lad but its all le ironic so its ok

**Comment by Cyberboss** [comment]
>Fire

**Comment by ExcessiveUseOfCobblestone** [comment]
At least now there's an actual reason to be a lizard since it offers different mechanics instead of being purely fetish-bait or something to trigger goof with.

**Comment by anconfuzedrock** [comment]
yea thats the point of this

**Comment by ExcessiveUseOfCobblestone** [comment]
also update the wiki to reflect this if it gets merged :)

**Comment by Incoming5643** [comment]
Considering I'm pretty sure heatmod reduces burn damage from lasers this is actually a huge buff. I strongly caution against this, as "cosmetically different with optional downgrades if you hate yourself" to be the maxim of lizards

**Comment by Sligneris** [comment]
Does this make temperature gun as effective on lizards as lasers are on xenos?

**Comment by bgobandit** [comment]
does this mean is-a-lizard is coming back

**Comment by swindly** [comment]
heatmod and coldmod are only used in calculating damage from heat and cold.

**Comment by optimumtact** [comment]
In case anyone is confused, the lasers deal direct burn damage, which is a seperate system from hot/cold temperature damage.

**Comment by XDTM** [comment]
There's a separate burnmod for burn damage yeah

**Comment by Militaires** [comment]
lizards should not be mechanically different unless you're that much of a snowflake where u need digi legs and so the game rightfully punishes you

**Comment by WJohn** [comment]
shouldn't the game rightfully punish you for being so much of a snowflake as to go lizard _at all?_

**Comment by anconfuzedrock** [comment]
Holy shit wjohn why you speakin sense im tryna little by little make lizards more like plasmamen in that in the occasional situation it might just save your ass anyway "heat and cold thresholds" is not too clear either because it still takes the same amount to feel it they just feel it harder

**Comment by XDTM** [comment]
Now spaced lizards die a lot faster what's not to like

**Comment by FantasticFwoosh** [comment]
What about ashwalkers and/or the relation to lavaland?

Might this mean you could make lavaland sauna hot by having lava radiate a threshold of heat but the natural ghost roles there and some lizards can go out without protection? Might be the opposite with a snow themed temprature

> Put some localised air coolers around the prisoner camp or supply ice drinks to stop prisoners passing out and dying. Literally space Australia

Lavaland is actually temperate atmos wise, and large explosions causes a vaccum that's cold enough to hurt normal players, even without this change.

**Comment by Hatfish** [comment]
This is going to make fighting watchers even worse than it already is
Why not make the cold threshold the same as the heat threshold?

**Comment by anconfuzedrock** [comment]
Are you fucking stupid it is balanced it makes you live longer when your stupid non watcher dodging ass slips into lava might as well give plasmamen noslips so wearing galoshes isnt worth than it already is

**Comment by YotaXP** [comment]
I don't see how this is a "buff".  I tend to see cold damage more often than heat damage anyway.  And +50% damage to one with -25% damage to the other still means more damage overall.  It would have to be +50% and -33% to be even.

**Comment by anconfuzedrock** [comment]
Well thats not happenin neither shakin like a seizure hold up let me spark this take a breather breathe that reefer in my lungs I got grapes what you watchin son
Actually i might change it to .67 later but its not a buff to anythin lad

**Comment by Hatfish** [comment]
no, really though
why not bring the cold mod more in line with the heat mod, or vice versa?

**Comment by Dorsisdwarf** [comment]
Because fuck lizards

**Comment by Incoming5643** [comment]
Stating again this is really goes against what lizard people are supposed to be.

Also the up thumbs are a bit deceptive, a lot of unfamiliar names in there.

**Comment by anconfuzedrock** [comment]
What do you think I gathered my secret mumble to thimbs this up

**Comment by anconfuzedrock** [comment]
the effect if the lizard is only set on fire seems to be fairly noticeable, allowing the lizard to survive like 4 seconds longer, so I hesitated with the buff

**Comment by bgobandit** [comment]
BUT ARE YOU BRINGING BACK IS

**Comment by anconfuzedrock** [comment]
This is the first step

**Comment by Doppeltongue** [comment]
How does this affect virology? Right now, you can make a virus that enables spacewalking by healing you for exactly 3 burn and 3 brute per tick, which is the amount of damage dealt by space. Would this change mean that lizards can no longer do this compared to humans? That seems like bigger change than intended.

**Comment by anconfuzedrock** [comment]
Chrisr how many hours of trying to find a major balance issue did it take you to find that? Boo fucking hoo a lizard needs to drink some coffee or cryoxadone before abusing a heal virus to spacewalk they cant be hulk either go complain about that

**Comment by Doppeltongue** [comment]
Eh? It took me 5 seconds since I make that virus regularly. No need to overreact. Fair point on the minor effect, since if the damage difference only amounts to 1 second to die without any equipment, the damage through the virus probably won't amount to much. Quite honestly, as long as speed isn't involved (due to the way speed modifiers work in this game), this is more of a neat flavor change than anything else, since stuns an instant deaths are the biggest killers.

Not big enough of a change to cause powergaming, go ahead.

**Comment by anconfuzedrock** [comment]
woah shit I can't believe you didn't snap back at me instant respect thanks

**Pull request merged**
