### PR TITLE
Mechs are added to the orbit list

### LINKED ISSUE #10586: Mechs cannot be followed unless their occupant is known
This is a feature request, but a fairly good one in my opinion, since mechs are usually the most fun for ghosts to watch. Yet, it's hard to know in advance, or find out who the pilot of a certain mech is.

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
Fixes #10586

### CODE REVIEW

**Comment by MrStonedOne** [comment]
technically this was fixed by #13686

=P

**Comment by KorPhaeron** [comment]
@MrStonedOne 

Huh this probably isn't needed then.

I guess if you lost track of a mech and want to jump to it?

**Comment by LatD** [comment]
I think the mechs are on the orbit list too now

**Comment by AnturK** [comment]
I'm pretty sure i added them to poi list

**Comment by Zilenan91** [comment]
Mechs are on the orbit list on the bottom

**Pull request closed without merging**
