### PR TITLE
Olives! + Custom sushi/Pierogi changes

### PR DESCRIPTION
**Pull request by MidoriWroth**
## About The Pull Request

This is a continuation of #66946 since I have enough points to finally do so.

This PR will:

- Expand upon my previous sushi PR, allowing people to use an ingredient on a sushi sheet to start creating custom sushi.
- Add olives! A new type of fruit that can be grown in hydroponics. When ground, it becomes olive paste which when mixed with water in a 4-1 reaction turns into 2 units of quality oil.
- Make pierogis require a dough slice to craft instead of a bun.
- Make quality oil cost 50 credits to order instead of 120

## Why It's Good For The Game

Since my sushi PR merged, many people have asked me to add custom sushi, so here it is. This will allow chefs to make more interesting menus with added customization.

Quality oil is an extremely expensive commodity (120 credits for one 50 unit bottle, 240 if you expedite it!!!) and can only be acquired from cargo. I feel because of this, many chefs do not make lizard or mothic foods because simply acquiring the ingredients to do so is either very time consuming, expensive, or both. This will encourage people to make those foods more often since one of the key ingredients in many lizard or mothic dishes can be made by them, too. Olives themselves can be eaten as a snack and open up opportunities for new foods in the future, and it makes sense for you to make your own oil since the process is simple yet highly inefficient in real life.

This PR originally had a way to craft cornmeal as well, but that idea was adopted yesterday in #67227 which they can keep.

Lastly, it seems more reasonable for pierogis to require a dough slice instead of a burger bun. Don't think that requires more explanation.

I believe my gbp score is at -3, but I have three PRs waiting to merge currently which will boost me way above that.

## Changelog

:cl:
add: Botany can now grow olives, which can be ground into a paste and mixed with water to make quality oil.
add: You can now make custom sushi by using an ingredient on a seaweed sheet. The sushi will be named after the first ingredient you use.
balance: Pierogis now need a dough slice instead of a bun
balance: Quality oil costs 50 credits to order instead of 120
/:cl:

### CODE REVIEW

**Comment by MidoriWroth** [comment]
oh boy i love random tg errors

**Comment by Farquaar** [comment]
Mmm, pancreas sushi

**Comment by Iatots** [comment]
If olive paste exists only to make oil, why not have the olives grind directly into oil?

**Comment by MidoriWroth** [comment]
> If olive paste exists only to make oil, why not have the olives grind directly into oil?

Because this gives it a bit more realism, since the process is relatively that simple in real life where olives are mashed, mixed with water, mashed again, then the oil is filtered out. Though typically a whole bowl full of olives would only give like maybe half a cup of oil, which is why I made the reaction so inefficient.

**Comment by tf-4** [comment]
https://github.com/tgstation/tgstation/pull/67227 adds a quality oil recipe, might wanna check that

**Comment by MidoriWroth** [comment]
> #67227 adds a quality oil recipe, might wanna check that

I am aware, though as I said this is a resurfacing of an old PR I was not able to complete due to gbp issues, and the quality oil recipe in that one is... not the greatest, and doesn't make much sense.

**Comment by MidoriWroth** [comment]
oh no haha if only a maintainer was here to save me 🥺

**Comment by LemonInTheDark** [comment]
Re: Oil.

It seems like the concern is if you put it in botany it'll be too easy to access, taking away part of its status as a rare ingredient.
It feels strange to take the decision to make oil hard to get, and kinda circumvent it without cleaning up the source.

If it should be easier, you should make it easier and argue for that. I don't like keeping the hard source, but adding an easy one so the hard source is never used.
This is why cargo never has anything useful in it.

**Comment by MidoriWroth** [comment]
> Re: Oil.
> 
> It seems like the concern is if you put it in botany it'll be too easy to access, taking away part of its status as a rare ingredient. It feels strange to take the decision to make oil hard to get, and kinda circumvent it without cleaning up the source.
> 
> If it should be easier, you should make it easier and argue for that. I don't like keeping the hard source, but adding an easy one so the hard source is never used. This is why cargo never has anything useful in it.

That's a fair assessment! The thing is that oil really isn't a rare commodity. Even in a sci-fi setting like this, I'd imagine it would not be as well which is why it's silly for it to be so expensive. I think lowering the price of it would be suitable for balancing it out as well.

**Comment by LemonInTheDark** [comment]
That argument doesn't really agree with me. Reality is unimportant, especially if a decision was made with some intent behind it.
Rare ingredients blocking production of food is a choice. If it's a good one or not is kinda up to the author/maints, I think it's a fine way for things to be personally.

It's clear that it's currently a bit too rare and hard to get enough of. That said, if you want to make it tomato levels of accessible you should argue for why that's better then rare or slightly rare you know?

Sorry if I wasn't quite clear. I think rare and hard to get things have a place in the game, and if you want to make something not that you're gonna need to argue the why. Reality is kinda unimportant, we could fluff it as being true italian olives or something. It's more important to argue for why this rare thing should be made not rare

**Comment by Iatots** [comment]
if #67227 goes through, growing it will become the hard method.

**Comment by MidoriWroth** [comment]
If botany has regular and plentiful access to many normal Earth fruits and vegetables, then I don’t see why olives should not be included as well. And if olives exist, oil can be made from them with just them, water, and a bit of brute force. If the oil was still only limited to lizard food, I could see you making the argument that it’s maybe a native Tziran plant or something that only grows there which is why it’s expensive, but since it’s used to make moth food as well, that would imply that it’s somewhat universal. Besides, the process is so inefficient that processing 10 max potency olives would only give you enough oil to make about 2 garlic nizayas.

All in all, I simply want more people to be encouraged to make lizard/moth foods and not have to scrounge up all the money they can get by spending more time doing bounties than cooking for the crew. If anything, cheese should be a rare commodity, but luckily we have magical enzyme that instantly makes cheese.

**Comment by MidoriWroth** [comment]
@Twaticus

**Comment by MidoriWroth** [comment]
@MrMelbert

**Comment by MidoriWroth** [comment]
@Imaginos16 @Krysonism @Twaticus @MrMelbert @ExcessiveUseOfCobblestone Could this be looked at sometime soon please?

**Comment by LemonInTheDark** [comment]
Meant to ask you to remove the new recipe for oil, should have been more direct, sorry bout that

**Pull request merged**
