### PR TITLE
Pre-Rifle Armoury + Lethal Shotgun Ammo

### LINKED ISSUE #12450: HoS office bugged
This effects a couple of things in the HoS office - namely the light and the red alert swipe thingo, not sure if any thing else is effected, but I suspect it's just anything along that wall.

Basically, since the pr got merged that added hardsuits to the head offices (hos/rd/cmo), the redalert swipe and light in the hos office aren't conected to the hos room apc anymore, so start the round depowered.

The RD and CMO offices may have the same issue, but I haven't checked.

edit: Box station.

### PR DESCRIPTION
**Pull request by Steelpoint**
This PR returns the armoury to its pre-rifle state, before I added in the Automatic Rifles to the armoury. As well as readding any lost items such as bulletproof armour and similar.

screenshot 2015-10-14 19 32 10

You will also notice in the top right hand corner is a new locker, this locker contains three ammo boxes holding seven lethal shotgun 'buckshot' in each box.

That is all.

Edit

Fixes #12450

### CODE REVIEW

**Comment by Steelpoint** [comment]
Link to the last, closed, PR for reference: https://github.com/tgstation/-tg-station/pull/12305

**Comment by Steelpoint** [comment]
I could return the armoury to this design I pushed to the server as well.



It was on the server before hand, but I don't know which we want.

**Comment by optimumtact** [comment]
aaaaaaaah

**Comment by Steelpoint** [comment]
I kinda like my more recent design shown above simply because it makes the armoury feel more roomy instead of being very cramped.

**Comment by Bawhoppen** [comment]
Make that locker all access, and add a shutter so officers can enter the armory if the warden opens it

**Comment by Cookiesndip** [comment]
What Baw said. The lockers should be all-access, and you may as well put the APC where the scooter is and use that rwall for a shutter.

**Comment by Steelpoint** [comment]
The ammunition locker always had a access requirement, which it should be imo.

I'm literally just reverting the design to the previous one, aside from replacing the ammo in the locker with actual lethal shells.

**Comment by Bawhoppen** [comment]
It didn't. It was a grey normal locker full of shells.
Also you give them 3 shotties instead of 2, which is fine IMO, but worth pointing out.

**Comment by Bawhoppen** [comment]
Also if you're 'reverting' it, you need to readd the shutter entrance.

**Comment by Steelpoint** [comment]
There are three shotguns.

Also there never really was a shutter entrance, at least with the last design before my overhaul with rifles.

**Comment by Bawhoppen** [comment]
PRESTEELRIFLES:
![ss 2015-10-09 at 08 31 23]
(https://cloud.githubusercontent.com/assets/6510293/10423600/bc58b5a0-708d-11e5-9212-d90d3fea3dac.png)

**Comment by Jalleo** [comment]
Closet seen on the left of that image from bawhoppen is the contraband locker and it does have a access requirement.

**Comment by Bawhoppen** [comment]
yes but the ammo locker in the top right is normal locker without access

**Comment by WJohn** [comment]
I want to get off security's wild ride.

**Comment by tuypo1** [comment]
you mean I get my armory back and the lethal shells I always wanted sign me up

also I prefer the racks in a square instead of lined in a row

**Comment by Lumipharon** [comment]
>Make that locker all access, and add a shutter so officers can enter the armory if the warden opens it

If nothing else, having a locked closet in a room full of unsecured lethal weapons is pretty redundant.

**Comment by Steelpoint** [comment]
Think of it like this.

It's the only locker in the entire armoury that not only has armoury level access but can be moved around at will.

That can prove useful in moving items in a very secure, and neat looking, locker.

If we like the more squared based design I'll go for that.

**Comment by Bawhoppen** [comment]
Goddamnit steelpoint, just make it a fucking normal locker and everyones happy.

**Comment by tuypo1** [comment]
is it not possible to make secure lockers if so that should be a thing

also if you want to keep something safe send an armed escort

**Comment by Supermichael777** [comment]
rack hell in a cell. also your all retarded and this fight is retarded

**Comment by Bawhoppen** [comment]
im going to fucking earn my relevancy

**Comment by Bawhoppen** [comment]
no but in all honesty, we all just want the game to be as perfect as possible, and we can have disagreeing views on whats best, so we discuss them and try and figure out what the best solution would actually be.

**Comment by Supermichael777** [comment]
take out the racks, put everything in non locking closets, no win-door into locker room they can bloody well come to the front desk if they want to get a gun. change retarded shutters to a bolt able airlock on sec locker room access (because you can hack it open) open debate on glass or not glass. Sec storage room and public secway were good ideas they can come back

**Comment by Shapsy** [comment]
What's even wrong with racks, they allow you to see how many guns are there at a quick glance without having to worry about constantly popping open the lockers to check on them or someone snagging one gun and not being able to tell because they all cover each other up

**Comment by Bawhoppen** [comment]
@Supermichael777 thats the most retarded comment i've heard all week

**Comment by Cookiesndip** [comment]
Why can't we just revert to the original design and add lethal bullets to the closet with no lock. Why is this so difficult? Why do we have to add locks or make contested design changes? No one thought the prior armory had any problems.

**Comment by Nanotransistor** [comment]
Without the entrance shutter is fine.The warden should do his damn job and personally hand out equipment as necessary.

**Comment by Lumipharon** [comment]
The point of the shutter is when there's a big threat to the station (like nuke ops or blob), where you basically just need to unload the entire armoury.

But seriously, just merge this one way or another, the loss of bullet proof gear is gay.

**Comment by tuypo1** [comment]
NO FUCKING GUNS IN LOCKERS it makes it a pain to see whats been stolen

what cookiesndip said just use the old armory with some lethals in the ammo locker

**Comment by duncathan** [comment]
@tuypo1 if you could read you'd see that the only thing in a locker is ammunition

**Comment by Steelpoint** [comment]
Internet is ded.

This is the original armoury, even older than the one used pre rifles.

There are no guns in lockers, as you can see in the OP

**Comment by Anonus** [comment]
Yes, but where's the shutter to let officers into the armory?

**Comment by tuypo1** [comment]
I should clarify I was saying no guns in lockers to supermichael I am very much in favour of this I prefer the layout with the racks in a square but I can live with a row as well

**Comment by Steelpoint** [comment]
As soon as my internet is alive again I'll properly address any concerns and make some changes.

**Comment by Cookiesndip** [comment]
There IS copious lethal ammunition that spawns in an armory-ID locked locker. Give one reason why that shouldn't be general access, and why you have to change it from how it was before? The locker was always just vanilla..

**Comment by Steelpoint** [comment]
Because its a minor thing that has more uses than holding ammo.

I mean, its not like I'm hiding all the guns behind lockers, I'm just putting three ammo boxes behind the locker.

**Comment by tuypo1** [comment]
I think ammo should be in lockers I hate guns in lockers but ammo in lockers is fine

although im not sure what to think on locking the ammo locker

**Comment by Steelpoint** [comment]
If we ever do get the Auto Rifles back in the future.

I would make the Rifle start out with Rubber Bullets that dealt stamina damage, and keep the lethal mags in the locked locker.

**Comment by Bawhoppen** [comment]
Locked lockers a BAD. Remove.

**Comment by Steelpoint** [comment]
Updated design, also I'm not going to compromise on the locker issue. If your really disagree with it then propose a PR that removes it after this one is merged, if it is.

screenshot 2015-10-14 13 03 14

**Comment by Bawhoppen** [comment]
>after this gets merged
Cocky aren't we?
also you forgot some windows in between the warden's office

**Comment by Steelpoint** [comment]
>after its merged
>if it is

Read my posts.

**Comment by Bawhoppen** [comment]
I was going to write a ranting post about sentence structure and intended meaning, but whatever. Anyways my view still stands

**Comment by Anonus** [comment]
Uh, where's the shutter to let all the officers into the armory?
Why is that gone?

**Comment by Steelpoint** [comment]
Sometimes its there, other time's its not.

There's a shutter on the window, but I can add the shutter entrance back in.

**Comment by Bawhoppen** [comment]
You don't add it back when I ask for it, fucking BIAS

**Comment by Steelpoint** [comment]
Final change.

New side shutter entrance, also fixed a area issue and missing r-windows.

screenshot 2015-10-14 19 32 10

**Comment by Anonus** [comment]
Also, you should swap the APC and the shutter button so you don't have to open a windoor to click the button.
And the table should be reinforced, too.

**Comment by Cookiesndip** [comment]
Okay explain why the ammunition specifically has to start in a locked locker Steelpoint?

You have the evidence locker, so it's not that. Just why? You could, if you really want a moveable armory-access-only locker, just make the evidence locker moveable instead. The point is that if you take the trouble to break into the armory and no one notices, everything should be accessible, including the ammunition. Or, if the warden is absent and the AI lets you in for emergency equipment, everything should be accessible so that the officer can adequately arm up.

Why is it so hard just to revert to the base design then making a second PR to make changes to that, instead of sneaking in contested balance changes so your shitty changes will get pushed instead of closed? You always do this shit and it drives me insane, it's like you're a politician or something.

**Comment by Steelpoint** [comment]
Its a minor change for reasons I've stated above.

Again, I'm not holding hostage all the guns in the armoury behind a locked locker, its just a few extra boxes of shotgun ammo.

If I wanted to revert to the base line I would be using a far more older design, I'm simply iterating upon the design.

**Comment by Steelpoint** [comment]
Also tell me where I'm 'sneaking' in this change?

I resent that accusation.

**Comment by duncathan** [comment]
Yeah he's not sneaking anything in; the locker is mentioned right in the OP

**Comment by Nanotransistor** [comment]
Don't see anything bad about lethal ammo being locked. So far we have played all this time without even lethal ammo being readily available. If anything, the lethal ammo shouldn't even be added.

**Comment by Bawhoppen** [comment]
Locking ANYTHING in the armory should be a no go. The point is the armory itself should be the lock, and for balance reasons to not lock it.

**Comment by Nanotransistor** [comment]
Fair enough.

**Comment by Anonus** [comment]
Swap the shutter and the table/windoors, but not the button placement.
The table should also definitely be reinforced.

**Comment by Steelpoint** [comment]
I moved the table to be a r-table and swapped the shutter's and table around.

screenshot 2015-10-15 02 13 39

**Comment by tuypo1** [comment]
i know i thought tooth and nail against guns in lockers but ammo behind a lock i am happy either way im just so glad to finally get lethal shells

i suppose its not a perfect comparison because for the guns i was against it wether locked or unlocked for ammo of course they should be in lockers its just a matter of if it should be locked

**Comment by Lumipharon** [comment]
Steel whatever happened to  the sabr nerf? It's still 42 rounds per mag, and incendiary is still misspelt.

Also please merge this someone - whether you like locked lockers or not, I think we can all agree it makes very little actual difference considering the 7 weapons in the same room that can blow it open.

**Comment by Bawhoppen** [comment]
Uranium is misspelt somewhere too.

**Comment by Steelpoint** [comment]
Never got around to the SABR due to complications in the PR that did nerf it, mainly in that people complained how I should not have a nerf and bug fix in the same PR so I picked the bug fix.

**Comment by Steelpoint** [comment]
Operation pester is a go, this PR is good to merge.

@Aranclanos or @Razharas or @Cheridan or whoever.

**Comment by Dorsisdwarf** [comment]
Reddy4freddy

**Comment by Steelpoint** [comment]
The Freddy is still Ready.

**Comment by Jalleo** [comment]
Lets hope freddy dosent have to wait five nights

**Comment by Steelpoint** [comment]
Fuuuck this is what happens.

**Comment by Steelpoint** [comment]
Merge Conflicts fixed.

PR also fixes https://github.com/tgstation/-tg-station/issues/12450

**Comment by Bawhoppen** [comment]
there goes steelpoint, combining changes into one pr so he can stealth in things he wants

he probably gave the HOS a pulse rifle or something

**Comment by Steelpoint** [comment]
Oh fuck off Baw its a minor fix to something that's literally a few tiles to the right of my changes.

**Comment by Steelpoint** [comment]
It appears this PR was accidently reverted by another map change...

**Pull request merged**
