### PR TITLE
adds plumbing machine that can grind/juice items

### PR DESCRIPTION
**Pull request by Tlaltecuhtli**
:cl:
add: plumbing machine to grind/juice objects and put it on duct net
/:cl:
!! it doesnt move shit you need to add belts to feed it!!

sprite by arcanemagician

### CODE REVIEW

**Comment by Buggy123** [comment]
My savior


Now all we need is a machine that can automatically extract/inject reagents into stuff.

**Comment by lolman360** [comment]
circui- on wait

**Comment by Krysonism** [comment]
Great PR

looking forward to making a suture factory

**Comment by ArcaneMusic** [comment]
I can get you some sprites going, sure.

**Comment by cacogen** [comment]
fucking neat


good sprite too

**Comment by QFMVC** [comment]
Plumbing fermentation barrel when?

**Comment by optimumtact** [comment]
For a second I honestly though these where the sprites

**Comment by JJRcop** [comment]
Would be neat to have an animation when something is fed into it

**Pull request merged**
