### PR TITLE
Adds a not garbage PDA manifest

### PR DESCRIPTION
**Pull request by AffectedArc07**
## About The Pull Request
~~Makes the PDA crew manifest available to everyone, and also~~ makes it look a whole load cleaner, as it now categorises by department instead of just alphabetical name
image
image

## Why It's Good For The Game
The current manifest is fucking atrocious

## Changelog
:cl: AffectedArc07
add: The crew manifest on the PDA is now bearable to use.
/:cl:

cobby edit: strikethrough

### CODE REVIEW

**Comment by Tharcoonvagh** [comment]
Yum

**Comment by cacogen** [comment]
colours look out of place but otherwise is good

**Comment by RaveRadbury** [comment]
Isn't this bloat? I thought that the crew manifest required at least a little bit of access, rather than just passing one out to everybody.

**Comment by Farquaar** [comment]
@RaveRadbury Everyone technically has a crew manifest in their PDA messaging system already, but it's impractical to use. I'd say that a manifest like this helps foster cooperation between departments. 

Want to know if there's a chemist? Bam, right there. Need help for a project, but don't know who's staffing the engineering department? Bam, now you know there's a CE and three engineers. Want to know whether to call the Captain of the HoS? Bam, now you know there's no HoS.

**Comment by MrDoomBringer** [comment]
@Farquaar Why do there have to be colors?? Just get rid of the background colors and keep the black text + table lines, and it'll be perfectly in-line with any PDA style

**Comment by Teepeepee** [comment]
@Farquaar you can check roundstart who is on the manifest with the PDA by going to the messaging tab, yes, but people can turn off messaging and disappear from that list, which is useful to obscure your presence, although not perfectly since latejoiners and anyone else with access to the manifest or meta-info about it (like someone who has a head on high and doesn't spawn as it, when someone spawns as an underling and the game tells them who's their head or when there's a roundstart captain) can know you're there
I think it would be fine if this possibility went away, but maybe it's something that wasn't considered

**Comment by AffectedArc07** [comment]
I will look into removing the colours so it matches the style, as for now this is just using the proc built into the datacore to allow for easy manifest generation.

**Comment by Tlaltecuhtli** [comment]
@RaveRadbury the pda list =/= manifest as someone may just turn his off and the manifest is only available to head cartridges

**Comment by spessbandit** [comment]
yeah I like the UI change but this downplays the balance component

**Comment by Ohagi-Chan** [comment]
You could still change the messaging system to be a nice table like this.
There's also no reason this exact table can't be given to the head cartridges.

**Comment by RaveRadbury** [comment]
Manifests are not provided on basic PDA's. The list of who can be messaged is determined by who has their PDA set to receive messages. I'm against manifests being provided to every PDA.

**Comment by Cyberboss** [comment]
Going to agree with the other commentators, having every grunt able to check the manifest can screw over stealth plays

**Review by Cyberboss — CHANGES_REQUESTED** [review]
Keep `CART_MANIFEST`. It can be considered in a separate PR

**Comment by AffectedArc07** [comment]
I really dont see the problem with the manifest being provided to everyone. Surely the crew would know who the hell they are working with, and this stuff is available on any records console anyways. But since the change was requested ill remove it in a bit.

**Comment by AffectedArc07** [comment]
OP updated.

**Comment by Ohagi-Chan** [comment]
Keep the obscurity in the messenger list but change both the messenger and manifest UI to be presented this way because it looks a lot nicer

**Comment by RaveRadbury** [comment]
> I really dont see the problem with the manifest being provided to everyone.

>Going to agree with the other commentators, having every grunt able to check the manifest can screw over stealth plays

**Comment by AffectedArc07** [comment]
Im not changing the messenger UI because that is a change far too big for this PR, and why should a message list be crew ordered. Do you have your phone contacts in order of what job they work?

**Comment by AffectedArc07** [comment]
Closing/Reopening to deal with travis

**Comment by ExcessiveUseOfCobblestone** [comment]
don't do that please.

**Comment by AffectedArc07** [comment]
Apologies. Am used to other repos and their rules.

**Comment by spookydonut** [comment]
Those colors hurt my eyes

**Pull request merged**
