### PR TITLE
Adds a few more weapons to the black market uplink

### PR DESCRIPTION
**Pull request by TheBonded**
## About The Pull Request
PR 2.5 of hopefully many that hope to bring life to the black market uplink. Adds a chainsaw and switchblade to the pool of items that can appear in the black market uplink. Let's be honest, there's not many actual weapons in the weapons section, despite the name.

## Why It's Good For The Game
The black market uplink is hardly used now. Maybe it gets used more with more items to go for?

## Changelog
:cl:
add: Added the chainsaw and switchblade to the list of items available in the black market uplink.
/:cl:

### CODE REVIEW

**Comment by Time-Green** [comment]
Add moth milk to the black market

**Comment by TheBonded** [comment]
> Add moth milk to the black market

I'll put this on my list of ideas for black market additions

**Comment by ilikesaying** [comment]
Lizard Milk

**Comment by Mothblocks** [comment]
> I'll put this on my list of ideas for black market additions

no you wont

**Comment by TheBonded** [comment]
> > I'll put this on my list of ideas for black market additions
> 
> no you wont

(Joke)

**Pull request merged**
