### PR TITLE
Mech & vending machine fixes

### LINKED ISSUE #10207: Vending Machine contraband items are supposedly always empty
Apparently everyone knows about this issue but nobody reported it?

??????

### LINKED ISSUE #10773: Ripley goliath plate overlay is broken.
It doesn't turn with the ripley anymore:

### LINKED ISSUE #10776: Resisting out of the odysseus sleeper still says they are in the sleeper
Guy gets picked up by a the sleeper and resists out but the sleeper says he is still in it. So if you hit eject he gets teleported back to the mech without dropping him out.

### PR DESCRIPTION
**Pull request by phil235**
Vending fixes:
- Give refill canisters three separate charge values for standard, contraband(hacked) and premium(coin) items. So that next time someone increases the amount of items in a vending machine w/o updating the refill  charges (looking at you /vending/clothing), it will affect the items in the same product list instead of only contraband. This will prevent wrong charge amounts to standard items from going unnoticed (because only changing hidden items amount). (I also changed a warning comment to be in capital letters for visibility)
- I also updated the charges of the refill canisters to the correct amounts. Fixes #10207 

Cooking:
- Adding a mention about being able to load food into snack vending machines in the cook book.
- Removed the power setting of the microwave. The microwave upgrades makes it unneeded.

Mech fixes:
- Fixes goliath hide overlay on ripley not updating correctly. Fixes #10773 
- Simplifies the code for goliath hide application on ripley mech.(adding hides var to ripley)
- Fixes some mech equipment's Destroy not calling return ..()
- Fixes mech sleeper not reset its patient var when ejecting the patient. Fixes #10776 
- Removed unnedded update_equip_info( in sleeper/detach()
- Fixes an oversight in syringe_gun/process().

### CODE REVIEW

**Comment by Lumipharon** [comment]
NO, NO!! don't remove the chef thing in the snake vendors. It is unbelievable useful - just because not everyone uses it, why remove it?

It's a good feature that reduces clutter.

**Comment by phil235** [comment]
Alright, if people actually like it, I'll keep it.

**Comment by Midaychi** [comment]
I don't understand what the chefs thing is or how to use it, and I've seen no hints nor tips on relieving these issues. Maybe the reason it isn't used is because of that?

**Comment by phil235** [comment]
@Midaychi Anyone with chef access can load any snack vending machine with meals (as long as they aren't junk food) either by attacking the machine with the food or by using a kitchen tray. What should I add to make the feature more visible?

**Comment by Midaychi** [comment]
Add a mention of the feature to the wiki at http://www.ss13.eu/wiki/index.php/Chef , and maybe give them a note on their table? Something from supply and requisitions about enabling such a feature on food vending machines, due to lawsuits from healthy nutrition op representatives.

**Comment by phil235** [comment]
@Midaychi  That's the wrong wiki.

**Comment by Midaychi** [comment]
Oh I figured it was the right one cause the https://tgstation13.org/wiki/Main_Page doesn't load. Guess it might if you leave it.

**Comment by phil235** [comment]
I readded the ability to load food in the snack vending machines. I removed the power setting of the microwave that I added with the cooking overhaul. It's really not needed since we have the machine upgrade system. If anything it makes  the microwave window look more complicated to newbies.

**Comment by Lumipharon** [comment]
If the kitchen had a snack machine by the tables to the corridor, chefs might actually use it.
Ive only used it while autism forting the white ship, and seen a few chefs that have been assed moving one to the front of the kitchen.

**Pull request merged**
