### PR TITLE
Map pull for DiscStation.0.8.0 [DNM]

### PR DESCRIPTION
**Pull request by Strathcona**
I know several people have disliked the map and there may well be terminal issues with it but I was encouraged to make a pull request all the same so here it is.

Pictures are slightly out of date
thumbnail06

You can see the full image [here](https://www.dropbox.com/s/86h8prd8vm763jq/discstation.0.7.8.dmm.0.png?dl=0)

And the forum thread is [here](https://tgstation13.org/phpBB/viewtopic.php?f=11&t=3871)

### CODE REVIEW

**Comment by Anonus** [comment]
I don't super like this map, but the department placement seems good.
Map buddies!

**Comment by WJohn** [comment]
So are we all pushing our maps now?

**Comment by Strathcona** [comment]
Miaw suggested in the forum thread that we should push them in order to test them since it's much easier than manual changes. They won't be permanent features of the codebase unless people actually want to play them regularly.

**Comment by GunHog** [comment]
All these mappers, and I cannot even get one person to make a small edit to the main Box map...

The DiskStation map is not without its faults, but I am certainly interested in playing it for a while.

I do not like the idea of all those little windowed holes in the hallway, they make it dangerously easy to create hull breaches.

The AI Sat's staircase is quite strange. The turrets' stun mode would be blocked by the windows, so they would only be useful on lethal mode.  I think you may want to consider replacing some spots on the staircase with normal tiles, as it looks strange being so long.

It is also frustrating to no end that the only head without easy access to a hardsuit continues to be the RD. It is this way with all the alternate map...

**Comment by Strathcona** [comment]
The AI sat has since been fixed. 
ai04

It's just that the program I use to render the map broke recently and I don't have the time to run around as a ghost. I'm also going to guess there's a lot of button related problems since the button PR seems to have removed some, but not all, of mine in the map update and I probably missed some putting them back in.

**Comment by WJohn** [comment]
Could you NOT have that wire running through the wall there in your AI sat?

**Comment by Strathcona** [comment]
I know about wires pipes and disposals only going through walls when absolutely necessary. It's already fixed in the version I'm pushing, don't worry.

**Comment by Fox-McCloud** [comment]
That turret control placement is terrible.

**Comment by MrStonedOne** [comment]
@Strathcona I need it to compile for testing.

**Comment by Strathcona** [comment]
That should work now.

**Comment by Razharas** [comment]
Ahahaha good luck

**Comment by Strathcona** [comment]
I'm going to try again with another pull. Closing.

**Pull request closed without merging**
