### PR TITLE
Lawyer PDAs can't be painted by the HoS

### PR DESCRIPTION
**Pull request by JohnFulpWillard**
## About The Pull Request

Removes the Lawyer's PDA from the head of security's PDA painter, as they're a Service job.

## Why It's Good For The Game

They're a Service job, there's no reason for the Head of Security to be able to have any authority over them or their equipment.

## Changelog

:cl:
fix: The HoS' PDA painter can no longer paint PDAs into Lawyer ones.
/:cl:

### CODE REVIEW

**Comment by Farquaar** [comment]
Crippling HoS nerf

**Comment by Timberpoes** [comment]
If the HoS wants to promote a lawyer, they can. The role is primarily brig based and the HoS controls it.

If the HoS wants to demote a lawyer, they can for the same reasons.

The alternative is a HoS confiscating the ID and PDA which is so, so much worse IC consequence wise.

I think it's fine for both to have control over this.

Similarly I think it's fine if the CMO gets partial control over Psychologists.

While one controls the role, the other controls the department. Letting both have the tools to get into conflict trying to assert this authority is fine and good and SS13.

**Comment by ShizCalev** [comment]
+1 w/ Timbers.

**Comment by JohnFulpWillard** [comment]
I think it's wrong for a HoS to be able to give Lawyer trims without being able to give access to the Law office.
Lawyers are a Service job, and their access to the brig can be removed by the HoS, same with their security radio, but the HoS should not have a say over the Lawyer's trim, PDA color, and personal service office.

This PR only removes the PDA painter too, the ID trim was removed in https://github.com/tgstation/tgstation/pull/68292 already.

**Comment by Mothblocks** [comment]
As we have an abnormally large number of open PRs, I am closing all ones that have been marked stale. Please find an interested maintainer over Discord to reopen and merge the PR.

**Pull request merged**
