### PR TITLE
Martial art fixes

### LINKED ISSUE #8941: If you drop boxing gloves, you leave boxing mode
Even if you have another pair still equipped. Makes you look like a douche if you challenge people and knock them bloody if they accept.

### LINKED ISSUE #8965: The new wrestling suplex doesn't show up in attack logs
Suplex does 30 damage and doesn't log. If it ever becomes available to the crew without admins this should be logged.

### PR DESCRIPTION
**Pull request by AnturK**
Fixes boxing resetting on dropping unequipped gloves
Fixes #8941 
Fixes #8965

### CODE REVIEW

**Comment by Cheridan** [comment]
Please include a small description of what your PR does changes :)

**Comment by AnturK** [comment]
:speak_no_evil:

**Comment by Incoming5643** [comment]
Dear AnturK,

How do you type with boxing gloves on?

Crapfully Yours,

Incoming

**Comment by SamCroswell** [comment]
I believe you can also get the wrestling/boxing style permanently by:

 - Equipping a wrestling belt, setting your style to wrestling and saving the old style in the belt as the default style.
 - Equipping boxing gloves, thus saving the old wrestling style in the gloves as the wrestling style and setting your style to boxing.
 - Dropping the wrestling belt, setting your style back to the default.
 - Dropping the boxing gloves, setting your style to the wrestler's style saved in the gloves.

**Comment by AnturK** [comment]
Yeah, that's the issue i couldn't come up with easy solution too. I guess i'll differentiate between temporary and permanent ones. Will put up fix for that soon.

**Comment by Jordie0608** [comment]
Silly travis

**Pull request merged**
