### PR TITLE
adds Kudzu as a botanist-only uplink item

### PR DESCRIPTION
**Pull request by ghost**
:cl: awesine
add: The botanist can now purchase Kudzu seeds for 5 TC.
/:cl:

[why]: botanists don't have a job-specific traitor item so i'd thought i'd give them one

### CODE REVIEW

**Comment by Buggy123** [comment]
I don't touch botany much - is Kudzu hard to grow? Don't you just keep growing weeds until you randomly get it?

**Comment by kevinz000** [comment]
i mean sure if they want to waste 5 tc lol.

**Comment by XDTM** [comment]
Traitor items should open extra options for a given job, not replace its progression; and in any case kudzu is pretty easy to get

**Comment by awesine** [comment]
well this is just a simple thing so that botanists have a job-only item

**Comment by awesine** [comment]
>Traitor items should open extra options for a given job, not replace its progression; and in any case kudzu is pretty easy to get


geneticists and CMO's get a syringe that turn people into monkeys

**Comment by ExcessiveUseOfCobblestone** [comment]
@awesine that is not progression replacement, it's nullifying the do_after of injecting.

**Comment by awesine** [comment]
@ExcessiveUseOfCobblestone english please

**Comment by XDTM** [comment]
normal syringe no instant, traitor syringe yes instant

**Comment by awesine** [comment]
Well with a regular Botanist, you have to wait and grow your on Kudzu. With this, you get instant kudzu.

**Comment by Cyberboss** [comment]
Make sure this is able to be mutated/get potency otherwise its worthless

**Comment by Cyberboss** [comment]
@awesine kudzu was removed from regular botany iirc

**Comment by awesine** [comment]
@Cyberboss it's just a regular seed of kudzu i'm not exactly sure i'll test it

**Comment by FantasticFwoosh** [comment]
People laughed me out of the git when i suggested making a botanist traitor box-set for like 15 tc on IRC that one time, that's like adding a gatfruit seed for 10 tc despite the fact its going to totally destabilize the round.

It'll either fall flat or just call a instant shuttle out of there if you planted it later in the round when the crew is too weary with other traitor shenanigans. Botanists are also too close by to abuse the Kudzu hard akin to the old days when Daisy used to make deadly strains in a small portion of maintenance.

**Comment by awesine** [comment]
This is a single-use seed that can't be mutated unless you fucks with it in Botany, which is highly obvious and most people will valid you. If you want, I can increase the TC price or make it 1 purchase only.

**Comment by FantasticFwoosh** [comment]
You can plant it into a tray, spam saltpetre/gene edit it and then split the harvest pods into upwards of 3 or more seeds each. Hence why generating kudzu pods gets out of control in the first place @awesine

**Comment by awesine** [comment]
Which takes time and the cooperation of an entire different department.

**Comment by awesine** [comment]
fuck why is the close button right next to comment

**Comment by FantasticFwoosh** [comment]
Uh, you mean botany. For botany traitors.

Which other department.

**Comment by awesine** [comment]
Chemistry. For saltpetre.

**Comment by awesine** [comment]
Not to mention you have to be incredibly lucky to get a mix of bad kudzu traits that aren't fuddled with good ones

**Comment by FantasticFwoosh** [comment]
That still only effects potency but you can circumnavigate it anyway by using a floral somaray to raise 0 harvest to 1 and then double it with 'robust harvest' plant nutriment. After you grow more seeds you don't need to re-buy the kudzu at all and are free to ask around for more methods to develop it.

**Comment by awesine** [comment]
Which requires the cooperation of another department.

**Comment by FantasticFwoosh** [comment]
Even with the proposed scenarios, why aren't you attributing it into your balance concerns? (**ninja'd by new commit**) Botanists frequently ask for chemicals and supplies with only a minor amount of thought going through the person giving it on the opposite department already.

**Comment by 81Denton** [comment]
I don't see it offer many benefits for 5TC - for comparison, an emag costs 6. Especially if you consider that A) everyone is gonna valid you as soon as it's planted and B) you'd still have to mutate it until you get stats and traits that make it really effective.

**Comment by Bawhoppen** [comment]
Job only traitor items are still silly

**Comment by awesine** [comment]
you're silly

**Comment by awesine** [comment]
@81Denton So you're saying even cheaper?

**Comment by awesine** [comment]
also i have no clue why the travis ci build failed

**Comment by awesine** [comment]
@FantasticFwoosh Because Kudzu is *incredibly* easy to kill once you find out where it is.

**Comment by 81Denton** [comment]
@awesine Either that, or make the seed better. Unmutated/low potency strains can be cleared out super easy.

**Comment by KorPhaeron** [comment]
>Traitor items should open extra options for a given job, not replace its progression; and in any case kudzu is pretty easy to get

**Comment by awesine** [comment]
>@awesine kudzu was removed from regular botany iirc

@KorPhaeron

**Comment by FantasticFwoosh** [comment]
Because we nerfed it multiple times @awesine people tremble in terror of the more powerful mutations such as flowering. That close-down was actually intercepted in #30080 compared to the nerf that succeeded it in #30084

**Pull request closed without merging**
