### PR TITLE
Adds a new station trait: Alert Database Mishap

### PR DESCRIPTION
**Pull request by Rhials**
## About The Pull Request

Adds a new station trait: The Alert Database Mishap.

With this trait active, the Disease Outbreak (level 7 biohazard) and the Blob (level 5 biohazard) will swap announcements. Better make sure the crew knows about it.

## Why It's Good For The Game

Encourages command to be more diligent about keeping the crew informed. This can take the form of announcing the station trait to the crew at roundstart, or by reining in a panicked crew and informing them that there is not, in fact, a blob. Either way, the trait should be mostly benign in the presence of good command, and completely disastrous in their absence. 

Also, I miss hearing the "confirmed outbreak of level x biohazard" alert and watching chat fill with people unsure of if there's a blob or a sentient disease. People just don't do that anymore. I miss it. 

## Changelog

:cl:
add: New station trait: Alert Database Mishap -- Swaps around the level 7 and 5 biohazard alerts, because that would be funny I think.
/:cl:

### CODE REVIEW

**Comment by JohnFulpWillard** [comment]
Command reports are sent to command for a specific reason and it’s to limit it to command, like secret’s antagonists flavortexts mentioning not to alert the crew of its contents, I dont see why we should encourage this behavior

**Comment by thgvr** [comment]
Meh, turns both announcements into "search for blob" instead of just one. It's a little funny though.

**Comment by MrDoomBringer** [comment]
Hard to win the round as blob without being called out at any point by crew, unlike the narsie-announcement.

**Comment by ArcaneMusic** [comment]
(Just an FYI we don't have content expansion tag anymore, you might want to tweak the changelog)

**Comment by Rhials** [comment]
I've decided to lower the weight of the trait to prevent it from becoming something people get desensitized to because it happens so often. I'm not sure what the chances of both this trait and either of the relevant events rolling in the same round are now, but the potential humor I intended for this event would be diminished if it became a regular thing.

**Comment by SuperNovaa41** [comment]
I agree with the others above, I feel like those are fairly important announcements. especially since most times the blob is a far greater threat than a disease (even if it is sentient).

Now, making the messages worded differently so that they're obscured a bit would be okay i think, but they should still respect their event

**Comment by tralezab** [comment]
I wish this wasn't blocked 😢

**Comment by Ryll-Ryll** [comment]
We already have the fake announcement events, this is just lying to the players for the sake of lying to the players

**Pull request closed without merging**
