### PR TITLE
Fix light eater affecting lava, space, openspace, and transparent turfs

### LINKED ISSUE #79388: Nightmares can darken glass floors with starlight shining through
Reporting client version: 514.1589

## Round ID:
[217785](https://scrubby.melonmesa.com/round/217785)

## Testmerges:
- [Extends Halloween](https://www.github.com/tgstation/tgstation/pull/79316)
- [Changes how halloween lighting works slightly](https://www.github.com/tgstation/tgstation/pull/79340)

## Reproduction:

See the title. Given that #78318 was considered a bug, I feel like this is probably a bug too.

### PR DESCRIPTION
**Pull request by timothymtorres**
## About The Pull Request
Fixes #79388

Light eater element can no longer affect lava, space (starlight), openspace, or any turf with transparency.

## Why It's Good For The Game
Better consistency.

## Changelog
:cl:
fix: Fix light eater affecting lava, space, openspace, and transparent turfs
/:cl:

### CODE REVIEW

**Comment by Jacquerel** [comment]
I think you should just expand the typecache rather than reimplement it as four separate checks.

**Comment by timothymtorres** [comment]
Each one of those checks are typepaths linked to the turf.  For instance, if someone in the future creates a new type of lava or space, it would be in those helper is typepaths.

I've seen this problem occur previously.  You want one global typepaths to check.

**Comment by Jacquerel** [comment]
> Each one of those checks are typepaths linked to the turf. For instance, if someone in the future creates a new type of lava or space, it would be in those helper is typepaths.
> 
> I've seen this problem occur previously. You want one global typepaths to check.

Typecaches also include children, I am not sure what the saving is supposed to be from doing this as four checks.

**Comment by timothymtorres** [comment]
Using these global helpers is done in a lot of the code already as a replacement for individual typecaches.  It's better to use the helpers since whenever a new atom gets added to the helper list, it updates to every place using them instead of having to individually update multiple typecache. (which leads to a lot of bugs!)

And these helpers don't just have subtypes, some have traits and other typepaths included.

**Comment by Jacquerel** [comment]
Only one of these isn't a literal typecheck so you can keep that one. Put the rest back in a typecache. If you are worried about maintainability then make a global list for it.

**Comment by timothymtorres** [comment]
The whole reason this bug exists is because someone _hardcoded_ the typepath into a list... and you want to keep that behavior so it will break years down the road when someone inevitable adds new turfs to any of the above lists?

**Comment by Jacquerel** [comment]
`typecacheof(list())` is literally how we solve these problems (for `isopenspaceturf` for instance)
Changing it into four checks is not an improvement and you have not named any problem which isn't 

To fix this you have made a change which is functionally identical to expanding a typecache, if someone adds a fifth type of turf we don't want to remove lights from you would still need to add it here anyway. 
If they add one which is already a subtype of one of those turfs, it will already get caught by `typecacheof(list())`

If you want it to be composed of a group of other existing lists that is also possible while still using a list typecache instead of pointlessly breaking one check into multiple, and making it so that the next person to add something will just turn it back into a typecached list.

**Comment by timothymtorres** [comment]
The advantage of helpers is not having to maintain separate blacklists or whitelists all across the codebase where they are used. 
When a new atom is added to a helper, like `isopenspaceturf()` or `isgroundlessturf()`, it updates in all spots accordingly.  Before those helpers were global typecaches, they used to be simple `istype()` checks.  As more turfs were added, the need to convert the helpers into global typecaches happened to catch and prevent bugs in the future. (note - I helped convert some of the helpers to global typecaches and expanded their lists accordingly)

So let's take something like the lava helper:

`#define islava(A) (istype(A, /turf/open/lava))`

Using the helper seems pointless but if later someone adds a new turf like, `/turf/open/openspace/lava`, it can be added as a global typecache for the lava helper without breaking everywhere. Why would someone want openspace lava? Perhaps they want it to be a multi-z pool of liquid?! (Dwarf fortress style!)

---

Using the helpers the way I did has _precedent_ in lots of different parts of the codebase. The helpers are easier to use and more readable than a blacklist. This helper typechecking method has been used in many PRs in the past:

- I have implemented it
- Other maintainers have implemented it
- _You_ have implemented it

One of many many examples:
https://github.com/tgstation/tgstation/blob/a7439f69f96f6cdb23c2f7cf80340c03c87c6a3c/code/datums/elements/floorloving.dm#L15-L18

So there is nothing wrong with this doing it like this. Keep in mind, **I have used blacklists/whitelists in other parts of the codebase** but they are idiosyncratic.  The only time a blacklist/whitelist is more suitable:

- There is a large list of different types of atoms
- Atoms are expected to be frequently added later
- The blacklist is being referenced in multiple spots

None of these applies to this bugfix and I don't want to spend hours debating this. This was _supposed_ to be a 5 minute one-line bugfix.

So to make this short and sweet, the blacklist is back and is a static var linked to the element. I kept the transparent turf helper since it's checking for traits and would not be suitable for the blacklist. During my recent testing, the openspace checks were also unnecessary since it is not possible to click on those tiles due to how multi-z openspace click callbacks works.

**Comment by Jacquerel** [comment]
To make a short reply to your long post:
Is this list likely to be expanded in the future? Yes!
Are the new turfs we need to add to this list likely to be attached to any of the helper methods you were using? Absolutely not! Nobody is going to add a new lava turf which isn't a subtype of lava!

Expanding the list is faster and more convenient for future developers, and more likely to make future maintenance easier.

**Pull request merged**
