### PR TITLE
Replaces EVEN BLOODY MORE RELATIVE PATHS WITH ABSOLUTE PATHS AGHHHHHHHHH...

### PR DESCRIPTION
**Pull request by Firecage**
Basically what it says in the title...

### CODE REVIEW

**Comment by optimumtact** [comment]
:+1:

**Comment by Jalleo** [comment]
:rotating_light:

**Comment by JJRcop** [comment]
Keep in mind https://github.com/tgstation/-tg-station/pull/5871#issuecomment-62916418

**Comment by Firecage** [comment]
JJRcop, you still need consistency. Considering just about all the code is absolute paths, well, yah.

**Comment by JJRcop** [comment]
I know, I support this change, but just saying I don't believe @Carn will at all

**Comment by optimumtact** [comment]
I think consistent standards are important to have

**Comment by paprka** [comment]
Consistency is nice visually but relative paths keep related code together (hence the name)

It's preference really, up to @Cheridan @hornygranny etc because bygex is carn's deal

**Comment by optimumtact** [comment]
I don't think we should have one standard for most people and then one more for a few people. It's not fair on either side

**Comment by Cheridan** [comment]
The paths hurt nothing and if changed impedes Carn's ability to port any changes she makes to the bygex package. Do not change the paths.

**Comment by paprka** [comment]
It's pretty fair if you're just changing it because you have OCD and never actually use the system @optimumtact

**Comment by Firecage** [comment]
Well, if @Carn wishes, I will just make the Bygax stuff into relative paths again.

**Comment by Firecage** [comment]
Personally for absolute paths, it looks neater atleast for me, and personally it is easier to find stuff.

**Comment by Cheridan** [comment]
As I said before, losing support for the code because of an OCD adherence to cosmetic standards in a file that nobody but the original author is likely to change anyway is not worth it.

**Comment by MrPerson** [comment]
Well even if Cheridan insists on being stupid and keeping Timsort as relative, the rest is all obviously good since it's all clearly oversights, oldcode, or the same sort of "oh carn is a special snowflake" bullshit.

**Comment by Carn** [comment]
@MrPerson
seriously, just stop with these crusades against people over superficial cosmetic issues like varnames and absolute pathing. It's not Cheridan's fault.
Change them all to absolute, whatever... I'm busy actually fixing shit that matters.

**Comment by paprka** [comment]
pwned

**Comment by optimumtact** [comment]
Epic memes, follow the coding standards next time so we don't have to keep beating you over teh head about it.

Everyone else seems to manage it but you're the only person who doesn't, and then you have the gall to get upset when people ask you to fix it or come in and fix it themselves

**Comment by MrPerson** [comment]
If we don't want the standard, that's fine. It is a lot of work to enforce it and stick to it. But if we're going to keep it, it should be applied to everyone and everything equally.

Also update https://tgstation13.org/wiki/Coding_Standards accordingly

**Pull request closed without merging**
