### PR TITLE
Updated MetaStation.v41F.dmm to MetaStation.v41G.dmm

### LINKED ISSUE #9607: Pipe error on metastation map
Two pipes are on same tile (and same dir) at 106, 89 on Metastation map causing an error during initialization.

### LINKED ISSUE #9853: Mini sat and Incinerator Air Injectors into space don't work on MetaStation
The Air injectors meant for disposing of gases on the mini sat and for the incinerator don't  seem to work. They don't seem to be receiving power and clogs the the mini sat scrubbers.

### LINKED ISSUE #11074: Meta: Pugley IV is invisible

### LINKED ISSUE #11415: Metastation syndie base has an area of space in it, making parts unpowered.
@Metacide 
Syndie base

### LINKED ISSUE #11529: Metastation: Starboard Emergency Storage airlock Invisible

### PR DESCRIPTION
**Pull request by Metacide**
Updated MetaStation.v41F.dmm to MetaStation.v41G.dmm
Updated MetaStation/z2.dmm
*Altered the AI chamber so it is (hopefully) somewhat more secure
*Added AI liquid dispensers to the AI chamber foyer and two adjacent siderooms
*Added far more varied blob spawn locations
*Added (provisionally) a 2% chance roundstart xeno egg in the secure lab test chamber
*Added photocopier to security office and warden's office
*Added shutters to the armory for ease of arming security
*Adjusted club spawner to mostly spawn russian roulette revolvers, somtimes syndicards, rarely ninja stars
*Adjusted MiniSat powergrid - it is now independent of the station, but easy to hook up
*Fixed issue with z2 where part of the syndicate mothership wasn't designated properly causing depowered TC console
*Fixed invisible doors: starboard emergency storage, brig infirmary maint, both fore solar control room doors
*Fixed missing revenant spawners and Marauder entry points
*Fixed a few blob spawn locations being dangerously close to fueltanks
*Fixed duplicate CMO stamp on their desk
*Fixed a few access issues on maint. doors around research
*Fixed heat passing through toxins burn chamber glass doors
*Fixed missing Pugley IV sprite
*Moved north-west nuke op shuttle location further away from the station
*Moved routing manifold segment of disposals which routes to Captain's Office adjacent to the office, under a camera, so it can more easily be checked for tampering
*Replaced the walls connecting MiniSat walkway to the MiniSat proper with girders or lattices for better visibility
*Replaced now-destructible shuttle turf at the bombsite with indestructible centcom-style turf
*Switched general intercom outside AI chamber to the private AI channel

Fixes https://github.com/tgstation/-tg-station/issues/9607
Fixes https://github.com/tgstation/-tg-station/issues/9853
Fixes https://github.com/tgstation/-tg-station/issues/11074
Fixes https://github.com/tgstation/-tg-station/issues/11415
Fixes https://github.com/tgstation/-tg-station/issues/11529

Map merge is broken and has been for quite some time, so I'm submitting this as-is despite all the addition / deletion spam. Blame whoever broke map merge.

[Wiki Page](https://tgstation13.org/wiki/index.php/MetaStation)
[Full Res Image](https://dl.dropboxusercontent.com/u/858120/Static/SS13/MetaStation/15-09-04%2016-34%20MSv41G%20Full.png)
[Feedback Thread](https://tgstation13.org/phpBB/viewtopic.php?f=11&t=3090)
[Files](https://dl.dropboxusercontent.com/u/858120/Static/SS13/MetaStation/15-09-04%20MSv41G%20Files.zip)

### CODE REVIEW

**Comment by Supermichael777** [comment]
>Blob spawn locations
are these even still used?
>random xeno egg round-start
please no xenos are enough of a problem. Don't make them rng round-start. all round-start rng should be on the asteroid anyway

**Comment by GunHog** [comment]
Pic plz k thx lol

**Comment by Anonus** [comment]
Blob spawn locations are used for the nuke disc and blob event spawns

**Comment by Metacide** [comment]
I'll try setting the shield generators to active on roundstart as an added precaution. Wonder how much power it'll drain.

**Comment by Metacide** [comment]
Alright, looks good to go now, haven't seen any other issues.

**Comment by Dorsisdwarf** [comment]
Metacide, is it possible to make the blast shutters start down when there's an egg?

**Comment by Metacide** [comment]
I think the best protection really would be the shield, but I could just make the shutters start down every shift. I'll look into it, but either way it'll be something for the next update, I think.

**Comment by Aranclanos** [comment]
why don't you use an old version of the map merger?

**Comment by Metacide** [comment]
I presumed something had changed, and that if that were possible we'd have reverted to that version at some point in the last few weeks. I'll check with WJohnston.

**Comment by Razharas** [comment]
Is this ready or some additions will come?

**Comment by Metacide** [comment]
It's good to go.

**Comment by Aranclanos** [comment]
alright sure yolo

**Pull request merged**
