### PR TITLE
[s] Buckling a mob to a comfy chair will no longer set them on fire

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
I'm not sure why I decided to do the first dozen or so of these manually before advanced find+replace but this is the result.

### CODE REVIEW

**Comment by GunHog** [comment]
Now THIS is proper use of the [s] tag! Also hilarious.

**Comment by KorPhaeron** [comment]
@GunHog 

Between this and perma flipped mobs from meat spikes I think I have a pretty good shot at winning bug of the year

**Comment by hornygranny** [comment]
fantastic

**Comment by PKPenguin321** [comment]
kek

**Comment by bgobandit** [comment]
feature

**Comment by Shapsy** [comment]
how

**Comment by duncathan** [comment]
I went to review the code, saw this, and then went back and noticed that it had ALREADY BEEN MERGED HOURS AGO AAAA

**Comment by duncathan** [comment]
This is holding up a server update and also is kinda high priority in itself

**Pull request merged**
