### PR TITLE
Items in your hands can catch fire

### PR DESCRIPTION
**Pull request by Jacquerel**
## About The Pull Request

Recently we allowed items held in your hands to catch fire if you catch fire.
This makes sense but the code had a few oversights, then we reverted it.

This PR reintroduces the feature, but with a few refinements.
The basic feature is simple: If you are on fire then items you are holding will also catch fire, in the same vein as items you are wearing on your head or hands.

There are also a few caveats we forgot about the first time we added this:

- If your gloves cannot catch fire, your held items will not catch fire (because your hands aren't on fire).
- If you are extinguished, your held items will also be extinguished.
- Stopping, Dropping, and Rolling on top of any items will also extinguish those items. 

As part of this change, after an argument about whether or not this is an oversight in coding-general, I've made the proc `get_equipped_items` take a bitflag instead of a series of booleans as an argument and added a new one for "include held items", so that we need no longer argue about whether holding something counts as "equipping" it (in all other parts of the game than this proc, it does). This is what gives the PR most of its code footprint, don't be scared.

## Why It's Good For The Game

Items you are holding in your hands _should_ catch fire if everything else on your person is on fire, and taking an item off of your body to put it in your hands shouldn't protect it from fire, because those things don't make intuitive sense. 
If we want an item to be able to catch fire when worn, then it should do so.

This might expose some issues where we were improperly setting the flammability flags on items, but any weapon which will burn in your hands now would also have burned if you were wearing it on your belt or back, so making those issues more visible should be a bonus (we'll also stop them from burning on your back or belt).

If you see someone holding a piece of paper that you really don't want them to read you can now set them on fire to stop them from reading it, whereas previously they would deftly hold the very flammable object out of reach of their flaming body.

## Changelog

:cl:
balance: Items held in your hands can catch fire.
balance: Items you are holding won't catch fire if your hands cannot catch fire.
balance: When you stop being on fire so will items you are holding.
balance: If you roll around on your burning items they will stop being on fire.
/:cl:

### CODE REVIEW

**Comment by GPeckman** [comment]
Does this include the flammable-armblade stuff is that going to be part of a later PR?

**Comment by Jacquerel** [comment]
> Does this include the flammable-armblade stuff or is that going to be part of a later PR?

It's up to goofball to decide when or if or in what form he reintroduces any of that stuff
Armblades cannot currently catch fire, even following this change

**Comment by ATH1909** [comment]
Aren't borgs able to catch on fire if they stand in a hotspot? Will this affect them/risk destroying their modules?

**Comment by Jacquerel** [comment]
> Aren't borgs able to catch on fire if they stand in a hotspot? Will this affect them/risk destroying their modules?

The change to the list of things which can burn is on the `carbon/human` subtype so cannot reach cyborgs.

**Pull request merged**
