### PR TITLE
Adds nuke challenge mode feedback detail

### PR DESCRIPTION
**Pull request by Jordie0608**
For @nfreader
It makes more sense to be a distinct detail

### CODE REVIEW

**Comment by coiax** [comment]
I feel like we already track this stat though, I've seen the stats on war-ops vs regular (spoiler alert, war ops have far worse win rates)

**Comment by Jordie0608** [comment]
I had a quick look but didn't see it, I'll search some more later.

**Comment by nfreader** [comment]
Thanks!

**Comment by lzimann** [comment]
stop stealing my prs @Jordie0608

**Pull request merged**
