### PR TITLE
[Aprile Fools] [TM] Add Zomboid jumpscare

### PR DESCRIPTION
**Pull request by TheBoondock**
## About The Pull Request
Have you ever wanted to scare a fellow player? well now you can, simply stay in the dark next to a door when they open it.

https://user-images.githubusercontent.com/92416224/229048120-20581431-51dc-4a0c-8905-c49d39c6f1bc.mp4
## Project Zomboid Info
Thanks to The Indie Stone for creating Project Zomboid https://projectzomboid.com/), which made this possible. This is an unofficial fan production for non-commercial purposes made under the AGPL-3 license. 

## Why It's Good For The Game
Mini heart attack for the fellow pz players out there
## Changelog
:cl:
add: Added project zomboid jumpscare sound
/:cl:

### CODE REVIEW

**Comment by UnokiAs** [comment]
Should not be a april fools and instead should be instant merged

**Comment by RikuTheKiller** [comment]
> Should not be a april fools and instead should be instant merged

So true...

**Comment by Valorium-RB** [comment]
Merge it, but have it only work when the person behind the door is infected with Romerol.

**Comment by Mothblocks** [comment]
For the benefit of the maintainers, April Fools PRs will be labeled and closed. Key Holders are still able to test merge PRs that are closed, so this makes no difference to you, the author, assuming you were able to find a Key Holder to merge this PR in the first place. If you need to make updates to this PR, you can simply add to the branch, and when the TM updates it will use those changes, even if they do not show up to the PR.

**Comment by LSommers** [comment]
Okay but can we restrict this to nightmares and remerge it after April Fool's?
It's fitting. And funny.

**Comment by Mothblocks** [comment]
nightmares already have a sound

**Pull request closed without merging**
