### PR TITLE
Adds friendly life reaction to chemistry

### PR DESCRIPTION
**Pull request by 81Denton**
## About The Pull Request
This adds a version of the Life reaction that spawns friendly mobs instead of hostile ones.

## Why It's Good For The Game
Chemistry is missing some reactions that aren't just for killing or healing people. With this you can spawn non-hostile mobs, which can be useful for things like the DNA vault or cargo bounties.

## Changelog
:cl: Denton
add: Added a friendly version of the Life reaction to chemistry. It has a similar recipe as the original reaction, just replace blood with sugar.
/:cl:

### CODE REVIEW

**Comment by 81Denton** [comment]
On second thought, I'll replace blood with pax instead to avoid possible recipe conflicts. Synthflesh contains blood already, after all.

**Comment by Tlaltecuhtli** [comment]
accidentally getting combat bears instead of corgis seems fun tho

**Comment by 81Denton** [comment]
The old recipe still spawns friendly mobs, it just also causes the recipe conflict test to throw errors

**Comment by subject217** [comment]
Nerf bastion

https://www.youtube.com/watch?v=COOmBnwbVj0

This pr

**Comment by 81Denton** [comment]
I've decided to replace pax with sugar, it just fits better for a reaction that creates fluffy dogs and butterflies.

**Pull request merged**
