### PR TITLE
*bong rip sound* "ok, ok, bros, what if, like, we add this space ruin, where you can like, get a bunch of guns and syndicate gear, but like, you have to beat really easy crappy AI simplemobs with guns" "oh yeah thats a great idea bro this definitely wont get run into the ground every single round"

### PR DESCRIPTION
**Pull request by Iamgoofball**
## About The Pull Request

Removes the Syndicate Ambush ruin from the game.

## Why It's Good For The Game

See fucking title. This shit was run into the ground the day it went live and it's just an endless source of fuckin guns and explosions in otherwise normal rounds.

## Changelog

:cl:
del: The Syndicate will no longer ambush space trade routes due to increased Spinward Stellar Coalition police presence.
/:cl:

### CODE REVIEW

**Comment by tralezab** [comment]
thread theme:
https://www.youtube.com/watch?v=GQFTAFLBdi4

**Comment by actioninja** [comment]
ided

**Comment by optimumtact** [comment]
make another half baked removal PR and that will be the end of you.

You didn't even remove the map template.

This is literally attention seeking behaviour and I am going to land on you like a tonne of bricks

**Comment by EOBGames** [comment]
Well, that saved me the effort- if you're gonna remove it, remove it properly.

**Comment by Mothblocks** [comment]
> oh yeah thats a great idea bro this definitely wont get run into the ground every single round

it literally is not though

**Comment by KittyNoodle** [comment]
Mothblocks is right on this one, I have rarely seen this used, and many times it is for some fu gimmick.

**Comment by ChristianDenDanske** [comment]
Ided

**Pull request closed without merging**
