### PR TITLE
Removes fucking gangs

### PR DESCRIPTION
**Pull request by ghost**
:cl: More Robust Than You
del: Finally fucking removed gangs
/:cl:

This removes TEAM MURDERBONING: THE GAMEMODE!

almost nobody fucking likes this garbage gamemode, it's like splatoon meets CoD meets Team Deathmatch. it's horrible. gangsters get instakill/crit weapons (like c4 shurikens, which are almost guaranteed to kill if they hit), security has to deal with 3-4 groups trying to rip each other's hearts out, the AI constantly screams "HOOMAN HARM!!", and oh yeah, it's a fucking mass conversion mode.

Or, explained by @YakumoChen: 
> It's like Revolution but the revs also get free ballistics to kill me more easily with!!!!
> Now with triple the revheads and the round doesn't end when I kill them all leading to an endless stalemate where I will have to implant absolutely everybody on the station (or end the round with shuttle as quickly as possible because fuck this gamemode) before it's finally over!!

### CODE REVIEW

**Comment by kevinz000** [comment]
low effort

**Comment by kevinz000** [comment]
doesnt even compile

**Comment by MoreRobustThanYou** [comment]
now it should. also, people actually like gangs?

**Comment by FantasticFwoosh** [comment]
Its with plenty of flaws and has gone through 3 iterations and major adjustments with no radical improvement to players opinions or experience of it.

Unless something else is on the table canning it for now is justified.

**Comment by ma44** [comment]
Would be better if this was preserved by making it happen 0% of the time via config, hit up the headmins or whoever to go and disable it on the main servers.

**Comment by lzimann** [comment]
There's nothing to gain with this being preserved. Github stores the entire history, so not like this whole thing will be lost, and honestly, if anyone wants to do anything with gang, it would be better if it was written back from scratch than using what we currently have.

**Comment by YakumoChen** [comment]
It's like Revolution but the revs also get free ballistics to kill me more easily with!!!!

**Comment by YakumoChen** [comment]
Now with triple the revheads and the round doesn't end when I kill them all leading to an endless stalemate where I will have to implant absolutely everybody on the station (or end the round with shuttle as quickly as possible because fuck this gamemode) before it's finally over!!

**Comment by jughu** [comment]
Stoop eet im trying to BELANCE

**Comment by CPTANT** [comment]
Not this shit again.

**Comment by KingPhilipIII** [comment]
>Giving your own PR a thumbs up.

Disgraceful.

**Comment by lzimann** [comment]
@KorPhaeron i'll probably merge this soon(tm), unless you don't want it happening

**Comment by Armhulen** [comment]
i need this merged for my shadowling agenda soooooooooooooo

**Comment by PraiseRatvar** [comment]
> shadowling agenda

@Armhulen you are a funny man

**Comment by ecronogist** [comment]
Finally.

**Review by Cyberboss — DISMISSED** [review]
You missed some defines in misc.dm, some checks in ticker, the antag hud, /datum/station_state, game_mode.dm, the swarmer_act for gang crayons, config files, tip strings, tons of other stuff (though you can keep the flufftext like ion laws and cas cards etc...)

**Comment by Cyberboss** [comment]
Just grep for gang in the codebase

**Review by lzimann — CHANGES_REQUESTED** [review]
You need to remove from the `game_options.txt` and figure out to give multiverse a proper hud.

**Comment by MoreRobustThanYou** [comment]
Isn't the multiverse an admin-only weapon?

**Comment by PopNotes** [comment]
how about just removing it from the rotation instead of deleting it from the game entirely

**Comment by Bawhoppen** [comment]
@PopNotes no

**Comment by PKPenguin321** [comment]
At least wait for the poll to finish, regardless of the outcome

**Comment by YakumoChen** [comment]
Isn't the poll horribly broken?

**Comment by Cyberboss** [comment]
Not anymore

**Comment by optimumtact** [comment]
I don't think he should have to add a hud, or just leave the gang hud in for mthe multieverse sword

**Comment by lzimann** [comment]
Yea, leave the ganghud for the multiverse sword

**Comment by ExcessiveUseOfCobblestone** [comment]
Replace the Gs with Ms at least, don't TEASE!

**Comment by MrStonedOne** [comment]
https://atlantaned.space/newSS13tools/polls.php?poll=182

**Comment by KorPhaeron** [comment]
Think its fair to wait on the poll

**Comment by DoctoreMad** [comment]
Where's the obligatory "rework not remove" comment?

**Comment by Anonymous583** [comment]
remove this trash already

**Comment by Bawhoppen** [comment]
@DoctoreMad If someone had motivation to rework it, they would have by now. If someone ever does get the motivation, I'm sure their new version would be gladly accepted.

**Comment by MoreRobustThanYou** [comment]
@DoctoreMad it's been tried. Needless to say, Gangmageddon was AAAAAAAAAAAAAAAAAAAAAAAAAAA

**Comment by Robustin** [comment]
How does the poll look, I can never seem to remember where the results are posted. 

I took a hiatus and obviously haven't touched Gang because I wasn't ready to go through another Engipoints debacle where I get a couple months of work closed with no warning. 

Having said that, Gang was definitely in an unfinished state. I was hoping Mekhi would address some of the balance stuff and flesh out the "Gang HQ" concept, but it sounds like that never materialized. 

I would contemplate coming back for the Gang PR but only on the condition that there was a clear plan for handling it and not just "hey were gonna constantly threaten to close it but you also need to put in a couple dozen more hours of work to get it merge-ready...  have fun!"

**Comment by lzimann** [comment]
oh don't worry about coming back to gang, it will die like it should've months ago

**Comment by Robustin** [comment]
@lzimann 

Great illustration of the attitude blighting our community. If the community wants something you don't - then just sabotage every effort the community makes to obtain that something until the inevitable dysfunction convinces enough people to abandon the effort. 

We know where you stood on Gang months ago Leo. Just like Oranges and the Engipoints system it wasn't enough to make your position clear and leave it at that, you've got to wave that maintainer dick around telling everyone on every occasion that you will never let it get merged, you'll kill it the first chance you get, etc.

**Comment by optimumtact** [comment]
it's oranges, and there are plenty of people who work well with us, you failed to do so.

You ever wonder if everyone around you hates you because they're dumb or because you might be the bad guy?

**Comment by Cyberboss** [comment]
Stop the salting

**Comment by ChangelingRain** [comment]
I wish robustin would get a real avatar...

**Comment by RemieRichards** [comment]
I'm not sure if I want to see the smug dooku here

**Comment by Iamgoofball** [comment]
Robustin did nothing wrong

**Comment by jughu** [comment]
You are the vigilante!

**Comment by optimumtact** [comment]
no maintainer wants to work with any developer who wants to change gang so it's dead either way

**Comment by Cyberboss** [comment]
Speak for yourself

**Comment by Steelpoint** [comment]
Every gang round I play is simply a unfun experience. You have gangsters running in circles tagging and untagging areas as they chase each other. Everyone is shooting everyone as half the station can spawn firearms and deadly weapons on the fly. Any sense of "roleplay" or even the illusion of you working on some kind of space station falls apart.

Security becomes a game of either committing ritual suicide or you essentially becoming the 5th gang except you get to not die by wiping out half the station and calling the shuttle as fast as humanly possible.  Every time you play as Sec during a gang round your enthusiasm for the game dips and falls as you once again have to act, not as a protector of the station, but as just another antagonist as you end up murdering the entire station once again.

Gang is the antithesis of SS13, it absolutely destroys the point of the game and turns it into a literal game of Capture the Flag except you get UZIs and Pistols instead of Instant Kill Lasers.

Removing this game mode would do nothing but be of net benefit for the game. If I wanted to run around killing people with traitor guns I would play on a deathmatch server or Colonial Marines. On /tg/ I like to pretend to be working on a space station, even if an Assistant is running RnD and the Captain is wearing a Clown uniform.

**Comment by Cyberboss** [comment]
Final vote was against: https://atlantaned.space/newSS13tools/polls.php?poll=182

@Robustin If you want to try and balance this madness, I'd step to it

**Comment by KorPhaeron** [comment]
@cyberboss

By like 10 votes. If half our population dislikes a mode so much that they want it out of the game is that mode worth keeping?

**Comment by Cyberboss** [comment]
Frankly, I'm disappointed in the poll because of the meme third option, but democracy is democracy. Had the vote gone the other way I wouldn't have complained.

**Comment by Steelpoint** [comment]
I honestly feel the game has been in for so long, and has remain such a point of contention and has thusly remained a unbalanced game mode, that removing it should be acceptable.

The vote was a knife's edge between either side and it nonetheless showcases how unpopular it is when almost half our playerbase dislikes the game mode.

**Comment by lzimann** [comment]
it's not worth keeping at all

**Comment by KorPhaeron** [comment]
There was evidently some miscommunication if people thought it was a binding vote rather than a poll of opinions

**Comment by lzimann** [comment]
i don't get why the poll was made, it is not going to change the fact that this is a bad gamemode

**Comment by KorPhaeron** [comment]
Because if the poll was like 70 - 30 for keeping gang it'd mean the mode is actually fun and we're just out of touch with the playerbase

**Comment by lzimann** [comment]
anyway, i will be merging this as soon as the multiverse hud/team is figured out(be it by removing multiverse or finding a way around it)

**Review by lzimann — APPROVED** [review]

**Comment by Robustin** [comment]
It was left in an unfinished state and as long as the process for updating gang is "Spend Dozens of hours of your time coding and testing something just to cockblocked by maintainers" it was never going to be finished. 

We need a better system for this shit, plain and simple. We brought Gang back on popular vote, it was getting improvements, but the moment I stepped from "incremental QOL" stuff to a significant change requested by the """""design lead""""" then opponents saw sufficient controversy to stall the PR by closing it with little notice, threatening to close it once its reopened, warning the coder that it will never get merged, etc. 

We held like 3 Gang Polls after it was reintroduced and each one had <30% in favor of removal - yet despite those numbers it was still hell trying to make any kind of progress on it. I did like a week of testing and coding to make the mode compatible with "standard" and "vigilante" versions that would be split about 50/50 in line with the last poll that people support for either type roughly split. Only to have Kor inform me the "vigilante" version would be the only one that would see the light of day, and other maintainers swearing on their life that vigilantes would never be merged either. Hence my departure. 

@optimumtact 

Its not about who's pleasant. It's about me undertaking two major changes, both with the blessing of community support (roughly 2/3rds of the vote for each) and each attempt devolving into a nightmare simply because a couple maintainers didn't like what I was implementing. No amount of sparkling personality was going to win you over to Engineering Rewards and gobbling Leo's dick for months wouldn't convince him to support keeping Gangs around. 

It would be far easier on myself to just sit around tweaking vars and making the least controversial changes possible then I'm sure we could all "get along". I made the mistake about being passionate and undertaking big projects.

**Comment by MrStonedOne** [comment]
\>don't let guy improve thing

\>remove it because its bad

Really makes you think.

**Comment by KorPhaeron** [comment]
I explcitly made an exemption from the freeze for robustin to rework gang though

**Comment by MrStonedOne** [comment]
I'm referring mainly to the repeated gang prs of his that got closed 3 or so months ago

**Comment by KorPhaeron** [comment]
And Cheridan went and overrode oranges to put gang back in the game so he could work on it

**Comment by Robustin** [comment]
Yes a freeze exception, not an exception from all the drama and uncertainty.

**Comment by KorPhaeron** [comment]
I think you might be thinking of his engineering PRs because I think most if not all of his (finished) gang PRs got merged

**Comment by KorPhaeron** [comment]
Nothing can exempt you from drama sadly thats a given

**Comment by Robustin** [comment]
It's a fundamental aspect of human behavior - people will not invest a material amount of time, money, or energy into something when the outcome becomes sufficiently uncertain.

This system works fine for little changes "hey I added an item", "hey I tweaked a var", "hey I fixed a thing". But the only sane way for big stuff to get done is to have the right relationships to get a full commitment on your changes in advance. For a non-maintainer to get a maintainer to commit to a project when it's still being fleshed out is almost impossible.

**Comment by Arzion5** [comment]
In this PR : Local coder roasts the codernati, goes full Martin Luther against the church

**Comment by MrStonedOne** [comment]
>I think you might be thinking of his engineering PRs because I think most if not all of his (finished) gang PRs got merged

maybe

**Pull request merged**
