### PR TITLE
[MDB Ignore] Power cable AI Sat update

### PR DESCRIPTION
**Pull request by Mooshimi**
## About The Pull Request
Updates AI sat wiring to multi layer, and @Maurukas requested the AI's personal SMES be connected to grid as well--which has been done.

<details><summary>Delta:</summary>

</details>

<details><summary> Meta: </summary>

</details>

<details><summary> Kilo: </summary>

</details>

## Why It's Good For The Game
The AI sat wiring gets an update, and apparently power sinks don't directly drain SMES.

## Changelog

:cl:
refactor: Reworked the wiring in AI Sats incorporating multiple layered wiring.
/:cl:

### CODE REVIEW

**Comment by san7890** [comment]
Very, very tentative Do Not Merge because I get antsy every time these go through and Maurukas is the only person who consistently knows how this stuff works.

**Comment by zxaber** [comment]
Similar PR here (that didn't actually touch the AI but people thought did), had a comment about the AI's powernet;
https://github.com/tgstation/tgstation/pull/57294#pullrequestreview-600437108
image


AI's being disconnected from the grid seem to be intentional, so this at the very least should be a balance PR.

**Comment by Ryusenshu** [comment]
Now that i take a closer look at this one, it should really use multi colored cables in almost all situations
i used to wire the sat up with those as borg and it worked pretty well and was cleaner

Also the delta maint smes needs some love because it can only be charged by an empty gen round start and the maint apc is connected to the power grid itself

**Comment by Mooshimi** [comment]
drafting until I have tome to fix merge conflict

**Review by Maurukas — CHANGES_REQUESTED** [review]
Alright, there's some confusion here, but I believe this has been worked out.

Zxaber is correct - Power sinks cannot pull power from the input side of SMES - they create a large draw on the SMES that are supplying it. 

At this time the SMES on the sat are to be connected to the grid. There's been some power balance changes and I've been given reports of AIs running out of power or dying as a result of changed consumption, plus other power related anomalies. Unless there's an extremely compelling reason I'm not aware of, I want all the SMES on the AI sat to be charging from *something*. In the case of Tram, that's its dedicated solars. For other stations, that should be the main grid.

Please drop the changes from Icebox and Tramstation. These are working as intended. The following changes need to happen on Kilo, Meta and Tram.

On Kilo, connect this SMES to the blue wire that already extends onto the station:
image

On Meta, please connect this SMES to the blue wire:
image

Delta requires the most significant changes due to the arrangement of its room and wires. Please connect this SMES to the grid, and be careful to avoid power loops. I see in your changes you added a blue cable to Delta. That will work perfectly as a point to hook it in.

image

**Review by Maurukas — APPROVED** [review]
Perfect.

**Pull request merged**
