### PR TITLE
Adds plasmaman EVA suits to cargo

### PR DESCRIPTION
**Pull request by 81Denton**
:cl: Denton
add: Added a plasmaman EVA suit pack to cargo for 4000 bucks each.
/:cl:

Plasmaman EVA suits were just sitting around unused; I added them as a cargo pack. 1000 bucks more than the regular space suit pack since these have the fancy self-extinguish function.

### CODE REVIEW

**Comment by Kagus** [comment]
Not sure why people would use this over just throwing an emergency firesuit on, but hey... It's there, it might as well be on the cargo list.

**Comment by lolman360** [comment]
this is proper spaceproof, but the crate should probably be EVA idlocked because of this, like the other space suit crate.

**Comment by XDTM** [comment]
it's worth noting that any spaceproof suit also prevents plasmaman combustion, although they don't have self-extinguishers

**Comment by 81Denton** [comment]
Yeah, these just let you rock the plasmaman color scheme in space

**Review by Cyberboss — APPROVED** [review]

**Pull request merged**
