### PR TITLE
Fixes autobuild tgui github actions

### PR DESCRIPTION
**Pull request by Neotwr**
## About The Pull Request
https://github.com/tgstation/tgstation/pull/48122 broke that

### CODE REVIEW

**Comment by MCterra10** [comment]
Still doesn't fix it

**Comment by MCterra10** [comment]
The rebuild action as so far never worked a single time

**Comment by Neo-0** [comment]
@MCterra10 I tested and it works now

**Comment by actioninja** [comment]
I don't think this will work on live. The problem was that in some situation the changelog bot was building and pushing its pr before the tgui clone and rebuild finished. This would still have the same issue I belive.

**Comment by Neo-0** [comment]
Anyway this is probably better than it is now, I think we should test this

**Comment by actioninja** [comment]
can't really test without merging, fuck it.

**Comment by MCterra10** [comment]
The best option is to integrate changelog gen and tgui compiles into a single package and have them push either sequentially or in a single commit. I'm working on an all in one repo management solution, so I'll see how that turns out

**Comment by actioninja** [comment]
That's not exactly trivial though.

**Comment by MCterra10** [comment]
Eh, I've made good progress so far, mostly it's just dealing with the API. We already have code that does everything to work with, it's just a matter of packing everything into one program

**Comment by MCterra10** [comment]
but it will be java, so

**Comment by MCterra10** [comment]
so it works downstream, but not here because you have master set as a protected branch.

**Pull request merged**
