### PR TITLE
gbs now grants a sense of pride and accomplishment instead of 40 hours of toxin damage.

### PR DESCRIPTION
**Pull request by ghost**
When we released GBS, we got a lot of feedback. a lot of it positive, and a lot of it constructive. "I find it interesting that the admin only virus kills you with toxin damage before it gibs you, as it did with me and the roboticist last round. I ded, but I didn't ded with a gib. Two out of the five stages have a hilariously lethal amount of toxin damage, and the gibbing is way too slow." Hopefully, by removing the toxin damage, making the emotes a lot more obvious to what's happening, and finally delivering the gib a lot faster, I can deliver a sense of pride and accomplishment.

### CODE REVIEW

**Comment by Y0SH1M4S73R** [comment]
I was originally in favor of this PR, but OP wrote "satisfaction" instead of "accomplishment", so it gets a solid :-1: from me.

**Comment by Armhulen** [comment]
holy shit

**Comment by Armhulen** [comment]
hotfixed, thanks gamer.

**Comment by nicbn** [comment]
I was originally in favor of this PR, but OP wrote "toxin damage" instead of "pain and suffering", so it gets a solid 👎 from me.

**Comment by Armhulen** [comment]
image

**Comment by Armhulen** [comment]
lziman will kill me if i make that title any worse

**Pull request merged**
