### PR TITLE
Nerfs holodeck thunderdome suits

### PR DESCRIPTION
**Pull request by SmArtKar**
## About The Pull Request

Are you fucking sure that giving crew deathsquad-level armor in PUBLIC HOLODECK after AI overrides safety protocols is a good idea? I don't think so.

## Why It's Good For The Game

Deathsquad-level armor just lying in public is NOT good

## Changelog
:cl:
balance: Holodeck thunderdome armor now has 10 melee and bullet protection instead of deathsquad-tier armor
/:cl:

### CODE REVIEW

**Comment by Kylerace** [comment]
when i was testing this a few months ago, i was able to survive 7 pre-nerf shotgun slugs to the head. the thunderdome suits are way too overpowered

**Comment by SinfulBliss** [comment]
Never see them, like ever, but the nerf makes sense I guess.

**Comment by Kylerace** [comment]
> 
> Never see them, like ever, but the nerf makes sense. They were pretty funny though ngl.

https://www.youtube.com/watch?v=sSBJH3MnHVA&t
only time ive seen it, i know ive told at least two people about it

**Comment by Serxule** [comment]
wasnt thunderdome suits stronger than deathsquad?

**Comment by Serxule** [comment]
> only time ive seen it, i know ive told at least two people about it
slavik , korol, and seth were all tots and used it with ebows and eswords a while back

**Review by Mothblocks — APPROVED** [review]

**Comment by DatRatzor** [comment]
Literally the best counter to these mega op deathsquad armor sets is to turn holodeck safety on or kill the thing, which isnt that hard, possible in a couple different ways and takes a single bored assistant with a fuel tank. I'd be more surprised seeing anyone using them to gain huge advantage, because stripping them away of this gear is dirt easy and can be even done by accident. That means someone who uses this public trick should pay attention so their gear isn't "under threat" and have make sure the holodeck stays the way it is.

**Comment by MrDoomBringer** [comment]
i see people do this all the time, sad to see the funny godmode armor go

**Comment by Sparkezel** [comment]
This is why we can't have nice things

**Comment by Kylerace** [comment]
> Literally the best counter to these mega op deathsquad armor sets is to turn holodeck safety on or kill the thing, which isnt that hard, possible in a couple different ways and takes a single bored assistant with a fuel tank. I'd be more surprised seeing anyone using them to gain huge advantage, because stripping them away of this gear is dirt easy and can be even done by accident. That means someone who uses this public trick should pay attention so their gear isn't "under threat" and have make sure the holodeck stays the way it is.

Doesn't matter it's too strong stop malding about your gamer trick

**Comment by MrDoomBringer** [comment]
> DatRatzor commented 17 hours ago

hmm I build 4 r-walls around holodeck console within 80 seconds of roundstart then murderbone in dorms for the entire shift in my god armor

seems fun and intended

**Comment by Sparkezel** [comment]
> hmm I build 4 r-walls around holodeck console within 80 seconds of roundstart then murderbone in dorms for the entire shift in my god armor
> 
> seems fun and intended

You can also just kill the apc and same effect would be achieved

**Comment by ATH1909** [comment]
sad

**Comment by moocowswag** [comment]
Holoswords that come with thunderdome armor are safe tho right?

**Comment by Mothblocks** [comment]
yeah those are funny

**Pull request merged**
