### PR TITLE
Customizable sushi + cornmeal/quality oil manual creation

### PR DESCRIPTION
**Pull request by MidoriWroth**
## About The Pull Request

This pr mainly expands upon my previous sushi pr. I have received quite a few requests to be able to make custom sushi, and this will allow it.
This pr will also finally allow you to create quality oil and cornmeal yourself.

## Why It's Good For The Game

Custom sushi allows players to more customize the foods they create, and stops people from asking me about it constantly, haha.
Being able to make your own cornmeal and quality oil is a change I have wanted to see for a long time. Cornmeal is essentially just processed, dried corn, so there's no reason you shouldn't be able to make it yourself. Quality oil is a big one because it's extremely expensive to order (120 credits for 50 units!) and you cannot make it or get it anywhere else, making it hard to stockpile. I feel this is a reason many chefs do not try making lizard or mothic cuisine because simply getting the required ingredients is already difficult enough, let alone being expensive, and unless you want to spend 240 credits instead to expedite a bottle to you, then you are at cargo's mercy and need to wait for them. I just kind of winged it for the recipe, so if anyone else thinks of a better alternative, let me know. I might add olives as a plant in the future that you could grind to get the oil, but this will do until then.

## Changelog

:cl:
add: You can now make custom sushi. Use an ingredient on a seaweed sheet to start.
balance: Quality oil and cornmeal can now be manually created
/:cl:

### CODE REVIEW

**Comment by optimumtact** [comment]
you haven't really considered why quality oil is so expensive/hard to get in your justification for why it should be creatable.

**Comment by MidoriWroth** [comment]
There 'ya go. I don't know if it has like in-game lore or whatever but I don't see why you shouldn't be able to make it.

**Comment by optimumtact** [comment]
Oh, they responded to my post, better check to see what they said
very sour lemon being consumed

The point I was trying to get across is you need to look at existing uses and provide all the information so the maintainer looking to merge the PR can decide if there is a balance concern or not. 99% of the time if you're the person who looked/touched that code you're going to know more than everyone else so you need to lay out the data that lead to you concluding that the oil was too hard to get for the benefits it provided.

**Comment by MidoriWroth** [comment]
There! Hope that's better.

**Comment by PCPort** [comment]
WOOOOOHOOOOOOOOOO! CHEF MAINS REJOICE

**Comment by ilikesaying** [comment]
why not make Quality Oil be Frying Oil + Universal Enzyme (Catalyst), Frying Oil can be obtained from Soybeans and Universal Enzyme is fucking magic anyways

**Comment by MidoriWroth** [comment]
> 

I considered that, but I thought it should be somewhat difficult to make considering it seems to be a very high value prestigious product. Most kitchens spawn with a huge frying oil tank anyways.

**Comment by ilikesaying** [comment]
Water and Tomato Juice are both easily obtainable from the soda dispenser, Korta is easy, Black pepper is the only one that's not obtainable for free...

**Comment by MidoriWroth** [comment]
You can get black pepper from a biogenerator. Either way, making it somewhat complicated is the idea, without requiring things that are too outlandish or too easy to get.

**Comment by ilikesaying** [comment]
> You can get black pepper from a biogenerator. Either way, making it somewhat complicated is the idea, without requiring things that are too outlandish or too easy to get.

fuck.
yeah, making it complicated may seem nice, but the ingredients for the oil are kind of ridiculous and will make me scared that Gordon Ramsay will turn me into mincemeat

**Comment by MidoriWroth** [comment]
Yeah I gotcha. That's why I said I may pr growable olives in the future that can be dried then ground down into oil, eliminating this whole process.

**Comment by MidoriWroth** [comment]
> > You can get black pepper from a biogenerator. Either way, making it somewhat complicated is the idea, without requiring things that are too outlandish or too easy to get.
> 
> fuck. yeah, making it complicated may seem nice, but the ingredients for the oil are kind of ridiculous and will make me scared that Gordon Ramsay will turn me into mincemeat

Actually, screw it, I'm gonna make olives.

**Comment by MidoriWroth** [comment]
Gonna remake this PR from scratch.

**Pull request closed without merging**
