### PR TITLE
Adds a space ruin, inspired by all the fluke ops out there

### PR DESCRIPTION
**Pull request by MrMelbert**
## About The Pull Request

Adds a space ruin, the Abandoned / Old Infiltrator.

Simply, it's a Syndicate Infiltrator that's seen better days. The design is pulled from the OLD Infiltrator design (VERY SLIGHTLY updated stylistically). Some carp have made it their home. 

There is very little in the way of loot, as scavengers have picked it clean. Some medical supplies, tools, and a locked crate. One suit remains locked in the airlock.
Within the cockpit lies more notable items (Illegal technology and an equipped corpse), but getting in there is much harder, as the last pilot bolted themselves in before the power died. 

<Details>

<Summary>Picture within</Summary>

image

image

</Details>

## Why It's Good For The Game

More variety for deep space. 

## Changelog

:cl: Melbert
add: Somewhere, in deep space, a relic to every fluked nuclear operative mission drifts abandoned. 
/:cl:

### CODE REVIEW

**Comment by san7890** [comment]
should have a copy of fission mailed somewhere for epicness

**Comment by SomeoneYouProbablyKnow** [comment]
Cyenne extended family LORE

**Comment by VladinXXV** [comment]
I like it. It feels a little empty, though I guess that's the scravengers. Just tossing the idea out there, though: add an entrenching tool? (`/obj/item/trench_tool`) I don't feel it's an overly strong piece of equipment, but it's certainly interesting, and adds a little more "real nuke ops"-ness to it.

**Comment by Addust** [comment]
finally, spessman armour

**Review by Maurukas — APPROVED** [review]

**Pull request merged**
