### PR TITLE
Fixes slips

### LINKED ISSUE #28602: Stuns broke
Slipstuns only last a single second.
Lzimann asked if we noticed something weird about stuns so i am guessing it's related.
Server revision compiled on: 2017-06-19

The following pull requests are currently test merged:
#28580: 'Fix cid reconnect message not showing' by MrStonedOne

Based off origin/master commit: 9c9691

### PR DESCRIPTION
**Pull request by ChangelingRain**
Fixes #28602

These values are absolute bullshit frankly but hey, that's what you get for basing stun values of off Life() ticks

### CODE REVIEW

**Comment by Armhulen** [comment]
"""""""""""""""fix""""""""""""""""""

**Comment by KorPhaeron** [comment]
150 hours of testing

**Comment by Robustin** [comment]
IMO this whole refactor should account for the fact that 1 tick was usually less than 2 seconds, this feels like a flat stun buff when combined with the other PR.

**Comment by ChangelingRain** [comment]
All stuns were basically `input_value * 20 - rand(20, 0)`, thus the rework. Further stun tuning can happen after the freeze, once stun times are much less random.

**Review by Cyberboss — APPROVED** [review]

**Pull request merged**
