### PR TITLE
Fix 515 warnings from INVOKE_ASYNC and qdel experiment flag, treat warnings as errors in CI

### LINKED ISSUE #72681: GCd_at_time reports as unused on 515
https://github.com/tgstation/tgstation/blob/4d6eadabadec42779771aa8fb544df4841fc00e3/code/controllers/subsystem/garbage.dm#L176-L189

This is reported as an unused variable because `IS_DELETED` does not use `GCd_at_time` in 515. Could save this for free by doing something like:

```dm
#define SUPPRESS_UNUSED(name) if (UNLINT(FALSE)) { pass(name) }
```

### PR DESCRIPTION
**Pull request by Mothblocks**
Fixes #72681

### CODE REVIEW

**Comment by Mothblocks** [comment]
I committed that to the wrong branch but I guess I might as well do it all in one

**Comment by ZephyrTFA** [comment]
it works, they lied confidently

**Comment by Mothblocks** [comment]
Weird, did it compile out and influence the diagnostics? I'm actually impressed

**Comment by Mothblocks** [comment]
Wow it does

**Review by ZephyrTFA — APPROVED** [review]

**Pull request merged**
