### PR TITLE
If you're gonna rename a job, do it right!

### PR DESCRIPTION
**Pull request by Cyberboss**
#26813

### CODE REVIEW

**Comment by KorPhaeron** [comment]
Thanks

**Comment by Robustin** [comment]
>Curator
>Not Archivist
>Not Conservator

Disgusting

**Comment by KorPhaeron** [comment]
Archivist was actually my first choice I forget why I switched

**Comment by Iamgoofball** [comment]
Indie

**Comment by Iamgoofball** [comment]
Also speedmerge

**Comment by Iamgoofball** [comment]
As librarian can't spawn without this

**Comment by KorPhaeron** [comment]
@Iamgoofball 

That is not true

**Comment by Iamgoofball** [comment]
it makes you spawn on the title sscreen???

**Comment by KorPhaeron** [comment]
No it doesn't? It's been working on server all day

**Comment by Iamgoofball** [comment]
w h a t

fuck, i was lied to

**Comment by KorPhaeron** [comment]
Coiax made job landmarks each their own path so I was able to edit them without ruining everything

**Pull request merged**
