### PR TITLE
Removes meth explosion syringes

### PR DESCRIPTION
**Pull request by BeeSting12**
:cl: BeeSting12
balance: The meth explosion temperature has been raised.
/:cl:
Being shot and exploded in under five seconds in a relatively easy to make manner is not fun for anyone.

### CODE REVIEW

**Comment by pubby** [comment]
Update the comment.

**Comment by Armhulen** [comment]
git gud

**Comment by lordpidey** [comment]
I'd keep the second temperature where it is.  But I can see the argument for the first one.

Or is there some kinda flag we can put on the reaction to prevent it from happening inside of people's body?

**Comment by RandomMarine** [comment]
>Or is there some kinda flag we can put on the reaction to prevent it from happening inside of people's body?

Adding something like this seems like a better way to go.

**Comment by NewSta1** [comment]
I am against this, personally.

Meth explosion syringes aren't used or abused too often for them to be removed, and I believe they should stay.

**Comment by MoreRobustThanYou** [comment]
i ded plz nerf

**Review by Cyberboss — APPROVED** [review]

**Comment by KorPhaeron** [comment]
@Cyberboss 

Agreed

**Review by ChangelingRain — APPROVED** [review]

**Comment by Darkgenerallord** [comment]
The second reaction is the only one that actually matters. You more or less pre heat it to 299, shoot it, one tick passes and due to the human body temperature sitting at 300, it heats it to 300 and explodes.

**Comment by BeeSting12** [comment]
I believe I would have to update the wiki about this also. It wouldn't be good to see someone blowing up due to the wiki's bad instructions

**Comment by lordpidey** [comment]
@BeeSting12 

This makes the explosions more difficult to occur.

**Comment by BeeSting12** [comment]
I'm aware, but I don't want people heating it up too much either way.

**Comment by Ninja137** [comment]
It's an easily made, mass-produceable, spammable instant-death syringe powerful enough to blow people's limbs off. It literally serves zero purpose other than powergaming to a level that even I think is fairly fucking suspect, and you people know me. The only time it's ever used is by medbay powergamers to have an instant-kill option that they can spam, or by other people abusing it. It's honestly something that never should have existed as an option in the first place.

**Comment by optimumtact** [comment]
?

**Comment by Ninja137** [comment]
Meth explosion syringes. They were bullshit, removing them entirely is a good idea.

**Comment by lordpidey** [comment]
As the person who added meth explosions in the first place, this... this was not the intent.

**Pull request merged**
