### PR TITLE
Honkbots now cuff you (fixes honkbots' infinite loop)

### PR DESCRIPTION
**Pull request by JohnFulpWillard**
## About The Pull Request

Fixes Honkbot's infinite loops by letting Honkbots cuff you, allowing them to just use secbot's automated action.
Also makes honkbots call parent more times.

## Why It's Good For The Game

please god no more infinite loops
and people endlessly being honked isn't a good alternative either

## Changelog

:cl:
expansion: Honkbots now handcuff people, if you somehow manage to get caught by one.
fix: Honkbots now no longer spam you and break the game
/:cl:

### CODE REVIEW

**Comment by GlitchySoftware** [comment]
Based.

**Comment by ATH1909** [comment]
but I thought that clowns were bad at using handcuffs???

can you still set these to chainstun mode like you can with secbots?

**Comment by nianjiilical** [comment]
make them use pink fuzzy cuffs for optimal hilarity

**Comment by TheBonded** [comment]
> make them use pink fuzzy cuffs for optimal hilarity

As funny as that might be, I'm pretty sure that would be seen as fetish content. Might be better suited for skyrat though, they probably already have a pair of handcuffs in game just like that so it would be a pretty easy change.

**Comment by YakumoChen** [comment]
> > make them use pink fuzzy cuffs for optimal hilarity
> 
> As funny as that might be, I'm pretty sure that would be seen as fetish content. Might be better suited for skyrat though, they probably already have a pair of handcuffs in game just like that so it would be a pretty easy change.

(They do)

**Pull request merged**
