### PR TITLE
Engineering techweb node now requires basic tools

### LINKED ISSUE #41091: Advanced tools node doesn't require regular tools
This is inconsistent and doesn't make much sense for jaws and such to be researched while lathes can't print out basic tools...

### PR DESCRIPTION
**Pull request by ShizCalev**
Closes #41091

:cl: ShizCalev
tweak: Engineering techweb node now requires basic tools to be researched first.
/:cl:

Logical progression, doesn't make too much since to be able to lathe high cap powercells, rechargers, and circuitry if you can't even make a wrench or crowbar.

### CODE REVIEW

**Comment by Barhandar** [comment]
Make regular tools accessible by default instead of being a node reeeee, they're accessible by autolathe already

**Comment by evsey9** [comment]
imagine having to research something THAT YOU CAN ALREADY MAKE ROUNDSTART

**Review by Cyberboss — CHANGES_REQUESTED** [review]
Remove them from the autolathe until research is complete on it

**Review by Cyberboss — APPROVED** [review]

**Comment by Barhandar** [comment]
Autolathe cannot sync research, GG

**Pull request merged**
