### PR TITLE
Adds frogs

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
Sprites by WJ, sounds by Cuboos. You can find them in xenobio right now, but nowhere else.

:cl: Kor
add: Added frogs, with sprites by WJ and sounds by Cuboos.
/:cl:

### CODE REVIEW

**Review by Razharas — CHANGES_REQUESTED** [review]
> Adding the desgusting symbol of neo-nazi internet hatred and violence to our christian game

Horrible

**Comment by Chocobro** [comment]
:-1: this is a hate symbol

**Comment by WJohn** [comment]
Close enough to the picture tag right?

**Comment by ShadowDeath6** [comment]
do they ribbit constantly

**Comment by MMMiracles** [comment]
>HUUUUUUUUUUUU

bikehorn 2.0

**Comment by Supermichael777** [comment]
>Those sounds

FUCK NO USE REAL FROG SOUNDS

**Review by Supermichael777 — CHANGES_REQUESTED** [review]
CHANGE SOUNDS

**Comment by Durkel** [comment]
Holy shit that fucking sound, did you record yourself trying to take a shit or what?

**Comment by KorPhaeron** [comment]
Well that was fun

**Comment by KorPhaeron** [comment]
@Cuboos 

The HUUUUUUUU sounds got pretty loud and distorted

**Comment by PKPenguin321** [comment]
Reopen please

**Comment by ShadowDeath6** [comment]
this is a pretty ok PR can you just remove the tortured screams of the damned and replace them with actual frog sounds

**Comment by KorPhaeron** [comment]
Someone get me frog sounds then

**Comment by PKPenguin321** [comment]
No keep the reeees

Or maybe get real frog sounds but it also reeees now and then

**Comment by Cuboos** [comment]
you guys must have really shitty headphones or something because my sounds have never hurt my ears.

**Comment by lordpidey** [comment]
Why the hell is this marked DNM?  *clicks*  The sounds?  They can't be that bad... *click*

My entire neighborhood thinks I've kidnapped a special needs child.

**Comment by Cuboos** [comment]
https://dl.dropboxusercontent.com/u/9654207/Reee.ogg
https://dl.dropboxusercontent.com/u/9654207/Huuu.ogg

I lowered the volume on the sounds.

**Comment by SkowronX** [comment]
RRRRRREEEEEEEEEEE

**Comment by ShadowDeath6** [comment]
I'd prefer the screeches of actual frogs than some guy trying to imitate them, but I guess memes are memes

**Comment by Anonmare** [comment]
@ShadowDeath6 https://www.youtube.com/watch?v=tYKPdNvH800

**Comment by CrAzYPiLoT-SS13** [comment]
I thought /tg/ was supposed to be neutral in the elections :^)

**Review by Shadowlight213 — APPROVED** [review]

**Comment by Cuboos** [comment]
I will live on, as a meme.

**Comment by KorPhaeron** [comment]
The DNM tag fails to stop citrus once again

**Pull request merged**
