### PR TITLE
Watcher's Wing No Longer Perma-Disarms

### LINKED ISSUE #41655: Proto Kinetic Crushers can delay attacks basically infinitely
## Reproduction:

https://github.com/tgstation/tgstation/blob/2e227d11ee7b375bba8abb023e4aa8fc89d4f23a/code/modules/mining/equipment/kinetic_crusher.dm#L236

This whole section should be setting ranged_cooldown not ranged_cooldown_time. It's setting the recovery cooldown time for some mobs to ridiculous amounts. For example.

https://github.com/tgstation/tgstation/blob/17dfb07f99612b6d7c92d928ec22694ef20eb328/code/modules/mob/living/simple_animal/hostile/megafauna/drake.dm#L108

Literally just hit anything with the crusher with a watcher wing and it will do this. Except certain mobs that don't use ranged_cooldown_time like the colossus. Every other megafauna it just stops their attacks for minutes though.

### PR DESCRIPTION
**Pull request by ExcessiveUseOfCobblestone**
:cl: Lavalandby
bugfix: Watcher's Wing no longer Perma-Disarms certain mobs
/:cl:

> 1-line fix
> puts an issue report anyways

scared?

fixes #41655

### CODE REVIEW

**Comment by subject217** [comment]
150 hours

**Comment by Barhandar** [comment]
I greatly approve of this fix. It's exactly as fixing as the previous "fix" of the matter, as in, it makes the disabler period accumulate without actually making said period reasonable.

**Comment by ExcessiveUseOfCobblestone** [comment]
> test stuff before you PR it

heh

**Comment by ExcessiveUseOfCobblestone** [comment]
this will work now that I have actually read the code lol.

**Comment by ExcessiveUseOfCobblestone** [comment]
also this is dumb depending on what the units are. If it's seconds lol.

**Comment by Barhandar** [comment]
It's in deciseconds, like literally everything else in byond.

**Comment by ExcessiveUseOfCobblestone** [comment]
um some things are shifted in calculations to be in seconds sw33ti3

but that's good to know

**Comment by Whoneedspacee** [comment]
it uses world.time so it's in deciseconds

also 👍 good to go

**Review by SpaceManiac — APPROVED** [review]

**Pull request merged**
