### PR TITLE
Regal Queen Sprite (by Onule)

### PR DESCRIPTION
**Pull request by axietheaxolotl**
## About The Pull Request

adds a one in one hundred chance for the regular rat sprite to be replaced with a regal rat queen sprite.

wow so wacky, it seems github didn't want to embed my screenshots. so weird!
## Why It's Good For The Game

some more random happenstance is a good thing :)
## Changelog
:cl: axietheaxolotl
imageadd: Adds a new, random, alternate sprite for the regal rat antag.
/:cl:

### CODE REVIEW

**Review by Imaginos16 — APPROVED** [review]
What a fun little PR!

**Review by Jacquerel — APPROVED** [review]

**Comment by Jolly-66** [comment]
20f5d3b6fcc849732c071f478635e570_c5_720x720

**Review by Time-Green — APPROVED** [review]

**Comment by OrionTheFox** [comment]
This cant be right... Icondiffbot shows---
No, it must just be a bot error. I'm sure the PR is fine!

**Review by Fikou — CHANGES_REQUESTED** [review]
Die

**Review by Twaticus — APPROVED** [review]
unironically

**Comment by ArcaneMusic** [comment]
Might I suggest absolutely not?

**Comment by Rex9001** [comment]
What.....What does it look like?

**Comment by ArcaneMusic** [comment]
> What.....What does it look like?

image

**Comment by axietheaxolotl** [comment]
you invalidate your argument by posting a twitter screenshot.

**Comment by Mey-Ha-Zah** [comment]
Here's an argument, you can't ignore, Who gave you permission to use that sprite?

**Review by dragomagol — CHANGES_REQUESTED** [review]
Perish

**Comment by fishingsman** [comment]
consider harming yourself

**Comment by Imaginos16** [comment]
Gonna have to add a DNM until an issue is resolved regarding this PR, which also requires Twaticus' presence.

**Comment by Xkallubar** [comment]
Revive this pr cowards

**Pull request closed without merging**
