### PR TITLE
The Throwing Arm quirk now makes you better at basketball

### PR DESCRIPTION
**Pull request by FernandoJ8**
## About The Pull Request

Having the throwing arm quirk now significantly increases your chance to land shots on a basketball hoop.
## Why It's Good For The Game

Gives the throwing arm quirk more fun interactions, which is neat. This quirk has a lot of potential.
~~It's frankly a crime that this wasn't the case to begin with~~
## Changelog
:cl:
add: Having the Throwing Arm quirk increases your chances to land shoots on a basketball hoop
/:cl:

### CODE REVIEW

**Comment by Jacquerel** [comment]
This actually *was* the case to begin with but was vetoed by maintainers at the time who wanted to preserve the sanctity of basketball, which all know is an equal opportunities sport.

**Comment by FernandoJ8** [comment]
> This actually _was_ the case to begin with but was vetoed by maintainers at the time who wanted to preserve the sanctity of basketball, which all know is an equal opportunities sport.

My disappointment is immeasurable, and my day is ruined.
I will not close this *yet* in hopes that it is no longer non-negotiable.

**Comment by Ghommie** [comment]
> This actually _was_ the case to begin with but was vetoed by maintainers at the time who wanted to preserve the sanctity of basketball, which all know is an equal opportunities sport.

Respect for everything and the basketball minigame aside, that's... too staid of a motive when it's just a friendly match between players who just want to have some harmless fun. Let them decide if they want to give one party or another an advantage or penalty.

**Comment by EricZilla** [comment]
It's a 7 point quirk I think that's an appropriate cost to be good at basketball

**Comment by FernandoJ8** [comment]
> It's a 7 point quirk I think that's an appropriate cost to be good at basketball, but maybe this is too high?

I'm entirely willing to tweak the value, assuming the idea isn't turned down.

**Comment by CCC23** [comment]
Help power gamers are beating me in basketball again admains ples nerf

**Comment by timothymtorres** [comment]
No

**Pull request closed without merging**
