### PR TITLE
Changes Shield wall generator Access to Engine instead of Teleporter

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request

Changes the required access of the shield wall generators to engine access just like shield generators instead of teleporter

## Why It's Good For The Game

Makes Engineers able to use shield wall generators, not just RD and CE

## Changelog
:cl:
balance: changed required acces of shield wall generators from Teleporter to Engine
/:cl:

### CODE REVIEW

**Comment by Fabian272** [comment]
could be code change or balance change tbh not really sure

**Comment by D4C-420** [comment]
I'm pretty sure the reason they have teleporter access is because none of them actually spawn in engi they get field generators. The only one's which spawn are in xenobio (for the xeno pen) and in the teleporter room itself.  Also I'm pretty sure this is a balance change.

**Comment by ATH1909** [comment]
Would it be possible to make them accept either sci access or engi access?

**Comment by D4C-420** [comment]
> Would it be possible to make them accept either sci access or engi access, then? Also, are you sure that the ones in XB require access to use? I seem to vaguely recall toggling them on and off without engi access in the past, but maybe I was just playing as cyborg or captain or something whenever I did that.


I'm pretty sure the ones in xenobio require sci access cause I know a few rounds where a regular old scientist "accidently" let out the xeno resulting in me having to pop off all the orange extracts.

**Comment by Fabian272** [comment]
> > Would it be possible to make them accept either sci access or engi access, then? Also, are you sure that the ones in XB require access to use? I seem to vaguely recall toggling them on and off without engi access in the past, but maybe I was just playing as cyborg or captain or something whenever I did that.
> 
> I'm pretty sure the ones in xenobio require sci access cause I know a few rounds where a regular old scientist "accidently" let out the xeno resulting in me having to pop off all the orange extracts.

the ones spawning in xenobiology require xenobio access as of right now



> I'm pretty sure the reason they have teleporter access is because none of them actually spawn in engi they get field generators. The only one's which spawn are in xenobio (for the xeno pen) and in the teleporter room itself. Also I'm pretty sure this is a balance change.

there are some on delta, that spawn in a small room in maint, thats attached to engi

**Comment by Fabian272** [comment]
Right, I've changed it to make shield wall gens require Engine / Teleporter access, and changed it from code to balance

**Pull request closed without merging**
