### PR TITLE
nerfs c20r reworks m90gl adds mgl

### PR DESCRIPTION
**Pull request by LanCartwright**
C20r no longer has stamina damage.
Damage reduced from 25 to 20.

M90gl now has stamina damage.
Damage reduced from 35 to 25.
34 stamina damage per bullet.

Adds 6B40 MGL
6 chambers.
40mm (can add 40mm Slug, 40mm buckshot, 40mm rubbers, ect)
Complete with sprites.

### CODE REVIEW

**Comment by Steelpoint** [comment]
So you nerfed the C20r from 20 damage, to 20 damage?

So what this PR does is really make the C20r even more useless, while nerfing the M90 to be slightly less useful, but considering its a three shot stun your target's still going to be dead after your 3rd burst.

Now there's no reason to ever buy a C20r.

The grenade launcher is a nice addition so :+1: on that part. But I think your C20/M90 balancing needs work.

**Comment by Steelpoint** [comment]
Also I thought the problem was that the C20r was too underpowered and that the M90 was too powerful? This dosn't really address the issue at all and infact further compounds it.

**Comment by LanCartwright** [comment]
I swear c20r was 25 damage. oh well.

stamina damage was cancer anyway

**Comment by Steelpoint** [comment]
I agree on that. I just feel this PR makes C20r's worthless.

While I don't want to shill but this is why in my PR I simply removed the M90gl from the Uplink menu and buffed the C20r's damage slightly to be a 4 hit crit. I kept the C20r mainly due to it being the most iconic weapon for the Ops.

**Comment by CosmicScientist** [comment]
25 brute + 34 stam?
So if you get hit by at least two of three of the burst bullets, you're at... 50 brute and 64 stam... so you're going to be on the floor and even if not hit by the third shot, you'll be killed by the next three shots because you can't move?

**Comment by KorPhaeron** [comment]
I like steelpoints better right now

**Comment by MMMiracles** [comment]
I really don't see the point of the M90 if the grenade launcher is going to become a thing since the C20 already has the job as a standard all-around gun, with things like the bulldog / SAW being for more of the pure damage output. 

Ops need more variety in their arsenal past "bullet-shooter with different damange/bursts"

**Comment by LanCartwright** [comment]
would you like me to change the stamina damage to 18 instead.

the m90 is literally a more premium c20r.

**Comment by WJohn** [comment]
This is the third PR on these two god damn.

**Comment by Lumipharon** [comment]
reeeeee, how many times to I have to shill the fact that the m-90 has NEVER BEEN AN ISSUE, until ops got access to fuckhuge amounts of tc's, and the prices of guns got slashed in half or something?

**Comment by Steelpoint** [comment]
I still think the Grenade Launcher aspect of this PR is worth PRing in its own right and I encourage that.

Also odds are we'll be revisting the whole C20r/M90 issue later down the line.

**Comment by LanCartwright** [comment]
I'll make a PR tonight with 40mm slugs and 40mm buckshot.

You'll best be scared of that.

**Pull request closed without merging**
