### PR TITLE
RPD ui improvements

### PR DESCRIPTION
**Pull request by duncathan**
:cl:
add: The RPD has a shiny new UI!
add: The RPD can now paint pipes as it lays them, for quicker piping projects.
/:cl:

image
The one loss is that the UI doesn't have the actual colored buttons like the old one did. If anyone knows of a way to implement that I'm all ears.

### CODE REVIEW

**Comment by Supermichael777** [comment]
Finally

**Comment by epochayur** [comment]
great PR

**Comment by CPTANT** [comment]
Ohw one thing that I would like to see is merging the Bend disposals pipes and straight disposals pipes under one category like is the case with atmos pipes.

**Comment by duncathan** [comment]
That is already the case.

**Comment by CPTANT** [comment]
Really? Since when?

**Comment by duncathan** [comment]
My guess is @ACCount12's disposal pipe rework.

**Comment by ACCount12** [comment]
Yep, that was me in #32435.

**Comment by MoreRobustThanYou** [comment]
Make the color circles their own sprites and copy the way that clockwork slabs showed components pre-rework?

**Comment by duncathan** [comment]
If it were just the circles I'd do that but I don't want them to clash against the green "selected" color. The current rpd has custom css to style them when selected and with tgui I'm not sure how that can be done. It probably can be done tho in which case I'll gladly make it happen

**Pull request merged**
