### PR TITLE
[FUN REMOVAL] Makes fire not able to become ice.

### PR DESCRIPTION
**Pull request by silicons**
:3c

### CODE REVIEW

**Comment by evsey9** [comment]
I want my frozen fire

**Comment by Ausops** [comment]
you'll remove this fun when hell stops freezing over

**Comment by Iamgoofball** [comment]
:-1:

someone please close this

**Comment by FantasticFwoosh** [comment]
Our ice/temprature mechanics are woefully un-maintained apart from opportunistic memes anyway

**Comment by Militaires** [comment]
shit pr

**Comment by Kromgar** [comment]
👍

**Comment by BeeSting12** [comment]
remove freon when

**Comment by Bawhoppen** [comment]
freon is good but this feature was a bit too memey

**Comment by banthebantz** [comment]
revert this

**Comment by duncathan** [comment]
>[15:35] (Pirou) 541b1567 Dunc|Mobile: <Iamgoofball> Freon is incredibly powerful magicgas like Plasma is, so the ability to freeze anything including fire is essential

this is the reason goof gave not to merge this, so I'm glad it was merged

**Pull request merged**
