### PR TITLE
Holster upgrade, badassery for everyone

### PR DESCRIPTION
**Pull request by DrDiasyl**
## About The Pull Request
Holsters now can be attached to _almost_ any clothing in the suit slot (jackets, hazard vests, etc.)

Holsters now can hold Captain Antique gun and HoS gun (they are designed to look like handguns, are normal-sized and can be fitted in the backpack which is more convenient than a holster)

SecTech now has 4 energy holsters (which can only house medium-sized energy/laser weaponry) in the premium section.
## Why It's Good For The Game
Holsters being possible to attach to the suits makes them more convenient to use for those who have their belt slot occupied and don't have armour while still wanting to have a badass holster. It won't be a storage abuse as it is still more convenient and stealthy to keep guns in the backpack (holsters can only hold normal-sized guns).

Captain Antique gun and HoS gun were the only normal-sized guns which were left over from the holsters. Now Captains and HoSs can spin their cool guns in their hands.

SecTech having holsters (can only house 1 gun) let Security more easier access to more badass gear if they really want to. It won't change a lot as they would've kept their gun on the armour anyway (which holster can be clipped on).
## Changelog
:cl: DrDiasyl aka DrTuxedo
balance: Holsters can now be clipped to any suit, and house Captain antique gun and HoS gun. You now can buy holsters from the SecTech premium section.
/:cl:

### CODE REVIEW

**Comment by DrDiasyl** [comment]
If you don't know, you can make holsters with leather (leather can be acquired from the BioReactor at the Botany)

**Comment by mc-oofert** [comment]
storage creep

**Comment by DrDiasyl** [comment]
> storage creep

This was already addressed in the PR body.

**Comment by GuillaumePrata** [comment]
With how our system works (If it didn't change or I'm being stupid) adding an item to the `allowed_list` of the base suit will only carry over to clothing that doesn't have their own `allowed_list`
So this won't work for hazard vests or jackets as they have their own `allowed_list` which will overide the base list.

You can make it work by using some `allowed += list(XYZ`` if you want an example, it is how the each wintercoat avoids having their custom list overide the base wintercoat one.

**Comment by mc-oofert** [comment]
> With how our system works

thats how DM works smartass

**Comment by DaydreamIQ** [comment]
Does the syndicate holster do this as well? I've never see that thing used ever.

**Comment by optimumtact** [comment]
> > storage creep
> 
> This was already addressed in the PR body.

you didn't address it, you brushed it off.

**Comment by optimumtact** [comment]
wrong button

**Comment by DrDiasyl** [comment]
> Does the syndicate holster do this as well? I've never see that thing used ever.

It should, as I have the added the parent holster object.

**Comment by SyncIt21** [comment]
This should be labeled as balance not qol

**Comment by DrDiasyl** [comment]
Holsters are pretty weak objects to have a huge impact in the game, hence this is not a Balance change.

**Comment by itseasytosee** [comment]
> Holsters are pretty weak objects to have a huge impact in the game, hence this is not a Balance change.

You have not read the guide for what quality of life is. This is a balance change, and gun storage is a very notable element of inventory management. This is because guns take up the most valuable inventory slots, being belt, chest, and suit storage.

INCREASING the utility of holsters INCREASES the amount of guns people can carry and DECREASES the cost for carrying guns.

**Comment by itseasytosee** [comment]
> Does the syndicate holster do this as well? I've never see that thing used ever.

Its surprisingly one of the most bought items, but that's also because its piss cheap.

**Comment by DrDiasyl** [comment]
> > Holsters are pretty weak objects to have a huge impact in the game, hence this is not a Balance change.
> 
> You have not read the guide for what quality of life is. This is a balance change, and gun storage is a very notable element of inventory management. This is because guns take up the most valuable inventory slots, being belt, chest, and suit storage.
> 
> INCREASING the utility of holsters INCREASES the amount of guns people can carry and DECREASES the cost for carrying guns.

Holsters can only hold medium-sized guns (beside nukie holster). As such you can just put the gun into your backpack if you really need to, it will take some space but not a lot.

Holsters are mostly just a badassery accessory.

**Comment by DrDiasyl** [comment]
Also just for your information, holsters can only be put on belt or suit storage slot. So you're STILL TAKING UP A "IMPORTANT SLOT" as you named suit storage and belt important slots.

**Comment by Thelolswat** [comment]
I think the problem is putting a holster on a piece of clothing that wouldnt normally be able to hold a gun, like most non-armors. However, if your armor cant hold a gun its probably horrible armor anyway so being able to hold an extra normal sized gun while wearing a leather jacket or something doesnt seem like a big deal. Its not like being able to wear something like captains carapace or HOS trenchcoat AND hold an extra gun or something

Idc what has to happen though this is so cool and is a nice QoL

**Review by ninjanomnom — APPROVED** [review]

**Comment by drIcepop** [comment]
Finally I can look good in my captain's parade jacket and have a gun

**Pull request merged**
