### PR TITLE
Major cult changes

### PR DESCRIPTION
**Pull request by optimumtact**
Copy of #11436

The current code for runes is god-awful. Like, seriously terrible. This PR aims to fix that. Rather than having every rune effect defined in a single attack_hand proc, this PR will separate the runes into subtypes, which supports for more modular runes as well as cleans up the code.

It also separates invocation into a two different procs. The first of these will determine if the rune can be invoked; if that passes, the second will cause the rune's effects. There is also a third proc that will cause effects if the rune fails to invoke.

Research words have been removed, and all runes are now available from the start of the round. This is highly subject to change once some feedback is in from actual cult rounds.

Miscellaneous tweaks:

```
Blood boil runes now explode when used
Convert runes can now work solo, but take time
Armor runes now only provide the basic armor set
Tomes now do a static 15 burn damage and play a sound
If the Escape objective is rolled, the amount of people that must escape will scale with the round population to a factor of 5 (i.e. 50 players = 10 cultists)
```

### CODE REVIEW

**Comment by Xhuis** [comment]
WHOSE PULL REQUEST IS WHOSE REEEEEEEEEEEEEEEEEEEEEEE

**Comment by optimumtact** [comment]
Man that was dank

**Comment by Anonus** [comment]
WHO WHAT WHEN WHERE REEEEEEEEEEEEEEEEE

**Comment by optimumtact** [comment]
This is just a squashed version of Xhuis's work without 20 million commits, phil235 squashed it, I just reauthored it so the author was correctly set as Xhuis

**Pull request merged**
