### PR TITLE
Resprites changeling abilities and weapons

### PR DESCRIPTION
**Pull request by MelokG000**
## About The Pull Request

This PR resprites changeling powers buttons and weapons

Changelingus

Sorry for quality, ClipChamp fucked it
## Why It's Good For The Game

Old changeling sprites look old and boring, we thought they should get an update
## Changelog
:cl: MelokGleb and KREKS
image: changed changeling powers and items
/:cl:

### CODE REVIEW

**Comment by Admiral-Gigaton** [comment]
Foamblade good? What about xenobio arm/nightmare armblade? This affects those, right? Didn't check code

**Comment by EricZilla** [comment]
While I like the production value of the gif, you also gotta post the images in the PR.

Based on what I saw in discord though they look awesome great work

**Comment by EuclidianGeometer** [comment]
these are undoutebly far better sprites than the old ones, and i'm glad we're getting them. The icons in particular i have basically no issue with, but i have a few critiques.

1. They're just too clean. while normally that's good the changeling is like, a fucked up flesh abomination, and these are very parseable as huge flesh muscles. Not the end of the world, but i liked how the old ones have bits that trail off and weird tendrils that make it less 1-1 a muscle.

2. The armblade looks incorrect for nightmare now, nightmare armblade might need it's own sprite now.

otherwise these are super good, imo.

**Comment by Jacquerel** [comment]
These are real good but as I said on Discord I think making everything entirely out of the same shades of red is a missed opportunity when you could have some pink or purples or yellows mixed in for veins or muscles or bones or weird glands or what have you
Flesh isn't _just_ red

**Comment by SomeoneYouProbablyKnow** [comment]
Vogue gif. Solid sprites, remind me more of the "prototype" game than "the thing" but pur changeling mechanics are not that "the thing" to begin with so that fine with me. Kinda opens up space for new a fleshy eldrich horror monster thing.

**Comment by Admiral-Gigaton** [comment]
fr we need a carrion antag
image
its a reverse horror game about escaping a facility as a giant flesh blob

**Review by Wallemations — APPROVED** [review]
I like the sprites but why did you put a fast gif in your PR instead of just putting screenshots/the pngs themselves

**Comment by EuclidianGeometer** [comment]
> > these are undoutebly far better sprites than the old ones, and i'm glad we're getting them. The icons in particular i have basically no issue with, but i have a few critiques.
> > 
> > 1. They're just too clean. while normally that's good the changeling is like, a fucked up flesh abomination, and these are very parseable as huge flesh muscles. Not the end of the world, but i liked how the old ones have bits that trail off and weird tendrils that make it less 1-1 a muscle.
> > 2. The armblade looks incorrect for nightmare now, nightmare armblade might need it's own sprite now.
> > 
> > otherwise these are super good, imo.
> 
> both of us (me and KREKS) dont know how to code, so we cant change sprites for nightmare blade, because it uses changeling sprite

I'm sure someone would be happy to help with the code end of things if you ask in the discord or the like.

**Comment by EricZilla** [comment]
I wouldn't worry bout the light eater, but it's actually pretty simple to add a new icon state

**Comment by mc-oofert** [comment]
i think these sprites arent grotesque enough and the blade is kinda a downgrade

**Comment by anclandor** [comment]
I think it would be nice for the shield to be more boney.  Not a great shield if it's just made out of flesh

**Comment by zeroisthebiggay** [comment]
Fleshmend looks way less immediately visually telling than a `BIG RED MEDICAL CROSS`, it's a human with a couple of green pluses floating around his head. I think a `BIG GREEN MEDICAL CROSS` would simultaneously convey the idea immediately during an emergency while also not being a war crime.

Same goes with adrenals. The inlaid lightning bolt isn't really visible at all if you have less than perfect vision. I think making the lightning bolt gold and making it overlay the heart rather than inlaying it would be better. The heart kind of gives me the idea it's a medical ability versus a pop up out of stuns button.

Very minor gripe but strained muscles should really be a leg instead of an arm. It does fuckall to your arms. It'd really ought to be strained legs to be completely and utterly honest.

**Comment by Wallemations** [comment]
You've still got merge conflicts

**Comment by Jacquerel** [comment]
I will happily merge this as soon as the conflicts are resolved (might have to ping me so I notice) but you have to do that first.

**Comment by Wallemations** [comment]
> I will happily merge this as soon as the conflicts are resolved (might have to ping me so I notice) but you have to do that first.

You reminded me I forgot to do this

**Review by Wallemations — APPROVED** [review]

**Pull request closed without merging**
