### PR TITLE
Adding three units of *chemical im slapping in soon* to a plant will reduce the amount of reagents it spawns with (math inside, WIP)

### PR DESCRIPTION
**Pull request by ma44**
:cl: ma44
add: The Centcomm in your sector has reported that adding three units of *wip thingy* to a plant will reduce the amount of reagents it produces. 
/:cl:

**wip please don't kill me, bad code ahead**

[why]: # Some plants produce a lot of reagents that are unnecessary in scenarios like combining chemicals. This is a pr that is meant to address this issue 

## Maths

Each three untis of mutagen will decrease the amount of reagents by 5 at 100 potency, 2.5 at 50 and 1 at 20.

### CODE REVIEW

**Comment by Jordie0608** [comment]
>WIP PR for a chemical so WIP it doesn't even exist yet
Why would you even open this.

**Comment by fludd12** [comment]
@Jordie0608 I am assuming the chemical itself will be one that already exists, and they're just having trouble finding said chemical.

I suggest capsacian or sulfuric acid, since both of these chemicals can be obtained through botany, and both are known for their volatility.

**Comment by ExcessiveUseOfCobblestone** [comment]
What is the mechanical use for this in more easy to read terms?

**Comment by ma44** [comment]
@ExcessiveUseOfCobblestone Less waste products in mixing, as some reagent ratios may give much more then you need

**Comment by XDTM** [comment]
Can't you just make a lower potency plant instead of making a special interaction to get less chems

**Pull request closed without merging**
