### PR TITLE
Refactors toolspeed to be a multiplier instead of a divisor

### PR DESCRIPTION
**Pull request by ChangelingRain**
bluh bluh easy as fuck

### CODE REVIEW

**Comment by RemieRichards** [comment]
Thank god

**Comment by KorPhaeron** [comment]
Kind of  confusing as far as adding times go that the "default" speed is going to be time x 2 or 3 what the number in the dm is

**Comment by ChangelingRain** [comment]
?confusing?
it's just a multiplier

**Comment by KorPhaeron** [comment]
Oh nevermind I misread it

**Comment by Supermichael777** [comment]
don't fractions get rounded down?

**Comment by RemieRichards** [comment]
@Supermichael777 only for indices.

**Pull request merged**
