### PR TITLE
Fixes NTNet Transmitters not working

### PR DESCRIPTION
**Pull request by SmArtKar**
## About The Pull Request

I did an oopsie

## Changelog
:cl:
fix: NTNet Transmitter now works
/:cl:

### CODE REVIEW

**Comment by SmArtKar** [comment]
nogbp this or something, it's my mistake

**Comment by PrefabQuasar** [comment]
is it just me, or are NTNET components still not working? the receiver now gets triggered properly, but both data package values still show as null.

**Comment by Gurkenglas** [comment]
Doesn't get triggered properly for me - just every time the receiver changes input parameters. Also, receiver and transmitter component printer entries are switched around. WireCarp says no packets get sent.

**Comment by Mothblocks** [comment]
are you guys sure the server is up to date because they have to manually do that now

**Comment by Gurkenglas** [comment]
"NTNet Transmitter now works" was in the manuel changelog

**Pull request merged**
