### PR TITLE
Bloodbrothers now cost less threat

### PR DESCRIPTION
**Pull request by Kaffe-work**
## About The Pull Request
Bloodbrothers now cost 10 and scaling 10 threat instead of 15, to put in line with traitors

## Why It's Good For The Game

Bloodbrothers are less threatening to the order of the station than, at least in my opinion, regular traitors. This is because they have no external tools to cause havoc with if they desire to murderbone, and are to some extent suggested to work as a team to accomplish goals instead of go on a rampage. This results in less chaos on the station, despite there being two antags that work in unison. They also have no way of identifying regular traitors either, and this prevents larger cooperation that may be more chaos promoting to the station.

Furthermore, regular traitors have tools to get a companion if they desire such, in the way of hypnoflash, AI upload board and Emag. 

## Changelog
:cl:IradT
balance: Blood brothers now cost 10 threat instead of 15
/:cl:

### CODE REVIEW

**Comment by Dorsisdwarf** [comment]
Wasnt their price increased because the dynamic mode picked nothing but blood brothers because they were so cheap?

**Comment by EdgeLordExe** [comment]
blood brothers are bad, dont make them more common, literally noone wants to play them. Keep em as they are.

**Comment by Kaffe-work** [comment]
> blood brothers are bad, dont make them more common, literally noone wants to play them. Keep em as they are.

hmm, that is the issue im trying to fix - but i realize the problem here.

If they are made cheaper we will see more of them, made more expensive they will "steal" threat from a high-threat round. eck!

**Comment by Doosteroni** [comment]
Seems bbs as a whole need a revamp

**Comment by Kaffe-work** [comment]
> Seems bbs as a whole need a revamp

Agree - perhaps they could have a different uplink? The fact that they got no tools at all makes them boring as fuck to play.

**Comment by Angustmeta** [comment]
Just bring back BB-hud so I don't need to be paranoid about accidentally attacking my BB. They don't need an uplink since there is plenty of crew content to antag with. But it could get less weight.

**Comment by Fhaxaris** [comment]
> If they are made cheaper we will see more of them, made more expensive they will "steal" threat from a high-threat round. eck, this is some fucking catch 22 shit.

decrease BB weight then? IIRC it makes things appear more/less often

**Comment by tmtmtl30** [comment]
yeah that would do it i think

**Comment by Taylorkills2** [comment]
Threat needs to be decreased too, it commonly costs 45 threat, which is ridiculous when traitors rolls once for 10 threat producing 4-6 traitors.

**Comment by Kaffe-work** [comment]
I'll look into the weight; but there is an issue here too, it doesn't want to roll for more than 3 rulesets (if I'm reading this right)

**Comment by kriskog** [comment]
What you are doing here does nothing, since the cost is already overridden in the on-server configs. Blood brothers was found to be spawning too often while not being very interesting and contributing little to the round.

**Comment by Kaffe-work** [comment]
> What you are doing here does nothing, since the cost is already overridden in the on-server configs. Blood brothers was found to be spawning too often while not being very interesting and contributing little to the round.

Yeah, i see the problem. Gonna close this for now, but i belive that there is still an issue where the threat is stolen with shitty bloodbrothers. idealy, they should cost less, don't take ruleset and roll less often.

**Pull request closed without merging**
