### PR TITLE
Crates and bountes are now defined by crate's value and paygrades. Civilian bounty payout is higher and uncheesable.

### PR DESCRIPTION
**Pull request by ArcaneMusic**
Merry Christmas from the Arconomy Man. 🎄 🎁 ⛄ 

## About The Pull Request

Does a value-wise refactor of crates and bounties in order to scale the value of these imports and exports to the value of crate exports (500 credits each). Then, I have adjusted the value of crate exports to 200 credits down from 500 to place the most standard unit of profit within cargo to a scale within that of roundstart paygrades currently on station. (350-1400 credits). 

This effectively balances one of the biggest disparities left within the in-game economy, which is that cargo's price scales have really never been re-balanced with the considerations of on station prices, and have been still to the same scale as when they were based on cargo points 3 years ago. While admittedly some prices in vendors were scale to those original cargo values, so many of them weren't that it warranted a massive rebalance PR in order to places the scale of these items within an appropriate range of their intended user's cost values.

Now, this means that the value of most crates on station are within the scale that cargo is now receiving 2.5 free crates every payday, in addition to the value they gain from doing bounties, with other departments getting 5 crates in their budgets, albeit that resource pool can only be used exclusively for imports as it stands, but more or less it places their buying power on par with each other as cargo can consistently pull additional profit during the shift should they choose to.

This also keeps the proportional value of most bounties the same, while still enabling the payout to crewmembers to be reasonable to their own department. In tilting this scale downwards, it also means that it's reasonable to give crewmembers a larger chunk than 10% for their exports, based on gratuitously provided feedback from players, so the 10% payout has been increased to a 30% increase. 
Eg: As an assistant, you collect a civilian bounty for 3 monkey cubes, with a payout of 800 credits for cargo. For the assistant, they'd be paid 240 credits for that. With the value of what's left over, in the new scale, that's enough for most of the cheaper style crates on-station, like carpet crates, janitorial supplies, cytology equipment, etc. . A reasonable trade that also feels like a sizable chunk of profit within a department if using bounties as a way to supplement your income mid-shift.

Additionally: I was told that I miiiight have left out a slightly important feature to the pricetag component that miiiiight have enabled some absurd amount of profiteering. This is now fixed. _As a reminder, once your civilian bounty is completed, all you need to do is take the golden bounty cube, and put it on the cargo shuttle to send off, as is. There's nothing else you need to do with it._

As a final note, some prices of crates, specifically crates that see excessively little use mid-round for the utility the provide, have been adjusted for accessibility. 

## Why It's Good For The Game

Consistency is good, and price consistency feels good to see and know that the values are based on a tangible figure in-game as opposed to being based on a random spaghetti value at the end of the day. This places export values in terms of a single, standard unit (crates moved) and should be easy to relate to for players.

Prices are now more appropriate for both cargo's level of effort, and for station-side access in terms of what should and shouldn't be available with minimal effort at a given paygrade.

Fixes a bug that allows you to collect 50% of a civilian bounty's value because I am a stupid dumb dumb idiot several months ago.
As a result of the prices being appropriate to the level of resources being provided to players, the payout for performing civilian bounties could be increased as a direct result.

## Changelog
:cl:
balance: Civilian Bounty Cubes now pay out 30% of the value of the cube, up from 10%.
balance: Cargo Crates are now worth 200 credits each. Cargo crate prices have seen some tweaks as well for more uncommonly ordered crates as well.
fix: You can no longer cheat the bounty system by slapping a new price tag over a bounty cube.
refactor: The values of cargo crates you can order are now scaled in terms of the value of cargo crates.
/:cl:

### CODE REVIEW

**Comment by wesoda25** [comment]
no no no no no NO 500 credits a crate is CANON

**Comment by spessbro** [comment]
you based all your scaled on crate value changes on the old 500 mark which means you just lowered the cost of everything while not changing the base export value of regular exports if i'm not mistaken

**Comment by optimumtact** [comment]
I assume that's an intentional part of `Now, this means that the value of most crates on station are within the scale that cargo is now receiving 2.5 free crates every payday, `

**Comment by Tlaltecuhtli** [comment]
are shuttles prices being untouched intended?

**Comment by ArcaneMusic** [comment]
> you based all your scaled on crate value changes on the old 500 mark which means you just lowered the cost of everything while not changing the base export value of regular exports if i'm not mistaken



> are shuttles prices not being touched intended?

That's an excellent point, and I can adjust those in-kind as well.

**Review by Timberpoes — APPROVED** [review]
Misery loves company.

**Pull request merged**
