### PR TITLE
adds the brappenmatter

### PR DESCRIPTION
**Pull request by Jackal-boop**
## About The Pull Request

adds a chance for the SM to fart when it has miasma

## Why It's Good For The Game

image

## Changelog
:cl:
add: The SM has a new sound effect when it is interacting with miasma
/:cl:

### CODE REVIEW

**Comment by Bluedino1025** [comment]
Exadev is dead and we killed him

**Comment by Iamgoofball** [comment]
wrong codebase i think you meant to PR to https://github.com/goonstation/goonstation

**Comment by Kapu1178** [comment]
> Exadev is dead and we killed him

Oh if only you knew...

**Comment by ZephyrTFA** [comment]
while this is hilarious, I'm not really confident it should be a thing

**Comment by TheBoondock** [comment]
while we're at it might as well make it laugh with n2o

**Comment by dragomagol** [comment]
No thank u

**Comment by Jackal-boop** [comment]
can we atleast test merge it for a round

**Comment by BangingDonk** [comment]
> while we're at it might as well make it laugh with n2o

I think it is good and soulful that if we're stuck using exactly one engine for arbitrary reasons, it at least does some funny stuff now and again.

**Comment by BangingDonk** [comment]
I also submit precedent in the form of the clown car having a fart interaction

IMG_0201

**Comment by Loafin34** [comment]
NO!!!!!!

**Comment by lmenvs** [comment]
we will take it over on Monkestation

**Pull request closed without merging**
