### PR TITLE
CMO Hardsuit polish now with 100% less transparent hat

### PR DESCRIPTION
**Pull request by Haevacht**
Who the fuck put this in even, the inhands had the wrong colour plus, the right hands were misaligned and the helmet was SO MUCH FLAT COLOUR.

I fix my mistakes. Should mention, this does not update the helmet inhands because the helmet is not a seperate item anymore. 

Transparent hat removed, both icon and codewise.

Old S:

New S:

Old On E:

New On E:

### CODE REVIEW

**Comment by GunHog** [comment]
Pics?

**Comment by Haevacht** [comment]
Added. SHould less less jarringly flat against most terrain at least.

Embedding syntax is so fucking weird on this.

**Comment by ChangelingRain** [comment]
the helmet should be mostly flat color but partially transparent

**Comment by Haevacht** [comment]
Finally got git to replace them. It's got the transparent hat and the related code now, working on getting new pictures.

**Comment by WJohn** [comment]
I personally don't like the transparency of the helmet, but otherwise good work fixing the other problems. This suit is so rarely used I never noticed.

**Comment by Haevacht** [comment]
Aiight seems the transparency is the dividing factor, just throw up a comment saying in favour or not of the transparent hat.

**Comment by Lexorion** [comment]
Remove the transparency, looks slightly odd and no other hardsuit does it.

**Comment by phil235** [comment]
The issue with transparency is that it will show a bald head without mask/glasses because the hardsuit helmet hides them. Same thing occured with EVA suit helmet which lead to removal  of the helmet's transparency in #12357

**Comment by PKPenguin321** [comment]
Phil's right, nix the transparency.

**Comment by TechnoAlchemisto** [comment]
Transparency is bad

**Comment by Haevacht** [comment]
Aiight the votes are cast, transparency bad. And Phil, I could make it show the rest but horrendous clipping issues. Bald was better than basically all items and hair showing outside the helmet.

Reverting the tranparent hat and .dm changes now.

**Comment by Haevacht** [comment]
Too dumb to fix merge conflicts and it's too small to really bother trying.

Also this kinda breaks the 'need to explain why the pr i important' thing anyway because it's only me replacing a sprite I don't like.

**Comment by TechnoAlchemisto** [comment]
Improving sprites is a more than valid reason

**Pull request closed without merging**
