### PR TITLE
Remove birdstation

### PR DESCRIPTION
**Pull request by optimumtact**
Unmaintained and unliked, there are better options

### CODE REVIEW

**Comment by Keekenox** [comment]
Fuck yes.

**Comment by PKPenguin321** [comment]
top tier event map

**Comment by ChangelingRain** [comment]
you should remove mini instead mini is way worse

**Comment by ma44** [comment]
Don't remove my mini reeeeeeeeeeee

**Comment by KorPhaeron** [comment]
Agreed, remove mini instead, bird is a much more interesting low pop map

**Comment by dannno** [comment]
RIP mini, RIP trash bins
FML

**Comment by Cyberboss** [comment]
@Iamgoofball Who's closing this one?

**Comment by PKPenguin321** [comment]
this pr should not merge

**Comment by Iamgoofball** [comment]
This one doesn't belong to a maintainer and Mini is for lowpop

**Comment by Cheridan** [comment]
it would seem that the bird is, in fact, the word.

**Comment by BeeSting12** [comment]
remove mini while youre at it

**Comment by KorPhaeron** [comment]
Mini and Bird are both designed for lowpop, but bird is far more feature complete as far as small maps go.

**Comment by Aloraydrel** [comment]
>people defend bird station

**Comment by optimumtact** [comment]
The day of the rope approaches

**Comment by peoplearestrange** [comment]
Why remove it? What damage is it causing? Just remove the map from the rotation list.

**Comment by kyrahabattoir** [comment]
How about we stop removing maps?

**Comment by Iamgoofball** [comment]
You're a retard

**Comment by kyrahabattoir** [comment]
And you are highly immature.

**Comment by optimumtact** [comment]
@peoplearestrange they take developer overhead to maintain, nothign was wrong with these three maps as such, they just failed to inspire any support or love amongst the players.

Remember, we hold each map to the standards of box and meta, so if they sit around for a long time and aren't getting played regularly then the overhead of keeping them up to date is not worth it.

**Comment by optimumtact** [comment]
It looks like birdstation will survive for now at least.

**Comment by jughu** [comment]
But how can we play them regularly if they never come up???

**Comment by optimumtact** [comment]
If they can't beat our current kings of meta and box, then they failed to be better.

**Comment by jughu** [comment]
But people only puck those because they dont like change

**Comment by optimumtact** [comment]
Then you need to make a map that is extremely compelling

**Comment by kyrahabattoir** [comment]
@jughu Pretty much hits the nail, people don't want to play other maps because they don't want their routine to be changed because learning takes effort.

**Comment by KorPhaeron** [comment]
>It looks like birdstation will survive for now at least.

Killing mini is a good idea still though

**Comment by Shadowlight213** [comment]
Can't believe birdpoop station outlived mini. Rip 100 player mini rev rounds

**Pull request closed without merging**
