### PR TITLE
Completely remove the blood contract from the game, including the blood contract antag datum.

### PR DESCRIPTION
**Pull request by Timberpoes**
## About The Pull Request

Completely removes Blood Contract and the Blood Contract antag status.

Alternative to #52903 
Closes #52903 

## Why It's Good For The Game

image

## Changelog
:cl:
del: Removed the Blood Contract from the game.
/:cl:

### CODE REVIEW

**Comment by ATH1909** [comment]
What if we took the changes made by #52903, applied them, then removed blood contracts from the bubblegum loot pool, but KEPT them in the summon magic loot pool?

**Comment by necromanceranne** [comment]
Actually athath that might go the way you hope it will and for reasons unrelated to free antag. Magic that isn't ranged based will completely obliterate these bezerkers, since they lack hand use the whole time they're under the contract. It'll be hard for them to reasonably even kill anyone under the contract.

Seems like it'll just up being a feels bad moment when the crew get cool magic to only be given a fairly crappy antag last stand, you know?

**Comment by ATH1909** [comment]
> Actually athath that might go the way you hope it will

?

**Comment by necromanceranne** [comment]
might not, typo

**Review by Rohesie — APPROVED** [review]
This can be re-added when a better alternative is found later on in the future.

**Comment by TiviPlus** [comment]
Well if it doesnt people evidently dont care enough to actually fix the issues beyond complaining "I want selfantag paper"

**Comment by FloranOtten** [comment]
> Well if it doesnt people evidently dont care enough to actually fix the issues beyond complaining "I want selfantag paper"

That's a bit unfair. People aren't going to spend the same effort readding something as they are fixing it. That's just a fact of life.

**Comment by Whoneedspacee** [comment]
but it doesnt self antag

**Comment by TemporalOroboros** [comment]
Why not have it target megafauna instead of players? If it gives the megafauna a buff (possibly scaling with living playercount) to both its difficulty and the loot it drops it could be a cool way for the miner to conscript some backup.

**Comment by Doosteroni** [comment]
why don't we remove gluttony then since by your "muh self antag" logic, it should be removed. I have literally never heard anyone care about this because if you have this you JUST KILLED FREAKING BUBBLEGUM!

**Comment by Whoneedspacee** [comment]
rip

**Pull request merged**
