### PR TITLE
Adds new sprites for the energy axe

### PR DESCRIPTION
**Pull request by itseasytosee**
## About The Pull Request
old sprites:
image
image
-Chunky
- Doesn't look like an axe
- Doesn't look like a weapon worthy of one-hit killing people.
- Soulful 2D

New sprite
image
image
- Dynamic sprite
- Looks deadly
- Distinct from other glowy weapons
- Looks like an axe
- A weapon worthy of a berserker
- Soulful 2D

## Why It's Good For The Game
It's sick, look at this smooth operator: 
image
image

## Changelog

:cl:
imageadd: added new sprites for the energy axe
/:cl:

### CODE REVIEW

**Comment by itseasytosee** [comment]
fuck

**Comment by optimumtact** [comment]
unknown(2)

**Comment by itseasytosee** [comment]
Ok, now we are ready.

**Comment by Bawhoppen** [comment]
I think the handle should be a mixture of chrome & black polymer, maybe some red/colored bits on it too to break it up. As is it feels a bit uniform I think. Like imagine how the new syringe rifle sprite kinda is. Sorta more that style, though different.

**Comment by wesoda25** [comment]
HUMMINA

**Comment by TheBonded** [comment]
the old sprites looked like a stardew valley hoe

**Review by Twaticus — CHANGES_REQUESTED** [review]
axes_lefthand.dmi - axe front facing looks offset

**Comment by itseasytosee** [comment]
> axes_lefthand.dmi - axe front facing looks offset

Rectified

**Pull request merged**
