### PR TITLE
Allows all accessories to toggle between under/above suit, Take 2

### PR DESCRIPTION
**Pull request by VladinXXV**
## About The Pull Request
What I've done here is I've allowed the already existing accessory above_suit toggle to actually be used by all accessories, rather than only specific ones (such as the medical medals.) As part of this, the default for all accessories is to show ABOVE your suit. I **can** make the default to show BELOW, but there is little reason to hide an accessory to begin with, so I think it is less hassle for the majority of players if accessories start ABOVE.

image

## Why It's Good For The Game
The code already existed, and certainly seems to be an intended behavior. I can't find any reason for it to only apply to things like the medical medals, but not say, the captains medal, or an armband. You're telling me I can't wear an armband over a winter coat sleeve?

The majority of accessories in the game are things you would usually want to show off. Largely, this refers to medals, pins, and armbands. There is no harm in letting people choose to show these off, and it's a generally positive change to the gameplay experience.

## Changelog

:cl: Vladoricious
qol: All accessories show above the suit by default and can be toggled.
/:cl:

### CODE REVIEW

**Comment by Fikou** [comment]
mining accessories should be forced to go above suit, as they have balance implications

**Comment by VladinXXV** [comment]
> mining accessories should be forced to go above suit, as they have balance implications

Mining accessories already had the ability to be toggled, and I'm not deranged enough to make a balance PR.

**Review by Mothblocks — CHANGES_REQUESTED** [review]
going to agree with fikou here since i trust him more on lavaland balance than anyone else i can think of right now

**Comment by VladinXXV** [comment]
> going to agree with fikou here since i trust him more on lavaland balance than anyone else i can think of right now

My PR isn't changing anything related to balance, and I don't even know how I'd go about forcing mining accessories to be unable to toggle. They are **already able to toggle.** I'm just letting the accessories that **can't** toggle.

**Comment by VladinXXV** [comment]
If someone wants to change that, be my fuckin guest. But I do not know how nor am I interested in changing it.

**Comment by VladinXXV** [comment]
I don't see why I would be expected to make that change when #65333 did effectively the exact same thing I'm doing here, on a smaller scale.

**Comment by Mothblocks** [comment]
it's not a balance pr if you're preserving existing functionality (which is that they don't overlap)

at least if i'm understanding @Fikou correctly

**Comment by VladinXXV** [comment]
> it's not a balance pr if you're preserving existing functionality (which is that they don't overlap)
> 
> at least if i'm understanding @Fikou correctly

This IS existing functionality. The code as it exists allows any accessory set to show above suits toggle. MEANING mining accessories are ALREADY ABLE TO DO THIS.

**Comment by Mothblocks** [comment]
@Fikou let me know if i misunderstand anything then, i would want existing functionality preserved so if it's already like that then sounds out of scope?

**Comment by VladinXXV** [comment]
The two exceptions for mining related accessories would be the Bone Talisman and Hope specifically, but not in the way Fikou would want. Exact opposite, actually. Because they don't have above_suit = TRUE specifically there already, they are actually always HIDDEN. So, if anything, the balance change here is I'm giving people the choice to... NOT hide those. I repeat, before this they would ALWAYS be hidden under the suit.

**Comment by Mothblocks** [comment]
@optimumtact What happened? I think I saw something on Discord but can't find where it was

**Comment by optimumtact** [comment]
ok

**Comment by Mothblocks** [comment]
I'm going to assume what Fikou wants is new behavior and thus out of scope, I asked for his clarification a few times but I don't think I got it

**Pull request merged**
