### PR TITLE
The Clown now has a chance to spawn in Prison

### PR DESCRIPTION
**Pull request by theselfish**
## About The Pull Request

Who is the most arrested job in this game?
Barring assistant.
The Clown.
They now have a chance to spawn where they belong, a holding cell, except Tram which as none so sadly he's with the hardened criminals there.

## Why It's Good For The Game

This adds a fun little chance for the Clown to spawn with his favourite buddies; Security.
Maybe he asks to be let out, maybe he stays, maybe he takes over the prison to become a god-king of the underworld.
All up to the Clown.

## Changelog
:cl:
add: Clowns may notice that their actions have consequences. 
/:cl:

### CODE REVIEW

**Comment by xXPawnStarrXx** [comment]
Poor guy will never get released.

**Comment by Jolly-66** [comment]
The clown honked their last honk, ended up in the SLAMMER

**Comment by Jolly-66** [comment]
Also, maybe instead of putting a spawner in the holding cells, this could probably be a station trait?

**Comment by theselfish** [comment]
> Also, maybe instead of putting a spawner in the holding cells, this could probably be a station trait?

Not entirely sure how I'd convert it.
Any tips?

**Comment by Jolly-66** [comment]
> reply chain

Genuinely wish I could. My only advice is to look in code, or poke someone else in the coding channel who would have a better idea than me.

**Comment by BlueMemesauce** [comment]
It definitely needs to be a rare station trait, i'm pretty sure the spawn locations are equal chance by default so the clown would spawn in brig 50% of the time

**Comment by Admiral-Gigaton** [comment]
> > Also, maybe instead of putting a spawner in the holding cells, this could probably be a station trait?
> 
> Not entirely sure how I'd convert it. Any tips?

there IS the traits for spawning in arrivals, hangover, drop pods, maybe you could see how they did that? could give you some pointers.

**Comment by DATA-xPUNGED** [comment]
Holy mother of soul

**Comment by Admiral-Gigaton** [comment]
as he should be in jail. you are doing the work of god, we worship you and your jailing of clowns.

**Comment by GuillaumePrata** [comment]
A simple change is to add a clown spawner right outside the brig airlocks, as if they were just let free before the shift started.

Cute enviromental storytelling or something...

**Comment by xXPawnStarrXx** [comment]
> A simple change is to add a clown spawner right outside the brig airlocks, as if they were just let free before the shift started.
> 
> Cute enviromental storytelling or something...

Hear me out, a rare spawn for the clown inside the locker room in security. Also the same for the mime, immediate recruitment or assault 9/10.

**Review by MrMelbert — CHANGES_REQUESTED** [review]
Make this a station trait instead of adding a clown spawn landmark to the brig of every map

It should be rather easy, you can simply override `/datum/job/clown/get_roundstart_spawn_point()` to spawn the clown in one of the chairs in the brig holding cell area

**Comment by EricZilla** [comment]
I feel like if it's gonna be a station trait, go all in on it.
Wheres Waldo his ass and add 10 spawn options and remove the original

**Comment by Time-Green** [comment]
I think it’s super funny, but we shouldn’t punish players for picking a job by adding a random chance to incarcerate them. 

Right now it’s like a 30% chance depending on the map, which is unacceptable. A station trait would make it a lot less problematic, but I’m not keen in seeing more ‘do nothing’ station traits that only affects one player. 

We don’t need to add everything for the meme, some things are better if they just work like they’re supposed to

**Pull request closed without merging**
