### PR TITLE
Replaces chaplain smoke spell with recall spell

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
On Meta and Eff. 

I'm not sure whether this is a nerf or buff (aoe disarm is pretty good!), but it will work nicely with his weapons and not punish chaplains who choose a weapon without NODROP.

### CODE REVIEW

**Comment by TrustyGun** [comment]
We should add the spell to every map tbh

**Comment by KorPhaeron** [comment]
"Gives chaplain spell" is more of an argument than "changes the chaplains spell" though

**Comment by PKPenguin321** [comment]
We should make spells an option on the null rod so the chaplain can give up his rod for smoke/recall or whatever

**Comment by KazeEspada** [comment]
Fix chaplain armor when? Im tired of the crusader chaplains.

**Comment by AdamElTablawy** [comment]
>traitor chaplain

>get storage implant for free at roundstart

why

**Comment by Robustin** [comment]
Big buff imo. You can be ready for smoke, and its mostly defensive, etc...

Recall is just nuts with high powered weapons. Not looking forward to trying to chase down the chaplain when he's got an ebow/revolver that he will never lose.

**Comment by KorPhaeron** [comment]
I guess I could make it a snowflake recall that only works on his chaplain weapon

**Comment by Shadowlight213** [comment]
>War ops
>Got dat disk
>Disk suddenly vanishes
>Chaplain marked the disk for recall

I can see absolutely nothing wrong with this.

**Comment by KorPhaeron** [comment]
>I guess I could make it a snowflake recall that only works on his chaplain weapon

**Comment by Iamgoofball** [comment]
>I guess I could make it a snowflake recall that only works on his chaplain weapon

**Comment by Lumipharon** [comment]
jus leave smoke.

Smoke does fuck all if you're prepared for it, and is essentially a handy, but not powerful defensive ability (also a grief tool if you want, honkhonk).

Recall is OP as fuck, and if you snowflake it, it becomes pointless for weapons WITH nodrop.

**Comment by Zilenan91** [comment]
I could get behind it being only for his chaplain weapons so people don't hide them in maint where he will never find them

**Comment by Bawhoppen** [comment]
:-1: if its just a standard recall :+1: if its only for chap weaps

**Comment by Core0verload** [comment]
Leave smoke. Recall is really fucking powerful when used the right way.

**Comment by Armhulen** [comment]
> We should make spells an option on the null rod so the chaplain can give up his rod for smoke/recall or whatever
I'd be more than okay with this, he's trading his 'holy' validhunting tool for it so seems fair enough

**Comment by AdamElTablawy** [comment]
>snowflake recall on nodrop godhand

>negate half the weakness of choosing godhand


Hmmhmhmhmhmhmhmmmmm

**Comment by Fox-McCloud** [comment]
I strongly sympathize with your ideas to make chaplain something other than a useless RP gimmick role,  @KorPhaeron, but I think this is probably going to cause serious issues. There's a plethora of ways to abuse this, and I can see it just being used mostly by powergamers for very niche, very abusive applications.

If anything, some wacky healing spell or something that's kinda the opposite of revenant's defile would work out better for him; maybe he gets something that automatically blesses turfs in an area or some deculting method or something. Dunno; just throwing ideas out there.

**Comment by KorPhaeron** [comment]
Whoops I broke everything trying to work on two PRs at once

**Pull request closed without merging**
