### PR TITLE
Makes ash storms look better

### PR DESCRIPTION
**Pull request by Razharas**
Makes ash storms look better
Disregard the branch name

image

Gif made with gifcam so the size is not right and the looping is also probs fucked

### CODE REVIEW

**Comment by RemieRichards** [comment]
Pics.

**Comment by KazeEspada** [comment]
It's not transparent?

**Comment by Razharas** [comment]
Its not
For some reason all weather area effects are being transparented afterwards somehow i didnt understood how but in the end it just looks thicker and faster moving + cinders inside

**Comment by ChangelingRain** [comment]
The icon doesn't loop properly

**Comment by KorPhaeron** [comment]
>Pics.

**Comment by Razharas** [comment]
I just took the usual ash storm sequence, cut every second frame out, collapsed it to 8 frames, added one of the prestorm cinderfall sprites and pasted it into each frame with 2pixel shift to the down-left each new frame from previous, then progressevely pixelshifted all the frames to the left up to 7 pixels of last frame to make the horizontal speed faster, then bucketed the alpha layer with 255 of all frames and changed colour of cinders to be more bright
Looping couldnt break from this

**Comment by optimumtact** [comment]
BoHFix

**Comment by duncathan** [comment]
what does it look like ingame

**Comment by Razharas** [comment]
Like a much thicker, much faster version of the old icon + red dots

**Comment by duncathan** [comment]
having seen it ingame, it's cool as shit. :+1:

**Comment by ChangelingRain** [comment]
No, really, the icon doesn't loop properly, the cinders don't return to the position they started from so it 'flinches' when the icon goes back to the start

**Comment by TechnoAlchemisto** [comment]
Saw it in game, looks nice and I like it.

**Pull request merged**
