### PR TITLE
Removes extra admin info from Who

### PR DESCRIPTION
**Pull request by ghost**
Admins really don't need a completely untraceable way to check antagonists and who is alive/dead.

All that info is available in other panels that actually log when used.

### CODE REVIEW

**Comment by Iamgoofball** [comment]
Then why not log it? This is pretty useful.

**Comment by KorPhaeron** [comment]
Logging every time an admin uses Who would be silly, and it would be impossible to tell between "I was just checking players!" and cheating.

Using the check antagonist verb in the middle of playing, on the other hand, is pretty hard to explain.

**Comment by Iamgoofball** [comment]
Then just make it give verbose mode if you're dead or ghosted, normal mode if you're playing. Best of both worlds.

**Comment by Fox-McCloud** [comment]
:+1:  to this; something that effectively lets you check antag status and is completely unlogged is a big no no.

That said, you may want to fix a few antags only showing up in Who...for example, I believe the people infected by a blob don't show up in "check antag"....may be others.

**Comment by KorPhaeron** [comment]
@Iamgoofball 

Check Antagonists already does that very quickly though

@Fox-McCloud 

Infected blob people show up in check antags, it's the normal blob that doesn't.

**Comment by Shadowlight213** [comment]
It would be nice if you could keep the alive/dead/observing info though. I usually will use that to get a quick overview of how the round is going, and see how many ghosts are available.

**Comment by Ikarrus** [comment]
:+1: Gay Master approved

**Comment by clusterfack** [comment]
Make a logged advanced who option instead?

**Comment by Chocobro** [comment]
@clusterfack pretty sure it already exists in admin tab.

**Comment by Fayrik** [comment]
This PR has (to my knowledge) removed the only way to find out if someone was a round start observer.

Have we really gotten to the point where admins knowing who antags are is a bad thing?

**Comment by duncathan** [comment]
No, but admins having an unlogged way of checking who antags are is. We don't exactly want to allow cheating.

**Comment by Fayrik** [comment]
Well, that's my point. We've removed a useful feature, that's fixing a non-problem.

I suppose I'll have to be the one to clean this up. I will look into implementing it in the way @Iamgoofball suggests, as that seems to be the best way of doing it. Much better than my idea.

Using check-antagonists is a non-solution as it only shows information on active antagonists. That's *completely useless* when you're trying to run an event in extended and you need to get a list of round start observers for special roles.

**Comment by Jordie0608** [comment]
I'm inclined to agree with @Fayrik here, the additional information was rather convenient to have at hand and we've still a couple of ways to get the same information unlogged pretty easily, a few of which would be very messy to log and really not removable as features.

I understand the reasons this change was made, but now that I've used it I can't say I'm a fan and would like to see a more reasonable compromise made.

**Pull request merged**
