### PR TITLE
Adds package wrapping to autolathes

### PR DESCRIPTION
**Pull request by MrDoomBringer**
adds package wrap to autolathes for 200 metal 200 glass

:cl: MrDoomBringer
add: Advances in NanoTrasen's wrapping department have resulted in the easy creation of package wrap from all station autolathes!
/:cl:

>break into delivery office, click twice on a table
>sorry buster no more package wrap for the station. ever.

### CODE REVIEW

**Review by Cyberboss — APPROVED** [review]

**Comment by praisenarsie** [comment]
making paper out of metal and glass.

🤔

**Comment by MrDoomBringer** [comment]
@praisenarsie 
image

**Comment by PKPenguin321** [comment]
jogs the nog

**Comment by FantasticFwoosh** [comment]
You're obviously excluding the festive paper wrapping type, unless it is your intention for it to be a festive season only addition.

**Comment by Tlaltecuhtli** [comment]
metal is actually made of mushrooms lore wise (steel caps)

**Comment by MrDoomBringer** [comment]
@FantasticFwoosh keeps the scarcity of festive paper wrapping intentionally so that if you get a package wrapped in Holiday paper, you know its special!

**Comment by BeeSting12** [comment]
When will the cargo powercreep end?

**Comment by uraniummeltdown** [comment]
Don't do this it makes no sense
Add it to the Biogenerator

**Comment by Bawhoppen** [comment]
But this is clearly paper... not metal. Don't make such a break from reality just so you can have your silly wrapper replaceable.

**Comment by MrDoomBringer** [comment]
@Bawhoppen in space, paper is just a word for aluminum foil! (see the above picture for further issues about muh realism)
also:
>confused emoji and downthumb emoji at the same time

**Comment by Bawhoppen** [comment]
My comment still stands, as do my emoji

**Comment by MrDoomBringer** [comment]
i can make it a pack if you want

**Comment by TechnoAlchemisto** [comment]
don't make any changes for bawhoppen, they are nothing

**Comment by Bawhoppen** [comment]
Woah... how dare you say that about me...

Yes please make it a pack I think that would be best

**Comment by Bawhoppen** [comment]
As Jordie (or some other maintainer maybe) said once, just because something else is designed in a bad way, that's no excuse to do the same again (it was about bluespace bodybags or something like that)

**Comment by PsyCommando** [comment]
As a cargo tech, I don't really care much about having to go through a lot of bs with other departments, or "reality" just to get some dang wrapping paper. Chances are they'll have bigger things on their plates to care anyways. So instead of mailing stuff with the delivery system I'd use the mules or do it by hand if wrapping paper was the issue, just like before. Basically nullifying the whole point of putting a way to be able to make wrapping paper in the first place.. 

That's why it makes sense imo for it to be made in the lathe with glass or whatever, since its convenient game wise and doesn't require anything special or inaccessible to a simple cargo tech.
Or maybe wrapping paper could be made obtainable from something like the paper dispenser thingie but for wrapping paper? So you'd get basically infinite wrapping paper, and nobody will get to complain about realism.

**Pull request merged**
