### PR TITLE
Smoke Machine Updates & Fixes

### PR DESCRIPTION
**Pull request by Robustin**
Seriously Man

:cl: Robustin
tweak: The wrench-anchoring time of the smoke machine is now doubled to 4 seconds.
tweak: Smoke Machine smoke is now transparent.
add: The smoke machine has taken its rightful place in the chemist's office. 
fix: Smoke machine will no longer operate while moving/unanchored.
/:cl:

### CODE REVIEW

**Comment by Robustin** [comment]
Ok I'm getting some fun looking map issues associated with trinary filters that I definitely didn't touch.

**Comment by Bawhoppen** [comment]
Seriously man.

**Comment by Robustin** [comment]
Hey you got your tech storage boards, now the boards are in tech storage. 

I just wanted to make it consistent since all the other tech boards exist elsewhere as roundstart machinery.

**Comment by ShizCalev** [comment]
@the map stuff; see #31595 
just revert the changes using notepad for now.

**Comment by Cyberboss** [comment]
travis + confrictur

**Comment by Robustin** [comment]
So is the trinary thing fixed? Do I repull the new master?

**Comment by ShizCalev** [comment]
It was fixed. You can either pull a new master or just revert those lines with notepad and commit.

**Pull request merged**
