### PR TITLE
Adds missing items to Robotics crate

### PR DESCRIPTION
**Pull request by SpaceLoveSs13**
## About The Pull Request

Adds missing items to robotcs crate.

## Why It's Good For The Game

Issue Fix PR

## Changelog

:cl: SpaceLove
fix: Central Command Logistics department noticed the missing items on their listings for robotics assembly crate. They have updated it!
/:cl:

Testing Proof: 
image

### CODE REVIEW

**Comment by jughu** [comment]
use empty kits/toolboxes

**Comment by Vect0r2** [comment]
Wooooh! can't wait to get an energy axe from a robo crate.

**Comment by SpaceLoveSs13** [comment]
> use empty kits/toolboxes

Medkits already initialize empty. I have changed the toolbox to the base empty variant and removed the mention of mechanical from previous description.

**Review by ArcaneMusic — APPROVED** [review]
Appears fine

**Pull request merged**
