### PR TITLE
Fixes edible rabbit eggs

### LINKED ISSUE #39791: Rabbit eggs are edible
Round ID: 92725

The eggs that rabbits "lay"; you're supposed to unwrap them and then get a prize and a chocolate egg inside.

But you can also just eat them and throw them like they were regular eggs.

### PR DESCRIPTION
**Pull request by Wayland-Smithy**
## About The Pull Request

Fixes: #39791 thanks to [issue roulette](https://issue-roulette.vercel.app/)

## Why It's Good For The Game

Fix good.

## Changelog
:cl:
fix: Fixed chocolate surprise easter eggs being edible before they are unwrapped and tasting like egg.
/:cl:

### CODE REVIEW

**Review by ghost — CHANGES_REQUESTED** [review]
they shouldn't be a food subtype if they can't be eaten.

**Review by Ghommie — COMMENTED** [review]
At this point, it's better to make these surprise eggs not a subtype of `food/`, get rid of that `containsPrize` variable and move the `dispensePrize` (the list of prizes could be a static variable btw) and `attack_self` definitions to the new typepath.

**Comment by Wayland-Smithy** [comment]
I suppose that would be best. Now I expect those reviews circled back to for approval and not just used as comments.

**Review by ghost — APPROVED** [review]
looks good to me.

**Review by Ghommie — APPROVED** [review]
Ditto.

**Comment by EricZilla** [comment]
You fixed another thing too, now when rabbits lay eggs they wont flood the station with ants.

**Comment by AMonkeyThatCodes** [comment]
@EricZilla food like eggs should not decompose like that in the first place 🤔

**Pull request merged**
