### PR TITLE
Revert "adds a new janiborg sprite!"

### PR DESCRIPTION
**Pull request by Iamgoofball**
Reverts tgstation/tgstation#63619
24hourrule

### CODE REVIEW

**Comment by Iamgoofball** [comment]
also this is for merging in 1 day when christmas is over

**Comment by Fikou** [comment]
oranges allowed it

**Comment by Iamgoofball** [comment]
yeah, for christmas, it has to go after christmas if i read oranges post right

**Comment by cacogen** [comment]
doing god's work

**Comment by exymian** [comment]
He contributed and gave us modsuits let him have fun fir christmas man

**Comment by Hafahya** [comment]
> He contributed and gave us modsuits let him have fun fir christmas man

modsuits are shit tho. When will coders separate codebases to fuck over with updates 3 servers less

**Comment by optimumtact** [comment]
closing in 24 hours

**Comment by optimumtact** [comment]
actully I guess I can merge these when xmas is over.

**Comment by thgvr** [comment]
1984

**Comment by Jackraxxus** [comment]
Pls keep the maidborg skin borgs need more customization options

**Comment by tralezab** [comment]
> Pls keep the maidborg skin borgs need more customization options

I AGREE BUT IS THIS THE WAY

**Comment by Iamgoofball** [comment]
the people have spoken

**Comment by Capsandi** [comment]
in our hour of need, he abandoned us...

**Comment by Serxule** [comment]
ok but fr though? it looks cool, janiborg needs more sprites anyways.

**Comment by optimumtact** [comment]
cool story, but I dont' care.

**Comment by CourageTheCat** [comment]
noOOO DONT REVERT

**Comment by optimumtact** [comment]
24 hours remain of xmas

**Comment by thgvr** [comment]
dawn of the final day

**Comment by interestingusernam3** [comment]
1 hour remains

**Comment by TemporalOroboros** [comment]
> 1 hour remains

Long hour

**Comment by optimumtact** [comment]
I was playing eu4

**Comment by tralezab** [comment]
Everyone who played during christmas please take a look at this device

**Comment by SoftStone101** [comment]
service borg rules

**Pull request merged**
