### PR TITLE
Adds Star Cacti and the Prickly Adhesion plant trait.

### PR DESCRIPTION
**Pull request by ArcaneMusic**
## About The Pull Request

Adds a new plant, the star cacti, as a new mutation to the lavaland cactus plant. Star Cacti are only obtainable by collecting a regular cacti, collecting it for seeds, then mutating it. Star Cactus have some basic brute medicine production, produce water, but most importantly carry the needles trait as well as the new trait...

Prickly Adhesion. Prickly Adhesion applies sticky, embedding properties to the plant product.
**Updated 7/14/2020**
The embedding type is now dependent on presence of the stinging trait on the plant. Without stinging, the plant has harmless embedding, while with stinging it becomes harmful embedding.
The plant's throwforce is capped at 5 , calculated by the seed's potency/20.

Interactions of note, post-testing:
**Hypodermic + Adhesion:** Applies the plant's reagents when embedded based on the typical 20u transfer limit that hypodermic needles provide.
**Slippery + Adhesion:** no effect, BUT when the plant falls out you can slip on it.
**Bluespace + Adhesion:** Appears to have no effect, as bluespace activity interacts with on squash (Liquid_contents) and on_slip (slippery exclusively).

## Why It's Good For The Game

Provides a unique trait for botanists to work for and collect with a payoff that would enable them to deal some damage as a traitor.

In addition, this will help in expanding the lavaland chemicals access to the station by tempting botanists to take the time out and collect the plants, OR, to encourage other players to collect plants for them (Miners, You have a plant bag for a reason).

## Changelog
:cl:
add: Added Star Cactus, a new mutation of lavaland cacti.
add: Added the Prickly Adhesion plant trait, enabling embedding on plants, but is mutually exclusive with liquid contents.
/:cl:

### CODE REVIEW

**Comment by ShibaInuLord** [comment]
would potency be the best stat for this? since saltpeter exists, which can get 100 potency extremely quickly.

**Comment by necromanceranne** [comment]
Bag full of ninja stars that inject acid, oh no.

**Comment by carshalash** [comment]
We need cactus juice tbh

**Comment by evilcyborgmrt** [comment]
This is too powerful.

Each individual plant grown with this trait should require an anomaly core.

**Comment by oklews** [comment]
Potency is 100% the wrong direction to take this, but I can't think of a better way.

**Comment by Doosteroni** [comment]
Do they inject their reagents?

**Comment by ArcaneMusic** [comment]
I've updated the embedding to avoid balancing it around potency, but instead on the traits the plant already has.

**Review by kriskog — APPROVED** [review]

**Pull request merged**
