### PR TITLE
makes girders smooth

### PR DESCRIPTION
**Pull request by mc-oofert**
## About The Pull Request

image

## Why It's Good For The Game

looks better i think

## Changelog
:cl:
image: girders and reinforced girders smooth now (except cult girders, bronze girders, and whatever other special type)
/:cl:

### CODE REVIEW

**Comment by SmArtKar** [comment]
normal girders look very neat but what is even going on in the reinforced girder's sprite

**Comment by mc-oofert** [comment]
> normal girders look very neat but what is even going on in the reinforced girder's sprite

they used to look like this but i felt it looked not so good but it might just be better than whatever i made as a replacement
image

**Comment by mc-oofert** [comment]
image

i made it look like this

**Comment by mc-oofert** [comment]
also what the fuck does that runtime mean

**Comment by AtomTheProphet** [comment]
I like this. This is good.

**Comment by Loafin34** [comment]
i liked the first reinforced girder sprite more. it's less busy with the lines

**Comment by GuillaumePrata** [comment]
This is something I always wanted and never knew until I looked at the pictures here.

**Review by Wallemations — CHANGES_REQUESTED** [review]
> image

I feel like the girders in the center aren't visually connected to the outer girders enough, which kinda makes the larger issue that they look very simple more apparent.
Right now they kinda just look like groups of 4 squares with very little depth. Even if we're not touching the perspective of them we can improve their shading/palettes a tad.

**Comment by Wallemations** [comment]
Actually now that I look it's not the girder centers that are the issue, it's the corners of those center girders that are the pillars. They are the bits that look odd to me.

**Comment by mc-oofert** [comment]
> Actually now that I look it's not the girder centers that are the issue, it's the corners of those center girders that are the pillars. They are the bits that look odd to me.

reinforced_girder
do you mean this 5th from the left part representing connections from all 8 sides

idk what you mean specifically

**Comment by mc-oofert** [comment]
i also made this variant idk if its any good
<details>
<summary>expand</summary>

image

</details>

**Comment by Wallemations** [comment]
> > Actually now that I look it's not the girder centers that are the issue, it's the corners of those center girders that are the pillars. They are the bits that look odd to me.
> 
> 
> 
> reinforced_girder
> 
> do you mean this 5th from the left part representing connections from all 8 sides
> 
> 
> 
> idk what you mean specifically

image

I mean this entire area here. All of this.

**Comment by mc-oofert** [comment]
> > > Actually now that I look it's not the girder centers that are the issue, it's the corners of those center girders that are the pillars. They are the bits that look odd to me.
> > 
> > 
> > 
> > reinforced_girder
> > 
> > do you mean this 5th from the left part representing connections from all 8 sides
> > 
> > 
> > 
> > idk what you mean specifically
> 
> image
> 
> I mean this entire area here. All of this.

How would I fix that do I just make mini girders there

**Comment by Wallemations** [comment]
> How would I fix that do I just make mini girders there

It's specifically the colors/shading (or lack thereof) that I'm referring to in this screenshot. That set of grayscale colors are _entirely_ grayscale. This tends to make things look really muddy, so usually what we do is change it so grays are actually very slightly blue, which allows us to hue-shift it to get a better feeling palette.

Here's an example with the metal sheets, which use a slightly blue tint. 
(the red is because it was blending into the background checkerboard lmao)

image

Despite the blue tint we still register it as gray, but we're also able to make use of that previously mentioned hue-shifting so it looks far better.
I'd recommend using a similar palette, and seeing how that works out.

**Comment by mc-oofert** [comment]
ok im not doing shading

**Comment by mc-oofert** [comment]
more variants.....
<details>
<summary>Variant A - no pillars (reinforced girders untouched)</summary>

image

</details>
<details>
<summary>Variant B - Pillars</summary>

image
</details>

**Comment by Wallemations** [comment]
> ok im not doing shading

Not saying you HAVE to add shading, just update the palette at least

**Comment by mc-oofert** [comment]
I forgot to commit variant A but I'm not at my computer now so don't merge yet

**Pull request merged**
