### PR TITLE
Blood contract knives only last two minutes, like the chainsaw

### PR DESCRIPTION
**Pull request by coiax**
:cl: coiax
tweak: All the butcher cleavers that spawn during a blood contract will only last two minutes, and then vanish.
/:cl:

Because otherwise there's a bunch of mundane knives lying around.

### CODE REVIEW

**Comment by 81Denton** [comment]
Is michnia a bot or what

**Comment by tralezab** [comment]
They're an npc.

**Comment by imsxz** [comment]
kinda lame, target could get away with just hiding like a bitch for 2 mins and being completely fine the rest of the round. Of course I’m heavily biased because who am I to turn down a free antag chance?

**Comment by 4dplanner** [comment]
Knife clutter should go, but why get rid of the redness?

**Comment by kriskog** [comment]
I don't know about this, makes mark for death much less dangerous and I don't like that. Two minutes also isn't very long.

If you wanna smite people, just make a lesser blood contract that do these things?

**Comment by MACIEKBAKI** [comment]
Bubblegum got (somewhat) harder to beat, and it is a tough-ish battle for the unrobust like me. Now you get a blood contract, maybe give it to the clown, but it only lasts two minutes. I feel like thats too little reward for too much work. If it was extended to lets say 10 or atleast 5 minutes, I think that'd be a little better.. If you make it so everyone knows where the marked person is (I.e give them something like a pinpointer) I think it'd be more fair, without it you can just hide for the 2 minutes as @imsxz mentioned.

**Comment by GhostEcho** [comment]
Just remove the weapons not the red marking

**Comment by optimumtact** [comment]
Do what they said yo

**Comment by coiax** [comment]
They said different things, which ones do I do?

**Comment by optimumtact** [comment]
`Just remove the weapons not the red marking`

**Comment by Cyberboss** [comment]
Your PR is getting old. Either Travis CI is failing, it is still labelled work in progress (change this by adding `[READY]` to the start of your title), or there are unaddressed change requests. This may be closed soon to free up space on our tracker if it remains idle. In the event that it is, please ask in #coderbus on Rizon for it to be reopened once you have resumed work on it.

**Review by Cyberboss — APPROVED** [review]

**Pull request merged**
