### PR TITLE
Fixes certain alien organs (eyes, tongue, liver) not registering for organ bounty.

### LINKED ISSUE #42961: alien organs bounty doesnt seem to work
i sold stuff like the alien liver and still had 0/3

### PR DESCRIPTION
**Pull request by Militaires**
:cl: Basilman
fix: Fixed certain alien organs (eyes, tongue, liver) not registering for organ bounty.
/:cl:

closes #42961

### CODE REVIEW

**Comment by Militaires** [comment]
oops fucked my labels up

**Comment by Tlaltecuhtli** [comment]
does the alien brain even work?

**Comment by Militaires** [comment]
theoretically, there's no reason it wouldnt

**Comment by Tlaltecuhtli** [comment]
well brains are considered mobs and make shuttle not depart, idk about the alien brain from tendrill chest tho

**Pull request merged**
