### PR TITLE
replaces vox o with an actual o sound

### LINKED ISSUE #28691: sound/vox_fem/o.ogg is really sound/vox_fem/i.ogg
sound file is an incorrectly named dupe. i can't say "l m a o" over vox announcements because of it

### PR DESCRIPTION
**Pull request by JohnFulpWillard**
## About The Pull Request

Do you know what I had to do, to get this sound?
I had to track down where it was originally made, and I fucking found it, because thankfully, they went open source in 2020 https://github.com/N3X15/ss13-vox
I then discovered they don't support Windows, only Linux. I had to get a fucking Linux on a VM just to run this. Then I found out that all sounds are doubled because of ??? (they even had an issue report over this, that they closed, but never pushed a fix to it.), so I had to open this in audacity to cut out the doubled part and only keep the first o sound.
Was it worth it? Maybe, but that's only because I also found out there's a "SFW" version of Beepsky's emag message, which I cannot send on github because it doesn't support .ogg, but I can transcribe what it says;
``Fry your cake you soil eating chicken-sucker. Man, eat a donut, flying boat-ramming spam-flipper. Eat pickles in your fat face, and scream out apples of fruit, and do shuttles in your butt, you skub-love spam monkey apple-eater from the depths of Spain!``

## Why It's Good For The Game

Closes https://github.com/tgstation/tgstation/issues/28691 - an issue since 2017

## Changelog

:cl:
fix: AI's "O" sound on vox now sounds like an O instead of an I.
/:cl:

### CODE REVIEW

**Comment by Mothblocks** [comment]
You can get that script working with WSL

**Comment by Mothblocks** [comment]
That being said why didn't you just copy the "oh" sound

**Comment by JohnFulpWillard** [comment]
> That being said why didn't you just copy the "oh" sound

o sound is "O." while oh sound is "oh" so I didn't know if they would make the same sound.

**Comment by Mothblocks** [comment]
Fun fact I've been trying to get us automatically on this script for fucking weeks but it doesn't work on Windows outside of WSL in any form. There are like 2 different versions of festival, one intended to be easier to embed, neither of which support Windows, one of which supports WASM, which doesn't actually work (or would take several minutes to complete at minimum making it useless)

**Pull request merged**
