### PR TITLE
Revert "Adds player preference to hide irrelevant tablecraft recipes"

### PR DESCRIPTION
**Pull request by Razharas**
Reverts tgstation/-tg-station#16978

### CODE REVIEW

**Comment by Robustin** [comment]
Apparentl #16978 broke tablecrafting and let you craft infinite anything without any materials.

**Comment by Thunder12345** [comment]
This was an excellent piece of testing here, how was it possible to miss this

**Comment by RemieRichards** [comment]
High priority, jeez.

**Comment by phil235** [comment]
That's what happens when you don't test your PRs...

**Pull request merged**
