### PR TITLE
Research and different mat requirements for borg upgrades

### PR DESCRIPTION
**Pull request by ghost**
Vtec upgrades now require 5000 uranium, materials 5, and engineering 4 (no longer requires gold)
Taser cooler upgrades now require combat 5 and power 4
Jetpack now requires engineering 4 and power 4, but the uranium requirement was lowered to 10,000 (previously 20,000) and the plasma requirement was lowered to 12,000 (previously 15.000)

Why these blatantly extremely powerful upgrades were available roundstart is beyond me. Robotics being able to upgrade borgs without research is nice but then again we can't have nice things due to bad apples that continue to abuse systems unpunished.

### CODE REVIEW

**Comment by hornygranny** [comment]
:+1:

**Comment by Jordie0608** [comment]
Changelog.

**Comment by HoaxIT** [comment]
:-1:

**Comment by Dorsisdwarf** [comment]
:+1:

**Pull request merged**
