### PR TITLE
Adds a few clothing items to the AutoDrobe

### PR DESCRIPTION
**Pull request by ghost**
Added the joy mask from /vg/, cueball helmet and scratch suit and added them to Autodrobe.

:cl:
add: Added the cueball helmet, scratch suit, joy mask to Autodrobe
/:cl:

### CODE REVIEW

**Comment by uraniummeltdown** [comment]
I'd like for someone to map in Autodrobes into the locker rooms of Box, Meta, Eff. I tried doing it myself but map merger and FastDMM both keep removing random things from the map and messing it up. And maybe also add it to Pubby. As a PR to my branch or after this one.
http://imgur.com/a/dthek

**Comment by Iamgoofball** [comment]
@Cheridan i warned you, slippery slope, they're re-adding homestuck shit

**Comment by uraniummeltdown** [comment]
@Iamgoofball the scratch clothes are snazzy as heck, i'm not adding troll horns or zodiac shirts

**Comment by Niknakflak** [comment]
The cueball helmet and scratch suit used to exist in this very codebase and were removed.  I also don't know why you would remove the autodrobe's access requirement.  It's for dress up for clown and mime, regular crew members have the clothesmate.  The autodrobe is special for a reason.  :-1:x :100:

**Comment by optimumtact** [comment]
I'm merging this :grin:

**Comment by Iamgoofball** [comment]
@uraniummeltdown thats how it starts, slippery slope

**Comment by jaxy15** [comment]
I don't think I've ever seen Niknak say anything positive about a PR

**Comment by ExcessiveUseOfCobblestone** [comment]
What do these clothes look like? I know about the cueball and have been hoping someone would put it back in but I don't remember the other 2.

also just hack the autodrobe you lazy boy.

**Comment by Niknakflak** [comment]
That's probably because you don't github very often, shown by your lack of contributor tbh

**Comment by Shadowlight213** [comment]
Ignoring the clothes thing, which I don't care either way on..

@uraniummeltdown why are you removing the theater access/asking for it to be added to locker rooms?
The autodrobe is specifically FOR the clown and mime. Regular crewmembers have the clothesmate. If you're making it be general access, then there is zero reason to keep them separate and instead the two should just be merged into one vendor.

**Comment by uraniummeltdown** [comment]
@Shadowlight213 
The Autodrobe has the more wacky and fun clothes, and a bunch of things that don't even belong on the Clown/Mime like plague doctor, roman legion, owl, gladiator. The clothes in the ClothesMate are mostly boring and regular, there is a difference in theme so they should be kept separate.

@ExcessiveUseOfCobblestone 
Here is what they look like:
joymask
scratchss13

**Comment by Shadowlight213** [comment]
@uraniummeltdown the clown and mime are performers. That's why they have those costumes. It's retarded to give them to the rest of the crew. If you want wacky costumes go play clown or mime ir get access. Might as well remove theatre access entirely and make the stage a public area at that point.
Hell, I'll do that if this pr goes through.

**Comment by uraniummeltdown** [comment]
@Shadowlight213 The clown and mime hardly ever use the stage and put on a show, most people wouldn't even RP and watch a performance by the clown and mime. Crew already have access to wacky costumes from the crates in cargo, and they can already get those costumes by hacking the Autodrobe. This just makes it easier for everyone.

**Comment by optimumtact** [comment]
Shadowlight is correct. Keep the autodrobe permissions, if you want this generally available put it in the vending machine for clothes that spawns in the break room.

**Pull request merged**
