### PR TITLE
Multiple medibots no longer cause overdosing.

### LINKED ISSUE #10241: Medbots OD you on bicaridine
See above

### PR DESCRIPTION
**Pull request by GunHog**
- Medibots now re-assess the patient before dosing meds to avoid
  overdose injections.
- Fixes #10241.

### CODE REVIEW

**Comment by Anonus** [comment]
I'm pretty sure this won't fix it if the medibots are all injecting at once, as the chem doesn't heal instantly and can't be allowed to anyway.

**Comment by Jalleo** [comment]
Does this include when medibots inject at the same time?

**Comment by GunHog** [comment]
That is exactly what this fix addresses. Two medibots may try to inject someone, but due to BYOND's single-threaded nature, one medibot will inject at an infinitesimal moment before the other, so the second medibot, by scanning the patient before the injection completes, can avoid overdosing someone.

**Comment by Jalleo** [comment]
Okay then :+1:

**Comment by SconesC** [comment]
The deadliest predator of Medbay is no more

**Comment by Aranclanos** [comment]
remove the comment

**Comment by Cheridan** [comment]
i think the comment might be informative to people looking at the code

**Comment by Aranclanos** [comment]
its implied, ending up making the code harder to read

**Comment by Jordie0608** [comment]
Could you add a failure message to indicate the bot aborted injecting you?

**Comment by GunHog** [comment]
I left that out as it would probably be spam (as one other medibot is likely trying to inject as well), but I will do that and remove the comment so the Spider is happy, too.

**Comment by Jordie0608** [comment]
I'm just thinking it may lead to people wondering why the bot didn't inject them; they're already rather spammy anyway.

**Comment by Marflowerose** [comment]
I just got overdosed by 2. Someone exploded nearby, 2 medibots injected him, then I dragged the prone dude to medbay where a third one injected him after the 2, probably ODing aswell.
http://i.imgur.com/HQO7mws.png

**Comment by GunHog** [comment]
Well, that is fixed, now. (Just not live).

**Comment by Marflowerose** [comment]
Ah, my bad, I assumed this one was in aswell since Orbit etc got in yesterday.

**Pull request merged**
