### PR TITLE
Adds radial menus.

### PR DESCRIPTION
**Pull request by AnturK**
Adds radial menus.
Can be used for things like this : https://streamable.com/u3vse
The actual context menu is NOT in this PR, this is only base menu code.

Sprites by @WJohn

### CODE REVIEW

**Comment by Ziiro** [comment]
It's beautiful.

**Comment by epochayur** [comment]
looks great, but a few comments/questions for whoever implements this;
1. It seems like it takes longer than it should for the icons to reach their final resting position
2. will the menu be canceled from moving/clicking elsewhere?
3. this seems like this could potentially get in the way of clicking other nearby objects, will it be toggleable?

**Comment by AnturK** [comment]
The animation is actually faster in current version, this is bit outdated video.
No, unless whoever uses it wants it to.
Not sure what you mean by toggleable ? Just close it if you don't want in the way ?

**Comment by yoyobatty** [comment]
Ah it looks so good!

**Comment by epochayur** [comment]
sorry, i meant having it as a preference, that partially answers my question though

**Comment by ExcessiveUseOfCobblestone** [comment]
what would the preference be?

**Comment by nicbn** [comment]
why does every feature needs to be a preference
stop the preference boat

**Comment by epochayur** [comment]
I have yet to have someone explain why "preference bloat" is supposedly a bad thing.

**Comment by yoyobatty** [comment]
I made a nanosuit over at hippiestation, this needs it now.

**Comment by Iamgoofball** [comment]
@epochayur no more preferences, accept the game design we give you and adapt

**Comment by epochayur** [comment]
"No!"

**Comment by BeeSting12** [comment]
Will this eventually replace right click?

**Comment by WJohn** [comment]
Possibly, @BeeSting12 but it's going to be a long while before we reach that. A lot more buttons need to be added, UI styles (we only have it in midnight right now), something will have to be done about the clusterfuck of admin buttons that are bloating the context menu, too.

**Comment by octareenroon91** [comment]
>something will have to be done about the clusterfuck of admin buttons that are bloating the context menu, too.

This seems like a strong reason to make it a pref.

Merge pls so we can argue without jeopardizing the feature.

**Comment by actioninja** [comment]
Holy fuck, yes please.

**Comment by outbools** [comment]
>I have yet to see someone explain why "preference bloat" is supposedly a bad thing.
Because it's not you who gonna maintain 2-3 alternative preferences, right?

**Comment by octareenroon91** [comment]
>maintain

I'm not going to dispute that code maintenance takes effort. The right-click menu is more or less an enumeration of verbs (basic code entity) with a more or less native drop-down menu, though, isn't it? I suspect that adding any user-customizability to radial menus would bring us close to the same code complexity anyhow.

**Comment by Iamgoofball** [comment]
>with a more or less native drop-down menu, 

It's also incredibly laggy, breaks like a motherfucker on older clients and computers, and is an endless source of struggle for anyone wanting to have a right click action on an item.

**Comment by ExcessiveUseOfCobblestone** [comment]
having right click only work on the pixel you clicketh upon would be an immediate upgrade to the current right click, radial menu or not.

**Comment by Bawhoppen** [comment]
Preferences sometimes are warranted, but for stuff like this, I think people just need to get used to the changing times.

**Comment by TheDreamweaver** [comment]
This looks really nice, but unfortunately it seems like this can only cleanly support up to 8 options, which for normal use should be enough, but for admin buttons another solution will have to be implemented first.

**Comment by davethwave** [comment]
Cool, didn't expect it to be merged to soon though.

**Comment by Iamgoofball** [comment]
>This will never replace right click, this will likely instead just be a way to access the action buttons of something you don't (or can't) have equipped.

This is absolutely replacing right click, what are you smoking?

**Comment by PKPenguin321** [comment]
how would this replace right click? seems to serve a different purpose?
and he's probably smoking weed

**Comment by TheDreamweaver** [comment]
It has to replace right click, because you can't have two right click functions. Unless we can do a control + right click, in which case I'd actually have the current right click menu made into th control click one since this is more useful to the average player than the things that will have to remain in the normal menu.

**Comment by MrStonedOne** [comment]
>It has to replace right click, because you can't have two right click functions. Unless we can do a control + right click, in which case I'd actually have the current right click menu made into the control click one since this is more useful to the average player than the things that will have to remain in the normal menu.

You can.

Very likely we would put this into control+right click while we start to give it things and move stuff over to it, then swap them out, but give admins the ability to have it swap back automatically while they are ghost.

**Comment by MrStonedOne** [comment]
> Stop giving ultimatums, you're not good at UI design.

I'm good at prioritizing functionality and a menu that can only support 8 options is not functional.

**Comment by Iamgoofball** [comment]
Open with that next time.

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
I made a bunch of icons following the style of the originals:
dreammaker_2018-09-28_03-08-58
dreamseeker_2018-09-28_03-07-23
I don't have a clone of this repo to make a PR from and you guys hate web edits so I'll just link the DMI
https://github.com/vgstation-coders/vgstation13/blob/4c2ebec617501cba30506a09fc9e12bfcfd2407f/icons/mob/radial.dmi?raw=true

**Pull request merged**
