### PR TITLE
unfucks lavaland

### PR DESCRIPTION
**Pull request by Buggy123**
# testmerge don't merge

# testmerge don't merge

# testmerge don't merge

:cl:
fix: fuck
/:cl:

### CODE REVIEW

**Comment by Qustinnus** [comment]
lmao epic web editor stories gone wrong

**Comment by Qustinnus** [comment]
why is this testmerge only? it's the right fix

**Comment by spookydonut** [comment]
is this a shitpost

**Comment by Buggy123** [comment]
@Qustinnus it's not tested and for the foreseeable future I am unable to test it. Merge without testmerging at your own peril.

**Pull request merged**
