### PR TITLE
concussive gauntlets now launch you away from gibtonite and mine basalt

### PR DESCRIPTION
**Pull request by Fikou**
## About The Pull Request
when you mine gibtonite using concussive gauntlets, you now get launched away from it, so you wont get hit by the explosion
concussive gauntlets can now mine basalt

## Why It's Good For The Game
makes them not kill you everytime

## Changelog
:cl:
qol: concussive gauntlets now launch you away from gibtonite
qol: concussive guantlets can now mine basalt
/:cl:

### CODE REVIEW

**Comment by TheGreatValvatorez** [comment]
Punch the explosion back into the rock infront of you 😈

**Comment by TheGreatValvatorez** [comment]
Maybe instead of knocking you back! you could make it instead of disarming it would launch a explosion forward from the direction you hit and the power based on the gibnonite strength this could potentionally allow for (emergency gameplay lavaland) and danger zone

**Comment by VladinXXV** [comment]
I'd prefer the gibtonite interaction disarm, do as suggested above, or not change at all. You can stop if you pay attention and avoid gibtonite as-is. Getting launched away is potentially more dangerous than facing the explosion (launched into lava, megafauna, chasm, etc)

**Comment by newfren** [comment]
dying to the concussive gauntlets is extremely funny but right now they're just worse than the advanced plasma cutter except for grinding mining skill so this is a good change

**Comment by Shadowflame909** [comment]
this will be great for the sole reason of when you play those old MX vs ATV games and reaching the edge of the map ragdolls you back towards the middle of it.

It will create a great high-speed method to stave off boredom

**Pull request merged**
