### PR TITLE
Adds sprites for conveyor belt constructs

### PR DESCRIPTION
**Pull request by MrDoomBringer**
Conveyorbelts used to look the same attached to the floor as they did as an item (in your hand UI, in a locker, etc). this changes that

:cl: MrDoomBringer
imageadd: Conveyor Belts now look better when they are crowbar'd off the ground.
/:cl:

**before - Conveyor Attached to the ground on the left, Conveyor as an item on the right:**
conveyora
**After - Conveyor attached to the ground on bottom, Conveyor as an item on top:**
conveyorc

### CODE REVIEW

**Comment by WJohn** [comment]
This looks good.

**Review by WJohn — APPROVED** [review]

**Review by Cyberboss — DISMISSED** [review]
Ignore this review

**Review by Cyberboss — CHANGES_REQUESTED** [review]
Not done yet

**Review by silicons — CHANGES_REQUESTED** [review]
Meme

**Review by silicons — APPROVED** [review]
Meme

**Review by Cyberboss — APPROVED** [review]

**Pull request merged**
