### PR TITLE
Fixes space vision

### LINKED ISSUE #29521: NVG's, thermals, etc make the user see stars outside of vision range instead of normal tiles
RID# 73852
self explanatory

### LINKED ISSUE #30510: Meson module in engiborg turns non visible tiles to spess tiles and can't be turned off.
[Note]: # (<B>Please enter the `Round ID` from the `Status` panel if you can!</B> If you believe the issue to be caused by a testmerge, please report it in its relative PR thread. State what the issue is from a "whats wrong" prospective. Issue reports should clearly allow maintainers to understand whats wrong and how to test/reproduce if that is not obvious. Avoid ambiguity. Start your issue report below both of these lines (or remove them))

[Admins]: # (If you are reporting a bug that occured AFTER you used varedit/admin buttons to alter an object out of normal operating conditions, please verify that you can re-create the bug without the varedit usage/admin buttons before reporting the issue.)

Round ID: 75843 (I am reporting this after the end of the round I meant to do it, so its not this one but the one that happened before in Basil)

This happened multiple times to me, but I'm unsure if its on my end or on yours.

I played engiborg a few times, and everytime I put the meson module on, it never gets turned off. Not only that, but any tiles I should see as dark/shadow/not seeing anything behind turns into a space tile. I tried putting the mesons back in storage, using the module (with y, hotkeys on) and reconnecting.

Its not something too big, but it is jarring to me, look into it if you can.

Note: I'm using the stable version of BYOND and not the beta as is recommended somewhere in the forums or wiki or something, I don't know, that may be it

### PR DESCRIPTION
**Pull request by AnturK**
Fixes #29521
Fixes #30510

### CODE REVIEW

**Comment by Supermichael777** [comment]
baised

**Comment by praisenarsie** [comment]
i liked this bug, whyyyyyyy 😭

**Review by Cyberboss — APPROVED** [review]

**Comment by KorPhaeron** [comment]
@AnturK This happens with night vision eyes (aliens etc) as well

**Review by Cyberboss — CHANGES_REQUESTED** [review]
What kor said

**Comment by optimumtact** [comment]
Then he can fix it in another PR you dummy

**Pull request merged**
