### PR TITLE
Singularities, but not gods, are now stronger than shuttles

### LINKED ISSUE #18763: Docking shuttles defeat lord singulo
If a singularity is in the shadow of a docking shuttle, it's deleted.

This is so not canon

### PR DESCRIPTION
**Pull request by ChangelingRain**
Fixes #18763

### CODE REVIEW

**Comment by Kromgar** [comment]
Whats with this americans need not apply meme?

**Comment by optimumtact** [comment]
Stop making pr's that have been denied already.

**Comment by ChangelingRain** [comment]
this isn't the pr that was denied

**Comment by Kromgar** [comment]
Orange's can't read

**Comment by Core0verload** [comment]
Yeah, that's better than the last one.

**Pull request merged**
