### PR TITLE
Adds mapping helpers to handle cyclelink & locking airlocks, updates all relevant maps

### PR DESCRIPTION
**Pull request by ShizCalev**
Closes #35652

Adds new helpers to handle cyclelinking & locking airlocks. 

The reasoning for this is to
1: Fix a number of broken icons on maps related to locked airlocks
2: Make it clear to mappers what it happening on the map without having to manually review an airlock's vars
3: Make it very obvious to mappers when there are issues with cyclelinking
4: Reduce the number of unique instances of vareditted items on maps

With these changes, I identified a **_very large_** number of incorrectly cyclelinked airlocks, and resolved all of said issue. Also went through and linked all unlinked airlock pairs where was it was necessary.

### CODE REVIEW

**Comment by WJohn** [comment]
Neat. I personally don't have much of a problem with var editing these things in, myself, but whatever improves clarity.

**Review by WJohn — APPROVED** [review]

**Comment by 81Denton** [comment]
@ShizCalev Dumb question, but how do I use the cycle link helper in Dream Maker? I only know how to link them by var editing.

**Comment by ShizCalev** [comment]
select /obj/effect/mapping_helpers/airlock/cyclelink and then place it ontop of an airlock. make sure the arrows are pointing towards the door you want to cyclelink it with.

image

example

**Comment by 81Denton** [comment]
Much more convenient than I thought, thank you.

**Pull request merged**
