### PR TITLE
Asteroid station fixes

### LINKED ISSUE #13370: These two APCs in asteroid maint are facing the wrong direction.
Easy fix, just change their dir to 2 for both of them.

### LINKED ISSUE #13896: asteroid station's robotics morgue tray faces the wrong way
the tray comes out to the right and clips into the wall

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
Shuffle robotics to fit the morgue tray in the correct direction. Fixes #13896

Fixes the weird APCs with bad directions in maint. Fixes #13370

Adds a dropper to virology

Fixes the toxins airlocks leaking heat #13374

### CODE REVIEW

**Comment by Zilenan91** [comment]
Can you fix this too https://github.com/tgstation/-tg-station/issues/13890

**Comment by KorPhaeron** [comment]
I'm bad at shuttles I'd rather not

**Comment by Jordie0608** [comment]
They just need plating tiles underneath them

**Comment by PKPenguin321** [comment]
while you're at it i think robotics doesn't have any empty medkits
if you could add a few that'd be tite

**Comment by tkdrg** [comment]
ok sure you don't have to fix every single issue on the map

**Pull request merged**
