### PR TITLE
Adds a config option to automatically reopen job positions of folks who suicide at roundstart

### PR DESCRIPTION
**Pull request by ShizCalev**
Config option, defaults to off.

Mostly to help counter mass-suicides at the HOP due to folks not liking a map leaving tons of jobs walled off. If 10 folks suicide at the start you'll be spending the next 10~ minutes just sitting at the console to reopen their slots (that is if you even have a HOP, and have enough player **connected** to the server to allow you to increase the number of slots.)

:cl: ShizCalev
add: Added a config option to automatically reopen the job positions of players who have suicided at roundstart.
/:cl:

### CODE REVIEW

**Comment by davethwave** [comment]
The reopen thing stops at 12 minutes ingame from what I can see

**Comment by PKPenguin321** [comment]
really good idea, hope this becomes the standard

**Comment by Bawhoppen** [comment]
This seems fair.

**Comment by Poojawa** [comment]
Make it tally the number of times they've done it in that job position, then auto-job ban. They clearly didn't want to play that role anyway.

honk.

**Comment by Bombpants** [comment]
@Bawhoppen A little off topic, but does the staff of healing revive suicided people?

**Review by Cyberboss — APPROVED** [review]

**Pull request merged**
