### PR TITLE
Reebe cogscarabs have infinite power and can recite scripture during non-clockcult rounds

### PR DESCRIPTION
**Pull request by ghost**
:cl: Xhuis
tweak: Cogscarabs can now experiment more freely with base design during non-clockcult rounds with infinite power and the ability to recite scripture!
/:cl:

Cogscarab shells always spawn no matter the round, as people have been figuring out. These scarabs can't interact with the station in any way, and they're meant so people can experiment with base designs during non-CC rounds. However, in practice, it's very difficult for them to do this because they have very little default power generation and no way to set up more, and they can't build actual defenses either.

Now, during non-clockcult rounds, scarabs have infinite building materials and can recite scripture so they can build out a more proper base that they might have been planning! *They are still unable to interact with the station in any way.* This is just to make experimentation less painful.

This functionality is tied to a new variable in construct shells, `infinite_resources`.

### CODE REVIEW

**Comment by Repukan** [comment]
What stops people from hosting their own server and practicing there?

Is there going to be support for blood cult, blob, nuke ops and other antagonist practice areas?

**Comment by KorPhaeron** [comment]
We need less things that rely on ticker.mode not more. Makes mixed modes more difficult

General concept is a good idea though

**Comment by Xhuis** [comment]
I was thinking about moving it to a global var called `reebe_operational` or something, so that admins could also varedit it to true if they want to make an actual cult.

@Repukan Not everyone wants to commit to downloading the source code just so they can learn how to play an antagonist. This is a smooth solution, and is especially relevant since one major portion of the antagonist (building) can be done without ever interacting with the crew - which the other antagonists you named cannot.

**Comment by KorPhaeron** [comment]
Whatever procs you call during game mode setup that turns on the ark could revert these shells to normal

**Comment by Xhuis** [comment]
This is ready for review.

**Review by Cyberboss — APPROVED** [review]

**Pull request merged**
