### PR TITLE
Loyalty Implant Icon Update

### PR DESCRIPTION
**Pull request by Ikarrus**
This is me trying out new styles for the loyalty HUD icon, for aesthetic reasons and to declutter the sec hud.

I'd rather not put the icon on the bottom icon, mostly because everyone already looks near the characters' heads for any icons because that's where they consistently appear.

Anyways, let me know what you guys think, these are just ideas that can be changed. 

This is what it looks like with this PR. I think it's quite noticeable, actually.
gif

This is a more subtle alternative we could use if people find the above too distracting
loyalty

For reference, this is what the HUD looks like now, worst-case scenario (sans med hud fuckery but that is a different beast):
leavenothingtotheimagination

### CODE REVIEW

**Comment by Lumipharon** [comment]
It makes it harder to tell if someone has a loyalty implant - by a lot.

**Comment by duncathan** [comment]
I dunno; by nature of the human eye a flashing border attracts attention better than a static image.

**Comment by Incoming5643** [comment]
if lizard tail wagging has taught me anything it's that any animation on a spessmen invokes intense scrutiny

**Comment by phil235** [comment]
I like it.

**Comment by Steelpoint** [comment]
While I prefer the current style, if I had to chose from the presented styles I would go with the obvious style.

**Comment by CosmicScientist** [comment]
I like the obvious one and whilst it means losing the neat N sprite, it looks a lot better like that.

**Comment by xxalpha** [comment]
Eh it's a good idea, but I don't like that sprite.

**Comment by Jalleo** [comment]
Make a couple of versions of the border flashing at different brightness levels a less bright one is probably better but only the eyes can tell which one would be best. (I think this maybe too noticeable atm.

**Comment by veganzombeh** [comment]
I prefer the subtle alter alternative personally.

**Comment by WJohn** [comment]
:+1:

**Pull request merged**
