### PR TITLE
Adds a new prefab circuit (2nd)

### PR DESCRIPTION
**Pull request by Carbonhell**
Prefab circuits, 2nd attempt ( https://github.com/tgstation/tgstation/pull/35973 )

:cl:
add: A new prefab circuit has been added. You can convert an assembly into a single circuit. To handle the new circuit pins, you need to prioritize, through the new wirer function, the pins you want to show up in the prefab circuit UI.
:/cl:

[why]: It's a very good mechanic to compress several circuits into one and making assemblies look cleaner

### CODE REVIEW

**Comment by Qustinnus** [comment]
muhfreeze

**Comment by Carbonhell** [comment]
don't tell me the freeze already started

**Comment by PKPenguin321** [comment]
i dont understand what this does can somebody hit me with the layman terms

**Comment by Shdorsh** [comment]
This looks nice. Can I haz it for modularized hippie circuits?

**Pull request closed without merging**
