### PR TITLE
Removes the xeno nest lavaland ruin

### PR DESCRIPTION
**Pull request by tralezab**
pr for just removing the eggs but keeping the ruin, close this if that gets in #43616

## About The Pull Request

removes the xeno nest lavaland ruin

## Why It's Good For The Game

this won't be very readable because i'm sleepy sorry

removes the xe- okay okay, so right now this ruin is massive, and with that a massive eyesore. The mobs inside are not the worst to fight but they are just simplemobs that sometimes shoot a projectile. The unique mechanic, the eggs, are a problem allowing the miners to create game ending antagonists. there is a pr if you want it to remove the eggs but keep the ruin, but I think the ruin is just really not worth keeping as we are removing its one unique mechanic (and sadly, that's a good thing)

## Changelog
:cl:
del: removes the xeno nest lavaland ruin
/:cl:

### CODE REVIEW

**Comment by tralezab** [comment]
and thanks JJR for already having this ready

**Comment by ATH1909** [comment]
I'd prefer to keep both the eggs AND the ruin, but if we're going to remove the eggs, I'd prefer to remove the ruin as well.

**Comment by knacker48** [comment]
If we do end up keeping the ruin I hope we atleast cut its size in half

**Comment by WJohn** [comment]
I'd prefer it be removed entirely, to be honest. Self-xenoing isn't cool, and having a neutered ruin lying around that looks ugly and doesn't even fit the surroundings (fire-avert xenos on a fire world???) is pretty bad.

Good on this PR 👍

**Comment by Daxxed** [comment]
The only good thing about this is the free baton as miner/ashwalker.
All other uses are grief and shouldn't be a thing, remove it.

**Comment by optimumtact** [comment]
This is a policy issue in the first instance because it can be configured off as a ruin at which point we'll remove it anyway.

Suggest you raise this via the headadmins first.

**Pull request closed without merging**
