### PR TITLE
Removes the white tiles in the kitchen hallway on Ice Box.

### PR DESCRIPTION
**Pull request by sergeirocks100**
## About The Pull Request

Self explanitory.

Before: [https://amel.pw/trevie/screenshots/Screenshot_154.png](https://amel.pw/trevie/screenshots/Screenshot_154.png)

After: [https://amel.pw/trevie/screenshots/Screenshot_153.png](https://amel.pw/trevie/screenshots/Screenshot_153.png)

## Why It's Good For The Game

They looked ugly, and they probably weren't supposed to be there.

## Changelog
:cl:
add: Removes the white tiles from the Ice Box kitchen hallway.
/:cl:

### CODE REVIEW

**Comment by RaveRadbury** [comment]
Those are clearly intended fringe. You don't accidentally something like that.

**Comment by sergeirocks100** [comment]
There was a cluster of 4 white tiles by the southern wall of the hallway by the kitchen, which i removed.

I did not touch the white tiles by the counter, which i assume you were referring to.

**Comment by RaveRadbury** [comment]
Could you please do a before and after shot to prevent such confusion?

**Comment by sergeirocks100** [comment]
Sure.

**Comment by RaveRadbury** [comment]
Oh! That looks like an artifact from a door that was removed or something.

**Comment by EOBGames** [comment]
I think the morgue door used to be across from the kitchen, on the old box medbay layout

**Comment by Twaticus** [comment]
oof my fault

**Comment by tgstation-server** [comment]
Your Fix/Feature pull request delta is currently below zero (-5). Maintainers may close future Feature/Tweak/Balance PRs. Fixing issues or helping to improve the codebase will raise this score.

**Pull request merged**
