### PR TITLE
botany buffs: mass produced emps?

### PR DESCRIPTION
**Pull request by ghost**
Discussed on coderbus a few changes to botany to give it some unneeded but helpful buffs
Adds iron as a reagent to steelcap, removing the grinding/injecting step in making emp plants. considering antags are the only ones who really use emps, yet other antags (clock cult, malf ai) have emps as a weakness, the crew should have SOME form of easy emps, even if they're ones with low aoe, like 25uranium 25 iron botany ones would be.

changes the amount of corn oil available in corn, and the amount of sulphuric acid available in your standard nettles, to streamline gylcerol production. That being said, its still so poor that you can't really produce viable grenades off the vine

adds the smoke trait to meatwheat, to give the smoke trait and meatwheat some love. meat decomposes into gas anyways, so it makes mild amounts of sense.

### CODE REVIEW

**Comment by jughu** [comment]
but meatwheat steaks are my favorite! it has all my love!

**Comment by optimumtact** [comment]
Can you justify the reason why you removed the grinding/injecting step for the steelcap?

This is removing gameplay difficulty without justification.

**Comment by jughu** [comment]
i mean steelcaps are litteraly made of metal why wouldnt they give iron? i mean metal does it maybe steelcaps technically should be too big for the grinder i mean realism and such oh wait... its a game

**Comment by ExcessiveUseOfCobblestone** [comment]
I demand a """QoL""" tag

**Comment by optimumtact** [comment]
@jughu that's not a justification for why a gameplay element was made less difficult

**Comment by vcordie** [comment]
> Can you justify the reason why you removed the grinding/injecting step for the steelcap?
Mostly to piss off ma44.

**Comment by optimumtact** [comment]
You're not doing a very good job at making me want to merge your pr

**Comment by vcordie** [comment]
People I discussed with said it's not a massive deal that one step is removed, and speeds up the process of making emp plants significantly. People generally DON'T make emp plants, because of that slow step of grinding and injecting into the glowberries with liquid contents. This should change that, and emp plants should see a surge in use.

**Comment by Crushtoe** [comment]
Don't nerf my nettles.

**Comment by jughu** [comment]
>nerfing nettles still wont stop my acid melons which burn a your clothes off and your nerfing nettles? Jesus

**Comment by ExcessiveUseOfCobblestone** [comment]
remove the gene machine

**Comment by vcordie** [comment]
I'm nerfing regular nettles, not death nettles.

**Comment by jughu** [comment]
WHY

**Comment by jughu** [comment]
OF ALL THE NETTLES YOU CAN NERF YOU DO THE REGULAR ONE

**Comment by Crushtoe** [comment]
Nettles don't need nerfing under the guise of a botany buff.

**Comment by vcordie** [comment]
regular nettles don't have robust weapon trait, so they don't really do much damage aside from the injected sacid. I've lowered the amount of sacid in them. It doesn't really matter at all except it makes producing gyclerol easier.

**Comment by jughu** [comment]
Close this pt

**Comment by vcordie** [comment]
Why?

**Comment by ma44** [comment]
The reason why I don't like this because it allows you to instantly make 13 gold bars a minute, and we all know what's going to happen when that's merged

**Comment by Kromgar** [comment]
@ma44 Cash lemons?

**Comment by vcordie** [comment]
you can already make a bunch of gold bars, not quite 13 a minute, but close, simply by grinding up the steelcap iron.

**Comment by ma44** [comment]
But that takes labor, you can do at most 5 gold bars in a large beaker + grinder, as the leftover reagents will fill up the beaker.

With this, you just click on the plant and insta 13 gold bars

**Comment by vcordie** [comment]
could adjust amount of gold in goldenapple to make it inconvinent then.

**Comment by vcordie** [comment]
and done. lowered amount of gold in golden apple from 0.2 to 0.15. can no longer trigger the reaction, without being much of a nerf

**Comment by vcordie** [comment]
actually, it takes 20 minutes for the first goldenapple to grow after you mutated for it, plus time to genemod it and get it up to 100 potency. by the time your producing gold bars, the shift is probably close to over. It really didn't need a nerf, now that I think about it. None the less, nerfed golden apples slightly to appease you, ma44.

**Comment by ma44** [comment]
Densified chemicals only increase max chem storage of the plant, not increase the amount of reagents in it

**Comment by kevinz000** [comment]
yeah no.

**Comment by vcordie** [comment]
reverting golden apple change on second thought, its enough of a grind that if you get it, you deserver your gold bar plants.

**Comment by vcordie** [comment]
commited the revert but github isnt picking it up for some reason

**Comment by Cebasiz** [comment]
>more EMP

no thx

**Comment by vcordie** [comment]
as if anyone other then antags use emps anyhow.

**Comment by vcordie** [comment]
On 80th thought, iron gene is a terrible, not good, very bad idea.

**Pull request closed without merging**
