### PR TITLE
Adds high-contrast inhand templates for spriters

### PR DESCRIPTION
**Pull request by ghost**
The new templates are in `__inhand_template.dmi` which is in the base inhands folder.

I made this because it's often unclear what parts of inhands should be cut out to accomodate for the actual "hand" portion. Very bright colors signify something that should _block_ a sprite (as if it's being held behind that part) and shaded parts are something that the sprite should be held _over._ For instance, the north-facing sprite has bright colors for all parts (as the human is in the way of the object) but the south-facing one is dark for all parts because it's being held directly towards the camera.

There are also more generic "solid" sprites, for those that don't care about the parts.

### CODE REVIEW

**Comment by Xhuis** [comment]
Are those ones you suggest for replacements, or ones that already exist? I'd like to have each body part be distinctively shaded, but I can easily make it much more obvious.

**Comment by FuryMcFlurry** [comment]
@ChangelingRain 
image

the west and east sprites have their hands out. I highlighted them

**Comment by Tokiko1** [comment]
This is incredibly helpful for clothing/new bodyparts too.

**Comment by Xhuis** [comment]
Now that you mention it, it probably is (although the parts-based one is probably the most useful for that.) I'm kind of curious why something like it never existed in the first place.

**Pull request merged**
