### PR TITLE
Makes claymore back wearable

### PR DESCRIPTION
**Pull request by AnturK**
And adds the sprite. Always ticked me off only katanas could do this. Don't ask how it works without sheath because it's :sparkles: magic :sparkles:

### CODE REVIEW

**Comment by Supermichael777** [comment]
Freeeeeedoooom

**Comment by optimumtact** [comment]
How does it work without a sheath?

**Comment by freerealestate** [comment]
velcro

**Comment by optimumtact** [comment]
Unvelcros katana

**Pull request merged**
