### PR TITLE
Adds Kor's requested radiation fail chance to nuclear egun and pins change

### PR DESCRIPTION
**Pull request by Bawhoppen**
Not my ideal solution, but compromise is a natural part of life.

@KorPhaeron 

Closes #32259 

:cl: R&D Balance Committee
del: RD's firing pins reduced from 5 -> 3
tweak: Advanced Energy Guns now produce radiation again.
/:cl:

### CODE REVIEW

**Review by ninjanomnom — APPROVED** [review]

**Comment by Bawhoppen** [comment]
Oh I guess you wanted it to irradiate when it recharged? I thought when you meant when it shot.
I can do that instead I guess

**Comment by Arianya** [comment]
Might as well include a "Closes #32259"

Also changelog

**Comment by ninjanomnom** [comment]
@KorPhaeron 
If we wanted to mess a bit with the radiation while we're at it here, repeated use could contaminate the gun with stronger and stronger radiation until it gets cleansed in the normal method for cleaning contamination.
`AddComponent(/datum/component/radioactive, strength, src)`
strength could get high when the gun is being overused in short periods

**Comment by Arianya** [comment]
I'm amused by the idea of the RD irradiating the station/random people by using an advegun tbh

**Comment by ninjanomnom** [comment]
it wont contaminate anything else unless you set the strength levels way too high

**Comment by Bawhoppen** [comment]
As it is, the fail_chance seems to only irradiate the gun itself and make the recharge function not work.
I'll change it to whatever Kor requests though

**Comment by evsey9** [comment]
seems like the adv e-gun will only be usable for engis as some space-police that patrol space because:
1. Radiation suits slow you down, a lot.
2. Engi hardsuits slow you down on station, a lot.
3. The suits I mentioned are the only ones that protect from radiation, as far as I'm aware

I'm not saying I'm against this PR, but just providing some info

**Comment by DoctoreMad** [comment]
Funnily enough I think this makes the stun setting it has more useful.

**Comment by ninjanomnom** [comment]
at lower levels, radiation is mostly harmless, just take care not to abuse the gun and use it too much and you'd be fine.

A contamination strength of 15 for the lower end and 50 max would be a good starting point to test it out

**Comment by Arianya** [comment]
The default engineer hardsuit only has 75 rad resist, so some rads will leak through. The CE hardsuit is the only one with 90 rad, while the RD hardsuit has 60 rad.

Bio suits have 80, radiation suits have 100, obv.

**Comment by ninjanomnom** [comment]
resist is percentage resist, not flat reduction

**Comment by Arianya** [comment]
So anyone in less then a radiation suit would get atleast a little radiated?

**Comment by ninjanomnom** [comment]
yes, but as I said low amount of radiation don't mean much

**Comment by ninjanomnom** [comment]
you need 300 radiation in your body to even start getting effects of any kind

**Comment by Slignerd** [comment]
I really don't like the idea of radiation being ordinary behavior - rather than giving it any sensible trade-off, it makes the guns not worth using at all.

I'd say that the current behavior of radiating the user when EMP'd is much better.

**Comment by Arzion5** [comment]
R&D items are supposed to be safe and without a fail rate. Either add a separate advanced e-gun in R&D that has slightly more material cost and/or higher research levels required or this PR shouldn't pass. It will become the very first R&D item that has a reliable chance to harm the user outside of human error.

**Comment by CPTANT** [comment]
RnD guns should be wacky and require creative use to be effective (but have to potential to be very powerful).

The advanced e-gun is just used as a regular gun.

**Review by nicbn — CHANGES_REQUESTED** [review]
Update the gun description, make it clear that it emmits radiation.

**Comment by Repukan** [comment]
Should make this stronger and add a small chance for explosion if EMP'd

It's supposed to be a prototype of a better HoS gun.

**Comment by Hatfish** [comment]
But the HoS's gun doesn't recharge, which makes the advanced egun a straight upgrade.

**Comment by Repukan** [comment]
*It's supposed to be a prototype of a better HoS gun*

**Comment by sawrge** [comment]
Make every R &D gun have a 2% chance of spawning a singularity

**Comment by sawrge** [comment]
Every gun has a 20% chance to fire every single shot at once in a random direction

**Comment by sawrge** [comment]
Every gun has a 8.99(repeating)% chance to misfire (this makes a farting noise and expends a charge but no projectile)

**Comment by sawrge** [comment]
Every gun has a 12.2818182828% chance to teleport out of the user's hand and into the target space (if fired at someone it goes in there hand)

**Comment by Bawhoppen** [comment]
@everyone All good ideas

**Comment by sawrge** [comment]
Every gun has a 1.3141573262% chance to become sentient, giving a ghost player control of when it fires and its firing mode like a pAI that shoots things

**Comment by MoreRobustThanYou** [comment]
The best part about this is that the RD wouldn't give a shit about irradiating everyone

**Comment by sawrge** [comment]
Every gun has a 5.69% chance be constructed as a random item of any type with that gun's sprite

**Comment by sawrge** [comment]
Every gun has a 3.444444444444444444444434343434445% chance of calling the shuttle every time it's shot

**Comment by MoreRobustThanYou** [comment]
@sawrge *shoots gun 30 times* THE EMERGENCY SHUTTLE HAS BEEN CALLED

**Comment by sawrge** [comment]
Every gun has a 4.20% chance of discharging random reagent smoke every time it's fired.

**Comment by sawrge** [comment]
Every gun has a 2.22% chance of blink-teleporting the user on fire.

**Comment by sawrge** [comment]
Every gun has a 0.21% chance of instantly vaporizing the user and target space

**Comment by MoreRobustThanYou** [comment]
@sawrge STOP SPAMMING MY NOTIFICATIONS

**Comment by sawrge** [comment]
Every gun has a 13.37% chance of opening a new PR requesting the removal of said gun

**Comment by sawrge** [comment]
Every gun has a 100% chance of sending @MRTY an email

**Comment by MoreRobustThanYou** [comment]
@sawrge your ideas SUCK ASS

**Comment by sawrge** [comment]
Every gun has a 10% chance of opening a news station and writing an article about gun violence

**Comment by sawrge** [comment]
Every gun has a 3.33% chance of sending a PDA message to a random person nearby

**Comment by sawrge** [comment]
Every gun has a 9% chance of being an antagonist

**Comment by DoctoreMad** [comment]
@sawrge Please elaborate

**Comment by sawrge** [comment]
On what

**Comment by DoctoreMad** [comment]
Most of those, please. I'm particularly curious about antagonist guns though.

**Comment by sawrge** [comment]
I think they are all self explanatory

**Comment by DoctoreMad** [comment]
Too bad because I don't

**Comment by GunHog** [comment]
I have said this before, and it bears saying again: This change will make the weapon useless for Security players. **An officer will not accept a weapon that kills him.** Doing this will make the weapon almost exclusively used by Science, not by Security.

The old drawback was that you had to either deconstruct several (wasteful) or fire and recharge it several times until you got the critical failure state, and then decon it. At that point, it becomes safe for Sec to use. Note: EMP had always worked to reverse this.

You need some way to make it work safely, or at the very less, give something to Sec to make it work properly. That, or require some sort of effort on the part of the Scientist to assemble or stabilize the weapon (which used to be the case). Player laziness alone would make a significant difference.

**Comment by Repukan** [comment]
You say that as if it isn't used by scientist players exclusively.

**Comment by Ratvar** [comment]
RD says, "oh guess i have more reasons to make myself into fire-spaceproof skeleton with xenobio just so nobody but me can use advanced egun hue hue hue hue"

**Comment by GunHog** [comment]
> You say that as if it isn't used by scientist players exclusively.

You say that as if no one from Security or other departments ever do. I do not have evidence to support my point, and neither do you, except perhaps our own memories.

**Comment by Slignerd** [comment]
> You say that as if it isn't used by scientist players exclusively.

I use the advanced energy gun as a Captain or a Security Officer.

**Comment by Jalleo** [comment]
I wish we had round end statistics of job roles holding created items in the round.

**Comment by Hatfish** [comment]
>RD says, "oh guess i have more reasons to make myself into fire-spaceproof RADPROOF skeleton with xenobio just so nobody but me can use advanced egun hue hue hue hue"

this is what will really happen, the egun is just going to become limited to science only.

**Comment by Iamgoofball** [comment]
>https://file.house/mwxE.png
>37 minutes from now

**Comment by Iamgoofball** [comment]
@KorPhaeron congrats you fell for R&D memelords changing the argument

**Comment by Mey-Ha-Zah** [comment]
I can see Security stealing a Miner's hard earned <a href="https://github.com/tgstation/tgstation/pull/30525">H.E.C.K. Suit</a> as it is a heavily armored Rad suit with no slowdown just so they can use the Advanced E-Gun without fear of being irradiated.

**Comment by sawrge** [comment]
@optimumtact all of tohse ideas were way better tahn wahtever stupid shit these r_Tards have been arguing about for two weks

**Comment by Robustin** [comment]
Im all for advanced eguns hurting the user again but 3 firing pins is a weak ass compromise. 

3 pins on a lot of RND's guns is still obscene. 

I also seriously doubt we're going to properly manage RND's gun balance, its only a matter of time before RND figures out a way around this or abuses some other gun instead.

It was simpler when RND could make guns and simply couldn't use them without help from security, cargo, or an emag (except maybe we scrap the emag gimmick).

**Comment by Arianya** [comment]
@KorPhaeron for Bawhoppen's question regarding radiation type and trigger

**Comment by YakumoChen** [comment]
@Robustin 

> (except maybe we scrap the emag gimmick).

why would you want to punish traitors for traitoring lmao

**Comment by Bawhoppen** [comment]
Alright, Kor has told me he wants a small rad pulse while it is recharging from use. I will get on that so don't  close this PR

**Comment by DoctoreMad** [comment]
@YakumoChen 
If we wanted to punish traitors for traitoring,we wouldn't be adding incentives to not rob the armory.
But much on the contrary, _you're the one promoting that!_ Imagine.

**Comment by optimumtact** [comment]
24 hours, clocks ticking

**Comment by Bawhoppen** [comment]
I have some real life distractions. I will return to this.

**Pull request closed without merging**
