### PR TITLE
adds v.a.t.s. system 

### PR DESCRIPTION
**Pull request by Tlaltecuhtli**
:cl:
add: press F to use radial body menu targetting system
removal: removed f old function (rotate intent)
/:cl:

gnome

pretty usefull to change body part to target while in combat or during a surgery
optionals:
- [ ] use real sprites
- [ ] change descriptions 
- [ ] maybe add for eyes and mouth?

### CODE REVIEW

**Comment by ExcessiveUseOfCobblestone** [comment]
> he doesn't know

**Comment by Tlaltecuhtli** [comment]
not everyone has numpad and its pretty clunky

**Comment by necromanceranne** [comment]
Also that requires taking your hand off the mouse so fuck that. Radials radials radials!

**Comment by SpaceManiac** [comment]
Looks like the `/var/jumping` could be removed as well?

**Comment by ATH1909** [comment]
But I liked using F as an intent change hotkey...

Maybe add an option where players can choose between the two?

**Comment by Tlaltecuhtli** [comment]
use g

**Comment by nemvar** [comment]
Crazy idea: Make hotkeys bindable.

**Comment by Therapist1** [comment]
Sounds like you have some footsteps mixed in with the vats sound effect.

**Comment by anconfuzedrock** [comment]
how about YOU use g

**Comment by Fox-McCloud** [comment]
>Crazy idea: Make hotkeys bindable.

This. And quite frankly, I think just having hotkeys for specific body parts would be...pretty useful at this stage.

**Comment by PKPenguin321** [comment]
I think this was a really smart change and if it can't be a hotkey it should at least have a button on the UI (maybe in the corner of the current zone selection panel) so that you don't have to pixel hunt for whatever zone you're trying to target.

**Comment by ExcessiveUseOfCobblestone** [comment]
numpad in hotkey mode does this already

**Comment by PKPenguin321** [comment]
So? Some people don't play hotkey mode, some people don't have numpads

**Comment by optimumtact** [comment]
I am not going to add a ui element that does the same thing as one that already exists.

if it's going to be used it should replace the existing one.

**Comment by PKPenguin321** [comment]
We totally could actually. Hmm

**Comment by nicbn** [comment]
This looks awful

**Comment by PKPenguin321** [comment]
The sprites do but the UI is solid, this is a great use for radials

**Comment by nicbn** [comment]
Uh please tell me yall are being sarcastic

**Comment by ExcessiveUseOfCobblestone** [comment]
> So? Some people don't play hotkey mode, some people don't have numpads

>I think this was a really smart change and **if it can't be a hotkey** it should at least have a button on the UI (maybe in the corner of the current zone selection panel) so that you don't have to pixel hunt for whatever zone you're trying to target.
>> ### if it can't be a hotkey

Maybe you meant this system in particular but I was simply responding to the statemeant "it" (which I thought was zone targeting) can't be a hotkey

**Pull request closed without merging**
