### PR TITLE
Spinward Threat Advisory: Making Dynamic Threat Announcements Make More Sense

### PR DESCRIPTION
**Pull request by EOBGames**
## About The Pull Request
Replaces the text for the Dynamic Threat announcements with a new set of threat advisories, to nail down SS13 as being in a single location rather than variable.
image
Additionally changes the text for progtraitor comms console hacks, for the same reason, and essentially reverts #67528's system of context-dependent messages due to being depreciated by these changes.

## Why It's Good For The Game
Nailing SS13 to a single location allows us to do more detail in the setting, as well as being more compliant with the lore (insofar as that matters) and reducing the need for odd reasoning for threat changes (how the hell do you change a station's orbit just like that? makes no sense).

## Changelog

:cl:
add: Nanotrasen has implemented a new system of Threat Advisories to inform stations of the relative Dynamic threat to their stations by sector.
/:cl:

### CODE REVIEW

**Comment by itseasytosee** [comment]
Lame

**Comment by anclandor** [comment]
> Nailing SS13 to a single location allows us to do more detail in the setting, as well as being more compliant with the lore (insofar as that matters) and reducing the need for odd reasoning for threat changes (how the hell do you change a station's orbit just like that? makes no sense).

I really like the idea that it isn't just one station.  I mean, ss13 gets destroyed 25% of the time, and the characters remember previous shifts where it was destroyed.  NT probably just has like a ton of ss13 class stations right?  I mean, the stations layout is even physically different!

**Comment by wesoda25** [comment]
Bit of a bikeshed but these star colors aren't very intuitive given the actual alert levels go in a different order. The old ones spared us that confusion at the very least.

**Comment by EOBGames** [comment]
> Bit of a bikeshed but these star colors aren't very intuitive given the actual alert levels go in a different order. The old ones spared us that confusion at the very least.

I'm not quite sure what you mean- these progress in Green > Blue > Yellow > Orange > Red > Black > Midnight, alert levels go Green > Blue > Red > Delta, so the colour progression is the same?

**Comment by wesoda25** [comment]
My apologies my brain doesn't work

**Pull request merged**
