### PR TITLE
Fixes pink slime potions.

### LINKED ISSUE #11708: pink slime potion dosent work
ingected with plasma produced the slime potion an invisible item that didnt work.

### PR DESCRIPTION
**Pull request by harmonyn**
Fixes https://github.com/tgstation/-tg-station/issues/11708.

I SWEAR TO FUCK IF THERE ARE ANY OTHER BUGS I'LL... complain and salt and fix them I guess

:(

### CODE REVIEW

**Comment by Bluespace** [comment]
bandit fixing xenobiology one pr at a time.

**Comment by bgobandit** [comment]
bluespace doing absolutely nothing, ever, except getting permabanned

**Comment by Supermichael777** [comment]
the item was invisible at the time does this fix that? (to deep into code for me to get)

**Comment by bgobandit** [comment]
Yes.

**Pull request merged**
