### PR TITLE
Adds alternative more fitting peacekeeper borg skin

### PR DESCRIPTION
**Pull request by Niknakflak**
image

Adds the freedomhound borg skin for peacekeeper borgs.  A couple things to note off the bat

- I did this in class because I was bored.  Didn't really try to code it since I knew there would be overlay problems with peacekeeper borg eyes since service borgs at least have the same shape and being in class on shitty college internet that doesn't allow IRC, help was impossible plus someone mighta shot it down before I even at least made the meme PR.  

- I randomly looked in my sprite folder and looked for something easy to code because holy shit I'm bored
  This happened to something that popped to mind.

- Before the BritishDefenseForce attacks this, it's also a Jab at the United States since we are known for sticking our military dick in places that it shouldn't always go.  The name goes along with the meme of the USA "keeping the peace" and they still can't harm anyone even though they look like sec borgs.

- Feel free to comment about code changes that need to be done or if this is destined to be closed, at least it helped curve the boredom that is my professor reading code aloud line by line.

- I have no idea where the sprites came from, normally I just use this as an admin meme thing to replace a borg sprite or maybe for an event.  Could be a deterrent to the PR.

 :us: :us: :us: :us: :us: :us: USA USA USA USA  :us: :us: :us: :us: :us: :us:

### CODE REVIEW

**Comment by GunHog** [comment]
Time to try and tack on as many AMERICAN PARODIES to this as we can!

**Comment by optimumtact** [comment]
Need russian, uk, french, german, chinese, indian and canadian sprite sets before I can merge this sorry

**Comment by BeeSting12** [comment]
Just sprite it as a middle finger as it's intended purpose was to be a middle finger to sec borg players.

**Comment by kevinz000** [comment]
can this be a choice i like being an egg D:

**Comment by Niknakflak** [comment]
it is you dumb butt

**Comment by RemieRichards** [comment]
Bad PR

**Comment by meeeeme** [comment]
This is a goof PR with slightly more effort put into it.

**Comment by Niknakflak** [comment]
THE BRITISHDEFENSEFORCE HAS ARRIVED

**Review by Cyberboss — APPROVED** [review]

**Comment by ChangelingRain** [comment]
This is an awful sprite.

**Comment by Jalleo** [comment]
Its not American enough - A british guy. 

Seriously it look like there is a english flag on the sides. Its just off center.

**Comment by Tacolizard** [comment]
yeah it looks more british than american. It's also ugly as hell. super oversaturated.

**Comment by RemieRichards** [comment]
Been 2 days, no body likes this.

**Comment by Niknakflak** [comment]
Let it go on the record that everyone who downvoted are salty britfucks

**Comment by optimumtact** [comment]
when you comment like this, it just makes you look like the salty one

**Comment by Niknakflak** [comment]
I knew the British defense force would come, didnt know it would be spearheaded by remie

**Comment by optimumtact** [comment]
Americans might get more done if they didn't spend all their time throwing their toys out of the cot when they ran into cultural differences

**Comment by Niknakflak** [comment]
I would say something about new zealand but new zealand doesnt do anything period

**Pull request closed without merging**
