### PR TITLE
Adds Directional Presets To Several Common Wall Mounts For Mapping

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request
Turns a lot of shit like this:
image

Into this:
image

# This has zero effect on gameplay and I will laugh at you if you say it does.

## Why It's Good For The Game

Less headache for mappers when placing wall mounts, as they now no longer have to search through 30 instances of the same thing to find a fire alarm that is in the right direction.

## Changelog
:cl:
add: Directional subtypes to common wall mounts for mapper use
/:cl:

### CODE REVIEW

**Comment by Ghommie** [comment]
Good luck to anyone willing to spend hours doing the most monotonous task of replacing map-edited wall mounts with the presets through dozens of different .dmms.

**Comment by Paxilmaniac** [comment]
> Good luck to anyone willing to spend hours doing the most monotonous task of replacing map-edited wall mounts with the presets through dozens of different .dmms.

This isn't meant to replace every single wall mount, as some are in wall corners, or need to be varedited in whatever way they are, but if someone really feels like they want to, nobody is stopping them

**Comment by bobbahbrown** [comment]
> Good luck to anyone willing to spend hours doing the most monotonous task of replacing map-edited wall mounts with the presets through dozens of different .dmms.

probably wouldnt be that hard to get a majority of them if they follow the same pattern as these new presets

**Comment by AnturK** [comment]
Use the path replacement script and include it in the directory.

**Comment by MMMiracles** [comment]
> 
> 
> Use the path replacement script and include it in the map_scripts directory.

good luck with that lmao half of those var edits aren't even consistent with their pixel changes

**Comment by Paxilmaniac** [comment]
> > Use the path replacement script and include it in the map_scripts directory.
> 
> good luck with that lmao half of those var edits aren't even consistent with their pixel changes

I mean, technically speaking ok, anything with a positive pixely, north, negative pixely, south. Same for pixelx.
The only situation that'd concern me with that is anything that has edits to both for whatever reason.

**Comment by Mothblocks** [comment]
> This has zero effect on gameplay and I will laugh at you if you say it does.

> puts it in changelog anyway

**Pull request merged**
