### PR TITLE
Mining skill now can be gotten from plasma cutters(x0.25) and KC

### PR DESCRIPTION
**Pull request by SmArtKar**
## Changelog
:cl:
balance: Mining skill now can be gotten from plasma cutters(x0.25) and KC
/:cl:

### CODE REVIEW

**Comment by Fikou** [comment]
plasma cutters giving exp basically makes it so you can get the cloak every single round as miner, and you didnt make the mining skill affect either of them, just make them give exp

**Comment by Qustinnus** [comment]
you aren't supposed to get exp from the plasma cutter, this was intended.

**Comment by LemonInTheDark** [comment]
You haven't explained why this is good for the game. My gut says I don't want it, but I'll give you a chance to elaborate on the reasoning

**Comment by Jhyrachy** [comment]
I think that as mining is now, giving any incentive for miners to actually mine stuff would be appreciated.

I mean, after all the mining nerfs, right now people mine the bare minimum to get the 777 points needed for the skeleton key and then is time for gamers loot.

Mining is essential for the station (who is not tired of hearing engi and science screaming on comms that they need more mats) but it has been quiet gutted of any fun and is more of a chore then anything else.

**Comment by ExcessiveUseOfCobblestone** [comment]
remove the boring bits instead of giving them more tbh

**Comment by Mothblocks** [comment]
i don't like it

**Pull request closed without merging**
