### PR TITLE
Updates space-heater sprite to 3/4, updates icon

### PR DESCRIPTION
**Pull request by MrDoomBringer**
[saw an earlier PR like this](https://github.com/tgstation/tgstation/pull/33595), but they didnt revamp sprites: so i stole the pallet from some of the newer sprites and made this.

:cl: MrDoomBringer
imageadd: NanoTrasen has sent the station new spaceheaters! They look nicer now!
/:cl:

[~~video of it in action~~](https://gfycat.com/ThirdJaggedAmericanshorthair)

### spriting-general testimonies: 

image

image

### CODE REVIEW

**Comment by ACCount12** [comment]
The old one looked like an outdated heater. This one doesn't look like anything at all.

**Review by ShizCalev — APPROVED** [review]

**Comment by ShizCalev** [comment]
@ACCount12 modern space heaters are vertical yo
image

**Comment by Xhuis** [comment]
I like the retro aesthetic a lot more! It's more fitting of SS13 to me.

**Comment by MrDoomBringer** [comment]
@Xhuis i tend to agree, but I feel like the old heaters are less "retro" and more.. just old-timey? I could make some adjustments if it would fit that theme better though.

**Comment by ACCount12** [comment]
SS13 is full of this "old-timey" stuff. Like, we have laptops and even _tablets_ that accept floppy disks, PDAs have monochrome screens and cartridge slots.

**Comment by MrDoomBringer** [comment]
@ACCount12 yeah, that's true, but i was referring to how specifically machinery in ss13 seems to be sprited in a more high-tech way than handheld devices or computers. (all of science, autolathes, PDA Printers, engineering machinery, smoke machines, etc etc).

The space heater is a machine both code-wise and ingame: It's only ever used in emergencies (after a fire or hull breach) , rather than as furniture or personal effect (where a retro-aesthetic would be more fitting?)

**Comment by Xhuis** [comment]
Even so, I'm somewhat attached to the old sprite and aesthetic. Like I said, though, I guess I'm not really *opposed* to this, just dislike it a slight bit compared to the old one.

**Comment by ACCount12** [comment]
Maybe one of the reasons I don't like it is that it doesn't look like a machine to me. It seems more like an in-hands item.

**Comment by praisenarsie** [comment]
there i am gary! the frog!

**Comment by WJohn** [comment]
Yeah this does come off as too small, and also a bit too modern. I get that ss13 is a mix and match of new and old technology, but I think old technology works best here.

While the animations *are* fancy, I don't think those are enough to save them. The object itself is not very interesting to look at, it's just a tall and thin rectangle. Granted, the other one didn't look very interesting either, being a box on legs, but the point here is to try and come up with a more unique shape and (still retro) design.

**Comment by Bawhoppen** [comment]
I mean in reality were we had always had the modern variant, and someone tried to change it to our current one, people would say the exact same thing about "it fitting better"

**Comment by Armhulen** [comment]
a bit too modern

fuck man hahaha

**Comment by MrDoomBringer** [comment]
update: took ideas into consideration, howabout this?:
image

**Comment by Xhuis** [comment]
I like that a lot better, but it looks like a piece of industrial machinery more than a space heater. Do I know how to fix this? Nope, no idea.

**Comment by ACCount12** [comment]
Much better. Still looks off, but this time it may be because I'm too used to the old one.

**Comment by WJohn** [comment]
It's an improvement, but yeah it still needs work. I may take my own spin on this shortly, see if I can throw some colors and designs I like for it. I do really like the centerpiece -- the heating looks really nice -- and with some tweaking around the surrounding box it could be made pretty great.

**Comment by optimumtact** [comment]
You need to either include a custom name in the change log or remove `optional name here` or it will literally call you optional name here

**Comment by Iatots** [comment]
dumb fruit

**Pull request merged**
