### PR TITLE
Fixes c4 not working on shutters

### PR DESCRIPTION
**Pull request by Razharas**
Fixes c4 not working on shutters

### CODE REVIEW

**Comment by Dorsisdwarf** [comment]
Actually, is this even a fix?

**Comment by Cheridan** [comment]
> //"BLAST" doors are obviously stronger than regular doors when it comes to BLASTS.

**Comment by Razharas** [comment]
C4 is supposed to destroy its target, it takes down rwalls ok, surely shutters arent as strong as rwalls

**Comment by Razharas** [comment]
For a reference, long ago when i was reworking ex_act and c4 to not be ass the intent of the "target" argument was exactly to destroy a thing if its passed to itself as argument in ex_act() so c4 can destroy things in closets and boxes and shit without completely obliteration the turf it happens on with ex_act(1) while letting minor explostion ex_act(3) affect things in boxes and lockers(and people sometimes but that was removed)
Unless someone seriously nerfed c4 and intended so its not supposed to destroy its target anymore this pr is a fix

**Pull request merged**
