### PR TITLE
Lavaland raptor barn improvements 

### PR DESCRIPTION
**Pull request by Draggeru**
## About The Pull Request

This PR re-maps the lavaland raptor barn to:
1. Have bridge access from public and regular mining so people are not forced to build one themselves
2. Give the area a bit of spice to look more visually interesting
3. Gives anyone working on raptors less of a giant walk to go eat

pee arr

<details><summary>In game screenshots</summary>

Merde Stopover Theta 2024-07-14 165108

Merde Stopover Theta 2024-07-14 165104

Merde Stopover Theta 2024-07-14 165059

Merde Stopover Theta 2024-07-14 165036

Merde Stopover Theta 2024-07-14 165031

</details>

## Why It's Good For The Game

It seems like a major oversight that there was no reliable walkway to and from the barn. Additionally, the barn currently looks out of place. This PR makes it a cohesive themed area, making it more comfortable and attractive to interact with while fitting better into the overall "on lavaland" theme.

## Changelog

:cl: Thedragmeme
qol: re-maps the raptor barn to not stick out like a sore thumb
fix: Miners and the public both can access the raptor barn without having to make a bridge themselves
/:cl:

### CODE REVIEW

**Comment by Cheshify** [comment]
I like it, solid lil bit of mapping to make engaging with a feature better.

**Comment by Draggeru** [comment]
All AT's removed and no changes are planned, ready for review

**Comment by EricZilla** [comment]
I did always wonder what kind of fucked up asbestos hay they are using down there

**Comment by san7890** [comment]
yea i think it should be accessible roundstart

**Pull request merged**
