### PR TITLE
Removes asteroid station

### PR DESCRIPTION
**Pull request by tkdrg**
The map has been broken ever since the first pathing change.
We're also not allowed to touch it. So, it's time for it to go. RIP

### CODE REVIEW

**Comment by ike709** [comment]
fix not remove please, this is turning into a boxstation dictatorship

**Comment by RemieRichards** [comment]
@ike709 if you'll read the PR desc, we're not allowed to fix the map, the mappers don't want us to touch it, so we can't fix it, so were dropping all support for it.

**Comment by CorruptComputer** [comment]
Don't remove it, were planning an update this week. After that anyone will be able to edit it.

**Comment by tkdrg** [comment]
This is going to be updated apparently.

**Comment by paprka** [comment]
Box is the best map who fucking cares

**Comment by Atskadan** [comment]
god damn it

**Pull request closed without merging**
