### PR TITLE
[s]Fixes ass photo copying allowing you to open the sandbox spawn panel

### PR DESCRIPTION
**Pull request by Iamgoofball**
also updates the april fools branch

### CODE REVIEW

**Comment by duncathan** [comment]
dude you can't let them know
it's a warning this time next time it's a repo ban baby

**Comment by Xhuis** [comment]
It ain't hard to make a new branch's base /upstream/April-fools-branch.

**Comment by PKPenguin321** [comment]
that title lmao

**Comment by Bawhoppen** [comment]
@Cheridan see goof is doing it too

**Pull request closed without merging**
