### PR TITLE
Makes runtime not save family if killed

### LINKED ISSUE #16793: Catsplosion still happening
The kitten stretches out for a belly rub.
The kitten wags its tail.
The kitten wags its tail.
The kitten stretches out for a belly rub.
The kitten shakes out its coat.
The kitten shakes its head
The kitten grooms its fur.
The kitten shakes its head

end my suffering pls

### PR DESCRIPTION
**Pull request by Shadowlight213**
Finally brings an end to catsplosion. As long as runtime is alive, their legacy will grow, when they die, the slate is wiped clean
Fixes #16793

### CODE REVIEW

**Comment by Dorsisdwarf** [comment]
Kinda resolves #16793

**Comment by Incoming5643** [comment]
doesn't really resolve it, just kinda hides it.

**Comment by lzimann** [comment]
it's a dumb feature to begin with tbh

**Comment by Zilenan91** [comment]
Thank fuck

**Comment by Shadowlight213** [comment]
For the record, before this change, the only way to get rid of runtime's family was to kill every cat EXCEPT for runtime FIRST.

@Incoming5643 All the other pets punpun and ian "reset" their persistence stuff on death, so it makes sense that runtime should as well.

**Comment by GunHog** [comment]
She should respawn as a kitten if she dies, imo.

**Comment by optimumtact** [comment]
It seems logical and a way to slow down the cat spam.

**Pull request merged**
