### PR TITLE
baton left click right click swapped, code improvements

### PR DESCRIPTION
**Pull request by tralezab**
## About The Pull Request

Now uses attack and alt-attack instead of params, left and right click swapped (left click always harm, right click is a special action from the item)

## Why It's Good For The Game

Code improvements always good, consistency for combat mode buttons. I've played sec and I absolutely just could not stop beating the shit out of people because of the left and right click swap that only happens on stunbatons.

## Changelog
:cl:
tweak: swapped the left and right click for stunbatons. oh my god, no more beating the snot out of prisoners!
/:cl:

### CODE REVIEW

**Comment by RaveRadbury** [comment]
Looking forward to all the investigations we'll be doing because newfriends "didn't know" they were harmbatoning someone with the **primary click** of a _stunbaton_

**Comment by Pugie** [comment]
Stunning with a stun baton is a special interaction how shocking.
No that isn't a pun, this pr makes me sad

**Comment by Son-of-Space** [comment]
I don't like this at all. The primary action of the stunbaton should be to stun unless you're on combat mode. The primary action ALWAYS being harm is really silly.

**Comment by Jared-Fogle** [comment]
I'm still on the fence about this. Both control schemes have the same goal--making it more understandable for new players.

On one hand--left click stun, right click harm. This is meant to be easier for new players to understand because left click is likely the obvious option they're going to choose when attacking someone for the first time.

On the other--left click harm, right click stun. This is meant to be easier for new players to understand because right click is generally non harmful actions, while left click is for harmful actions.

I don't know if I like the precedent the last one (this PR) sets. I want the understanding going forward to be "left click is *probably* what you want, right click is the alternate action", which this breaks.

Let me know what you think.

**Comment by Qustinnus** [comment]
what moth said above is basically what made me do it in the first place, but im pretty neutral on it.

**Comment by optimumtact** [comment]
well I'm not floyd but surely

out of combat mode
left click primary - stun
right click alt - stun but you also shout stop resisting like an american cop

in combat mode
left click stun + harm
right click stun

**Comment by Jared-Fogle** [comment]
What oranges said sounds fine to me.

**Review by Mothblocks — CHANGES_REQUESTED** [review]
Do what oranges said, I think it's the best we can do.

Make it clear in the description, so ideally people aren't constantly switching combat mode because they don't realize they can just right click.

**Comment by necromanceranne** [comment]
Have you considered just having it do harm when it's actually turned off?

**Comment by optimumtact** [comment]
I think you should shutup

**Comment by ATH1909** [comment]
> I'm still on the fence about this. Both control schemes have the same goal--making it more understandable for new players.
> 
> On one hand--left click stun, right click harm. This is meant to be easier for new players to understand because left click is likely the obvious option they're going to choose when attacking someone for the first time.
> 
> On the other--left click harm, right click stun. This is meant to be easier for new players to understand because right click is generally non harmful actions, while left click is for harmful actions.
> 
> I don't know if I like the precedent the last one (this PR) sets. I want the understanding going forward to be "left click is _probably_ what you want, right click is the alternate action", which this breaks. Furthermore, it's not obvious to a new player that the stun baton has a right click action to begin with. Sure we can put it in the description, but are new players examining every item they have? Do we _want_ them to be doing that?
> 
> Let me know what you think.

personally, I think it's okay if new players start out harmbatonning instead of disarmbatonning; harmbatonning will still stun your target if your baton is off of cooldown, so it'll still get the job done, and then the HoS or warden or whoever can berate their new recruit for handling their prisoners too roughly.

> well I'm not floyd but surely
> 
> out of combat mode
> left click primary - stun
> right click alt - stun but you also shout stop resisting like an american cop
> 
> in combat mode
> left click stun + harm
> right click stun

this sounds good to me, except maybe the "stop resisting" part (that (saying a phrase on each baton strike) should be a sechailer setting, if anything).

> Have you considered just having it do harm when it's actually turned off? It'll teach those seccies an important advanced detainment technique for battery conservation.
> 
> Stunning is still a combat related act, and I may want to be in combat mode when I go to stun someone, but I don't want to flip my mouse button presses the other way to do that. Floyd already said we should keep combat related interactions to combat mode, and I think that should be equally valid for nonlethal attacks too.

note that making harmbatonning only possible with a turned off baton will affect the dps of chainstunning someone to death with a baton (because your stunning strikes won't deal damage), and also doesn't address what we should do with telebatons, which turn into tiny little pocket-sized thingies when not "on".

> I think you should shutup

there's no need to be rude to anne here, oranges, they're just giving their opinion (and some of their thoughts on the subject) after mothblocks specifically asked for people to post their opinions.

**Comment by optimumtact** [comment]
you should also shutup

**Comment by tralezab** [comment]
Doing what oranges wants

**Comment by tralezab** [comment]
>losing GBP for this

**Pull request closed without merging**
