### PR TITLE
Attachable Seclite & Camera to Helmet

### PR DESCRIPTION
**Pull request by GunHog**
Steals #8109
This is a continuation of @Steelpoint's Security helmet cameras and flashlights PR. As he as given up on the PR, I have yoinked it and made a copy of my own. I will work on updating this and getting it up to merge-able status.

<b>My modifications to his work:</b>
- You can now make Securitrons with Sec helmets.
- Helmet cameras now function as borg cameras do. They will update the
  chunk on the next game tick, if the camera moves.
- Helmet cameras are now vulnerable to EMP (camera alarm is not
  triggered). EMPing a Sec officer as a means of silencing him is still viable!
- Removed the extra canAttachCam lines.
- Paid my tithe to Lord of Changelogs.

_I want to revisit this later and make the helmet cameras work for more helmets, by having the camera sprite be an overlay. I will save that for another PR if this one makes it in. I do not want to go too far outside the scope of Steelpoint's original PR._

### CODE REVIEW

**Comment by Steelpoint** [comment]
Make sure to do a changelog with all relevant information.

**Comment by GunHog** [comment]
I will, or Jordie will burn me alive until I give him his blood sacrifice.

**Comment by Jordie0608** [comment]
I'd like to point out this again as it wasn't addressed previously.
https://github.com/tgstation/-tg-station/pull/8109#issuecomment-76896852

**Comment by GunHog** [comment]
I will address it in my next commit.

**Comment by Giacom** [comment]
Have you fixed the issue with the AI's freeroam camera system? https://github.com/tgstation/-tg-station/pull/8109#discussion-diff-25768670

**Comment by GunHog** [comment]
Yes, Gia. I simply had the camera check for movement via its process() stage.
 https://github.com/GunHog/-tg-station/commit/46ca095f2b98122709a0cdf3ef175d1f9857ec0a#diff-c09680be30f12b96e9d70193e415f6ffR345

**Comment by Jordie0608** [comment]
I was able to put a seclite onto the gladiator and lasertag helmets, which broke their sprite. Camera didn't attach to them however.

**Comment by Jordie0608** [comment]
If you make a secbot assembly with a /helmet/sec that has a camera and seclite on it; when you disassemble the assembly it drops only a /helmet.

I think once that is fixed this'll be good for merge.

**Comment by GunHog** [comment]
I made it a bit more consistent. I could not think of a better way to do it than this, to make sure what you put into an assembly is what you get out.

**Comment by GunHog** [comment]
YAAAAAAAAAAAAAAAY <3

**Comment by Lumipharon** [comment]
Extremely important question, can you helmets with cameras on them (or even just the helmetcam) lying around (or say inside a locker) and still view it via the camera console?

**Comment by RemieRichards** [comment]
@Lumipharon yes.

**Comment by Miauw62** [comment]
this will need rebalancing or a revert.
https://tgstation13.org/phpBB/viewtopic.php?f=10&t=3247
AI is already an omniscient god, doesnt need to be moreso
officers can already be tracked multiple ways
this forces antags into either using a very specific subset of items or just going loud.

etc.

possible solutions:
* suggest w_class 3 cameras that film only if they're in your hand or on the floor. (my personal favorite)
* make camera helmets not have armor
* make camera helmets lategame research items

**Comment by Steelpoint** [comment]
That's a very close vote and I don't think a revert would be fair in only so little time.

Why don't we simply remove the AI's ability to view the camera's mounted in the helmets? Make it a Sec Console only thing.

**Comment by Miauw62** [comment]
I'm not talking about the vote.
I think the player arguments contra are valid and that this is too powerful.

**Comment by Steelpoint** [comment]
If the AI is the problem then take my suggestion above, AI's can still track via normal cameras anyway.

Personally now though people are less hesitant to bum rush Officers because now they have a good chance to get seen, also Warden's/HoS's are incentivised to stay on the brig.

**Comment by Miauw62** [comment]
you mean people can't take down officers at all because help arrives immediately. maint doesn't have any cameras, so this is really just cutting out the middleman.

**Pull request merged**
