### PR TITLE
[MAP] Readds Security Morgue 

### PR DESCRIPTION
**Pull request by Steelpoint**
It appears the sec morgue and other similar sec changes were accidently deleted in a prior map PR, this PR readds it to the game.

Link to prior merged PR: https://github.com/tgstation/-tg-station/pull/10443

Pics

### CODE REVIEW

**Comment by Aranclanos** [comment]
edit the OP with a screenshot of it

**Comment by duncathan** [comment]
morgue
from the original PR

**Comment by xxalpha** [comment]
It shouldn't have those exterior r-walls actually.

**Comment by Steelpoint** [comment]
Also for the issue of transperancy.

The exact things this PR readds that were removed are as follows.

The Morgue
The shuffled Sec Hardsuit Lockers
The Warden's medkit.

These were all in the original merged PR but they were accidently removed.

@xxalpha The R-walls replaced the space facing r-walls the insane ward had.

**Comment by optimumtact** [comment]
99% of the sec area is rwalls to space anyway

**Comment by xxalpha** [comment]
Yea but don't put r-walls there, it's bad. We already had this discussion.

**Comment by Aranclanos** [comment]
to be fair it would be pretty shitty to take the time to dismantle a r-wall to discover a morgue tray.
like SMES back then with the AIs

**Comment by Supermichael777** [comment]
actualy if the complaint was that the rwalls were pointless would flipping the room help? or would we need directional, deconstruct-able morgue trays first?

**Comment by Aranclanos** [comment]
I don't see the r-walls as an 'issue'. But I find them silly, considering that there are normal walls next to it.
And personally I hate anything related to giving security their own murder room, straightjackets, kill-injections and now morgue but idk thats just me

**Comment by Iamgoofball** [comment]
@Aranclanos 

i'll check out buildable morgue trays

**Pull request closed without merging**
