### PR TITLE
bitrunning - implements objects

### PR DESCRIPTION
**Pull request by jlsnow301**
## About The Pull Request
Atomized #77927
The core pieces of bitrunning. Does nothing on its own, nothing without the rest

Note: If anything, this should receive more scrutiny than any other piece.

## Why It's Good For The Game
See #77259
## Changelog
:cl:
add: Adds new machines for bitrunning - quantum server, console, vendor, and netpods.
add: Adds bitrunner avatars and the shared damage link.
add: Adds bitrunning host monitors to visualize host health.
/:cl:

### CODE REVIEW

**Comment by Time-Green** [comment]
make it GREEN CHECKMARK

**Comment by jlsnow301** [comment]
> make it GREEN CHECKMARK

it won't, it's so atomized that it's not functional. See: https://github.com/tgstation/tgstation/pull/77927.
i made these just so people can look at the internals better

**Comment by Time-Green** [comment]
Wait uhhhhh… So what do we review? This is confusing me

**Comment by jlsnow301** [comment]
> Wait uhhhhh… So what do you want reviewed? This is confusing me

I would definitely appreciate reviewing the code you see here, above all, as it's the core pieces. I got to thinking (given its tremendous size) getting the individual bits approved would help the main PR get merged.

**Pull request closed without merging**
