### PR TITLE
Adds glass floors (That work with multi-z)

### PR DESCRIPTION
**Pull request by ghost**
:cl: Qustinnus (sprites from Lohikar)
 code: Open-space now has a parent /transparent/ that handles the visuals of open-space besides the backdrop
 add: Glass floors and reinforced glass floors. Look at those peasants down below in style.
/:cl:

image

i got the sprites from this closed pr on aurora https://github.com/Aurorastation/Aurora.3/pull/4385

### CODE REVIEW

**Comment by Qustinnus** [comment]
image
 works even on the bottom floor now

**Comment by Qustinnus** [comment]
(they also show wires and stuff like plating does now)

**Comment by Qustinnus** [comment]
Updated the code a bit, the bottom floor now uses whatever baseturf the lowest z level has set, this means that glass floors on lavaland show basalt rock.

**Comment by FloranOtten** [comment]
Does Clarke break them?

**Comment by Qustinnus** [comment]
no

**Comment by Qustinnus** [comment]
wait that thing breaks everything wtf, well idk ive never used the clarke

**Comment by tmtmtl30** [comment]
are these tiles applied to plating, or are they independent from plating? it feels like it would be weird to apply glass to opaque metal and suddenly that metal becomes seethrough.

**Comment by Qustinnus** [comment]
theres no construction path atm but theyd go over plating, you could just say you're switching the plates on the plating

**Comment by deathslayer2481** [comment]
If you have non-reinforced glass floors can you bash a hole in the floor to cause a breach?

**Pull request merged**
