### PR TITLE
removes rotting map files

### PR DESCRIPTION
**Pull request by grungussuss**
## About The Pull Request
removes unused map files
## Why It's Good For The Game
muh file size
## Changelog
:cl: grungussuss
del: Removed old, rotting map files
/:cl:

### CODE REVIEW

**Comment by JohnFulpWillard** [comment]
it's not fully dead since admins can spawn them in at will and even replace existing/broken shuttles with them

**Comment by Sadboysuss** [comment]
> it's not fully dead since admins can spawn them in at will and even replace existing/broken shuttles with them

image

also are you only talking about whiteships or all of them

**Comment by Loafin34** [comment]
call me crazy but i think whiteships still spawn. I remember the ant one vividly

**Comment by DaCoolBoss** [comment]
The whiteships spawn ingame. The whiteship dock ruin if it's selected as a spaceruin will pick a random shuttle from the list and these are all valid choices. Should probably rename them from station names to avoid confusion, because they're not tied to any specific station map.

**Comment by Sadboysuss** [comment]
> Another renaming there methinks, since Birdshot exists on this fork and Kilo doesn't.

I didn't rename any files

**Comment by DaCoolBoss** [comment]
Yeah I'm saying it should be renamed to shuttles/labour_birdshot instead, to avoid confusion.

**Pull request closed without merging**
