### PR TITLE
Revert "REMOVES COATS OF IGNORANCE"

### PR DESCRIPTION
**Pull request by optimumtact**
Reverts tgstation/tgstation#18421

### CODE REVIEW

**Comment by KorPhaeron** [comment]
Coward

**Comment by JJRcop** [comment]
:)

**Comment by optimumtact** [comment]
Coward this

**Comment by Jazaen** [comment]
So... The merge token system is no more?

**Comment by optimumtact** [comment]
Correct

**Comment by ike709** [comment]
Why? Seemed like a good system.

**Comment by optimumtact** [comment]
It didn't really have much of an affect on the issue count.

most of the early gain was me closing old issues

**Comment by PKPenguin321** [comment]
oh wait what no more merge tokens?

**Pull request merged**
