### PR TITLE
changes hypertool sprite

### PR DESCRIPTION
**Pull request by Fikou**
## About The Pull Request

gooder sprite

## Why It's Good For The Game

i am scared of the old one

## Changelog
:cl:
imageadd: Adjusted hypertool sprite.
/:cl:

### CODE REVIEW

**Comment by carlarctg** [comment]
the new one is worse

**Comment by wesoda25** [comment]
the new one is better

**Comment by trollbreeder** [comment]
Not sure what to say about the new icon, but i definitely prefer the older one.

**Comment by ATH1909** [comment]
> Not sure what to say about the new icon, but i definitely prefer the older one.

What if we just added a new subtype of the hypertool null rod form that used this new sprite, so that chaplains could choose between the old and new sprites.

**Review by Cyberboss — APPROVED** [review]

**Comment by TheVekter** [comment]
Does it vibrate?

**Pull request merged**
