### PR TITLE
Makes the ERT commander's sword great again

### PR DESCRIPTION
**Pull request by vuonojenmustaturska**
:cl: Naksu
fix: Chaplains are once again unable to acquire the inquisition ERT commander's sword, as intended. The sword has been restored to its former glory
/:cl:

### CODE REVIEW

**Comment by DaxDupont** [comment]
This still allows the regular chainsword I hope

**Comment by fludd12** [comment]
`why was this not the first solution`

**Comment by vuonojenmustaturska** [comment]
augh this is no good, the code requires a better fix

**Comment by Tlaltecuhtli** [comment]
what does it fix

**Comment by vuonojenmustaturska** [comment]
@Tlaltecuhtli chaplains being able to acquire ERT equipment

**Comment by Bombpants** [comment]
What was the ert equipment?

**Comment by ExcessiveUseOfCobblestone** [comment]
@DaxDupont it does not.

**Comment by vuonojenmustaturska** [comment]
it allows the regular chainsword but not the sentient one

**Comment by GuppyLaxx** [comment]
kinda sucks it's the possessed one and not the normal one, but oh well

**Review by Cyberboss — APPROVED** [review]

**Pull request merged**
