### PR TITLE
Makes halloween species change only affect humans and lizards

### PR DESCRIPTION
**Pull request by Shadowlight213**
It was messing up ayys.

### CODE REVIEW

**Comment by optimumtact** [comment]
It's one day a year. They'll get over it.

**Comment by TheDreamweaver** [comment]
Not true. They hate zombies, thats it.
.

**Comment by TheDreamweaver** [comment]
They hate zombies, not the whole species change.

**Comment by Shadowlight213** [comment]
@optimumtact they complained enough to get it disabled in the config..

**Comment by AdamElTablawy** [comment]
The species change actually fucks over abductors when it hits since they can't use their shit anymore @optimumtact

**Comment by optimumtact** [comment]
Add a check for the person being a human/lizard then, this event seems like harmless fun once a year to me.

**Comment by TheDreamweaver** [comment]
Good fix

**Comment by optimumtact** [comment]
remove speed mod slowdown on zombie and move to infectious

**Comment by bgobandit** [comment]
I think you underestimate the degree to which the players hate this

**Comment by optimumtact** [comment]
I think you overestimate the degree to which I care about peoples feelings for a 3 day event that happens once a year at a predictable time.

**Pull request merged**
