### PR TITLE
Makes husking harder, adds husk healing to instabitaluri

### PR DESCRIPTION
**Pull request by kriskog**
## About The Pull Request
Prerequisite to #48668 

Makes husking take a bit more burn damage, up to 300 from 200. Main reason is to prevent easy husking with a welder. Husking in fire should still happen pretty consistently, you just dont husk the moment you die.
Adds curing of husking to instabitaluri when the total burn damage is less than 50. It is replacement flesh, after all. @ExcessiveUseOfCobblestone thoughts?

## Why It's Good For The Game
Husking is pretty challenging to deal with, often making people resort to braining and cloning. Makes it a bit harder to husk someone intentionally, and gives doctors a tool to fix it.

## Changelog
:cl: Skoglol
balance: Husking now requires more burn damage before it happens.
balance: 100u instabitaluri (synthflesh) can now cure husking when burn damage is below 50.
balance: Roundstart beaker of instabitaluri removed from all stations.
/:cl:

### CODE REVIEW

**Comment by Tlaltecuhtli** [comment]
how about a machine that "rehidratates" the husks instead of magic chems

**Comment by blobbernaut** [comment]
You mean a high level cloner?

**Comment by Iatots** [comment]
You can't turn a cooked steak back into a cow bit without magic chems.

**Comment by optimumtact** [comment]
you could use the cyro to rehydrate people, seems thematic and the machine already exists.

**Comment by kriskog** [comment]
They are burned to a crisp, instabitaluri is synthetic flesh. Seems pretty thematic to me. It has the drawback of loading up heavily on toxin damage. At least 90% sure old synthflesh fixed husking as well.

Thats not to say cryo cant fix husking, but it is already a bit of a magic machine much like the cloner. Put someone in, they get fixed at pretty much no effort and resource cost.

**Comment by ExcessiveUseOfCobblestone** [comment]
https://github.com/tgstation/tgstation/pull/48726#issuecomment-573342180

**Comment by kriskog** [comment]
Now requires 75u in the body (they dont metabolize since its dead) and less than 100 burn damage. Roundstart beakers of instabitaluri removed from the crates on all maps, leaving only the vendor and chemistry instab available.
To unhusk someone you now need more than one spray or medkits worth of instab, so its gonna cost you (them).

**Comment by ExcessiveUseOfCobblestone** [comment]
DNM since I just merged the other PR and want to get """data""".

**Comment by kriskog** [comment]
Allright, fair enough. I might split out the heightened requirement to husk, as the other PR doesnt touch on that and it is an important thing imo.

**Comment by ExcessiveUseOfCobblestone** [comment]
https://github.com/tgstation/tgstation/pull/48726/files#diff-b8589c5a1a2ec97e844ba32c2f55400aR206

if you could define this as well as the synthflesh req and have it as 1 number (I don't care which) i'm okay with merging this.

not really able to get the observations i want considering cloning is still in so people have no reason to make rezadone in the first place so this might be changed after the removal if I find it to be too simple.

**Review by ExcessiveUseOfCobblestone — CHANGES_REQUESTED** [review]
^

**Comment by kriskog** [comment]
Allright, done. Treshold is 50, now needs 100 instab to cure, added some feedback text.

**Pull request merged**
