### PR TITLE
bazelart sprites, fikou animation: resprites hierophant

### PR DESCRIPTION
**Pull request by tralezab**
## About The Pull Request

Animations when fikou is finished with that, but just to get rid of the "Needs Pictures" label:
image

resprites the hierophant.

- [ ] replace held and worn sprites
- [ ] grab animations whenever ready from fikou and implement em'

## Why It's Good For The Game

it looked bad

## Changelog
:cl: bazelart spriting, fikou animation
imageadd: resprited the hierophant, it's less ugly!
/:cl:

### CODE REVIEW

**Comment by Ghommie** [comment]
I'm going to miss that soulful square in a square head.

**Comment by bastardblasted** [comment]
the item/club looks very different from the main thing

**Comment by Sheits** [comment]
Might be worth respriting the arena too since this uses a completely different colour palette, which I do like better and seeing a darker arena would be neat as hell

**Comment by tralezab** [comment]
will address some issues with the hilt

will consider respriting the area but no promises

@bastardblasted i'm kinda sad about this but there really is no way to preserve the detail well

**Comment by Sheits** [comment]
also, animations!! even just adding an idle hover for the boss would make it better I think and would take like 2 seconds

**Comment by notfrying1pans** [comment]
ngl the hierophant tele isn't noticable enough, and just looks like a weird purple cyborg head

**Comment by tralezab** [comment]
i don't think I can do it justice tbh.

can i beat "square with diamond on a stick" yes

can i also redo all the effects and the arena along with it? i don't think I have the time, skill, commitment, or

**Pull request closed without merging**
