### PR TITLE
Rearrange Delta library gaming room to host D&D parties

### PR DESCRIPTION
**Pull request by timothymtorres**
## About The Pull Request

This moves things around so that the curator's private room represents the center stage for D&D gaming.  Alternatively, the AI holopad is strategically located in the center for their participation as well.  I added box of toy action figures to gaming room so people can use them to represent their D&D characters.  Moved the pAI into the main library section.  Removed the dresser.  Better positioning for atmos pipes for library.

<details>
<summary>Before:</summary>

StrongDMM_wTxlvn90N9

</details>

<details>
<summary>After:</summary>

StrongDMM_0vqVKRbnUc

</details>

<details>
<summary>After: (zoomed in with filters applied)</summary>

StrongDMM_m3fNB90xwN

</details>

## Why It's Good For The Game

This helps set a better atmosphere for library gaming room to be used for gaming activities.  The curator will have more flexibility with managing gaming events.

## Changelog

:cl:
qol: Rearrange Delta library gaming room to host D&D parties
/:cl:

### CODE REVIEW

**Comment by BlueMemesauce** [comment]
holy shit that is sick as fuck

**Comment by wesoda25** [comment]
Just rearrange it

**Comment by YakumoChen** [comment]
I think this is missing the camera range for the AI to see enough to participate unless I can't see a right side cam

**Comment by timothymtorres** [comment]
> I think this is missing the camera range for the AI to see enough to participate unless I can't see a right side cam

Nice catch.  Added two additional cameras to the right side for full coverage.

**Comment by Learner10** [comment]
Holy shit, that looks awesome.

**Comment by YakumoChen** [comment]
> > I think this is missing the camera range for the AI to see enough to participate unless I can't see a right side cam
> 
> Nice catch. Added two additional cameras to the right side for full coverage.

Three might be too many for a very low security area, would recommend two at most, with good spacing

**Review by Maurukas — APPROVED** [review]

**Pull request merged**
