### PR TITLE
Makes plant bags hold a lot more seeds and plants

### PR DESCRIPTION
**Pull request by ma44**
as title says

### CODE REVIEW

**Comment by GunHog** [comment]
No need for a plantbag of holding, then!

**Comment by PKPenguin321** [comment]
:-1: 50 is already a ridiculous amount with things like killer tomatoes

**Comment by ma44** [comment]
@GunHog >implying dropping 1000 seeds/plants wont create lag

**Comment by ma44** [comment]
@PKPenguin321 you should now be able to only hold 50 plants, but can also hold up to 100 seeds (if plants weight class is 2)

**Comment by PKPenguin321** [comment]
oh well that should be fine

**Pull request merged**
