### PR TITLE
[WIP] Paperwork-Adjacency Polishing Part 1

### PR DESCRIPTION
**Pull request by 00-Steven**
## About The Pull Request

Decided to make this a draft so I don't forget about it while investigating other code jank.

This is the first out of multiple prs I planned for polishing up some of the paperwork-adjacent systems.
This specific pr covers the wall clocks, calendars, and most importantly the photocopier.
The former two can be crafted with an iron sheet and 5 paper respectively, while the photocopier is now a proper buildable machine with its own circuit board in the same node as fax machines.

Now normally photocopiers have fees associated with them, but it'd be weird if built photocopiers have fees and it'd be weird if you couldn't build the roundstart photocopiers. This pr solves that by letting you add a card reader to add a payment component and assign an arbitrary budget/account for the 5cr fees to go into, while only mapload photocopiers get this automatically for the civil budget. You can remove this with a crowbar, but it'll shock you for trying. 
Additionally only mapload photocopiers get their free paper and toner, if you build one yourself you have to do it yourself.

Then, remember the fax lets you fax the Syndicate when emagged, I thought it'd be funny if emagging the photocopier let you print syndicate-themed forms. Not necessarily *useful* ones, but fun or interesting ones. It currently does so by adding a `blanks_syndicate.json` config and swapping out which config it uses based on emagging status.
As of writing, this is still unfinished.

Finally the photocopier has so many interactions that it can be a bit awkward, so I'm adding context to it.

As this is still a draft, following is a list of things that still need to be done for this to be finished.
### To-do list:
- [ ] Add photocopier panel open sprite
- [ ] Write up a few more syndicate-themed forms
- [ ] Actually convert the already written up forms to the right format and add them to the config file
- [ ] Remove debug nanotrasen forms from syndicate forms config file
- [x] Make photocopier dump empty paper on deconstruct in some way
- [x] Try use interact instead of attackby/somesuch where applicable

## Why It's Good For The Game

Paperwork is fun. I love paperwork. But it's really annoying that some of these fancy little office things are not normally buildable, especially given they simply don't exist on some maps.
Want to build an office and respond to faxes? You're either gonna need to go across the map each time you need a photocopier, or steal it and let no one else use it.
This sucks, so I'm fixing it.
## Changelog
:cl:
add: Wall clocks are now buildable, crafted using 1 iron sheet.
add: Calendars are now buildable, crafted using 5 paper.
add: Photocopiers are now buildable, as a circuit at the same tech node as fax machines. They require a laser, scanning module, and servo, and start empty and without associated fees.
add: The 5cr photocopier fees can now be removed from existing photocopiers by crowbarring it while open, or added by adding a card reader to it while open. The latter lets you assign an arbitrary budget/account for it to put the fees into.
add: Emagging a photocopier replaces its standard forms with syndicate-themed ones. Enjoy using this together with the emagged fax.
qol: The photocopier now has usage contexts.
/:cl:

### CODE REVIEW

**Comment by 00-Steven** [comment]
Aight so, for my own sanity's sake, probably just gonna do like three syndicate forms and call it a "other prs can go and add more" deal, and then finish the rest of the pr

**Comment by 00-Steven** [comment]
Well that's done, but proooobably going to need to make them drop a paper bin at some point, or let paper bins scoop up all paper on a turf

**Comment by 00-Steven** [comment]
wild how I can get myself to do multiple fixes in a day and then spend months on having a funky feature cycle between stale-not-stale

**Comment by Sadboysuss** [comment]
I really want this, you can do it! You can finish it!

**Comment by optimumtact** [comment]
make a new pr if you want to take this up again.

**Pull request closed without merging**
