### PR TITLE
[dnm] The stonerone gets high and ~~webedits~~ breaks the MC.

### PR DESCRIPTION
**Pull request by MrsTonedOne**
The MC will no longer run a second time in the same tick if there was paused subsystems and at least 30% of the tick remaining. because of the extools change, the assumption that 30% of a tick meant that there was still 10% left for the mc is no longer valid, and i doubt this system was helpful enough to warrant trying to make it work with extools.

The MC will no longer tell a subsystem to run with a 0% tick allotment. the overhead of starting a subsystem up only to have it process 1 thing and sleep is silly. and likely the cause of so many ssgarbage induced lag spikes if the 1 thing it did was a hard delete.

The MC will no longer hard lock in a loop if given a subsystem with both background, and no_tick_check flags.  (no subsystem currently has both flags) (I feel like I've fixed this bug before)

var editing the priority of a paused subsystem no longer takes until the next fresh fire to take effect. (this allows one to low the priority of a long running subsystem (looking at you atmos) without waiting for it to do 1 full loop thru its queue to take effect, as this could take whole minutes.)

### CODE REVIEW

**Comment by LemonInTheDark** [comment]
What the absolute fuck

**Comment by actioninja** [comment]
unbelievable levels of based

**Comment by ATH1909** [comment]
oh god oh fuck

**Comment by ATH1909** [comment]
image

damn, and here I was thinking I had a record (on /tg/)

**Comment by Qustinnus** [comment]
kevinz has way more @ATH1909

**Pull request closed without merging**
