### PR TITLE
add cims to engineer and chief engineer tablets

### PR DESCRIPTION
**Pull request by Sparkezel**
## About The Pull Request
what it says on the tin

## Why It's Good For The Game
I'm pretty sure most of people new to engineering don't even know this application exists. I hope this will make it less tedious to use and popularise it more.

## Changelog
:cl:
qol: Engineers and CE have NT CIMS installed on the tablets from the start
/:cl:

### CODE REVIEW

**Comment by Time-Green** [comment]
Does this work? CIMS can't be downloaded on the tablets, only the big computer

**Comment by zxaber** [comment]
CIMS can be installed on any mod-PC device, not just the consoles.

**Comment by maxymax13** [comment]
it should come on that laptop in the engineering lobby so it has a reason to exist

**Comment by Time-Green** [comment]
> CIMS can be installed on any mod-PC device, not just the consoles.

Apparently I couldn't install it because I needed to insert my ID, my fault

**Pull request merged**
