### PR TITLE
Chasms will glow dimly, like lava

### PR DESCRIPTION
**Pull request by ChangelingRain**
:cl: Joan
tweak: Chasms will glow dimly, like lava.
/:cl:

Closes #27496
Another other alternative to chasms being unlit instakill pits.

### CODE REVIEW

**Comment by Kromgar** [comment]
Brighter pls

**Comment by KorPhaeron** [comment]
Neat

**Comment by KorPhaeron** [comment]
Do you think it'd clash too much with lava if the glow was more necropolis red coloured

**Comment by ChangelingRain** [comment]
I dunno really I'm not sure what color to use anyway. Brighter isn't super possible since its values are pretty close to lava's values already

**Comment by Repukan** [comment]
Ye this is pretty good. With the lights one carries it'll stand out too.

**Comment by FantasticFwoosh** [comment]
HUGBOX

Why does a bottomless pit emit light? Least you could be enough of a sensible person to simply walk, doesn't this make your lava chasm PR irrelevant?

**Comment by Grazyn** [comment]
It's an eerie glow emanating from below. The pit isn't actually bottomless. But you don't want to know what's down there.

**Comment by YakumoChen** [comment]
it's a dwarf fort reference nerd

**Comment by Niknakflak** [comment]
This looks way more ambient and cool, holy shit.

**Comment by Steelpoint** [comment]
This is nice.

**Pull request merged**
