### PR TITLE
Makes Sec Members know Krav Maga at Roundstart

### PR DESCRIPTION
**Pull request by ExpAntique**
:cl: optional name here
add: Added Krav Maga implant to list of Sec member's implants.
/:cl:

[why]: # Sec was too easy to shit on, used to know krav maga automatically on (((/tg/))) took it away. Full reasons and autistic arguements here:
https://hippiestation.com/threads/have-all-sec-guards-know-krav-maga.8253/

New and retarded, pls correct.

### CODE REVIEW

**Comment by QualityVan** [comment]
Hey buddie i think you got the wrong repo, the hippie club is two blocks down

**Comment by SgtxRootbeer** [comment]
Enough to make a man :thonk:

**Comment by ExpAntique** [comment]
Wrong repo, rip.

forget i was here

**Comment by 81Denton** [comment]
This really makes me 🤔

**Comment by PKPenguin321** [comment]
also to clarify since i added this to /tg/
hippie before the rebase had a completely different version of krav maga i think, not sure how it worked but theirs was different from ours. we never gave it to all of sec but almost did when i was first implementing it since i wasn't sure exactly who in security to give it to

**Pull request closed without merging**
