### PR TITLE
Bot heat resistance

### PR DESCRIPTION
**Pull request by GunHog**
:cl: Gun Hog
tweak: Nanotrasen has improved the coolant system in the stations automated robots. They will no longer violently explode in hot rooms.
/:cl:

Bots will no longer be affected by temperature.

### CODE REVIEW

**Comment by Cheridan** [comment]
Is there any reason in particular for this

**Comment by anconfuzedrock** [comment]
just a theory but I had a pai in a cleanbot but then heat killed it and smells kidnapped the pai so thats my theory on why

**Comment by Alek2ander** [comment]
Wouldn't a better solution be _not running into fire_?

**Comment by Jordie0608** [comment]
Yeah I don't see much reason for this, whats wrong with how it is?

**Comment by GunHog** [comment]
Because losing bots, especially pAI bots to overheated rooms, especially floorbots and medibots, is annoying, and they usually do not get fixed.

>Wouldn't a better solution be not running into fire?

Just high temperatures is enough. Of course, sentient bots have no way of telling this, and non-player bots are not capable of escaping. Bots, before they were made into simple animals, did not have a vulnerability to temperature.

**Comment by PKPenguin321** [comment]
I usually see the opposite. A medibot is vaguely near a cold breach (because it was going towards all the injured people that were cold from the breach) and suddenly dying violently, presumably from temperature

**Comment by GunHog** [comment]
I will test this, but are you sure there was no damage from fire at all in the area?

**Comment by PKPenguin321** [comment]
Iunno. Could've also been low pressure that did it.

**Comment by Alek2ander** [comment]
Now cold is another matter, bots should definitely have immunity to cold and low pressures (because floorbots).

>Just high temperatures is enough. Of course, sentient bots have no way of telling this, and non-player bots are not capable of escaping.

Give environment alerts to simple animals. Non-sentient bots can abort patrol when taking damage, maybe return to last checkpoint as well. Could also alert the station AI so it can manually reroute them.

**Comment by optimumtact** [comment]
It's a gunhog buffs his personal army pr

**Comment by optimumtact** [comment]
Did not mean to do that

**Comment by AnturK** [comment]
Simple animal atmos alert would probably be more appropriate if this is issue with pAI bots.
 
When making them simple animals i didn't transfer the old heat resistance because it seemed to mostly stem from objects not having easy way to interact with atmospherics rather than actual decision.

**Comment by GunHog** [comment]
It is not just pAI, it is any bots just up and dying in hot areas. Their destruction usually goes unnoticed, and the expectation that bots do not get hurt by heat, as they were before. I had figured it was an oversight.

>It's a gunhog buffs his personal army pr

Comments like this is why I hesitated for so long to make a PR. For the longest time, I was the only one who cared about them until AnturK made them into simple animals. I cannot improve anything without being a meme, it seems. I cannot help it that no one else cares or thinks they should not be exploding so readily.

I want to make a more extensive improvement to bots in the same vein of what was done for minebots - giving them action buttons and better control of themselves. This change was on my list, but since I believed it to be a one-line change with little significance to the game at large, I made it separate to get it in faster. I did not think anyone would oppose or care, nor did I expect to have to explain myself.

**Comment by Cheridan** [comment]
merging this before gunhog has a meltdown

**Comment by Chocobro** [comment]
>there is no warning or even knowledge that temperature is a bad thing for robots

excuse me
it's a computer why does it not have a temperature warning
feature request

**Pull request merged**
