### PR TITLE
[MAP] Boxstation/Mining Fixes and Board Additions

### LINKED ISSUE #10754: Box map tech storage missing boards
Checked it out on dm; Not sure if this is intentional or not but there's no circuit imprinter or exosuit fab boards in tech storage.

I remember them being there before, so perhaps this is an oversight?

### LINKED ISSUE #10837: BoxStation's maint bar has a vent set to suck air in, not push air out.
read title ^^^^

### LINKED ISSUE #10840: Mining dorm airlock sprites, seen through mesons, are honked up
What happened: http://i.imgur.com/EcT1KTq.png

Why this is bad: HONK!

Additional details: I tested a bunch of other doors, all of them seemed to be fine. This is mesons only.

### PR DESCRIPTION
**Pull request by Steelpoint**
This PR fixes or address the following issues.

Fixes https://github.com/tgstation/-tg-station/issues/10754 - Box map tech storage missing boards
Fixes https://github.com/tgstation/-tg-station/issues/10837 - BoxStation's maint bar has a vent set to suck air in, not push air out.
Fixes https://github.com/tgstation/-tg-station/issues/10863 - Box mapping errors.
Fixes https://github.com/tgstation/-tg-station/issues/10840 - Mining dorm airlock sprites, seen through mesons, are honked up

Changelog included.

### CODE REVIEW

**Comment by xxalpha** [comment]
You have to write Fixes #123456 for it to autoclose the issues.

**Comment by Steelpoint** [comment]
Neat.

**Comment by Jalleo** [comment]
@Steelpoint merge conflicts

**Comment by Steelpoint** [comment]
I'll fix it tomorrow.

**Pull request closed without merging**
