### PR TITLE
Health HUD for plants

### PR DESCRIPTION
**Pull request by MTandi**
image

## About The Pull Request

"Plants are people too!" &copy; - NutriMax

Health HUD now shows plant health and status depending on weed, pests, toxicity, being dead.

## Why It's Good For The Game

Good extra feature for health HUD.

## Changelog

:cl:
qol: Health HUD shows hydrotray plant health and illness depending on weed, pest, toxicity level
/:cl:

### CODE REVIEW

**Comment by Mothblocks** [comment]
i think this should be a new hud item that botanists could potentially get, not put on health hud

**Comment by BlueMemesauce** [comment]
The red dot on the hydroponics tray is fine enough, I dont really think there's ever a need to constantly see the exact health. But I don't play botany that often so botanist mains might think otherwise.

**Comment by MTandi** [comment]
> The red dot on the hydroponics tray is fine enough, I dont really think there's ever a need to constantly see the exact health. But I don't play botany that often so botanist mains might think otherwise.

I don't think that they need it too. I just saw that health HUD shows health of walking plants and thought it makes sense that it should do the same thing for static ones.

Not sure if this deserves a separate HUD.

**Comment by RealityOverseer** [comment]
As someone who has played a bit of botany if it could show nutrients and water it'd be a amazing addition for botanist gameplay in regards to making it far easier to manage multiple plants and be able to tell what needs what with just a glance. The Plant HUD would be a very cool addition for botany in my opinion.

**Comment by Mothblocks** [comment]
if this isnt on another hud item then i dont wan tit

**Comment by Comxy** [comment]
Plant Hud sounds funny and it kind of makes sense for a futuristic space game

**Comment by MTandi** [comment]
I will actually make a proper  botany HUD, I guess, that will be a mix of health and diagnostic HUD from game's perspective. @CoiledLamb mentioned that he already has a nice sprite for it.

**Pull request closed without merging**
