### PR TITLE
Replaces sleepers in medical with another cryo tube

### PR DESCRIPTION
**Pull request by ghost**
ss 2015-01-17 at 01 17 14

Also adds a circuit board for a sleeper in medical storage should research actually provide parts.

### CODE REVIEW

**Comment by spheretech** [comment]
Whats wrong with sleepers?

**Comment by paprka** [comment]
everything

**Comment by AlexCrimson** [comment]
This is the worst option you couldve gone with. So now Medical will just throw people in Cryo rather a sleeper. Its no different.

**Comment by Steelpoint** [comment]
If your going to do this, you need to re add the ability to be able to resist out of Cyro Cells.

**Comment by spheretech** [comment]
I think medical in general is way too easy. Its easier to just bruise kit/ointment someone or showe a antitox pill in their face rather than sleepering or cryo. And you can do it anywhere. I'd be up for bays medical...

**Comment by Miauw62** [comment]
what is the reasoning for this

**Comment by Steelpoint** [comment]
Hell, if we're getting Goon Chem why not do the rest and get Goon Med?

**Comment by paprka** [comment]
a) cryo has disadvantages
b) it's slower than traditional medicine
c) it doesn't work if you're wearing your hardsuit

none of the above described sleepers, which is why an additional cryo tube is replacing them. it is completely different. cryo is generally used for cloned people or people in crit, so the number of people who will be like 'put me in cryo' is extremely small. most of the time !!actual medics!! might be required to do !!actual medicine!! instead of push a button on the sleepers.

**Comment by Chocobro** [comment]
i'd prefer if you at least kept a sleeper in like the bottom of the recovery room. that place doesn't really need four beds.

**Comment by Dorsisdwarf** [comment]
Make sleepers not work through hardsuits.

**Comment by Nyvrem** [comment]
If the medbay makes a  good cryomix cryo is faster than sleepers, actually.

**Comment by pudl** [comment]
with goon chemistry, cryo is about to recieve an amazing buff.
at below 240k it heals burn, brute, and tox damage at 3 per cycle. organ and brain damage are removed.

**Comment by Actionb** [comment]
By removing sleepers without changing anything else around medbay you are simply putting more emphasis on inventory juggling, tedious body part aiming and chemists actually doing their job. Competent chemists are rare; when playing CMO or MD, I end up having to do the mixing myself most of the time - and when there IS a 'competent' chemist, why bother involving the MD's at all when you can just spam Tricord or DD?
If you feel that the sleeper is too 'fire and forget' (that is, shove patient in, press buttons, throw patient out while he's healing on his own), why not make the sleeper slowly heal somebody at a steady rate. With extra options for more specialized medicine like alkysine or imidazoline.
Besides all that... cryogenics is even more boring than sleepers. Just throw a patient in, go play with your balls for 5 seconds, shake patient up. Cryo is REALLY fast when you make a robust mix with many healing chemicals. And it's REALLY awful with a retarded MD not stripping your space suit and/or the default mix.

**Comment by Anonus** [comment]
You can't spam tricord or DD anymore because we're goonchem now, silly.

**Comment by GunHog** [comment]
:-1: This is bad, and not even needed since the chemistry system got replaced. Medbay is for healing people, and needs to be able to do it well and properly. If you want to play MD, you should *go outside* and heal people instead of sitting around the medbay all day.

**Comment by AnonymousNow** [comment]
Mmm-mmm-mmm, more medbay nerfs, thick and fast. Looks like doctors are on the coders' hitlist!

**Comment by paprka** [comment]
i'll give you 5 minutes to go figure out who added defibrillators anonymousnow, and preferably stop shitposting

i don't intend to nerf medical doctors, only make them more relevant than sleepers and medibots as far as wound healing goes.

cryo is much more robust than sleepers anyway, especially with the new chems, so..

**Comment by palpatine213** [comment]
As Steelpoint said. Could you please add the ability to resist out of cryo if your going to do this?

**Comment by paprka** [comment]
mmk

**Comment by Iamgoofball** [comment]
:-1: conflicts with my goonchem PR changes to sleepers
do not merge this

**Comment by paprka** [comment]
...Or, make the changes to cryo instead?

Does your PR even affect their ability to infinitely distribute chemicals, goof? I don't care about the balance or quality of the chemicals, as long as they're 'press button to chemical' cryo tubes will remain infinitely more fun for gameplay than sleepers.

**Comment by Iamgoofball** [comment]
Cryo was also changed.

**Comment by paprka** [comment]
the chemicals were, the function wasn't

**Comment by pudl** [comment]
yes they were

**Comment by paprka** [comment]
https://github.com/tgstation/-tg-station/pull/7131/files#diff-bc8cf2a6e56e32c5f580617844801ee3R64

This is all that was changed, so no

**Comment by Iamgoofball** [comment]
I'm sorry @paprka but people are already pissed enough about goonchem being too hard to heal people with, removing sleepers is just going to make people even more pissed, even with my buffs to cryotubes.

**Comment by Xhuis** [comment]
:-1:

**Comment by paprka** [comment]
Goof your changes made sleepers useless

You shouldn't have removed ointment and bruise packs since they're completely unrelated to chemistry but that's another topic

**Comment by Iamgoofball** [comment]
Yes, and my new changes make sleepers more useful.

**Comment by paprka** [comment]
You're ignoring the real problem with sleepers goofball, they shit out chems and make the MD completely irrelevant, and changing the chems inside won't fix that problem

Cryo is a better alternative to sleepers which has downsides and doesn't only require power

**Comment by pudl** [comment]
goof is fixing the fact that they shit out chems

**Comment by paprka** [comment]
I still don't see what the big deal is with sleepers. Why not just have more cryo cells, add the ability for people to resist out of them even when knocked out (the release sequence thing), and gut sleepers alltogether? Sleepers are stupid button pushing infinichem nonsense, wheras cryo requires power, and a decent chem mix to heal people. They're easier to use than sleepers, but require more upkeep than sleepers, which is much better in the long run

**Pull request closed without merging**
