### PR TITLE
Adds the HoP messkit to their garment bag

### PR DESCRIPTION
**Pull request by grungussuss**
## About The Pull Request
image
image
image
image
image

Ported from Delta-V, a fork of SS14, edited to reflect our style better.
## Why It's Good For The Game
All of the heads have alternative outfits and I think HoP deserves some love too.
## Changelog
:cl:
add: Added the HoP mess-kit outfit to their garment bag
add: Added latex gloves to HoP's garment bag to go along with their mess-kit
image: New sprites for the HoP's mess-kit outfit
/:cl:

### CODE REVIEW

**Comment by MrMelbert** [comment]
I like this outfit but there's been a semi-strict ruling that new head of staff equipment should go in cargo

Also the pants don't match the hat

**Comment by sylvia-from-fulp-station** [comment]
HOP garment bag is empty beside from a change of clothes so 👍

**Comment by Cheshify** [comment]
"new head of staff gear should go in cargo" is so nonsensical.

**Comment by Loafin34** [comment]
they look cool! like a sailor!

**Comment by Twaticus** [comment]
not interested in alt uniforms atm

**Pull request closed without merging**
