### PR TITLE
Reverts the individual chem heating system

### PR DESCRIPTION
**Pull request by Iamgoofball**
:cl: Iamgoofball
del: Individual chem temperatures have been reverted.
/:cl:

Individual chem temperatures have multiple problems:
1. They don't create any new and interesting gameplay aside from confusing chemists who aren't used to the new system.
2. Due to everything equalizing, the actual temperatures to the average player will end up being the same, just with more processing time spent calculating it.
3. Atmos has the excuse of being excessively complex and realistic because it's designed to be. Reagents are not designed to be realistic, and as such do not need this level of realism attached to it.
4. When confronted with the lack of gameplay potential for the feature and the lack of usage of the feature, plasma's specific heat was adjusted with no reasoning given to how this improves the gameplay experience.

@kevinz000 Please defend this feature you've added.

**Any inflammatory comments, straw-man arguments, logical fallacies, or "but goofchem lol" comments will be reported to the maintainers. If you are an administrator, an administrator complaint will be filed due to inappropriately representing the /tg/station servers on outside platforms. Any harassment in violation of the GitHub ToS will be reported to GitHub.**

### CODE REVIEW

**Comment by Bluespace** [comment]
Could you link to the PR you're reverting? Or at least where the feature was merged.

**Comment by SpaceManiac** [comment]
Reverts #37691

**Comment by Iamgoofball** [comment]
My bad, forgot this isn't an auto-revert

**Comment by Firecage** [comment]
Seems a bit way to quick to make a revert PR, since the one this reverts was merged only a day ago. Merge/revert wars probably aren't a good idea.

**Comment by Iamgoofball** [comment]
I'm leaving the PR up in case anyone has good ideas for the system to justify it remaining.

**Comment by Tlaltecuhtli** [comment]
improve dont remove

**Comment by 81Denton** [comment]
I gotta agree with goof, the chem system isn't complex/realistic enough to warrant this. Most interesting interactions I can think of would be killed by temp equalizing anyway.

**Comment by Iamgoofball** [comment]
Our players complained for 3 years about trekchems being removed. Do you think they'll appreciate needing to do temperature calculations for mixing?

**Comment by deathride58** [comment]
Y'see, all of the imbalanced shit in this codebase is a lot like an ingrown nail.

It hurts like hell, yeah, and if you try to remove it, it's going to hurt like a son-of-a-bitch for *days* on end, but after all is said and done? It's gonna be a lot better off than it once was.

If chem's reworked to be a lot more realistic/complex, then yeah, it's gonna piss people off quite a lot, and there's gonna be a lot of drama surrounding it, but once the bitching ends? Things are gonna be a lot better than they once were.

**Comment by Bluespace** [comment]
There are no plans to build on this system, it's just making chem a little bit more awkward right now.

**Comment by DaxDupont** [comment]
I have to agree with goof on this for once

**Comment by vuonojenmustaturska** [comment]
What makes you think there are no plans to build on this system?

**Comment by vuonojenmustaturska** [comment]
There's a chem-related bug report that might necessitate merging this, but in the event that that does not happen i do not see a need to merge it

**Comment by GuyonBroadway** [comment]
On the subject of making chem more complex for balance I feel like specific chem temps is a step in the wrong direction. Its just like telescience imo, all you need is a cheat-sheet or some autist to code a calculator (and they will) and its back to business as usual.

**Comment by Spaceinaba** [comment]
I think if anything the more complex chem gets the better considering we added CHEMISTRY MACROS that trivialized any sort of memorization or effort to making basic chems, removing more things that require chemists to actually do work is bad for complexity and any feeling of accomplishment for mastering the system is going to be lost when we just start lowering the skill ceiling.

**Comment by Iamgoofball** [comment]
This isn't adding complexity though.

**Comment by Aloraydrel** [comment]
but goof chem lmao

**Comment by GuyonBroadway** [comment]
Repeat after me.

:clap:adding:clap:tedium:clap:does:clap:not:clap:make:clap:something:clap:more:clap:skillful:clap:or:clap:rewarding:clap:

**Comment by Spaceinaba** [comment]
Putting emojis inbetween your words does no make you right nor does it explain what your idea of """tedium""" is

**Comment by GuyonBroadway** [comment]
Ok lets use an actual example then. 

Telescience.

Telescience used to be simple, till people figured out basic math then they could loot the station at roundstart easy peasy. So they made the math "more complex" and made it randomise every so often so you needed to recalculate after a few tries. 

And people just used a spreadsheet or a program that did the calculations and the problem didn't go away.

Tedium is just putting extra steps or time between start and finish, it does not make the finish any less potent at best and at worst it just leaves the turbo autists who can do the thing and abuse the results harder.

Adding extra steps/time does not stop the thing at the end being any less potent.

Also take regular science. Years and years of making guns harder or longer to get did nothing, only when gun production was flat out removed from the R&D dept did the issue stop. 

Making meth trickier to get just meant that only hardcore meth abusers made it and were basically better off than those who don't.


So on and so forth, and despite this happening time and time again people:clap:never:clap:learn:clap:

**Pull request closed without merging**
