### PR TITLE
Converts several species traits into generic traits

### PR DESCRIPTION
**Pull request by XDTM**
Now species have the inherent_traits var, which handles generic traits to add/remove along with the species.

Notable change: removed some snowflake checks for the coldres mutation, and instead made coldres give the RESISTCOLD and PRESSUREIMMUNE traits. 

Note that this was a direct conversion with minimal adaptation, which means that the trait checks are still on human-only procs even if they could apply to living mobs; notably, the temperature/pressure traits should ideally apply to simple animals as well. Since i'd rather not hunt for those manually, i'll add them in if consistency issues come up later.

### CODE REVIEW

**Review by ChangelingRain — CHANGES_REQUESTED** [review]
Cold resistance shouldn't protect you from high pressure, only low pressure

**Comment by YogsMcree** [comment]
Are you going to add more blocks for traits? Last time someone played with genetics, 1/6 powers got cucked every round.

**Comment by XDTM** [comment]
this time around i didn't remove a genetic power, i just changed its effect

**Comment by XDTM** [comment]
@ChangelingRain i separated the trait into RESISTHIGHPRESSURE and RESISTLOWPRESSURE, should be fine now

**Comment by Cyberboss** [comment]
Why do I feel like I reviewed this before?

**Comment by optimumtact** [comment]
conflict but good change

**Comment by XDTM** [comment]
@optimumtact fixed conflict

**Pull request merged**
