### PR TITLE
SMES logging fix

### LINKED ISSUE #14259: SMES deconstruction shows nullspace for the coordinates in the admin log
ADMIN LOG: The power storage unit has been deconstructed by [ckey]/([person])(?) (FLW) in (0,0,0 - JMP)
This is after someone deconstructed both SMES in electrical storage on box

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
Fixes #14259

### CODE REVIEW

**Comment by phil235** [comment]
The location won't be exact if the user is deconstructing the machine with telekinesis (which is possible).

**Comment by tkdrg** [comment]
Yeah just use var/turf/T = get_turf(src) and T.x T.y T.z

**Comment by Aranclanos** [comment]
use the SMES location

**Comment by duncathan** [comment]
@KorPhaeron

**Comment by KorPhaeron** [comment]
@duncathan

**Pull request merged**
