### PR TITLE
You can't defy lack of gravity through the power of love.

### LINKED ISSUE #53192: Through the power of love, if you and someone else hold each others hands you will be able to negate gravity
## Reproduction:

1. Find a friend, and grab their hand (aim for arm, grab intent).
2. Have the friend grab your hand too. Aw.
3. Walk into space.
4. Watch as you are able to fly around as if you had a jetpack on.

### PR DESCRIPTION
**Pull request by Ghommie**
## About The Pull Request
Title. Law of conservation of energy, not handholding.

## Why It's Good For The Game
This will close #53192.

## Changelog
:cl:
fix: You can't defy lack of gravity through the power of love.
/:cl:

### CODE REVIEW

**Comment by TheBonded** [comment]
~~Feature~~

**Comment by TheBonded** [comment]
This still leaves the issue of one person standing still and the other person walking into them on disarm/pull/harm intent and walking through space the same way

**Comment by Ghommie** [comment]
> This still leaves the issue of one person standing still and the other person walking into them on disarm/pull/harm intent and walking through space the same way

Interesting, I'll try to reproduce the issue on this branch later, and perhaps fix it too (plus other things).

**Comment by TheBonded** [comment]
> > This still leaves the issue of one person standing still and the other person walking into them on disarm/pull/harm intent and walking through space the same way
> 
> Interesting, I'll try to reproduce the issue on this branch later and perhaps fix it too (plus other things).

It works with anything you can both push and push off of in no gravity. Unwrenched lockers, or AI cores work even

**Comment by Jared-Fogle** [comment]
> You can't defy lack of gravity through the power of love. 

speak for yourself

**Comment by ShibaInuLord** [comment]
feature

**Review by kriskog — APPROVED** [review]

**Pull request merged**
