### PR TITLE
removes lich from wizard book

### PR DESCRIPTION
**Pull request by PKPenguin321**
"wizard dies -> round ends" should happen slightly more often now

edit: token: https://github.com/tgstation/tgstation/pull/18299

### CODE REVIEW

**Comment by YakumoChen** [comment]
fun removal

**Comment by Incoming5643** [comment]
yes to fun lich nerfs

no to removal

It's not even taken that much these days

**Comment by Incomptinence** [comment]
On one part lich is a bit flawed on the other part PKP is a nerf herding scum bag who is just doing this because he is sentient salt.

**Comment by Steelpoint** [comment]
Lich is a horrible spell and I've been saying that since it was added, being able to respawn in SS13 is bad design.

Wizards should emphasize on being powerful, not being powerful AND nearly unkillable via respawning.

**Comment by PKPenguin321** [comment]
yes i am very salty about the lich that killed me (just kidding that literally didn't happen, but wizard rounds are made stale when they never ever end, bring back round-end-on-wizard-death 2016)

**Comment by PKPenguin321** [comment]
@Incoming5643 if you have an idea for a nerf that makes lich still usable without making the round 40 gorillion years let's hear it

**Comment by Incoming5643** [comment]
Pick one:

Limbs detach from any brute damage.

Max health drops with every revival.

Lich philo becomes a unique item that's fairly obvious instead of soul bound bullet casings.

The beam that points to the liches revival spot lasts longer.

Raise cost of spell.

**Comment by Incomptinence** [comment]
@PKPenguin321 
Buddy we both know your tears flow at stubbed toes I never said you got killed..

**Comment by Bawhoppen** [comment]
PKP I'm all for gutting the dumb wiz spells (aka almost all of them) but we can't do one at a time and I learned this in the past

**Comment by PKPenguin321** [comment]
i'm just here to make wizard round the length god intended it to be man, i'm not here to "gut all the dumb spells"

**Comment by PKPenguin321** [comment]
@Incoming5643 all good ideas but that doesn't really fix the core issue of liches quadrupling the round length

**Comment by Incoming5643** [comment]
>people bitch about rounds getting shorter

Hey here's a pull that shortens the round

@Bawhoppen You are not understanding the point of wizard mode

**Comment by Bawhoppen** [comment]
KorDesignleadPhaeron agrees that wizard should be simple

**Comment by Incoming5643** [comment]
Well then kors a butt

Also pretty sure he said that and then immediately followed it up with "just to prove to people at how shitty that would be"

**Comment by KorPhaeron** [comment]
I don't remember saying wizard should be simple

**Comment by KorPhaeron** [comment]
Lich is probably one of the most poorly balanced things in the game but it's really fluffy and I'd be sad to see it removed instead of reworked

**Comment by KorPhaeron** [comment]
Also making pulls in response to threads in the containment board is silly

**Comment by PKPenguin321** [comment]
please note that this leaves it in the game, just not in the spellbook. feel free to rework and readd it whenever you please

>>people bitch about rounds getting shorter

>Hey here's a pull that shortens the round

i'm not sure anybody says this about *wizard* rounds though

**Comment by InsaneHyena** [comment]
Great change, merge immediately.

**Comment by Zilenan91** [comment]
I still think it would be cancer if liches lost a limb on each hit since it's really hard to get hit by anything as a wizard if you're doing the oldman robustin shit

**Comment by Incomptinence** [comment]
Decision made do not swallow the baloney of the salt man hollow.

**Comment by optimumtact** [comment]
Oh design lead disapproved, you can refactor this into something that reworks lich if you want this merged

**Comment by ike709** [comment]
improve not remove or something like that

**Comment by Aloraydrel** [comment]
would be fun if every limb gets detached on any brute damage but can be reattached by hitting the limb on yourself

**Comment by Steelpoint** [comment]
If we must keep Lich then here's how it should work.

You get ONE (1) extra life if you die at all, however upon spawning in your selected location you must, within ten seconds, select one limb to remove. If you don't pick one the game will pick one for you, your head is among the choices.

So your buying a extra life at the cost of a limb.

A Wizard being able to cheat death once is a very massive stretch considering the MASSIVE AMOUNT of powerful offensive and defensive spells they have access to, a extra life is extraordinary powerful as it utterly counters bombs and essentially any one-off trap.

One extra Life is all the Wizard should get.

**Comment by KorPhaeron** [comment]
Start tracking KDR again and then restrict lich based off it so newfriends can have lich as a safety net but powergaming veterans can't use it with 4 stuns

**Comment by Iamgoofball** [comment]
Hold off on this PR, I have a rework planned

**Comment by PKPenguin321** [comment]
@optimumtact If it's disapproved just close it

**Comment by KorPhaeron** [comment]
I still want this open so someone will finally rework it

**Comment by optimumtact** [comment]
That doesn't make sense, Kor, OP isn't gonna do it and this pr isn't gonna get merged

**Comment by KorPhaeron** [comment]
I'll merge it if nobody actually does any changes to lich in ~7 days

**Comment by optimumtact** [comment]
Well okay then

**Comment by optimumtact** [comment]
Looks like your evil plan worked #18455

**Comment by Steelpoint** [comment]
How does that solve it?

It just makes it easier to lose a limb, which is a pretty damn fair price for extra lives.

**Comment by optimumtact** [comment]
Solve what? This pr was left open to encourage someone to make some substantial changes to Lich.

The question of what the issue is with Lich is one I'll leave to other people.

**Comment by Steelpoint** [comment]
The problem with Lich is how horrendously powerful extra lives is in a game, nay game mode, based around one very powerful individual fighting a entire station.

A substantial change would be to heavily punish someone who revives as a Lich after death, and I fail to see how making losing limbs a bit easier is sufficent punishment, since by the time you've got the Lich in a position to dismember them they'll already be dead, or more accurately they'll be reviving and alive again unless dismembering the head prevents a Lich from reviving. 

The only way to stop a Lich from reviving is to find the mythical item its using to revive, or to destroy the body. That's something that is not inherently told to the player and only someone who is told after the fact will know, not even the wiki details Lich last time I checked.

That linked PR does not solve the problem in my opinion, and I don't even know it its intent was even to affect the Lich issue.

**Pull request closed without merging**
