### PR TITLE
Assistant Simple mobs + Clown random names

### PR DESCRIPTION
**Pull request by Firecage**
Well, this adds an Assistant simple mob. Both a male and female version. Their appearance is with standard grey jumpsuits, black shoes, grey backpacks, ID's, and PDA's. They also have black hair. The male one has short black hair, the female one has floor-length black hair. They also have random first and last names from the names files.
i22v8ek

Also, I made it so the Clown simple mobs also uses random names from the clown names file.

Also, this PR uses @vista- 's targeting system.

### CODE REVIEW

**Comment by vista-** [comment]
#1937

**Comment by Razharas** [comment]
Add "VALID" to their phrases

**Comment by Dorsisdwarf** [comment]
VALID SALAD!

**Comment by WJohn** [comment]
I think you forgot to remove the pixels for the female versions there used for "fitting" clothing.

**Comment by Firecage** [comment]
@WJohn . They are just slightly chubby and flat. Do you have to be so sexist?

**Comment by paprka** [comment]
This is bad, mostly because the female assistant uses floorlength braid instead of a more generic female haircut like long fringe or something. :-1:

**Comment by TZK13** [comment]
Isn't the joke that people with floorlength braids are usually shitlers :^)

**Comment by paprka** [comment]
It's epic because firecage uses floorlength braid and grey tides all the time!1!1!!!!1

**Comment by WJohn** [comment]
I-I'd use them ;~;

**Comment by Firecage** [comment]
Paprika. Does the hair really matter that much?

**Comment by pudl** [comment]
i agree with everything pap said, this is shit

**Comment by Niknakflak** [comment]
I actually agree with everything pap said too.  Mostly about the hair though.  This mob is litterly a play joke on the greytide.

**Comment by Iamgoofball** [comment]
>flb

no self respecting greytider would be caught dead with a FLB

**Comment by paprka** [comment]
Unless you're firecage in which case ebig self reference xD

I grief as a joke! lmaooooooo

**Comment by Atskadan** [comment]
nah im pretty sure everyone ive met with a FLB is a shitter so its accurate
plus i doubt anyone is going to look at a random simple mob and say "wow i should do that it's hilarious"
greytide is still banned and all, if anyone is retarded enough to think that a violent simple mob is validation for shittty behavior then you know they're going to cop a ban some day anyway

**Comment by Iamgoofball** [comment]
no longer relevant due to #6762

**Comment by paprka** [comment]
Yeah that PR has basically replaced the need for this one

**Comment by Miauw62** [comment]
sorry firecage

**Pull request closed without merging**
