### PR TITLE
Robot tourists now know what mercy is again

### PR DESCRIPTION
**Pull request by ghost**
:cl: CodeMonkey
fix: Robot tourists now stop attacking you after they show you who's boss.
/:cl:

was an issue with the finish_action not receiving the correct arguments.

### CODE REVIEW

**Comment by ATH1909** [comment]
https://youtu.be/SlLcQF59niQ?t=70

**Review by Mothblocks — APPROVED** [review]

**Comment by Mothblocks** [comment]
`[] = null` takes another

**Comment by timothymtorres** [comment]
@AMonkeyThatCodes does this fix #61065

**Comment by Mothblocks** [comment]
If it does, they're an issue manager and can close it :P

**Comment by wraith-54321** [comment]
When combined with Corgi of the North Star they would kill you and then deal 300 damage to you in about 5 seconds, it was terrible

**Pull request merged**
