### PR TITLE
New blob chemicals plus tweaks to old blob chemicals

### PR DESCRIPTION
**Pull request by ChangelingRain**
:cl: Joan
rscadd: New blob chemicals:
rscadd: Pressurized Slime, which is grey, does low brute, oxygen, and stamina damage, but releases water when damaged or destroyed.
rscadd: Energized Fibers, which is light yellow, does low burn damage, high stamina damage, and heals if hit with stamina damage.
rscadd: Hallucinogenic Nectar, which is pink, does low toxin damage, causes vivid hallucinations, and does some bonus toxin damage over time.
tweak: Replaces Kinetic Gelatin with Reactive Gelatin, which does less brute damage, but if hit with brute damage in melee, damages all nearby objects.
wip: Changes three of the old blob chemicals:
tweak: Ripping Tendrils does slightly more stamina damage
tweak: Envenomed Filaments no longer causes hallucinations, but does some stamina damage in addition to toxin damage over time.
tweak: Cryogenic Liquid will freeze targets more effectively.
/:cl:

The blob damage reduction is now a multiplier instead of a divider, meaning you can have a blob take more damage instead of less, or take 0 damage.
You can do a LOT with blob chemicals now, like really there's a lot you can do.

### CODE REVIEW

**Comment by GunHog** [comment]
Huh, interesting. :+1:

**Comment by Lumipharon** [comment]
stam damage is pretty crap because it's impractical to heal, and takes ages to wear off naturally.

**Comment by Jalleo** [comment]
Pressurized slime is very much a colour from outer space.

**Comment by Zilenan91** [comment]
@anonus How much damage does kinetic gelatin now? If it got nerfed for more than 5 it's basically objectively worse than every other blob chem now since the damage it'll do will be far too little, especially since it's brute

Also can you please do something about cryogenic liquid, it's absolutely worthless and does nothing.

**Comment by Anonus** [comment]
Reactive Gelatin does between 10 and 20 brute plus the flat 5 from blob act. The reacting on brute damage is pretty significant, because it'll react on off welder hits(often) and people trying to hit it with a wrench(distressingly common)

**Comment by Zilenan91** [comment]
But welder hits do burn, not brute, so that wouldn't do anything at all. 
If you mis-said in the OP, and it reacted off of melee hits in general then this is fine.

Though for real please do something about cryo liquid because if you drink a singular cup of coffee you are immune to 80% of the blobs damage.

**Comment by Anonus** [comment]
It's brute only and it still does decent damage.
You're underestimating how many people look at their welder to see if it's off before they hit again and how many people just hit the blob with a fucking wrench.

I could make it trigger off of non-explosion damage, though, which would mean it'd trigger on bullet guns(also used distressingly often)

**Pull request merged**
