### PR TITLE
Added botany tools, salt and pepper shakers to vendors, changed how you get rice seeds

### PR DESCRIPTION
**Pull request by erwgd**
This adds some items to the vending machines for the Kitchen and the Hydroponics work areas:
5 salt shakers and 5 pepper mills to Plasteel Chef's Dinnerware Vendor
2 plant analyzers, 3 spades and 3 cultivators to NutriMax
3 rice seeds to the Megaseed Servitor; this will help the crew grow rice from the start of the round.

The wheat-to-rice mutation has been removed; if you mutate the species of a plot of wheat stalks then it will always mutate into oat stalks.

The seeds crate from supply will now contain a pack of rice seeds.

:cl: Erwgd
rscadd: The Kitchen Vending machine now stocks salt shakers and pepper mills!
rscadd: The NutriMax now stocks spades, cultivators and plant analyzers.
rscadd: Rice seeds are now stocked in the MegaSeed Servitor, and the seeds supply crate now contains a pack of rice seeds.
rscdel: Botanists should be aware that wheat stalks can no longer mutate into rice.
/:cl:

### CODE REVIEW

**Comment by Chocobro** [comment]
everything in this pr is okay however
removing rice mutation outright is a pretty bad idea
rice seeds are fine in the servitor, but also make it a mutation of oat
alternatively, fix the mutation chances so it's 50% of both instead of 100% of one - that's a bug if anything
the king of hydroponics has spoken

**Comment by Iamgoofball** [comment]
what happened to steel wheat

**Comment by tkdrg** [comment]
It would be pointless to have it be a mutation and also in the vendor, it would just be wasting a mutation slot. Are there even any other mutated seeds in the vendor by default? Don't think so

**Comment by Chocobro** [comment]
then mystery
goof I don't remember if it was even added ever? ?????????????

**Comment by newfren** [comment]
@tkdrg I believe the only ones are oranges + lemons (mutate into each other for some reason) and replica pod seeds (which are difficult to reproduce).

**Comment by newfren** [comment]
@Iamgoofball also we have steelcaps - mutation of towercaps that give rods when hatched instead of planks.

**Comment by Chocobro** [comment]
oranges and lemons are part of the same genus - if you want, you can make them also mutate into limes and just turn it into a circle of mutation
it's not imaginitive, but oh well

**Pull request merged**
