### PR TITLE
Fixes mech projectiles hitting the mech that fires them

### LINKED ISSUE #55641: Firing a mech's gun results in hitting your own mech if you're moving forwards
## Reproduction: 

Spawn a mech, add any common gun to it including the plasma cutter and fire whilst walking forwards. Your mech will most likely be hit.

## Description: 

Any mech, including durands which are incredibly slow will be whacked by their own projectile (even from plasma cutters) if they walk forward while firing. While this was a very rare occurrence before the latest projectile changes, now it's virtually a guarantee if you fire when walking forwards.

### PR DESCRIPTION
**Pull request by MLGTASTICa**
## About The Pull Request
What if you had a phazon , but god said "All mech guns act like hilarious firing pin lasers" and you shot yourself to death?
## Why It's Good For The Game
Bug fix
Also closes #55641

## Changelog
:cl:
fix: fixed mech bullets hitting the mechs they're fired from
/:cl:

### CODE REVIEW

**Comment by Serxule** [comment]
THANK YOU THANK YOU THANK YOU THANK YOU THANK YOU

**Comment by spessbro** [comment]
we really should separate tgmc and tg gbp by now.

**Comment by ArcaneDefence** [comment]
Related issue that wasn't linked https://github.com/tgstation/tgstation/issues/55641

**Comment by MLGTASTICa** [comment]
> Related issue that wasn't linked #55641
did a quick look myself but i couldn't find it , thanks for pointing it out.

**Pull request merged**
