### PR TITLE
Ash Ascension spells have high transparency

### PR DESCRIPTION
**Pull request by carlarctg**
## About The Pull Request
Ash ascension flame hotspot effects are now 150 alpha
Oath of flame (ring)=
image
cascade
pre-post-burst
image
during burst
image

The effect ingame is that every time the flame bursts again it makes it hard to see for a second but then it's a transparent cool 'background' effect. I think its perfect !

## Why It's Good For The Game

I want to see the fucking game

## Changelog

:cl:
qol:Ash Ascension spells have high transparency
/:cl:

### CODE REVIEW

**Comment by carlarctg** [comment]
@Jacquerel silly

**Comment by Xackii** [comment]
askend nerf?

**Comment by Jacquerel** [comment]
I still cant see shit in that picture

**Comment by carlarctg** [comment]
> I still cant see shit in that picture

I ahve idea for fix

**Comment by Time-Green** [comment]
would also appreciate a pic of the smaller fire thing

**Comment by moocowswag** [comment]
Judging by your screenshot it seems that the effects stack ontop of eachother to fully blot out tiles, still this looks better and shows spots that people really want to avoid or risk taking double damage so i think its fine.

**Comment by CCC23** [comment]
Finally you can now actually play ash heretics ascension

**Comment by Admiral-Gigaton** [comment]
Good thing: now heretic can stab shit

Bad thing: now people can easy counter because they can see what to throw the corpse at to stun

**Pull request merged**
