### PR TITLE
Makes sounds worth as much GBP as sprites

### PR DESCRIPTION
**Pull request by ghost**
This was something I asked if I could do when Kryson raised sprites to +3, and got a yes, but never ended up PRing the change. (good) sounds are as much in demand as sprites.

### CODE REVIEW

**Comment by tralezab** [comment]
makes sense and is actually way harder to get good sound content into the game without any license issues so i approve big time

**Comment by maxymax13** [comment]
it's a ladder guys. first sprites are raised, then sounds are raised to match, and then someone will raise sounds even higher, and then someone else will raise sprites to match. soon the spriter nation will take over

**Review by Timberpoes — APPROVED** [review]
I like the idea that we provide subsidies and rewards for PRs we want to encourage and tax PRs we want to discourage relative to the various other PR types.

Sprites and sounds are the heart and soul of any game. Giving sound authors and sound porters a couple of extra Disney Dollars to match sprite artistes and sprite porters makes sense.

I intend leave this open to discussion for a few days incase dissenting views pop up.

If you're the maintainer who originally okayed this, don't let me slow you down if you wanna merge away though.

**Comment by celotajstg** [comment]
Before this is merged, I would like to make sure there is no oversight here - does the github action take label GBP values from the gbp-balances or the master branch?

**Comment by Mothblocks** [comment]
@celotajstg It takes it from master.

https://github.com/tgstation/tgstation/blob/master/.github/workflows/gbp.yml#L20-L23

**Pull request merged**
