### PR TITLE
Removes the assimilation/hivemind gamemode

### LINKED ISSUE #43361: issue with mindshield implanting and hiveminds
not a dupe of #43059 this one has more info

mindshield implant goes into awoken vessel, doesnt give any feedback nor give them the flashy mindshielded HUD thing, implant still goes in and fails future mindshield attempts since they already have one.

@Kierany9

### LINKED ISSUE #43365: xenomorphs cant speak on the one mind
@Kierany9 
long story but as a xeno queen an ascended hive host came up and assimilated me, i wasnt able  to speak on their hive though (ability was present but clicking it did nothing) and none of the other assimilated xenos got the purple glow.

### LINKED ISSUE #45465: No sitties for One Mind
Issue reported from  Round ID: 114085 (/tg/Station Bagil [ENGLISH] [US-WEST] [100% FREE LAG])

Reporting client version: 512.1471

Players within the One Mind cannot buckle themselves to chairs.

### PR DESCRIPTION
**Pull request by kriskog**
**MAINTAINER NOTE:**
Since this is going to cause reddit shitfits about so many removals, the reason as to why this is potentially up for removal is because the creator and main active maintainer of the gamemode, [Kierany9 will no longer be working on it](https://tgstation13.org/phpBB/viewtopic.php?f=5&t=23300). It's not a particularly popular mode. As shown by the last community poll, the most popular opinion was that people would like to see the gamemode majorly reworked. This will likely not be happening, so it's up for removal.

## About The Pull Request
Removes the assimilation gamemode, as requested by oranges. 

I think I got it all, but if you come across any other references let me know.

Closes #43361
Closes #45465
Closes #43365

## Why It's Good For The Game
Removes hiveminds. 

## Changelog
:cl: Skoglol
del: Removed Assimilation/Hivemind gamemode.
/:cl:

### CODE REVIEW

**Comment by KomradeSpectre** [comment]
The absolute madman becoming an absolute messiah.

**Comment by Detective-Google** [comment]
I wonder if it'd be better to just disable it in the config instead of removing the code, but if oranges thinks a full removal is good then good riddance to a broken mode

**Comment by Whoneedspacee** [comment]
> The absolute madman becoming an absolute messiah. The mode had a lot of hilariously bad design flaws, and suffered the same issues conceptually that clock cult did over its various iterations. The core design philosophy (powerful antagonist with no/very minimal tells) of it was not great to begin with, and if it were to be redesigned successfully would have to be re-evaluated. Better to remove it and let someone rework it later on if they want, than to leave a broken mode in.

the amount of work it would take, you might as well just make your own gamemode and steal the sprites mate.

**Comment by CPTANT** [comment]
I think it is a good thing to evaluate why the mode didn't work and not just dump it with "good riddance".

I think there are several points that make the mode weak:

1. Minimal crew involvement unless hivemind is achieved. Why would crew care? They don't notice anything from being in a hive unless they get objectives, there is nothing to really fear or fight.

2. Crew is punished for taking out hiveminds. Lack of competition only makes it easier for remaining hiveminds to succeed, bringing it in the weird position of the crew getting punished for taking out antagonists.

3. Mass implantation is the only counter. Security mass implants everyone and there is no resistance because the people getting implanted don't even know they were in a hive to begin with.

4. Stealth antagonist that is fucked over once the MODE, not the ANTAGONIST is known. There is no point in keeping stealthy, every power you use will lead to the mode being known, leading to mass implantation. Keeping your own identity as a hivemind host hidden is almost pointless because the counter is performed anyway.

**Comment by Akrilla** [comment]
It's a shame he's not working on it anymore, but I totally respect the fucking effort put in. It really does have some fundamental flaws, and unfortunately is just too ingrained into the gamemode. If nobody goes on to maintain this, I'll pick it up in a few months. There's so much potential with an antag vs antag gamemode like this.

**Comment by wesoda25** [comment]
Ay yai yai do what you should have done ages ago and make it a side antag!!

**Comment by necromanceranne** [comment]
I feel like there is enough stuff to be salvaged that it would be a damn shame not to just shelve it in the config over actually outright removing it from the code. It has too much work put in and actually has some bits and pieces worth keeping. It's not bad code but just a bad game mode.

**Comment by Mickyan** [comment]
It's convenient that you'd mention the creator leaving as if it's relevant to an open source project and not that in that very thread someone mentioned they're still working on updating it

**Comment by necromanceranne** [comment]
If someone is taking up the project it seems ridiculous to remove it from underneath them.

**Comment by wesoda25** [comment]
As far as I know no one has officially accepted it and you can’t really hate krisk for removing it. But theres a ton of good code here that shouldn’t be outright removed, as anne said.

**Comment by actioninja** [comment]
It's git, the code is still there. You can't truly remove anything with git. I can get a snapshot of the repo as it existed 5 years ago right now.

**Comment by kriskog** [comment]
The consensus seems to be that it requires a major rework. Small tweaks and changes isn't going to do it, and keeping it in code encourages that style of working on it. If someone is serious about adressing the concerns people have about the mode, they can attempt to have it re-added at a later date based on the merits of the reworked mode.

**Comment by necromanceranne** [comment]
I meant also in the sense of keeping parts of it open for admin use. We still have devils and clockcult for that as an example. Even if it's ancient by this point and buggy as all hell.

**Comment by GuppyLaxx** [comment]
r*tarded cash grab gamemode made for the old code bounties for "new!!" and "original!!!" gamemodes

**Comment by Nickkoranda** [comment]
>r*tarded cash grab gamemode made for the old code bounties for "new!!" and "original!!!" gamemodes
lmao for the amount of work kierany put in $100 was not enough to deal with the bullshit people threw at them

**Comment by Ziiro** [comment]
Honestly I feel like it should just be a side antag.

**Comment by py01** [comment]
I'm currently working on a re-work to address some of the issues people are yelling about. However it'll take a while and the mode is honestly not in a great spot ATM, and it's totally fair to remove it from rotation until more fixes are made.

**Comment by optimumtact** [comment]
I actually have zero interest in carrying this mode in the code going forward

**Comment by ATH1909** [comment]
Mind control was cool as a power; could we turn it into a wizard spell or something?

**Comment by TheRespectedMan** [comment]
goodbye to bad garbage

**Comment by py01** [comment]
Is there interest in a reworked version of the mode? I don't want to waste time reworking it if no one wants it back.

**Comment by optimumtact** [comment]
I don't particularly have any interest no.

I dont' want to focus on more antags and gamemodes at this time, I'd prefer to focus on features aimed at the crew.

Currently im actually semi planning to implement a change freeze at some point on new antag/gamemode items and features

**Comment by bigfatbananacyclops** [comment]
honestly i've had fun as a hivemind but it was usually when i wasnt focusing on getting hivemind powers, the gamemode does seem boring and if sec were to be competent, they'd go on a implant holocaust where they go implanting everyone until the hivemind dies, it's boring.

**Comment by Akrilla** [comment]
I have interest in antagvsantag since it's a cool concept but tbh I'm fine with a freeze

**Comment by Tlaltecuhtli** [comment]
remove when?

**Comment by Akrilla** [comment]
Yeah on dynamic it’s just a bit of a meme at this point that your antag round gets fucked lmao

**Comment by 81Denton** [comment]
Since we have plenty of antags, the game mode is widely unpopular and oranges is not interested in a rework, I'm gonna go ahead and merge this.

**Pull request merged**
