### PR TITLE
Buffs bedsheets

### PR DESCRIPTION
**Pull request by jughu**
Bedsheets buff STYLE BUFF this probaly makes people meme as one punch man more

:cl: jughu
tweak:bedsheets goes around your neck silly!
/:cl:

### CODE REVIEW

**Comment by YakumoChen** [comment]
But what if I want the sheet-cape combo??

**Comment by jughu** [comment]
THEN TOO BAD

**Comment by jughu** [comment]
Woopsie

**Comment by KorPhaeron** [comment]
You didn't test this PR, did you?

**Comment by jughu** [comment]
Nein i didnt test

**Comment by KorPhaeron** [comment]
It doesn't work like this

**Comment by KorPhaeron** [comment]
Maybe I should just do the PR

**Comment by jughu** [comment]
That would be tip top perfect

**Pull request closed without merging**
