### PR TITLE
New Nar-Sie rune sprite

### PR DESCRIPTION
**Pull request by ChangelingRain**
New:
huge
Old:
this is the old sprite
New sprite credit @WJohn

### CODE REVIEW

**Comment by lordpidey** [comment]
Honestly, I think it looks terrible compared to the old one.

**Comment by WJohn** [comment]
This sprite is 4 years old, and is a seriously cut down version of the 7x7 rune it's supposed to be.

**Comment by xxalpha** [comment]
It's an umbrella.

**Comment by MMMiracles** [comment]
pentagram seems to fit more when it comes to summoning a dark god than an umbrella, tbh.

**Comment by xxalpha** [comment]
No I prefer the umbrella, Nar-Sie isn't satan.

**Comment by Cebasiz** [comment]
i like the umbrella.

**Comment by Thunder12345** [comment]
Centre looks a bit bland tbh. Maybe more writing around the inside edge of the hexagon, and the outside of the middle circle?

**Comment by GunHog** [comment]
Agreed with thunder, add some stuff in the sections

**Comment by Core0verload** [comment]
I like the size and outline better, but the straight lines and shapes is not what you except from Nar-Sie's runes.

**Comment by KorPhaeron** [comment]
I prefer old

**Comment by WJohn** [comment]
It's cut down from this 7x7 monstrosity:

**Comment by KorPhaeron** [comment]
Yeah you cut out half the detail, doesn't look as cool anymore

**Comment by GunHog** [comment]
maybe you should...like it like that....

**Comment by Kromgar** [comment]
Holy shit we need the 7x7 instead.

**Comment by ChangelingRain** [comment]
The issue with the 7x7 is that, well, it's THAT BIG.

**Comment by Kromgar** [comment]
Artificers can tear down walls and make walls. The solution is clear

**Comment by Kromgar** [comment]
also this way you dont have all the idiots pushing eachother around on the nar'sie rune

**Comment by Cebasiz** [comment]
that is cool as fug wjohn

let's use that one instead

**Comment by Armhulen** [comment]
fuck it that rune is mine i'm stealing it

**Comment by Cheridan** [comment]
I like it. Narsie is literally called the Geometer of Blood, so the rune being a geometric shape fits perfectly.

I deem this pr ABSOLUTELY CANON

**Comment by KorPhaeron** [comment]
Yeah but the other one looks cooler

**Comment by KazeEspada** [comment]
0/10, not an octagon that shows best cultist location

**Comment by MMMiracles** [comment]
design lead has spoken

**Comment by Robustin** [comment]
It's a pretty clear downgrade. Either find a way to get your expanded sprite to work or just focus on improving the center of the current rune.

**Comment by optimumtact** [comment]
The new sprite looks fuzzy compared to the old one, I don't know if it's just the way you took the screenshots but please put them in game to compare.

**Comment by ChangelingRain** [comment]
Here are two equivalent screenshots
New:
huge
Old:
this is the old sprite

**Comment by optimumtact** [comment]
Yeah that's a better comparison I think. Maybe try a version of the geometric sprite without the writing around the edges? Might make it look cleaner.

**Comment by optimumtact** [comment]
Sorry but people dont' like it

**Comment by ChangelingRain** [comment]
shrug

**Pull request closed without merging**
