### PR TITLE
Gives hivelord broods (legion skulls) the swarming component

### PR DESCRIPTION
**Pull request by nemvar**
## About The Pull Request

Hivelord broods (legions skulls) have lost their density and gained the swarming component. This makes legions even weaker when alone and a lot stronger when in groups

The broods still block projectiles.

## Why It's Good For The Game

Legions were always pathetically weak for how much reward they gave. This changes that. Their skulls will now swarm the enemy and deal large amounts of damage if in large groups, instead of waiting for their turn to attack.

It makes engaging legion tendrils are bit more interesting, because it is really boring currently.

I also think that the legion megafauna fight plays out a lot better with this.

## Changelog
:cl:
balance: Legions have been buffed. Their skulls will now swarm you much more efficiently
/:cl:

### CODE REVIEW

**Comment by SpaceManiac** [comment]
Heads-up: the email address you are committing with is not associated with your GitHub account.

**Comment by nemvar** [comment]
Are you sure about that? Github died for a moment when I pushed this, might be related to that.

**Comment by SpaceManiac** [comment]
The same is true on your other open PRs

**Comment by nemvar** [comment]
Should be resolved now. Thanks for bringing it up.

**Comment by XDTM** [comment]
How do you make them still take bullets with no density? I had this problem when adding the swarming component

**Comment by nemvar** [comment]
Currently only one thing prevents mobs from getting hit by projectiles, and that is:
```
if(CHECK_BITFIELD(L.mobility_flags, MOBILITY_USE | MOBILITY_STAND | MOBILITY_MOVE) || (L.stat == CONSCIOUS))
```
It's kinda silly to be honest. We probably need a need passflag that determines if something should get hit by indirect projectiles.

**Comment by Shadowflame909** [comment]
>Weak

I see he hasn't stumbled upon a goliath legion double tendril, where you get gripped and then death-locked by the legion swarm.

In exchange for an okay 25 Brute and 25 Burn heal pack. There's always the chance of being turned into a simple mob NPC that's forgotten about.

**Comment by nemvar** [comment]
If you get stunned by a goliath, you are dead 9 times out of 10 anyways. If this gets merged, that specific thing should actually be somewhat easier because the skulls will no longer diminish your ability to dodge the tendrils.

**Comment by Dorsisdwarf** [comment]
Finally, maybe this will make capital l Legion less of a joke

**Pull request merged**
