### PR TITLE
New chair sprites

### PR DESCRIPTION
**Pull request by WJohn**
Because our current ones are really really old and are full of inconsistent perspectives that's driving me insane.
image

### CODE REVIEW

**Comment by paprka** [comment]
SHIT SHIT SHIT POSTING IN OOC THIS IS A SPRITE CHANGE FUCKING RALLY

**Comment by pudl** [comment]
these were made to go with my tables, should i make a pr for those

**Comment by WJohn** [comment]
Go ahead, those have been needing some fixing up and consistency for a long time anyway.

**Comment by pudl** [comment]
i'll have to do reinforced tables as well, then

**Comment by TZK13** [comment]
It should be noted that the chair sprites were just recently made wider in #6421 in order to make it easier to buckle yourselves to them, I like these sprites more in terms of aesthetics but they definitely do seem a lot smaller than even the old chair sprites were.

**Comment by WJohn** [comment]
Alright, I'll make em wider before this gets merged.

**Comment by pudl** [comment]
no one EVER complained about chair buckling, making them any wider will make them ugly, just keep them as it. they're still wider than original chairs.

**Comment by TZK13** [comment]
The N and S facing sprites are fine, it's the E and W that are exceedingly slim compared to the old old chair sprites.

**Comment by pudl** [comment]
a sideways human wouldn't block that whole chair

**Comment by paprka** [comment]
they might have big coats on

post a pic of someone in a hardsuit in front of the chair in all directions

OR MAYBE WE CAN CHANGE HOW CHAIRS ARE BUCKLED INTO

**Comment by WJohn** [comment]
Hm, now that I take a second look at the north sprite I can't say I'm terribly happy with how that works. The alternative though is to make chairs straight flat on their sides and then *PERSPECTIVE CLASH WITH SURROUNDINGS*

**Comment by dannno** [comment]
Wh-what about walterje's chairs :-D

**Comment by WJohn** [comment]
They'd have the same problem as mine, actually. The only reason ours currently work is because it doesn't show any of the bottom pad because of the smooth unbroken back.

**Comment by paprka** [comment]
EXACTLY THAT'S WHAT I'VE BEEN TRYING TO SAY

**Comment by WJohn** [comment]
So basically: *PERSPECTIVE SHENANIGANRY*

**Comment by Miauw62** [comment]
@Nienhaus

**Comment by Nienhaus** [comment]
I'm not sure how I feel about that because the bottom middle looks so weird.

**Comment by Nienhaus** [comment]
At least the sprites don't look bad, right?

**Comment by An0n3** [comment]
These don't look good at all.  They don't seem consistent with the rest of the items in game, they're gigantic compared to the player sprite, and they just plain look really uncomfortable to sit in.

**Comment by WJohn** [comment]
These are smaller than the previous ones...

**Pull request merged**
