### PR TITLE
The curator's PDA now works in space

### PR DESCRIPTION
**Pull request by JohnFulpWillard**
## About The Pull Request

The Curator's PDA, while out in space, will have low-signal, rather than none. This means that their apps (Messenger, Newscaster, ect) will still work.

## Why It's Good For The Game

Originally I was going to make the newscaster app work without NTNet, but thought this was the better solution. I also recently removed the modular computer upgrades that allow low-signal connections to NTNet from space, so this is my alternative to that as well.

Curators are many things, but is also the only job we expect to explore space. Because of this, I think it's necessary for the Curator to still be able to talk with crew members, and use their Newscaster app, to hopefully make space exploration feel like you're just on a private singleplayer world.

## Changelog

:cl:
balance: The Curator and Crystal PDA is now upgraded to have long-distance NTnet connections, they are able to use their apps in space.
/:cl:

### CODE REVIEW

**Review by Mothblocks — APPROVED** [review]

**Comment by OperativeLyn** [comment]
> Can I suggest this also be added to the clear PDA? It's found exclusively (if I'm not mistaken) in a space ruin, and makes a nice cosmetic upgrade for the curator or any other space explorers.

It's also in the abandoned crate item pool, but it's a good idea regardless

**Comment by VladinXXV** [comment]
> > Can I suggest this also be added to the clear PDA? It's found exclusively (if I'm not mistaken) in a space ruin, and makes a nice cosmetic upgrade for the curator or any other space explorers.
> 
> It's also in the abandoned crate item pool, but it's a good idea regardless

Ah, true! I forgot about that. I still think it wouldn't be a bad idea, though.

**Comment by VladinXXV** [comment]
> It'd be cooler to tie this behavior to a hardware piece instead of having a random var on them that players can't change

This behavior _**was**_ tied to a hardware piece but JFW is on a crusade to eliminate hardware.

> Edit / Or actually, maybe tie it into wirecarp or something like you did with the mass send feature, like being able to signal boost certain devices (limited to a few only)

This seems more likely to happen.

**Comment by JohnFulpWillard** [comment]
I thought it would be better to tie it to their equipment like their beacon currently is, reskinning PDAs just gives them the icon from what I checked, so this isn't abusable

**Comment by JohnFulpWillard** [comment]
I disagree with that, Wirecarp giving mass pda was made because people steal the lawyer's cartridge for that ability, so I thought moving it to an interaction would be better.
Here, I'm not really replacing anything, and I don't think long-ranged abilities is something I'd like to be replaceable It's a unique ability to a unique item. I'd compare it more to the messenger's ability to send emotes more than the ability to mass-message.

**Comment by JohnFulpWillard** [comment]
I can add it to examine text, I've never opened a .dmi file to change the icon though. I assumed Curators would be able to tell by how their PDAs have a signal while in space, which is usually more obvious than something like ability to use emojis in messenger.

**Comment by Mothblocks** [comment]
Adding to the examine text is a good idea.

**Comment by calliophis-maculiceps** [comment]
also change the changelog to reflect the clear PDA also having it

**Comment by Farquaar** [comment]
Curator powercreep!

**Pull request merged**
