### PR TITLE
Hotel Feedback Tweaks

### LINKED ISSUE #19191: Staff and Security on the Hotel can't open some lockers
[Note]: # (State what the issue is from a "whats wrong" prospective. Issue reports should clearly allow maintainers to understand whats wrong and how to test/reproduce if that is not obvious. Avoid ambiguity. Start your issue report below both of these lines (or remove them))
Security can't open their locker, and I remember not being able to open one of the cabinets as a staff working the kitchen
[Admins]: # (If you are reporting a bug that occured AFTER you used varedit/admin buttons to alter an object out of normal operating conditions, please verify that you can re-create the bug without the varedit usage/admin buttons before reporting the issue.)

### PR DESCRIPTION
**Pull request by MMMiracles**
:cl: MMMiracles
fix: Hotel staff can now actually use their own lockers. 
/:cl:

Fixes #19191

newhotel1

Large map change is due to TGM conversion. 

Fixed locker access. Some slight visual changes to turfs as well as a small theatre-ish stage to the open bar/kitchen area. The front desk now has pamphlets to give to arriving guests as a short description of the place they just teleported to.

Also, all hotel staff now spawn in with mindshield implants (vigorous background checks to ensure any subconscious bloodlust urges are contained), as well as the energy shotgun being given a mindshield pin due to complaints about _some_ people bumrushing the hotel for it.

### CODE REVIEW

**Comment by GunHog** [comment]
How many pamphlets are there? The last time I played as hotel staff, I wrote up some ads and tossed them into the teleporter. I attracted the CE and a lawyer. Will there be enough of them for me to all the station's teleporter locations with them? It is not a big deal if it is not, as I can simply write more.

I do not think the pool's water tiles work properly. They simply look like water colored tiles, not a pool at all. I am not sure if that can be fixed by mapping alone, though.

Is it possible to make the hotel staff spawn with their respective IDs?

I am guessing the ~~Loyalty~~ Mindshield implants are to ensure that the hotel staff put up a fight when a conversion antag tries to use it as a base?

**Comment by Militaires** [comment]
@GunHog oh wow was that you i was georgene something the sec officer, same guy?

also good pr now i dont have to smash the lockers

**Comment by Armhulen** [comment]
I will find your broken pr token scandal mmmiricles

**Comment by AnonymousNow** [comment]
Ah, good - a place I can post this.

The lowest solar array arms aren't wired, and the way they're placed requires deconstructing the two closest panels to the main strut, placing wire from their tile and then replacing the solar panels.

Seems inconsistent, and I'm guessing that it's unintended.

**Pull request merged**
