### PR TITLE
adds cycler shotgun to wardens locker

### PR DESCRIPTION
**Pull request by jughu**
screenshot_2016-12-13-07-16-19-1

### CODE REVIEW

**Comment by jughu** [comment]
Last time kor tries they took wardens stungloves away which got them salty

**Comment by jughu** [comment]
@KorPhaeron give it another testmerge try but this time with the krav maga

**Comment by Fox-McCloud** [comment]
seems like powercreep to be honest---he should lose *something* for this. His taser, gloves, or something.

**Comment by jughu** [comment]
But then all players get grumpy because they lose stungloves 2.0
I mean look at the captain with all his powercreep stuff give the poor warden a cycler shotgun he has to stay in brig anyways ATLEAST the good ones

**Comment by PKPenguin321** [comment]
Poor warden only has the entire armory at his disposal

**Comment by jughu** [comment]
poor wardens need mroe advanced shotguns

**Comment by PKPenguin321** [comment]
. No ??

**Comment by Dorsisdwarf** [comment]
The warden already has a machinegun in his locker, he'll survive without a gun that lets him tase and lase but with buckshot.

**Comment by Fox-McCloud** [comment]
>The warden already has a machinegun in his locker

Uh, come again?

**Comment by jughu** [comment]
thats metastation @Dorsisdwarf

**Comment by ExcessiveUseOfCobblestone** [comment]
What's the point of the shotgun if it won't go anywhere because "it's for security", then when it goes to security it's "too strong"?

Also the Krav gloves are ok, just chop off his hands if you don't want to go against the owner of the armory :^)

**Comment by Shapsy** [comment]
A shotgun is going to deal just as much havoc whether or not you can press a button to switch it to nonlethal rounds, it's not like the armory doesn't have multiple shotguns already

**Comment by ExcessiveUseOfCobblestone** [comment]
can you not do this anyways by putting varying shells in the shotguns in a particular order?

**Comment by jughu** [comment]
Yeah you basically can but people often forget the next upcoming bullet

**Comment by optimumtact** [comment]
What's the ammo count?

**Comment by KorPhaeron** [comment]
4 in each tube, so 8 total

**Pull request merged**
