### PR TITLE
New lighswitch sprite

### PR DESCRIPTION
**Pull request by MTandi**
image

## Why It's Good For The Game

The new sprite uses neutral color instead of green-red combination used by things that show status of air, power, fire alarm.
The sprite is now a bit bigger, and in the same style as APCs. It also glows slightly in the dark.

https://user-images.githubusercontent.com/3625094/170317794-fae06315-bef5-4de6-bf6c-88c8d01f6185.mp4

Also, fixed the nopower state as it wasn't using power, even though it had unpowered sprites. Now it consumes 0.02, just like buttons. 

## Changelog

:cl:
imageadd: Changed light switch sprite and made it depend on the power availability.
/:cl:

### CODE REVIEW

**Comment by MTandi** [comment]
unknown
unknown1

**Comment by cacogen** [comment]
if you make it bigger it'll presumably cause overlapping with other things or over the edges of walls in certain places on maps

**Comment by MTandi** [comment]
> if you make it bigger it'll presumably cause overlapping with other things or over the edges of walls in certain places on maps

It's just 6x9 compared to the previous 5x9

**Comment by Imaginos16** [comment]
Yeah sure why not.

**Pull request merged**
