### PR TITLE
Improves mulebot movement code

### PR DESCRIPTION
**Pull request by LemonInTheDark**
## About The Pull Request

Unfucks mulebot timer bullshit, makes some math cleaner, and removes an old fuckup in how the code got translated from sleep to the if check we have now.

## Why It's Good For The Game

Hardens the code against timers dying, cleans shit up, and kickstarts the skogcoin market.

## Changelog
:cl:
fix: Mulebots no longer go insane when shit starts to lag
/:cl:

### CODE REVIEW

**Comment by LemonInTheDark** [comment]
Oh and have a [Video](https://cdn.discordapp.com/attachments/458452245256601615/712570681698811965/2020-05-20_00-31-44.mp4)

**Comment by Tlaltecuhtli** [comment]
does it fix the funny thing ?

**Comment by LemonInTheDark** [comment]
Depends, what issue report is the funny thing?

**Comment by MaltVinegar** [comment]
Found out the hard way that before this fix [this](https://media.discordapp.net/attachments/770646519078191116/818212285579395132/unknown.png) happened

**Pull request merged**
