### PR TITLE
Brings back ministation telecommunication.

### PR DESCRIPTION
**Pull request by mph55**
https://github.com/tgstation/-tg-station/pull/7627

Ministation telecomms is like this right now:
old
This PR brings bus, processor, broadcaster, receiver and the server back.

### CODE REVIEW

**Comment by Jordie0608** [comment]
Er, what is this meant to be doing?

**Comment by mph55** [comment]
It adds back telecommunications machines that were missing on MiniStation.

**Comment by hornygranny** [comment]
you need to use the map merger

**Comment by Cheridan** [comment]
RIP

**Pull request closed without merging**
