### PR TITLE
Cargonian Uniform Added to Cargo Wardrobe

### PR DESCRIPTION
**Pull request by SaintBurgher**
## About The Pull Request
This PR adds the Cargonian military uniform to the HACKED Cargo Wardrobe. There are enough for all cargo members.
## Why It's Good For The Game
This is good for whenever cargo wants to declare itself independent or in the case of rev rounds. Mostly added just for flavor.
## Changelog
:cl:
add: Cargonian Uniform Added
/:cl:

### CODE REVIEW

**Comment by actioninja** [comment]
you're missing an end of file newline on the cargo uniform file.

**Comment by Pugie** [comment]
Add a mosin to the clothes vendor contraband too

**Comment by FantasticFwoosh** [comment]
nice idea, but i don't like the blurryness of the sprite; especially around the area where the badge and the shoulderpads are with the contrast, but that's just my personal taste.
my eyes are bleeding

**Comment by optimumtact** [comment]
I think we have enough problems with the amount of bandwidth hosting a tg server takes to not need this

**Pull request closed without merging**
