### PR TITLE
Adds charger holoparasites to traitor

### PR DESCRIPTION
**Pull request by ChangelingRain**
:cl: Joan
rscadd: Traitors can now buy charger holoparasites.
rscadd: Charger holoparasites move extremely fast, do medium damage, and can charge at a location, damaging the first target it hits and forcing them to drop any items they're holding.
/:cl:

chaaaaaaaaaaaaaaaaaaaaaarge

### CODE REVIEW

**Comment by Ninja137** [comment]
I was going to post that this might be too strong, but then I remembered that we allowed bees to be programmed and them to be able to get nanomachines and heart-attack chems in them

**Comment by ChangelingRain** [comment]
Take your salt elsewhere.

**Comment by Iamgoofball** [comment]
@ChangelingRain will I get bonus points if I have my holoparasite charge people off of a chasm

ps. make it do knockback so we get the full l4d2 experience

**Comment by KorPhaeron** [comment]
One of the core design bits of stands is they cant stun people (nor can they be stunned). I dont think this is good

**Comment by ChangelingRain** [comment]
Easily adjusted; it now forces them to drop any items they're holding instead of stunning.

**Comment by PKPenguin321** [comment]
>ps. make it do knockback so we get the full l4d2 experience

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

**Pull request merged**
