### PR TITLE
Staff of Animation costs 3 points now

### LINKED ISSUE #4490: Staff of animation is overpowered
Some objects (e.g. the ion rifle) have too much health and do too much damage. Especially considering the amount of other hostile objects on the station.

This has been the case since it was added. Issue report #286 ported from Dec 2012 is the earliest mention of the staff I've found. So it's been a problem for nearly two years.

### LINKED ISSUE #13835: Staff of Animation is annoying
You can animate an infinite number of things at once, and they don't revert until you kill them. Given enough time the Wizard can have hundreds of objects animated throughout the station, without any real crew interaction.

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
Very powerful and recall basically removes any downsides from it. Also fills the same niche as soulstones/necrostone but without letting other players join the fun. Still think it will be too strong after this but oh well.

Fixes #4490

Fixes #13835

### CODE REVIEW

**Comment by WJohn** [comment]
I think it'd be better if the animated objects stopped moving after a period of time, that way you can't permanently lock down areas you were at 10 mins ago, only immediately where you are for support.

**Comment by Bawhoppen** [comment]
The alternatives to this will be far superior now
If anything alot of things need a nerf than just the staff of animation

**Comment by Incoming5643** [comment]
The staff of animation is currently as popular as such hard hitting spells as "Smoke" and "Forcewall". I can't really see this being necessary.

**Comment by MMMiracles** [comment]
@Incoming5643 
You say this now.

But then you face the horror that is grille swarm.

**Comment by phil235** [comment]
This isn't a fix, it just hides the bug by making the staff less accessible. I'm with @WJohn, a timer for staff-animated objects would be a good solution.

**Pull request closed without merging**
