### PR TITLE
Sentinel's Compromise can now be used on yourself

### PR DESCRIPTION
**Pull request by ChangelingRain**
:cl: Joan
tweak: You can now target yourself with Sentinel's Compromise, allowing you to heal yourself with it.
/:cl:

This makes it really goddamn powerful but it does still do the toxin damage.
It'll also only list damaged targets, instead of all.

### CODE REVIEW

**Comment by InsaneHyena** [comment]
Does this mean sentinel's compromise will be actually used now?

**Comment by ChangelingRain** [comment]
It very well might be, healing is healing even if it's kind of shitty.
#18826 will make it a lot more rewarding to do so, as well

**Comment by coiax** [comment]
Ratvar's ideal servants are slimepeople apparently.

**Comment by Jazaen** [comment]
Ratvar is an equal opportunity employer. You don't have to be a slime or made out of brass to worship him, but it helps!

**Pull request merged**
