### PR TITLE
Simple multi-z audio

### PR DESCRIPTION
**Pull request by ghost**
:cl: qustinnus
 add: simple multi-z audio
/:cl:

saw a lack of this in the current implementation, sounds only propagate up and down if theres a transparent or open space for them to go through, this prevents you from hearing sounds that are under a dirt ground etc and some other edge cases, but isn't ideal, as things one tile next to an open turf wont be heard. It's a trade-off for performance but its much preferable over no audio at all imho.

### CODE REVIEW

**Comment by Qustinnus** [comment]
appveyor crashed which is why its red btw

**Comment by optimumtact** [comment]
This caused mobs to get duplicated into every single z level list and caused the "issues" that made icebox slow to a crawl.

**Comment by optimumtact** [comment]
FYI I strongly dislike this change, I do not believe we should attempt to do anything other than the network systems as multi z

**Comment by Qustinnus** [comment]
It's inconsistent to have half a multi-z implementation. But thats mostly my opinion. Also sorry for not using .Copy(); looking at the code again it seems logical it would cause it, but it didn't appear in my mind at the time.

**Comment by optimumtact** [comment]
That's alright, it's a very subtle bug, I don't think most people would have caught it on a simple review

**Comment by Dennok** [comment]
Great

**Pull request merged**
