### PR TITLE
Separates Medical Weaponry Tech Node

### PR DESCRIPTION
**Pull request by SynnGraffkin**
## About The Pull Request

Moves "Medical Weaponry" to be just Rapid Syringe Guns and appears after normal Weaponry research and the Cryostasis Shotgun shells to Exotic Ammo after Advanced Weaponry.

## Why It's Good For The Game

Honestly, the only reason I could have seen Rapid Syringe Guns (RSG) to be AFTER advanced weapons wasn't because of the gun itself, but because of whatever could be in the syringes fired from it, which could range from a moderately harmless syringe of Chloral Hydrate to a concoction of toxins or rarely just healing medicine or mutadone. The ammunition is more dependent on chemists, or whoever has access to chemistry machines, ability rather than just printing ammunition from various lathes on the station. Considering how science tends to do Weapons research last, unless varying circumstances occur such as War Ops happens or robotics wants guns on their mech earlier in a shift, people tend to ignore Medical Weaponry, and sometimes Weaponry in general, unless there is nothing else to spend points on or someone requests it. Considering the materials to make a RSG, which is just metal and glass, there really isn't a reason for it to be locked behind a second 10k point wall of "Advanced" weaponry.

I moved the shotgun shells to Exotic Ammunition, which is behind Advanced Weaponry, because not only do the shells require some kind of chemistry access or ability to put a payload in it, it also requires the ability to have a shotgun to begin with, which is behind cooperative walls of other departments such Security or Cargo buying gun crates, where as Medical tends to start with one or two single shot syringe guns that are usually rushed for.

## Changelog
:cl:

balance: Medical Weaponry can now be researched after basic Weaponry Tech. Cryostasis shotgun shells have been moved to the Exotic Ammunition node, with medical weaponry as a prerequisite.

/:cl:

### CODE REVIEW

**Comment by Tlaltecuhtli** [comment]
at least make it require weapon tech

**Comment by SynnGraffkin** [comment]
Gah, Mobile usage of this site is annoying. Anyways, Tlal, it DOES require weapon tech for them. It is just basic weapon tech instead of advanced weapon tech. So you still need to get the first weapon tech and advanced biotech in order for RSGs to be researchable, but the cryostasis shotgun shells require exotic ammo from advanced weapon tech. Honestly, I am kind of surprised no one used those shells as much with shotguns. It holds 10u and doesn't react like cryo beakers, so you can load 5u water / potassium into a shotgun.

**Comment by YakumoChen** [comment]
>He didn't even read the PR or spend 12 seconds looking at the code

Anyway, good change. I do feel like too much is locked behind advanced weaponry, which is a pain to get. Medical tech also suffers from "it's not parts or mining tools" syndrome, so you don't really see it researched until late round on average, but it is nice to see the chance for at least some weaponry coming out earlier

**Comment by ExcessiveUseOfCobblestone** [comment]
Is the cryostasis shell moved because the tech it's currently under never gets researched?

**Comment by SynnGraffkin** [comment]
I moved the Cryostasis shell to Exotic ammunition, because in my opinion, it IS exotic ammunition for a weapon that isn't normally attributed to medbay.

**Comment by actioninja** [comment]
I don't think you want to see the game with the rapid syringe gun being even easier to obtain.

**Comment by SynnGraffkin** [comment]
Why not? The tech barely gets researched, because like Chen says, it isn't part of the "Parts and mining" meta. Even then, the things that usually get done after such tech are Posi-brains / AI, other medical tech, BoH, mech shit that Roboticists want, and nanites.

**Comment by ExcessiveUseOfCobblestone** [comment]
Almost looks like medical tech needsto be a prereq to exotic then if it's not already.

**Comment by SynnGraffkin** [comment]
That could work, it honestly didn't cross my mind to do that, Cobbie.

**Comment by ExcessiveUseOfCobblestone** [comment]
update changelog

**Comment by SynnGraffkin** [comment]
Done.

**Pull request merged**
