### PR TITLE
Fixes stop-sounds not force-stopping internet midis

### PR DESCRIPTION
**Pull request by silicons**
kek

### CODE REVIEW

**Comment by Cyberboss** [comment]
I explicitly asked the guy to make sure this worked REEEE

**Comment by BeeSting12** [comment]
1 5 0

**Comment by ExcessiveUseOfCobblestone** [comment]
There is no stopping the madness.

**Comment by JJRcop** [comment]
I made it so if you don't provide anything and press ok that it will stop things, but didn't add it to the stop sounds verb.

**Review by JJRcop — APPROVED** [review]
This is what I should have done in the first place, and should work

**Pull request merged**
