### PR TITLE
Ayy, lmao, I forgot to give flightsuits research requirements :^)

### PR DESCRIPTION
**Pull request by silicons**
Woops.

### CODE REVIEW

**Comment by PKPenguin321** [comment]
"forgot"

**Comment by kevinz000** [comment]
hey I could just leave this out it doesn't matter it costs a crapton of mats anyways but I forgot meh so someone noticed and told me in deadchat lmao

**Comment by ExcessiveUseOfCobblestone** [comment]
and because anyone who has duke's can basically ignore anything that is below level 5 five minutes in.

**Comment by XDTM** [comment]
Also because i never see someone other than me try to make it

**Comment by Haevacht** [comment]
Worst PR ever stops my goal of building one in that maint room 0/10 see me after class mehki.

**Pull request merged**
