### PR TITLE
Reworks do_after and removes do_mob

### PR DESCRIPTION
**Pull request by JohnFulpWillard**
## About The Pull Request

I am doing a request from 2015 https://github.com/tgstation/tgstation/pull/9921#issuecomment-112570535

In this PR I have:
- made 'target' the second arg of do_after
- Renamed 'delay' to timer'
- ^ These basically made do_after use the SAME args as do_mob. I COULD'VE not spent 40 minutes manually going through every single do_after in the game, but I liked it better this way because target is important, and makes it consistent with many other procs that both have a user and a target.
- Removed do_mob entirely, replacing all instances with do_after
- Implemented some improvements of code from do_mob into do_after
- Manually went over every do_mob and do_after, making most of them use SECONDS for their time instead of dediseconds.
- Removed a tab from pAI's hacking cable
- removed now redundant check in ``code/game/object/items.dm`` since they both now use the same do_after

This PR has been brought to you by mario vs sonic beatbox battle by veralase as it has been stuck in my head the whole time.

## Why It's Good For The Game

Better consistency and merging 2 procs that have been the exact same but kept separate for 7 years because no one wanted to be the one to waste their time making the PR, well I've done it now.

## Changelog

Nothing player facing, I expect.

### CODE REVIEW

**Comment by san7890** [comment]
On Sybil Round 192623, Heretic Rune Drawing (which includes do_afters) was completely broken for everyone. Didn't see any relevant runtimes, but you would keep getting some odd balloon collision like this and be completely unable to ever draw a rune:

image

**Comment by san7890** [comment]
image

Most recent test-merge (Round 192680), the welding animation appears to be stuck on anything that is welded. Relevant issue is https://github.com/tgstation/tgstation/issues/70651.

**Comment by JohnFulpWillard** [comment]
testmerge seems to indicate this has gone fine

**Comment by JohnFulpWillard** [comment]
chances of something breaking by now?

**Comment by JohnFulpWillard** [comment]
giving in

**Comment by LemonInTheDark** [comment]
?

**Pull request closed without merging**
