### PR TITLE
Revert "Removes i did not grief them"

### PR DESCRIPTION
**Pull request by Iamgoofball**
You, you're just a chicken.

Cheep cheep.

### CODE REVIEW

**Comment by Armhulen** [comment]
:+1:

**Comment by Cheridan** [comment]
you are tearing me apart

**Comment by Tacolizard** [comment]
i did not remove it i did naaaaauuuuuugggghhht

**Comment by Mark9013100** [comment]
Everybody betrayed me.
I'm fed up with this world.

**Comment by Cyberboss** [comment]
Thumbs don't lie

**Pull request closed without merging**
