### PR TITLE
Healing hands 3 -- fuck kor suck my balls edition

### PR DESCRIPTION
**Pull request by ghost**
basically touch people to heal 5 brute+burn damage. doesn't work on androids/synths/borgs/yourself. 7.5 second cooldown.

it works but it needs sprites

🆑 More Robust Than You
add: Healing hands mutation
/🆑

### CODE REVIEW

**Comment by Iamgoofball** [comment]
that's a paddlin

**Comment by kevinz000** [comment]
are you sure you're over 18

**Comment by MoreRobustThanYou** [comment]
yes

**Comment by Iamgoofball** [comment]
he's not, which is why he's still perma'd

**Comment by MoreRobustThanYou** [comment]
and my balls really do itch

**Comment by SyruseEln** [comment]
i dont want a genetics buff

**Pull request closed without merging**
