### PR TITLE
Drone Rework 2022

### PR DESCRIPTION
**Pull request by Youtubeboy139**
## About The Pull Request

Replaces the old `droneDispenser` sprite with a modern rendition that looks sleeker and more in line with the current art style by eliminating the cabinet look. Also gives drones the ability to see what wires do what when working on the station - basically giving them the Engineer Skillchip - because drones shouldn't have to guess what the wires do.

## Why It's Good For The Game

Brings drone dispensers up to speed with the current art direction of the server and gives drones a minor QoL change that will make the ghost role a bit easier.

## Changelog

:cl:
qol: Gave drones the ability to see what wires do what (essentially the engineer skillchip)
imageadd: New Drone Dispenser sprite
/:cl:

### CODE REVIEW

**Comment by Simplehorror** [comment]
oh thanks for letting me know it was 2022 I almost forgot

**Comment by Youtubeboy139** [comment]
> oh thanks for letting me know it was 2022 I almost forgot

Nevermind then

**Comment by Valorium-RB** [comment]
This is why we can't have nice things

**Comment by Wallemations** [comment]
image

**Pull request closed without merging**
