### PR TITLE
Forces security to be fashionable

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
They start with berets and their sleeves rolled up as god intended

### CODE REVIEW

**Comment by Mercenaryblue** [comment]
Sec cap best cap

**Comment by Aloraydrel** [comment]
:ok_hand:

**Comment by CosmicScientist** [comment]
God intends blood to be on the batons too but we all know it's better to identify good officers from the marks of their actions rather than be clueless with visible perfection by default.

**Comment by PKPenguin321** [comment]
Ascended snowflaking

**Comment by KorPhaeron** [comment]
The problem is that officers without red hats+helmets look awfully close to assistants in stolen armour

**Comment by Mercenaryblue** [comment]
> The problem is that officers without red hats+helmets look awfully close to assistants in stolen armour

I believe that is a feature

**Comment by GunHog** [comment]
The Security Sprite war begins anew! I would prefer them in red, or blue with red highlights. There is simply not enough red.

**Comment by Supermichael777** [comment]
now they look simaler to mimes in stolen gear great.

**Comment by TechnoAlchemisto** [comment]
yeah add the caps god damn

**Comment by ChangelingRain** [comment]
I don't like it.

**Comment by KorPhaeron** [comment]
The caps in the code are not the caps you had in the preview I am not sure where those sprites went

**Comment by xxalpha** [comment]
Leave berets to the officers with good taste.

**Comment by KorPhaeron** [comment]
I think its important that officers are more visually distinct

**Comment by Dorsisdwarf** [comment]
Visually distinct from _what?_ More distinct from people pretending to be security? From infiltrators?

Use a secHUD.

**Comment by TechnoAlchemisto** [comment]
I think he means a red headpiece would help quell some complaints about them being not sec looking

**Comment by KorPhaeron** [comment]
From assistants. They are almost the same colour scheme as them right now.

The weird elitist "lol newfags dont know how to put on the good clothes" is not a good reason to only implement an outfit halfway.

**Comment by Niknakflak** [comment]
:-1:

**Comment by KorPhaeron** [comment]
@GunHog 

The hats are red, this PR adds more red

**Comment by Thunder12345** [comment]
Give them the parade jackets, that'll make them distinctive again

**Comment by Niknakflak** [comment]
:-1:

**Comment by TechnoAlchemisto** [comment]
I feel like I keep seeing niknak do the exact same emotes but I keep thinking I hallucinated them

**Comment by Steelpoint** [comment]
If you want to quell security officers looking non-distinctive enough, then don't dress them all up in a grey uniform. 

On this PR, I disagree with it. Imo I think a Beret should be reserved for the HoS and Warden to better distinguish them. Keep Officers with helmets and caps.

**Comment by KorPhaeron** [comment]
I'll try and get better cap sprites then

**Comment by KorPhaeron** [comment]
Guess nobody wants to merge this

**Pull request closed without merging**
