### PR TITLE
Spays and neuters holographic animals

### LINKED ISSUE #46529: cats can reproduce with holographs
https://monosnap.com/file/ceQ2qRxwHm6iQxhD8csDtCYRm0zIIF

119291

### PR DESCRIPTION
**Pull request by 81Denton**
## About The Pull Request
This PR prevents holographic animals from reproducing.
Fixes: #46529

## Why It's Good For The Game
Please remember to spay&neuter your holo pets

## Changelog
:cl: Denton
fix: Holographic animals can no longer reproduce.
/:cl:

### CODE REVIEW

**Comment by Quartich** [comment]
Feature not a bug.

**Comment by ATH1909** [comment]
Keep this as a feature; it won't hurt anyone, right?

**Comment by 81Denton** [comment]
It's unintended since holographic mobs shouldn't interact with non-holographic mobs in this fashion. 

Feel free to add code where holographic mobs reproduce with each other though.

**Comment by ExcessiveUseOfCobblestone** [comment]
you need a permit to breed pure holographic animals

**Pull request merged**
