### PR TITLE
Makes Cayenne as harmless as advertized

### PR DESCRIPTION
**Pull request by Supermichael777**
:cl:
tweak: Cayenne can no longer pull soap, break windows, or kill people
/:cl:

Pulling soap at a billion miles per hour gets old when every load of ops does it.

### CODE REVIEW

**Comment by KorPhaeron** [comment]
lol

**Comment by Supermichael777** [comment]
oh right i will do this properly

**Comment by PKPenguin321** [comment]
It unironically is really fucking strong as long as https://github.com/tgstation/tgstation/issues/26839 exists

**Comment by PKPenguin321** [comment]
Turbo purple man that stuns you by touching you

**Pull request closed without merging**
