### PR TITLE
Plasmamen no longer have radiation immunity, but their helmets are now radiation immune to compensate.

### PR DESCRIPTION
**Pull request by CRITAWAKETS**
## About The Pull Request

maintainer permission:

Plasmamen no longer have the radiation immune trait. To compensate, the plasmamen helmets now have 100% radiation resistance and have had changes in the descriptions of the ones where it is needed the most. (e;g: Engineering and Atmos helmets.)

## Why It's Good For The Game

There is a noticable trend where every single person who powergames fusion plays plasmaman. The reason for this is that they have radiation immunity, so they do not have to care about the radiation from the fusion mixing. Want your radiation immunity back? Wear a radsuit. Unfortunately you have no pressure protection if you do so. That said there is still the CE hardsuit.

## Changelog
:cl:
balance: Plasmamen now no longer have radiation immunity.
balance: Plasmamen helmets now have 100% radiation resistance.
/:cl:

### CODE REVIEW

**Comment by Dawson1917** [comment]
plasmamen are a nuisance but just removing their rad immunity, and making them even more of a human reskin in the process, isn't interesting. radiation having a different mechanic against plasmamen would be far better

**Comment by ExcessiveUseOfCobblestone** [comment]
full damage immunity is a more creatively bankrupt approach and, as we've all seen, it ripe for abuse.

**Comment by ATH1909** [comment]
Isn't the problem here with some of the more broken mechanics of fusion, not with plasmamen?

InB4 we get wizards who turn themselves into golems, teleport into atmos, and start fusion flooding again.

**Comment by 81Denton** [comment]
Fusion mass murder potential has been nerfed recently (#47073 and #46806), so this might not be neccessary anymore.

**Comment by Ghilker** [comment]
radiation immunity is the only trait plasmamans have good, if you remove this they become worse than moths

**Comment by SynnGraffkin** [comment]
Plasmemes already had their built in flash protection removed. Don't remove their rad protection.

**Comment by CRITAWAKETS** [comment]
Plasmamen already have cold immunity which doesnt sound like much at first until you realize that with just a fire suit you can EVA freely so they have a pretty big upside along with some smaller ones like virus immunity. 
also muh hardmode race

Also want your radiation protection + EVAing? Use the CE hardsuit. It is more obvious than before and there is only one though.

**Comment by lolman360** [comment]
i don't like this pr because it's a plasmaman nerf, but rads aren't even that bad

**Comment by 81Denton** [comment]
I'm not sold on this since the abuse potential will be severely reduced with the fusion fixes and future radiation rework. Any other maintainer is free to weigh in of course.

**Comment by Jordie0608** [comment]
I think the current rad immunity is fine plus the above.

**Comment by Ty-the-Smonk** [comment]
Give them high rad resistance but not immunity, having a plasmeme with rads using scientific notation shouldn’t be allowed

**Comment by Ghilker** [comment]
Never saw one... Have you?

**Comment by ExcessiveUseOfCobblestone** [comment]
let's hold off on this, reopen if it's still an issue after the items mentioned above

**Pull request closed without merging**
