### PR TITLE
All space suits can now hold oxygen and air tanks

### LINKED ISSUE #7441: Balance Suggestion: Space Suits, Hardsuits, and Tanks
With the recent nerf to hardsuits and the effective elimination of spacesuits, I suggest a buff to all spacefaring gear: allow spaces suits and all child items to equip large tanks in their exosuit slot, just like hardsuits were once able to do.

### PR DESCRIPTION
**Pull request by ghost**
fixes https://github.com/tgstation/-tg-station/issues/7441

Apparently this allows tanks without the side affects of allowing jetpacks in the suit storage slot so everyone's happy.

### CODE REVIEW

**Comment by Dorsisdwarf** [comment]
Hail the spessman overlord paprka.

**Comment by Fox-McCloud** [comment]
:+1:

**Comment by xxalpha** [comment]
Maybe this one will get merged, since its paprka.

**Comment by phil235** [comment]
:+1:

**Comment by Miauw62** [comment]
this is pretty hacky, can't you split the types so you have /atmoscontainer/tank and /atmoscontainer/jetpack or something?

**Comment by xxalpha** [comment]
This https://github.com/tgstation/-tg-station/pull/7474 might be a better solution. It's a remake of another PR of mine.

**Comment by RemieRichards** [comment]
@xxalpha No offence, but I prefer this change by far.

**Comment by paprka** [comment]
This is really not hacky at all compared to xxalpha's change

**Comment by Miauw62** [comment]
It sort of really is. You're only including two subtypes and any others
will have to be manually added
Op 1-feb.-2015 01:14 schreef "paprka" <notifications@github.com>:

**Comment by paprka** [comment]
those are literally the only subtypes that matter

would you prefer plasma tanks and jetpacks or something

**Comment by Miauw62** [comment]
Tbh you should be able to use plasma tanks
Op 1-feb.-2015 10:38 schreef "paprka" <notifications@github.com>:

**Comment by paprka** [comment]
i don't care just merge one of these i'm so tired of this not being a thing

**Pull request closed without merging**
