### PR TITLE
Non-airlock doors check for mobs while closing + extra shit

### PR DESCRIPTION
**Pull request by harmonyn**
- Non-airlock doors check for mobs while closing. Fixes https://github.com/tgstation/-tg-station/issues/14005. Door/airlock procs are messy, I know. The alternative to yet another proc is copypasta.
- Removed a bunch of fucking terrible istypes from airlock code.
- Minor edits to messages. FULL DISCLOSURE Y'ALL.

### CODE REVIEW

**Comment by swankcookie** [comment]
OBVIOUSLY cicuritry is referring to the reinforced panels covering the wiring.

**Comment by Bawhoppen** [comment]
why must you make everything so impersonal

**Comment by bgobandit** [comment]
it's an AI message

**Comment by xxalpha** [comment]
Yeah, it doesn't make sense when it says "We", silicons aren't the geth.

**Pull request merged**
