### PR TITLE
removes the block chance from bloody bastard swords

### PR DESCRIPTION
**Pull request by jughu**
They were meant to be a counter to hulks and they dont need an block chance when their litteraly spin 2 win technique reflects all gun shots

:cl: Improvedname
tweak: Bloody bastard sword no longer blocks shots
/:cl:

[why]: # (Please add a short description [two lines down] of why you think these changes would benefit the game. If you can't justify it in words, it might not be worth adding.)

### CODE REVIEW

**Comment by tgstation-server** [comment]
You currently have a negative Fix/Feature pull request delta of -2. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

**Comment by calzilla1** [comment]
Werent they removed?

**Comment by jughu** [comment]
They are still in and mass producable by cult basically they have 50 block chance to block ranged and melrr like an katana and a spin attack that reflects all shot 3 hit KO removing the block chance will give crew a fair chance fighting it then litteraly be destroyed before you know it

**Comment by jughu** [comment]
Im sure removing passive block chance will involve more risks in vastard sword murderboned

**Comment by imsxz** [comment]
i ded pls nerf

**Comment by jughu** [comment]
Its a reverse case of i ded i murderboned and won hard

**Comment by Buggy123** [comment]
When will we be able to stick 2 of them together and get a dual bloody bastard sword with 100% ranged&melee block and 70 force?

**Comment by jughu** [comment]
for april fools three and have 100 brute and 100% block chance and 100 armour penetration

**Comment by Buggy123** [comment]
Better idea: N-eswords. Like dual eswords but you can just attach as many as you want, and force&melee block rises with each one. At higher numbers, you also dismember anyone who disarms you because they literally can't reach the hilt without hitting a blade.

**Comment by KorPhaeron** [comment]
>You currently have a negative Fix/Feature pull request delta of -2. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

**Comment by jughu** [comment]
Murdeebone instefies

**Pull request closed without merging**
