### PR TITLE
Alt-click for aesthetic toggling

### PR DESCRIPTION
**Pull request by ghost**
This makes rolling down your jumpsuit and toggling the buttons on labcoats / suit jackets / etc use alt-click instead of an object verb which is pretty much terrible.

This should probably be applied to more clothing for variety and stuff. Ideally you could roll up the sleeves of any jumpsuit (mask overlay that cuts off the sleeves), and roll down any jumpsuit, instead of having to choose between the two, but whatever. Easier usability for something that doesn't occur often, small aesthetics like this should remain relatively out of the way since they're only done once or twice a round.

Not applied to hoods or hardsuits or anything, those are kind of different and can have serious gameplay affects.

Death to object verbs. удаления объекта глагола сука

### CODE REVIEW

**Comment by MrStonedOne** [comment]
object verbs can be typed, alt clicks can not

:-1: until you leave both.

Aren't you suppose to be banned.

**Comment by paprka** [comment]
Well the point of this PR is to kind of de-clutter the objects tab when you're wearing a lot of clothing, this is kind of a big verb for something that is only a minor aesthetic change which can be done with alt click, imo.

**Comment by Razharas** [comment]
>удаления объекта глагола сука

google translate/5

**Comment by paprka** [comment]
trolled

**Comment by Dorsisdwarf** [comment]
:+1:  for decluttering the object verb tabs. It's like this constantly changing grid of long words that makes it impossible to use while running

**Comment by Steelpoint** [comment]
Nice but it kinda defeats the point of being "banned" if one can still contribute.

**Comment by RemieRichards** [comment]
I'd prefer if the verbs were left over and the altclick calls simply redirect to the verb.
Object verbs on their OWN are pants, but as an optional choice, I feel they are ok.

Headcoders feel free to slap me.

**Comment by pudl** [comment]
>stealing my benis meme

**Comment by pudl** [comment]
alert: i said benis first, before everyone else did

**Comment by pudl** [comment]
people even got mad at me and told me it was a forced meme when i spammed it on sybil

**Comment by pudl** [comment]
dont delete those comments they're top priority

**Comment by Dorsisdwarf** [comment]
We need to be able to tag individual posts.

**Comment by dannno** [comment]
step 1 of removing object verbs :+1: :+1: :+1: :+1: :+1: :+1: :+1: 

>Aren't you suppose to be banned.

can you fuck OFF? this is a good PR, take it somewhere else

**Comment by Dorsisdwarf** [comment]
hey pudl stop posting in topics I post in it just sends me a frillion emails from your actual email account or something

**Comment by RemieRichards** [comment]
@Dorsisdwarf it's sent from notifications@github.com using the poster's Name fields on their profile.
Which is why @pudl shows up as Annie Acosta and my self Remie Richards and @Miauw62 as Swag McYolosteinen.

I'm pretty sure there's an option on your profile to disable notifications overall.

**Comment by MrStonedOne** [comment]
you can remove verbs from the tabs by giving it a null category

than they only work for typing.

come on @paprka you should know this by know

**Comment by RemieRichards** [comment]
Actually I personally would like them left in 100%, not just in the command bar (which sucks ass, it's useless)

**Comment by dannno** [comment]
I use the command bar quite a bit, actually.

**Comment by RemieRichards** [comment]
<B>USELESS</B>

**Comment by pudl** [comment]
literal scum lmao

**Comment by Thunder12345** [comment]
Didn't someone say something before about every mob having to process something for all its verbs constantly?

**Comment by paprka** [comment]
I don't think that's the case, if it is, first I'm hearing of it.

@MrStonedOne Thanks, I was looking for a way to keep verbs without having them clutter up the tab. Readded.

**Comment by Razharas** [comment]
Yes, object verbs are being checked like lights or vision, every time on the move everything is reprocessed
You can open the verbs tab and run around to see the verbs poppin in and out like crazy, the more objects with verbs there are in the game the more it checks for things each time each mob moves
In short - object verbs are bad

**Comment by paprka** [comment]
Well this is just a normal verb now, no longer an object verb, I removed the category as MSO suggested.

**Pull request merged**
