### PR TITLE
Replaces all sleepers from escape shuttles with stasis units.

### PR DESCRIPTION
**Pull request by nemvar**
## About The Pull Request

Does the thing nobody dared to do.

Also adds nanomeds to the luxary shuttle (but not to the pleb section).

## Why It's Good For The Game

If we are serious about changing the way medical is played, this change would need to happen sooner or later. The current reason why we still have sleepers on shuttles isn't gameplay related and simply because it was out of the scope of the original PR.

Most (sane) shuttles don't lack in meds anyways, so this somewhat of a buff if you can be easily fooled.

## Changelog
:cl:
del: Removed all sleepers from escape shuttles and replaced them with stasis units. Some shuttles have gotten surgery and new medical vendors added.
/:cl:

### CODE REVIEW

**Comment by spessbro** [comment]
yes thank you, might also be good to remove the sleepers in space ruins while you're at it

**Comment by spessbro** [comment]
if you move the sleeper board imma hate you forever

**Comment by HomocidlePancakes** [comment]
Most of the shuttles don't even have brute medkits so either add them or keep sleepers. I am keen on the second cuz medkits always get looted

**Comment by Whoneedspacee** [comment]
like why though, if you add this then the only concievable way you’ll play the rest of the round is attached to a damn stasis bed why bother at that point.

**Comment by Detective-Google** [comment]
The big caveat to this I see is just sticking some dude in stasis so his injuries are complete stasis, vs sleepers where yes they can be healed but their injuries don't progress

The true move would be to A:add more med supplies to the shuttle and 
B: remove sleepers and replace them with beds that have medical sheets

**Comment by Fikou** [comment]
oh boy i sure do love 2 stasis sleepers in which a person is probably gonna be kept for a whole minute on a shuttle with most of the stations populaton and antags usually wanting to cause havoc

**Comment by ishitbyabullet** [comment]
i think sleepers have personally murdered multiple coder's dogs or some shit at this point.

**Comment by nemvar** [comment]
@HomocidlePancakes Most sane shuttles have nanomeds. I will go through them again and check which ones don't have any and add them if needed. Or, big think, what if we were to expect doctors to actually MOVE medical supplies TO the shuttle. Players are honestly way too tampered with this kind of stuff. Anything that requires a minimum of planning or even just thinking is seemingly impossible to some.

@Whoneedspacee There is so much wrong with your statement. What you are refering to is literally just the case where you get critted and nobody can be assed to give you proper help. It will happen with or without sleepers, only that sleepers are a crutch for braindead people.

**Comment by ExcessiveUseOfCobblestone** [comment]
1 stasis bed and 1 surgical table /w tools would be nice, at the very least people should be able to heal off brute/burn via tend wounds.

some shuttles like meta have TWO NANOMEDS that may/may not be free. like lol...

**Comment by SgtxRootbeer** [comment]
I'd like you to consider the fact that the emergency escape shuttle is just that. Both thematically and in practice, it's supposed to be called to a dying station's aid. Proposing that doctor's move medical supplies to the shuttle is like going onto a modern ship and removing the first aid kits from the life rafts because they have a fully stocked sick bay. Nevermind the fact that due to the events of the round there might not even be any doctors.

**Comment by Timonkeyn** [comment]
So... No meds on shuttle because chemistry got blown up is what the coder man's are saying?

**Comment by ExcessiveUseOfCobblestone** [comment]
Medkits in space do a heck of a lot more to the patient than a medkit IRL.

Even if you had medkits in a life raft chances are you'll still need items from the sickbay of a ship if the situation calls for it. You can't 0-100 someone with the contents of an IRL medkit like you can with the game's.

> So... No meds on shuttle because chemistry got blown up is what the coder man's are saying?

I suggested a surgical table so you can perform our game's equivalent of emergency aid. Most shuttles have nanomeds too which are just as powerful as a sleeper (although I would like those to be removed in the near future too).

**Comment by kopoba** [comment]
Add chemestry on shuttles then.

**Comment by ExcessiveUseOfCobblestone** [comment]
No? The only thing you need if a surgical toolset it provided is Toxdamage meds because all other types have a Cat1 healing method.

**Comment by Detective-Google** [comment]
Surgery on tg is slow, slow enough the shuttle has landed or the patient is dead before treatment is done

Surgery also doesn't heal toxin and oxyloss damage

**Comment by nemvar** [comment]
Does anyone know why map diff doesn't like this? Ugh... guess I take pictures manually.

**Comment by ExcessiveUseOfCobblestone** [comment]
Then you die unless they premade emergency chems. You're going to outheal brute/burn anyways with the surgery unless you're currently being attacked which I would argue chems that negate someone constantly taking damage shouldn't be widely available to begin with.

Also surgery is not that slow unless you manage to choose the wrong tool at literally every step. You can also get better tools (implant and surgical power tools) that increase the speed. For the tend wounds surgeries specifically, there is an upgrade that heals both brute and burn 250% faster than the normal tend wounds surgery if you researched it.

CPR heals oxyloss fine enough for the purpose of getting to central unless you're poisoned and I already mentioned tox would need to be addressed.

**Comment by wesoda25** [comment]
Nah removal off shuttle is good, not so sure about space ruin removal tho (you can’t harvest them anyways).

**Comment by nemvar** [comment]
Added two nanomeds to the asteroid shuttle - Has surgery
Added a single nanomed to the bar shuttle - Has surgery
Added a nanomed to the birdboat shuttle - Has surgery
Added a nanomed to the box shuttle - Doesn't have surgery
Added a nanomed to the clown shuttle - Doesn't have surgery
Added nothing the cere - Has surgery
Added nothing to cramped - Doesn't have surgery
Added nothing to delta - Has surgery
Added nothing to disco shuttle - Doesn't have surgery
Added surgery to the donut shuttle - Now has surgery
Fuck Daniel - Doesn't have surgery
Added nothing to the kilo shuttle - Has surgery
Added two nanomeds and surgery to the luxery shuttle. Nanomeds are not free.
Added nothing to asteroid - Doesn't have surgery
Added nothing to meta - Has surgery
Added surgery to mini - Has surgery
Added nothing to omega - Has surgery
Added a nanomed to pubby - Has surgery
Added nothing to raven - Has surgery
Added surgery to mother russia bleeds - Has surgery
Added nothing to scrapheap - Doesn't have surgery
Added nothing to supermatter - Doesn't have surgery
Added nothing to wabbajack - Doesn't have surgery

Full list of new changes. I wish map diff would work

**Comment by nemvar** [comment]
bar
bar
birdboat
birdboat
box
box
cere
cere
clown
clown
delta
delta
donut
donut
goon
goon
kilo
kilo
meta
meta
mini
mini
omega
omega
pubby
pubby
raven
raven
fuck poor people
rich
russia
russia
wabbajack
wabbajack

**Comment by bigfatbananacyclops** [comment]
The emergency shuttle is meant to be supportive and a backup for emergencies on the station, there could probably be a lack of supplies and Centcom is on charge to make sure they have enough supplies so they can get out safely, irrelevant but, why remove the sleepers? Its not like they will be there the whole round, they’re there to support the amount of people that are hurt in the shuttle, almost the whole station is boarding it.

**Comment by FloranOtten** [comment]
Let's keep them on the emergency shuttles. They're emergency shuttles. Clue's in the name. There's going to be a lot of people in need of treatment. Why would Centcom, the most powerful station we know of, stock the massive shuttle meant to haul valuable Human Resources(tm) with a couple of bruise patches and some ointment? 

>yes thank you, might also be good to remove the sleepers in space ruins while you're at it

God no. That's the only gimmick for a bunch of ruins. They're space ruins. You cannot harvest them, so what's the balance concern? 

And if you remove the Syndicate Sleeper off that one ruin I don't know the name of that has dual blast doors meant to space people, you'll take away that particular ruins entire damn gimmick.

**Comment by nemvar** [comment]
@FloranOtten Yes, it's an emergency shuttle. So what? Why would centcom do anything? They literally have god powers if we talk about how their name is usually used ingame. We are on a high tech research station, with a state-of-the-art medbay. Why does that thing not have sleepers? Because that's just a thing from a lore perspective. Why would an emergency shuttle have better medical care than a fucking hospital? In short, loreposting is stupid.

Also I'm fairly certain that ruins gimmick is that it has secret documents and a syndi hardsuit, and not that it has a sleeper. Sleepers used to be (and still are) in a lot of space ruins. It's not even like it would impact the functionality, because that ruin also has a bunch of medkits.

**Comment by ExcessiveUseOfCobblestone** [comment]
dis is fine

**Review by ExcessiveUseOfCobblestone — APPROVED** [review]

**Comment by ExcessiveUseOfCobblestone** [comment]
> lets be honest, stasis are completely useless and their only good use is to prevent damage from increasing or to pause a dangerous chemical’s progress inside a body, it should have more versatility, its not even portable.

remember, if you can't 0-100 from the same machine then it's completely useless outside of the really important uses I just mentioned!

**Comment by AdamElTablawy** [comment]
is making it so that people can't heal other people in the last five minutes of the round that important

**Comment by ExcessiveUseOfCobblestone** [comment]
You still can though?

Yes it's a big deal to heal people easily regardless of round time so long as the round has not ended. Antags can still antag and mishaps can still be mishappening.

**Pull request merged**
