### PR TITLE
Nearsighted people can't read without glasses

### PR DESCRIPTION
**Pull request by timothymtorres**
## About The Pull Request

This was split off of https://github.com/tgstation/tgstation/pull/65668 into its own separate PR.

There was discussion in the original PR about how the medical definition for nearsighted is only for far away objects instead of bad vision.  I tried to resolve this by renaming nearsighted to halfsighted in: 

- #66275 

Feel free to close this at will if this isn't going to workout.

## Why It's Good For The Game

Time to powergame by stealing all the prescription glasses.

## Changelog

:cl:
expansion: Nearsighted people can no longer read without glasses
/:cl:

### CODE REVIEW

**Comment by dragomagol** [comment]
Why is this good for the game?

**Comment by Y0SH1M4S73R** [comment]
Hot take:
Instead of making you unable to access the paper UI without glasses...
You should use CSS to blur the text to the point of near-illegibility.

**Comment by wesoda25** [comment]
What? Can't read at all or is it proximity based?

**Comment by CRITAWAKETS** [comment]
bullshit, im able to read this after taking off my glasses by just leaning in

**Comment by Serxule** [comment]
do you not know how being nearsighted works 😐

**Comment by Wallemations** [comment]
> Hot take:
> 
> Instead of making you unable to access the paper UI without glasses...
> 
> You should use CSS to blur the text to the point of near-illegibility.

I agree with this, but if this is too much work...

> im able to read this after taking off my glasses by just leaning in

...another easier rendition could simply be making nearsighted people require a short do_after to lean in to the thing they're trying to read.
Something like 0.5 seconds would work fine imo.

**Comment by Serxule** [comment]
> ...another easier rendition could simply be making nearsighted people require a short do_after to lean in to the thing they're trying to read. Something like 0.5 to 1 seconds would work fine imo.

this is literally what i do, its easier to read stuff when my glasses are off so the time delay would make sense

**Comment by thgvr** [comment]
Nearsighted enjoyer here

Nearsighted makes you unable to see far away, this is silly

**Comment by timothymtorres** [comment]
Alright so after doing some brainstorming I've decided to close this.  

I plan on making a new PR where the effects of having your eye stabbed out or taking eye damage results in a new status condition halfsighted.  Nearsighted will be an exclusive only for the quirk.   All other forms of eye damage (with the exception of blindness) will result in halfsight.  Both halfsight and nearsight are just semantics for eye damage and poor vision.

**Pull request closed without merging**
