### PR TITLE
New soapstone sprites

### PR DESCRIPTION
**Pull request by ghost**
:cl: Xhuis
add: Soapstones and their messages now have nicer-looking sprites.
/:cl:

Atomized from #23717

soapstone
message

### CODE REVIEW

**Comment by anconfuzedrock** [comment]
why would we want soapstone messages to look BIGGER?

**Comment by Xhuis** [comment]
Right now, they're handled in a poor way - the greyscale sprite they use has a generally random color, meaning that some messages are completely invisible. While it's hard to see here, the messages are almost invisible in practice and can be reliably seen without being intrusive.

[Exhibit A](https://puu.sh/tONHZ/3bf2c2d7bf.png)

**Comment by KorPhaeron** [comment]
@coiax @Iamgoofball 

I prefer the old sprites and feel like this is going to make the spam even more annoying but this is your guys thing so let me know

**Comment by Hatfish** [comment]
Why not just keep the tiny message sprites and make them only choose from higher (or lower, if that's the problem) contrast colors?

**Comment by Xhuis** [comment]
Because the sprites are only one color, and colors are chosen from message contents. No matter the color, there will always be the potential for a turf to hide the message entirely. I want to eliminate that.

**Comment by dannno** [comment]
way too big
why is object so fucking big

**Comment by Iamgoofball** [comment]
these sprites are great

the sprites I used originally were lifted cult rune sprites anyways

**Comment by TehZombehz** [comment]
Part of me wishes they had ever-so slight animated glowing.

**Comment by Xhuis** [comment]
They actually do. It's just not included in this OP!

**Comment by coiax** [comment]
With free retries, a person can just change the message content to change the md5 determined color, if they REALLY care.

Also, @KorPhaeron has a point, keeping them smaller and less noticable is probably better.

@Xhuis I suggest a test merge or two, see how it looks in practice.

**Comment by Xhuis** [comment]
Sure, that's fine to me.

**Comment by KorPhaeron** [comment]
Well one creator said yes and one creator said no so I'm going to tie break and say these shouldn't be more noticeable or else people will get mad and try to remove them entirely again

The soapstone sprite is better though I'd merge that alone

**Comment by dannno** [comment]
ITS TOO BIG

**Comment by Xhuis** [comment]
Okey doke, I'll cut out the message sprite. I'm still gonna push for the actual soapstone tho

**Comment by dannno** [comment]
THE SPRITE IS TOO BIG WHY IS IT SO BIG JUST MAKE IT SMALL

**Comment by Xhuis** [comment]
It isn't actually that big, it's enlarged for github.

**Comment by dannno** [comment]
I know.

**Comment by Xhuis** [comment]
>:(

**Pull request closed without merging**
