### PR TITLE
You can now send PDA messages when resting

### PR DESCRIPTION
**Pull request by Maia-J**
## About The Pull Request

No longer must you stand up when sending messages over the PDA! Do it all comfortably, laying down in your bed!

Computers are automatically inaccessible when resting, so this only affects PDA's, TABLETS, and LAPTOPS

## Why It's Good For The Game

Why wouldn't I be able to use a PDA laying down, heck everyone uses their phone laying on their back, using your PDA like that  only makes sense

## Changelog
:cl:
fix: The messenger app can now be used when laying down.
/:cl:

### CODE REVIEW

**Comment by lessthnthree** [comment]
This is actually a fix, not qol. It's supposed to have been working: https://github.com/tgstation/tgstation/pull/72934

**Comment by Majkl-J** [comment]
> This is actually a fix, not qol. It's supposed to have been working: #72934

Roger, updating changelog accordingly

**Comment by Jacquerel** [comment]
You should have a small chance to drop it on your face.

**Comment by Majkl-J** [comment]
> You should have a small chance to drop it on your face.

This would honestly be pretty funny, but better for another PR

**Review by Ghommie — APPROVED** [review]

**Pull request merged**
