### PR TITLE
sec hailer emag

### PR DESCRIPTION
**Pull request by dannno**
:cl: Dannno
add: Sec hailer gasmask can now be emagged for a more rational, calm message.
/:cl:

I dunno why I gave up on this and no one else picked it up
i wanted to make it burn you bad if you spammed it but I dunno how haha :)

### CODE REVIEW

**Comment by ma44** [comment]
How do you emag the helmet? Do you just slap it with an emag?

**Comment by dannno** [comment]
what helmet

**Comment by ShadowDeath6** [comment]
he means the sechailer

**Comment by Cyberboss** [comment]
Dude, you need to use the complionator TTS for the love of all that is holy

**Comment by dannno** [comment]
don't have the know how to make such a sound file, but would willingly accept one

**Comment by YakumoChen** [comment]
maybe cause the hailer to break more quickly if you spam it

**Comment by Cyberboss** [comment]
@Malkevin added the sechailer pharses originally

**Comment by Shadowlight213** [comment]
It should just break immediately after first use when emagged.

**Comment by anconfuzedrock** [comment]
BEEEPSKY SAYS COCKSTORM NOT COCKSUCKER!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by anconfuzedrock** [comment]
also he says abortions AND FUCK not of fuck

**Comment by RemieRichards** [comment]
Beepsky's correct line (for the 500th time of correcting people) is:

```
fuck your cunt you shit eating cockstorm and eat a dong fucking ass ending shit fuck eat penises in your fuck face and shit out abortions of fuck and poo and shit in your ass you cock fuck shit monkey fuck ass wanker from the depths of shit
```

**Comment by dannno** [comment]
i fix it :)

**Comment by RemieRichards** [comment]
thank.

**Comment by Malkevin** [comment]
https://dl.dropboxusercontent.com/u/95696802/Commits/secmask/badbot.ogg

**Comment by Malkevin** [comment]
http://www.cepstral.com/en/demos

Voice: Damien
Rate: Default
Pitch: High
Effect: Old Robot

**Comment by dannno** [comment]
ah thanks

**Comment by lordpidey** [comment]
May I ask how you made the new file?  I'm interested in re-creating #13244 with better sound files.

**Comment by Cheridan** [comment]
@dannno the audio has like 2-3 seconds of silence at the end looks like

**Comment by dannno** [comment]
it has under 1 second of silence

**Comment by Jordie0608** [comment]
There's about 1.4 seconds of silence
capture

**Comment by Cheridan** [comment]
BOOM

**Comment by dannno** [comment]
FUCK

**Comment by dannno** [comment]
that actually is so weird how it cuts the file in half

**Comment by dannno** [comment]
merge this NNNNNOWWWWW

**Comment by ShadowDeath6** [comment]
https://github.com/tgstation/tgstation/blob/master/strings/brain_damage_lines.json#L33

**Comment by dannno** [comment]
SHIT

**Comment by Malkevin** [comment]
>Edit: You must be doing something weird, just resaving this file in Audacity sans the silence cut the size in half with no audible difference

That would be because you halved the bit rate.

**Comment by lordpidey** [comment]
So uhh... licensing memes.

**Comment by Cheridan** [comment]
>This service provided for demonstration and evaluation purposes only. No additional rights to use or distribute audio are provided. All submissions are logged.

wow malkevin real nice illegal audio you got there

**Comment by Cyberboss** [comment]
SHHH WE DIDNT SEE ANYTHING OK?

**Comment by Malkevin** [comment]
*shrugs* your problem not mine.

**Comment by lordpidey** [comment]
From the looks of it, we can get legal rights to use it for $10.

I'll look into if that's compatible with our license later.  But I'm willing to drop $10 on this, provided it will work.

**Comment by dannno** [comment]
What's the problem

**Comment by Cheridan** [comment]
@lordpidey Oh, it's only 10 dollars? That's not so bad, I assumed it would be something absurd like how Photoshop was 700 smackers

**Comment by lordpidey** [comment]
I'm looking into it now, the website isn't exactly clear, it just says look at the EULA, which isn't available until you purchase.

Either way, Damien appears to be one of their cheaper voices.

**Comment by lordpidey** [comment]
Lol no, $5,000.

**Comment by dannno** [comment]
fucking pardon me?

**Comment by optimumtact** [comment]
Here's a nickel :dollar:

**Comment by optimumtact** [comment]
:copyright: strikes again

**Comment by dannno** [comment]
I was gonna just revert it back to having beepsky voice

**Pull request closed without merging**
