### PR TITLE
Stockings

### PR DESCRIPTION
**Pull request by AffectedArc07**
## About The Pull Request
This pull request adds stockings into the game as selectable sock sprites
image
*(Sprites made by @Shazbot194)*

## Why It's Good For The Game
More customisation fluff is always good

## Changelog
:cl: AffectedArc07 and Shazbot
imageadd: Added 9 new sock styles
/:cl:

### CODE REVIEW

**Comment by Swiftkor** [comment]
oh god don’t let the catgirls see this

**Comment by Fikou** [comment]
nya

**Comment by habader** [comment]
no please dont

**Comment by HomocidlePancakes** [comment]
Fuck yo snowflake insta thumbs down

**Comment by bgobandit** [comment]
no fetish content

**Comment by nervere** [comment]
Excellent work.

**Comment by habader** [comment]
hell yeah i wanna play dress up with my cute catgirl ss13 character

**Comment by Akrilla** [comment]
thigh highs on, yeah its gamer time

**Comment by vpellen** [comment]
Would alternating pink/pastel blue stripes be too obvious

**Comment by shazbot194** [comment]
You tell me.

image

**Comment by PKPenguin321** [comment]
😬

**Comment by Shadowflame909** [comment]
Gigapuddi and orange man predicted this in voice chat

**Comment by Militaires** [comment]
image

**Comment by Rowelll** [comment]
finally the last element for my ss13 programming starter pack

**Comment by vpellen** [comment]
> You tell me.
> 
> image

No no, you're meant to keep the white stripes.
Blue, Pink, White, Pink, repeat.
Alternatively, Blue White Pink White repeat.

**Comment by necromanceranne** [comment]
I see this on a catboy and they're going on the fucking table.

**Comment by Tlaltecuhtli** [comment]
fetish content

**Comment by Eaglendia** [comment]
these should make you better at programming

**Comment by habader** [comment]
Make wearing them constantly cause bleeding

**Comment by ExcessiveUseOfCobblestone** [comment]
Anyone who merges this will be cursed with stray cats lingering around your living quarters, be warned.

**Comment by anconfuzedrock** [comment]
Why is there a negative response to this we needed you negative response people when that guy was adding vorestation ported haircuts WHERE WERE YOU

**Comment by AffectedArc07** [comment]
Its actually disappointing how many people dont get the meme here


smh

**Comment by YakumoChen** [comment]
haha nice

**Comment by plapatin** [comment]
if i see anybody wearing these i’m banning them under rule 8

**Comment by 81Denton** [comment]
wearing these programming socks doesn't even increase research point generation, what a waste

**Pull request merged**
