### PR TITLE
Space Ninja Fixes

### LINKED ISSUE #54859: Ninja suit permanent cooldown.
## Round ID: [149848](https://scrubby.melonmesa.com/round/149848)

Possibly related to https://github.com/tgstation/tgstation/pull/53492 @IndieanaJones 
I got hit by a disabler while cloaked, this put my suit on permanent cooldown. I disabled and reenabled the suit, I charged on apcs, I waited a long time, but every time I tried to use a suit ability it just said "suit on cooldown"; it was like 20 minutes I think from first having it disabled till I died.

### PR DESCRIPTION
**Pull request by IndieanaJones**
## About The Pull Request

Fixes #54859

This is a bugfix PR regarding the recent changes to space ninja.  The changes are as follows:
- Fixed a bug where the ninja suit would get a permanent cooldown
- Fixed a bug where Space Ninja could reroll cyborgs he's already hacked
- Made cyborg hacking use a cyborg method instead of typing it out custom.  Said method covers everything better.

## Why It's Good For The Game

Bugs are bad, fixes are good.  Both of these issues are something we don't want

## Changelog
:cl:
fix: Fixed a bug where Space Ninja could go into infinite cooldown
fix: Fixed a bug where Space Ninja could reroll an already hijacked cyborg endlessly
/:cl:

### CODE REVIEW

**Comment by Pumpkinoe** [comment]
speedmerge please

**Comment by adamkad1** [comment]
Agreed

**Comment by necromanceranne** [comment]
It seems as though the suit items don't deactivate when separated from the suit anymore. Which means they can be collected from the ninja exploding and reused.

Also, are the ninja shoes supposed to speed you up? Because they do. If you're not the ninja wearing the suit.

**Comment by adamkad1** [comment]
Syndicate sure does love salvageable tech huh?

**Comment by ATH1909** [comment]
> It seems as though the suit items don't deactivate when separated from the suit anymore. Which means they can be collected from the ninja exploding and reused.
> 
> Also, are the ninja shoes supposed to speed you up? Because they do. If you're not the ninja wearing the suit.

feature(?)

**Comment by IndieanaJones** [comment]
> 
> 
> It seems as though the suit items don't deactivate when separated from the suit anymore. Which means they can be collected from the ninja exploding and reused.
> 
> Also, are the ninja shoes supposed to speed you up? Because they do. If you're not the ninja wearing the suit.

This was always the case.  Ninja code never contained anything to "disable" the items after a death.  However, the only two of worth is the katana and the shoes, and yes, the shoes also always sped you up.

**Pull request merged**
