### PR TITLE
Adds activated hulk mutation

### PR DESCRIPTION
**Pull request by AnturK**
Alternative to hulk removal in #12905

Hulk is now activated and lasts only a short burst of time.
Actual duration values/icons/scaling with health not finished.
This is mostly to gather some feedback.

### CODE REVIEW

**Comment by AnturK** [comment]
Blargh forgot to update master before branching

**Comment by ExcessiveUseOfCobblestone** [comment]
as long as it goes on and off and not just 'you get it then it goes away forever' i'll be alright with it.

**Comment by bgobandit** [comment]
:-1: 

people can and will powergame by turning on hulk, turning it off when they need to use guns or hide or whatever, etc. the downside of hulk is that you CAN'T do certain things and you are very obvious.

**Comment by RemieRichards** [comment]
@bgobandit they can't toggle it off.

**Comment by AnturK** [comment]
That and all stamina accumulated during the hulkout is leftover. So you're probably going to drop for a while after it wears off.

**Comment by bgobandit** [comment]
@RemieRichards you just *know* people will learn to time it exactly

**Comment by ExcessiveUseOfCobblestone** [comment]
pls no stamina damage, it's stupidly powerful to the point where you're basically taking a nap before moving each tile. If you're gonna nerf hulk to the point where it is more of a disability than a power, then please don't nerf it at all.

**Comment by Nanotransistor** [comment]
:+1:  This is the way to do it. Maybe it could also stun the user once hulk wears out.

**Comment by AnturK** [comment]
Actually,forgot i removed the collapse emote, so there's no stamina damage. I need to read what i commit.

**Comment by Durkel** [comment]
Just remove the fucking thing, it's spaghetti code all over the fucking place and is still retarded. Just replace it healing hands so genetics actually has a reason to be near medical.

**Comment by optimumtact** [comment]
@bgobandit are you legitimately arguing against people having skill with using a technique?

**Comment by bgobandit** [comment]
skill no, powergaming to the millisecond that probably will be based on ping yes

**Comment by Iamgoofball** [comment]
:+1: vg has this, hulk is a lot less shit there because of it

i mean i personally want hulk to stay dead but this works too

**Comment by Amemelius** [comment]
Horrible. May as well just remove hulk. It's fine, is locked behind a crapton of genetics work, luck, and already has ample downsides (not being able to use guns).

**Comment by KorPhaeron** [comment]
>crapton of work

It's completely random and can spring up 10 minutes into the round at which point you can infinitely produce it

**Comment by KorPhaeron** [comment]
@Durkel 

At least someone cleaned up a lot of the shitcode by making hulk_act instead of checks in everything, but it's still pretty dumb yeah

**Comment by GunHog** [comment]
Is "Neither PR" an option? It is my opinion that design decisions like things, along with the crackdown on disruptive behavior by non-antagonists that has led to the rise in 'validhunting' by Security and vigilante players. It moves us to a point where the primary interest in any given round is Security + vigilantes against the antagonists, with everyone else being support, fodder, or targets.

It is my belief that this change will contribute to the boredom I seem to have noticed when the Sec vs Antag battle of the round tips too far to one side, takes too long to begin, or does not happen at all.

**Comment by KorPhaeron** [comment]
@GunHog 

Hulk turns you into a yelling retard/close combat monster, how does nerfing something purely used to go on murdersprees or validhunt encourage those things?

How does nerfing something that requires security guns to stop contribute to civillians being fodder?

I'm not sure how you're complaining about vigilantes and "everyone else being fodder" in the same paragraph either.

**Comment by YakumoChen** [comment]
Hulk isn't 'balanced' by any definition and it's far too easy to get with the current Genetics "100% proc chance" powers. This is on top of the half a dozen other useful genetics powers that turn anyone with a full powerset into an upstoppable killing machine. Invis+TK+Hulk+Xray is pure cancer and when everyone has it the station always goes immediately to shit with 30+ vigilante retards running around and straight up destroying the station / any antags who haven't gotten the memo. Turn it around and an antag with a full powerset can just sit in a locker in maint and TK murder other people with flying extinguishers invisibly behind a wall.

Reminder that Hulk grants:
-Stun immunity in a game with a combat system revolving around stuns
-Wallpunch that works on Rwalls
-One-punch stuns that basically mean u ded if you get within melee range of a hulk
-The only downsides is that you're green and you scream a lot, and you can't use guns, but why need guns with you can TK smash people to death as a geneticist while invisible from behind a wall or in a locker??

I want hulk removed but I could at least be a little satisfied knowing that hulks get a stun if I manage to wait it out, as long as the cooldown isn't short enough they can just spam it and get right back up after half a second.

**Comment by neersighted** [comment]
:+1: to this, hulk needs a rework.

**Comment by Dorsisdwarf** [comment]
@AnturK 

Do you intend to finish this project?

**Comment by AnturK** [comment]
Not really.

**Pull request closed without merging**
