### PR TITLE
Internals ASMR

### PR DESCRIPTION
**Pull request by DATA-xPUNGED**
## About The Pull Request

Adds 2 sounds: One for turning on internals and one for turning it off

[breathing showcase.webm](https://github.com/tgstation/tgstation/assets/44149906/2c5811ac-6a1e-4da5-80e4-ced5e9f9e3c8)

PS: The passive breathing has been removed from this PR as Maintainer's request and will be added with an option to turn it off later

sounds made by Beebblie on discord for this PR, couldn't have been done without them.
## Why It's Good For The Game

Sound feedback good.

## Changelog
:cl: DATA, with sounds by Beebblie
sound: Added sounds for turning on and off internals.
/:cl:

### CODE REVIEW

**Comment by Rhials** [comment]
Sounds awesome, and is subtle enough to not be annoying if you have internals on passively. 

Since the looping sound is kept as a datum, maybe you could set up a signal to delete it as soon as internals are closed to stop the breathing effect? I'm not sure if that would really work but it might.

**Comment by DATA-xPUNGED** [comment]
> Sounds awesome, and is subtle enough to not be annoying if you have internals on passively.
> 
> Since the looping sound is kept as a datum, maybe you could set up a signal to delete it as soon as internals are closed to stop the breathing effect? I'm not sure if that would really work but it might.

I don't even need a signal for that, I think I'll add it as part of the `inventory.dm`'s handling of closing internals (Which is what i was doing originally before a kind soul showed me the breathing proc)

**Comment by Sadboysuss** [comment]
I like the sound, SS14 has a really good sound for turning on internals, but this is better.

**Comment by Livrah** [comment]
Please make breathe sound toggleable. 
Contant loop sounds can't be good for the round based game.

**Comment by DATA-xPUNGED** [comment]
> Please make breathe sound toggleable. Contant loop sounds can't be good for the round based game.

Trust me, it is lower than your footsteps and only happens while on internals, I don't think this will be needed

**Comment by chestlet** [comment]
> > Please make breathe sound toggleable. Contant loop sounds can't be good for the round based game.
> 
> Trust me, it is lower than your footsteps and only happens while on internals, I don't think this will be needed

While I agree that the loop seems fairly unintrusive amongst the general soundscape it would still be ideal to have it as an option rather than a mandatory part of the game.

People should be able to toggle it off for reasons ranging from simple 'I don't like it' to 'Misophonia can be triggered by the sound of breathing'

**Comment by Cheshify** [comment]
Please let us toggle this off, it's very hard to explain how this personally makes me very uncomfortable.

**Review by san7890 — CHANGES_REQUESTED** [review]
i very much like the internals opening/closing hiss but breathing loop should be either discarded or optional. it's not how sound works anyways, the effect works in _Outer Wilds_ because the MC in that game wears a domed space helmet. If spessman are getting their air through a breathing mask, they wouldn't have the "fishbowl" reverberation effect anyhow (maybe good for EVA suits?)

i'm not certain on how the implementation of this would work so if you could kindly split this PR out (you can label the other one sound it's fine) so that this one is just the open/shut hiss then I would very much appreciate that.

**Comment by san7890** [comment]
also, fun fact: some of the effects in _Outer Wilds_ (like the spaceman's helmet fogging up) was removed accidentally while devs were making promo photos / trailers for their game - and when they found out it was removed wayy later on, the accessibility team said that it shouldn't be re-added. there's a config file somewhere in the game files where you can uncomment a variable to toggle your face mask fogging up.

it's slightly pertinent here because it's a very cool atmospheric effect that would add to the game, but the removal of it was only confirmed because it affected the "readability" of stuff in _Outer Wilds_- another major component of that game. By having a static looping sound when internals are on, it will drown out the rest of the really nice soundscape we have going on (and players who will have their internals always on wouldn't care about missing out of the soundscape anyways)

**Comment by LemonInTheDark** [comment]
what does this sound like in contrast to say, an airlock opening

**Comment by DATA-xPUNGED** [comment]
> what does this sound like in contrast to say, an airlock opening

The airlock's too loud to be able to hear the breathing while it's opening

**Comment by DATA-xPUNGED** [comment]
> also, fun fact: some of the effects in _Outer Wilds_ (like the spaceman's helmet fogging up) was removed accidentally while devs were making promo photos / trailers for their game - and when they found out it was removed wayy later on, the accessibility team said that it shouldn't be re-added. there's a config file somewhere in the game files where you can uncomment a variable to toggle your face mask fogging up.
> 
> it's slightly pertinent here because it's a very cool atmospheric effect that would add to the game, but the removal of it was only confirmed because it affected the "readability" of stuff in _Outer Wilds_- another major component of that game. By having a static looping sound when internals are on, it will drown out the rest of the really nice soundscape we have going on (and players who will have their internals always on wouldn't care about missing out of the soundscape anyways). i wouldn't mind it if it were more situational but if it follows the player everywhere...

I do have to reiterate how the breathing almost gets mixed in with the white noise that you get while on station, that's how low it is. But I'll be removing it from this PR and somehow trying to make it a toggle later

**Comment by Sadboysuss** [comment]
> I just want to reiterate that this is what, before i removed it, the breathing sounded like while doing other stuff; Maybe i should have done this first.
> 
>  8mb.video-LU1-ED4RJTzr.mp4

I think it's perfect and is only really noticeable in space, which imo is fine

**Comment by DingleFlop** [comment]
Now I'm feeling like it would be awesome to have the respiration rate, the sound queues for respiration, the air consumed on a tile AND the air consumed from an internals tank all tied together...

Then adding things like pain increasing respiration, diseases increasing or decreasing respiration, etc.... to make the sound queue play off the psychology of a situation... Like fighting a traitor, and you hear yourself breathing more rapidly from the tank!!!

**Comment by Dorsisdwarf** [comment]
Given that you can hear physical combat at full volume from through 2 walls offscreen in ss13 i don't know if a barely perceptible sub-ambience huff would affect balance. But it could get annoying so a toggle sounds right.

**Comment by radarseas** [comment]
does the breathing effect happen for races that, don't breath, like skeletons that turn their internals on for whatever reasoning?

**Comment by DingleFlop** [comment]
> Please make breathe sound toggleable. Constant loop sounds can't be good for the round based game.

Ah yes, I think we already do pitching up and down with the majority of effects to prevent sounds becoming to "samey."
I think breathing, being "organic" process would benefit from this sorta thing....

**Comment by DATA-xPUNGED** [comment]
> > Please make breathe sound toggleable. Constant loop sounds can't be good for the round based game.
> 
> Ah yes, I think we already do pitching up and down with the majority of effects to prevent sounds becoming to "samey." I think breathing, being "organic" process would benefit from this sorta thing....

I didn't use pitch up and down because i feel like that would be weird, i added .2 seconds of variance on breathing intervals instead

**Comment by LemonInTheDark** [comment]
I am in theory on board with a breath loop (with potential toggle for uh, whatever accessibility concerns there are)
I plan on testing this out locally because my gut is it is a pretty minimal effect that was overpresented by the initial video. Will see. May be a while before I get around to this so please do not treat this comment as a block on all work

**Comment by DATA-xPUNGED** [comment]
> I am in theory on board with a breath loop (with potential toggle for uh, whatever accessibility concerns there are) I plan on testing this out locally because my gut is it is a pretty minimal effect that was overpresented by the initial video. Will see. May be a while before I get around to this so please do not treat this comment as a block on all work

[This branch](https://github.com/DATA-xPUNGED/DataStation/tree/TheActualbreathing) has the original breathing still implemented if you'd like to try it locally

**Pull request merged**
