### PR TITLE
Moves Tram Station Vault Out Of The Armoury

### PR DESCRIPTION
**Pull request by Thunder12345**
## About The Pull Request

Moves the Tramstation vault from the armoury to a more typical location next to a public hallway. Moves tool storage a little to make space, and rearranges a couple of other related areas.

Vault has been moved to a new location in the service wing next to tool storage
image
image

Tool storage has been rotated, and filled with a bit more junk
image

Cargo's mech has been replaced with the cargo specific one, and moved into the old ORM room
image

BEPIS has been moved into the old mech spot to use the available space better
image

Old vault has been completely purged, and some armoury contents rearranged to fill the gap where the ladder was
image

## Why It's Good For The Game

The current location for Tram's vault is unnecessarily secure from the point of view of hacking in, as the only approach to it is through the armoury. This PR moves it to a more typical location, which can be approached from a public hallway, as well as the previously available method of digging through the rock to access a wall.

This also allows the quartermaster to get into the armoury as is normal on other maps, previously this was impossible without getting the warden to let them walk through the armoury to get to the vault door. As the vault is now accessible this way, the ORM can be moved out of its room in cargo and returned to the vault as is consistent with other maps.

## Changelog

:cl:
expansion: Tram Station's vault has been moved to the service wing, next to tool storage.
/:cl:

### CODE REVIEW

**Comment by MetalClone** [comment]
Very good change, the only way to break in before was strong-arming through security which was often impossible. Or breaking in through space which was much harder and required many more tools such as mesons, mining tools, and EVA

**Comment by Bawhoppen** [comment]
I am mixed on this. On one hand, I did like the unique character the vault placement lended to Tram. Having maps that are different in how they function is good and oughtta be encouraged. On the other hand, I was also not a fan of the specific way that the vault was designed in this case though.

**Comment by newfren** [comment]
toolbelts god bless you there are no fucking toolbelts on this map

**Comment by Zytolg** [comment]
Please include the other changes you made (mech and beepis relocations) in the title and CL.

**Comment by nianjiilical** [comment]
i always thought having the orm not be in the vault was interesting, since it makes it a lot more vulnerable to antags, but everything else sounds like an upgrade

**Comment by ATH1909** [comment]
if you're touching the armory, could you please make the dragnets not be hidden by those blue and red pipe things?

**Comment by MMMiracles** [comment]
this pr only confirms my suspicions that our players have collectively forgotten the existence of pickaxes or the fact the station is covered in rocks that can be dug with said pickaxes for break-ins

**Comment by Thunder12345** [comment]
> 
> 
> this pr only confirms my suspicions that our players have collectively forgotten the existence of pickaxes or the fact the station is covered in rocks that can be dug with said pickaxes for break-ins

A very good point seeing at those pipes don't even serve any purpose any more and I have no idea why I forgot to remove them

**Comment by MMMiracles** [comment]
my comment was me voicing my dislike of this change btw

**Comment by EuSouAFazer** [comment]
Tram's vault is the least secure in the entire game. 
From the main near perma you can take down a non-reinforced wall, mine into the vault and boom you're there. And no: You don't need internals or a space suit; the tram rocks give air when mines. And there are not only but 2 pickaxes down the hallway from perma maint they're really easy to get.

But damn I'll be lying of I said that I didn't like the new vault. Multi-Z is always based and honestly I like multi-Z vault better than current Tram's vault tbf

**Comment by LemonInTheDark** [comment]
> 
> 
> toolbelts god bless you there are no fucking toolbelts on this map

:sadkirby: the wheel turns

**Review by EOBGames — CHANGES_REQUESTED** [review]
Alright, there's a few issues needing resolved.

You've got an orphaned area here in Primary Tool Storage:
image

Same in the vault here:
image

Not sure what's going on with this air alarm, but it really doesn't look right to me:
image

The mech charger is gone from here, looks like something you missed while fixing a conflict:
image

I think that's about everything I can see for now- resolve those and give me a shout.

**Comment by EOBGames** [comment]
Yeah, this all looks fine. Sorry about the delays in reviewing again, and for you having to fix all those conflicts.

**Comment by LemonInTheDark** [comment]
😢

**Pull request merged**
