### PR TITLE
Bug removal from the codebase

### PR DESCRIPTION
**Pull request by BeeSting12**
:cl: BeeSting12
fix: Moths have been removed.
/:cl:
Why: This codebase has reached the issue count of 1000 recently. We need to get rid of the bugs causing this so I am removing a bug.

### CODE REVIEW

**Comment by evsey9** [comment]
testmerge needed

**Comment by ma44** [comment]
>Doesn't fix any issues

It should probably close all of them tbh

**Comment by DaedalusGame** [comment]
Couldn't we just deadmin beesting for a similar effect as this pr has

**Comment by BeeSting12** [comment]
Bugs in the administration are fine we allow slimes and emus right?

**Comment by DaedalusGame** [comment]
Are you smoking roaches neither slimes nor emus are arthropods

**Comment by DaxDupont** [comment]
https://github.com/tgstation/tgstation/blob/master/.github/CONTRIBUTING.md

> Code adding, removing, or updating the availability of alien races/species/human mutants without prior approval. Pull requests attempting to add or remove features from said races/species/mutants require prior approval as well.

**Comment by DaxDupont** [comment]
fuck sniped

**Comment by DaedalusGame** [comment]
gitbannu post haste

**Comment by BeeSting12** [comment]
wtf i was removing bugs? mods???

**Comment by vuonojenmustaturska** [comment]
Next time you attempt this joke, please use the revert functionality to save yourself an hour of your time

**Comment by BeeSting12** [comment]
it didnt work

**Comment by Xhuis** [comment]
itt beesting acts like a preschooler

**Comment by BeeSting12** [comment]
itt ur gay lol

**Comment by Tlaltecuhtli** [comment]
where is the 24h rule + 1 year of test merge?

**Comment by Cyberboss** [comment]
This is banned content go away

**Pull request closed without merging**
