### PR TITLE
Adds kill streaks

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
Only humans/lizards etc count for kill streaks.

As an alternate PR to #14058

Closes #14058

### CODE REVIEW

**Comment by hornygranny** [comment]
exquisite

**Comment by Cheridan** [comment]
>doesn't even have sound files

it's shit

at least record some using a mic

**Comment by KorPhaeron** [comment]
@Cuboos

**Comment by duncathan** [comment]
I would love to provide shitty voice over
I'll record after my flight home

**Comment by Cheridan** [comment]
Tactical nuke incoming.

**Comment by KorPhaeron** [comment]
It's too late, it's already on the server

**Comment by ike709** [comment]
>not having killionaire

**Comment by KorPhaeron** [comment]
@duncathan

Need those killstreaks still

**Comment by Kromgar** [comment]
I think you need to add fly persons, and plant persons now

**Comment by PKPenguin321** [comment]
finish this kor

**Pull request closed without merging**
