### PR TITLE
Adds holsters and storage vests

### PR DESCRIPTION
**Pull request by Core0verload**
This PR ports holsters and storage vests from Bay.
webbingwestbrwestbl
These items are attached to jumpsuits using current ties system. They add extra pockets to jumpsuits when attached.

Webbing stores 2 `w_class 2` items.
Storage vest stores 4 `w_class 2` items.
Holster stores 1 `w_class 3` gun. Supports alt-click quickdraw.

This PR also adds support for ties having armor rates. Armor is added to jumpsuit when the tie is attached and removed when the tie is removed.

Adminspawn/mapspawn only for now.

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
Having armor on a tie is pointless; armor checks aren't done on those.

Also this is yet again *more* storage creep.

**Comment by Ergovisavi** [comment]
You're adding "webbing" when webbing already exists as a belt slot item, which will cause player confusion.... think it even shares the same icon. And do we really need even more storage on players? I think not.

:-1:

**Comment by TechnoAlchemisto** [comment]
I think it's cool just to have it available for future things.

**Comment by Core0verload** [comment]
Storage creep? Those items are intended to be placed on space/lavaland ruins as low level rewards. It's not like I add them to every locker.

>Having armor on a tie is pointless; armor checks aren't done on those.

This PR also adds support for ties having armor.

**Comment by TechnoAlchemisto** [comment]
I added an accessory a bit ago with armor values so this would actually make it work :+1:

**Comment by optimumtact** [comment]
We're not accepting new storage increases at this time.

**Pull request closed without merging**
