### PR TITLE
A bunch of tweaks to holsters.

### PR DESCRIPTION
**Pull request by uomo91**
## About The Pull Request

This PR changes some things about what weapons and ammo the various holsters can hold.

### **Regular holsters:**
Can no longer hold pulse carbines.
Can now hold toy pistols.

### **Detective's holster:**
Can no longer carry ALL ammo box types, it's crazy this was possible.
Can now carry all handguns instead of only revolvers, their ammo, the mini e-gun, and the toy pistol and its magazines.

### **Chameleon holster:**
Can no longer hold pulse carbines.
Can now hold all the ammo of guns it can hold (handguns and revolvers), the toy pistol and its magazine, **and the small energy crossbow.**

### **Operative holster:**
Can now hold... basically everything gun related. **All** guns, **all** ammo (except ammo boxes), all grenades.

Descriptions of all holsters changed to reflect this.

## Why It's Good For The Game

Mostly makes sense and seems like an oversight, the only balance concern I could see here would be enabling the energy crossbow to be hidden in the chameleon holster. Also, there may be some missing gun types that the operative holster should be able to hold.
Please let me know if there are any other oversights.

## Changelog
:cl:
tweak: Holsters should now hold appropriate weapons and their ammo types.
/:cl:

### CODE REVIEW

**Comment by LemonInTheDark** [comment]
christ

**Comment by uomo91** [comment]
> christ

...blesses this PR? ✝️

**Comment by Tlaltecuhtli** [comment]
why not all  mags subtypes?

**Comment by uomo91** [comment]
> why not all mags subtypes?

For the operative holster, I could do that, though it still wouldn't cover everything.

For the other holsters, it made no sense for me to have them able to carry ammo for a gun they can't hold.

**Comment by uomo91** [comment]
Here, I think this makes it a lot simpler and nicer to look at.

**Review by Rohesie — APPROVED** [review]

**Pull request merged**
