### PR TITLE
Fixes old simple animal humanoid issues

### LINKED ISSUE #4360: Humanoid hostile mob corpse
When the simple mobs die, they turn into 'corpse' mobs for looting, which is a problem because currently mobs have randomized skin color and underwear/hair. Thus, syndicate/pirate/etc humanoid mobs have basic 4 way directional bald sprites, where when they die they magically grow pink hair and shit.

Additionally, syndicate simple mobs have some broken sprites and need to be 'remade'.
- They have old armor sprites.
- They wear security backpacks instead of normal backpacks. The corpses of the mobs have normal backpacks.

### PR DESCRIPTION
**Pull request by Bawhoppen**
Fixes #4360

This fixes simple animal humanoids growing hair out of nowhere and changing their skin_tone when they die.
I added some additional clothing to help cover stuff to help solve the issue aswell.

I also painstakingly completely remade all the sprites for humanoid simple mobs from the ground up, in order to reflect clothing sprite changes over the years, and the issue mentioned in that issue report.

I am aware this is a very in-elegant way to fix the issue, but it works.

### CODE REVIEW

**Comment by Bawhoppen** [comment]
3rd oldest issue hurray

**Comment by Bawhoppen** [comment]
>Maps cause conflicts

You gotta be kidding me

**Comment by praisenarsie** [comment]
🚶

**Comment by WJohn** [comment]
Neat.

**Pull request merged**
