### PR TITLE
Major resprite for the device.dmi folder ( Now with exploration.dmi fixes! )

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request

Adds animations and resprites many outdated or unanimated sprites in the device.dmi folder. 
In total resprites, animates, or reshades the Mining Scanner On, Emp Nade, Emp Nade Activated, Syndie Pinpointer, Camera Bug, Syndicate Autoimplanter, CMO Autoimplanter, Swapper-Linked, Radio Jammer, Scanner, and T-ray1.

## Why It's Good For The Game

While some of the changes are a bit negligible ( swapper-linked, emp nade, mining scanner ) it adds animation to alot more of these devices and reshades them to current standards. It also resprites particularly egregious sprites like the radio jammer into a flip-phone instead of being a cargo scanner with a nipple on it and the scanner into not a big grey brick that has a stick figure on it. Furthermore the EMP nades seem to draw from a different sprite I can't find.

## Changelog

:cl:
imageadd: Overhauls the mining scanner active, emp nade, emp nade active, syndicate pinpointer, camera bug, syndicate autoimplanter, autoimplanter, swapper-linked, radio jammer, scanner, and t-ray1 sprites all found in the Devices.dmi folder. Also resprites the satellites found in exploration.dmi 
/:cl:

### CODE REVIEW

**Comment by tommysalami3** [comment]
https://user-images.githubusercontent.com/77305289/114327023-606f9800-9b05-11eb-8307-ff1009cad271.mp4

Pictured left to right: Camera bug, desynchronizer, radio jammer, mining scanner, syndicate autodoc, syndicate pinpointer, swapper-linked, t-ray 1, and CMO autodoc.

**Comment by GuillaumePrata** [comment]
T-ray scanner looks broken, the top half of it goes invisible.
Crew monitor changed... my soul...

**Comment by tommysalami3** [comment]
> T-ray scanner looks broken, the top half of it goes invisible.
> Crew monitor changed... my soul...

top half antennae lift up and do a lil spin now, might just be you arent used to seeing it

**Comment by tommysalami3** [comment]
https://user-images.githubusercontent.com/77305289/114327596-b2b1b880-9b07-11eb-8dbf-c261a05a3198.mp4

forgot to add the scanner for the gif

**Comment by MrDoomBringer** [comment]
>Pictured left to right: Camera bug, desynchronizer, radio jammer, mining scanner, syndicate autodoc, syndicate pinpointer, swapper-linked, t-ray 1, and CMO autodoc.

>shows sprites ingame

>uses stretch scaling instead of pixel perfect

what is wrong with you!!

**Comment by tommysalami3** [comment]
> > Pictured left to right: Camera bug, desynchronizer, radio jammer, mining scanner, syndicate autodoc, syndicate pinpointer, swapper-linked, t-ray 1, and CMO autodoc.
> 
> > shows sprites ingame
> 
> > uses stretch scaling instead of pixel perfect
> 
> what is wrong with you!!

born to sprite
forced to pr

**Comment by Fikou** [comment]
the desynchronizer feels a bit weird
emp and crew monitor look like downgrades
the autoimplanter shouldnt look the same between nanotrasen and syndicate and im not sure why you added a button and removed the shears or whatever

**Comment by tommysalami3** [comment]
This push fixes problems described above. It also adds the EMP nades to the correct folder and adds sprites to the exploration sateillites only because i was browsing through icons, saw how horrific they looked, and decided that it needed to be fixed ASAP. They aren't even particularly good sprites, the old ones were just so jarringly bad that they needed to be changed right now. Im talking like reverse bear trap levels of spriting here.

**Review by Twaticus — CHANGES_REQUESTED** [review]
your animations are really nice but theres a few resprites im not a fan of

the emp is fine, but the empar loses all its flair. it should have the same bright flashing blue as the old version.
i dont like the new scanner at all sorry that should be reverted.
desynchronizer & desynchronizer-on has a nice shape and animation to it, but the greys are pretty muddied. needs more definition with the highlights and shade

**Comment by tommysalami3** [comment]
> your animations are really nice but theres a few resprites im not a fan of
> 
> the emp is fine, but the empar loses all its flair. it should have the same bright flashing blue as the old version.
> i dont like the new scanner at all sorry that should be reverted.
> desynchronizer & desynchronizer-on has a nice shape and animation to it, but the greys are pretty muddied. needs more definition with the highlights and shade

Haha, literally all of what was mentioned is the stuff i have the least faith in. I'll check it out again when I have the chance.

**Comment by tommysalami3** [comment]
New push that should address feedback here. Reverts changes for the new scanner, further reworks desynchronizer shading, and empar has a visible low transparency pulse similar to the original now. Since this is the second time ive had to rework these resprites, if there are further problems with them i'll likely scrap the changes and put them into a different PR where i can put more focus on them.

**Review by Twaticus — APPROVED** [review]
👍

**Comment by LemonInTheDark** [comment]
if you need help with the merge conflicts feel free to ask in coderbus yeah?

**Comment by tommysalami3** [comment]
i tried to fix the merge conflicts and did some fucky shit and now its not pushing and god dammit i just want to sprite you son of a bitch
image
if i cant fix it today i'll have to close this and reopen the PR. if i had a nickel for every time ive had to close this PR and reopen it due to errors that dont have to deal with spriting, I would have two nickels, which isn't alot but its frustrating its happened twice.

**Comment by maxymax13** [comment]
these kinda suck

**Comment by psykzz** [comment]
You seem to have a white pixel top left on the first frame of `scanner_on`
68747470733a2f2f6964622e616666656374656461726330372e636f2e756b2f46696c65732f333233343938372f323430303939313430352f332f61667465722e676966

**Comment by MrDoomBringer** [comment]
@psykzz This is a common bug, that white pixel only appears in IconDiffBot, not on the actual sprite. You can check the actual DMI file to confirm
image

**Comment by manofpepsi** [comment]
the ore scanner and the tray scanner are pretty good, while everything else, especially the emp nade is a downgrade...

**Pull request closed without merging**
