### PR TITLE
Laser Musket & Smoothbore Disabler BUFFS (Crank it AND Run)

### PR DESCRIPTION
**Pull request by Cheshify**
## About The Pull Request
This rebalances the Laser Musket and Heroic Laser Musket

Replaces glasses with 2 drinking glasses in the crafting recipe
Removes 2-handed demand
Standard shot damage slightly increased and stamina damage greatly decreased
Heroic shot made a 3-round scatter shot, very powerful, damage and stamina damage decreased to compensate
Crank-charge weapons, except the thermal revolvers, can be charged while moving
Muskets can also be worn on jackets

## Why It's Good For The Game

These things were severely underused, and I always kinda wanted them to be crankable while you moved, I just didn't know how. This should also help the Militiamen ERT be less of a joke. I would appreciate balanceposters giving some advice on the numbers if you're seeing this.

The heroic musket is incredibly rare, and SHOULD be pretty powerful.
## Changelog
:cl:
balance: laser muskets have been rebalanced
balance: crank weapons can be charged while moving
/:cl:

### CODE REVIEW

**Comment by Loafin34** [comment]
Why remove the drinking glass? It requires a concave laser to focus it into the glasses.

**Comment by Cheshify** [comment]
Because man it's hard enough to make the damn thing. I can add it back if it's upsetting.

**Comment by carlarctg** [comment]
readd it and remove the glasses

drinks can be lathed but glasses cant

or remove both and replace with 2 glass

**Comment by JupiterJaeden** [comment]
If this affects thermal pistols, it makes them too strong. The laser musket has a fairly long crank and low rate of fire so it’s whatever, but thermal pistols crank very fast and fire very fast. Allowing you to do it while moving gives you basically infinite ammo during a fight. Please don’t “fix” this by making pistols have an annoyingly long crank, just snowflake it to laser muskets.

**Comment by Loafin34** [comment]
it's on the crank trait so it would affect thermal revolvers.

**Comment by Cheshify** [comment]
Going to try to fix the thermal revolver issues

**Comment by CCC23** [comment]
finally I can use the musket as a actual weapon for protracted fights instead of just hit and run

**Comment by MoonDeer728** [comment]
> Why remove the drinking glass? It requires a concave laser to focus it into the glasses.

its just craft item, it doing bothing

**Comment by Cheshify** [comment]
> > Why remove the drinking glass? It requires a concave laser to focus it into the glasses.
> 
> its just craft item, it doing bothing

yeah but flavour

**Comment by necromanceranne** [comment]
> Please don’t “fix” this by making pistols have an annoyingly long crank, just snowflake it to laser muskets.

Definitely wouldn't support any changes to thermal crank times atm, but I expect chesh has it down pat. It wouldn't be too hard to make it so that the crank can be done while walking or has to force you to be standing. I'd prefer thermals force you to a stop.

Also, as I said to chesh, they beat me to actually doing something with laser muskets myself! I might still do some stuff but I'll put it even further on the backburner just to see how things go with this change.

**Comment by Dawnseer** [comment]
Finally! Now if only the musket fit on the suit slot for a bit more clothes...

**Comment by Cheshify** [comment]
> Finally! Now if only the musket fit on the suit slot for a bit more clothes...

It should fit on all armor vests, like any other laser gun

**Comment by DrAmazing343** [comment]
Make the trenchcoat from the clothing vendor hold it so my oh see can say heh... you're not gonna expect THIS... while I whip out my trusty laser musket and blow a golf ball sized hole in the bulkhead beside my opponent

**Comment by Dawnseer** [comment]
> What if it
> 
> fit on the same outfits as pipeguns? :3c

That'd be terrific

**Comment by Cheshify** [comment]
aight it can be worn on jackets

**Comment by necromanceranne** [comment]
> > What if it
> > fit on the same outfits as pipeguns? :3c
> 
> Pipeguns fit on extra armor sets?

They fit on a lot of thematically appropriate clothing for assistants/tiders. Jackets, trenchcoats, bomber jackets and stuff like that.

**Comment by Dawnseer** [comment]
> aight it can be worn on jackets

You have my eternal gratitude and a 5% off coupon on cargo services, good for one use.

**Pull request merged**
