### PR TITLE
Halves xenomorph neurotoxin spit's stun time

### PR DESCRIPTION
**Pull request by Ekaterina-von-Russland**
## About The Pull Request

Reduces the xenomorph's neurotoxin spit's stun timer from 10 seconds to 5 seconds.

## Why It's Good For The Game

A nearly unlimited instant ranged stun which takes no preparation and lasts for 10 seconds, which is enough for a xenomorph to take someone from full health to crit, is overpowered and gives the player no chance to fight back, making for an uninteresting steamroll instead of an engaging battle.

In addition, xenomorphs already have a powerful instant ranged stun, the facehugger. The facehugger, however, is more balanced because it has drawbacks: reasonable precaution can be taken when you learn there are xenomorphs and it requires the xenomorphs to actually grow and carry the facehugger in preparation. Neurotoxin, by contrast, is too powerful for how cheap it is.

:cl:
balance: reduces neurotoxin spit's stun from 10 to 5 seconds
/:cl:

### CODE REVIEW

**Comment by Livrah** [comment]
Speed queen up by half too

**Comment by Mothblocks** [comment]
I wasn't interested in anything like this last time, I think the stun is important for how xenomorphs feel to play against. I would rather a larger rework that tries to figure out other ways to keep that vibe, but on its own I think it's completely fine that a xenomorph is outlierishly threatening, and that the best way to deal with one without specialized gear is to GTFO. 

https://github.com/tgstation/tgstation/pull/68243#pullrequestreview-1031167448

**Comment by Ekaterina-von-Russland** [comment]
One hit kills don't inspire fear, but rather annoyance.
This change would keep xenomorphs strong, as they could still deal severe damage with a 5 second stun, but not to the point where the enemy player has no chance, which is no fun.

**Comment by Mothblocks** [comment]
I don't think a single person alone without equipment should have any chance against a xenomorph. That makes the xenomorph feel insanely weaker in comparison.

**Comment by Ekaterina-von-Russland** [comment]
You're thinking about a xeno's ability to easily dispatch a crew member with no equipment, which makes total sense.
I'm thinking about a xeno's ability to take down a fully equipped security officer in riot gear with a single ability, which makes no sense.

**Comment by Mothblocks** [comment]
It makes sense to me that a lone officer is completely overpowered by a xenomorph, I want them to go in as teams

**Comment by moocowswag** [comment]
Isnt the spit blocked by proper head protection (bio hood)

**Pull request closed without merging**
