### PR TITLE
Add: Deaf Personnel Pin

### PR DESCRIPTION
**Pull request by Floofies**
## About The Pull Request
This PR contains a single small addition: The deaf personnel pin/accessory for users of the Deaf quirk. I changed the quirk type to `item_quirk` in order to easily grant the pin to the user. Upon spawning, the quirk will put a deaf personnel pin in their backpack or hands, allowing them to pin it to their uniform as they please.

## Why It's Good For The Game
Users of the Blind quirk get the Blind Personnel blindfold upon spawning, however there is no such indicator for users of the Deaf quirk, and they may find themselves in some awkward social situations. This PR gives deaf crew an easily identifiable pin with a design based on a the international symbol for deafness which I have slightly tweaked for extra visibility.

imageimage
image
image

## Changelog

:cl: A.C.M.O.
add: Added the Deaf Personnel pin for users of the Deaf quirk.
/:cl:

### CODE REVIEW

**Comment by Mothblocks** [comment]
arent the awkward social situations the point

**Comment by ArcaneDefence** [comment]
Could put earmuffs on them instead of their normal headset if you want to be in line with what the blindfold does.

**Comment by improvedname** [comment]
tbh deaf is kinda boring as a quirk i'd personally give them a hearing device and only let them hear people in 3-4 tiles if they lose their device their fucked any anny ear damaging sounds take thrice aslong to solve

**Comment by Wallemations** [comment]
> > Could put earmuffs on them instead of their normal headset if you want to be in line with what the blindfold does.
> 
> 
> 
> When I played a deaf character I still kept my headset on, because you can hear people over the radio that use sign language. It was a pretty neat interaction. 

An unintended one but damn that does sound neat, I didn't know that worked that way.

**Pull request merged**
