### PR TITLE
Adding a GaGs recolourable santa hat.

### PR DESCRIPTION
**Pull request by xXPawnStarrXx**
## About The Pull Request
I saw the current santa hat and thought, this doesn't carry the right level of... energy for me. Too festive. So I added a version that can be recoloured. I added them as a new variant to not touch anything that uses them such as Santa.
image

image
## Why It's Good For The Game
Aesthetics and personal customisation good? Merry Chrimbo?
## Changelog
:cl:
add: Added new GaGs santahats.
/:cl:

### CODE REVIEW

**Comment by xXPawnStarrXx** [comment]
I don't know if this requires seperate tags or what. I just wanted to try get this up before Christmas, let me know if you want me to quickly add it to the vendors list too.

**Review by Wallemations — CHANGES_REQUESTED** [review]
The brim's shading is barely contrasting I hardly even noticed it when I first gave this a look
Please raise that contrast

**Comment by xXPawnStarrXx** [comment]
> The brim's shading is barely contrasting I hardly even noticed it when I first gave this a look Please raise that contrast

The white trim on the bottom? Sure.

**Comment by xXPawnStarrXx** [comment]
> The brim's shading is barely contrasting I hardly even noticed it when I first gave this a look Please raise that contrast

image
Better?

**Comment by xXPawnStarrXx** [comment]
Okay, I put the file in the wrong place. I resolved that now.

**Review by Wallemations — APPROVED** [review]
The whole thing could be shaded better but given the fact Christmas is so close I don't want to make you work on this for longer, let people have their hat in time for the holidays yknow?

**Comment by xXPawnStarrXx** [comment]
> The whole thing could be shaded better but given the fact Christmas is so close I don't want to make you work on this for longer, let people have their hat in time for the holidays yknow?

Yep. I can always do a noGBP clean up if you want me to!

**Pull request merged**
