### PR TITLE
fixes brain traumas not being cured by nanites sometimes

### LINKED ISSUE #43266: Brain Damage Healing Nanite Programs Only Cure Traumas If You Have Brain Damage
The neural reimaging and neural regeneration nanite programs heal brain damage and cure brain traumas. They're "smart" programs too, so they'll only activate/consume nanites if their host has brain damage. Unfortunately, they only check for brain damage, not brain traumas, so if you have brain traumas but no brain damage, they won't heal your brain traumas.

Thus, one of the best ways to "cure" hypno-flashed people is to give them neural reimaging nanites, then feed them some mercury. This will cause them to take some brain damage, which will in turn cause their neural reimaging nanites to kick in and cure their brain trauma(s).

Suggested Fix: Make the if statement(s) in the check_conditions() functions of the neural reimaging and neural regeneration nanite programs check for the presence of brain traumas that those programs can cure as well.

### PR DESCRIPTION
**Pull request by tralezab**
fixes #43266

### CODE REVIEW

**Comment by optimumtact** [comment]
question, why should this be buffed?

**Comment by tralezab** [comment]
Do you want me to remove the trauma cure  instead? I just saw the issue and thought the fix was easy enough to crunch out

**Comment by necromanceranne** [comment]
The viro version removes all traumas regardless of brain damage. Why shouldn't the nanites do what they are supposed to do, which is exactly the same thing?

Is it really a buff if it wasn't working as intended in the first place?

**Comment by Repukan** [comment]
Seems kinda dumb to add something that's supposed to only be curable through surgery and then add work arounds to said surgery

**Comment by necromanceranne** [comment]
Counterpoint: traumas are such a shit mechanic requiring contrived methods of removal that are sometimes equally punishing despite usually being completely out of their hands, and that some gamers refuse to accept the 'cures' on the grounds of playing this game like a solo valid simulator.

In addition, this is an obscure method of curing traumas while also being unaccepted for the same reasons as above and the same reason they cure even helpful viro viruses. Gamers won't take nanites for fear of boomies and because they play like apes.

**Comment by Tlaltecuhtli** [comment]
nanites r magic

**Comment by tralezab** [comment]
the satisfaction is from closing the issue, not getting something merged. I don't really care if it goes either way but if it's intentional than make sure to close the issue

**Comment by ExcessiveUseOfCobblestone** [comment]
I think surgery and nanites are fairly synonymous in terms of balance. Both their selling points are putting trust in someone else, and actually nanites does this particular aspect better than surgery (you can't get up and walk out of the nanite chamber midway).

I don't have an issue with this feature-wise, not even considering the obvious "it was merged with the intention to be working already and OP is just fixing a bug".

**Pull request merged**
