### PR TITLE
replaces mech madness with a cooler map (from fulp); Final Destination (+ sorts map list)

### PR DESCRIPTION
**Pull request by mc-oofert**
## About The Pull Request
https://github.com/fulpstation/fulpstation/pull/1164

313430212-bea5509e-7d63-424b-a923-87fe60704f3c
313896894-79329d9f-5756-4fba-9414-63b956a8fd0e-1

mech madness is removed
map list is sorted alphabetically
indestructible light tiles emit light
## Why It's Good For The Game

final destination is a far better map than Mech Madness (boring exosuit gameplay)
mech madness was just cluttering up the dropdown as anyone who ever picked it would never play it again

also i guess alphabetically sorting maps looks better??? (qol????)

light tiles should be emitting light because logic

## Changelog
:cl:
add: Final Destination, deathmatch map
del: Mech Madness, deathmatch map
qol: deathmatch map list is sorted alphabetically
fix: indestructible light tiles emit light
/:cl:

### CODE REVIEW

**Comment by sylvia-from-fulp-station** [comment]
i am sylvia from fulpstation and i approve of this pr

**Comment by DATA-xPUNGED** [comment]
Literally why remove mech madness with this? Just because you personally didn't like it?

**Comment by mc-oofert** [comment]
> Literally why remove mech madness with this? Just because you personally didn't like it?

firstly i am the reason why the map is on tg
secondly its ass

**Comment by DrDiasyl** [comment]
> > Literally why remove mech madness with this? Just because you personally didn't like it?
> 
> firstly i am the reason why the map is on tg so thats my mistake secondly its ass

Why is it ass? Like reasoning beside "its ass" and "boring exosuits"

**Comment by jughu** [comment]
Mech madness lets you interact with a unique feature thats around mech combat.

Maint mania is just assistants with objects beating eachother.
brig is just assistants beating eachother up in the brig.
securing is just officers shooting disablers at eachother till they go down and knife them

Raging mage is also a good example of a map that lets you interact with uncommon mechanic like

**Comment by mc-oofert** [comment]
> Mech madness lets you interact with a unique feature thats around mech combat.
> 
> Maint mania is just assistants with objects beating eachother. brig is just assistants beating eachother up in the brig. securing is just officers shooting disablers at eachother till they go down and knife them
> 
> Raging mage is also a good example of a map that lets you interact with uncommon mechanic like

unarmed or armed combat is miles more interesting than a static object with a set amount of health before it drops dead

**Comment by Admiral-Gigaton** [comment]
RIP mech madness, the masses actually loved it

(You barely have reasoning to remove it, jimmy, come on man)

Welcome, super smash bros!

**Comment by mc-oofert** [comment]
> (You barely have reasoning to remove it, jimmy, come on man)

if I actually played the map when I PRed deathmatch i can guarantee this map wouldn't make it in

**Comment by Admiral-Gigaton** [comment]
> if I actually played the map when I PRed deathmatch i can guarantee mech madness wouldn't make it in

You could always just rework the map (select a loadout and their respective mech?) Or just... not remove it

People enjoy it, there isn't much point to removing it, it's not a matter of balance or anything, it just sounds like you, yourself, don't like the map you made, and want it gone for no other reason beyond that

**Comment by DATA-xPUNGED** [comment]
> > Mech madness lets you interact with a unique feature thats around mech combat.
> > Maint mania is just assistants with objects beating eachother. brig is just assistants beating eachother up in the brig. securing is just officers shooting disablers at eachother till they go down and knife them
> > Raging mage is also a good example of a map that lets you interact with uncommon mechanic like
> 
> unarmed or armed combat is miles more interesting than a static object with a set amount of health before it drops dead

Bro doesn't move in his mech

**Comment by deathrobotpunch** [comment]
I agree, why remove mech madness? just add the cool map with it

**Comment by mc-oofert** [comment]
> > unarmed or armed combat is miles more interesting than a static object with a set amount of health before it drops dead
> 
> Bro doesn't move in his mech

static as in mechs dont have stamina nor can you shove or launch them under most circumstances nor is mech vs mech melee an option nor do mechs get any interesting wounds and theres like 3 optimal guns with the rest being bad

**Comment by Loafin34** [comment]
mechs suck ASS! give some extra mechs around the map or do final destination i really hate it!

**Comment by Toastgoats** [comment]
Just add the ability to spawn different mechs

**Comment by mc-oofert** [comment]
> Just add the ability to spawn different mechs

then everyone rolls the best mech possible

**Comment by Xackii** [comment]
Just an open platform with no cover and everyone has guns that kill in 3 shots? Why is this better than mech madness?

**Comment by mc-oofert** [comment]
> Just an open platform with no cover and everyone has guns that kill in 3 shots? Why is this better than mech madness?

maybe you shouldnt be standing still

**Comment by Xackii** [comment]
> > Just an open platform with no cover and everyone has guns that kill in 3 shots? Why is this better than mech madness?
> 
> maybe you shouldnt be standing still

it’s similar to insta gib where everything is decided by random shots, but even there there are walls through which you can ricochet (although despite this, insta gib is still not very popular). This map is similar to the one that will be played 1-2 times and then go on to play ragin mages. Despite this, more maps are cool, but then the question arises: why remove mech madness?

**Comment by Sakamoto4ka** [comment]
Never used mech in mech madness

**Comment by sylvia-from-fulp-station** [comment]
> > > Just an open platform with no cover and everyone has guns that kill in 3 shots? Why is this better than mech madness?
> > 
> > 
> > maybe you shouldnt be standing still
> 
> it’s similar to insta gib where everything is decided by random shots, but even there there are walls through which you can ricochet (although despite this, insta gib is still not very popular). This map is similar to the one that will be played 1-2 times and then go on to play ragin mages. Despite this, more maps are cool, but then the question arises: why remove mech madness?

its nothing like instagib it's a class based deathmatch with no cover and focus on emulating stuff you'd see in the game. You are not meant to run around looking for loot boxes / hiding just spawn with some OP gamer gear and fight. If you think it's decided by random shots anymore so than the actual game you obviously have not played the map and are just yapping

**Comment by Xackii** [comment]
> > > > Just an open platform with no cover and everyone has guns that kill in 3 shots? Why is this better than mech madness?
> > > 
> > > 
> > > maybe you shouldnt be standing still
> > 
> > 
> > it’s similar to insta gib where everything is decided by random shots, but even there there are walls through which you can ricochet (although despite this, insta gib is still not very popular). This map is similar to the one that will be played 1-2 times and then go on to play ragin mages. Despite this, more maps are cool, but then the question arises: why remove mech madness?
> 
> its nothing like instagib it's a class based deathmatch with no cover and focus on emulating stuff you'd see in the game. You are not meant to run around looking for loot boxes / hiding just spawn with some OP gamer gear and fight. If you think it's decided by random shots anymore so than the actual game you obviously have not played the map and are just yapping

The map is more like the one that will be of interest to beginners who want to learn how to press the shot button or see what kind of tricky items in battle (to understand that the meat hook is broken once again). Loot boxes are shit and I don’t understand why they are added to deathmatch, but I’m just talking about some boxes or other structures that can be carried to protect yourself from bullets and don’t hope that lags and block chances of the shield will help you. I didn’t play on the map because it wasn’t added, but I see just a platform with no shelters and 4 holes with chasms, so I don’t know what to comment on here. I have nothing against the map, I just don’t know why the mech madness should be removed. Mech madness looks better.

**Comment by mc-oofert** [comment]
> The map is more like the one that will be of interest to beginners who want to learn how to press the shot button or see what kind of tricky items in battle (to understand that the meat hook is broken once again). Loot boxes are shit and I don’t understand why they are added to deathmatch, but I’m just talking about some boxes or other structures that can be carried to protect yourself from bullets and don’t hope that lags and block chances of the shield will help you. I didn’t play on the map because it wasn’t added, but I see just a platform with no shelters and 4 holes with chasms, so I don’t know what to comment on here. I have nothing against the map, I just don’t know why the mech madness should be removed. Mech madness looks better.

idk what you guys want im not backing the fuck out of this once its not a democracy and its up to the maints

**Comment by Xackii** [comment]
> > The map is more like the one that will be of interest to beginners who want to learn how to press the shot button or see what kind of tricky items in battle (to understand that the meat hook is broken once again). Loot boxes are shit and I don’t understand why they are added to deathmatch, but I’m just talking about some boxes or other structures that can be carried to protect yourself from bullets and don’t hope that lags and block chances of the shield will help you. I didn’t play on the map because it wasn’t added, but I see just a platform with no shelters and 4 holes with chasms, so I don’t know what to comment on here. I have nothing against the map, I just don’t know why the mech madness should be removed. Mech madness looks better.
> 
> idk what you guys want im not backing the fuck out of this its not a democracy and its up to the maints


I want you to leave mech madness. 
I don't see any reason to remove it

**Comment by DrDiasyl** [comment]
Still needs more justification for removing mech madness. 

"It sucks" is not very clear.

**Comment by sylvia-from-fulp-station** [comment]
image
you can see in the checks what the map actually looks like


> > > > I didn’t play on the map because it wasn’t added, but I see just a platform with no shelters and 4 holes with chasms,

**Comment by Xackii** [comment]
> image you can see in the checks what the map actually looks like
> 
> > > > > I didn’t play on the map because it wasn’t added, but I see just a platform with no shelters and 4 holes with chasms,

cool

**Comment by Admiral-Gigaton** [comment]
> image you can see in the checks what the map actually looks like
> 
> > > > > I didn’t play on the map because it wasn’t added, but I see just a platform with no shelters and 4 holes with chasms,

ok wont lie that map could definetly use some cover, considering almost every opponent has guns. very, very strong guns.

otherwise, starting to grow on it, i just still dislike how mech madness is being removed. nevertheless someone could probably just open their own PR to bring it back (with a facelift hopefully) and that jimmy actually... improves this map (healing and cover is a good start)

**Comment by Loafin34** [comment]
Clown and HoS items need a revamp, maybe let clown call down a H.O.N.K. that they can try to get in before dying instantly, and HoS needs either stingbangs or lower-dose teargas grenades, so that they can have a defensive hold on the arena. Also, wouldn't a tider benefit from the ablative trenchcoat? The traitor already has the E-bow and the e-sword, and the tider only has the axe and a stunprod, giving them energy protection would be nice.

**Comment by sylvia-from-fulp-station** [comment]
https://github.com/tgstation/tgstation/pull/82929/files#diff-25467d2c8e9786903219d0c22a3c7821e16a793e1e275b44e8d797dd51bd8aa5
The graphics i made for this are not up to date to the final version of the map that was merged, or the one being pr'd here.. you can see the loadouts above. It was tested extensively for what it is; it's not going to be competitive with 8 players and was originally built for 4 only, but it was suggested and the standoff spawns added to it.

**Review by Maurukas — CHANGES_REQUESTED** [review]
I'm not convinced Mech Madness needs to be removed to add this.

**Comment by mc-oofert** [comment]
yeah me neither

**Pull request closed without merging**
