### PR TITLE
Revert "Adds defib to techwebs"

### PR DESCRIPTION
**Pull request by improvedname**
Reverts tgstation/tgstation#35454

Defibs should be limited and not mass producable trough rnd if we keep adding stuff to rnd what cargo orginally has cargo order list just becomes bloat and be nothing usefull then for cargonia

### CODE REVIEW

**Comment by Iamgoofball** [comment]
i uh

what

**Comment by Iamgoofball** [comment]
is english your first language or

**Comment by nicbn** [comment]
Ponctuation dude

**Comment by nicbn** [comment]
Punctuation, dude
Punctuation

**Comment by KorPhaeron** [comment]
The entire point of department lathes is that we can add new things to them without flooding rnd

**Pull request closed without merging**
