### PR TITLE
tgui-next portgen

### PR DESCRIPTION
**Pull request by spookydonut**
## About The Pull Request
functions!

image
image

### CODE REVIEW

**Comment by Time-Green** [comment]
Is there a better symbol for the 'off' button? Right now it looks like it's about to die for our sins

**Comment by spookydonut** [comment]
> 
> 
> Is there a better symbol for the 'off' button? Right now it looks like it's about to die for our sins

oh oops i used cross instead of times

**Comment by TheChosenEvilOne** [comment]
Maybe use NumberInput component introduced in #47221 for the power selector

**Comment by actioninja** [comment]
conflict

**Pull request merged**
