### PR TITLE
[READY] repeatable cavity step

### LINKED ISSUE #43753: The handle_cavity step is not repeatable
Unlike the manipulate_organs step from the organ manipulation surgery, the handle_cavity step from the cavity implant surgery doesn't have the "repeatable" variable set to true.

What this means is that if you accidentally implant the wrong thing in someone's chest with the handle_cavity step of the cavity implant surgery, you have to end and then redo the entire surgery to remove that item (instead of just pulling it out while the patient's chest is still open) and then end and then redo the entire surgery _again_ if you want to implant whatever item you had wanted to implant in there before.

### PR DESCRIPTION
**Pull request by tralezab**
it's not really a bug, but organ manipulation is repeatable and it doesn't make sense to have to stitch someone open and then saw them apart just because you misclicked

closes #43753

### CODE REVIEW

**Comment by Shapsy** [comment]
How many pills are you stuffing into that tooth?

**Comment by ATH1909** [comment]
Yaaaaaaaay!

**Comment by OverlyGeneric** [comment]
Oh god. Is this going to be like that one scene from Invader Zim where Zim is full of school children's organs and is a bloated mess? On the side note, Zim did replace organs with objects and most notably a cow tipping toy.'

**Comment by ATH1909** [comment]
> Oh god. Is this going to be like that one scene from Invader Zim where Zim is full of school children's organs and is a bloated mess? On the side note, Zim did replace organs with objects and most notably a cow tipping toy.'

This PR is about the organ cavity surgery, not the organ manipulation surgery. IIRC, your chest cavity can only hold one item at a time.

**Comment by OverlyGeneric** [comment]
> This PR is about the organ cavity surgery, not the organ manipulation surgery. IIRC, your chest cavity can only hold one item at a time.

I see terrible things to come with this and I am fearful of it. Double-tapping and shoving an air horn and a bike horn during lag.

**Comment by tralezab** [comment]
let me test to make sure that won't happen, this probably needs sanity

**Comment by ExcessiveUseOfCobblestone** [comment]
call me when ready

**Comment by tralezab** [comment]
@ExcessiveUseOfCobblestone ready

**Pull request merged**
