### PR TITLE
Hulks will be briefly held in place by Sigils of Transgression

### PR DESCRIPTION
**Pull request by ChangelingRain**
:cl: Joan
rscadd: Hulks will be briefly held in place by Sigils of Transgression.
/:cl:

### CODE REVIEW

**Comment by PKPenguin321** [comment]
where did the hulk touch you joan

**Comment by Aloraydrel** [comment]
Hulks were a mistake

**Comment by TechnoAlchemisto** [comment]
Stop

**Comment by kilkun** [comment]
No.

**Comment by anconfuzedrock** [comment]
kill yourself

**Pull request closed without merging**
