### PR TITLE
Shitty ideas thread: 2. Emagging a sleeper now scrambles the chems, woops!

### PR DESCRIPTION
**Pull request by MrsTonedOne**
:cl: RemieRichards
add: Emagging a sleeper now randomises the buttons, the buttons remain the same until randomised again so you can "learn" the new button config if you're a masochist, Inject omnizine but realise far too late that it's all morphine, woops! (Note: Epinephrine can always be injected, regardless of chem levels, this means if something !!FUN!! ends up on the Epinephrine button, it will always be injectable!)
/:cl:
@RemieRichards
Closes #23180

### CODE REVIEW

**Comment by ExcessiveUseOfCobblestone** [comment]
emag functions...

**Comment by Supermichael777** [comment]
hey this makes sense

**Comment by Durkel** [comment]
I can already taste the ahelps I'll get from this.

**Comment by Haevacht** [comment]
This is goind to lead to alot of confusing situations with ODs. As long as there's enough logging so the admins know it's not the doc's fault, mostly, should be good.

Though as someone who plays doc, I am now very scared.

**Comment by AdamElTablawy** [comment]
why not just make an emagged sleeper inject every single chem available to it at the maximum possible amount

AKA an unupgraded emagged sleeper would inject 20u bicard, 20u kelo, 20u morphine, etc

a fully upgraded emagged one would stuff you full of 80u of every single chem at once

**Comment by SweaterKittens** [comment]
As hilarious as this is, being a medic is already shitty enough without a mechanic to simply make your job worse. Also does the emag really need MORE functions?

**Comment by PKPenguin321** [comment]
Quit your bitching, this is fine (won't do much aside from an accidental 10u of morphine one time) and "wah emag has too many uses" is just a lame catch-all argument to pull when you don't like the prospect of maybe having to put up with something out of your comfort zone in game.

**Comment by SweaterKittens** [comment]
That's my point thought, it won't do anything most of the time except inconveniencing the person you're trying to treat and you. I just don't find it fun or interesting like a lot of the other emag interactions, like the comms console or simple robots.

I also don't appreciate you jumping to the conclusions that I dislike more emag functions because it's a fallback or I'm "afraid of change" or something. I tend to agree with Kor that adding more functions to an already somewhat-bloated item is not a good design choice, in the same way that adding any new content via RnD is also a poor design choice.

**Pull request merged**
