### PR TITLE
Fixes Shuttle bar bugs I caused

### PR DESCRIPTION
**Pull request by Niknakflak**
Fixes some stuff
- Some wall fuckery should be fixed
- Kor changed plant paths, this fixes it
- Fixes airless shuttle medbay (I'm really dumb for overlooking this one)

### CODE REVIEW

**Comment by coiax** [comment]
Stop touching my shuttles if you're going to break them.

**Comment by Niknakflak** [comment]
No, your salt sustains my life force

**Comment by optimumtact** [comment]
@coiax please read the last item in this sub heading
https://github.com/tgstation/tgstation/blob/master/CONTRIBUTING.md#pull-request-process

**Comment by xxalpha** [comment]
Proper use of floor types.

**Comment by Niknakflak** [comment]
Thanks ;)

**Pull request merged**
