### PR TITLE
Mindread now reads the correct true name

### LINKED ISSUE #48023: Mind reading can give wrong real name
## Round ID:
124588 Events EU

## Reproduction:
With the genetics upgrade mind reading the subject "Niklas Biermann" (HoS), mind was read. This gave the answer that their 'true name' was "Ava Dennis". However according to the VV this was not true. The round contained NO lings, game mode was 'Traitor' as confirmed by the Round status panel.
I couldn't see anywhere where the name Ava was taken from. No other player had that name. The HoS's backup name was something else (Zayden Williamson), so its not getting it from that.
All in all this caused security to make the assumption that the HoS was a ling and therefore was cremated.
I'm not sure where mind reading gets its names from but its certainly wrong.

## Relevant info:

Mind reading text from Detective John Jonas:
You plunge into Niklas(?|F) Biermann's mind...#You catch some drifting memories of their past conversations...#"mhm if we have cargo lets sell it"#"good job grey(?|F) man"#"on anything, instead of making someone a cap"#You find that their intent is to help...#You uncover that his true identity is Ava Dennis. 

"Victim":
Niklas Biermann. Round Start HoS. Mindsheilded

Current Game Mode: traitor

### PR DESCRIPTION
**Pull request by kriskog**
## About The Pull Request
Uses mind name instead of DNA name. Should be more consistent as well.

## Why It's Good For The Game
Fixes #48023

## Changelog
:cl: Skoglol
fix: The mind reader mutation should now always tell you the correct true name.
/:cl:

### CODE REVIEW

**Review by Cyberboss — DISMISSED** [review]

**Comment by PKPenguin321** [comment]
Thanks, I forgot about this

**Comment by kriskog** [comment]
This is why. Should be dna.real_name.
image

Either way, using mind name is the right way of doing this, as it should hopefully carry across multiple bodies in case of changeling.

**Comment by kriskog** [comment]
Actually, it was a double bug. :tada:

**Comment by PKPenguin321** [comment]
Nice work!

**Review by Cyberboss — APPROVED** [review]

**Comment by AnturK** [comment]
Wasn't this intended to not reveal lings ?

**Comment by kriskog** [comment]
Is it? I assumed that was its intention since its trying to read real_name, but if it isnt we can just read the mobs name instead.
@PKPenguin321 ?

**Comment by PKPenguin321** [comment]
Hadn't really considered lings but I think it's probably fine

**Comment by Cyberboss** [comment]
This is a true ling test, but that's a problem with the spell itself and should be addressed seperately.

**Comment by PKPenguin321** [comment]
Not necessarily... Anyone could hypothetically have their DNA identity changed, either by a geneticist or by a transform sting.

**Pull request merged**
