### PR TITLE
Refactors Temporal Scarring, changes how it works, removes longtimer quirk

### PR DESCRIPTION
**Pull request by Ryll-Ryll**
## About The Pull Request
The way that I implemented temporal scarring was pretty janky on a technical level, using 5 hardcoded slots per character pref to store the data. It was also kinda confusing mechanically, I wanted there to be some lead time between ending a shift with a bunch of scars and having them appear again, so each round you joined you'd load and save to a random slot. This probably seemed very wonky if you weren't specifically told that, so here we are.

Temporal scars are now stored in their own savefile, and rotate between a defined number of slots (3). Every time you join a round, you move to the next slot to load from and save to for that round, until you wrap back around. Much simpler to explain!

I also removed the longtimer quirk that gave you a bunch of fake scars upon spawning, so you have to work for your stolen valor (read: get the chef to carve you 'til you're unrecognizable).

Lastly, now that different species can suffer different types of wounds or have different scars for the same wound (plasmamen vs fleshy races), your biological makeup for the scar is recorded as well, so you can't load a gash scar as a plasmaman or whatever.

## Why It's Good For The Game
Improved code quality, abuses preferences less. 

## Changelog
:cl: Ryll/Shaps
del: The Longtimer quirk has been removed
tweak: Temporal Scarring has been reworked. Rather than drawing from one of five random slots each round, you now have 3 slots that you will go through sequentially, so if you survive a round with a bunch of scars, they'll be with you 3 rounds from now.
/:cl:

### CODE REVIEW

**Comment by Ryll-Ryll** [comment]
having an annoying issue where the ckey/mind doesn't seem to be there if i forcestart the round as soon as i can on runtime station while testing, so the scars don't load, but it does if i join after the round starts. not sure if that's just a quirk of my impatience but i'll look deeper into it tomorrow or the day after or so

**Comment by Ryll-Ryll** [comment]
Fixed the above issue, I just didn't understand the order of startup procs

**Comment by Pugie** [comment]
delimbed people still keep scars despite not even still having the limb

**Comment by Rohesie** [comment]
Code improvement good.

**Pull request merged**
