### PR TITLE
Adds Security Jacket

### PR DESCRIPTION
**Pull request by DrDiasyl**
## About The Pull Request
Adds a new Security clothing piece: Security High-Vis Jacket (taken from my #80278). The high-vis lines are emissive in darkness like the hazard vest.
Security Jacket (light)
Security Jacket side

You can buy it at the Security wardrobe vendor. It offers worse protection than body armour in exchange for covering arms.
## Why It's Good For The Game
More Security drip. Those are supposed to resemble real high-vis jackets that Police Officers wear irl.
## Changelog
:cl:
image: New Security clothing: Security High-Vis jacket!
/:cl:

### CODE REVIEW

**Comment by EricZilla** [comment]
Love this

**Comment by Singul0** [comment]
security's trauma team

**Comment by DrDiasyl** [comment]
FEATURE???
GBP fraud failure 😔

**Comment by wesoda25** [comment]
This with gags would be awesome 👀

**Comment by DrDiasyl** [comment]
> This with gags would be awesome 👀 

Gags 🤢

**Comment by Fikou** [comment]
> > This with gags would be awesome 👀
> 
> Gags 🤢

learn to use it kid

**Review by Wallemations — APPROVED** [review]
Swag

**Pull request merged**
