### PR TITLE
UI objects should PIXEL_SCALE

### PR DESCRIPTION
**Pull request by RemieRichards**
I added this to atoms ages ago, but screen objects override those flags (so that they don't get coloured and stuff) meaning they missed out on PIXEL_SCALE.

Duplicates the shim, but it's supposed to be ugly anyway to encourage us to remove it whenever 512 finally drops (PIXEL_SCALE is a 511 feature but it was added midway into 511, hence the >= on the 512)

### CODE REVIEW

**Comment by AnturK** [comment]
You can drop the one in movable really.

**Review by Cyberboss — CHANGES_REQUESTED** [review]
Remove the PIXEL_SCALE define in atoms_movable.dm

**Comment by RemieRichards** [comment]
no.

**Review by Cyberboss — APPROVED** [review]

**Comment by lzimann** [comment]
\>merging things you contributed to

cybeross pls

**Pull request merged**
