### PR TITLE
Fixes runtimes with Dethralling / Deshadowling

### PR DESCRIPTION
**Pull request by WhiteFox08**
Thanks to @CarbonHell for finding this gem.

### CODE REVIEW

**Comment by Carbonhell** [comment]
i love you too cutie

**Comment by Xhuis** [comment]
Thanks fam

**Comment by Aranclanos** [comment]
What if they have other spells for whatever reason

**Comment by Razharas** [comment]
>CUTTING LISTS AND REBUILDING INSTEAD OF PER INSTANCE HANDLING IS FUN!!!!11

I want this meme to die
So yes @whitefox08 please remove the list nulling completely and leave the remove_spell thingie

**Comment by Razharas** [comment]
@whitefox08 
Hows the progress

**Comment by Aranclanos** [comment]
RAAAAAAAAAAAAAAAAAZH

**Pull request merged**
