### PR TITLE
Sign synthesizer

### PR DESCRIPTION
**Pull request by Donkie**
This little nifty device is one step ahead of a complete station construction/deconstruction ability.

It lets you select a sign from a (programmically) generated list of signs available, and then slap it onto your wall of choice.

It also lets you remove existing signs from the walls.

Note that this is not done yet, I'm throwing it out here for commenting on ideas and my code.
Things to be done:
- [ ] Add a delay to pasting/removing
- [ ] Fix afterattack/use some other method
- [ ] Make the menu use NanoUI
- [ ] Mergeconflicts
- [ ] Any TODO's left in code
- [ ] Should I implement a fuel/charge/ink level thing?

Current issues I need help with:
- [ ] Implement NanoUI
- [ ] Workaround for afterattack. I want to use it because I don't want to spread my code in everyplace to make sign-removing able, but I don't want it cause it creates these messages "you push the wall", etc.
- [ ] How do I insert a list in a list without this hacky method? See my TODO

### CODE REVIEW

**Comment by ike709** [comment]
is this dead?

**Comment by Donkie** [comment]
Both yes and no, I guess you can close for now.

**Comment by Jalleo** [comment]
@tkdrg ^ maintainers choice

**Comment by tkdrg** [comment]
I don't mind leaving this open until it's done.

**Pull request closed without merging**
