### PR TITLE
Fixes a misspelled path.

### PR DESCRIPTION
**Pull request by francinum**
Whoever is responsible for this should be embarrassed.

### CODE REVIEW

**Comment by PKPenguin321** [comment]
its just a typo calm down

**Comment by Cyberboss** [comment]
NO THIS IS WHY PROXIMITY SENSORS ARE BROKEN AS FUCK REEEEEEEEEEEE!!!!!!!!!!!!!!!!!! @optimumtact !!!!

**Comment by optimumtact** [comment]
holy fuck

**Comment by AnturK** [comment]
AAAAAAAAAAAH.
I was searching for these runtimes so many times.

**Pull request merged**
