### PR TITLE
Conversions and De-conversions briefly stuns you

### PR DESCRIPTION
**Pull request by Ikarrus**
Getting converted or de-converted from a rev or cultist will knock you out for a few seconds. This is to stop them from running around, attacking people, yelling and gives them a brief moment to take in what just happened to them.

Conversions made via flash will only stun+blind+mute you

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
Won't this make it super super easy do detect revolutions?

It's already easy enough when you hear flashes 5 minutes in, but when you hear flashes accompanied by thuds, then it's a *dead* give away.

Stunned+Blinded+Silenced would accomplish the same thing without the loud thud.

**Comment by xxalpha** [comment]
Then be more subtle.

**Comment by Lumipharon** [comment]
This makes it A LOT harder for revs. You can't just say 'be more subtle' when rev literally hinges on getting shit loads of converts, before the heads know what's up.

**Comment by Thunder12345** [comment]
Even stun blind and silence is open to meta. Sec sees someone get flashed, tase the flasher, scream at the victim to move, if they don't move within a few seconds, they got revved, kill the flasher.

**Comment by Ikarrus** [comment]
This is almost exactly how rev was before flashes were nerfed and we had no such issues. 

The only different was that not stunning them left a few of them fuck around a bit before finally noticing hey, you're converted, you dunce.

**Comment by Thunder12345** [comment]
But then flashes always knocked you down, so it might just be a guy getting flashed, whereas with this there's a testable difference between flashing to fuck up and flashing to convert, which allows for syndicake style meta.

**Comment by Ikarrus** [comment]
>which allows for syndicake style meta.

Security already has an antag check for rev-heads: Loyalty implants. Using flashes as some kind of test is not only horribly inefficient, it's also not as bad as it would be with traitors, as Revolution relies on security having ways to identify the head revs.

**Comment by Fox-McCloud** [comment]
"this is the way they functioned before"....yes, but not anymore; when all flashes made you go thud, then a flash *may* have just been a flash, but when you hear flashing without thuds, then officers are instantly going to go "oh, it's fine". Flashing and a thud "CONFIRMED REVOLUTION GUYS".

I'm not worried about this being a "test" so much as I'm worried about this being very easily discernible via sound; each department has its own head, and the range of the flash and thus sound is long enough that you'll be able to hear it from just about anywhere within your department (both the thud and flash).

So "be subtle" doesn't usually cut it, sadly, in a lot of cases.

**Comment by Ikarrus** [comment]
It's a non-issue. Whatever "nerf" to revs you may think this is, it's well within acceptable bounds.

**Comment by optimumtact** [comment]
>pretending that security won't immediately assume rev when people start flashing

You guys are the worst

**Comment by Dorsisdwarf** [comment]
Anyone flashing people when I'm an officer is headed to the brig instantly anyway, and if there's VIVA on the comms/more flashing reports, they're getting an implant, whether or not people make a 'thump'

**Comment by Antimattercarp** [comment]
:+1: Stealthrev = bestrev

**Comment by AlexanderUlanH** [comment]
I'm not sure you understood the complaint @Ikarrus.  With this change, there will be a 100% accurate ingame way to identify a revolution any time someone is within sight range of a flashing- that includes passing by the department's maintenance tunnel, being in the next department over, etc, all of which there's not much avoiding.  
It can't be inefficient when knowledge of the gamemode is basically thrust at you, and the difference between "I heard someone fall over from being flashed, rev confirmed" and "I heard someone being flashed and informed security, who arrested and implanted the flasher/flashee, rev confirmed" is hardly negligible.

**Comment by Lumipharon** [comment]
Pretty much. It will be meta as fuck since that's the ONLY reason why someone will fall over when you get flashed by another player.

**Comment by Fox-McCloud** [comment]
Yup.

Which is why I suggested at most just making it stun+blind+silence; it's still obvious when you see someone do it, but it won't be obvious to people who are within hearing range; it could still just be a flash.

**Comment by Ikarrus** [comment]
Updated to not knock you down if a flash was used.

**Pull request merged**
