### PR TITLE
Stealthier Doorjack

### PR DESCRIPTION
**Pull request by Jacquerel**
## About The Pull Request

Rather than permanently busting airlocks open, the doorjack now instead:
- Unbolts the door.
- Unshocks the door.
- Removes all door access requirements.
- Opens the door.
- "Locks" bolts such that the door can no longer be bolted until the circuitry is replaced.

For the rare set of doors which cycle automatically and form an actual airlock, this also essentially removes any safety feature preventing them from opening before the cycle is finished, making them somewhat more dangerous.

As a tradeoff these two other extremely small changes have also been made:
- It takes 0.1 seconds longer for the doorjack to actually open a door (this allows the animation for the door opening to actually play).
- You can't doorjack doors with plasteel cover reinforcements (you still need to use tools to open the vault).

This change currently **does** also affect Ninjas which I am not totally satisfied with... on the one hand this is a much more ninja-y thing to do but on the other I thought the old behaviour was funny. Maintaining both is a bit of a pain in the ass though. May or may not change this based on what PR comments think.

## Why It's Good For The Game

The doorjack is fairly commonly considered to be something of a "noob trap"; that being because it's an item which _seems_ attractive and valuable for its ability to break into areas rapidly, but which actually mostly just signals as an indicator that someone should be looking for you because you leave a trail of visibly busted doors behind you.

The fact that the doorjack is worse than just hacking using tools is intentional so this change isn't intended to make it a replacement for manual effort, but now it's a little better for breaking in as well as for busting out as if you are sneaky about it then it might be some time before someone realises what has happened.
If you do it in front of someone they will still see you do it and it still leaves the examine notice that there's something up with the electronics, so it's still not a tool of first resort.

## Changelog

:cl:
balance: Doorjacks (including the one Ninjas have) now unbolt doors, render them unboltable, and remove all access requirements, rather than permanently bolting them open.
balance: Doorjacks cannot be used to open the vault door.
/:cl:

### CODE REVIEW

**Comment by SomeoneYouProbablyKnow** [comment]
The problem with doorjack is not that it's giving you away. That's fine and that's what makes it a fun item, it involves others in your stealth even if they never find you. That's the good kind of stealth not "I never impacted anyone's round" stealth.

The issue is that ANY antag already wants tools. Frankly all crew wants tools considering how many situations they bail you out of and how piss easy they are to get. So doorjack becomes redundant, not because it's a bad item but because it's a solution to a non existant problem. 
And doorjack itself isnt to blame. It's used quite effectively by nuckies. It's a sidegrade to the jaws of life and a reasonable one at that.

And making it stealthier isn't really an issue because anyone seeing you magically open a restricted door is going to be suspicious, you still leave prints and if you get searched you still have a big item with TRAITOR written on it.
Why bother when you can 3 click hack any door or weld like 70% of walls open.

But also this makes me sad cos the door emag effect is just... cool? You pull out a weird hack-card the door sparks and breaks open? That's simply kickass and this visual makes it marginally less kickass.

**Comment by Xackii** [comment]
What about nukes that declared war, who do not need to work covertly and ability to open doors and leaving them in open position is very important for maneuverability?

**Comment by SomeoneYouProbablyKnow** [comment]
Yea but if you mess with doprjack charges you end up with nuckies running around with old emag levels of door opening ability

**Comment by nianjiilical** [comment]
if this goes through, emagging the doorjack should restore the old functionality

i dont want to be a successful and stealthy antagonistic force i want to be Johnathan Emag, Permafucker of Entranceways

**Comment by SomeoneYouProbablyKnow** [comment]
Wasnt there a pr that made it so using a doormag and an emag magnetized them together? or was it just emags on emags?

**Comment by SimplySmiley123** [comment]
> But also this makes me sad cos the door emag effect is just... cool? You pull out a weird hack-card the door sparks and breaks open? That's simply kickass and this visual makes it marginally less kickass.

Well the way it works right now it also just fucks you over if the door you wanted to hack open with it was bolted.

**Comment by SomeoneYouProbablyKnow** [comment]
I mean... yea? It's not AA it's a quick and dirty hacking method for a price. The issue im trying to point out is that our hacking is already in a state where a method that's "quick and dirty" is redundant for most traitors who know what they are doing.

Imagine a world where hacking an airlock was a bigger pain in the ass or getting tools was harder or more suspicious, then an emag would have a home. But as it is no matter what you do with it'll stay a) worse than hacking tools b) better than cap spare with very little space between those options. Except for the use by nuckies but their have their own unique constraints.

There is design space for it to allow for more tricky stuff with airlocks but that'd be like making a whole new items, very few iterations of "item that just opens doors" are viable

**Comment by YuliceTheDruid** [comment]
Honestly, at this point I'd say just re-merge doormag and emag together; even if you have to have the door cooldown still for it I think having the multi functionality of both would make it a more desirable item to have.

**Comment by Maximal08** [comment]
Let people choose how they want to open the door, for example, leave the rough version of hacking on the left mouse button, and the more delicate one on the right mouse button.

**Comment by SomeoneYouProbablyKnow** [comment]
> Honestly, at this point I'd say just re-merge doormag and emag together; even if you have to have the door cooldown still for it I think having the multi functionality of both would make it a more desirable item to have.

Tbf yea. The reason for the split was that everyone was getting emags right? But that was when they didnt have charges so it evens out. It all comes full circle

**Comment by Jacquerel** [comment]
This is more contentious than it was when suggested in coding general, but I do find the arguments against it compelling. Personally I also _do_ think the current behaviour is "cool" so I wouldn't be sad to keep it. Guess I'll retire this and if someone else feels really strongly about it they can pick it up instead.

**Comment by moocowswag** [comment]
What about putting this behavior on a syndicate door remote that requires stealing and gaining heads of staff access remotes and linking them to it in order to gain access to more doors, itl function like the other door remotes but also have a mode that is alittle faster than having the player manually switch from toggling bolts to opening the airlock..

**Comment by SomeoneYouProbablyKnow** [comment]
Died 2018 (i think?)
Born 2024
Welcome back agent id

> What about putting this behavior on a syndicate door remote that requires stealing and gaining heads of staff access remotes and linking them to it in order to gain access to more doors, itl function like the other door remotes but also have a mode that is alittle faster than having the player manually switch from toggling bolts to opening the airlock..making it alittle bit faster than normal station door remotes.

**Pull request closed without merging**
