### PR TITLE
RiC: Rest in Cube 2015

### PR DESCRIPTION
**Pull request by Incoming5643**
Memorializes the space cube the best way I know how, with a stupid arcade toy in-joke to pass through the ages forwards towards eternity.

<a href="https://www.youtube.com/watch?v=4aGDCE6Nrz0">You can't cuck the cube!™</href>
341s6

### CODE REVIEW

**Comment by JJRcop** [comment]
Got any ideas for a fun special function, or just gonna be a cute little memorial object?

**Comment by Incoming5643** [comment]
I was thinking it could maybe work like the GPS and reveal your z-level, but I couldn't really justify it. Sometimes dumb stuff is better when it's useless.

**Comment by PKPenguin321** [comment]
i like the idea of a memorial but this probably isnt the way to do it
maybe a plaque in EVA or something

**Comment by Jalleo** [comment]
How about making it a toy that spouts out 8 ball style stuff to do with loops n such

**Comment by Supermichael777** [comment]
love it. stupid spacecube.

**Comment by Anonus** [comment]
Maybe you try and trace what direction something would go in from one of the sides and get disoriented/confused/angry

**Comment by PKPenguin321** [comment]
when used, you get this message:
"You trace your finger across the sides of the spacecube, but when you pass over the top of it your finger seems to move to a place it shouldn't. You get a nasty headache."
adds 15u of headache reagent which occasionally causes the following:
Cyoob McSpays looks bothered by something.
Cyoob McSpays says, "FUCKING SPACELOOPS!!"
Cyoob McSpays says, "Why didn't they make it a space torus?"
Cyoob McSpays says, "OH GOD THE IMMOVABLE ROD KEEPS LOOPING THROUGH THE STATION"

attempting to use it again while headache reagent is still in your system gives you the following message:
"You still haven't recovered from your last attempt to figure out how this thing works. It's best not to try again so soon."

**Comment by MrPerson** [comment]
That sprite is awful

**Comment by Incoming5643** [comment]
Thanks I try

**Comment by Incoming5643** [comment]
Shuttered in favor of #11904 , will reopen if for some reason that doesn't get merged

**Comment by Iamgoofball** [comment]
reopen pls

**Pull request closed without merging**
