### PR TITLE
Removes layered turfs from the crashed ship

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
Which according to joan should fix the runtimes

### CODE REVIEW

**Comment by ChangelingRain** [comment]
I know exactly what I'm having kor fix for me so this should work

**Comment by optimumtact** [comment]
This is just carpet code calling a proc only defined at the carpet level and then getting replaced with a closed turf proc without the update_icon proc

define an empty update_icon proc at the turf level and let this be a warning to all people coding turfs that they need to define all used procs at the turf level as byond will update the turf type and not stop any sleeping or running attached procs

**Comment by optimumtact** [comment]
Also it's a warning not to use turfs for as much as possible

**Comment by KorPhaeron** [comment]
there is literally no reason to have layered turfs now

**Comment by ChangelingRain** [comment]
>shove the problem under the rug by defining the proc at turf level

**Comment by nullbear** [comment]
YOU SHOULD JUST DEFINE IT AT THE ATOM LEVEL AT THIS POINT JESUS FUCK. AREAS UPDATE THEIR ICONS ANYWAYS.

**Comment by ChangelingRain** [comment]
Admittedly it's true a sssshitton of stuff uses some name of update_icon but for other procs?

**Comment by optimumtact** [comment]
The bug is still there, you just removed one of it's triggers

**Comment by nullbear** [comment]
yes.

**Pull request merged**
