### PR TITLE
psyker echolocatione improvementa

### PR DESCRIPTION
**Pull request by Fikou**
## About The Pull Request
psyker echolocation cooldown time has been reduced from 2 to 1.8 seconds
psyker heads no longer render an overlay of not having eyes
psyker echolocation rendering has been reworked to hopefully not crash the game anymore when theres many psykers

## Why It's Good For The Game
these changes make psyker better

## Changelog
:cl:
qol: psyker echolocation cooldown time has been reduced from 2 to 1.8 seconds
fix: psyker heads no longer render an overlay of not having eyes
/:cl:

### CODE REVIEW

**Comment by iamteapot422** [comment]
gamechanger

**Comment by atlasle** [comment]
i mean it still isn't echolocation... its more of a blinking mechanic currently

**Comment by Fikou** [comment]
who asked

**Comment by atlasle** [comment]
> who asked

🥺

**Comment by Loafin34** [comment]
make it 0.7 and then well see it used

**Comment by tralezab** [comment]
> i mean it still isn't echolocation... its more of a blinking mechanic currently

would be cool but it's like that "lets see you take a crack at it" meme image. it's laggy enough without firing on a delay based on distance from the psyker... but the real kicker is coding that

**Review by Ghommie — APPROVED** [review]

**Pull request merged**
