### PR TITLE
adds unique inhands for the captain's laser

### PR DESCRIPTION
**Pull request by ghost**
WOW I SURE AM GLAD SOMEONE REFACTORED INHANDS SO THIS IS POSSIBLE ISN'T THAT FUCKING RAD

ss 2015-01-28 at 04 36 37
normal laser in the left hand, cap's in the right hand

### CODE REVIEW

**Comment by dannno** [comment]
cool :+1:

**Comment by Steelpoint** [comment]
Excellent :+1:

**Comment by GunHog** [comment]
Great stuff :+1:

**Comment by PKPenguin321** [comment]
pretty sexy :+1:

**Pull request merged**
