### PR TITLE
Fixes attacking humans, paintings and some other stuff with items causing the animation to display incorrectly

### LINKED ISSUE #58058: Fried items have error sprites when attacking, fried and grilled items grill the error sprite
## Round ID:
tested locally

## Testmerges:
N/A

## Reproduction:
Deep fry something and hit yourself with it
become error
image

For further fun, take your fried something and grill it
image

### PR DESCRIPTION
**Pull request by robbertapir**
## About The Pull Request
Fixes #58058.

## Why It's Good For The Game
Attacking humans or other things that have KEEP_TOGETHER (atmos omni tanks, supplypods, paintings) with a deep fried thing will now actually show that thing instead of both that thing and an error sprite.
Attack animations for attacks against those things are no longer black.

## Changelog

:cl:
fix: Attacking people, atmos omni tanks, supplypods and paintings with deep-fried items no longer shows an error sprite.
fix: Animations for attacking people, atmos omni tanks, supplypods and paintings with items are no longer black.
/:cl:

### CODE REVIEW

**Comment by ArcaneDefence** [comment]
This doesn't feel like the right fix to me, as this is just removing the error sprite from deep fry holders that do not get their icon changed properly

**Comment by robbertapir** [comment]
@ArcaneDefence No, this fixes the bug.
The image for the attack animation is generated here:
do_item_attack_animation

The underlined line creates an image by combining the current sprite of used_item and the default sprite of it's class. This can be observed by varediting an item's sprite to something else and hitting yourself with it.
Here is what happens when you hit yourself with a rolling pin with the icon_state varedited to knife:
whack

The default sprite of the deep fried holder is error, so that line combines the error and the sprite of whatever was fried, creating this:
friedknifecurrent
Making the default sprite of the deep fried holder a blank sprite makes it create this instead:
friedknifefixed
Alternatively we could change 
`attack_image = image(icon = used_item, loc = attacked_atom, layer = attacked_atom.layer + 0.1)`
to 
`attack_image = image(icon = used_item.icon, loc = attacked_atom, icon_state = used_item.icon_state, layer = attacked_atom.layer + 0.1)`
which also makes all attack animations brighter for some reason.
This is a deep fried knife with that change:
firedknifealtfix

**Comment by Fikou** [comment]
cant you create an image and make it copy the object's appearance?
image.appearance = used_item.appearance

**Comment by ArcaneDefence** [comment]
Removing `KEEP_TOGETHER` from a carbon's `appearance_flags` makes the attack animation function as intended, but breaks unrelated things, such as ninja's cloaking. 
There's more to this bug, and people aren't even talking about how the attack animation is tinted near black when attacking carbons but works fine on other atoms.

**Comment by Fikou** [comment]
does it fix https://github.com/tgstation/tgstation/issues/59040 ?

**Comment by robbertapir** [comment]
IDK about the seethrough pods. I didn't even know that existed. This probably does not fix the pod bug.
However, it does fix the bug with attacking causing a full black animation.

**Comment by robbertapir** [comment]
This does not fix the seethrough pod bug nor affect seethrough pods in any other way, and I have no idea how to fix the seethrough pod bug.

**Comment by LemonInTheDark** [comment]
@robbertapir the dm ref seems to imply that using image() in the way we were before ought to work, do you know why it doesn't/why this does?
On that topic, why does this fix the black thing?

**Comment by LemonInTheDark** [comment]
If someone can explain this to me I will merge this pr

**Comment by robbertapir** [comment]
@LemonInTheDark It turns out that the actual problem was the plane being set incorrectly.

**Comment by LemonInTheDark** [comment]
Why was two things with the same plane intersecting causing blackness? that doesn't typically happen

**Comment by robbertapir** [comment]
@LemonInTheDark This affects everything that has KEEP_TOGETHER and can be attacked (humans, atmos omni tanks, supplypods, paintings, anything varedited to have KEEP_TOGETHER). Likely a BYOND bug.

**Comment by LemonInTheDark** [comment]
Is it something that should be replicated/reported to lummox?

**Comment by robbertapir** [comment]
It probably should but I don't have enough information about when this happens in general to report it.

**Comment by LemonInTheDark** [comment]
If you can get it to replicate in a base testcase, that'll be enough

**Pull request merged**
