### PR TITLE
New SW Maint Pantry (Box)

### PR DESCRIPTION
**Pull request by Robustin**
First map change, might need some guidance.

I hate SW maint. All the side rooms have glass so all those solar engineers and whoever love to come gawk at you, just feels like there's not enough discrete locations like SE/NW/NE maint have. 

So I moved an unremarkable little dead end around and gave us a new pantry!

http://imgur.com/L6K8LBd

### CODE REVIEW

**Comment by ChangelingRain** [comment]
It looks like you used mapmerger wrong, too, you should be using the TGM mapmerger.

**Comment by Robustin** [comment]
Yea ill need some instruction on how to use the map merger.

**Comment by coiax** [comment]
1) Run backup maps.
2) Make changes.
3) Run the merger with TGM in its name.
4) commit.

**Comment by Bawhoppen** [comment]
@coiax its called prepare maps

**Comment by Zilenan91** [comment]
@Robustin Can you also put a meat rack in here?

**Comment by coiax** [comment]
No whetstone, then you'll just get people rushing to grab it. Maybe we should consider adding whetstone to the maintenance loot though.

**Comment by bgobandit** [comment]
babby's first map merge conflict

**Comment by PKPenguin321** [comment]
nice line changes :+1:

**Comment by ChangelingRain** [comment]
In this case, line changes like that are baaaad.

**Comment by PKPenguin321** [comment]
i was joking

**Comment by Robustin** [comment]
uh what are line changes?

**Comment by TechnoAlchemisto** [comment]
i like everything except removing the super hidden vice admiral suit

**Comment by Zilenan91** [comment]
Vice admiral suits are random maint spawn though, they don't always spawn there, they can spawn anywhere

**Comment by Bawhoppen** [comment]
those are vice officer suits

**Comment by Zilenan91** [comment]
Aren't they the same thing?

**Comment by Bawhoppen** [comment]
hahahahhahahahahahahahahahhahahahahahahhaha

**Comment by PKPenguin321** [comment]
pppppppedantics

**Comment by Robustin** [comment]
so wait if I didn't run prepare maps before I made these changes, do I have to repeat them?

**Comment by Bawhoppen** [comment]
I dont actually know what prepare maps does but probably

**Comment by Robustin** [comment]
someones gonna have to post a guide to this, I used Dreammaker to make the changes and I don't see anything about TGM or Prepare Maps anywhere.

**Comment by Bawhoppen** [comment]
run prepare maps
edit map in dreammaker
run TGM mapmerger and select the map you edited
commit changes
make pull request
mergebeg

**Comment by Robustin** [comment]
Its #1 and #3 that have me clueless.

**Comment by Bawhoppen** [comment]
there is a folder named tools in the code that has the bat files you need to run

**Comment by Robustin** [comment]
thaaaaank you

**Comment by Robustin** [comment]
When I try to run TGM I get "python is not a recognized as an internal or external command, operable program, or batch file."

**Comment by Jalleo** [comment]
@robustin install python

**Comment by Robustin** [comment]
Installed Python and I'm still getting that message.

**Comment by Cheridan** [comment]
what version did you install

**Comment by xxalpha** [comment]
Read the wiki for instruction.

Just run the installer again and make sure you tick the "Install PATH" checkbox at the start. This is crucial for running python anywhere on the system without having to tell the command line where python is.

**Pull request closed without merging**
