### PR TITLE
Uh so

### PR DESCRIPTION
**Pull request by EvenInDeathIStillServe**

### CODE REVIEW

**Comment by Atskadan** [comment]
n1c3

**Comment by Thunder12345** [comment]
Congrats on the smallest possible PR. No line additions or deletions and on commit.

**Comment by Atskadan** [comment]
no someone had a pr with 0 commits once

**Comment by Miauw62** [comment]
I once had a PR with infinity commits 8)
Op 3-apr.-2015 23:22 schreef "Atskadan" <notifications@github.com>:

**Pull request closed without merging**
