### PR TITLE
Nerfs nuclear slugs to 51 brute

### PR DESCRIPTION
**Pull request by Dorsisdwarf**
This lets them still crit the clown, the assistant with a stunprod, or whoever, in 2 shots, but means they have to expend three shots on anyone with any bullet resist (and maybe 4 shots on bulletproof, I'm not so hot on the armor values right now)

Probbably fixes an issue or two out there somewhere.

### CODE REVIEW

**Comment by Steelpoint** [comment]
For basic armour it will take three shots to crit, with two shots leaving the user with 14 health.

For HoS armour it will take three shots to crit, with two shots leaving the user with 28 health.

For bulletproof armour it will take ten shots to crit, with two shots leaving the user with 80 health. HOWEVER if shot on the bulletproof helmet it will take four shots to crit, with two shots leaving the user with 40 health.

However bulletproof armour, and armour in general in most cases, only covers the torso thus any shots to the arms and legs will deal full damage.

**Comment by freerealestate** [comment]
Not sure if these need nerfing, considering the station's advantage is that
they outnumber the ops, and any one of them can overpower the ops with a
stun weapon or by disarming them

**Comment by PKPenguin321** [comment]
why 51 why not 50

**Comment by AlexanderUlanH** [comment]
What if, instead of rebalancing nuke op slugs to be right on the edge of a 2-hit-crit with their own special projectile, we gave people like the HoS enough bullet armor to make a difference when faced with the single most commonly used projectile on the station?
When you consider burst weapons, 60 bullet damage is what the majority of guns on the station are going to wind up doing.

**Comment by Dorsisdwarf** [comment]
Actually, revolvers and slugshots fire Bullet, not heavybullet, which is used in the LMG and only does 35. Pretty sure the ProtoSMG Saber does something like 15 damage a shot, too, not 60.

This is also mechanical TC balance too, seeing as there's no point buying special slugs or other guns when you 2hitcrit the HOS through his chest armor.

**Comment by CosmicScientist** [comment]
So wait, you want chems to be able to bring you back if they're in your system at the time so you can either bite another slug or get away or disarm some ignorant operatives?

Also this seems like a weird nerf, you might as well replace the handguns operatives have on their person with these shotguns since who'd use anything besides a two-hit on crew and a three-hit on sec if it's for free? And then use the stun ammunition combined with dragon's breath to just annoy the bulletproof wearer to death if anyone actually picked that armour up.

**Comment by WJohn** [comment]
Honestly just buff security armor to actually survive that kind of punishment. Maybe make it so armor has 20 bullet protection or something.

**Comment by Steelpoint** [comment]
20 bullet protection for sec armour would reduce this slug's damage from 51 to 40, meaning it would take three (3) slugs to crit a officer.

I think current armour has around 15 bullet protection.

**Comment by Steelpoint** [comment]
Bullet protection has almost always been on the low side for sec barring the head of security, usually armour let you survive one or two extra bullets before going into critical. However the more common bullet weapons tended to stun you in one hit or so meaning the damage was meaningless.

**Comment by Nanotransistor** [comment]
If you buff sec's armor, you will end up making traitor guns weaker.

Also 51 would leave you in a very light crit, making it really easy for someone to come an apply a brute patch. Seems like a reasonable nerf.

**Comment by Steelpoint** [comment]
Or shoot you again.

I'm just stating the exact damage values this slug will deal against current armour, actual discussion on armour and other features should be discussed on the forums.

**Comment by AlexanderUlanH** [comment]
You're right about the bullet type, so I updated the comment.  They do 60 damage, which is the point.  Also, the SABR does fire 20-damage bullets.
@Steelpoint, 20 bullet protection would also make the current 60 a 3-hit crit.
As far as TC balance goes, there is reason to buy a gun in ops already: your choices are either a one-burst stun, or a more expensive one-burst crit plus grenades, both of which are premium items for use against larger crews where you won't necessarily have time or ammo to shoot every graytider and officer twice.

**Comment by Dorsisdwarf** [comment]
Cosmic, bear in mind that this is explicitly a flat-out nerf to the ops' capability, introduced when my last nuke PR simply used the default 60 brute shotgun slug, instead of the five 15 brute pellets in the (cruddy) buckshot default.

**Comment by PKPenguin321** [comment]
nobody will have tricord in their blood as they're being shot at
just appease my autism with nice round numbers and make it 50 please

**Comment by WJohn** [comment]
Yeah if regular armor is buffed to have at least 20 bullet resistance, the current 60 damage slugs will do 48, making it a 3 hit crit against officers.

**Comment by Steelpoint** [comment]
Correct me if I'm wrong here.

Nuke Ops get the shotgun for free correct? And this is the standard ammo used by said shotguns.

Is this balanced? Beforehand when C20r's where the standard issue it took 5 shots to crit and 10 to kill a target, yet we're comfortable with giving Ops a, essentially, two hit crit weapon for free.

I know we're trying to find ways to buff Nuke Ops in high pop rounds, but if we buff them like this then suddenly the 80% win rates on low pop will start turning into 100%.

**Comment by CosmicScientist** [comment]
@Dorsisdwarf this is hardly a nerf except for situations where people stop clicking before they see *deathgasp or are intimately familiar with the damage system so they efficiently crit anyone they see and not kill them if they don't care about medical staff loitering around.

When shotguns used to use pellet spread, people complained about friendly fire, now that they start with the objectively better slugs (less chance to kill your fellow operatives unless you/the others are stupidly fidgety and for the same damage)... why not make this a purchasable gun? Or even give the nuke ops the guns but force them to buy the ammunition rather than giving them what is it? Five? That not everyone uses in a half decent team? So whoever does use them gets free reloads?


The only currently open issue I could see related to this is #9118 but it's a complaint about what we used to have in the shotguns.

**Comment by SconesC** [comment]
SABR does 20 btw

**Comment by Dorsisdwarf** [comment]
Cosmic, again, you haven't read the fucking PR.

This PR does nothing but *reduce* the damage that the slugs (which have been standard-issue for something like a week now) *already do*, because they made the starter weapon objectively the best weapon in the game, under all.

The downside of these being that they don't instastun or whatever like the CR-20.

If people think that 51 is still too high, I'll drop it down to 35 and just use heavybullet1

**Comment by AlexanderUlanH** [comment]
@Dorsisdwarf point-blank pellets deals 75 damage, and damage falls off very, very harshly with range.
If you want to give ops reason to purchase weapons instead of using a default one, I'd suggest making the bulldog a sidearm, except that they already have a sidearm.  Said sidearm deals 30 damage, which makes your suggestions dangerously close to that already.

I'll propose as a suggestion, then, that you instead add bulldogs to the uplink for a cost roughly on par with a revolver and increase the nuke op TC count to compensate.

**Comment by Lumipharon** [comment]
https://tgstation13.org/phpBB/viewtopic.php?f=10&t=3990

I was already talking about this.
The bulldog in it's current state is a revolver with 1 extra shot per reload. There is quite literally no reason to ever use any other ammo type since they're all terrible, while a 2 hit crit on EVERYONE BUT THE HOS, is rediculously good.

I suggested ops simply not start with a shotgun at all, but each uplink would be able to purchase ONE main weapon (bulldog/c-20r/m-90/saw/chem thrower) at some sort of scaled cost, rather then simply giving them more tc's (which would just let them spam borgs or mechs easier).

**Comment by optimumtact** [comment]
bullets kill, surprising isn't it

**Comment by Dorsisdwarf** [comment]
Who thinks ops should get Taser slugs as their starting ammo, a callback to when they had old eguns?

**Comment by AlexanderUlanH** [comment]
I think that would be fine to more or less everyone.

**Comment by freerealestate** [comment]
If you're going to change their ammo, they should probably just start
unloaded, because taser slugs are worthless without a decent back-up
weapon. They'll just have to switch the ammo for bought slugs anyway.

**Comment by Lumipharon** [comment]
They used to default to taser slugs, but that was changed at some point around the stun reductions.

Make them start with those new chem darts, mute and short stun mang.

**Comment by Dorsisdwarf** [comment]
freerealestate, I'm not even sure if it's possible to make them start unloaded, especially with the shitty way they handle multiple ammo types (All ammo types must be a child of the ammo type the guns start with)

**Comment by Nanotransistor** [comment]
Honestly, i feel nuke ops waste too much time choosing what to and not to buy, and newer players will never make the right choice in equipment. Too much to choice from and so little differences between each gun that dont affect strategy in any way. 

Their main gun should be able to fulfill most combat needs, and expend TC only to get a tactical advantage, and increased ammo. Most experienced ops end up buying the same gear every time anyway.

**Comment by Jordie0608** [comment]
@Dorsisdwarf Are you still working on this?

**Comment by Dorsisdwarf** [comment]
no

**Pull request closed without merging**
