### PR TITLE
Changes to two AI Malfunction camera powers

### PR DESCRIPTION
**Pull request by GunHog**
- Reactivate camera is now "Reactivate Camera Network". It now fixes up
  to 30 cameras, automatically diagnosing the entire network instead of
  requiring selection.
- Cost doubled to 10.
- Upgrade Camera is now "Upgrade Cameranet". It now works on the entire
  camera network to give each camera X-ray and EMP proofing, as well as
  giving the AI night-vision.
- Cost greatly increased to 35 to reflect its utility.

Costs and effects subject to change, based on feedback. A changelog will be made upon finalizing the PR.

### CODE REVIEW

**Comment by Shadowlight213** [comment]
Would there be a non terribly snowflake way to have the reactivation give priority to areas close to where the AI eye currently is? Because it would suck to really need to fix a camera, and use the ability, only to have it fix cameras on the other side of the station or something.

**Comment by GunHog** [comment]
If there were a view() check or something, perhaps. That is why the limit is so high, roundstart broken cameras and the camera failure event might cause you to burn ~8 or so uses on those, and the rest would be sufficient to repair areas where people have started cutting. Use it wisely. Let me know if you think the limit should be adjusted.

**Comment by GunHog** [comment]
So, no maintainers or additional comments in six days, so changelog posted. Ready for merge unless someone has suggestions.

**Comment by Jordie0608** [comment]
You edited the example changelog by accident, need to make your own one.

**Comment by GunHog** [comment]
I...I am sorry, Dark Lord! I have displeased you! I have corrected my mistake!

**Pull request merged**
