### PR TITLE
Removes sentient disease

### PR DESCRIPTION
**Pull request by Time-Green**
## About The Pull Request

Completely removes sentient disease from the game

## Why It's Good For The Game

Sentient disease is a unique antag and seems fun on paper, but really doesn't work that well. 

Sentient disease is a pretty binary antagonist: you either get cured and watch helplessly as you lose all your hosts, or you infect everyone and wipe out the entire station. Its everything bad about conversion antags, but there's not even any fighting.

I also don't think any amount of balancing can fix sentient disease. If we make it harder to cure, the disease gets an easier station wipe, but if we make it less lethal, it loses all ability to stop cure generation. The core gameplay pitches the entire crew against one disease, and it's merely a timer before either it gets cured or wipes out everyone

This is my latest sentient disease round, where I wiped out the entire station. I only even greentexted because there was one guy on the escape shuttle in crit that barely made it because they had the sense to take spaceilline. 

image

The removal of the virologist lets us balance viruses to be fairer challenges to the player, but as long as sentient disease exists we'll always have to balance viruses somewhat in favor of the enjoyment of the disease blowing your head and making you spontaneously combust. 

## Changelog
:cl:
del: Removes sentient disease from the game
/:cl:

Hopefully, once we get virology truly sorted out, we can readd sentient disease, but this would require our diseases to have endgoals that aren't focused around killing every person, being widespread while also not being instantly curable. A reworked sentient disease would have to be so different, it's better to leave it out, fix virology and then consider if we can truly add a new sentient disease and have it be fun and fair

### CODE REVIEW

**Comment by EnterTheJake** [comment]
At long last.

**Comment by Higgin** [comment]
let's take this one out back

**Comment by Mothblocks** [comment]
> Hopefully, once we get virology truly sorted out, we can readd sentient disease

This will never happen and you know it

**Comment by DrAmazing343** [comment]
RIP to a real one. You were fun... once. Now, it's time to go. o7

**Comment by Time-Green** [comment]
> > Hopefully, once we get virology truly sorted out, we can readd sentient disease
> 
> This will never happen and you know it

Same likelyhood as someone closing a 3000 line feature PR after a review and saying "will re-open later"

**Comment by moocowswag** [comment]
sentient disease should be reworked into being like the infectonator game

**Comment by PKPenguin321** [comment]
what if it was admin only :)

**Comment by MatrixOne500** [comment]
Yes! There's just not enough fun interaction and possible counterplay against an antag like that.

**Comment by Dawnseer** [comment]
What do you mean not having end goals about killing everyone? It already DOESN'T have that end goal. It's goal is just to spread and also get on the shuttle. That most players decide to go for funny sleepy death virus is a player thing. They could become a healing virus. But chances are they still become cured anyway due to the off chance that they might choose death later down the line.

**Comment by PotatoOfChaos** [comment]
Good riddance

**Comment by Time-Green** [comment]
Rest in peace 😔

**Comment by TheVekter** [comment]
Finally taken out back and given the shotgun. Thank you for your service.

**Pull request merged**
