### PR TITLE
fixes ministation telecomm

### PR DESCRIPTION
**Pull request by ghost**
poor little ministation has been missing her telecomms stuff for a while, this fixes it

### CODE REVIEW

**Comment by Jordie0608** [comment]
You've misunderstood how the map compiling system works. The code files used by ministation are only included when ministation is set to be the map used for compile since that's the only time they'll be needed.

https://github.com/tgstation/-tg-station/blob/master/_maps/ministation.dm#L66

**Comment by Giacom** [comment]
That's right, I put a warning here: https://github.com/tgstation/-tg-station/blob/master/_maps/map_files/MiniStation/readme.dm

**Comment by syndicute** [comment]
i've had _maps\map_files\MiniStation\telecomms.dm included because the map wouldn't load by default on dreammaker, but now you guys are aware and can come with a better fix!

**Comment by Deantwo** [comment]
Make an issue if... it is an issue.

**Comment by Jordie0608** [comment]
If you just ticked /_maps/ministation.dm you need to re-compile before trying to open the dmm.

**Pull request closed without merging**
