### PR TITLE
Curator Suit Resprite!

### PR DESCRIPTION
**Pull request by Imaginos16**
## About The Pull Request
Self explanatory! I'll get around to the other costumes at a later date

image

## Why It's Good For The Game
No more eye bleeding colors, now they can be taking a tinge more seriously too!

## Changelog

:cl: PositiveEntropy
imageadd: Resprites suits associated with the curator job!
/:cl:

### CODE REVIEW

**Comment by ShizCalev** [comment]
If it's not too much bother would you mind doing inhands for these too? ♥

**Comment by Imaginos16** [comment]
> If it's not too much bother would you mind updating the inhands for these too to match the new shades? ♥

There's none associated with the three specifically. As in, ones that match one-to-one.

**Comment by ShizCalev** [comment]
```
/obj/item/clothing/under/rank/captain/suit
	name = "captain's suit"
	desc = "A green suit and yellow necktie. Exemplifies authority."
	icon_state = "green_suit"
	inhand_icon_state = "dg_suit" <-----------------------
	can_adjust = FALSE

/obj/item/clothing/under/rank/captain/suit/skirt
	name = "green suitskirt"
	desc = "A green suitskirt and yellow necktie. Exemplifies authority."
	icon_state = "green_suit_skirt"
	inhand_icon_state = "dg_suit" <-----------------------
```
image

```
/obj/item/clothing/under/suit/red
	name = "red suit"
	desc = "A red suit and blue tie. Somewhat formal."
	icon_state = "red_suit"
	inhand_icon_state = "r_suit" <-----------------------
```
image

```
/obj/item/clothing/under/rank/civilian/head_of_personnel/suit
	name = "head of personnel's suit"
	desc = "A teal suit and yellow necktie. An authoritative yet tacky ensemble."
	icon_state = "teal_suit"
	inhand_icon_state = "g_suit" <-----------------------
	can_adjust = FALSE
```
image


They're not named the same in the inhands .dmi files, but these correspond to the sprites you're changing.

**Comment by ShizCalev** [comment]
That's what I meant; could you make ones that at least kinda match what you made?

The teal suit you made has an inhand of 
image


The green suit you made has an inhand icon of
image

Just trying to widdle down the amount of things using generic icons that aren't really representative of someone's holding.

**Comment by OrionTheFox** [comment]
Out of curiosity, why not make suits GAGS, get all the suit resprites done at once?

**Pull request merged**
