### PR TITLE
Adds 'Guardian of Balance' AI lawset

### PR DESCRIPTION
**Pull request by coiax**
:cl: coiax
add: Adds a 'Guardian of Balance' lawset and AI module, currently admin
spawn only.
/:cl:

- Also refactors some of AI_modules.dm to use the /datum/ai_laws stuff
to avoid law duplication.
- Saw this lawset on Basil, thought it was too nice to not immortalise

### CODE REVIEW

**Comment by ChemicalRascal** [comment]
_I am one with the force, and the force is with reeee._

**Comment by Jazaen** [comment]
I saw it to. 
I was a revhead, and from my point of view AI used it to validhunt incredibly. That, plus I think it vented the lower half of station entirely.

**Comment by GunHog** [comment]
I honestly would have no clue how to follow the Balance lawset.

**Comment by Buggy123** [comment]
"so long as it does not disrupt the balance of the greater balance"
That wording could be reworded, changing the words by rewording it to be reworded to words such as:
"so long as it does not disrupt the greater balance"

**Comment by ExcessiveUseOfCobblestone** [comment]
is this jargon valadin?

**Comment by Dorsisdwarf** [comment]
It's beautifully worded, but to work as an AI lawset we need to get the circlesaws out and pare it down to unambiguous simplicity.

**Pull request merged**
