### PR TITLE
Syndicate lavaland base now has a single self-destruct bomb

### PR DESCRIPTION
**Pull request by coiax**
:cl: coiax
tweak: The Syndicate lavaland base now has a single self destruct bomb
located next to the Communications Room. Guaranteed destruction of the
base is guaranteed by payloads embedded in the walls.
/:cl:

I saw WJohn do this for his syndicate space base, and thought it made a
lot better sense than just having a bunch of bombs lying around.

A very minor refactor of syndicate bomb code, mostly because the base
seemed to use a badmin bomb that had no other purpose other than being
slightly larger to explode?

image

(Syndicate balloon was already there, it's a special baseturf modification effect, not actually visible ingame)

### CODE REVIEW

**Comment by Repukan** [comment]
I refuse because one of thr best things about the many bombs was that you could plan break ins and set them up without the syndicate members knowing.

**Comment by Armhulen** [comment]
will this explode the whole base?

**Comment by BeeSting12** [comment]
@Armhulen 

> Guaranteed destruction of the
base is guaranteed by payloads embedded in the walls.

**Comment by Supermichael777** [comment]
It has space base turfs fix that

**Comment by lzimann** [comment]
This should probably be in the middle of the base.

**Comment by coiax** [comment]
They are visible in game, I'm working out how to hide them. I can either make them invisible and anchored, or I could lower their layer, so they're beneath the walls

**Pull request merged**
