### PR TITLE
Makes the felenid language not break the "no netspeak" rules

### PR DESCRIPTION
**Pull request by GuyonBroadway**
## About The Pull Request

This changes the felenid language from mostly Japanese themed netspeak to a rough approximation of real cat noises.

## Why It's Good For The Game

Saying half this stuff IC might or might not be ok on the norp servers depending on which admin you ask but would likely get you a stern talking to on the medrp servers. It's bad to give players a mechanic as basic as this and risk them getting punished just for using it. 

## Changelog
:cl: GuyonBroadway 
tweak: adjusted the felenid language to be more cat-like
/:cl:

### CODE REVIEW

**Comment by optimumtact** [comment]
you are not welcome here, go away

**Comment by GuyonBroadway** [comment]
What did I do wrong?

**Comment by GuyonBroadway** [comment]
I left hippie well over a year ago, those repos are just leftovers.

**Comment by optimumtact** [comment]
I don't care, the apple doesn't fall far from the tree.

**Comment by GuyonBroadway** [comment]
Why does it matter that I used to continue to hippie anyway? The change I made here is made in a vacuum, if what I changed is bad on its own merits then fine but a little feedback on why would be nice. I think you are being unfair here.

**Comment by optimumtact** [comment]
Your concern is manufactured and false, admins will not punish people for using a language, least of all not because ghosts have an omnitongue and can literally understand everything said.

The only way to interpret this PR is sour grapes that the original PR got merged at all, as your clear and evident bias was on show in the comments of the other PR.

I am not interested in negotiating with the anti felinid faction, as far as I'm concerned the matter is at rest, so while we will strictly manage all species changes still, I am more than happy to bring them in line with the rest of the roundstart species, which means they get their own language.

**Comment by GuyonBroadway** [comment]
I dispute that this concern is manufactured, I was going to bring it up in the discussion but ya merged it before I got the chance.  I actually made this pr in good faith and I only ask it not get tossed aside cuz of opinions I have elsewhere. They're opinions and people are allowed to have and disagree with them, and that's fine, I accept people don't see things my way.

Sure I don't like the cat race, but I am literally the person who coined the name, if I don't like things I try to make my point, contribute  and propose changes, that's the point of open source software. You might refer to the chocolate pr but that was based on a copypasta about lepi mewterra getting deathly I'll from eating chocolate and dying cus cats are allergic. It sucks people used it to grief and I never intended for mass poisonings. I did it because people on discord found the pasta funny and when I joked about coding it people said I should. So I did, because I thought they would find it funny.

I just wanted people to have a good laugh, nothing else.

And indeed here, I'm sure Krisog added this with the best of intentions, I disagreed in the comments and others disagreed with me. My change here was simply attending to something I thought might be a real concern. And you know what, I could be wrong and if so, then fine. I'm wrong. 

If I was actually salty I'dve made other prs to fuck felenids over in less funny ways. But as it stands I don't actually like making things less fun for people.

**Comment by Joey-Loey** [comment]
No, I don't believe you made this PR in good faith. For starters, as of the time this comment was posted, the felinid PR has only been merged for six hours. If admins thought there'd be problems with netspeak, it would have been brought up. You did not cite a single ban caused by the language. Besides that, the felinids have always been one big anime catgirl joke, hence why they'd speak in broken japanese. Their language makes sense. I know this may be shocking to you, but tgstation originally came from 4chan's traditional games /tg/ board. Obviously coming from a community that likes anime/otaku culture, there would be anime jokes and references. Hence, this entire PR is dubious and poorly thought out, but we all know anti-felinid PRs are generally created to stir shit so nobody is going to give you the benefit of the doubt.
>Why does it matter that I used to [contribute] to hippie anyway?

Hippie players are notorious for having their heads up their asses. Pretty much everyone from that server that was once worth a damn now hates it. Admiral hates it, Looping hates it, Carbonhell hates it, the list goes on. HippieStation has had its forums nuked three times in a year by disgruntled staff who hate the server. Hippie may have been a server years ago, but as of recent it's nothing but a tg spite server with reddit tier humor. Or WAS one, any way. Now it's a ghost on the hub.
Why does this matter? Well, it just so turns out that 2017-2020 HippieStation prided its self on being anti-TG and anti-felinid. There's reasonable cause to believe that someone who was once from HippieStation would make PRs like this. You might not like felinids or felinid players, but Hippie players hated them only because the lot of them were extremely easily offended despite believing they were hardcore, again much akin to a redditor.

So, you're from Hippie (or once was, now you're from whatever zombie downstream like Spacepunch hoveirng at 0 pop), you've made anti-felinid PRs in the past, and you also generally only show up here to mock controversial PRs (which if I recall got you blocked from the git in the past), then why would anyone believe you're suddenly here innocently making a PR over some concern you had?

**Comment by lordpidey** [comment]
While I personally think this PR is a net negative based on it's own merits, finding the netspeak meme mildly funny, I am agitated at the way he was treated.

The coder made a legitimate attempt to improve our game, and brought his proposition to us in the form of a PR, where we are supposed to analyze and discuss the contributions, both technically, and for appropriateness of the addition.

And what did we do?  We insulted who he associates with, and then accused him of making a PR in bad faith.

**Comment by Joey-Loey** [comment]
I've lurked too many of these dumb anti-felinid PRs to believe any of them are made in good faith any more, lordpidey. They're almost always made by some random guy who clearly hates the felinids and wants to piss them off. Mentioning that he's from HippieStation is fair given Hippie's community constantly tried to punch up.
It's understandable that you'd want to assume good faith, but we've seen these PRs time and time again.

**Comment by optimumtact** [comment]
There's no we lordpidey

**Comment by lordpidey** [comment]
Okay, fine.

While I still very much disagree with you that being associated with Hippie is a deal breaker, he appears to no longer be associated with them, his last commit being approximately 10 months ago, consistent with their claims.

And let's face it:  2017-2019, TG was anti-felinid.  They were round start, then removed, then grandfathered, and whole hordes of stuff.  Killing catgirls used to be basically a meme.  What's your point about hippie being anti felinid during those periods, given that the times OP was with hippie, TG was also anti-felinid.

Also, the original PR had equal numbers of thumbs up and thumbs down.  This is a fair indication that it's somewhat controversial among the coders.

**Comment by Joey-Loey** [comment]
>he appears to no longer be associated with them, his last commit being approximately 10 months ago, consistent with their claims.

That's because Hippie completely died. They wiped their banlist out of desperation for players.
>And let's face it: 2017-2019, TG was anti-felinid. They were round start, then removed, then grandfathered, and whole hordes of stuff. Killing catgirls used to be basically a meme. What's your point about hippie being anti felinid during those periods, given that the times OP was with hippie, TG was also anti-felinid.

Felinids had many reasons to be hated however most of them made no sense and was purely whining about anime. The playerbase problem is inherent with SS13 and races as a whole, it's not like Lizards or Tajarans on other servers didn't have their fair share of metagamers and obnoxious players as well. Removing a feature specifically because annoying people like it is ridiculous and caving to easily offended nerds. If they annoy you, learn to ignore them or robust them.
>Also, the original PR had equal numbers of thumbs up and thumbs down. This is a fair indication that it's somewhat controversial among the coders.

Because felinids are somehow still controversial, and nearly every PR pertaining to felinids one way or another becomes a shitshow, hence why I don't think anti-felinid PRs should be given the benefit of the doubt. "Felinids are too similar to humans!" "Let's make them less like humans!" "BUT THE METAGAMERS NOOOO YOU CAN'T DO THAT!!"

**Comment by GuyonBroadway** [comment]
This PR isn't anti-felenid, if I wanted to be anti felenid I'd report every player who used this to the admins for breaking the no netspeak rules.

**Comment by cacogen** [comment]
still terrible

**Comment by GuyonBroadway** [comment]
That's fine... but why do ya think that is all I wanna know.

**Comment by optimumtact** [comment]
thanks_for_shraing

**Comment by Dorsisdwarf** [comment]
you guys merged the joke anime language PR?

**Comment by cacogen** [comment]
as i said on the previous pr, it's furry or anime and they both attract cringy cliquish snowflakes

**Comment by GuyonBroadway** [comment]
One has netspeak which is, as far as I remember, against the rules, one does not. I agree with your stance on cliques but this pr isn't about metabuddying, it's about what doesn't and doesn't break rules just by virtue of its use in just about any situation.

**Comment by Acer202** [comment]
> One has netspeak which is, as far as I remember, against the rules, one does not. I agree with your stance on cliques but this pr isn't about metabuddying, it's about what doesn't and doesn't break rules just by virtue of its use in just about any situation.

I like your PR on the grounds that felinids would reasonably have an inherent understanding of cat noises akin to their natural urge to chase lasers instead of explaining it away by saying they have developed their own completely unique language distinct from galcom within 300 years of existing as a species. Am glad for the content either way, though. Thanks for your PR.

**Comment by lordpidey** [comment]
Here is my review on the PR itself.

I think your change is fundamentally a net negative.

Classic SS13 has been based around memes, and high danger.

When making a list, try to make them take up more size on each line.

You have reduced the total number of syllables by about half.

You made a PR that didn't even compile, and didn't fix it for eight hours.  This speaks poorly as to your programming ability.

**Comment by GuyonBroadway** [comment]
SS13 is memes but netspeak is against the rules. (I also think the weeaboo speak is garbage but that's my opinion and therefore not objective)

Will fix.

Open to suggestions for more, I just added the common ones plus several reverse engineered from noises my pet cat makes.

I put it up then had to go do other stuff. Only got the chance recently to fix it.

**Comment by lordpidey** [comment]
https://github.com/tgstation/tgstation/blob/master/.github/CONTRIBUTING.md#pull-request-process

> If your pull request is not finished make sure it is at least testable in a live environment. Pull requests that do not at least meet this requirement will be closed. You may request a maintainer reopen the pull request when you're ready, or make a new one.

Non-compiling code is effectively the most untestable you can make it, without it being outright malicious code.

**Comment by GuyonBroadway** [comment]
Yeah that one's on me and I was a little hasty and got called away to do stuff before I could correct it.

**Comment by CRITAWAKETS** [comment]
japanese isnt netspeak you trilobyte

**Comment by GuyonBroadway** [comment]
Hewo, boop and to a lesser degree uwa are newspeak vernacular and I see the other terms used a heck of a lot.

Unless I've been hanging around you people too much and literally nobody says any of those things.

**Comment by CRITAWAKETS** [comment]
> Hewo, boop and to a lesser degree uwa are netspeak vernacular and I see the other terms used a heck of a lot.

local coder doesnt even know how the foreign speech system works when changing stuff relating to it

**Comment by GuyonBroadway** [comment]
Well it's about time and this PR is actually demonstrably unpopular.

Any last words oranges?

**Comment by optimumtact** [comment]
template

**Comment by GuyonBroadway** [comment]
image

**Pull request closed without merging**
