### PR TITLE
Fix TGUI notepad with various small fixes

### PR DESCRIPTION
**Pull request by raffclar**
## About The Pull Request

Back from my hiatus and playing ss13 again!  A few fixes for this component I wrote back in 2022. Hopefully the commit messages are self-explanatory.

There's one fix to TextArea that needs extra scrutiny. I removed the `blur()` call as it prevents newline input (unless holding shift).
@jlsnow301 Could you check this one-liner change?

## Why It's Good For The Game

Fixes incorrect prop usage, uses new props on TextArea, uses `login.IDName` instead of `clientName` and so on.
The most important fix would be restoring state change on text input as that's quite important for other bits to work.

## Changelog
:cl:
fix: Various fixes to TGUI notepad
/:cl:

### CODE REVIEW

**Comment by jlsnow301** [comment]
> I removed the blur() call as it prevents newline input (unless holding shift).
That's the point though, enter (without shift) is to enter

**Comment by raffclar** [comment]
> > I removed the blur() call as it prevents newline input (unless holding shift).
> 
> That's the point though, enter (without shift) is to enter

That's new behaviour with the TextArea since I wrote this component. I can either:
* Replace the commit with a small blurb of text in the bottom left in the status bar to explain shift-enter for newlines.
* Just drop the commit.

**Comment by jlsnow301** [comment]
> * Replace the commit with a small blurb of text in the bottom left in the status bar to explain shift-enter for newlines.

I kind of like this shift enter behavior. If you wish to add in a blurb of text to show the user this, that's acceptable

**Comment by raffclar** [comment]
> > * Replace the commit with a small blurb of text in the bottom left in the status bar to explain shift-enter for newlines.
> 
> I kind of like this shift enter behavior. If you wish to add in a blurb of text to show the user this, that's acceptable

I've dropped the old commit and replaced it with
https://github.com/tgstation/tgstation/pull/85472/commits/549a7a81f291277972a8b63b7c4f5dc41b5b76bc

<details>

image

</details>

**Pull request merged**
