### PR TITLE
Adds some more reagents to clogged vents

### PR DESCRIPTION
**Pull request by DaxDupont**
[Changelogs]: 
:cl: Dax Dupont
tweak: More reagents in the clogged vents event.
/:cl:

[why]: Added some more _mostly_ harmless reagents for more variety.

### CODE REVIEW

**Comment by DaxDupont** [comment]
@Armhulen it's a tweak I guess. I redid clogged vents and I wanted it to be test merged but they just merged it instead. 

Also I added skewium, that's a buff if anything. Beer in high amounts is lethal and sugar will cause sugar overdoses or at the very least cause slowdowns due to being overly fat.

**Comment by Armhulen** [comment]
Sure, I just mean that you're adding more nonlethal chems than lethal ones. I actually like this pr

**Comment by Anonmare** [comment]
>whiteglitter

D E V I L I S H

**Review by arsserpentarium — COMMENTED** [review]
Skewium, white glitter, growthserum...
Don't forget about colorful reagent, pax, carpet, plasmaman mutation toxin and mulligan toxin.

**Comment by DaxDupont** [comment]
No mutation toxin you dweeb.

Also there's already colourful reagent in there, read before you comment
please.

**Review by Cyberboss — APPROVED** [review]

**Pull request merged**
