### PR TITLE
Refactors most spans into span procs

### PR DESCRIPTION
**Pull request by Watermelon914**
## About The Pull Request

Converts most spans into span procs. Mostly used regex for this and sorted out any compile time errors afterwards so there could be some bugs.
Was initially going to do defines, but ninja said to make it into a proc, and if there's any overhead, they can easily be changed to defines.

This definitely will need a testmerge once I'm done with local testing.

## Why It's Good For The Game

Makes it easier to control the formatting and prevents typos when creating spans as it'll runtime if you misspell instead of silently failing.
Reduces the code you need to write when writing spans, as you don't need to close the span as that's automatically handled by the proc.

## Changelog
:cl:
refactor: Refactors how spans are done in code.
/:cl:

### CODE REVIEW

**Comment by Time-Green** [comment]
RIP maintainers having to review your changes

**Comment by Watermelon914** [comment]
> RIP maintainers having to review your changes

It's mostly just regex

**Comment by Jordie0608** [comment]
Can you post the regexes you used?

**Comment by Watermelon914** [comment]
> Can you post the regexes you used?

I used a lot and I didn't keep track of the ones I was using but I can try and recall the ones I did use

Regex: "<span class='([a-zA-Z_]+)'>(.*?)</span>"
Replace: span_\L$1("$2") 
Used this one a few times for spans that encased entire strings.

Regex: <span class='([a-zA-Z_]+)'>(.*?)</span>
Replace: [span_\L$1("$2")]
Used this for spans embedded in strings

Then to undo any specific regex, e.g. ones not included in chat-dark.scss, that I would get a runtime error when trying to use, I used the following regex:
Regex: span_(SPAN_NAME_GOES_HERE)\("(.*)"\)
Replace: "<span class='$1'>$2</span>"
Or I would just manually revert the change back to default (I did this for a portion of them)

Then to solve the fact that constant expressions were needed on variable defines, I'd also revert those with this regex:
Regex: (VARIABLE_NAME_GOES_HERE) = span_([a-zA-Z_]+)\("(.*)"\)
Replace: $1 = "<span class='$2'>$3</span>

**Comment by Rohesie** [comment]
Any reason for these to be procs instead of macros?

**Comment by Watermelon914** [comment]
> Any reason for these to be procs instead of macros?

Ask ninja, he told me to make them into procs because they're easier to maintain. My intention was to originally make them defines.

Either way, if being procs prove to be a problem (e.g. proc overhead creating actual game lag), they can easily be converted into defines with this implementation.

**Comment by bobbahbrown** [comment]
call me crazy but it sounds like a lot of proc overhead for a reason i dont quite follow, the macro seems like the much less expensive option

**Comment by optimumtact** [comment]
what an exceptionally stupid idea

**Comment by LemonInTheDark** [comment]
I think it should be defines just to set a precedent, and since there's no cost to maintainability, but it genuinely barely matters.

Just like, do what you want yeah? if you want a direction just make them macros and I'll merge this tomorrow, but I'll merge it tomorrow anyway, so eh

**Comment by MrDoomBringer** [comment]
> what an exceptionally stupid idea

could you be more specific? It seems like multiple maintainers on your team support the author's original vision, and at least one other maintainer supports this in it's current implementation

**Comment by LemonInTheDark** [comment]
> 
> 
> > what an exceptionally stupid idea
> 
> could you be more specific? It seems like multiple maintainers on your team support the author's original vision, and at least one other maintainer supports this in it's current implementation

I don't disagree with oranges, he's right, but it's easier to merge this and deal with the conversions to defines later (they keep telling me that defines + spans are unstable for some reason) then let it sit. It's a waste, but I'm willing to take the hit for now, shouldn't be nearly as troublesome to convert once it's safe to do so

**Comment by optimumtact** [comment]
This absolutely should not have been merged, I expect and demand people have a higher standard of care when doing things like this.

**Pull request merged**
