### PR TITLE
new dead body mapping helper icons

### PR DESCRIPTION
**Pull request by axietheaxolotl**
## About The Pull Request

tin

image

## Why It's Good For The Game

image

## Changelog

:cl:
imageadd: new dead body spawner icons
/:cl:

### CODE REVIEW

**Comment by timothymtorres** [comment]
On behalf of mappers everywhere, this is greatly appreciated!  Thank you.

**Review by Imaginos16 — APPROVED** [review]
Nyehehe, hey Lois this is worse than that one time the traitor killed me in Space Station 13!

**Comment by Jolly-66** [comment]
Hey Lois remember that time I followed that clown out an airlock?

**Comment by ShizCalev** [comment]
Can you put a questionmark on the randomized one?

**Comment by Wallemations** [comment]
> Can you put a questionmark on the randomized one?

or put that one in the rainbow jumpsuit

**Pull request merged**
