### PR TITLE
Suspected status is now teal

### PR DESCRIPTION
**Pull request by Vincent983**
## About The Pull Request
recolors the suspected status to teal
## Why It's Good For The Game
now the security records color and the hud color match, which is good for consistency
image

## Changelog

:cl:
image: the security records suspected status is now teal instead of orange
/:cl:

### CODE REVIEW

**Comment by YakumoChen** [comment]
make it orange in the records? A Purple ! is the same symbol as Scientist jobs, which is a little confusing.

**Comment by Singul0** [comment]
Changing the sprite instead of the far more easy fix of changing the UI color. Truly, the spriter grindset at it's most optimum

**Comment by YakumoChen** [comment]
wouldn't say its a good fix if it adds a different UI discrepancy.

**Comment by Vincent983** [comment]
I didn't change it to orange in the records since incarcerated was ALSO orange

**Comment by AtomTheProphet** [comment]
Maybe it could be a nice, non-confusing lighter blue. Maybe something like 99CCDD

**Comment by Vincent983** [comment]
hows this look 
image

**Comment by AtomTheProphet** [comment]
> hows this look, ingame I think it doesn't really look good image

Maybe a soft yellow would be good. Try ffe37a, I guess?

**Comment by Vincent983** [comment]
how about this 
image

**Comment by AtomTheProphet** [comment]
Could work. Now that I think about it, perhaps blue isn't the best 

> how about this, teal image

I think it looks pretty good.

**Comment by jlsnow301** [comment]
Whichever color you decide upon, pls include photos in the pr description

**Comment by Vincent983** [comment]
done

**Pull request merged**
