### PR TITLE
Remember when I made GetAllContents() just a slight bit faster?

### PR DESCRIPTION
**Pull request by silicons**
## About The Pull Request

Well it turns out length() is only faster (https://canary.discordapp.com/channels/484170914754330625/487268744419344384/761161071972188180 and read up for a few screens of my bot spam) on empty list.

Don't get me wrong I did profile the original PR, it did perform better, but it *should* be even better with this change

## Why It's Good For The Game

why do i obsess over small performance increases

## Changelog
nothing major

### CODE REVIEW

**Comment by Timberpoes** [comment]
Our [guidelines](https://github.com/tgstation/tgstation/blob/master/.github/CONTRIBUTING.md) recently got updated with the following:
`Should you be optimizing a routine you must provide proof by way of profiling that your changes are faster.`

**Comment by optimumtact** [comment]
And no, dropping a link to a discord channel and telling us to just "read up" is not proof

**Comment by Rohesie** [comment]
I'm not following, `length()` is faster than `.len`, so why would this speed up things?

**Comment by Cyberboss** [comment]
`length()` vs `.len` is the epitome of coder bikeshed.

**Pull request closed without merging**
