### PR TITLE
Allows Signers to send COMSIG_MOB_SAY

### PR DESCRIPTION
**Pull request by DBGit42**
## About The Pull Request
By removing a conditional statement which prevented signers from sending a `COMSIG_MOB_SAY` signal (for some reason), this PR fixes a few things in one go:

- Sign language once again prints a notice that the signer raises or lowers their eyebrows for exclamations and questions respectively.
- Tonal indicators (sign/typing icons that depict eyebrows raising or lowering) are also working again.
- RuneChat is now punctuated the same as the chat box for Signers.

This PR is now atomic thanks to @MrMelbert.

## Why It's Good For The Game
Repairs intended functionality that broke a while ago. Adds a little flavor and spice to sign conversation again. Makes RuneChat properly register Signer punctuation.
signer
## Changelog
:cl: Danny Boy
fix: Fixed Signer eyebrow raising/lowering indicators and emotes
fix: Fixed Signer RuneChat punctuation
/:cl:

### CODE REVIEW

**Comment by DBGit42** [comment]
While I have simply disabled the tonal indicator code because I don't think it has worked since I first started playing SS13, I will happily look further into it if it's deemed necessary.

That being said, I don't think it would be a good feature even if it _did_ work.

**Review by MrMelbert — CHANGES_REQUESTED** [review]
We don't comment out broken code, if you have no intent on fixing in this PR either leave it or remove it, preferably the former

**Comment by MrMelbert** [comment]
Also, I don't believe this is the proper fix. 

It's not happening because this comsig is not sent, because for some silly reason we don't let sign language users respond to `COMSIG_MOB_SAY`. We should be fixing that instead

image

**Comment by DBGit42** [comment]
> Also, I don't believe this is the proper fix.
> 
> It's not happening because this comsig is not sent, because for some silly reason we don't let sign language users respond to `COMSIG_MOB_SAY`. We should be fixing that instead
> 
> image
> 
> Especially because I _think_ `say_quote` is supposed to be pure.

Understood, I will look further into this.

**Comment by DBGit42** [comment]
> It's not happening because this comsig is not sent, because for some silly reason we don't let sign language users respond to `COMSIG_MOB_SAY`. We should be fixing that instead

Yeah, this is literally the only thing that needed to be done to fix both the eyebrows and the tonal indicator. Wow. I appreciate you stopping a case of terrible coding and giving me a lesson to check signals too.

There's no apparent reason for signers not to send a say signal, so I simply took out that condition. sign_language.dm stays unmodified and functions fine. No apparent reason for the condition, no consequence to its removal in testing. A real mess turned into a one-line atomic change.

Brilliant.

**Review by MrMelbert — APPROVED** [review]
As far as I can tell this was done to prevent sign language users from having accents and lisps. But I think it's funny that a lizard sign language-r would lisp so I'm fine with this.

In any case, the offending procs should have been fixed by adding the trait check in the signal handlers, preventing the signal wholesale is silly.

**Comment by DBGit42** [comment]
> As far as I can tell this was done to prevent sign language users from having accents and lisps. But I think it's funny that a lizard sign language-r would lisp so I'm fine with this.
> 
> In any case, the offending procs should have been fixed by adding the trait check in the signal handlers, preventing the signal wholesale is silly.

I may look into this for my next PR and leave it up to people/maintainers to vote or debate on it. It does sound funny, but it could also take away from signing itself. Even so, it fixed more things than I was expecting so there's definitely a better way for that to be done as you siad.

**Pull request merged**
