### PR TITLE
Nerfs Beepsky Smash

### PR DESCRIPTION
**Pull request by Iamgoofball**
It got rather absurd with the new changes to chemistry speed processing, so I doubled the metabolize rate and halved the stun.

### CODE REVIEW

**Comment by Cheridan** [comment]
:no_entry_sign: :runner: :radio: :no_entry_sign:

**Comment by Fox-McCloud** [comment]
Personally, I'd remove the stun entirely and the weaken from neurotoxin (the drink); perhaps they would be a delayed knockout if they're in your system for long enough, instead, much like sleep toxin and chloral? Gives them some counterplay.

**Comment by paprka** [comment]
beepsky smash is a gimmick and only really meant to counter aliens since it's the only thing that really did counter aliens besides flamethrowers and lasers

**Comment by Dorsisdwarf** [comment]
Beepsky smash is for your hypospray along with mute toxin for that ghetto parapen, silly.

**Comment by paprka** [comment]
Well yeah it's good for that too but it's more fun out of syringe guns at that point, not hypos.

**Comment by Fox-McCloud** [comment]
Neurotoxin is better, IMO; once they get back up, they're going to be pretty screwed up; 1 unit is significantly  worse than a taser.

**Comment by Dorsisdwarf** [comment]
Yeah but I prefer beepsky because they get to watch as you casually drag them, upright, past everyone who doesn't suspect a thing.

**Pull request merged**
