### PR TITLE
Refactors glass bottle reagent spawning

### PR DESCRIPTION
**Pull request by Jordie0608**
Disease and reagent addition to bottles has been moved out of individual New()s and into the parent bottle's New() and created with a var. A side benefit of this is it's now easy for reagents or diseases to be added to a bottle when mapping.

The double-size robot versions of bottles were removed since they are no longer used anywhere.

A couple of vars that duplicated their parent's definition were removed.

### CODE REVIEW

**Comment by Jalleo** [comment]
:+1:

**Comment by WJohn** [comment]
:+1: x :100: 
Finally being able to edit contents of bottles. THANK YOU.

**Comment by Jordie0608** [comment]
Presently it's only for glass bottles, I'll see if I can change that however.

The bottles are filled to whatever amount 'spawned_amount' is set to, defaultly 30.

**Comment by Jordie0608** [comment]
Moving this to work with base reagent_container is going to need some weird stuff with lists I don't understand and changing all of food and drinks so I'll try and make that happen in a separate PR rather than stall this one.

**Pull request merged**
