### PR TITLE
Prevents SDQL2-query "SELECT /datum" from destroying the server

### PR DESCRIPTION
**Pull request by silicons**
SELECT needs a tick_check for sure.

### CODE REVIEW

**Comment by MrStonedOne** [comment]
Could have sworn i added one.

**Comment by kevinz000** [comment]
Imma add emergency stop button for it later.

**Comment by Haevacht** [comment]
I feel like there's a good story behind this one.

**Comment by MrStonedOne** [comment]
No on the stop button. it should be a generic running job system with a panel that shows all of them, their progress (if known) and stop/pause buttons.

**Comment by kevinz000** [comment]
implying i have any coding skill i don't know how sdql works but I know how to add a lagcheck.

**Comment by kevinz000** [comment]
you should do that instead of shitty ideas thread :^) do it for the admin team :D

**Comment by MrStonedOne** [comment]
I didn't do the shitty ideas thread, remie did. she's just being a butt and not putting it in seperate prs, rather making it in one big pr, so i put those 3 up to help her along

**Pull request merged**
