### PR TITLE
FIXES NEW TEMP SYSTEM

### PR DESCRIPTION
**Pull request by ghost**
WOOPS.

### CODE REVIEW

**Comment by Arianya** [comment]
WHY ARE WE SHOUTING

**Comment by MoreRobustThanYou** [comment]
I DUNNO

**Comment by Poojawa** [comment]
150 hours of testing.

**Review by AnturK — CHANGES_REQUESTED** [review]
.temperature
Please, you just removed that line.

**Review by AnturK — APPROVED** [review]

**Review by Cyberboss — APPROVED** [review]

**Pull request merged**
