### PR TITLE
Minor modernization of nanotrasen death commandos

### PR DESCRIPTION
**Pull request by kilkun**
:cl: kilkun
add: Adds a shielded deathsquad hardsuit. it has four charges and recharges after 15 seconds of not being shot (compared to the syndicate 3 charges and 20 second recharge rate)
tweak: All death commandos now spawn with this new hardsuit. The previous hardsuit was not removed.
/:cl:

Before this PR Syndicate SWAT technically were superior to Deathsquad due to having the shielded hardsuit that granted 3 free hits of no damage and the SAW barely doing less damage than a pulse rifle. This meant that 5 nuke ops with the right loadout would have no problem taking on 5 squaddies.

This isn't the only problem, as traitors, the station and generally everybody has slowly gotten more powerful over time, Deathsquad's equipment has remained relatively stagnant. We no longer play a game where 50 burn rifles with a shit ton of ammo and 80% reduction on two damage types is as threatening as it once was.

To rectify this and restore Deathsquad above Syndicate SWAT, their hardsuits now have energy shields that are slightly more effective than Syndicate energy shields. The result makes Deathsquad much more formidable, distinguishing them further from code red ERT, while not overtly changing too much about them, retaining the general effectiveness of their equipment.. The original plan for this PR also included pulse beams passing through energy shields and not being deflectable by martial arts, but I decided on ditching these for both balance and the lack of support in the code for these kinds of exceptions, without rewriting the relevant underlying procs.

It's a very simple change, and something that's long overdue. Deathsquad has been deprecated for a long while now and the hope that this very minor change will be the buff that they've sorely needed for some many months.

The old SWAT suit was not removed due to the existence of a tacticool locker that contains it that I'm fairly sure is space loot. Upon request I can purge it to prevent item bloat.

### CODE REVIEW

**Comment by Bawhoppen** [comment]
>deathsquad

>weak

>this is the supposed evidence to show that coders are out of touch

lmao x :100:

**Comment by GunHog** [comment]
I have been wanting to do this myself

**Comment by kilkun** [comment]
Deathsquad being barely better than red alert ERT (their guns do a teeny bit more damage and their armor is slightly better) and being slightly worse than Nuke Ops is frankly unacceptable.

The PR itself isn't evidence, but your response to it is one that I anticipated. So thank you for proving my point for me in the very first comment. Now I'd like to keep the rest of the PR on topic.

**Comment by Eaglendia** [comment]
if you think pulse rifles are any less threatening then ever you're an absolute madman

**Comment by kilkun** [comment]
That's why they didn't get a buff. To the average station goer, pulse rifles are extremely deadly. But so are revolvers (which do more damage anyways) and SAWs.

Not everything is about the crew, you know.

**Comment by optimumtact** [comment]
The fact we have to buff the deathsquad to be stronger than station antags is indicative of the power creep problem that we rail on about so much and everyone discounts us on.

sadly this will only perpetuate the cycle.

**Comment by Kromgar** [comment]
Yet the crew still wins against nuke squad 50% of the time

**Comment by optimumtact** [comment]
in fact at this point you may as well just remove them.

**Comment by Kromgar** [comment]
>Removing deathsquad
>iconic part of the game

REEEEEEEEEE

**Comment by kilkun** [comment]
You will get no argument from me that the power creep is ridiculous. I've always discounted coders on the fact that they themselves perpetuate the power creep. You are the ones making the game afterall.

The only people who argue that the power creep doesn't exist/is good are the people who directly benefit from it and don't want to admit that everything is getting deadlier and even more weaponized. Like Daisy Holmes and her space vines/lubed tomatoes that teleport people.

>You might as well remove them at this point

This was commonly thrown about in my last attempt to buff deathsquad, but it's something that I can't agree with.

**Comment by optimumtact** [comment]
anyway it's fairly safe to remove the old swat suit and just purge the reference to it.

**Comment by Bawhoppen** [comment]
do not remove it

**Comment by optimumtact** [comment]
Why not?

**Comment by Bawhoppen** [comment]
diversity, but then again if its the same exact sprite I guess it doesn't matter

**Comment by GunHog** [comment]
Well, you have a pulse rifle just sitting out in space. Maybe toss the suit into the loot table? (So you get the suit OR a pulse rifle)

**Comment by KorPhaeron** [comment]
It really doesnt matter what you give deathsquad. They're already so overpowered admins won't spawn them outside of the shuttle dock.

**Pull request merged**
