### PR TITLE
Brings back better bombmaking.

### PR DESCRIPTION
**Pull request by Iamgoofball**
Reverts tgstation/tgstation#27894

Lame as hell. Dumb nerf. Most definitely not good for /tg/.

### CODE REVIEW

**Comment by kevinz000** [comment]
:+1: I want toxins made less of a 5 minute maxcap joke but this isn't the right way to do it.

**Comment by kevinz000** [comment]
Also even with this nerf it was still a 5 minute destroy station joke.

**Comment by GunHog** [comment]
These devices are useful for cleaning tanks and siphoning rooms as well!

**Review by Cyberboss — APPROVED** [review]

**Comment by GuyonBroadway** [comment]
@kevinz000 People will always find a way to make five min maxcaps, unless you make plasma burn _Sloooow like treacle_ people will always find the quickest mix.

You'd need to re-do bombs from the ground up basically.

**Comment by ExcessiveUseOfCobblestone** [comment]
you can't make 5 minute max caps if we remove toxins :^)

**Comment by YakumoChen** [comment]
@GuyonBroadway You don't even need the mix tank to make 5min maxcaps, just a heater.

**Comment by CPTANT** [comment]
It was a dumb change from the start and nerfed almost everything except bomb making.

**Comment by LaharlMontogmmery** [comment]
How the change was even introduced was controversial. Hell, lzi closed the revert as well afterward when the discussion died down.

**Comment by Robustin** [comment]
This has absolutely 0 balance implications. Rapid maxcap production never involved using the pumps like that.

All it means is that we can make Mining NUKES again, and I love those massive mining bombs.

**Comment by Supermichael777** [comment]
does this make those hilarious supercooled canisters bombs possible again?

what was the record for those anyway;
i recall seeing 40,80,160 or something goofy like that

**Comment by CPTANT** [comment]
@Supermichael777 

Those were already possible without this. You make them with superheated freon and a cooled burnmix.

**Pull request merged**
