### PR TITLE
fixes a number of typographical errors within the /tg/station13 codebase

### PR DESCRIPTION
**Pull request by MrDoomBringer**
description:
fixes typos
why its good:
typo bad!!
changelog:
non player facing not required

### CODE REVIEW

**Comment by LemonInTheDark** [comment]
Dear god he's right

**Comment by Ghilker** [comment]
I never checked on what a pr was so fast

**Comment by Jared-Fogle** [comment]
NOOOO! HELP ME!!

**Review by Mothblocks — APPROVED** [review]

**Review by SpaceManiac — APPROVED** [review]

**Review by itseasytosee — APPROVED** [review]

**Comment by optimumtact** [comment]
Your PR has been closed due to having a misleading or incorrect title, adjust the title and ping me to reopen it or make a new PR with a properly descriptive title and body content.

**Comment by MrDoomBringer** [comment]
I hope you're proud of yourselves. You've driven away another customer! It's baffling, I tell you! Your deep rooted lack of self-control only fosters failure in every endeavor we undertake! I mean, it's always one step forward and two steps back! Why? Don't you see the example I try to set for you?

**Pull request merged**
