### PR TITLE
Feat: Updated Syndie Shuttle

### PR DESCRIPTION
**Pull request by TrashDoxx**
## About The Pull Request
Hey-hey! I'm a maptainer at SS220, not too long ago we added a TG to our stack of servers and to start getting into your development we upgraded one of the locations a bit. This is just the beginning and not the most serious work.

And the screenshot, of course:
Just-A-Shuttle

## Why It's Good For The Game
New shuttle is a little more classy & austere, I think.

## Changelog

:cl: TrashDoxx & He11Force
add: Updated nukie shuttle!
/:cl:

### CODE REVIEW

**Comment by Sealed101** [comment]
concerning amounts of airlocks used (zero)

**Comment by TrashDoxx** [comment]
> concerning amounts of airlocks used (zero)

We stick to open spaces and minimal decals. We often use firelocks to visually separate areas but here it would be inappropriate, I think. I would be glad if you could suggest something as a substitute!

**Comment by Sealed101** [comment]
doors on the nukie shuttle serve as an additional stall in case someone manages to break into the shuttle, as well as a potential trap via shocking them. they also help with containing breaches whenever they occur. though operatives usually don't suffer from them as much, they sometimes still need the shuttle to not be spaced, especially with modsuits' EVA capabilities and deploy times in mind. imo some airlocks wouldn't hurt at all.

then again im not a maptainer, they might agree with your idea of open spacing.

**Comment by TrashDoxx** [comment]
> doors on the nukie shuttle serve as an additional stall in case someone manages to break into the shuttle, as well as a potential trap via shocking them...

Thanks for the helpful review. I'm a fairly inexperienced TG player and this sounds pretty interesting, but I'll wait to hear back from maptainers for now.

**Comment by JohnFulpWillard** [comment]
> doors on the nukie shuttle serve as an additional stall in case someone manages to break into the shuttle, as well as a potential trap via shocking them.

Shocking doors on a shuttle do nothing as they don’t have any electricity to shock you with.

**Comment by axietheaxolotl** [comment]
somehow, this looks more barren then the old interceptor.

**Comment by MrDoomBringer** [comment]
I don't really see a good justification to make this change. You've made the shuttle take up more space while at the same time not making great use of the newly-expanded interior.

> We stick to open spaces and minimal decals. 

This is objectively wrong. Please look at the white ships in our codebase before making these kinds of claims. Very few have any large open spaces, because like the infiltrator they're designed for a small crew.  

> I'll wait to hear back from maptainers for now.

Please don't hand-wave away contributors who are more experienced than you - you don't need a maptainer to tell you that airlocks are important for keeping atmos inside the shuttle, and gameplay-wise important for slowing the advance of crew trying to hijack it.

**Comment by Serxule** [comment]
imo this doesnt fit for normal nukies, looks more like a shuttle thatd be somewhere like voidcrew

**Comment by Son-of-Space** [comment]
All this seems to do is make the space larger without contributing anything to the actual function of the ship. I would have to say "Nay" on this one. I, in fact, prefer a bit of grunge to the syndicate aesthetic that we have with our current design.

I am not a "maptainer" but I have contributed significantly to TG's maps. If you still want to change the syndicate shuttle, you would likely get my buy-in by reducing the space that you're using and keeping that original syndicate aesthetic.

**Comment by TrashDoxx** [comment]
Okay, I'll make a new version for further discussion.

**Comment by wraith-54321** [comment]
I would say some airlocks are needed, as was already said they help slow down someone breaking into the shuttle that can be VERY important in some cases.

**Comment by LemonInTheDark** [comment]
> We stick to open spaces and minimal decals. We often use firelocks to visually separate areas but here it would be inappropriate, I think. I would be glad if you could suggest something as a substitute!
 
 Done on properly open spaces, this can be very annoying to simulate in terms of atmos. Please don't follow this pattern over large spaces

**Comment by Cheshify** [comment]
This ship has a lot of open space that doesn't need to exist/doesn't serve any tangible purpose. I would seriously suggest cutting down any open spaces so you only have one or two tiles to walk on.

**Comment by TrashDoxx** [comment]
This may seem like an element of comedy, but I was left without a laptop when I decided to do a new version. It's not the first time it's happened to me.

Anyway, I've asked my mate to prepare a couple of update options, and they're ready now, so I'll get onto them as soon as I get a computer and sort out the current projects for the other builds.

In the meantime, I'll close PR so those awful emoji don't stab me right in the heart.

I guess I'll see you soon.

**Comment by TrashDoxx** [comment]
Ehh.

**Pull request closed without merging**
