### PR TITLE
Updates the Reactive Armor sprites

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request
Tried to keep it as close to the original as possible, but... you know. Updated.
Modernized, even.

**NEW COLOR PALETTE**
dreamseeker_hTdvDAjIYy

_Also, fun fact, the side states weren't originally animated. They were a flat blue._
_AND one of the 'off' side states was... still that flat blue. As if it was on._

## Why It's Good For The Game
image

## Changelog

:cl:
image: Resprites the Reactive Anomaly Armor
/:cl:

### CODE REVIEW

**Comment by OrionTheFox** [comment]
woah hold on its trying to wipe the suits files i did something wrong

**Comment by OrionTheFox** [comment]
IconDiffBot is just having a seizure. Downloaded the files, the ONLY changes in them are to the two states, reactive and reactiveoff

**Comment by CRITAWAKETS** [comment]
The removal of black outlines and improvements to the shading are good, but it really needs more contrast to pop out, try and experiment with highlight colors to get the shiny metallic effect like on the old sprite!

**Comment by EricZilla** [comment]
Huge improvement!

**Comment by SomeoneYouProbablyKnow** [comment]
It kinda look like one of those cheap plastic laser tag vests. It used to look like that is well but the sprite was too cooked for anyone to notice. It for sure can benefit from a touch up.

But like if you're changing it feel free to go wild, i'd try more contrast and maybe more metalic color combinations as well as just sharper shapes instead of softer ones. It's supposed to be a high tech prototype made by an insane immovable rod suplexing scientist.

**Comment by OrionTheFox** [comment]
> But like if you're changing it feel free to go wild, i'd try more contrast and maybe more metalic color combinations as well as just sharper shapes instead of softer ones. It's supposed to be a high tech prototype made by an insane immovable rod suplexing scientist.

Yeah, I'll definitely come back and up the contrast - it's way too soft even for me still now that I see it a while later.
Gonna leave it Ready for spritetainers tho so they can give feedback

**Comment by Fikou** [comment]
what if the energy core thingy in the middle was colored differently depending on what kind of core is in it which both looks cool and provides combat info at first glance instead of every armor looking the same

**Review by Wallemations — CHANGES_REQUESTED** [review]
I agree that you might want to up the contrast on the outlines
Not going full black like before, but definitely a little darker than you have now.

**Comment by deathrobotpunch** [comment]
are you changing the on character sprites too?

**Comment by OrionTheFox** [comment]
> what if the energy core thingy in the middle was colored differently depending on what kind of core is in it which both looks cool and provides combat info at first glance instead of every armor looking the same

I wanted to look into that but it'd involve some code changes too - either individual animations for each and something to set which one to use, or a greyscale bit that'd take some tinkering to get working. Out of my knowledge-set to do, at least, in a reasonable timeframe. Figure that once the sprites are less ugly it'd be easier to tweak them like that though!

> are you changing the on character sprites too?

Yeah, the gif in the PR body is on character sprites - but the Obj and Mob sprites both use the same exact scale for the front-facing so I don't mind clarifying lol

**Comment by Exester509** [comment]
> > what if the energy core thingy in the middle was colored differently depending on what kind of core is in it which both looks cool and provides combat info at first glance instead of every armor looking the same
> 
> I wanted to look into that but it'd involve some code changes too - either individual animations for each and something to set which one to use, or a greyscale bit that'd take some tinkering to get working. Out of my knowledge-set to do, at least, in a reasonable timeframe. Figure that once the sprites are less ugly it'd be easier to tweak them like that though!

You'd just have to edit the individual icon_states for the individual armor types, since they're not modular. They're different objects altogether.

**Comment by OrionTheFox** [comment]
> 
> You'd just have to edit the individual icon_states for the individual armor types, since they're not modular. They're different objects altogether.

True, but having a unique iconstate for each one would be a _lot_ of animated icons to add...
My working concept is:
- Base Vest icon
- Generic Core icon / GAGS core?
- Color overlay on core / GAGS

But that'll take a while and, honestly, I'm feeling a bit burnt out on this. I have really short bursts of motivation to work off LOL. Would rather the icon as-is be updated and any larger-scale changes like that happen to the updated one later.

**Comment by optimumtact** [comment]
Okay but do you have a full dmi for the soul sucker?

**Comment by LSommers** [comment]
"Tried to keep it as close to the original as possible, but... you know. Updated."

Thank you for this mindset.
Also the Soul Sucker is comical, love it.

**Pull request merged**
