### PR TITLE
Adds Changeling Swap Forms Ability

### PR DESCRIPTION
**Pull request by Ikarrus**
- Chemical Cost: 40
- DNA Cost: 2
- Requires at least an aggressive grab, and 2 seconds without interruption (Such as the target walking away)
- Both subjects will slightly jitter during the brief process. Otherwise, no messages are sent until it's finished
- After two seconds if the changeling hasn't been interrupted, they swap minds
- DNA is also exchanged; The changeling will lose the old one and gain the new one

### CODE REVIEW

**Comment by Kromgar** [comment]
Does this replace transform sting?

**Comment by Ikarrus** [comment]
Do you want it to @Kromgar ?

**Comment by Incoming5643** [comment]
please don't replace transformation sting.

**Comment by Kromgar** [comment]
Im just tired of transform sting spam. With this you could cahnge to an alternate identity double grab some sap table him double grab again and then swap with em. You can setup people for being lings and being JUSTLY murdered

**Comment by Cebasiz** [comment]
transform sting is cancer because it's never used for anything but mekhistation13 or other totally pointless shenanigans

in fact most of the stings are basically garbage, combatsteroid armbladeling is really the only way to play and it fucking sucks. 

i think you could make a decent game mode out of ling but nobody even bothers with it these days.

anyway yeah it's a nice addition no reason to object

**Comment by Anonus** [comment]
What happens if the target is dead, do you have to regenerate?

**Comment by Ikarrus** [comment]
yes

**Comment by SconesC** [comment]
...It gives no message?

So I could casually table the HoS, mindswap him, and he would just be a screaming maniac going on about how I'm a ling? I think this is a funny idea, but the timer just makes me think of the old bullshit stuff like Parasting that just made anybody worth their salt never want to stand adjacent to someone.

**Comment by Ikarrus** [comment]
Well you guys are free to make suggestions on the pricing and strength of the ability. This is all just guessing with theory right now until we can actually see it in game.

**Comment by Dorsisdwarf** [comment]
The bodyswap should destroy loyalty implants, so there's at least one tell for everyone else.

**Comment by veganzombeh** [comment]
If your target is dead and ghosted, what happens? Would they have to re-enter corpse?

**Comment by Ikarrus** [comment]
They get forced in to their new body

**Comment by Dorsisdwarf** [comment]
This is also a neat way to rez lings who were burning chems when they died and cant regenerate

**Comment by Anonus** [comment]
Why does regenerate even cost chemicals it's still so dumb

**Comment by Cebasiz** [comment]
to balance spam of extremely high chemical abilities i'd guess

it's relatively trivial to keep enough for revive especially with engorged chemical glands anyway.

**Comment by Robustin** [comment]
The era of table-lings has begun.

On a serious note this seems fine. 20% of your genome for a super-niche ability that will probably be used effectively like twice a month or so. The purpose would be to gain access to implanted roles (though this really isn't hard, kill a sec officer, put on all their stupid bloody stuff, mess up your hair as a bonus, walk to brig and say you were cloned and need a new implant... the real officer is dead/missing so the stories will almost always add up) or a heightened access/restricted items/etc. 

You can't use this casually on security, after the swap you're the one on a table and they can freely murder you at that point if they know how to quick-table, otherwise they'll go screaming on radio and AI/Sec will see you two jittering and metadunk you so hard that the hivemind will feel it. It would require some pretty ridiculous setup to actually work on sec, the nature of the ability means you're always going to be at a disadvantage after using it. Even if you manage to get up in your new sec body and convince the crew the other guy is full of it, you're going to have a cloud of suspicion over you. I've found that the crew has gotten pretty good at solving swapcrimes since the induction of summon magic/apprentices made it pretty rampant. Again, it's much simpler, less risky, and no genome cost just to absorb an officer and play the "cloned" card. 

Casual swapping is the biggest risk for this ability. There will be lings that will just run around tabling and swapping people and then running off, but as I said before this isn't as crippling as mass-transform spam and the crew has gotten pretty good at tracking down a mindswapper. 

As for transform sting, keep it, it has legitimate uses and lings don't need to become even more bland/vanilla/traitors without guns than they already are. It takes an unprecedented 3 genomes to learn, it's still instant and even more obvious than ever, just look at your damn screen and you'll have a very good idea of who transformed you, what they were wearing, etc... and it's really not hard to track and kill them with the AI's help. While it may seem like le epic prank to some, it's a very useful tactic for veiling ling activity. Distributing disabilities like this is a bit crazy but that takes planning, usually some level of teamwork, and genetics can still cure disabilities just as fast as a ling can distribute them, and even blinded you should be able to sprint off toward a public place and PDA the AI with the description of the ling who messed you up.

**Comment by SconesC** [comment]
Good thing ling is disabled

**Pull request merged**
