### PR TITLE
Makes carps not lose track of who they're following if vision gets obstructed

### PR DESCRIPTION
**Pull request by Watermelon914**
## About The Pull Request

Carps would constantly lose track of who they're following if they take a path that obstructs their vision to reach who they're following, making them very easy to lose. This helps prevent that.

## Why It's Good For The Game

Less buggy carp AI

## Changelog
:cl:
fix: Fixed carps losing track of who they're following if they take a path that obstructs their vision
/:cl:

### CODE REVIEW

**Comment by LemonInTheDark** [comment]
Isn't this intended? if you can't see it for long enough, just give up

**Comment by Capsandi** [comment]
I guess you could say they have the memory of a space goldfish

**Comment by Watermelon914** [comment]
> Isn't this intended? if you can't see it for long enough, just give up

It's more of a problem with them going around 1 wall and then they stop following you because their vision was obstructed for 1 second because they took a path that obstructs their vision.

**Comment by Rohesie** [comment]
Not exactly a fix, it's more closer to a rebalance.

**Comment by Watermelon914** [comment]
> Not exactly a fix, it's more closer to a rebalance.

I'd say it's an oversight which is why I flagged it up as a fix since it was never supposed to lose target when taking a path to the target, but I guess it could be considered both.

**Pull request merged**
