### PR TITLE
You can no longer equip pet collars on humans

### PR DESCRIPTION
**Pull request by optimumtact**
:cl: oranges
del: Pet collars can no longer be equipped on humans
/:cl:

### CODE REVIEW

**Comment by epicmemename** [comment]
BASED oranges

**Comment by CitrusGender** [comment]
thank you!

**Comment by Barhandar** [comment]
Bagel residents'll hate this!

**Comment by Anonmare** [comment]
So these are oranges' alts...

**Comment by Ordonis** [comment]
Thanks lemonlime

**Comment by Wilchenx** [comment]
image

**Comment by YakumoChen** [comment]
Oranges will host vore themed extended rounds but wearable collars are too far?

**Comment by pigeonsk** [comment]
Where's the popcorn

**Comment by kevinz000** [comment]
@pigeonsk here 🍿

**Comment by epicmemename** [comment]
cat apologists are absolutely seething from this pr

**Comment by optimumtact** [comment]
and I can give myself approval

**Comment by Xhuis** [comment]
big nut

**Comment by YakumoChen** [comment]
This is not very funny, even if I don't care for the or content itself and only further demonstrates why github and coderbus is toxic to use

**Comment by Shadowflame909** [comment]
Content serves as erp fetishes!!!!1!!

**Comment by cyclowns** [comment]
funny how you can tell who likes catpeople based on who thumbs downed this PR

**Comment by Xhuis** [comment]
god I love tribalism

**Pull request merged**
