### PR TITLE
Makes the tech storage more secure against greytiders (and give some love to the Icebox tech storage)

### PR DESCRIPTION
**Pull request by PestoVerde322**
## About The Pull Request

Adds R-walls around all of the tech storages on all the maps to make them less greytidable, since as it's now, any assistant with a welding protection and a welder with a wrench can just steal anything within the tech storage, the only REAL weak part now is the front door.

Also adds some decor to the Icebox's tech storage, making it no longer as drab, alongside minor changes in all the tech storages like a part mat vendor in the delta tech storage.

iceboxTSbutbetter

## Why It's Good For The Game

Greytide bad, Security good, small tweaks and more decorations better

## Changelog

:cl:
add: Made the tech storage on all the maps more secure to compensate the fact that they're rushed within 5 minutes to get absolutely looted
add: The tech storage in Icebox now have a proper floor with a proper decoration
add: Added a Part Mat vendor in Delta's tech storage
/:cl:

### CODE REVIEW

**Comment by Pickle-Coding** [comment]
It always sucks that the entire techg storage gets looted and destroyed by the time I set the engine.

The reinforced walls should give me some time to finish the engine then go stab their eyes with a screwdriver before they can get in.

**Comment by Shadowflame909** [comment]
What's the point of secure tech storage if regular tech storage is just as secure?

Just move the more important boards in there!

**Comment by necromanceranne** [comment]
> What's the point of secure tech storage if regular tech storage is just as secure?

It's partially outside, behind additional walls and has a reinforced vault door?

**Comment by D4C-420** [comment]
Regular tech storage does not have anything in it that really justifies it having r walls. Besides people go only really in there to steal the insulated gloves or to get a chem machine board. 
This also makes stealing boards for antagonist objectives harder (not that It was that hard before but still).

**Pull request closed without merging**
