### PR TITLE
Astronaut box now gets a void jetpack

### PR DESCRIPTION
**Pull request by ghost**
## Why It's Good For The Game
Curators need to break into EVA for a jetpack for their space adventure shenanigans, this resolves that

## Changelog
:cl:
tweak: The curator's First Man on the Moon trophy now gets a void jetpack
/:cl:

### CODE REVIEW

**Comment by loserXD** [comment]
that's not a feature

**Comment by OverlyGeneric** [comment]
> that's not a feature

it is now

**Comment by FantasticFwoosh** [comment]
This is not what i wanted when i created the themed kit, since you can source your own jetpack from station materials in the crafting screen or ask permission for one from EVA (unlikely without generousity or skillful theft), it'll definitely skewer the balance regarding the other relatively soft power of the objects inside those like the braveheart sword by comparison or the regular tomb raider gear.

If you want to proceed to PR, im just outlaying my opinion when i was going into this gear-pack system, that's all.

**Comment by optimumtact** [comment]
Finally a sensible post from fwoosh

**Pull request closed without merging**
