### PR TITLE
Renames the Cleanable/ folder to cleanable/

### PR DESCRIPTION
**Pull request by coiax**

### CODE REVIEW

**Comment by BeeSting12** [comment]
do you have to rename everything that references this file too? new to this so thats why I'm asking

**Comment by coiax** [comment]
Oh yeah

**Comment by Cyberboss** [comment]
As a warning, windows gets fucky with git when all you do is change path capitalization

**Comment by RemieRichards** [comment]
I will murder you for this.
@Cyberboss is 100% correct and you will pay with your soul and the soul of your firstborn.

**Pull request merged**
