### PR TITLE
Changes Oddysseus chemical synth to be dependent on can_synth instead of...

### PR DESCRIPTION
**Pull request by alexjrob**
... the arbitrary reagent_state value.

### CODE REVIEW

**Comment by RemieRichards** [comment]
is this not a buff then? since it can now create non liquid reagents AS WELL as the liquid ones.

**Comment by lolnon** [comment]
Everyone I asked in the IRC thinks it's fine to be able to synth every chemical.

I'm open to suggestions.

**Comment by Miauw62** [comment]
Merge conflicts, I'll merge this once they're resolved since people don't seem to object.

**Comment by Cheridan** [comment]
Just manual merge it

**Pull request closed without merging**
