### PR TITLE
Removes the instagib from shield gens

### PR DESCRIPTION
**Pull request by anconfuzedrock**
I was concerned when I realised this existed, it seems people are very against instagibs nowadays considering when I saw people be gibbed by it in game and from recent opposition to a pr that allows hydro trays to compost people. I tested myself and lmao holy fuck this should not be as good as it is for murderbone I just put it on two sides of a hallway through some windows and people asplode with one click it's not fair at all

### CODE REVIEW

**Comment by 81Denton** [comment]
just don't stand between two shield gens

**Comment by Time-Green** [comment]
This happened to me a really long time ago and just now I know what really happened

**Comment by Ratvar** [comment]
Maybe you should fix shield generators working through opaque objects instead. 
Or remove bombs, chemistry, botany and spearnades for uncounterable (if you do not rush them roundstart, like you can rush engineering) gibs.
Choooooooose pleeeeeeeease

**Comment by dr-bee** [comment]
This is a good change, Ive seen multiple people set up 2 shield gens in maint and then depopulate the station with an e-bow by dragging people to it. Instagibs are lame.

**Comment by anconfuzedrock** [comment]
how the fuck are so many people opposed to the most unbalanced shit in the game lmao, I guess I'll have to go murderbone with it like durkel with uranium walls until it gets nerfed. Stop being a fucking retard purple man, you know you're being a tard as well as I do. This is one pr to fix one specific thing that is undeniably more egregious than all of what's listed. what if I told you I actually hate ied spears? This pr has similar opposition to another pr going on at the same time as this one, #41791, which is disliked because it adds a new way to gib someone. This is ridiculous.

**Comment by Ratvar** [comment]
Why don't you start with IEDs instead of limited machinery? They are much worse, and you agree they are at least bad.
Also, you should know by now you write like something's off in your head, so why wonder people dislike your work even if it makes sense? Like, try to format PR's body. Or something.

**Comment by HideAndSeekLOGIC** [comment]
>just don't stand between two shield gens

Based

**Comment by AdamElTablawy** [comment]
It does require some setup and it's about as tactically effective as dragging people to the crematorium and burning them one by one.

Personally, i'm more against it because it makes it *really* easy for xenobiologists to speed up the whole process of getting headslugs and such.

**Comment by 81Denton** [comment]
Let me elaborate on "just don't stand between two shield gens".
I'm fine with them gibbing people because
1) They need to be set up first. This means dragging this very obvious machine across the station, then a second one, then wiring both of them up to a power source. This makes it really hard to get these anywhere unnoticed.
2) They can't be deconstructed or printed, you can only get them on station or from cargo. You can't just print some boards and sneak over; you'll again have to drag them across the station.

Instead of completely removing gibbing, there is an easy way to make them less frustrating: Have them charge up for half a second or so before activating, while emitting a really obvious sound (like a high-pitched EEEEE). That way you can still kill people with them, but they will an opportunity to react.

**Comment by kriskog** [comment]
Why do we have to remove everything that's fun? Yes, some things have devastating effects but that is also what makes them fun. These are barely used apart from gibbing gold mobs in xenobio, and due to the things Denton pointed out above you do have to take pretty big risks in using them for anything else.

**Comment by HideAndSeekLOGIC** [comment]
@AdamElTablawy how exactly does it make it easier?

@81Denton not saying I disagree with 'just don't stand', just saying it layed out the truth on a nice, compact silver platter.

I'd say more, but you already did a fatality on this PR.

**Comment by dr-bee** [comment]
> 
> 
> Why do we have to remove everything that's fun? Yes, some things have devastating effects but that is also what makes them fun. These are barely used apart from gibbing gold mobs in xenobio, and due to the things Denton pointed out above you do have to take pretty big risks in using them for anything else.

What part of being instantly killed from 1 stun is fun? The main difference between these emitters and the crematorium is that the crematorium is 1. Unbuildable. 2. In a particular location on the station and is typically out of the way and 3. cant be moved around and hidden near a high traffic area, or activated through fucking walls.

I would rather the shield just violently throw you in a direction and do brute damage, it is more reasonable. Instant kills in any sense are lame.

I once linked 2 of these so they would activate in the middle of the hallway through 2 walls and waited in maint with thermals to activate them, ended up killing a third of the station with it. Instant kills need to go, but portable instant kills REALLY need to go.

**Comment by Anonmare** [comment]
FYI this and shuttle slamming is one of only two ways that a cyborg can gib anything, like zombies and changelings - And the latter are especially annoying for destroying anything that can gib them


Plus they're piss easy to deal with, literally cut the power cable to them and they become as flaccid and impotent as a murderboner dosed up on Pax.

**Comment by anconfuzedrock** [comment]
Excuse me? I've literally never died to a shield gen. I know some people who have, though. https://cdn.discordapp.com/attachments/342725945095880716/521364170826842143/unknown.png

**Comment by improvedname** [comment]
well to be fair. you were using a ebow, and its pretty much the equalavent of ebow + esword/ Ebow + cremator

**Comment by zamolxius** [comment]
death is cheap in space,  and that is not a problem

**Comment by ExcessiveUseOfCobblestone** [comment]
If you use master to PR you're going to have a bad time in the future.

Also if you remove IED spears I won't shed a tear.

**Comment by anconfuzedrock** [comment]
believe me cobby, I do it all the time.

**Comment by improvedname** [comment]
When you are gonna remove the cremator from removing you from the round, atleast the shield gens leave a head.

And sure they might have dead but uou were ebowing them and throwing them in the middle might aswell cremate people at that point, this is a grudge pr

**Comment by Shadowflame909** [comment]
What's the difference between this and Stun + Supermatter Shard or Stun + Gibber/Crematorium

I just find it funny that you'd take the time to pick out this one and go "There's a problem with instant gib ree" without thinking about how many items can cause a similar chain of events, albeit faster.

Instant Death in this game is very common, and I feel like making dying harder would currently go against the standards of the maintainers, as stated in previous PRs.

**Comment by imsxz** [comment]
@Shadowflame909 i can set up shield gen gibber in any room i want, and theres plenty of spares if mine gets borked.

**Comment by Shadowflame909** [comment]
> 
> 
> @Shadowflame909 i can set up shield gen gibber in any room i want, and theres plenty of spares if mine gets borked.

I don't quite understand how this undermines my argument.  The death trap shown in the previous image requires both shield gens to be powered, and across the room. It's easy to depower the other one, break and remove as you have to buy more and lastly since we're all getting speed nerfed. This gimmick will be entirely much harder to pull off as people will see it a mile away.

It'd be much easier to just use space lube + a super matter shard.

**Comment by AdamElTablawy** [comment]
true, but it still requires effort and setup enough that it's basically like constructing a one-way quantum pad into space that you ebow and drag people onto, killing them permanently, or something of that nature.

it's a guaranteed kill but takes a while to set up and honestly, it's too gimmicky to be a meta

again the main 'problem' would be something like the xenobiologists spawning all their gold slime cores between two shield gens and then instantly activating them to gib anything not a headslug for faster work, but that's basically a non-issue as well.

**Comment by GuyonBroadway** [comment]
This PR counts as a sci nerf therefore anyone who argues against it is a salty sci main.

The harder they argue the saltier they are and the faster oranges merges this on principle of merging any and all sci nerfs.

**Comment by kevinz000** [comment]
Science main here this PR sucks!

**Comment by GuyonBroadway** [comment]
I'd make a joke about maining sci being kevinz fetish but I'll actually bet he does roll xenobio on multiple rounds to have it off with slimepeople.

**Comment by HideAndSeekLOGIC** [comment]
I saw what I think was kevinz's deviant art account some time ago (at least, his profile pic is from there) and can confirm, he does indeed like to get it on with slimepeople.

**Comment by ExcessiveUseOfCobblestone** [comment]
Having it not affect mobs at all who are in the path is not modernization though. This PR wouldn't be so bad if it actually replaced the gibbing functionality with say throwing the individual back.

That said, I've seen very few (like I could count on one hand few) shield gen murderbones since i've played here. Just having them anywhere but xenobio puts you on people's radar.

If it doesn't already you can change the args of gib to retain organs, specifically the brain, to make it less of a GG. Otherwise i'm not really sold.

**Comment by improvedname** [comment]
it just gibs your body, and leaves all your bodyparts on the ground including your head which can be instantly cloned without effort.

**Comment by ExcessiveUseOfCobblestone** [comment]
Figured but didn't want to lookup the gib proc l0l.

**Pull request closed without merging**
