### PR TITLE
R[D]evamp - Secret Door

### PR DESCRIPTION
**Pull request by axietheaxolotl**
## About The Pull Request

Adds a new RD labcoat, and resprites the RD's turtleneck and skirtleneck. Oh, and a beret. Because the RD had no unique headwear.

To make the outfit look better, the RD now also has black gloves and jackboots. These are incredibly minor changes, but they must be mentioned.

image

Soundtrack for this PR is: [Humbug, Arctic Monkeys](https://youtube.com/playlist?list=PLDCdjwiC90TEjasEPkoqisZw84QS0zTF1)

Stuff in the pipeline: Locker resprite, Non-Wallening Syndiesthetics.
## Why It's Good For The Game

New sprites = good, and the new coat helps differentiate the RD from other scientists? I think that's a good enough excuse, yeah. The same applies to the beret.

Oh, and the boots and gloves make the outfit look better.
## Changelog
:cl: axietheaxolotl
add: Brand-new RD labcoat and beret. Along with a pair of black gloves and a set of jackboots.
imageadd: Resprites RD turtleneck/skirtleneck.
/:cl:

(BRING BACK TWEAK PLEASE)

### CODE REVIEW

**Comment by LemonInTheDark** [comment]
I hate beret posters

**Comment by EuclidianGeometer** [comment]
berets are good

**Comment by LemonInTheDark** [comment]
no really we use them everywhere and it's just really boring and samey. makes me sad

**Comment by Shadowflame909** [comment]
Needs a funny in universe CL like nanotrasen has implemented bluespace particles into cans of monkey energy so they no longer overflow upon opening!

**Comment by Sealed101** [comment]
security and science berets were a long standing clothing item, all the other departments were filled in like a year back at most, devaluing the og berets. 

these sprites look great. bit of a shame that most RD lawyers will ditch that lavish labcoat in favor of their anomaly armor

**Comment by Shadowflame909** [comment]
Looks good. I like the stripes!

**Comment by GuillaumePrata** [comment]
> Oh, and a beret. Because the RD had no unique headwear.

> Oh, and the boots and gloves make the outfit look better.

Amazing, the boss of the science department dresses like a purple officer.

**Comment by OneAsianTortoise** [comment]
#63164

Is giving every command jackboots your plan

**Comment by improvedname** [comment]
they are turning my tactical turtleneck into a tactical pj

**Comment by axietheaxolotl** [comment]
>Amazing, the boss of the science department dresses like a purple officer.

Breaking news, gloves and boots now restricted to military positions. Civilians who dare wear them now all caught up in scandals of stolen valour.

**Comment by MMMiracles** [comment]
please stop adding berets the french might start to think this is a safe space

**Comment by GuillaumePrata** [comment]
> security and science berets were a long standing clothing item, all the other departments were filled in like a year back at most, devaluing the og berets.

Not really a long standing clothing item, science berets were added in Oct/2020 #54255 and then everyone else got berets when they got gagsified in Jul/2021#59536

It is only 8 months between both PRs. Science berets are not OG, sec and mime berets are.
Science berets were just the first domino on the stupid beret mil larpification.

**Comment by Wallemations** [comment]
> I hate beret posters why does every job get a beret who thought this was a good idea reeeeeeeeeeeeeeee

There's really only 3 jobs I would give berets; Sec officers because military, mimes because France, and the RD because I'd imagine someone who devotes themself to science would be _that kinda guy_ to think wearing a beret makes them look smart

**Review by Imaginos16 — APPROVED** [review]
https://www.youtube.com/watch?v=xzpndHtdl9A

**Comment by GuillaumePrata** [comment]
Welcome to Beret Station 13, enjoy your mil larping.

**Comment by Pepsilawn** [comment]
> Breaking news, gloves and boots now restricted to military positions. Civilians who dare wear them now all caught up in scandals of stolen valour.

There's nothing wrong with casual milsim streetwear but why is my employer assigning them to me as work uniform

**Comment by CRITAWAKETS** [comment]
I have three issues with this.
1) The turtleneck has too much contrast and looks kinda neon, but not _quite_ enough for it to look intentional. Maybe tone it town a little?
2) The labcoat looks more like a wintercoat, it has pretty much all the design cues. This isn't exactly a knock on the design, though it could be an interesting opportunity to make something more coat-like.
3) The beret should probably be in the garment bag and not default. Currently berets have issues with hair sprites being often too big for them and thus causing a ton of odd clipping. Since it's a cosmetic item there really isn't anything forcing it to be worn.

**Comment by Sealed101** [comment]
there is a science beret in the garment bag already

**Comment by Fikou** [comment]
security officer with a coat

**Comment by Wallemations** [comment]
> 2) The labcoat looks more like a wintercoat, it has pretty much all the design cues. This isn't exactly a knock on the design, though it could be an interesting opportunity to make something more labcoat-like.

Iirc it's based off robotnik's coat from the live action sonic movies

**Comment by Imaginos16** [comment]
Seems fine, lets go.

**Pull request merged**
