### PR TITLE
Removes forcesay on attacked

### LINKED ISSUE #8999: Using Say Hotkey lets you Talk without being interupted
Basically, ye know how you can get interrupted if you get hit hard while typing somethi-oof!
If you use the say HotKey, it makes a window pop up, which can't be interrupted.
So you could use it to utterly ignore the interruption getting attacked can cause to yell out whatever you want.

### PR DESCRIPTION
**Pull request by kriskog**
## About The Pull Request
Ancient feature that is circumvented by most of our players since hotkey mode is the default and most used input mode. I am calling this deprecated, and saying lets remove it.

I will not entertain "improve dont remove" unless you actually bring a solution to #8999 that does not impact general user experience.

## Why It's Good For The Game
Closes #8999

## Changelog
:cl: Skoglol
del: Removed forcesay on getting hit in classic mode.
/:cl:

### CODE REVIEW

**Comment by Tharcoonvagh** [comment]
Glorf

**Comment by Tlaltecuhtli** [comment]
why not make it work on say windows?

**Comment by PKPenguin321** [comment]
I'm surprised we never managed to fix this by making the say popup a tgui thing, what with how fast tgui has become

**Comment by optimumtact** [comment]
You can't do this this is tg cul- ...glorf

**Comment by Jared-Fogle** [comment]
> why not make it work on say windows?

Because it's impossible to cancel or retrieve the text from `input` windows, which is what say uses. 

Personally, I'd love to turn the say menu into a more intuitive tgui at some point, I just haven't done so out of performance concerns.

**Comment by theOperand** [comment]
:pensive:

**Pull request merged**
