### PR TITLE
Adds Vulpkanin, Tajaran, Skrell, and IPCs to the game.

### PR DESCRIPTION
**Pull request by Iamgoofball**
dreamseeker_2016-12-11_00-03-59

Pictured from right to left: Vulpkanin, Tajaran, Skrell, IPC

# Vulpkanin

Vulpkanin are a species of sharp-witted canine-pideds residing on the planet Altam just barely within the dual-star Vazzend system. Their politically de-centralized society and independent natures have led them to become a species and culture both feared and respected for their scientific breakthroughs. Discovery, loyalty, and utilitarianism dominates their lifestyles to the degree it can cause conflict with more rigorous and strict authorities. They speak a guttural language known as 'Canilunzt' which has a heavy emphasis on utilizing tail positioning and ear twitches to communicate intent.

# Tajaran
The Tajaran race is a species of feline-like bipeds hailing from the planet of Ahdomai in the S'randarr system. They have been brought up into the space age by the Humans and Skrell, and have been influenced heavily by their long history of Slavemaster rule. They have a structured, clan-influenced way of family and politics. They prefer colder environments, and speak a variety of languages, mostly Siik'Maas, using unique inflections their mouths form.

# Skrell

An amphibious species, Skrell come from the star system known as Qerr'Vallis, which translates to 'Star of the royals' or 'Light of the Crown'. Skrell are a highly advanced and logical race who live under the rule of the Qerr'Katish, a caste within their society which keeps the empire of the Skrell running smoothly. Skrell are herbivores on the whole and tend to be co-operative with the other species of the galaxy, although they rarely reveal the secrets of their empire to their allies.

# IPC

Positronic intelligence really took off in the 26th century, and it is not uncommon to see independant, free-willed robots on many human stations, particularly in fringe systems where standards are slightly lax and public opinion less relevant to corporate operations. IPCs (Integrated Positronic Chassis) are a loose category of self-willed robots with a humanoid form, generally self-owned after being 'born' into servitude; they are reliable and dedicated workers, albeit more than slightly inhuman in outlook and perspective.

### CODE REVIEW

**Comment by dannno** [comment]
very mature approach to the situation

**Comment by HankMoodyExperience** [comment]
fuck off you autistic cunt

**Comment by Iamgoofball** [comment]
@Fox-McCloud please argue in support of this PR

**Comment by Cebasiz** [comment]
goof can you stop being such a triggered baby please

**Comment by Iamgoofball** [comment]
there's no triggering here

**Comment by Cebasiz** [comment]
you flip the fuck out every time someone adds some new thing for nonhumans. you don't have the right perspective about the whole thing, that is to say, my perspective

>more snowflake shit for nonhumans
>more people play nonhumans
>there is a bigger pool of nonhumans to shock doors in front of

basically goof, just go to your happy place and there i will be, shocking things to death for breathing wrong near humans.

**Comment by Iamgoofball** [comment]
exactly, so what's the problem with this PR?

**Comment by Cebasiz** [comment]
because goof, this is in your silly tantrum you do everytime someone tries (and fails this time) to add insignificant flavor options for whatever race

if you were serious about it i'd be okay with it. maybe it would get someone to roleplay once every 20 rounds or something

**Comment by kevinz000** [comment]
:^) Goof, your code may be good, but your attitude isn't.

**Comment by PKPenguin321** [comment]
Goof please stop this kind of thing makes it difficult to support you

**Comment by PKPenguin321** [comment]
(((((((((((((((((((although I won't lie IPCs aren't the worst))))))))))))))))))

**Comment by dannno** [comment]
grow up

**Comment by Iamgoofball** [comment]
@PKPenguin321 I actually like IPCs, they just need to be done in a not-shit way(like pure cosmetic)

**Comment by Archie700** [comment]
This would have actually been pretty acceptable if it wasn't posted by goof shortly after the stupid "CATPURRRRRRR" pr.

This is how infamous goof is.

**Comment by dannno** [comment]
no it wouldn't
the fuck

**Comment by Iamgoofball** [comment]
@dannno see? players wannt it man

**Comment by dannno** [comment]
¯\_(ツ)_/¯

**Comment by optimumtact** [comment]
Alright, this has gone on long enough.

Offically codebase policy from this point:

1) no new races unless they are really, really really unique and interesting (that means no ports of existing races)
2) Cat people won't change from their current status quo as human mutation items for ears and tail until I'm fired.


Can you please stop making these PR's now? That goes for all sides of the debate.

**Comment by Kevak** [comment]
IPC's would actually be a neat thing to add because mechanically speaking they're rather balanced (unclonable, take x2 damage from brute/burn sources, don't take tox/oxy, still take pressure damage, surgery is different and would confuse the average doctor, EMP is instadeath.) and play utterly different from the current races. Would work methinks.

**Comment by Iamgoofball** [comment]
@KEVAK THAT'S NOT BALANCED FUCK

**Comment by Kevak** [comment]
I'd call it balanced. Remove two damage types _Completely_ and removing regents affecting whatsoever baring ones that affect from coating a target is a pretty fair exchange for getting a new (Very rare) damage source (EMP) and double damage from burn/brute.

**Pull request closed without merging**
