### PR TITLE
Adds scrunglartiy as a roundend sound

### PR DESCRIPTION
**Pull request by VileBeggar**
## About The Pull Request

Adds the "_How do I set up the. SHow do I set u p the Singu. how I the scrungulartiy????_" line as a roundend sound.
Credit to Hulkamania for the actual sound, credit to Plapatin for ~~leaking it~~ showing it.

The sound is 13 seconds long and it didn't cut off when I tested it, but I can trim it further if needed.

https://vocaroo.com/i/s16gT3Vtee1w

## Why It's Good For The Game

I don't think the /tg/ playerbase can handle playing another round without hearing this magnificent piece of art. Also it's not loud which is good (I think it's not loud).

## Changelog
:cl: Vile Beggar, Hulkamania
soundadd: Adds the scrungulartiy as a roundend sound effect.
/:cl:

### CODE REVIEW

**Comment by VileBeggar** [comment]
https://soundcloud.com/floatonfire/hulka-says-scrunglartiy/s-aOZA4 here's the HQ full recording if you want to hear it

**Comment by wesoda25** [comment]
this will be 10x worse than 20 gondolas on the bridge in half the time, please no

**Comment by VileBeggar** [comment]
> 
> 
> this will be 10x worse than 20 gondolas on the bridge in half the time, please no

**Comment by OverlyGeneric** [comment]
implement an actual type of singularity that animated in MSPaint.  anyway :+1:

**Comment by Shadowflame909** [comment]
I never really got the joke honestly, or maybe I just didn't find it funny.


So when you're that guy who doesn't get the joke, and you see it literally everywhere. It's off-putting.


This is gondolas on the bridge all over again

**Comment by VileBeggar** [comment]
> 
> 
> I don't get the joke...

dumb CE says dumb shit and makes everyone laugh at him

**Comment by lordsaladin** [comment]
scrunglarity is just a ms paint singulo.

**Comment by Kierany9** [comment]
close this and don't reopen until there's also hulk reading erotica as a roundend sound

**Comment by Ziiro** [comment]
It's too damn long. It would likely be clipped by the restart.

**Pull request merged**
