### PR TITLE
Don't initialize stack components inside machines

### PR DESCRIPTION
**Pull request by SyncIt21**
## About The Pull Request

An attempt at the [Initiative](https://github.com/tgstation/dev-cycles-initiative/issues/29) all types/subtypes of `obj/item/stack` no longer exist inside any machine. Only during deconstruction is the stack created from the circuit boards requested components.

Also moved the component printer & module duplicator circuitboards into `machine_circuitboards.dm` so they all are in one place

I was unable to do this for circuitboards because that still needs to exist so we can use `apply_default_parts()` on the machine. I tried to do the whole datum circuitboard approach just like with stock parts but i'm unsure about it so maybe next time

## Changelog
:cl:
refactor: stack components no longer exist inside a machine's component_parts
refactor: move component printer & module duplicator circuitboards into machine_circuitboards.dm
/:cl:

### CODE REVIEW

**Comment by SyncIt21** [comment]
@Mothblocks

**Comment by SyncIt21** [comment]
So i did try to create a singleton instance of all `obj/item/circuitboard` to pass around inside an datum just like `datum/stock_part`. My assumption was no machine needed to change the circuit board properties so it would be okay to create a shared instance but unfortunately some machines do edit circuit board properties
1. The vending machine
https://github.com/tgstation/tgstation/blob/d74f2dd8e07de05d9bb467512e777448e9517009/code/modules/vending/_vending.dm#L224-L228
2. medical kiosk 
https://github.com/tgstation/tgstation/blob/d74f2dd8e07de05d9bb467512e777448e9517009/code/game/machinery/medical_kiosk.dm#L154-L156
3. changing piping layer on thermo machine circuitboards
https://github.com/tgstation/tgstation/blob/d74f2dd8e07de05d9bb467512e777448e9517009/code/game/objects/items/circuitboards/machines/machine_circuitboards.dm#L294-L297

And more instances elsewhere. In general there are boards who's properties can be tweaked by the user & during mapload so each machine must have its own instance of a circuitboard initialized to hold these tweaks  so i think we have to give up on circuitboards

**Comment by SyncIt21** [comment]
`/datum/unit_test/outfit_sanity` is failing. Can't help it.

**Comment by SyncIt21** [comment]
Should probably test merge this

**Comment by Mothblocks** [comment]
Sorry I haven't been able to look at this, I'll TM it tomorrow

**Comment by SyncIt21** [comment]
Just wondering can [stack init](https://github.com/tgstation/dev-cycles-initiative/issues/15) initiative also be closed with this? If not machines where else could stacks be created during mapload that could cause them to merge?

**Comment by Mothblocks** [comment]
I'll investigate the savings on all this later

**Comment by SyncIt21** [comment]
I think 28 rounds is enough testing for the merge.? The only possible bug that could creep up is stack components not spawning when a machine is deconstructed but i specifically tested & fixed for that, besides that everything else is good

**Pull request merged**
