### PR TITLE
Adds 535 Unique Hardsuits + Customization Options

### PR DESCRIPTION
**Pull request by nullbear**

### CODE REVIEW

**Comment by nullbear** [comment]
meme. jk tho

**Comment by Kromgar** [comment]
Dank memes

**Comment by F-OS** [comment]
nice.

**Comment by Sligneris** [comment]
Shitty response to a simple idea everyone decided to overreact to :^) Nice.

**Comment by nullbear** [comment]
Don't be so muffed about it. The idea isn't bad, it's just a repetitive 'snowflake feature creep' that gets requested often with little/no lore or gameplay reason for it.

**Pull request closed without merging**
