### PR TITLE
Light is now white

### PR DESCRIPTION
**Pull request by nicbn**
[Changelogs]: #
:cl: nicbn
add: Stations are now equipped with fluorescent lighting.
/:cl:

### CODE REVIEW

**Comment by praisenarsie** [comment]
looks dull

**Comment by 81Denton** [comment]
Can you post some screenshots to show the difference (regular/night time)?

**Comment by 81Denton** [comment]
🤔

**Comment by nicbn** [comment]
4 downvotes not a good sign

**Pull request closed without merging**
