### PR TITLE
Fixes and changes Napalm Recipe

### LINKED ISSUE #8864: Napalm does nothing
Exactly what the title says. Once you mix it, all the reagents disappear and nothing happens.

### PR DESCRIPTION
**Pull request by Iamgoofball**
turns out I 1. forgot to make it actually produce the reagent, and 2. forgot to change the recipe

Fixes #8864

### CODE REVIEW

**Comment by babinsquared** [comment]
This will break pre-made incendiary chem grenades fyi

**Comment by Iamgoofball** [comment]
Napalm effects were changed, new napalm doesn't make a plasma fire anymore, it's used for upping fire stacks which makes the other burny chems more effective damage wise. Phlog is the new burny plasma fire chem if not stabilized.

**Comment by optimumtact** [comment]
Please make sure you fix the incendiary grenades to use the correct recipe if that is not already the case

I'll love you long time

**Comment by Iamgoofball** [comment]
I'll check them out.

**Pull request merged**
