### PR TITLE
Compiles tgui for atmos alarms and freon

### PR DESCRIPTION
**Pull request by Shadowlight213**
Goof updated the template but wasn't able to build the js

### CODE REVIEW

**Comment by Iamgoofball** [comment]
yeah, btw if anyone can help me out, gulp refuses to work

**Comment by RemieRichards** [comment]
@Iamgoofball are you installing it via the "install_dependencies.bat"? if so, don't, it's trash and doesn't work.

**Comment by PJB3005** [comment]
This is why complex build toolchains like this are a terrible idea.

**Comment by optimumtact** [comment]
It's not that complex for a modern web app project in 2016

**Pull request merged**
