### PR TITLE
Change candy description to have some form of punctuation

### PR DESCRIPTION
**Pull request by Mothblocks**
:cl:
spellcheck: Changed candy description to read better
/:cl:

### CODE REVIEW

**Comment by optimumtact** [comment]
nougat love it or hate it

**Comment by LemonInTheDark** [comment]
WHAT DOES IT MEAN

**Comment by TJatPBnJ** [comment]
—hate it

**Comment by DATA-xPUNGED** [comment]
What does it even mean

**Comment by Mothblocks** [comment]
Nougat love it or hate it

**Comment by MrMelbert** [comment]
Nougat love it or hate it

**Comment by san7890** [comment]
i'm fond of nougat

**Comment by Loafin34** [comment]
Nougat it, or ya don't.

**Pull request merged**
