### PR TITLE
Restores RPD placement delay for disposals

### LINKED ISSUE #10644: New RPD speed can be abused with blocking items
Currently RPD pipe laying speed is almost instant. This includes blocking items such as bins, inlets etc. People can now lay down a near infinite amount of bins blocking hallways almost instantly.

### PR DESCRIPTION
**Pull request by duncathan**
Fixes #10644
in my defense disposals construction is shit

### CODE REVIEW

**Comment by duncathan** [comment]
what the FUCK does this conflict with

**Comment by MrPerson** [comment]
You probably should just redo this one

**Comment by duncathan** [comment]
i am bad at computer

**Comment by Firecage** [comment]
Oh, it probably conflicted with mah PR.

**Pull request closed without merging**
