### PR TITLE
Minor Abductor update

### PR DESCRIPTION
**Pull request by AnturK**
- Fixes unbuckling from tables
- Makes the location that abductees will be sent to chosen by the abductors.

### CODE REVIEW

**Comment by Supermichael777** [comment]
For the second thing is it an xy or does it list areas. xy could be used to kill(bad).

**Comment by KazeEspada** [comment]
I am going to drop so many people into the tesla.

**Comment by AdamElTablawy** [comment]
>abduct the captain
>send him into the singularity

best pr

**Comment by Shadowlight213** [comment]
You should have it only work for sending them to safe areas. There's no point to the glands/abductee objectives if the ayys just send everyone to the singularity.
:-1: otherwise.

**Comment by KazeEspada** [comment]
singuloth wont work since you can drop onto space.

**Comment by Shadowlight213** [comment]
@KazeEspada Tesla then.
My point still stands.

**Comment by WJohn** [comment]
You could still drop them on the field gen tiles and then they'll get sucked in right after anyway.

**Comment by Shadowlight213** [comment]
@wjohn exactly. It should be restricted to like the hallway areas or departments other than engineering. Abductors aren't supposed to murder people.

**Comment by KorPhaeron** [comment]
@AnturK 

Merge conflicts

**Comment by AnturK** [comment]
Should be good now.

**Pull request merged**
