### PR TITLE
Lets Player-Controlled Monkeys Make Noise When Using *Screech

### PR DESCRIPTION
**Pull request by IndieanaJones**
## About The Pull Request

This PR lets player-controlled monkeys make screeching noises using *screech.

Under the hood, this PR also adds a new proc to emotes called, should_play_sound.  What this does by default is the same check run_emote used to do with only_forced_audio, but now that it's in a proc you can override it if you want to.  Though, let's be real here, this is only going to get used for this PR because the only reason you'd want to bypass that check is if you're doing something for monkeys.  The amount of extremely specific circumstances which even warranted something like this could only stem from some stupid monkey/alien specific crap anyway, BUT JUST IN CASE YOU NEED IT, here it is.

## Why It's Good For The Game

Considering all the screeching AI monkeys do, it's a big shame that currently player monkeys can't do similar.  Considering that monkeys are valid salad and that AI monkeys already screech a lot anyway, I don't think letting players get in on the fun is a bad idea.  If need be, we can just tune up the sound cooldown on *screech but I don't think it's really that abusable to begin with.

## Changelog
:cl:
expansion: Player monkeys make a screeching noise when using the *screech emote.
/:cl:

### CODE REVIEW

**Comment by LemonInTheDark** [comment]
What? why?

**Comment by Iamgoofball** [comment]
:+1: this is good

**Comment by optimumtact** [comment]
>  As a result of these changes, player-controlled humans can no longer screech

? just fix it?

**Comment by optimumtact** [comment]
just fucking fix it properly what is wrong with you? the code is open source just add a conditional flag that lets you achieve what you want christ on a bike

**Comment by IndieanaJones** [comment]
The whole point was to avoid adding a way around only_forced_audio which would only be used for a singular emote, which I'd feel would've been unnecessary bloat.  However, if that's what's wanted I can easily do that instead.

**Review by LemonInTheDark — CHANGES_REQUESTED** [review]

**Comment by LemonInTheDark** [comment]
Refuses to elaborate, leaves, pr is merged

**Pull request merged**
