### PR TITLE
Felinid screaming.

### PR DESCRIPTION
**Pull request by grungussuss**
## About The Pull Request
They get their own scream sounds, that's it.

<details>
<summary>Click me for sounds!</summary>

https://github.com/user-attachments/assets/4dceec83-24ff-445e-847b-9b8511af86a8

https://github.com/user-attachments/assets/6bbe199f-33b6-43e7-adfd-ffd89a8ae562

https://github.com/user-attachments/assets/0185deba-60be-44ec-a792-7280dbb9b3dc

https://github.com/user-attachments/assets/2bc8146c-a3bc-4e37-84be-007759f0eaf1

</details>

## Why It's Good For The Game
You will be able to recognize a catgirl easier
## Changelog
:cl: grungussuss
sound: felinids have their own scream sound
/:cl:

### CODE REVIEW

**Comment by DATA-xPUNGED** [comment]
AAA,AAA,AAA,AAA

**Comment by norsvenska** [comment]
MREOEEEEEEEEOW

**Comment by DrAmazing343** [comment]
Too much downstream in my upstream. I’ve never been a particular fan of the full animal sounds except meowing and hissing.

**Comment by YakumoChen** [comment]
The funny cat emotes are (and should be) optional, don't think that TG should enforce animal sounds via screams.

**Comment by EmptyLullaby** [comment]
at this rate we should just turn felinids into full catpeople and stop having them be humans But  Cat Ea- *i am pelted to death with stones*

**Comment by Maximal08** [comment]
It is necessary to give 10 brain damage to the one who screams for every scream

**Comment by Sadboysuss** [comment]
Ok, ok, you're right. Let's not turn tg into a furry codebase.

**Comment by LemonInTheDark** [comment]
turn?

**Pull request closed without merging**
