### PR TITLE
Frog masks no longer have a sound

### PR DESCRIPTION
**Pull request by Iamgoofball**
why

### CODE REVIEW

**Comment by Iamgoofball** [comment]
@WJohn this feature deserves that tag

**Comment by ACCount12** [comment]
REEEEEEEEEEEEEEEEEEEE

**Comment by SgtxRootbeer** [comment]
@armhulen

**Comment by Qustinnus** [comment]
does this mean goof played??

**Comment by Armhulen** [comment]
denied

**Comment by Arianya** [comment]
Administration issue

**Comment by AnonymousNow** [comment]
If there HAS to be a ree sound, then let it be [Burger.](https://www.youtube.com/watch?v=_SWApWkEiIc)

**Comment by Mercenaryblue** [comment]
Goof cannot handle the reeee

**Comment by lzimann** [comment]
Change the orb title to actually say what the pr does.

**Comment by Mercenaryblue** [comment]
Can we keep the sounds for the cursed version? Because its cursed?

**Comment by The-clown-known-as-Pepe** [comment]
@Mercenaryblue your downstream can just not merge this PR if they want shitty earrape

**Comment by Mercenaryblue** [comment]
I'm sorry, I can't hear you over the REEEEEEEEEEEEE!!

**Comment by Slignerd** [comment]
@Iamgoofball I thought you were all about being representated in the game?

**Comment by Slignerd** [comment]
@Iamgoofball I thought you were all about being represented in the game?

**Comment by Dorsisdwarf** [comment]
a goofball pr  I agree with? 

what is this, the end times?

**Pull request merged**
