### PR TITLE
READDS FUN MK.2

### PR DESCRIPTION
**Pull request by ghost**
🆑 MORE ROBUST THAN YOU
add: HEADPATTING
add: SLAP THOSE CATS IN THE FACE TO MAKE THEM STOP WAGGIN THEIR STUPID TAILS!
/🆑

### CODE REVIEW

**Comment by PraiseRatvar** [comment]
if this gets added and i get slapped by a hos/warden catgirl and i am (not) antag, don't come to the security department tomorrow

**Comment by Iamgoofball** [comment]
@optimumtact 

This STILL DOESNT MEET CODE STANDARDS.

OH MY GOD.

# ALL YOU HAVE TO DO IS ADD IT AS AN EMOTE.

**Comment by MoreRobustThanYou** [comment]
i dont wanna have to type *slap or *pat, i wanna just do it

**Comment by MoreRobustThanYou** [comment]
**_MUH CODE STANDERDSZZZ_**

**Comment by banthebantz** [comment]
Slap my hand

Slap it now

This is NOT a trick!

**Pull request closed without merging**
