### PR TITLE
makes ss13 more SJW friendly

### PR DESCRIPTION
**Pull request by ghost**
```[18:47:34] <QualityVan> reminder that we should remove suicide from ss13 because it promites it!!```

### CODE REVIEW

**Comment by qbmax32** [comment]
delet this

**Comment by RogueSteampunker** [comment]
But this PR makes me want to kill myself. Quite the inigma

**Comment by qbmax32** [comment]
good boy oranges

**Comment by TGxSingularity** [comment]
wew, that was fast

**Comment by qbmax32** [comment]
was this a bet

**Comment by TGxSingularity** [comment]
Was getting your PR closed part of your plan?

**Comment by MoreRobustThanYou** [comment]
```
<Xhuis> QualityVan, dang it
<Xhuis> you did this
```

**Comment by MoreRobustThanYou** [comment]
it was a meme PR, I expected it to get close really fast

**Pull request closed without merging**
