### PR TITLE
Removes cockroaches from the maps

### PR DESCRIPTION
**Pull request by Core0verload**
This PR removes all the cockroaches from all the maps. Reasoning: 
- Cockroaches have incredibly ugly sprites (<B>Remie Edit: They're actually stolen from Goon too, which we have no permission to use</B>)
- Cockroaches, being harmless useless simple mobs, have no gameplay value.
- Cockroaches are cluttering mobs lists (30-40 cockroaches on every map), possibly reducing performance of some critical code segments such as radio.
- Cockroaches add no fun to the game.

They are simply not worth their server processing time.

### CODE REVIEW

**Comment by GunHog** [comment]
Agreed. Hate them. :+1:

**Comment by KazeEspada** [comment]
:-1:

**Comment by lzimann** [comment]
thank you, i only didn't do this because i was lazy

**Comment by ChangelingRain** [comment]
:+1:

**Comment by Aloraydrel** [comment]
Adios shit roach

**Comment by bgobandit** [comment]
:-1: 

improve don't remove

**Comment by Cheridan** [comment]
:+1:

**Comment by Core0verload** [comment]
There is no way to improve these creatures. They exist solely to die under a boot of some random greyshirt.

**Comment by PKPenguin321** [comment]
yeah these don't really do anything at all

**Comment by bgobandit** [comment]
how am I supposed to run roach survival events with no roaches

**Comment by KazeEspada** [comment]
They aren't supposed to do anything. They are like mice.

**Comment by Zilenan91** [comment]
Mice didn't have a point either until they started biting wires. Roaches could be improved to do more and be pests if someone wanted to put the time to them, but currently I don't see a point in removing them.

**Comment by Zilenan91** [comment]
Personally I'd love it if cockroaches actually bred with each other and ventcrawled around everywhere and poked people so that people would have to look for the ones doing the breeding.

**Comment by PKPenguin321** [comment]
make cockroaches feed on corpses and make them into unknowns

**Comment by Fox-McCloud** [comment]
:+1: 

There's only like 4-5 mice, so it's hardly worth comparing the two.

**Comment by Lumipharon** [comment]
Mice do have a purpose -  they squeek when stepped on.
If you're in the dark people can hear you moving around when this happens.

It's not much, but atleast it's SOMETHING compared to MEGAROACHES

**Comment by Zilenan91** [comment]
Mice also bite wires which is annoying as fug

Cockroaches could be an actually decent case of improve don't remove if someone wants to do something with them.

**Comment by Ultimate-Chimera** [comment]
:+1:

**Comment by KorPhaeron** [comment]
░░░░░░░░░░░░▄▄                     
░░░░░░░░░░░█░░█                  
░░░░░░░░░░░█░░█                  
░░░░░░░░░░█░░░█                  
░░░░░░░░░█░░░░█                  
███████▄▄█░░░░░██████▄ 
▓▓▓▓▓▓█░░░░░░░░░░░░░░█ 
▓▓▓▓▓▓█░░░░ Valve, ░░░░░█ 
 ▓▓▓▓▓▓█░░░░Add This░░░░█  
▓▓▓▓▓▓█░░░░Please!░░░░░█ 
▓▓▓▓▓▓█░░░░░░░░░░░░░░█ 
▓▓▓▓▓▓█████░░░░░░░░░█   
██████▀░░░░▀▀██████▀

**Comment by Core0verload** [comment]
I don't understand why some people try to defend cockroaches. Well, @KazeEspada is just a bug-alien hiding in a human skin, but the rest?

And about "they are just like mice". Fuck no. Unlike mice, they are not maint-only critters, they spawn in amounts 6-8 larger than mice spawn, and their sprites are so ugly they make me cry with blood every time I see them. 

In comparison, mice have a neat small sprite, live in maint only, can train shit engineers to find and fix broken wiring, are useful for making burgers and justify existence of mousetraps. Cockroaches can't even justify their own existence.

**Comment by Iamgoofball** [comment]
make cockroaches go after food

if they get into food/fuck with the food, poison it and poison the eater

allow them to raid vending machines too

**Comment by RemieRichards** [comment]
At bare minimum the sprites need replacing.
since the current ones are stolen from a Goon leak.

**Comment by Core0verload** [comment]
>the current ones are stolen from a Goon leak

I told in IRC that sprties "are probably stolen from some shithole of spriting". Didn't knew it was Goon.

**Comment by xxalpha** [comment]
Instead of suggesting coreoverload to improve not remove, you should improve them yourself to make this PR unnecessary.

Cockroaches really serve no purpose other than being stepped on and squished. Here's an idea, make them come out of the scrubbers during the scrubbers event, for extra nasty. That way they are not always present and can still serve their function.

**Comment by Dorsisdwarf** [comment]
:+1: 

If they're ever made nonshit they can be remapped

**Pull request merged**
