### PR TITLE
Ports Eris Station's shuttle chairs

### PR DESCRIPTION
**Pull request by ghost**
:cl: More Robust Than You
add: Shuttles now have new, super-comfy chairs!
/:cl:

sadly I got tired of editing the new shuttle chairs into maps into shuttles so I only got it done on Box and Cere.

capture

### CODE REVIEW

**Comment by Cyberboss** [comment]
These do not look good

**Comment by Durkel** [comment]
Here's a relevant video describing those sprites.

https://www.youtube.com/watch?v=Sd3APu-Sb90

**Comment by Mark9013100** [comment]
I'd recommend Urist McStation's shuttle chairs.

**Comment by PraiseRatvar** [comment]
@Mark9013100 pictures?

**Comment by Iatots** [comment]
Those are recoloured goonstation chairs.

**Comment by InsaneHyena** [comment]
The sprites look super fucking weird

**Comment by GunHog** [comment]
Airplane chairs!

**Comment by MoreRobustThanYou** [comment]
just got a slightly better pic from the map editor

**Comment by FantasticFwoosh** [comment]
Tougher, fixable to the ground with a wrench and built out of titanium? Then i'd be interested.

Otherwise its just a throwaway pallete change that looks a little bit odd. mmm.

**Comment by dannno** [comment]
I can't imagine that people would look right buckled to these sideways

**Comment by WJohn** [comment]
I figured these were goon chairs, no?

Anyway I actually don't mind these that much as far as the design is concerned, but I don't like how the arms are handled in the side sprites (lack of outlines in the near arm). Could probably also have the color palette reduce some to make use of fewer colors going on.

But, if there's one thing I know not to even bother touching, it's super ancient iconic sprites like chairs, walls, windows etc. Unless you come through with something really stellar to replace all chairs I don't think it's a good idea.

**Comment by ChangelingRain** [comment]
the arm on the side won't go over people buckled to it right, and even if it did it wouldn't look good(armchairs do this but it only looks good because the arm of the chair has no holes to see through)

**Comment by Mark9013100** [comment]
@PraiseRatvar Give me a few hours and I'll get a screenshot.

**Comment by optimumtact** [comment]
these look awful lol

**Comment by Iatots** [comment]
Port couches instead.

**Comment by JStheguy** [comment]
@Iatots 
This, give us spess sofas. I need some proper decor for my shitty hidden maint flophouse.

**Comment by calzilla1** [comment]
Ironically, I actually like these

**Comment by mattroks101** [comment]
Are these are an edit of goonchairs?

**Comment by Mark9013100** [comment]
@PraiseRatvar

**Comment by optimumtact** [comment]
looks like people don't like it.

**Pull request closed without merging**
