### PR TITLE
stops midround dynamic families ruleset from picking mindshielded starting family members

### PR DESCRIPTION
**Pull request by tmtmtl30**
## About The Pull Request

title

## Why It's Good For The Game

mindshielded people aren't supposed to be in families

## Changelog
:cl:
fix: stopped midround dynamic families ruleset from picking mindshielded starting family members
/:cl:

### CODE REVIEW

**Comment by bobbahbrown** [comment]
can you switch the weird structure of if / continue to just use if else its literally the same thing except in one line

**Comment by tmtmtl30** [comment]
ok

**Comment by tmtmtl30** [comment]
TRAVIS SHUT THE FUCK UP

**Comment by tmtmtl30** [comment]
hopefully thatll shake him up

**Comment by tmtmtl30** [comment]
goddammit

**Comment by AnturK** [comment]
These need a bit more formatting clean-up but that's bit out of scope here.

**Pull request merged**
