### PR TITLE
Reverts toolboxes

### PR DESCRIPTION
**Pull request by MrsTonedOne**
If you don't want me to play re-open war with prs, you are going to have to leave the original pr open for longer.

### CODE REVIEW

**Comment by WJohn** [comment]
server host vs head coder

WHO WILL WIN

**Comment by KorPhaeron** [comment]
@MrStonedOne 

We can't afford to leave PRs open for discussion anymore because our rogue citrus bot automerges things at 24 hours

**Comment by Incoming5643** [comment]
Can we not merge obvious meme prs?

I mean seriously he called the player base morons in the changelog.

**Comment by dannno** [comment]
nuh uh

**Comment by kevinz000** [comment]
Yes you fucking did.

**Comment by RemieRichards** [comment]
Can you two calm down? Yes his changelog is stupid, but his PR wasn't.

**Comment by Cyberboss** [comment]
#23938
#23977

**Comment by optimumtact** [comment]
Who cares the maintainers are agreed on this one, so it's really just MSO being a libertarian or whatever and violating NAPS

**Comment by PKPenguin321** [comment]
poll

**Comment by RemieRichards** [comment]
@PKPenguin321 the change hasn't even been infor a day yet, Chill and give it a week.

**Comment by kevinz000** [comment]
how about we delete my thread and let me redo it at the end of a week and see if people like it more?
If that suits everyone it'd suit me fine.

**Comment by WJohn** [comment]
Let stockholm syndrome run its course, no one will care in a couple of weeks. It's just 3 sprites.

**Comment by kevinz000** [comment]
Toolboxes are a part of SS13 culture.

**Comment by Haevacht** [comment]
The function is unchanged, kev. You still robust people with them.

**Comment by RussellTalbott** [comment]
As I wake from the Cryochamber, the hum of machinery calms me.  

_Doctor, this is within acceptable operating parameters_

I look beside me.  The toolbox looks...different somehow.

"Computer, end simulation."

_Doctor, you know what you see is real._

I can't stop myself.  I'm shaking.  This can't be real.  My legacy has been sullied.

"Computer, administer lethal dose of epinephrine."

_Look at them._

"Computer please."

_You are on thin ice, doctor._

**Comment by kevinz000** [comment]
Can we stop bringing up my icepacks ban? It's getting irritating.

**Comment by dannno** [comment]
WATCH OUT FOR THIN ICE

**Comment by Haevacht** [comment]
Closed by #24001 probably.

**Comment by Kromgar** [comment]
REEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE FUCK CHAAAAAAAAAAAAAAAAAAAAANGE

**Comment by dannno** [comment]
You have declared war on the Grand Duchy of Kev!

**Comment by sawrge** [comment]
_crys so hard is so sad_

**Comment by CosmicScientist** [comment]
I can understand people wanting to not want a different sprite.
I can understand people wanting to move onto a different sprite.

I didn't realise there'd be more shitposting than drama nor that the original change would be a shitpost in of itself.

**Comment by Hatfish** [comment]
poll
Here, have a more recent version of that poll that was posted further up.

**Comment by Cheridan** [comment]
well #24001 got merged so this should be good now

**Comment by Incoming5643** [comment]
That's not how this works

**Comment by optimumtact** [comment]
it is now.

**Comment by YakumoChen** [comment]
untitled3

**Pull request closed without merging**
