### PR TITLE
Genders feminine hair for character randomisation

### PR DESCRIPTION
**Pull request by cacogen**
## About The Pull Request

1. Conservatively adds FEMALE gender to hair that looks feminine and/or has a name that intends it to be feminine (e.g. Pixie Cut, Kusanagi hair)
2. Makes it so the hairstyles shown in Character Settings are not affected by gender (previously this didn't do anything)

## Why It's Good For The Game

1. You should no longer get a random male character that appears female
2. Male randomised characters should look less strange

I may gender masculine hairstyles for random female characters as well. 

If you feel I've missed an obvious feminine hairstyle or mislabelled an androgynous or masculine one (according to the name, common use or how it looks) then let me know.

## Changelog
:cl: cacogen
tweak: Random hairstyles on male characters should be less feminine
/:cl:

### CODE REVIEW

**Comment by itseasytosee** [comment]
I like the direction this is going in. Wacky characteristics like colored hair are fine, but it starts feeling off when everyone at the syndie lavaland base had their genes and sexual identification picked by throwing darts at a wall.

**Comment by iwishforducks** [comment]
Can't wait for the heated "political" discussions about what hairs are feminine and what hairs are masculine. In all seriousness, not a good idea to try to impose your cultural ideals of what hairs are masculine and what hairs are feminine. I can imagine any new hairs put in down the line will end up just being put in as adrogynous because of stated problems above.

**Comment by wesoda25** [comment]
Not an ideal solution to random body being ass but better than what we currently have. If someone wants to PR a more "correct" PR they can.

**Comment by cacogen** [comment]
I was quite careful about this which I should've known ahead of time was pointless having seen video game developers try to placate the types of people I imagine are leaving wonky face emoticons on this.

Currently the random hair option is worthless if you aren't willing to go to the bathroom some rounds to make your character look male at a glance to avoid uncomfortable interactions with children and other virgins who don't use examine. I'd be willing to bet none of the people disapproving of this use the random hair option to begin with. 

This doesn't get in the way of people picking whatever hairstyle they want.

**Comment by interestingusernam3** [comment]
>In all seriousness, not a good idea to try to impose your cultural ideals of what hairs are masculine and what hairs are feminine. 

Most of these hairs were created by certain groups or individuals at some point for the female gender. Some others were clearly erraneously classified as female by cacogen however.
Examples: the ponytails and the braids

main-qimg-b095c02e137f279dfe2d70c3c75c25f9

**Comment by cacogen** [comment]
I don't think the images you posted reflect the sprites I classified as feminine. I was careful and if there was some doubt I left it alone.

**Comment by interestingusernam3** [comment]
>If you want to show me a specific sprite that I got wrong you can.

Ponytails 2, 4, 6

Upon checking the sprites I drop the braid miscategorization accusation.

**Comment by Farquaar** [comment]
Good PR

**Comment by optimumtact** [comment]
> I was quite careful about this which I should've known ahead of time was pointless having seen video game developers try to placate the types of people I imagine are leaving wonky face emoticons on this.
> 
> Currently the random hair option is worthless if you aren't willing to go to the bathroom some rounds to make your character look male at a glance to avoid uncomfortable interactions with children and other virgins who don't use examine. I'd be willing to bet none of the people disapproving of this use the random hair option to begin with.
> 
> This doesn't get in the way of people picking whatever hairstyle they want.


your attitude is just garbage and this more than anything else rules you out of fixing any of the issues with randomised characters.

**Comment by wesoda25** [comment]
And so random body will continue to be shit

**Comment by interestingusernam3** [comment]
Cacogen scuttling his own shit as always.

**Comment by ShibaInuLord** [comment]
i cant believe random body is cucked

**Comment by optimumtact** [comment]
you could fix it, just without being a smarmy little shithead and trying to start a massive flamewar

**Comment by cacogen** [comment]
Look oranges, unlike you I don't want to cause controversy, sow discord or abuse "power" over the internet for attention and to feel like I actually have any.

I didn't expect liberal university tier idpol types to swarm this PR with enough wonky disapproval faces to spur a "white knight" like yourself into action. I can only guess you wanted to appear to either have the moral high ground or to be a voice of reason. 

But the very idea of you being either is laughable, considering the types of things you say to people and the way you abuse the power you crept into here (which hurts people whether it's on the internet and whether this place has a 4chan mentality or not).

Also, it's your general abrasiveness, nastiness and consistent power abuse used to hurt and control people in the community and avoid any sort of criticism or insult that you should be concerned about if you want anyone to take you seriously in situations like this.

I understand that in being one of the few people here willing to take the risk of standing up to you by writing this I'm running a risk of getting banned from the GitHub, which obviously further proves what I've written here (which we already knew anyway, just no one wanted to say it). Fix your life, instead of taking it out on people here.

>Cacogen scuttling his shit as always.

Examples? Correct your dumb/suck-up thinking that because this shitler did it it's correct.

**Comment by cacogen** [comment]
Also I'm guessing one of the wonky faces whined to him in coderbus or in secret rather than laying out their issue here.

**Comment by optimumtact** [comment]
The hole just got six feet deeper

**Comment by Fikou** [comment]
😕

**Comment by SweptWasTaken** [comment]
Trying to remove femboys? What a shitter.

**Comment by ZeWaka** [comment]
> Trying to remove femboys? What a shitter.

yeah OP has really faulty reasoning, don't you dare take femboys, tomboys, egirls, and eboys out of my space rp simulator game

**Comment by cacogen** [comment]
I don't what's worse, the insincere suck-up reactions or the liberal idpol ideologues who think because the tyrant is favouring them this time the behaviour is fine. As though the pull request had anything to do with that in the first place. But I've seen how he talks to the maintainers in coderbus sometimes so this Stockholm syndrome you have inevitably effects everyone.

The arrogant façade is unconvincing.

**Comment by interestingusernam3** [comment]
Cacogen, are you still too blind to understand that your comments made this PR de facto unmergeable? This isn't the fault of some wonky face shitmin cabal, you fucked up by disregarding all rules for handling this kind of situation and instead acting like deedub.

**Pull request closed without merging**
