### PR TITLE
Gang Tweaks

### PR DESCRIPTION
**Pull request by Ikarrus**
##### Notable Changes
- Gang Lieutenants can buy gang tools now, but at a higher cost than the original boss
- Gang leaders can register additional gangtools to themselves for use as spares.
- Number of maximum lieutenants lowered to 2
- Pistol cost increased to 25 influence
- Uzi cost increased to 50 influence
- Uzi Ammo decreased to 20 influence
- Overcoats added to leather items the biogenerator can produce
##### Minor Changes
- Starting influence reduced to 15
- Domination attempts reduced to 2
- Gang dominator time bonuses cannot reduce it lower than 5 minutes
- Showers will clean off lipstick and face paint

### CODE REVIEW

**Comment by PKPenguin321** [comment]
In order of changes listed:
Notable changes:
Good, though I don't see why it should cost more
Good
Bad, unless you add something that can remotely de-lieutenant someone. If a lieutenant gets captured by security, you're permanently down a lieutenant.
Neutral
Neutral
Good
Good

Minor Changes
Neutral
Bad, if the gang takes up enough territory and stomps the other gang hard enough *and* the crew does nothing to fix the gang tags, the gang has earned their tiny dominator time.
Good

**Comment by Ikarrus** [comment]
>unless you add something that can remotely de-lieutenant someone. If a lieutenant gets captured by security, you're permanently down a lieutenant.

As intended

>if the gang takes up enough territory and stomps the other gang hard enough and the crew does nothing to fix the gang tags, the gang has earned their tiny dominator time.

It already works this way, only I forgot to change the minimum time the bonus is allowed to be rewarded

**Comment by WJohn** [comment]
Do sinks wash off lipstick and face paint if you use an empty hand on them? If not, they should.

**Comment by Ikarrus** [comment]
What if you had lipstick on you didn't want to was off?

**Comment by Xhuis** [comment]
probably conflicts with #10191

**Comment by Razharas** [comment]
@Ikarrus

**Pull request merged**
