### PR TITLE
Add Restaurant and Bar Holosigns to the Protolathe

### PR DESCRIPTION
**Pull request by Funce**
## About The Pull Request
I think this was a oversight with the implementation of #57010 
Seems to fit fine. If they were supposed to be something else, then uh... let me know!

## Why It's Good For The Game
Oversight/Bugfix?

## Changelog
:cl: Foxtrot (Funce)
fix: Restaurant and Bar Holosigns are now buildable in the Service Protolathe.
/:cl:

### CODE REVIEW

**Comment by Fikou** [comment]
test the pr

**Comment by Funce** [comment]
Yep!

**Comment by Qustinnus** [comment]
can u move them to the protolathe file rather than the autolathe file?

also hi funce long time no see

**Comment by Funce** [comment]
That.. does make a bit more sense, I admit.

Heya Floyd! Always good to see ya

**Pull request merged**
