### PR TITLE
Fixes a consistency issue with Bounty Boards, plus sprite tweaks.

### LINKED ISSUE #52107: Bounty Board Text rubber bands and rebounds harshly on live servers.
## Testmerges:

https://github.com/tgstation/tgstation/pull/51786
https://github.com/tgstation/tgstation/pull/52065

## Reproduction:

Open up a bounty board.
Attempt to type on the right-hand side of the UI. You'll find that the easiest way to get a message into the textbox is just `ctrl-v`ing the text in as the text is updating at every character. Typing too quickly will also potentially send a warning to admins for too many inputs too quickly.

The issue is probably with the text being rebounded back and forth between the UI and DM, I'd reckon. If the text was just stored on the JS side and sent to DM independently, that should fix it.

### PR DESCRIPTION
**Pull request by ArcaneMusic**
## About The Pull Request

Closes #52107.
This adds a bounty board to the Icebox Dorms, as well as fixes a consistency issue with bounty boards where they were sending to the game harshly.

Also, I adjusted the sprite since, after staring at it for long enough I realize that I I'd prefer if it looked like it actually sits on the wall, as opposed to whatever weird tumor thing it was doing before.
image

## Why It's Good For The Game

Forgot to map one of the boards, and the change to the UI should allow it to be usable without screeching the game to a halt repeatedly

## Changelog
:cl:
fix: Bounty boards are properly responsive, and are mapped on icebox dorms as intended.
/:cl:

### CODE REVIEW

**Comment by LemonInTheDark** [comment]
Fuck you

**Comment by ATH1909** [comment]
damn, ya got me

**Comment by MrDoomBringer** [comment]
lmao

**Comment by LemonInTheDark** [comment]
Oh and on another note, keep in mind that  commits show in history, so you want em to be at least kinda descriptive

**Comment by Jared-Fogle** [comment]
> and the change to the UI should allow it to be usable without screeching the game to a halt repeatedly

So I can actually type on them now without hunt and pecking?

**Review by kriskog — APPROVED** [review]

**Pull request merged**
