### PR TITLE
Remaps Lavaland

### PR DESCRIPTION
**Pull request by WJohn**
This PR remaps all of lavaland from a super boring pile of rock carved with caves into a glorious hell world full of lava, chasms, spikes, and vistas.

Minimap because I'm too lazy to map literally all of this in game that'd take FOREVER also spoilers.

### CODE REVIEW

**Comment by PKPenguin321** [comment]
so a lot of this is solid rock now. odes that mean that a bunch of randomized ruins will spawn in them, and likely never be found?

**Comment by WJohn** [comment]
Current lavaland is literally all solid rock, PKpenguin. It is entirely handled by cave generation. This is significantly more open than before.

**Comment by PKPenguin321** [comment]
oh okay

**Comment by MMMiracles** [comment]
The amount of existing lava lakes looks nice but I feel like it might be a bit overkill when accounting in lava river generation and general annoyance of actually getting around lava already in the current solid rock that is our mining.

Other than that, it looks a hell of a lot better. Neat mysterious sphere building on the bottom of the map too.

**Comment by WJohn** [comment]
Almost no lava or chasms get generated in our current lavaland at all. Besides, the intent here is to make lavaland both much more dangerous and give you a reason to use lava boats to travel around.

**Comment by Kromgar** [comment]
Shit i use lava boats all the time the issue with lava boats though is rng of finding enough goliath plates.


Maybe if you could make the recipe Metal and 1 or 2 Goliath plates

**Comment by Durkel** [comment]
Kromgar is right, there might be a issue with lava boats if you increase the amount of lava like that. Perhaps add a nanotrasen style boat purchasable with your voucher or some shit or with points?

**Comment by Steelpoint** [comment]
Durkel is right.

It should be a choice of either spending mining points to buy a NT lava boat versus spending time hunting enough wildlife and getting resources to make one.

**Comment by WJohn** [comment]
I can't code, so someone else will have to do that if it's really necessary. We'll see how it's like.

**Comment by Dorsisdwarf** [comment]
It looks a little... open?

Like thats some HUGE open spaces there

**Comment by xxalpha** [comment]
Special lattices resistant to lava will be made in the near future, as soon as WJ makes some sprites.

**Comment by xxalpha** [comment]
This won't have 24 hours by the time I get home, but I declare DNM since I see floors that need to be corrected.

Please stop copy pasting old map floors.

**Comment by WJohn** [comment]
What floors need correcting? I'm pretty sure I was using all appropriate paths for new floor tiles.

**Comment by xxalpha** [comment]
They are being var edited with icon states for whatever reason.

**Comment by WJohn** [comment]
Uh, the only ones that are doing that are the riveted cult walls near the necropolis gate. I plan to use the necropolis walls once those are implemented in a future update.

**Comment by xxalpha** [comment]
I am not referring to walls, only floors.

**Comment by KorPhaeron** [comment]
This map is going to require code changes to be functional. Areas ruins are allowed to spawn, how monster spawning is handled, turrets not being ignored entirely by mobs, etc.

I'm worried it's going to run into the same problem the asteroid had (big precut tunnels mean no room for hiding things). This looks far easier to game both as a miner and as an ash walker/prisoner.

**Comment by KorPhaeron** [comment]
Testing locally, takes ~80 seconds to dash from the mining base to the necropolis door. Saw two goliaths together at one point and just ran past.

**Comment by KorPhaeron** [comment]
Also we can't use the pylons because those spread cult floors everywhere now

**Comment by Kromgar** [comment]
Just make new pylons that make necropolis floors everywhere

**Comment by Zilenan91** [comment]
If the timer from station to necropolis gate is too little you can probably put some rock walls blocking it off.

**Comment by xxalpha** [comment]
This is not DNM worthy anymore, I checked and the floor types are all proper, just some have redundant icon state edits.

**Comment by KorPhaeron** [comment]
Still DNM since it has invisible rocks and a very easy way to game the bosses built in.

Also monsters don't spawn in most of the map.

**Comment by KorPhaeron** [comment]
Probably gonna take me a couple of days to get to this, and I might end up carving it up and using parts of it as templates instead.

**Comment by Kromgar** [comment]
The snowdome ruins have invisible rocks too

**Comment by Cheridan** [comment]
Yeah, I prefer Kor's template idea. The whole thing behind lavaland is that its randomly generated so it feels different each round, this kind of flies in the face of that.

**Comment by optimumtact** [comment]
so what is the status of this pr then?

**Comment by KorPhaeron** [comment]
Whether or not we use this map or just parts of it I would need to do code changes to make it functional, so I will download the map file from this commit and open my own soon

**Pull request closed without merging**
