### PR TITLE
Adds Zookeeper Bundle to Replace Bee Bundle

### PR DESCRIPTION
**Pull request by wesoda25**
## About The Pull Request

gorilla ooga

## Why It's Good For The Game

cause bee is getting removed 

## Changelog
:cl:
add: Zookeeper bundle
/:cl:

### CODE REVIEW

**Comment by wesoda25** [comment]
not sure if this will be OP might set odds to 1 idk

**Comment by YakumoChen** [comment]
Doesn't this kind of negate the whole point of having gorillas be genetics-only

**Comment by wesoda25** [comment]
Never knew there was a grand code design for gorillas being genetics only

**Comment by HomocidlePancakes** [comment]
>To replace bee bundle

I kinda doubt it will be merged with the reasoning of “I think this meme is stale”.

**Comment by wesoda25** [comment]
If it isn't merged I'll add a removal of it to this PR, its a stupid meme I made a while ago, and I think maintainers won't mind if I want my own stupid meme removed.

**Comment by Shadowflame909** [comment]
we already gotz so many gorillas

send in a leaper bro.

**Comment by Dorsisdwarf** [comment]
why magilitis

**Comment by Krysonism** [comment]
It seems a shame to remove the bee bundle for this. This seems much weaker and less fun to play.

magilitis was always trash  and i don't know if a stun baton and gorilla cubes - the grenade is going to change that.

**Comment by nemvar** [comment]
Only gorillas? This is lame. Give it some leapers, bears, parrots, snakes and ,god-forbid, bees. A zookeeper with only gorillas is pretty boring.

**Comment by Shadowflame909** [comment]
Real Zookeeper kit that wont get merged:

1x Catgirl mutation toxin 1x Lizard Mutation toxin 5x Electropack 1x Riot Dart Gun (Tranquilizer)

**Comment by wesoda25** [comment]
Hmm, might be fun to make a nade which spawns 3 random animals from a large pool, they’d need to bw hostile though.

**Comment by Krysonism** [comment]
> 
> 
> Hmm, might be fun to make a nade which spawns 3 random animals from a large pool, they’d need to bw hostile though.

You might want to give them the same faction if you do that so they don't ignore their targets and just infight.

**Comment by wesoda25** [comment]
im away for a week won’t be able to edit this will be back probably

**Pull request closed without merging**
