### PR TITLE
Thrown objects phase through thrower

### LINKED ISSUE #18670: You can hit yourself with items you've thrown if moving in the same direction as them
Send help I cucked myself and it wasn't fun

### PR DESCRIPTION
**Pull request by 4dplanner**
## About The Pull Request

Thrown objects don't collide with the (living) mob that threw them
## Why It's Good For The Game
Stops you from hitting yourself throwing while running

fixes #18670 

Discussion there called it a hacky fix, but there's been no better fix for multiple years. I personally think it's fine, but even if it wasn't it's not OK to leave the game in a broken state for aesthetic reasons.

## Changelog
:cl:
fix: thrown objects (but not mobs) no longer hit the thrower
fix: mirror shield rebound no longer depends on the original thrower's momentum
/:cl:

### CODE REVIEW

**Comment by spessbro** [comment]
wont that interfere with throwing bodies?

**Comment by nemvar** [comment]
Does this work with returning items? Like eshields for example.

**Comment by 4dplanner** [comment]
Both good points, actually. I'll need to do some thinking.

**Comment by 4dplanner** [comment]
bananium shield resets the thrower on hit, so it works fine. This does let you throw corpses through yourself, which is a bit lame.

**Comment by spessbro** [comment]
well just make it so it ignores only when you're not in aggro grab

**Comment by 4dplanner** [comment]
> well just make it so it ignores only when you're not in aggro grab

that feels a bit too hacky, honestly.

**Comment by MrPerson** [comment]
There's nothing hacky at all about this, imo. The only major issue should be the extremely rare "teleport into the path of a thrown object" situation. That's such a rare edge case, I wouldn't worry about it. 

Why would you want to hit the player with a body they're throwing? Having them collide with the body is stupid, illogical, and unfun.

**Comment by nemvar** [comment]
You can't deny that it's fun when people stun themselves with thrown bodies. At least when you are watching them.

**Comment by 4dplanner** [comment]
Turns out there are some fun unrelated bugs because at some point someone switched speed and range on throw_at

**Comment by 4dplanner** [comment]
I'm not too set either way on the bodies hitting their thrower part, I just didn't want to make too many unrelated changes in a bugfix. If a maintainer decides either way I'll follow it.

One potential reason you might want thrown bodies to still hit their thrower is because it adds an extra tactical dimension to a strangely strong tactic. You can't run straight at someone and throw, you have to run and position and then throw. It's not a big difference, but it is a difference.

**Comment by PKPenguin321** [comment]
>Why would you want to hit the player with a body they're throwing? Having them collide with the body is stupid, illogical, and unfun

Bodies are the only thing you don't have to have in your hands to throw, so if they're on the ground behind you and you try to throw them in front of you you'll hit yourself with them, which is really funny

**Comment by kriskog** [comment]
I love it when people space themselves with a body they are trying to space. It's a rite of passage.

**Comment by Daxxed** [comment]
Big corpse throwing buff, throwing corpses you are dragging behind you OH WOAH
That said, I wouldnt mind.
Those diagonal throws that somehow manage to hit you are annoying though

**Comment by nicbn** [comment]
What about guns? Can the projectiles still hit the shooter?
And what if the thrown object is reflected? It will still not collide with the thrower?

**Pull request merged**
