### PR TITLE
Cleans up some of the more unsavory Valentines pick up lines, cutting them down to being more flirting and less propositioning.

### PR DESCRIPTION
**Pull request by Iamgoofball**
## About The Pull Request

Cleans up some of the more unsavory Valentines pick up lines, cutting them down to being more flirting and less propositioning.

## Why It's Good For The Game

A ton of these were way, way too forward for a corporate mandated valentine's day celebration. Cheesy pickup lines are one thing but a ton of these were encouraging rulebreaking behavior or were things that, if a player said it to another player, an admin would ban their ass for being creepy.

## Changelog

:cl:
spellcheck: Cleans up some of the more unsavory Valentines pick up lines, cutting them down to being more flirting and less propositioning.
/:cl:

### CODE REVIEW

**Comment by optimumtact** [comment]
god your'e cringe

**Comment by dwasint** [comment]
wow this really got closed smh

**Comment by Iamgoofball** [comment]
@optimumtact *you're

**Comment by Draggeru** [comment]
If I would ban people for saying what is on some of these cards they probably should not be in the code.

**Pull request closed without merging**
