### PR TITLE
Ends grey tiding, Assistant now requires 50 hours as security

### PR DESCRIPTION
**Pull request by MrsTonedOne**

### CODE REVIEW

**Comment by YourNeighborsObnoxiousCat** [comment]
what the fuck no please it's all I play

**Comment by Plaguewalker** [comment]
MSO, time to go to the happy house get your wig.

**Comment by Hatterhat** [comment]
image

**Comment by optimumtact** [comment]
Please don't spam this pr with the same comment over and over thanks

**Comment by Hatterhat** [comment]
hi Oranges

**Comment by Pascal125** [comment]
I like this idea, and i believe people brought up fairly interesting comments both for and against it. However brief some may have been. Unfortunately Oranges went on an editing spree as most were for and less against and as such they are all unfortunately lost in a sea of "I don't like this idea." edits.

**Comment by unusualcrow** [comment]
I. LIKE. THIS. IDEA.

**Comment by Buggy123** [comment]
>>Please don't spam this pr with the same comment over and over thanks

!()[https://imgur.com/hRqTQgS]

**Comment by F-OS** [comment]
fuck codebase solutions to admin problems

**Comment by awesine** [comment]
i don't like this idea

**Comment by AverageJoe82** [comment]
Imagine a shift where instead of 0 sec 17 tide we have 17 sec 0 tide, what a day it would be, I would,in fact, tc trade just to see it happen once.

**Comment by kevinz000** [comment]
Red tide

All things said and done it'll be hilarious when all of the greytide is consisted of security veteran elites and the greytide is now 500x more coordinated and robust

**Comment by outbools** [comment]
Chemist should require 0 hours overall so anyone can get MSO his meds when he need them.

**Comment by SgtxRootbeer** [comment]
Here's the problem tho, all greyshits are either 

A, noobs
Or b, vets.
For the noobs, the greytide isn't a problem, for the vets, they already have spent 50 hours playing sec

**Comment by PKPenguin321** [comment]
Red tide is worse, especially if they're new

**Comment by 81Denton** [comment]
How HIGH are you

**Comment by Buggy123** [comment]
Remember, MSO has exclusive access to the server's off button. We should probably do what he wants.

**Comment by RemieRichards** [comment]
>my vote is that we blacklist mso until he reaches the point of maturity where he doesn't try to turn off the servers over the fact that he doesn't like assistants

**Comment by Carbonhell** [comment]
dear assistants,
it's time to fight back

**Comment by Buggy123** [comment]
That's sort of like if we tried to nuke Russia until they agreed to hand over all of their nukes.

Let me reiterate: **MSO has the singular and unfettered power to completely and totally kill TGStation, instantaneously and with no possible way to prevent or avoid it.**

**Comment by Bawhoppen** [comment]
I hope you don't really believe that and are just saying it as a meme

**Comment by Buggy123** [comment]
I mean am I wrong? I kinda doubt MSO is going to play ball that hard but by my understanding he absolutely _could_.

**Comment by Potato-Masher** [comment]
I'm not defending greytiding, but can we stop trying to add code solutions to admin issues? I'm sensing that there are going to be WAY more unforseen issues if this goes through.

(mso this better be a meme pr)

**Comment by Thunder12345** [comment]
@Buggy123 then we'd just get another host, we did it before when SoS went off the rails

**Comment by AlexTheSysop42** [comment]
> An incompetent assistant has to try real hard to ruin someones day.
> How HIGH are you

The key is word incompetent

**Comment by Bawhoppen** [comment]
@Buggy123 
TG doesn't lie in the host. It never did. 
It lies in our hearts.


(but now that I think of it, oranges would probably become the new host if MSO went nuclear...)

**Comment by Bawhoppen** [comment]
Holy crap, the more I think about it, the more and more this looks like a conspiracy for oranges to seize power once and for all

**Comment by JJRcop** [comment]
Another solution I can think of which is compatible wih this change, is adding departmental intern roles.

**Comment by GuyonBroadway** [comment]
Don't be even entertaining the notion of compromising this idea. Assistant fuckery is one of the core parts of ss13 and only the most pig anal mil-sim job simulator paperwork HRP servers would ever dain to meddle with that.

**Comment by nicbn** [comment]
image

**Comment by ChuckTheSheep** [comment]
To expand on JJ's make it so they get armbands or an accessory for IDs for a particular department with minimal access (for both visibility and so demoting would just be confiscating accessory).

Also, maybe assign the person to another player? Maybe a preference to accept an assistant and having it on grants you a slight exp bonus for having to be a babysitter?

**Comment by Kromgar** [comment]
Shouldn't this be a config?

**Comment by Buggy123** [comment]
No.

**Comment by MrStonedOne** [comment]
I should very deliberately point out that almost all of the other ranks have single digit hour requirements.

So a pr limited assistants to 50 hours, 5 to 10 times more than most other ranks, might have a certain poe quality to it.

**Comment by Robustin** [comment]
Who still complains about greytiding? I feel like at this point it's just a scapegoat for "player does something I don't like". 

I haven't seen assistant unleash coordinate griefing in years. And again I can't fathom why forcing bored players into actual limited job slots that have a purpose is seen as desirable. Job slots routinely run out during highpop why would we ever push someone who just wants to fuck around into chemistry or engineering so that when actually useful veteran chemists/engineers come online the only slot open is assistant?

**Comment by Bawhoppen** [comment]
People are taking this PR too seriously

**Comment by Anonymous583** [comment]
This is good.

Fuck assistants. Go to hippie to be tiding faggots.

**Comment by KingPhilipIII** [comment]
We've fucked up. We're producing CAPABLE assistants now who've been forced to learn the best ways to break the rules by combating it. You're creating monsters!

**Comment by arsserpentarium** [comment]
This way security should need 50 hours of assistant exp.For balance reasons.

**Comment by epochayur** [comment]
This is such an idiotic PR I can hardly wrap my mind around it.

Assistant is the definition of a beginner job. Do you seriously want the first job that someone ever picks up to be security of all things? Especially 50 fucking hours of it before they can play the job with the least amount of access/rights of the entire station? If this doesn't just lead to sec officers sitting AFK in the brig, it'll be someone put into a job they don't want or don't particularly care about and doing a half-assed job because of it. 

If you wanna address "greytiding" (which, when was the last time greytiding was a concern since like 2013?), just lock assistant off at 50 hours in any other position. At the least that might keep the people who know better from picking the "dick-around" job. Locking people out of the most absolute basic position before 50 hours of "community service" or however it is you like to think of this as, is a dumb way to try to address it. **Keep it open for the newbies.** You shouldn't have to put in effectively a week's worth of work at a full-time job to play a fake space job, one that's even lower on the totem pole than the janitor. 

Here's a novel concept: if you have problem players, address it in-game through administration, not sweeping mechanics changes that challenge the foundation of the game.

**Comment by epochayur** [comment]
Also, in what way does this "end grey tiding"? The people fucking up the station likely already have 50 hours in sec under their belt just from playing the game. All this does is punish new players trying to get a feel for the game.

**Comment by KingPhilipIII** [comment]
9b67632f-5618-41f0-b1df-42d62a54d8b1

@epochayur

**Comment by epochayur** [comment]
sorry that I missed the part where it said in bold caps "**THIS IS SATIRE**"

**Comment by KingPhilipIII** [comment]
I guess everyone ever should preface every joke now with “Jk” just in case. 

You don’t label humor beforehand.

**Comment by nicbn** [comment]
<joke>Yeah who labels humor beforehand?</joke>

**Comment by GuyonBroadway** [comment]
The issue is that prs that were once considered jokes have now become a thing and irremovable, see cat-ears for more details.

**Comment by Robustin** [comment]
>Its just a joke PR
>Goofball PR with incoherent title that's actually the most important cult change in years gets merged

I don't trust anyone with joke PR's right now.

**Comment by MrStonedOne** [comment]
Normally joke prs get closed shortly after being opened, how ever oranges decided to lock mine and than relocked it after i got kor to unlock it so i'm making them keep this one open for 24 hours before closing it as punishment for mishandling the first version.

**Comment by ninjanomnom** [comment]
Why did we keep this open just because it's mso?

**Comment by HomocidlePancakes** [comment]
Nobody going to find me here...

**Comment by MrStonedOne** [comment]
:eyes:

**Comment by optimumtact** [comment]
it's rewind time

**Pull request closed without merging**
