### PR TITLE
Moveable SMES

### PR DESCRIPTION
**Pull request by rocket2guns**
Added movabled SMES with character effects when not wearing gloves. 

Documentation at: 
http://wiki.nanotrasen.com/index.php?title=User:Rocket2guns

I will add to wiki if accepted

### CODE REVIEW

**Comment by kilkun** [comment]
what did he mean by this

**Comment by KorPhaeron** [comment]
When is Ion coming out?

**Comment by HankMoodyExperience** [comment]
wew

**Comment by kilkun** [comment]
never.

wait for us13 0.3 or whenever it goes public, otherwise the chances of a remake (let alone a paradigm shift remake) are slim to nil.

**Pull request closed without merging**
