### PR TITLE
New closet sprites

### PR DESCRIPTION
**Pull request by nicbn**
[Changelogs]: #
:cl:
imageadd: Closet sprites changed.
/:cl:

*Images outdated, new ones in later comments.*

closet

These fit much better with the other new sprites.

### CODE REVIEW

**Comment by ChangelingRain** [comment]
Can we get some ingame shots?

**Comment by WJohn** [comment]
Very nice improvement over the other versions (namely something like #32825 which is just a direct copy of its predecessor). I'm not huge on how the coffin looks, so that may need a bit of tweaking (it just looks like it's top down rather than 3/4th).

I also think the wardrobe could be done better, it come off as a bit thin and the doors in their open versions are a bit lacking in detail (the other version does the open doors better, but the wardrobe is thinner still than this one and that needs changing).

Gun cabinet absolutely needs a makeover. It has looked ugly since its addition and now would be a great time to like, give it an actual visible interior or... anything at all? Please rework it.

Lastly, for the closets in general I think their floors need a bit better shading, I'm not keen on it just being basically pillow shaded on the bottom there.

Otherwise, these being round is a nice improvement over the other version, but check those out and see if there's anything you can take from it.

**Review by WJohn — CHANGES_REQUESTED** [review]
Check what I mentioned in my comment and see to those changes, please.

**Comment by nicbn** [comment]
By wardrobe you mean the wooden cabinet?

**Comment by The-clown-known-as-Pepe** [comment]
@nicbn the thingies in dorms that you can put stuff in

**Comment by nicbn** [comment]
Well, I have experimented and I found that the most non-distracting that is not ugly way to do the floor shading is using the pillow shadow. Also I have no idea on how to improve the shotgun cabinet. Improvements done by now:

**Comment by nicbn** [comment]
I'm not sure about the closet wall thickness thing. Maybe I'll do another PR for making the closets thicker later.

**Comment by Bawhoppen** [comment]
Rule of thumb for sprite PRs is to ignore all downthumbs and just listen to WJ and other spriter's critique.

**Comment by calzilla1** [comment]
Yup, just like modern art!

**Comment by WJohn** [comment]
The gun cabinet needs further changes to its insides, primarily in how it is super lacking in any sort of contrast with the back wall to the floor, to the outside outline, so it comes off looking like this blob of grey.

Your wardrobe doors could also use some more shading and details to them, they're lacking in anything other than a one pixel doorknob right now (which is for some reason visible from the inside?)

**Comment by nicbn** [comment]
It's not a doorknob it's a screw
But ok I'll take in consideration

**Comment by ExcessiveUseOfCobblestone** [comment]
> doorknobs for your closets

Why are you guys playing byond if you're this rich?

**Comment by pantherpusher** [comment]
What are the chances of directional coffins?

**Comment by PKPenguin321** [comment]
Isn't this like the third time goon closets have been PRed

**Comment by CosmicScientist** [comment]
Obligatory reee

More seriously, the lockers look too thick even if that may just be familiarity with how thin the old ones are. I just don't like looking at it from too far above, maybe?

**Comment by WJohn** [comment]
That can easily be fixed by making them a little bit shorter.

**Comment by praisenarsie** [comment]
@PKPenguin321 these arent goon closets

nicbn sprited them, he even said in the first goon closet pr. Plus you can see the difference

**Comment by nicbn** [comment]
I already made the door 2 pixels shorter, should I make it even shorter?

**Comment by nicbn** [comment]
Changes:


Also all the closets were repositioned to be centralized.

**Comment by Jalleo** [comment]
Why are there so many duplicates for the opened door sprites? That really should be reduced. There are what three copies of the red opened one I think.

**Comment by nicbn** [comment]
@Jallo that's for another PR @WJohn what changes you think that are more important now?

**Comment by WJohn** [comment]
You still need to make them centered, make the closets a little bit shorter (such that they don't touch the top of the tile), and fix the lighting being pillow shaded on the floor of each closet, it looks unnatural.

**Comment by nicbn** [comment]
They already are centered in the horizontal axis. Gonna do the shorter and non-pillow thing

**Comment by ChangelingRain** [comment]
Update your pictures then!

**Comment by nicbn** [comment]
I added a inner border to add sense of thickness to the closets. They are one pixel shorter.

closet

**Pull request merged**
