### PR TITLE
Removes adamantine extracts from DM scientist loadout

### PR DESCRIPTION
**Pull request by EEASAS**
## About The Pull Request
Removes the adamantine extract 
## Why It's Good For The Game
Adamantine shield and armor is busted. There is a roughly 80 percent chance of block with the shield,
and you can tank hits with the armor.
## Changelog
:cl:
del: Removed scientist's admantine extract from deathmatch
/:cl:

### CODE REVIEW

**Comment by Paxilmaniac** [comment]
I can't believe we're removing the one time players actually interact with xenobio content

**Comment by EEASAS** [comment]
> In an environment where the average class has access to one-hit stuns typically sealed away behind admin-intervention, the presence of a bullshit 80% block shield shouldn't be a dealbreaker for the entire class -- if the adamantine shield is really that big of a problem just jettison that part of the class, especially when it's not central to how the class functions nor is it the backbone that makes it competitive.
> 
> Getting rid of the class is as destructive as it is unnecessary. Of course the class has passive healing, that's part of its schtick. You can curate the individual extracts the class has access to if you're that set on balancing it.

the adamantine armor and shield is used by 99% of the players that use the sci loadout but ill think about it

**Comment by MrMelbert** [comment]
It's hilarious that something is considered "too op" for a ghost minigame with no stakes but "perfectly fine" for use on the station itself

**Comment by deathrobotpunch** [comment]
this PR is honestly one of them, scientist is only OP to an extent and relies on plasma heavily and is difficult to use effectively.

stop removing trying to remove something cool and interesting (In a deathmatch minigame specifically) and instead make fun things instead.

**Comment by githubuser4141** [comment]
> It's hilarious that something is considered "too op" for a ghost minigame with no stakes but "perfectly fine" for use on the station itself

because you're not locked into engaging with them, and you're free to chose weaponry of your choice, e.g. you can grab a flashbang, a bomb or whatever. So yeah, there's a handful of loadouts that'd be OP in minigame, but not on-station

**Comment by jughu** [comment]
Uhh lets see.... classes that simply bypass the "blockchance"
Cowboy Whip.
Raider Meathook.
Ripper Sawn off meathook,
Druid gets straight up bombs
Clown can just slip the goofball
Any other class with a gun can just bait him next to a welding tank and they just have to go for it or the game stalemates out
Only class that takes the L is coder which i see as a joke class anyways

**Comment by Iamgoofball** [comment]
I play deathmatch to get away from the perils of actual SS13 and xenobio mains ruin the fantasy

**Comment by EEASAS** [comment]
ill keep scientist but remove only the adamantaine thing extract

**Comment by jughu** [comment]
it isn't broken git gud

**Comment by CCC23** [comment]
skill issue

**Comment by YakumoChen** [comment]
Surprised this is what tg is most mad about and not the engineer turret

**Comment by Elli-Skala** [comment]
As a person who plays scientist I agree it should be more a class with lots of utility but weak in direct combat

Though playing it I mostly use the same couple cores, there should be more plasma sinks like the industrial black (but no one uses that)

Maybe a recurring sepia?

**Comment by deathrobotpunch** [comment]
F49BF11B-E69D-4D6B-9BC5-36E5865769D1

**Comment by moocowswag** [comment]
This has to be a joke pr because it immediately has 3 strikes at a glance

>its not strong to begin with
>its in a for fun gamemode on a map where everyone can choose to be op 
>the pr doesnt even try to compare “80% block rate you can tank hits” is nothing when power is relative, what loadout were you using that made you feel useless against it?

**Comment by EEASAS** [comment]
damn

**Pull request closed without merging**
