### PR TITLE
Some shuttes rework. Allow many shuttles of one template to work at the same time.

### PR DESCRIPTION
**Pull request by Dennok**
## About The Pull Request

Refactored #53687 Rework of #45024

Multiple shuttles created from one template that work simultaneously
<details>

image

</details>

add replace button to shuttle panel, load button now only load new shuttle, replace replaces only original shuttle

<details>

image

</details>

shuttle template loads as shuttle

new shuttle console connects to shuttle on construction/spawn

new navigation computer connect to shuttle on construction/spawn

docking_port id now unique, add count to id if id already in work

many docks from one base template
<details>

image

</details>

Now 'id' true unical, replaced part of it behavior by `port_destinations`. You can set many docks with one `port_destinations` but all it have different `id`, you can send shuttle to docks ID

Now shuttle console collect list of ID's by matching console(shuttle) and dock `port_destinations`. 
And you can send shutle to dock ID.

Temporarily make stationary docking_port's set up `port_destinations` on Initialise(). just add initial `id` to `port_destinations`.
Until someone change `id` of all mapped  stationary docking_port's to `port_destinations`

Previous console collect list of ID's by matching console(shuttle) and dock ID. 
And if list have matching ID's you you can send only to first match ID in SSshuttle.shuttles list.

Some old, partially updated, explanations
<details>

About ID and name
Actual: 
image
image
Placed from one template docking_port share one id, Old interface allow us to see multiple destinations, but when we try sent shuttle to it we sended only to first docking_port, because console send us to id, not to determined docking_port.

After my changes:
image
id generated from base id if we already has one with mach id

First check that SSshuttles dont has docking_port with mach id (for stationary and mobile separately).
If find, add counter in next of original id.(not in this picture, it is better visible on upward pictures)
This way allows us to be confident that we have base shuttles for hard defined things, evacuation, arrival, cargo, etc.

</details>

## Why It's Good For The Game

<details>

Now we don't need code new areas, consoles, docking ports to create new shuttles from single template.
If you need second whiteship, just place it.
If you want new docking port just place it,
For whiteship's Deep Space just place whiteship dock template.
</details>

Now we dont need code new areas, consoles, docking ports to create new shuttles from single template.
If you need second whiteship, just place it.
If you want new docking port just place it, no need to VV it id, and VV shuttle console destinations. Just make sure that it destynation_type same, and it fit in width and height.
For whiteship's Deep Space just place whiteship dock template.

Many working shuttles at one time from one template is great

## Changelog
:cl:
add: replace button to shuttle panel, load button now only load new shuttle
tweak: shuttle template loads as shuttle
add: new shuttle console connects to shuttle on construction/spawn
add: new navigation computer connect to shuttle on construction/spawn
tweak: docking_port id now unique, adds count to id if id already in work
fix: ports from one template now work
/:cl:

### CODE REVIEW

**Comment by LemonInTheDark** [comment]
If you could elaborate on the problem you're solving it would make reviewing this pr a lot easier

**Comment by optimumtact** [comment]
Dennok nobody knows what you are trying to do, you need to try to explain it

**Comment by Dennok** [comment]
> Dennok nobody knows what you are trying to do, you need to try to explain it

I want make it able to load multiple whiteships that work at one time.
And some optimization.

**Comment by Timberpoes** [comment]
Why do you want to be able to load in multiple whiteships at once?

**Comment by Dennok** [comment]
I want on hot run add/remove stationary docking ports and shuttles.
Whiteships only for example. I mean all shuttles that have one id. Mining, etc.
For what? For events. Or for modes.

**Comment by Misdoubtful** [comment]
Ran into this not too long ago, I appreciate the idea of greater qol with docking ports.

Does this mean more shuttle tools soon to come? I hope so.

**Comment by Dennok** [comment]
> Ran into this not too long ago, I appreciate the idea of greater qol with docking ports.
> 
> Does this mean more shuttle tools soon to come? I hope so.

What tools you want?

**Pull request merged**
