### PR TITLE
buffs captain's and centcom jumpsuit

### PR DESCRIPTION
**Pull request by Fikou**
## About The Pull Request

gives captain jumpsuit 5 brute protection and 50 fire and acid protection while increasing the strip delay to 50 like sec has
also gives the same but with 30 fire and acid protection to centcom officer jumpsuit (used by centcom officials and ert)
and gives same but with 10 brute protection and 60 strip delay like hos to the centcom commander jumpsuit (used by centcom commanders and death squad)

## Why It's Good For The Game

the highest ranking people should get some armor

## Changelog
:cl:
balance: Central Command finally used more of their budget on their highest ranking people's jumpsuits, maybe this will help a little, captain
/:cl:

### CODE REVIEW

**Comment by loserXD** [comment]
balance:

**Comment by Fikou** [comment]
> balance:

ok i am retard shut up

**Comment by Shadowflame909** [comment]
sec jumpsuits peak comfy

**Comment by CPTANT** [comment]
I actually dislike how good the captains gear has already become. IMO the captain should be a command role, and not a one man solution to everything.

**Comment by necromanceranne** [comment]
Captains are often prone to being shot with ballistics, so increasing their armor is fine to me.

**Comment by CPTANT** [comment]
Also I don't think security officer jumpsuits should have an increased strip delay in the first place.

**Comment by ExcessiveUseOfCobblestone** [comment]
armor is so dumb right now because you can just lolnope it via hitting a non covered/ lowly armored bodypart.

> Captains are often prone to being shot with ballistics, so increasing their armor is fine to me.

We don't just reinforce armory because it's often prone to being looted. The current armor is certainly capable of mitigating bullets already, I don't really see a driver for this change.

**Comment by habader** [comment]
powercreep

**Comment by Shadowflame909** [comment]
>Be me cap

>Review the chefs exquisite menu

>All of a sudden this clown pulls out a bulldog shotgun and 2 shots me before I can react

Sometimes you die. But buff caps ballistic's defense. Aaaaa

**Comment by ATH1909** [comment]
For reference, the current standard sec uniform gives 10 melee armor (and some other armor, IIRC).

Also, this PR will NOT affect the captain's resistance to bullets; bullet armor and melee armor are TWO SEPARATE THINGS IT'S NOT "BRUTE" ARMOR IT'S BASED ON THE METHOD OF DAMAGE DELIVERY HOW HARD IS THIS TO UNDERSTAND AAAAAAAAAAAAAAAAAAHHHHHHHHHHHHHHHHHHHHHHH

**Comment by Shadowflame909** [comment]
But nobody cares about brute armor. If the captain is getting beat up in melee then its already too late for him. Since all of his sec team was clearly murdered by revs/cult/whatever.

Ballistics is the killer of the cap

**Comment by Detective-Google** [comment]
yeah brute armor for the cap is a non issue usually, if the cap is taking brute damage without being able to whip whoever is dealing it it's already over, that being said, increased ballistics armor would make sense for the cap "muh' kevlar jumpsuit" or whatever, since getting shot is a much more realistic issue for the captain in a fight.

**Comment by SpaceManiac** [comment]
Captains and CentCom commanders already get outerwear armor, so I don't think armoring the jumpsuit is necessary.

The PR can be reopened if another maintainer is interested.

**Pull request closed without merging**
