### PR TITLE
Colossus will now chase down sleeping carp users

### PR DESCRIPTION
**Pull request by ChangelingRain**
:cl: Joan
add: Trying to use sleeping carp against the colossus will now anger it.
/:cl:

It will chase you down at high speed and murder your ass for daring to try and cheese it.

I think this should be a relatively fair speed given that 17tc for total immunity to a boss's entire attack pattern is bullshit.

### CODE REVIEW

**Comment by Ergovisavi** [comment]
I would be extremely cautious with dealing with outliers in this fashion. It's very easy to enter into a design that's just shutting off a playstyle, similar to how antimagic field worked in PvP in Demon's Souls: It just shut off your ability to cast magic, utterly ruining a playstyle for little more than the express purpose of shitting on it with no real concern for the player on the receiving end. 

There's nothing wrong with limiting the effectiveness of it, but be careful of what you touch in that way.

**Comment by ChangelingRain** [comment]
"I am immune to everything this boss can practically do" is not a playstyle, or it shouldn't be if it is.
I get your point, but this is one of those things that is definitely not good to allow just because of how it works.

**Comment by Kromgar** [comment]
Uh... they cant block melee attacks and they cant use guns dude. Most people use sleeping carp to lure it to the station

**Comment by KorPhaeron** [comment]
do people actually kill the boss like this?

**Comment by ChangelingRain** [comment]
I'm not sure if they actually kill it but it certainly gets lured to the station, which is... probably too much destruction for 17tc.

**Comment by Kromgar** [comment]
Is it really?

**Comment by ChangelingRain** [comment]
I'm having difficulty trying to figure out how it wouldn't be, given that it's a huge, high-health mob that can't kill you, will follow you around, and just ruins everything in the area.

**Comment by Kromgar** [comment]
You do realize colossi have melee attacks right?

If your on the shuttle with them your most likely dead

**Comment by Archie700** [comment]
The actual intent is to prevent traitors from baiting them to the station easily.

**Comment by Kromgar** [comment]
Even non traitors can do it easy if you know what your doing. Just surround yourself with botany machines and it can never touch you

**Comment by ChangelingRain** [comment]
That is probably totally wrong thanks to a fix in one of my prs a while ago.

**Comment by Archie700** [comment]
>Just surround yourself with botany machines and it can never touch you

I don't think that should be a thing.

**Comment by KorPhaeron** [comment]
@optimumtact

the tag aaaaaaa

**Pull request merged**
