### PR TITLE
Swaps Genetics and Cyto tech

### PR DESCRIPTION
**Pull request by Vect0r2**
## About The Pull Request

This swaps the cyto and genetics tech- this means that you get tech as bio -> genetic -> xenobio -> cyto

## Why It's Good For The Game

It means that you can actually get genetics tech before botany and xenobio- and is also not locked behind 30k points. Genetics is normally seen as a "more simple" thing than cyto, which means that the tech should come early.

## Changelog
:cl:
balance: Cyto and Genetics tech are swapped
/:cl:

### CODE REVIEW

**Comment by GPeckman** [comment]
I don't think either cytology or genetics should be locked behind 30k points tbh

**Comment by MTandi** [comment]
> Genetics is normally seen as a "more simple" thing than cyto, which means that the tech should come early.

It's not a matter of harder, but rather a matter of benefits. Genetics provide permanent buffs, while cytology is just about creating mobs that don't empower you.

All strong buffs in the new tree have higher tiers - exotic ammo, experimental tools, strong implants. All of this is timegated to not let people speedrun multiple strong buffs.

Also, why do you want the genetics node early if you have everything from this node in the genetics room roundstart?

**Comment by Donglesplonge** [comment]
> Also, why do you want the genetics node early if you have everything from this node in the genetics room roundstart?

mainly because genetics is the first to finish, just in general of all the science jobs (and i'd argue most likely any job), so if you wish to make public consoles around the time you do get finished you either now have to step on the scientists and botanists toes to get your equipment researched, all while wasting points doing so, or hope that someone will, with an experiment that was already never researched outside of the geneticists themselves, research it. 

i can understand that genetics provides (nearly) permanent buffs, and you can have multiple at a time, but the research itself was already fairly underutilized by people because, well, why would scientists need it ever, plus geneticists are already in short supply due to it being a very unpopular job, locking the equipment they could utilize without destroying their office because they can buff everyone with mediocre to moderate upsides just adds needless tedium to a job that already suffers heavily from needless tedium, and kinda makes the tech itself useless, because like you say, everythings already available roundstart, so it'd just be geneticists now sitting out in public with their consoles and scanners so they don't have to move it later because they won't be getting their tech ever.

**Comment by MTandi** [comment]
This reasoning reminds me of nanomachines that were completed early and had people set up public chambers for free buffs.

**Comment by Vect0r2** [comment]
> > Genetics is normally seen as a "more simple" thing than cyto, which means that the tech should come early.
> 
> It's not a matter of harder, but rather a matter of benefits. Genetics provide permanent buffs, while cytology is just about creating mobs that don't empower you.
> 
> All strong buffs in the new tree have higher tiers - exotic ammo, experimental tools, strong implants. All of this is timegated to not let people speedrun multiple strong buffs.
> 
> Also, why do you want the genetics node early if you have everything from this node in the genetics room roundstart?

As an antag I love to get the genetic scanner to scan people to take identity more easily. It is something that doesn't START on the station, and only genetics get it, also when there are spys it seems like it takes 30 seconds before all of genetics is stolen.

**Comment by Donglesplonge** [comment]
> This reasoning reminds me of nanomachines that were completed early and had people set up public chambers for free buffs.

the problem is that genetics is nowhere near nanomachines strong, nor nowhere near as popular as nanomachines ever where, plus its buffs aren't anywhere near important enough that you'd realistically always need to go to the public gene console every time every round because they aren't that good, i'd say trust me on that one but its something you'd have to observe to get, people will just pass it up if its not dangled in their face.

**Comment by GuillaumePrata** [comment]
> so if you wish to make public consoles around the time you do get finished

Public consoles are really lame tho, McDonald drive through and get your freebies design.

If it is later on in the tech tree, it pushes crew to work closely with the geneticists, go into their lab for power, open ways for the sandbox to unfold out of that interactions. It is way better than the public chamber being made so early that no one bothers to talk with geneticists.

Ff genetics wasn't so easy to mass produce passive power ups like how public consoles do, we could get away with giving them more power easier.

**Comment by Vect0r2** [comment]
> > so if you wish to make public consoles around the time you do get finished
> 
> Public consoles are really lame tho, McDonald drive through and get your freebies design.
> 
> If it is later on in the tech tree, it pushes crew to work closely with the geneticists, go into their lab for power, open ways for the sandbox to unfold out of that interactions. It is way better than the public console being made so early that no one bothers to talk with geneticists.
> 
> If genetics wasn't so easy to mass produce passive power ups like how public consoles do, we could get away with giving them more power easier.

This tech can just let you make more consoles: you can just move the starting consoles out. The thing is with spys your consoles can be stolen easily, and there is no way to replace it. There is also the fact that the genetics scanner is round start ONLY if you have genetics.



> > Genetics is normally seen as a "more simple" thing than cyto, which means that the tech should come early.
> 
> It's not a matter of harder, but rather a matter of benefits. Genetics provide permanent buffs, while cytology is just about creating mobs that don't empower you.
> 
> All strong buffs in the new tree have higher tiers - exotic ammo, experimental tools, strong implants. All of this is timegated to not let people speedrun multiple strong buffs.
> 
> Also, why do you want the genetics node early if you have everything from this node in the genetics room roundstart?

The thing is there is no reason to not have this node earlier, when you ALREADY have these consoles, and timegating this tech will not stop public consoles: it will keep genetics from being able to do it's job if the consoles are destroyed. If you want to mass produce TK or hulk, you can already do that without this tech.

**Comment by GuillaumePrata** [comment]
> This tech can just let you make more consoles: you can just move the starting consoles out. 

I know, but unless we go so far to make the roundstart consoles some magic variant that can't be moved, this is as far as we can go and is enough IMO.

> The thing is with spys your consoles can be stolen easily, and there is no way to replace it.

Antagonist should have negative effects on the round.

> There is also the fact that the genetics scanner is round start ONLY if you have genetics. 

Now this can easily be fixed by itself, other jobs all have spare equipment for job swaps.

**Comment by MTandi** [comment]
>This tech can just let you make more consoles: you can just move the starting consoles out. The thing is with spys your consoles can be stolen easily, and there is no way to replace it. There is also the fact that the genetics scanner is round start ONLY if you have genetics.

>Antagonist should have negative effects on the round.

People ask why Telecomms are where they are, and the reason is similar to what @GuillaumePrata is saying. 

Telecomms are in a secured area, and a high value target.
When they're down, there's tech storage with tcomms part in engineering for repairs.
When both are unavailable, then the crew is fucked and they need to research it to print the spare parts.

If I put telecomms early in the tree, then there's little point in having that storage - you can print everything in a techfab.

**Comment by MTandi** [comment]
>As an antag I love to get the genetic scanner to scan people to take identity more easily.

Moved genetic scanner to tier 1 node - bio_scan in scope of #84086 for this use case.

**Comment by Donglesplonge** [comment]
> > so if you wish to make public consoles around the time you do get finished
> 
> Public consoles are really lame tho, McDonald drive through and get your freebies design.

its next to the only way to get crew to show up to interact with the content you do get access to in genetics, short of printing 40 syringes of the good stuff and dumping it all in medical and telling them to sort it out, its legitimately one of the ONLY ways i've been able to get people to actually attempt to interact with the job, and it takes all the effort on your part to do so, the only time i've seen people go out of their way to do the opposite is when its a chaplain running burdened sect, or someone looking to grief with hulk, this isn't xenobiology where its practically free AND has good buffs, we're running on fumes with these ones.
 
> If it is later on in the tech tree, it pushes crew to work closely with the geneticists, go into their lab for power, open ways for the sandbox to unfold out of that interactions. It is way better than the public console being made so early that no one bothers to talk with geneticists.

nobody talks to geneticists, they just don't, even on rounds where there wasn't public consoles up and ready, nobody still actively went out of their way to get genetics powers, or talk to the geneticists, because the powers suck, even on maps where the windows right out in front and center, its just the nature of them, and the resulting nature of the powers being stomped out so early by gear you get for free with minimal work (grey bull, EVA/fire suits, insulated gloves, chemicals) that you can't force it either, its in an awkward position where its so bad that nobody wants to use it because of how bad it is, and the only times people do want to use it its a direct tie-in with their jobs, or they need hulk.

> If genetics wasn't so easy to mass produce passive power ups like how public consoles do, we could get away with giving them more power easier.

public consoles were never a make or break for genetics, you don't see new powers PRs or any buffs because people have a genuine lack of interest in the job because it sucks, new powers aren't gonna invite anyone but gearhounds lusting after their free stuff unless they're mediocre or not in their wheelhouse, because the minigame, how you interact with people, the other systems tied to it, all of its bad, its just bad.


i know that i'm biased towards the point because this is the main job i play, but all of this stuff compounds into a really crippling downgrade to your ability to actually provide for the crew, because nobody wants to put in the work to get the stuff you make, its shifting their ability to make it easier for people to give the people what they want away from the power of the geneticist and into the hands of people who, quite frankly, weren't and never will be really interested in providing for you (botanists and scientists), so you just flat out lose on all fronts.

**Comment by GPeckman** [comment]
There's another thing I'd like to bring to attention:

323802817-097d47c3-c8c9-459d-8b86-d1b458ec5f8a

Moving genetics to the end of the tech tree absolutely seems like a nerf to me. Did you actually talk to Mothblocks about it beforehand or not?

**Comment by Vect0r2** [comment]
> There's another thing I'd like to bring to attention:
> 
> 
> 
> 323802817-097d47c3-c8c9-459d-8b86-d1b458ec5f8a
> 
> 
> 
> Moving genetics to the end of the tech tree absolutely seems like a nerf to me. Did you actually talk to Mothblocks about it beforehand or not?

I- I am moving it forward in the tech web, not moving it to the back. It was at the back before, now it is not.

**Comment by Vect0r2** [comment]
> > The thing is with spys your consoles can be stolen easily, and there is no way to replace it.
> 
> 
> 
> Antagonist should have negative effects on the round.
> 

Yes, they should have a negative effect on the shift, but said negative effect shouldn't be making a job impossible to play or enjoy until you are 45 minutes into the shift. It's not only negative, it's just not fun.

**Comment by GPeckman** [comment]
> I- I am moving it forward in the tech web, not moving it to the back. It was at the back before, now it is not.

Sorry, that message was directed at MTandi. The original change was a seemingly unapproved nerf, and this PR is good because it undoes that.

**Comment by ExcessiveUseOfCobblestone** [comment]
whats the lore behind putting either of them at 30K points again?

**Comment by MTandi** [comment]
> whats the lore behind putting either of them at 30K points again?
> 
> Is the intention behind the genetics change that someone oneday is going to make genetics good ergo its slotted already in the spot where it "needs" to be?

It is 8K points RN, not 30. 
Has two simple discount experiments, that give 4k each.

Locked by two simple experiments:
- vat grown slime - take biopsy off grey slime, grind meat or tofu, put into a vat, scan
- mutated plant scan (harvest a plant with around 30 instability, make seed of the new specie, plant into soil, scan.)

I have already moved the problematic gene scanner to the tier one node in #84086

The reasoning behind the genetics being at t4 (8k of previous points) is that they provide powerups, and the new tree puts all significant powerups to the later nodes.

Nothing has been done to the roundstart genetics. If you're done doing your job, just deconstruct the console and build it outside, you won't need it anyway if you're done.

The lore behind it is as on the image, natural progression on biology tree and convergence with a plant DNA node of the same vibe:
image

**Comment by Donglesplonge** [comment]
> It is 8K points RN, not 30. Has two simple discount experiments, that give 4k each.

combined total, you have to get all 4 of those nodes in order to research this one, the discounts are nice though

> Locked by two simple experiments:
> 
> * vat grown slime - take biopsy off grey slime, grind meat or tofu, put into a vat, scan
> * mutated plant scan (harvest a plant with around 30 instability, make seed of the new specie, plant into soil, scan.)

only one of these experiments is something a geneticist can do without trouble (botanical, because of the public garden), why should they have to rely on a job that isn't even connected to their department, and another that doesn't need the research because its so high up and not a part of their job?

> Nothing has been done to the roundstart genetics. If you're done doing your job, just deconstruct the console and build it outside, you won't need it anyway if you're done.

deconstructing the consoles removes all the genes stored on it, you'd have to either disk all of the genes and manually put every single one back onto at least one console (this takes quite a while to do), or just live with not having everything there, its still a huge downside.

**Comment by Donglesplonge** [comment]
> > It is 8K points RN, not 30. Has two simple discount experiments, that give 4k each.
> 
> combined total, you have to get all 4 of those nodes in order to research this one, the discounts are nice though.
> 
> > Locked by two simple experiments:
> > 
> > * vat grown slime - take biopsy off grey slime, grind meat or tofu, put into a vat, scan
> > * mutated plant scan (harvest a plant with around 30 instability, make seed of the new specie, plant into soil, scan.)
> 
> only one of these experiments is something a geneticist can do without trouble (botanical, because of the public garden), why should they have to rely on a job that isn't even connected to their department, and another that doesn't need the research because its so high up and not a part of their job?
> 
> > Nothing has been done to the roundstart genetics. If you're done doing your job, just deconstruct the console and build it outside, you won't need it anyway if you're done.
> 
> deconstructing the consoles removes all the genes stored on it, you'd have to either disk all of the genes and manually put every single one back onto at least one console (this takes quite a while to do), or just live with not having everything there, its still a huge downside, plus you don't get enough disks to make it a single trip, so you'd have to then go and purge a couple of disks so you can move everything else, while also keeping track of what is and isn't already there.



i just want to make the point clear that i don't think this has to be something you instantly research and should definitely be a freebie every single round because lol lmao its useless to everyone else but the one group who signed up for it, its just that it being locked behind 2 required experiments, and being so deep in the tree, and being a large chunk of points to get to, and being something neither group of the required experiments want, hampers it heavily, it doesn't have to be cheap, just not so damn expensive and labor intensive, its just not worth its price.

**Comment by MTandi** [comment]
> only one of these experiments is something a geneticist can do without trouble (botanical, because of the public garden), why should they have to rely on a job that isn't even connected to their department, and another that doesn't need the research because its so high up and not a part of their job?

Xenobio is also science. I've also added xenobio access to geneticists in #84086 where they can pefrorm both of these experiments

> deconstructing the consoles removes all the genes stored on it, you'd have to either disk all of the genes and manually put every single one back onto at least one console (this takes quite a while to do), or just live with not having everything there, its still a huge downside, plus you don't get enough disks to make it a single trip, so you'd have to then go and purge a couple of disks so you can move everything else, while also keeping track of what is and isn't already there.

Don't you need to move the genes with disks when you build a new console anyway? And There are multiple consoles in genetics, you can spare one of them if you're done discovering all genets.

And you're bringing a matter of disks not being able to store multiple mutations, which is a separate topic.

> i'm not trying to say that this should be a freebie every round, nor should it exactly be all that cheap, but its just that its locked behind two required experiments, both of which don't interact with gene

Yes, just like plasma guns require experiment with plasma, cryogenics require crystalizer tube unlocked, and robotic firearms locked by the explosive experiment.

I don't see any problem with that.

If you are a GENETICIST, then you should know how plant mutations work and basics of biology. The fact that it's not related to profession is purely the way how our departments split up. I think that Botany, Genetics, Cytology and Xenobiology should all be a part of **Biology department**.

@GPeckman so answering to your question, I don't see any nerf in my changes, and the valid issues that guys mentioned are already adressed in #84086.

**Comment by Donglesplonge** [comment]
> If you are a GENETICIST, then you should know how plant mutations work and basics of biology. The fact that it's not related to profession is purely the way how our departments split up. I think that Botany, Genetics, Cytology and Xenobiology should all be a part of **[BIOLOGY department](https://discord.com/channels/326822144233439242/1252907418090999868/1252907418090999868)**.

so what you're saying is that the current changes are being put on for a document that hasn't been approved yet? nor has a guarantee to pass? also no, as a geneticist i don't need to know anything about plant mutations or cytology, because neither of them benefit the job, in your project sure whatever, but there is literally no system that bridges it in a positive manner, genetics has one crossover mechanic with virology and its also universally panned because its a bad mechanic, both in how cheap it is and how odd it is, it just doesn't make sense.

> Don't you need to move the genes with disks when you build a new console anyway? And There are multiple consoles in genetics, you can spare one of them if you're done discovering all genets.

yes, you do need to move genes with disks already, the issue is that you're having to flub your department and move all your stuff into the main hallway, which is gonna make it a bastard for other people who might, say need to steal it, because i wouldn't just move one of them, i'd be moving all of them, theres no reason to leave one behind if it'd be more efficient for everyone evolved if there was more than one console, so its generally what you'd want to do

**Comment by MTandi** [comment]
> so what you're saying is that the current changes are being put on for a document that hasn't been approved yet? nor has a guarantee to pass?

No, this is me reiterating the point, why Genetics is a logical progression of cytology, xenobiology and botany. I didn't just randomly put it on tier 4, neither was it supposed to nerf something.

**Comment by ExcessiveUseOfCobblestone** [comment]
I think the solution is to make sure theres an alternative (IE Cargo, tech storage). I do not stan with the idea a base job you can signup for can be trolled with no way to fix it until a strict timegate has passed because its later in the tree. Even tcomms has fallbacks.

Theres also the alternative of maybe just combining trees to be a generic gene manipulation tech unless theres a particular reason you need it in this configuration. Honestly you could just make them all a "singular" T4 tech, divided into 3 subsections so the total tech is T4 price but each section is worth 1/3 of that. While I understand the argument and trying to blend mechanics/immersion into building a nice tech tree (which I respect), i think mechanically speaking gene machine is not worth currently the cost so its a hard ask to get people to buy it especially when it has prereqs that aree experiment-locked to completely different jobs.

**Comment by MTandi** [comment]
> I think the solution is to make sure theres an alternative (IE Cargo, tech storage). I do not stan with the idea a base job you can signup for can be trolled with no way to fix it until a strict timegate has passed because its later in the tree. Even tcomms has fallbacks.

I think that this is the best solution. Breaking it into smaller nodes will break the whole design of the tech tree.
And I doubt that these extra circuit boards will be used frequently anyway. 

If they will be, then it's a sign that there is indeed an issue.

**Review by ExcessiveUseOfCobblestone — CHANGES_REQUESTED** [review]
plan on closing unless I hear a good argument for the tech swap vs. alternative sources of the board for spares (which should be pr'd differently).

**Comment by Donglesplonge** [comment]
i'd be happy if there was any other way to reliably get the boards in a less efficient manner yeah, i think everyone could get on board with it

**Comment by Vect0r2** [comment]
That's fair

**Pull request closed without merging**
