### PR TITLE
Refactors and nerfs Fleshmend

### PR DESCRIPTION
**Pull request by ghost**
:cl: Xhuis
balance: Fleshmend can no longer be stacked several times at once.
balance: Fleshmend no longer heals changelings who are on fire, and heals burn damage half as quickly as brute and oxygen damage.
code: Fleshmend has been refactored into a status effect.
/:cl:

Fleshmend is one of the abilities that makes changelings unkillable combat juggernauts with essentially no counterplay, so I decided to change it:
* First of all, refactored it into a status effect that cannot stack, meaning that only one instance of Fleshmend can be active at once
* Instead of healing 10/10/10 brute/burn/oxy damage, it now heals 10/5/10, emphasizing changelings' weakness to fire
* If a changeling is on fire, Fleshmend will not function at all

This keeps Fleshmend powerful for healing in and out of combat, but adds counterplay to it and gives changelings something to fear: fire. With an extinguisher, they still need to manage their inventory to use it, and even with a fire-immune suit and helmet using the fire on them as a weapon will be unable to use their Fleshmend trump card to outheal any damage they take.

I'll be keeping an eye on changelings after this is merged and adjusting accordingly.

### CODE REVIEW

**Comment by DaxDupont** [comment]
>It still has no immediate message or sound cues, but examining someone with Fleshmend active will reveal it (I don't consider this necessary to the nerf and I'd be fine with removing it; I just put it in since it felt right to me)

please remove

**Comment by Hatterhat** [comment]
>skin rippling like liquid
damn son

**Comment by coiax** [comment]
For bonus points, make the examination text only visible if skin is visible. You know, in case they're in a hardsuit.

**Comment by juanototo2** [comment]
## A T O M I Z E

**Comment by coiax** [comment]
Atomize what? It's a rebalance, and refactoring at the same time. It's all touching the same feature, and they're all linked.

**Comment by Xhuis** [comment]
As the feedback on the examine text is slightly controversial, I think I'll cut it entirely; it was also intended to let changelings see if they're still healing, but now that Fleshmend is a status effect they get a HUD alert anyway.

**Comment by Dorsisdwarf** [comment]
Finally, a weakness of lings to fire that doesnt suck.

**Comment by Xhuis** [comment]
The lore of keeping changelings from being unkillable juggernauts; if you want a fluff explanation, the changelings' inbuilt fear of fire is strong enough to interfere with fleshmending even when they seem protected.

**Comment by JohnMcLaime** [comment]
Unkillable? You guys still have 1 hit tasers, explosive lances which instagib targets (unless they are using slow ass eod suit/hardsuit).

**Comment by Xhuis** [comment]
A single changeling with an arm blade has infinite healing and infinite adrenaline should they buy the abilities. Short of that instant gib, nothing can kill a ling that just heals the damage it takes instantly or immediately undoes the taser shot.

**Comment by coiax** [comment]
I mean, it's unlimited healing given enough time, but they are vulnerable to high levels of burst damage.

Perhaps TG needs a Dagon.

**Comment by Xhuis** [comment]
This is ready for review/merge/maintainer thoughts or input whenever.

**Comment by coiax** [comment]
@Xhuis dagons when

**Pull request merged**
