### PR TITLE
Removes a ton of bloat from several clothing files and inhands

### PR DESCRIPTION
**Pull request by ghost**
Part 1 of 2, of the https://github.com/tgstation/-tg-station/pull/7107 project.

All of these are unused unless stated otherwise at the bottom.
Icon state removals are as follows.
## icons/mob/suit.dmi

s_ninja_old
poncho
webbing
hosdnavyjacket
officerdnavyjacket
wardendnavyjacket
## icons/mob/uniform.dmi

blackf_s
hop_old_s
ba_suit_s rename --> bar_suit_s
johnny_s
tourist_s
robotics2_s
chemist_new_s
genetics_new_s
scientist_new_s
virologist_new_s
cargo_s
scratch_s rename --> white_suit_s
redcoat_s
jensen_s
hosdnavyclothes_s
officerdnavylothes_s
wardendnavyclothes_S
++cargotech_d_s
bluepants
militarypants
## icons/obj/clothing/suits.dmi

hardsuit_old
bombsuitOld
rad_old
johnny
s-ninja-old
webbing
hosdnavyjacket
officerdnavyjacket
wardendnavyjacket
## icons/obj/clothing/uniforms.dmi

johnny
nazi
hop_old
blackmedical
mario
luigi
ba_suit rename --> bar_suit
tourist
robotics2
chemist_new
genetics_new
scientist_new
virologist_new
scratch rename --> white_suit
redcoat
jensen
securityold
hosdnavyclothes
officerdnavylothes
wardendnavyclothes
bluepants
militarypants
## Inhand files

fire_suit.dmi
johnny rename --> brownjsut
ba_suit rename --> bar_suit
r_feet
r_hands
r_head
daederic
cueball
scratch rename --> white_suit
jensensuit
jensencoat rename --> hostrench
ice_tea_can
energy_drink
cespace_suit
cespace_helmet
## REMOVALS:

Johnny five aces jacket and jumpsuit (rip goonstation memes)
Johnny emote, see above
Alternative 'medisci' clothes that haven't been used for years
## CHANGES:

Changed "Adam jensen beard" to just "jensen beard". Same for the hairstyle. I don't mind these, and I don't even mind that they're character references, just be more subtle about it when you add shit like this.
Changed some inhand states, namely speargun (we've always had these inhands? huh..)
Readded scratch suit, named 'white suit' with a black undershirt.

### CODE REVIEW

**Comment by Iamgoofball** [comment]
>removing *johnny

fuck no :-1:

**Comment by TZK13** [comment]
It's not even used at all who gives a fuck.

**Comment by Cheridan** [comment]
I've seen one person use *johnny ever, I think. Just use *me and copy-paste in the message, whatevs.

**Comment by Yakk** [comment]
Related: tan pants and khaki pants are the exact same sprite.

Also johnny is a goon meme please go goofball.

**Comment by Dorsisdwarf** [comment]
Goon?

You mean New TGstation, right?

**Comment by Chocobro** [comment]
purple lawyer suit is very commonly used. lawyer gets it when they spawn in. there's also one in the closet in his office. rest of those seem fine to be deleted, though.

**Comment by dannno** [comment]
Why did we even have mario, luigi, and nazi jumpsuits ahahahahah what the fuck
good pr kill memes and doesnt afraid of goonbabies :+1:

**Comment by Miauw62** [comment]
keep the purple lawyer suit, please.
sprite matters are one thing where majority opinion matters.

**Comment by paprka** [comment]
I did not touch the purple lawyer suit in this iteration. If I change lawyer stuff it will be in a different PR, it was stupid of me to change it in my last one but I got anxious and thought 'well gee i could just change it now' but I will do that shit later.

**Pull request merged**
