### PR TITLE
RADIMMUNE species can no longer be used for radiation free DNA research

### LINKED ISSUE #13451: Plasmamen can have their DNA modified by the genetics DNA machine, but they will not be affected by the radiation.
Kind of a consistency issue as being rad immune should make it so radiation cannot modify your DNA. Also it means that geneticist plasmamen can easily be used as test subjects and never have to worry about stopping to heal or decrease rads.

### PR DESCRIPTION
**Pull request by ShizCalev**
🆑 shizcalev
tweak: "Radiation immune species are now incompatible with the radiation based genetics DNA scanner/modifier."
/🆑

Closes #13451

DNA scanners use radiation to alter DNA of a being, however races such as Plasmamen are immune to radiation. This results in the DNA scanner altering their DNA without any radiation sickness related damage or drawbacks, making them a perfect subject to blast away at. 

The DNA scanner will now check if a mob is immune to radiation, and if so, they will not be an applicable target for DNA modification.

### CODE REVIEW

**Comment by Shadowlight213** [comment]
Huh, I could have sworn I had fixed this. Guess I forgot.

**Comment by ShadowDeath6** [comment]
would it be better for a radimmune check rather than just the one species? I assume if it can be done with plasmamen it can be done with other ones

**Comment by Shadowlight213** [comment]
Yeah, radimmune would be better

**Comment by RandomMarine** [comment]
DNA injectors use radiation too, right?

I care less about balance memes and more about consistency, so radiation-immune things shouldn't get the benefits of controlled radiation, either.

**Comment by ShizCalev** [comment]
@RandomMarine Indeed it does, good catch. I'll make another PR for that since I have a feeling that might see a little more push-back than this will.

**Comment by Alek2ander** [comment]
What about radsuits?

**Comment by ShizCalev** [comment]
Do radsuits actually protect against the radiation from a dna scanner? lol

**Comment by Shihrt** [comment]
Makes sense.

**Review by ChangelingRain — CHANGES_REQUESTED** [review]
Please make your changelog not imply that this is a bug or something that will be fixed, since it's an intentional change.

**Comment by ShizCalev** [comment]
too much fluff. :(

changed.

**Comment by RandomMarine** [comment]
Fluffy changelogs are often bad ideas. Especially for anything resembling a balance change.

Personal suggestion: Radiation immune species are now incompatible with genetics DNA modification.

**Comment by AnturK** [comment]
Radsuit fix can go in another PR.

**Pull request merged**
