### PR TITLE
Fixing crew monitor suit sensors

### LINKED ISSUE #50792: Duplicate unknowns in crew tracker
Issue reported from  Round ID: [136037](https://scrubby.melonmesa.com/round/136037) (/tg/Station Sybil [ENGLISH] [US-WEST] [100% LAG FREE])

Reporting client version: 513.1521

Crew tracker has multiple identical unknowns with identical vitals and locations. these do not appear to other crew using the same crew tracker i am using
Screenshot 2020-05-01 01 44 26

### PR DESCRIPTION
**Pull request by MacBlaze1**
## About The Pull Request

Fixes the cool amazing bug that makes taking your clothes on and off duplicate an unknown onto the crew monitor program/console/device 
This PR has been unit/practical/requirement tested 
## Why It's Good For The Game

This is like a major bug why hasnt this been fixed yet jesus

## Changelog
:cl:
fix: fixed #50792, also known as the cool amazing bug that makes taking your clothes on and off duplicate an unknown onto the crew monitor program/console/device
/:cl:

### CODE REVIEW

**Comment by willox** [comment]
I think with this change if you're wearing a suit with sensors disabled and also have nanite-sensors which are enabled, you won't be tracked. Is that intentional?

**Comment by MacBlaze1** [comment]
> I think with this change if you're wearing a suit with sensors lowered and also have nanite-sensors which are enabled, you won't be tracked. Is that intentional?

probably not, let me switch them around as nanites should take priority in function over suit sensors

**Comment by MacBlaze1** [comment]
done ^

**Comment by Neo1w** [comment]
update your changelog with something more descriptive, players in game will not know what "fixed 50792" is

**Comment by MacBlaze1** [comment]
> update your changelog with something more descriptive, players in game will not know what "fixed 50792" is

Give me a description of fix and Ill paste it, I dont even want to try to articulate it into words.

**Comment by Neo1w** [comment]
> > update your changelog with something more descriptive, players in game will not know what "fixed 50792" is
> 
> Give me a description of fix and Ill paste it, I dont even want to try to articulate it into words.

> Fixes the cool amazing bug that makes taking your clothes on and off duplicate an unknown onto the crew monitor program/console/device

**Comment by MacBlaze1** [comment]
Added documentation

**Pull request merged**
