### PR TITLE
Makes a thing that should be static, static

### PR DESCRIPTION
**Pull request by Cyberboss**

### CODE REVIEW

**Comment by optimumtact** [comment]
travis disagrees

**Comment by Cyberboss** [comment]
I ADDED THOSE CHECKS AND NOW THEY KEEP FUCKING ME

**Comment by MrStonedOne** [comment]
on that note, I should point out that static vars internally are still global vars and there is zero reason not to use proc or datum static vars when something isn't needed outside that scope.

**Comment by Mervill** [comment]
outside of static scope?

**Comment by Cyberboss** [comment]
Proc scope

**Pull request merged**
