### PR TITLE
Fucking hell people, fix these boxes

### PR DESCRIPTION
**Pull request by yackemflam**
:cl: Yackemflam
tweak: Boxes are worth >26 tc at LEAST
/:cl:

### CODE REVIEW

**Comment by ma44** [comment]
Can't tell if NULL crate nerf or buff

Also yay for no slip shoes

**Comment by yackemflam** [comment]
Null crates dont give boxes

**Comment by ma44** [comment]
https://github.com/tgstation/tgstation/blob/15c5d8cd06848766131c52cd3f8e5d500c35ec37/code/modules/cargo/packs.dm#L150

contains = list(/obj/item/weapon/storage/box/syndicate)

**Comment by anconfuzedrock** [comment]
I HATE BUNDLES

**Comment by Niknakflak** [comment]
Bad

**Comment by Archie700** [comment]
>Null crates dont give boxes

You have never done syndicate cargo.

**Comment by yackemflam** [comment]
Whoops, I havent done cargo in like months

**Pull request merged**
