### PR TITLE
Plasmaman Language

### PR DESCRIPTION
**Pull request by Tacolizard**
:cl: Tacolizard Forever
add: Added a plasmaman language. Access it with 'p'.
/:cl:

If lizards have their own language, why not plasmamen? 

- Given to plasmamen upon job assignment
- Has a very high word-length

### CODE REVIEW

**Comment by Armhulen** [comment]
Extremely similar to the lizard language :thinking: 

also add a reason why it should be added

**Comment by Tacolizard** [comment]
well yeah it is similar because it's basically the same thing except for plasmamen.

**Comment by Armhulen** [comment]
I meant in how they speak, a skeleton =/= a lizard

**Comment by Tacolizard** [comment]
well ingame it will look very different.

**Comment by Tacolizard** [comment]
what why won't it compile

**Comment by BeeSting12** [comment]
[enter slippery slope meme here]

**Comment by PKPenguin321** [comment]
Stop

**Comment by dannno** [comment]
use different syllables than lizard language you broke brain fuck

**Comment by Repukan** [comment]
GOOF WAS RIGHT

SLIPPERY SLOPE IS REAL

**Comment by optimumtact** [comment]
If the other pr regarding lizards is merged then this this *must* be merged as well IMO

**Comment by kevinz000** [comment]
@optimumtact bette rreject both

**Comment by factoryman942** [comment]
when do we get catperson and hulk languages

**Comment by Shapsy** [comment]
What is this, aren't plasmamen just the burned husks of people who got destroyed by plasma?

**Comment by Militaires** [comment]
@Shapsy no they're not.

they're an alien race who live on gas giants.

**Comment by PKPenguin321** [comment]
wrong your lore is incorrect mili

**Comment by KorPhaeron** [comment]
I can't tell if this PR is a shitpost or merely lazy.

It cant share the same language key as lizard speak

**Comment by Iamgoofball** [comment]
# SLIPPERY SLOPE

**Comment by Iamgoofball** [comment]
CONSPIRACY ALREADY FORCING IN LIZARDS

**Comment by Cheridan** [comment]
if the language syllables are anything but various screaming noises you've failed

**Comment by optimumtact** [comment]
@KorPhaeron perhaps it's to illustrate the precedent that giving lizards a language involves? If we merge that one then we must merge this one as it would tick all the same reasons you mentioned in the other pr.

Irregardless of if the pr needs work or not, that doesn't dull it's intent.

**Comment by coiax** [comment]
Except lorewise, plasmamen are humans died ink plasma related accidents.

Also, it needs a language icon before this can be merged. And change the key.

**Comment by Tacolizard** [comment]
i changed the key

**Comment by Militaires** [comment]
but if they died in plasma accidents why must they breath plasma?????????????//
and why do they even have lungs????????????? shouldnt those burn away

obviously alium raec

**Comment by cedarbridge** [comment]
> https://tgstation13.org/wiki/Guide_to_races#Plasmaman
> A recently discovered race that inhabits orbital bodies with high concentrations of Plasma.

hmmmmmm

**Comment by KorPhaeron** [comment]
We're going to test with a single extra crew language first, and if that is not a complete trainwreck, we can add this later

**Comment by Cheridan** [comment]
@cedarbridge 
https://github.com/tgstation/tgstation/pull/26829#issuecomment-298767431

**Comment by optimumtact** [comment]
if lizards go in this must go in

**Comment by kevinz000** [comment]
>kor s aid no *closes pr*

>kor said no *reopens pr*

**Comment by optimumtact** [comment]
I don't agree with Kor on everything and I'm in a mood

**Comment by KorPhaeron** [comment]
day of the juicer soon

**Comment by Iamgoofball** [comment]
I'm adding cattebeest

**Comment by Cheridan** [comment]
catgirl language when

NYAAAAAAAAAAAAA

**Comment by Iamgoofball** [comment]
ill do you one better

**Comment by kevinz000** [comment]
@Iamgoofball do it if this goes through I want cat language reee

**Comment by KorPhaeron** [comment]
No cat language sorry

**Comment by kevinz000** [comment]
:(

**Comment by KorPhaeron** [comment]
This doesn't have an icon yet so its not actually mergable opinions aside

**Comment by Tacolizard** [comment]
@KorPhaeron well my git re-fucked itself so this pr was made off an old version of the code, a version before language icons were added. To add an icon I either commit the cardinal sin of clicking the 'update from tgstation/master' button in github desktop or deleting my repo for the third time and remaking everything I'm working on.

**Comment by Tacolizard** [comment]
i just deleted my repo, starting from scratch. will reopen this when it's done.

**Comment by Iamgoofball** [comment]
>GitHub desktop

**Comment by Tacolizard** [comment]
i know its crap i don't know why i use it

**Pull request closed without merging**
