### PR TITLE
Removes grab from Charge spell

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
Instead, if you're pulling a mob, it will charge them.

### CODE REVIEW

**Comment by PKPenguin321** [comment]
bad bad bad terrible bad omens of bad

**Comment by Zilenan91** [comment]
Wait what? You could use the charge spell on mobs? What would that do?

**Comment by PKPenguin321** [comment]
if you have an apprentice it charges their spells instantly
or if your apprentice grabs you it charges your spells instantly
woefully underused

**Comment by Dorsisdwarf** [comment]
No this is the one instance where Grab is more intuitive.

do both

**Comment by Lumipharon** [comment]
this is dumb. grab actually made sense for this. Charge charges anthing in hand. you grab someone and they're in hand.

**Comment by Zilenan91** [comment]
They're getting rid of grab code because it's shit and there are alternatives to it. Also charge charges things in your backpack too.

**Pull request merged**
