### PR TITLE
Adds dynamic backstories (adds prison suits to maint loot)

### PR DESCRIPTION
**Pull request by Bawhoppen**
[close if this uses a mergetoken]

### CODE REVIEW

**Comment by optimumtact** [comment]
There now you don't need a merge token

**Comment by Bawhoppen** [comment]
who the fuck is Terror4000Rus and why did he downvote me

**Comment by Bawhoppen** [comment]
also what the fuck is with all these shitrenames

**Comment by Cheridan** [comment]
(10:13:23 PM) Cheridan: what's the point of #18492
(10:13:24 PM) TheGhostOfWhibyl1: https://github.com/tgstation/tgstation/pull/18492 - 'Adds dynamic backstories (adds prison suits to maint loot)' by Bawhoppen
(10:13:31 PM) Cheridan: there's already obtainable orange jumpsuits
(10:13:41 PM) Cheridan: in the lockers in the laundry room
(10:13:44 PM) LeoZ: just close it
(10:13:45 PM) oranges: dynamic
(10:13:51 PM) KorMobile: please clap

:clap: :clap:

**Comment by Bawhoppen** [comment]
this isn't an important pr but cheri do you even have any idea of what you're talking about?

**Pull request closed without merging**
