### PR TITLE
Pubby SM Rework

### PR DESCRIPTION
**Pull request by actioninja**
## About The Pull Request

Relayouts the pipes on the pubby sm
image

Tested and ready to ass blast

## Why It's Good For The Game

Makes it better

## Changelog
:cl:
tweak: A more up-to-date version of the supermatter unit has been deployed to pubbystation
/:cl:

### CODE REVIEW

**Comment by Fikou** [comment]
put a spinning toy singulo to say goodbye to our old friend

**Comment by TheSilverNuke** [comment]
You don't really HAVE to fill in the space, just shrink both sides of the SM by two tiles. That should be sufficient.

**Comment by actioninja** [comment]
image

**Comment by TheSilverNuke** [comment]
Dunno what to tell you then, would fix your problem easy.

**Comment by actioninja** [comment]
It's just a lot of work, probably going to end up doing it

**Comment by tralezab** [comment]
put potty the plant in there

**Comment by actioninja** [comment]
Yeah that looks a lot better, top post updated

**Comment by MrFluffster** [comment]
Finally, a nice clean SM setup with no extra layers used. This is good.

**Comment by Dennok** [comment]
All what i can say, this SM can normal work on low temp. Just rormal.
To good work on hight temp it need redesign, or full rework. 
This dont bad, it gives to engi work, but it hard to stabilise if it start to owerheat.
This dont a demand but i think, this SM engine have 2 bad things:

1. The filtering of hot gas.
2. The freezer cooling before space cooling.

Maybe to work better it just need rewert gas flow?

**Comment by TetraK1** [comment]
I'm all for getting rid of layered pipes on stations roundstart (FUCK donut), but what @Dennok is getting at is changing the rotation direction doesn't work that well without moving everything else.  The chamber scrubbers -> space loop -> main filters -> freezers -> chamber vents order is pretty particular and important (although less so freezer location), both in terms of roundstart stability and ease of optimisations.  As the pr is, doing some basic space loop optimisations that take 30 seconds on meta/box would need ripping up and relaying a bunch of pipes, and hot delams on the stock setup would stabilise slower than meta stock setup (no idea how much slower, but probably a very decent chunk slower).

In addition, having the filter to canisters after main filters defeats the purpose/makes it so you have to set the gas you want to filter on both the canister filter and the main filters.  The ideal location for canister filters would be after space loop but before main filters (even though meta and box don't do this, they have it after scrubbers but before space loop).

Having said all that, hardmode/higher effort stock sm setups could be pretty based, FUCK "muh free-hardsuit" engineer players (and FUCK stock pipe layers, again).

**Comment by FloranOtten** [comment]
I think it may be a bad idea to filter before the cooling loop. Even volume filters have limits, and that may become an issue during delams.

**Comment by Cornarias** [comment]
SM loop is going the wrong way. Heads into uncooled piping which filters into freezers which heads to space loop then returns.

Flip it.

**Comment by ErwinSnowden** [comment]
Replacing all SM engines with antimatter, because "change is good" - oranges.

fuck you.

**Comment by Dennok** [comment]
Replace all engines by abductor core.
Because why not.
Infinite power for our deathmatch.

**Comment by actioninja** [comment]
going to fix the complaints listed and then do some testing and this should be ready.

**Comment by actioninja** [comment]
Alright, pubby sm v3 is now done and in the top post.

**Comment by actioninja** [comment]
tested and ready to go

**Pull request merged**
