### PR TITLE
BoxStation Fixes

### LINKED ISSUE #6875: Security lockers spawn in front of each other
Security lockers seem to spawn based on the number of security officers now. If there are enough officers, a second row of lockers starts forming in front of the first row, blocking the back ones off and impeding traffic in the tight locker room.

### LINKED ISSUE #8426: [Box] Scrubber Not Hooked Up
The QM's office has a scrubber that isn't hooked up and no vent on box station.

### LINKED ISSUE #9390: Incinerator room is accessible with default maintenance access.
It should be limited to engineering general or perhaps atmos tech only.

### LINKED ISSUE #9619: Bar disposals don't work properly
Tested on latest revision as of time of posting.
feeb

From what I can tell, the disposal trunk is one tile too far to the right.
space station 13 2015-05-23 172154

### PR DESCRIPTION
**Pull request by CorruptComputer**
Fixes #6875

Fixes #8426 

Fixes #9390 
(not much to screenshot here)

Fixes #9619

### CODE REVIEW

**Comment by duncathan** [comment]
Can you make the incinerator airlock atmos painted?

**Comment by WJohn** [comment]
You dun goofed the top image. You need to shift the little camera spot around the tables to the right one table, and also re-connect the pipe to the HoS's office.

**Comment by CorruptComputer** [comment]
No idea what you mean by camera spot, but I fixed the pipe;

**Comment by WJohn** [comment]
I mean the two computers to the bottom there with the chair and filing cabinet. You should move that one tile so there's a bit of room. It's weird to have to go through a chair to move around.

**Comment by SconesC** [comment]
While you're fixing things on Box, can you take care of the heater+freezer stacked on top of one another in maint outside the Experimentor room?

Shit has bothered me for ages.

**Comment by duncathan** [comment]
If you changed the access for the incinerator, change the airlock paint to match.

**Comment by WJohn** [comment]
Have you moved that pair of security camera consoles in the sec office to the right one tile? It's just a visual thing but it'd look a lot better.

**Comment by duncathan** [comment]
Commits would seem to indicate he did.

**Comment by CorruptComputer** [comment]
Yeah I did.

**Pull request merged**
