### PR TITLE
Buffs security formal wear by allowing them to carry things a vest can.

### PR DESCRIPTION
**Pull request by silicons**
allowed=list(/obj/item/gun/energy,
/obj/item/reagent_containers/spray/pepper,
/obj/item/gun/ballistic,
/obj/item/ammo_box,
/obj/item/ammo_casing,
/obj/item/melee/baton,
/obj/item/restraints/handcuffs,
/obj/item/device/flashlight/seclite,
/obj/item/melee/classic_baton/telescopic,
/obj/item/kitchen/knife/combat,
/obj/item/tank/internals/emergency_oxygen)

### CODE REVIEW

**Comment by pantherpusher** [comment]
Mayhaps the next step could be adding the formal crates to every station

**Comment by Anonmare** [comment]
Look out guys the next steelpoint is buffing sec again

**Comment by PKPenguin321** [comment]
Woah, is that the Head of Security main Kevinz000 buffing security again?

**Comment by kevinz000** [comment]
:3c

**Comment by Arianya** [comment]
Wait formal wear is un-armoured!?

**Comment by Hatterhat** [comment]
>wearing formal wear
faggot

**Comment by Arianya** [comment]
>fisting kev
>extra fag

**Comment by optimumtact** [comment]
fuck off kev, I'm closing this at 24 hours for being power creep.

Stop removing trade-offs from teh game or I'll have @KorPhaeron git ban you.

**Comment by optimumtact** [comment]
```
fuck off kev, I'm closing this at 24 hours for being power creep. Stop removing trade-offs from teh game or I'll have @KorPhaeron git ban you.
```

**Comment by optimumtact** [comment]
>fuck off kev, I'm closing this at 24 hours for being power creep. 
>Stop removing trade-offs from teh game or I'll have @KorPhaeron git ban you.

**Comment by Hatterhat** [comment]
image

**Comment by SgtxRootbeer** [comment]
@optimumtact are you well?

**Comment by Bawhoppen** [comment]
Literal powercreep trash

**Comment by ShizCalev** [comment]
Vests can carry 	
/obj/item/gun/energy, 
/obj/item/reagent_containers/spray/pepper, 
/obj/item/gun/ballistic, 
/obj/item/ammo_box, 
/obj/item/ammo_casing, 
/obj/item/melee/baton, 
/obj/item/restraints/handcuffs, 
/obj/item/device/flashlight/seclite, (this is inconsistent between items. will fix this in another PR myself.)
/obj/item/melee/classic_baton/telescopic, 
/obj/item/kitchen/knife/combat, 
/obj/item/tank/internals/emergency_oxygen

Your list;
/obj/item/tank/internals/emergency_oxygen, 
/obj/item/reagent_containers/spray/pepper, 
/obj/item/device/flashlight, 
/obj/item/gun, -> this is bad since it'll allow them to carry ANY gun
/obj/item/melee/baton, 
/obj/item/restraints/handcuffs

**Comment by kevinz000** [comment]
switching

**Comment by DoctoreMad** [comment]
@optimumtact Can you just merge this already

**Comment by Bawhoppen** [comment]
Don't believe oranges cares for security creep like this

**Pull request closed without merging**
