### PR TITLE
Clown and Mime items can equip to belt and back

### PR DESCRIPTION
**Pull request by RaveRadbury**
## About The Pull Request

Here goes my first PR

A lot of equipment can be placed on the back and belt slot. Much of this equipment is job specific. Sadly, the Clown and Mime have been left out of the fun.

## Why It's Good For The Game

Why should all the other jobs have the fun of belt and back slots? Sometimes you want to mosey around the station like a honkin' cowboy, your bikehorn clipped securely to your belt. Now you can. Your trusty honkshooter is ready to go. DRAW!

Or maybe you're a Mime who wants his crusty baguette saber at his side. EN GARDE!

## Changelog
:cl:
tweak: Bike horns and baguettes can now be equipped to belt and back slots!
/:cl:

### CODE REVIEW

**Comment by mattroks101** [comment]
Belt slot I guess, but I don't think it really makes a lot of sense to equip a bikehorn to your back.

**Comment by RaveRadbury** [comment]
Guns equip to the back slot. Sometimes you need a honk on your belt and a honk on your back for TACTICAL SWITCHING MID-HONKBAT.

**Comment by ExcessiveUseOfCobblestone** [comment]
no sprite for the backguette smh reported

**Comment by Tlaltecuhtli** [comment]
its just that you shouldnt be able see the equipped baguette in your back

**Comment by RaveRadbury** [comment]
I wasn't sure if there would need to be additional spriting for this to work. I can definitely try reaching out on the spriter discord to see if I can make it happen. Might need some help on working that out as it's much more than just adding a line to a file.

**Comment by Farquaar** [comment]
> 
> 
> I wasn't sure if there would need to be additional spriting for this to work. I can definitely try reaching out on the spriter discord to see if I can make it happen. Might need some help on working that out as it's much more than just adding a line to a file.

If nobody takes you up on that request, I might be able to sprite up a back-baguette in a week or so once I finish my current wave of uni assignments.

**Review by SpaceManiac — APPROVED** [review]

**Pull request merged**
