### PR TITLE
Prototype Hardsuit

### PR DESCRIPTION
**Pull request by GunHog**
Adds the prototype hardsuit, intended for the Research Director.
- Primarily a bomb suit
- Emergency firesuit protection
- Slightly higher radiation protection than a normal hardsuit

This suit has no combat advantage over a standard hardsuit, and provides utility for the dangerous work and accidents faced by the RD in a typical round. <b>This PR does not add it to the map, only the code.</b>

Note: _This suit, if added to a map, is intended to replace one of the map's existing EVA suits._

<b>Sprites by @WJohn!</b>
screenshot 2015-10-01 01 38 11

### CODE REVIEW

**Comment by WJohn** [comment]
This is what the hardsuits look like up close.

**Comment by SconesC** [comment]
Really goddamn nice looking sprite, wow

**Comment by AlexCrimson** [comment]
Remove the fire protection and just give it full radiation protection. That would make more sense, no?

**Comment by Thunder12345** [comment]
Fire protection makes more sense to me than radiation, since the only major sources of radiation I know of are the singulo and the event, and it's far less likely the RD'll find a singulo than find toxins on fire.

**Comment by Miauw62** [comment]
the sprites look really fucking nice but aaaaaaa powercreep AAAAAAAAAA

**Comment by Cheridan** [comment]
Yeah, the CE's suit is just a hardsuit + firesuit. This is Hardsuit + Bombsuit + Firesuit + Some extra rads on the side. It's too good.

**Comment by GunHog** [comment]
It is not a <b>FULL</b> firesuit. CE hardsuit is Hardsuit + Atmos suit + full radsuit + Jetpack. Pure environmental immunity. 

RD suit is bomb suit (which is not as awesome as it sounds) + *emergency* firesuit + higher radsuit than normal.

Based on my experience as RD:
- Bomb suit because Toxins
- *Emergency* firesuit because Toxins FIRES. (It is the same as the ones in the lab entrance, you will still burn if you take too long to escape)
- +10 to rad armor because of working with the AE gun and Experimentor on the Irradiate setting.

It would be more of a "ghetto" CE suit for bombs.

**Comment by WJohn** [comment]
Also I would like to point out how bad the armor values are for this suit. The highest for combat related stuff is like 10. CE's hardsuit on the other hand has like 30 or 40 melee protection, alongside other really good armor stats.

**Comment by AlexCrimson** [comment]
The Experimentor produces radiation, no? Like i said, remove the fire protection, because the RD has no business running into toxins when its on fire. It makes more sense to have full protection from something rather than partial damage reduction.

**Comment by Fox-McCloud** [comment]
IMO, this should have full fire immunity, like the CE's hardsuit; the stats on this hardsuit aren't that great to begin with---and bomb armor is generally fairly niche (and not that useful considering its chance based and only has flat damage reduction)...keep in mind this is competing against the teleport armor.

@Cheridan 

Even if this is given fire immunity, it's still nothing compared to the CE's hardsuit. The CE's hardsuit is one of the few suits that didn't get its armor values nerfed a long time ago--it still has insanely high combat effectiveness in addition to having higher than normal radiation protection and fire immunity.

**Comment by hornygranny** [comment]
*dusts off old meme shelf*
power creep

**Comment by pudl** [comment]
It looks like a scarab.

**Comment by SconesC** [comment]
It shouldn't have fire immunity, just temp reductions

Inferno-walking is limited to the CE and Atmos suit and it's best that way

Radiation protection is much more reasonable

**Comment by Dorsisdwarf** [comment]
Honestly this should just be a hardsuit bombsuit/radsuit combo. Maybe with less slowdown.

**Comment by Alek2ander** [comment]
Looks like something ayyliens would wear. :+1: RD stealing xenotech

**Comment by daman997** [comment]
hop gets an ian hardsuit when

**Comment by xxalpha** [comment]
:+1:

Looks great.

**Comment by PKPenguin321** [comment]
pretty cool but i hope it never gets onto the map to be honest
RD really doesnt need a hardsuit

**Comment by Fox-McCloud** [comment]
If fire immunity isn't "acceptable", then it should probably have the same armor stats as the bomb suit

**Comment by GunHog** [comment]
Bomb suit is *armor = list(melee = 20, bullet = 0, laser = 20,energy = 10, bomb = 100, bio = 0, rad = 0)*
Pretty meh, hardly a combat difference at all. The only modification I wish to make to the suit at this time is to add the RPED as a possible suit slot item.

**Comment by Fox-McCloud** [comment]
I suppose it would mean 10 more melee and laser and 5 more energy *shrug*

**Comment by Steelpoint** [comment]
I think it should keep the Fire, Rad and Bomb protection.

Bomb protection only really counts for if your body is gibbed by a bomb or not. The main killer in explosions is the heat and space exposure.

I think the suit is great for the RD, and it looks really cool either way.

**Comment by Fox-McCloud** [comment]
If you wanted to go super snowflake, it could be upgradeable with stock parts to gain better armor in different areas.

**Comment by Steelpoint** [comment]
That's kinda what Goon does to a small extent.

Best example is the Captain's Laser, it starts the round broken yet can be repaired by Maintenance and RnD. The better the parts used on the gun the more powerful it can be.

**Comment by GunHog** [comment]
While I am not against such an idea, and the fact that I named it 'prototype' supports such a thing, but this sounds like a real pain to code, in which I would rather get this suit in first before touching fancy tech that might be a nightmare to maintain properly.

**Comment by tuypo1** [comment]
I don't have anything to say about the balance of it but holy shit that spirit is amazing

**Comment by Steelpoint** [comment]
WJohn should spend more time respriting everything else except Aliens.

**Comment by WJohn** [comment]
Never!

**Comment by duncathan** [comment]
You can't ask a man to leave the one he loves so that you can get the child of him and another

**Comment by WJohn** [comment]
And just because you mentioned it steelpoint I went ahead and literally resprited aliens!


So there!

**Comment by Dorsisdwarf** [comment]
@WJohn 
I heard you made that phoenix-wright pose xeno I asked for, but haven't been able to find it

**Comment by SconesC** [comment]
Nice

**Comment by GunHog** [comment]
WJ is a Xeno spriting machine! I think it best to fix the hugger problem in https://github.com/tgstation/-tg-station/pull/12077 and have that merged rather than trying to combine the two.

**Comment by Steelpoint** [comment]
Being serious I absolutely love the Hardsuit sprite, and worst case if this PR is rejected I would still love to see it used in some capacity.

Hell, it might even make a great replacement sprite for Bombsuits if we remove the more mechanical parts of it.

Great work, now to recolour it for all other NT space suits (I kid, maybe).

**Comment by GunHog** [comment]
You do not have to kid. WJ made a sexy Syndicate version of it (Without the visor change though):

fkbmiud

**Comment by Steelpoint** [comment]
Beat me to the punch.

Well impressive.

You know, some people really wanted to move away from the more Dead Space RIG design (Paprika spearheading the RIG to Hardsuit movement).

Just saying but these sprites might make a interesting replacement for NT Hardsuits.

**Comment by Alek2ander** [comment]
Syndie suit looks like a walrus. :+1:

Can you make an ayylien themed version?

**Comment by Steelpoint** [comment]
If we did expand these sprites to other Hardsuits I think it should be reserved for Nanotrasen Hardsuits, so Med, Sec, Eng and Atmo.

Syndicate would still retain their iconic Hardsuits, and Space Suits would remain as is (to better differentiate between just a suit and a hardsuit).

**Comment by GunHog** [comment]
I prefer to keep the Dead Space theme for most hardsuits. It is an amazing game with great themes. There is no need to change something just because of wanting to remove a reference. It should be because you have cooler looking sprites. My first image of the RD hardsuit was the Archaeologist Suit from DS 3 and the white battle suit from 1. WJ made a sprite that was soooo good that I was blown away! All it needed from his first proposition was a color tweak and the visor shape!

**Comment by Anonus** [comment]
The nifty syndicate version should have green lights and black instead of purple and then it'd be really cool but the red lights on red doesn't look that good

**Comment by WJohn** [comment]
Yeah it was originally supposed to be in roboticist colors, not nuke op. I could however make a nuke op version pretty easily.

**Comment by GunHog** [comment]
Should I modify the allowed suit storage items? If so, what item types should be allowed? (Besides the obvious internals tank)

**Comment by Fox-McCloud** [comment]
@GunHog 

Wormhole projector, for sure.

**Comment by GunHog** [comment]
Any other items? Such as RPED?

**Comment by Fox-McCloud** [comment]
That's a super big item, dunno if it should fit on this hardsuit or not....probably the hand teleporter, too..hhmmm...maybe an intellicard/pAI?

**Comment by GunHog** [comment]
Alrighty, I added hand tele, AI card, and portal gun, along with the standard tank and flashlight.

**Comment by freerealestate** [comment]
that sprite is almost too nice for nt

looks like something an alien race would wear

**Comment by AnonymousNow** [comment]
A good balance of defences appropriate to science, in my opinion. Nice one.

**Pull request merged**
