### PR TITLE
Fixes spilled radium decal containing uranium instead of radium

### LINKED ISSUE #10998: Pouring radium on the floor yields scoopable uranium
I guess this was the remnants of some old chempiles thing that didn't get followed through with, but if you take radium and splash it on the ground and scoop up the green goop on the floor with a beaker (like how you would get ash), you get back liquid uranium. Since this lets you get roundstart nukacola and EMP's without grinding uranium ore, I think this would count as unintentional and bad

Edit: Oh and it can be made for mute toxin too

### PR DESCRIPTION
**Pull request by ghost**
Fixes #10998

I haven't touched or looked at BYOND code for years so someone confirm this doesn't break the server please

### CODE REVIEW

**Comment by Dorsisdwarf** [comment]
But doesn't liquid uranium also create the greenglow decal when spilled?

**Comment by advomach** [comment]
Yes but each has their own proc/function/whatever-it's-called

```
/datum/reagent/radium/reaction_turf(turf/T, volume)
    src = null
    if(volume >= 3)
        if(!istype(T, /turf/space))
            var/obj/effect/decal/cleanable/reagentdecal = new/obj/effect/decal/cleanable/greenglow(T)
            reagentdecal.reagents.add_reagent("radium", volume)
```

and 

```
/datum/reagent/uranium/reaction_turf(turf/T, volume)
src = null
if(volume >= 3)
    if(!istype(T, /turf/space))
        var/obj/effect/decal/cleanable/reagentdecal = new/obj/effect/decal/cleanable/greenglow(T)
        reagentdecal.reagents.add_reagent("uranium", volume)```

Before they both added uranium into the reagentdecal

**Comment by Shadowlight213** [comment]
Please make more descriptive pr titles in the future, so people can actually see what you are fixing at a glance.

**Comment by advomach** [comment]
Taking PR title recommendations for this PR, my alternative was "Spill radium scoop green glow get uranium bad, now spill radium scoop green glow get radium"

**Comment by advomach** [comment]
"Fixes radium reagent floor scooping"

**Comment by Delimusca** [comment]
i suspect the minimum volume is to stop 99%water:radium solutions from leaving splats everywhere in smoke/spray.

**Comment by advomach** [comment]
That makes sense. But 3 still seems like a strange case to set the minimum at.

**Comment by Shadowlight213** [comment]
4th pr title suggestion sounds best.

**Pull request merged**
