### PR TITLE
New laser and disabler sounds!

### PR DESCRIPTION
**Pull request by DrDiasyl**
## About The Pull Request
Changes old laser sounds (and sear sound) to new ones, made by me in FL Studio.

(The sound getting too distorted when pitching up will be soon fixed, as Goof will make pitching down of gun sounds better)

https://user-images.githubusercontent.com/42353186/233795506-d68825d9-63a5-4cff-a52d-9fc949f2ec13.mp4

https://user-images.githubusercontent.com/42353186/233795520-525bada0-265c-4003-bb76-0b256ee844fb.mp4

https://user-images.githubusercontent.com/42353186/233795548-e97528ab-c9d6-4389-bee1-f849ceb71c60.mp4

## Why It's Good For The Game
For a long time, people have always been liking ballistics more than laser for many reasons.
But I often heard that the ballistics sound gives feedback of a punch and that laser guns (especially disablers) sound like toys.

And to make the laser more satisfying and intimidating to use, I have created new sounds for them which are more in-depth. And also changed the sear sound (when you get hit by a laser) to give more of a punch.
## Changelog
:cl:
sound: Disablers and lasers have a new deeper sound to them
sound: Sound of lasers hitting a person now are giving more of a punch
/:cl:

### CODE REVIEW

**Comment by Jacquerel** [comment]
I do like these but the pitch when it gets really low on ammo is 😬 
That would be a code adjustment rather than asset replacement though I imagine

**Comment by DrDiasyl** [comment]
> I do like these but the pitch when it gets really low on ammo is 😬 That would be a code adjustment rather than asset replacement though I imagine

Is there a lot of code to adjust for that? If yes, I rather just tweak the audio to be less eerie when pitched down

**Comment by DrDiasyl** [comment]
I did kinda heard it in the laser gunshot, but disabler really remained the same when getting pitched down.

**Comment by DrDiasyl** [comment]
So Goofball says there is a way to make pitch go down without stretching audio, and that he wants the gun pitch to go down this way.
So I think this pitch problem is now kind of negotiated already.

**Comment by Jacquerel** [comment]
> So Goofball says there is a way to make pitch go down without stretching audio, and that he wants the gun pitch to go down this way. So I think this pitch problem is now kind of negotiated already.

Yeah as we may be fixing the backend for this to work better, that concern can be sort of put off for now.

**Comment by Cheshify** [comment]
Love these new sounds, they're a huge upgrade from the piddly little squirts of laser gun fire we currently have.

**Comment by msgerbs** [comment]
Maybe my sub is just not set up right but the bassy sound at the start of the laser blast effect seems a bit *too* big of a thump to the point it's distracting.

**Comment by DrDiasyl** [comment]
> Maybe my sub is just not set up right but the bassy sound at the start of the laser blast effect seems a bit *too* big of a thump to the point it's distracting.

Yeah it is pretty loud, but low frequencies are not easily noticeable. But I don't see anyone else complaining yet.

**Comment by carlarctg** [comment]
This is sick, I love it. If I may, some sort of hit sound like 'sear' for the disabler would do wonders for making it feel impactful.

**Comment by moocowswag** [comment]
They sound larger and more powerful than they are.

Definitely serves to give the shooter more dopamine.

**Comment by DrDiasyl** [comment]
> They sound larger and more powerful than they are.
> 
> Definitely serves to give the shooter more dopamine.

That's the point, although there is even smaller guns that sound even bigger. Like thermal pistol's.

**Comment by DrDiasyl** [comment]
> This is sick, I love it. If I may, some sort of hit sound like 'sear' for the disabler would do wonders for making it feel impactful. 

Currently disabler uses a sound for a soft impact, that sound when you get hit by a medkit or folder.
Maybe I can give it a custom sound actually...

**Comment by Pumpkinoe** [comment]
Actually pretty cool! Love that it keeps the spirit of them while giving them a nice _punch_.

**Comment by DrDiasyl** [comment]
Alright, I think I will now do 2 things:

- [ ] Make thump at the beginning of laser shot quite
- [ ] Give disablers their own sear sound

**Comment by DrDiasyl** [comment]
@msgerbs I have made thud quieter on the laser gunshot
@carlarctg I have made a sear sound for the disabler

I have already updated the videos, so listen to them again

**Comment by msgerbs** [comment]
Still a bit thumpy imo but I can live with it since everybody else seems to like it. Thanks!

**Comment by Mothblocks** [comment]
you dont need to bother with the pitch. it will always sound bad as long as it pitches down instead of up.

**Pull request merged**
