### PR TITLE
Penguins are immune to cold

### PR DESCRIPTION
**Pull request by ghost**
Yeah this was pretty embarassing

### CODE REVIEW

**Comment by PKPenguin321** [comment]
thanks

**Comment by MoreRobustThanYou** [comment]
SQWAK SQWAK

**Comment by LetterN** [comment]
But what if we hit -1k?

**Review by Cyberboss — APPROVED** [review]

**Comment by Cyberboss** [comment]
#34343

**Comment by Armhulen** [comment]
@Cyberboss who is this QT who made that pr ;)

**Pull request merged**
