### PR TITLE
Fixed the name of the burger that turns you into a cyborg.

### PR DESCRIPTION
**Pull request by KathyRyals**
## About The Pull Request

The roburger is now named borger, as it always should have been.

## Why It's Good For The Game

Borger is a way better name.

## Changelog
:cl:
fix: Nanotrasen has rebranded their horrifying mechanical burger filled with nanites that turns you into a glorified metal slave ! Roburgers are now named borgers.
/:cl:

### CODE REVIEW

**Comment by Timberpoes** [comment]
Can't even be mad.

**Review by Timberpoes — APPROVED** [review]
Haters gonna hate. Made me laugh then facepalm, in that order.

**Comment by KathyRyals** [comment]
Needs the GBP: No Update label by the way.

**Comment by KathyRyals** [comment]
I'll make a sprite for the big borger and rePR this.

**Pull request closed without merging**
