### PR TITLE
[WIP][Port] RBMK reactor

### PR DESCRIPTION
**Pull request by Ghilker**
## About The Pull Request
original PR: [NSV13](https://github.com/BeeStation/NSV13/pull/828)

WIP, will update the description and all the good stuff later on
The baseline experience is implemented, i'll add more features while i work on it
This is supposed to replace the SM

## Why It's Good For The Game
Ditto

## Changelog
:cl:
add: RBMK reactor
/:cl:

### CODE REVIEW

**Comment by Cyprex** [comment]
Looks cool, is there any documentation for this? I wasn't able to find anything on the beestation wiki and the linked original PR doesn't seem to have any either

**Comment by Ghilker** [comment]
there isn't yet, i'll make the docs while i work on it, also some kind of basic guide

**Comment by spessbro** [comment]
would this mean the end of the sm shard as well?

**Comment by Gandalf2k15** [comment]
3.6

**Comment by Qustinnus** [comment]
this code is very KMC, most of it should probably be re-written. Things such as the update_icon() proc are very outdated and do things in ways we dont do them anymore for example.

**Comment by Jared-Fogle** [comment]
>  This is supposed to replace the SM

This goes against the engineering design doc and should be discussed with the writer (oranges) -- https://hackmd.io/@tgstation/HJfQsj4jI.

**Comment by Ghilker** [comment]
closing this untill furter notice

**Pull request closed without merging**
