### PR TITLE
Status panel cleanup

### PR DESCRIPTION
**Pull request by kingofkosmos**
Removed the intent and move mode info since they're already displayed to the player on the game screen at all times.

Removed internals stuff. A new system of alarming the user about low pressure in internals is coming up and it's just kinda weird that you just know the accurate pressure at all times without looking.

Current:
sieppaa

New (UPDATED):
sieppaa

### CODE REVIEW

**Comment by Dorsisdwarf** [comment]
:-1: 
The internals information now looks ugly as sin.

**Comment by phil235** [comment]
It's good but I'd prefer if "emergency oxygen tank" and the pressure numbers were kept in the same column (like in the Current), it's easier to get the info at a glance.

**Comment by duncathan** [comment]
:-1: why?

**Comment by kingofkosmos** [comment]
The jumping server time, intent and move mode bugged me and imo it looks very sloppy. It should stay in one place.

**Comment by Fayrik** [comment]
If you're going to round the pressure numbers, please do it to two decimal places, in line with ~~all~~ most of the other atmospheric rounding.

**Comment by Aranclanos** [comment]
that information shouldn't be on the status panel on the first place

**Comment by kingofkosmos** [comment]
>If you're going to round the pressure numbers, please do it to two decimal places, in line with all most of the other atmospheric rounding.
I can't find any roundings done to two decimals, plus it feels unnecessarily accurate.

>that information shouldn't be on the status panel on the first place
Assuming you mean the intent & move mode info, I realized all of that info is already shown on the screen at all times. Removed and updated to all other status-panels as well.

New:
sieppaa1

**Comment by Fayrik** [comment]
>I couldn't find any other roundings done to two decimals - plus it feels unnecessarily accurate.
Air alarms, air pumps, air canisters... (And air tanks *should*) all round to two decimal places if they round at all.
Consistency is key.

**Comment by kingofkosmos** [comment]
Oh yeah I see, I'll change them to round to 0.01.

**Comment by Aranclanos** [comment]
no, I don't think that tank pressure should be on the status panel either

**Comment by Fayrik** [comment]
Where do you think it should be then, @Aranclanos ? The status panel is actually useful for checking how much air you have.

**Comment by Anonus** [comment]
what no :-1:

**Comment by Aranclanos** [comment]
on the UI

**Comment by Fayrik** [comment]
Then how about we put it on the UI before removing it?

**Comment by Aranclanos** [comment]
that would be rational thinking, are you crazy?

**Comment by kingofkosmos** [comment]
Ok it's kinda silly to have this as its own pr.. maybe if the internals button gets changed to flash to indicate low oxygen something like this can be done.

**Pull request closed without merging**
