### PR TITLE
Shuttle fix

### PR DESCRIPTION
**Pull request by Aranclanos**
Fixes shuttles taking turfs that aren't part of the shuttle itself.
Fixes shuttles breaking apart if the turfs aren't strictly shuttle turfs (who are also gone in a previous commit, now under wall and floors paths)
Reduces reddit's angry levels by 5
Fixes issue #9722
Fixes issue #6856
Fixes issue #9788

### CODE REVIEW

**Comment by MrStonedOne** [comment]
Hmm...

The whole point of carn shuttles was to get away from area based shuttles, and allow for more dynamic shuttle control in game. 

Admins currently make shuttles on the fly with their own docking points and everything. It wasn't even until 2 weeks ago that some of the default shuttles had their own areas, and i think some still don't.

**Comment by Aranclanos** [comment]
no they don't

**Comment by MrStonedOne** [comment]
I'm not gonna argue this point with you, they do.

**Comment by Jordie0608** [comment]
Yes we do aran; ask Sticky and NikNak

**Comment by Aranclanos** [comment]
where's the button for it?

**Comment by MrStonedOne** [comment]
There is no button because you don't need one, You just spawn the docking ports, edit their bounding box vars, at that point you can make a computer to move it between the docking points.

One little bit of autism build mode later and you have a shuttle.

**Comment by Boggart** [comment]
There's no specific button, it's done by var-editng (and sometimes spawning) the docking ports, shuttle consoles and the shuttle control object.

**Comment by Aranclanos** [comment]
well there you go its not supported

**Comment by Stickymayhem** [comment]
Aran we do this all the time and it's been one of the single best helps to doing events in a very long time.

Without it we can't use shuttles to move people around or make our own.

Don't break something then tear what was there to start with to shreds to "fix" it.

**Comment by Aranclanos** [comment]
just keep doing it I don't give a shit

**Comment by MrStonedOne** [comment]
alright, ya, on second thought, this does seem like it will work with admin shuttles.

**Comment by Aranclanos** [comment]
https://github.com/tgstation/-tg-station/pull/9844 is kinda tied to this PR to keep the security pod from not breaking in half

**Pull request merged**
