### PR TITLE
Stimpack syringe changed into medipen

### PR DESCRIPTION
**Pull request by carlarctg**
## About The Pull Request

title. Also improved some syringe.dmi sprites a tad, namely tuberculosis cure got the color lightened up a bit and the holy injector is more stabby

## Why It's Good For The Game

stimpack feels like it should be a medipen rather than a syringe. it's one-use, injects a lot of units instantly, and is a healing item. this also makes it easier for nukeops to inject it without taking off their hardsuit so that's neat

image

## Changelog
:cl:
tweak: traitor stimulants syringe is now traitor stimulants medipen, no changes otherwise
/:cl:

### CODE REVIEW

**Comment by ATH1909** [comment]
"this also makes it easier for nukeops to inject it without taking off their hardsuit so that's neat"

Wait, you can apply medipens through hardsuits?

**Comment by carlarctg** [comment]
> "this also makes it easier for nukeops to inject it without taking off their hardsuit so that's neat"
> 
> Wait, you can apply medipens through hardsuits?

image

**Comment by necromanceranne** [comment]
I'm of two minds actually. I'm happy the stimpack can be used through hardsuits that's a big plus.

I'm sad since the stimpack isn't actually one use. It's actually a fully functional 50 unit injector you can refill and then plunge 50 units of any drugs you want. Even load it into a syringe gun.

**Comment by carlarctg** [comment]
> I'm of two minds actually. I'm happy the stimpack can be used through hardsuits that's a big plus.
> 
> I'm sad since the stimpack isn't actually one use. It's actually a fully functional 50 unit injector you can refill and then plunge 50 units of any drugs you want. Even load it into a syringe gun.

oh i'll just give the infiltrator a few lethal injections then, how about that

you dont need map merger for code-based changes to maps right

**Comment by necromanceranne** [comment]
I was thinking more for traitor use actually, I don't believe nukies get nearly enough access to chemical synthesis for it be even functional for them short of like...I think they have a grinder somewhere on the base so I THINK they can grind up syndicakes for doctor's delight?

**Comment by carlarctg** [comment]
meh
just add some to the syndie uplink, perhaps the poison kit

**Comment by Akrilla** [comment]
Could you do the same with mulligan? I'm sure there's probably others as well that would work better as a medipen.

**Comment by ExcessiveUseOfCobblestone** [comment]
a 50u sleepy pen sounds very bad

**Review by ExcessiveUseOfCobblestone — APPROVED** [review]

**Pull request merged**
