### PR TITLE
Generalizes vomit into a single carbon proc

### PR DESCRIPTION
**Pull request by ghost**
Vomiting contains a lot of copypasta - this just remedies that.

### CODE REVIEW

**Comment by WJohn** [comment]
Any mechanics changes?

**Comment by Xhuis** [comment]
@WJohn, it now has a static 4-second stun instead of the varying amounts of time in the different occurrences of the effect. It also doesn't work if your nutrition is below 100, at which case it weakens you for ten seconds Other than that, no change.

**Comment by bgobandit** [comment]
>Vomiting contains a lot of copypasta 

have you tried altering your diet

**Comment by Xhuis** [comment]
Conflicts removed, you can merge this now.

**Pull request merged**
