### PR TITLE
Nerfs healing coma 25%

### PR DESCRIPTION
**Pull request by Supermichael777**
:cl:
balance: Healing coma base heal rate is now 3 DPS instead of 4DPS.
/:cl:

Its broken, effectively making you immortal in space in the upgraded fourm. You stay in a perpetual coma.
Also annoying because the fake-death prevents Regen stasis for lings, you need to succumb and regen and that might become impossible.

Balance wise a max of 6 damage regenerated per second was broken. You couldn't beat someone to death with low force weapons, they out healed it.

### CODE REVIEW

**Review by XDTM — APPROVED** [review]

**Comment by davethwave** [comment]
Hasn't Virology been nerfed enough yet?!?

**Comment by Repukan** [comment]
Viro as a concept just doesn't fit well into the game

**Comment by Supermichael777** [comment]
This is actually broken and fucks with lings. edge case you can get trapped in perpetual near death.

**Comment by Shadowflame909** [comment]
Isn't this only if it's at max speed? IMO, seeing a feature get made, and then get nerfed into uselessness and then replaced because it sucked, only for the same thing to happen. It might just be better to start stealing medikits from medbay then to waste time on viro.

**Comment by Tlaltecuhtli** [comment]
lings can purge the virus with one of their powers lol

**Comment by ExcessiveUseOfCobblestone** [comment]
Why this vs #38855

**Comment by Ratvar** [comment]
Lit on fire/welderbomb/space/toxin liver/toolbox/spear/weld in locker/layer of walls/cuff/strangle... so many ways to deal with. Or you can fuck mining+botany/virology before they make shitty virus. And lings can get permastunned from other viruses as well, and can purge them out as well-nerf them all?

**Comment by PKPenguin321** [comment]
Just fix the ling interaction?

**Comment by Supermichael777** [comment]
Got a better fix for lings

**Pull request closed without merging**
