### PR TITLE
Revert "[NO GBP] Beef stroganoff sprite left behind"

### PR DESCRIPTION
**Pull request by optimumtact**
Reverts tgstation/tgstation#67279

twaticus said the old sprite was better anyway

### CODE REVIEW

**Comment by Zergspower** [comment]
I mean.. no?

**Comment by Zergspower** [comment]
image
how is that better than 
image

**Comment by MidoriWroth** [comment]
yeah like... i really don't get how the old one looks better in any way, considering this is what beef stroganoff actually looks like and what i referenced for the sprite 
image

**Comment by AtoriBirb** [comment]
Yeah the new look is better. Not sure why the hell you'd just plop it on a table.

**Comment by optimumtact** [comment]
Cool but you are not the sprite lead

**Comment by Zergspower** [comment]
image
idk have they looked at this

**Comment by Twaticus** [comment]
> image
> 
> idk have they looked at this

WHAT LOL
ok it was supposed to be an overlay using a bowl base so nevermind then we can leave the new one
sorry oranges :)

**Comment by Zergspower** [comment]
> > image
> > idk have they looked at this
> 
> WHAT LOL ok it was supposed to be an overlay using a bowl base so nevermind then we can leave the new one sorry oranges :)

lmao no worries - I was concerned haha

**Pull request closed without merging**
