### PR TITLE
Revert "ELEVATOR MUSIC: True Elevator Experience"

### PR DESCRIPTION
**Pull request by Cheshify**
Reverts tgstation/tgstation#75388
## About The Pull Request
Reverts tgstation/tgstation#75388
## Why It's Good For The Game
I mean no disrespect to the original creator of the elevator music. While I think elevator ambiance is a neat idea, this is not the way to do it. 
A few issues:
- The elevator music is agonizing when you're ghosted on a map with a lot of elevators. It goes through walls, and due to how soundloops work you'll have a 5.83 second sound clip just playing in either your left or right ear and it's really annoying.
- The song is just not good enough and the clips don't merge seamlessly enough for me to enjoy listening to it. It's royalty free music, it's fine, it's not something I want chopped up and blasting entirely in one ear as I try to handle tickets or watch people be funny spessmen. It just doesn't sound good.
- You can't disable it, just like tcomms, it's not a part of audio prefs. 
- It plays from way too far away, I heard it decently at around 8 tiles away, this leads into frustration as a ghost and a separate issue while playing.
- There are a few map specific issues listed below.

 On the North Star, none of the elevators have north or south facing control panels, so the audio is always left or right ear, as shown below.
<details>
<summary> NS </summary>

c
a
b

</details>

Tram specifically has a few problem areas where the song will be playing even when the elevator tunes shouldn't be there.
In sec, if the elevator is called up you'd be hearing it in secmed.
In medical, if the elevator is up, the jingle could possibly even be heard from the lobby.

<details>
<summary> Tram </summary>

e
image

</details>

## Changelog

### CODE REVIEW

**Comment by DrDiasyl** [comment]
Also in issues about tile range, we can just decrease it

**Comment by DrDiasyl** [comment]
And about medical and Security elevators in tram, panels have a variable that you can disable and it won't have music

**Comment by BlueMemesauce** [comment]
Just make it so it is only played when the elevator is moving like i said in the original pr

**Comment by Farquaar** [comment]
Couldn't you also make it that ghosts can't hear it?

**Comment by tralezab** [comment]
It seems very fixable but elevator music seems more fitting as an upgrade applied to the elevator. Overall though still super fixable problems

**Comment by Cheshify** [comment]
> It seems very fixable but elevator music seems more fitting as an upgrade applied to the elevator. Overall though still super fixable problems

So instead of it being a constant annoyance it's now an upgrade that is entirely negative? I don't see how that tracks as a possible fix.

**Comment by Cheshify** [comment]
I know I'm just speaking for myself when I say this, but I would much rather just take the central/side staircase so I could avoid the song blasting in my left/right ear. I don't think that's good.

**Comment by Iamgoofball** [comment]
We could pretty easily disable the directional audio on it so it's not stuck in one ear.

**Comment by Iamgoofball** [comment]
```The elevator music is agonizing when you're ghosted on a map with a lot of elevators. It goes through walls, and due to how soundloops work you'll have a 5.83 second sound clip just playing in either your left or right ear and it's really annoying.```
HTML audio lets us fix this by properly doing falloff so it steps down the second you're out of the elevator, along with removing the ear-based directionality.
```The song is just not good enough and the clips don't merge seamlessly enough for me to enjoy listening to it. It's royalty free music, it's fine, it's not something I want chopped up and blasting entirely in one ear as I try to handle tickets or watch people be funny spessmen. It just doesn't sound good.```
HTML audio lets us loop clientside in an embedded audio element, which loops a hell of a lot smoother than BYOND sound loops.
```You can't disable it, just like tcomms, it's not a part of audio prefs.```
We can easily add a pref for it.
```It plays from way too far away, I heard it decently at around 8 tiles away, this leads into frustration as a ghost and a separate issue while playing.```
Totally fixable.
```There are a few map specific issues listed below.```
See above fixes.

**Comment by Cheshify** [comment]
A few issues still remain- I don't want it in the North Star, and song isn't good enough justify playing on-loop in certain areas.

**Comment by DrDiasyl** [comment]
> ```The elevator music is agonizing when you're ghosted on a map with a lot of elevators. It goes through walls, and due to how soundloops work you'll have a 5.83 second sound clip just playing in either your left or right ear and it's really annoying.```
> HTML audio lets us fix this by properly doing falloff so it steps down the second you're out of the elevator, along with removing the ear-based directionality.
> ```The song is just not good enough and the clips don't merge seamlessly enough for me to enjoy listening to it. It's royalty free music, it's fine, it's not something I want chopped up and blasting entirely in one ear as I try to handle tickets or watch people be funny spessmen. It just doesn't sound good.```
> HTML audio lets us loop clientside in an embedded audio element, which loops a hell of a lot smoother than BYOND sound loops.
> ```You can't disable it, just like tcomms, it's not a part of audio prefs.```
> We can easily add a pref for it.
> ```It plays from way too far away, I heard it decently at around 8 tiles away, this leads into frustration as a ghost and a separate issue while playing.```
> Totally fixable.
> ```There are a few map specific issues listed below.```
> See above fixes.

Oh wow, can we already use this HTML audio?

**Comment by Cheshify** [comment]
I wouldn't have an issue with HTML audio if it could be disabled clientside. However, we shouldn't keep the current annoying system around while it gets totally retooled.

**Comment by Rex9001** [comment]
Elevator music is extremly good and makes rounds really fun, having that classic elevator tune playing whilst getting shot by a nukie is extremly funny

**Comment by Cheshify** [comment]
The current implementation is not good, it's annoying, doesn't sound good, and is agonizing to ghosts.

**Comment by Loafin34** [comment]
just make an option to turn off game music in general: instrument midis, roundstart music, elevator music, etc. etc... it'd be nice for people who play this game while having work on the side to do when things are quiet.

**Comment by kinneb** [comment]
if you dont remove it please make it toggleable my ping can be sucky so its basically eternally playing until the game realizes im 5000 tiles away

**Comment by moocowswag** [comment]
Is it not already toggleable under ambiance or literally anything already?

Cant you atleast use a tool on the elevator panel to turn off the music or something? Smash it?

**Comment by Cheshify** [comment]
> Is it not already toggleable under ambiance or literally anything already?
> 
> Cant you atleast use a tool on the elevator panel to turn off the music or something? Smash it?

There's no way to disable or not hear it, part of the issue

**Pull request closed without merging**
