### PR TITLE
Cleans up dirty mapping var edits.

### PR DESCRIPTION
**Pull request by actioninja**
## About The Pull Request

I ran every file with no changes through strongdmm to clean up every dirty var edit possible.

## Why It's Good For The Game

Even if this isn't that important, instance/var cleanup makes future mapping just a little bit easier.
Also if strongdmm ever catches on, this should be done ahead of time so that small changes stop creating huge diffs.

### CODE REVIEW

**Comment by SpaceManiac** [comment]
the horror
image

**Comment by actioninja** [comment]
Unfortunately there was a good amount of var resorting as well which inflated the diff a good amount.
Some maps like meta had a stupid amount of dirty edits though. _Lots_ of dir = 2, icon_state = <default state>, etc.

**Comment by WJohn** [comment]
The icon state stuff should save a few mapping issues in the future with certain things going invisible because they were referencing an icon name that no longer exists. Good stuff.

**Comment by ShizCalev** [comment]
conflict.

**Pull request merged**
