### PR TITLE
Tells od lints to shut the fuck up

### PR DESCRIPTION
**Pull request by ZephyrTFA**
## About The Pull Request

I want this lint to go away. it's killing me internally.
## Why It's Good For The Game

It's a pragma that no longer exists and it's throwing warninns (which are supposed to be a linter failure but isn't for some reason)

### CODE REVIEW

**Comment by san7890** [comment]
the reason why this wasn't fixed sooner is because it obfuscates the issue for later where opendream isn't respecting the `#pragma` namespace which is meant to exist for multiple different things that plug into the code regardless if opendream sees it as valid or not, see #82696 and some related conversations in maintainerbus

**Comment by ZephyrTFA** [comment]
> the reason why this wasn't fixed sooner is because it obfuscates the issue for later where opendream isn't respecting the `#pragma` namespace which is meant to exist for multiple different things that plug into the code regardless if opendream sees it as valid or not, see #82696 and some related conversations in maintainerbus

od lints are supposed to cause CI to fail.
This failure is broken, and as such this is technically needed.

**Comment by optimumtact** [comment]
od lints are in fact not all supposed to make CI fail, mso was pretty clear on that.

**Comment by ZephyrTFA** [comment]
I still want them to not have a broken pragma

**Comment by ike709** [comment]
bros didn't know about `#pragma InvalidWarningCode`

**Pull request merged**
