### PR TITLE
Makes Plasma More Canon

### PR DESCRIPTION
**Pull request by Cheridan**
Plasma aka Tritiated Ethanol aka Tritium is slightly radioactive when consumed

### CODE REVIEW

**Comment by Iamgoofball** [comment]
no

**Comment by Supermichael777** [comment]
yes

**Comment by Fox-McCloud** [comment]
>having merge commits in a freshly submitted PR for a single line change.

Shameful.

**Comment by PKPenguin321** [comment]
NOT CANON

GAS THE PLASMA LORE WAR NOW

**Pull request closed without merging**
