### PR TITLE
Adds three new disease symptoms

### PR DESCRIPTION
**Pull request by TZK13**
One positive, one neutral/obnoxious, and one negative.

Starting off with the negative one we've got spontaneous combustion, a symptom just as illusive as the unverified natural phenomenon. Basically it lights infected mobs on fire periodically, this isn't actually as bad as it first sounds considering how effective simply resisting is.

The positive one is ocular restoration which is similar to say self-respiration and stimulant in that it periodically injects you with a useful chemical, in this case oculine (Goonchem replacement for imidazoline). Now assistants across the station can weld to their heart's content.

Finally the neutral/obnoxious one is revitiligo which is basically the opposite of vitiligo in that it gives you dark skin instead of pale skin.

### CODE REVIEW

**Comment by Dorsisdwarf** [comment]
Spontaneous combustion along with the ones that freeze you in place sound pretty deadly, have you tried those out together?

**Comment by TZK13** [comment]
None of the stuns from symptoms really last that long for it to be a major concern I think, it really does take quite a few seconds for fire to actually start hurting you badly.

**Comment by CocaneStyle** [comment]
What's the point of "neutral" symptoms that don't provide any sort of stat increases?

**Comment by TZK13** [comment]
When I say "neutral" I just mean that they aren't objectively "bad" for you. Facial hypertrichosis and vitiligo are both "neutral" symptoms that decrease all stats, for some reason the wiki article has vitiligo as +2 when it's actually -2 in the code. The reason for that is simply, all three of these are obnoxious which might be the better term for it.

**Comment by CocaneStyle** [comment]
So Neutral symptoms really are useless, thanks for clarifying.  Also Facial Hypertrichosis should stop you from wearing masks.

**Comment by GunHog** [comment]
They should not be such high levels. Drop them down virus food level. Vitiligo and Revitiligo are useless and annoying symptoms that only serve to waste the Viro's time looking for actually useful symptoms, be they applied  to a heal virus or bioterror weapon.

**Comment by TZK13** [comment]
Well I lowered both vitiligo and retilitgo from level 5 to 4 which requires unstable mutagen instead of plasma, that places it alongside facial hypertrichosis and alopecia which I think is fair enough.

**Comment by CocaneStyle** [comment]
All "neutral" symptoms should have some positive stats so actually using them in viruses is possible.

**Comment by TZK13** [comment]
They're obnoxious symptoms made to fuck with the entire crew in a way that isn't blatantly antagonistic, it's incredibly annoying when a disease with facial hypertrichosis is released because then you either have to keep going to the bathroom mirrors to remove your beard every couple minutes or you just have to deal with having a big ugly beard which is even worse if you're playing a female character. I wouldn't want to promote their usage anymore then as a joke which they are.

**Comment by dannno** [comment]
If you're implying that a disease that makes the entire crew black wouldn't get any use you're insane and delusional

**Comment by GunHog** [comment]
They should be *buff* stats, not pure debuffs. That should be saved for symptoms that are true weapons or healing/support. Right now, I would have to pad the virus with other buff symptoms I do not really want or need in my griefing virus. All pure grief symptoms, including this one, need to be balanced to make the virus stronger, or at least have a buff/debuff balanced.

**Comment by CocaneStyle** [comment]
All "neutral" symptoms are considered antagonistic by the crew for the most part, and nearly all of them negatively impact all stats without giving anything in return.  Why would anyone use any symptom in their virus that is nothing but a detriment for the virus?

**Comment by Chocobro** [comment]
a virus that can turn everyone black
i'm expecting gratuitous racism :+1:

**Comment by cookingboy3** [comment]
;+1: for negro virus

**Comment by paprka** [comment]
ebigggg

**Comment by TZK13** [comment]
The fact that 90% of the discussion about this PR has to do with the joke symptom I threw in as an afterthought instead of the two the PR originally contained with real mechanics behind them is amusing.

**Comment by TZK13** [comment]
@hornygranny @Miauw62 @MrPerson @Razharas @tkdrg @Cheridan 

Could a maintainer at least comment on this.

**Comment by Tenebrosity** [comment]
You so rarely receive eye damage that the ocular restoration symptom seems like one no virologist would bother with imo

**Comment by TZK13** [comment]
Well welding a lot of things causes eye damage and people don't usually do it too much unless they have some sort of eye protection, ocular restoration is basically a way to give people free eye protection without the cumbersome nature of welding and hardsuit helmets.

**Comment by dannno** [comment]
It'll have great synergy with the nerfed version of laser eyes I'm going to add
IF I EVER FIGURE OUT GENETICS CODE AAAAAAAAAAAAAAAAAAAAAAA

**Comment by CocaneStyle** [comment]
@TKZ13
That's the problem though, most symptoms are jokes because they are all such heavy stat drains regardless what it does or how well it does it.

**Pull request merged**
