### PR TITLE
Energy melee weapons now deal Burn damage

### PR DESCRIPTION
**Pull request by Dorsisdwarf**
Edit: Now this just makes sense. Good work, whatever retard modified secvests to have the same 25 armor vs burn that they do vs being punched.

Adds myself to admins.txt

### CODE REVIEW

**Comment by Steelpoint** [comment]
Seven hits, they take seven hits to crit now. Whereas it takes five hits to crit someone without armour...

While this makes thematic sense this will make it hard to balance things, because the energy value is used to determine how long your stunned from ranged stun attacks.

**Comment by AlexanderUlanH** [comment]
I imagine this change makes it use the laser armor type, not the energy armor type.

**Comment by Steelpoint** [comment]
My mistake, but my main point stands in that armour is almost now utterly worthless against Eswords.

**Comment by Steelpoint** [comment]
Upon further revision this change does absolutely nothing balance wise.

Currently it takes seven hits to crit someone wearing armour, with this change it will take seven hits to crit someone wearing armour.

**Comment by Dorsisdwarf** [comment]
It's four hits to crit someone without armor from fullhealth, not five, anyway.

**Comment by WJohn** [comment]
So wait does this PR split up melee damage types into melee brute and melee burn?

**Comment by Dorsisdwarf** [comment]
What?

It literally just sets energy weapons to deal burn damage, not brute.

What do you mean, "melee damage types"?

**Comment by Steelpoint** [comment]
Is this even necessary? It adds a whole new level of balancing complications to one attack system, so instead of melee damage almost always dealing brute damage now we're dealing with some that deal melee and some that deal burn.

Not to mention this means Riot Armour is not useful in melee now.

I believe we're better off balancing the values as they stand instead of trying to split them up further.

**Comment by WJohn** [comment]
Currently armor is made so that it blocks entire spectrums of damage types. The only example which falls into this currently is melee protection that helps prevent both brute AND burn damage. I was wondering if you split it up, but given your answer it doesn't seem so.

**Comment by Dorsisdwarf** [comment]
I was apparently completely unaware of how armor worked then. I guess splitting it by actual damage type would have been too much &!@!ing difficulty.

This is now a fucking fluff PR

**Comment by WJohn** [comment]
So wait this DOES split up brute and burn melee attacks? Does this mean that using a welding tool on a guy with a riot suit is straight up better than a circular saw?

**Comment by Steelpoint** [comment]
It always has been since welding tools deal burn damage.

**Comment by Dorsisdwarf** [comment]
Wjohn, have you considered looking at the damn 2 line change made instead of being really confusing?

**Comment by Cheridan** [comment]
Burn doesn't cause KO, so this is a pretty big nerf to eswords.

**Comment by Dorsisdwarf** [comment]
:(

**Comment by Jordie0608** [comment]
If I'm not mistaken you can make a weapon deal both brute and burn damage and armor needs to protect against both to nullify the damage

**Pull request closed without merging**
