### PR TITLE
Adds DrawPixel() + Easels + Canvases!

### PR DESCRIPTION
**Pull request by RemieRichards**
Yet more random pixel related stuff.
- Adds DrawPixel(), and interface for DrawBox() for ease of drawing 1 pixel on an Icon.
- Adds DrawPixelOn(), an interface for DrawPixel() for ease of drawing 1 pixel on THIS ATOM's icon, and setting it.

Both return the modified icons if they succeeded.

This was made for some form of freeform drawing (Think custom grafitti) But as of yet doing that is literally Pixel Hunting the game as you carefully try to draw your image without fucking up. 
It worked, it was just super difficult/annoying for the "artist", Also yes I know that it would totally only be used for griefing/messing around, but that's what grafitti is for.
- Adds Easels, a holder for canvases
- Adds Canvases! Draw on these with crayons, clean one pixel with a rag or soap, clean it all off by clicking it with itself (It's a giant etch-a-sketch!) - Sprites by Nienhaus
- Canvases held in your hand look (to you) like the picture you drew! Amazing!

### CODE REVIEW

**Comment by Cheridan** [comment]
Typically the concern with user-generated content is "what if they draw a dick"

We have the advantage of being /tg/station and hence not giving a damn!

**Comment by RemieRichards** [comment]
True, we'll end up with plenty of dicks, but I kind of hope people also go the route of cableart with it and just draw wild/awesome stuff. 

I haven't given up on trying to implement the custom drawing use case for this, just thought while I struggle it'd be nice to commit the procs.

**Comment by Iamgoofball** [comment]
stop being optimistic

you know that there will be dicks

**there will be dicks**

**Comment by WJohn** [comment]
There aren't a whole lot of cable art dicks or grafitti dicks, I'm not expecting too many once the hype dies down a bit.

**Comment by RemieRichards** [comment]
@WJohn can I get a Canvas+Eisel object sprite? even with the current constraints of pixel hunting, that'd be pretty cool.

**Comment by optimumtact** [comment]
the proc name should be dixel()

**Comment by RemieRichards** [comment]
Alright I got sprites from @Nienhaus and have Added Canvases and Easels.

**Comment by Cheridan** [comment]
>Canvases held in your hand look (to you) like the picture you drew! Amazing!

No way to get them to show for other people?

**Comment by RemieRichards** [comment]
@Cheridan Well, I'm not sure about examining them to see it in their hands (Which *probably* would appear like your drawing)

I could allow you to "attack" someone to show you them with (target << actualbackup) to show them the image, but that seems odd.

**Comment by Miauw62** [comment]
Allow people to frame paintings/pictures and hang them on walls or
something. You could probably make the sprite be a downsized version of the
actual picture, photos do that.

**Comment by RemieRichards** [comment]
@Miauw62 there'd be no need to downsize it, As I already stated, this version is still pixelhunty and is manily for the novely of it.

So if pictures could be hung on walls in this iteration, they'd already show their picture contents.

**Comment by CosmicScientist** [comment]
Ooo, space art. If you do allow the pictures to be hung on walls in a future iteration, would you also consider allowing them to be saved like literature in the library or would that cause issues similar to the book ordering console or even not be worth it besides the one in one hundred dick drawings that can be appreciated for actually being good?

**Comment by RemieRichards** [comment]
not actually sure if it's easy/practical to export images from byond.
They'd also need a home to sit in and a database to organise them.

**Comment by CosmicScientist** [comment]
Ah databases, I blissfully forgot they existed. Don't worry about my suggestion then.

**Comment by optimumtact** [comment]
It would most likely end up a database of poorly drawn lewd art

**Comment by Jordie0608** [comment]
Changelog

**Comment by SconesC** [comment]
Will the papers be PDA-scannable?

**Comment by RemieRichards** [comment]
@SconesC say what now?

**Comment by Cheridan** [comment]
You can hit a paper with your PDA to copy it to your notes.

I don't think these are actually paper, though, so probably not.

**Comment by tigercat2000** [comment]
If it's possible, I think spraycans should draw a 3x3px box. For fancier drawings, or something. 
:neutral_face:

**Comment by RemieRichards** [comment]
Ideally all crayons (including spraycans) will be able to, on walls and floors (and now canvases), bring up an enlarged version of what they're drawing on, so that you can draw without pixelhunting.

Not in this first PR though, sadly.

**Comment by Amnestik** [comment]
pretty incredible.

**Comment by Crystalwarrior** [comment]
Added a zooming function on Atlas Station codebase, going to PR it soonish. Here's a screenie:
http://puu.sh/i4Sfe/891fb76780.png

**Pull request merged**
