### PR TITLE
FIX - Adds the prototype canister icon to the game

### PR DESCRIPTION
**Pull request by Robustin**
Lets just say the icon got ~ ATOMIZED ~

### CODE REVIEW

**Comment by KorPhaeron** [comment]
>broke every canister in the game
>didnt even have icons
>150 hours of testing

Hmm

**Comment by Robustin** [comment]
AHHHHHHH

**Comment by Robustin** [comment]
>Working canister with icon, doesn't break the game
>Forced to atomize and scatter dozens of icons into different PR's
>Frequent testing becomes unfeasible across 10 PR's
>Maintainer nitpicking (switch looks cleaner than if statements just put them all in!) breaks the canister code

**Comment by coiax** [comment]
This uh, isn't just a fix for the cannisters, you also are including your ship

**Comment by Haevacht** [comment]
Looks like you forgot to atomise your fix, nerd.

**Pull request closed without merging**
