### PR TITLE
Removes TG

### PR DESCRIPTION
**Pull request by YakumoChen**
It's time to end it

### CODE REVIEW

**Comment by trexter555** [comment]
+support

**Comment by optimumtact** [comment]
`r/station`

**Comment by Ty-the-Smonk** [comment]
reddit time

**Comment by Dawson1917** [comment]
Agreed. This is such a shit gamemode. Its literal only purpose is to grief, and the only people allowed to have fun are powergaming validhunters and the antags. Everyone else is just an NPC to be horizontal'd. We need to stop catering to these kinds of shitters and remove this mode for good.

To quote Nicholas Cage;
>It's quite obvious the change will be wildly unpopular but I don't believe that changes the fact of it being necessary or not.

**Comment by datorangebottle** [comment]
SS13 is such a shit game, why can't we play lifeweb on sybil instead?

**Comment by FancyCyclops** [comment]
With the current attitude towards TGstation, why bother with trying to fix around the holes?

Cut the middleman and just end it.

**Comment by wesoda25** [comment]
What

**Comment by Detective-Google** [comment]
change the /tg/ to TG 
we redditstation now boys

del: reddit

**Comment by Shadowflame909** [comment]
Have we ever done a traditional game

**Comment by FancyCyclops** [comment]
Hmm. Why did someone get blocked, I wonder? 
also go dnd in dorms lmao

**Pull request closed without merging**
