### PR TITLE
Buffs the Medical Beamgun

### PR DESCRIPTION
**Pull request by silicons**
Medbeam gun now heals toxins and oxygen damage.
:cl:
tweak: Nanotrasen has reprogrammed their medical beamgun nanite streams to heal toxins and simulate the effects of oxygen as well!
:cl:

### CODE REVIEW

**Comment by PKPenguin321** [comment]
Mekhi buffing himself :-1:

**Comment by kevinz000** [comment]
>Mekhi buffing himself
I DONT EVEN USE THEM.
because the last time i did some hubbie-op blew me up when i was nuke leader ;-;

**Comment by optimumtact** [comment]
You didn't justify why you need this buff?

**Comment by PKPenguin321** [comment]
no mekhi you dont use them you have a lackey use it on you

👎

**Comment by Bawhoppen** [comment]
extreme powercreep

**Comment by Iamgoofball** [comment]
i usually buy one of these as a nuke op support dude, :+1: for buffing them, they needed it

**Comment by KorPhaeron** [comment]
If they have oxygen damage, means they were in critical, don't need super fast healing out of crit

**Pull request closed without merging**
