### PR TITLE
Changes the name of the Love Shack

### PR DESCRIPTION
**Pull request by KazeEspada**
Previously Lotsu's Love Shack is now Jean's Love Shack.

### CODE REVIEW

**Comment by TechnoAlchemisto** [comment]
so sensitive

**Comment by optimumtact** [comment]
You're glasses!

**Comment by PKPenguin321** [comment]
:-1: cuck shed is way funnier

**Comment by KazeEspada** [comment]
It is, but it doesn't match. I mean it only has one table. Needs at least two to properly cuck Mehki

**Comment by Aloraydrel** [comment]
Cuck Shed is better

**Comment by Cheridan** [comment]
sorry kaze you have been overruled by the design lead

**Pull request closed without merging**
