### PR TITLE
makes it so the sanitize_hexcolors' default is 6 characters rather than 3 and gets rid of color_legacy

### PR DESCRIPTION
**Pull request by Seris02**
## About The Pull Request

title

I thoroughly tested this on tg code, and unless I missed something, which, I'm gonna admit is totally possible, it should be totally fine, even with legacy prefs.

Unless you know of a reason as to why it was 3 characters rather than 6 in which case please tell me

## Why It's Good For The Game

***better colour picking***

## Changelog

:cl:
code: removes color_legacy prefs and changes sanitize_hexcolor()'s default to 6 characters
/:cl:

### CODE REVIEW

**Comment by Ghommie** [comment]
I'm pretty sure there're a few `sanitize_hexcolors()` calls with `desired_format` explicity set to 3 in the code.
Also this is why I refactored the `sanitize_hexcolors()` last year. If I hadn't, this would have brought quite a few issues since `sanitize_hexcolors()` was only capable of converting RRGGBB to RGB and not the other way around. Thanks goodness that's not the case anymore.

**Review by Mothblocks — CHANGES_REQUESTED** [review]
If you're going to do this, remove `/datum/preference/legacy_color` or whatever it was as well, since that is the only reason it exists.

**Comment by Ghommie** [comment]
> 
> 
> If you're going to do this, remove `/datum/preference/legacy_color` or whatever it was as well, since that is the only reason it exists.

`/datum/preference/color_legacy`

**Comment by Seris02** [comment]
> you arent updating the procs that had it set to 6

There is none so I don't need to :p

**Comment by Seris02** [comment]
> I'm pretty sure there're a few `sanitize_hexcolors()` calls with `desired_format` explicity set to 3 in the code. Also this is why I refactored the `sanitize_hexcolors()` last (or earlier this) year. If I hadn't, this would have brought quite a few issues since `sanitize_hexcolors()` was only capable of converting RRGGBB to RGB and not the other way around. Thanks goodness that's not the case anymore.

There is not anything other than sanitize_hexcolors(color) in the code right now, no calls to setting default_value to anything, if you search sanitize_hexcolor in the code, you can see what I mean. Also thank you for rewriting it otherwise I would have had to do it myself

**Review by Mothblocks — APPROVED** [review]
Pending me testing migrations of pre and post tgui prefs.

**Comment by Mothblocks** [comment]
Looking at this today

**Pull request merged**
