### PR TITLE
Makes The North Star a martial art Ided

### PR DESCRIPTION
**Pull request by Fhaxaris**
## About The Pull Request
Makes The North Star a martial art, meaning you can no longer combine it with other martial arts. Equipping the gloves of the north star will give you this martial art (like warden krav maga), so if you already have Sleeping Carp, CQC, etc. nothing will happen. It also adds a granter for silliness.

## Why It's Good For The Game
The gloves of the north star allow you to attack very fast, combined with the armor-piercing and high damage of Sleeping Carp, allow you to kill any target, no matter the armor they are wearing. The North Star is supposed to be used by itself, the speed doesn't affect weapons, only fists. Sleeping Carp bypasses this by nearly tripling the damage while keeping the speed. It is just really unbalanced.

## Changelog
:cl:
tweak: made north star into a martial art, the gloves of the North Star now give the martial art "The North Star"
balance: North Star + Sleeping Carp and other martial arts are now forbidden combinations
add: added granter for North Star martial art (admin only)
/:cl:

### CODE REVIEW

**Comment by SkeletalElite** [comment]
Fun while it lasted, but was clearly busted. Click someone with grab intent > harm intent and click until dead was brain dead easy killed someone in just a few seconds.

**Comment by Fhaxaris** [comment]
oops I am having an aneurysm.

**Comment by Pugie** [comment]
You've given birth to carp power fist meta that is even worse good work.

This item sucks on its own by the way, might as well just remove it instead of this for being anime.

**Comment by Tharcoonvagh** [comment]
yeah remove it

**Comment by necromanceranne** [comment]
don't remove it, it's actually pretty decent with a stun baton or similar means of disabling people. It is still bad after this PR we can come back and make it stronger given it is it's own martial art and gives you room to improve.

**Comment by HomocidlePancakes** [comment]
Really? That’s it? You are just separating it in to it’s own martial art without adding any new cool moves or anything? Like, I understand that this is a salt fueled ided nerf, but at least put some effort in to it.

**Comment by Ty-the-Smonk** [comment]
Make it a actual martial art then

**Comment by Ty-the-Smonk** [comment]
Tbh make it 20 tc and give a modified plasma fist + the speed punches since plasmafist is unused and is similar to the actual North Star technique with the organ failure punches

**Comment by HomocidlePancakes** [comment]
>Tbh make it 20 tc and give a modified plasma fist + the speed punches since plasmafist is unused and is similar to the actual North Star technique with the organ failure punches

North Star removes CD only on punches. Not shoves, grabs or hugs. Only punches.

**Comment by ExcessiveUseOfCobblestone** [comment]
> Really? That’s it? You are just separating it in to it’s own martial art without adding any new cool moves or anything? Like, I understand that this is a salt fueled ided nerf, but at least put some effort in to it.

sounds like a great first PR!

**Comment by GravitronBlue** [comment]
I wouldn't say this is the right way to nerf sleeping carp, attack speed rarely seems to be an issue compared to sleeping carp's innate one-click stun which can have zero tells or warning other than behavior.
The only linkable issue I can think of to North star gloves is it being faster to finish people off after you grab them and possibly quicker body throwing.

My thoughts are either make it so the stun grab requires being behind the target or them being down to score the instant aggressive grab on, or buff the other 2 other existing stun combos (back kick and stomach knee).

Reason is mostly that sleeping carp should be combo focused for damage and utility and not merely because your grab gets upgraded  into a one-click win murderbone meme, the flavortext _"Grab them first so they don't retaliate..."_ confirms this as well.

...

As for the rest of sleeping carp:
I dislike default attacks bypassing armor stats, especially for riot armor (something specifically meant for close quarters combat and impacts), as well as having indefinite ranged stun immunity.

Preferably give it 30-50% armor penetration instead and if possible an endurance meter that very quickly regenerates, enough so that one or two people shooting at you with mere lasguns won't be able to get through but, anything much more than that will quickly overwhelm it provided you aren't dodging. (Think Jedi during order 66 with an overwhelming amount of ranged weaponry getting through, and so deathsquad pulse beams aren't some joke against you)

Only problem I haven't worked out with this would be a meta of going for shotguns and rubber/buckshot, was thinking some kind of a more focused deflection that would make it near suicide to use buckshot at effective range alone, but that a couple shotgun users could stay up long enough to be effective.

Regardless, I hope this can at least help inspire some better changes.

**Comment by GuyonBroadway** [comment]
This wasn't so bad when carp was a single item that cost too much to be purchased with gloves.

Then again one slippery boi with a toolbox can ruin everything...

**Comment by HomocidlePancakes** [comment]
@guyonbroadway

You can’t purchase carp and gloves with 20 TC.

**Comment by GuyonBroadway** [comment]
I thought carp now came as a mask and you needed to buy it twice for projectile deflection but you could buy it once for AP punches plus gloves for lots of doom.

Also if you wanna make it not bad  and something worth a bigger tc pricetag consider removing the harm intent limitation for _fun times'

**Comment by ATH1909** [comment]
> I thought carp now came as a mask and you needed to buy it twice for projectile deflection but you could buy it once for AP punches plus gloves for lots of doom.

... no?



> @GuyonBroadway
> 
> You can’t purchase carp and gloves with 20 TC.

Well, you can if one of them is on sale.

IMO, the gloves of the north star+sleeping carp wombo combo is really strong, but it's at around the same power/station-destruction level as romerol (which also normally costs >20 TC), so I think it's okay to keep in the game (you'll only see it rarely when certain items are discounted or two traitors team up).

**Comment by FantasticFwoosh** [comment]
Lorewise they are clearly rival schools, so two traitors committing dojo invasions on the other is valid.

Cheese is dead, long live the cheese. :+1:

**Comment by itseasytosee** [comment]
They cost more than 21 TC together for a reason.
also, you have not updated the uplink so it would just give you the non-existant gloves.
So then I assume this is untested?

**Comment by Shadowflame909** [comment]
It's like when romerol is on sale. A rare chance for za POWA.

This nerf is lame since it's worried about the ocassional potential of an antag instead of the average potential.

**Comment by Spepbuthewranglesgithub** [comment]
this reeks of antifun, the armor piercing on carp is _disgustingly_ powerful yes, but that does not warrant complete mutilation of this one combo that 9 out of 10 times is not gonna happen, not to mention you can kill people just as easily if not moreso with a good ol ebow/sword, stun baton/chemnade, romerol... really though, unless someone is planning to rework the entire traitor kit, this is just gonna make even less people want to take the niche martial art over the stabby stabby big damage stick.

**Comment by ExcessiveUseOfCobblestone** [comment]
taking the "kills fun" route when the combo is only used to make a portion of the people trying to play the game sit in observer is really interesting.

**Comment by Spepbuthewranglesgithub** [comment]
> taking the "kills fun" route when the combo is only used to make a portion of the people trying to play the game sit in observer is really interesting.

yes, it is, so is the big hurt stick with absolutely any form of restraining measure.

**Comment by ExcessiveUseOfCobblestone** [comment]
if you mean the desword, I agree. Trying to counter touching to the items with "anti-fun" when both items are meant solely to make people sit as a ghost the rest of the round is quite odd.

**Comment by Fhaxaris** [comment]
> also, you have not updated the uplink so it would just give you the non-existant gloves.
So then I assume this is untested?

they work like warden krav maga gloves

**Comment by Fhaxaris** [comment]
> This nerf is lame since it's worried about the ocassional potential of an antag instead of the average potential.

yea, it only nerfs the unbalanced combination without effecting it otherwise, how is that lame?

**Comment by Shadowflame909** [comment]
> 
> 
> > This nerf is lame since it's worried about the ocassional potential of an antag instead of the average potential.
> 
> yea, it only nerfs the unbalanced combination without affecting it otherwise, how is that lame?

The worst part about nerfs like these is that it only allows ONE SIZE FITS ALL solutions like the stun baton.

Sometimes your gonna have to find other ways to kill strong things. Like space lube, syringe guns, or a shitload of beartraps.

I love it when rare occurrences happen that make an antagonist stronger than usual. It shakes up the META way to win (Shoot at it until it stops moving, or harmbaton it until it goes down) And it makes players get out of their comfort zone.

Death is stinky, but that's gonna get nerfed in general when all items do less damage. Or all races have more resistance to dying.

Forcing a change in strategy every once in a while due to rare occurrences is a good thing and this takes a huge dump on the concept of rare powerful and out of the norm items itself.


So yes. GIT GUD. Learn how to counter someone you can't shoot at from afar to win, and you can't get close to. Soap and a Locker is your friend.

**Comment by Fhaxaris** [comment]
>Forcing a change in strategy every once in a while due to rare occurrences is a good thing and this takes a huge dump on the concept of rare powerful and out of the norm items itself.
>So yes. GIT GUD. Learn how to counter someone you can't shoot at from afar to win, and you can't get close to. Soap and a Locker is your friend.

You are entirely missing the point of this PR. How powerful Sleeping Carp is on its own or how I am un-robust for getting insta-stunned are irrelevant. The gloves act like a martial art and directly change how unarmed works, but they are not treated as such.

The Gloves of the North Star already can't be used with hulk. Why? Because it's clearly unbalanced. Sleeping Carp is no different. Attacking at 12.5 damage at four times the regular attack speed along with all the other buffs of carp is unbalanced to the point of absurdity.

>this reeks of antifun, the armor piercing on carp is disgustingly powerful yes, but that does not warrant complete mutilation of this one combo that 9 out of 10 times is not gonna happen,

Why not? Just because it won't happen often doesn't justify the fact it is horribly unbalanced.
> not to mention you can kill people just as easily if not moreso with a good ol ebow/sword, stun baton/chemnade, romerol...

Ebow + sword is much less effective and actually does way less damage than Carp + Star. Stun/baton + chemnade requires much more setup, takes longer, and can't be done indefinitely. Romerol doesn't kill people, it turns them into zombies, not that annoying to "die" from.
> really though, unless someone is planning to rework the entire traitor kit, this is just gonna make even less people want to take the niche martial art over the stabby stabby big damage stick.

Carp isn't niche, where did you get that idea from. Why would people want to take an esword over Carp after this, Carp isn't being nerfed.

**Comment by MarioWizard119** [comment]
This isn’t a problem with GotNS, this is a problem with the carp scroll. This particular combination is a once-in-a-blue-moon incident that happens in the rare occasion in which either of these items go on sale. It’s the instant aggressive grabs that make the carp scroll a one click murderbone meme, not combos with the GotNS. The same thing can be done with a syndie toolbox to finish off foes, and you can do that far more often.

**Comment by Spepbuthewranglesgithub** [comment]
> Why not? Just because it won't happen often doesn't justify the fact it is horribly unbalanced.

discounted mechs for ops, discounted holopara, discounted Desword, pretty much any discounted high cost item, are _absolutely_ busted, and rare, some miner loot can be pretty broke too, and _oh boy xenobio_, so either the discount system in general, some _particular_ miner drops, and half of the things xeno can make need to be nerfed too, or it _does_ justify the unbalance

> Ebow + sword is much less effective and actually does way less damage than Carp + Star. Stun/baton + chemnade requires much more setup, takes longer, and can't be done indefinitely. Romerol doesn't kill people, it turns them into zombies, not that annoying to "die" from.

alright, Romerol wasn't a good example, fair enough. Ebow/sword is less effective yes but not by enough to make a diffrence for greyson mcbone ripping through engineering, and as for chemnades, the setup is a dispenser, some wire, and some metal, slap together a potassium bomb and you got some easy hurt, if you can grab some large beakers you even get to gib.

> Carp isn't niche, where did you get that idea from. Why would people want to take an esword over Carp after this, Carp isn't being nerfed.

no, Carp isn't niche, the gloves on the other hand...

**Comment by gitbirb** [comment]
> discounted mechs for ops, discounted holopara, discounted Desword, pretty much any discounted high cost item, are _absolutely_ busted, and rare, some miner loot can be pretty broke aswell, so either the discount system in general and some _particular_ miner drops need to be nerfed too, or it _does_ justify the unbalance

oh no don't give him ideas. Also overall my opinion on this pr is it's bad because it just reeks of salt over a rare combo that shakes up the meta, like almost all discounted items on uplink.

**Comment by optimumtact** [comment]
martial arts need a rework in general.

**Pull request closed without merging**
