### PR TITLE
Fixes marooned status.

### LINKED ISSUE #33520: White Ship counts as you getting marooned when roundends.
roundid 80140

### PR DESCRIPTION
**Pull request by AnturK**
Fixes #33520

### CODE REVIEW

**Comment by Dorsisdwarf** [comment]
I believe this would fix #34970 too

**Comment by KorPhaeron** [comment]
Two character fix and the issue is breaking all our stat tracking

**Comment by AnturK** [comment]
Stat tracking was fine, it's just the display. However the other report makes me worry it's something more.

**Comment by deranging** [comment]
You also count as marooned if you are sitting in a chair when the shuttle hits centcom

**Pull request merged**
