### PR TITLE
Shielded Hardsuits now have an internal jetpack

### PR DESCRIPTION
**Pull request by Robustin**
YOU KNOW, LIKE THE REST OF THE SYNDICATE HARDSUITS EXCEPT THIS ONE COSTS 30TC HNNNNGH.

### CODE REVIEW

**Comment by TechnoAlchemisto** [comment]
if youre not using your back jetpack you are scum

**Comment by Robustin** [comment]
> Spawned as reinforcement
>Codernerds haven't fixed game-breaking hardsuit bug
>Spend almost my entire TC budget on shielded hardsuit, all the jetpacks are taken by now
> LOL GIT REKT NERD UR SUIT IS SHIT AND CANT HANDLE SPESS

**Comment by Robustin** [comment]
Tested it, worked g8, I am best coder.

**Comment by TechnoAlchemisto** [comment]
robustin g8 sounds phonetically like gate

**Comment by Shadowlight213** [comment]
Powercreep. smh tbh fam. Make jetpacks cheap in ops upinks

**Comment by Robustin** [comment]
Shadowlight back to the meme farm. 

It's absurd that something that's supposed to be an upgraded syndie hardsuit lacks one of the core features of the syndie hardsuit.

**Comment by Shadowlight213** [comment]
I know. It makes sense.
It's just, what's the point of having jetpacks If they all are going to be made built in?

**Comment by KorPhaeron** [comment]
I don't really like inbuilt jetpacks at all but it doesn't make much sense for this one to lack it if all the others are gonna have them

**Comment by Robustin** [comment]
If you let people use jetpack from suit storage you'd have a better middle ground.

**Pull request merged**
