### PR TITLE
Fixes pAIs not being able to use messenger

### LINKED ISSUE #13722: PAI "lacks dexterity" to use digital messenger software
Downloaded digital messenger, tried to message a crewmember, this popped up in red italics:

"You don't have the dexterity to do this!"

This was in space, inside someone's pocket, near the bananium clown shipwreck. Problem persisted at the derelict station, and presumably would be the same everywhere else.

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
Thanks to @dragonrobot from Hippie for the fix

Fixes #13722

### CODE REVIEW

**Comment by Arquebusier** [comment]
:+1:

**Comment by JJRcop** [comment]
Are you sure you fixed that?

**Comment by GunHog** [comment]
Did you test this? I stole this fix from Hippie as well, but never got a PDA message on my human character.

I highly recommend you play as pAI and test this live, because I do not believe this works as is.

**Comment by KorPhaeron** [comment]
I tested using the messenger, and sending a message, but didnt confirm I recieved it

**Comment by ike709** [comment]
@KorPhaeron pretty sure that's the wrong issue number in the OP

**Comment by KorPhaeron** [comment]
Huh. Thanks

**Comment by ike709** [comment]
I assume you had "Fixes #1597" because Hippie's #1597 was the solution you copied for this issue.

**Comment by GunHog** [comment]
>I tested using the messenger, and sending a message, but didnt confirm I recieved it

This is where I had problems, I did not get the dexterity message, but I could not find the message in the log, nor did my human character receive the PDA message. I strongly recommend testing this before requesting a merge.

**Comment by tkdrg** [comment]
kor testtesd this again and he says it works

**Pull request merged**
