### PR TITLE
New stunbaton icon by Sirich96

### PR DESCRIPTION
**Pull request by tralezab**
## About The Pull Request

they're pretty rad, right?
image

## Why It's Good For The Game

soul must die, our game must have no heart (real talent) in it

## Changelog
:cl: Sirich96
imageadd: new stunbaton sprites
/:cl:

### CODE REVIEW

**Comment by Sirich96** [comment]
Thanks for putting up the PR for me!

**Comment by ShibaInuLord** [comment]
soul has been deleted

**Comment by Iatots** [comment]
Almost looks telescopic now, which it isn't.

**Comment by Jared-Fogle** [comment]
image
Why does the animation for the active stun baton only loop 5 times?

**Comment by Sirich96** [comment]
> image
> Why does the animation for the active stun baton only loop 5 times?

Believe it or not, the current one does that too.

**Comment by wesoda25** [comment]
I think it’d look a lot better without the hilt thing

**Comment by nullAdept** [comment]
It looks frail and weak

**Comment by ShizCalev** [comment]
@Sirich96 make it always loop.

**Comment by tralezab** [comment]
I can just tick it to always loop on my side. It's stupid that stunbatons don't loop indefinitely.

**Comment by bluetshirtguy** [comment]
Un ironically Not an ounce of soul.

**Comment by Angustmeta** [comment]
Could be made even more clear when it's on or off. With current sprites it can be hard (for me) to tell from a glance so I tend to switch it off and on again to be sure.

**Comment by tralezab** [comment]
There's gonna be a second version coming up shortly

**Comment by GuyonBroadway** [comment]
Oh so you're the kinda guy who points his baton right are you?

**Comment by tralezab** [comment]
image

**Comment by tralezab** [comment]
new, removed spikes different coloring, etc

**Comment by wesoda25** [comment]
Can we see it ingame?

**Comment by Sirich96** [comment]
> Can we see it ingame?

Ingames

**Review by Twaticus — APPROVED** [review]

**Pull request merged**
