### PR TITLE
Removes vile hate symbol from the game

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
Xhuis can't keep getting away with this

### CODE REVIEW

**Comment by RemieRichards** [comment]
The urge to merge is extremely high.

**Comment by Kraseo** [comment]
no please my rare pepes

**Comment by Giacom** [comment]
SELL SELL SELL

**Comment by PKPenguin321** [comment]
If the icon is null how will people examine it and know to report to the admins
:-1: on the icon change

**Comment by KorPhaeron** [comment]
Using pepe is copyright infringement sorry

**Comment by CyberbossJHCB** [comment]
Please tag as FUCK

**Comment by Anonmare** [comment]
Normie get out stop touching my Pepe reeeeeeeeeeeeeeeeeeeeeeee

**Comment by ma44** [comment]
http://www.cnn.com/2016/09/28/us/pepe-the-frog-hate-symbol-trnd/index.html

for context

**Comment by optimumtact** [comment]
This isn't even funny

**Pull request closed without merging**
