### PR TITLE
Adds support for negative values in chem macros NOW WITH TIMEGATE!

### PR DESCRIPTION
**Pull request by yorii**
:cl: yorii
tweak: chem macros now support negative value inputs
/:cl:

### CODE REVIEW

**Comment by Buggy123** [comment]
So it just removes that much reagent? Neat.

**Comment by yorii** [comment]
ikr? and it only needed 4 lines of extra code

**Comment by yorii** [comment]
PS: I did all this code on github.com and I haven't tested it whatsoever

**Comment by RandomMarine** [comment]
>PS: I did all this code on github.com and I haven't tested it whatsoever

GOOD SIGN

**Comment by Buggy123** [comment]
>PS: I did all this code on github.com and I haven't tested it whatsoever

Welcome to the club, here's your complimentary t-shirt:

failed

**Comment by Tlaltecuhtli** [comment]
does it read not basic chems like pyrosium?

**Comment by yorii** [comment]
of course! the function used to remove the reagents from the container is the same proc used by everything that removes reagents from any container.

**Comment by yorii** [comment]
also from reading the code I am about 90% certain that chem macros should support decimal values?

**Comment by vuonojenmustaturska** [comment]
Before you go any further with this, consider the following:

Chem macros are there to automate an annoying, repetitive task. They're not there to enable new functionality (removing leftover reagents), even though dispensing custom amounts is already a thing. 
Chemistry is already too close to where science used to be, where your "gameplay" is copy+pasting shit from a wiki.
Furthermore, chem macros are likely the "source" of chemistry's recent balance problems, as previously chemistry was kept in check by the shit UI. The only way increasing the power of chem macros would be OK is if we finally started addressing the problem of chemistry producing everything out of nothing, or removed chemistry as a separate department completely.

**Comment by yorii** [comment]
This functionality already exists in the machine which is situated on the tile next to this machine.
All this does is save you **literally three clicks.**

**Comment by deathride58** [comment]
B O I

This is straight powercreep and you *know it*

**Comment by CameronWoof** [comment]
Now all we need is for chem macros to heat beakers, so that we don't have to click the extra few times to use the chemical heater.

**Comment by ExcessiveUseOfCobblestone** [comment]
*sigh*

When will I ever get around to removing hand-wave chemistry :(

**Comment by kevinz000** [comment]
This is power creep plain and simple, do not try to say it is "quality of life"

**Comment by MMMiracles** [comment]
What if we just made the dispenser have every recipe pre-stocked in the machine so I don't have to do any work and every chemical at any desired quantity is ready at the push of a single button.

Truly a QoL change.

**Comment by CPTANT** [comment]
This is NOT functionality in the chem dispensor. It is a functionality of the chem master. Merging them together is not a QoL change, it is a balance change.

What's next, automatically heating recipe's to the desired temperature? This is also functionality on a tile next to the machine.

**Comment by CPTANT** [comment]
I do not understand why we bother recipe's at all if you can just get everything with the right macro and the push of a button.

Seriously, why bother?

**Comment by yorii** [comment]
> Now all we need is for chem macros to heat beakers, so that we don't have to click the extra few times to use the chemical heater.

We already do.

**Comment by yorii** [comment]
>This is NOT functionality in the chem dispensor. It is a functionality of the chem master. Merging them together is not a QoL change, it is a balance change.
Is it really a balance change to save you 3 clicks?

>What's next, automatically heating recipe's to the desired temperature? This is also functionality on a tile next to the machine.
We already have that since forever with chem macros. Geez.

**Comment by CPTANT** [comment]
>Is it really a balance change to save you 3 clicks?

YES, WHY DO YOU NOT UNDERSTAND THIS.

Why do you not understand that macros have eliminated the only balance mechanism there was on these chemicals, namely the effort to produce them.

Balancing chemicals around effort was suboptimal, but not removing it without putting another balance mechanism in place is just dumb.

**Comment by yorii** [comment]
Fine, it is a balance change that saves you 3 clicks then, why is that even a problem though?

**Comment by CPTANT** [comment]
Because it's increasing the insane output of advanced chemicals even more?

Also since when can macros heat chemicals, I see no reference to that anywhere.

**Comment by yorii** [comment]
>Also since when can macros heat chemicals, I see no reference to that anywhere.

It's unrelated to macros.

**Comment by Kraseo** [comment]
we've truly reached critical reddit mass when people think having to skip having another tgui interface open is powercreep

**Comment by Bawhoppen** [comment]
They told me I was crazy for being anti-QoL, but now look at where we are...

**Comment by CPTANT** [comment]
@kraseo Seriously, tell me the situation that we were in before with regards to chemistry balance is the same as we are now, despite only being "QoL" changes.

**Comment by CPTANT** [comment]
@yorii Yes I am aware of the existence of pyrotheum, I thought you ment macro's could set heat by themself.

**Comment by ExcessiveUseOfCobblestone** [comment]
When do people learn being tedious /is/ balance, just not /good/ balance.

If only everything was like that RPD pr where it keeps the times in.

**Comment by CPTANT** [comment]
When do people learn that replacing tedious balance with /no/ balance balance is even dumber.

**Comment by ExcessiveUseOfCobblestone** [comment]
I completely agree @CPTANT , I just hate having to type the same thing over and over on every similar pr.

**Comment by yorii** [comment]
Once #36449 gets inevitably merged I'll make sure to make this requires the highest manipulator tier. Will that stop you from shouting powercreep?

**Comment by MMMiracles** [comment]
No, because it still is powercreep.

**Comment by yorii** [comment]
So? This entire game is built around powercreep.

**Comment by ExcessiveUseOfCobblestone** [comment]
slig alt that can code how sad

**Comment by yorii** [comment]
updated to support the new chem dispenser changes and made this only usable with femtomanipulators.

**Review by Cyberboss — APPROVED** [review]

**Comment by banthebantz** [comment]
just cut out the middleman and replace chem dispensers with SCP-294

**Comment by yorii** [comment]
Tried and tested now on localhost, this PR works perfectly fine :)

**Review by ExcessiveUseOfCobblestone — CHANGES_REQUESTED** [review]
https://github.com/tgstation/tgstation/pull/36436/files#diff-62145a4bc8c6a8dc166d3cb4320bb221R245

needs to inform the player they can remove reagents at t4 (preferably ONLY when they have t4)

**Comment by yorii** [comment]
>needs to inform the player they can remove reagents at t4 (preferably ONLY when they have t4)

There is actually nothing that tells the player what the resolution limits to macros are either, there is only the warning that pops up if you try to make an unsupported macro, which also does show up if you try to use negative values before t4.

Maybe there needs to be a help button that explains the whole thing? There isn't actually any ingame doc whatsoever to how macros even work at all.

**Comment by ExcessiveUseOfCobblestone** [comment]
Not sure what you mean but if you're going to gate something behind tiers you should inform the player in some way that functionality is available when they try to make a macro. Not everyone starts with science goggles!

**Comment by yorii** [comment]
>Not sure what you mean but if you're going to gate something behind tiers you should inform the player in some way that functionality is available when they try to make a macro in the game. Not everyone starts with science goggles!

I mean that the dispenser was recently changed to require higher tier components to produce any amount lower than 5 with macros, and you only get a warning message if you try to actually put in a recipe that is not supported.

What this really needs is actually a whole help section on the dispenser itself (in tgui) which explains both that and this PR and maybe quick line explaining how to even do a macro, because none of this is actually explained ingame.

**Comment by ExcessiveUseOfCobblestone** [comment]
@yorii add it to the examine() perhaps?

**Comment by yorii** [comment]
@ExcessiveUseOfCobblestone hmm maybe, but I'd probably add all of the information regarding the upgrades there then... might as well grab the bull by the horns and do it properly in tgui. If that site to compile tgui comes back up some time soon I could probably throw that in another PR.

**Comment by KorPhaeron** [comment]
Old and conflicting, bug me when you're ready to finish the PR

**Comment by yorii** [comment]
@KorPhaeron hm.. where was it conflicting? This PR was already approved weeks ago. Please open it so I can fix any eventual conflicts.

**Comment by duncathan** [comment]
don't confuse cyberboss using the approve button to say "this is lacking code issues" with someone actually approving of your changes btw

**Pull request closed without merging**
