### PR TITLE
Adds NT Default lawset

### PR DESCRIPTION
**Pull request by ghost**
:cl: More Robust Than You
add: Nanotrasen has allowed AIs to possibly use the NT Default lawset by an upload board that it has placed in uploads on all models of the station currently in use
/:cl:

1. Safeguard: Protect your assigned station to the best of your ability. You may ignore minor damage, but substantial threats towards the structural integrity of the station must be attended to.

2. Serve: Serve the crew of your assigned space station to the best of your abilities, with priority as according to their rank and role.

3. Protect: Protect the crew of your assigned space station to the best of your abilities, with priority as according to their rank and role.

4. Survive: AI units are not expendable, they are expensive. Do not allow unauthorized personnel to tamper with your equipment.

while yes, it will serve/protect lizards and catpeople, it won't serve nuke ops. And this lawset allows it to be fine with, say, the HoS/Captain executing people (or ordering the AI to execute the greytide traitor)

### CODE REVIEW

**Comment by Tacolizard** [comment]
this doesn't add anything, lmao. these laws aren't mapped in anywhere and are totally inaccessible.

**Comment by MoreRobustThanYou** [comment]
@Tacolizard how would i do that?

**Comment by GunHog** [comment]
:warning: :warning: :warning: **YOU NEED TO CHANGE THE ORDER OF THESE LAWS SUCH THAT PROTECT IS FIRST ELSE YOU HAVE A KILLBOT DEATHSCAPE!** :warning: :warning: :warning:

**Comment by MoreRobustThanYou** [comment]
>with priority as according to their rank and role.

an assistant can't "LAW 2 KILL THE CAPTAIN", but the captain can "LAW 2 KILL TRAITOR MCTRAITOR!"


It works on other servers like /vg/ and para... why wouldn't it work here? also,

**Comment by BeeSting12** [comment]
@MoreRobustThanYou 
You'd map the board onto a map somewhere or you'd gate it behind RnD. Use the wiki's guide to mapping for the former.

**Comment by JJRcop** [comment]
>but it really shouldn't kill for breaking windows

Where does it say that in the laws?

**Comment by MoreRobustThanYou** [comment]
uhhh it doesn't but most AIs don't wanna get bwoinked

**Comment by GunHog** [comment]
>an assistant can't "LAW 2 KILL THE CAPTAIN", but the captain can "LAW 2 KILL TRAITOR MCTRAITOR!"

>It works on other servers like /vg/ and para... why wouldn't it work here? Also the AI is also able to kill for MAJOR damage... but it really shouldn't kill for breaking windows

Do they have a priority rule as we do? I.E. Law 2 conflicting with Law 1 unless Law 2 redefines the meaning of Law 1 in some way? Or have they built up mountains of policy for the lawset as we did with Asimov? 

The Captain going "AI, LAW 2, KILL ALL NON-HEADS AND SEC" would be totally valid under this lawset, would it not? You need to adapt it to /tg/. What works for /vg/ and Paradise will not work here. We are not the same.

**Comment by MoreRobustThanYou** [comment]
Hmmm... you guys like this?

> Safeguard: Protect your assigned space station to the best of your ability. It is not something we can easily afford to replace. You may ignore minor damage, but major damage must be attended to.

**Comment by JJRcop** [comment]
I think this is the start of many edits, too many edits.

**Comment by ShizCalev** [comment]
Safeguard: Protect your assigned station to the best of your ability. You may ignore minor damage, but substantial threats towards the structural integrity of the station must be attended to.

**Comment by MoreRobustThanYou** [comment]
I've just added the board and put it in all the maps currently in rotation (Box, Meta, Delta, and Cere), lemme upload this

**Comment by MoreRobustThanYou** [comment]
I'll do this tomorrow, Github For Desktop decided to give me the middle finger and start some sort of snake bomb (opens new proccesses and closes old ones constantly) rather than actually owrking

**Comment by MoreRobustThanYou** [comment]
maybe i can pull this off tonight

**Comment by bgobandit** [comment]
>an assistant can't "LAW 2 KILL THE CAPTAIN", but the captain can "LAW 2 KILL TRAITOR MCTRAITOR!"

sounds like valadin+ to me

**Comment by nicbn** [comment]
So it's asimov with protect station and role/rank racism?

**Comment by Magikarpet** [comment]
this lawset encourages silicon validhunting while pushing them away from the role of an impartial mediator

I get what you're doing and it's fine to have as an addable lawset maybe but a roundstart one is just full retard and you may as well change asimov to validmov

This image can explain why 

shitlicon

**Comment by DoctoreMad** [comment]
>an assistant can't "LAW 2 KILL THE CAPTAIN", but the captain can "LAW 2 KILL TRAITOR MCTRAITOR!"

How? What the fuck? Here, let me ACTUALLY read the laws for you.

>Serve: Serve the crew of your assigned space station to the best of your abilities, with priority as according to their rank and role.
Protect: Protect the crew of your assigned space station to the best of your abilities, with priority as according to their rank and role.

Serve is above protect, so by default the AI is only stopping non-crewmembers form killing crewmembers. If someone says AI KILL THE CAPTAIN and the captain hasn't ordered the AI to not kill anyone or given a similar order, then its up for the AI to do it. Your post only replies to the INTENT of the law(Serving higher crew members) but glosses over the ACTUAL laws, and AIs work off the law's wording.

**Comment by DoctoreMad** [comment]
Anyways on baystation AIs choose their law priority by default, so it might be good to not do the /vg/ thing and actually adapt this law.

**Comment by Magikarpet** [comment]
I am sorry DoctoreMad, you are prying up floortiles. I have no choice but to end your life for harming the station.

**Comment by uraniummeltdown** [comment]
Paradise removed NT Default from roundstart, it's a shit lawset that results in validhunting and only obeying Command and Sec

**Comment by InsaneHyena** [comment]
Valadin and Validcop were removed for a reason.

**Comment by juanototo2** [comment]
Why not just put Mother Drone in every upload instead?
/s

**Comment by MoreRobustThanYou** [comment]
Ok, I will remove it from default, and put it in as a optional board.

**Comment by MoreRobustThanYou** [comment]
Ok i've added it to the maps

**Comment by KorPhaeron** [comment]
We had poor experiences with paladin and robocop being in the upload at roundstart. Even as optional things they were used nearly every round to let the AI kill every antag.

Basically just echoing what others have said already

Don't think this will work out, sorry

**Comment by DoctoreMad** [comment]
>to let the AI kill every antag.

Peacekeeper available roundstart when

**Pull request closed without merging**
