### PR TITLE
[NO GBP] Spider Healing Fix

### PR DESCRIPTION
**Pull request by Comxy**
## About The Pull Request
I didn't look at the healing component good enough.
## Why It's Good For The Game
This fixes my over sight.
## Changelog
:cl:
fix: Spiders can heal correctly again.
/:cl:

### CODE REVIEW

**Comment by Helg2** [comment]
Maybe just subtype everything under `basic/spider/...` or something?

**Comment by Comxy** [comment]
> Maybe just subtype everything under `basic/spider/...` or something?

That is a good idea for the next big spider update, I'll leave this just as a fix though. Someone merge this as soon as possible please, now everyone sees how blind I am.

**Comment by san7890** [comment]
clashes with #77523

**Comment by Comxy** [comment]
Gets fix by another pr

**Pull request closed without merging**
