### PR TITLE
Update CI byond version to 512.1441

### PR DESCRIPTION
**Pull request by Cyberboss**
Stable as 1427 yet?

@tgstation/commit-access @MrStonedOne

### CODE REVIEW

**Comment by optimumtact** [comment]
dreams are free lol

**Comment by Jared-Fogle** [comment]
But then OOC won't be spammed with people crashing from wiggle code

**Comment by SpaceManiac** [comment]
There are definitely a couple remaining client issues but 1441 has been running on Bagil for a while and I haven't noticed any server issues locally

**Comment by optimumtact** [comment]
@Jared-Fogle this is the server version used in travis builds, not the minimum client version

**Comment by Jared-Fogle** [comment]
ok good

**Review by SpaceManiac — APPROVED** [review]

**Pull request merged**
