### PR TITLE
Fixes css appending forever.

### PR DESCRIPTION
**Pull request by AnturK**
This is kinda crude but should work as stopgap.

### CODE REVIEW

**Comment by optimumtact** [comment]
This works  but damn is generation of the spritesheets slow lol

**Comment by Jared-Fogle** [comment]
Because the webhook processor is written in PHP and nobody wants to work with that

**Comment by SpaceManiac** [comment]
This is the correct solution, though I think the `fexists()` check can be skipped since `fdel()` will simply return `0` rather than crashing on failure.

I accidentally broke things with this change in #38837, forgetting that `text2file` appends:
https://github.com/tgstation/tgstation/pull/38837/files#diff-1ed4f8fbfc0260cba68c35003422e2ceL228

**Review by Cyberboss — CHANGES_REQUESTED** [review]
Just fdel, also the `to_chat(world` seems noisy

**Comment by JohnGinnane** [comment]
thank you for this

**Pull request merged**
