### PR TITLE
Tweaks paramedic loadout

### PR DESCRIPTION
**Pull request by Mickyan**
Moved the pinpointer to the medical belt and the medical pen to suit storage

Just a few tweaks to avoid always having to shuffle your items at roundstart since both pinpointer and medipen have limited use, and I think we should generally avoid using pocket slots for starting loadouts if possible.
## Changelog
:cl:
tweak: Tweaked paramedic loadout, moved pinpointer to medical belt, moved medipen to suit storage
/:cl:

### CODE REVIEW

**Comment by nemvar** [comment]
paramedics aren't surgeons. chembag seems more appropriate.

**Comment by Mickyan** [comment]
paramedics aren't doctors, they shouldn't be carrying medicine

or piles of rotten organs to do impromptu ghetto surgery, apparently?

**Comment by Mickyan** [comment]
I decided to remove biobags after all, I might add something specific and more appropriate for paramedics later

**Comment by improvedname** [comment]
give them a special rollerbed pocket clip idk

**Pull request merged**
