### PR TITLE
directional recyclers

### PR DESCRIPTION
**Pull request by Vincent983**
## About The Pull Request
the recycler has sprites when facing any direction aside from west, also you can now actually rotate it ingame.
## Why It's Good For The Game

It's strange how this machine that is dependent on directions can't be rotated.
## Changelog
:cl:
qol: the recycler can now be rotated
/:cl:

### CODE REVIEW

**Comment by Vincent983** [comment]
hold on I need to remap the stuffs

**Comment by Vincent983** [comment]
image
image
image
image

**Comment by Vincent983** [comment]
side sprite is the same, east direction is just it but flipped

**Comment by Vincent983** [comment]
for some reason, they're unable to face west in the map editor now? wat

**Comment by ZephyrTFA** [comment]
I'd like to see a video of the directional recyclers being used in game.

**Comment by Vincent983** [comment]
sure, lemme do that

**Comment by Vincent983** [comment]
https://github.com/tgstation/tgstation/assets/124026007/bd392e57-41e7-49a0-a204-bf4bd6f3d640

how was this 14 mb before compression, i have no clue

**Comment by mc-oofert** [comment]
the animation for the blades or whatever facing south and west looks really silly

**Comment by Vincent983** [comment]
im not good at spriting

**Comment by san7890** [comment]
image

you only have south-facing sprites committed, did you not stage the changes to the icon file?

**Comment by Vincent983** [comment]
downloaded the icon files from the branch, looked at them, they definitely have all directional sprites

**Comment by san7890** [comment]
hm probably just it shitting the bed then. odd though

**Pull request merged**
