### PR TITLE
Makes some improvements to mood code

### LINKED ISSUE #39578: Moodlet duration doesn't refresh while it's still active
Example: 
The moodlet for slipping has a 3 minutes duration
You slip at 0:00
You slip again at 2:30
Moodlet goes away at 3:00

@Qustinnus

### PR DESCRIPTION
**Pull request by ghost**
:cl: Floyd / Qustinnus
code: removes useless mood events subtypes
fix: fixes mood event timers not resetting when they get triggered again
remove: removes the depression overlay which makes our fruit happy
/:cl:

fixes #39578

### CODE REVIEW

**Comment by epicmemename** [comment]
misleading title, if you wanted to fix mood you'd just revert it

**Comment by Qustinnus** [comment]
the title doesn't have fix in it but good attempt nonetheless

**Comment by SpaceManiac** [comment]
Merge conflict

**Comment by Qustinnus** [comment]
@SpaceManiac resolved

**Comment by SpaceManiac** [comment]
```
code/datums/components/mood.dm:239:error: /datum/mood_event/nutrition/fat: undefined type path
code/datums/components/mood.dm:241:error: /datum/mood_event/nutrition/wellfed: undefined type path
code/datums/components/mood.dm:243:error: /datum/mood_event/nutrition/fed: undefined type path
code/datums/components/mood.dm:247:error: /datum/mood_event/nutrition/hungry: undefined type path
code/datums/components/mood.dm:249:error: /datum/mood_event/nutrition/starving: undefined type path
```

**Review by SpaceManiac — CHANGES_REQUESTED** [review]
compile errors

**Review by SpaceManiac — APPROVED** [review]

**Pull request merged**
