### PR TITLE
Adds a series of new laws and boards

### PR DESCRIPTION
**Pull request by Dorsisdwarf**
Redo because ew mergeconflicts

:cl:
rscadd: Adds Robo-Doctor board (The Hippocratic Oath: Now on your beepbot)
rscadd: Adds Reporter board (The truth will set ye free (termsandconditionsmayapply))
rscadd: Adds Live and Let Live board
rscadd: Adds Thermodynamics as a dangerous board.
/:cl:

### CODE REVIEW

**Comment by AnturK** [comment]
Maybe it's time to make the lawboards a weighted spawner. If you feel like it.

**Comment by AlexanderUlanH** [comment]
Hippocratic oath laws actually seem pretty cool. AI-Patient confidentiality would spice things up a bit.

**Comment by Buggy123** [comment]
Law 3 on the Mother Drone lawset seems kind of unnecessary. Also, are slaved borgs considered drones? Maybe we should add something about that.

Also the fact that the AI can't communicate with drones makes using that lawset a bit harder.

**Comment by Dorsisdwarf** [comment]
Slaved borgs must be drones, because their laws say so too, right? 

(Drones can hear binary)

**Comment by Aloraydrel** [comment]
>wontbefunnyinsixmonths
What are you implying

**Comment by YotaXP** [comment]
I love these laws, but I'm not smart enough to understand the Thermodynamics one.  Is it simply "kill everyone"?

Also, why are there no boards for Station Efficiency and Peacekeeper?

**Comment by PKPenguin321** [comment]
>I love these laws, but I'm not smart enough to understand the Thermodynamics one. Is it simply "kill everyone"?

ye

**Comment by YotaXP** [comment]
So, are actual drones allowed to interact with such silicons?  Is it possible to make the drone's static overlay thingy show for the silicons, and make the static over borgs go away for drones if they have this lawset?

**Comment by Dorsisdwarf** [comment]
Yes. You would go about it by making the drone staticvision check for a "Dronevisible" var or something, and have applying the lawboard set it to true for all silicons synced to the AI it was applied to. Then you'd make the default lawboard (and hence all its children other than MotherDrone) remove this variable.

I'm not doing that because it touches too much stuff and is the sort of thing that'll drag this PR down again.

**Pull request merged**
