### PR TITLE
Fixes an oversight with EVA helmets having no FOV despite blocking pepperspray and hiding your identity.

### PR DESCRIPTION
**Pull request by Iamgoofball**
## About The Pull Request

Fixes an oversight with EVA helmets having no FOV despite blocking pepperspray and hiding your identity.

## Why It's Good For The Game

Discord_p4MEgJG8OU
Discord_0xhGl7sh99

i see all, players, nice try
## Changelog

:cl:
balance: Fixes an oversight with EVA helmets having no FOV despite blocking pepperspray and hiding your identity.
/:cl:

### CODE REVIEW

**Comment by SmArtKar** [comment]
изображение
pretend this says EVA instead of projectiles. This is not a fix, its a massive balance change and you are once more mistagging your PRs

**Comment by Iamgoofball** [comment]
anything with identity protection + pepperspray protection is supposed to have FOV

**Comment by Astrogem2** [comment]
If this IS going to go through, can we please have it turned off on non station z-levels, this would kill all space exploration.

**Comment by Iamgoofball** [comment]
it's a grand total of like, 5 tiles you can't see on screem, how does it kill space exploration

**Comment by SimplySmiley123** [comment]
> it's a grand total of like, 5 tiles you can't see on screem, how does it kill space exploration

It's annoying as shit.
Enough of a reason for someone who's not using the EVA helmet for pepperspray immunity (barely anyone cares about that anyway) or hiding their identity to dislike this.

**Comment by SargesC** [comment]
why not make eva helmets show your face doesnt it have a big visor

**Comment by SomeoneYouProbablyKnow** [comment]
I see a people using a cool items
"wow they look stylish, i love it when players use weird items as a form of self expression"
Turns out the item has a minor powergaming benefit and that's the only reason it's used

How are players so lame

**Comment by Deultus** [comment]
> anything with identity protection + pepperspray protection is supposed to have FOV

I am waiting for a PR "FOV for all costume mods, heretical robes and the like" from you, as I hope that you are consistent in your judgments

**Comment by Exester509** [comment]
Look mom I'm on the photo

**Comment by Exester509** [comment]
> it's a grand total of like, 5 tiles you can't see on screem, how does it kill space exploration

You could say the same about mining and yet, a different approach was taken with their mask

**Comment by CCC23** [comment]
New PR pepperspray now gibs if it hits you gas masks cause massive oxy damage while they are on

**Comment by CCC23** [comment]
> it's a grand total of like, 5 tiles you can't see on screem, how does it kill space exploration

same way it killed anyone wanting to use gas masks

**Comment by btcbuster** [comment]
Security gas masks?

**Comment by btcbuster** [comment]
I do not feel this is a good change, EVA helmets may block pepperspray and identity, but it takes the helmet slot. If you really are worried about this issue, look at the welding gas mask.

**Comment by SomeoneYouProbablyKnow** [comment]
welding gas masks don't exist. 5hey are an rnd item, only like 4 giganerds use em routinely

**Comment by DrDiasyl** [comment]
Adding FOV for pepperspraying protection was a bad idea anyway, no one abused pepperspray that much not protect their face that often for FOV to be constituted.
Everything FOV ever did was kill the classic greytider style bearing a gas mask.

Just get rid of the FOV already for spess sake.

**Comment by SomeoneYouProbablyKnow** [comment]
Pepper spray itself is a shit mechanic, no reason why it's a core security item except inertia.

**Comment by DrDiasyl** [comment]
> Pepper spray itself is a shit mechanic, no reason why it's a core security item except inertia.

Pepperspray is a-okay just like flash, has it uses in very niche situations like a desworder boner

**Comment by SomeoneYouProbablyKnow** [comment]
Flash is also shit but borgs are ubiquotous. Honestly a desword boner (without stolen sec gear giving them pepper protection) isn't enough reason to justify giving everyone pepper spray. It is funny as shit seeing them spray themselves but if the sec kit was being made right now pepper spray wouldn't make the cut is all i'm sayin

**Comment by ATH1909** [comment]
is the opportunity cost of (obtaining and) wearing an EVA helmet instead of something that actually protects your head not enough of a drawback? pepper spray protection is pretty niche, and the head slot is much more contested than the mask slot.

**Pull request closed without merging**
