### PR TITLE
Scrubbers & pAI

### LINKED ISSUE #2847: Spawning a pAI MOB Runtimes
Version is commit:
https://github.com/tgstation/-tg-station/commit/8108cb1b7f2d64532148cad7e6cfdf0e6c341b4d

runtime error: undefined variable /turf/simulated/floor/carpet/var/radio
proc name: New (/mob/living/silicon/pai/New)
  source file: pai.dm,62
  usr: the pAI (/mob/living/silicon/pai)
  src: the pAI (/mob/living/silicon/pai)
  call stack:
the pAI (/mob/living/silicon/pai): New(Carpet (121,181,1) (/turf/simulated/floor/carpet))
CrimsonVision (/client): Spawn("pAI")

The Mob want's something that has a radio var, which means you can't summon it, Not sure if this even needs fixing but I know we hate runtimes and we don't want someone accidentally spawning this thinking it's the real deal and getting a runtime live on the servers

(sorry about the formatting, I'm busy and just wanted to get the runtime up)

### LINKED ISSUE #10770: Tanks can be placed into stationary scrubbers, but not removed.
While portable scrubbers have a UI option to remove tanks placed in them, the huge air scrubber of toxins storage doesn't have an interactable UI.

### PR DESCRIPTION
**Pull request by phil235**
Fixes not being able to spawn a pai manually. Fixes #2847.
Fixes not being able to remove your inserted tank from a huge scrubber by removing the ability to insert a tank inside a huge scrubber. Fixes #10770.

### CODE REVIEW

**Comment by Supermichael777** [comment]
B-b-but my scrubber bombs! actually aren't these remotely activate-able could a bomb or bomb like object be made?

**Comment by Aranclanos** [comment]
looks good.

**Comment by phil235** [comment]
@Supermichael777 No, the only thing you can do with a huge scubber is turn it off/on, there's no valve to open or anything. Plus I don't think huge scrubbers were ever intended to receive tanks, the portable scrubber have a special overlay when a tank is inserted but huge scrubber don't.

**Comment by Fayrik** [comment]
Why could you even add tanks to large scrubbers in the first place?
Was it just an inheritance issue?

**Comment by phil235** [comment]
@Fayrik  yep

**Pull request merged**
