### PR TITLE
Capped poly's speak_chance

### PR DESCRIPTION
**Pull request by Buggy123**

### CODE REVIEW

**Comment by PKPenguin321** [comment]
Fun removal

**Comment by Buggy123** [comment]
It just prevents the var getting ridicuolously large, values over 100 were pointless anyway.

Trust me I wanna leave it as-is but if we implement this 'nerf' maybe no one will decide to REALLY nerf it.

**Comment by Incoming5643** [comment]
Doesn't actually do anything, this goes into a prob check and any prob of over a 100 has the same effect as prob(100): always returns 1

**Comment by Buggy123** [comment]
Shhhh.

**Comment by KorPhaeron** [comment]
>Doesn't actually do anything, this goes into a prob check and any prob of over a 100 has the same effect as prob(100): always returns 1

**Pull request closed without merging**
