### PR TITLE
Ports a modified Fire Extinguisher Sprite from Tau Ceti

### PR DESCRIPTION
**Pull request by Imaginos16**
## About The Pull Request
It adds sprites heavily based on the PR: [New fire extinguisher sprites#4664](https://github.com/TauCetiStation/TauCetiClassic/pull/4664) from Tau Ceti!

Editor's Note: Previous reviews were regarding the original version of the PR, when it was originally a straight up port of them.

I would also like to include special thanks to @Mey-Ha-Zah for refining the mini fire extinguisher sprites!

Image:
image

## Why It's Good For The Game
I feel as though its much more refined than its previous counterparts!

## Changelog
:cl: PositiveEntropy, Meyhazah
imageadd: Adds new fire extinguisher sprites based on Tau Ceti's!
/:cl:

### CODE REVIEW

**Comment by maxymax13** [comment]
too shiny and the pocket one looks bad, looks more like jumbo sized incendiary nades than extinguishers which are usually painted in dull bright red, not Valve HL1 GoldSrc Crowbar Red Chrome Texture™

**Comment by SkeletalElite** [comment]
The regular extinguishers are fine but the emergency ones are small

**Comment by AndroidMK2** [comment]
Quite not fitting everything else i gotta say, especially the emergency extinguisher.

**Comment by Imaginos16** [comment]
Updated the sprites, will change description and update photo.

**Pull request merged**
