### PR TITLE
Removes xeno queen maid

### PR DESCRIPTION
**Pull request by lzimann**
:cl:
del: Xeno queens can no longer be maids
/:cl:

This is just streching the limit, without good reasons to even exist. 
This was only for byond members so you probably rarely saw it and we have quite a few byond member benefits already.

### CODE REVIEW

**Comment by VeryRealAccount** [comment]
no fun allowed

**Comment by lzimann** [comment]
I don't see how this is fun in any way, but ok, we can go with that.

**Comment by WJohn** [comment]
@KorPhaeron your call, since you want to keep REGULAR xeno maids.

**Comment by lzimann** [comment]
He literally said in the other pr to remove this.

**Comment by Tacolizard** [comment]
i want to be able to pay money on patreon to get this. 👎

**Comment by xxalpha** [comment]
What is this xenophobe shit

**Comment by WJohn** [comment]
Are you oppressing my right to roleplay as a xeno queen maid?

**Comment by InsaneHyena** [comment]
No degeneracy.

**Comment by Pascal125** [comment]
Why?

**Comment by BeeSting12** [comment]
don't you need a changelog and a reason for removal

**Comment by lzimann** [comment]
ill do later

**Comment by DoctoreMad** [comment]
>don't you need a changelog and a reason for removal

>ill do later

lol

**Comment by lzimann** [comment]
When you stop to think, needing an extra reason to remove such thing besides the actual removal is really sad.

**Comment by Tacolizard** [comment]
Sad!!

**Comment by PKPenguin321** [comment]
This one shoulda gone through

**Comment by lzimann** [comment]
too bad, now you lost patting instead

**Comment by optimumtact** [comment]
merging the original maid pr was my only mistake

**Comment by lzimann** [comment]
Joan keeps ignoring me on this, so I'll just reopen until I get at least an answer.

**Comment by Anonymous583** [comment]
close it again loser

**Comment by Militaires** [comment]
image

**Comment by Militaires** [comment]
also why did "veryrealaccount" and "praiseratvar" thumb this down lol

**Comment by PKPenguin321** [comment]
>praiseratvar

joan...

**Comment by AnturK** [comment]
I literally never seen this used. Just ask admins for varedit if you have legitimate need for maid queen.

**Comment by GunHog** [comment]
> I literally never seen this used. Just ask admins for varedit if you have legitimate need for maid queen.

I saw it used two-three days ago in a round where something may have TC traded for a Xeno. She was grown in Xenobio, and released when someone sent the SM into full Tesla mode. 

Also, you cannot varedit this that easily, because you removed not only the proc, but the sprite from the DMI as well, which I do not believe can be referenced during an icon update (resting, dead, etc).

**Comment by RemieRichards** [comment]
@GunHog it's actually quite easy.
All of the sprites are:
"alien[caste]_sleep" "alien[caste]_leap" etc.

you just set the alien's icon to a custom dmi containing named states, and set their caste to like, "maid" (and use "maid" in the icon state names, eg: a dmi containing: "alienmaid_leap", "alienmaid_sleep" etc.)

**Comment by xxalpha** [comment]
>19 thumbs down vs 12 thumbs up
>still merged

leoz does it again

**Comment by Spacedong** [comment]
fuck faggots, remove furries, god bless goof

**Pull request merged**
