### PR TITLE
Latejoining crew start with emergency large crowbars if arrivals is not powered

### PR DESCRIPTION
**Pull request by mc-oofert**
## About The Pull Request

If you latejoin, and arrivals environmental power is off (airlocks depowered), you start with an emergency large crowbar in your hands (or floor if both hands are full already)

## Why It's Good For The Game

Some arrival shuttles start with a crowbar, but its not enough if someone already took it before you arrived.
Being stuck in airlock + firelock CBT especially with no air is very shit (unless youre the CE or an Engineer who start with tools, unlikely)
Having a crowbar resolves movement

## Changelog
:cl:
qol: Latejoining crew start with crowbars if arrivals enviromental power is OFF
/:cl:

### CODE REVIEW

**Comment by necromanceranne** [comment]
Did you test it? Did you test it while a plasmaman?

**Comment by mc-oofert** [comment]
> Did you test it? Did you test it while a plasmaman?

well it works as a human and i dont see a reason it wouldnt work as a plasmaman

**Comment by Likteer** [comment]
They meant that plasmamen already spawn holding their internals tank.

**Comment by mc-oofert** [comment]
> They meant that plasmamen already spawn holding their internals tank.

they have two hands

**Comment by NamelessFairy** [comment]
> > They meant that plasmamen already spawn holding their internals tank.
> 
> they have two hands and the crowbar is onehanded

There are a few situations where people should spawn with an item in both hands, such as a plasmaman medical doctor who gets an item from their job and species, dullahans and cargo technicians also experience this. The birthday station trait will also place some items in peoples hands when they spawn but has some checks incase both hands are occupied. It would be worth ensuring that no issues occur if someone is a job/species/station trait combination where both of their hands would be occupied.

**Comment by mc-oofert** [comment]
> There are a few situations where people should spawn with an item in both hands, such as a plasmaman medical doctor who gets an item from their job and species, dullahans and cargo technicians also experience this. The birthday station trait will also place some items in peoples hands when they spawn but has some checks incase both hands are occupied. It would be worth ensuring that no issues occur if someone is a job/species/station trait combination where both of their hands would be occupied.

at best i can just make it spawn on the floor if both hands are occupied because the large crowbar is bulky

**Comment by jughu** [comment]
add a crowbar dispenser to the shuttle :)

**Comment by mc-oofert** [comment]
> add a crowbar dispenser to the shuttle :)

adding a dispenser would just make it unused by anyone that doesnt know it exists

**Pull request merged**
