### PR TITLE
makes the medical hardsuit faster

### PR DESCRIPTION
**Pull request by Fikou**
## About The Pull Request
Changes the medical hardsuit's slowdown from 1 to 0.5

## Why It's Good For The Game
Medical hardsuit is the worst one, doesnt even have any flash protection, doesnt have any cool protection thing like sci bomb protection or atmos fireproofness, its description says that its made of lightweight materials to allow easier movement too, and also if you want to save someones life you probably would like to do it as fast as possible and not go in a slow hardsuit

## Changelog
:cl:
balance: Medical Hardsuit is faster
/:cl:

### CODE REVIEW

**Comment by Tlaltecuhtli** [comment]
maybe give it a custom slowdown?

**Comment by Fikou** [comment]
i dont know if you can do something like slowdown=0.5 so i just havent tried

**Comment by yoyobatty** [comment]
Slowdown 0.5 works, it's only slightly slower than running

**Comment by Fikou** [comment]
ok this should work

**Comment by WJohn** [comment]
yay my slowdown analysis is actually getting used

**Comment by knacker48** [comment]
You know how the science bomb hardsuit has a reagent scanner that you can toggle on and off? Could the medical hardsuit have a built in medical scanner?

**Comment by Fikou** [comment]
> You know how the science bomb hardsuit has a reagent scanner that you can toggle on and off? Could the medical hardsuit have a built in medical scanner?

im pretty sure sci hardsuit has the yellow hud about borgs, nanites and shocked doors, and med hardsuit has reagent scanner

**Comment by 81Denton** [comment]
Medical scanner wouldn't be terribly useful since CMO starts with the medHUD implant, but something like an integrated surgery toolset would be pretty great

**Comment by HomocidlePancakes** [comment]
>0 pressure enviroment
Surgery

**Comment by 81Denton** [comment]
only with that attitude

**Comment by ExcessiveUseOfCobblestone** [comment]
I don't want roundstart items to forgo getting things like the surgery implant though.

**Comment by Shapsy** [comment]
Surgery tools would be the wackest thing I could possibly imagine putting in a space suit.

**Comment by knacker48** [comment]
What about a crew pinpointer? Would that be too much?

**Comment by RaveRadbury** [comment]
I don't get why the medical hardsuit doesn't have more fire+acid protection given that the basic chemist jumpsuit gives 50/65 compared to the hardsuit's 75/75. The RD hardsuit gets 60/80 WITH 100 Bomb.

Maybe buff those armor categories?

**Comment by ATH1909** [comment]
With regards to HUDs, the medical hardsuit should at least give you the data that science goggles normally give you (because let's face it: they're not science goggles, they're chemistry goggles).

But yeah, I like this change. Maybe make handheld suit sensor monitors and pinpointers fit in the exosuit slot of the medical hardsuit as well?

**Comment by Shapsy** [comment]
Why would you waste your exosuit slot that can hold bulky items on an item that can fit in your pocket

**Comment by Barhandar** [comment]
Having medihud in this wouldn't be helpful for (competent) medbay, but it would be helpful for everyone else who'd take the hardsuit.

**Pull request merged**
