### PR TITLE
simplifies fingerprints code to remove a million useless procs and stop creation / deletion of useless extra components

### PR DESCRIPTION
**Pull request by tmtmtl30**
## About The Pull Request

in essence: every time fingerprints were added to an object it instantiated a new forensics component, attached it to the object, did nothing to it, immediately deleted it, and then added the fingerprints to the old forensics component (unless there was no old component, in which case it acted like you'd expect). this was stupid as shit, so i fixed it. (also simplifies code for ghosts viewing storage items)

## Why It's Good For The Game

shitcode is bad

## Changelog
:cl:
refactor: forensics components are no longer instantiated and thrown away immediately every time they're modified. ghost storage item viewing code has been simplified. these (should) have no gameplay effect
/:cl:

### CODE REVIEW

**Comment by silicons** [comment]
hi i'd very much recommend it be considered to just toss forensics datum components entirely
when i made it the idea was you can eventually do stuff relating to component signals like being able to clean off fingerprints or something
but so far no one's ever used that and it's just extra overhead for what i thought was a good reason but in reality is not that much of a good reason not to mention making checking for

**Comment by tmtmtl30** [comment]
what would you recommend? a lazy associative list of lazy (associative) lists?

**Comment by silicons** [comment]
@tmtmtl30 the system before i did forensics components was just 3 lazy lists and fingerprintslast being a datum (like it is now i believe), yea

**Comment by silicons** [comment]
nested lists don't necessarily offer better performance + memory savings, pretty sure it's better in this case to not do that.

**Comment by AnturK** [comment]
Conflicts.

**Pull request closed without merging**
