### PR TITLE
Removes left inhand files, automatically mirrors inhands

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
Inhands are now automatically mirrored, so you only need one set of inhands (right hand). Two lines of matrix code lets us throw out over three thousand extra icons and will save spriters a ton of tedious busy work.

:cl: Kor
imagedel: Deleted all (3000+) left handed inhand icons. They are now automatically mirrored from the right hand, saving spriters a lot of tedious busywork.
/:cl:

### CODE REVIEW

**Comment by ShadowDeath6** [comment]
Nice x :100:

**Comment by Ausops** [comment]
aah kor-sama

**Comment by PKPenguin321** [comment]
holy fuck i was just theorycrafting about doing this a while back. you're a god

**Comment by TechnoAlchemisto** [comment]
Good boy

**Comment by Mervill** [comment]
The matrix is all ... whoa!!

**Comment by Thunder12345** [comment]
Halves the chance of misaligning an inhand :+1: x :100:

**Comment by utahclock** [comment]
Awesome

**Pull request merged**
