### PR TITLE
Kinetic Accelerator description condensation.

### PR DESCRIPTION
**Pull request by TechnoAlchemisto**
Gets rid of the huge paragraph while keeping the essential information.

### CODE REVIEW

**Comment by Bawhoppen** [comment]
>rifle

**Comment by Jordie0608** [comment]
Rifling is like an inverse drill

**Comment by coiax** [comment]
Jeez, why do people hate useful information

**Comment by Cheridan** [comment]
it doesn't mention the recharging mechanic at all. what's wrong with a big DEEP LORE description?

**Comment by PKPenguin321** [comment]
>useful information
>>According to Nanotrasen accounting, this is mining equipment.

**Comment by yackemflam** [comment]
OH
SO YOU GO OFF AND DELETE MINE
MINE THAT HAS A SENSIBLE JOKE THAT I DON'T TAKE CREDIT FOR. (All credit goes to https://github.com/tgstation/tgstation/issues/18610)
https://github.com/tgstation/tgstation/pull/18702

**Comment by optimumtact** [comment]
I don't know why you even did this

**Pull request closed without merging**
