### PR TITLE
Hemostat/cautery steps now heal their targetted bodypart instead of a random one

### LINKED ISSUE #48432: Any surgery step that heals damage dealt during surgery heals whatever limb was last damaged.
sigh, lets try this again

During any step, ie: clamping bleeders, ending the surgery via cautery, etc, that causes healing, if any brute damage is sustained after the damage but before the healing step, the damage last taken will be healed.

How to reproduce: punch somebody in the face and then clamp their bleeders or cauterize their surgery and watch as magically their chest is still sawn open but their face is good as new.

### PR DESCRIPTION
**Pull request by strandsofivy**
## About The Pull Request

Title summarizes all.
## Why It's Good For The Game

Fixes #48432 
@Sealed101 
## Changelog
:cl: distributivgesetz
fix: Clamping/closing a wound should now heal the bodypart that was damaged instead of a random one.
/:cl:

### CODE REVIEW

**Comment by iamcooldan** [comment]
Personally working in medbay I would not be a fan of this, as tend wounds is the major surgery and having to constantly change body part targeting to fully revive someone would be extremely tedious and turn some people off the role.

**Comment by distributivgesetz** [comment]
> Personally working in medbay I would not be a fan of this, as tend wounds is the major surgery and having to constantly change body part targeting to fully revive someone would be extremely tedious and turn some people off the role.

PR doesn't touch tend wounds at all, only the healing that happens after you hemostat/cautery in a surgery where you sawed once like organ manipulation

**Comment by iamcooldan** [comment]
alright then, guess I misinterpreted this.

**Comment by EricZilla** [comment]
Is this why sometimes people randomly still bleed after surgery holy shit

**Comment by distributivgesetz** [comment]
> Is this why sometimes people randomly still bleed after surgery holy shit

nop

**Pull request merged**
