### PR TITLE
Update PDA sprites to better resemble real ones

### PR DESCRIPTION
**Pull request by EricZilla**
## About The Pull Request

I've always been somewhat bothered by how the PDAs looked so I decided to take it into my own hands, as I understand it this is still allowed during the feature freeze, and trust me you dont want me typing code into your game, I promise.
OLD PDAS:
sold
NEW PDAS:
science BIG
I have also added a bit of white to the head PDA pattern so that the CE's PDA isnt just weirdly extra yellow for no reason, and made the thin stripes a little thicker too. The curator and clown PDAs are untouched because the clown PDA being an older and worse model is funny, and the curator PDA is a special model anyway, and I want to preserve both of their identities as being weird old PDAs

I would really love if this got a test merge or something to see how people feel about changing up PDAs

## Why It's Good For The Game

PDAs have always been weirdly huge and clunky, smalling them up gently like this will be more realistic, and make the other larger options stand out more, such as the tablet. I also think, showing people its not that hard to work with a post GAGS sprite is an important step even if its not merged, its really easy to work with.

## Changelog
:cl:
imageadd: Centcom finally sent us new PDAs, except for the clown. Suffer.
/:cl:

### CODE REVIEW

**Comment by EricZilla** [comment]
These arent the final sprites but this is pretty close to how the final set look in game and I was too lazy to set them all up in a row again:

PDA presentation

**Comment by tralezab** [comment]
### a soulful sprite pr, fellas?

image

**Comment by ZephyrTFA** [comment]
You might want to actually push your branch bud

**Comment by EricZilla** [comment]
AW fuck

**Comment by EricZilla** [comment]
unfuck

**Comment by Mothblocks** [comment]
hahaaaha dude

**Comment by EricZilla** [comment]
I'm not even sure what went wrong but I'm gonna try again

**Comment by Mothblocks** [comment]
just push to the same branch u dont need to delete it

**Comment by ZephyrTFA** [comment]
if it won't let you push for some reason; force push it (use --force)

**Pull request closed without merging**
