### PR TITLE
tgui v4.4: More performance improvements

### PR DESCRIPTION
**Pull request by jlsnow301**
## About The Pull Request
Consider this a much more intensive version of #79916. We're pretty limited by the speed of babel-loader, and this PR would completely replace it (with Rust!). Doing so removes the need for a minimizer, but it comes with **drawbacks**.

1. We have to switch to using the node_modules folder
2. IE8 target does not play well, so I'm dropping support (this should affect precisely no one)

<details>
<summary>Test environment / My specs</summary>

intel i7-13700kf 
32GB RAM
windows 11 
intel 660p m.2 SSD
asus 4080 TUF series

</details>

<details>
<summary>Fresh build</summary>

Test steps:

1. Delete `tgui/.yarn/webpack` folder
2. `CTRL SHIFT B`

Results:
fresh

terser averages `25.16s`
swc averages `16.65s` - 33.82% faster

</details>

<details>
<summary>Cached build</summary>

(assuming files are already there, CTRL SHIFT B if not)

1. add a comment to an interface file
2. `CTRL SHIFT B`

Results:
cached

terser averages `9s`
swc averages `2.73s` - 69.65% faster

</details>

The resulting tgui build speed is faster than both #79916 and certainly our current babel/terser solution. 
## Why It's Good For The Game
Improved build speed, faster dev tools
## Changelog
N/A nothing player facing

### CODE REVIEW

**Comment by MrStonedOne** [comment]
this branch uses 2.2gb peak memory usage to clean compile the tgui target.

the `npm-updates` branch used 1.8gb peak memory usage to clean compile the tgui target, and spent much less time at peak. This mostly matches with that the servers normally expect

the `esbuild-plugin` branch used 0.9gb peak memory usage to clean compile the tgui target.

Memory usage in prod matters because we almost always have some reason why page/swap/vertical ram has to be disabled, from both k8s and zfs hating it on linux to windows being stupid with it to byond's memory access patterns not meshing well with it to just pure disk iops budget concerns.

Food for thoughts.

**Comment by jlsnow301** [comment]
> Food for thoughts. 

If we used esbuild instead (which I'm not against), I'd like to still remove ie8 support from the esbuild branch, similar to this. It might even run faster as a result. Any objections to this?

**Comment by stylemistake** [comment]
I have no objections to remove IE8 support and fully target IE11.

Regarding node_modules: esbuild supports yarn pnp natively, https://github.com/evanw/esbuild/pull/2451. 

Inferno only has a plugin for Babel, so I see no other option but to keep it just for transforming JSX, and esbuild would do the rest.

**Comment by optimumtact** [comment]
Memory is already under pressure when there are like 5 keyholders inactive accounts logged in.

**Comment by jlsnow301** [comment]
> Regarding node_modules: esbuild supports yarn pnp natively, [evanw/esbuild#2451](https://github.com/evanw/esbuild/pull/2451).

I wonder if the higher memory usage is because we have to use the default node modules folder vs yarn's package management system. It doesn't make sense to me that swc would have higher memory usage than esbuild AND babel/terser

**Pull request closed without merging**
