### PR TITLE
Security clothing and armors ported from BeeStation

### PR DESCRIPTION
**Pull request by Rohesie**
## About The Pull Request

Takes some soul away from security. Replaces it with bees.

## Changelog
:cl:
imageadd: Ported security-related clothings from BeeStation.
/:cl:

### CODE REVIEW

**Comment by cacogen** [comment]
I like choices. No one's going to go for these as replacements. Sec has a clothing vendor. Why not add them to that as an alternative? You could add the alternative detective's vest to his (admittedly already stuffed) locker.

**Comment by ArcaneMusic** [comment]
> I like choices. No one's going to go for these as replacements. Sec has a clothing vendor. Why not add them to that as an alternative? You could add the alternative detective's vest to his (admittedly already stuffed) locker.

Better yet, Alt styles, like with gray jumpsuits or with labcoats.

**Comment by Rohesie** [comment]
There are white sec uniforms and other stuff for extra options if wanted, in this same style.
In this PR I was just replacing what exists in both codebases with their smoother counterpart, but sure, I could add more.

**Comment by AWalton** [comment]
Please add the helmet and red jumpsuit sprites from [here](https://github.com/BeeStation/BeeStation-Hornet/pull/487) if you haven't already, though the rest of the sprites in that PR are also great.

**Comment by necromanceranne** [comment]
These with those additional sprites look modern and sleek. I like it a lot.

**Comment by itseasytosee** [comment]
Pics please? i don't feel like downloading your whole repo

**Comment by CPTANT** [comment]
useless without pics

**Comment by Rohesie** [comment]
@itseasytosee and @CPTANT : Do checks > IconDiffbot > Diffs - Pull Request #48804
No need to download it to see the exact sprite changes.

**Comment by Rohesie** [comment]
Added the on-mob helmets as well, @AWalton , and could add the improved civilian ones, plus adding the new white and tan options for security members to sec vendors, but first we should get the green light from a maintainer, else it's wasted time and work.

**Comment by optimumtact** [comment]
no bikeshed

**Comment by optimumtact** [comment]
you better not be thinking about adding these as alternates either I'll start blasting

**Comment by Rohesie** [comment]
Some of these sprites haven't been updated since forever. The armor vest has at least six years, it's the same we had from old Bay in TGMC. What's bikeshed about it?

**Comment by optimumtact** [comment]
security sprites have changed like four times in the last two years and not a single other JOB has been touched.

I wont' allow it, sec sprite freeze begins NOW.

**Comment by AWalton** [comment]
Cringe

**Comment by Tharcoonvagh** [comment]
Haha

**Pull request closed without merging**
