### PR TITLE
Boss of this Fitness Room

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
Niknak tried to remove the reference, so we must make it stronger

### CODE REVIEW

**Review by Iamgoofball — APPROVED** [review]
ccc
bbb
community_image_1430104039
aaa

**Comment by TechnoAlchemisto** [comment]
t-thanks aniki

**Comment by Aloraydrel** [comment]
What's the lore behind this deep dark fantasy?

**Comment by Bill-Luxe** [comment]
*Gachigasm*

**Comment by Cheridan** [comment]
>iamgoofball hates anything lewd or suggestive
>UNLESS ITS GAY PORN
>GAY PORN IS TOTALLY FINE

**Comment by TechnoAlchemisto** [comment]
nothing wrong with a couple dudes wrestling

**Comment by Iamgoofball** [comment]
^

**Comment by KorPhaeron** [comment]
It's _ironic_ gay porn

**Comment by PKPenguin321** [comment]
no homo

**Comment by Iamgoofball** [comment]
@KorPhaeron p. much

**Pull request merged**
