### PR TITLE
Removes Freon preset gas filters from all maps

### PR DESCRIPTION
**Pull request by ACCount12**
RIP Freon.

### CODE REVIEW

**Comment by MoreRobustThanYou** [comment]
F.

**Comment by Celau** [comment]
bring back brown gas
also, should probably remove blue glitter

**Review by ShizCalev — APPROVED** [review]

**Comment by Bawhoppen** [comment]
@Celau Or better idea, we could add a new gas with that sprite

**Comment by nicbn** [comment]
Hyper-noblium already uses freon sprite.

**Pull request merged**
