### PR TITLE
Small clothes addition.

### PR DESCRIPTION
**Pull request by Tokiko1**
Adds blue and red female clothes to the ClothesMate.
Picture:
clothes2

Sprites by me, used the blackskirt one as a base.

### CODE REVIEW

**Comment by Dorsisdwarf** [comment]
:-1: 
Will reduce prevalence of the omnipresent jumpsuit.

**Comment by GunHog** [comment]
Not bad, if a little bland :+1:

**Comment by Thunder12345** [comment]
:+1: Just needs some more details, idea is great though

**Comment by WJohn** [comment]
Yeah I don't like how it removes the prevalence of jumpsuits or how they look quite so bland, but otherwise it's okay.

**Comment by GunHog** [comment]
We have loads of options already, WJ, and none of them have dominated jumpsuits. Players must choose to change and wear them. Our players are lazy, and do not like to go through the hassle of changing their default gear every round, nor will they remember to do so.

This addition will be no exception. Once the hype dies down, they will be as uncommon as every other alternatively dressed person.

**Comment by WJohn** [comment]
Well in that case that still leaves the sprites being low detail, definitely needs more going on.

**Comment by Tokiko1** [comment]
Does this really remove the prevalence of jumpsuits? There's only 1 of each of them at roundstart and cargo needs to order crates for more. As for details, I agree, I'll add some stuff.

**Comment by ExcessiveUseOfCobblestone** [comment]
These aren't slutty at all, why would anyone who plays a female character wear this?

**Comment by Aranclanos** [comment]
up to wj

**Comment by Chocobro** [comment]
shading makes it look a little too similar to the laser-tag armour. try changing it as if there is a light from above. aka shadows on the armpits, wrists and lower hem. maybe thin up the shading on the collar too, just to give it that little bit of detail and erase some laser-tag-ness. skirt looks good, like the pleats.

**Comment by Razharas** [comment]
@WJohn 
This is for you do decide

**Pull request merged**
