### PR TITLE
Fixes bots responding to greetings not mentioning them.

### PR DESCRIPTION
**Pull request by RemieRichards**

### CODE REVIEW

**Comment by freerealestate** [comment]
You can greet bots?

**Comment by RemieRichards** [comment]
@freerealestate this PR refers to Mr_Basil and Mrs_Sybil the IRC Bots in #adminbus and #coderbus, not the ingame bots.

**Comment by freerealestate** [comment]
Damn, my bad.

**Comment by RemieRichards** [comment]
Merging for MSO, this doesn't affect game code.

**Comment by Iamgoofball** [comment]
# woooooowwwwww
what happened to 24 hours nerd??????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????

( :+1: these bots are so annoying oh my god)

**Comment by RemieRichards** [comment]
@Iamgoofball rofl you were there when I ask MSO if I should merge it early.
dingus :P

**Pull request merged**
