### PR TITLE
Clockcult AIs no longer require APC power

### PR DESCRIPTION
**Pull request by ChangelingRain**
:cl: Joan
rscadd: Clockcult AIs have power as long as they are on a Clockwork Floor or next to a Sigil of Transmission. This is in addition to having power under normal conditions.
/:cl:

MILDLY CLUNKY

### CODE REVIEW

**Comment by GunHog** [comment]
Wow, maybe the AI really IS steam powered...Btw, since you are touching AI power code (I feel sorry for you), why not expand your requires_power var to handle things instead of turf checks for carded, consoled, and mech pilot AIs? Good potential for some cleanup!

**Comment by coiax** [comment]
Doesn't this mean you can now drag your clockcult AI to float randomly in space or to another z-level?

**Comment by GunHog** [comment]
I did not think of it that way. While there are many powered places an AI can hide off station, to survive in space, it would have to be carded or a mech pilot - both these things localize most of its abilities...in a card, you have a buffed pAI, and in a mech, it is basically a big borg.

Then again, Steampunk AIs do not get any special powers except SteamChat™ and auto-hacks for its linked borgies. I am now unsure on this one.

**Comment by ChangelingRain** [comment]
I mean, you could, but you don't get that much out of it; it's still just an AI, really.

**Comment by kevinz000** [comment]
/just/ an AI?

**Comment by ChangelingRain** [comment]
yes you can cut the cams and it can't do shit

Ideally converting it would make it use a ratvarian camera sight; ratvar-stuff only+servants, but camera code is dongs, so.

**Comment by Cyberboss** [comment]
Good way to get the AI lynched faster when it can't help the crew at all

**Comment by TechnoAlchemisto** [comment]
I don't think having the AI survive indefinitely anywhere without power is a good idea. They should still have to worry about being in powered locations.

**Comment by ChangelingRain** [comment]
They now only have to worry if they're off clockwork floors/not next to a Sigil of Transmission, which seems... more fair, probably.
I can make this more extreme pretty easily, ie, with it actually consuming sigil power if it needs to, but I'm not sure that'd be needed.

**Comment by GunHog** [comment]
>Ideally converting it would make it use a ratvarian camera sight; ratvar-stuff only+servants, but camera code is dongs, so.

The camera repair and upgrade Malf powers are somewhat close to such an ideal.

**Comment by KingPhilipIII** [comment]
Ratvarian Silicons should see everything as brass. Like how on some servers(Maybe this one Idk) the detective has glasses that make everything black and white. Harmless and fun.

**Comment by coiax** [comment]
We don't have film noir glasses for the detective, but that's a fantastic idea.

**Comment by KingPhilipIII** [comment]
Porting film noir glasses or silicon brass sight?

**Comment by coiax** [comment]
Noir glasses definitely makes me happy. Brass sight would be a little harder, but not impossible. It depends on what @ChangelingRain wants.

**Comment by GunHog** [comment]
The glasses would be a great addition, but mandatory brass sight would not be so fun.

**Comment by KingPhilipIII** [comment]
Maybe make it toggleable I guess. I'd personally love Clockwork Station, but I can see how that would be cumbersome.

**Comment by GunHog** [comment]
You could make it a feature of the Steampunk Xray glasses!

**Comment by KingPhilipIII** [comment]
I'd honestly wear wraith spectacles solely for Clockwork Station 13. 

Maybe the mass hallucination scripture should make it appear as clockwork station. More Ratvar consistent, probably a bitch to code.

**Pull request merged**
