### PR TITLE
Revert "Fixes one hotspot per tile"

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
This broke atmos somehow. Making this PR so I can test merge it/make the game playable while the bug is figured out

### CODE REVIEW

**Comment by Zilenan91** [comment]
A T M O S   C O D E

**Comment by duncathan** [comment]
Testing in-game would indicate that this change is not responsible for the sudden increase in atmos lag

**Comment by KorPhaeron** [comment]
@duncathan 

It was happening every round after the server updated and was the only recent atmos update.

After I test merged this the problem stopped

**Comment by duncathan** [comment]
@KorPhaeron no it didn't. Tkdrg and I tested it. Trust us.

**Pull request closed without merging**
