### PR TITLE
[Deltastation] Access Fixes [Ready for Review]*

### PR DESCRIPTION
**Pull request by BeeSting12**
Don't merge quite yet, atmos solars doesn't take an engineer's ID since it's set to atmos access so I'm gonna fix that in the mornign but can't really think right now.

:cl: BeeSting12
fix: Deltastation's secure tech storage is no longer all access.
/:cl:

Why: Secure tech storage is not intended to be all access.
*and by review i mean merge because who's gonna review all of one line.

### CODE REVIEW

**Comment by QualityVan** [comment]
Engineers can also only access the northeast solars/smes by spacetravel, I'm pretty sure.

**Comment by BeeSting12** [comment]
That is correct, I'm fixing that. I believe Okand37 intended them to be for atmos techs to use, but atmos techs don't even get insulated gloves, so that doesn't really work.

**Comment by QualityVan** [comment]
I thought the atmos ones were northwest?

**Comment by BeeSting12** [comment]
Oh got my directions wrong. Sorry I'll look at that right now

**Comment by BeeSting12** [comment]
All of the solars' airlocks didn't have the external airlock access codes required to use them for some reason. Added those. I made it so that either atmospheric technicians or station engineers can use the NW ones. I tested the NE ones and they should've worked either way.

**Comment by QualityVan** [comment]
Turns out the doors I remembered was a door between the auxiliary construction zone and the NE solars, labeled auxiliary construction storage. You have to pass through it to get to the solars from inside the station as far as I can tell, and engineers don't have access.

**Comment by BeeSting12** [comment]
At some point tonight I'll fix that too @QualityVan 
Just having a severe case of laziness with procrastination symptoms

**Comment by optimumtact** [comment]
Please use [WIP] in the title until your PR is ready

**Comment by BeeSting12** [comment]
Okay, sorry, will do next time.

**Pull request merged**
