### PR TITLE
Replaces space turfs with template_noop turfs in wizard academy

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
Meaning I can plop it down on lavaland or something.

Last I checked the map merger was bugged, if that is no longer the case I'll go back and redo this with the merger.

### CODE REVIEW

**Comment by Zilenan91** [comment]
Since you're doing map edits can you remove the singularities at the beginning too?

**Comment by francinum** [comment]
Yeah those singularities are only used by academy defenders to permanently take players out.

**Comment by optimumtact** [comment]
Isn't that pretty much their job?

**Comment by xxalpha** [comment]
The map merger isn't bugged, but the map loader doesn't support tgm yet so you shouldn't convert this anyways. You can still use the map merger to write the map as a normal dmm.

**Comment by PKPenguin321** [comment]
Noop noop

**Comment by duncathan** [comment]
@KorPhaeron map merger pls

**Comment by KorPhaeron** [comment]
I'll do this later once dunc is done with his stuff

**Pull request closed without merging**
