### PR TITLE
Radio Sounds

### PR DESCRIPTION
**Pull request by DrDiasyl**
## About The Pull Request
Now talking into radio and hearing radio messages produces a sound. Using LOUD-MODE makes a unique sound.

https://github.com/user-attachments/assets/891d9b9a-5313-4aac-9fef-56d0a7286bf1

https://github.com/user-attachments/assets/112a3587-46ea-413e-89e4-2da7b54c3d62

**YOU CAN DISABLE IT IN THE GAME PREFERENCES**
## Why It's Good For The Game
People REALLY tend to miss radio messages, especially from the heads.
This makes it so they can hear when some interesting or important chatter is going on.

Unless all of the heads of staff decide to dispute in the Common, subordinates will start noticing messages from their bosses in their channels more often.

Also, these sounds are tickling my ears, in a good way.
## Changelog
:cl: DrDiasyl aka DrTuxedo
sound: Hearing and talking into the radio now produces a sound. Heads get a special sound.
/:cl:

### CODE REVIEW

**Comment by DrAmazing343** [comment]
Not sure how I feel about the big text sound- a lil high-pitched? BUT I absolutely ADORE the other sounds, they really do tickle the ears.

**Comment by Moltovz** [comment]
I loved this on Eris/Soj, its a good feature. I'd love an option to chose what channels it comes in on though. I ignore common as much as possible, but chosing for sec/med/command to click as cappie would be neat.

**Comment by SmArtKar** [comment]
Should be a preference to be honest, ideally separate ones for normal/loud modes

**Comment by MrMelbert** [comment]
I love radio sounds from other servers but I'm not sold on bigtext having its own sound

**Comment by DrDiasyl** [comment]
> I love radio sounds from other servers but I'm not sold on bigtext having its own sound

Why does big text exist? To make heads of staff messages more distinguishable

So logically they also must have a distinguishable sound

**Comment by Livrah** [comment]
Please make it togglable in preferences

**Comment by Skebulba** [comment]
Can't wait for someone to give a bunch of monkeys Tourette's and then throw them in a pit with some radios and ruin the hearing of everyone playing

**Comment by DrDiasyl** [comment]
> Can't wait for someone to give a bunch of monkeys Tourette's and then throw them in a pit with some radios and ruin the hearing of everyone playing

ban them?

**Comment by atlasle** [comment]
> Can't wait for someone to give a bunch of monkeys Tourette's and then throw them in a pit with some radios and ruin the hearing of everyone playing

just add an option to toggle it in game, like alt-clicking a headset for example (probably should be in a headset's menu too then)

**Review by ShizCalev — CHANGES_REQUESTED** [review]
love it. make it a preference.

**Comment by DrDiasyl** [comment]
@ShizCalev @atlasle @Livrah preferences added you can now toggle it off and on as you please

**Comment by ophaq** [comment]
Cool idea but I really dislike the radio sound for incoming regular ones. When the entire station is talking and it's repeating, it is extremely jarring and annoying. I would disable it, but I do like the outgoing sound when I talk and the head's special sound. If only we could have the incoming regular sound changed to something less distracting/annoying. Something more subtle that can be more easily ignored when 50 people are talking at once.

**Comment by bruhman8ghughug** [comment]
this would work much much better if it was only for departamental radio, most things said in common are irrelevant and on high/medium pop common gets spammed constantly so the radio noise gets really annoying

**Pull request merged**
