### PR TITLE
Shuttles and Centcom now have dynamic lighting

### LINKED ISSUE #25047: The Tomb of the Unknown Employee really shouldn't be directly inside the endgame griff zone
Like, yes, it's kind of in the spirit of the game, but, uh. Kind of disrespectful?

### PR DESCRIPTION
**Pull request by ChangelingRain**
:cl: Joan
rscadd: Shuttles now have dynamic lighting; you can remove the lights on them and use your own lights.
tweak: All maps now use Deltastation's fancy syndicate shuttle.
/:cl:

This SUPER NEEDS testmerging to catch any issues
Fixes #25047
Pictures not included because we have a fuckload of maps sorry
Okay one picture it's of deltastation's syndicate shuttle for reference also this is a map editor pic not ingame

### CODE REVIEW

**Comment by Sligneris** [comment]
Where are the C4 charges? Ops normally get five of these in the hardsuit room.

**Comment by MrStonedOne** [comment]
there is a spawner object by the batteries could be there?

**Comment by MrStonedOne** [comment]
no, the diff says thats a screw driver????

**Comment by ChangelingRain** [comment]
If there's C4 I'll readd it a bit later

**Comment by XDTM** [comment]
Finally! Everlighted shuttles were really odd.

**Comment by PKPenguin321** [comment]
Misleading title and not atomized

**Comment by Shadowlight213** [comment]
How much extra overhead is lighted centcom? It really shouldn't be dynamic lighted since it's not supposed to be used most of the time.

**Comment by ChangelingRain** [comment]
I don't know, but it can't be as bad as lavaland, which is an entire zlevel of dynamic lighting that is always updating a little bit.
Centcom's lighting will update approximately never barring admin shenanigans.

**Comment by MrStonedOne** [comment]
>How much extra overhead is lighted centcom? It really shouldn't be dynamic lighted since it's not supposed to be used most of the time.

Basically unless there are bugs, lighting only updates on changes, and lights ~~wouldn't~~ shouldn't be triggering changes on centcom

**Comment by ChangelingRain** [comment]
oranges has requested that I move the memorial statue so I did that because fuck map conflicts

**Comment by Iamgoofball** [comment]
ATOMIC PRS

**Comment by Iamgoofball** [comment]
But that looks nice

**Comment by Xhuis** [comment]
I got $20 for this

**Pull request merged**
