### PR TITLE
Change the "Who" verb to display a table rather than a list

### PR DESCRIPTION
**Pull request by Mothblocks**
## About The Pull Request
dreamseeker_2020-09-18T22-47-15

Doesn't apply for active admins since those have longer lines that wouldn't fit well.

## Why It's Good For The Game
Easier to quickly parse than a list.

## Changelog
:cl:
add: The "Who" verb now uses a table rather than a list.
/:cl:

### CODE REVIEW

**Comment by Angustmeta** [comment]
Never liked how tables are sorted from left to right instead of top to bottom , bit maybe that's just me.

**Comment by Barhandar** [comment]
Is it going to also display a table with low amount of players, e.g. 14? That would be less readable than a list.

**Comment by Jared-Fogle** [comment]
It's agnostic to player count, though I'm not sure I'd agree it'd be less readable than a list. Adding too many distinctions like that would get in the way of usability if you have to spend a moment to figure out which interpretation you're looking at.

**Comment by ATH1909** [comment]
god yes, thank you

**Pull request merged**
