### PR TITLE
Adds two new holodeck levels

### PR DESCRIPTION
**Pull request by coiax**
- Winter Wonderland
  Apparently no one paid for christmas decorations, and it's
  incredibly cold and low pressure. But it's a good counter
  to a burn mix.
- Anthophila
  "A simulation of a bee colony? Why is this in the restricted
  section?" - Victim of the holodeck bee massacre

Note, the bee one is EXTREMELY lethal. Like, borderline broken. I'm considering nerfing the number of bees, but I kinda want to leave it in just for the fun of it. Even though that would be bad.

### CODE REVIEW

**Comment by swankcookie** [comment]
Keep the bees. keep them.

**Comment by PKPenguin321** [comment]
I remember that NBA jam event in the holodeck that ended with bees and fire

:+1:

**Comment by KazeEspada** [comment]
Use Snow Temperate. Thats survivable and NOT THE FUCKING TEMPERATURE OF HOTH.

**Comment by coiax** [comment]
Actually, it's deliberately designed to be a counter to the plasmafires of death from the holodeck.

**Comment by optimumtact** [comment]
BEEEEEEEEEEEEEEEEEEEEEEEEEEEESSSSSSSSSSSSSS

**Comment by Jazaen** [comment]
I'm coming from the grim dark future where this is merged, and the bees are the most stupidly lethal holodeck module. It is so bad because the darn things can leave, and are really numerous. I suggest cutting the number of bees a bit.

**Comment by coiax** [comment]
> Note, the bee one is EXTREMELY lethal. Like, borderline broken. I'm considering nerfing the number of bees, but I kinda want to leave it in just for the fun of it. Even though that would be bad.

**Comment by Metacide** [comment]
So uh any chance of a nerf of this?

Seems bees get released more or less every shift and are absolutely lethal when they are.

**Pull request merged**
