### PR TITLE
Xenomorph changes and tweaks

### PR DESCRIPTION
**Pull request by GunHog**
:cl: Wjohnston, Gun Hog
add: Aliens with Neurotoxic Spit readied will now have drooling animations.
add: Hunters may now safely leap over lava.
tweak: Hulk punches no longer stun Xenos.
tweak: Alien evolve and promotion buttons updated to current Xeno sprites
bugfix: Handcuff sprites for Xenos now show properly.
/:cl:
- This PR on behalf of @WJohn! All changes to mechanics must be approved by him.
- Sprites by @WJohn!

Note, I cannot make a gif right now, but the drool is **animated** and looks a LOT better ingame.

image

### CODE REVIEW

**Comment by Ultimate-Chimera** [comment]
Make all xenos drool tbh.

**Comment by GunHog** [comment]
Good lord, Chimera, I was not even done editing the OP!

**Comment by Ultimate-Chimera** [comment]
Heh.

**Comment by Ultimate-Chimera** [comment]
But yes, please make all xenos drool, but have the ones with spit active drool acid.

**Comment by GunHog** [comment]
That would require base sprite editing, or a permanent standing overlay. Ask WJ, not me. That is a sprite thing.

**Comment by Ultimate-Chimera** [comment]
Okay.

**Comment by MMMiracles** [comment]
Hulk change is lame, non-queen xenos should fear the green man.

**Comment by PKPenguin321** [comment]
>tweak: Hulk punches no longer stun Xenos.

:-1:

**Comment by WJohn** [comment]
Its a consistency issue. Hulks cannot stun queens/praetorians OR humans, so why on earth can they stun regular xenos who are otherwise immune to literally everything else?

**Comment by MMMiracles** [comment]
I feel like if you can hit with enough force to smash through solid metal you could probably knock down an ordinary xeno. 

Not being able to stun queens/praetorians is balance because a single hulk could easily squash a early hive if they could, that and the fact the queen towers over a hulk visually so they'd probably be a match strength-wise.

**Comment by PKPenguin321** [comment]
hulks not stunning humans was a balance meme but xenos are already so fukken strong that them getting stunned by hulks kinda balances that out (but not queens since we dont want hulks destroying the *entire* xeno nest)

so yeah still :-1:

**Comment by WJohn** [comment]
Then either give hulks their stun punches against humans back, or make them unable to stun xenos, either. One or the other.

**Comment by GunHog** [comment]
Even as a Praetorian, I had issues fighting hulks. They would hit me with welding tools, and punch when I disarmed them. Since they cannot be stunned, my only option was to melee 1v1 on harm due to having no other options.

**Comment by PKPenguin321** [comment]
wjohn did you miss the part where xenos are stronger than humans therefore them being stunned by hulk is okay when compared to a human being stunned by a hulk

**Comment by Durkel** [comment]
Xeno bias circlejerk between WJ and gunhog. Wew.

We would still have hulk stun if people weren't cry baby bitches about dying, Just like crying about dying as a xeno because someone strong enough to punch a fucking solid plasteel wall down can knock your bitch ass on the ground.

**Comment by WJohn** [comment]
Then give hulks the ability to stun humans and I'd be quite happy to let them keep stunning xenos.

**Comment by GunHog** [comment]
> We would still have hulk stun if people weren't cry baby bitches about dying, Just like crying about dying as a xeno because someone strong enough to punch a fucking solid plasteel wall down can knock your bitch ass on the ground.

I agree with this statement. And someone strong enough to punch a solid plasteel wall down should knock humans, which are _much more frail_ to the ground as well.

**Comment by MMMiracles** [comment]
Could you at least replace it with something like throw_at instead so hulks can still act as a semi-threat in melee, considering they've given up their main advantage (range) in exchange for tackle immunity?

**Comment by ike709** [comment]
for the sake of this PR actually getting merge, take out the hulk stun tweak and put it in a new PR so people can argue about it in there and the rest of this can be merged without issue

**Comment by WJohn** [comment]
That'd be fine, then. I personally would rather see humans become stunnable by hulk rather than hulk simply losing the ability to stun anything ever. At least then the only thing they *can't* stun are royals, and thats so queens are stomped into mulch and the rest of the xenos suffer with no counter.

**Comment by optimumtact** [comment]
I thought I removed hulk stun punch?

**Comment by optimumtact** [comment]
Okay so apparently I left the Hulk stun punch in there by accident.

Just remove it completely.

**Comment by GunHog** [comment]
So, @WJohn, @optimumtact, keep the hulk changes in? I was about to commit a revert to that before I read the updates.

**Comment by ShadowDeath6** [comment]
Stunlocking has always been cancer, I'd be fine if it just locked xenos in place but let them still slash so it makes them a bit more vulnerable but not instant "if you get punched once by green man you are dead say goodbye"

**Comment by Kromgar** [comment]
Xenos can easily escape hulk punches. They recover faster than you can punch i would know ive been genetihulk a few times vs xenos

**Comment by kevinz000** [comment]
stop buffing xenos they're op enough already

**Comment by WJohn** [comment]
They just got a pretty major nerf with their tackle changes. Riot shields are now guaranteed to block leap and it's possible to near-indefinitely deny them their stunlocking by continuously pulling items out of your backpack. Now you'll also be able to tell they're ready to spit at you, and will be able to move accordingly. They ARE getting nerfs alongside their buffs, but no one pays attention to that.

**Comment by MMMiracles** [comment]
@WJohn 
>it's possible to near-indefinitely deny them their stunlocking by continuously pulling items out of your backpack

If someone can successfully pull this off against hunters with their spam disarms I will be genuinely impressed. Considering this as a legitimize nerf is hilarious because of how situational it is and how almost nobody would actually try to game that during a real fight.

Also calling the spit visual a nerf seems more like proper visual feedback that should be a priority for a decent game.

**Comment by ShadowDeath6** [comment]
>hulking 7ft tall monster furiously slapping the items out of grayshirt mcgee's hands as he rapidly pulls items from his backpack while running away

kek

also I agree, spit visual indicator really isn't a nerf

**Comment by WJohn** [comment]
Thats not the point of the nerf. The main point of the nerf is that you are given one guaranteed grace swipe that you can survive. You will lose the item in your hand, but you can still run. If you think quickly, you can pull another item out of your ass to save your life. If you have a shield, be it riot or roman or even a buckler, you're completely immune to pounces. The only thing the xeno can do now is try to spam disarm fast enough before you get to safety.

Besides, I have other nerfs in mind. I do plan on eventually removing xeno thermals, but that'll be done simultaneously with a large number of drone buffs to cement their role as support. This'll be a huge slowdown on xeno expansion when they can't find you through the ventilation system or if you're hiding in a locked room.

**Comment by GunHog** [comment]
Handcuff sprites and updated buttons added

image

**Comment by KorPhaeron** [comment]
Can you put hulk stun punches in another PR since the rest of this seems to make everyone happy

**Comment by GunHog** [comment]
I will need permission from WJ, but sure.

**Comment by PKPenguin321** [comment]
no you dont gunhog youre your own man not some bdsm slave to wj (actually you might be who knows)

**Comment by GunHog** [comment]
PKP, I made this PR on WJ's behalf as he does not know how to code, just as he makes mapping changes and sprites for me, as I do not know how to map or sprite. It would be ~~lewd~~ rude to change something without asking him first.

**Comment by PKPenguin321** [comment]
orangeeeees *shakes fist*

**Comment by optimumtact** [comment]
Hulk Stun punch can die in a ditch.

**Comment by PKPenguin321** [comment]
Hulk stun punch on xenos though

**Pull request merged**
