### PR TITLE
[Port] Removes all lag forever

### PR DESCRIPTION
**Pull request by Hopekz**
Ports yogstation13/Yogstation#8006

Removed everything that causes lag while keeping all the sprites, sounds and assets in the game (even the maps survived)

I tried to profile it but there is no code left to profile so you're going to have to trust me.

## Changelog
:cl: Hopek
rscadd: Whole game rework
rscdel: Removed anything that might create lag
/:cl:

### CODE REVIEW

**Comment by alexkar598** [comment]
high quality yogs meme content

**Comment by actioninja** [comment]
damn bro you got the whole coderbus laughing

**Comment by wesoda25** [comment]
like ur DOOM pfp bro

**Comment by Hopekz** [comment]
> like ur DOOM pfp bro

Thanks.
Edited it years ago

**Pull request closed without merging**
