### PR TITLE
Lemons are healthy

### PR DESCRIPTION
**Pull request by ma44**
:cl: ma44
tweak: Nanotrasen scientists have discovered that lemons contain a very little amount of healing reagents inside of it.
/:cl:

[]: # https://www.youtube.com/watch?v=yUqj8yEXp-0
REALISM IS FUN

### CODE REVIEW

**Comment by coiax** [comment]
Vitamin and nutriment already heal a small amount.

**Comment by WJohn** [comment]
A whole 0.1 omnizine for 100 potency lemons!

WORTH

**Comment by ma44** [comment]
@coiax It's not healthy if you get overweight and die from all of that nutriment!

**Comment by Haevacht** [comment]
Ma44 stop buffing botany this is TOOOOO FAAAAR.

**Comment by Kromgar** [comment]
@Haevacht he's got to balance joan's grudge code botany nerf

**Comment by FantasticFwoosh** [comment]
Im starting to feel like this is just a PR for the sake of a PR rather than a contribution

**Comment by kevinz000** [comment]
this is literally pointless.

**Comment by Militaires** [comment]
@kevinz000 just like u

**Comment by optimumtact** [comment]
Closed for being too savage

**Pull request closed without merging**
