### PR TITLE
[READY] New Sprites and Icons to fix certain items

### PR DESCRIPTION
**Pull request by LordVollkorn**
## About The Pull Request
Adds a few sprites to the game and attempts to fix some sprite issues.
Code changes are only minimal.

1. The following bags/items previously caused a pink error sprite when worn on the belt slot and are now fixed:
- Mining satchel
- Mining satchel of holding
- Chemical bag
- Plant bag
- Bio bag
- Book bag
- Construction bag
- Portable Chemical Mixer
bags_sample
portmixerbelt_sample

2. The previous **DNA sample device** for the DNA vault used the same sprite as the CMO's Hypospray. 
Thanks to **MrDoomBringer** for making this new sprite!
DNA_Sampler_export

## Why It's Good For The Game
Faulty sprites (shown as pink error sprites) are replaced by new sprites.
The dna sampler now has its own sprite to not look like the hypospray.

## Changelog
:cl: Jay Smith & MrDoomBringer
fix: Replaced faulty sprites for various bags and the Portable Chemical Mixer in the belt slot
fix: Replaced the DNA probe's old sprite (Hypospray) with a unique sprite
imageadd: New icon and sprites for the DNA probe
imageadd: Belt sprites for the Portable Chemical Mixer and various bags
/:cl:

### CODE REVIEW

**Comment by kopoba** [comment]
DNA sample device looks ugly

**Comment by MrDoomBringer** [comment]
@kopoba then sprite a new one
unique codersprites are better than sharing the same slightly cooler sprite among multiple unrelated items

**Review by ShizCalev — CHANGES_REQUESTED** [review]
anything that can go in a suit storage slot (ie plant bags, chemistry bag, bio bag, ect) need an icon in belt_mirrored.dmi too. 

it's essentially just offsetting/mirroring everything onto the other side of the wearer's body so it doesn't cover up belt items

**Comment by LordVollkorn** [comment]
> anything that can go in a suit storage slot (ie plant bags, chemistry bag, bio bag, ect) need an icon in belt_mirrored.dmi too.
> it's essentially just offsetting/mirroring everything onto the other side of the wearer's body so it doesn't cover up belt items

Thank you, I have been wondering why some items are in the belt_mirrored.dmi and some not;
I have tested with various suits and all the bags to confirm, as far as I can see none of these bags/items can be equipped into the suit storage 👍

**Review by Twaticus — APPROVED** [review]

**Comment by nemvar** [comment]
Oh nice, these are way better than the ones I made.

**Pull request merged**
