### PR TITLE
Skin Rework

### PR DESCRIPTION
**Pull request by neersighted**
I've reworked large parts of the skin, primarily cleaning up the skin file (never use the skin editor, only edit by hand!).

Here is what my changes look like. The only real  apparent change is flatter buttons:
image

This also fixes the window title being stuck as 'Space Station 13' and not respecting `world.name`.

### CODE REVIEW

**Comment by Dorsisdwarf** [comment]
I cant see what this does

**Comment by MrStonedOne** [comment]
Sorry neersighted, not everybody is dumb enough to use windows 10(=P), you are gonna have to show us before and afters.

**Comment by duncathan** [comment]
Any way to apply it to all the controls we have? Like in the upper right?

**Comment by MrStonedOne** [comment]
yes, they just have to edit the rpane window.

**Comment by MrStonedOne** [comment]
you also might want to give them a flat line border, its not obvious they are buttons otherwise

**Comment by Incoming5643** [comment]
I dislike this on a shearly subjective level

**Comment by octareenroon91** [comment]
I think it might do more for the tabs than the chat button.

Maybe add one or more user prefs for this?

**Comment by Shadowlight213** [comment]
I dislike it as well. Looks wierd with the buttons blending in and not being distinct

**Comment by PKPenguin321** [comment]
i see literally no difference, what exactly are we looking at

**Comment by neersighted** [comment]
This is still WIP, I'm working on making some of the native skin nicer. Will update screenshots in a bit but the 510 port is occupying me ATM.

**Comment by Dorsisdwarf** [comment]
@PKPenguin321 I think it's the buttons in the bottom right hand corner.

**Comment by neersighted** [comment]
I've updated the OP with new screenshots.

**Comment by Razharas** [comment]
Ok lets see how it works

**Comment by lzimann** [comment]
OH GOD WHY

**Comment by Shapsy** [comment]
no no no no no

**Comment by Incoming5643** [comment]
text box font changed, looks like smashed assholes

http://i.imgur.com/TyOycE5.png

A lot of people bitching that "it's shitty change for the sake of change" which I kind of agree with.

Why wasn't this just test merged instead.

**Comment by Dicks1** [comment]
Absolutely disgusting

**Comment by MrStonedOne** [comment]
I told you @neersighted you need something to indicate it's a button on the buttons.

**Comment by lzimann** [comment]
Why was the text size increased, it's just fucking huge for no reason, and pls make the hotkey mode the same color as before(white)

**Pull request merged**
