### PR TITLE
Replaces the Reaper Scythe with the Vorpal Scythe (also the Morbid trait)

### PR DESCRIPTION
**Pull request by necromanceranne**
## About The Pull Request

Adds the Vorpal Scythe, a special chaplain null rod variant, replacing the Reaper Scythe, a not so special null rod variant.

da scythe

When you choose the vorpal scythe, it comes as a shard that you implant into your arm, similar to a cursed katana.

Once implanted, you can draw it at any time like an arm implant. However, sheathing it again presents some problems. (Also, implanting the organ gives you ``TRAIT_MORBID``, which I'll explain in a bit)

The Vorpal Scythe has 10 force, one of the weakest null rod variants for force that isn't a joke null rod. However, it has exceptional armor pen and also has 2 tiles of reach. So quite unique.

It also has a special beheading ability when you right-click someone. This borrows some code from amputation shears, functioning pretty similarly, except with a few additional ways to speed up the action and restrictions. (It takes 15 seconds baseline to behead someone standing and conscious, and speeds up or slows down based on factors such as incapacitation and whether or not our scythe is already empowered)

When you successfully behead someone with a mind, the vorpal scythe gains 20 force and can be safely stowed and drawn for 2 minutes. Performing more death knells like this will reset the timer.

If it has not performed its 'death knell', or you haven't hit a living mob, then it will cause severe damage to you if you ever try and stow it (or its forced back into your arm). Just hitting a mob with the scythe will sate it for 4 minutes. Unless it is a non-player monkey. Horrible things. Just hitting mobs does not reset the timer on empowerment.

What this means is that the chaplain may be more hesitant to simply draw their weapon on people. It also means that potentially, the chaplain will not always have magic immunity, since they may end up stowing the weapon away and be reluctant to draw it on a whim without either taking damage for sheathing it without hitting something, or dealing with having one less hand up until they can.

While empowerment only happens when you behead mobs with a mind, beheading monkeyhumans and other mindless humans subtypes causes their heads to become haunted! It's mostly harmless and largely just SpOoKy. We don't want heads with actual players in them to go floating off to space. (Does not work on monkey heads for sanity reasons)

haunted heads oooooh

When you have the Morbid trait, you think creepy stuff is cool and hate saving peoples lives. You get a mood boost from graverobbing, autopsies, dissections, amputations (including beheadings with the scythe and amputations with the shears) and revival surgery. However, you get a mood penalty when you tend wounds on the living, as well as a hefty penalty when you perform CPR or defibrillate someone. I was thinking Victor Frankenstein when I was choosing which actions had an associated moodlet, so anything that I might have missed would be appreciated.

You also count as potentially cool with regards to haunted objects. Ghosts think you're neat. (Revenants probably will still kill you if they had the chance)

## Why It's Good For The Game

I've wanted a null rod that radically alters how you approach things as a chaplain and gives them a real unsettling, sinister vibe. It isn't just that you've got a cool weapon, you have a completely different approach to how you treat others on top of that.

Chaplains with a giant scythe beheading people all day is kind of fucked up, and especially if they are seemingly obsessed with amputating limbs, dissecting corpses and performing mad science in the morgue. 

This isn't a sect and yet will still define a bit about your round and how it plays out. I mean, it could be a sect but I think it is more fun if you mix and match it with the sects. Maybe a Sparring sect chaplain beheads the loser! Maybe the maintenance freak is graverobbing and stealing arms. All kinds of combinations.

## Changelog
:cl:
add: The Vorpal Scythe, a special null rod variant that gains power from beheading people! But it is fickle about when and how you use its power. Replaces the Reaper Scythe.
add: Beheading via the special death knell attack empowers the scythe, but only on humans with a mind, and requires you to use the right-click button to wind up the slice. If you succeed, you empower your scythe for a bit!
add: If they don't have a mind, you cause the heads to float around. OoooOOOooo! Spooky!
add: With the sinister crystal that holds the Vorpal Scythe within bound to your arm, you are Morbid! You love to do pretty unsettling things, like dissections for fun! But helping the living stay alive is abhorrent to you!
add: ...unless you get to do it while screaming 'IT LIVES!' via Revival surgery. Screw conventional medicine and science, you know the true way to bring back the dead! 
/:cl:

### CODE REVIEW

**Comment by CoiledLamb** [comment]
this is so fucking cool!!

**Comment by MercuryArrow** [comment]
I didn't choose the morbid life, the morbid life chose me. 
Will be very cool to see this in action and maybe see the trait make its way into other things.

**Comment by Wollywoger** [comment]
I play(ed, i moved to a /tg/ downstream) a lot of chaplain, and here are my two real nit-picks that don't just devolve into "where does this fit into the Balance [tm])

the biggest one is the exclusivity of removing the sheathe penalty only on beheading of a mind-owning mob, 
I still need to trawl and find the exact damage/force you set, but it might be a good idea to allow reducing/removing the sheathe penalty (and only the sheathe penalty, obviously you said why you can't have the damage bonus) when beheading a mindless mob- perhaps throw in some flavor text that says it didn't boost the damage or w/e

the other one is really just stating how big a deal anti-magic is for the chaplain, since nullification of magic is balanced around how dangerous several of the magics are (namely, cult and heretic stun), so often it may just result in chaplains walking around with the scythe always out, a bit like a reduced various of the dark blessing/chainsaw hand

**Comment by EricZilla** [comment]
You should give coroners the morbid trait too lmao

**Comment by Loafin34** [comment]
> You should give coroners the morbid trait too lmao

abso-fucking-lutely please. 10% chance on scientists

**Comment by necromanceranne** [comment]
All things in due time. (can you guess what my next pr will be)

**Comment by Fikou** [comment]
looks like the soulscythe

**Comment by necromanceranne** [comment]
> the biggest one is the exclusivity of removing the sheathe penalty only on beheading of a mind-owning mob

I like your idea, and I think that's a fair tradeoff. I'll maybe make it work like the cursed katana, and while it is empowered, you can sheathe it at will.
 
> the other one is really just stating how big a deal anti-magic is for the chaplain

I think if there is more liberty on when you can draw and sheath the scythe, this might be a bit easier, but I don't think chaplains are necessarily _assumed_ to be antimagic, or else they'd spawn with one on the shuttle/roundstart. (I know extra chaplains do but I digress)

I think enough people assume the chaplain to be safe from magic that they'll assume that they're untouchable. At the very least, I could maybe look at giving the chaplain lesser antimagic on insertion of the shard.

**Comment by necromanceranne** [comment]
Big changes. You can stow the weapon more easily by just hitting a mob. Haunted objects like you if you're Morbid. Beheading mindless humans with the scythe will haunt their severed heads, making them float about.

**Comment by ATH1909** [comment]
> We don't want heads with actual players in them to go floating off to space. (Does not work on monkey heads for sanity reasons)

how far do they tend to roam?

**Comment by necromanceranne** [comment]
It's entirely random. Not too far?

**Pull request merged**
