### PR TITLE
Fixes vehicle action handling ordering

### PR DESCRIPTION
**Pull request by silicons**
Woops, passenger should be removed from the passenger list AFTER their stuff was taken.
apologies to @MoreRobustThanYou and @Qustinnus

### CODE REVIEW

**Comment by Qustinnus** [comment]
-angry grunting noises-

**Comment by MoreRobustThanYou** [comment]
150 hours

**Comment by Qustinnus** [comment]
you need to switch 

grant_passenger_actions(M)
after_add_occupant(M)

or else passenger actions dont get assigned properly, you troglodyte. @kevinz000

**Comment by kevinz000** [comment]
@Qustinnus that's a bug, fixed.

**Comment by Qustinnus** [comment]
i know its a bug, that's why I'm reporting it.

**Pull request merged**
