### PR TITLE
[READY] Adds a chance to spawn with a horrible tie as a scientist

### PR DESCRIPTION
**Pull request by kittymaster0**
https://www.youtube.com/watch?v=Wd6qOHSDqOI&feature=youtu.be

The ties now spawn on a 1/250 or .4% chance

Thanks to two nice coders for grabbing my helmet and holding my hand onto the coderbus.
Thanks for @Mat#3542  on discord for the suggestion
:cl:
add: gives scientists a chance to spawn with an awesome tie
/:cl:

### CODE REVIEW

**Comment by nemvar** [comment]
Make it a chance and you got my full *unironic* support. Also, link doesn't work.

**Comment by kittymaster0** [comment]
> Make it a chance and you got my full _unironic_ support. Also, link doesn't work.

link fixed.

**Comment by wesoda25** [comment]
Epic

**Comment by ishitbyabullet** [comment]
half life 1 reference.

**Comment by optimumtact** [comment]
to the actual random mat pinged, sorry, apologies, don't look in here for your own sanity.

**Comment by coiax** [comment]
Is there a holiday where we can set the chance to 100%?

**Comment by JStheguy** [comment]
"Why do 0.4% of us have to wear these ridiculous ties?"

**Pull request merged**
