### PR TITLE
Brig/Medbay door button now opens simultaneously

### LINKED ISSUE #14941: Medbay doors are no longer synced.
When pushing the medbay door button, one door will open after the other, rather than simultaneously.

Both doors started closed, I'm not sure why it's getting queued.

### PR DESCRIPTION
**Pull request by Cyberboss**
Fixes #14941

:cl: Cyberboss
fix: Fixed a bug that caused door buttons to open doors one after another rather than simultaneously like they are suppose to
/:cl:

untitled

### CODE REVIEW

**Comment by pudl** [comment]
This doesn't need a changelog

**Comment by PKPenguin321** [comment]
it doesnt need it but it deserves it

**Comment by MrStonedOne** [comment]
Can you explain what you mean by this.

They already open at the same time? What does this change?

**Comment by CyberbossJHCB** [comment]
No they don't they open one after another. NOW they open at the same time

**Comment by MrStonedOne** [comment]
who the hell changed that.

**Comment by MrStonedOne** [comment]
caused by this: https://github.com/tgstation/tgstation/commit/b2629a56e2a7b59fb953caca6341b55b2b039e15#diff-c482a10fcca4f5f661eced08a61da8eeL50

**Comment by MrStonedOne** [comment]
Also, please make your changelog more clear, it should state something more definitive then "synced" as the average player would have multiple ideas of what that could mean.

Something like `Buttons now open doors simultaneously rather then one after another`. Specifying the old behavior (if you can do so succinctly) keeps the entry meaningful to all players, and prevents the changelog from being filled with meaningless noise causing people to tune it out.

The 100% correct phrase would also specify that it's a bugfix, something like `Fixed a bug that caused door buttons to open doors one after another rather than simultaneously like they are suppose to` but i'll leave that up to you.

**Pull request merged**
