### PR TITLE
Auto Rifle Balance Changes

### PR DESCRIPTION
**Pull request by Steelpoint**
Before anyone asks, this PR does not re add the Auto Rifles back to Boxstation, or any other station, this is a pure balance PR for the rifles.

---

This PR effects multiple balance changes to the rifles, they are as follows.
- Ammunition Change

The ammo used by the Auto Rifle has been changed from 9mm to 4.6x30mm. Damage wise there are no changes but this ammo change means that Auto Rifle magazines are no longer 9mm ammo compatiable, meaning you cannot produce ammo from a cargo autolathe for the rifles cheaply and en mass.
- Sprite Change

While I love Ausops gun sprites, I feel that the quality and art style difference between the current sprites, and all other Sec gun sprites, clash badly with one another. 

Thus I am reverting the gun to the prior sprites.

Ausops gun sprites will remain in the code, now named 'oldrifle', for any admins to use in game or future coders to use as they see fit.

In addition the alt red gun sprites were removed from the game due to non-usage.
- Cargo/RND Cost Changes

The cost for the Gun and Ammo crates was slightly reduced to be more in line.

The 'Auto Rifle Gun Crate' was reduced from 40 to 35 cargo points, being just 10 more points than a Energy Gun crate and 20 more points than a Laser Crate (EGuns should be rebalanced as the points are going off of the old Eguns).

The 'Auto Rifle Magazine Crate' was reduced from 40 to 30, in addition one magazine was removed bringing the total per crate to four magazines.

The RND costs for magazines was increased, metal costs remain the same but a additional 400 to 600 more unique material (silver, uranium) costs was added.

### CODE REVIEW

**Comment by Steelpoint** [comment]
Link to prior relevant PRs
https://github.com/tgstation/-tg-station/pull/12202
https://github.com/tgstation/-tg-station/pull/12122

**Comment by Bawhoppen** [comment]
>make the already extremely OP guns even CHEAPER

seriously steelpoint, stop with the memes

**Comment by Niknakflak** [comment]
Eh, for once it's not just a buff.  He made them cheaper yes but also made it so ammo can only be ordered or made by science, and no longer the autolathe which is a large nerf.  He buffed and nerfed and personally I am ok with this.

**Comment by WJohn** [comment]
I personally much prefer our current sprites, but if they're too beastly I can understand. We should definitely keep the new sprites (in all black, perhaps) for future usage.

**Comment by Steelpoint** [comment]
One of the more bigger annoyances with the rifles was how they clashed with other sec equipment, the quality and design difference made the Rifles look more like something you would see from a Military team or the Nuke Ops, not something reminiscent for NT Security. The original sprites are far more in line with what other Sec gear looks like.

But yes, the sprites will be kept in the code for anyone else to use.

Also seems Travis is not updating well today.

**Comment by Iamgoofball** [comment]
If travs fucks up close/reopen the pr to force it to get its head out of its ass and recompile

**Comment by Steelpoint** [comment]
Thanks.

**Comment by Bawhoppen** [comment]
I do quite like the bay sprite more.

**Pull request merged**
