### PR TITLE
Adds brig cells to Tramstation security checkpoints

### PR DESCRIPTION
**Pull request by SgtHunk**
## About The Pull Request
Blah blah blah, you've seen this PR in the form of https://github.com/tgstation/tgstation/pull/58688.
It adds brig cells to each department's security outposts in Tramstation. Cool stuff.
Tramstation was the easiest one to do this on due to most areas having a lot of space for that task. I'd love to do this on all other stations - this was mostly to see the feedback related to it.
Would mark this as QoL but such an addition is way too big for a QoL so going for the feature one.
@EOBGames 

(Disclaimer: Images in PR are outdated. Scroll down to the comments to actually see the current designs.)
As for how it looks:

## Engineering

tramsec-engi

## Science

tramsec-sci-new

## Medical

tramsec-med

## Cargo

tramsec-cargo

## Why It's Good For The Game

Brig cells in security checkpoints is an amazing feature only really done in Delta. In the future, I'd personally like to see them implemented in all maps.

## Changelog
:cl:
add: The Tramstation security checkpoints now have cells for easy brigging on the go.
/:cl:

### CODE REVIEW

**Comment by Mothblocks** [comment]
While you're at it, is there any way you can make it nicer now that they're designed towards 1-3 security officers rather than always 1? I saw someone complaining about how cramped and weird they feel presently.

**Comment by SgtHunk** [comment]
I could try. I did this while trying to modify the rest of the map as least as possible, but I do agree that I should expand them (And also because I killed the plant in the sci outpost)

**Comment by SgtHunk** [comment]
Currently working on reworking the cargo security checkpoint to make the brig cell face the hallways (to add a button to let people out) As of now, I have these done, and want feedback in case the layouts aren't the most favorable.

## Engineering: 
tramengsec-expanded

## Medical:
(Yes, the chemistry room was expanded to make up for the space that the checkpoint used)
trammedsec-expanded

## Science:
(The plant is ALIVE!)
tramscisec-expanded2

**Comment by Mothblocks** [comment]
yeah i like tht

**Comment by Maurukas** [comment]
Very nice work. Directional mounts and everything.

**Comment by notfrying1pans** [comment]
do the pipes in atmos work?

**Comment by SgtHunk** [comment]
> do the pipes in atmos work?

In theory? They should. From my tests I didn't spot any runtimes and it worked fine. The pipes that got moved were normal scrubber pipes and shouldn't conflict as the other scrubbers pipes are on layer 2 (and are the hidden kind)
The normal scrubber pipes are visible up until the Right entrance of CE's Office, where they become hidden and go through the walls & windows for convenience's sake

And I tested in-game just recently to confirm, they DO work. I understand this confusion was because it seems as if the pipe is leading nowhere because that's where the hidden/visible transition happens?

**Pull request merged**
