### PR TITLE
Durathread Strangling Bug Fix and Better Feedback

### LINKED ISSUE #59569: Durathread Invisible to Third Parties
## Reproduction:
Durathread choking fibers as produced by Golems are unable to be seen by third parties: this means that medical staff, first aid, etc attempting to revive you after you've gone down to a magical choking fiber are unable to remove/assist you in any way. The fibers, simultaneously, appear to keep you in a state of permanent crit/near crit unconsciousness without killing you from O2 starvation.

### PR DESCRIPTION
**Pull request by RandomGamer123**
## About The Pull Request
Adds examine feedback for people being strangled by durathread.
Jaws of life can now cut durathread strangling.
Better cut messages (and a playsound()) when cutting the durathread off, previously it only sent messages to the person being freed.

## Why It's Good For The Game
Fixes #59569 and also related bugs / qol issues / lack of feedback

## Changelog
:cl:
qol: You can now examine people to see if they are being strangled with durathread.
qol: Cutting durathread off of someone else now produces a public message for everyone to know.
fix: Durathread strangling caused by golems can now be cut off with jaws of life as well.
/:cl:

### CODE REVIEW

**Comment by TheBonded** [comment]
is there even a way to strangle someone with durathread without being a durathread golem?

**Comment by RandomGamer123** [comment]
> is there even a way to strangle someone with durathread without being a durathread golem?

no as far as i can tell

**Comment by ATH1909** [comment]
it'd be nice if we could cut these with wirecutters as well

**Comment by TheBonded** [comment]
> it'd be nice if we could cut these with wirecutters as well

good news, @ATH1909 
you already can

**Pull request merged**
