### PR TITLE
Remove TRAIT_HANDS_BLOCKED trait from stasis

### PR DESCRIPTION
**Pull request by Mothblocks**
## About The Pull Request
You can now use your hands again while in stasis. I am labeling this a fix since the source is from the mobility refactor, which did not advertise this behavior (not that it really matters).

## Why It's Good For The Game
It's moreso a very helpful quality of life feature than anything problematic, especially being able to take off your clothes to help out doctors.

## Changelog
:cl:
fix: You're now able to use your hands again while in stasis.
fix: You can now click the backpack slots while in stasis, previously you would have to click the backpack itself.
/:cl:

### CODE REVIEW

**Comment by Winterous** [comment]
Now robomen can replace their own hearts!

**Comment by Rohesie** [comment]
I'm not a fan of the implications of this, of being able to suspend your biological processes and not die unless further direct damage is applied, but still being perfectly functional.

> Now robomen can replace their own hearts!

This is a good example.

**Comment by Winterous** [comment]
Yeah the concept of stasis is super weird, really you should be unconscious and immobile, like you're frozen in time, kinda.

**Comment by msgerbs** [comment]
> 
> 
> I'm not a fan of the implications of this, of being able to suspend your biological processes and not die unless further direct damage is applied, but still being perfectly functional.

Wasn't this the behavior before the refactor?

**Comment by Rohesie** [comment]
> Wasn't this the behavior before the refactor?

Yes, I believe so. It's not something I'd like to revert to, though, personally.

**Comment by Winterous** [comment]
At present you can move stuff around from your surface inventory, like belt and pockets, but not inside your backpack I believe. But you might be able to shift-b to remove the top item of backpack? I'm not sure. It's definitely a weird situation.

**Comment by Rohesie** [comment]
> 
> 
> At present you can move stuff around from your surface inventory, like belt and pockets, but not inside your backpack I believe. But you might be able to shift-b to remove the top item of backpack? I'm not sure. It's definitely a weird situation.

Can you open an issue about it? It seems like the shift+b action is bypassing having your hands blocked.
Same as the moving of your surface inventory, that should require hands usage.

**Comment by Jared-Fogle** [comment]
Robomen replacing their hearts is such an unreasonably niche use case compared to "person comes to medbay and needs to take off their clothes". I don't think that's a valid complaint, nobody was really "abusing" this while it was still in the game.

Regardless, I'm not really a fan of a code refactor (which should ideally be invisible to players) introducing regressions and then leaving them in.

> At present you can move stuff around from your surface inventory, like belt and pockets, but not inside your backpack I believe

Correct, because you're lying down. You *can* however click the backpack itself.

**Comment by Rohesie** [comment]
> Robomen replacing their hearts is such an unreasonably niche use case compared to "person comes to medbay and needs to take off their clothes". I don't think that's a valid complaint, nobody was really "abusing" this while it was still in the game.

It's more of a general and long-term thing. With this you can shoot disablers and lasers while in stasis, and if we make mobile stasis beds that will still be true. It open venues for unwanted interactions.
And on removing their clothes, you can only do so while not incapacitated, so there's absolutely nothing preventing you from unbuckling, removing the clothes and re-buckling.
The benefit for not taking these simple steps is tiny compared to introducing a state in where you can act and fight, but your vital processes are stopped.

> Regardless, I'm not really a fan of a code refactor (which should ideally be invisible to players) introducing regressions and then leaving them in.

It wasn't really planned/intended, that was a major refactor which included several fixes, and in some cases I had to guess what was the intended behavior, as I was rebuilding the checks.

**Comment by Jared-Fogle** [comment]
>  And on removing their clothes, you can only do so while not incapacitated, so there's absolutely nothing preventing you from unbuckling, removing the clothes and re-buckling.

Which is what we had before, and anecdotally, as someone who played a lot of medbay both before and after you were able to take off clothes while in stasis, people were significantly more willing to do so after the changes than before. This doesn't even factor in how there's now a cooldown to getting back up from the stasis bed. Again, it's just a decent quality of life change.

> It's more of a general and long-term thing. With this you can shoot disablers and lasers while in stasis, and if we make mobile stasis beds that will still be true. It open venues for unwanted interactions.

I care about the long term health of the game, but this hypothetical feels a little silly to me. We can deal with issues like this when (if) we get there.

> The benefit for not taking these simple steps is tiny compared to introducing a state in where you can act and fight, but your vital processes are stopped.

Again, anecdotal, but I have not heard of anyone using stasis beds for combat, ever. I have, however, seen people take off their clothes while on stasis every day, which has been received well.

**Comment by Rohesie** [comment]
> Which is what we had before, and anecdotally, as someone who played a lot of medbay both before and after you were able to take off clothes while in stasis, people were significantly more willing to do so after the changes than before. This doesn't even factor in how there's now a cooldown to getting back up from the stasis bed. Again, it's just a decent quality of life change.

Does the cooldown influence any of the actions? You can use your hands even while on the floor, and you don't need to wait to get up to re-buckle.
 
> I care about the long term health of the game, but this hypothetical feels a little silly to me. We can deal with issues like this when (if) we get there.
> Again, anecdotal, but I have not heard of anyone using stasis beds for combat, ever. I have, however, seen people take off their clothes while on stasis every day, which has been received well.

It's actually not a hypothetical, I've used effectively my disabler as a poisoned sec officer (who'd otherwise be dying) to help out against someone attacking medbay.

This is not my main concern, though. I understand the appeal of no-anesthetics surgery in where you are always ready to react and never lose control, even the small QoL which will make some people will perform an action they could do the same with one extra click and one click-and-drag action, but long-term I think it's better if stasis and surgery put the patient in some kind of state of vulnerability (why would any non-traitor use anesthetics?), and it'd be nice to move in that direction.

At the end of the day it's clear we don't really agree with each other, and it's unlikely we'll change each others' minds. We should probably get feedback from other maintainers. I'll defer to others if they have a different design vision.

**Comment by Jared-Fogle** [comment]
Replacing with blocking the ability to use items, but still be able to take off clothes later.

**Pull request closed without merging**
