### PR TITLE
Un-snowflakes heat-proofing glass airlocks, fixes #9437

### LINKED ISSUE #9437: Airlock heat-proofing is extremely snowflakey
As it stands right now, there is only one way to make a heat-proof airlock: make it glass and paint it in the Research palette. As a result, glass Research airlocks are the only heat-proof airlocks on the station short from special airlocks that had their variables edited by mappers.

My personal suggestion is to include the option to add plasteel to an airlock during construction. Then when the airlock is finished, set heat_proof to 1. This allows people to make their own insulated airlocks if they have plasteel, which they usually will if they are building an incinerator.

### PR DESCRIPTION
**Pull request by maartenberg**
Glass airlocks as they are now magically block all heat (only) if they're research airlocks (see #9437), this pull changes that so that any glass airlock can be made heat proof by using a sheet of reinforced glass to create a windowed airlock (regular glass for a non-heat proof airlock).

Feedback needed:
- How should the heat-proofness of airlocks be shown? In the description, name, or sprite, or not at all?

### CODE REVIEW

**Comment by WJohn** [comment]
By non-glass airlocks blocking heat, did you change it so they DON'T block heat? Because that's a pretty major change since everyone thinks around that concept during fires, it'll trip up a lot of people.

**Comment by spasticVerbalizer** [comment]
@WJohn You're right, I didn't think of that and I'll change it back again.

**Comment by WJohn** [comment]
Also when upgrading glass airlocks to become heat proof, I think the method to do that should be choosing between regular glass or reinforced glass, rather than adding plasteel later, as it's fewer steps and is cheaper for the builder. Still, that's up for debate on which system people would prefer.

**Comment by RandomMarine** [comment]
Airlocks are rarely manually constructed already, and plasteel is a pain to get a hold of at times. I'd just go with glass vs r-glass.

**Comment by PKPenguin321** [comment]
As of now r-glass is the only way to make a glass airlock, you'd have to redo everything so normal glass airlocks are made of normal glass and heat-resistant ones are made of r-glass.
Although this might be trickier codewise, it's a better idea, as heat-resistant airlocks aren't at all gamebreaking so needing plasteel to make them is a little intense.

**Comment by Lumipharon** [comment]
Wouldn't it just be better to make all airlocks heat proof?
Like, wouldn't the station be hemorrhaging heat out all the airlocks like crazy, even though walls and even thin panes of glass are perfectly heat proof?

**Comment by spasticVerbalizer** [comment]
@Lumipharon The problem is that glass airlocks in their current state are not heat proof by default, but use the paintjob (only research airlocks) to determine whether or not to block heat. This PR changes that, so that you have to use a sheet of reinforced glass to make a heat-proof airlock or a sheet of normal glass to make a non-heat-proof airlock
Solid airlocks (all non-transparent ones) always blocked heat regardless of paintjob and this PR doesn't change that.

**Comment by Ricotez** [comment]
:+1:

**Pull request merged**
