### PR TITLE
Makes silver tiles consistent with the other station tiles

### PR DESCRIPTION
**Pull request by Lexorion**
## Changed the silver tile sprites to make it consistent with the other tiles in the game. In addition to that,made it similar to the gold tile.

Lower half of the picture shows the new tiles.
Bananium is still missing but I have no idea how I should change it (they are also quite 
rare so it's not that much of a problem I hope)...

### CODE REVIEW

**Comment by ShadowDeath6** [comment]
What is the blus part in the tile made of

**Comment by coiax** [comment]
why is it blue

**Comment by ChangelingRain** [comment]
Same reason gold tiles have red; it looks cool

**Comment by Lexorion** [comment]
It's *supposed* to be carpet like material which can be slightly reflective

**Comment by Militaires** [comment]
prussian blue

**Comment by PKPenguin321** [comment]
>spacemen are so strong that they can, with just one bare hand, mush solid silver into the color blue

**Comment by Nabski89** [comment]
Paul Karason managed to do it, so can we!

**Comment by Lexorion** [comment]
I'll fix the conflicts later

**Comment by KorPhaeron** [comment]
@Lexorion conflicts

**Comment by Lexorion** [comment]
Fixed my conflicts in #24979

**Pull request closed without merging**
