### PR TITLE
petting a pug no longer makes you think you pet a corgi!

### LINKED ISSUE #42361: Pugs are classified as corgis when pet
## Round ID:
N/A

## Testmerges:
N/A

### PR DESCRIPTION
**Pull request by granpawalton**
:cl: GranpaWalton
fix: petting a pug no longer gives you a positive moodlet like petting a corgi does
/:cl:

is there a good way i could have done it without just copy pasting?

fixes  #42361

### CODE REVIEW

**Comment by adamkad1** [comment]
we need a quirk that makes you get positive moodlets from petting cats instead of corgis

**Comment by ExcessiveUseOfCobblestone** [comment]
this change drops the moodlet for pet :(

**Comment by Menshin** [comment]
> is there a good way i could have done it without just copy pasting?

Well, you could always try something like this https://pastebin.com/gTavug6A .

Also, `1` (help intent) and `-1` (harm intent) are magic numbers when calling `wuv()`  and the code is mostly similar for `.../pet/cat` if you want to refactor even further.

**Comment by bgobandit** [comment]
👎 

this is not an ideal way to do this

**Comment by granpawalton** [comment]
thanks for the help @Menshin !

@bgobandit is this way better?

**Comment by tortellinitony** [comment]
Add new argument for the SEND_SIGNAL with the name of the pet

**Comment by Grazyn** [comment]
Maybe fix the text as "dogs are adorable!" instead of removing a source of positive moodlets?

**Comment by granpawalton** [comment]
@Grazyn I thought about doing it that way because I know we need more but then I was worried people would say that "why doesnt x pet also give a positive moodlet?" and due to the original purpose of the moodlet but since we are trying to have more positive moodlets a seperate pr could be made to propose a positive moodlet for petting all pets

**Comment by tortellinitony** [comment]
That's why you change it @granpawalton

**Comment by ExcessiveUseOfCobblestone** [comment]
you only needed to change this lol https://github.com/tgstation/tgstation/blob/7837f014595f4d8b4677cd271aa38e5db2c985fb/code/datums/mood_events/generic_positive_events.dm#L26-L29

**Comment by Menshin** [comment]
I think the code refactor you propose here is complementary with the other PR and is an improvement as it reduces spaghetti code. 
I was suggesting merging the two because there's some _minor_ conflicts in the `dog.dm` file.

Unless we want only specific pets as "wuvable" (regardless of moodlets), you should update and propose your PR rather than closing it (provided you're not fed up with it, of course).

**Comment by tralezab** [comment]
I'll try and implement your improvements in mine

**Comment by granpawalton** [comment]
Im not fed up with it, it just seems that there are people who are a lot more interested in it than I am. I would rather let people make their changes before I try to touch it as I only want to try to improve it not change it's purpose and letting the other PR run its course would be a good way of me seeing how people want it to act.

**Pull request closed without merging**
