### PR TITLE
Remaps the AI satellite

### PR DESCRIPTION
**Pull request by WJohn**
AI satellite has been an eyesore for a long time, and more than that a complete joke to take out on box. So I went ahead and remapped it to make it bigger, prettier, and significantly tougher to take out.

Also, it is now connected to the incinerator, so if you send a cyborg there you can have piping turned on to flood plasma even in the satellite!

:cl: WJohnston
tweak: The AI satellite has been remapped on box to be significantly more challenging to take down. Now features branching rooms, the ability to flood plasma from a connection made to the incinerator, a kill hallway, and flanking pathes in maintenance. Beware the external turrets near the back!
/:cl:

### CODE REVIEW

**Comment by Bawhoppen** [comment]
much stronger overall for AI, mixed feelings

**Comment by GunHog** [comment]
Smells like Mettaton. :+1:

**Comment by Xhuis** [comment]
Seems too strong for me. The current satellite is virtually impregnable if you cut power to the transit tube - you need space access or luck to get there, and even then if you have an engiborg hack the SSUs you can roast all the space suits and completely destroy any opportunity of getting there. :-1:

**Comment by Cebasiz** [comment]
two minibombs will 100% guaranteed kill the AI and depower all the turrets on box btw if you throw them in the right spot.

i've been ggnore'd in about 5 seconds twice in the last week so the knowledge is spreading.

**Comment by Anonus** [comment]
I give you permission to take dream's AI sat because I think it's nicer.

**Comment by xxalpha** [comment]
I like it. That AI core positioning might have to be changed in the future due to balance, but let's go with this for now.

**Comment by WJohn** [comment]
Keep in mind the AI has the ability to bolt down the "viewing area" in front of the core with the button there next to it, forcing you to go around through maintenance and cut through an r wall.

**Comment by Bawhoppen** [comment]
Dream's is very similar to box's current one

**Comment by GunHog** [comment]
Might be missing exterior cameras, you do not know what your outside turrets are shooting or why!

Does the lobby or any place have motion sensors?

**Comment by WJohn** [comment]
Cams added to the outside turrets, foyer and kill hallway now have motion cams instead.

**Comment by xxalpha** [comment]
Did you bomb test it?

**Comment by Zilenan91** [comment]
Can you remove some of the turrets on the outside of the back of the sat? It's way too hard for Ops to kill the AI with this setup

**Comment by Bawhoppen** [comment]
It makes me happy we are a codebase that does bombtesting of new map edits

**Comment by WJohn** [comment]
You can actually easily kill the AI by sitting at the middle at the very top with a sniper rifle and penetrator rounds. Besides that a syndieborg could just blitz straight down and reach the AI very quickly.

Also no I did not bombtest this, but the core should be fairly well protected against explosions with how many r walls it has on the sides.

I *did* test the turrets, however, they're all able to shoot you from the doorway and from much further still.

**Comment by KorPhaeron** [comment]
>exterior turrets

Cant wait to be yelled at about malf balance more

**Comment by xxalpha** [comment]
@Wjohn I am almost sure you can knock out AI power if you place a bomb outside the south wall.

**Comment by Xhuis** [comment]
Wait, exterior turrets?
thumbsdown

**Comment by Zilenan91** [comment]
Yeah get rid of the exterior turrets

**Comment by tkdrg** [comment]
I dunno, on one hand it does look a bit too strong, but on the other hand it's so pretty

**Comment by xxalpha** [comment]
It's just so people do easily bomb the core. You can break into the satellite from the north.

**Comment by Jalleo** [comment]
Actually this may be weak if the sniper rifle can still 1 shot it

**Comment by tkdrg** [comment]
That's the point of the rifle. Penetrators were made to one-shot AIs. The issue is that it's ridiculously harder for loyal crew to breach into the sat.

**Comment by WJohn** [comment]
The exterior turrets in my mind basically buy you just as much time as having an exterior catwalk + grilles for defense. If you plan to attack from outside, then you'll need to invest just as much time breaking in.

**Comment by Jalleo** [comment]
How does the exterior turrets target atm WJohn by default.

**Comment by Zilenan91** [comment]
@WJohn You still technically don't with this setup if you tunnel through the rwalls

**Comment by tkdrg** [comment]
@Zilenan91 that would be the case, if the AI was facing down. Facing up however, even if you breach maintainance from outside the turret's range, you're gonna have to face at least the turrets in the core before being able to laser the AI.

**Comment by Zilenan91** [comment]
@break the rwall above the monitor in the AI chamber and you should be able to lase the AI from there without getting hit by the turrets.

**Comment by tkdrg** [comment]
You mean the upper chamber? Yeah, you can do that, but the turrets can still laser you.

**Comment by WJohn** [comment]
Yeah and that's the entire point, zilenan. You can either rush through the death hallway and take it by storm, giving you a very safe firing line into the AI core, or work around in the maintenance where you don't have to deal with as many turrets, but take longer and have to fight the AI in a less usable spot.

**Comment by PKPenguin321** [comment]
:-1: 
hella shit defenses, breaking into this thing is EZPZ
kind of a clusterfuck with different things such as rechargers and tools being all spread out
the whole corridor with the windows on both sides is pointless and dumb
random one tile wide dead end "maintenance tunnels"
strangely phallic shape overall

**Comment by Bawhoppen** [comment]
Atleast its not xeno shaped, I'm proud WJ could resist that urge

**Comment by Zilenan91** [comment]
ILLUMINATI CONFIRMED

**Comment by Niknakflak** [comment]
:-1: what's with all the dumb hallways that don't do anything.  Looks awful.  Find the middle ground inbetween nothing there and all that shit you just mapped.  
It also looks like a penis complete with two balls, a distinct shaft and distinct head.

**Comment by Anonus** [comment]
I HAVE AN ALTERNATE PROPOSAL;
this and that

**Comment by xxalpha** [comment]
Couldn't you just glue them together.

**Comment by Bawhoppen** [comment]
>DREAM

**Comment by Niknakflak** [comment]
I like anonus'.

**Comment by PKPenguin321** [comment]
i like the one we have

**Comment by Niknakflak** [comment]
wtf is with that wiring

**Comment by kevinz000** [comment]
why take out shutters meta has those..

**Comment by WJohn** [comment]
I've pointed out many times that the hallway with glass in front of the turrets is solely a "killing hallway". It's harmless in any state other than lethal, in which case it'll be a bit of a nightmare to get through.

**Comment by PKPenguin321** [comment]
you can literally go around it

**Comment by xxalpha** [comment]
But this leaves the option for the AI to trap people in that corridor while pretending not to be rogue.

**Comment by WJohn** [comment]
PK do you even read anything I or other people have written here? That's the point. You can go through the kill hallway and take the heavy losses disarming that, then you're left with an easy pot-shot firing lane right into the AI's core without its turrets being able to even target you.

OR you can go around it in maintenance, having to deal with only one turret on either side room, then dig through an R wall and have to fight the AI in a more conventional manner (not directly in front).

**Comment by Niknakflak** [comment]
My penis concerns have not been discussed yet

**Comment by Bawhoppen** [comment]
you'll get your penis issue discussed after my penis issue higher on WJ's list is discussed first

**Comment by xxalpha** [comment]
@Niknakflak Stop sucking so much :rooster: and maybe you will stop seeing :rooster: everywhere.

**Comment by tkdrg** [comment]
Could we keep this discussion non-penis related please

**Comment by Steelpoint** [comment]
With my Sat design it took two old max cap bombs to breach the core, I think with the new max cap it may only take one bomb.

How many bombs would it take for someone outside the Sat to breach into the AI Core?

**Comment by GunHog** [comment]
From my testing, once you deal with the side turret, it seems that you can breach it with a syndiebomb, if you place it at the weak spots, which are 2-R-walls thick. It will, however, leave an R-girder behind. You will need tools to remove it.

You can get through with two minibombs + tools as well. 

The optimal, cheapest way to breach is with two bricks of C4, which did not leave a girder in my tests.

**Comment by Niknakflak** [comment]
It looks like a dick though so?

**Comment by xxalpha** [comment]
You called for it, in fact.

**Comment by Dorsisdwarf** [comment]
I like the idea of the glass corridor with turrets so every time you go through you sweat bullets

But the sat design isnt great

**Comment by KorPhaeron** [comment]
AI turrets that can only hit people in lethal is kind of a weird design choice for an AI that starts asimov.

Maybe make the deathall have disabler/laser turrets?

**Comment by YakumoChen** [comment]
guys look at the thing i made its much better except it's a hueg wip and also i made it really fast and i don't know how to map
aisat

**Comment by Zilenan91** [comment]
3 thick rwalls baaaaad, go with WJs

**Comment by GunHog** [comment]
I do not see how that alt one is better.

**Comment by Bawhoppen** [comment]
how does this not have a controversial tag

**Comment by tkdrg** [comment]
because nobody asked for it

**Comment by PKPenguin321** [comment]
why not just not change the AI satellite? i still don't see why this is needed

**Comment by xxalpha** [comment]
Because Box is the main map and needs to be changed every so often to not become totally stale.

**Comment by PKPenguin321** [comment]
>longstanding functional features are "stale" by definition

okay

**Comment by WJohn** [comment]
I've changed the turrets in the killing hallway to have a disable mode instead of tasers, so they can still stun you through the glass.

**Comment by Bawhoppen** [comment]
I still don't like this :-1:

**Comment by tkdrg** [comment]
Yeah I'm not sure about this. I'd love to see this testmerged for a couple rounds to get a feel for the way it plays out. @KorPhaeron

**Comment by KorPhaeron** [comment]
@tkdrg 

When the goof shit is done I'll put this one up

**Comment by tkdrg** [comment]
That would be great. Restarting this for travis.

**Comment by lzimann** [comment]
:-1: turrets in the outside is just awful imo

**Comment by GunHog** [comment]
Might be missing fire control equipment, such as fire alarms, firelocks, a few wall extinguishers, a water tank in the atmos room, etc.

**Comment by WJohn** [comment]
I didn't quite see the need for firelocks at the time, and it seems sorta unecessary given how incredibly rare fires would be here. You could also shut it down pretty much instantly by wrenching a single pipe away in space, or in the incinerator, or lots of other rooms.

**Comment by swankcookie** [comment]
Is there any other area in any map guarded by three r-walls? It seems a tad excessive,  even with reduced internal security.

**Comment by WJohn** [comment]
Metastation has 3 r walls guarding its satellite, too. Dreamstation as an extremely thick and sturdy catwalk, which'll take just as long to break through as deconstructing an r-wall, birdboat has a large portion covered by an asteroid, and Disc has up to four r walls thickness in some places, and at minimum at least 3.

This is pretty standard at this point.

**Comment by GunHog** [comment]
I requested fire alarms because that is standard for nearly all of the station. And if you think plasma fires are going to be rare, I think you should play AI more! Even without the firelocks, having the alarm and other equipment is a good idea for when it does happen.

**Comment by KorPhaeron** [comment]
I still think all the statues and extra stuff laying around makes the satellite appear overcluttered/doesn't fit with box.

**Comment by Bawhoppen** [comment]
yea box is the base one not supposed to have the fancy gimmicks and cool things

**Comment by Jalleo** [comment]
If all other stations have it then really its not the standard

**Comment by WJohn** [comment]
Remaking because conflicts.

**Pull request closed without merging**
