### PR TITLE
Admins now get deadminned when roundstart antag

### PR DESCRIPTION
**Pull request by DaxDupont**
[Changelogs]: # (Your PR should contain a detailed changelog of notable changes, titled and categorized appropriately. This includes, new features, sprites, sounds, balance changes, admin tools, map edits, removals, big refactors, config changes, hosting changes and important fixes. An example changelog has been provided below for you to edit. If you need additional help, read https://github.com/tgstation/tgstation/wiki/Changelogs)

:cl: Dax Dupont
admin: Admins now automatically get deadminned on roundstart antag.
/:cl:

[why]: # (Please add a short description [two lines down] of why you think these changes would benefit the game. If you can't justify it in words, it might not be worth adding.)

Sometimes you miss roundstart and you remain adminned without realizing or you can already get a lot of meta information between roundstart and hitting deadmin.

Automatically deadminning seems like a fair thing to do, you can always readmin if needed.

### CODE REVIEW

**Comment by Cyberboss** [comment]
>current year

**Review by Cyberboss — CHANGES_REQUESTED** [review]

**Review by Cyberboss — CHANGES_REQUESTED** [review]

**Comment by ExcessiveUseOfCobblestone** [comment]
Admins should force-deadmin when joining the game so they have to make the conscious effort to readmin while playing tbh.

**Comment by DaxDupont** [comment]
@ExcessiveUseOfCobblestone feel free to make a PR that has that I'd be supportive of it. However the bikeshed would be real so I'd rather do stepping stones myself.

**Comment by bgobandit** [comment]
ennnnnhhhh

I'm ok with admins starting deadminned for all roles but (possibly in a separate PR) it would be good if deadminned admins could see the number of open tickets. not the contents of the tickets, but how many exist, so they can have an idea of how urgent their presence is

I guess maaaybe you could metagame off the existence of tickets but that would either be some real sherlock holmes galaxy brain shit, or something very obvious in the round

**Comment by OverlyGeneric** [comment]
i don't know if this is a meme pr or not.

**Comment by DaxDupont** [comment]
This PR only does it for antag roles.

I'd like to do this in steps, head roles next.

**Comment by subject217** [comment]
yah this is fine, I simply meant re:cobby's post

there have been some edge cases where the server is fucked where being adminned and joining means that i have access to the fancy schmancy dropdown menu manual restart option and you can't use it while deadminned

**Comment by DaxDupont** [comment]
@Kierany9 its a single button press to readmin if you're antag

**Comment by ExcessiveUseOfCobblestone** [comment]
@subject217 This PR and my comment are referring to joining the round, not the server.

**Comment by Cyberboss** [comment]
@DaxDupont Yeah, being alive and an admin should be the exception not the rule

**Comment by ShizCalev** [comment]
I have a branch more or less ready for when I get back from my vacation.

It adds config options to auto-deadmin when an admin gets
Roundstart antag
Command roles
Security roles
Silicon/ai roles
ECT

The admin is then readminned automatically upon death.

**Comment by Cyberboss** [comment]
Let's wait for that then

**Comment by subject217** [comment]
@ShizCalev No readmin on death please - if I stand any chance of getting cloned I don't want to get exposed to a bunch of extra round info that I wouldn't need to see otherwise.

**Pull request closed without merging**
