### PR TITLE
Sink changes

### LINKED ISSUE #12611: Grabbing someone and washing them in the sink will wash the grab.
What it says on the tin.

### PR DESCRIPTION
**Pull request by ghost**
- Sinks now allow you to wash your face, which removes lipstick and makes you less drowsy. To wash your face, target the head, eyes, or mouth before using it.
- Reagent containers can no longer be filled from sinks if they lack the OPENCONTAINER flag.
- Abstract items can no longer be washed. (Fixes #12611)
- Stuns from washing an active stun baton are now modified by the baton's stun duration, and a spark sound now plays.
- sleep() checks followed by Adjacent() checks have been replaced with do_after() checks.

### CODE REVIEW

**Comment by Firecage** [comment]
Xhuis...please someday make it so Sinks doesn't always dispense water. So that admins or mappers can easily change them to dispense some other reagent.

**Comment by Xhuis** [comment]
That would require almost an entire rewrite of sinks, and that won't be happening in this PR. It was going to be a part of plumbing before I decided that it wouldn't be worth the effort.

**Comment by duncathan** [comment]
Why not just add a`reagent_type` var or something?

**Comment by Xhuis** [comment]
As I said, that's for a different PR, not this one.

**Comment by duncathan** [comment]
It would literally be a two line change :v
w/e tho

**Comment by Xhuis** [comment]
The problem with that is that I'd have to implement some different checks for if the reagent is from a certain list (i.e. water, space cleaner, etc...) but if I ever do plumbing I'll add it then.

**Comment by Jalleo** [comment]
Is there a hostile version for drowning another person by using grab and tageting the face etc etc?

**Comment by Xhuis** [comment]
@Jalleo No. I was going to code it, but decided against it because fitting an adult human's head into a sink is really hard.

Unrelated: Merge-ready

**Comment by Lumipharon** [comment]
you dont have to fit the whole head, just submerge the face for long enough.
People have drowned in puddles and all sorts of shit.

**Comment by Iamgoofball** [comment]
@xhuis why'd you delete your account

**Comment by Chocobro** [comment]
that won't ping him, ask him on irc

**Pull request merged**
