### PR TITLE
Serverwars uniforms and mascot pr.

### PR DESCRIPTION
**Pull request by Mandurrrh**
Adds in uniforms for sybil and basil. Add the corgisuit in for the mascot. All have to be adminspawned for now! 

corgimascot
basiluniform
sybiluniform

### CODE REVIEW

**Comment by pudl** [comment]
okay everyone i can already predict these sprites getting SMASHED but seriously that is a good S so props on that

**Comment by pudl** [comment]
im already back to look at the s again i love it so much

**Comment by dannno** [comment]
smh
:-1:

**Comment by Nienhaus** [comment]
What about team terry

**Comment by xxalpha** [comment]
team who

**Comment by Nienhaus** [comment]
The best team.

**Comment by Mandurrrh** [comment]
Sorry guys its been up on the forum forever if you wanted different uniform sprites for your team @dannno then you should have made them. We are out of time seeing as the event is in 3 days. It was open for anyone to make.

**Comment by Jalleo** [comment]
These uniforms are perfect to barf on. Apart from corgistan one.

**Comment by Mandurrrh** [comment]
Still 24 hours for you guys to make uniforms! Cant bitch about codersprites when its been in the forums for weeks asking for an alt bc no time now with 3 days left and no one offering I had to make the pr so it would be in time.

**Comment by xxalpha** [comment]
I don't know if it's the background, but there's something going on with Sybil's south facing sprite. Like the arms are thinner than usual.

**Comment by dannno** [comment]
why would i have made them when i hate the entire concept and event

**Comment by kevinz000** [comment]
s? SYNDICATE!

**Comment by RandomMarine** [comment]
Let's just commit these to master, yes.

So every server running up to date /tg/ code will have these suits in their code.
That exist for a brief event between two servers.
That everyone will forget about within a week.
So they'll just sit around until somebody can be assed to revert them.
Just so we can have people wearing S and B shirts for some event instead of the team colors that already exist in the thunderdome.

:-1:

**Comment by dannno** [comment]
also yeah^

**Pull request closed without merging**
