### PR TITLE
Converts maps to TGM

### PR DESCRIPTION
**Pull request by Cyberboss**

### CODE REVIEW

**Comment by optimumtact** [comment]
buffing that linecount life

**Comment by xxalpha** [comment]
Didn't MSO suggest using JSON to load them faster? Why isn't that being done?

**Comment by Cyberboss** [comment]
Because do it yourself

**Comment by xxalpha** [comment]
You're the person behind the loading maps on runtime.

**Comment by Cyberboss** [comment]
I'm also busy and lazy

**Comment by xxalpha** [comment]
>lazy

Yeah right

**Comment by Cyberboss** [comment]
Are you seriously implying I'm not lazy?

**Comment by xxalpha** [comment]
I am not implying anything, you're the most active contributor since last summer, consistently the top contributor in commit count.

**Comment by Cyberboss** [comment]
S-stop, you're making me blush

**Comment by optimumtact** [comment]
Get a room

**Pull request merged**
