### PR TITLE
Revolutions won't lose if all rev heads lose their connections

### LINKED ISSUE #13039: Causing revs/loyalists to loose due to braindeadness is unfair
As it says in the title, it is unfair. Sure, it has a legitimate use, but not everyone has a 100% super never-fail internet connection, nor does everyone have a PC which never crashes. And on rare occasions, even dream seeker may crash for a player for a weird reason.

In short, this means that you can get disconnected for a reason beyond your control, and suddenly your entire side looses.

### PR DESCRIPTION
**Pull request by Incoming5643**
Fixes #13039 (which was also #15159 and #17452)

### CODE REVIEW

**Comment by Shapsy** [comment]
What if the last revs do all go braindead? Can we get an admin notification if all the remaining heads/revheads are AFK/disconnected?

**Comment by PKPenguin321** [comment]
yeah, it should ping admins so they can put somebody else in the body or something

**Comment by Jalleo** [comment]
Wait so this is why rev rounds end if everyone dc's due to a sudden connection loss.

**Comment by kevinz000** [comment]
WHAT ABOUT HEADS OF STAFF?!!

**Comment by Incoming5643** [comment]
@kevinz000 They use a different check that involves traitor objectives. That never had the client check to begin with.

**Comment by kilkun** [comment]
sounds like the whole gamemode needs a rework. isn't it mostly oldcode anyways?

**Comment by Incoming5643** [comment]
Everything about game mode code is old code and needs a rework. None is without sin.

**Pull request merged**
