### PR TITLE
Chemistry holder sanity checks

### PR DESCRIPTION
**Pull request by optimumtact**
You can no longer add/remove negative amounts.

Removing reagents now ensures you don't remove more of the reagent than actually exists.

### CODE REVIEW

**Comment by Chocobro** [comment]
[04:26] (ma44) shit
pr made to prevent ma "cash lemons" 44 from powergaming

**Comment by Chocobro** [comment]
ok fuck you phone git live with my mistake forever

**Comment by optimumtact** [comment]
@Fox-McCloud may be applicable to paradise

**Comment by optimumtact** [comment]
@tgstation/commit-access merge please

**Pull request merged**
