### PR TITLE
Removes Disco Inferno

### PR DESCRIPTION
**Pull request by Rohesie**
## About The Pull Request

Removes Disco Inferno emergency shuttle.

## Why It's Good For The Game

It was funny the first forty times or so. It currently gets bought every round, and it's basically a grief shuttle.
This kind of thing should be an admin event, not the regular choice. The joke gets stale if it's overplayed.

## Changelog
🆑 
del: Disco Inferno emergency shuttle has been decommissioned.
/:cl:

### CODE REVIEW

**Comment by ATH1909** [comment]
cringe ass nae nae PR

if you have to remove it from normal rotation, lock it behind emagging the console or something instead (there's support for other shuttle unlocking conditions, like bubblegum needing to die to unlock the arena shuttle)

**Comment by Kylerace** [comment]
take out the plasma tiles and rename it to disco shuttle. no other shuttle has caramelldansen afaik.

**Comment by Barhandar** [comment]
remove not improve

lock it behind defeating an ashdrake or something

**Comment by Winterous** [comment]
I say either just make it more expensive, or lock it behind something yeah. Maybe selling like 500 plasma sheets.

**Comment by MimicFaux** [comment]
Saying it gets bought every round is hyperbole. It has an easily accessible spectators box for those who want to enjoy their party at room temperatures. This is unnecessary at best, and salty at worst.

**Comment by Tlaltecuhtli** [comment]
if you dont want to die you go in the room without plasma lol

**Comment by TreyWJ** [comment]
If it gets bought every round, maybe that means, I don’t know, people LIKE it?

And if people LIKE it, how is removing it good for the game? Is this just you trying to remove something you personally think is tired? The like-dislike ratio seems to say so.

**Comment by Winterous** [comment]
Ok to be fair, it's very common for the windows to get broken, rendering the saferoom unsafe.

**Comment by Tlaltecuhtli** [comment]
make windows stronger (not 1 shot by axeman) then

**Comment by Fikou** [comment]
>It currently gets bought every round

because players like it, its fun to have a party with a disco ball

**Comment by CRITAWAKETS** [comment]
even for an unsafe shuttle this sucks because you literally just need a fire axe and a welder to make the shuttle unsurvivable without an atmos hardsuit

this is only ordered and liked by griff captains who think themselves funni

**Comment by Detective-Google** [comment]
>citadel
this and/or an emag lock could probably keep in a fun and interesting shuttle while making it less common

https://github.com/Citadel-Station-13/Citadel-Station-13/pull/10745

(making it more expensive would also help)

**Comment by MimicFaux** [comment]
If the complaint is people dismantling the safety of the spectator's box, then it's a player behaviour problem, not a code fix. The same people who want to see a room of spessmen turn sideways are going to be venting the other shuttles (scrapheap comes to mind), or bringing their own combustibles. Bwoink the trouble makers.

Or make the windows unbreakable.

**Comment by Jared-Fogle** [comment]
> this and/or an emag lock could probably keep in a fun and interesting shuttle while making it less common

I plan on locking the Disco Inferno, the Hyperfractal, and the Oh Hi Daniel all behind an emag after this.

> Bwoink the trouble makers.

I've spoken to several admins who say that they simply do not care about grief on the Disco Inferno. I don't want to make this PR look like enforcing policy through code, because I sincerely believe it isn't, but it's food for thought.

**Comment by ATH1909** [comment]
> I plan on locking the Disco Inferno, the Hyperfractal, and the Oh Hi Daniel all behind an emag after this.

... So why didn't you just lead with that PR instead of making this one? Why should we merge a PR on the promise that you'll make another PR if that PR's gonna undo what this PR did anyway?

**Comment by Jared-Fogle** [comment]
Because even if I don't make that PR, the Disco Inferno still sucks.

**Comment by ATH1909** [comment]
Oh, wait, Rohesie made this PR, not you. My bad.

**Comment by anconfuzedrock** [comment]
based

**Comment by lordpidey** [comment]
> If it gets bought every round, maybe that means, I don’t know, people LIKE it?

It means people in command roles like it.

**Comment by optimumtact** [comment]
https://www.youtube.com/watch?v=A67ZkAd1wmI

**Comment by Barhandar** [comment]
The problem isn't even disco inferno, it's that some asshole with comms access (or just dumbass with it failing to log out) can unilaterally buy a shuttle.

**Comment by WorldofLoina** [comment]
Another PR that only slims the game down without realising why this has remained for so long before

**Comment by Jared-Fogle** [comment]
@Barhandar That's why I'm making it emag only.

**Pull request merged**
