### PR TITLE
2H Sword to the Cult Forge - Robustin's Github Adventure

### PR DESCRIPTION
**Pull request by Robustin**
New Image Link: https://i.imgur.com/Y33AgJo.png

🆑 Robustin
add: Blood cultists can now create a unique bastard sword at their forge
del: Blood cultists can no longer obtain a hardsuit from the forge
/🆑

See #28252  and #30329 for previous PRs that got meme'd.

The cult bastard sword (name pending) is a powerful 35-force weapon with a 50% block rate that can only be held with 2 hands and cannot be pulled or placed in any inventory slot. It uses a BIGHUGE 64x64 icon as well. To avoid RUSH THE BRIG memes and greedy cultists revealing their presence early, this weapon can only be forged after about 20 minutes into the round.

What makes this weapon unique are three special abilities:

    Using a new totally modular dash datum based on Kor's dash code, the sword can jaunt you somewhere in visual range once every 30 seconds.

    The sword acts as a soul reservoir. Upon attacking any crit or dead target, the sword will absorb their soul like a soulstone. The key difference is that the souls cannot be released as shades and can only be used on construct shells. Using a bible on the sword will exorcise it and release the souls in a purified form.

    The sword also has an action ability called Geometer's Fury (name pending) that empowers the user with a whirlwind-type attack for 5 seconds. The ability will slow down the user but make them effectively invincible during this period. Obvious audio and visual cues will make the ability easy to notice when used in combat. During the whirlwind the sword will attack all adjacent targets at the same rate that normal melee attacks occur.

### CODE REVIEW

**Comment by DoctoreMad** [comment]
>Using a bible on the sword will exorcise it and release the souls in a purified form.

Do they have a special sprite to represent it or is it only "Purified [name]"?

**Comment by Robustin** [comment]
Yes, its a unique sprite with "Purified Shade of Oldman Robustin" as the name.

**Comment by DoctoreMad** [comment]
I c-can't find the DMI...

**Comment by ExcessiveUseOfCobblestone** [comment]
chaos two-handed zweihander for obvious darksouls memes [because the soapstone wasn't enough]

**Comment by Ratvar** [comment]
Now add clockmech

**Comment by DoctoreMad** [comment]
Was already slated to be added but 2hard4Xhuis so dropped.

**Comment by Armhulen** [comment]
good the clock mech sounds retarded anyways

**Comment by ExcessiveUseOfCobblestone** [comment]
If it's like that mech in bayonetta 2 then that sounds cool

**Comment by DoctoreMad** [comment]
@Armhulen Excuse me? GIRLS love fighting GIANT ROBOTS. You should ADD GIANT ROBOTS so that GIRLS will come to your server. It "WORKS".

**Comment by Thunder12345** [comment]
Pics pls

**Comment by Robustin** [comment]
I'm too lazy to load the branch and screenshot it.

Imagine the current cult sword but twice as thick and twice as long.

**Comment by Bawhoppen** [comment]
As acting art director I remind you that you're obligated to show sprites on any PR related to them

**Comment by DoctoreMad** [comment]
>Acting art director

3/4 perspective reverts when

**Comment by Bawhoppen** [comment]
I'm thinking a 3/4+-45 is our best bet

**Comment by Bawhoppen** [comment]
I wasn't joking about that show the sprites thing by the way. Even if you don't recognize my legitimate rule, that is our actual policy.

**Comment by DoctoreMad** [comment]
Thanks Bawhoppen you are my greatest ally

**Comment by tgstation-server** [comment]
Your Fix/Feature pull request delta is currently below zero (-1). Maintainers may close future Feature/Tweak/Balance PRs. Fixing issues or helping to improve the codebase will raise this score.

**Comment by Bawhoppen** [comment]
This shouldn't have gotten merged considering he violated the repo policy by not revealing his sprites when asked

**Comment by Robustin** [comment]
@Bawhoppen 

Read the first line of the fucking PR body you moron.

**Comment by Bawhoppen** [comment]
Was that always there? The comment by Thunder threw me off

**Pull request merged**
