### PR TITLE
Command Roles are properly restricted to just humans

### PR DESCRIPTION
**Pull request by Incoming5643**
instead of everything except lizards, catgrills, and plasmamemes (when the config is set for that).

Resolves the problems pointed out in https://tgstation13.org/phpBB/viewtopic.php?f=10&t=5754

### CODE REVIEW

**Comment by KorPhaeron** [comment]
Skeletons are perfectly qualified heads of staff

**Comment by Anonmare** [comment]
@KorPhaeron Stop pushing your skeleton agenda you damn rattler

**Comment by demonfiren** [comment]
0/10 everyone should qualify for headstaff

CAPTAIN'S A CLOACA

**Comment by PKPenguin321** [comment]
>captain is a nonhuman
>it's rev
>"ai kill the captain"
>rip rev

**Comment by freerealestate** [comment]
Wouldn't changing the wording from "human" to "crewmember" work?

**Comment by PKPenguin321** [comment]
>bringing up asimov wording changes

trust me just don't start it won't end well for anybody

**Comment by ChemicalRascal** [comment]
@freerealestate: Nope, because borgs could be considered crewmembers, as could the AI itself.

**Comment by CosmicScientist** [comment]
> captain is a nonhuman
> it's rev
> "ai kill the captain"
> rip
Unless I'm wrong current policy on the tg servers is that AIs shouldn't be killing without reason so they can't kill lizards because they exist.

**Comment by PKPenguin321** [comment]
yes, they cannot kill lizards etc. fnr. if they are ordered to, however, they are 100% obliged to, but the blame admin-wise falls on whoever ordered them to do it

**Comment by topham1** [comment]
well, i feel like killing nonharmful lizards as an asimov silicon would violate the first and third laws of robotics, as nonharmful lizards are carbon-based beings and are very capable of assisting the crew, reducing the chances of human harm. however, a lizardperson that has been proven to be harmful would likely no longer carry the possibility of reducing the chances of human harm, and thus are then valid for the borgs' and AI's raging murderboners.

this should solve this dilemma. if a human orders a nonharmful lizard dead, the AI cannot oblige because that lizard is capable of preventing human harm. if a human orders a harmful lizard dead, the AI must oblige because that lizard is no longer capable of preventing human harm, and is likely the cause of the harm.

as for the original topic, flypeople are not human and should not be heads of staff. there's no way we can let lizards be heads because having that social power gap is a really interesting part of the game, but that means that flypeople can't be heads for the sake of consistency. also, nanotransen is racist probably so

**Comment by PKPenguin321** [comment]
policy discussion doesn't really belong here, i was just pointing out what the standing policy is

**Pull request merged**
