### PR TITLE
GOOF ELECTION PR #2: Desucake: Removes Patch Delay

### PR DESCRIPTION
**Pull request by Iamgoofball**
# VOTE IAMGOOFBALL 2017
# DIRECT ALL BALANCE AT @Desucake
:cl: Desucake & Iamgoofball
tweak: Fixes patches having a delay.
experimental: Vote Iamgoofball for Headmin 2017!
/:cl:

### CODE REVIEW

**Comment by Cheridan** [comment]
sigh

**Comment by ChangelingRain** [comment]
I'm going to close your pr and you're going to call it voter suppression and get a rage aneurysm.

**Comment by Iamgoofball** [comment]
that's exactly what I'm going to do

**Comment by AnonymousNow** [comment]
Stopped clock.

**Comment by ChangelingRain** [comment]
Okay I'm glad we got that clear thanks goof.

**Comment by Cheridan** [comment]
Please see: https://tgstation13.org/phpBB/viewtopic.php?f=38&t=9821

**Pull request closed without merging**
