### PR TITLE
Modifies plastic flaps to defeat the secret box technique.

### LINKED ISSUE #12129: You can get past plastic flaps with a box
What it says on the tin. Boxes, like lockers can go through plastic flaps. Unlike lockers, the person hiding inside can move while inside it to get through.

### PR DESCRIPTION
**Pull request by Incoming5643**
This code is not object oriented, but that's mostly because of how hideously circumstantial plastic flaps are. In the long term these flaps should be phased out and replaced with something more justifiably uniform in how structures interact with it. Remember that initially they only existed to let mulebots through.

Always remember to use windoors with plastic flaps, as ways to get under them are still plentiful, box or no box.

Fixes #12129

### CODE REVIEW

**Comment by Incoming5643** [comment]
Branches made indirectly due to cardboard boxes: 1

**Comment by TrustyGun** [comment]
r.i.p

**Comment by Zilenan91** [comment]
Fun Removal

**Comment by Razharas** [comment]
The code is so bad, so bad

**Comment by Cookiesndip** [comment]
Fun removal. It's one of the fun, interesting uses of the box. Keep it!

**Comment by tuypo1** [comment]
I like d20s solution there you can actually move while lying down but the flaps have an electrified floor below them.

**Comment by Incoming5643** [comment]
After much lollygagging, I've fixed the conflict. It'd figure the first time flaps have been touched in seemingly years would be when I was touching them.

**Comment by Razharas** [comment]
Ok fuck it code is bad but so are plastic flaps

**Pull request merged**
