### PR TITLE
Medbay Rework and Plumbing for Pubbystation 

### PR DESCRIPTION
**Pull request by Maurukas**
## About The Pull Request

This gives Pubby's medbay a much needed refresh, and adds in a large plumbing space where the surgery and CMO office were previously. The corgi petting garden has been reallocated from the recovery room to the psychologist's office. A storage area has been added behind cryo to house it's equipment and gas hookups, as well as other large items like blood crates.

Due to the constraints around the area, the monastery asteroid and southwest engineering maintenance area have been moved around slightly in order to keep virology and the petting garden intact. 

2020-09-27 14_44_40-tgstation  _maps_map_files_PubbyStation_PubbyStation dmm  - StrongDMM

## Why It's Good For The Game

This adds plumbing, a major feature, to PubbyStation, and reworks its medbay to be a more pleasant and functional area to work in. The main treatment area should have quite a bit less shoving going on.

## Changelog
:cl:
add: PubbyStation's medbay has undergone major reconstruction, including the addition of a plumbing area.
/:cl:

### CODE REVIEW

**Comment by Angustmeta** [comment]
Looks like xenos spawning in viro monkey pen can get trapped if they can't open the windoor.

**Comment by nightred** [comment]
You have a duplicate camera name.

c_tag match for cameras at Medbay Lobby (119,126,2) (JMP) and Medbay Lobby (121,130,2) (JMP) - c_tag is Medbay Entrance
c_tag match for cameras at Medbay Lobby (121,130,2) (JMP) and Medbay Lobby (119,126,2) (JMP) - c_tag is Medbay Entrance

**Comment by Tlaltecuhtli** [comment]
large plants inside windows look weird

**Review by EOBGames — CHANGES_REQUESTED** [review]
Alright there's a few things to address here (don't worry, nothing major, and the design is good overall).

1: Surgery should also have a drill, a bonesetter, and some bone gel or surgical tape, otherwise they won't be able to deal with broken bones.

2. I'm seeing some decals under windows, namely at surgery and the entrance- remove these, please.

3. With medbay having a front desk again, including a button which will open the front doors from the desk seems like a good idea- I believe you can do this by setting them up with an ID, the same as you would for shutters.

4. Some of the use of decals is a little confusing, particularly in storage where they just seem to end abruptly halfway around the room, or in psych, where they're solid, except for one wall where they alternate with white- while it wouldn't stop me merging this, I'd appreciate some changes for internal consistency.

5. YOU REMOVED THE NO ERP POSTER FROM THE CMO'S LITTLE PRIVATE ROOM, YOU'VE DOOMED US ALL!

6. Perhaps some detailing on the floor in chem, to help break up the big white blob?

7. Runtime starts blocking the CMO into their desk, perhaps move them to their bed so they can be cozy and comfy, as all cats long to be?

8. Have you checked this over with debug tools (just because that would save me having to clone and compile this myself)?

**Comment by Maurukas** [comment]
@EOBGames Changes made, mediocre plumbing detailing decals added, and the rest of them have been touched up. I believe I have hit everything on your list.

**Pull request merged**
