### PR TITLE
buffs ling adrenalin somewhat

### PR DESCRIPTION
**Pull request by ghost**
ling adrenalin now actually lets changelings resist stunbatons, as previously it had a stamina regen of -1

note that the ability comes with a -75 on use to stamina when activated before but in practice it was less effective against stunbatons and disablers than it was vs tazers because ling adrenalin had absolute shit for stamina regeneration. worse than cigs even

i can tone the value down if -15 is too high but i'm not worried about this making lings entirely immune to stuns the main value of adrenalin sacs has always been the immediate stun removal not the benefit over time and it's still a costly ability that penalizes you for overusing it with poisoning you

stunbeating is still effective as ever for lings

## Changelog
:cl:
balance: Changeling adrenalin ability now improves stamina regeneration by -10, rather than a measly -1, to reflect stamina based combat
/:cl:

### CODE REVIEW

**Comment by kriskog** [comment]
15 stamina regen is extremely strong given how the meta is shifting towards stamina over stuns. You might just be able to tank disablers with this, and you sure as hell wont be taken down by a stun baton if you got the stun resistance.

**Comment by PKPenguin321** [comment]
You should follow the lead of the traitor adrenals rebalance PR

**Comment by AdamElTablawy** [comment]
like i said in the above stunbeating with a baton should work just fine like before just like it worked fine with the pure stun batons when this had -2s to stun per tick

it makes it hard to keep a ling stunned if you're not constantly beating it but still possible

@PKPenguin321 elaborate

**Comment by kriskog** [comment]
Since the batons have a two second cooldown, I am fairly sure it wont be possible. Try it yourself.

**Comment by PKPenguin321** [comment]
See https://github.com/tgstation/tgstation/pull/46211

**Comment by AdamElTablawy** [comment]
that's a fair argument


Aranesp is higher at -18 but i can reduce this to -10 or so

maybe -5 given the speedboost it gives you

**Comment by kriskog** [comment]
And that's the reason the new adrenals doesn't have aranesp.. :)

Aranesp needs a nerf, it's something I'll get to later.

**Comment by AdamElTablawy** [comment]
@kriskog i'll wait for more feedback before i drop the numbers some

**Comment by Detective-Google** [comment]
>buff ling

please no

**Comment by ATH1909** [comment]
Yeah, drop this to -10 or -5 stamina regen per tick; -15 looks like it'll be way too much.

**Comment by AdamElTablawy** [comment]
it is now -10

**Pull request merged**
