### PR TITLE
Makes the Syndicate mask fireproof and acidproof

### PR DESCRIPTION
**Pull request by Ebin-Halcyon**
## About The Pull Request
Basically just reopens #60689 as the feature freeze is now over and the original PR author didn't reopen it themselves.

## Why It's Good For The Game
Same reasons as the original PR.
Nukies shouldn't have to worry about fire melting their gear off while wearing a fireproof hardsuit.

## Changelog

:cl:
balance: Syndicate masks are now fire + acid proof
/:cl:

### CODE REVIEW

**Comment by SuperNovaa41** [comment]
Balance change not QOL

**Comment by Ebin-Halcyon** [comment]
> Balance change not QOL

Didn't think it'd be big enough to warrant it being a balance change since it's a single line, thanks for telling me otherwise.

**Comment by Sealed101** [comment]
*Your syndicate mask starts to fall apart!* with an elite hardsuit no more, god bless

**Review by 81Denton — APPROVED** [review]

**Comment by Ebin-Halcyon** [comment]
> I can accept fireproof because of the elite suit not providing a separate one, but acid proof you have not made a case for.

I added acidproof as well since Elite suits are fire+acidproof, if you think it's a bit much I can just pop it off to make it just fireproof.

**Comment by necromanceranne** [comment]
If it's fireproof because ops use pyrotechnic weapons, the same argument can be levelled towards acid since they use caustic weapons as well. That really shitty biosprayer thing

The captain's gas mask is also acidproof, and there is _some_ trend towards captain power being only a rung below operative power.

**Comment by ExcessiveUseOfCobblestone** [comment]
> > I can accept fireproof because of the elite suit not providing a separate one, but acid proof you have not made a case for.
> 
> I added acidproof as well since Elite suits are fire+acidproof, if you think it's a bit much I can just pop it off to make it just fireproof.

makes sense

**Pull request merged**
