### PR TITLE
Adds new icon for the null rod's reaper's scythe variant.

### PR DESCRIPTION
**Pull request by Crushtoe**
:cl: Crushtoe
imageadd: Added a shiny new icon for the reaper's scythe in-hand and normal sprite. It's 25% less gardener.
/:cl:

Got tired of the Chaplain carrying a literal gardener's scythe, so I made a deliciously black staff version that glows red on the tip. It does in fact compile cleanly, and it showed the correct sprite in-game.

It looks less blood-soaked and more like a glow in-game, I swear.

Dream Maker Export:
  scythe-item

In-Game Still Image:
 scythe-ingame

Various In-Hand Images: 
scythe-inhand4
scythe-inhand
scythe-inhand2
scythe-inhand3

### CODE REVIEW

**Comment by ExcessiveUseOfCobblestone** [comment]
If it's suppose to pulse like that instead of look bloody, maybe have a bit of red pulse above the blade as well [kinda like the cult blade].

Anything besides gardener scythe is a 👍 in my book though.

**Comment by RemieRichards** [comment]
If you want, you can make it bigger than 32x32, might be nice if some of the chaplain's weapons got the XBAWKS HEUG treatment.

**Comment by KorPhaeron** [comment]
@RemieRichards 

Add the buster sword already I know you have the sprites

**Comment by RemieRichards** [comment]
@KorPhaeron pls no bully.

**Comment by Crushtoe** [comment]
@RemieRichards I think a 32x32 is sufficient.

**Comment by Niknakflak** [comment]
This sprite is just ok and the "blood pulse" effect looks kinda bad.  Should take remie's advice and get a fancy as fuck bigger than 32x32 sprite.

**Comment by Bawhoppen** [comment]
remove unnecessary changelog entry please

**Pull request merged**
