### PR TITLE
Adds the assembly shell

### PR DESCRIPTION
**Pull request by Y0SH1M4S73R**
## About The Pull Request

Adds the assembly shell, which can be attached to wires and other assemblies like proximity sensors, timers, etc. Because assemblies already have screwdriver interaction that gets overriden by the shell component, the regular assembly screwdriver interaction can also be performed with right-click. This can be seen on examine.

## Why It's Good For The Game

While currently, circuits can interact with wires and such using remote signalers and the radio component, this has its limits, such as the possibility that someone else uses the same frequency/code combo. With the assembly shell, you can put all your circuit logic into the attached assembly.

## Changelog

:cl:
expansion: Adds the assembly shell, available after researching the Advanced Shells tech node.
/:cl:

### CODE REVIEW

**Review by Twaticus — APPROVED** [review]

**Comment by KittyNoodle** [comment]
What does it look like

**Comment by Y0SH1M4S73R** [comment]
> 
> 
> What does it look like

I guess here's a picture of the sample colors.
image

**Comment by Y0SH1M4S73R** [comment]
> 
> 
> What does it look like

Here's the assembly shell sprite
image

**Comment by moocowswag** [comment]
Is it intended for them to not be attachable to grenade wires?

**Pull request merged**
