### PR TITLE
Advanced ProcCall improvements & Atom ProcCall

### PR DESCRIPTION
**Pull request by tkdrg**
You can now right click an atom to call a proc on it if you have +DEBUG.
Also cleaned up callproc() code a bit.

### CODE REVIEW

**Comment by Razharas** [comment]
Instead of reminding later ill add proposals here

**Comment by Razharas** [comment]
* Make it possible to select things in VV as srcs of advanced proc call

**Comment by optimumtact** [comment]
>trusting people with +debug

:sob:

**Comment by Cheridan** [comment]
Atom verbs are bad, as shown by @MrPerson https://github.com/tgstation/-tg-station/pull/4516 here.

**Comment by RemieRichards** [comment]
@Cheridan where in here is an Atom verb? these are all /client/proc

**Comment by Cheridan** [comment]
Oh, I assumed atoms were calling the proc, hence the name Atom ProcCall. Should be fine then.

**Pull request closed without merging**
