### PR TITLE
[READY]New shoulder holster sprite!

### PR DESCRIPTION
**Pull request by Tharcoonvagh**
## About The Pull Request
You can actually click on the sprite now

## Why It's Good For The Game
See above

I *think* it's compatible with #49245

## Changelog
:cl:tarchonvaagh
imageadd: new shoulder holster sprite!
/:cl:

Inspired by:
images

### CODE REVIEW

**Comment by HomocidlePancakes** [comment]
Never had problems with clicking it, but kay.

**Comment by Dorsisdwarf** [comment]
For some reason diffbot doesnt seem to work and I cant download the file?

**Comment by CRITAWAKETS** [comment]
image

here you go have a picture of new sprite

**Comment by trollbreeder** [comment]
I'm very not sure about the new sprite.

**Comment by Tharcoonvagh** [comment]
What do you propose instead

**Comment by trollbreeder** [comment]
If you're having difficulties selecting it, maybe add 1 alpha pixels around the holster vaguely in the color of the holster. Those should be _almost if not completely_ invisible but should still be treated as part of an item's "hitbox".

**Comment by trollbreeder** [comment]
Or you can do this
image
(Police gun holster)

**Comment by Tumesuo** [comment]
Can't aim mouse to sprite pls buff

**Comment by Tlaltecuhtli** [comment]
sprite looks like a sling

**Comment by PKPenguin321** [comment]
i think it's less that the sprite looks like a sling and more that real holsters are basically non-elastic slings

**Comment by Tharcoonvagh** [comment]
> i think it's less that the sprite looks like a sling and more that real holsters are basically non-elastic slings

is this a pro or a con?

**Comment by ShizCalev** [comment]
conflict

**Comment by Tharcoonvagh** [comment]
resolved

**Comment by Dennok** [comment]
Old
old

New
new

**Comment by Tharcoonvagh** [comment]
fuck

**Comment by Tharcoonvagh** [comment]
@itseasytosee mind if I resprite the syndie holster as well?

**Comment by Tharcoonvagh** [comment]
Uhh stalies?

**Comment by itseasytosee** [comment]
Yeah go for it

**Comment by Tharcoonvagh** [comment]
Aaaaa

**Review by itseasytosee — APPROVED** [review]

**Comment by Tharcoonvagh** [comment]
hello?

**Comment by itseasytosee** [comment]
git actions comes for us all.

**Comment by Tharcoonvagh** [comment]
ffda6a32a5a1387c001e46187f8ad944

**Comment by Tharcoonvagh** [comment]
Mmm yess

**Comment by adamkad1** [comment]
When did they make holster hold only one thing?

**Comment by Tharcoonvagh** [comment]
#49245

**Pull request merged**
