### PR TITLE
Adds two CA mapGenerators

### PR DESCRIPTION
**Pull request by AnturK**
Very simple cellular automaton modules. Absolutely basic implementation.
shot

### CODE REVIEW

**Comment by Supermichael777** [comment]
i assume this will help do something?

**Comment by optimumtact** [comment]
looks really nice

**Comment by RemieRichards** [comment]
:+1:

**Comment by tkdrg** [comment]
Whitespace conflicts, see orange's guide on how to fix them.

**Comment by optimumtact** [comment]
update to latest master
git rebase -Xignore-all-whitespace upstream/master

**Pull request merged**
