### PR TITLE
Slightly tweaks medigel ratios, changes instabitaluri description

### PR DESCRIPTION
**Pull request by googobbug**
## About The Pull Request

Slightly changes the contents of the roundstart medigels so they apply 2 units of medicine per spray rather than 1.6666 or whatever dumb number it was
Also changes the descriptions of instabitaluri sprays/patches to reflect the medicine's toxicity because C2s not telling you their downsides is bad

## Why It's Good For The Game

Minor polish

## Changelog
:cl: Bumtickley00
tweak: Slightly adjusted the dosage of brute/burn medigels
tweak: Changed description of instabitaluri sprays/patches to reflect the medicine's toxicity
/:cl:

### CODE REVIEW

**Comment by kriskog** [comment]
Give me some healing numbers here. How much do the old patches heal vs the new ones? How much organ damage on old vs new?

**Comment by AdmiralPancakes1** [comment]
Brute patch: 
Old: 30 brute, 3 liver damage
New: 60 brute, 6 liver damage

Burn patch:
Old: 10 burn, 1.25 eye damage
New: 40 burn, 5 eye damage (you don't start losing vision until 20 eye damage)

Compare with a trophazole pill (53 brute + extra healing from food) and a 10u spray from the rhigoxane bottle (50 burn, less if their clothes block part of the spray)

**Comment by kriskog** [comment]
Granibitaluri isnt included in that is it?

**Comment by AdmiralPancakes1** [comment]
It isn't, my bad. For the new patches, the best case scenario (the patient has 10 or less damage after the C2 is done) is that the granibitaluri heals a little over 5 brute and burn. In practice it's usually less.

**Comment by kriskog** [comment]
@ExcessiveUseOfCobblestone Thoughts? Brute seems a little high for just a patch, but :man_shrugging: 3u maybe?

**Comment by ExcessiveUseOfCobblestone** [comment]
the issue is the organ damage got overkilled, it needs to be bumped up a bit so it's not something you casually take. I'm fine with the healing output if the organ output became comparable.

In any case rn you could just as easily make your own patches of the amount desired now that MDs have ez chemmaster access so the shift between granib/C2 would be just determining how many iterations of the C2 you want to exist per patch for the defaults. If it's too strong because of the ratio, it's because the C2 itself is too strong.

My personal take is that the organ damage gets bumped up first then this PR gets relooked at to see if that's how many iterations of the chem we want to have per patch.

**Comment by AdmiralPancakes1** [comment]
Alright, I'll hold off on changing the patches then.

**Pull request merged**
