### PR TITLE
Removes Families

### PR DESCRIPTION
**Pull request by charlottesgit**
## About The Pull Request

	Removes Gangs. This is my first PR, might be a little sloppy and not full. 
	Removes the following:
	code/modules/antagonists/gang/gang.dm
	code/game/gamemodes/gang/gang_things.dm
	code/game/gamemodes/gang/gang.dm
	code/game/gamemodes/gang/gang_handler.dm
	Also Edits code/__DEFINES/role_preferences.dm
	Sorry if this sucks, just thought I'd do this and see if anyone wants it.
## Why It's Good For The Game

	Nobody likes this mode. They removed gangs, a good gamemode, for an RP based version of it that only belongs on Manuel.

## Changelog
:cl:
rcsdel: Families gamemode has been removed, due to unpopular reception.
/:cl:

### CODE REVIEW

**Comment by necromanceranne** [comment]
>nobody likes this mode

This is a deeply opinionated, do you have a thread discussing this to back this claim up?

**Comment by SweptWasTaken** [comment]
I agree with the pr

**Comment by Mycah142** [comment]
The salt is real. Incredible.

**Comment by Jared-Fogle** [comment]
Don't we have a poll up that's not even done yet that judges the fate of the mode?

**Comment by ArcaneMusic** [comment]
> 
> 
> Don't we have a poll up that's not even done yet that judges the fate of the mode?

There's a poll up that, **as quoted by the headmins**, was meant to judge player opinions of the gamemode. Nobody is discussing removing Families at this time.
And, on that note, sounds like a rash, opinionated PR that should really shouldn't be just pulled without any forethought.
Like, hell, unlike several other gamemodes in-game, goof is actively maintaining this mode, and perhaps instead of trying to remove it, you could instead try and provide some feedback on the linked feedback thread instead?
https://tgstation13.org/phpBB/viewtopic.php?f=10&t=25598
Anyway, I said my 2 cents.

**Comment by LemonInTheDark** [comment]
^ in addition, gangs were removed a long time ago. This isn't a replacement for that mode, it's an attempt by it's creator to do it right.

**Comment by MrMelbert** [comment]
image

**Comment by HAD848** [comment]
Look, I said I'd do this OOC on Sybil because every families round everyone complains about it. I just wanna see it gone, personally. Not up to me if this goes through or not, I honestly just wanna see how it goes.

**Comment by Doosteroni** [comment]
Haha that is not how this works. You can’t just remove an **Actively maintained**  game mode and expect it to get merged

**Pull request closed without merging**
