### PR TITLE
Adds flashdarks

### PR DESCRIPTION
**Pull request by PKPenguin321**
Like flashlights but they make darkness. Or do they suck light? Who knows!

# Youtube video of it in action: https://www.youtube.com/watch?v=VlbNj0Nr0dk
The video is sort of outdated and more accurate examples can be seen here: https://imgur.com/a/WQcFF

Changes:
- Tweaks flashlight code to make light power a var
- Adds code and sprites for flashdarks
- Currently not obtainable ingame, I was thinking traitor item or maybe R&D but I'd like to hear your thoughts

### CODE REVIEW

**Comment by Kraseo** [comment]
can you add flashbacks so i can go back to a time where you didn't exist

**Comment by Niknakflak** [comment]
Perhaps a little bit stronger seeing as the dark doesn't even follow the character super well, or due to the fact that places with lightbulbs or lightsources are basically uneffected making it so you'd need to break/turn those off anyway to get into darkness which eliminates the point of the darklight.

Also, buggy lighting doesn't quite follow you super well but that's lighting stuff in general so I dunno how to combat that stuff.

**Comment by Haevacht** [comment]
Deleted poly 👎

**Comment by PKPenguin321** [comment]
>Also, buggy lighting doesn't quite follow you super well but that's lighting stuff in general so I dunno how to combat that stuff.

This was recording lag :V

**Comment by Niknakflak** [comment]
oh ok

**Comment by xxalpha** [comment]
Deleted poly 👍

**Comment by ShadowDeath6** [comment]
it should be a tad stronger I think, if a shitty console light can blot out your high level R&D  / traitor item it's pretty bad

**Comment by WJohn** [comment]
cute idea, i guess? don't see much of a purpose as-is other than proving this is possible with the new lighting system.

**Comment by GunHog** [comment]
>cute idea, i guess? don't see much of a purpose as-is other than proving this is possible with the new lighting system.

NVG + high power flashdark = Combat advantage

**Comment by WJohn** [comment]
yeah i suppose that would be a cute advantage you could give yourself. okay, i give this a completely superfluous thumbs up.

**Comment by PKPenguin321** [comment]
Adjusted values a bit as per feedback, see a couple examples here: https://imgur.com/a/WQcFF

**Comment by scoopscoop** [comment]
What if it could blow out lights silently from a short distance away?

**Comment by AnturK** [comment]
I'll be frank there are times when you should ask "should i" not "can i". The plant genes are cancerous enough.

**Comment by xxalpha** [comment]
Yeah this is probably better as an april fools PR (turn every flashlight into flashdarks).

**Comment by PKPenguin321** [comment]
This is not nearly as potent as shadowshrooms and can be effectively beaten by a flashlight (or two if you're also in a completely dark area)

**Comment by bobdobbington** [comment]
Why would you make this less powerful than shadowshrooms? Shadowshrooms do not cost TCs and spread. This thing should be at least half again as powerful as a max potency shadowshroom if you expect tators to shell out for it.

**Comment by PKPenguin321** [comment]
Because not every feature that uses negative light has to be more powerful than the last?

**Comment by ShadowDeath6** [comment]
>make a tc traitor item or a high level R&D item
botany can spam mutagen on a mushroom and plant a single one that is stronger than the item

**Comment by PKPenguin321** [comment]
Nobody said it would be expensive for traitors or high level for R&D

And I think the shrooms comparison says more about how shitty botany is than it says about this

**Comment by ShadowDeath6** [comment]
if it's going to be a tc item it should be like 2 tc so you can meme and buy like 10 and become the void, that would be really fun

**Comment by PKPenguin321** [comment]
So this is pretty much good to merge, a real way to implement it can be added later. It might be awful so I want this to happen first so I can adminspawn it in now and then to kinda test.

**Comment by Tacolizard** [comment]
@PKPenguin321 @Niknakflak just interjecting here from beyond the grave to rub in some salt, if you guys had merged my lighting pr i made a couple months ago light would track perfectly to you.

**Pull request merged**
