### PR TITLE
Plasma cutters have double range in low pressure

### PR DESCRIPTION
**Pull request by ChangelingRain**
:cl: Joan
add: Plasma cutters(normal, advanced, and mech) now have double range in low pressure areas, but slightly lower range in high pressure areas.
/:cl:

Or in other words a standard cutter goes through 7 tiles of rock on lavaland, 4 otherwise, advanced goes through 10, 5 otherwise, and mech goes through 12, 6 otherwise.
Basically, super good for making single-tile tunnels.

### CODE REVIEW

**Comment by GunHog** [comment]
### Happy Squeals

**Comment by KorPhaeron** [comment]
do miners really need to able to cross the map that quickly

I mean I guess hypers already to that but still, you get 40 shots out of these for one sheet of plasma

**Comment by GunHog** [comment]
A miner would likely want this near roundstart, encouraging them to come by Science to ask for one and interact before heading off to ~~die~~ mine, or at least getting a tiny haul up in the first bit of the round. It is inspiring to have a miner talk with you at the beginning of the round, they are nice friends to have.

**Comment by Ergovisavi** [comment]
I'm not particularly entertained by the notion of killing _anything_ offscreen. Part of the reason I made the KA have a low range in the first place was because you actually had to interact with mobs instead of MLG 420 crossmap them.

**Comment by ChangelingRain** [comment]
Tuning; now the normal cutter is getting 2 more tiles instead of 5, advanced is getting 3 more, instead of 7, and mech is getting 4, instead of 8.

**Comment by Davdichan** [comment]
Plasma cutter damage is hilariously low, I don't think this is as bad as people think. Last I counted its 18~ shots to kill a goliath, and that's assuming everything hits, if you're firing at mobs off screen good luck ensuring or even knowing if your shots connected.

**Pull request merged**
