### PR TITLE
Humans and monkeys now breath all of the gas in their breath.

### PR DESCRIPTION
**Pull request by KazeEspada**
Humans and monkeys now breath all of the gas in their breath, if they breath it in the first place.
Any gas in their breath that they don't breath leaves their internals(think bubbles on a scuba gear).
Fixes 
Plasmamen no longer pollute the enviroment with their internals.

### CODE REVIEW

**Comment by duncathan** [comment]
About time someone killed `/6`
I didn't care enough to do it but thank you for proving to everyone who asked me how to fix the bug how easy it is to fix

**Comment by KorPhaeron** [comment]
>Any gas in their breath that they don't breath leaves their internals

>Plasmamen no longer pollute the enviroment with their internals.

It can't be both, can it?

**Comment by KazeEspada** [comment]
It can. If you gave a plasmameme a O2 tank, the O2 would not be removed from the breath. It would go onto the tile.
Oxygen breathing species would do the same with plasma if they were breathing from a Plasma tank.

**Comment by KorPhaeron** [comment]
Oh that makes sense. Cool stuff, thanks.

**Comment by SweaterKittens** [comment]
Thank you so much, this will fix one of the last major bugs with Plasmamen

**Pull request merged**
