### PR TITLE
Synth Creation Surgery[WIP]

### PR DESCRIPTION
**Pull request by GunHog**
Adds Synth Creation surgery!
<b>This is a work in progress. The code is not complete and contains only the basics to function. Not fully tested or balanced. This PR may be discarded based on feedback.</b>
Surgery steps not defined yet, that will be done later.

To create a Nanotrasen aligned Synth, you must insert a _positronic_ brain into a fully augmented, debrained corpse. The corpse must not have any physical damage, as the procedure is very delicate!

More to come once code is progressed. Please note that the current code is quite raw and not well polished. Expect bugs and mistakes!

### CODE REVIEW

**Comment by Niknakflak** [comment]
why though

**Comment by Zilenan91** [comment]
Is it even possible to get an undamaged corpse? Doesn't debraining do damage, so isn't this impossible since you can't heal dead bodies without magic

**Comment by GunHog** [comment]
Augs are repaired with welding and wires. Not sure if you can do that with a dead aug. *Untested code* baby

**Comment by Jalleo** [comment]
Heh

**Comment by KorPhaeron** [comment]
I think it'd be much more interesting to save synths for an antagonist or third party race.

I had vague plans for them and lavaland, which will be done in february (or whenever the freeze ends).

**Comment by Dorsisdwarf** [comment]
:-1: 
stop adding post-death backsies

**Comment by Jazaen** [comment]
Well, it already requires a posibrain, so it definitely is not easier than just stuffing that inside a borg/AI. As for returning them to life as humans, xenobio can do that with golems (that you can braintransplant into real humans, or just feed mutation slime thingy.

**Comment by The-Albinobigfoot** [comment]
Going to have to agree with Kor - having synths be a Terminator-esque race of robotic infiltrators is a far better use for them than yet another consolation prize for getting killed.
:-1:

**Comment by PKPenguin321** [comment]
Code looks like it checks out, although I'm not sure the augments are ever actually removed (but maybe that's intentional?).

It would be neat if you could emag posibrains to slave the synth to you.

**Comment by GunHog** [comment]
The augmentations are not removed when Synth is created. So they remain augs. Synth slaving sounds interesting, I welcome more feedback on that topic.

**Comment by Shadowlight213** [comment]
:-1: keep the Synths as an antag thing. Not another way to get back in the round.
Golems and borgs all have disadvantages compared to regular humans, and even if you make one into a human they are just a regular human.
Synths in the other hand are better than humans as they don't have to breath, and when combined with the augments will have pressure immunity and higher damage resistance.
So yeah don't turn what could possibly be an interesting antag race into yet another way to get back into the round.

@Jazaen I thought that the golem debraing was a neat little trick that could create some interesting scenarios. However if you're using that as justification that it's fine to let people rejoin the round as full fledged humans it sounds like that might need to be removed then.

**Comment by Jazaen** [comment]
It's not like I have done that in recent memory. Most people are content to stay as golem tide, and one RNG department to work with is enough for me. (Besides, for full back-into-round experience, you need at least two departments to cooperate, in this case HoP and xenobiology.)

**Comment by Shadowlight213** [comment]
@jazaen I know that. You were just using it as a justification for bringing people back in as full fledged humans. Which I don't think it is.

**Comment by GunHog** [comment]
To be honest, I was expecting a little more enthusiasm for this. Remember that there is a <b>military synth</b> variant which can be used for antagonists in Kor's lavaland, why can they not coexist?

I expect this to have quite the rarity, about half as common as augmentation is currently. Unlike assembling cyborgs, it is a long and tedius process to augment someone.

Them currently being augmented and such is something I can fix by deleting the old corpse and replacing it with a fresh one - the reason I have not done this previously is because I wanted to maintain the attributes of the body used (implants, cybernetic parts, etc).

Can any part of this be adjusted to be more acceptable, or am I just wasting my time with this feature?

**Comment by Zilenan91** [comment]
Actually GunHog, can you make it so the surgery specific to only a specific type of surgery drapes? What this would allow mappers to do is to make what is basically an uncanny valley away mission with player synths haunting its depths, harvesting unfortunate crewmembers who stray just a bit too far into the darkness.

**Comment by GunHog** [comment]
The current way of doing that is with the can_start() proc in surgeries. Such as for Abductors, only they can do experimental dissection, as the game checks the user for being Abductor or having one of their organs.

I could add drapes used to the argument of can_start() or some other way of checking. It depends on what exactly you intend to do.

**Comment by Shadowlight213** [comment]
@gunhog there were ideas tossed around for making surgery less tedious at one point with possibly a researchable auto surgery table. This pr will kill any possibility of that. Also I am completely against bringing people back into the round as full fledged humans. We have enough ways to get back in the round already that all have obvious tells and decreased ooc protection as they are coming back into the round.

**Comment by GunHog** [comment]
Clearly there is no support for this. Enjoy your salt and waiting in dead chat.

**Pull request closed without merging**
