### PR TITLE
Make wagging cat tails look gooder

### PR DESCRIPTION
**Pull request by EikoBiko**
## About The Pull Request

It makes the cat tails actually look like cat tails. Like this:

tail3

## Why It's Good For The Game

It makes the mandatory cat people less of an eyesore.

## Changelog
:cl:
tweak: altered the wagging cat tail sprite.
/:cl:

### CODE REVIEW

**Comment by Qustinnus** [comment]
thats cursed mate

**Comment by Qustinnus** [comment]
also ur a first time contributor so u probably didnt realize but u gotta ask permission from a maint before u make species PRs else they glare at u

**Comment by LemonInTheDark** [comment]
This requires permission from oranges, as it touches felinids

**Comment by EikoBiko** [comment]
> also ur a first time contributor so u probably didnt realize but u gotta ask permission from a maint before u make species PRs else they glare at u


>This requires permission from oranges, as it touches felinids

Glare at me all you want, I will glare back. Just take my better sprites you nerds.

**Comment by cacogen** [comment]
I strongly believe oranges will approve this

**Comment by NotRanged** [comment]
Help I can't stop staring at the way it lashes about I'm mesmerized this is dangerous

**Review by Twaticus — APPROVED** [review]

**Comment by itseasytosee** [comment]
A bad omen indeed

**Comment by cacogen** [comment]
Give them the Good First PR tag

**Comment by Twaticus** [comment]
@EikoBiko i really like this animation. would you be interested in making a low tail version and/or fluffy tail version for another project?

**Comment by bluetshirtguy** [comment]
cool sprite

**Comment by StarHorder** [comment]
wiggy waggy yes

**Comment by EikoBiko** [comment]
> 
> 
> @EikoBiko i really like this animation. would you be interested in making a low tail version and/or fluffy tail version for another project?

Sure, doesn't sound too hard! Let me know what the specifications of that are!

**Comment by wesoda25** [comment]
Rat　Smoking symbol
   RatSmoking symbol
　 Smoking symbol
　Smoking symbolRat
 Smoking symbol　Rat
Smoking symbol　　Rat
Smoking symbol　　Rat
 Smoking symbol　Rat
   Smoking symbolRat
　  Rat
　Rat Smoking symbol
 Rat　 Smoking symbol
Rat　　Smoking symbol
Rat　　 Smoking symbol
 Rat　  Smoking symbol
　RatSmoking symbol
     Smoking symbol
  Smoking symbol    Rat

**Comment by Acer202** [comment]
Any chance you could make the tail animation from the side a little thicker? It's quite a bit thinner than a stationary tail. 
smolwag

**Comment by interestingusernam3** [comment]
░░░░░▄▄▄▄▀▀▀▀▀▀▀▀▄▄▄▄▄▄░░░░░░░
░░░░░█░░░░▒▒▒▒▒▒▒▒▒▒▒▒░░▀▀▄░░░░
░░░░█░░░▒▒▒▒▒▒░░░░░░░░▒▒▒░░█░░░
░░░█░░░░░░▄██▀▄▄░░░░░▄▄▄░░░░█░░
░▄▀▒▄▄▄▒░█▀▀▀▀▄▄█░░░██▄▄█░░░░█░
█░▒█▒▄░▀▄▄▄▀░░░░░░░░█░░░▒▒▒▒▒░█
█░▒█░█▀▄▄░░░░░█▀░░░░▀▄░░▄▀▀▀▄▒█
░█░▀▄░█▄░█▀▄▄░▀░▀▀░▄▄▀░░░░█░░█░
░░█░░░▀▄▀█▄▄░█▀▀▀▄▄▄▄▀▀█▀██░█░░
░░░█░░░░██░░▀█▄▄▄█▄▄█▄████░█░░░
░░░░█░░░░▀▀▄░█░░░█░█▀██████░█░░
░░░░░▀▄░░░░░▀▀▄▄▄█▄█▄█▄█▄▀░░█░░
░░░░░░░▀▄▄░▒▒▒▒░░░░░░░░░░▒░░░█░
░░░░░░░░░░▀▀▄▄░▒▒▒▒▒▒▒▒▒▒░░░░█░
░░░░░░░░░░░░░░▀▄▄▄▄▄░░░░░░░░█░░

**Comment by EikoBiko** [comment]
> Any chance you could make the tail animation from the side a little thicker? It's quite a bit thinner than a stationary tail.
> smolwag

Yep! I'll do that when I get home from work, no problem. Will be several hours though.

**Comment by ArcaneMusic** [comment]
I definitely like the kinetics of the sprite better than the old one from an art standpoint, seems neat.

**Comment by zombiegums** [comment]
Cute!

**Comment by Timberpoes** [comment]
I like the style of it. Feels swooshy.

**Comment by EikoBiko** [comment]
> 
> 
> Any chance you could make the tail animation from the side a little thicker? It's quite a bit thinner than a stationary tail.
> smolwag

Okay done! Beefed up both of them so they should be more consistent with the static sprites.

tail4

**Comment by LemonInTheDark** [comment]
Scratch that, it just needs maintainer approval ~~please don't kill me orange man~~

**Comment by Acer202** [comment]
> Okay done! Beefed up both of them so they should be more consistent with the static sprites.
> 
> tail4

You're a legend! Thank you.

**Comment by Jared-Fogle** [comment]
art lead likes it, whatever

in the future ask maintainers for approval on prs like this

**Comment by Twaticus** [comment]
@EikoBiko coolio my discord is TWATICUS#0784 if youre still interested

**Comment by cacogen** [comment]
We know that slippery slope fallacy is just a fallacy so why does it keep happening

**Comment by Autisem** [comment]
@EikoBiko you OK if I port it to bee?

**Pull request merged**
