### PR TITLE
Changes the acronym of the Enhanced Interrogation Chamber

### PR DESCRIPTION
**Pull request by ATH1909**
## About The Pull Request

The Enhanced Interrogation Chamber's name has been changed. It is now the Enhanced Prisoner Interrogation Chamber.

## Why It's Good For The Game

Let's say, someone has added a machine to the game. Let's also say, hypothetically, that this machine's acronym was one letter off from being a very cool word. Okay, and if this machine's acronym went from not being a very cool word to being a very cool word, then that would improve the game that that machine was in, right? So, therefore, adding a letter to that machine's acronym by adding an extra word to its name would improve the game that that machine was in.

Logically, then, adding an extra word to the name of the Enhance Interrogation Chamber would improve SS13.

## Changelog
:cl: ATHATH
tweak: The Enhanced Interrogation Chamber's name has been changed. It is now the Enhanced Prisoner Interrogation Chamber.
/:cl:

### CODE REVIEW

**Comment by ATH1909** [comment]
Note that only the name of the EIC has been changed; the name of the act of interrogating someone in an enhanced manner has not been changed, so things like the name of the "Begin Enhanced Interrogation" button in the EIC's interface have not be changed.

**Comment by AutisticFroggy** [comment]
Epic

**Comment by necromanceranne** [comment]
This is not epic. This is cringe.

**Comment by lolman360** [comment]
yeah ok anne

**Review by Timberpoes — CHANGES_REQUESTED** [review]
Linter error:
```
Error: our build differs from the build committed into git.

Please rebuild tgui.
```

Please rebase your branch and rebuild tgui

**Comment by SpaceManiac** [comment]
Thumbs-down from me, "enhanced interrogation" is a real-world euphemism which this change disrupts

**Pull request closed without merging**
