### PR TITLE
Buffed medigun healing to 5 per tick

### PR DESCRIPTION
**Pull request by ghost**
:cl: More Robust Than You
balance: The medibeam gun should now heal faster
/:cl:

why: people complained on the discord about it being too slow

### CODE REVIEW

**Review by Tlaltecuhtli — APPROVED** [review]

**Comment by Robustin** [comment]
>Listening to people on Discord

It's an automatic beam, you don't even have to hold the damn thing, and it heals up to 8 damage per tick.

**Comment by coiax** [comment]
For 12 TC, the medibeam gun has always felt very underwhelming.

**Comment by Bawhoppen** [comment]
It's like the most OP thing nukeops get, don't buff it

**Comment by MoreRobustThanYou** [comment]
@Bawhoppen no it isn't. You can only safely have one active on screen at a time (else you risk accidental crossing of the beams), it's hard to fight when one hand is occupied by a medigun, and the beam will be cut off by solid objects

**Comment by Buggy123** [comment]
TBH its kinda shit yeah :+1:

**Review by ShizCalev — APPROVED** [review]

**Comment by KorPhaeron** [comment]
It basically eliminates damage attrition as a concern for the team, how is that shit?

If you want something that tanks gunfire get the double eblade or shield suit

**Comment by coiax** [comment]
The biggest risk to a nuke op is a stun and drag. Not chip damage. 14 TC spent not on adrenals, that require someone to hang back and not participate in shooting people running at you means you're overall weaker.

**Comment by Buggy123** [comment]
Also, everyone, this is a 20% buff. It currently heals 4 per tick, now it heals 5. It's not going from 1 to 5 or something.

**Comment by ShizCalev** [comment]
The intent is to provide players with a sense of pride and accomplishment for being able to strategize and accomplish their goals without them having to rely on one set of absolutely optimal unlocks for them to have to defeat the crew. If you're able to simply shrug off all the damage that the crew can throw at you, there's really no point in not getting this, and it'd simply become a psuedo requirement to purchase this whenever play ops, lest you get criticized by both your team and OOC.

Just pull back into cover, heal up for a few extra seconds, and then resume your murder rampage against the crew; the damage _will_ be healed.

**Pull request closed without merging**
