### PR TITLE
Orangifies Current Skills (Slightly Slower at Noob, Faster at High Lvl)

### PR DESCRIPTION
**Pull request by ExcessiveUseOfCobblestone**
## About The Pull Request

Brings current skills in line with how oranges would prefer skills to work. Lower skills are now slower than base and you will achieve better than base as you progress. 

Basically skills are now an embedded part of the actions' progression instead of an added bonus.

Mi = Mining, Me = Medical

  | Mi-Current | Mi-PR | Mi-Diff | Me-Current | Me-PR | Me-Diff
-- | -- | -- | -- | -- | -- | --
Noob | 1 | **1.1** | 9.52 | 1 | **1.1** | 9.52
Novice | 0.95 | **1.05** | 10.00 | 0.95 | **1.05** | 10.00
Apprentice | 0.9 | **0.9** | 0.00 | 0.9 | **0.9** | 0.00
Journeyman | 0.85 | **0.8** | 6.06 | 0.85 | **0.8** | 6.06
Expert | 0.75 | **0.75** | 0.00 | 0.75 | **0.75** | 0.00
Master | 0.6 | **0.6** | 0.00 | 0.6 | **0.6** | 0.00
Legend | 0.5 | **0.4** | 22.22 | 0.5 | **0.4** | 22.22

## Why It's Good For The Game

Doesn't make skills just upgrades, as one now has to put in the work to use items at their "base" stat.

## Changelog
:cl: Cobby
balance: All current skills now give slower than base speeds at "noob" levels but are faster as you get to the more advanced levels. See PR for actual breakdown.
/:cl:

### CODE REVIEW

**Comment by Fikou** [comment]
why did you make that mining and medical part of the thing if they both have the same times

**Comment by itseasytosee** [comment]
You have just effectively lowered the "base stat" nothing was gained

**Comment by ExcessiveUseOfCobblestone** [comment]
> 
> 
> why did you make that mining and medical part of the thing if they both have the same times

they were initially different on my first pass and i didn't want to remake the table lol.

> 
> 
> You have just effectively lowered the "base stat" nothing was gained

Legendary has been made faster and the base stat is the numerical speed prior to skill adjustment which wasn't touched.

**Comment by Mickyan** [comment]
I dont really understand what you mean by "base value" from a mechanical perspective, if everyone starts at noob value then that's functionally the base level and this just seems to make the values more confusing to read in code

**Comment by 4dplanner** [comment]
> I dont really understand what you mean by "base value" from a mechanical perspective, if everyone starts at noob value then that's functionally the base level and this just seems to make the values more confusing to read in code

are skills able to be disabled via config? If so, base value matters.

**Comment by MrPerson** [comment]
It feels kind of weird to me that skills don't actually hit the "1x base level" at any time. This means you have to balance around modifiers to that base level. I'd prefer if the 1x was whatever skill the relevant job spawns with that skill and then increase/decrease from there.

**Comment by ExcessiveUseOfCobblestone** [comment]
yes that's a better way to approach it

**Pull request closed without merging**
