### PR TITLE
Fixes spellbook refund issue

### LINKED ISSUE #11325: Wizerds can refund spells with more than one point invested receve all points back and invest 1 point for that level
Wizards with almost max tier in 5 spells
this is terible

### PR DESCRIPTION
**Pull request by AnturK**
Fixes #11325

### CODE REVIEW

**Comment by Jalleo** [comment]
RIP boss wizard

**Comment by Incoming5643** [comment]
I didn't know this was never fixed. Whoops.

**Comment by AnturK** [comment]
Yeah i completely forgot about this, someone saying he had spellbook issues yesterday reminded me.(also firecage should test  automatic changes)

**Comment by Miauw62** [comment]
>this wasnt quickmerged

**Pull request merged**
