### PR TITLE
Remove healing skill

### PR DESCRIPTION
**Pull request by Mothblocks**
## About The Pull Request
Removes the healing skill, and by effect dissection surgery and the legendary healer's cloak.

Requested by @ExcessiveUseOfCobblestone 

## Why It's Good For The Game

As stated before, this was requested by Cobby, but I'd like to throw my thoughts down here **and why I'm opting for a hard removal**.

1. In its current form, it is not an accurate measure of anything other than how hard you are focusing on the skill specifically.

I am regularly in medbay healing everyone who comes in of any ailments for upwards of an hour and a half, and I've never gotten anywhere close at all to the higher skill levels. I don't think I've even gotten close to master. None of the medical mains I know of that do the same have gotten anywhere close either. Call me an egomaniac, but to me it's pretty clear that doctors that do their jobs aren't mixing well with the skill.

2. Any changes at all would be powergamed.

This is a fault of the skills system as a whole, really. Any metric used to reward doctors for doing their job, or whatever else the skills system is meant to be doing, would have some way to powergame it, or would be totally worthless. This wouldn't be a major issue, except...

3. Powergaming of the healing skill means spending time not actually helping players

The janitor and gaming skills both come to mind as skills that can be easily powergamed. While it detracts from whatever the point of the system is, it's not really harmful since the worst that usually happens is the janitor isn't cleaning up messes, and some assistant isn't spending time breaking into the brig because they're too busy shooting themselves in The Orion Trail.

When a doctor is powergaming the healing skill, it is actually detrimental to the rest of the crew. Instead of spending their time healing actually players or in the case of paramedics, helping people that are hurt, they're spending it dissecting a body or doing some weird thing like putting a body over a bonfire and tending wounds. You could argue this should be treated as part of the triage process, but "not healing players" isn't fun for anyone.

It's not healthy to reward medical staff for not doing the one job they're supposed to be doing, actually helping people.

4. The benefits it gives aren't very useful to begin with

I'm somewhat talking out of my ass here since again, I've never gotten anywhere close to the higher levels of the skill, but the healing skill grants the player faster surgeries and better probabilities. Except perhaps if you're a paramedic, where you're not really designed to be healing someone all the way back on the field anyway, neither of these are very useful. In normal shift to shift work, surgeries messing up is not a big concern. Either you're on a stasis bed/operating table, or you're doing some quick on the field work where you don't have to do much anyway. There's already a time gate for making the surgery process faster, it's the experimental tools, advanced surgeries, etc. R&D can even sometimes produce the alien tools, which are much more fun than doing surgery faster just because you spent a long time dissecting a body.

## Changelog
:cl:
del: Removed the healing skill, and by effect dissection surgery and the legendary healer's cloak.
/:cl:

### CODE REVIEW

**Comment by WarlockD** [comment]
I always thought one way to anti powergame it would be to base experience on complete surgerys instead of just "on tool use" and not including would surgery experience on that.  The power gaming way is to stack a bunch of corpses on a table and just would repair all of them while they are on fire.  Yea its stupid and I hated it.  Especially since the reward isn't that great.

Maybe a score system would be better.  How many surgerys a doctor has done, revives, cpr, etc.  Maybe he can get the cloak if he has revived 10 different people with minds.  Of course he can't shock the same guy 10 times, maybe a cooldown of 5-10 min for it to count on the same person.

On that note, we could count how many times a sec has batonned someone with an arrest status hah.

**Comment by GhostEcho** [comment]
The cloak is nice though, removing it feels kinda shit when the amount of doctors who are powergaming is maybe 1 every 10 rounds to get the cloak, and usually there are other docs anyways,

**Comment by PKPenguin321** [comment]
Dissection surgery may swing back around once R&D gets revamped to require it as an unlock component

**Comment by Jared-Fogle** [comment]
> The cloak is nice though, removing it feels kinda shit when the amount of doctors who are powergaming is maybe 1 every 10 rounds to get the cloak, and usually there are other docs anyways,

Anecdotal of course, but I've never seen the cloak other than on people who I saw in the beginning doing some weird way to get it fast, and even then it's after a significantly long time.

I like the cloak as an accessory, but not in its current form. Perhaps a later PR could add it as something like the veteran's cloak, where if you have X crazy amount of hours in medical, you get it?

**Comment by Jared-Fogle** [comment]
> Dissection surgery may swing back around once R&D gets revamped to require it as an unlock component

It can be added back in whatever PR does that then--I don't want a surgery that does nothing until some later content update.

**Comment by necromanceranne** [comment]
The skill experience generation has been nerfed so significantly, even when I was using alien dissection I only seemed to make reasonable progress when I was using golem corpses, which are extremely rare and difficult to obtain unless you're forcing a golem to swap bodies constantly. The alternative therefore was using slimepeople.

Essentially, unless you use xenobio powergay, this skill is practically unable to be researched via the department that actually benefits from it. I have never, over the course of standard play as a paramedic who uses surgery constantly and am routinely doing so to stop people wasting medical supplies or taking a long trip back to medical, and would dissect morgue bodies when I had downtime, level up my skill beyond novice, and felt no reasonable reward for even achieving that. It's kind of crummy as a skill you can level.

The only redeeming feature would be keeping it as a skill only doctors and medical staff have any skill in, and not something you can level. But because /tg/ are extremely adverse to the idea of not being able to be equal to everyone else in everything they do, we'll probably not see a change like that happen.

**Comment by Tharcoonvagh** [comment]
Why only remove healing? Skills are dumb and pointless, SS13 ain't some MMORPG

**Comment by GhostEcho** [comment]
> Why only remove healing? Skills are dumb and pointless, SS13 ain't some MMORPG

Mining skill provides some incentive to NOT use the plasma cutter since it doesn't provide mining experience, and does help noticeably with using the less efficient tools for mining. 

Quite frankly though re reading through the PR again, I'm failing to see what issue this is actually addressing. How many times does a doctor actually try to "powergame" the medical skill across all the different servers? I can't speak for the others, but those doctors are essentially non existent on Bagil from the rounds I've been able to see. Bagil is a fast paced server though, so people likely realize they don't have enough time to try and grind for it.

In my opinion just play with skill gain on it rather than just removing something you've admitted to not using much of, granted at request of Cobby, but it doesn't make it better.

**Comment by Jared-Fogle** [comment]
> How many times does a doctor actually try to "powergame" the medical skill across all the different servers? I can't speak for the others, but those doctors are essentially non existent on Bagil from the rounds I've been able to see. Bagil is a fast paced server though, so people likely realize they don't have enough time to try and grind for it.

Hello, I play Bagil doctor nearly exclusively and see this frequently.

> In my opinion just play with skill gain on it rather than just removing something you've admitted to not using much of, granted at request of Cobby, but it doesn't make it better.

See points number 2 and 3.

**Comment by Tlaltecuhtli** [comment]
ngl if you are wasting 20min for some extra speed that is gonna be kinda useless when station reaches high chaos stage, instead of just prepping shit like chempills/cmc hawking/building extra beds / clicking tend wounds research ur dumb

also i see u wrote that "you never reached the legendary level" well i see you dont play the game often the "clf3 monky technique" which i invented isnt that great anymore when xp got changed and its better to do the augment surgeries which give 50ish xp and you need 2500 for legendary, which i think is fine as its a benefit for both parties to do during downtime and are rarely done.
i think this workframe could be used in the future for like super magic special surgerys which would require you to have mastery etc and the cape looks cool 
i dont see why remove

**Comment by Jared-Fogle** [comment]
> also i see u wrote that "you never reached the legendary level" well i see you dont play the game often 

I think you're missing the point I was making if your response is then explaining a strategy to game the system rather than its intended purpose of rewarding people doing medical normally.

**Comment by wabash1** [comment]
Why not rework the healing skill into being gained only by working on unique actual humans but make it faster overall? You fix up 30(arbitrary #) random people you get the cloak

**Comment by Fhaxaris** [comment]
A possible solution is to have diminishing returns on healing the same mobs by storing them in a list and reducing the xp gain based on how many times you've healed that mob before. I don't think it'll be that hard to implement.

**Comment by ExcessiveUseOfCobblestone** [comment]
Even if you changed healing surgery so people will have to move to something else, the premise behind it is people will be not doing their job to get skill so they can do the job they arent doing better.

**Comment by WarlockD** [comment]
Like is said a point or merrit system for the cloak.  Based not on tool use but how many surgery's revives etc.

**Comment by HiKewne** [comment]
Very based, also very true in every single point made.

In any case you could always heal at max speed by just getting the surgical arm so the whole tending wounds farming was always kinda dumb when we have t e c h n o l o g y.

**Comment by Dennok** [comment]
Why not just remove speed multiplier ?
And lost skillcape for ones who want fluff item that show that is autises half of hour for  for fancy cloak.

**Pull request merged**
