### PR TITLE
Makes stations more airtight

### PR DESCRIPTION
**Pull request by LemonInTheDark**
## About The Pull Request

I've gone through delta, meta, and icebox and added some choice windoors, changed some areas around, added some more doors, and changed some other miscellaneous things.

I'll list the full changes in drop downs, for both our sakes

Delta:
<details>
Splits the central hallway into fore and aft central hallways

Adds the spaces that jut out of medbay and sci into the central hallway, rather then having them be a part of
medbay and sci

Adds medbay access locked windoors to the back desk of the medbay reception area

Adds airlocks to both the upper and lower parts of the main hallway
</details>

Meta:
<details>
Gives the storage wing another set of firelocks, and two fire alarms. It didn't have any alarms in the first place, so hopefully this helps things

Adds the spaces that jut out of medbay and sci into the central hallway, rather then having them be a part of
medbay and sci

Replaces a small bit of the science area with nanite lab, to prevent a breach near xenobio causing fire alarms
at the front of sci

Adds a windoor in front of the ORM to block air

Adds a wall behind a smart fridge in chemistry
</details>

Icebox:
<details>
Added airlocks between arrivals and the port hallway, and the escape hallway and the starboard hallway

Added a windoor between the kitchen and the bar
</details>

## Why It's Good For The Game

Cuts delta's main hallway in half, with the goal of reducing fire alarm strain. Some thoughts on this would be nice, I don't want to make everything else that uses areas worse just because fire alarms are dumb, and I'm worried that's what I've ended up doing here.

I've also added the portions of medbay/sci that jut out into the main hallway into the main hallway, I think? I could make these into lobby areas, but I'm not sure if that's appropriate or not.

Adds a few windoors and airlocks to better section off portions of the station, this should reduce the amount of mass gas spreading that can occur.

My goal here is to reduce the amount of uninteresting gas movement and make firelocks less hellish when there's a breach

## Changelog
:cl:
add: Adds some windoors and airlocks to better deal with gas movement
add: Shifts some of delta's areas around, hopefully this reduces mass fire alarm spam
/:cl:

### CODE REVIEW

**Comment by Serxule** [comment]
if you could, change firelocks to the dual ones (like beestation, etc), it's already in code (I think) and would help a lot

**Comment by LemonInTheDark** [comment]
> 
> 
> if you could, change firelocks to the dual ones (like beestation, etc), it's already in code (I think) and would help a lot

I don't like the idea of locking down breaches/dangerous areas that hard, even dual firelocks in the monstermos style is kinda odious, but they go to even further extremes to prevent their atmos system from doing much. See the window firelocks and such.

That's not to say I like how things are currently, I'd like to strike a middle ground rather then going all in on sealing off breaches.

**Comment by Tlaltecuhtli** [comment]
i did some math and one major problem is that refilling an area takes too much time which ends in shuttle call for 1 simple bomb or a simple broken window in maint which ends up sucking all air because someone opened to there.

to fill a tile with air requires 100 mol of standard temp air gas, an air canister contains 1500 mol which is 15 tiles. even the smallest department is a whole screen big, which is  9x9 aka 81 tiles, you need 7 canisters to refill it (fixing pipes requires even more time 1h+) and even 1 single idiot entering the room before all holes are fixed will create more rooms instantly vented to the point its impossible to drag that many air cans, you are better off walling off all the areas that go there and just call shuttle

maints need a minimal firelock system, they are large and give no warning to anyone opening the door which leads to 200+ 0  pressure tiles normalizing with the hallway and pooof shuttle call before even the antags kill anyone caused by space sand

**Comment by Serxule** [comment]
> shuttle call for 1 simple bomb or a simple broken window in maint which ends up sucking all air because someone opened to there.

this sorta extends on my point, is that we _need_ a very strong firelocks/breach system due to the fact that, in a past round, a _**SINGLE**_ broken window depressurized 90% of the station and got the shuttle called, which is unacceptable in any standards, which is why I constantly say we need the dual firelocks which would fix that major issue

**Comment by LemonInTheDark** [comment]
> 
> 
> i did some math and one major problem is that refilling an area takes too much time which ends in shuttle call for 1 simple bomb or a simple broken window in maint which ends up sucking all air because someone opened to there.
> 
> to fill a tile with air requires 100 mol of standard temp air gas, an air canister contains 1500 mol which is 15 tiles. even the smallest department is a whole screen big, which is 9x9 aka 81 tiles, you need 7 canisters to refill it (fixing pipes requires even more time 1h+) and even 1 single idiot entering the room before all holes are fixed will create more rooms instantly vented to the point its impossible to drag that many air cans, you are better off walling off all the areas that go there and just call shuttle
> maints need a minimal firelock system, they are large and give no warning to anyone opening the door which leads to 200+ 0 pressure tiles normalizing with the hallway and pooof shuttle call before even the antags kill anyone caused by space sand

As it applies to maint freezing I somewhat agree with you, I think some sections of maint (Especially delta) need to be significantly more broken up.
The rest of your statement assumes that space instantly jettisons all gas, which is just not true. Spaces get colder much faster then they lose moles, so it's more an issue of heating them up.

>This sorta extends on my point, is that we need a very strong firelocks/breach system due to the fact that, in a past round, a SINGLE broken window depressurized 90% of the station and got the shuttle called, which is unacceptable in any standards, which is why I constantly say we need the dual firelocks which would fix that major issue

As I said before I don't want to go that far into making space easy to deal with. My plan is to give atmos techs better tools for solving air problems, and refocus their gameplay towards dealing with these things, rather then making the issues less present.

The goal of this pr is to reduce some of the dumb behavior around station wide firelocks on particularly delta, and the nuking of portions of the station that really shouldn't have the same airspace.

This isn't really the most productive place to discuss more general atmos woes, if you've got more general feedback like this I'd recommend leaving it on the forum thread https://tgstation13.org/phpBB/viewtopic.php?f=10&t=28421

**Comment by Tlaltecuhtli** [comment]
by time someone with a suit comes and start repairs at least 3 min have passed and the 3x3 hole will jettison the gas

**Comment by itseasytosee** [comment]
>adds fire alarms

👎

**Comment by TheBonded** [comment]
> by time someone with a suit comes and start repairs at least 3 min have passed and the 3x3 hole will jettison the gas

If you wait for someone with a suit then that's on you, if I see a breach smaller than 12 tiles I grab some nearby metal (deconstruct chairs or something) and I make some iron rods and use nearby floor tiles to patch it up. I know that I have at least 45 seconds in a fully depressurized room (longer if I wear a firesuit) which is more than enough time to fix a breach

**Review by Twaticus — APPROVED** [review]

**Comment by LemonInTheDark** [comment]
😭

**Comment by Cyberboss** [comment]
I see approval, I merge

**Comment by LemonInTheDark** [comment]
~~it needed inept~~

**Pull request merged**
