### PR TITLE
Removes zombies from xenobio

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
Probably not a great idea

### CODE REVIEW

**Comment by LanCartwright** [comment]
It's shit. trust me. remove/event only.

**Comment by GunHog** [comment]
No fun :(

**Comment by KorPhaeron** [comment]
@GunHog 

The vote to keep/remove them on the server was dead even and I don't have the energy to deal with trying to balance them/getting yelled every time they kill someone

**Comment by KorPhaeron** [comment]
Actually I just realized xenobio has already been able to do this with spiders forever I'll just nerf zombies so they're easier to contain the spread of

**Comment by Zilenan91** [comment]
Would making them slightly slower but having way more health balance them? Like we're talking Xeno Sentinel health.

**Comment by KorPhaeron** [comment]
@Zilenan91 

I was gonna make them slower and leave health the same, they multiply pretty rapidly.

I'm not sure if people are gonna have the patience for balancing them though

**Comment by Zilenan91** [comment]
Yeah I think the health is fine as it is actually. Slowdown 2 is only miner hardsuit slow, which isn't even that slow to begin with, so slowdown 2 might balance them? If all else fails consider nerfing their damage down to 15 or 18 so they don't 5 hit people.

**Comment by KorPhaeron** [comment]
Kneejerk response to this happening two rounds in a row, failed to happen the rest of the day.

I'll try toning them down a bit and re-open it if its still a big problem

**Pull request closed without merging**
