### PR TITLE
Removes baseball bat knockback

### PR DESCRIPTION
**Pull request by Iamgoofball**
> easily constructable 10 force KNOCKBACK ON HIT spammable with good throwforce weapon

:cl: Iamsaltball
tweak: Removed the knockback from baseball bats
/:cl:

### CODE REVIEW

**Comment by PKPenguin321** [comment]
oh dude we got baseball bats? sweet

**Comment by Zilenan91** [comment]
Can you buff the force to 15 or so since a 10 brute weapon that actually costs things to create is pretty useless

**Comment by jughu** [comment]
>not adding a plasteel version which does 21 brute

**Comment by ChangelingRain** [comment]
The only useful thing the knockback does is let you chainstun people by slamming them into walls which is hilarious but also basically a 20 force stunbaton

**Comment by lzimann** [comment]
just make it harder to make then

**Comment by bobdobbington** [comment]
Yeah, make this require logs and the autolathe, don't ruin spaceball forever

**Comment by MMMiracles** [comment]
I still say they should hit back stuff thrown at you instead of hitting people away. Being able to chain-stun people with walls is hilariously overpowered.

**Comment by jughu** [comment]
>clown throws pie at you you hit it back into his face Checkmate

**Comment by optimumtact** [comment]
Make it apply to mob size so you can still play droneball but it's not relevant to normal sized mobs like humons

**Comment by optimumtact** [comment]
Goof pls

**Comment by Iamgoofball** [comment]
i will when I get home from work today, sorry I got distracted by 60 FPS last night

**Comment by KorPhaeron** [comment]
someone who isn't goof should do this

goof should finish guncrafting

**Comment by kilog** [comment]
dunked

**Pull request closed without merging**
