### PR TITLE
Necropolis floors and walls

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
learn how to fucking embed

### CODE REVIEW

**Comment by Razharas** [comment]
MAKE THEM SMOOTHE

**Comment by TechnoAlchemisto** [comment]
squelch

**Comment by KorPhaeron** [comment]
you make them smooth

**Comment by KorPhaeron** [comment]
@WJohn

**Comment by WJohn** [comment]
Smoothing is gonna be a pain in the arse but I can do that after I finish my lavaland remap and incoming's lizard sprites and probably a lot of xeno shit so not very soon.

**Comment by KorPhaeron** [comment]
I was more asking if you approve and suggesting copypasting this for your branch and using it in your remap

**Comment by WJohn** [comment]
I can add these after my remap is merged. There's a lot more tweaking to be done there.

**Comment by Aloraydrel** [comment]
Hope it makes a squishy sound when you step on it ;)

**Comment by Steelpoint** [comment]
I know this is not a map edit but the machine that spawns behind the door should be moved somewhere that can't be seen.

otherwise this is a good sprite change.

**Comment by Dorsisdwarf** [comment]
JESUS CHRIST

**Comment by Cheridan** [comment]
floors might be too bright and busy to come across well during play

**Comment by Sammaell** [comment]
Well. The walls look stupid. We need more sprites, like in normal station wall.

**Comment by optimumtact** [comment]
Creeps me out

**Pull request merged**
