### PR TITLE
Gives sec jackboots shoelaces you can untie and/or knot

### PR DESCRIPTION
**Pull request by L0pz**
## About The Pull Request

I really, really want to be able to untie unassuming secoffs' shoes and after consulting the discord, I believe others do too.
## Why It's Good For The Game

Funny
## Changelog
:cl:
add: Security jackboots now have shoelaces which may be untied and/or knotted.
/:cl:

### CODE REVIEW

**Comment by Sadboysuss** [comment]
Jackboots take more time to strip than normal shoes, so it should be the case for untying shoelaces too, I think.

**Comment by L0pz** [comment]
> Jackboots take more time to strip than normal shoes, so it should be the case for untying shoelaces too, I think.

Yeah regular shoes take 5 secs to untie while these take 10

**Comment by SomeoneYouProbablyKnow** [comment]
Can't wait for someone to make an argument "if you give sec normal boots they'll have to kill shoe thiefs in self defence"

Great pr, sec shouldn't have had special hugbox boots to begin with.

**Comment by Iamgoofball** [comment]
sec shoes are velcro because they dont know how to tie their shoes 👎

**Comment by projectkepler-ru** [comment]
> sec shoes are velcro because they dont know how to tie their shoes 👎

what if they still use the tied boots type because it's cheaper or something

**Comment by iwishforducks** [comment]
> sec shoes are velcro because they dont know how to tie their shoes 👎

so shouldn’t you be able to rip the velcro in the split of a second if that was the case

**Comment by Exester509** [comment]
> 

Mountain gear and industrial equipment also use laces for similar reasons. Laces also resist strong pulls better than velcro.

**Comment by Loafin34** [comment]
sec shoes are welded down to the officer

**Comment by TheVekter** [comment]
+2

Anything that makes security's lives slightly more inconvenient is worth it in my book.

Not harder, just more inconvenient.

**Comment by DaydreamIQ** [comment]
Ain't there a level of tie shoes that specifically targets jackboots? Might have to trim that down a bit if one of the levels is gonna be useless now

**Comment by Iamgoofball** [comment]
change all the flavor text to fucking with the velcro straps on the boots and you've got my support

**Comment by nukularpower** [comment]
thought this was bringing back noisy jackboots for a minute, sadness

**Comment by SomeoneYouProbablyKnow** [comment]
There something to be said about velcro being easier to use in 0g. Also yes noisy jackboots my beloved

**Comment by CCC23** [comment]
hit this man with the shoelace goblins

**Comment by DrDiasyl** [comment]
Update the sprites to indicate very important addition of shoe laces to the jackboots

**Comment by SomeoneYouProbablyKnow** [comment]
Gotta add the 2000 cr special powergaming shoelaces less jackboots to the secvendor. Have to keep the economy running

**Comment by githubuser4141** [comment]
> 

so, it's not military grade because Security is not military, they are mall cops that spend 99% of their time in a dry, temperature regulated indoors environment. Also material science has advanced massively in the _500 years_, try having a civilization 500 years ago (IRL time) understand a modern jet engine.

**Comment by deathrobotpunch** [comment]
> so, it's not military grade because Security is not military, they are mall cops that spend 99% of their time in a dry, temperature regulated indoors environment and spare boots are available anyway. Very far from the typical military use case. Also material science has advanced massively in the _500 years_, try having a civilization 500 years ago (IRL time) understand a modern jet engine.

>mall cops
>has an armoury full of lethal weapons

**Comment by SomeoneYouProbablyKnow** [comment]
They ARE mall cops in a sense that they are corporate security. Honestly considering the full extent of NTs arsenal sec's "lethal weapons" are barely the surplus. It's the future and a pulse rifle pretty much vaporizes you. But that's minutia sec is SPIRITUALLY mall cops, or i strongly believe they should be

**Comment by Timberpoes** [comment]
Not interested in this change.

**Pull request closed without merging**
