### PR TITLE
Adds a missing brown gas rename.

### PR DESCRIPTION
**Pull request by praisenarsie**
#bringbackbrowngas

### CODE REVIEW

**Comment by Qustinnus** [comment]
recompile it

**Review by ghost — CHANGES_REQUESTED** [review]
needs TGUI compile

**Review by ShizCalev — CHANGES_REQUESTED** [review]
compile

**Comment by praisenarsie** [comment]
someone compile it for me please, i don't want to go through the effort of setting up tguicompiler

**Comment by ShizCalev** [comment]
https://dextraspace.net/TGUICompiler

**Pull request merged**
