### PR TITLE
Clock powerdrain now works on any device with a powercell

### PR DESCRIPTION
**Pull request by Cyberboss**
Small oversight from the get_cell refactor methinks

### CODE REVIEW

**Review by ChangelingRain — APPROVED** [review]

**Comment by ChangelingRain** [comment]
You should probably keep this from working on guns though

**Comment by GuyonBroadway** [comment]
Actually it would put clock cult more on par with blood cultvas blood cult have them Emp papers that let them make a mockery of secs day.

**Comment by ChangelingRain** [comment]
Yeeees... but bloodcult's EMP papers aren't passive and can't be on constantly.

**Review by ChangelingRain — CHANGES_REQUESTED** [review]
Hey please add an override for guns and batons maybe

**Comment by GuyonBroadway** [comment]
It depends how fast the drain for guns is. One bloodcultist with two emp papers can completly empty anyones guns and batteries in a couple seconds and do so from stealth. A clock base is static and obvious and the rune might take a while to drain any energy weapons in use.

**Comment by Time-Green** [comment]
Make sure KA's are accounted for, the powercell inside constantly refills

**Review by ChangelingRain — CHANGES_REQUESTED** [review]
batons too

**Review by ChangelingRain — APPROVED** [review]

**Pull request merged**
