### PR TITLE
Changes to vendor prices and other tweaks

### PR DESCRIPTION
**Pull request by Mickyan**
:cl: Mickyan
balance: Changed price and availability of several items sold in vending machines
/:cl:

No new items in this PR, split most vending machines into the two price ranges, where applicable the distinction is between equipment and supplies (ie. engi vendor) or otherwise either how useful or how fancy the item is. Even though at first glance it may look like all prices have been decreased, in reality a lot of stuff has been moved to premium and increased in price. The main goal is having better distinction between cheap and expensive items.

Occasionally changed some items from contraband to premium and the available amounts to be more in line with the rest.

Changed the order of the items in the booze-o-mat and sorted them by type (dinnerware -> juices -> sodas -> light booze -> booze)

### CODE REVIEW

**Comment by Repukan** [comment]
Don't add Vapes as something more easily accessible

**Comment by Mickyan** [comment]
you can print multitools you can't print money

**Comment by epochayur** [comment]
logo

**Comment by anconfuzedrock** [comment]
Maybe the basic stuff in the youtool should be cheaper? just my opinion, but not many people spend $25 on wirecutters.

**Comment by MMMiracles** [comment]
If you want actual custom prices per item, you need to set a 'custom_price' var with a number on each item you want changed. The default prices on vendors are just there as a backup when an item doesn't have a price set yet.

**Comment by FantasticFwoosh** [comment]
The correct answer to tool expenditure is how many tools do you need to buy to greytide & invade a department to force access to the autolathe? Its a similarly militant approach like you see in botany/chemistry standoffs on who has the most divine right to commandeer the chem dispenser.

- Off the top of my head, for most maps its enough to weld 1 wall, tank the eyedamage best you can and bash the girder down with a readily availible weapon before someone comes out to stop you.

**Comment by BeeSting12** [comment]
@Mickyan this weekend i plan on fully fine tuning all the prices.

**Comment by Arkvold** [comment]
BeeSting12's efforts are here, unless I'm mistaken.  #40532

**Comment by Mickyan** [comment]
This does more than just adjusting prices and shouldnt even cause conflicts

**Comment by BeeSting12** [comment]
I actually plan on touching the vendor's default prices as well, so there probably will be conflicts.

**Comment by Mickyan** [comment]
I'll just let you do your thing I have very little faith goof will actually bother to fix premium prices anyway

**Comment by BeeSting12** [comment]
I'll integrate your changes to the order of the vendors into my PR and give you credit.

**Pull request closed without merging**
