### PR TITLE
Removes Cyborg RCD ability to deconstruct reinforced walls

### PR DESCRIPTION
**Pull request by Anonmare**
I'm not sure who thought this was a good idea to be quite honest.
:cl:
tweak: Cyborg RCDs can no longer deconstruct reinforced walls.
/:cl:

### CODE REVIEW

**Comment by RandomMarine** [comment]
May as well go all the way and remove the var and checks altogether, because that's the only thing that uses it.

**Comment by Anonmare** [comment]
Leaving it in unless a maintainer tells me to, on the off chance we want to add something that will decon R-walls or alter an existing RCD (such as the ERT Engineer's combat RCD).

**Comment by optimumtact** [comment]
it's bait

**Comment by KorPhaeron** [comment]
Freeze

**Comment by optimumtact** [comment]
if what @RandomMarine says is true then you should remove the var and check

**Comment by Anonmare** [comment]
I'd prefer not to on the off-chance that someone wants to make an RCD that can remove r-walls. Like the engineering ERT's combat RCD

**Comment by optimumtact** [comment]
It wasn't a request

**Comment by Anonmare** [comment]
@optimumtact Fiiiiine but it's not my fault if someone is sour about it

**Comment by optimumtact** [comment]
The most salty people here should be the cyborg players

**Comment by MoreRobustThanYou** [comment]
sxtqaevtk6yjp2kux9iuicbax19kcnbhp_y6ivhq7le

**Comment by KorPhaeron** [comment]
Balance PR with no justification by author

**Comment by Anonmare** [comment]
@KorPhaeron Extremely overpowered isn't a good enough reason? 

It's inconsistent with every other RCD, including the admin-only one, and makes it too easy to break into the AI satellite. I don't see any reason why a cyborg RCD should have this ability when not even the admin device has it

**Comment by optimumtact** [comment]
@KorPhaeron ^ that should be reasoning enough right?

**Comment by KorPhaeron** [comment]
I dont agree with the reasoning of comparing admin spawn stuff to things that exist in the game world but sure at least they tried now

**Comment by KorPhaeron** [comment]
I am still not sold on this though because borgs give up versatility to be extremely good at their specialization and r wall spam is obnoxious so counters arent bad

Plus this has been in for 6 years

**Comment by RandomMarine** [comment]
Still didn't remove the canRturf checks in reinf_walls.dm

Code cleanup aside, I'm ambivalent toward this change. It feels like a nerf for the sake of a nerf. How does this improve the game?

**Comment by KorPhaeron** [comment]
Slept on it and still dont see the need for it

**Pull request closed without merging**
