### PR TITLE
lol lets just give you an instant stun that takes someone out of the round and doesn't even kill them so they can ghostrole no fighting back just dead 

### PR DESCRIPTION
**Pull request by Iamgoofball**
Close reason wasn't provided so I'm re-opening it.

this way ninja is less autistic

### CODE REVIEW

**Comment by kevinz000** [comment]
and this is how you get gitbanned.

**Comment by Shadowlight213** [comment]
Then modify the map to remove the holding facility. Stop doing half-assed removals

**Comment by GunHog** [comment]
You were already denied, Goof. Opening PRs that were already denied in the same day might get you banned.

**Comment by ChangelingRain** [comment]
Actually try fixing or tuning it maybe instead of doing ridiculous bullshit like this!

**Comment by Iamgoofball** [comment]
@kevinz000 I asked for a close reason and none was provided so I have to assume it's a mistake.

@GunHog No denial reason was given? Have to assume it was a mistake.

**Comment by Iamgoofball** [comment]
@ChangelingRain 
chrome_2017-01-22_18-25-19

**Comment by Iamgoofball** [comment]
literally doing what you asked in the original PR

**Comment by MimicFaux** [comment]
Even if it's what for what was asked for in the old PR, not explaining what the PR is for in the NEW one, is aggravating to everyone who wasn't following the previous one.

**Pull request closed without merging**
