### PR TITLE
Rebalances plasma fires at lower temperatures to burn slightly hotter

### PR DESCRIPTION
**Pull request by mirrorcult**
:cl: cyclowns
balance: Plasma fires at lower temperatures burn slightly hotter. This means bombs utilizing plasma and oxygen will behave closer to what they used to.
/:cl:

related to #37116 

Changes PLASMA_UPPER_TEMPERATURE to (870 + T0C), from (1370 + T0C). This means that plasma fires will reach peak efficiency slightly faster and at a lower temperature, which means plasma combustion bombs will be slightly bigger, to reflect bombs from before #37116 . Other plasma fires (SM room, toxins burn room, incinerator, etc.) already reached peak efficiency pretty fast, so this will not affect them as severely. This fix is mainly intended to rebalance bombs. Also, this PR moves some plasma-fire related defines to code/__DEFINES/atmospherics.dm, from code/modules/atmospherics/gasmixtures/reactions.dm. I notice that #37293 also does this. This shouldn't be an issue as the define names are specific enough to not cause collisions in the future.

[why]: #37116 appeared to be just a fix to an old atmospherics error pertaining to plasma fires, but it actually had a lot of balance consequences. _Any_ change that was related to plasma fires or plasma combustion bombs in the past 10 years was balanced around the old, albeit broken, values. It's not really fair to fix the bug and not rebalance it to work how it did previously, considering that the values related to the 'broken' math were tweaked to give the outcome that they did.

While the value of (870 + T0C) rather than (1370 + T0C) seems like an arbitrary change, I actually looked at several different approaches to rebalancing this. This was the simplest and easiest to understand change that gave the desired effect.

### CODE REVIEW

**Comment by Jalleo** [comment]
I think its better to make it a tad bit harder.

**Comment by cyclowns** [comment]
then that should be handled in a separate balance PR, not one that was just intended to fix a 10 year old atmos bug.

**Comment by GuppyLaxx** [comment]
`No.`
I stand by the fact I hate people trying to change it back to what it was before, it doesn't matter that your mix fucking sucks now, that you're too lazy to go figure out new shit, whatever. Go change what you did before to fit now instead.

**Comment by cyclowns** [comment]
the problem is that #37116 was a **BUG FIX**. it wasn't intended to have balance repercussions and it's a little unfair to treat it as a balance change.

**Comment by optimumtact** [comment]
In this case I'm happy to shake up the bomb meta as that's been stale for a while anyway, so I don't think I would merge this.

**Comment by Jalleo** [comment]
Yes but @cyclowns see https://github.com/tgstation/tgstation/pull/37116#issuecomment-380547328
This means that people were presuming the math was the current math at least with some of the changes. So how can you prove it shouldn't be as the current style with burning rather than the old style?

**Comment by ExcessiveUseOfCobblestone** [comment]
I have a hard time giving any ground to the "it wasn't explicitly tagged balance therefor give old effects" argument.

Everyone in the discussion knew that it had balance implications. It was literally mentioned by a maintainer under the OP, and the 4th post (yours) explicitly explained an example of it.

**Comment by ninjanomnom** [comment]
In absence of dunc saying otherwise I'd rather let the current changes sit a while and make changes from current code than attempt to recreate the older model.

Closing this in 24 hours assuming no intervention.

**Comment by Arianya** [comment]
Maintainer fiat is maintainer fiat, but it seems extremely weird to not correct values so that they replicate existing behavior, especially when certain PRs like #34601 were made on the basis of "bombs vaporizing the entire map".

Especially because there was no real impetus to change bomb meta. No complaints or stats to show that bombs/Toxins was out of control, just a (needed) fix that had knock on consequences that weren't correct because *???*

**Comment by ninjanomnom** [comment]
I wake, I close

**Comment by ninjanomnom** [comment]
People are always complaining about one thing or another, the bomb meta in particular though has been a minor point of dissatisfaction among some of the maintainers for a while now. We're not averse to changes here.

**Comment by RogueSteampunker** [comment]
It's one thing to change factors, it's another to make it where achieving maxcaps requires you to jurry-rig the toxins setup to make tritium bombs in order to actually make anything of worth. 

Jussstttt sayin'

**Comment by optimumtact** [comment]
actually that sounds pretty much ideal. We want maxcaps to be effort required

**Comment by cyclowns** [comment]
gay but whatever i'll just deal with it

**Comment by optimumtact** [comment]
https://www.youtube.com/watch?v=nYsUKPoW-Qo

**Pull request closed without merging**
