### PR TITLE
Fixes endless Nar-sies.

### PR DESCRIPTION
**Pull request by KazeEspada**
Hopefully this fixes the endless nar-sie storm.

### CODE REVIEW

**Comment by KorPhaeron** [comment]
This is critical

**Comment by PKPenguin321** [comment]
>tested code

**Comment by KazeEspada** [comment]
See that patch-3. Means this shit never touched DM.

**Comment by tkdrg** [comment]
weight 0 doesn't mean they don't run, it just means they're very rare

**Pull request merged**
