### PR TITLE
Improves cyberimplant medHUD and health analyzer readout

### LINKED ISSUE #49085: Multiple cybernetic modifications in medHUD examine missing space, take up needless room
> Detected cybernetic modifications: 
> x is modified with a breathing tube implant.x is modified with a integrated toolset implant.x is modified with a Nutriment pump implant PLUS.x is modified with a Reviver implant.x is modified with a Medical HUD implant.x is modified with a CNS Rebooter implant.x is modified with a anti-drop implant.x is modified with a implantable thrusters set. 

**Suggested change**
Detected cybernetic modifications: 
Breathing tube implant, integrated toolset implant, Nutriment pump implant PLUS, Reviver implant, Medical HUD implant, CNS Rebooter implant, anti-drop implant, implantable thrusters set

### PR DESCRIPTION
**Pull request by cacogen**
## About The Pull Request
before

after

closes #49085 

## Why It's Good For The Game

Saves space, cleans up formatting, gives ants an idea of what these things look like

## Changelog
:cl: cacogen
spellcheck: Cybernetic implant readouts on medHUD and health analyzer are more compact and show an icon of each
/:cl:

### CODE REVIEW

**Comment by HomocidlePancakes** [comment]
This hurts to read.

**Comment by cacogen** [comment]
What would you prefer?

**Comment by HomocidlePancakes** [comment]
Each item on it’s separate line.

**Comment by cacogen** [comment]
I did think about it and I can do it, it just takes up a lot of space for
an already lengthy readout.

**Review by kriskog — APPROVED** [review]

**Pull request merged**
