### PR TITLE
Removes Cryotubes from the game completely

### PR DESCRIPTION
**Pull request by strandsofivy**
## About The Pull Request

This PR removes cryotubes from the game completely. Cryoxadone has been rebalanced to have no effect on brute/burn and has had its wound mending stat and unconscious requirement removed. Pyrox/Clonexadone have been removed from the game entirely. 

-xadone wound healing has been renamed to wound mending and is now a mechanic exclusive to plasmamen digesting plasma.

I'm not sure if it's a good idea to keep cryoxadone around since it has had its original purpose removed, but I saw that it has uses in botany and in creating synthflesh, so I kept it around until I have a better idea on how to handle that. Pyrox/Clonex are both gone now too because their purpose is no longer conveniently achievable, however I can readd pyrox back if people want to keep it around for leaping into fires, as that is kind of a funny mechanic.

Meta cryoroom has been turned into a maintenance room, Tram cryo has been merged with the treatment theatre and all other cryorooms have been replaced with either a freezer or a chem storage.
## Why It's Good For The Game

I'm here to argue that cryotubes are bad for the game. No, seriously, put down your pitchforks please and hear me out.

Medical on /tg/ has a very rich history of mechanics battling with themselves over balance. Sleepers and cloning have been debated and discussed to death at this point, and as far as I can tell, the wide consensus is that medical was left in a better state with them gone. Now I'm willing to make the argument that cryotubes do not fit under the medical balance either, and for the same reason as sleepers and cloning, namely that it is simply too much of a crutch that it tries to invalidate surgery and chem.

#### But cryotubes are already useless, why remove instead of buffing them?

While yes, it's true that cryotubes are useless, it's also really hard to make it better for the department? I mean, we have a machine dispensing a panacea reagent at the downside that it's very awful to use, meaning its jankiness is the only part of it keeping department balance in check and from taking over surgery/chem. If we instead nerf it more, it's just going to become more of an irrelevant mechanic. Balancing cryotubes to be better/worse is out of the picture then.

#### What does this mean for sepsis wounds?

The validity of sepsis in itself is another topic to discuss, but it has always suffered from the consequences of cryotube healing. Imagine getting all that fluff throwing at you about you losing your limb completely, only for a doctor to stick you in a cryotube and your sepsis wounds being qdel'd immediately. I have no idea how bad sepsis is for medical/victims to deal with (since the answer was always tube the person), but I hope at least sepsis can actually be explored as a mechanic now and adjusted accordingly. 

#### What does this mean for clone damage?

Clone damage is a weird mechanic. It only affects a single department, and shouldn't even be around today anymore. It's way too niche to be of note to medical in most rounds, and should be removed from the game. But for now, yeah, clone damage might be a problem, and I have been thinking about adding a passive clone damage heal to mitigate this. Or, people could start making rezadone.
## Changelog
:cl:
del: Nanotrasen has discovered that breathing cryogenic juice mixed with plasma, shockingly, has had severe long-term impacts on the mental faculties of patients and medical staff, and has decommissioned all their cryogenic facilities until further notice.
/:cl:

### CODE REVIEW

**Comment by Jacquerel** [comment]
I will miss putting people in a big tube but frankly aside from my radical idea of "replace stasis beds with a big tube" I don't have a good idea for what a big tube should do and I agree with this reasoning.

**Comment by RikuTheKiller** [comment]
As much as I would love to disagree, you're mostly right. I don't see any harm in leaving the chemicals themselves in, though. Simply let them be chemistry exclusives and remove the sleeping bonuses? Being cold slows you down and there is no way to keep yourself warm enough to use pyroxadone effectively without risking burning yourself to death after a while.

**Comment by chemistrymain2** [comment]
While arguments about the cryotube are fine, you can't remove the cryotube without adding a way to fix clone damage.

Do that first or bundle it with the PR.

**Comment by Nimowa** [comment]
I would like to point out that the tubes actually work _with_ chem because you can use other reagents with the tube to make it more efficient, as well as promoting interaction with atmospherics because they can replace the gasmix with healium.

And while I get it allows people to avoid dealing with wounds, I've noticed that people will usually pick surgery over the tubes because it's more convenient when it's just a wound or two. Instead it's used for severe cases, like a tram victim covered in critical wounds that no MD would (understandably) want to deal with personally.

**Comment by GuillaumePrata** [comment]
The only issue with the tube is the wound healing, before they had that feature added in, they were mostly unused unless doctors were flooded with people needing treatment which was a good niche for the tubes to fill in, a backup for doctors.

Another angle is that while the tubes without wound healing are basically a worse version of a medibot, they are something that the non-doctors can use to heal people from minor injuries.
It is really cringe IMO when the clown walks into medbay (doctorless or not), grab surgery gear and starts doing tend surgery on their metafriend. If the tubes exists we can at least scream at them to use tubes instead of becoming a doctor, if the tubes are gone, the only option people will have for healing others consistently is doing surgery themselves.

**Comment by Vincent983** [comment]
If there's an issue with the wound-healing of cryoxadone, why not just only remove that instead of cryotubes as a whole? It's just flavor but cryotubes are a lot cooler way to deliver healing chems than a pill or patch.

**Comment by JohnFulpWillard** [comment]
Man I just fixed the overlays

**Comment by CoiledLamb** [comment]
i mostly just use tubes for suffocation and toxin damage, but yeag personally i think i'd rather see the wound healing functionality stripped before seeing them outright removed. like i said in discord, reducing their capacity to heal brute and burn damage could be interesting too.

**Comment by Pinkufeck** [comment]
"But cryotubes are already useless, why remove instead of buffing them?"

They're not, they're underused and situational, they're a pretty good healing machine, even if they take some time for brute and anything other than suffocation, but apart from that they're not bad. 

I don't know why you absolutely want to touch it in its current state. It doesn't need nerf or buffs, I don't know why it would. What's wrong with it *currently* ?

"What does this mean for sepsis wounds?"
Your whole answer on that question is "balance around sepsis it all out of wack because we have a solution for sepsis, so we should remove the solution for sepsis"
Btw, unless you put someone in cryo, sepsis means that you'll either have to change their limb, or fix it, which takes ages via surgery. Cryo gives an opportunity for people to retain their limb without having to sit in a bed for surgery for 5 minutes (I'm not exaggerating, infectious tissue removal takes that much time. At least it did, unless it was changed)

As for clone damage. Rezadone cannot be done by chemistry alone, it requires carpotoxin, which can only be obtained after mutating soybeans in botany. 
So if you don't have competent botany, or it's destroyed, good luck healing any clone damage. 


This whole PR feels like it was written after someone got put into a cryotube after they asked not to, and then had to wait 2 minutes to be full health.
A solution to cryo being so unenjoyable to me would be making it not put you to sleep. Allowing you to see what's happening around you, making it an equivalent to waiting in a stasis bed in terms of interaction with the outside world rather than being put in baby jail for 2 minutes.

**Comment by Jacquerel** [comment]
> > Being mostly unused, equivalent to a worse medibot, and which is handed to tiders to get them out of the way are arguments that this feature is unhealthy.
> 
> The reason cryotube goes unused is mostly because medical tends to suffer from "oops, all new players"-itis. New players don't know the benefits, what it does better than some other surgery/chem, etc. And it's not a worse medibot. Medibots don't fix wounds, it does, even if it heals brute and burn slower than medibots made for it. Also medbay doesn't start with a medibot, yes you can get one from hallways, but having dedicated equipement for overall healing being present in medbay makes sense.

This was in reply to a post saying "without regarding wound healing". I am of the opinion that cryotubes being a simple answer to any and all wounds is negative, and that if we _don't_ remove cryotubes we still _should_ remove their wound healing.
Getting a medibot from robotics in exchange for one of your empty medkits if you want a passive healing source to help you triage is also good gameplay as far as I am concerned.

**Comment by thElasT13** [comment]
Bad pr cryo good 😎

**Comment by carlarctg** [comment]
I'm of two minds on this PR. I think cryo tubes are soul and fun to use and really cool and I like putting patients under while I go treat others - it feels like good multitasking and triage. Add on to that the depth and complexity of cryo mechanics and it's very interesting.

On the other hand I dislike how _base_ it is and the fact that it so dead simple leads dumb people to fuck it up. It's the only sane way of healing Wounds, so removing that is an issue, but wounds themselves need to be less stupid to fix without cryo.

**Comment by Pinkufeck** [comment]
> This was in reply to a post saying "without regarding wound healing". I am of the opinion that cryotubes being a simple answer to any and all wounds is negative, and that if we _don't_ remove cryotubes we still _should_ remove their wound healing. Getting a medibot from robotics in exchange for one of your empty medkits if you want a passive healing source to help you triage is also good gameplay as far as I am concern

Why remove wound healing from cryotubes, some wounds definitly don't have their place being fixed by it, like bleeds,  but outright removing everything would just remove one area in which it's relevant. 
As for the claims that it's a subpar without wound healing medibot, this is only when it has it's default chems in it. if you take a little time to sprinkle healing chems in it, it becomes a lot better.

**Review by MrMelbert — CHANGES_REQUESTED** [review]
Delta mapping nitpicks

<Details>

<Summary> Make this part's area belong to the treatment center now. Put smooth-large tiles underneath the vents and scrubbers. Move that camera off of the window on the left. I also wished there was some symmetry in the vents and scrubbers here (maybe put them in the middle two tiles of the corridor and adjust the pipe / cable run a smidge). </Summary>

image

</Details>

<Details>

<Summary> You have a few wall mounts stacked on one another here that will make AI players upset. Namely, a poster over an air alarm and an intercom under a status display. Also the nittiest of nitpicks, would be nice if the scrubber was on the southmost tile rather than the eastmost for that symmetry :tm: . (Also lso  it's a shame the breakroom has no enertainment monitor but I understand how cramped it is) </Summary>

image

</Details>

<Details>

<Summary> More stacked wallmounts here, buttons in the psych office and an APC under a Nanotrasen sign. I also would kind of appreciate if this kept a door from med -> departures. This room could also use a few wall mounts of its own, mostly fluff ones - light switch, periodic table / wash hands / wear goggles poster, secure area sign, that kinda stuff. The south wall is pretty plain. Also there's an air supply pipe that runs south which does nothing. </Summary>

image

</Details>

**Comment by Jackal-boop** [comment]
i think this is a silly removal. the tubes arent over powered nor underpowered, i see them used maybe once each round, sometimes more if a doctor is smart

**Comment by carlarctg** [comment]
I think the optimal fix here is to leave the cryo tubes in as a post-research machine, that way they're still in, still cool, but need to be set up so they don't outshine other methods of treatment.

**Review by MrMelbert — CHANGES_REQUESTED** [review]
Meta Mapping nitpicks

<Details>

<Summary> Left-most door should have med-maint access and not med-serv access. Left-most door also has an air pipe sticking in which is useless. Also put small strips of warning stripes in front of each maint door on both sides to match the meta maint door style. Also also nitrile gloves in maint is kind of a meme, do we do that anywhere else? If so, lol, otherwise I'd suggest putting latex there instead. </Summary>

image

</Details>

**Review by MrMelbert — CHANGES_REQUESTED** [review]
Tram 

Not sure med should REALLY have 6 roundstart defib mounts? Probably fine to leave the two new beds mount-less and let players assign that.

<Details>

<Summary> MDB shows you left a trail of decals, fix that. </Summary>

image

</Summary>

</Details>

<Details>

<Summary> Also these. </Summary>

image

image

</Details>

<Details>

<Summary> Also these large textured tiles are off. </Summary>

image


</Details>

**Comment by HoodMilk** [comment]
They're very flavorful for the sci-fi setting and are pretty much the only way to heal clone damage. They're also good for treating extreme amount of wounds on a person and with the power of chem can take custom chemicals to do fancy things. If you really have an issue with them rework them instead of axing them completely. Maybe remove them roundstart from medical and have them only be obtainable with research, to be a reward later in the round when doctors get bored of treating wounds and the critical people pile up.

**Review by MrMelbert — CHANGES_REQUESTED** [review]
Norf Star

Not a huge fan of this one, doesn't make a ton of sense to have a chemical room right off of the treatment center... Not sure what I'd replace it with but just throwing that out there. 

<Details>

<Summary> Stacked wallmounts and lots of empty wall space to make use of. Move around that air alarm, APC, and chem warning sign and throw in a light switch, AI display, and some posters. Also - running ducts right through a wall. Double check the pipe work. And no vents or scrubbers. </Summary>

image

</Details>

I think the med storage could be better without the anesthetic closet but maybe for another time.

**Review by MrMelbert — CHANGES_REQUESTED** [review]
Icebox

<Details>

<Summary> Not a ton here, I'd just suggest moving the vent and scrubber to the middle of the room. And maybe throw some more wall mounts in, light switch and ai display namely. </Summary>

image

</Details>

**Review by MrMelbert — CHANGES_REQUESTED** [review]
Birdboard

This one reminded me, be sure to double check all camera tags and airlock names for the rooms being axed. It would be silly to have cameras point to "cryogenics" and doors with the name "cryogenics room" left over. 

<Details>

<Summary> Why library changes? </Summary>

image

</Details>

Otherwise looks fine, if anything I'd suggest more grime, a chem related poster, and 1 ai display in the chemical closet.

<Details>

<Summary> Remove this one way access though.</Summary>

image

</Details>

**Comment by MrMelbert** [comment]
I will also throw out my opinion, even though I'm reviewing the maps - I'm not a huge fan of the removal myself, since I think it provides a good backup for newer medical players to use. (IE - If you are truly clueless on how to fix a wound or heal a damage type, cryogenics can fill gaps in knowledge until you learn how.)

**Comment by epochayur** [comment]
This PR seems, in general, not thought-out. Aside from the outright removal/nerfing of several chems, and aside from the fact that cell damage will no longer have a counter, you provide exactly one sentence that describes why you think cryo should be removed:
>...namely that it is simply too much of a crutch that it tries to invalidate surgery and chem.

In what ways is this actually the case? Surgery and chem remain the backbone of Medical, and meanwhile, I can count on one hand the amount of times I see the cryo tubes get used in a round. That is to say, they fill their niche perfectly. Cryo is there for patient overflow, healing weird damage types (like cell damage), and for non-doctors who need to do healing in an emergency.

Cryo does become very good under specific circumstances, which is when multiple departments work together on something like a healium + healing chem mix, which is behavior that should be rewarded anyway!
 
If your problem is with cryo healing wounds, then address that. But you really haven't explained why this would be a good change other than "we removed sleepers too!".

**Comment by DaydreamIQ** [comment]
In regards to the genetic damage "only affecting one department". Abductors and cosmic heretics exist and the latter is far more effective at dishing it out

**Comment by Inari-Whitebear** [comment]
> 9/10 medical doctors don't want to heal somebody of 5 wounds after they get hit by the tram (not to mention that 9/10 players don't want to be under the blade for 10 minutes), a lot of them don't even know the steps and need to rely on the help of the wiki (showing how situational the whole thing is). 

They don't know the steps because they don't do it, they just cryo them. They'll learn from doing it though.

And dunno, maybe I'm weird, but I get a person with 5 wounds an am like "Yay, finally something I CAN do, that isn't just 'slap all these chems on we have 5000 from lying around because of chemists doing chemist stuff"
Except not, because it's "just cryo them instead"

**Review by ZephyrTFA — APPROVED** [review]
I am approving the goal of this PR, I have not looked at the code as of yet.

**Comment by Pickle-Coding** [comment]
Honestly I think it's better for cryotubes to just simply have a stasis effect for storing bodies, and the stasis beds get replaced by surgery tables.

**Comment by DaydreamIQ** [comment]
This also just seems kind of lazy to remove a big chunk of wound treatment and then expect someone else to fix it later. If you're gonna remove cryo, then you're gonna have to address locked up limbs, genetic damage and the nightmare that is treating t2/3 burn wounds. Like for instance removing the carptoxin requirement from rezadone

**Comment by DaydreamIQ** [comment]
This also just seems kind of lazy to remove a big chunk of wound treatment and then expect someone else to fix it later. If you're gonna remove cryo, then you're gonna have to address locked up limbs, genetic damage and the nightmare that is treating t2/3 burn wounds. Like for instance removing the carptoxin requirement from rezadone so it's actually feasible to make without relying on a random event.

**Comment by Time-Green** [comment]
I really don’t like this. I was immediately onboard with the cloning removal, I agree braindead healing is not interesting, and it qdelling strong wounds needs to go, but:

Cryo is so fucking good for triage. I’ll often be handling medbay alone, overrun with patients, or both, and the only reason I don’t have to just start shoving bodies into disposals is cryo. It’s weak, slow, but reliable, it’s the ultimate backup support and I’m not convinced medbay would be better without it

**Comment by TheFatRoozbeh** [comment]
You're just removed cryotubes for the sake of change and its gonna break alot of things

**Comment by Pickle-Coding** [comment]
Sepsis wasn't really meant to be fixable without replacement, until someone powercreeped their chemicals so they could fix it easily. It won't be a problem.

**Comment by GuillaumePrata** [comment]
> Being mostly unused

Being mostly unused is SS13 features in a nutshell. Features don't need to be used all the time to be important, as long as they are important in a way that adds to some rounds. A backup for when doctors are mostly new players and have multiple people needing treatment is important.
We don't need to make medbay more hostile to new players, it already is the worst department on that angle.

> equivalent to a worse medibot

Medibots are just stupid infinite passive healing. IMO most medical features are worse than medibots, from tend surgeries to chem mixes. Infinite, non-interactive passive healing you can just drag to anywhere on the station is just too good.

> and which is handed to tiders to get them out of the way

It is not handing out to tiders, it is a good tool for non-medical staff.
You can ask people to use it instead of grabbing tools and healing others themselves mid crisis, I don't think we should push the idea of "The doctors are flooded with their job, let me help them by doing their surgical job" being the main angle crew can assist medbay.

With the cryo existing, you can be a non-doctor that does triage and helps put people in cryo when medbay is overloaded.
Without it, you either do surgery or chemistry yourself if you want to help as a non-doctor. As far as I'm aware, doctor players hate to see their job being so easily taken by anyone with a toolbelt.

**Comment by FlufflesTheDog** [comment]
Few minutes late I guess but I might as well, in case this gets further consideration.

I have mixed feelings on how much cryo can trivialize an otherwise intensive and engaging job, and I could probably get behind a removal or rework. (Disclaimer that I do almost exclusively play skeleton shifts where triage work is much less of a problem.) However septic wounds are a really big deal that would need addressed. 

Burn wounds have such a weird loop compared to other wounds, going from something that has literally no impact if you have the right chems or some mesh on hand, to something that can leave you crippled and neigh unfixable (lacking cryo) in just a few minutes if left untreated. I can appreciate the flavor of a limb so ruined it needs to be amputeted entirely, but considering it can strike your head or chest and be caused by something like a stray laser or an emitter accident, it seems far too punishing for the average player.

**Comment by CliffracerX** [comment]
Late to this since OP nuked the PR, but putting my $0.02 on the record: this PR coulda used a public design phase and some more time in the oven.  There's very little rationale for the removal beyond "I don't like this system", and *no* effort was put into fixing the mechanical mess its removal would make seeings as how cryo is a part of the wounds cycle & the primary means of patching up slime smooches & other cloneloss sources.

Cryo *can* be a crutch in the hands of bad medics, but nine times out of ten it's the last-resort "OH GOD OH FUCK" option for healing people, if it's used at all; mostly it's for patching up foolish xenobiologists or whatever poor bastard atmosian went to fight off pyroclastic slimes, because cell damage is janky and unpleasant & the only healing chem for it isn't the best.  When it *is* used to its full extent, it requires cooperation between chemistry and atmospherics to cook up the best healing mix, and it can be great on high-pop for triage since it keeps the surgery load down enough to save a few more lives.

As others have said, a *rework* that makes it more situational would be ideal to resolve some of the gripes the designers have with cryotubes, but outright removing it- let alone removing it without patching the created holes- is just a sucky move.  Wound healing could easily be covered by changing up how the chems work - e.g, cryoxadone for broken bones and infected burns, pyroxadone can cauterize bleeding, both have unique balances for raw damage healing - and making them require more setup from the get-go by only including boards & frames could help reinforce the idea that cryotubes are advanced tech & the brainchild of multiple departments working in unison.  Medical knows the healing, atmos knows how to make the best air, and R&D provides the advanced parts to make their efforts worthwhile.

**Comment by Majorkite** [comment]
Putting in my opinion in case this gets resurrected, because I have one. I've seen nearly every iteration of medbay, and they've all had an engagement-with-job to do-other-stuff ratio. The current ratio is pretty good, and some rounds can verge on the oppressive with the amount of stuff you have to do (I'm looking at you, swing combat test round). 

Taking away cryo without a doubt would ruin that ratio. Especially with no plan as to what to do to fill the holes it would leave behind. The cryo tube is ideal for things like tram accidents, people that try to fight the tourist robots, excessive toxin damage, and just too many wounds in general. Any other benefit it has, can be done better by a combination of surgery or meds, and I don't see people that know what they're doing using the tube in place of the better methods. 

In your next attempt, I'd come armed with some more knowledge of how the game systems work and some suggestions other than 'remove this thing'. I'd much rather see something replacing it rather than just removing stuff from the department.

**Comment by nukularpower** [comment]
thank goodness this got closed.    this is a big deal flavor wise - leave my soul alone

**Comment by Screemonster** [comment]
OP's list of things saying that the cryo is bad for the game focuses entirely on the _medical_ uses of cryo

I'd argue that the brainless quick heal method for doctors who don't know what they're doing is very _good_ for the game because it's hilarious when you fill it with some horrible killmix instead of the normal cryo chemicals and watch said clueless doctors dutifully stuff people into the death tank

**Comment by ExcessiveUseOfCobblestone** [comment]
cryo is  cringe but I think for more steep medical nerfs I will need a giga buff on the engagement factor for current methods before I would consider letting them slide.

Surgery is not fun even for people who find the job fun, so as we approach the point of mandating surgery it gets harder and harder to be content with changes like these in the current iteration of the game.

**Comment by Dorsisdwarf** [comment]
I usually only get cryoed when im completely and utterly fucked up, and it saves me 20 minutes of medical torture by john clueless... sepsis isnt a fun mechanic anyway so who cares if it makes it easy to bypass.

**Pull request closed without merging**
