### PR TITLE
Watchers now instantly fire at targets instead of setting temperature

### PR DESCRIPTION
**Pull request by ChangelingRain**
This should feel slightly more fair.

### CODE REVIEW

**Comment by Zilenan91** [comment]
No longer will you walked into a watcher and another mob and instantly die because you get slowed :+1:

**Comment by ChangelingRain** [comment]
Provided you dodge the watcher bolt, of course.

**Comment by Zilenan91** [comment]
How fast is it anyways, is it laser speed?

**Comment by ChangelingRain** [comment]
It's projectile speed so possibly dodgeable, but not always easy.

**Pull request merged**
