### PR TITLE
Revert "Adds the other half of the fox infusion because Arm is a coward"

### PR DESCRIPTION
**Pull request by optimumtact**
Reverts tgstation/tgstation#85129

### CODE REVIEW

**Comment by optimumtact** [comment]
When I said no more animal races, I was 100% serious.

**Comment by Blacklist897** [comment]
Cringe

**Comment by atlasle** [comment]
THANK YOU

**Comment by CopperCrow9** [comment]
TECHNICALLY its not an animal race, its an infusion...

**Comment by paganiy** [comment]
tg saved

**Comment by Samag5** [comment]
Based

**Comment by Inari-Whitebear** [comment]
So why did we add carp infusion? Isn't that an animal race then?

**Comment by CRITAWAKETS** [comment]
Okay I have no idea what this PR is about. Fox infusion was already a thing with cosmetic features so this isn't removing the ability to become half-fox with DNA infusion. So "no more animal races" is just flawed since its still there.

And furthermore, there are more DNA infusion "half-species" with cosmetic effects than foxes.
Mothroach Infusion - You get mothic organs like wings, no matter your species
Cockroach Infusion - You get a visible shell with the heart.

So should these be removed aswell for being extra animalid species?

I just wanna know what bro is yapping about here.

**Comment by axietheaxolotl** [comment]
holy based

**Comment by CCC23** [comment]
its so joever

**Pull request merged**
