### PR TITLE
Bans shitty commits

### PR DESCRIPTION
**Pull request by Cyberboss**
These are uninformative and don't detail what they've done. At least enter literally ANYTHING in the box

@kevinz000

### CODE REVIEW

**Comment by kevinz000** [comment]
lol
vs
lol2

**Comment by Jalleo** [comment]
Both of those are uninformative.

**Comment by optimumtact** [comment]
you can't solve this, I've tried educating people on good commit message practice.

It's why the squash/merge button is the most useful button as a maintainer.

**Comment by GunHog** [comment]
This helps to show us if a coder is using the online web editor, which is what actually should be banned!

**Comment by Jordie0608** [comment]
I'd rather educate people on using a proper git client instead of the web browser, that way they'll have to write commit messages too. This is restrictive with little gain; just read the diff.

Even then what'll be done if the rule is broken? Does the PR get closed because of a commit message? If not there's little difference from just commenting to ask to write better commit messages.

**Comment by RemieRichards** [comment]
@GunHog no it shouldn't, people are able to use it perfectly fine (including commit names and commit messages), it's just some people abuse it.

**Comment by GunHog** [comment]
I disagree with you here, for the sole reason that I feel that someone who has used the web editor to build a commit is unlikely to have bothered to test his code. That is seriously my only objection to the web editor. Maintainers can (usually) be trusted to know their code works, but normal contributors, especially newer ones, should always be 'encouraged' to use the desktop client to increase the chance that their code gets tested.

After all, if someone is too lazy to write code in DM instead of the web editor, what is the chance that he bothered to test it, or even _compile?_

**Comment by RemieRichards** [comment]
And that is the abuse.
Compilation is covered by travis, and it's VERY obvious when someone hasn't done local testing (150 hours etc.), I stand by that abuse being punished rather than banning a useful tool.

**Comment by Cyberboss** [comment]
I blame github tbh

**Pull request closed without merging**
