### PR TITLE
Fixes for projectiles bugs

### LINKED ISSUE #42426: Plasma Cutter - Single Block?
Problem Description: Plasmacutter and Advanced plasma cutter only cut a single rock block at a time on Boxstation after the 1/18/19 update

What did you expect to happen: I expected the plasma cutter to cut 5 blocks, and the advanced to cut 10.

What happened instead: the plasmabolt stopped at the first block.

Why is this bad/What are the consequences: Makes deep-mining much more difficult to achieve.

Steps to reproduce the problem: It just seems to happen as if it was an unmarked update rather than a 'bug', it was affecting the other miners too.  Two games, three miners, 6 cutters used between us.

Server: /tg/Station 13 Bagil

Revision: Master commit: b9f1ca56d43f21abf6172b99604d8b315a751474
Local commit: d6b3dc5a3f7469cf31f9ca6a2f6c2e173c97196e
Server tools version: /tg/station 13 Server v3.2.5.1

Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?): Antags were blobs if that makes a difference.  Again the station was BoxStation.

Thanks for helping us out!

### LINKED ISSUE #42427: Reflector/Emitter Relation
Issue reported from  Round ID: 100471 (/tg/Station Terry [EU] [100% LAG FREE])

Reporting client version: 512

Seems like the reflectors in the SM area on metastation are not willing to properly reflect the emitter beams 
and choose to get hit instead. I've encountered that bug thrice by now in 4 months of playtime, that's not a very high number but it usually ended by either a  restart vote or very early shuttle call.

### PR DESCRIPTION
**Pull request by Menshin**
Thought the bugs (reflectors not working and plasma cutters stopping at first tile) were severe enough for a quick fix.

Properly fixing these would involve getting deeper into the projectile code (notably, `on_hit()` seems to have been overlooked ~~eand there's others `return` that have not been converted to the new `BULLET_ACT*` format, .g the laser cannon~~ Done lots of these. Pretty tought to choose between `BULLET_ACT_HIT` or `BULLET_ACT_BLOCK` in certain cases, but since they work the same for now, it's not really a problem).

Fixes #42427 and fixes #42426.

:cl: Menshin
fix: Reflectors now work properly
fix: Plasma cutters stop digging one tile at a time
fix: Various projectiles reflections have been fixed (human, glass golem, etc).
fix: heavy beam pulses are now penetrating correctly
/:cl:

### CODE REVIEW

**Review by silicons — APPROVED** [review]
sorry i missed those

**Review by SpaceManiac — CHANGES_REQUESTED** [review]
Emitter beams which get reflected start hitting multiple times

**Comment by Menshin** [comment]
> Emitter beams which get reflected start hitting multiple times

How naïve of me to think it was limited to the supermatter.
It's fixed.

I've also dwelve a little more in the code and fixed projectiles reflection not working and heavy beam pulses not penetrating.

Also, lots of little changes to use the new `BULLET_ACT_*` format (there's more, but there's not as straightforward as these).

**Comment by Daxxed** [comment]
Pls merge and force update Terry pretty pls.
Miners are stealing my hierophant because its the only half decent mining tool available now

**Comment by Menshin** [comment]
Just in case, ready for merging.

**Comment by kopoba** [comment]
I see its merged. But advanced plasma cutter still hit only 1 block.

**Comment by subject217** [comment]
servers probably not updated if you're talking about live, unless you have confirmed this on current code :^)

**Comment by Menshin** [comment]
Yes the server is not updated yet : it's on b1b7eb4, last commit from yesterday.

**Comment by TrueWOPR** [comment]
If this was implemented on Bagil it's still not working as of 4:00pm PST

**Comment by Menshin** [comment]
Bagil is still not updated according to the tgstation site (still on ee04738).

**Comment by subject217** [comment]
all the servers were updated earlier and the fix appears to work as intended so

**Pull request merged**
