### PR TITLE
Renames Charcoal to Anti-Toxin

### PR DESCRIPTION
**Pull request by Core0verload**
This is a very highly requested change among all /tg/ players.

### CODE REVIEW

**Comment by Jalleo** [comment]
#11349 you were already beat on this

**Comment by Core0verload** [comment]
You are wrong.

**Comment by phil235** [comment]
There's already an anti-toxin reagent https://github.com/Core0verload/-tg-station/blob/fuckgoof/code/modules/reagents/Chemistry-Reagents/Medicine-Reagents.dm#L823 . So if we decide to change "charcoal" to "antitoxin" then we have to rename or remove the old antitoxin.

**Comment by Fayrik** [comment]
Wasn't the old anti-toxin a legacy chem, for those situations where the newchems aren't appropriate? (Like admin fuckery and all that.)

Also, Anti-toxin is a pretty terrible name, it's just what it does. The old anti-toxin was infact called Dovelyn (or something like that), but wasn't always referenced as such, so no one remembered it's actual name.

**Comment by Core0verload** [comment]
Anti-Toxin is a Nanotrasen Fancy Brand Name for charcoal. Old antitox had the same effects as new.

**Comment by Iamgoofball** [comment]
Uh, no it didn't. Anti tox. And charcoal have different values.

**Comment by Core0verload** [comment]
Okay, it's actually two things diffirent in antitox and charcoal. Charcoal has no OD and metabolises 2 times slower. That's all. Healing speed is the same, effect on other chemicals is same too.

**Comment by Firecage** [comment]
So why rename it anyway? Since it isn't exactly uncommon knowledge that charcoal IRL helps for toxins and shit.

**Comment by Anonus** [comment]
Fuck you and the map conflicts you rode in on
:-1: 
I don't even care about the name, but this is annoying because of map and path edits.

**Comment by Core0verload** [comment]
Where are the map conflicts? I changed only outdated pathes with external find/replace tool. There is no huge map diffs.

**Comment by Iamgoofball** [comment]
Literally no point in renaming :-1:

**Comment by PKPenguin321** [comment]
there was literally no point in renaming it to charcoal either, goof

**Comment by Iamgoofball** [comment]
but it has a different recipe and different effect

**Comment by PKPenguin321** [comment]
this just in, every time a chem is rebalanced it has to get renamed or else the code wont compile

**Comment by Iamgoofball** [comment]
this just in, the point
-------------------------
               your head

**Comment by Rinoka** [comment]
>this just in, every time a chem is rebalanced it has to get renamed or else the code wont compile

this is not a rebalance, this is a flat rename. git gud

**Comment by PKPenguin321** [comment]
my point was goof renamed it to charcoal for a poor reason, and it was that he rebalanced it
this pr just rectifies something that never needed to be done in the first place

**Comment by Fox-McCloud** [comment]
Pointless and dumb. People are used to it being charcoal by now.

**Comment by xxalpha** [comment]
Why would spessmen be eating charcoal anyways, that's retarded.

**Comment by duncathan** [comment]
BECAUSE IT'S AN ACTUAL MEDICINE AAAAAAAAA 
https://en.m.wikipedia.org/wiki/Activated_charcoal_(medication)

**Comment by Razharas** [comment]
Strangely enough i agree with goof since chemistry is his field in general
I just hope he wont grow into numbers

**Comment by Razharas** [comment]
So verdickt - closed

**Comment by Iamgoofball** [comment]
@Razharas i approve of chemistry changes to fuck with chemistry

renames for the sake of renames/drama is no bueno though

**Pull request closed without merging**
