### PR TITLE
Cargo Resprite by Dragonfruits!

### PR DESCRIPTION
**Pull request by Imaginos16**
## About The Pull Request
Resprites our favorite cargonians into a tasteful QM-style brown color, as envisioned by spriter @Spc-Dragonfruits!
image

And yes, that includes the digitigrade versions!
image

## Why It's Good For The Game
The cargo outfits were some of the most dated, and messiest sprites in our lineup, with some strange inconsistencies such as the old QM pants having shorts layered on top of it, and the skirt on the back sprite being strangely misaligned. It also changes the yellow color to a brown akin to the QM, as to make them more aesthetically pleasing!

## Changelog

:cl: Dragonfruits, with some tweaks by PositiveEntropy
imageadd: The cargonian wardrobe has now been updated into a tasteful brown!
/:cl:

### CODE REVIEW

**Comment by Spc-Dragonfruits** [comment]
image

**Comment by MrMelbert** [comment]
image

I believe you're missing a sprite

**Comment by carshalash** [comment]
The title made me think we were getting dragonfruits. Downvoted for false advertisement.

**Comment by Fikou** [comment]
i think the colors are too light, they are practically whites instead of paper pushers with mundane greys

**Comment by Spc-Dragonfruits** [comment]
> The title made me think we were getting dragonfruits. Downvoted for false advertisement.

Maybe one day. You never know.

**Comment by Imaginos16** [comment]
> image
> 
> I believe you're missing a sprite

image

Not anymore baby!

**Pull request merged**
