### PR TITLE
adds foxgirls

### PR DESCRIPTION
**Pull request by RigglePrime**
But wait... this isn't code refactoring... this is an April fools PR! And a terrible one at that. What does it do? Find out yourself.

Thanks PositiveEntropy for the improved sprites, and thanks Cimika for the lore.

I'm probably getting lynched for this. At least it will be funny, right?

🆑Riggle, PositiveEntropy
refactor: Human code has been "refactored"
/🆑

### CODE REVIEW

**Comment by LemonInTheDark** [comment]
You people are the worst

**Review by Imaginos16 — COMMENTED** [review]
Speedmerge this NOW

**Comment by thgvr** [comment]
lets FUCKING GO

**Comment by Imaginos16** [comment]
Other than this, you should be ashamed at your creation. Good work.

**Comment by realthomas69** [comment]
fuck off

**Comment by Kylerace** [comment]
cool pr

**Comment by JohnFulpWillard** [comment]
NO NO NO

**Comment by thgvr** [comment]
Toasting in epic bread

**Comment by san7890** [comment]
WAIT WAIT WAIT

**Comment by LemonInTheDark** [comment]
The separation between me and that shit is absolute

**Comment by Kylerace** [comment]
conflicts

**Comment by Kylerace** [comment]
wait nevermind this is cool

**Comment by JohnFulpWillard** [comment]
this will cause issues

**Comment by LemonInTheDark** [comment]
I've changed my mind

**Comment by Kylerace** [comment]
SO TRUE BESTIE

**Comment by san7890** [comment]
This is unallowable from a mapping standpoint.

**Comment by TheSilverNuke** [comment]
I say let it live

What's the worst that could happen right? ... right?

**Comment by LemonInTheDark** [comment]
I'd fix the conflicts and merge, but @RigglePrime disabled maintainer write access, so I can't.
h

**Comment by Kylerace** [comment]
this is just like that book uh, 1984

**Comment by RigglePrime** [comment]
#65855 is better though, it fixes some issues

**Comment by RigglePrime** [comment]
@LemonInTheDark access enabled

**Comment by LemonInTheDark** [comment]
The moment has passed I'm sorry

**Comment by RigglePrime** [comment]
😔

**Comment by MoonDeer728** [comment]
what about boys

**Comment by LemonInTheDark** [comment]
🗞️

**Pull request closed without merging**
