### PR TITLE
Z Level Button: Redone and ReBETTER.

### PR DESCRIPTION
**Pull request by TheSmallBlue**
## About The Pull Request

Second crack at my z-level changing HUD button. I felt that my last attempt left a lot to be desired, so here I am with it again!

<details>
<summary> Images </summary>

Widescreen:
image
image

Non-widescreen:
image
image

Basic/Simple mobs:
image

</details>

TODOs:

- [x] Apply to cyborgs
- [x] Apply to xenomorphs
- [x] Sprites: Glass UI Style
- [x] Sprites: Detective UI Style
- [x] Sprites: Clockwork UI Style
- [x] Sprites: Operative UI STyle

I still wanted to get the PR up to both get feedback on this method and to see if I could garner a little bit of help with the spriting bit (PLEEEEASE)
## Why It's Good For The Game

The current button leaves a lot to be desired, mainly:

- It isn't applied to every possess-able mob
- It has weird positioning and sizing that doesn't match anything else in the game
- It's confusing and inconsistent to use (it straight up would not work for observers, and I had to add the option to do alt click to go down)

This PR aims to fix all this, and more!

- One, big, long button that matches other similar ones that already exist!
- Click the up arrow to go up, click the down arrow to go down. Always. No fuzz!
- Two types: Horizontal and Vertical! Choose whichever fits your needs!
## Changelog
:cl:
qol: The z-level button got a refresh! It's now applied to more places and it should be simpler to use.
/:cl:

### CODE REVIEW

**Comment by DaCoolBoss** [comment]
What sprites do you need, exactly?

**Comment by TheSmallBlue** [comment]
> What sprites do you need, exactly?

image

These, but drawn in each ui type (retro, xeno, detective, plasma, etc). And hell, maybe a redraw of these two too, they look quite ugly...
This screenshot is all I have with me right now, when I get home I'll export the sprites and upload them here

**Comment by TheSmallBlue** [comment]
Here:
floor_change
floor_change_v

**Comment by snailomi** [comment]
would you be able to make these buttons disappear when you use the toggle hotkey buttons? it feels like it'd fit

**Comment by TheSmallBlue** [comment]
> would you be able to make these buttons disappear when you use the toggle hotkey buttons? it feels like it'd fit

Uh, how do you mean?

**Comment by TheSmallBlue** [comment]
Ready! Here's some screenshots of the sprites i ended up making myself:


<details>
<summary> Images </summary>

Clockwork:
image

Detective:
image

Glass:
image

Midnight (Default):
image

Operative:
image

Plasmafire:
image

Retro:
image

Slimecore:
image

Trasen-knox:
image

Xeno:
image

Cyborg:
image

</details>

**Review by Wallemations — APPROVED** [review]

**Comment by TheSmallBlue** [comment]
Shit, I'm totally sleep deprived and I clicked something that maybe I shouldn't have. Oh well, it builds and looks the same so im sure its fiiine

**Review by Ghommie — APPROVED** [review]

**Pull request merged**
