### PR TITLE
Adds destination taggers to chemistry, kitchen and R&D lab

### PR DESCRIPTION
**Pull request by cedarbridge**
For Metastation, Boxstation, and Deltastation for use with the disposals mail system

Allows chem to mail products to departments, chef to arrange for food deliveries and R&D to send toys around the station without needing people to crowd around the department windows.  Should hopefully lead to a bit more office cooperation.  Might consider removing from R&D for balance reasons if required.

:cl: Cedarbridge
add: Added destination taggers to Chemistry, Kitchen and R&D.  Now you can ship your own products between departments like cargo does.
/:cl:

### CODE REVIEW

**Comment by Cyberboss** [comment]
What about wrapping paper?

**Comment by cedarbridge** [comment]
@Cyberboss Each of these departments already had wrapping paper.   The destination taggers are mapped to spawn on or next to these paper rolls.  I considered gift wrap as well, but decided against it and left that to cargo.

**Comment by jughu** [comment]
@cedarbridge WAIT SO YOUR TELLING ME YOU CAN USE ANY DISPOSAL AS MAILING SYSTEM?

**Comment by cedarbridge** [comment]
@jughu That's how the cargo mailroom works.  You warp a crate or package, hit it with the tagger, throw it on the belt and into the disposal system.  There are sorters built into the tubes that detect the tagger destination and route everything else to either cargo or onto the compactor.

Just realized I need to double check that Delta has those sorters.

**Comment by RandomMarine** [comment]
I always believed the process was supposed to be like this.

Kitchen/R&D/chem wrap a package.
Write their intended destination with pen.
Cargo receives the package.
Dutiful Cargonian tags the destination according to the note.
Package is sent on its way to the receiver.

Problem is hardly anyone ever pays the cargo office any mind so it just piles up with junk.

This cuts out the cargo reliance, though someone still needs to turn the belt on. Which, while a good thing, I'd prefer see more incentives for a cargo tech to manage the office.

**Comment by cedarbridge** [comment]
@RandomMarine The problem is that the mail sorting shares a belt and tube system with all of the garbage.  Cargo doesn't care what comes in because its 99% garbage.  the only use I've seen from cargo in the office is to mail crates arriving off the shuttle.  I think that's well enough and cargo can use the stop/start lever to sort through the trash for recycling/re-purposing if they'd like.  

I feel having the mail not reliant on inattentive cargo techs is the better way to go about it just for ease of use.

**Comment by RandomMarine** [comment]
Ideally, someone should be manning the office to sort through the stuff coming through. Many players don't realize that lots of "trash" sent down disposals have recycle value in the autolathe.

Again, this is a good change considering the current circumstance, I'd just rather see something done to make the office more appealing to manage.

**Comment by optimumtact** [comment]
you need to fix the conflicts but I think on the balance of things here thsi sould be merged unless the mail system is reworked so that every department has their own tagger to tag the final destination but it goes to the mail room first and spits out a different chute and then the cargo team can reroute it.

**Comment by cedarbridge** [comment]
This PR broke.  I'll have to resubmit.

**Pull request closed without merging**
