### PR TITLE
Adds portable seed extractor to ash walkers

### PR DESCRIPTION
**Pull request by Daturix**
take 2, used mapmerge.

### CODE REVIEW

**Comment by Quardbreak** [comment]
> Daturix:master

aaaaaaaaaaaa

**Comment by Repukan** [comment]
>tribal spear chuckers based on hunting knowing how to use advanced agricultural devices

**Comment by Mindustry** [comment]
Why though?

**Comment by Cruix** [comment]
They have an RCD already, and being able to farm just means that there might be one less ashwalker trying to get to the station to murder everyone.

**Comment by Daturix** [comment]
discussion on coderbus went along many topics, one coming to some ash walkers wishing to plant the various lavaland plants and be able to do more with the botany crate they have besides glowshrooms.

I hope to be able to add the ability to farm these plants not only for ash walksers to allow them to do more with what they have but also allow miners to gather seeds for botany for more plants.

Repukan, how can a tribal lizard person use an advanced building tool like th RCD?

**Comment by Repukan** [comment]
True enough.

**Comment by Repukan** [comment]
I wish I knew how to edit comments

Anyhow, it never sat well with me that they could use them. However because of the other stuff you find in the nest (sing beacon, malf disk) one could say it's stuff looted from other mining expeditions?

**Comment by Daturix** [comment]
I have always thought that through scavaging from the dead miner ruins or ruins themselves they have collected a odd array of objects and wish to learn more as with their goal is to grow the den thus they need to learn more of whats in their homeland.

**Comment by optimumtact** [comment]
why do they need a seed extractor to do botany?

**Comment by Daturix** [comment]
Currently ash walkers cannot reproduce any seeds.

**Comment by optimumtact** [comment]
dude what happened to plants dropping seeds on harvest

**Comment by Daturix** [comment]
Playing botany as we speak and I dont see that.

**Comment by Daturix** [comment]
Nice meme

**Comment by FantasticFwoosh** [comment]
Plants need processing which with the terrible rate of efficiency (1 plant for 1 seed) will make it very slow. Even so there's barely anything beside towercaps worth growing, out of the weeds besides glowshroom for ashwalkers.

Its a better alternative to making 50 plus trays for free top ups of water (weeds therefore mandatory) and nutrients which are hard to get without slathering on other plants as compost or using goliath meat/steak.

**Comment by Mindustry** [comment]
The guthens give nutrients.

**Comment by FantasticFwoosh** [comment]
@Mindustry where did you source that information? Guthens spit out 2/3 salbutomol and 1/3 milk which aren't nutrients at all.

Most nutrients will probably come from farming plump helmets since they seem to be the most jam packed with them per-piece from the selection of weed plants.

**Comment by Daturix** [comment]
As with goofs attempt to add more flora and trees this will be quite a need to be able to continue any botanical things. Along with my plan to add a way to replant lavaland mushrooms which would allow them to do serious botanical work. 
Last checked the guthens gave saline-glucose solution which had 33% per tick to heal either brute or burn as the ash walkers dont need the same air and those are the 2 main damage types in lavaland.

**Pull request merged**
