### PR TITLE
Lava proofs spell movement holders

### LINKED ISSUE #13252: Lava burns things it shouldn't burn
Like jaunt holder objects and other effects, as well as things that shouldn't burn because they have a burn state of -1 THIS IS WHY THEY HAVE A BURN STATE OF -1 @KorPhaeron

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
Since the initial report was about these, fixes #13252

This also lava proofs the singularity (and nar-sie)

If people want more items lavaproofed they're gonna have to ask specifically cause I can't search through every obj path in the game deciding if each should be fireproof.

### CODE REVIEW

**Comment by optimumtact** [comment]
Why didn't you just use the flammable flag?

**Comment by KorPhaeron** [comment]
I wanted stuff like lockers and mechs to burn up in lava

**Comment by optimumtact** [comment]
I guess

**Comment by optimumtact** [comment]
update to latest master
git rebase -Xignore-all-space upstream/master

**Comment by KazeEspada** [comment]
Atmos hardsuits.

**Pull request closed without merging**
