### PR TITLE
Players can now reorder items inside storages by dragging them

### PR DESCRIPTION
**Pull request by SmArtKar**
## About The Pull Request

https://github.com/user-attachments/assets/8949965f-a78a-4f3d-b528-afcdfe5c4e72

Drag'n'dropping items inside of an open storage that you can access will reorder them. I had to register dropping onto items themselves instead of cells as they ignore icon transparency when in storage for QOL reasons, so bear with that.
## Why It's Good For The Game

Reordering your storage currently requires taking out all items in front of position that you want a certain item to be and putting them back in which could be rather annoying with large storages.

## Changelog
:cl:
qol: You can now reorder items inside storages by dragging them
/:cl:

### CODE REVIEW

**Comment by Sadboysuss** [comment]
what happens if I want to transfer items from box A to box B? Would it transfer the items from click dragging or would they change places in the storage container?

**Comment by MTandi** [comment]
Does it work for stacked items? Like fruits in botany bag, or parts in construction bag.

**Comment by EuSouAFazer** [comment]
YES, YES YES YESSSSSSSS Smartkar goated

**Comment by mc-oofert** [comment]
do people actually play resident evil with their storage

**Comment by SmArtKar** [comment]
> what happens if I want to transfer items from box A to box B? Would it transfer the items from click dragging or would they change places in the storage container?

Transferring between objects works, but you no longer try to dump stuff "onto" objects in storage that don't have storage of their own (resulting in stuff spilling out from your bag in a weird fashion)

> Does it work for stacked items? Like fruits in botany bag, or parts in construction bag.

Good point, yeah, I need to fix that. Forgot about those.

> do people actually play resident evil with their storage

A surprising amount of people do, yeah. I've seen most folks prefer their storage boxes/smuggler satchels to be first in storage and smaller stuff to come afterwards

**Comment by Sadboysuss** [comment]
> resulting in stuff spilling out from your bag in a weird fashion

Can you add a check for if the item you're drag dropping onto has storage so that doesn't happen? Imagine how horrible it would be to spill your SM sliver kit because of a qol.

**Comment by SmArtKar** [comment]
> > resulting in stuff spilling out from your bag in a weird fashion
> 
> Can you add a check for if the item you're drag dropping onto has storage so that doesn't happen? Imagine how horrible it would be to spill your SM sliver kit because of a qol.

I fixed said issue, not added it. So dragging your kit onto other things into your backpack wont spill it out (like it does rn)

**Comment by Sadboysuss** [comment]
> I fixed said issue, not added it. So dragging your kit onto other things into your backpack wont spill it out (like it does rn)

hell yeah, awesome.

**Comment by alien3301** [comment]
Does this work with integrated storages like drone and borg inventories?

**Comment by SmArtKar** [comment]
> Does this work with integrated storages like drone and borg inventories?

those aren't storage

**Pull request merged**
