### PR TITLE
Pets (and Beepsky) are a higher priority for random sentience events

### PR DESCRIPTION
**Pull request by coiax**
:cl: coiax
add: Pets will be selected first to gain self awareness before other simple mobs during a sentience event.
/:cl:

This is to solve the "sentient slime in Xenobio" problem. Instead, we'll go through the types of starter pets that the station has, and put someone in control of them instead. If they're all dead, then you go to the extended cockroach, mice and slime pool.

This also increases the chances that Ian will spontaneously become self aware.

### CODE REVIEW

**Comment by funnyman2003** [comment]
Not a very good idea. The slime is only a problem if there's no active xenobiologist anyways. It would be the exact same as getting a sentient renault or such secluded pets...

**Comment by Ziiro** [comment]
Mind adding Janitor buckets, Beepskys, ED209s, and Medibots to the list? Without it, I doubt we'll ever see one of those again.

**Comment by kriskog** [comment]
How about removing slimes from the pool if they are causing issues? Xenobio can make sentience potions and there are other slime sentience events, it probably wouldn't be missed.

**Comment by HydroFloric** [comment]
Don't merge this or else we will never see the wonder that is suddenly sentient beepsky again.

**Comment by coiax** [comment]
@Ziiro all of those, except Beepsky, can be accomplished with using a pAI.

**Comment by fluffe9911** [comment]
Can you add the cargo roller thing as well thats fun to play as and I dont think you can pai it

**Comment by coiax** [comment]
MULEbots can be pAId.

**Comment by Peeping-Peacock** [comment]
> 
> 
> @Ziiro all of those, except Beepsky, can be accomplished with using a pAI.

Cant pAI ED209 sadly.

**Review by SpaceManiac — APPROVED** [review]

**Pull request merged**
