### PR TITLE
Changes whetstone sprite

### PR DESCRIPTION
**Pull request by dannno**
Before & After

you could say this is a fix
it fixes the whetstone being a fuckhuge piece of shit

### CODE REVIEW

**Comment by Arianya** [comment]
Looks like starburst

**Comment by ma44** [comment]
Starbursts!

**Comment by dannno** [comment]
when I get admin there are going to be some rapid bans

**Comment by Arianya** [comment]
Rapid as the burst of tangy, fruity taste of starburst on your tongue from the first bite?

**Comment by kilkun** [comment]
now make it craftable

**Comment by ma44** [comment]
The old sprite should be for butter.

**Comment by dannno** [comment]
no it's terrible if you want a butter sprite I can make one that isn't TERRIBLE

**Comment by Nienhaus** [comment]
uabrnvw
Butter?

**Comment by dannno** [comment]
nice.

**Comment by Supermichael777** [comment]
dautum cooking when?

take recipes out of strange table crafting/slap-crafting limbo when(I suggest actually fleshing out the kitchen to be more then microwaves)?

**Comment by dannno** [comment]
what the FUCK DOES THAT HAVE TO DO WITH ME

**Comment by WJohn** [comment]
pretty much anything is an improvement.

**Pull request merged**
