### PR TITLE
64x64 SS13

### PR DESCRIPTION
**Pull request by Iamgoofball**
Credit goes to @PJB3005 for all his work with python on the needed converter scripts to upscale everything with Nearest Neighbor.
:cl: PJB3005, /vg/station and Iamgoofball
experiment: The game now uses 64x64 and higher base sprites for everything. This will allow for loads more detail when it comes to sprites.
/:cl:

TODO:
- [x] Icon Conversion
- [x] Map Conversion
- [x] Code Conversion

EXAMPLES:
example1
example2
example3

### CODE REVIEW

**Comment by PJB3005** [comment]
If any other codebase wants to do this, here's the scripts I made: https://gist.github.com/PJB3005/1f8911552b251672ad582f4f3a92af80

**Comment by xxalpha** [comment]
>todo code conversion

what do you have to do

**Comment by RemieRichards** [comment]
@xxalpha things that assume 32x instead of ```world.icon_size```, all code driven pixel offsets (need to be doubled, like the maps' were)

Overall I don't really support this, it's a double edged sword.

**Comment by Iamgoofball** [comment]
How is it double edged

**Comment by RemieRichards** [comment]
All art takes 4x as long to produce (yes, 4!, because you're doubling in two directions).
Art takes long enough to get made around here, do you really want to quadruple it?

**Comment by PJB3005** [comment]
@RemieRichards you can just make a 32x32 and then nearest neighbor upscale it.

**Comment by RemieRichards** [comment]
@PJB3005 while true (and ironically talking on this PR, something I forgot), it goes against what goof claims this is for: ```This will allow for loads more detail when it comes to sprites.``` There's no more detail, none, there's just 4x the pixel density.

**Comment by Iamgoofball** [comment]
Why don't we consult the actual spriters

**Comment by PJB3005** [comment]
@RemieRichards You're missing the fact that it says *allows*. You can convert and upgrade sprites as needed, no rush.

**Comment by Jordie0608** [comment]
@RemieRichards It does indeed allow for the possibility of more detailed sprites, there just aren't any in this PR.

I don't think time is much of a concern compared to the boons from larger dimensions, especially when it comes to something like in-hands and on-mob sprites.

**Comment by xxalpha** [comment]
I am okay with 64x64, but how does this affect users with smaller screens?

**Comment by RemieRichards** [comment]
@Jordie0608 did you ignore everything I've said? I'm saying just drawing 32x32s and up-scaling them goes against what goof claims the 64x64 is for, which it does! to then tell me "uh but 64x64 does allow for more detail" is pointless, I know it does, but you know what doesn't? -still drawing them at 32x32-

@PJB3005 you underestimate human laziness, 32x32 is infinitely easier to draw (some might say... 4x) if our (already overworked) spriters get requests for 64x64s, what do you think they're going to do now? it should be pretty obvious they'll take the quicker route (and even if they don't, we're back at the longer wait times!)

**Comment by Iamgoofball** [comment]
Solution: do the main work at 32x32, upscale, then federal at 64x64

**Comment by RemieRichards** [comment]
@Iamgoofball cos that'll totally look cohesive and not shit.

**Comment by Thunder12345** [comment]
A mixture of upscaled 32x32 and full 64x64 sprites would probably look worse than all 32x32

**Comment by Iamgoofball** [comment]
I'll explain better tomorrow when I'm not on a phone

**Comment by Thunder12345** [comment]
I don't get what the examples are for, anyway. They're all just existing sprites.

**Comment by Iamgoofball** [comment]
Demonstrating the scaling

**Comment by Thunder12345** [comment]
So you've achieved something that takes 10 seconds to do in MS Paint and called it an example? How about a demonstration ofwhat a mixture of 32x32 and 64x64 sprites looks like?

**Comment by Iamgoofball** [comment]
Are you fucking kidding me, please fuck off and die

**Comment by xxalpha** [comment]
He's on his phone, he can't post sprites now.

**Comment by Thunder12345** [comment]
And yet instead of saying he'll get something like that done his first reaction is to tell me to fuck off and die?

**Comment by RemieRichards** [comment]
@xxalpha he also didn't have to make the PR right now, he could have waited till he had actual examples.

**Comment by PJB3005** [comment]
@Thunder12345 


If you look very closely you can see that I made the little bits in the top and bottom middle of the floor turfs slightly more precise with 64x64 sprites.

**Comment by xxalpha** [comment]
@Thunder12345 You are not being nice either.

**Comment by PJB3005** [comment]
@xxalpha
> I am okay with 64x64, but how does this affect users with smaller screens?

Any screens below 1080p will just have more precise downscaling from 64x64 than the upscaling from 32x32 (where the sprites make use of the added precision) so it doesn't actually change anything for these people.

**Comment by Iamgoofball** [comment]
They are literally examples of sprites passed through the converter holy fuck read the OP

**Comment by Thunder12345** [comment]
But I still don't understand the point of putting scaled up sprites in the OP with nothing to compare them to. You can get the exact same effect by using the 64x64 scaling in game if you want to see what they look like at 64x64

**Comment by Iamgoofball** [comment]
I'm done arguing with you, you're ignoring thepoibt of this and STILL NOT READING THE OP

**Comment by Thunder12345** [comment]
You've never actually answered my question. What is the purpose of random 2x size sprites in the OP?

**Comment by RemieRichards** [comment]
@Iamgoofball Don't talk shit behind people's back goof, " i expected better"

**Comment by PJB3005** [comment]
Okay TL;DR
# THERE IS NO VISUAL DIFFERENCE RIGHT NOW. ALL THIS DOES IS ALLOW SPRITES TO BE HIGHER PRECISION WHICH IS :+1: FOR EVERYBODY.

**Comment by Thunder12345** [comment]
So there's no purpose to this excapt a few cases where you want a little bit more detail, and in return everyone needs an extra step to make new sprites?

**Comment by PJB3005** [comment]
> So there's no purpose to this excapt a few cases where you want a little bit more detail

Yes.

> and in return everyone needs an extra step to make new sprites?

No unless the spriter in question's an idiot.

**Comment by Thunder12345** [comment]
So if a spriter isn't an idiot they don't have to remember to run their sprites through some script just to satisfy a couple of people's need for some tiny details?

**Comment by PJB3005** [comment]
> https://github.com/tgstation/tgstation/pull/19566

Dear god how fucking hard is it to scale your sprites 2x. If you're using any sort of decent image editor this isn't an issue.

**Comment by AnturK** [comment]
Script is only needed to upscale current sprites. 

Anyway i'm not against the idea but this PR is worthless without code changes and i don't really see why it was opened already.

**Comment by Iamgoofball** [comment]
I thought you were in the IRC at the time, my client on the phone hides user lists

**Comment by Thunder12345** [comment]
Actually a quite significant effort once you take into account 2 hands x 4 directions x the number of different base states for inhands, 4 directions x the number of different base states for on mobs, etc. That's a lot of work to produce already, before having to scale them all up. It's hard enough to get art already, will this extra effort make it any easier to get the sprites we need?

**Comment by Iamgoofball** [comment]
@remierichards

**Comment by Skullyton** [comment]
But a larger canvas size means more fun

**Comment by Thunder12345** [comment]
More fun/detail yes, if people use it, but it's also 4x the effort to produce a proper 64x64 sprite, and extra effort to scale up a 32x32 sprite for more benefit

**Comment by Iamgoofball** [comment]
You don't know what you're talking about

**Comment by Thunder12345** [comment]
How so?

**Comment by Jordie0608** [comment]
@Iamgoofball How much larger is the icons folder with this?

**Comment by xxalpha** [comment]
So is this just downscaling 64x64 to 32x32 for higher detail or ?

**Comment by Jalleo** [comment]
I dont care aboutanyones input but @WJohn let them be the final say on this.
If its just a script to prevent extra work that is fine and we can just take sprites from other codebases that are higher in detail.

**Comment by Iamgoofball** [comment]
I'll check sizes of decompiled and compiled in . morning

**Comment by Nienhaus** [comment]
I personally really like this.

**Comment by PJB3005** [comment]
The icon folder increased by approximately 4 MiB when I did this on /vg/: https://github.com/d3athrow/vgstation13/tree/64x64

Note that I did "cheat" by running optipng on all DMI files while I was at it. I suggest you do the same since you need to do EVERY ICON anyways.

**Comment by Notamaniac** [comment]
Hobbyist noob spriter here

One of the main issues I find with 32x32 is the lack of detail you have, every single pixel you have to put down is far more important. With 4x as many pixels, you can be a lot more lax with your pixel placement and planning; you can afford to make less compromises regarding the raw space (i.e one pixel in 32x32 can horribly unbalance a sprite, while one pixel in 64x64 is a lot less noticeable) .

In regards to 4x as much work regarding sprites, a lot more time and effort goes into actually making and planning the linework of the sprite, rather than actually drawing the lines. As I said before, more space is easier to work with, and easier work can be done faster. Overall it'd probably be the same amount of time making the sprite, accounting for the extra shading you might want to do.

Oh and in case this detail hasn't been stressed enough, you can put a fuckload more detail in 64x64 than 32x32, and this shouldn't be overlooked.

**Comment by NigglyWiggly** [comment]
I'm not a fan of this.
64x64 removes the _fun_ of making a sprite look recognizable at such a small size.
It'll also lead to everyone being really unsatisfied if you make normal, 32x32 sprites instead of 64x64 ones, and god knows it's going to look awful when some objects have new sprites and others look all pixelated in comparison. 
Was there really a problem with 32x32? Was there a demand for this?

Also Goofball if you don't get why just putting scaled up sprites in your PR while talking about more detail, but not actually showing any additional detail is dumb, you might have brain problemos. I mean I get it, they're an example of scaling them up and all, but that's not a good example of what this PR is actually trying to accomplish, I'm assuming.

**Comment by Iamgoofball** [comment]
>64x64 removes the fun of making a sprite look recognizable at such a small size.

This is one of the reasons it's harder to get sprites for ss13

>Was there really a problem with 32x32? Was there a demand for this

Yes, not enough room to work with. Also yes.

**Comment by Skullyton** [comment]
Okay, if you're wanting an example, here's one somebody drummed up yesterday when we were discussing 64x64

image

While 64x64 does give you more room for HD sprites, it also comes with the problem of mixed-size pixels when put side by side with a simply upscaled sprite, so things will stick out a wick for a bit if HD sprites are brought in while others are left in the dust.

**Comment by Nienhaus** [comment]
That looks fucking cool Skully, Might help to curve it a bit in places though.

**Comment by Iamgoofball** [comment]
Having an orgasm over that much right now

**Comment by NigglyWiggly** [comment]
Yes 64x64 allows for more detail and stuff, but is that really worth ruining what little consistent style SS13 currently has?
Also Mixels make me want to smash my head into a wall

**Comment by Iamgoofball** [comment]
We don't have any consistent style every PR has a different style and spriter

**Comment by NigglyWiggly** [comment]
Also here's this, from the same place Skully got his sprite.

**Comment by GunHog** [comment]
@WJohn

**Comment by GeneralGoose** [comment]
is it more work? you get more space and my problem with 32 is having to fucc to make use of every pixel

**Comment by Thunder12345** [comment]
Oh, and if you want to edit an existing sprite that's a scaled up 32x32, you have to change 4 pixels for every 1 in the original

**Comment by blobbernaut** [comment]
Shit, I'm getting a huge Risk of Rain vibe from that Odysseus. 

All the arguments against this are "but it's going to take a lot of work" which a spriter came in and refuted so I'm not sure what the discussion here is.

**Comment by WJohn** [comment]
No. Absolutely not okay with this.

Main reason is mixed pixel sizes, it's one of the golden rules of spriting and it's because breaking it makes your sprites look like horseshit. Our sprites are bad right now yes, but it's for other reasons. Let's not add to it and make them look even worse.

If you have a program that magically goes around and properly upscales everything without leaving nasty-ass blurs then it will still need huge amount of hand-made adjustments, this would be a gigantic nightmare project in the best case scenario.

**Comment by Jordie0608** [comment]
@WJohn This (and BYOND usually) uses nearest-neighbour interpolation; there's no mixed pixel sizes or blending. According to goof a python script was used here but almost any non-MS Paint image editing software can do upscaling with selectable interpolation.

**Comment by Incoming5643** [comment]
My vertical resolution is only 900px so I have to downthumber this on principle. Stretch to fit looks like ass enough without entire pixels just straight up missing.

**Comment by PJB3005** [comment]
@Incoming5643 I hope you realize this does absolutely nothing different for you. In fact the higher precision sprites will scale down better than they would scale up (at 900p the scaling up from 32 is worse than scaling down from proper 64 sprites)

**Comment by Incoming5643** [comment]
But that's supposing that I always want to play on stretch to fit, which I don't. I'd rather scale down to a nice x1 than a x2 that's just a little too big for my screen, but with this even x1 is too big.

Also according to stuff like this http://www.w3schools.com/browsers/browsers_display.asp almost half of computers don't have 1000px vertical resolution.

**Comment by PJB3005** [comment]
\> Citing W3schools as a source for anything.

Also, with how BYOND's map control works the current 64x64 mode you can select (2x) works as a 1x and 32x32 works as 0.5x when using 64x64 icons. So actually this changes absolutely nothing.

**Comment by Incoming5643** [comment]
Running the game in stretch to fit (or in higher X modes for that matter) makes my gpu run hotter, but that is probably a pretty obscure problem because potato computer.

---

> Citing W3schools as a source for anything.

THIS AIN'T NO THESIS DEFENSE I'M JUST TRYING TO SURVIVE

:last_quarter_moon_with_face: G O S H :first_quarter_moon_with_face:

**Comment by Giacom** [comment]
This is a great future proofing change. Obviously the upscaling is going to look noticeable on some sprites but once it is cleaned up the game is going to look very sharp.

Your monitor's vertical resolution only needs to be over 640 (64 * 10 (tiles)) to get a crisp, non-stretched, picture; which I am sure 99.9% of people will have.

**Comment by PJB3005** [comment]
Uh the view range is larger than that.

You basically need a 1080p display to perfectly fit it.

**Comment by Incoming5643** [comment]
View range is 15 tiles, 7 in each direction and the center column/line.

If you're implying that stretch to fit tries to put the fudged pixels on the outside edges where they'd be less obvious, I'm gonna say that that's not how it works from my experiences.

**Comment by Giacom** [comment]
Sorry, got the number of tiles shown wrong.

**Comment by Incoming5643** [comment]
That said reducing the playing area of the game could make this work, but I think people would (understandably) riot

**Comment by JJRcop** [comment]
How does this affect icon procs, do they get 4X more expensive?

**Comment by PJB3005** [comment]
@JJRcop uh... That's a really good concern actually/

**Comment by Metacide** [comment]
This sounds really great.

Other than mixed 32/64 sprites which is a taste issue more than anything, and one which presumably will get better, are there actually any problems with this? Filesize an issue at all? I don't get all the hate here it sounds really super handy and should allow things to be much nicer in future (as Skullyton/NigglyWiggly showed).

**Comment by Incoming5643** [comment]
Anything that makes it harder to retain/gain spriters is a bad change. We're already almost completely out of these guys.

**Comment by Giacom** [comment]
The icon procs is a good point but it's a very BYOND issue with the image processing being done server-side and then being transmitted to everyone. Blood for example could easily be done on the client side.

**Comment by GunHog** [comment]
@WJohn is our only consistent spriter (And the art director). Ausops appears randomly, Nienhaus left for greener pastures, John Oxford's reputation leads the community to defecate on him, and I have not seen any activity from Steelpoint lately. We have some other spriters that make things as a one-off deal.

I do not understand the full implications of this PR, but I do hope it is something that attracts artists, not scares them away!

**Comment by xxalpha** [comment]
Icon procs are already prohibitively slow, just avoid using them at all costs, problem solved.

**Comment by clusterfack** [comment]
Color matrices and plane masters exist now, there are only a few select things that you need icon procs for in this day and age.

**Comment by ike709** [comment]
I like how most of the complaints regarding the spriting are from non-spriters, and the ones from actual spriters have to do with consistency and mixing the old low detail sprites with the new 64x64 sprites more than any actual increased difficulty in spriting.

:+1: x :100: This is great.

**Comment by Iamgoofball** [comment]
by the way here's an example of Rat'Var scaled up.
ratvar

**Comment by NigglyWiggly** [comment]
Why would you scale up an already higher-than-average sprite

**Comment by Iamgoofball** [comment]
alright now we know you're a fucking idiot

**Comment by NigglyWiggly** [comment]
That means so much coming from you.

What I'm saying is this doesn't really show us much.
I'm assuming Rat'var is as large as Nar'sie.
Since this literally just Rat'var's sprites but scaled up, it doesn't really show much more than your ability to use an image editor, but I assume your scripts did it. If you want to show any actual benefits of doing this you should post some comparisons showing the capability of more details or some shit, because scaling up sprites does dickall.

**Comment by xxalpha** [comment]
The benefit is you have a larger canvas and this lets you put more detail into sprites.

**Comment by ChangelingRain** [comment]
The only immediate benefit is that transforms will look better, but goof hasn't provided any shots of that because who the fuck knows it's goof.
Instead he's just posting the larger images, which mean basically fuckall on their own.

**Comment by Supermichael777** [comment]
design process for new sprites.
take old sprites and upscale
do detail finishing work
???
non-profit

**Comment by Thunder12345** [comment]
@ike709 I'm an actual sprinter when I find something that I'd be interested in doing

**Comment by Iamgoofball** [comment]
>actual sprinter
chrome_2016-07-29_14-39-16

**Comment by PKPenguin321** [comment]
le u spelled somethin wrong XD

**Comment by TechnoAlchemisto** [comment]
Goof stop losing all composure as soon as anyone shows you adversity, it's embarassing.

Anyways if we move to 64 the expectation is going to Sprite in 64 which has its own sets of boons and banes. 
High tier works will be better but beginner works will look much worse, this is coming from someone who has been spriting for a year, without an art background , who can produce mediocre sprites.

Not to mention a mix would really look sucky and nobody wants to bring everything up to 64x64 in terms of detailing  

On the other hand, those mech sprites look amazing and stuff like that would give the game a better feel and might bring more players to it, given plenty of people get turned off by the art style.

**Comment by MrStonedOne** [comment]
Nothing but good can come of this.

If people expect 64x64 and a sprite doesn't want to do 64x64 they can tell them to fuck off.

**Comment by MMMiracles** [comment]
Pixel density is gonna look like ass once people start adding 64x64 sprites with majority still technically being 32x32 like @WJohn said, but honestly being able to get that extra space for drawing out assets is gonna be super helpful and will help pave the way for at least someone down the line to make the game as a whole look less ass.

Also anything that helps make 'stretch to fit' look less ass is a :+1: in my book.

**Comment by WJohn** [comment]
As others have discussed in coderbus, if VG wants to give this a shot they can go ahead and try, but we simply do not have enough spriters to give this a shot since I estimate there's probably around 20,000 sprites in game, even if a lot are minor variations this would be a ridiculous workload to resprite the whole damn game (and of course fighting ENDLESS player adversity because graphical changes are REALLY HARD to get accepted even if they're objectively superior).

**Comment by JJRcop** [comment]
What if we got rid of the output and verbs skin stuff and made it ourselves in ui overlaying the map?

**Comment by clusterfack** [comment]
The skin should have been replaced ages ago to be honest, it's just so fucking BYOND

**Comment by Bawhoppen** [comment]
goof will never finish this dont get your hopes up

**Comment by Steelpoint** [comment]
itt Luddites vs Progress.

**Comment by RemieRichards** [comment]
@Steelpoint I know! How could people possibly want to move to such horrendous work times!

**Comment by KazeEspada** [comment]
Actually larger sprites are easier to make than 32x32 ones.

**Comment by RemieRichards** [comment]
@KazeEspada Make me a 1080x720 sized sprite then, with proper detail.

**Comment by KazeEspada** [comment]
Thats called a wallpaper?

**Comment by RemieRichards** [comment]
@KazeEspada My point is you're being stupid, "Larger sprites are easier to make" is a generalisation, a 32x32 is easier to make than a 1080x720.

**Comment by Nienhaus** [comment]
Here you go Remie, you didn't say what of.
untitled
I call it box with almostish rounded corners.

**Comment by RemieRichards** [comment]
@Nienhaus ha-ha.

**Comment by Ausops** [comment]
>64x64

wew lad

w e w l a d

W E W  L A D

**Comment by Iamgoofball** [comment]
>goof will never finish this dont get your hopes up

Good thing is

**Comment by Iamgoofball** [comment]
VG is

**Comment by RemieRichards** [comment]
@Iamgoofball you have bigger memes to meme right now, go look at the leaked CM source.

**Comment by GunHog** [comment]
Please finish Guncrafting.

**Comment by Iamgoofball** [comment]
@GunHog this is one of those "regain will to live" projects

**Comment by Jordie0608** [comment]
@Ausops Our players are all babies so having a small mob size would be more realistic.

**Comment by Shadowlight213** [comment]
@MrStonedOne we really don't have enough spriters to tell them to fuck off about not doing 64x64.
I mean unless @Iamgoofball is offering to make sprites and all the spriters who support it are offering to work harder to also make up for spriters who don't support it and would likely quit,

**Comment by PKPenguin321** [comment]
Is it not possible to fit the script into some kinda thingy where you just drag a 32x32 dmi onto it and it poops out a 64x64 version

Just a drag and drop would mean literally a half second of extra effort

**Comment by Ausops** [comment]
re: no sprites

can't this be implemented and the current sprites be upscaled while /vg/, /tg/ and whatever codebases gradually build up a workable collection of 64x64 sprites to do a mass replace instead of an incremental one, if the fear is mixing different tile sizes together

**Comment by Skullyton** [comment]
So, rather than everyone complaining about 'Oh, the sprites'll all look like shit', why don't we start working on making them not look like shit?

I'll work on the wall mounted stuff (APCs, Fire alarms, Air alarms, etc.) somebody grab vending machines, we'll have this done in no time

**Comment by Cheridan** [comment]
https://www.youtube.com/watch?v=YgcbJUuPKXk

**Comment by xxalpha** [comment]
Why are you ignoring the picture posted by PJB

**Comment by MrStonedOne** [comment]
>@MrStonedOne we really don't have enough spriters to tell them to fuck off about not doing 64x64.

No, I meant that spriters can tell people to fuck off if the spriter doesn't feel like doing 64x64 and people are trying to get the spriter to.

**Comment by Iamgoofball** [comment]
yeah, and even if they just wanna do 32x32, we got that covered because we can just convert it after they sprite it

**Comment by WJohn** [comment]
http://boards.4chan.org/vg/thread/150028725/spessmen-on-a-spess-station-ss13g#p150067469

Goofball if this post and these parameters for your spriter recruitment are your idea of how to handle 20,000 sprites, effectively reverting our art quality to oldstation's days AND wasting all THEIR and MY time when I inevitably clean up after their shit, it's reason enough for me to close this. 

We can try this when we have more than one or two active spriters who can actually handle the workload and some art already prepared to get the bulk of this done.

**Comment by Man-Shroom-** [comment]
here is the above link on an archive site for when that 4chan thread is inevitably deleted

https://boards.fireden.net/vg/thread/150028725/#150067469

**Comment by Iamgoofball** [comment]
I was joking holy fuck, read the thread, reopening this when I get home

**Comment by MrStonedOne** [comment]
"No progress until we can have 100% progress"

Perfection is the enemy of progress.

Maybe I should shut the server down until all of the bugs are fixed?

**Comment by clusterfack** [comment]
I mean I think it seems fairly clear to me the optimal way to proceed.
Step one
Make the code 64x64 (and identical to the current revision of ss13)
Step two
Update sets of sprites sequentially so they don't mixel
- Touching up all floors/walls at once
- Touching up all mechs at once
- Touching up all human mobs at once
- Touching up simple animals at once

You will NEVER be at a point where there is a binary all 32x32 -> all resprited 64x64. And its extremely rare that a project that would be completely stalled until everything is sprited would never gather interest.

**Comment by Cheridan** [comment]
I'm with MSO. 

If this is something that /vg/ is doing then we need to get on board as well. It'll be better for both of us in the long run.

**Comment by Incoming5643** [comment]
>If this is something that /vg/ is doing then we need to get on board as well. It'll be better for both of us in the long run.

If someone else is doing this we can wait and see if there's any horrible unforeseen consequences of doing this without expending any effort. The fact that someone else is doing this first is a reason to wait, not to rush.

**Comment by xxalpha** [comment]
Wake up Mr. WJohnston and smell the ashes.

**Comment by Bawhoppen** [comment]
vg should do a gen-skip rebase tbh

**Comment by NigglyWiggly** [comment]
>If this is something that /vg/ is doing then we need to get on board as well. It'll be better for both of us in the long run.

Except that a bunch of people on /vg/ don't want this either

**Comment by Iamgoofball** [comment]
vg has told me that nigglywiggly is the vocal minority at vg and we can safely ignore him

**Comment by RemieRichards** [comment]
we all have innate knowledge that goofball is goofball and not only can we ignore him we are encouraged to.

**Comment by Iamgoofball** [comment]
mhm

**Comment by NigglyWiggly** [comment]
What the hell is a vg?

Also if you actually think i'm some vocal minority, remember all of those people that told you to fuck off in our thread? None of them were me. I'm banned until tomorrow.

**Comment by MMMiracles** [comment]
I want less-shitty stretch-to-fit because I'm too poor to afford a slightly larger monitor as 1x is too small and 2x is slightly too big. Merge now fix sprites later I want to see stretch-to-fit settings that doesn't outright remove pixels.

**Comment by Iamgoofball** [comment]
Use 1.5x

**Comment by 9600bauds** [comment]
Someone needs to profile icon procs under 64x64
Cameras and blend() might be a landmine here

**Comment by PJB3005** [comment]
> He didn't make it use a multiplier.

**Comment by Iamgoofball** [comment]
>got shot down

**Comment by Giacom** [comment]
Had there been any BYOND updates which would allow masking? If you could figure out a way to mask blood splatter on items, it would really reduce the extra resources people would have to download.

**Comment by HankMoodyExperience** [comment]
if you guys really must have native 64x64 (presumably for poorfags whose upscale is blurry because shit computer) then just maintain the 32 aesthetic with minor coloration and beautification with 64x64. this should probably have a forum post instead of MUH CODEBASE IS ABSOLUTE shitfest on github.

**Comment by Iamgoofball** [comment]
MUH CODEBASE IS ABSOLUTE 

@Giacom i'm not certain, bug @MrPerson on irc he'd probably know

**Comment by Miauw62** [comment]
64x64 sprites literally dont fit on my (1080p) screen with the task bar at the bottom, they're slightly too big.

**Comment by clusterfack** [comment]
You could always modify your skin slightly to get a little more space out of it, we're thinking about that.

**Comment by optimumtact** [comment]
At the very least this will need a test merge for a week so people can see how it looks on their screen.

**Comment by optimumtact** [comment]
I've gone through and pruned a ridiculous amount of useless comments in this PR.

Please do the following
1) Express criticism in a calm evidence based matter
2) Respond to comments with emoticons rather than single sentence replies
3) make a feedback thread for things that need indepth discussion.

Thank you for your consideration.

**Comment by DrCelt** [comment]
@optimumtact is a censor enforced on TG?

**Comment by optimumtact** [comment]
only when it annoys me.

**Comment by Niknakflak** [comment]
When this was test merged, it lagged a lot for me. An unacceptable, unplayable level of lag.

**Comment by Iamgoofball** [comment]
Prove it was 64x64, post your specs and beyond version

**Comment by Bawhoppen** [comment]
goof stop being dumb, just admit that it is quite laggy and isn't just a placebo

**Comment by MrStonedOne** [comment]
I need to see a video of this lag, so i can understand it, not a screen capture recorded lag, but like a phone pointed at the screen.

During the test merge, I saw no lag, even on my pos laptop.

**Comment by Bawhoppen** [comment]
its just standard FPS lag with stuff not loading fast enough, might only happen to some people under specific circumstances

**Comment by MrStonedOne** [comment]
I really have to see it in action. next test merge (some time during low pop where i can see without as much spam) we shall see.

**Comment by WJohn** [comment]
I didn't feel any lag during the brief time this was test merged.

**Comment by 9600bauds** [comment]
Did anyone profile icon procs during that test merge?

**Comment by MrStonedOne** [comment]
no, but they were only a touch more costly, round start lag is from generating security record mugshots, and that was only a touch worse than normal.

**Comment by clusterfack** [comment]
It's weird you'd have lag, you guys don't even have parallax plane master slowing your shit down and my 6 year old laptop can run ours without any slowdown when zoomed out.

**Comment by optimumtact** [comment]
It's possible it was network lag, basil was up and down all day yesterday and the extra bandwidth load may have also caused sybil to be affected.

**Comment by PKPenguin321** [comment]
i had absolutely no lag on sybil during the 64x64 test merge

**Comment by Bawhoppen** [comment]
its the kind of weird FPS lag I already rarely get but then sometimes everything is perfect its always been weird

**Comment by Iamgoofball** [comment]
i like how you still haven't complied with MSO's request

**Comment by Bawhoppen** [comment]
I am going to try when the time comes????? Holy fuck goof

**Comment by Iamgoofball** [comment]
>icon conflicts again

here we gooooo

**Comment by Niknakflak** [comment]
>haven't done what mso wanted
>that requires this being test merged again

Goof please, your stupidness can only go so far

**Comment by PKPenguin321** [comment]
realistically this will probably need an icon freeze

**Comment by Jalleo** [comment]
To be honest if we share spriters between the codebases to get the worst sprites fixed it may be okay. It really depends on if we want to risk the burnout of our great and wonder spriters.

**Comment by clusterfack** [comment]
Relevant to 64x64 for coders who still use dream maker

http://pastebin.com/pLhg3rPk

**Comment by PJB3005** [comment]
So basically if you're still using DM then you're screwed?

**Comment by clusterfack** [comment]
As of now, somewhat

**Comment by Jalleo** [comment]
I suggest we hold on this per issue stated in that pastebin. Deferall of object tree generation is needed. Seriously random 20 min compile times?

**Comment by WJohn** [comment]
Sooo exactly the same as I'm experiencing right now?

I get that my computer's a toaster but whatever.

Does this mean I'll have 2 hour compile times?

**Comment by PJB3005** [comment]
I made a quick web program to upscale DMI files.

If you DON'T enter any states the entire DMI's size will be doubled, if you DO enter states the specific states will have their bottom left corner upscaled to 64x. So if you are working on a 64x64 DMI but just want to sprite 32x32, you make the sprite in the BOTTOM LEFT of the state, run it through my website and enter the states in question and then use the DMI it spits out.

http://84.195.252.227/dmi

**Comment by PJB3005** [comment]
DM can't handle it.

**Comment by Iamgoofball** [comment]
We can't be the only project doing 64x64 and having this issue.

**Comment by PJB3005** [comment]
Lummox said that BYOND is retarded about the way BYOND stores higher than 32x32 icons so it's not impossible that 64x64 is hitting some form of limit in DM.

**Comment by PJB3005** [comment]
http://www.byond.com/forum/?post=2127204&first_unread=1

**Comment by Iamgoofball** [comment]
i've worked with 64x64 on nthe mapper before

i'll see how it looks on our copy

**Comment by Iamgoofball** [comment]
FUCK wrong button

**Comment by Thunder12345** [comment]
Totally not shilling the fact this is still around or aaaaanything

**Comment by Cheridan** [comment]
Veegee users are complaining of lag and there's the whole "totally breaks the map editor" issue so this isn't going anywhere until the issues with it are ironed out.

**Comment by Iamgoofball** [comment]
veegee users are mostly placebo effect, they tend to blow shit out of proportion when they dont like shit

the map editor thing is a valid issue but let's talk to lummox about it

**Comment by DrCelt** [comment]
There was no perceptible lag on /vg/ on release, nor have I heard of anyone on the thread or github, or in game complain as such.

**Comment by Bawhoppen** [comment]
there is very definite and obvious lag for some people that is crippling to play with, but there isn't for some people aswell, is that so hard to understand? it's not a fucking placebo like goof seems to think

**Comment by clusterfack** [comment]
I don't know about your version but no one has put their name to such a complaint for us

**Comment by DrCelt** [comment]
@Bawhoppen I was never been alerted of this during /vg/'s usage of 64x64.

**Comment by Bawhoppen** [comment]
on tg me and several other people have gotten bad lag

**Comment by DrCelt** [comment]
@Bawhoppen Try connecting to /vg/; I don't think we've reverted 64x64 yet.

**Comment by Iamgoofball** [comment]
@Bawhoppen you also still havent described the type of lag or provided evidence

**Comment by Bawhoppen** [comment]
oh my god goof

**Comment by Iamgoofball** [comment]
what are you bitching about now

fork my branch and test it locally and get @MrStonedOne actual data

**Comment by DrCelt** [comment]
@Bawhoppen Try connecting to /vg/; we don't have goofball here yet

**Comment by DrCelt** [comment]
@Iamgoofball yeah that's true he'll probably confuse the optimised ticklag we have for 64x64 being less laggy.

**Comment by TheFriggenSawbones** [comment]
Yet? As codebase admin I don't think I'll let him wrap his fingers around our livelihoods once again.

**Comment by Iamgoofball** [comment]
literally who

**Comment by TheFriggenSawbones** [comment]
Headmin of /vg/

**Comment by DrCelt** [comment]
fuck off sawbones

**Comment by Iamgoofball** [comment]
headmin this:
8===========D
@DrCelt exactly, he's gonna get different results compared to us

**Comment by DrCelt** [comment]
he's an attention seeking trialmin
@Iamgoofball maybe your codebase isn't optimised enough for 64x64

**Comment by Bawhoppen** [comment]
okay now thats a joke

**Comment by Iamgoofball** [comment]
@DrCelt 
we put boobs on it, maybe we didnt optimize it enough

i'll go rewatch eric's tutorial

**Comment by MrStonedOne** [comment]
@Bawhoppen I need a camera phone recorded video of the lag, so i can see exactly how it looks, how it skips, how it catches up, etc.

I'm 100% serious on this, "It lags" tells me nothing. there are 50 million ways for lag to manifest, each with their own solution.

**Comment by optimumtact** [comment]
Byond simply isn't ready for this quite yet, so there is zero reason to leave this clogging up the tracker.

**Comment by 77seven77seven** [comment]
is BYOND ready for this now

**Comment by optimumtact** [comment]
maybe, it's unclear

**Pull request closed without merging**
