### PR TITLE
[WEB EDIT] [UNTESTED] [ONE LINE CHANGE] Fixes black pills

### PR DESCRIPTION
**Pull request by ATH1909**
## About The Pull Request

Increases the amount of shadowperson mutation toxin found in each of the black pills that legion corpses sometimes have in their pockets from 1u to 5u.

## Why It's Good For The Game

These pills were added before the mutation toxin nerf(s), and the shadowperson mutation toxin from one black pill currently won't actually stay inside of you for enough chem ticks to turn you into a shadowperson if you eat it. In other words, the pill does basically nothing.

This PR increases the amount of shadowperson mutation toxin found in each of those pills to 5u, which definitely should be enough mutation toxin to turn one person into a shadowperson, but NOT two people (unless you use bees or something).

## Changelog
:cl: ATHATH
fix: Increases the amount of shadowperson mutation toxin found in each of the black pills that legion corpses sometimes have in their pockets from 1u to 5u. They should actually turn you into a shadowperson if you eat them now.
/:cl:

### CODE REVIEW

**Comment by itseasytosee** [comment]
Shadow bee time

**Comment by necromanceranne** [comment]
I forgot to make an issue report about this. Thanks ATH!

**Comment by wesoda25** [comment]
please stop making the rest of the contributors look bad

**Review by Cyberboss — APPROVED** [review]

**Comment by optimumtact** [comment]
untested webedit

**Comment by ATH1909** [comment]
I've finally gotten around to testing this PR, and here's proof that it works:
proof1
proof2

**Comment by ATH1909** [comment]
Thanks!

**Pull request merged**
