### PR TITLE
Adds WJohn's chair sprites

### PR DESCRIPTION
**Pull request by fiercestwarrior**
## About The Pull Request

Made by WJohn

Removes greyscale chairs as I have no clue what they're used for (unless they're actually used for something in which case I'll make greyscale versions)

## Why It's Good For The Game

'Improves' the current chair sprites since I think the current ones are conflicting with the current style of the game.

## Changelog
:cl: WJohn, FrozenGuy5
imageadd: New chair sprites
/:cl:

### CODE REVIEW

**Comment by Twaticus** [comment]
greyscale chairs are used for datum materials so there does need to be a greyscale version added sorry lad

**Comment by Qustinnus** [comment]
remove the old sprites please. if we want them back we can check the history.

**Comment by partyaddict** [comment]
Done.

**Comment by Dorsisdwarf** [comment]
!()[http://puu.sh/FBicP/3bc785f6cf.png]

**Comment by nicbn** [comment]
Is there a reason wj didn't pr himself these?

**Comment by partyaddict** [comment]
> 
> 
> Is there a reason wj didn't pr himself these?

Because he hated them. I'll revisit 'better' chairs in the future.

**Comment by nicbn** [comment]
I think we could still have these, at least as a placeholder, that is if WJ gives permission to use that, of course.
They are still way better than what we currently have.

**Pull request closed without merging**
