### PR TITLE
Add candle design to biogenerator

### PR DESCRIPTION
**Pull request by timothymtorres**
## About The Pull Request
For a little biomass, candles can now be printed at any biogenerator.

## Why It's Good For The Game
Producing more candles was inaccessible.  Now there is an easy solution!

## Changelog
:cl:
add: Add candle design to biogenerator
/:cl:

### CODE REVIEW

**Comment by Capsandi** [comment]
https://tgstation13.org/wiki/Guide_to_chemistry
ctrl +f "candle"

**Comment by AtomTheProphet** [comment]
> https://tgstation13.org/wiki/Guide_to_chemistry ctrl +f "candle"

I don't really blame them for thinking there wasn't a way to produce them. After all, how many times have you seen a candle actually get made through chemical reactions?

**Comment by timothymtorres** [comment]
I said it was inaccessible, not impossible.  There is currently #78593 that lets people buy candles as a crate, but having other methods to obtain a aesthetic item is pretty harmless.

**Comment by carlarctg** [comment]
Maybe... just maybe, not throwing every possible item into a chemical reaction is a good thing?

**Comment by Wallemations** [comment]
Boutta add a recipe that lets you dye candles to make crayons I think

**Review by ninjanomnom — APPROVED** [review]

**Pull request merged**
