### PR TITLE
Adds the Human Language

### PR DESCRIPTION
**Pull request by Iamgoofball**
The language is added as part of the job equipping code, changing your
species to Human via xenobio will not magically teach you the language.
Normal human tongues are capable of speaking Human.
pAIs with translator and Librarians are capable of speaking and
understanding Human

This is to increase diversity and roleplay in SS13.

### CODE REVIEW

**Comment by Really-Good-Soda-Flavor** [comment]
If removing the lizard language does not go through, then I support a unique language for each species. No special treatment.

**Comment by GunHog** [comment]
https://github.com/tgstation/tgstation/pull/26856 Add Latin for heads and gutter-speech for the greyscum! (Kor suggested this)

**Comment by Really-Good-Soda-Flavor** [comment]
@Iamgoofball Make it Spanish

**Comment by Iamgoofball** [comment]
@Really-Good-Soda-Flavor no our players are weebs

**Comment by Armhulen** [comment]
this is okay, but how does WGW sound in japanifornia

**Comment by KorPhaeron** [comment]
This will actually lead to lizard metagangs if they can be excluded from the majority

**Comment by InsaneHyena** [comment]
All the more reason to lynch them.

**Comment by KorPhaeron** [comment]
Says the lizard player

**Comment by octareenroon91** [comment]
This is hideous.

I'm not sure you should stop though.

**Comment by GunHog** [comment]
Please do not forget to add this to the silicon language holder, found here:
https://github.com/tgstation/tgstation/blob/master/code/modules/language/language_holder.dm#L131

**Comment by dannno** [comment]
at least be a little more creative than """"human language""""

**Comment by octareenroon91** [comment]
>>at least be a little more creative than """"human language""""

>it's a clone of the lizard language PR text

**Comment by dannno** [comment]
i dont care

**Comment by InsaneHyena** [comment]
>Says the lizard player

What did he mean by this?

**Comment by kevinz000** [comment]
this sounds like a shit change but :+1: because you can't argue with the syllable choice.

**Comment by Bawhoppen** [comment]
what does this mean actually?

**Comment by optimumtact** [comment]
Humanity already has their language, it's galcommon and it's the rightful language of the galaxy due to our superior intellect and technology.

Cave races btfo.

**Pull request closed without merging**
