### PR TITLE
[WIP] Closet sprites the return: goon 3:4 closets

### PR DESCRIPTION
**Pull request by nicbn**
[Changelogs]:
[]:
:cl:
imageadd: New closet sprites
/:cl:

[why]: For 3:4 haters yell all over this.

Some of the closets are from goon, most were modified.

closets
print1
print2
print3
print4
print5

## WIP means it's not ready

### CODE REVIEW

**Comment by ChangelingRain** [comment]
The open door sprite is too small.

**Comment by PraiseRatvar** [comment]
The actual closet is a bit too tall as well.

**Comment by nicbn** [comment]
It was ported from goon, and there is no more room for a bigger open door in the tile.

The closet frontal face is actually one pixel smaller.

**Comment by ChangelingRain** [comment]
There's room if you pixel shift the door.

**Comment by nicbn** [comment]
Yeah but he position of the contents, and of closet itself, wouldn't look nice.

**Comment by FantasticFwoosh** [comment]
the coffin and others are lower quality as a result of a gimmick no thank you.

**Comment by lzimann** [comment]
The closests don't like nice so who cares

**Comment by pubby** [comment]
I thought Goonstation's non-commercial license was incompatible with AGPL.

**Comment by ChangelingRain** [comment]
>Yeah but the position of the contents, and of closet itself, wouldn't look nice.

why not? you'd be moving the door, not the closet.

**Comment by nicbn** [comment]
Well if I moved the door it wouldn't in the closet.

The goon license is CC-BY-NC-SA, I'm not any lawyer but I think that if we just credit them somewhere we'll be fine.

**Comment by nicbn** [comment]
>the coffin and others are lower quality as a result of a gimmick no thank you.

I can revert the coffin, and I have no idea what you mean by others.

**Comment by nicbn** [comment]
If anyone wants to give a try and improve the sprites, go on.

**Comment by ChangelingRain** [comment]
You make the open door larger, in the file, and then you pixel shift the open door so it sticks out to the left instead of being super squashed.

**Comment by nicbn** [comment]
Will do it later, too tired for now

**Comment by Incoming5643** [comment]
The laws of perspective haven't changed, it's still not a good idea. It robs information from the icon for a perspective we'll never truly embrace. I'm on a long break and this is like the one hot opinion I still feel passionate about.

**Comment by nicbn** [comment]
Which information?

**Comment by Fox-McCloud** [comment]
I wonder how many people are downvoting this because it came from Goon as opposed to genuinely not liking the perspective or sprites.

If it's the former--I'd like to point out that a lot of the recent sprite updates (like the toolboxes and some vending machines) come *directly* from Goon and the sprite style was the *inspiration* for a number of other vending machines.

**Comment by nicbn** [comment]
Yeah I have no idea if it will be accepted after I improve it. I don't want to waste time and effort for it to be refused for some reason that the downvoters did not specify.

**Comment by Incoming5643** [comment]
@nicbn The side of the sprite, 3/4ths only give you the top and front of the box, the diagonal depth is lost.

I'm of a mind that sprites in this game should be more abstract representations of what they are rather than be a literal projection of what that object would look like from a certain (arbitrary) perspective.

In short I say draw it to make it as obvious as possible to what it is. Usually 3/4ths view is not the best for this. Compare old and new toolboxes for a good example where "making something look like itself" was sidelined for a more ambiguous perspective.

Just my opinion though. Very subjective topic.

**Comment by pubby** [comment]
I do dislike the perspective a lot, but I also dislike the colors, the jaggies on the open door, the random pixels in the upper corners, the odd light edges on the top, the door graphics not matching the door vents in style, the door graphics having bad shading, and the bump-up tangents formed because the sprites are exactly 32 pixels tall.

image

**Comment by nicbn** [comment]
Well the whole idea for the sprites is behind the perspective. I kinda like it, it's not great but it's better than what we have now. For comparison, the generic, biohazard - except L4 -, fire and O2 are goon-original, withouth modification.
I think they fit better in the game, but if you don't think so...

**Comment by nicbn** [comment]
Also I'd like to mention how much a consistent artwork helps with beauty and immersion: look at colonial marines ship, and even goon. They look neat and solid.

**Comment by WJohn** [comment]
These look great. Always liked goon lockers. 👍 

As others have said, the open door sprite is a touch too small. You could stretch it out further horizontally, or perhaps vertically if you pixel shift it (if that's even possible to do with overlays and ONLY the overlays).

**Comment by Lexorion** [comment]
I think you have to move the sprites to the goon folder (which sort of makes [this](https://github.com/tgstation/tgstation/projects/6) a bit harder)  but I might be wrong! Most of them look good but I really don't like the coffin.

**Comment by DoctoreMad** [comment]
@Fox-McCloud 
I'm 99% sure that we've had 3:4 sprite changes that came form non-goon locations and they were just as disliked.

**Comment by WJohn** [comment]
Then I wonder if people actually dislike 3/4th for a good reason, or if they actually dislike the sprites because they're changing old iconic ones.

Incoming *has* raised the point of 3/4th technically having less detail than oblique from the side sprite, but the thing is that oblique provides so little detail on the sides anyway that you don't lose anything at all. As for a loss of depth or thickness, it's really not hard to visualize the top half as how thick something is.

**Comment by lzimann** [comment]
This is probably going to be reopened and merged regardless of what anyone's thinks, but fuck it, stop with these goddamn awful 3:4 sprites, and specially, sprites from goon needs to be on goon folder, and that alone is a big no.

**Comment by nicbn** [comment]
Could we have a vote?
Also most of the sprites are not from goon, but modified. Do they still need to go to goon folder?

**Comment by nicbn** [comment]
Also closing WIP PRs like this is lame.

**Comment by WJohn** [comment]
Come on, lzimann, I like these sprites, they *do* still need a bit of work, yes, and I won't merged them until they are

Things to be worked on:
1. Improve the doors to be longer when opened, they seem too short.
2. See if you can remove the sharp corners of the open doors.

That's mainly it, actually, these look pretty good otherwise.

**Comment by MoreRobustThanYou** [comment]
Make the door opening animated

**Comment by nicbn** [comment]
Also it will take a long time to finish, as I'm not rushing to finish this ASAP. Please calm down and don't hate the sprites until they are done.

**Comment by nicbn** [comment]
> Improve the doors to be longer when opened, they seem too short.

Longer or wider?

**Comment by WJohn** [comment]
Wider. Sorry, bad terminology. I haven't slept well.

If you plan on remaking it from scratch, go right ahead. Might be best to make it in a new PR so it can be more properly reviewed without the bad taste from what was previously there.

**Comment by nicbn** [comment]
Yeah. But keep in mind that the style will be basically the same. Bye PR.






> I haven't slept well.

NONE OF US HAD.

**Pull request closed without merging**
