### PR TITLE
Fixes the zombie powder recipe

### LINKED ISSUE #8361: Cannot Make Zombie Powder
The problem here is pretty simple.
Zombie Powder requires stoxin, better known as sleep toxin, to be made.
Sleep toxin got cut out of the code besides its recipe (Which is getting fixed)... and it being used for Zombie Powder.
So, should be easy enough to do a quick change to making it require morphine instead of Sleep Toxin.
For reference, Zombie Powder currently requires 5 Stoxin, 5 Carpotoxin, and 5 copper to make 2u or so of Zombie Powder.

### PR DESCRIPTION
**Pull request by Iamgoofball**
fucking sleep toxin

it uses morphine now
Fixes #8361

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
*coughcapulettiumcough*

**Comment by Iamgoofball** [comment]
*coughcapulettiumbrokewhenItesteditmaybeinthefuturecough*

**Comment by Fox-McCloud** [comment]
*coughdamnwhatashamecough*

**Comment by RemieRichards** [comment]
*coughcutthebullshitcough*

**Comment by Iamgoofball** [comment]
*coughbesidesIcouldntgetcap+workingwithoutsnowflakeuptheasszombiepowderdoesthejobfinecough*

**Comment by Cheridan** [comment]
you guys are nerds

**Pull request merged**
