### PR TITLE
Adds the Great Banhammer

### PR DESCRIPTION
**Pull request by Niknakflak**
The regular ban hammers big brother.
This is not a toy.

Bans on suicide and hit.

Image:
image

### CODE REVIEW

**Comment by ma44** [comment]
http://i.imgur.com/sKgCPKQ.png

**Comment by BeeSting12** [comment]
How many TCs for this?

**Comment by Niknakflak** [comment]
Admin only babe

**Comment by Cyberboss** [comment]
Should also ban the user

**Comment by Cyberboss** [comment]
And gib both

**Comment by DoctoreMad** [comment]
A item that actually bans people on use?
Someone is going to mistakenly spawn this thinking its the banhammer toy that doesn't ban people, aren't they?

**Comment by ninjanomnom** [comment]
make it not directly spawnable without messing with proc calls

why dont we have admin easter eggs

**Comment by BeeSting12** [comment]
@Niknakflak What if the admin spawns it to use it, gets robusted, and gets banned themselves

**Comment by AuroranAI** [comment]
then they have proven that they aren't good enough to use the weapon, and should be banned

**Comment by KorPhaeron** [comment]
@Jordie0608 rejected this last time

**Comment by dannno** [comment]
this is such an irrefutably stupid, awful, and just downright bad idea
but it's so fucking funny in theory that it just might work...

**Comment by Armhulen** [comment]
i say

**Comment by ShizCalev** [comment]
Why isn't it a subtype of /obj/item/weapon/banhammer?

**Comment by Armhulen** [comment]
yes

**Comment by Shadowlight213** [comment]
Inb4 someone runs sandbox and a player spawns this

**Comment by Tokiko1** [comment]
Go the full distance, add a permaban hammer item too!

**Comment by Jordie0608** [comment]
\>Not a child of banhammer
\>Uses legacy ban system for server bans
\>`hitting [user.p_them()]selfself with`
\>only bans for a day
\>name after desc in item def
\>different messages, capitalization and `bannedby` for `attack` and `suicide_act` `AddBan` call
\>doesn't instagib anyone 
\>`<font>` instead of `<span class>`

-1440/10 Go directly to Jail. Do not pass Go.

**Comment by Shadowlight213** [comment]
>\>only bans for a day

Kek

**Pull request closed without merging**
