### PR TITLE
14:40	oranges	I'm sick of hulk

### PR DESCRIPTION
**Pull request by Iamgoofball**
14:40   oranges delete hulk

ordered by a maintainer
# remember kids if you vote for me in the election 1st place of the IRV AND I WIN you can use a goofcode token to get hulk back _**i dont want to remove it**_

### CODE REVIEW

**Comment by TheDreamweaver** [comment]
GOof loves me

**Comment by MMMiracles** [comment]
could you at least full-ass it and remove the injector items and fix the appropriate maps with it instead of using the PR as a campaign attempt?

**Comment by optimumtact** [comment]
goodbye hulk

**Comment by ChangelingRain** [comment]
remove hulk REMOVE HULK I do not want to cater to this horrid thing no more.

**Comment by Cuboos** [comment]
No

**Comment by optimumtact** [comment]
None can stop the fruit tyranny

**Comment by Cuboos** [comment]
DON'T

**Comment by Kraseo** [comment]
yes please

**Comment by Cuboos** [comment]
**DO NOT**

**Comment by ExcessiveUseOfCobblestone** [comment]
bring back jellybones

**Comment by Durkel** [comment]
Ravioli ravioli give a replacement poweroli.

**Comment by Iamgoofball** [comment]
i could replace it with the power that makes you immune to electricity

**Comment by PKPenguin321** [comment]
Autistic campaign bait

**Comment by Cuboos** [comment]
Goofball has lost my vote.

**Comment by Iamgoofball** [comment]
@Cuboos this pr doesnt work anyways and was more made to quick-gauge player opinion on it for origins

**Comment by HankMoodyExperience** [comment]
meme

**Comment by ChangelingRain** [comment]
"doesn't work"

**Pull request closed without merging**
