### PR TITLE
Updates the Station-bounced Radio sprite

### PR DESCRIPTION
**Pull request by Wallemations**
## About The Pull Request
Updates the radio sprite, courtesy of @Imaginos16
Before
2355436346234-export

After
1234234234234234234124-export

## Why It's Good For The Game
The current sprites look really large and exceedingly clunky, this makes 'em a little smaller and more well-detailed

## Changelog

:cl: Imaginos
imageadd: Updates the station-bounced radio sprite
/:cl:

### CODE REVIEW

**Comment by SeigaSeiga** [comment]
I'm not sure about reducing the saturation of the green. That saturated green is pretty important in giving the station bounced radio immediate readability, compared to the dark green of the smaller Remote Signaler. This change pushes the station bounced radio closer to the same general dimensions and colors as the Signaler. Hopefully it's still easy to distinguish between them at a glance.

**Comment by Wallemations** [comment]
> I'm not sure about reducing the saturation of the green. That saturated green is pretty important in giving the station bounced radio immediate readability, compared to the dark green of the smaller Remote Signaler. This change pushes the station bounced radio closer to the same general dimensions and colors as the Signaler. Hopefully it's still easy to distinguish between them at a glance.

image

The signaller's olive is nowhere near the green of the radio

**Comment by SeigaSeiga** [comment]
> > I'm not sure about reducing the saturation of the green. That saturated green is pretty important in giving the station bounced radio immediate readability, compared to the dark green of the smaller Remote Signaler. This change pushes the station bounced radio closer to the same general dimensions and colors as the Signaler. Hopefully it's still easy to distinguish between them at a glance.
> 
> image
> 
> The signaller's olive is nowhere near the green of the radio

Looking at 'em both now, yeah, that's fine. Consider my concern proven wrong!

**Comment by Miczu555PL** [comment]
imageadd: Updates the station-bounced radio sprite... Again

**Comment by SuperSayu** [comment]
Is there any way this sprite could get overlays that show when the mic is hot or the speaker is on?  A version where the display isn't animated would work for the speaker being off, probably.

**Pull request merged**
