### PR TITLE
You can no longer shoot and melee with guns at the same time

### PR DESCRIPTION
**Pull request by ghost**
:cl: Qustinnus
fix: you can no longer shoot and melee with guns at the same time
/:cl:

not epic

### CODE REVIEW

**Comment by Qustinnus** [comment]
i will look into that later today but you make a good point

**Comment by Pugie** [comment]
NOOOOOOOOOOOOOOOOOOO

**Comment by necromanceranne** [comment]
Solve the bug before the consistency problem, of course. Just worth bringing up.

**Comment by ShibaInuLord** [comment]
we should make a gunblade

**Comment by interestingusernam3** [comment]
>we should make a gunblade

Yes but as shitty as IRL so weebs try to use it and suffer.

**Review by Mothblocks — CHANGES_REQUESTED** [review]
let me know what you find wrt bayonets, going to draft this until you find a solution

**Pull request merged**
