### PR TITLE
Makes cash lemons trash the seed for a cash lemon, extracting the seed from a cash lemon will instead make money = to potency of the plant

### PR DESCRIPTION
**Pull request by ma44**
Also the big seed extractor has been modified so you can't make more than the amount of money that's in it

inb4 PR closed cause infinite cargo points

### CODE REVIEW

**Comment by ma44** [comment]
This is mostly a work in progress, so you guys can tag it

**Comment by ChangelingRain** [comment]
Excuse me, we currently have a lemon ban enacted.

**Comment by ma44** [comment]
Really

**Comment by Jalleo** [comment]
Cheridan> I never want to hear about fucking lemons again
You burnt out our head coder

**Comment by bobdobbington** [comment]
Topic for #coderbus is: Welcome to /tg/station, one of the largest open-source development projects in the universe. | Lemon ban has been enacted, please direct all lemon-related conversation to www.lemonparty.org

**Comment by ma44** [comment]
what have i done

**Pull request closed without merging**
