### PR TITLE
Adds a treasure chest to the ocean/beach fishing spot.

### PR DESCRIPTION
**Pull request by Ghommie**
## About The Pull Request
This PR adds a treasure chest that can be fished from the ocean if you're lucky enough (or have enough explosives or lobstrosities to do it for you). The treasure chest is basically a mystery box (like the ones from the deathmatch) with a couple catches; the treasure chest can be opened up to 18 times in total before breaking down, however, it can only be opened up to 3 times per spaceman, encouraging the player to share it with others.

Here the possible loot by the by:
- A toolbox containing a master fishing rod, all the hooks and reels, fish feed, an experi-scanner, an aquarium kit and a can of super baits
- A box containing a lazarus injector, a cup and a bottle of strange reagent which you can use to revive fish now
- A circuit board for a pre-emagged fishing portal generator
- A master fishing rod
- A can of super fishing baits
- A fish case containing Tiziran fish
- A fish case containing Syndicate fish
- An old, yet fairly strong cutlass
- An old laser gun which fires only 5 shots before running out
- A crank laser musket
- A smoothbore disabler
- A surplus bolt action rifle
- A ration pack
- A can of squid ink
- A bottle of aged rum that forces you to switch to the piratespeak language
- A money bag with some doubloons inside
- A piratespeak manual
- Pirate armored coat
- Pirate armored hat
- A pre-loaded cannon
- Four trash cannon balls
- Four cannon balls

## Why It's Good For The Game
Mystery boxes are fun, from the little fanfare they play to the potential loot they can give, and I had an old treasure chest I had sprited for fun years ago around so I've come up with an entertaining idea. If you think the loot list is a bit too hot, I can cool it down a bit.
Also yeah, I wanted to make fish revivable with strange reagent, since you can already do it with lazarus injectors even though using a lazarus injector for this would be a severe waste of mining points.

## Changelog

:cl:
add: Added a treasure chest you can rarely fish from the ocean/beach, with loot being a mix of fishing and piratey stuff.
add: You can revive fish with strange reagent now.
/:cl:

### CODE REVIEW

**Comment by Ghommie** [comment]
Drafting cuz I've been suggested to map in some pirate skeleton with a note and fishing equipment beside to give this a little visibility.

**Comment by CCC23** [comment]
YAR HAR THEIR BE TREASURE

**Comment by Paxilmaniac** [comment]
THERE BE TREASURE

**Comment by Loafin34** [comment]
ss13 terraria reference

**Comment by deathrobotpunch** [comment]
YARR BEHOLD ME ANCIENT BOOTY

**Comment by CCC23** [comment]
I cant wait for someone to make the omega fish sm

**Pull request merged**
