### PR TITLE
( src ) ---> (src) and if ( ---> if(

### PR DESCRIPTION
**Pull request by ghost**
Why did I do this

Byond's replace tool is very powerful though

Mostly these two things just upset my autism a lot

### CODE REVIEW

**Comment by Razharas** [comment]
What is ( src )?

**Comment by RemieRichards** [comment]
@Razharas I think paprika is referring to new statements
eg ```new /obj/item/weapon/crowbar (src)```

**Comment by Deantwo** [comment]
I am with you on the part that it annoys me.
But are you sure you want to change 504 files just for that?

**Comment by Jordie0608** [comment]
Sounds like a nerf to spaces.

**Comment by paprka** [comment]
i do want to change 504 files, commit history be damned my name will be painted across this codebase like sacrificial blood

**Comment by Deantwo** [comment]
And you'll make merge conflicts with all PRs that are also trying to edit any of those 504 files.

**Comment by Lo6a4evskiy** [comment]
> if ( ---> if(

I actually prefer the space, it looks nicer imo

Anyway, we need consistency, so someone should decide how to write it from now on. Currently I do it the same way other code is written in the same file.

And you should also do it with for's and switch's and while's and other things.

**Comment by Miauw62** [comment]
if() is used in most code, so that should be the standard.
usually there are no spaces between parentheses and var names/keywords, but operators (+, -, *, /, %) are always surrounded by spaces.

**Comment by paprka** [comment]
Fixing conflicts here is extremely easy but it just takes a long time since changing branches and pushing takes forever. Please lemme know if you guys want this to happen @hornygranny @Miauw62 @Razharas @Cheridan @RemieRichards etc, and I'll fix the conflicts. It'd be nice to clean up this kind of stuff in the code, but it's a very very very minor issue and if the file history being shit all over by one large commit is a bad thing then I won't do it and you can close this. But consistency is nice and byond is powerful enough to make this happen extremely efficiently.

**Comment by JJRcop** [comment]
this is the wrong way to do it, we need to rebase then revise the first commit we have to include these changes

changing all of our commit hashes is obviously the more sensible option

**Comment by paprka** [comment]
I'll revisit this when I'm less bored

**Pull request closed without merging**
