### PR TITLE
Allows captains to set name of station

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
As preference option (default is Space Station 13)

### CODE REVIEW

**Comment by Buggy123** [comment]
This couldn't possibly go badly.

**Comment by GunHog** [comment]
I cannot wait to see what Mekhi names us.

**Comment by Dorsisdwarf** [comment]
Not another damn preference goddamn it damnit damn.

Give the captain a token or something or let the authenticator do it or _something_

**Comment by Zilenan91** [comment]
Inb4

ONE DAY WHILE ANDY WAS MASTURBATING Station

**Comment by AdamElTablawy** [comment]
COCKGOBBLER STATION 13

**Comment by Cebasiz** [comment]
allow to set default AI lawset when thanks

**Comment by KazeEspada** [comment]
Forgot the savefile...

**Comment by KorPhaeron** [comment]
@KazeEspada 

Thanks

**Comment by KazeEspada** [comment]
Forgot to save the name.

**Comment by KorPhaeron** [comment]
@KazeEspada 

Where do I do that?

**Comment by Incoming5643** [comment]
:-1: I like the RNG names, it gives a sense of uniqueness to every shift. If a captain stays a captain for a few rounds in a row (and that's pretty likely) the station will continue to have whatever the hell the captain has set as their preference.

Hell you even set a default station name, meaning no one could dean to use the RNG names even if they wanted to outside of there being no captain.

**Comment by KazeEspada** [comment]
same place, either higher or lower in the file.

**Comment by TrustyGun** [comment]
Yeah, you should leave the RNG names as a separate preference. I like them quite a bit

**Comment by KorPhaeron** [comment]
I will redo it as a comms console thing

**Comment by Incoming5643** [comment]
yeah that'd be fine

**Pull request closed without merging**
