### PR TITLE
🐟 Floor Aquariums

### PR DESCRIPTION
**Pull request by tralezab**
## About The Pull Request

Aquarium logic is now in its own component

Aquarium floors now exist! You make em by smacking a glass floor with an aquarium kit.

## Why It's Good For The Game

FLOOR. AQUARIUM.

## Changelog
:cl:
add: You can build aquariums into the floor by hitting a glass floor with an aquarium kit.
/:cl:

### CODE REVIEW

**Comment by Kylerace** [comment]
cant wait to make a toggleable supervillian floor sharktank combining this with a trapdoor

**Comment by maxymax13** [comment]
by glass floors do you mean like the metasci real glass floors or the shitty fake material tiles you craft ingame that shouldnt even exist

**Comment by tralezab** [comment]
real glass floors.

**Comment by maxymax13** [comment]
how do you even make real glass floors, anyways? do you just smack plating with glass or something?

**Comment by tralezab** [comment]
wait... glass floors are UNCRAFTABLE? wooow

**Comment by maxymax13** [comment]
> 
> 
> wait... glass floors are UNCRAFTABLE? wooow

why not hit two glass floors with one stone and make them craftable, if challenged on the scope say that you need them to be craftable if you want the floor aquariums to be craftable in any reasonable degree outside of the fiew places they spawn in. and maybe disable fake nae nae glass tiles that make no sense. talking about floors, i should probably make floor lights craftable outside of researching mini-rlds someday

how do floor aquariums look like, any screenshots?

**Comment by tralezab** [comment]
screenies soon!

**Comment by Fikou** [comment]
they are craftable

**Comment by tralezab** [comment]
This Comment is Locked to Pro Github Users Only!

**Comment by Fikou** [comment]
This Comment is Locked to Pro Github Users Only!

**Comment by interestingusernam3** [comment]
This Comment is Locked to Pro Github Users Only!

**Comment by OceanFish1** [comment]
Le fishe

**Comment by tralezab** [comment]
todo for myself tomorrow:
refactor fish from being in contents to being in nullspace + a list

**Comment by maxymax13** [comment]
> 
> 
> cant wait to make a toggleable supervillian floor sharktank combining this with a trapdoor

you've heard of hop drops you into icebox z level now get ready for hop dropping tider into a maze with swinging axes, buzzsaws and shark pits

**Comment by MrDoomBringer** [comment]
https://youtu.be/5EqUauvcbD8
hopline every round after this PR

**Comment by tralezab** [comment]
It's becoming more and more obvious

we need MORE turf components

**Comment by Zytolg** [comment]
You spoil me! It'll go perfectly with the drab carpeting and new stuff on some of the new content that's being worked on!

**Comment by tralezab** [comment]
will return when i have less on my plate

**Comment by Burgermancoding** [comment]
tralezab where is floor aquariums

**Comment by Twaticus** [comment]
tralezab where is floor aquariums

**Pull request closed without merging**
