### PR TITLE
Revert: [WIP] Floyd's wild sound adventure (Adds sound_loop datums to a bunch of machinery)

### LINKED ISSUE #32713: T-Com sound loop is imperfect
One of the sounds is overlapping.

https://vocaroo.com/i/s0AVCSbnxtSm

### PR DESCRIPTION
**Pull request by ShizCalev**
Reverts (#32336)
 (reverted from commit ea523084c2f64c62e85a7ee4b13bc8461313966e)
Closes #32713

PR was still a WIP when it was merged. Introduced runtimes, the machines are way too loud, the loops aren't perfect and pop, ect.

### CODE REVIEW

**Comment by ShizCalev** [comment]
Imperfect loop example;
https://vocaroo.com/i/s0AVCSbnxtSm

**Comment by ShizCalev** [comment]
Play a roll that has to stand next to multiple computers for an entire round and tell me you don't want to kill yourself after an hour

**Comment by Iamgoofball** [comment]
@ShizCalev sounds like an excuse to go on break to the bar or kitchen?

**Comment by Iamgoofball** [comment]
incentives to leave your workplace is good, especially for places like R&D

**Comment by Iamgoofball** [comment]
additionally the concept of committing murders near heavy machinery to mask the noise is a great gameplay concept and I love the idea of it

**Comment by Iamgoofball** [comment]
@Cuboos back me up here m8, sounds make good games

**Comment by PKPenguin321** [comment]
Have certain sound loops respect the ambiance pref maybe?

**Comment by ShizCalev** [comment]
New machinery ambient pref sounds look a good idea.

**Comment by Iamgoofball** [comment]
making it a pref removes all gameplay impact, fuck off with that

**Comment by PKPenguin321** [comment]
Only certain sounds would fall under it so gameplay oriented sounds would be unaffected

**Comment by Iamgoofball** [comment]
@PKPenguin321 Loud machinery masking other sounds is definitely gameplay oriented, are you kidding me?

**Comment by PKPenguin321** [comment]
Ehh

**Comment by epochayur** [comment]
this is the definition of "making a mountain out of a molehill"

**Comment by optimumtact** [comment]
just reduce the volume shiz, this is lazy

**Comment by ShizCalev** [comment]
@optimumtact I already ran my game at 20% volume before these were added, a player shouldn't have to mute the entire game just because the computers on the bridge are deafening or because their job is to literally stand next to multiple (4+) computers for most of the round (HOP, Warden, ect)

**Comment by Cuboos** [comment]
Are the sounds still in the game? i wanna hear them to see what everyone is freaking out about.

**Comment by optimumtact** [comment]
I mean on the sounds shiz

**Comment by Qustinnus** [comment]
why was a WIP PR merged again

**Comment by ShizCalev** [comment]
someone was impatient.

**Comment by Qustinnus** [comment]
so basically my PR got sabotaged :^)?

**Comment by Qustinnus** [comment]
also regarding the computer thing, I can make computers have an on/off button similar to modular computers so you can turn off the computer.

**Comment by Qustinnus** [comment]
also im fine with this being reverted as long as I can finish my original WIP PR after, (and this isn't a permanent revert)

**Comment by ShizCalev** [comment]
Yeah, nothing barring you from reopening it.

**Comment by PopNotes** [comment]
"so instead of fixing it, you make a knee jerk revert?"

>>>>>>>>>>>>>>goofball

**Comment by Iamgoofball** [comment]
Why was this speedmerged by oranges

**Comment by Qustinnus** [comment]
no clue i think it was to meme on me while I wasn't home

**Comment by Qustinnus** [comment]
oh sorry i misread, I thought you ment the original PR, it was merged on my request so I can go fix it in peace first

**Comment by Cuboos** [comment]
Mind if i give the computer sound a shot, see if i can make something not so annoying and won't require playing around with the volume?

**Comment by Qustinnus** [comment]
feel free! but please dont remove the startup/end sounds, i'm quite fond of those

**Comment by Qustinnus** [comment]
send me the sounds when you have them and I'll implement them in my PR @Cuboos

**Pull request merged**
