### PR TITLE
Updates Eye of God item sprite.

### PR DESCRIPTION
**Pull request by TechnoAlchemisto**
New
old
new
Old
new
The darker coloured sclera was kind of icky, IMO>

### CODE REVIEW

**Review by ChangelingRain — CHANGES_REQUESTED** [review]
Needs to not replace the current sprite, also needs to apply to the double god eye.

**Comment by optimumtact** [comment]
Why would you not replace the existing sprite @ChangelingRain ?

**Comment by ChangelingRain** [comment]
This is replacing the sprite with an older, edited version instead of editing the current sprite.

**Comment by TechnoAlchemisto** [comment]
I'll do the double, but what do you mean by not replacing the current Sprite?

**Comment by TechnoAlchemisto** [comment]
This is replacing it with a newer edited version, which I edited outside dream maker

**Comment by ChangelingRain** [comment]
These are still heavily reminiscent of an older version of these sprites.
http://puu.sh/rbZYy/87e680a071.dmi Here is the current sprites, but with the lighter colors.

**Comment by pudl** [comment]
:thought_balloon: Sometimes change isnt a good thing

**Comment by TechnoAlchemisto** [comment]
I do understand that it's similiar, but the sprites are straight lightening of the old sprites, and some iris modifications. I mean, I did make the original sprites for the eye, so this is just an improvement of something I see as not-as-good-as-it-could-be.

I'm not quite sure what the issue is with replacing, since it accomplishes essentially the same thing as editing them in dreammaker. Unless i've misunderstood you.

**Comment by pudl** [comment]
I was responding to joan

**Comment by pudl** [comment]
Why cant i delete comments on mobile

**Comment by Niknakflak** [comment]
Looks no different to me.

**Comment by pudl** [comment]
@niknakflak look at the sclera

**Comment by ChangelingRain** [comment]
The iris's color loop is significantly different. Just use that linked .dmi it's the fixed version.

**Comment by TechnoAlchemisto** [comment]
Oh, I also fixed the gross off coloured pixels in the iris and replaced them with a more solid "ring" 

I don't really think this is a "fix" i'm just making the sprites less ugly. To be honest i'm not entirely sure if me changing the sprites significantly is where you're taking issue with it, I feel like we're not on the same wavelength with this.

**Comment by ChangelingRain** [comment]
I think I can explain; the sprites got changed semi-recently;
This is the current sprite. these

**Comment by TechnoAlchemisto** [comment]
Oh, I see.  Okay we're on the same page now. Personally I like my color shifts better, it's more distinct and I'm not a fan of the dark iris blink.

But I'm kind of biased .

**Comment by KorPhaeron** [comment]
@TechnoAlchemisto 

Is this ready to merge or not I literally have no idea what you two are talking about

**Comment by TechnoAlchemisto** [comment]
I think so.

**Comment by KorPhaeron** [comment]
well it comes down to OPINIONS and TA made the item and I can't tell the difference anyway so here goes nothing

**Comment by ChangelingRain** [comment]
Aaaaa the doubleeye didn't even loop right aaaaa

**Pull request merged**
