### PR TITLE
[READY] MetaStation Brig Revamp

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request

This pull request changes the location of the warden's office on MetaStation and tweaks other things about the brig. Notable changes include removing the previously rarely used Sec desk, shrinking brig cells to 2x2, moving part of the department towards the center of the station more, and changing the layout of several rooms as well as adding a few small things to the armory. Some miscellaneous office supplies were removed.

Full Picture
image

New Armory, Gear Room, and Evidence Room
image

New Sec Hallway, Prison Cells, and Warden's Office
image

New Holding Cells
image

## Why It's Good For The Game

Warden can now talk to crew without them waiting around and without compromising a restricted area.

Layout changes open new ways to do/combat theft and trespass. Standard firing pins are vulnerable, so is the gear room. More sightlines mean higher risks but easier access.

The new layout also prevents security from being two long straight hallways and will hopefully encourage more interesting combat in the brig.

Prison cells have been changed to make searching, confiscating, and restraining prisoners one fluid clockwise motion around the cell and saves space for the Warden's new location.

Bomb and hazmat suits have been moved for space reasons and also so that people will think about utilizing or looting them more often.

The Secway key was moved to the Warden's Office to give them control over the equipment since distribution is part of their job.

Adding trimline to the brig helps showcase the work done and inspire others to think about utilizing it in the future and potentially add more floor decals (I think they look really sweet, too)

Tools have been moved as a quality of life improvement in case of fire or power outages.

The grenade launcher has been added to encourage security to use diverse (Nonlethal of course!) methods to capture criminals and to keep it from dying out if donut is removed from rotation.

The extra sechuds were added since they can be destroyed if caught on fire and to showcase the radical gar sechuds that have not been seen elsewhere. Also armory looters might be able to get them without sec access to lockers.

Additional lattices were added outside the armory to improve maneuverability in a heavily contested EVA area. No more straight line pew pew disabler battles.

Moving the armory shutters makes it harder to just keep the armory doors open, which means the warden will actually have to keep track of who is taking what.

Adding deputy armbands so the HoS can designate helpers without implanting them like on other maps.

## Changelog
:cl:
add: Major renovations to the MetaStation Brig
add: Donut Station Grenade Launcher added to Armory Equipment
add: A public-facing desk for the Warden
tweak: The Secway Key has been moved to the Warden's Office
/:cl:

### CODE REVIEW

**Comment by TheVekter** [comment]
Fuck you

**Comment by HomocidlePancakes** [comment]
>Looks nice to me. Makes it easier to break into the armory (that's a good thing).

I don’t see how it’s easier to break in. The side entrance is gone, meaning you are more likely to get spotted while breaking in. The armory overall has a greater visibility, meaning officers can spot breaks in from space easier and shoot pretty much everything that’s standing there from the hallway. 2-tile wide hallways makes it harder to escape from brig and the 2-tile wide armory leaves little to no room for dodging. 

Thanks to the better visibility armory overall became a lot more easier to defend.

**Comment by TheVekter** [comment]
> > Looks nice to me. Makes it easier to break into the armory (that's a good thing).
> 
> I don’t see how it’s easier to break in. The side entrance is gone, meaning you are more likely to get spotted while breaking in. The armory overall has a greater visibility, meaning officers can spot breaks in from space easier and shoot pretty much everything that’s standing there from the hallway. 2-tile wide hallways makes it harder to escape from brig and the 2-tile wide armory leaves little to no room for dodging.
> 
> Thanks to the better visibility armory overall became a lot more easier to defend.

Easier to defend, but also easier to quick emag in, snag what you want, and get out. It creates more conflict and that's a good thing.

**Comment by HomocidlePancakes** [comment]
The door is located at the most populated part of brig. There is no way you can emag in, kill armsky and leg it before somebody notices.

**Comment by CAPTTLasky** [comment]
> 
> 
> The door is located at the most populated part of brig. There is no way you can emag in, kill armsky and leg it before somebody notices.

Guess you'll have to examine the rest of it and think of other creative ways you could get in and get out quickly!

**Comment by HomocidlePancakes** [comment]
>Guess you'll have to examine the rest of it and think of other creative ways you could get in and get out quickly!

There are 2 ways in - space and the hallway. I’ve analyzed both of them. If you think I’ve missed something, then please, point it out instead of being vague.

**Comment by CAPTTLasky** [comment]
launchpad, evidence deconn, fireaxe the reinforced window to the left, steal a baton from the gear room on the right and robust the warden, chameleon box, teleport, monkey ventcrawl, probably 5-10 more I cant think of.

**Comment by HomocidlePancakes** [comment]
>evidence decon

Equivalent to breaking in from space

>steal a baton from the gear room on the right and robust the warden, chameleon box

Equivalent to going in through the main door

>launchpad, teleport, monkey ventcrawl 

All of these methods bypass the terrain, so they don’t apply. Bombing would fall under the same category.

>fireaxe the reinforced window to the left 

And on current meta you can hack/open/emag the door which is much easier. You do realize I am complaining about the brig being more reinforced? Hell, it would be better if you had walls there, so that officers have one less angle to shoot from.

**Comment by Canohaaaaaaa** [comment]
Were the dragNETs removed ? It's hard to tell if you stacked them with the rest of the gear.

**Comment by Dorsisdwarf** [comment]
makes it easier to tailgate into the armory but I like the other changes a lot

**Comment by Fhaxaris** [comment]
i think you need to remove the purple arrow things on doors that no longer have a door paired to them

**Comment by CAPTTLasky** [comment]
> 
> 
> -Were the dragNETs removed ? It's hard to tell if you stacked them with the rest of the gear.
> -The printer feels like it's in the way, why move it from the warden's office to the hallway?
> -One of the warden's office window/grille isn't electrified (the one near the donuts).
> Nice changes overall.

>i think you need to remove the purple arrow things on doors that no longer have a door paired to them

DragNets are there, just on the bottom. I'll move them to the top.
The printer is definitely in the way, but it was in the way in the office, too. I would say remove it entirely but who knows? I say lets see what happens with it.
I'll electrify the window.

I haven't had much exposure to the door helpers but I'll look into them before my next commit.

Thanks for your comments!

**Comment by GithubPrankster** [comment]
I really like this! Brig may become much more interesting to be in, and generally Warden may actually better do their job.

**Comment by bobbahbrown** [comment]
looks nice

**Comment by Shadowflame909** [comment]
only thing I dislike here is how it moves the warden further away from the armory.

He doesn't have a window to give items to those who request it, and now it's quite honestly easier to catch the door behind him. If you were to request something.

I dunno, easier antagging I guess.

**Comment by CAPTTLasky** [comment]
> 
> 
> only thing I dislike here is how it moves the warden further away from the armory.
> 
> He doesn't have a window to give items to those who request it, and now it's quite honestly easier to catch the door behind him. If you were to request something.
> 
> I dunno, easier antagging I guess.

That's a good point about the window, I'll make a commit and replace one of the windows with a desk so the Warden can distribute without needing to open the door repeatedly.

**Comment by Twaticus** [comment]
this looks awesome. love the idea of wardens office having a front desk to sec hallway and the room placement gives a nice view of the brig while still being close enough to the armory. the dark tiles, new curved decals, cell facelift, its all very pleasing to look at. 

the only thing that looks like it would drive me mad ingame is that photocopier jutting out in the hall above the cells. the placement is just asking for people to get stuck between there and the lockers. throws off the flow imo. other than that, amazing job!

**Comment by CAPTTLasky** [comment]
We'll see what happens with the photocopier! I'm sure it can be moved if it ends up being trouble, but I kind of like how it blocks the cells from a straight rush to the armory shutters and gives the bomb/hazsuits a little nook.

Also, as of now I'm going to leave it as it is unless a maintainer wants me to change something, at least until the players get a hold of it and start yelling at me. Don't want to keep scope creeping.

**Comment by Twaticus** [comment]
understandable! the armory shutter rush prevention is a good point for it to stay there and the rest of the positive brig changes will outweigh whatever annoyances the photocopier might cause

**Comment by CAPTTLasky** [comment]
Main post updated, changes made via skoglol's request.

**Comment by kopoba** [comment]
Horrible change. God damn warden pepe in center that squeeze corridors to cells to 2 tittles wide and you must go around it to reach cells. Looks like labyrinth for AI bots training to move around corners.

**Pull request merged**
