### PR TITLE
Removes freon from the maps

### PR DESCRIPTION
**Pull request by lzimann**

### CODE REVIEW

**Comment by Kraseo** [comment]
YES PLEASE

**Comment by PKPenguin321** [comment]
I ded plz remov

**Comment by PKPenguin321** [comment]
????

**Comment by KorPhaeron** [comment]
It is causing server crashes

**Comment by FlavoredCactus** [comment]
here lies goofgas. It died as it lived.

**Comment by Iamgoofball** [comment]
THANKS FOR FUCKING IGNORING THE CRASH FIX YOU RETARSS

**Comment by Iamgoofball** [comment]
Fuck you all

**Comment by Iamgoofball** [comment]
Holy shit

**Comment by Iamgoofball** [comment]
We fixed the fucking issue causing the crashes and you just remove it from the maps

**Comment by Iamgoofball** [comment]
Why are you fuckers doing this

**Comment by Iamgoofball** [comment]
I quit

**Comment by Nienhaus** [comment]
:c

**Comment by Iamgoofball** [comment]
Jesus fucking christ

**Pull request merged**
