### PR TITLE
adds freedom vendors to centcomm for 4th festive [speedmerge asap]

### PR DESCRIPTION
**Pull request by Tlaltecuhtli**
:cl: optional name here
add:freedom
/:cl:

### CODE REVIEW

**Comment by Tlaltecuhtli** [comment]
hmm why are there 80k less lines

**Comment by Cyberboss** [comment]
Cause you didn't mapmerge, soiboi

**Comment by 81Denton** [comment]
hold on this gives me an idea

**Comment by Cyberboss** [comment]
Denton's is memier

**Pull request closed without merging**
