### PR TITLE
Remove rats from total count on death

### LINKED ISSUE #53187: Dead rats contribute to the rat cap
Dead rats contribute to the rat cap making regal rats unable to get more mice and rats if there is enough dead rats on the map.

### PR DESCRIPTION
**Pull request by nightred**
## About The Pull Request

Rats are removed from the SSmobs.cheeserats list on death now
This caused blocking when spawning new rats.

Fixes #53187 

## Why It's Good For The Game

Fixes Issues

## Changelog
:cl:
fix: New rats can spawn for the king when some die.
/:cl:

### CODE REVIEW

**Comment by Jared-Fogle** [comment]
Make sure it adds them back when they get revived through strange reagent or lazarus injector.

**Comment by nightred** [comment]
> Make sure it adds them back when they get revived through strange reagent or lazarus injector.

Added with player controlled rats, and admin revivals can bypass the limit of rats.

**Comment by RaveRadbury** [comment]
https://www.youtube.com/watch?v=qo5imhAvUdI

**Review by ghost — CHANGES_REQUESTED** [review]
edit: disregard that, i suck cock.

**Comment by Qustinnus** [comment]
or well, also mouse code, remove the mouse part and keep the rat part.

**Comment by nightred** [comment]
Mouse migrations are not part of the rat cap, only mouses spawned by them eating cheese.
This does make mouses a bit more complicated for the rat cap but i feel it is valid.

**Pull request merged**
