### PR TITLE
Revert "Adds a short telegraph to the watcher's blasts"

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
Reverts tgstation/tgstation#30389

Why: I forgot to close it

Ergosavi made an excellent post in it if you want actual gameplay reasons why not

### CODE REVIEW

**Comment by DoctoreMad** [comment]
24 hour rule :^)

**Comment by Xhuis** [comment]
Are we deadset on having watchers be completely unfun to fight

**Comment by Hatfish** [comment]
For consistency's sake you should probably remove the goliath's telegraph if you're going to leave watchers without one.

**Comment by DoctoreMad** [comment]
@Hatfish SHUT UUUUP

**Pull request merged**
