### PR TITLE
[DNM] A bunch of Battle Royale features for events. TM this to enable Battle Royale mode on Delta.

### PR DESCRIPTION
**Pull request by KathyRyals**
Brought to you by Jimmius (@Clyde-Thunderpants) and yours truely.
Now with the added STORM brought to you by @tralezab 

## About The Pull Request

Add lootcrates of varying rarity with assorted coloured rays.
Double the health of players to extend firefights.
Adds a shit ton of lootcrates spawners on Delta
DISABLE EVERY JOB SLOTS EXCEPT FOR ASSISTANT

# Adds the damn fortnite storm

## Why It's Good For The Game

We got a number one victory royale
Yeah, Fortnite, we 'bout to get down (Get down)
Ten kills on the board right now
Just wiped out Tomato Town
My friend just got downed
I revived him, now we're heading south-bound
Now we're in the Pleasant Park streets
Look at the map, go to the marked sheet

Take me to your Xbox to play Fortnite today
You can take me to Moisty Mire, but not Loot Lake
I really love to chug jug with you
We can be pro Fortnite gamers

He said
"Hey broski, you got some heals and a shield pot?
I need healing and I am only at 1 HP"
Hey dude, sorry, I found nothing on this safari
I checked the upstairs of that house but not the underneath yet
There's a chest that's just down there
The storm is coming fast and you need heals to prepare
I've got V-Bucks that I'll spend
More than you can contend
I'm a cool pro Fortnite gamer (Cool pro Fortnite—)

Take me to your Xbox to play Fortnite today
You can take me to Moisty Mire, but not Loot Lake
I really love to chug jug with you
We can be pro-Fortnite gamers

Bro my jaw hurts so much
Water break

La-la-la-la-la-e-ya
La-la-la-la-la-e-ya
La-la-la-la-la-e-ya
Will you be my pro Fortnite gamer? (Pro Fortnite gamer)

Can we get a win this weekend?
Take me to Loot Lake
Let's change the game mode and we can Disco Dominate
Let's hop in an ATK
Take me to the zone
I'm running kind of low on mats, I need to break some stone
Dressed in all his fancy clothes
He's got Renegade Raider and he's probably a pro
He just shot my back
I turn back and I attack
I just got a victory royale
A victory royale

Take me to your Xbox to play Fortnite today
You can take me to Moisty Mire, but not Loot Lake
I really love to chug jug with you
We can be pro Fortnite gamers

## Changelog
:cl:
add: pain
/:cl:

### CODE REVIEW

**Comment by tralezab** [comment]
>no storm

**Comment by KathyRyals** [comment]
> 
> 
> > no storm

PR a storm to this branch, you won't.

**Comment by D4C-420** [comment]
no map edit to make delta surrounded by a giant electric grill  so sad.

**Comment by Mothblocks** [comment]
you guys know you can test merge closed prs, right?

**Comment by Fikou** [comment]
> no random lootcrates

**Comment by Bluedazzled** [comment]
chug jug with you is a valid reasoning

**Comment by KathyRyals** [comment]
> 
> 
> you guys know you can test merge closed prs, right?

I wanted the checks before closing.

**Comment by MrDoomBringer** [comment]
We got a number one victory royale
Yeah, Fortnite, we 'bout to get down (Get down)
Ten kills on the board right now
Just wiped out Tomato Town
My friend just got downed
I revived him, now we're heading south-bound
Now we're in the Pleasant Park streets
Look at the map, go to the marked sheet

Take me to your Xbox to play Fortnite today
You can take me to Moisty Mire, but not Loot Lake
I really love to chug jug with you
We can be pro Fortnite gamers

He said
"Hey broski, you got some heals and a shield pot?
I need healing and I am only at 1 HP"
Hey dude, sorry, I found nothing on this safari
I checked the upstairs of that house but not the underneath yet
There's a chest that's just down there
The storm is coming fast and you need heals to prepare
I've got V-Bucks that I'll spend
More than you can contend
I'm a cool pro Fortnite gamer (Cool pro Fortnite—)

Take me to your Xbox to play Fortnite today
You can take me to Moisty Mire, but not Loot Lake
I really love to chug jug with you
We can be pro-Fortnite gamers

Bro my jaw hurts so much
Water break

La-la-la-la-la-e-ya
La-la-la-la-la-e-ya
La-la-la-la-la-e-ya
Will you be my pro Fortnite gamer? (Pro Fortnite gamer)

Can we get a win this weekend?
Take me to Loot Lake
Let's change the game mode and we can Disco Dominate
Let's hop in an ATK
Take me to the zone
I'm running kind of low on mats, I need to break some stone
Dressed in all his fancy clothes
He's got Renegade Raider and he's probably a pro
He just shot my back
I turn back and I attack
I just got a victory royale
A victory royale

Take me to your Xbox to play Fortnite today
You can take me to Moisty Mire, but not Loot Lake
I really love to chug jug with you
We can be pro Fortnite gamers

**Comment by notfrying1pans** [comment]
> 
> 
> > you guys know you can test merge closed prs, right?
> 
> I wanted the checks before closing.
@KathyRyals 
cant you add these actions to your fork?

**Comment by Mothblocks** [comment]
they can also be ran locally x_x

**Pull request closed without merging**
