### PR TITLE
Adds black market meat ship to Z6

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
Removes it as an away mission.

It's small and short and we've all seen it a thousand times in regards to away missions, but has a ton of detail/is actually well mapped so it makes it perfect for space debris.

Updated the away mission config to remove all the maps I've taken out in the last few commits.

@Cheridan mapped this originally.

### CODE REVIEW

**Comment by KorPhaeron** [comment]
Well thats odd

**Comment by GunHog** [comment]
Pics plz

**Comment by Zilenan91** [comment]
What map is this again?

**Comment by optimumtact** [comment]
Was there a missing type added in the away mission code?
 undefined type: /area/awaymission/BMPship/Af

_maps/map_files/generic/z6.dmm:415:error: expected )

**Comment by Jordie0608** [comment]
No Kor just didn't finish the path; it should be `/area/awaymission/BMPship/Aft`
Which makes me question how this was done.

**Comment by KorPhaeron** [comment]
Copypasting in the map editor.

Very odd

**Comment by KorPhaeron** [comment]
Something has gone terribly wrong with this PR

**Comment by optimumtact** [comment]
but it built?

**Pull request closed without merging**
