### PR TITLE
Add simple circuits RCD upgrade

### PR DESCRIPTION
**Pull request by Dennok**
## About The Pull Request
Add to RCD simple circuits upgrade.
Simple circuits upgrade allow rcd work as electro adaptive pseudo circuit

And make RCD upgrade work as a flag, that can contain all upgrades of rcd.

## Why It's Good For The Game
Engineers like it. 
Flag better than binary.

## Changelog
:cl:
add: Simple circuits RCD upgrade.
/:cl:

### CODE REVIEW

**Comment by Detective-Google** [comment]
based dennok PR, this is a neat af feature

**Comment by MrFluffster** [comment]
I'm fairly sure this is called a "power creep". Especially the silo link sounds stupidly overpowered.

The RCD doesn't need buffs, it's already a strong and fast alternative with downsides(that aren't even that big). We added special engineer bags for a reason.

**Comment by Dennok** [comment]
This powercreep blocked by researtch and mats. If need price can be increased.

Link can be aquired in another way, just construct orm or fab and link it to silo. 
RCD need be linked too, if it dont upgraded from start.

**Comment by CPTANT** [comment]
Simple circuits is fine.
Silo link is a HUGE buff that the RCD doesn't need.

**Comment by CPTANT** [comment]
> 
> 
> This powercreep blocked by researtch and mats. If need price can be increased.
> 
> Link can be aquired in another way, just construct orm or fab and link it to silo.
> RCD need be linked too, if it dont upgraded from start.

That still requires you to visit a stationary machine.

**Comment by Tlaltecuhtli** [comment]
its not like you can make an ore silo and eject all the metal from your lathe and fill it in 1 min then walk around with infinite rcd

**Comment by CPTANT** [comment]
> 
> 
> its not like you can make an ore silo and eject all the metal from your lathe and fill it in 1 min then walk around with infinite rcd

No you can, by sacrificing inventory space.

**Comment by Dennok** [comment]
> its not like you can make an ore silo and eject all the metal from your lathe and fill it in 1 min then walk around with infinite rcd

You can unload your pile of metal in crate/locker/bluespace backpack, and have your near infinite rcd, by loading it by it.

**Review by 81Denton — CHANGES_REQUESTED** [review]
Please split these into two PRs so each one can be reviewed separately. The RCD part will have a lot of discussion on it, so it will be better to have it in a separate PR.

**Comment by Dennok** [comment]
> Please split these into two PRs so each one can be reviewed separately. The RCD part will have a lot of discussion on it, so it will be better to have it in a separate PR.

I can just disable research? Lleave it as admin spawned?

**Comment by fludd12** [comment]
>84 commits
>10+ web edited commits

Someone didn't properly pull remote master!
I suggest using [git rebase to squash those commits into one](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html), properly named commit for the sake of a sane commit list.

**Comment by Dennok** [comment]
Strange. Last time as i force push it broke pr.

**Comment by Dennok** [comment]
What mean RED LABEL?

**Comment by Dennok** [comment]
@actioninja I fix conflict.

**Comment by actioninja** [comment]
I just realized I added red label instead of merge conflict, whoops

**Pull request merged**
