### PR TITLE
Fix name of greek cucumber and attack verbs

### PR DESCRIPTION
**Pull request by Mothblocks**
:cl:
spellcheck: Cucumber greek is now Greek cucumber
spellcheck: Fixed attack verbs on the greek cucumber
/:cl:

### CODE REVIEW

**Comment by carshalash** [comment]
Just remove it. desu.

**Comment by Mothblocks** [comment]
no oranges likes it

**Comment by carshalash** [comment]
> no oranges likes it

Ask if we can remove it due to recent events, desu.

**Comment by Mothblocks** [comment]
do it yourself

**Pull request merged**
