### PR TITLE
Nanite timer rework and general code improvements

### PR DESCRIPTION
**Pull request by XDTM**
## About The Pull Request

Removed the old timer system from nanite programs, replaced them with 4 new timers:
- Restart Timer: every time the program is deactivated, it will re-activate by itself after the timer expires
- Shutdown Timer: every time the program is activated, it will deactivate by itself after the timer expires
- Trigger (repeat) Timer: triggers the program every time the timer expire, keeps repeating as long as the program remains active
- Trigger Delay: Delays trigger activation by a given amount of time

Other changes:
- Stasis prevents nanites from processing
- Moved the inherited trigger function to an on_trigger function to avoid having to ..() every time
- Removed the triggered subtype, since it was not doing much
- Removed the unused nanite hijacker, which in the cloud era is mostly pointless and a maintainability burden with its UI

## Why It's Good For The Game

Makes timers more intuitive to use, making some programs easier to set up without using two or three separate programs.
Cleans up the code in some ways, which is always good.

## Changelog
:cl:
add: Nanite timers have been changed into four separate timers: Restart Timer, Shutdown Timer, Trigger Repeat, and Trigger Delay. See the wiki or github for more information.
tweak: Stasis now prevents nanites from processing and syncing.
/:cl:

### CODE REVIEW

**Comment by stylemistake** [comment]
Since you have touched old tgui code, perhaps you're interested in porting this whole interface to tgui-next?

**Comment by XDTM** [comment]
Sure, although I have to learn it first

**Review by actioninja — CHANGES_REQUESTED** [review]
I hate pulling the "this isn't implemented the way I want" but could you add a boolean for whether or not timers are enabled instead of basing it off whether the timer value is 0 or not?
It's related to the ui reworks I'm working on.

**Comment by XDTM** [comment]
Considering that codes work the same way it could add up to 8 variables to track with every change of codes and timers. Maybe it could be calculated and sent as a parameter in the tgui data proc instead? Not familiar with the new system yet.

**Review by actioninja — APPROVED** [review]
I initially misunderstood how the new timer system works

**Pull request merged**
