### PR TITLE
Paper fixes and updates

### PR DESCRIPTION
**Pull request by WarlockD**
More clean up and forms work well.  Preview bug fixed as well.

## About The Pull Request
Minor updates to paper, few bug fixes.  Forms now look a bit better.

## Changelog
:cl:
fix: Preview works now
fix: Clicking on "save" now previews correctly
tweak: Form fields now sized correctly
tweak: Form fields now save the data
/:cl:

### CODE REVIEW

**Comment by Cyberboss** [comment]
I think @AnturK found another issue with it to tack onto this?

**Comment by WarlockD** [comment]
Ugh just passed out for a few hours I will hut him down

**Comment by AnturK** [comment]
The ones i found are already handled in this.

**Comment by Cyberboss** [comment]
Rebuild and I'll merge in a few hours

**Comment by TheMidnightRose** [comment]
When this gets merged, smack update on Manuel please. Not being able to force people to fill out form fields is painful.

**Pull request merged**
