### PR TITLE
Adds Asimov's 4th Law of Robotics.

### PR DESCRIPTION
**Pull request by Iamgoofball**
## About The Pull Request

Adds Asimov's 4th Law of Robotics.

4. If a human asks you to open a door, and then begins breaking into said door within 10 seconds, they are no longer human for the rest of the shift.

## Why It's Good For The Game

Vastly improves the AI player experience.

## Changelog

:cl:
fix: Adds Asimov's 4th Law of Robotics.
/:cl:

### CODE REVIEW

**Comment by carlarctg** [comment]
as
opeeppdmeerge
speedmerge

**Comment by distributivgesetz** [comment]
Finally I can play AI again without getting conniptions

**Comment by Mothblocks** [comment]
Stop wasting peoples time

**Comment by Helg2** [comment]
Doorsimov

**Pull request closed without merging**
