### PR TITLE
[READY] Nerfs tasers (and all energy weapons capable of firing electrodes) to only have 1 electrode per engament

### PR DESCRIPTION
**Pull request by KetasDotepasto**
## About The Pull Request
This PR represents an alternative to pull request #42930.

This pull request changes all energy weapons capable of firing electrodes in a way that they can only fire one electrode per engament. This is achieved by giving them a limited store of electrodes. Once depleted, the weapon will not be able to fire any more electrodes. If the weapon goes unused for 30 seconds, the weapon's stock of electrodes will be refilled.

If the last electrode is depleted, the weapon will automatically switch to next ammunition, the same as if the weapon had been activated in hand. For the hybrid taser, this is disable.

Potential future work would be to add additional counters to tasers. For example, some clothing, such as firesuits, could be made to grant the wearer immunity from taser shots.

## Why It's Good For The Game

The problem with tasers is that they lead to anticlimatic combat, since they deliver a 1 hit stun, which, if your opponent is bent on murder, means you are basically dead.

However, I believe that 1-hit kills have a place in game design, namely to foster paranoia among the players. Therefore, the ranged instant stun should not be excised entirely. This PR will make it so that a combat can be opened with an attempt at delivering an instant stun. However, if this attempt misses, you now have to use the taser in disabler mode, which needs 3 hits to down somebody.

## Changelog
:cl:
tweak: stun capable energy weapons have a limited store of electrodes (currently 1).
tweak: If a stun capable energy weapon runs out of electrodes, it has to go unused for 30 seconds to recharge its electrodes.
tweak: After the last electrode has been fired, the weapon switches to the next firing mode. (Disable in case of the taser).
/:cl:

### CODE REVIEW

**Comment by PKPenguin321** [comment]
oranges will close this

**Comment by TheRespectedMan** [comment]
My chief issue with tasers is that i can tase antags in the back and put them in perma. 

Disabler combat is an improvement in my eyes because once i fire at them they can immediately try to counter. For example, activating their EMP implant to empty my disabler, or pull out their energy sword to deflect my beams, or to simply return fire with their gun. 

1 taser is all i need to tase an antag in the back for a "search"

**Comment by zxaber** [comment]
It isn't a bad thing for antags to have to be careful around Sec. Taking on an armed security _should_ be difficult and risky. And really, do antags need a buff at this point?

**Comment by optimumtact** [comment]
no zxaber, we're obviously just spending ages arguing about it for the pure fun of it.

**Comment by nicbn** [comment]
This is a chaotic simulator not an esport, mechanics should not require skill, but strategy. Make it so that it takes multiple shots to stun someone or something, but don't fucking make it a point-an-click one-shot sniper game.

**Comment by ExcessiveUseOfCobblestone** [comment]
How are tasers paranoia when you know that by default people in security have them?

**Comment by Angustmeta** [comment]
Make sure this doesn't break turrets.

**Comment by kevinz000** [comment]
what nicbn said

**Comment by KetasDotepasto** [comment]
@Angustmeta 

I did try wether my change would make the AI's turrets turn lethal after firing an electrode. They did not.

@nicbn 

My next PR will be one that makes some clothing (e.g. firesuits, bombsuits, spacesuits, hardsuits) taserproof.

**Comment by ShizCalev** [comment]
A hail-mary sort of deal with a single chance at stunning if you're completely fucked sounds good to me tbh. Much prefer this over #42930

**Comment by optimumtact** [comment]
I don't, I am trying to move away from binary stuns at range, this is a step in that direction, but imo we don't need iterative moves here, we just need to accept the disabler fits the role far better than the taser does.

**Comment by nicbn** [comment]
@KetasDotepasto oh yeah tasers will be one shot AND you won't even be able to tase anyone you want.
The famous nerf to oblivion technique. Just remove it straight, nerd.

**Comment by KetasDotepasto** [comment]
@nicbn The idea is to give widely available clothing that proctects against tasers, but which is also highly visible on the sprite. That way if you're wearing taser protective clothing, you're not proadcasting "I'm valid" (Unless your clothing happens to be a syndicate space-/hardsuit), but instead only "I'm up to no good".

This leaves traitors with a question: "Do I put on a firesuit, and look suspicious, or do I try and fly under the radar?"

This would enhance the social deduction aspect of the game.

**Comment by Angustmeta** [comment]
> 
> 
> @Angustmeta
> 
> I did try wether my change would make the AI's turrets turn lethal after firing an electrode. They did not.

But do they keep firing taser-shots at the same rate as before?

**Comment by adamkad1** [comment]
i dont like one shot stuns, even if you only get one shot

**Comment by HomocidlePancakes** [comment]
Out of all the suggestions to rework tasers that were made in the "remov tazr kek" PR why this one?

**Comment by KetasDotepasto** [comment]
@HomocidlePancakes Because I came up with.

**Comment by JMoldy** [comment]
I'm not gonna be happy to see tasers go, but if they're gonna go, just get rid of them.

Setting them up like this is just going to make them frustrating for antags because they're still one-shot drops, and this will just make them frustrating for security to use because of how gimped they are.

If we're getting rid of them then just let's go through with it.

**Comment by Anonymous-Player** [comment]
@KetasDotepasto 
Post your hours of security played.

**Comment by KetasDotepasto** [comment]
@Anonymous-Player 18h.

**Comment by Anonymous-Player** [comment]
Pretty pathetic. I've only been playing for ~2 months after this tracking feature was added and have 80 hours as Security, 120 if you count Captain. If you've been playing for years and have that amount it shows that you have no actual experience. People that don't play as job X shouldn't make changes to the game that will primarily effect job X.

**Pull request closed without merging**
