### PR TITLE
Remove the singularity from box and meta, replaced with TEG setups

### PR DESCRIPTION
**Pull request by optimumtact**
The singularity causes too much lag and ends most rounds prematurely.

I've had to remap engineering quite significantly, so I'll put up screenshots when I get home tonight.

### CODE REVIEW

**Comment by Incoming5643** [comment]
There's nothing in the world you could say that would make me feel like this is worth it.

**Comment by RemieRichards** [comment]
:+1: Good, I like PRs that people mistake when they don't read the actual changes.

**Comment by Incoming5643** [comment]
Ya got me :man: :gun: :cop: :

**Comment by GunHog** [comment]
DANG IT ORANGES!!!!!!! This is what happens when someone forgets to juice him!

**Comment by Iamgoofball** [comment]
:+1:

**Comment by Fayrik** [comment]
:-1: :100: 
This PR is nothing but a blatant shill.

~~Okay I like it but don't tell anyone.~~

**Comment by Ricotez** [comment]
:+1:

**Comment by optimumtact** [comment]
This is going to  make the server better in the long run

we all know that

**Comment by Fox-McCloud** [comment]
lulz

**Comment by daman997** [comment]
singularity only good power source all else for nerds

**Comment by duncathan** [comment]
TEG is best engine and I will kill to ensure that it never lands in that hands of those damn engies
:+1:

**Comment by Niknakflak** [comment]
This is like the 4th maybe 5th time oranges has made this kind of joke.  Its old

**Comment by optimumtact** [comment]
2nd actually, which you would know if you didn't have a blinding hateboner for me

**Comment by Niknakflak** [comment]
I guess you just magically make things old quicker.  10/10

**Comment by Jalleo** [comment]
Ill see it when i believe it.

**Comment by optimumtact** [comment]
It could happen sooner than you think

**Comment by TheVekter** [comment]
a y y  l m a o

**Comment by Memendia** [comment]
TEG is better..

**Comment by Firecage** [comment]
....Can we perhaps ban stupid PR's like this?

**Comment by duncathan** [comment]
What's wrong with the PR?

**Comment by TheVekter** [comment]
It's a well-known fact that @Firecage has no sense of humor.

**Comment by Firecage** [comment]
That is a well-known fact,  but regardless I hate joke/troll PR's like these.

**Comment by Jalleo** [comment]
Dont worry be happy the clickbait will always occur

**Comment by optimumtact** [comment]
@Firecage loosen up friend

**Pull request merged**
