### PR TITLE
Fixes "There's a tree in space" adventure

### LINKED ISSUE #75427: Remembering the christmas party always leads to losing your drone in "strange tree" encounter
## Reproduction:
Step 1: encounter the strange tree in exploration drone
Step 2: choose everything until "remember the christmas party" and choose that
Step 3: choose "snap a photo"
Step 4: choose "take a moment to calm down"
Step 5: see issue - nothing is happening

### PR DESCRIPTION
**Pull request by E231kei500bandai**
## About The Pull Request

Removes the enter effect that set your confusion to 9999 on the epilogue page
Having confusion over 30 would send you to the page where you have to either give up or press a button until your confusion goes back under 30. However setting it to 9999 was very confusing as there is no indication how exactly much confusion you had, so players would be sitting there pressing the button over and over again not realizing they were only at like 9643 confusion and had to press it hundreds of more times.
Anyway, that doesn't matter since even if they pressed all those buttons and got back to the epilogue, they would just be sent right back to this confusion page after getting confusion set to 9999 again. So it was impossible to beat. 

Fixes #75427

Also makes JSON prettier

## Why It's Good For The Game

Now you can actually beat the adventure

## Changelog
:cl:
fix: fixed "There's a tree in space" adventure being impossible to beat
/:cl:

### CODE REVIEW

**Comment by san7890** [comment]
this stuff has really gotta go through a JSON prettifier the diff is incomphrensible

**Comment by san7890** [comment]
that wasn't a hard ask btw...

@tralezab @AnturK were the JSONs intentionally obfuscated for any reason? if anyone is sweaty enough they can literally just feed the JSON into a website to have it be prettified so it really just ultimately harms maintainability in cases like this

**Comment by BlueMemesauce** [comment]
> that wasn't a hard ask btw...
> 
> @tralezab @AnturK were the JSONs intentionally obfuscated for any reason? if anyone is sweaty enough they can literally just feed the JSON into a website to have it be prettified so it really just ultimately harms maintainability in cases like this

Only takes like 3 seconds to do it might as well

These ones are specifically meant to be read since they're the example adventures. The other adventures are manually set in database, so they're not accessible.  Although unfortunately that means people can't maintain them but at least I can fix this one.

**Comment by AnturK** [comment]
No reason for it, i just didn't bother pretty printing it.

**Pull request merged**
