### PR TITLE
DNA Restoration Virus Symptom

### PR DESCRIPTION
**Pull request by GunHog**
Adds a new virus symptom: DNA Restoration. This is a replacement for DNA Aide, which was removed.
- Heals <b>brainloss</b> damage.
- Reduces radiation (but not toxin damage)
- Cleanse the SE of unwanted mutations, but does not affect power mutations.

~~This is a work in progress.~~ The bonus listed here is not finalized, and is subject to change/buffs/nerfs.

The code is not optimized, and I am sure to have made mistakes, so I will correct them as the PR matures. Basic testing confirms it is performing its intended function so far.

### CODE REVIEW

**Comment by Xhuis** [comment]
:+1:

**Comment by KorPhaeron** [comment]
I'd rather cloneloss be kept hard to heal personally.

**Comment by GunHog** [comment]
What are the sources of cloneloss other than un-upgraded cloning and slimes? I do not expect there to be much impact from adding it.

**Comment by KorPhaeron** [comment]
Clones, slimes, the decloner gun, and taking too much damage while using a Guardian.

It's the only damage type we have that isn't healed in 5 seconds from anywhere, it's nice to have as an option for the future if nothing else.

**Comment by GunHog** [comment]
Decloner does radiation damage, not clone.
````
/obj/item/projectile/energy/declone
	name = "radiation beam"
	icon_state = "declone"
	nodamage = 1
	damage_type = CLONE
	irradiate = 40
````

I did not know about the Stand thing. Cloner damage I would want to address with this, providing an alternative to the cryo pods, damage from slimes do not concern me either, but the Guardian thing does present an issue that will have me considering if or not I should nerf or remove that feature. I would like to put something else there though.

**Comment by KorPhaeron** [comment]
The guardian cloneloss was actually put in specifically to counter people who use regen viruses, (or too many chems in the blood) yeah.

**Comment by Kromgar** [comment]
Is the decloner even in the game?

**Comment by GunHog** [comment]
Abductors have them as a sidearm, yes. Please suggest a replacement for the cloneloss healing. Something that fits with the rest of the symptom, that will make it worth using.

**Comment by Dorsisdwarf** [comment]
Also you can get it in R&D if you know how to use the experimentor

**Comment by Shadowlight213** [comment]
Decloner is like the shittiest gun in the game

**Comment by GunHog** [comment]
I can make a PR to allow making the gun, and give it 5 cloneloss damage, 25 irradiate. But, that is a discussion for another location.

With what should I replace the cloneloss healing in this symptom?

**Comment by KorPhaeron** [comment]
Heal brain damage?

Probably the most obnoxious part of getting cloned since the default crying set up won't fix it

**Comment by GunHog** [comment]
Kind of lame, but okay...if one other person agrees and explains why, as you have, I will change it to heal brain damage. I may need to change the name to suit its function, though.

**Comment by KorPhaeron** [comment]
Could also make it cure the worst defect of all (bring a lizard)

**Comment by KorPhaeron** [comment]
In all seriousness though viruses that only target specific mutant races might be interesting

**Comment by Shadowlight213** [comment]
Foxdie virus when?

**Comment by Jalleo** [comment]
Gunhog having it heal braindamage is really op for medical players and for during a brainrot outbreak it could help to stabalize the amount of damage people have and help focus on making a cure sooner. Changing to helping to cure brain damage than cloneloss is much more ideal.

**Comment by GunHog** [comment]
The change is done.

**Comment by KorPhaeron** [comment]
Cool, thanks

**Comment by Jalleo** [comment]
Yay clined people infected with that symptom will eventually be able to use cryo woo.

**Comment by GunHog** [comment]
How much radiation should it heal per pulse?

**Comment by ExcessiveUseOfCobblestone** [comment]
Fun fact, If you have brainloss + <typical healing disease symptoms> you are immune to negative side-effects of Meth, A Chemical which nearly removes stuns and is typically accompanied by Ephedrine which also lowers stuns.

Not saying this is a bad thing, just saying There's no downside to meth if you have this disease.

**Comment by GunHog** [comment]
I am probably not going to do anything else to this virus until I receive additional feedback or a maintainer wants me to change some code. Ready for review and all that good stuff.

**Comment by Razharas** [comment]
I say this is ok

**Pull request merged**
