### PR TITLE
Clowns no longer lose clumsy when they are antagonists.

### LINKED ISSUE #22117: Cultist clowns are no longer clumsy but randomly drop guns while firing
Cultist clowns are no longer clumsy but randomly drop guns while firing

### PR DESCRIPTION
**Pull request by ghost**
It now gives a warning that they are still clumsy.

closes #22117, technically

**WHY?**

I talked a lot about what this is about in the coding so i'll put some excerpts on some good points here

"When you select a job, or a trait, like clown, mime, pacifism, etc, you're accepting the consequences of the role. I'd much prefer a traitor story of a clown working around his clumsiness to kill a target and the fix for all of these are simple. For clowns, just revoke the clumsiness. If you get it as a normal antag then you gotta play smarter to not kill yourself like an idiot and conversion antags might be annoyed you can't help out as much but it's their choice on who they are converting."

"all this does is remove interesting scenarios from the game antags shouldnt be randomly exempt from it"

### I will be doing this for pacifism as well if this pr goes well, but pacifism can't be bundled into this pr.

Pacifism gives trait points and I need to tackle stuff like operatives having it or not, etc.

### CODE REVIEW

**Comment by MrDoomBringer** [comment]
finally this pr

**Comment by Armhulen** [comment]
I will be giving pacifists special uplink items like tranq darts, and syndicate body bags for kidnapping people. pacifists cannot get assassinate, but they can get "prevent from escaping alive"

**Comment by praisenarsie** [comment]
#22117 ?

**Comment by Armhulen** [comment]
@praisenarsie thank you

**Comment by optimumtact** [comment]
it's a no from me

**Comment by Armhulen** [comment]
why?

**Comment by ExcessiveUseOfCobblestone** [comment]
you can just go to genetics lol

**Comment by PKPenguin321** [comment]
The role of an antagonist plays a bigger part in a round than the role of a clown in that it's needed for a conflict to develop. Hindering their ability to do antagonistic things like this can potentially hurt the overall conflict of the round

>you can just go to genetics lol

"hey make me not clumsy please honk honk"
"sec traitor clown at genetics"

**Comment by Armhulen** [comment]
^^^^^^ if you /really/ can't handle it

**Comment by arsserpentarium** [comment]
Make clown_check() return true for detective.

**Comment by ExcessiveUseOfCobblestone** [comment]
Sounds like the role of an antagonist in action 🤔

**Comment by Armhulen** [comment]
@PKPenguin321 how is a clown not wanting to be clumsy a traitorous action holy moly

that aside, there are 3-6 traitors in the round. there can only be one clown roundstart.

**Comment by Armhulen** [comment]
alright, that should be all of them.

**Comment by PKPenguin321** [comment]
>how is a clown not wanting to be clumsy a traitorous action holy moly

it will be if this change goes through
welcome to our playerbase

**Comment by davethwave** [comment]
Good idea in my opinion

**Comment by iskyp** [comment]
@Armhulen for pacifist ops you could give them donksoft

**Comment by CosmicScientist** [comment]
\>pacifist
\>prevent X from escaping alive
\>OD or otherwise indirectly kill them on the shuttle
\>get your pacifist greentext
You're going to have to put some more thought into pacifism objectives than that.

I agree with PKP that going to genetics will label you as valid or a shitter who wants to valid.

I agree with this PR because it sounds fun.

I disagree because I'm not sure of the entire scope of clumsiness; what it does outside of oh dear I shot my foot.

**Comment by ExcessiveUseOfCobblestone** [comment]
The game is way too open-ended for pacifism to be enforced (no indirect killing!) entirely through code. Indirect killing, if it's to be handled at all, should be handled administratively. 

That said, the game is also so open-ended it's not exactly hard to bypass clumsiness to the point where you don't have to go to genetics to greentext. Heaven forbid you have to be a bit creative in your approach to antagonist objectives because you opted in for a particular job.

**Comment by Armhulen** [comment]
How about I don't do pacifism, and I do this

**Comment by Cyberboss** [comment]
The syndicate is not going to hire incompetent agents

**Comment by Armhulen** [comment]
@Cyberboss That's not a valid reason, The syndicate employ sleeper agents. The syndicate codes and allegiance is buried deep in their brain.

**Comment by davethwave** [comment]
Perhaps make it a preference on whether you want to keep the traits or not

**Comment by Cyberboss** [comment]
And when they awake, they remember how to stop being shit

**Comment by iskyp** [comment]
@Cyberboss you're implying syndicate agents even without genetic disabilities are competent
also yeah since when has syndicate hiring policy taken a higher priority than depth for game mechanics

@davethwave making it a toggleable options would be a terrible idea because every powergamer would just opt out if they get the role.

**Pull request closed without merging**
