### PR TITLE
Removes catpeople

### PR DESCRIPTION
**Pull request by Buggy123**
[Verse 1]
Harry Truman, Doris Day, Red China, Johnnie Ray
South Pacific, Walter Winchell, Joe DiMaggio
Joe McCarthy, Richard Nixon, Studebaker, Television
North Korea, South Korea, Marilyn Monroe
Rosenbergs, H-Bomb, Sugar Ray, Panmunjom
Brando, The King And I, and The Catcher In The Rye
Eisenhower, Vaccine, England's got a new queen
Marciano, Liberace, Santayana goodbye

[Chorus]
We didn't start the fire
It was always burning since the world's been turning
We didn't start the fire
No, we didn't light it, but we tried to fight it

[Verse 2]
Joseph Stalin, Malenkov, Nasser and Prokofiev
Rockefeller, Campanella, Communist Bloc
Roy Cohn, Juan Peron, Toscanini, Dacron
Dien Bien Phu Falls, "Rock Around the Clock"
Einstein, James Dean, Brooklyn's got a winning team
Davy Crockett, Peter Pan, Elvis Presley, Disneyland
Bardot, Budapest, Alabama, Khrushchev
Princess Grace, Peyton Place, Trouble in the Suez

[Chorus]
We didn't start the fire
It was always burning since the world's been turning
We didn't start the fire
No, we didn't light it, but we tried to fight it

[Verse 3]
Little Rock, Pasternak, Mickey Mantle, Kerouac
Sputnik, Zhou Enlai, Bridge On The River Kwai
Lebanon, Charles de Gaulle, California baseball
Starkweather Homicide, Children of Thalidomide
Buddy Holly, Ben-Hur, Space Monkey, Mafia
Hula Hoops, Castro, Edsel is a no-go
U-2, Syngman Rhee, payola and Kennedy
Chubby Checker, Psycho, Belgians in the Congo

[Chorus]
We didn't start the fire
It was always burning since the world's been turning
We didn't start the fire
No, we didn't light it, but we tried to fight it

[Verse 4]
Hemingway, Eichmann, Stranger in a Strange Land
Dylan, Berlin, Bay of Pigs invasion
Lawrence of Arabia, British Beatlemania
Ole Miss, John Glenn, Liston beats Patterson
Pope Paul, Malcolm X, British Politician sex
J.F.K. blown away, what else do I have to say?

[Chorus]
We didn't start the fire
It was always burning since the world's been turning
We didn't start the fire
No, we didn't light it, but we tried to fight it

[Verse 5]
Birth control, Ho Chi Minh, Richard Nixon back again
Moonshot, Woodstock, Watergate, punk rock
Begin, Reagan, Palestine, Terror on the airline
Ayatollah's in Iran, Russians in Afghanistan
Wheel of Fortune, Sally Ride, heavy metal suicide
Foreign debts, homeless Vets, AIDS, crack, Bernie Goetz
Hypodermics on the shores, China's under martial law
Rock and Roller cola wars, I can't take it anymore

[Chorus]
We didn't start the fire
It was always burning since the world's been turning
We didn't start the fire
But when we are gone
It will still burn on, and on, and on, and on...
We didn't start the fire
It was always burning since the world's been turning
We didn't start the fire
No, we didn't light it, but we tried to fight it
We didn't start the fire
It was always burning since the world's been turning
We didn't start the fire
No, we didn't light it, but we tried to fight it
We didn't start the fire
It was always burning since the world's been turning
We didn't start the fire
No, we didn't light it, but we tried to fight it
We didn't start the fire
It was always burning since the world's been turning

### CODE REVIEW

**Comment by optimumtact** [comment]
why don't you leave the jokes to me

**Comment by Buggy123** [comment]
fuck

**Comment by Buggy123** [comment]
seriously though this took like 20 minutes on the webeditor fuck

**Comment by optimumtact** [comment]
well on the bright side now you have the branch for future reuse

**Comment by Buggy123** [comment]
fair enough

**Comment by praisenarsie** [comment]
doesn't even compile

**Pull request closed without merging**
