### PR TITLE
Gives walls some perspective.

### PR DESCRIPTION
**Pull request by nemvar**
## About The Pull Request

Walls are no longers perspectiveless globs.

## Why It's Good For The Game

soullesstwo
soullessthree
soulessfour

## Changelog
:cl:
imageadd: Slightly altered wall sprites.
/:cl:

### CODE REVIEW

**Comment by carlarctg** [comment]
feels too subtle a change to be honest, i can barely tell as it is and most people will probably take days or hours to notice this.

maybe make the perspective part bigger?

**Comment by Rowelll** [comment]
i don't see that much of a difference, but i like it anyways

**Comment by nemvar** [comment]
shut up travis

**Comment by MMMiracles** [comment]
@carlarctg a subtle change is probably gonna go over a lot better than a drastic one and this still lets most wall-mounted objects make sense without additional changes.

**Comment by nicbn** [comment]
I'd rather we to go the full 3/4 path, maybe port bay sprites

**Comment by Tlaltecuhtli** [comment]
yeah port them from hippie

**Comment by nemvar** [comment]
I like these, they are subtle and make rooms just look at bit more... roomy.

**Comment by GuyonBroadway** [comment]
At this point just start stealing from the goonleak, ya already got the toolboxes.

**Comment by nemvar** [comment]
What do you mean? I don't play goon and literally just moved the south of the walls two pixels higher. You can't really patent perspective.

**Comment by nicbn** [comment]
Yeah goon walls are really better than this but I still think bay walls are the best
But people around here are mostly "changes r bad" when it comes to this so eh

**Comment by bigfatbananacyclops** [comment]
i was going to resprite walla but i had no idea how this sprite divisions worked in icons

**Comment by brandonvdongen** [comment]
I like it. it modernizes the look just a little bit but doesn't change the visual appearance drastically like most servers.

**Pull request merged**
