### PR TITLE
changes shadow shackles sprite (action button)

### PR DESCRIPTION
**Pull request by improvedname**
New sprite
image

vs

old sprite
image

reason of change:THE OLD DOESNT LOOK LIKE SHACKLES REEE DESPITE THEM CALLED SHADOW SHACKLES!!! THIS IS A SHACKLEES

image

:cl: Improvedname
imageadd: adds a new icon for shadow shackles (ripoff clockwork menacles)
imagedel: deletes old shadow shackles (zipties)
/:cl:

### CODE REVIEW

**Comment by Tlaltecuhtli** [comment]
-1 gbp lol

**Comment by WJohn** [comment]
Good heavens those look terrible. Fix yo shading, and also the girthyness of those shackles.

**Comment by FuryMcFlurry** [comment]
why not use this one 
image

**Comment by WJohn** [comment]
Yeah use those and make em black and shiny. Boom, done.

**Comment by improvedname** [comment]
aye i do it tommorow

**Pull request closed without merging**
