### PR TITLE
borg research module (split up of 40337)

### PR DESCRIPTION
**Pull request by Tlaltecuhtli**
:cl:
add: borg research module
/:cl:

### CODE REVIEW

**Comment by ExcessiveUseOfCobblestone** [comment]
Not a fan, the points should be incorporated into the job which borgs can utilize (IE a medical borg doing experimental surgery).

**Comment by Supermichael777** [comment]
Prepare to get lynched by every engi for gimping the already terrible battery life of their ~robot buddy~ self-propelled RCD.

**Comment by Tlaltecuhtli** [comment]
more reasons to upgrade borg cells and rechargers

**Comment by ExcessiveUseOfCobblestone** [comment]
Yet another reason why tiered parts are cancer

**Comment by optimumtact** [comment]
this is lame, I might put a global moratorium on anyone making ways to get techweb points without consulting us first

**Comment by ExcessiveUseOfCobblestone** [comment]
At least for passive-generation of any sort, I don't think we need ultimatums of all techweb point gens.

**Pull request closed without merging**
