### PR TITLE
Shooz

### PR DESCRIPTION
**Pull request by actioninja**
:cl: Arachnidnexus/actioninja
imageadd: New shoe object sprites
/:cl:

image

### CODE REVIEW

**Comment by MrPerson** [comment]
Sprite changes like this are a step in the right direction. Most people are going to form a lasting impression solely based on how the game looks, so we should put our best foot forward. I know it's a lot of work to redo and stomp out the bad sprites, so thank you for putting your foot down. These sprites are a shoe-in to be accepted.

**Comment by yoyobatty** [comment]
Looks like old rs sprites

**Comment by kingoftheautism** [comment]
They actually look nice, I especially like magboots. I will miss old sprites tho, but again, those are nice too

**Comment by actioninja** [comment]
I know what you mean, they don't quite perfectly fit into the general artstyle of newer sprites. They're close enough and miles better than the old ones that I still thought it was worth rolling them into a PR though.

**Comment by PKPenguin321** [comment]
I kind of dislike how shiny they all look. Might be getting my terminology mixed up here but this looks vaguely pillow shading-y with how they seem to all shine at the toes
Other than that they're pretty ok

**Comment by GuyonBroadway** [comment]
@MrPerson

**TEN THOUSAND YEARS PUN JAIL!**

**Comment by nicbn** [comment]
hey don't forget about the proto clown shoes

**Comment by xxalpha** [comment]
Are you not doing the rest?

**Comment by actioninja** [comment]
This ain't isometric at all get out of here

**Comment by MrDoomBringer** [comment]
@actioninja i made a coloring book 2 help ur smooth brain understand this concept
image

**Comment by MrDoomBringer** [comment]
@actioninja mayb this coloring book will help ur glossy brain understand this concept
image

**Comment by ExcessiveUseOfCobblestone** [comment]
soul

soulless

**Comment by pubby** [comment]
I like the sandals, the detective shoes, the crusader shoes, and the cultalt shoes a lot.

The rest I'm not so convinced on. I think you can do better with both the shape and the shading.

Here's my own attempt at isometric shoes:

image

I think these look a bit off too, but they show a good amount of detail.

**Comment by nicbn** [comment]
We should make the items isometric and the other things 3/4 for maximum Space Experience(tm)

**Comment by actioninja** [comment]
@MrDoomBringer isometric doesn't mean "3 sides visible" you spastic.

**Review by Cyberboss — APPROVED** [review]

**Comment by k-k-karma** [comment]
You haven't converted all shoes from a quick glance which will lead to shit being misaligned

**Comment by actioninja** [comment]
@k-k-karma it's already merged but I think you're a hippie guy.
Except for the prototype clown shoes, all the unupdated sprites are either items that are admin only or sprites that are completely unusued and don't have any code references.

**Pull request merged**
