### PR TITLE
Birdshot Cargo Changes

### PR DESCRIPTION
**Pull request by GremlinSeeker**
## About The Pull Request

Some QoL changes for cargo, mostly just with the goal of cutting down on the sheer amount of airlocks in cargo. I also added a small cargo lobby to aid in pushing the ORM a tad closer to the miners and cutting down on the airlocks in and out of cargo. 
## Why It's Good For The Game

Less claustrophobic, more space. The changes are very minor, just small changes to the layout without completely overhauling it. 

You can see the changes below.
image

re-added dnd room:
image

new cargo lobby area:
image

the freed up space: 

image

## Changelog
:cl:
add: Birdshot Cargo now has a lobby and is slightly more open overall.
add: Re-added the DnD room  to Birdshot
add: re-added the skill station to the library.

/:cl:

### CODE REVIEW

**Comment by GremlinSeeker** [comment]
Something I had done awhile ago but it was stuck in limbo due to the wallening

**Comment by DaydreamIQ** [comment]
Think you could give them more reinforced windows? Its kind of weird that the QM office especially is so easy to tide into

**Comment by MrMelbert** [comment]
> Think you could give them more reinforced windows? Its kind of weird that the QM office especially is so easy to tide into

we are supposed to be de-creeping r-window usage, that's why the CMO's office on Meta uses normal windows

**Comment by MrMelbert** [comment]
not a gigantic fan of maintenance now being split in two entirely, makes it a bit harder for antagonists to get around that idea

**Comment by GremlinSeeker** [comment]
> not a gigantic fan of maintenance now being split in two entirely, makes it a bit harder for antagonists to get around that idea

I could maybe connect maintenance through to the small corridor between the cargo lobby and aux tool storage, and add another maintenance door in the lobby to connect through to the southern maintenance.

**Pull request merged**
