### PR TITLE
CQC PR AGAIN and does what orangus wanted.

### PR DESCRIPTION
**Pull request by Militaires**
:cl: Basilman
add: A third martial art, CQC, has been added and is now available to nuke ops instead of sleeping carp
/:cl:

>if you do consider remaking this pr, simply replace the one the nukeops have.
@optimumtact 

are you happy now rampant fruit

[s]  added leg sweeps by resting and then harming someone, so that you can flank someone by pretending to be crit or ded henk, not putting it in the recall teachings cause im a memer like that

**new:   CUSTOM CQC SOUNDS**
_~~which i shamelessly stole from the phantom pain~~_

### CODE REVIEW

**Comment by optimumtact** [comment]
yes

**Comment by Militaires** [comment]
@Iamgoofball that's actually how it's written for the recall verb and i wanted to keep it for that, but it'd work there too i guess, good find.


snake





also fucking conflicts

**Comment by KorPhaeron** [comment]
@Cheridan 

People keep trying to add stun gloves help

**Comment by Iamgoofball** [comment]
@KorPhaeron 
RULES OF GREYTIDE

**Comment by Militaires** [comment]
@KorPhaeron 
already exist it's called krav memega and cybernetic stun implant

**Comment by Militaires** [comment]
i fucking hate you conflicts

**Comment by PKPenguin321** [comment]
it's oranges

**Comment by Militaires** [comment]
@PKPenguin321 there i voted for you stop bullying me

**Comment by PKPenguin321** [comment]
thanks

**Pull request merged**
