### PR TITLE
Adds the advanced mech clamp

### PR DESCRIPTION
**Pull request by Fikou**
## About The Pull Request

adds the advanced mech clamp from advanced exosuit tools  techweb, its like a normal clamp but has a lil bit more power and can open powered doors

## Why It's Good For The Game

the exosuit clamp's brother, the drill has an upgrade, this lets people with access to advanced exosuit stuff open doors without fully destroying them, which is nice compared to griff with mech punches

## Changelog
:cl:
add: The advanced exosuit clamp is here!
/:cl:

### CODE REVIEW

**Comment by adamkad1** [comment]
why not unpowered doors tho, its a oversized crowbar no?

**Comment by Fikou** [comment]
> why not unpowered doors tho, its a oversized crowbar no?

because the normal mech clamp can open unpowered doors

**Comment by adamkad1** [comment]
oh, i never tried

**Comment by Tlaltecuhtli** [comment]
make it able to open bolted doors too

**Comment by knacker48** [comment]
So Its basically a big jaws of life?

**Comment by optimumtact** [comment]
mech power creep

**Comment by dr-bee** [comment]
> 
> 
> mech power creep

Not really, as usually a mech with a clamp will have a drill anyway, or be able to punch the door down anyway. All this does it make it possible to open the door without destroying it.

**Comment by zxaber** [comment]
You should stick it on the same tech node as the mech RCD. Otherwise, good change.

**Comment by optimumtact** [comment]
>All this does it make it possible to open the door without destroying it.

SO IT'S LITERALLY POWER CREEP U GOOFY ASS

**Comment by Fikou** [comment]
> You should stick it on the same tech node as the mech RCD. Otherwise, good change.

good idea, i forgot about that node

**Comment by Fikou** [comment]
> also how long does it take to get that tech normally?

the whole path costs 10000 points, but it isnt usually researched before like 30 minutes from what ive seen

**Comment by FloranOtten** [comment]
Mech parts are never researched before both mining and parts, effectively adding those points to the cost as well.

**Comment by wesoda25** [comment]
Weeeeeeeeee mechs can ignore literally all structures and now do so better

**Comment by bigfatbananacyclops** [comment]
this is more like improved than advanced

**Comment by Fikou** [comment]
> this is more like improved than advanced

do i need to stick a bottle opener on it to make it advanced

**Comment by Tlaltecuhtli** [comment]
make it open windoors

**Comment by AcapitalA** [comment]
By the time you get to the advanced clamp most people will have combat mechs anyhow which can also destroy almost any structure if they want. You can also hack doors which takes like 3 seconds or less if you know the wires.

**Comment by SpaceManiac** [comment]
Not really convinced this is fatal power creep, but it does seem unnecessary. Nobody else seems interested in merging it either.

**Pull request closed without merging**
