### PR TITLE
Changes radiation storm random event into a weather type.

### PR DESCRIPTION
**Pull request by Shadowlight213**
WIP needs new sprites/sounds for the storm. Currently using lavaland ash as placeholder.

:cl:
tweak: The radiation storm random event will automatically enable and disable emergency maint.
add: The radiation storm random event is now a weather type that affects the station.
/:cl:

### CODE REVIEW

**Comment by YakumoChen** [comment]
ooh, so just like on /vg/?

**Comment by Bawhoppen** [comment]
:-1: For auto-enabling maint access
:+1: for other stuff

**Comment by Shadowlight213** [comment]
@Bawhoppen this new system will MASSIVELY fuck you over if you get trapped in the main halls. Its literally like standing in an ash storm bit instead of burn damage it irradiates you and mutates you. Maint access is kinda needed if you don't have an AI.

@yakumoChen I'm not sure exactly how vg does theirs. Do they just have the visual effect? Or is there actually a rads over time thing?

**Comment by Bawhoppen** [comment]
Seems hugbox

It's kind of a sideways step, interesting situations can come from people being trapped out of maint as it is now, but this will make there be interesting scenarios I guess too :confounded:

**Comment by GunHog** [comment]
I kind of agree with Baw here. Besides, most department jobs have access to their own maint, whereas the greys have access to general maint. If you are not in your department, you will have to slip in with someone else!

**Comment by PKPenguin321** [comment]
wait so rad storms super kill you now? that sucks because now i wont be able to get superpowers

**Comment by kilkun** [comment]
why would radiation leak inside of the station in the first place?

just have it fry people in non-antag space suits who are out in space.

**Comment by optimumtact** [comment]
It's for gameplay purposes, not RP purposes.

**Comment by kilkun** [comment]
you can tell how little you actually even join either of the servers because you'd realize how stupid arguing anything to do with this meme event is "gameplay"

**Comment by optimumtact** [comment]
arguing about how the game event works currently when the PR is changing it's meta doesn't make any sense.

**Comment by kilkun** [comment]
i came from /vg/

this doesn't change how the event plays out at all. it's a completely stale and artificial change, completely superficial in all sense of the word. changing the meta from "do nothing" to "apply anti-mutation and anti-tox patches"/run into maint is disingenuous to imply it is anything but a negligible change.

of course you'd know this if you ever played the game...

**Comment by Shadowlight213** [comment]
>if you don't agree with my opinion on something you obviously don't ever play the game.

Nice meme. Coders never play is a stale joke.
I looked at vg's radstorm code. Instead of 1 pulse they have 15. Not nearly exactly the same as a weather effect. Hell their rads are capped at 25 per pulse and don't even have any variation to their event timing. You could probably run around between pulses if you learned the timing.

**Comment by optimumtact** [comment]
Who cares what vg has, their medical is completely different to ours.

**Comment by optimumtact** [comment]
Finish please

**Comment by Bawhoppen** [comment]
radiation should be frying everyone already for the sake of just being in space

**Comment by Shadowlight213** [comment]
@optimumtact I'm waiting for @WJohn to hopefully get some sort of overlay for the effect. although I guess I could try having it not have any visual effect.

**Comment by kilkun** [comment]
@Shadowlight213 
> if you don't agree with my opinion on something you obviously don't ever play the game.

>Nice meme. Coders never play is a stale joke.

this is completely baseless, I only call out coders who never play the game as never playing the game. you can't just call something a meme and act like that makes your point true. oranges never fucking plays. half the maintainers hardly ever log into either of the servers, and when they do they observe.

No, testing your code on a localized server isn't fucking playing the game. Neither is observing.

@optimumtact 
when it comes to healing general damage it really fucking isn't.

>b-but the chemicals are different! p-patches AND pills!

that's barely a fucking difference. if this had to do with surgery the medical systems being different is a valid point. our hypercasual medical system makes radiation storms even more irrelevant.

@Shadowlight213 
just color the turfs in affected zones green for the duration of the storm

**Comment by optimumtact** [comment]
You would be more accurate to say that I have not played recently because I have indeed played the game.

**Comment by Shadowlight213** [comment]
Alright I've commented out the overlays and sounds, to be implemented when I can get sprites for them.
To compensate, I added a message for the start of the storm itself, and added an announcement for the end.
I guess it's ready now.

**Comment by kilkun** [comment]
Coding doesn't give you a grasp on game balance.

See: Pretty much every PR that adds something made by someone who doesn't play the game and doesn't have anything to do with the inner workings of the game.

Playing the game frequently and understanding how the features mesh together is the difference between Kor's features and Goofball's features.

**Comment by Bawhoppen** [comment]
kilkun are you actually mentally deficient

**Comment by optimumtact** [comment]
If you continue to comment on matters without becoming a coder I'm afraid we'll have to ban you from the github.

Please learn how to balance things before commenting again.

**Comment by kilkun** [comment]
I've made plenty of PRs that have gotten shot down for various reasons, and am in fact in the middle of rebalancing a deprecated feature that's just as likely to get shot down. And when it does for the reasons I'm predicting, I'll have all the hard evidence in the world that shows just how out of touch the majority of coderbus actually is.

Futhermore, don't get salty because I called you out on your lack of knowledge on what's relevant to the current way the game plays. Own up to it and if it bothers you enough to threaten abusing the powers trusted in you, it's very easy to fix by simply playing the game.

**Comment by Bawhoppen** [comment]
okay mr. kilkun, we're all eagerly awaiting your PR

**Comment by optimumtact** [comment]
Look I'm afraid that for your actions and words towards me we have no choice but to github ban you. I will make the arrangements now. Please feel free to appeal on the forums when you have grown up.

**Pull request merged**
