### PR TITLE
Removes night vision quirk

### PR DESCRIPTION
**Pull request by improvedname**
## About The Pull Request
This pr removes the quirk night vision from being selectable

## Why It's Good For The Game
Since the night vision rework this gives instead of the 3 tiles around you full soft vision in the darkness
Heres 2 screenshots to compare the difference.

This is what people without night vision see.
image

This is what people with night vision see.
image

Night vision does not define a character and is 100% client side.
this also turns antags like nightmares that hide in the shadows less scary and just make the envoirement boring when it comes to combat darkness vs light has 0 adventages because majority of the people run night vision antags who break lights to rely on this adventage just end up wasting time because everyone has inbuilt night vision

## Changelog

:cl:
del: Removes night vision quirk
/:cl:

### CODE REVIEW

**Comment by Jacquerel** [comment]
I've never much liked Night Vision because "good at seeing in the dark" says nothing about the character who has it selected.

**Comment by Fikou** [comment]
> I've never much liked Night Vision because "good at seeing in the dark" says nothing about the character who has it selected.

it says that they are a power gamer

**Comment by cnleth** [comment]
I don't use this quirk but I don't like the fact that you're just straight up removing it instead of trying to improve it. Also I can't see any difference in your screenshots but maybe my vision is just bad

**Comment by improvedname** [comment]
> I don't use this quirk but I don't like the fact that you're just straight up removing it instead of trying to improve it. Also I can't see any difference in your screenshots but maybe my vision is just bad

if you don't see a difference then the quirk does nothing in your eyes (so useless and pointless) and it doesn't need improvement because its just a bad concept



> I've never much liked Night Vision because "good at seeing in the dark" says nothing about the character who has it selected.

exactly if you check the people who take this trait stat wise it will come out in top

**Comment by improvedname** [comment]
heres the stats for the most quirks taken
image

And let me tell you these quirks aren't taken for their "character definition" let me explain what these in combination do.

Light drinker is a -2 quirk that makes alcohol affect you more in the long run its nothing special but minor character definition
Hypersensitive is a -2 quirk that makes moods effect you twice more then the usual
Family heirloom is a -2 quirk that gives you a item if you lose it you get a mood debuff if you have it on person you get a mood

Night vision is a 4 point quirk that gives you 3 tile night vision but due night vision code being reworked it gives you night vision of the whole area instead

**Comment by cnleth** [comment]
Ok, so apparently this quirk looks different on different screens and it's basically unsalvageable because of how it works, so I changed my mind

**Comment by improvedname** [comment]
Also this is the difference if you take gamma in consideration
With NV
image

Without NV
image

this is max gamma so it looks very ugly but i think it gets the point across

**Comment by Jacquerel** [comment]
The way darkness works is heavily variable based on your screen settings and even where you are sitting relative to your screen.  
Unfortunately this is largely speaking just how colour works and there isn't much to be done about it.

**Comment by MercuryArrow** [comment]
This quirk has always been fairly divisive - some people consider it a powergame perk while others barely notice the difference and point to the ease of getting other forms of nightvision within minutes of roundstart anyway.
Either camp, I don't really see anyone who's a particular fan of it from an objective perspective.

**Comment by improvedname** [comment]
> This quirk has always been fairly divisive - some people consider it a powergame perk while others barely notice the difference and point to the ease of getting other forms of nightvision within minutes of roundstart anyway. Either camp, I don't really see anyone who's a particular fan of it from an objective perspective.

Mesons which are also the same viction of the NV rework suffer the same issue as night vision quirk, unlike the quirk mesons carry other disadventages like getting blinded from emps or flashes being enchanced in general

Oculine is on the nerf bed aswell since 90 units lasts you trough the whole round so metabolism should just be increased so it wouldn't do that exact thing

**Comment by Time-Green** [comment]
I kept being so confused by people perfectly seeing and tracking me in darkness, I had no idea it worked like this

**Comment by SomeoneYouProbablyKnow** [comment]
> This is just a bad quirk design wise and its better if it just was removed
> 1 everyone should have it
> 2 nobody should have it

Yea fuck it but the real problem is one step below that
1. All powergamers have it
2. non powergamers don't bother and are at a disadvantage from the get-go

Actually useful positive quriks will always end up like this as long as tou can mix and match upsides and downsides. Any system like that is an invitation to abuse it.

> I don't use this quirk but I don't like the fact that you're just straight up removing it instead of trying to improve it. 

There was actually a PR that tried to rework it (it and the other common quirks) so safe to say it was attempted.
You can always make a counter PR before this is merged, that's usually the best way to go about this. But NV really does belong in the bin.

> more seriously, consider wrapping it into photophobia as a small upside for an almost untouched negative quirk

Although this is fun

> What if instead of fully removing it we replaced it with 'night acclimatization' where the longer ur in the dark the better u can see

And this is cool but much bigger in scope than just night vision. It is a good idea though on its own merits.

**Review by optimumtact — APPROVED** [review]

**Comment by uaioy** [comment]
tiders are still gonna take mesons to see in the dark lol

**Comment by improvedname** [comment]
> tiders are still gonna take mesons to see in the dark lol

thats fine because i can use my cult emp to blind every tider nearby

**Comment by CCC23** [comment]
> > tiders are still gonna take mesons to see in the dark lol
> 
> thats fine because i can use my cult emp to blind every tider nearby

melsons dont get affected by emps but ok

**Comment by MrMelbert** [comment]
I wish this pr added something to replace the void it is introducing

**Comment by Jacquerel** [comment]
> tiders are still gonna take mesons to see in the dark lol

I prefer that to them just being born different
Stealing stuff requires you to break in somewhere and might get you in trouble

**Comment by BlueMemesauce** [comment]
If anyone want to readd it, I suggest to make it like my blackstone pr where it uses the see_in_dark thing https://github.com/Blackstone-SS13/BLACKSTONE/pull/135/files
so basically instead of brighting the screen, you just make it like a bigger radius that you can see in the dark

image
image

**Comment by LemonInTheDark** [comment]
> If anyone ever wants to try to readd it, I suggest to make it like my blackstone pr where it uses the see_in_dark thing https://github.com/Blackstone-SS13/BLACKSTONE/pull/135/files so basically instead of brighting the screen, you just make it like a bigger radius that you can see in the dark
> 
> only problem is it looks shit

this is how things used to work, I removed see_in_dark as a factor in #73094
solution here IMO is to make eyes adapt to darkness, so you can see ok in the dark but any light spaces will blow you tf out

**Pull request merged**
