### PR TITLE
[s] Adds the Triple-Bladed Energy Sword

### PR DESCRIPTION
**Pull request by PKPenguin321**
trisword

**Stats:**
- Can be purchased in the traitor uplink
- Requires 2 hands
- Deals a whopping 45 damage per hit
- Has 100% block chance for ALL projectiles
- Has a 80% block chance for any melee attacks
- Can be rapidly spun, causing it to shoot electricity that stuns (on a cooldown)

:cl: PKPenguin321
rscadd: The devious triple-bladed energy sword can now be purchased from the uplink.
/:cl:

### CODE REVIEW

**Comment by Shadowlight213** [comment]
Kek

**Comment by Cheridan** [comment]
we need to go deeper

**Comment by Incoming5643** [comment]
I always thought the triple sword would immediately penetrate you if you turned it on

**Comment by Zilenan91** [comment]
>cost = 2

**Comment by Jazaen** [comment]
Make it look like a sword that a certain Darth Vader-imitator has and we will be good.

**Comment by CPTANT** [comment]
Wouldn't this actually be pretty lethal if thrown around with telekinesis?

**Comment by Saegrimr** [comment]
Triple sword is shit, only pros use the quad-sword.

**Comment by MMMiracles** [comment]
this is a beautiful thing

**Comment by Aloraydrel** [comment]
Sheev would be proud

**Comment by Jazaen** [comment]
*Cringe inside*
Also, I think you can still use it with nodrops.

Does it have multiple colours? Is the brute damage dealt directly, or does it pass resistances? Does it have any real uses? Is this just a troll item? Who IS John Galt anyway?

**Comment by PKPenguin321** [comment]
>Does it have multiple colours? Is the brute damage dealt directly, or does it pass resistances? Does it have any real uses? Is this just a troll item? Who IS John Galt anyway?

No, passes resistances, no, yes, it's a mystery.

**Comment by Jazaen** [comment]
Well, you CAN "accidentally" drop that during a maint chase, and hope it gets a powergamer. It would possibly be useful in disposals death spirals, if only it functioned as advertised.

**Comment by PKPenguin321** [comment]
>April-fools-branch

**Comment by KazeEspada** [comment]
Binding this to your summon item, getting some cuck to turn it on, and then summoning it to your hand so you can FINALLY kill someone with it(besides the cuck on the ground).

**Comment by Jazaen** [comment]
This just came in from Bagil, someone actually impaled themselves on it as tator.

**Comment by PKPenguin321** [comment]
Should I add this to the real game y/n

**Comment by Incoming5643** [comment]
Not as an uplink item, but as a thing you can make from a double sword sure.

Just be nice and give them a way to take it apart, getting three eswords isn't exactly easy

**Pull request merged**
