### PR TITLE
Eatting fried items actually consumes the item

### LINKED ISSUE #38025: Fried monkey hides spontaneously become un-fried when eaten
[Round ID]: # 88400

[Testmerges]: # #37867: 'Adds an admin punishment: Spewapalooza' by Armhulen at commit b13873b73e 

[Reproduction]: # Obtain a monkey hide, fry the monkey hide (the ones I ate were lightly-fried but it probably works with any level of fried), eat the monkey hide. The monkey hide will drop at your feet, un-fried, after the first bite. You can fry this hide and repeat this infinitely.

### PR DESCRIPTION
**Pull request by ShizCalev**
Closes #38050
Closes #38049
Fixes #38025

🆑 ShizCalev
fix: -All- fried items are now edible. Yum!
/🆑

### CODE REVIEW

**Comment by AlexTheSysop42** [comment]
:-1:, this makes it somewhat easy to accidentally (or not) delete important things

**Comment by ShizCalev** [comment]
Gotta be careful in kitchens. Don't wanna drop your cellphone in the fryer now. ¯\_(ツ)_/¯

**Comment by ma44** [comment]
There should probably be a thing where you can't deep fry INDESTRUCTIBLE items such as the unique objective items (CMO hypospray, HoS laser gun etc.)

**Comment by PKPenguin321** [comment]
this is going to get fryers removed if it goes through

**Comment by Shadowflame909** [comment]
You can get rid of those items either way though. Just cremate them? Deep Fryer's just an alternative crematorium. That goes through your mouth, and is objects that can fit into your hand only! I mean, crematoriums haven't been removed yet.

**Comment by Tlaltecuhtli** [comment]
does this cause the nuke disk to be duped?

**Comment by Kromgar** [comment]
@Tlaltecuhtli A new nuke disk would spawn once it is consumed

**Comment by Iamgoofball** [comment]
@PKPenguin321 no it isnt lmao stop fearmongering over people deep frying shit, I could put them in space or a toilet cistern and they'd be impossible to trace too

**Comment by PKPenguin321** [comment]
somebody's gonna get stripped and have their stuff placed in the deep frier for 0.1 second destroying it instantly at roundstart and they will PR a removal

**Comment by Iamgoofball** [comment]
you know, that sounds like a player problem you **admins** should deal with

**Comment by ShizCalev** [comment]
Nuke disk A) respawn when destroyed, and B) Has the indestructible flag, so you couldn't put it in the fryer anyway.

**Comment by ShizCalev** [comment]
@PKPenguin321 That sounds like a pretty straightforward rule 1 violation if they're not an antag. Though if you really wanted, you could introduce a minimum frying time for the item before it's transferred to a holder.

**Comment by Therapist1** [comment]
This still is a bad fix for an issue that’s not a problem in the first place. Let me just fry the chaplains null rod, the entire armory, someone’s ID, or maybe be an antag objective. Point is, very abusable and bound to fuck shit up

**Comment by Iamgoofball** [comment]
@Therapist1 Let me just space/fry/toilet cistern the chaplains null rod, the entire armory, someone’s ID, or maybe be an antag objective. Point is, very abusable and bound to fuck shit up

**Comment by Iamgoofball** [comment]
>you could introduce a minimum frying time for the item before it's transferred to a holder.

This is a thing, last I checked.

**Comment by ShizCalev** [comment]
@Iamgoofball nope, everything's currently fried instantly since it's handled in attackby. The only thing that's adjusted over time is the amount of oil added to the holder.

**Comment by Mickyan** [comment]
This seems like one of those things where the fix is worse than the problem

All of this just because you can fry an item twice instead of having to grab a paper bin or just one of the thousands of useless items scattered around the station?

Besides I'm not sure what this is even supposed to fix, cooking oil isn't infinite and there's already dozens of much more efficient ways to get infinite nutrition/mood boosts outside of the kitchen

**Comment by ShizCalev** [comment]
There are two deepfryers at roundstart, both start with 25u of cooking oil, and use 0.0405u per tick when unupgraded. That works out to just a hair away from 1u of oil used per minute, meaning a single fryer would run dry after ~25 minutes of non-stop frying. 

If you do manage to drain them both after 25 solid minutes of cooking, every kitchen has a tank that contains 1000u of oil. So in actuality, oil is essentially infinite.

**Comment by Mickyan** [comment]
So is the sugar in the bar dispenser next room, actually literally infinite and more efficient nutriment than cooking oil. In fact, if you're just after nutriment you can just drink cooking oil from the vat and it'll have the same nutrition value as frying non-edible items. 
My point is even by ignoring the entire kitchen, supply of nutriment will never be an issue as the station has enough to last pretty much forever so singling out cooking oil for being an issue is futile

You could nerf cooking oil but the reality of the situation is food and nutrition is unbalanced spaghetti code (pun not intended) and I don't think giving the chef the ability to delete items solves anything other than giving him an extra way to screw people over

**Comment by moonheart08** [comment]
I'd support this is it only made this happen on *food*
Also i don't think you can eat the null rod, i thought it was indestructible 🤔

**Comment by davethwave** [comment]
I doubt eating metal/glass is healthy for you or/and your teeth is strong enough to bite and chew metal, whats the logic for this PR?

**Comment by moonheart08** [comment]
@davethwave i mean, you *can* bite and chew some metals. Why not chew this mercury, it's good for you. 😄

**Comment by davethwave** [comment]
*deep fry's a power cell* It would be such a waste if I don't eat the lithium wouldn't it? I can think of perhaps a new goal for graytide everywhere. Eat everything on the station. Break in different departments and deconstruct the station down piece by piece until only the gravity generator, the eater(with only one hand left since he ate the rest of them), and the deep fryer remain. Didn't include the SM since either it would have blown up from the lack of equipment keeping it cool(eaten) or if the eater is lucky, has the steal a sliver of the SM mission and deep fry's the SM sliver by sliver eating it.

**Comment by SgtxRootbeer** [comment]
Fixes a non-issue and creates a whole host of new issues. Bad Shiz, bad!

**Comment by AlexTheSysop42** [comment]
>fry disk
>give to cap
>ops kill cap and get disk
>someone onstation still has a pointer
>ops eat the disk
>"Disk? What disk?"
>ops stare at each other in confusion
>crewmember finds disk 
>crew major victory

**Comment by ShizCalev** [comment]
@AlexTheSysop42 
image

**Comment by Kurgis** [comment]
I think a better fix would to have fried non-edible items give you negative mood, since the main concern you point out is infinite positive mood from re-frying the same item repeatedly. Though I don't understand why this is generating such a deal of salt, people keep referencing putting the Nuke Disk into the fryer as the PR's failing, something which has been impossible for quite awhile.

**Comment by ShizCalev** [comment]
@Kurgis that's actually incorrect, you -can- currently deepfry the nuclear disk, this PR prevents that though.

**Comment by Iamgoofball** [comment]
Mood is disabled on Basil atm, so it effectively doesn't exist anymore. Don't worry about mood.

**Comment by yorii** [comment]
Will eating a deep fried reagent container also release the contained reagents into the mob?

**Comment by Mickyan** [comment]
If mood isn't a factor then there's literally no reason for this change as there's no benefit from eating the same fried object multiple times

**Comment by Therapist1** [comment]
You can’t deepfry containers,  yorii, you just scoop out cooking oil with them or dump whatever is inside into the fryer

**Comment by yorii** [comment]
@Therapist1 oh I see, so the comment earlier about eating the hypospray doesn't actually work then?

**Comment by KorPhaeron** [comment]
You can get rid of items very easily by walking to any of the several public airlocks that lead into space and just throwing the item 

Or feeding them to the crematorium

Or the RD analyzer

Or throwing them in lava or setting them on fire or pouring acid on them or using disposals that lead to sapce and so on forever if someone starts deleting every item its an admin issue

**Comment by SgtxRootbeer** [comment]
>does nothing except negatively effect balance and make life harder for everyone whilst not stopping the original issue (deck of cards, hmmm?)
>people complain endlessly
>image
>@KorPhaeron still merges it.

**Comment by Iamgoofball** [comment]
>not reading anything kor said

try again bby

**Comment by Iamgoofball** [comment]
have you considered admitting you just care about the reelism meme and stop lying about balance being your reason?

**Comment by SgtxRootbeer** [comment]
i care about the fact that this removes functionality, for a non-issue. I care about the fact that most of the people viewing this have decided its a poor addition, yet it was ham-fisted because kor wanted it.
besides, the alternative methods that kor mentioned are either behind access, or recoverable.

airlocks/disposal spacing is recoverable with effort
rnd, crematorium, acid, sm shard, etc are all behind access that is secured with more than a table and a shutter. rnd, for example has a windoor blocking it.

most kitchens for example, however, only have a table between your assistant who stole the blueprints/mag-boots/hos gun/[other critical item which cannnot be replaced] and the deep-fryer which now has the capability of destroying any item that fits into it.

**Comment by SgtxRootbeer** [comment]
also, did i mention how this removes functionality for a non-issue?

**Comment by Iamgoofball** [comment]
>also, did i mention how this removes functionality for a non-issue?

>>>>removes functionality

can someone gitban this person yet

**Comment by Iamgoofball** [comment]
>rnd, crematorium, acid, sm shard, etc are all behind access that is secured with more than a table and a shutter. rnd, for example has a windoor blocking it.

how 2 get into R&D:
screwdriver-crowbar-screwdriver-wirecutters
OR
"AI law 2"
how 2 get into crematorium:
welding tool->thingy to unsecure/deconstruct girder
OR
"AI law 2"
how 2 get acid:
screwdriver-crowbar-screwdriver-wirecutters
OR
"AI law 2"

**Comment by PKPenguin321** [comment]
how 2 get into kitchen
climb table

**Comment by Iamgoofball** [comment]
mhm

all of these are equally easy to access

**Comment by cacogen** [comment]
it wouldn't completely solve the issue but you could transfer the item to the mob's contents and have it reappear if they're gibbed

**Comment by PKPenguin321** [comment]
no not equal

**Comment by KorPhaeron** [comment]
how 2 get to escape airlocks

walk

**Comment by SgtxRootbeer** [comment]
Notice how it is recoverable though? A determined chaplain can ask for a hard suit and they have a chance of recovering it.

**Comment by Iamgoofball** [comment]
don't kid yourself

**Pull request merged**
