### PR TITLE
Highlander won't kill people who are in space upon being used

### LINKED ISSUE #13410: Highlander mode doesn't check if the person is in a 'safe' area before changing their equipment
I know its a meme admin button but as far as I'm aware all the other force-apparel events (at least wizard ones) has a check to make sure people that are in space aren't immediately fucked by the fact their hardsuit stuff just turned into a pair of kawaii cat ears and a horse mask.

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
Warps them to arrivals shuttle before equipping them if they are in space.

Fixes #13410

### CODE REVIEW

**Comment by PKPenguin321** [comment]
do the solars count as space too because i've been very nearly cucked by highlander because i was on a solar once

**Comment by Jordie0608** [comment]
isinspace() only checks for /turf/space

**Comment by KorPhaeron** [comment]
We need an isinvacuum proc

**Comment by tkdrg** [comment]
> We should have some sort of isinvacuum() proc

This is a great opportunity to code it.

**Comment by KorPhaeron** [comment]
@tkdrg 

Should it be absolute vacuum only or low pressure as well?

And if low pressure how low?

**Comment by tkdrg** [comment]
Do mobs have some sort of pressure resistance var before they start taking damage? Maybe check for that.

**Comment by KorPhaeron** [comment]
Don't know. Will redo this during the freeze maybe

**Pull request closed without merging**
