### PR TITLE
Fix halloweens races

### LINKED ISSUE #70873: Halloween races are un selectable
## Reproduction:

- Halloween races, despite it being Halloween, are not selectable. This is because the roundstart races list is instantiated before the holidays list is. 

image

image

image

### PR DESCRIPTION
**Pull request by MrMelbert**
## About The Pull Request

Fixes #70873

SSevents was initialized far, far after roundstart races were initialized, meaning the halloween species checked an-filled list, which always failed. 

So, I delegated it to a helper - `check_holidays`. If you want to check the existence of a holiday, you must use it instead, and the helper ensures the holidays list is filled no matter the situation. 

This should be unit tested but I just wanna get it out so they work

## Why It's Good For The Game

Halloween races are... fun

## Changelog

:cl: Melbert
fix: You can select halloween races again.
/:cl:

### CODE REVIEW

**Review by LemonInTheDark — DISMISSED** [review]
does this mean there's no reason for ssholidays to init now?

**Comment by ShizCalev** [comment]
```
 [02:59:51] Runtime in events.dm,168: bad index
  proc name: check holidays (/datum/controller/subsystem/events/proc/check_holidays)
  src: Events (/datum/controller/subsystem/events)
  call stack:
  Events (/datum/controller/subsystem/events): check holidays("Pride Week")
  the neutral fourcorners (/obj/effect/turf_decal/tile/neutral/fourcorners): Initialize(1)
  Atoms (/datum/controller/subsystem/atoms): InitAtom(the neutral fourcorners (/obj/effect/turf_decal/tile/neutral/fourcorners), 0, /list (/list))
  Atoms (/datum/controller/subsystem/atoms): CreateAtoms(null, null)
  Atoms (/datum/controller/subsystem/atoms): InitializeAtoms(null, null)
  Atoms (/datum/controller/subsystem/atoms): Initialize()
  Master (/datum/controller/master): init subsystem(Atoms (/datum/controller/subsystem/atoms))
  Master (/datum/controller/master): Initialize(10, 0, 1)
```

**Review by ShizCalev — CHANGES_REQUESTED** [review]
```
 [02:59:51] Runtime in events.dm,168: bad index
  proc name: check holidays (/datum/controller/subsystem/events/proc/check_holidays)
  src: Events (/datum/controller/subsystem/events)
  call stack:
  Events (/datum/controller/subsystem/events): check holidays("Pride Week")
  the neutral fourcorners (/obj/effect/turf_decal/tile/neutral/fourcorners): Initialize(1)
  Atoms (/datum/controller/subsystem/atoms): InitAtom(the neutral fourcorners (/obj/effect/turf_decal/tile/neutral/fourcorners), 0, /list (/list))
  Atoms (/datum/controller/subsystem/atoms): CreateAtoms(null, null)
  Atoms (/datum/controller/subsystem/atoms): InitializeAtoms(null, null)
  Atoms (/datum/controller/subsystem/atoms): Initialize()
  Master (/datum/controller/master): init subsystem(Atoms (/datum/controller/subsystem/atoms))
  Master (/datum/controller/master): Initialize(10, 0, 1)``
```

**Comment by LarissaMayrink** [comment]
the halloween races are working tho, i just played as a zombie for multiple rounds and saw the headless ones

**Pull request merged**
