### PR TITLE
makes torches craftable in the tribal menu

### PR DESCRIPTION
**Pull request by AarontheIdiot**
## About The Pull Request

 title. craftable for 1 cloth and 2 log

## Why It's Good For The Game

 torch

## Changelog
:cl:
add: Torches are craftable in the Tribal menu. 1 cloth, 2 logs.
/:cl:

### CODE REVIEW

**Comment by fludd12** [comment]
You can make torches already by applying a leafy plant (I think?) to a log - I'm not sure an effective way to convey this through the crafting menu, though.

**Comment by ishitbyabullet** [comment]
Good thing we have a vegan torch option then.

**Comment by carlarctg** [comment]
but cotton is made by processing a cotton plant's products...

also, is there a way to make this also/only craftable via planks? it's going to be very underused as-is, because iirc only botany can produce logs. making it plank craftable give it a lot more use as a makeshift torch, since not only can both botanists and ashwalkers use their hatchet or saw, random assistants or whatever can deconstruct wooden things and make torches with them

**Comment by ishitbyabullet** [comment]
that's why i said hippie as well. besides, what if we add sheep and you got cloth (for some dumb reason) from shearing them?

Plank option would be nice too. You only need a single, good stick.

**Comment by AarontheIdiot** [comment]
I have small brain

**Pull request closed without merging**
