### PR TITLE
Hang Loose Bruh! A new Beach Biodome

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request

This pull request completely revamps the beach biodome lavaland ruin, making it slightly more interactive, granting the ability to do more, and preventing the beach bums from leaving the ruin without outside intervention.

image

## Why It's Good For The Game

This should reduce the number of people that take the beach spawns just for a "free respawn" and also give more substance to the beach ruin instead of just removing it.

## Changelog
:cl:
add: Completely New Beach Biodome
/:cl:

### CODE REVIEW

**Comment by wesoda25** [comment]
image
perfect

**Comment by evilcyborgmrt** [comment]
Looks great bro but can you add a grill bro?

**Comment by ATH1909** [comment]
Do the beach bums get any disks to go with their gene manipulator?

**Comment by Ratvar** [comment]
Ah, so you just break girders with anything and walk out?

**Comment by CAPTTLasky** [comment]
> 
> 
> Do the beach bums get any disks to go with their gene manipulator?
> 
> Is that a nutrivend or a seed vendor? If the latter, do the beach bums have the supplies needed to fertilize their plants, kill pests, etc.?
> 
> A heroi- er, space drugs syringe or two might also be a cool thing to add to the little maint section of the ruin.

I will add disks and also random drugs : )

**Comment by CAPTTLasky** [comment]
> 
> 
> Ah, so you just break girders with anything and walk out? Make 'em walls instead, or it'll stay free respawn ruin

I was under the impression that it took a lot to break a girder. I'll playtest and see what/if anything in there can break the girders. If they can, I'll either remove the item or get better barricades.

**Comment by AnonymousNow** [comment]
Cool. The beachdome felt barren and underutilised, by far the worst lavaland ghost spawn. I'll have fun trying this out alongside the new seed vault.

**Comment by Ratvar** [comment]
max_integrity = 200
Metal sheets are metal rods are force = 9
200/9=23 hits to escape
That's not really "Cannot escape without outside intervention", is it

**Comment by CAPTTLasky** [comment]
> 
> 
> max_integrity = 200
> Metal sheets are metal rods are force = 9
> 200/9=23 hits to escape
> That's not really "Cannot escape without outside intervention", is it

I'll fix it

**Comment by wesoda25** [comment]
_chicken joe intensifies_

**Comment by CAPTTLasky** [comment]
The girders are reinforced and deflect 22 damage. Miners can get in, beach bums with spears cannot get out.

**Comment by Fikou** [comment]
its not a biodome anymore change the name

**Comment by AnonymousNow** [comment]
?

**Comment by gitbirb** [comment]
wheres the dancemachine? that was an integral part of the ruin

**Comment by wesoda25** [comment]
so why was this dudes account nuked

**Pull request closed without merging**
