### PR TITLE
AI core turret move on Meta and Delta.

### PR DESCRIPTION
**Pull request by zxaber**
## About The Pull Request
Moves two of the AI core turrets on Meta and Delta so that they can cover the tiles directly in front of the AI. All other maps in rotation already have turrets in similar positions.

## Why It's Good For The Game
Jaunting allowing attackers to completely ignore the AI's defenses is lame. Most (if not all) antagonists that would use jaunting to attack the AI have other options that allow some counterplay on the AI's side.

## Changelog

:cl:
balance: The AI turrets on Metastation and Deltastation now cover the area directly in front of the AI.
/:cl:

### CODE REVIEW

**Comment by Mothblocks** [comment]
very very very skeptical on this wrt cult balance already not really being in their favor

**Comment by SkeletalElite** [comment]
> very very very skeptical on this wrt cult balance already not really being in their favor

Cult have EMPs and the AI shouldn't be so weak to jaunting that anyone who does it can use a single jaunt, and kill the AI by the time the AI screams for help a single time.

**Comment by jughu** [comment]
This nerfs the ai infact
Lets go trough some points
1.this adds coverage of the middle part of the ai which is a good thought but this makes the ai extremely vulnerable at the positions the turrets at.
2.if cult jaunts in theres 9/10 times ai has turrets on stun and wont be able to react anyways
3.crew can destroy litteraly 1 turret and take the rwall behind it and kill the ai
4.crew can destroy litteraly 1 turret climb on the left table and shoot the apc with  ion rifle without the ai even being able to get coverage on them

Tl;dr AI nerf

**Comment by wesoda25** [comment]
This will do nothing about jaunting, you will always be able to kill an AI with 0 risk if you know what you are doing.

**Comment by IndieanaJones** [comment]
You can just jaunt onto the tile with the AI physically on it and be fine.

**Comment by TheBonded** [comment]
can't they just jaunt on top of the AI and kill it there while the AI takes the laser hits?

**Comment by zxaber** [comment]
You can't jaunt onto an AI anymore. That was changed in the PR that also prevents jaunting into walls.

That said, I think I'm going to sit on this a bit more. I'm not really totally happy with how the turret placement ended up.

**Pull request closed without merging**
