### PR TITLE
Fixes temperature not causing turfs to activate

### LINKED ISSUE #17255: Heating a turf with a heater will only heat this turf and not spread the heat.
Basically the turf is not excited and doesn't update the air so the temperature isn't equalized with the nearby turf until the starting turf gets excited by something.

### PR DESCRIPTION
**Pull request by Cyberboss**
@MrStonedOne 

For the life of me I can't figure out why this check was here, so I removed it and, lo and behold. Space heaters work

Fixes #17255 

:cl:
fix: Temperature changes will now properly cause atmospherics simulation to activate
/:cl:

### CODE REVIEW

**Comment by optimumtact** [comment]
This looks like it was copypasta from earlier code that used ratios and was not updated properly so the delta's were just too large instead of being properly scaled based on the temperature size.

Not sure any scaling is actually needed honestly, we always want differences past some meaningful point to activate and equalise.

**Comment by AnturK** [comment]
Pre dunc rewrite there seemed to exist another define for temp ratio instead of diff. This seems to be a just some leftover that was not culled.

**Comment by Cyberboss** [comment]
@duncathan #whileyouwereaway

**Comment by duncathan** [comment]
this is fine

**Pull request merged**
