### PR TITLE
Bitrunning: Combat domain [READY]

### PR DESCRIPTION
**Pull request by jlsnow301**
## About The Pull Request
Finally dusts off this project to make a deathmatch style bitrunning map.  
Don't be too intimidated by the file diff, lots of code organization + resized a large map.

Changes:

1. Reuses the gateway beach map as a combat zone (99% of the file diff) (maptainers: i just added spawners and areas)
2. Alters how bitrunning handles spawning: Custom spawns are now available, which can be anything

Misc organization:

- Splits netpod.dm into separate files.
- Fixes some wording in vdom map documentation.
- Organizes vdom variables a bit.
- Adds a permanent hololadder spawn.

How bitrunning deathmatch works: 

- Temporary spawners are offered to both ghosts and bitrunners. 
- Runners spawn in like usual. Ghost can use the spawner menu.
- Ghosts work to prevent avatars from collecting side objectives or try to cause mass brain damage.
- The domain completes after a number of deaths accrue. Any faction. Blood for the blood god, etc.
- This map can be played solo. ANY deaths.

## Why It's Good For The Game
I've been toying with the idea of a deathmatch style map for some time. I liked syndicate assault, the spawners were intentionally left there, and the possibility of player-controlled players made the experience more tense and challenging.

This PR leans into this idea: The virtual world is dangerous. Players get a chance to compete on both sides here. It offers a lot of variety to bitrunning other than "run for box". It's also very lucrative if ghosts join in.

## Changelog

:cl:
add: Added a bitrunning deathmatch map: Island Brawl. Both ghosts and runners get many more spawns than normal.
fix: Lowered the static vision time in domain load in.
/:cl:

### CODE REVIEW

**Comment by jlsnow301** [comment]
First test of this went very well

**Comment by norsvenska** [comment]
good ideas and all, but i'm struggling to see the reason for outright removing the beach gateway

**Comment by jlsnow301** [comment]
> good ideas and all, but i'm struggling to see the reason for outright removing the beach gateway

One of the few maps worth saving from the gateway

**Comment by Blacklist897** [comment]
I will miss the beach gateway. it was a cool rp zone

**Comment by jlsnow301** [comment]
Readded the beach map since a conversation opened about gateway in disc

**Review by Maurukas — APPROVED** [review]
Since this is preserving the gateway (you may want to update the description), I've got no issues with this.

**Comment by jlsnow301** [comment]
> Since this is preserving the gateway (you may want to update the description), I've got no issues with this.

Changed it to say "reuses"

**Pull request merged**
