### PR TITLE
Runechat now shows on the thing the talker is in, rather then on the talker themself

### PR DESCRIPTION
**Pull request by LemonInTheDark**
## About The Pull Request

Changes the object runechat text is overlayed onto from the talker, to the closest thing to the turf the talker is in.
This means if someone is talking in a locker, you can see it. Ditto for radios in people's packs.

## Why It's Good For The Game

If someone is talking, I should be able to see where the chat is coming from.

We lose a little in this change, because we can't cheaply update the target of the image, it'll stick around attached to whatever it started in. This will only really effect throwing objects out of your bag mid talk, which I think is worth it.
We **could** get around this, but it would require using a semi expensive component, which feels like it will end poorly.

## Changelog
:cl:
add: If you are "in" something, and talk, runechat will be displayed as if the thing you are in talked.
/:cl:

### CODE REVIEW

**Comment by ATH1909** [comment]
justice for pAIs

**Comment by MrPerson** [comment]
What do you mean can't cheaply update the target of the image? What part is expensive there? Isn't it literally just registering to the moved comsig?

**Comment by LemonInTheDark** [comment]
Does move progress down? I need to watch if the thing moves, if it's parent moves, ect.

**Comment by Rohesie** [comment]
Still working on this?

**Comment by LemonInTheDark** [comment]
yeah, well kinda. I'm not sure it's possible to add full functionality cheaply, at the very least I don't wanna poke the runechat ss and have it collapse around me. The lint failing is just a matter of travis getting overloaded. Is there anything else you'd like done to it?

**Comment by Rohesie** [comment]
Those this behave properly for moving objects such as mechs?

**Comment by LemonInTheDark** [comment]
yep, the only issue is as I described in my pr, saying something in say a locker and moving out of it causes the text to stay on the locker. Ditto for objects that say things in someones backpack.

The upside is things that are contained in something will make proper runechat text now

**Pull request merged**
