### PR TITLE
Everything is fire

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
What have I done

### CODE REVIEW

**Comment by duncathan** [comment]
did you fuckin do it again

**Comment by KorPhaeron** [comment]
do I ever not do it

**Comment by KorPhaeron** [comment]
@duncathan 

Merge fuck

**Comment by duncathan** [comment]
Dammit kor

**Comment by PKPenguin321** [comment]
what the heck did you do

**Comment by Incoming5643** [comment]
Instead of "if something is burning, hurt a human" it was "if something can burn, hurt a human"

**Pull request merged**
