### PR TITLE
Makes the cardboard sprite 3D

### PR DESCRIPTION
**Pull request by Wallemations**
## About The Pull Request
I know it's meant to be flat but the fact it was incomprehensibly flat irked me, not to mention the weird lighting
Before
card-export

After
card-export2
## Why It's Good For The Game
antonblast
## Changelog
:cl: Wallem
image: Tweaks cardboard sheet sprite
/:cl:

### CODE REVIEW

**Comment by san7890** [comment]
it's funny whenever i see the cardboard sprite because it always implies that every box in ss13 is missing a side. how are you going to get a fully-enclosed box with five sides mr. smart guy

**Comment by Wallemations** [comment]
> it's funny whenever i see the cardboard sprite because it always implies that every box in ss13 is missing a side. how are you going to get a fully-enclosed box with five sides mr. smart guy

The same way the station has a roof

**Comment by ChungusGamer666** [comment]
i hate this

**Comment by Serxule** [comment]
is this 3d? i only see a bunch of extra dots and one line at the very bottom

**Comment by Wallemations** [comment]
> is this 3d? i only see a bunch of extra dots and one line at the very bottom

Compared to the old one, yes. The line at the bottom implies depth that wasn't there before

**Comment by Toastgoats** [comment]
Wouldn't it make more sense to just make a new cardboard sprite in line with the other 3/4 stacks?

**Comment by Wallemations** [comment]
> Wouldn't it make more sense to just make a new cardboard sprite in line with the other 3/4 stacks?

That's more or less what I tried to do here, though it isn't as clear as I didn't give it the actual stacked sprites
I could easily throw that together though

**Pull request merged**
