### PR TITLE
ClickOn now actually calls ranged right click attacks

### PR DESCRIPTION
**Pull request by tralezab**
## About The Pull Request

I... don't know how this was missed. Ranged right clicks only called post secondary attacks, which is hilarious and mysterious. How did NOBODY notice you could only hold someone up in MELEE range?

I also named the vars in the proc to be more readable, and added a few early returns. I didn't touch much about the top part of the proc so it may still look gross.

## Why It's Good For The Game

You can now hold people at gunpoint with a gun... at range!

This probably fixes a lot of other weird stuff?

## Changelog

:cl:
fix: You can now hold people at gunpoint from range!
/:cl:

### CODE REVIEW

**Comment by TemporalOroboros** [comment]
> How did NOBODY notice you could only hold someone up in MELEE range?

I thought this was intended.

**Comment by tralezab** [comment]
there are zero range checks on gun holdups

**Comment by manofpepsi** [comment]
> > How did NOBODY notice you could only hold someone up in MELEE range?
> 
> I thought this was intended.

yeah it is 100% intended.

**Comment by NamelessFairy** [comment]
> > How did NOBODY notice you could only hold someone up in MELEE range?
> 
> I thought this was intended.

https://github.com/tgstation/tgstation/pull/47677

Seems to be intended that you can only start the initial hold up at point blank but you can move afterwards, not sure if this PR is just fixing the move around after holding someone up aspect or making it so holdups can be done at any range

**Comment by itseasytosee** [comment]
Before combat mode, you could hold people up at as far as two places away. I remember this vividly.

**Comment by optimumtact** [comment]
I do not think this PR is correct it should be reverted

**Pull request merged**
