### PR TITLE
Adds blob early communication button

### PR DESCRIPTION
**Pull request by ChangelingRain**
:cl: Joan
rscadd: Blobs can communicate before bursting to allow for more coordination.
/:cl:

this ain't a moment it's a movement

### CODE REVIEW

**Comment by Incoming5643** [comment]
I disagree on this one. Not every antag needs a team antag chat.

**Comment by KorPhaeron** [comment]
@Incoming5643 

What do you think the odds are someone PRs a rev hivemind sometime during the year?

**Comment by PKPenguin321** [comment]
>removes early popping for being too powerful
>adds this

hmm

**Comment by ChangelingRain** [comment]
it's hard to gauge the effect of good communication given that players can often range in skill from 'absolute idiot firsttimer' to 'literally knows it inside and out'

if this turns out too strong, I'll just lower the time blobs have to burst(or give the verb later)

**Comment by ChangelingRain** [comment]
also incoming probably wants my head for adding another thing to add to datum antags

**Comment by GunHog** [comment]
It is confirmed, Joan is the next Paprika. This particular PR is a good one, though.

**Comment by Incoming5643** [comment]
thankfully an action button is fairly self contained

**Comment by Incoming5643** [comment]
hgnh

**Comment by ChangelingRain** [comment]
every team antag needs a team antag chat

**Comment by Incoming5643** [comment]
if you try to add revolution chat I'm gonna slap you

**Pull request merged**
