### PR TITLE
Atrocinator flips your chat text around

### PR DESCRIPTION
**Pull request by MrMelbert**
## About The Pull Request

image

## Why It's Good For The Game

It's funny

## Changelog

:cl: Melbert
add: The Atrocinator will now flip you even more. 
/:cl:

### CODE REVIEW

**Comment by carlarctg** [comment]
it IS funny but it kinda makes me sad

**Comment by CRITAWAKETS** [comment]
great PR, finally australians can play

**Comment by Wallemations** [comment]
Honestly I had no clue this was even something that was possible, it is insanely funny

**Comment by Jacquerel** [comment]
> it IS funny but it kinda makes me sad

Are the dreams in which you're dying the best you've ever had?

**Review by Jacquerel — APPROVED** [review]

**Pull request merged**
