### PR TITLE
Welding Goggles now available at Autolathe

### PR DESCRIPTION
**Pull request by AarontheIdiot**
## About The Pull Request

 @ExcessiveUseOfCobblestone said to PR this before merging my plasmaman helmet PR. PR just adds Welding goggles to autolathes for like, 350 glass.

## Why It's Good For The Game

 Some people don't want to wear ugly welding helmets all the time, this makes welding goggles more available so that people can remain stylish and have welding protection at the same time.

## Changelog
:cl:
add: Welding goggles can be made at Autolathes now.
/:cl:

### CODE REVIEW

**Comment by InsaneHyena** [comment]
Power creep

**Comment by bigfatbananacyclops** [comment]
There’s already welding helmet but i think the goggles should be a engi protolathe think, it’d make sense since it uses plastic material for the goggles. Also it isn’t even powercreep ????? There is welding helmet and welding goggles are kind of really useless, they aren’t “sunglasses with weld protection” you realize it blocks your sight if you wear it right?  @InsaneHyena

**Comment by FantasticFwoosh** [comment]
> but i think the goggles should be a engi protolathe thing, it’d make sense since it uses plastic material for the goggles

Just roll with this guy's idea and this PR would be fine. Both welding goggles and helmet are outclassed by the welding gas-mask anyway.

**Comment by ExcessiveUseOfCobblestone** [comment]
This is why I did not want to hide the change under the plasmaman PR.

**Comment by dr-bee** [comment]
if this should go anywhere it should go under basic engineering tech in the engineering and research protolathes so engineers and roboticists can print more if needed. cargo and normal crew dont need it.

**Comment by Tlaltecuhtli** [comment]
engineers and scientists get welding gas masks on the literally first node ever researched there is no need for more bloat

**Comment by ExcessiveUseOfCobblestone** [comment]
I wouldn't call these bloat since they are on a unique slot compared to the mask and helmet. They're not JUST a cosmetic difference, they do have a balance implication.

**Comment by AarontheIdiot** [comment]
I could probably move the welding helmets to the engi protolathe and keep the goggles in the autolathe

**Comment by ExcessiveUseOfCobblestone** [comment]
Is there REALLY that strong of a difference between the helmet/goggles from a balance perspective? Everyone's being kinda vague about the consequences of this so if no one can actually explain what's bad in a practical matter i'll just merge this.

**Comment by 81Denton** [comment]
I don't see a huge difference since welding goggles also keep you from wearing sunglasses or mesons.

**Comment by AarontheIdiot** [comment]
the only real difference between the goggles and helmet is the slot they go in and the sprite. Both toggle, they have the same flash protection, and the same tint.

**Comment by dr-bee** [comment]
> 
> 
> the only real difference between the goggles and helmet is the slot they go in and the sprite. Both toggle, they have the same flash protection, and the same tint.

One lets you wear armor or a space suit helmet the other does not.

**Comment by 81Denton** [comment]
Let's give this a shot, if it becomes a balance issue we can always rebalance them or move them to the engineering lathe.

**Comment by optimumtact** [comment]
revert this

**Comment by optimumtact** [comment]
or move it to the techwebs node

**Pull request merged**
