### PR TITLE
Adds new emojis and gives the QM's PDA a unique sprite

### PR DESCRIPTION
**Pull request by TZK13**
all new emojis example
That's all of the emojis added in this PR, as I said previously I'll make a wiki article for all of the emojis if and when this is merged.

https://tgstation13.org/wiki/Emoji_cheat_sheet

qm pda
The cargo tech and QM PDAs have always looked identical, this serves to distinguish between them.

### CODE REVIEW

**Comment by phil235** [comment]
:+1:

**Comment by Nienhaus** [comment]
:+1:

**Comment by Nienhaus** [comment]
:-1:

**Comment by TZK13** [comment]
:fries:

**Comment by bgobandit** [comment]
:honkman:

**Comment by JJRcop** [comment]
>not making one or two emojis have slightly distant names (besides silentman)

**Comment by TZK13** [comment]
My excuse is that I was adding emojis so quickly that I couldn't take the time to come up with good names.

**Comment by paprka** [comment]
Shades are really hard to see and tiny.

Add a flash one maybe.

**Comment by Ergovisavi** [comment]
:+1: 
SALT SALT SALT

**Comment by TZK13** [comment]
The shades are definitely the smallest emoji but it's in scale with the head emojis so it looks appropriate if placed beside :head:.

I was gonna add a flashbang one, maybe I'll do that instead. A flash doesn't really communicate much as an image alone I feel compared to a flashbang.

**Comment by TZK13** [comment]
Changed my mind about both of your suggestions Pap, the shades emoji now uses the icon sprite and I added a flash emoji.

**Comment by Nienhaus** [comment]
Owlman :+1:

**Comment by TZK13** [comment]
https://tgstation13.org/wiki/Emoji_cheat_sheet

**Pull request merged**
