### PR TITLE
Makes N2O an effective oxidizer

### PR DESCRIPTION
**Pull request by as334**
Since N2O acts a powerful oxidizer in fires IRL, I figure it would make sense to port to spessmens. Especially because toxins has needed something new to experiment with, as do atmos techs.
Also cleans up some relative pathing.

INB4 I now get blamed for every issue related to fires.
(This is a remake of my previous PR, that i closed due to merge conflicts)

### CODE REVIEW

**Comment by Lumipharon** [comment]
Realism aside, this doesn't actually change anything, except for fires where people don't have internals, they'll fall unconscious THEN burn to death.

**Comment by WJohn** [comment]
I've stated before and I'll state it again: Plasma is already insanely powerful and is completely impossible to put out once it gets started, we really don't need another horribly burny substance, even if all it does is make plasma even more deadly.

**Comment by duncathan** [comment]
>completely impossible to put out

my nanofrost says otherwise
also the fact that fires very quickly break holes into space and put themselves out :/

**Comment by as334** [comment]
Jesus christ, do i have to restate this every time. The Nitros Oxide doesn't burn. It is a facilitator of the burn, like oxygen. However it burns up faster than oxygen, but works a bit better in lower temperature fires, and works just as well in high temperature fires.

**Comment by Tokiko1** [comment]
Currently, N2O can also be mixed into a plasmaflood mix to ensure that the fire never gets too hot to melt floor tiles, greatly expanding the lenght of the fires. Is this still possible with this change?

**Comment by duncathan** [comment]
Are you sure that's N2O, not N2?

**Comment by Razharas** [comment]
@Cheridan your call

**Comment by Cheridan** [comment]
surpriiiiiise

**Comment by optimumtact** [comment]
Nobody expects the cheridan inquistion

**Pull request merged**
