### PR TITLE
Changes the Salt Shaker and the Pepper Mill sprites

### PR DESCRIPTION
**Pull request by chanoc1**
:cl:
tweak: The salt and pepper shakers have new sprites.
/:cl:
peppermillsmall
saltshakersmall

### CODE REVIEW

**Comment by Iamgoofball** [comment]
It's good

**Comment by jughu** [comment]
It looks more like an AAA battery

**Comment by Fox-McCloud** [comment]
Yeah; these aren't very iconic.

Yeah, I know, most salt and pepper shakers at fastfood places are plastic and cylindrical, but that's hardly instantly recognizable as a salt/pepper shaker.

The sterotypical shapes already used are instantly recognizable as salt and pepper without even examining them.

**Comment by chanoc1** [comment]
here they are ingame 
dreamseeker_2017-02-06_22-05-44

**Comment by PKPenguin321** [comment]
Kinda gross

**Comment by chanoc1** [comment]
uff~

**Comment by calzilla1** [comment]
STOP FUCKING WITH IT

**Comment by dannno** [comment]
it does kind of look like a battery

**Comment by chanoc1** [comment]
bum, new sprites, but same ol' shape. their color is according to the palette
peppermillsmall
saltshakersmall

**Comment by WJohn** [comment]
Those look nice right there, the ones suggested in the PR aren't, but I like those.

**Comment by chanoc1** [comment]
I DID IT; I SEE THEHEAD LINES NOW: CHANOC FINALLY GETS THE SPRITES RIGHT

**Comment by Fox-McCloud** [comment]
Concur with @WJohn

**Comment by jughu** [comment]
@chanoc1 give them empty sprites too then this pr be 10/10

**Comment by chanoc1** [comment]
wouldnt making the salt and pepper shakers actual sprite changing containers be a separate PR?

**Comment by jughu** [comment]
I mean if you turn this it in auctally sprite changing containers you have two things in one stone related to the same thing

**Comment by chanoc1** [comment]
i guess yeah ill do that

**Comment by chanoc1** [comment]
<o/

**Comment by chanoc1** [comment]
so, whats the verdict

**Comment by jughu** [comment]
@chanoc1 firstly you should put the new sprites in the pr descriptoon so people wont still think its a AAA battery

**Comment by chanoc1** [comment]
oh yeah

**Pull request merged**
