### PR TITLE
Redo's #23247 adding more TOOLS to the TOOLBELT

### PR DESCRIPTION
**Pull request by jughu**
i only love the geiger and airlock painter anyways

:cl: Hyena
tweak:Toolbelts now can fit geiger_counters and airlock painters
/:cl:

[]: # (Please add a short description of why you think these changes would benefit the game. If you can't justify it in words, it might not be worth adding:)they are tools DUH

### CODE REVIEW

**Comment by Core0verload** [comment]
Why not botany tools? Botany can make tool belts, why they can't use them?

**Comment by ExcessiveUseOfCobblestone** [comment]
Botany belt should be made out of vines

**Comment by jughu** [comment]
@core0verload this is my priority to fix my immersion i want geiger counter and airlock painter they tools and supposed to be in a toolbelt you make your own pr about botany

**Comment by Haevacht** [comment]
Or you can expand your shit. If it can fit a crowbar why not a spade or cultivator? If it holds a Tray why not a plant analyser, etc.

**Comment by jughu** [comment]
We could say that over every belt yet they hold limited items

**Comment by jughu** [comment]
@haevacht i be porting a botany belt from /para/ anyways which you be able to make from the biogenerator as a upgrade

**Comment by Core0verload** [comment]
it's always better to extend existing items instead of creating new ones

**Comment by jughu** [comment]
If you want random clutter use a bookbag

**Comment by jughu** [comment]
@korphaeron do you atleast agree with this one?

**Pull request closed without merging**
