### PR TITLE
Revamps and gives some love to the Free Golem Ship

### PR DESCRIPTION
**Pull request by Zergspower**
## About The Pull Request

Not 100% sure why i did it but i wanted to see a less ah, dated ship design for the Golem ship and so i took a stab at it. As for the shape? I love irregularly shaped ships (EVE Online, most sci-fi shows etc).  And if anything should be changed with this that the old had suggest it below, dont mind making tweaks (e.g. 'hated the lamps', 'fuck that one purple tile' etc)

Old: 
image

New:
<details>
<Summary>With working shutters</Summary>

image

image
</details>

## Why It's Good For The Game

Nothing outside of the ship shape has really changed - though there is exactly 2 more golem shells and +1 of each mining item to make it an even 10 instead of 9. 

## Changelog
:cl:Zergspower
qol: Free Golem Ship - Revamped design, made it shiny
/:cl:

### CODE REVIEW

**Comment by newfren** [comment]
mining vendor seems sorta weirdly tucked away

**Review by MrMelbert — CHANGES_REQUESTED** [review]
rotate those front shutters

**Comment by Zergspower** [comment]
image

image


> rotate those front shutters

**Comment by Zergspower** [comment]
i've been too spoiled by SR's omni shutters heh

**Comment by YakumoChen** [comment]
8 beds, 6 shells...?

**Comment by Paxilmaniac** [comment]
I feel like the shape of this is somehow actively worse than the box it was before. There is no rhyme or reason its just offset fnr, and looks stupid as a consequence.

**Comment by Helg2** [comment]
I think if you will put mining gear in the vendors it will look somewhat better.
And only one exit from the shuttle seems lame, what if there's megafauna in there?

**Comment by YakumoChen** [comment]
The tiling is really ugly, all purple was somehow better.
It needs a portside door

**Comment by Zergspower** [comment]
> 

could we do that? let me see what the golem mining vendor has and maybe i can add those in

**Comment by Zergspower** [comment]
> I think if you will put mining gear in the vendors it will look somewhat better. And only one exit from the shuttle seems lame, what if there's megafauna in there?

image
Done through the order_golem.dm yeah?

**Comment by iwishforducks** [comment]
I'm all for some golem appreciation, but this removes way too many external airlocks. Having airlocks surround the ship is extremely important as sometimes megafauna (or just fauna in general) will be camping one of the external airlocks.

**Comment by Zergspower** [comment]
> I'm all for some golem appreciation, but this removes way too many external airlocks. Having airlocks surround the ship is extremely important as sometimes megafauna (or just fauna in general) will be camping one of the external airlocks.

yeah going to change it up a bit more - looking to add their gear to the vendor at the moment

**Comment by Zergspower** [comment]
image

**Comment by Zergspower** [comment]
I looked in the vendor code but i had no way to set a quantity and didnt want to allow - say - 5 billion pickaxes at 0 cost

**Comment by Helg2** [comment]
> I looked in the vendor code but i had no way to set a quantity and didnt want to allow - say - 5 billion pickaxes at 0 cost

https://github.com/tgstation/tgstation/blob/0931f3b75cc6480826b2924d77821f9e5ce2bdcd/code/modules/vending/_vending.dm
Why not make your own new vendor though? Dont think its too hard

**Comment by YakumoChen** [comment]
Six golems... four beds...

**Comment by YakumoChen** [comment]
I don't like the placement of the resonators. It feels a little random and out of the way from the other miner stuff.

Goofy amount of bags and shovels and picks, I feel we could do away with half of them all. Shovels can be lathed and everything else is vendored or printed.

**Comment by Zergspower** [comment]
> I don't like the placement of the resonators. It feels a little random and out of the way from the other miner stuff.
> 
> Goofy amount of bags and shovels and picks, I feel we could do away with half of them all. Shovels can be autolathed and everything else is vendored or printed.

that's literally the exact amount of items that were there before except i added 1 to make it not 9

**Comment by YakumoChen** [comment]
Counting 16 ore bags

You might as well get rid of some of the extra useless junk while you're here though, nobody is going to miss a few shovels.

**Comment by YakumoChen** [comment]
Having 9 sets of items felt a little more sensible in crates but having them all on racks really brings out how overstocked it looks.

**Comment by YakumoChen** [comment]
The ORM frame should be placed somewhere it's actually likely to be built

**Comment by Zergspower** [comment]
> > I looked in the vendor code but i had no way to set a quantity and didnt want to allow - say - 5 billion pickaxes at 0 cost
> 
> https://github.com/tgstation/tgstation/blob/0931f3b75cc6480826b2924d77821f9e5ce2bdcd/code/modules/vending/_vending.dm Why not make your own new vendor though? Dont think its too hard

i popped a question into coding-general about it - since these run off the caro model now rather than the vending - maybe could use a generic vendor for just the 'basic mining items' but unsure if we want to create a new one just for golems for that

**Comment by YakumoChen** [comment]
The toolbox is also placed way far away from anywhere its likely to be used for no reason (aesthetics?)

**Comment by YakumoChen** [comment]
It has dawned on me that golems having beds is a bit nonsense.

It's heavily implied they don't require sleep since they refer to all bedsheets as capes

**Comment by EOBGames** [comment]
Just relaying what I said on discord to the contributor- I don't think this actually addresses the issues with the golem ship, which is that it's big and empty. I'll leave this open to give an opportunity to change it up further, but I'll mark the PR as DNM for the time being.

**Comment by UnokiAs** [comment]
Maybe add like a engi part, A bar and room to process mats to make it more full kinda like current space ships ruins

**Comment by san7890** [comment]
it's been three weeks since any work was done on this PR and one week without any sign of the contributor addressing feedback (as well as a lack of interest from maintainers), I will be closing this PR in the interest of keeping the tracker clean.

You are encouraged to make a new PR (such that it is more visible to maintainers) if you come back with the feedback from this PR incorporated within.

**Pull request closed without merging**
