### PR TITLE
Improves Geis binding resist

### PR DESCRIPTION
**Pull request by ChangelingRain**
:cl: Joan
rscadd: Trying to move while bound by Geis will cause you to start resisting, but the time required to resist is up by half a second.
experiment: Resisting out of Geis now does damage to the binding, and as such being stunned while bound will no longer totally reset your resist progress.
rscadd: Using Geis on someone already bound by Geis will interrupt them resisting out of it and will fully repair the binding.
tweak: Geis's pre-binding channel now takes longer for each servant above 5. Geis's conversion channel also takes slightly longer for each servant above 5.
/:cl:

Yes, this means mending motors are eeeeven beeetter because they'll repair the binding.
In exchange, the pre-binding channel is longer and more obvious when above 5 servants, and it's easier for people to resist out(but also easier to see how close they are to getting out, and the actual resist time is slightly higher)

And yes, you can use a proselytizer on the glowing ring. Don't ask me HOW that works, exactly.

### CODE REVIEW

**Comment by francinum** [comment]
in which geis becomes useless without 5 people throwing spears into them.

**Comment by Cheridan** [comment]
>Yes, this means mending motors are eeeeven beeetter because they'll repair the binding.

ok but what are you supposed to do before you have a fancy base going

**Comment by ChangelingRain** [comment]
Something something actual teamwork instead of lone mcwolf wolfson, servant of lonewolfvar

**Comment by Cheridan** [comment]
>actual teamwork
>aka the whole group being all in one place so sec can catch them all at once when caught

👍

**Comment by ExcessiveUseOfCobblestone** [comment]
You Lone Wolf until you get scarabs, then you have a team at your fingertips [more or less literally if you pick them up]

**Comment by AnturK** [comment]
Not sure how i feel about the pulling change, pull first then unbuckle is nice with prisoners.

**Comment by optimumtact** [comment]
Yeah honestly it seems like an ascended feature than a bug

**Comment by KorPhaeron** [comment]
I agree, would be awful for security

**Comment by ChangelingRain** [comment]
The pull change is to avoid pull then bind and then they have to resist out of your pull before they can resist the binding

**Comment by PKPenguin321** [comment]
Isn't pull resist instant though

**Comment by ChangelingRain** [comment]
It's instant but is at a prob(30/pulledby.grab_state) so you won't always get out and there's a 2 second delay on trying again if you fail

**Comment by KorPhaeron** [comment]
I don't think we should change a quality of life feature used by security (and a
some badguys!) in every mode to try and balance a single power in a single mode

**Comment by ChangelingRain** [comment]
okay limited that effect to the geis binding(and anything else that sets it)

**Pull request merged**
