### PR TITLE
Engineering Cyborg Tools Now Use the Default Sprites

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
I'm sick of trying to look through half a dozen dark grey blobs trying to figure out which tool is which

### CODE REVIEW

**Comment by TehZombehz** [comment]
As much as I like the fancy different sprites, they're all a dark color, the multitool looks almost exactly like the screwdriver and they all have absurdly similar colors that are hard to see on certain backgrounds.

**Comment by Ausops** [comment]
https://file.house/bKbx.dmi
https://i.imgur.com/4gHTk1G.png

alternate sprites for the engiborg tools, could be more distinguishable might not be vOv

**Comment by KorPhaeron** [comment]
Thanks Anna

**Comment by Aloraydrel** [comment]
Why not power tool models 8^)

**Comment by XDTM** [comment]
Those sprites are better, but still ambiguous. I think that differentiating the shape of the whole tool would improve clarity, instead of only the final part.

**Comment by ChangelingRain** [comment]
Yeah you really need to be able to tell which tool is which instead of them being similar

**Comment by coiax** [comment]
It took me a little bit of time to learn them, but I have no problem with telling the tools apart. But maybe from a usability perspective, it's easier if we just change them back, or reskin them subtley.

**Comment by MrStonedOne** [comment]
\>no changelog

fucking fired.

**Pull request merged**
