### PR TITLE
Improves many areas of CentCom

### PR DESCRIPTION
**Pull request by EuSouAFazer**
## About The Pull Request

Centcom is better

## Why It's Good For The Game

It's because because, as we all know, the better something is, the better it is.

## Changelog
:cl: Fazzie
qol: NT's logo on Centcom's landing pad looks better
qol: Centcom's Cargo and other rooms had their items rearanged to look marginally better. Like you're every gonna see them!
fix: The Thunderdome on Centcom now has up-to-date cooking machinery
/:cl:

### CODE REVIEW

**Comment by EuSouAFazer** [comment]
Also removed the hierophant tiles from an inacessible room. Nobody is gonna look at that room and adding megafauna tiles to centcom sounds like a ticking time bomb for a problem to arize

**Comment by mc-oofert** [comment]
improvements to an area nonadmins nonobservers will see for 1 minute every 1 hour or so

**Comment by EuSouAFazer** [comment]
> improvements to an area nonadmins nonobservers will see for 1 minute every 1 hour or so

True, actually! I am going to close this PR and, instead, put my work towards fixing a minor visual bug that has a 1-in-5 chance of happening once every 400 rounds. Much more beneficial to the codebase as a whole! Thank you for your comment!

**Comment by DaydreamIQ** [comment]
Always found it weird that the CC kitchen had barely anything to cook with. Good change, Now I can beeline for the kitchen and actually feed people

**Review by Maurukas — APPROVED** [review]

**Pull request merged**
