### PR TITLE
Resprites Mech Mining Tools

### PR DESCRIPTION
**Pull request by KingkumaArt**
This PR Resprites Mech Drills, PKA, Plasma cutter and Clamp. Stuff like scanner, RCD, and wiring arent being touched.
Below are the 5 new sprites in the PR.

Drill2

## Why It's Good For The Game

A lot of the mech tool sprites have some crust to them, but I felt a single pr redoing every single one might be a bit broad strokes (and also eat up a lot of free time, something I lack right now), so I felt focusing on one subset would be a good idea, for now. 

As for why they're changed to how they are, the drills, PKA, and plasma cutter are functionally upscaled versions of existing handheld mining tools, but some - namely the drills and PKA - have been resprited since the mecha equivalents were added. This adds consistency between the two, and makes them more clearly resemble their prior, human-sized variant. (This is also why the plasma cutter's sprite hasn't changed much, as its already near-identical.)

## Changelog

:cl:
image: Resprited mech drills, plasma cutter, pka and cargo clamp.
/:cl:

### CODE REVIEW

**Comment by MTandi** [comment]
Comparison

image

**Comment by KingkumaArt** [comment]
Apparently github doesnt keep pngs transparent upon upload so heres one with a green background for contras
DrillGreen
t.

**Comment by KingkumaArt** [comment]
> Comparison

Oops thats some white pixels on the clamp lemme fix that

**Comment by necromanceranne** [comment]
I love how chunky they are

**Comment by KingkumaArt** [comment]
> I love how chunky they are

I just got off doing a 3d modeling contract for a construction firm so i've been doing a lot of work with excavators and the like lately.  The tools definitely aren't precision instruments, thats for sure!

**Review by Wallemations — CHANGES_REQUESTED** [review]
I like their shapes and general designs but something about the execution on the palettes makes me pause.
I can't tell whether or not you used any hue-shifting, I think.
Whatever the root cause, the main issue I have with these is their outlines, which just feel far too desaturated, which makes them kinda meld together. The complete lack of outline on the drills also isn't great.

**Comment by KingkumaArt** [comment]
> I like their shapes and general designs but something about the execution on the palettes makes me pause. I can't tell whether or not you used any hue-shifting, I think. Whatever the root cause, the main issue I have with these is their outlines, which just feel far too desaturated, which makes them kinda meld together. 

Do you mean the outlines are too dark? As for the palletes, most of the colors were taken from the pre-existing sprites for the tools they replaced. Is there a "proper" (for lack of a better term) pallete I can/should use?

**Comment by KingkumaArt** [comment]
Drill2
New version, better outlines

**Comment by Dorsisdwarf** [comment]
Old plasmacutter still looks better than the updated version but the rest of these are wonderful 👍

**Comment by KingkumaArt** [comment]
Bumping to avoid the dreaded stale tag

**Comment by KingkumaArt** [comment]
Drating until the reviewer isnt in the middle of dealing with the biggest and probably most hotly debated pr in tg history

**Pull request merged**
