### PR TITLE
Slimes start at 700 nutrition

### LINKED ISSUE #35060: Slimes need more food than before
[Round ID]:  82699

[Reproduction]: 
As opposed to usual, where a slime needs 2 monkeys(or 3 if left alone for large period of time), it appears that the slimes need around 3-4 in order to split.

### PR DESCRIPTION
**Pull request by GLACoding**
Slimes will now take 2 monkeys again to split.

Fixes #35060

### CODE REVIEW

**Comment by Repukan** [comment]
It's not a fix, it's literally a feature.

**Comment by Buggy123** [comment]
Everyone who says "nerf xenobio" remember it takes them literally 30 minutes minimum to get to anything good.

**Comment by davethwave** [comment]
And at least within those 30 or so minutes something tragic usually happens that makes all that work useless at least 30% of the time.

**Comment by Tlaltecuhtli** [comment]
people that say "nerf xenobio" are also permabanned in game really makes me think

**Comment by Repukan** [comment]
Not an argument

**Comment by ma44** [comment]
TFW you thought this was a powercreep buff but it's an actual fix
👍

**Comment by Bawhoppen** [comment]
Fix is a strong word. The other PR was merged fairly, and this is reverting one of the changes it made.

**Comment by davethwave** [comment]
I think it was meant for the playerbase and not the mobs. The fact that slimes are also hungry being a bug probably should be answered by Coiax since he created the PR responsible for this. Also how Coiax worded the description for the PR made it just sound that it was to make it only for the players to make the chef more useful in my opinion.
#34791

**Comment by Bawhoppen** [comment]
It's possible it was an oversight, but even then, saying it's a fix is kind of pushing it.

**Comment by 81Denton** [comment]
Good fix

**Review by Cyberboss — APPROVED** [review]

**Pull request merged**
