### PR TITLE
Makes welders deterministic

### PR DESCRIPTION
**Pull request by Cyberboss**
>prob

### CODE REVIEW

**Comment by Incoming5643** [comment]
On average a buff to welder ignition timers. There is over a 60% chance that a welder would lose a fuel before 20 ticks.

**Comment by Cheridan** [comment]
This seems like a really weird way to track fuel consumption. So if I turn my welder on, do something really fast, and then turn it off quickly, it won't use any fuel?

**Comment by CosmicScientist** [comment]
I always thought fuel was used up *on usage*, why is it on probability or potentially a timer? Surely it's more fun and intuitive to ~attack spessmen~ weld down a consistent number of walls?

**Comment by Poojawa** [comment]
Technically, it just being on consumes fuel, but since welding fuel is a liquid and not something like, say, a flamethrower's gas tank, it'd just be a tremendous pain in the ass for Engineering to have to drag a full welder rig to fight the blob or w/e.

**Comment by Incoming5643** [comment]
@CosmicScientist It's both. Actions cost fuel, but just leaving it on also costs fuel.

**Pull request merged**
