### PR TITLE
Shadowling Update V

### PR DESCRIPTION
**Pull request by ghost**
Changes:
- A new spell type has been added, /self. This spell will only target the user and is made for ease of creation of new spell types made to be self-centered.
- Many shadowling abilities have been refactored into "self" spells.
- Spells now play sounds automatically if they have an assigned sound.
- All shadowling abilities now require the user to be human.
- Many shadowling ability cooldowns have been reduced.
- Shadowlings no longer possess Enthrall before hatching.
- Enthralling fluff messages now center around the shadowling placing their hands onto the target's head rather than soulfully staring into their eyes with love and care.
- Ascendant Broadcast has been removed.
- Shadowling clothing/items now have icons on the HUD to better represent that they exist. They are mainly just darkened versions of other icons.
- Destroy Engines is now removed after use.
- The Shift Nerves button now has an icon.
- Regenerate Chitin has been renamed to Rapid Re-Hatch to better reflect its use.
- Dethralling surgery's final step now requires a flashbulb, penlight, or flashlight.
- Dethralling surgery now produces a shadow tumor at the target's location.
- New item: shadow tumors. Have a tech origin of 4 biological. Dies in the light and heals in the dark.

### CODE REVIEW

**Comment by Zilenan91** [comment]
Ehh, the ascendant broadcast was kinda nice to be honest. It was VERY satisfying hearing everyone scream oh shit once you ascend.

**Comment by PKPenguin321** [comment]
:+1: to everything but removing ascendant broadcast, that shit was hilarious
Everything else is hella cool
Suggestion: Allow ascendants to hear deadchat so they can embrace the salt

**Comment by Robustin** [comment]
All well and good, still would like to see a modest reduction on enthrall time.

I've played Sling several times and its never pleasant to spend 80% of your round channeling a conversion spell because recent converts turn on their lights and you have to bail out before they kill you by accident, or they bump you while enthralling, etc... it's holding Shadowlings back (I still haven't seen one win in months in a regular round) and makes for mind-numbing gameplay.

**Comment by Xhuis** [comment]
I have actually implemented a way for creative shadowlings to enthrall much more quickly.

**Comment by Xhuis** [comment]
New in this commit:
* Destroy Engines is now removed after use
* Shadowling clothing items now have item icons to represent their existence (they're mainly just recolors)

**Comment by KorPhaeron** [comment]
I'd suggest that destroy engine gib at least one thrall so there is an actual cost, otherwise they can just use their revive power, can't they?

**Comment by Bawhoppen** [comment]
You should make ascendants killable imo.

**Comment by Xhuis** [comment]
@Bawhoppen # NO.
@KorPhaeron My main gripe with destroying the thrall entirely is that unless proper preparations are made they're out of the round permanently, and I don't want to do that.

**Comment by Cookiesndip** [comment]
> Shadowlings no longer possess Enthrall before hatching.

Euuuuuuuuuuugh. Almost every sling round as a sling I've either been very close to victory (shuttle arrives at Centcom), or victorious as a human, since I've gotten used to them (within the past couple months). Hell, yesterday my teammate hatched instantly and was discovered 4 minutes in, and we still eked out a victory by knocking out comms, and taking out people heading to arrivals from the junction next to the bridge. However, this would be utterly impossible if I had to hatch to enthrall, since I would never be able to get a base of thralls before starting to clash with security, and I probably would have died in maintenance somewhere, to the validhunters.

Unless you're going to sharply lower the enthrall time, it's just a massive nerf to shadowmemes. Lowering the CDs doesn't really help when you have torches/glowshrooms/flares/bounced radios on every fucking person the moment shadowmemes are called out.

Basically, without pre-hatch enthralling the shadowling forces themselves into a ridiculously vulnerable state that screams 'valid', as one of 2-3 antags in the game, with no real combat resources and a long enthrall time. To exacerate this, you have hordes of validhunters in maint, so even if you catch someone, no matter where you enthrall them the chances you're discovered is fairly high. Pre-hatch enthralling is _required_ to generate a modicum of manpower for defense and offense.

Also: perhaps it would work if you kept pre-hatch enthralling the way it is currently, but also decrease the enthrall time in shadowmeme mode to incentivize hatching.

Lastly, for chrissakes give shadowlings perfect NV instead of syndie NV. Not being able to see doors is ridiculous when you spend most of your time in maint (hurray for memorization).

> Removing ascendant broadcast.

Why? Ascendants are basically mini versions of Nar Nar. That's just fun removal.

**Comment by Bawhoppen** [comment]
@Xhuis THEY CAN BE REALLY STRONG, BUT IF YOU FIRE ENOUGH CRUISE MISSILES AT SOMETHING IT SHOULD DIE

**Comment by Xhuis** [comment]
@Bawhoppen They technically are killable. They just have around 100,000 health and don't take damage from most things.

**Comment by Anonus** [comment]
Shadowlings do have perfect NV, the button to mess with it just doesn't have an icon.

**Comment by Xhuis** [comment]
@Cookiesndip Night vision can be tweaked via action button. Pre-hatch enthralling almost always results in bad gameplay and, no matter how much I myself want it, the players asked me to remoev it, so I'm removing it.

@Anonus The button will have an icon soon.

**Comment by Xhuis** [comment]
Debating making shadowlings talk in Chiller.

Y/N?

**Comment by GunHog** [comment]
Too hard to read.

**Comment by Bawhoppen** [comment]
SnowCaps or bust as the font

**Comment by Xhuis** [comment]
Conflicts fixed. Icon added for the Shift Nerves button.

**Comment by Zilenan91** [comment]
yeah they should be in regular font, that one there is really hard to read.

**Comment by Xhuis** [comment]
Shadowlings will not speak in Chiller.

**Comment by Dorsisdwarf** [comment]
Don't asc. shadowlings have a tag which makes them take no damage whatsoever? Thereby making them actually unkillable without shenanigans

**Comment by Xhuis** [comment]
No, ascendant shadowlings don't have godmode.

**Comment by Bawhoppen** [comment]
You should atleast let singulos kill them again, and be way less invincible even if still ridiculously OP

**Comment by Anonus** [comment]
Ascended shadowlings do have an infinite force threshold and infinite health, though. No reason not to slap godmode in there too.

**Comment by GunHog** [comment]
Do not change Ascendants. They are the end-of-round reward. Nothing should kill them, for they are gods, like Nar-Sie. That is what they are. A playable version of Nar-Sie.

**Comment by Bawhoppen** [comment]
>gods unkillable

atleast try

**Comment by KorPhaeron** [comment]
For once I actually agree with Bawhoppen. Making it incredibly hard to kill but still killable would allow for cool moments where mortals get to take down a god with a dozen mechs.

Nar-Sie should also be killable.

**Comment by Cookiesndip** [comment]
Still though, removing pre-hatch enthralling is a pretty hefty nerf to antags that hardly ever win. At least decrease enthrall times somewhat.

**Comment by Xhuis** [comment]
As I said, creative shadowlings can enthrall much faster now.

**Comment by Zilenan91** [comment]
Yeah can't they directly implant the black tumors into peoples heads now if they surgerize their thralls?

**Comment by Xhuis** [comment]
Exactly.

**Comment by Anonus** [comment]
Uh, how is that faster? Removing the tumor will dethrall your thrall and then you have to rethrall them and put a tumor in someone, which is definitely not faster.

**Comment by Anonus** [comment]
Also, shadowling is shit and likely to remain so until the gameplay changes from "hide in maint, thralling people silently" to something that actually interacts with the station in a way other than stunning and thralling crew or running the fuck away from crew.

**Comment by Xhuis** [comment]
@Anonus What do you suggest?

**Comment by Bawhoppen** [comment]
remove stuns from combat entirely

**Comment by Anonus** [comment]
I'm not suggesting I'm giving feedback, good luck with fixing it.

**Comment by Boredone** [comment]
So, question about the tumor handling whether someone is a thrall or not now.
What happens if a thrall gets cloned? Might be obvious code wise, but I'm not that good at reading it.

**Comment by Xhuis** [comment]
The shadow tumor _should_ be transferred with the cloning. Let me test this locally.

**Comment by Xhuis** [comment]
New in the latest commit:
* Enthralling now takes 21 seconds, 31 for loyalty-implanted targets. (Down from 30 and 45)
* Dethralling surgery has been re-added
* The final step in dethralling surgery is now performed with a flash, penlight, or flashlight
* The final step in dethralling surgery now produces a shadow tumor after successful completion

**Comment by Robustin** [comment]
Stop stop I can only get so erect

**Comment by Shadowlight213** [comment]
@Xhuis could you maybe remove the shadowling check for veil lights? I had a lot of fun giving it to myself as a ghost and spooking the station, but It wont let me use it anymore.

**Comment by Xhuis** [comment]
@Shadowlight213 That's a bit of an odd request, but okay.

**Comment by Xhuis** [comment]
Merge-ready.
@Razharas

**Comment by Robustin** [comment]
I'll throw out another Feedback comment I made before (Xhuis you're a cool guy but I chuckled when you passive-aggressively told me I should have raised some of these issues in your feedback thread when almost all of my thoughts on Ling are expressed as like the 2nd post in your thread):

In return for ramping up SLing power (shorter conversions, reduced CD's), give them one end-game objective once they have hit the 15-thrall requirement. It could be a dominator-style ritual site where a rune/portal/beacon/relic/whatever charges the Sling(s) for ascendance but must be protected from crew intervention, or even a simpler "Make X% of the station dark" so that the Sling/Thralls actually have to leave maint and engage in some semi-overt activity to succeed, etc. etc. this would be fodder for a future update but I agree that even after this update, Sling will not reach its full potential as long as it has such a bland win condition.

**Comment by Zilenan91** [comment]
That's actually a decent idea. Currently, there's no point for thralls going out of maint to smash lights, it just screams SHADOWLINGS. If slings needed a certain portion of the station dark (like 70 or 80%) this could be doable. A dominator type of thing could work but it would have to be way shorter than gang ones.

**Comment by Zilenan91** [comment]
Just had a round where Dante was a sling and he was absolutely spamming his abilities. If we lower them any further slings will have ridiculously low CDs for how good all their abilities are. They'll be totally uncatchable.

**Comment by Robustin** [comment]
45s for jaunt is a fair compromise. Zilenan under no circumstances can current Slings "spam" anything, and Zaross got crushed that round along with most of the thralls. It was a complete rout and was proof that Slings are not at risk of snowballing. 

30s does seem too low for jaunt though, at 30s it runs into the possibility of being able to endlessly chain CC and escape spells to be a unecessarily hard to kill. On the other hand 60s is unreasonably burdensome since its also a travel spell, I can say first hand its a nightmare when you need to jaunt to get past a door you dont have access to/cross between maint sections/etc. and then you have to hide out for 60 seconds because if a validhunting party finds you during that time you're dead 90% of the time.

**Comment by Zilenan91** [comment]
You really didn't see what Zaross was doing, did you. Dude it was ridiculous, whenever anyone found him he'd shit out smoke, glare, walk away, they'd run away, a group would find him again, he'd jaunt away, then he'd shit out smoke, then he'd glare... he got no thralls in this entire process but it was really really stupid.

**Comment by Bawhoppen** [comment]
the fact that slings have ranged parasting is kind of silly tbh

**Comment by Anonus** [comment]
He got exactly one thrall, but yes, that is what I'm talking about when I say they need to interact with the crew in ways other than leaving whenever aggressed and instantly stuncuffing anyone they see enter their screen.

**Comment by KorPhaeron** [comment]
Problem with the way our movement/combat/communication is set up is that you gotta down them/silence them more or less in one hit or they run away screaming.

**Comment by Bawhoppen** [comment]
@KorPhaeron and how do we plan to fix THAT?

**Comment by KorPhaeron** [comment]
@Bawhoppen 

Fuck if I know. It's why changeling has been unworkable for years

**Comment by Bawhoppen** [comment]
@KorPhaeron the best solution, but simulataneously the most hated would be the bay solution

**Comment by Zilenan91** [comment]
Most hated? Not really. Bay combat is so lethal because they aren't expected to be in combat all the time like we are. We could always port it and over a period of time, using the feedback gained, nerf parts of it so it's not ridiculous.

**Comment by Bawhoppen** [comment]
@Zilenan91 I mean the RP solution.

**Comment by Zilenan91** [comment]
that's not gonna happen

**Comment by Bawhoppen** [comment]
Why do you think I said the most hated?

**Comment by Dorsisdwarf** [comment]
Bay's RP is shitty too, because they're projecting 21st century office values into 25th century alien frontiersmen.

therefore we have the deepest lore

**Comment by Zilenan91** [comment]
Bay also enforces their RP with a set of rules, not a set of mechanics, and that's why most people don't like playing there. Hell, that's why I like Lifeweb so much from an RP perspective, it's got enough mechanical depth, and they're well balanced enough to make you constantly be doing something and organically moving around and talking to people to get these needs satisfied.

**Comment by Razharas** [comment]
No idea about the balance implications of this but self spells sound nice

**Pull request merged**
