### PR TITLE
Remove problem matchers from Build All

### PR DESCRIPTION
**Pull request by stylemistake**
## About The Pull Request

Fixes the following:

deb6eb2bf897158a7eca1bf69dde466c

The better fix would be to make dm matcher smarter, but I simply plugged the hole for now.

### CODE REVIEW

**Comment by optimumtact** [comment]
build our own build tool he said it wouldn't be a problem he said

**Comment by SpaceManiac** [comment]
No problem matchers at all seems worse to me than a problem matcher that is occasionally overzealous.

A better solution might be prefixing the build output, e.g. `[tgui] ` for tgui lines and `[dm] ` for dm lines, and building that into the problem matchers.

**Comment by stylemistake** [comment]
Or make problem matcher a bit more specific, so that it wouldn't match non-dm problems or at least wouldn't match ISO dates as problems.

**Review by Cyberboss — CHANGES_REQUESTED** [review]
Improve, don't remove for this one.

**Comment by stylemistake** [comment]
Nobody wants to improve it.

**Pull request closed without merging**
