### PR TITLE
Unfinished - cryo tube UI

### PR DESCRIPTION
**Pull request by Aranclanos**
UNFINISHED WORK
Creates a new subtype of the cryo tube and the datum/browse.
This cryo tube subtype will use a classic html string, looking exactly like nanoUI and updating properly without stealing focus.
The cryo tube will create the browse datum at New(), and this one will have a list of the mobs using it, to send the update string.
Due to being unfinished, the datum will steal focus and open again if the user closes the window.
Updated cmmon.css with nanoUI-like style.

The main reason this is unfinished is because updating the window by sending the huge string again and again is unacceptable when web templates are a thing.

I'm opening the PR to get opinions and some comments, abusing a bit the PR system, this shouldn't be merged at all, I'm looking for your input.
I don't know if I should start from 0 or continue from here, at this point im really burned out after 13 hours. Close this PR after a week or something, but leave it open for a while to get some attention.

### CODE REVIEW

**Comment by Aranclanos** [comment]
And sorry for abusing the PR system

**Comment by RemieRichards** [comment]
@Aranclanos it's ok, you mean well.

**Comment by HoaxIT** [comment]
The current UI works fine right? Why change away from an perfectly working NanoUI?

**Comment by Aranclanos** [comment]
nanoUI has a lot of issues, when you log in you get all possible templates, even if you're not going to use them, sometimes the buttons don't respond, it fails to show for some players on some specific setups, making it not work at all, and finally, it refreshes way too fast even if there isn't a need for an update.
But all of those issues aren't that big of a deal, the main problem is that it's just unmaintainable.

So no, the current UI doesn't 'work fine' and it isn't 'perfectly working'

**Comment by HoaxIT** [comment]
Thanks for the clarification :+1:

**Comment by Aranclanos** [comment]
👌

**Comment by optimumtact** [comment]
nanoui is master race :x:

**Comment by Aranclanos** [comment]
I'll kill it one day 👌

**Comment by Razharas** [comment]
ANd then they lived happily ever after

~ The End ~

**Pull request closed without merging**
