### PR TITLE
Updates rhumba beat to be more different from GBS

### PR DESCRIPTION
**Pull request by vuonojenmustaturska**
I'm gonna need to make forced dancing a status effect after I get home.

:cl: Naksu
admin: Rhumba beat is now more than renamed GBS
/:cl:

### CODE REVIEW

**Comment by Cyberboss** [comment]
excuse me tgstation-server?

**Comment by Cyberboss** [comment]
oh wait, why does this have an admin cl?

**Comment by RandomMarine** [comment]
Because it's a badmin-only virus I guess???

**Comment by vuonojenmustaturska** [comment]
^ that

**Comment by Bawhoppen** [comment]
I still love Line 16.

**Comment by Iamgoofball** [comment]
Cuban Pete must live on ;_;7

**Pull request merged**
