### PR TITLE
RnD consoles can no longer be screwdrivered to reenable research

### PR DESCRIPTION
**Pull request by TiviPlus**
## About The Pull Request

https://github.com/tgstation/tgstation/pull/49899 was easily circumvented by this

https://tgstation13.org/phpBB/viewtopic.php?f=10&t=25889 This is a Orange mandate PR

## Changelog
:cl:
balance: RnD consoles can no longer be screwdrivered to reenable research
/:cl:

### CODE REVIEW

**Comment by trollbreeder** [comment]
Incremental changes bad. Wait until experiscience fully comes out.

**Comment by Fikou** [comment]
cant we wait till experisci is out

**Comment by EgorDinamit** [comment]
What's the point of doing so anyway? You are making another useless PR just like Arcane did.
It will just make people make a new console board/raid bridge/raid a goddamn charlie station/take a spare board from tech storage/etc.

**Comment by ArcaneMusic** [comment]
> 
> 
> What's the point of doing so anyway? You are making another useless PR just like Arcane did.
> It will just make people make a new console board/raid bridge/raid a goddamn charlie station/take a spare board from tech storage/etc.

Now in my defense, there was a very valid reason for my PR, which was to get players into the habit of going to the bridge for research nodes.
(If I wanted to whole-ass it, I would have moved the R&D Console board to the computer consoles technode as well as this.)

**Comment by Shadowflame909** [comment]
Can it still be destroyed?

If so you can get the board that way.

If not, then that's major power creep swarmers/morphs/any antag can't destroy science to make the round easier

**Comment by Survivioboi** [comment]
This is a common issue for hippie station too. If people dont have easy access to something, they will just raid or do other, more antagonistic things to achieve the same goal. Alike said before, if people have to go to the bridge, they will just break in and deconstruct the console to get the board the make it in science. You could fix this by giving them bridge access so they can fucking access it, but that likely wouldnt be a good idea. The best idea I can find is just to not merge this and INSTEAD revert the one that made the non research consoles in the first place. Seriously, there is absolutely 0 reason this should exist, both gameplay-wise and lore wise. If the only place research could be researched from is the bridge, a place the scientists didnt have access to, that would be very unefficient due to the fact that either they would have to just bolt the doors open or they would have to open the doors every time someone wanted to research something, or research just wouldnt happen, which would be dumb because the whole history behind the stations is they were made for the EXACT PURPOSE of research, and it would be, as I said, very inefficient if the scientists didnt have access to the only console on the stations. Both that and It would, in gameplay, either encourage antagonistic behavior for ease of access, or nobody would do research, which would be very unfun. Overall this is all just grudgecode, a needless obstacle that shouldnt exist, an annoyance, in other words,

Congrats TG. You fucked yourself.

**Comment by ArcaneMusic** [comment]
Engineers and scientists can still print the board lol

**Comment by Survivioboi** [comment]
Then may I fucking ask why this PR exists if they could still print the board, because they will just print another board.

So basically, this is merged to be a **useless** obstacle, and still doesnt achieve what the old PR was trying to get people to do.

**Comment by MarioWizard119** [comment]
@Survivioboi welcome to tg development code, you’re new here aren’t you? Same thing happened with Medical. Good intentioned changes that end up being half assed to the point where they are pretty much useless or a complete grudge. Just look at the “finished” medical rework, intended to make chemistry less brainless and surgery more viable, but chemistry plays like trekchem with the addition of a few extremely debilitating poisons and surgery has been made even more boring. Oh, and craftable cryo pills are back, because that’s balanced. 

I agree that research should be more decentralized. Research nodes never acted as a good time gate because the “meta” nodes would get bum-rushed round start (t4 parts, advanced mining, and BSBoH), and the others would only ever be researched if the round lasted more than an hour. That and the scientist is a conglomerate of sub departments that don’t have enough substance to be their own job. RnD boils down to click blue buttons until the miners stop nagging. Early game xenobio is like watching paint dry. Toxins is interesting, but once you’ve made one good bomb, you’re done. Nanites were reworked and were supposed to be made independent of RnD, but that was half assed, so it still cannot function as its own department.

Best I can say is if you don’t like the changes, stop playing on tg. Let the server die. Look into its derivatives, or if you’ve got the talent, start your own. They won’t listen, they never did and never will, and they will keep making dogshit changes to the game until tg chokes and dies.

**Comment by ArcaneMusic** [comment]
You are aware that this is part of an actively being worked on science change, right?
If you'd like to talk about the context of this change, please check out the new design documents website to avoid conjecture.
https://hackmd.io/@tgstation

**Comment by optimumtact** [comment]
hippie cannot be compared to /tg/ because hippie is made up of the dregs of ss13

**Comment by adamkad1** [comment]
Still making golems useless and letting antags delet research, crippling the entire station, with just a screwdriver? nice

**Comment by ExcessiveUseOfCobblestone** [comment]
You can help close the gap to make it easier

**Pull request merged**
