### PR TITLE
Lets you tie the Syndicate balloon around your wrist

### PR DESCRIPTION
**Pull request by ghost**
:cl: Xhuis
rscadd: You can now tie the Syndicate balloon's string around your wrist by activating it in your hand. This will prevent you from dropping it. You can repeat the process to untie the string and let you drop it again.
/:cl:

### CODE REVIEW

**Comment by WJohn** [comment]
Why not just make it a sort of glove? Have it take up the hand slot or something.

**Comment by Xhuis** [comment]
The Syndicate balloon's power is restrained only by the fact that you must carry it. Being able to have the balloon equipped while having two free hands would unleash its power and cause the fabric of spacetime to tear.

**Comment by Shadowlight213** [comment]
@Xhuis how would someone else untie it if you die though?

**Comment by Xhuis** [comment]
@Shadowlight213 They wouldn't. Although, I intend to add the ability to snip the balloon from someone's wrist with wirecutters once I find the code for removing cable ties the same way.

**Comment by Fox-McCloud** [comment]
Could just make it an accessory/tie.

Yeah, that's a little weird, but would be more interesting, IMO.

**Comment by Cheridan** [comment]
I like the accessory idea

**Comment by Xhuis** [comment]
Jesus Christ I make a silly PR and you guys get in a debate about its technicality. I'm done with this codebase.

**Comment by duncathan** [comment]
@Xhuis or you could've done what cheri asked and got it merged
You do realize that we don't merge things with concerns from other maintainers, right?

**Comment by Xhuis** [comment]
I hardly count a vague five-word sentence as "concerns", and judging by last year's facehugger fiasco, maintainer concerns are ignored.

**Comment by duncathan** [comment]
If you say so

**Comment by Xhuis** [comment]
All right, now I'm not pissed off and I don't have a massive headache. I still don't want it to become an accessory because then people could just disarm people and whip the balloon onto their jumpsuit so that they have to take the jumpsuit off before removing it rather than just snipping with wirecutters. I also have no motivation whatsoever, so I'm probably not going to continue this.

**Pull request closed without merging**
