### PR TITLE
Makes staff of doors create random mineral doors.

### PR DESCRIPTION
**Pull request by AnturK**
:cl: 
tweak: Staff of Doors now creates random types of doors.
/:cl:

### CODE REVIEW

**Comment by Incoming5643** [comment]
Uranium doors will irradiate you when you go to open them I do believe.

**Comment by Anonus** [comment]
The staff and wand of doors still have the description mentioning wooden doors, and the spellbook has it as well.

**Comment by Aranclanos** [comment]
>using typesof to create anything ever

it will bring problems later on :-1: 
maintainability issues

**Comment by Incoming5643** [comment]
Honestly when it's limited to MINERAL doors it's pretty future proof. Without electronics I can't imagine much in the way of unintended future consequences (beyond the current ones in plasma and uranium).

I mean they open and close, what more could you do with that?

**Comment by AnonymousNow** [comment]
Makes me think that bolts of change should change floors/walls/doors hit into random mineral floors/walls/doors.

**Pull request merged**
