### PR TITLE
Updates Lizard Sprites & New Digitigrade Sprites

### PR DESCRIPTION
**Pull request by thgvr**
## About The Pull Request
Hi.
This pr contains work that is a  collaborative effort between myself, Halcyon, Mqiib and `2cents#8442` for the original leg-work (Ha Ha, Get it?), ultimately finished by myself.

Here's a preview!

image

And here's some side previews!

image

## Why It's Good For The Game

Lizard sprites have not been updated since their inception in 2016. They will now be updated and be much more consistent with everything else.

Signed off by @optimumtact

## Changelog
:cl:
imageadd: Lizards have been resprited, as well as Digitigrade sprites. Please remember to update your colors to account for this.
/:cl:

### CODE REVIEW

**Comment by Rex9001** [comment]
Looks cool! Just 2 questions, will this alter aquatic or any other lizard aguements? and two, will the lizards have that slight glow that they have in your images?

**Comment by thgvr** [comment]
> Looks cool! Just 2 questions, will this alter aquatic or any other lizard aguements? and two, will the lizards have that slight glow that they have in your images?

This doesn't touch any of the spines. I will hopefully work on that in the (near but far) future.

There is no glow. That's the Ambient Occlusion effect on a pure white tile background.

**Comment by Slurge00** [comment]
whats with the square on the legs in the side profile shot? looks weird to me

**Comment by Fikou** [comment]
> whats with the square on the legs in the side profile shot? looks weird to me

thats where the hand overlay goes

**Comment by Fikou** [comment]
> whats with the square on the legs in the side profile shot? looks weird to me

hand overlay

**Comment by thgvr** [comment]
You can't stop me

**Comment by Helg2** [comment]
It looks wrong, it feels wrong.

**Comment by Ebin-Halcyon** [comment]
As beautiful as the day I made you.

**Comment by san7890** [comment]
Are their legs modeled after horse's thighs or something? they're unusually large- that isn't a bad thing but man it's really jarring (i suppose that's the point for digitigrade legs)

**Review by Imaginos16 — APPROVED** [review]
Looks good

**Comment by LukasBeedellCodestuff** [comment]
DAMNN....THEY A BADDIE............

**Pull request merged**
