### PR TITLE
Gets rid of Robustin's garbage hardcoded action button positions

### PR DESCRIPTION
**Pull request by ghost**
**ROBUSTIN, YOU COULDA ADDED, I DUNNO, A PREF WITH WHAT BUTTONS YOU LIKED WHERE**

:cl: More Robust Than You
tweak: Cult dagger / rune action buttons no longer teleport to retarded places
/:cl:

### CODE REVIEW

**Comment by Iamgoofball** [comment]
why are you fucking with the UI design

**Comment by MoreRobustThanYou** [comment]
@Iamgoofball because constipation is less annoying than hardcoded buttons in unusual positions

**Comment by Iamgoofball** [comment]
sounds like a case of the 'tism

these arent normal action buttons, these are using the action button API to easily place screen elements where he wants them

**Comment by Iamgoofball** [comment]
this also serves the purpose of keeping the important always-needed cult buttons far away from the automatically shifting and variable sized equipment action buttons

**Comment by Iamgoofball** [comment]
in short, you're an idiot mrty

**Comment by Robustin** [comment]
@Iamgoofball summed it up but I can make a compromise where if someone unlocks and moves the buttons then they will no longer be re-ordered when you get/lose a new button.

**Comment by Bawhoppen** [comment]
I want verbs back

**Comment by Iamgoofball** [comment]
Never

**Pull request closed without merging**
