### PR TITLE
ebows cannot be purchased under 25 pop

### PR DESCRIPTION
**Pull request by ghost**
well i suppose that makes sense?

https://tgstation13.org/phpBB/viewtopic.php?p=369390#p369390

### CODE REVIEW

**Comment by ShizCalev** [comment]
boooooooooo

**Comment by MrStonedOne** [comment]
Links in pr titles can't be clicked. Please move that to the description

**Comment by Armhulen** [comment]
oh, my bad

**Comment by lzimann** [comment]
We don't really enforce commit messages, but for fucks sake start doing some meaningful commit messages.

**Comment by Armhulen** [comment]
i don't know what to say in them, it's a one commit pr and i'm outta jokes

**Comment by lzimann** [comment]
You can put what the commit actually does, it's not meant to have jokes, it's a description of what is being changed.

**Comment by Armhulen** [comment]
i'll work on it!

**Comment by Repukan** [comment]
Then what?

Remove revolvers too since they can two shot people. Then bombs since it's likely they'll end the round if used to make various breaches. Remove Carp because it's too strong to counter. 

If you want to avoid killing sprees in lowpop you need to remove a lot more weapons. This seems knee jerky tbh.

**Comment by lzimann** [comment]
The only real way to stop low pop killing spree is making it against the rules, no real other way of doing it honestly.

**Comment by MMMiracles** [comment]
why not just go the route of ministation and make loud traitor items cost more TC during lowpop?

**Comment by KorPhaeron** [comment]
@armhulen

We should just add a rule 4a: Repetive killing sprees on low pop stations may result in an antagonist ban

**Comment by Tlaltecuhtli** [comment]
only way to stop low pop murderboning is removing low pop so its ok to murderbone

**Comment by ACCount12** [comment]
+[i ded]

Wait, the tag is already there. Wouldn't hurt to add another one then, this is "i ded" as fuck.

**Comment by Iamgoofball** [comment]
@KorPhaeron people will strawman about what constitutes lowpop in every kill scenario if you do that

+ if you set a specific number, people will argue about that number until the end of days

**Comment by duncathan** [comment]
as a primarily lowpop player I think this is a positive change and I support this PR.

**Comment by Armhulen** [comment]
rule would be way easier

**Pull request closed without merging**
