### PR TITLE
Improves various sprites.

### PR DESCRIPTION
**Pull request by WJohn**
Improves the following sprites:
Shotgun shells, RCD cartridge, speedloaders.

Intelicard and pAI, these are actually animated.

Older buttons.

Easel and canvases.

:cl: WJohnston
imageadd: Improved/resprited AI card, pAI, easel/canvases, shotgun shells, RCD cartridge, speedloaders, and certain older buttons.
/:cl:

### CODE REVIEW

**Comment by PKPenguin321** [comment]
pretty god tier sprites

**Comment by calzilla1** [comment]
Eh,  the shells look like goon station regects, but the intelicard and pai look nice

**Comment by WJohn** [comment]
Our current shell sprites aren't exactly great, either. I guess I could make the gold/silver a bit shinier, that'd be easy to do.

**Comment by WJohn** [comment]
Done. Haven't updated the OP though.

**Comment by anconfuzedrock** [comment]
rcd thing looks a bit weird when the rcd doesn't look anything like that.

**Comment by GunHog** [comment]
Mista Jay is the best! Excellent sprites.

**Comment by TechnoAlchemisto** [comment]
Not a huge fan of the speedloaders, but everything else looks amazing, good work!

**Comment by WJohn** [comment]
Yeah I don't like the speedloaders too much myself, but the current ones aren't good either so bleh. I may redo them again in the future when I know what I want to do with them.

**Comment by GunHog** [comment]
(And mining borgs)

**Comment by pudl** [comment]
I think that the canvas on the easel should be shaded more, and the color of the stand should be consistent with the rest of the wood in game, but the rest is fine.

**Comment by calzilla1** [comment]
I just realized why i hate the shot gun shells.  Because shot gun shells aren't the size of my fist. (Though,  if someone could make it so that the regular sprie is on the ground and your sprite is the in hand sprite that would be cool)

**Comment by WJohn** [comment]
They're not that much bigger than our current ones. But diagonal sprites can usually boast a fair bit more interesting textures and details, in my opinion. Making them the size of a bullet casing on the ground would make them absolutely minuscule.

**Comment by pudl** [comment]
Resprite walls pls

**Comment by PKPenguin321** [comment]
Do not resprite walls

**Comment by TechnoAlchemisto** [comment]
the duality of man

**Pull request merged**
