### PR TITLE
Identity theft with non crew humans

### LINKED ISSUE #8432: Escape with identity can have bad targets
4: Escape on the shuttle or an escape pod with the identity of Adamantine Golem (948), the Assistant while wearing their identification card.

### PR DESCRIPTION
**Pull request by Incoming5643**
As a mercy, if your target doesn't have his ID on him (or never had an ID to start) when you're assigned to steal his identity you won't need to wear an ID to complete the objective.

Have fun DNA stinging the wizard all the same though.

Fixes #8432

### CODE REVIEW

**Comment by PKPenguin321** [comment]
So this just removes the need for the ID in the "escape as" objective?
If so, I like it.

**Comment by Incoming5643** [comment]
You'll still need it if you can feasibly get it. The wording of the objective itself will change to reflect this.

**Comment by Jordie0608** [comment]
Changelog

**Comment by Incoming5643** [comment]
I'd really rather not for this, anyone affected by this will know just by reading their objective that it has changed. If they aren't going to actually read their objectives, they probably aren't going to read the changelog anyways.

Also there's some really dumb subjective meta potential targets could do with the knowledge that they'd be more "appetizing" a target if they lost their ID.

**Pull request merged**
