### PR TITLE
Fixes AI restorer fixing suicided AIs

### PR DESCRIPTION
**Pull request by Cyberboss**

### CODE REVIEW

**Comment by CPTANT** [comment]
I don't really see this as a fix, because suiciding as an AI is different from suiciding as a human. Sometimes laws means that an AI has to self terminate, I think it is dumb to punish them for that.

**Comment by Ratvar** [comment]
Off your own APC if you want to suicide in nonpermanent manner. Still suicide, amirite.

**Comment by Anonmare** [comment]
@ratvar New players aren't always going to know that, plus the law might say that you must suicide *immediately* and dying by power drain doesn't count as immediate.

**Comment by kevinz000** [comment]
What they said.

**Comment by Ratvar** [comment]
Sorry for language, i am russian.
@Anonmare The same way new players won't know about suicide command, why new player got AI without knowing how AI die.  You also should think about normal people loyaled with syndieimplant ordered to "suicide immediately by biting your tongue off so nobody can clone you cause this is ooc mechanic for leaving round and i woud like you to go permanently thank u kyss"-same thing, right? You can insert their brain into MMI ? You also can load totally "new" AI into posibrain, no change.
Forcing other players to abuse OOC mechanics is shitty thing and should be no-no. I myself would say that offing APC is as fast as I can.

**Comment by MoreRobustThanYou** [comment]
how about fixing ai restorers so they can fix EI Nath'd AIs

**Comment by KorPhaeron** [comment]
AI suicide and human suicide are different for reasons cptant outlined

**Pull request closed without merging**
