### PR TITLE
fixes admins being able to destroy stuff by throwing ghosts around because they're assholes

### LINKED ISSUE #39846: a whole new level of adminbus
You can use buildmode's telekinesis to throw ghosts at stuff.
*And break stuff.*

**oh god no**

the saga of ghostbusting: https://imgur.com/a/rk5miaG
[~12mb and looks ugly af because of compression]

lite version of the gif above

~~this is too good to be fixed~~

### PR DESCRIPTION
**Pull request by Iamgoofball**
fixes #39846

next time admins dont report bugs can we remove their tools from the code

### CODE REVIEW

**Review by ninjanomnom — APPROVED** [review]

**Comment by ninjanomnom** [comment]
It's not really a bug that needed reporting and we discourage admins from reporting bugs that only happen due to badmining. Ghosts not having a throw force makes sense though regardless.

**Comment by Anonmare** [comment]
Fun removal

**Comment by ninjanomnom** [comment]
You can edit the throw force yourself if you must

**Comment by PKPenguin321** [comment]
I will never not be amused by how paranoid goof is of admins

**Comment by ExcessiveUseOfCobblestone** [comment]
> he doesn't know we can varedit stuff to be invisible to players and even other ghosts then throw that very same item and *gasp* even edit the throwforce

This is an okay fix since it doesn't really add anything for the sake of btfoing badminnery, I just second PKP in the fact that he's absolutely off his rocker.

**Pull request closed without merging**
