### PR TITLE
Removes the ghost chair config

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
An outdated config from I think 2012 which believe it or not was a compromise to stop massive community drama and a downstream revolt.

/tg/ hasn't had this on for 6 years now, it's a silly thing to still keep around.

### CODE REVIEW

**Comment by KorPhaeron** [comment]
Assigning MSO because it's a config update, and I know he does not appreciate options being removed without his input

**Comment by praisenarsie** [comment]
brb getting hippie to enable ghost chairs in config

**Comment by arsserpentarium** [comment]
just return chair rotating.

**Comment by optimumtact** [comment]
>implying we care about hippie

good one narsie

**Comment by MrStonedOne** [comment]
I've used this config for events back when i actually ran them.

We already have a funverbs var on ghosts for when they can do things like flicker lights. Just make ghost chair rotation check that. Keeps the functionally around for memes and events and wizards, and editing a var on ghosts (or even just triggering the event) is much easier then a config entry for admins to use anyways

**Comment by GuyonBroadway** [comment]
SO your line of thinking here is that something you added that means you don't have to use a thing but others can means you should remove it because you weren't using it despite others using it...

**Comment by duncathan** [comment]
I use ghost chairs on my servers when I play but I'd be perfectly happy with mso's proposal

**Comment by ninjanomnom** [comment]
How could you suggest removing this. mso's suggestion seems fine.

**Comment by Cyberboss** [comment]
Keep or change

**Pull request closed without merging**
