### PR TITLE
Adds edgy suicide sound effects

### PR DESCRIPTION
**Pull request by Tacolizard**
:cl: Tacolizard: CRAWLING IN MY CRAWWWWL
add: Committing suicide by shooting yourself now plays edgy memes.
/:cl:

it will play either a crawling in my skin meme or an ooo watcha sayyyy meme.

someone suggested this on the forums because apparently /vg/ does it.

### CODE REVIEW

**Comment by Difrit** [comment]
Mass Ceres suicides will now be even better

**Comment by Anonmare** [comment]
https://www.youtube.com/watch?v=eCiFO7qV54E

**Comment by KorPhaeron** [comment]
Feels like a cheap OOC joke we will wonder why we added in 2 months

**Comment by dannno** [comment]
fucking no, dude

jesus

**Comment by Chronitonity** [comment]
yikes

**Comment by Jordie0608** [comment]
@KorPhaeron We don't have to wonder about what we don't merge.

**Pull request closed without merging**
