### PR TITLE
Buffs the station's electrolyte count

### PR DESCRIPTION
**Pull request by Iamgoofball**

### CODE REVIEW

**Comment by Supermichael777** [comment]
my thirst is kill.
make this real and have it make your heart explode if you od

**Comment by Niknakflak** [comment]
:-1: meme

**Comment by Zilenan91** [comment]
You really just ctrl f'd every source of water in the code and replaced it with brawndo huh

**Comment by Iamgoofball** [comment]
like outr the toilanetr?

**Comment by JJRcop** [comment]
@Zilenan91 Ctrl+H mass replace no further action required

**Comment by Iamgoofball** [comment]
actually it took a lot of extra work to fix icon names and shit

**Comment by phil235** [comment]
@Iamgoofball Stop posting useless PR please.

**Pull request closed without merging**
