### PR TITLE
Enables CHECK_TICK'd find_references outside of TESTING

### PR DESCRIPTION
**Pull request by Cyberboss**
Related #26568

### CODE REVIEW

**Comment by optimumtact** [comment]
for what purpose, you only need that when you're actively doing debugging

**Comment by Cyberboss** [comment]
Yeah but there's only so much debugging you can do yourself. If we really want to clean out obscure mob references we need to check this shit on live occasionally.

**Comment by Fox-McCloud** [comment]
if by "heavily increase server load", you mean, "make the game literally unplayable for 30 minutes", then...yeah.

**Comment by optimumtact** [comment]
Fox outta nowhere, who are you responding to?

**Comment by Jordie0608** [comment]
This shouldn't be getting run on a live server, it seizes up DD and prints every result to world.

**Comment by Fox-McCloud** [comment]
@Cyberboss

**Comment by optimumtact** [comment]
He never said "heavily increase server load" though so it was just a very confusing comment

**Comment by Jordie0608** [comment]
It's reference to https://github.com/tgstation/tgstation/pull/26569/files#diff-7664a9b9849fbd5b5d688654469b26d9R259

**Comment by optimumtact** [comment]
at last I truly see

**Comment by duncathan** [comment]
no god no wtf this is not for use on live my guy

**Pull request closed without merging**
