### PR TITLE
fixes combat gloves plus not having a sprite

### PR DESCRIPTION
**Pull request by Fikou**
## About The Pull Request

combat glove plus used a sprite that doesnt exist i replaced it with black gloves

## Why It's Good For The Game

invisible weapon bad

## Changelog
:cl:
balance: combat gloves plus are no longer invisible
/:cl:

### CODE REVIEW

**Comment by Shadowflame909** [comment]
Lower the TC or keep it because I need my stealth Krav Magna gloves

The downside to this is that you cant have krav magna with cqc. Only one martial arts at a time. And Krav Magna is clearly the weaker kung fu.

Thus, this is not epic.

**Comment by Fikou** [comment]
> Lower the TC or keep it because I need my stealth Krav Maga gloves

what do you need stealth for youre a nukie idot gay

**Comment by Shadowflame909** [comment]
Because War Ops is becoming its own mode and stealth is the main course.

Clown needs to leg sweep and throat punch the captain.

A good reason for why the stealth icon was intended.

**Comment by PKPenguin321** [comment]
Ops didn't have the option to declare war for the better part of their existence and stealth was not the dominant strategy for the majority of that. (Element of surprise != stealth)

**Comment by Fikou** [comment]
> Because War Ops is becoming its own mode and stealth is the main course.
> 
> Clown needs to leg sweep and throat punch the captain.
> 
> A good reason for why the stealth icon was intended.

bruh black gloves arent something 100% suspicious they are literally just black gloves that secman can get also its not intended it literally uses a sprite that doesnt exist giaojhdfhsfh

**Comment by actioninja** [comment]
go away shadowflame

**Pull request merged**
