### PR TITLE
Adds genuine cat fur products

### PR DESCRIPTION
**Pull request by Thunder12345**
:cl: Thunder12345 and Improvedname
add: You can now turn severed cat tails and ears into genuine kitty ears
add: Cat tails can now be used to make a cat o' nine tails, similarly to the liz o' nine tails.
/:cl:

Cat o' nine tails is identical in fuction to the liz o' nine tails, and the kitty ears are identical except the description.

### CODE REVIEW

**Comment by Penguaro** [comment]
Bye bye Runtime...

**Comment by PKPenguin321** [comment]
Top ten test features to test the tattoos system that went way too far

**Comment by FantasticFwoosh** [comment]
The tatoo's were a front and something that was later mentioned to not even be possible or planned.

**Comment by improvedname** [comment]
THUNDER I WANTED TO DO THIS FUCK YOU

**Comment by improvedname** [comment]
YOU STOLE MY IDEA REEEEE

**Comment by Thunder12345** [comment]
@Penguaro You need the ears and tail off a catgirl, Runtime won't do. If I let you use just any old cat it would devalue the goods.

@improvedname I'm pretty sure I came up with it first but okay

**Comment by Grazyn** [comment]
>@Penguaro You need the ears and tail off a catgirl, Runtime won't do. If I let you use just any old cat it would devalue the goods.

Then you should change the description to "fashioned from real cat people" and not "cats" for consistency.

**Comment by KorPhaeron** [comment]
@tgstation/commit-access 

I'm inclined to close this because

A) I'm sick of the stupid catgirl PRs in general

B) This isn't something I can realistically see people doing while not antag, since it requires killing or maiming other players

Any second opinion?

**Comment by Thunder12345** [comment]
A) The removing the ears/tail thing is already there, this just adds a couple of silly things to do with them

B) I've seen non-antags de-tail lizards before, also see above, this is nothing to do with removing these things, only something to do with them

**Comment by lzimann** [comment]
"sick of catgirl prs"
well this is the path you chose
about the pr, don't care!

**Comment by DaxDupont** [comment]
B) I've seen non-antags de-tail lizards before, also see above, this is nothing to do with removing these things, only something to do with them.
Yup, sec/captains tend to do this to really shitty lizard players and whip them with their own tails. 
That or attach them to shitty human greytides.

**Comment by optimumtact** [comment]
god retreated from earth in fear of what he had created

**Comment by Grazyn** [comment]
@KorPhaeron you can operate on cloned bodies, suicides, volunteers etc. so it can be realistically used by non antags. Also you can't dismember ears or tails, you need surgery, and surgery won't hurt or kill the catgirl. At most it's an IC issue and conflict between catgirls and humans which results in forced surgery doesn't require either part to be an antag.

**Comment by improvedname** [comment]
Cat tail weapon thingy is litteraly the same as a lizard but different tail so it wouldnt be that big of a deal

**Comment by Thunder12345** [comment]
That's a fox you silly

**Comment by improvedname** [comment]
juice-pulp-ejector

**Comment by AnturK** [comment]
Chill with the image spam please.

**Comment by octareenroon91** [comment]
Export datums?

**Pull request merged**
