### PR TITLE
Remove x-mas trees

### PR DESCRIPTION
**Pull request by lzimann**
Down with x-mas... trees, because it's almost february and they are still there

~~Didn't touch birdboat/mini because of a pathing issue(and i got lazy)~~ No issue, went and removed from those aswell.

### CODE REVIEW

**Comment by Zilenan91** [comment]
T H E   M A N   W H O   K I L L E D   C H R I S T M A S

**Comment by Incoming5643** [comment]
Get the festivus polls too.

The santa suit on the wizard ship is a judgement call, I love watching santa kill people any time of the year

**Comment by lzimann** [comment]
Oh fuck forgot about those. TO THE MAP EDITOR AGAIN

**Comment by duncathan** [comment]
:-1: christmas never ends

**Comment by Cheridan** [comment]
there's a restaurant in town, they keep a christmas tree up all year. but they decorate it different. like for valentines, they'll put pink ribbons and hearts on it. we should do that. how fun

**Comment by Nienhaus** [comment]
@Cheridan Which one?

**Comment by tedward1337** [comment]
MAD MAN

**Pull request closed without merging**
