### PR TITLE
Reverts clock-cult.

### PR DESCRIPTION
**Pull request by Iamgoofball**
@optimumtact

### CODE REVIEW

**Comment by evsey9** [comment]
needs a testmerge

**Comment by Kromgar** [comment]
Lets get in shadowling reborn

**Comment by evsey9** [comment]
💯💯💯💯💯💯 lit af

**Comment by kevinz000** [comment]
nya

**Comment by evsey9** [comment]
~~~

**Comment by obscolene** [comment]
the only goof pr worth pulling

**Comment by kevinz000** [comment]
il pull you

**Comment by evsey9** [comment]
im a coder and in my professional opinion this needs a testmerge

**Comment by Iamgoofball** [comment]
BIASED

**Comment by evsey9** [comment]
Iamremoveratvarball

**Comment by evsey9** [comment]
Reopen this or I will ddos your server

**Comment by evsey9** [comment]
😠😠😠😠😠😠😠

**Comment by Kromgar** [comment]
Joan is biased though for real

**Comment by evsey9** [comment]
goof for code maintainer 2k17

**Comment by PKPenguin321** [comment]
Do it properly and I'll testmerge it for a round to trigger Joan :^)

**Comment by evsey9** [comment]
Bring back poo

**Pull request closed without merging**
