### PR TITLE
Resprites soft caps

### PR DESCRIPTION
**Pull request by Imaginos16**
## About The Pull Request
Does what it says on the tin! It redoes the look of all soft caps flipped from the front...
image

...And the back!
image

(for the record if you notice some weird yellowish pixels showing up that's the character's hair clipping through the hat lol)

## Why It's Good For The Game
Resprites are good, and these are an improvement from a previously old sprite!

## Changelog

:cl: PositiveEntropy
imageadd: Resprites the soft caps!
/:cl:

### CODE REVIEW

**Comment by cacogen** [comment]
the item sprite looks like a barn in various different areas of zoning

**Comment by Colovorat** [comment]
item sprite is too big and for me personally it's too square

**Comment by bluetshirtguy** [comment]
Looks pretty rad but your hair clipping through it slightly in the screenshots makes it seem less flattering.

**Comment by Jolly-66** [comment]
To me this is a downgrade for the current paramed hat. Sure we got the perspective now, but my overall gripe with them in general is they appear way too boxy, they actually look more like _snapbacks_ than softcaps.

**Comment by Serxule** [comment]
why are they completely square? not only does it look weird but it doesnt match with the wearing sprite, also the security cap looks pretty ass.

**Comment by MrDoomBringer** [comment]
floor sprite needs to be much smaller

**Comment by Dorsisdwarf** [comment]
why are they square

**Comment by Pepsilawn** [comment]
Security cap's Nanotrasen logo doesn't seem to be matching between sprites, looks like a white background on the worn sprites when it should be mostly blue

**Comment by ilikesaying** [comment]
it looks like it was kidnapped from Minecraft what the fuck

**Comment by cacogen** [comment]
kinda reminds me of the houses and hotels in monopoly

**Pull request merged**
