### PR TITLE
Adds patriotism to Liberation Station

### PR DESCRIPTION
**Pull request by 81Denton**
Why bother calling it Liberation Station if it doesn't vend burgers, fries and shitty light beer?

This PR adds regular ones + light beer to the product list, cheese fries/bacon burgers to the premium section and a super bite burger to contraband. God bless.

### CODE REVIEW

**Comment by 81Denton** [comment]
Ok we now have Carp Lite™️, shitty light beer

**Review by ShizCalev — DISMISSED** [review]

**Comment by PKPenguin321** [comment]
Add home run baseball burger

**Comment by 81Denton** [comment]
@PKPenguin321 great idea

**Comment by Bawhoppen** [comment]
You could also add some all-American apple pie, for a well-rounded meal.

**Comment by optimumtact** [comment]
We live in a society

**Comment by PKPenguin321** [comment]
Gamers...

**Pull request merged**
