### PR TITLE
Cult Refactor Update

### PR DESCRIPTION
**Pull request by ghost**
- Runes are no longer rites (except in the information entry bodies) and have names that describe what they do
- Examining a talisman no longer opens the paper GUI
- Re-adds armor talismans
- EMP talismans have been changed to be as effective as the rune
- Some talismans now take health when used, in variable amounts - the highest is the stun talisman, requiring 10 brute damage to invoke (same as before the update)
- Scribing runes now deals 0.1 brute damage instead of 1
- Bind Talisman runes no longer deal 5 damage when invoking
- All rune colors and shapes are now identical to how they used to be, excluding armor and soul shell runes because they were both randomly colored and shaped
- Conversion runes now require a static two cultists to invoke.

### CODE REVIEW

**Comment by PKPenguin321** [comment]
>Conversion runes now require a static two cultists to invoke.

what made the system of "less cultists, longer convert time" not work out?

**Comment by Xhuis** [comment]
Nothing. People didn't want it, so I got rid of it.

**Comment by PKPenguin321** [comment]
aw, well okay
two people is alright i guess

**Comment by Xhuis** [comment]
This is merge-ready.

**Comment by Xhuis** [comment]
Changelog is added. This is merge-ready.

**Comment by Xhuis** [comment]
@RemieRichards Could you merge this? Cult is in desperate need of some of these changes, and the wiki page is updated to reflect them.

**Comment by Miauw62** [comment]
lmao why are all our players babbies that cant be bothered to learn a few new cool-sounding names.
maybe we should rename fleshmend to "heal self"

**Pull request merged**
