### PR TITLE
Intern Horde take 2

### PR DESCRIPTION
**Pull request by Ryll-Ryll**
## About The Pull Request
See: #47210

## About The Pull Request
Adds a new ERT type, a human wave of NT Interns

Each intern gets internals, a bolt action rifle, two extra stripper clips, and a police baton. The head intern gets all that, PLUS a dorky-ass hat to command authority with, a megaphone to yell at their peers with, and a vest to sling their rifle on.

I had the idea to add this after sending ~10 centcom officials to the station to combat a giant spider infestation, and wishing there was an easier way to arm them than spawning their extra gear en masse and hoping they took them

[](https://i.imgur.com/obWEz1F.png)

Showing off the Head Intern and Intern outfits. Great thanks to @Mey-Ha-Zah for the excellent sprites!

## Why It's Good For The Game
Adds another tier of CentCom Response Team (at the bottom) that is focused on shooting things en masse, without all the excessive/irrelevant gear and loot of ERT's (you don't _need_ fancy toys like RCD's, medibeams, and pulse weaponry to detonate a nuke!)

Low gear level lets you throw a ton of ghosts back into the game and hope a few of them can stick together and accomplish something. Losing one member of a four man ERT can be devastating, especially if their gear ends up in the hands of the enemy, but losing one intern and their half empty mosin out of ten is par for the course. Remember, it's not human wave tactics, it's the _doctrine of stochastic tactical effectiveness_!

And honestly, most ERT's are horribly coordinated and usually immediately split up and die alone. If they're gonna act like disposable interns, may as well treat them like it!

## Changelog
:cl: Ryll/Shaps
add: New opportunities for (unpaid) internships are available at CentCom for those willing to face danger and earn glory for your company! 
/:cl:

### CODE REVIEW

**Comment by Ziiro** [comment]
My only concern is: does their ID work the CC shuttle console? That's about the only thing that would still be valuable on them if that's the case.

**Comment by carlarctg** [comment]
only let the head intern use the console, everyone else has a no access id

**Comment by ATH1909** [comment]
Can you give them all cable cuffs to go with their batons? Cable cuffs are dirt cheap to make, so it still fits the "herd of interns" theme.

**Comment by Shapsy** [comment]
I don't have an issue with centcom ID's being out there, I usually have contingencies for if people steal ID's and come back

As far as cuffs, I'd rather they just shoot everything like a really shitty deathsquad. I envision them mostly only being used against simple mob hordes

**Comment by fludd12** [comment]
This is totally bikesheddy and probably difficult to code, but some way of letting admins choose a loadout for the horde would be neat, like giving them all paladin armor and claymores for a last stand against the cult, or choosing to make them all spawn with zipties like @ATH1909 mentioned.

**Comment by Shapsy** [comment]
I mentioned being able to specify outfits like you can do with custom portal storms but by god i just wanna get this standard in first if this stops conflicting for half a sec, uploading another commit

**Comment by Shapsy** [comment]
After minor technical difficulties it compiles for me and passes review!

**Pull request merged**
