### PR TITLE
KA text 2 : Electric Boogaloo

### PR DESCRIPTION
**Pull request by yackemflam**
Make the text much shorter.

### CODE REVIEW

**Comment by JJRcop** [comment]
tadaa..

**Comment by PKPenguin321** [comment]
:clap: bravo :fireworks: :tada: :smile: :clap: :balloon:

**Comment by Iamgoofball** [comment]
:+1:

**Comment by TechnoAlchemisto** [comment]
unacceptable

**Comment by PKPenguin321** [comment]
wtf

**Comment by Davdichan** [comment]
Stop fucking quoting my shitposts.

**Pull request closed without merging**
