### PR TITLE
Changelings can now manually detach limbs!

### PR DESCRIPTION
**Pull request by ghost**
:cl: More Robust Than You
add: Changelings can now manually detach limbs!
/:cl:

[why]: # (Please add a short description [two lines down] of why you think these changes would benefit the game. If you can't justify it in words, it might not be worth adding.)

Changelings have full control over their bodies, yeah? So why can't they pop their limbs off like the true monsters they are?

### CODE REVIEW

**Comment by ShiggyDiggyDo** [comment]
the limbs should turn into hostile simplemobs

**Comment by Armhulen** [comment]
^^^^^^^^^^^^^^^^^^^

**Comment by MMMiracles** [comment]
detach your head for a 20 throwforce weapon, truly horrific

**Comment by Armhulen** [comment]
@MoreRobustThanYou you did it, but by god you did it stupid like. why can't you have the detached limbs grow spines legs and tentacles when they attack instead of the wizard animate

**Comment by Mey-Ha-Zah** [comment]
Because he doesn't have the sprites.

But he could...

**Comment by Armhulen** [comment]
it's super easy though look at my thinglings pr, and add tiny spines to the limbs

**Comment by KorPhaeron** [comment]
Love to clutter an ancient shitty verb list with another useless button that cripples me

**Comment by Armhulen** [comment]
i understand why a slime wouldn't understand the strength of this pr but
1. one hand removed means you slip out of cuffs
2. losing your head is just fantastic as a throw weapon and it also means they can't hit your head. finally you look pretty awesome but who cares fine whatever

**Comment by Armhulen** [comment]
which means this pr really invalidates breaking out of cuffs with that other ability now that i think of it

**Comment by ShiggyDiggyDo** [comment]
Just make them unable to remove limbs when cuffed and write a plausible (lol) reason

**Comment by Mey-Ha-Zah** [comment]
Maybe they legit pull off their limbs.

Hulk style.

**Comment by KorPhaeron** [comment]
@Armhulen throwing your head does garbage damage unless you're a dullahan

Useless and suicidal in most situations and a free instant replacement for the cuff dissolve power otherwise doesn't actually make me like it more either

**Comment by Mey-Ha-Zah** [comment]
@KorPhaeron if he makes it so they have to have a free hand to perform the action, it's an easy fix.

**Comment by Potato-Masher** [comment]
A more time consuming alternative to Fleshmend.

>super damaged limb
>remove and dispose
>regenerate

I like it.

**Comment by Mey-Ha-Zah** [comment]
Remove it then make it attack the person who caused it.

**Comment by DaedalusGame** [comment]
shouldn't this be an action button or are people really attached to having verbs

**Comment by KorPhaeron** [comment]
@DaedalusGame nobody wants to do the tedious work of converting changeling abilities to action buttons so they just keep piling more verbs in

**Comment by Armhulen** [comment]
ok yeah then this has no place


SADLY.

**Comment by DaedalusGame** [comment]
aaaaaaaaa i have like 3 minecraft mods to maintain and you keep piling up bullshit that makes me want to pr fixes

**Comment by imsxz** [comment]
Can you detach your torso? Also might wanna consider making it a purchasable ability because it seems rather strong..

**Comment by KorPhaeron** [comment]
Ling powers really need to be action buttons before add more innate ones

**Comment by KingPhilipIII** [comment]
As much as I enjoy this idea(Which can then lead into other fun stuff with severed limbs) Kor is right we need to make some damn action buttons.

**Comment by Armhulen** [comment]
Sounds really easy to do I'll do it

**Comment by DaedalusGame** [comment]
Can I just note here that Armhulen is my favorite codermin

**Pull request closed without merging**
