### PR TITLE
[s] Disables persistence saving in sandbox mode

### LINKED ISSUE #28586: Smuggler stachels should check gamemode for sandbox
.>Admin switches to sandbox for fun
.>Spawn a smuggler stachel and some game breaking item like a antag item or syndicate borg spawner
.>Wait

Youuuu must
Youuuu must
Youuuu must

### PR DESCRIPTION
**Pull request by Cyberboss**
Fixes #28586

### CODE REVIEW

**Comment by DoctoreMad** [comment]
PROPER USAGE OF [s] TAG, 10 POINTS
By the way is there any way to delete saves? Luckily the sandbox was just in Pubby so its unlikely people will find anything.

**Comment by RemieRichards** [comment]
They're on the servers. Someone can remote in and delete the savefile if they really care that much.

**Comment by DoctoreMad** [comment]
Should I page MrStonedOne?

**Comment by kevinz000** [comment]
or we can roll pubby again and have admins mass delete satchels????

**Comment by DoctoreMad** [comment]
That too works

**Comment by Kromgar** [comment]
Did we actually have any sandbox modes in the last couple months?

**Comment by optimumtact** [comment]
I don't think the [s] tag was intended for security issues, just for things like april fools pr's and maintainers closing and reopening pr's for travis rebuilds etc.

**Comment by Armhulen** [comment]
@Kromgar I'm so sorry. I was so curious!

**Comment by Shadowlight213** [comment]
No, mso literally said at one point it's for security issues

**Comment by Jordie0608** [comment]
The [s] is for sarcasm.

**Comment by DoctoreMad** [comment]
Ah well I'll call him
@MrStonedOne you should wipe Pubbystation's Satchel list.

**Pull request merged**
