### PR TITLE
Ghosts can click on a linked quantum pad to tp

### PR DESCRIPTION
**Pull request by coiax**
Pretty simple QoL.

### CODE REVIEW

**Comment by GunHog** [comment]
Another QoL would be a quantum pad list so a pad can find another pad without having to use a multi-tool!

**Comment by XDTM** [comment]
I kept it intentionally complicated so the antag variant (cult telerunes) would still be superior. Plus, this way you can make one-way telepads for prisoners and such.

**Comment by SgtxRootbeer** [comment]
I still like the idea of optionally linking pads to a computer which is not only expensive and power-hungry, but also gives the pads a list similar to cult.

**Comment by Supermichael777** [comment]
>power limiting anything 95% of the time

Stop it I'm gonna break something

**Comment by SgtxRootbeer** [comment]
Power can limit stuff in the game, if the machine is built on lavaland, it might drain the smes, or over-usage may drain your APC.

**Pull request merged**
