### PR TITLE
resprites shitty remie plants

### PR DESCRIPTION
**Pull request by Militaires**
old
mspaint_2017-04-14_00-02-30
new
dreamseeker_2017-04-14_00-07-36

:cl: basilman

imageadd: added new remie plant sprite
/:cl:

[why]: # (Please add a short description [on the next line] of why you think these changes would benefit the game. If you can't justify it in words, it might not be worth adding:) because memes and new sprite

edit: i changed the maw

### CODE REVIEW

**Comment by Sligneris** [comment]
How is this a revert/removal?

**Comment by coiax** [comment]
Because it's... removing the old sprite?

**Comment by Cyberboss** [comment]
No my php code mustve fucked up somewhere

**Comment by Cyberboss** [comment]
@Militaires did you have it as imagedel and edited it? That's the only way I can see this could've happened https://github.com/tgstation/tgstation/blob/master/tools/github_webhook_processor.php#L357

**Comment by optimumtact** [comment]
Please use a single name in your changelog

**Comment by Militaires** [comment]
@Cyberboss yes i knew you'd freak out over that so i didnt say that i had that tag and i removed it.

**Comment by Militaires** [comment]
hmmm i have an idea

**Comment by Armhulen** [comment]
i kinda like the huge maw reeeeee

**Comment by WhiteHusky** [comment]
@Armhulen Don't vore yourself to the plant damnit.

**Comment by Iamgoofball** [comment]
Do you think you can keep the piranha plant/Audrie 2 theme?

**Comment by dannno** [comment]
looks good

**Comment by PKPenguin321** [comment]
too subtle it needs to say "hey look this is a thing that will eat you"

**Comment by Militaires** [comment]
@PKPenguin321 vore

suck the plant in your dick and then cum it to gib it to counterplay

**Comment by Militaires** [comment]
@Iamgoofball this is just a placeholder dont worry

**Comment by Armhulen** [comment]
make it scarier, have you seen that rogue legendary corpseplant thing? THAT. DO THAT.

**Comment by RemieRichards** [comment]
that one isn't actually my sprite either.
it was much worse.

**Comment by XDTM** [comment]
It's a big improvement, but i agree with PKP, it's gotta look more dangerous

**Comment by Militaires** [comment]
just a placeholder guys the real one will have more flair

**Comment by Iamgoofball** [comment]
:+1:

**Comment by ExcessiveUseOfCobblestone** [comment]
Replacing a placeholder with a placeholder??????

**Comment by YakumoChen** [comment]
sprite is too busy, the old one looks better because it's bright and obvious.

**Comment by dannno** [comment]
that is utter nonsense what are you on

**Comment by Militaires** [comment]
@yakumochen >the old looks better

_audience laughs_

**Comment by FantasticFwoosh** [comment]
Would have been happier if you actually spent time sharing & asking for help in the spriting part of the forum so you could submit a finished project straight away with their input.

If you do, please link where or make your own thread for it there.

> Happy with a improvement to the lackluster sprite though.

**Comment by Militaires** [comment]
@Iamgoofball @PKPenguin321 @Armhulen 
i set the maw to be bigger until i can get around to a better

**Comment by WJohn** [comment]
Much better 👍

**Pull request merged**
