### PR TITLE
Fixes nanite comm remotes

### LINKED ISSUE #54427: Nanite comm remotes don't work at all
## Reproduction:

I usually add a skull echo with comm code 300 on a relay 112 to signal about crewmember's death. When trying to send a relay message with comm code 300, nothing happens. Neither targeted nor local work too. The skull echo (now also tested on forced speech) program is always active and ready to receive signals.

### PR DESCRIPTION
**Pull request by XDTM**
## About The Pull Request

Fixes #54427

## Changelog
:cl: XDTM
fix: Fixed nanite comm remotes not working at all.
/:cl:

### CODE REVIEW

**Comment by Winterous** [comment]
I thought it was just an incomplete feature, like a lot of things with Nanites.

**Comment by XDTM** [comment]
Just a victim of the UI rework. Since i'm back to coding, what other things are left incomplete with nanites?

**Comment by Hadzabadza** [comment]
> Just a victim of the UI rework. Since i'm back to coding, what other things are left incomplete with nanites?

I've been playing around with nanites a lot and it seems that accelerated regen works somewhat wonkily when the host is in crit/dead/resurrected by nanite defib. I haven't managed to pinpoint exactly what's happening there, but I think it might be some inconsistency with defib - the defib itself is supposed to heal some damage after successfully resurrecting someone, but I'm not sure it actually does, it's almost as if it applies some kind of a harmful debuff. Or more likely, it's accelerated regen that damages the host while trying to heal them. I remember once seeing my limbs (I think torso as well) becoming blue and then suddenly green again after I was brought back from death by the defib despite having no harmful effects like heat around (I was also immune to crit because I had self-respiration virus). So in short, accelerated regen seems to work either very poorly, or it outright does both damage and heal after someone is successfully defibbed.

One more thing that could be really useful is having rules affect triggers as well - say you set a defib to repeat every second and add "death" and "health>-50%" rules so the defib automatically brings someone back without many convoluted programs necessary to make it work (currently I make a defib + health sensor + signal repeater + death sensor to make a proper defib happen). However, this kind of addition may make things too easy, I kind of like that it seems I'm the only one who came up with a proper defib routine :) It also seems I'm one of, if not the biggest user of nanites currently, so feel free to hit me up if you need tests or something.

**Comment by XDTM** [comment]
>(I was also immune to crit because I had self-respiration virus)

Self-respiration applies TRAIT_NOBREATH, and crit is currently coded to deal brute damage instead of oxygen if the mob has TRAIT_NOBREATH, which combined with regen running should explain the damage-heal cycle you saw.

I'll look into making rules able to restrict triggers, it would open up some interesting possibilities and i'm always trying to make nanites more accessible and easy to use whenever possible.

If you have any other feedback or suggestion about nanites, hit me up on discord! I usually don't get much feedback since they don't seem to be widely used, so anything would be helpful.

**Comment by Winterous** [comment]
The problem with the conditional rules is that they literally only apply to programs which already check things; like accelerated regen, how it checks for if you're at full health.
Unless a program has that checking behaviour built-in, conditional rules just don't function. They're very janky.

**Comment by XDTM** [comment]
Is that so? I was fairly sure it works with bio-reconstruction, which has no check whatsoever.

**Comment by Winterous** [comment]
I can't remember the specifics, was a while ago, but I'm pretty sure that I could only get the conditions to work on a few programs.

**Comment by Hadzabadza** [comment]
I'm quite sure conditionals work fine when I tried them, biorec definitely obeyed the rules

**Pull request merged**
