### PR TITLE
Includes chicken breast to the produce console for variety

### PR DESCRIPTION
**Pull request by carshalash**
## About The Pull Request

You fell for the bait title. I haven't seen any chicken recipes made in weeks, by adding an orderable single breast at the produce console we add the possibility of more varied recipes being made. 

## Why It's Good For The Game

More varied use of cooking needs to take place, adding accessibility to less used ingredients hopes to amend the current lack of variety in chef players creations. 

## Changelog

:cl:
qol: Adds accessibility to breasts for service members
/:cl:

### CODE REVIEW

**Comment by san7890** [comment]
would you believe me if i told you i only clicked on this because i had no idea why you doing the semantic commit style with the `[
Content]` tag

**Comment by carshalash** [comment]
Okay, I had my 5 minutes of fun.

**Comment by DaydreamIQ** [comment]
Finally I can make Tikka masala without having to blow the entire cargo budget on fourty chickens

**Comment by CCC23** [comment]
finally you can GET meat

**Pull request merged**
