### PR TITLE
Tramstation Service Revamp

### PR DESCRIPTION
**Pull request by MMMiracles**
## About The Pull Request
Revamps the entire service wing on Tramstation, mostly working around the Kitchen/Bar setup.

## Why It's Good For The Game
Redesigns the service wing, making it easier to access the bar while making the kitchen/dining area more unique.

## Changelog
:cl: MMMiracles
add: Tramstation's service wing has been revamped!
add: The Kitchen and Hydroponics has been redesigned entirely with small adjustments to the bar.
add: A larger dining area as well as a Kitchen area with underground freezer.
add: Better department layout in general for Hydroponics while keeping the dedicated beekeeper room.
add: A dedicated service room to hold the various ordering/request consoles between the ktichen/bar/hydro.
add: The stairs leading to the bar have been made very accessible from the tram dock, being right beside the kitchen entrance. The lower segment of the bar has been redesigned the better fit this change.
/:cl:

- The Kitchen, Hydroponics, and to an extent the Bar have been revamped for better flow.
- The kitchen and dining area have been made larger, with a ladder-accessed freezer. The glass flooring in the dining area is larger to better show the floor below.
- The dinky service lathe room has been changed to a dedicated service room with the appropriate consoles and desks for ease of access.
- The side staircases are now directly beside the new kitchen entrance to make it that much easier to walk between the two.
- Shorter walking distance between the permawing and the courtroom side entrance.
- New maintenance dock bit.
- The custodial office was changed and given a water closet that connects to all the faucets in the service wing.

image
image

### CODE REVIEW

**Comment by MrMelbert** [comment]
The cargo requests console and paired computer should really be moved somewhere all of service can access them instead of the middle of hydroponics for no reason.

**Comment by Bawhoppen** [comment]
Gotta reiterate my opinion on the bar being removed. That original bar design you came up with in the basement was a work of gold, and featured some of the most agreeable, fun, and vibrant bar action I've seen in the game ever. I have no real stance on any of the other changes, just that I know people will be very disappointed to lose out on the bar.

**Comment by Zargoar** [comment]
Please do not implement this change.
The underground bar is one of the most interesting distinguishing features of Tramstation.
With the double restrooms it actually looks like a bar (nowhere has unisex restrooms).
With the clear floor above you could see the lights and the people in the bar beneath when eating.

The new bar area looks rather crowded and potentially prone to assistant shoving-matches or bombing.
I really appreciate Tram as-is and applaud your efforts to improve it.

This last year or so being stuck at home during covid that silly lower bar on Tram has been some of the most fun I've had. It was cathartic for me as I missed going to my nightclub IRL.

Please keep the bar as it is to preserve the uniqueness of the service area on Tramstation.

**Comment by ShizCalev** [comment]
Are there no fire alarms in botany?

**Comment by Farquaar** [comment]
My opinion on the old bar: It was really cool when people visited it. But the problem was that people rarely did. Great layout, and cozy, but a ghost town 9 shifts out of 10.

I'm indifferent to the new changes, mostly. The fact that you have to walk through the bar to get a snack means that the bar may see more foot traffic, but the counter-area seems to take up a lot of space. I prefer maps where the bar and kitchen are close enough to work together (i.e. go to the bar counter and order a beer and some fries) but that's just me.

**Comment by carshalash** [comment]
Quite frankly even I was okay with the old bar.  The only real issue was the lack of access to cargo as well as none of the maint doors in that area being accessible (Trying to get welding fuel for hooch, running into maint for a radstorm etc.)
The lack of portraits in the new bar is a drag. 
I think you should really reconsider the whole, firelocks instead of airlocks approach for the bar.

**Comment by notfrying1pans** [comment]
i'm not a big fan of maint being cut down, on a map that already has little maint

**Comment by carshalash** [comment]
Another big thing, I know for a fact that a lot of maint goblins are going to try and crawl over the counter shift start screeching like monkeys to try and get the shotgun.

**Comment by Zargoar** [comment]
> 
> 
> Another big thing, I know for a fact that a lot of maint goblins are going to try and crawl over the counter shift start screeching like monkeys to try and get the shotgun.

The lack of bar back room means there can't be any shady back-room bullshit.

**Comment by MMMiracles** [comment]
Comments in this github and as well as the discord is making me second-guess this current layout.

**Comment by BebeYoshi** [comment]
Thank you for making upstairs botany actually enjoyable (bottom floor probably will still be just used to hide dangerous plants though).

**Pull request merged**
