### PR TITLE
Nerfs rezadone to a heal-over-time rather than an instant total heal

### PR DESCRIPTION
**Pull request by Iamgoofball**
# FUCK

### CODE REVIEW

**Comment by Iamgoofball** [comment]
# BEFORE YOU SCREAM ILL MAKE THE RECIPE EASIER OK

**Comment by Cheridan** [comment]
if you make cloneloss easier to heal then people will want to add more features that use cloneloss, and cloneloss is a garbage mechanic so that's bad.

**Comment by Iamgoofball** [comment]
cloneloss is garbage yes

but that isnnt gonna hold me back fgrom REMOVING 0.0000001U HEALSOS DGKAFHGWSIFYEWFRE4GTRGF

:ok_hand: :joy: :hankey:

**Comment by PKPenguin321** [comment]
>kill 6 carp, gib and grind their meats
>painstakingly brew 10u of rezadone
>heals 60 cloneloss and that's it

Welp there goes any reason to ever make this shit again

You're so good at coding for chemistry, goofball

**Comment by Iamgoofball** [comment]
2631 units of rezadone have been made in the last 30 days.

For comparison, there has been:

228999u of Unstable Mutagen
153408u of Styptic Powder
68436u of Space Lube
10u of Grappa, which is wine plus enzymes.

This is all in the last 30 days.

No one makes rezadone anymore.

**Comment by Core0verload** [comment]
Cool down, goof. You are contradicting youself. You claim rezadone is OP, yet you say nobody ever uses it. Fix your logic and retry again.

**Comment by jughu** [comment]
Koibeans=carpotoxin
Reed=Chemist
Botanist=Koibeans

reed+botanist+koibeans=Rezadone

**Comment by 9600bauds** [comment]
You're also saying you only need 1u to treat 10 people so 2631 isn't terribly representative

**Comment by coiax** [comment]
So with this change, how many units do you need to heal, say, 200 clone damage? Infinity heals is pretty bad, regardless of how difficult it is to make.

**Comment by optimumtact** [comment]
Dont' expect goofs logic to be internally consistent, he uses the byond rng

**Comment by Cheridan** [comment]
sorry nerd you got downvoted lmao

**Pull request closed without merging**
