### PR TITLE
Adds invisible sprites to unfuck P.D.A.s.

### PR DESCRIPTION
**Pull request by pireamaineach**
Ouch ow my eyes.

Rehash of https://github.com/tgstation/tgstation/pull/51267 using a suggestion posed post closing.

## Changelog
:cl:
add: Invisible sprites which unfuck P.D.A.s.
/:cl:

### CODE REVIEW

**Comment by Iamgoofball** [comment]
this is a better fix, not the proper fix, but a better fix :+1:

**Comment by pireamaineach** [comment]
I just went with what Oranges' suggested since it's low-skill enough for me.

**Comment by PKPenguin321** [comment]
a singular invisible sprite in its own file that can be used whenever we explicitly want to make something spriteless may be better

**Comment by pireamaineach** [comment]
It is only spriteless for on_mobs, keep in mind.

**Comment by actioninja** [comment]
don't pdas actually have an onmob though? it's called `electronic` iirc and was just broken a while back.

**Comment by PKPenguin321** [comment]
iirc they have one when worn in the ID slot but not sure about the belt slot

**Comment by pireamaineach** [comment]
So many things in waist slot are broken by this by the way:

In progress list so far:
>Belt PDA sprites
Wrench, tool belt sprites.
Fucking cigarette pack belt sprites.
Mining, chem bags.
Laser pointer.
Pinpointer.
Autoinjectors.
The generic belt, both icob and on_mob.

**Comment by nemvar** [comment]
Closing this because there is a proper fix to this. Some of the worst offenders have already been fixed yet work still remains.

**Pull request closed without merging**
