### PR TITLE
Fixes object processing list 

### LINKED ISSUE #7508: Xeno bursting time is now insanely fast and two larvae are bursting from one body seemingly at random
A xeno round just happened on Sibyl where everybody was bursting insanely fast, like less than half the time it used to take. Also two larvae burst from my body and somebody else mentioned the same thing happening to them too in deadchat but other bursted bodies only produced one larva. Both of these combined obviously make the xenos far more OP than even they're supposed to be.

### PR DESCRIPTION
**Pull request by phil235**
by replacing "SSobj.processing.Add" with "SSobj.processing |= " to avoid having duplicated objects in the list, meaning the objects would be processed more than once per iteration.

Also, I fixed Alien embryo processing that was processed twice. Fixes #7508

### CODE REVIEW

**Comment by Miauw62** [comment]
@cheridan @hornygranny

**Comment by paprka** [comment]
Should I do this in my stun baton PR as well, even though I fixed the loop?

**Comment by phil235** [comment]
@paprka It's probably safer that way.

**Comment by RemieRichards** [comment]
I love |= and use it wherever possible, makes things so much nicer :+1:

**Pull request closed without merging**
