### PR TITLE
makes decal painter a basic tool

### PR DESCRIPTION
**Pull request by XRandomXManX**
## About The Pull Request

Makes the Decal Painter into a Basic Tool instead of a BEPIS unlock. It's very meh for a BEPIS unlock, especially for the Scientists that'll be using it. Though, it does have a use that some builders might like. add some pizazz to your rage cage with a couple of warning tiles!

## Why It's Good For The Game

Imagine spending a shiz ton of money on the BEPIS and getting a glorified Airlock Painter but for floors? -or being a Builder and not being able to get the Decal Painter because you're not a millionaire. NO MORE, for you can now print it off for 50 Metal, 50 Glass. It does take Ink Toner, which only gives a few shots. It'd be easier to use Spray Cans or Crowbarring the Floor if you wanted to be a horrible person. Worst Case: The Halls are filled with warning signs, after someone managed to get a million Ink Toner and had a LOT of free time. I'm just trying to cover my bases when I say, "Please oh god please don't say it being a BEPIS Reward is a good thing.", all it being a game luck does is give it to people who aren't looking for it.

## Changelog
:cl:
del: Removed Decal Painter from BEPIS Minor Rewards
add: Added Decal Painter to the Basic Tools Research Node
add: Added Decal Painter to Maintenance Loot alongside the Airlock Painter
/:cl:

### CODE REVIEW

**Comment by ernestget8thumb** [comment]
wow thanks its just what i wanted for christmas

**Comment by Fikou** [comment]
could you add it to the servicelathe too?

**Comment by XRandomXManX** [comment]
Both the Airlock and Pipe Painters are Engi only, so I'm trying to keep up with that until this is merged. I might add a separate PR changing it. I'll at least add it to Maint Loot. It won't be too hard to ask the Engis or search in Maint hopefully.

**Comment by ernestget8thumb** [comment]
put it in every lahte, its so versatile that i can see a reasonable use in every department

**Comment by XRandomXManX** [comment]
The Airlock Painter is versatile too, but it's only available on the Engineering Lathe. I'm gonna put in another PR to get both of them to not have restrictions, or at least exist in the Service Lathe, but don't want anything to mess up this PR getting merged first );;;;;;; I think Cargo might have access to Basic Tools too, in case you want to ask them.

**Comment by RaveRadbury** [comment]
I'd really like to see this in the service lathe soon, as Bartender, Curator, and Chaplain have an emphasis on remodeling their spaces.

**Comment by ArcaneMusic** [comment]
Sure, why not.
The Decal Painter is honestly pretty cool, it's just held together with string and duct tape on the backend but it's un-ironically useful for making things look good mid-round.
Plus, now there's a use for **TONER**

**Comment by optimumtact** [comment]
This user has received a permanent block

**Comment by Tlaltecuhtli** [comment]
when i used it i felt that changing the toner was really not intuitive and the toner doesnt last enough can you make it better while you are at it?

**Comment by XRandomXManX** [comment]
the toner is small right now probably so you can't cover the halls in markings, but I'll make another PR requesting more shots and the ability to let you release toner early. Just give me an hour or so.

**Comment by XRandomXManX** [comment]
thank you very much for this suggestion, as it led me to find that the Decal Painter actually costs 2000 iron and 500 glass right now to make, and that I really need to adjust that in this PR!

**Comment by XRandomXManX** [comment]
Sorry this took so long, had to deal with some Raisins. Anyways, while trying to figure out if I could make the Decal Painter use less Ink:- I discovered that there are different types of toner carts. So all you need to do to get more shots is to ask RnD or whoever for a large or massive toner cartridge. (Massive Toner has 200 shots by the way)

**Comment by XRandomXManX** [comment]
(:

**Pull request merged**
