### PR TITLE
AIs no longer block the auto-shuttle call

### PR DESCRIPTION
**Pull request by zxaber**
## About The Pull Request
AIs will no longer add themselves to GLOB.shuttle_caller_list, and thus are no longer considered when the game decided if to auto-call the shuttle. Thus, smashing all communications consoles will call the shuttle even if the AI is still alive.

The actual ability for AIs to call the shuttle has not been affected.

## Why It's Good For The Game
Related to #56121, in terms of trying to call the shuttle by smashing all consoles, one no longer also needs to break into the AI's sat (or otherwise find the AI) and kill it to get the shuttle called.

## Changelog
:cl:
balance: The shuttle auto-call function no longer requires killing any on-station AIs.
/:cl:

### CODE REVIEW

**Comment by optimumtact** [comment]
I don't see what the point of this change is

**Comment by zxaber** [comment]
Complaints were made against another PR that calling the shuttle was too difficult if the heads of staff are gone. In response, this PR (and the linked one) intend to help with that.

For example, if the AI has been given laws that only the heads of staff are human, and all heads of staff are subsequently killed, the AI would be under no requirement to listen to orders for it to call the shuttle. In that case, the crew should be able to break into the bridge and destroy the consoles without having to deal with the AI at all if they want the shuttle to be called.

**Comment by Pugie** [comment]
Its easy just emp ai core to call shuttle take some initiative smh

**Comment by necromanceranne** [comment]
Calling the shuttle being quite literally a two room stop is going to be pretty obnoxious if people were so eager to end the round. The AI being the other thing preventing shuttle calls was mostly to prevent exactly that. If you want to go home early and you have no access,  you better have a good reason for killing the AI other than you want to antag roll. The current method weeds out the dipshits who openly admit to antag rolling.

**Comment by Timberpoes** [comment]
AIs blocking auto shuttle calls is intended functionality. I would like to see more discussion about this in general, as I'm not certain it's a net positive change.

If an AI player is unduly stalling a round out it may be a breach of the server rules and require ahelping - Either because their laws are bad and the uploader needs a talking to or because they are bad and they need a talking to.

**Comment by zxaber** [comment]
Yeah alright, given it some thought, this one probably isn't necessary.

**Pull request closed without merging**
