### PR TITLE
[s] Fixes datum var hiding

### PR DESCRIPTION
**Pull request by Cyberboss**
@MrStonedOne @kevinz000 Please tell me if I missed any vectors

### CODE REVIEW

**Comment by kevinz000** [comment]
Sdql

**Comment by Cyberboss** [comment]
Elaborate

**Comment by kevinz000** [comment]
Mark global var datum
Update /thing set var = marked.Thing

**Comment by MrStonedOne** [comment]
protect Master other wise somebody could edit it to glob and then call Recover and look at the logs to see every global var's value.

**Comment by MrStonedOne** [comment]
In fact, take a look at every use of vars. do a search for `vars[` to prevent false positives.

I found a fuck ton of examples.

It might be best to put protected info in old school global vars for now.

**Comment by Cyberboss** [comment]
Anything that can be accessed in the MC tab is a real global (except
cameranet)

**Comment by MrStonedOne** [comment]
buildmode.dm:305 needs to respect vv edit var.

**Comment by MrStonedOne** [comment]
Also it looks like sdql2 lets you set somethings value to something else's value, like kevin was saying, so you could abuse that to read.

**Comment by Cyberboss** [comment]
SQL, comms, and hub keys, right?

**Comment by MrStonedOne** [comment]
right.

**Comment by MrStonedOne** [comment]
oh, one thing you could do in a later pr, is a global var that is set before any proc call/advance proc call, so we could protect procs from admin abuse if needed.

callbacks should also set if if their var_edited value is set, and addtimer should set var_edited when it's advance proc called.

and then #TESTING should override all of this.

**Pull request merged**
