### PR TITLE
cleans my legacy and changes the shitty nutrition mood

### PR DESCRIPTION
**Pull request by ghost**
:cl: Qustinnus / Floyd
tweak: your belly is now flat and empty
/:cl:

at the time of writing that text i didnt really think how cringy the text could sound, this text is probably a bit less weird. ;^)

i actually thought someone fixed this already tbf

### CODE REVIEW

**Comment by Arianya** [comment]
Your legacy is forever tainted.

**Comment by Qustinnus** [comment]
stop bullying it was 4am when i wrote half of the moodlets flavor texts

**Comment by Nabski89** [comment]
I should really put in an actual issue report, but Mint toxin doesn't seem to work anymore for gibbing fat people.

**Comment by Qustinnus** [comment]
has to do with traits most likely

**Comment by Qustinnus** [comment]
ill test that might as well fix it now i got DM open anyways

**Comment by ExcessiveUseOfCobblestone** [comment]
It's so funny now it's almost a shame to see it go.

**Comment by iskyp** [comment]
My belly is round and full!

**Comment by optimumtact** [comment]
You cannot run

**Comment by Qustinnus** [comment]
AAAAAAAAAA

**Pull request merged**
