### PR TITLE
You can now use backslashes as an escape character for text modification.

### PR DESCRIPTION
**Pull request by Ghommie**
## About The Pull Request
When the feature was first coded back on citadelstation years ago I told kevinz to make the text emphasis macros and have them require the characters being inputted twice (`++text++` vs `+text+` to avoid stuff like a+b+c being outputted as a**b**c).
It turned out to be a terrible solution that made the feature more tedious to use, so it got reverted back to its original, unescapeable implementation last december. Afterward, it's ported to TGMC and then here a few days ago.

So here I am, making the underline, bold and italics text modification escapeable in a similar fashion of a markdown language, with backslashes.

## Why It's Good For The Game
Underscore, plus symbols and vertical bars are not often used in sentences (specially ICly), but there are still situations where you should be able to use these symbols more than once in a sentence without getting screwed over by these modifiers.

## Changelog
:cl:
qol: You can now use backslashes to escape say text modifiers (e.g. a\\+b\\+c = d will be outputted as a+b+c instead of abc with the middle letter b bolded).
qol: Two new tips of the round, both concerning say"" syntax.
/:cl:

### CODE REVIEW

**Comment by LemonInTheDark** [comment]
@Mothblocks I blame you for this

**Comment by Mothblocks** [comment]
people are totally not going to remember this exists

**Comment by Mothblocks** [comment]
but why not nobody's made a say profiler yet

**Comment by Ghommie** [comment]
> 
> people are totally not going to remember this exists

That's definitely true for people who aren't accustomed to markdown, regexes or coding, so if you know of a better solution, tell me.

**Comment by Mothblocks** [comment]
yeah sure why not

**Comment by Mothblocks** [comment]
also add a tip of the round for the normal emphasis while youre at it

**Review by Mothblocks — CHANGES_REQUESTED** [review]
add a tip of the round

**Pull request merged**
