### PR TITLE
flushed emoji

### PR DESCRIPTION
**Pull request by bobbah**
## About The Pull Request

This fixes a critical bug, most likely an oversight in the emoji.dm file. The "flushed" emoji was incorrectly provided as a toilet; I have rectified this issue in what I hope is a PR which will lead by example. In the time of this antag freeze, the demand for better PRs, I have been thinking deeply about what may constitute a greater change for the game.

I understand it's controversial.

I know it'll cause issues.

But it's for the best.

**EDIT: okay, jeez, chill out! I've made the concession to have :flush: = toilet and :fl*shed: = flushed emoji**

## Why It's Good For The Game

image

## Changelog
:cl: bobbahbrown
fix: The flushed emoji has now been returned to its former glory.
/:cl:

### CODE REVIEW

**Comment by Qustinnus** [comment]
bring back the toilet

**Comment by bobbahbrown** [comment]
> bring back the toilet

i know this change is hard, but understand the great suffering that some have went through to get to this point.

**Comment by Qustinnus** [comment]
I understand that you have gone through a lot to get this emoji into your branch, and put it into a full PR. but we need to stand together at this time, what are we without toilets? Where will we shit? Will we become weak and start using the streets as our lavatories? Could we become such barbarians?

I say, this PR gets closed, and prevent our civilization from collapsing.

**Comment by bobbahbrown** [comment]
> I understand that you have gone through a lot to get this emoji into your branch, and put it into a full PR. but we need to stand together at this time, what are we without toilets? Where will we shit? Will we become weak and start using the streets as our lavatories? Could we become such barbarians?
> 
> I say, this PR gets closed, and prevent our civilization from collapsing.

what if i made a compromise and added the toilet back but keep the flushed emoji

**Comment by Dawson1917** [comment]
if the tg discord is anything to go by, this is a terrible idea and will get spammed in OOC as much as the bee emote does

**Comment by kriskog** [comment]
No dont take our shitter emote

**Comment by Akrilla** [comment]
😳

**Comment by Tlaltecuhtli** [comment]
fetish content

**Comment by ArcaneMusic** [comment]
Alright hear me out.
😳 should be :flushed: and 🚽 : should be :flush:.
This'll give something to everyone.

**Comment by nervere** [comment]
:flushed:

**Comment by nemvar** [comment]
Duplicate of https://github.com/tgstation/tgstation/pull/44043

**Comment by bobbahbrown** [comment]
this is not a duplicate of that pr

**Comment by bobbahbrown** [comment]
okay okay, this now has `:flushed`: as the flushed emoji and :flush: as the toilet emoji

**Comment by JJRcop** [comment]
this ruins the joke

**Comment by carlarctg** [comment]
power creep 👍

**Pull request merged**
