### PR TITLE
Removes Delta Station from the Rotation, adds Citadel ERP Mechanics and renames Box Station Medbay to ERP Central

### PR DESCRIPTION
**Pull request by BreadBurner**
Just as the title implies and im still waiting for a reason to close my previous request as it was more vaild that those weird fuckign saber noises.

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
@Cyberboss 

Lucky you; we have a specific Russian branch that does it every freaking time they update. YOu think they'd learn, after a while.

**Comment by lzimann** [comment]
you can't even hit the right branch

**Comment by kevinz000** [comment]
Can you shut the fuck up?

**Comment by kevinz000** [comment]
@BreadBurner

**Pull request closed without merging**
