### PR TITLE
Small fix for small problem

### PR DESCRIPTION
**Pull request by volas**

### CODE REVIEW

**Comment by Menshin** [comment]
What was the non-standard character ?

Was it causing bugs with some procs ? (I think this old sanitizing proc is still used somewhere in the code)

**Comment by volas** [comment]
>What was the non-standard character ?
Maybe once it was a Russian "я" letter ("я" = "Я"), but due to problems with encodings at some point it was "broken". Or maybe someone left it specially. Who knows.

>Was there any proc that was affected by this infinite loop ? (I think this old sanitizing proc is still used somewhere in the code)
sanitize() use it, and sanitize()  is used in many places. https://github.com/tgstation/-tg-station/search?utf8=%E2%9C%93&q=sanitize%28

**Comment by Menshin** [comment]
Yeah, apparently it's still used a lot...
I've a PR dealing with sanitizing procs opened already (#7471), i'll add your fix to it.

Thanks for pointing this out.

**Comment by volas** [comment]
Yeah, well, then I close my PR

**Comment by Deantwo** [comment]
What about goimg back in the commit history and see what the symbol was.
But yeah I had been wondering what it was too.

**Pull request closed without merging**
