### PR TITLE
Removes Snowflake Wooden Tile Behaviour

### PR DESCRIPTION
**Pull request by ghost**
This was annoying and really pointless
Wooden tiles can now be crowbarred up and not destroyed just like the other tiles, no need to use a screwdriver

:cl:
tweak: Wooden tiles can now be crowbarred up without destroying them, no longer need to use a screwdriver
/:cl:

### CODE REVIEW

**Comment by WJohn** [comment]
Thank you. This was pointless inconsistency.

**Comment by Cyberboss** [comment]
Ew no

**Comment by Core0verload** [comment]
Ew yes. This was just annoying for the sake of being annoying.

**Comment by FantasticFwoosh** [comment]
If you really need to, but you can outright replace floor tiles by holding a stack of tiles in one hand and a lever in the other.

I voted no, but consistency i guess (???)

**Comment by XDTM** [comment]
You can remove grass and carpet with a crowbar, and wood's not mechanically different enough to warrant special treatment, unlike reinforced floor.

**Comment by Bawhoppen** [comment]
yes let's remove anything that isn't a streamline antag simulator

**Comment by lzimann** [comment]
Snowflake code please go.

**Comment by Bawhoppen** [comment]
no really though why remove it? it's not like it lags the server or wastes file size, and it's a nice little flavor thing

**Comment by ChangelingRain** [comment]
This is good flavour stuff, if not obvious. Perhaps consider making it a little more obvious that wood is screwed down and not standard tiles.

**Pull request closed without merging**
