### PR TITLE
Adds Drone/MMI hybrid sprites

### PR DESCRIPTION
**Pull request by justinbooj9**
## About The Pull Request

Modifies the assemblies icons adding 3 new sprites.

## Why It's Good For The Game

These sprites would be useful for a drone or emagged variant of the Man Machine Interface.

## Changelog
:cl:
add: mmi_eoff, mmi_ealive, mmi_edead Sprites
/Bluedazzled :cl:

### CODE REVIEW

**Comment by Winterous** [comment]
Cute spider brains.

**Comment by justinbooj9** [comment]
I have unleashed satan upon this mortal plane with these sprites.

**Comment by Qustinnus** [comment]
if you wanna add sprites you should probably make sure they're actually used by code.

**Comment by optimumtact** [comment]
https://github.com/tgstation/SS13-sprites

**Pull request closed without merging**
