### PR TITLE
Makes lasertag projectiles beams

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
So they can reflect off of mirrors (and be reflected by eshields and juggernauts!)

### CODE REVIEW

**Comment by Cuboos** [comment]
:+1: fun shit could happen with this.

**Comment by Zilenan91** [comment]
does this also mean you can trigger reactive armor with them

**Comment by kevinz000** [comment]
Rng armor can be triggered with pretty much everything except for a select few items like handcuffs and telebatons

**Comment by Bawhoppen** [comment]
no more deathsquid laser tag :-1:

**Pull request merged**
