### PR TITLE
ClF3 no longer melts walls.

### PR DESCRIPTION
**Pull request by Timberpoes**
## About The Pull Request

ClF3 no longer melts walls. It stills melts through floors.

Thermite is the tool of choice for melting walls.

## Why It's Good For The Game

tYeYxkOM8F

## Changelog
:cl:
balance: ClF3 can no longer melt through walls.
/:cl:

### CODE REVIEW

**Comment by 81Denton** [comment]
On one hand I really like CLF3, but on the other I understand that it's a little silly to be able to melt r walls instantly by clicking on them with a 100u beaker 🤔

**Comment by Timberpoes** [comment]
> 
> 
> On one hand I really like CLF3, but on the other I understand that it's a little silly to be able to melt r walls instantly by clicking on them with a 100u beaker 🤔

Thermite still has the wall melting niche. 50u and 20 seconds for r-walls, which I would argue is a little bit more balanced.

**Comment by bluetshirtguy** [comment]
Malf ai's deserve suffering but if you think it's for the best

**Comment by ATH1909** [comment]
it still looks kind of weird that clf3 works on floors but not on walls that are made of the same materials as those floors. maybe clf3 could degrade walls into merely being (anchored) girders (which are still a pain to remove if the wall you're deconstructing is reinforced), while thermite could go the whole way and remove the whole wall?

**Pull request merged**
