### PR TITLE
Biosuits now offer high Rad resistance

### PR DESCRIPTION
**Pull request by Robustin**
:cl: Robustin
balance: Medical biosuits (and hardsuits) now offer heavy, but not complete, radiation resistance.
/:cl:

Aside from the boatload of bugs, I like the new radiation. My biggest beef is that if you're not in one of the 2-4 rad suits available to engineering, you're pretty much fucked if you try to work in a contaminated area.

Yet radioactive contamination is one of the areas where medical personnel should shine. It's a complex health problem that can't be solved by an assistant with a FA kit from the holodeck. Yet with biosuits offering virtually no rad resistance, the doctors end up just as fucked as the patients.

This will also give security (they have a biosuit) a way to provide assistance to a contaminated area without instantly getting assblasted.

### CODE REVIEW

**Comment by ninjanomnom** [comment]
Hey I fixed the bugs >:(

Good pr though

**Comment by KorPhaeron** [comment]
@ninjanomnom We had a person with like 90k rads stumble out of engineering and into medbay and he killed the whole station

**Comment by davethwave** [comment]
that was me, I was a traitor too, no idea how I got so irradiated though

**Comment by davethwave** [comment]
And STILL no one suspected I was a traitor. The most I got was [oh you stupid engineer, why did you go to medical instead of isolation] from the medical staff

**Comment by Bawhoppen** [comment]
Why do we even have separate suits if we're going to do this? Just give medbay actual radsuits instead of this form of powercreep

**Comment by ninjanomnom** [comment]
Yeah if you can survive it yourself it's easy to hurt people with contaminated objects. Radiation outbreaks has to be treated somewhat like a viral outbreak.

I'll take a look though to try and find out why the contaminated objects were so strong. Also I need to add some higher tier radiation level events.

**Comment by davethwave** [comment]
by the way @ninjanomnom , I think its kind of building itself up by relying on the objects the radiation irradiate, for instance when I entered into medbay as the ONLY irradiated person I had 27k of rads, when I left I then had 38k of rads about 10 minutes later for some reason and everyone was chalk full of rads at around 10k to 50k.

**Comment by Mark9013100** [comment]
Give biosuits minor rad resistance, map in actual radsuits.

**Comment by ninjanomnom** [comment]
Yes, you need to remove your contaminated objects that you're carrying if you want to treat the radiation. Use a geiger counter on someone and you can see the total strength of contaminated objects they're carrying.

**Comment by RandomMarine** [comment]
Biohazard suits becoming the third-best option for rad resistance is somewhat nonsensical.

Instead, security should have a sec-themed radsuit, and medbay gets lead aprons with a tongue-in-cheek remark in their description about the lack of x-ray machines.

**Comment by Robustin** [comment]
A quick google search confirmed that hazmat suits protect the user in contaminated areas by preventing contact with irradiated particles.

Realism confirmed, lets call this a fix and goooo.

**Comment by Supermichael777** [comment]
Make rads not irradiate things with a higher radiation level and make the decay of nonsources more severe

**Comment by ninjanomnom** [comment]
@Supermichael777 that's already the case, I have been considering increasing the decay rate but I still need to observe more to decide on exact details.

**Comment by jughu** [comment]
Rad suits are orderable from carho

**Comment by Bawhoppen** [comment]
It's true, they are

**Comment by RandomMarine** [comment]
Yeah. If you want more sources of rad protection, tell cargo to get them.

**Pull request merged**
