### PR TITLE
ASTEROID FUNLAND

### PR DESCRIPTION
**Pull request by jughu**

### CODE REVIEW

**Comment by Grazyn** [comment]
No. It kills people, it has dangerous wildlife inside and makes a big hole in the station. It shouldn't cost money.

**Comment by jughu** [comment]
A THEME PARK COSTS MONEY

**Comment by jughu** [comment]
AND THE KILLING IS THE MOST FUN PART!!!

**Comment by Arianya** [comment]
@Grazyn Since "it kills people" and "it makes a big hole in the station" hasn't stopped the asteroid shuttle, I don't see why those should be critiques levelled at this one.

I have my own thoughts on credit costs for shuttles but thats really for a forum thread, not a PR.

**Comment by Chocobro** [comment]
pretty sure you've made it give credits instead of remove them. they buy this and get 7k?????? sorry????????

also i suggest you make another entry instead of editing the already fine one

**Comment by optimumtact** [comment]
Please don't touch kor's meme shuttle, it's hurt enough innocent lives

**Comment by Grazyn** [comment]
@Arianya 

It is exactly the same asteroid, he just changed the name and made it cost money instead of giving you money. Shitty and dangerous shuttles like the asteroid are supposed to give you money, that's the whole point. If coders don't like the asteroid they can just remove it instead of trying to push these "disguised" nerfs.

**Comment by Arianya** [comment]
@Grazyn Since most of my thoughts have to do with Kor's shuttle as opposed to this PR I'll put them in the Purchasable Shuttle thread. 👍

**Comment by FantasticFwoosh** [comment]
Least add some kind of addition to ACTUALLY make it a theme park on a asteroid (and therefore make it easier to navigate if not for walking down long corridors of queue dividers.)

**Comment by KorPhaeron** [comment]
Don't ruin my lore

**Comment by ShadowDeath6** [comment]
is this a salt pr?

**Pull request closed without merging**
