### PR TITLE
Updates Altar sprites

### PR DESCRIPTION
**Pull request by Fikou**
## About The Pull Request

ports changed versions of the altars from https://github.com/BeeStation/BeeStation-Hornet/pull/4064
removes the thing where basic altars have candle flames baked into the sprite for some reason

## Why It's Good For The Game

they look nice

## Changelog
:cl: Fikou, PestoVerde322
imageadd: New Altar of Gods sprites
/:cl:

### CODE REVIEW

**Comment by SmArtKar** [comment]
random white pixel moment

**Comment by Twaticus** [comment]
its an icondiffbot problem with multiple frames

**Review by Twaticus — APPROVED** [review]

**Comment by OceanFish1** [comment]
we do a little respriting :trollface:

**Comment by PestoVerde322** [comment]
Well that was unexpected to see my sprites being ported over from Bee to... somewhere else really, and that's actually great. however, I noticed that you modified the sprite and removed both the bobbing animation on the sect thing and the candle flames, which if i recall right, makes no sense to remove it since the altar itself emits light...
I'm fine with it, but just asking because it seems like an odd change to me.

**Comment by maxymax13** [comment]
> 
> 
> Well that was unexpected to see my sprites being ported over from Bee to... somewhere else really, and that's actually great. however, I noticed that you modified the sprite and removed both the bobbing animation on the sect thing and the candle flames, which if i recall right, makes no sense to remove it since the altar itself emits light...
> I'm fine with it, but just asking because it seems like an odd change to me.

the flames are an overlay bro

**Comment by PestoVerde322** [comment]
> 
> 
> > Well that was unexpected to see my sprites being ported over from Bee to... somewhere else really, and that's actually great. however, I noticed that you modified the sprite and removed both the bobbing animation on the sect thing and the candle flames, which if i recall right, makes no sense to remove it since the altar itself emits light...
> > I'm fine with it, but just asking because it seems like an odd change to me.
> 
> the flames are an overlay bro

OH! I'm blind i just noticed them now, That's cool then.

**Pull request merged**
