### PR TITLE
Remove SM from delta station atmos and put it in engi

### PR DESCRIPTION
**Pull request by Ghilker**
## About The Pull Request
After the Singulo/tesla engine removal delta station engineering has been pretty empty, only used as free for all loot room
This PR aims to move the SM from atmos to engi and make a big testing facility inside the old SM place.
Engi SM
image

Atmos Testing facility
image

## Why It's Good For The Game
Engies finally have a job again, more space for atmosians

## Changelog
:cl:
del: removed atmos SM room
add: added atmos testing facility
add: added SM to replace the hole left by singulo/tesla engines
/:cl:

### CODE REVIEW

**Comment by Ghilker** [comment]
image
atmos uses engi tiles and not cargo ones

**Comment by MrDoomBringer** [comment]
Not sure if it's been added already, but could you add an HFR machine atmos in lieu of the SM?

**Comment by Ghilker** [comment]
As in all maps except icebox you have all the parts you need to build one! Look at the north side, you can see on the left some tables with stuff on them, and those are all the necessary stuff, on the right side you can see the outline for the machine

**Comment by MrDoomBringer** [comment]
oh look at that! neat, thanks.

**Comment by TemporalOroboros** [comment]
I don't really like this as it brings delta even closer to the black hole of originality that is metastation. The atmos SM was one of the only actually interesting things delta had going for it.

**Comment by Ghilker** [comment]
uh no? the SM in this one is the most original, with different setup, layers and temperature gate, the atmos room will have much more stuff going on, in addition to space. Also how is "having the SM in atmos" original or interesting? At least engi now has a job

**Comment by GuillaumePrata** [comment]
Does this also fix the Airlock access? Because everyone and their mom had access to Delta's Atmos room and it was really annoying to deal with.
Moving the SM back to Engineering just to remove engineers access to the Atmos room is good by itself, the new Atmos facility on top of that is awesome.

**Comment by Ghilker** [comment]
Yes, you can now access the SM as atmosian if there is low pop (similar to how meta works) and atmos is blocked from engies again

**Comment by Okand37** [comment]
she's not the prettiest duckling, but she'll float!! i think it would look a little nicer if it was rotated to align with the door but not necessary

i like the atmos experimentation/testing area put above atmos, i think that'll be really neat and fun to work around in

**Comment by Ghilker** [comment]
New tiny room
image

Repiped SM
image

**Comment by GuillaumePrata** [comment]
Won't that new SM Setup make it extra annoying to make internal HE since they use the 3 HE layers?
I know it isn't that much work to remove and change it back to the normal setup to be an issue, but I guess at least a layer 1 and 5 instead of 2 and 4 would be better.
Hopefully I'm not saying dumb shit since I haven't played much with the 5 layers yet...

**Comment by Ghilker** [comment]
Good point, i'll change the external ones to use 1 and 5 instead of 2 and 4

**Comment by Jared-Fogle** [comment]
bring back the laser puzzle i like it

**Comment by Ghilker** [comment]
Update: layer 1 and 5 can't be easily made in DM because of the icon_state that can't be done and i can't figure out how to do pixel shifting for mapping in DM and i don't really want to var edit, so they'll stay as layer 2 and 4 for now

I saw many people complain about the emitters puzzle saying that it was annoying, if you want i can make something but i don't know if people will be happy

Well now they have one more job instead of wandering around waiting for walls to break

**Comment by Jared-Fogle** [comment]
> I saw many people complain about the emitters puzzle saying that it was annoying, if you want i can make something but i don't know if people will be happy

do whatever u want i just like it

> Well now they have one more job instead of wandering around waiting for walls to break

atmos players weren't the ones doing the sm anyway, everyone just breaks into the room to steal n2 (a pr made like 2 days ago resolved that, but eh) because they have the skill chip or the jaws of life that delta gives you for some reason

**Comment by zxaber** [comment]
Those vents and scrubbers being in different layers serves no real purpose and will just be more things that need changing for custom setups. Is there anything wrong with using layer 2 like other maps?

Delta's current emitter room is probably the coolest one we have. If you're even a little bit clever with angles you can get all nine emitters to work using only the round-start reflectors provided.

**Comment by Ghilker** [comment]
i don't agree that much, i kinda dislike that particular emitter room, but i'm putting up a poll to see what people think about it
[Poll: Do you like current deltastation SM emitter room?](https://tgstation13.org/phpBB/viewtopic.php?f=10&t=28054)

**Comment by Ghilker** [comment]
I've decided to make the emitter room much more unique
image

**Comment by LemonInTheDark** [comment]
Keep in mind that flow wise having things be diagonal does actually change things, the engine will get more cold air second tick, and its hot air will get drained faster

**Comment by Ghilker** [comment]
Current SM (should really update the main images lmao)
image

**Comment by zxaber** [comment]
There doesn't seem to be any real reason to use different layers for the scrubbers and vents inside the chamber except for the sake of it. You're not really saving any room since the size of the chamber isn't due to the pipes, and the rest of the loop is all on layer three anyway. Really, you're just putting extra work onto people that want a custom setup, since they'll now have to rip up and replace all the vent and scrubber piping if they want to use heat pipes in the camber (as those pipes cannot be placed on layers 1 and 5)

**Comment by Ghilker** [comment]
Oh no, how dreadful of me trying to make a SM that is both original and  that teaches new players that layers exists and how to use them, dang how will i cope with the thoughts of people having to use the wrench to remove 6 pipes to allow them to make a custom SM.. oh the pressure

**Comment by MrDoomBringer** [comment]
i mean we can teach players that layers exist in ways other than "here are some layers that you need to remove if you want to make a custom setup"

**Comment by taylorbarrera** [comment]
I think I'm with DoomBringer on this one. I don't think we need to add more reasons for people to avoid modifying the loop. I'm also not crazy about the piping running under the SM itself, I feel that will lead to a higher than normal amount of people dusting their wrenches and rpds into the SM. Feels like gate-keeping more than it does lesson-teaching to me at least.

image

I kinda liked that one. Feels like a good compromise for both viewpoints.

**Comment by tgstation-server** [comment]
Your Fix/Feature pull request delta is currently below zero (-6). Maintainers may close future Feature/Tweak/Balance PRs. Fixing issues or helping to improve the codebase will raise this score.

**Comment by Kaffe-work** [comment]
Soulless

**Pull request merged**
