### PR TITLE
Armour Value Changes

### PR DESCRIPTION
**Pull request by Steelpoint**
This PR puts forward several armour defense value changes I wish to propose.

As a forword, nothing in this PR is fixed and all is subject to change. This PR is meant to show case my proposed PR changes, and justification, as well as to facilitate discussion on this issue. My position is clear in that I feel the current armour defense is too little.

I know this will be controversial but I wish to get some good discussion out of this, so leave the shitposts to singulo please. 

Also, this PR currently only touches armour used by station personal, I feel antagonist armour is very strong as is but no one has discussed if antag armour should be changed. 

Overall I feel enough people agree that current armour is too weak to at least allow for a PR of this kind to exsist to generate discussion and see if we make make armour a bit better. My proposals don't boost armour back to the pre-nerf days, but they take them to a nicer middle ground.

Link to relevant forum thread: https://tgstation13.org/phpBB/viewtopic.php?f=10&t=6763

---

Following changes are effected.

**Armour Vest+Helmet**
Old Value: melee = 25, bullet = 15, laser = 25
New Value: melee = 40, bullet = 30, laser = 30 (Vest is 30)

(This affects Security Officers, Detective, The Warden, the HoP and the Bartender)

Reasoning:  The main justification here is the buff to the bullet protection, a direct hit on the chest or head will deal 30% less damage, in cases of weapons like the Revolver this will force the attacker to either aim for the external limbs or to hit the target a third time to crit someone wearing a armour vest. 

Security Officers will take three revolver rounds to crit instead of two. The melee boost also gives reasonable protection to a wearer unless external limbs are being targeted. Laser protection is only a minor boost for consistency

**HoS Jacket + Beret**
Old Value: melee = 30, bullet = 30, laser = 30
New Value: melee = 60, bullet = 50, laser = 50 (50 melee for jacket)

Reasoning: The HoS is meant to represent the best of security, and his old defense values were barely better than a stock armour vest. These new values will mean it'll take some real considerable effort to kill the HoS (or just stun him and strip him).

I feel currently the HoS, considering him being the most targeted and stress inducing job on station, is very squishy against attacks. I believe this buff will go a long way into making the HoS far more durable.

**Bulletproof and Riot Helmet** have both had their values buffed to match the Chest pieces values.
So Bulletproof Helmet from 40 to 80
And Riot Helmet from 41 to 60.

### CODE REVIEW

**Comment by Steelpoint** [comment]
Also this PR complies with the new rules of the Freeze.

**Comment by optimumtact** [comment]
Lets try to keep it civil

**Comment by WJohn** [comment]
Third time's the charm, right?

Or is this the fourth?

I've lost count.

**Comment by lzimann** [comment]
who really cares about armor tbh, just rush everyone without caring

**Comment by Cebasiz** [comment]
it doesn't bother me. does anyone think that sec is too strong?

antagonists have surprise and powerful weapons on their side, and something does need to be done about sec population.

at least, i don't think it'll break things horribly so why not give it a try

**Comment by Steelpoint** [comment]
Right now I think security is at its worst population wise.

All Security roles (sans Detective) have some of the lowest popularity rates in the game and I'm often seeing (on Sybil at least) rounds with forty or fifty people with barely one or two people in Security.

Security is just not a popular role at all and I think these small buffs may help at least give a nice protection boost to security players.

**Comment by Bawhoppen** [comment]
I'd be fine with a security buff after coiax finishes datum antags (i believe in him), but armor isn't the way I'd want to do that, I'd be fine with a minor armor buff atleast

Also what about SWAT armor you gonna fuck with that

**Comment by Steelpoint** [comment]
SWAT armour is not something normally found on station. 

With respects to datum antags, I'll wait until I see it. If datum antags massively shifts the balance paradigm of the game far enough it can be just as easy to alter these figures after the fact.

Until then I'm doing this with the game we have now, not the game we may have months down the line.

**Comment by Bawhoppen** [comment]
coiax is a madman its going to be merged before you think

also SWAT armor is ordered like every wardec ops, but it is pretty good already

**Comment by Imagebard** [comment]
>but armor isn't the way I'd want to do that

Do you believe that in TGstation the default Security armor is worse than some craftable armor for anyone willing to hunt some mobs?
Like, crikey.

**Comment by PKPenguin321** [comment]
Armor is fine :-1:

**Comment by Steelpoint** [comment]
How so PKP?

Why do you believe station armour is fine as is?

If you honestly think security should be squishy and barely be able to take one more melee hit to die then that's a valid position to hold, I just believe that continuing down this road is just driving good veteran players away from security.

**Comment by KorPhaeron** [comment]
@Imagebard 

Yeah the vest should be stronger. I'm not sure riot and HoS armour need to be stronger though

**Comment by PKPenguin321** [comment]
I think armor is fine because it is. Sec is more durable than regular crew but not walking tanks. This is as it should be, and it is fine.

**Comment by Imagebard** [comment]
The biggest thing here, in my opinion at least, is that the armor only covers the chest and groin area and is bad with defending against bullets, so its best used for blocking lasers.

Adding the body_parts_covered = LEGS|ARMS flags to the armor would be my suggestion to buffing security armor. If it breaks immersions too much, its always possible to add knee pads and elbow protection to the sprite in-game.

**Comment by Boredone** [comment]
So, quick complaint. With the current values, HoS gear is Riot Armor+, same melee defense and coverage on both, but HoS gear has more defense against other stuff as well.
While I can understand making their armor tough, just as good as the specialized gear?
Though checking, Cappy's armor actually already had the same value, just didn't cover everything. Huh.
Also, you didn't touch the Warden and HoS's hats, most likely cause they are in the Job file instead of the Helmet file.

**Comment by Supermichael777** [comment]
The vetren sec players left 2 years ago. its a wasteland now

**Comment by Steelpoint** [comment]
I haven't got to the HoS hat but that's going to be identical to the HoS Jacket.

I'm of the school that the HoS should not need to swap out his uniform sans for getting his unique Hardsuit.

**Comment by Steelpoint** [comment]
Also this PR is not making Riot Armour more stronger, its simply making the helmet match the armour values. Since beforehand what's the point of having 60 def chest when your head is 20 points or so weaker and anyone would just aim for the head by default?

**Comment by Steelpoint** [comment]
Razharas, I already put up a fix PR before hand as part of the freeze rules.

**Comment by Steelpoint** [comment]
https://github.com/tgstation/tgstation/pull/18098 is the fix I put forward, it was just merged very fast.

**Comment by Steelpoint** [comment]
Any further thoughts on this PR?

I feel it at least warrants a brief run period, it can be easily reverted if we find security to be far too durable to antagonists.

**Comment by pudl** [comment]
My thought is that jumpsuit armor should be removed and armor buffed to compensate.

**Comment by pudl** [comment]
Also @Steelpoint maybe a new feature for armor would be a1? Im thinking of smaller caliber bullets not being able to pierce standard armor so for a small time antag like a traitor they have to get armor piercing bullets, but nuke ops or a ling can completely supersede it

**Comment by Jalleo** [comment]
I think this is a fair compromise since there is limb decapitating now.

**Comment by optimumtact** [comment]
@Shadowlight213 @Jordie0608 @MrStonedOne @KorPhaeron 

Requesting 4 day game poll with support/no support/don't care
options thank you.

If at the end support > no support this pr will be merged, don't care votes will be discarded

**Comment by KorPhaeron** [comment]
I'd rather just buff vests and not give near melee immunity with 0 slowdown out to everyone.

It won't make security any better off when dealing with antags (guns, slips, stunprods) but it will fuck with things that rely on melee with no stuns (cult constructs, stands, lavaland, I think some clock cult stuff, and I'm sure plenty more).

Buffing armour against straight melee damage (the weakest kind of attack in the game) just seems counter intuitive to me. It's almost never just straight melee attacks that take me out when I'm security, unless it's an RNG knockout, and that bypasses armour anyway.

The potential upsides just don't seem worth the potential downsides.

**Comment by Steelpoint** [comment]
The melee immunity is only conferred to the HoS. Rest is to the Riot Armour.

40 melee protection on just the torso and head is a good defense, but only for melee I feel is fine. Don't forget you can still aim to decap the arms or legs which are not covered by the vest.

Cult Constructs have a LOT of advantages over sec, the Wraiths can jaunt very rapidly, the Jugg's are nearly immune to laser weaponry and the Constructs have a inbuilt Magic Missile. Lavaland is irrelevant as Ash Walkers versus Security is hilariously one sided outside of low pop and the Clock Cult has a whole bunch of stuns and powerful items.

If 40 melee for the vest is too much I can drop it to 30 to match the Bullet and Laser defense.

**Comment by Steelpoint** [comment]
I mean if we're going pure maths then I should point out weapons like the Esword already have Armour Piercing so they already ignore a whole bunch of armour.

Security should not be that vulnerable to grey shirts with make shift spears by themselves, and you can still decap or impale sec.

**Comment by Bawhoppen** [comment]
did you know you can do incremental change? buff it a tiny bit, then buff it again in another PR, I know the reason we don't think to do this is because psychologically it seems like its even worse, but if we make it commonplace it would be a good standard to follow

**Comment by Steelpoint** [comment]
I think bigger changes first, followed by incremental changes after, would be better. Having a large sudden change to something makes the change more noticeable and impactful, thus more likely to get better feedback (or feedback in general)

People are less likely to notice a change effected over several months in very small incremants, versus one sudden change in a single PR followed by other PR's that change the numbers based on feedback.

**Comment by KorPhaeron** [comment]
I meant PVE mobs on lavaland. You put on a riot suit roundstart with these new numbers and you'll be essentially immune to most of those creatures. Very cheap in cargo as well.

I'll merge a buff for the vest (whether raising values or making it cover arms and legs) and I'd merge a buff for security hardsuit armour bullet values but I think riot and HoS are fine as is

**Comment by Steelpoint** [comment]
I'm disappointed, the HoS's armour is barely any different to a standard vest, sans it covers more of the body and has actual laser defense.

I'm also disappointed no one even went with oranges idea of a in game poll, or at least a trial. Those are easy to do now days.

**Comment by Steelpoint** [comment]
Also if I were to buff the sec armour vest to what you propose it would be almost literally identical to the HoS's jacket.

**Comment by KorPhaeron** [comment]
I guess I misread then. Sorry.

I still think only the vest really needs a change, I would merge such a PR if you made it alone.

**Pull request closed without merging**
