### PR TITLE
Gates space lube behind banana juice

### PR DESCRIPTION
**Pull request by Supermichael777**
Because invisible damaging stuns are awful and should just be removed outright, but its used in like a million places.
Full disclosure i did get memed and coded in anger.

### CODE REVIEW

**Comment by WJohn** [comment]
It being invisible is the real problem here, not it being easily accessible.

**Comment by bustygoku** [comment]
Make it have the same effect as water, being a superior water you can't walk over is still funny because people will walk and still slip and that's pretty much comedy gold!

**Comment by WJohn** [comment]
Maybe someone can expand the whole "water sheen" effect to every chem, or at least to something more than just water. It's already grey, so greyscaling it doesn't seem too outrageous.

**Comment by Supermichael777** [comment]
I don't know how to make the overlay appear but space-lube being a three default reagent chem was awful 2 years ago but somehow its survived every chem and stun rebalnce sense practically untouched.

**Comment by bgobandit** [comment]
ITT: i ded pls nerf

**Comment by Lumipharon** [comment]
Rage coding aside, I do agree it should at the very least be visible like water.
Having absolutely no way to tell there lube is on the floor is pretty gay.

**Comment by Cookiesndip** [comment]
-1. It's been here forever. It's a double-edged sword, being a territory denial tool without visiblity means that you don't know when it's gone, meaning deploying it can VERY easily result in you slipping yourself (especially since noslips/magboots do not provide immunity). Furthermore, it requires chemistry, and is very obvious who made it and is deploying it. Making it visible is actually a net buff, surprise, surpirse, since it also lulls victims into a false sense of security by walking, whilst also allowing the assailant to know exactly when the lube is gone, effectively removing the major downside of using lube.

It's balanced as-is. Seriously, I'm sick of you guys ragenerfing everything across the board that you can get departmentally. Very little of viability is left in chemistry after grenades were nerfed to the point of almost universal uselessness, syringes are basically useless sans for the quick and dirty mute since phlog was nerfed, and normal poisons take forever to kill limiting their usefulness severely. All that's really left are the utility chems - healchems, thermite, and spess lube.

**Comment by Anonus** [comment]
Thermite got nerfed too :^)

**Comment by Iamgoofball** [comment]
>and normal poisons take forever to kill limiting their usefulness severely

didn't I just buff all the poisons recently

**Comment by Fox-McCloud** [comment]
:-1: 

It's been this way for years, literally YEARS, without many complaints. Why now?

I could see an overlay being added to it (a light light blue one or something, distinctively different from water), but nerfing the recipe like this is really stupid.

**Comment by Supermichael777** [comment]
wow that was far more negative then expected.

**Pull request closed without merging**
