### PR TITLE
Replaces Marauders with Brazen Bolters (and maybe an AOE tower or something like that)

### PR DESCRIPTION
**Pull request by ghost**
:cl: armhulen
add: Clockwork Cultists can now summon Brazen Bolters, beware.
del: They can't summon marauders anymore because Ratvar thinks they're dumb.
/:cl:

 ## SHIT I STILL GOTTA DO:
Remove the remnants of marauders (this certainly isn't the whole thing)
Actually add Brazen Bolters
Test balanceeeee

 ## WHY?
"Lets have a base defense gamemode but instead of building a base they just murderbone with infinite spawning murdershells"

I want to let the person working on the gamemode have their dream of what they want out of the gamemode come true, but:
"I'm currently burnt out on clockcult"

They don't want to take the steps to make it a good gamemode, or really change it at all. This pr will require a lot of testing but I believe it's a step in the right direction. And if we can't agree on either my pr or something xhuis puts out i'm going to start lowering the gamemode chances, the best part of it is the assault on reebe and the rest is stupid garbage conversion and marauder spam.

 # Brazen whats?
Brazen Bolters are emitters, basically. They'll be a great addition, maybe i'll add some reflectors too. I'm also thinking of a tower that shoots all around it for 1 or 2 tiles but that's if I have time.

### CODE REVIEW

**Comment by tgstation-server** [comment]
You currently have a negative Fix/Feature pull request delta of -3. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

**Comment by Armhulen** [comment]
Yeah yeah bugger off i'm saving a gamemode

**Comment by ChangelingRain** [comment]
xhuis made a lot of changes that absolutely required followup that they just didn't fucking get at all, like replacing geis and making scripture use power.
plus silly stuff like abscond existing at the same time as spatial gateway.

**Comment by Armhulen** [comment]
i want him to have his way with his gamemode but like, it's in a really bad spot right now

**Comment by KorPhaeron** [comment]
>You currently have a negative Fix/Feature pull request delta of -3. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

owned

**Comment by GunHog** [comment]
It would be nice if the Steampunks could keep some sort of ghost role besides the two builder scarabs. Maybe something that helps with scouting or damaging station infrastructure? One of the things I like most about the cults is that they have options for using ghosts. Is there a way we can keep that without it being unbalanced?

**Comment by Armhulen** [comment]
I like the clockcults sabotaging the station but we should hold off on conversion really.

**Comment by Spaceinaba** [comment]
honestly you can sabotage the station just fine with a screwdriver and a crowbar

**Comment by praisenarsie** [comment]
>saving a gamemode

you're making this gamemode ten times easier for the clockcult. the op hippie mech for clockcult is way better than this.

**Comment by Armhulen** [comment]
that's why i don't like them having armor and spears too

**Comment by Armhulen** [comment]
@praisenarsie >removing the cheaper than walls marauder spam
>easier
?

**Comment by Repukan** [comment]
You currently have a negative Fix/Feature pull request delta of -3. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

**Comment by praisenarsie** [comment]
you should know why this is going to make clockcult easier. think about it. i'll give ya hint for now, _emitters and autismbases go well with each other._

@repukan that joke was funny 3 prs ago. now it's not.

**Comment by KorPhaeron** [comment]
It isn't a joke though, it isn't hard to make three grammar fixes if he wants to make another balance PR

**Comment by praisenarsie** [comment]
i thought grammar doesn't give gbp

**Comment by KorPhaeron** [comment]
It gives 1 per grammar fix PR, we made it as easy as possible for people to stay in the positive

**Comment by Armhulen** [comment]
Now it's just disheartening

**Comment by Armhulen** [comment]
Ok ok fine I'll look for some grammar problems later today

**Comment by praisenarsie** [comment]
listen, just stop chopping a feature from the gamemode that was just finished. inform @Xhuis or discuss with the playerbase if they think marauders are op.

**Comment by Xhuis** [comment]
No, Arm's talked about wanting to do something like this for a while now. I'm fine with seeing how this change goes out, especially given that I currently lack the motivation to work on it. I still stand by that the mode is in a good state right now, though, and I wish you'd stop acting like it's the end of the world that it has problems. You might be a headmin, but you still have a bit of that doomsayer in you.

I can probably make something like this PR if you have sprites and an idea of what you want done with them, as it seems you kind of lack the ability to.

**Comment by Armhulen** [comment]
I got sprites for the Blazen Bolter, if this is closed before I get my fix pre up I'll send em all over

**Comment by DoctoreMad** [comment]
Why not let Xhuis do it so you don't lose you are points?

**Comment by Xhuis** [comment]
>I got sprites for the Blazen Bolter
>**Blazen Bolter**

**Comment by Doppeltongue** [comment]
Blazin' Bolter: a brass structure that fires bolts of pure space drugs at non-cultists, subduing them with the sheer power of Duuuuuuuuude, and totally converting anybody who expands their minds to the, like, true nature of reality, woaaaaaah.

**Comment by Xhuis** [comment]
Smoke steam erryday.

**Comment by AnonymousNow** [comment]
It's sad to see a ghostrole go. Maybe its assets can be reused somewhere else.

People were asking after other ghostroles for clockwork cults. Why not, y'know, scarabs? Give them the ability to reach stationside and recite some scripture pertaining to building things like stargazers, give them the marauders' old limitations on number based on conversions and nix the ability to shoot/use weapons.

**Comment by Xhuis** [comment]
Scarabs were a massive balance debate when they existed in replenishable forms, because they were either junk and only good for repair or taser-wielding terrors of the night that could ventcrawl. I suppose something could be done if power is tweaked to be more valuable like I'd wanted to do originally, but otherwise I think the static 2-only is a nice balance.

**Comment by uraniummeltdown** [comment]
Bring back soul vessels
You can already spam posibrains in RnD/Robotics and anyway you still need an AI frame or borg shell

**Comment by ExcessiveUseOfCobblestone** [comment]
@Korphaeron depending on how you look at it this could be a fix to a gamemode :^)

**Comment by Armhulen** [comment]
TY cobby, 80 monkeybucks have been added to your account.

**Review by ExcessiveUseOfCobblestone — CHANGES_REQUESTED** [review]
You need to remove the script you webbitor FUCK

**Comment by davethwave** [comment]
I think this can be a positive feature for the gamemode, I'm just unhappy to see the ghost roles go.

**Comment by Armhulen** [comment]
everybody likes blood cult so clock cult is fine i guess i gotta work on thingling anyways

**Pull request closed without merging**
