### PR TITLE
New Packaging Icons

### PR DESCRIPTION
**Pull request by Mey-Ha-Zah**
## About The Pull Request

Fikou told me Wrapping and Packaging Icons needed updating, so I updated them. The Bow for it was a version of Pigeon's bow with a few modifications. 

image

## Why It's Good For The Game

Causes the packaging style to now match the standard 3/4 style.

## Changelog
:cl:
imageadd: Updated Wrapping Icons.
/:cl:

### CODE REVIEW

**Comment by flowercuco** [comment]
you GOTTA remember to put screenshots in the op!!!!!!!!

**Comment by Mey-Ha-Zah** [comment]
I also left the Shitty wrapping thing largely untouched because... it was just so shitty I loved it. Though I did add a few 'tape' pieces to it.

**Comment by Wallemations** [comment]
Would it be possible to swap the palette of the wrapping paper spool itself to be closer to the palette of the boxes?

**Comment by Mey-Ha-Zah** [comment]
Updated to include the wrapping paper now.

**Pull request merged**
