### PR TITLE
Changes the broken floor sprite

### PR DESCRIPTION
**Pull request by Bawhoppen**
Makes it that black and purple checkerboard pattern from other games. Now we can have broken things be a reference in and of themselves. 

(Real reason: People can identify it's a broken easier as it blatantly stands out being not correct)

### CODE REVIEW

**Comment by Bawhoppen** [comment]
>already conflicting 

W T F

**Comment by Niknakflak** [comment]
Where is the picture, why even make the pr without them

**Comment by nicbn** [comment]
It's not broken floor, it's the floor base turf.

**Comment by Bawhoppen** [comment]
@nicbn It isn't supposed to show up ingame unless something breaks (unless I'm wrong and some advanced things happen that I don't know of)

@Niknakflak 
image

**Pull request merged**
