### PR TITLE
Beret Resprites Mk. II

### PR DESCRIPTION
**Pull request by pireamaineach**
Old:
OldBeret
BeretOld
BeretOldNorth
BeretOldWest

New:
NewBeret
BeretNew
BeretNewNorth
BeretNewWest

:cl:
imageadd: Adds new sprites for all berets.
imageadd: Adds the sprites for the archaic and vintage berets.
imagedel: Removes old sprites for all berets.
add: Adds the archaic and vintage berets, the vintage one being the current one and the archaic one being the one from 2014.
add: Adds the vintage and archaic berets to the autodrobe.
/:cl:

Commits FuCK

### CODE REVIEW

**Comment by pireamaineach** [comment]
oh god oh fuck

**Comment by optimumtact** [comment]
you're spamming IRC

**Comment by pireamaineach** [comment]
Nice.

**Comment by HomocidlePancakes** [comment]
I am a mime main. I do not like how the new sprite covers a part of my eye.

**Comment by pireamaineach** [comment]
As a mime main, I prefer it.

Do look at the rest of the sprites using the sprite difference bot before leaving a dislike, the side views are drastically improved.

**Comment by pireamaineach** [comment]
Wait a minute... the sprite difference bot isn't working on this P.R.

**Comment by pireamaineach** [comment]
Weird. Can someone add the sprites tag?

**Comment by pireamaineach** [comment]
Okay, now check out the sprite difference bot.

**Comment by HomocidlePancakes** [comment]
Yeah. Side ones do look better. But I stll don’t like how the front one covers the right eye. Could you keep the old front sprite?

**Comment by pireamaineach** [comment]
That'd be inconsistent with the side views and as is it looks quite nice, only caveat being that the top of the eye paint being covered for mimes isn't ideal.

If a few people say they don't like it I might see about changing it.
I could make the french beret have special sprites, more like a french beret rather than a western military one.

**Comment by HomocidlePancakes** [comment]
2 sprites that are supposed to go together (mask and hat in this situation) shouldn’t obscure each other.

**Comment by ATH1909** [comment]
Why not just add this kind of beret as an item in the costume vendor?

**Comment by pireamaineach** [comment]
I don't think that it obscures it that badly, and I'm fairly sure ATH is either kidding or mentally handicapped.

You want me to add a whole new set of berets which are only negligibly different from the old ones, instead of just respriting the old ones?

**Comment by pireamaineach** [comment]
Also the berets aren't necessarily supposed to go with the mime mask.
Regardless I think I'm going to make the French beret have it's own sprite.

**Comment by Tlaltecuhtli** [comment]
why not make it a togglable style

**Comment by knacker48** [comment]
Toggle style seems like the best compromise. Although if you did that then which one would be the default?

**Comment by ExcessiveUseOfCobblestone** [comment]
who cares, that's the whole point of the friggin toggle lol

**Comment by pireamaineach** [comment]
I'm not going to add whole new sprites for something that's nearly exactly the same.

That's dumb, it's needless.

**Comment by knacker48** [comment]
Isn't that what your doing right now?

**Comment by pireamaineach** [comment]
No, it's not. It's resprites, quite drastic ones on the side view.

**Comment by ExcessiveUseOfCobblestone** [comment]
It's not new sprites, it's just ones that have been edited so they _appear_ new

**Comment by pireamaineach** [comment]
New to /tg./
I modified the sprites from T.G.M.C.

**Comment by nicbn** [comment]
Why?

**Comment by pireamaineach** [comment]
Because the current ones look bad, espeically the side views.

**Comment by ATH1909** [comment]
> Toggle style seems like the best compromise. Although if you did that then which one would be the default?

The old one, so that we won't have to use different mime sprites in our SS13 memes.

**Comment by pireamaineach** [comment]
I've got an idea, give me a hot minute.

**Comment by ExcessiveUseOfCobblestone** [comment]
I don't think I own any minutes, and I certainly haven't left any in the oven!

**Comment by pireamaineach** [comment]
Out a' luck, then.

**Comment by pireamaineach** [comment]
Some grammar issues here, I'll get it in a minute.

**Comment by Bawhoppen** [comment]
These seem to be a sideways step in my opinion. They're not particularly better, but aren't any worse either. 
While it's definitely more consistent, the shape seems a little odd based on what a beret should look like. SS13 sprites are supposed to be caricatures in some fashion also rather than strictly realistic and fair reality-to-pixel proportions. I am not sure what exact changes you would need to make to improve them though. I think you could ask @WJohn for some help, if they're not busy that is.

**Comment by pireamaineach** [comment]
I have no idea what kind of berets you people are looking at.

**Comment by anconfuzedrock** [comment]
snowflakey as FUCK

**Comment by pireamaineach** [comment]
My apologies for trying to make the game look better. Just let massive clipping issues sit.

**Comment by Dorsisdwarf** [comment]
What a load of bikeshedding in this thread

**Comment by ExcessiveUseOfCobblestone** [comment]
I hate PRs that make me go "ok" so i'll give this 24 hours then fall back on democracy (close atm) unless another maintainer touches it first.

**Comment by pireamaineach** [comment]
Most of the down votes are outdated though.

**Comment by ExcessiveUseOfCobblestone** [comment]
oh I was looking at an older commit, didn't see you separated them.

cringe i need more coffee

**Pull request merged**
