### PR TITLE
Paradox bag sprites director's cut

### PR DESCRIPTION
**Pull request by itseasytosee**
project card link -> https://github.com/tgstation/tgstation/projects/6#card-2128039
## About The Pull Request
ezgif com-video-to-gif
ezgif com-crop
the arc is complete I learned gifs

## Changelog
:cl: itseasytosee
imageadd: new paradox bag sprites
/:cl:

### CODE REVIEW

**Review by Mothblocks — DISMISSED** [review]
code 👍

**Comment by Timberpoes** [comment]
@Twaticus Awaiting sprite approval from you before we merge this!

**Comment by Twaticus** [comment]
its still just a black blob 😔

**Comment by itseasytosee** [comment]
I'm gonna give it one more shot

**Comment by itseasytosee** [comment]
image
image
Imagine these but animated

**Comment by itseasytosee** [comment]
@Twaticus

**Pull request closed without merging**
