### PR TITLE
buffs the cybernetic heart

### PR DESCRIPTION
**Pull request by Fhaxaris**
## About The Pull Request
Injects reagents on crit instead of unconsciousness, because for some reason it didn't do that.
The heart will restart after being EMP'ed in at least 20 seconds based on emp severity instead of stopping forever.
The heart will take damage based on emp severity, like all other cybernetics.

## Why It's Good For The Game
Cybernetic hearts are pretty useless right now and I don't think anyone actually uses them due to the fact that if you get EMP'ed you are dead. Making the cybernetic heart not instantly kill you would be good. 

## Changelog
:cl:
tweak: cybernetic heart will restart after 20 seconds instead of stopping forever
tweak: cybernetic heart takes damage from emp like other cybernetics
tweak: heart injects epinephrine on crit instead of unconsciousness
/:cl:

### CODE REVIEW

**Comment by CPTANT** [comment]
cybernetic lungs and liver are also useless. 

Make the upgraded lungs give you Nobreath and give the upgraded liver a very small toxins heal.

**Comment by Fikou** [comment]
didnt someone already try to do this

**Comment by Fhaxaris** [comment]
I tried this earlier but I coded it in a really janky way so it got closed

**Comment by Dawson1917** [comment]
Dunno about ephedrine. Will it even speed you up, at all, when you're nearly in crit and have massive damage slowdown? Atropine is a fantastic chem for the cyber heart to give on crit, but I will still never, ever have one because a single stray EMP is death. I'm sure the majority of people share this opinion.

It might be time someone overhauls the effect of EMPs on cybernetics. "Let's buff them because one ion/EMP is guaranteed death" is a shitty thing to balance around, always.

**Comment by Fhaxaris** [comment]
instead of the emp being permanent heart stop, it could restart after 10 to 20 seconds so you would still be in crit after, but you wouldn't die.

**Comment by dr-bee** [comment]
Balancing it so an EMP is instacrit that you eventually come out of due to the drugs it auto-injects is a significantly better downside than the instant death it was before. It still makes EMPs a valuable weakness if you intend to fuck someone up with cyber organs but doesnt make random untargeted EMPs that so many antags get deadly.

Be sure to test it to make sure that you can actually recover from the EMP naturally. 20 seconds is a long time and the chems might have metabolized by that point.

**Comment by Fhaxaris** [comment]
It will crit you for 20 seconds, and then about 10 seconds later you will wake up and be at low health

**Comment by Detective-Google** [comment]
> cybernetic lungs and liver are also useless.
> 
> Make the upgraded lungs give you Nobreath and give the upgraded liver a very small toxins heal.

Cybernetic livers have a larger toxin ignore threshold, are more resilient to damage overall, and have a higher health pool
Cybernetic Lungs (used to) allow you to breath on lavaland/low pressure etc, however with randomized lavaland this doesn't always work anymore.
👍 to the EMP restart, right now getting EMPed with one requires a full transplant
👎 to the amount of chemicals, just epi or just atropine is good, rest are overkill

**Comment by anconfuzedrock** [comment]
it's a literal fucking heart transplant dude nobody would get this without good reason

**Comment by KetasDotepasto** [comment]
Cybernetic Livers are so powerful, that they allow you to live through a lethal injection. You won't even fall into crit.

**Comment by Fhaxaris** [comment]
oops, i am retarded and deleted the fucking branch

**Comment by PKPenguin321** [comment]
don't say the R word you fool

**Comment by ExcessiveUseOfCobblestone** [comment]
atropine alone will carry you, not sure why you need salbu/omni on top of that.

**Comment by ExcessiveUseOfCobblestone** [comment]
what was wrong with epi on normal guy?

**Comment by ExcessiveUseOfCobblestone** [comment]
honestly just having cybernetic hearts have more HP will make them immensely useful now that defibbing is oriented around heart health.

**Comment by Fhaxaris** [comment]
I removed the epinephrine from the normal cybernetic heart because I think it should just be an artificial version of the heart.

I think it should be a powerful way of avoiding death. We already have regen coma from virology, and that makes everyone wolverine when they go into crit without any vulnerabilities. Regen coma can spread to everyone on the station very quickly, while a cybernetic organ only effects one person and must be implanted through surgery. I do agree in that the salbutamol doesn't really fit, nor does the ephedrine. I think I will just have it be atropine + omnizine.

In my opinion, we shouldn't even have a normal cybernetics and upgraded cybernetics, especially since they aren't even that far apart in the tech-web, I don't think anyone will actually use the normal one due to the fact that you can always use the upgraded one instead.

**Comment by ExcessiveUseOfCobblestone** [comment]
>I removed the epinephrine from the normal cybernetic heart because I think it should just be an artificial version of the heart.

sure

> I think it should be a powerful way of avoiding death. We already have regen coma from virology, and that makes everyone wolverine when they go into crit without any vulnerabilities. Regen coma can spread to everyone on the station very quickly, while a cybernetic organ only effects one person and must be implanted through surgery. I do agree in that the salbutamol doesn't really fit, nor does the ephedrine. I think I will just have it be atropine + omnizine.

These are not mutually exclusive, you can have regen coma plus a cybernetic heart (although I'll agree spreadable pseudo-ling revive is a bit wild).

**Comment by Fhaxaris** [comment]
I've decided that making it a powerful healing item is silly, mainly due to the fact that we already have the reviver implant.  Also considering the way medical is being changed it doesn't really fit with the way things are being developed. I decided to instead give it increased health like the other cybernetic organs and make emp heart-stopping last for a maximum of 20 seconds because dying instantly to a screen-wide AoE is very unfun. It will also now take damage from emp like the other cybernetic organs.

**Comment by ExcessiveUseOfCobblestone** [comment]
mfw little sev numbers = higher severity for EMPs

**Comment by Fhaxaris** [comment]
yea closer to one = worse. how terrible

**Pull request merged**
