### PR TITLE
Adds movement states for some cyborgs + overlay for miner jetpack

### PR DESCRIPTION
**Pull request by GunHog**
Shamelessly rips off #7111 by <b>Paprika</b>.
- Mining and Medical cyborgs will now have an animation for when they are moving.
- Janitor cyborg scubbers will only move when the borg does.
- Made mining borg jetpack an overlay.

_If you have any more borg movement states to add, I would be more than happy to accept them!_

<b> Secborgs have not been changed.</b> I am just lazy since Paprika did all the work making gifs already.

### CODE REVIEW

**Comment by WJohn** [comment]
Still love this. Though I can't say I like the secborgs' treaded office wheels? The intention to my knowledge was to make them like office chair wheels which are small and roll very easily on the smooth tiles of the station for high speed chase (and presumably being so top heavy the sec borg could easily flip over and crash into a wall when it tries to slow down or turn).

**Comment by phil235** [comment]
:+1:

**Comment by GunHog** [comment]
@WJohn as specified above the images, *Secborgs have not been changed*. Those images I stole from Paprika instead of making my own (I do not know how to make gifs). This PR shall not affect Security Cyborgs in any way, unless someone gives me a sprite set for them.

**Comment by WJohn** [comment]
Ah, perfect.

**Comment by RemieRichards** [comment]
@GunHog 
>I do not know how to make gifs

Gifcam.

**Pull request merged**
