### PR TITLE
Emagging Siliconnect allows for sending messages to borgs without an ID

### PR DESCRIPTION
**Pull request by zxaber**
## About The Pull Request
SiliConnect (the tablet app for managing borgs) requires an ID to send messages to borgs in order for the user's name to be attached to the message. This change allows anyone with an emag to remove this requirement, and instead send messages without the sender's name attached. The borg will instead see "STDERR:UNDF" as the name.

No change for the nuke ops version Roboverlord.

## Why It's Good For The Game
Allows for the user to use SiliConnect for alternative purposes. Keep the borgs busy with an anonymous threat against the CMO, or send a tip about an upcoming hit on the captain to get rid of a rival traitor. Maybe shitpost your best just to make someone actually download WireCarp for once.

Anyway, adds a neat emag function to another ModPC app.

## Changelog
:cl:
add: SiliConnect users can now emag their device to send anonymous messages to borgs. Remember to remove your ID before hitting send!
/:cl:

### CODE REVIEW

**Comment by LemonInTheDark** [comment]
Do you think it'll be used? do you plan on adding emag functionality to other apps/do they have that already?

**Comment by zxaber** [comment]
I'm trying to expand emag functionality to more apps in general, as currently only the NTNet downloader has an emag function. I added support some time ago to allow for emagging to be handled on the app-level rather than the device itself, but as of yet no new emag effects have been done.

I'd like the emag functions of apps to mainly focus on removing restrictions in interesting ways but still tie into the app's overall role (hence this one simply allowing for sending of anonymous messages to borgs which is not normally allowed).

I don't know for sure that it'll be used, but I hope that it offers at least an alternative to anonymously get the silicons attention over using a voice changer.

**Comment by LemonInTheDark** [comment]
Do you think it's a good idea to have people emag each individual program? wouldn't it be better to have emagging the computer itself cause the effect?

**Comment by zxaber** [comment]
I think it's neat thematically. It has you breaking into the programs themselves rather than the device becoming some sort of gateway to unintended features. Modular PCs are one of the few items you can emag multiple times, so if you later download a new app you can just re-emag (and there _is_ feedback on whether your emag unlocked anything new on an installed app each time you swipe).

**Pull request merged**
