### PR TITLE
Resprites microwaves

### PR DESCRIPTION
**Pull request by Kraseo**
Changes the sprites of microwaves to be smaller and no longer use a 3/4 perspective.

Comparison old and new:

### CODE REVIEW

**Comment by demonfiren** [comment]
The new ones almost look like TVs tbh.

**Comment by RemieRichards** [comment]
Eh

**Comment by GunHog** [comment]
Significant loss of detail. :-1:

**Comment by ExcessiveUseOfCobblestone** [comment]
also look like they'd be harder to click tbqh

**Comment by XDTM** [comment]
Currently they catch clicks on the whole tile for some reason

**Comment by Bawhoppen** [comment]
Losd of detail and perspective

**Comment by phil235** [comment]
Also the functionality of the microwave has been changed with my food refactor, it's a "microwave OVEN", it needs to be decently big.

**Comment by Iamgoofball** [comment]
@WJohn

**Comment by Iamgoofball** [comment]
@phil235 that is irrelevant and you know it please don't confuse the spriter

**Comment by xxalpha** [comment]
I don't like it. It is significantly less detailed and has a weird perspective.

**Comment by PKPenguin321** [comment]
>Significant loss of detail. 👎

**Comment by Nienhaus** [comment]
They're kinda small.

**Comment by WJohn** [comment]
Small, looks kind of like a television, not sure what aesthetic it's going for either.

I will likely be taking a shot at this soon™

**Comment by Kraseo** [comment]
The microwave is a bit bigger now and shouldn't sit on the edge of the ~~crater~~ tables, Thanks to Nienhaus for help with the sprites.

**Comment by Niknakflak** [comment]
Still :-1:

**Comment by GunHog** [comment]
Too small, not enough detail, this is not an improvement.

**Comment by scoopscoop** [comment]
What style is /tg/ going for anyway? The sprites are a mishmash of perspectives and sizes.

**Comment by TrustyGun** [comment]
currently most sprites are 3/4, but wjohn is attempting to move it towards 1/4 topdown (similar to goon), with a palette.

**Comment by ExcessiveUseOfCobblestone** [comment]
I really need to start using his palette REEEEE

**Comment by Niknakflak** [comment]
I dont even like goon's perspective.  If you want goonspective, go to goon, dont fuck the /tg/ style

**Comment by Delimusca** [comment]
why is it so tiny, it's like a quarter-tile in size.

**Comment by bgobandit** [comment]
wjohnston also talks about leaking cloacas are we really trusting his taste

**Comment by Kraseo** [comment]
Updated the PR with a new image.

**Comment by WJohn** [comment]
Closed due to overwhelming negativity. If you want to give it another shot or resprite it significantly, I'll reopen this.

**Pull request closed without merging**
