### PR TITLE
Fixes Meat grinder and immortality from the Wild West away mission.

### PR DESCRIPTION
**Pull request by Shadowlight213**

### CODE REVIEW

**Comment by Incoming5643** [comment]
The meat grinder kind of loses its omph these days if you know what you're doing. You can just feed it a syndicate human corpse from the first part of the mission instead of having the first guy through get blended.

**Comment by Shadowlight213** [comment]
@Incoming5643 True. The only thing I could think of would be to have a check for the mob having a key or something. Or I could make the grinder be invisible.

**Comment by Thunder12345** [comment]
Make it invisible, and move it to an earlier part of the mission, where they don't expect it

**Comment by Shadowlight213** [comment]
Eh. I like where it currently is, as you get an option. to leave the area from the gateway before the meat grinder and wish granter. Definitely going to make it invisible on the map though which will be a seperate pr. I need to wait for the map merger tweak to get merged before I continue work on it.

**Comment by KorPhaeron** [comment]
Make the meatgrinder something you have to click on, rather than throw someone into?

**Comment by Shadowlight213** [comment]
Hmm. I could make the meat grinder be the wish maker itself then. Have it need a sacrifice.
Although that would kinda remove the stalker reference.

**Comment by Supermichael777** [comment]
this is just becoming the kind of bullshit trap you want to avoid as a game designer
Would you enjoy fighting your way into the final room only to get killed by the invisible trap on the prize? and then seeing Greyshirt Mcloadstone grab it and get dat antag.

if you have no way of knowing about the trap it losses the gotcha impact of getting horribly killed by the trap.

**Comment by AlexanderUlanH** [comment]
It's fine as-is.  It rewards people who spend the time to examine the notes all over the mission, and screws up the powergaming looter who tries to speed through the mission to get to the loot.

**Comment by Miauw62** [comment]
all away missions except WJs are terrible anyway.

**Comment by KorPhaeron** [comment]
We had a lot of fun with Wild West yesterday

**Comment by Dorsisdwarf** [comment]
Make there be 2 meatgrinders in a row, have them require manual clicking. That way you gotta convince/trick two people to gib themselves  for your sole gain

**Pull request merged**
