### PR TITLE
ash drakes now take extra damage from lamarr

### PR DESCRIPTION
**Pull request by ATH1909**
## About The Pull Request

Hitting an ash drake (or lesser ash drake) with Lamarr, the RD's pet facehugger, will deal an extra 30 damage. Due to the (current) limitations of the bane element, only melee damage is affected.

A space has been added to the description of a bitrunning disk that was bugging me.

## Why It's Good For The Game

image

https://www.youtube.com/watch?v=T6eK-2OQtew

## Changelog

:cl: ATHATH
add: Lamar(r) now deals extra melee damage to ash Drakes.
spellcheck: Corrects an instance of "ashdrake" to "ash drake".
/:cl:

### CODE REVIEW

**Comment by Loafin34** [comment]
why?

**Comment by ATH1909** [comment]
> why?

my brain saw a funny reference that will become outdated in like 5 years and took the shot

**Comment by the-orange-cow** [comment]
"Alright, why is the RD dead in Lavaland again?"

**Comment by projectkepler-ru** [comment]
I don't get the joke

**Comment by Aurumdude** [comment]
> I don't get the joke

https://en.wikipedia.org/wiki/Drake%E2%80%93Kendrick_Lamar_feud

**Comment by carlarctg** [comment]
more damage, MORE

**Comment by Loafin34** [comment]
it should like kill the drake in four beats-hits

**Comment by ATH1909** [comment]
> it should like kill the drake in four beats-hits

I could technically do this by bumping the damage to 50, since that would be a 4HKO on a 200 health Lesser Ash Drake, but I don't want miners to (unironically) swap out their kinetic crushers for Lamarr when Ash Drake hunting (on Lavaland, anyway).

**Comment by Loafin34** [comment]
i mean, it's funny to have the RD be asked by miners for lamarr to speedrun drake armor.

**Comment by CCC23** [comment]
RD I need lammar WHY well I gotta kill the drake somehow

**Comment by MrMelbert** [comment]
this will certainly not be funny or even understood in a few months when everyone forgets about it

**Comment by san7890** [comment]
> this will certainly not be funny or even understood in a few months when everyone forgets about it

nah brah K-Dot beefing with BBL Drizzy is some of the stuff out dere on the streets that will live on for eternity

**Comment by san7890** [comment]
that being said it's so niche i don't really know if it matters or not to anyone but powergamers.

**Comment by ATH1909** [comment]
> this will certainly not be funny or even understood in a few months when everyone forgets about it

probably

but my hope is that, years from now, some codediver is going to look through xeno code, find the code for this, and be absolutely baffled

and then someone will send them this pr and their reaction to the joke being this stupid will be really funny

~~the "hulks take brute damage instead of burn damage from cold" pr is precedence for this~~

**Comment by Time-Green** [comment]
This is weird

**Pull request closed without merging**
