### PR TITLE
makes shadowpeople and nightmares not resist flashes

### LINKED ISSUE #48092: Nightmares are flashproof
Steps to replicate:
1: Flash a nightmare

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request
@carshalash believes this is unintended. If this is intended I'll just close this. Also I'll need a maintainer to okay this because antag freeze.
## Why It's Good For The Game
They should not resist flashes?
fixes #48092

## Changelog
:cl:PepperPrepper
fix: Nightmares/Shadowpeople can be flashed
/:cl:

### CODE REVIEW

**Comment by optimumtact** [comment]
this should be fine antag freeze approved

**Comment by carlarctg** [comment]
have you even thought about balance implications?
like i get it haha flash shadow but it's going to be such a joke to click on shadowling once and win
flashes aren't a sec or head only thing, lots of people have them, this shits on them really really bad

**Comment by PepperPrepper** [comment]
@carlarctg flashes are not that overpowered. Turning somone's screen white for a bit does not equal a win

**Comment by HomocidlePancakes** [comment]
You do realize flashes stun?

**Comment by SkeletalElite** [comment]
> @carlarctg flashes are not that overpowered. Turning somone's screen white for a bit does not equal a win

If you click someone with a flash, it stuns them

**Comment by PepperPrepper** [comment]
Well this is just proof of my unrobustness. But still if it was intended for them to be stunned then they should be stunned

**Comment by SkeletalElite** [comment]
Flashes are probably gonna get nerfed eventually anyways

**Comment by Shadowflame909** [comment]
I say keep it maintainers. This race is only slightly better then a plasma-man without his hardsuit.

A flash + a bright light is a kill. Let us continue this stun nullification.

T. Shadowflame909

**Comment by HomocidlePancakes** [comment]
@shadowflame909 The one that added eye sprites or something. Remember the short period when months became flashproof? It was a bug from that PR

**Comment by kriskog** [comment]
Yeah, these didnt use to be flash proof :eyes: They are weak to light, stop arguing to keep it in.

**Comment by necromanceranne** [comment]
The shadowman should not be immune to the intense flash of light. Big fucking yikes, powergamers out here not giving a shit about THEMATICS.

**Comment by Shadowflame909** [comment]
Fair. But I'm trying to take and keep any buffs in the game for the impossible mode race

**Comment by HomocidlePancakes** [comment]
https://github.com/tgstation/tgstation/pull/43632 This is the PR that added it.

**Comment by HomocidlePancakes** [comment]
#43661. This is the PR that added it

**Comment by Moonman121** [comment]
Nightmares being flash immune without going through the effort of stealing glasses is bad.

**Review by ShizCalev — APPROVED** [review]

**Pull request merged**
