### PR TITLE
Salt PR: Removes revenants

### PR DESCRIPTION
**Pull request by jlsnow301**
## About The Pull Request
Removes revenants from the game.
## Why It's Good For The Game
So there's a hostile midround antagonist with invisibility, wall clipping, ranged abilities and did I mention it can tank laser shots to the face and just run through walls if low?

... I do think there should be antagonists that accelerate a shuttle call but this guy is deadchat salt incarnate with almost zero counterplay.

The tiny niche interaction given to chaplains and table salt do not outweigh the pure annoyance they bring to the station.
## Changelog
:cl:
del: Removed revenants as an antagonist. Begone!
/:cl:

### CODE REVIEW

**Comment by Mothblocks** [comment]
theyre an antagonist they are supposed to be annoying and i like them

**Comment by Mothblocks** [comment]
we also straight up do not have enough light rulesets to be doing stuff like this frivolously

**Comment by Mothblocks** [comment]
salt pr is a good pun though

**Comment by Shadowflame909** [comment]
The counterplay is that they're a weak little griff ghost baby

What if you just make it so they can't get in an aoe near the chaplain/anyone in chapel garbs like the reimu clothes in the costume vending machine

That'd be quite soulful

**Comment by jlsnow301** [comment]
> theyre an antagonist they are supposed to be annoying and i like them

antagonists should be capable of being annoying and causing destruction, but this is in line with swarmers in grief

i really wish we had others that weren't like, well, this. if they couldn't be deleted, what about nerfed?

**Comment by thgvr** [comment]
Nobody tell him about nightmares and space dragons

**Comment by Pumpkinoe** [comment]
revenants have never been that difficult to ownzone when they are completely unable to enter a tile covered in holywater

**Comment by thgvr** [comment]
> antagonists should be capable of being annoying and causing destruction, but this is in line with swarmers in grief

> i really wish we had others that weren't like, well, this. if they couldn't be deleted, what about nerfed?

They used to be able to breach every external window, for free. They've already been nerfed, revenants are a minor nuisance if there aren't corpses literally lying in the halls everywhere.

**Comment by jlsnow301** [comment]
> revenants have never been that difficult to ownzone when they are completely unable to enter a tile covered in holywater

super niche interaction by one job is not a valid counter

**Comment by Pumpkinoe** [comment]
the chaplain fights paranormal stuff that's his deal
holy water is also super easy to mass produce if you have a chaplain, and you can buy it from cargo as well
revenants are annoying yes but their killing power is very low since you can effectively remove everything he can throw at you

**Comment by Shadowflame909** [comment]
> > revenants have never been that difficult to ownzone when they are completely unable to enter a tile covered in holywater
> 
> super niche interaction by one job is not a valid counter

Two jobs if you use a smoke machine and a chemist

**Comment by Pumpkinoe** [comment]
don't forget that salt can be mass produced by a chemist and used against the revenant yeah
salt both reveals them and stuns them even when they're invisible, so if you use salt smartly you can effectively ruin their day entirely

**Comment by RedBaronFlyer** [comment]
Revenants are both super slow and can be physically damaged for quite a generous time after using most of their abilities. They're also super weak to borgs until they unlock their malfunction ability. I've seen quite a few revenants get killed by extremely stupid stuff because someone just out of range of one of their attacks ran up and smacked them with a toolbox a few times.

Honestly, between nightmares and revenants (because I often see them do somewhat similar things in terms of round impact), I see Nightmares as something far, far more intimidating and troublesome. Revenants are an annoyance at their strongest, while nightmares will typically pile up a small body count from people who think fighting a shadow demon in a maint tunnel or a pitch-black room alone is a fantastic idea. (plus most nightmares will b-line for APCs to knock out station power)

**Comment by EuclidianGeometer** [comment]
i play primarily on a server that has ~16 people on average, and still revenants basically cannot do shit. in part that's just 'not enough dead bodies at that pop', but none of their abilities are extremely kill-y, and the good old salt smoke machine puts a stop to them doing anything meaningful.

Honestly, what i'd like to see is a rework that brings more flavor to them- add some of the spooky minor portent stuff goon wraith can do, give them some more powers. Wasn't Melbert working on a rework of some kind?

**Comment by Addust** [comment]
you do not deadchat salt a machine controlled entirely by deadchat salt

you also do not coderbus salt a machine formed entirely by members of coderbus experiencing deadchat salt

**Comment by Mothblocks** [comment]
i cannot even begin to parse either of those sentences

**Comment by Dorsisdwarf** [comment]
The fact that revenants can kill the AI with no risk on most maps is dumb, but also it takes so long that if nobodys come to help you in that time you're probbably an ass anyway

**Comment by Fikou** [comment]
i like them, they affect the game in small ways, and its funny to see players bring out giant smoke machines and chaplains bless stuff with a holy extinguisher
they are certainly not unbeatable, their only ability that can directly hurt you can be avoided by simply staying aware and moving away from a light (or just breaking it) and then shooting them. as a rev youre heavily punished for timing/positioning mistakes
> this guy is deadchat salt incarnate with almost zero counterplay.

yeah thats the intention
if anything, it should have a pretty low chance to spawn that increases/decreases with the amount of dead people on station, so if medbay doesnt treat people, higher chance for a rev

closing after 24 hours unless someone has more to say

**Comment by Profakos** [comment]
One thing is certain, right now revenant is tied to having minimum 20 dead mobs in the game, which can be achieved very fast by the miners. On our downstream we swapped it to three dead players, and it successfully turned it into a rare and delicious treat instead of spawning all the time.

**Comment by Sealed101** [comment]
>One thing is certain, right now revenant is tied to having minimum 20 dead mobs in the game, which can be achieved very fast by the miners. On our downstream we swapped it to three dead players, and it successfully turned it into a rare and delicious treat instead of spawning all the time.

having it tied to _any_ dead mob spawn sounds like a gaping hole in design considering the amount of corpses in space ruins/morgue/lavaland. feels like this should be addressed, could also open a way for more abilities for the revenant

**Comment by jlsnow301** [comment]
We need better mid rounds 😞

**Comment by IndieanaJones** [comment]
You can always make one yourself, The best way to get leverage in a scenario like this is to set the bar high with your own work.

**Comment by optimumtact** [comment]
good change should have been merged

**Comment by the-orange-cow** [comment]
> good change should have been merged

bring back swarmers imo

**Pull request closed without merging**
