### PR TITLE
gives icebox atmos o2 to pure pipe

### PR DESCRIPTION
**Pull request by Red-byte3D**
## About The Pull Request
Adds o2 to pure pipeline to icebox and also edits the suppyline to be easier to acsess and understand
Before
image

After

image

## Why It's Good For The Game
o2 to pure was removed(?) after the smart pipes so adding it back will let the plebians who use it be able to continue using it
editing supply line to work better with atmos space
## Changelog
:cl:
add: Adds O2 to Pure pipeline on icebox atmos and fixes air mix pipeline to take up less space and work better with smartpipes.
/:cl:

### CODE REVIEW

**Comment by Mothblocks** [comment]
Your changelog isn't correct--please follow the format in the default PR body.

**Comment by InsaneRed** [comment]
> Your changelog isn't correct--please follow the format in the default PR body.

👍

**Comment by Mothblocks** [comment]
Changelog is good.

**Comment by Nexofas** [comment]
I like this answer, rather than "just pipe it yourself on rounds lol"

**Pull request merged**
