### PR TITLE
fix xeno airlock soundspam

### LINKED ISSUE #17502: Rapid clicking airlocks as xeno causes fun noise spam
as if the sound of hundreds of airlocks were being opened at once, suddenly silenced.

### PR DESCRIPTION
**Pull request by Iamgoofball**
fixes #17502

### CODE REVIEW

**Comment by KorPhaeron** [comment]
How is this a fix

**Comment by GunHog** [comment]
This is a very poor fix (simply removing the sound), please do it properly.

**Comment by Iamgoofball** [comment]
here's why @KorPhaeron 

a "fix" would involve giving xenos a 5 second click cooldown but then we get into XENO BALANCE

a better fix is to remove the sound outright because we can't do that easily without snowflake

**Comment by Iamgoofball** [comment]
feel free to code your own fix then

**Comment by KorPhaeron** [comment]
I will just ignore it instead

**Comment by Ultimate-Chimera** [comment]
lol goofball got denied

**Pull request closed without merging**
