### PR TITLE
Makes the service cyborg competent at bartending

### PR DESCRIPTION
**Pull request by Anonmare**
## About The Pull Request
Shameless service cyborg buff, features include: a drink apparatus (can only manipulate container related to drinks/food), replacing their internal drinks glass with a large beaker for mixing and simaltenously expands and cleans up the cyborg shaker for ease of reading.

## Why It's Good For The Game
Becaus the service cyborg deserves better than this

## Changelog
:cl:
add: Service cyborgs have a drink manipulator - Rejoice!
tweak: The service cyborg shaker has more options available - show the bartender why his job will be automated away
/:cl:

### CODE REVIEW

**Comment by Detective-Google** [comment]
Borg hands borg hands :+1:

**Comment by Shadowflame909** [comment]
S M H 

automation be stealing all my job

bunny coder will one day understand when bunny borgs automate away their cravings for carrots and adorableness!

**Comment by InsaneKatrina** [comment]
THE ROBOT MENACE WILL NEVER HAVE MY BAR!

NEVER!!!

**Comment by Tlaltecuhtli** [comment]
borg should have an iv drop to attach humans

**Comment by Onule** [comment]
> replacing their internal drinks glass
RIP drinking glass synthesizer, or whatever it's called.

**Comment by Anonmare** [comment]
Odd, I can't tell why the robot_modules file is failing Travis.

@Onule It only replaces the internal drinks glass, the one you can't put down, the module can still make more drinking glasses via the Rapid Service Fabricator.

**Comment by ATH1909** [comment]
Are they getting the same kind of beaker holder module that mediborgs get, or are they directly getting a "large beaker" as a module? The latter could cause problems.

**Comment by Onule** [comment]
> @Onule It only replaces the internal drinks glass, the one you can't put down, the module can still make more drinking glasses via the Rapid Service Fabricator.

I know, the internal drinks glass can, for some reason, replicate liquids at a very weird rate. I can't tell if that's an intended feature, seeing as barely anyone goes service borgs and any of those service borgs barely make drinks using that glass?
I pretty much use it to make a bunch of hearty punch.

**Comment by spessbandit** [comment]
considering that alcohol overdose can cause negative effects and possibly damage (I don't know what state of bugginess that is in currently), how does this fit asimov

**Comment by Anonmare** [comment]
@ATH1909 Both, they're getting a subtype of the mediborg's beaker apparatus, but it can only manipulate drink bottles/glasses/cartons/condiments. As well as a large beaker, I know a shaker is more appropiate but I didn't want to cause visual confusion with the shaker synthesizer. 

@spessbandit Humans are assumed to know that alcohol is bad for their health and are capable of making an informed decision as to whether they will consume alcohol or not, hence why mediborgs can do surgery even though that is harmful and why the bar isn't locked down every shift.

**Comment by Shadowflame909** [comment]
Yeah does this remove the bartender borg gimmick of slowly regenerating any alcohol they create?

Please no Anonmare

**Comment by Anonmare** [comment]
@shadowflame909 No, you can just also use bottles as well now

I have never heard of this thing about using the drinking glass to replicate a reagent but it shouldn't change anything as beakers and glasses are cut from the same cloth

**Comment by ExcessiveUseOfCobblestone** [comment]
am i dumb or did you not actually give them the apparatus

**Comment by actioninja** [comment]
this tiny buff to an almost never played module threatens to destabilize the entire balance of the game.

**Pull request merged**
