### PR TITLE
Tgui error reporting, Keyboard passthrough, RPD, NtOS, Power Monitor

### PR DESCRIPTION
**Pull request by stylemistake**
### Improved tgui error reporting

Tgui will now show a slightly more robust, non-blocking and immersive error screen.

IE8 compatible. Nanotrasen approved.

### Keyboard passthrough

Adapted from https://github.com/yogstation13/Yogstation/pull/7001.

Browser was stealing focus from the game, and it was very disruptive. Well, now you can control your epic spaceman while tgui is open!

### Rapid Pipe Dispenser

New Rapid Pipe Dispenser UI is fast, compact, and benefits a lot from keyboard passthrough!

rpd

### NtOS

image

### Power Monitor

Damn it took a very long time to make (charts were a pain to make), but I finally did it, with a beautiful blue NtOS theme (which will be active on all NtOS-based devices later).

power_mon

## Supermatter Monitor

supermatter

## Changelog
:cl:
add: Improved tgui error reporting.
add: You can now control your character and use hotkeys while tgui windows are open.
add: New Rapid Pipe Dispenser interface.
add: New NtOS theme.
add: New NtOS Menu interface.
add: New Power Monitor interface.
add: New Supermatter Monitor interface.
/:cl:

### CODE REVIEW

**Comment by TheVekter** [comment]
> add: Improved tgui error reporting.
This is peak kino and looks very nice.

> add: You can now control your character and use hotkeys while tgui windows are open.
If this works this is an actual fucking godsend.

**Comment by MCterra10** [comment]
clearly stolen from austation who stole from yog

**Comment by stylemistake** [comment]
who stole from hippie

**Comment by stylemistake** [comment]
Phew, that's a lot of changes. Added a PowerMonitor interface, with a completely new theme. I refactored a lot of shit, so I hope nothing major breaks.

**Comment by stylemistake** [comment]
I have included a yet another CSS rework, this time to migrate to the new Sass module system (because in 2 years or so, they will deprecate the old `@import` system).

It's pretty good, and after some experimentation I have found a very granular way to theme components, with a very high control over the output. Size of CSS went down dramatically (68KB -> 39KB).

**Comment by stylemistake** [comment]
Tweaked colors a bit.

image

Waiting for reviews, I play tested this quite a bit on local and on Terry.

**Comment by actioninja** [comment]
Nothing really jumps out on a review end, all looks pretty good. Sass module migration is good, I wasn't aware that input is going to be deprecated and we have a chronic problem with things shifting under us and just shimming needed functionality instead of making proper migrations.

**Comment by nichlas0010** [comment]
image

Excuse you https://github.com/HippieStation/HippieStation/pull/12257

**Pull request merged**
