### PR TITLE
Removes unused clockwork cult icons

### PR DESCRIPTION
**Pull request by SuperNovaa41**
## About The Pull Request
and also moves them over to the sprite repo 
there were still some used, so the fluff pieces got added to `obj/fluff.dmi`, and also there was one sprite for the wall girder, the toy wrist watch and the null rod, so those got moved into their respective files.
moved the clothing to their respective files aswell.

## Why It's Good For The Game
almost all of these sprites are completely unused, aswell as the gamemode being removed from the code anyways, so they can rest in sprite purgatory 

## Changelog

nno player facing changes

### CODE REVIEW

**Comment by dragomagol** [comment]
image

Send him up to the farm with the other sprites >B(

**Comment by SuperNovaa41** [comment]
> image
> 
> Send him up to the farm with the other sprites >B(

his removal was causing maintainer distress

**Comment by SuperNovaa41** [comment]
bro what................

**Comment by SuperNovaa41** [comment]
Forgot to do clothing

**Comment by ShizCalev** [comment]
was literally about to merge.

**Comment by SuperNovaa41** [comment]
good thing you didnt

**Comment by SuperNovaa41** [comment]
Okay we're good now

**Comment by SuperNovaa41** [comment]
what a messy commit history

**Pull request merged**
