### PR TITLE
Ports the kinetic accelerator changes from NT

### PR DESCRIPTION
**Pull request by Iamgoofball**
You can reduce kinetic gun's cooldown by tweaking or upgrading it's thermal exchanger. 
Maximally upgraded gun's cooldown is 8, standard is 20.

You can increase kinetic gun's range with plasma sheets (up to 5, current is 3), but this can make your gun unsafe.

Kinetic charge is buffed a bit and can damage structures and turfs around the kinetic blast (but not station walls or mobs). This makes kinetic guns a bit better in mining.

credit goes to @ACCount12 for the code

### CODE REVIEW

**Comment by Iamgoofball** [comment]
i might repurpose some of this upgrade stuff too so that we can tinker with guns a bit more too

**Comment by Fox-McCloud** [comment]
Could utilize stock parts to upgrade it too, or something, though I get that upgrading is supposed to be done by methods the miner has access to.

Maybe it could be upgraded with silver once (-1),  gold once (-2), uranium once (-4), and diamond once (-5), instead? Screwdriver upgrading is so trivially easy that it might as well not be in and the gun just has a CD of 17--especially a week after this is patched in and everyone knows about it.

**Comment by AlexanderUlanH** [comment]
The way it looks in the code, 'tweaking' just means you just click the KA three times with a screwdriver.  Seems rather pointless.

**Comment by RemieRichards** [comment]
Screwdriver upgrades are fine, if you get them all you save a wopping 3 ticks (0.3 seconds)

**Comment by AlexanderUlanH** [comment]
All the more pointless.

**Comment by pudl** [comment]
this is cool as fuck, go suck a fatty alex lmao xD

**Comment by Fox-McCloud** [comment]
I realize that remie, but it's just one of those "total newbies never know about it, but everyone who's played this job past the first week does it at the start of the shift, so it's ubiquitous) in practice.

Upgrading it is pretty awesome, but in my opinion, it should be a resource gate as opposed to knowledge one.

**Comment by paprka** [comment]
^ make it require minerals or drops from mining mobs.

**Comment by Jordie0608** [comment]
Changelog.

**Comment by ACCount12** [comment]
Why a miner can't get some sheets for upgrades? When i was coding this, miners had an ore smelter in their base.

**Comment by Fox-McCloud** [comment]
@ACCount12 

Reason I suggested raw ores as opposed to mineral sheets is so they're not having to run all the way back to the station to upgrade convert it and upgrade their stuff as opposed to just doing so in the field--it also means it's a further tradeoff between "do I want more points or this sweet upgrade?"

**Pull request merged**
