### PR TITLE
[SPRITE] Medical Patch Colour Change

### PR DESCRIPTION
**Pull request by Steelpoint**
Minor change to better reflect what kind of damage a band aid patch will heal when applied. To help people and whatnot

screenshot 2015-01-18 01 33 38

### CODE REVIEW

**Comment by Iamgoofball** [comment]
you gotta change the sprite in the New(), other wise the inherited pill code will change the icon state to a random pill type since you commented out that shit

also this probably breaks standard patch sprites

**Comment by Steelpoint** [comment]
Done.

**Comment by Cheridan** [comment]
Should probably be a blue cross, because muh bluebay

**Comment by Anonus** [comment]
Normal patches are blue, these are just for roundstart healing patches

**Comment by Fox-McCloud** [comment]
Eh, I don't like this; patches should be white that are empty and take on the color of the chems injected into them.

Just make the center color of the patch match the color of whatever chemical is inside/injected into it--much like how beakers get a color change.

**Comment by Iamgoofball** [comment]
i don't have colors assigned to the chemicals yet, that was gonna be one of the final things

**Comment by Fox-McCloud** [comment]
@Iamgoofball 

Fair enough; understood.

**Comment by Steelpoint** [comment]
Red is for Brute
Yellow is for Burn.

I've also got a Green patch if we add in a anti-toxin patch.

This PR is meant for usability, players are going through a lot to understand the new system and anything we can do to help would be great.

**Comment by paprka** [comment]
blue should be for brute, bruise packs used blue

**Comment by Steelpoint** [comment]
I'll let Goofball deal with this. He seems to have a idea in mind for patches, I hope.

**Pull request closed without merging**
