### PR TITLE
The Ark of the Clockwork Justicar is easier to summon

### PR DESCRIPTION
**Pull request by ChangelingRain**
:cl: Joan
experiment: The Ark of the Clockwork Justicar now only costs 3 of each component to summon, but must consume an additional 7 of each component before it will activate and start counting down.
rscadd: The presence of the Ark will be immediately announced, though the location will still only be announced after it has been active and counting down for 2 minutes.
tweak: The Ark also requires an additional invoker to invoke.
/:cl:

Summoning the Ark shouldn't be the difficult part, protecting it should.

### CODE REVIEW

**Comment by coiax** [comment]
Six invokers is a lot... It's damn hard enough to get 5 as it is.

**Comment by Kromgar** [comment]
... CUlt needs 9 invokers i think cucks can manage

**Comment by Thunder12345** [comment]
STOP USING THE COMPONENTS YOU FAGGOTS

**Comment by francinum** [comment]
@Kromgar Bloodcult needs 9 invokers after the rune goes down, this needs 6 to start the countdown.

**Comment by ChangelingRain** [comment]
I've only seen them fail due to not being able to group up *once*. Most of the time they even end up with 9 people, even though they don't even need that many.
Like, what the shit, how and why do clockcultists have an unnatural ability to group the fuck up?

**Pull request merged**
