### PR TITLE
[Icebox] Retvrn: Brings Bar Back to Base (level)

### PR DESCRIPTION
**Pull request by MrMelbert**
### Pictures below (You have to click them)

<Details>

<Summary> The prodigal bar returns to its home on the first floor, re-combining the kitchen and the bar's atrium into one room off of the main hallway. I didn't want to leave the Clown and Mime out, though, so I added a mini stage by the bar's entrance, for stand-up.</Summary>

image

</Details>

<Details>

<Summary> The lower bar area is not entirely dead, however, Where it once was now lies an expansion of Hydroponics, as well as a  gambling lounge and stage for the clown and mime. </Summary>

image

</Details>

<Details>

<Summary> The maintenance in and around the upper service area and dorms have also expanded, adding a connection between serv maint and sec maint. </Summary>

image

</Details>

Other notes:

- Standardizes some decal styles in the main hallway
- Adds a single air alarm to the brig (I noticed it was missing one while running mapping verbs)

## Why It's Good For The Game

I really, really like the design behind the Icebox bar, the "seedy gambling bar underneath the station" is supreme vibes, but unfortunately it really hampers visitation. Bars should really be front and center on the station to people walking by can see what shenanigans are going on, who is around, if the bartender is serving drinks, etc... which is difficult when it's hidden under the kitchen. 

This PR aims to bring it back to the front, and kinda bring back the kitchen-bar connection, while not entirely abandoning the vibes of the bar as-is. 

## Changelog

:cl: Melbert
add: Icebox: The bar returns to its home. 
add: Icebox: Standardizes some decal styles in the main hallway.  
fix: Icebox: The lower brig's missing air alarm has been found. 
/:cl:

### CODE REVIEW

**Comment by sylvia-from-fulp-station** [comment]
I really like this.
Do you have any thoughts about swapping the kitchen to the other side so it's adjacent to botany? the separation between botany and kitchen has always been frustrating on icebox; so much so that my first PR was adjusting it.

**Comment by MrMelbert** [comment]
> I really like this. Do you have any thoughts about swapping the kitchen to the other side so it's adjacent to botany? the separation between botany and kitchen has always been frustrating on icebox; so much so that my first PR was adjusting it.

Well it's a bit late for that, I already finished it 

I have been throwing around ideas for some way to connect them better, I joked about mine carts and someone else suggested transit tubes

**Comment by carlarctg** [comment]
While this is undoubtedly better, a large part of Boxstation's bar design success is that it was directly attached to not just one hallway, but two of them at a corner. This, alongside the seethrough windows, vastly increased visibility and meant that if you were just walking by the hallway you'd get a full view of the bar and whatever hijinks may be going on there. I am not saying this to demand a change, but rather to help understand exactly why people yearn for boxbar.

**Comment by sylvia-from-fulp-station** [comment]
> > I really like this. Do you have any thoughts about swapping the kitchen to the other side so it's adjacent to botany? the separation between botany and kitchen has always been frustrating on icebox; so much so that my first PR was adjusting it.
> 
> Well it's a bit late for that, I already finished it
> 
> I have been throwing around ideas for some way to connect them better, I joked about mine carts and someone else suggested transit tubes

Other multiz maps like tram i think, use a "dumbwaiter", a one tile elevator with a fridge.

**Comment by MrMelbert** [comment]
> Other multiz maps like tram i think, use a "dumbwaiter", a one tile elevator with a fridge.

Yeah I don't really wanna copy it tho. Unique things on certain maps should stay unique. That's why I'm on team minecart.

**Comment by tralezab** [comment]
Multi-z design is one of the most interesting design challenges mappers have, but one of the clearest outcomes of trying all sorts of stuff and seeing what sticks is that putting a service role in a lower zlevel is a terrible idea for getting people to be there

> Yeah I don't really wanna copy it tho. Unique things on certain maps should stay unique. That's why I'm on team minecart.

TRUE

**Comment by MMMiracles** [comment]
Another sad loss in the books for superior underground bars, truly all problems are due to players.

Really like the layout on first glances, both the bar and hydroponics extension making me want to do another service rework. The wood/stone tile combo goes harder than it has any right to.

I'll take a look in SDMM later but here's a freebee if you haven't caught it yet.
image

**Comment by MrMelbert** [comment]
> I'll take a look in SDMM later but here's a freebee if you haven't caught it yet

Have caught it, pictures are slightly out of date

**Comment by MrMelbert** [comment]
Okay I'm gonna add a minecart that connects botany to the kitchen but it will have to be in a second pr

https://github.com/tgstation/tgstation/assets/51863163/03c60026-a6b5-4b4e-93a1-1ce8cf2b6658

**Comment by GoldenAlpharex** [comment]
One thing I need to say, and that's mostly for hydroponics: The bell at the front desk likely will never get heard by the people downstairs, because I think it doesn't reach down, I recall trying that out yesterday on another downstream map with a similar layout for Hydroponics, and the botanist couldn't hear the desk bell's ring.

**Comment by Gaxeer** [comment]
image
What do you think about replacing those stools with sofas or pew?
I personally don't like how those stools look here.

**Comment by MrMelbert** [comment]
> What do you think about replacing those stools with sofas or pew? I personally don't like how they look here.

I'd rather not put sofas in the middle of the main hallway

**Comment by Zytolg** [comment]
God Tier work Melbert

**Comment by Ketrai** [comment]
Well I'll miss the old diner a little. It had a nice theme to it! But this bar is certainly a nice and very welcome replacement. Given I don't see botany to kitchen connection changing for the better in this one either, I'd like to at least see the smartfridge be moved to a spot that's less cumbersome to work with. Either the chef or the botanist will be ferrying ingredients between fridges (or ferrying entire fridges), would it be possible to slide it into the kitchen's counter instead? Especially given it's in a rather tricky spot for multiple people to access as well.

**Comment by Ketrai** [comment]
image
Also minor nitpick but what's up with the two slots machines where people have to hug to use them.

**Comment by MrMelbert** [comment]
> Also minor nitpick but what's up with the two slots machines where people have to hug to use them.

It's not for two people, it's for dual wielding

**Comment by hiss1000** [comment]
Would it be possible to get a little more counter space in the kitchen? Maybe moving the carts into the freezer or rearranging the tables into a kind of 3x4 'C' shape with the griddles making up the upper limb. I feel like with 2 chefs things are going to get congested pretty quickly with only 4 central tables, especially with 2 of them holding the grinder & food processor. Apart from that it looks really good! I dig the flagstone look.

**Comment by MrMelbert** [comment]
image

**Comment by hiss1000** [comment]
That looks a lot better, thank you very much!

**Comment by san7890** [comment]
looks nice. i'm happy with it because the "snowed in" and excavatable cold room is still there

**Comment by MrMelbert** [comment]
Botany now has a way to deliver directly to the Kitchen 

image

**Pull request merged**
