### PR TITLE
Replaces illegal sound with a legal sound.

### PR DESCRIPTION
**Pull request by Iamgoofball**
Prevents copyright issues.

### CODE REVIEW

**Comment by PKPenguin321** [comment]
trash

**Comment by optimumtact** [comment]
This sounds bad, please find something good.

**Comment by HankMoodyExperience** [comment]
vg has fucking david bowie stop being a cuck

**Comment by Robustitron** [comment]
you mean undocumented sounds

**Comment by Iamgoofball** [comment]
Sorry my bad

**Pull request closed without merging**
