### PR TITLE
Tram Mk. IV

### LINKED ISSUE #73125: Tram controls display wrong direction
## Round ID:
[199310](https://scrubby.melonmesa.com/round/199310)

## Reproduction:
Send the tram from Central or East to West. It incorrectly shows the East animation.

image

### PR DESCRIPTION
**Pull request by lessthnthree**
## About The Pull Request
- After one too many tram malfunctions, Nanotrasen's insurance provider finally sprung the cash for a new tram. Made with the latest in lightweight materials, there's more capacity than ever before to shuttle your crew around the station.

https://user-images.githubusercontent.com/83487515/215639768-3f7fcb84-cfd2-4efe-b578-998197651f13.mp4

- Consolidates all the tram turfs, objs, and structures into respective .dm files because they were haphazardly spread everywhere.
- Fixes tram doors playing open/close animations when they're already in the correct state, corrects timing for when they change density.
- Tram now correctly has an operating status and will stop functioning when power is lost.
- Call buttons no longer dispatch a tram that doesn't have power.
- Fix for emergency exit when tram has no power.
- Running at closing tram doors is a gamble, you may be crushed
- Fixes https://github.com/tgstation/tgstation/issues/73125

## Why It's Good For The Game
Looks nice, more space, tram doors demand a pound of flesh.
## Changelog
:cl: LT3
imageadd: Nanotrasen's insurance provider finally sprung the cash for a new tram. Made with the latest in lightweight and mostly* non-flammable materials, travel in comfort and style!
code: All tram components are now organised based on type
code: Tram is now aware if it has power or not
del: Removed movement slowdown running on tram plates
fix: Tram call buttons will not work calling an unpowered tram
fix: Tram doors will no longer cycle open/closed when they're already in the correct position
fix: Fixed an edge case where running onto the tram you bounce off the open door as if it was closed
fix: Unpowered tram doors can only be forced into the open position
fix: Westbound travel shows the correct controls animation
add: Tram doors take a chunk of flesh if you run at them last minute
qol: Reduced duration of amber stage on tram crossing signals 
/:cl:

### CODE REVIEW

**Comment by Jackal-boop** [comment]
pictures...

**Comment by Time-Green** [comment]
I know the bot image is a thing, but an actual in-game image of the tram is really important for changes like this

**Comment by lessthnthree** [comment]
Yeah it was a draft while I do the last finishing touches, and add the content.

**Comment by Pumpkinoe** [comment]
love those new doors, sublime

**Comment by lessthnthree** [comment]
> love those new doors, sublime
> 
> say, how does this look when it blows up?



> love those new doors, sublime
> 
> say, how does this look when it blows up?

See: https://github.com/tgstation/tgstation/pull/72828

**Comment by Pumpkinoe** [comment]
neado

**Comment by MrDoomBringer** [comment]
WOAH thats sick good work on the doors

**Comment by wesoda25** [comment]
Looks fantastic but does this mean you can't fall/get pushed out anymore?

**Comment by AlamoTurtle** [comment]
I miss benches. Could slap some at the ends just for aesthetic.

**Comment by lessthnthree** [comment]
> Looks fantastic but does this mean you can't fall/get pushed out anymore?

Of course not! The doors operate the same as usual, you can bump/click to open them and jump/push out.

**Comment by Zytolg** [comment]
I think I'd prefer benches over shuttle-seats. It's public transportation after all.

**Comment by lessthnthree** [comment]
Here's 3 options, what looks best?

seats2
seats1
seats3

**Comment by lessthnthree** [comment]
Yeah it adds some colour too.

**Comment by lessthnthree** [comment]
> I think I'd prefer benches over shuttle-seats. It's public transportation after all.

Changed it.

**Comment by bruhlookatthisdood** [comment]
Why are the benches facing the wrong way?
image

**Comment by lessthnthree** [comment]
They're not?

**Review by tralezab — APPROVED** [review]

**Review by MMMiracles — APPROVED** [review]
i don't hate the layout

**Pull request merged**
