### PR TITLE
Planned Spaceparenthood would like to apologize for mislabeling their cloning pod ejection buttons.

### PR DESCRIPTION
**Pull request by Iamgoofball**
:cl: Planned Spaceparenthood
fix: We would like to apologize for mislabeled cloning pod buttons.
/:cl:

### CODE REVIEW

**Comment by Robustin** [comment]
A marginal improvement on a terrible system.

**Comment by Iamgoofball** [comment]
Making sure OOC gets the new name

**Comment by kevinz000** [comment]
Rename it aborted

**Comment by Bawhoppen** [comment]
why

**Review by Cyberboss — APPROVED** [review]

**Comment by kevinz000** [comment]
robustin is mad he got aborted guys

**Pull request merged**
