### PR TITLE
Adds some clarity to a defib message when confronted with extreme tissue damage

### PR DESCRIPTION
**Pull request by SconesC**
Just for clarity's sake, so people don't keep screaming WHY HE NOT DEFIB

### CODE REVIEW

**Comment by KorPhaeron** [comment]
Why is patient capitalized?

**Comment by Shapsy** [comment]
Thank youuuu, this'll make the transition much less painful now

**Comment by phil235** [comment]
Remove the capital P in patient. :+1: otherwise.

**Comment by SconesC** [comment]
@phil235 I fixed it

**Pull request merged**
