### PR TITLE
Small tweaks to captains starting equipment

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
Starts with a bowman headset. He has one in his locker anyway.

Starts with sunglasses. He has the ridiculous gar ones in his locker anyway.

Starts with his gloves on. Again, in the locker already.

Moves the box of silver IDs from his bag to start in his locker instead. On the off chance anyone ever uses them, they're now actually on the map vs tied to the captain spawning. As it was, just another item to drop from your bag at round start.

Should hopefully save on some round start shuffling of items/locker digging. Not intended to be a balance thing, just a small quality of life update.

### CODE REVIEW

**Comment by PKPenguin321** [comment]
:+1:

**Comment by tuypo1** [comment]
No on the bowman I'm a supporter of grabbing the best equipment you have access to normally but the caps an exception he has to be accessible it's why i use an internals mask rather then a gas mask as cap

And doesn't a box of silver ids start in the bridge anyway all no cap needs are covered by the spare anyway

Gloves should start in your backpack but I'm mostly neutral on that one.

In the end though captain should have to get to his locker to get the good stuff and if the cap starts with his bowman the only way to steal one is to attack sec

**Comment by Cheridan** [comment]
muh gloves

**Comment by KorPhaeron** [comment]
I really don't think the captain retrieving his stuff from a locker 5 tiles away from his spawn is a balance issue.

I don't think fringe scenarios where the captain late joins and is so fucked that he can't reach the locker but is somehow miraculously saved by his bowman are worth balancing around to the point that the other 99 rounds there is pointless tedium.

**Comment by SconesC** [comment]
@tuypo1 Why the fuck do you think think his gloves should start in his backpack?

This is a convenience change. It is good.

**Comment by Dorsisdwarf** [comment]
:-1: to bowman headset, captains not preparing and flashbanging themselves is top cakes

**Comment by Firecage** [comment]
....I like the standard headsets sprite better than the ugly bowman sprite :(

**Comment by GunHog** [comment]
I do not play Captain, but this seems good to me! :+1:

**Comment by pudl** [comment]
Just include a normal headset in the captain's locker and have him spawn with a bowman, similarly to how security is right now, please?

**Comment by KorPhaeron** [comment]
@pudl 

But then latejoin captains can't get the bowman.

**Comment by pudl** [comment]
What? Latejoin captains will spawn with a bowman on, and get a normal one from the locker if they want it.

**Comment by KorPhaeron** [comment]
@purl

Sorry, meant people who get promoted to captain/swap into the job

**Comment by pudl** [comment]
Then include both normal and bowman in the locker.

**Comment by SconesC** [comment]
Thee captain's headsets on the map? Thanks but no thanks

It's such a minor cosmetic "loss" for a reasonable balance concern

People swapping into the job can take the key, remember?

**Comment by Jalleo** [comment]
Just remove bowmans and give a accessory earplug to standard headsets that need it.

**Comment by SconesC** [comment]
Stealth protections are bad and that's why dermal was removed

**Comment by pudl** [comment]
Since when did the captain need absolutely every tool that security has access to, anyway? If someone wants a job where they're decked out with gear made for protecting themselves and others, they can play HoS. The captain shouldn't be an extension of secutiy with access to their equipment.

**Comment by pudl** [comment]
Security

**Comment by KorPhaeron** [comment]
@pudl 

He already has access to it. In his locker. 5 steps from his spawn point.

**Comment by pudl** [comment]
That doesn't mean he should have ever recieved it in the first place.

**Comment by SconesC** [comment]
He's the only implanted non-sec person and having him jacking a bowman+transferring the key every round just to avoid friendly fire is dumb

**Comment by bustygoku** [comment]
Off topic comments again?

**Comment by GunHog** [comment]
The Captain is <b>The Boss.</b> He has valid reason for having the best stuff, because he is the *Captain*, and is the single biggest target on the station.

**Comment by PKPenguin321** [comment]
you guys are fucking lunatics literally all this does is equips the captain with different stuff at roundstart
if you dont want the bowman then go get the standard headset, it's not like this PR removes it

as a captain player, :+1:

**Comment by pudl** [comment]
It does remove the normal headset.

**Comment by kevinz000** [comment]
:-1: on the bowmans
I mean come on it's well worth the hilarity of condoms getting flashbanged into the stone age.

**Comment by bustygoku** [comment]
I'm almost inclined to agree.

**Comment by OhEmGee** [comment]
I suggest removing the egun from the captain's locker, and making them spawn with it. Why does the HOS spawn with one in suit storage, but the most important person on station doesn't? I've more than once gotten mobbeed and killed when I'm fresh off the shuttle for dat all access. The big-ass announcement doesn't help either.

**Comment by KorPhaeron** [comment]
@OhEmGee

I agree but I was trying to avoid the exact balance arguments I got into anyway

**Comment by Bawhoppen** [comment]
Yea bowman should be a powergame choice as opposed to default, in the ideal RP world he wouldn't need to personally fight, and thats why bowman should be optional. Like how the HOP spawns with normal sunglasses as opposed to HUDglasses.

**Comment by KorPhaeron** [comment]
We literally have a game mode about him keeping the nuclear launch codes safe from a corporate death squad armed with assault rifles and mech how in the hell do you figure he should be "roleplaying" during that

**Comment by SconesC** [comment]
"guys dont shoot"

**Comment by bustygoku** [comment]
Works for me. ^

**Comment by KorPhaeron** [comment]
@Razharas @Jordie0608 @Miauw62 @Cheridan @RemieRichards

**Comment by Bawhoppen** [comment]
This is a bad change for reasons explained above. Don't merge it.

**Comment by freerealestate** [comment]
please merge this while ignoring 90% of the comments
for a change in pace i actually mean what i've said there

but maybe the regular headset should be added to the captain's locker as well so people who like it can have it? maybe it could have no encryption keys by default so if people are that concerned about having two spawn on the map the captain would have to switch them over to use it?

**Comment by Bawhoppen** [comment]
Don't do it, would be bad

cept the sunglasses thing, thats fine

**Comment by OhEmGee** [comment]
I can't see why captain spawning with a energy gun, bowman and sunglasses
would be such a big deal. A latejoin captain is easy prey for the
rev/loitering antag, etc. All access shouldn't be easy to get.

**Comment by Bawhoppen** [comment]
It dumb because the captain shouldn't necessarily be needing to use the best equipment, in an ideal world he wouldn't need to personally march into battle, as that's supposed to be security's job.
Plus its better if these things start in the locker where they can be taken even if there is no captain.

**Comment by OhEmGee** [comment]
We don't live in a ideal world. A lucky antag can easily score free
all-access by dunking a latejoin captain before they can gear up. All
access should be hard to get.

**Comment by Bawhoppen** [comment]
Its an RP thing, not a fucking tryhard only ever try win thing

**Comment by OhEmGee** [comment]
I don't know about you, but I don't think getting wordlessly mowed down by
antags 15 seconds after you exit the arrivals shuttle doesn't really count
as RP.

**Comment by KorPhaeron** [comment]
See my above comment about the game mode Nuclear Emergency.

Pretending the game doesn't exist doesn't make you a good roleplayer.

**Comment by Bawhoppen** [comment]
The problem isn't the captain's starting equipment if thats the case, and don't act like you're not exaggerating.
Pretty sure you're not allowed to camp the arrivals shuttle anyways.

**Comment by Bawhoppen** [comment]
Also Kor, bay does it. You can easily do a far toned down version of the way they do it to accomodate us.
But no, TG is about the valids, winning, memes, and doing things the most efficiently now.

**Comment by OhEmGee** [comment]
The truth is, that /tg/ never was a RP-heavy server, and never will be. A
bay-like solution would sadly never work on /tg/.

**Comment by KorPhaeron** [comment]
I don't see how having to put on your gloves roundstart is a balance or roleplay issue anyway. It's literally just busywork.

**Comment by Bawhoppen** [comment]
The captain shouldn't NEED the gloves, or the bowman, or the sunglasses. They should be optional, and not the obligation.

And I'm not saying TG is heavy RP oriented, I'm saying we should have SOME RP

**Comment by OhEmGee** [comment]
You can't force people to RP. Also, this change doesn't have anything to do
with RP WHATSOEVER.

**Comment by Bawhoppen** [comment]
It definitely does, and I already explained why.

**Comment by freerealestate** [comment]
Can the regular headset go in the locker with the bowman one so it's not completely removed from the game? Apparently some people like it.

**Comment by tuypo1** [comment]
as bawhoppen has said the captain has no need for a bowman until shit hits the fan

**Comment by bustygoku** [comment]
He probably shouldn't have one anyway, the only thing it facilitates is flashbang usage if he's going out of his way to throw flashbangs he'll probably loot a bowman

**Comment by Dorsisdwarf** [comment]
If this gets merged, I'm totally gonna nerf the siemens coeff on the captain's gloves from 1 to 0.75, so you take less damage from shocks but not total immunity.

**Comment by KorPhaeron** [comment]
But why

**Comment by freerealestate** [comment]
plain captain's headset
in locker

**Comment by bustygoku** [comment]
You still get stunned dorsisdwarf, that's ultimately the reason he has yellows anyway.

**Comment by Dorsisdwarf** [comment]
@bustygoku You don't get stunned from doors with the current captaingluvs or take any damage at all because they were changed from being "Look how boss I am I don't even need yellows" to "I start with yellows but they're a different color so I don't have to show off the fact", and now to "I will always be wearing yellows no matter what"

**Comment by bustygoku** [comment]
I guess the captain has a hand tele if he gets shockbolted into a room, so him having hacking tools all the time lest he be fucked by the AI isn't really that necessary.

Still, I think we either have to settle for the cap jacking yellows at roundstart or giving him yellows by default. Powergamers will always powergame, and removing the shock proofing only effects non-powergaming captains since powergaming comdoms will ALWAYS have some form of hack protection on them I think, won't they?

**Comment by Razharas** [comment]
Not really a balance change so i dont see why not

**Comment by Bawhoppen** [comment]
goddamnit razharas

**Comment by freerealestate** [comment]
i will put
a plain headset
in the captain's locker
if it's the last
thing i

**Pull request merged**
