### PR TITLE
Improvised shotgun shell recipe simplification

### PR DESCRIPTION
**Pull request by ghost**
Replaces the chem grenade casing with 1 more metal sheet, since grenade casing are just made with 1 metal sheet inhand. Recipes should avoid being half handcrafting I think.

### CODE REVIEW

**Comment by optimumtact** [comment]
power creep

**Comment by py01** [comment]
i can increase the time to craft so it ends up the same if you want

**Comment by py01** [comment]
added +2s to the crafting time, so its basically the same time to make but less clicks for the player

**Comment by Angustmeta** [comment]
With 2.5 second craft time this PR will just make it take much longer than before. Crafting grenade casings are instant.

**Pull request merged**
