### PR TITLE
Nullrods now use a radial menu to choose their skins

### PR DESCRIPTION
**Pull request by Arkatos1**
## About The Pull Request

This PR replaces a method via which nullrod variants are chosen - instead of an ugly input menu, we now use a radial menu. Also cleans up and autodocs relevant reskin proc.

Example image:

NullrodRadials

## Why It's Good For The Game

Better nullrod variant choosing method.

## Changelog
:cl: Arkatos
add: Nullrod variants are now chosen via a radial menu. Fancy!
/:cl:

### CODE REVIEW

**Comment by LordSaladin** [comment]
more radials than c&c RA3 on consoles.

**Comment by mrhugo13** [comment]
A pain in the ass to cross-reference the wiki and in-game for the null-rod i want, thanks for trying to fix this relatively annoying inconvenience.

**Comment by cacogen** [comment]
hated that menu and not knowing what any of these things were or looked like

**Comment by Fikou** [comment]
can you do the same to the bible

**Comment by ATH1909** [comment]
Mm, I feel like there are too many null rod forms in the game for this to really work. Maybe add an option in the first radial menu to just pull up the list of null rod forms instead (in case the null rod form you want is buried behind, like, 10 pages of radials, or if someone recommended a null rod form to you by name and you don't know what it looks like yet)?

**Comment by NoxVS** [comment]
Yeah, WAY too many null rods to have a radial menu. People still need to check the wiki anyways to see some of the mechanics of the null rod (Different equip spots, special abilities, different stats, and so forth). Is it possible to just give the chaplain a book that links to the wiki page like the space law, robotics, engineering, etc books?

**Comment by MrPerson** [comment]
Sounds like the problem is option overload then.

**Comment by cacogen** [comment]
it really is

**Comment by minichibis** [comment]
does the menu also show the name of the null rod skin?

**Comment by Arkatos1** [comment]
Yes, it does show a name of the nullrod upon mouse hover.

**Comment by spookydonut** [comment]
dear tg,
today there are too many nullrods
please eliminate 3
ps: i am not a crackpot

**Comment by ThePainkiller** [comment]
Any hud changes make me hard, this is a great improvement

**Pull request merged**
