### PR TITLE
Cranks down the flashiness on ghost HUD icons to manageable levels.

### LINKED ISSUE #12707: Ghost hud icons are animated
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa

### PR DESCRIPTION
**Pull request by Incoming5643**
tex1_256x256_m_c71c938a4fb4bd71_14

It's a general rule of HUDs that how annoying and standoutish an element is should usually be roughly correlated to how urgently it need to be taken care of.

Ghost HUDs are, by definition, not urgent in the slightest, so they REALLY should be understated.

Fixes #12707

### CODE REVIEW

**Comment by WJohn** [comment]
:+1:

**Comment by AnturK** [comment]
While you're at it, could you add the F12 functionality to it ? So you can hide it completely.

**Comment by Jordie0608** [comment]
The colors weren't bad, looks a bit drab in all grey.

**Comment by tkdrg** [comment]
@AnturK You can do that already, with a verb.

**Comment by Razharas** [comment]
1 - colours were ok
2 - we need a system of icon animation on mouseover of huds, thats add to visual appeal without always being a flickering shit in the eye

**Comment by Nitrousoxide** [comment]
some of these aren't clear what they're for when they're not animated, like teleport and orbit.  Would need to redo them probably.

**Pull request closed without merging**
