### PR TITLE
Resprites civilian MODsuit

### PR DESCRIPTION
**Pull request by SmArtKar**
## About The Pull Request
изображение
изображение

Civilian MODsuit got its visor back but lost its lower helmet piece, exposing the mouth and chin. It also decided to hit up the gym and lost weight, as after it became a separate theme it no longer has a slowdown.

Additionally, made sure that mouthhole module cannot be installed on MODsuits that don't have a helmet or a mask that cover the face.

## Why It's Good For The Game

It looks extremely odd and bulky despite not providing a slowdown. Also the visor was cool.

## Changelog
:cl:
fix: Mouthhole module can no longer be installed on MODsuits that don't cover the mouth
image: Civilian MODsuit got a resprite
/:cl:

### CODE REVIEW

**Comment by GPeckman** [comment]
This is definitely better than my old sprite

**Comment by Exester509** [comment]
Excellent. Now welding protection and HUD modules make sense.

**Comment by norsvenska** [comment]
should probably also change the item sprites to match

**Comment by sylvia-from-fulp-station** [comment]
Very cool, looks like a crew version of the new infil mod which i adore.

**Comment by Wallemations** [comment]
So wait does this not protect against space then?

**Comment by sylvia-from-fulp-station** [comment]
> So wait does this not protect against space then?

iirc the civilian plating never did

**Comment by SmArtKar** [comment]
> So wait does this not protect against space then?

civilian MODs exchange space protection for no slowdown

**Comment by Dawnseer** [comment]
I was just getting excited, thinking that then the regular modsuit could get it's alternate skin back, but then I actually saw the pr. But yeah I agree the visor is definitely much better

**Review by Wallemations — APPROVED** [review]

**Comment by Wallemations** [comment]
Idk if I'm allowed to merge stuff
Iirc there's a revert happening but idk if that means sprite freeze

**Comment by Ghommie** [comment]
FAILURE # 1: Assertion failed: /obj/item/mod/control/pre_equipped/mining initial module /obj/item/mod/module/mouthhole is not supported by its parts. at code/modules/unit_tests/modsuit.dm:17

**Pull request merged**
