### PR TITLE
New spaceheater sprites

### PR DESCRIPTION
**Pull request by praisenarsie**
Ported from CEV-Eris.
I had to make the standby and cool sprite.

@WJohn 

:cl: Frozenguy5
imageadd: Spaceheaters are in the 3/4 perspective now.
/:cl:

### CODE REVIEW

**Comment by WJohn** [comment]
These really aren't a huge improvement. As people have complained about not arbitrarily changing oblique sprites to 3/4th without at least making some significant improvement, this PR currently has a 👎 from me. While I DO want the game to move towards that particular perspective, I think now is a perfectly good time to redo and upgrade these old sprites.

**Comment by praisenarsie** [comment]
Alright but how would I go about changing the sprites because it literally looks like a heater, it just doesn't look that modern, that's all.

**Comment by nicbn** [comment]
I will try to resprite these

**Comment by nicbn** [comment]
@WJohn thoughts on this heater?

**Comment by WJohn** [comment]
Still not superb. I can't quite tell what's going on with the front.

Maybe try something like visible heating coils? Having those turn orange when heating would be really pretty.

**Comment by nicbn** [comment]
The things in the front are supposed to be radiator tubes. The heating coils sounds like a better idea anyway.

**Comment by duncathan** [comment]
Space heaters function as both heaters and coolers so be sure not to focus solely on the heater aspect please

**Comment by nicbn** [comment]
What happened to this PR

**Comment by ninjanomnom** [comment]
No progress has been made to improving the sprite and wjohn has expressed disinterest in a purely perspective change. Ping me for re-open if better sprites are made/found

**Pull request closed without merging**
