### PR TITLE
Adds atmos link override variables to hand teleporters and portal guns

### PR DESCRIPTION
**Pull request by silicons**
Why: Portals have supported atmospherics linking for a long time, just that it defaults to off. This would allow admins to let the two things that uses basic portals (not wormholes) enable it for portals they create.

### CODE REVIEW

**Comment by davethwave** [comment]
Oh no...

**Comment by davethwave** [comment]
I have images of someone linking the atmos plasma tank to the halls...

**Comment by BlueNothing** [comment]
This sounds like it could be cool.

**Review by SpaceManiac — APPROVED** [review]

**Comment by davethwave** [comment]
welp, opening portals in space is now much more dangorous...

**Comment by SpaceManiac** [comment]
@davethwave The atmos link remains off by default, but it's possible for admins to enable.

**Pull request merged**
