### PR TITLE
Shuttle Engine Sprites Again

### PR DESCRIPTION
**Pull request by ghost**
Forgot to include these, sprites for the heater and router parts. No CL because they're part of the engines and should have been included before.

tgshuttleengines

### CODE REVIEW

**Comment by WJohn** [comment]
Neat. Those looks really good.

**Comment by xxalpha** [comment]
Isn't he just changing the sprite? Why does he need to edit the maps?

**Comment by uraniummeltdown** [comment]
@WJohn I'll do the map edits in another PR when the mapmerger fix gets merged
@xxalpha the old shuttle propulsion and burst sprites had east and west the wrong way around, so on most maps they had the wrong dir. These new ones face the correct way but the dirs on maps are still incorrect.

**Comment by Jordie0608** [comment]
You could do that with a text editor, just find/replace to swap dirs 4 and 8 (i think) on the typepath.

**Comment by Militaires** [comment]
while you're at it can you delete the toolboxes with latches on them (excluding green_awakening) from storage.dm they were reversed by another pr and are not supposed to be there

handled by overlay now

**Comment by uraniummeltdown** [comment]
I'll try and fix the dirs via n++ when I have time, I'll delete the latched toolboxes except green_awakenining

**Comment by Militaires** [comment]
thank you friend

**Comment by anconfuzedrock** [comment]
I hated them before because they looked like fucking ass but now that they have the other part of the engine i hate them like a third as much

**Pull request merged**
