### PR TITLE
Ports the Head of Personnel's Parade Jacket

### PR DESCRIPTION
**Pull request by axietheaxolotl**
## About The Pull Request

Read on the tin. I originally made this for Skyrat, but I thought you guys might want it too.

Male:
image

Female:
image

## Why It's Good For The Game

HoP has a severe lack of drip, this supplements it.

## Changelog

:cl: axietheaxolotl
add: Head of Personnel's Parade Jacket, ported over by Skyrat, and originally made by: ME.
/:cl:

### CODE REVIEW

**Comment by optimumtact** [comment]
/me blocks your path

sorry kid, nothing personnel, but there's too much formal clothing choking up people's roundstart lockers.

I'm mandating that you move formal outfits into a clothing cupboard that is put in the command meeting/break room in the bridge before we add any more formal uniforms for heads.

*teleports away*

**Comment by Donpedrito** [comment]
Weren’t garment bags added to lockers so that the alternate outfits weren’t clogging them?

**Comment by optimumtact** [comment]
Yes but I decided I like this solution more

https://hackmd.io/SGPt7aJtRDyC0FLJQPew_A?view

**Comment by CRITAWAKETS** [comment]
looks way too ostentacious for the head of personnel

**Comment by EricZilla** [comment]
Head of personnel doesnt have any formal gear at all, how is this bloat

**Comment by optimumtact** [comment]
cope, seethe, mald

**Comment by EricZilla** [comment]
> cope, seethe, mald

Mods can we remove the smap

**Comment by optimumtact** [comment]
lets keep this thread on topic please. Thanks

**Comment by EricZilla** [comment]
> lets keep this thread on topic please. Thanks

You missed one

**Comment by ATH1909** [comment]
> /me blocks your path
> 
> sorry kid, nothing personnel, but there's too much formal clothing choking up people's roundstart lockers.
> 
> I'm mandating that you move formal outfits into a clothing cupboard that is put in the command meeting/break room in the bridge before we add any more formal uniforms for heads.
> 
> _teleports away_

wtf oranges would never bikeshed im literally shaking and crying rn

**Comment by ATH1909** [comment]
> looks way too ostentacious for the head of personnel

eh, I like the over the top anime-ness of the female version

**Comment by optimumtact** [comment]
closing since youve made no attempt to do the requested changes.

**Pull request closed without merging**
