### PR TITLE
Only include the map if tgstation.dme is the main project

### PR DESCRIPTION
**Pull request by nullquery**
This is a minor change that will allow me and others who inherit from tgstation.dme rather than making direct changes and getting merge conflicts to add our own maps without having to override /tg/station code.

It's an addition I'd very much like to see, but I'm fearing it won't get pushed because of concerns that people won't know how to change maps etc.

I've modified the README.md to document this behavior, but if there's any other place that needs documentation please point this out to me - I really want to get this pushed through because I _DON'T_ want to make changes to the /tg/station codebase (see also: https://tgstation13.org/phpBB/viewtopic.php?f=5&t=3967).

**This PR can be merged.**

### CODE REVIEW

**Comment by optimumtact** [comment]
Yeah why not :+1:

**Comment by nullquery** [comment]
**Disclaimer:** Personally I'd prefer if everyone used the submodule approach.

Reasoning for this:
* Working with the /tg/station code directly leads to a merge hell where you have to compare your changes vs. /tg/station changes. For most forks /tg/station works at a much faster pace, so it's difficult to keep up especially if you have real life kicking you around all the time.
* The approach encourages sharing. A clear example: hypothetically if I implemented the adminbus from /vg/ (a feature /tg/ probably does not want) then I have two options:
  * If I fork directly I practically have to make a pull request to avoid merge conflicts, but if the PR is rejected then I'll have to split off from /tg/ as any future merges will slowly become impossible as I add more features/changes that /tg/ doesn't want to merge.
  * By using the submodule approach (i.e., a separate .dme) I can include any changes I want and not have to push them to /tg/ to remain up-to-date. There may still be merge conflicts, but any conflicts occur in my own code. Since I know what my code is supposed to do, I can resolve these conflicts much more quickly than having to resolve conflicts in the existing .dm files.

**I'm only ever going to push things that are either beneficial to /tg/station itself or are beneficial to the submodule method of working.**

Pushing an overhaul of the crew monitoring computer through benefits both myself (it becomes part of the /tg/ source so the responsibility for maintenance is shared, I can ask for help with this) and it benefits /tg/ (looks much better IMO).

Pushing map changes that only apply to our server through is NOT beneficial to /tg/, but pushing a change that allows us to make our own map changes WITHOUT touching the "tgstation" folder is a must IMO before we can proceed to make changes. If there's going to be any code conflicts, it ought to be in my own code and not between someone else's.

**Comment by CorruptComputer** [comment]
Can we still just unchecked and check the boxes to play other maps? Because if we have to manually edit the file every time :-1:

**Comment by nullquery** [comment]
You already have to manually edit the file every time by unchecking and checking the map you want whenever the DME file changes. You shouldn't have to.

This change means that you can create your own .dme file alongside the tgstation.dme file and include any custom content/maps yourself. And if the tgstation.dme is updated you won't have to re-include your files.

If you compile tgstation.dme directly it'll use the tgstation map. If you create your own .dme you'll be able to include the tgstation.dme file without it including its own map files.

For an older example on how this works, check the following links:

https://github.com/HeavensGate/heavensgate-old
https://github.com/HeavensGate/heavensgate-old/blob/master/heavensgate.dme

There are 2 dme files: "nullstation.dme" and "heavensgate.dme". "nullstation.dme" represents the "tgstation.dme" in this example. It includes the full source-code. "heavensgate.dme" includes some custom content and its own maps. It **extends** the source-code rather than modifying it, which makes it more resilient against merge conflicts (i.e., no need to reapply your own changes after a merge, you'd only ever need to fix what was changed in /tg/).

**Comment by CorruptComputer** [comment]
Yes, but if we don't want to make another dme for every map, can we still check and uncheck the dm for maps. Or do we have to do it manually with Notepad? And honestly, I don't see any benefit from this, why should we tip toe around our files to that downstreams don't have conflicts?

**Comment by nullquery** [comment]
You don't have to manually change anything with Notepad. You can modify .dme files through Dream Maker.

If you want to see the map being checked in the file tree just comment out the code in the .dme and check the map.

> why should we tip toe around our files to that downstreams don't have conflicts?

Because this is one of the major codebases, and if you don't cater to those downstream projects they will split off from you and you'll lose their content.

This open-source business is a symbiotic relationship. Downstream merges from upstream and ensures any code they submit adhere to a set of code standards; upstream ensures that downstream has hooks so they can compile their own code/maps/resources without having to interfere with the main codebase.

**Comment by JJRcop** [comment]
@CorruptComputer I don't get how you are against this.

**Comment by nullquery** [comment]
@JJRcop Thank you for your comment, that makes me feel a whole lot better.

**Comment by CorruptComputer** [comment]
I'm not against it, I'm just not sure if it's worth it. Also you haven't answered my question, I don't want to have to type in the dm file path, does ticking and unticking dm files for the map still work. Or does it break this?

**Comment by palpatine213** [comment]
> Tgstation doesn't want the adminbus

If the code is good and some of the incompatible features like the jukebox and stuff was stripped, I'd love to see that added.

**Comment by RemieRichards** [comment]
it isn't getting added.

**Comment by palpatine213** [comment]
Rip.

**Comment by nullquery** [comment]
@CorruptComputer It's worth it because it will encourage other developers (like myself) to contribute back to /tg/station and not to split off altogether. What good is contributing to /tg/station for me if I have to jump through hoops to make my own changes or to have my own map? I'd be better off taking the current /tg/ source-code and using it as a base to develop my own server in, which many are doing.

@palpatine213 The adminbus is a perfect example of something that will never get added to /tg/, but IMO if you want to have it you should be encouraged to do so as part of custom content on your server. But you should still be able to merge from upstream without having to compare dozens of code files even though you had to override plenty of content to make the adminbus possible.

@RemieRichards I hope you're referring to the adminbus and not this PR... though I'm expecting if your comment was intended toward this PR it would be closed or a flag added by now.

**Comment by RemieRichards** [comment]
@nullquery yes, I was referring to the gimmickbus.

**Comment by nullquery** [comment]
Ok, thankful for that one. I'm on edge about getting this merged as it's the first indicator that /tg/ is Mr. Right in terms of codebases around here.

That said I'm open to discussion about how to make this change more transparent for others. There are several other options for this issue:

1. Request a new BYOND feature: to uninclude files that other .dme files have included. This would make this PR moot. But I doubt Lummox JR is going to be willing to implement this change.
2. We could use the \#define statement to enable a specific map. This means no more changes to the .dme would be needed, but nothing is checked/unchecked either. You'd basically have the same thing this PR introduces, except condensed into a single \#define specifically for the map.
3. Have /tg/ distribute separate .dme files for the core code and code + map. I don't think this is the right way to go and it should be up to the person using /tg/ to create and manage their own .dme file.

**Comment by optimumtact** [comment]
This is actually a better solution to handling multiple maps than the tick /untick one, since you just create a new dme for that map and include tgstations main one. It also makes it easier to include custom code for a map

**Comment by Cheridan** [comment]
@tgstation/commit-access What's the verdict on this?

**Comment by Jordie0608** [comment]
Tbh i skimmed most of the lengthy discussion but from what I gleamed this seems like a good idea.

**Comment by MrStonedOne** [comment]
Our system already does this.

If the map is included BEFORE the defined map in the dme, the defined map does not load.

This is how my updater is able to get basil to compile to metastation. 

This is also how travis compiles different maps.

**Comment by Razharas** [comment]
None relevant voted in favour of this
One semi-relevant vote against
Verdickt - denied

**Comment by optimumtact** [comment]
I disagree with your decision

this is a worthy change to make irregardless of the original contributor is gone.

I'm going to open a new PR with this

**Pull request closed without merging**
