### PR TITLE
Resprites The Detective's Wardrobe!

### PR DESCRIPTION
**Pull request by Imaginos16**
## About The Pull Request
Does exactly what it says on the tin, giving them a much needed redo when I was still mastering my spriting skills!

image

This PR also retouches the Disco Elysium outfits!
## Why It's Good For The Game
The older versions weren't as clean as I hoped they would've been. Now that a year and a half has passed, I've become wiser, and now these should be the true version of what I was intending detectives to look like!
## Changelog
:cl: PositiveEntropy
imageadd: Resprites the detective's wardrobe!
/:cl:

### CODE REVIEW

**Comment by Serxule** [comment]
the hat still looks ridiculous with how pointed it is, but thats a personal opinion and not an actual problem

**Comment by Wallemations** [comment]
Next on the block is the columbo fit

**Review by Twaticus — APPROVED** [review]

**Comment by calliophis-maculiceps** [comment]
the resprited disco gear is so good, why don't you also resprite his wardrobe though? (the piece of furniture)

**Comment by Wallemations** [comment]
> the resprited disco gear is so good, why don't you also resprite his wardrobe though? (the piece of furniture)

I think they're technically lockers so it's probably best to leave them for when lockers are redone for the wallening

**Comment by calliophis-maculiceps** [comment]
> > the resprited disco gear is so good, why don't you also resprite his wardrobe though? (the piece of furniture)
> 
> I think they're technically lockers so it's probably best to leave them for when lockers are redone for the wallening

oh is there somewhere where i could see those or are they not finished?

**Pull request merged**
