### PR TITLE
Stops people dragging CTF spawn traps

### PR DESCRIPTION
**Pull request by coiax**
:cl: coiax
fix: Fixed dragging the spawn protection traps on CTF.
/:cl:

### CODE REVIEW

**Comment by Arzion5** [comment]
oh no, how am I supposed to ruin the entire game now?

**Comment by kevinz000** [comment]
emergent gameplay

**Comment by coiax** [comment]
Yes, you can drag the goalposts in football as well, but that doesn't mean its sporting.

**Comment by XDTM** [comment]
Imagine football with that emergent gameplay

**Comment by coiax** [comment]
I have an idea, what if people tripped over the spawn traps and then did damage to anyone they tripped over

**Pull request merged**
