### PR TITLE
Space Dragon Now Has Event Weights Comparable to Slaughter Demon

### PR DESCRIPTION
**Pull request by ExcessiveUseOfCobblestone**
## About The Pull Request

See CL

## Why It's Good For The Game

I got a few complaints about this event being on par with slaughter demon so I've adjusted it to such. Needed to be lowered anyways since the novelty of a new baddie has worn off.

If you take issue with the baddie itself post here or on the forums. If there's nothing brought up within 24 hours i'm closing this.

@IndieanaJones 

## Changelog
:cl: Dragontalesby
balance: Space Dragon can now fire a hour in but has a greatly reduced firing chance (it's now equivalent to slaughter demon event)
/:cl:

### CODE REVIEW

**Comment by fluffe9911** [comment]
Shame

**Comment by HomocidlePancakes** [comment]
Why not 4?

**Comment by habader** [comment]
seems like a shame

**Comment by ExcessiveUseOfCobblestone** [comment]
> Why not 4?

Why would I set it to 4?

**Comment by imsxz** [comment]
i play this game every day for too many hours a day and ive only seen a slaughter demon random spawn once in my year of playing, maybe twice.

**Comment by Shadowflame909** [comment]
COBBY NOOO




I argued against its original spawn chance because slaughter demons have literally never spawned ever.


I've never seen them spawn in the 2 years I've been playing on this server. So if you do that, you're essentially just making the event never happen. Which to me, is pretty wasteful.



All in all. Slaughter demons are different from this event because they have an actual way to spawn outside of an event. This does not, so making it slaughter demon tier will just give us another never seen event.

**Comment by optimumtact** [comment]
Do not adjust the start time please, I have a hard time believing this has spawned that many times already that it needs changing the weight either.

**Comment by Shadowflame909** [comment]
A better nerf I feel, after having drafted the complaints of the players who've seen this event.


Is the ability for this huge boy to escape.

It's pretty weak once you corner it with your engineering hardsuit and gun/mining fireproof suit. But, it has carp speed so it has the ability to flee and eat and gib some unknowing nerd for health.


I'd just slightly nerf its speed. So you can chase after it, and it can't use it to cheese you.


This, or remove its 50% resistance to burn damage. Since it was based on regular ash-drakes.


This would allow the regular sec team to not need to order more ballistics, and instantly kill it with the lasers they have.

**Comment by ExcessiveUseOfCobblestone** [comment]
> Do not adjust the start time please, I have a hard time believing this has spawned that many times already that it needs changing the weight either.

Prob being adminspawned tbh

**Comment by IndieanaJones** [comment]
Alright, I'm down for nerfing it.  Which is better, no burn resist or slower speed?

**Comment by IndieanaJones** [comment]
Also, isn't nerfing it's spawn chance by even half at this point a little knee-jerky?  Maybe wait and see how often it pops up when admins aren't spawning it in?

**Comment by IndieanaJones** [comment]
Oh, and it would be nicer to have feedback on it first from more people, because as of now, I think only one person I've asked has actually seen the damn thing, but even they knew barely anything about it.

**Comment by Shadowflame909** [comment]
I'd go for the burn resistance


Sec can laser that sucker to death really fast, but it keeps its carp speed. So maybe it'll prey on more unsuspecting assistants..

Well, I just hope that it wouldn't kill the dragon too fast.

**Comment by ExcessiveUseOfCobblestone** [comment]
> Oh, and it would be nicer to have feedback on it first from more people, because as of now, I think only one person I've asked has actually seen the damn thing, but even they knew barely anything about it.

I figured as much, which is why I was hoping to get some feedback from the anons discussing with me their distaste for the event on a more public channel.

**Comment by ExcessiveUseOfCobblestone** [comment]
> Edit: I agree with you IndieanaJones. I think the shock of seeing megafauna is what's causing this. When people don't realize how easy it is to kill, and how many nerfs it already has.

It hasn't had any nerfs barring this one which is most likely going to get closed by myself no less and doesn't even touch it's actual power. We (I) would never even consider adding a fully decked PC drake/megafauna event so I don't know why you're insisting that it should be the base of the balance discussion.

**Comment by Shadowflame909** [comment]
That's my point though, it's super weak and easily killable. I think an Xeno Hunter could cause more damage than it, and they have 4 ways to spawn! While it can only spawn 1 hour and 10 minutes into the round.

**Comment by IndieanaJones** [comment]
I haven't seen a real write-up about anyone's experience so far.  I've heard some people complain about it, some people like it, but nothing concrete.  Is there anything on the forums?

**Comment by Timonkeyn** [comment]
There is a slaughter demon spawn event?

**Comment by Shadowflame909** [comment]
@IndieanaJones  The only complaint I've heard is that getting gibbed and being permadead makes people salty


also when the drake is cornered, thanks to their speed. they fly off into spess with the power of hit and run tactics.

**Comment by ExcessiveUseOfCobblestone** [comment]
> I haven't seen a real write-up about anyone's experience so far. I've heard some people complain about it, some people like it, but nothing concrete. Is there anything on the forums?

Only thing i've really heard is "it's pretty much a second form of slaughter demon event where it's just murderbone as a powerful simplemob".

**Comment by ExcessiveUseOfCobblestone** [comment]
chirp chirp

**Pull request closed without merging**
