### PR TITLE
Inhand Sprite: Lit Flamethrower Animation

### PR DESCRIPTION
**Pull request by gwhit94**
## About The Pull Request

+ Added slightly transparent smoke effect to lit flamethrowers.
+ Also decided to add ignite/extinguish sounds, same as those currently used by welding tool for now.
+ Welding tools emit some light when on, flamethrowers now do as well!

5ex3A1SBPn

## Why It's Good For The Game

Brings flamethrowers more to life, much like a lit welding tool! Also better indication that someone has a flamethrower ready to roast, especially in dark areas of maint.

## Changelog
:cl: smallveggiepaws
imageadd: Lit flamethrowers inhand sprite animated. Smokey.
tweak: Flamethrowers emit light when lit.
soundadd: Flamethrowers make a sound when you light/extinguish them.
/:cl:

### CODE REVIEW

**Comment by gwhit94** [comment]
I have had this idea for a while now, but this is my first time doing sprite animations, so any feedback is appreciated! Sorry that I'm not familiar with showing an example gif of this - @Twaticus how do?

**Comment by Twaticus** [comment]
@gwhit94 just drag and drop the images from your computer into the the textbox. i use shareX for screenshots and gifs its great. definitely recommend.

also it feels a _little_ harsh with the current amount of animations. i think adding a couple more with delays on them all would smooth it out a bit and look really nice

**Comment by gwhit94** [comment]
Alright! I'll keep working on it over the weekend and add pics to the PR when I have a better version

**Comment by gwhit94** [comment]
All set!

**Comment by gwhit94** [comment]
Hmmm, compiled fine for me I'll make a new PR

**Pull request closed without merging**
