### PR TITLE
Improvements to crew monitoring computer

### PR DESCRIPTION
**Pull request by nullquery**
This PR introduces the following changes:
- Bug fix: The table wasn't sorted according to department/rank, which is how the original monitor worked.
- Bug fix: sNPCs were given ID cards with null assignments.
- Tweak: Hovering over a dot on the minimap now scrolls to the appropriate entry in the table.

**This PR can be merged.**

### CODE REVIEW

**Comment by freerealestate** [comment]
It'd be better if the table was sorted based on damage, because after all it's what you look for when you're looking for who needs treatment.

**Comment by nullquery** [comment]
I'm not sure if this would make the game too OP. You don't want people constantly looking at the crew monitoring and IMMEDIATELY pointing out someone is hurt. It wouldn't allow antags to do their jobs.

**Comment by freerealestate** [comment]
Well you're also relying on people regularly checking crew monitoring, there being people available and willing to help the person, and that they have to access to that portion of the station and the capability of retrieving the body without getting critted or killed themselves. Currently, whenever I check crew monitoring I do an entire scroll anyway, so if they're there I'll see them. This just adds more busywork.

The other thing I wanted to suggest was making the dot colours more representative of the jobs of their owners. Currently you have brown chaplains and clowns for some reason, as an example. It'd be better if the dots either represented the department they were part of (in this case civilian, which is grey if I'm not mistaken) or better yet, the colour scheme of the specific job title (black for chaplain, pink for clown, etc.) I've noticed too that engineering seems to be brown rather than orange.

**Comment by nullquery** [comment]
Originally the color was white, but it was decided that the color wasn't visible enough on the minimap so it was changed.

If you have a specific color you'd like to try out you only need to modify the crew.js file and return a different color code in the getColor function. You can open a PR on my hi-extended-patch branch to make your changes appear in this PR.

**Pull request merged**
