### PR TITLE
Revert "Ports /vg/'s datum component system (#29178)"

### PR DESCRIPTION
**Pull request by Cyberboss**
Reverts #29178
Half-merged, half-finished, too much drama for me to bother anymore

### CODE REVIEW

**Comment by outbools** [comment]
>Still unable to describe PR in description like a sane person

**Comment by Qustinnus** [comment]
I think the drama was mainly just people not being sure about how it works and then reacting in their usual memey way. I think we could atleast try it out for a while. I think Ninja wanted to work on a system using these, and I did as well for traits.

**Comment by outbools** [comment]
Also i want to try it

**Comment by PJB3005** [comment]
And that's how a potential revolution in SS13's code went to shit because mso had a tantrum.

Mso's pretty good at being unrationally a PITA if you piss him off. Honestly best to just ignore him about this and keep on chugging.

**Comment by Cyberboss** [comment]
@PJB3005 convinced me

**Comment by ninjanomnom** [comment]
good because I want to use this for a project in the works

**Comment by Cyberboss** [comment]
#29324 for reference

**Pull request closed without merging**
