### PR TITLE
Prevents medbeams from crossing themselves

### LINKED ISSUE #30229: Medibeams can trigger microbombs and macrobombs
Round ID: 75282, Sibyl

Details: Nuke ops. Cayenne's macrobomb implant went off on the base, fucking people over. Then my microbomb implant also went off in the assault pod. Neither of us clicked the button. I wasn't even in crit.

Relevant factors?
- I was actively being medibeamed at the time for a long time. So was the other guy.
- The assault pod was depressurized at the time (due to aforementioned fucking over). I was floating in and out of crit hence the medibeam. But I was at red health when the microbomb went off.
- I had every cybernetic implant in. The reviver had fired at least once.

HREF logs do not appear to have anything useful.

***UPDATE***

I am able to consistently reproduce it. If you use a medibeam on someone with a microbomb/macrobomb and click their sprite too often (toggling beam on/off) you will "lose control of the beam" and they will go boom. I THINK what may be happening is that the old beam does not qdel fast enough and thus it thinks it's crossing streams

EDIT: Confirmed without implant this is 100% what is happening

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
Fixes https://github.com/tgstation/tgstation/issues/29827
Fixes #30229

### CODE REVIEW

**Comment by bgobandit** [comment]
probably also fixes https://github.com/tgstation/tgstation/issues/30229

**Comment by Ratvar** [comment]
Make crossed medbeams explode

**Comment by bgobandit** [comment]
also is there a way there can be a feedback message just in case it does happen again, would make tracking the bug easier (and honestly if something explodes there should be at least some message to the user)

**Comment by JJRcop** [comment]
@Ratvar [😄](https://github.com/tgstation/tgstation/blob/b8244823b7a9402874f54e74c5add7f5178dcbfc/code/modules/projectiles/guns/medbeam.dm#L105)

**Comment by DoctoreMad** [comment]
@Ratvar That's already what happens.

**Review by Cyberboss — APPROVED** [review]

**Comment by AnturK** [comment]
This allows you to have use two beams at once, maybe it should use some static id per gun to identify, or just pass the gun ref in.

**Comment by KorPhaeron** [comment]
@AnturK I considered that but I rationalized avoiding extra work by saying to myself "if they wanna spend 50tc and be defenseless more power to them"

**Pull request merged**
