### PR TITLE
You can now manufacture bone gel

### PR DESCRIPTION
**Pull request by Ryll-Ryll**
## About The Pull Request
I never got around to adding a way to get more bone gel on station other than buying medical crates from cargo, which is silly considering it's required to treat hairline and compound fractures, so this adds a way to do so. Simply get some bone dust from grinding up an organic bodypart (you still can't grind heads or chests), add some carbon, and throw it in a chem heater until it hits 630 Kelvin, and you'll get 1 bone gel as a result.

The actual recipe is: 10u bone dust + 10u carbon (@673K) -> 1 bone gel

## Why It's Good For The Game
On the off chance you use up all of medical's bone gel, you can actually make more. I doubt anyone knew you could buy more of it in medical crates, so this was long overdue

## Changelog
:cl: Ryll/Shaps
add: You can now manufacture bone gel by combining 10u of bone dust (obtainable by grinding any organic arm/leg [so no heads/chests]) and 10u of carbon, then heating to 673K.
/:cl:

### CODE REVIEW

**Comment by Timberpoes** [comment]
I'm considering this a continuation of implementing the extended wounds feature over time.

**Comment by Krysonism** [comment]
This is not a real cost, considering how easy limbs and carbon is to get. 

I also don't like adding reagent that is trivial to get and don't have any effect outside crafting.

If getting bone meal required actually grinding bone sheets, culinary bones or scooping remains decals i think it would be a lot more interesting reagent with several diverse strategies that could be used to obtain it.

**Comment by D4C-420** [comment]
dont we have bones from moisture traps? we can use those cause im not sure they really do anything

**Comment by Ryll-Ryll** [comment]
> This is not a real cost, considering how easy limbs and carbon is to get.
> 
> I also don't like adding reagent that is trivial to obtain and don't have any effect outside crafting.
> 
> If getting bone meal required actually grinding bone sheets, culinary bones or scooping remains decals i think it would be a lot more interesting reagent with several diverse strategies that could be used to obtain it.

The intention of this isn't to limit bone gel, it's to add a simple way to get more if you somehow exhaust medbay's supply.

**Comment by Krysonism** [comment]
> 
> 
> dont we have bones from moisture traps? we can use those cause im not sure they really do anything.

Yes we do. And pile of bones decals from mobs getting dusted by the supermatter.

**Comment by Serxule** [comment]
i feel like it should do a bone gel chem, not magically make a bottle of bone gel

**Comment by Fikou** [comment]
it should at least be obtainable from moisture trap/lavaland fauna bones in addition to bodyparts if its not the main method

**Comment by MrDoomBringer** [comment]
> simple way to get more

buy the cargo pack then reee

**Comment by Mothblocks** [comment]
just to be clear, we already have the ability to create surgical tape through way of making plastic from the dispensers and putting it into the lathe. surgical tape, if i remember right, is just as good as bone gel. this doesn't really make anything that wasn't possible *mechanically* possible, except I guess for really ghetto stuff. i am merging it simply because i like the prospect of creating items that you could not create before.

**Pull request merged**
