### PR TITLE
Dissection Now Provides XP Instead Of Research (+Balancing To Support Change)

### PR DESCRIPTION
**Pull request by ExcessiveUseOfCobblestone**
## About The Pull Request
Per RND design doc, removes the active gen of surgery and provides XP instead.

Numbers have been changed to be less giving than RND points, as XP can result in speed increases (atm at least hehe)

## Why It's Good For The Game

Ensures active generation of points do not negatively impact techweb balance.

## Changelog
:cl: Cobby
balance: Dissection will now give XP instead of research points.
/:cl:

### CODE REVIEW

**Comment by CPTANT** [comment]
I find it very hard to judge what the practical effect this will have without examples of the numbers involved. How much does dissecting corpses improve the skill and what effect does this have?

**Comment by optimumtact** [comment]
Approved

**Comment by ThePainkiller** [comment]
This is a bit unclear, does this actually make you gain experience faster even through other surgeries or is it just a huge XP ammount on successful surgery? Looking at code looks more like the latter...

**Comment by XDTM** [comment]
Perhaps we could keep a reserach interaction by making dissection grant biomedical research points instead of generic, and requiring those to unlock advanced surgeries and biotechs.

**Comment by Tlaltecuhtli** [comment]
> Perhaps we could keep a reserach interaction by making dissection grant biomedical research points instead of generic, and requiring those to unlock advanced surgeries and biotechs.

i think its better to put it  biotech generation on those advanced surgery buffs, like the first unlocking node  (no biotech cost) gives you basic buffs and more people you upgrade the more things you unlock: gives crew the benefit of interacting with medical for cool things and gives medbay things to do with actual humans instead of monkey dissection 24/7

**Comment by XDTM** [comment]
There can and should be more than one way of getting surgery points.

An idea to make dissection unique among those (since it's its specialty) would be to unlock unique techweb nodes when dissecting particular targets. Perhaps some stuff currently connected to Alien Technology could instead be unlocked by dissecting an abductor or xenomorph. Or dissecting people with particular brain traumas could unlock implants that mimic their functionality.

**Comment by ExcessiveUseOfCobblestone** [comment]
@XDTM that is not a possible solution given the RND design doc, as it creates a non-flat method of gaining points.

**Comment by ExcessiveUseOfCobblestone** [comment]
> I find it very hard to judge what the practical effect this will have without examples of the numbers involved. How much does dissecting corpses improve the skill and what effect does this have?

humans give about 30 xp total per out of the box dissection AKA these are between organ fixing and advanced surgeries in terms of XP. More is provided if you do it on wacky species as well as doing the upgraded surgeries.

This means dissecting the 2 bodies in morgue gives you a much easier time leveling up near roundstart, giving you the 5% speed bonus.

**Comment by XDTM** [comment]
> 
> 
> @XDTM that is not a possible solution given the RND design doc, as it creates a non-flat method of gaining points.
> 
> Not sure what oranges would like the process to be to propose changes to his design docs so should ask him about that.

My bad, i wasn't up to date with the new docs. Unlocking special unique nodes via dissection should still be doable within those parameters, though, right?

**Comment by TheVekter** [comment]
> 
> 
> > @XDTM that is not a possible solution given the RND design doc, as it creates a non-flat method of gaining points.
> > Not sure what oranges would like the process to be to propose changes to his design docs so should ask him about that.
> 
> My bad, i wasn't up to date with the new docs. Unlocking special unique nodes via dissection should still be doable within those parameters, though, right?

Theoretically, but we're still working on that code.

**Comment by ExcessiveUseOfCobblestone** [comment]
to my understanding activities that pre-req unlocking (not point-giving) are fair game.

**Comment by ExcessiveUseOfCobblestone** [comment]
> 
> 
> This is a bit unclear, does this actually make you gain experience faster even through other surgeries or is it just a huge XP ammount on successful surgery? Looking at code looks more like the latter...

It makes leveling easier by providing a sum of xp per dissection ;)

**Comment by jtroopa** [comment]
If it can still be done only once per cadaver, I can absolutely see MDs fighting over corpses.

**Comment by CPTANT** [comment]
Personally this change means to me that dissection goes from something very worthwhile to something I don't know why I would bother with it.

**Comment by CPTANT** [comment]
Also this is one of reasons why departmental research Points are so badly needed. Medbay should be rewarded for doing medical research.

**Comment by ExcessiveUseOfCobblestone** [comment]
Arguments about the design are useless comments for this PR, I do not own the design. I'm just having medical comply with said design.

**Comment by CPTANT** [comment]
> Sub chains of research should be gated by a scientific experiment, what that looks like for each part of the web is up to users implementation choice, it might be redeeming something like a slime, or building a specific nanite/virus, it should be related to the technologies in question

**Comment by ExcessiveUseOfCobblestone** [comment]
That is not points, but it is why dissection is not being removed (so dissection pre-reqs can be supported when the people working on experiments [not me] finish).

**Comment by Rohesie** [comment]
Is this ready?

**Comment by ExcessiveUseOfCobblestone** [comment]
yes

**Comment by kopoba** [comment]
Wew guys 500 research points per body is SO much impact of RND balance

**Comment by TomFulpWillard** [comment]
Now that medical XP has been removed, can we revert this PR so medical can have a way to help RnD in exchange for medical research done faster

**Comment by ExcessiveUseOfCobblestone** [comment]
no

**Pull request merged**
