### PR TITLE
Locks cloning behind a base node

### PR DESCRIPTION
**Pull request by tralezab**
## About The Pull Request

Moved the cloning node down to just base, removed the cloners from medical

finishing other maps in a second, the ones i have now have dirty vars so i need to grab those as well

## Why It's Good For The Game

kill and clone is cancer, techwebs has devolved to always getting the mining node or getting lynched, this should shake up both

## Changelog
:cl:
del: Cloning is now behind techwebs, cloning tech made much easier to get.
/:cl:

### CODE REVIEW

**Comment by wesoda25** [comment]
yes yes ye syes yes praise God thank you

**Comment by zxaber** [comment]
We're not really ready for cloning to be gone yet. Doing tend wounds on people with lots of damage takes ages and so you alt-tab for ten minutes while the surgery loops, waiting for the body to be defibbable.

**Comment by wesoda25** [comment]
> We're not really ready for cloning to be gone yet. Doing tend wounds on people with lots of damage takes ages and so you alt-tab for ten minutes while the surgery loops, waiting for the body to be defibbable.

Yes we are. The functionality is completely there. It doesn't take ages, not by a long shot. Not only that, the method of surgery/defibb for bringing people into the round is much more entertaining for a doctor as opposed to throwing someone into a cloning pod aka bad gameplay.

**Comment by shellspeed1** [comment]
You know what, fuck it, lets see what this does.

**Comment by Fikou** [comment]
techwebs buff

**Comment by msgerbs** [comment]
Would be interesting to see this testmerged for a while (after medchems are fixed).

While you're at it, fuck Cryo too.

**Comment by ExcessiveUseOfCobblestone** [comment]
trip notice

**Comment by Difrit** [comment]
We are nowhere near ready for this. Medbay is in a sorry state because of the current changes, removing cloning will just contribute to the mess rather than resolving some of it.

**Comment by kriskog** [comment]
This is overdue. But barriers are cancer, why are there barriers :eyes:

**Comment by tralezab** [comment]
@Difrit please don't repeat what other people 6 posts up have said. you should be responding to what wesoda said, not just saying the same thing. i want to keep an open mind about this kind of thing since i'm not even too much a fan of big balance stuff

@kriskog it's not much, but hopefully the inbetween between "i deleted the machines, making the room weird and "everything is abandoned and now the room is garbo". you can just smack the barriers down

**Comment by tralezab** [comment]
while i still think it's a good idea, i'm going to wait for the medbay craze to be over. it's just bad timing to do it between the new experimental chems

**Comment by wesoda25** [comment]
Oob

**Pull request closed without merging**
