### PR TITLE
Chem dispenser upgrade

### PR DESCRIPTION
**Pull request by vuonojenmustaturska**
It's been a long time coming, but this time let's do this:

:cl: Naksu
fix: Chem dispensers now show the correct amount of units they will vend (instead of 1/10)
balance: Chem dispensers can now be upgraded. Manipulators increase macro granularity, matter bins increase power efficiency, cells increase power capacity, capacitors increase recharge rate.
balance: Chem dispensers can now be constructed
del: mini-chemdispensers are removed.
/:cl:

At tier 1 manipulators, macros round to the nearest 5u, then 3u at tier 2, 2u at tier 3 and 1u at tier 4. 

Matter bins give you power efficiency and capacitors increase recharge rate.

### CODE REVIEW

**Comment by Armhulen** [comment]
AAAAATOMIZE

**Comment by Anonmare** [comment]
Power cells would make more sense instead of matter bins tbh

**Comment by vuonojenmustaturska** [comment]
matter bins increase efficiency, power cells increase capacity

**Comment by swagbringer** [comment]
how far down the techweb are chem dispensers? could be a serious balance issue

**Comment by CameronWoof** [comment]
Shouldn't matter bins increase capacity? Since they're... bins that contain matter?

**Comment by WJohn** [comment]
Does this mean the default dispensers on maps are going to be nerfed so they can't offer every chem? Or will they be special in that they have high tier parts from the get go?

**Comment by davethwave** [comment]
The way are produced is energy the gets turned into said chems

**Comment by YakumoChen** [comment]
Good PR :+1: 
Macros need a nerf so we don't have certain captains spamming meth every single shift at roundstart.
Will this enable the roundstart machines to be upgrades to have the chems the tier 3-4 upgrades give to the mini ones?

**Comment by Buggy123** [comment]
# A T O M I C

**Comment by yorii** [comment]
Upgrade? Sounds like a nerf to me but okay.

**Comment by arsserpentarium** [comment]
Chem macro either should be removed. Or shouldn't have lenght restrictions. Because chemnerds like long macros.

**Comment by arsserpentarium** [comment]
Also it means, that roundstart you gave only tier 1 reagents?
Why do you call nerfs upgrades?

**Comment by CPTANT** [comment]
I do not like where chemistry is going. Gating things behind nano manipulators is just a minor inconvenience when the reward is getting all available chemicals with the push of a button.

**Comment by Tlaltecuhtli** [comment]
is the roundstart power similar to the old chem dispensers?

**Comment by GunHog** [comment]
It appears that the reagents oil, ash, acetone, saltpeter, ammonia, and diethylamine are no longer available at tier 4 manipulators. Perhaps that, and only that portion of the reagent list could be preserved? Do not restrict the current chems, simply give access to the T4 list when the manipulator is upgraded to femto.

**Comment by Poojawa** [comment]
Why are macros a thing anyway.

especially when they just make death mix a literal button click with 0 effort?

**Comment by yorii** [comment]
Deathmix chems aren't even close to the most difficult chems that you can make, they were never a problem neither before or after macros.

I can however give this PR credit for at least making the power level more progressive and not just instant roundstart max level like it is today.

**Comment by vuonojenmustaturska** [comment]
Yes, the roundstart power is the same as old dispensers, except the UI now reads "1000 units" as 1000 units is the actual capacity of the machine. I'm gonna continue on this work today, I think making the granularity of macros improve with manipulator levels is a better direction to move towards, so that with tier 1 manipulators you get 5u increments, 3u with nanos, 2 with picos and 1 with femtos. 

For those chemists disappointed with all the nerfs, I will add plastic as a material to lathes later today and two new intermediate beaker types (one unlocked with tech) between larges and bluespace. There's also been talk about adding new mechanics, please look forward to it.

**Comment by davethwave** [comment]
Honestly the best death mix comes from death berries... Put a 13u currare/5 bicardine pill in the fridge and simply label it 5u bicardine. Once the person takes it he/she will die mysteriously a few minutes later from 200 or so tox damage

**Comment by yorii** [comment]
yeah, only nonchemists will ever claim that macro deathmixes are even a problem, we were easily doing those long before chem macros.

But I can perhaps fold to the fact that putting 10000u of meds in the fridge before even 5 minutes have passed into the round could be attributed to a balance issue. Maybe.

**Comment by CPTANT** [comment]
You might have been making them before, but you weren't making them in 0.1 seconds or in unlimited quantities.

**Comment by ExcessiveUseOfCobblestone** [comment]
you're not making them in unlimited quantities now?

**Comment by yorii** [comment]
>You might have been making them before, but you weren't making them in 0.1 seconds or in unlimited quantities.

This isn't even an argument as you don't require an unlimited amount and making them in 20 seconds is basically the same as 1 second. With this PR however you'll be back to making them on your own or waiting the amount of time required for science to upgrade your machine.

I don't understand why you're even complaining about issues you have that this PR will solve.

**Comment by CPTANT** [comment]
>making them in 20 seconds is basically the same as 1 second.

No it is not.

**Comment by yorii** [comment]
You can't honestly be saying that the balance issue with a deadly chemical is the fact that it is easy to make and the solution to balance the deadly chemical would be to timegate it?

If there is any issue with a reagent being too powerful to have access to in unlimited amount, the balance issue is with the fucking chem itself, and not with how fast or slow it is to acquire. It doesn't matter if it would take 0.1 seconds to procure it or 10 bloody minutes, you are looking at the wrong fucking issue.

**Comment by Doppeltongue** [comment]
My only gripe would be if this gets merged alongside the sleeper nerf.

**Comment by yorii** [comment]
>My only gripe would be if this gets merged alongside the sleeper nerf.

Time to seek therapy then because they are both definitely getting merged.

**Comment by arsserpentarium** [comment]
No macros likes non chemist.
Unlimited macros likes chem nerds, who are developing 1 button recipes for everything.
Limited macro likes no one.
Delete them completely, or don't bother.

**Comment by vuonojenmustaturska** [comment]
henk

**Pull request merged**
