### PR TITLE
Wendigo Cave Ruin & Domain Aesthetic Refresh + Wendigo Corpse Fix

### PR DESCRIPTION
**Pull request by Ical92**
## About The Pull Request

Updates the Wendigo Cave ruin on Ice Box and it's domain to be more detailed, without changing the shape of the arena too much. Also fixes the Wendigo attacking corpses,

image
image
And the domain!
image
## Why It's Good For The Game
Makes the Wendigo arena and the surrounding area more varied visually, as well as stopping the Wendigo from attacking the decorative corpses used in the domain.

(Previous Arena for reference)
image

## Changelog
:cl:
qol: Wendigo Cave ruin gets an aesthetic refresh
fix: Wendigos (Wendigi?) no longer attack corpses

/:cl:

### CODE REVIEW

**Comment by CCC23** [comment]
I can already see myself running into the trees screaming about this pr as im gunned down by the tohua

**Comment by Ical92** [comment]
> I can already see myself running into the trees screaming about this pr as im gunned down by the tohua

Well, the trees are only on the edge so you wouldn't run into them any more than a regular wall. Plus, the projectiles from the Wendigo can break the trees, so you won't have to worry about them for long.

**Comment by Admiral-Gigaton** [comment]
does this affect the bitrunner cave?

**Comment by Ical92** [comment]
> does this affect the bitrunner simulation for this fight? (is there a fight for this? i dunno)

It does now! (Or it will once I commit this)
image

**Pull request merged**
