### PR TITLE
IV drips now pull you closer and create a beam to you

### PR DESCRIPTION
**Pull request by Mothblocks**
## About The Pull Request

https://github.com/user-attachments/assets/173c1753-3da4-4180-80ea-eb49d19e7b2f

Purely visual. Pulling someone from an IV drip is dangerous so it's nice to make it more clear than the current very small appearance change that doesn't give you any more information than that *someone* is connected.

If you review tell me on Discord bc I don't check GitHub

## Changelog

:cl:
qol: IV drips now create a beam from their spout to your body, and will visually pull you closer.
/:cl:

### CODE REVIEW

**Comment by mc-oofert** [comment]
the pixel offset kinda looks bad

**Comment by moocowswag** [comment]
I like the offset

**Comment by carlarctg** [comment]
when we needed her the most she returned

**Comment by Mothblocks** [comment]
> I like the offset but does it still offset people who are buckled to something like a bed

no



> when we needed her the most she returned

we did emdr and i saw that i was disappointed that i dont work more on ss13

**Comment by Sadboysuss** [comment]
what happens if the mob attached to the IV is pulled by another mob?

**Pull request merged**
