### PR TITLE
golems can now become botanists and virologists AND chefs

### PR DESCRIPTION
**Pull request by Fikou**
## About The Pull Request

golem vendor now gets a rhinovirus culture bottle and a seed vendor refill, allowing them to do jobs of botanists, chefs and virologists, both cost 1000 points

## Why It's Good For The Game

golems are a really fun lavaland role, the only one thats able to come close to doing what the station can, would be nice for them to be able to do these 3 jobs they couldn't previously
they can already buy a start for a xenobio department with the grey slime and thats a much more powerful department so 2 more starting things shouldnt hurt

## Changelog
:cl:
add: The Golem Ship vendor now has a bottle of rhinovirus and a seed vendor refill, both for 1000 points, allowing you to do more fun stuff!
/:cl:

### CODE REVIEW

**Comment by Qustinnus** [comment]
this is definitely a bruh moment pr

**Comment by SomeoneYouProbablyKnow** [comment]
Tittle says 2 jobs but the body says botany viro and chef. I have been tricked and i don't like being tricked.

**Comment by Fikou** [comment]
> Tittle says 2 jobs but the body says botany viro and chef. I have been tricked and i don't like being tricked.

no it doesnt

**Comment by Anonmare** [comment]
Wait, aren't golems virus_immune?

**Comment by Fikou** [comment]
> Wait, aren't golems virus_immune?

yes, but theres a symptom that makes inorganic things able to get viruses, and you can experiment on monkeys until you get it

**Comment by spookydonut** [comment]
image
you ruined this.

**Comment by Fikou** [comment]
> image
> you ruined this.
its still in your heart

**Comment by ATH1909** [comment]
> > Wait, aren't golems virus_immune?
> 
> yes, but theres a symptom that makes inorganic things able to get viruses, and you can experiment on monkeys until you get it

Maybe you should give them a bottle of a virus that just has the inorganic biology symptom in it instead of (or in addition to?) a bottle of rhinovirus?

Do golems have a source of milk to make virus food with?

**Comment by Fikou** [comment]
the pr adds botany, which allows biogenerator use for milk

**Comment by ExcessiveUseOfCobblestone** [comment]
doesn't this step on the toes of lifebringers (botany) and syndie base (viro)?

**Comment by Pumpkinoe** [comment]
yeah this does kind of step on the syndiebase and lifebringer's toes a bit
i think golems should be more centered around mining + science since they fill that niche for the lavaland roles

**Comment by OverlyGeneric** [comment]
what the hell is even the point of golems anymore now that R&D is simplified to techwebs. it's just an extra life to piss on the station by stealing points and annoying miners at this point.

**Comment by Fikou** [comment]
> doesn't this step on the toes of lifebringers (botany) and syndie base (viro)?

its an optional task golems may pursue if they have enough cash, they dont get automatically all botany machines even better than fully upgraded with a magic chem machine, gatfruits and cherry bombs like how lifebringers do and unlocking the vendor is not roundstart, it will probably be done around the same time golems do xenobio, which takes a similar amount of setup, so like one hour in or more
they already "step on" syndie base by allowing them to do chemistry, but again, golems need preparation and points to unlock the virus, and they need to create the machinery that doesnt exist, also they need a botany push for the milk needed for virus food, lastly theres nothing you can do with syndie base viruses, wow you made a cool regen virus for your ship that no one is gonna visit ever or made an ultra killing virus that you cannot send on the station through some cargo pod to spread aids

**Comment by wesoda25** [comment]
Overescalation: biowarfare edition

**Comment by Pumpkinoe** [comment]
give charlie a space ship that allows them to go to lavaland to mine for materials

**Comment by ExcessiveUseOfCobblestone** [comment]
Not really a fan, ghost roles should be focused around one of two things:

1) A role hyperfocused on a job, in which you can learn a particular trade.
2) A role focused on interacting with the crew in some way, in which you shake up the meta (perhaps provide something they can't otherwise obtain).

It should not be a role where you just recreate the station, Charlie being an exception not a model.

I'd really like to see golems reworked anyways to not be "leech off station tech and occasionally war because a golem and human have some minor escalation", especially since they're no longer needed as a RND tut.

**Pull request closed without merging**
