### PR TITLE
Changes to Path of Lock

### PR DESCRIPTION
**Pull request by Justice12354**
## About The Pull Request
The Path of Lock currently only sidepaths with Path of Flesh and it's a huge mess. I've made it so now it sidepaths with Ash and Cosmic in a more consistent way to the Path Tree. It's currently lacking a spell in the slot between Cosmic and Lock on the third row, but Idk how/what to put there, so it'll be left blank until someone puts another spell there
## Why It's Good For The Game
CONSISTENCY!!!!
The Paths now look like the following:
imagem
## Changelog
:cl:
qol: The Path of Lock now sidepaths into the Paths of Ash and Cosmic, becoming consistent with the other Paths
/:cl:

### CODE REVIEW

**Comment by Rex9001** [comment]
I think Cosmic <-> Ash <-> Lock is the better order here, keeps most the sidepaths intact and places lock in an actual position in the heretic tree

**Comment by Justice12354** [comment]
> I think Cosmic <-> Ash <-> Lock is the better order here, keeps most the sidepaths intact and places lock in an actual position in the heretic tree

There will always be certain spells that will not fit into the place they are at since you have to open up the tree's loop and stuff a new path inside. Changing the order will also have a few spells out of context. I believe the best way to fix this might be to re-contextualize Apetra, for instance, by making it more cosmic-sided. Maybe make it a "COSMIC SLASH!" so it doesn't make you think so much about Flesh

**Comment by mc-oofert** [comment]
I thought this was a balance PR and almost got a stroke but otherwise very good PR

**Comment by Justice12354** [comment]
> I thought this was a balance PR and almost got a stroke but otherwise very good PR

I don't have enough free time or coding abilities for that pahahahaha

**Comment by mc-oofert** [comment]
why what

**Comment by Justice12354** [comment]
> why what

The Path of Moon has relocated the Path of Lock into a possible place. It does have a flaw still, but it will be something for February

**Pull request closed without merging**
