### PR TITLE
Changes a few radio channel colors

### PR DESCRIPTION
**Pull request by ghost**
Changes a few radio channel colors to be like Bay's colors, as I thought they looked a lot better.
Before

tgoldcolors

After

baycolors

:cl:
tweak: Changed the Command and Security radio colors
/:cl:

### CODE REVIEW

**Comment by lzimann** [comment]
the supply one is kinda close to the traitor radio color imo, the current colors look fine, there's no need to change them

**Comment by John-Peppercorn** [comment]
Always liked bay's colors more. And brown and dark purple aren't that similar.

**Comment by GunHog** [comment]
Command looks too close to OOC default color now, Supply now looks too close to Syndicate as well. Furthermore, they are dull compared to the sharp contrast among channels now. I do not believe this to be an improvement.

**Comment by jughu** [comment]
Can we not change colours at all they are fine and nothing is wrong with them

**Comment by uraniummeltdown** [comment]
>Can we not change colours at all they are fine and nothing is wrong with them

The Bay ones are easier on the eyes, these colors match the departments.

**Comment by lzimann** [comment]
the current colors are perfectly fine, let's stop changing shit for the sake of change when things are fine

**Comment by ChangelingRain** [comment]
I only like the command one, really.

**Comment by Niknakflak** [comment]
:-1:

**Comment by Cyberboss** [comment]
Command is WAY to close to OOC

**Comment by PKPenguin321** [comment]
:-1: New supply color is fucking bad and looks like traitor radio, engineering radio has no reason to look like cargo radio, command radio is now more like ooc and much subtler meaning it's easier to miss, and the sec color isn't different enough to justify the rest of the PR.

**Comment by XDTM** [comment]
OOC chat is bright blue and has OOC in front of it. I'd keep the command chat color. Also, yellow on white is just as subtle and easy to miss.

**Comment by Anonmare** [comment]
Command is _too_ yellow tbh, it's the one radio colour that would benefit from the change. Seriously, it's godawful and i have to strain my eyes constantly for it.

**Comment by Iamgoofball** [comment]
:-1:

**Comment by Shadowlight213** [comment]
Command, maybe. I'd need a side by side comparison of it and OOC and medbay to be sure.
The others, major :-1:  looks pretty bad.

**Comment by uraniummeltdown** [comment]
@Shadowlight213 
medcomooc

Since people really don't like them I changed Engineering and Supply back to normal. I kept Command as I really think the current Command color is ugly and doesn't fit the department, and Security as I just made it a bit darker.

**Comment by Cyberboss** [comment]
Better

**Comment by KorPhaeron** [comment]
Fine now that supply doesn't look like traitor I think

@tgstation/commit-access 

Any last opinions? Only sec and command changed now

**Comment by optimumtact** [comment]
I have no strong opinion either way.

**Comment by KorPhaeron** [comment]
I might not be worth the inevitable bikeshedding

**Comment by AnonymousNow** [comment]
I go away for a few months and you fuck up the command channel colour with a slender minority approval. I keep mixing it up with medical chat, and I'm a 3 on the colourblindness scale (below average).

**Comment by optimumtact** [comment]
Hahah you have stupid eyes

**Comment by Dorsisdwarf** [comment]
feel free to change command color again. The power is within you.

**Comment by AnonymousNow** [comment]
I know next to nothing about coding, but I'm going to risk breaking everything for a simple colour change.

**Comment by jughu** [comment]
#anonymousnow its just a simply color change 😆 just get the hexcode change it and viola😧

**Comment by AnonymousNow** [comment]
I know that much; I've never put in any sort of coding for anything ever, and I'm not sure how GitHub actually works in that regard. Will clicking "edit file and submit pull request" be enough? Time to find out!

**Comment by jughu** [comment]
@anonymousnow fork make new branch switch to that branch select wished codefile to edit push commit into branch and then compare changes

**Pull request merged**
