### PR TITLE
Removes die of fate from snowdin

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
Because @Cheridan is a madman and having 6 snowdin ops rolling until they become a wizard squad sounds terrible

### CODE REVIEW

**Comment by Zilenan91** [comment]
Speed merge pls the ops have defibs and healing wands this is going to be bad.

**Comment by Buggy123** [comment]
Holy shit i didn't even know my infinite roll PR got merged woo!

**Comment by Core0verload** [comment]
Being dusted means no wand can save you. And with Die of Fate, chance of being dusted is equal to chance of being wizard.

**Comment by WJohn** [comment]
Except that you have multiple respawns here so you actually have a pretty decent chance to get wizard at least once.

**Comment by Zilenan91** [comment]
Doesn't die of fate just kill you rather than dust you or am I wrong

**Comment by duncathan** [comment]
I believe if you roll a 1 it dusts you

**Comment by Cheridan** [comment]
hehe

**Pull request merged**
