### PR TITLE
Ports "Crew Transfer" vote from other servers

### PR DESCRIPTION
**Pull request by etherware-novice**
## About The Pull Request
Ports the crew transfer/shuttle vote feature other servers have
## Why It's Good For The Game
Lets you more officially do a shuttle vote, preventing endless rounds where nobodys having fun
## Changelog
:cl:
add: crew transfer vote
/:cl:

### CODE REVIEW

**Comment by Sealed101** [comment]
this isn't shiptest/voidcrew, people do shuttle votes IC or just destroy comms consoles if noone can call

**Comment by Jolly-66** [comment]
Honestly this isn't needed for TG.
Rounds don't last long enough to warrant this system.
Not even my time on Manuel would warrant this, due to how "long" the rounds were (compared to the 3 LRP servers).

**Comment by Oranggu** [comment]
Just restart vote with a new name 😕 not feelin this one

**Comment by optimumtact** [comment]
i will never support this.

**Comment by Mothblocks** [comment]
tried before with https://github.com/tgstation/tgstation/pull/53584

**Comment by Wallemations** [comment]
Even if we figured out an in-character way to send out a vote to people, like through PDAs or something like that, I doubt anyone on a TG server would need to use this.

**Comment by MrDoomBringer** [comment]
see also https://github.com/tgstation/tgstation/issues/57940

**Pull request closed without merging**
