### PR TITLE
Adds poutine

### PR DESCRIPTION
**Pull request by Sylphet**
## About The Pull Request

This PR adds a recipe for poutine to the game. It's easily made in the kitchen, from fries, gravy, and a cheese wedge. It's filling, delicious, and is perfect for when you've had too many fringe weavers.

## Why It's Good For The Game

More recipes are always fun, for the chefs that make them, and the players who are tired of fried eggs _again._

## Changelog
:cl:
add: Added poutine recipe, and a new gravy reagent to go along with it.
/:cl:

### CODE REVIEW

**Comment by Iatots** [comment]
think of the canadian players

**Comment by 81Denton** [comment]
fucked up how we don't have a gravy reagent

**Comment by Sylphet** [comment]
it really is, but i can probably make once i have a better idea of what i'm doing in dream maker

**Comment by Ratvar** [comment]
Can we add vlad poutine recipe made with bear meat

**Comment by Sylphet** [comment]
that would be doable. i could do a whole series of poutine - but there's not much sense having slightly different versions of the same food, and i'd rather work on some more interesting things

**Comment by RiskySikh** [comment]
poutine is a must

**Comment by CRITAWAKETS** [comment]
solution to adding more poutines: custom poutine

**Comment by WarlockD** [comment]
I remember talking to my step-mom about the cooking recipes in here and her response was, "I don't understand.  You have bacon, but not bacon fat?  Why not just make a bacon fat regent and make everything taste good?"

**Comment by 81Denton** [comment]
Your step mom is onto something, bacon fat could be used as a weaker version of the secret sauce.

**Comment by OverlyGeneric** [comment]
op, how do you make custom poutine?

is it just a crafting recipe or can you actually throw in the bacon bits?

**Comment by Sylphet** [comment]
you make poutine through the crafting menu, using fries, a cheese wedge, and the new gravy reagent, which is made from milk, nutriment, and flour. once you have poutine, you can add any ingredient you want to it, in the same way that you would put something on a pizza, or in a bun.

**Comment by Farquaar** [comment]
I support this as a man who, at several points during his life, sustained himself on nothing but food truck poutine for weeks on end.

**Pull request merged**
