### PR TITLE
Gives Janiborgs a flyswatter, a bucket, and a paint remover.

### PR DESCRIPTION
**Pull request by zeroisthebiggay**
## About The Pull Request

Gives Janiborgs a flyswatter, a bucket, and a paint remover. That's it.

## Why It's Good For The Game

Janiborgs have had a mop with no bucket for ages. They've also been unable to clean up after colorful reagent spillages and Janiborgs being deployed to destroy swarms of bees (and/or) angry moths sounds hilarious.

## Changelog
:cl: zeroisthebiggay
add: Gives Janiborgs the long lost bucket for their mop.
add: Gives Janiborgs a paint remover.
add: Gives Janiborgs a flyswatter to destroy angry bees and moths with.
/:cl:

### CODE REVIEW

**Comment by Militaires** [comment]
can they even use the mop on the bucket? it's technically not inhand

**Comment by zeroisthebiggay** [comment]
> can they even use the mop on the bucket? it's technically not inhand

yes they can

**Comment by DaxDupont** [comment]
Isn't their mop snowflake? Might as well make it like the advanced mop.

**Comment by zeroisthebiggay** [comment]
> Isn't their mop snowflake? Might as well make it like the advanced mop.

they have an advanced mop upgrade and it's _really stupid_ but consistency's sake.

**Comment by Tlaltecuhtli** [comment]
they can clean by walking on top, can use soap for unreacheable tiles and have an adv mop for slip griefing why would they need the normal mop

**Comment by kriskog** [comment]
Buckets and mops can hold other things than water. Advanced mop however, can not.

This is a good change, needs a way to transfer stuff from a container to the bucket though.

**Comment by MegaEmpirical** [comment]
Thank fucking god. This has annoyed me for so long. Though I've always just thought their mop should always be wet.

**Comment by zeroisthebiggay** [comment]
> Buckets and mops can hold other things than water. Advanced mop however, can not.
> 
> This is a good change, needs a way to transfer stuff from a container to the bucket though. Normally, you'd need hands to do that.

you can bang a water tank or a sink to get water in your bucket but i think it'd be safer to keep janiborgs from washing the floors with thermite though that might be a funny emag module

**Comment by ExcessiveUseOfCobblestone** [comment]
Doesn't flyswatter do immense damage to certain species?

**Comment by ATH1909** [comment]
> Doesn't flyswatter do immense damage to certain species?

They have an effective force of 10 against mothpeople and 30 against flypeople; it's not really a big deal.

**Comment by kriskog** [comment]
> 
> 
> > Buckets and mops can hold other things than water. Advanced mop however, can not.
> > This is a good change, needs a way to transfer stuff from a container to the bucket though. Normally, you'd need hands to do that.
> 
> you can bang a water tank or a sink to get water in your bucket but i think it'd be safer to keep janiborgs from washing the floors with thermite though that might be a funny emag module.

But what about space cleaner and space lube? It's not our job to make borgs safe, their laws are supposed to do that.

**Comment by zeroisthebiggay** [comment]
> Doesn't flyswatter do immense damage to certain species?

flies are a meme race that got removed from roundstart and moths can already be flashed through protective gear it's not a _huge_ deal especially when anyone can break into the janny's closet and get a flyswatter that way.

**Comment by Arianya** [comment]
Gonna :-1: giving them a paint remover.

Borgs shouldn't be able to do every single job a human in that job could do, they're meant to be specialized. Janiborgs are already very good at cleaning up normal messes, though I approve of giving them a bucket/mop or advanced mop for that purpose since slips are good.

**Comment by anconfuzedrock** [comment]
Janiborgs can't clean up large trash, and paint remover has only one can so giving it to borgs is a great idea to make it a bit less bullshit. Janitors are outclassed by the janiborg in other ways that need nerfed.



I swear on my life the only reason janiborgs have a mop is so they have something with force to attack with.

**Comment by ExcessiveUseOfCobblestone** [comment]
> outclassing a janitor

tfw no borg ADCs.

> This is a good change, needs a way to transfer stuff from a container to the bucket though. Normally, you'd need hands to do that.

Go mediborg if you want reagent transfer

**Review by ExcessiveUseOfCobblestone — APPROVED** [review]

**Comment by zeroisthebiggay** [comment]
> Gonna 👎 giving them a paint remover.
> 
> Borgs shouldn't be able to do every single job a human in that job could do, they're meant to be specialized. Janiborgs are already very good at cleaning up normal messes, though I approve of giving them a bucket/mop or advanced mop for that purpose since slips are good.

remember that paint removers are almost useless and can only remove paint off of floors and walls and _not items like cameras, physical items, and firelocks_ because ????

**Comment by MegaEmpirical** [comment]
And borgs can already fix floors. Unsure if their space cleaner bottle works on walls, if so then the complaint doesn't matter.

**Comment by zeroisthebiggay** [comment]
> And borgs can already fix floors. Unsure if their space cleaner bottle works on walls, if so then the complaint doesn't matter.

speaking of which yes they can already unfuck floors by using a crowbar but that removes the pretty decals and the only time you'll see colored walls is if someone gets their hands on a paint bucket themselves

**Comment by ExcessiveUseOfCobblestone** [comment]
Is it really worth having the argument of whether or not borgs should be able to remove painted floors/walls?

**Comment by zeroisthebiggay** [comment]
> Is it really worth having the argument of whether or not borgs should be able to remove painted floors/walls?

no not really.

**Pull request merged**
