### PR TITLE
Ports oracle's cult structure sprites

### PR DESCRIPTION
**Pull request by nicbn**
[Changelogs]: # 
:cl:
imageadd: Updates the blood cult structures: Forge: Altar, Archives, and Pylon. (by Quantum-M)
/:cl:

Stolen from https://github.com/OracleStation/OracleStation/pull/1050

### CODE REVIEW

**Comment by Nabski89** [comment]
These sprites seem to have missed the 3/4's boat, and really don't seem to be an improvement on what we already have.

The only one that isn't just back to a front view of the existing sprite is the forge, and the lava effect on our current forge seems better.

**Comment by WJohn** [comment]
What nabski said. These need to be substantially better than our current ones to make it in, and they're not. I still think 3/4th boat should be happening, though.

**Comment by AnturK** [comment]
Pylon looks like a desk lamp instead of spooky polyhedron

**Comment by nicbn** [comment]
Warn me when 3/4 boat arrives

**Pull request closed without merging**
