### PR TITLE
Validate all character slots on preference load

### LINKED ISSUE #65318: Quirk selection doesn't validate on save load, allowing invalid quirk setups (from older savefiles or due to bugs)
## Reproduction:

Quirks, when loaded, do not validate if they are a legal setup. 

Meaning if you have two quirks invalid with one another selected on your save file - if your character file is older and an invalid setup was added, or a bug occurred that allowed an invalid setup - your quirks will not reset, and you will be allowed to have an illegal quirk setup in game. 

Source: I have both mime-fan and clown-fan equipped on my local save file testing a bug a while ago that allowed both to be chosen. Every time I load in both quirks are assigned despite being incompatible with one another.

### PR DESCRIPTION
**Pull request by ZephyrTFA**
## About The Pull Request

See title.
Ensures that all character slots don't have invalid setups.
## Why It's Good For The Game

According to [this discord message](https://discord.com/channels/326822144233439242/326831214667235328/1221868487035846716) we do not perform character validation on loading preferences, only when attempting to update. This means we can have instances where players use outdated and banned quirk pairings. This prevents that from happening in the future and is also made expandable so that we can check for anything else in the future as it arises.
Fixes https://github.com/tgstation/tgstation/issues/65318

## Changelog

:cl:
balance: Client Preferences now validate character slots at load.
/:cl:

### CODE REVIEW

**Comment by MrMelbert** [comment]
Fixes #65318

**Review by MrMelbert — COMMENTED** [review]
image

**Comment by ZephyrTFA** [comment]
> image

addressed

**Review by MrMelbert — COMMENTED** [review]
I pulled the code locally and it didn't fix the invalid quirk setup I have on my local char

image

**Comment by ZephyrTFA** [comment]
go away stalebot

**Pull request closed without merging**
