### PR TITLE
Unfucks my docking port

### PR DESCRIPTION
**Pull request by pubby**
PubbyStation's escape dock is now defined with poise and sanity and all hell won't break loose once Kor's shuttle PR gets merged.

Bonus: the diff has extra bloat because I snuck two holopads into the commit.

### CODE REVIEW

**Comment by Iamgoofball** [comment]
pimp my shuttle

**Comment by Jordie0608** [comment]
It looks more like the diff has extra bloat due to a lack of map merger.

**Comment by pubby** [comment]
I ran the mapmerger script before each commit, but maybe I'm doing it wrong?

This is what I'm invoking (on linux):

`python3 tools/mapmerge/mapmerger.py _maps 1`

And it does seem to do *some sort* of conversion, as evident by the `//MAP CONVERTED BY dmm2tgm.py THIS HEADER COMMENT PREVENTS RECONVERSION, DO NOT REMOVE ` comment.

I figured the diffs were big because the changes added/removed three-letter 'palette' entries in the dmm file.

**Comment by Jordie0608** [comment]
I'm not bothered to check so it's possible.

**Comment by JJRcop** [comment]
very poor choice of PR title

**Comment by ExcessiveUseOfCobblestone** [comment]
Wjubby: my docking port is leaking for you

**Comment by xxalpha** [comment]
I can't put comments on the map file, but if you check the dictionary entry with "bVR" key, the very next key is "chj". Text edits like this can break the map merger, and in this case it did.

**Pull request merged**
