### PR TITLE
Standardizes cable colors

### PR DESCRIPTION
**Pull request by 81Denton**
## About The Pull Request

This PR standardizes cable colors: Power source to SMES is red, SMES to main grid is yellow. Cables that can connect the main grid to AI sat/telecomms sat are cyan.

It also fixes some odd wiring at the Pubby incinerator, the zoo ruin and the BMP ship ruin.

This would probably be a good testmerge candidate, since it touches a lot of map code. Aside from the three files where I tweaked/fixed cables, the only effect should be different colors.

## Why It's Good For The Game
Cable colors are all over the place, which causes a lot of confusion for players that haven't memorized every single area's cable layout. Cables are probably the smallest and most annoying objects to interact with ingame, so what they're doing should be obvious at first glance.

I chose red for power source -> SMES wires, since these are most likely to really hurt when you touch them. Yellow is IMO the best color for the main grid, since it doesn't overlap with scrubber pipes like red cables do.

## Changelog
:cl: Denton
tweak: Power cable colors have been standardized across all areas. Power input cables are now red, while the main grid is yellow.
fix: Fixed SMES input/output wiring being connected to each other in the abandoned zoo and BMP ship space ruins.
tweak: Tweaked cables near Pubbystation's incinerator SMES to keep them from overlapping.
/:cl:

### CODE REVIEW

**Comment by Tlaltecuhtli** [comment]
>SMES to main grid is yellow OR white
😂

**Comment by 81Denton** [comment]
Well fine, I'll have a look at Delta as well

**Comment by MrPerson** [comment]
Jesus this must have sucked to do. Mad respect.

**Comment by Barhandar** [comment]
I don't like main cables being yellow because muh nostalgia about red cables, but your color reasoning is sound.

**Comment by DaxDupont** [comment]
Red for main grid is better looks wise.

**Comment by 81Denton** [comment]
Red overlaps with scrubber pipes and makes them harder to see since they're both the same color.

**Review by SpaceManiac — APPROVED** [review]

**Pull request merged**
