### PR TITLE
Change pistol outlines color

### PR DESCRIPTION
**Pull request by Destrings2**
Change pistol outlines color in projectile.dmi from black to gray to be
consistent with other gun outlines

### CODE REVIEW

**Comment by optimumtact** [comment]
take a quick in game pic so people can compare

**Comment by lombardo2** [comment]
Just a quick change in the outlines. I was looking at the projectile guns sprites and noticed the only gun with black outlines is the pistol, even when there are guns with darker bodies. Also made the handle a little bit smaller in order to better represent the handle-barrel relation.

Before:
pistolbefore

After:
pistolafter

In-game:
ingame

**Comment by optimumtact** [comment]
ta

**Comment by coiax** [comment]
image

I'm sure it's great, but my eyes cannot tell the difference.

**Comment by Supermichael777** [comment]
>I'm sure it's great, but my eyes cannot tell the difference.

**Comment by lombardo2** [comment]
Hahaha exactly. Alone it's looks very similar but looked in the context of other guns the black outlines stand out. It's just a small tweak so all guns have the same outline style.

**Comment by Supermichael777** [comment]
yeah try 24 24 24

**Comment by coiax** [comment]
Even though I still can't see the difference, I have strong opinions on the colouring, and feel that @Supermichael777 is wrong and evil, and it should be 25 24 24

**Comment by Supermichael777** [comment]
🥇 shitposting 👍

**Comment by lombardo2** [comment]
Okay, 

Before:
image

After:
image

**Comment by Arianya** [comment]
Trying to find the difference was bugging me so here:

http://diff.pics/LmAEulYmWMnY/1

Probably worth noting the grip change since I missed that even looking at the two images.

**Comment by Bawhoppen** [comment]
It is very slight, but I think what you had just before the last edit is the best

**Comment by coiax** [comment]
Okay, now I can see the difference.

**Comment by KorPhaeron** [comment]
@WJohn

**Pull request merged**
