### PR TITLE
Removes flightsuits

### PR DESCRIPTION
**Pull request by silicons**
Why: Code is in the way of certain refactors for pixel movement like mob movement delays, snowflake all over the place, and as of right now it's just a speed booster. I do intend on PRing this again after completely overhauling and reworking the code and features of this at a later date, likely after or right before pixel movement is out. Assets (icons) left in for future usage.

:cl:
del: Removed flightsuits
/:cl:

### CODE REVIEW

**Comment by subject217** [comment]
>I do intend on PRing this again after completely overhauling and reworking the code and features of this at a later date

another feature joins the forgotten pile of things that were going to be PRed again at a later date

**Comment by ishitbyabullet** [comment]
PSA: important part of this is
> I do intend on PRing this again

> 

so don't fear about it being gone forever rip

**Comment by kevinz000** [comment]
@subject217 only this time it's my codebaby :^)

**Comment by subject217** [comment]
The point being that even if you do intend to PR it in the future, it is perhaps wise to treat this like they will never be added in again. It's still not really a problem. Removing flight suits is pretty unimpactful.

**Comment by WJohn** [comment]
These could be thrown out permanently in favor of just giving jetpacks indoor-usage. 6 extra buttons and manufacturing barriers is a pain in the butt.

**Comment by Militaires** [comment]
image
brought to you by your's truly, ((((((discord)))))
**(dont shoot the messenger)**

**Comment by ExcessiveUseOfCobblestone** [comment]
I think when they were first added everyone asked their purpose, I wonder what that answer was but i'm too lazy to check.

**Comment by ExcessiveUseOfCobblestone** [comment]
@subject217 you can always add them back with better implementation :^)

**Comment by ninjanomnom** [comment]
He's actually removing them because we keep making fun of how bad the code is for them

**Comment by ExcessiveUseOfCobblestone** [comment]
if only the circuit authors...

**Review by Cyberboss — APPROVED** [review]

**Comment by GunHog** [comment]
You ARE adding this back soon, right, Kev? Please?

**Comment by ninjanomnom** [comment]
Mission successful guys the flightsuit is gone. He's done his last pr; time to ban kevin

**Comment by Fikou** [comment]
image
aged like fine wine

**Pull request merged**
