### PR TITLE
Adjusts alignment on the new examine blocks to reduce visual noise

### PR DESCRIPTION
**Pull request by scriptis**
## About The Pull Request

Builds upon #67937 by @13spacemen. I couldn't find you in coderbus, and I wanted your opinion on this!

I really like the new examine blocks, but felt that they were a bit too intrusive and it really irked me that they weren't aligned with the rest of the text in the chat window. This PR does absolutely nothing except left-align the inspect blocks with negative margins and remove the borders.

Before:

https://i.imgur.com/T6okxJm.png
https://i.imgur.com/BXhpgLr.png

After:

https://i.imgur.com/BxzNADu.png
https://i.imgur.com/7wUYA2g.png

## Why It's Good For The Game

Reduced visual noise. Maybe people like it better. Feedback? Thoughts?

## Changelog

:cl:
qol: Inspect blocks are now aligned with the rest of the text in tgchat
/:cl:

### CODE REVIEW

**Comment by scriptis** [comment]
Oh, yeah, no, I'm absolutely bikeshedding here. I'll adjust the margins and background colors here in a bit and upload some new screenshots; I'll also seek out some other feedback to see if this is worth it. I'll let you know.

**Comment by Mooshimi** [comment]
I like the borders and the indentation.... 😢

**Comment by timothymtorres** [comment]
The borders and indentation are good separators.  Removing them makes it harder for people to tell what is an examine block and what's regular chat.  

-1 from me.

**Comment by scriptis** [comment]
Apparently I'm the exception :q

Well, nothing lost.

**Pull request closed without merging**
