### PR TITLE
AIs can now flip again

### LINKED ISSUE #54391: [CRITICAL] AI cannot spin/flip anymore
AI needs to spin. Its a integral part of the gameplay for everyone on the station, this needs to be fixed asap.

#53981 broke this

### PR DESCRIPTION
**Pull request by Mothblocks**
## About The Pull Request
Fixes #54391, which was broken by the mobility refactor requiring TRAIT_HANDS_BLOCKED not be active. AIs, however, always have this active.

## Why It's Good For The Game
It's always funny to see as a non-AI when you forget its possible.

## Changelog
:cl:
fix: AIs can now flip again.
/:cl:

### CODE REVIEW

**Comment by ATH1909** [comment]
❤️

**Comment by ShibaInuLord** [comment]
powercreep

**Comment by Rohesie** [comment]
This is an unfortunate development.

**Comment by Jared-Fogle** [comment]
@Rohesie scared?

**Comment by Paxilmaniac** [comment]
Ai powercreep

**Comment by techno0** [comment]
still not merged REEEEEEEEEEEEEE

**Comment by Fikou** [comment]
YEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEES

**Pull request merged**
