### PR TITLE
Makes the watcher wing crusher trophy less effective

### PR DESCRIPTION
**Pull request by ChangelingRain**
yyyyup, it's strong enough to mostly nullify bosses if you get it and that's not K.
bosses aren't supposed to be unable to use their special attacks a good 90% of the time, that's not K.

the icewing trophy is unaffected.

### CODE REVIEW

**Comment by Buggy123** [comment]
I've made my stance on this clear. This is nerfing a already substantially inferior piece of equipment.

**Comment by 81Denton** [comment]
Has this ever been an issue? For January '18, only about 15% of all redeemed vouchers have been for crushers. You'd figure this number would be much higher if this was a superior weapon compared to KAs or plasma cutters.

**Comment by ChangelingRain** [comment]
It's technically superior, but it takes farming time since the watcher wing wasn't supposed to be easy to obtain or particularly useful;
it's effectively supposed to be a "oh hey cool I got a thing" bragging rights object rather than a practical bonus

**Comment by Buggy123** [comment]
These are the current statistics for voucher redemption(January 2018):

Survival Capsule and Explorer's Webbing - 851
Resonator and Advanced Scanner - 1828
Mining Drone - 75
Extraction and Rescue Kit - 190
Crusher Kit - 547
Mining Conscription Kit - 69

(source: https://atlantaned.space/statbus/stat.php?year=2018&month=1)

So the crusher kit comes in behind the Explorer's Webbing. But here's the real kicker: the crusher kit comes with a free webbing(and fire extinguisher). A majority of people, given the choice, prefer a _survival capsule_ over the crusher.

You can purchase the crusher from vendors, too, and trust me that's even worse. 87 people bought crushers last week, compared to 214 kinetic accelerators (of which there are 6 free ones available to miners), or 3848 survival medipens.

If you want I could probably go deeper and use regex to search the logs and compare total number of megas killed with the crusher vs total killed with KAs/Plasmas, but I'm pretty sure we'll find the same picture: _people don't use kinetic crushers_, probably because they're shit.

And fine, if its "challenge mode" just leave it as-is. Don't nerf this already shitty piece of equipment even _further_ because its not enough of a "challenge". If you want a challenge so damn much, you start with a survival knife, go kill megas with that.

**Comment by ChangelingRain** [comment]
Bosses shouldn't be unable to use abilities because you're attacking them, and this, according to *you specifically*, lets you do that.
it's not an okay thing, and if it's a big enough nerf to your pattern of crusher use that you're this vehemently against it I think you need to get good.

**Comment by Buggy123** [comment]
_My_ pattern of crusher use? I've _tried_ to use crushers a little, as well as a few times in the past, because someone told me about that trick and I thought I should give it another chance, and you know what I discovered?

It's **shit**.

Its a pain to move around, its unwieldy, its dangerous and it puts you in a lot of pain early on, and ultimately its inferior to both KAs and Plasmas because by the time you get the right trophies such that it _can_ compete with those...

#   The emergency shuttle has been called
##          "I STUBBED MY TOE"

If I'm not killing megas by the 20 minute mark, I'm not going to be _able_ to kill megas.

>Bosses shouldn't be unable to use abilities because you're attacking them

Why? I say its a perk of going through the immense effort to upgrade this shitty weapon. If you have the skill to use it you should ultimately be _rewarded_ for your efforts with a more powerful weapon.

**Comment by Xhuis** [comment]
I don't play much miner anymore, but when I do I pick crusher with 100% of my vouchers. In that time, I haven't gotten any watcher trophies from the mobs I've killed, or if I did, I missed them, so this doesn't really affect me too much. I'd say that this brings it too close into being useless, but I also don't know how it could strike a balance without being nullified entirely.

Maybe it could fill a similar niche to the blood-drunk miner's trophy, by suppressing melee attacks (or weakening them) but not their special attacks? That would mean that miners still have to be careful during fights in case the ash drake pulls a triple-swoop, but also awarding aggressiveness by giving them more hits if they act recklessly. It'd be an interesting tradeoff that doesn't force you into a specific style, like, say, the hierophant trophy does.

**Comment by Buggy123** [comment]
Ironically, I'm in the same position: I _do not_ use the crusher to fight, but I do pick it every round. Why? Its 10-20% faster than a unupgraded KA and it comes with a free webbing. I don't fight fauna at first anyway, I mine for resources and healing items, grab dual plasmas, and then kill a drake(or bubble) for armor instead of upgrading my explorer suit

>Maybe it could fill a similar niche to the blood-drunk miner's trophy, by suppressing melee attacks (or weakening them) but not their special attacks?

This is a really good idea, actually. Would make the crusher much more interesting and worthwhile, ignoring the horrendous drop rates.

**Comment by ExcessiveUseOfCobblestone** [comment]
The crusher being difficult to use should have 0 input regarding an upgrade that allows you to lol nope boss attacks come on...

**Comment by Buggy123** [comment]
Parts of the whole invariably affect the whole. Regardless of what they were intended to do, watcher trophies constitute a major use-case for the crusher, and nerfing them is nerfing that use case and thus nerfing one aspect of the crusher as a whole.

**Comment by ChangelingRain** [comment]
The result absolutely matters. being able to cheese bosses using the 'challenge' weapon thanks to an overtuned upgrade is absurd.

**Comment by Buggy123** [comment]
And yet, you are still cutting the one thread by which this weapon (only just!) clings to usefulness,

**Comment by Xhuis** [comment]
You hush the crusher is the best weapon, look at this chart
`Kinetic Crusher >>>>>>>>>>>>>>>>>> all the other lame shit`
it's obvious. You can't deny the facts, buggy.

**Comment by ChangelingRain** [comment]
This should not be the source of the crusher's usefulness, even if removing it makes the crusher "unusable". Which it won't.

**Comment by Buggy123** [comment]
I disagree, its already unusable, but _theoretically_ usable with a droprate buff. This is just cementing it as unusuable.

**Comment by ChangelingRain** [comment]
Your inability to use the crusher properly, without a specific trophy, doesn't mean it's unusable by everyone if that trophy is nerfed 37.5%.

**Comment by Buggy123** [comment]
I've already stated why the crusher is bad: It's not the _inability_ to kill shit with it. I can kill shit with it, alright, anyone can if they really put their mind to it. The problem is it is _factually inferior to the alternatives_ **UNLESS** it gets trophies, and even _then_ it is still inferior in practice due to the time it takes to farm.

Yes, I could kill a fucking megafauna by stabbing it for 50 damage per hit (80 if i'm really good). OR, i could get dual plasma cutters, which do 54 damage at range, fire at about the same rate, and are also astounding good mining tools and can fit in a backpack.

**Comment by Buggy123** [comment]
Quick demonstration I put together, showing the absolute minimum time to kill a ash drake under _ideal_ circumstances. I.E. with their AI frozen. [Watch it here.](https://www.youtube.com/watch?v=A9qcKuCGBek)

The results:

1: Kinetic Crusher with 100% backstabs - 42 seconds
2: Dual plasmas - 50 seconds
3: Kinetic Crusher - 58 seconds
4: Kinetic Accelerator with 3x cooldown - 61 seconds

So, yes, there you go. If you can hit a mega with 100% consistency and always land backstabs without a moment of delay, and without getting murdered by the 40 armor-bypassing melee damage, the kinetic crusher is, infact, a moderately better weapon. If you can only consistently hit normal stabs, it is in close second for _worst_ weapon.

In normal circumstances, the time taken with plasma cutters tends to be around 1.5-2x this, depending on swoop RNG. See example [#1](https://www.youtube.com/watch?v=whGmMv2FIZQ) (faster but I fucked it up and had to burn a pen), and [#2](https://www.youtube.com/watch?v=2tH9vAe6D4c) (slower and slightly worse aim).

**Comment by Xhuis** [comment]
I don't see the issue here with crushers supposedly being terrible. They are meant to be difficult to use well because they rely on good positioning and precise timing. I used crusher even before I even knew trophies were a thing, and this change isn't going to ruin the crusher because only a tiny few people will ever get this trophy anyway.

**Comment by Buggy123** [comment]
The risk/reward is way off. Kinetic crushers are worse off than plasmas because it is much easier to consistently land ranged shots than it is to consistently land ranged shots _and_ melee hits.

Even if you manage both of those very well, it is _still_ worse unless you also manage to carefully manuever so that you very consistently hit from the _back_ of the mega, which is even harder.

So essentially you have this _astoundly_ difficult to use weapon that only actually rewards skill if you are _incredibly_ skilled at using it, above and beyond simply being adequate with it. Otherwise it is factually worse than the easier-to-use alternatives.

Trophies would be a good way to balance this out, because they provide substantial buffs if you put in the effort to get them. That sort of progressive build-up and effort-rewarding mechanic is a very good system.

Except... if you're good enough to use a crusher decently you can probably use plasmas decently as well, and the trophy drop late is _so low_, that by the time you get decent trophies, you could've killed a lot/all of the megas with plasmas.

In 9/10 cases research gets you plasmas by the 7-8 minute mark or earlier. So you can mine for 8 minutes, grab plasmas and get back on lavaland by the 10 minute mark. If a mega takes, at most, ~2 minutes to kill, and lets say 2 minutes to find the next mega and prepare a arena (cutters mine _very_ fast, essentially at running speed.), you'd have taken down 2 megas and just started a third by the 20 minute mark.

So if it takes _twenty minutes_ to find even a watcher trophy, _why the would you even bother with the crusher_. The only, _only_ reason you'd take it is if you're so _mind-bogglingly_ good at using it, that it's faster to kill megas with it instead of plasmas without trophies. And I'm willing to bet that the list of people who can do that is rather short.

**Comment by Xhuis** [comment]
I don't *care* that plasmas are better. It's not *meant* to be the best weapon. It is a bulky challenge weapon that even includes that point in its description. It's perfectly fine to be flawed and difficult to use because that's how it's designed.

**Comment by Buggy123** [comment]
Okay, fine, but: _why are we making it harder_? It's already enough of a challenge, isn't it? It has all the makings of a good weapon that is also a challenge weapon, a weapon that is challenging but that also has that tantalizing hint of sheer power that makes people want to try it. But if you _remove_ that tantalizing hint, its just a flat out worse weapon. Nothing alluring to it, aside from maybe the slightly unique mechanic it has.

And if people who want a challenge are okay if its just a arbitrary handicap instead of something interesting and potentially rewarding, then why don't they just take the survival knife they start with and _stab the megas to death with that?_

**Comment by Xhuis** [comment]
But they're *not* making it harder. The watcher trophy is already very rare. This is making a strategy that turns the challenge weapon into the superior choice into something that buffs the challenge weapon without removing the difficulty aspect. Speaking as someone who uses the crusher, I like it because it's challenging but *rewarding* to use. Bringing down a beastie with a crusher is infinitely more satisfying than the dual-cutter strategy you outlined. It's not an exercise in tedium like normal weapons are, because the fight would take ages with say, a knife, but it's much more involved and just as effective if used well.

**Comment by YogsMcree** [comment]
Crusher pack has many things wrong with it. Namely it has no advanced scanner. However the weapon itself requires you to be constantly in melee range with creatures that can 3hko you regularly. I dont think this change is the right direction for the crusher. Its unwieldy (takes your backpack slot), requires both hands (meaning no healing with it on) and again puts you directly into harms way. If it were as powerful as you suggest, it would be used more often.

**Comment by Xhuis** [comment]
Ok, I give up.

**Comment by Spaceinaba** [comment]
sorry eggs your first mistake was responding to buggy

**Comment by Buggy123** [comment]
He's right you know.

**Comment by Kromgar** [comment]
Fuck it i'm gonna try killing drake and bubblegum with this now because you wont stop bitching about it buggy once the PR for Crusher kill medals gets merged i'm doing it

**Comment by YogsMcree** [comment]
Kromgar comes back 3 weeks later, gibbed 218 times and killed both once, and says "See i told you so"

**Comment by Kromgar** [comment]
@YogsMcree atleast i can try to git gud

**Comment by ExcessiveUseOfCobblestone** [comment]
There's really no point in arguing with someone who believes the weapon itself is flawed and that the only way to use it is to have an upgrade which allows you to hit the mob unfettered.

They lost the removal pr I don't see why they just suck it up and stop buying the weapon instead of crying on literally every thread surrounding the one object.

**Comment by Buggy123** [comment]
Like I said, only reason I buy it is that 10% efficiency boost compared to KAs, if it wasn't for that I wouldn't use the thing. I don't use it for combat.

I'm being so persistent here because I think it would be nice to be _able_ to use it, and I hate the idea of something just sitting around in a unusable state. Either _fix it_, or _put it out of its misery_.

**Comment by ExcessiveUseOfCobblestone** [comment]
It is usable, just not for you :^)

**Comment by Xhuis** [comment]
***It is not unusable.**"

**Comment by Buggy123** [comment]
Yes, it is? In a practical "why would I ever use this in gameplay" as opposed to "this is too terrible to ever pick up" sense.

**Comment by Xhuis** [comment]
I've already said why I use it in gameplay. I'm not going to endlessly repeat myself.

**Comment by ExcessiveUseOfCobblestone** [comment]
Whether _you_ use it or not isn't the sole metric of whether to keep it in the game, you have to come to terms with this miningpointe.

**Comment by Xhuis** [comment]
I take it you've never heard of the Calamity Ring.

**Comment by Buggy123** [comment]
>The rings has no real purpose, and is simply used to make the game harder.

Ergo, it is only used by people who want a challenge. Speedrunners, people who don't want a challenge, etc have absolutely no reason to use it.

**Comment by Xhuis** [comment]
But people still *want* it and use it for that purpose, so we shouldn't remove it just because other people don't, y'know? :v

**Comment by Buggy123** [comment]
Okay, fine, the "remove crusher" PR got closed anyway. But lets not restrict it even _more_ to just people who want a challenge. Items which have multiple uses are better than items with exactly _one_ use.

**Comment by ChangelingRain** [comment]
cheesing bosses with a challenge weapon is not okay

**Comment by Buggy123** [comment]
I wouldn't call it cheesing.

**Comment by ChangelingRain** [comment]
if the boss can't interact with you in any meaningful way while you murder it, then it's cheesing. what else would you call that, mozzarellaing?

**Comment by KorPhaeron** [comment]
We have players of wildly varying skill levels, the crusher was added by a player who wanted a tough but viable challenge mode after he had killed all the bosses, not as competition for the KA

**Comment by Buggy123** [comment]
Damnit.

**Pull request merged**
