### PR TITLE
Restrict AI floor bolt external manipulation

### PR DESCRIPTION
**Pull request by Wayland-Smithy**
## About The Pull Request

My delayed reaction to #68451

**When an AI is alive, on main power, and not SSD its bolts cannot be raised or lowered externally thus returning some small amount of autonomy to everyone's favorite brain in a box.** 

I tested to be sure this change does not interfere with (de)construction or other tool actions besides their "must be anchored" requirements. Should maintainers wish I can adjust the check to allow external lowering, but not raising, of the bolts anytime to satisfy those scenarios.

I decided to include "is on backup power (incapacitated)" in the check as a middle ground so when moving an AI from a bombed sat or the like anyone who is now used to being able to wrench for a rescue is not caught off guard since AI gets a harsh penalty for moving bolts on backup power (most likely overlooked in the original PR). This also means if you really want to move an active AI Core against its will you still have a path forward aside from _convincing_ the AI to raise them voluntarily.

## Why It's Good For The Game

IMO this sort of check should have been included in the original changes, or at least made to post the anchor status message to the AI's chat rather than a balloon they are likely to miss. An incapacitated AI is much more likely to be watching their core.

In the grand scheme this changes very little for anyone out to get an AI since they will most likely just card or smash it to death anyway. It's mostly just good for a little silicon piece of mind.

## Changelog
:cl:
balance: When an AI is alive, on main power, and not SSD its bolts cannot be raised or lowered externally.
/:cl:

### CODE REVIEW

**Comment by moocowswag** [comment]
No, please no

as an engie borg that is defending my ai I cant just wait for them to look around their ui to unwrench themselves, this is a really big nerf to malf ai/ai who cant have their attention everywhere while their own borgs guard them.

**Comment by ATH1909** [comment]
> No, please no
> 
> as an engie borg that is defending my ai I cant just wait for them to look around their ui to unwrench themselves, this is a really big nerf to malf ai/ai who cant have their attention everywhere while their own borgs guard them.

You can ask them to unbolt themselves ahead of time, no?

> Having to cut off my own ai's power just to quickly unwrench them to move them away from a predictable launch pad + card attempt is going to piss of my ai.
> 
> At the very least let borgs that are syncd to the ai continue being allowed to toggle their bolts for them.

I'd be down for this.

**Comment by Wayland-Smithy** [comment]
I could make borgs bypass, but like you point out they can already just turn off equipment power at the APC which is not a big deal to me since you are probably wanting to leave the area anyway and if not can turn it back on.

> let borgs that are syncd to the ai continue being allowed to toggle their bolts for them.

I will look into this, but just don't want to get too much spaget in this proc.

I prefer the skill issue to be on the side of the equation that is safer. If an AI does not even know how to toggle bolts it is in far more danger from bad actors than good ones taking advantage of that fact.

**Comment by zxaber** [comment]
At the risk of suggesting more screen clutter, the AI's bolts *could* be given a hud button.

**Comment by nikothedude** [comment]
isnt there a verb for it

**Comment by zxaber** [comment]
Yeah but verbs are the worst form of UI.

We could probably swap the unbolt and call shuttle functions; unbolting is more time-sensitive and makes sense to have a hud button. Calling the shuttle is seldom and rarely needs to be done quick.

**Pull request merged**
