### PR TITLE
Allows populating new vv'd lists

### PR DESCRIPTION
**Pull request by LemonInTheDark**
You get an alert, and can continue to enter variables until you hit cancel. Not sure if this is good ux or not, yell at me if not
## Why It's Good For The Game

Fikou asked me for it and that guy's pretty cool. Also it's annoying to not be able to feed lists into procs

## Changelog
:cl:
admin: You can now optionally populate new lists created via vv. hit cancel to stop filling them up
/:cl:

### CODE REVIEW

**Comment by optimumtact** [comment]
this really could benefit from a js panel intermediary that lets you add options and has an explicit save button tbh, rather than reepated alerts.

but all the VV variable inputs could use better interfaces I suppose.

**Comment by optimumtact** [comment]
I guess like, vving the list while ti's created or something, then feed it to the original thing

**Comment by LemonInTheDark** [comment]
> this really could benefit from a js panel intermediary that lets you add options and has an explicit save button tbh, rather than reepated alerts.
> 
> but all the VV variable inputs could use better interfaces I suppose.

Yeah I'm not entirely happy with the ux. 

> I guess like, vving the list while ti's created or something, then feed it to the original thing

This would be way better. I'm not sure how I'd hook into the list vv being closed tho

**Comment by san7890** [comment]
i think ultimately figuring out tgui/js endpoints into VV would be quite involved or require some tampering/hooks into the whole backend- and would be kino if it could be resolved in one PR that specifically targets this

i'm not really happy with the UX in the present state since i think alert-spam sucks a bit....... but it's better than absolutely nothing, which is where we are now.

**Pull request merged**
