### PR TITLE
new icons for the forcefield projector and the atmos projector

### PR DESCRIPTION
**Pull request by Tlaltecuhtli**
:cl:
sprites: new icon for the atmos projector and forcefield projector
/:cl:
new icons

### CODE REVIEW

**Comment by Time-Green** [comment]
Icondiff is dead, you got any pictures?

**Comment by evsey9** [comment]
thats a lotta commits

**Comment by MrDoomBringer** [comment]
recorded some gifs, first one is atmos, second is forcefield
### https://i.imgur.com/Om21swU.gifv
### https://i.imgur.com/2O3sDDj.gifv


- they dont really look like that much of an improvement, mechanically speaking
- it isnt super intuitive that one is an atmos projector and the other is a forcefield projector
- they dont loop that well
- theres no changelog
- you didn't post images (and icondiffbot, even if it was alive rn, doesn't output GIFs so thats still on you)
- also
image


for these reasons i'm voting your pr off my island

**Comment by duncathan** [comment]
what are you talking about icondiffbot has the gifs and it works fine

anyway i like the look of the atmos one but as mentioned the loop isn't great
the forcefield one seems kinda weird tho, constantly generating a field or what?

**Comment by MrDoomBringer** [comment]
@duncathan what? I'm talking about how icondiffbot doesn't show animated GIFs, just the individual frames, so its up to the OP to record and post a gif or video

**Comment by Time-Green** [comment]
Uhh, I cant see the icondiffbot

**Comment by MrDoomBringer** [comment]
@Time-Green its dead rn. dunc and i are referring to its regular behavior

**Comment by duncathan** [comment]
screenshot_2018-09-25-21-52-55
obvs i can't show it in a screenshot but it literally shows the gifs

**Comment by MrDoomBringer** [comment]
@duncathan oh shit huh
ive never noticed that i might be tarded
_shrugs_

**Pull request merged**
