### PR TITLE
Increase the number of shots for laser rifles, energy guns and hellfire lasers

### PR DESCRIPTION
**Pull request by Spookuni**
## About The Pull Request

Increases the shot count of Laser rifles (from 14 to 16) Energy guns on Kill (from 10 to 12) and Hellfire lasers(from 8 to 10)

## Why It's Good For The Game

The change from weight class normal to weight class bulky for most ranged weapons largely broke the old and rather silly meta of carrying 4+ laser / energy guns around to handle threats, but it had the unfortunate side effect of dramatically increasing the relative value of reloadable ballistics (where before you would swap out to a fresh energy weapon) and later with the nerfs to shotguns, decreasing the viability of the roundstart armoury for dealing with deadly midrounds like space dragons.

Hopefully boosting up the total shot count available to energy weapons will help their logistical viability compared to ballistics that can be reloaded mid combat, and boost the ability of the station to deal with large external threats without relying on cargo sourced ballistics. At the same time not shifting the lethality of energy weapons in an engagement lasting the same duration of time.

## Changelog
:cl:
balance: Nanotrasen has released experimental new laser lenses for laser rifles, energy guns, and illegal hellfire modkits, increasing the number of shots they can fire from full charge by roughly 20%. 
/:cl:

### CODE REVIEW

**Comment by Spookuni** [comment]
I forgot to change the PR name from my branch name. Fuck.

**Comment by stylemistake** [comment]
Sounds reasonable to me.

**Comment by ExcessiveUseOfCobblestone** [comment]
@PolishUser thoughts

**Comment by PolishUser** [comment]
@ExcessiveUseOfCobblestone It seems a little bit of an overkill, lasers may still give some deadly wounds and security in the current state is just too strong. A well coordinated sec force can easily neutralize most of the possible threats within first 10-20 minutes.

**Comment by ExcessiveUseOfCobblestone** [comment]
I was thinking similar, would you suggest a change to the current amount or keep it as is

**Comment by Sparkezel** [comment]
doubling is a little too much, something around 40-50% for most guns should be fine though

**Comment by Krysonism** [comment]
Ranged weapons are already too dominant in my opinion.

I know maintainers have expressed a desire to see more combat with improvised and environmental weapons, supercharging the round start arsenal is not the way to go.

**Comment by PolishUser** [comment]
> 
> 
> I was thinking similar, would you suggest a change to the current amount or keep it as is

I'd say keep it as it is or increase it _slightly_.

**Comment by Spookuni** [comment]
Happy to shift numbers down a bit if required, does slightly mean in the region of 15-25% more? or even lower than that?

**Comment by PolishUser** [comment]
> 
> 
> Happy to shift numbers down a bit if required, does slightly mean in the region of 15-25% more? or even lower than that?

You may increase it by 2 each maximum or just close this PR.

**Comment by stylemistake** [comment]
So basically 25%.

**Comment by Spookuni** [comment]
Numbers have been tuned down to 2 more shots per gun, for a total change of roughly 15-25% for each gun.

**Comment by ExcessiveUseOfCobblestone** [comment]
these numbers should really be expressions (DEFINE/desired number of shots), when I see 83 im not going "oh thats 7 shots from a gun" im going "wtf"

**Comment by optimumtact** [comment]
this is my idea

**Comment by KathrinBailey** [comment]
> I know maintainers have expressed a desire to see more combat with improvised and environmental weapons, supercharging the round start arsenal is not the way to go.

Unless someone reworks melee combat to be less janky and godawful (tile-based rather than sprite-based, which makes small sprites a giant mechanical advantage) I don't think you're ever going to see players voluntarily opting for anything other than guns. Melee combat is really boring, it feels like playing Battleship with chess pieces. _What tile will this lagged-up bald grey entity teleport into next?_

But anyway more on topic, doesn't this indirectly buff the mini egun too? I suppose with 9mm and 10mm doing 30/40 brute respectively, it isn't that much of a big deal, but still, it's a (probably) unintended buff.

**Comment by Spookuni** [comment]
> this is my idea

He said I wouldn't do it, but I did.

**Pull request merged**
