### PR TITLE
Prevents blinded people from using camera consoles perfectly fine

### PR DESCRIPTION
**Pull request by MrMelbert**
## About The Pull Request

Adds a machine interaction flag, `INTERACT_MACHINE_REQUIRES_SIGHT`, for machines that cannot or should not be used with the operator being blind. This PR puts it on camera consoles and advanced camera consoles.

## Why It's Good For The Game

- Blinded people should not be able to use camera consoles to see completely fine
- Blinded people could previously activate advanced camera consoles, but it would kick them out on the next life tick. it's not intended that they use them anyways, so this just prevents them from activating it in the first place.

## Changelog
:cl: Melbert
tweak: Blinded people can no longer use camera consoles
fix: Blinded people can no longer activate all types of advanced camera consoles, including navigation consoles (They were already not intended to be able to use them)
code: adds a machine interaction flag for machines that require the user not be blind to use
/:cl:

### CODE REVIEW

**Comment by Fikou** [comment]
the camera consoles are in space age dynamic braille screens

**Comment by MrMelbert** [comment]
image
this is some damn good braille

**Comment by necromanceranne** [comment]
Lifelike textures ;_;

**Review by nemvar — CHANGES_REQUESTED** [review]
Please also make the camera bug require sight.

**Comment by MrMelbert** [comment]
>Please also make the camera bug require sight.

as far as I can tell from testing, the camera bug already doesn't actually let you view any cameras if you're blind

**Pull request merged**
