### PR TITLE
Xray range tweak

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
Now uses kill_count instead of range. This should be functionally identical, but it will let reflector structures refresh the xray lifespan

### CODE REVIEW

**Comment by CosmicScientist** [comment]
Refresh the lifespan? Does that mean you can have an infinite loop for X-rays that you can keep adding?

**Comment by KorPhaeron** [comment]
Yeah

**Comment by as334** [comment]
:+1:

**Comment by CosmicScientist** [comment]
So that won't cause lag issues or death machines that people will try to build in escape?

**Comment by KorPhaeron** [comment]
It wont cause lag.

I'm hoping it does cause death machines.

**Comment by CosmicScientist** [comment]
Well at least you're honest and at least it's for fun. :+1:

**Comment by Dorsisdwarf** [comment]
@KorPhaeron 
Is this ready?

**Comment by KorPhaeron** [comment]
Yeah

**Pull request merged**
