### PR TITLE
Standardizes the names for the default Chameleon Clothing.

### LINKED ISSUE #19392: Chameleon Suit default naming
The names of the default chameleon backpack and headset should be named Backpack and Station Headset instead of chameleon backpack and headset respectively they look the EXACT same as those items and it would fix the inconsistency of the rest of the items default names not giving themselves away.

### PR DESCRIPTION
**Pull request by Firecage**
The default types of the rest of the Chameleon clothing now has normal names as well.

chameleon backpack > backpack
chameleon headset > radio headset
chameleon PDA > PDA

Fixes #19392

### CODE REVIEW

**Comment by XDTM** [comment]
got me valided once, 10/10

**Comment by coiax** [comment]
@Firecage unless a "backpack" actually exists, I'd suggest changing it to "grey backpack".

**Comment by Firecage** [comment]
@coiax The default grey backpack is actually named backpack. Same with the default grey satchel being named satchel.

**Comment by coiax** [comment]
I stand corrected.

**Pull request merged**
