### PR TITLE
Fixes a bug with Branca Menta and moves Fernet to contraband

### LINKED ISSUE #38565: Fernet is deadly
This is apparently intended, so I'm just pointing out how absurd it is

Its effect are so extreme that drinking an entire glass is almost guaranteed to starve you and then kill you with toxloss. 
This is also the case for most recipes that contain it, which are usually just as strong as drinking it straight (but with a fraction of the boozepwr) despite the fact it would realistically be heavily diluted

### PR DESCRIPTION
**Pull request by Mickyan**
:cl: Mickyan
fix: Branca Menta won't make you starve and then kill you
tweak: Fernet has been moved to contraband
/:cl:

Closes #38565
See issue above for more detailed discussion & context.

Branca Menta was not supposed to lower satiety according to the original creator

A single glass of Fernet is enough to starve you(tested at about 350 nutriment, 400 being the roundstart max) and then kill you through toxloss, making it the deadliest drink the bartender has with the exception of Bacchus Blessing. 
The original PR was misleading and gave the impression that this was meant to be a weaker, no risk alternative to lipolicide while it's the opposite.
This is ridiculous, makes no sense and has no business being in the bartender's standard selection where it can easily be mistaken for a regular drink by anyone who didn't read the code for it. 
If a bartender wants to risk poisoning people they may do so willfully by going the extra mile for it.

### CODE REVIEW

**Comment by DaxDupont** [comment]
Please don't list balance changes as fixes

**Comment by davethwave** [comment]
this doesn't fix anything... if anything you should lower the nutriment it removes rather than removing the drink at all.

**Comment by davethwave** [comment]
Moving it to contraband is not fixing the situation...

**Comment by ExcessiveUseOfCobblestone** [comment]
The branca menta is a fix though, original creator supposedly didn't intend for it to have the nutrient removing effect even though they coded it in (???)

Please fix fernet properly by making it match original PR description rather than just moving it to contra.

**Comment by Mickyan** [comment]
That would indeed be a balance change and this isn't worth wasting my points on since not even the creator cared enough to actually reply when we were discussing about it. 
What I do care about is people accidentally dying because someone thought putting deadly toxins into the booze o mat and then disguising it as a drink was acceptable.

If someone wants to make an alternative PR that makes fernet not stupid I'll personally close this.

**Comment by ExcessiveUseOfCobblestone** [comment]
Fixes can have balance implications, that doesn't make them not a fix.

**Comment by ExcessiveUseOfCobblestone** [comment]
Then you should atomize the balance (fernet) and the fix (bm)

**Comment by YakumoChen** [comment]
It only kills you if you actually drink too much though??? It's not like it's hard to spot in a drink, and it doesn't kill you unless you chug the shit.

**Pull request merged**
