### PR TITLE
Removes horribly overt copyrighted nonsense that made the game not compile in 509

### LINKED ISSUE #16897: /obj/item/toy/talking/skeleton/proc/skelly_say() requires byond 510 beta to function
#16792 
@coiax 

**Don't use features not in the stable release**

### PR DESCRIPTION
**Pull request by Incoming5643**
Removes the blatantly copyrighted sans and papyrus action figures and the blatantly copyrighted sounds attached to them.

As a bonus this also makes the project work in the stable 509 build again. Fixes #16897

@ChangelingRain I hate to be the fun police but that should have never gotten merged outside of april fools day.

:cl: Incoming5643
rscdel: Removed the horrible meme skeletons, please don't sue us.
/:cl:

### CODE REVIEW

**Comment by Iamgoofball** [comment]
jesus fucking christ why were these merged

**Comment by Iamgoofball** [comment]
WHEN were these merged

**Comment by Incoming5643** [comment]
https://github.com/tgstation/-tg-station/pulse

**Comment by Bawhoppen** [comment]
this is PR of the week for sure

**Comment by Incoming5643** [comment]
D O N ' T  M E R G E  S H I T P O S T  P R ' S

**Comment by Cheridan** [comment]
stop breaking 509 compat plz

**Comment by coiax** [comment]
REEEEEEEEEEEEEEEEEEEEEEEEEE

**Comment by PKPenguin321** [comment]
rip

**Comment by coiax** [comment]
NICE SPEED MERGE ASSHOLES

**Comment by PKPenguin321** [comment]
it made the game not compile

**Comment by Incoming5643** [comment]
W E  
A L R E A D Y 
H A V E 
A N
U N D E R T A L E 
R E F E R E N C E
.
I
A D M I T
T H E 
E M U L A T E D
S P E E C H 
W A S
C O O L
B U T
M Y 
G O D
I T
W A S
J U S T
S O 
F L A G R E N T

**Comment by coiax** [comment]
THE SPEECH WAS MADE BY HAND USING tSAMPLES, THE SPRITES WERE ALSO MADE BY HAND (which is why they are so shit).

AND IF THIS BROKE THE BUILD THEN WHY DID IT PASS THE FUCKING JARVIS

**Comment by Incoming5643** [comment]
because we're still supporting 509 (stable) but jarvis tests for (510) beta and you used something that only works in 510.

**Comment by Incoming5643** [comment]
For what it's worth this was/is running on live servers so it's not like people didn't/aren't experiencing your content.

**Comment by coiax** [comment]
experiencing my MINOR AND TINY CONTENT which adds TOYS THAT MAKE SOUNDS, which was a replacement suggestion for making MAGICAL SKELETONS make noises based on the way they talk which INSPIRED THE PR IN THE FIRST PLACE

**Comment by optimumtact** [comment]
@Incoming5643 on what basis do you say this is incompatible with 509?

**Comment by RemieRichards** [comment]
@optimumtact probably the regex datum, it's 510 iirc.

**Comment by optimumtact** [comment]
But there was a 509 shim that worked if you had bygex installed, which you needed for some unrelated crap anyway

**Comment by Incoming5643** [comment]
it was the use of `.next` that didn't work in 509, or at least the first thing that didn't work.

I didn't make this pull because it broken 509 I made this pull because it was the worst kind of reference:

1. We already have a more subtle reference for undertale (and indeed for sans and papyrus!) in the game
2. It was really blatantly a reference without any subtly, integration with the setting, or reason for existing in space station 13 outside "It's a reference!".
3. It used sounds that were indistinguishable from copyrighted sounds, a lot of quotes directly ripped from the game, and was just generally just so on the nose that it hurt.

The fact that it broke 509 support was just icing, I would have made this pull all the same just on the basis of the reference. I didn't ask for the quick merge either, it happened of Cheridan's own violation.

**Comment by duncathan** [comment]
or you know you could've actually fixed the problem and made next work
this was a terrible pull; stop being stupid incoming

**Comment by Iamgoofball** [comment]
@duncathan Let's be honest here the undertale crap is retarded

**Comment by duncathan** [comment]
then make the pull be about that. saying he's reverting it because it's not compatible with 509 means he's reverting it because of the code I wrote for it (the regex) which is a nice big "fuck you, dunc." I don't really appreciate that.

**Comment by Iamgoofball** [comment]
yeah, it should of been reverted for the meme reason and not the le compatability meme

**Comment by Incoming5643** [comment]
Read the title again 

**Removes horribly overt copyrighted nonsense** that made the game not compile in 509 

That WAS my primary reason, as I've already said

**Comment by duncathan** [comment]
You know as well as I do that it's because of the 509 incompatibility that the revert got speed merged. The fact is that you used my code (which there was nothing wrong with besides a small bug which could've been fixed) as an excuse to remove a feature you disliked. I don't even care about the feature; I'm just pissed that you got my code reverted on unfair pretenses.

**Comment by Incoming5643** [comment]
I didn't ask for a speed merge and I didn't expect a speed merge. It just sorta happened man. I'm pretty sure the revert would have gone through pretty quickly even if I hadn't mentioned the incompatibility.

The only reason I even mentioned it was 509 incompatible was because I noticed this while I was coding organ stuff. I made https://github.com/tgstation/-tg-station/issues/16897 before I even realized what that code actually was being used for. I had to mention it to show why it closed that issue.

Not gonna lie, yes that title was made in a bit of "I can't believe this nonsense got merged" style harrumph, but it was never my intention to use that as "the reason" it should be reverted even when I wrote it.

**Pull request merged**
