### PR TITLE
Add's stat feedback to vending machines

### PR DESCRIPTION
**Pull request by Iamgoofball**
time to see what autodrobe costumes literally never get used so i can purge them

### CODE REVIEW

**Comment by Cyberboss** [comment]
Or we could, you know

### NOT REMOVE CONTENT!

**Comment by Iamgoofball** [comment]
or we could, you know
### NOT WASTE RSC SPACE ON STUFF THAT GETS USED NEVER!

**Comment by FantasticFwoosh** [comment]
Don't add content that is going to get stale after a month then cyberboss, im supporting goof on this one.

**Comment by Iamgoofball** [comment]
yeah like the robbie rotten costume got added because this one guy played robbie rotten for a month and then NEVER TOUCHED IT AGAIN

**Comment by FantasticFwoosh** [comment]
I mean deleting the content doesn't mean its gone forever if you actually back up what you were going to delete on your hard-drive.

**Comment by Cyberboss** [comment]
> NOT WASTE RSC SPACE

80% of RSC space is sounds

**Comment by Militaires** [comment]
hey goof i added a sailor costume but i didnt increase the autodrobe can size so there's a sailor costume that is always 0 amount on every round fix that bug too please

**Comment by Iamgoofball** [comment]
@Militaires now is this a proper sailor's outfit or is this anime weeb shit

**Comment by FantasticFwoosh** [comment]
@Iamgoofball does have bias versus anime stuff, but this logging tool will help everybody in a passive way in knowing the popularity of a purely cosmetic item.

**Comment by KorPhaeron** [comment]
Time to vend the entire machine every round golfball will not divide us

**Comment by ShadowDeath6** [comment]
This is actually pretty interesting information to know, memes aside.

**Comment by Screemonster** [comment]
"waste RSC space" when the entirety of uniform.dmi is only 217kb

I mean it's a mildly interesting thing to know I guess but seriously dude

**Comment by kevinz000** [comment]
Between fwoosh and goofball atleast one of them can't code their dumb memes.

**Comment by Bawhoppen** [comment]
You're supposed to use [s] on the April fool's prs

**Comment by ExcessiveUseOfCobblestone** [comment]
Real talk I like this PR for the exact opposite reason:

To see what people like so I can make more meme costumes :^)

**Comment by FantasticFwoosh** [comment]
I can actually support that sentiment @ExcessiveUseOfCobblestone

**Comment by Iamgoofball** [comment]
see

now that's perfectly okay

it's using stat tracking to add more of what people want to actively use

**Comment by PKPenguin321** [comment]
kor's post kind of nullifies this

**Comment by optimumtact** [comment]
kor can post memes all she wants, she will not divide the maintainers

**Comment by Cyberboss** [comment]
Dammit, I assumed kor's gender!

**Comment by ShadowDeath6** [comment]
hot lesbian maintainer action

**Comment by KorPhaeron** [comment]
http://i.imgur.com/nw1vw.png

**Comment by Iamgoofball** [comment]
@pranked

**Comment by ExcessiveUseOfCobblestone** [comment]
yeeeee haw1111

**Comment by pranked** [comment]
@Iamgoofball y doe

**Comment by Iamgoofball** [comment]
This is all machines

**Comment by optimumtact** [comment]
everyone act normal we have visitors

**Comment by Iamgoofball** [comment]
my bad @pranked i was shitposting from my phone and hit the wrong button

**Comment by Bawhoppen** [comment]
You keep pinging some poor random guy with the username pranked

**Comment by pranked** [comment]
That's ok I love shitposting and @dank memes :)

**Comment by ShadowDeath6** [comment]
I can't imagine what people must think when they get accidentally pinged by some random shit in here and look at this repo

**Comment by Bawhoppen** [comment]
So the random guy goof pinged now pinged some other random guy.

It's like inception.

**Pull request merged**
