### PR TITLE
Fentanyl Nerf

### PR DESCRIPTION
**Pull request by N9neball**
## About The Pull Request

Makes the recipe for Fentanyl more complex and reduces the overall brain damage.

## Why It's Good For The Game

Makes an overpowered chem less overpowered

## Changelog
:cl:
tweak: Changed recipe for Fentanyl from just heated space drugs to space drugs, cyanide, ammonia, and oxygen heated together
balance: Reduced brain damage gain speed, as well as overall brain damage inflicted
/:cl:

### CODE REVIEW

**Comment by Kierany9** [comment]
You do realize the lower the metaoblization rate, the longer the chem lasts in you and therefore the deadlier it is and the less you need of it, right?

**Comment by wesoda25** [comment]
I didn't know fentanyl was OP at all. And I have used it in a lot of chem mixes. I dunno about this one hoss. The recipe change is warranted though

**Comment by Sisyphusrollson** [comment]
> You do realize the lower the metabolization rate, the longer the chem lasts in you and therefore the deadlier it is and the less you need of it, right?

Hmm, perhaps I did overcompensate for the damage nerf. Adjusted.

**Comment by Kierany9** [comment]
Now this fentanyl is hardly a better brain killer than impedrezene (which is uncapped damage with a small chance to not do any but is twice as fast metabolizing), hardly a better sleep than morphine (which isn't a toxin but is slower), a worse sleep compared to chloral (which is faster but metabolizes ridiculously fast) and a worse toxin compared to cyanide and the recipe's harder than all four of these. I'm not sure whether to say this is a good change because it's an all-purpose chem weaker than more specialist chemicals or bad because this now makes an already meh mix ingredient bad.

the power of brain damage is ridiculously out of whack because of traumas though, nobody went through the chems to fix them. a single syringe of crank will begin to deal 5 brain damage per tick because addictions are garbage and there's nothing you can do to stop it.

**Comment by anconfuzedrock** [comment]
Fentanyl is like if a guy tried to breed chloral and cyanide only for the baby to come out with downs. fentanyl is less lethal than most drugs, 15u of pure liquid plasma is lethal, but fentanyl can never kill, which even chloral can. if you suspect fentanyl then you're already ok, since you can sprint to a coffee machine way before it can kick in. even so, you actually have to be finished off for fentanyl to fentakill, since the brain damage can't reach lethal levels.

**Comment by Shadowflame909** [comment]
Yeah this isn't overpowered at all and seems like its in fact in need of a buff with this new change


What drove you to decide to want to nerf it?

**Comment by uBadush** [comment]
unneeded nerf

**Comment by Sisyphusrollson** [comment]
You can give people 10 different brain traumas in seconds with 15u. It’s also ridiculously easy to produce as it stands. Most times I use it the victim is knocked unconscious within 5 seconds, or at the very least incapacitated. Stack it with some other brain damaging chem and you have a hilariously effective deathmix.

**Comment by wesoda25** [comment]
> You can give people 10 different brain traumas in seconds with 15u. It’s also ridiculously easy to produce as it stands. Most times I use it the victim is knocked unconscious within 5 seconds, or at the very least incapacitated. Stack it with some other brain damaging chem and you have a hilariously effective deathmix.

If anything I think braindamage in general should be nerfed, as kierany said.

**Comment by Shardj** [comment]
> > You can give people 10 different brain traumas in seconds with 15u. It’s also ridiculously easy to produce as it stands. Most times I use it the victim is knocked unconscious within 5 seconds, or at the very least incapacitated. Stack it with some other brain damaging chem and you have a hilariously effective deathmix.
> 
> If anything I think braindamage in general should be nerfed, as kierany said.

is that really needed though? Who goes for brain damage when you can straight up kill someone instead

**Comment by BebeYoshi** [comment]
The temperature still seems oddly high for me

**Comment by wesoda25** [comment]
@shardj brain damage is the new meta for chemistry death mixes.

**Comment by wesoda25** [comment]
@shardj I use something along the lines of fentanyl, meth, and bath salts. Enough in a 15u syringe to kill your brain, as long as you scale them appropriately. And if you’re feeling lazy and don’t wanna make bath salts, theres like 3 other toxins you could use.

**Comment by Sisyphusrollson** [comment]
I’m beginning to find myself agreeing with Kierany and Wesoda. The core issue seems to be with brain damage itself.

**Comment by Shardj** [comment]
> @Shardj I use something along the lines of fentanyl, meth, and bath salts. Enough in a 15u syringe to kill your brain, as long as you scale them appropriately. And if you’re feeling lazy and don’t wanna make bath salts, theres like 3 other toxins you could use.

You can kill someone with brain damage now? Never seen that, where can I find the code?

**Comment by uBadush** [comment]
If your brain reach 200 damage you die

**Comment by Tlaltecuhtli** [comment]
>changing the recipe is a nerf in the year of chem macros
  
  
  
  
 
 :joy:

**Comment by Shardj** [comment]
> Bath salts only does 10 at the last addiction stage

You're mistaken unless I'm reading the line `M.adjustBrainLoss(10)` wrong https://github.com/tgstation/tgstation/blob/master/code/modules/reagents/chemistry/reagents/drug_reagents.dm#L310

**Comment by uBadush** [comment]
You right, my mistake, bath salts is 100% deadly if overdosed

**Comment by ExcessiveUseOfCobblestone** [comment]
If this is still an issue after trauma formula change we can relook at this.

**Pull request closed without merging**
