### PR TITLE
Increased odds of station traits a little. Introduced a "budget", so smaller traits only take half as much space.

### PR DESCRIPTION
**Pull request by Ghommie**
## About The Pull Request
Recently, I chatted with others about how few station traits are rolled on a round by round basis - about 59% of the shifts go without either positive or negative traits for example - and how the mild most of these traits are (not a bad thing per se), which results in an underwhelming feature, despite the more interesting bits of it. So, after sharing opinions, I've decided to make this PR to increase the rolls and odds a bit.

EDIT: After reading comments and taking some time to think this thoroughfully, I've decided to push the probabilities back a little in favor of a simple budget system for station traits, to allow for smaller things to only count as half a station trait. This mean smaller traits won't necessarily stop "better" ones from rolling, or at least allow for plentier permutations of traits that do not affect the round TOO much.
I've also reduced the weight of the glitched pda beeps trait from 15 to 10, the same of scarves, wallets and colored assistant jumpsuits.

## Why It's Good For The Game

I believe the current odds of station traits to be a smidge low, and that the lack of any sort of cost-budget for station traits to hurt the rarer, more interesting traits (and the feature in general) if the more common, milder ones take just as much space. It's totally within the spirit of the feature to have small, niche traits, though they can get quite boring pretty fast on their own, so what I'm saying is that their cost should stay low so that other traits can roll.

## Changelog

:cl:
refactor: Introduced a simple budget system to station traits, so that smaller things only count as half a trait, for example.
balance: Increased the odds and maximum number of station traits that can be rolled each shift.
/:cl:

### CODE REVIEW

**Comment by MrMelbert** [comment]
I feel like this should be configurable

**Comment by optimumtact** [comment]
@tgstation/head-admins interested to hear your thoughts.

**Comment by Ghommie** [comment]
> I feel like this should be configurable

I guess I can agree on that.

**Comment by atlasle** [comment]
isn't there a trait weight system? couldn't it work like theres a trait score thats the same for every round and then it fills that with enough traits to meet the score (so multiple small ones or one big one)

**Comment by Ghommie** [comment]
> isn't there a trait weight system? couldn't it work like theres a trait score thats the same for every round and then it fills that with enough traits to meet the score (so multiple small ones or one big one)

It'd better stay as is rather than dynamic v2.0. The weights of station traits don't necessarily represent the (pretty subjective) impact they've on the round.

**Comment by atlasle** [comment]
> It'd better stay as is rather than dynamic v2.0. The weights of station traits don't necessarily represent the (pretty subjective) impact they've on the round. 

i see thank you

**Comment by optimumtact** [comment]
Personally I think increasing the odds actually waters down the impact of having station traits.

**Comment by Ghommie** [comment]
Debateable. I understand you want them to be the exception rather than the norm, and that's good on paper, but we have many of those small, "fluffy" (not necessarily bad design) traits (many of which have High weight), so it really isn't that much interesting and impactful as you make it seem ito be, if those scarce rolls are predominatingly going to "fluff".

**Comment by optimumtact** [comment]
It doesn't have to be impactful, it's a side feature, it doesn't have to have so much weight as to be extremely in your face.

You fundamentally misunderstand the point of these flavour enhancers.

MSG improves a dish, it doesn't smack you in the face with it's presence it's not a primary seasoning.

**Comment by Ghommie** [comment]
So, why were you arguing about the impact of station traits being watered down if they don't have to be impactful at all?

**Comment by optimumtact** [comment]
> So, why were you arguing about the impact of station traits being watered down if they don't have to be impactful at all?

The impact is from them not running often which makes them more interesting when you do see them, the impact doesn't have to be increased, because they dont need to be more impactful than they already are.

**Comment by Ghommie** [comment]
I don't think players will abundantly care that much. Several traits are pocket-sized novelty anyway, or can easily go unnoticed by many. I don't think they're going to be less interesting at all if they rolled more often provided there's a good variety of them.

I can easily lower the chances, also because I've this creeping doubt I may have overshot them, but if you don't want traits to roll more often merely because you dislike them, I don't think we'll ever to a middle point here.

**Comment by Ghommie** [comment]
Ok, I've updated the PR (and the main comment, which previously read a bit like a word salad written by an half-asleep me calling it a day). Reduced the odds a little to meet optimumtact's critique, while implementing a simple "budget" system, which is something that was indirectly suggested by Time-Green's in another PR.

**Pull request merged**
