### PR TITLE
Botany Fixes

### PR DESCRIPTION
**Pull request by Fox-McCloud**
Just a few botany fixes

- Fixes a runtime with Kudzu being impacted by certain chemicals
- Fixes Kudzu seeds created from vines not having their potency and production genes properly set
- Fixes reagent application to Kudzu seeds not properly altering gene stats
- Fixes `set_production`  to clamp to 1 and 10 instead of 2 and 10
- Fixes `set_weed_chance` to clamp to 0 and 67 instead of 0 and 100
- Fixes `set_weed_rate` to clamp to 0 and 10 instead of 0 and 100
- Fixes glowshrooms having an invalidly high lifespan (120->100)
- Fixes explosive vines deleting their own datum
  - Impact of this is that chain reactions now properly work

:cl: Fox McCloud
fix: Fixes Kudzu seed gene stats not being properly altered by certain reagents
fix: Fixes Kudzu vine dropped seeds not properly having gene stats set
fix: Fixes glowshrooms having an invalidly high lifespan
fix: Fixes explosive vines not properly chaining
/:cl:

### CODE REVIEW

**Comment by XDTM** [comment]
Damn i really need to get working on my rework

**Comment by Fox-McCloud** [comment]
apparently the 67 weed rate was intentional? That's a really weird number to pick.

**Comment by Fox-McCloud** [comment]
so apparently whoever added in the explosive kudzu mutation made the mutation delete itself when it gets hit by an explosion...instead of the kudzu vine.

**Comment by FantasticFwoosh** [comment]
120 is a working age range, it will continue past a 100 with a additional 20 lifespan time, the only part that is buggy about it is that its outside the typical scale of 0-100.

> The fact that is only present within base glowshrooms add to their value to preserve & not slather in ez-grow (though it might buff gene editors too much)

On the fence about that change.

**Comment by RemieRichards** [comment]
@Fox-McCloud I'd argue it's intended, with explosive mutation acting as a sort of "one-time shield" against other explosions.

**Comment by Fox-McCloud** [comment]
@RemieRichards 

I kinda doubt it though; the vine mutations are semi-global and shared across all vines and the vine controller; when it's deleted, it's deleted from existence until a new vine controller is created---so you end up with null entries in the mutation list when you delete them.

Also, it doesn't even function as intended, because of how the vine's `ex_act` works.

If `on_explosion` runs, then it delete the datum and not the vine---it's impossible for it to chain react at all--which, judging by the comments, the whole gimmick of explosive vines is that once a single one is set off, it cascades throughout the entire vine system.

**Comment by AnturK** [comment]
Raz confirmed original intent was chain reaction.

**Pull request merged**
