### PR TITLE
The Hydration Update

### PR DESCRIPTION
**Pull request by itseasytosee**
image

## About The Pull Request
This update adds some new additions to water-based things.
Water now gives you a minor mood buff and very minor stun resistance while in your system.
This effect also applies to holly water and funnily enough hell water, so at least you can feel refreshed while being burned alive.
Water coolers have been installed in the medical break room (getting rid of the cig machine because smoking is bad for your health) and also in the research breakroom.
Alkaline water can now be made with 5 parts water and 1 part saltpetre. It is identical to water except it tastes a bit bitter.
There is now a gilded water cooler hidden away in the vault. Legends say that it was used by office workers of the gods.
## Why It's Good For The Game

Hydration is important.

## Changelog
:cl: itseasytosee
add: Stay hydrated crew! studies show that regular water intake can boost morale by up to 3%
add: The medical break room smoke machine was replaced with a water cooler to help people break bad habits. More water coolers might be found in other breakrooms and meeting places.
add:  Our top chemists have finally cracked the creation of alkaline water its made with 1 part saltpetre and 5 parts water.
/:cl:

### CODE REVIEW

**Comment by itseasytosee** [comment]
accidently delete meta.

**Comment by wesoda25** [comment]
this pr is a yikes in general

**Comment by EOBGames** [comment]
> accidently delete meta.

"accidentally"

**Comment by itseasytosee** [comment]
Something fucked up bad I may need to redo this PR

**Comment by spessbandit** [comment]
dehydration sounds like a good symptom for viruses etc

**Comment by itseasytosee** [comment]
I'll be back later tonight fuck.

**Pull request closed without merging**
