### PR TITLE
Reminds the user that reading a book or writing a book while blind is stupid

### PR DESCRIPTION
**Pull request by ma44**
:cl: ma44
add: Reminds the user that reading or writing a book while blind is stupid. 
/:cl:

### CODE REVIEW

**Comment by Shadowlight213** [comment]
>not having braille in spacemen year.

Wow

**Comment by KorPhaeron** [comment]
Ableist garbage

**Comment by ShadowDeath6** [comment]
>not making it do brain damage 
"You suddenly feel stupid"

**Comment by optimumtact** [comment]
build failure was down to github dns trouble, build restarted

**Pull request merged**
