### PR TITLE
Adding laceup shoes to curator's outfit

### PR DESCRIPTION
**Pull request by ecronogist**
## About The Pull Request
Adds laceup shoes to curator's outfit.
--
Old: 
old
New:
new

## Why It's Good For The Game
The curator looks fancy, and should not be wearing sneakers.

## Changelog
:cl: Cyfause
code: changed some code
/:cl:

### CODE REVIEW

**Comment by PKPenguin321** [comment]
i HATE laceup shoes

**Comment by Angustmeta** [comment]
Doesn't suit the curator imo. At least not as default.

**Comment by plapatin** [comment]
i agree, give curators combat clown shoes at roundstart instead

**Comment by ExcessiveUseOfCobblestone** [comment]
put the default outfit before/after

**Comment by ecronogist** [comment]
fixed

**Comment by ExcessiveUseOfCobblestone** [comment]
you actually like the laceup better lol?

**Comment by ecronogist** [comment]
yeah dude, i don't know why everyone i talk to hates it

**Review by 81Denton — APPROVED** [review]
PK "suit with sneakers" Penguin

**Comment by ExcessiveUseOfCobblestone** [comment]
cringemerge

**Comment by ecronogist** [comment]
epic style merge

**Pull request merged**
