### PR TITLE
adds more weapons to the murderdome (i just woke up at 5 in the morning don't bully me)

### PR DESCRIPTION
**Pull request by ghost**
:cl: iksyp
add: The murderdome now has new weapons to play with! Those being: AT Launchers, and freedom vendors.
tweak: The singular firing pins in the murderdome have been replaced with boxes of firing pins
/:cl:

\>add a place to fucking kill each other
\>no explosives
literally unplayable

### CODE REVIEW

**Comment by AlexTheSysop42** [comment]
Will the AT launcher explosions destroy the other guns/items?

**Comment by iskyp** [comment]
no I don't think it will

**Comment by AlexTheSysop42** [comment]
Solution: make deleting a VR avatar dust them instead (with no remains)

**Comment by DaxDupont** [comment]
Dusting also eats everything iirc

**Comment by AlexTheSysop42** [comment]
Suggestions: 
* Replace scatter laser with the recharging scatter laser
* Add accelerator lasers
* Add golden revolvers if they aren't in the liberation station
* Add wormhole projectors (they work in VR, I just looked at the code) (no you can't abuse this to transfer items between virtual reality and real reality because the portals are tied to the projector and there's no way to shoot a projector on both sides without an existing means of transportation)
* Add grav guns

**Comment by MrDoomBringer** [comment]
add an emagged recycler to the center of the map

**Comment by iskyp** [comment]
I'm just going to remake this pr but better when #37909 is merged and I'm not tired

**Comment by AlexTheSysop42** [comment]
oh looks like it does

**Pull request closed without merging**
