### PR TITLE
False walls now block air

### LINKED ISSUE #11813: Examine false walls have a different mini icon than normal walls
Title.

### PR DESCRIPTION
**Pull request by ChangelingRain**
:cl: Joan
tweak: Closed false walls will block air.
/:cl:
Fixes #11813

### CODE REVIEW

**Comment by coiax** [comment]
Eh. I am unsure. Shouldn't we be encouraging people to use airlocks, and this implies that an assistant with a welder and a wrench can turn a wall into an airtight door

**Comment by xxalpha** [comment]
Inconsistent with regular doors not blocking air.

**Comment by ChangelingRain** [comment]
CLOSED DOORS BLOCK AIR YOU BUTT

**Comment by Bawhoppen** [comment]
they really shouldn't

**Comment by PKPenguin321** [comment]
Bad

**Comment by xxalpha** [comment]
This is inconsistent with reality and this game is about realism.

**Comment by Bawhoppen** [comment]
and I mean the mineral doors should block air either

**Comment by swankcookie** [comment]
I've been seeing a lot less autism forts recently. this makes me sad.
:+1:

**Comment by TechnoAlchemisto** [comment]
Falls walls should be used for pressurized areas, it's like in old timey' novels where the ye old detective would feel a draft of air and discover the secret passage/false wall.

**Comment by ChangelingRain** [comment]
Yeah but you can't feel the draft, the only time you'll notice is when it depressurizes or when plasma/n2o go through it, and then you have bigger problems.

**Comment by Lumipharon** [comment]
False walls shouldn't be airtight. It's literally just a loose piece of wall.

**Comment by optimumtact** [comment]
Minor change, can be reverted if it somehow causes too much pain.

Plus phil thumbed it up.

**Comment by PKPenguin321** [comment]
smh

**Pull request merged**
