### PR TITLE
Unified mechs energy and ballistics guns firing proc

### LINKED ISSUE #6179: Mech guns leave all the bullets on the floor
At first i thought its casings, but no, its bullets
Loads of bullets
@Aranclanos

### LINKED ISSUE #8384: Why is this not fixed yet, make it stop
The guns on the Mauler (the 140tc nuke op mech) don't work - other then the missile launcher.
This is the scattershot and the AC2. Effects the robotics built ones also.
Both just spawn bullets instead of actually firing them.

I'm certain this bug was reported like, 6 months ago, dunno why it's still around.

Also tangentially related, but the mech missile launcher (which is really shit, does like, no damage) can be rather powerful, due to REASONS.

I just watched a nuke op in a mauler shoot a windoor at point blank, with a nuke op on either side of him.
The explosion destroyed the windoor, which some how propelled rods into the 2 ops like 50 times, and insta killed both of them.

### PR DESCRIPTION
**Pull request by Menshin**
What's better than three nearly identical procs ?
Three nearly identical procs, with two being broken...
#### Contents
- Unified the firing proc for energy and ballistics mech guns (generalized multi-projectiles shooting and projectiles deviation).
  Fixes  #8384.
  Fixes #6179
- Fixes incendiaries bullets runtiming on qdel

I've left missiles racks and honkmaster alone.

### CODE REVIEW

**Comment by WJohn** [comment]
Does this fix #6179?

**Comment by Menshin** [comment]
Yeah, it's the same issue (calling _Process()_ instead of _Fire()_).

**Comment by Kromgar** [comment]
Can you fix the fact maulers can't destroy tables or walls without like 15+ punches?

IT COSTS 140 TC. It should instantly tear down non rwalls and rip apart shutters

**Comment by Menshin** [comment]
This is unrelated and will have to be treated in another PR.

Agreed that it's silly that a table is a hard-to-bypass obstacle for Mechs though.

**Comment by Jordie0608** [comment]
A changelog wouldn't hurt for this

**Comment by Menshin** [comment]
Added harmless changelog.

**Pull request merged**
