### PR TITLE
Fixes Oh Hi Daniel shuttle using the wrong name.

### LINKED ISSUE #68789: Oh Hi Daniel is incorrectly labelled as Oh Hi Mark
image

fix this immediately

### PR DESCRIPTION
**Pull request by orthography**
## About The Pull Request

Fixes the Oh Hi Daniel ship accidentally still referencing copywritten materials.

Correct if wrong @Iamgoofball 

## Why It's Good For The Game

Fixes https://github.com/tgstation/tgstation/issues/68789

In accordance to https://github.com/tgstation/tgstation/commit/8b4524603435c90a7d9816fac18aa820321deb3a

## Changelog

:cl:
spellcheck: oh hi mark changed to oh hi daniel.
/:cl:

### CODE REVIEW

**Comment by san7890** [comment]
Can you change your changelog to be more discreptive, please?

**Comment by Iamgoofball** [comment]
it was named oh hi daniel when i implemented it 🤷

**Comment by Farquaar** [comment]
If "Oh Hi Mark" is copyrighted material then everything in the game is copyrighted material. You can't hold copyright over something as simple as saying hi to a guy named Mark. 

What's next, getting rid of red security officer uniforms because Star Trek TOS had red shirts?

**Comment by BlueMemesauce** [comment]
> If "Oh Hi Mark" is copyrighted material then everything in the game is copyrighted material. You can't hold copyright over something as simple as saying hi to a guy named Mark.
> 
> What's next, getting rid of red security officer uniforms because Star Trek TOS had red shirts? Or yellow engineering uniforms? Or blue medical uniforms?

It doesn't really matter, the name of the shuttle is already Oh, Hi Daniel. I don't know why the PR contributor made it confusing. These are only some random minor things that probably were just accidentally misnamed.

**Comment by orthography** [comment]
> > If "Oh Hi Mark" is copyrighted material then everything in the game is copyrighted material. You can't hold copyright over something as simple as saying hi to a guy named Mark.
> > What's next, getting rid of red security officer uniforms because Star Trek TOS had red shirts? Or yellow engineering uniforms? Or blue medical uniforms?
> 
> It doesn't really matter, the name of the shuttle is already Oh, Hi Daniel. I don't know why the PR contributor made it confusing. These are only some random minor things that probably were just accidentally misnamed.
> 
> https://github.com/tgstation/tgstation/blob/c38b594ca4514b40de6fa003a0abfaab6a00276a/code/datums/shuttles.dm#L390

The shuttle was calling the wrong name, this was the only other places it was being mentioned as Oh, Hi Mark.

image

**Comment by tralezab** [comment]
This is obviously not about copyright but more obviously that the shuttle is named something and there are references that aren't using the correct name

**Pull request merged**
