### PR TITLE
Cold room is no longer a cryogenic freezer

### PR DESCRIPTION
**Pull request by nightred**
## About The Pull Request

The cold room starts off at -80c, at that temperature you are storing tissue samples, not cooking supplies.
This changes the default room to -14c.

Originally is was going to do +4c the recommended walk in fridge temperature, but requests to leave lizard damage have been high.

## Why It's Good For The Game

The act of opening the doors to the cold rooms would cause the area around them to become unbearably cold.
This is a good temp to keep food and medical supplies.
Just bureaucratically low enough that lizards feel discriminated against. (1 kelvin past lizard damage threshold)

## Changelog
:cl:
tweak: Cold rooms are now cold, no longer arctic conditions.
/:cl:

### CODE REVIEW

**Comment by ATH1909** [comment]
is it still cold enough in that freezer to cause cold damage, or are lizard chefs finally free from the tyranny of the cold room now?

**Comment by nightred** [comment]
> is it still cold enough in that freezer to cause cold damage, or are lizard chefs finally free from the tyranny of the cold room now?

This puts the cold room temp about 10c above lizard cold damage.

**Comment by RaveRadbury** [comment]
Cold damage from the freezer rooms is awesome I want it on every map tbh

**Comment by nightred** [comment]
> Cold damage from the freezer rooms is awesome I want it on every map tbh

What is the thought of putting it a few points past lizard cold without being insane like -14c?

**Comment by RaveRadbury** [comment]
A saner temp that still activates the damage threshold sounds reasonable.

**Comment by evilcyborgmrt** [comment]
Tissue sample are usually frozen in liquid nitrogen around -200C. They are only stored at -80.

**Comment by Quietly12** [comment]
This feels like a loss of characterization for the game, rather than an improvement.

**Review by kriskog — APPROVED** [review]

**Pull request merged**
