### PR TITLE
Rework of the sound annoucing a Malf AI

### PR DESCRIPTION
**Pull request by Dafium**
## About The Pull Request
I replaced 'malfai.ogg' by a other sound.

## Why It's Good For The Game
The current sound, is very old fashioned, and we've all heard it thousands of times. I decided to rework it and i found something which could fit as a new sound, it doesn't sound as the current one, but in my opinion, it's better than the actual one.

To make your opinion, you can listen to the sound here : https://vocaroo.com/1mFrea4XAaUH

## Changelog
:cl: EnPeignoir
soundadd: Now, you'll hear a brand new sound when a malf IA is announced
/:cl:

### CODE REVIEW

**Comment by MrDoomBringer** [comment]
old sound was better imo. sounded more interesting, the fucky synthesized voice made it a little unnerving. This is just weird static noise with too much bass 👎

**Comment by zxaber** [comment]
The old one gives the impression that the AI is actually losing its mind. Either through abuse from the crew, or data corruption, the AI has lost all semblance of its old self and simply wears its prior helpful personally as a facade.

I guess modern Malf is closer to "implanted Syndicate AI" than "station AI going haywire" , but the old sound is better than obscure static.

**Comment by Dorsisdwarf** [comment]
Ah yes, replace an interesting sound that lines up with all the other announcement files with... generic synth static screech you made in 30 seconds in audiacity. 

Your reason for "Why this is good for the game" is incoherent and its only point is "im bored". How quick do you think people willl be bored of you replacing one of the more unique and threatening sounds in ss13 with the most generic sound effect yet?

**Comment by Iamgoofball** [comment]
:-1:
The Steve Chopping Wood joke is fucking hilarious and this replaces it with dumb dubstep garbage.

**Comment by Thunder12345** [comment]
No soul 👎

**Comment by Fhaxaris** [comment]
https://youtu.be/A-ZDgXm95YM

**Comment by MrDoomBringer** [comment]
> 👎
> The Steve Chopping Wood joke is fucking hilarious and this replaces it with dumb dubstep garbage.

holy shit that is a deep cut reference, I didn't even know that lmao
even more reason to not merge this

**Comment by EnPeignoir** [comment]
damn

**Pull request closed without merging**
