### PR TITLE
Nutriment gives heart attacks IF you reach the OD threshold

### PR DESCRIPTION
**Pull request by yackemflam**
If you somehow eat enough to get a heart attack. The gods should spawn you a cookie.

:cl: Yackemflam
add: Nanotrasen 'nutriment' now actually gives nutriment. Don't eat too much!
/:cl:

### CODE REVIEW

**Comment by ShadowDeath6** [comment]
if you somehow get 300u nutriment in your system you deserve this

**Comment by SkowronX** [comment]
I guess this makes the weight gain symptom instantly kill?

**Comment by Kromgar** [comment]
Buuut thin mint existed for this

**Comment by Niknakflak** [comment]
Bad

**Comment by KorPhaeron** [comment]
Sounds like a pointless nerf to slime people

**Comment by jughu** [comment]
Make it turn you into a morph as overdose result :^) a harmless morph that is

**Comment by ShadowDeath6** [comment]
don't nerf slime people pls

**Comment by ChangelingRain** [comment]
the weight gain symptom doesn't give you nutriment

**Comment by yackemflam** [comment]
Slime people wont even be effected.
Since you'd have to eat FIFTY BURGERS to even get the heart attack.

**Comment by KorPhaeron** [comment]
So why add it if it will never happen outside of someone doing it on purpose the round after its added?

**Comment by yackemflam** [comment]
I can lower the number and make it so that slime people are excluded from the heart attacks.

**Pull request closed without merging**
