### PR TITLE
Centcomm is on Z1

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
This will be important for any multi-z maps we do, since we don't want people falling into centcomm.

### CODE REVIEW

**Comment by RemieRichards** [comment]
You are playing a dangerous game.

**Comment by KorPhaeron** [comment]
I'm sure it will be fine

**Comment by AnturK** [comment]
What's the worst thing that can happen. 🤔 

Anyway, not really sure how this is relevant to multi-z since that would require some explicit z level links defined anyway.

**Comment by RemieRichards** [comment]
@AnturK my multiz can only link up/down for simplicity, eg: z5 (optionally) links to z4 and z6, this allows us to use the byond ```UP``` and ```DOWN``` dirs

**Comment by KorPhaeron** [comment]
Someone is making a multi deck ship map as well and I would not be surprised if that got finished before planetstation

**Comment by Jordie0608** [comment]
What if the real purpose of this PR is to find out if there are still z level checks using magic numbers?

**Comment by AnturK** [comment]
I see , well at least we'll probably find out some badcode with this.

**Comment by Cyberboss** [comment]
I trust nothing about this PR

**Comment by KorPhaeron** [comment]
It loads in the correct order at least. Obviously can't test the entire rest of the game by myself though

**Comment by BeeSting12** [comment]
@KorPhaeron 
You underestimate my procrastination

**Comment by kevinz000** [comment]
living the dangerous life kor memeron

**Comment by ninjanomnom** [comment]
I've tested with functionally identical code in ftl13, but then again our z level manager is very different. Should work fine.

**Comment by MrStonedOne** [comment]
Somebody should have told me about this pr so i could have properly updated the death table in the database.

**Comment by optimumtact** [comment]
I apologise, that didn't even cross my mind sorry.

**Comment by optimumtact** [comment]
hmm, we shouldn't store the actual z level number, instead it should be abstracted away into a lookup table, so we can change the actual z level and not affect stats.

**Pull request merged**
