### PR TITLE
Marisa resprite, by TetraZeta

### PR DESCRIPTION
**Pull request by necromanceranne**
## About The Pull Request

A moff player made a new sproite and said I was allowed to pr this to /tg/ so I did. I also changed the icons a bit to match.

marisa by tetrazeta

Here is a preview they made ye

## Why It's Good For The Game

I only use this outfit as wizard, as any good cat player does, as any good moff probably too iunno I don't speak for moffs

## Changelog
:cl: TetraZeta, NecromancerAnne
add: A new sprite for the Marisa outfit.
/:cl:

### CODE REVIEW

**Comment by Fikou** [comment]
player reference outfit removed when

**Comment by Doosteroni** [comment]
I love sproites

**Comment by Tharcoonvagh** [comment]
they don't even play anymore

**Comment by necromanceranne** [comment]
Who, tetrazeta? No shit? I asked them if I could use it because they made it for a downstream.

**Comment by Tharcoonvagh** [comment]
Right

**Pull request merged**
