### PR TITLE
Monkeys can now use all guns without restrictions.

### PR DESCRIPTION
**Pull request by AnturK**
image

### CODE REVIEW

**Comment by PKPenguin321** [comment]
:+1:

**Comment by Armhulen** [comment]
If mice can use fireballs, I see no problem with monkeys using guns

**Comment by GunHog** [comment]
Bring back Monkey mode.

**Comment by Aloraydrel** [comment]
Finally monkey gangs is a possibility

**Comment by Supermichael777** [comment]
this was removed for a reason. namly lings crawling into the armory ever ling round and gging the warden before stealing all the guns

**Comment by KazeEspada** [comment]
Except... that you can't ventcrawl while holding shit.

**Comment by TheRealGLH** [comment]
But you can break the windows/ lure the warden inside.

**Comment by KazeEspada** [comment]
You could just ventcrawl into his office, go human, armblade him to death and steal the armory that way?

**Comment by Lumipharon** [comment]
That is a terrible reason to remove monkey using guns.
If you ventcrawl into the armoury, the warden can jsut flashbang/disabler you through the glass. If the warden is dumb enough to run into the room with the monkey carrying pils of guns, that's his own fault.

This was a dumb change, same with making monkeys not be able to read, like, for what purpose?

**Comment by Shapsy** [comment]
You can't shoot into the armory from the brig because of the consoles. Also it takes 5 seconds to take a monkey's DNA injector in genetics and get a free ticket right into the armory while ignoring all of the brig's defenses and giving no warning to anyone before you're in there with a taser and an egun which is obnoxiously easily for the weaponry you get.

**Comment by HankMoodyExperience** [comment]
>security taunts pun pun https://youtu.be/GhxqIITtTtU

**Comment by Lumipharon** [comment]
Console only cover a small part of the warden's office, so no, they don't block shit.
Also flashbangs in the warden's office still assfucks anyone in the armoury.

Once you're in the armoury you can't get out with the guns unless you A: have a storage implant or B: shoot your way out, in which case you're at a huge ass disadvantage as you're a naked monkey, or if you're a ling, you're at best a naked person with swordarm.
Either way, you're still a fish in a barrel for a warden that isn't literally asleep.

**Comment by PKPenguin321** [comment]
>wasn't there a pr to let you shoot past consoles or something also? Did that ever get merged?

no and no

**Comment by Lumipharon** [comment]
https://github.com/tgstation/-tg-station/pull/14649
It never got finished, but it did exist.

**Comment by PKPenguin321** [comment]
Based cheridan

**Pull request merged**
