### PR TITLE
Bar dispensers and table placement improvements

### LINKED ISSUE #51967: There are 2 Bar APCs on meta
## Round ID:
Unrelated

## Testmerges:
Local Server

## Reproduction:

There appear to be 2 bar apcs on meta.
image

They are both in the same area. More deets to flow.

Deets:

There are spaces defined as the "bar". One is in the bartenders office, the other is the main room to the north west 
image
Both are using the same area. So 2 apcs, one area. APC code is not made to work properly with this, don't do it.

### PR DESCRIPTION
**Pull request by nightred**
## About The Pull Request

The flow of the bar is now improved, walking lines in and out are better.
The back counter in the bar and kitchen have been cleaned up to give more space and less counter.
Moved one fridge from freezer to kitchen, and removed the extra fridge I added earlier.
Got Potty back in the bar.
Fixed an apc duplication in an area.

Changes

## Why It's Good For The Game

Getting feedback on the layout has improved the flow.
fixes #51967

## Changelog
:cl:
tweak: Meta Bar counters are tweaked in placement
/:cl:

### CODE REVIEW

**Comment by Fikou** [comment]
can you remove the cheeto dust over the kitchen tables

**Comment by nightred** [comment]
> can you remove the cheeto dust around the kitchen tables

_Gumples_ I like decals... but ok done.

**Comment by Tlaltecuhtli** [comment]
the angle stool is triggering

**Comment by nightred** [comment]
> the angle stool is triggering

You are right, that is now fixed.

**Comment by ArcaneDefence** [comment]
I might be lame in asking this, but do we still have potty the plant with the cake hat? I'm a fan of birthday cakes and cake hats, and so potty is naturally dear to me.

**Comment by nightred** [comment]
> I might be lame in asking this, but do we still have potty the plant with the cake hat? I'm a fan of birthday cakes and cake hats, and so potty is naturally dear to me.

I am so sorry, I never noticed that potty existed.
I have corrected this and put him back in the bar.

**Comment by LemonInTheDark** [comment]
APC destroyed, pls fox #51967

**Comment by LemonInTheDark** [comment]
thank

**Pull request merged**
