### PR TITLE
Fixes book bags not being able to hold bibles and looking like backpacks

### LINKED ISSUE #7425: Librarian's bookbag can't be worn on the back slot, despite the sprite looking like a backpack
if this isn't intended, i'll sprite it.

### LINKED ISSUE #8258: Bibles can be put in bookshelves, but not in book bags
title

### PR DESCRIPTION
**Pull request by phil235**
Fixes book bags not being able to hold bibles. Fixes #8258 
Changes the book bag sprite so it looks more like a briefcase and isn't confused with a backpack (bigger handle, no back straps, slightly shorter and wider). Fixes #7425

### CODE REVIEW

**Comment by Chocobro** [comment]
jesus phil you're so goddamn diligent

**Comment by Lumipharon** [comment]
Isn't the book bag essentially redunant now? It used to be a normal sized item, so you could put it in a bag.
Now that it's bulky, it's just a bag that can only carry books. Unless it can carry more then 7?

**Comment by PKPenguin321** [comment]
while you're at this can you check if arcane tomes will fit in book bags? it'd be great if they could, too, but i don't think they can currently

**Comment by Jordie0608** [comment]
Tomes aren't children of books, so they can't.

**Pull request merged**
