### PR TITLE
Updates the bee description: no speedmerge pls

### PR DESCRIPTION
**Pull request by Iamgoofball**
maybe this time it gets merged

### CODE REVIEW

**Comment by ike709** [comment]
https://www.youtube.com/watch?v=99-LPa_-5sE

**Comment by Armhulen** [comment]
ChangelingRain added the Do Not Merge label 16 hours from now
RemieRichards was assigned by ChangelingRain 16 hours from now
ChangelingRain requested a review from RemieRichards 16 hours from now
cmon now

**Comment by Dorsisdwarf** [comment]
but why

**Review by RemieRichards — DISMISSED** [review]
No.

**Comment by Qustinnus** [comment]
why not

**Review by Cyberboss — DISMISSED** [review]

**Review by RemieRichards — DISMISSED** [review]
No.

**Comment by Iamgoofball** [comment]
god get a room

**Comment by PopNotes** [comment]
merge this now

**Review by Cyberboss — APPROVED** [review]
Code is valid af

**Comment by Armhulen** [comment]
@optimumtact

**Comment by RemieRichards** [comment]
@Cyberboss reviews aren't just about code you know, they're about whether something will be accepted (which includes) code, and this won't ever be accepted.
@optimumtact it was already there.

**Pull request closed without merging**
