### PR TITLE
Brings back headpatting, not shitcode.

### PR DESCRIPTION
**Pull request by Iamgoofball**
I code for the players.

### CODE REVIEW

**Review by Cyberboss — APPROVED** [review]

**Comment by juanototo2** [comment]
A goof PR that doesn't involve hatred against furries, not-tested-at-all meme features or complete redesigns of something because it crossed his mind? **WHAT IS THIS MADNESS?**

**Comment by BeeSting12** [comment]
Bring back slapping

**Comment by Qbopper** [comment]
low tier attempt to bait out votes tbqh

**Comment by optimumtact** [comment]
there is a clique of people who use this emote and I don't like any of them and I was hoping they'd leave when it was removed

**Comment by Arianya** [comment]
Slippery slope.

**Comment by Slignerd** [comment]
I preferred help intent head targetting for headpatting.

**Comment by Arianya** [comment]
Also realistically this is a attempt to gain votes in the headmin election that he'll try to revert win or lose.

**Comment by DoctoreMad** [comment]
>Also realistically this is a attempt to gain votes in the headmin election that he'll try to revert win or lose.

Finally another person who is hot on the gimmicks of the metaclub

**Comment by nicbn** [comment]
> I preferred help intent head targetting for headpatting.

# P L E A S E

**Pull request closed without merging**
