### PR TITLE
Passes thrownthing to hitby

### PR DESCRIPTION
**Pull request by 4dplanner**
:cl:
fix: now checks throwforce of objects, so you can't push tendrils around
/:cl:
EDIT: Now also standardises throw_impact() and hitby() calls.
EDIT: Also changes var/mob/M to var/mob/M=hit_atom in SM sword, because it did nothing
Turns out the reason that you could push tendrils around was that hitby wasn't actually checking the throw force at all

### CODE REVIEW

**Review by ShizCalev — DISMISSED** [review]

**Comment by 4dplanner** [comment]
Spaghetti code: there are other places I need to do the same

**Review by ShizCalev — DISMISSED** [review]

**Review by ShizCalev — CHANGES_REQUESTED** [review]
/obj/item/shield/energy/bananium/throw_impact
too

**Comment by 4dplanner** [comment]
Apparently default arguments lead to runtimes in DM because of overloading

**Comment by optimumtact** [comment]
overloading procs and adding variables to the children only is the devils work and I wish byond would complain about it at compile time

**Comment by 4dplanner** [comment]
can_push is hitpush

**Pull request merged**
