### PR TITLE
Revert "Moves all the custom AsteroidStation areas"

### PR DESCRIPTION
**Pull request by tkdrg**
Reverts tgstation/-tg-station#6733

The PR was self-merged by its creator even after two maintainers raised concerns about it that went unaddressed. Thus, I propose a revert unless those complaints can be actually answered.

My point is that merging asteroid stuff into the main codebase is bad because it kills the modularity and makes it more difficult to remove the map from our codebase if we want to do that.

### CODE REVIEW

**Comment by pudl** [comment]
why does the map even use custom areas? why not just the the normal ones?????

**Comment by pudl** [comment]
also asstation has already been replaced by efficiency 3, so the pr was never needed in the first place

**Comment by paprka** [comment]
Why the hell is corruptcomputer even a maintainer if his first act as maintainer was to self merge shit

**Comment by Razharas** [comment]
Wait what?
Unironic self-merge?

**Pull request merged**
