### PR TITLE
Adds Thocks

### PR DESCRIPTION
**Pull request by Mickyan**
Maintainer approved

Screenshot_5

Screenshot_3

https://www.youtube.com/watch?v=N4oNOZoIS0o

## Changelog
:cl:
add: Added Thocks socks: dress to impress with thongs for your feet
/:cl:

### CODE REVIEW

**Comment by PKPenguin321** [comment]
it kind of doesnt work when you cant make out what it is with the tiny sprite

**Comment by wesoda25** [comment]
funny but bloat

**Comment by Anonmare** [comment]
When will we add stirrup socks?

**Comment by trollbreeder** [comment]
begone thot

**Comment by TheVekter** [comment]
Tim & Eric sucks

**Comment by trollbreeder** [comment]
do you think god stays in heaven because he, too, lives in fear of what he has created?

**Comment by TiviPlus** [comment]
Against God and Nature tag please

**Comment by HomocidlePancakes** [comment]
What the fuck is wrong with you?

**Pull request merged**
