### PR TITLE
Removes Summon Events from Wizard

### PR DESCRIPTION
**Pull request by Bawhoppen**
:cl: Gameplay Sanity Committee
del: Wizards may no longer summon events. Admins on the other hand...
/:cl:

C'mon... We all know it's too much. Nobody has fun during it except the wizard. In a normal wizard round, crew can atleast have fun banding together to fight the wiz.

### CODE REVIEW

**Comment by carshalash** [comment]
Thank you jesus.

**Comment by Acer202** [comment]
Nothing shatters roleplay like your character being irrecoverably changed at random. It's super lame, and I wouldn't miss it at all. Good PR, methinks!

**Comment by Jack7D1** [comment]
Very elegant way of removing it from wizard. Like a surgeons knife.

**Comment by wesoda25** [comment]
events isn't even the problem, at least there are some interesting things attached to it

what really needs the ax is summon guns/magic

**Comment by carshalash** [comment]
Race change/face swap every 2 minutes isnt fun.

**Comment by Farquaar** [comment]
I think most of the expressed annoyance comes from veteran players who have seen all the events dozens of times, which is understandable, but I've always enjoyed summon events, especially when I started playing two years ago. It was so fun and chaotic, and I think it's a mistake to outright remove it. Limiting it like in #49365 is a better choice.

**Comment by Taylorkills2** [comment]
Summon events needs to be gutted and changed, I like the idea and some of the events alot, but if a wizard uses the summon events even once, the round is ruined.
And everyone who's a veteran knows the round is ruined too, there's no point in continuing since you'll probably get raceswapped into a slug, or an abductor, or bodyswapped and die. Even if you don't you'll get identity swapped and no one will know who is who over comms.
Or the station will be attacked by swarms of sentient and hostile magicarp/chaos carps along with some magicians and survivalists.
Assuming you're not killed by some asshat spawning in infinite lavaland goliaths(or better yet ancient goliaths) using a matter bin.

**Comment by actioninja** [comment]
Summon events sucks but the bigger issue with it is not it existing, but that the events are ridiculously round disrupting and obnoxious, and there's not many of them.

Should be limited to max one time, needs a bigger event pool, and it should be a weighted pool. Seriously round disrupting events should happen once a round if at all, etc.

**Comment by cacogen** [comment]
round disrupting events such as those Taylorkills2 listed should undo before the next event is triggered

**Comment by trollbreeder** [comment]
in the gameconfig there's an option to turn off summon events, summon guns and summon magic, you dont have to circumcise it out, just yell at the headmins

**Comment by Fikou** [comment]
> in the gameconfig there's an option to turn off summon events, summon guns and summon magic, you dont have to circumcise it out, just yell at the headmins

**Comment by ATH1909** [comment]
> > in the gameconfig there's an option to turn off summon events, summon guns and summon magic, you dont have to circumcise it out, just yell at the headmins

**Comment by trollbreeder** [comment]
oh and there was an option to turn off cloning in the gameconfig as well

**Comment by Ratvar** [comment]
everyone who suggests gameconfig knows that you cannot trust headmins to use it even once, that is their goal

**Comment by 81Denton** [comment]
Summon events is a config option and from what I'm aware, removing it requires headmin approval. I'll go chat with them and oranges about the specifics, but until then I'm putting the DNM label on this PR.

**Comment by Tharcoonvagh** [comment]
remove fireball

**Comment by cacogen** [comment]
nah just make it better like having them undo before the next one

**Comment by optimumtact** [comment]
policy thread

**Pull request closed without merging**
