### PR TITLE
[very very wip] Esper gamemode

### PR DESCRIPTION
**Pull request by ghost**
a gamemode based on sentient electricity. suck up electricity, subvert machines, gain power, annoy spaceman

### CODE REVIEW

**Comment by optimumtact** [comment]
This is premature, considering you don't nearly enough of the code worked out yet

**Comment by 0d0be32b607ee4ecbc2358f3dd4a27de** [comment]
yes but it would be good to have code critiqued as it is workd on

**Comment by optimumtact** [comment]
The tracker is for nearly completed work, not for you to have other people write your code for you

**Comment by 0d0be32b607ee4ecbc2358f3dd4a27de** [comment]
how dare u accuse me of trying to freeload off other ppl

**Comment by Borisvanmemes** [comment]
Sounds like a neat idea but i don't think Esper is a very fitting name.

**Comment by 0d0be32b607ee4ecbc2358f3dd4a27de** [comment]
come up with better name

**Comment by 0d0be32b607ee4ecbc2358f3dd4a27de** [comment]
i can't figure out how to check if wire in direction is connected :(

**Pull request closed without merging**
