### PR TITLE
You tg fucks broke advanced proccall :(

### PR DESCRIPTION
**Pull request by monster860**
## Changelog
:cl:
fix: fixes advanced proccall
/:cl:

### CODE REVIEW

**Comment by PKPenguin321** [comment]
You can just delete the changelog from your PR body if you don't need it, striking it through will probably break things

**Review by MrsTonedOne — APPROVED** [review]

**Comment by Jordie0608** [comment]
This runtimes on every use
```
[14:50:30] Runtime in debug.dm,143: bad proc
  proc name: WrapAdminProcCall (/world/proc/WrapAdminProcCall)
  usr: Jordie0608/(Leland Beedell)
  usr.loc: (Law Office (102, 159, 2))
  src: world
  call stack:
  world: WrapAdminProcCall("some_magic_bullshit", "station_time", /list (/list))
  WrapAdminProcCall("some_magic_bullshit", "station_time", /list (/list))
  Jordie0608 (/client): Advanced ProcCall()
```

**Comment by Menshin** [comment]
Shouldn't you also change this line ?

https://github.com/tgstation/tgstation/blob/7e1ce9c041e566749580821d2f2ce00d4d191a49/code/modules/admin/verbs/debug.dm#L86

**Comment by optimumtact** [comment]
you tried, now fuck off

**Pull request closed without merging**
