### PR TITLE
Tweaks deep storage access, other tweaks+fixes

### PR DESCRIPTION
**Pull request by 81Denton**
:cl: Denton
tweak: The Syndicate have replaced the EVA suit, sleepers and soap inside their deep storage bunker with stylish, yet functional red/black models. Bunker access now requires Syndicate ID access instead of generic away mission access.
fix: Replaced deep storage bunker air alarms and APCs with models that can be unlocked with bunker IDs.
fix: Fixed the security camera at the deep storage bunker's entrance.
/:cl:

Ever since the last PR that touched it, the deep storage bunker contains a standard NT softsuit. I replaced it with a syndie softsuit/mask/oxygen harness, which IMO fits much better thematically.

Access reqs were also off, with everything requiring `ACCESS_AWAY_GENERAL` instead of the more plausible `ACCESS_SYNDICATE`.

Also, replaced the soap bar+sleepers with the syndie subtypes and replaced air alarms/APCs with subtypes that can be unlocked with bunker IDs.

### CODE REVIEW

**Comment by WJohn** [comment]
Ah, was trying to move it away from being a syndicate bunker because a few too many things were syndicate ruins. Might remake this one in the future to be a bit less of a freebie for its equipment.

**Comment by 81Denton** [comment]
That makes sense, I was wondering why it contained so many generic objs for a syndie ruin.

**Comment by WJohn** [comment]
Overall though I'm not really in favor of this as it gives this bunker back some good loot without making it any harder to actually get to any of it. A syndicate space suit is nearly as good armor as a hardsuit, and the harness jetpack is very powerful when you're going exploring because oxy tanks are much more common than CO2, and it can be put into your backpack which is relevant for the inventory juggling and hoarding that you typically do on space adventures.

The syndicate sleepers are also self-serving, which makes them a powerful source of free healing, though it's not a huge deal as this ruin has no way to hurt you, so they're not very useful here.

I don't really see the purpose of this PR tbh.

**Comment by WJohn** [comment]
fuckin' whaaaaat

**Comment by Tlaltecuhtli** [comment]
i think there are a bunch of reskinned red soft suits you can use if you dont want it to be syndicate

**Comment by Bawhoppen** [comment]
It's supposed to be a paranoid doomsday prepper bunker.
Source: I made the original version

**Comment by SpaceManiac** [comment]
Seems like the inclination is to not Syndicate-theme this ruin

**Pull request closed without merging**
