### PR TITLE
Reduce the defib revive times by half [DNM]

### PR DESCRIPTION
**Pull request by optimumtact**
3000 - 300 seconds - 5 minutes
1500 - 150 seconds - 2.5 minutes

Feedback thread https://tgstation13.org/phpBB/viewtopic.php?f=10&t=4030

### CODE REVIEW

**Comment by Iamgoofball** [comment]
:+1: x :100:

**Comment by optimumtact** [comment]
Please keep feedback to the thread goof, I'll view it as much as possible

**Comment by JJRcop** [comment]
From the feedback thread, this PR should get a controversial tag.

**Comment by Cheridan** [comment]
Personally, I prefer a paradigm where it is easy to revive rather than putting the emphasis on second-chance roles. I would much rather have a human with a real job and previous character interactions that can lead to better roleplay, over a golem created halfway into the round with no real responsibilties.

Design-wise I think defibs are perfect. Most importantly they neuter aimless killing-spree behavior while not actually preventing it or shutting down the antagonist. I don't think their use should be discouraged.

**Comment by optimumtact** [comment]
10 minutes is a long time to guard a corpse cheri

**Comment by Cheridan** [comment]
Eh, is it really necessary to guard them for 10 minutes though? You can just space or hide the body better.

**Comment by Miauw62** [comment]
Maybe we should fix the patch bug, then.

**Comment by optimumtact** [comment]
According to goof it's "not a bug"

**Comment by Miauw62** [comment]
there's a lot of BS that goof calls "not a bug"

**Comment by Iamgoofball** [comment]
Fuck off with that shit, Miauw.

Healing corpse brute/burn with patches was a specific intended thing because of Strange Reagent. Which is still in.

It'll revive you without a timer but if they've got too much brute/burn they'll get gibbed, and I'm pretty sure it brings you back as a zombie. The zombie part mighta gotten fucked up when incoming removed skelebones, though.

"fixing" this """bug""" makes strange reagent useless. So don't "fix" it because muh reels.

**Comment by optimumtact** [comment]
no clear winner here, so closing this for now

**Pull request closed without merging**
