### PR TITLE
you need spaceproof arm and leg covering to be spaceproof

### PR DESCRIPTION
**Pull request by Fikou**
## About The Pull Request

you no longer only need a spaceproof helmet and chest extended to be spaceproof, but also arms (or hands) and legs (or feet)
this checks for them being covered, not the slot itself. like if youre in an eva suit you dont need any gloves or anything because it covers your hands
if you dont have both of your arms you dont need arm/hand covering
if you dont have both of your legs you dont need leg/feet covering

**what this means in practice:**
you cannot only extend modsuit head and chest out to be spaceproof
if you xenobio potion a sec vest you also need to potion your gloves and shoes. if you potion something that covers arms like a winter coat then only shoes, if you potion something like a firesuit then youre overall good
technically also now if you were to lose your head youd be spaceproof in just a spaceproof suit (hars buff??)

**possible iffiness:**
while you only now need one arm to wear gloves, the same is not the case for legs and shoes. if youre in a modsuit and have your leg dismembered your leg will not be covered and you will take damage (though you can dismember your other leg and then you wont :P )

## Why It's Good For The Game

a bit silly in practice to have modsuits protect you from space in just a helmet and chestplate

## Changelog

:cl:
balance: you need something spaceproof to cover your legs (or feet) and arms (or hands) to be spaceproof, not only head and chest
balance: magboots and atmos gloves now have pressure protection
/:cl:

### CODE REVIEW

**Comment by AtomTheProphet** [comment]
I hope I'm not asking a pointless question here, but this doesn't impact EVA suits and whatnot, correct?

**Comment by Fikou** [comment]
> I hope I'm not asking a pointless question here, but does this impact EVA suits?

if you read the pr body:
> like if youre in an eva suit you dont need any gloves or anything because it covers your hands

**Comment by AtomTheProphet** [comment]
> > I hope I'm not asking a pointless question here, but does this impact EVA suits?
> 
> if you read the pr body:
> 
> > like if youre in an eva suit you dont need any gloves or anything because it covers your hands

I did read it. Must have glanced over that though, alright.

**Comment by OuroborusReporter** [comment]
Stealth dullahan buff, we just keep ~~winning~~ breaking even

**Comment by Holinka4ever** [comment]
If i remember well, atmos can make a special reagent that turn clothes into spaceproof item.
Mostly people do it with coats cause they have "helmet", but i see it gonna disturb em as well.

**Comment by Fikou** [comment]
> If i remember well, atmos can make a special reagent that turn clothes into spaceproof item. Mostly people do it with coats cause they have "helmet", but i see it gonna disturb em as well.

yeah they have a copy of the xenobio potion i think

**Comment by Xackii** [comment]
modsuits could be dressed partially and still get the effects of their body parts?

**Comment by moocowswag** [comment]
Do i gotta dress my lizard tail? :(

**Comment by Striders13** [comment]
you can't apply potions to shoes cause most of them have an item storage

**Comment by Xackii** [comment]
I don't understand. mc-oofert made it so that mods can be worn even if you don't have an arm or a leg in this pr https://github.com/tgstation/tgstation/pull/86825#issue-2540407449. Now you're making people without an arm or a leg die in space from pressure? I also don't understand why you're nerfing all possible ways to get space protect from clothes. 
> a bit silly in practice to have modsuits protect you from space in just a helmet and chestplate
>
This is not a reason to make it more difficult to obtain space protect in other ways.

**Comment by TheVekter** [comment]
Before I dunk on Xackii, I don't love that this is a nerf to xenobio space protect potions, but I don't see those used much anymore so maybe this will make them show up more often. They're not exactly hard to make multiples of anyway.

What are a list of gloves/boots that protect from space?

> I don't understand. mc-oofert made it so that mods can be worn even if you don't have an arm or a leg in this pr [#86825 (comment)](https://github.com/tgstation/tgstation/pull/86825#issue-2540407449). Now you're making people without an arm or a leg die in space from pressure? 

image

> I also don't understand why you're nerfing all possible ways to get space protect from clothes.

Use EVA suits or get a mod, it's not that difficult.

> > a bit silly in practice to have modsuits protect you from space in just a helmet and chestplate
> 
> This is not a reason to make it more difficult to obtain space protect in other ways.

It is, because consistency is important.

**Comment by Xackii** [comment]
> image
> 
Ye BOTH. But what if you only have 1 hand?

**Comment by Xackii** [comment]
if you only have one hand then you can't put on gloves but you will still receive damage from space because you have a hand and it is not covered

**Comment by Xackii** [comment]
In short, this PR seems to have been made for the sake of everyone using Eve or getting a gene from a geneticist instead of making a mod or potions in BenoXio

**Comment by mc-oofert** [comment]
@Xackii you can put on modsuit gloves with 1 hand

**Comment by Xackii** [comment]
Any other gloves?

**Comment by mc-oofert** [comment]
> Any other gloves?

all

**Comment by Xackii** [comment]
> > Any other gloves?
> 
> all

You can wear any gloves and any shoes (not just mod suits) if you are missing one arm or leg?

**Comment by mc-oofert** [comment]
> You can wear any gloves and any shoes (not just mod suits) if you are missing one arm or leg?

you can wear gloves onearmed yeah
not implemented for boots yet though

**Comment by Xackii** [comment]
Uh ok? If I don't have a leg, then I won't be able to get space proof from xenobio potion or hypernob crystal?

**Comment by YakumoChen** [comment]
winter coat covers your arms so the potion works for arms?
wouldn't that mean you can just potion the jumpsuit and it works?

**Comment by Sadboysuss** [comment]
People seem to keep forgetting that hyper nob crystals can be applied to jumpsuits, which cover your whole body

**Comment by YuliceTheDruid** [comment]
You should probably also up the amount of doses on the pressure potions if you want to make it so you need more coverings.

**Comment by Fikou** [comment]
> winter coat covers your arms so the potion works for arms? wouldn't that mean you can just potion the jumpsuit and it works?

probably

**Comment by GuillaumePrata** [comment]
Wouldn't you need to make the Atmos gloves pressure proof by default for the suit to work now?

**Comment by Fikou** [comment]
> Wouldn't you need to make the Atmos gloves pressure proof by default for the suit to work now?

the atmos firesuit covers your arms, so no

**Pull request merged**
