### PR TITLE
Fixes some window sizes

### PR DESCRIPTION
**Pull request by ghost**
Fixes the manifest having a horizontal scroll bar, which it shouldn't.
Fixes the new player setup window having a vertical scroll bar.
Fixes manifest not using paragraph tags instead of double breaks on the new player options.

Kinda new to this UI stuff, sorry.

ss 2014-12-28 at 04 22 41

### CODE REVIEW

**Comment by tkdrg** [comment]
Conflicts. Also this might conflict with carn's stuff, but i'm not sure.

**Comment by paprka** [comment]
Probably will

**Comment by paprka** [comment]
Conflicts fixed, unable to check if this conflicts with carn's PR due to it having conflicts with the master, but yeah.

**Comment by paprka** [comment]
Yeah just checked, this can be merged.

ss 2015-01-03 at 06 00 05

**Comment by paprka** [comment]
I'm not fixing the conflicts here again lol this should have been merged ages ago

**Comment by paprka** [comment]
The amount of butthurt I am about this not being merged and having to fix the conflicts a billion times is offset by how annoying it is to have these windows have scrollbars. Fucking merge this it changes 2 lines.

**Pull request merged**
