### PR TITLE
#19696 without the OP stuff

### PR DESCRIPTION
**Pull request by Bawhoppen**
People didn't want the special medkit I gave to doctor's in #19696, that wasn't even the reason why I made the PR, I mainly wanted to replace the dumb o2 kits inside the emergency closets with something moderately useful.

They only have two tricord pens with 10u of tricord each which is barely anything and really useless for anything save the emergencies they're intended for. I want to give some minor emergency healing ability.

The only reason I did that other medkit was because the sprite was already in the code for a purple medkit so I thought why not. 

:cl:
add: Emergency medkits now replace the o2 medkits in emergency closets.
/:cl:

(This PR still adds the special medkit to the code)

### CODE REVIEW

**Comment by PKPenguin321** [comment]
This was the part I didn't like about the last PR tho

**Comment by Bawhoppen** [comment]
don't know why you didn't still, I could atleast hear out the argument regarding the OP auto-injector

**Comment by PKPenguin321** [comment]
Because hugbox?

**Comment by Bawhoppen** [comment]
nothugbox

**Comment by PKPenguin321** [comment]
It is though?

**Comment by Bawhoppen** [comment]
its balance: rveenge

**Comment by PKPenguin321** [comment]
This reminds me of when defibs were new and people wanted to add single use defibs to emergency lockers?

**Comment by Bawhoppen** [comment]
that sounds OP and this is not OP

**Comment by TechnoAlchemisto** [comment]
healing items belong in medbay stop

**Comment by Bawhoppen** [comment]
there is NOTHING wrong with there be some **_minor_** healing items around the station for emergency

**Comment by Bawhoppen** [comment]
I really don't think I can emphasize more how minor they are

**Comment by TechnoAlchemisto** [comment]
they're unnecessary and bad literally everyone already has epi

**Comment by Ergovisavi** [comment]
> healing items belong in medbay stop

What is botany, chef, bartender and robotics

Joking aside, I agree. Leave healing to the doctors.

**Comment by KorPhaeron** [comment]
>What is botany, chef, bartender and robotics

All the more reason that players can go seek out another player who's job is to heal people rather than having healing stuff in lockers everywhere

**Comment by Bawhoppen** [comment]
what are you talking about? do you guys like not understand this PR or something

**Comment by Bawhoppen** [comment]
I'm sick of this bullshit, how is this making the game more hugbox? and how can people honestly say that tricord is good? have they ever used it ingame even?

**Comment by yackemflam** [comment]
Medbots injects you with tricord.

**Comment by TechnoAlchemisto** [comment]
bawhoppen youre losing it

**Comment by PKPenguin321** [comment]
>wants to add something that can keep you from dying everywhere in the station

>"yeah but it doesn't keep you from dying as much as it *could*"

>he honestly thinks this isn't hugbox

U need meds

**Comment by Bawhoppen** [comment]
what are you talking about reeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee

**Comment by yackemflam** [comment]
It has 10u of tricord and 10u of epipen in each pen
That will heal for ~3.2 damage per TICK if you are stable.
If you are in crit, it'll throw your oxydamage to 35 if you are above that, then starts healing you for ~5.2 damage per tick.

This is of course implying that you have taken a little of every damage (brute/burn/toxin/oxyloss).

Here's the problem.

Assistants/anyone who isn't a doc will just open every o2 closets and hoard the pens for themselves.
Making doctors even more useless than before since they can just inject 3 pens inside of themslves. putting them RIGHT under the OD threshold and start healing quickly since this is the same chem we use for MEDIBOTS, the doctor killer.

Epipens are fine enough.

So yes, everyone has their right to say that this is not ok.

**Comment by yackemflam** [comment]
Also, hugbox.

**Comment by Jalleo** [comment]
That is more a issue with powergamers than anything else to be honest.

**Pull request closed without merging**
