### PR TITLE
[s]Add pacifism checks for screwdriver/bottle attacks

### PR DESCRIPTION
**Pull request by Mickyan**
:cl: Mickyan
fix: Fixed pacifists being able to harm using bottles/screwdrivers
/:cl:
Smashing bottles/screwdriver to the eyes are unique attacks that needed a check

### CODE REVIEW

**Comment by vuonojenmustaturska** [comment]
remove pacifism when

**Comment by Mickyan** [comment]
when someone removes/reworks all of the things that use the pacifist trait

**Comment by XDTM** [comment]
why is pacifism not cool now what did i miss

**Comment by Mickyan** [comment]
If I had to guess it's overreacting because of #37511 and #37593

This check is as basic as it gets, it's just these items have their own snowflake attacks

**Comment by optimumtact** [comment]
hey look more snowflake code to fuck things up

:-1: why would you expect my position on this to change

**Comment by Mickyan** [comment]
I didn't, I expected you to understand the difference between trying to cover complex edge cases and literally clicking on someone with an easily acquired item

And also because there are literally dozens of checks like this for the clumsy trait and for some reason that never came up as being an issue

**Review by SpaceManiac — APPROVED** [review]
not as egregious as magically detecting that a locker contains a living being, not perfect, but better than eyestabbing cheating pacifism

**Comment by optimumtact** [comment]
the clumsy trait already existed and was inherited shit code

absolutely no reason to add more of this shit still :-1: very strongly

**Comment by Tlaltecuhtli** [comment]
just make pacifism remove your arms

**Comment by CPTANT** [comment]
The way these attacks work in the first place should be refactored.

**Comment by cacogen** [comment]
Would it be possible to check everytime a mob takes damage from an attack whether it's from a human with the pacifism trait and if it is then stop the attack?

**Comment by cacogen** [comment]
I don't think so, because you wouldn't have to add it to every weapon. We already have attack logs that show the ckeys of the attacker and victim, so how hard would it be to add a check for pacifism in the same place before letting the attack go through?

**Comment by Mickyan** [comment]
Yeah these checks are necessary because the attacks are snowflake code themselves and should be refactored. is_pointed already exists and would be perfect for eye stabbing and a breakable helper would be handy for more than just bottles. 
Need someone who knows exactly what they're doing to volunteer, though. Until then this is necessary.

**Comment by SpaceManiac** [comment]
Elaborate checks for elaborate situations are a no-go, snowflake attack checks are not great but must suffice until either pacifism is removed (which would be unfortunate) or attacks are under some unified system.

Naively adding the pacificism checks to the same place the attack log occurs won't work. Most code that logs attacks does so *after* the attack has already occurred. It'd be a mess to fix and it'd be better to rework the whole system.

**Pull request merged**
