### PR TITLE
Add kahki pants to the sec wardrobe

### PR DESCRIPTION
**Pull request by optimumtact**
:cl: oranges
add: Sec now has khaki pants for tacticoolness
/:cl:

I like pants

### CODE REVIEW

**Comment by CitrusGender** [comment]
harmless pr

**Comment by Bombpants** [comment]
Any pictures?

**Comment by SpaceManiac** [comment]
There's no shirt part, that's the undershirt visible

image

**Comment by Ratvar** [comment]
Add kahki skirts to the sec wardrobe #38086
add: Sec now has khaki skirts for tacticoolness

**Review by SpaceManiac — APPROVED** [review]

**Comment by yorii** [comment]
slirperyslorp

**Comment by Armhulen** [comment]
@yorii kor can't break my heart twice whatever

**Comment by KorPhaeron** [comment]
fetish content

**Pull request closed without merging**
