### PR TITLE
[READY] Yet more darkmode tweaks and fixes

### LINKED ISSUE #43280: Dark Mode Makes BYOND Donor Icons Look Bad!!
## Round ID:
104424

## Testmerges:
#42958: '[READY] Disarm Rework: Shove that Dickhead' by actioninja at commit f0af0d0e86 
#43142: 'Don't use megafauna in events' by subject217 at commit 0ade2949ec 
#43145: 'Makes strong booze more dangerous' by Mickyan at commit 0770b4b59c 
#42879: '[Test Me :) ] The Virtual Reality Hub' by Whoneedspacee at commit eb0c65f858 

## Reproduction:
1) Be BYOND donor
2) Result: Bad

(Look at all the light mode bleeding out of the icon)

### PR DESCRIPTION
**Pull request by actioninja**
## About The Pull Request
Bunch of small tweaks and fixes:
- Better byond icon for donors that looks fine in dark mode and better in light mode.
- Fixes to color in the admin ticket log.
- Better backend that makes changing colors easier
- Some slightly tweaked colors for easier readability in dark mode
- Default asay and custom ooc colors are now readable in both dark and light mode.

## Why It's Good For The Game

Fixes + nice
Fixes #43280

## Changelog
:cl:
fix: Lot of small darkmode fixes
/:cl:

TODO: maybe add a system for automatically inverting custom colors based on lightmode/darkmode if they're unreadable enough? probably too much effort.

### CODE REVIEW

**Comment by actioninja** [comment]
fuck you the build worked fine appveyor just sucks

**Comment by zxaber** [comment]
Add a line break and try it again?

**Review by ShizCalev — DISMISSED** [review]

**Comment by Angustmeta** [comment]
Haven't rested with this PR but I do feel most text is too dark for comfort on live.

**Comment by actioninja** [comment]
> Haven't rested with this PR but I do feel most text is too dark for comfort on live.

After playing with it for a while the default say color could be a bit brighter. going to tweak that.

**Pull request merged**
