### PR TITLE
All AI datum behaviors are now added using a wrapper

### PR DESCRIPTION
**Pull request by ghost**
NinjaNomNom added a proc called AddBehavior that was used in 1 place for monkeys, I made it so that every behavior now uses them and implemented them better with my design for AI controllers. This can be used to add arguments for specific behaviors, for example when you add a "Attack target" behavior, you can specify the target key in the blackboard to prevent needing a subtype for each behavior.

### CODE REVIEW

**Comment by AMonkeyThatCodes** [comment]
this should be tm'd @Mothblocks

**Comment by Mothblocks** [comment]
was this test merged

**Review by Mothblocks — CHANGES_REQUESTED** [review]
if this was test merged then it looks ok

**Comment by Mothblocks** [comment]
i meant approve

**Comment by Couls** [comment]
can confirm it's TMed on terry right now

**Comment by AnturK** [comment]
```Runtime in _ai_controller.dm, line 208: Behavior /list not found.``` Testmerge runtimes from TryFindWeapon -> queue_behavior

**Comment by AMonkeyThatCodes** [comment]
this doesnt sound like a basic mob bug

**Comment by AMonkeyThatCodes** [comment]
smash merge bro @Mothblocks trust me bro

**Comment by Mothblocks** [comment]
Bet

**Pull request merged**
