### PR TITLE
Mesons no longer show turfs on lavaland, but miners no longer need mesons to see minerals scanned by a mineral scanner through walls

### PR DESCRIPTION
**Pull request by ChangelingRain**
:cl: Joan
rscdel: Nanotrasen has taken a lower bid for their meson suppliers, and meson scanners will no longer display terrain layouts while on the planet.
tweak: However, they have discovered that, with some tweaks, mineral scanners will no longer actually require you to be wearing mesons.
tweak: The cheaper mesons will not completely remove reliance on light.
/:cl:

Mesons let you see tunnels and possibly avoid terrifying dangers by just mining around them; this has been a 'problem' of sorts for the entire existence of combat-mining.
The only reason mesons weren't removed was that we had no way to show minerals without either mesons, which show tunnels, or material scanners, which just show too much other stuff.

I solved that.

### CODE REVIEW

**Comment by Militaires** [comment]
so miners have fucking xray eyes and see EXACTLY where that ONE diamond is 15 tiles away

wew

**Comment by ChangelingRain** [comment]
If you have a mineral scanner.

**Comment by Militaires** [comment]
i guess that makes more sense

**Comment by ShadowDeath6** [comment]
this could actually make it less likely to run into megafauna since they emit light and mesons kind of nullified light

**Comment by Qbopper** [comment]
If you need a mineral scanner to see the minerals you might want to make that clearer in the PR, it initially sounded ike you can just see minerals at all times now and I was a bit confused

**Comment by kevinz000** [comment]
i'm going to go bribe engi to give me mesons <3

**Comment by FantasticFwoosh** [comment]
It doesn't really make a difference since you can pick up mesons & night vision variant from RnD anyway, if anything you should make a nerf to the meson object in not being able to see through rocks.

**Comment by Kromgar** [comment]
Using Kinetic Accelerators are really annyoing you have to click the asteroid tile you want to mine now. You ahve to be standing away from the asteroid now its so fucking annoying cant do it right up close or you bash the asteroid with your ka

**Comment by FantasticFwoosh** [comment]
@Kromgar if you don't carry a pick, even a compact pick that is supplied to you then you probably deserve it.

**Comment by ShadowDeath6** [comment]
Can't you click the highlighted mineral through the wall to fire at it?

**Comment by Kromgar** [comment]
@ShadowDeath6 What highlighted minerals? I see jack shit except for the closest mineral wall

**Comment by ShadowDeath6** [comment]
>tweak: You can see minerals scanned by a mineral scanner through walls even without mesons.

**Comment by ChangelingRain** [comment]
Also, you should be able to fire at darkness since we have the click catcher.

**Comment by adamkad1** [comment]
i say, this makes no goddamn sense, but it might make mining as golem easier cause youll see all dem mineralz

**Comment by Repukan** [comment]
Just nerfs miners and buffs ghost roles 👎

**Comment by octareenroon91** [comment]
>fix: Too many miners have been surviving

**Comment by Repukan** [comment]
If this is due to a change in the function of scanners then remove the golem ship mesons too.

**Comment by ChangelingRain** [comment]
Golems, uh, don't HAVE mesons? They can buy GAR mesons, but I removed those so they shouldn't have default mesons.

**Comment by Repukan** [comment]
They don't?

Uh soz then

**Comment by jughu** [comment]
ADMINHELP:miners using x-ray mod and mined all the diamonds in the area!!!

**Comment by KorPhaeron** [comment]
Snowflaking them to not work on lavaland seems very odd and frustrating

**Comment by ChangelingRain** [comment]
Well, I can't practically remove them from everyone since apparently "engineers need mesons" and "engineers need the turf vision", so this is compromise. Of a sort.

**Comment by VeryRealAccount** [comment]
Maybe that means your change is garbage, then.

**Comment by ChangelingRain** [comment]
You'll get ruins with secret rooms and like it.

**Comment by VeryRealAccount** [comment]
Yeah but they can only see like 3 tiles into a wall.  There are plenty of times when you see a silver node you wouldn't have gotten if you had just kept doing your standard mining strategy with Mesons.

**Comment by GunHog** [comment]
I do not feel this change is necessary to make mining more atmospheric, as MSO's change to mesons and NV equipment did this already.

**Comment by ChangelingRain** [comment]
>Yeah but they can only see like 3 tiles into a wall. There are plenty of times when you see a silver node you wouldn't have gotten if you had just kept doing your standard mining strategy with Mesons.

??? That's not even a response to ruins with secret rooms being literally impossible right now.

>I do not feel this change is necessary to make mining more atmospheric, as MSO's change to mesons and NV equipment did this already.

It's not to make mining more atmospheric, though it does do that: it's to make tunnels not something you can see in advance, and to make ruins with secret areas actually possible.

**Comment by uraniummeltdown** [comment]
The death rate for miners is already very high even with their mesons, let's not turn Lavaland into Dark Souls bullshit

**Comment by Sligneris** [comment]
How do you imagine plasma cutters to work with this?

**Comment by Core0verload** [comment]
Shit change, and that's not to mention snowflakiness. And if you need secret rooms, map ruins with a lot of rooms so the fact that one of them is not connected wouldn't be that obvious.

**Comment by Kromgar** [comment]
@ChangelingRain maybe if tunnels were more than just open spaces with monsters in them then yeah maybe? Like instead you mined into a pocket of lava and get blasted with molten rock or you strike an aquifer

**Comment by ChangelingRain** [comment]
>How do you imagine plasma cutters to work with this?

Same as they do currently, since you can still see minerals in the same range.

>And if you need secret rooms, map ruins with a lot of rooms so the fact that one of them is not connected wouldn't be that obvious.

That effectively limits all secrets to pretty huge ruins, and those ruins would probably need a special design to make the entranceless room not obvious. It sounds greatly impractical from a mapping standpoint alone.

**Comment by Repukan** [comment]
Are there even any maps of such kind?

**Comment by ChangelingRain** [comment]
No, because the mappers of the time understood how mesons worked.

**Comment by adamkad1** [comment]
Meh, i like this.

**Comment by KorPhaeron** [comment]
Is it possible to just remove meson night vision in general instead?

**Comment by ChangelingRain** [comment]
I can do that provided you'll actually merge it like that and also want to get pointed at when asked "why do my mesons now remove light anymore who did this!"

**Comment by adamkad1** [comment]
wow, your making this sooo confusing

**Comment by VeryRealAccount** [comment]
Would it be possible to still give the x-ray (not sure how to better describe it) effect on just the rocks that can be mined?  Instead of showing all walls.

**Comment by ChangelingRain** [comment]
I'm not sure what you mean, but the mineral scanner that miners have will show nearby minerals. You don't need mesons or whatever for that with this pr.

**Comment by Sligneris** [comment]
Wouldn't it be better to just give miners nightvision goggles given the circumstances? Don't get me wrong, I see you reasoning for ruins, but there's no need to turn mining into falling into chasms simulator.

**Comment by ChangelingRain** [comment]
Yeah, probably; the main objective of this PR is to keep miners from seeing tunnel/ruin layouts.
Maybe I'll change chasms to leave the glowing tendril object+center turf, so you can see them always.

**Comment by XDTM** [comment]
@Sligneris makes a good point, we should replace mesons with some other equipment. It might be enough to prevent powergaming without making snowflake checks on the zlevel.

**Comment by ChangelingRain** [comment]
Frankly I seriously doubt good miners like @Repukan or @Kromgar will go without mesons if they can avoid it, since the advantage mesons give in not being surprised when you come up on a potentially hostile ruin/lava river/any other stuff that's really obvious if you can see turfs is massive.

**Comment by Core0verload** [comment]
Typical /tg/ coders: making up balance problems to implement shit solutions.

**Comment by Hatfish** [comment]
So a handful of players will powergame to optimize their round, should we really balance all of mining around so few people?

**Comment by ChangelingRain** [comment]
<sarcasm\>Why not? We do it for other jobs.</sarcasm\>
In actual seriousness, I think the bonus mesons give while mining is too much to allow at all, even if, especially if, you're a veteran miner.

**Comment by Core0verload** [comment]
Lavaland has much bigger balance problems than mesons, such as Bubblegums spawning too close to base entrance and rekking miners before they can even suit up. But nooooo, let's make big deal out of it and remove some items that make life safer from a job that has 98% newbie mortality rate!

**Comment by Hatfish** [comment]
I just don't see how this is going to improve mining at all, tunnels aren't anything more than a minor annoyance if you're actually trying to mine and are nothing but good if you're hunting monsters, and there aren't really any ruins that would benefit from this yet.  Plus, there's the excellent point of chasms becoming even more of a pain since it's difficult to pick them out in low light already anyways when every tile is some shade of black.

**Comment by ChangelingRain** [comment]
>98% newbie mortality rate!

You're gonna need some stats to back that shit up, m8.

**Comment by ChangelingRain** [comment]
>Plus, there's the excellent point of chasms becoming even more of a pain since it's difficult to pick them out in low light already anyways when every tile is some shade of black.

Do you want me to fix this in THIS pr, or in another pr?

**Comment by obscolene** [comment]
revert mesons completely to how they were before. there was literally nothing wrong with it, and everyone hates this shit. there's no reason for this, at all.

**Comment by Incomptinence** [comment]
Oh yeah we want miners to mine less and tendril hunt more. 

I hate every time this dumb atmospheric shit is pulled.

**Comment by ShadowDimentio** [comment]
This has been tried fifty times before and it's been reverted every single time.

Stop.

**Comment by ChangelingRain** [comment]
It has not, in fact, been tried 50 times before. Unless you can link me to prs for it?

**Comment by KorPhaeron** [comment]
I tried giving them material goggles and people didn't like it

**Comment by ChangelingRain** [comment]
Okay that's one pr

**Comment by VeryRealAccount** [comment]
I find it hilarious you use Repukan as an example when he's a powergamer.  And thus isn't even the target for the atmospheric shit (too busy hunting them valids).

**Comment by ChangelingRain** [comment]
Why would you find that hilarious? As powerqamers I would fully expect them to grab mesons if they could. That's, in fact, why I mentioned him.

**Comment by Repukan** [comment]
>Become proficient in not dying in the area with high mortality rates
>Express concerns relating to how it might fuck up newer miners
>But because I'm good my input is invalid

Fuck👏 Your 👏couch👏

**Comment by Repukan** [comment]
In fact one of my first posts was complaining about how this would shoot up the mortality rates of miners but I guess you couldn't read that well with your head so far up your ass.

**Comment by ChangelingRain** [comment]
Hey, if you've got an idea to give people new to mining mesons without it feeling awful when they have to lose them, I'm up for it.

**Comment by ShadowDeath6** [comment]
all I can tell this changing is making miners more prone to walking into chasms which is really shitty and unfun 
they already see megafauna and lava through walls due to the lighting they emit, they already need light / night vision to see regular mining mobs, and if they have night vision mesons then they already have access to night vision goggles which will serve the exact same purpose if this pr goes through

I guess it helps with secret rooms when making ruins but it takes one go-through and you'll know what the ruin holds for every time after so it doesn't change that much

**Comment by ChangelingRain** [comment]
frankly chasms are kind of shitty and unfun as-is but I do have a solution pr, #27479, which makes chasms basically always somewhat lit.

**Comment by MMMiracles** [comment]
Secrets are a secret until the miner discovers the ruin for their first time or glances at it as a ghost. Gimping a pretty vital part of a job to turn it into a mess of darkness for the sake of 'SECRECY' and 'ATMOSPHERE' on an open-source codebase is dumb.

Unless you also plan on pushing limited ghost vision on lavaland (not like that already failed before) and moving ruins off of the codebase to be loaded in and prevent people from just looking at the .dmm file, this change is an unnecessary hindrance.

**Comment by ChangelingRain** [comment]
Oh right I should do limited ghost vision too

**Comment by Repukan** [comment]
>limited ghost vision

Whoa hold the fuck up

**Comment by ChangelingRain** [comment]
surprise I'm kor in disguise

**Comment by GunHog** [comment]
Normally I would think a response like that is in sarcasm, but seeing as the limited ghost exploration has already been proposed by Kor, it is probably 100% serious.

**Comment by ChangelingRain** [comment]
Waiting on one of these PRs, since invisible chasms suck: #27496 #27526

**Comment by AmakusaNagano** [comment]
I will be very honest, ChangelingRain...

Before this change, we had an already "hardcore mode" place called Lavaland. 
Where it was almost certain that a newbie would die.
But also where we frequently saw some ore returning.

It was already a place where a newbie miner would stumble upon a creature, get caught by surprise and die... But at least was where they could keep themselves "safer" by avoiding the tunnels.
Then slowly get the courage to fight off the monsters or explore deeper.
 - So effectively, it had an "easy mode", that could grant some not-so-frustrating-results in those cases.

After? This changed to a much harder difficulty.
To the point I had to constantly replace miners while being a cargo tech, quartermaster or even when in other roles.... - The whole station was screaming for ore non-stop, and someone had to do something.

Also, keep in mind that the lag might not be perceived by you when testing those changes.
It was already another element before. But now it's very exacerbated...

So - specially because of the LAG - your change to mesons made too easy to fall on lava when digging with the diamond pick-axe (one of the best tools a miner can get with no research).
And we aren't seeing a lot of plasma cutters... They need ore to be made, right?

Lavaland - as a whole - might be "more immersive" now.
And this change might "give you the possibility of implementing secret rooms" (that actually could be implemented in many other ways).

But mining on Lavaland - and by extension working on cargo, depending on research,... turned into much more frustrating gaming experiences.

But don't take my word for an absolute truth. 
Just ghost, stick to miners while listening to cargo or research and see by yourself.
Or try to mine when the server is lagging.

**Comment by ChangelingRain** [comment]
Do you think making lava show up on mining scanners would be a good idea for this or a bad idea?

>And this change might "give you the possibility of implementing secret rooms" (that actually could be implemented in many other ways).

a lot of people say this but it's really impractical to make secret rooms when miners can see all the terrain at all times, you know?

**Comment by GunHog** [comment]
Please consider if these secret ruin rooms are really worth this, when none have even been mapped. Also, there would need to be a lot of these rooms OR controlled by RNG, to avoid the surprise aspect being lost within the first two weeks for most repeat mining players. 

It needs to be something interesting and actually rewarding to explore. If you are going to degrade the entire experience for the sake of this one feature, it needs to be worth the cost. As of this moment, I do not see the merit of it. Not concepts or ideas, but backed by actual mapping.

**Comment by octareenroon91** [comment]
There is a sense in which we're talking about a stub of changes for unseen future additions.

**Comment by ChangelingRain** [comment]
>Oh right I should do limited ghost vision too

I can't actually do this just FYI, since my solution would either require disabling the rightclick menu, which is impossible, or making ruins with massive ghost-prevention fields, which is really annoying to ghosts and thus undesirable; my solution would have just been static over parts of ruins that a human hasn't passed through yet

**Comment by Repukan** [comment]
👻

**Comment by VeryRealAccount** [comment]
I see you went ahead with this garbage despite the popular opinion being against you.  It's not like you could be wrong after all.

**Comment by ShadowDeath6** [comment]
1:5 dislike ratio but it gets merged anyway? Weird.

**Comment by Core0verload** [comment]
this is retarded

**Comment by Core0verload** [comment]
This is retarded, and "Revert" button broke on me. Can anyone revert this manually?

**Comment by Repukan** [comment]
Sure right here my nigga

🍼🍼🍼🍼🍼🍼

**Comment by KorPhaeron** [comment]
Leo why did you ask me if you could merge this if you were gonna merge it anyway after I said no

**Comment by lzimann** [comment]
You never really said no though. Plus, I tested this myself and wasn't even bad as people are making it to be. If it gets really bad I will open a revert myself.

**Comment by KorPhaeron** [comment]
<LeoZ> pineapples will you get mad at me
<LeoZ> if i merge it
<LeoZ> i tested earlier today and it isn't so bad
<pineapples> probably

<LeoZ> hey kor
<LeoZ> do you mind if i make a lot of people probably unhappy to make a single person happy
<pineapples> yes

:tada:

**Comment by Sligneris** [comment]
>/> do you mind if i make a lot of people probably unhappy to make a single person happy

I'm not sure what to say about this.

**Comment by lzimann** [comment]
More of a joke than anything, so you don't really have to say anything

**Comment by Incomptinence** [comment]
Uh don't the power gamers purposefully seek tendril and boss combat with their gps for the huge loot?

When is miners bringing in ore instead of seeking loot power gaming on their end? 

Why would the 3 professional lavaland guys be going in blind as an ashligger? 

Like the pros cut through tunnels because they find the mobs mindlessly easy and not worth avoiding. 

If you care about miner powergaming hit them in the gps finding all bosses and monsters instead of pulling this same old DARKNESS OOH SPOOKY shit.

**Comment by VeryRealAccount** [comment]
How is it not really bad already if people are 5-to-1 against it?

**Comment by ChangelingRain** [comment]
>How is it not really bad already if people are 5-to-1 against it?

Small sample size.

**Comment by octareenroon91** [comment]
>Small sample size.

>n=32

**Comment by Qbopper** [comment]
I mean I'd say that you both have a point

The github is a very small percentage of the total playerbase, but on the other hand there's a LOT of votes on this PR (compared to other big ones I've seen)

**Comment by Repukan** [comment]
Lem meth eat cake

**Comment by KorPhaeron** [comment]
Mesons not working on lavaland
Atmospheric!: 3
Unfun!: 15
Don't care: 8

Every time I run this poll I get similar results, it is still immensely unpopular 2 weeks out

**Comment by GunHog** [comment]
It is impossible to get a nerf this heavy reverted, Kor. :cry:

**Comment by MSBeholder** [comment]
Since I had to come here just couldn't resist commenting.

> Mesons let you see tunnels and possibly avoid terrifying dangers by just mining around them; this has been a 'problem' of sorts for the entire existence of combat-mining.

Is that a serious problem?
Very important station role not surprise instakilled?'
While other server even implemented a fauna detector?

By the holy cheesy holey cheese my dear.
So you are dong it wrong. 
Very wrong.

It's not enough yet to represent NanoTrasen total lack of care about the very core activity of that crappy plasma research facility on space!
Add random failures code to every mining gear for reflecting that properly!

KAs and Resonators should have a 20% chance of blowing up, zapping the user or backfiring on every trigger pull.

Of three miners, one should spawn with a healing auto-injector loaded with a random harmful chemical with double the chances of it being cyanide.

35% of the shelter capsules must contain an aquarium of space sharks with lasers in place of what they should.

Then pick axes are still too reliable. 
Make them wear on every strike and after 20 to 30 strikes they should break, turning into wooden poles while the metal head is launched stray at the closest non-hostile.
Said head is to be an armor piercing projectile with 90% chance of embedding.

Also satchels should rupture are random, dumping all ore straight on the miner's feet and causing 5 of de-limbing brute damage by each piece of ore with no max cap to both legs.

Healing medikits on base should rarely contain actual healing items.

95% of all food is to be bland, spoiled or spiked with dangerous stuff.

And leave an official Nanotrasen note by every mining locker.
['Due to the space recession we were forced to replace our standard equipment suppliers.
We extensively and thoroughly tested alternative brands and carefully selected only the suitable replacements fully approved by our quality committee.
If any nonconformity is found, please report to our in-charge quality officer by your PDA messenger.]

Then finally put the cherry bomb on top.
Add a dummy contact on every miner's PDA.
Random human name with 'Remote Quality Officer' role.
If messaged by a miner, will answer with a text about 'inviting them to participate on a quality audit' and teleport said miner to a pool of lava surrounded by titanium walls.

> I solved that.

Nein nein nein nein NEIN. 
Not yet.
Miners are still surviving sometimes.

More effort is required. Aim for a greater standard.
100% of miner casualties every round.

> You'll get ruins with secret rooms and like it.
> a lot of people say this but it's really impractical to make secret rooms when miners can see all the terrain at all times, you know?

Whoa. 

What?

Was that the point instead? 

Gadzocks. 

So redact what I just wrote above then.

No real point in secret rooms and heavy anti-spoofing unneeded nerf if they'll still learn a dungeon design by pure game-play experience.

Only merit on meson scanner nerf was 'making harder to find any ruins'.

Still unneeded since it's not where the main game happen and by the fact that said ruins mostly contain only gimmicks, dangerous features or stuff on par with what's found at station.

>Yeah, probably; the main objective of this PR is to keep miners from seeing tunnel/ruin layouts.

Are you afraid of tweaking the whole 'sight code'? 
To add 'meson-proof' walls and doors?
Or 'disappear on unobstructed line of sight, create floor and drop items' walls instead?
If so then there's plenty of code to spawn entire structures and randomize it all.
Just a matter of *POOF* and a wild secret room appears inside any solid structure.
Like any good shelter capsule but could work from a 'secret door mechanism' or something.

Still n that a perimeter of 'signal-on-destruction rock walls' with a 'structure spawner' on the middle would result in surprise ruins popping up only when dug up.

________________________________________________________________________________________
P S

Indeed I loved the insights gained by peeking at this sweet piece of code. 
Be certain of that. 
T#X 4 7#3 (0D3! <3

**Pull request merged**
