### PR TITLE
Decreases the minimum age to 16.

### PR DESCRIPTION
**Pull request by Krysonism**
## About The Pull Request

This PR decreases the minimum age to 16.

## Why It's Good For The Game
A future where unaccountable megacorporations rule the solar system and collective action is illegal would logically mean the return of all the horrors of the gilded age, though more severe.

One of those horrors were of course; child labour, 

Therefor, in the interest of building an interesting and believable setting for our game, SS13 should also have child labour.

## Changelog
:cl:
balance: Decreased the minimum character age to 16.
/:cl:

### CODE REVIEW

**Comment by manofpepsi** [comment]
image

**Comment by interestingusernam3** [comment]
@manofpepsi 
Screenshot 2021-06-26 at 22-17-22 Rules - tg station 13 Wiki

**Comment by Moltovz** [comment]
_**Whatthefuck**_

**Comment by LemonInTheDark** [comment]
I don't want this. I think it's just a reaction to goof's pr, and don't consider it good faith

In short, cringe, bluepilled

**Comment by Krysonism** [comment]
> image


Players != characters. 

You are not your character.

**Comment by Krysonism** [comment]
> 
> 
> I don't want this. I think it's just a reaction to goof's pr, and don't consider it good faith
> 
> In short, cringe, bluepilled

It is both in reaction to goofs PR and in good faith. I honestly believe this.

**Comment by Stalkeros2** [comment]
MAN WHAT THE FUCK NO NO NO NO NO NO DON'T YOU DARE

**Comment by Mothblocks** [comment]
u guys know the minimum age is already 17, right?

**Comment by bluetshirtguy** [comment]
> u guys know the minimum age is already 17, right?

Doesn't mean we should make it lower.

**Comment by ondrej008** [comment]
make it 15

**Comment by Stalkeros2** [comment]
image

**Comment by Kylerace** [comment]
since you made this as an anti goof kneejerk pr im closing this. having more underage player characters is not what the game needs

**Comment by Stalkeros2** [comment]
Based and redpilled.

**Comment by Kylerace** [comment]
> 
> 
> make it 15

can you dont

**Comment by MaintClown** [comment]
> since you made this as an anti goof kneejerk pr im closing this. having more underage player characters is not what the game needs

Based.

**Comment by Krysonism** [comment]
> since you made this as an anti goof kneejerk pr im closing this. 

We can't suggest alternative PRs to changes we disagree with now?

>having more underage player characters is not what the game needs
Why not?

The US supreme court just greenlit Nestle's use of child slavery on cocoa farms.

A corporation with no oversight would inevitable use child labour.

**Comment by Real-MAGNUM** [comment]
viperious alt?

**Comment by SharkLordSatan** [comment]
What the honest to god fuck?

**Pull request closed without merging**
