### PR TITLE
DNAConsole interface refactor

### PR DESCRIPTION
**Pull request by mordent-goonstation**
## About The Pull Request

Attempts a reasonable "good faith" attempt at splitting up a tgui interface (DnaConsole) into separate files, i.e. not being overzealous with splitting but doing so at logical points that improve code maintenance/structure rather than "for the sake of it".

Draft PR as intended to support #57825. This PR would need tidying up after that gets merged.

As noted in the main PR this does increase the bundle size, in this case from 733.75 KB to 737.7 KB, with the DnaConsole interface now at 28.81 KB instead of 25.47 KB before (~13% increase). Note that the bundle increased by 3.95 KB, while the DnaConsole increased by 3.34 KB. I can't explain the additional 0.61 KB that was added outside of DnaConsole, as I attempted to not touch the inner working of the files. Happy to look into further if needed.

Please note that I am *not* a tgstation player, and while I interacted with the DNA Console in a local build, poking at various buttons and the like, it's entirely possible I missed something as I don't truly know how it works.

## Why It's Good For The Game

Breaks up behemoth interface file into logical chunks, allowing for easier code maintenance.

## Changelog
:cl: Mordent
refactor: Split DnaConsole into separate files.
/:cl:

### CODE REVIEW

**Comment by stylemistake** [comment]
Upholding, this just needs a rebase, somehow this PR fly past my radar.

**Comment by optimumtact** [comment]
@mordent-goonstation @stylemistake hello?

**Comment by 81Denton** [comment]
@mordent-goonstation This PR has been stale for a while, please ping stylemistake or any other maintainer when you're ready to finish it.

**Comment by mordent-goonstation** [comment]
@stylemistake Sorry, just clearing my notifications queue and saw this. Is this PR something you want? If so, I'll do the rebase and stuff.

**Comment by stylemistake** [comment]
Yes

**Pull request closed without merging**
