### PR TITLE
Adds memos to the server bots

### PR DESCRIPTION
**Pull request by tkdrg**
People want this apparently

### CODE REVIEW

**Comment by optimumtact** [comment]
:-1: there are open source bots that do this much more effectively

**Comment by Iamgoofball** [comment]
Yeah, we have Pirou already, we don't need memos on these guys too.

**Comment by optimumtact** [comment]
Goof this is for admin bus, but your point does prove that there are bots for this job already.

As well as the memoserv.

**Comment by MrStonedOne** [comment]
@Iamgoofball one, pirou is down a lot, two, pirou isn't in #adminbus or the headmin channel.

@optimumtact this is an open source bot, shh now.

**Comment by tkdrg** [comment]
this is redundant now

**Comment by Chocobro** [comment]
@MrStonedOne
pirou responds to /invite commands
did you even try that

**Comment by Shadowlight213** [comment]
Why was this closed? Adminbus still doesn't have a memo bot.

**Comment by tkdrg** [comment]
I PMed my patch to @MrStonedOne quite a while ago. He probably hasn't had the time to put it live yet.

**Pull request closed without merging**
