### PR TITLE
Changes Admin OOC color to use Magenta

### PR DESCRIPTION
**Pull request by Ikarrus**
(Image is slightly outdated but uses the same colors)
screenshot 2015-07-03 09 33 42
This makes it stand out more from attack text, warning text, and security radio text.

### CODE REVIEW

**Comment by Miauw62** [comment]
fabulous

**Comment by Steelpoint** [comment]
I personally prefer red.

Is there a way to make this a option in the set up menu?

**Comment by Kelenius** [comment]
MY EYES.

MY FUCKING EYES.

PLEASE NO.

**Comment by MrPerson** [comment]
I was a bit worried that the color wouldn't be 'red' enough but that color seems great.

**Comment by SconesC** [comment]
This looks terrible, why change it from our current dark red? This looks extremely similar to AI private, and it not a Security color. The current color is easily distinguishable from the other departments, and is the iconic Security red shade.

**Comment by demonfiren** [comment]
Red is more typical (although this might accurately represent how gay Sec is.) Please, don't change.

**Comment by SconesC** [comment]
votez

**Comment by Ikarrus** [comment]
Admins use magenta now, not sec radio.

**Comment by SconesC** [comment]
:+1:

**Comment by Fox-McCloud** [comment]
Better red than dead(min).

**Comment by Jordie0608** [comment]
It's worth pointing out this will have no effect upon admins choosing their own OOC color when the config to do so is enabled; only the default admin OOC color.

**Comment by GunHog** [comment]
Note: AI Private is also magenta.

**Comment by optimumtact** [comment]
It looks poo brown, I like it

**Comment by Ikarrus** [comment]
Remaking in #10379 as it's changed considerably since I opened this one.

**Pull request closed without merging**
