### PR TITLE
Adds Bull Terriers

### PR DESCRIPTION
**Pull request by ishitbyabullet**
## About The Pull Request
The Bull Terrier is a breed of dog in the terrier family.

Bull terriers are finally able to added thanks to sprites being made. Sadly, I could only PR the sprites that have **no soul** since it would just be redundant to add the ian resprite ones which look worse **(but have soul)**.

**_Pet.dmi mob sprites made by Memager_**

## Why It's Good For The Game
As there is currently great debates over _(completely different)_ dogs, now is the best time to consider adding a bull terrier into the game. Besides that, he serves as an additional pet.

## Changelog
:cl: Bald People
add: Bull terriers are now added into the game. Buy one at your local cargo department today.
/:cl:

### CODE REVIEW

**Comment by Rohesie** [comment]
@Twaticus

**Comment by kingofkosmos** [comment]
Couldn't it be a healthier dog breed, like golden retriever or something?

**Review by Twaticus — APPROVED** [review]
hi walter

**Comment by san7890** [comment]
> Couldn't it be a healthier dog breed, like golden retriever or something?

shut up it's walter time

**Pull request merged**
