### PR TITLE
Festival Sect Expansion: New Tunes, New Rites, Cogitandi Fidis

### PR DESCRIPTION
**Pull request by tralezab**
### Cogitandi Fidis

Creates a holy violin that gives an analysis of songs played on it. This lets you check how long the song is for final effects, to make sure they trigger without the hassle of trying a rite with a song until you get one that works. 20 Favor, looks neat too!

### Portable Song Tuning

Rite to empower an instrument with the ability to invoke specifically song tuning rites, 5 charges before you need to go back to a proper altar. Helps a chaplain stay on the move, since songs are interruptable and sometimes an altar can be incredibly far. 10 Favor for 5 charges.

### Illuminating Solo

image

New free invocation that lets you light up the way with your music! The finishing effect applies a weaker glow to all listeners for a minute.

### Other Misc Changes

The threshold for getting a final effect on a song is now lower, 220 -> 170. As a reminder, this threshold is lines * tempo. I think the threshold was simply too high

## Why It's Good For The Game

Changes were made from https://tgstation13.org/phpBB/viewtopic.php?f=10&t=35381 statistics and feedback about sects. I think, overall, Festival Sect is in a very good place and doesn't need a whole lot but a few rites that help with a quality of life would really cut down on the amount of time a chappy is spending doing nothing but running allllll the way back to the chapel to load up some new songs

## Changelog
:cl:
add: Festival Sect has 3 new rites: Cogitandi Fidis, Portable Song Tuning, and Illuminating Solo.
balance: lowers threshold for triggering a final effect. Consult your Cogitandi Fidis for more information
/:cl:

### CODE REVIEW

**Comment by Eronymun** [comment]
This is good! I didn't even consider the travel time but it's true the biggest headache of the sect is finishing your song and then breaking the flow of whatever you are doing to go back and restock on your next holy song.

I think I mentioned this before but I hope the new instrument works like the synth does, so that any instrument can be played on it and it's sounds can be adjusted in real time.

**Comment by tralezab** [comment]
Should it? I made the violin more as, it was easy to work with songs when they are in their natural habitat codewise. I could make the violin work as a synth, I just imagined people would prefer to use the instrument they chose at the beginning over it.

**Comment by deathrobotpunch** [comment]
I think honourbound sect needs some love too,  this is a good PR and makes festival sect a little less repetetive

**Comment by tralezab** [comment]
I'm touching one of the sects in the Top 3 where I am confident there are minor problems first to get comfortable, then I'm tackling one of the nasty naaasty gunky sects. But I think this is overall a pretty safe pr

**Review by Wallemations — APPROVED** [review]

**Review by Ghommie — APPROVED** [review]

**Pull request merged**
