### PR TITLE
stops bots crashing

### PR DESCRIPTION
**Pull request by optimumtact**
Changes the code to use the python logger library which will handle this all for us

👌

### CODE REVIEW

**Comment by lzimann** [comment]
thanks fam

**Comment by xxalpha** [comment]
👌 👌 👌 👌 👌 👌 👌 👌 👌 👌 👌 👌

**Comment by Core0verload** [comment]
oranges is somehow useful? HOW'S THAT POSSIBLE?

**Comment by PKPenguin321** [comment]
you're quite a rude dude

**Comment by Zilenan91** [comment]
:cleanbot:

**Comment by optimumtact** [comment]
haters gonna hate

**Pull request merged**
