### PR TITLE
Guvax is slower if above 5 servants

### PR DESCRIPTION
**Pull request by ChangelingRain**
:cl: Joan
experiment: Guvax now invokes 1 second faster(5 seconds), but is 0.75 seconds slower for each scripture-valid servant above 5, up to a maximum of 15 seconds.
/:cl:

Basically, if you have a lot of servants guvax becomes painfully slow. Where's your base, why aren't you summoning ratvar already.

### CODE REVIEW

**Comment by Man-Shroom-** [comment]
are you meant to summon ratvar when you hit 5?

**Comment by ChangelingRain** [comment]
No, but by the time you have 12 you should be ready to, and have other, slightly faster methods of converting. Also note that A this doesn't count cogscarabs or suchlike and B at 6 servants it's the same as it is currently so this should actually be a buff.

**Comment by InsaneHyena** [comment]
> Let's make converting cyborgs even more impossible

**Comment by ChangelingRain** [comment]
Unless you have 7+ servants, it's easier, and if you have 7+ you have access to the spear throw+judicial visor stun combo which makes it possible to convert cyborgs even if you have the 19 servants needed to max out the invoke time.

**Pull request merged**
