### PR TITLE
Fixes Ice Slipping, Refactors noslip mechanics, Allows magboots to prevent slip slides (but not the slip itself)

### LINKED ISSUE #73946: Slip nerf PR from like 4 years ago broke ice slipping
## Reproduction:

https://github.com/tgstation/tgstation/pull/41068

image

So ice slipping relied on this being a `Stun` - 
Knocked down they can't slip again, breaking the ice slip mechanic.

### PR DESCRIPTION
**Pull request by MrMelbert**
## About The Pull Request

Code changes: 

- Fixes #73946 , Ice Slipping not going forever as intended
    - Detailed in the issue report. Ice slide slip was replaced from a stun to a knockdown, but it relied on it being a stun to function. I replaced it back with an immobilize and incapacitate, reduced to 1 second to prevent cheese.

- Refactors noslip mechanics
    - Changes noslip and noslip_ice from a clothing flag to a clothing trait, as the trait already existed and was used by MODsuits. Also added noslip_slide, which prevents all sliding from slips like lube. 

- Refactors magboots
    - Refactored and modernized magboot code. Mostly cleanup, like using base icon state, updating appearance, etc. 

- Fixes speed potioned magboots not maintaining the speed boost after a toggle

- Adds a helper for adding or removing clothing traits from existing, (potentially) worn items. 

- `TRAIT_NEGATE_GRAVITY` now always updates gravity on signal, no longer requiring a manual call after. 

Balance change: 

- Magboots now prevent sliding on permafrost (outside icebox).  
   - This is mainly to give them more of a purpose on Icebox. 
- Magboot snow prevent sliding on ice (or lube). You will still slip. 
   - Slipping over ice or lube will knock you down as before, but will not send you across the room. 
   - See https://tgstation13.org/phpBB/viewtopic.php?t=33217. 

## Why It's Good For The Game

Magboots justification: 

This makes Magboots much less of a "noob trab" for engineers fire-fighting in the Supermatter room. Most engineers believe themselves to be completely save to the Supermatter's pull with magboots, however "wet ice" will still send you flying into the crystal. 

I think it is an inconsistency, seeing as it protects you from other forms of forced movement like gravitational pulls. However making them pure no-slip seemed a bit too far to me, so the knockdown still occurs. 

## Changelog

:cl: Melbert
balance: Magboots will now protect you from sliding on ice. It will not stop the slip, though.
fix: "Ice sliding" (from patches of permafrost ice) will now correctly slide you until you reach a non-ice patch. 
fix: Speed potioned magboots maintain their speed booster after toggling them 
refactor: Refactored magboots. 
refactor: Refactored noslip mechanics. 
/:cl:

### CODE REVIEW

**Comment by Sealed101** [comment]
i kind of remember there being an issue with magboots that if you were to apply a speed potion to them, the effect would only apply to the state of the boots that they were on when you've applied the speed potion. so speedpotting them while they're off wouldn't remove the slowdown from when they're on. or something along those lines

was that fixed? (or was that a thing even i'm not sure)

**Comment by Profakos** [comment]
Hm, probably not then, it only has the SLIDE flag, not SLIDE_ICE. Wait a minute, there are two different ice slips. TURF_WET_ICE only adds SLIDE, TURF_WET_PERMAFROST adds SLIDE_ICE. Maybe that is why TURF_WET_SUPERLUBE is not working as intended, it only add SLIDE?

**Comment by Profakos** [comment]
Confirmed, this has also fixed the "Trial Of Honkitude". 👍

**Comment by Profakos** [comment]
I heard reports that ice slip has been broken again. Frozen water vapour at least. I will try to reproduce it to make sure its not a downstream issue, and create a new issue if it is indeed back...

**Comment by san7890** [comment]
Make a unit test if it's reproducible

**Pull request merged**
