### PR TITLE
Add the ability to use blips as your character's voice

### PR DESCRIPTION
**Pull request by Mothblocks**
## About The Pull Request

- Adds the ability to force your TTS voice to always be blips, default is still normal speech
- Probably fixes a bug with silicon voices not transferring properly? There was an entire argument missing from tts_request/New
- Fixes problems I got from the Docker build not working at all. Only thing interesting is `--no-cache-dir` which was to fix the container running out of RAM even though I literally just got 64GB of RAM today

Got permission from @optimumtact as alternative to being able to disable your voice, CC @Iamgoofball 

## Why It's Good For The Game

I spent two hours trying to find a voice that didn't make me uncomfortable to use and that was even in the realm of being the voice I would actually want people to hear. Characters still have distinct "voices" because the blips are chopped together from the voice itself

## Changelog

:cl:
add: You can now set your voice to just blips.
/:cl:

### CODE REVIEW

**Comment by Vincent983** [comment]
Does everyone hear the blip voice or only the person who has it turned on? Also, does ling transforming into a person with blips turned on make your voice sound like blips?

**Comment by nikothedude** [comment]
leeet s fucking GOOOOOOOOO

**Comment by Mothblocks** [comment]
> Does everyone hear the blip voice or only the person who has it turned on? Also, does ling transforming into a person with blips turned on make your voice sound like blips?

Everyone hears it (otherwise it would just be the game setting but worse), yes

**Comment by Inari-Whitebear** [comment]
Feels like this defeats the point of having TTS, since it makes me read again. It sorta acts the same as an option for people to just turn off TTS for themselves, which we explicitly don't have

**Comment by SomeoneYouProbablyKnow** [comment]
I don't like TTS (it sounds wonky, it doesn't fit, half the voices are very out of place, it stutters on any minor typo) but this feels like a really weird half measure solution. Now every time you hear a blip you have to search your screen for the one sentqnce that you didn't catch.

I wish everyone just used these TTS filtered blips instead of full TTS sentances

**Comment by Iamgoofball** [comment]
im fine with this imho

**Comment by carlarctg** [comment]
can we get a demo

**Comment by Watermelon914** [comment]
Don't really like this because I still feel that this defeats the purpose of having a TTS system which is to hear other people speak

**Comment by EricZilla** [comment]
I also want more androgynous voices tbh. I wish there was an easier way to test how they sound, since sometimes the preview sounds little like the in game.

**Comment by Inari-Whitebear** [comment]
> I also want more androgynous voices tbh. I wish there was an easier way to test how they sound, since sometimes the preview sounds little like the in game.

From what I've seen there are plans to give you a better selection alongside custom text to preview the voice with

**Comment by HoodMilk** [comment]
When are we gonna get don't starve instruments as a voice option

**Comment by Nimowa** [comment]
I really don't want to put up with blip voices when I explicitly have that option turned off, it's not something I want to listen to for an entire round.

And as @Watermelon914 said, not being able to hear what players are actually saying defeats the point of having TTS (at least for those not using blips).

**Comment by SapphoQueer** [comment]
> Feels like this defeats the point of having TTS, since it makes me read again. It sorta acts the same as an option for people to just turn off TTS for themselves, which we explicitly don't have

I guess the mute + signer combo kinda does that?

**Comment by Mothblocks** [comment]
To be fair mute + signer should probably have *some* indication even if it's something special

**Comment by IndieanaJones** [comment]
OK having actually played with people using this, it does kind of suck to just not have access to hearing some characters and having to listen to the annoying animal crossing sounds.

**Comment by Watermelon914** [comment]
yeah, now that I'm hearing this in game, I'd rather just TTS be disabled by default instead.
I've disabled TTS for myself because the animal crossing voices just sound so annoying to listen to.

**Pull request merged**
