### PR TITLE
The nullrod sabers now have sprites again.

### LINKED ISSUE #45206: Dark energy sword null rod option is invisible
Choose the dark energy sword option when selecting a null rod, it has a sprite on your character when held but in your hand it is invisible and it will become invisible if dropped or equipped. Can be picked up still by right clicking/alt clicking on the tile its on

Issue reported from  Round ID: 113214 (/tg/Station Sybil [ENGLISH] [US-WEST] [100% LAG FREE])

Reporting client version: 512.1471

### PR DESCRIPTION
**Pull request by nemvar**
## About The Pull Request

Fixes my oversight.
Closes #45206

## Why this is good for me

This is my scheme for farming GBP.

## Changelog
:cl:
fix: The nullrod sabers now have sprites again.
/:cl:

### CODE REVIEW

**Comment by actioninja** [comment]
you fool, gbp hasn't been accepted here for months now.

**Comment by nemvar** [comment]
It's not about the GBP on the website. It's about the GBP in our hearts.

**Comment by ATH1909** [comment]
Could we make null rod eswords have a toggle-able blade at some point (like "real" eswords?)?

**Comment by nemvar** [comment]
Probably can't make them toggable because of powercreep reasons. A nullrod with normal damage that fits into pockets and provides antimagic would be a bit much.

**Pull request merged**
