### PR TITLE
Joker (2019) Suit and Coat

### PR DESCRIPTION
**Pull request by 13spacemen**
Adds the comedian suit and coat to the AutoDrobe
Ported from BeeStation https://github.com/BeeStation/BeeStation-Hornet/pull/533, sprites by @severepwnage

jokertg

## Why?
It looks drippy, it's a great costume for the clown for a gimmick, and also Joker 2 got confirmed by Todd Phillips

:cl:
add: The comedian suit and coat are now available in the AutoDrobe! Wearing them may make you feel like you need a psychiatrist.
/:cl:

### CODE REVIEW

**Comment by Farquaar** [comment]
Good evening, ladies and gentleman. Let me introduce myself.  My name is Rupert Pupkin.  I was born in Clifton, New Jersey, which was not, at that time, a federal offense. Is there anyone here from Clifton?

Good.  We can all relax. Now, I'd like to begin by saying that my parents were too poor to afford me a childhood but the fact is nobody is allowed to be really poor in Clifton. Once you fall below eleven thousand you're exiled to Passaic. My parents did, in fact, put down the first two payments on my childhood. Then they tried to return me to the hospital as defective.   But, like everyone else I grew up in large part thanks to my mother. If she was only here today I'd say, "Hey, mom.  What are you doing here?  You've been dead for nine years?"

You should have seen my mother. She was wonderful-- blonde, beautiful, intelligent, alcoholic. We used to drink milk together after school. Mine was homogenized. Hers was loaded. Once she was picked up for speeding.  They clocked her doing fifty-- in our garage.  

When they tested her they found that her alcohol was two per cent blood. They took away her license and she died shortly afterwards. We used to joke together Mom and me, until the tears would stream down her face and she'd throw up. And who would clean it up? Not Dad. He was too busy down at O'Grady's throwing up on his own. In fact, until I was sixteen, I thought throwing up was a sign of maturity.  While the other kids were off in the woods sneaking cigarettes, I was hiding behind the house with my fingers down my throat. I never got anywhere until one day, my father caught me.  Just as he was giving me a final kick in the stomach, for luck, I managed to heave all over his new shoes. "That's it," I thought.  "I've made it.  I'm finally a man!" 

As it turned out, that was the only time my father ever paid any real attention to me. He was usually too busy out in the park playing ball with my sister, Rose. And, today thanks to those many hours of practice, my sister Rose has grown into a fine man. Me, I wasn't especially interested in athletics.  The only exercise I ever got was when the other kids picked on me. They used to beat me up once a week, usually Tuesday. After a while, the school worked it into the curriculum. And, if you knocked me out, you got extra credit. Except there was this one kid who was afraid of me. I kept telling him, "Hit me!  Hit me! What's the matter with you? Don't you want graduate?" As for me, I was the only kid in the history of the school to graduate in traction.  The school nurse tucked my diploma into my sling.  

But my only real interest, right from the beginning, was show business.  Even as a young man, I began at the very top, collecting autographs.

A lot of you are probably wondering why Jerry couldn't make it this evening.  Well, he's tied up-- and I'm the one who tied him. You think I'm joking, but that's the only way I could break into show business -- by hijacking Jerry Langford. I'm not kidding.  Right now, Jerry Langford is strapped to a bedstead somewhere in the middle of this city. Go ahead.  Laugh. But the fact is... I'm here. Tomorrow you'll know I wasn't kidding and you'll think I was crazy. But I figured it this way: better to be King for a Night than Schmuck for a Lifetime! Goodnight ladies and gentlemen. God bless you.

**Comment by dablusniper** [comment]
This says a lot about society

**Review by Twaticus — CHANGES_REQUESTED** [review]
the icons/mob/clothing/under/costume.dmi suit handholes need to be filled

**Comment by 13spacemen** [comment]
@Twaticus done

**Review by Twaticus — APPROVED** [review]

**Pull request merged**
