### PR TITLE
Nothing to see here

### PR DESCRIPTION
**Pull request by MrsTonedOne**
Move along folks.

### CODE REVIEW

**Comment by ike709** [comment]
one does not simply make a PR to solely add themselves to admin.txt, please include a feature or bugfix. :-1:  x :100:

**Comment by MrStonedOne** [comment]
This one does.

**Comment by Nienhaus** [comment]
:p

**Comment by optimumtact** [comment]
CODER'S MAKING THEMSLEVES ADMINS ABUSE< CONSPIRACY AHHHHHHHHHHhh

**Comment by paprka** [comment]
this is the wrong file to add yourself to isnt it

**Comment by dannno** [comment]
yes

**Comment by RemieRichards** [comment]
There's on reason to put yourself in this config file, and that's to be able to use the byond profiling tools.

**Comment by tkdrg** [comment]
You can profile from dreamdaemon if you're hosting on local anyway.

**Comment by optimumtact** [comment]
aran in charge of making more admin.txt files

**Pull request merged**
