### PR TITLE
Adds methods for cultist to deal with wounds

### PR DESCRIPTION
**Pull request by necromanceranne**
## About The Pull Request

Unholy water acts as a coagulant for cultists, and fixes bleeds.

Blood rites will apply wound healing based on the amount of uses used up. It will heal wounds _before_ healing blood loss and damage, so low charges may get eaten up healing wounds, but it is capped to 50 charges so usually you'll have enough left over for actual damage (and wounds are usually scarier than actual damage). 

For blood loss, it begins to reduce the flow. For burns, it applies flesh healing. In both these instances, it is worse than most standard methods of recovering from these wound types.

Offering rune will mildly heal wounds on successful conversion. They may still need further healing, but it will help stop them from outright bleeding out.

## Why It's Good For The Game

Cult straight up didn't receive any wound healing when we implemented wounds. Before wounds, most effects similar to wounds were healed using standard damage healing, including bleeding (which the cultist healing currently operates on this older assumption, namely that that brute damage = bleeds, so healing brute heals bleeds, hence why most effects recover blood but do not stop bleeds in of itself). 

Cultists will often have a hard time fixing wounds. I can easily think of several instances where a cult got eventually bled out/died of mass infection because, while they recovered damage with ease, their absolute lack of wound fixing meant that they were defeated via attrition unless they could get themselves medical supplies.

If cult is receiving a lot of wounds, it is probably at a point where cult has moved into going loud. Cult, due to how their mechanics work, have a harder time pretending to be normal crew as time goes on. So, unless they butcher their way into medbay just to get a few sutures and regen mesh to fix their wounds, they're in a bit of a losing spiral unless they're really overwhelming the crew. This problem is therefore something that heavily contributes to cults landslide victory/loss problem.

At the same time, I recognize that cult healing is _slightly_ better due to not needing to put yourself in a vulnerable position to get it. Blood rites does require some fiddly stuff to get going, but it is ostensibly free. So I've made these methods weaker than typical healing methods.

## Changelog
:cl:
add: Implements ways for cultists to fix wounds.
add: Blood rites begin to fix various wounds. It is slightly weaker than using medical supplies.
add: Offer rune does a much weaker heal than blood rites.
add: Unholy water acts as a coagulant, and begins to heal bleeds.
/:cl:

### CODE REVIEW

**Comment by pilotmans** [comment]
Cultists are overpowered and they want to buff them?

**Comment by Livrah** [comment]
Most of the round cultists don't have 90% of their powers due massprinted bullrods. And with no range combat options, you will get a lot of wounds. 
As a Blood Rites enjoyer I approve.

**Comment by necromanceranne** [comment]
> Cultists are overpowered and they want to buff them?

So, on paper, cult reads like a powergamers wet dream. It seems to have everything going for it.

However, statistically speaking, cult struggles to actually succeed more often than not. It has roughly around a 30% win rate. Most cults get beaten down before they ever get anywhere. For a role that suffers from such little success, it isn't easy to call it overpowered. Otherwise I would think its consistent success would be self evident.

While I understand cult can be frustrating to face, it should remain current with the development of the game. Particularly because nobody is making the significant effort to redesign cult from the ground up, and we are seemingly keeping the mode in rotation. This, to me, is more restoring power the cult has had historically (evidenced by the recovery of blood in all their healing powers, and bleeding being the proto-wound at the time) that wasn't updated when health mechanics were updated other than to fix runtimes.

**Comment by DaydreamIQ** [comment]
This is entirely balanced by the fact that nobody uses blood rites despite how CRACKED it is, Love it.

**Comment by SimplySmiley123** [comment]
> > Cultists are overpowered and they want to buff them?
> 
> So, on paper, cult reads like a powergamers wet dream. It seems to have everything going for it.
> 
> However, statistically speaking, cult struggles to actually succeed more often than not. It has roughly around a 30% win rate. Most cults get beaten down before they ever get anywhere. For a role that suffers from such little success, it isn't easy to call it overpowered. Otherwise I would think its consistent success would be self evident.
> 
> While I understand cult can be frustrating to face, it should remain current with the development of the game. Particularly because nobody is making the significant effort to redesign cult from the ground up, and we are seemingly keeping the mode in rotation. This, to me, is more restoring power the cult has had historically (evidenced by the recovery of blood in all their healing powers, and bleeding being the proto-wound at the time) that wasn't updated when health mechanics were updated other than to fix runtimes.

Ehhhh not really.
They don't really struggle unless they forget about the massive crutch that is the stun hand. And most of the time they do take over medbay anyway due to how easy it is and because of the burn medkits for laser guns which are only real weapon crew can use against cult without gambling wether the cultist or the baton user clicks first.

**Comment by CCC23** [comment]
> > Cultists are overpowered and they want to buff them?
> 
> So, on paper, cult reads like a powergamers wet dream. It seems to have everything going for it.
> 
> However, statistically speaking, cult struggles to actually succeed more often than not. It has roughly around a 30% win rate. Most cults get beaten down before they ever get anywhere. For a role that suffers from such little success, it isn't easy to call it overpowered. Otherwise I would think its consistent success would be self evident.
> 
> While I understand cult can be frustrating to face, it should remain current with the development of the game. Particularly because nobody is making the significant effort to redesign cult from the ground up, and we are seemingly keeping the mode in rotation. This, to me, is more restoring power the cult has had historically (evidenced by the recovery of blood in all their healing powers, and bleeding being the proto-wound at the time) that wasn't updated when health mechanics were updated other than to fix runtimes.

you are on crack if you think the conversion antag with a 15 second stun hand eswords and dswords the ability to instantly gib people on command access to the strongest armor in the game and the ablility to summon humans with eswords for the cost of standing on a rune with some plasteel

**Comment by IndieanaJones** [comment]
I mean, stats are stats. 30% is 30% regardless of what you may have personally experienced. Regardless, I think its a good change because more antags should have solutions to wounds.

**Comment by necromanceranne** [comment]
I wanna just clarify; I don't intend to make changes to cult with the expectation of that number going up. I don't think, in its current state, that the win rate going up is a good sign unless it happened to be a _significant_ rework, and even then, it may not be ideal simply because the antagonist ends the round outright.

Moreso, I think the number is a good demonstration that cult, even thought it has the bonkers equipment it does right now, still cannot easily secure victory consistently. 

Not to say that this justifies adding any old bonkers balance change to cult. But I think, in the sense of a significant quality of life improvement that will hopefully help cult be somewhat _less_ frustrating to _experience_ (especially for new converts who might have to now deal with severe wounds from a particularly loud cult that currently would just see them die without much of an obvious solution, even if they may be an experienced cultist), I think reducing the frustrations of cults seemingly outdated design is positive change that is long overdue.

**Comment by pilotmans** [comment]
> > Cultists are overpowered and they want to buff them?
> 
> 
> 
> So, on paper, cult reads like a powergamers wet dream. It seems to have everything going for it.
> 
> 
> 
> However, statistically speaking, cult struggles to actually succeed more often than not. It has roughly around a 30% win rate. Most cults get beaten down before they ever get anywhere. For a role that suffers from such little success, it isn't easy to call it overpowered. Otherwise I would think its consistent success would be self evident.
> 
> 
> 
> While I understand cult can be frustrating to face, it should remain current with the development of the game. Particularly because nobody is making the significant effort to redesign cult from the ground up, and we are seemingly keeping the mode in rotation. This, to me, is more restoring power the cult has had historically (evidenced by the recovery of blood in all their healing powers, and bleeding being the proto-wound at the time) that wasn't updated when health mechanics were updated other than to fix runtimes.

Cult only has a low win rate cause only new players play it, get any competent player that at the very least has a static and you’ll see just how quickly cult can steamroll, hell, one time a cultist tried to sacrifice me but his rune was next to a disposal unit and I just hid in it and dude couldn’t find me despite the fact I didn’t even turn it on.

**Comment by necromanceranne** [comment]
> Cult only has a low win rate cause only new players play it, get any competent player that at the very least has a static and you’ll see just how quickly cult can steamroll,

That sounds really anecdotal my guy. Sure, it has a grain of truth in there. Plenty of new players end up cultists and are confused about what to do. The game is quite difficult to grasp as it is. But consider this; if newer players are struggling to play cult, they clearly need the onboarding to be less severe, Because the experienced players, with all of cults various tools, seemingly are not enough to push the win rate higher, and this change will almost certainly not meaningfully impact their ability to succeed, because they were doing so _before_ this change as well, right?

**Comment by pilotmans** [comment]
> > Cult only has a low win rate cause only new players play it, get any competent player that at the very least has a static and you’ll see just how quickly cult can steamroll,
> 
> 
> 
> That sounds really anecdotal my guy. Sure, it has a grain of truth in there. Plenty of new players end up cultists and are confused about what to do. The game is quite difficult to grasp as it is. But consider this; if newer players are struggling to play cult, they clearly need the onboarding to be less severe, Because the experienced players, with all of cults various tools, seemingly are not enough to push the win rate higher, and this change will almost certainly not meaningfully impact their ability to succeed, because they were doing so _before_ this change as well, right?

- If you say so, just don't think a game mechanic that pisses off players so much that they start coming up with ways to bypass or ignore the antagonist so much that it becomes obnoxious is a sign of a good mechanic, such as those memes of mk ultraing assistants, whilst this healing may not buff them I'll still be on edge simply due to the amount of times I've been unfairly stun locked by an inexperienced shitter.

**Comment by SimplySmiley123** [comment]
> > > Cultists are overpowered and they want to buff them?
> > 
> > 
> > So, on paper, cult reads like a powergamers wet dream. It seems to have everything going for it.
> > However, statistically speaking, cult struggles to actually succeed more often than not. It has roughly around a 30% win rate. Most cults get beaten down before they ever get anywhere. For a role that suffers from such little success, it isn't easy to call it overpowered. Otherwise I would think its consistent success would be self evident.
> > While I understand cult can be frustrating to face, it should remain current with the development of the game. Particularly because nobody is making the significant effort to redesign cult from the ground up, and we are seemingly keeping the mode in rotation. This, to me, is more restoring power the cult has had historically (evidenced by the recovery of blood in all their healing powers, and bleeding being the proto-wound at the time) that wasn't updated when health mechanics were updated other than to fix runtimes.
> 
> Cult only has a low win rate cause only new players play it, get any competent player that at the very least has a static and you’ll see just how quickly cult can steamroll, hell, one time a cultist tried to sacrifice me but his rune was next to a disposal unit and I just hid in it and dude couldn’t find me despite the fact I didn’t even turn it on.

I seen regulars who speedran a cult victory before station would even know cultists existed, all while _alone_ only getting constructs.
New players have the issue of getting overwhelmed, it has nothing to do with wounds really. Been there before, seen it before and had to deal with players like that before.

**Comment by moocowswag** [comment]
Stats only cover winrate as summoning narsie before round end?

I would say at least 5% of the time its a loss due to cultists not getting on rune, not really crazy or anything but its something.

Another thing stats dont cover is how fun an antagonist is to play as/against one of the things holding cult back is not because its kit is so limited its because players can spend more time learning ways to counter it than playing as it since 90% of gameplay for most players is playing as a regular crew member.

The main thing holding cult winrate up at 30% (yes "up") is because a minority of players are capable of carrying it and providing an obscene amount of value, I don`t have a problem with this but I do have a problem with how some nerfs in the past have been directed at this. (We literally removed Nar`sie plushie interaction because it allowed easier solo conversions and rune stuff)


So on one hand we have an conversion antagonist with a ton of overpowered tools that a competent player can abuse to easily wipe out even SOLO antagonists by themselves that are pushing up the cult winrate

On the otherhand, we try to nerf the ability for a minority of cultists to carry the rest of cult, potentially pushing down the winrate and in the end justifying for the fact that most items and abilities accessible to cult are absurdly powerful on both paper and in practice.

As for wounds, this is one of those things where itl mainly help solo cultists carry, wound attrition is a killer of anyone that is capable of doing dirty work and fighting on the frontline of cult, other players who spend half the time looking at the wiki generally won`t survive conflict long enough for wounds to matter.

Imo this is a good buff for cult (and in general alot of solo antagonists need ways to deal with wounds) because it pushes solo cultists to being more capable of carrying and hopefully down the road their "winrate" will be high enough to "justify" nerfs/removals of things that are seen as unfun or generally unbalanced.

But one last note, balance isnt everything, if balance was a strict tightrope, we wouldn't be able to have cool and interesting mechanics in the first place.

**Comment by necromanceranne** [comment]
So, to summarize your point, you argue only individually skilled cultists are what is actually propping cult's win rate whatsoever? And that, historically, we've focused nerfs on this aspect, which this PR is in direct opposition towards?

I'm not entirely sure if that is true, that would be an incredible stretch even if individual cultists making the most of all the tools is a formidable force. I've certainly seen competent cultists still fail, and seen otherwise less competent cultists pull back from victory. It's in the nature of a conversion antagonist to somewhat snowball into a victory with sheer numbers, but also lose steam if they can't make that happen. It's the nature of the tug of war, both sides of a conflict can have equally competent opponents. It's just that cult provides quite a lot of individual power compared to, say, revolutionaries, who use their subtly as a smokescreen to foster chaos as a way to achieve their goal.

I would argue it's not really ascertained what is actually maintaining the current win rate. Certainly, I wouldn't look at niche interactions like the Nar'sie plushie and think too much of it, it ostensibly did the job of Spirit Realm conversions. I'd say that it was maybe wishful thinking removing that interaction would have any meaningful impact. The removal was more likely due to people believing too strongly in patterns without considering the nature of those patterns and merely repeating what they're seeing, and someone else coming to those same conclusions and taking issue.

We just call that 'ruining the game for yourself' quite honestly.

**Comment by moocowswag** [comment]
When i say carry cult i dont mean solo win i mean providing an extreme amount of value like rushing to sac the target by yourself before cult is even outed or dealing with threats to cult like disabling genetics/botany or focusing on converting specific jobs 

You even have the tools to rush down static names that you know might be the problem to the cult in the future 

It might not look like much on paper but completing a laundry list of side objectives  like this allows a single cultist to greatly impact the round and you certainly have the tools to do all of this

**Comment by ninjanomnom** [comment]
Broadly speaking I'd prefer antags, especially ones that are fake crew, use the same systems as crew when dealing with a problem that both have. Instead of special cult healing mechanics I'd prefer they either, like now, have to get into medbay, or give them some way of creating their own normal (as far as the code is concerned) medical supplies.

**Comment by necromanceranne** [comment]
That's only true for about 2/3rds of the time for cult. Once halos are out, they're very clearly no longer crew.

**Comment by ninjanomnom** [comment]
I said *especially* ones that are fake crew, not entirely. What I'm talking about has close to nothing to do with how much an antag appears to be crew but more about how close it feels to play that antag compared to normal crew. Unless it ties in deeply with what's unique about an antag they should be using the normal systems that players experience most of the time. It's a matter of preferring deep mechanics over shallow and wide ones, but the more mechanical depth something has the better it is to make it consistent across the game.

**Comment by necromanceranne** [comment]
Okay, that's a bit clearer, but I'm still not entirely sure how I'm supposed to action on your point. Are you softly telling me to close this PR and telling everyone the current healing mechanics are inappropriate? Is the only option going forward to then remove that healing?

**Comment by moocowswag** [comment]
If you limit antags ability to interact with the medical system without non antag gear you suddenly get players silently assassinating / murderboning with stun weapons since attrition from lethal combat becomes a much bigger deal.

please dont encourage a playstyle like this. Especially on a conversion antag which is already best played as a sec/command assassination rush since you can silently wipe command/sec with stun hands and rr them one at a time at round start.

**Comment by ninjanomnom** [comment]
> [...]but I'm still not entirely sure how I'm supposed to action on your point.[...]

I'm not against improving the ability to heal like you do in this pr, as I said in the first reply I would just prefer it if the mechanics the cultists used to heal were the same system as what most crew uses. If the issue is that it's unreasonable for late stage cultists to get access to healing, then make alternate methods for them to get items that fulfill the same mechanics. Instead of having special systems in the code for cult healing you could give them reskinned, possibly only usable on cultists, wound healing item subtypes.

> Ninjanomnom, If you limit antags ability to interact with the medical system without non antag gear you suddenly get players silently assassinating / murderboning with stun weapons since attrition from lethal combat becomes a much bigger deal.

Them having to use the same systems doesn't mean it can't be made easier for antags to access those systems.

**Comment by necromanceranne** [comment]
>Instead of having special systems in the code for cult healing you could give them reskinned, possibly only usable on cultists, wound healing item subtypes.

Our current methods for healing are medical tools, surgeries and healing packs like sutures and regen mesh. And chemicals as well I suppose. Unholy water covers the reagent part, so it is kind of in line with that thinking. The sacrifice rune doing mild wound healing is mostly to resolve a noob trap.

I would maybe be more inclined to agree with this suggestion, if there was not already a very severe issue of cult being overloaded with mechanical tools and knowledge checks. 

The most significantly mechanically deep of these methods touched here, Blood Rites, is basically turning sources of blood into healing. The depth is in trying to accumulate that blood in some way to create that healing (or other spell variations). It feels like something thematically in-touch with cults premise as blood mages. So much so it is weird that this isn't how cult works in general....

I'm not sure if, currently, cult is in a state where making all their healing options utilize crew facsimiles isn't stacking the knowledge barrier  higher against inexperienced cultists. A problem we would want to avoid whatsoever.

**Comment by ninjanomnom** [comment]
In the early stages of the game the cultist can still reasonably stay hidden and get healing from medbay, and in the lategame should they not have converted someone from medbay who should know how to use items that behave the same as normal healing items? If the cult is getting heavily wounded and slowly dying because they failed to get anyone who knows how to heal, then that sounds like an issue on their end.

**Comment by necromanceranne** [comment]
My point has been that has healing. It is outdated healing, with expectations of the game still squarely in 2016.

I'm getting severely mixed messages here, so I'll just close the PR.

**Comment by ninjanomnom** [comment]
I wasn't trying to stop what you were going for here and most of the changes seemed fine, just the method for applying the benefits was a bit off. Please don't read what I say as dictating what you must do, I make it clear that's what I'm doing if that's the case.

**Comment by necromanceranne** [comment]
That's fair. Sorry, I was just getting a bit confused still I suppose.

**Comment by necromanceranne** [comment]
gonna close this pr and atomize it out so I can make sure this is done right.

**Pull request closed without merging**
