### PR TITLE
Allows emotes to be uppercase by changing early lowertext() (take two, post-freeze version)

### PR DESCRIPTION
**Pull request by nikothedude**
## About The Pull Request
Makes the message of emotes not lowercase by moving the lowertext(act) in emote.dm lower.

And yes, it still recognizes emotes. *coUGH will still happen.

## Why It's Good For The Game
For the guys up here, mainly code cleanup. This PR was originally made for skyrat, because there you can press T and then type "*me blah blah blah". Due to the way this works, before this PR, you couldn't put any capitalization after *me because it'd lowercase it.

## Changelog

:cl:
qol: In the edge case that an emote would have a custom parameter capitalized, it now stays capitalized properly.
/:cl:

### CODE REVIEW

**Comment by Ghommie** [comment]
Finally, now I can dab on other mobs without their names being lowercased.

**Comment by nikothedude** [comment]
> Finally, now I can dab on other players without their names being lowercased.

I actually had no idea this happened (nobody fuckin dabs on skyrat _thankfully_)

**Comment by Ghommie** [comment]
I mean, I was joking. There's no *dab emote.

**Comment by nikothedude** [comment]
> I mean, I was joking. There's no *dab emote.

oh thank fucking god

**Pull request merged**
