### PR TITLE
Power crepes are now finger food

### PR DESCRIPTION
**Pull request by TJatPBnJ**
## About The Pull Request
Power crepes are now finger food, meaning you can eat them while walking. I think this makes sense because the power crepe is massive enough to just take a bite out of while you walk.
## Why It's Good For The Game
Power crepes are a very expensive food item, the should at least be easy to eat.
## Changelog
:cl:
balance: Power crepes are now finger food
/:cl:

### CODE REVIEW

**Comment by Elli-Skala** [comment]
This is just more power creep

**Comment by newfren** [comment]
this is going to make it much easier to eat this when you steal it from the captain, highly approved

**Comment by moocowswag** [comment]
power crepe

**Comment by EricZilla** [comment]
power crepe power creep?

**Pull request merged**
