### PR TITLE
Changed Pyroxadone recipe to use CLF3 instead of Slime Jelly.

### PR DESCRIPTION
**Pull request by KathyRyals**
## About The Pull Request

Changes Pyroxadone recipe to be a 1:1 mix of Cryoxadone and CLF3.

## Why It's Good For The Game

More accessible Pyroxadone. More options for medical.

With permission from @ExcessiveUseOfCobblestone 

## Changelog
:cl:
balance: Changed Pyroxadone recipe to be a 1:1 mix of Cryoxadone and CLF3.
/:cl:

### CODE REVIEW

**Comment by ATH1909** [comment]
it just makes sense, really

**Comment by Krysonism** [comment]
Powercreep.

**Comment by XDTM** [comment]
Pyroxadone was initially meant to be an intentionally hard-to-make gimmick reagent that rewarded some cooperation between xenobio and chemistry, with the obvious benefit of rapid healing by just setting the patient on fire.

Giving chemistry the ability to make it on their own is definitely unnecessary powercreep in my opinion, if the reagent effects have not changed since then. 
Plus, it reduces the incentive for chemistry to communicate with another department, which seems like a step in the wrong direction.

**Comment by KathyRyals** [comment]
Pyroxadone is quite literally never made. And cryotubes are underused. We can always tune Pyroxadone's number or recipe later. I'm interested to see if this will change anything to the current "medical meta".

**Comment by XDTM** [comment]
My point of view on that matter is that if a mechanic that requires cooperation is nearly never used, the solution is to further incentivize cooperation rather than remove the requirement.
Which, in this case, would translate to either buffing the reagent, making it easier for xenobio to share their products, adding a larger variety of xenobio-based reagents, or giving chemistry something useful to xenobiologists, to increase the chance of the two departments wanting to ask each other's help.

It's a point of view based on a wider gameplay pattern, so it's not a big problem by itself (especially if cobby approved it) but it does set back the cooperation agenda a little bit.

**Comment by KathyRyals** [comment]
I agree with you, and I would like to see more inter-department things. That's not the scope of today's PR however, and I thank you for respecting that.

**Comment by Thalpy** [comment]
What if I made slime jelly an optional reagent to reduce it's reaction volalility (see convermol/tirimol for examples)? I think this change is a good idea since it's one of my favourites but I never get to make it.

**Comment by Rhials** [comment]
Inter-departmental collaboration is great and all, but who the fuck is gonna expect collaboration from two of the most antisocial and powergamer-riddled subdepartments when the reward doesn't directly benefit them (and only them)?

**Comment by ExcessiveUseOfCobblestone** [comment]
i thought pyrox was just cryo inverted, didnt realize it had a completely different calculation... yikers....

**Comment by Tlaltecuhtli** [comment]
cryo doesnt cool you

**Comment by moocowswag** [comment]
Pyroxadone healing the same as cryoxadone would leave it extremely niche and borderline useless, harder recipe, only a limited amount of people can even use it without burning their clothes off (unless xenobio/chap mass produce fireproofing) not to mention the damage that most species will take from the high heat/fire making it only viable on lizards/slime people or someone with fiery sweat.

As for the current collaboration issue with making it, most xenobiologists would be more than willing to give up a few dozen unused extracts (or a single reproductive grey so the chemist can make his own slime jelly) seriously most people who go to a staffed xenobio will leave with what they want if its easy enough to make.

I have made this chem before and the reward is worth the effort its just that making pyroxadone usually means youre either planning for a scenario where it will actually be useful without getting bwoinked. Thats the biggest downfall, not the department cohesion but the fact that its not a chem you can easily use on the go for combat regen without being that guy who runs around on fire and walks into a dozen people.

**Comment by ATH1909** [comment]
> i thought pyrox was just cryo inverted, didnt realize it had a completely different calculation... yikers....
> 
> Think i led you a bit astray here, for it to be merge-worthy I'd need it to be just an inversion of cryo. My thought was it would be pretty much a worse version considering if you are in a fire you are already fricked, and its a snoozer compared to using leporazine.

Well, I mean, the fire/hot temperatures are gonna be damaging you more than cold temperatures would...

**Comment by ATH1909** [comment]
> What if I made slime jelly an optional reagent to reduce it's reaction volalility (see convermol/tirimol for examples)? I think this change is a good idea since it's one of my favourites but I never get to make it.

https://www.youtube.com/watch?v=1WburVhYHn8

**Comment by Mothblocks** [comment]
> Pyroxadone is quite literally never made. 

that's because you're lazy, I've made it plenty of times

and I don't *WANT* to be incentivizing cryo more, cryo is the exact opposite of the medical gameplay we're looking for (which is to be engaging with the patient). it's worse than surgeries since you can't even talk to the person about their round or whatever, and they can't talk to you. you have literally no other option but to alt-tab.

**Comment by KathyRyals** [comment]
Good point. I'm not interested in merging a change that nerf Pyroxadone. I think looking at a way to make chem-xenobio interactions easier is a better idea.
As a quick side-note, Pyroxadone doesn't put the patient to sleep. Which is why I like it so much.

**Comment by Mothblocks** [comment]
>  As a quick side-note, Pyroxadone doesn't put the patient to sleep. Which is why I like it so much.

Yep! The sleep is a feature of the cryo tubes itself when their body temp is a low enough level.

**Comment by SinfulBliss** [comment]
I have not seen pyroxadone made once, like ever. I think the issue is that, to make pyroxadone, you need to 1) get into xenobiology, 2) hope they have leftover extracts, 3) hope they care enough to help you. It sounds easy, and it isn't too hard, but it's just an added hurdle that chem would rather avoid and instead make normal healing chems which are 100% chem-supplied.

That and .4u/tick is a whole lot for what's a relatively expensive chem to produce.

**Pull request closed without merging**
