### PR TITLE
Mulebot resprite :>

### PR DESCRIPTION
**Pull request by Sheits**
## About The Pull Request

Currently the version in this pr should be one pixel too low, because I was told crates are going to be shifted up later. Overall the sprite hasn't changed much, just minor colour stuff and track wheels instead.

image

## Why It's Good For The Game

Crates line up now

## Changelog

:cl:
image: Resprites the mulebot
/:cl:

### CODE REVIEW

**Review by Wallemations — APPROVED** [review]

**Comment by TheVekter** [comment]
oh boy, here we go again

Looks fine by me. Have mules always had treads and I'm just unobservant? I thought they had wheels instead.

**Comment by OverwatchVoice** [comment]
I don't know if it should be threaded or not, is it 

> Have mules always had treads and I'm just unobservant? I thought they had wheels instead.

They always had wheels, not threads. I'd say it makes sense for them to have wheels though, being in a (mostly) artifical environment with flat floors, instead of threads which are better suited for rougher terriains.

**Review by ShizCalev — CHANGES_REQUESTED** [review]
could you fix the paranormal mulebot too? (it's essentially just a greyscale palette swap + 127 alpha on everything but the wheels)

**Comment by TheVekter** [comment]
> They always had wheels, not threads. I'd say it makes sense for them to have wheels though, being in a (mostly) artifical environment with flat floors, instead of threads which are better suited for rougher terriains.

Treads.

**Comment by Wallemations** [comment]
> I don't know if it should be threaded or not, is it
> 
> > Have mules always had treads and I'm just unobservant? I thought they had wheels instead.
> 
> They always had wheels, not threads. I'd say it makes sense for them to have wheels though, being in a (mostly) artifical environment with flat floors, instead of threads which are better suited for rougher terriains.

Them being able to roll over people if they have their safeties off makes me think they'd have treads personally

**Comment by TheVekter** [comment]
Can you widen the rollers a little bit on the top of it? These doohickeys.

image

The top of it feels kind of featureless and I think it'll help with that. Just extend them down and up.

**Comment by SomeoneYouProbablyKnow** [comment]
Looks neat. Would appreciate an actual ingame image to see how it works with everything and at its proper size.

**Comment by BlueMemesauce** [comment]
Could someone post how they look with the new crates?

**Comment by BlueMemesauce** [comment]
image

**Comment by MrDoomBringer** [comment]
treads look much cooler than wheels!

**Comment by Dorsisdwarf** [comment]
You know what? I dig it.

**Comment by Sheits** [comment]
> Once

I'll do it now, thanks

**Comment by Sheits** [comment]
That should be it, minor change but I didn't make the wheels have full opacity since the tracks go all the way under and would have probably just made a noisy mess.
Also idb doesnt show the opacity on the animations but its there I promise 
image

**Pull request merged**
