### PR TITLE
Adds a mutagen dispenser

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
For use in the seed vault. Will add to the map once the map freeze is done.

### CODE REVIEW

**Comment by Core0verload** [comment]
Why not a wall mounted tank similar to pepper spray refiller?

**Comment by RandomMarine** [comment]
Those have a finite amount.

**Comment by kyrahabattoir** [comment]
Wheren't you supposed to rely on chemistry for mutagen? Or are we making that redundant too?

**Comment by KorPhaeron** [comment]
This is only for the lavaland vault creatures, who are stranded alone, not normal botany

**Pull request merged**
