### PR TITLE
Academy Fixes & Upgrades.

### PR DESCRIPTION
**Pull request by AnturK**
Mostly making it bit more resistant to cheap tricks.
- Swaps northern windows for indestructible ones. Southern ones are left untouched. Also fixes the icons for these.
- Moves the Skeleton Relase to Teacher room.
- Sprinkles few magicarp spawns in space around the academy.
- Adds syndicate mask,gloves and turtleneck to freezer bear cave.

### CODE REVIEW

**Comment by Aranclanos** [comment]
please include the changes in the OP and a image of before and after

**Comment by AnturK** [comment]
Soonish

**Comment by KorPhaeron** [comment]
Might want to consider a box of internals for the academy defender.

Alternatively dont spawn thr mob until you picked a ghost for it so it doesnt suffocate for 30 seconds while catatonic.

I realize the windows will help with this but there sre plenty of other ways to fuck atmos

**Comment by Zilenan91** [comment]
Is the skeleton release button named "skeleton release button"?

**Comment by Zilenan91** [comment]
Oh and another thing, can you add a medkit into the headmasters office or do you think he'd be too tough to kill if he had one.

**Comment by Incoming5643** [comment]
Replacing the wooden door where the defender spawns with a wooden airlock would go a long way to keeping its pressure up.

**Pull request merged**
