### PR TITLE
Replaces Xenomicrobe gas from Experimentor.

### PR DESCRIPTION
**Pull request by GunHog**
- Requested in https://github.com/tgstation/-tg-station/issues/7856.

This PR is created in response to admin complaints of rampant abuse of the xenomicrobes gas. The gas is replaced currently by Sulfuric Acid. (Suggestions open for similar deadly gases, wear a biosuit to protect yourself).

I recommend acquiring admin feedback based on if https://github.com/tgstation/-tg-station/pull/7768 has had the desired effect in cutting down abuse.

### CODE REVIEW

**Comment by RandomMarine** [comment]
Another sad case of nice things that had to go due to abuse.

**Comment by GunHog** [comment]
Merge issues fixed. Should admins still desire this after the bwoinks have gone out, it is ready to go.

**Comment by GunHog** [comment]
This was not meant to be merged yet, without feedback from the admins, but I guess it is too late now.

**Comment by phil235** [comment]
Argh, sorry I got a bit too merge-happy.

**Pull request merged**
