### PR TITLE
GAME OVER YEAHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH

### PR DESCRIPTION
**Pull request by Iamgoofball**
:cl: Iamgoofball
add: Ported two round-end sounds, and one new round-end sound.
/:cl:

### CODE REVIEW

**Comment by bobdobbington** [comment]
>goonposting

**Comment by optimumtact** [comment]
newround2.ogg is fine

newround1.ogg is lame and uninteresting

**Comment by xxalpha** [comment]
This isn't goon.

**Comment by Incoming5643** [comment]
newround1.ogg is fine

newround2.ogg is lame and uninteresting

**Comment by optimumtact** [comment]
now it's good

**Comment by xxalpha** [comment]
big :+1:

**Comment by Iamgoofball** [comment]
Fuck you.

**Comment by xxalpha** [comment]
Have you tried coding for goon if you love goon so much

**Comment by Iamgoofball** [comment]
Fuck you.

**Comment by Core0verload** [comment]
Fuck you.

**Comment by phil235** [comment]
Yes, let's put sound files in a goon folder instead of the sound folder.... :-1:

**Comment by TechnoAlchemisto** [comment]
goon go home

**Comment by francinum** [comment]
@phil235 There's already sounds there.

**Comment by optimumtact** [comment]
the two goon sounds need to be there for licensing reasons afaik, the other one can be moved.

**Comment by PKPenguin321** [comment]
goon or not goon these sounds are fun so why not

**Comment by Incoming5643** [comment]
You literally could just rerecord the lines from the source material and cut out goon completely. This ain't a transformative work.

**Comment by Iamgoofball** [comment]
:cop: :e-mail: :arrow_right:

**Comment by MrPerson** [comment]
They all sound like ass

**Comment by optimumtact** [comment]
Y U HEFF TO BE MAD?

**Comment by Cheridan** [comment]
gb2 goonstation

**Comment by Iamgoofball** [comment]
Why

**Pull request closed without merging**
