### PR TITLE
Lava article

### LINKED ISSUE #21544: That's a lava.
reee

### PR DESCRIPTION
**Pull request by Cyberboss**
Fixes #21544 

Disclaimer: On vacation, haven't actually tested this, but, I'm 99% sure it's right.

### CODE REVIEW

**Comment by lzimann** [comment]
did you just assume lava's gender

**Comment by Cyberboss** [comment]
Wait is it proper or improper? FUCK

**Comment by Cyberboss** [comment]
@lzimann I already made that joke damn you, #21544

**Comment by Cyberboss** [comment]
OK apparently neither of those work...

**Pull request closed without merging**
