### PR TITLE
Fixes smartfridges once and for all.

### PR DESCRIPTION
**Pull request by MrsTonedOne**
url_encode allows us to keep stacking done by name without worrying about special chars in the name.

Making the list on interact is the only way to ensure name changes doesn't fuck things up.

:cl:
fix: Fixes the smartfridge not stacking items.
/:cl:

### CODE REVIEW

**Comment by Jalleo** [comment]
:+1: even if this does cause some issues

**Comment by Jalleo** [comment]
I just worked out a possibly better way have the objects stored in the actual matter bin to have that act as a list since it would update live without needing to regenerate the list each time on interact

**Comment by MrStonedOne** [comment]
that would prevent stacking from working correctly

**Comment by Incoming5643** [comment]
could you roll back the rpgloot -'s and +'s?

**Comment by Jalleo** [comment]
I can do that tomorrow if it isnt done in this PR

**Comment by RemieRichards** [comment]
Merged 3 hours early, for science.

**Pull request merged**
