### PR TITLE
Replaces Pubby With Kilo, Alternative To #53857

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request
What the title says, replaces Pubby with Kilo, Kilo being a station that was removed a while back when the four maps at a time rule came into place.

image

It looks like this, for anyone who hasn't seen it yet.

## Why It's Good For The Game
Pubby has been one of those maps that above anything like 20 pop, the shuttle is called as soon as possible, because most people just genuinely don't like Pubby that much. Because the pr to replace Pubby with Omega hasn't been getting the greatest feedback, I propose this instead.

I'll handle maintaining it and all that, and if there are any problems you see with the map please tell me about them.

Also the whole decals crashing the server an hour in thing was fixed so I think it's fine to readd it, I'm gonna go through and clean up the decal spam a bit anyways.

## Shit I Gotta Do
- [ ] Make sure it's all running right, because it probably isn't
- [ ] Clean up the decals a bit, we don't need to be warned that there is a warning ahead
- [ ] Holy fuck where did all these decals come from
- [x] Plumbing area for medbay

## Changelog
:cl:
add: Kilostation is back in rotation
del: Pubbystation is removed in favor of Kilostation
/:cl:

### CODE REVIEW

**Comment by zxaber** [comment]
If we have to see Pubby go, Kilo is a better choice for a replacement.

**Comment by LemonInTheDark** [comment]
This will require extensive test-merging on servers with newer players to see if the crashing is still a concern.

**Comment by Paxilmaniac** [comment]
Yes, I am not 100% sure on the decals not crashing it, which is why I'm gonna remove a lot of the super unnecessary decals that are put everywhere if it turns out to be a true problem.

**Comment by EOBGames** [comment]
I'll leave the same here as a reminder, please take the opportunity to talk to the creator of #53857 and see if an arrangement can be made.

**Comment by EOBGames** [comment]
By the way, please inform me when this is ready for a testmerge, since if the crashing still affects the map regularly it won't be accepted.

**Comment by TreyWJ** [comment]
Yeah no reason to remove the decals until that's a confirmed problem (AFAIK Delta has significantly more decals than Kilo).

**Comment by wesoda25** [comment]
Holy fuck kilo re added plus an excuse to remove the eye bleed caution stripes? Christmas come early.

**Comment by bluetshirtguy** [comment]
I beg of thee, kilo botany is very cramped for modern botany, adjusting it's size would be very appreciated. Botany also suffers a lot from decals creating almost a eye blur effect with the amount of visual noise. Botany on kilo lacks privacy as your whole department is open with windows.

**Comment by sergeirocks100** [comment]
The permabrig needs to be redesigned to accomodate shiftstart prisoners, namely more cells and contraband loot spawns.

**Comment by Barhandar** [comment]
Please remove all the super unnecessary decals regardless of whether it crashes or not.
>~~Botany~~ Entirety of Kilo also suffers a lot from decals creating almost a eye blur effect with the amount of visual noise.

**Comment by TreyWJ** [comment]
Kilo botany is pretty massive, not sure why you're saying it's small. The decals look great and give the station character, without them it'd be much duller.

**Comment by Fikou** [comment]
will you maintain the map after this pr

**Comment by Paxilmaniac** [comment]
@Fikou Yes

**Comment by FloranOtten** [comment]
> Kilo botany is pretty massive, not sure why you're saying it's small. The decals look great and give the station character, without them it'd be much duller.

I've seen the map with the decals mass removed. It looks absolutely fine. The decals are just massively distracting.

**Comment by Barhandar** [comment]
The hydroponics is actually properly sized, the excessive decals just make it _look_ much smaller (and also like you're supposed to walk while standing across tiles), just like vast majority of rooms on Kilo. Also makes it obnoxious to change tray layout due to floor pattern not matching the layout you want.  
kilohydro
7x8 + 6x2=68. For comparison, Meta is 7x11=77, pre-z icebox: 8x8=64, pubby: 6x9+4x4=70.


Given the amount of warning tape, literally doing a mass delete and then redoing it from scratch will likely be MUCH faster and better than deleting what it has place per place. And yes, looks WAY better with all decals removed.  
The amount of decals is such that instead of creating visual interest and distinction, they become _noise_ at the in-game viewing scale (viewrange 7), just like how pointillism looks like a mess if you're standing too close. And because their scale is comparable to the actual things you need to emphasize (i.e. machinery, airlocks...), those get integrated into the noise too and stop being distinct. Ironically, putting a different texture under every single machine and surrounding it with warning tape makes them stand out _less_, not more.

Medbay Storage is physically two areas.  
medbay
Also you might need to run tests for missing and duped APCs, request consoles, air and fire alarms, pipes, wires, etc.

Also obligatory "[alert fatigue](https://en.wikipedia.org/wiki/Alarm_fatigue): a case study" in the form of shitposting:
WARNING: WARNING: WARNING: WARNING: STAND CLEAR WARNING AHEAD  
> VENT <  
>>>> RO >> CENTER << OM <<<<  
///////////  
//TOE  
//STUBBING  
//DANGER

**Comment by Paxilmaniac** [comment]
I actually don't have the time to deal with this right now, maybe some other time

**Comment by wesoda25** [comment]
😭

**Pull request closed without merging**
