### PR TITLE
Update: replaces the singulo area with sm area (derelict)

### PR DESCRIPTION
**Pull request by nyozzl**
## About The Pull Request
Replaces the empty singularity chamber with a usable supermatter chamber

## Why It's Good For The Game

The derelict drone station since removal of singularity generators (i assume it used to have a singularity generator) most likely lacks a big goal.. other than total repair
this adds a supermatter shard to the material vault and a exploded supermatter chamber
## Changelog

:cl: Nyozzl
Add: SM chamber to drone derelict station
/:cl:

corner 1

corner 2

image

image

### CODE REVIEW

**Comment by PeriodicChaos** [comment]
Would love this.

**Comment by iwishforducks** [comment]
I liked the soul of having the singulo area there but yeah having the SM chamber there so there's an actual goal for drones would be much better.

**Comment by Sealed101** [comment]
should first check whether https://github.com/tgstation/tgstation/issues/79926 is still an issue because having one more sm shard in space ruins locked behind some door hacking (see: oldstation) can be kinda controversial and/or extra funny

**Comment by Admiral-Gigaton** [comment]
Hey wasnt someone trying to get an SM shard to seem like it came from a crashed cargo express pod? Could be used here but thats on you

**Pull request merged**
