### PR TITLE
Wraps calls to BYOND alert()

### PR DESCRIPTION
**Pull request by Cyberboss**
Having a layer control over procs that sleep is a nice thing

### CODE REVIEW

**Comment by optimumtact** [comment]
it's not though

**Comment by Cyberboss** [comment]
H-Hey, remember thread monitoring? R-remember that feature request? :P

**Comment by optimumtact** [comment]
reeeeeeeeeeee

**Comment by Cyberboss** [comment]
<3

**Comment by lzimann** [comment]
i really dislike this, feels so pointless

**Comment by MrStonedOne** [comment]
Just change them to all use tgalert

**Comment by Cyberboss** [comment]
Some other time

**Pull request closed without merging**
