### PR TITLE
Nerfs bicycles to normal slowdown

### PR DESCRIPTION
**Pull request by silicons**

### CODE REVIEW

**Comment by DaxDupont** [comment]
Why though, the bicycles cost like 1 million points at cargo. They are really rare and supposed to be a meme.

**Comment by optimumtact** [comment]
yeah this is a dumb pr

**Comment by Dorsisdwarf** [comment]
But why

**Comment by Repukan** [comment]
You're asking the wrong questions. Don't ask why, ask Kevinz how the bike killed him

**Comment by Grazyn** [comment]
He tried the bike during the ball

**Comment by kevinz000** [comment]
@Repukan the latest stream of nerf prs are the things i personally used and abused

**Pull request closed without merging**
