### PR TITLE
 Journeying Hitchhikers Shuttle Events + Bugfixes

### PR DESCRIPTION
**Pull request by Time-Green**
## About The Pull Request

Adds the following new general shuttle events:_
**Hitchhiker**
- 1% chance
- A single assistant in an EVA suit and some PBJs in a suitcase

**Assistant Wave**
- 0.1% chance
- Spawns 10 assistants with internals
- For clarity, they don't get sent to the shuttle, but get launched at it from space. It's a scuffle of 10 assistants trying to get in without being spaced or succumbing to the cold/pressure

**Intern Wave**
- Admin only
- Unarmed and armed version
- Spawns centcom interns, with a little announcement to warn they're coming

I've also fixed projectiles bugging out and admin forced shuttle events not activating if they were added after the shuttle launched

<details>
  <summary>Admin only events added</summary>
  
**Nukie**
Spawns a single nukie, armed with a shotgun, pistol and edagger. Basically the deathmatch nukie loadout, you dont want to fight this

**Meaty ores**
Meaty-ores meteors. Have a 4% chance to hit the shuttle, posing a potential hazard

**3 player controlled fire-sharks**
3 fire sharks controlled by players. Not much to talk about here

**Fireball Wave**
Shoots a wave of fireballs at the shuttle. I think it's cool but apparently shuttle walls and windows deflect fireballs so it's kind of moot unless you're outside :/

</details>

## Why It's Good For The Game
The assistant and hitchhiker events are some flavoring that I thought up a while ago. The Hitchhiker is just intentionally a flavor addition, but the assistant wave and intern wave can be used by admins to repopulate or retake the emergency shuttle as well. 

## Changelog
:cl:
add: Adds an assistant and hitchiker shuttle event, replenishing the crew mid flight!
admin: Adds two intern wave shuttle events
code: You can now supply shuttle events with outfits!
code: You can now shoot projectiles with the shuttle events!
fix: Fixes projectiles bugging out when fired in shuttle transit space
fix: Fixes admin forced shuttle events not activating when added mid transit
/:cl:

### CODE REVIEW

**Comment by timothymtorres** [comment]
##### _I have been summoned from the depths of Valhalla_

---

Glad to see someone finally incorporating this shuttle event via player actions. I would check with Melbert since he initially placed a DNM restriction on the original PR in #77188.

**Comment by itseasytosee** [comment]
I'm not so certain people this will make people want to stop hijacks more, but its certainly cool.

**Review by MrMelbert — COMMENTED** [review]
I still very much disagree with random bullshit being thrown at the shuttle, and I still think the shuttle is chaotic enough without throwing in a singularity or nukie. 

I also have to disagree with this point: 

> This gives a very good mechanical incentive to stopping antag hijacking, since there are actual consequences now, and they can be pretty severe.

You've disincentivized allowing friendly hijacking which I actually do agree with, but you've also entirely disincentivized *un*friendly hijacking, because there's a non-zero chance that you start a hostile take-over (and people actually try to stop you!) but you get nailed in the forehead by a singularity and die instantly

**Comment by timothymtorres** [comment]
> you've also entirely disincentivized _un_friendly hijacking, because there's a non-zero chance that you start a hostile take-over (and people actually try to stop you!) but you get nailed in the forehead by a singularity and die instantly

You know it's funny I was thinking the same thing but was too lazy to verbalize it. Might be better off reworking it to only trigger if an antag has the `Die a glorious death objective` or as a Final Objective/Grand Ritual.

**Comment by Time-Green** [comment]
> I still very much disagree with random bullshit being thrown at the shuttle, and I still think the shuttle is chaotic enough without throwing in a singularity or nukie.
> 
> I also have to disagree with this point:
> 
> > This gives a very good mechanical incentive to stopping antag hijacking, since there are actual consequences now, and they can be pretty severe.
> 
> You've disincentivized allowing friendly hijacking which I actually do agree with, but you've also entirely disincentivized _un_friendly hijacking, because there's a non-zero chance that you start a hostile take-over (and people actually try to stop you!) but you get nailed in the forehead by a singularity and die instantly

Is your issue with the singularity, the other hijack events or also the Hitchiker events?

**Comment by MrMelbert** [comment]
> Is your issue with the singularity, the other hijack events or also the Hitchiker events?

Big issues with:
Singularity (instant death), Nukie (not super impactful but I think will detract from the exprience), Magicarps (don't these things get fireball?), and fire sharks (they explode into a plasmafire) 

Minor issues with:
Meaty ores (the cockpit, where you hijack, is like the most likely place that you will get nailed by a meteor) 

Probably fine:
Fireballs (since you say they deflect off the shuttle, probably looks more cool than harmful) 

And as for the hijackers, I don't get the point of them (particularly the assistants), outside of getting everyone killed when they inevitably space the shuttle. 
In general I would prefer if the shuttle was spaced by an antag or a stupid engineer than by some random ghost role.

The admin only centcom one is probably fine though, would be funny to throw them at someone hijacking to give them a challenge

**Comment by SmArtKar** [comment]
> > I still very much disagree with random bullshit being thrown at the shuttle, and I still think the shuttle is chaotic enough without throwing in a singularity or nukie.
> > I also have to disagree with this point:
> > > This gives a very good mechanical incentive to stopping antag hijacking, since there are actual consequences now, and they can be pretty severe.
> > 
> > 
> > You've disincentivized allowing friendly hijacking which I actually do agree with, but you've also entirely disincentivized _un_friendly hijacking, because there's a non-zero chance that you start a hostile take-over (and people actually try to stop you!) but you get nailed in the forehead by a singularity and die instantly
> 
> Is your issue with the singularity, the other hijack events or also the Hitchiker events?

every single one of these is harmful to the antag themselves, in most cases they'd either get hit by the event itself or friendly fired by summons. I'm a bit confused on the lore aspect of this too, if you want to raise the stakes a bit maybe make hijacking the shuttle do something in-transit instead? But then again, its once more almost guaranteed to harm the antag themselves too.

**Comment by Time-Green** [comment]
> > Is your issue with the singularity, the other hijack events or also the Hitchiker events?
> 
> Big issues with: Singularity (instant death), Nukie (not super impactful but I think will detract from the exprience), Magicarps (don't these things get fireball?), and fire sharks (they explode into a plasmafire)
> 
> Minor issues with: Meaty ores (the cockpit, where you hijack, is _the_ most likely place to be hit by a meteor)
> 
> Probably fine: Fireballs (since you say they deflect off the shuttle, probably looks more cool than harmful)
> 
> And as for the hijackers, I don't get the point of them (particularly the assistants), outside of getting everyone killed when they inevitably space the shuttle. In general I would prefer if the shuttle was spaced by an antag or a stupid engineer than by some random ghost role.
> 
> The admin only centcom intern one is probably fine though, would be funny to throw them at someone hijacking to give them a challenge

I'll take out the hijack stuff tomorrow then, we'll just have the hitchikers and bugfixes/improvements

**Comment by Time-Green** [comment]
Also lore is micro-singularities because of haphazard navigating, the others are just wacky.
I've removed all the hijack stuff, it's just the Hitchikers and assistant wave now. All the events are still in as admin only events

**Comment by MrMelbert** [comment]
I'll remove the DNM but I still think the assistant one in particular is dumb

**Comment by Time-Green** [comment]
> I'll remove the DNM but I still think the assistant one in particular is dumb

I think it’s divine but if it’s reslly disliked I can relegate it to admin only. It’s already very rare so the difference is nihil (and it will still let me do it on live)

**Comment by EEASAS** [comment]
maybe you should do a salesman variant of hitchhikers with some space cash and some goodies

**Pull request merged**
