### PR TITLE
[s] [HOTFIX] Being bumped into and not just bumping into people makes you visible as agent box

### PR DESCRIPTION
**Pull request by Militaires**
:cl: Basilman
fix: fixed agent box invisibility
/:cl:

:cry: hey a man's gotta do what a man's gotta do

### CODE REVIEW

**Comment by Militaires** [comment]
@Cyberboss i just did this quick as possible but ok ill do some epic github edit hacks.......

**Comment by optimumtact** [comment]
bman learns to code, part xivvi

**Comment by Militaires** [comment]
@Cyberboss done im also gonna test it locally

**Comment by Militaires** [comment]
grazie italiano :blush:

**Pull request merged**
