### PR TITLE
Syndicate shotguns spawn with buckshot by default

### PR DESCRIPTION
**Pull request by ghost**
Rip free stuns.

### CODE REVIEW

**Comment by Cheridan** [comment]
Wasn't the whole point of these is that they were a replacement to the old eguns that the ops used to get? I'm generally anti-stun but I never really saw it as an issue in the case of Ops, who are typically outnumbered.

**Comment by hornygranny** [comment]
They are a bad replacement because you can't really kill people with them.

**Comment by Fox-McCloud** [comment]
As long as sec start out with tasers, then nukies should start off with stun weapons, especially since it's 5 ops vs the entirety of the crew.

**Comment by paprka** [comment]
This will be addressed in another PR with more guncode wizardry from myself.

**Comment by Fox-McCloud** [comment]
Care to extrapolate a bit, please?

**Comment by paprka** [comment]
Look at my latest PR I guess

**Pull request merged**
