### PR TITLE
sugarcane

### PR DESCRIPTION
**Pull request by Tlaltecuhtli**
:cl:
fix: sugarcane is now available in vendors
/:cl:

### CODE REVIEW

**Comment by erwgd** [comment]
Sugarcane was intentionally [removed](https://github.com/tgstation/tgstation/commit/19d6e40baec1cc2eef3b638008f97d508efcc8e2) in 2012:
> -Removed sugarcane seeds from the vending machine. They were redundant and had poor sprites and no recipes. Added the seeds to the seeds crate so you can still get them, if you really want to...

Now that sugarcane uniquely distills into rum it's distinct enough from white beets.

**Comment by Tlaltecuhtli** [comment]
i might add a mutation to turn them into vietnam bamboo

**Comment by FloranOtten** [comment]
> i might add a mutation to turn them into vietnam bamboo

make it damage Sec

**Comment by optimumtact** [comment]
Putting emojii in the changelog will break it you madman

**Pull request merged**
