### PR TITLE
Makes ghosts float up and down ala zero-g

### PR DESCRIPTION
**Pull request by ghost**
They bob up and down now like spooky ghosts floating about.

### CODE REVIEW

**Comment by TheVekter** [comment]
:-1:, too spooky.

**Comment by Miauw62** [comment]
:two: :ghost: :four: :mens:

**Comment by RemieRichards** [comment]
I agree with Miauw, 2Ghost4Cry

**Comment by ike709** [comment]
:-1: Too spooky, you must balance it out by adding various things from Ghostbusters.

**Comment by Dorsisdwarf** [comment]
:-1: I'm scared of spooky ghosties

**Comment by Kraseo** [comment]
GHOULISH GAUDY GHOSTS

**Comment by Miauw62** [comment]
:ghost:

**Pull request merged**
