### PR TITLE
Stops monkey hordes from spamming chat log to some extent

### PR DESCRIPTION
**Pull request by AnturK**
Yes

### CODE REVIEW

**Comment by coiax** [comment]
Doesn't stop them screeching on mass though

**Comment by AnturK** [comment]
Yeah, maybe i should make monkey screeches share cooldown with monkeys in view.

**Comment by coiax** [comment]
I think we also have to accept that our current information system (ie. the chat window) cannot deal with 50 mobs all talking and emoting frequently. Shuttle rides tend to be clusterfucks in part because everything happens so quickly you have no idea what's going on.

**Comment by Kromgar** [comment]
One round there was like 60 monkeys and the chat screen would freak the fuck out

killed me to find out emotes were controlled by ghost sight

**Pull request merged**
