### PR TITLE
 Bloody Friday wasn't funny

### PR DESCRIPTION
**Pull request by SpaceVampire**
## About The Pull Request

Renames the Irish Car Bomb to the Irish Slammer.

## Why It's Good For The Game

The current name of the drink references the infamous car bombs that were set off by the Irish Republican Army in Northern Ireland during a time known as the Troubles, which lasted from 1968 to 1998. On July 21, 1972, the IRA used more than 20 car bombs in a single day, now known as Bloody Friday, killing nine people and injuring 130 more. It has often been said this is like if there was a drink named the "Twin Towers Bomb" or the "9/11" after the American tragedy.

## Changelog

:cl:
del: change the name of the "Irish Car Bomb" to a more generic "Irish Slammer"
/:cl:

### CODE REVIEW

**Comment by Burgermancoding** [comment]
I am Irish do not merge no one is offended

**Comment by MMMiracles** [comment]
if this stays does that mean we can add a 9/11 drink

**Comment by Naloacisamazing** [comment]
Second irish person here,  This is a dumb as fuck pr

**Comment by Burgermancoding** [comment]
You're completely lying by relating it to a single incident as well, no one is saying "hey bloody friday was funny"

**Comment by Naloacisamazing** [comment]
add a drink called the twin towers please

**Comment by 81Denton** [comment]
ok

**Comment by wesoda25** [comment]
> add a drink called the twin towers please

https://user-images.githubusercontent.com/37246588/142271986-cb626b34-7ada-4776-b66d-d37e49e6e438.mp4

**Comment by Lauwma** [comment]
Just add a twin tower drink

**Comment by drIcepop** [comment]
What would be the recipe for the Twin Tower drink? Thermite and something else? I think we're on to something here.

**Pull request closed without merging**
