### PR TITLE
Reorganizes the sound folder

### PR DESCRIPTION
**Pull request by grungussuss**
## About The Pull Request

<details>

- renamed ai folder to announcer

-- announcer --
- moved vox_fem to announcer
- moved approachingTG to announcer

- separated the ambience folder into ambience and instrumental
-- ambience --

- created holy folder moved all related sounds there
- created engineering folder and moved all related sounds there
- created security folder and moved ambidet there
- created general folder and moved ambigen there
- created icemoon folder and moved all icebox-related ambience there
- created medical folder and moved all medbay-related ambi there
- created ruin folder and moves all ruins ambi there
- created beach folder and moved seag and shore there
- created lavaland folder and moved related ambi there
- created aurora_caelus folder and placed its ambi there
- created misc folder and moved the rest of the files that don't have a specific category into it

-- instrumental --

- moved traitor folder here
- created lobby_music folder and placed our songs there (title0 not used anywhere? - server-side modification?)

-- items --

- moved secdeath to hailer
- moved surgery to handling

-- effects --

- moved chemistry into effects
- moved hallucinations into effects
- moved health into effects
- moved magic into effects

-- vehicles --

- moved mecha into vehicles

created mobs folder

-- mobs --

- moved creatures folder into mobs
- moved voice into mobs

renamed creatures to non-humanoids
renamed voice to humanoids

-- non-humanoids--

created cyborg folder
created hiss folder
moved harmalarm.ogg to cyborg

-- humanoids --

-- misc --

moved ghostwhisper to misc
moved insane_low_laugh to misc

I give up trying to document this.

</details>

- [X] ambience
- [x] announcer
- [x] effects
- [X] instrumental
- [x] items
- [x] machines
- [x] misc 
- [X] mobs
- [X] runtime
- [X] vehicles

- [ ] attributions

## Why It's Good For The Game

This folder is so disorganized that it's vomit inducing, will make it easier to find and add new sounds, providng a minor structure to the sound folder.

## Changelog
:cl: grungussuss
refactor: the sound folder in the source code has been reorganized, please report any oddities with sounds playing or not playing
server: lobby music has been repathed to sound/music/lobby_music
/:cl:

### CODE REVIEW

**Comment by DATA-xPUNGED** [comment]
image
Very divisive reception to this PR /s

**Comment by Sadboysuss** [comment]
even though I have not acomplished everything I wanted yet, I'm gonna mark this as ready because it's already an extremely gigantic pr to review and most of the important work is done.

**Comment by Sadboysuss** [comment]
had to do some map edits because maps had varedited sound file paths

**Review by LemonInTheDark — APPROVED** [review]
I agree with the concept and implementation thus far, am NOT going line by line here but this seems perfectly sane.
Tentative approval, will check back when you're satisfied with the work here.

**Comment by LemonInTheDark** [comment]
Fuck it we ball

**Pull request merged**
