### PR TITLE
removes fiverr content

### PR DESCRIPTION
**Pull request by Fikou**
## About The Pull Request

removes a round end sound that the headmin of hippiestation or something wants to sue us over

## Why It's Good For The Game

wah wah

## Changelog
:cl:
sounddel: jordan peterson disappointed round end sound is gone
/:cl:

### CODE REVIEW

**Comment by Tumesuo** [comment]
lmao

**Comment by Tumesuo** [comment]
today I will claim copyright to a sound file that was generated by a free to use website, despite the fact that any other person could have used the same one.

**Comment by Iamgoofball** [comment]
whoa whoa whoa, you only need to pull disappointed, not petersondisappointed

however, the peterson voice generation is TERRIBLE

**Comment by Fikou** [comment]
> whoa whoa whoa, you only need to pull disappointed, not petersondisappointed
> 
> however, the peterson voice generation is TERRIBLE

the pr that added the peterson sound said that it was taken from hippiestation so i think thats the one, but wheezl seems to just be trolling or stupid and this probably wont get us sued so ill close someone can reopen and merge if they want i guess

**Comment by Iamgoofball** [comment]
i'll replace the two later today

**Comment by optimumtact** [comment]
@Iamgoofball are you redoing peterson ?

**Pull request closed without merging**
