### PR TITLE
Adds an extremely important emote. I can't believe the game grew this popular without it.

### PR DESCRIPTION
**Pull request by ghost**
:cl: Reeeimstupid
add: Added farting. Because what's better slipping someone then farting on them?
/:cl:

See CL.

### CODE REVIEW

**Comment by jughu** [comment]
Its not fun when it doesnt tell which player got farted on

**Comment by kevinz000** [comment]
Believe goonstation is that way. Wrong station.

**Comment by gt33** [comment]
@jughu How would I do that? (I assume i'd need to check if the fartee was standing on another player or next to one)

**Comment by optimumtact** [comment]
back 2 goon

**Comment by gt33** [comment]
never been on goon before

**Pull request closed without merging**
