### PR TITLE
Replaces the current, unreasonably long tram whiteship, with a shorter and more compact one

### PR DESCRIPTION
**Pull request by Paxilmaniac**
## About The Pull Request
As the title would imply, this replaces the current tram whiteship, which while a funny reference to the [REDACTED] event when the tram bugged out and killed everyone, is just way too long and especially when compared to the other ships, is massively larger.

image

(Imaged above is the map editor view of the new shuttle, which is a cool 13x27)

## Why It's Good For The Game
Greatly reduces the amount of things that has to be moved whenever someone uses the tram whiteship, while still mostly keeping the original reference.
The original was 13x41, and this new one is 13x27, just to give a better idea of how much it was cut down.

## Changelog

:cl:
qol: the whiteship of tram station has been made much shorter, allowing for less lag on movement and easier docking
/:cl:

### CODE REVIEW

**Comment by Fikou** [comment]
have you tested if this one spawns

**Comment by Paxilmaniac** [comment]
how is this conflicting

**Comment by Maurukas** [comment]
This is almost too nice Paxil. Wonderful use of the new spawners.

**Comment by datorangebottle** [comment]
Any chance you have a preview of what the old one looked like, for comparison? I don't think I've ever seen it.

**Comment by YakumoChen** [comment]
> Any chance you have a preview of what the old one looked like, for comparison? I don't think I've ever seen it.


just look at mapdiffbot, it looks like a huge cargo freighter with a tram in it and gibs

**Pull request merged**
