### PR TITLE
Raptor Sprites

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
http://imgur.com/a/gydrS

img

For @RemieRichards to use as vehicles after the freeze

There are 7 colour variants but I don't feel like uploading all of them.

Name is subject to change/can be whatever remie wants, needed a name for giant bird though.

Work was done by my girlfriend.

### CODE REVIEW

**Comment by tedward1337** [comment]
lmaoo

**Comment by duncathan** [comment]
Does chocobro's name come from chocobo
Tbh I'd always thought it was chocolate bro but now I'm uncertain

**Comment by Fox-McCloud** [comment]
yeah, "raptor"...sure.

**Comment by WJohn** [comment]
Fairly nice sprites, although the nearly black outlines on the back/side sprite kind of bother me. I see you already have a dark outline color on the "front" of the chocobo's side sprite, you should make more use of that.

**Comment by ike709** [comment]
image

**Comment by Memendia** [comment]
image
I am 99.9% sure that is not a raptor but an overgrown chicken..

**Comment by RemieRichards** [comment]
Yes it's a Chokobo/Chocobo, but copyright and nonsense.

**Comment by Memendia** [comment]
Then it's a super overgrown chicken.... correct?

**Comment by danhibiki** [comment]
make it have a chance for poly to mutate into it with mutagen

**Comment by KorPhaeron** [comment]
@danhibiki

I was thinking chicken eggs so botany could breed them

**Comment by danhibiki** [comment]
why not both?

**Comment by KazeEspada** [comment]
Ce riding a parrot colored chocobo into battle with an RCD in one hand and a flamer in the other.

**Comment by danhibiki** [comment]
the raptors shouldn't be flameproof though, so they should burn down to a nice crispy dinner

**Comment by Iamgoofball** [comment]
hey @KorPhaeron Can you have your GF do one of these with the feathers greyscaled and as an overlay? I got an idea.

**Comment by Iamgoofball** [comment]
@danhibiki breed a red raptor for that

**Comment by Iamgoofball** [comment]
oh and uh

ask her to make colored eggs for each type of """raptor""" and baby versions of each """raptor""" so I can implement some original content

**Comment by KorPhaeron** [comment]
I uploaded them in the dmi I meant didnt want to put them all on imgur

**Comment by KorPhaeron** [comment]
@Wjohn

I'll ask her how easy it will be to move the head down in the front sprites but I'd rather not ask her to redo the outlines on 28 sprites (I will tell her no black outlines in the future but it would be nice if it could slide this time since they're better than a lot of stuff in game anyway)

**Comment by tedward1337** [comment]
nooooOOOOOOOOOOOOOOOOO

**Comment by PKPenguin321** [comment]
They're in goof's PR now Ted

**Pull request closed without merging**
