### PR TITLE
New dark blue slime reaction (fireproofing potion)

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
Add water to a dark blue extract to get a fireproofing potion.

Use the potion on a clothing item to give it maximum heat resist.

### CODE REVIEW

**Comment by Jalleo** [comment]
News at 6 owlman seen runnimg into the fire at medical and dragging out 10 bodies.

**Comment by Supermichael777** [comment]
>3 uses

I know this is strait up power creep to begin with but come on.

**Comment by RemieRichards** [comment]
This should also disable the item's burn state and stuff

**Comment by KorPhaeron** [comment]
@Supermichael777 

You gotta do it for the shoes, exoslot, and head if you dont want to burn.

**Comment by KorPhaeron** [comment]
@RemieRichards 

Sure

**Comment by Aloraydrel** [comment]
wew laddy

**Comment by GunHog** [comment]
Love this. Love it. :+1:

**Comment by Anonus** [comment]
this and the red slime speed boost extract should be incompatible

**Comment by Durkel** [comment]
Good seeing the shitty slime reactions get something good.

**Comment by KorPhaeron** [comment]
Surely one day every slime extract will be almost worth using

**Comment by GunHog** [comment]
Maybe one for radproofing?

**Comment by Steelpoint** [comment]
I think its cool :+1: 

If there's grave concerns about this being too powerful, look at making the application of this item halve the amount of defence a item has, so its not viable to use this on powerful armour as it would make it overall less effective, but is useful on mundane, less armoured, items.

**Comment by KorPhaeron** [comment]
Updated the burn_state thing

**Comment by GunHog** [comment]
Merge it. Now. I want this.

**Comment by KorPhaeron** [comment]
@GunHog's quest for the ultimate hardsuit

**Pull request merged**
