### PR TITLE
Add Birdshot Station to _basemap.dm

### PR DESCRIPTION
**Pull request by lessthnthree**
## About The Pull Request

Puts Birdshot in _basemap.dm, it wasn't in the original PR.

### CODE REVIEW

**Comment by san7890** [comment]
can you alphabetize this

**Comment by Cyberboss** [comment]
Drop the changelist please, I'm pretty sure this setting is for CI only.

**Comment by lessthnthree** [comment]
> 

Yeah

**Comment by lessthnthree** [comment]
> can you alphabetize this

Yeah

**Comment by Addust** [comment]
why is this still not merged Holy Shit

**Comment by Mothblocks** [comment]
it's not important at all?

**Pull request merged**
