### PR TITLE
Bartender now has theatre access

### PR DESCRIPTION
**Pull request by lzimann**
Proper solution to #28528

The bartender "owns" the bar, makes sense that he would have access to the theatre backstage and the costume vendor.

### CODE REVIEW

**Comment by FantasticFwoosh** [comment]
Faster access to maidsuits, cream pies, slips and stuns, losing your ID and being trapped tied to a pipe in maintenance and relentlessly hunted by clowns & mimes who want theatre, bar, kitchen & botany access 

Im pretty sure the station owns the bar. The bartender just works there.

With this level of access i don't see why the bartender can't just be a mini head of staff like the QM.

**Comment by TrustyGun** [comment]
> With this level of access i don't see why the bartender can't just be a mini head of staff like the QM.

The QM has underlings.. he doesn't. Why do you think the two are comparable?

**Comment by Grazyn** [comment]
Access creep. And where does it say that he owns the theatre? Some stations (like meta) have the theatre clearly separated from the bar.

**Comment by FantasticFwoosh** [comment]
@TrustyGun well i hardly see HOP's even acknowledge that they are even the head of service or that the clown technically answers to them, so do whatever minor position change (bar-manager) is nessecary.

**Comment by lzimann** [comment]
I mean, for all I care bartenders having a maid ~~fetish~~ costume is stupid as fuck, but at least this way you prevent the snowflakeness of adding to their locker.

**Review by Cyberboss — APPROVED** [review]

**Comment by Penguaro** [comment]
Arguably though this wouldn't happen, the QM should be Head of Service and Supply and the HoP more like a second in command / HR manager. I mean really, the HoP is just a clerk. The only reason they're given significant attention is that they have the ability to generate all-access.

**Comment by kevinz000** [comment]
> No doubt @kevinz000 will burst in at some point and just tell me to shoot the clown/mime/greyshirt attacker, but i dont want to end up being murdered/robbed by a access crazed clown or having to literally restrain/kill the clown in response because of the power of responsibility the bartender now has to hold onto it. There's a reason why ID is partitioned between sections.
> Faster access to maidsuits, cream pies, slips and stuns, losing your ID and being trapped tied to a pipe in maintenance and relentlessly hunted by clowns & mimes who want theatre, bar, kitchen & botany access capitalizing on your greed for costumes.

1. call security
2. stretch goal: get good and you know, not get robusted by the joke roles as a guy with a shotgun?????
3. sounds like a "you're bad" problem rather than a "bartender shouldn't get access" problem, try again.

**Comment by FantasticFwoosh** [comment]
1. You mean call kevin who'll run out from whatever job they are doing pop a cap in the clown indiscriminately and probably bail you out of ahelps saying it was a justified response. I dont want to have to murder the clown that should have been jobbanned anyway to just work safely at my job.

2. You gave them a cream pie cannon you shitter, you can't initially knock down the bartender with a raw cream pie because of glasses but you can slip them any such way, and its unavoidable. Only the second shot with beanbags calls a stun. 

3. "You're bad extends to the 90% and anybody vaguely not interested in the job going afk and getting ID robbed for near full service access

Your standards of playing are so high its any wonder nobody gets anything done in-game without calling for a powergamer for hire.

**Comment by bgobandit** [comment]
@lzimann making it easier for more jobs to be clowns

I'm onto you

**Comment by Grazyn** [comment]
Departments belong to those who work them. Bartender doesn't work in the theatre. He doesn't belong in there.

If he wants to play make believe with silly costumes he can ask the professionals who handle them daily.

**Comment by RocKeD** [comment]
^ This I don't see any purpose to give theater access to the bartender.

**Comment by bgobandit** [comment]
>clowns and mimes
>professional

**Comment by Grazyn** [comment]
Costumes are tools, tools designed for a very specific purpose: entertainment. There are only 2 jobs dedicated to entertainment: clown and mime. 

Yes, the bartender may want the maid costume for the maid bar gimmick, but it's the same thing as a scientist needing atmos tools like pumps and filters: he gets some of them in science, but he doesn't get atmos access just because the RPD would make it easier.

**Comment by DoctoreMad** [comment]
>clown and mime. They are professionals in their own field.

I chortled audibly!

**Comment by GunHog** [comment]
>Yes, the bartender may want the maid costume for the maid bar gimmick, but it's the same thing as a scientist needing atmos tools like pumps and filters: he gets some of them in science, but he doesn't get atmos access just because the RPD would make it easier.

This would be more accurately saying that an Engineer needs atmos tools, but does not get access to the atmos area. Clown and mime are part of the same department as the bartender, which is the Service department.

**Comment by FantasticFwoosh** [comment]
You say that like if the bartender was not there, we'd all die because we lost a vital department, or that cat costumes are not just divisive filth and don't actually need to be wheeled out every round to be enjoyable let alone shoehorned in more than regularly with more characters using it.

> Bwoink - put on the cat maid costume and let me stroke you for my own unadulterated enjoyment or you will be daybanned.

There's nothing penultimately to lose if the entire bar & theatre area was removed from the round, unlike atmos needed to breathe. And on most maps there are plenty of areas in maint where you can establish your own atmos heater/transfer or whatever or pretend to run a bar in a cat costume.

**Comment by Grazyn** [comment]
Fwoosh you don't even know what you're talking about, maids in maid cafés wear bands or frills on their hair, they don't wear cat ears and sure as hell don't wear cat tails. Cats have nothing to do with this.

Paging our resident japanese expert @RemieRichards for confirmation

**Comment by RemieRichards** [comment]
Depends where the Meido cafe is, for example if it's in Akihabara (Weeb central), you probably will see cat ears. Though even in that case they're an extension of the uniform, not a standard part of it.

**Comment by KorPhaeron** [comment]
Doesn't it make more sense to give the service job an alt service uniform instead of letting them dress up in a chicken suit?

**Comment by lzimann** [comment]
when the only purpose of the alt uniform is a fetishism content(don't try to deny it, it is one), no, it doesn't make any sense in giving the uniform. At least with theatre access, bartenders get their own choice on what theme they want to go with.

**Comment by Really-Good-Soda-Flavor** [comment]
I don't like this

**Comment by Grazyn** [comment]
Beside a single coder making the PR to add the maid outfit, do we really have so many cases of bartenders begging for costumes to warrant this change?

**Comment by lzimann** [comment]
not really, should probably just close this and move on without any of this tbh

**Comment by Cyberboss** [comment]
Agreed

**Pull request closed without merging**
