### PR TITLE
Placing a robotics factory actually disables shunting

### PR DESCRIPTION
**Pull request by YPOQ**
Broken by #28334

### CODE REVIEW

**Comment by Repukan** [comment]
Intended.

**Comment by YPOQ** [comment]
Can you clarify?

**Comment by Repukan** [comment]
Robotic factory was intended to remove shunting afaik

**Comment by YPOQ** [comment]
Indeed, this PR restores that behavior.

**Comment by CPTANT** [comment]
Just remove shunting, it adds nothing to the game except allowing a malf AI to greentext by making himself completely useless.

**Review by Cyberboss — APPROVED** [review]

**Comment by GunHog** [comment]
I feel shunting should not be affected by the factory anymore for two reasons:
- Security cyborgs were removed, thus drastically reducing the power of the factory.
- Shunting now halts the Doomsday countdown, so the shunt ability now serves only the purpose of survival for the drawback of limiting the AI's influence to its immediate visible location.

**Comment by ExcessiveUseOfCobblestone** [comment]
conversely bring shunting back to it's rightful seat on the throne at a cost of doubling the remaining time before countdown.

**Comment by KorPhaeron** [comment]
Any borg can move the AI anywhere without weakening it now so worrying too much about shunting is silly

**Comment by Cyberboss** [comment]
iF THIS NEEDS TO BE CHANGED IT SHOULD BE A DIFFERENT BALANCE PR, AS IT ASTANDS IT S A BROKEN MISTAKE FROM THE TOEHRER PR

**Pull request merged**
