### PR TITLE
Optimizes SDQL2 a bit

### PR DESCRIPTION
**Pull request by silicons**
## About The Pull Request

I was a really bad coder in 2017/whenever I did this.

Yeah so.
It turns out I basically wrote this:
while(TRUE)
  Check status
  Stop if CPU is over tick limit

The problem is, check status doesn't need to be run literally every other call, and in effect I did
while(TRUE)
  Use all CPU available
  continue

New code is:
while(TRUE)
  Check status
  Wait 0.1 seconds before checking again, like sane code should

I can honestly probably get away with changing this to every 0.2-0.5 seconds if needed, SDQL2 for the most part really doesn't need to be super accurate with when to check for query completion.

## Why It's Good For The Game

Wow, that was a bad fuckup.

## Changelog

No real player/admin facing changes, just correcting my fuckup.

### CODE REVIEW

**Comment by LemonInTheDark** [comment]
I don't know a ton about sdql, but I do know that sleep's proc archival effect can generate a not insignificant amount of overtime. Wonder if it wouldn't be better handled with a subsystem?

**Comment by LemonInTheDark** [comment]
Would also be nice to see exact numbers on this, or at least some idea of how much it helps things

**Comment by silicons** [comment]
image
only did one test query (this is on very old tgcode tho, but, SDQL2 is the exact same as current tg) but uh.

Yeaaah.
It's a busy loop
Anyways @LemonInTheDark I thought about subsysteming but the main reason I didn't yet is because SDQL2 was almost never used, and I figured the overhead of another ticking subsystem would be worse average case than the overhead of just having it be a busy loop-ish deal

**Comment by Timberpoes** [comment]
As per the contrib guidelines https://github.com/tgstation/tgstation/blob/master/.github/CONTRIBUTING.md#pull-request-process

> Should you be optimizing a routine you must provide proof by way of profiling that your changes are faster.

You must provide details of your test cases and before/after profiling the results of these test cases showcasing the improvements in performance between your optimised code and the old code.

Once this has been completed, anyone is free to remove the DNM tag.

**Review by Timberpoes — CHANGES_REQUESTED** [review]
As per the contrib guidelines https://github.com/tgstation/tgstation/blob/master/.github/CONTRIBUTING.md#pull-request-process

> Should you be optimizing a routine you must provide proof by way of profiling that your changes are faster.

You must provide details of your test cases and before/after profiling results of these test cases showcasing the improvements in performance between your optimised code and the old code.

Once this has been completed, anyone is free to remove the DNM tag.

**Comment by silicons** [comment]
Aight, gimme a bit.

**Comment by silicons** [comment]
for minimal changing variables between tests I used 1000 pieces of /obj/item/paper in a location in space on a station zlevel.
Test query: `USING PRIORITY = HIGH UPDATE /obj/item/paper IN global._range() SET x = src.x + global._rand(-3,3), y = src.y + global._rand(-3, 3), pixel_x = global._rand(-16, 16), pixel_y = global._rand(-16, 16)`, picked to put heavy load on SDQL's expression evaluation functions

without tweak:
image
image
image

with tweak of stoplag(1):
image
image
image

as you can see here it was nearly twice as fast without having a ton of the tick unnecessarily eaten by the busy loop.

@Mothblocks :+1:

**Comment by LemonInTheDark** [comment]
> Yeaaah. It's a busy loop Anyways @LemonInTheDark I thought about subsysteming but the main reason I didn't yet is because SDQL2 was almost never used, and I figured the overhead of another ticking subsystem would be worse average case than the overhead of just having it be a busy loop-ish deal

You could just can_fire = FALSE the subsystem when it's not in use couldn't you? cost's also reasonably low regardless

**Comment by silicons** [comment]
@LemonInTheDark up to you if you think it's worth it i'm willing to come make the subsystem for it

**Comment by LemonInTheDark** [comment]
Lemme read sdql code a bit closer. I have a feeling it'd help, but I don't wanna set you on a wild goose chase

**Comment by LemonInTheDark** [comment]
Looked into it. Things like `SDQL_get_all` would be very useful as subsystems rather then sleep checked operations, since we need to copy the state of the whole proc and up, including the object list we've already found. S not cheap at all, and generates a lot of spikes of lag at highpop. Harder to do though.

That aside, just making the bit you're touching now a subsystem would be useful. Moving all sleeps out would be amazing, though I realize that just like shuttle code, that's a bit tough.

**Comment by Iamgoofball** [comment]
your issue, no GBP will be issued

**Comment by silicons** [comment]
Oh fuck-

**Comment by Ryll-Ryll** [comment]
What's the status of this?

**Comment by TrashDoxx** [comment]
Ehh.

**Comment by Fikou** [comment]
KEEEVIIIIIIIIIN

**Pull request closed without merging**
