### PR TITLE
Adds the ability to create circuit floor tiles

### PR DESCRIPTION
**Pull request by VileBeggar**
:cl: Vile Beggar
add: You can now create circuit floor tiles with the autolathe.
/:cl:

[why]:  i like how these look and it's a shame that i have to make tcomms/robotics look like gordon freeman was there with a crowbar

### CODE REVIEW

**Comment by necromanceranne** [comment]
Have people replace all the halls floor tiles with these so that, when you go Delta as a Malf AI, the whole station starts flashing red.

**Comment by GunHog** [comment]
>Have people replace all the halls floor tiles with these so that, when you go Delta as a Malf AI, the whole station starts flashing red.

That is exactly what is supposed to happen! :smile:

**Review by SpaceManiac — APPROVED** [review]

**Comment by AnonymousNow** [comment]
These separated into green and blue?

**Comment by Cyberboss** [comment]
Congrats on getting your first pull request approved. Welcome to the /tg/station 13 codebase!

**Pull request merged**
