### PR TITLE
Fixes inflict_handler spells not doing burn damage in some cases

### PR DESCRIPTION
**Pull request by ChangelingRain**
Specifically, if brute damage was 0, they wouldn't do burn damage.
Also makes them use the proper procs for inflicting damage.

### CODE REVIEW

**Comment by duncathan** [comment]
What the players don't know this fixes won't hurt them

**Comment by Anonus** [comment]
Bugfixes have never hurt anything.

**Comment by Incoming5643** [comment]
(this buffs magic missile)

**Comment by duncathan** [comment]
>What the players don't know this fixes won't hurt them

**Pull request merged**
