### PR TITLE
New ruin, the Venusian

### PR DESCRIPTION
**Pull request by Fikou**
## About The Pull Request
my thing for march into mapness, ive been busy so it's not quite finished yet but im hoping to get it done fairly soon.
includes a new ruin, the venusian one, a cybersun cargo freighter
for code changes, a variation of blast doors which require a set amount of players to open them
a new cybersun decal
and a plasma cannon, as some special loot from the ruin

### Mapping March
Ckey to receive rewards: Fikou

## Why It's Good For The Game
More stuff to explore in space, introduces new mechanics that could be useful for future mappers in co-op locks.

## Changelog
:cl: Fikou, Halcyon
add: In the depths of space, the hulk of Cyber-Sun's Venusian drifts.
imageadd: Cyber-Sun decals.
add: A new high-powered plasma gun.
/:cl:

### CODE REVIEW

**Review by tralezab — COMMENTED** [review]
Not going to review until it's in a more complete state but it looks awesome. I would move the plasma gun out of the spaceruins file and break things up a bit more

**Comment by Addust** [comment]
I AM THE NAVAL ARTILLERY CANNON

**Comment by spockye** [comment]
Image plz

**Comment by Pumpkinoe** [comment]
https://www.youtube.com/watch?v=82e_v_YBTkM
VENUSIAN OOOOONEEE

**Pull request closed without merging**
