### PR TITLE
A Selection of Minor Map Fixes

### LINKED ISSUE #48800: Boxstation pharmacy has no air alarm
## Round ID:
Not relevant

## Testmerges:
Not relevant

## Reproduction:
Not relevant

### LINKED ISSUE #48962: Donut AI shutters
Issue reported from  Round ID: irrelevant (/tg/Station Terry [EU] [100% LAG FREE] [New-Dedi])

Reporting client version: 513.1507
The shutters are in space instead of a reinforced door
tgStation Terry  EU   100% LAG FREE   New-Dedi  Explosive Monitor Echo 2020-01-23 201910

### LINKED ISSUE #48963: Donut AI restorer
Issue reported from  Round ID: 128790 (/tg/Station Terry [EU] [100% LAG FREE] [New-Dedi])

Reporting client version: 513.1507
tgStation Terry  EU   100% LAG FREE   New-Dedi  Explosive Monitor Echo 2020-01-23 202828

you cant access the integrity restorer without destroying the r-window
OOOR the drawer

### LINKED ISSUE #49015: Engineering desk Windoor is inaccessible to engineers on Metatstation.
## Testmerges:
Server revision compiled on:  
Master commit: cb9c710b5d00014fc9a7334101cb90231e194618 
The following pull requests are currently test merged: 
#48901: 'Remove votebox temporarily' by optimumtact at commit c14f942739 

Local commit: 624f6e8d929c42d96c19c8d4a1eeffb5ed34ac75 
Server tools version: /tg/station 13 Server v3.2.6.2 

No reason to think this is the result of a test merge though

## Reproduction:

image
(See attached screenshot, the windoor to the left of this player character cannot be opened by somebody with engineering access, I believe I could in the past, besides it's in the ENGINEERING foyer so. 

PLEASE NOTE: I WAS DIRECTED HERE FROM THE DISCORD. I am sorry if this isn't the right place.

### LINKED ISSUE #49174: Donutstation: Harry Potter and the Paranormal Light Fixture of Experimentation
## Testmerges:

48668: 'Completely removes cloning' by kriskog at commit fde6a50633
49065: 'Disable library machine uis' by optimumtact at commit f261fc0b45

## Reproduction:

Step 1: Be a scientist.
Step 2: Run to the experimentor/bepis room.
Step 3: Go into the room with the reinforced floor.
Step 4: Examine the light fixture. Something's not right.

## The issue:
The light fixture is detached from the wall. It's floating.
image

### LINKED ISSUE #49197: Clown and Mime dorm access on Delta
## Reproduction:
Currently the clown and mime have access to the dorm with the mime blanket, and neither of them have access to the dorm with the clown blanket. Clearly these are meant to be personal individual dorms for the clown and mime.

### PR DESCRIPTION
**Pull request by EOBGames**
## About The Pull Request
A few minor map fixes. Fixes #49197, fixes #49174, fixes #49015, fixes #48963, fixes #48962 and fixes #48800. Also removes a stray chapel requests console from Delta's singularity chamber.

## Why It's Good For The Game
Less problems with maps.

## Changelog
:cl:
fix: Fixed a few minor map problems.
/:cl:

### CODE REVIEW

**Comment by Tlaltecuhtli** [comment]
can you fix paramedic access on meta box delta to the primary engineering entrance
also gl with conflicts

**Review by kriskog — APPROVED** [review]

**Comment by cacogen** [comment]
maybe it isn't in the scope of this pull but a lot/all the maps have issues such as duplicate/incorrect camera tags and missing pipes which can be seen using the Mapping debug verbs

**Comment by kriskog** [comment]
@cacogen I went through those pretty recently

**Comment by cacogen** [comment]
I was seeing issues on Meta when doing the chemistry/morgue swap. Didn't touch them though. Seemed out of scope.

**Comment by kriskog** [comment]
Did you base it off the cloning removal version of the map? I cleaned up a lot of stuff around the morgue there that was messed up in genetics move

**Pull request merged**
