### PR TITLE
Makes bubblegum possibly more fun/fair to fight maybe

### PR DESCRIPTION
**Pull request by ChangelingRain**
:cl: Joan
experiment: Bubblegum has been seen reaching through blood. Try not to get hit.
/:cl:

Significantly reworked bubblegum's attacks, it now has the following attacks;
- Attacks through blood, done occasionally and at the end of every charge.
- Spray blood if it failed to attack through blood during its normal attack sequence.
- Warp through blood if it failed to attack through blood during its normal attack sequence.
- Spawn up to 6 slaughterlings, which block enemies but not it.
- Charge at a target. May be prefaced by a blood warp or done up to 3 times if below half health.
- [x] more description, explain what the fuck I did
- [x] get testmerges watch ergo fight it get "wow this is boring" response redo attacks repeat until interesting

### CODE REVIEW

**Comment by FantasticFwoosh** [comment]
I ded pls nerf.

**Comment by PKPenguin321** [comment]
Pics?

**Comment by Durkel** [comment]
I'd really advise against balancing something with 4-5 players who kill it in mind. The vast of majority of our player base isn't autistic enough to count the time for life() ticks to fight something and will actually find something like bubblegum challenging.

**Comment by KorPhaeron** [comment]
Probably shouldn't be entirely balanced around Ergo yeah

**Comment by ChangelingRain** [comment]
Well I mean I balance stuff more around what I get from my own testing; I tend to try to get things to 'just barely outside of my own skill range' which is generally at least a little challenging to ergo.

**Comment by kevinz000** [comment]
tfw the game doesnt balance certain players, certain players balance the game.

**Comment by AdamElTablawy** [comment]
>gives bubblegum spellblade as lootdrop

UNDOCUMENTED CHANGE REEEEEEEEE

**Comment by AdamElTablawy** [comment]
also tbh the one boss who really needs a rework to be not boring as sin and wimpy to fight is Legion

fucker's like weak as fuck compared to almost anything

make him spawn full on legions instead of legion skulls for exponential spam

**Comment by Ergovisavi** [comment]
That's not an undocumented change, that's been in there for quite a while now.

**Pull request merged**
