### PR TITLE
Automatic TGS DMAPI Update

### PR DESCRIPTION
**Pull request by comfyorange**
This pull request updates the TGS DMAPI to the latest version. Please note any breaking or unimplemented changes before merging.

### CODE REVIEW

**Comment by JohnFulpWillard** [comment]
who the fuck are you

**Comment by JohnFulpWillard** [comment]
help

**Comment by JohnFulpWillard** [comment]
hey?

**Comment by calliophis-maculiceps** [comment]
hi joh,n

**Comment by JohnFulpWillard** [comment]
im being stalked

**Comment by san7890** [comment]
hiiiiiiiiiiiiiiiiiiiiiii

**Comment by optimumtact** [comment]
stop being cringe

**Pull request merged**
