### PR TITLE
Fixes projectile impacts + messages, embedding, adds deployable landmines

### LINKED ISSUE #53346: bullet impacts broke
shoot someone with a ballistic weapon
watch in disappointment as there is no impact sound or effect

### PR DESCRIPTION
**Pull request by Ryll-Ryll**
## About The Pull Request
So this had originally started as a PR to give the Captain a deployable landmine in their backpack so they could choose to lock down one small area once per round, but then I found that pellet clouds and projectiles in general were showing several issues, so this expanded to fix those as well, and the landmine deployment has been relegated to being in-code but not obtainable.

Here's a list of the fixes and improvements:
- #53001 added a fix for pellet clouds with no wounding power hitting carbons runtiming, but also preventing showing impact messages for hit carbons. This fixes the absent impact messages.
- #52912 helped projectiles with shrapnel play nice when some (i believe) reusable projectiles like lollipops failed to embed, but introduced some issues where projectiles would return from process_hit() too early which would prevent embedding attempts and impact blood effects when hitting already damaged bodyparts. This fixes those issues, including fixes: #53346
- Embed code is now a bit less messy 
- A few types of shrapnel were defining their embedding on the item rather than the projectile, giving them the wrong stats, which is now fixed. I also removed some unused stingbang subtypes.
- Embed examine messages finally now use "a" instead of "the" in descriptions ("They have [] a .38 caliber bullet embedded in their chest!" vs "They have [] the .38...")
- Shrapnel landmines now have a variable for shredding the mob who steps on it with shrapnel in addition to the ring of pellets. All landmines can be set to only become active after so many seconds from being spawned, and also properly display a message describing setting off when triggered by non-mobs.

Then there was the deployable landmine who's been cast aside at their own party. It's only obtainable through admin spawning now, but it's a tiny handheld beacon that, when used, starts a 3 second countdown, then creates a shrapnel landmine with a small radius but decent damage on the spot with a mix of brute and stamina. This inactive landmine then arms itself after another 3 seconds, and has a weak red warning light so you can't just use it as a grenade.

I don't know if giving the captain one in his bag (not his office, his bag) would actually be a good idea, but I think it could be neat for a one-shot peace of mind. You could drop it in your office maint tunnels to catch overly zealous tiders hacking into your office or save it to give yourself a bit of extra breathing room when being chased by throwing it ahead of where you're running. It can be defeated by throwing something at it or shooting it then running around a corner, and the pellets only last about 8 tiles. I think it could be neat for the cap, or if not for them, then for adminspawned roles.

## Why It's Good For The Game
Makes some pretty important fixes to projectiles and embedding, adds some neat possibilities with new landmine options

## Changelog
:cl: Ryll/Shaps
fix: Projectiles now properly display impact messages on people as well as blood impact splatters
fix: Embedded objects now properly use the "a" article rather than "the" when relevant

/:cl:

### CODE REVIEW

**Comment by Fikou** [comment]
the mine seems really useless if it takes 6 seconds for it to even arm and its a one use item, you cant use that in a chase because the other guy will just outrun it, so the only purpose is to protect some area once

**Review by Twaticus — APPROVED** [review]

**Comment by Ryll-Ryll** [comment]
> so the only purpose is to protect some area once
Literally what a landmine is made for. I was only speculating at other possible uses

**Comment by wesoda25** [comment]
If anything, a priming time + inability to carry (while primed) should be an example for other area defense items, like bear traps. 

Btw your cl doesn’t have the landmine stuff in it.

**Comment by Ryll-Ryll** [comment]
Because it's only added to the code, not the game

**Review by Timberpoes — CHANGES_REQUESTED** [review]
I'm not gonna tag each and every undoc'd proc, however there are number of procs you've edited and some you've created that are not DMDoc'd.

Are you able to do a sweep of your changes and document all new procs you've created, and as an optional extra by special request (not merge blocking) to document any procs you've modified that you know enough about to actually document?

In addition, Rohesie has conditioned me to expect a code review for leaving single-letter vars in code I've changed and where changing said vars are relatively straightforward. If you're able to cut down some of the single letter vars in for loops and the like, I'd appreciate it!

Other than that, none of these changes look too crazy.

If this is tested and working, are you happy to call it in a mergeable state after these issues are addressed?

**Comment by Timberpoes** [comment]
Also there's now a merge conflict to be resolved too!

**Comment by Ryll-Ryll** [comment]
@Timberpoes done

**Comment by AnturK** [comment]
Conflicts.

**Comment by Ryll-Ryll** [comment]
@Timberpoes @AnturK Done, again

**Pull request merged**
