### PR TITLE
Bone gel now spawns in stacks of 4 inside Paramedic and Medical ERT belts

### LINKED ISSUE #71393: Paramedic starts with only one bone gel in their medical belt, even when they have five surgical tapes.
I am not really sure, if this is even a bug, but it's at least an inconsistency.

### PR DESCRIPTION
**Pull request by atosti**
## About The Pull Request
Bone gel spawned inside player medical belts, for the roles of Paramedic and Medical ERT, now spawns in a stack of 4. Previously they would spawn with only a single stack. This new amount matches the stack size received when purchasing the identical item from a Nanomed, or ordering it in a Cargo crate.

As such, this change creates consistency around the number of uses in an fresh, "unopened" bottle of bone gel.

## Why It's Good For The Game
Creating a uniform, default stack size for bone gel keeps interactions with the item consistent and predictable. In the case of paramedics, their starting kit also includes 5 stacks of surgical tape, so having a few stacks of bone gel matches the player expectation that they have enough supplies to treat a few instances of each type of injury (rather than only one).

Addressing this discrepancy also Closes #71393.

## Changelog
:cl:
balance: Bone gel now spawns in stacks of 4 in Paramedic and Medical ERT belts
/:cl:

### CODE REVIEW

**Comment by san7890** [comment]
i believe that this should be considered a balance change so i will be updating your PR appropriately

**Comment by atosti** [comment]
I understand how it can be interpreted in that way. What would be a suggested implementation that would simply be a uniform fix as opposed to a balance? My main issue with the current form of bone gel is that surgical tapes are given as a stack of several, whereas bone gels are given as a single stack, which I think is confusing (especially to newer players).

Should they both be uniformly adjusted to only a single stack for both uniformity and to better encourage purchasing more supplies from Nanomeds?

**Comment by san7890** [comment]
no i think this change as fine as it is, the reason for labelling it as a balance is just so people have the right idea if they wish to offer constructive criticism as to why this change is the way it is rather than assuming "oh they're fixing something that needs to be fixed"- when i don't particularly see that to be the case in this specific instance

**Comment by Spookuni** [comment]
You might want to [No GBP] it for them then San, since it does seem to be unintended in general

**Comment by coiax** [comment]
[NOGBP] is for "whoop I made a mistake please don't give me points for fixing my own mistakes" generally.

This will have a meaningful balance impact, even if it's really just removing an inconistency. (Although 👍 this always annoyed me.)

**Pull request merged**
