### PR TITLE
Adds IRC bot to travis

### PR DESCRIPTION
**Pull request by CorruptComputer**
Tells #coderbus when the build finishes and if it passed or failed.

### CODE REVIEW

**Comment by Mloc** [comment]
:-1: causes join/quit spam

**Comment by CorruptComputer** [comment]
:+1: Tells us if things broke.

**Comment by optimumtact** [comment]
I'm not sure this is necessary, the github notifications should be enough, and maintainers shouldn't merge broken code at any point.

**Comment by Jordie0608** [comment]
With @optimumtact and @Mloc on this, would probably be more annoying than useful really.

**Pull request closed without merging**
