### PR TITLE
Updates alien whisper ability icon

### PR DESCRIPTION
**Pull request by ChangelingRain**
To better match the alien talk bubble.
yup
New on left, old on right.

:cl: Joan
imageadd: Alien whisper ability has a new icon
/:cl:

### CODE REVIEW

**Comment by WJohn** [comment]
Sure why not :+1:

**Comment by Bawhoppen** [comment]
>feature freeze

**Comment by Supermichael777** [comment]
icons are not features

**Comment by Bawhoppen** [comment]
I've heard nothing but excuses

**Comment by duncathan** [comment]
How many times do we have to tell you that sprites are and always have been exempt @Bawhoppen

**Comment by Bawhoppen** [comment]
then why were my sprite changes shot down

**Pull request merged**
