### PR TITLE
Reduce Carpenter hammer force (this thing can open locked gun crates!)

### PR DESCRIPTION
**Pull request by MrMelbert**
## About The Pull Request

Carpenter hammer force 20 -> 17
Carpenter hammer throwforce 20 -> 14
Carpenter hammer demo mod 1.25 -> 1.15

## Why It's Good For The Game

You can buy this thing in the black market for 250 credits and it's strong enough to open gun crates from cargo

image

## Changelog

:cl: Melbert
balance: Carpenter hammer force 20 -> 17
balance: Carpenter hammer throwforce 20 -> 14
balance: Carpenter hammer demo mod 1.25 -> 1.15
/:cl:

### CODE REVIEW

**Comment by Ghommie** [comment]
Why not 18 or 19? Since the problem is that the hammer can open locked crates, that should be enough.

**Comment by carlarctg** [comment]
thats kinda the point, lmao? chainsaws are much easier to get and do the same?

**Comment by Loafin34** [comment]
to be fair carpenter hammers would probably be able to knock off the lock on crates

**Comment by MrMelbert** [comment]
> Why not 18 or 19? Since the problem is that the hammer can open locked crates, that should be enough. 😕

It has a demo mod of 1.25

> Why are you lowering the force instead of the demolition modifier? The modifier is what pushes it to crate breaking, not the base force

I think the modifier is cool

**Comment by breadcrombs** [comment]
atleast make it 17, having it as 15 will just make it a boring tool that breaks glass by a tiny bit faster than a drill or saw

**Comment by CCC23** [comment]
I mean yea thats kinda its whole thing also you can just get a chainsaw to break gun crates and thats even stronger

**Comment by MrMelbert** [comment]
> I mean yea thats kinda its whole thing also you can just get a chainsaw to break gun crates and thats even stronger

Chainsaw is not normal sized

> Atleast make it 17, having it as 15 will just make it a boring tool that breaks glass by a tiny bit faster than a drill or saw

17 still puts it above threshold for closets, though I could lower the modifier by a smidge

**Comment by GuillaumePrata** [comment]
Braking down the modifier out of .25 slices just make me feel we are becoming a MOBA balancing team trying to find the perfect number to leave minions with 1 digit HP to make players life harder.

But on a more serious note, we already have 20 damage knives on the uplink, wouldn't it be more interesting to just lower the main damage so each has a narrower niche?

Sometimes I think we should just push the locker armor up so it is easier to make weapons designed for it.
The low armor makes it quite hard to split weapons from a crew/structure focus.

**Comment by MrMelbert** [comment]
> Sometimes I think we should just push the locker armor up so it is easier to make weapons designed for it. The low armor makes it quite hard to split weapons from a crew/structure focus.

Player health pool doesn't offer a lot of granularity on that front ultimately

**Comment by Ghommie** [comment]
> > Why not 18 or 19? Since the problem is that the hammer can open locked crates, that should be enough. 😕
> 
> It has a demo mod of 1.25

I see. If that's the case, I'd rather lower the demo mod a bit and leave it in the 17-19 range, since the main appeal of the hammer is that it's a kinda decent weapon with a special death sound when used.

**Comment by Holinka4ever** [comment]
> > thats kinda the point, lmao? chainsaws are much easier to get and do the same?
> 
> Chainsaw is not normal sized

Yeah, because indeed carpenter hammer is normal sized weapon with 20 damage, honestly, these argument would be valid rather than "this hammer can break security crates!!!!11!" ,and then dying from  simple observation that cargo slackers using chainsaws to get armory weapons in years.

Use normal argument to nerf stuff that you dont like, cause currently on is really out of place if you actual play the game.

**Comment by MrMelbert** [comment]
> Yeah, because indeed carpenter hammer is normal sized weapon with 20 damage, honestly, these argument would be valid rather than "this hammer can break security crates!!!!11!" ,and then dying from simple observation that cargo slackers using chainsaws to get armory weapons in years.
> 
> Use normal argument to nerf stuff that you dont like, cause currently on is really out of place if you actual play the game.

what?

**Comment by Sakamoto4ka** [comment]
I'm going to make a black market, save up money, wait a minute for delivery to finally break a crate instead of using spear or chainsaw

**Comment by Holinka4ever** [comment]
> what?

So you are insist for a clear answer? Okay:

Thing is, your argument about that you can open crates by carpenter hammer is unvalid, because before hammer, people using chainsaws, and after that it came, cargo still using chainsaws to break security crates. Nothing like really change.

We also should take in charge that carpenter hammer need to be roll into shift, cause its not 100% always in, also in mind to craft black market receiver, to not loose your stuff upon teleportation.

You _cant_ just pay 250 credits for a weapon with 20 damage and being able to fit in belts and bags, it literally sounds like that blackmarket uplink is sounds like vending machine, gosh.

As i see, a lot of factors wasnt there to include , but there are should be in, insist that you just dont like 20 damage weapons that crewmembers can get in various ways.

**Comment by MrMelbert** [comment]
> Thing is, your argument about that you can open crates by carpenter hammer is unvalid, because before hammer, people using chainsaws, and after that it came, cargo still using chainsaws to break security crates. Nothing like really change.

My argument isn't solely that these can open secure crates, it's that they're *powerful enough to* open security crates.

That includes everything *under* crates, like shutters and closets - closets being a *lot* more problematic (it's basically an emag at that point) 

I just picked out crates as an example to you, the reader, as to what their upper capabilities are

> We also should take in charge that carpenter hammer need to be roll into shift, cause its not 100% always in, also in mind to craft black market receiver, to not loose your stuff upon teleportation.

Don't think this is particularly relevant

> You _cant_ just pay 250 credits for a weapon with 20 damage and being able to fit in belts and bags, it literally sounds like that blackmarket uplink is sounds like vending machine, gosh.

Not sure what this means

> As i see, a lot of factors wasnt there to include , but there are should be in, insist that you just dont like 20 damage weapons that crewmembers can get in various ways.

I guess? I think people should be more careful about adding easily obtainable items with big numbers and big demolition modifiers, because otherwise it hurts the security of a lot of things that Are Supposed To Be Secure

**Comment by Deultus** [comment]
Who asked for this and why? the fact that someone breaks something has never been a problem, maybe you can still reduce the damage of the crusher or accelerator simply because they can smash locker round start

**Comment by MrMelbert** [comment]
> the fact that someone breaks something has never been a problem

image

**Comment by Holinka4ever** [comment]
> > Thing is, your argument about that you can open crates by carpenter hammer is unvalid, because before hammer, people using chainsaws, and after that it came, cargo still using chainsaws to break security crates. Nothing like really change.
> 
> My argument isn't solely that these can open secure crates, it's that they're _powerful enough to_ open security crates.
> 
> That includes everything _under_ crates, like shutters and closets - closets being a _lot_ more problematic (it's basically an emag at that point)
> 
> I just picked out crates as an example to you, the reader, as to what their upper capabilities are

Once again, giving less information will lead to these type of outcomms, anyway... Basicly chainsaw do the same job, yeah, in way it cant be fit into bags or belts, you still can do these various stuff, and no one blamed on it, even once... except you for a hammer.

> > We also should take in charge that carpenter hammer need to be roll into shift, cause its not 100% always in, also in mind to craft black market receiver, to not loose your stuff upon teleportation.
> 
> Don't think this is particularly relevant

Its indeed relevant, mechanics that based on luck are indeed relevant, and being part of the random number generator should be aplied on any changes.

> > You _cant_ just pay 250 credits for a weapon with 20 damage and being able to fit in belts and bags, it literally sounds like that blackmarket uplink is sounds like vending machine, gosh.
> 
> Not sure what this means

Do you know how black market uplink works? It main gimmic? How much time need spend to set up it? Cause statement like "you can buy it for 250 credits" sounds like to scam people, who dont check game for times.

> > As i see, a lot of factors wasnt there to include , but there are should be in, insist that you just dont like 20 damage weapons that crewmembers can get in various ways.
> 
> I guess? I think people should be more careful about adding easily obtainable items with big numbers and big demolition modifiers, because otherwise it hurts the security of a lot of things that Are Supposed To Be Secure

Powerfull stuff are powerfull due of being part of low quantity and rng based. Ita justified as we see.

**Comment by Deultus** [comment]
> > the fact that someone breaks something has never been a problem
> 
> image

This only confirms the fact that this is not a problem.

**Comment by SomeoneYouProbablyKnow** [comment]
> > > the fact that someone breaks something has never been a problem
> > 
> > 
> > image
> 
> This only confirms the fact that this is not a problem.

Lol. You should go and read all the comments under that PR. Even spears and lockers are a contentious issue. For good reason i might add. But also wtf is a carpenters hammer

**Comment by Deultus** [comment]
> Lol. You should go and read all the comments under that PR. Even spears and lockers are a contentious issue. For good reason i might add. But also wtf is a carpenters hammer

Ratio 👎👍 shows quite enough

**Comment by SomeoneYouProbablyKnow** [comment]
... i don't think you understand how talking about things works. Anyway how's this for 👍 👎 ratio

**Comment by zoomachina** [comment]
> Lol. You should go and read all the comments under that PR. Even spears and lockers are a contentious issue. For good reason i might add. But also wtf is a carpenters hammer

"contentious"
image
what's even funnier is that in that other PR, people are talking about how there needs to be an item that's specifically capable of breaking lockers, but the carpenter hammer is literally that item (locked behind black market no less), and it's getting nerfed to the point where it's incapable of doing that

**Comment by MrMelbert** [comment]
Anyways just cause I was curious here's a list of every item > 20 force when factoring demo mod (+ wielded or active) 

The *only* non-antag, non-bulky (or large) item readily available to the crew is the Deathnettle. I just thought that was cool

```
item: the instakill rifle - force: 60 - demo: 1 - weight: bulky // admin
> item: Powercrepe - force: 30 - demo: 1 - weight: bulky
> item: the deathnettle - force: 25 - demo: 1 - weight: normal-sized
item: the bo staff - force: 10 - demo: 1 - weight: bulky // admin
item: the toolbox - force: 19 - demo: 1.25 - weight: bulky // antag
item: the metal baseball bat - force: 20 - demo: 1.25 - weight: huge // admin
item: the energy axe - force: 40 - demo: 1.5 - weight: normal-sized // admin
item: the energy sword - force: 3 - demo: 1.5 - weight: small // antag
item: the cyborg energy sword - force: 3 - demo: 1.5 - weight: small // antag cyborg
item: the energy saw - force: 18 - demo: 1.5 - weight: normal-sized // antag cyborg
item: the energy cutlass - force: 3 - demo: 1.5 - weight: small // antag
item: the energy blade - force: 30 - demo: 1.5 - weight: bulky // antag
item: the hardlight blade - force: 30 - demo: 1.5 - weight: bulky // antag
item: the eldritch longsword - force: 30 - demo: 1 - weight: bulky // antag
item: the haunted longsword - force: 30 - demo: 1.5 - weight: bulky // antag
item: the bloody halberd - force: 17 - demo: 1 - weight: huge // antag
> item: the fire axe - force: 5 - demo: 1.25 - weight: bulky
> item: the bone axe - force: 5 - demo: 1.25 - weight: bulky
> item: the metallic hydrogen axe - force: 5 - demo: 2 - weight: bulky
item: the boarding axe - force: 5 - demo: 3 - weight: bulky // antag
> item: the mech removal tool - force: 5 - demo: 1.25 - weight: huge
item: the heavy crowbar - force: 20 - demo: 1.25 - weight: normal-sized // space ruin
item: the possessed chainsaw sword - force: 30 - demo: 1 - weight: bulky // admin
> item: the chainsaw - force: 13 - demo: 1.5 - weight: huge 
item: THE GREAT COMMUNICATOR - force: 13 - demo: 1.5 - weight: huge // special
item: the double-bladed energy sword - force: 3 - demo: 1.5 - weight: small // antag
item: the claymore - force: 40 - demo: 1 - weight: normal-sized // antag
item: the claymore - force: 24 - demo: 1 - weight: normal-sized // gateway
item: the cutlass - force: 30 - demo: 1 - weight: normal-sized // antag
> item: the old cutlass - force: 24 - demo: 1 - weight: normal-sized // fishing 
> item: House Edge - force: 12 - demo: 1 - weight: huge // black market 
> item: the katana - force: 40 - demo: 1 - weight: huge // very rare
item: the energy katana - force: 30 - demo: 1 - weight: normal-sized // antag
> item: the unmarine mastodon - force: 17.1 - demo: 1.3 - weight: gigantic // fishing
> item: the nessie-fish - force: 16.5 - demo: 1.3 - weight: huge // fishing
> item: the monocloning jumpercable - force: 19.2 - demo: 1.2 - weight: bulky // fishing
> item: the chainsawfish - force: 27 - demo: 1.5 - weight: bulky // fishing
> item: the diamond-tipped pickaxe - force: 19 - demo: 1.15 - weight: bulky // mining
> item: Big Slappy - force: 30 - demo: 2 - weight: huge
item: Fine Tipped Pen - force: 5 - demo: 9000 - weight: tiny // admin
```

**Comment by zoomachina** [comment]
> item: House Edge - force: 12 - demo: 1 - weight: huge // black market 

this isn't helping your point

**Comment by mc-oofert** [comment]
> > item: House Edge - force: 12 - demo: 1 - weight: huge // black market 
> 
> this isn't helping your point
> call me a tider, but I don't think lockers and such should be protected by the hand of God from all harm, beyond antag/admin chicanery and incredibly rare occurences, which are made rarer and rarer pr after pr

Breaking closets and lockers is only relevant if you're powergaming or an antagonist which usually have tools for this anyway

**Comment by MrMelbert** [comment]
> > item: House Edge - force: 12 - demo: 1 - weight: huge // black market
> 
> this isn't helping your point 

weight: huge is the operative point there

**Comment by Holinka4ever** [comment]
> > > item: House Edge - force: 12 - demo: 1 - weight: huge // black market
> > 
> > 
> > this isn't helping your point
> 
> weight: huge is the operative point there

... you actually dont know how blackmarket works?  
Also house edge is worse example to use by the way, with way of getting and need to craft it, and item perfomance.

**Comment by zoomachina** [comment]
> Breaking crates and lockers is only relevant if you're powergaming or an antagonist which usually have tools for this anyway

1) are you implying that trying to acquire a useful item is powergaming, no matter the circumstances?
2) some antags don't have antag gear whatsoever
3) even if what you said was true, limiting locker breaking to antagonists only is an incredibly ill-advised move

I simply don't see why a black market item's gimmick being "normal-sized item with high demolition power" is such an issue, especially since as Melbert pointed out, there are barely any theoretically crew-accessible items that are also capable of breaking lockers, and all of them have something else going on (like Big Slappy and House Edge)

**Comment by mc-oofert** [comment]
countless ways to break a locker without antag tools without a spear

**Comment by Xackii** [comment]
When useless hammer has at least something useful:

**Comment by carlarctg** [comment]
"chainsaw isn't normal sized" no shit thats the entire thing that makes this item remotely interesting... you need to buy it from the black market for a sizable sum of money and in exchange you get a smaller demolition tool

to get a hammer:
1. craft black market uplink
2. get money for hammer
3. buy hammer and 
A: go into space and try to catch it before someone else grabs it from one of the 4 random directions it's thrown at
B: pester security to let you into the armory to get the hammer where it always teleports into
C: spend considerable amounts of time setting up a LTSRB

to get a chainsaw:
1. go to autholathe and print the ingredients

this mildly interesting item that serves the same function as a thrown spear now has absolutely nothing interesting about it except for making people do weird sounds when they die to it. it being a demolition tool elevated it from a pointless item to something with some enjoyable niche.
it's okay to get an upgrade after spending effort to do so. not everything needs to be behind a techweb.

**Comment by Dorsisdwarf** [comment]
I don't know how much relevance chainsaws being large items has when discussing the balance of an item being able to smash open cargo crates?

Usually if cargo's forcing open gun crates they're either openly using an emitters setup or smashing them in the warehouse (area they control where nobody else really sees). Being more convenient to carry around on your person doesn't seem to be that huge of an advantage in this use case. If you're stealing the gun crates to break open yourself elsewhere, I think the _gun crate_ might be significantly more attention-attracting than carrying a chainsaw, which even the silicons rarely bat an eye at.

**Comment by DaydreamIQ** [comment]
On this day TG was divided over a fucking hammer.
Anyways breaking open crates should be something you need to work towards and black market items are so laughably easy to obtain idk what crack people are smoking saying its difficult

**Comment by Exester509** [comment]
> On this day TG was divided over a fucking hammer. Anyways breaking open crates should be something you need to work towards and black market items are so laughably easy to obtain idk what crack people are smoking saying its difficult

Apparently fireaxes and chainsaws take a lot of work to create

**Comment by Holinka4ever** [comment]
> > On this day TG was divided over a fucking hammer. Anyways breaking open crates should be something you need to work towards and black market items are so laughably easy to obtain idk what crack people are smoking saying its difficult
> 
> Apparently fireaxes and chainsaws take a lot of work to create

Hydrogen fireaxes are not so popular nowadays, just fireaxes are getting stolen each shift in both sides. Yeah

**Comment by EnterTheJake** [comment]
> On this day TG was divided over a fucking hammer. Anyways breaking open crates should be something you need to work towards and black market items are so laughably easy to obtain idk what crack people are smoking saying its difficult

Baton nerf TM : I sleep

lil hammer nerf: Real shit.

**Comment by Sk1Wass3r** [comment]
> > > On this day TG was divided over a fucking hammer. Anyways breaking open crates should be something you need to work towards and black market items are so laughably easy to obtain idk what crack people are smoking saying its difficult
> > 
> > 
> > Apparently fireaxes and chainsaws take a lot of work to create
> 
> Hydrogen fireaxes are not so popular nowadays, just fireaxes are getting stolen each shift in both sides. Yeah

roundstart craftable 24 damage chainsaw: I sleep

literally any other crew available weapon with more than 15 damage: real shit

**Comment by Loafin34** [comment]
i would make it more expensive and be done with it.

**Comment by Yebok24** [comment]
Just close it already
Снимок экрана 2024-12-11 152550

**Comment by Yebok24** [comment]
Just close it already
image

**Comment by mc-oofert** [comment]
or remove the hammer outright its just a worse chainsaw

**Comment by Getonus** [comment]
> or remove the hammer outright its just a worse chainsaw

I'd ask you not to take copium in public places

**Comment by Sakamoto4ka** [comment]
> > On this day TG was divided over a fucking hammer. Anyways breaking open crates should be something you need to work towards and black market items are so laughably easy to obtain idk what crack people are smoking saying its difficult
> 
> Baton nerf TM : I sleep
> 
> lil hammer nerf: Real shit.

cause all sigmas wanna baton nerf

**Review by ArcaneMusic — APPROVED** [review]
I'm approving this purely due to these changes being disregarded in the original PR's review stage, and I stand by my original assessment.

https://github.com/tgstation/tgstation/pull/87070#discussion_r1789139561

**Pull request merged**
