### PR TITLE
Fixes not being able label humans with appropriate names

### PR DESCRIPTION
**Pull request by Iamgoofball**
dreamseeker_2017-03-19_19-18-03

### CODE REVIEW

**Comment by coiax** [comment]
I think the commit title may suggest this isn't a serious change

**Comment by ChangelingRain** [comment]
Absolutely not.

**Comment by MoreRobustThanYou** [comment]
looking back at this made me laugh, @Iamgoofball

**Comment by PKPenguin321** [comment]
This PR but unironically

**Pull request closed without merging**
