### PR TITLE
Fixes cable_coil children not merging each other

### LINKED ISSUE #13086: Engineering cyborg unable to refill cable coils
An engineering cyborg on Sybil was unable to refill the cable coil module from cable coils, maybe this has changed or something but it definitely used to be possible. It also had 250 floor tiles, dunno if that's supposed to be the case.

Replicated by spawning myself as a borg with the rudimentary transformation and then selecting the engineering module, using up all my coil with awful wire art, and then spawning a cable coil and trying to refill. Unsuccessful.

### LINKED ISSUE #14240: Engieborg's wire module not refillable from cable coils
**Server:** Sybil

**Revision:** Didn't grab the exact number; it's whatever revision was active around 2015-12-31 15:00 UTC+01:00.

**Problem Description:** Few months ago, refilling your cable coil as engieborg was as simple as clicking a cable coil lying around with it. This doesn't seem to work anymore; when clicking the coil, nothing happens, and no message is displayed.

Didn't see anything along this vein in the changelog, so I'm guessing it's unintended. Might be wrong.

**What did you expect to happen:** The message 'you join the cable coils to form X lengths of wire' to pop up, and the cable coil module to be filled with the corresponding amount.

**What happened instead:** Nothing.

**Why is this bad/What are the consequences:** Means you have to recharge between solars, instead of using one of the conveniently-placed-for-this-purpose cable coils floating around the arrays. Makes it more of a hassle to fix other wiring, when you can't pick up pieces anymore.

**Steps to reproduce the problem:**
1. Activate cable coil module
2. Use up some wire
3. Click cable coil lying on the floor

**Possibly related stuff:** Only tried with the cable coils on the solar arrays.

### PR DESCRIPTION
**Pull request by tkdrg**
Fixes #14240
FIxes #13086

### CODE REVIEW

**Comment by phil235** [comment]
Fixes #13086 as well, I think.

**Comment by tkdrg** [comment]
It does, adding that to the OP.

**Comment by phil235** [comment]
This will also mean you can merge cable coils of different colors together. I don't remember if this used to be possible, but it's currently not doable and this PR will change that.

**Comment by tkdrg** [comment]
It used to be possible, yeah. I don't know why it was removed, or if it was on purpose.

**Pull request merged**
