### PR TITLE
[s] FREE DRONE

### PR DESCRIPTION
**Pull request by KazeEspada**
F R E E `   `D R O N E

### CODE REVIEW

**Comment by F-OS** [comment]
this is a meme pr, please meme elsewhere.

**Comment by Cheridan** [comment]
sorry sir but we've met our meme quota for this year, please try again in 2017

**Comment by KazeEspada** [comment]
Sorry, not sorry.

**Comment by Xhuis** [comment]
You should probably make them immediately hack upon being created, considering that making drones all-access ventcrawling greytiders isn't a good idea.

**Comment by KazeEspada** [comment]
Its april fools. GHOSTS ARE FREEZING. And other chaos.

**Pull request merged**
