### PR TITLE
Fixes character appearances - no more bald albinos

### LINKED ISSUE #8383: Character appearances don't apply on roundstart
Everyone spawns as the same albino bald guy, names are ok as is hair color if you grow some later but most of the settings just don't work period even if you set and save them again.

Reassigning gender helps restore a lot of the missing settings (just updating icon in general probably is enough) they are still THERE, they just aren't expressed on round start

### PR DESCRIPTION
**Pull request by MrPerson**
Fixes #8383

Also removed two defunct comments.

### CODE REVIEW

**Comment by Incoming5643** [comment]
There are still other parts of that bug not handled here, but I guess we can tackle that next.

Merge like Blanic

**Comment by MrPerson** [comment]
What other parts?

**Comment by Incoming5643** [comment]
Most/all of these settings are not saving/loading correctly and always default to these default settings. Some of them also do not toggle correctly within the screen.

d10_icon

**Comment by Miauw62** [comment]
that is a separate bug and should be fixed.

**Comment by Iamgoofball** [comment]
Why hasn't this been merged yet

**Pull request merged**
