### PR TITLE
GAGSifies Plushies

### PR DESCRIPTION
**Pull request by Thunder12345**
## About The Pull Request

Resprites space lizard plushies to match regular lizards, and also resprites carp, slime and snake plushies. All have been set up to use GAGS.

image

## Why It's Good For The Game

They look much more plush now and can be more colourful in future.

## Changelog
:cl:
image: Space lizard, carp, slime and snake plushies have been resprited and set up to support GAGS.
/:cl:

### CODE REVIEW

**Comment by Helg2** [comment]
I don't think that making carp plushie's eyes like this is a good idea, as plush is pictured from aside it will just look like bad drawing of pigeon.

**Comment by Thunder12345** [comment]
> I don't think that making carp plushie's eyes like this is a good idea, as plush is pictured from aside it will just look like bad drawing of pigeon.

That’s what a space carp's eyes look like though

**Comment by Helg2** [comment]
> That’s what a space carp's eyes look like though

Never noticed it xd

**Comment by DingleFlop** [comment]
Ohmigosh... I have a Manuel character this sorta thing would be perfect for!

**Comment by san7890** [comment]
image

should probably fix these

**Review by san7890 — APPROVED** [review]

**Pull request merged**
