### PR TITLE
goofball meme pr #949302-Δ ver. 3

### PR DESCRIPTION
**Pull request by Iamgoofball**
stupid link made by stupid person
actually adds a brain damage line about polls

### CODE REVIEW

**Comment by kevinz000** [comment]
you're brain damaged.

**Comment by PKPenguin321** [comment]
pfft

**Comment by Cyberboss** [comment]
@tgstation/commit-access This gets closed: I close all my PRS.

**Comment by GunHog** [comment]
There needs to be a rule against deceptive PR titles, I am getting sick of it.

**Comment by kevinz000** [comment]
i had my sound off jokes on you golfball.

**Comment by WJohn** [comment]
can you stop

**Comment by RemieRichards** [comment]
@WJohn Don't anger the great stoner in the sky.
24hr rule for all PRs now.
weed has spoken.

**Comment by Cyberboss** [comment]
@kevinz000 I almost did it

**Comment by Anonmare** [comment]
Jokes on you my adblock blocked it

**Comment by RemieRichards** [comment]
Oh, it's a strawpoII
didn't even notice
even if I had I've been burned by strawpoII before, damn screamers.

**Pull request closed without merging**
