### PR TITLE
Viewer Discretion Advised: Adds a graphic content filter for Wounds

### PR DESCRIPTION
**Pull request by Ryll-Ryll**
## About The Pull Request
Legends say that pretty much immediately after the first spessmen began showing up on SS13, the .357 revolver was added to the game and people have been murdering each other ever since. SS13 has had murder and cartoon violence in its DNA basically from the get-go, but the addition of Wounds was a pretty big jump in how visceral that violence is. That's mostly by design, I put a lot of effort into making the descriptions and sounds I put into the game visceral because I think it makes fighting for your life much more engaging when you're picturing pulverized, broken bodies instead of just clicking someone until they turn sideways, but I get that cracking someone's skull open on a table with a nasty crunch sound isn't everyone's bag.

Recently, I was looking at skyrat's repo and noticed they have a preference for seeing certain extreme messages, and thought prefs would be a good answer. This PR adds a preference toggle (defaulted to off) that has the following effects when enabled:

- Detailed wound occur and examine texts are replaced with simple descriptions with the wound name
- Wound sounds are replaced with generic chimes with longer, lower tones representing more serious injuries (this is just a rough idea, open to suggestions that are less OOC-ey)

Here's a screenshot of it in action:

[](https://i.imgur.com/yoySxzT.png)

This isn't intended to create a continually expanding filter for all of the violence and gore in the game, since as I said before, violence is a core part of SS13. This is intended to reduce the impact of a few specific features that some people have said they found overwhelming, specifically the sounds of bone breaking/slashes/pierces and some of the severe and critical description texts, to be more even with the level of violence we had before. Mind that I probably have some more neatening up to do along the way, especially with dismemberment wounds.

## Why It's Good For The Game
The majority of feedback I got on the original descriptions and sounds were positive and liked the extra crunch it added to the game, but a few people found it offputting. This offers a relatively painless and low maintenance way for people to opt out of the extra gore without putting them at a mechanical disadvantage. 

## Changelog
:cl: Ryll/Shaps
add: Added a new preference called 'Reduce Wound Graphic Content' that genericizes the descriptions and sounds from suffering wounds, perfect 
/:cl:

### CODE REVIEW

**Comment by optimumtact** [comment]
This is utterly rediculous

If someone can handle text based gore descriptions they are so childish that it would be better for them not to play at all.

I will be closing this in 24 hours.

**Comment by ATH1909** [comment]
wow, this is a really wholeso-

> This is utterly rediculous
> 
> If someone cannot handle text based gore descriptions they are so childish that it would be better for them not to play at all.
> 
> I will be closing this in 24 hours.

_sigh_

**Comment by infoman-cor** [comment]
Germans are one step closer to playing ss13!

On a more serious note I have to agree with oranges. I get the idea but it is just waaay to inconsistent, SS13 is a violent game, why bother having a toggle that only censors one of the **many** horrible things that happen in this game?

**Comment by Ryll-Ryll** [comment]
The sounds and levels of description are far more graphic than any other part of the game, in our codebase or elsewhere, which I felt a bit guilty about. That said, if maintainers aren't interested, I'm not going to crusade for it.

**Comment by necromanceranne** [comment]
Ah yes, text, the medium to which people can't attribute visualisation at all and cannot possibly find disturbing given sufficient detail and audio cues. 

Imagine reading text and visualising things. Nobody has done that before. Why should we start now!

**Comment by cacogen** [comment]
oranges® is right®

**Comment by anconfuzedrock** [comment]
you could just make them less edgy and more informative period.

**Comment by tralezab** [comment]
I love the visceral descriptions

**Comment by Mickyan** [comment]
They are needlessly verbose by default if you ask me

Not surprised people are complaining about accessibility options though, I can imagine the outrage they must feel whenever they see a wheelchair ramp

**Comment by san7890** [comment]
One of the things I liked about the wounds update was how verbose everything was, ranging from the actual attacks to the flavorful descriptions of scars. Defaulting a diet version of these wordy (but good) descriptions reels like it negates a lot of time and effort put in the first place.

**Comment by Moja10** [comment]
By Oranges logic, you are now allowed to upload porn sounds to the game, if you don't like it you are just childish! Go play on Bee, you big toddler! Rename /tg/ Bagil to /tg/ baby, for babies who don't want hardcore porn in their speasemans!

**Comment by Ryll-Ryll** [comment]
broh what

**Comment by ExcessiveUseOfCobblestone** [comment]
we've had descriptions where people slice themselves open in a variety of ways, other wild forms of suicide, and visual cues of someone pressurizing themselves so much to the point they explode in a pile of gore.

We even have an interaction where you die by being put through a trash grinder.

The game is visceral, if it actually bothered people I don't think they would have started complaining only when wounds were added. Heck we game-ify suicide to the point where people do it just because it's funny, which I think is a much more uncomfortable subject for people than the imagery in wound descriptions.

**Comment by optimumtact** [comment]
I suspect the people complaining about this are people who think they will gain some mechanical advantage in game over their fellow players by having shorter text.

**Comment by AdamElTablawy** [comment]
It could just be that some people are kind of uncomfy with visceral descriptions of wounds, oranges. There are the types of people who'll just want mechanical advantages, yeah, but if you made the allowance for gender verbs on TG (which is a good thing) then, I mean, there's nothing _wrong_ with this either.

Like, it's really just a preference toggle for 'I don't want to see visceral descriptions of wounds.' Dismissing it as childish and just deciding to close it is kind of shit of you.

**Comment by SpaceManiac** [comment]
If the descriptions are too graphic, they should be made less graphic. A preference flag and two sets of descriptions are an undue maintenance burden.

**Comment by Eskjjlj** [comment]
Don't really care about gore but i hate how long the descriptions are when you examine someone who is wounded. No one has time to read it all and it hides more important information.

**Comment by optimumtact** [comment]
@AdamElTablawy Adding a spectrum of genders and not reducing the graphic nature of wounds are consistent positions, both involve me contending that people who play this game need to be adult enough to confront the nature of the human experience within the limited graphical canvas we have to paint it with.

That aside, I'm not suggesting these things are not evocative, they are, I'm a voracious reader and I understand the ability text has to completely transport you to another world.

My point was badly put across, but it's actually that if these text descriptions affect you to the point where you are uncomfortable, then I would be concerned about the level of maturity you have to not be able to accept that ultimately this is still fiction. If these affect you even more to the point of triggering any trauma, then you should not be playing ss13, given the free form nature of an online massively multiplayer sandbox.

Spacemaniac has already covered the technical issues, so I will refrain from repeating them, but rest assured they play a large part in the decision to.

**Comment by necromanceranne** [comment]
I don't read chat in action heavy moments. That's not even a concern that occured to me. It is definitely spam heavy but the game has always been spam heavy and so I don't bother reading the chat.

Nor do I necessarily think it was a sound precedent to start making light of suicide either but I doubt anyone is going to be given the green light to axe that, even if I would happily see that removed, personally. I feel like it is too late given one of our last additions to that feature was from a maintainer.

As someone who is affected now and again by anxiety around injury and gore, and it being something I am very hit and miss on (leaning into 'if it is realistic enough I get anxiety attacks'), the initial sounds for wounds were a bit much for me and I voiced that concern with ryll. I appreciate they took it on board and that they changed it. Honestly I can count on one hand when the gore in ss13 has been a bit much for me because the game is so cartoony and the violence so absurd it's palatable as well as being so lacking in visual information it won't really occur much. But when it gets bad, mostly from devs not thinking about how something might be perceived could be too much, I don't have much choice in it, I just feel awful for a long time because I can't stop feeling anxious about it after encountering it. I get really bad anxiety already and this compounds it. 

I don't see any reason why a filter shouldn't be added because it at least lets you manage incoming information for you and only you. Plenty of modern games have accessibility options just like this for good reason. It lets more people engage with the game but control the peripheral stuff that isn't necessary as the core part of the experience. Verbose wounding descriptions one of them. We understand our spacemen get fucked up. We can explain this in fairly analytical and dry terms to remove the emotional response that might be disturbing and just instead keep it to a gameified 'my spaceman is in danger'. That's easy and simple and hurts nobody.

(I didn't necessarily find these too much for me personally but I emphasise all the same, is my point)

**Comment by Winterous** [comment]
As someone who would normally be on the side of "harden the fuck up", I can definitely appreciate that the SOUNDS might uh, make people a bit squeamish. They're pretty gross, and I'd have no objection to having a 'lower impact' version available in prefs. But I think having the text modified is a bit silly.

**Pull request closed without merging**
