### PR TITLE
Moves documentation from the component readme to doc comments

### PR DESCRIPTION
**Pull request by ninjanomnom**
Also improves some wording and code structure
We never remembered to update the readme anyway

### CODE REVIEW

**Comment by ninjanomnom** [comment]
It's pure fantasy to hope that if I improve readability of core component systems I'll get another person working on them but I can try T.T

**Comment by optimumtact** [comment]
this is the wrong approach

it's in the readme so it appears in the module system.

The docs on how to actually use something should not exist on the item itself, that's for the individual details of each proc

http://codedocs.tgstation13.org/code/datums/components/README.html

**Comment by ninjanomnom** [comment]
I can't even find the readme when starting from the top level of the codedocs. The readme before contains a brief overview and then a bunch of details about specific vars and procs used in the system. The first part is still in the readme here and the second part should be moved to the thing they're actually describing.

**Comment by optimumtact** [comment]
suppose

**Comment by SpaceManiac** [comment]
Merge conflict.

We can waffle back and forth on organization. Adding more doc comments to vars/procs/etc is good and the PR seems fine as long as you're not removing information or spreading it out too uselessly.

dmdoc is designed to support directory README files.

**Comment by ninjanomnom** [comment]
...I didn't even realize that you had a pr open before for components docs, sorry oranges

I'll update this later tonight

**Comment by optimumtact** [comment]
then again neither did I notice this was for the same thing.

besides merging the two will likely make it even more accurate

**Pull request merged**
