### PR TITLE
Instant Atmos Unwrenching

### PR DESCRIPTION
**Pull request by 13spacemen**
## About The Pull Request
Unwrenching empty atmos pipes/devices is now instant
## Why It's Good For The Game
Worst part about playing atmos is how long it takes to set up builds, especially if you want to unwrench all the ports and pipes that come after the main yellow Pure loop. Also annoying if you misclick and have to spend time unwrenching an empty pipe
Just QOL for atmos players
## Changelog
:cl:
qol: Unwrenching empty atmos pipes/devices is now INSTANT
/:cl:

### CODE REVIEW

**Comment by Mothblocks** [comment]
@LemonInTheDark

**Comment by CRITAWAKETS** [comment]
oh goodness no this time is a good way to go "wait oh shit wrong pipe"

**Comment by Pickle-Coding** [comment]
This will look dumb.

**Comment by 13spacemen** [comment]
> oh goodness no this time is a good way to go "wait oh shit wrong pipe"

you can just as instantly wrench it back if you unwrench the wrong pipe, or if you're worried about losing low pressure gas then I'll make it instant only on empty pipes

**Comment by 13spacemen** [comment]
Ok I have changed it so only completely empty pipes/devices are instantly unwrenched

**Pull request merged**
