### PR TITLE
Throwing an active stunbaton now has a chance to stun people!

### PR DESCRIPTION
**Pull request by lzimann**
:cl: Lzimann
add: Throwing active stunbatons now has a chance to stun whoever it hits!
/:cl:

Throwing a stunbaton now has a 75% chance of stunning someone(if it is active and has charges).
Stunprods have 10% chance

fix token: #18931

### CODE REVIEW

**Comment by Armhulen** [comment]
complete madman, but I like it

**Comment by X-TheDark** [comment]
I wonder if people will start making 10 improvised stunprods to abuse this.

**Comment by lzimann** [comment]
Maybe.

**Comment by Zilenan91** [comment]
stunprod pneumatic cannon on the 1st setting

Ghetto taser

**Comment by lzimann** [comment]
emergent gameplay

**Comment by xxalpha** [comment]
Why not 100% chance? This would be a lot more interesting if it was 100%. 35% means nobody will throw it because it won't pay off most of the time.

**Comment by Zilenan91** [comment]
100% would be broken

**Comment by lzimann** [comment]
100% is a bit too much, maybe 50% then?

**Comment by xxalpha** [comment]
100% is not a bit much. If you are not getting guaranteed or almost guaranteed results when throwing your stun baton away, why would you ever throw your stun baton at someone who will pick it up and use it on you?

**Comment by RandomMarine** [comment]
Keep the 33% for improvised batons, but make the real thing have a better shot.

**Comment by lzimann** [comment]
@xxalpha style points

**Comment by Zilenan91** [comment]
35% is perfect as it is. It shouldn't be a coinflip to get a 7 second instant stun.

**Comment by xxalpha** [comment]
Make it at least 90% chance to stun, 10% in byond rng is enough to cuck you regularly if you spam your throws.

**Comment by Zilenan91** [comment]
90% would be ridiculous

**Comment by KorPhaeron** [comment]
I think this bypassess shields the way its coded

**Comment by lzimann** [comment]
@KorPhaeron stun_baton actually checks for shield

**Comment by InsaneHyena** [comment]
This kills the sleeping carp.

**Comment by Zilenan91** [comment]
Is sleeping carp still in the uplink?

**Comment by lzimann** [comment]
Yes it is. And how does it kill?

**Comment by bgobandit** [comment]
needs a clumsiness check or else it is a massive buff to the clown

**Comment by kevinz000** [comment]
.. BEcause sleeping carp doesn't deflect thrown objects
Also this is adding too much rng into combat, I don't want to deal with getting stunned by a baton while I'm trying to gun someone down :/

**Comment by Fox-McCloud** [comment]
Don't like this at all; everyone and their brother doesn't need access to a ghetto taser.

**Comment by Iamgoofball** [comment]
just make it a rand(1,100) for cattle prods

**Comment by Zilenan91** [comment]
High capacity power cells are hard to come by as a simple assistant. The most you can usually get without breaking into robotics is 3 and that's only like a 40% success rate and I'm not sure if that many prods even fit in a pneumatic cannon.

**Comment by Fox-McCloud** [comment]
It's not assistants that I'm worried about.

It's science having yet another feather in its cap for insanely powerful tactics  while (as you pointed out, whether you intended or not), everyone else doesn't get to do this (well, minus engineering and hypothetically cargo).

I really don't understand why a melee weapon inherently needs to have ranged properties.

**Comment by lzimann** [comment]
Ok done, now stunprods have a 10% chance of triggering while stunbatons have 75%

**Comment by Zilenan91** [comment]
70% for regular stunbatons? That's way too high man.

**Comment by jughu** [comment]
Rip sleeping carp

**Comment by KorPhaeron** [comment]
35 for all was good why did you get tricked into listening to github comments

**Comment by lzimann** [comment]
alright i'll just keep 35% and 10% for stunprods then

**Comment by AdamElTablawy** [comment]
how about a scaling chance depending on the power cell in the stunbaton

35% for highcap, 45% for supercap, 55% for hypercap, 75% for bluespace cell

**Comment by Zilenan91** [comment]
no

**Comment by JJRcop** [comment]
think of it like throwing a knife, if you get hit by the hilt, it doesn't do nearly as much damage as the blade, and stun batons have a much lower surface area where it would stun you than a knife has where it would slice you. 35% sounds fine.

**Pull request merged**
