### PR TITLE
Fixes Gr3y.T1d3 delaming the SM

### LINKED ISSUE #36841: Greytide virus can bolt open SME chamber airlocks
The greytide virus event (events/prison_break) can bolt open the SME chamber airlocks since it affects area/engine. On lowpop, this usually results in delamination and round end.

From what I can see, random events aren't supposed to break the engine - filters, pumps etc. in engineering have the critical_machine var set to TRUE, which exempts them from the grid check event.

My best bet is that the greytide virus is older than the SME (singulo doesn't break if a bunch of doors open).

### PR DESCRIPTION
**Pull request by ShizCalev**
Fixes #36841

### CODE REVIEW

**Review by vuonojenmustaturska — DISMISSED** [review]

**Comment by RandomMarine** [comment]
I bet someday someone is going to try to creep this var onto the permabrig doors.

**Comment by PKPenguin321** [comment]
sad but i can absolutely see it happening

**Comment by chesse20** [comment]
no support its funny that it can cause a delam by bolting open the engine doors and its rare enough where its not an issue

**Comment by Cyberboss** [comment]
Yeah, I disagree with this pr myself

**Comment by ShizCalev** [comment]
Hm.... Perhaps cut it down to just Omegastation then where delam means half the station gets nuked?

**Comment by 81Denton** [comment]
Random events blowing the engine isn't really fun, I mean SME filters/pumps are already exempt from grid check after all.

**Comment by RandomMarine** [comment]
There's still the rare meteor or even space dust that manages to slip past the barricades and knock out a heat exchange pipe.

**Comment by Barhandar** [comment]
These don't immediately create a dangerous-to-unfixable environment (you can still engage freezer loop after damage to h/e pipes, while only sillycons can easily fix the airlocks without actually getting in the cold burnmix/nitrogen combo engine typically outputs).

**Comment by CPTANT** [comment]
Or you just use the engineering remote.....

**Review by Cyberboss — DISMISSED** [review]

**Comment by chesse20** [comment]
make it a server vote i think its a cool feature rather than a bug

**Comment by Dennok** [comment]
Also opening of server rooms and slime kill rooms is freezing a station. Please fix it.

**Comment by ShizCalev** [comment]
@dennock just turn off the freezers.

**Pull request merged**
