### PR TITLE
Add an electric guitar and removes duplicate guitar sound files

### PR DESCRIPTION
**Pull request by Niknakflak**
:cl: NikNak 
rscadd: Adds an electric guitar for those more hardcore space crewmembers who have a desire to shred. /:cl:

Adds an electric guitar for those more hardcore space crewmembers who have a desire to shred.  It currently sounds pretty ass though so I'm open to anyone wanting to touch up the sound files or contact the expert (cuboos) or someone to make them better.  Current sounds were licensed under creative commons but then heavily heavily edited by me.  (Probably why they sound like ass)  I will continue to work on the sounds anyway.

image

Also removed duplicate sounds in the regular guitar folder because boggart thought that F flats and C flats were a thing when he already had B naturals and E naturals.  No merge token because this fix is in the same PR which was a """bug""".

Demo:  https://file.house/dVtz.mp4    Warning: may hurt ears.
Sprites by Nienhaus.  Forgot to mention that.

### CODE REVIEW

**Comment by Durkel** [comment]
To be fair, all instruments sound like shit.

**Comment by Niknakflak** [comment]
Not true, you obviously have nightmares of midi instruments because the guitar and violin sound quite nice now since the system in which they function off has changed

**Comment by Supermichael777** [comment]
Well someone has their gain set too high.

**Comment by xxalpha** [comment]
I checked and those files are no duplicated, what are you doing?

**Comment by Niknakflak** [comment]
You are tone deaf, sorry.

**Comment by xxalpha** [comment]
Adding yet another instrument without adding the missing notes for other instruments and this one sounds too awful and will be spammed to annoy people.

:-1:

**Comment by Niknakflak** [comment]
I don't think you understand how instruments or music works....

**Comment by Bawhoppen** [comment]
niknak you don't actually have to name it eguitar you can name it electricguitar it doesn't actually make a difference besides you feeling like a hotshot

**Comment by Niknakflak** [comment]
I dont understand

**Comment by RemieRichards** [comment]
I don't speak music, are you trying to say like, Cb5 is covered by Bb5?

**Comment by optimumtact** [comment]
You know what, I kinda like it.

**Comment by Incoming5643** [comment]
I said it before and I'll say it again, megaman X guitar

**Comment by PKPenguin321** [comment]
how does the DOOM theme sound on this

**Comment by RemieRichards** [comment]
@xxalpha it's true, they are duplicates, @Niknakflak helped me hear it, for example, Cb7 == Bn6

**Comment by Nienhaus** [comment]
I made the sprites. Sorry if not the best, I didn't have much time to work
on them.
On Jun 11, 2016 3:59 PM, "Remie Richards" <notifications@github.com> wrote:
>
> @xxalpha it's true, they are duplicates, @Niknakflak helped me hear it,
for example, Cb7 == Bn6

**Comment by TheWiznard** [comment]
I really want to try all my midis on this now

**Pull request merged**
