### PR TITLE
Adds new gun dry firing sounds

### PR DESCRIPTION
**Pull request by ShizCalev**
Added new gun dry firing sounds (recorded by myself) to distinguish it from the fire select/flashlight toggle/multitool sound ([empty.ogg](https://raw.githubusercontent.com/tgstation/tgstation/master/sound/weapons/empty.ogg)). 

Varied the length of the trigger pull slightly so the sounds don't get repetitive.

:cl: ShizCalev
soundadd: Revamped gun dry-firing sounds.
tweak: Everyone around you will now hear when your gun goes click. You don't want to hear click when you want to hear bang!
/:cl:

I'll probably end up rerecording empty.ogg, as well as recording all new sounds for the rest of the gun interactions sometime as well.

### CODE REVIEW

**Comment by Buggy123** [comment]
can this replace the smg empty noise please?

**Comment by ShizCalev** [comment]
The empty sound already plays with the alert. You're free to open a PR removing the alert sound if you so desire.

**Comment by Buggy123** [comment]
If this is merged I will.

**Comment by banthebantz** [comment]
the alert sound is god tier, **No**

**Comment by Buggy123** [comment]
Its a **ALARM CLOCK**. WHO WANTS TO HEAR A ALARM CLOCK? The noise that ALWAYS wakes you up from your PEACEFUL SLUMBER so that you can do MIND NUMBING MENIAL WORK for EIGHT HOURS OR MORE while SEVERELY SLEEP DEPRIVED. This happens FIVE DAYS OUT OF EVERY SEVEN. I honestly know of no other sound that causes a serious involuntary reaction, other than the fucking BEEP BEEP BEEP of every alarm clock in existence.

**Review by ninjanomnom — APPROVED** [review]

**Pull request merged**
