### PR TITLE
Adds owo, fap, twerk, and getwood emotes.

### PR DESCRIPTION
**Pull request by CthulhuOnIce**
[Changelogs]: # (Your PR should contain a detailed changelog of notable changes, titled and categorized appropriately. This includes, new features, sprites, sounds, balance changes, admin tools, map edits, removals, big refactors, config changes, hosting changes and important fixes. An example changelog has been provided below for you to edit. If you need additional help, read https://github.com/tgstation/tgstation/wiki/Changelogs)

:cl: CthulhuOnIce
add: Added some new emotes.
/:cl:

[why]: I think emoting is super important in the life of an otaku such as myself, and i'd like that to be expressed in my space simulations.

### CODE REVIEW

**Comment by CitrusGender** [comment]
what

**Comment by vuonojenmustaturska** [comment]
How do i delete someone else's repo

**Comment by CitrusGender** [comment]
image

cursed image
cursed image

**Comment by nichlas0010** [comment]
I love you

**Comment by Ratvar** [comment]
I don't

**Comment by nichlas0010** [comment]
**Nichlas0010** *twerks at* @CitrusGender

**Comment by CthulhuOnIce** [comment]
Thanks for all the support friends, make sure to hit that like button, subscribe, and hit the bell icon

**Pull request closed without merging**
