### PR TITLE
Xenos are no longer barricade-intolerant

### LINKED ISSUE #20202: Xenos cant attack wood barriers
image

We couldnt attack them at all new meta.

ITS LIKE SIGNS. ALIENS DONT LIKE WOOD

### PR DESCRIPTION
**Pull request by MMMiracles**
:cl: MMMiracles
fix: Xenomorphs can now actually damage barricades.
/:cl:

Fixes #20202

crisis averted

### CODE REVIEW

**Comment by phil235** [comment]
Alien attack usually use the slash sound instead of a generic smashs sound. See https://github.com/MMMiracles/-tg-station/blob/65a6a93141a2be075ae84187ff002175918b31f9/code/game/machinery/machinery.dm#L272

**Comment by phil235** [comment]
take_damage(50, BRUTE, 0)  
Unless you want both sounds played.

**Comment by MMMiracles** [comment]
oh, right. good point.

**Comment by kilkun** [comment]
>buffing xenos

for what reason

**Comment by Jazaen** [comment]
Because otherwise they can't, to my knowledge, damage barricases in a timely manner, through which you can shoot at them.

**Comment by WJohn** [comment]
Oh, I thought you were talking wooden barricades.

This is fine, I think.

**Comment by kilkun** [comment]
god forbid the xenos have to get creative and adapt their playstyle instead of just acting like the greytide with a different sprite

god forbid wooden barricades are actually useful for anything

**Comment by MMMiracles** [comment]
I don't even like xenos much but how can you make sense of them not being able to smash through wooden planks but can do shit like pry open metal airlocks and smash down reinforced windows?

**Comment by kilkun** [comment]
same reason hot plasma and chilled oxygen don't explode when they interact outside of a TTV.

same reason wizards can disintegrate an ascended shadowling but can't disintegrate a megafauna.

because its a video game and its not supposed to make sense.

**Comment by MMMiracles** [comment]
yes, lets keep the mass-producable barricade capable of stopping 7ft behemoths in their tracks because their afraid of getting a splinter or something.

you are right that wouldn't make any sense

**Comment by WJohn** [comment]
This is not debatable, it is a bug. They used to be able to smash these, and now they can't. The fix is up, there shouldn't be any controversy over this "buffing" xenos.

**Comment by kilkun** [comment]
im just saying that if xenos are so braindead that the only way they can think of to get around something is to hit it, that's textbook PICNIC

**Comment by Kromgar** [comment]
We used acid instead dipsit but it should be easier to break down a wooden barricade

**Comment by kilkun** [comment]
should it though?

should it really? wood's pretty tough.

**Comment by MMMiracles** [comment]
i honestly want to know where you're getting your wood from if its strong enough to withstand a xeno's strength fully.

**Comment by kilkun** [comment]
would you expect a tiger to break through a properly built wood barricade?

the answer to that is no. no it wouldn't be able to. xenos are space tigers, no matter what the colossal trainwreck memefest that was the sequel tried to paint them as.

**Comment by Kromgar** [comment]
XENOS ARENT TIGERS

**Comment by kilkun** [comment]
correct.

they are space tigers.

**Comment by Dorsisdwarf** [comment]
What sequel. Are you imposing outside lore on our deep OC not-a-ripoff-of-a-copyrighted-product aliens?

**Comment by kilkun** [comment]
did that excuse work with the OC jelly aliens

**Comment by KorPhaeron** [comment]
Being arbitrarily unable to interact with an otherwise destructible object with no feedback isn't a balance thing

**Pull request merged**
