### PR TITLE
firedoor pr

### PR DESCRIPTION
**Pull request by Tlaltecuhtli**
🆑 Tlaltecuhtli
balance: firelocks now have less steps ( weld wrench screw crowbar weld to remove and frame circuit wrench to make)
balance: firelocks steps now all take the same time of 2s
balance: destroying a firelock only has 40% chance of creating the frame
balance: lowered the hp of firelock and frame a bit
/🆑
firelocks are literal satan, they are useless and a pain to make and ugly now it takes like 10s to remove or place which helps rebuilding places as they usually confuse/annoy people and never get made

https://user-images.githubusercontent.com/33834933/87551678-ff6b7e80-c6b0-11ea-88e5-47add74b2e3e.png
^ this picture is why i set the 70% to not create a frame when destroyed, its ugly to see all these random frames around

### CODE REVIEW

**Comment by ArcaneMusic** [comment]
The hero we need. Firelocks are such an infinite pain to handle in the aftermath of a bombing, but similarly if you're trying to free up an airlock/passage way getting rid of them is practically out of the question considering the time investment to get them all ready to remove, plus if they're easier to setup then they might see more use in construction projects.

**Comment by ATH1909** [comment]
deja vu

**Comment by Acer202** [comment]
>Firelocks are such an infinite pain to handle in the aftermath of a bombing

Currently, all you need to do to repair a blown up  firelock is crowbar+wrench it, and it becomes a fixed, working firelock. Like last time this PR was up, I'm all for making the steps faster and the construction easier, but if you're deconstructing the firelocks after an explosion instead of just dragging them into place and repairing with crowbar+wrench, then you're being silly and creating more work for yourself later when you need to build them all over again. Assuming they're ever rebuilt, which never seems to happen.

**Comment by LemonInTheDark** [comment]
broken firelocks stop airflow right? It's semi important that they're always gonna do that, could you keep it in?

**Comment by kriskog** [comment]
> broken firelocks stop airflow right? It's semi important that they're always gonna do that, could you keep it in?

Dont think the frames do? Either way, it wouldnt make sense for them to.

**Comment by Tlaltecuhtli** [comment]
the timer is similar to "wrench and crowbar"

**Comment by trerri** [comment]
why isnt this merged already? what's the argument against it

**Pull request merged**
