### PR TITLE
[Boxstation]Minor Map Changes

### PR DESCRIPTION
**Pull request by Steelpoint**
This PR effects several minor and major changes to Boxstation. Listed below are the minor changes, followed by the major change.

* New space based grilles above the perma wing, to help block asteroids from venting perma.
* Security surgical tools are now inside a duffel bag
* Moved Security Hardsuits to new Sec EVA Storage near the perma wing
* Re-added the 'insane asylum' to Perma Brig. Renamed as the Sanitarium
* Medical Laptop added to HoS's Office
* Electrified most space facing security windows (Still less electrified than other stations brigs)
* All Heads of Staff Rooms are now electrified. This being the HoS, CMO and RD.

New security area below (added a extra camera after the fact)
secpic1

I admit a lot of these changes are security related, but that's simply because I play a lot of the role, and thus find ways to slightly update or improve it. 

If you have any suggestions for more changes, please suggest them here or on the Boxstation feedback thread: https://tgstation13.org/phpBB/viewtopic.php?f=11&t=21&start=300

Thanks for reading.

:cl: 
tweak: Several minor mapping changes have been made to Boxstation, of note are the addition of electrified grilles around all head offices and the inclusion of a security 'sanitarium' and a new 'security EVA' within the perma wing.
/:cl:

### CODE REVIEW

**Comment by FantasticFwoosh** [comment]
Expect the conveyor belts to get cannibalised (high metal content), all we need now is for the conveyor belts to feed into a auto-assembler machine for regular borg parts, though there was nothing wrong before with using ALT click to sort through the pile.

**Comment by Steelpoint** [comment]
The belt is a 'aesthetic' choice, not practical.

**Comment by GunHog** [comment]
You are missing a fuel tank, two holopads (One for the mech bay, another for robotics lab), and the AI display within the room. The southern portion of the mech bay used to be R-walls, but that section is now part of the robotics lab, I guess. Did you decide to get rid of the windoor for the surgery room? I would have liked to keep it. Anyone who does not like having to open it can just click it to keep it open forever.

Another note, some of your items (Flashes, metals, etc) do not seem well sorted. Maybe add a table next to the console and move some things there so you do not have several mixed piles.

Old Robotics below:
old robotics

**Comment by Aloraydrel** [comment]
Should of kept the rack that was below the drawer for all the toolboxes/belts/welding helmets

**Comment by Steelpoint** [comment]
I've somewhat divided the equipment between the two Robo areas, hence why it might seem a bit unseemly. 

I did re add the fuel tank, I just took the picture before I added it. I'll address the issues raised and put up a new image.

**Comment by ChangelingRain** [comment]
Can you please, please, please split these changes up so we can allow or deny parts of them instead of having to review and allow/deny all of them at once?

**Comment by KorPhaeron** [comment]
Atomize your PRs please.

No need for the security changes to be bundled with robotics changes

**Comment by RemieRichards** [comment]
the surgery bit should be white tbh.

**Comment by Steelpoint** [comment]
If a certain aspect of this PR is denied I can remove it after the fact.

I'm also hoping to add more changes to the PR as suggestions and 'inspirations' come to me.

**Comment by KorPhaeron** [comment]
Every time maintainers remind people of procedure politely by phrasing it as a question they misinterpret it as a suggestion, sad

**Comment by Shapsy** [comment]
Most misleading PR title 2017

**Comment by Steelpoint** [comment]
Minor changes is a acceptable title, its mostly security related because no one has posted about suggested boxstation changes on the forums for a year and the old suggestions are out of date or unviable. 

I still think that if a certain aspect of this PR is denied then I can simply remove it, but if one part of the PR must be removed then I can do so, just state which one that is.

**Comment by GunHog** [comment]
>Every time maintainers remind people of procedure politely by phrasing it as a question they misinterpret it as a suggestion, sad

I hate it when people do this, it is confusing. I find it best to be clear, yet polite. State what you mean such that there is no ambiguity. Do not make it look as if you are giving him a choice when you are actually giving an order. 

Dealing with map conflicts is a major pain, so I can see a reason why he would try and bundle modifications into one PR. I have no opinion on the Security changes, but I am happy to take the Robotics changes. Please PR the Robotics changes first, Steelpoint, as you are probably going to be held up for weeks with Security map changes.

**Comment by Niknakflak** [comment]
I expected sec changes when I  clicked on this PR and wasn't disappointed.  Misleading title is misleading

**Comment by Steelpoint** [comment]
Fuck off Niknak.

-----

My PR is still open to further suggestions on positive changes to Boxstation, minor item additions or small changes to a room.

The reason its mostly sec changes is because I predominately play security on Box and as such I become aware of possible minor changes I can effect to the area.

**Comment by InsaneHyena** [comment]
I don't like new robotics. The conveyor belts are silly, and while old robotics may seem to small and cluttered, it also means that barely need to move much between the front desk, the surgery table and the fabricator. I also prefer to be able to see the front desk while doing surgeries.

**Comment by Shadowlight213** [comment]
To be fair, niknak has a point.

**Comment by PKPenguin321** [comment]
Actually a sec nerf assuming you removed the hardsuits from the armory. Now you can space them/break into them from the permabrig without the warden noticing. :+1:

**Comment by Steelpoint** [comment]
Correct, I removed the hardsuits from boxs armoury.

**Comment by ExcessiveUseOfCobblestone** [comment]
can you move the camera to, say, beside the window of the security asylum? Something about the AI seeing people approaching from that side via space is bothering me.

Also I /REALLY/ hate those stupid straight jackets. I understand why they're in there [especially since meta has them as well] but they are REALLY REALLY LAME.

**Comment by Niknakflak** [comment]
I'll fuck off when you stop buffing your job.  

Let's go over your points
>New space based grilles above the perma wing, to help block asteroids from venting perma.
This is present on and off mostly through-out the other maps, not a huge deal.  Not present at all in metastation and sorta present in the other station maps.
>Security surgical tools are now inside a duffel bag
Not a big deal, I think only box doesn't have them in the bag at this point.
>Moved Security Hardsuits to new Sec EVA Storage near the perma wing
Metastation has this, it's hit or miss, not a big deal, but it is buffing sec
>Re-added the 'insane asylum' to Perma Brig. Renamed as the Sanitarium
Some stations have it, some don't.  It was removed from box because nobody used it, likely nobody will continue to use it but ya know, just gotta buff sec again
>Medical Laptop added to HoS's Office
Isn't this the huge argument you had with sweaterkittens over medical stuff in security.  It's not a monitoring console but still.  None of the stations have it, it's a buff to sec needlessly.
>Electrified most space facing security windows (Still less electrified than other stations brigs)
Mostly true except for pubby, Pubby has almost no electrified windows.
>All Heads of Staff Rooms are now electrified. This being the HoS, CMO and RD.
what? Why? Is the CE not a head? What is the purpose of this?
>Addition of Cautery to Robotics Surgery
I always thought it didn't have it so that medical surgery would be the place for real operations and robotics was only there for debraining mostly.

You're closing the gap in some of the different map discrepancies but only address the things in box, aka, only coding to effect yourself.  Some of these aren't a big deal since other stations all vary in what security has, but some of these are also just needless buffs and I will never stop posting on your PRs because all you do is buff your own damn job so you can win more and that's scummy as utter fuck.

This PR itself is weird.  Why would you mix in a fuck ton of sec changes with a robotics remap.  You labeled this PR as "Minor changes" + "big robotics remap" when in reality it's "Tons of sec changes" + "Minor robotics remap" and the remap isn't even good.  The appeal of the conveyor belts in the old robotics was that it was long and it actually looked like an assembly line.  These conveyor belts are 3 tiles long and literally just move the shit printed 2 tiles away.  It's useless, dumb, and your PRs should be separate anyway and the fact that you say "I can just remove the offending thing in my PR" instead of just atomizing in the first place is itself scummy and manipulative because then someone has to choose between not having something at all or merging it all together when in reality, there should be an equal choice and chance for both things to be merged or not merged.    This is a long comment but I'm tired of you pulling this shit.  Maybe I'm putting too much effort in again and I should go back to shitposting and not bothering but I figured I'd actually try this time.

**Comment by KorPhaeron** [comment]
Atomize

**Comment by optimumtact** [comment]
Every time stellio,

**Comment by ExcessiveUseOfCobblestone** [comment]
"Thous Shalt Not Push Request Thine Own Department, Especially If Thine Department is Security"

Excerpt from The Ten Coderbusmandments.

**Comment by optimumtact** [comment]
actually it's  more about making sure you don't bundle changes to a wide range of disparate things in one pr because although some of the changes might be good even a single negative change will inevitably sink that pr to the bottom of the sea

**Comment by Steelpoint** [comment]
I did state beforehand that I would atomize this PR, I would appreciate if I would be allowed to do so.

I can't react instantly to any demanded or desired change to my PRs.

It hasn't even been 24 hours since I opened the PR.

**Comment by Steelpoint** [comment]
Still would appricate this be reopened to so I can effect the desired changes.

Also, someone should write out actual rules so people can read them, instead of asking people to follow unwritten ones.

**Comment by Steelpoint** [comment]
I guess I should rephrase, what I mean is that the rules should be in a very visible area. 

literally just putting a link to the 'contribution' file in this repo's wiki page, intead of filling it with memes and jokes, would have solved my issue.

-----

On topic, I'll be updating this PR shortly now, thanks @Jordie0608

**Comment by Steelpoint** [comment]
I've removed the Robotics alterations, I'll put it in another PR.

**Comment by optimumtact** [comment]
Everyone else manages to follow this one simple rule with only one or two corrections required, you seem to be a repeat offender

**Comment by optimumtact** [comment]
as it is you've still got a tonne of changes such as the security remaps mixed in with head rooms being electrified which should ideally be different discussions

**Comment by Steelpoint** [comment]
The atomiation of my PRs is a rare issue I've run into, at least its not one I've had for a year or so. You could argue that about the Centcom changes but I felt the PMC additions were heavily intertwined with the other changes.

I also think the changes I'm proposing in this PR are minor enough to not warren many individual PRs for their alterations, this is also considering how mapping PRs usually, from my experience, are very prone to merge conflicts.

I'm not trying to be malicious, I'm trying to be practical.

**Comment by optimumtact** [comment]
The other perspective it that it just looks like you're trying to bundle changes you know will be unpopular with ones that are worthy of consideration

Anyway at the end of the day the only person it harms is you as your PR will attract more negative attention and the good aspects will be lost.

**Comment by Steelpoint** [comment]
I'm very open to other people making minor suggestions on mapping changes.

Besides, aside from the electification (which is far, far, more tame than what other stations do) this is more of a sec nerf, with the Hardsuit being moved out of the very secure armoury and into the isolated Sec EVA room, akin to most other stations.

**Comment by jughu** [comment]
>atomize your prs kor said
Picks the security side and buffs it more

**Comment by XDTM** [comment]
Speaking about the cautery, don't forget robotics is also supposed to install implants and replacement limbs.

**Comment by Steelpoint** [comment]
Cautery is included in the remap PR.

If that PR is denied I'll put up another PR that just puts the cautery in on the current setup.

**Comment by Niknakflak** [comment]
You never addressed my long post, I made an effort

**Comment by Steelpoint** [comment]
Was going to address your points @Niknakflak  it but I wanted to sleep on it.

* Moving Hardsuits to a seperate EVA room is a buff and nerf, more so a nerf. The Warden no longer has immediate viewing access to the Hardsuits, and must now check on them in a separate, and distant, room. It's also easier for someone to steal the Hardsuits or deny access to them. However bombing the armoury now won't make it harder for sec to get their Hardsuits.

* I hardly see the Sanitarium as 'buffing' security, its more of a fluff room than anything else, it'll have a very minor impact on any sort of balance.

* The Medical Laptop is not the Crew Monitoring Console, it has access to medical records which are not game breaking. Also one already spawns in the Sec Medbay.

* On Box only the HoP and CE's offices are electrified, so I simply added electrical grilles to the other heads that don't have them.

* Robotics kinda needs a cautery now, from what I've been told.

**Comment by optimumtact** [comment]
I'm cautious on straightjackets and muzzles since they tend to be abused in shitty ways

**Comment by Steelpoint** [comment]
We already have straightjackets in the Box Sec Medbay, which have been moved to the new Sanitarium.

**Comment by Niknakflak** [comment]
Most of things you said to refute my points are how your "buff" is really a "nerf" for some obscure reason.

**Comment by Steelpoint** [comment]
Firstly I question why you think moving the straightjackets from the Sec Medbay to a new Sanitarium is considered a buff.

Secondly I gave you my opinion on the moving of the security Hardsuits out of the armoury. You may see it as a buff, I claim its more disadvantaging to the Warden.

**Comment by Niknakflak** [comment]
Alright, back to giving up.

**Comment by Steelpoint** [comment]
It just seems like your opinion on 'buffing' something is just the act of changing or moving items around the brig, and in doing so that's automatically a bad thing.

Literally the only thing being added to the brig in this PR is a medical laptop and a few electrified grilles, which both can be seen as barely a buff (especially since I do leave a few space facing windows unelectirifed. The rest of the PR, at least for sec, is just moving things around. 

If you think moving hardsuits out of the very secure armoury, and into a isolated room far away from anyone usually walking by, is a buff, then its no wonder you shitpost.

**Comment by Niknakflak** [comment]
the armoury gets bombed often and with it, the suits usually go.  This makes it so traitors, or whoever, can no longer bag two birds with one stone and instead have to take deliberate measures to dispose of both the suits in one area, and the armoury in the other area.

You just see this as a nerf, but it's also a buff.  You say I shitpost because you disagree with how I see it as a buff.  I see it as a buff because I view from the above point of view and the fact that you are terribly biased and I don't believe in good conscious that you are doing this as a nerf.

**Comment by Steelpoint** [comment]
I want to add the Sec EVA because I think its cool, and at the time I did not think it would be seen as a significant buff.

**Comment by Steelpoint** [comment]
Note.

I won't update the merge conflicts this PR has until after my Robotics PR is resolved, since I would rather only have to fix the merge conflicts for this PR once, not twice.

**Comment by ExcessiveUseOfCobblestone** [comment]
> Medical Laptop added to HoS's Office

Why?

> Electrified most space facing security windows (Still less electrified than other stations brigs)

See above

> All Heads of Staff Rooms are now electrified. This being the HoS, CMO and RD.

See Above

You should provide reasoning for each in the Heading in compliance with the PR template.

**Comment by Steelpoint** [comment]
I forgot half of those reasoning's are hidden on the forums.

The addition of the Med Laptop and Electrified Grilles to the HoS's office and brig respectively is more to bring box brig into line with the majority of other station brigs. The Medical Laptop is more a aesthetic addition with a minor usefulness and the extra electrified grilles shore up areas of the brig that no long have electrified grilles. I should note that even with these additions box brig is still significantly less electrified than most other station brigs.

The head rooms being fully electrified is meant for consistency purposes, since right now the HoP, CE and to a minor extent the HoS are the only ones with electrified grilles.

**Comment by Steelpoint** [comment]
I'm going to rethink this later on. I'm not feeling some of these proposed changes.

I'll revisit this PR later on.

**Comment by GunHog** [comment]
If it is any consolation, I get the bullying too, so I know how it feels.

**Comment by Steelpoint** [comment]
I'm not finished with the PR, I'm likely just going to revert the Sec EVA addition.

Just want to mull it over a bit.

**Comment by Shadowlight213** [comment]
I don't like having the rd's windows be electrified, since it makes it much harder to access the robotics control console. Sometimes the rd isn't available/dead and a roboticist has to break in.

**Pull request closed without merging**
