### PR TITLE
Upgrades Joy Mask, 4 New Emojis

### PR DESCRIPTION
**Pull request by 13spacemen**
## About The Pull Request
CONCEPT PORTED FROM CITADEL WITH MODIFICATIONS
Adds 4 new emojis to the joy mask, you can switch the emoji with alt-click
Renamed joy mask to emotion mask
And you can use internals with it now

Pensive, Flushed, Angry emojis have new sprites by Twaticus
Pleading emoji by Wallemations
joysnew
pleading

## Why It's Good For The Game
Joy mask is one of the best things in the autodrobe, more choice and now you can use internals

## Changelog

:cl: Twaticus, Wallemations
add: 4 new emojis added to the joy mask! Check the AutoDrobe
tweak: You can now use internals with the joy/emotion mask
/:cl:

### CODE REVIEW

**Comment by Striders13** [comment]
Excuse me sir, SIR, ACTUALLY it's emoji not emoticon please get it right......

**Review by MrMelbert — CHANGES_REQUESTED** [review]

**Comment by LemonInTheDark** [comment]
why make them internals capable? they're uh, not

**Comment by 13spacemen** [comment]
> why make them internals capable? they're uh, not

i think the mask is very neat and you can already breathe through the clown and mime masks (and a few others)
keep in mind this mask is in the autodrobe which is restricted to clown and mime when unhacked

**Review by MrMelbert — CHANGES_REQUESTED** [review]
Minor nitpicks, also needs sprite approval.

**Review by Twaticus — APPROVED** [review]

**Pull request merged**
