### PR TITLE
Kills snowflakey PDA close button

### PR DESCRIPTION
**Pull request by Core0verload**
PDA window now has a proper "Close" button. Old ultra-snowflake close button is removed.

:cl: Core0verload
rcsadd: PDA window now has a proper "Close" button.
/:cl:

### CODE REVIEW

**Comment by octareenroon91** [comment]
Have you tested this, including trying to use a PDA after closing?

**Comment by Core0verload** [comment]
Of course. And now I know why that snowflakey button was added in a first place. It was added because closing a PDA with regular button was breaking it. But then I fixed `Topic()`, and now the new close works like the old one.

**Comment by YotaXP** [comment]
I LOVE YOU!!!
:kissing_closed_eyes: :heart:

**Comment by duncathan** [comment]
Changelog please

**Comment by octareenroon91** [comment]
This is waiting on a changelog.

**Pull request merged**
