### PR TITLE
[s] Remove a duplicate pipe in MetaStation maint

### PR DESCRIPTION
**Pull request by Cyberboss**
This PR is mainly for fucking with MDBv3

### CODE REVIEW

**Comment by lordpidey** [comment]
What's the [s] for?

**Comment by ShizCalev** [comment]
Read the desc

**Comment by lordpidey** [comment]
Okay, so what is MDBv3?

Why must we hide this?

**Comment by praisenarsie** [comment]
@lordpidey MapDiffBot

mapdiffbot usually posted in the comments but as you see, cyber moved it to the checks tab

**Pull request closed without merging**
