### PR TITLE
Refactors Guardian Color Handling

### PR DESCRIPTION
**Pull request by KazeEspada**
Makes guardians use an overlay system to allow for more colors to be added easier, added a color flag to determine which part of the sprite gets color.

### CODE REVIEW

**Comment by ChangelingRain** [comment]
Holoparasites need four overlays and colors so they don't change in appearance.
I'll provide a list of colors/locations on request.

**Comment by KazeEspada** [comment]
Yeah but i think thats rather extreme.

**Comment by KazeEspada** [comment]
I would at least like to see the sprites and colors.

**Comment by KazeEspada** [comment]
Okay, after testing it out, some colors like Iris look MUCH different between the two. Although, I dont think Holos need four overlays, one overlay should work, but I do agree that the colors need adjusting. Maybe two colors, one for their text and another for their overlay.

**Comment by ChangelingRain** [comment]
Helpful color list; http://puu.sh/oeVQp/5ba4a31b7d.txt
Overlay parts; http://puu.sh/oeUu0/0f46683d1d.dmi
I'd say "I told you so" but that'd be ~~rude~~ I did it anyway

**Pull request closed without merging**
