### PR TITLE
Yet another debug outfit update

### PR DESCRIPTION
**Pull request by kriskog**
## About The Pull Request
Less uranium in the material box due to radiation. Suit helmet has had geiger sound reduced to 0, and a manual geiger counter added to the box. Also added a death wand for easier and cleaner killing.

### CODE REVIEW

**Comment by kriskog** [comment]
Well okay, let's see what happens with uranium radiation first then.

**Comment by Tharcoonvagh** [comment]
Just make the suit 100% radproof

**Comment by kriskog** [comment]
I considered it, but the debug outfit should not make you immune to anything or you'll miss shit like this while testing and debugging. Besides, the geiger would still go off and that's honestly the second most annoying thing about this.

**Comment by kriskog** [comment]
Okay, updated again. Good to go.

**Pull request merged**
