### PR TITLE
Buffs stamina regen

### PR DESCRIPTION
**Pull request by CPTANT**
Because Stamina regeneration is currently complete aids.

After this it will just be serious aids.

### CODE REVIEW

**Comment by CPTANT** [comment]
ah shit something is going wrong here

**Comment by phil235** [comment]
this contains your changes to lasers igniting people.

**Comment by CPTANT** [comment]
yes i noticed

**Comment by CPTANT** [comment]
lets try that again.

**Comment by PKPenguin321** [comment]
you were probably working off a branch of your branch, checkout to master before creating your new branch next time

**Pull request closed without merging**
