### PR TITLE
[Kilostation] Command gets Rockier

### PR DESCRIPTION
**Pull request by Zytolg**
## About The Pull Request

Given that just about the rest of the station features a significant portion of rock, It's fairly inconsistent that the central portion of Kilostation does not. 

## Why It's Good For The Game

Command players are stoners

## Changelog

:cl:
fix: Kilostation's command section now accurately reflects that command staff are, in fact, commanding a hollowed out asteroid. 
/:cl:

### CODE REVIEW

**Review by Maurukas — CHANGES_REQUESTED** [review]
You have a mix of tiles with atmos, airless tiles, space tiles, and plants (which nominally can't exist in a vacuum). The other enclosed asteroid areas on Kilo have atmosphere in them.

image

**Comment by Zytolg** [comment]
Bwah, I'll get to this sometime tomorrow murkle darned conflicts

**Review by Maurukas — CHANGES_REQUESTED** [review]
Active turfs snuck back in.

**Review by Maurukas — APPROVED** [review]
Disregard, my local broke

**Pull request merged**
