### PR TITLE
replaces silicon petting with silicon patting

### PR DESCRIPTION
**Pull request by ATH1909**
## About The Pull Request

Clicking on a silicon without something in your hand will now pat them instead of pet them.

Adds a period to a message given when you attempt to shock hug a silicon.

Per oranges's request, cyborgs now pat non-human mobs instead of pet them.

## Why It's Good For The Game

Petting is kind of... weirdly intimate for something people often do drive-bys with? I believe that patting a borg when you want to show your appreciation for them will be less awkward for both parties involved and better communicate the borg-patter's intent.

And before someone posts that image, no, I don't think that borg petting is fetish content. It's just... weird if you think about what your character is actually doing, y'know?

## Changelog

:cl: ATHATH
spellcheck: Clicking on a silicon without something in your hand will now pat them instead of pet them.
spellcheck: Adds a period to a message given when you attempt to shock hug a silicon.
spellcheck: Cyborgs with hugging modules now pat non-human mobs instead of petting them.
/:cl:

### CODE REVIEW

**Comment by Stalkeros2** [comment]
Why not make it depend on targeted area akin to how it's done with people?

**Comment by ATH1909** [comment]
> Why not make it depend on targeted area akin to how it's done with people?

Patting would probably need to be bound to targeting the head, but characters start targeting the chest by default, meaning that a lot of people would still end up petting instead of patting because they couldn't be bothered to switch targeting zones.

**Comment by optimumtact** [comment]
This makes zero sense, why can you pet other mobs but only pat borgs?

It's a weird snowflake exception and I don't really understand the problem, can you try to explain?

**Comment by Helg2** [comment]
The wonders of english, kek.

**Comment by ATH1909** [comment]
> This makes zero sense, why can you pet other mobs but only pat borgs?
> 
> It's a weird snowflake exception and I don't really understand the problem, can you try to explain why only borgs and not all mobs get the updated text?

Borgs are always either entirely inanimate (SSD, AI shell, etc.) or sapient. Cats and other pets are usually not sapient unless something makes them sapient, like an event or a sentience potion. 

Petting a sapient coworker (that is not trying to imitate a non-sapient creature, such as a cat or dog) is incredibly demeaning to them, and I've seen multiple other borg players, including a /tg/ admin, complain about being pet out of the blue. I can provide screenshots of testimony from them if you request it and they consent to it.

Sapient station pets (e.g. a sapient Ian) usually try to act in a manner similar to their non-sapient counterparts (e.g. chasing balls, barking at mailmen, general dog things), and as such, petting them is usually more acceptable.

Borgs also do not have fur to stroke. Note that not all mobs can be pet- butterflies, for example, are shooed instead. The verb used is determined by response_help_simple and response_help_continuous, which are variables that silicons do not have.

If you do want to intimately pet either an empty shell or a sapient coworker, you can still manually emote that.

**Pull request closed without merging**
