### PR TITLE
New ID card sprites

### PR DESCRIPTION
**Pull request by Agameofscones**
## About The Pull Request
Adds custom ID card sprites on a per role basis. Divided between Heads and normal crew. A few select roles (Clown, Mime, Miner, Chaplain) get slight color shifts to better display their role at a glance.

image
image

## Why It's Good For The Game

My biggest gripe with TG codebases is a distinct lack of department colored ID badges. Helps in quick identification of access on ID cards when removing from PDA, on the ground, etc.

Useful for whenever a player might want to know what access or job an ID has without using the examine verb, they can now do so with their eyes. Their _real_ eyes.

## Changelog
:cl: Triiodine
imageadd: New sprites for all station departments and their respective head staff.
imageadd: New sprites for department budget cards.
spellcheck: Changed the description of a few ID cards.
/:cl:

### CODE REVIEW

**Comment by Agameofscones** [comment]
wait this is the wrongcodebase lmfao

**Comment by actioninja** [comment]
Damn, these are cool. Probably going to steal them.

**Comment by Agameofscones** [comment]
Hey, toss me some credit and I won't mind. I gotta go PR this somewhere else

**Comment by Anonmare** [comment]
oof

**Comment by bobbahbrown** [comment]
look at those commits epic style

**Comment by PKPenguin321** [comment]
weren't the old ID sprites horizontal

**Comment by Detective-Google** [comment]
goddamnit no these actually look good give them back 

also _god dayum those commits_

**Pull request closed without merging**
