### PR TITLE
elite nukie suit improvements

### PR DESCRIPTION
**Pull request by Fikou**
## About The Pull Request

deletes the elite armor booster module, instead the elite syndie suit has some armor by default, with the rest being filled by the standard armor booster
makes welding protection a part of armor booster, removes it from nukie suits since they have armor booster
adds new towering sprites, here you can see the space mode and combat mode
image
old sprite
image

## Why It's Good For The Game

the elite suit needed some more love i think

## Changelog

:cl: Fikou, PositiveEntropy
imageadd: the elite nukie suit has new sprites
balance: the elite nukie suit starts with a little armor filled to standard by the armor booster, the elite armor booster is removed
balance: welding protection is now a part of the armor booster module, no longer a separate module in syndie suits
balance: adds a jetpack and holster to traitor modsuit
/:cl:

### CODE REVIEW

**Comment by ATH1909** [comment]
so now I can just flash nukies if they're in space???

**Comment by Shadowflame909** [comment]
> so now I can just flash nukies if they're in space???

I didn't think about this

We don't want flashbang meta to exist

**Comment by Serxule** [comment]
new sprites give me hella halo vibes and thats swag

**Comment by Imaginos16** [comment]
> new sprites give me hella halo vibes and thats swag

It was certainly an influence!

**Pull request merged**
