### PR TITLE
Gets rid of manual overlay manipulation

### PR DESCRIPTION
**Pull request by tortellinitony**

### CODE REVIEW

**Review by Cyberboss — APPROVED** [review]
Grade A PR

**Comment by AnonymousNow** [comment]
Make it a toggle.

I've found uses for it in the past, but it's also been a pain when doing things like xenobiology etc. and I'm accidentally moving icons sometimes when clicking at a hundred miles an hour to beat The Antagonist of Nearly Every Round.

**Comment by Cyberboss** [comment]
Wrong PR @AnonymousNow

**Comment by Cyberboss** [comment]
Or maybe you don't understand what we mean by overlays, here

**Comment by AnonymousNow** [comment]
I'm thinking of incidental HUD elements.

**Comment by Cyberboss** [comment]
Yeah, that's not this

**Pull request merged**
