### PR TITLE
You can now craft white jumpskirts.

### PR DESCRIPTION
**Pull request by nemvar**
## About The Pull Request

You can now craft white jumpskirts with cloth.

## Changelog
:cl:
add: You can now craft white jumpskirts with cloth.
/:cl:

### CODE REVIEW

**Comment by spessbro** [comment]
original title was better

**Comment by nemvar** [comment]
I agree

**Comment by habader** [comment]
skirtpr

**Comment by ishitbyabullet** [comment]
how is that image even related beyond the name skirts?

If you can craft a white jumpsuit, scarf, etc then you should be able to craft a jumpskirt. It's not some sort of item that you would have to get a vanilla wow 300/300 tailor to craft or some dumb shit. Merge it.

**Pull request merged**
