### PR TITLE
Pickable bar stools

### PR DESCRIPTION
**Pull request by lzimann**
What's even the point of having them if you can't fight people with it
in-hand sprite by WJohnston:
inhand

### CODE REVIEW

**Comment by MMMiracles** [comment]
fuck you beat me to it

**Comment by TechnoAlchemisto** [comment]
literally beat me to it

**Comment by lzimann** [comment]
if that's what the people want i can change so you have to wrench it, but i  don't care regardless

**Comment by Zilenan91** [comment]
Nah just let people pick them up. It's not a bar fight if you have to prepare it beforehand

**Comment by MMMiracles** [comment]
dont HALF-ASS IT like SOME PEOPLE

**Comment by pudl** [comment]
cancer pr, massively bluepilled, if this is merged im going to murder cheridan :-1:

**Comment by Zilenan91** [comment]
@pudl do it


fgt

**Comment by Iamgoofball** [comment]
please evacuate the pacific ocean is rolling in

**Comment by pudl** [comment]
AHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH

**Comment by Iamgoofball** [comment]
@optimumtact wheres the fix

**Comment by lzimann** [comment]
if you mean fix token, #18227

**Pull request merged**
