### PR TITLE
Halves most tablecrafting times

### PR DESCRIPTION
**Pull request by PKPenguin321**
Hopefully this will make tablecrafting less of a massive pain in the ass. There's no point in recipes taking that long to finish when I can slap the objects together in my hands in a few seconds.

:cl: PKPenguin321
experiment: The time needed to complete most tablecrafting recipes has been cut in half to make tablecrafting less annoying to use.
/:cl:

### CODE REVIEW

**Comment by TrustyGun** [comment]
:+1:

**Comment by Shapsy** [comment]
Less time with my shit on the table for assistants to snag :+1:

**Comment by The-Albinobigfoot** [comment]
:+1:

**Comment by Jalleo** [comment]
This isnt really most this is really gimmick ones and robot.

**Comment by PKPenguin321** [comment]
I left foods and shit alone

**Comment by tkdrg** [comment]
sure we can give this a try, if it's cancer we have the revert button

**Pull request merged**
