### PR TITLE
Fixes lockers alt-click

### LINKED ISSUE #30533: Alt-Clicking on lockers no longer locks them, returns "You can't do that right now!"
Strangely enough, tapping on a locker with the appropriate ID can still lock it.

### PR DESCRIPTION
**Pull request by AnturK**
Fixes #30533

### CODE REVIEW

**Comment by ExcessiveUseOfCobblestone** [comment]
THIS KILLS TACTICAL UNLOCKING FROM INSIDE

**Comment by XDTM** [comment]
Wait who decided that they couldn't be unlocked from the inside in the first place

**Comment by kevinz000** [comment]
PLEASE NO!!!

**Comment by Bawhoppen** [comment]
powergamers get out

**Comment by QualityVan** [comment]
the lock's on the outside of the locker, how are you reaching it from the inside?

**Comment by kingofkosmos** [comment]
@XDTM it was an oversight in my locker-resist-PR, was going do another PR for it since I thought it was weird that you could lock/unlock from the inside, but completely forgot about it and left the half-assed line in.

**Comment by KorPhaeron** [comment]
Can argue over locker balance in another PR, the intent of the existing code is clear

**Pull request merged**
