### PR TITLE
Flickering no longer enables emergency lights

### PR DESCRIPTION
**Pull request by ghost**
:cl: Xhuis
tweak: Flickering lights will now actually flicker and not go between emergency lights and normal lighting.
/:cl:

Someone mentioned that flickering was causing lights to swap between emergency lights and normal lights; now it'll swap between normal lights and off like normal.

### CODE REVIEW

**Comment by ACCount12** [comment]
Does this fix the bug with lights flickering while being constructed/deconstructed?

**Comment by Xhuis** [comment]
I'm not sure what's causing that bug, so I can't say.

**Comment by ACCount12** [comment]
Have you tested *this* PR at the very least?

**Comment by Xhuis** [comment]
It was made with the webeditor, so not yet, but I'm reproducing them locally to make sure it works as intended.

**Comment by Xhuis** [comment]
Yup, it works.

**Comment by ShizCalev** [comment]
image

summoning the spirit of @kevinz000

**Comment by Xhuis** [comment]
༼ つ ◕_◕ ༽つ KEVINZ COME FORTH ༼ つ ◕_◕ ༽つ
༼ つ ◕_◕ ༽つ KEVINZ COME FORTH ༼ つ ◕_◕ ༽つ
༼ つ ◕_◕ ༽つ KEVINZ COME FORTH ༼ つ ◕_◕ ༽つ

**Comment by Shadowlight213** [comment]
@Xhuis typo in changelog. You probably meant "lights will now actually flicker" instead of "lights will not actually flicker"

**Comment by Xhuis** [comment]
You saw nothing.

**Review by Cyberboss — APPROVED** [review]

**Pull request merged**
