### PR TITLE
Adds a purple bartender suit and apron, and Long Hair 3 - Requested and sprites by Okand37!

### PR DESCRIPTION
**Pull request by silicons**
blah blah VARIETY IS THE SPICE OF LIFE!

image
image
image

:cl:
rscadd: purple bartender suit and apron added to clothesmates!
rscadd: long hair 3 added, check it out. both have sprites from okand!
/:cl:

### CODE REVIEW

**Comment by Arianya** [comment]
Purple as a colour belongs to R&D

Moonlighting is *not* okay

**Comment by Spaceinaba** [comment]
HM I WONDER WHAT THIS IS A REFERENCE TO

**Comment by DoctoreMad** [comment]
That hair reminds me of Shinobu which probably means some xXAnime_ProXx is going to correct me with the proper reference in a few seconds.

**Comment by zamolxius** [comment]
Snowflake

**Comment by Xhuis** [comment]
🚰, just saying.

**Comment by Okand37** [comment]
@Xhuis Water you meaning by this?

**Comment by Spaceinaba** [comment]
there is nothing wrong with getting hydrated

**Comment by praisenarsie** [comment]
muh feature freeze

**Pull request merged**
