### PR TITLE
Simple Animal structure attacking

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
Would it be better to add another istype (for barricades) or just let it attempt to hit every structure?

### CODE REVIEW

**Comment by KorPhaeron** [comment]
@phil235 probably knows what is best

**Comment by lzimann** [comment]
it will end up attacking cables, map signs and a few other things that are not destructable afaik

**Comment by KorPhaeron** [comment]
@lzimann 

Which should just return nothing, right?

**Comment by lzimann** [comment]
yea they will just do an attack animation on them i believe

**Pull request closed without merging**
