### PR TITLE
Small pizza bomb balancing

### PR DESCRIPTION
**Pull request by ghost**
- The pizza bomb's minimum fuse is now three seconds (up from one second).
- The pizza bomb's explosion has been reduced and should no longer cause hull breaches.

### CODE REVIEW

**Comment by Stickymayhem** [comment]
Was this balancing really needed? It's an unwieldy item to use for a bigger bang and possibly trickstery but now it's just a less powerful syndieminibomb.

At most make one of those changes, not both.

**Comment by KorPhaeron** [comment]
Hull breaches aren't even a big deal you can run straight past them and they take all of 10 seconds for an engiborg to fix

**Comment by Lumipharon** [comment]
It becomes a big deal when there's like a dozen across the station but yeah, they rarely get spammed anymore, if the explosion gets reduced this much they're pretty useless.

**Comment by Fox-McCloud** [comment]
There's literally no point to this with a three second delay.

People will never get gibbed by it let alone put into crit.

**Comment by RocKeD** [comment]
In all the time (admittedly isn't a whole lot) I have only seen pizza bombs once or twice and it wasn't even that bad, I agree that the hull breach change isn't needed. Anyone walking by knows how to and can easily fix the hull breach plus this gives atmos more utility.

**Comment by Xhuis** [comment]
I can see people aren't interested in this.

**Pull request closed without merging**
