### PR TITLE
Add syndicate headset messages, squashes both together.

### PR DESCRIPTION
**Pull request by DaxDupont**
[Changelogs]: 

:cl: Dax Dupont
refactor: Syndicate and Centcom messages have been squashed together.
admin: You can now send both Syndicate and Centcom headset messages. Be mindful that the button was changed to HM in the playerpanel
/:cl:

[why]: Adds syndicate messages as well as suggested.
@Cyberboss I hope using client proc is okay, sadly I couldn't use /datum/admin since you can't refer to the other proc and for some reason buttons don't work with a second argument.

### CODE REVIEW

**Comment by MrDoomBringer** [comment]
Why not just have a field to type where the message is coming from? Would be useful for wizards, admeme events, etc

**Comment by DaxDupont** [comment]
@MrDoomBringer because there's some differences in the message text. For wizards/admins SM stuff will do.

**Comment by ExcessiveUseOfCobblestone** [comment]
> I couldn't use /datum/admin since you can't refer to the other proc and for some reason buttons don't work with a second argument.

?

**Comment by fludd12** [comment]
> Why not just have a field [...]?
At that point, wouldn't it just be direct narrate but with like two words auto added?

**Comment by vuonojenmustaturska** [comment]
@ExcessiveUseOfCobblestone the src in datum verbs is the client and not the datum so you can't refer to other procs in the datum and you don't get a handle to the datum either

**Comment by ExcessiveUseOfCobblestone** [comment]
that's lame

**Review by Cyberboss — APPROVED** [review]

**Pull request merged**
