### PR TITLE
Added projectile vomiting symptom.

### PR DESCRIPTION
**Pull request by lordpidey**
:cl:
rscadd: New virology symptom, projectile vomiting.  It is a level four symptom.
/:cl:

### CODE REVIEW

**Comment by Zilenan91** [comment]
So does this shoot vomit everywhere? Sounds sweet.

**Comment by WJohn** [comment]
This is super gross :+1:

**Comment by newfren** [comment]
Please don't add symptoms to virology please they just clog up the randomisation that you need to go through to get good diseases.

Especially a symptom like this which will realistically never be used given its terrible stats.

**Comment by Xhuis** [comment]
As a formerly avid virologist, this adds nothing useful. :-1:

**Comment by Zilenan91** [comment]
It's actually insanely good because you can quite literally chainstun people to death with this, vomiting, blood vomiting, sneezing, and eternal youth.

**Comment by Xhuis** [comment]
My current issue with this symptom is that it's basically bloat. There are better symptoms that are harder to get due to virology's entire basis on randomness. It might be wanted eventually, but for right now I don't see it serving a purpose.

**Comment by lordpidey** [comment]
Tell you what @Xhuis ,  I'll close this PR, and wait for #15412 to finish, and see how things change before reopening it.

**Comment by lordpidey** [comment]
re-opening, now that #15412 has merged.  Hopefully the new chems help alleviate the concerns over this PR.

**Pull request merged**
