### PR TITLE
Remove detain mode as a toggleable switch for end user

### PR DESCRIPTION
**Pull request by optimumtact**
Functionality is left in to support killbots, (so they don't try to handcuff you)

Note that killbots will not announce when engaging

This is still a problem with people getting permastunned, so I've reopened the PR removing it

### CODE REVIEW

**Comment by optimumtact** [comment]
DNM testing

**Comment by optimumtact** [comment]
Reasoning behind this is that being perma stunned by ed is not fun for criminals

Also the spamming of radio chat is annoying as security

**Comment by palpatine213** [comment]
You could just add a delay to it, so the criminal can move a few tiles or try to hit them before being stunned again.
Detain is really useful in situations where cuffing someone isn't going to help as they can just run away.
Also beepsky on detain plus a hacked medibot is a good strategy for rogue Ais to assasinate someone.

**Comment by Cheridan** [comment]
Yeah, Detain can lead to situations where the perp is just stunlocked for the rest of the round. It'd be ok if it had diminishing returns or if the bot would eventually wander off or something, but as it is it isn't really cool.

**Comment by optimumtact** [comment]
Please follow the guidelines in the OP

**Comment by Fox-McCloud** [comment]
If you're going to do this for ED209's, do it for Beepsky too.

**Comment by Dorsisdwarf** [comment]
ED-209s lose it because they have a taser instead of a stunbaton, and more health.
You can outrun the long baton of the law, but not the golden bolt.

**Comment by Fox-McCloud** [comment]
I think the point here is that the detain feature is pretty shitty because if you get caught (beepsky or ED209), you're pretty much permastunned, forever. Yes it's easier to deal with, with beepsters, but the feature it's is pretty shit.

**Comment by optimumtact** [comment]
People are indicating you can run away from beepsky's detain stun, I'll have to test that out and see.

**Comment by Lumipharon** [comment]
I haven't seen detain for a LONG ass time, but from what I remember, BEFORE the stun nerfs, detain mode would perma stun. But the stun durations got nerfed, but the delay between stuns for detain mode was not, so you could get up between stuns.

I could be wrong though.

**Comment by Fox-McCloud** [comment]
It stuns you for 5 cycles (roughly ~10 seconds) and bots process every cycle (~2 seconds), so yeah, no way to escape once you're detained, AFAIK.

**Comment by Rinoka** [comment]
Why not just make it so that the bots have to recharge their taser/stunbaton and will do it automatically?

Means permastunning ain't no thing.

**Comment by Fox-McCloud** [comment]
Because it's easier to remove a shit feature to begin with?

**Comment by Rinoka** [comment]
Point.

**Comment by optimumtact** [comment]
if someone wants to take over this

**Comment by optimumtact** [comment]
Ready to merge

**Comment by optimumtact** [comment]
ready for merge

**Comment by Dorsisdwarf** [comment]
Not ready for merge unless travis is lie

**Comment by GunHog** [comment]
What? No, zombing a long dead PR to try and slip it past people as well as bypass the 24HR limit should be unacceptable. At that point, it needs to be treated as a new PR.

**Comment by optimumtact** [comment]
your paranoia is outstanding

**Comment by tkdrg** [comment]
Stop trying to use necromancy to bypass the freeze

**Comment by Cheridan** [comment]
He's not trying bypassing the freeze. Someone was talking about this topic and he reopened the old pr.   Obviously don't merge it right away, treat it as a new pr

**Comment by optimumtact** [comment]
treat this as a new PR so gunhog doesn't freak out

**Comment by GunHog** [comment]
Still against it :-1:

**Comment by Shadowlight213** [comment]
Still against it as well. :-1:

**Comment by KorPhaeron** [comment]
Back in my day beepsky didnt shout out the criminal location while holding them in place

**Pull request closed without merging**
