### PR TITLE
[s] Fixed being able to speak while unconscious using alien or changeling channels

### PR DESCRIPTION
**Pull request by Cruix**
If you don't have the ability to speak on them.

### CODE REVIEW

**Comment by ChangelingRain** [comment]
Could you explain how this works, exactly?

**Comment by KorPhaeron** [comment]
You're supposed to be able to speak when unconscious on the changeling channel though

**Comment by Cruix** [comment]
If you use the alien or changeling channels, the message bypasses the crit check, because those channels are usable while in crit.

However, if you aren't able to use those channels and handle_inherent_channels() returns 0, you will speak the message out loud. Because you are already past the unconsciousness check, you'll speak them out loud even in crit.

Making alien and hive channels always return 1 fixes this, at the cost of non-changelings not being able to say anything prefixed with ".g" or ".a".

**Comment by ExcessiveUseOfCobblestone** [comment]
so what you're saying is you can bypass not being able to speak in crit if you try to speak while in these channels?

**Comment by Cruix** [comment]
Yes. If you are not a changeling you can use .g to speak while in crit. If you do not have a hivenode, you can use .a to speak while in crit.

**Comment by ExcessiveUseOfCobblestone** [comment]
would it be easier to add a check to see if the human is in crit in `can_speak_vocal` instead?

**Comment by Cruix** [comment]
You would have to also pass in the message mode and check if it is MODE_WHISPER after you have already done so. This would also make MODE_WHISPER a special snowflake, which is something to be avoided.

**Comment by JJRcop** [comment]
aglblatf :/

**Pull request merged**
