### PR TITLE
Fixes broken carbonation unit on Soda Dispensors: Fizzy lives!

### PR DESCRIPTION
**Pull request by carshalash**
## About The Pull Request

I noticed how horrible and ugly cola sprites were, I then realized that none of our sodas actually FIZZ. So I decided to fix that and updated the cola colour so that it isn't the same color as multiple other drinks as well.

## Why It's Good For The Game

Who the fuck likes flat soda. Get that shit outta here.

Cola
cola

Soda/tonic water
SODA

Pwr game (Now in gamer dank purple!)
pwrgame

Shambler juice, that I honestly still have no clue what the fuck it is meant to be.
shambler

And a few more! Enjoy the fizzy drinks, my friends.

## Changelog
:cl:
add: Carbonation
/:cl:

### CODE REVIEW

**Comment by KathyRyals** [comment]
I like flat sodad and I cannot lie.

**Comment by ilikesaying** [comment]
~~carbonate them even more by pumping even more carbon dioxide into them~~

**Comment by IndieanaJones** [comment]
I'M GOING TO KILL YOU
YOU STOLE FIZZY LIFTING DRINKS
*I shove you to the ground and you're held there by two burly oompa loompas*

**Comment by TheBonded** [comment]
Can you fizzify gibbfloats too?

**Comment by carshalash** [comment]
> Can you fizzify gibbfloats too?

This is gonna sound really weird but, I actually really like the gibb+gibbfloat sprites so I left them.

**Review by Twaticus — APPROVED** [review]

**Comment by StarHorder** [comment]
gods work.

**Pull request merged**
