### PR TITLE
Adds Bee and Mad Scientist Traitor Bundles

### PR DESCRIPTION
**Pull request by wesoda25**
## About The Pull Request

Adds two new syndicate bundles, mad scientist and bee!! 

## Why It's Good For The Game

Syndicate bundles are fun because its rolling the dice with awesome, gimmicky traitor kits. More variety is always nice, it keeps things fresh. 

## Changelog
:cl:
add: syndicate mad scientist bundle
add: syndicate bee bundle
fix: fixed an undocumented code issue with the sabotage bundle, pizza bomb now appears
:cl:

### CODE REVIEW

**Comment by wesoda25** [comment]
if you have any other ideas just toss them out because this shit is not hard to code

**Comment by Sisyphusrollson** [comment]
Ok, this is epic.

**Comment by Shadowflame909** [comment]
Thrift Store Wizard

**Comment by wesoda25** [comment]
eueruhggh I dislike the idea of magical items in upload. Wizard is immersion breaking enough, but traitors with spells? Its a neat idea but I don't think it has any place in the traitor uplink.

**Comment by Shadowflame909** [comment]
yeah but gamer


these bundles aren't g00d for completing OP objectives and are just memes


If you add this in with that, you've essentially perfected the casino scam artist technique, and will get more people using syndicate bundles, and who will roll your new meme bundle gimmicks

**Comment by Kierany9** [comment]
For a moment I thought that the Bees bundle would actually give you queen bees for all your evil beekeeping needs

Oh well, a man can dream

**Comment by GuyonBroadway** [comment]
Do I need to dig up the relevant video or can it just be assumed at this point?

**Comment by ATH1909** [comment]
A Mr. Freeze bundle, which would include:
A belt of gluon grenades
Special noslips that would let you walk on permafrost (but NOT provide any protection against other slippery surfaces
A winter coat and other cold-protection gear
Mutation injectors for cryokinesis and geladokinesis
A freeze gun (basically just an energy crossbow, but it applies the freon status effect instead of stunning and muting your victim and has a greater range)
A special subtype of sechailer that would spew ice puns when used. Like normal sechailers, its settings could be adjusted:
  Lowest setting: Normal/okay ice puns ("FREEZE!", "ICE to meet you!", etc.)
  Middle setting: Terrible ice puns ("I think I have a COLD!", "I SEE you! Get it? 'I SEE' sounds like 'icy'? No? Aw.")
  Highest setting: Ice-related references ("Let it go!", "Batman & Robin is a cinematic masterpiece!", etc.)
  Emagged setting: An ice-related copypasta (I can't think of any off of the top of my head)

**Comment by Shardj** [comment]
Add a thug bundle and it's just all of the standard shitcurity clothing and a bloody stun baton

**Comment by Tlaltecuhtli** [comment]
the mad scientist bundle seems pretty underwhelming and rng based, and why the signalers? you cant attach em to clusternades can you?

**Comment by wesoda25** [comment]
You can I’m fairly certain. And the clusterbusters can be incredibly OP, or just something half decent, hence why I put two in. The kit is rolling the dice.

**Comment by Shadowflame909** [comment]
I don use clusters at all. What's the strongest thing you can get?

**Comment by wesoda25** [comment]
Carp which spawns like 80 space carp.

**Comment by wesoda25** [comment]
I like the mr freeze and infiltrator ideas, and if you guys think the kits are underpowered I’d be willing to move them to a different bundle type (maybe 18 tc for all the gimmick bundles). 

Unfortunately I’m gonna be away from my computer for the next 4 days so I guess I’ll toss a wip tag on.

**Comment by Shadowflame909** [comment]
Second Bundle Idea

Gang Leader

Hypnoflash
Syndismokes
Switchblade
Gatfruit (more guns for your fellow gangstars)
50 Leather. (For Leather Overcoats and jackets. Those are expensive as hell)

That'd be a pretty good bundle, might make it one of the rarer ones though.

**Comment by OverlyGeneric** [comment]
@wesoda25 

**Busy Bee Bundle**

- A reusable briefcase that spews out an assortment of toxin bees on a three-minute cooldown and is slightly robust.
- A lightly-armored business suit.
- A bee mask that acts like a syndicate mask.
- A e-dagger.

**Pull request merged**
