### PR TITLE
edits clockwork helmet sprite, makes clockwork boots unable to be tied

### PR DESCRIPTION
**Pull request by Fikou**
## About The Pull Request

removes clockwork_garb.dmi, moves the stuff to the other clothing files
resizes the clockwork helmet to be 2x smaller because it looks really bad
makes it impossible to tie bronze boots (they are literally crafted from sheets of metal)

## Why It's Good For The Game

less icon files

## Changelog
:cl:
tweak: you cant tie bronze boots anymore
spriteadd: makes the clockwork helmet not as big on the ground
/:cl:

### CODE REVIEW

**Comment by interestingusernam3** [comment]
You should probably mention the helmet change in the changelog.

**Comment by Fikou** [comment]
no, i dont think i will

**Comment by Jared-Fogle** [comment]
You should probably mention the helmet change in the changelog.

**Comment by optimumtact** [comment]
> You should probably mention the helmet change in the changelog.

**Comment by Fikou** [comment]
why

**Comment by tralezab** [comment]
Why are you even doing this you fucking idiot, files are FREE STOP CONTRIBUTING TO THE CLOTHING FILE PROBLEM FJDIXIBJEBSJSOAO

**Comment by optimumtact** [comment]
> > You should probably mention the helmet change in the changelog.

**Comment by optimumtact** [comment]
actually yeah I don't even agree with the change undo it

**Comment by Twaticus** [comment]
obj icons are supposed to be big now it just looks like you took the mob icon and pasted it in obj/clothing/hats
image

**Comment by Fikou** [comment]
> Why are you even doing this you fucking idiot, files are FREE STOP CONTRIBUTING TO THE CLOTHING FILE PROBLEM FJDIXIBJEBSJSOAO

another pr already moved the helmet and armor, and if someone really wants to split it should be a proper job and not a "random glove, boot, suit and helmet" in 1 file

**Comment by tralezab** [comment]
That someone should be YOU though

**Comment by tralezab** [comment]
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
image

**Review by Mothblocks — CHANGES_REQUESTED** [review]
As said in Discord by me and Cyberboss, we'd rather clothing be in sets rather than in mega files.

Please limit this to just making boots untieable.

**Comment by Twaticus** [comment]
what jared said. also i still dont like the tiny helmet so yes
> Please limit this to just making boots untieable.

**Comment by Twaticus** [comment]
alright scratch my comment the helmet change is fine. just need the changes jared suggested and its good

**Review by Twaticus — APPROVED** [review]

**Pull request merged**
