### PR TITLE
Revert "Borg movement now has sounds"

### PR DESCRIPTION
**Pull request by ZephyrTFA**
Reverts tgstation/tgstation#82704

The sound ingame appears much louder than the original author intended.
Not to mention that the sound loops stack for every borg moving near you.

### CODE REVIEW

**Comment by sylvia-from-fulp-station** [comment]
this noise is like a drill in the back of my skull. thank you

**Comment by NexusLeader** [comment]
Please. Yes. Please. Fuck yes.

**Comment by Dawnseer** [comment]
Yes please, it is way too loud as it is right now.

**Comment by Sadboysuss** [comment]
oops, I was gonna fix it today but yeah revert it, maybe it will come back some other time, but with more testing beforehand.

**Comment by DrDiasyl** [comment]
To be honest, just switch to other sounds and make it only play like every 4 tiles.

The sound I would suggest is "servostep.ogg" in the sounds/effects folder!

**Pull request merged**
