### PR TITLE
Prevents admins without +ADMIN from kicking clients

### PR DESCRIPTION
**Pull request by Cyberboss**

### CODE REVIEW

**Comment by kevinz000** [comment]
wtf sdql mass kick was a thing!!!!

**Comment by kevinz000** [comment]
also are you sure it's not intentional it's locked to +ADMIN?

**Comment by PKPenguin321** [comment]
put a confirm prompt on kicking too ive kicked on accident once

**Comment by Cyberboss** [comment]
things be dumb

**Pull request closed without merging**
