### PR TITLE
Bot fixes and PDA upgrades!

### PR DESCRIPTION
**Pull request by GunHog**
A funny thing to note, the Newscaster stuff I did because I happened to be looking through the PDA code. I just thought it would be nice to expand it a little.
- Bot radio code now no longer uses filters to allow for multi-access
  radio control.
- Bots can now patrol while off station.

<b>EDIT:</b> I merged an old fix PR for bots with this one. It should make bots less prone to getting stuck. 
- The Captain's PDA can now access multiple bots!
  (Security bots, floorbots, cleanbots, medibots)
  screenshot 2015-04-08 18 45 35
- The Captain and HoP PDAs can now also remotely access Newscasters!
- The Newscaster PDA app now supports comments and images!
  screenshot 2015-04-08 20 04 57
  
  -- VS --

screenshot 2015-04-08 20 04 35

### CODE REVIEW

**Comment by RandomMarine** [comment]
How about MULEbots for the captain too? And newscaster for librarian?

**Comment by CorruptComputer** [comment]
Does the roboticist and RD have the bot control as well? Also the ability for rouge/malf AI to "hack" PDA's and reset them back to default would be interesting.

**Comment by GunHog** [comment]
>How about MULEbots for the captain too? And newscaster for librarian?

MULEbots are too snowflake at the moment, and would take more work than is worth it to get them functioning properly.
The Libarian already has newscaster access! He previously was the only one who did!

>Does the roboticist and RD have the bot control as well? Also the ability for rouge/malf AI to "hack" PDA's and reset them back to default would be interesting.

The RD does not, as his PDA is a signaller (combining them gets hairy). I would need to create a new cart for Robos, as I do not want to give them access to Securitrons. And for that, I may be required to touch the map - I would really rather not do that. I will consider adding a cart for Roboticists if I can avoid editing the map to give the RD spare carts.

As for a Malf AI hacking PDAs..what do you mean?

**Comment by CorruptComputer** [comment]
>As for a Malf AI hacking PDAs..what do you mean?

Like frying the cartage inside the PDA, making it just default with no extra things. EX: If the AI "hacks" the captains PDA he loses the ability to access bots and the newscasters, making it just a normal PDA.

>as I do not want to give them access to Securitrons.

Then give Securitrons to HoS, Floorbots to CE, and Medibots to CMO. Personally I think PDA's are underused in this game.

**Comment by GunHog** [comment]
> Then give Securitrons to HoS, Floorbots to CE, and Medibots to CMO. Personally I think PDA's are underused in this game.

This is currently the case, right now. This update does not change that.

**Comment by CorruptComputer** [comment]
>This is currently the case, right now. This update does not change that.

Oh, I've never noticed this then. Does the RD have cyborg access on his PDA?

**Comment by GunHog** [comment]
No, that would be a big balance change if the RD could just lock/blow borgs whenever he felt like it. How would rogue borgs defend against that?

**Comment by CorruptComputer** [comment]
Well he can already do that from his office, but I was thinking it would be balanced if the AI could do something to destroy PDA's. I mean currently the only thing that keeps him from doing it is most likely just an electrified door to the office.

**Comment by GunHog** [comment]
Yes, from his office, but a robust rogue AI + borgs will find a way to stop the RD and anyone else who might be a threat. Engineering borgs can deconstruct the computer, the AI could flood it with plasma, etc. With a borgs control PDA app, he could stop a borg at the press of a button, and the only way to stop that would be to kill the RD first, by surprise. Even then, the borg console is not ID locked, so they would still have to deal with the console as well.

I am not against a read-only version of the cyborg console, though.

**Comment by CorruptComputer** [comment]
A read only console would be fine with me, I was just trying to find a way to give them more uses. As I said a couple posts ago I think PDA's are underused.

**Comment by GunHog** [comment]
@Jordie0608 please remove the "Do Not Merge" tag from this. A lot of problems I discovered in testing this were fixed in an old PR I never re-opened. Also, I have already paid my tithe in changelog. No edits to the changelog, as players should not see any changes except them not getting stuck in places.

**Pull request merged**
