### PR TITLE
Removes vault walls

### PR DESCRIPTION
**Pull request by dragomagol**
## About The Pull Request
Removes vault walls

## Why It's Good For The Game
They're not used anywhere

## Changelog
:cl: Tattle
image: removes unused vault walls
/:cl:

### CODE REVIEW

**Review by LemonInTheDark — APPROVED** [review]
Free me from this hell

**Comment by Pumpkinoe** [comment]
i wonder where these were used originally

**Comment by Fikou** [comment]
> i wonder where these were used originally

iirc the randomly generated vaults on the mining asteroid

**Comment by Imaginos16** [comment]
https://www.youtube.com/watch?v=dyIilW_eBjc

**Pull request merged**
