### PR TITLE
Adds aux base construction area

### PR DESCRIPTION
**Pull request by WJohn**
This is a continuation of kor and gun_hog's work, made into a NOT tumor (or at least less so).

Metastation:

Box:

:cl: WJohnston
add: Metastation and Boxstation now boast auxillary mining construction rooms in arrivals. These allow you to build a base and then launch it to wherever you want on lavaland.
/:cl:

### CODE REVIEW

**Comment by KorPhaeron** [comment]
Where does the shuttle dock with the station?

**Comment by Niknakflak** [comment]
still tumors, not good enough to not be ugly

**Comment by GunHog** [comment]
There is no mining shuttle dock. It would only go to another location on the station. You cannot send the shuttle to the base after it lands, I have not figured out how. (Adding the Landing zone to the mining shuttle's list just caused errors)

**Comment by TechnoAlchemisto** [comment]
Does this get rid of one of the arrivals pods?

**Comment by KorPhaeron** [comment]
Kind of pointless if you cant send the shuttle to it

**Comment by KorPhaeron** [comment]
This is also on the opposite side of the station from both science and engineering

**Comment by xxalpha** [comment]
Why would you send the shuttle there, there isn't enough space.

**Comment by GunHog** [comment]
Trying to work out a way to get the mining shuttle to dock next to it when it lands.

**Comment by xxalpha** [comment]
Also stop calling it ugly, it's meant to be a large empty space.

**Comment by GunHog** [comment]
I will make PRs to this PR for spawning a docking point for the mining shuttle after the base lands. It should also contain a teleport beacon, so that is a way to reach it as well.

**Comment by KorPhaeron** [comment]
Above the chapel was a more interesting spot debate me

**Comment by francinum** [comment]
It's so tiny.

**Comment by Bawhoppen** [comment]
:-1: don't remove a useful construction area for a shitty gimmick nobody will ever use, add it on top of it or something

**Comment by francinum** [comment]
Replace the toxins site or something with this, or make it a square in space surrounded by catwalks, and the launch console a computer engineering has to build on it,

**Comment by lzimann** [comment]
normies get out of my lavaland REEEEEEEEEEE

**Comment by PKPenguin321** [comment]
1. literally no reason for it to be that big, it should be the size of the R&D area at max, maybe detective's-office-before-it-was-moved-to-cargo at minimum
2. \>removing one of box's pods
3. the box one is absolutely a travesty and the only reason the meta one works is because it already had a giant open empty tumor for some reason

**Comment by GunHog** [comment]
> Above the chapel was a more interesting spot debate me

That area ran directly through the chapel; It needs to be accessible from the hallway. Arrivals is not an optimal location for it, but there are not that many good spots on the station that can be reached from a hallway.

>literally no reason for it to be that big, it should be the size of the R&D area at max, maybe detective's-office-before-it-was-moved-to-cargo at minimum

I feel the current size is optimal, as it should be large enough to support the major departments. Do you remember the asteroid days where the whole crew would move to the mining area and build from there? The base needs to be at least that large to let crew send down enough machines and equipment for the rest of the crew to teleport/shuttle down to base at landing.

>removing one of box's pods

I agree that the second pod should be added back somehow.

**Comment by Bawhoppen** [comment]
WJ please just replace that space plating area above it on meta it would work so easily

**Comment by WJohn** [comment]
I never got rid of the second pod, it's underneath the shuttle in the same kind of spot the top one is.

**Comment by Bawhoppen** [comment]
@WJohn that will cause problems with some of the shuttle manipulator's ferry ships

**Comment by WJohn** [comment]
Uh, no it shouldn't be a problem at all?? The ferry ship is in the same spot it is as always.

**Comment by Bawhoppen** [comment]
I mean ferries like this for example that extend out 
ss 2016-08-07 at 09 04 34

**Comment by WJohn** [comment]
maybe we shouldn't have retarded funnel-shaped ships and stick to things that are within a rectangle?

**Comment by xxalpha** [comment]
Nah thats boring.

**Comment by optimumtact** [comment]
Why not place this in space next to the AI satellite  or below the engine and run some tubes out to it from engineering.

Would work for box at least.

**Comment by francinum** [comment]
That'd probably be best.

**Comment by PKPenguin321** [comment]
i still dont like the current spot for box. maybe stuff it in SE maint someplace? it's not a hallway but at least it's not another department

**Comment by GunHog** [comment]
>i still dont like the current spot for box. maybe stuff it in SE maint someplace? it's not a hallway but at least it's not another department

It needs to be hallway accessible, PKP/oranges. The Engi/Sci/Miner access is so people who build things have their chance to set up the base, and the miner to grab the remote and set the drop point. I requested a shutter so that it can be opened to the public to join in for the drop. The red airlock is all-access for this purpose.

Putting it in maint or inside a department will result in access issues, and the accessibility needs to be high enough to generate public curiosity, similar to a storefront. It cannot be put in a back alley of maint, or tubed off (tubes push the difficulty of transporting things to the base above the player laziness threshold). 

@WJohn To meet @KorPhaeron's request of a mining shuttle dock, I am going to send you code to support a shuttle docking beacon.

**Comment by Hatfish** [comment]
Would it be possible to make the colony drop console constructible so engineers can still build in this room without worrying about the clown jettisoning all their hard work to lavaland?

**Comment by optimumtact** [comment]
Then we need to push the escape shuttle out and put a new area below it then or something.

Where it is just is too much of a compromise imo.

**Comment by GunHog** [comment]
> Would it be possible to make the colony drop console constructible so engineers can still build in this room without worrying about the clown jettisoning all their hard work to lavaland?

The console itself is Head access only, although since when has a silly thing like access stopped a clown? Someone also has to take the beacon down and set it before it can be launched, so if an early drop DOES happen, it would probably be the work of an antag or a really hard working clown. This is funny enough to be left in.

Are you asking that the console be **de**constructible? Building another console would not allow you to drop another base, due to how docking ports work.  It is a possibility for the future if this feature is popular enough, though.

>Then we need to push the escape shuttle out and put a new area below it then or something.

>Where it is just is too much of a compromise imo.

If you and WJ can work out a better location, I am all in support! It just needs to be in a hallway so people can see and access it easily. Escape is a good place, since Science is nearby, and Engineering is not too far away.

**Comment by Bawhoppen** [comment]
again I hate how this removes the fun construction area that I've seen people do tons of creative things with for some shitty gimmick that will rarely be used

**Comment by Hatfish** [comment]
> Are you asking that the console be deconstructible?
Essentially, yes.  What I was thinking is that the console could start unconstructed, so if the engineers wanted to use that space for colony building they could simply build the console anywhere, and if they wanted to do something else with the space they wouldn't have to build around it.

**Comment by GunHog** [comment]
> again I hate how this removes the fun construction area that I've seen people do tons of creative things with for some shitty gimmick that will rarely be used

Help us decide on an optimal location, accessible from a hallway. Oranges suggests extending Escape to accommodate attaching it to the south there. And I do not see the activity you claim, barring antags. This is also going to be a construction area, complete with tools and resources to get people started. The difference being that it has the added bonus of being droppable. Are you honestly suggesting that such creative things would be lost in an area that has even includes starting resources?

> Essentially, yes. What I was thinking is that the console could start unconstructed, so if the engineers wanted to use that space for colony building they could simply build the console anywhere, and if they wanted to do something else with the space they wouldn't have to build around it.

If you really do not want the control pillar there, you can remove the wall, but remind me of this request if this is merged so I can make such a tweak for the console. Right now, I am working on the base code with WJ to support landing the mining shuttle nearby.

**Comment by Cheridan** [comment]
@Bawhoppen you can still use the construction area as a construction area?? nothing is stopping you from doing that. this just adds the ability to drop it to lavaland

**Comment by Core0verload** [comment]
Just make it an empty area in space, with shuttle dock and drop console being marked by floor tiles. This way it wouldn't be a tumor, and you would be able to chose a shape of brick you drop.

**Comment by Bawhoppen** [comment]
@GunHog On sybil yes it is never used (well sybil is mostly box anyways), but I have seen tons of fun things happen there on basil
I have already suggested what to do, just make the maint tunnel into a kind of hallway and put it above it like this:
ss 2016-08-10 at 06 32 26

**Comment by WJohn** [comment]
Sorry for taking as long as I did to fix this.

Also bawhoppen what you've shown there is an abomination of mapping. I will not keep a huge construction area as a higher-priority zone, then tuck away an equally large construction area behind it where no one will ever see it.

**Comment by WJohn** [comment]
Gonna have to nuke this because I ruined everything be RIIIIGHT back!

**Comment by GunHog** [comment]
Had a mini heart-attack when I saw the red on this PR...

**Pull request closed without merging**
