### PR TITLE
Important Moth Related Tramstation Fix

### PR DESCRIPTION
**Pull request by Maurukas**
## About The Pull Request

A piece of job critical equipment is missing from the Tramstation's psychologist office. Central Command has authorized the distribution of one moth plush from the corporate stockpile to remedy this. Guard it well.

## Why It's Good For The Game
image

We're on a timer here. God only knows what they will do if their demands aren't met.

## Changelog
:cl:
fix: One standard moth plushie has been issued to the tramstation psychologist's office.
/:cl:

### CODE REVIEW

**Comment by Mothblocks** [comment]
my HERO

**Comment by optimumtact** [comment]
Moths are a scourge, this PR is blocked

**Comment by Mothblocks** [comment]
moth blocked

up high ✋

**Comment by optimumtact** [comment]
:hand:

**Comment by Mothblocks** [comment]
🙏

**Pull request merged**
