### PR TITLE
Hos sprites

### PR DESCRIPTION
**Pull request by Supermichael777**
:cl: 
add: Ian can now wear the HoS cap. Bark bark
imageadd: Resprited the Hos cap because the old sprite and icon were ugly and inconsistent.
/:cl:

The new sprites are here

nerd

Sorry I made three prs for such a simple change.  I felt the best way to undo my mistakes was to simply copy the changes to a new branch

### CODE REVIEW

**Comment by Niknakflak** [comment]
looks like a tumor hat on humans

**Comment by Supermichael777** [comment]
well unless i get some of @Nienhaus sprite magic it will have to do.

**Comment by WJohn** [comment]
Thats a pretty bad sprite. Gotta agree with niknak here. :-1:

**Comment by PKPenguin321** [comment]
that's pretty bad

**Comment by Thunder12345** [comment]
This is even more ugly than the current one

**Comment by ChangelingRain** [comment]
this is actually godawful why do you think this is better

**Comment by Supermichael777** [comment]
fug
better get moar practice

**Pull request closed without merging**
