### PR TITLE
Flappity Flap? Readds moth language

### PR DESCRIPTION
**Pull request by ghost**
:cl: More Robust Than You
add: Moths can speak Lepidopterian again!
/:cl:

Moth circlejerks are what moths are all about, and removing Lepidopterian broke them up!

### CODE REVIEW

**Comment by praisenarsie** [comment]
This is against contributing guidelines.

**Comment by Buggy123** [comment]
It's about damn time

**Comment by vuonojenmustaturska** [comment]
It hasn't even been two weeks since the equivalent PR was closed

**Comment by Rockdtben** [comment]
image

**Comment by MoreRobustThanYou** [comment]
~if nazis are banned, why is lzimann a maintainer~

**Comment by lzimann** [comment]
since he deleted

**Comment by MoreRobustThanYou** [comment]
truth be told, you aren't really a fun-loving kind of person from all that I can tell

**Comment by praisenarsie** [comment]
@MoreRobustThanYou he's doing his duty as a maintainer??????

**Comment by MoreRobustThanYou** [comment]
@praisenarsie good point

**Comment by Tlaltecuhtli** [comment]
is erp not banned then?

**Comment by Rockdtben** [comment]
@Tlaltecuhtli Please read the last sentence in that picture. You are smarter than this.

**Pull request closed without merging**
