### PR TITLE
Explosions no longer throw anchored items.

### LINKED ISSUE #9943: Explosions can throw station intercoms and other anchored items
Presumably this includes gibtonite.

### PR DESCRIPTION
**Pull request by phil235**
Fixes #9943

### CODE REVIEW

**Comment by Razharas** [comment]
>Intercomms are items

Thats the real problem

**Comment by Anonus** [comment]
Gibtonite is also anchored, though.

**Comment by Dorsisdwarf** [comment]
What do you mean, it's anchored?

**Comment by Miauw62** [comment]
intercomms being machinery with a station-bounced radio inside is completely possible.

**Comment by Razharas** [comment]
^

**Comment by Supermichael777** [comment]
Boom Boom shake the room.

**Pull request merged**
