### PR TITLE
Tramstation Nu-Medbay (again)

### PR DESCRIPTION
**Pull request by MMMiracles**
## About The Pull Request

Remaps the medical wing (again) to more properly suite the act of working as a medical doctor.

## Why It's Good For The Game
After seeing such classic criticism as [the defib glass table](https://user-images.githubusercontent.com/9276171/148595154-5aff1025-45bf-49be-9778-5a3a4ed261f7.png), I realized my choices in the new layout may of overlooked a few key issues for those who uh, actually play Medical.

## Changelog

:cl: MMMiracles
add: Tramstation's medical wing has been revamped once again to maybe not be as bad as before.
/:cl:

image

- Security's outpost is now off to the side instead of dead center
- The treatment center is easily accessed as soon as you enter
- The CMO's office and break room was pushed more towards the bottom of the department.
- There is now a chemical storage room at the bottom of the department.
- A hopefully more well equipped medical storage with secure windoors protecting the actual medical supplies.
- A crew console is accessible in the main medical hallway as well as the CMO's office.
- Better defib placements in the central treatment wing.

Listed as a draft since I need to do the maintenance segment still, Medical is finished though.

### CODE REVIEW

**Comment by Sealed101** [comment]
bring the glass table defib (ni defib just the mount) back in the maint area

**Comment by MMMiracles** [comment]
no its funny

**Comment by TheBonded** [comment]
I dont see any medical lockers in the medical storage room, are there any nitrile gloves placed to make sure they are available to the doctors? (im probably just blind but still good to bring this up just in case)

**Comment by MMMiracles** [comment]
PR updated with a general list of changes from the current medbay.

**Comment by YakumoChen** [comment]
is there going to be a port-side maint? Medical always did concern me with the lack of ways to actually leave the department.

**Comment by notfrying1pans** [comment]
The med storage room's entrance is a bit awkward, and the cmo office is missing a reinforced wall. other than that i like it!

**Review by Maurukas — COMMENTED** [review]
You knew exactly what you were doing here

image

**Comment by Maurukas** [comment]
Between the default lockers and medbay storage, you have 5 roundstart defibs mapped in. Is this intended?

image

**Pull request merged**
