### PR TITLE
Deathmatch: Waffle Corp Parking Lot

### PR DESCRIPTION
**Pull request by DaCoolBoss**
## About The Pull Request
Now you can compete in the asphalt arena with your friends. Pick one of 5 syndicate loadouts and fight up to 11 other agents in the parking lot of a combination breakfast food chain restaurant and gun factory.

GILwB73 1
9Mx6hwK 1

The Waffle Corp Parking Lot is a wide-open deathmatch map focusing on gunplay. There are large areas with good sightlines, and a variety of corners, obstacles and cover to provide tactical options. Every player will start off with a mid-tier gun, and scattered across the map are gun-only lootboxes to replace or add to your arsenal. Melee options are limited.

LOADOUTS:
1. Spinward Syndicate Agent - Typical turtleneck-and-armor agent outfit. Primary weapon: Makarov Pistol.
spinward

2. Donk Company Employee - Black-and-brown clothing with orange branding and highlights. Primary weapon: .38 Revolver.
donk

3. Waffle Corporation Private Security Guard - Blue camo with an armor vest and helmet. Primary weapon: WT-550 variant. 
waffle

4. Cybersun Corportation Troubleshooter - Black combat uniform with a black armored trenchcoat and black shades. Primary weapon: C-120 Energy Carbine
cybersun

5. Gorlex Marauders Rent-A-Trooper: Bright red and jet combat black uniform with signature SWAT helmet. Primary weapon: Pump Action Shotgun (Buckshot)
gorlex
full map

Two minor changes to things outside deathmatch: fences now let projectiles pass them 70% of the time unless the bullet is aimed at the fence itself (fences with holes cut in them have a higher projectile penetration rate) and the camo outfit used by the waffle corp reinforcements summoned via nuke op beacon is now blue instead of green. The green camo is still in the game everywhere else.

It's nearly complete, just needs some polish and the cybersun class's weapon recharger isn't functioning right now. Haven't tested with perspective walls yet, but I've designed the map with it in mind (no posters on non-north walls, no machine mounted machines, nothing pixel shifted onto walls).
## Why It's Good For The Game
I wanted a big wide-open deathmatch map and one that also has syndicate agents shooting each other because I find that very funny. Most of the current shooting maps are balanced for a mix of melee and ranged combat, this one's for people who just want to use guns on other people using guns.

Also Waffle Corporation had next to no representation in game and surprisingly little theme. Their nuke op reinforcement looks a bit like a UN peacekeeper, they have their name stamped on some of the Syndicate's guns (not often because they mostly use subsidiaries apparently), and they have a nominal connection to waffles and a hatred of Donk Co that isn't really shown in game. So I'm adding more theme to them by making them diametric opposites of Donk Co. 

Donk Co's colour palette is warm oranges and browns, so Waffle Corp's new palette is cold blues and greys. Donk Co uses wood frames for their retro guns, Waffle Corp makes the metal and plastic modern ones. Donk Co uses wooden floors and tables, Waffle Corp uses metal almost exclusively. Donk Co is a little silly and over-the-top, Waffle Corp is professional and no-nonsense. And so on. 
## Changelog
:cl:
add: Added a new deathmatch map, Waffle Corp Parking Lot
balance: Fences now have a high chance of allowing projectiles to pass.
image: Waffle Corp nuke op reinforcements now wear blue camoflage fatigues instead of green.
/:cl:

### CODE REVIEW

**Comment by YesterdaysPromise** [comment]
Oi, got a discord? Happend to be spriting syndicate clothes and whatnots and it seems like a good go-along.

**Comment by mc-oofert** [comment]
deathmatch maps dont need to be surrounded by indestructible turfs like those cool matrix walls from bitrunning as the map gets cordons placed around it during loading, but it would probably still need some in spots it would leak to space

**Review by Twaticus — CHANGES_REQUESTED** [review]
blue camo sure but use an existing leather coat instead we dont need another

**Comment by DaCoolBoss** [comment]
> deathmatch maps dont need to be surrounded by indestructible turfs like those cool matrix walls from bitrunning as the map gets cordons placed around it during loading, but it would probably still need some in spots it would leak to space

It leaks blue light in from space and ruins the illusion of being on a planet. Here's the same walls with a layer of matrix walls and then without it.

ZRu5uxh 1
wlewggP 1
Screenshot 2024-08-09 184450
Screenshot 2024-08-09 183718

> blue camo sure but use an existing leather coat instead we dont need another

Yeah detective coat looks better I think.

Screenshot 2024-08-09 183927

> humble request to give the donk co guy a riot dart filled smg in the backpack.

Not putting nonlethals in, so Donk Co. gets a bunch of grenades. Foam dart might need its own deathmatch mode.

**Comment by mc-oofert** [comment]
> > deathmatch maps dont need to be surrounded by indestructible turfs like those cool matrix walls from bitrunning as the map gets cordons placed around it during loading, but it would probably still need some in spots it would leak to space
> 
> It leaks blue light in from space and ruins the illusion of being on a planet. Here's the same walls with a layer of matrix walls and then without it.

Then use the indestructible plating turf reservation as used in trainship hijack

**Comment by Yobrocharlie** [comment]
Amazing 10/10 map keep up the good work

**Comment by Zargoar** [comment]
I look forward to this being added.

**Comment by DaCoolBoss** [comment]
Still working on this, just got delayed for a while. Map got wallening-ized and unwallening-ized and is in a complete state, only IDs and cybersun class's gimmick weapon recharger need completed so will be finished soon. Also all the classes spawn with microbombs now. Looting corpses is now much more difficult and the use of melee weapons on downed opponents is discouraged. I think it opens some fun new strategies, and encourages players to succumb and become a ghost instead of hanging around in crit without any hope of winning.

**Pull request closed without merging**
