### PR TITLE
Sending adminpms from IRC.

### PR DESCRIPTION
**Pull request by Shadowlight213**
Haven't tested it, so I'm not 100% sure if it works.
This should hook into the adminbus bot's existing pm sending code.

### CODE REVIEW

**Comment by kevinz000** [comment]
IC issue

**Comment by RemieRichards** [comment]
@kevinz000 
>IRC issue

**Comment by Shadowlight213** [comment]
DNM since i still haven't been able to test this due to the bot's connection function for the pms not being setup correctly.

**Comment by optimumtact** [comment]
Any news?

**Comment by Shadowlight213** [comment]
Still waiting on @MrStonedOne to make the necessary changes to the bot function to be able to really test.

**Comment by optimumtact** [comment]
Ded

**Comment by optimumtact** [comment]
@MrStonedOne oi

**Pull request merged**
