### PR TITLE
Turns mush cap into an extorgan

### PR DESCRIPTION
**Pull request by Time-Green**
Pretty self explanatory. I suppose this isn't a 100% fix or refactor, since it adds a UI for their features and makes it removable, but also these never happen

:cl:
code: The mushroom cap is now an external organ (jungle station will never happen)
fix: Mushpeople caps are no longer solid black
/:cl:

### CODE REVIEW

**Comment by Time-Green** [comment]
I'm too tired to deal with this rn

**Comment by Time-Green** [comment]
Nevermind it was a very small typo

**Comment by Time-Green** [comment]
image
Now just to kill body markings (tattoo datum with bodypart overlays or smthing?), ears (for this I need to modularize the external organs code, raaagh) and "legs" which I am terrified to even guess at

**Comment by Time-Green** [comment]
Oh wow, apparently their icon generated wrong and I accidentally fixed it. I love surprise GBP

**Comment by Ghommie** [comment]
Oh shoes, you're right!

**Comment by Time-Green** [comment]
> image
> 
> These used to spawn with randomized colors for the caps, I think? At some point anyway. Now they're all just like flesh-toned.

Wait really? Shit. They weren’t even grayscaled or something

**Comment by Time-Green** [comment]
> image
> 
> These used to spawn with randomized colors for the caps, I think? At some point anyway. Now they're all just like flesh-toned.

Also how did you even notice this this fast? These things basically never happen

**Pull request merged**
