### PR TITLE
adds yeehaw.ogg to round end sounds

### PR DESCRIPTION
**Pull request by dannno**
:cl: Dannno
add: yeehaw.ogg is now a round end sound
/:cl:

thanks kor

### CODE REVIEW

**Comment by AdamElTablawy** [comment]
why an ogg

**Comment by sawrge** [comment]
this cost me $30

**Comment by dannno** [comment]
because they're all oggs

**Comment by lzimann** [comment]
this is... awful

**Comment by AdamElTablawy** [comment]
don't use a fucking ogg

use a .wav

**Comment by dannno** [comment]
that's a really rude thing to say about kor

**Comment by dannno** [comment]
if you want to turn all the oggs into wavs feel free

**Comment by bgobandit** [comment]
no player references sorry

**Comment by sawrge** [comment]
its not a player reference

**Comment by dannno** [comment]
👍

**Comment by PKPenguin321** [comment]
?????????????????

**Comment by Xhuis** [comment]
just let it happen pk

**Comment by Sometinyprick** [comment]
yeehaw

**Comment by dannno** [comment]
SPACCEMANSPARK

**Comment by Chocobro** [comment]
you spent thirty united states dollars to have some subpar audio quality and copy pasteable code
:+1:

**Comment by sawrge** [comment]
Scared?

**Comment by sawrge** [comment]
[https://my.mixtape.moe/bmjgfj.png](url)

**Comment by dannno** [comment]
flaccid

**Comment by PKPenguin321** [comment]
best PR of ALL TIME

**Comment by dannno** [comment]
you're welcome champ

**Pull request merged**
