### PR TITLE
fixes caves.dmm not actually working

### LINKED ISSUE #13444: Caves.dm is broken and won't open
On inspection, it appears to still have merge tags in it, probably due to an improper merge conflict fix.
@MMMiracles

### PR DESCRIPTION
**Pull request by MMMiracles**
fixes #13444

i am good at merging

### CODE REVIEW

**Comment by MMMiracles** [comment]
literally high priority because its my map

**Comment by Anonus** [comment]
There are a few errors, probably due to improper merge.
fourth area
third area

**Comment by MMMiracles** [comment]
i really should look over the map instead of just changing it in notepad.

**Comment by MMMiracles** [comment]
i actually looked over it now and i'm pretty sure I fixed all the oddities.

**Comment by Jordie0608** [comment]
You should add this to the away mission configs.

**Comment by MMMiracles** [comment]
k

**Comment by Anonus** [comment]
I can confirm that this has no easily visible issues and is effectively ready for merge, so someone should.

**Pull request merged**
