### PR TITLE
Birdstation update #5 mining

### PR DESCRIPTION
**Pull request by Tokiko1**
Changes a lot about mining and mining related things as suggested by players. Also makes the armory less lethal in general.

See below for a full list of changes.

Added a cyborg and mech charger to the mining station.
Added a lot of high chance ore spawns to the outer asteroids to make it more desireble to mine these.
Main mining asteroid roughly doubled in size.
Added some wumborian fugus to the asteroid.
Added a few bananium ore patches to the main asteroid.
Removed all but one xenoegg spawns, made the remaining one spawn an embryo on failure.
Added a large amount of mobs to the room containing the xenoegg to stop players from easily obtaining it.

Station:
Added a bunch of RP related items suggested by people.
Removed autorifles from the armory.
Added riot shotguns and rubber + lethal ammo to armory.
Added special temperature guns to the armory that come with pins and have reduced research levels.
Replaced the energy guns in the armory with disablers.
Added a random organ spawner locker to xenomed.
Modified xenobio maint to allow slime console cursors to move through it.
Added a second slime management console.
Added science goggles to chem and science.
Added beer goggles to the kitchen.
Changed the oxygen pipe color near the supermatter engine to cyan.
Changed the reflector layout in engineering.
Added a safety door between the supermatter engine room and the reflector room.
Added a coin press just outside of the maint casino.
Fixed the backwards piano in the theatre.
Replaced the armory desk with a window.
Added more portable flashers to security.

### CODE REVIEW

**Comment by GunHog** [comment]
>See commits for a full list of changes.

143 additions, 130 deletions not shown

Pictures and details, please. You should not be forcing people to download the map changes to know what you did!

**Comment by Zilenan91** [comment]
Why did you replace all the eguns with disablers? Those will only really be appreciated on bagil, but they only have like 6 people at peak anyways, and they all only play Meta, so even then not very much.

**Comment by Tokiko1** [comment]
Well, this is a lowpop map afterall. It shouldn't even be played on 30+ populations. Seems right to balance it around what lowpop players suggest.

GunHog, try expanding the text in the commits. Unless you mean that list is not detailed enough.

**Comment by GunHog** [comment]
D'oh. I am stupid, I was looking at the diff, not the commit description. Statements retracted!

**Comment by Dorsisdwarf** [comment]
You're welcome

**Pull request merged**
