### PR TITLE
Adds sofas

### PR DESCRIPTION
**Pull request by silicons**
What title says.

:cl:
rscadd: Sofas have been added. Make 'em with metal, 1 sheet each.
/:cl:
image

### CODE REVIEW

**Comment by nicbn** [comment]
Make them use smoothing instead of making many items

**Comment by MrDoomBringer** [comment]
@kevinz000 OOH the sprites are directional lmao

**Comment by improvedname** [comment]
Kevinz porting citadel features to tg so he can return

**Comment by Cyprex** [comment]
Shouldn't these be made from leather?

**Comment by ExcessiveUseOfCobblestone** [comment]
Glad to see ERP isn't being encouraged by having the couch black.

**Comment by GuyonBroadway** [comment]
Can you occasionally find coins down the back of them?

**Comment by necromanceranne** [comment]
It's time to make the station comfy

**Comment by optimumtact** [comment]
make it use the smoothing subsystem

smh lazy port

**Comment by kevinz000** [comment]
Smoothing would not allow for things like having two rows of sofas directed towards each other without the entire thing being weird, sometimes you don't want corners.
@nicbn

**Comment by optimumtact** [comment]
sofa king serious

**Comment by Mickyan** [comment]
Man why is everything made out of metal, we have cloth which is barely used at all

**Comment by GuyonBroadway** [comment]
For pointless decorative stuff like this metal is easy to get and all its good for is comfy autism forts.

**Comment by JStheguy** [comment]
Now we just need trash can (disposal bin?) fires for the complete hobo camp package.

**Comment by tuypo1** [comment]
sofas should take more than just some metal, maybe make them need some sort of leather

**Comment by nicbn** [comment]
Make your chances of cardiac arrest increase if you sit for long enough on a sofa (and increase even more if you're eat potato chips while doing so).

**Comment by nicbn** [comment]
You could do something like the directional windows for deciding the sofa direction, and make sofas show their ends based on the direction.
If two sofas with direfent directions are adjacent in a way that they can create a corner, they do so.

**Comment by Swiftkor** [comment]
Finally, I can truely complete my psychologist gimmick with a therapy couch.

**Pull request merged**
