### PR TITLE
Removes remove_any from the game

### PR DESCRIPTION
**Pull request by RikuTheKiller**
## About The Pull Request

Okay, so, turns out smoke machines, cigarettes, vapes and all sorts of things intentionally unmix your mixes.
Why? For chaotic effects. Well sadly it just deletes chems from mixes and makes them completely useless.
It also tends to have very little effect on deathmixes and moreso just gimps you ability to use them for healing.
This is pretty bad, especially for machines like the smoke machine that are specifically intended for chemists.

This PR entirely removes all uses of remove_any as well as the proc itself from the game. It's just bad.
## Why It's Good For The Game

As it turns out, the game intentionally gimping your chem mixes just to fuck with you is bad.
Especially when it's both obscure and not really all that fun for gameplay.
## Changelog
:cl:
balance: Smoke Machines, Showers, Vapes, etc will no longer arbitrarily delete a random amount of the chems they are processing
/:cl:

### CODE REVIEW

**Comment by SyncIt21** [comment]
It's fine just nerf `remove_any()` proc completely from the codebase. I've been meaning to do for a long time.

**Comment by RikuTheKiller** [comment]
> It's fine just nerf `remove_any()` proc completely from the codebase. I've been meaning to do this for a long time.
> 
> Also please re-write your changeog in a way players can understand. Words like "quantum filters" makes no sense to anyone

i legit edited it to include a parentheses explained version but apparently that wasnt saved some-fucking-how

**Comment by SyncIt21** [comment]
Update your PR body and title

**Comment by RikuTheKiller** [comment]
> Update your PR body and title

updated

**Comment by ZephyrTFA** [comment]
I updated your changelog to actually make sense to players.
Don't include code details, players both won't know and won't care.

**Comment by RikuTheKiller** [comment]
> I updated your changelog to actually make sense to players. Don't include code details, players both won't know and won't care.

I mean the changelog edit is kinda wrong, they didn't remove arbitrary amounts of reagents they removed reagents arbitrarily, but that's a nitpick.

**Pull request merged**
