### PR TITLE
Re-organizes the files in the root of the icons/ folder into it's substituents

### PR DESCRIPTION
**Pull request by san7890**
## About The Pull Request

Same vein (although a lot larger than) #64118

On the tin. This moves them into their own folders and the paths were updated in the code.

## Why It's Good For The Game

It's not exactly good visuals for stuff that can be placed elsewhere to just be sitting in the root. Organization is nice.

## Changelog

:cl:
fix: For those of you into code, some stuff with the icon pathing has been shuffled around so it's no longer in the roots of the icon/ folder. If you aren't into code, that's fine too.
/:cl:

### CODE REVIEW

**Comment by tralezab** [comment]
...optics?

**Comment by san7890** [comment]
> ...optics?

fixed

**Comment by san7890** [comment]
renamed the pr because i didn't "get rid" of the icons, they're still there

**Comment by Fikou** [comment]
whys this fix label

**Comment by san7890** [comment]
> whys this fix label

Something had to go in the changelog (yes I know its not exactly needed but I don't like leaving empty spaces) and I'm not sure if this is exactly code improvement.

**Pull request merged**
