### PR TITLE
Removes oranges

### PR DESCRIPTION
**Pull request by jughu**
This fruit is never grown and only causes drama

### CODE REVIEW

**Comment by Doppeltongue** [comment]
That was fast.

**Comment by jughu** [comment]
@AnturK 24 hour rule

**Comment by Cyberboss** [comment]
We don't respect that for meme PRs anymore

**Comment by jughu** [comment]
this is a very serious pr

**Comment by duncathan** [comment]
can you remove the `orange()` proc from our codebase instead?

**Comment by Pascal125** [comment]
Check it before you hit close you massive fag.
This removes oranges, oranges are obviously fetish code.

**Pull request closed without merging**
