### PR TITLE
Adds colours to languages that lack them

### PR DESCRIPTION
**Pull request by coiax**
:cl: coiax
add: Drone, monkey and swarmer language now have distinctive colours when
spoken.
/:cl:
BEFORE:
image

AFTER:
image

### CODE REVIEW

**Comment by Niknakflak** [comment]
Too many colors.  Radio channels and now fucking languages ahaaaaaaaaaaa where does it stop

**Comment by RemieRichards** [comment]
strongly disagree.
raw, plain text, is black. it should stay that way regardless of language spoken, UNLESS said language is a hivemind, but we already colour those.

**Comment by coiax** [comment]
We already have coloured languages for xenos, slimes, Ratvar, EAL. I'm just making it consistent. Without the colouring, it's often difficult to tell what language you are speaking.

**Comment by RemieRichards** [comment]
Uh, you should know what language you're speaking.
Either you:
A. Selected it as your default
or
B. Typed in the language key

**Comment by coiax** [comment]
IT also means that observers can tell what language is being spoken, because they understand them all.

**Comment by RemieRichards** [comment]
doesn't really matter whats spoken since they can understand it.

**Comment by coiax** [comment]
Yes, but they want to be able to tell if other people can understand it.

**Comment by RemieRichards** [comment]
stick the name of the language next to it for ghosts then?

**Comment by Jalleo** [comment]
This feels more like a observer feature than a consistency fix.

**Comment by coiax** [comment]
Except, as I have said, other languages already have colours when spoken.

**Comment by RemieRichards** [comment]
and surely you can infer from what's been said that maybe they shouldn't.

**Comment by AnturK** [comment]
What languages have colors ? Only channels do afaik ?

**Comment by duncathan** [comment]
According to the screenshot slime, xeno, ratvar, machine. That's more languages (excluding common) with colours than without colours, so this is a consistency fix. Whether the colours should even be around can be PR'd post-freeze.

**Comment by duncathan** [comment]
I don't really care either way whether uncommon languages have colors but the majority currently do so making it consistent with this PR is good

**Comment by AnturK** [comment]
I don't think adding more rainbow colors to our already busy chat is good idea.

**Comment by lzimann** [comment]
this is ugly

**Comment by Iamgoofball** [comment]
runescape font when

**Comment by Iatots** [comment]
monkey should not be too different from human, keep it black.

**Comment by Armhulen** [comment]
Add swarmer, but don't add drone or monkey.

**Comment by coiax** [comment]
Different languages need markers so people fluent in them can still tell that they're being used. Unless people can come up with a better solution, then marking non-common languages in colours is the best idea.

**Comment by Armhulen** [comment]
Then give a font, not a color.

**Comment by octareenroon91** [comment]
>more font variations

What, wingdings? Papyrus? Console? light-text-on-dark-background?

**Comment by ExcessiveUseOfCobblestone** [comment]
@Iamgoofball pretend like it's a bug that we don't have runescape text then PR it in as a fix :^)

**Comment by duncathan** [comment]
whether this is a good idea can be discussed after things are made consistent. I don't care if someone wants to remove the colors instead (that'd be a formatting removal so it shouldn't break the freeze rules) but I just want consistency

**Pull request merged**
