### PR TITLE
Fix - Creampie Spellcheck

### PR DESCRIPTION
**Pull request by Mercenaryblue**
Removes an unnecessary The when a creampie hits target.

### CODE REVIEW

**Comment by Man-Shroom-** [comment]
>0 files changed

????

**Comment by N3X15** [comment]
NINJA CHANGE
I BET IT'S A BALANCE CHANGE

**Comment by optimumtact** [comment]
10/10 good commit practice

**Comment by PKPenguin321** [comment]
>12 commits to fi a rogue "The"
>they're all merging the master branch except the last one which has a "CPFix"
>doesn't even fix it

my sides

**Comment by Mercenaryblue** [comment]
oh fucking hell. I swear I changed the file.

**Comment by KorPhaeron** [comment]
I'm merging this because it's a single world typo fix and the massive amount of unmerged prs is triggering me

**Pull request merged**
