### PR TITLE
Makes the prices more reasonable.

### PR DESCRIPTION
**Pull request by BeeSting12**
:cl: BeeSting12
balance: Some prices have been changed to be more reasonable.
/:cl:
Just getting the PR up here so I can get comments on what needs to be changed before I start getting real work done on it. I'm not writing a why for each one and I'm not going to spend much time arguing on each one because fuck that.

Vendors to review:
- [x] YouTool
- [x] Booze-O-Mat (bar)
- [x] Dinnerware (kitchen)
- [x] Botany
- [x] Medical (EMERGENCY nanomed costs money lmao)
- [x] Vendomat
- [x] Engineering Vendors ($25 RCDs lol)
- [x] Shadycigs
- [x] Snack/drink vendors
- [x] Autodrobe/costume vendors
- [x] Misc.

### CODE REVIEW

**Comment by Razharas** [comment]
Make roundstart prices depend of the materials used for crafting/production of the stuff * time it takes to make / amout of the type of this stuff just lieing around the station at round start
Make all vendors accept stuff in like snacks with cook food does
Make the price of the inserted item be settable to whatever inserter wants, with destination either to his account or his department account

**Comment by Arkvold** [comment]
Probably should mention #40512 , as these two PRs seem to be after similar goals of price adjustment.

**Comment by MMMiracles** [comment]
One thing should be that when it comes to tools, the welder and multi-tool should be the premium priced items, while the crowbar/screwdriver/wrench should be more low tier. Wirecutters should be somewhere in the middle since they still have an active role in stuff like hacking doors, just not as effective as the multi-tool.

**Comment by FantasticFwoosh** [comment]
Wrenches are critical to stealing and a number of construction/deconstruction recipies like loosening girders so throwing them in mid-level would be pretty good. For convenience crowbars should be pretty cheap though since they are technically a emergency tool.

**Comment by BeeSting12** [comment]
@Razharas 
I'm going to look into basing prices for stuff that can be made in the autolathe off of material costs. A crate of 50 metal sheets costs 2000 credits, each metal sheet costs 400 credits. 4000 units per sheet goes into the lathe. 

@MMMiracles @FantasticFwoosh 
I'm going to make the cost of tools standardized. Multitools aren't even in the vendor.

@fen0s 
Yeah insulated gloves will cost about a hundred dollars when I'm done.

**Comment by BeeSting12** [comment]
It might be funny to even make tool prices randomized within a certain range.

**Comment by bgobandit** [comment]
> Medical (EMERGENCY nanomed costs money lmao)

I take it you don't live in the united states

**Comment by BeeSting12** [comment]
I do.

**Comment by Barhandar** [comment]
>I take it you don't live in the united states

USA currently doesn't require money upfront for ER, just massive debt afterwards

**Comment by Mickyan** [comment]
consider also changing paychecks while you're working on this, I suggest lowering high paying jobs a bit so we don't end up in a situation where we either have to add items that cost thousands of credits or leave high paying jobs with effectively infinite money

**Comment by MMMiracles** [comment]
nerfing paychecks on the higher end is probably not a bad idea but that would be much better suited for a different PR

**Comment by FantasticFwoosh** [comment]
@BeeSting12 throwing at the wall to see what sticks here, but would allowing cargo/engineering to refill the vendors like the chef inserts their 'selection' (which needs to be priced) by just adding tools to the lathe be a good change for sustainability?

More incentive to build vendors around that wire straight back into departments.

**Comment by QualityVan** [comment]
If it's an emergency, shouldn't you be more than willing to pay extra?

**Comment by Iamgoofball** [comment]
what @QualityVan said

**Comment by Tlaltecuhtli** [comment]
dont forget DONKSOFT vendors

**Comment by JStheguy** [comment]
> > I take it you don't live in the united states
> 
> USA currently doesn't require money upfront for ER, just massive debt afterwards

Nanomed letting you go into negative balance when?

**Comment by Kagus** [comment]
> > > I take it you don't live in the united states
> > 
> > 
> > USA currently doesn't require money upfront for ER, just massive debt afterwards
> 
> Nanomed letting you go into negative balance when?

"Welcome to Nanotrasen Banking! Your account balance has been overdrawn. You have been fined $400 for not having enough money."

**Comment by Tlaltecuhtli** [comment]
just make it so if you have a negative balance for enough time nt sells your soul

**Comment by BeeSting12** [comment]
I've been looking at the YouTool. Here's my list of changes:
1. Flashlights to 10 dollars.
2. Glowsticks to 10 dollars.
3. Insulated gloves to 80 dollars.
4. All tools are changed to 20 dollars.
5. Analyzers and T-ray scanners are changed to 10 each.

**Comment by Tlaltecuhtli** [comment]
i would say insulates 150$

**Comment by YakumoChen** [comment]
So is goof paying for this code since he was too lazy to fix it himself

**Comment by Kagus** [comment]
> So is goof paying for this code since he was too lazy to fix it himself

It's called the trickle-down effect, and it works.

**Comment by BeeSting12** [comment]
Snack and Drink Vendors: Leaving as is. Expensive snacks will promote going to the chef for food and drinks instead just running to the nearest snack machine. Drinks are basically useless right now (thirst bar when?) so 10 dollars seems like a fair price for something people only buy for a) slips or b) to craft IEDs.

**Comment by Kagus** [comment]
Also c) grinding canned air along with a piece of metal in order to make thermite.

**Comment by BeeSting12** [comment]
Booze-O-Mat:
1. All drinks are 20 dollars now. More expensive than sodas because alcohol is generally more expensive, but not 50 dollars more expensive.
2. I set all the nonalcoholic beverages in there to 10 dollars. 
3. Shot glasses and drink glasses are 5 dollars.
4. Flasks are 30 dollars. No real reason there, just flavor.
5. The canned cola price was set to 10 for consistency with the soda machines.
6. Ice is 5 dollars. Noone will pay 20 bucks for an ice cup, let alone 50.

**Comment by BeeSting12** [comment]
Shady Cigs:
1. Left the price of cigarettes at ten.
2. Changed the premium price (cigars, robust gold) to fifty to make them a kind of status symbol.
3. Added zippos to the premium list instead of contraband, again, making them a status symbol.

**Comment by BeeSting12** [comment]
I'll try to finish this tonight, was too busy playing fortnite yesterday to do it.

**Comment by AnturK** [comment]
:clock11:

**Comment by BeeSting12** [comment]
@AnturK yea i think im done now

**Pull request merged**
