### PR TITLE
Players are dumb lmao, oranges was here 2021

### PR DESCRIPTION
**Pull request by Mothblocks**
## Changelog

:cl:
add: Added new mechanics or gameplay changes
add: Added more things
expansion: Expands content of an existing feature
del: Removed old things
qol: made something easier to use
balance: rebalanced something
fix: fixed a few things
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

### CODE REVIEW

**Comment by peptron1** [comment]
mom and dad are fighting

**Comment by MetalClone** [comment]
please top I can't handle it when you guys yell

**Comment by MetalClone** [comment]
stop*

**Comment by tralezab** [comment]
## this dog is HILARIOUS

whatthedogdoing

**Comment by Nabski89** [comment]
Yeah it's working.

**Comment by optimumtact** [comment]
handsclaspedglasses

**Comment by MetalClone** [comment]
thog posting I see

**Comment by TJatPBnJ** [comment]
who closed this

**Comment by D4C-420** [comment]
MoffHub

**Pull request closed without merging**
