### PR TITLE
Fixes IIV [11/10/17] CONV

### PR DESCRIPTION
**Pull request by JohnOxford**
# CHANGE LOG

For the newest (und unstable) version always check the develop branch, for beta check 
master branch, for really stable stuff check the releases (the ones that have a real version number :))

## master branch

- [slaveek/panique] [PR](https://github.com/panique/huge/pull/773) [#770] fix for sending user back to last visited page after login
- [slaveek] [PR](https://github.com/panique/huge/pull/815) lots of code styling fixes 
- [panique] [#729] Fix, mail sending now returns true or false success status (https://github.com/panique/huge/issues/729)
- [OmarElGabry] [PR](https://github.com/panique/huge/pull/693) session id regeneration in certain situations
- [OmarElGabry] [PR](https://github.com/panique/huge/pull/693) encrypted cookies
- [OmarElGabry] [PR](https://github.com/panique/huge/pull/693) new encryption class
- [OmarElGabry] [PR](https://github.com/panique/huge/pull/693) anti-CSRF feature (used in login and username change forms) 
- [josh-bridge] [PR](https://github.com/panique/huge/pull/689) logged-in user can now change password
- [justincdotme] [PR](https://github.com/panique/huge/pull/684) better code for brute-force blocking when logging in
- [panique] soft autoinstaller improvements
- [panique] updated dependencies to current versions
- [Kent55/panique] XSS protection filter
- [FAlbanni] XSS protection with better session/cookie, now only allowed on used domain 
- [panique] there's now a simple Favicon and a fallback to avoid browsers hammering the application requesting favicons
- [panique] application has now a page title
- [panique] avatar upload feature can now handle jpg, png, gif
- [panique/tankerkiller125] avatars folder now does not run any PHP code (security improvement) 
- [tysonlist] [#657] send user back to last-visited page after successful login (when not being logged in first)
- [sandropons] anti-brute-force feature for login process
- [panique] removed old Facebook texts (as Login-via-Facebook feature was removed since 3.0)
- [oisian/ldmusic] [#608] Deletion / suspension of users, Admin menu
- [panique] [#654](https://github.com/panique/huge/issues/654) little frontend navi bug fixed
- [Dominic28] [PR](https://github.com/panique/huge/pull/645) added checkboxes to request class
- [Dominic28] [PR](https://github.com/panique/huge/pull/644) code style fixes
- [M0ritzWeide] [PR](https://github.com/panique/huge/pull/635) added browser caching
- [modInfo/panique] [PR](https://github.com/panique/huge/pull/647) added missing view table column

### CODE REVIEW

**Comment by praisenarsie** [comment]
obvious baaaaaaaaaaaaaaaaaaaaaaait

**Comment by JohnOxford** [comment]
no, this is a direct improvement of the codebase at large.

**Comment by JohnOxford** [comment]
why would you keep something that only causes controversy

**Comment by praisenarsie** [comment]
meme

ALSO, changing that config doesn't do fuckall to like our servers (hippie, ftl13 and citadel too prob) considering they run a config on TGS so good job john

**Pull request closed without merging**
