### PR TITLE
Automatic TGUI rebuilding on master branch via Github Actions

### PR DESCRIPTION
**Pull request by actioninja**
## About The Pull Request

Uses actions to automatically rebuild tgui if files are changed, then push the result.
Triggers on push to master, pushes results to master.

Also disables build checking in Travis because it's unimportant now.

### CODE REVIEW

**Comment by ArcaneMusic** [comment]
"You have turned my mourning into joyful dancing. You have taken away my clothes of merge-conflict and clothed me with compiling code,"
TGUI-Next 30:11

**Comment by ShizCalev** [comment]
so to double check, does this mean you no longer have to commit the compiled TGUI file?

if that's the case, should we add it to gitignore?

**Comment by MCterra10** [comment]
Can we integrate changelog generation too? Finally get rid of that part of the webhook

**Comment by actioninja** [comment]
I think I want to do that before this is merged.

**Comment by actioninja** [comment]
what if it were just amended into the previous commit?
Thonkin hard about this.

**Comment by ninjanomnom** [comment]
If we do this we definitely should be gitignoring changed compiled tgui files. The issue is tgui builds arent reproducible and vary based on os/dependency installations/whim of rng.

Do not amend commits on master.

**Comment by actioninja** [comment]
That is true for tgui builds but not tgui-next builds, they're fully deterministic.
If we're commiting the resulting build wouldn't a .gitignore not matter anymore because it's being tracked?

**Comment by ninjanomnom** [comment]
The gitignore would be so human devs don't commit changes.

If it's deterministic then I'd prefer a CI check though to make sure it was built.

**Comment by optimumtact** [comment]
git amending is a bad strategy, ideally you'd just add a commit after.

is this not possible?

**Comment by actioninja** [comment]
It's possible it's more just about the git history spam it generates. That's the reason I'd want to incorporate the CL bot into this as well to avoid generating 2 commits for every tgui-next change.

We are currently checking tgui-next builds via CI. It works, it's just the workflow is really clunky. Every time a PR gets merged it causes every single open tgui-next pr to conflict.

**Comment by optimumtact** [comment]
im not particularly worried about history spam as such, as long as the log title is simple, it can relatively easily be grepped out

**Comment by actioninja** [comment]
I was thinking more about git performance, but you always can just shallow clone thinking about it.

**Comment by SpaceManiac** [comment]
Force-pushing master on a regular basis by policy seems like a monumentally bad idea. It's definitely a step up in complexity if we were to solve this the "right" way by having a bot perform all the squash-merges

**Comment by actioninja** [comment]
Yeah I'm definitely debating whether making this action complex enough to do both the tgui rebuild and changelog rebuild in the same pass is worth the extra complexity in one action. It certainly seems possible though.

**Comment by optimumtact** [comment]
git performance would definitely be more affected by the size of the repo.

I have repos at work with hundreds of thousands of commits, git is not goind to mind

**Comment by actioninja** [comment]
This works as is then, and I'm not sure if there's any more discussion to be had than has already happened.

**Comment by optimumtact** [comment]
Well
HERE WE GO

**Comment by MCterra10** [comment]
Yeah boiiiiii!

**Pull request merged**
