### PR TITLE
makes dark wizards unable to get from gold slimes

### PR DESCRIPTION
**Pull request by Fikou**
## About The Pull Request

also gives it mob types that should be there

## Why It's Good For The Game

you can spawn a dude with slime

## Changelog
:cl:
tweak: you can no longer spawn dark wizards with gold slimes
/:cl:

### CODE REVIEW

**Comment by Shadowflame909** [comment]
you can spawn a miner with a slime

and the blobbie boys can possess dead bodies

checkmate fikou 

gimme my dark wiznerds

**Comment by carlarctg** [comment]
stupid removal..................

**Comment by carshalash** [comment]
How dare you.

**Comment by Fikou** [comment]
> you can spawn a miner with a slime

miner is an undead kind of guy, shambling miner, hes like a zombie kind of
dark wizard is just a dude in a wizard costume that you can spawn with slime for some reason

**Comment by Grazyn** [comment]
But... it's not actually a dude? It's a simple mob that looks like a dude and shoots chilling bolts

**Comment by Fikou** [comment]
> But... it's not actually a dude? It's a simple mob that looks like a dude and shoots chilling bolts

that didnt prevent all the other simplemobs that shoot stuff and look like dudes from not being in gold slimes

**Comment by Grazyn** [comment]
Yeah but what's the logic behind it? I mean those mobs still exist in the game... somewhere. Don't they? So why remove them from gold slimes?

**Comment by ishitbyabullet** [comment]
What the fuck is this reasoning to keep it in? Are we joking right now?

_Mobs exist in the game somewhere therefore they MUST be spawnable by gold slimes_ is not valid. With that logic, RnD could make all the guns in the game.

**Comment by FloranOtten** [comment]
> What the fuck is this reasoning to keep it in? Are we joking right now?
> 
> _Mobs exist in the game somewhere therefore they MUST be spawnable by gold slimes_ is not valid. With that logic, RnD could make all the guns in the game.

Why remove it though? Half the items in the game could be removed if we're asking 'why keep it.' Why keep a festivus pole in the gold pool? Doesn't serve an explicit purpose./

**Comment by Tlaltecuhtli** [comment]
i did ask auinnus and he said its intended

**Comment by ishitbyabullet** [comment]
Festivus poles aren't ICly sentient human beings. Besides that, I have no idea why they actually exist. It's probably part of an old inside joke.

**Comment by Grazyn** [comment]
>

> What the fuck is this reasoning to keep it in? Are we joking right now?
> 
> _Mobs exist in the game somewhere therefore they MUST be spawnable by gold slimes_ is not valid. With that logic, RnD could make all the guns in the game.

I mean, there are a million reasons why guns shouldn't be spawnable by science. While the only reason provided for removing gold slime mobs that look like dudes is... that they look like dudes. So I suppose it must be a design decision, that simple mobs shouldn't look like dudes for consistency. Hence my confusion about these mobs still existing in the game somewhere else.

**Comment by Ty-the-Smonk** [comment]
This change just seems kinda dumb, does dark wiz drop any broken shit or something?

**Comment by 81Denton** [comment]
We already have humanoid mobs (like the fucky shaft miners), other strong creatures and wacky stuff like the festivus pole in the spawn pool. I don't really see the need to remove those.

**Pull request closed without merging**
