### PR TITLE
[WIP] Makes the bandolier a neck item

### PR DESCRIPTION
**Pull request by Tacolizard**
:cl: Tacolizard
tweak: The bandolier is now a neck item
/:cl:

[why]: realism

todo:
test
replace all references to the old bandolier with the new one

### CODE REVIEW

**Comment by kevinz000** [comment]
13 commits 14 lines
Oh yeah we don't leave code commented in.

**Comment by Tacolizard** [comment]
1. it isnt done yet meanie
2. why is this closed

**Comment by dannno** [comment]
this is stupid

**Comment by PKPenguin321** [comment]
Feature freeze and storage creep

**Pull request closed without merging**
