### PR TITLE
[FUCK] Linters work again, V3

### LINKED ISSUE #71695: Greps are not working on CI
Local ripgrep gives an enormous. Test for yourself, install ripgrep (but not PCRE?), and run `./tools/ci/check_grep.sh`.

Likely from #71324, as the failures I'm getting are weeks old, like:

https://github.com/tgstation/tgstation/blob/master/code/modules/food_and_drinks/machinery/coffeemaker.dm#L275

@ZephyrTFA

### PR DESCRIPTION
**Pull request by ZephyrTFA**
Get linters working again, I was never using the correct directory expansion syntax for checks, so why some of them still worked anyway is beyond me.

Fixes https://github.com/tgstation/tgstation/issues/71695

### CODE REVIEW

**Comment by optimumtact** [comment]
are you going to fix all those lintfailures?

**Comment by ZephyrTFA** [comment]
That's the idea

**Comment by Mothblocks** [comment]
run them locally and just file them all in one commit imho

**Comment by ZephyrTFA** [comment]
> run them locally and just file them all in one commit imho

At work, gotta do it the stupid way

**Comment by ZephyrTFA** [comment]
They called me in and I lack the ability to say no

**Comment by Mothblocks** [comment]
Zephyr be like yeah Mothblocks some people work weekends you know

**Comment by ZephyrTFA** [comment]
Nice to know bash has a solution for everything

**Comment by ZephyrTFA** [comment]
@san7890 it's my fuckup, no gbp please

**Pull request merged**
