### PR TITLE
New Coffin Sprite

### PR DESCRIPTION
**Pull request by ghost**
dreamseeker

Coffins have a new sprite with perspective now, note that this is a vertical sprite instead of the current horizontal ones. From Goon

:cl:
imageadd: Coffins have a new sprite
/:cl:

### CODE REVIEW

**Comment by praisenarsie** [comment]
@uraniummeltdown goon shit go in the goon folder

**Comment by Jalleo** [comment]
Yup goon is a different licence

**Comment by uraniummeltdown** [comment]
will put in goon folder later

**Comment by DaxDupont** [comment]
but dead spessmen are horizontal

**Comment by Cyberboss** [comment]
@DaxDupont is very right

**Comment by Jalleo** [comment]
The coroner/chaplain moves them into the correct position when closing the coffin. By folding the spaceman so the head is beside their feet. Which is why they pop out of coffins. Top SS13 lore.

**Comment by nicbn** [comment]
Really? When you lay you stand on horizontal position not in vertical position

**Comment by nicbn** [comment]
Replacing with goon sprites for the sake of replacing with goon sprites.

**Comment by DaxDupont** [comment]
can you buckle people to caskets? otherwise say goodbye to open casket funerals

**Comment by WJohn** [comment]
This looks nice, but frankly we could get pretty much equally good looking sprites in about 5 seconds just by giving ours a proper border and some height to it.

**Comment by awesine** [comment]
Isn't /tg/ license incompatible with goonstation's license? I remember reading this a while back.

**Comment by nicbn** [comment]
It is

**Comment by awesine** [comment]
then close this kek

**Comment by nicbn** [comment]
RLY

**Pull request merged**
