### PR TITLE
Manual changelog generation

### PR DESCRIPTION
**Pull request by nfreader**
Requested by @AnturK

### CODE REVIEW

**Comment by SpaceManiac** [comment]
have the servers given up?

**Comment by nfreader** [comment]
tgs asplode apparently

**Comment by Akrilla** [comment]
yeah bunch of stuff not listed

**Review by SpaceManiac — CHANGES_REQUESTED** [review]
seems to be changing the line endings

**Comment by SpaceManiac** [comment]
same on the .yml

**Comment by SpaceManiac** [comment]
the PGP key you are signing commits with is expired

**Pull request merged**
