### PR TITLE
Tactical Suit Resprite

### PR DESCRIPTION
**Pull request by axietheaxolotl**
## About The Pull Request

hitman2

Resprites the tactical ""turtleneck"" suit. To actually be unique, and fitting.

## Why It's Good For The Game

the old one looked like poop

image

## Changelog

:cl: axietheaxolotl
imageadd: Resprited the Tactical Turtleneck Suit
/:cl:

### CODE REVIEW

**Comment by axietheaxolotl** [comment]
FEMALE_UNIFORM_TOP my beloathed

**Comment by FernandoJ8** [comment]
47

**Comment by LemonInTheDark** [comment]
I'm assuming that this having a different sprite then `/obj/item/clothing/under/suit/black_really` is intentional

**Comment by axietheaxolotl** [comment]
> I'm assuming that this having a different sprite then /obj/item/clothing/under/suit/black_really is intentional

yes

**Comment by Imaginos16** [comment]
Yea sure

**Pull request merged**
