### PR TITLE
Security's Holding Cell, Another Cut In The Behemoth

### PR DESCRIPTION
**Pull request by san7890**
## About The Pull Request

Hey there,

Here's a photograph of MetaStation's Security Wing.

image

We've had strides to cut down how just how monstrous the brig is (PRs #64851, #64445), but it's too big on some stations still.

This is another PR that seeks to split it up once more, now with the addition of the "Holding Cell area". It adds the area turf icon, the area pathing, and maps it into IceBox, Meta, and Delta.

I also realized that the Security Locker Room sprite was offset by a pixel. I passed that change into here, let me know if you want to break it off.

## Why It's Good For The Game

image

It's a monstruous area with a lot of individual rooms. Unless I think of something else, I think this may be where the train ends for the continuous carving of the brig. The beast is impossible to fell, but it can be crippled.

## Changelog

:cl:
add: On MetaStation, IceBoxStation, and DeltaStation: Nanotrasen has formally defined the "holding cell" section of the brig.
imageadd: There is now a new area icon for this new "holding cell" section.
/:cl:

### CODE REVIEW

**Comment by TheBonded** [comment]
you could also make each of the individual cells their own rooms (calling them "cell 1" through "cell3"), or make them all one separate room called "cell block" if you wanted to cut down on more

**Comment by bruhlookatthisdood** [comment]
> you could also make each of the individual cells their own rooms (calling them "cell 1" through "cell3"), or make them all one separate room called "cell block" if you wanted to cut down on more

would have to put apc's in them
and air alarms
break the apc, then escape. guh.

**Comment by TheBonded** [comment]
> > you could also make each of the individual cells their own rooms (calling them "cell 1" through "cell3"), or make them all one separate room called "cell block" if you wanted to cut down on more
> 
> would have to put apc's in them and air alarms break the apc, then escape. guh.

if you are leaving the prisoners with crowbars (needed to open depowered doors) while theyre in their cells for a 5 minute brig sentence thats your problem, not a mapping issue

**Comment by san7890** [comment]
I'm not interested (and I doubt anyone else is interested) in several snowflakey rooms that don't really have a purpose in being snowflakey. I know I come across as someone obsessed with optimization and APCs, but all the changes on production thus far have only been about as reasonable as we can get without having to need to slog through area code and area mapping on several different accounts. I've increased the amount of debt someone has to go through with areas on new maps (or maintaining older maps), while simultaneously making it better by having more sprites/pathing/variety when logical to do so.

**Review by Twaticus — APPROVED** [review]

**Pull request merged**
