### PR TITLE
tgui: Radioactive Microlaser

### PR DESCRIPTION
**Pull request by Arkatos1**
## About The Pull Request

This PR converts Radioactive Microlaser from html monstrosity to the newest version of tgui with some tweaks and improvements.

**OLD:**

MicrolaserOLD

**NEW(Updated!):**

LaserUIFixed

## Why It's Good For The Game

Better UI.

## Changelog
:cl: Arkatos
add: Radioactive Microlaser now uses tgui.
/:cl:

### CODE REVIEW

**Comment by Qustinnus** [comment]
Looks good, good job

**Comment by trollbreeder** [comment]
Omega based.

**Comment by Dennok** [comment]
Nice. But please replace numbers to component like in SMES if possible. To allow hand enter and another advantages.

**Comment by Arkatos1** [comment]
Good idea, I have updated main post with a newest image of the UI.

**Comment by stylemistake** [comment]
@Arkatos I wonder why status sticks out that way (like it has a left margin). Try removing the Box and moving the "color" property to the LabeledList.Item.

**Comment by Arkatos1** [comment]
@stylemistake Found the issue, I was missing a parent <LabeledList> for the item. Updated the main post image.

**Pull request merged**
