### PR TITLE
The clockcult empress gets a crown

### PR DESCRIPTION
**Pull request by coiax**
:cl: coiax
experiment: If you see a REALLY cranky cogscarab with a crown on, it probably
knows better than you.
/:cl:

I thought it would be funny. Gives @ChangelingRain a crown if she plays
cogscarab. That's it

### CODE REVIEW

**Comment by KorPhaeron** [comment]
"No"

**Comment by ChangelingRain** [comment]
Denied

**Comment by coiax** [comment]
RIP.

**Comment by PKPenguin321** [comment]
❄️

**Comment by Cyberboss** [comment]
> the cogscarab alarms: CEASE COMPONENT USE!

**Pull request closed without merging**
