### PR TITLE
fixes tramstation's AI sat solars not working

### PR DESCRIPTION
**Pull request by spiders24110**
## About The Pull Request
There was a wrong type of wire adapters placed everywhere, fixed now.
## Changelog
:cl:
fix: fixed tramstation's AI sat solars not working
/:cl:

### CODE REVIEW

**Comment by san7890** [comment]
@Maurukas Does this look good to you? You probably should be the only one to merge this since if it turns out it's broken, you're likely the only one to be able to fix it.

**Review by Maurukas — CHANGES_REQUESTED** [review]
You have a loop in the grid here. The SMES on the second level is charging and feeding power to the same powernet.

image

The power needs to flow from the solars to the input side of the SMES, and then from the output side of the SMES to all the APCs on the satelite.

**Comment by Striders13** [comment]
> The power needs to flow from the solars to the input side of the SMES, and then from the output side of the SMES to all the APCs on the satelite.
Would it be okay to use a different cable layer?

**Comment by Maurukas** [comment]
Yes. That's perfectly fine. In fact that's exactly what's done on the other stations for this situation. Just be aware that the two available instances of the multilayer you can map with connect to either all cable layers or no cable layers.

**Comment by Striders13** [comment]
изображение
now it shouldn't be in a loop

**Review by Maurukas — APPROVED** [review]

**Pull request merged**
