### PR TITLE
Halves strength of all chemical explosives

### PR DESCRIPTION
**Pull request by Buggy123**
image
Nitro's gonna get nerfed anyway, so might as well make things more consistent.

:cl:
balance: The strength of all chemical explosives have been halved.
/:cl:

### CODE REVIEW

**Comment by 4dplanner** [comment]
A little ahead of the game, just because 5dplanner makes a PR doesn't mean it's going to happen

**Comment by Buggy123** [comment]
> A little ahead of the game, just because 5dplanner makes a PR doesn't mean it's going to happen

Haven't you heard, this is the year of the NERF. By year's end, all that will be left is the lobby screen, because everything else is too OP to keep existing.

**Comment by 4dplanner** [comment]
If you actually look at the PR the maintainers are discussing other solutions, since that one isn't the right one.

**Comment by Buggy123** [comment]
I was under the impression that Oranges supported it, but was also looking towards possible alternatives at the same time.

**Comment by wesoda25** [comment]
lol this is stupid all other chem explosives are pathetic, nerf trit or some shit

**Comment by ExcessiveUseOfCobblestone** [comment]
*sigh*

**Comment by necromanceranne** [comment]
This is bad and you should feel bad.

**Comment by 81Denton** [comment]
This is your brain on Botany

**Comment by Tlaltecuhtli** [comment]
dumb pr

**Comment by Buggy123** [comment]
Quite a lot of people don't like this, but a lot of the recently merged nerf PRs have had pretty much the same sort of reaction so I'm not going to close this.

If you don't like it, settle that square with the players and the maintainers being on completely different tracks.

**Comment by necromanceranne** [comment]
> Quite a lot of people don't like this, but a lot of the recently merged nerf PRs have had pretty much the same sort of reaction so I'm not going to close this.
> 
> If you don't like it, square that circle where the players and the maintainers are on completely different tracks.

This doesn't seem like amazing justification to me. Just because '4dplanner is doing it' doesn't mean you can justify it by that alone. At least he justifies his changes most of the time. And his change to nitro is a nerf to botany. Not because chemistry bombs are too strong, but what botany can produce is excessive.

**Comment by 4dplanner** [comment]
> > Quite a lot of people don't like this, but a lot of the recently merged nerf PRs have had pretty much the same sort of reaction so I'm not going to close this.
> > If you don't like it, square that circle where the players and the maintainers are on completely different tracks.
> 
> This doesn't seem like amazing justification to me. Just because '4dplanner is doing it' doesn't mean you can justify it by that alone. At least he justifies his changes most of the time. And his change to nitro is a nerf to botany. Not because chemistry bombs are too strong, but what botany can produce is excessive.

That's 5dplanner ok

**Comment by Buggy123** [comment]
> > Quite a lot of people don't like this, but a lot of the recently merged nerf PRs have had pretty much the same sort of reaction so I'm not going to close this.
> > If you don't like it, square that circle where the players and the maintainers are on completely different tracks.
> 
> This doesn't seem like amazing justification to me. Just because '4dplanner is doing it' doesn't mean you can justify it by that alone. At least he justifies his changes most of the time. And his change to nitro is a nerf to botany. Not because chemistry bombs are too strong, but what botany can produce is excessive.

No, but the maintainers are looking to nerf nitro or chem grenades in general. The nitro nerf would _work_, but it's also a bit silly that nitro would have the same destructiveness as black powder but require more effort to produce. So, this accomplishes the desired nerf and fixes that oddity at the same time.

**Comment by 81Denton** [comment]
There is no need to indiscriminately nerf the power of all chemical explosives. 
What should be looked into instead are three things - KO/delimb at very low explosion severity, the easy availability of bluespace beakers and maybe even explosive lances.

**Pull request closed without merging**
