### PR TITLE
pAIs in MODsuit - Finishing what was started

### PR DESCRIPTION
**Pull request by GoldenAlpharex**
## About The Pull Request
Replaces AIs being inserted into MODsuits with pAIs.

This was originally in #63743, but John ended up giving up after maintainers didn't seem to agree with the direction he wanted to go. Obviously, most of the credits go to him, and I've gotten his authorization to re-use his code this way.

Thus, I present a touched-up version of his PR, where pAIs do not have the ability to move the MODsuit at all unless `can_pai_move_suit` is set to `TRUE` on the mod control unit, which currently can only be done by admins in-game. I'm thinking of potentially making a program which would take the majority (or entirety) of a pAI's RAM to allow them to move the suit, but regardless, they won't be able to move the suit if the wearer is not conscious (so anything between soft crit and death, passing by unconscious), to make it so they can't be used as a mean to basically give you a second chance at life, or to be your personal paramedic.

I also made removing the pAI from the MODsuit something handled via TGUI, as can be seen here:
image

Of course,  it requires the cover to be opened to allow the user to eject the pAI and i tdoes get greyed out for the pAIs, because they shouldn't be able to get themselves out of the MODsuit against their owner's wish.

## Why It's Good For The Game
You can find most of the reasoning in #63743, it stays true here as well, but basically, long story short: pAIs don't have inherent AA, access to all comms channels and binary, and don't affect the round by taking a job that's meant to interact with the station and putting it in a spot where it's basically the equivalent of being one-human'd. As a plus, it's now also a lot more intuitive to get your little buddy in your MODsuit, because you can actually pick and choose personalities that would want to be in a MODsuit, which you couldn't really do with positronic brains that you then turned into AIs.

Eventually I'd want to possibly even make it so you can select from a list of reasons why you're requesting a pAI, so people know what they're signing up for when someone's requesting a pAI, but that's a story for another day.

Oh, and if anyone actually wants to add support for positronic brains, like some maintainers have suggested, be my guest, but I'm not doing it here due to how much more complex the code would become, as a pAI is a mob whereas a positronic brain is an obj.

## Changelog

:cl: JohnFulpWillard for the initial code, GoldenAlpharex for the touch-ups and the QoL
balance: AIs controllers MODsuits cannot move an incapacitated or dead owner anymore.
refactor: Modsuits have been refactored to allow pAIs to enter them.
qol: Taking your pAI out of your MODsuit is now done via the MODsuit's interface menu rather than with an empty hand.
/:cl:

### CODE REVIEW

**Comment by JohnFulpWillard** [comment]
maintainers didnt want pAIs to move modsuits, posibrains would be fine I believe.

**Comment by GoldenAlpharex** [comment]
> maintainers didnt want pAIs to move modsuits, posibrains would be fine I believe.

Yuh, I know, I left the door open both in case they'd change their mind, or if someone wanted to introduce positronic brains into this, so there'd at least be some of the movement code already present.

**Comment by catrock31** [comment]
would it be possible to make a module that expands a pAI's control of the suit allowing it to walk around, but a high draw and complexity?

**Comment by GoldenAlpharex** [comment]
> would it be possible to make a module that expands a pAI's control of the suit allowing it to walk around, but a high draw and complexity?

That's what I was suggesting in my PR, but that'll come in a future PR, if Maintainers are willing to budge on it (which I think they should, John and Fikou's design document was pretty solid)

**Review by Mothblocks — CHANGES_REQUESTED** [review]
You seem to have missed my comment explaining what changes we actually want, let me help you with that:

image

This PR *cannot* remove AI support **unless it will replace it with MMIs**.

To repeat:

> The actions of those are specific: **don't replace AI with pAI**, replace AI with MMIs, and add pAIs later (or before).

**Comment by Mothblocks** [comment]
Your changelog also doesn't suggest AIs are replaced, even though your PR body does

**Comment by Mothblocks** [comment]
> Oh, and if anyone actually wants to add support for positronic brains, like some maintainers have suggested, be my guest, but I'm not doing it here due to how much more complex the code would become, as a pAI is a mob whereas a positronic brain is an obj.

I am assuming you meant MMI. That was not a suggestion, that was a requirement. If you don't plan on adding support for it, then there's no reason for me to keep this up

**Comment by B4CKU** [comment]
sad, this would be so cool in-game

**Pull request closed without merging**
