### PR TITLE
14 New Hairstyles

### PR DESCRIPTION
**Pull request by Shadyyy66**
## About The Pull Request

This PR adds 14
 new hairstyles (that are totally not based on any pre-existing media) into the game for humans or any hair-havers to use.

"Dolorosa"
Dolorosa

"Double"
Double

"Egg"
Egg

"Eight"
Eight

"Harley"
Harley

"Justice"
Justice

"Manime"
Manime

"Meow"
Meow

"Miracles"
Miracles

"Prince"
Prince

"Pupa"
Pupa

"Rosemary"
Rosemary

"Stride"
Stride

"Thresh"
Thresh

## Why It's Good For The Game

There aren't enough hairstyles if you ask me.

## Changelog

:cl:
add: Nanotrasen has added fourteen (14) new NT approved haircuts to their list of allowed hairstyles, check them out at your nearest mirror.
/:cl:

### CODE REVIEW

**Comment by Jacquerel** [comment]
Someone is going to inevitably tell you to put screenshots on here so it might as well be me.

**Comment by Jackal-boop** [comment]
No current hair styles have curls >:1

**Comment by tralezab** [comment]
needs pictures

**Comment by Shadyyy66** [comment]
added screenshots, cool beans

**Comment by VladinXXV** [comment]
***cough cough***
image
image

which one is it buddy im not counting them for you

**Comment by dragomagol** [comment]
Oops! All Homestuck references

**Comment by CandleJaxx** [comment]
my hands will find your neck

**Comment by Farquaar** [comment]
The names don't convey what the hairstyles look like at all. If I pick "short" hair, or "spiky" hair or "long ponytail" hair, I know what I'm going into. What does "justice" or "miracles" hair look like? How am I supposed to imagine it? Am I supposed to click on every single hairstyle before I have any idea what it is?

I am aware that there are a couple hairstyles in the codebase that already have this problem- let's not make it worse.

**Comment by Jacquerel** [comment]
> The names don't convey what the hairstyles look like at all. If I pick "short" hair, or "spiky" hair or "long ponytail" hair, I know what I'm going into. What does "justice" or "miracles" hair look like? How am I supposed to imagine it? Am I supposed to click on every single hairstyle before I have any idea what it is?
> 
> I am aware that there are a couple hairstyles in the codebase that already have this problem- let's not make it worse.

To be fair on the character generation screen (which is the most common use case) they are all displayed with an icon preview.
The issue is that the mirror should do that as well and doesn't, You shouldn't ever need to be picking your haircut via name.

**Pull request closed without merging**
