### PR TITLE
Reinforces Captain's and HoP's airlock wire panels

### PR DESCRIPTION
**Pull request by CoffeeDragon16**
## About The Pull Request

This adds plasteel reinforcements to all airlocks in the captain's office, save their bathroom, and plasteel for the HoP's front door and iron for their back.

## Why It's Good For The Game

This makes it take more time to hack into two high-risk areas, which discourages rounds where someone hacks into captain's office, releasing AA ten minutes into the shift. The actual difficulty is not majorly changed, just takes more time and equipment.

## Changelog
:cl:
balance: New models of Captain's and HoP's office airlocks are now reinforced.
/:cl:

### CODE REVIEW

**Comment by Fikou** [comment]
giving the hop the plasteel doors at all is really dumb and giving every single airlock in cap's plasteel is really dumb

**Comment by CoffeeDragon16** [comment]
Oh thats right, I could remove the reinforcement that goes between cap's office and bedroom so if you disposal in there's less of an equipment check, to encourage doing it COOL

**Comment by Fikou** [comment]
i was gonna say the opposite, captains office doesnt deserve to be locked, all of its cool items are locked behind windows and ittself it just has a table with donuts but captains quarters is the cool area

**Comment by Timberpoes** [comment]
See associated thread suggesting this kind of change in the context of Cap's office and armory: https://tgstation13.org/phpBB/viewtopic.php?f=9&t=27483

I am not supportive of this change.

There exist policies in place preventing re-inforcement of certain high security areas on shift start for a reason. The station is meant to have vulnerabilities to enable antagonistic behaviour overall.

There are future plans in place for ID Card changes that makes rushing the Cap's office roundstart for all access much less desirable. https://hackmd.io/@tgstation/HkS-z64NP - And oranges wishes for this to be a priority nearer the top of coder lists right now as he's requested someone pick up the slack and implement it.

While I appreciate where you're coming from, I don't feel this is the appropriate solution to the simplicity of obtaining and distributing all access on rounds where there is no Captain and no other heads secure the spare.

**Comment by optimumtact** [comment]
@Timberpoes the changes will make it more likely, not less, not sure how you came to that conclusion.

The spare and captain's id are much more valuable under the proposed change.

**Comment by Timberpoes** [comment]
> 
> 
> @Timberpoes the changes will make it more likely, not less, not sure how you came to that conclusion.
> 
> The spare and captain's id are much more valuable under the proposed change.

Apologies, I should have been clearer with what I was referencing!

The PR body itself explains its reasoning as "which discourages rounds where someone hacks into captain's office, releasing AA ten minutes into the shift"

I was focusing in on this aspect. Your plans for changes IDs directly hit the ability to air quotes "release" all access.

I was under the impression that this PR was more focused on tackling players ability to distribute all access 10 minutes into the shift, with making the Cap's spare harder to obtain being a part of that end goal. Although, reinforcing the HoP office is a lot less useful as anyone with an AA-capable card can just walk in, it does still go some way to help when the HoP leaves the console logged in though.

If I'm wrong on that front then I'm happy to stand corrected and will reassess my thoughts based on it.

**Comment by CoffeeDragon16** [comment]
Ah, I hadn't seen that thread, or had the design docs in mind. Is this a hard no on the PR? I can see how as it's a more influential balance PR, I just can't stand how easy it is to break into one of the highest-risk areas in the game. The captain and hop shouldn't have to watch over their offices like a hawk, or if they leave for 5 minutes AA is out, or an objective stolen, and it was taken with only 3 tools, one of which being public access and the others still being easy to acquire.

**Comment by Tlaltecuhtli** [comment]
>e. The captain and hop shouldn't have to watch over their offices like a hawk, or if they leave for 5 minutes AA is out

bro.... you log out of the consoles.... that makes aa not go out....

**Comment by Timberpoes** [comment]
> 
> 
> Ah, I hadn't seen that thread, or had the design docs in mind. Is this a hard no on the PR? I can see how as it's a more influential balance PR, I just can't stand how easy it is to break into one of the highest-risk areas in the game. The captain and hop shouldn't have to watch over their offices like a hawk, or if they leave for 5 minutes AA is out, or an objective stolen, and it was taken with only 3 tools, one of which being public access and the others still being easy to acquire. And yeah, you're accurate on the intents, its supposed to make it risker and take more time to acquire AA and other items in their offices.

It's not a hard no, per se.

I think my issue is conceptually - Why does the Captain's spare exist, why is it in the Captain's quarters and then still why is it locked in his own personal locker, which can only be accessed by a Captain-class ID card? The only time the Captain would want his spare, is if he had to break into his own office and break into his own locker to get it.

Technically, it's even more secure than the nuke disk that's just lying around on a desk.

It seems to me that one of the primary reasons it exists is simply to be stolen.

It's just as hard for any Head of Staff to access (barring the HoP) as it is for any random greytider to access, although perhaps a Head of Staff may be able to leverage the power of a nearby silicon to open doors, they still need to break into the Cap's locker unless that silicon is also a cyborg and can unlock it.

**Comment by CoffeeDragon16** [comment]
Hmm, could be interesting if it were in the vault, behind a command-level ID check, but I suppose the QM would just dip it in lava for free AA.

**Comment by Timberpoes** [comment]
> 
> 
> Hmm, could be interesting if it were in the vault, behind a command-level ID check, but I suppose the QM would just dip it in lava for free AA.

If I read between the lines, I think the issues you're trying to address are less related to all access and the captain's spare in general, and more to how exponential growth of all access can happen when the Captain's spare is let loose into the world. One person gets it and gives it to 2 people, who give it to 2 others each, who give it to 2 others each. In a very short time, everyone has all access and can obtain additional copies of all access from anyone else.

This is definitely an undesirable gameplay loop, but I'm not certain that "hide the captain's spare behind increasing layers of security" is TRULY the solution we're looking for in the context of your concerns. And they're valid concerns that I agree with. I just want to make sure the fixes are approached correctly.

In my eyes, this seems much more of a band-aid solution. It's not that AA is any harder to distribute, it's just getting that first AA card is a bit more of a pain in the ass to do.

In terms of what I can suggest in its place:
Instead of reinforcing the HoP office, I would not oppose a PR that logged you out of the ID consoles when you removed your ID card. Yes, this would prevent the HoP from modifying his own ID card's access permissions without creating a second burner card to do it. This is fine.

Similarly, I would be interested to see the discussion and arguments both for and against removing ID Console permissions from the Captain's spare. It would still operate as an all access card, but would have no ability to distribute all access on its own.

**Comment by Tharcoonvagh** [comment]
If you really want that AA you gotta work for it, _or you know, thermite exists _

**Comment by SkeletalElite** [comment]
@Timberpoes as the person who made the suggestion, It's less about stopping the spread of AA and more about slowing down how long it takes to steal the spare.
There's a reason we specifically have a policy that allows the captain to kill anyone who breaks into their office at or near shift start. It happens all the time. Ideally, this should at least give the captain a few more minutes before someone is capable of busting into their office.

Also the reason the spare exists is in case their is no HoP or Captain and another head needs to take up the mantle for one reason or another.

**Comment by Tharcoonvagh** [comment]
Also I usually just strip the spare of access and throw it out of my airlock

**Comment by Timberpoes** [comment]
People keep saying the spare exists for the sole purpose of other heads or the HoP, yet the HoP can give himself all access so he doesn't need it and for every other head its just as difficult to get for them as it is for greentiders without silicon intervention.

There is nothing about the spare that screams "this exists for when there's no captain around". The only people who can access it without breaking and entering, probably don't need it to begin with.

It's not in an area accessible by the other heads, nor stored in a container openable by other heads, nor does it despawn from the locker when a captain or HoP enters the shift.

I know I'm being pedantic but there's absolutely nothing about where that item is placed that indicates its purpose is for other heads to get it when no captain is around. Without a cyborg on the station to open it for them, the heads have to smash into the locker just like any tider.

I'm not saying you're wrong. There's every chance that you're right and when the spare was first added it was intended only for the other heads to access. But nothing about its placement from a game design perspective indicates that. And this band aid solution makes it just as hard for a head to secure without silicon intervention as it does a greytider without silicon intervention.

**Comment by 81Denton** [comment]
>This is definitely an undesirable gameplay loop, but I'm not certain that "hide the captain's spare behind increasing layers of security" is TRULY the solution we're looking for in the context of your concerns.

I fully agree with this. There are already enough layers to protect the spare like maint motion cams, the spare being inside a locker, r-walls and so on. This is just a band aid fix for what's essentially a policy issue when people any% speedrun the spare every round.

>Instead of reinforcing the HoP office, I would not oppose a PR that logged you out of the ID consoles when you removed your ID card.

Honestly, I'd be for keeping consoles as is, since it gives players the opportunity to fuck up and cause chaos through their own negligence. I'd rather see them punished (in-game by the captain ofc) instead of just making the console log out by default.

**Pull request closed without merging**
