### PR TITLE
Adds a way to filter BZ gas in air alarms and trinary filters

### PR DESCRIPTION
**Pull request by lzimann**
So now you don't have to rely on slow portable scrubbers.

I guess this is a feature PR, so fix token #18138.

:cl: Lzimann
:rscadd: You can now configure air alarms to filter BZ gas!
/:cl:

### CODE REVIEW

**Comment by lzimann** [comment]
conflicts fixed @ChangelingRain

**Comment by Jordie0608** [comment]
Looks like you messed something up with the tgui asset files, line endings perhaps?

**Comment by lzimann** [comment]
I had some conflicts in the file, maybe it messed up in the fixing process

**Comment by RemieRichards** [comment]
the tgui css isn't minified anymore.

**Pull request merged**
