### PR TITLE
Spear sprite fixes

### LINKED ISSUE #46036: Plasma Spears have no In-hand
Issue reported from  Round ID: 116520 (/tg/Station Sybil [ENGLISH] [US-WEST] [100% LAG FREE])

Reporting client version: 512.1471

Basically, they have no inhand sprites at all and don't even have a back sprite. They're completely invisible.

### PR DESCRIPTION
**Pull request by Twaticus**
## About The Pull Request

Adds missing plasma spear right inhands
Adds plasma spear back sprite
Fixes multiple spear inhands that were misaligned
Closes #46036 

dreamseeker_8qnBlXaxFp
plasma spear inhand

dreamseeker_sOZNbnTxqX
plasma spear on back

ddd
spear fixes before and after 

## Why It's Good For The Game

Invisible plasma spear bad

## Changelog
:cl:
fix: missing plasma spear inhand
imageadd: plasma spear back sprite
/:cl:

### CODE REVIEW

**Comment by mrhugo13** [comment]
>The  Icondiff bot failed instead of travis

Now that's a new one for me.

**Comment by nemvar** [comment]
icondiff has been failing for a while now. Has probably nothing to do with this PR in particular.

**Comment by Twaticus** [comment]
added pictures since the bot failed, even though its probably not necessary on this type of PR

**Review by ShizCalev — APPROVED** [review]

**Comment by ShizCalev** [comment]
if you want a few more to tackle, look at #30081

**Comment by WaterStBlues** [comment]
This is the best type of PR tbh. Altruistic and detail-focused in every sense. We must all appreciate.

**Pull request merged**
