### PR TITLE
Added Two New Moustache Styles on the Character Setup.

### PR DESCRIPTION
**Pull request by MetalClone**
## About The Pull Request

Adds two new moustache styles, The Handlebar and Handlebar...2!

Preview: 
Moustache

## Why It's Good For The Game

Adds more variety and flavor to character setup!

## Changelog
:cl: MetalClone
add: Added the handlebar moustache, available in the character setup
add: Added the handlebar moustache 2, available in the character setup 
imageadd: added both handlebar moustache icons
/:cl:

### CODE REVIEW

**Comment by JohnFulpWillard** [comment]
#60608

**Comment by EricZilla** [comment]
> #60608

Sprites arent frozen I dont think, you cant expect spriters to code dive and fix bugs

**Comment by tralezab** [comment]
Make old sprites better then, don't add new content during the freeze!!

**Comment by tralezab** [comment]
(that being said these look really good and should be considered once freeze is over again)

**Comment by Mothblocks** [comment]
feature freeze, touch up older sprites instead

**Comment by Mothblocks** [comment]
also arm is right if you pr these after freeze i would appreciate that they look funny

**Comment by thestubborn** [comment]
reopen the pr
stop...having it be closed

**Comment by MetalClone** [comment]
> 
> 
> reopen the pr
> stop...having it be closed

I would love to, but I have no ability to reopen it

**Comment by Mothblocks** [comment]
CC @Krysonism @Twaticus

**Review by Twaticus — APPROVED** [review]
epic

**Comment by Mothblocks** [comment]
oh i forgot to change the tag to content expansion oops

**Comment by MetalClone** [comment]
Thank you, I appreciate it

**Pull request merged**
