### PR TITLE
Remove taser firing delay

### PR DESCRIPTION
**Pull request by optimumtact**
Making the game unintuitive as fuck and annoying as shit is not a balance
change, I'm frankly quite suprised it was merged in the first place

In the future don't nerf the interface as a balance fix

### CODE REVIEW

**Comment by optimumtact** [comment]
Also I'll be honest, I think going away from stun based combat was a mistake, we got nowhere effectively, stuns still rule the game.

**Comment by Dorsisdwarf** [comment]
:+1: :-1: 

Not sure how I feel about this. Taserspam is universally crap.

**Comment by optimumtact** [comment]
If a security officer wants to blow his wad all over the fucking place then let him. Making the game hard through artificial interface difficulty is a cop out.

**Comment by Miauw62** [comment]
this really isnt "artificial interface difficulty".
how does this even compare to stuff like ai fast doorbolting?

**Comment by Actionb** [comment]
I like this. If you think you are entitled to win against somebody firing taser shots at you by rushing up to them instead of staying out of taser range, there's something wrong with you.

**Comment by Miauw62** [comment]
i dodged all his taser shots man, i didnt literally walk up to him, try getting better reading comprehension.

**Comment by Steelpoint** [comment]
The reason its easier to dodge taser shots is because its awkward to fire the taser. 

This is a good change imo, more quality of life.

@Miauw62  Prehaps buffing Nuke Ops energy defence might be worth a look, somewhere around 50 or even 75 so that stun times for them range from 5 to 2.5 seconds. Make stuns more of a thing that drops their guns and less of a ggnore.

Also off topic but I don't think we'll ever get a non-stun based combat system ever. Every proposed idea has either never worked or never come to fruition.

**Comment by Miauw62** [comment]
i wasnt an op, though, i was just a traitor that got an op suit in a surplus crate

**Comment by Steelpoint** [comment]
Oh, I thought the implication of your statement (Op suit) was that you were a operative.

If we ever do buff Op suits we really need to disallow Traitors from buying Nuke Op suits directly from their PDA.

**Comment by Dorsisdwarf** [comment]
Op suits are pretty fucking tough already, last I checked they had like 60 melee and laser armor. 

Also this isn't a QOL change, it's a balance change and a direct buff to security, Steelpoint

**Comment by Steelpoint** [comment]
I'm supporting this PR, I was just giving a suggestion on Nuke Op armour.

**Comment by KorPhaeron** [comment]
I agree about the stun thing. We're stuck in some awful middleground and we need to decide on one direction or another instead of leaving it sitting forever.

The person designing the new system is gone though and nobody else seems willing to do it.

**Comment by Nanotransistor** [comment]
If you do this, might as well do the same for the ebow and it's reload crap mechanism.

**Comment by Steelpoint** [comment]
The legacy of Paprika lives on.

**Comment by SconesC** [comment]
This is the change I have been waiting for.

Taserstorm is not an issue because we don't have long-ranged electrodes anymore. This is such a massive QoL for Security.

**Comment by PKPenguin321** [comment]
:+1: :+1: :+1: IIRC the last time we tried this *EVERYBODY WANTED IT* but then paprika ban evaded on the github and hurt everybody's feelings and it got closed

**Comment by Supermichael777** [comment]
pew pew tazers

**Comment by optimumtact** [comment]
Ebow I'm not going to touch since it has infinite ammo, reducing any cooldown on that would make it sooper strong without other nerfs that I don't have time to implement

**Comment by optimumtact** [comment]
BTW DNM I still need to test this

**Comment by Fox-McCloud** [comment]
Not a fan of this; it just promotes chain-stunning multiple people with ease, at range.

Getting attacked by 5 attackers at once? No problem; just pew pew and down them all, no questions asked.

Yes, I realize flashbangs have a similar impact, but they need to be primed and tossed, where as a taser is literally pew pew.

:-1:  While @paprika was a bit of a grump at times, these were very positive changes that added in more interesting counterplay.

**Comment by SconesC** [comment]
I don't think you play sec if you honestly think that

It impedes accuracy beyond all else and it's fucking easy to just outrange the taser

**Comment by Falamazeer** [comment]
Thank you, you beautiful citrus fruit you.

**Comment by Nanotransistor** [comment]
@optimumtact Old ebows had 5 oe 6 shots, after that you had to wait a minute or two to recharge, in that regard  they were as infinite as tasers.


Otherwise i agree with the change. I'm not a fan of the currently delayed taser shots.

**Comment by optimumtact** [comment]
Ah interesting, I had no idea it was that powerful

**Comment by SconesC** [comment]
So we're past 24 hours and there's been overwhelming amounts of support for this

**Comment by optimumtact** [comment]
Patience

**Comment by Miauw62** [comment]
vOv

**Pull request merged**
