### PR TITLE
Removes duplicate typecaches

### PR DESCRIPTION
**Pull request by Cyberboss**
Requires #31882

Best reviewed as two commits.

The first commit is just making some typecaches which should be static static.

The second is a change to the proc

Added GLOB.typecaches_created as a performance metric
Added GLOB.master_typecache

All typecaches on only one type will go in this list (keyed by the type). Further calls to typecacheof for that type will return the cached version. Every time that happens, the "request_count" key is incremented. I'm interested to see if this is a performance boost and which typecaches are being created excessively

### CODE REVIEW

**Comment by Iamgoofball** [comment]
profile this with tesla tbh

**Comment by optimumtact** [comment]
I was joking when I suggested this in irc but it might just work

**Comment by optimumtact** [comment]
What is the idle memory usage after this change @Cyberboss ?

TG currently idles at about 900MB ~ 1GB for me

**Comment by RemieRichards** [comment]
This won't be worth it, besides fixing the non-static ones.
If a typecache can be static, it's optimum state is being static.
If it can't be static, it gains nothing from this since if it can't be static it must be modifiable per instance, which means it can't use this `global cache"

**Comment by duncathan** [comment]
What about those which very rarely need to change? If the unchanged typecache is the average case, then surely this improves memory use in the average case.

**Comment by MrStonedOne** [comment]
The big question is, does anything change the list after getting a typecache?

If it does, this could spell trouble because those changes would make it into the globalcache.

if not, a typecache cache should be used for all typecaches. if its multiple types are requested, it should | together the typecaches for each type.

**Comment by RemieRichards** [comment]
@duncathan then you still have to copy it, and if it changed once there's the possibility it will do so again in the future, meaning you're only caching it for a relatively short period of time, you won't gain much.

If it's some known state where it changes, then you can have them use a shared cache up until that point, at which point they all switch to individual copies, but then you still have copy overhead and even so doing that would be better done on the type regardless, no need for global there.

I actually missed another case, which is where one typecache is kept between multiple types, but that should just be its own global (eg: ```GLOB.living_typecache```), no gain to being indirectly global in some cache-cache.

@MrStonedOne yes, some hostile mobs do it and so do bees (anytime you want a hostile mob to "selectively" target something really), which is why cyberboss had to add the "copy pls" argument to typecacheof.

It's much better to handle this specifically on each case, rather than fudge some global cache-cache with no real benefit.

**Comment by Cyberboss** [comment]
I checked each of the ~200 uses. Nothing modifies typecaches

**Comment by ShizCalev** [comment]
@Cyberboss compile failed.

**Pull request merged**
