### PR TITLE
New sprite for the chemmaster to fit the updated chem dispenser.

### PR DESCRIPTION
**Pull request by yorii**
:cl: yorii
imageadd: added a brand new sprite for the chemmaster!
/:cl:

gif3

### CODE REVIEW

**Comment by yorii** [comment]
Over 9000 hours in mspaint

**Comment by yorii** [comment]
test2

Not sure this upload will work..

**Comment by Bawhoppen** [comment]
@WJohn

**Comment by yorii** [comment]
I think I have to start from scratch on this because the stupid condimaster in the kitchen uses the same sprite.

**Comment by MrDoomBringer** [comment]
@yorii It looks like a good start, but I'm not sure what shape you're going for with the piston-moving-press thing. Is it cylindrical? I'd also suggest using fewer colors on the cylinder. Its best to avoid gradients as much as possible, and the sprite looks good on that front save for the cylinder thing. It also might be a good idea to better define where the underside of the piston thing is, as right now, underneath the piston looks like a flat vertical surface (which Im assuming is not the intention).

**Comment by MrDoomBringer** [comment]
@yorii also the PANDEMIC i think

**Comment by yorii** [comment]
I'll figure something out, just don't merge this yet unless you want a big fancy pill press in the kitchen.

**Comment by yorii** [comment]
>@yorii It looks like a good start, but I'm not sure what shape you're going for with the piston-moving-press thing. Is it cylindrical? I'd also suggest using fewer colors on the cylinder. Its best to avoid gradients as much as possible, and the sprite looks good on that front save for the cylinder thing.
It also might be a good idea to better define where the underside of the piston thing is, as right now, underneath the piston looks like a flat vertical surface (which Im assuming is not the intention).

Hmm you're right, I'll fix it up to be more of a flat piston with rounded edges.

**Comment by MrDoomBringer** [comment]
@yorii for sick verticle-moving cylinders, check out [the smoke machine](https://github.com/tgstation/tgstation/pull/33344) maybe? <sup>shameless   plug</sup>

**Comment by yorii** [comment]
I made it more like a smooth polished aluminium rectangle with rounded corners

test3

I'm putting these in as separate sprites and doing some codework to leave the current pandemic and condiment machines untouched.

**Comment by yorii** [comment]
Allright, that should do it, tested it and it seems to be working as intended. But my ugly code probably needs a review.

**Comment by WJohn** [comment]
Yeah I have really no idea what is going on on the left side. I can tell it's some sort of pill injection line of some kind but it's got this huge spot above it whose shape I can't even discern.

**Comment by ExcessiveUseOfCobblestone** [comment]
can we discuss that flagrant memery of `condi`?

The subtype exists, why would you not abuse procs instead of have a var on the original reeeeeeeeeeeeeeeeeeeeee

**Review by WJohn — CHANGES_REQUESTED** [review]
This frankly looks too similar to the chem dispenser. I know it's supposed to mimic the same style but they're really far too close (although I'm also really not all that happy about the chem dispenser either).

**Comment by Buggy123** [comment]
The chem dispenser went from simple, good looking, and distinctive to some arbitrary button-y piece of high-tech garbage that only stands out because its one of the _only_ things that look like that.

And now you want to replace the chemmaster with a equally shitty sprite, so we have two terrible looking machines, and no one can tell them apart because their only defining characteristic is how ungodly awful they both look.

1f44e

**Comment by zamolxius** [comment]
looks like shit

**Comment by yorii** [comment]
>The subtype exists, why would you not abuse procs instead of have a var on the original reeeeeeeeeeeeeeeeeeeeee

Pure laziness really.

**Comment by yorii** [comment]
>looks like shit
fuck off hippieplayer

**Comment by yorii** [comment]
How about I flatten the piston out some more, put the medbay logo on it, add a hatch with a medpatch logo to the front and make the graph animation not look like shit?

**Comment by yorii** [comment]
image

How's this?

**Comment by GuyonBroadway** [comment]
Ewwww, that pillow shading on the piston-thing rustles my jimmies.

**Comment by yorii** [comment]
I think I just made it look worse now, does anyone want to take over this PR? Or just rebuild the top and send me what you made, I'm satisfied with the right half of the machine now and the animation is pretty decent, but the piston bit is just getting worse and worse, please send help.

gif3

**Comment by ShizCalev** [comment]
conflict.

**Comment by yorii** [comment]
I see, yes. I'll deal with it tomorrow, bit busy and don't feel to well to be dealing with sprite copy-pasting right now. (Migraine inducing work)

**Comment by chaoko99** [comment]
Medicine ATM

**Pull request closed without merging**
