### PR TITLE
Flagellant Robes Changes

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request
title
changes the speed value of flagrobes from -1 to -0.6
reduces received damage by 5
making this a separate pr from #42608

## Why It's Good For The Game
Basically as it is right now, wearing flagrobes allows you to zoom along into people(s) screens and click them within a mere second or so before they could even react or know about you coming.

While they do make the user take more damage as their drawback and a single laser or so changes their health condition, I felt like this was a needed thing considering our movespeed changes on server config as of late, they're way too fast at the moment.

## Changelog
:cl: SuicidalPickles
balance: Flagellant Robes have had their speed reduced from -1 to -0.6, in return for tuning the extra received damage down by 5.
/:cl:

### CODE REVIEW

**Comment by Shadowflame909** [comment]
I think going from -1. to -0.25 while keeping all of that extra damage stack is too hard of a nerf

**Comment by wesoda25** [comment]
Did you even bother testing it. -0.25 means its slow as fucking shit and a complete waste of, well everything. For comparison, nuka cola is currently at -0.75, which seems way, WAY slower than what it formally was (-1). Drop this to like -.9 or something, anything else is absolutely ridiculous. You take double damage with it, after all.

**Comment by Angustmeta** [comment]
I posted this in another PR and I think it's relevant to this discussion:
[1.5 run delay and -0.75 multiplicative slowdown](https://gfycat.com/pertinentsmallfeline)
[1.5 run delay and -0.85 multiplicative slowdown](https://gfycat.com/carefreeimperturbabledingo)
[1.5 run delay and -1.0 multiplicative slowdown](https://gfycat.com/remorsefulpastelatlanticspadefish)

**Comment by Shadowflame909** [comment]
Honestly from what I'm seeing. The speed nerf wouldn't make Flagellant Robes a good gimmick at all, and it'd essentially be the armored hardsuit of cult, like it is to war-ops.

**Comment by wesoda25** [comment]
-0.25 will be a hardly noticeable speed difference, combat wise. All this does is make it easier for you to die, because of the amplified damage. 

If you turn this to -0.25 literally rework everything else based off speed because this will never be used in favor of others.

**Comment by ExcessiveUseOfCobblestone** [comment]
> speeds using hard numbers

gah!

**Comment by Suicidalpickles** [comment]
alright after giving it a second go, i'll bump this to -0.6 yeah, plus reduce the damage taken on everything by 5.

https://streamable.com/14bag (-0.25)
https://streamable.com/2xeh6 (-0.6)

**Comment by wesoda25** [comment]
Reeeee it should give positive armor then since its now outlcassed by nuka cola alone

**Comment by Hathkar** [comment]
> 
> 
> Reeeee it should give positive armor then since its now outlcassed by nuka cola alone

Not for long. I plan on doing other movespeed change PRs once my speed potion goes through.

**Comment by ExcessiveUseOfCobblestone** [comment]
not everyone gulps nuka cola though so you'd still be better off most of the time.

**Pull request merged**
