### PR TITLE
Removes SSreligion

### PR DESCRIPTION
**Pull request by AffectedArc07**
## About The Pull Request
This removes SSreligion. Subsystems are meant (MSO correct me if I am wrong) for things that need to happen on server initialize, or for loops happening in the round. Considering this is just a var container, for a whopping 7 vars, they should just be globals instead, as using a subsystem for this is a waste.

## Why It's Good For The Game
As said before, subsystems are for things that happen on initialize or need to periodically trigger. This subsystem was just a var container and has literally no reason to exist

## Changelog
:cl:
tweak: Religion is now a globalvar instead of being a subsystem for some reason
/:cl:

### CODE REVIEW

**Comment by Barhandar** [comment]
Religion usurping code ghosts smh

**Comment by MrPerson** [comment]
Before we had global vars stored, the idea was to use a SS to store global vars so they could be VV'd and tracked.

**Comment by optimumtact** [comment]
in what possible use of the word waste, is it actually a waste?

**Comment by AffectedArc07** [comment]
@optimumtact 
- Waste of space on the MC tab (A whole line)
- Waste of space on the filesystem (A whopping 77 characters)
- Waste of uhhhhhhhh

Look its a bad word to use, but I am going to ask for the other side of the argument because I cant argue points.

Please defend this, peaches

**Comment by optimumtact** [comment]
GO ON A LIVE SERVER AND TRY TO VV THE GLOBAL GLOB DATUM AND THEN COME BACK AND BE A SMART ASS ON THE GITHUB

**Comment by AffectedArc07** [comment]
ARE YOU SAYING WE NEED EVERY GLOB TO BE ITS OWN SUBSYSTEM

**Comment by optimumtact** [comment]
NO BUT I'D RATHER SOMEONE BREAK IT UP LOGICALLY SOMEHOW BECAUSE IT'S GETTING HARDER AND HARDER TO ACTUALLY DEBUG THE GLOBAL LIST

**Comment by AffectedArc07** [comment]
THEN IMPROVE THE DEBUGGER

**Comment by optimumtact** [comment]
IT'S NOT THE DEBUGGERS FAULT THE GLOB HAS AROUND 10,000 ITEMS ON IT

**Comment by optimumtact** [comment]
THE DEBUGGER IS DOING HER BEST

**Comment by optimumtact** [comment]
SHES TRYING REALLY HARD AFFECTED

**Comment by AffectedArc07** [comment]
WELL HER BEST ISNT GOOD ENOUGH

**Comment by optimumtact** [comment]
APOLOGISE TO HER AT ONCE, LOOK AT WHAT YOU HAVE DONE

crying sad anime girl

**Comment by AffectedArc07** [comment]
*headpats the global var controller*

**Comment by AffectedArc07** [comment]
Also you ever heard of CTRL and F, and pushing them together at the same time, then typing for the var you want

**Comment by optimumtact** [comment]
It's more about the time it takes to open the thing in VV.

**Comment by AffectedArc07** [comment]
Does it really take that long?

**Comment by optimumtact** [comment]
I just tested and honestly no, it's not as bad as I thought

**Comment by AffectedArc07** [comment]
image

**Comment by SpaceManiac** [comment]
you're welcome

**Pull request merged**
