### PR TITLE
Uses optipng to compress dmi's and save a whole 8 MB.

### PR DESCRIPTION
**Pull request by nemvar**
## About The Pull Request

Compresses all .dmi's using optipng. The process is lossless.

## Why It's Good For The Game

Before compression: 34,540,253 Bytes used
After compression: 26,373,091 Bytes used

We are saving 8 MB, it's free memory.

Why this is a draft: I still need to write a readme for how to use this (spoiler alert, just run the script), but more importantly, I want this to run off a git hook.

EDIT: Reminder to self, currently does not compress png, only dmi. Pls fix.

## Changelog
:cl:
imagedel: Compressed all .dmi files.
/:cl:

### CODE REVIEW

**Comment by ArcaneMusic** [comment]
Ho Hooo, can we get a rough guesstimate how much data this'll save per month on the server?

**Comment by LemonInTheDark** [comment]
Absolutely based, now I can add more random wine

**Comment by cacogen** [comment]
now we can add two 320kbps linkin park songs

**Comment by PKPenguin321** [comment]
>Ho Hooo, can we get a rough guesstimate how much data this'll save per month on the server?

Completely off the top of my head math, if you suppose we get around 200~? unique connections a day that need to download the cache then that's 48 GB a month

**Comment by optimumtact** [comment]
we do cache the RSC in a cdn but this will help for the misses.

**Comment by ShizCalev** [comment]
conflict

**Comment by LemonInTheDark** [comment]
dark days

**Comment by TemporalOroboros** [comment]
Welp, this hope has died... for now.

**Pull request closed without merging**
