### PR TITLE
Unlocks AI Multicamera Mode, now with config.

### PR DESCRIPTION
**Pull request by Potato-Masher**
:cl: Potato Masher
tweak: CentCom would like to announce that new station AIs will now support updated surveillance software, allowing units to monitor multiple locations with ease with customizable viewing range, albeit at an overall reduced viewing radius.
config: Cruix's AI Multicamera mode has been finally enabled, with a new config option for enabling and disabling it as well!
/:cl:

If you somehow have missed this feature's addition a while back, check here for details and original discussion: #37695
Earlier attempt that inspired this PR: #40153 

---

>firefox_2018-09-09_23-52-58

This probably should have been a config in the first place. Oh well.
Return of the AI Multicamera Mode, this time with requested config toggle.

First time messing with config shenanigans, let's see if I'm not retarded.

### CODE REVIEW

**Comment by CosmicScientist** [comment]
inb4 anti-sillycone brigade

**Comment by CosmicScientist** [comment]
Well I think this is overpowered and all silicon roles should be removed because I salt hard over not learning how to defeat a role that confronts me in 3% of my games!

**Comment by CosmicScientist** [comment]
>Well I think this is overpowered and all silicon roles should be removed because I salt hard over not learning how to defeat a role that confronts me in 3% of my games!

You're wrong because everyone has access to hard counters and no-one has fixed the EMP spot for the autismsatellitefortress. I can't play for 5 seconds without being EMPed, power cut, tesla'd, subverted, killed by a rogue borg, blinded on all of my cameras and carded for laws to be checked only to be erased and told in an a help ic issue!

**Comment by CosmicScientist** [comment]
>You're wrong

I hate you! You play hunt valid role!

**Comment by CosmicScientist** [comment]
>You play hunt valid role!

No u! Don't remove features because other players abuse them to be cancer! I need to be Isaac Asimov!

**Comment by CosmicScientist** [comment]
There I had all the arguments so everyone else can't.

Was the admemeistration going to have this enabled like the default value in this PR?

**Comment by Potato-Masher** [comment]
Thank you for summarizing the comments before they were added @CosmicScientist .

**Comment by Cruix** [comment]
Considering the fact that Oranges immediately closed the PR that he thought enabled the config, it is doubtful that he will allow this to pass as long as the config is enabled.

**Comment by ExcessiveUseOfCobblestone** [comment]
@Cruix He thought you were trying to backseat headmin, calm down.

**Review by Cyberboss — APPROVED** [review]

**Pull request merged**
