### PR TITLE
Make objects being dragged immune to pressure differentials (space wind)

### PR DESCRIPTION
**Pull request by MrPerson**
While not a solution to space wind being shit, this is just a good change that should have been done anyway to make dragging dead/dying people back onto the station from a hull breach less annoying. Also closets and other dense shit are still annoying because the wind pushes you into the closet, which pushes it backwards and out of your grasp, which is annoying and stupid, but there's no really good way to fix that right now.

### CODE REVIEW

**Comment by bgobandit** [comment]
THANK YOU BASED GOD

**Comment by Cebasiz** [comment]
i think this is a good solution, that way the majority of the new deadlier spacewind can be kept while toning down how annoying it is.

have cake, eat too

**Comment by Jalleo** [comment]
Can you do the same with people please.

**Comment by SconesC** [comment]
Does this include mobs?

PLEASE make it include mobs.

**Comment by Cebasiz** [comment]
>this is just a good change that should have been done anyway to make dragging dead/dying people back onto the station from a hull breach less annoying. 

this sentence indicates to me that it includes everything could be wrong

**Comment by Aloraydrel** [comment]
Oh lord yes please

**Comment by MrPerson** [comment]
It's on atom/movable. That means everything that moves.

**Comment by PKPenguin321** [comment]
so if two people pulled each other they could walk down hallways of raging hellfire unscathed

sounds neat :+1:

**Comment by Jalleo** [comment]
Conga line with only one person who is at risk i like it!!!!!!

**Comment by xxalpha** [comment]
:+1:

**Comment by daman997** [comment]
i love you :+1:

**Comment by Fox-McCloud** [comment]
:+1:

**Comment by optimumtact** [comment]
Fix dense

**Pull request merged**
