### PR TITLE
Makes drones more realistic

### PR DESCRIPTION
**Pull request by optimumtact**
09:26 < coiax> anyway, before drones got dufflebags
09:26 < coiax> I'd always go to the captain's room
09:26 < coiax> and take the hat and dufflebag
09:26 < coiax> and then lock the locker again

### CODE REVIEW

**Comment by Bawhoppen** [comment]
this is going to be really annoying for drones :neutral_face:

**Comment by phil235** [comment]
No, the drone needs the access to do maintenance tasks.

**Comment by optimumtact** [comment]
They'll live

**Comment by coiax** [comment]
> this is going to be really annoying for drones :neutral_face:

you have correctly stated the intent of this PR

**Comment by KorPhaeron** [comment]
Someone deleted the meme pr tag and rather than spending 2 seconds to recreate it I gave you the next best thing

**Comment by Bawhoppen** [comment]
@optimumtact more like :question:x:100:

**Comment by optimumtact** [comment]
I dislike you characterising my fair and necessary nerf to the new greytide as a meme

bad

**Comment by coiax** [comment]
@KorPhaeron what do you mean someone removed the Meme PR tag

**Comment by Incoming5643** [comment]
Good, they have ventcrawling they don't need access anyway, and now I have a way to keep the fuckers out of my room.

**Comment by RandomMarine** [comment]
New meta, steal HoP's id when he's not looking to make all access ids among drones.

**Comment by TheNightingale** [comment]
If a drone steals something they shouldn't, ask for it back and they can't refuse. Simple.

**Comment by Zilenan91** [comment]
>gimping the already most gimped ghost role in the game

For what purpose

**Comment by PKPenguin321** [comment]
>If a drone steals something they shouldn't, ask for it back and they can't refuse. Simple.

more like they have to run screaming because no interaction allowed

**Comment by PKPenguin321** [comment]
>meme pr tag is a nasty black on yellow color

fix this heresy

**Pull request closed without merging**
