### PR TITLE
Freddy's Pizzeria Virtual Domain

### PR DESCRIPTION
**Pull request by munchyi**
## About The Pull Request

This PR adds a new virtual domain for bitrunners! The new domain includes the belowed pizzeria from FNAF and some bears (scary and strong). 
## Why It's Good For The Game
So there hasn't been any virtual domains being added and it can get boring playing the same domains over and over again. In my own opinion we need more maps or some of them changing with new ones! I also thinks its a funny idea to have such a domain and people will enjoy it. 
## Changelog
:cl:
add: added a new virtual domain
:cl:
image

### CODE REVIEW

**Comment by GremlinSeeker** [comment]
holy cwap fedy fastbare in ss13!!!

**Comment by munchyi** [comment]
Uhh can someone help me with fixing the last failing check I really dont understand what am I supposed to do

**Comment by MrMelbert** [comment]
why's there 4 noerp posters in sequence

**Comment by IndieanaJones** [comment]
Ummm, based??

**Comment by Admiral-Gigaton** [comment]
Damn I thought this was gunna be a fun gimmick one, With a timer attached to wait out and get the loot, not just bears

Still good

**Comment by Singul0** [comment]
They sell alcohol in freddy fazbwar?

**Comment by Loafin34** [comment]
the butterbear LMAO

**Comment by munchyi** [comment]
> Damn I thought this was gunna be a fun gimmick one, With a timer attached to wait out and get the loot, not just bears
> 
> Still good

sorry i dont know how to code downloaded map maker to do this :(

**Comment by EricZilla** [comment]
Need a springlocked modsuit wearing ghost spawn so bad here

**Comment by munchyi** [comment]
> They sell alcohol in freddy fazbwar?

its alcohol bottles filled with sparkling water trust

**Comment by nianjiilical** [comment]
> why's there 4 noerp posters in sequence

have you seen what theyve done to the chicken

also maybe give it a slightly less on the nose name like Fredrick's Pizzorium or something

**Comment by totalglyphiddeath** [comment]
har har har ha ha harh har har har har hah rah rhar har har har har

**Comment by CCC23** [comment]
Fredrick fazbearinttons pizarea? Establidhment?

**Comment by Elli-Skala** [comment]
SmartSelect_20240607_041243_Chrome
Vendoor

**Comment by projectkepler-ru** [comment]
what the fuck

**Comment by vendingmachine24** [comment]
> what the fuck

whats wrong?

**Comment by projectkepler-ru** [comment]
> whats wrong?

I'm scared

**Comment by vendingmachine24** [comment]
> I'm scared

you should be

**Review by Maurukas — APPROVED** [review]

**Pull request merged**
