### PR TITLE
Foam no longer spreads to transit space turfs.

### PR DESCRIPTION
**Pull request by harmonyn**
Fixes https://github.com/tgstation/tgstation/issues/22666.

if there's anywhere else foam/metal foam should not be spreading to let me know so I can add it to the blacklist

### CODE REVIEW

**Comment by Supermichael777** [comment]
lava?

**Comment by Supermichael777** [comment]
chasms

**Comment by Mervill** [comment]
I was just sizing up this bug too ... Good Work!

**Comment by bgobandit** [comment]
- would lava consume the metal foam?

- idk the thought of metal foam filling a chasm is fucking hilarious to me for some reason

**Comment by Mervill** [comment]
Does metal foam "fill in" chasms or make lava tiles traverse-able? If they don't, then I don't see why metal foam should propagate to those tiles.

If metal foam blocked a chasm, you could accidentally fall into it while removing metal foam, which is an extreamily shitty way to die.

**Comment by Cheridan** [comment]
While you're blacklisting things, kudzu probably shouldn't expand onto lava!

**Comment by bgobandit** [comment]
kudzu shouldn't expand onto anything tbh

**Comment by Kromgar** [comment]
Kudzu is stronger than lava it is the most invasive plant in existence it grows into freaking rock walls and plas steel walls

**Pull request merged**
