### PR TITLE
Increase gas_mixture/react() performance by around 10%

### PR DESCRIPTION
**Pull request by vuonojenmustaturska**
This is cherrypicked from a WIP branch since that needs more work and might not materialize

:cl: Naksu
code: gas reactions no longer copy a list needlessly
/:cl:

image

### CODE REVIEW

**Review by Cyberboss — APPROVED** [review]

**Comment by yoyobatty** [comment]
How does this compare after say, plasma flooding or causing breaks in the stations hull which create a ton of active turfs?

**Comment by vuonojenmustaturska** [comment]
it'll be the same speedup in that case... i wonder if istext is faster, though

**Comment by StarSmasher44** [comment]
So what is the thing with .Copy() then? Is it slower or is it another weird internal quirk of BYOND? could you explain it?

**Comment by Cyberboss** [comment]
It's copying the entire list to avoid iterating two values

**Comment by vuonojenmustaturska** [comment]
it makes a copy and then removes the two keys from the copy to make the loop cleaner, but it turns out to be slower

**Pull request merged**
