### PR TITLE
Enables space exploration on the North Star

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request

Enables space exploration when on the North Star

## Performance Testing

Testing was done with a very high ruin budget which may be higher than on TG's servers. This spawned about 32 Distant Signals, and possibly maps without a GPS beacon.

image

Performance was examined a few minutes after the round start, and then in 30 minute increments:
image
image
image
image
image

The presence of levels for space exploration does not appear to perceptibly impact performance.

## Why It's Good For The Game

Space exploration may be seen as a pretty minor part of the game to many, but I feel it's an important one for both mechanical and flavor reasons:

Having space exploration allows creators to contribute in a way that's smaller than developing a full-fledged station, but that is still meaningful. It allows lore writers to tangibly include lore in game, rather than being relegated to a wiki or similar. It allows dramas to play out in game, as people might struggle to survive - and perhaps fail - and some might attempt a rescue. It provides spawners that can be great for learning things like improvised engineering and medical, in addition to giving ghosts a way to reenter the round. It gives curators reason to use their beacon and things to put on display. It gives space rods a chance to not loop - and generally adds a sense of vastness missing when someone jumping into the void merely loops back.

It is true that it is not mandatory content, but using this argument, one could cut out nearly anything; there's very little that the game truly couldn't get by without if it were gone.

But I do think the game is better with this content than without. It is more fun with than without.

## Changelog

:cl:
config: Enables space exploration on the North Star
/:cl:

### CODE REVIEW

**Comment by optimumtact** [comment]
This map has been live for less than a day, you don't get to make changes to the design that chesify has made

**Comment by Jolly-66** [comment]
> The presence of levels for space exploration does not appear to perceptibly impact performance.

Unless you stress-tested this locally (there's ways to do this), there's no real way to garner how this'll work on live.
But that's besides the point if Chesh decided to go against this overall.

**Comment by Cheshify** [comment]
Yeah so a few things:
1. The focus on the map should ALWAYS be on the ship, space ruins don't really mesh with that design.
2. Space ruins don't WORK on the north star with a limited number of space Z-levels, they spawn like 50 of them all in one tiny lil area. I don't want 7 z levels of ruins, and I don't want 2 z levels of shitloads of ruins. I would accept it if there was a fix to limit how many spawn in space to be reasonable, but until then, this was deliberate.

**Comment by YehnBeep** [comment]
> Unless you stress-tested this locally (there's ways to do this), there's no real way to garner how this'll work on live. 

If someone could tell me how to do this, and this were required for acceptance, I would be willing to undergo the testing procedures. But there's not really an answer to "You're not allowed to change this." Though I suppose this could at least serve to show the many in-game commentators that it's not quite so simple as "WYCI" and "When it's merged you can make changes" and so on...

**Comment by Cheshify** [comment]
What happened was, I didn't want ruin z-levels enabled, thought to myself "well that's not very fair for space explorers". So I settled on 2 z levels, which I thought could be a fun distraction but not draw too much focus away from the ship.

Well, when testmerges started, it didn't work like I expected, and the 2 z levels were way overpacked with ruins, encouraging people to leave the station to get loads of space loot without searching or travel.

I didn't like that, so I settled on my original intent of just disabling them.

If something happens to fix how ruins generate so it's not overcrowded, I'll be happy to keep one or two levels in until the North Star gets some other cool mechanic for actually being a ship.

**Comment by YehnBeep** [comment]
I understand it is intentional, but in in-round OOC discussions, I saw some express performances concerns, which is why I wanted to test.

As far as ideological differences go... I don't have the knowledge and skill to develop customized systems. I've made the best argument I can in the first post; I feel it is much better for the game that this content be present than absent. If that is insufficient, then... I suppose that's that.

**Comment by Cheshify** [comment]
I don't want broken, ugly content on my map. Space ruins have always been side content, and if they're on the north star I want them sparse as to keep focus on the map itself, not all jammed into two z-levels.

**Comment by YehnBeep** [comment]
In the proposed change, the ruins are spread out. Should be moreso than on the test, since I imagine the live servers don't have an excessive ruin budget.

**Comment by Cheshify** [comment]
> In the proposed change, the ruins are spread out. Should be moreso than on the test, since I imagine the live servers don't have an excessive ruin budget.

I don't want 7 levels of ruins though. I don't really want any ruins, I feel like 2 z levels of sparse ruins is more than enough.

**Comment by Cheshify** [comment]
Again, the perfect world isn't "North Star has space ruins" it's "North Star has randomized maint"

**Comment by Cheshify** [comment]
Sorry, a lot of messages but I have a lot of thoughts on this. I don't really want space ruins as they are on the map because I think focusing in on the ship (which is MASSIVE) should take priority. I would be comfortable with 2 z levels of sparse ruins as a compromise if I was forced to have them, but ideally I would have no space ruins.

**Comment by BlueMemesauce** [comment]
The focus is still on the station on every other map that has ruins. I don't see how this map is so different.

If the map is generating too many ruin z levels, then that's a bug and should be fixed.

**Comment by Cheshify** [comment]
> The focus is still on the station on every other map that has ruins. I don't see how this map is so different.

That's the __issue__. I'm not trying to do the same thing, I'm trying to do something different. I want a heavier focus on the station than is present.

> And what's wrong with having the default 7 z levels of ruins? It works fine on every other map?

Because I don't want 7 z levels full of ruins.

**Comment by ZephyrTFA** [comment]
The map designer has clearly stated that the current state is intentional. If you get their approval, or a maptainer, this can be reopened.

**Comment by nukularpower** [comment]
Misguided decision on my opinion, but its not my map.  Just went from my favorite vote to least favorite.  I do not agree that the 2-3 people that go into space draw the "focus" away from the station.   :/   oh well

**Comment by dessysalta** [comment]
> Anyways, in short, strongly disagree that the 2-3 people that go into space draw the "focus" away from the station.

I think the argument is less "a few people eff off into space" and more so "the map is an extremely large map designed for player interaction, and having people metagame space ruins and get tons of loot defeats the purpose of the already emphasized roleplay station". People like to fuck off and do whatever it is they want anyways, in the context of the North Star I don't think it needs any more reasons for ~~those greytiding little shits to break immersion~~ people to ignore the emphasis it puts on development and interaction.

**Comment by BlueMemesauce** [comment]
But why "in the context of the north star", that is what I dont understand. What is it specifically about the north star that you can't have anyone leaving to go space exploring?

Seems to me like space exploration affects roleplay on all maps equally. The decision to disable it on this map feels really arbitrary, and in my opinion it feels like the map creator is just doing it because he has a personal connection to the map so 'wants the focus to be on it'

**Comment by optimumtact** [comment]
it's irrelevant what it seems like to you, map creators have creative control over their map as long as they are engaged and working on it.

**Pull request closed without merging**
