### PR TITLE
SM now uses the turbine to generate power

### PR DESCRIPTION
**Pull request by Ghilker**
## About The Pull Request
Change the supermatter to produce power with turbines instead of the zaps and coils. Increased the amount of gas and energy released from the crystal and rebalanced some turbine values.
Added the hypermatter state, where gas and heat generation is greatly increased, heat from damage is ignored and the sm releases an enormous amount of zaps that provides plenty amount of power. This state is achieved by feeding plasma coated metallic hydrogen sheets to the crystal, these sheets are made by putting metallic hydrogen in a chamber with plasma at over 2000 degrees. Each sheet will increase the time the hypermatter state will be maintained by 30 seconds.

image
Metastation
image

For the concerned players: using stock setup you can be expected to produce around 800 kW - 1 MW of power, and have an output of 600 kW for the initial SMES setup without upgrades. The initial setup will likely last around 40 minutes on high pop with high machine use and build.

The setup will not change (usual turn on pumps and filters, set scrubbers to succ, vent to 0, add n2, turn on emitters) there is only 2 more buttons to press, the turbine ON in the computer and the incinerator igniter ON. The basic complexity (if we want to call it this way) just rose to 2 more button presses.

To do:
- [ ] change all 5 maps
- [ ] add a delamination event for the hypermatter

## Why It's Good For The Game
Improve the power generation control by having one more step between the crystal and the SMES, this will help balance better the production for coders and players too, since they have one more point of upgrade and increases the amount of interactions that the SM  and the metal hydrogen can have.

This also follows the intended path for power generation going towards the Supermatter-turbine end goal. It's still not a final PR and there will be more needed for balance and checks. 

My end goal is to make the SM a fully customizable engine that is able to provide power in many ways that players can use. Yes is all atmos still, because the SM is an atmos engine first and foremost, BUT there will be ways to generate power from the SM WITHOUT the need of atmos gases, it just take time to do.

There is a rough draft of my idea for the heat based engine [Here](https://hackmd.io/HeypdIl9S52ik4zfHUgDpg?view) that is far from finished but is has the concept of what i'm doing there.

## Changelog

:cl:
add: SM power generation is now provided by turbines burning the gases coming from the crystal
add: new state of the SM called hypermatter, the crystal turns blue and shoot tesla zaps that can be harvested for power, this state will produce much more gases and heat but will ignore any damage coming from high temperatures. Is achieved by feeding the SM plasma coated metallic hydrogen, obtainable by having the metallic hydrogen sheets on the ground with plasma at over 2000 K on top.
balance: changes to the SM and turbines to provide more gas and heat production and more power generation.
add: Explanation of the change: The basic loop of the SM is still the same, turn on the necessary pumps and filters and you're good, the difference is that now the waste gas is not dumped anymore but is rerouted to the turbine, now you just have to turn the turbines on (by using the computers) and turn the incinerator igniter on. Don't forget to setup the SMES near them.
/:cl:

### CODE REVIEW

**Comment by Cheshify** [comment]
SM is a solved system, this is cool.

**Comment by MacBlaze1** [comment]
@Ghilker are you going to update the wiki or are we going to have several rounds of people delaminating the SM trying to figure it out culminating in a revert PR because you didnt bother to explain shit in enough detail?

**Comment by Pickle-Coding** [comment]
Making the SM invulnerable to damage sounds extremely overpowered, especially if it's 30 seconds per sheet.

This would allow you to dump like 100 metal hydrogen sheets into the SM to keep it invulnerable for half the round, then heat the SM with HFR to make a gargantuate amount of power and gases for the rest of the round.

**Comment by CursedBirb** [comment]
> Making the SM invulnerable to damage sounds extremely overpowered, especially if it's 30 seconds per sheet.
> 
> This would allow you to dump like 100 metal hydrogen sheets into the SM to keep it invulnerable for half the round, then heat the SM with HFR to make a gargantuate amount of power and gases for the rest of the round.

"but will ignore any damage coming from high temperatures."

**Comment by Pickle-Coding** [comment]
My bad.

**Comment by CursedBirb** [comment]
Happens

**Comment by YakumoChen** [comment]
A feature this big lacks much of a way of "why this is good"

This sounds like the average engineer is going to need to be even more versed in atmos than current just to figure out how to make the engine go brrrr without it going BRRRRRRRRRRR

**Comment by RandomGamer123** [comment]
How much power does this new round-start setup produce under a standard full N2 setup? (provided you do the easy setup changes like replacing pumps with straightpipes etc)

**Comment by jlsnow301** [comment]
A cool concept but I think this exacerbates (one of) the problems with the SM: There's no fun in overengineering it.

I would love to see this after the result of some sort of "reason" is made to produce power other than keeping the lights on, until then this makes it simply more complicated to perform

**Comment by YakumoChen** [comment]
The SM and atmos have changed so many times in the last year or two I no longer want to have to relearn the entire thing again just to make anything more than a basic N2 setup because they keep changing the math

**Comment by private-tristan** [comment]
I have no idea what this PR means and I am scared
> Change the turbine (I assume you mean supermatter?) to produce power with turbines instead of the zaps and coils. Increased the amount of gas and energy released from the crystal and rebalanced some turbine values.

it seems to use the gas produced and siphoned from the SM to spin, if so, how will this effect cooling loops (the turbines appear to be PAST the cooling loops, meaning that only cold air gets sent in)
is there a design doc so I can understand what's happening?
how is a newbie engineer gonna learn this without spending 30 minutes reading the wiki or having an elder atmosian guide them by the hand?
how will this change setups? will I need to create a new loop specifically for gasses to not get cooled by the cooling loop
how will this change power efficiency?  will the supermatter be able to produce the same amnt of energy as before?

I am very confused, and very scared

**Comment by Pickle-Coding** [comment]
The gases in turbine get burned to make heat.

**Comment by YakumoChen** [comment]
Here's this engine. Your job is to make gas with it. Then burn the gas, to make power.

That's cool. Hey, when I burn the gas, it makes a funny green gas. Can I do anything with that?

That's the beat part: you cant. Another job uses the gas.

Oh. What else can I do?

You can put a different gas in the engine for other effects.

Can I get this gas myself?

That's the best part: you can't. You have to ask the other job for gas.

What else do I do then?

Uh...

**Comment by private-tristan** [comment]
> What else do I do then?

press 10 buttons at roundstart and then go build the shuttle or some other project until the supermatter catches on fire and explodes (you have no idea how to fix SM because it has changed 15000 times in the past 3 weeks)

**Comment by lucigoosi** [comment]
Is there some kind of design doc for these changes somewhere?
Could we possibly get further elaboration on why these changes are good?
_How_ does adding an extra step improve control? Is there an objective measure for this claim? More granularity/complexity is not an inherently good or bad thing and is not grounds alone for a claim either way.
How does increasing the number of interactions improve the game? Furthermore, are the new interactions _good_? Simply adding new ones is not an inherently good (or bad) thing.
If I throw sheets into the SM to turn it into HM and the heat production goes up, what happens when I run out of sheets and it goes back to SM? Will it start taking damage from the increased heat and delam if I'm not ready to immediately begin cooling it? Has this scenario been tested?
Has this change been tested in a long term scenario to ensure that the scrubbers are able to keep up with the increased gas output?

**Comment by YakumoChen** [comment]
"Help I am a janitor that just unlocked HoP and there are no engineers"

2014: "Wrench everything down, turn everything on, and turn everything on, set this to 0

2020: ...
"Now set the pumps to this..."
"Now configure the air alarm like this.."

2022: ...
....
...
"Now a proper gas mix ratio for a plasma burn is..."
...
...
...

**Comment by wesoda25** [comment]
I agree with others that the justification seems lacking.

SM already offers complexity for those who wish to pursue it, and a somewhat simple baseline setup for those who aren't willing to invest that much time. Proper SM setup is currently more important than ever, and I'm not sure making it more complex/changing it is the best thing to do at the moment.

**Comment by ZerVexon** [comment]
This seems way too overly complicated and overengineered as a design philosophy to begin with. This feels like you need to turn 6 boards into a box with some nails, so you make some extremely complicated rube goldberg machine that fills an entire warehouse to build a single wooden crate, and then the directions are in a different language for each and every 5 steps. 

If the SM is being made into the only source of power for the station (Remember, you've already nerfed PACMANs, are planning to hit solars, and tesla and singulo dont exist and there's a rework for turbines) then it needs to exist in a state where people can actually use it.

This would be much better as part of your Turbine rework to add some alternate form for the supermatter (call it hypermatter and then make the state ultramatter or whatever) that doesn't work to produce power, but instead produces the gasses similarly and is meant as a turbine supplement, instead of reworking the SM into it.

**Comment by Dorsisdwarf** [comment]
I think the core concept of the SM-fed turbine is a cool one that deserves development along these lines

**Comment by Colovorat** [comment]
i never ever in my life saw that adding one more step to something makes it easier. It's literally contradictory

**Comment by Pickle-Coding** [comment]
Alright I tried doing a turbine engine powered by supermatter engine. I used BZ for SM because I was too lazy for tritium. It was pretty fun, just dumped SM waste into an upgraded turbine, and generated around 2MW, with grid supply spiking up to 5MW for some reason.

I have no idea why people think this is a bad change or thinks it's complicated. It adds barely any additional setup required, and dumping all of SM waste and burning it (with the igniters the turbine chambers include) is enough to power the station. You don't need to do algebra or anything to let something that is already mapped in for you to make power.

I had a lot of fun building it, and it's not overly complicated or anything.

**Comment by Shadowflame909** [comment]
Appreciate the interest in deeping the complexity of a core-system of the game.

But I think that early game shouldn't be changed so often and so much. Best way to describe it is that by putting so many barriers onto setting up the SM. It makes it that much harder for people who weren't in the know previously, to learn it now.

Stuff like this should be optional, for the atmos mains who love to test their might.

**Review by san7890 — COMMENTED** [review]
Small mapping thing as you go forward in updating all five maps:

Would you mind trimming the SM Loop down a bit? Since people don't need to access/update the Tesla Coils or Grounding Rods, we might be able to tighten up the amount of space the supermatter room takes up in its current configuration.

Let me know if you want me to create a mockup of this for you, since I understand this isn't an easy concept to put into words.

**Comment by Shadowflame909** [comment]
please make a video recording you setting up the new sm after your change so non-math brains like us can copy that instead of actually having to devote time to relearning the sm. \

That'd work out!

**Comment by Jackal-boop** [comment]
So will atmos be given another burn chamber to use for their own gas creation? It would kinda suck having to build your own burn chamber every shift just because the one you have is now strictly dedicated to power production

**Comment by Ghilker** [comment]
> @Ghilker are you going to update the wiki or are we going to have several rounds of people delaminating the SM trying to figure it out culminating in a revert PR because you didnt bother to explain shit in enough detail?

i will update the wiki plus i'll add more informations to the PR itself

> How much power does this new round-start setup produce under a standard full N2 setup? (provided you do the easy setup changes like replacing pumps with straightpipes etc)

With this setup the SM will still make around 800 kW to 1 MW with standard N2 setups (even without replacing pumps)

> I would love to see this after some sort of "reason" is made to produce power other than keeping the lights on, until then this makes it simply more complicated to perform

there is already a reason, now the station constantly needs more power as the rounds go on, since the consumption goes up as the machines are upgraded and build

> I agree with others that the justification seems lacking.
> 
> SM already offers complexity for those who wish to pursue it, and a somewhat simple (not actually) baseline setup for those who aren't willing to invest that much time. Proper SM setup is currently more important than ever, and I'm not sure making it more complex/changing it is the best thing to do at the moment. Barrier of entry shouldn't be made any higher for a job this important to the round.

This is an already planned change that i was doing step by step (from changing collectors to tesla coils) but i needed time to do it and it was impossible to do in one PR. The complexity of base setups hasn't changed, there is just one more step to do before being done, because the basic cooling loop is still the same and the new step is to turn on the turbine (which is a 2 button press)

> So will atmos be given another burn chamber to use for their own gas creation? It would kinda suck having to build your own burn chamber every shift just because the one you have is now strictly dedicated to power production

atmos hasn't change, the incinerator is still there


I also want to add that this is a planned feature from a long time that was impossible to see it done in one or two PRs. I have an old doc (not totally finished and still an old draft but the concepts are there) [Here](https://hackmd.io/HeypdIl9S52ik4zfHUgDpg?view) that i'm roughly following, plus i'm following what @optimumtact wanted about the SM-turbine engine
This is just one more step.

**Comment by CMDR-Gungnir** [comment]
Why are we changing the way it works every 30 days? The Turbine already exists. If people want to use it, they can. Let the SM do SM things. It used to be it worked on radiation. Now it works off of tesla shocks. And while that's still barely set in, now it doesn't actually work and you just pump the stuff to the Turbine?

You don't have to change it every fifteen minutes. It's fine.

**Comment by datorangebottle** [comment]
oh my gooooooood stoooooop.
It's already hard enough to learn atmos/engineering without you changing literally everything every month.
Stop it.

**Comment by Pandarsenic** [comment]
While I'm getting real tired of the lightning round SM changes, especially since it seems shock supermatter wasn't any sort of step toward implementing Superturbinematter

If it comforts anyone, this sounds like how I expected the SM to work back when I first saw it because it's similar to how the first Supermatter engines I saw generated power (the TEG or whatever based on hot gas vs. cold gas) and it wasn't nearly as complicated as it sounded.

**Comment by Dmeto** [comment]
Can you please wire the power produced to Power Monitoring rather than the indepenednt smes so its not powering all of enginerring like we had with tram at one point.I would recomend using Layer 1 or 3 cableing for this.
Space Station 13 2022-05-15 222406

I would also strongly suggest adding a Chamber Monitor like we have with the regular turbine.


A wild Red Pipe apperars!!

Space Station 13 2022-05-15 222422

Having an issue with upgrading turbines gona check if its not a once off thing.

**Comment by CRITAWAKETS** [comment]
Why did you take the half-step of just making it burn the gases? It would've be so much more fun if instead the SM output hothot gas and that's what you used. Right now this just makes the SM look like a crappy incinerator.

also CO2 now is 100% bad to the engine because the pluoxium reaction causes the O2 to get sucked out and turned into pluox.

**Comment by MetalClone** [comment]
Didn't read anything or any comments, Blue super matter is cool enough.
(I lied about not reading, it's pretty cool to have alternate super matter states to allow for a more customizable engine, especially through some things like metal hydrogen that has other little uses)

**Comment by Unit2E** [comment]
Overall, I like this, and I realise it has been in the works for a long time as well (the idea, anyway). But, just a few things:

The turbine is very not perfect currently, I think it still currently has some bugs relating to putting in new parts and taking out old parts. Recently I crowbarred a running turbine, which broke out a part, despite giving me a message I should turn the turbine off first (and it also reduced power generation to 0). Beyond this, replacing parts is somewhat annoying, as I don't think the standard setups on maps allow you to access the non-center parts, which is incredibly clumsy and would necessitate deconstructing R-walls to upgrade parts, and that sort of thing.

So beyond fixing bugs and annoyances, it's also very important to make very, very sure that the turbine setups will make enough power for every station. I don't think this will necessarily be a problem, but ~600 kW generated (preferably around 800) unupgraded is sort of the minimum requirement, as this is what we currently have, and it's often required.

Lastly, though I already mentioned this on discord as well, gas interactions might have to change some. Gases that lower heat penalty are less desirable in this new setup, and power bonuses will become mostly irrelevant, even if they do cause a little bit more gas to be expelled. Make sure to balance these preferably before this goes through.

Not related to the criticism / advice here, but uh, people, this won't make the SM any harder. Shocky SM is also less complicated to set up than radiation SM was, as it is explicitly just a step less than that one was, while working essentially identically. The SM's complexity for the uninitiated player has remained roughly the same for 5+ years, so... what are you talking about?

**Comment by TheVekter** [comment]
This doesn't seem to change anything positively? I thought we were trying to make the SM more interactive, not less. Introducing a thing you can throw into the SM to supercharge it for a while is like... the polar opposite of making it more interactive.

**Comment by Ghilker** [comment]
I've realised that both the SM and turbines requires more work to be done beforehand, so I'm going to close this now and remake it better later on

**Pull request closed without merging**
