### PR TITLE
Fixes disabler inhand sprite and tech levels

### PR DESCRIPTION
**Pull request by jughu**
i wonder who messed this up... HMMM

:cl: Hyena
fix: Fixes disabler in hand sprites
/:cl:

### CODE REVIEW

**Comment by jughu** [comment]
I legit want to know who coded this

**Comment by GunHog** [comment]
>I legit want to know who coded this

https://github.com/tgstation/tgstation/commit/fe76e6464105430aefe76529b0632e5ceeab65bd#diff-87d14f6147ecf517bd2fddfae91bad45R44

**Comment by jughu** [comment]
@KorPhaeron merge pls

**Comment by jughu** [comment]
so now i have a antag token?

**Pull request merged**
