### PR TITLE
Revert "makes tech point gen from rad collectors less useless"

### PR DESCRIPTION
**Pull request by deathride58**
Reverts tgstation/tgstation#38289

THAT PR LETS YOU HAVE A MINIMUM OF 7K FUCKING RESEARCH POINTS PER *MINUTE* ON ONE SINGLE FUCKING RAD COLLECTOR WITH JUST THE ROUNDSTART SETUP. THAT MEANS IT'S ENTIRELY PLAUSIBLE TO GET RND 100% DONE IN ***ONLY*** TEN FUCKING MINUTES WITH MINIMUM EFFORT OR SETUP REQUIRED.

@Tlaltecuhtli why in the actual ***FUCK*** did you think those values in that PR were a good idea? did you do any testing at all?

The original values were so low to make it so that you have to put active effort into speedrunning RND. I've been able to get RND 100% done in 30 minutes without leaving engineering with the original values. 

And to those that want to abuse the new values the moment live recompiles? Here's a step by step guide

1. Set up the supermatter normally. You don't need to do anything special to 100% RnD with it anymore.
2. Instead of putting more plasma into the plasma tanks, put an equal amount of oxygen in the plasma tank to match the amount of plasma inside, then put the oxy/plasma tanks in the rad collectors
3. Wait for the rad collectors to suck the tanks dry. You'll hear a "ding" when the rad collectors run "dry"
4. The rad collectors now contain tritium and oxygen. Multitool every single rad collector and turn them back on. You are now generating upwards of 42k research points per minute if you're using a standard setup.
5. Have fun! You just completed RND without leaving the supermatter chamber.

:cl: deathride58
balance: Reverted the increased rad collector tech point gain rate.
/:cl:

### CODE REVIEW

**Comment by JJRcop** [comment]
I think the changelog entry should nix the second sentence

**Comment by 81Denton** [comment]
How about adjusting the conversion rate to a sensible value instead of reverting it back to uselessness?

**Comment by iskyp** [comment]
@deathride58 literally change 1 N U M B E R to something sensible don't just remove it

**Comment by deathride58** [comment]
@81Denton  The original values are *far* from useless. You just need to know how to set up the supermatter to produce more than just 7 research points per minute per rad collector. I've been able to get a peak of 5k research points per rad collector per minute on a live server with the original values, which took quite a bit of effort, but was worth it since there were warops that round. The more effort you put into setting up the supermatter, the more research points you can get out of it, it's a simple concept to understand. The original values are balanced for engineering autism. The new values are balanced for the instant gratification playerbase that's been infecting ss13 as a whole as of recent.

**Comment by MrDoomBringer** [comment]
@iskyp the original value was sensibile. This is intended to provide motivation to actually putting effort into learning how the SM/atmos works.

**Review by SpaceManiac — APPROVED** [review]

**Comment by RandomMarine** [comment]
>ON ONE SINGLE FUCKING RAD COLLECTOR WITH JUST THE ROUNDSTART SETUP

Ah yes the roundstart setup with the roundstart tritium canisters.

**Comment by deathride58** [comment]
@RandomMarine Rad collectors turn plasma into tritium. Premix the plasma tanks with an equal amount of oxygen instead of adding more plasma, and you can start pumping out research points the moment the rad collectors eject their tanks

**Comment by DaxDupont** [comment]
Why am I not surprised a science Powergamer insanely buffed science.

**Comment by 81Denton** [comment]
@deathride58 Sounds like I had my numbers wrong. Thanks for taking the time to elaborate on that.

**Pull request merged**
