### PR TITLE
Adds tool_behaviour support to crafting, door wires, surgeries and mech construction

### PR DESCRIPTION
**Pull request by ACCount12**
Making `istype` checks obsolete, one PR at a time.

It also makes "cauterize" possible with any hot item, 30% chance, to simplify a tool check in surgery code. This is similar to "incise" step, which has 30% success chance with any sharp item.

### CODE REVIEW

**Comment by Bawhoppen** [comment]
What qualifies as a "hot" item? I'll update the wiki.

**Comment by ACCount12** [comment]
Energy swords, lighters, matches, candles, flares, cigarettes, cake hats (when on),

**Comment by ACCount12** [comment]
I don't think this is what [Tools] tag means.

**Comment by vuonojenmustaturska** [comment]
it isn't, but you can't say it's not appropriate

**Comment by praisenarsie** [comment]
ree misusing labels

**Comment by ACCount12** [comment]
This was test merged, no issues reported. Ready to merge?

**Comment by YPOQ** [comment]
Multitools don't make a noise when pulsing wires.

**Comment by ACCount12** [comment]
Pretty sure that's fixed by #35521. I can port a fix from there.

**Comment by ACCount12** [comment]
It isn't, the sound PR was merged ahead of it. Conflicts resolved, RTM.

**Pull request merged**
