### PR TITLE
Adds a bunch of cyborg limbs to the surgery closet

### PR DESCRIPTION
**Pull request by Ergovisavi**
:cl:
add: Added robot limbs to the surgery closet, for MD's to more easily replace lost limbs. Or augment people, whatever.
/:cl:
- Adds a set of robot limbs to the surgery closet

Nobody ever gets augmented around here and it's stupid that in the future you wouldn't have spare limbs lying around to replace ones lost in workplace hazards. I mean, look at Dead Space, they had tons of cloning facilities dedicated to generating limbs and organs.

I considered just putting basic limbs in there but I realized that it's more entertaining if they're robot limbs, and people get augmented. You don't have any flashes or an endoskeleton, so you can't make a cyborg though. And robotics has a bunch of stuff to do anyway, so into the MD pile it goes.

### CODE REVIEW

**Comment by Bawhoppen** [comment]
powercreep

nah but really, this is less fun than having to get genetics to make your a human so you can chop off it's legs

**Comment by Jazaen** [comment]
Speaking of genetics, I think you still can regrow limbs by turning them into a monkey and back into human (though it might mess up some stuff like skin colour and such for lizards).

**Comment by ExcessiveUseOfCobblestone** [comment]
I aug all the time as robro and even advertise my services :angry: 

Please replace them with the normal legs/arms. I don't want to lose a very enjoyable aspect to ROBROs because medbay stutterwhores want the job.

**Comment by Core0verload** [comment]
I think one set of robot arms and legs is okay.

**Comment by Niknakflak** [comment]
:-1: go ask robotics and interact like a normal person.  Hugbox BS easy life shit pls go

**Comment by optimumtact** [comment]
This weird concept of taking one jobs items and putting them in other jobs department is very strange.

Do you think it's like balance or something? Because it really just harms one job

**Comment by PKPenguin321** [comment]
nice quality of life thing but probably not good for the game's interaction aspect, if you want to harvest limbs ask genetics for a monkeyman or ask robotics directly.

**Comment by Jordie0608** [comment]
I agree this is a poor idea.

**Pull request closed without merging**
