### PR TITLE
Xenobiology consoles can now scan slimes and apply potions

### PR DESCRIPTION
**Pull request by XDTM**
:cl: XDTM
add: Xenobiology consoles can now scan slimes and apply potions remotely. Use potions on the console to load them.
/:cl:

Before someone kneejerk rages against QoL, the whole scan/potion system is still made for old xenobio.
Currently, if you are trying to get a slime to 100% mut chance, you have to do stuff like this:

* Open door 1
* Open door 2
* Scan each slime to find out which one is the highest
* Apply potion to highest
* Open door 2
* Open door 1
* Wait, a slime slipped out
* Open door 1
* Open door 2
* Try to pull slime in, but door 2 closes
* Open door 2
* Pull slime in
* Open door 2
* Open door 1
* Go to console
* Forget which slime you were about to keep
* Go back in to re-scan
* Get out
* Goddamn slime slipped out again

Repeat for several generations

### CODE REVIEW

**Comment by LarissaMayrink** [comment]
fucking loved it

**Comment by Tlaltecuhtli** [comment]
speedmerge

**Comment by GuyonBroadway** [comment]
Yeah but trimming the fat with regards to clunkiness is a good thing IMO.

**Comment by Repukan** [comment]
It's not even trimming the fat when the console allows you to take out slime by slime and check them individually.

You're comparing how it was done in old xenobio to how it's done now.

If you want rainbows that much go to the tedium. What's next, making mesons have ore scanners so miners don't have to use mineral scanners inhand?

**Comment by GuyonBroadway** [comment]
They don't have to use the scanners in hand, just stick em in their pocket like a Tray scanner and away they go... actually mining scanner goggles might make a nice thing to add to the mining vendor.

**Comment by Ratvar** [comment]
Stop opening doors and use console to teleport slimes near you, you don't have to do staff like this

**Comment by KomradeSpectre** [comment]
I can agree with this change to be honest.

**Comment by kevinz000** [comment]
powercreep but i'm a science main :+1:

**Comment by Kromgar** [comment]
Powercreep but 90% of the itme the round is too short to get rainbows anyway

**Comment by Repukan** [comment]
Players aren't entitled to the end game rewards of any job.

**Comment by DoctoreMad** [comment]
Mommy if you don't hold my hands I'll intentionally run in front of a car
I dare you let me go

**Comment by ayyourboibilly** [comment]
ADD NOW

**Comment by Robustin** [comment]
I think QOL stuff like this is good for the game but endgame Xenobio will (and already does) need a reckoning to acknowledge that it's always been a bunch of crazy OP bullshit locked behind tedious clicking for 20 minutes. As we remove the tedious clicking, the bullshit is going to be pouring out faster and in greater quantities.

**Comment by InsaneHyena** [comment]
(((Quality of life)))

**Comment by XDTM** [comment]
@Robustin fair point, but the point of xeniobio itself is, in my opinion, great rewards at the cost of great time investment. My goal here is to make the time investment based on game mechanics (time to split/kill/grind slimes) rather than clunkiness and busywork (wrestling with door timers, inserting monkey cubes one by one, etc.). If it ends up being too fast to have healthy rounds, we can adjust slime split time, the evolution tree, mutation chances, grinder upgrades and so on without making it frustrating.

**Comment by ExcessiveUseOfCobblestone** [comment]
I have a feeling xeno will see the nerf bat quite soon.

**Comment by Slignerd** [comment]
>It's not even trimming the fat when the console allows you to take out slime by slime and check them individually.

I did that once, then someone walked into my lab, and the slime started breaking things and chasing after them.

**Comment by juanototo2** [comment]
Dude RnD got neutered due to dept lathes let them keep SOMETHING

t. greytide main

**Comment by ExcessiveUseOfCobblestone** [comment]
replace lame console with epic slime ~~rancher~~ gun

**Comment by Noahnoah55** [comment]
Maybe you could give the slime scanner a 3-5 tile range that works through windows to encourage xenobiologists to get out of their seat more often.

**Comment by XDTM** [comment]
If you think about it keeping them glued to the console is a nerf to their awareness

**Comment by ayyourboibilly** [comment]
honestly this should of been added  a week ago

**Pull request merged**
