### PR TITLE
Laptops now have actual sprites for using the supermatter monitoring instead of defaulting to a generic one.

### PR DESCRIPTION
**Pull request by JStheguy**
:cl: JStheguy
imageadd: Laptops now have actual sprites for using the supermatter monitoring instead of defaulting to a generic one.
/:cl:

It still counts as a sprite change if the code changes were only in service to the sprite change, right?
Also here is a preview, this being of the laptop running the monitoring program while shit is not fucked:
https://puu.sh/x1uNC/2d4bd8fb04.gif

From the DMI:
untitled

### CODE REVIEW

**Comment by Cyberboss** [comment]
... We have laptops?

**Comment by XDTM** [comment]
Modular computers between tablets and consoles

**Comment by JStheguy** [comment]
Yeah, they're a bit pointless at the moment, as the only thing they have over tablets is that they support more powerful hardware, when the current situation means that basic hardware is more than enough, and also that they can have an unusable intellicard slot.
All for the low-low price of not being able to put it in your belt or pocket slot.

**Comment by CosmicScientist** [comment]
I thought laptops were just consoles with a different sprite? What's the one in box's security medical area?

**Comment by francinum** [comment]
There's 2 types of laptops, the fakeass console ones, like the medical laptop, and the modular computers ones, which are objects.

**Pull request merged**
