### PR TITLE
Ports gas sprites from paradise

### PR DESCRIPTION
**Pull request by ghost**
More realistic, tbh.

:cl: More Robust Than You
spriteadd: Ported gas sprites from paradise
/:cl:

also i need freon and maybe vapor sprites

### CODE REVIEW

**Comment by MoreRobustThanYou** [comment]
Also, should i increase/decrease the contrast/brightness/etc?

**Comment by DoctoreMad** [comment]
Got any Zyklon B?

**Comment by ChangelingRain** [comment]
Wow you can see the tile borders amazing.

Also, this won't be accepted until you can click objects under the gas overlay, since that still isn't fixed.

**Comment by ChangelingRain** [comment]
Actually given that I seriously doubt you know how to fix that, since *we* don't, let me just....

**Comment by optimumtact** [comment]
don't be that dickish and at least give them 24 hours to attempt to fix it

**Comment by lordpidey** [comment]
This will also make glitter bombs not make sense.  We can deal with that later though.

**Comment by optimumtact** [comment]
from this very simple initial screenshot it does appear nicer, but it's very suspicious they did not show the edge of a flood or somethign similar, which is where this probably blends the worst

**Comment by nicbn** [comment]
Yes please

**Comment by nicbn** [comment]
For freon change plasma hue, for water vapor change N2O speed and make N2O more transparent.

**Comment by Qustinnus** [comment]
looks nice in the screenshot, but I'm also worried about how it looks when leaking.

maybe we can have some kind of icon smoothing for gas connected to open tiles.

**Comment by nicbn** [comment]
We can just decrease the opacity for tiles where there is less gas.
That way we can even mix the sprites and do fancy things.

**Comment by GunHog** [comment]
Concurred with Qustinnus. The edges of lavaland rock have a fuzzy look to them; You could give gas overlays puffy edges or something. Even so, gas has always had sharp, square edges, including fires. Lack of smoothing would not be a reason against this change, in my opinion.

**Comment by lzimann** [comment]
i think these are really bad and i'll probably close in 24h or something

**Comment by nicbn** [comment]
No these look amazing!!

**Pull request closed without merging**
