### PR TITLE
Inhand icons for scrubs and hardsuit

### PR DESCRIPTION
**Pull request by StoneMason**
## About The Pull Request

Made two PRs (58156, 58205) about adding inhand icons to the elite hardsuit and medical scrubs. I fucked up and I have no idea how fix code. This just merges those two PRs with the final changes that Twaticus approved. If this gets merge conflicts again, I'll cry and blacklist myself from the repo.

## Why It's Good For The Game

image

## Changelog
:cl:
fix: fixes the syndie hardsuit clipping through people
imageadd: adds new inhand icons for scrubs and elite syndie hardsuit
/:cl:

### CODE REVIEW

**Comment by StoneMason** [comment]
how the fuck does a sprite change, conflict with the map bot what

**Comment by StoneMason** [comment]
i have zero idea why the dmi files are conflicting, theyre the same!!!

**Comment by StoneMason** [comment]
alright im gonna go cry and sleep, i have zero idea what the issue is

**Comment by optimumtact** [comment]
simply changing the file to be the same as the latest file on master is not enough to resolve a conflict.

You must do a git merge operation and rectify the conflict during the merge operation.

No matter how many times you update the file here, git will still flag it as conflicted because it has no common ancestor commit.

**Comment by StoneMason** [comment]
man how the fuck does code work hold on

**Comment by StoneMason** [comment]
WELL THE MERGE CONFLICTS ARE GONE

BUT NOT THE FUCKING 2000+ FILE CHANGES

**Comment by optimumtact** [comment]
IM GIVING HER ALL SHES GOT CAPTAIN

**Comment by StoneMason** [comment]
ok ok ok ok ok ok ok ok ok ok ok give me like 2-3 buisness hours to cry and figure out what to do

**Comment by StoneMason** [comment]
learning to use code shit and github isnt a high priority for me at the moment, i havent got the time, the dmi files are there for anyone who wants free gbp, thanks for the advice though

**Pull request closed without merging**
