### PR TITLE
Reverts Fungal tuberculosis #14107

### PR DESCRIPTION
**Pull request by Niknakflak**
Reverts #14107
See this feedback thread where everything is explained in detail: https://tgstation13.org/phpBB/viewtopic.php?f=10&t=5591
It's awful
Overpowered
Not Fun
Remove virology without memes when?

### CODE REVIEW

**Comment by TheWiznard** [comment]
100% thumbs up

**Comment by hornygranny** [comment]
i could have prevented this

**Comment by hornygranny** [comment]
why did you stop me

**Comment by hornygranny** [comment]
https://tgstation13.org/wiki/Getting_Your_Pull_Accepted#3._Do_not_automatically_add_FILE_DIR.

**Comment by Niknakflak** [comment]
god damnit, so close

**Comment by Incomptinence** [comment]
Weak

Keep the death

**Comment by KazeEspada** [comment]
Niknak, go to the TB PR and click the REVERT button.

**Comment by xxalpha** [comment]
Improve don't remove.

**Comment by KazeEspada** [comment]
You can't improve trash.

**Comment by duncathan** [comment]
@Niknakflak nah this isn't cancer
I think that one's in line for his next PR

**Comment by Incomptinence** [comment]
@KazeEspada 
WRONG YOU CAN MAKE IT KILL BETTER!

**Comment by Niknakflak** [comment]
Incompitence with his bad ideas striking again

**Comment by duncathan** [comment]
#15018 is a better removal

**Comment by duncathan** [comment]
I was mistaken; I thought the other one completely removed it from player reach

**Comment by xxalpha** [comment]
Unless players can use the spawn verb, it does remove it from players reach.

**Comment by duncathan** [comment]
Apparently nuke ops have a grenade or some shit

**Comment by LanCartwright** [comment]
Nuke rounds don't last long enough and it's an effective area denial weapon for ops.

Also my next virology update, it removes blood vomiting, so all you need is internals or sterile mask and a janitor and you're golden.

**Comment by Niknakflak** [comment]
You mean it's an effective (die to disease and bullshit) instead of tacticool shootouts.  It's a lousy weapon for nuke ops.  The whole point of the revert is because the disease is not fun.  Hell, diseases in general are all around, just anti-fun

**Comment by tkdrg** [comment]
We'll try making it nuke-only first. If it's still bad then you can ping me or another maintainer to reopen this.

**Pull request closed without merging**
