### PR TITLE
HoP and Cap spawn with jackboots

### PR DESCRIPTION
**Pull request by axietheaxolotl**
## About The Pull Request

yeah

## Why It's Good For The Game

Sneakers cringe peepee poopoo. Now jackboots are based, they look kino.

## Changelog

:cl: Nanotrasen Employee Footwear Department
code: We've stopped giving the Head of Personnel and Captain surplus Converse, and now give them Standard Issue Jackboots
/:cl:

### CODE REVIEW

**Comment by JohnFulpWillard** [comment]
Captains and HoP's aren't part of security, I am heavily against them getting any sec gear. They're supposed to look formal, especially the HoP who is basically a fancier Lawyer.

**Comment by Sealed101** [comment]
the only fitting footwear aside from brown sneakers for hop or cap is lizard skin boots

**Comment by axietheaxolotl** [comment]
> Captains and HoP's aren't part of security, I am heavily against them getting any sec gear. They're supposed to look formal, especially the HoP who is basically a fancier Lawyer.

How is giving them literal converse formal. If we want them to look formal, give them laceups.

**Comment by UnokiAs** [comment]
Eh give the captain jackboots, it's own sprite to match with the outfits (Blue yellow or something)

**Comment by necromanceranne** [comment]
Give them lace up shoes, if anything else.

**Comment by SuperNovaa41** [comment]
powercreep plus thinly veiled balance

**Comment by Pickle-Coding** [comment]
Jackboots don't look good on them, or match in any way. Obviously powercreep.

**Comment by tf-4** [comment]
Cringe powercreep

**Comment by cacogen** [comment]
why would bureaucrat wear jackboots unless to stomp paper tray pile down no

**Comment by Fikou** [comment]
holy cringe

**Comment by MrDoomBringer** [comment]
brown shoes aren't converses what are you saying

**Comment by EricZilla** [comment]
HOP and Cap have money and access they can go buy new shoes

**Comment by Googles-Hands** [comment]
You should close this PR... Now!

**Comment by optimumtact** [comment]
Get the hell out of here with this garbage.

**Pull request closed without merging**
