### PR TITLE
Guide to Advanced Mimery spellbooks will grant the vow of silence spell if the user doesn't have it already.

### PR DESCRIPTION
**Pull request by harmonyn**
You can't use the spells the mime spellbooks grant you unless you have a vow of silence going. But the game still allows you to read the spellbooks and get the spells, you just can't use them, which seems silly and overly restrictive. If a mime traitor wants to give his spellbooks to someone else, I don't see why he shouldn't be able to. (The other day I was the clown and the mime and I were traitors, and we did a gimmick of trading each other's tator items, except I had to ahelp to actually use the spells. Massively disappointing.) Vow of silence is useless on its own so I don't think this will affect balance.

Also added the spell names to the messages you get so it wouldn't show up blank ("You have learned how to cast !"), idk if this was some kind of mime joke but if it was it was more confusing than funny

### CODE REVIEW

**Review by SpaceManiac — APPROVED** [review]

**Comment by Wilchenx** [comment]
I don't think having a infinite use spellbooks in the round is a good idea.

**Comment by ExcessiveUseOfCobblestone** [comment]
people running silently around shooting people with finger guns is the epitome of ss13

**Comment by bgobandit** [comment]
>I don't think having a infinite use spellbooks in the round is a good idea

What? That part isn’t changed, the books have the same number of uses they always did, they just also give vow of silence

**Comment by Wilchenx** [comment]
>I don't think having a infinite use spellbooks in the round is a good idea

>What? That part isn’t changed, the books have the same number of uses they always did, they just also give vow of silence

Which is?

**Comment by ExcessiveUseOfCobblestone** [comment]
@Wilchenx 1

https://github.com/tgstation/tgstation/blob/f8f9d83eee8ae7769772ca57d97acd42cf82ac48/code/game/objects/items/granters.dm#L4-L11

**Pull request merged**
