### PR TITLE
Fixes Ling Decap

### LINKED ISSUE #51408: Changelings permanently die if beheaded
If you get beheaded as a ling, all your powers stop working and you cannot revive.

### PR DESCRIPTION
**Pull request by ExcessiveUseOfCobblestone**
## About The Pull Request

arm: we are not going to delete ur brain
also arm 3 lines later: we are going to delete ur organ 😏 

fixes #51408 

🆑 Cobby
fix: Lings cannot be owned by decap
/:cl:

### CODE REVIEW

**Comment by ExcessiveUseOfCobblestone** [comment]
line 285-287 is SUPPOSED to protect decoy (ling) brains from being deleted but 288-289 deleted it anyways so basically the edits made to the brain in the ling power were useless because it was getting overwritten here.

**Comment by Pugie** [comment]
It's only been a year

**Comment by ExcessiveUseOfCobblestone** [comment]
fakenews, reported

**Comment by davethwave** [comment]
Any idea if this fixes the old devil decap glitch as well?

**Pull request merged**
