### PR TITLE
Replaces a / with * as per Contributing.md [bscrystal.dm]

### PR DESCRIPTION
**Pull request by ExcessiveUseOfCobblestone**

### CODE REVIEW

**Comment by optimumtact** [comment]
you're bikeshedding on my repo

**Comment by optimumtact** [comment]
it's bikeshedding to make that change in a pr all of it's own

**Comment by ExcessiveUseOfCobblestone** [comment]
IM ENFORCING THE STANDARDS

(i don't really care I think it's silly to begin with)

**Comment by optimumtact** [comment]
You're treading on my dreams preston

**Pull request merged**
