### PR TITLE
Adds Short tail for Lizards

### PR DESCRIPTION
**Pull request by whataboutism-alos**
## About The Pull Request
This PR adds a short tail for lizard characters called Short. It is about half the length of the other tails. This tail has been fully sprited in 9-frame animation in accordance with the sprite style in use by other lizard tails. Hope you like my work; this is my first PR, let me know if I am missing anything.

## Why It's Good For The Game
A couple lizard players requested this of me. If there's a demand for short tails, why not? This change is cosmetic only, it adds a new selectable lizard tail and nothing else.

sogtail_tg

## Changelog
:cl:
add: Sprited and implemented a short lizard tail
/:cl:

### CODE REVIEW

**Comment by mikederkan** [comment]
show us the tail.

**Comment by DATA-xPUNGED** [comment]
> show us the tail.

When you get around to this, show us a comparison between the NORMAL and short tail

**Comment by DATA-xPUNGED** [comment]
Also, does this account for the frills?

**Comment by whataboutism-alos** [comment]
> show us the tail.

Currently making it and its wag state into a nice gif.

**Comment by whataboutism-alos** [comment]
> Also, does this account for the frills?

Frills work just fine with it. However, it IS NOT meant for use with spines owing to the fact that the spines' pixel dots just keep going well past it. If someone could point to a way of writing a proc that could override the spine icon state, I would make alternate versions of each for the short tail. At the moment, I have no clue how to do that, and so this short tail is for spineless lizards (kek).

**Comment by whataboutism-alos** [comment]
Here is the Short tail, in comparison to the Smooth tail. Excuse the slightly imperfect loop.

sogtail_tg

**Comment by optimumtact** [comment]
https://github.com/tgstation/tgstation/blob/master/.github/CONTRIBUTING.md#banned-content

**Comment by whataboutism-alos** [comment]
> https://github.com/tgstation/tgstation/blob/master/.github/CONTRIBUTING.md#banned-content

Thanks, who can I get in contact with to talk about that?

**Comment by thgvr** [comment]
It's a good sprite.

**Comment by DATA-xPUNGED** [comment]
> https://github.com/tgstation/tgstation/blob/master/.github/CONTRIBUTING.md#banned-content

i thought cosmetic stuff was fine?

**Comment by DaCoolBoss** [comment]
Front/back facing wagging animations look good, but left/right facing ones look like the tail is wagging vertically like a dog. Lizard tails are heavy, reptiles rarely lift them like that. Keeping the tip of the tail at the same height throughout the animation will make it look less weird.

**Comment by whataboutism-alos** [comment]
> Front/back facing wagging animations look good, but left/right facing ones look like the tail is wagging vertically like a dog. Lizard tails are heavy, reptiles rarely lift them like that. Keeping the tip of the tail at the same height throughout the animation will make it look less weird.

I understand that, but I based this off of the Paradise/Bay sogtail spritesheet on request. That one has the same discrepancy, and I was asked to keep it. I think that one was animated as it was because the shortness of the thing kind of made it tweaking horizontally in the air near its tip look odd. Further, I think it can be justified that this tail is a lot lighter given the halved length.

**Comment by DaCoolBoss** [comment]
It should be consistent with TG sprites rather than para bay. Up/down wagging sprites are close to the standard lizard tail, left/right wagging isn't. Non wagging is consistent in all directions. That animation sticks out a lot.

**Comment by whataboutism-alos** [comment]
> It should be consistent with TG sprites rather than para bay. Up/down wagging sprites are close to the standard lizard tail, left/right wagging isn't. Non wagging is consistent in all directions. That animation sticks out a lot.

Yeah, that’s a good point. It irks me too, so I’ll probably do it sometime tonight.

**Comment by thgvr** [comment]
> It should be consistent with TG sprites rather than para bay. Up/down wagging sprites are close to the standard lizard tail, left/right wagging isn't. Non wagging is consistent in all directions. That animation sticks out a lot.

Honestly, I think it's better.

**Comment by whataboutism-alos** [comment]
Adding two-tone option as well. Push coming in the next few hours after playtesting. Thanks to thgvr for making that mod to my sprite.

**Comment by whataboutism-alos** [comment]
Ok, given TG's current status regarding secondary colors for lizard parts (read: no functionality), guess I won't be doing a two-tone variant to the existing one added by this PR. The goal of this PR is not to rework TG mutant color customization. Which makes this PR all ready for an assignee and review. 

_The additional content is already made, I simply won't be pushing it. If a secondary mutant color is implemented on TG I would add Short (Two-Tone) tail as a new PR._

**Comment by Ghommie** [comment]
Soooo, is this good to go?

**Comment by whataboutism-alos** [comment]
> Soooo, is this good to go?

Yep!

**Pull request merged**
