### PR TITLE
Removes light blasts shredding clothes

### PR DESCRIPTION
**Pull request by Ikarrus**
ex_act(3) no longer shreds clothes.
Also, jumpsuits are a little more resistant to all blast severities.

### CODE REVIEW

**Comment by CPTANT** [comment]
yeah light blasts shredding clothes went pretty silly. My security jumpsuit got destroyed by a ling bursting into a headslug.

**Comment by xxalpha** [comment]
You also should make bomb suits very resistant to bomb shredding.

**Comment by Lumipharon** [comment]
Old bombs destroying items wasn't popular and I haven't particularly seen anyone like the new iteration.

Getting your boots or armor blown up by a weak as water/pot nade is pretty gay, let alone shit like losing parts of your hardsuit etc.

**Comment by Ikarrus** [comment]
I hear you. I've removed shredding for light severity explosions

**Comment by Kromgar** [comment]
Hahahaha weak as water potassium nade.

300water 300 potassium grenades are bomb  cap

**Comment by Lumipharon** [comment]
I meant a 30u waterpot nade, that blew off my boots and armor.

**Pull request merged**
