### PR TITLE
Adds pet collars to heads of staff lockers.

### PR DESCRIPTION
**Pull request by Wilchenx**
:cl: Wilchen
add: Adds pet collars to captains, cmo's and hos's lockers.
/:cl:

### CODE REVIEW

**Comment by Thunder12345** [comment]
The first part is supposed to be your name, silly

**Comment by Qbopper** [comment]
include me in the screencap

is this really going to be a problem

**Comment by RogueSteampunker** [comment]
@Qbopper Of course it is

**Comment by Qbopper** [comment]
it's probably going to be another "the people complaining about X are far worse than X" episode, but this time the PR was suggested by the head coder

**Comment by optimumtact** [comment]
I assumed this was in bad faith because of who it was coming from

**Comment by The-clown-known-as-Pepe** [comment]
@optimumtact sorry i gave you the wrong impression fruitboye

**Comment by KorPhaeron** [comment]
I think qm/hop/cmo are thr only ones who have a pet on every map

**Comment by The-clown-known-as-Pepe** [comment]
@KorPhaeron pretty sure HoS too

**Comment by KorPhaeron** [comment]
Also I think Runtime and Ian are the only ones the collar works on anyway

**Comment by KorPhaeron** [comment]
So it might make sense for the CMO to get one but giving the RD one to smack lamarr with would be silly

**Comment by Iamgoofball** [comment]
They only work on the cats and dogs. Anything that isn't one of these two do not support collars, and thus don't need them.

This would be better accomplished by making the collars start on the animals.

**Comment by FantasticFwoosh** [comment]
You are obviously just abusing this PR for the effect.

**Comment by Qbopper** [comment]
\>random horizontal line
\>random list bubble
\>bolding text fnr
\>still difficult to parse sentences (though this one isn't so bad)

it's a fwoosh post through and through

**Comment by KorPhaeron** [comment]
>I assumed this was in bad faith because of who it was coming from

One of my many spies told me this PR was made to cause all the fighting we're having now so you're not wrong

Someone should make these spawn on Ian/Runtime/Renault if they have a non shitposting interest in the matter

**Pull request closed without merging**
