### PR TITLE
Put's the AI back out of its place

### PR DESCRIPTION
**Pull request by Incoming5643**
There's a lot of fighting on both sides and I just wanted to get this put up before someone more passionate about this does and makes a huge stink in the description here. Personal opinions follow in the comments.

Keep it civil~

Reverts tgstation/tgstation#18625

### CODE REVIEW

**Comment by KorPhaeron** [comment]
I plan on merging this unless someone comes up with an alternate solution that doesnt involve every critical station system (power, comms, gravity) in one spot

**Comment by Incoming5643** [comment]
I don't mind the idea of a central AI personally, but having the Grav Gen, the SMES, and telecom right next to each other marks the return of "the golden bomb spot" that can potentially disable all three. Literally every nuke round will use it, as they have historically.

At least two of these things need to be moved for a centralized AI to be viable. I'm not exactly too sure on where those spots could be, but maybe they exist?

Also the Grav Gen has to move/move back, as it's an irreplaceable machine within sauntering distance of every singularity release. "No one uses the singularity anymore!" is not a valid arguement, and also isn't really true.

**Comment by Cheridan** [comment]
>extremely contentious PR opposed by design lead who points out valid issues with it
sounds good lets merge it

:person_frowning:

**Comment by pudl** [comment]
Here's my feedback: This change polled successfully and was tested and was popular, with no issues. This change hasn't even been UPDATED to the server, so the entire issue pointed out here is hypothetical. What if it turns out to not be an issue at all? Especially with the fact that the singularity almost never gets used anymore.

Also, having the gravity gen back in one place changes absolutely nothing. If the singularity is released, a shuttle will be called no matter what. Just because the gravity gen has a higher chance of being released doesn't change anything whatsoever. If someone were to set off a bomb that destroys engineering and telecomms, the shuttle would be called anyway, the gravity gen now being in that range doesn't do anything different.

**Comment by pudl** [comment]
I approve this change

**Comment by MMMiracles** [comment]
best choice is just to go full-out and put it back on its own separate z-level, absolutely nothing bad can happen.

**Comment by Firecage** [comment]
Silly @MMMiracles . The AI was only ever on a seperate Z-level during malf on the old AI satellite.

**Comment by Bawhoppen** [comment]
bikeshedding ahoy

**Comment by tedward1337** [comment]
Ffs just decide on one spot for the AI to be god damn

**Comment by ike709** [comment]
flip a coin to decide whether or not to merge this and don't allow a revert or reattempt of this for a month

**Comment by jughu** [comment]
Follow old goon cannon give it a satalite on abandoned teleporter z level where the abandoded teleporter got fixed and then add a supermatter setup where old satalite was for godsake of varierity

**Comment by optimumtact** [comment]
I'm sorry but the poll had a majority for the AI being in the center of the station.

The tail doesn't get to wag the dog.

**Comment by optimumtact** [comment]
In fact the only way we could merge this and not be hypocrites was if it only moved around the smes and telecoms

**Comment by jughu** [comment]
>listening to powercreeps so they can take the ai easily down

**Comment by Incoming5643** [comment]
I suggest that nearly no one who voted in the poll understood or even thought of the ramifications of the golden bomb spot. They didn't vote for that.

**Comment by KorPhaeron** [comment]
Yeah it's not like there was an overwhelming consensus, and we shouldn't fuck the primary map to satisfy the lust for AI nerfs.

If we always went by straight player votes we'd have secborgs back as well.

**Comment by Cebasiz** [comment]
straight player votes two zero one six

**Comment by optimumtact** [comment]
straight player votes only matter when I make the poll

**Comment by Niknakflak** [comment]
If I were to map the gravity generator and or telecomms somewhere else, would this revert be closed?

**Comment by Incoming5643** [comment]
If anyone can figure out the tcomms/SMES/Grav Gen shuffle that solves these three conditionals I'd personally be placated

1. The Grav Gen can't be extremely close to the engine
2. The SMES / SMES room mustn't be extremely close to tcomms
3. The AI sat still exists even if it's unused simply because it's a cool space for hideouts/lairs.

But I probably wouldn't close this PR if other people still had problems with it.

**Comment by KorPhaeron** [comment]
Moving like 6 rooms in 1 week just feels wrong for our oldest and most popular map

**Comment by ChangelingRain** [comment]
Well, we could go to one of our less-changing maps, like dreamstation or meta.

**Comment by optimumtact** [comment]
alternative maps get out reeeeeeeeeeeeeeeeeee

**Comment by Zilenan91** [comment]
Why don't we just put the gravgen where the Gateway is since we're not ever going to use it

**Comment by KorPhaeron** [comment]
Downstreama use it.

Also I cant tell if Joan is joking about merging bad changes to kill box or not

**Comment by optimumtact** [comment]
I agree with zilenan

gateway can be moved, or downstreams can remap it in

**Comment by Niknakflak** [comment]
Working on an alternative to this

**Comment by Lumipharon** [comment]
Well since I completely missed the previous PR until after it got merged, here's my opinion.

>Makes Antag/rogue AI easier to put down

AI is honestly already easy to kill. Hell, the sat even got buffed up the ass because it was STILL too easy.

>Makes AI much harder to kill FOR antags

This is very bad. Literally all of the crew traffic flows around the center block of the station, and 99% of the crew is within 20 seconds of whatever poor prick that got the objective to gank the AI. It does not matter that mechanically it is easier to get to the AI - the 50 crew being ready to valid your ass with 5 seconds notice is the problem.

>grav gen is 1 r-wall away from space

This is incredibly bad. Enjoy every nuke op round for the rest of time being a nograv, jetpack abusing shitshow as they use the a block of c4 to take out grav every round, because they have a objectively HUGE advantage in zero gee. I would like to say that it wouldn't be such an issue in other roundtypes, but lets be real - when you got CERTAIN POWERGAMING FUCKS that love any chance to abuse mechanics to murder bone, you can be sure this will be jumped upon.

**Comment by KorPhaeron** [comment]
@Incoming5643 

Conflicts

**Comment by Incoming5643** [comment]
I didn't sign up for this shit

**Comment by ChangelingRain** [comment]
Travis no longer exists for this PR please stand by

**Comment by tedward1337** [comment]
Oh for fuck sakes guys

**Pull request merged**
