### PR TITLE
Small ghosting changes

### PR DESCRIPTION
**Pull request by ghost**
- Ghosting now clears the mob's key
- Ghosting now messages admins about the ghosting, for purposes of knowing the mob's old key
- Ghosting is now logged

### CODE REVIEW

**Comment by Durkel** [comment]
neat :+1:

**Comment by bgobandit** [comment]
This is only on the first ghosting, right? So people can't spam admins by repeatedly re-entering their body?

**Comment by francinum** [comment]
@bgobandit You can't re-enter it.

**Comment by SconesC** [comment]
Cool

**Comment by MrStonedOne** [comment]
Ghosting clearing the key doesn't matter, the assigning of the key to a new mob clears the old key.

**Comment by Xhuis** [comment]
@MrStonedOne For a very long time the mob's old key was conserved with an '@' before it, is this no longer the case?

**Comment by Xhuis** [comment]
fffffffffffffffffffffUCK

**Comment by Xhuis** [comment]
OH GOD HELP

**Comment by Xhuis** [comment]
Well, I just tested this on the latest revision and discovered that ckeys are properly wiped now. Closing this.

**Pull request closed without merging**
