### PR TITLE
Buffs BCI capacity

### PR DESCRIPTION
**Pull request by SmArtKar**
## About The Pull Request

Buffs BCI capacity because mothblocks said so

Alternative to #60529 

## Why It's Good For The Game

10 capacity only allows you to make simple circuits like "3 buttons that transmit signals and when X signal is recieved mark ref from it using HUD" which is not really cool. Mothblocks said to just add capacity to BCIs so here it goes.

## Changelog
:cl:
balance: BCI now has more capacity
imageadd: Adds new cool sprites for BCI
/:cl:

### CODE REVIEW

**Review by Mothblocks — APPROVED** [review]

**Comment by moocowswag** [comment]
I kind of liked the limited capacity because it meant that if more ways for your bci to function were added you could pick and choose and specialize what your bci does, but i guess circuits in their current unfinished state warrant these kinds of buffs.

**Comment by Mothblocks** [comment]
its more likely that if a certain functionality becomes too powerful we'll tweak things along the way, capacity was not really a balancing factor yet

**Comment by Colovorat** [comment]
i think it would better to make incompatible components with BCI's, because, muhh dangerous to brain to have such components and etc(if we would have some OP components in BCI's. Higher capacity just let things make more cooler

**Comment by Mothblocks** [comment]
Due to the general nature of circuit components, I find it unlikely we'll blacklist any for BCIs for anything other than technical reasons.

**Comment by Mothblocks** [comment]
Taking #60587 instead

**Pull request closed without merging**
