### PR TITLE
Fixes drone inventories

### LINKED ISSUE #23520: Doing basically anything to an item as a drone puts it inside of you
this is probably @Cyberboss 's fault

### PR DESCRIPTION
**Pull request by Cyberboss**
Fixes #23520 

FUCKING IM GONNA MURDER WHOEVER CALLED THE BASE PROC WITH MANUAL ARGS

### CODE REVIEW

**Comment by AnonymousNow** [comment]
TFFT.

**Comment by Cyberboss** [comment]
FUCKING FOUND IT

**Comment by TehZombehz** [comment]
Without this fix, Drones are pretty much unplayable and unsuspecting drone players can accidentally eat resources and materials and make them essentially disappear off the face of the station. Potential for griff is there (because drones already have a bad rap, I'm sure somebody's gonna take it to the next level if they discover this). The sooner this gets merged, the better. Thanks, Cyberboss.

**Comment by Cyberboss** [comment]
What happened was the manual base proc calls were overriding the newloc var, making it null. So basically instead of transferItemToLoc being called, essentially, temporarilyRemoveItemFrom Inventory was being called. AND I EXPLICITLY STATED IN #22918 THAT THAT PROC WAS DANGEROUS

**Comment by TehZombehz** [comment]
You meme.

**Pull request merged**
