### PR TITLE
Less laughing from trace nitrous

### PR DESCRIPTION
**Pull request by Swiftfeather**
## About The Pull Request

Re-open of #80808 post embargo

I've increased the minimum amount of n2o required in the air to cause giggling. Threshold is still well below the para and sleep values. 

This should stop people randomly getting drugged and giggly from trace amounts of gas.

I'm not gonna lie I had no idea how to fully dial this in, so the numbers are an arbitrary ~~10x increase from .01 mol to .1 mol~~ 8x increase from .01 mol to .08 mol. 

## Why It's Good For The Game

After "extensive" real life testing I've determined that giggling and euphoria from trace amounts of the gas is unrealistic.

Also it would be a lot less annoying. @Cheshify also called it qol so I'm sticking with that. 

220f1c0470cef181192facef1374bf5c

## Changelog
:cl:
qol: Increased threshold of trace n2o required to make euphoria and giggles happen.
/:cl:

### CODE REVIEW

**Comment by Profakos** [comment]
The N2O laced air tank will also require an update, as its right now set at 0.05 mol.

**Comment by GuillaumePrata** [comment]
The clown internals will need to have it's mix recalculated too.

Good change tho.

**Comment by Swiftfeather** [comment]
> The N2O laced air tank will also require an update, as its right now set at 0.05 mol.


> The clown internals will need to have it's mix recalculated too.
> 
> Good change tho.

Will make the changes when I get back to computer.

**Comment by Swiftfeather** [comment]
> > The N2O laced air tank will also require an update, as its right now set at 0.05 mol.
> 
> > The clown internals will need to have it's mix recalculated too.
> > Good change tho.
> 
> Will make the changes when I get back to computer.

I comprehend breath code far less than I'd like. At the default .05 concentration on clown internal, giggling and drugginess worked as intended but only for a short time, increasing the amount in the can caused insta sleeps even with lower regulator pressure (default set to 20kpa, any lower than 17 and the o2 pressure likely drops below 16 causing oxyloss). I dropped the N2O threshold down to 0.08 and found the clown internals worked as intended with no changes necessary. 

image

**Comment by GuillaumePrata** [comment]
> I comprehend breath code far less than I'd like

I just did an eyeball guess and checked if the value worked when I did the internals, so don't worry too much about it.

Personally, I don't think it is good to have optimized internal tanks, let players improve their own internals in round if they want, so if it works well enough shift start that is all that matters.

**Pull request merged**
