### PR TITLE
Some adjustments to the new vision code

### LINKED ISSUE #15268: Teleporter accident can KO you permanently
rev 978b0fafaf89b070f37f8722803c7309ecaa0735 

reproduce:
- use teleporter until you turn into a fly
- be weakened/stunned/KO for all eternity "You feel weak." xInfinity

### PR DESCRIPTION
**Pull request by phil235**
- I renamed some of the new adjust procs and create new ones for eye_blind,eye_blurry and eye_stat so they get three procs just like weakened/sleeping/etc.. (Sleeping, AdjustSleeping, SetSleeping)
- renamed the eye_stat var to eye_damage.
- mob/on_varedit() added. Manually var editing a mob's eye_blind var properly updates his vision.
- I removed update_vision_overlays(), we now just update the relevant fullscreens instead of all fullscreens whenever one needs to be updated.
- fixed climbing into mecha not giving you mecha sight.
- simplified and removed copypasta from update_tinttotal() (now update_tint() )
- Fixes radiation never going down when above 100. fixes #15268

### CODE REVIEW

**Comment by neersighted** [comment]
You're gonna want to change cryo to use the `SetSleeping` proc I think (unrelated note however).

**Comment by freerealestate** [comment]
i don't suppose light will ever not show on the opposite side of walls, giving away people hiding in maint

**Comment by phil235** [comment]
@neersighted Why SetSleeping? if some mob in cryo has a super high sleeping var (from reagents let's say) then the cryo shouldn't make him wake up sooner.

**Comment by neersighted** [comment]
Mkay.

**Pull request merged**
