### PR TITLE
Adds elite hardsuit inhand and fixes syndie hardsuit inhand.

### PR DESCRIPTION
**Pull request by StoneMason**
## About The Pull Request

The syndicate elite hardsuit currently uses the normal syndicate hardsuit inhand sprite. It now has its own inhand sprite.

image

image

image

The normal syndicate hardsuit would clip through someone's backside, so it has been adjusted for just the single pixel showing inbetween the legs. 

image

image

## Why It's Good For The Game

Nukies will now carry a black elite hardsuit instead of a red elite hardsuit. 
The normal syndicate hardsuit will no longer break the laws of physics.

## Changelog
:cl:
fix: Fixes the syndicate hardsuit clipping through people.
imageadd: Adds the syndicate elite hardsuit inhand icon.
/:cl:

### CODE REVIEW

**Review by Twaticus — CHANGES_REQUESTED** [review]
clothing_lefthand.dmi
syndie hardsuit left directional offset
syndie_elitehardsuit back directional offset, left directional offset

clothing_righthand.dmi
syndie hardsuit right directional offset
syndie_elitehardsuit front directional offset, right directional offset

**Review by Twaticus — APPROVED** [review]

**Comment by StoneMason** [comment]
woops

**Comment by StoneMason** [comment]
fuck i'll just do this and the other PR in a later PR

**Comment by Mothblocks** [comment]
your git fu is weak

**Comment by StoneMason** [comment]
Damn... Shit cuts deep

**Pull request closed without merging**
