### PR TITLE
Lets RD/Engineering build a second mining base, drop it on lavaland

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
:cl: Kor
add: There is a hideous new tumour of a room on metastation, connected to toxins maint.
add: There is a hideous new tumour of a room on boxstation, just above the chapel.
add: These rooms contain an area to build a new mining base, as well as a targeter allowing you to designate a landing point for said base (the landing point must be on lavaland).
/:cl:

### CODE REVIEW

**Comment by GunHog** [comment]
heavy-breathing-fat-cat-meme-gif

**Comment by francinum** [comment]
@KorPhaeron Can we get some pictures?

**Comment by MMMiracles** [comment]
@francinum imagine boxstation, but then someone out-boxed boxstation by putting a giant box ontop of it.

**Comment by GunHog** [comment]
So, on the first test merge, I set it to the mining base by accident, the mining shuttle left parts of itself on the colony, and when I LAUNCHED the colony, it wiped out the mining base, spaced a LOT of people, and REALLY ticked off the miners. 

Some recommendations based on the round I ruined:
- Make it a LITTLE smaller
- Maybe give it some walls so the whole atmos does not flow out as soon as it lands
- Do not let it drop in/around ruin or station areas (TIM EBOW AS NOT PLEASED ABOUT THAT)
- Consider a tiny fan or two for the airlocks
- Consider a minimal set of stuff, like an APC, security camera on the control pillar, air alarm or such.

**Comment by KorPhaeron** [comment]
Will add checks to make sure it doesn't land on stuff yeah.

It seems largely ignored both on sybil and basil though, so I don't think it will be worth finishing the pr

**Comment by GunHog** [comment]
That might change if it is improved. The location is a bit unfortunate, as very few people will see it, but I guess that cannot really be helped much. If the colony could be dropped as is without all the atmos escaping and killing everyone, it might be a bit more workable. 

It might not be compatible for Sybil thanks to its super short rounds, but Basil lends itself well to base building. It would be quite a hoot to move Research to the colony. It certainly would not be used every round, but would be ultra fun when it is. Do not give up on it so soon, Kor.

**Comment by KorPhaeron** [comment]
It's honestly too big to be a sometimes thing, is the biggest issue

**Comment by GunHog** [comment]
It is a little too big entirely!  Consider shrinking it to 1/4 its current size, and that would let you move it to someplace more accommodating as well. There only needs to be enough room to fit a few crew members, their chosen machines (Science, Autolathe, medical machines, atmos devices, etc). If you give it walls and an APC, with a tiny fan on the entrance, it will be accessible. The need to build the walls and basic structure is too intimidating to the average speeseman. 

I think shrinking it down and giving it the basics would it much more interesting and popular.

**Comment by WJohn** [comment]
If this is purely a test for being able to build shuttles or whatever at very high speeds with in game tools and mechanics, then that's fine. But please for the love of god do not merge that room holy hell.

**Comment by Robustitron** [comment]
The idea is really cool but you might want to make it require bridge authorisation or something, so someone doesn't immediately send the construction slab to space along with 30 people again.

Also after it launches the chapel then has 3 doors directly to space, might want to shut blast doors on launch to seal t

**Comment by Jordie0608** [comment]
Oh geez it's hideous.
capture

**Comment by francinum** [comment]
Can we have the area power requirement var set to one so it takes atmos and power equipment?

**Comment by KorPhaeron** [comment]
I can make it smaller but I can't really make a big empty box to build in prettier

**Comment by WJohn** [comment]
Huge :-1: on the box room. Simply not okay.

**Comment by KorPhaeron** [comment]
Map me a better one please

**Comment by Niknakflak** [comment]
It's super ugly yea

**Comment by evsey9** [comment]
Its ugly.

**Comment by PKPenguin321** [comment]
It does not need to be that big at all. I was expecting R&D lab size, maybe smaller

**Comment by Core0verload** [comment]
Make it just an area in space, maybe marked with lattices or plating turfs.

**Comment by Jalleo** [comment]
@KorPhareon move the one on box to the empty space behind tcomms that is enough room there for it.

**Comment by GunHog** [comment]
@KorPhaeron If this does not inspire you to continue improving this project, nothing will: https://tgstation13.org/phpBB/viewtopic.php?f=2&t=53&p=199941#p199941

**Comment by Bawhoppen** [comment]
this is a little wonko

**Comment by Dorsisdwarf** [comment]
Name all the doors you nerd Kor. 
I might sprite you a DROP sign so people can find it

**Comment by KorPhaeron** [comment]
I have not seen it used even once since test merging, other than the half finished screenshot gunhog posted.

Not worth having a large area for something that is never used (the courtroom already fills that niche)

**Comment by Dorsisdwarf** [comment]
Replace the courtroom with a mini-this

**Comment by Hatfish** [comment]
This would actually be a great feature for bagil, since the rounds there can often go on for 2-3 hours the crew has much more free time to devote to something like this.

**Comment by GunHog** [comment]
Could you please keep and improve the code for this, Kor? The mapping can be worked out and improved, but it needs the code to work.

**Comment by ike709** [comment]
I'd use it when I roll engineer and don't have any explosions to fix. Building space slides gets old.

**Comment by GunHog** [comment]
@KorPhaeron could you remove the map bits and merge the code part? I am going to request the map changes from @WJohn, but he needs the code in place first.

**Comment by WJohn** [comment]
I'd be willing to map this in properly, yeah. There's a nice empty spot on metastation's arrivals with the construction area, so that can be easily converted to this. I can do some placement changes on box to make room for that, too.

**Comment by Bawhoppen** [comment]
do not fucking ruin that construction area for some shitty meme mining base, that construction area is used all the time by players for all sorts of projects

**Comment by WJohn** [comment]
so how exactly is changing a construction area into a construction area a bad thing

**Comment by Bawhoppen** [comment]
that construction area is extremely broad use, some snowflake mining base construction area will be a huge limit on what you can do

**Comment by Hatfish** [comment]
Maybe make the launch console into a thing you can build and have the room be double-purpose?

**Pull request closed without merging**
