### PR TITLE
Moved CentComm Station To The Left

### LINKED ISSUE #23077: The "asteroid with engines on it" shuttle is too big for new Centcom
image

### PR DESCRIPTION
**Pull request by JohnTheDonut**
## **Moved CentComm Station**
Moved the CentComm station to the left to prevent large shuttles and possible players on the shuttle from being clipped off the right side of the map due to the lack of docking room. Effects when the shuttle lands and you are clipped off because of the lack of docking space are still unknown but this PR should prevent that.

## **Changelog**

:cl: 
Fix: Moved The CentComm station 6 tiles to the left in order to prevent large shuttles such as "asteroid with engines on it" from clipping off the end of the right side of the map.
/:cl:

### CODE REVIEW

**Comment by Cyberboss** [comment]
Your PRs are beautiful, never stop ❤️

**Comment by Mervill** [comment]
Does underlining/formatting the fix like that still auto-close the issue?

**Comment by Thunder12345** [comment]
_...it's just a jump to the left..._

**Comment by Tofa01** [comment]
@Mervill Hmm that is a good question i am not very sure

**Comment by ChangelingRain** [comment]
It does yes; as long as there's a `Fixes #####` string somewhere in the pr body or commits, it'll be closed.

**Comment by Haevacht** [comment]
No actually do stop you;re making us all look unprofessional (which most of us are)

**Comment by Tofa01** [comment]
@Haevacht Sorry that would be impossible, its like asking the station engineers of the shift to **not** release the Tesla or better yet the Singularity during the shift.

**Pull request merged**
