### PR TITLE
De-souls RCD Radials

### PR DESCRIPTION
**Pull request by unit0016**
## About The Pull Request
Updates the RCD's Radials to the current-day sprites. I had originally planned to implement firelocks, reinforced glass tables, and ladders while I was in here, but my GBP is at a deficit. Honk.

image

Also standardizes the size of the furnishing the the rest of the objects! And fixes the windoors having extraneous icon states.
image

## Why It's Good For The Game
An embarrassing amount of people don't even know the RCD *can* have custom access limitations applied to airlocks. Or different designs. Or reinforced windows. Or that electronics upgrade let you do everything a cyborg's electroadaptive psuedocircuit does.

Updating the sprites just a smidge probably won't help with that, but maybe it will for one or two people.

## Changelog

:cl:
imageadd: RCDs' Radial Menu new uses the updated Chairs, ID Cards, Stools, and Walls. 2562.
/:cl:

### CODE REVIEW

**Comment by Fikou** [comment]
the chair/table modes really need smaller sprites, they are ginourmous when stuff like pcs and machines are sized down

**Comment by unit0016** [comment]
> the chair/table modes really need smaller sprites, they are ginourmous when stuff like pcs and machines are sized down

I'll give it a try, shouldn't be too hard.

**Comment by unit0016** [comment]
Complete! Did some cleanup while I was in there.

**Comment by zxaber** [comment]
Are the furniture options in the base RCD, or just in an upgrade? I don't hate the idea of an RCD to layout furniture quickly, but it seems a bit bloated.

**Comment by unit0016** [comment]
> Are the furniture options in the base RCD, or just in an upgrade? I don't hate the idea of an RCD to layout furniture quickly, but it seems a bit bloated.

This isn't new content, they're a pre-existing upgrade

**Pull request merged**
