### PR TITLE
Admins are no longer kicked from lobby on reboot

### PR DESCRIPTION
**Pull request by Cyberboss**
I'M DEBUGGING, STOP KICKING ME

### CODE REVIEW

**Comment by lzimann** [comment]
You are only kicked if you are AFK AND in the lobby.

**Comment by MrStonedOne** [comment]
I see you now take bribes from @kevinz000

**Comment by lzimann** [comment]
Also when the server reboots, the AFK tracker resets, which means for a few minutes it will look like there is an admin active when there is not.

**Comment by Cyberboss** [comment]
I'll dig up some shit to track afks across reboots

**Comment by PKPenguin321** [comment]
Idlemin pandering

**Pull request closed without merging**
