### PR TITLE
Soul Vessels can now be used similarly to soulstones

### PR DESCRIPTION
**Pull request by ChangelingRain**
:cl: Joan
rscadd: Soul Vessels can now be used on unconscious or dead humans to extract their consciousness, much like a soulstone.
tweak: Soul Vessels no longer automatically ping ghosts when created, though they can still be used in-hand to ping ghosts.
/:cl:

### CODE REVIEW

**Comment by anconfuzedrock** [comment]
why does cock cult have to be better than nar nar in EVERY way

**Comment by ChangelingRain** [comment]
This isn't strictly better, because the target has to have no head-covering objects on and it doesn't make equipment immediately accessible.

Also, you can't release the soul vessel as a shade, and it can already be used in-hand to draw in ghosts. This is more or less specifically corpse denial and something to make ratvar cult feel less like it's The Good Cult.

**Comment by anconfuzedrock** [comment]
>not better because you need to take off the dead target's hat
are you shitting me

**Comment by ChangelingRain** [comment]
Soulstones are instant if the target is unconscious, immediately unequip objects, and don't leave a corpse.
Time is valuable, ya butt.

**Comment by francinum** [comment]
But, why?

**Comment by Chocobro** [comment]
@ChangelingRain 
been wondering
are soul vessels literally the ones from dark souls
http://darksouls2.wiki.fextralife.com/Soul+Vessel

**Comment by ChangelingRain** [comment]
No they're just clockwork posibrain/soulstone things that happen to share a name with those

**Pull request merged**
