### PR TITLE
Removes the overthrow gamemode

### PR DESCRIPTION
**Pull request by kriskog**
## About The Pull Request
Begone, dead bounty code. Has this even been run once since it was taken out of rotation?

## Why It's Good For The Game
Code cleanup

## Changelog
:cl: Skoglol
del: Removed the overthrow gamemode.
/:cl:

### CODE REVIEW

**Comment by FancyCyclops** [comment]
Finally, a game mode removal people can agree on!

**Comment by Shadowflame909** [comment]
The game mode is fucking bugged as well.

**Comment by daklj** [comment]
hivemind next

**Comment by kriskog** [comment]
Funny you should say that

**Comment by knacker48** [comment]
I didn't even know this was a game mode. What was it even about?

**Comment by actioninja** [comment]
It sucks and is bad.

**Comment by necromanceranne** [comment]
So underdeveloped. High potential. No payoff. Truly a tragic loss.

**Comment by GuppyLaxx** [comment]
r*tarded cash grab gamemode made for the old code bounties for "new!!" and "original!!!" gamemodes

**Comment by actioninja** [comment]
I hate this game mode a lot.

**Pull request merged**
