### PR TITLE
all the base NT tech is now one node

### PR DESCRIPTION
**Pull request by Fikou**
## About The Pull Request

the mmi, mecha tools, cyborg etc tech nodes are now a part of the base one

## Why It's Good For The Game

theres no reason for them to be separate when they are all unlocked at the start

## Changelog
:cl:
tweak: all the base nanotrasen tech is now in one node
/:cl:

### CODE REVIEW

**Comment by ArcaneMusic** [comment]
Nerf to traitors with the steal x tech nodes objective

**Comment by Tlaltecuhtli** [comment]
who even does that boring rng decided objective

**Comment by itseasytosee** [comment]
why?

**Comment by TheVekter** [comment]
This doesn't really change much, it just makes everything start under a single node for simplicity's sake.

**Comment by Bawhoppen** [comment]
This is less flavorful and there's no practical reason to change it

**Comment by ExcessiveUseOfCobblestone** [comment]
I can only see the practical use of this being used to diminish the tech node obj and we're still under the freeze.

**Comment by Fikou** [comment]
> I can only see the practical use of this being used to diminish the tech node obj and we're still under the freeze.

getting 5 more tech nodes isnt gonna change anything really and theres literally no reason for all things to not be under the BASE node since it is the BASE node, it already includes half of the roundstart stuff so why not have all?

**Comment by XDTM** [comment]
They're technically superfluous, but they divide the starting techs in different categories instead of an unreadable lump of stuff. So it's about readability, mostly, both in code and in game.

**Comment by Fikou** [comment]
> They're technically superfluous, but they divide the starting techs in different categories instead of an unreadable lump of stuff. So it's about readability, mostly, both in code and in game.

it should be split to more technodes then, since half of the stuff is in base node anyway

**Comment by XDTM** [comment]
If that's the case i'd split off the remaining base clump instead then

**Comment by ExcessiveUseOfCobblestone** [comment]
> getting 5 more tech nodes isnt gonna change anything really

correct, which is why I locked the PR for an antag change since it does change the starting ones for the purpose of the obj.

Unless there's a practical reason that's beyond the antag change that's worth ignoring the antag change, It's gonna be blocked per the freeze.

**Comment by Fikou** [comment]
ok i guess i will reopen this after the freeze

**Comment by Fikou** [comment]
antag freeze is over 🦀

**Comment by kriskog** [comment]
This is pretty pointless, as others have said earlier is better as separated nodes for readability and editing.
I wouldnt mind if you put all the robotics nodes into one though, we dont need four nodes for a single department.

**Comment by ExcessiveUseOfCobblestone** [comment]
if you wanna do ^, do it in a different PR

**Pull request closed without merging**
