### PR TITLE
Rework of adv egun failure mechanic

### PR DESCRIPTION
**Pull request by Jordie0608**
Changes advanced eguns to only critically fail when they fail after multiple recent minor fails. Minor failures increase fail_tick, fail_tick is reduced every process(), critical failures only occur when fail_tick is above 200.
Reduces the radiation given by failures and make them only irradiate the user.

### CODE REVIEW

**Comment by GunHog** [comment]
I cannot agree with this. Forcing a critical failure is a slow, but significantly less costly way of perfecting the weapon for practical use. I believe this change makes the crit-fail method of perfecting the weapon impractical. :-1:

**Comment by Jalleo** [comment]
How about having critical failures start low for the first gen and after some deconning of critical failures it has increased to at least 200 or even higher.

**Comment by GunHog** [comment]
Deconning a crit failed one makes the next gun you make in the proto perfect, all the time. This is a cheaper alternative to deconning 3-5 of the things instead.

**Comment by Jordie0608** [comment]
@GunHog I don't see how this makes it any less practical to force a critical failure, it's still possible to just fire the gun until it fails or emp it enough to ensure it fails critically. Removing one of the probability checks makes it a more linear process too.

**Comment by GunHog** [comment]
But *how long* will this take? I am worried about this making the average time to break it take significantly longer. Only a fool or desperate player would consider using one of these without perfecting it first. If it does not hurt the average time to break the gun, this is fine.

**Comment by AlexCrimson** [comment]
Wasnt reliability removed?

**Comment by Jordie0608** [comment]
@AlexCrimson No

@GunHog 
1 reliability
3 shots (six times)
avg 3 shots

50 reliability
7 shots
9 shots
9 shots
9 shots
7 shots
8 shots
avg 8 shots

76 reliability
17 shots
22 shots
10 shots
34 shots
28 shots
16 shots
27 shots
18 shots
20 shots
23 shots
20 shots
19 shots
avg 21 shots

**Pull request merged**
