### PR TITLE
Revert "Adds mentorhelp"

### PR DESCRIPTION
**Pull request by lzimann**
Reverts tgstation/-tg-station#16308

baw the guy that killed ahelp

### CODE REVIEW

**Comment by TechnoAlchemisto** [comment]
BEEP BEEP

**Comment by PKPenguin321** [comment]
bwoink

**Comment by Bawhoppen** [comment]
IM MAKING A FIX YOU BITCH HOLD ON

**Comment by TechnoAlchemisto** [comment]
BEEP BEEP

**Comment by TechnoAlchemisto** [comment]
@Bawhoppen  BEEP BEEP

**Comment by lzimann** [comment]
make it named adminhelp because it changed button positions and IT BOTHERS ME A LOT(or readd adminhelp)

**Comment by Bawhoppen** [comment]
ADMINHELP WAS NEVER SUPPOSED TO DISAPPEAR
IT WAS THERE WHEN I TESTED

**Comment by Bawhoppen** [comment]
LOOK ITS HERE WHEN I COMPILE IT http://puu.sh/nT6rP/7b751072ab.png

**Comment by lzimann** [comment]
admin pm is an admin button that let's us send messages to people

**Comment by lzimann** [comment]
uh i closed by mistake but w/e since you are actually fixing it

**Comment by Shadowlight213** [comment]
FIXITFIXITFIXITFIXIT

**Comment by Bawhoppen** [comment]
ok actually we should revert this Ihave no idea whats going on

**Comment by Iamgoofball** [comment]
# 24 HOUR WAIT PERIOD

**Comment by Iamgoofball** [comment]
# WOOOOOOOOOOOOOOOOOOWW

**Pull request merged**
