### PR TITLE
Cake hats now properly emit light.

### PR DESCRIPTION
**Pull request by harmonyn**
Fixes https://github.com/tgstation/-tg-station/issues/11864.

someday if we all believe we can get below 800 issues

### CODE REVIEW

**Comment by freerealestate** [comment]
In the words of Jimbo Wales,

"If everyone watching this repository fixed just 10 issues, we would have 10 issues."

**Comment by MrPerson** [comment]
You coulda also done SetLuminosity(0) but this is 100% fine.

**Comment by Aranclanos** [comment]
fix conflicts and remove the new var

**Comment by Dorsisdwarf** [comment]
@bgobandit

**Comment by bgobandit** [comment]
I AM FIXING MY SHIT STARTING WITH THIS

**Pull request merged**
