### PR TITLE
changes explosive implant death signalling

### PR DESCRIPTION
**Pull request by silicons**
versus
emote("deathgasp") --> on_mob_death()

### CODE REVIEW

**Comment by Repukan** [comment]
I ded pls nerfe

stop coding out every single thing that kills you

**Comment by lzimann** [comment]
Can't see a problem with triggering on *deathgasp if you can trigger with an action button already

**Comment by kevinz000** [comment]
@Repukan ill close this if you tell me in what way a shaft miner walking into a team of ops and saying two words and them all blowing up with no way to counter other than removing everyone's implants is balanced in any way shape or form

oh yeah no "only 3 people can kill it before the 15 minute mark" colossus is one of the easier bosses that isn't a valid argument

gamemodes should never be "do i have <person> on my team if so i win yay"

**Comment by kevinz000** [comment]
@lzimann miner with VOG walks up in warops and 420 TC of equipment are nulled by explosive implants.

**Comment by Repukan** [comment]
>What are earmuffs

**Comment by kevinz000** [comment]
something the ops don't start with?

**Comment by kevinz000** [comment]
also what you expect every op team to metagame and put on earmuffs if they see a staticnamer on mining or anyone they don't know is 100% incompetent?

**Comment by ChangelingRain** [comment]
Fix voice of god, then, instead of probably breaking some edge cases.

**Comment by Repukan** [comment]
War Ops is essentially telling all powergamers on station that a bunch of very well equipped valids are gonna come to bust your shit. A maxcap can kill everyone too, so can many other things that require much less effort and skill than killing megafauna and getting someone else to do surgery on you

**Comment by Repukan** [comment]
>also what you expect every op team to metagame and put on earmuffs if they see a staticnamer on mining or anyone they don't know is 100% incompetent?

I mean you already powergame to hell and back so you can just adjust your tactics now ;)

**Comment by kevinz000** [comment]
@ChangelingRain how would I fix it? Make its deathgasp snowflake and not trigger?
@Repukan opteams don't have earmuffs

**Comment by Repukan** [comment]
then code in earmuffs

**Comment by kevinz000** [comment]
@Repukan deafen thyself every op round just in case??? no.

**Comment by XDTM** [comment]
I thought it would never happen

**Comment by jughu** [comment]
Just say play dead trougg comms everyone deathgasps and dies

**Comment by jughu** [comment]
Besides it already has a action button so why even deathgasp

**Pull request closed without merging**
