### PR TITLE
HFR: Better observation of delta_time

### LINKED ISSUE #55983: HFR does not seem to fully observe delta_time
Opening for discussion, since there's quite a lot to go through. Please let me know if there's something obvious I'm missing!

---

Each fusion power level's `var/scaled_production` calculation can double-dip on `delta_time` whenever production is bounded by fuel injection, with unpredictable results:

```
var/fuel_consumption = clamp((fuel_injection_rate * 0.001) * 5 * power_level, 0.05, 30) * delta_time
```
```
var/scaled_production = clamp(heat_output * 1e-X, 0, fuel_consumption) * delta_time
```

A possible fix might be to split `fuel_consumption` into a `fuel_consumption_rate`, used for clamping purposes, and `fuel_consumption`, used for actually consuming fuel and producing Helium.

---

The fusion level 5 and 6 responses to Healium differ.

Level 5:
```
critical_threshold_proximity = max(critical_threshold_proximity - (m_healium / 100), 0)
moderator_internal.gases[/datum/gas/healium][MOLES] -= min(moderator_internal.gases[/datum/gas/healium][MOLES], scaled_production * 20)
```
Level 6:
```
critical_threshold_proximity = max(critical_threshold_proximity - (m_healium / 100), 0)
moderator_internal.gases[/datum/gas/healium][MOLES] -= min(moderator_internal.gases[/datum/gas/healium][MOLES], scaled_production * 20) * delta_time
```

Both provide a fixed amount of healing per update, based on the amount of Healium in the moderator. Level 6's response can also up to triple dip on `delta_time` when consuming Healium, since `scaled_production` can already use `delta_time` as a factor twice.

---

Level 5's Antinoblium production produces a fixed amount of Antinoblium per update, based on the proportion of Helium in the fusion mix:
```
internal_output.gases[/datum/gas/antinoblium][MOLES] += 0.1 * (scaled_helium / (fuel_injection_rate * 0.0065))
```
---
General moderator gas consumption removes each type of gas at a fixed proportion per update, based on `power_level`:
```
moderator_internal.remove(moderator_internal.total_moles() * 0.0005 * power_level)
```
---
Waste removal also ignores `delta_time`:
```
                if(filtering && moderator_internal.gases[filter_type])
                        var/datum/gas_mixture/removed = moderator_internal.remove_specific(filter_type, 20)
                        removed.temperature = moderator_internal.temperature
                        linked_output.airs[1].merge(removed)

                var/datum/gas_mixture/internal_remove
                if(internal_fusion.gases[/datum/gas/helium][MOLES] > 0)
                        internal_remove = internal_fusion.remove_specific(/datum/gas/helium, internal_fusion.gases[/datum/gas/helium][MOLES] * 0.5)
                        linked_output.airs[1].merge(internal_remove)
                if(internal_fusion.gases[/datum/gas/antinoblium][MOLES] > 0)
                        internal_remove = internal_fusion.remove_specific(/datum/gas/antinoblium, internal_fusion.gases[/datum/gas/antinoblium][MOLES] * 0.05)
                        linked_output.airs[1].merge(internal_remove)
```
---
Random radiation and hallucinations also ignore `delta_time`, if we should care about that.

### PR DESCRIPTION
**Pull request by esainane**
## About The Pull Request

This changes HFR's fusion_process() to better observe delta_time.

Resolves #55983.

## Why It's Good For The Game

The HFR process becomes (slightly) more predictable.

## Changelog
:cl:
fix: Many HFR reactions and processes no longer change their behaviour based on the amount of space lag.
/:cl:

### CODE REVIEW

**Comment by LemonInTheDark** [comment]
I have some concerns about delta_time in atmos procs in general, I'll leave a longer form comment on the issue itself, but in short gas flow itself can't be limited in such a way, so it would cause changes in behavior if wait were to ever change, instead of the two systems scaling together. Also worth noting that in this case, delta_time is literally just the wait of the air ss times 0.1 (5 * 0.1), which is a static value.

Separate from all that, this looks like a good conversion at first glance, even if I dislike delta_time in atmos procs, it should be consistent where it is used.

**Comment by LemonInTheDark** [comment]
Fix the conflicts and we'll be good

**Comment by esainane** [comment]
Newly rebased for that fresh minty scent

**Comment by LemonInTheDark** [comment]
mmmmm smells like the mountain air.

**Pull request merged**
