### PR TITLE
New Max and Gib gang tags

### PR DESCRIPTION
**Pull request by ChangelingRain**
maximum
gibbing

### CODE REVIEW

**Comment by PKPenguin321** [comment]
what is "Max" even referring to

**Comment by Lumipharon** [comment]
V8 gang when?

**Comment by bgobandit** [comment]
The Mesons when

**Comment by Ricotez** [comment]
> The Mesons when

please, and make their tag that stupid pyramid but with meson goggles instead of an eye

**Comment by Anonus** [comment]
Fuck if I know what the name means, I just make the sprites.

**Pull request merged**
