### PR TITLE
Added staffs of teleportation, fireball, and death (sprites by WJohn)

### PR DESCRIPTION
**Pull request by Buggy123**
These are all admin-spawn only, which is good considering that a staff of fireball is incredibly powerful, and a staff of death is second only to the instagib rifle. The staff of death and fireball use the staff of storms sprite by WJohn, while the staff of teleportation uses the staff of nothing sprite.

### CODE REVIEW

**Comment by Boredone** [comment]
You misspelled the PR title, you put Wands instead of Staff. Besides that, looks fine to me.

**Comment by Buggy123** [comment]
I swear i do that every time.

**Comment by WJohn** [comment]
You forgot to add the inhands and back sprite for the staff of fire.

**Comment by Buggy123** [comment]
I... am honestly not sure how that works. On one hand yes I didn't but on the other hand all of the other staffs don't have those sprites either...

**Comment by WJohn** [comment]
Uh, they definitely have inhands I've seen all of them in game. I know that wands use a generic wand sprite, but the staves are all unique.

**Comment by Buggy123** [comment]
I agree but I can't find the inhand/back sprites anywhere.

**Comment by Zilenan91** [comment]
I wouldn't mind seeing the staff of fireball as an actual fireball alternative if you want more freedom in aiming it. Though it should probably have some sort of cooldown attached to firing it, like 1 shot refreshed every 6 seconds.

**Comment by Buggy123** [comment]
That's probably beyond the scope of this PR, but I like the idea. Do you mean it can only hold 1 shot which recharges, or that it acts like other staffs which can hold ~10 and fire them off rapid before having to recharge?

**Comment by Zilenan91** [comment]
Probably only 1 charge with a 4 or 5 second recharge time (because it can be disarmed) with the ability to aim it freely.

**Comment by Buggy123** [comment]
Sounds good, I might do something like that in another PR if i can figure out how the multiple buys=reduced cooldown thing works. I could let you buy it multiple times for less of a cooldown.

**Comment by GunHog** [comment]
Pics plz k thx lol

**Comment by Zilenan91** [comment]
Ehh I don't think the staff of fireball, if it would ever be made, should be upgradable. Staffs of Chaos and Gem Hardsuits aren't upgradeable, and it would already be a good item on its own.

**Comment by WJohn** [comment]
Gunhog is already likely going to make fireball something you can aim, so this staff may not be necessary in the wizard's arsenal. Maybe it'll have to have no cooldown, but with the downside of being possible to lose it.

**Comment by Razharas** [comment]
>No pics

**Comment by Buggy123** [comment]
Here are the three staffs: http://i.imgur.com/UuHgY9A.png

They don't have inhands, but apparently neither does the staff of teleportation, and that uses the same sprites as the staff of nothing.

I'd be happy to add the inhands but I don't actually see any possible way to do it.

**Comment by KazeEspada** [comment]
Buggy, that pic only has 2 staffs in it, and one is the staff of nothing.

**Comment by Buggy123** [comment]
They re use sprites, I said this. I can't sprite and I only have 1 unique sprite to work with. The staves in that picture are the staves of death, fireball, and teleportation.

The staffs of death and fireball use the same sprite because it suits them, the wand of teleportation uses the staff of nothing sprite because it has vaguely the same sort of color scheme as the wand of teleport

**Comment by WJohn** [comment]
I thought it was agreed that the staff of death was supposed to use the scythe sprite. Also I never sprited a staff of teleportation. I won't be able to get it to you for a little while because internet.

**Comment by Buggy123** [comment]
Alright, I'll change the staff of death back to the scythe sprite.

**Comment by KorPhaeron** [comment]
@Buggy123

**Comment by Buggy123** [comment]
I was waiting until @WJohn finishes that staff of teleportation sprite...

**Comment by KorPhaeron** [comment]
@WJohn 

Let me know when you are back and ready to help him finish this

**Pull request closed without merging**
