### PR TITLE
Minor speedups to movement: First Blood Part 2

### PR DESCRIPTION
**Pull request by vuonojenmustaturska**
Local man opens new PR after ruining the previous one with git UI tools

Squash before merge, the history is all sorts of fucked up.

[Changelogs]:

:cl: Naksu
tweak: Minor speedups to movement processing.
change: Fat mobs no longer gain temperature by running.
/:cl:

### CODE REVIEW

**Comment by vuonojenmustaturska** [comment]
This is a semi-unfucked version of #32568

**Comment by nicbn** [comment]
> Fat mobs no longer gain temperature by running.

Why

**Comment by XDTM** [comment]
Because it was an if check on every single mob step, it adds up

**Comment by DoctoreMad** [comment]
Well that's a valid reason to remove it but I certainly hope it comes back later with less shitcode.

**Comment by vuonojenmustaturska** [comment]
but why? I could break movement for fat people and we'd only notice maybe a month from now, when a newbie starts ranting in OOC about bugged gluttony ruin

**Pull request merged**
