### PR TITLE
Increases arena shuttle cost

### PR DESCRIPTION
**Pull request by evsey9**
having a cheap murderbone crew wiping shuttle that doesnt even fit into the game is dumb. the price is one million now.
why?
its a fucking free for all murderbone shuttle

### CODE REVIEW

**Comment by evsey9** [comment]
what why

**Comment by BeeSting12** [comment]
100000 is acceptable. A million is fucking ridiculous and will never happen ingame.

**Comment by evsey9** [comment]
ok fine i'll change it but for what reason was this closed

**Comment by praisenarsie** [comment]
that and the fact you have to talk to a headmin about shuttles since they are enabled/disabled through the server/remote

**Comment by praisenarsie** [comment]
and you have to kill bubblegum for the shuttle so lol

**Comment by evsey9** [comment]
if you have a good miner then it won't be hard, and 10k is very easy to get

**Comment by evsey9** [comment]
@KorPhaeron why was this closed

**Comment by KorPhaeron** [comment]
Because you got mad about dying in a shuttle that is rarely purchased and lazily made it cost an absurd amount to try and remove it

Also yes, that these are all config side and traditionally added/removed by head admins

**Comment by evsey9** [comment]
No its not an "I ded"
I wasn't ANYWHERE near the shuttle the round I posted this PR

**Comment by evsey9** [comment]
Also, why would a murder shuttle cost THAT low?

**Pull request closed without merging**
