### PR TITLE
Adds a chance of clowns spawning with bananium

### PR DESCRIPTION
**Pull request by kriskog**
## About The Pull Request
Adds a 1/5 chance that clowns spawn with a single sheet of bananium in their backpack. Not nearly enough for a honk mech or anything really useful, but allows a lucky clown to go print an air horn or a clown borg module once in a while.

## Why It's Good For The Game
Bananium is fairly rarely seen brought back from mining/space, this single sheet could bring some clown variety. Hopefully.

## Changelog
:cl: Skoglol
add: Particularly lucky clowns might now find a sheet of bananium in their backpack.
/:cl:

### CODE REVIEW

**Comment by nemvar** [comment]
Make the bananium implanted in their cavity and we have deal

**Comment by Arathianen** [comment]
I think there should be some ways to gather bananium as clown, but random chance on spawn ain't it.

Maybe there should be some way for people to "approve" of a clown (because le funny clown meymeys) to give him a small amount of bananiun. So a popular clown would gather bananium.

Irono, just spitballing ideas here.

**Comment by bgobandit** [comment]
the clown must earn bananium not have it handed to him

as a clown main: 👎

**Comment by HomocidlePancakes** [comment]
Rare stuff is fun because it’s rare. Make it more common and it suddenly looses it’s appeal.

**Comment by 4dplanner** [comment]
> the clown must earn bananium not have it handed to him

Having it handed to you by miners is still having it handed to you, eh?

**Comment by wesoda25** [comment]
give clown puzzle cube, solve puzzle cube for bananium

**Comment by FantasticFwoosh** [comment]
But courtesy of the HOP there are unlimited clown slots.

**Comment by optimumtact** [comment]
no

**Pull request closed without merging**
