### PR TITLE
Firefighting Foam

### PR DESCRIPTION
**Pull request by DaedalusGame**
:cl:
add: Firefighting Foam reagent, better alternative to water and corn oil for firefighting purposes
/:cl:

Requested by @KomradeSpectre 

- It's made from stabilizing agent, carbon and fluorosurfuctant at 200 K (-73 C)
- It puts out people and neutralizes firestacks if you spray it or splash it on people
- It creates foam that doesn't spread on applying to a turf
- The foam goes away faster than ordinary foam
- The foam extinguishes people and reduces firestacks.
- The foam extinguishes fire on tiles
- The foam is not slippery
- The foam is not dissipated in heat
- The foam absorbs plasma out of the air and normalizes temperature (Tritium is unaffected)
- The absorbed plasma is dumped on the floor after the foam fades away, but you can only scoop up stabilized plasma.
- It doesn't go in foam (it won't make foam that lingers), but it can go in smoke or dispersed directly with splashes or spraybottles

Foam code is an abomination but I think refactoring it should be saved for a non-feature pr.
Also Extinguishers can't be filled with this (yet?) because something about spraybottles being too good.

### CODE REVIEW

**Comment by DaedalusGame** [comment]
it only absorbs the plasma if the plasma is on fire and also you can still make tritium fires (if you can ever make tritium)

**Comment by Anonmare** [comment]
I actually wanted to PR firefighting foam grenades but Atmos Resin dissuaded me.

**Comment by DaedalusGame** [comment]
yeah this is slightly worse than atmos resin, which is normally only used if atmos techs are competent (ha)

**Comment by Tlaltecuhtli** [comment]
how can i grief with this

**Comment by DaedalusGame** [comment]
idk

**Comment by Robustin** [comment]
Plasma is still just a little too easy to (ab)use for the results it produces. Open a canister and that department is done for the shift, so I support ways for the crew to fight back.

**Comment by Anonmare** [comment]
One or two fire-fighting grenades in the fire lockers might not be a bad idea, the foam's not slippery so it can't even be used for griff

**Comment by DaedalusGame** [comment]
Maybe but I'm not sure if it should be in this PR.

**Comment by Bawhoppen** [comment]
>Foam code is an abomination but I think refactoring it should be saved for a non-feature pr.

That's not going to go over well with maintainers...

**Comment by DaedalusGame** [comment]
atomic prs tbh also who broke my pr

**Comment by vuonojenmustaturska** [comment]
Tested locally and seems to work fine

**Pull request merged**
