### PR TITLE
Improves nuke op area and fixes some issues

### LINKED ISSUE #6789: Someone broke the nuke op equipment room [map]
ss 2015-01-03 at 08 49 35

Sigh

### PR DESCRIPTION
**Pull request by ghost**
syndizone

(I apologize for inconsistencies in the image; the den itself is fine, but I am bad at image editing.)
NOTE: Some elements may be missing from picture. This is because the images were taken on a test server that was running on extended, not nuclear emergency.

Issues fixed:
-Tables on the shuttle blocked access to some tools
-There is no wooden table holding the rum or drinking glasses
-The right of the ship shears off when you move places due to movement areas being one tile too small
-Half of the double-airlock to the lockers is blocked

Changes:
-The sixth locker in the cockpit has been placed adjacent to the others
-The locker room's layout has been changed slightly

Fixes #6789 
Fixes that one issue where the nuke op thing sheared off that I can't remember the number of

### CODE REVIEW

**Comment by Anonus** [comment]
I think this'll conflict with carn's thingy, won't it?

**Comment by Xhuis** [comment]
Still working on finding that out.

**Comment by tkdrg** [comment]
>  The sixth locker in the cockpit has been placed adjacent to the others

Doesn't that defeat the whole point of having that locker in the first place? I thought the idea was to help ops that forget their stuff. Also, the shearing off issue is already fixed.

**Comment by Xhuis** [comment]
I guess it's :fire: DOUBLE-FIXED :fire:
As for the other locker, I almost never see it used in the first place. I might re-add it back at some point in time if this doesn't cause a conflict, but for now it's just extra supplies.

**Comment by Xhuis** [comment]
Yeah, this conflicts, will close it for now

**Pull request closed without merging**
