### PR TITLE
Clowns can now buy the mk-honk shoes

### PR DESCRIPTION
**Pull request by ghost**
:cl:
add: clowns can now buy shoes that shit out bananas
/:cl:

### CODE REVIEW

**Comment by Tlaltecuhtli** [comment]
dont they need banarium to work

**Comment by anconfuzedrock** [comment]
top 10 ways to make a feature stale

**Comment by MACIEKBAKI** [comment]
make it so clowns can buy bananium

**Comment by optimumtact** [comment]
this is an awful pr, no offense

**Pull request closed without merging**
