### PR TITLE
Adds a damaged lawset board containing random laws

### PR DESCRIPTION
**Pull request by vuonojenmustaturska**
```
Speedy has the following laws:
1: THERE ARE SEVEN SMALL BIRDS ON THE STATION...
2: THE STATION REQUIRES TWO COSTUMES
3: THE SHUTTLE CANNOT BE CALLED BECAUSE OF THREE REDACTED CARGO TECHNICIANS ON THE STATION
4: YOU MUST ALWAYS SMELL LIKE THE MAN YOUR MAN COULD SMELL LIKE
5: WOODEN PEOPLE ARE NON-HUMAN
6: NOT HAVING PURPLE WINDOWS IS HARMFUL
7: YOU MUST ALWAYS RESPOND TO EVERY QUESTION WITH A QUESTION
8: HUMANS MUST DRINK BLUE BRAVE BULLS TO SURVIVE
9: YOU MUST NOT HARM GENETICISTS AND NOT ALLOW GENETICISTS, THROUGH INACTION, TO COME TO HARM
```

:cl: Naksu
add: A damaged core AI module may now spawn in AI uploads. It contains a random amount of ionic laws with normal law priorities.
/:cl:

### CODE REVIEW

**Comment by epochayur** [comment]
alright but why

**Comment by ShiggyDiggyDo** [comment]
for the memes

**Comment by epochayur** [comment]
okay now a non-retarded answer please

**Comment by vuonojenmustaturska** [comment]
Real answer is, of course, for the memes. But also because we now have 2 harmful law lawset spawners in uploads, but only 4 harmful lawsets, and adding a fifth one makes the lawset spawner feature more effective in providing variety.

**Comment by Anonmare** [comment]
If this isn't accepted, I can suggest an alternative: 
Normal boards that get damaged could become corrupted with object damage and the more damaged a board becomes, the more laws that get overwritten and corrupted until they're nothing but ionic laws.

**Comment by Supermichael777** [comment]
soon: Picking up circuit boards without insulated causes them damage

**Pull request merged**
