### PR TITLE
autolathe speed func is the same as protolathe

### PR DESCRIPTION
**Pull request by Tlaltecuhtli**
:cl:
tweak: autolathe and protolathe now produce items with the same speed
/:cl:

probably a typo

### CODE REVIEW

**Comment by HomocidlePancakes** [comment]
Yeah. Sure. Typo. You are doing this just so you can print ammo fot tge 10 fucking thousand sawn-off self-made shotties you wlways keep on yourself. And I like that because I am a powergaymer too.

**Comment by Daxxed** [comment]
As someone who used to main shotgun even before tasers were gone I can only upvote!

**Comment by ExcessiveUseOfCobblestone** [comment]
link to the proto time, im too lazy

**Comment by Tlaltecuhtli** [comment]
addtimer(CALLBACK(src, .proc/do_print, D.build_path, amount, efficient_mats, D.dangerous_construction), (32 * timecoeff * amount) ** 0.8)

**Comment by Daxxed** [comment]
Every tick counts for a powergamer

**Comment by ExcessiveUseOfCobblestone** [comment]
1 job

**Pull request merged**
