### PR TITLE
Revert #38412 (Virus crate change)

### PR DESCRIPTION
**Pull request by optimumtact**
"Virus crates now contain randomly generated viruses instead of single-symptom advance presets (#38412)"

This reverts commit af50573d8541235c71854f669da0481216ff47cf.

This appears to be causing atom init to fail whenever the vet ruin spawns

```
[2018-06-13 09:44:56.005] runtime error: Maximum recursion level reached (perhaps there is an infinite loop)
[2018-06-13 09:44:56.005] To avoid this safety check, set world.loop_checks=0.
[2018-06-13 09:44:56.005] proc name: timSort (/datum/sortInstance/proc/timSort)
[2018-06-13 09:44:56.005]   usr: null
[2018-06-13 09:44:56.005]   src: /datum/sortInstance (/datum/sortInstance)
[2018-06-13 09:44:56.005]   call stack:
[2018-06-13 09:44:56.005] /datum/sortInstance (/datum/sortInstance): timSort(1, 6)
[2018-06-13 09:44:56.005] sortTim(/list (/list), /proc/cmp_text_asc (/proc/cmp_text_asc), null, 1, 6)
[2018-06-13 09:44:56.005] sortList(/list (/list), /proc/cmp_text_asc (/proc/cmp_text_asc))
[2018-06-13 09:44:56.005] Experimental Disease (/datum/disease/advance/random): GetDiseaseID()
[2018-06-13 09:44:56.005] Experimental Disease (/datum/disease/advance/random): Refresh(0)
[2018-06-13 09:44:56.005] Experimental Disease (/datum/disease/advance/random): New(5, 8)
[2018-06-13 09:44:56.005] Experimental Disease (/datum/disease/advance/random): Copy()
[2018-06-13 09:44:56.005] Experimental Disease (/datum/disease/advance/random): Copy()
[2018-06-13 09:44:56.005] Experimental Disease (/datum/disease/advance/random): Refresh(0)
[2018-06-13 09:44:56.005] Experimental Disease (/datum/disease/advance/random): New(1, 8)
[2018-06-13 09:44:56.005] ...
[2018-06-13 09:44:56.005] Experimental Disease (/datum/disease/advance/random): Copy()
[2018-06-13 09:44:56.005] Experimental Disease (/datum/disease/advance/random): New(6, 8)
[2018-06-13 09:44:56.005] Experimental Disease (/datum/disease/advance/random): Copy()
[2018-06-13 09:44:56.005] Experimental Disease (/datum/disease/advance/random): New(4, 8)
[2018-06-13 09:44:56.005] Experimental Disease (/datum/disease/advance/random): Copy()
[2018-06-13 09:44:56.005] Experimental Disease (/datum/disease/advance/random): New(3, 8)
[2018-06-13 09:44:56.005] Experimental disease culture b... (/obj/item/reagent_containers/glass/bottle/random_virus): Initialize(1)
[2018-06-13 09:44:56.005] Atoms (/datum/controller/subsystem/atoms): InitializeAtoms(null)
[2018-06-13 09:44:56.005] Master (/datum/controller/master): Initialize(10, 0)
[2018-06-13 09:44:56.005] 
[2018-06-13 09:44:56.008] Initialized Atoms subsystem within 18.1 seconds!
```

### CODE REVIEW

**Comment by optimumtact** [comment]
No longer critical, abandoned zoo has been disabled as a ruin

**Comment by optimumtact** [comment]
pictured, a lack of air on any turf


Arcane sigils of the fourth wall bleeding through into the game

**Comment by XDTM** [comment]
It's likely that adding a ..() in the random disease New could fix it

**Comment by SpaceManiac** [comment]
Erf, shouldn't have missed that. @XDTM You going to test/fix?

**Pull request closed without merging**
