### PR TITLE
Fixes the HoS's spider being air type instead of earth type (it's flying...)

### PR DESCRIPTION
**Pull request by silicons**
makes it overridden to ground type.

### CODE REVIEW

**Comment by TheVekter** [comment]
how the fuck did that happen

**Comment by WJohn** [comment]
Because sergeant araneus is actually a bat with a toooon of custom vars done entirely on the map, rather than an actual special type of spider or something.

**Comment by Armhulen** [comment]
Why the fuck

**Comment by WJohn** [comment]
because var editing is comically powerful.

**Comment by ShizCalev** [comment]
what

**Comment by ShizCalev** [comment]
can you put a collar on it atleast

**Comment by The-clown-known-as-Pepe** [comment]
@ShizCalev 
>/mob/living/simple_animal/hostile
Nope, only animals under simple_animal/pet are able to get collars for some reason

If only they were repathed/refactored though...

**Comment by XDTM** [comment]
Why not just make it a spider with edited faction? Only nurse spiders' AI spins webs, other spiders only spin webs when player-controlled.

**Comment by CPTANT** [comment]
The solution is obviously to make Araneus a var edited monkey instead.

**Comment by The-clown-known-as-Pepe** [comment]
Obvious solution is to make Araneus a Fighting/Venom type

**Comment by Armhulen** [comment]
@The-clown-known-as-Pepe heyooooooooooooooooo

**Comment by duncathan** [comment]
this is fine until someone repaths appropriately

**Pull request merged**
