### PR TITLE
Soul Vesseled corpses can be consumed by Vitality Matrices

### PR DESCRIPTION
**Pull request by ChangelingRain**
REMOVE CLUNKY BULLSHIT

### CODE REVIEW

**Comment by Kromgar** [comment]
Add a way to request new drones. We had one drone break we repaired it but it remained braindead

**Comment by Haevacht** [comment]
Trav doesn't like has_status_effect for some reason.

**Comment by coiax** [comment]
What are the requirements for a corpse to be consumed by a vitmatrix anyway

Also, should vitmatrixes have global storage? As in, if you charge one up, they can all access the charge.

**Comment by ChangelingRain** [comment]
A: it has to be dead
B: it has to have a mind, if not necessarily be currently inhabited by a player
C: with this, the mindless soul vesseled corpses also count

**Pull request merged**
