### PR TITLE
[READY] Gives crabs their own meat + recipes (Revived edition)

### PR DESCRIPTION
**Pull request by tralezab**
this has everything in it:
image

## Changelog
:cl: giygaslittlehelper
add: Crabs have their own meat and recipes!
/:cl:

### CODE REVIEW

**Comment by tralezab** [comment]
whoops one moment

**Comment by tralezab** [comment]
let me take a look at how imitation fish is made in the code, then i'm gonna do the same thing with crab to make imitation crab meat

**Comment by Krysonism** [comment]
> 
> 
> let me take a look at how imitation fish is made in the code, then i'm gonna do the same thing with crab to make imitation crab meat
> 
> (also post crab recipes and i'll see if i can't add them)

Wouldn't it be cooler if it was hard to get. Making bear steak or xenobread always feel cooler than fish dishes.

If you make an imitation meat, don't make it too easy to get.

**Comment by bgobandit** [comment]
crab cakes (crab + plain cake, not quite the recipe but easier with our code)
crab rangoon (crab + cheese + flat dough)

**Comment by tralezab** [comment]
will add both

**Comment by tralezab** [comment]
i'll finish imitation and crab cake another time

**Comment by AnturK** [comment]
These sprites could use some work imo but alright.

**Pull request merged**
