### PR TITLE
Soapstones can remove messages for free; empty soapstone for janitor

### PR DESCRIPTION
**Pull request by coiax**
:cl: coiax
add: Soapstones/chisel/magic markers/chalk can remove messages for free.
Removing one of your own messages still grants a use.
add: The Janitor starts with a dull soapstone for removing unwanted messages.
/:cl:

### CODE REVIEW

**Comment by KorPhaeron** [comment]
@AnturK 

Hopefully this helps, if not we can try limiting it to only a handful spawn per round like satchels do

And if it still sucks after that I'm out of ideas to limit it without ruining it so removal would be my next suggestion

**Comment by coiax** [comment]
@KorPhaeron maybe banning certain people from leaving messages?

**Comment by KorPhaeron** [comment]
We can just ban people normally if they don't take a warning to stop spamming,  don't need a new ban type

**Comment by Armhulen** [comment]
jobban from librarian, readys your :Laugh: s people

**Comment by Iamgoofball** [comment]
i'm jobbanned from librarian

just make destroying messages physically remove them from the pool

**Pull request merged**
