### PR TITLE
Ore Redemption Rescaling

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
Old:

T1: 1 sheet per ore

T2: 2 sheets per ore

T3: 3 sheets per ore

T4: 4 sheets per ore

New:

T1: 1 sheet per ore

T2: 1.35 sheets per ore

T3: 1.7 sheets per ore

T4: 2.05 sheets per ore

Literally doubling mineral output basically from roundstart is silly. I still need to test this but I figured the arguing may as well start now.

### CODE REVIEW

**Comment by bgobandit** [comment]
:+1: needed to be done

**Comment by lzimann** [comment]
Maaaybe around 2.5 sheets per ore in T4?

**Comment by Dorsisdwarf** [comment]
:+1: 
Scarcity Smarecity.

**Comment by octareenroon91** [comment]
Would you consider shifting from linear scaling?

```
temp_yield_per_ore = 1.41 ** max(0, rating - 1)
```

**Comment by Jazaen** [comment]
Yeah, it's a bit too low on T4, when you need materials (especially diamond) for all those shiny upgrades. Besides, this nerfs robotics quite heavily, since I think most mech costs were balanced around upgraded ORM.

**Comment by xxalpha** [comment]
Sounds good.

**Comment by Iamgoofball** [comment]
:-1: on the t4 nerf

it's supposed to be insanely good, please make that be 2.5 or 3

**Comment by KorPhaeron** [comment]
@Jazaen 

https://github.com/tgstation/-tg-station/commits/master/code/modules/mining/equipment_locker.dm?author=Iamgoofball

It was June 2015 when goof added mining machine upgrades.

https://github.com/tgstation/-tg-station/commits/c408e065667cfbd63b481342b8e58690d268064a/code/modules/research/designs/mechfabricator_designs.dm

But mecha costs have not been touched since google code

**Comment by GunHog** [comment]
There is nothing I can do to stop this.
No one cares that I oppose it anyway.
But still...
Do not like. :-1:

**Comment by KorPhaeron** [comment]
I think, deep down in your heart, you know that it's a good thing

**Comment by Buggy123** [comment]
:-1: People rarely bring in ores anyway, don't nerf it even more.

**Comment by AdamElTablawy** [comment]
Eh.

Leave T4 as is. The other nerfs I wholeheartedly approve of. R&D gets done every other shit and 40 mechs out the asshole is 2strong.

**Comment by Fox-McCloud** [comment]
I'd personally recommend: 1, 1.5, 2, 3 to start with.

But that's me; either case, this needed to happen.

**Comment by Iamgoofball** [comment]
@KorPhaeron Keep in mind, cargo's getting mineral exports, so they're gonna be tempted to ship materials off to R&D less.

**Comment by Fox-McCloud** [comment]
@Iamgoofball 

That only applies to plasma; they don't get any points for anything else.

**Comment by Iamgoofball** [comment]
@Fox-McCloud Nope, when shipping datums get in everything not bolted to the floor is going to be exportable

**Comment by Core0verload** [comment]
Maybe make it a chance instead of multiplier, or at least round the output? The sheets system is not intended to work with decimals.

**Comment by duncathan** [comment]
Yes, make it round please.

**Comment by KorPhaeron** [comment]
@duncathan 

Can't really round or we'd just be back to 1/2/3/4 (or have some tiers do nothing).

**Comment by Core0verload** [comment]
Round the output, not input. One T2 ore will add 1.35 sheets, but you will be unable to grab 13.5 sheets from the machine after smelting 10 ore, it will floor to 13 and leave 0.5 sheets in.

**Comment by KorPhaeron** [comment]
Couldn't someone do some dumb shit like feed sheets in at certain amounts to get more if it rounds up?

I could just discard the remainder I guess

**Comment by Core0verload** [comment]
That's why you must use floor on output, not round.

**Comment by KorPhaeron** [comment]
Do you know the name of the proc off the top of your head?

**Comment by Core0verload** [comment]
According to BYOND docs, `round(x)` floors the number unless given second arg.

**Comment by KorPhaeron** [comment]
cool, thanks

**Comment by Cheridan** [comment]
looks good to go then

**Comment by francinum** [comment]
RIP

**Comment by GunHog** [comment]
Lame.

**Comment by Lumipharon** [comment]
Thank. fucking. god.
Upgrades used to make R&D/robotics/mining an utter joke with how much shit you could shit out.
99.95% of everything had mineral amounts balanced with no upgrades in mind (both in the proto AND before the orm even existed).

**Pull request merged**
