### PR TITLE
New coat of paint 2

### PR DESCRIPTION
**Pull request by dannno**
:cl: Dannno
tweak: help I accidentally replaced all the computers and vending machines and shit with better ones
/:cl:

Replaces all the old computer/vending machine/crate/closet sprites with new ones in the new perspective

### CODE REVIEW

**Comment by optimumtact** [comment]
Hop in

**Comment by dannno** [comment]
I bought a gun

**Comment by PKPenguin321** [comment]
Use "spriteadd" instead of tweak in your changelog

**Comment by PKPenguin321** [comment]
Those consoles are THICC btw

**Comment by Incoming5643** [comment]
Looks alright for vending machines and to a lesser extent the crates but I don't like it on the closets, it loses a lot of perceived depth looking straight down like that.

3/4th sprite did nothing wrong.

**Comment by dannno** [comment]
This is 3/4.
Previous was some weird bastard child

**Comment by Incoming5643** [comment]
Well whatever it's called I didn't hate it. I don't hate these either, it just doesn't translate the concept that "this is a closet" as effectively without seeing the space behind the door.

**Comment by PKPenguin321** [comment]
Yeah some of these are a lot worse without being able to see the sides

**Comment by ChemicalRascal** [comment]
yeah well maybe you're a weird bastard child did you consider that

I'd suggest tweaking the wire on the consoles to be a bit more obvious, as that does have minor gameplay implications for those who are learning how to spess. ("How do I continue dismantling this console? I don't see the wire because it's too subtle, so I will never think to use a wirecutter! Also I was dropped on my head as a child and don't know what a wiki is.")

**Comment by ChemicalRascal** [comment]
Also yeah leave the lockers alone

**Comment by ChangelingRain** [comment]
None of your ratvar computer keyboards are different from the others; they all have the same color pattern instead of the differing ones.
Also, your ratvar computers don't have the proper bottom pixel loop.

**Comment by optimumtact** [comment]
Why does the computer change perspective when you deconstruct it?

**Comment by anconfuzedrock** [comment]
whats the problem with the lockers? they look fine, but they looked fine before too I guess.

**Comment by ChemicalRascal** [comment]
@optimumtact Based on the unchanged NT computer sprite, I'm guessing the mid-construction sprites just aren't updated

**Comment by ChangelingRain** [comment]
Also the off state for atmos keyboards is misnamed as 'atmos_key'

**Comment by ChangelingRain** [comment]
These should absolutely all hit the bottom border of the tile it's kind of weird if they don't

**Comment by ShadowDeath6** [comment]
nice commit name

**Comment by BeeSting12** [comment]
Honestly current lockers look better, the rest is p good.

**Comment by Nienhaus** [comment]
I did the crates.

**Comment by lzimann** [comment]
The lockers look really weird, they don't have much depth(especially if you compare with the vending machines that show some). Maybe expand the top a bit?

**Comment by dannno** [comment]
I did forget to mention that Nienhaus did the crates.

**Comment by dannno** [comment]
@ChangelingRain In all of the tedium of it I got lazy with the keyboards because I don't understand why they are different in the first place 
I will do something about it

**Comment by Xhuis** [comment]
S E R V E R C U L T U R E
E
R
V
E
R
C
U
L
T
U
R
E

Jokes aside, my only actual complaint with this is that the crates seem a little too far up on the perspective. :+1: to all else

**Comment by WJohn** [comment]
It looks like a lot of these were not really changed all that much. The lockers definitely need more extensive tweaking to make them appear thicker, as do the computers. I've also noticed that the colors for the lockers and the computers don't seem to have been changed at all.

I think it'd be best if you currently limited this PR to just the vending machines, and then did some more extensive work on lockers and computers in two future separate PRs.

**Comment by anconfuzedrock** [comment]
did nobody else notice the modular computer hasn't had a sprite change

**Comment by Metallusions** [comment]
Good vendor sprites, the lockers don't really have the same perspective though (also what do they look like when open?).  The markings on that rad crate look especially stretched.  I agree with WJohn, keep vendor changes and rework the other two later.

**Comment by WJohn** [comment]
Hmmm, dannno's palette desperately lacks good brown colors, as well as most low saturation colors I can think of using. When swapping to it, the crates are usually extremely bright and cheery, which they weren't after.

Here's a before (left) and after (right):
 

In this case, I think it's best if we leave the crates in the PR untouched, primarily because dannno's palette just has a few too many issues in it. Lacking browns, too high saturation in a lot of cases (blues especially) and so on. For the most part it's good, but it just needs significant tweaking. I noticed myself grabbing the highly desaturated colors from my OWN palette a lot of the time, so perhaps the high saturations being prevalent throughout this palette just have a few too many limitations as-is.

**Comment by PKPenguin321** [comment]
Wow no kidding, the radiation and paper wrapped crates look awful in the palette

**Comment by Iamgoofball** [comment]
can you check out how goon does 3/4ths lockers? might b. helpful

**Comment by Quardbreak** [comment]
Make please all dir's for consoles, i dont want use them by my ass side

**Comment by dannno** [comment]
Things to do

**Comment by peoplearestrange** [comment]
The issue with this forced perspective is its trying too hard to be an accurate representation of perspective. Its already a tile based game, if you force a more realistic perspective it makes everything else look off, particularly walls. It also makes crates look oddly flat. And when you open the lid it just looks like its expanding rather than opening.

**Comment by WJohn** [comment]
So you're saying that because the game is starting to look less shit, that, for a while, things that are REALLY shit are going to stand out more and more? Wouldn't that just mean that we should hurry this along and get it over with?

Besides, it's not like we haven't put the players through REALLY LONG SHITTY PERIODS of broken mechanics.

_oh wait_

remember when you couldn't reattach arms for a couple of months?

**Comment by Incoming5643** [comment]
The argument from consistency is just too early here. Convert the stuff that looks decent in 3/4ths (or already basically is in 3/4ths) first so you have a stronger case for this kinda stuff later.

**Comment by FantasticFwoosh** [comment]
Nobody rioted this hard to reject when @WJohn redid sprites.

**_Double standards_**

**Comment by peoplearestrange** [comment]
This isn't a update of code or a feature. This is a design choice, a look or feel that changes what is recognisable about SS13 or more accurately the /tg/ branch of the code. Each code base has a very definitive look to it. I feel like this moves away from said design. I mean honestly its already a horrible mash of different designs, but this particular perspective shifting is bad, in my view, from a purely design function. The form FOLLOWS the function, if I cannot easily tell if my crate is open or closed from glancing at it, its wrong.

**Comment by dannno** [comment]
This PR was closed
Stop commenting on it, it's annoying

**Comment by Incoming5643** [comment]
There is a an unsubscribe button over there -->

Not trying to be passive aggressive just letting you know that you can unsub, even from your own PRs.

**Comment by dannno** [comment]
thanks actually
continue arguing over a dead PR if you wish

**Pull request closed without merging**
