### PR TITLE
[wip]Cable/Powernet refactor

### PR DESCRIPTION
**Pull request by silicons**
basic cable stuff moved to /obj/structure/cable, power cables are now /obj/structure/cable/power
basic cable network stuff will be moved to /datum/cablenet while power would be /datum/cablenet/power
cable laying is now easier when done in code, just do new cable(loc, color, dir1, dir2), instead of having to manipulate icon states and all that stuff or use one of the convulated procs. will also add helpers to do this (possibly to be used later in mapping helpers)

so uh yeah, this is something to get me aquainted in power code which i'll be touching a lot for future overhauls potentially.
also opening this in a WIP state so if maintainers think this is not worth it or something they can tell me before i finish the whole thing?

### CODE REVIEW

**Comment by ninjanomnom** [comment]
Seems fine in concept, let me know when you have more of this done for review

**Comment by kingoftheautism** [comment]
expecting trainwreck that will break everything as usual

**Comment by Barhandar** [comment]
Fine in concept, but will guaranteed be a trainwreck that everyone BUT you will have to fix.

Can someone competent write it on designdoc from you, instead?

**Comment by kevinz000** [comment]
@Barhandar no

**Comment by ShizCalev** [comment]
Don't mean to be negative or anything, but what is the benefit of doing this over just adding two params to `cable/Initialize()` to set dir1 & dir2? Just seems like code churn to change tens of thousands of lines of code and require all the downstreams to do manually updating everything they have, as well as all their maps, just to accomplish something that could be done in 6~10 lines.

**Pull request closed without merging**
