### PR TITLE
Puts the AI in its place

### PR DESCRIPTION
**Pull request by pudl**
:cl: Quiltyquilty
rscadd: The AI is back in the center of the station. The gravity generator is now where the SMES room used to be. The SMESes are in the equipment room.
/:cl:

Personally I don't think it's good for Box to just copy everything Meta does. Since the start the MiniSat has been massive powercreep for the AI for no reason, since Meta is basically powercreep: the map.

The new AI core is similar but not identical to the old one. I shrunk down and made the upload a bit more secure. The rest is pretty similar.

EDIT: Since people are instantly saying this is a nerf and giving a thumbs down, here's my view on this change and why it isn't really a nerf.
- The AI can no longer be killed by nuke ops/wizards instantly at roundstart without anyone noticing.
- On that same note, breaking into the ai core to steal its brain is harder as well.
- However, malf AI is quite a bit more vulnerable being onstation.
- Rogue AIs go unchanged, because the upload was already onstation.

By looking at it like that, you could argue that it's a buff with a downside, or at the least a balanced change that evens out. That's my two cents.

AI Upload/Core:

Gravity Generator:

Where the MiniSat entrance used to be:

I forgot to take a picture of the equipment room, but just look at any pre-SMES room revision of Box, it's identical to that.

Merge token is #18147

### CODE REVIEW

**Comment by InsaneHyena** [comment]
Fuck this AI sat snowflake bullshit. Back to the station with you!

**Comment by GunHog** [comment]
Yet another middle finger to the AI. Yay.

**Comment by Imagebard** [comment]
I don't know who this GunHog guy is but he's incredibly salty if he placed reddit votes 1 second in after InsaneHyena's post.

**Comment by Cheridan** [comment]
lol @ gunhog's immediate downvote

**Comment by InsaneHyena** [comment]
GunHog downvotes anything that nerfs science or silicons.

**Comment by GunHog** [comment]
Because I find WJ's design a lot nicer.

**Comment by Cheridan** [comment]
i know hyena that's why its funny

**Comment by Miauw62** [comment]
DAE DAE DAE DAE DAE DAE DAE DAE DAE DAE DAE XDDDD LE LE LE

can we not do this dumbshit fucking drama please? jesus fucking christ

if you dont have anything useful to say fuck off.

**Comment by InsaneHyena** [comment]
However, all the previous designs I've seen have some special spots you can essentially murder AI from without coming into the reach of it's turrets. For the previous Box sat design it was SMES room, now it's from the "maint" on the AI sat. I don't really see any obvious weak spots here.

**Comment by Miauw62** [comment]
it doesnt really matter. ai on station means that the moment somebody thinks ur rouge you might as well ghost and save yourself the frustration.

**Comment by coiax** [comment]
Weak spots will generally only become apparent with repeated play.

And putting the AI in a more central location will make it easier to destroy if malf, which makes this map change a pretty clear nerf.

I think traitor AI has enough difficulty as it is, so :-1:

**Comment by KorPhaeron** [comment]
This actually makes the AI way harder to kill as any sort of antag though.

**Comment by KorPhaeron** [comment]
You can take the AI out as a traitor or ops or whatever because it's isolation works against it. Breaking in from the bridge is highly visible and security can dash right over to attack you.

**Comment by lzimann** [comment]
YES

**Comment by Miauw62** [comment]
thats actually a good point tbh

**Comment by lzimann** [comment]
well, not really since you can't see the AI from bridge(the entrance is to the south, where the upload is), killing the AI might be harder, but changing ai's law should be easier since you don't have to enter the bridge anymore to enter the upload

**Comment by xxalpha** [comment]
Make it like the vault, where it is floating in space with a bridge to access it.

**Comment by KorPhaeron** [comment]
So it makes

>hacking the AI easier (I consider this bad)

>killing the harmyeller station AI harder to kill (also bad)

>making the malf AI easier to kill (debatable, probably not great though)

I feel like people are cheering/decrying an ai "nerf" without actually considering what this will do. It's not actually really a nerf at all.

**Comment by Aloraydrel** [comment]
Downvoting since this doesnt say red pills the AI

**Comment by Iamgoofball** [comment]
testmerge?

**Comment by MrPerson** [comment]
Excuse me I was joking about that

**Comment by GunHog** [comment]
It has higher vulnerability to crew attacks, which makes it difficult for antag AI. All you need are tools to hack into the Captain's office, or break though to the meeting room to breach the single R-wall. With the greatly weakened borgs since the time the AI was moved off station, antagonist AI is going to be easier to defeat. It is also harder to steal shield or other modification items to fortify the chamber.

It is more difficult for antags to attack the AI, given that you need station access first, and there is the possibility of a Security response when hacking the upload doors. 

I feel that is the wrong direction, and please consider this feedback outside of the "GunHog downvotes all silicon nerfs" memes. It is a true statement, but I do have a **reason** for this.

**Comment by MrStonedOne** [comment]
I approve. This cuts down on vaild hunting ais as ais will notice that if they get a rep for valid hunting, tators will kill it quickly.

I played when we had this layout before, its not hard to win at malf, but you do need good borgs.

I played when we had this layout before, its not hard to secure yourself, but you do need to keep an ear out for sounds (ai can now hear any attempt to break in to upload)

The ai shouldn't be strong and super hard to kill. if you want to malf you have to actually get to a really low timer to win, OR have good borgs. I have never lost on ai sat as malf as viki, but i have about 50/50 record for bridge.

This also make uploading laws as tator easier, and as caption risker (as you could get ganked trying to enter upload, no more doing it from the comforts of bridge)

Test merging soon.

**Comment by KorPhaeron** [comment]
How are traitors gonna "kill it quickly" when it's in the most secure and heavily trafficked part of the map.

You can kill the AI for just a few tc right now (C4), it's much easier

**Comment by MrStonedOne** [comment]
you can kill it in this lay out with normal hacking and some good throwing or an emag and 1 hacked door.

**Comment by MrStonedOne** [comment]
also nobody goes in meeting room you can still use c4 to kill it that way once you get in, maybe via hops office

**Comment by GunHog** [comment]
> if you want to malf you have to actually get to a really low timer to win, OR have good borgs

Except that the timer is hard-coded to 450 process() ticks, and borgs were heavily nerfed since that time. No Secborgs, Baton removed from standard borg, and Malf AI = Traitor AI, so hostile traitors will GG you if they desire.

**Comment by MrStonedOne** [comment]
well that needs to be changed

**Comment by dhostak** [comment]
#bringbackthebaton

**Comment by KorPhaeron** [comment]
In a vacuum sure the station core is weaker, but all it takes is one ;CHELP TRAITOR and security (plus the rest of the crew) swarms you from a public hallway.

**Comment by Zilenan91** [comment]
It isn't any different on the AI sat currently. All they gotta do is yell help and people arrive with jetpacks.

It's even worse on Meta for traitors trying to kill it since there's a futurama suction tube to and from engineering and the AI sat that's really easily accessible.

**Comment by pudl** [comment]
Yeah I got the knife, I don't wanna use it tonight.

**Comment by Miauw62** [comment]
"people arrive with jetpacks" is still a huge difference from just being literally in the middle of the station and close to *everyone*

**Comment by pudl** [comment]
Let the stars decide if I'm gonna live or die.

**Comment by PKPenguin321** [comment]
one small nitpick, i think it would look nicer if the top two upload turrets were between the table and the console rather than right smack on top of the console

**Comment by MrStonedOne** [comment]
# HOLD THE PHONE!

***WHERE THE FUCK IS THE PHONE?***

**Comment by SidonCC** [comment]
Grav gen being close to the engine is shit, engine release buff poercrep :-1: :-1:

**Comment by Cebasiz** [comment]
actually using doomsday is going to be impossible now.

otherwise i don't really care. AI at present can be GGnore'd in 30 seconds with no hope of survival right now anyway, so any "nerf" to this value is essentially meaningless.

the state of borgs is far more worrying than the AIs "survival" which is basically 0% if anything attacks you with like 6 tc of equipment anyway.

**Comment by KorPhaeron** [comment]
>Rogue AIs go unchanged, because the upload was already onstation.

Clearly people have already forgotten how often roundstart borg emag+entering the upload used to happen when it wasn't on the bridge.

**Comment by Cebasiz** [comment]
to those who think i'm exaggerating btw

>4 tc X-4 which will get you through the wall with on charge to spare in ~20 seconds
>2 tc for 5+ EMP grenades and a 3-use EMP implant

>burn through the wall in 20 seconds
>throw a single EMP grenade, preventing the AI from screaming and depowering it & all the turrets in the core

run in spam emp implant a few times or throw grenades

AI ded 40s tops. even with a borg or two defending they will get zapped by the EMP and die and EMP implant is literally uncounterable as borgs have no stuns (and afaik it is usable anyway)

you have no chance of security responding in time if there are even any

100% indefensible ggnore 40s tops

**Comment by Cebasiz** [comment]
also core unanchors when ded now so you can space the core with no effort so it's also unrecoverable

>btw i'm probably shooting myself in the foot by telling everyone this but even before secborg removal sillicons were trivial to walk over because you have an at-will full screen + stun + several dozen throwable full screen + stuns for 2 tc

for like 6 tc you can literally black out and destroy every machine on the station no joke

**Comment by MrStonedOne** [comment]
Test merge successful, minor bugs, (apc direction is wrong, and smes in grav gen is broke, also the /core/ smes type is fucked, but thats a code issue)

Ai subversion is easier, making validing as ai harder since they can just subvert you for the price of an emag and some hacking.

:+1:

**Comment by KorPhaeron** [comment]
Except then the AI is validing the whole station

**Comment by KorPhaeron** [comment]
Being able to have control of the entire station "for the price of an emag" is not something we should be encouraging.

**Comment by optimumtact** [comment]
Needs an ingame poll, no question about it

**Comment by KorPhaeron** [comment]
Will probably be the regular split of people who hate ai vs people who don't

**Comment by lzimann** [comment]
I prefer the core in the station, but I don't think it's the way we should go right now. Maybe the AI could be turned to the bridge itself, so it would be the upload how it was(in the bridge) and then the core below, won't make the AI any harder to kill(maybe even easier?) but it will make subverting WAY harder.

**Comment by KorPhaeron** [comment]
I understand that the AI hate is strong after 5 years of uninterrupted buffs but making it more likely that the AI will kill everyone every round in the name of "nerfing" it just seems so silly to me

**Comment by Jordie0608** [comment]
A poll has been made

**Comment by pudl** [comment]
What the fuck @oranges and @Jordie0608. The change has only been testmerged for half a day, you can't poll it like that. You should wait like 3 days to a week, once everyone has played with the core a lot, before you test merge. Atm it's obviously going to get denied.

**Comment by Steelpoint** [comment]
Irrespective of your opinion on this change but the only fair way to do a poll is to have the change up for a few days.

**Comment by Jordie0608** [comment]
@pudl are you joshing me

**Comment by Imagebard** [comment]
Emags already have too much utility because of how much feature bloat they get. Making it easy to hack the AI with just a bonus that it doesn't need.
I'm changing my vote on this.

**Comment by pudl** [comment]
@Imagebard I'm guessing you weren't around for when Rigel and Williams would effortlessly subvert the AI as traitor RD EVERY round EVER with the hacked module in tech storage and rampage with mechs. How did tg EVER POSSIBLY survive back then?

**Comment by Zilenan91** [comment]
I don't think AI subversion will be that big of a deal to be honest. The upload has enough doors in front of it so that the AI will notice if someone is breaking in. There should be a turret or two in the first room though.

**Comment by optimumtact** [comment]
@pudl you know you're winning the poll right now right?

**Comment by pudl** [comment]
@optimumtact Yeah mso showed me, but it's still unfair. What if it's biased in the other sense, in that people haven't seen the negatives of it yet? I don't want it to be unfair for either side.

**Comment by Dorsisdwarf** [comment]
New pics?

**Comment by pudl** [comment]
@Dorsisdwarf Check the op

**Comment by Sligneris** [comment]
Please no. There's no way a traitor AI can work with this.

**Comment by pudl** [comment]
@Sligneris Lol how did it work from 2009-2013 then

**Comment by Miauw62** [comment]
not

**Comment by Sligneris** [comment]
It barely did. Most of the time people just bum rushed it from the Bridge.

**Comment by pudl** [comment]
Lol

**Comment by Davdichan** [comment]
Back to 3 Malf rounds I see.

**Comment by Keekenox** [comment]
This is the way it's always been on yogs and I see traitor AI's manage perfectly fine all the time, you just have to adapt your strategies accordingly.

**Comment by Imagebard** [comment]
>Yogs

Probably not the best testing place but whatever.

**Comment by Keekenox** [comment]
Hey man, I know what you mean, yogs has a decent sized list of shortcomings but I did rather like the configuration of AI, Tcommsat, and grav generator.

**Comment by KorPhaeron** [comment]
Malf went through various stages of bullshit 2009 -2013 including being on another z level and being able to shunt infinite times

**Comment by vista-** [comment]
re: 2009-2013 tater/malf AI: you either had to have robust borgs (rip secborg, rip baton) or have a pretty incompetent crew to win.

**Comment by Anonmare** [comment]
FYI you don't even need to go into the AI chamber to kill it as long as you have at least two EMPS.
Go to the APC side, pop your implant to drain the APC and stun the AI. Go to bridge side, pop your implant to drain the SMES. RIP AI.

This works against antag AI as well.

**Comment by Davdichan** [comment]
Shouldn't you drain the SMES first?

**Comment by SidonCC** [comment]
still don't agree on the grav gen placement

**Comment by Banana-Fist** [comment]
You can break the windows to the conference room and lob in EMP grenades without even stepping into the room, they will kill the AI. It's almost funny how bad that is.

**Comment by PKPenguin321** [comment]
You can already do that from the satellite, you just need a space suit

**Comment by KorPhaeron** [comment]
So why do we need to move it to the center of the station if it's already very killable, when moving it results in it getting hacked more often and grav gen being eaten more often

**Comment by optimumtact** [comment]
Actually it needs EMP proof walls on the core so they have to brave the turrets

**Comment by jughu** [comment]
Now we just need malf satalite back

**Comment by Anonmare** [comment]
Honestly I'd say it needs a space trench, like the vault has. Better than putting in a bunch of r-walls

**Comment by lzimann** [comment]
you need to add a borg spawner, since the old one was inside the upload(had a borg spawning over genetics today)

**Comment by pudl** [comment]
Done

**Comment by GrayRachnid** [comment]
The borg recharger is missing from the entrance room.

**Comment by pudl** [comment]
It doesnt need a borg recharger.

**Comment by Zilenan91** [comment]
The minisat recharger was only ever used if there was a malf. If the AI core is on the station it can use the ones that borgs use already, they don't need more coverage.

**Comment by YakumoChen** [comment]
> @Sligneris Lol how did it work from 2009-2013 then
Two words: Security Cyborgs

AI is currently unviable in any degree right now for fighting crew because the core defense is so shitty you might as well ignore it. Cyborgs have been completely nerfed into the ground and are barely any help defending a core unless they go into melee, and have a ton of hard counters from traitors and crew alike. You can make EMP grenades from chemistry and some simple mining ores, borgs have to melee to do anything now (which means flash gg no re), and traitors can just get the TC gg no re EMP kit and laugh as the AI is unable to do anything to stop them as they EMP all your borgs, your SMES, and your APC charge.

**Comment by KorPhaeron** [comment]
2010 era malf doors also instacrit you.

**Comment by YakumoChen** [comment]
Also Beepsky can't leave his home on box because he can't go through flaps.

**Comment by pudl** [comment]
@YakumoChen
The entire point of this pr is to kill the powercreep that's happened with the AI in the past year or so. Of course Pingsky is gone, because he's shit, especially now that botcall exists so you can summon Beepsky. There's two soap dispensers, which is enough to fill the entire core, the addition of all those APCs in WJ's pr was awful, and malf functioned fine just before that, like literally a couple of months ago so it's not like it's a huge jump in time. There is room for the autoborger, try harder to look for it, and no, it's not easier to hack into. The ai is capable of hearing its doors being messed with because of the size of the core, and it has cameras, compared to a sat it's a lot harder to fuck with.
Also you keep on listing off all these negative traits, trying to make this pr seem like a massive nerf, when no, it's not a massive nerf, it is an incredibly significant buff to station AI as well, and the station AI is the one that tg players see the most of and it's the more useful one, so I think the buff to it is a lot more important to the nerfs to traitor AI.
I don't even know why the hell you're going off about this, the change is already being polled. If it doesn't win, then it doesn't get in, so just go cast your vote and get it over with. Alternatively you could, instead of flinging shit, tell me what parts of the core you would like changed. And if you answer to that is "Keep it on the sat", then don't even comment. Thanks.

**Comment by KorPhaeron** [comment]
>malf worked fine a couple months ago

Well yeah we had sec borgs then

**Comment by Zilenan91** [comment]
Should all hacked borg modules get a stun arm?

**Comment by lzimann** [comment]
no

**Comment by Steelpoint** [comment]
mfw my original AI core was the second best AI core we've ever had on this server.

I'm serious, my AI design was pretty tame in comparison to the powercreep the current AI sat has gotten.

**Comment by GunHog** [comment]
> Alternatively you could, instead of flinging shit, tell me what parts of the core you would like changed. And if you answer to that is "Keep it on the sat", then don't even comment. Thanks.

The grilles to the side of the upload entrance are wasted space. On the left, you could add power and station computers, and on the right, cyborg rechargers, as well as a spawn point.

Add windoors to the second and third AI slots.

The rooms are missing fire alarms.

Add AI screens to the front door, visible in the hallway.

I have not verified this, so make sure the cameras are motion sensitive.

**Comment by pudl** [comment]
I updated the core. Old upload is back so there's 4 turrets again, also I put a red phone in the antechamber. The three cyborg spawns are now one in tool storage, one in the antechamber and one in the bathroom.

**Comment by Cebasiz** [comment]
if your objective is to nerf malf you shouldn't bother. it's basically already autolose except in extreme lowpop.

even the 3-Rwall core can be walked over with zero problems by one traitor in 30s or a few crew in no time flat.

like sure i don't care that much because losing doesn't bother me but if balance is your objective the pendulum has already swung way past the middle of the arc here. trust me i end up playing lots of malf.

**Comment by SidonCC** [comment]
Grav gen still near engine :-1:

**Comment by optimumtact** [comment]
The poll is pretty close, so get your final votes in soon

**Comment by optimumtact** [comment]
@Zilenan91 ai borg hacking needs a rework so the AI can choose what traitor modules the borg gets.

That's been something on my list of things todo for some time.

**Comment by Zilenan91** [comment]
Then nobody would ever pick anything but engiborg though. The only reason people pick different things currently is if they get emagged they have different gear.

**Comment by Incoming5643** [comment]
Merged with do not merge tag

**Comment by Incoming5643** [comment]
D O E S N ' T 
C O U N T

**Pull request merged**
