### PR TITLE
You can now drag-drop people into open DNA scanners

### PR DESCRIPTION
**Pull request by ghost**
:cl: More Robust Than You
tweak: You can now drag-drop people into open DNA scanners
/:cl:

### CODE REVIEW

**Comment by Mercenaryblue** [comment]
QUALITY OF LIFE UPDATE!

**Comment by FantasticFwoosh** [comment]
Geneticists will use this to murder people i am sure because the machines in genetics are so close to each other. The murderous potential outweighs the good & 'convenience that can be gained from it that was barely noticeable in the first place.

- Grab your collegue while they are looking at the screen, lock them inside, spam rads until dead.

No.

**Comment by Supermichael777** [comment]
https://www.google.com/url?sa=i&rct=j&q=&esrc=s&source=images&cd=&cad=rja&uact=8&ved=0ahUKEwidgPORp-zWAhUM5YMKHVdSA04QjRwIBw&url=https%3A%2F%2Fforums.ultra-combo.com%2Ft%2Fpost-a-video-image-of-your-reaction-when-fill-in-the-blank-scenario-happens-to-you-in-killer-instinct%2F3350&psig=AOvVaw3l96nWrPmeTt-Hd8iSvc1D&ust=1507939660859336

**Comment by Ratvar** [comment]
Fwoosh, you can do the same with cryo currently and cryo are automatic 30s cuffs

**Comment by nicbn** [comment]
Add a cooldown.

**Pull request merged**
