### PR TITLE
Fixes for plastic bottle splashing

### LINKED ISSUE #49089: Plastic bottles (water bottles) can't splash properly
#### Round ID:
Local testing. 

#### Reproduction:
Make or spawn a food/drinks/waterbottle/empty

Note it spawns without a white cap, which I believe is intended. 

Fill it with water. Select harm intent. 

* Clicking yourself with it makes you drink from the bottle instead of splashing the water on you. 
* Clicking a table makes you slap it with the bottle without splashing the water. 
* Throwing the bottle does not spill the water. 

Now alt-click the bottle to put the cap on. Testing the above again will give identical results (except it lands slightly differently). 

Alt-click the bottle a second time to remove the cap. 
* Clicking yourself with it still makes you drink from the bottle instead of splashing the water on you. 
* Clicking a table still makes you slap it with the bottle without splashing the water. 
* Throwing the bottle now DOES spill the water. 

Splashing yourself with other containers like the 30u bottles still works.

### PR DESCRIPTION
**Pull request by nightred**
## About The Pull Request

Fixes #49089 

Plastic water bottles did not spash properly.
The cap was not updated to be shown on at init.

## Why It's Good For The Game

Bug fixes

## Changelog
:cl:
fix: plastic water bottles can now spash
fix: plastic water bottle caps render properly the first time
/:cl:

### CODE REVIEW

**Comment by AnturK** [comment]
Someone explain why waterbottle doesn't share type with other bottles.

**Comment by ExcessiveUseOfCobblestone** [comment]
in b4 because it's not glass 😏

**Review by Cyberboss — APPROVED** [review]

**Comment by Angustmeta** [comment]
Now after testing you still have to put the cap on and take it off again to be able to splash.

**Comment by nightred** [comment]
Good to know, i will work on the fix.

**Pull request merged**
