### PR TITLE
Adds Stabilized Omnizine to Medical Cyborgs

### PR DESCRIPTION
**Pull request by SconesC**
Replaces the current selection of bastardized trekchems with an overdoseless Omnizine variant. This avoids meaningless tedium and is a throwback to the arguably much more streamlined Doctor's Delight rendition. 

This also replaces the Omnizine in the Adrenal Implant to fix an unreported edge case issue involving accidental overdose.

### CODE REVIEW

**Comment by Cebasiz** [comment]
so you're replacing every chemical with just omnizine? are you giving them 100u of it? otherwise it's a straight nerf. the "tedium" you're talking about is like core functionality of the fuggin cyborg

if you want to change mediborg add ability to use bloodbags or add a chemset or something, don't nerf the healing ability while reducing the skill involved that's just asinine.

**Comment by xxalpha** [comment]
How effective is stabilized omnizine compared to regular omnizine?

**Comment by SconesC** [comment]
Actually in retrospect this is a bad idea

**Comment by Cebasiz** [comment]
weeeeeellllllllll okay

i didn't expect that to work

sorry ;_;

**Comment by Iamgoofball** [comment]
i uh

i thought i did this already

with tricord

**Pull request closed without merging**
