### PR TITLE
[s] makes sure github doesn't kill us

### PR DESCRIPTION
**Pull request by Iamgoofball**
TODO: edit maps
edit sprites
edit all references to this word out of the repo

### CODE REVIEW

**Comment by JJRcop** [comment]
https://lzimann.org/icon_searcher/index.php?state=faggot&icon=

**Comment by praisenarsie** [comment]
you can probably get away with saying faggot for da meat tho. the rest, probably not.

**Comment by Cyberboss** [comment]
Don't try and suppress our faggots

**Comment by epochayur** [comment]
are they actually cracking down on this or something?

**Comment by AlexTheSysop42** [comment]
Arm got gitbanned for a bit by calling mrty retarded in the title of a PR

**Pull request closed without merging**
