### PR TITLE
Removes one dotty boi

### PR DESCRIPTION
**Pull request by Cyberboss**
Prepare the witchhunt

https://github.com/tgstation/tgstation/commit/ad7fc7417c74fd390cd2ab0ec54bcd87401998ef#diff-f85a828b3534f00a3805fb2329e65605R42

### CODE REVIEW

**Comment by Kraseo** [comment]
.

**Comment by praisenarsie** [comment]
💠

**Comment by Anonmare** [comment]
Who would win? A spaghetti codebase over a decade in age? Or one dotty boi?

**Comment by Buggy123** [comment]
:+1: But did this actually break anything?

**Comment by Cyberboss** [comment]
@Buggy123 it broke @MapDiffBot

**Pull request merged**
