### PR TITLE
Adds a glug sound to welding fuel tank leaks

### PR DESCRIPTION
**Pull request by MrMelbert**
## About The Pull Request

When a fuel tank leaks it makes a quiet "glug" sound. 

https://github.com/tgstation/tgstation/assets/51863163/21d5665e-c06c-49db-9c61-1479be0f0b7a

## Why It's Good For The Game

I noticed that there was absolutely no fx associated with dragging a leaking tank which was very off putting to me so I thought a glug glug glug gas can sound would sound good.

Maybe doesn't sound the best when dragging at max speed but it sounds funny anyways so. 

## Changelog

:cl: Melbert
sound: Glug-glug sound when dragging a leaking gas tank
/:cl:

### CODE REVIEW

**Comment by TheBoondock** [comment]
The sound is too quick with it being played every time it's pulled. I think you should make it a constant looping sound independent of on pulled. Also this sounds like liquid splashing inside a container more than leaking. I think having a water droplet sound looping while it's open is more fitting

**Comment by MrMelbert** [comment]
I think it kinda sounds like how it sounds when you pour something really fast so I'm leaving it as it

**Comment by Sadboysuss** [comment]
Should add this same sound to water tank too, or a different one if you like. Love this sound

**Comment by LemonInTheDark** [comment]
> The sound is too quick with it being played every time it's pulled. I think you should make it a constant looping sound independent of on pulled. Also this sounds like liquid splashing inside a container more than leaking. I think having a water droplet sound looping while it's open is more fitting


We could really use a component for this, like "loop while active" that refreshes the end time on a looping sound every time some generic signal is sent

**Review by L0pz — APPROVED** [review]
glug glug

**Comment by Dawnseer** [comment]
Now make it play when someone with the alcoholic quirk drinks anything alcoholic

**Comment by LemonInTheDark** [comment]
> glug glug

please do not use the approve/deny feature if you are not a maintainer it confuses people (unless it's a meme in which case go off king)

**Pull request merged**
