### PR TITLE
Removes old, shitty bedsheet sprite, changes spooky ghost pathing

### PR DESCRIPTION
**Pull request by tralezab**
## About The Pull Request

Changes spooky ghost to be a subtype of the ghost sheet, instead of it's own path.

It inherits the (much better) ghost_sheet icon state and cover flags

## Why It's Good For The Game

bedsheet icon state is ugly as hell and we definitely don't need two of these sprites

## Changelog
:cl:
imagedel: goodbye bedsheet icon state you will not be missed
/:cl:

### CODE REVIEW

**Comment by tralezab** [comment]
image
the top one is the removed sprite. the bottom one is the sprite all instances of the top will now use. the left is an actual ghost.

**Comment by SkeletalElite** [comment]
There should be a byond member ghost sprite that looks like that

**Comment by tralezab** [comment]
I would love that, i'll add it

**Comment by Winterous** [comment]
Fuck yeah my sprite getting an upgrade!

**Review by Twaticus — APPROVED** [review]

**Pull request merged**
