### PR TITLE
Maintenance Space Huts

### PR DESCRIPTION
**Pull request by tralezab**
## About The Pull Request

Each map has a space hut, it's a nice little room only accessible from an airlock + catwalks.

Each one has a different theme per map:
Metastation: Moved the nice romantic maint-dinner onto the hut, with a mass driver for dumping your bodies.
Deltastation: A space observatory that will get completely obliterated by even the lightest of meteor storms. (+Space Lizard Plush!)
Icebox: A quaint little broken down cabin. You'll have to break through barricades to get in, but the fireplace will make it quite cozy.
Kilo: A very, VERY hidden little plasma-friendly environment to hang out in without your suits on. No oxygen, so no worries about starting a fire! (+Plasmamen Plushies!)

## Why It's Good For The Game

Just a little spice to my maintenance meta, plus I've repeatedly seen and been told that people love finding plushies.

## Changelog
:cl:
add: Space huts are accessable from maint on all maps. Expect it to be the first thing checked when sec is looking for the cultist factory!
/:cl:

### CODE REVIEW

**Comment by necromanceranne** [comment]
Space Hut sounds like a bad pizza place.

**Comment by Jared-Fogle** [comment]
cuute

**Review by Twaticus — APPROVED** [review]

**Comment by tralezab** [comment]
changes: improved pretty much every map except cabin a lil' bit, finally added the button for mass driver and the plasma for plasmaroom

**Comment by Tlaltecuhtli** [comment]
space huts? are they inhabited by space indians?

**Comment by tralezab** [comment]
That would be a space tipi, or maybe a space longhouse...

**Comment by Fikou** [comment]
deltastation hut is bad dont do diagonals in that way ever please

**Comment by Cartographer-D** [comment]
I like these. Are there items in the crates on the deltastation one? If there are just make sure they aren't strong items.

Fikou is also right about not doing diagonals that way. Make sure your walls connect to each other.

Please at least give each of them a camera as well. Otherwise the default for security will be to have to don a hardsuit and search them every time they can't find a traitor. At least with the cameras, you'll be able to sometimes tell if they're clear so long as the camera is working.

**Comment by ilikesaying** [comment]
outpizza the space hut

**Comment by Cyberboss** [comment]
I can live with the lack of cameras

**Pull request merged**
