### PR TITLE
Removes The Random Brain Trauma Event

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request
YES this is an ided pr
NO I do not care
Removes the random brain trauma event from the game

## Why It's Good For The Game
My day be so fine, then boom, random brain trauma.

I don't think something that is completely rng that has a very high chance of completely fucking your round over in whatever way is something that should remain in the game.

## Changelog
:cl:
del: Random Brain Trauma Event
/:cl:

### CODE REVIEW

**Comment by tralezab** [comment]
hahahahaha

**Comment by ArcaneMusic** [comment]
I do think this will effect the quantity and quality of brain trauma that players will see and get experience with from a medical gameplay perspective.

**Comment by Time-Green** [comment]
Ideally we just sometimes punish curious people. Like exposure to certain events could induce a brain trauma later on. 

Random brain trauma's are worth the suffering IMO

**Comment by wesoda25** [comment]
waaa waaa waaaa!!!

**Comment by IndieanaJones** [comment]
https://www.youtube.com/watch?v=GdNI0_cx22s

**Comment by Serxule** [comment]
i like how coders continue to prove my "coders: thing bad i delete" meme

**Comment by Paxilmaniac** [comment]
There are plenty of ways to get brain traumas, complete and total unavoidable uncontrollable rng shouldn't be one of them

**Comment by dondonpow** [comment]
retarded catgirl acts like a retarded catgirl. many such cases!

**Comment by maxymax13** [comment]
sounds like *someone* got rng brain trauma

**Comment by RaveRadbury** [comment]
Random brain traumas are fun and interesting, and we have a lot of brain traumas to choose from. I would prefer not to see this event go.

**Comment by nianjiilical** [comment]
if this is really a problem just blacklist the most game-ruining ones from the event pool

**Comment by Pumpkinoe** [comment]
> if this is really a problem just blacklist the most game-ruining ones from the event pool

yknow this is actually a pretty good idea

**Comment by ATH1909** [comment]
> if this is really a problem just blacklist the most game-ruining ones from the event pool

or maybe blacklist antags from being selected by the event, although that could lead to some metagaming.

**Comment by EgorDinamit** [comment]
Just make it run only on high(~35+) pop and choose only weak/less harmful traumas.
As shitty this event is, I think complete removal isn't a good solution.

**Comment by D4C-420** [comment]
> or maybe blacklist antags from being selected by the event, although that could lead to some (acceptable levels of?) metagaming

Nah I don't think that would lead to any metagaming. For every round someone gets a brain trauma they play many more which they don't plus all the ways of forcing brain traumas onto people would still work. A person not suffering from a random event won't give away their status. IF someone some how did mange to meta game this way you could always just black list the really debilitating stuff.

**Comment by Mothblocks** [comment]
i think its funny, i'd rather see the extremely debilitating ones just get blacklisted

> or maybe blacklist antags from being selected by the event

no lmao

**Pull request closed without merging**
