### PR TITLE
Adds some shuttle wreckage (Lavaland Ruin)

### PR DESCRIPTION
**Pull request by r3dj4ck0424**
## About The Pull Request
To try and figure out the map-making process, I've made a little ruin to add to Lavaland and hopefully pique the interest of any passing shaft miners.
Map-Making Shuttle Wreckage
Currently, in-game it looks something like this
Space Station 13 2024-05-31 211713

## Why It's Good For The Game
It's a nice bit of story for the shaft miners to come across while blasting their way across the wasteland, with a few potential prizes mixed with danger. At the very least, this should help increase the variety of ruins available.

## Changelog
:cl:
add: Added another ruin to Lavaland
/:cl:

### CODE REVIEW

**Comment by Admiral-Gigaton** [comment]
hey doc you should probably describe what it is before the maintainers rip off your GBP limbs

**Comment by SomeoneYouProbablyKnow** [comment]
Unsure how this works but won't the items spawned on lava tiles just burn up by the time any miner finds them?

**Comment by Admiral-Gigaton** [comment]
pretty damn sweet ruin, even if it doesn't add much to the table, its a guaranteed tendril, and whatever those crates are (i don't map... yet) would probably be something decent... probably

**Comment by r3dj4ck0424** [comment]
Thanks for the help, yall. Figuring this stuff out has been a learning experience.
(Sidenote: I think the crate spawners I used were just copied out of maints somewhere)

**Review by Maurukas — COMMENTED** [review]
Please push an empty commit or merge master and push to force Mapdiffbot to rerun. It has been fixed.

**Comment by r3dj4ck0424** [comment]
Hm. Any idea what's going on with the integration tests?

**Comment by r3dj4ck0424** [comment]
> Please push an empty commit or merge master and push to force Mapdiffbot to rerun. It has been fixed.

okay, I think I got it working now. Can you review the new stuff and confirm?

**Review by Maurukas — APPROVED** [review]

**Pull request merged**
