### PR TITLE
Adds missing access check to brigdoors

### LINKED ISSUE #24270: brig timer access requirement doesn't work
copied from https://github.com/HippieStation/HippieStation13/issues/268

brig timers are meant to require access to use, but for some reason they don't. i think the req_access check was accidentally removed after the interface was updated to tgui.

### PR DESCRIPTION
**Pull request by Cyberboss**
Fixes #24270
:cl:
fix: Brig cell doors now properly require the correct access
/:cl:

### CODE REVIEW

**Comment by coiax** [comment]
People will be running into these to make them spam the chat.

**Comment by Cyberboss** [comment]
Yeah, I guess I'll just change it to a `to_chat`

**Comment by XDTM** [comment]
Aw, i liked reducing my sentence with TK while inside, it felt like emergent gameplay

**Comment by optimumtact** [comment]
use tochat

**Pull request merged**
