### PR TITLE
Revert "MERGE THIS RIGHT FUCKING NOW I DON'T CARE ABOUT TRAVIS"

### PR DESCRIPTION
**Pull request by Razharas**
Reverts tgstation/-tg-station#10174

### CODE REVIEW

**Comment by LaharlMontogmmery** [comment]
FUCK IT

MICROBOMS WILL REMAIN MACRO BOMBS

GOOOOOOOOOOOOOOOOOOOOOOOOOOOF

**Comment by Anonus** [comment]
HOW DOES A ONE-LINE CHANGE LIKE THIS BREAK UPLINKS THANKS GOOF

**Comment by LaharlMontogmmery** [comment]
WHAT IS GOOF

**Pull request merged**
