### PR TITLE
Fix pipenets volume

### PR DESCRIPTION
**Pull request by Ghilker**
## About The Pull Request
Fix the various pipenet volumes by setting the volume to 70 L per pipe
This will reduce the distro and waste loop volumes by around three times reaching around the correct amount

## Why It's Good For The Game
Fix bad volume

## Changelog
:cl:
fix: distro and waste loop are no longer almost 3 times as big as they should
/:cl:

### CODE REVIEW

**Comment by LemonInTheDark** [comment]
I know what I said on discord, but after giving it some thought I'm pretty sure changing volume on connection is just fine, and would be a better solution to this issue

**Comment by Ghilker** [comment]
> I know what I said on discord, but after giving it some thought I'm pretty sure changing volume on connection is just fine, and would be a better solution to this issue

the issue is that how do i update the pipenet volume on connection?

**Comment by LemonInTheDark** [comment]
This is a more painful problem then expected

**Comment by LemonInTheDark** [comment]
Honestly not sure what to do with this, my gut says there should be a proc to hook into but there isn't.
Take the average of 140L maybe?

**Comment by Ghilker** [comment]
Mmmh i can't find a proper way to make it into a proc, 140L is the maximum for pipes (35L * connection)
i'll close this and come back to it in the near future

**Comment by LemonInTheDark** [comment]
if I'm honest I thought it was 70 per end, 50% would be a reasonable stopgap

**Pull request closed without merging**
