### PR TITLE
Removes all game modes considered to be less fun then extended.

### PR DESCRIPTION
**Pull request by MrsTonedOne**
Based off of https://tgstation13.org/tgdb/irvpolltally.php?id=171&totalsort=1

:cl: 
del: Removed cult
del: Removed clock cult
del: Removed rev
del: Removed blob
del: Removed changeling/tatorchan
/:cl:

Closes #30320

### CODE REVIEW

**Comment by MoreRobustThanYou** [comment]
how much time did you spend on this shitpost

**Comment by PraiseRatvar** [comment]
tbh traitorchan is worse than tchan

**Comment by MrStonedOne** [comment]
>how much time did you spend on this shitpost
about 5 minutes

**Comment by KorPhaeron** [comment]
Its really funny that only original goon modes are more popular than doing nothing and everything we have added in 7 years is less popular

**Comment by KorPhaeron** [comment]
https://atlantaned.space/newSS13tools/polls.php?poll=169

When polled individually modes less popular than extended are still popular though, or at least clock cult is. Only 25% want it removed

**Comment by GuyonBroadway** [comment]
Game modes were a mistake, revert all the way back to the OG game mode.

Meteor.

**Comment by CPTANT** [comment]
Remove extended while you are at it.

**Comment by ma44** [comment]
Why not just make one server have all the game modes, and the other have the fun gamemodes?

**Comment by calzilla1** [comment]
BUENO

**Comment by Iamgoofball** [comment]
Blob needs to have mulligans disabled

**Comment by kilkun** [comment]
keep rev and merge this motherfucker

**Comment by DoctoreMad** [comment]
>keep rev

I am now:
Praying for kilkun's death

**Comment by BlueNothing** [comment]
I'd say to keep the cult modes, but otherwise... eh, that works.

**Comment by kilkun** [comment]
all cult cultists must die

**Pull request closed without merging**
