### PR TITLE
GAGSify colored/job labcoats

### PR DESCRIPTION
**Pull request by Jolly-66**
## About The Pull Request
Title.

## Why It's Good For The Game
Cuts down on sprites, converts colored labcoats into GAGS labcoats.

GAGS labcoats are primarily built by 3 components on top of the, well, actual labcoat.

- The shoulder parts
- Back pattern
- Belt/sash thing

<details>
<summary> Before Image </summary>

image

</details>

<details>
<summary> After Image </summary>

image

</details>

## Changelog

:cl: Jolly
image: Colored labcoats have been GAGSed! Please report any weird oddities on Github.
fix: The coroners lab coat is no longer offset by one pixel.
/:cl:

### CODE REVIEW

**Comment by DATA-xPUNGED** [comment]
Does this mean we can change the white of the labcoat?

**Comment by Jolly-66** [comment]
> Does this mean we can change the white of the labcoat?

Yes, however, REGULAR lab coats weren't touched, just the job specific ones with the trims or whatever. I'll do the regular coats at a later date.

I just want to clear that up because there's technically two types of coats

**Review by Wallemations — CHANGES_REQUESTED** [review]
What do the other 2 labcoats look like
You only showed 5/7

**Comment by Jolly-66** [comment]
Chemist colors were tweaked because they were too dark/brown, so I included them in this screenshot.

image

**Comment by Jezzared** [comment]
I was just thinking about dipping my toes back in and doing the GAGscoats i had planned to do like a year ago.

I might still be able to do some of the changes I wanted, if anything this makes it easier. Regardless, GAGscoats are way overdue.

**Comment by Wallemations** [comment]
This doesn't add customization to the labcoats through vendors, right? Compared to a lot of the other clothing I'm not sure how I'd feel if people could swap their colors around freely, since these are big visual indicators for your job

**Comment by Jolly-66** [comment]
> This doesn't add customization to the labcoats through vendors, right? Compared to a lot of the other clothing I'm not sure how I'd feel if people could swap their colors around freely, since these are big visual indicators for your job

No, this just enables them to be rendered through the GAGs system and adding them to vendors is not the intention of this PR.

If someone else decides to do it then that discussion focus is for that PR.

**Comment by Jolly-66** [comment]
I'll fix that tomorrow

**Review by Wallemations — APPROVED** [review]
Fuck it, they look fine enough to me
Fix those snapshots first though

**Pull request merged**
