### PR TITLE
Rewords the traitor panel's policy tooltip

### PR DESCRIPTION
**Pull request by tralezab**
## About The Pull Request

Fulp's spacelaw isn't a suggestion, which makes the upstream comment in the tgui kind of an unintentional griffon.

image

## Why It's Good For The Game

Helps other open codebase repositories

## Changelog
:cl:
spellcheck: Changed the wording on antag panel policy a little bit.
/:cl:

### CODE REVIEW

**Comment by tralezab** [comment]
feel free to no-gbp label this by the way, it's a few line change

**Comment by Colovorat** [comment]
can't downstreams change that on their own?

**Comment by Mothblocks** [comment]
make it a policy.json silly

**Comment by Mothblocks** [comment]
and send it through static data

**Comment by stylemistake** [comment]
And what mothblocks said, but it belongs to another PR.

**Pull request merged**
