### PR TITLE
Gives the skateboard a sick-ass paint job.

### PR DESCRIPTION
**Pull request by harmonyn**
Nanotrasen blue!

Fixes https://github.com/tgstation/-tg-station/issues/16144.

### CODE REVIEW

**Comment by RandomMarine** [comment]
Suggestion, keep the default sprite but let players use a spraycan to choose from a list of sicknasty custom paintjobs.

**Comment by bgobandit** [comment]
the default sprite is almost invisible, that's the whole point of changing it

**Comment by TehZombehz** [comment]
Gnarly tubular radical!

**Comment by PKPenguin321** [comment]
Yeah, post pics

**Comment by PKPenguin321** [comment]
u never posted pics

**Comment by Chocobro** [comment]
needs more GIRL and Birdhouse board designs imo

**Pull request merged**
