### PR TITLE
Awakening killer tomatoes is no longer impossible to stop

### PR DESCRIPTION
**Pull request by ChangelingRain**
A: visible message
B: you have to stand still for a little bit before the tomato will start to awaken

accordingly you don't have to worry about somebody clickspamming to produce unending tomatoes because they need a second for each one, and, as such, cannot produce infinite tomatoes while you're beating them to death.

### CODE REVIEW

**Comment by kevinz000** [comment]
nerf botany to the ground please.

**Comment by PKPenguin321** [comment]
but not science though right fellow gamers?? ^_^

**Comment by KorPhaeron** [comment]
Just run away if they're spamming tomatoes? Having to "channel" them makes them incredibly weak

**Comment by Cyberboss** [comment]
>kevinz000
>nerf botany
My sides

**Comment by ChangelingRain** [comment]
Having to channel them means you can't do it on the run or while being attacked. You can still build a tomato army, it just happens to take longer.

**Comment by KorPhaeron** [comment]
You can't really move them or steer them once you make them though, so you couldn't really use them defensively.

And as you've discovered trying to balance clock cult, this game doesn't really lend itself to defensive play.

**Comment by ChangelingRain** [comment]
Uh, you mean you can't use them offensively, right? Because standing in a swarm of tomatoes sounds like a HELL of a rad defense.

**Comment by bobdobbington** [comment]
Is the idea to balance the game around the dudes abusing fucking macro hotkeys? This is like the opposite of a quality of life upgrade. This makes the tomatoes much harder to deploy against both megafauna and the station. Your rationale for this PR is literally "the guy I was murdering killed me with tomatoes, it's too stronk." If you're worried about macro abuse implement something to defeat that, don't use it as a red herring to justify nerfing a feature you don't like.

**Comment by Supermichael777** [comment]
your the first one to mention macros

**Comment by Supermichael777** [comment]
also facid/naplm tomatos are still the fucking best weapon.

**Comment by Supermichael777** [comment]
seprated chem potasium water is also gud

**Comment by Iamgoofball** [comment]
# this is fueled by clockcult getting killed by tomatoes

**Comment by Iamgoofball** [comment]
# stop balancing the game around clockcult

**Comment by ChangelingRain** [comment]
3 tomatoes a second, each with 60~ health and 20~ damage and also fast as fuck!
explain to me how this is fine. explain how being able to produce an infinite stream of 60 health 20 damage mobs that won't attack you is fine. please, try.

**Comment by ShadowDeath6** [comment]
They move at default simplemob speed unless turns_per_move influences that at all. 

They have 30 health each

They do between 8 and 12 damage

**Comment by Iamgoofball** [comment]
# cute they closed a PR of mine because I called out their grudge nerfing of stuff to balance for clock cult

**Comment by ChangelingRain** [comment]
@ShadowDeath6 Yes, but they gain additional stats based on the seed's stats, and the resulting stats are, in fact, around 60 health and 20 damage if the seed is at maximum stats.

**Comment by ShadowDeath6** [comment]
Well, that's fair, then. 

A different way to go about this could be that it takes however long for the item to activate, like a slime core reaction so people can drop it or hold it in their hand while moving rather than being locked in place to spawn one.

**Comment by Haevacht** [comment]
Goof you know a normal sized font exists right?

**Comment by PKPenguin321** [comment]
:-1: Tomatoes are fine, they're really weak and easy to just run away from if you're not equipped to handle them. Not to mention they're pretty rarely used already.

**Comment by Doppeltongue** [comment]
It takes an experienced botanist around 30 minutes with **good** RNG to get tomatoes planted with 25 damage and 47 health, which is usually well after the engine is loose/the round is decided. Before then, botany is essentially helpless and in order to not die to your own tomatoes, you must be a plant person, which requires you to die and also requires another person to harvest you. You also must do this in a part of the station that is visible to everyone who passes by, in a job that has virtually no access. Tomatoes cannot be controlled so they'll attack people you don't want attacked, and they won't help you get through a bolted door or walls.

**Comment by PKPenguin321** [comment]
Yeah, they're basically weak as fuck and only really become strong in hordes. Not sure why they need to be nerfed.

**Comment by Emilc4h** [comment]
To be fair, if a Botanist knows even the bare basics of Botany, they'll easily be able to make enough for a horde.

But either way, I don't think they're really that strong. If they're too powerful as is, perhaps reduce their damage/health, but giving them an activation time is nerfing them into the ground.

**Comment by XDTM** [comment]
It takes way less than 30 minutes if you have some mutagen, but becoming a podperson can be complicated.

**Comment by FantasticFwoosh** [comment]
If you want to rebalance tomatoes, hard nerf the max amount of killer tomatoes per plant & adjust growth times adequately. The mob exists in areas of the game and focusing on the mob is probably the wrong decision compared to its production source.

Its a plant that is consumed on use (without gene editing perennial growth) so people build large gardens of them eventually, and you shouldn't stop them from doing that but you can make changes on how efficient & difficult it is to set up those gardens.

> Goof is right to criticize you in such a way, this does sound like something ocular wardens can't handle and out-guns clockcult hence a nerf without really explaining why you even care about a feature people barely use & spam is open to scrutiny

**Comment by jughu** [comment]
Something something... tomato power... based on... potency...

**Comment by Kromgar** [comment]
They need to be nerded because tomatoes beat vlock cult a boo hoo 

Joans a real grudge voder if it beats clock cult it must be nerfed only cucks can be op

**Comment by Robustin** [comment]
Oh man I was thought it was a joke about the Joana making a tomato nerf PR after clock cult got finished off by tomatoes but here we are. Overt grudgecode go!

They're a niche weapon and it's really not hard to either set up somewhere with a chokepoint so that tomatoes are a non-issue or just shut down/convert botany before they've have 80 minutes to make goddamn tomatoes. Bonus points if you manage to not set up in the bar literally 5 seconds from where botany has been making tomatoes for 80 minutes.

**Comment by vcordie** [comment]
okay this is getting a bit ridiculous. the only reason tomatos were able to stop that clock cult is because of how bloody incompetent that clock cult was, not summoning after A GODDAMN HOUR. it took EATS AN HOUR TO CREATE HIS TOMATO ARMY. grudgecode, plain and simple.

**Comment by Kromgar** [comment]
Seriously joans obsession with clock cult has gone too far joan needs to be banned from coding clockcult for a month or two to cool off. 

Killer tomatoes are also stopped by doors and ranged weaponry also how did they get beaten by tomatoes when they have fucking marauders

**Comment by jughu** [comment]
RUN COWARD

**Comment by Kromgar** [comment]
Oh right and running tomatoes are so slow

**Comment by Nabski89** [comment]
I've seen two cults get taken down by tomatoes so far. One blood tried to summon in the middle of medbay. The other tried to summon in the bar on meta. The AI had said that they were growing tomatoes and someone should convert them before they tried to summon. Everyone ignored it, everyone lost. If they had spent the same amount of time making deadly bees instead, the cult would have been just as dead.

**Comment by vcordie** [comment]
exactly. its cult incompetence, not a balance issue.

**Comment by ChangelingRain** [comment]
something something... tomato power... is based... on potency...

**Comment by PKPenguin321** [comment]
Something something shit argument

**Comment by Ausops** [comment]
i don't like this solely because killer tomato strat is my favourite strat when I play plant vault in lavaland and want to kill megafauna, and it's only viable for me to do because I start as a pod person, no one disturbs me deep in lavaland, I start as a podperson, and I have unlimited mutagen

the average on station player isn't going to come up with max lethal killer tomatoes frequently enough for it to be a balancing issue

**Comment by Robustin** [comment]
I was with the blood cult that got fucked by a tomato army. The lesson there was the same as the lesson here, the tomatoes weren't the problem it was the cult taking too long to summon in a very public location and failing to secure the perimeter. 

Funny thing is I didn't feel the need to make a PR after tomatoes beat the cult. It was fine then and it's fine now.

I've shut down tomato assaults as a clock cultist this week too. I was able to cut off the botanist in a 1x1 hall and accidentally gave him a window to summon after I missed a conversion chance, he got out about 15 tomatoes but a single guardian, myself in clock armor, and one other cultist, single handled contained the situation without any casualties.

**Comment by Kromgar** [comment]
Better make gold slime cores a channel too amirite fellow cultists

**Comment by Kromgar** [comment]
Also we better make golems do half damage dont want an army of golems killing the cult oh no.

Oh and give them more slow down. Also hulks cant destroy brass walls any more its too op.


NOTHING SHALL STOP RATVAR SOON HE SHALL BE IMMUNE TO ALL FORMS OF HARM AHHAHAHAHHAHA

**Comment by Kromgar** [comment]
Shit that happens 1 in 20 or 1 in 50 cult rpunds MUST BR NERFED ALL HAIL RATVAR THE IMMORTAL NOW HIS AIRLOCKS CANT BE DESTROYED OR HACKED AHAHAHA

**Comment by Kromgar** [comment]
Oh and we better nerf the staff of storms because it can kill cultists so im just going to make ratvar armor ash storm proof.


BALANCE

**Comment by Emilc4h** [comment]
Kromgar buddy I think you're overreacting just a little tiny bit.

Maybe.

**Comment by Kromgar** [comment]
Well we've already had changeling rain instantly react to rounds that beat clock cult in unexpected ways twice. Making prs within 12 hours of the fucking round

First Swarmers

Now fucking tomatoes

**Comment by Doppeltongue** [comment]
Funny thing is, the blood cult loss, the clock cult loss, and the dead botanist Robustin was talking about are all the same botanist. This entire PR seems to be about one botanist who creates a tomato army in ~40 minutes of being left alone while doing their job and beat cult twice in like 20+ cult rounds.

**Comment by Kromgar** [comment]
Revised Edition: Joan the grudge coder

image

**Comment by MimicFaux** [comment]
Don't mind me, just stopping by to refill my salt shakers.

**Comment by Kromgar** [comment]
This isn't a tweek either its a major balance change

**Comment by ExcessiveUseOfCobblestone** [comment]
> using tomato's to kill megafauna

I'm not sure why but I really dislike ghost roles taking away content from the miners [tendies, megafauna, etc.]

**Comment by Kromgar** [comment]
@ExcessiveUseOfCobblestone ITs very rare considering you have to 

A: Find the megafauna you have no oxygen, and only glowberries to light your way. 

B: Its usually legion the least killed megafauna

**Comment by supernoodles13** [comment]
Kromgar, post once you muppet.

**Comment by FantasticFwoosh** [comment]
@ExcessiveUseOfCobblestone You can just fight the golems for taken loot instead, they are technically valid (and each corpse =minerals) if you want them to be, and you will be valid in return.

Though just try not to be a jerk about it that attracts ahelps.

**Comment by Kromgar** [comment]
@FantasticFwoosh 

Wait you can butcher golem corpses for minerals?

**Comment by KorPhaeron** [comment]
This is off topic and there is an entire z level to share with ghost roles

**Comment by Kromgar** [comment]
Regardless this PR is totally unneeded. Making clockwork watchers able to shoot simple mobs should be enough which joan has done. If the cult cant fight back against an army of 60hp tomatoes with magical spears, volt void, and an army of clockwork soldiers it doesnt deserve to summon ratvar

**Comment by optimumtact** [comment]
I don't know about this, because technically I think there should be a delay on waking killer tomatoes anyway

**Comment by vcordie** [comment]
there is a delay. you bypass it by activating a tomato, dropping it while it wakes up, then activating another tomato

**Comment by Kromgar** [comment]
👍 

@optimumtact They do have a delay

**Pull request closed without merging**
