### PR TITLE
Follow - highlight the name

### PR DESCRIPTION
**Pull request by psykzz**
Highlighed name can be clicked to start following the unit.
Mostly taken from #6780 just stole the code from AI to make it work via clicking the name.

### CODE REVIEW

**Comment by Miauw62** [comment]
Did you test this? Because this shouldnt work.

**Comment by psykzz** [comment]
No i havn't but why wouldn't it? If its call compose_message which inturn calls those procs?

**Comment by Miauw62** [comment]
It only runs compose_message if it's neccesary, which means that the message is composed only once for all humans/ghosts, so those procs are never called in the first place. They are called for the AI because theres a var somewhere that you can set to force it to always compose the message. IIRC that only works for mob/livings, too. (and it's inefficient because you'll always have to compose one message per ghost)

**Comment by psykzz** [comment]
So i looked into this a bit, and I only see force_compose (used by living when hearing) for the AI to force incoming heard messages to be with the follow topic. When dead however you just hear the rendered text from compose_message, with the inefficiency that already existed as all I am doing is placing the before and after link ( if a string concat is slow then yes this is a problem, but its already happening just with a 0 length string )

Explained a little further below.

Living use the following [say](https://github.com/tgstation/-tg-station/blob/master/code/modules/mob/living/say.dm#L79) which in turn calls [send_speech](https://github.com/tgstation/-tg-station/blob/master/code/modules/mob/living/say.dm#L138). [send_speech](https://github.com/tgstation/-tg-station/blob/master/code/modules/mob/living/say.dm#L160) renders the text once via [compose_message](https://github.com/tgstation/-tg-station/blob/master/code/modules/mob/living/say.dm#L169) which (as its not defined) is called via the standard proc defined in [code/game/say.dm#L37](https://github.com/tgstation/-tg-station/blob/master/code/game/say.dm#L37)

The only time force_compose ( used by AI ) is used is hearing when alive, [shown here](https://github.com/tgstation/-tg-station/blob/master/code/modules/mob/living/say.dm#L155)

**Comment by psykzz** [comment]
But on top of all that, i can test this myself before we continue with a merge.

**Comment by Miauw62** [comment]
Yes, I know how the code works, I'm the dude that wrote it in the first place.

The message is composed a single time, this is what all humans hear. This is, to be clear, WITHOUT tracking hrefs. This same message also appears to all ghosts. If you want ghosts to have a follow href, you would have to force every ghost to compose it separately or have send_speech() include its own entry for ghosts (and ensure that they are not included in the normal speakers!)

Say there's an alien outbreak. If somebody speaks, you'll have to compose your message 10-15 times, depending on the amount of aliens around. If it's also going to compose that message for every single dead player separately, you'll probably be at about twice that.

**Comment by psykzz** [comment]
Doesn't work, going to close and revise doing it later.

**Pull request closed without merging**
