### PR TITLE
Replaces old midi2piano with a new version

### PR DESCRIPTION
**Pull request by DeltaEpsilon7787**
I've made this one quite some time ago. Watch this https://www.youtube.com/watch?v=Oa7vbqFT2xs to see it in action.
It's supposed to be used with my newest music system (more specifically, synthesized sounds rather than prerecorded ones and a new instrument: synthesizer), but I am not ready to upload this one yet. However, you can still use it for regular musician.dm instruments.

Oh, and by the way, this code is a little bit crappy and does not comply to PEP8 at ALL, but it works and I can't be bothered with rewriting it properly.

Not sure if it works in Linux though, but I'm pretty sure it'd do fine.

### CODE REVIEW

**Comment by ExcessiveUseOfCobblestone** [comment]
Is there any advantage to using the 2013 one? if not, just remove it if that's possible.

**Comment by EditorRUS** [comment]
No, there is not.
I'm not exactly sure about deleting the old one though. I mean, this pull requests merely "adds" another midi2piano rather than outright replacing it.

**Comment by ExcessiveUseOfCobblestone** [comment]
ah, no big deal then. 

Just thought this was an upgrade to it.

**Comment by Jordie0608** [comment]
Just remove the old one.

**Comment by EditorRUS** [comment]
Done

**Pull request merged**
