### PR TITLE
Tourists now pay for their DAMN items again.

### PR DESCRIPTION
**Pull request by tralezab**
## Add no GBP this is an issue i made

Bad way of getting venue was runtiming and ending the proc that would pay for food.

## Why It's Good For The Game

fix

### CODE REVIEW

**Comment by Qustinnus** [comment]
no because with reagents the container is different.

**Comment by tralezab** [comment]
yeah i just figured that out in d*scord i'll edit doc accordingly

**Comment by Mothblocks** [comment]
> You currently have a negative Fix/Feature pull request delta of -5. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

i thought i fixed that

**Comment by Mothblocks** [comment]
oh wait no i did its because fix was applied after

**Pull request merged**
