### PR TITLE
Holobarrier toggle removal

### PR DESCRIPTION
**Pull request by deathrobotpunch**
## About The Pull Request
this PR removes the PENLITE holobarrier’s biometric scanner toggle function activated by hitting the holobarrier.

## Why It's Good For The Game
This is good for the game as having the toggle is quite useless because the only reason someone would have it up is to keep sick people out.

 There is no point to turning off the biometric scanning because you may as well have nothing put up in the first place.

This also prevents people from unknowingly turning it off allowing sick patients to infect valuable medical staff.
## Changelog
:cl:deathrobotpunch1
del: Removed the biometric scanning toggle from the PENLITE holobarrier
/:cl:

### CODE REVIEW

**Review by MrMelbert — CHANGES_REQUESTED** [review]
Remove the var if it's unused now, as well as the examine hint

**Comment by deathrobotpunch** [comment]
> Remove the var if it's unused now, as well as the examine hint

I can’t remove the var as it is needed for the scanning to function so I removed the toggle on it so it still works. though the examine message can go

**Comment by timothymtorres** [comment]
I'd say that this functionality should be reserved for emag effects, but I don't think we currently have that type of feature for holobarriers or holosigns.

**Comment by deathrobotpunch** [comment]
yeah and I don’t know shit about coding in emag effects

**Comment by deathrobotpunch** [comment]
> I'd say that this functionality should be reserved for emag effects, but I don't think we currently have that type of feature for holobarriers or holosigns.

yeah and I don’t know much about coding anyways

**Comment by deathrobotpunch** [comment]
didn’t the monkey business runtime fix PR merge? why am I still getting that error message?

**Pull request merged**
