### PR TITLE
Reverts seclite sprite change

### PR DESCRIPTION
**Pull request by TZK13**
seclite example
old seclite example

First one is the one that Pap just changed it to, second was my attempt to make it more suitable, third is the old sprite which this PR reverts it to.

### CODE REVIEW

**Comment by pudl** [comment]
how about you just change them back in general, since the sprite was stealth changed

**Comment by Anonus** [comment]
Didn't everyone say these were shitty? How'd they get in?

**Comment by TZK13** [comment]
I don't really wanna piss off Pap or maintainers by going for a straight revert.

**Comment by as334** [comment]
:+1:

**Comment by pudl** [comment]
go for a straight revert

**Comment by Anonus** [comment]
I don't care about pap's feelings, and you shouldn't either, because they clearly haven't cared about us saying no.

**Comment by Nienhaus** [comment]
Do a straight revert, TG likes the old ones better.

**Comment by TZK13** [comment]
Okay then if Nienhaus is okay with it that's the most important.

**Comment by paprka** [comment]
Default flashlights are flat and not diagonal. Diagonal makes the curvature on the lense bit look like garbage and nien's shading is better on the grip, that maglite texture is conveyed better if you look at it closer.

Also it generally looks better since you attach it to guns and if it's a giant flashlight it wouldn't attach to guns like that so I'll just revert the seclite attaching thing since it wouldn't make sense if you still want these xbox huge flashlights because some of us actually care about scale consistency. They'd suddenly be cut down in size when attached to guns and it'd look awful with this change. :-1:

**Comment by pudl** [comment]
lol

**Comment by paprka** [comment]
Also what the shit I could have swore i made those gunlight sprites bigger than they are now

**Comment by paprka** [comment]
Anyway yeah nah:

a8ad8bee-9824-11e4-9175-dba3131368cd



ass

Scale > MUH MAGLITE HUEG FLASHLIGHT

**Comment by TZK13** [comment]
Are you serious that is blatantly out of scale, there's no way somebody would mount a flashlight that large on a handgun. Maglites =/= flashlights dedicated for mounting on handguns.

I don't care though, it's a neat enough feature that I don't want to shit around about sprites with you when I have better things to be working on. Somebody else can do that if they want.

**Pull request closed without merging**
