### PR TITLE
Space Pirates

### PR DESCRIPTION
**Pull request by TrustyGun**
:cl:
add: A group of space pirates have been detected near Nanotrasen space stations. Crew is advised that they may target your station - be vigilant!
/:cl:

**[Image of the Ruin](http://i.imgur.com/CwEjoOi.png)** *Spoilers!*

**Playing as a Space Pirate**
The clothing set you spawn next to is actually space worthy.
A set of 4 pdas, 4 radios, and 4 e-cutlasses can be found in the foyer of the ship. 5 lanterns can be found around the ship for easier navigation around the cosmos.
Space pirates are honor bound and DO NOT KILL FOR NO GOOD REASON. They are only interested in getting dat booty.

### CODE REVIEW

**Comment by Militaires** [comment]
look at me




















































im the pr author now

**Comment by Haevacht** [comment]
So its a ghost role DESIGNED to raid shit with Eswords.

No.

**Comment by juanototo2** [comment]
>giving them free antag, traitor level gear, spacesuits, WHAT WERE YOU EVEN THINKING THIS IS EVEN WORSE THAN ROMEROL EVERY ROUND!!!!

**Comment by Militaires** [comment]
what people think will happen:

- pirates get down to business and kill people like they're in fucking city of god

what will actually happen:

- someone will say pirates and sec will tase them easily at a distance and/or flashbang them and then they or any of the other crew having guns will murder them cause they have no ranged weapons

**Comment by TrustyGun** [comment]
^

The only plus that pirates get over regular members is an e-sword and space suit. Otherwise they have less access than the librarian and have no other weaponry.

**Comment by Militaires** [comment]
double trouble: what will actually happen in a usual round.

- as pirate casualty increases and ruin distance is too far people will gradually abandon bothering to play pirates.

- pirates are a very easy to defeat enemy and thus an easy source of eswords.

- specific crew members will go out to space just to steal the cutlasses.

**Comment by Haevacht** [comment]
That double trouble is also an abhorrent result.

**Comment by ExcessiveUseOfCobblestone** [comment]
It's like ash walkers but the ash walkers actually have viable loot despite being the same difficulty?

**Comment by Haevacht** [comment]
Ash walkers don't get eswords.

**Comment by GunHog** [comment]
I would at least like to see it used for a few rounds to see how it goes.

**Comment by PKPenguin321** [comment]
Free eswords every round

Flashbacks to gateway missions

**Comment by ExcessiveUseOfCobblestone** [comment]
@Haevacht Stun weaponry.

**Comment by Haevacht** [comment]
Then they are loot pinatas. Being beatable does not make it good.

**Comment by Niknakflak** [comment]
Just another box shuttle

**Comment by ExcessiveUseOfCobblestone** [comment]
Sorry if my message came across as in favor to this.

I am not.

**Comment by Repukan** [comment]
FREE ESWORDS

**Comment by Armhulen** [comment]
>Space pirates are honor bound and DO NOT KILL FOR NO GOOD REASON. They are only interested in getting dat booty.

WHAT

**Comment by Armhulen** [comment]
i mean i want this but you're probably going to have to rework it for it to work

**Comment by calzilla1** [comment]
PEOPLE, THE REAL LOOT IS THE TOOL BOXES

**Comment by Repukan** [comment]
All around flawed and horribly thought out idea. In my opinion. 

Loot pinatas is only going to make people powergame it to get free weapons. Hell we already have this problem with people rushing to the space bar to dismantle their teleporter and build telescience before the 5 minute mark.

**Pull request closed without merging**
