### PR TITLE
Buffs breathing gas conversion

### PR DESCRIPTION
**Pull request by Cyberboss**
IT'S TOO DAMN LOW!

This will multiply the rate o2 is converted to co2 by 6.25 (For standard carbon lungs). Still low as fuck but it needs a buff badly (probably bigger than this) because people will never even realize we exhale CO2 unless they go codiving to find it.

### CODE REVIEW

**Comment by coiax** [comment]
For reference (https://en.wikipedia.org/wiki/Breathing)

>The air we inhale is roughly composed of (by volume):
> - 78.62% nitrogen
> - 20.84% oxygen
> - 0.96% argon
> - 0.04% carbon dioxide
> - 0.5% water vapour

> The permanent gases in gas we exhale are 4% to 5% by volume more carbon dioxide and 4% to 5% by volume less oxygen than was inhaled. This expired air typically composed of:[11]
>- 78.04% nitrogen
>- 13.6% – 16% oxygen
> - 4% – 5.3% carbon dioxide
> - 1% argon and other gases

**Comment by coiax** [comment]
Also, this is probably feature frozen, since it's really balance? But everyone seems to not care about the freeze anymore.

**Comment by Iatots** [comment]
Look, one tile (2.5m^3) holds approximately 0.1 moles of ideal gas at normal conditions. 
The volume of your breath holds around 0.00002. Of that, 5% is turned into CO2 every few seconds; that's not a lot. 
I can't for the life of me read any of the code, but I know CO2 is currently at least 7 times as lethal as it already is in real life, because in-game 1% CO2 is enough to start choking you while IRL that concentration is non-asphyxiating. Yes right now atmos has the depth of a puddle and half the gasses are ez grief-in-a-can bullshit, but this PR will just gut internals and maybe create choking clouds in maintenance away from the station's magical air filters thanks to the slow gas mixing. What exactly are you trying to achieve here?

**Comment by Cyberboss** [comment]
This won't affect internals at all. All the gas you breathe in from internals is already put on the turf when you exhale. Also, it currently takes something like 4 hours of breathing in a 1x1 room to start choking, I don't think we need to worry about maintenance choking happening even a percentage of rounds.

**Comment by Iatots** [comment]
Ok so you are just having more CO2 produced per mole of O2 consumed?
Is it currently not 1:1? Coiax referencing IRL stats make me think the current values are flawed but as I said, I can't read code to save my life.

**Comment by duncathan** [comment]
wtf no lol
co2 exhalation is designed to be inconsequential
also freeze

**Comment by Iatots** [comment]
> co2 exhalation is designed to be inconsequential
Do you have a single fact to back that up?

**Comment by duncathan** [comment]
yes, the fact is that I am in charge of atmos. as the system currently is and is being advanced towards, co2 exhalation is intentionally inconsequential. for the most part increasing the conversion ratio to anything effective would necessitate activating turfs due to breathing which is something that will never happen.

**Comment by Cyberboss** [comment]
Turfs have been activated by breathing for a long time

**Comment by duncathan** [comment]
sorry I wasn't clear; what I mean is that breathing being effective enough that it would cause actual active turf calculations regularly vs the rare cases where it can happen now is not going to happen because having actual active turfs (rather than stuff without a big enough delta to actually activate) all the time would be a huge drain on performance

**Pull request closed without merging**
