### PR TITLE
New Icebox Ruin - Syndicate Biodome

### PR DESCRIPTION
**Pull request by GremlinSeeker**
## About The Pull Request
**A Dangerous Ruin Approaches!**

A new high-risk, high reward ruin for icebox! Featuring some very dangerous enemies for some goodies.

Small puzzle element included find the keycard to open the research directors office to lift the lockdown on the security post, from there you can lift the lockdown on the surgical rooms, all the while encountering feral gorillas.

## Why It's Good For The Game

Icebox lacks some dangerous ruins with decent loot. The loot here is a WIP and I'm hoping can be discussed. I know icebox still is in need of some ruins and I had some ideas and threw this together. The map size is 45x45. I made it so you also can't just bee-line and cheese it by adding indestructable shutters, windows, and walls, along with a noteleport area flag to prevent cheesing of the area. 

In-game rendered screenshots:

image

image

Editor Screenshots:

image

image

Notable loot Spawns:

image

image

image

image

image

image

## Changelog
:cl:
map: New Icebox  Ruin "Syndicate Biodome" added.

/:cl:

### CODE REVIEW

**Comment by carlarctg** [comment]
the 'weak antag gear' spawners are deprecated garbo, they have like night vision goggles and nothing else iirc

**Comment by norsvenska** [comment]
antag gear weak can spawn:

normal medkit
toxin medkit 
brute medkit
burn medkit
syndicate toolbox
diamond drill borg upgrade
butcher knife
night vision goggles
diamond drill

so yeah not particularly good

**Comment by Loafin34** [comment]
syndicate tome is a bit weird.. could you make it give you some spess-only loot? like Syndicate Explorer suits, maybe a tranquilizer gun to shoot the monkeys with?

**Comment by GremlinSeeker** [comment]
> syndicate tome is a bit weird.. could you make it give you some spess-only loot? like Syndicate Explorer suits, maybe a tranquilizer gun to shoot the monkeys with?

yeah, like I said WIP right now I'm kind working how you'll encounter the gorillas. I want you to just 1v1 each one because they can just insta-kill you if they do manage to touch you. I also am aware of the possibility of just breaking in through the windows so I'll make them indestructable.

**Comment by zoomachina** [comment]
Those are the nerfed genetics gorillas, right? Are those actually dangerous nowadays?

**Comment by zoomachina** [comment]
Honestly loot is fine imo, it's certainly not underpowered from what I'm seeing on the screenshots

**Comment by Loafin34** [comment]
> > syndicate tome is a bit weird.. could you make it give you some spess-only loot? like Syndicate Explorer suits, maybe a tranquilizer gun to shoot the monkeys with?
> 
> yeah, like I said WIP right now I'm kind working how you'll encounter the gorillas. I want you to just 1v1 each one because they can just insta-kill you if they do manage to touch you. I also am aware of the possibility of just breaking in through the windows so I'll make them indestructible.
> 
> Tinkering with the miner's hardsuit and making a more syndicate flavored version.

there's literally a syndicate hardsuit don't worry https://github.com/tgstation/tgstation/pull/75762

**Comment by MoonDeer728** [comment]
> syndicate tome is a bit weird.. could you make it give you some spess-only loot? like Syndicate Explorer suits, maybe a tranquilizer gun to shoot the monkeys with?

no

**Comment by Admiral-Gigaton** [comment]
yo quick thing, last I checked syndie tome was an antag checker (I think, if im right, you can use it as a non antag, but if you use it on anyone but an antag it hurts or doesnt heal them) which makes it probably a no-go for civilian access type shit. replace it with something different? eg. chameleon kit, combat wrench, etc.

**Comment by GremlinSeeker** [comment]
> Those are the nerfed genetics gorillas, right? Are those actually dangerous nowadays?

Yes, they are. Infact I chose them specifically since it's sorta close quarters that you dont have a chance to get instant knocked down and die.

> Honestly loot is fine imo, it's certainly not underpowered from what I'm seeing on the screenshots

Honestly, just waiting on maintainer approval.

> yo quick thing, last I checked syndie tome was an antag checker (I think, if im right, you can use it as a non antag, but if you use it on anyone but an antag it hurts or doesnt heal them) which makes it probably a no-go for civilian access type shit. replace it with something different? eg. chameleon kit, combat wrench, etc.
 
 Chameleon Kit would be nice I think.

**Comment by YuliceTheDruid** [comment]
Couple things for the loot; Resin Spinner requires a Plasma organ to draw from or else it's functionally useless; Alien Eyes (and the Alien Liver and Stomach), being regular organs and not 'implant' organs, actually decay, so if they are laying outside of an organ fridge then they will likely be completely destroyed by the time anyone clears the ruin, let alone finds it.

**Comment by SmArtKar** [comment]
I like the vibe of this ruin but the amount of loot is questionable, you probably should remove one of the toolboxes and stechkins, lenses are also quite strong.

**Comment by LemonInTheDark** [comment]
image

**Pull request merged**
