### PR TITLE
Hulk punches no longer ignore armor entirely

### PR DESCRIPTION
**Pull request by ChangelingRain**
:cl: Joan
tweak: Hulk punches no longer ignore armor entirely.
/:cl:

Whaaaaat. No, this is bullshit. Take your free 15 force hands and fuck off.

### CODE REVIEW

**Comment by KorPhaeron** [comment]
>free
>can't use ranged weapons

???

**Comment by ChangelingRain** [comment]
free as in genetics hands them out for free yes

**Comment by SweaterKittens** [comment]
@KorPhaeron Like they need to, being completely stun immune and almost certainly paired with x-ray/invisiblity/dwarfism.

If you don't think Hulk is a big ol' stinky pile of doo-doo, don't talk to me or my son ever again.

**Comment by KorPhaeron** [comment]
Hulk got high damage hands that ignored armour because we took away their stun hands though

**Comment by ChangelingRain** [comment]
If you want to buff hulk damage be my guest but they shouldn't totally ignore armor because that's bullcrap.

**Comment by KorPhaeron** [comment]
What is wrong with ignoring armour

**Comment by PKPenguin321** [comment]
Yeah seriously, just like walk away or some shit seriously

**Comment by PKPenguin321** [comment]
Fucking anti hulk memes I'm triggered. Just fucking get good at straight 1v1 back and forth combat, or just straight up shoot them. You can even just walk away if the need be, not like they're gonna shoot after you.

Stop with all these PRs that change the game because you're bad at it.

**Comment by Durkel** [comment]
20 Minutes of work for the ability to punch for 15 damage through armor

10 seconds to build a 18 brute spear which also has a knockdown chance, a embed when thrown, doesn't restrict your weapons, can be used to break down most airlocks by throwing, Doesn't make you scream like a retard, Can decapitate limbs, and doesn't make you non human.

**Comment by Haevacht** [comment]
Spears can be disarmed, and you can get stunned while using them. Durkel that is a shit comparison and you know it.

**Comment by SweaterKittens** [comment]
I like how everyone completely looks past the **COMPLETE STUN IMMUNITY** which is the best and most broken part of hulk. This will hardly change anything, geneticists will still get it in 10 minutes with all the other powers and proceed to validhunt traitors at their leisure, through walls with x-ray/tk/chameleon too.

**Comment by PKPenguin321** [comment]
Two guys with fire extinguishers > one hulk.

Notice how stuns aren't even part of that. Notice how that doesn't even account for just lasering them. Notice how it uses one of the most common weapons in the game, which could easily be changed to say, a spear, which would only need one guy to beat a hulk with.

This is not a code problem, this is you all sucking at the game and losing your shit the second your stun batons, tasers, ebows, cult stun shit, etc, stops winning your fights instantly.

**Comment by TheNightingale** [comment]
If hulk punches ignore armour, that also means they ignore riot armour, which is supposed to be a hard counter to hulks.

**Comment by Durkel** [comment]
We were able to take down hulks when they were still able to use guns. we were able to take down hulks when they could stun punch. Try applying some strategy to a fight instead of mindlessly trying to stun baton or tase something.

Hulks aren't immune to disablers, Shoot them three times and throw shit at them, or better yet, just go get a shotgun from sec and light them up.

**Comment by SweaterKittens** [comment]
PK why don't you calm down with the Robustin-tier bitchfit, damn dude. Hulks are annoying and one of the least fun and most complained about aspects of the game. I wouldn't miss them if they were gone completely, to be honest. And they'll still be good after this. 

Also it's a pretty bold assumption that "I ded pls nerf" rather than this being brought up from observing a thousand rounds where the same people get all the genetics powers every round and either use them to validhunt or cause their team to stomp, consistently.

**Comment by KorPhaeron** [comment]
So come up with an interesting replacement that will make people happy instead of whittling them away into irrelevance

**Comment by Arianya** [comment]
>Guys don't remove hulk just nerf the parts that are problematic!

> WHAT THE FUCK GUYS WHY ARE YOU NERFING HULK REEEEEEEEE

Hyperbole aside, too much shit ignores armour at the moment. Armour penetration should be something special/specialized, not just dished out like candy.

Armour should be useful _in most standard threats that come against the station_ or else the armour is worthless. Riling up sec or someone wearing armour should be a risky affair due to their damage mitigation, not just "lolnope penetrated"

@KorPhaeron Would you approve of hulk being swapped out for armblade then? This is an interesting replacement.

**Comment by ShadowDeath6** [comment]
Was the armor penetration _really_ an intended feature? 
Even if people emit salt and stop this from being merged in its current state, it should provide some feedback that your full riot suit is actually worse than being totally naked versus a geneticist.

**Comment by SweaterKittens** [comment]
Things like mutations have drawbacks and having to take some disabilities with your superpowers have been suggested forever. But, no one bothers coding it or making it happen, so we're stuck with current shitty system where we have to balance of series of near-direct upgrades that can be obtained within the first 10 minutes of the match, and breaks several gamemodes.

**Comment by KorPhaeron** [comment]
Being able to punch other people is literally the least offensive part of hulk, this does nothing to address

1. It being essentially infinite

2. Access to every room for everyone forever once it spreads

3. The taser immunity which throws security into chaos 

@Arianya 

Yes

**Comment by YakumoChen** [comment]
healing hands instead of hulk would be nice. The most obnoxious part about Hulk is the free all access and stun immunity, which breaks the game for so, so many antags (notably AI)

**Comment by jughu** [comment]
@korphaeron doesnt really throw sec in chaos just disable it and it isnt even a threat

**Pull request closed without merging**
