### PR TITLE
Quote the armor lists

### PR DESCRIPTION
**Pull request by Cyberboss**
About time

`(armor.*=.*list *\(.*)(melee|bullet|laser|energy|bomb|bio|rad|fire|acid|magic)(( |=).*\)) => $1"$2"$3`

Has to be run multiple times until finished

### CODE REVIEW

**Comment by coiax** [comment]
Why?

**Comment by ExcessiveUseOfCobblestone** [comment]
qutoes ples

**Comment by Cyberboss** [comment]
All unquoted list associations do is cause confusion. Eventually, it will propagate and cause people to think that you can use vars as list keys in the `list()` proc, which you can't. This has been the code standard for a long time now.

**Comment by lzimann** [comment]
Also it's on [CONTRIBUTING.md](https://github.com/tgstation/tgstation/blob/master/.github/CONTRIBUTING.md#use)

**Pull request merged**
