### PR TITLE
Cleans up leftover palette

### PR DESCRIPTION
**Pull request by ShizCalev**
There were palettes of various plating variants left in the boundary wall in the SW corner.

### CODE REVIEW

**Comment by WJohn** [comment]
Oh I kept these intentionally as I updated these quite often when they were released, and wanted to be able to easily put in damaged turfs with all their modified variables in short order.

Whatever though, because I no longer update these maps or make away missions when they're so totally unused.

**Comment by Iamgoofball** [comment]
Move them to space wj

**Comment by WJohn** [comment]
Both of these are planetside missions, so that's not possible. MO19 takes place on a moon, and UO45 is underground in a heated plasma pressure pocket.

**Comment by Iamgoofball** [comment]
Welcome to sacrificing some lore for gameplay in the video game

**Pull request merged**
