### PR TITLE
Lollipop sprite fix

### PR DESCRIPTION
**Pull request by FluffTheMoth01**
Signed-off-by: Space Prius <bubba041102@gmail.com>

## About The Pull Request
Somebody pointed out some problems with the sprites, they are now fixed.

## Why It's Good For The Game
I M M E R S I O N.

## Changelog
:cl:
fix: Lollipop stick mask sprite is now fixed.
/:cl:

### CODE REVIEW

**Comment by Akrilla** [comment]
Fixes #45525

**Review by ShizCalev — CHANGES_REQUESTED** [review]
doesn't need to be an animation
west facing sprite is now messed up.

**Comment by SpacePrius** [comment]
fixed
image

**Comment by SpacePrius** [comment]
fixed, the sprite on the west facing direction now actually sits properly.

**Pull request merged**
