### PR TITLE
Closet overlay refactor

### PR DESCRIPTION
**Pull request by Jordie0608**
This refactors closets (and bin) to use overlays for doors, reducing the number of icons in closet.dmi by 55KB; see pictures below.

Icons for crates have been exported from storage.dmi to crates.dmi. Crates have not been refactored with overlays as they only have two states, overlays would increase the number of icons in the file.

Fire axe cabinets, extinguisher cabinets and the unused ugly wall safes have been moved to wallmounts.dmi; I'm going to get around to reworking these a bunch in a future pr, for now the files have a few WIP icons in them.

Misc changes also include the removal of some unused icons and defines as well as collation of existing ones and small organization improvements.

This touches a lot of files, merge conflicts are likely.

beforeolverays
afteroverlays

### CODE REVIEW

**Comment by MrPerson** [comment]
>merge conflicts are likely
>there already is one

**Comment by Incoming5643** [comment]
We were told, but didn't listen!

**Comment by Jalleo** [comment]
:+1:

**Comment by WJohn** [comment]
I'm hoping you can still edit what closets are like on the map maker, I do a lot of that on my away missions and would be pretty sad to see that function go.

**Comment by phil235** [comment]
@WJohn  Pretty sure you still can by editing icon_state and icon_door.

**Comment by Jordie0608** [comment]
@WJohn You can.

**Comment by Cheridan** [comment]
I'm gonna priority merge this due to the nature of the PR (simple refactor across significant amount of dmi and dm files)

**Comment by pudl** [comment]
ITS ALL BROKEN

E V E R Y T H I N G

**Comment by astralenigma** [comment]
I have a good question @Jordie0608 How would I add an overlay to a crate of for example a manifesto, on the update_icon?

**Comment by Jordie0608** [comment]
@astralenigma 
```
if(manifest)
overlays += manifest_icon
```

**Pull request merged**
