### PR TITLE
Input-based teleportation paper no longer allows you to abuse the delay in inputting a location

### PR DESCRIPTION
**Pull request by ChangelingRain**
:cl: Joan
bugfix: You need to be holding teleport talismans and wizard teleport scrolls in your hands when you finish the input, and cannot simply open the input and finish it whenever you get stunned.
/:cl:

Very funny. I don't want to see you doing it again.

### CODE REVIEW

**Comment by TechnoAlchemisto** [comment]
The most ancient wizard Powergame technique, finally killed. I'm pretty sure this was on the old misc tips page rip

**Comment by PKPenguin321** [comment]
This is definitely a legacy tactic. Kind of sad to see it go.

**Comment by Iamgoofball** [comment]
:-1: ITS A FEATURE

**Comment by PKPenguin321** [comment]
in the arrrrms offff an aaangel

**Pull request merged**
