### PR TITLE
chainsaws rebalance, but working this time :)

### PR DESCRIPTION
**Pull request by ghost**
Fire axes:
Can be held in one hand for space.
Can be held on back for space.
Deals 24 damage.
Found in atmos and bridge
Chainsaws:
Must use 2 hands at all times
Cannot be stored anywhere on body
Deals 21 damage
Found nowhere, must be crafted with plasteel (engineering or mining), circular saw(robotics or medical and you can't take it as they NEED it for surgery, maybe cargo but i'm not sure on that), and wire. some tools needed.

Now chainsaws will be more expensive to create, but stand up as something that's worth both of your hand slots.

### CODE REVIEW

**Comment by KorPhaeron** [comment]
>engineering or mining

Or the stack of 50 in the EVA foyer

And yeah you can make essentially infinite circ saws in cargo so it just takes the QM going "AI door" to churn out 50 of these things

**Comment by Armhulen** [comment]
>Or the stack of 50 in the EVA foyer
Only on some maps, and I think it's ten. I'll double check but I think you need 5 plasteel for each chainsaw, so a max of two

>And yeah you can make essentially infinite circ saws in cargo so it just takes the QM going "AI door" to churn out 50 of these things
See above, you can only make two unless I'm wrong

And even then, getting plasteel from EVA and printing saws takes longer than a fire axe that will always be two doors away from obtaining. Which, by the way, does more damage and is way easier to carry around.

**Comment by KorPhaeron** [comment]
/datum/crafting_recipe/chainsaw
	name = "Chainsaw"
	result = /obj/item/twohanded/required/chainsaw
	reqs = list(/obj/item/circular_saw = 1,
				/obj/item/stack/cable_coil = 1,
				/obj/item/stack/sheet/plasteel = 1)


dumb frog poster

**Comment by Armhulen** [comment]
heck i'll change that right now! doesn't seem that hard.

**Comment by Armhulen** [comment]
there, done like a true pro coder

**Comment by calzilla1** [comment]
Make it 25 or 26. They replaced axes with chainsaws for a reason!

**Comment by Armhulen** [comment]
you'd be suprised at the balance jump 24 > 25 is, it's the difference between 5 hit kill and 4 hit kill

**Comment by XDTM** [comment]
Justified, i'd say

**Comment by The-clown-known-as-Pepe** [comment]
@Armhulen dumb frog, increase the damage of chainsaw hand too

**Comment by Ratvar** [comment]
@Armhulen , increase damage of DOUBLE chainsaw hands? Convert meme into fair trade of hand slots for free damage.

**Comment by DoctoreMad** [comment]
This is still a meme PR that buffs the powergamer's mainstay. Robotics can get a chainsaw roundstart and is encouraged to do so for faster surgery. Platsteel nerf does something at least since it means you can't decon things for platsteel in the main station as quickly anymore, but still, really?

**Comment by PraiseRatvar** [comment]
why can spessmen craft chainsaws ez pz? how do they make a fucking chainsaw out of a **C I R C U L A R** SAW

**Comment by Armhulen** [comment]
pepe i'll fix the hand
ratvar, out of scope for pr mkay
doctore, powergamers will just use the fireaxe if they need a weapon, it' would still be better than a chainsaw
also ratvar, i increased the price a bit

**Comment by PopNotes** [comment]
energy chainsaw traitor item when

just like good old times

**Review by Cyberboss — APPROVED** [review]

**Comment by Cyberboss** [comment]
>First time contributor

wut?

**Comment by Armhulen** [comment]
has nobody ever contributed for the first time before?

**Comment by Cyberboss** [comment]
absolutely not

**Comment by Tacolizard** [comment]
5 plasteel PogChamp

**Comment by Tacolizard** [comment]
glad to see my little admin sprouting wings and making useless balance PRs 👏

**Comment by Armhulen** [comment]
still less useless than chainsaws are right now

**Comment by Armhulen** [comment]
also i've already contributed I added the syndicate vendor sprite

**Comment by Tacolizard** [comment]
@Armhulen I just said useless because I couldn't think of a good adjective. I guess I really should've said 'small' or 'inconsequential'.

also spriting != coding

**Comment by Tacolizard** [comment]
the plasteel price is a little steep though. It would be better to add more types of materials instead of more of the same I think

**Comment by Armhulen** [comment]
it's just so people can't spam out chainsaws

**Comment by PraiseRatvar** [comment]
how about uhhhh make it so you can't craft chainsaws out of c i r c u l a r saws? 

how about removing the crafting menu completely 🤔

**Comment by Tacolizard** [comment]
@PraiseRatvar is this a next level shitpost

**Comment by Tacolizard** [comment]
@Armhulen if someone is set on spamming out chainsaws, say, during a rev round, then they'll find the resources to do it regardless of price. Robotics, where chainsaws usually come from, only has enough materials for one iirc

**Comment by Armhulen** [comment]
@PraiseRatvar lol!
@Tacolizard if they run to cargo and dispense some saws (2 minute job if you're quick) they can make 10 chainsaws. Now they can only make 2.

**Pull request merged**
