### PR TITLE
Makes IC issues more literal

### PR DESCRIPTION
**Pull request by silicons**
Adds icees to the game.
Gives people icees when their ahelp is marked as an IC issue.
Icees decrease your body temperature gradually if it's above the maximum over which you take burn damage, and provides minor amounts of nutriment!
Sprites by @chanoc1 
icees

### CODE REVIEW

**Comment by RandomMarine** [comment]
Unfortunately, I'm sure Icee is trademarked or something,

**Comment by kevinz000** [comment]
It is? Fuck.

**Comment by chanoc1** [comment]
it is

**Comment by kevinz000** [comment]
damnit someone give me an alternative name .

**Comment by chanoc1** [comment]
IckEE

**Comment by kevinz000** [comment]
whatever someone else pr this ;-;

**Pull request closed without merging**
