### PR TITLE
Slows down natural blood generation

### PR DESCRIPTION
**Pull request by Mickyan**
:cl:
balance: Natural blood generation has been halved
/:cl:

Alternative to #44497

From testing, in an optimal situation it takes 5 minutes to go from a just above survivable blood level (475) to stable (560), hence blood loss can often be kept in check by stabilizing the symptoms for a short amount of time rather than tackling the issue directly

This retains the usefulness of salglu for stabilizing patients while making it much harder to rely solely on natural blood regeneration to do all the work without having to seek a proper treatment (particularly in severe cases)

Now a define cause they are fun, cool and easy to change

### CODE REVIEW

**Comment by ishitbyabullet** [comment]
Let's say Saline-Glucose is nerfed to be completely useless for blood regeneration because there's a PR for it right now:

> This retains the usefulness of salglu for stabilizing patients

well i guess your idea is ruined now.

**Comment by Shapsy** [comment]
Yeah I mean I feel like natural blood regen is fine as is, add more ways to lose blood quicker instead

**Comment by Mickyan** [comment]
You don't notice blood loss because you regenerate faster than you can possibly get hurt for in most situations

> well i guess your idea is ruined now.
How did you manage to type this without being able to read

**Comment by ishitbyabullet** [comment]
@Mickyan 
While it wouldn't actually make the pr useless, if there is nothing to stabilize with then the odds of someone getting screwed over because "shit we ran out of blood that is useful (for the patient) and no one bothers giving blood" are very likely. I don't think that sounds fun tbh.

Though maybe I underestimate the power of iron or some chem I can't even think about right now therefore none of this is a worry.

**Comment by wesoda25** [comment]
Its perfect as is

**Comment by Mickyan** [comment]
@ExcessiveUseOfCobblestone this is your department I think

**Comment by Swiftkor** [comment]
I like this, keeps salglu’s original function while keeping it from being better than using actual blood in the majority of cases.
Also being able to regenerate almost half of your blood back in 5 mins is kinda silly

**Comment by ishitbyabullet** [comment]
@Swiftkor You do realize you said 5 minutes, right?

It's 5 minutes. Cloning can easily be shorter with one upgrade, I think. I actually think non-upgraded cloning wouldn't take 5 minutes at all though I never kept track of the time.

The shuttle timer itself is 10 minutes normally assuming it stays on blue alert. That means that by the time you regenerate, the shuttle is almost at the station. It's clearly not a short time.

**Comment by Dawson1917** [comment]
Alternate PR: buff blood regeneration because nobody likes having to beg or buy salglu after a doctor/sec/assistant did a marathon around the station while dragging your critted body to medbay

also make other sources of bleeding actually threatening instead of nerfing the recovery time, fast damage fast recovery is better appreciated on tg than slow damage slow recovery and this has been proven countless times

**Comment by shellspeed1** [comment]
I like the idea of adding more sources of bleeding and making bleeding more severe. Would give doctors and janitors both something to do.

**Comment by ExcessiveUseOfCobblestone** [comment]
I guess the question is

What are you (and 44497) actually trying to fix and, more importantly, does this PR (or 44497) actually fix that?

If the issue is blood damage is pretty braindead in handling from a medical standpoint, is it because the treatments are really easy to cure even the steeper ranges of blood loss or is it because bloodloss never really gets to the steeper ranges to begin with, or heck even a bit of both? I haven't really looked into it but my current theory is team shaps, I think bloodloss is negligible to begin with making it really easy to shrug off especially when combined with the chems that are designed to mitigate it at all ranges.

**Comment by AdamElTablawy** [comment]
Natural blood regen is fine and nobody really likes bloodloss, because severe bloodloss is hilariously debilitating and usually kills you, where minor bloodloss is a minor annoyance but does nothing at all, including slowdown.

All that will do is make it more annoying if you get dragged while in crit to heal off the bloodloss, and you'll have a mildly fuzzy tint to your screen for a while. Five minutes is quite some time, honestly.

**Comment by Mickyan** [comment]
@ExcessiveUseOfCobblestone My gripe with bloodloss isn't really with the ease of treatment, rather it's presented as a less immediate, more long term injury but the speed at which it regenerates means any type of bloodloss that isn't presently fatal is very unlikely to ever build up to become a problem, hence bandages sit unused, transfusions are rare, blood is cheap and expendable! 
This is functional but a wasted opportunity to add more long term penalties to getting injured one too many times and relying too much of first aid kits to get back up good as new.

So my interest isn't really in nerfing salglu or blood loss treatment, it's more of a byproduct of making blood loss not heal by itself so quickly

**Comment by Mickyan** [comment]
WJohnston graciously shared some of his in-depth testing for blood loss, check it out

https://pastebin.com/raw/3d6qyxG5

One point of interest I want to bring attention to: assuming the standard healing rate of 0.5, you can indefinitely survive and regenerate the bleeding caused by 38.4 points of brute damage

**Comment by WJohn** [comment]
This is based on your nutrition level. 0.5 blood/tick regen only occurs when you're full. Otherwise you'll find most crewmembers hanging around 0.3 blood/tick.

**Comment by Mickyan** [comment]
That's a very good point actually, I'm going to add a define for the nutrition drain as well

**Comment by Mickyan** [comment]
bumped up regen to a nice round half of what it used to be initially, nutrition drain is also halved to fit the slower regeneration

**Comment by anconfuzedrock** [comment]
theory: blood regen can by default outheal minor bleeding because it'd be stupid if a guy with 20 brute would just keel over and die if he didn't get help from an actual doctor within 5 minutes?

**Comment by optimumtact** [comment]
I think maybe we will try to do some other things, like adding more ways to lose blood first sorry.

**Pull request closed without merging**
