### PR TITLE
Removes a leftover 0 from bot ui

### PR DESCRIPTION
**Pull request by JohnFulpWillard**
## About The Pull Request

Removes a 0 at the very right of the Bot UI, if they can't be possessed (so secbots)
image

## Why It's Good For The Game

why is that there

## Changelog

:cl:
fix: Bots that can't be controlled (like beepsky) no longer has a stray 0 at the very right side of its UI.
/:cl:

### CODE REVIEW

**Comment by Sealed101** [comment]
nice get

**Comment by ZephyrTFA** [comment]
not gambling related

**Comment by Ghommie** [comment]
Not a good justification for closing an actual fix to the UI.

**Comment by Fikou** [comment]
let him cook

**Comment by MrMelbert** [comment]
Help

**Comment by san7890** [comment]
wait why did this inflate the size of `rust-g.dll` by 1 megabyte

**Comment by JohnFulpWillard** [comment]
I didn't touch it man

**Pull request merged**
