### PR TITLE
fixes for Delta and Kilo

### PR DESCRIPTION
**Pull request by spockye**
## About The Pull Request
This PR makes some small fixes to Delta and Kilo station. 
mostly fixes to piping, disposals, space decals, and zoning!

examples:
image

image

image

image

these aren't all the changes made, but a couple of them. 
### Mapping March
Ckey to receive rewards: spockye

## Why It's Good For The Game
less errors = good! 
whenever changing something on a map, please make sure that things like disposals weren't borked in the process!
## Changelog
:cl:
fix: fixed piping on deltastation
fix: fixed piping on kilostation
fix: fixed disposals on deltastation
fix: fixed disposals on kilostation
fix: fixed zoning on deltastation
fix: fixed zoning on kilostation
/:cl:

### CODE REVIEW

**Comment by Jolly-66** [comment]
I swear to CHRIST the area bullshit constantly happens on Kilo.

**Comment by san7890** [comment]
in the future it would be nicer if you could split up your PR into two (one touching Delta, one touching Kilo) and then earmarking that PR as "A bunch of delta minor fixes". it's okay for now just for next time (unless you want to split apart this PR's branch into two right now)

**Comment by Time-Green** [comment]
You have a merge conflict

**Comment by spockye** [comment]
Out of town for a while. I'll draft this meanwhile

**Pull request closed without merging**
