### PR TITLE
Armor rune updated to allow multiple choices based on what you are we…

### PR DESCRIPTION
**Pull request by Sabbat**
Updates the cult armor rune to let you get additional equipment or abilities based on what you're wearing or holding. Adds FUN.

Some nerfed versions of wizard spells can be used by the cult in exchange for unique clothing, these spells require the cult robes or armor in order to use. No armor choices are mandatory you will always have the option of the default choice if all you want is the sword and armor/etc. They are just extra choices for FUN.

"Zealot": Default armor rune. If none of the required clothing is worn this will be chosen automatically. Is the same as ever.
"Summoner": If you are wearing the wizard robe and hat when using the armor rune this choice will be available. User will receive magus robes and hat and nerfed versions of the summon shard and summon shell spells.
"Traveler": Available to people wearing EVA suit and helmet. Replaces the EVA suit and helmet with the cult space suit and space helmet. Gives you a sword.
"Marauder": Available to people wearing the captain's space suit and helmet. Same as Traveler except user is given a spell of summon creature (two creatures). They can and will attack the user.
"Trickster": Available if wearing the RD's reactive teleport armor. Gives you magus robes, a wand of doors, and a nerfed version of Blink.
"Physician": Available if wearing the CMO's labcoat. Gives you a wand of life. 

All of the wands can easily be lost to non-cultists and have the normal limited charges. (Wand of life only has 4 charges.) All spells require the cult robes or space suit, normal armor will not work for casting them.

Like I said, can easily be updated to allow more clothing or items to give the user certain things. I was thinking things like hand teleporter in exchange for teleport spell. That kind of thing. The possibilities for FUN are endless.

I do not know why the beginning cut off but I changed it.

### CODE REVIEW

**Comment by optimumtact** [comment]
Someone finally giving the unloved game mode some love

:+1:

**Comment by Kromgar** [comment]
Can you add the option if you have a rig to turn your suit into a cult space suit?

**Comment by Kromgar** [comment]
Sacrificing stuff for powers seem cools

**Comment by Cheridan** [comment]
Wand of Death is too strong to be passed out outside of Summon Magic, it's only fine there because there are unlimited-use Staves of Life that are typically created along with it.

**Comment by Boredone** [comment]
So a Cargo Cult is pretty much a human artificer cult?
As Cargo can order wizard suits for pretty much arming the whole cult with magic.
That doesn't sound too bad personally, but figured it was worth mentioning.

**Comment by Sabbat** [comment]
@Cheridan  wands are stopped by literally everything including tables and at two uses the wand of death is actually a pretty weak weapon unless it's used while the cult is still stealthed (In which case you could have used a stun paper for a similar effect). As well as the fact they'll probably just lose it or hit an ally half the time. I fucked around with it for a while before I decided to add it. I think the ability to kill yourself with it, or kill allies, or lose it balances it out pretty well. But if people are absolutely against it, what would you suggest replaces it? The wand of life has too few charges to be worth it alone in my opinion. You have to remember the amount of runes the cult has at the point in the game where they would be using armor runes. and what they can do with those.

@Boredone It's doable! The spells you get are about half speed compared to artificer though, you spawn things much slower. It's not meant to replace the use of artificer, just give you the option to loud-cult summoner if you want to, since you need the robes on in order to use the spells.

**Comment by Anonus** [comment]
Wands aren't stopped by tables, they fire actual projectiles and not weird magic effects(and even if they were weird magic effects they still wouldn't be stopped by tables)

**Comment by Sabbat** [comment]
They were stopped while I was messing around with them, couldn't shoot over the medbay table, but I only tried with death and door wands.

**Comment by freerealestate** [comment]
How will people figure out in-game what items they need for these alternate load-outs though? It's not very intuitive if the only way to find out about it is from having seen this pull or looking through the code.

**Comment by Sabbat** [comment]
@freerealestate Isn't that half of the fun? Finding out what does what? I'm sure the wiki will get updated with the information soon after it's merged.

**Comment by doerakpoes** [comment]
a way to get soul shard as cult with out a constructor or starter paper

**Comment by Sabbat** [comment]
I got rid of the wand of death entirely due to lack of alternatives that really made any sense.

Now there are zero complaints about it. Merge? Kthx.

**Comment by Razharas** [comment]
Changelog please
@Sabbat

**Comment by Dorsisdwarf** [comment]
You can always just quickmerge a changelog PR if he doesn't show up!

**Pull request merged**
