### PR TITLE
replaces the old carrier sprite with the new tgmc one

### PR DESCRIPTION
**Pull request by Pariah919**
## About The Pull Request
Carrier card looks different, actual new TGMC sprite.

## Why It's Good For The Game
CONSISTENCY WITH TGMC ART ~~despite the fact i made them two seperate universes with divine mandate~~

## Changelog

:cl:
spriteadd: New carrier TCG art.
del: Removed old carrier TCG art.
/:cl:

### CODE REVIEW

**Comment by JohnFulpWillard** [comment]
holy shit its them

**Comment by Pariah919** [comment]
image

image

truly, my power are beyond human comprehension

**Comment by Kylerace** [comment]
Trpllface

**Comment by Pariah919** [comment]
image
cease

**Pull request merged**
