### PR TITLE
Rearranges cargo packs

### PR DESCRIPTION
**Pull request by 81Denton**
:cl: Denton
tweak: Cargo packs have been grouped and sorted alphabetically. Station goal crates are now in the Engineering section.
tweak: The cargo security section has been split into security/armory.
tweak: Grouped all gas canisters and fuel/water tanks together in one section with raw materials.
spellcheck: Fixed a few cargo pack descriptions. 
/:cl:

The supply pack list is a total clusterfuck with items strewn all over. I've attempted to fix it by grouping items together and sorting them alphabetically.

Since cargo is a touchy subject: This PR doesn't change any prices, access reqs or contents (if it does, let me know so I can fix it).

- Split security into two sections: security/armory
- Grouped all gas canisters and fuel/water tanks together in one section with raw materials
- Moved station goal crates to engineering
- Moved plasmaman supplies to emergency

### CODE REVIEW

**Comment by ExcessiveUseOfCobblestone** [comment]
Neat

**Comment by 81Denton** [comment]
The misc section is still kinda shitty, I'll do that one in another PR

**Comment by DaedalusGame** [comment]
>alphabetically

kill me

**Comment by 81Denton** [comment]
Only after you fix tritium fusion

**Comment by Bawhoppen** [comment]
But why?

**Comment by ExcessiveUseOfCobblestone** [comment]
I didn't know baw had such a connection to the current organization that he must ask why someone is sorting them in a sensible manner

**Comment by Bawhoppen** [comment]
Alphabetical is more arbitrary in this case since related stuff is in general next to each other

**Comment by Bawhoppen** [comment]
I didn't mean I cared really though just saying

**Comment by 81Denton** [comment]
>Alphabetical is more arbitrary in this case since related stuff is in general next to each other

That's what I assumed, but it turned out that packs were just strewn all over. I tried to group them; for example engineering is now equipment -> engine parts -> station goal packs. 
Security also had armory packs mixed with regular sec packs in one big list, which is why I split them.

**Comment by ShizCalev** [comment]
conflict.

**Comment by 81Denton** [comment]
Should be fine now

**Comment by MrDoomBringer** [comment]
merge this shit i've got a pr waiting on it ree

**Comment by MrDoomBringer** [comment]
good change

**Pull request merged**
