### PR TITLE
Adds sorting to most input() lists

### PR DESCRIPTION
**Pull request by kriskog**
## About The Pull Request
Was bored, added sorting to lists used with the input() window. Some global lists were sorted upon filling them. Have mostly all been tested, should be good to go.

## Why It's Good For The Game
Picking from sorted lists > unsorted lists

## Changelog
:cl: Skoglol
tweak: Most input windows now have sorted lists of choices.
/:cl:

### CODE REVIEW

**Comment by yoyobatty** [comment]
I don't think I saw it but, can you add a sort to the view variables verb? It always seem to be impossible to look through it, although I often use `SELECT` as SDQL2 command to get where I am going.

**Comment by kriskog** [comment]
> 
> 
> I don't think I saw it but, can you add a sort to the view variables verb? It always seem to be impossible to look through it, although I often use `SELECT` as SDQL2 command to get where I am going.

I looked for this, but couldn't find the input(). Know where it is?

**Comment by 81Denton** [comment]
Conflict

**Comment by kriskog** [comment]
I still havent gotten around to doing the actual testing of about 50 of these. Hold off on merge until I have.

**Comment by kriskog** [comment]
Allright, been through them all now. I havent explicitly tested everything, but have validated the sort type in code and checked those where I have been in doubt. If I have fucked something up, it will runtime and show the list anyway so it doesn't make anything unusable. I will keep an eye on the runtime logs.

**Pull request merged**
