### PR TITLE
pAIs now use their creator's PDA instead of having their own Messenger

### PR DESCRIPTION
**Pull request by JohnFulpWillard**
## About The Pull Request

Removes pAIs Messenger app, and their ability to buy Digital Messenger.
Instead, pAIs will be able to interact with any PDA they are inserted into, allowing them to receive/send PDA messages through their creator's name rather than their own.
I also replaced pAI's cameras with using the already existing ``aicamera``, so I don't have to copy paste code in nt messenger's photo sharing abilities. This isn't really helpful though since pAI cameras in general don't work right now, but I'm thinking ahead here.

I also added a check for recursive content checking in ``can_perform_action``, so anyone inside of something can do actions on it now (in practice, I don't think there's any cases outside of pAIs, but I could be wrong).

## Why It's Good For The Game

The goal is to simplify pAIs, and part of that is to remove their cluttered UI. Preferably there would have 2 important buttons, the button to interact with something they are inserted into, and the button for everything else (put into a single internal tablet). This isn't a perfect plan (some things will have to remain, such as radio and photography) but it at least helps move towards that.
It also makes pAIs more dependent on their creator, as they no longer have the ability to PDA people unless it's through them. Just another way of encouraging them to actually stay with them throughout a round.

## Changelog

:cl:
balance: pAIs no longer have a Digital Messenger app to download.
balance: pAIs inserted into a tablet can now control it, sending PDA messages in their name and such.
/:cl:

### CODE REVIEW

**Comment by ATH1909** [comment]
I like the PDA control, but don't like the removal of independent PDA'ing. Many pAIs like to vibe in holoform, and this would cut them off from being PDA'd.

It's also, like, two buttons? I don't really see how that's hud clutter, especially on a mob without an inventory.

**Comment by YehnBeep** [comment]
Aside from the holoform concerns, this would mean a pAI's downloader/creator and the pAI itself can no longer message each other? Sorry, but... 👎

**Comment by JohnFulpWillard** [comment]
> Many pAIs like to vibe in holoform, and this would cut them off from being PDA'd

Many maintainers already have shown their distaste for holoform mode and I will not code for the benefit of people who wish to play a personal assistant role to not perform the one job asked of them. I don't care that they exist but I'm not going out of my way to give them tools 

> Aside from the holoform concerns, this would mean a pAI's downloader/creator and the pAI itself can no longer message each other

Then you should not be separating from your downloader

**Comment by YehnBeep** [comment]
> Then you should not be separating from your downloader

You don't need to be separate. There are many conditions that can inhibit speech, for example. And sometimes one might want privacy, for antag/security/or just plain personal reasons.

Lastly, many people like to wear the holoform. Although storage inside a PDA is more efficient.

**Comment by JohnFulpWillard** [comment]
My PR makes no change to pAIs who stand in front of bars to welcome people, not people who wear pAI as hats. It takes away their PDA messenger app, sure, but you are completely blowing out of proportion how much it harms a role. Your pAI should be an extension of you, and PDAing through your name is a perfect example of how we can expand on that

**Comment by YehnBeep** [comment]
> My PR makes no change to pAIs who stand in front of bars to welcome people, not people who wear pAI as hats. It takes away their PDA messenger app, sure, but you are completely blowing out of proportion how much it harms a role. Your pAI should be an extension of you, and PDAing through your name is a perfect example of how we can expand on that

So what if the downloader is mute?

What if they got a brain trauma?

What if they're deaf and need to talk to medstaff that ignore PDA messages, or security for explaining that no they didn't set off that bomb they were just caught in the blast, and so on?

Back to the bar scenario, what is the bartender's gone and someone asks you where they are? (This isn't just theoretical - The PDA messenger has let me ask and get an answer like "Doing bounties, back in 30 secs") and so on.

These are all under 'cases where you need to message the person you're with', though I'm not sold on roaming pAI players exactly being a menace to SS13 society either.

**Comment by YehnBeep** [comment]
So, if I might suggest more gentle encourage of a pAI to stay on someone's person, that would be more additive than subtractive:

What if pAIs didn't need encryption keys, but could just access the channels their master can?

IMO this leads to far more "the pAI is an extension of me and helps me manage things", yet it's often passed up because not that many people really want to go out of their way to get a tool, spare headset, and then mess about with the card.

**Comment by JohnFulpWillard** [comment]
> So what if the downloader is mute? What if they got a brain trauma? What if they're deaf

These are all niche situations and players aren't owed a way to bypass everything, though here there is the notes app that will let pAIs and users write notes at eachother instead of PDA (which is much more interesting than PDA anyways)

> need to talk to medstaff that ignore PDA messages

This PR changes nothing then???

> what is the bartender's gone and someone asks you where they are?

Typically you can ask the bartender before they leave, or over the radio, or just say "they aren't here currently", or assume they're doing the thing you saw them doing for some time now. I doubt people are asking pAIs where the bartender is with a grading paper in their hand. 

> I'm not sold on roaming pAI players exactly being a menace to SS13 society either.

Ok great. Unrelated to the PR though. 

> What if pAIs didn't need encryption keys, but could just access the channels their master can?

Sounds fine. Unrelated to the PR though.

**Comment by YehnBeep** [comment]
I was hoping to propose an alternative to your goal that doesn't hurt pAI <-> pAI owner communications, but, right, to stay focused just on this:

> These are all niche situations and players aren't owed a way to bypass everything, though here there is the notes app that will let pAIs and users write notes at eachother instead of PDA (which is much more interesting than PDA anyways)

They are not really that niche. It's a pretty common use case to have a pAI help work around disabilities, be they quirks or acquired in games (and things like deafness from explosions, flashbangs, honks and so on really isn't that uncommon at all.

> This PR changes nothing then???

No. If the pAI owner is deaf, the pAI can act as a verbal bridge via PDA messages to said owner.

> Typically you can ask the bartender before they leave, or over the radio, or just say "they aren't here currently", or assume they're doing the thing you saw them doing for some time now. I doubt people are asking pAIs where the bartender is with a grading paper in their hand.

Of course. But every step of making communication harder, hurts the ability of a pAI to facilitate things for whomever they're attached to.

And I really wouldn't downplay it as a minor thing. Like, if this PR were increasing communication facilities, I'd think it's pretty great. But taking out such a fundamental and frequently used communication facility with the person a pAI is "supposed" to be talking with most. This isn't good.*

* Though once again, this is assuming acceptance of your premise that pAIs shouldn't roam/be set free, which I still don't particularly agree with the anathema for.

**Review by Imaginos16 — APPROVED** [review]
Not sure what this changes sprite-wise after checking IDB, but it seems fine so I don't really mind.

**Comment by zxaber** [comment]
What if pAIs could access their "home" PDA while within a set distance? You'd still allow mobile pAIs that nevertheless stick near their owner to manage the inbox.

**Comment by ATH1909** [comment]
> Your pAI should be an extension of you, and PDAing through your name is a perfect example of how we can expand on that

your pAI _can_ be an extension of you, but I think it's a bit restrictive to make it so that they _must_ be an extension of you. sometimes you just... split ways to each follow your own plot threads. or you don't have that owner-minion dynamic. or you go ssd and they can't find a good candidate for a new owner.

**Comment by JohnFulpWillard** [comment]
The point of this PR is that they don't have a personal messenger. Removing the entire point of the PR is not "middle of the road". I don't want them to be limited to messaging only while inside a PDA, I want them to control the PDA while inside of one.

**Comment by AdipemDragon** [comment]
Fair enough on that, then, borrowing mom's phone for messaging it is.

**Comment by JohnFulpWillard** [comment]
> No. If the pAI owner is deaf, the pAI can act as a verbal bridge via PDA messages to said owner.

If they are deaf then they can still talk, they just can't hear, which means you are still able to use notepad on the PDA, or emotes like any player can do.

The commentors on this PR seem to act like messaging is the only form of communication in the game, it's not. The biggest form of communication is chat, whether it's talking or emoting, this PR doesn't affect either of those two. Paper, PDA notepad app, and other forms of communication still exist after this PR, and it also gives pAIs a massive benefit while inside of a PDA of being able to see the messages their creator gets, so they can more easily follow along the ongoing events that surround them. Say a Security Officer gets a PDA msesage of a murder going on in a certain part of the station, now the pAI already knows of that and understands why their master is going there, and can respond for them. It also gives pAIs the ability to use any app the PDA has.

> but I think it's a bit restrictive to make it so that they must be an extension of you

I'm not forcing them to be in a PDA. They just aren't getting a messenger while not inside of one. Like plug and play, you plug the pAI into different things so it can do different stuff, all of which would be to help your downloader in some form.

**Comment by YehnBeep** [comment]
> The commentors on this PR seem to act like messaging is the only form of communication in the game, it's not. The biggest form of communication is chat, whether it's talking or emoting, this PR doesn't affect either of those two.

No, that's really not the issue, and saying this makes me wonder how much you've read or if you're just missing the point.

Verbal communication is the most common but it's also very fallible. Hurting communication options - particularly the most common fallback - for a role where social interaction is central... IMO this fails the "this is good for the game" measure in no small manner.

**Comment by YehnBeep** [comment]
I guess one last thing I'd just like to say: I'd really hope you can be open minded towards considering some alternatives.

There **are** some good ideas here. pAIs could use some love on the code side. With some flexibility and constructiveness, the experience for both pAIs and those using them could be improved a lot and some of these ideas could be much better received.

Maybe the maintainers will force this on us anyways if that's all that matters to you, but it doesn't have to be this hostile thing.

**Comment by Breadeagle** [comment]
There are so many problems that this introduces to those who both like and dislike pAIs. For people that dislike pAIs as a dead man's switch, this literally makes it worse, because they are pretty much entirely invisible while carded on another player. For people that play pAIs, it makes messaging people while in any other state impossible, and makes communicating more complicated while you are carded. 

The capability to have a combined inbox _might_ be nice, but it comes at a "literally why" price. Lots of pAIs that actually stick by me will already be messaging on my behalf for kitchen ingredients or other miscellaneous business. Any pAIs that don't seem interested, or lose interest later, I often just tell them its fine to roam, or give them a directive to improve other people's day. I don't see the point in gutting one of their most major forms of communication while in a completely social (holo) form. This is not even to mention how incredibly awkward taking someone's identity is. You give up an easy way to communicate with your downloader, the PDA, (notepad is incredibly bad) and have all the downsides of sharing/stealing an identity, like changelings.

Make no mistake, PDA functionality is a _massive_ portion of what pAI players will end up doing, due them not having much other capability, and being a primarily social role. Decoupling PDA functionality from being in any other form but a card within a PDA (rekt if you're not the only pAI) will feel incredibly bad. Like removing the ability to turn and shoot at the same time in a shooter bad.

**Comment by MrMelbert** [comment]
Not particularly interested in this. Does not address the primary issue of PAI communication that I (and most of us?) have, that being their ability to harm alarm. 

Not sure I agree with the "Why it's good for the game" section. Does PAI actually need simplification when they can only access like three buttons at a time?

**Comment by MrMelbert** [comment]
I will say though that the concept of PAIs interacting with stuff they're inserted in is an excellent idea. Kinda like USB circuits.

**Comment by JohnFulpWillard** [comment]
The PR is meant as one part to a hackmd I had written up a while ago; https://hackmd.io/VOI8MBV0QZGKXhdnAJ_HWQ 

> Does not address the primary issue of PAI communication that I (and most of us?) have, that being their ability to harm alarm.

I don't understand what the problem is here, pAIs being able to talk over the radio? I wasn't even aware it was seen as a negative in any way. Maybe it could be fixed in other ways (like making radio jammer easier to obtain, or something other antagonists can get too).

> Does PAI actually need simplification when they can only access like three buttons at a time?

I'm trying to remove the overabundance of buttons. Even if they can only access 3 at once, they're still there on screen for no reason, and I think it would be more fun to make pAIs work better with their masters than it is to just add the icons when the pAI downloads a program.

**Comment by YehnBeep** [comment]
> I don't understand what the problem is here, pAIs being able to talk over the radio? I wasn't even aware it was seen as a negative in any way. Maybe it could be fixed in other ways (like making radio jammer easier to obtain, or something other antagonists can get too).

There's an old PR (people have showed me it before) that did actually remove pAI radios, a central justification for it being pAIs calling for help when their master/owner is attacked. It faced apparently pretty big backlash and was reverted in time. Could dig it up but... it all seems a bit out of scope here - only mentioning it to provide context to MrMelbert's comments.

> I'm trying to remove the overabundance of buttons. Even if they can only access 3 at once, they're still there on screen for no reason, and I think it would be more fun to make pAIs work better with their masters than it is to just add the icons when the pAI downloads a program.

There's some good goals and neat ideas to what you want to do, but it's very hamfisted to players and situations that don't fit your ideals (or that simply seem to have been overlooked, like if someone has more than one pAI). I really do hope you'll consider alternatives with a lighter touch, because I don't think this has to be a dichotomy.

**Comment by MrMelbert** [comment]
> I'm trying to remove the overabundance of buttons. Even if they can only access 3 at once, they're still there on screen for no reason. 

Can't we just make them invisible then? :P 

I just don't find this change very constructive. If the issue lies solely with how bad their UI is we can just make it better rather than remove stuff one by one until it's "decluttered".

Maybe this is better done as a project across multiple PRs to achieve the end goal.

**Comment by JohnFulpWillard** [comment]
> rather than remove stuff one by one until it's "decluttered".

That's how I work, I make several smaller PRs rather than do it all at once, I did the same for Mafia. Close the PR if you don't agree with it

**Comment by carshalash** [comment]
Christ, you're going after PAI now as well?

**Comment by AtomTheProphet** [comment]
> Christ, you're going after PAI now as well?

I mean, it _is_ John Fulp Willard

**Pull request closed without merging**
