### PR TITLE
makes it so lockers/crates can have access electronics removed/inserted

### PR DESCRIPTION
**Pull request by Seris02**
## About The Pull Request

title

They can only have electronics inserted if they
- are welded shut (if they can be welded)
- don't have electronics already and aren't secure

They can only have electronics removed if they
- are welded shut (if they can be welded)
- are unlocked
- are secure (even if they don't have electronics, then it'll create them)

## Why It's Good For The Game

better locker locking + fun things

## Changelog
:cl:
add: makes it so lockers/crates can have access electronics removed/inserted
/:cl:

### CODE REVIEW

**Comment by MessoDepresso** [comment]
Dont forget to set the install variable to false on Minecarts too >->

**Comment by Seris02** [comment]
linen bins aren't crates and mine carts uh, don't exist?
but yes I've set the install variable on all of those, don't worry

**Comment by MessoDepresso** [comment]
I could have sworn they were from here and all subtypes of closets wtf wtf wtf 😖

Either way, very cool very nice pr yesyes. Cant say much about the code cuz im bad at it but it loooooks sound <3

**Comment by ATH1909** [comment]
why do they need to be welded shut for this?

**Comment by Seris02** [comment]
Because do you really want people just popping access onto something, plus, if you were installing a lock on a locker, or taking it off, you'd want the door steady, right?

**Comment by MessoDepresso** [comment]
Using that argument, would it be better to require we bolt them to the floor instead maybe?

**Comment by Farquaar** [comment]
This is the future

**Comment by ATH1909** [comment]
> Because do you really want people just popping access onto something, plus, if you were installing a lock on a locker, or taking it off, you'd want the door steady, right?

I mean, it already requires a do_after()- one that you can lengthen if you want

**Comment by Seris02** [comment]
> > Because do you really want people just popping access onto something, plus, if you were installing a lock on a locker, or taking it off, you'd want the door steady, right?
> 
> I mean, it already requires a do_after(), no? if the do_after() isn't long enough, just lengthen it.

I dunno
I'll wait for a maintainer's opinion on that

**Review by Watermelon914 — CHANGES_REQUESTED** [review]

**Pull request merged**
