### PR TITLE
Adds lowercase paths rule to contributing.md

### PR DESCRIPTION
**Pull request by AnturK**
@tgstation/commit-access

Respond if you disagree.

### CODE REVIEW

**Comment by FantasticFwoosh** [comment]
Seems unnesecary. This will just shift people into using numerical markers for differentiation in similar instances which is a worse practice, though i admit lower case would be easier to read. There's so much spaghetti i doubt you can get all the offending lines without running out of substitute path-names when people have used different cases.

> /mob/simple/friendly/blackcat1 
> /mob/simple/friendly/blackcat2 (let say this cat's markings are inversed or aesthetically different)

**Comment by Jordie0608** [comment]
I think there's enough words in the english language we won't encounter a time when two paths could only possibly be differentiated by numbers.

**Comment by ninjanomnom** [comment]
If two paths could only be differentiated by casing then making one path
`/some/type/path`
and another
`/some/type/Path`
is worse than numbers. Regardless with both they should just find another word.

**Review by Cyberboss — APPROVED** [review]

**Comment by ExcessiveUseOfCobblestone** [comment]
@FantasticFwoosh look at `/obj/structure/flora/ausbushes` where they are pretty much the same with just a different icon.

If they're functionally similar then they should be subtyped, if they're pretty much at equal value then the small differences should be included in the path (in this case the bush's color).

**Review by ShizCalev — APPROVED** [review]

**Review by SpaceManiac — APPROVED** [review]

**Review by duncathan — APPROVED** [review]

**Pull request merged**
