### PR TITLE
so it turns out I forgot to actually give integration cogs power generation!!!!! [please speedmerge this]

### PR DESCRIPTION
**Pull request by ghost**
:cl: Xhuis
fix: Cogs now fucking work
/:cl:

hit me with that pr:b: no update

### CODE REVIEW

**Comment by AdamElTablawy** [comment]
TEST

YOUR

CODE

**Comment by Xhuis** [comment]
I DO TEST MY CODE BUT THIS SOMEHOW GOT IN IN ONE OF THE FINAL COMMITS AFTER IT WAS TESTED.

**Comment by Hatterhat** [comment]
thanks :b:oders

**Comment by nicbn** [comment]
TEST

YOUR

CODE

**Comment by Xhuis** [comment]
>I DO TEST MY CODE BUT THIS SOMEHOW GOT IN IN ONE OF THE FINAL COMMITS AFTER IT WAS TESTED.

**Comment by GunHog** [comment]
Poor Not-Cat-Slime..

**Comment by Robustin** [comment]
now make that 1 a 2 and we're cooking with gas

**Comment by Xhuis** [comment]
I'll cook you with gas

**Pull request merged**
