### PR TITLE
Fixes lye/plastic/charcoal conflicts

### LINKED ISSUE #35490: Conflicting chemicals
Right now, the following chemicals conflict when mixing, i.e. you can get different results with the same ingredients:
- Plastic and charcoal
- Plastic and lye 

Anything else?

### PR DESCRIPTION
**Pull request by 81Denton**
:cl: Denton
fix: Fixes lye/plastic/charcoal conflicts when mixing.
fix: Lye is now made by combining ash with water and carbon. Plastic sheets by heating ash, sulphuric acid and oil.
/:cl:

Closes: #35490

Charcoal (ash+salt) conflicts with plastic (ash+salt+oil). Lye (ash+water) can conflict with both of them, since water is a component of salt. 

This PR changes their recipes from: 
ash/water + ash/salt/oil
to:
ash/water/carbon + ash/sacid/oil

### CODE REVIEW

**Comment by DaedalusGame** [comment]
this, actually, is good

**Comment by arsserpentarium** [comment]
Do you even know, what is lye?
also reaction is fucky, but working.

**Comment by DaedalusGame** [comment]
Lye refers to several caustic compounds but most commonly we're talking about potash stewed in water

**Comment by arsserpentarium** [comment]
yep.So why carbon?

**Comment by 81Denton** [comment]
/tg/chem doesn't have quicklime/calcium oxide, so I picked something that wouldn't conflict with other recipes. It's not an elegant solution, but imho better than having to change other recipes that are used more often.

**Pull request merged**
