### PR TITLE
Nerfs stupid armor stats of bone bracers.

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request

Nerfes the bone bracers armor stats.

## Why It's Good For The Game

For something that can be made so easily, out of a few bones, it has too good stats, especially the fact that it has radiation protection for some reason?
## Changelog
:cl:
balance: Changed bone bracers armour stats from:
`melee= 15, bullet= 35, laser= 35, energy= 20, bomb= 35, bio= 35, rad= 35, fire= 0, acid= 0)`
to:
`melee = 15, bullet = 25, laser= 15, energy= 15, bomb= 20, bio= 10, rad= 0, fire= 0, acid = 0`
/:cl:

### CODE REVIEW

**Comment by Akrilla** [comment]
Yikes, those commits don't seem to really reflect what the PR's for.

**Comment by BeloneX** [comment]
> 
> 
> Yikes, those commits don't seem to really reflect what the PR's for.
> 
> Edit: Oh you changed them back in later commits - though it'd probably be better to do it on a separate branch so that doesn't need to happen.

sorry i'm pretty new to github so everything is a fucking mess.

**Comment by ExcessiveUseOfCobblestone** [comment]
all bone armor should have - bio values tbh, they're dirty bones.

**Comment by Shadowflame909** [comment]
What if I wash em

**Comment by ExcessiveUseOfCobblestone** [comment]
DIRTY

BONES

**Comment by Fikou** [comment]
oh no not those very very overpowered bone bracers that are so easy to make and every powergamer uses them every round

**Comment by anconfuzedrock** [comment]
just because something isn't used often doesn't mean it's fair

**Comment by ExcessiveUseOfCobblestone** [comment]
It is used often though? It's just not available to a large portion of the crew because it's exclusive to lavaland.

Miners totally make this regularly.

**Comment by Barhandar** [comment]
Nerfing ashliggers is very good yes

**Comment by ExcessiveUseOfCobblestone** [comment]
*sips lizard tears*

**Comment by ATH1909** [comment]
Uh, you DO know that bone bracers only protect your ARMS (NOT your chest/torso), right? They're a niche protection item for if someone's stray shot or laser blast or whatever hits your arm instead of whatever part they were aiming for. I'd drop 'em for insuls (or hell, even krav maga gloves) in a heartbeat.

**Comment by granpawalton** [comment]
i ded

**Comment by FantasticFwoosh** [comment]
I see you too are a man of culture, they're better than the black gloves you're given as miner despite not being inheriently fireproof.

**Comment by CRITAWAKETS** [comment]
bone bracers are actually only useful agaisnt fauna

**Pull request merged**
