### PR TITLE
Makes the sloth an actual sloth

### PR DESCRIPTION
**Pull request by MrsTonedOne**
Glide_size change lowers their tile glide rate to be slow as well.

:cl:
tweak: The sloth no longer suspiciously moves fast when gliding between tiles.
balance: The sloth's movespeed when inhabited by a player has been lowered from once every 1/5 of a second to once every second.
/:cl:

### CODE REVIEW

**Comment by Armhulen** [comment]
he's going to get tokens for this :rage:

**Comment by MrStonedOne** [comment]
Better?

**Comment by AnturK** [comment]
Nice try

**Comment by The-clown-known-as-Pepe** [comment]
🍊

**Review by ninjanomnom — APPROVED** [review]

**Pull request merged**
