### PR TITLE
Re-adds forcesay

### LINKED ISSUE #8477: When you're pushed, it makes you say whatever is in your chatbar..
How 2 Reproduce:  Type Say " in your chatbar, push yourself.

What happens:  Jebediah Kerman has pushed Jebediah Kerman!
                          Jebediah Kerman says, "Say ""

What should happen?  I should be pushed.

### PR DESCRIPTION
**Pull request by theOperand**
whoops i accidentally removed this because i thought it was awful and deprecated but APPARENTLY NOT
fixes #8477

### CODE REVIEW

**Comment by Miauw62** [comment]
oh ffs

**Comment by Miauw62** [comment]
there we go

**Comment by pudl** [comment]
what is forcesay?

**Comment by Miauw62** [comment]
its the proc that is called when y- GLORF

**Comment by pudl** [comment]
i cant believe you removed this

**Comment by Miauw62** [comment]
it's called an accident, much like your conception.

**Comment by optimumtact** [comment]
It's got a terrible name too

**Pull request merged**
