### PR TITLE
Fixes the secret monkey technique

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
Monkeys can no longer "duplicate" NODROP items by stealing them

### CODE REVIEW

**Comment by Iamgoofball** [comment]
how many fucking monkey techniques

**Comment by Cyberboss** [comment]
Infinite

**Comment by SweaterKittens** [comment]
I'm not gonna lie, I'm going to miss my daily ahelp of "Uh, a monkey just took my "god hand/dark blessing and beat me with it"

**Comment by jughu** [comment]
>when somoene this to tell me this is a feature

**Comment by SgtxRootbeer** [comment]
Feature, being able to beat you with NODROP items.

**Comment by PKPenguin321** [comment]
Monkeys should just straight up tear off your arms

**Comment by Anonmare** [comment]
>tfw you're a Changeling and beating a man to death in Genetics when you make eye contact with a monkey behind the glass
>tfw said monkey goes, literally, apeshit and he and his friends burst through the glass - followed by them suplexing you on the table and ripping off your own armblade to beat you to death with it

**Comment by Alek2ander** [comment]
Ook

**Comment by optimumtact** [comment]
So I ah, fixed yoru conflict, but the github editor ate the spacing, can you twaek that please?

**Comment by optimumtact** [comment]
So I ah, fixed yoru conflict, but the github editor ate the spacing, can you fix it?

**Comment by optimumtact** [comment]
kor pls

**Pull request merged**
