### PR TITLE
adds a new fish to lava and plasma rivers

### PR DESCRIPTION
**Pull request by Ben10Omintrix**
## About The Pull Request
this pr adds a new fish to lavaland and icebox, the lavaloop! i noticed neither has any exclusive fish so im trying to add one of my own. u can find this fish by using reinforced rods on lava or plasmarivers. this fish is also lobstrosity's favorite delicacy as you will now often see AI controlled lobstrosities fishing for it in lava and then eating it. 
fished

because of its body's curvature and razor sharp spikes, this fish can also be used as a make-shift boomerang weapon against mining mobs, although it comes with some new mechanics. u can increase the damage it does to mobs by winding up ur throw. when the bar reaches purple, this indicates maximum damage. however, if it goes over the purple, it will react violently and explode your arm off, so you have to time it just right to get the best damage possible. On icebox, instead of dealing raw damage, fish will freeze mobs depending on how long you charged ur throw. charging it for too long will cause the fish to freeze you instead

https://github.com/tgstation/tgstation/assets/138636438/c8ac3696-3705-45b0-bc43-c5b81d75cb1b

while its nowhere near as effective as using PKA's or crushers, it can be a useful tool for hermits and ashwalkers.
## Why It's Good For The Game
having lobstrosities fish and hunt for it makes lavaland feel more like an ecosystem with a food chain. also i think tossing fish at eldritch horrors is a funny way to fight them

## Changelog
:cl:
add: adds a new fish to lava and plasma rivers, the lava loop
/:cl:

### CODE REVIEW

**Review by Wallemations — APPROVED** [review]

**Comment by MercuryArrow** [comment]
Explosive lava fish boomerang is an absolutely deranged series of words and I'm all for it. This looks quite fun.

As an aside, have you added anything as far as making the lobstrosities tameable if they now have a favourite food? Might be something to consider for the future.

**Comment by Admiral-Gigaton** [comment]
feel like blowing a whole ass arm off just because you fucked up your throw might be a bit much, what if instead it gave you a wound, more treatable on the field (where you will be, likely, due to it being a lavaland/icebox exclusive, and on the levels of those where mostly only miners go) and could make more sense. 

I mean, this is your PR, keep it as you will, but getting your arm blown off for a bit extra damage seems kinda... iffy, especially considering it looks like if you throw it on purple, the enemy you hit doesnt get blown up or anything like that. at the very least, show some kind of indicator for noobs that theres a bigass downside to using it like a moron

**Comment by Ben10Omintrix** [comment]
> feel like blowing a whole ass arm off just because you fucked up your throw might be a bit much, what if instead it gave you a wound, more treatable on the field (where you will be, likely, due to it being a lavaland/icebox exclusive, and on the levels of those where mostly only miners go) and could make more sense.
> 
> I mean, this is your PR, keep it as you will, but getting your arm blown off for a bit extra damage seems kinda... iffy, especially considering it looks like if you throw it on purple, the enemy you hit doesnt get blown up or anything like that. at the very least, show some kind of indicator for noobs that theres a bigass downside to using it like a moron

sure

**Comment by Ben10Omintrix** [comment]
> Explosive lava fish boomerang is an absolutely deranged series of words and I'm all for it. This looks quite fun.
> 
> As an aside, have you added anything as far as making the lobstrosities tameable if they now have a favourite food? Might be something to consider for the future.

id love to make more lavaland mobs tameable. however we HAVE made maybe a bit too many of them tameable

**Pull request merged**
