### PR TITLE
Gives cyborgs the ability to open morgue trays

### PR DESCRIPTION
**Pull request by ghost**
:cl: Xhuis
add: Cyborgs can now open morgue trays. This does not include crematoriums!
/:cl:

I saw that we didn't have this and, speaking from a medical cyborg perspective, it seems like it'd be really handy to have. They can only do this when adjacent to them, and they can _not_ open crematoriums.

### CODE REVIEW

**Comment by Shadowlight213** [comment]
Finally!

**Comment by Iamgoofball** [comment]
This kills tactical morgues

**Comment by TehZombehz** [comment]
Wow now I can't use morgue trays to tactically hide my bodies from borgs like a professional valid acquirer, my hardcore strategies are ruined.

**Comment by jughu** [comment]
Isnt the cremator a subtyoe morgue tray? :DDDDDDD

**Comment by Xhuis** [comment]
@jughu I think so, yeah.

**Comment by jughu** [comment]
((secret changeling nerf))

**Comment by KorPhaeron** [comment]
Actually kind of a big deal then

**Comment by Cebasiz** [comment]
inb4 PKP complaining about uncounterable sillicons

**Comment by Xhuis** [comment]
Well, I want to give borgs the ability to open morgue trays _without_ causing balance issues. I'll override the subtype to not be usable for this PR.

**Comment by FantasticFwoosh** [comment]
Is this remotely or by touching?

And does the AI have the same capacity, because morgues typically before would be safe spaces away from revenants or the AI where only staff touches them given a borg can just whip open morgue, drag away in a locker then space/destroy the corpse.

**Comment by Xhuis** [comment]
@FantasticFwoosh From range. I can easily make it so that it's only if you're adjacent though, and probably will. AIs cannot open them, no.

**Comment by Xhuis** [comment]
OP updated with some changes.

**Comment by Cebasiz** [comment]
oh zhu-ice 

while you are at it can you add a blood bag dragging ability or an IV module or something just while you are currently engaged in improving mediborgs thank you i will expect it on my desk in under a week thx

**Comment by Xhuis** [comment]
Once I finish with my bugfixes, I can look into it.

**Comment by Cebasiz** [comment]
you are a good person it's a missing functionality of mediborgs since forever and it makes the whole thing stupid, also it compels you to follow people around once they are at 89.9999999% because they are being harmed by oxygen loss.

**Comment by Xhuis** [comment]
This is ready to go

**Pull request merged**
