### PR TITLE
brings gender equality on /tg/station

### LINKED ISSUE #37708: all corgis bought from cargo are female
shouldnt it be 50% lisa and 50% corgi (male)

### PR DESCRIPTION
**Pull request by Tlaltecuhtli**
:cl:
fix: 50% of the corgis bought are now male
/:cl:
why: fixes: #37708

### CODE REVIEW

**Comment by Iatots** [comment]
Will all females be lisa with this?

**Comment by Tlaltecuhtli** [comment]
yes i can make it have male + female + lisa if u want

**Comment by Anonmare** [comment]
-4 strength

**Comment by Iatots** [comment]
Ideally there would only be one Lisa I suppose, just like there is only one Ian.

**Comment by ExcessiveUseOfCobblestone** [comment]
'> fixes all the corgis spawning female by deleting the female dog and replacing it with... another female dog

**Comment by optimumtact** [comment]
Is this a shitpost? this does not do anything

**Comment by Dorsisdwarf** [comment]
Isnt it meant to work such that the first corgi is always Lisa, then subsequent corgis are whatever? just like the first cat is always Proc

**Comment by Iatots** [comment]
ok so this is the old
```
if(prob(50))
 		var/mob/living/simple_animal/pet/dog/corgi/D = locate() in .
-		qdel(D)
-		new /mob/living/simple_animal/pet/dog/corgi/Lisa(.)
```
from the comments on #37708, I assume "contains = list(/mob/living/simple_animal/pet/dog/corgi" rolls the prob(50) on whether it's male or female, and the above code rerolls it to switch whatever is in the crate with lisa. Net result: 25% males, 25% females, 50% lisa (female corgi)

```
if(prob(50))
+		if(D.gender == FEMALE)
+			qdel(D)
+			new /mob/living/simple_animal/pet/dog/corgi/Lisa(.)
```
This is the new code. the contains = list(/mob/living/simple_animal/pet/dog/corgi rolls and the crate contains on average 50% male corgis and 50% female corgis. Now, with a prob(50) it rolls a check to see if the female corgi is female, and if it succeeds said female corgi becomes lisa.

So, it fixes #37708 by restoring a 50/50 split on male/female corgis, and the net result should be 50% males and 50% females, of which 50% are Lisas.

**Comment by ExcessiveUseOfCobblestone** [comment]
Oh I see, it's just that once again his issue title is bad.

**Review by SpaceManiac — APPROVED** [review]

**Pull request merged**
