### PR TITLE
Adds 2 bee hives, saltpeter dispenser to the seed vault ruin. Changed cherry seed to cherry bomb in the loot generator

### PR DESCRIPTION
**Pull request by ma44**
BEES
:cl: ma44
add: 2 Bee hives to plant vault
add: Adds a saltpeter dispenser to plant vault
tweak: Plant vault has a chance to spawn a cherry bomb seed instead of a cherry seed
/:cl:

[why]: # 
Bee hives: bees are cool and also teach people how to use bees and stuff

Saltpeter dispenser: Allows pod people to increase potency of seeds somewhat easier

Cherry seed to cherry bomb: New rare seed option (alongside the gatfruit) instead of a regular cherry seed (the only seeds besides that and gatfruit are mutated plants, while cherry is a beginner plant)

https://gyazo.com/e1732ab1a12fba6ace56493e74462cd9.png

### CODE REVIEW

**Comment by FantasticFwoosh** [comment]
> Murder bees stinging miners to death & existing on lavaland in huge sweeping laggy numbers.

No thank you

**Comment by GunHog** [comment]
This sounds awesome! I cannot wait!

**Comment by ma44** [comment]
>murder bees

they don't start off with any reagents, fighting a couple of bees when you can already one shot them should be easy

Bees can also get easily killed by lavaland monsters as they have 10 health and barely do damage (implying they ever get out)

**Comment by ma44** [comment]
Once im able to update this again ill remove one bee hive, as you can already make more if you have at least one queen bee

**Comment by octareenroon91** [comment]
> no mapmerge

Please just put the saltpetre in the mutagen dispenser. Rename it if you have to. It's defined specifically for the seed vault unless I'm mistaken, so whatever bounty of botany chems is probably fine.

**Comment by KorPhaeron** [comment]
Do what octareenroon said

**Review by Cyberboss — CHANGES_REQUESTED** [review]
You didn't mapmerge

**Comment by ma44** [comment]
Doing some other stuff, don't want this open or else cool map merge conflicts

**Pull request closed without merging**
