### PR TITLE
Tweaks space cave generation

### LINKED ISSUE #32728: Cave generator acts on space ruins, causing atmos runtimes
Runtime in open.dm, line 137: Cannot execute null.compare().
proc name: Initalize Atmos (/turf/open/Initalize_Atmos)
src: the asteroid sand (172,60,11) (/turf/open/floor/plating/asteroid/airless/cave)
call stack:
the asteroid sand (172,60,11) (/turf/open/floor/plating/asteroid/airless/cave): Initalize Atmos(1)
Atmospherics (/datum/controller/subsystem/air): setup allturfs()
Atmospherics (/datum/controller/subsystem/air): Initialize(80202)
Master (/datum/controller/master): Initialize(10, 0)

BMPship, _maps/RandomRuins/SpaceRuins/crashedship.dmm

image
image

### LINKED ISSUE #40930: Flora is growing on the asteroids in space
Round ID: 95488
Send help

image

### LINKED ISSUE #43207: It is not possible to disable generation of caves on asteroid turfs
## Reproduction:
Create asteroid.
Caves generate.

There is currently no possible way to disable this behavior, and it causes issues as seen in #32728. This also limits mappers abilities to create locations which should not have caves generated. 

Proc in question:
```
/turf/open/floor/plating/asteroid/airless/cave/proc/produce_tunnel_from_data(tunnel_length, excluded_dir = -1)
```

I tried to fix it myself but I suck at DM code. Also a side note, it seems strange to me that this proc is included under floors when it effects walls. It also only runs at world start, so it could possibly be moved somewhere else or refactored to clean up that file a bit, but again I suck a DM code so there may be a specific reason as to why its there.

### PR DESCRIPTION
**Pull request by kriskog**
## About The Pull Request
closes #43207
closes #40930

Space caves no longer spawn flora, and a few more space ruins now have random mineral spaws as I replaced non-mineral walls with the no_caves variant. Replacements generally made where: The rock was too small, or previously of the no mineral variety.

No changes for lavaland.

## Why It's Good For The Game
Bugs bugs bugs

## Changelog
:cl: Skoglol
fix: Space asteroids no longer spawn caves or cacti/mushrooms.
tweak: Additional space ruins will have ores spawn in mineral walls.
/:cl:

### CODE REVIEW

**Comment by Fikou** [comment]
sand cacti were cool though, added some variety to asteroids

**Comment by optimumtact** [comment]
i'd rather fix the issues personally

**Comment by Fox-McCloud** [comment]
The weird generation issues are partially caused by this: https://github.com/tgstation/tgstation/pull/36756

It *may* have removed round start active turfs, but it introduced a lot of bugs to lavaland cave generation.

there's turfs on lavaland that shouldn't be there because of it, it causes *other* atmos issues, and it's also the cause of the random sand turfs.

**Comment by kriskog** [comment]
@Fox-McCloud I fixed the issue with asteroid sand on lavaland here: #46586

I'll take a look at the cave generation a bit later and see what it would take to make them proper space caves. I expect not that much, with the biggest issue probably in finding the cause of the atmos runtimes.

Just fixing it will still require quite a bit of replacement on space ruin maps, as some just dont make sense to spawn caves. This one liner was easier :grin:

**Comment by Fox-McCloud** [comment]
That doesn't really fix the issue though; it just covers it over.

Those turfs shouldn't *exist* to begin with; the changes in the PR I linked introduced the problem and allow those turfs to stick around (they shouldn't stay).

**Comment by FantasticFwoosh** [comment]
Improve don't remove gang is a no-show today. Why not improve this alternatively with tighter area checks like we do to zone bosses away from the lavaland base and leaving the flora in as a placeholder?

**Comment by kriskog** [comment]
Fine, I did some other stuff.

**Pull request merged**
