### PR TITLE
UO45 Updates

### PR DESCRIPTION
**Pull request by WJohn**
Updates paths, makes the elevator look broken so people stop asking, injectors now start on etc.

### CODE REVIEW

**Comment by ike709** [comment]
working elevator needs to be a thing...

**Comment by WJohn** [comment]
Going surface side is not the intent of the away mission, perhaps doing something like that will be more of the focus in another away mission.

**Comment by pudl** [comment]
so can i ride the elevator? lmao

**Comment by WJohn** [comment]
Now that the elevator looks all broken I'm hoping people will stop asking.

**Comment by Nienhaus** [comment]
Picture?

**Comment by WJohn** [comment]
image

**Comment by ike709** [comment]
Surface Outpost 45 please

**Comment by Nienhaus** [comment]
You should just do a whole map that's like mini station, but on the surface.

**Comment by Deantwo** [comment]
Ooh I was playing with that elevtor the other day. I gave up after clicking a few times and soing nothing change.
Most of all. You need to add a note/sign saying that it doesn't work.
Or make the two buttons give an error.

**Comment by WJohn** [comment]
No broken tile in the game leaks air.

**Pull request merged**
