### PR TITLE
renames Admin Help in escape to Get Help per mothblocks post in https://tgstation13.org/phpBB/viewtopic.php?p=664964#p664964

### PR DESCRIPTION
**Pull request by Iamgoofball**
## About The Pull Request

see PR title

## Why It's Good For The Game

headcoder posted it so lets give it a try

## Changelog

:cl:
spellcheck: renames Admin Help in escape to Get Help
/:cl:

### CODE REVIEW

**Comment by Jolly-66** [comment]
Couldn't it be "Get help by contacting an Admin"?
"Get help" seems vague, at least to new players. Doss the esc menu support those lil hover overs? Idk what they're called or how to properly describe them.

**Comment by zxaber** [comment]
Alternatively, maybe "Request Help"?

**Comment by flowercuco** [comment]
Request Help or "Request Admin Help" both feel way better than "get help"

**Comment by optimumtact** [comment]
This isn't a bugfix

**Comment by Mothblocks** [comment]
all these comments would've been answered if this PR contained the context or anything other than that i said to do it

**Comment by Iamgoofball** [comment]
@Mothblocks i linked the thread, its not my fault people dont read links

**Comment by Mothblocks** [comment]
it is your fault that its a non-clickable link that will some day erode to link rot

**Comment by Iamgoofball** [comment]
/tg/station forums will never die

**Pull request closed without merging**
