### PR TITLE
Restores client controlled mulebots running people over. Greatly nerfs mulebot health to compensate.

### PR DESCRIPTION
**Pull request by Shadowlight213**
PAIS can now run people over as mulebots. Mulebot health has been nerfed from 150 to 50 to compensate.
:cl: 
rscadd: pAI controlled mulebots can now run people over.
tweak: Mulebot health has been greatly decreased.
/:cl:

### CODE REVIEW

**Comment by KazeEspada** [comment]
Just make it do damage so that PaIs can get banned.

**Comment by PKPenguin321** [comment]
RIP

**Comment by kevinz000** [comment]
I ded pls nerf

**Comment by tkdrg** [comment]
Yeah, I expected something like this, to be honest. Oh well.

**Comment by borntohonk** [comment]
make it do damage, so that the one who summons and puts it into the mulebot will be held accountable for cutting the wire in the first place. It'll be like a snowflake traitor companion.

this also gives the AI reason to immeadetly disable the mulebot's power.

**Comment by Shadowlight213** [comment]
I can make it do damage if people think that's a better option I guess.

**Comment by Zilenan91** [comment]
Yeah let's make it do damage

**Comment by Buggy123** [comment]
:+1: to making it do damage instead

**Comment by Shadowlight213** [comment]
Hmm. If I make pai mulebots do damage, I'd couple it with a nerf to mulebot health. Traitor mulebot rampages are pretty strong. They need to be far more fragile to compensate.

**Comment by Zilenan91** [comment]
That'd be fine

**Pull request merged**
