### PR TITLE
Health analyzers now warn you if someone can't survive their temperature.

### PR DESCRIPTION
**Pull request by JohnFulpWillard**
## About The Pull Request

Health analyzers are now red/blue if the temperature of the person is too hot/cold
image
image
image

Also because I just noticed it, I moved the signal for health scan down, meaning that things that are registered to it now work with inverse technetium setting it to advanced mode.
I also removed the ishuman check for bleeding because it's a carbon proc. This has no game-effects as xenos don't have DNA.

## Why It's Good For The Game

We currently expect doctors to see all the important information with red text to know what needs to be fixed, however this is not the case for temperature, we are currently expecting them to pay attention to a body's temperature, and what their species can handle. I think this is quite lame, and I think it would be better if it worked like everything else in the analyzer.

## Changelog

:cl:
qol: Health analyzers now show body temperature in red/blue if the temperature of the body can't sustain it's own life.
fix: Inverse technetium now properly gives advanced details in genetics/radiation analyzing.
/:cl:

### CODE REVIEW

**Comment by Iamgoofball** [comment]
@JohnFulpWillard Can we just make it red if it's an unsafe temp, hot or cold? making it dark blue doesn't match our style guide for "bad".

**Comment by JohnFulpWillard** [comment]
> @JohnFulpWillard Can we just make it red if it's an unsafe temp, hot or cold? making it dark blue doesn't match our style guide for "bad", it's less readable than just making it red. I'd also make the actual number red instead of the entire sentence to highlight that the value is bad and not the sentence.

I think blood volume works the same way so I wanted to make it consistent with that. The darker-blue thing I can change, I just thought that cold would not be as troublesome as heat and would be fine if it didn't stand out as much.

**Comment by timothymtorres** [comment]
Goof is right, the blue color for cold temperature doesn't stand out.  Either make it red or maybe a neon blue.

**Comment by Iamgoofball** [comment]
@JohnFulpWillard that's an issue with blood volume that should be patched then

**Comment by Iamgoofball** [comment]
@timothymtorres no, no blue at all

blue = good, red = bad, this is game color theory that has worked for over 30 years of game design

**Comment by san7890** [comment]
could we slap a unicode emoji like `“❄” U+2744` to wrap both sides around the dark blue cold so it's increasingly obvious (and something similar for people with elevated body temperature, e.g. `“☼” (U+263C)`)

**Comment by Mothblocks** [comment]
i agree with goof if im understanding right

**Comment by msgerbs** [comment]
> could we slap a unicode emoji like `“❄” U+2744` to wrap both sides around the dark blue cold so it's increasingly obvious (and something similar for people with elevated body temperature, e.g. `“☼” (U+263C)`)

Honestly based idea, and makes the game ever so slightly more colorblind-friendly.

**Comment by san7890** [comment]
> could we slap a unicode emoji like `“❄” U+2744` to wrap both sides around the dark blue cold so it's increasingly obvious (and something similar for people with elevated body temperature, e.g. `“☼” (U+263C)`)

you should still be able to do this even if they both would be red for "bad"

**Comment by JohnFulpWillard** [comment]
image
image

**Pull request merged**
