### PR TITLE
Botany Changes

### PR DESCRIPTION
**Pull request by Iamgoofball**
blue cherries -> cherry bombs

light with a heat source and throw, sprites pending me adding them

plump helmet description changed

plants with salglu in them had the salglu replaced with styptic or silv. sulf. to compensate

"but muh toxin damage from ingest!!1!"
Well, no shit. If I didn't have toxin damage in there, then bam, why go to medbay when I can just chow on 100 potency poppy seeds?
Why should botany be better than medbay at medbay's job?

i'm not arguing the "REVERT GOONCHEM???" shit in this pr so don't even fucking get started

i'll be going through any non-unique/boring plant mutations and improving on them. see: blue tomatoes(who even goes for those when I could just use bluespace), blood tomatoes(literally worthless), sweet potatoes(we have sugarcane which is better than this), etc.

### CODE REVIEW

**Comment by babinsquared** [comment]
So uh. What's the point of styptic or silversulf in foods? It'll make them basically useless as edibles and it's not like you'll be handing over backpacks full of poppy seeds to chemists when chemists can already make enormous quantities of (useful, touch-based) styptic.

**Comment by Cheridan** [comment]
^

**Comment by Aranclanos** [comment]
REVERT GOONCHEM???

**Comment by Iamgoofball** [comment]
@Aranclanos REVERT LINDA???

Botany used to be able to do ghetto medbay work with Bicard in the poppies and the kelotane in whatever plant had it, can't remember off the top of my head. It was good for when you couldn't make it to medbay but needed a quick pick-me-up. Wasn't as good as actual treatment, but would get you through the day.

I accidentally'd this by replacing everything in plants with salglu for some reason.

This restores the ghetto medbay ability of botany. If you guys don't want it I can remove it and give those plants some other properties.

**Comment by babinsquared** [comment]
Except it doesn't restore the ghetto medbay ability because botanists by default can't create things which apply touch effects, short of giving the plants to chemistry to insert into patches, which is utterly useless when chemistry is perfectly capable of synthesizing the chemicals themselves. Botany can't make patches.

Kelotane and bicard weren't exactly ghetto either. They were strong and botany could produce backpacks full of the stuff. The only thing "ghetto" about it was that you were eating the reagents from fruit instead of pills. Literally the exact same reagent.

**Comment by Iamgoofball** [comment]
You do realize that Styptic and Silver Sulf still do the 2 units of brute/burn healing per tick while inside of you, right?

**Comment by Cheridan** [comment]
@Iamgoofball Except this isn't ghetto medbay work, this is "well these poppies are going to poison me so i'll walk 10 tiles to the left and get patches instead". Pre-goofchem poppies didn't hurt you, and nobody was preferring them to medbay treatment then. Hydroponics produce is balanced by the effort required to grow them and the comparably lower amount of that can be made compared to chemistry.

**Comment by Lumipharon** [comment]
^.

Even 100 potency poppies and green grapes require TIME and EFFORT (also almost always mutagen from chemistry to begin with). Even then, you could also get healed faster/more easily at medbay then you ever could at botany.

The only advantage botany ever had, was the ability to stuff 50 plants into one plant bag.

**Comment by Iamgoofball** [comment]
then we axe the healing and replace it with gimmicks akin to cherry bombs and shit

y/n unless you have a better option that /isn't "revert when???"/

**Comment by babinsquared** [comment]
Also this'll probably make eating these foods spammy with the "Maybe you ate a medicine you shouldn't have?" message because you'll get the message with every single bite you take. It makes them almost a universally bad idea to grow in the first place because eating them will hurt you.

This is basically the definition of a sloppy and poorly balanced change. The plants were hardly grown even when they were useful (in part because chemistry was ALREADY better back then). They were grown even less with salglu and they'll be grown even less if they deal toxin damage.

**Comment by Lumipharon** [comment]
This has nothing to do with reverts. Just add ingest friendly healing reagents that don't kill you if you have more then 10u of it. Whether they're called bicard or dong juice, doesn't matter.

**Comment by Iamgoofball** [comment]
@Lumipharon and then I get shat on for "adding more chems!!! just remove styptic and replace with this!!!" and then we end up back at the same "revert goonchem!!!" argument

even if that does succeed then why use styptic when botany can just make bicard renamed?

**Comment by babinsquared** [comment]
I'd rather have ingested useful healing chems over salglu, but I'd rather have salglu than toxic meds. Salglu is weak. If you're looking for ghetto, there you go. Nobody likes salglu because it's slow but it does get the job done.

There is no ingestable, effective, single-type healing reagent anymore? HMM, THAT'S A PROBLEM.

**Comment by Lumipharon** [comment]
because chemistry can pump out 20 patches in 60 seconds from round start.

Unless you have a floral somatory, getting good potency plants takes time, and have to be grown in batches, which requires more time and supervision.

Alternatively, just make styptic etc ingest friendly. They're literally the only reason why patches exist, and I don't see what it adds to the game.

**Comment by babinsquared** [comment]
Even if botany had access to "bicard renamed," styptic patches would still technically be better because instant upfront healing. Chemistry has always been superior at healing than botany. Botany just has a few choice special reagents which chemistry normally can't synthesize (only two of which heal, afaik - omnizine and vitamin). Botany is also already subservient to chemistry for mutagen. Without mutagen, it's much harder and time-consuming to get potency and species mutations. Funny how botany has access to omnizine but they're still mostly reliant on chemistry to get it in a reasonable timeframe.

**Comment by Iamgoofball** [comment]
Aaaaa

The toxin damage is INCREDIBLY MINOR

LITERALLY ONLY 0.5 PER UNIT

If I ate 50 units of styptic, that's 25 toxin max. I have to do that 4 times to go into crit. And charcoal rapidly heals 2 units of toxin damage a tick. 

Your average plant won't have more than 20 styptic in it. 

Just use a plant with charcoal in it to deal with the incredibly minor toxin damage.

**Comment by babinsquared** [comment]
Yeah let's just outline which department is already the superior healer

Medbay:
* Clone bays
* Surgery
* Cryo
* Sleepers (for what they're worth)
* Enormous quantities of roundstart meds from vending machines, from tables in a backroom, and from doctors themselves (they spawn holding a kit)
* Extremely flexible chemistry bay, capable of generating large quantities of almost every relevant medicine from the beginning of the round
* Pill bottles to fit said medicines in, for highly efficient storage

Botany:
* Plants which take time to grow, also more time and luck to become strong
* Special recolor mutant plants which take a lot of time and luck to grow, and then even more time to become strong
* Special useful weeds which also require more RNG to grow -- which, SURPRISE, you can significantly swing in your favor if you swing by chemistry for some sugar
* Plant bags for extremely efficient storage
* 50u bottles, drinkable but not instant like patches/pills are
* No touch-based applications by default (so no instant touch-styptic heals anyway)
* Some of the good things are , as opposed to starting with everything unlocked (like a certain other reagent-heavy department)

dude just leave them with salglu if you're gonna do this, this is a nerf
i'll just make omnizine or bottles full of vitamin+salglu or someshit if i'm looking for ghetto heals

**Comment by PKPenguin321** [comment]
"This has nothing to do with reverts. Just add ingest friendly healing reagents that don't kill you if you have more then 10u of it. Whether they're called bicard or dong juice, doesn't matter."

>and then I get shat on for "adding more chems!!! just remove styptic and replace with this!!!" and then we end up back at the same "revert goonchem!!!" argument

what the fuck are you talking about
nobody would mind at all if we finally had a half-decent ingestion-based healing chem again
if anything it would make goonchem more tolerable

**Comment by bgobandit** [comment]
I'm not gonna touch the goonchem issue but please don't fuck with blood tomatoes, there is nothing more entertaining to throw at the clonw

**Comment by babinsquared** [comment]
Other things of note:
Please no more reagents in ambrosia deus. It's so packed full of garbage already, it's tedious to extract omnizine because the beaker gets too full. If anything it needs the vitamin and salglu removed with no replacements - it's already a good healing food and vitamin is abundant elsewhere. Whatever the case just pls don't add any more.
Keep generic toxin in vulgaris. It's useful for chemist mixes, for traitor botanists, and it's also flavorful in that people who do the dank have to get treated for it. 
Blood tomatoes have no practical use but they do have a fun use. Keep.
Green tomatoes apparently get charcoal. This still means you need to mutate them, which makes styptic ingestion still a bad idea due to the time involved. Reishi is easier and gets morphine on top of charcoal.

**Comment by Tokiko1** [comment]
I think blue cherries have some special recipes, you'll need to remove them or change them if you remove blue cherries.

**Comment by Iamgoofball** [comment]
@Tokiko1 yeah, that's what's making travis die.

i'll revert the styptic and silver sulf shit then

**Comment by CosmicScientist** [comment]
More informed minds have already explained things but I'd like to point out one thing on the side.

As stated above the "Maybe you ate a medicine you shouldn't have?" message is annoying to get when eating food and especially bad if you don't understand what's happening.

Hell, if you didn't get that message then as soon as your "100%" disappears whilst eating food and you're not familiar enough with botany/cooking/code to understand it's not because you've been poisoned, you're going to immediately avoid the kitchen, possibly for the entire round.

I don't think you should have anything that harms you in any food unless it's an explicit quirk of the dish such as carp plates or slime jelly meals. I didn't even figure out the "ate a medicine you shouldn't have" message until I saw this here because medbay didn't know or care what happened to me at the time because I wasn't keeling over in their foyer.

**Comment by phil235** [comment]
@Iamgoofball still working on this?

**Pull request closed without merging**
