### PR TITLE
Grabber and Cavity Implant Interaction Nerf

### PR DESCRIPTION
**Pull request by BlueNothing**
Prevents the internal cavity from holding normal-sized circuit assemblies with combat circuits(heavily nerfs 'chestgun' circuits). Additionally, prevents circuits from grabbing or throwing in storage implants. As part of this change, grabbers can now hold items up to assembly size (shouldn't be problematic, since they cannot hold TTVs or two-handed weapons, and can no longer function inside of a storage implant).

[Changelogs]: # 
:cl:/
balance: Cavity implants can no longer hold normal-sized combat circuits. Grabbers can now hold up to assembly size.
fix: Grabbers and throwers no longer function inside of storage implants.
/:cl:

[why]: # (Please add a short description [two lines down] of why you think these changes would benefit the game. If you can't justify it in words, it might not be worth adding.)
Without these changes, cavity implant allows for the use of thrower guns capable of doing 90 damage in about two seconds, that cannot be disarmed, with no sign of their presence until they fire. Storage implants also allow this behavior with out these changes. The grabber buff is intended as a counterbalance for the circuitry crowd.

### CODE REVIEW

**Comment by DaxDupont** [comment]
They shouldn't fire at all from inside storage.

Also cavity bombs are a hilarious strat don't kill them. They require at least one other person to do the surgery.

**Comment by Shadowflame909** [comment]
>no more traitor suicide bomb with chest implants.

Sad.

**Comment by BlueNothing** [comment]
This doesn't prevent cavity bombs.

**Comment by BlueNothing** [comment]
This also prevents a specific failure of the 'firing from storage' problem that I was aware of. If there are others, I can fix that when I find out about them.

**Comment by BlueNothing** [comment]
_Singletanks can still be _implanted.__ They're the only items bigger than small that can be implanted, though.

**Comment by BlueNothing** [comment]
Singletanks can still fit in storage implants, too, and still work inside them (or they should). The only thing that changes for singletanks is that medium circuits can grab them now. They can still fit in storage implants, and cavity implants.

**Comment by AverageJoe82** [comment]
Oddly enough throwers don't work from backpacks but do work from storage implants @DaxDupont

**Comment by AlexTheSysop42** [comment]
What if you want to store a non-singletank normal item, like a box or a chemical bomb core (with C4)?

**Comment by BlueNothing** [comment]
Then you're out of luck. I basically never hear of anyone who does that, anyway, though, so it was good that this was here, so someone would speak up.

**Comment by YakumoChen** [comment]
it's specific interactions like these that require genuine effort and creativity we should be applauding, not removing

**Comment by BlueNothing** [comment]
Don't get me wrong, this stuff was cool and fun while it lasted, but it
also had some problems, and this is intended to fix said problems.

On Jun 27, 2018 12:09 AM, "YakumoChen" <notifications@github.com> wrote:

it's specific interactions like these that require genuine effort and
creativity we should be applauding, not removing

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/tgstation/tgstation/pull/38748#issuecomment-400536819>,
or mute the thread

**Comment by BlueNothing** [comment]
Don't get me wrong, this stuff was cool and fun while it lasted, but it also had some problems, and this is intended to fix said problems.
@YakumoChen Which interactions are you referring to? Just to be sure we're on the same page.

**Review by optimumtact — DISMISSED** [review]

**Comment by optimumtact** [comment]
This is such an common sense obvious fix and syptomatic of everything wrong with circuit coding.

**Comment by Therapist1** [comment]
Why should cavity implants have to suffer from the powergaming of circuits? I agree with the removal of chest guns, but there is no sense in merging a feature that is otherwise fine without circuits.

**Comment by AverageJoe82** [comment]
@Therapist1 what does this actually take away from chest cavities though?

**Comment by Therapist1** [comment]
“Shrinks the internal cavity, allowing only singletanks, small, and smaller items to be implanted in the chest”

**Comment by AverageJoe82** [comment]
yeah but what normal sized item did you want to have as a chest implant

**Comment by optimumtact** [comment]
maybe he can't fit his egomania in his chest after this change

**Comment by fludd12** [comment]
Why not just make implanted circuits only able to shoot yourself, rather than shrink the human chest cavity? Or just disable them, like you did with throwers...?

**Comment by PKPenguin321** [comment]
Doesn't cavity implant have a blacklist for things like the nuke disk? Just adding circuit assemblies to the blacklist would probably be a more elegant fix than nerfing cavity implants as a whole

**Comment by fludd12** [comment]
Stopping circuit implants as a hole wouldn't be preferable, IMO, but maybe blacklisting thrower circuit components and weapon circuit components? IIRC, the cavity blacklist checks recursive depth, so it'd work while still allowing neat things like GPS circuits or health monitor circuits to be implanted.

**Comment by PKPenguin321** [comment]
Not worth nerfing cavity implant overall though

**Comment by Therapist1** [comment]
Apparently disagreeing makes me an egomaniac? Still, why reduce the size of cavity implants?

**Comment by BlueNothing** [comment]
My position here: Implanted throwers are not intrinsically problematic, but
are very imbalanced as-is. Storage implant allows you to store a circuit
that deals almost 50 damage on a salvo, while leaving both hands free?
Broken. Cavity implant (requires help from someone with surgery stuff)
allows you to store and use a circuit that does about 15 DPS? Seems...
reasonable.

I'd probably be okay with keeping cavity implants as-is and blacklisting
medium circuits with grabbers and throwers, but that seems more technically
complex. That said, if this PR merges, and someone codes that one, I'll
support it.

**Comment by DaxDupont** [comment]
throwers shouldn't fire from inside backpack/storage locations other than hands.

**Comment by DaxDupont** [comment]
The fix is to prevent throwers from being to throw from inside things.

**Comment by BlueNothing** [comment]
I agree that backpack throwers shouldn't be a thing. I think that throwers
should, essentially, work in three positions: In-hand, On-floor, and
Implanted. We seem to agree on the first two. The last one, however,
appears contentious.

On Jun 27, 2018 12:11 PM, "Dax Dupont" <notifications@github.com> wrote:

throwers shouldn't fire from inside backpack/storage locations other than
hands.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/tgstation/tgstation/pull/38748#issuecomment-400734729>,
or mute the thread

**Comment by DaxDupont** [comment]
>We seem to agree on the first two. The last one, however,
appears contentious.

I literally said throwers shouldn't work inside of ANYTHING. This includes implanted.

**Comment by BlueNothing** [comment]
I know what you said, and I know what I said. We simply disagree.

On Jun 27, 2018 12:43 PM, "Dax Dupont" <notifications@github.com> wrote:

We seem to agree on the first two. The last one, however,
appears contentious.

I literally said throwers shouldn't work inside of ANYTHING. This includes
implanted.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/tgstation/tgstation/pull/38748#issuecomment-400748468>,
or mute the thread

**Comment by DaxDupont** [comment]
Wait are you seriously implying you should be able to throw things out of the inside of your chest that's closed???

**Comment by BlueNothing** [comment]
It's not like you can see that the chest is closed... or even that it
necessarily is, if the surgeon doesn't cauterize.

On Jun 27, 2018 1:04 PM, "Dax Dupont" <notifications@github.com> wrote:

Wait are you seriously implying you should be able to throw things out of
the inside of your chest that's closed???

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/tgstation/tgstation/pull/38748#issuecomment-400757758>,
or mute the thread

**Comment by DaxDupont** [comment]
So people should be running around with a hole in their chest that shoots shards.

**Comment by BlueNothing** [comment]
I am completely okay with that outcome.

On Jun 27, 2018 1:07 PM, "Dax Dupont" <notifications@github.com> wrote:

So people should be running around with a hole in their chest that shoots
shards.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/tgstation/tgstation/pull/38748#issuecomment-400759117>,
or mute the thread

**Comment by Therapist1** [comment]
That is a very bad idea. A weapon that doesn’t require hands, can’t be disarmed, and can only be partly disabled with their death, and they will (presumably) have two other hands free that are also trying to fuck you up is no bueno.

**Comment by ExcessiveUseOfCobblestone** [comment]
A funny fix would be to have their examine display they have a frikken gun protruding out of their chest lol.

**Comment by BlueNothing** [comment]
I think that would be cool.

On Jun 27, 2018 3:53 PM, "Grandmother of 50" <notifications@github.com>
wrote:

A funny fix would be to have their examine display they have a frikken gun
protruding out of their chest lol.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/tgstation/tgstation/pull/38748#issuecomment-400808239>,
or mute the thread

**Comment by BlueNothing** [comment]
I don't really know how to do some of that stuff, but... how does this sound as a change: Prevent medium circuits with grabbers or throwers from being used in cavity implants, but nothing else. Buff grabbers as described here, and retain the function of small implanted circuits, regardless of components (with plans to add an examine feature for them soon, or at least requesting help from someone else to implement that, and maybe add logging)?

**Comment by AverageJoe82** [comment]
The last thing BlueNothing suggested is definitely the best solution to this since it doesn't hurt any interactions other than the toxic one this PR is trying to stop.

**Comment by AverageJoe82** [comment]
personally what I would write is
```dm
var/obj/item/electronic_assembly/EA = tool
if(istype(EA) && EA.combat_circuits && tool.w_class > WEIGHT_CLASS_SMALL)
    to_chat(user, "<span class='warning'>[tool] is to dangerous to put in [target]'s [target_zone]! Maybe if it was smaller...</span>")
    return 0
```
since that way it stops future combat circuits from causing the same issue in the future.

**Comment by BlueNothing** [comment]
I'm going to get to work on implementing that proposed change, and I'll try to add an examine text for people with small combat circuits in their cavity, then recommit.

**Comment by BlueNothing** [comment]
Okay, now it's updated. Examining for small implanted combat circuits isn't something I quite know how to do yet, but I doubt there will be a ton of abuse of this before I can get it worked out. As for logging, I think that should wait for Dax's PR https://github.com/tgstation/tgstation/pull/38762 to establish a framework.

**Comment by DaxDupont** [comment]
I already established a framework for circuit logging in the first logging PR. Throwers throwing will be logged in the currently open one. If you want more logging that doesn't fit in chat or attack, call investigate log on the assembly as in that pr

**Comment by BlueNothing** [comment]
Oh, whoops, hadn't noticed the first one merged, but that was all I wanted
to add for them, anyway.

**Comment by evsey9** [comment]
Just make throwers tear a massive hole in your chest, causing all of your organs ( including the brain ) to fall out and cause unstoppable bleeding that admin healing cannot fix because fucking hell how retarded do you have to be to think that you should be able to throw shit out of an implant

**Comment by optimumtact** [comment]
alright calm down everyone

**Comment by vuonojenmustaturska** [comment]
let's do this

**Pull request merged**
