### PR TITLE
Fixes announcements font scaling

### LINKED ISSUE #78875: Announcements are Smaller than Standard Text
## Testmerges: 
- tgstation/tgstation/pull/77307

## Reproduction:
1. Receive announcement.
2. **PRIORITY ANNOUNCEMENT/CENTRAL COMMAND UPDATE** text is actually smaller than normal text.
image
dreamseeker_08-14-48

### PR DESCRIPTION
**Pull request by lessthnthree**
## About The Pull Request

Creates CSS spans for priority announcement and minor announcement so they scale properly with the player's chosen font size

image

## Why It's Good For The Game

Fixes https://github.com/tgstation/tgstation/issues/78875

## Changelog

:cl: LT3
fix: Fixed font scaling for announcements
/:cl:

### CODE REVIEW

**Review by strandsofivy — CHANGES_REQUESTED** [review]
If we aren't going to style header elements to use percentage sizing, then we should at least give the announcement spans top and bottom margins so they stand out like they did before.

**Comment by lessthnthree** [comment]
There's a bit there from the breaks, but yeah we could switch to a margin.

**Comment by distributivgesetz** [comment]
Didn't see that in the image, at least there's something then

**Comment by lessthnthree** [comment]
Increased the spacing before and after announcements.

**Comment by TheVekter** [comment]
This honestly looks very not good, to the point where people were asking if it was a bug on Manuel earlier. Can we put a bounding box around it or something to make it stand out without needing five miles of line breaks before and after it?

**Pull request merged**
