### PR TITLE
Makes lethal injection actually lethal.

### PR DESCRIPTION
**Pull request by TechnoAlchemisto**
:cl: Papa Bones
tweak: Security's lethal injections are actually lethal now.
/:cl:

If you've used the lethal injections as warden/captain you know how garbage it is. It used to be potent before chloral was nerfed into the dirt. 

Hopefully this will make lethal injection actually good. I'm open to chemical changes, this crits within  15ish seconds (rough estimate).

### CODE REVIEW

**Comment by GunHog** [comment]
@Iamgoofball Is the best consultant on kill chems.

**Comment by TechnoAlchemisto** [comment]
I pinged him but he took more than 60 seconds so I PRed it anyways

**Comment by Iamgoofball** [comment]
good mix

**Comment by jughu** [comment]
Inb4 xenobiology breaks into prisoner transfer room to steal syringes cuz they had plasma and sec wont need it anyways

**Comment by Zilenan91** [comment]
That would be a good thing^^

**Comment by AlexCrimson** [comment]
I know its a minor thing, but isnt the lethal injection supposed to be painless? I assumed thats why we used Chloral for so long back when it was so lethal. Formaldehyde and Acid does not sound painless to me. Not that i have any knowledge about such things.

**Comment by TechnoAlchemisto** [comment]
Considering we have the electric chair assemblies too I think this is a situation where pain isn't really cared about.

**Comment by Cheridan** [comment]
Seems like a waste of plasma from a LORE standpoint

**Comment by jughu** [comment]
Keep it in i would legit laugh if science breaks in to steal the plasma

**Comment by GunHog** [comment]
15 units of plasma is not worth getting Gulag'ed....

**Comment by Zilenan91** [comment]
Perhaps it should be syringes full of nothing but liquid plasma so that this conflict happens

**Comment by coiax** [comment]
How much damage does 50 of /datum/reagent/toxin/amanitin do

**Comment by Core0verload** [comment]
Make it 30u morphine + 20u some other toxin, so it would fit old "puts you in sleep then kills you" pattern.

**Comment by WJohn** [comment]
You could just do chloral, lexorin, cyanide, and one or two traitor-only poisons. Acid and plasma seems just a bit weird.

**Comment by Iamgoofball** [comment]
@coiax

**Comment by AlexCrimson** [comment]
50 units of Cyanide would be more than enough to kill someone, and thats what the movies usually use in those suicide capsules, right?

Amantin would be completely overkill in 50 units. 20 is enough to instantly kill someone. Although it only does damage once it leaves the victims system. Its not an execution poison.

**Comment by coiax** [comment]
I don't think Cyanide is that potent in tg

**Comment by AlexCrimson** [comment]
Its lethal with 10 units. Just takes a little time. Shouldnt be an issue considering if you are getting a lethal injection you are probably restrained. Against someone that can get treatment its probably not great because some of the damage is oxyloss, which i think your roundstart epipen can counter.

**Comment by lordpidey** [comment]
Could you include some miner's salve in there, you know, to make the execution more humane, because... rights... or something...

**Pull request merged**
