### PR TITLE
Expands Northstar TComms To Proper Rather than Birdshot

### LINKED ISSUE #74749: NorthStar only has a Tcomms server for the Common channel, yet every other radio network works fine anyways
Reporting client version: 514.1589

## Round ID:
[203802](https://scrubby.melonmesa.com/round/203802)

## Testmerges:
- [Adds a Material Stack manipulation apparatus for Engineer Cyborgs, replaces the R-Glass tool](https://www.github.com/tgstation/tgstation/pull/74297)

### PR DESCRIPTION
**Pull request by orthography**
## About The Pull Request

Northstar was using birdshot tcomms, this almost fully clears it up (I'm sorry for stealing the soul of the tcomms design)

## Why It's Good For The Game

Fixes https://github.com/tgstation/tgstation/issues/74749

image

## Changelog
:cl:
fix: fixed northstar tcomms to use proper rather than birdshot
/:cl:

### CODE REVIEW

**Comment by BlueMemesauce** [comment]
How is making tcomms much more complex good for the game? I think having it simplier makes it much easier for players to interact with

It also looks like you've caused #74813 again by accident

**Comment by Cheshify** [comment]
Screenshot please!

**Comment by orthography** [comment]
> Screenshot please!

Added!

> How is making tcomms much more complex good for the game? I think having it simpler makes it much easier for players to interact with
> 
> It also looks like you've caused #74813 again by accident

Oops, got carried away with symmetry with #74813

As brought up in the issue report it's improper to use the birdshot version of tcomms, even being marked as a Northstar mapping issue by tattle. While the room for tcomms is small and thereby needs some compromise, but by placing all radio signals on one we ignore the sabotage aspect of tcomms. 

It's not as easy to take down comms for security or command when it's just all on-one, it also allows for one block of X-4 to totally wipe out tcomms,  rather than the previous barrier that it's spread apart.

**Comment by Cheshify** [comment]
Just a minor point, could you zoom out of that screenshot? You'd need to displace part of maint to account for the space used and I'd like to see what's up.

**Comment by orthography** [comment]
> Just a minor point, could you zoom out of that screenshot? You'd need to displace part of maint to account for the space used and I'd like to see what's up.

Updated!

**Comment by Cheshify** [comment]
image
 I'm not sure how much I like the doublewalls being used outside of the ship hull. There's a reason I use the two-walls-with-a-grille  around maintenance as a more visually appealing barrier for high-risk areas. You could either Expand the area slightly and replace all the external walls with R-walls or give the outside walls to maint? 

I think if you wanted to put more space in tcomms and spread things out further, that could be acceptable and good.

**Comment by Cheshify** [comment]
image
Maybe even expanding it like this? Then tossing something fun in it like some disabler turrets or something, with a turret anyone with tcomms access can control. Maybe don't press machines against the walls though.

**Comment by BlueMemesauce** [comment]
the rack with the circuit boards in the control room still has a telecomms floor which means it's initially filled with cold air causing active turfs
image

**Comment by orthography** [comment]
> image Maybe even expanding it like this? Then tossing something fun in it like some disabler turrets or something, with a turret anyone with tcomms access can control. Maybe don't press machines against the walls though.
> 
> This is just a quick mockup. Just avoid the doublewalls, protection can be something unique.

But then you cant reach anything in the middle.

**Comment by Cheshify** [comment]
> > image Maybe even expanding it like this? Then tossing something fun in it like some disabler turrets or something, with a turret anyone with tcomms access can control. Maybe don't press machines against the walls though.
> > This is just a quick mockup. Just avoid the doublewalls, protection can be something unique.
> 
> But then you cant reach anything in the middle.

ah shit I didn't even see this. Not that specific layout of the machines. I meant the walls moreso.

**Comment by orthography** [comment]
> snip
> ah shit I didn't even see this. Not that specific layout of the machines. I meant the walls moreso.

How does the new one look?

**Comment by BlueMemesauce** [comment]
image

**Comment by Cheshify** [comment]
> > snip
> > ah shit I didn't even see this. Not that specific layout of the machines. I meant the walls moreso.
> 
> How does the new one look?

Looks great! 0 issues, you should bug maptainers about the merge

**Review by Maurukas — APPROVED** [review]

**Pull request merged**
