### PR TITLE
MiniStation Aesthetic Overhaul

### PR DESCRIPTION
**Pull request by pudl**
This PR makes MiniStation look nicer.
- Replaces all border firelocks with normal ones.
- Removes many extraneous firelocks (such as ones that covered mostly unimportant windows, and all maintenance firelocks.)
- Gives chemistry a heater.
- Gives engineering a transit tube dispenser.
- Replaces rack/suit combos with SSUs. Engineering now has 2 engineer hardsuits and 1 atmospheric hardsuit.
- Adds "Mining Unexplored" area to the asteroid field surrounding mining.
- Fixes missing icon states for research-related shutters and pod doors as well as two comfy chairs at arrivals.
- Removes an air alarm in the science freezer, as there are no air vents in the area, so it just produces an atmospherics error all round.
- Moves around some lockers in engineering to make the department more congruent.
- Gives medbay modern blue tiling.
- Adjusts some lattices that were unattractive.
- Replaces two normal plating in toxins testing with airless plating.

### CODE REVIEW

**Comment by WJohn** [comment]
Impressive.

:+1: 

Can we have a picture of the updated map?

**Comment by SconesC** [comment]
pictures please but this sounds nice

**Comment by pudl** [comment]
@SconesC 
minifull

**Comment by WJohn** [comment]
This is a nice upgrade, although I do personally wish that the halls had the repeating corner tile pattern to illustrate which hall is which. Probably not necessary on a station this small though.

**Comment by CorruptComputer** [comment]
@pudl You forgot the full tile windows in medbay and science.

**Comment by pudl** [comment]
@corruptcomputer No I didn't.

**Comment by kyrahabattoir** [comment]
very cool @pudl ! But are you sur eengineering needs 3 ssus on such a small station? the initial kit only gave them 1. Also, if i may point out, you forgot to give an SSU to mining.

Wouldn't it be better to have 2 mining SSUs and 2 engineering ones?

**Comment by duncathan** [comment]
2 mining, 1 engineering, 1 atmos might be better. What about the CE's hardsuit?

**Comment by kyrahabattoir** [comment]
There is no CE on ministation i believe.
Speaking of that, does anyone know how to fix the job selectiojn on ministation? some jobs are available but don't exist in the station, and since they have no spawn point it fucks up.

**Comment by pudl** [comment]
@kyrahabattoir Are you just compiling with the map, or are you checking "Ministation.dm"
Engineering has 2 engineering and 1 atmos ssu. I'll fix the mining one later.

**Comment by kyrahabattoir** [comment]
@pudl ministation.dm, but still a friend of mine picked... i think the chef slot? And spawned at the title screen.

**Comment by pudl** [comment]
@kyrahabattoir Try to manually check off every Ministation file, excluding Ministation.dm, then. Basically compile everything with the map yourself.

**Comment by kyrahabattoir** [comment]
@pudl I do that all the time...

**Comment by pudl** [comment]
@kyrahabattoir If that's what you normally do, then only check Ministation.dm this time. Don't check anything else map related, not even Ministation.dmm.

**Comment by kyrahabattoir** [comment]
@pudl that is exactly what I do. Don't make me look dumber than i am, this is not a problem on my end or i wouldn't mention it :p
Ministation won't start if you do not follow the procedure anyway due to the extra scripts it needs.

**Comment by pudl** [comment]
Please merge this.

**Pull request merged**
