### PR TITLE
Removes cryo syringes and cryo shotgun darts

### PR DESCRIPTION
**Pull request by Thunder12345**
## About The Pull Request
Purges cryo syringes and cryo shotgun darts, and all references to them from the code.

## Why It's Good For The Game
Cryo syringes are, to put it mildly, a blight on chemistry and its balance. Every single design decision around the difficulty of using pyrotechnic chemicals can be sidestepped by heating the ingredients to max temperature and putting them in a single cryo syringe. This leads to instant kill weapons like RDX+teslium or TATP syringes, which mix their ingredients and instantly explode as soon as the syringe makes contact with something.

Nuke ops have to cough up 8 telecrystals for a rocket launcher that causes a roughly similar explosion, plus 4 more for each subsequent rocket, all with the cost of the launcher being a bulky item. Based on this, it seems like it should be inconceivable for chemists to have access to the same firepower with only a syringe gun that fits in a backpack, their chem dispenser available from roundstart and a single techweb node.

Removing these syringes will prevent chemists from evading the dangers of working with explosive chemicals, and should have little to no impact on other applications since very few other reactions exist which need to take place on being injected into a person.

Cryo shotgun darts present an identical problem, and are only not seen in the wild due to their smaller capacity and position far into the techweb making them comparatively undesirable at a point when rapid syringe guns are likely already researched.

## Changelog
:cl: Thunder12345
del: Cryo syringes and cryo shotgun darts have been removed from the game
/:cl:

### CODE REVIEW

**Comment by Glassmanner** [comment]
Ided remove ples

**Comment by TheVekter** [comment]
Nah, I agree with this one - these things aren't used often, but when they are, it's pretty fucking goofy.

**Comment by Shadowflame909** [comment]
I blame that PR that added a bunch more explosives for no raisin

Cryo Syringes > 5 new explosives PR.

**Comment by Thunder12345** [comment]
Before those were added the situation was pretty much the same, since you could just as simply make a cryo syringe meth bomb. The underlying issue is still the syringe itself trivialising explosive chems.

**Comment by Shadowflame909** [comment]
Considering the codebase move to make OP things more rare, like the marksman rifle and the BOH. Are you sure it simply isn't a rarity issue.

I propose making both these items unobtainable without admin intervention then fully gutting them. Allowing for easier reimplementation through anomaly crafting. Like a bluespace anomaly + a bluespace syringe.

**Comment by ExcessiveUseOfCobblestone** [comment]
Or just work with explosions in a way that you have to be careful.

"lol nope" no downside items are dumb. No react doesn't even have medical applications outside of maybe seiver.

**Comment by Thunder12345** [comment]
@Shadowflame909 and if someone wants to add that at a later date, readding the syringe itself is trivial. It has no unique functionality that warrants it being kept as an admin only item, and it would only serve as a few more lines of unnecessary bloat.

**Comment by AtlasRules** [comment]
i ded pls remove....,,,,,,,,,,,,,,,,,,,,,.................................

just take the death like a man instead of using your coding to remove it, they're fine

**Comment by necromanceranne** [comment]
Nothing like gibbing someone with no counter even when you don't pierce their suit because it mixes on impact.

Nitroglycerin syringes could literally waste rooms. And with a rapid syringe gun they are unironically semiautomatic grenade launchers you could print out of the fucking medlathe, not out of security.

Me and pretty much everyone I knew who had discovered how utterly and inconceivably broken these things were vowed to keep it a quiet secret until the cat was out of the bag and they started to get abused. If Thunder hadn't made this PR out of the blue, I'd have done it the moment I caught wind of their abuse. This is straight up unfair as fuck and even gets past stuff like meth explosion internal mixing due to it being better to fire into syringe counters than not. 

When you are looking to this over piercing syringes, the dedicated syringe for puncturing through material, just because an explosion is a definitive method of game ending someone without any effort, that's really not good. And more importantly, it's all the lethality of elances in a discreet and concealable package but faster and more accurate and from an extremely safe distance. And if you happen to have a dart gun, this is even more so.

Only will get worse with instant explosions.

Legit, there aren't counters to this, nothing protects you short of sleeping carp and that's if you know it's coming at you and you get throw mode up and you're not standing immediately next to a wall, and given most halls are 3x3 wide that won't save you if it's a nitrosyringe. They are nitrotomatos on cocaine, but just without the spammability...kinda. They are cheap to print and you can put more than enough of them into a chem bag to make your way through a station just opening holes everywhere if it takes your fancy.

Cryo shotgun darts were kinda bugged though and it was inconsistent as hell. But the syringes are very reliable.

**Comment by SkeletalElite** [comment]
Better idea, make it so it never mixes if it doesn't hit a person or doesn't penetrate. Hit a wall? No dice. Someone has pierce protection? Also no dice.

**Comment by itseasytosee** [comment]
There are two alternate solutions that I'm not saying are nessisarly better. 1 making the big booms not create in the body and making the chems not mix on a miss. 2 nerf cryo syringes to only be able to hold 10u or a chem which if math is correct in even with nitroglycerin will on make and explosive power of 3.1, not enough to gib.

**Comment by CRITAWAKETS** [comment]
keep cryo shotgun, because that requires both effort and its on the same power level as shotguns if not lower.

**Comment by Iamgoofball** [comment]
10u cap fixes this problem.

**Comment by optimumtact** [comment]
lets delete all the explosive chems instead

**Comment by ExcessiveUseOfCobblestone** [comment]
> 
> 
> lets delete all the explosive chems instead

uuhhh UHHHHHH

:b:ased?

**Comment by OverlyGeneric** [comment]
> lets delete all the explosive chems instead

revised: let's get rid of all the old explosive chems and make better ones.

**Comment by Coastfront** [comment]
See now part of me wants to defend cryo syringes. But when i both figured out and used a nitro syringe loaded into rapid gun and got to gib 12 people at range with almost no counter, It becomes very fucking obvious how unfair this is. Cryo syringe bad

**Comment by necromanceranne** [comment]
Explosives are fine. It's entirely in the ease of delivery and the difficulty of delivery. Cyrosyringes beat literally every explosive delivery method out of the park and then some. Some weapons like rocket launchers don't even come close to these things in power.

Removing the explosion chems entirely doesn't do anything other than lop off a limb because of a bruise. They're bullshit to get hit with but if their method of being employed was both more difficult and dangerous to the operator as to their target, then explosives would be in a better. Chemistry being as robust as it is actually isn't a detriment but it's explosives are far too easy to employ and that is their only fault. (Personally I'm not a big fan of grenades as they stand but I don't see it as a particularly big issue. I have more issue with syringes as a whole in terms of chemistry bullshit and explosives are by far the least problematic element of chemistry except where cryosyringes are concerned.)

**Comment by optimumtact** [comment]
I don't really want to merge this but I don't really see any other alternative without someone cleaning up chemistry

**Pull request merged**
