### PR TITLE
Upgrades the chairs on the syndicate shuttle.

### PR DESCRIPTION
**Pull request by harmonyn**
where better to sit in your turtleneck

### CODE REVIEW

**Comment by lzimann** [comment]
this revives tactical chairs

**Comment by coiax** [comment]
You missed Delta

**Comment by bgobandit** [comment]
no I didn't it's literally the first one

**Comment by bgobandit** [comment]
wish me luck boys

**Comment by bgobandit** [comment]
the map conflict fixer doesn't list any maps when I run it WHAT DO

**Comment by coiax** [comment]
Just invoke @xxalpha @xxalpha @xxalpha three times.

**Comment by xxalpha** [comment]
I am summoned.

You need to actually cause the conflict locally by attempting t merge the most recent upstream master.

**Comment by KorPhaeron** [comment]
stale, should probably just remake the PR if you're having trouble with the conflict thing

**Comment by Xhuis** [comment]
this kills tactical chairs

**Pull request closed without merging**
