### PR TITLE
Reverts Hardlight Bows

### PR DESCRIPTION
**Pull request by silicons**
Unfortunately, after 3 tries, they still won't stop infinite-ricocheting. If someone could find where in the code it's fucked up in, that'd be great, but otherwise, pretend this never happend. :(

### CODE REVIEW

**Comment by ExcessiveUseOfCobblestone** [comment]
is it possible it has something to do with the reusable type in the projectile's path?

**Comment by jakeramsay007** [comment]
Don't merge this yet, I'm taking a pass at hardlight bows and seeing if I can fix the bugs.

**Comment by PKPenguin321** [comment]
Shoo shoo untested feature

**Comment by jakeramsay007** [comment]
I've managed to fix the bugs plaguing the hardlight bows. Making my PR soon­™.

**Comment by Cheridan** [comment]
that's what you get for being off theme

**Comment by ExcessiveUseOfCobblestone** [comment]
@Cheridan i still really like that bunny

**Comment by optimumtact** [comment]
Readd them when you figure out the bugs

**Comment by HankMoodyExperience** [comment]
dont ever readd these for the love of god

**Comment by Bawhoppen** [comment]
>readded ebows in revert

Please try

**Comment by optimumtact** [comment]
@Bawhoppen ? They were removed as part of the deal of having hardlight bows added. What on earth are you talking about.

**Comment by Bawhoppen** [comment]
Yea I know but we shouldn't have readded anyways cause generic stun weapons are dumb

**Pull request merged**
