### PR TITLE
Proto-kinetic crushers are significantly better

### PR DESCRIPTION
**Pull request by ChangelingRain**
:cl: Joan
balance: Proto-kinetic crushers have been worked over by our highly qualified techs, will recharge 12% faster, and no longer require very low-pressure atmospheres to fire!
balance: In addition, our techs have tweaked the quantum linker module and proto-kinetic crushers can apply multiple marks to different targets! Marks applied may eventually expire if not detonated.
/:cl:

The only person who I've ever seen use these effectively is @Ergovisavi, who is, to my knowledge, literally not around anymore, and he was the person who added them.

### CODE REVIEW

**Comment by Armhulen** [comment]
balance: Proto-kinetic crushers have been worked over by our highly qualified techs, will recharge 12% faster, and no longer require very low-pressure atmospheres to fire!

PR title: removes blob

**Comment by Iamgoofball** [comment]
>, and no longer require very low-pressure atmospheres to fire!

Miners are going to kill people on station. I hope you know this.

**Comment by Expletive** [comment]
@Iamgoofball 
`if(owner.mob_size > = MOB_SIZE_LARGE)`

**Comment by ChangelingRain** [comment]
It doesn't even DO anything to things that aren't large mobs. Maybe they'll use it to kill alien queens, that'd be cool as heck.

**Comment by Repukan** [comment]
This was added as a self imposed challenge item, not as something to be used by any doofus.

It's too strong with those buffs.

**Comment by Armhulen** [comment]
hahahahahaahahahah three shot people with your infinite charge revolver

I'm over exaggerating but still this is really strong

**Comment by ChangelingRain** [comment]
do any of you but @Repukan actually know how this thing works

**Comment by Bawhoppen** [comment]
The crusher is supposed to be a gimmick

**Comment by ChangelingRain** [comment]
# _The projectile does literally 0 damage._

**Comment by ChangelingRain** [comment]
it's still a gimmick! articulate how this changes it away from a gimmick! perhaps some concerns!

**Comment by Armhulen** [comment]
I THOUGHT THIS WAS THE GUN

OOOOOOOH yeah I like this

**Comment by Repukan** [comment]
It becomes too strong because if two people are marking it, then that's a guaranteed backstab damage bonus. It removes the challenge for ash walkers using tribal weapons and golems working for better tech and allows them to skip the challenge that comes with the role.

It was not meant to be used by all, and it being subpar was part of it's conception. It is rewarding when you know how to use it? Yeah, but quickly gets overshadowed by ka upgrades and such. That's why it's a voucher option.

**Comment by ChangelingRain** [comment]
do ash walkers even HAVE a proto-kinetic crusher? for that matter, you do still have to get into melee, which for golems is dangerous due to slowdown.
Admittedly, i can see your concerns, but it's not hard to make it do reduced damage if the mark wasn't yours.

**Comment by Repukan** [comment]
Don't add stuff on a basis of "do they start with this?" Look at the whole picture. They are often pit against miners and two humans with Crushers aren't gonna win against one ashwalker with at least two spears (which is usual armament for ash hunters.)

Slowdown is a non issue because our monster ai is laughable. You can kill a Goliath with the roundstart knife as a plasmaman or even a pickaxe inside your golem ship without suffering any damage. It's not exclusive to me either, I'd wager at least 60% of the server can do it.

Making it do reduced damage would be negated by the backstab damage bonus. If you removed that, then really, what's the point?

**Comment by ChangelingRain** [comment]
Oh, so your argument is that I shouldn't buff the crusher since it makes miners more likely to die in fights with ashwalkers, who can then use the crusher to hunt monsters. Kind of makes sense.

>If you removed that, then really, what's the point?
Since I am not a complete idiot, you'd be getting more damage from two people than you'd get from one, but the damage wouldn't just be double damage.

**Comment by Repukan** [comment]
I guess so, yeah.

It's mostly a gimmick weapon, as mentioned earlier. Maybe making the crusher upgradable by buying the modules that allow this in the vendor with points or printed by RnD would cull this. That way it would get used more so the buff is actually seen, and it would give it a sense of progression like Proto Kinetic Accelerators

**Comment by Repukan** [comment]
Also let us name crushers.

**Comment by AlexCrimson** [comment]
I very much doubt two people will ever get one of these and work together. The "well we could just nerf damage if its OP with two people" is bullshit that would nerf single players using it for no reason.

Just leave it as is.

**Comment by ChangelingRain** [comment]
If I nerf the damage for multiple users, single players will experience no gameplay changes _because I'm not a **fucking idiot, holy shit**._

**Comment by optimumtact** [comment]
shh joan just let it happen

**Comment by kevinz000** [comment]
>ergo

lol

**Comment by RemieRichards** [comment]
So this weapon, which is a prototype early version of the accelerator, works in pressured environments.
But the fully functional complete one doesn't?

**Comment by Jazaen** [comment]
http://tvtropes.org/pmwiki/pmwiki.php/Main/SuperPrototype

**Comment by ChangelingRain** [comment]
Given the mechanics of the weapon, it 'working' in pressurized environments doesn't really change anything.

**Comment by KorPhaeron** [comment]
@repukan @Kromgar you are the most active mining players on github what do you guys think


I agree trying to make the self imposed hard mode weapon viable kind of defeats the purpose

**Comment by Repukan** [comment]
I say nay with this tbh. A gimmick weapon should remain a gimmick

**Comment by ChangelingRain** [comment]
This is still as much of a gimmick as it was before. Please contest my statement with information.

**Comment by Repukan** [comment]
It was added as a one player self imposed crutch. Making it more focused on teamwork defeats that goal, and having it work on pressurized environments won't solve what I assume is fauna breaking into the station / golem ship.

If you want to make it better and keep it still the gimmick it was designed to be then add a hook upgrade that only works on marked creatures. Or something that rewards the miner using the crutch (although I believe they don't need upgrades since using this is mostly for the challenge and the thrill of the hunt.)

**Comment by ChangelingRain** [comment]
Actually you do have a point there, I'll limit it back to only letting you detonate your own mark.

**Comment by Repukan** [comment]
Shit

**Comment by KorPhaeron** [comment]
@lzimann 

Please dont merge PRs when I am in the middle of talking about them

**Comment by optimumtact** [comment]
@KorPhaeron don't forget to tag things DNM

**Comment by KorPhaeron** [comment]
That just seems so agressive

**Comment by lzimann** [comment]
sorry!

**Comment by optimumtact** [comment]
It's not agressive, it's just good communication

**Pull request merged**
