### PR TITLE
i miss the old security

### PR DESCRIPTION
**Pull request by pudl**
tasers to go security
suicide and ghost security, red fuckin hoes security
i hate the new security, the grey suit security
better off nude security, donuts for food security
i hate the grey security, always round delay security
i gotta say, nowadays i don't play security
see i invented security, there wasnt any security
and now i look and look around and there's so many securities
i used to love security, i used to love security
i even killed a greysuit, i thought i was security
what if security made a song about security?
call it "i miss the old security", man that'd be so security
stop all the buzz security, you know you love security
and i love you like security loves security

### CODE REVIEW

**Comment by pudl** [comment]
fucking conflicts

**Comment by Iamgoofball** [comment]
:-1: will conflict with Alternate Sprites

**Comment by TechnoAlchemisto** [comment]
i miss my home planet

**Comment by ChangelingRain** [comment]
please don't revert icon file changes unless they're actually *changing* icons(which this sec icon stuff didn't)

**Comment by KorPhaeron** [comment]
There is no reason to touch the dmis the old sprites are still there

**Comment by pudl** [comment]
i removed the grey icons so this will never happen again

**Comment by ChangelingRain** [comment]
please don't revert icon file changes unless they're actually changing icons(which this sec icon stuff didn't)

**Comment by pudl** [comment]
its in my code

**Comment by ChangelingRain** [comment]
#17753 does this better
both are bad but oh well

**Pull request closed without merging**
