### PR TITLE
Game mode and antag items/roles freeze (1 week warning)

### PR DESCRIPTION
**Pull request by optimumtact**
After some discussion, I have enacted a gamemode and antag items/roles freeze, to go into effect 1 week from this PR.

This should not come as a surprise, given that I have been talking publicly about the issue with the lack of crew content for some time, use this time to focus on crew content, job content and if you're very bold, perhaps a new job.

If you need inspiration, see this thread: https://tgstation13.org/phpBB/viewtopic.php?f=9&t=23614

Key info

WHEN: 1 week from now

HOW LONG: a minimum of 1 month, this will almost certainly be extended.

WHY: we want to encourage a focus on crew content and job content for standard crew

Note that maintainers can still greenlight an antag rebalance or change if they feel it's necessary at any time to protect the server or health of the community.

### CODE REVIEW

**Comment by adamkad1** [comment]
I can get behind that

**Comment by Arathianen** [comment]
Banning new modes or antag items isn't the way to go with encouraging more job stuff.

**Comment by senjx** [comment]
Yes it is. Bye bye antag content!

**Comment by Wutnold124** [comment]
> Banning new modes or antag items isn't the way to go with encouraging more job stuff.

what is the way then lol

**Comment by Whoneedspacee** [comment]
how would this affect my currently open pr which is near completion but cant be reviewed for some reason

**Comment by Dawson1917** [comment]
this is pretty based, i look forward to content that isn't about increasing your power level

**Comment by ExcessiveUseOfCobblestone** [comment]
Since this has happened before, If I catch branches being made during the freeze and just stashed until said freeze is over I will be autoclosing those.

> 
> 
> how would this affect my currently open pr which is near completion but cant be reviewed for some reason

it's fine for the purpose of this.

**Comment by MCterra10** [comment]
Orange man good

**Pull request closed without merging**
