### PR TITLE
Delta + Ice + Meta Atmos Hotfixes

### PR DESCRIPTION
**Pull request by vincentiusvin**
## About The Pull Request
Fixes many problems introduced by #59058

## Why It's Good For The Game
FIxes my own mistake.

## Changelog
:cl:
fix: Fixed multiple piping mistakes in Delta, Meta, and Icebox.
/:cl:

### CODE REVIEW

**Comment by Mothblocks** [comment]
we should lint for this

**Comment by norill** [comment]
you might be interested in #59263 
it reports a bunch of duplicate pipes all over the place

**Comment by vincentiusvin** [comment]
> you might be interested in #59263
> it reports a bunch of duplicate pipes all over the place

I'll take a look at that.

**Comment by vincentiusvin** [comment]
Found some more problems but I can't get straight to all right away. Will draft so it isn't accidentally merged.

**Pull request merged**
