### PR TITLE
Hydrogen Gas

### PR DESCRIPTION
**Pull request by Ghilker**
### THIS IS THE SAME AS #50284 HAD TO REMAKE BECAUSE OF GIT
This PR will add the Hydrogen gas, a new basic gas that will be used in future for more gas interaction and reactions.
What's changed in the PR (more details in the changelog):
- New gas H2
- New machine the Electrolyzer
- New SM interaction for H2
- Fusion no longer uses CO2, replaced with H2
- Fusion no longer generate nitryl and stimulum gases (only co2 and h2o)
- _Water vapor no longer generate the slippery surface (still does it when cold)_ no longer in the pr
- Water vapor now slips and clean if under 30 °C
- Plasma fire generate water vapor too 
- Reaction with N2 to make ammonia crystals
- Metal Hydrogen, made in high pressure and heat enviroment (and golems too!)
With this change fusion is "locked" behind more work to do instead of tech nodes, making it harder to do from roundstart and giving atmos techs more things to make before getting into fusion. Also fusion will get more work in the future to add uses to it.
Plasma fire got more realistic since normal fires consume the fuel to produce co2+h2o+energy (had to remove the slippery of normal h2o at high temperatures otherwise plasmafloods would be hell). Now there is another way to make h2o so that making h2 no longer need tritium to start with
The Electrolyzer is a machine that works open air, changing the h2o in o2 and h2, it can be upgraded and requires a power cell. To make it you need lasers, capacitor, cable coils, glass, gold and silver.

## Why It's Good For The Game
Increase the amount of stuff to do for the engineering team, stop fusion from being abusable roundstart, a new more basic gas to expand on the current gases and provide more interactions, more realism from an atmos perspective. Also new gas!

## Changelog
:cl:
add: Added H2 gas
add: Added H2 gas burn (reaction with o2, similar to tritium but without the radiations)
add: Added Electrolyzer (machine to make H2, requires power cell, once turned on and with h2o in the air will start converting it to h2 and o2 with the reaction 2H2O -> 2H2 + O2. Upgrading the parts will increase the amount of converted H2O and the efficency of the cell)
add: Added H2 interaction with SM (similar to trit, less radiation emission, same heat production and a bit of heat protection)
add: H2 reaction with N2 to make ammonia crystals (reaction in open air to make the crystals, temperatures between 0 °C and - 120° C, more N2 than H2)
add: H2 reaction with bz as catalyst at high heat and pressure (over 1e6 for both) to make metal hydrogen
add: metallic hydrogen golem (one of endish atmosian goal)
tweak: changed fusion to use h2 instead of co2, everything else is still the same
tweak: plasma burn now produces h2o too (a quarter of the produced co2)
tweak: H2O vapor now slip under 30 °C so that plasma fires are not hellish
imageadd: added electrolyzer sprites (reuse of some unused ones)
imageadd: added ammonia crystals sprites
remove: fusion no longer generate stim and nitryl
/:cl:

### CODE REVIEW

**Comment by TheSilverNuke** [comment]
speedmerge

**Comment by Ghilker** [comment]
yes please

**Comment by LordSaladin** [comment]
can we get the metallic forms of the other elemental(real) gases too.

**Comment by Ghilker** [comment]
maybe in future PRs i'll add something

**Comment by Ghilker** [comment]
first one was without the thing

**Comment by Timberpoes** [comment]
What's the concept behind Toxin bombs now?

I experienced 6-figure degree kelvin burns on Manuel with huge amounts of water vapour being released (water vapour as a percentage was equal to CO2) and significantly reduced tritium yields.

It took me nearly 6 cans of O2 alone to barely get the trit I needed. I ended up raiding Atmospherics for another 2 cans of O2 after that to get the plasma I needed. (1 can woulda probably done the trick but didn't want to risk it) and ended up filling the plasma can part of the toxins bomb with freakin 50,000 degrees kelvin plasma.

Needless to say that the whole process took me about an hour to figure out and didn't feel at all smooth or clean. I only managed it because I was on the station that starts with 6 O2 cans in Toxin storage

Is this change intended to make toxins harder to create good bomb mixes for?

**Comment by SamuelRowe** [comment]
please, please, put 3 pipe nodes on the Electrolyzer. Something like Node 1(Input) --> Node 2(Output) + Node 3(Output)

**Comment by Ghilker** [comment]
@Timberpoes If you use the basic setup that there is inside the toxin's incinerator you won't generate much of it. It is intended to make trit a bit harder to make (even tho i've seen toxins players make more than enough for multiple bombs)  so that you have to rethink a bit your way of doing it

@SamuelRowe I wont make it pipeable because, 1 i like the idea of it being an open air reaction, 2 making the code work that way is a pain

**Comment by Rohesie** [comment]
This has been reviewed previously, code-wise.
Do you feel the PR to be ready, and have you tested it locally enough to be satisfied by the results and guarantee it works like you intended it to?

**Comment by Ghilker** [comment]
i think so, yes, i just want to test it some more and to make some changes i wanted (mostly balance stuff or change a min() to a clamp() for better performances). I'll ping you on discord once i'm really done. Shouldn't take more than 2 to 3 hours

**Comment by Rohesie** [comment]
Alrighty.

**Pull request merged**
