### PR TITLE
You can now break open bones during surgery with a hammer like God intended in Surgeon Simulator.

### PR DESCRIPTION
**Pull request by Iamgoofball**
See title.
## Changelog
:cl:
add: You can now break open bones during surgery with a hammer like God intended in Surgeon Simulator.
/:cl:

### CODE REVIEW

**Comment by Shadowflame909** [comment]
Dang that title made me think this was gonna be a unique tc-less traitor surgery sabotage.

Imagine someone doing organ manipulation on you, only for them to start shattering all your bones.

**Comment by wesoda25** [comment]
Bait title

**Comment by trollbreeder** [comment]
STOP! Hammer time

**Comment by 81Denton** [comment]
Bruh how does a hammer saw bones

**Comment by Iamgoofball** [comment]
It's a surgeon simulator reference. The main tool you use to get through bone is a hammer.

**Comment by HomocidlePancakes** [comment]
1)Make the hammer 100% success chance.
2)Make it deal damage as you “cast” it instead on finishing the action.
3)Make it much faster than the saw.
4)Make it deal much more damage than the saw.

I wanna kill people with it.

**Comment by 81Denton** [comment]
Surgery steps are already convoluted enough, adding meme steps is only gonna make it worse. This can probably tie into #50558 though, you should chat with @Ryll-Ryll about it.

**Comment by ExcessiveUseOfCobblestone** [comment]
lol this was funny

**Comment by HomocidlePancakes** [comment]
How does adding a ghetto alternative make surgery more convoluted?

**Pull request closed without merging**
