### PR TITLE
[s] Revert "Revert "Improves bee lore""

### PR DESCRIPTION
**Pull request by Iamgoofball**
Reverts tgstation/tgstation#29972

### CODE REVIEW

**Comment by optimumtact** [comment]
24 hours please

**Comment by evsey9** [comment]
what the fuck

**Comment by Jordie0608** [comment]
I would prefer not to have 24 hours of this.

**Comment by optimumtact** [comment]
then ask remie to stop closing it

**Comment by evsey9** [comment]
Top 10 Anime Battles

**Comment by RemieRichards** [comment]
I'm not the one at fault here.

**Comment by optimumtact** [comment]
just wait 24 hours and you can close it anyway

**Comment by Iamgoofball** [comment]
@RemieRichards 
if i take the bee lore off, would you die?

**Comment by Iamgoofball** [comment]
big_1437631748_image

**Comment by MrStonedOne** [comment]
````
[01:38:36] <Iamgoofball> she probably just gave up and went to work
[01:38:39] <Iamgoofball> a victory for the bees
[01:38:42] <TheGhostOfWhibyl1> [tgstation] RemieRichards closed pull request #29976: [s] Revert "Revert "Improves bee lore"" (master...revert-29972-revert-29970-patch-291) https://github.com/tgstation/tgstation/pull/29976
````

**Comment by Iamgoofball** [comment]
mqdefault

**Comment by RemieRichards** [comment]
I'm already at work, I'm closing this in between compilations.

**Comment by Iamgoofball** [comment]
maxresdefault 1

**Comment by Iamgoofball** [comment]
ruug67q

**Comment by evsey9** [comment]
wtf

**Comment by Iamgoofball** [comment]
axxocn 2

**Comment by RemieRichards** [comment]
@evsey9 it's the gay porn his desc are in reference too

**Comment by Iamgoofball** [comment]
it's not gay porn, it's art

**Comment by Qustinnus** [comment]
gachimuchi is not gay.

**Comment by Iamgoofball** [comment]
gachimuchi is probably one of the best anime i ve ever _b4ecf5e07882fec10195b600c13819d7

**Comment by Qustinnus** [comment]
https://www.youtube.com/watch?v=drGnb30QFwQ tell me at which point this art is "gay porn"

**Comment by Iamgoofball** [comment]
do the same with this:
https://archive.org/details/youtube-IX5jhZ5Ttms

**Comment by Iamgoofball** [comment]
@Qustinnus there's a PC version i wonder if someone's modded this in yet

**Comment by Qustinnus** [comment]
they better have

**Comment by kevinz000** [comment]
What the fuck...

**Comment by Qustinnus** [comment]
image
**fuck you**

**Comment by Arianya** [comment]
inbetween open and close comment

**Comment by Stealthkibbler** [comment]
Remie mate, stop being a dog cunt and let the goofball have his artistic bee descriptions, the man bestows his superior artistic impression upon the community but then he has to cope with shit cunts like you starving him of his artistic pride.

**Comment by Stealthkibbler** [comment]
Remie mate, stop being a dog cunt and let the goofball have his artistic bee descriptions, the man bestows his superior artistic impression upon the community but then he has to cope with shit cunts like you starving him of his artistic pride.

**Comment by Iamgoofball** [comment]
epmr

**Comment by Iamgoofball** [comment]
# CENSORSHIP OF THE HIGHEST CALIBER

**Comment by Stealthkibbler** [comment]
Mate status
[X] Dogged
[  ] Not Dogged

**Comment by lzimann** [comment]
stop with this shit

**Comment by Stealthkibbler** [comment]
Actual footage of remie confronting goofball about his prs
https://www.youtube.com/watch?v=71DIT6hYXYo

**Comment by Iamgoofball** [comment]
@Stealthkibbler just waiting on a merge mate

**Comment by Stealthkibbler** [comment]
@Iamgoofball Where's your speed-merge license mate? can you stand out of the pr for me mate? you've curbed the entire github with this act.

**Comment by Qustinnus** [comment]
image

**Comment by Iamgoofball** [comment]
chrome_2017-08-17_05-09-33

# MORE CENSORSHIP

chrome_2017-08-17_04-55-20
chrome_2017-08-17_05-09-23
chrome_2017-08-17_05-09-40
chrome_2017-08-17_05-09-45

**Comment by Iamgoofball** [comment]
@Stealthkibbler I'm not in the github, just waiting on my merge.

**Comment by Stealthkibbler** [comment]
@Iamgoofball That's fine mate, your pr' been involved in an accident and you are an occupant of the pr. Alright so what I'm gonna getcha to do since you don't want to show me your speedmerge license I'm gonna need ya to step out of your pr for me.

**Comment by Iamgoofball** [comment]
chrome_2017-08-17_04-55-20
chrome_2017-08-17_05-09-23
chrome_2017-08-17_05-09-33
chrome_2017-08-17_05-09-40
chrome_2017-08-17_05-09-45

# CENSORSHIP

**Comment by Iamgoofball** [comment]
@Stealthkibbler I dont have any features on me mate

**Comment by Qustinnus** [comment]
image

**Comment by MoreRobustThanYou** [comment]
I nominate this for "PR of the year"

**Comment by Thunder12345** [comment]
I wanna be in the screenshot

**Comment by ChangelingRain** [comment]
No. If you speedmerge memes, you're goign to get memed on.

**Comment by ChangelingRain** [comment]
I can't believe you've betrayed me like this.

**Comment by Qustinnus** [comment]
there really is a god

**Comment by DoctoreMad** [comment]
Newton's translation of the "Emerald Tablet" of Hermes Trismegistus
A translation by Isaac Newton is found among his alchemical papers that are currently housed in King's College Library, Cambridge University.

    Tis true without lying, certain & most true.
    That which is below is like that which is above & that which is above is like that which is below to do the miracles of one only thing
    And as all things have been & arose from one by the mediation of one: so all things have their birth from this one thing by adaptation.
    The Sun is its father, the moon its mother, the wind hath carried it in its belly, the earth is its nourse.
    The father of all perfection in the whole world is here.
    Its force or power is entire if it be converted into earth.
    Separate thou the earth from the fire, the subtile from the gross sweetly with great industry.
    It ascends from the earth to the heaven & again it descends to the earth & receives the force of things superior & inferior.
    By this means you shall have the glory of the whole world
    & thereby all obscurity shall fly from you.
    Its force is above all force. For it vanquishes every subtle thing & penetrates every solid thing.
    So was the world created.
    From this are & do come admirable adaptations whereof the means (or process) is here in this. Hence I am called Hermes Trismegist, having the three parts of the philosophy of the whole world
    That which I have said of the operation of the Sun is accomplished & ended.

**Comment by DoctoreMad** [comment]
By the way I wanted to ask how serious are the maintainers about this PR? I feel like they're just having fun but I can never tell.

**Comment by BeeSting12** [comment]
include me in the screenshot

**Comment by Cheridan** [comment]
im deadly serious

**Comment by Cyberboss** [comment]
Only one way to end this madness...

**Comment by Cyberboss** [comment]
>not ticking allow maintainer edits

**Comment by GunHog** [comment]
>> not ticking allow maintainer edits

I have learned this lesson the hard way.

**Comment by JJRcop** [comment]
[](https://github.com/tgstation/tgstation/pull/23989#issuecomment-279422067)

**Comment by Cyberboss** [comment]
Enough of this

**Pull request merged**
