### PR TITLE
Inquisitor Armour

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
To lead paranormal response teams. It is just reskinned paranormal response armour (which is just fireproof/magic proof ERT armour)

Actually I'll just do the other stuff in another PR whenever

### CODE REVIEW

**Comment by Dorsisdwarf** [comment]
A defense against the unexpected, huh?

**Comment by demonfiren** [comment]
I'm reasonably sure those things aren't revenant-proof, though.

**Comment by StormAGeddonz** [comment]
Spooky! :thumbsup: 👍👍👍👍👍

**Comment by Zilenan91** [comment]
How about putting a Holy Hand Grenade of Antioch in a special PRU armory?

**Comment by StormAGeddonz** [comment]
That would be cool as hell, make it suck shades in and destroy them.

**Comment by Zilenan91** [comment]
Or just explode like a HHH should

**Comment by StormAGeddonz** [comment]
But that's not fun, normal grenades already just explode

**Comment by Zilenan91** [comment]
Naturally a HHH would be a maxcap

**Comment by StormAGeddonz** [comment]
That sounds reasonable

**Comment by Dorsisdwarf** [comment]
HHH would be 0,9,9,9, of course.

**Comment by AlexCrimson** [comment]
If we are having some kind of Inquisition then we might as well go all the way and add some kind of brutal squad that purges the station of all Heretics. Not overpowered or anything, but an "antagonist" that has full sanction to kill people on the station... if they are found to be Heretics.

Go full Warhammer 40K on this bitch.

**Comment by HereticChurch** [comment]
:+1:

**Pull request merged**
