### PR TITLE
Remove infectability from xeno nest lavaland ruin

### PR DESCRIPTION
**Pull request by JJRcop**
At request of @nervere, see https://tgstation13.org/phpBB/viewtopic.php?p=489435#p489435

closes #43619 

:cl: JJRcop
del: Live facehugger eggs and dead facehuggers removed from xeno lavaland ruin.
/:cl:

### CODE REVIEW

**Comment by Jalleo** [comment]
I personally would of done this and a second PR with a spawner with a low chance to create a discussion of which would be better. Then later on with having a PR for different chance of different sized alien ruins on lavaland. Normally smaller instead of larger.

**Comment by Repukan** [comment]
What does this neutered ruin add that makes it worth keeping in

**Comment by JJRcop** [comment]
That is an excellent point. I'm not removing it in this PR, however I've made a branch that contains the removal. You can [PR it here](https://github.com/tgstation/tgstation/compare/master...JJRcop:xeno_burnt?expand=1) if you wish.

**Comment by imsxz** [comment]
it has stechkin, nvg, tactical turtleneck(very good jumpsuit, stylish and 10 melee armor, not available to normal crew and not ugly like sec clothes), syndie space suit(same resistance values as blood red hardsuit, helmet is flashbang protection), stun baton, xeno meat/skin

not a bad loot pinata even with this PR, though my instincts tell me I should be shouting "ided" and pressing the thumbs down button because i like my free antag roles

**Comment by Repukan** [comment]
Snowdin proved loot behind terrible AI npc defenses is bad and should be removed.

Hell it's just a shittier version of the caravan ruin sans xeno skin availability

**Comment by imsxz** [comment]
id argue it's better than caravan for the purposes of the international "awful ruins that need to be changed" list. caravan has even more loot locked behind less defenses and even has a gps signal screaming at space powergamers so that they can't not find it.

thats not what this PR is about though so i'll stop that train of thought. dont think ayy ruin needs to be removed. if there is any issue with the eggs (i've not personally had many issues with them as an administrator or a player) then i wouldnt be too sad to see them go.

**Comment by Repukan** [comment]
Do you like only read the title of the PR and then comment?

**Comment by imsxz** [comment]
??? i was responding to your comment about removing it and then said why i think this is a good PR. if you're referencing the thread that it was at the request of nervere, yes i see other admins had issues with it i just said that i didnt have them myself.

**Comment by 81Denton** [comment]
If you remove the eggs, you might as well replace the lava moat with regular floors so that miners can kill xenos for organs and the mediocre loot inside

**Comment by HomocidlePancakes** [comment]
How do you even get organs from simplemobs xenos? Surgery doesn't seem to work and butchering them just makes meat.

**Comment by 81Denton** [comment]
Right, the simplemobs only have hide and meat as bucher_results. Disregard what I said.

**Comment by nervere** [comment]
I requested this PR because the xeno ruin primarily gets used to self-antag with the facehuggers.
I don't want the ruin to be removed entirely, however, as it's nice other than that, hence this PR.
Plan of action if this doesn't get merged is to disable the ruin from the config.

**Comment by improvedname** [comment]
Add a rare chance for xenomorphs to drop xeno organs on a chance based butcher result so its atleast something worthwhile

**Comment by JJRcop** [comment]
I'm not intending to change this, it's ready.

**Review by ExcessiveUseOfCobblestone — APPROVED** [review]

**Comment by ExcessiveUseOfCobblestone** [comment]
me will prob merge later this afternoon unless someone has a good argument for keeping as is / full removal

**Comment by OverlyGeneric** [comment]
I never liked this ruin.

It's an unnecessarily large structure that takes up space that could be used for ore veins or other ruins. 

It lacks any challenge or reward. The enemies, even the queen, are stupidly easy to beat that even ashwalkers can kill them and the rewards are worthless for miners or ashwalkers.

The only redeeming thing about it was the eggs that were primarily used to be a newb-bait and a "trap" for the queen fight but made useless as the queen always chases you out of its arena.

Please just remove it. It provides nothing but repercussion-free griefing.

**Comment by tralezab** [comment]
We're removing the repercussion free griefing. We're not removing the massive simplemob hive. I'm a little annoyed with ruins that are just like "hey you clicked on a simplemob here's some syndicate gear woooo"

comparing to some others, the clown dome has a sliding puzzle, the winter dome has a security system lockdown, and even though this might have been removed as I haven't seen it around anymore the vault with the wish granter required a human sacrifice to open the loot, and the loot itself was kind of abstract

**Comment by OverlyGeneric** [comment]
> We're removing the repercussion free griefing. We're not removing the massive simplemob hive. I'm a little annoyed with ruins that are just like "hey you clicked on a simplemob here's some syndicate gear woooo"

I would remove say remove it altogether and it's free syndicate gear and way too big to be lavaland ruin.

**Comment by AdamElTablawy** [comment]
might as well remove it without the eggs-it's just a pointless simplemob loot pinata at that point.

**Comment by Arianya** [comment]
Do not go gentle into that good night,
Old age should burn and rave at close of day;
Rage, rage against the dying of the light.

Though wise men at their end know dark is right,
Because their words had forked no lightning they
Do not go gentle into that good night.

Good men, the last wave by, crying how bright
Their frail deeds might have danced in a green bay,
Rage, rage against the dying of the light.

Wild men who caught and sang the sun in flight,
And learn, too late, they grieved it on its way,
Do not go gentle into that good night.

Grave men, near death, who see with blinding sight
Blind eyes could blaze like meteors and be gay,
Rage, rage against the dying of the light.

And you, my father, there on the sad height,
Curse, bless, me now with your fierce tears, I pray.
Do not go gentle into that good night.
Rage, rage against the dying of the light.

**Comment by ExcessiveUseOfCobblestone** [comment]
it's a really late this afternoon ok

**Comment by Daxxed** [comment]
Why wasnt it fully removed ?
Everyone agrees that it is way too big for the mediocre loot in there.
On top of that, it can spawn multiple times and fill entire lavaland, losing the miners lots of megafauna and tendrils.
I never liked the fact that random observers could self antag with ghostroles by suiciding in there so alteast that's gone.

**Comment by ExcessiveUseOfCobblestone** [comment]
miners are not entitled to either of those things but I don't mind limiting it to 1 and trimming it down. Don't think a full removal is necessary.

**Comment by optimumtact** [comment]
@Daxxed you're not everyone

**Comment by Daxxed** [comment]
Just stating my opinions and experiences from playing miner a bit.
Do with it as you please.

**Pull request merged**
