### PR TITLE
New Chem master sprite

### PR DESCRIPTION
**Pull request by MrDoomBringer**
image
### here let me do it (closes #36489)

:cl: MrDoomBringer
imageadd: All stations have been outfitted with brand new Chem Masters! They have nicer sprites now!
/:cl:

cus the old ones were uckus.
ill add variants for pandemic and kictchenmaster or whatever later

heres a gif for yall's viewing pleasure:
https://i.imgur.com/3y61xqA.gifv

testimonials:
image
image
image
image

### CODE REVIEW

**Comment by Grazyn** [comment]
This is beautiful, thank you

**Comment by MrDoomBringer** [comment]
@Iatots 
>says it looks like a pipetting machine

image
>platform is clearly organized by rows, rather than cells

**Comment by Iatots** [comment]
So, what are the rows, and what is the arm doing?

**Comment by nicbn** [comment]
What the actual

**Comment by nicbn** [comment]
This is on the wrong colors, make it blue-white like the other chem machines.

**Comment by MrDoomBringer** [comment]
@nicbn i prolly will make other chem machines closer to these colors or something like that, but thats for a later PR. 

@latots the arm is clearly a 3d printer nozzle and the rows are clearly a textured surface for the 3d printmachine shit to cling to duh

**Comment by nicbn** [comment]
Do in this PR, if we merge this machine we will merge the others too

**Comment by MrDoomBringer** [comment]
@nicbn no i mean cus im 2 lazy and the other machine isnt as awful as the chemmaster was

**Comment by MrDoomBringer** [comment]
FUCK fine
pipette machine vs cool sliding machine? place ur votes
cool sliding gifs:

- https://i.imgur.com/wb6EFVj.gifv

pipette gifs:

- https://i.imgur.com/7Jf9hdr.gifv
- https://i.imgur.com/Ij8lAF5.gifv

**Comment by ShizCalev** [comment]
Seems more suited to be a replacement circuit imprinter tbh

**Comment by MrDoomBringer** [comment]
@ShizCalev citcuit imprinter already fits the theme of rnd. i feel like this being a pipetter might be work better to distinguish itself from the circuit imprinter?

**Comment by yorii** [comment]
This looks really good, but I think it should be more white to fit with the general medbay white and blue theme.

But reuse this exact coloring for the kitchen machine perhaps?

**Comment by MrDoomBringer** [comment]
@yorii sst13 spriting in general aims for a more retrofuturistic aesthetic, so while plain white and blue has its places, its generally better to aim for off-white or beige colors

**Comment by WJohn** [comment]
I am cool with the retro future aesthetic, and would like to see more equipment move in that direction.

**Review by WJohn — APPROVED** [review]

**Pull request merged**
