### PR TITLE
Makes medibots tricord aware. Changes the tox treatment to charcoal

### LINKED ISSUE #21346: Medibots can and still will overdose you
>30u tricord >Overdosing >It keeps injecting the same things >You now have metric tons of tricord in you.

### PR DESCRIPTION
**Pull request by Cyberboss**
Fixes #21346

:cl: Cyberboss
fix: Medibots, by default, can no longer OD you on tricord
tweak: They will now use charcoal instead of anti-toxin to heal tox damage
/:cl:

### CODE REVIEW

**Comment by Shadowlight213** [comment]
NOOO. FEATURE ;_;

**Comment by kevinz000** [comment]
THANK YOU.

**Comment by kevinz000** [comment]
WAit wait, this makes it not heal you if you have tricord? The issue is it's MIXING overdose-levels of tricord on default if you have more than 5 or 10 of each type of damage, but I guess ignoring tricord is also an issue, as if it mixes tricord you might overdose not from the mixed tricord, but from the tricord inside you.

**Comment by XDTM** [comment]
Yeah, having tricord isn't the real issue; you should make treatment_brute_avoid etc. a list instead, and put in each the other two components to make tricord.

**Comment by GunHog** [comment]
It would be easier if you just changed one of the chems....

**Comment by Supermichael777** [comment]
medbots now inject milk, orange, lime, and tomato juice. MMMMMM DELICIOUS

**Comment by XDTM** [comment]
yeah after all we have charcoal, and the only differences with antitoxin is that it doesn't OD and decays half as fast, which probably won't be a huge balance issue.

**Comment by ExcessiveUseOfCobblestone** [comment]
>medbot now inject milk,orange,lime, and tomato juice.

Butlerbots?!!

**Comment by Supermichael777** [comment]
how did you manage to fuck up a space copy pasting!?

**Comment by GunHog** [comment]
Excellent!

**Pull request merged**
