### PR TITLE
Touch-ups on 2nd level BoxStation

### PR DESCRIPTION
**Pull request by Son-of-Space**
## About The Pull Request

This pull request does 4 things:
**1. Standardizes some maintenance and wastes pathing to ensure that players can access every unrestricted area of maints through the snow wastes.** 
image
Pathing that can be traveled towards another area is also properly denoted by marker beacons which are placed every player screen or so
image
Two areas of maintenance were given no access requirements or maintenance access requirements to allow for slightly more freedom of movement:
Mining Base
image
BenoBio
image

**2. Standardizes window layouts for the 2nd level (interior full windows, exterior directional windows)**
image

**3. Standardizes signage on airlocks (so no "space" signs anymore, just cold and mask signs.)**
image

**4. Rebuilds some of the catwalks and accessible spaces to look less randomly placed and more haphazardly placed / placed with general purpose.**
Medical to Science:
image
Service to Chapel/Science:
image
Medical to Public Mining:
image
Commons to Mining/Medical:
image

I also added a few racks and one fire locker.

## Why It's Good For The Game

The purpose of this PR is mostly to clearly demarcate paths that players can travel throughout maintenance and make it easier to understand whilst playing that you can traverse paths between maintenance, showing that maintenance is interconnected if not also dangerous to traverse.

This way, instead of maintenance being separated into 4 pieces, players can reliably move between all sections of maintenance if they can survive the cold and beasts. Having the marker beacons shows where players can move between places without getting lost in the wastes and without detracting from the "We've just got our claws barely sunk in here" vibe that maintenance on this level is going for.

Standardizing some of the other bits just helps for general cohesion on the map and prevents players from associating the wastes with a vacuum (since it isn't).

I also tried to minimize the extra white space I was making during this to make sure that miners had plenty of area they could mine from.
## Changelog

:cl:
qol: It is now easier to tell that lower maintenance on box is traversable and is reliable to traverse.
balance: tweaked access reqs for certain doors in lower maintenance on BoxStation.
/:cl:

### CODE REVIEW

**Comment by Son-of-Space** [comment]
Mapp Diff Bot broke 😳

**Comment by Son-of-Space** [comment]
image

**Comment by AlinaStarkova** [comment]
this isnt connected to a wall



i can't tell if these have the inside areas over the outside lights or not. if not they need the area over the lights, thats how the lights get power

**Review by Maurukas — CHANGES_REQUESTED** [review]
<details>
<summary> Genturfs/Active turfs here. </summary>

image

image

</details>

Other than that, I see no issues. Looks like a nice bit of detailing work.

**Review by Maurukas — CHANGES_REQUESTED** [review]
This one's still here:
image
image

**Comment by Son-of-Space** [comment]
Oh, your original review had the same photo twice which is why I thought there was only one.

**Pull request merged**
