### PR TITLE
high-capacity fuel tanks

### PR DESCRIPTION
**Pull request by pubby**
stupid meme

Traitor assistants and engineers can purchase high-capacity fuel tanks for 5 TC. As you can assume, the explosions of these is more !!FUN!! than regular tanks, but like regular tanks, they're not convenient to make use of.

(note: these don't gib, and the range is only a few tiles more than regular tanks)

:cl: Pubby
add: Traitor assistants and engineers can buy high-capacity fuel tanks. BOOM!
/:cl:

why: Welderbombs tend to be pretty fun and funny.

### CODE REVIEW

**Comment by 81Denton** [comment]
elephantine is a great word

**Comment by GunHog** [comment]
This does not seem worthwhile as a traitor item.

- Since it can only be obtained through TC, it is an obvious traitor item.
- It is restricted to roles that have the easiest time obtaining tools and fuel.
- Its purpose as a fuel tank is obsolete given that engineering staff can use normal, non suspicious tanks, and Greyscum can buy more welding tools for 1TC each in a pinch.
- Its purpose as a bigger welding tank bomb is overshadowed by the huge drawback of causing panic or attacks if you are seen dragging one around, while you can buy a much easier to use mini-bomb for 6TC instead.

I think this would be better off as a map spawn in Engineering, or something.

**Comment by KorPhaeron** [comment]
Seems redundant with the syndie bomb, weirdly improvised for a traitor item

**Comment by pubby** [comment]
@KorPhaeron Uplink idea doesn't sound very hot then.

The ops ship and other syndicate places do have fuel tanks mapped into them. Instead of putting these in the uplink, would you approve of reskinning those with these?
image

**Comment by pubby** [comment]
It would be more for flavor than utility. I wouldn't expect them to be detonated much.

**Comment by Tlaltecuhtli** [comment]
bloatware

**Comment by BebeYoshi** [comment]
This is a nice idea, now give assistants a fake insulated gloves that cut your arm off when you equip it!

**Comment by PKPenguin321** [comment]
if it could gib it would be dope

**Comment by Wilchenx** [comment]
if you could make a syndicate bomb disguised as one for more tc that would be awesome

**Comment by SpaceManiac** [comment]
I like the sprite and giving syndie/pirate/etc. ships and bases more fuel. Doubt engineering needs it, the station has dozens of fuel tanks by default.

**Comment by MimicFaux** [comment]
I would say a price reduction is needed. Perhaps 3tc, to make it fairly priced for being obvious/impossible to conceal, and encourage gimmicks.

**Comment by europax** [comment]
Too pricey, and its use is questionable at best. Can't say I like this idea that much.

**Comment by Bawhoppen** [comment]
Doesn't really fit the theme of the uplink, being high-tech elite syndicate equipment.

**Pull request closed without merging**
