### PR TITLE
Minor Virus Symptom Stat Change

### PR DESCRIPTION
**Pull request by TheSilverNuke**
## About The Pull Request

Adjust some symptom stats to allow some combinations of viruses that were previously impossible to be possible, allowing for greater creativity when creating various diseases.

## Why It's Good For The Game

Instead of traitor virologists spamming ARDS, I would like to see some unique combinations that were previously unseen to be made. I adjusted some stats of lethal symptoms, but also adjusted the stats on a couple stat boosting ones, to buff the other side of the spectrum.

## Changelog
:cl:

add: two transmission to choking
add: one stealth to hallucigen
add: one transmission to necro fasciitis 
add: one stage speed to shivering
add: one stage speed to spontaneous combustion
add: one transmission to vomiting
remove: one stage speed from vomiting
remove: two stealth from spontaneous combustion

/:cl:

### CODE REVIEW

**Comment by TheSilverNuke** [comment]
I'm not sure what the return errors are in the code are, that are causing a merge conflict.

**Comment by XDTM** [comment]
as a heads' up, i'm currently doing a full rework of viro (again), making stats not tied to symptoms

**Comment by ExcessiveUseOfCobblestone** [comment]
for changelog entries the format is `tag: message`

**Comment by TheSilverNuke** [comment]
> 
> 
> as a heads' up, i'm currently doing a full rework of viro (again), making stats not tied to symptoms

When do you think that will be finished? That sounds awesome.

**Comment by TheSilverNuke** [comment]
> 
> 
> for changelog entries the format is `tag: message`

which part needs the tag?

**Comment by ExcessiveUseOfCobblestone** [comment]
`add message` >>>> `add: message`

**Comment by TheSilverNuke** [comment]
got it

**Comment by XDTM** [comment]
> 
> 
> > as a heads' up, i'm currently doing a full rework of viro (again), making stats not tied to symptoms
> 
> When do you think that will be finished? That sounds awesome.

Maybe the next week or two, depending on how much time i have to work on it.

**Comment by Dawson1917** [comment]
I thought the reason for spontaneous combustion providing +1 stealth was that the symptom is more powerful the **less** stealth your virus has, by providing more fire stacks. Matters little when all viruses require a stealth of +2 anyway I guess.

**Comment by TheSilverNuke** [comment]
> 
> 
> I thought the reason for spontaneous combustion providing +1 stealth was that the symptom is more powerful the **less** stealth your virus has, by providing more fire stacks. Matters little when all viruses require a stealth of 2 anyway I guess.

Yeah the more powerful your virus is the less stealth it has, so as a result I believe that the spont combust shouldn't have a default +1 but should instead have a -1

**Comment by ATH1909** [comment]
> I thought the reason for spontaneous combustion providing +1 stealth was that the symptom is more powerful the **less** stealth your virus has, by providing more fire stacks. Matters little when all viruses require a stealth of 2 anyway I guess.

That's a rumor, and as far as I can tell, nothing references that in the code.

**Comment by XDTM** [comment]
Used to be like that before thresholds

**Comment by ExcessiveUseOfCobblestone** [comment]
be sure to update wiki so I can also update my powergamer excel :^)

**Comment by TheSilverNuke** [comment]
Done

**Comment by TheSilverNuke** [comment]
done

**Pull request merged**
