### PR TITLE
Fixes Fucked Job Requirement Displays

### PR DESCRIPTION
**Pull request by san7890**
## About The Pull Request

Hey there,

I fucked up in #68856 (5b77361d399ba0dd992e61a16b9bbe38e8aa5a60). We weren't supposed to add another MINUTES multiplication here. I don't even remember why I did this if we are being perfectly honest with each other. Whoops.

## Why It's Good For The Game

image

image

image

:skull: i forgor

## Changelog

:cl:
fix: You should now no longer need thousands of hours to unlock your favorite head of staff role.
/:cl:

### CODE REVIEW

**Review by dragomagol — APPROVED** [review]

**Review by JohnFulpWillard — APPROVED** [review]

**Comment by TheBoondock** [comment]
It truly should require 6300h to be HoS

**Comment by the-orange-cow** [comment]
FEATURE FEATURE FEATURE

**Comment by JohnFulpWillard** [comment]
Marked draft because this isn't the proper fix.

**Comment by san7890** [comment]
no idea why rust_g.dll was being touched so i went ahead and unfucked that portion of this PR

**Pull request merged**
