### PR TITLE
Changes N2O into an extremely powerful oxidizer

### PR DESCRIPTION
**Pull request by as334**
Since N2O acts a powerful oxidizer in fires IRL, I figure it would make sense to port to spessmens. Especially because toxins has needed _something_ new to experiment with, as do atmos techs.
Also cleans up some relative pathing.

INB4 I now get blamed for every issue related to fires.

### CODE REVIEW

**Comment by Anonus** [comment]
N2O flamethrowers OP, pls nerf.

**Comment by Fayrik** [comment]
>powerful oxidizer

So, it won't burn in clean air, but will work in place of oxygen in a plasma fire?
Sounds kinda neat.

**Comment by as334** [comment]
It'll also help boost a fire if both are in there. As a matter of fact it's generally a good idea to include both for best results, as the N2O will burn away quicker than the oxygen.

**Comment by pudl** [comment]
Isn't the best use of N2O that it's good for suppressing fires? If the entire station was full of a gas that works amazing at burning, then everything would suck.
How about we forget realism and instead go for not making life suck.

**Comment by as334** [comment]
You're thinking of N2, N2O is laughing/knockout gas. N2 is a very stable gas that absorbs a lot of heat, that is a major part of the station air supply.

**Comment by GunHog** [comment]
Disagree. Plasma for fire, N20 for knocking people out and clogging atmos. There is no need for TWO fire gasses.

**Comment by as334** [comment]
It doesn't burn on it's own. It functions similar to oxygen, but with slightly different properties. It's a boost to fire, not something that actually burns.

**Comment by xxalpha** [comment]
I am not sure what to think of this. Please explain the mechanics.

**Comment by WJohn** [comment]
Plasma fires are already impossible to stop right now (because their ignition temp is 100 C), I don't think we need another one that is also impossible to stop.

Maybe fix fire burning mechanics (or expand it to shit like wood or carpet that doesn't burn indefinitely).

**Comment by optimumtact** [comment]
Usually plasma fires burn out when they break the tile into space.

You can speed this up by simply deconstructing the floor, it'll put the fire out like blam

**Comment by WJohn** [comment]
Yeah but extinguishers are literally completely useless because ambient temperature rises to the thousands and any lingering plasma is going to re-ignite. I get that plasma fires are meant to be nightmarish to fight but there's no fire that is NOT nightmarish, it's a;ways plasma fire.

**Comment by optimumtact** [comment]
Yeah it's a bit stupid

**Comment by Iamgoofball** [comment]
Buff firefighters

**Comment by duncathan** [comment]
Nanofrost works wonders.

**Comment by fj45** [comment]
Got sprites for more types of extinguishers if anyone needs em.

**Comment by MrStonedOne** [comment]
>Usually plasma fires burn out when they break the tile into space.

Not true, with the way hotspots work, they don't break the tile into space until after they are removed.

They store their highest temperature and have the tile calculate if it melts in the hotspot's Destroy.

Fires tend to burn out from using all the plasma, only sometimes is it from using all the o2 (and that's mainly from canister plasma spreads, as they add a lot more plasma.)

**Comment by optimumtact** [comment]
Thats what I meant, if you vent the area to space all the burnable material gets sucked out

**Comment by Fayrik** [comment]
So, there seems to be a lot of mixed feeling about this pull, all stemming from no one really knowing how atmospherics works.
Let me put it like this:
This is going to have minimal visible effect on any plasma flood that any malf or traitors do.
This is definitely going to make the theoretical perfect burn mix much harder to achieve. This means all those toxins wannabes are gunna be working harder, for longer, and achieving the exact same results. (One of the nicer features of the bomb cap.)
When toxins storage catches fire it will burn out faster, possibly even burning slightly cleaner.
Nanofrost will still be a wonder-extinguisher, that should probably have mini versions available in certain locations.

The biggest thing to note here, is that N2O is an Oxidizer, not a Fuel. This means, when released on the station, it will act exactly as it used to, throwing a lit welding torch at it isn't going to start a plasma fire 2.0, it'll do a whole bunch of nothing.
Personally I'd like to see it go a step further and make it flash when exposed to heat, leaving behind clean N2/O2... But I could imagine that'd be hard to do.

**Comment by Dorsisdwarf** [comment]
Title needs to be updated to stop people who don't understand the PR from soapboxing about NOAH MOAR FIYAH GAS

**Comment by chimersable** [comment]
I remember when I first started playing this game, my grade school science told me N2O would burn. I was quite surprised to find out otherwise when it did'nt seem to burn at all in this game that bragged about it's atmosphere simulation. 

 I endorse the change for consistency but recommended altering the load out toxin storage so that one or two cans of N2O are replaced by N2.

**Comment by as334** [comment]
eh fuck merge conflicts. i'll just remake the PR.

**Pull request closed without merging**
