### PR TITLE
Buff pillow

### PR DESCRIPTION
**Pull request by TheBoondock**
## About The Pull Request
Buff the pillow a little bit so its a little more viable
## Why It's Good For The Game
I think its too weak and a small bump in its force should make it more threatening
## Changelog
:cl:
balance: buff the pillow force unwielded to 10 and wielded to 15 stamina
/:cl:

### CODE REVIEW

**Comment by ExcessiveUseOfCobblestone** [comment]
pillow talk (discussing pillow balance) is not allowed

**Comment by Time-Green** [comment]
Hard no from me. Pillows are for pillow fights, not actual murder weapons. Your "Why is this good for the game" is also sorely lacking, and I strongly disagree pillows should ever be "more threatening" unless you put a brick inside

**Comment by Vect0r2** [comment]
I think it's funny as fuck.

**Comment by LemonInTheDark** [comment]
> ... unless you put a brick inside

Someone add this but it'll be very funny

**Comment by TheVekter** [comment]
> Hard no from me. Pillows are for pillow fights, not actual murder weapons. Your "Why is this good for the game" is also sorely lacking, and I strongly disagree pillows should ever be "more threatening" unless you put a brick inside

I was gonna say, how hard would it be to make it so you can put bricks/oranges/some other hard object in them?

**Comment by EricZilla** [comment]
Traditionally you add SOAP to pillowcases not bricks

**Comment by TheVekter** [comment]
> Traditionally you add SOAP to pillowcases not bricks

Oranges where I'm from. Butter if you grew up in the 2000s. Wait, those were socks. Butter socks.

**Pull request closed without merging**
