### PR TITLE
Adds "helpies!" to the list of brain damage lines

### PR DESCRIPTION
**Pull request by FrostyFridge**
[Changelogs]: # (Your PR should contain a detailed changelog of notable changes, titled and categorized appropriately. This includes, new features, sprites, sounds, balance changes, admin tools, map edits, removals, big refactors, config changes, hosting changes and important fixes. An example changelog has been provided below for you to edit. If you need additional help, read https://github.com/tgstation/tgstation/wiki/Changelogs)

:cl: Frosty Fridge
add: Brain-damaged people have a new line.
/:cl:

[why]: # (Please add a short description [two lines down] of why you think these changes would benefit the game. If you can't justify it in words, it might not be worth adding.)
helpies!

### CODE REVIEW

**Review by ShizCalev — APPROVED** [review]

**Comment by optimumtact** [comment]
god no

**Comment by Anonymous583** [comment]
reopen this it's a good pr

**Comment by FrostyFridge** [comment]
disrespecting the 24 hour rule for a high quality pr smh when will this tyrannical reign of maintainers end?

**Comment by optimumtact** [comment]
it will never end

**Comment by Ziiro** [comment]
reopen this instant

**Pull request closed without merging**
