### PR TITLE
Readds Cerestation and Omegastation

### PR DESCRIPTION
**Pull request by FloranOtten**
## About The Pull Request
I needed to get Omegastation and Cerestation readded. Why not kill two birds with one stone?

## Why It's Good For The Game
It's omegastation, does it need explanation?

## Changelog
:cl:
adds: Adds Omegastation and Cerestation back into the code
/:cl:

(Will PR the actual remade Cerestation once I finish it.)

### CODE REVIEW

**Comment by FloranOtten** [comment]
Joke falls flat considering map diff bot isn't around. Just a second

**Comment by MMMiracles** [comment]
image

**Comment by tralezab** [comment]
I get the joke but I do miss that funny meteor bridge map

**Comment by FloranOtten** [comment]
https://imgur.com/2yjZJV4

**Comment by GunHog** [comment]
I do hope we do get the real CereStation back one day, it was my favorite of the maps.

**Comment by 81Denton** [comment]
>_maps/map_files/OmegaStation/Cerestation.dmm

**Comment by FloranOtten** [comment]
Quiet, you!

**Comment by Teepeepee** [comment]
CERES BACK FROM THE GRAVE?
IS IT CHRISTMAS ALREADY?

**Comment by FloranOtten** [comment]
> CERES BACK FROM THE GRAVE?
> IS IT CHRISTMAS ALREADY?

Whose gonna tell him

**Comment by ArcaneMusic** [comment]
_S P E E D M E R G E_

**Comment by optimumtact** [comment]
absolutely not willing to accept more maps on top of the existing set.

**Comment by subject217** [comment]
LOL

**Comment by kevinz000** [comment]
Btfo

**Comment by Rowelll** [comment]
aww

**Comment by subject217** [comment]
Remove donut and readd cerestation

**Pull request closed without merging**
