### PR TITLE
removes amy + jon graffiti

### PR DESCRIPTION
**Pull request by ghost**
holy lel how did this remain in the game so long

### CODE REVIEW

**Comment by WJohn** [comment]
:-1: x :100: 
cmon man
leave the ancient player references in

**Comment by paprka** [comment]
this isn't a creative player reference it's a dude having a boner for his erp partner and their epic IC relationship but i don't expect you to understand the difference

**Comment by TZK13** [comment]
From what I can gather it wasn't added by either of the people that played as Amy or Jon though, it was added by Urist [here](https://code.google.com/p/tgstation13/source/detail?r=1594) along with most of the other graffiti that exists now.

**Comment by Steelpoint** [comment]
Stop obsessing over things that no one but you cares about.

**Comment by paprka** [comment]
Then why have it in the game

This isn't even me obsessing, it's me trimming the fat of stupid shit out of our game, what is the issue?

**Comment by WJohn** [comment]
I'm sure someone is going to be an *irredeemable retard* now that you've mentioned "trimming the fat" and then blowing it way the hell out of proportion in some big conspiracy with you slowly but surely trimming out the entire game.

**Comment by TZK13** [comment]
Love graffiti is a common trope, a replacement that doesn't reference specific players would be better than just removing it completely.

**Comment by paprka** [comment]
i should mention that it was you who threw a hissyfit about this in the first place wj, you're really not helping or distancing yourself from that crowd

**Comment by RemieRichards** [comment]
WJ didn't have a hissy fit, he simply said no to this PR.

On topic, There's no reason to remove this beyond your own personal preference, the only sort of rule we have against player references doesn't even make this PR valid. (No new player references but old ones can remain)

As Steelpoint brings up this reference is so old it's barely even a reference any more.
It hurts nobody.

So from me :-1:

**Comment by paprka** [comment]
I don't really care about the rules, I never said this broke rules, I just said it was stupid and useless bloat, especially since we can expand the graffiti now that drawing them is easier.

**Comment by xxalpha** [comment]
Why does this bother you? It's so vague and old that it doesn't matter that it is supposed to be a reference.

**Comment by Dorsisdwarf** [comment]
I have never known that this was a reference. It's effectively just generic loveheart graffiti now. Is there a point to this? Seems like a waste of time.

**Comment by Cheridan** [comment]
actual tgstation culture

**Comment by Miauw62** [comment]
its literally just love grafitti between two random names that nobody knows.

**Pull request closed without merging**
