### PR TITLE
Deepstorage Ruin Revamp

### PR DESCRIPTION
**Pull request by MMMiracles**
:cl: MMMiracles
tweak: Deepstorage ruin has been redone to be more self-sufficient and up to better mapping standards.
/:cl:

[why]: Current one looks pretty 'meh' and isn't all that self-sufficient for a survivalist bunker.

deepstorage
ignore rogue dresser i dont feel like updating the picture

**Includes**
- Functional powernet/atmospherics
- RTG room for non-magical power generation.
- Fully-fitted Hydroponics and Kitchen
- Mini-dorms
- Basic fire safety (extinguishers, some fire alarms/airlocks)
- Entrance airlock section with canister port for gassing unwanted visitors
- Recycle room with a crusher (set to crush people by default for more fun)
- High-security doors that require a bunker-access ID, which can be obtained from one of the dorm rooms after breaking in.

The actual loot from the storage areas is pretty much the same, except with the addition of some vending restocking units. Also includes a GPS so people can actually find it during a round once in a blue moon instead of never like most current ruins.

### CODE REVIEW

**Comment by FantasticFwoosh** [comment]
It shouldn't be a white ship V2 hideout, the point of it being a ruin is how you are going to DIY IMPROVE IT not tack it on to be totally fine in the first place.

**Comment by MMMiracles** [comment]
Sounds like you're asking for a pretty shitty survivalist bunker, then.

**Comment by WJohn** [comment]
ignore fwoosh, this is miles better.

**Comment by Repukan** [comment]
Remove GPS

**Comment by MMMiracles** [comment]
Majority of space ruins with any worth-while content has a GPS. Until space exploration becomes less ass, I see no reason to further hinder any chances of actually finding the place.

**Comment by Repukan** [comment]
It is less ass though, you can use jetpacks more effectively and cross two z levels or majorly explore one before needing to refill.

This is just going to get abused as a cult base. It even has guns for the taking.

**Comment by MMMiracles** [comment]
Sounds better than 'never being used at all'.

**Comment by Armhulen** [comment]
>cult base
>ratvar has extremely nerfed production while here
>i think nar nar can only rune on station zlevel

**Comment by FantasticFwoosh** [comment]
I draw my arguement that like the abandoned teleporter satellite, there is no reason why you can't just construct your own base out of the original design. 

A ready made bunker base is no fun, least not as fun as fixing a broken setup or bringing your own materials to make it operational. A CM approach of applying tool & equipment steps to restore a power generator & vital bits of equipment by pre-smashing the APC's etc would go much futher into making this not just a cultbase in a can.

> Remember its in deep space, all you need its a telepad from RnD to go there.

**Comment by MMMiracles** [comment]
Nah.

**Comment by Tacolizard** [comment]
>ignore fwoosh, no matter what he says

FTFY

**Comment by Bawhoppen** [comment]
Not everything has to just be another generic station-esque base with all kinds of different rooms and has no creativity.

When I made the original, I wanted it to be a simple bleak basic survival bunker that was dark and depressing, rather than some fancy high tech facility that takes away flavour because it's the exact same as station mapping style.

Also the argument something is never used is literally not an argument under any circumstances unless that thing causes some kind of extra coder or performance burden. (Also it is used just as much arguably as any other ruin so I don't even get why you'd say that)

**Comment by Supermichael777** [comment]
a fully functional mini station

**Comment by Penguaro** [comment]
We should just make it another map for low-pop.

**Comment by FantasticFwoosh** [comment]
Your proposed changes are to powercreep it into pretty much a Nox trader base minus the No2 atmos, all you have to do to claim this base is just break in and take the keys from under the door-mat because @MMMiracles has powercrept the ruin into a mini self sufficient station.

> Actually that'd be a better use for it.

Its not even a technical puzzle challenge like the abandoned teleporter OR EVEN the derelict, its lazy and premade.

**Comment by Bawhoppen** [comment]
fwoosh you're not helping our cause here

**Comment by FantasticFwoosh** [comment]
Cause being making readymade lazy bases in dead featureless space where literally only antags are going to hang out because the white ship is better.

**Comment by MMMiracles** [comment]
@FantasticFwoosh see the above "Nah."

@Bawhoppen supposed survivalist bunker without the bare minimal for actually living isn't a very good survivalist bunker. Having one fully functional ruin out of the dozen+ broken/empty ruins isn't doing anything wrong.

**Comment by Bawhoppen** [comment]
But the problem is this one doesn't do anything different, and instead falls back to the formula of just use station-based mapping/assets

**Comment by FantasticFwoosh** [comment]
Its a empty survivalist bunker, nobody lives there anymore, why does it look brand new.

**Comment by Penguaro** [comment]
By its very name, this isn't a 'ruin' in any sort. It's basically like one shift checked out and the next never showed up to work. It's pristine.

**Comment by Penguaro** [comment]
What Fwoosh just said

**Comment by Bawhoppen** [comment]
What I'm saying is, there is no creativity to it. On my original atleast I tried to do some interesting things such as having those blast doors with a viewing screen for entrance, a backroom full of boxes, a unique hydroponics area, this just lacks that

**Comment by Penguaro** [comment]
Blow a hole or two in it... Make it missing something vital. It would never have been abandoned if people could remain.

**Comment by Penguaro** [comment]
Oh OH! Fill it with Zombies!

**Comment by FantasticFwoosh** [comment]
Exactly my previous point, also it validates space explorers bringing tools penguaro. Readymade bases are stupid, it should atleast have a CM engineer role like challenge to use tools to repair a power generator, or rewire the floors.

I mention CM because often the buildings on those maps are completely shot shitholes littered with boxes & barricades, sort of what you expect from lived in but now derlicted areas.

**Comment by MMMiracles** [comment]
Let me just clarify this one more time, considering it apparently didn't get through the first time.

Nah.

**Comment by FantasticFwoosh** [comment]
I retort, nah you're wrong.

**Comment by Penguaro** [comment]
I vote No to its current state for whatever that is worth to the maintainers.

**Comment by MMMiracles** [comment]
WJohn already seems to prefer it vastly over the current ruin, so.

**Comment by Bawhoppen** [comment]
Don't make this mistake of not listening to feedback

**Comment by MMMiracles** [comment]
I didn't realize I was getting actual feedback.

**Comment by octareenroon91** [comment]
Seriously though, this is an entirely different ruin

**Comment by Repukan** [comment]
Shit merge

**Comment by RandomMarine** [comment]
@MMMiracles 
The SMESes are set up backwards. You have their output wired to the RTGs with the input terminals hooked to the grid.

**Comment by FantasticFwoosh** [comment]
Why did you set up a GPS co-ordinate here, people are rushing it for free security rifles and self sufficient space base simply using a hand teleporter.

**Pull request merged**
