### PR TITLE
Stops emitters from notifying admins every time they turn off

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**

### CODE REVIEW

**Comment by tkdrg** [comment]
you forgot to mention that this way they just won't bother admins AT ALL
how about like, checking if it was the first time it was turned off, and message only in that case

**Comment by Aranclanos** [comment]
its too spammy because there's a bug, the message is displayed when a cable is cut. The real fix is on the logic behind that. 
:-1:

**Comment by Jordie0608** [comment]
Emitters oft randomly turn off due to powernet magic; messaging only the first time wouldn't be useful and while this is annoying, removing this entirely isn't a good solution.

**Comment by KorPhaeron** [comment]
>removing this entirely isn't a good solution.

It isn't removed entirely, it's still logged to the singularity investigate button, and we still get a notice when containment fails.

I've literally never seen an admin stop the singularity escaping by listening to emitter warnings.

**Comment by Jordie0608** [comment]
I mean removing message_admins()

**Comment by optimumtact** [comment]
yeah I don’t' know what the purpose of this is

**Comment by Shadowlight213** [comment]
It's a bandaid fix really.

**Comment by optimumtact** [comment]
how is it a bandaid fix? The admins don't need to know when emitters are turning off, they only care when the power in the singularity containment goes below say 50%

**Comment by Shadowlight213** [comment]
@optimumtact I thought it was a fix for emitters sending false alarm messages. It's labeled as a fix anyways. Except said fix simply removes the visible problem rather than fix the underlying powernet issue.
Your idea is good though, sending a message when the containment power gets low. That would be a better change than simply removing it.

**Comment by MrStonedOne** [comment]
the underlying powernet issue can't be easily fixed.

How about making them spawn() the message, but check the power level after the spawn. say spawn(50)

**Comment by KorPhaeron** [comment]
>I thought it was a fix for emitters sending false alarm messages

No I just don't care about the message in any scenario, because we get a separate warning for the singulo getting out anyway

**Comment by tkdrg** [comment]
I thought about this for a little and yeah I kind of agree with kor, I find myself ignoring the emitter messages almost always.

**Comment by Aranclanos** [comment]
people ignore the emitter message because its bugged, what's so difficult to understand?
If it worked like intended, it would prevent the singulo from escaping on scenarios where admin intervention is needed

**Comment by Jalleo** [comment]
Folix on IRC is redoing powernet code from the bottom up and will probably have a PR in feburary which hopefully will have a fix for this. 
Another way to fix this is just give emmiters a basic battery to drain from and have the powernet fill that up instead.

**Comment by Aranclanos** [comment]
>folix
lmfao

**Comment by Shadowlight213** [comment]
@jalleo that would work well. Having a sort of buffer for power would help keep power steady even during powernet resets.

**Comment by Aranclanos** [comment]
you cant remove my checks reee

**Pull request closed without merging**
