### PR TITLE
High Gravity - First Draft

### PR DESCRIPTION
**Pull request by AnturK**
:cl:
code: Gravity can now go above 1g
/:cl:

Makes gravity scalar.
Adds forced gravity component.
Adds grav anomaly variation that messes with gravity around it.

High gravity:
- Slows you down
- Slows picking up items horribly
- Deals minor brute damage

Would be nice to have some visual representation of high gravity besides the alert but really not sure what it should look like.

### CODE REVIEW

**Comment by davethwave** [comment]
A few questions, how would you activate High gravity, and how much damage does it do per lets say 5 seconds

**Comment by AnturK** [comment]
Right now it' s admin abuse or mapping only.
It scales depending on the actual value but minimum is 1 brute maximum 3 per life tick (these are just first values, absolutely not balanced)

**Comment by JJRcop** [comment]
A visual for high gravity could be the floors subtly getting a little dustier

**Comment by GunHog** [comment]
Or make things look wavy/distorted, if that is something we can do with BYOND.

**Comment by ExcessiveUseOfCobblestone** [comment]
@GunHog we currently have skewium causing crashes/lockups so prob not very enticing atm although it's an otherwise nice idea.

**Comment by MrDoomBringer** [comment]
should make objects's throw range shorter

**Comment by nicbn** [comment]
Gibbing gravity when?

**Comment by KomradeSpectre** [comment]
If you ever do gibbing gravity, have it be a mechanism that can be disarmed on a long timer or something.

**Comment by davethwave** [comment]
Honestly the grav gen should have a constant high gravity zone around it constantly while it's on.

**Comment by AnonymousNow** [comment]
Can we get Kev's directional gravity back, too?

**Comment by kevinz000** [comment]
@AnonymousNow i can try to have directional gravity back in the future but it's practically infeasible with the memory cost.
my implementation heavily relies on using memory as opposed to cpu when doing it and we only have 2GB of memory and so much cpu to be wasting.
if you have a good feature to use dir grav on it'd be nice but otherwise don't expect it anytime soon until someone has a good reason to be using it

directional gravity also supported gravity amounts/high grav btw

**Comment by Iatots** [comment]
walking/running sound please

**Comment by KorPhaeron** [comment]
Not sure on the damage, would basically just kill anyone without a space suit to leave the station and make it so we could never have this player accessible

**Comment by JJRcop** [comment]
Maybe the brute damage should only be up to a certain limit, and that limit increases with the gravity

**Comment by davethwave** [comment]
The best way toward activating the high gravity mode is either a random event that activates it making it require a person to turn it off and on again. Or make it activatable via circuits and emag. BUT it would sap up power like crazy, disabling itself after a short while due to the APC not going fast enough.

**Comment by Jalleo** [comment]
doesnt the gravity gen take power from a wire instead of a APC?

**Comment by zamolxius** [comment]
make people get more squat in high gravity

**Comment by Ratvar** [comment]
Make it damage mobs as well? High gravity to kill all cockroarches

**Pull request merged**
