### PR TITLE
SimpleMed 2.0: prove it's better edition

### PR DESCRIPTION
**Pull request by Iamgoofball**
You guys have told me that making medbay self serve 100% is a better med system than my work on a med system. We're going to have a test merge of this, and we're gonna see if you were right by live fire testinng it.

dreammaker_2016-05-07_13-47-19

### CODE REVIEW

**Comment by Shapsy** [comment]
First for memes

**Comment by Supermichael777** [comment]
needs a defib on a cord

**Comment by phil235** [comment]
Stop this, goof.

**Comment by Iamgoofball** [comment]
whats wrong with this PR, I'm doing what people have said to do

**Comment by ike709** [comment]
420/69 doing god's work :+1: :+1: :+1:

**Pull request closed without merging**
