### PR TITLE
Ports oracle's dirt sprites

### PR DESCRIPTION
**Pull request by nicbn**
[Changelogs]: #

:cl:
imageadd: Dirt is smooth (by AndrewMontagne)
/:cl:

image

Stolen from https://github.com/OracleStation/OracleStation/pull/240

### CODE REVIEW

**Comment by WJohn** [comment]
smoothing DECALS? is that possible?

very cool, though! will definitely need wood/reinforced floor/other variations in time, however.

**Comment by Dorsisdwarf** [comment]
yeah was just gonna say that this will look _horrible_ on any floor which isnt 4x4 tiles

**Comment by WJohn** [comment]
this should probably be a subtype in the meantime so that it doesn't ruin the aesthetic we're using on a lot of ruins where the current dirt sprite is sprinkled everywhere.

**Comment by nicbn** [comment]
I tweaked the sprites themselves a little bit in the latest commit

**Comment by nicbn** [comment]
uh one moment something is wrong

**Comment by nicbn** [comment]
@WJohn it now displays old dirt if it's not a tiled floor.

**Comment by Bawhoppen** [comment]
Loving all these sprite improvements

**Review by SpaceManiac — APPROVED** [review]

**Pull request merged**
