### PR TITLE
Fix inconsistencies in Tram atmospherics

### PR DESCRIPTION
**Pull request by strandsofivy**
## About The Pull Request

Something to do with #68665 idk

Pipes leading to the portable air scrubbers/vents weren't hidden under tiles, also there were two Layer3 pipes just hovering around in engineering with no purpose

Edit: misplaced lights and requests console hepl

## Why It's Good For The Game

looked weird imo

## Changelog

:cl:
fix: Fixed some odd pipes menacingly laying around above tiles in Tramstation engineering.
fix: Fixed misplaced requests console and light fixture.
/:cl:

### CODE REVIEW

**Comment by vincentiusvin** [comment]
4/5 maps have visible port pipes. Might be worth it to keep this one consistent with the majority. Also helps newer people figure out the lines better, form over function yada yada.
Thanks for patching the engi one.

**Comment by distributivgesetz** [comment]
> Also helps newer people figure out the lines better, function over form yada yada.

I was thinking if I should keep the pipes right before the scrubbers and such visible, mainly wanted to hide the pipes in atmospherics lobby under tiles because it felt weird seeing them above the floor.

**Comment by vincentiusvin** [comment]
Yeah its not a big deal either way. Just figured it worth mentioning.

**Review by san7890 — APPROVED** [review]
No idea how I missed some of these, thank you!

**Pull request merged**
