### PR TITLE
:b: emoji

### PR DESCRIPTION
**Pull request by Ghommie**
## About The Pull Request
An emoji from elsewhere.

## Why It's Good For The Game
This is a slightly memetic PR, but at times the game is just so :b:orked you might want to use it.

## Changelog
:cl:
add: :b: emoji.
/:cl:

### CODE REVIEW

**Comment by trollbreeder** [comment]
b

**Comment by mrhugo13** [comment]
b

**Comment by HomocidlePancakes** [comment]
Can you add a :cringe: emoji while you are at it?

**Comment by spessbandit** [comment]
don't start this meme again

**Comment by trollbreeder** [comment]
image

**Comment by SpinnerMaster** [comment]
🅱️anned

**Comment by ArcaneMusic** [comment]
🅱️ ased and 🅱️ pilled.

**Comment by spessbandit** [comment]
in all seriousness this is a slippery slope to adding the other letter emojis and then we killed the entire point of the mime pda

**Comment by wesoda25** [comment]
never thought I'd see the "slippery slope" argument used on an emoji, wow

**Review by SpaceManiac — APPROVED** [review]

**Comment by trollbreeder** [comment]
Do you think god stays in heaven because he, too, lives in fear of what he has created?

**Pull request merged**
