### PR TITLE
Replaces var-edited high capacity power cells with normal ones

### PR DESCRIPTION
**Pull request by RandomGamer123**
## About The Pull Request
#65179 but instead of one in EVA its one in engineering.

## Why It's Good For The Game
#64900 was supposed to fix the power cell inconsistencies, but they missed some vareditted ones it seems.

## Changelog

:cl:
fix: The 0.7% charge high capacity power cell (which actually also stored 50% more charge than a regular high capacity power cell, didn't notice that right?) in Metastation engineering has been replaced with a regular high capacity power cell.
/:cl:

### CODE REVIEW

**Comment by cacogen** [comment]
there are fifteen var-edited cells on metastation alone, based on a quick search

**Review by ShizCalev — CHANGES_REQUESTED** [review]
image

**Comment by RandomGamer123** [comment]
Right so uh map merger did https://github.com/tgstation/tgstation/commit/2e52513742ab8e9df1b747d7f81c6129e0ad18b7

**Comment by RandomGamer123** [comment]
That did not work as intended at all

**Comment by RandomGamer123** [comment]
Ok maps merged finally, now actually ready for review.

**Pull request merged**
