### PR TITLE
New carpets & wood, version 2

### PR DESCRIPTION
**Pull request by maxymax13**
## About The Pull Request
I really wanted #58190 but then nobody gave it mergies so i've redone it except not stale, not merge conflict'd and not using stack crafting instead of tile floofing!
I fully replaced the fugly diagonal one with my own nicer parquet one, adjusted red carpet to be less noisy, and made a damaged state.

image
red arcade carpet, reskinnable from black arcade carpet

image
parquet wood (**MUCH** better used for 1 tile wide highlights than filling a room like this)

dreamseeker_NBUc0fLRZf
chunkier wood

dreamseeker_dQVcFPSo17
tiled wood

dreamseeker_8sqSqETC10
le radial

Closes #58190.

## Why It's Good For The Game
Much more customization for wood flooring enjoyers, and it's obtainable ingame, in an out-of-the-way method! Think of the bar remodels you could do with this and some cans of paint! Now all we need is to make the vinyl siding and wood panel siding decals place-able...

## Changelog
:cl: maxymax13, /vg/station, Citadel Station
imageadd: 3 new variations for wooden tiles are available (large, parquet, and tiled), the same way you color titanium tiles! Remember, use a screwdriver and not a crowbar!
imageadd: A new red planetary pattern design is available for arcade carpet!
/:cl:

### CODE REVIEW

**Comment by Fikou** [comment]
can you make the red tiles use tile reskinning system for regular arcade carpets?

**Comment by maxymax13** [comment]
sure, i asked twaticus and he said it was cool

**Review by Twaticus — APPROVED** [review]

**Comment by maxymax13** [comment]
WHER MY MERGIES????¿¿¿

**Comment by SmArtKar** [comment]
Yay!

**Comment by maxymax13** [comment]
helo?? where my merg??? mantaner pleas e???????

**Comment by LemonInTheDark** [comment]
Let's dance

**Pull request merged**
