### PR TITLE
fixes people with no skin/golems dropping skin when gibbed

### PR DESCRIPTION
**Pull request by Militaires**
:cl: basilman
fix: fixed species with no skin dropping skin when gibbed.
/:cl:

### CODE REVIEW

**Comment by Militaires** [comment]
and i'd do it.

all again.

**Comment by PKPenguin321** [comment]
hmm

**Comment by factoryman942** [comment]
mmmmmmmmm

**Comment by Repukan** [comment]
Mmmmmmmmmmmmm

**Pull request merged**
