### PR TITLE
Removes the shotgun nerf

### PR DESCRIPTION
**Pull request by UncleBourbon**
Reverts #24633

Shotguns are completely useless with the nerf, rubber shots just vanishing after 4 tiles, taking 3 buckshots to even crit a guy in a lab coat (at like point blank range i might add). This is a shitty nerf that makes a very interesting weapon into just a pile of trash, so fuck this nerf.

### CODE REVIEW

**Comment by kevinz000** [comment]
one of these days were making nt energy only fuck ballistics syndicucjs use those
Don't mind my typing I'm o na phone

**Comment by Hatterhat** [comment]
@kevinz000 ur dumb

**Comment by KorPhaeron** [comment]
Then tweak the falloff, we don't need shotguns to murder anyone onscreen instantly again

**Comment by UncleBourbon** [comment]
this is the man who wants your child to use dangerous energy weapons to replace harmless nerf darts for your children.

**Comment by Pascal125** [comment]
The best thing since fried butter merge immediately 10/10

sorry i'm on mobile

**Comment by Hatterhat** [comment]
the Syndicate did nothing wrong

**Comment by Hatterhat** [comment]
|  ||
|| |_

**Comment by kevinz000** [comment]
I'm going to do you wrong you grey shit

**Comment by Hatterhat** [comment]
@kevinz000 do it nerd

**Comment by UncleBourbon** [comment]
lmao if you get hit by the full spread of buckshot on the other side of the screen then i'm impressed how you managed to eat more pellets than pac man

**Comment by Pascal125** [comment]
Guys i just vomited my guts out holy shit. call an ambulance

**Comment by kevinz000** [comment]
i was going to meme on bourbon but I won't for the next few mins because I laughed.mt ass off at that line 10/10

**Comment by Hatterhat** [comment]
nice one boys

**Comment by kevinz000** [comment]
@hatter im going to pin you tot the fucking science testing target for all the scientists to test my new guns ln

**Comment by Hatterhat** [comment]
you fucking missed @kevinz000

**Comment by Cyberboss** [comment]
blah blah censosrship

**Comment by optimumtact** [comment]
We're not interested in rebuffing shotguns, get closer

**Pull request closed without merging**
