### PR TITLE
Reduces the amount of time required for bone wounds to heal (buffs Bonegel)

### PR DESCRIPTION
**Pull request by DaydreamIQ**
## About The Pull Request
Bone Gel (And Tape) will now take 2 minutes for hairline fractures (Down from 4) and 4 minutes for compound fractures (Down from 8)
## Why It's Good For The Game
Bone gel has a hard time justifying its existence. On one hand its the only means of self treating bone wounds that aren't disolcations. But on the other you can just go to medbay and get it done in literally ten seconds if the doctor knows what they're doing.

Other than the fact that you need bone gel anyways to treat compound fractures for the surgery there isn't much of an incentive for paramedics to ever bother using the ones they spawn with because the time it'd take to bring their patient to medbay and treat them would still be faster by all accounts. So by halving the amount of ticks required to repair this should maybe make more paramedics or antags in dire need of a ghetto alternative even if surgery is always going to be the quickest option.
## Changelog
:cl:
balance: Hairline and Compound fractures now take half as long to treat with bone gel and tape
/:cl:

### CODE REVIEW

**Comment by Pickle-Coding** [comment]
I think the point is you should just go to medbay instead of carrying the entirety of medbay, the armoury and engineering in your bag.

**Comment by ExcessiveUseOfCobblestone** [comment]
It's important to remember wounds are for DOCTORS. Paramedics providing you goober juice that takes eons because you won't see a doctor is meh but the two shouldn't be comparable. Going to the doctor should always be the better option, and this option should only be good when you can't go to the doctor.

**Comment by Ryll-Ryll** [comment]
I feel like hairline fracture should take 3 minutes instead of 2 but otherwise sure

**Comment by DaydreamIQ** [comment]
> I feel like hairline fracture should take 3 minutes instead of 2 but otherwise sure

Yeah that's fair, I'll tweak that real quick

**Comment by Time-Green** [comment]
I don't particularly like this. Compound fracture is a severe wound you're supposed to get fixed at med, not self-treatment. Bonegel is a means of self-healing these bone wounds, bypassing the whole medbay system. I think it's strong enough for what it is, and a fair compromise for not having to go to med

**Pull request closed without merging**
