### PR TITLE
NanoUIzed Solar Control Computers

### PR DESCRIPTION
**Pull request by Menshin**
**Note :** _it has been reported out inability to use NanoUI, at least on /vg.
i don't know if we encounter the same problem..._

Because, hey _Solars_ may be the first thing i reworked on /tg :
nano_solars
- Converted solar control computers interfaces to NanoUI
- Removed some now unused code

### CODE REVIEW

**Comment by GunHog** [comment]
MORE NANOUI PL0X

**Comment by Miauw62** [comment]
:+1:, now do air alarms :^]

**Comment by Deantwo** [comment]
Awesomeness! :+1:

**Comment by ike709** [comment]
NanoUI all the things!

**Comment by Deantwo** [comment]
I'd say only things actually have a constantly updating UI really need NanoUI.

**Comment by optimumtact** [comment]
The advantage of having nanoui on everything is that we only have one place to improve things, rather than two, or in teh case of old ui's - everywhere.

**Comment by Deantwo** [comment]
Ok good point.
Have one UI standard rather than two.

**Comment by pudl** [comment]
nanoui is awful, stop putting it everywhere so we can remove it more easily

**Comment by paprka** [comment]
said nobody ever

**Pull request merged**
