### PR TITLE
Adds more brain damage lines

### PR DESCRIPTION
**Pull request by ghost**
SUPEMAYTTER IS BEST ENGINE GUYZZZ

I used an online json formatter, so sorry if the format is off

### CODE REVIEW

**Comment by nicbn** [comment]
Stahp.

**Comment by Ratvar** [comment]
> addd moorr bayrendamagek limezss

**Review by Cyberboss — CHANGES_REQUESTED** [review]
Only touch the lines you modified

**Comment by Cyberboss** [comment]
Also, this doesn't warrant a changelog

**Comment by dannno** [comment]
"adds more brain damage lines" PRs are really starting to get annoying
we don't need these

**Comment by MoreRobustThanYou** [comment]
@Cyberboss what json formatter is used for this

**Comment by Cyberboss** [comment]
No idea, just use spaces to add the line you want to the original

**Comment by MoreRobustThanYou** [comment]
everybody hates this so i'm closing it

**Pull request closed without merging**
