### PR TITLE
Claymore Resprite: Take Two

### PR DESCRIPTION
**Pull request by necromanceranne**
## About The Pull Request

They're kind of all over the place ingame so I felt it was about time they got an update.

**Edit:** I've used Kyrsonism's sprites he's provided for me. He made a few variants too which I might think about using for some different stuff. 

Swords are cool.

74227271-662ddb80-4cbe-11ea-8330-2789aa93f43a
74227261-61692780-4cbe-11ea-8353-dcbd1b7137af

## Why It's Good For The Game

I have no idea how old this sprite was but it must have been pretty old.

## Changelog
:cl: NecromancerAnne and Kyrsonism
imageadd: Redid the claymore sprites to look a little better.
/:cl:

### CODE REVIEW

**Comment by necromanceranne** [comment]
I did it!

**Comment by optimumtact** [comment]
did it change the ingame sprite? 

pictures of a sprite out of game aren't particularly useful in evaluating what something will actually look like.

**Comment by Krysonism** [comment]
> pictures of a sprite out of game aren't particularly useful in evaluating what something will actually look like.

Especially on a pure white background since a lot of surfaces are quite a bit darker.

**Comment by Bawhoppen** [comment]
If giving some feedback is alright, I think it's too silky looking and needs more some texture to it

**Comment by necromanceranne** [comment]
Screenshot 2020-02-10 13 39 00

How's that?

**Comment by necromanceranne** [comment]
I made the quillions more thicc though have lost much of the curse as a result. Ah well, we're not aiming for historical accuracy anyway. Also added more gradiant.
Screenshot 2020-02-10 17 15 43

**Comment by Bawhoppen** [comment]
in my opinion, it should be less uniform in its texture... some variety is fine and won't necessarily make it look dull or impure
if I remember, the original claymore sprite kinda did an alright job at this with the blade

**Comment by Bawhoppen** [comment]
but it's pretty good don't get me wrong

**Comment by cacogen** [comment]
I think it needs an outline

**Comment by Krysonism** [comment]
claymore_ann_myway_x19

Here is my take on it.

**Comment by cacogen** [comment]
Krysonism's in-game

**Comment by Krysonism** [comment]
> Krysonism's in-game
> 

If you want it to look even better in hand i might need to make the dark edge even darker, since it blends together a bit with the dark blue background.  If I make it too dark however it might not look good on plating.

**Comment by cacogen** [comment]
depends on what HUD you're using I guess

**Comment by Tlaltecuhtli** [comment]
banana guard

**Comment by Krysonism** [comment]
claymore_ann_myway2 1
claymore_ann_myway2 2

**Comment by Bawhoppen** [comment]
@necromanceranne upon reflection, I think what you need to do is make the gradient difference more significant on your most previous version

the shading and texture of the blade itself is probably the most important part of the whole sprite

**Comment by necromanceranne** [comment]
I've added Kyrson's most recent contribution to the PR, and separated the standard and holy claymore between the undecorated and golden versions respectively. A whole big thanks to Kyrson, he's been a big help for someone who didn't have to go to the lengths he did.

**Comment by ShizCalev** [comment]
Trying to bind a blade with those quillons I see.

**Pull request merged**
