### PR TITLE
 [WIP] (Hopefully)Fixes some edge cases of destructive items not being logged.

### PR DESCRIPTION
**Pull request by silicons**
Someone ruined my extended round with explosive cigarettes.
Never fucking again.
Anyways, would be great if I was pointed to other items that really should be logged.
Todo list:
Cigarettes
Vapes 
Gravity guns (These are hilariously lethal/destructive used on the emergency shuttle) -Already logged but probably make an admin message when the projectile impacts the shuttle and sends shit flying around.

### CODE REVIEW

**Comment by TehZombehz** [comment]
There's an entire art around figuring out how to get around logging and griff at this simple and fun 2d spessmans game, apparently. This is why we can't have nice things. The time spent griffing this autism game could be time spent curing cancer, but what have you. ;)

**Comment by kevinz000** [comment]
spending more time then the griefer to patch the things used to grief rip

**Comment by TechnoAlchemisto** [comment]
It's called a prank, and it's art.

**Comment by kevinz000** [comment]
too fucking lazy and edge cases

**Pull request closed without merging**
