### PR TITLE
moved the goddamn locker in toxins maint

### PR DESCRIPTION
**Pull request by Qbopper**
:cl: Qbopper
tweak: Moved a locker blocking an airlock in Toxins maintenance.
/:cl:

this FUCKING locker has been pissing me off for months

it's in the tile between the shelf and airlock despite a perfectly fine tile being RIGHT THERE

so I moved it

fug

### CODE REVIEW

**Comment by Onule** [comment]
ABOUT TIME

**Comment by optimumtact** [comment]
fuck you qbopper

**Comment by Qbopper** [comment]
ok thanks

**Comment by Qbopper** [comment]
FUCK YES

**Pull request merged**
