### PR TITLE
removes rogue e from items.dm

### PR DESCRIPTION
**Pull request by Mothblocks**
## About The Pull Request
e

### CODE REVIEW

**Comment by Timberpoes** [comment]
e

**Review by Timberpoes — APPROVED** [review]

**Comment by maxymax13** [comment]
on one hand: how the fuck did i miss that

on the other hand: e

**Comment by Mothblocks** [comment]
to be fair i'm surprised the linter didn't pick it up. it saw it last time as a relative type path, but not by the time of merge

**Comment by ATH1909** [comment]
e

**Comment by ATH1909** [comment]
image
image

**Comment by interestingusernam3** [comment]
How tf do versions of the code without this patch even compile?

**Comment by maxymax13** [comment]
it just creates a datum named e and then keeps going apparently

**Comment by Mothblocks** [comment]
Yeah, this is technically just a relative path. In BYOND, a type path doesn't need to start with `/datum`. This just creates `/e`.

/vg/ had this for a long time too, they just had a rogue `a` lying around.

**Pull request merged**
