### PR TITLE
Power cell tiers consistency

### PR DESCRIPTION
**Pull request by MTandi**
## About The Pull Request

Tier 3 had both 20 and 30 MJ cells for some reason, while 10 MJ cell was considered tier 2.

Now the scaling is proper: 10 MJ is tier 1, 20 MJ is tier 2, and so on...

Also updated plasma crystal sprite, and gave unique sprites to the smallest cells.

image

## Why It's Good For The Game

The scaling was off, and the sprites made them look out of place for their tier.

## Changelog

:cl:
fix: Made 10 MJ & 20 MJ cells properly correspond to tiers 1 & 2 in lathes.
image: Updated cell sprites to correspond to other stock parts of their tiers.
image: Updated plasma cell, 500KJ cell and 2.5MJ cell sprites
/:cl:

### CODE REVIEW

**Review by Wallemations — APPROVED** [review]

**Comment by MTandi** [comment]
I'll add a couple more sprites.

**Comment by alien3301** [comment]
I feel like the tier 3 cell should keep that gold line. Makes it more consistent with the other cells.

**Comment by EricZilla** [comment]
Those lil batteries are to die for. Is the 2.5 meant to be a double battery or a D battery?

**Comment by AarontheIdiot** [comment]
t1 and t2 cells would look too similar at a glance imo

**Comment by MTandi** [comment]
> Those lil batteries are to die for. Is the 2.5 meant to be a double battery or a D battery?

Double, 9V. I initialy thought of making it for 1 MJ variant, but it seems to be a default one for many cells in the game.

**Comment by MTandi** [comment]
> t1 and t2 cells would look too similar at a glance imo

Not much different from the matter bins on the side as you can see, thanks to orange being bright and the red being dark.
In-game it looks good to me.

**Comment by MTandi** [comment]
> I feel like the tier 3 cell should keep that gold line. Makes it more consistent with the other cells.

The other parts don't have any orange lines.

image

**Review by san7890 — CHANGES_REQUESTED** [review]
code is fine

**Review by san7890 — APPROVED** [review]
okay code is actually fine

**Comment by Admiral-Gigaton** [comment]
Plasma crystal be summoning queen slime rn

**Pull request merged**
