### PR TITLE
Adds Space Casino space ruin

### PR DESCRIPTION
**Pull request by AarontheIdiot**
## About The Pull Request

 PR adds a completely new ruin to space for people to explore and gamble in.

## Why It's Good For The Game

 Some people get tired of exploring the same old space ruins everytime they explore space. Variety is a great thing to have more of.

## Changelog
:cl:
add: Added a new space ruin; Space Casino!
/:cl:

### CODE REVIEW

**Comment by Ziiro** [comment]
Got a screenshot?

**Comment by tralezab** [comment]
here you go bro i hacked their ip to get it

image

**Comment by Ziiro** [comment]
oh mapdiffbot actually takes screenshots I'll just show myself out then
😂🔫 

The only thing I would change is giving a way to get behind the bar without having to jump the table. Seems weird.

**Comment by WJohn** [comment]
Aight I'm gonna be the voice of quality control here because honestly dude, you need to add more detail to this kind of thing. I don't want to keep seeing new ruins added in with minimal amounts of quality put into their mapping. I get these are first time projects for a lot of people but they need to be at least comparable to boxstation or higher. There's no APC, life support, way to access the bartender area without climbing over the table(??), the rooms are quite barren, everything is basically just wooden flooring-- come on man. These things ain't hard.

**Comment by AarontheIdiot** [comment]
> Aight I'm gonna be the voice of quality control here because honestly dude, you need to add more detail to this kind of thing.

I hear you, i'll make some design changes and re-open at a later date once they're finished.

**Pull request closed without merging**
