### PR TITLE
Adds yeehaw to the discoball dj soundboard

### PR DESCRIPTION
**Pull request by improvedname**
YEEHAWWWW

:cl: improvedname
add: adds yeehaw to the dj's disco soundboard
/:cl:

[why]: # (Please add a short description [two lines down] of why you think these changes would benefit the game. If you can't justify it in words, it might not be worth adding.) yeehaww

### CODE REVIEW

**Comment by evsey9** [comment]
quickmerge

**Comment by Robustin** [comment]
Priority: CRITICAL

**Comment by Anonmare** [comment]
yeehaw

**Review by Cyberboss — CHANGES_REQUESTED** [review]
Fix the changelog

**Comment by improvedname** [comment]
fixed

**Review by Cyberboss — APPROVED** [review]

**Comment by Qbopper** [comment]
wew

**Comment by PKPenguin321** [comment]
aw shucks pardner

**Pull request merged**
