### PR TITLE
Attackby() now contains a Params argument.

### PR DESCRIPTION
**Pull request by RemieRichards**
attackby() now contains a Params argument passed down from the click that called it, like afterattack()
This allows you to use params in attackby() instead of snowflaking a `return 1` in the attackby and using the afterattack.

Yes afterattack has the same argument with identical data, but using afterattack like that is shitty.

Surprisingly only type added their own special arguments to attackby(): Guns
However I have tested this type to ensure nothing has changed functionally, and moved all their extra arguments and attackby() calls along one place (eg. attackby(Item,user,snowflek_shit) --> attackby(item,user,params,snowflek_shit))

One usage of this new argument is that items placed on tables (not racks, explained further down) will now center their icon on where the user clicked. (pixel_x and pixel_y values are now also reset upon item pickup)

Why not racks? Well they look like a rack.. so it makes no sense for items to be strewn about instead of logical ordered.

<B>Demo of table-item pixel placement:</B>
pixelperfectitems

### CODE REVIEW

**Comment by RemieRichards** [comment]
it's a minor refactor of attackby() arguments, I guess.

**Comment by phil235** [comment]
It's great but I fear pixel placement will make tablecrafing and especially cooking harder since you won't be able to easily stack items in the middle of the table w/o attacking other items instead of the table.

**Comment by RemieRichards** [comment]
@phil235 tablecrafting just requires them to be on the same table, it ignores pixel placements (or if it doesn't it really should)

**Comment by phil235** [comment]
I mean that if people place their items on a table, with pixel placement, then the table will be completely covered after placing a handful of items, making placing more items on the table impossible without either throwing it onto the table or using alt+click.

**Comment by dannno** [comment]
I don't think it will be that bad, we have alt-click anyways (and tbh tablecrafting is dumb but that's a whole new discussion)
This is good stuff :+1:

**Comment by WJohn** [comment]
Oh my GOD this is awesome. Though I'm worried about items which naturally are already badly shifted around as sprites, like screwdrivers (which are for some reason near the bottom).

**Comment by dannno** [comment]
Well, someone could comb through the DMIs and center anything that has a particularly stupid orientation

**Comment by Miauw62** [comment]
BYOND has a built-in params list.

**Comment by RemieRichards** [comment]
@Miauw62 what do you think I am passing down From Click() to Attackby()? Haha

**Comment by ike709** [comment]
still waiting on all of your other stuff Remie

**Comment by Razharas** [comment]
Im concerned with table icon eclipsion by things with big icons like books
This needs to be adressed somehow

**Comment by paprka** [comment]
Remie, thank you for this, you think it might be worth adding https://github.com/tgstation/-tg-station/pull/7485 again now that this allows you to place objects back down on tables where you want?

**Comment by mrpain666** [comment]
Oh thank fucking god the fucking warden's desk, among other things, have been a fucking bitch to work with without this.

**Comment by RemieRichards** [comment]
@paprka I actually did that in this PR, just in a different manner.

**Comment by paprka** [comment]
Oh okay

**Comment by RandomMarine** [comment]
Bartenders need this in their life right now.

**Comment by paprka** [comment]
^ so much this, drinking with people would be so much easier if i didn't accidentally pick up their drink.

**Comment by phil235** [comment]
merge conflict

**Comment by ComicIronic** [comment]
Can /vg/ have this?
Looks mighty useful, especially since you could use it to finally be able to put wrenches on tables instead of throwing them like a toddler with a temper tantrum.

**Comment by RemieRichards** [comment]
@ComicIronic Consider this reply a re-licensing/what have you, so that VG may indeed have it.

**Comment by RemieRichards** [comment]
also @phil235 conflicts are fixed.

**Pull request merged**
