### PR TITLE
Autolathe can make emergency welding tools

### PR DESCRIPTION
**Pull request by erwgd**
:cl: erwgd
add: You can now make emergency welding tools in the autolathe.
/:cl:

### CODE REVIEW

**Comment by Iamgoofball** [comment]
But it can already make normal welders

**Comment by GunHog** [comment]
Not particularly opposed to this, it just seems kind of pointless for the reason stated above.

**Comment by coiax** [comment]
An emergency welding tool is w_class 1, while a normal welder is w_class 2.

**Comment by Iamgoofball** [comment]
Ah, that makes sense

**Comment by GunHog** [comment]
In that case, :+1:

**Comment by kevinz000** [comment]
what is the functional difference between w_class 1 and 2?

**Comment by GunHog** [comment]
"Tiny" vs "Small" items. You can insert tiny items into wallets and other things like that.

**Pull request merged**
