### PR TITLE
Adds some extra flavor to station names.

### PR DESCRIPTION
**Pull request by kyrahabattoir**
Does this actually need any explanation?

### CODE REVIEW

**Comment by The-clown-known-as-Pepe** [comment]
Freeze my dude

**Comment by kyrahabattoir** [comment]
Don't care.

**Comment by WJohn** [comment]
This is so ridiculously minor,  so whatever.

**Comment by AnturK** [comment]
Change the list to strings file and i'll be okay with it.

**Review by Cyberboss — CHANGES_REQUESTED** [review]
Make it a /strings list and we can write it off as code improvement

**Comment by kyrahabattoir** [comment]
I don't know man, this is like, complicated.

**Comment by Cyberboss** [comment]
Just change the line to `GLOBAL_LIST_INIT(station_prefixes, world.file2list("string/station_prefixes.txt"))` and then put the stuff in the file 1 line at a time

**Comment by moonlol** [comment]
i see what you mean by "flavour"

**Comment by ExcessiveUseOfCobblestone** [comment]
>Make it a /strings list and we can write it off as code improvement

They should atomize the PRs at that point.

If you want to change the station name into your favorite may may or whatever this is, just use the charter. I don't really see the draw to adding this and allowing it to be hidden with a good change [turning it into a .txt] seems disingenuous to the freeze.

**Comment by Cyberboss** [comment]
Stale

**Comment by kyrahabattoir** [comment]
You can't tell me what to do @Cyberboss

**Comment by Cyberboss** [comment]
Ok

On Aug 6, 2017 9:28 PM, "Kyrah Abattoir" <notifications@github.com> wrote:

You can't tell me what to do @Cyberboss <https://github.com/cyberboss>

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/tgstation/tgstation/pull/29622#issuecomment-320547231>,
or mute the thread

**Pull request closed without merging**
