### PR TITLE
Adds work boots for engineers

### PR DESCRIPTION
**Pull request by TZK13**
ca2ff7cc-8ab7-11e4-8da9-dd55fcd5dd86
b9fe8d32-8ab7-11e4-8ffd-3d0278cc71d8

Resurrected with Pap's permission from #6540 which got bogged down in debate over the jackboot sprites, all credit for the sprites and code go to Pap.

This also updates and fixes some issues with the character setup previews, the most glaring one being that boots currently look like they're underneath whatever uniform the character is wearing.

### CODE REVIEW

**Comment by fj45** [comment]
You may also want to give atmos techs some boots. (Although firefighter boots would fit them better.)

**Comment by paprka** [comment]
Firefighter boots are a part of their fire suits themselves. Atmos techs have always had black sneakers outside of that to distinguish themselves, and I'd prefer if they kept sneakers.

**Comment by TZK13** [comment]
Yeah I was thinking about atmos techs but they have black sneakers which seems fine to leave as is to me.

**Comment by pudl** [comment]
bad sprite, why cant engineers just have orange shoes to look unique

**Comment by WJohn** [comment]
:+1:

A bit more shininess would be nice, but if you're trying to make it dull rubber then this is fine.

**Comment by paprka** [comment]
orange shoes are for prisoners, they can be cuffed because of this

**Comment by TZK13** [comment]
>orange shoes to look unique

Orange shoes are literally for prisoners.

**Comment by Nienhaus** [comment]
That would make them pretty unique then :p

**Comment by pudl** [comment]
why cant all fucking shoes be shackle-able. why does it matter if orange shoes are for prisoners, why do atmos techs have black shoes?! THOSE R FOR ASSISTANTSS!! WTF!

**Comment by TZK13** [comment]
>why do atmos techs have black shoes?! THOSE R FOR ASSISTANTSS!! WTF!

The bartender, botanists, cook, janitor, librarian, cargo tech, shaft miners, chaplain, mime, and robotocists all wear them too. The only people that wear orange shoes are engineers and prisoners and they look fucking stupid on engineers, their job is to be around heavy machinery and things under construction you don't wear sneakers for that sort of shit.

**Comment by fj45** [comment]
"their job is to be around heavy machinery"

Double that for atmos techs and add in freezing cold and burning hot piping.

**Comment by TZK13** [comment]
Sure but atmos techs don't get hard hats either except with their exclusive firesuits which come with boots.

**Comment by paprka** [comment]
Atmos techs are a really laid back department compared to engineering. There's no real reason for them to have industrial satchels or boots.

**Comment by WJohn** [comment]
They drag around a lot of heavy piping, still. Imagine those enormous disposal pipes landing on your toes!

**Comment by paprka** [comment]
operative word is drag and not lift

**Comment by Jordie0608** [comment]
Changelog.. i guess?

**Pull request merged**
