### PR TITLE
"Ready" tag now does nothing

### PR DESCRIPTION
**Pull request by Cyberboss**
Closes #32053

### CODE REVIEW

**Comment by kevinz000** [comment]
FUCK

**Comment by AnonymousNow** [comment]
First I thought I was being called out for something. The reality is funnier.

**Comment by Qustinnus** [comment]
literaly hitler

**Comment by ChangelingRain** [comment]
Please provide a comment with reasoning when closing PRs.

**Comment by optimumtact** [comment]
Right sorry, I forgot, removing the WIP tag is still relevant functionality, there's no reason to remove it.

**Pull request closed without merging**
