### PR TITLE
Adds SQDL Spells & a Menu to Give Them to Players

### PR DESCRIPTION
**Pull request by Y0SH1M4S73R**
## About The Pull Request

SDQL spells are spells that execute an SDQL query. Admins with fun verbs have the ability to open a menu allowing them to define all the relevant vars for the spell, including icons and spell requirements. Here is a video demonstrating the menu in action:

https://user-images.githubusercontent.com/12720844/113232902-0c92c280-926c-11eb-8c07-e5fb17942cce.mov

Oh it also fixes a bug with superuser SDQL queries always runtime if they try to call a proc.

## Why It's Good For The Game

Admins can now give players abilities that would otherwise require constant admin supervision or other weird workarounds. This has the potential to greatly expand the range of viable TC trades and event gimmicks.

## Changelog
:cl:
admin: There is now a menu that allows admins to give players spells that execute SDQL queries. New users of this menu should study it and its tooltips to figure out how to make the most of it.
/:cl:

### CODE REVIEW

**Comment by ninjanomnom** [comment]
This is a security nightmare and probably a terrible idea, but it does allow for some interesting possibilities. It should definitely be behind some more restrictive permission than just fun and should have a config value that defaults to disabled so hosts can choose whether they want something this dangerous available.

**Comment by ArcaneDefence** [comment]
I'm fucking terrified for what this could lead to

**Comment by Y0SH1M4S73R** [comment]
I should note that the queries that SDQL spells execute are assigned by the admin at the moment that they are given to the player, and can only be changed thereafter via VV.

**Comment by Y0SH1M4S73R** [comment]
God this commit history is a fucking mess I'm gonna reopen this pr.

**Pull request closed without merging**
