### PR TITLE
Changes how Cultists obtain the bastard sword. Instead of sacrificing Heretics, you now sacrifice Null Rods, with a caveat. 

### PR DESCRIPTION
**Pull request by MrMelbert**
## About The Pull Request

Merry Christmas, I bring Chaplain code. 

This PR reworks how cultists obtain the bloody bastard sword. 

Instead of sacrificing a Heretic, you gain the bastard sword by sacrificing a Null Rod that has been used by a holy person to spill cultist blood.

You can also sacrifice a Null Rod to turn it into a cult blade it if hasn't spilled any blood, as a means of destroying it. 

- Putting a Null Rod over an Offer rune with
   - 0 or 1 cultist crits / kills will transform it into ritual dagger.
   - 2 cultist crits / kills will transform it into longsword.
   - 3 or more cultist crits / kills will transform it into the bastard sword.

This effect does not apply to special null rod types like the Bow or Scythe implant. 

Heretics retain their innate cult stun resistance, and are still un-convertable. 

## Why It's Good For The Game

- Allowing the Cult to get multiple of these things is horrible. 
   - This puts a soft-cap on it to 1 under most circumstances.
- This makes obtaining the sword less incredibly easy. 
   - Heretics require a lot more time and effort to get equipped to pose a passing chance fighting cultists. As a consequence, it's dead easy to obtain: `I try to convert a guy 10 minutes into the round, they glow green, I stab them to death with my dagger. They can do nothing to defend themself. Free sword.`
   - Instead, we put it behind the chaplain, who more often than not is protected by security. 
      - Additionally, we put it behind the requirements that the chaplain is *robust*: a chaplain that has been killing cultists actively. 
   - This also serves as a "comeback" mechanic, as if a chaplain has been ripping and tearing through your ranks, but you manage to take them down, you are rewarded with a strong weapon. 

Honestly I would prefer if we straight up removed the sword (or... maybe nerfed it) but improve, don't remove etc. 

## Changelog

:cl: Melbert
balance: Blood cultists can now convert a Null Rod into a cult weapon on an offer rune. The strength of the weapon it is converted into depends on how many cultists the Chaplain crit / killed with it. At five or more, it will turn into a Bastard Sword. Note, sacrificing someone holding a Null Rod will automatically convert it after they are gibbed. 
balance: Heretics no longer produce a Bastard Sword upon cult conversion. They are still immune to cult stun and cannot be converted by blood cultists. 
/:cl:

### CODE REVIEW

**Comment by MrMelbert** [comment]
wat

**Comment by Striders13** [comment]
I don't think chaplains use their rods to actually attack people much during cult, they would probably use like a laser, while nullrod is kept for spell protection. 
So we probably won't see this thing often (good).

**Comment by MrMelbert** [comment]
Well I use my holy artifact as a chaplain vs cult so sorry that I'm not cringe

**Comment by necromanceranne** [comment]
Also, what stops you just...taking it off their corpse?

**Comment by nianjiilical** [comment]
do null rods actually have damage bonuses against cultists? this seems like it might be kind of rare

especially since vorpal scythe feels pretty popular anecdotally

then again the sword *is* pretty fucking strong so maybe thats fine

**Comment by Arturlang** [comment]
This is pretty much a soft removal.

**Comment by DATA-xPUNGED** [comment]
I like the idea but the numbers feel way too overtuned, killing 2 cultists already should be enough to get the bastard sword

**Comment by MrMelbert** [comment]
Let me get the stats for average # of cultists when risen

**Comment by MrMelbert** [comment]
image

**Comment by SimplySmiley123** [comment]
> do null rods actually have damage bonuses against cultists? this seems like it might be kind of rare
> 
> especially since vorpal scythe feels pretty popular anecdotally
> 
> then again the sword _is_ pretty fucking strong so maybe thats fine

It doesn't have a damage bonus, but it has the boon of giving the wielder immunity to cult stuns (anti-magic so no wizard spells will hit the wielder either)

**Comment by MrMelbert** [comment]
Decreased it by one in accordance to the stats I got

**Comment by MrMelbert** [comment]
> do null rods actually have damage bonuses against cultists? this seems like it might be kind of rare

All it requires is critting them at the very least. Most of the Null Rods even have Amour Penetration which makes them good against very armored cultists. 

I do it all the time when I am chaplain vs cult.

**Comment by RikuTheKiller** [comment]
I disagree with this and agree with the sentiment that bastard sword should be rebalanced rather than put behind something else.
This is a soft-removal as the conditions for it won't occur under normal circumstances.
You're among the (likely) few that actually use the null rod as a melee weapon against cult.

Actually improve it by balancing the damn thing rather than (soft) removing it, as you yourself said.

**Comment by itseasytosee** [comment]
You are probably gonna have to clean up all of the null rod subtypes from lavaland/icebox because alot of them are terribly easy to obtain.

**Comment by itseasytosee** [comment]
Also i think it would be cooler to keep the heretic sacrifice mechanic, but replace the reward to make it something else instead of the bastard sword. I personally am attached to the sentiment of rewarding culties for hunting heretics.

**Comment by necromanceranne** [comment]
> You are probably gonna have to clean up all of the null rod subtypes from lavaland/icebox because alot of them are terribly easy to obtain.

if it isn't being used by a chaplain, it won't matter.

**Comment by MrMelbert** [comment]
> You are probably gonna have to clean up all of the null rod subtypes from lavaland/icebox because alot of them are terribly easy to obtain.

I don't mind this since they don't really matter

> I am attached to the sentiment of rewarding culties for hunting heretics.

I don't really watch cultists hunt down heretics though, a majority of the time I just end up watching cultists trying to convert some guy, but it turns out they're a heretic so they just stab them to death instead. And 9 times out of 10 the heretic can't do anything because they're no match. 

Maybe someone can add a reward back when heretic actually gets their own rewards for hunting cultists rather than them being stunted for no gain

**Comment by itseasytosee** [comment]
> Maybe someone can add a reward back when heretic actually gets their own rewards for hunting cultists rather than them being stunted for no gain

My bad

**Comment by MrMelbert** [comment]
Rough estimate for how many people crit with null rods across the last month 

image

**Comment by MrMelbert** [comment]
> I disagree with this PR and agree with the sentiment that the bastard sword should be rebalanced. 

I thought about it more and I think I would rather the sword be a rare, very powerful "oh crap" weapon than making it a common, slightly-above-average sword.

**Comment by necromanceranne** [comment]
> Definitely a bit lower than I expected. Number of cultist slain could probably be tweaked down a bit.

It kind of makes sense why the multiverse sword is able to crit, given it fluctuates between 1 and 30 force. It can hit you with as much damage as the cultist can put out with their own swords.

**Comment by Higgin** [comment]
Does the null rod give any feedback on how many cultists it's been used to kill? If not, would be neat - but maybe only make it give feedback after eyes/halos?

**Comment by MrMelbert** [comment]
> It kind of makes sense why the multiverse sword is able to crit more often than any of the others, given it fluctuates between 1 and 30 force. It can hit you with as much damage as the cultist can put out with their own swords.

I made the graph assuming every hit was 15 force so don't put too much stake in that (it just so happened the multiverse sword was most used for combat of all nullrods)

**Comment by SomeoneYouProbablyKnow** [comment]
the 
> but improve, don't remove etc.
and its consequences have been a disaster for the spessmen race.

This does create a soft incentive for chaps not to use their null rod to bonk people with. I don't think it's gonna influence how chaps act (since half of them already act like seccie but magic immune and still use guns and batons) 

But maybe the condition could be changed to *promote* chaps bashing skulls instead.

**Comment by F-e-r-n** [comment]
I actually like this change, but make sure to check its not a CULTY stabbing another culty as then it'd still be dead easy to obtain one of these. Maybe you could also give chaplain a buff if they kill cultists with null rod, like a cultist bane or something?

**Comment by RikuTheKiller** [comment]
> VEEEEERY rough estimate for how many people crit with null rods across the last month (assuming force = 15 and target health is always 100%)
> 
> image
> 
> Definitely a bit lower than I expected. Number of cultist slain could probably be tweaked down a bit.

I mean, how many of these are cultist kills? Nullrod is used for combat outside of cultists too, most of these are likely just normal people or tots.

**Comment by Loafin34** [comment]
What the fuck? Why do you need the chaplain/assailant to kill 3 people in order to get the bastard sword? Cult's priority should be getting the nullrod first and foremost, and making it become the bastard sword every time is thematically appropriate because A. it is a bastard child, nullrod of good god and corruption of narsie and B. it is cult's hard counter, the cult gets a hard counter to the station by converting it

**Comment by ExcessiveUseOfCobblestone** [comment]
It seems a bit counterintuitive that the item you, the cultist, want immediately destroyed has a reward for not only keeping it around but letting it kill your teammates as well. That sounds ripe for BM or just generally poor play.

**Comment by MrMelbert** [comment]
> It seems a bit counterintuitive that the item you, the cultist, want immediately destroyed has a reward for not only keeping it around but letting it kill your teammates as well. That sounds ripe for BM or just generally poor play.

It's not a reward for letting it kill your teammates, it's a reward for avenging the deaths of your teammates

**Comment by MrMelbert** [comment]
> I imagine if you were to log cultist kills with a nullrod, you'd probably get like 5 per month and that would go down further once people know it gives them a bastard sword. There is no fucking way anyone is ever getting this in a regular round.

It's quite dumb to expect that people think like this. Literally every single time someone brought up "well people will know X is a thing so they won't do it" in response to one of my PRs it's never happened. 

/TG/ players powergame their asses off but they don't go out of their way to be actively detrimental to themselves and others in the off case it pays off.

**Comment by ExcessiveUseOfCobblestone** [comment]
> It's not a reward for letting it kill your teammates, it's a reward for avenging the deaths of your teammates

It's at best both. If I know I get the giga item by letting the chaplain get away with a few kills then oh noooo i didnt respond to the summon request or oh noooo i totally dont want to blow my cover to help him! 

The cult shouldnt be rewarded with the giga item that greatly enables carrying/soloing for letting the item they should be destroying be used to fester team kills.

I think the opposite will be true too though, if non-cult know that hitting people with the item CAN give cult an advantage then theyll be discouraged in using it to deny that ability so cult is basically never going to see the item.

This is assuming the sword itself is worth all of this trouble, if it is then people are absolutely going to enable (cult)/deny (noncult) the ability for this item to ever trigger. Otherwise its just a fancy removal or very-niche interaction, in that case yeah this hits the mark.

**Comment by MrMelbert** [comment]
> It's at best both. If I know I get the giga item by letting the chaplain get away with a few kills then oh noooo i didnt respond to the summon request or oh noooo i totally dont want to blow my cover to help him!

I can't imagine any universe in which a cultist would refuse to help another cultist for the off chance that they can nab the chaplain later in hops of getting the funny sword. It's actively putting your team in a state more likely to lose without any guarantee that you can actually follow though.

> The cult shouldnt be rewarded with the giga item that greatly enables carrying/soloing for letting the item they should be destroying be used to fester team kills.

But that's the idea behind moving it to this position - so if you fail to destroy it, and the chaplain has been owning your team you get the opportunity to come back. 

> I think the opposite will be true too though, if non-cult know that hitting people with the item CAN give cult an advantage then theyll be discouraged in using it to deny that ability so cult is basically never going to see the item.

Again I really doubt this will be at the forefront of people's minds when it comes to cult - chaplain dynamics. If you REALLY REALLY REALLY think the worst of people I can give the chaplain cool stuff in return for felling cultists (sect favor, more force on their stick?) but I don't think even the most serial powergamers will say "gosh I wish I could fight back against the cult but my only weapon might buff them so I guess I'll die instead."

**Comment by GuillaumePrata** [comment]
Players can always self-sabotage out of some secondary interest, it is quite hard to codify this possibility out of a game, even more on a wide sandbox like we have.

Now on the other angle, comeback mechanics are a gem, it is something I wish we put as a focus more on whenever possible and this PR achieves that extremely flavorfully.

Win-more antags like Progtots (no this is not a criticism to Progtot) are fun, not gonna lie, but they rarely make interesting stories to be shared when compared to antagonists that manage to come back out of a really bad situation.

**Comment by Jezzared** [comment]
Simply call Chaplains who don't purge the nonbelievers with their holy weapon cringe.

**Comment by Admiral-Gigaton** [comment]
> > It's not a reward for letting it kill your teammates, it's a reward for avenging the deaths of your teammates
> 
> It's at best both. If I know I get the giga item by letting the chaplain get away with a few kills then oh noooo i didnt respond to the summon request or oh noooo i totally dont want to blow my cover to help him!
> 
> The cult shouldnt be rewarded with the giga item that greatly enables carrying/soloing for letting the item they should be destroying be used to fester team kills.
> 
> I think the opposite will be true too though, if non-cult know that hitting people with the item CAN give cult an advantage then theyll be discouraged in using it to deny that ability so cult is basically never going to see the item.
> 
> This is assuming the sword itself is worth all of this trouble, if it is then people are absolutely going to enable (cult)/deny (noncult) the ability for this item to ever trigger. Otherwise its just a fancy removal or very-niche interaction, in that case yeah this hits the mark.

my name was spoken. i have been summoned.

i feel like this just removes bastard sword from game, i dont see people using it that much (tho i dont think people know what it does, i personally dont, i always get murdered and soulstoned instead of converted because i shredded too much and they got pissy) and locking it behind one item, making it so there can only be one in an entire round, is a bad idea. this just encourages more edgy mc-edgeface scythe players, and i personally dont think its a good idea to encourage that

also encourages sec to hoard it so culty cant fuck it all up, and metagame this shit. maybe just lock it behind a conversion counter, or make it so you can get them only after you take out nar nar's target, then do fuck all to get it besides null crod?

**Comment by Loafin34** [comment]
with this PR, are heretics able to dual-wield cult and heretic power?

**Comment by MrMelbert** [comment]
> with this PR, are heretics able to dual-wield cult and heretic power?

image

**Pull request merged**
