### PR TITLE
Syndie nuke and closet mapped to shuttle

### LINKED ISSUE #12554: Nuke ops dont spawn with a nuke
for both admin spawned ops and the gamemode itself, there is no nuclear bomb spawned in the syndicate shuttle.
@Jordie0608 since you touched centcom last

### PR DESCRIPTION
**Pull request by Jordie0608**
Nuke op's armory closet and nuke are mapped to the syndie shuttle instead of being landmarks spawned during startup.
Fixes #12554

### CODE REVIEW

**Comment by Shadowlight213** [comment]
why was the closet even made a landmark? that seems dumb

**Comment by Incoming5643** [comment]
In case admins wanted to use the shuttle for events other that nuke ops I'd wager. I think there was a point where literally EVERYTHING of merit was jammed in that one closet.

**Comment by Jordie0608** [comment]
Admins can just delete it if they want I guess.

**Comment by Firecage** [comment]
Incoming. I am pretty sure the nuke ops stuff were always landmarked...

**Comment by Anonus** [comment]
I'll just do this for dream with my own PR because I've got to fix a few things anyway.

**Comment by Tokiko1** [comment]
I have fixed this in my PR for birdstation aswell, though I suppose resolving the conflict on my end won't much extra time. Just remove it from the PR if you feel like it.

**Comment by Shadowlight213** [comment]
@phil235 @Cheridan @RemieRichards @Razharas @Aranclanos @Miauw62 
Priority high. needs merge as nuke ops is unplayable without admin intervention currently.

**Pull request merged**
