### PR TITLE
FUCK CATGIRLS PR

### PR DESCRIPTION
**Pull request by SireTurret**
deletes felinids

## About The Pull Request

Removes Felinids

## Why It's Good For The Game

Fuck Felinids

## Changelog
del: Removed felinid code from the game
/:cl:

### CODE REVIEW

**Comment by nemvar** [comment]
First

**Comment by SireTurret** [comment]
mad? stay mad

**Comment by GuyonBroadway** [comment]
You ding dong, you didn't delete all the checks and prefs and references to felinids in other parts of the code.

This would not have resolved the issue, just caused runtime errors which they would then use as justification to bring them back.

**Comment by wesoda25** [comment]
future maintainer

**Comment by SireTurret** [comment]
> You ding dong, you didn't delete all the checks and prefs and references to felinids in other parts of the code.
> 
> This would not have resolved the issue, just caused runtime errors which they would then use as justification to bring them back.

WHO CARES

**Pull request closed without merging**
