### PR TITLE
Refactors stunbatons and cattleprods

### PR DESCRIPTION
**Pull request by ghost**
[why]: fixes #38568

### CODE REVIEW

**Comment by Armhulen** [comment]
i just learned i could have subtracted the typecachelist of cattleprods but uuuh this refactor is nice so i'm keeping it

**Comment by epicmemename** [comment]
rip suit slot technique

**Comment by ExcessiveUseOfCobblestone** [comment]
This is not a good refactor please do the 1 line change instead or describe how it's good.

**Comment by Armhulen** [comment]
uuuuuuuugh give me a second

**Pull request closed without merging**
