### PR TITLE
Adds voice effects for lizards, ethereals, and xenomorphs.

### PR DESCRIPTION
**Pull request by Iamgoofball**
## About The Pull Request

Adds voice effects for lizards, ethereals, and xenomorphs.
Adjusts the API to break TTS input into sentences and send those to the worker endpoints for better batching and to bypass an issue with VITS.
Filters now support %SAMPLE_RATE% which is automatically replaced with the sample rate of the TTS server, so that effects like the new ones can be done without hardcoding the sample rate into DM.

## Why It's Good For The Game
More voice variety is good.
TGMC needed a way to differentiate xenomorph speech, this is sufficently creepy.
Makes lizards and ethereals sound different in conversations, which is good.
Audio is recorded with the new RVC layer.

https://github.com/tgstation/tgstation/assets/4081722/8169cb58-547d-4cbf-a8d9-c8069fb2ff8c

## Changelog

:cl:
add: Adds voice effects for lizards, ethereals, and xenomorphs.
/:cl:

### CODE REVIEW

**Comment by Wallemations** [comment]
Does the preview button in the character menu use the species' effects as well?

**Comment by Iamgoofball** [comment]
@Wallemations No, I'm probably going to change that soon

**Comment by nukularpower** [comment]
Really cool.  Any chance of some more variety in female voices soon?  it feels like the male voices are way more distinct vs the female ones

**Comment by Iamgoofball** [comment]
@nukularpower RVC allowing us to move from 22khz to 40khz will help immensely with that, as it brings higher ranges in the audio onto the table.

**Comment by Dorsisdwarf** [comment]
It feels kinda weird for the voice effect for the constantly-snarling deep-voiced xenomorphs that make a rattling hiss when they speak to be a chirpy reverb happy vox effect. It sounds more like the processing effect you'd use on abductors.

**Comment by Iamgoofball** [comment]
the deep AI voice has long since been removed

**Comment by Neskah** [comment]
Howdy. This sounds cool, but apparently it's broken everything on TGMC. We don't have any listed testmerges or changelogs related to voices, but robot voices seem to be 2-3 octaves higher and human voices are completely unexpressive while also frequently using the wrong consonants. For example, humans pronounce "nah" as "wah". I don't understand why, but it started about 2 days ago from the time of this post. Is this PR why?

**Comment by Iamgoofball** [comment]
TGMC needs to manually mirror things

**Comment by Watermelon914** [comment]
@Iamgoofball has MSO updated the python script for this?

**Review by Watermelon914 — CHANGES_REQUESTED** [review]
Need to give aliens a voice by default, since xenos have no voice by default.

**Comment by Watermelon914** [comment]
Lizard voice sounds a bit too similar to the alien voice

**Comment by Iamgoofball** [comment]
the lizard voice is a toned down version of the alien voice because of the meme

**Comment by Iamgoofball** [comment]
.

**Comment by Iamgoofball** [comment]
.

**Comment by Ghommie** [comment]
I'm going to echo what Wallemations and Watermelon asked regarding the character menu, xenos, and the python script (except lizards sharing a similar effect with xenos), nice PR however.

**Comment by Jacquerel** [comment]
Reopen this when you've done any of that above stuff.

**Pull request closed without merging**
