### PR TITLE
[READY] ~SPELL CARDS~, homing projectiles, and more! 

### PR DESCRIPTION
**Pull request by silicons**
Adds spell cards. They're a wizard spell that shoots a burst of 5 semi-accurate homing cards.
Projectiles now have a homing framework, complete with some variant of simulated inaccuracy.
The said wizard spell will make use of a new mob component, that allows that mob to select targets by moving their cursor near them. It will give a visual and lock onto the nearest mob to the cursor, allowing the homing projectiles to target on the locked on mob/object.
Removes colliding variable from projectiles - We never used it after Bump was refactored to Collide.
Images soon when I get the lockon datum-components to work.

### CODE REVIEW

**Comment by fludd12** [comment]
I mean, the Marisa costume is a valid wizard outfit - this just seals the deal.

**Comment by evsey9** [comment]
FUCKING WEEBS GET OUT OF MY STATION REEEE

**Comment by Iamgoofball** [comment]
what the fuck are spell cards

is this yugioh

**Comment by Jordie0608** [comment]
Cards is a misnomer, you're actually just throwing Pots of Greed at people.

**Comment by ike709** [comment]
@Iamgoofball https://www.youtube.com/watch?v=0VtPgIX_Dbk

**Comment by PKPenguin321** [comment]
Yugioh would be cooler tbh

**Comment by Repukan** [comment]
Goof it's a Touhou reference

**Comment by Shadowflame909** [comment]
>Gambit from x-men reference. Wtf I love kevinz now

**Comment by Shadowflame909** [comment]
I want yugioh hair now.

**Comment by Spaceinaba** [comment]
where the fuck is my patchouli knowledge librarian gown you fucking hack

**Comment by PKPenguin321** [comment]
hey so when are we getting the yugioh hair

**Pull request merged**
