### PR TITLE
Removes the stun from the mecha punch

### PR DESCRIPTION
**Pull request by Aranclanos**
HAHA BALANCE MEMES

context: mechas are easier to build

### CODE REVIEW

**Comment by SconesC** [comment]
:-1: 

There are so many other, interesting ways to go around this

Restrict to to certain mechs, make it a module, etc.

**Comment by Zilenan91** [comment]
I don't mind this

**Comment by Kromgar** [comment]
Oh good now mechs cant ever possibly hope to kill xenos

**Comment by ExcessiveUseOfCobblestone** [comment]
What's a mech?

**Comment by Zilenan91** [comment]
Kromgar mechs literally 2 shot xenos with their laser module

**Comment by Xhuis** [comment]
If you changed this to Weaken, I wouldn't mind, but a giant fucking metal fist slamming into your fucking body should be enough to stun you.

**Comment by ExcessiveUseOfCobblestone** [comment]
I'm not understanding how this is balancing when Mechs are garbage anyways.

**Comment by Aranclanos** [comment]
context: mechas are easier to build

**Comment by Lumipharon** [comment]
>easier

Please explain.

**Comment by Dorsisdwarf** [comment]
:-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: 

And to reiterate, :-1:

**Comment by Aranclanos** [comment]
you can use any sensor module and capacitor

**Comment by Miauw62** [comment]
making this a module would be sweet tbh

**Comment by Cookiesndip** [comment]
Why? Mechs are kinda mediocre/below average anyway. No need to nerf 'em when people hardly use them.

**Comment by optimumtact** [comment]
I don't mind this, also mechs killed me with stun punch and I was mega salty about it.

**Comment by Zilenan91** [comment]
Yeah I don't either. Functionally infinite stuns are shit.

**Comment by Dorsisdwarf** [comment]
Well don't try and melee a fukken combat mech then

**Comment by optimumtact** [comment]
I didn't, I opened an airlock and got a mech fist to the face

**Comment by blobbernaut** [comment]
@optimumtact literally the exact same thing as getting a taser or stun baton to the face so W H O C A R E S

**Comment by Thunder12345** [comment]
>Well don't try and melee a fukken combat mech then

This. Get guns, get backup, kite it, never run straight at it.

**Comment by optimumtact** [comment]
it hurts my soul man, it hurts my fucking soul.

**Comment by Razharas** [comment]
Well month passed with no strong enough people to merge it so its left to me to decide
I like mechs
Denied

**Pull request closed without merging**
