### PR TITLE
Lightly resprites the (Analog) Wall Clock

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request
A circle-tool rim and a pure white fill was kind of eye-grating and I was bored.

The new sprite has a tiny bit of depth to the frame and an off-white center.
No, it's not animated still. That would be an utter nightmare with how in-character time works.

image
## Why It's Good For The Game
De-crusts a sprite, a little bit at least.
## Changelog
:cl:
image: resprited the (Analog) Wall Clock
/:cl:

### CODE REVIEW

**Comment by Wallemations** [comment]
Can you post the sprite itself for me? The clock kinda blends into the wall in that screenshot so it's hard to tell what changed

**Comment by OrionTheFox** [comment]
> Can you post the sprite itself for me? The clock kinda blends into the wall in that screenshot so it's hard to tell what changed

Yeah I was realizing that shortly after opening the PR
image

**Review by Wallemations — CHANGES_REQUESTED** [review]
Do you think you could show me a pic of what it would look like with a lighter color on top instead of the darker one?
Don't commit it though, I just want to see if it looks better that way or not since light should be hitting the top of it

**Comment by OrionTheFox** [comment]
> Do you think you could show me a pic of what it would look like with a lighter color on top instead of the darker one? Don't commit it though, I just want to see if it looks better that way or not since light should be hitting the top of it

I actually did test this prior to commit, but again it had the same issue of the wall blending so that ingame screenshot of side-by-side won't help here... 
image

I might do a 3rd thing where I make it more charcoal instead of gray. Black will stand out against the wall better...

**Comment by OrionTheFox** [comment]
> 
> I might do a 3rd thing where I make it more charcoal instead of gray. Black will stand out against the wall better...

image

Tested it with a blacker color and took an editor-sized screenshot. Thinking this'd work better.

**Pull request merged**
