### PR TITLE
makes age options more accurate

### PR DESCRIPTION
**Pull request by Iamgoofball**

### CODE REVIEW

**Comment by TrustyGun** [comment]
stop with the meme prs pls

**Comment by TechnoAlchemisto** [comment]
my character is johnny mcdude he's a 800 year old man who is alive through sheer force of will, he is also related to gimmy mcdude who is a 1 year old baby with the speed, appearance, and functionality of a grown adult.

**Comment by Iamgoofball** [comment]
the average spaceman has the mental capacity of a 5 year old so this reflects it

**Comment by KorPhaeron** [comment]
Go to bed

**Comment by PKPenguin321** [comment]
this would have gotten merged if the youngest was -1000 and the oldest was 1000, are you even trying goofball

**Comment by Iamgoofball** [comment]
good idea

**Pull request closed without merging**
