### PR TITLE
Removes stationary syndicate infiltrator docking ports on all maps.

### PR DESCRIPTION
**Pull request by WJohn**
You have a perfectly functional shuttle navigator computer. With the removal of these and their enormous no-go bounding boxes, both the infiltrator and the white ship will have more room to navigate around on all maps, and removes confusion on seeing huge red locations that you can't place a custom location at that aren't used 95% of the time.

:cl: WJohnston
del: Removes stationary docking ports for syndicate infiltrator ships on all maps. Use the docking navigator computer instead! This gives the white ship and syndicate infiltrator more room to navigate and place custom locations that are otherwise occupied by fixed shuttle landing zones that are rarely used.
/:cl:

### CODE REVIEW

**Comment by MoreRobustThanYou** [comment]
Doesn't the nav computer bug out if you rotate the ship

**Comment by Cruix** [comment]
The syndicate shuttle ignores all of these docking ports, and in fact uses them as waypoints that the camera can jump to so you do not have to scroll across the entire map to go from one side of the station to the other. If you want the white ship to do the same, just add all the ids to the whiteship navigation computer's jumpto_ports list.

**Comment by WJohn** [comment]
This isn't actually the case, as we have something called station_lock_override which forces the camera to look at the station z level regardless of whether it has docking ports physically on that z level, or a jumpto list for docking ports on other z levels.

**Comment by Cruix** [comment]
What is not the case? And what does station_lock_override have to do with anything?

All this is doing is removing functionality from the syndicate shuttle navigation computer, which is what the navigation computer was designed for in the first place, so that the white ship can land in more places, even though the problem could just as easily be solved by adding the same functionality to the white ship navigation computer.

**Comment by WJohn** [comment]
The only "lost" functionality here is preset locations to jump to both for camera jumping and for docking locations around the station. You use the custom navigation console for it (which is automatically locked to looking at the station z level), and THEN use the shuttle computer to go to your new custom location.

What is "gained" is more room to actually place these custom locations because those were being obstructed by 6 enormous landing zones. Both the infiltrator and the white ship can make use of this new space to navigate where they want to better. It is now much easier to place either the white ship or syndicate shuttle EXACTLY where you want above the armory, for example.

And since it's now required to use that console, it'll help deal with meta locations just a little bit, since they're never gonna take the same 6 exact spots as before (though common locations are still obviously a thing like the armory, AI sat etc).

**Comment by Cruix** [comment]
The syndicate infiltrator is not and has never been obstructed by these docking ports. If you just edit one var, the white ship will not be obstructed by them either.

**Comment by WJohn** [comment]
Oh! I didn't notice this was changed. Originally got blocked by those, my bad. I'll go and tweak that then.

**Comment by WJohn** [comment]
According to ninja the best thing to do is to remove these, since otherwise we run the risk of the white ship being run over by the syndicate shuttle's static locations.

**Comment by ninjanomnom** [comment]
I hadn't read what cruix was suggesting here and actually yeah having them share ports is probably the better option because then it allows them to basically just act as generic dock locations.

You'll have to mess with port sizes a little bit probably

**Comment by WJohn** [comment]
I'll play around with it some, give me a bit. Gonna probably need to majorly rework the bounding boxes of the syndicate shuttle to work with this.

**Comment by Cruix** [comment]
No matter what we do, there will always be the possibility of the two shuttles crashing into each other as long as they both have navigation computers. The only foolproof way I can think of to prevent it would be to have each one back off to some static location just before detecting that they will crash into the other one.

**Comment by WJohn** [comment]
I'm gonna try to have them share docking locations, which is gonna require some fairly extensive reworks if it doesn't pan out immediately.

**Comment by WJohn** [comment]
Okay after working with this for a while, having stationary locations means that you can still run over people who have placed custom docking locations and vice versa, because they do not check if someone is standing there. So for now I stand by this change for the removal of all stationary syndicate ports so neither of them can crash land on top of eachother or obstruct their custom location's room.

**Comment by Cruix** [comment]
They will still be able to crash land on top of each other, and if you did as I suggested the docking ports would not be obstructing either shuttle.

**Comment by WJohn** [comment]
Except this is EXACTLY what happened when I did what you said.

**Comment by Cruix** [comment]
OF COURSE this would happen, there are no checks in place to stop it from happening, as I stated above. This does not even fix the problem, it just makes it less likely to occur by forcing everyone to manually chose their location 100% of the time. It is like a travel agency making sure they do not have to worry about overbooked flights by telling everyone to book their flights themselves.

If you are really that worried about the ships crashing into each other then you can keep things the way they are, remove the navigation computer from the white ship (why does it even have one anyway?), or implement some system that prevents them from crashing into each other.

**Comment by evsey9** [comment]
make syndi ships be able to ram and make so that white ships cannot ram

**Comment by WJohn** [comment]
If I removed the white ship navigation then we would lose the fun of... navigating the white ship, or any ship on the station z level for that matter, which is boring. If I left it as it is then we have the above problem of massive unused areas that block the custom navigation a ton. And implementing a system that checks whether something is in the way is up to ninjanomnom for that.

**Comment by Cruix** [comment]
At least leave one, so that if the navigation computers break the syndicates will not be totally screwed.

**Comment by WJohn** [comment]
I can do that, sure.

**Comment by jughu** [comment]
Keep this we raid ship like pirates now. boaaard the ship!!!

**Review by ninjanomnom — APPROVED** [review]

**Pull request merged**
