### PR TITLE
Shuffles around cargo to be a real multi-z experience.

### PR DESCRIPTION
**Pull request by ArcaneMusic**
## About The Pull Request

This makes some changes to icebox cargo so that it can better use the multi-z aspects of the map a bit better. This integrates the cargo warehouse into the first basement level of icebox in a new area to the north of the suit room on mining, moves the QM's office to where the old warehouse was, and adds a large open staircase area to cargo to move crates from the warehouse to the open cargo area. This also tweaks the surrounding area to better facilitate the open area, between connecting the new spaces with the old, and moving around some buttons/wall frames.

Plus, now we actually have a way to get from cargo to mining a bit easier with the staircase.

Top level: 
image
Sub Level:
image

## Why It's Good For The Game

Better utilizes the multi-z aspects of the map so that the sub-levels are more than just the "mining-z slice".
Plus, this frees up some space in cargo should new things ever need to be mapped in, gives icebox a bit more of a unique identity as the "multi-z map".

## Changelog
:cl:
tweak: Cargo warehouse now exists in the 1st basement of icebox.
tweak: The QM office is now where the cargo warehouse is.
/:cl:

### CODE REVIEW

**Comment by GravitronBlue** [comment]
Liking the concept, although I've got complaints already about the removal of the warehouse shutters and open visibility of the warehouse itself.

Mostly speaking as a loyal ~~cargonian~~ Nanotrasen employee who wishes to ~~openly rebel and declare independence~~ perform quality inspections of crate contents before sending them to our trusted associates in the ~~greytide alliance~~ security department.

**Comment by LemonInTheDark** [comment]
Using multiz like this means people are more likely to fix the issues with it, which is nice.

**Comment by Doosteroni** [comment]
How does one get a crate Down and up multiz

**Comment by LemonInTheDark** [comment]
It uses stairs, and has the opportunity for falling. that's better then nothing imo

**Comment by Tlaltecuhtli** [comment]
can you make qm office less sad

**Comment by Dennok** [comment]
@ArcaneMusic Please. You can try to integrate my # 52397?
Maybe this gives me stimul to improve it.
Now it can be controlled only from platform.

**Comment by ArcaneMusic** [comment]
> @ArcaneMusic Please. You can try to integrate my #52397?
> Maybe this gives me stimul to improve it.
> Now it can be controlled only from platform.

So, I don't think it makes as much sense to use an elevator for a 1 floor level difference, since the warehouse should probably be pretty easy to access, BUT, using an elevator instead of the public mining ladder in the middle of the station sounds like a really solid idea.

**Comment by EOBGames** [comment]
image
This camera's detached from the wall

**Comment by EOBGames** [comment]
image
image
there's an atmos injector under this wall, it's also on the wrong layer.

**Comment by EOBGames** [comment]
image
the atmos pipes and disposals pipe just sorta... end here? I think this was old mail pipe for the QM's office, given it's got the QM sorttype on it.

**Comment by EOBGames** [comment]
image
An intercom could be useful here, just to even out the coverage a bit.

**Comment by EOBGames** [comment]
The Quartermaster's office is missing an APC and an air alarm.

**Comment by EOBGames** [comment]
As far as personal opinion goes, the inclusion of multi-z is good, although I worry that a full imagining of the map with multi-z will end up with the same problems donut had: namely that a map not purpose built with multi-z in mind will never quite match up with something explicitly built with it in mind. That said, I'm excited to see where you can take this.

**Comment by ArcaneMusic** [comment]
Map conflicts are pain and I am constantly facing it

**Pull request merged**
