### PR TITLE
Clown Tech Overhaul: Social Psychology and Unregulated Pranking [Unfucked]

### PR DESCRIPTION
**Pull request by alphanerdd**
This is a redo of a PR I made a little over a week ago. I fucked some things up with github so I decided to close that PR and reopen it in a clean request. Link to the original [here](https://github.com/tgstation/tgstation/pull/64627). A lot of the justification for certain changes can be found in the comments.
## About The Pull Request
I was inspired by [this post](https://tgstation13.org/phpBB/viewtopic.php?p=622102#p622102) in the forums that points out the shortcomings of Clown tech. This PR aims to rebrand Clown Tech to Social Psychology, expand what can be printed from the service protolathes, and add some fun new illegal tech synergies.

Clown tech is replaced with the **Social Psychology** node, which in addition to all the things old clown tech did, now includes recipes for dice bags, crayon boxes, cardboard cutouts, synthesizers, and decks of cards. All of these are available from the service protolathe.

With both Social Psychology and Illegal tech researched, a new node, **Unregulated Pranking** is unlocked. This enables adaptive cardboard cutouts, pneumatic pie cannons, and decoy nuclear authentication disks to be printed from the service protolathe. 
clowntechplus
## Why It's Good For The Game
Previously, clown tech only unlocked clown borgs, clown mechs, and airhorns. That's both useless and disappointing in my opinion. Now with Social Psychology, these clown items are tied to multiple civilian items that really should be printable via the lathe.  (also adding more nonessential items that require plastic may encourage chemists to make it occasionally.)

Unregulated pranking makes a few _mostly_ harmless syndicate items available to the public. The tech already has quite a high barrier to entry, considering all the perquisites for illegal tech, and in return provides items that can be mad funny. Cardboard cutout and decoy disk gimmicks are pretty funny, and it would be cool to see more of those in the future.

As for the other suggestions in the forum post, I rarely use the art tools in game, so I'm probably not the best person to make those changes. I am however a dedicated mime fan, and would love to see new mime items. However ~~I'm not creative enough to make new mime stuff~~ i wanted to atomize that into a separate PR at some point.
## Changelog
:cl:
del: clown tech node
add: social psychology node, which unlocks dice, cards, crayons, synthesizers, and bike horns in the service protolathe
add: unregulated pranking node, which unlocks adaptive cutouts, decoy disks, clown PDA cartridges, and pie cannons in the service protolathe
tweak: cardboard can be accepted by lathes and ore silos now
/:cl

### CODE REVIEW

**Comment by bruhlookatthisdood** [comment]
its.... beautiful!

**Comment by RaveRadbury** [comment]
Some of the things you're adding are cardboard based and can be made by hand.

Isn't this a bit unbalanced from a resource perspective?

**Comment by alphanerdd** [comment]
> Some of the things you're adding are cardboard based and can be made by hand.
> 
> Isn't this a bit unbalanced from a resource perspective?

The attached screenshot is outdated and I forgot to update it from the previous PR. I'll replace that soon. Adaptive cutouts and crayon boxes both require cardboard which can now be accepted by the lathes. For normal cutouts to be honest I forgot you can just craft those normally, and now that the lathe recipe requires cardboard, I'm probably just going to remove the recipe.

> Also crayons are a bounty so you're kinda printing money here.

You only get 3 bounty options at a time, so it's not really a reliable option for grinding. Besides, stuff like spears, stun prods, comfy chairs, and skateboards are already bounty options. All of those are craftable with renewable resources and aren't locked behind tech. Cargo already has so many ways to generate income, so making an 800 credit bounty printable for 2000 carboard and 2000 plastic isn't that huge.

**Comment by optimumtact** [comment]
Screenshot from 2022-02-12 09-25-42

**Comment by alphanerdd** [comment]
emoji-disintergrating

**Comment by YakumoChen** [comment]
Not really sure about the crayon boxes, that's literally printable food.

**Comment by bruhlookatthisdood** [comment]
> Not really sure about the crayon boxes, that's literally printable food.

Only on TGMC

**Comment by YakumoChen** [comment]
Crayons sate hunger on base tg

**Comment by alphanerdd** [comment]
> Crayons sate hunger on base tg

if powergamers start eating crayons to avoid interacting with the chef, I'm fine with that

**Comment by MetalClone** [comment]
Eaten crayons should make you feel sick and should provide a mood debuff

**Comment by bruhlookatthisdood** [comment]
*sad trombone*

**Pull request closed without merging**
