### PR TITLE
improve performance of vis_overlays by handling dir by using vis_flags

### PR DESCRIPTION
**Pull request by Couls**
## About The Pull Request
Title. Tested locally but I wouldn't mind a few testmerges to ensure nothing breaks from this change

## Why It's Good For The Game
Probably better than removing the old overlay and adding one with the updated dir

## Changelog
:cl:
code: vis dir changes are now handled by vis_flags
/:cl:

### CODE REVIEW

**Comment by LemonInTheDark** [comment]
I imagine this will break a couple things, but lets give it a shot yeah?

**Comment by Dennok** [comment]
Great, only one case where i see it break. 
Where you need overlay that has not master dir. 
But this one is not important.

**Comment by Rohesie** [comment]
Really good PR!

**Comment by Couls** [comment]
has been testmerged on bagil for a few days now without any issues

**Pull request merged**
