### PR TITLE
Prevents direct Del() calls

### PR DESCRIPTION
**Pull request by Cyberboss**
Blame @kevinz000

### CODE REVIEW

**Comment by kevinz000** [comment]
I feel targeted.

**Comment by alexkar598** [comment]
Now this brings up the question: Why the hell do we need code mesures to prevent admins who are supposed to know what they are doing from shitting up the server?

**Comment by Iamgoofball** [comment]
@alexkar598 Admins cant be trusted

**Comment by ExcessiveUseOfCobblestone** [comment]
> @alexkar598 Admins cant be trusted

**Review by vuonojenmustaturska — APPROVED** [review]

**Comment by ninjanomnom** [comment]
Calling procs is for debugging. A warning and ability to cancel would be fine but blocking the call entirely sits wrong with me.

**Comment by Cyberboss** [comment]
There's currently unpreventable ways to get references to admin ranks/datums this allows you to delete them

**Pull request merged**
