### PR TITLE
Selecting Multiple files with new map merger

### LINKED ISSUE #10300: New Map Merge is terrible
added in #9784

Running the Preparer works fine, but the merge tool you have to use afterwards is disgusting. You have to type in the full _map folder path every time, you then pick a SINGLE map and then afterwards the program shuts down, and you have to reopen it and then type in the _map folder path again and pick a new map. This makes editing multiple z-levels a horrible chore.

### PR DESCRIPTION
**Pull request by CorruptComputer**
Fixes  #10300

### CODE REVIEW

**Comment by Alek2ander** [comment]
Can you set ../../_maps as the default maps folder so you don't have to input that every time?

**Comment by CorruptComputer** [comment]
If I do that other code bases won't be able to port this, and if we ever change the path it will break this. But if this is what everyone wants I can do it.

**Comment by Jordie0608** [comment]
You could give it a short little config file and have it grab the path from that.

**Comment by CorruptComputer** [comment]
@Jordie0608 I was actually thinking about doing that.

**Comment by CorruptComputer** [comment]
All issues that people have brought up have been fixed.

**Comment by Cheridan** [comment]
Thank you kind person

**Pull request merged**
