### PR TITLE
Makes retards slightly more retarded

### PR DESCRIPTION
**Pull request by bobdobbington**
Adds the lines "I'VE GOT BALLS OF STEEL" and "NO I'M ONNA KILL YOU MOTHERFUCKER OLD STYLE." 

```
<hornygranny> ILL KILL YOU OLD STYLE YOU FUCKIN PRICK
<hornygranny> classic mem
<NikNak> I'll classic mem u
<bob_dobbington> that is a classic meme
<bob_dobbington> actually fuckin' someone should add that to the list of things retarded people yell
<Shadowmobile> Bob_dobbington code it yourself? It's one of the easiest changes to make
```

Mostly doing this so I can understand how to make a PR correctly. Has no gameplay balance implications that I can think of.

### CODE REVIEW

**Comment by optimumtact** [comment]
Sorry, I shouldn't tag things when I'm tired, I get the labels mixed up

**Comment by Cebasiz** [comment]
balls balls balls balls balls balls of steel

**Comment by Shapsy** [comment]
I will snatch every motherfucker birthday

**Comment by Anonmare** [comment]
Thermite can't melt R-walls
Nuclear OPs was an inside job

**Comment by optimumtact** [comment]
Please add I will snatch every motherfucker birthday

**Comment by Davdichan** [comment]
RIP AND TEAR

TIME TO GET SHREKT

RIGHT IN DA PUSSY

PEOPLE DIE WHEN THEY ARE KILLED

COME AT ME BRO

DO YOU EVEN LIFT

MY TRAP CARD

FOR THE EMPERAH

YOUR IN MY HOUSE NOW

**Comment by lzimann** [comment]
what the fuck is carbon dioxide should be in there aswell tbh

**Comment by Chocobro** [comment]
wow you can't say retard on github that's illegal!!!!!!!!!!!!!!!!!!!!!!

**Pull request merged**
