### PR TITLE
Lava Staff Projectile Sprite

### PR DESCRIPTION
**Pull request by Mercenaryblue**
For @KorPhaeron to use with his lava staff

Edit: Fine.

lavastaff

### CODE REVIEW

**Comment by GunHog** [comment]
>Sprite PR with no Pics

**Comment by fizzle7** [comment]
> Lava tile respects imaginary tile borders

**Comment by KorPhaeron** [comment]
This is a very odd looking projectile

**Comment by Mercenaryblue** [comment]
Its supposed to represent some weird magical lava magic, yes. It may be too big for a projectile, but I think the sprite matches the effect well.

**Comment by Mercenaryblue** [comment]
@KorPhaeron : Maybe these are more to your taste.

lavastaff2

**Comment by KorPhaeron** [comment]
I like the second set more

**Comment by phil235** [comment]
The fourth sprite of the animation is not correctly centered.

**Pull request merged**
