### PR TITLE
Added Wabbajack Storm wizard event

### PR DESCRIPTION
**Pull request by coiax**
:cl: coiax
add: Reports from the Wizard Federation imply that summoning magical
events to the station may cause a polymorphic storm. Nanotrasen would
like to remind its employees that magic is not real, and all wizards
should be arrested for fraud.
/:cl:

It's Polymorph All, but as a rare wizard event. Hope the wizard picked
some robeless spells, because it's gonna be tough when you're morphed
into a butterfly.

### CODE REVIEW

**Comment by lzimann** [comment]
not going to be annoying at all!

**Comment by coiax** [comment]
You've clearly grasped the point of Summon Events.

**Comment by lzimann** [comment]
yea but being polymorphed by a staff is already annoying, a poly all? it's bad

**Comment by Shadowlight213** [comment]
This is horrible.
If this triggers, it'll fuck the round beyond what a normal wizard round does. Poor AI is just going to get fucked in its core. Plus there's a chance people get polymorphed into things that can't call the shuttle or destroy the console so restart votes will be the only way to end it.
Hell, this doesn't even have any of the checks the other events do, so I hope you're not in space when it hits, or Rip you.

**Comment by jughu** [comment]
The funniest thing that can happen if ash drakes would be changed

**Comment by Arianya** [comment]
Possibly it would help to make this a sub-type of the radiation storm event? Maybe a shorter warning period, but that way its not just a "fuck everyone". Not sure if that would fix concerns re: AI though, but that might be an acceptable tradeoff since its a random event.

**Comment by Incoming5643** [comment]
Congratulations, you've earned the rare stamp: "designed a mechanic so absurdly powerful and disruptive that not even a wizard is a good enough justification for it to exist".

**Comment by ChangelingRain** [comment]
I.. yeah, holy shit. Incoming pretty much said it all.

**Comment by PKPenguin321** [comment]
rad storm idea mightve been good

**Comment by ChangelingRain** [comment]
As a side note, other things with that stamp include the supermatter sword, which was absurd if the wizard manages to get around the radiation, the veil render, which produced a singularity, and I don't think there's literally anything else

**Comment by Incoming5643** [comment]
The supermatter sword was never intended to be given to the wizard, Kor just tried to later

I'd say the multiverse war event also still falls into that catagory, also kor.

Forget who did the veil rendered... maybe kor. 🧀

**Comment by KorPhaeron** [comment]
I am a visionary

**Comment by optimumtact** [comment]
This is my coderbus and I like it

**Comment by Iamgoofball** [comment]
then why did you ban yourself

**Comment by optimumtact** [comment]
The rules apply equally

**Pull request closed without merging**
