### PR TITLE
Partial revert of 14756 (Pipes don't transport air across time and space

### LINKED ISSUE #14859: Moving a shuttle with atmos pipes on them breaks their connections.

### PR DESCRIPTION
**Pull request by MrsTonedOne**
revert of #14756 for causing #14859

Fixes #14859

Hopefully @duncathan can fix this before this pr hits 24 hours

### CODE REVIEW

**Comment by duncathan** [comment]
:+1: for being sane and only reverting the bug

I'll see what I can do tonight

**Comment by tkdrg** [comment]
`code/ATMOSPHERICS/components/components_base.dm:163:error: dealWithShuttleStuff: undefined proc`

**Comment by tkdrg** [comment]
Conflicts now

**Comment by tkdrg** [comment]
@MrStonedOne

**Comment by tkdrg** [comment]
@MrStonedOne

**Comment by MrStonedOne** [comment]
@tkdrg

**Pull request merged**
