### PR TITLE
Savefiles Interface

### PR DESCRIPTION
**Pull request by ACCount12**
Ported savefiles interface from NT. 

https://github.com/NTStation/NTstation13/pull/970

### CODE REVIEW

**Comment by WJohn** [comment]
OH MY GOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOD

**Comment by Jalleo** [comment]
There are a few issues in this.

**Comment by ACCount12** [comment]
There is a lot of issues in it now. Mostly realted to /tg/ codebase humans shit that wasnt in NT codebase.

**Comment by ACCount12** [comment]
Fixed shit i found. RTM i think.

**Comment by RemieRichards** [comment]
Wont this take a LOT of maintaining? you've gone through and correct quite a few special occasions, which people will have to remember to abide by in the future, if they end up creating something that needs special handling here.

I don't know if it's worth it.

Weigh in please.
@tgstation/commit-access 
@tgstation/owners

**Comment by ACCount12** [comment]
The only thing that is hard to maintain is humans S/L. Everything else just needs proper tmp vars use.

**Comment by Giacom** [comment]
It'll create a lot of problems in the future, like Remie said.

**Comment by Cheridan** [comment]
Well, problems are bad.

**Pull request closed without merging**
