### PR TITLE
Adds magboots to engineering SSUs

### PR DESCRIPTION
**Pull request by Spess-Rando**
:cl: Sligneris
add: Magboots have been added to engineering suit storage units
/:cl:

@Anonmare

### CODE REVIEW

**Comment by Anonmare** [comment]
>tfw the spacewind meme will finally be rest in rip in piece

**Comment by optimumtact** [comment]
Hey look more unjustified power creep 

again :-1:

**Comment by Sligneris** [comment]
Justified power creep, considering that magboots are crucial to engineers.

**Comment by optimumtact** [comment]
Except you haven't justified anything and if it's crucial to engineers why hasn't this change been made before?

**Comment by ExcessiveUseOfCobblestone** [comment]
in what way lmao

**Comment by Sligneris** [comment]
For starters, engineers are the ones taxed with fixing breaches and have more reason than anyone to work in environments with no gravity - be it station with deactivated grav gen or new areas made in space.

Breaches, for that matter, have a habit of depressurizing areas, which leads to space wind - you know, the thing that very much gets in the way of repairs.

At that point, magboots are crucial to engineering duties.

Before you bring up EVA, we all know that going to EVA as engineer tends to only result in shitsec unsheathing their batons on the basis of "muh restricted area". You know, kind of common knowledge when you actually play the game.

**Comment by Cebasiz** [comment]
>Except you haven't justified anything and if it's crucial to engineers why hasn't this change been made before?

what kind of fucking logic is this

by this logic any theoretical first attempt could be shouted down by this same fucking argument

by this logic nobody would ever be able to change the game

fucking what

**Comment by Supermichael777** [comment]
Wow you see right through autism logic!

want to be a maintainer?

**Comment by BeeSting12** [comment]
If magboots shouldn't be given to engineers, then deltastation's magboots should be removed.

**Comment by Shadowlight213** [comment]
With the sing removed, engineers have even less reason to need magboots.
Spacewind persisting was fixed ages ago. If you're having trouble with it, try turning off the vents.
I've never actually run into any problems with spacewind as an engineer with a hardsuit. If anything, it's just annoying that it throws items out of breaches and makes a mess.
Saying they are crucial to engineers is a joke.
If the gravity goes out, sec won't have a reason to stop an engineer from getting eva magboots.
Areas made on the same zlevel of a grav gen also get gravity, so unless you are doing deep space building (in which case just go get permission) you don't need magboots.

**Comment by Tokiko1** [comment]
What exactly is the reason why magboots need to be protected and locked away from engineers in the first place? If they are not needed, why keep them secured in eva? If they are vital for repairs, why keep them away from engineers? Or is this about low gravity combat or something?

**Comment by optimumtact** [comment]
@Cebasiz that would be the logic where it's not on me to justify why their change shouldn't be merged, it's their job to make the case for why their change should be made. It shouldn't take two or three posts by me to squeeze an explanation out of someone for why they are making a change

**Comment by Poojawa** [comment]
You can't plug a hole if you're constantly being moved by spacewind.

**Comment by DanteRU0312** [comment]
See literally no reason why this shouldn't be added, no one uses magboots much anyway, now they actually will spawn into department that at least needs them sometimes to plug holes without being sucked into them. And it's not like they're high-risk item anymore.

**Comment by PKPenguin321** [comment]
>magboots are crucial to engineers guys

They literally are not

**Comment by jughu** [comment]
Didnt in the past magboots spawn in the ssus

**Comment by Steelpoint** [comment]
In the past the CE spawned with a pair of standard Mag Boots in his SSU. However it was one day changed so that he spawned with a Advance Pair, and you could make normal Mag Boots from the autolathe.

I don't think standard engineers have ever had access to Mag Boots.

**Comment by jughu** [comment]
Im pretty sure they did but that may just be me

**Comment by PKPenguin321** [comment]
>You can't plug a hole if you're constantly being moved by spacewind

Actually literally not true

**Comment by XDTM** [comment]
If anyone should have magboots it should be engineers rather than them being semi-public in EVA tbh.

**Comment by coiax** [comment]
> If anyone should have magboots it should be engineers rather than them being semi-public in EVA tbh.

^

**Comment by Anonmare** [comment]
>ITT people argue that magboots will for engineers will literally destroy the game

Nobody uses magboots normally because nobody can fucking get them without being tased by security the moment they even sneeze at EVA. Plus it's consistency, the CE gets his advanced magboots and everyone else in his department get fuck-all.

@PKPenguin321 It's convenient, engineers don't have access to the air alarms by default so that means they either have to get the AI's attention or hack the air alarm which is an inconvenient step in repairing breaches. Magboots are only powercreep in the same sense that the Jnaitor's galoshes are powercreep, they slow you down (even when not activated) and take up a normal-slot in your bag - I can't see any way they're OP

**Comment by PKPenguin321** [comment]
Incorrect, they do not slow you down when off and there is no effective downside to wearing them over regular shoes

**Comment by PKPenguin321** [comment]
And as a rule of thumb, convenience is usually fine when it's done in the form of removing (remove interface lag, reduce UI clutter, remove a tool and merge its functionality with another, etc). "Convenience" done by adding stuff that already exists but now it's easier to get is just a sneaky way of buffing things without saying that you're buffing them, and more often than not is just powercreep

**Comment by Anonmare** [comment]
@PKPenguin321 M8 they do slow you down, you're thinking of the CE's shoes which have no downside.

**Comment by XDTM** [comment]
They don't slow you while off nor while on with no gravity. They only slow you down if you're using them as noslips.

**Comment by PKPenguin321** [comment]
You are simply wrong, slowdowns are only applied when the boots are on with working gravity. See: https://github.com/tgstation/tgstation/blob/aceb8cec79d96b35e50c05d3e8786bc00b41263f/code/modules/clothing/shoes/magboots.dm

CE boots apply 1 less slowdown when on than regular boots do, but regardless, there is no downside to wearing magboots at all times.

**Comment by KorPhaeron** [comment]
No thanks

**Pull request closed without merging**
