### PR TITLE
Nerfs acid blob again

### PR DESCRIPTION
**Pull request by Iamgoofball**
goddamn acid blob

### CODE REVIEW

**Comment by Stickymayhem** [comment]
muh melty

**Comment by pudl** [comment]
fix the typo

**Comment by Iamgoofball** [comment]
@pudl what word and where

**Comment by Kromgar** [comment]
Is it possible to make it so that polyacid blobs only target exosuits and hemlet slots?

That way they work as the counter space suit guys.

**Comment by GunHog** [comment]
Do not melee an acid blob. Wear a biosuit to stop it dissolving your ID, jumpsuit, eye, face, ear and Pocket slot items. I could make an upgrade kit for RnD that lets you apply a coating to gun and mining implements to make them unacidable.

**Comment by Kromgar** [comment]
That sounds like a good solution to polyacid blob. Perhaps make it require some silver and plasma or something akin to that?

**Comment by Iamgoofball** [comment]
Adding an acidproof coating item would definitely help, but if the blob pops in rnd there's no nope, and miners will be too busy fighting the blob to mine.

**Comment by GunHog** [comment]
If it pops in Science, of *course* you are boned. You could try building RnD somewhere else using Tech Storage and parts from Robotics before the blob gets too big. If a blob or pair of blobs strategically take out its largest threats, it is at a point where it deserves to win for being robust.

**Comment by Iamgoofball** [comment]
Good point.

**Comment by Iamgoofball** [comment]
Oh, this compiles by the way, travis just lost connection to a server during the boxstation compile and reported it as fucked.

**Pull request merged**
