### PR TITLE
Reflector Vest Now Protects Arms and Groin

### PR DESCRIPTION
**Pull request by nemvar**
## About The Pull Request

Makes the reflector vest also cover your arms.
Updates the sprite.

## Why It's Good For The Game

The reflector vest is one of the weaker armors the player has access to and additionally it is classified as a high risk item. Currently, it's purpose is basically to get antags to breach the armory so they can greentext.

Since most other armors will still be preferable to this, this function of the item doesn't change but it will just be a little more desirable for other reasons.

## Changelog
:cl:
balance: The reflector vest now has elbow protectors, protecting your arms both from the dangers of small falls, as well as deadly laser fire.
imageadd: Updated the sprite accordingly.
/:cl:

### CODE REVIEW

**Comment by MMMiracles** [comment]
doesn't that make it more of a jacket than a vest now

**Comment by nemvar** [comment]
It's still a vest, just with elbow protectors.

**Comment by Tlaltecuhtli** [comment]
ablative pants when

**Comment by habader** [comment]
ablative socks

**Comment by HomocidlePancakes** [comment]
You do realize that there is no reason to aim for the arms, right? If someone is wearing a vest you just aim for the head to bypass it, thats all.

**Comment by nemvar** [comment]
I do realize that. But sometimes shots miss, so it's still a small buff to a barely used item.

**Comment by ATH1909** [comment]
Can we make it cover a bit of the legs, too?

**Comment by HomocidlePancakes** [comment]
So a small chance I won’t hit head and then a 50/50 on reflect. This is so minor it won’t even affect anything. Just add reflector helmet already

**Comment by nemvar** [comment]
Reflector helmet gets added when I can be assed to sprite it.

**Comment by PKPenguin321** [comment]
I would personally bump the reflect chance to at least 50, maybe 60

**Comment by YakumoChen** [comment]
Besides the reflection, the actual armor values are pretty insane. Dunno why nobody actually wears it if they're expecting to fight anyone with energy weapons (like all of security)

**Comment by necromanceranne** [comment]
Because as Homocide pointed out you just need to aim for the head. Unless shots deviated it'll hit all the same. Better when they don't expect it because you coloured it differently with a spraycan.

**Comment by Denthamos** [comment]
Ablative bodysuit.

**Comment by GuyonBroadway** [comment]
Improved combined ablative vest with shoe guards and everything.

**Comment by necromanceranne** [comment]
It's just a morphsuit with sequins sewn onto it.

**Comment by ExcessiveUseOfCobblestone** [comment]
yummy sprite conflicts

**Comment by nemvar** [comment]
Boo! Sprite conflicts!

It's not like I actually care about this. Someone else can steal my sprite if they want to make this a thing, be warned, it looks stupid when you lose an arm.

**Comment by ExcessiveUseOfCobblestone** [comment]
floating arm pads are a feature of the game.

**Pull request closed without merging**
