### PR TITLE
Properly kills the goliath outside Survival Pod Ruins ruin

### PR DESCRIPTION
**Pull request by Sealed101**
## About The Pull Request
The ruin added way back in #17284 has a varedited goliath with 0 health.

image

In practice this goliath will not be dead or a one-hit-kill, as upon taking damage, it would revert to being at full health.

This PR replaces this goliath with a proper corpse, as well as adds a corresponding goliath corpse spawner.

## Why It's Good For The Game
Banishes the fake undead goliath to the otherworld.

## Changelog
:cl:
fix: The goliath that you may encounter outside of a Survival Pod ruin on Lavaland is now properly a carcass.
/:cl:

### CODE REVIEW

**Comment by newfren** [comment]
Wow I always thought the goliath was supposed to have killed the miner

**Comment by Sealed101** [comment]
> Wow I always thought the goliath was supposed to have killed the miner

judging by the trail of bloody footprints I'd say the goliath mortally wounded the miner before dying, causing them to bleed out in the pod

**Comment by ATH1909** [comment]
> > Wow I always thought the goliath was supposed to have killed the miner
> 
> judging by the trail of bloody footprints I'd say the goliath mortally wounded the miner before dying, causing them to bleed out in the pod

might be nice to still have the goliath there, but have it start at like 25 health or something

**Comment by BlueMemesauce** [comment]
> > > Wow I always thought the goliath was supposed to have killed the miner
> > 
> > 
> > judging by the trail of bloody footprints I'd say the goliath mortally wounded the miner before dying, causing them to bleed out in the pod
> 
> might be nice to still have the goliath there, but have it start at like 25 health or something

Wouldn't it just reset back to full health like what this PR was trying to fix? or does it actually work for numbers greater than 0

**Pull request merged**
