### PR TITLE
Switches Uzi sprites

### LINKED ISSUE #10164: Mini Uzi bolt is closed when ready to fire
Uzis are supposed to be open bolt, so the bolt should be open when it's ready to fire, and closed when it's not. Muh autism hurts because of this.

### PR DESCRIPTION
**Pull request by swankcookie**
fixes #10164
I know nothing about guns, so i'm taking @Thunder12345's word on this one. just switched the regular and -e- sprites.
:cl: Swankcookie
rcsfix:Uzis now look correct
:cl:

### CODE REVIEW

**Comment by swankcookie** [comment]
@WJohn there's no pictures because i didn't add or change any sprites. I literally just switched the empty and full sprites with each other.

**Comment by GunHog** [comment]
You did not bother to verify your changes?

**Comment by swankcookie** [comment]
what?

**Comment by GunHog** [comment]
Did you load a game locally and look at the Uzi's empty and filled state to make sure that the sprites are corrected? It is also a chance to check if your changes cause the Uzi to be completely invisible!

**Comment by swankcookie** [comment]
yes I did, despite the fact that I didn't re path or delete a single thing, so there's no way that that type of issue could have come about.  I don't think you realize what a tiny fix this was.

**Comment by Thunder12345** [comment]
You should probably have a changelog for this, or there's going to be people ahelping that their uzi was delivered without any bullets

**Comment by swankcookie** [comment]
I think you're overestimating how much people actually look at sprites

**Comment by KorPhaeron** [comment]
please stop bullying the poor guy over 2 pixels

**Comment by swankcookie** [comment]
This entire PR is so low-stakes, i'm actually a little of concerned that it's getting even this amount of attention.

**Pull request merged**
