### PR TITLE
Tail wagging is corrected to prevent incorrect emote text.

### LINKED ISSUE #68799: Using *wag to stop wagging says you're wagging your tail
## Round ID:
Tested locally.

## Reproduction:
Have a tail
*wag
Wag your tail
Decide to stop wagging
*wag
Wag your tail (but you stop)

<details>
<summary>Vid because its not too obvious whats going on</summary>

https://user-images.githubusercontent.com/70232195/181307827-69278985-6378-409e-9fa5-2afbe02618fe.mp4

</details>

### PR DESCRIPTION
**Pull request by orthography**
## About The Pull Request

Tail wagging is corrected to prevent incorrect emote text.

Wagging will prompt `wags their tail`

Wagging while currently wagging will stop the wag and state `stops wagging their tail`

## Why It's Good For The Game

Fixes downstream issues. ~Oh god I'm doing work for skyrat~

Fixes https://github.com/tgstation/tgstation/issues/68799

## Changelog

:cl:
fix: fixes tail wag emote stopping the wag.
/:cl:

### CODE REVIEW

**Review by MrMelbert — CHANGES_REQUESTED** [review]
If you wanna fix that issue look at `/datum/emote/living/carbon/human/wing/select_message_type(mob/user, intentional)` instead for an example of an emote that changes its messages based on the state of something, instead of making two emotes

**Comment by Jolly-66** [comment]
> Oh God I'm doing work for Skyrat

I will be bringing more issues upstream the more they manifest down there, pending I can replicate then :)

**Comment by waffielz** [comment]
agony

**Comment by NamelessFairy** [comment]
Personally I prefer this as a toggle, Melberts already covered the main reason

**Comment by Ryll-Ryll** [comment]
Why not just keep *wag as a toggle and have *stopwag that only stops wagging if you're wagging, and does nothing if you aren't?

**Comment by orthography** [comment]
> Why not just keep *wag as a toggle and have *stopwag that only stops wagging if you're wagging, and does nothing if you aren't?

Was using *stopwag to help with an issue downstream. I'll try and get the text to change and just do it that way instead.

**Pull request merged**
