### PR TITLE
New Cult Sword Sprites by Keekenox

### PR DESCRIPTION
**Pull request by ghost**
:cl: Keekenox
imageadd: cult sword looks amazing now!
/:cl:

I'll get some pictures shortly

### CODE REVIEW

**Comment by Wilchenx** [comment]
15$ well spent

**Comment by Armhulen** [comment]
@Wilchenx give me the weird plate armor you were showing earlier i'll throw it into my chaplain armor kits

**Comment by Armhulen** [comment]
image
image
image
image
image

**Comment by drderp3635** [comment]
For when you swing your sword like a one handed golf club

**Comment by Kromgar** [comment]
Wow... these are awful.


You can barely tell its a sword inhand it looks like a cane

**Comment by Armhulen** [comment]
@Kromgar i somehow screenshotted it every single direction with no crackling

**Comment by GunHog** [comment]
The sword itself is amazing! The in-hands could possibly be improved by making it point up instead of down.

**Comment by Armhulen** [comment]
Ping Keek on discord about it, i'll update sprites if i get them

**Comment by GunHog** [comment]
I am not able to post on the Discord, you will have to ask him yourself, unfortunately.

**Comment by improvedname** [comment]
@kromgar thats why they have blindfolds on silly!

**Comment by Lexorion** [comment]
The sword looks pretty neat but the inhands aren't that great. I just realized the cult sword is using the wrong inhands and I didn't fix it [with my pr](https://github.com/tgstation/tgstation/pull/34678) so it was still using the old ones, my bad! We could still use this one for the 2h cult sword since that really needs a new sprite more in my opinion.

**Pull request closed without merging**
