### PR TITLE
Adds the map Asteroid station.

### PR DESCRIPTION
**Pull request by lzimann**
Alright, hopefully I didn't mess anything up. 
This adds the asteroid map to the code.
I don't know if I need anything else to work with the map rotation.

[Feedback Thread](http://tgstation13.org/phpBB/viewtopic.php?f=11&t=4913)

Please let me know if I'm doing something wrong or there's any problem with the map!

### CODE REVIEW

**Comment by Iamgoofball** [comment]
same old story, same old song and dance

**Comment by MrStonedOne** [comment]
Alright. Map rotation is config based, so i'd need to add it.

Let's do a test run shall we!

**Comment by MrStonedOne** [comment]
Shuttle doesn't work

**Comment by Supermichael777** [comment]
the dock is the wrong size so its not compatible
expected
dir = 4;
 height = 11;
 id = "emergency_home";
width = 22
yours:
dir = 4;
height = 28;
id = "emergency_home";
width = 13

**Comment by Supermichael777** [comment]
also wrong orientation

**Comment by lzimann** [comment]
That was a mistake in my part. The map has a custom z2.dmm, which was bugged, but now it's fixed. Once I fix the cargo shuttle I'll commit the changes

**Comment by lzimann** [comment]
Everything is working now!

**Pull request merged**
