### PR TITLE
New skinne colors

### PR DESCRIPTION
**Pull request by goobliner**
## About The Pull Request

Adds 4 new skin tones. Speedmerg.

## Why It's Good For The Game

There are currently a whopping FOUR dark skin tones, as opposed to the eight light ones. This adds four new darker skin tones :)
<details>
<summary> Some super awesome screenshots </summary>
"Chestnut" mixed1

image
"Walnut" mixed2

image
"Coffee" mixed3

image
"Macadamia" mixed4

image

All of my friends!

image

</details>

## Changelog
:cl:
add: 4 New skin tones, hooray!
/:cl:

### CODE REVIEW

**Comment by carlarctg** [comment]
can you add hazelnut and peanut colors too, maybe cashew and pistachio

fck im hungry

**Comment by goobliner** [comment]
> can you add hazelnut and peanut colors too, maybe cashew and pistachio
> 
> fck im hungry

adding yummy skin tone :3

**Comment by optimumtact** [comment]
can you take a picture showing the full range of all tones next to each other?

**Comment by goobliner** [comment]
> can you take a picture showing the full range of all tones next to each other?

i can do that actually

**Comment by goobliner** [comment]
> can you take a picture showing the full range of all tones next to each other?

done and done, i think I'll make Wenge a little bit brighter though, less grey

**Comment by goobliner** [comment]
updated with new, less grey wenge

**Comment by Serxule** [comment]
skin tones that actually look good holy shit

**Pull request merged**
