### PR TITLE
Makes meteor mode spawn 6 times less meteors

### PR DESCRIPTION
**Pull request by tkdrg**
This shitty mode should kill the server slightly less now.
No, I did not test this at all. Kill me.

### CODE REVIEW

**Comment by bgobandit** [comment]
hbl.ogg

**Comment by Durkel** [comment]
You're going the wrong way, we need more server crashing meteors, not less.

**Comment by PKPenguin321** [comment]
make it like ragin' mages where it has a bullshit var
setting it to 0 (the default) makes it have the amount of meteors proposed in this pr
setting it to 1 makes it go back to the original amount of meteors
setting it to 2 makes it have fucking 30 or something

**Comment by tkdrg** [comment]
It would be pointless. The current amount lagged the server to death even after disabling atmos.

**Comment by PKPenguin321** [comment]
do it anyways yolo

**Comment by GunHog** [comment]
It is not fun removal if it causes @MrStonedOne to re-add meteor to the rotation!

**Comment by Jordie0608** [comment]
Does meteor mode even work?

**Comment by tkdrg** [comment]
Yes. Just ask HBL.

**Comment by Firecage** [comment]
Pretty sure it causing the amount of lag you mention is a bug, and not due to the amount of meteors.

**Comment by duncathan** [comment]
Are you kidding? Meteors are laggy as shit

**Comment by phil235** [comment]
Maybe we should fix the actual cause of the lag instead of hiding it?

**Comment by swankcookie** [comment]
so get rid of atmos?

**Comment by Aranclanos** [comment]
>Maybe we should fix the actual cause of the lag instead of hiding it?

**Comment by Iamgoofball** [comment]
what's the fucking actual cause of the lag you dipshits

**Comment by optimumtact** [comment]
spawning to many meteors

**Comment by Iamgoofball** [comment]
then why did we close the PR that lowers the amount of meteors spawned

**Comment by tkdrg** [comment]
> spawning 6 meteors per tick is not an issue guys

**Pull request closed without merging**
