### PR TITLE
Adds a new type of Experiment Scans: Machinery Scanning

### PR DESCRIPTION
**Pull request by Sealed101**
## About The Pull Request
This PR adds a type of experiment for scanning machinery built with different tiered stock parts. Simply scan a required machine with the specified tier of stock parts in it for it to count towards the experiment. The basic type of this scan will work even if only one part of the machine is of the required tier, which can help you trick others into believing that you _did_ upgrade it properly.
An alternative type of this scan will look for a specified stock part type in the machine, such as a micro laser of tier 3.
## To-do
- [x] proper implementation of this scan
- [x] ~~randomized contents? perhaps making some experiments ask for unspecified machines with certain parts?~~ base this experiment on scanning_points instead
- [x] spread out the new experiments across the techweb
- [x] balance it out and write proper desriptions/names

## Why It's Good For The Game
Promotes using the acquired T2-T4 parts outside of Engineering or Science departments, profiting the whole station in varying amounts. More excuses for you to scream at AI to open Brig or Medical. ~~Buffs~~ ~~Nerfs~~ _Burfs_ various tech tree speedruns. More work for scientists to do aside from scanning literal toilets.

## Changelog
:cl:
expansion: There is a new type of experiment provided by Nanotrasen: Machinery scanning!
/:cl:

### CODE REVIEW

**Comment by Nexofas** [comment]
Finally, something useful for the station also that opens tech tree.

**Comment by Kubisopplay** [comment]
Not pointless experiment? Absolutely illegal.

**Comment by Nexofas** [comment]
> Not pointless experiment? Absolutely illegal.

**Comment by LemonInTheDark** [comment]
Finally some good fucking content

**Comment by Sealed101** [comment]
definitely needs balancing and general overview, i have a lot of bias as an RnD main

**Comment by optimumtact** [comment]
> Finally some good fucking content

it's not that good honestly it's just a reheated item fetch quest which is exactly what we tried to take away from RnD originally.

**Comment by Sealed101** [comment]
> > Finally some good fucking content
> 
> it's not that good honestly it's just a reheated item fetch quest which is exactly what we tried to take away from RnD originally.

wasnt experisci's intent to add more department interaction and this is exactly that

**Comment by LemonInTheDark** [comment]
> it's not that good honestly it's just a reheated item fetch quest which is exactly what we tried to take away from RnD originally.

Frankly I've barely looked at it, I'm just happy someone anyone is doing experiments

**Comment by LemonInTheDark** [comment]
> wasnt experisci's intent to add more department interaction and this is exactly that

You read the design docs?

**Comment by Sealed101** [comment]
> 
> You read the design docs?

https://hackmd.io/@tgstation/HJCoL8MUw
interaction with facets of the station and the game, cooperation of the crew, says it right from the get-go
last time i checked waiting for miners to mine enough uranium to build a bunch of toilets was the only department interaction we'd see in rnd

as far as i know, active point generation was either research bombs, tesla coils or rad collectors and experimentor shenanigans with relics or research notes. yes it was a fetch quest and yes this pr can be seen a s a fetch quest but this time rnd leaves a positive impact on the stationon its wake in the form of upgrades to various machinery. and that is still better than building several objects only to boop them once with a scanner and deconstruct them afterwards. no lasting impact aside from a plasma wall or some radiation.

**Comment by optimumtact** [comment]
yes, but I was expecting more ambitious experiments

**Comment by LemonInTheDark** [comment]
There's also this, which is a bit older https://hackmd.io/@tgstation/Sy8W0nvv8#Research-and-Development-oranges

**Comment by Sealed101** [comment]
> There's also this, which is a bit older https://hackmd.io/@tgstation/Sy8W0nvv8#Research-and-Development-oranges

i did read it before, yes. that's why i was asking for input on this pr's techweb changes since some of the experiments can and should be turned into a requirement for the nodes instead of the discounts that they are right now. as i said, i have a lot of bias as and rnd player and i want more discount experiments to increase efficiency of the techweb's exploration but the experiments should be added in moderation as well as have their contents shuffled around to up the "difficulty" of the experiments. 

bottom line of this pr is: rnd goes places outside their autism dome of building random furniture for faster tools or mechs or whatever and interacts with the station as a whole a lot more. they would have to gain access to the machines either by screaming at AI, screaming at departmental workers, busting their way in or visiting tech storage and taking some machine boards to make the machine. scientists wandering around the station will inevitably interact with the round's ongoing troubles much, much more, be it cult or a revolution, a murderboner on the loose, a xenomorph outbreak, an adbuctor team snooping around or something as simple as choking your fellow man for a pair of insuls in the cafeteria. same goes for the positive interactions as well, since they improve the efficiency of the station as they complete these experiments, perhaps save some folks in need of help, leading to building more connections and player interaction.

> yes, but I was expecting more ambitious experiments

just let me figure out what works for fun and engaging experiments first. there is a subtype of physical experiments that could be used for stuff like autopsies or tool speed testings. it's a field i'm willing to dive into but i first need some data on whether the rnd playerbase will be willing to complete something as simple as a glorified fetch quest for their tech or not.

once again, i need suggestions and input on placing the new experiments across the techweb in such a way that it will promote doing the experiments across the station and benefit research efforts

**Comment by AMonkeyThatCodes** [comment]
you should walk before you run and I don't see any issue with a PR that integrates experi-sci into something that scientists should be doing anyways. All this PR does is reward people for doing one of the few tasks scientists should actually be performing and if we want more ambitious experiments someone should go add them to the hackmd. Nothing wrong with simplicity.

**Review by tralezab — CHANGES_REQUESTED** [review]
my only code quality concerns are with the list formatting, take a look

**Comment by tralezab** [comment]
also i'm planning on merging this for reasons codemonkey explained, this system was let out the gates expecting more content, which never came. in the future there will be far better experiments but we don't know when that's gonna come and we may as well improve what we have now with some decent but simple variety

**Pull request merged**
