### PR TITLE
Adds new signage for the AI upload, AI sattelite, telecomms, vault, and R&D Servers

### PR DESCRIPTION
**Pull request by CoffeeDragon16**
## About The Pull Request

Also maps these in, shuffles things around to make them fit. I was playing some other maps for the first time, and I noticed that if you're not familiar with the map it tends to be confusing what these rooms are at a glance.

I'm not too experienced with either mapping or spriting so if you have any tips, feel free to let me know and I'll update the PR.

image  image
imageimage

image image
 

## Why It's Good For The Game

More beginner friendly, and they're good atmosphere.

## Changelog

:cl:
add: New signage for the AI upload, AI sattelite, telecomms, vault, and the R&D servers.
/:cl:

### CODE REVIEW

**Comment by ShizCalev** [comment]
conflict

**Comment by CoffeeDragon16** [comment]
yup, out of the house for a few days so I can't resolve it until then

**Comment by CoffeeDragon16** [comment]
uh oh i did it again

**Comment by CoffeeDragon16** [comment]
i will reupload this on a new branch X_X

**Pull request closed without merging**
