### PR TITLE
Fixes Linters (Three Month Old PR Edition)

### PR DESCRIPTION
**Pull request by san7890**
## About The Pull Request

On the tin, we required usage of `/mob/living/carbon/human/consistent` sometime last month and linters were never reran on 48e36ef2c78dc1f19d2542f6e0181b6f8f4a1d2e (#69799), causing it to error out and skew.
## Why It's Good For The Game

CI is BROKEN I am going to SOB.
## Changelog
Nothing to concern players.

### CODE REVIEW

**Comment by ZephyrTFA** [comment]
and this is why we merge master and enable auto merge

**Comment by san7890** [comment]
NOT the same fix as #71862, that fixes a proc ref linter failing. This fixes another issue.

**Comment by Mothblocks** [comment]
@ZephyrTFA I don't understand?

**Comment by Mothblocks** [comment]
If you mean always update people's branches before auto merging, I would definitely disagree because that would clog CI queues like crazy, and also not actually solve the problem if you have multiple PRs being merged, since they're not relying on *each other's* CI, since they're not merged serially. If anything, you'd make the problem worse because of the queueing bottleneck.

**Comment by Mothblocks** [comment]
The only change I would maybe make is to be able to opt into notifications of master failing in a way that is heuristically not flaky. From what I can tell we're already extremely on top of it though.

**Pull request merged**
