### PR TITLE
Almost halves airlock auto close delay

### PR DESCRIPTION
**Pull request by LemonInTheDark**
## About The Pull Request

We go from a delay of 15 seconds, to 8.

This has cheesed me off for a long time. Airlocks should lock, not just
stay open for a quarter of a minute.

This'll help with excited groups that stay permenantly connected at
highpop because of a slowed ssair and doors opening and closing
constantly

Also effects door chasing. I'm honestly just kinda eyeballing this, it
might be a bit much. Even if this goes through could totally be tweaked

Even if this is too low, 15 is way too damn high.

## Why It's Good For The Game

Airlocks take ages to close, makes me sad
Honestly have a hard time articulating why, but it just feels so nasty
Can't find any reasoning for it, it's an r4407ism 

## Changelog

:cl:
balance: Airlocks will now autoclose in 8 seconds rather then 15
/:cl:

### CODE REVIEW

**Comment by Ryll-Ryll** [comment]
I'd consider this to be a pretty sizeable change to the game's balance/flow and would request you to expand on what this change is intended to achieve, and give more than `Honestly have a hard time articulating why, but it just feels so nasty` for that reasoning.

The first part of the PR brings up specific issues with atmos excited groups staying active for too long from a performance standpoint, but then also acknowledges that it'll have a (pretty big) effect on door chasing as well that isn't really expanded upon for whether the PR sees less chasing as a good change that improves the game itself or as a necessary sacrifice for improving performance.

Taking the time to close an airlock behind you after passing through it is an important extra step in keeping places secure, such that some locations like the brig have matching dual-airlocks that close when the other one opens as an added security feature on purpose. I'm not against this necessarily, but I'd like to know the split between how much of this is based on performance gains, versus how much is based on gameplay changes

**Comment by zxaber** [comment]
Almost every door I go through that has an access requirement, I will manually close behind me. I even do this as a borg, out of respect for the owneres of the room. They're open so long that you can follow someone in, steal almost anything you want, unwrench a machine, and drag it out before the door shuts.

This is a good change. Eight seconds gives plenty of time to slip in behind someone, without allowing them an (easy) free exit too.

**Comment by LemonInTheDark** [comment]
> I'd consider this to be a pretty sizeable change to the game's balance/flow and would request you to expand on what this change is intended to achieve, and give more than `Honestly have a hard time articulating why, but it just feels so nasty` for that reasoning.

I agree with you. I've been meaning to do something like this for a long ass time, but I could never find a good way to describe why I think it'll be good, I'll do my best to do that, but no promises. I'm not a good balance coder

> The first part of the PR brings up specific issues with atmos excited groups staying active for too long from a performance standpoint, but then also acknowledges that it'll have a (pretty big) effect on door chasing as well that isn't really expanded upon for whether the PR sees less chasing as a good change that improves the game itself or as a necessary sacrifice for improving performance.

I didn't make this change to effect chasing, but I realize it does impact it. 
I'm honestly not sure how big an impact this will be to it. It does make it harder. 15 seconds is a long time, and it gives people a lot of leeway.
I don't think chasing being a bit harder is inherently a bad thing, but I don't have a good enough sense for things to tell you how much this will change it.
I initially did this with 6 seconds, but that felt too short. Really am just kinda going by feel here.

> Taking the time to close an airlock behind you after passing through it is an important extra step in keeping places secure, such that some locations like the brig have matching dual-airlocks that close when the other one opens as an added security feature on purpose. I'm not against this necessarily, but I'd like to know the split between how much of this is based on performance gains, versus how much is based on gameplay changes

I've got two main reasons I want to change this. One is more a me thing, the other isn't.
1: When there's a lot of people moving through an area with active turfs, the doors they open and close tend to break and reset the related excited groups. This leads to a lot of nothing happening. Honestly this will need solving separately to do it properly, but it bugs me to see.
2: Airlocks, especially public ones, stay open for a long time. Long enough that they don't feel like airlocks. Leads to lines of open airlocks facing a room, don't like how that looks. This is kinda what I'm stuck on, I don't have a good way of describing why I don't like this. It just seems silly.

I agree with you about the security. 
Right now you can go a bit more then 5 screens at standard run speed before the door will close behind you. With this change that will become a bit under 3. It's definitely a smaller window for people to sneak in behind you but it's not too short.

I wish I could explain this better. Maybe this will help? doors set to 15, 8 and 6 seconds
dreamseeker_7Jb6n9lUkp

It just feels crummy.... Ahhhh IDK.

**Comment by Farquaar** [comment]
This will make opportunistic tatoring a bit more difficult. I know I've slipped in through open airlocks more than a couple times to snatch an item to use in nefarious ends.

**Comment by githubuser4141** [comment]
Since there's a wire you can pulse to close the door quicker as Willard pointed out, does this make that redundant or reduce the timer even further?

**Comment by LemonInTheDark** [comment]
image
It keeps the same delay

**Comment by Dorsisdwarf** [comment]
Do airlocks really have a 15 second auto-close? That seems weird, as an AI when I open doors for people they ALWAYS seem to close again within 1 or 2 seconds, and brig doors close in under a second

**Comment by Mothblocks** [comment]
Brig doors have the thingy that close themselves once the other door opens, you might be thinking of that @Dorsisdwarf

**Comment by Mothblocks** [comment]
That being said I think this is *okaaaaaaay*

**Comment by LemonInTheDark** [comment]
> > 2: Airlocks, especially public ones, stay open for a long time. Long enough that they don't feel like airlocks. Leads to lines of open airlocks facing a room, don't like how that looks.
> 
> This is kinda the point in a way to me--it means both that I know the path someone is taking, but also making it easier to juke someone by opening a door, and going out another (and closing behind me)

That's true, but you're often not chasing someone 15 seconds behind them

**Comment by LemonInTheDark** [comment]
Kinda interested in what it'd look like on tm, don't wanna make a mistake with it

**Comment by derekhearst** [comment]
You generally don't use airlocks on doors leading bedrooms and bathrooms either..

> This will make opportunistic tatoring a bit more difficult. I know I've slipped in through open airlocks more than a couple times to snatch an item to use in nefarious ends.

I agreee with this, doors that should be closing quicker should be manually closed, higher skill cap. 

Maybe another option would be to make airlocks not close if there is an item between the doors, and make the door close in 8 seconds. Would allow traitors to throw objects to keep doors open sneakily while also making it a bit harder to just run in without planning. If you are going with the all doors are airlocks then it makes sense that an object would interfere with the airlocks ability to close and seal.

**Comment by Mothblocks** [comment]
I couldn't observe any test merges but I'll just trust it.

**Comment by LemonInTheDark** [comment]
If it goes fucky it'd be fine to back out.

**Pull request merged**
