### PR TITLE
Synthflesh also works via vapor.

### PR DESCRIPTION
**Pull request by MarioWizard119**
## About The Pull Request

This PR makes synthflesh work through vapor, meaning it can be used with spray bottles and foam.

## Why It's Good For The Game

Consistency and quality of life.

## Changelog
:cl:
tweak: Synthflesh now also works via vapor.
/:cl:

### CODE REVIEW

**Comment by MrDoomBringer** [comment]
>Consistency and quality of life.

???
did you mean to type balance change

**Comment by wesoda25** [comment]
healfoam healfoam

**Comment by MarioWizard119** [comment]
I wouldn’t consider this something major balance wise, I just found it a little odd synthflesh didn’t work via foam and spray bottles. You can already do it through smoke, so I don’t see why it would hurt to have healfoam as well, for those who prefer slipping people rather than blinding them.

**Comment by MrDoomBringer** [comment]
i might just be low IQ but i had thought that healfoam was intentionally not a thing for some reason, but yeah i guess if you can already smoke-ify it than i don't see why not!

**Comment by Farquaar** [comment]
>Breathes in Synthflesh
>Lungs get clogged with meat
>Die

**Comment by fludd12** [comment]
aerosolized flesh, it does a body good. nothing like the smell of sublimated blood in the morning.

**Comment by spookydonut** [comment]
you had me at "for those who prefer slipping people rather than blinding them."

**Pull request merged**
