### PR TITLE
Gamemode Announcement Cleanup

### PR DESCRIPTION
**Pull request by actioninja**
## About The Pull Request

Secret is no longer given a wasted chatline just to tell you potential gamemodes that you might be seeing. It's not useful to new players since they won't know what it means, and it's not useful to veterans because they're going to be familiar with gamemodes anyways. Removing it lessens the giant wall of spam you get roundstart just a little bit.
Also some gamemode announce code was cleaned up, announce is no longer overridden instead of using the built in vars literally for that purpose.

## Why It's Good For The Game

Code cleanup.
Lessens start of round spam.

## Changelog
:cl:
tweak: Secret no longer has a roundstart chatlog saying that it is secret.
/:cl:

### CODE REVIEW

**Comment by Fikou** [comment]
it might be "metagaming" but i like knowing what gamemodes aren't gonna get rolled roundstart instead of checking with who the amount of players and then checking how much players each mode needs

**Comment by Twaticus** [comment]
> it might be "metagaming" but i like knowing what gamemodes aren't gonna get rolled roundstart instead of checking with who the amount of players and then checking how much players each mode needs

I believe this PR is talking about the line that says "The gamemode is: secret! " and not the line that says "Possibilities:  extended, secret extended, traitor , traitor+brothers, etc"

**Comment by kriskog** [comment]
No, he is removing the possibilities print too.

Very unnecessary change imo. This has a function, as the possible game modes change with player number and config changes.

**Comment by ninjanomnom** [comment]
This is configuration based and not static. I see no particularly good reason to remove the line.

**Pull request closed without merging**
