### PR TITLE
Holiday changes (actual effort edition)

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request
This moves the Indigenous Peoples' Day holiday to the date on which it is celebrated in Brazil and adds the National Day of Spain holiday (October 12) and the International Day of the World's Indigenous Peoples.
All three days have station prefixes, National Day of Spain has a greeting.
This also removes a unit test that was used for the old Indigenous Peoples' Day. The new Indigenous Peoples' Day doesn't use nth_week so it isn't needed anymore.

## Why It's Good For The Game
More actually decent holidays, less skubby holidays related to american politics

## Changelog
:cl:
add: Added National Day of Spain
add: Added International Day of the World's Indigenous Peoples
tweak: Replaced US Indigenous Peoples' Day with Brazillian Indigenous Peoples' Day 
del: Skub amounts in the codebase have been reduced by approximately 0.02%. 
/:cl:

### CODE REVIEW

**Comment by Tlaltecuhtli** [comment]
why do we need these unknown festivities in? i dont really care about corporations making up day of X to sell happy "_____" t-shirts or get some free ads on twitter, at least hot dog day has a ingame item to reference, while brazil??? spain???? indigenous????

**Comment by interestingusernam3** [comment]
>why do we need these unknown festivities in? i dont really care about corporations making up day of X to sell happy "_____" t-shirts or get some free ads on twitter, at least hot dog day has a ingame item to reference, while brazil??? spain???? indigenous????

why not

**Comment by Fikou** [comment]
sopa de macaco

**Comment by Time-Green** [comment]
Sinterklaas when?!??

**Comment by Time-Green** [comment]
Should probably keep it to international holidays, like Day of Worlds Indigenous people is. Adding Spain Day is gonna start an absolute shitstorm with every country wanting their piece. The only reason Independence Day is in is because there's an american majority

**Comment by wesoda25** [comment]
Stupid hill to fight on but who the fuck cares 500 years in the future?

**Comment by Farquaar** [comment]
> 
> tweak: Replaced US Indigenous Peoples' Day with Brazillian Indigenous Peoples' Day
...why?

**Comment by jacklecroy** [comment]
If people don't want "Indigenous Peoples' Day" then that's fine. I did it kind of in jest, because Columbus sucks, and I added Columbus day in the first place.

But nobody wants these random Brazilian or Spanish holidays.

**Comment by Jared-Fogle** [comment]
when a pr closes you're not supposed to just reopen it and hope for the best

**Pull request closed without merging**
