### PR TITLE
Gives the captain a spartan helmet

### PR DESCRIPTION
**Pull request by Kmc2000**
## About The Pull Request

Gives the captain a spartan helmet for L(eonidas)RP shenanigans.

## Why It's Good For The Game

This gives the captain a helmet that matches his suit instead of using the space helmet.

## Changelog
:cl: Kmc2000
add: The captain's locker now spawns with a Spartan helmet in it.
/:cl:

### CODE REVIEW

**Comment by FantasticFwoosh** [comment]
Does this come in red & black for the HOS?

**Comment by GuyonBroadway** [comment]
Sorry but this is the first thing that springs to mind.

https://i.ebayimg.com/00/s/MzAwWDI3NQ==/z/zp8AAOSwfcVUBo-g/$_35.JPG?set_id=2

**Comment by ShizCalev** [comment]
conflict

**Comment by optimumtact** [comment]
this is also just needless bloat

**Pull request closed without merging**
