### PR TITLE
Why does it have to be snakes? REDUX

### PR DESCRIPTION
**Pull request by Togopalis**
🆑 Togopal
add: Snakes! They hunt vermin on the station!
add: They can be purchased in cargo.
/🆑

Mice can be a problem in late round random events, and I figured releasing a bunch of snakes in maintenance would be a more long-term solution than constantly running around with a crowbar when you hear them.

Now with updated sprites!

(SORRY FOR REUPLOADING THIS, GITHUB WAS BEING AWFUL AND NOT LETTING ME MODIFY THE OLD ONE)

### CODE REVIEW

**Comment by Cyberboss** [comment]
Continued from #34706

**Comment by Anonmare** [comment]
Yay snek
Snek da best

**Comment by epicmemename** [comment]
add goombas next togopal

**Comment by Supermichael777** [comment]
Needs sprites, desperately
image

**Comment by Buggy123** [comment]
Inb4 a admin varedits to this:
```var/static/list/edibles = typecacheof(list(/mob/living/simple_animal/butterfly, /mob/living/simple_animal/cockroach, /mob/living/simple_animal/mouse, /mob/living/carbon/human/moth))```
Anyway +1 look forward to filling the station with snakes.

**Comment by Togopalis** [comment]
Supermichael the sprites have been modified to fit Armhulenn's new sprites they are no longer the placeholders.

**Comment by Armhulen** [comment]
@Supermichael777 but yknow if you make better sprites than mine (not hard so) i'm ok with replacing it

**Comment by Hatfish** [comment]
Next add mongooses to curb the snake population after all the rats have been killed.

**Comment by Armhulen** [comment]
@KomradeSpectre i checked and it was the new sprite?

**Comment by Iamgoofball** [comment]
Make curators have a forced snake phobia

**Comment by Togopalis** [comment]
Armhulenns gonna help me make that possible @Iamgoofball :-)

**Comment by Armhulen** [comment]
@Iamgoofball DUUUUUUUUUUUUUUUUDE WE THINK ALIKE THAT'S WHAT I PITCHED TO TOGOPAL LIKE THIS MORNING OR SOMETHING

**Comment by Togopalis** [comment]
OK GUYS DONT GET MAD BUT I HAVE TO MAKE A THIRD PR BECAUSE APPARENTLY I WAS USING A FORK FROM jULY 2017

**Pull request closed without merging**
