### PR TITLE
SM now processes only when there is more than 0.01 moles of gas present

### PR DESCRIPTION
**Pull request by SyncIt21**
## About The Pull Request

**1. The Changes**
a) If you are activating a supermatter shard/engine for the very first time, then you need to make sure the SM has above 0.01 moles of that reactive gas present to take effect.

b) During it's processing lifetime if the amount of moles of a gas falls below 0.01 moles then SM will not process it because it yields a negligible amount of energy and thus saves processing power.

**2. The Fix**
Fixes this runtime
```
[2023-05-08 13:50:30.327] runtime error: Division by zero
 - proc name: calculate gases (/obj/machinery/power/supermatter_crystal/proc/calculate_gases)
 -   source file: supermatter.dm,553
 -   usr: null
 -   src: the supermatter crystal (/obj/machinery/power/supermatter_crystal/engine)
 -   src.loc: the reinforced floor (169,154,2) (/turf/open/floor/engine)
 -   call stack:
 - the supermatter crystal (/obj/machinery/power/supermatter_crystal/engine): calculate gases()
 - the supermatter crystal (/obj/machinery/power/supermatter_crystal/engine): process atmos()
 - Atmospherics (/datum/controller/subsystem/air): process atmos machinery(0)
 - Atmospherics (/datum/controller/subsystem/air): fire(0)
 - Atmospherics (/datum/controller/subsystem/air): ignite(0)
 - Master (/datum/controller/master): RunQueue()
 - Master (/datum/controller/master): Loop(2)
 - Master (/datum/controller/master): StartProcessing(0)
 - 
```
Which can happen in near vacuum environments(like an turf exposed to space)

**3. The Qol**
SM will not waste processing power if there is less than 0.01 moles of gas to process.

Scrubbers are not always 100% efficient. they can leave very small traces of gases behind which you can only see if you VV analyze it
Screenshot (203)
But your gas analyzer will lie & tell you a different story
Screenshot (202)
So what happens when 0(so you thought) moles of proto nitrate comes in contact with the supermatter? You thought you were safe? Well.. ask Dan

https://user-images.githubusercontent.com/110812394/237053037-e979140e-aeac-4b68-ac24-a54fa3ea3979.mp4

No more rude surprises like this. If you expect vacuum to keep your supermatter inert(It never get's activated) it will now do just that. But if you activate the shard at any point then nothing can save you except a good setup

**Note:**
Please note that this does not suddenly make the SM safe AFTER it has been activated under vacuum, because once it does get activated vacuum or not it will delam without appropriate cooling, this is only usefull if you have a fresh supermatter shard that has never been activated and you want to safely install it in an new vacuum area, but once activated then there is no saving it if your setup is shit.

## Changelog
:cl:
fix: runtime when sm processes gases in vacuum
qol: sm will now get activated for the very first time only if there is more than 0.01 moles of a reactive gas present, so you can now safely install it in near vacuum
qol: sm will continue to process gasses only when there is above 0.01 moles of the gas present else it just ignores it
/:cl:

### CODE REVIEW

**Comment by SyncIt21** [comment]
@LemonInTheDark I'll be honest #75257 main purpose was to stop the SM from delaming so now  i focused only on that. Thoughts?

**Comment by Ghilker** [comment]
> @LemonInTheDark I'll be honest #75257 main purpose was to stop the SM from delaming in vacuum so now i focused only on that. Thoughts?

The SM should delaminate in vacuum and not only in space. If there is no air on the tile the crystal should take a lot of damage or release plenty of harmful gases

**Comment by Pickle-Coding** [comment]
Install it in a nitrogen chamber, not a void.

**Comment by Pickle-Coding** [comment]
Put crate in chamber, rails around it, then set coolant before opening. This is a code solution to an IC issue of bad engineering practice. It going on fire as a result of that is not an issue gameplay wise.

**Comment by SyncIt21** [comment]
> Put crate in chamber, rails around it, then set coolant before opening. This is a code solution to an IC issue of bad engineering practice. It going on fire as a result of that is not an issue gameplay wise.

So what happens to the railings and the crate after opening the crate & the SM get's activated? Will you have enough time to Un wrench them and drag the crate out of there before they get vaporized? That would be extremely dangerous and so the only solution would be to let them go to dust and now you have wasted iron in making rails & a perfectly good crate, Like why do you want player's to take this long route?

`This is a code solution to an IC issue of bad engineering practice`

What you are suggesting is exactly bad practise and advice, i would not recommend to anyone, This is a very minor change in gas processing behaviour with huge safety benefits for first time installation,

**Comment by SyncIt21** [comment]
> Rails prevent the shard from moving

Yes i know that, what i'm saying is they will get vaporized after the SM activates and so you have wasted iron. If the shard has an option to be wrenched we should be using that and not improvised solutions like this

> People voiding the chamber seems opposite to the design of the supermatter. The supermatter is dangerous and creates awkward situations, and that's part of the fun

There are plenty of ways to have fun delaming the SM AFTER it has been activated, Hell even while it's being installed in the void you can just shove someone into it and watch everything get blown to shit cause the void will not save you now. This does not take away any fun it only allows the fun to start sooner AFTER we get through to the initial step.

**Comment by SyncIt21** [comment]
@LemonInTheDark your thoughts on this?

**Comment by SyncIt21** [comment]
@jlsnow301 11 rounds of testing should be sufficient?

**Pull request merged**
