### PR TITLE
Revert "Fixed 2: Electric boogalo, gives lusty xenomorph maid reskin to DONORS (are you happy now)"

### PR DESCRIPTION
**Pull request by Niknakflak**
Reverts tgstation/tgstation#18545

@Iamgoofball 
@KorPhaeron 
@Cheridan 

Please allow headcoder cheridan to review this before closing

### CODE REVIEW

**Comment by optimumtact** [comment]
The next revert you open gets you github banned, do not war with a github maintainer

**Comment by Cheridan** [comment]
sorry, this is my fetish

**Comment by WJohn** [comment]
Officially sanctioned xeno queen maids.

**Comment by PKPenguin321** [comment]
Oranges is a wj alt???

**Pull request closed without merging**
