### PR TITLE
Arconomy Balance Pass 2: Market Tendency

### PR DESCRIPTION
**Pull request by ArcaneMusic**
Remember when making a brand for your own PRs was a bad thing?

## About The Pull Request

Revisiting and improvements upon #52744, in order to work out the kinks in how price inflation should be handled.
**Price inflation is now based upon averages, and is now uncapped from 5.**
The math for determining station price inflation has been adjusted, with the new math being determined off of averages. I was hoping balacing it with a nice even exponential scale was going to work out with some tweaks, but all in all that was too optimisitic of me so shoutout if you said I should probably move over to a scale of averages in the first pr because you were wiser than I was brash.

New formula is:
station_target_buffer (0) += 40 (every paycheck, growing over time to alow more money into the shift every paycheck.)
station_target = max(round(temporary_total / (bank_accounts.len * 2)) + station_target_buffer, 1) (Recalculated every paycheck)
inflation_value = max(round(((station_total / bank_accounts.len) / station_target), 0.1), 1.0)

This means that every shift will start at or above 2.0 inflation as a target, as station_total and target should be nearly the same minus the first paycheck, resulting in a relatively close value around 2.0, 2.2 on live, meaning you'll feel the effects of inflation early into the round, but early shift purchases will decrease future inflation values across the station going forward.

Inflation will decrease as crew spend more of their money, and will increase as more money is horded on station, making the amount of money for a bounty versus the amount of money floating around the station feel a lot more dynamic, as you'll feel the inflation from the beginning, and should see it drop more often then not later into the shift

**Civilian budget is no longer the worst budget to pay out from.**
The civilian budget now gains more credits based on the number of accumulated civilian bounties completed across the board. The old system was literally just a random 2500-500 credit number for the whole budget, now it properly scales better with the amount of effort being applied by the crew, and being the most heavily used civilian budget now, it makes sense for there to be more pocket change floating around when the crew actually does their jobs.
New formula is:
var/civ_cash = ((rand(1,5) + civ_bounty_tracker) * 500)

**Medical Civilian bounties are no longer chees-able in seconds.**
Wow, alright, so it  turns out with the advent of tier 1 cybernetics, you could powergame existing medical bounties in like, 3 minutes tops. Like, Christ we're talking speedrun material here, since they cost practically zero real metal and glass to print and could be turned in for peanuts. As a result, all printable organ bounties that have multiple tiers now only accept the 2nd and/or 3rd tier organs as a result, with a stipulation added to the bounty description. Organs that are only printable via the synthflesh organ fabricator have been left as is, because honestly it's rarer to obtain. In addition, the pool of medical bounties has been slightly widened with a new operating table and operating computer bounty, rewarding appropriately for their completion.

**Engineering**
Well, _uhhhhh_, originally I was going to make the engineering tesla bounty a constant cargo bounty and move it out of the engineering rotation, but I can see this is currently pointless, if any of the current tesla "fix" PRs gets merged I have the code here but in the meantime I'll take this one out of the PR in the morning.

Minor adjustments:

_Newscasters don't bleep at you all the time!_
Newscasters can now send silent updates. While most other regular updates and alerts will all be a regular alert, economic news updates won't spam your chatlog and remind you about the newscaster every 5 minutes, as some players felt that was getting on their nerves.

_The Market Crash event is now more severe in it's effect._
As a result of there being no cap to how high inflation can go now, market crashes are now 100 year market lows, with prices going exceptionally, EXCEPTIONALLY high until the market stableises, after which prices will update like normal. Market prices won't update passively until the event ends, and CRAB17s are capable of holding the market prices at their momentary values as well. Do with that what you may.

## Why It's Good For The Game

Lessons learned: Feeling the effects of price inflation in a regular round helps economy actually feel like a dynamic and interact-able aspect of a round. Bounties that you can't complete feel like a waste of 5 minutes, and less of a chalenge, but too easy of a bounty can feel like just the same kind of waste because it's too easy to profit off of. Also, sometimes, something just being fuckoff expensive, even if it's temporary, can help really set in stone the actual value that the player should know something's worth. 

I got some more feature-y stuff in the works going forward, but now that I have the tools to test and simulate a real-ish roundstart and crew income setup, I was able to agree on a pretty rough early-game model of how player money should look, more or less. Feels more satisfying, react to player spending, and now some of the easier, more problematic bounties have had a first pass done to keep them from getting too easy.

Events relating to the in-game economy are now going to feel more impactful to the round by locking prices down temporarily, with CRAB17 being more tangential to player funds being actively stolen, versus market crash where prices on station will now quickly grow to be unimaginably high for a short period. 

Plus, dear lord that newscaster spam was getting a bit bad, yeah.

## Changelog
:cl:
tweak: Medical bounties will no longer accept tier 1 cybernetic organs, but will still take tiers 2 and 3.
tweak: Newscasters no longer chirp in your ear every 5 minutes for a news update, but will still provide regular updates if you check the Station Announcements channel.
balance: Station inflation has been rebalanced, with roundstart balance staying in the ballpark of 200% until the first paycheck, and now using averages to determine how high inflation should be.
balance: Market crash and CRAB17 both lock down market prices of vending machines until their event ends.
balance: The Civilian Budget now gets more pay as more civilian bounties are completed over the course of the shift.
/:cl:

### CODE REVIEW

**Comment by optimumtact** [comment]
poggers

**Comment by RaveRadbury** [comment]
Are market announcements still going to fill up the standard announcement channel? Any chance that could be split off into its own "Financial News" channel?

**Comment by ArcaneMusic** [comment]
> Are market announcements still going to fill up the standard announcement channel? Any chance that could be split off into their own "Financial News" channel?

They're still in standard announcements, yes, although considering how few times it's used in a single round there's not much harm in leaving it as is.

**Comment by Rohesie** [comment]
Is this ready?

**Comment by ArcaneMusic** [comment]
@Rohesie Yup, testing has proven consistent here and the most unique change was just to the math values.

**Pull request merged**
