### PR TITLE
New sink sprites

### PR DESCRIPTION
**Pull request by nicbn**
image

## Changelog
:cl:
imageadd: New sink sprites.
/:cl:

### CODE REVIEW

**Comment by WJohn** [comment]
These are very nearly exactly the same sprites from #42200 with slightly lighter insides. They were disliked then too.

image

**Comment by nicbn** [comment]
The small sink one is basically the same as the other PR (with different shading in the interior). The sink_alt however is totally different, I just reused the palette.

I decided to atomize the PR back then and now I'm doing it. That way I can receive proper feedback for one sprite at the time instead of having to deal with a lot of sprites on the same PR.

Anyway, most of the criticism on the other PR was directed at the sink_alt (reworked) and the urinals and toilets (which aren't on this PR).

I also PRed these sprites at #45183, but decided to undo the mirror changes.

**Comment by cacogen** [comment]
sink_alt is definitely a better sprite, especially given it has proper directions. sink is a better sprite too but i don't like the inconsistency in its size between directions

**Comment by nicbn** [comment]
I don't get the inconsistency in size thing. Their top is the same but rotated, with one extra pixel along x and one less along y because of the front face being shown.

**Comment by optimumtact** [comment]
Can you fucking show the original sprite I can't be bothered to check the comparison

**Comment by nicbn** [comment]
image

image

**Comment by optimumtact** [comment]
They honestly look fine to me

**Comment by nicbn** [comment]
Orange man good

**Pull request merged**
