### PR TITLE
Fixes suiciding with anomaly cores

### PR DESCRIPTION
**Pull request by TetraK1**
## About The Pull Request
Previously suiciding with an anomaly core would swallow it like a radio signaller, but you wouldn't die when signalled.  Now you get gibbed when the anomaly core is signalled.

## Why It's Good For The Game
Current is disappointing.

## Changelog
:cl:Tetr4
fix: Suiciding with an anomaly core kills you properly
/:cl:

### CODE REVIEW

**Comment by Tlaltecuhtli** [comment]
would me more funny if once signaled it creates an anomaly

**Comment by FloranOtten** [comment]
> would me more funny if once signaled it creates an anomaly

I can already foresee people tactically signaling pyroclastic anomalies.

**Comment by OverlyGeneric** [comment]
> > would be more funny if once signaled it creates an anomaly
> 
> I can already foresee people tactically signaling pyroclastic anomalies.

image

**Comment by TetraK1** [comment]
Or better yet hyper-energetic flux waves

**Pull request merged**
