### PR TITLE
Makes chaplain soulshard non-reusable

### PR DESCRIPTION
**Pull request by coiax**
:cl: coiax
rscdel: The Chaplain soulshard can only turn a body into a shade once.
A released shade can still be reabsorbed by the stone to heal it.
/:cl:

### CODE REVIEW

**Comment by Faltnor** [comment]
That's garbage. Not being able to reuse a soul stone makes it essentially useless

**Comment by coiax** [comment]
You mean like how it was before it got unintentionally buffed?

**Comment by PKPenguin321** [comment]
^
Soulstone was never meant to be able to infinitely gib bodies

**Comment by Jalleo** [comment]
:+1:

**Pull request merged**
