### PR TITLE
Adds a new AI hologram

### PR DESCRIPTION
**Pull request by zxaber**
## About The Pull Request
Adds a Rat'var-themed hologram.
image

I'm not an artist so I just took the plushie and gave it an animation.

## Why It's Good For The Game
Those dirty blood-cultists get a Nar'sie holo, so we should get a Rat'var one too.

I don't want to changelog it, since it's just a fluff thing, but I will if I get told to.

### CODE REVIEW

**Comment by CRITAWAKETS** [comment]
Only mad lads would add something relating to Ratvar while clock cult stuff is probably getting purged.

This, is that mad lad.

**Comment by 81Denton** [comment]
Clock cult references are absolutely fine.

**Comment by CosmicPhoenix** [comment]
I finally have a reason to play AI

**Comment by OverlyGeneric** [comment]
> Only mad lads would add something relating to Ratvar while clock cult stuff is probably getting purged.
> 
> This, is that mad lad.

i think it was the gamemode that was being purged and not the spells, items, and shit.

spells might be unsalvagable if no one decides to make them usable without clockcult resource gimmick.

**Comment by CosmicPhoenix** [comment]
>> i think it was the gamemode that was being purged and not the spells, items, and shit.

Those got purged too. All that remains is the chaplain nullrod spear and it's copy in the Ratvar ruin.

**Pull request merged**
