### PR TITLE
changes reskin from ALT to CTRL_SHIFT

### PR DESCRIPTION
**Pull request by aKromatopzia**
## About The Pull Request

Alt clicking is nice and all but this SHOULD open the possibility to simply NOT reskin any clothing with toggles. (stuff like labcoat and jackets, which may exist after this pr)

## Why It's Good For The Game

Pt 1 of allowing the possibility of reskinnable, toggle-able clothing. Pt 2 is figuring out how to change the reskin procs to handle it properly

## Changelog

:cl:
code: reskinning interactions are done through ctrl-shift rather than alt.
/:cl:

### CODE REVIEW

**Comment by projectkepler-ru** [comment]
I can't believe we've reached the point where we're actually running out of key we can press

**Comment by aKromatopzia** [comment]
> I can't believe we've reached the point where we're actually running out of key we can press

it's because reskin is on alt click and I want to figure out how to make togglable toggle suits

**Comment by SmArtKar** [comment]
if we're moving it from alt click, wouldn't ctrl alt click be more intuitive?

**Review by Ghommie — CHANGES_REQUESTED** [review]
I think each item should be able to have the reskin option assigned to a different key. This could be fairly easily done by adding a new variable and some checks.

Anyway, I think you deserve an apologise since I haven't reviewed this PR until now.

**Comment by Ghommie** [comment]
Well, it seems like you aren't going to finish this anytime soon, so I'll close it for the time being.

**Pull request closed without merging**
