### PR TITLE
Nerfs Slaughter Demon

### PR DESCRIPTION
**Pull request by ghost**
They are now slower, but get a temporary speed boost upon exiting blood
(good idea Lumi). Maybe they'll be a bit more ambush oriented instead of charging down the halls killing everyone.

They now have 200 health instead of 250.

### CODE REVIEW

**Comment by daman997** [comment]
remove demon cap 2015

**Comment by Robustin** [comment]
Not sure how fast Speed = 0 and Speed = 1 are, is 1 the same speed as regular crew?

**Comment by KorPhaeron** [comment]
Speed 0 is crewspeed, Speed 1 is how fast you move with a RIG suit on

**Comment by Supermichael777** [comment]
so still fast enough for a yolo doge but not a rush.

**Pull request merged**
