### PR TITLE
Nerfs Chaplain smoke book.

### PR DESCRIPTION
**Pull request by LanCartwright**
:cl:
add: Lesser smoke book to Delta and Metastation
del: Normal smoke book from Delta and Metastation
tweak: Civilian smoke book now has a 360 max cooldown (from 120) and halved smoke output.
/:cl:

### CODE REVIEW

**Comment by coiax** [comment]
Open after freeze.

**Comment by LanCartwright** [comment]
Robustin opened one earlier.
I opened this on the presumption it was okay; I'll lock this if that is locked due to freeze.

**Comment by coiax** [comment]
"removals are okay in the freeze" was a mistake.

**Comment by KorPhaeron** [comment]
Should have gone with "maintainers are allowed to make a judgement call and disable an uncounterable feature that makes a classic game mode unplayable during the freeze" yeah

**Comment by coiax** [comment]
An feature that's been present for how long? And it's suddenly an issue during the freeze? :/

**Comment by Bawhoppen** [comment]
I thought we allowed map makers to allow their maps to play out how they wanted?

**Comment by Robustin** [comment]
Better than nothing but you're gonna get meme'd by the freeze now @LanCartwright.

I agree the loopholes are all silly, but I also think feature freezes/issue tracking are done poorly in general. We need the same attitude about issues that you all developed about stale PR's. It's an unmanageabely long list because of all the "we could call this a feature and nobody would ever care" and "niche issue that has never been reproduced in over a year" made it difficult to track down what's even worth fixing.

Examples of "who gives a fuck" issues that I gathered in under 3 minutes:

https://github.com/tgstation/tgstation/issues/11620
https://github.com/tgstation/tgstation/issues/12215
https://github.com/tgstation/tgstation/issues/13670
https://github.com/tgstation/tgstation/issues/13006

**Comment by LanCartwright** [comment]
I hate feature freezes, hence why generally speaking I don't open issues.

**Comment by Bawhoppen** [comment]
Feature freezes are dumb. We should use the merge token system again.

**Comment by coiax** [comment]
Merge token system is easily gamified to fix simple issues in order to get a token, which defies the whole point.

**Comment by Bawhoppen** [comment]
How is it not better than people not fixing any issues?

**Comment by Niknakflak** [comment]
>I don't open issues because of freezes

Nice.

**Comment by Aloraydrel** [comment]
that'll teach them

**Comment by Bawhoppen** [comment]
No really though, I thought we allowed map balance and how it plays out to be decided by the mapper?

**Comment by Metacide** [comment]
Well, I played a bit today and saw @Robustin powergaming to the max as a traitorling.

When we already have that much terrible shit we could always start with that and get to low-hanging-fruit like the chaplainspell later. I'm actually more in favour of the crew having stuff like the smoke spell to counterbalance the crazy excesses of some antags.

**Comment by XDTM** [comment]
The chaplain can be an antag as well, along with the gibstone and the smoke spell. Why smoke, anyway? I feel like they should have some 'holy light' spell that illuminates the area around them, instead.

**Comment by KorPhaeron** [comment]
It's smoke because that was (and probably still is) the most harmless wizard spell available when metacide mapped it in.

It's also less outright magical than the others, something a stage magician could pull off

**Comment by KorPhaeron** [comment]
Anyway this PR is pretty reasonable but please wait until the freeze is over

**Comment by Robustin** [comment]
Reopen it reeeee

**Comment by LanCartwright** [comment]
Thanks Raz.

**Comment by Bawhoppen** [comment]
Still no reason for this except hugbox

**Comment by Robustin** [comment]
Shh. Smoke spam is fucking terrible.

**Comment by coiax** [comment]
What happened to freeze PRs being put in the timeout bin.

**Comment by optimumtact** [comment]
it's applied according tomaintainer preferences I supppose

**Comment by KorPhaeron** [comment]
One week wait since it was opened during freeze

**Comment by LanCartwright** [comment]
7 days has past kor

**Comment by Robustin** [comment]
Finally speedmerge goooo

**Pull request merged**
