### PR TITLE
New -> Initialize

### PR DESCRIPTION
**Pull request by Cyberboss**

### CODE REVIEW

**Comment by Armhulen** [comment]
Why is new bad

**Comment by duncathan** [comment]
we don't have control over when/how it is called, like we do with initialize

**Comment by Armhulen** [comment]
?!

**Comment by JJRcop** [comment]
New is called when an object is created, we can't block that. We created the Initialize function, and we can control that.

**Comment by RemieRichards** [comment]
That's not the benefit of ```initialize()```
The benefit of initialize is that it happens once all atoms have been created (```New()```'d), so you don't have to run any timers or delays to sync objects with their neighbours (Smoothing, Linked machines, etc.)

New and Initialize() happen at the same time after the maps have fully loaded.

```
new /type/path(loc) -> init() (hidden proc call, sets all the object's vars to the definition values) -> New() -> Initialize() (this last step is delayed if the map is still loading)
```

**Comment by Cyberboss** [comment]
As this may also confuse some people, the INITIALIZE_IMMEDIATE statement
kind of overrides what @RemieRichards says as it forces Initialize() to be
called from New() 100% of the time. However, we still change it to
Initialize() for the sake of codebase standardization.

**Comment by Qustinnus** [comment]
it also allows us to join before everything is loaded afaik so it means we don't have to look at our dream daemon for 5 minutes wondering if it crashed or its just loading very slow

**Review by ninjanomnom — APPROVED** [review]

**Pull request merged**
