### PR TITLE
Adds explaining the rationale behind your PR as a requirement in contributing.md

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
Why I think this would be good for the game: Lots of pull requests are just things randomly being added, taken away, or having their balance tweaked without much of an explanation from the person making the PR. If you can't write even a couple sentences justifying your change, the game might not need it. 

**I think the burden is often on maintainers to prove a PR is bad, rather than than the person making it to prove it is good, and this might help shift things slightly.**

### CODE REVIEW

**Comment by karlnp** [comment]
Oh thank god.

**Comment by RemieRichards** [comment]
@KorPhaeron do it yourself? it's in the repo...

**Comment by TechnoAlchemisto** [comment]
🎉

**Comment by MrStonedOne** [comment]
Nope, I hate formats and templates, if this goes thru i'll just spam prs to remove it.

**Comment by optimumtact** [comment]
We're perfectly happy to ban you from the repo if you do.

**Comment by MrStonedOne** [comment]
well ya, it stays out of the way. it is not a question you answer where both question and answer show up to other viewers.

that is what i hate, where the pr body looks like a interview transcript.

**Comment by KorPhaeron** [comment]
There isn't a required format for explaining why your PR is good, it's just a reminder so we don't have to deal with "I didn't know" for the dozens of different contributors we get each year.

**Comment by MrStonedOne** [comment]
@KorPhaeron that doesn't change the fact that the prompt, asking you to explain the pr, will show up on the pr as well.

**Comment by MrStonedOne** [comment]
I will oppose it as long as it has that

**Comment by optimumtact** [comment]
But you literally put the changelog example in, which I have to delete for the vast majority of the pr's I make!

**Comment by MrStonedOne** [comment]
That isn't a prompt, it isn't a question, it's not the same fucking phrase repeated over and over and over again on every pr i read while reviewing them.

**Comment by MrStonedOne** [comment]
look at this

https://github.com/tgstation/tgstation/issues/140

this was the old issue report template, 

it objectively made it harder to read issue reports, and reading the same fucking prompt over and over again while reading issues got annoying and everything looked stupid.

I'm not returning to those days.

**Comment by optimumtact** [comment]
There you hypocrite, it's invisible to everyone but the PR author

**Comment by MrStonedOne** [comment]
Thank you.

**Pull request merged**
