### PR TITLE
Allows paper airplanes to be vareditted to always hit someone in the eye

### PR DESCRIPTION
**Pull request by ShizCalev**
:cl: ShizCalev
tweak: Paper airplanes can now have their hit probability adjusted by badmins.
add: Added syndicate paper airplanes. They are rather robust and are guaranteed to hit someone in the eye.
add: Added The Art of Origami to the syndicate uplink. This allows you to fold weapons grade paper airplanes. It will also allow you to catch paper airplanes when you have the ability enabled.
/:cl:

### CODE REVIEW

**Comment by lolman360** [comment]
i didn't know i needed this before now

**Comment by 81Denton** [comment]
Amazing

**Comment by ATH1909** [comment]
Nice.
Do they unfold into normal paper?
We should totally add them as a nuke op or traitor item. How many TC should each syndicate paper airplane cost?

**Comment by ShizCalev** [comment]
@ATH1909 Yes they unfold into normal paper.

**Comment by ShizCalev** [comment]
@Bombpants Was planning on adding that in another PR, actually.

**Comment by Therapist1** [comment]
i didnt know my tc trade request would go this far, but im frankly flattered that the syndicate thought my tactical origami was good enough to be industrialized

**Comment by ShizCalev** [comment]
wip status.

Turning it into an uplink bundle which gives you a box containing a book that teaches you "The Art of Origami", and 5 pieces of paper to test out your new skills.

Knowing the "Art of Origami" will give you a toggle-able action button allowing you to MASTERFULLY fold perfectly aerodynamic (and robust) paper airplanes. 

Having the ability toggled on will also allow you automatically catch other paper airplanes if your hand is empty.

Should have it done by night's end, only have to sprite the icons for the action button.

**Comment by PKPenguin321** [comment]
could put a plane or two into the throwing weapons box in the uplink

**Review by Cyberboss — DISMISSED** [review]

**Comment by Cyberboss** [comment]
14 seems kind of steep, why not 6-8?

**Comment by ShizCalev** [comment]
what @k-k-karma said.

**Comment by ExcessiveUseOfCobblestone** [comment]
don't mess with me or you're going to get hit with the likes of a thousand paper cranes anon

**Pull request merged**
