### PR TITLE
[TEST MERGE THIS] improves halloween immersions

### PR DESCRIPTION
**Pull request by Tlaltecuhtli**
:cl: 
sound: doot
/:cl:

this post gave me inspiration https://tgstation13.org/phpBB/viewtopic.php?f=23&t=19910&view=unread#p447288

### CODE REVIEW

**Comment by Ziiro** [comment]
https://www.youtube.com/watch?v=hzPpWInAiOg

**Comment by evsey9** [comment]
default

**Comment by Tlaltecuhtli** [comment]
proof its not a web edit http://take.ms/O6gpt

**Comment by Arianya** [comment]
This isn't even spooky beyond being about a dead boring meme.

👎

**Comment by subject217** [comment]
tlal learn how to rebase so your prs don't have 5 gorillion web edited merge commits please

**Pull request closed without merging**
