### PR TITLE
Adds more random letters to posibrain.dm

### PR DESCRIPTION
**Pull request by JJRcop**

### CODE REVIEW

**Comment by Shapsy** [comment]
It's quickly becoming obvious why the player reference ban was enacted in the first place

**Comment by xxalpha** [comment]
You could have at least separated GUN and HOG in that list, kek

**Comment by Anonus** [comment]
We can do this without SIX COMMITS sheesh.

**Comment by xxalpha** [comment]
Merge commits don't count for statistics.

**Comment by Metacide** [comment]
Neat :+1:

**Comment by GunHog** [comment]
I am loving this, seriously!

**Comment by GunHog** [comment]
And now there is one.

**Comment by Cheridan** [comment]
>It's quickly becoming obvious why the player reference ban was enacted in the first place

oops

**Pull request merged**
