### PR TITLE
Frees tonto from hornygranny's grasp

### PR DESCRIPTION
**Pull request by optimumtact**
Merge immediately this is a game breaking fix

### CODE REVIEW

**Comment by Thunder12345** [comment]
No player references

**Comment by optimumtact** [comment]
It's not a reference, it's a bugfix

**Comment by PKPenguin321** [comment]
@KorPhaeron *this* is the kind of PR that needs a "MEME PR" tag

**Comment by Aloraydrel** [comment]
Upvote

**Comment by duncathan** [comment]
dammit citrus you fucked up
use double quotes next time

**Comment by KorPhaeron** [comment]
@optimumtact 

Please fix this up so I can speedmerge it, thanks

**Pull request closed without merging**
