### PR TITLE
Firing pins update

### PR DESCRIPTION
**Pull request by ACCount12**
- You can replace test range firing pins with any other pin.
- Added self-destruction to pins. Pin with self-destruction option will explode it's gun after failed check.
- Clown pin can replace any other pin. Honk!
- Added ultra clown pin. A gun with ultra clown pin is useful for clown and useless for everyone else.
- Added DNA pin. This pin checks owner's UE. Poke someone with this pin or just fire a gun first time to set it's DNA.
- Ultra clown pins and DNA pins have self-destructing subtype.

Clown pin, ultra clown pin, DNA pin and all self-destructing pins are adminspawn only. Maybe i should add a clown pin to clown's backpack?

### CODE REVIEW

**Comment by Xhuis** [comment]
not bad

**Comment by Fayrik** [comment]
>Clown pins.
>Replacing pins.

Dear god, why.

**Comment by WJohn** [comment]
It still needs to be possible to manually remove these things, or at least be able to replace any of them with any other (ideally this should take a moment).

**Comment by ACCount12** [comment]
@Fayrik, because traitor trying to fire a stolen captain's laser gun only to hear HONK HONK HONK is really funny.

@WJohn, isn't every pin being removeable ruining idea behind pins? RnD gun lords would farm toy guns, remove real pins from them and use these pins. Or print plasma cutters to farm pins, or print syringe guns, or everything else. And every single security officer would replace auth pins in looted syndie guns with loyality pins.

**Comment by WJohn** [comment]
No, you can't actually pull pins out right now. Once you add one, it's stick that way.

**Comment by ACCount12** [comment]
And syringe guns, plasma cutters, kinetics and floral guns. And laser tag guns, because connecting a real laser to laser tag vest is just too fun. And magic crystals from nothing wand from costume vending. And...

**Comment by Fayrik** [comment]
What if the regular clown pins were constructable in R&D, requiring a tiny bit of bananium ore?
The concept of an ultra clown pin still worries me, though.

**Comment by ACCount12** [comment]
Regular clown pin is meant to be clown's joke item. It's useless for everything besides making gun permanently unuseable.

**Comment by Fayrik** [comment]
Yeah, I understand that, I'm just considering, since it's potentially able to disarm an entire nuke-ops team, if it requires bananium ore to produce then it's got some kind of balance.

**Comment by ACCount12** [comment]
It's easier to just space nuke-ops team's guns. I could add a clown pin for bananium to RnD, but then it would be glorious ULTRA CLOWN PIN!

**Comment by optimumtact** [comment]
>That's how /tg/ coderbus works.

Great thanks, I really appreciate that

**Comment by Jordie0608** [comment]
changelog

**Comment by hornygranny** [comment]
clown pin is not getting merged

**Comment by optimumtact** [comment]
@hornygranny why? it just makes a gun unuseable? Seems fairly harmless

**Comment by hornygranny** [comment]
being able to break any gun at any time for any reason is not really a good thing

**Comment by ACCount12** [comment]
These clown pins are unused. Not being spawned in any way besides adminfuckery.

**Comment by ACCount12** [comment]
And why breaking guns is that bad? You can space or crush them anyway.

**Comment by ACCount12** [comment]
honk!

**Pull request merged**
