### PR TITLE
Posters refactor

### PR DESCRIPTION
**Pull request by coiax**
- Posters now use a simple type-per-poster definition, rather than some
large global lists requiring sprite numbers to be the same as entries in
a list.
- Putting a specific poster on a map now simply means putting the
specific type that you want, rather than var editing (often
unsuccessfully).
- There are random all-posters, random contraband posters, and random
official posters for mappers too.
- Ripped posters are now their own type.
- The potential to make additional classes of posters has been left
open, I'd like to move a bunch of the advertisement posters to their own
category, and clean up the "official" category to be more obviously
on-brand. But that's for another PR.

- [x] Get all the maps updated with the posters

:cl: coiax
experiment: Mappers now have an easier time adding posters, and specifying whether they're random, random official, random contraband or a specific poster.
del: Posters no longer have serial numbers when rolled up; their names are visible instead.
/:cl:

### CODE REVIEW

**Comment by RemieRichards** [comment]
Jesus christ, finally.

**Comment by Arianya** [comment]
> Jesus christ, finally.

> Fails to compile

RIP Remie

**Comment by coiax** [comment]
It compiles, but it's likely failing because I need to update the rest of the maps.

**Comment by RemieRichards** [comment]
^

**Comment by coiax** [comment]
FUCKING MAP MERGER ISN'T WORKING

**Comment by coiax** [comment]
@xxalpha could you investigate the map conflict merge please? You said something was wrong with it.

**Comment by xxalpha** [comment]
Nothing is wrong with them but did you map merge afterwards?

**Comment by xxalpha** [comment]
Also how up to date is your map merger?

**Comment by coiax** [comment]
My map merger is as updated as the rest of my codebase. And I map merged afterwards for everything. I think. Was I supposed to map merge again after using the map conflict fixer on Metastation?

**Comment by xxalpha** [comment]
Yes

**Comment by coiax** [comment]
Okay, that seems... better.

**Pull request merged**
