### PR TITLE
fashion is my passion

### PR DESCRIPTION
**Pull request by pudl**
:cl:
rscadd: Adds normal security headsets to security lockers
/:cl:

### CODE REVIEW

**Comment by chanoc1** [comment]
neat

**Comment by pudl** [comment]
dont emoji me or my son ever again

**Comment by Aloraydrel** [comment]
My wifes son laughed

**Comment by pudl** [comment]
pls merge

**Comment by pudl** [comment]
merge this shit

**Comment by pudl** [comment]
how is this controversial

**Comment by pudl** [comment]
MERGE IT ALREADY

**Comment by AlexanderUlanH** [comment]
Won't this result in fashion-savy sec officers' being flashbanged?

**Comment by KorPhaeron** [comment]
>Won't this result in fashion-savy sec officers' being flashbanged?

Yeah that's the biggest problem with this. It removes most sources of flashbang protection from the map.

That's more a problem with flashbangs being an awful AoE gearcheck though

**Comment by pudl** [comment]
@KorPhaeron this doesnt remove anything. the headsets are just in the locker, officers still spawn with bowmans and there are still bowmans in the locker

**Comment by KorPhaeron** [comment]
Oh okay I can't read

I'm not sure why this is controversial then

**Comment by AdamElTablawy** [comment]
i didn't even read the pr or look at the code to see that it's completely harmless but it says something about security and adding so i'm going to automatically :-1: 

all jokes aside why is this controversial

**Comment by KorPhaeron** [comment]
Clutter

**Pull request merged**
