### PR TITLE
Fixes slot machines having a giant rainbow flashing "FUCK" overlay on them

### PR DESCRIPTION
**Pull request by tralezab**
## About The Pull Request

Title says it all. WHY ARE THESE IN ECONOMY.DMI?

### CODE REVIEW

**Comment by SuperNovaa41** [comment]
Bad PR

**Comment by tralezab** [comment]
fuck
YOU

**Comment by tralezab** [comment]
I HEARD THERE'S A DIFFERENT PR UP FOR THIS

**Comment by LemonInTheDark** [comment]
dupe of https://github.com/tgstation/tgstation/pull/58482? I think?

**Comment by celotajstg** [comment]
Good idea about moving to computer.dmi, I will update my PR with that.

**Pull request closed without merging**
