### PR TITLE
Changelings can now speak Alien

### PR DESCRIPTION
**Pull request by ghost**
i mean cmon, changelings are alien creatures, so why can't they understand other languages of alien nature

:cl: Thefastfoodguy
add: Changelings can now speak Alien
/:cl:

### CODE REVIEW

**Comment by ChangelingRain** [comment]
Changelings are aliens, but not xenos.
Changeling == Alien
Alien == Xeno
??
!
Changeling == Xeno?
X!
Changeling =/= Xeno

**Comment by MoreRobustThanYou** [comment]
@ChangelingRain Still, wouldn't changelings be able to grasp the concept of an "alien" language quicker?

**Comment by ChangelingRain** [comment]
Maybe if they could transform into xenos.
But no.

**Comment by Xhuis** [comment]
Transforming into xenos, you say? 🤔

**Comment by Steelpoint** [comment]
If Humans can't understand xeno language by default, why would any other species?

You don't automatically know how to speak Spanish if you've only known Danish you're entire life.

Besides, Changlings and Xenos tend to have a mutual understanding to not get in the way of one another, since Changelings can resist any facehugging attempt and self-revive, and vice versa Changelings usually get no benefit from attacking Xenos.

**Comment by RemieRichards** [comment]
No to this.

**Comment by XDTM** [comment]
Make absorbing xenos give you hivemind

**Comment by kevinz000** [comment]
fucking why mrty just fucking why man

**Comment by FantasticFwoosh** [comment]
The actual title pr is...

- Changelings speak all languages (including alien/fringe languages)

Because this is the direction i see @MoreRobustThanYou 's changeling PR's taking from here on out

**Comment by KorPhaeron** [comment]
We've had three maintainers say no now and its very strange logic so I think its denied

**Comment by KorPhaeron** [comment]
@XDTM 

That would be cool

**Pull request closed without merging**
