### PR TITLE
Pride Pins Resprite

### PR DESCRIPTION
**Pull request by axietheaxolotl**
## About The Pull Request

image

ooh ahh ah
## Why It's Good For The Game

idk is it? (it looks better, so yes)
## Changelog
:cl:
imageadd: new pride pin obj sprites
/:cl:

### CODE REVIEW

**Comment by Jacquerel** [comment]
I'll be honest I kind of think the circular ones are cuter, and these look absolutely massive as a 32x32 sprite

**Comment by W4rd3nn** [comment]
Erm... Poggers i think.

**Comment by CameronWoof** [comment]
Definitely a quality improvement, but also absolutely massive as a sprite.

**Comment by axietheaxolotl** [comment]
you don't see them on the ground very often so i do not care

**Review by Imaginos16 — APPROVED** [review]

**Comment by JohnFulpWillard** [comment]
> you don't see them on the ground very often so i do not care

that's what this is respriting though, no?

**Comment by Jacquerel** [comment]
> > you don't see them on the ground very often so i do not care
> 
> that's what this is respriting though, no?

The flag with the circle on it, furthest to the right.

**Comment by optimumtact** [comment]
pride rugs

**Comment by Wallemations** [comment]
The intersex flag definitely needs a fix to the perspective on its circle, otherwise These look Great

**Comment by Fikou** [comment]
pride carpet

**Review by ZephyrTFA — CHANGES_REQUESTED** [review]
Those sprites are just not working for me. They look like rugs and not pins and clash with the style of literally everything else

**Comment by CRITAWAKETS** [comment]
ayo, pride poptarts
that said, isometric perspective. that's a big "don't do that" in tg spriting

**Comment by Jolly-66** [comment]
gay poptarts

**Comment by BlueMemesauce** [comment]
Why not just fix the colors of the original ones? They look way more like pins

**Comment by NicoDeLuna** [comment]
I like the circular better

**Pull request closed without merging**
