### PR TITLE
Adds new hairstyle - Short Bangs 2

### PR DESCRIPTION
**Pull request by Hardly3D**
## About The Pull Request
Adds a new hairstyle called Short Bangs 2.
The hairstyle is basically an edit of the existing double buns, except the hair buns themselves are removed.

https://github.com/tgstation/tgstation/assets/66234359/38fe3b09-c42b-43e6-9e30-949428aab506

## Why It's Good For The Game
More customization, variety and character flavor is great. Double buns itself is a good hairstyle but some may not like the hair buns out of personal preference or that it can look weird on non-human species like felinids.

## Changelog
:cl: Hardly3D
add: Added new hairstyle: Short Bangs 2
/:cl:

### CODE REVIEW

**Comment by Hardly3D** [comment]
Oh snap, I'll see on some GBP

**Comment by EricZilla** [comment]
That should be an imageadd not add, but I thiiiink gbp shouldn't block a sprite PR
If I am wrong a maintainer will kill me at high noon

**Comment by Wallemations** [comment]
Honestly why don't we just have hair cut into front/back sprites that you can mix and match

Either way sure it's fine

**Review by Wallemations — APPROVED** [review]
I think it looks fine but I can't remember if we're allowing hair additions again or not

**Comment by san7890** [comment]
> I think it looks fine but I can't remember if we're allowing hair additions again or not

if you change your mind later then feel free to revert this PR

**Pull request merged**
