### PR TITLE
Make intercoms great again!

### PR DESCRIPTION
**Pull request by ghost**
Ports sexy intercom textures from a paradise PR they didn't merge for some ungodly reason.  https://github.com/ParadiseSS13/Paradise/pull/6548

:cl: More Robust Than You & Xhuis
imageadd: make intercoms (look) great again!
/:cl:

also this contains (unused, currently) textures for intercom frames/opened 

there are currently 3 versions, I will implement the one that the most people like

### CODE REVIEW

**Comment by DoctoreMad** [comment]
Well I'm 99% sure that out intercomms are better.
Can you show what those look like in-game?

**Comment by MoreRobustThanYou** [comment]
You mean this ugly thing? GROSS!

**Comment by Repukan** [comment]
That's not ugly, I'd fuck it

**Comment by DoctoreMad** [comment]
I meant show how YOURS looks like in-game.

**Comment by MoreRobustThanYou** [comment]
Oh, ok

**Comment by MoreRobustThanYou** [comment]
Also, I think this SHOULD be compatible with the intercom building PR, as I also moved the textures for intercom frames / opened intercoms in, too.

**Comment by ChangelingRain** [comment]
Sort of an improvement, but the blue is classic.
Compromise; make the green frequency screen use the old intercom's blue colors?

**Comment by Xhuis** [comment]
This is compatible, but the sprite for the intercom frame is in a different file so I'd have to swap it out if this is merged. No biggie, though; it works.

Gonna have to agree with some of the others here though; I kind of prefer the old ones. I'm not sure how a palette-swapped version would look, but it might be an improvement over the old in that case if it kept the same blue color.

**Comment by WJohn** [comment]
This isn't really much better at all. All this changes is the screen and I personally prefer how ours look. Perhaps that's only because I'm used to our current ones.

If you're gonna change these, please resprite them completely to make them 3/4th and higher quality.

**Comment by MoreRobustThanYou** [comment]
Here's how it looks in-game: 

IN GAME GREENNESS


I am still willing to change it blue...

**Comment by DoctoreMad** [comment]
Well I don't have much faith in that but try it.

**Comment by MoreRobustThanYou** [comment]
It's not as light blue as the intercom, but still blue. Lemme get a gif of the blue texture...

**Comment by MoreRobustThanYou** [comment]
Also, everything else has been getting resprited, why not the intercoms?

**Comment by MoreRobustThanYou** [comment]
Here (it's not actually that slow, the GIF recorder just slowed the game to a crawl FPS-wise)

**Comment by Xhuis** [comment]
Looks kinda like a BSOD. I think going with a turquoise is my favorite idea.

**Comment by MoreRobustThanYou** [comment]
*autistic screeching because I have to resprite them all again* I have a headache. Lemme do this later.

**Comment by Xhuis** [comment]
If you want, I can probably do it really quickly. Paint.net lets me palette swap in three clicks.

**Comment by dannno** [comment]
green is better

**Comment by MoreRobustThanYou** [comment]
@Xhuis Sure. I just put the blue version in the repo... I got no sleep last night. At all. I just watched videos of shitty robots.

**Comment by ChangelingRain** [comment]
Blue as in the same blue as the old intercom. 
This blue. The blue in the picture you posted.
this blue. this one.

**Comment by MoreRobustThanYou** [comment]
Ok...

**Comment by MoreRobustThanYou** [comment]
@Xhuis you wanna do it with paint.net wizardry or naaa

**Comment by Xhuis** [comment]
Sure! Nothing better to do. Give me a bit.

**Comment by MoreRobustThanYou** [comment]
Thanks...

**Comment by Xhuis** [comment]
👍

**Comment by nicbn** [comment]
Use GIMP instead of Paint.Net your heretic

**Comment by MoreRobustThanYou** [comment]
isn't gimp like 200 MB, though?

**Comment by nicbn** [comment]
200 MB is not that large, SS13 repo is 1GB

**Comment by Xhuis** [comment]
I got my setup and I'm stickin' to it.

**Comment by MoreRobustThanYou** [comment]
I prefer paint.net, too. Simpler to use.

**Comment by Xhuis** [comment]
intercom
Here's what it looks like without any further touch-ups. I like it a lot better than the other two versions. [Here's the .dmi](https://puu.sh/wsnk8/620fda7e22.dmi); just right-click and Save Image As.

**Comment by dannno** [comment]
the green is definitely better tbh

**Comment by Xhuis** [comment]
To each their own.

**Comment by MoreRobustThanYou** [comment]
ya know what, here's a poll https://www.strawpoll.me/13266200

**Comment by DoctoreMad** [comment]
Why not just make a poll like "X emoji for 1 intercom, Y emoji for another" so people can't proxy it?

**Comment by Xhuis** [comment]
😂 👌 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯

**Comment by MoreRobustThanYou** [comment]
@DoctoreMad why the heck would anyone proxy a poll on which texture for an intercom in autistic spessmens they like

**Comment by WJohn** [comment]
why not actually resprite the intercomms completely instead of just a minor change that doesn't really improve it very much?

**Comment by RemieRichards** [comment]
>poll is about the colour of the new one
>not whether you want this trainwreck in the first place

Disappointing.

**Comment by Xhuis** [comment]
People are free to like it, just like you're free not to. No need to belittle them for it.

**Comment by MoreRobustThanYou** [comment]
If you DON'T like the texture, what could be improved?

**Comment by MoreRobustThanYou** [comment]
Don't thumbs down without telling me why... :(

**Comment by Xhuis** [comment]
People don't give reasonable feedback here. It's much easier to hop on a bandwagon than it is to tell the other people (and yourself) why you're doing it.

**Comment by MoreRobustThanYou** [comment]
also, @Xhuis, on your texture, it's kinda hard to see the frequency/volume... thing. I had to zoom in and look real close to see if it was actually there. It doesn't contrast enough.

**Comment by Xhuis** [comment]
I can see it pretty much fine. Because it's just one color, it should be really easy to change to something else if it's too bothersome.

**Comment by MoreRobustThanYou** [comment]
I can only see the top of the pulse

**Comment by Tacolizard** [comment]
dood you can't upvote your own pr dood

**Comment by MoreRobustThanYou** [comment]
it's better than letting the echo chamber of "REEE IT'S DIFFERENT DOWNVOTE DOWNVOTE" win

**Comment by MoreRobustThanYou** [comment]
also i've noticed that @Xhuis's texture kinda fits the with the new resprites of many of the machines

**Comment by Bawhoppen** [comment]
Here's a superior sprite they use down at Citadel:
dreamseeker_2017-06-23_14-52-02

They also have APCs, air alarms, etc in the same style

**Comment by dannno** [comment]
Citadel's version does look much nicer, it would be good for someone to port those.

**Comment by MoreRobustThanYou** [comment]
I'll be honest, that doesn't seem too /tg/-y.

**Comment by MoreRobustThanYou** [comment]
Also, why does everyone hate this?

**Comment by Xhuis** [comment]
People hate change.

**Comment by dannno** [comment]
what does "/tg/-y" mean

**Comment by dannno** [comment]
it's not about hate, but we're already making a shift towards 3/4 and those citadel sprites conform to that.

**Comment by Vivalas** [comment]
Pretty subjective, I like the current classic intercoms.

**Comment by DoctoreMad** [comment]
@MoreRobustThanYou 

>why the heck would anyone proxy a poll on which [something seemingly unimportant]

[Snicker]
[Laugher]

**Comment by nicbn** [comment]
I don't like animated things in walls, they take too much of the attention of new players, and even older ones. I'd like very much if we had the intercom static for off and animated when any of the speakers or mic is on.

**Comment by RemieRichards** [comment]
@Xhuis it was the fact that the only poll literally doesn't let you say no to this garbage.
if you're going to bother doing a poll, do it right.

**Comment by Iamgoofball** [comment]
@RemieRichards 

"poll isn't asking the question I want it to ask so therefore it's bad"

**Comment by dannno** [comment]
>I don't like animated things in walls, they take too much of the attention of new players, and even older ones


???????
nonsense

**Comment by Vivalas** [comment]
The problem with the poll is that it doesn't ask whether or not people actually like the new intercom style, but rather the colorations of the new intercom people like. The point being made here is the poll has no option for "I don't like either, leave the old one in."

**Comment by WJohn** [comment]
I am not happy with these proposed sprites. If you actually resprite them in 3/4th style AND make them look better than what we have now? Then you can ask me to re-open this.

**Comment by CosmicScientist** [comment]
Would thwee quarters still look good when it's on a wall below you?

**Comment by RemieRichards** [comment]
@Iamgoofball Dude, even you're not retarded enough to actually think that way.

**Comment by Iamgoofball** [comment]
>people arguing about which variation of the suggested sprite
>ok fine here's a poll on the variations that are available
>WTF THIS ISNT A POLL TO REMOVE IT ENITRELY????

**Comment by MoreRobustThanYou** [comment]
@RemieRichards I would like to note, the the new sprites look more... futuristic. The old, crap one, looks less futuristic, as the blue circular thing is probably some speaker thing. In the future, speakers are tiny but loud!

**Comment by kyrahabattoir** [comment]
You should have allowed multiple poll choices, that's the only way to gauge which option has the most popularity.

**Comment by Ausops** [comment]
as far as sprites that need replacing go the intercom wasn't too high on that list

**Comment by KorPhaeron** [comment]
Art man said no

**Comment by RemieRichards** [comment]
@MoreRobustThanYou a bit unfair of me to respond to you (since with this locked, you can't respond back), but SS13 isn't strictly about "futuristic" a lot of the original style and charm was the kind of future people predicted in the 80s, <i>retro</i>-futuristic.

**Pull request closed without merging**
