### PR TITLE
Adds googly eyes for animated mimics

### LINKED ISSUE #3522: animated objects are hard to visualize
is that briefcase a mob or it's just a briefcase? Is it biting me in that chat spam of animated objects? nobody knows!
They need some overlay or something to indicate that they are mobs. Afterall it's magic, it could be an aura or something

### PR DESCRIPTION
**Pull request by tkdrg**
The eyes also follow their targets.
Fixes #3522

WARNING: HERE BE CODERSPRITES
2015-10-25-143933_1366x768_scrot

### CODE REVIEW

**Comment by Cheridan** [comment]
its beautiful

**Comment by Alek2ander** [comment]
:eyes:

**Comment by Incoming5643** [comment]
Rare is gonna sue

**Comment by Shadowlight213** [comment]
:+1: best feature

**Comment by Giacom** [comment]
:eyes: :+1:

**Comment by optimumtact** [comment]
:eyes: this is the greatest!

**Comment by PKPenguin321** [comment]
:+1: long overdue
also :eyes:

**Comment by Razharas** [comment]
Damn that looks silly

**Comment by Aranclanos** [comment]
>tfw no aura

**Pull request merged**
