### PR TITLE
Buffs Lionhunter Damage and Range

### PR DESCRIPTION
**Pull request by generalthrax**
## About The Pull Request

- Increases damage modifier to 2 from 1.33, bringing up the Lionhunter's charged shot from 40 to 60 (closer to a mosin)
- Increases max range to do a charged shot from 16 to 30
- Increases how far you can use the scope component so you make use of the new max range
- Uncharged Lionhunter shots are unchanged (still 30)

## Why It's Good For The Game

The Lionhunter is originally described in the blade heretic PR as being able to charge to deal "massively increased damage" but in practice it doesn't seem very potent. The damage increase for charging goes from 30 to 40, which is just barely enough to crit unarmoured targets if you hit someone in the chest or head with every shot, and can't crit armoured targets at all, assuming you even land all chest / head shots and not limb shots at the current max range of 16

Which is also being increased because it has a scope component that is fairly unhelpful because it only gives you an extra 2 tiles of range and was much longer before scopes were changed

With the damage increase you should be able to fairly reliably crit armoured targets like sec officers with 3 shots and regular crew in 2, but with the ammo capacity its not enough to kill a target outright. So blade heretics will have a more potent weapon this far up the tree, but from testing shouldn't be too SILLY

If @MrMelbert wants some things to be adjusted I will happily oblige

on a separate note ive never opened a pr or touched github in my life please dont hurt me

## Changelog

:cl:
balance: Lionhunter on charge now has a damage modifier of 2 instead of 1.33
balance: Increased max range of charged shot from 16 to 30
balance: Increased scope modifier so you can use the new max range
/:cl:

### CODE REVIEW

**Review by MrMelbert — APPROVED** [review]
Might be better to only increase damage up to 50 and increase armor penetration to compensate but this is worth a try regardless

**Comment by the-orange-cow** [comment]
I have never once seen this weapon used in any way.

**Comment by EuclidianGeometer** [comment]
IF i had to guess, the idea was that you hurt someone, they get away, the lion hunter rifle lets you finish them off. but in practice i don't think that works out, so this buff seems pretty reasonable.

**Comment by carlarctg** [comment]
Nobody will ever use this gun.

1. It's overcomplicated (reading the info about it makes you dizzy)
2. You need to blow an additional knowledge point to even get spare ammo for it, which still needs annoying things to find
3. It needs a ballistic gun, of which there are very few obtainable, none easily, and the obtainable ones are better than it, generally.
4. It's situated in the tech tree literally right before ascension, meaning that getting the knowledge is actively a hindrance to you. Especially when by the time you're about to ascend you can definitely feel the crunch and need to hurry up, be it from the shuttle or security heat, there's never any good excuse to waste four minutes scrounging for the ingredients.

**Comment by generalthrax** [comment]
> Nobody will ever use this gun.
> 
> 1. It's overcomplicated (reading the info about it makes you dizzy)
> 2. You need to blow an additional knowledge point to even get spare ammo for it, which still needs annoying things to find
> 3. It needs a ballistic gun, of which there are very few obtainable, none easily, and the obtainable ones are better than it, generally.
> 4. It's situated in the tech tree literally right before ascension, meaning that getting the knowledge is actively a hindrance to you. Especially when by the time you're about to ascend you can definitely feel the crunch and need to hurry up, be it from the shuttle or security heat, there's never any good excuse to waste four minutes scrounging for the ingredients.

Yeah thats exactly why I'm doing this. Another PR moved this lower down in the tree so I'm hoping that + this making it a little more desirable would make it OCCASIONALLY picked, at least. 60 might seem high to some people but at the max range you hit a lot of limb shots which are lower damage (50) for... some reason. Also little fun fact, you can use the russian revolver for the gun in the ritual.

**Comment by nukularpower** [comment]
Honestly I can't see why blade needs this at all - they are bad enough without a sniper rifle on top of all the other silliness

**Comment by Jackal-boop** [comment]
you know whatt time it is? yeah its gun heretic time

**Comment by MrMelbert** [comment]
> Honestly I can't see why blade needs this at all

bullets are small and fast knives

**Pull request merged**
