### PR TITLE
AI sat remap 2: electric boogaloo

### PR DESCRIPTION
**Pull request by WJohn**
Same deal as last time, though with some minor remapping to make it significantly more secure.

This is still before the feature freeze, damnit! I've waited 10 days for a merge and then CONFLICTS.

### CODE REVIEW

**Comment by GunHog** [comment]
Still smells like Mettaton :+1:

**Comment by xxalpha** [comment]
:+1:

**Comment by swankcookie** [comment]
The freeze started 12 hours ago, and already is being broken... or is this not counting as it's a re-PR?

**Comment by Cebasiz** [comment]
is remapping a feature

it's not really a feature doe it's a remap

or maybe the definition of "feature freeze" is just a lot wider than i'm thinking but w/e

**Comment by WJohn** [comment]
I'm gonna go ahead and say it doesn't count, this was done 10 days before the freeze.

**Comment by GunHog** [comment]
Remake PRs that were broken due to conflicts are okay to PR again during the freeze.

**Comment by Cebasiz** [comment]
oh, i should comment on the satellite itself probably

i like it alot more than the current one. aesthetically it looks nice and defensively it's an improvement.

i've noticed very recently that there are way more traitors always trying to make me dead, and the current satellite simply does not cut it. it's an entirely non-issue to c4 in through the walls and throw an EMP on the APC, which blows out all the turrets in the place.

you can get in and kill the AI with a minibomb or two in like literally 5 seconds. since space suits are now easy to come by (due to no longer roundstart bolting EVA, etc) getting out there on the external wall is not actually a difficult task anymore.

i frequently die in the first 15 minutes where before that was exclusively an op thing.

they always use the same wall too. i imagine someone figured out a way to do it and now everyone learned via copycat.

anyway, more defenses are nice to have. i don't think it will unbalance things too badly. as it is there are now usually many traitors that need to kill the AI, rather than one due to goofjectives (i think?)

anyway yeah pls merge thanks.

**Comment by Aranclanos** [comment]
this doesn't touch code, is not relevant to me for the code freeze

**Comment by swankcookie** [comment]
those are turrets flanking that glass walkway?

**Comment by WJohn** [comment]
Yes, all those fuzzy patches are turrets. They've had bugged map maker icons for a long time now. The turrets in there have disablers while on stun mode.

**Comment by duncathan** [comment]
Map changes have historically been exempt from the freeze; worry not

**Comment by GunHog** [comment]
Why are the turrets and cameras gone? I can see someone whining about the turrets, but why the cameras? Visibility is the most important thing to an AI, and without those, this satellite has less than the old one!

**Comment by Jalleo** [comment]
I agree with Gun Hog on camera part.

**Comment by WJohn** [comment]
I was told to remove the turrets by razharas, because they were griff worthy. Instead there's an extra layer of r-walls added to make up for it. I can re-add the cameras though.

**Comment by WJohn** [comment]
So like can this get merged sometime this century please? It's been two weeks and I've addressed the balance concerns.

**Comment by GunHog** [comment]
Poor WJ :(

**Comment by ChangelingRain** [comment]
I don't like it, though, it looks distressingly dongish and I dislike several of WJ's piping/wiring choices, though I guess "being shitty for ventcrawling" is a WJ theme.

**Comment by duncathan** [comment]
what's wrong with the current one

**Comment by KazeEspada** [comment]
Bulge the center, and remove the windows and I will give it a :+1:. Also the center being larger and more open will help remove the dong like shape.

**Comment by swankcookie** [comment]
Why remove the windows? That walkway seems like half of the redeeming quality of the re-map.

**Comment by WJohn** [comment]
What are you talking about with the piping? Box's piping was way, way worse before I got around to improving it. It originally had countless dead ends, made no use of maintenance, and constantly went in loops around the main hallways in retarded ways.

**Comment by Bawhoppen** [comment]
still :-1:

**Comment by GunHog** [comment]
Still wish we had the turrets.

**Comment by Razharas** [comment]
Well we always can revert it if it turns out to be horrible guise

**Comment by Bawhoppen** [comment]
:cancer:

**Comment by lzimann** [comment]
Still feels way too meta imo

**Comment by swankcookie** [comment]
In what way?

**Comment by lzimann** [comment]
Too many decorations. You don't really see this kind of thing in box, but a lot in meta. Not that it's bad, but just don't fit IMO.

**Pull request merged**
