### PR TITLE
Reverts airlocks sounding like poo

### PR DESCRIPTION
**Pull request by praisenarsie**
:cl: Frozenguy5
del: Reverted bad airlock sounds.
/:cl:

image

### CODE REVIEW

**Comment by Qustinnus** [comment]
thank you now maybe will stop pinging me about this

**Comment by praisenarsie** [comment]
:no_mouth:

**Comment by Shadowflame909** [comment]
Can this be merged during the coding freeze?

**Comment by Wilchenx** [comment]
image

**Comment by Cyberboss** [comment]
Before anyone gets any ideas, remember that reverting a gameplay feature is removal which is still banned. Sound tweaks were explicitly allowed

**Review by Cyberboss — APPROVED** [review]

**Comment by Iamgoofball** [comment]
@Cyberboss this is, however, a violation of the kneejerk rule

**Comment by Cyberboss** [comment]
Shouldn't have been merged in the first place, my comment on the original pr is my disapproval of it

**Comment by Qustinnus** [comment]
that was a different sound, the replaced sound is completely different, while the sound you disliked was the original sound with a higher temp.

**Comment by Doppeltongue** [comment]
Considering that airlock opening/closing is probably the single most common noise in the game, it's probably not good to leave them shitty for too long.

**Pull request merged**
