### PR TITLE
the ultimate hulk nerf

### PR DESCRIPTION
**Pull request by ATH1909**
## About The Pull Request

Hulk punches now count as unarmed attacks for the purposes of blocking. They also now call check_block(). This effectively means two things:
* Held chairs, which can only deflect unarmed attacks, can now deflect hulk punches if their block chance procs.
* Martial arts that grant their users the ability to block unarmed and melee attacks while they're in throw mode can now block hulk punches.

## Why It's Good For The Game

Hulk hands may be green and strong, but they're still hands.

## Changelog

:cl: ATHATH
fix: Hulk punches now count as unarmed attacks for the purposes of blocking.
fix: Martial arts that grant their users the ability to block unarmed and melee attacks while they're in throw mode can now block hulk punches.
/:cl:

### CODE REVIEW

**Comment by tralezab** [comment]
## don't even start with me ATHATH everyone knows the REAL ultimate hulk nerf:

**Comment by Fhaxaris** [comment]
> don't even start with me ATHATH everyone knows the REAL ultimate hulk nerf:

this

**Comment by ArcaneMusic** [comment]
Jokes aside seems fair, it's strange that hulk melee wouldn't be considered unarmed melee in the first place

**Comment by necromanceranne** [comment]
> Jokes aside, this seems fair, it's strange that hulk melee wouldn't be considered unarmed melee in the first place

The flags didn't exist for a while.

**Comment by SuperNovaa41** [comment]
Literally just remove pure stun immunity and not a single person would ever complain about powergaming hulks ever again

**Comment by wraith-54321** [comment]
well, its a hulk nerf so it works for me

**Comment by optimumtact** [comment]
I don't think this is going to save them bro

**Comment by Coastfront** [comment]
The logical counter arguement i can come up with for why chairs and martial arts throwmode block didn't work on hulk hands is have you ever tried to block someone hitting you in the arm or the chair with a sledgehammer? If someone could literally punch an entire wall down extremely quickly i somehow doubt that a normal human being who read a book about martial arts is gonna have the bone density to block that.

**Pull request merged**
