### PR TITLE
Fixes an issue wherein plasma cutters accepted infinite plasma

### LINKED ISSUE #41776: You can feed infinite plasma into a plasma cutter even when it's full
## Reproduction:
1. Whip out a plasma cutter. Any charge works fine, can be either type as well.
2. Slam some plasma in there. Ore or mineral sheets, doesn't matter.
3. You will notice that you can do it even when it's at 100%, essentially creating a black hole of plasma and necessitating careful examination to avoid wasting it.

Ideally, the plasma cutter wouldn't let you stick in any extra plasma when it's full.

### PR DESCRIPTION
**Pull request by lilacrhododendron**
:cl:
fix: Plasma cutters will no longer accept infinite plasma, and will stop you when they are full.
/:cl:

Fixes https://github.com/tgstation/tgstation/issues/41776

### CODE REVIEW

**Comment by subject217** [comment]
lol imagine testing your code before you PR it, grammar issue

**Comment by MACIEKBAKI** [comment]
wow such technology

**Comment by MACIEKBAKI** [comment]
BUT speaking of technology, if I have a plasma cutter 99% charged and insert 1 more plasma, what happens? Plasma just gets wasted?

**Comment by subject217** [comment]
Same thing that happened before, which is that it consumes 1 sheet and charges the PC by the amount listed in the code. If that would go over the max charge then it just caps. No reason to change that behavior, it's fine.

**Comment by ExcessiveUseOfCobblestone** [comment]
I hate the copypasta ughghghgghghgh

this is quick read and even quicker code-vomit but something like this would be cleaner imo.

```DM
var/charge_multiplier = 0 //2 = Refined stack, 1 = Ore
if(istype(I,the/refined/type))
    charge_multiplier = 2
if(istype(I,the/ore/type))
    charge_multiplier = 1

if(charge_multiplier)
    if(cell.charge == cell.maxcharge)
        to_chat(user,"the round and full message")
        return
    I.use
    cell.give(500*charge_multiplier)
    to_chat(user,"the success mesage")
else
    ..()

**Comment by ExcessiveUseOfCobblestone** [comment]
would be cool if someone converted this into a material cost >> PC charge ratio so things like plasma coins can be churned in for minute amounts instead of just pure sheets/ore

**Comment by subject217** [comment]
I'll take a look at implementing it how you've suggested in a little while

**Comment by Daxxed** [comment]
99% of the time I recharge it by picking up a nearby plasma ore stack and spamming the pka, probably overcharging it, meh

**Pull request merged**
