### PR TITLE
A* fix

### PR DESCRIPTION
**Pull request by ghost**
Fixes a typo in A* that causes a run-time when not using default args

### CODE REVIEW

**Comment by AnturK** [comment]
This makes no sense, you have to pass in distance function.

**Comment by DaedalusGame** [comment]
every single bot and monkey also uses a* so it's not even right to pretend that only parrots and changelings do it lol

**Comment by AnturK** [comment]
This still doesn't make sense because we define our distance procs based off src so calling it contextless will just do nothing. What are you trying to fix here exactly.

**Comment by py01** [comment]
nvm i just fucked up with another arg and caused a runtime

**Pull request closed without merging**
