### PR TITLE
Gives robotocists mining access

### PR DESCRIPTION
**Pull request by bob-b-b**
## About The Pull Request
Adds mining access to robotocist ID's, letting them go in and out of the mechbay, mining base on lavaland and contribute by mining with the mechs they can make/convert.

Since miners almost never use mechs, this makes it easier for robotocists to start mining with there creations.

## Why It's Good For The Game

Robotocists are usually the only ones that use the mechbay, orbital mech transport pad on lavaland to go mining. This makes it so they dont have to hack doors or hope one of the miners bought a surplus kit so they have access.

edit: Robotics requires a lot of materials, being able to make mechs/tools specifically for mining, combined with the downtime due to big research point costs for mechs, parts, implants. Makes it easier for robotocists to mine and deposit ores

## Changelog

:cl:
balance: Added mining access to robotocist IDs
/:cl:

### CODE REVIEW

**Comment by Fikou** [comment]
why give them mining access and not just mining station access? they shouldnt have free access to all of cargo

**Comment by bob-b-b** [comment]
> why give them mining access and not just mining station access? they shouldnt have free access to all of cargo

When i tested it they only had access to the mining shuttle/office airlocks and none of the cargo doors

**Comment by JohnFulpWillard** [comment]
I disagree with this. If you want to mech-mine, you can go shaft miner and ask for a mech, rather than go robo just to mine. Roboticists have more than one responsibility in a round, since they maintain/build robots/cyborgs, as well as help with MODsuits and augmenting/misc surgeries, compared to shaft miner’s “supply ores”.

**Comment by Pickle-Coding** [comment]
Could you explain why they should have access, instead of the situation? I don't really understand the point of this.

**Comment by bob-b-b** [comment]
> I disagree with this. If you want to mech-mine, you can go shaft miner and ask for a mech, rather than go robo just to mine. Roboticists have more than one responsibility in a round, since they maintain/build robots/cyborgs, as well as help with MODsuits and augmenting/misc surgeries, compared to shaft miner’s “supply ores”.

In a perfect world this would be the case but with robotics being incredibly reliant on research nodes and materials for almost everything they do there ends up being a ton of downtime where they can't do anything but basic borg repairs which rarely happen and borging surgeries, full augmentation surgeries both of which rely on having a lot of iron

Due to how clunky mechs still are for mining and ore depositing, if miners are actively getting ores and not dead/hunting bosses i don't think this will have a significant impact on rounds where robotics is in high demand. Just gives an option on what to do when things are slow.

> Could you explain why they should have access, instead of the situation? I don't really understand the point of this.

Robotics requires a lot of materials, being able to make mechs/tools specifically for mining, combined with the downtime due to big research point costs for mechs, parts, implants. I think that justifies having access to the lavaland mining base and utilizing the orbital mech launchpad.

**Comment by necromanceranne** [comment]
> I disagree with this. If you want to mech-mine, you can go shaft miner and ask for a mech, rather than go robo just to mine. Roboticists have more than one responsibility in a round, since they maintain/build robots/cyborgs, as well as help with MODsuits and augmenting/misc surgeries, compared to shaft miner’s “supply ores”.

Unfortunate that it doesn't stop roboticists from mining anyway. They've been able to do it for years, and can currently do it on almost every map. Easier than ever, in fact. The various shuttles are not ID locked, and the public shuttle gets you access to the most important walkways to the mining area. 

The only thing they do not have immediate access too is the ORM, which is usually on a public facing space, and can be both reconstructed and substituted by just directly inserting ores mined into any lathe.

**Comment by zxaber** [comment]
Having to mine as robo is rare enough that asking the HoP/AI for access (or just using the public shuttle) isn't really that big of a deal.

I don't mind mining on lowpop rounds where no one else is and there's literally nothing else going on anyway, but I'd hate to be *expected* to.

**Comment by BlueMemesauce** [comment]
A better change would be to just add a mech pad to public mining. There's no reason to give them mining access when public mining exists.

**Comment by JohnFulpWillard** [comment]
Sorry for the delay

> In a perfect world this would be the case but with robotics being incredibly reliant on research nodes and materials for almost everything they do there ends up being a ton of downtime where they can't do anything but basic borg repairs which rarely happen and borging surgeries, full augmentation surgeries both of which rely on having a lot of iron

A roboticist being bored isn't the fault of the Shaft Miner and it shouldn't be enough reason to let Roboticists replace them in their own jobs. Roboticists start with plenty of iron (something I understand, but am not a fan of) which should last them enough time for Miners to start bringing ores in.

> Due to how clunky mechs still are for mining and ore depositing

This PR doesn't solve mechs being clunky, so I don't see the relevance here.

> If miners are actively getting ores and not dead/hunting bosses i don't think this will have a significant impact on rounds where robotics is in high demand. Just gives an option on what to do when things are slow.

That sounds like something you can deal with in-round, through the HoP, QM, or Captain.
Players should expect consequences for every single Shaft Miner's absence, and there's many tools to help recover their bodies, I prefer people trying to save dead miners over replacing them with Roboticists.

@necromanceranne comment:

> the public shuttle gets you access to the most important walkways to the mining area.
> The only thing they do not have immediate access too is the ORM

Mining access is also access to the Mining station's mech bay, which is what is relevant here since this PR is supposed to encourage mech mining. You can brute-force your way into doing it anyways using the public mining shuttle, but that way is time-consuming. Discouraging players from doing something is different than barring them from doing it entirely, and being able to do something doesn't mean we should encourage/expect them to do it.

I like the ways we currently discourage Roboticists from powercreeping Mining, like he mech pad gibbing anyone inside when they are sent off.

**Comment by JohnFulpWillard** [comment]
I left 48 hours for a response to my comment, nothing came out of it, so I am closing this for the reasons in my comment.

**Pull request closed without merging**
