### PR TITLE
Replaces the slime extract in the clown biodome with a superlube sprayer.

### PR DESCRIPTION
**Pull request by nemvar**
## About The Pull Request

Removed the slime extract from the clown ruin.
Added a water flower that sprays superlube instead.
Added superlube as a reagent.

## Why It's Good For The Game

The slime extract always felt a bit random in the clown ruin. Now it gives a unique loot item instead (probably a bit lower in powerlevel but more clown themed.)

Since at least one unit of lube needs to be applied to the floor for the lube to get working, the maximum range of the flower is effectively one.

## Changelog
:cl:
add: Added a new loot item to the lavaland clown ruin.
del: Removed the slime core from said ruin.
/:cl:

### CODE REVIEW

**Comment by Shadowflame909** [comment]
It was there for a good reason gamer.

A rare item that could be used for some angel wings.

All these miner nerfs smh my head will you ever give it a rest

**Comment by HomocidlePancakes** [comment]
30u of lube isn’t enough:

**Comment by nemvar** [comment]
The point of going into the clown ruin in clowning, not powergaming. This change facilitates this.

**Comment by Shadowflame909** [comment]
This "clowning" you speak of is very heretical. You might as well remove all the lava and chasms that this ruin possesses. If a proper clown joke to you is slipping people, stunning them with bananas, making clown mechs, and otherwise being a mean clown

I'm gonna get you, bad clowns. I'm gonna shove your lube dispenser so far down your intestine that you're going to throw up lube! 

All in All. Being a shitter is not at all the way I want clowns to go, or miners with clown gear. That sucks bro

**Comment by ExcessiveUseOfCobblestone** [comment]
This is the same clown ruin with the global slip staff right lol?

**Comment by Shadowflame909** [comment]
Meme got nerfed and no longer goes through walls and the stun got shortened to 1 second. It's also only useful to grief.

All I'm saying is. Angel Wings in exchange for cremation is a very good exchange. This'll make this ruins risk only attracted to griefers or burnt out players. IE: The same crowd who decide to build a singulo in cargo on a 5% charged APC.

**Comment by dee-dubya** [comment]
Why not just replace the rainbow extract with a pyrite extract instead? Seems like a much better "fix" that's not only more fitting(Pyrite slime effects are all associated with various clownery) but won't wind up serving as an excuse to griff in the main halls when you return.

**Comment by nemvar** [comment]
@Shadowflame909 At least know what the new honk staff does before you flame it.

**Pull request merged**
