### PR TITLE
Revert "Revert "Adds the saltmine shuttle. (#35369)""

### PR DESCRIPTION
**Pull request by ghost**
Reverts tgstation/tgstation#35435

Did you people not see the irony in reverting this? IT IS LITERALLY A SALT SHUTTLE. AND YOU KNEEJERK REVERTED IT....

# Let that sink in.

### CODE REVIEW

**Comment by Tlaltecuhtli** [comment]
🍆
you have been visited by the eggplant of bad prs, your pr wont be closed within 24h only if you post "thanks eggplant" in here

**Comment by outbools** [comment]
better salt shuttle incoming so just close it

**Comment by MoreRobustThanYou** [comment]
I will close it when the better saltmine is opened

**Comment by lzimann** [comment]
It was reverted for being unoriginal and literally nothing to do with "salt"

**Comment by Slignerd** [comment]
@lzimann It had everything to do with salt. It contained salt along with everything that constantly makes people salty.

**Comment by PKPenguin321** [comment]
this PR is just as ironic?

**Pull request closed without merging**
