### PR TITLE
Adds The Ducky Shoes, From Paradise

### PR DESCRIPTION
**Pull request by san7890**
## About The Pull Request

Courtesy and Regards to https://github.com/ParadiseSS13/Paradise/pull/13996 for the original sprites.

Sound is CC 0 via https://freesound.org/people/DrMaysta/sounds/418509/ (I found actual rubber ducky sounds to be kinda irritating).

This PR adds the ducky shoes to /tg/station. They go quack quack quack quack. Very cute. You waddle in them and they give a soft quack every time you step.

I alphabetized that list while I was there.

## Why It's Good For The Game

image

C'mon, look at how cute they are.

Look at it's face.

image

Are you staring into it's eyes?

image

Quack.

## Changelog

:cl: san7890, kugamo@ParadiseSS13
add: Nanotrasen had a loose shipping container hit the hull of Central Command from one "Station P", so they just decided to pour those into the station's autodrobes.
/:cl:

### CODE REVIEW

**Comment by Shadowflame909** [comment]
how cute!

Now time to turn it into a sign of an absolute menace by wearing them while murderboning with a dual e-sword in a chicken costume!

**Comment by JohnFulpWillard** [comment]
we just added the cat shoes, do we really need new ones? so soon from the last too?

**Comment by Miczu555PL** [comment]
> we just added the cat shoes, do we really need new ones? so soon from the last too?

Is there a limit?

**Comment by JohnFulpWillard** [comment]
> > we just added the cat shoes, do we really need new ones? so soon from the last too?
> 
> Is there a limit?

when i feel like it

**Comment by ShizCalev** [comment]
i hate you.

**Pull request merged**
