### PR TITLE
Adds limb destroyer behavior to hostile mobs. 

### PR DESCRIPTION
**Pull request by Incoming5643**
Mobs with this behavior will (usually [thanks proc/ran_zone]) attack the weakest limb of a mob until it gets dismembered

Adds ishostile() for this pretty specific situation

Behavior added to viscerators / xenos

:cl: Incoming5643
add: The previously underwhelming viscerator robot has been made a lot more terrifying by the new ability to proactively target and dismember limbs.
/:cl:

### CODE REVIEW

**Comment by Incoming5643** [comment]
Implementation is a little crap, but without a refactor of attack code it seems inevitable to be like this.

Feel free to suggest other things that should use this behavior

**Comment by GunHog** [comment]
Can you expand this to /carbon too, so things with sharp claws like Xenos can dismember as well?

**Comment by WJohn** [comment]
That would be cool :+1:

**Comment by Zilenan91** [comment]
:+1:  now if only viscertors weren't terrible

**Comment by PKPenguin321** [comment]
viscerators would be way better if either
1. they had more health
2. the grenade spawned way more of them

**Comment by Incoming5643** [comment]
Well keep in mind that now the second someone gets tagged by a viscerator every other viscerator in the swarm will try to nail it too. That can go south really fast if they take out a leg.

**Comment by PKPenguin321** [comment]
im not sure that matters too much though considering one hit usually kills them before they can even touch you though

**Pull request merged**
