### PR TITLE
Adds Craftable Meson Sunglasses

### PR DESCRIPTION
**Pull request by brokenOculus**
## About The Pull Request

Adds new craftable Meson shades! Grab a pair of regular meson goggles, sunglasses, some cable coil, wirecutters and a screwdriver and use the crafting menu to make a pair for yourself!

## Why It's Good For The Game

Every other department gets an option to combine sunglasses to their huds (Sec, Med, reagent scanner, diagnostic scanner), so now Engineering and Miners can enjoy the protection of sunglasses with the utility of Meson scanners.

## Changelog
:cl:
add: 
- Code for Meson sunglasses
- New Crafting menu recipe
- New sprites for Meson sunglasses
/:cl:

Preview of what they look like in-game:
three sun mesons

### CODE REVIEW

**Comment by wesoda25** [comment]
Mesons are basically discount night vision, and we don't let night vision get sunglasses, so this doesn't seem to make much sense either.

**Comment by brokenOculus** [comment]
> Mesons are basically discount night vision, and we don't let night vision get sunglasses, so this doesn't seem to make much sense either.

I've bumped down darkness_view from 2 (default mesons) to 1 since they're sunglasses and all. You still lose sight of mobs in the dark from a set distance, mesons are not the same as NVG's.

**Comment by FantasticFwoosh** [comment]
No thank you, depreciates the hereditary weaknesss of eye wear if all types can be flash resistant 'upgraded'; Engineers already get a flash resistant hood on their helmets which i think is too much.

**Comment by granpawalton** [comment]
we should just remove all the sunglasses combos except for sec instead of adding this

**Comment by Farquaar** [comment]
How about we just add green sunglasses instead?

**Comment by necromanceranne** [comment]
I can't believe people actually hate hudglasses. What actually makes sechudglasses even remotely special compared to standard ones? It's one of the weakest huds. Mesons ain't anything special either. 

The strongest hud by far is med hud because then you get functional combat information as opposed to 'id this a crook or not'.

**Comment by anconfuzedrock** [comment]
This is actually fucking retarded, mesons are supposed to have the weakness of reducing your eye protection.

**Comment by WJohn** [comment]
God our crafting system is so inexcusably shit.

**Comment by GuppyLaxx** [comment]
for some reason i thought it said melon sunglasses and was looking forward to the pr having some weird recipe about carving sunglasses out of melons
i am disappointed

**Comment by brokenOculus** [comment]
> for some reason i thought it said melon sunglasses and was looking forward to the pr having some weird recipe about carving sunglasses out of melons
> i am disappointed

New Idea for novelty glasses PR.

**Comment by YakumoChen** [comment]
Doesn't actually make fucking sense, mesons make you weak to flashes unless you have a hardsuit helmet on.

**Comment by brokenOculus** [comment]
> Doesn't actually make fucking sense, mesons make you weak to flashes unless you have a hardsuit helmet on.

Basic mesons only function for viewing structures as described and prevent hallucinations when looking at the SM, they do not apply light sensitivity to a player. You seem to have mistaken mesons with thermal vision. Even welding helmets will not protect a player with thermals from flashes.

**Comment by JJRcop** [comment]
brokenOculus#1

I'm going to fix this man's entire PR.

**Comment by ExcessiveUseOfCobblestone** [comment]
what does `darkness_view` do?

**Comment by JJRcop** [comment]
> what does `darkness_view` do?

Affects see_in_dark.
https://github.com/tgstation/tgstation/blob/88588de227a0abcc70540e6fe402b3bf81c054b5/code/modules/mob/living/carbon/carbon.dm#L570
https://secure.byond.com/docs/ref/index.html#/mob/var/see_in_dark

**Comment by plapatin** [comment]
how do mesons even work

**Comment by ExcessiveUseOfCobblestone** [comment]
so basically the var change is mitigated by having a flashlight as with other mesons?

**Comment by brokenOculus** [comment]
Yes, like with normal mesons you will need a flashlight to see beyond one tile's range.

**Comment by ExcessiveUseOfCobblestone** [comment]
Question: Why are these typed so horribly? Does it break if you try to do a base type for create/remove then subtype for each hud VS. having each one their own type?

**Comment by brokenOculus** [comment]
> Question: Why are these typed so horribly? Does it break if you try to do a base type for create/remove then subtype for each hud VS. having each one their own type?

I just copied what I saw the other sunglasses huds doing, for the most part. When I tried doing meson/sunglasses it spat out a lot of errors on me.

**Comment by ExcessiveUseOfCobblestone** [comment]
yeah I think i'm going to make u type the crafting recipes properly prior to merging, it's really cringe.

**Comment by brokenOculus** [comment]
My intention when I added this PR was to add a simple QOL change for miners and engineers. The last thing I would want to do with this PR is a re-write of the existing crafting code. All files have been tested and work as advertised. Its within your discretion to merge or close it as you see fit.

**Comment by JJRcop** [comment]
I think he means to make a generic glasses crafting recipe with some vars for the glasses then change the vars in the subtypes.

**Comment by optimumtact** [comment]
Power creep

**Comment by ExcessiveUseOfCobblestone** [comment]
Is it because it's not a "hud" in the sense like the others or...?

Just want to know if this is an indirect ok to examine the other ones.

**Comment by optimumtact** [comment]
we have a standing policy that we try to avoid adding two types of eyewear speciality into one item because it just leads to powercreep and basically renders the other two items useless

**Comment by ExcessiveUseOfCobblestone** [comment]
time to remove meds and secs >:)

**Pull request closed without merging**
