### PR TITLE
Drones can hear robotic talk

### PR DESCRIPTION
**Pull request by coiax**
:cl: coiax
rscadd: Drones can hear robotic talk, but cannot communicate on it. AIs and cyborgs are encouraged to share information with station repair drones.
/:cl:

### CODE REVIEW

**Comment by lzimann** [comment]
i honestly prefer they not hearing silicons at all

**Comment by Cebasiz** [comment]
they should be able to hear the AI so it can tell them where damage to the station is

borgs i could take or leave

**Comment by lzimann** [comment]
drones have nothing to do with AIs though

**Comment by MMMiracles** [comment]
Why wouldn't the station AI be able to directly communicate with the same mechanical beings that exist for the sole purpose of actually keeping the station intact?

**Comment by optimumtact** [comment]
This was previously denied iirc, let me see if i can dig it up

**Comment by Jordie0608** [comment]
>He even put line breaks in the web-generated changelog

@coiax you're killing me

**Comment by JJRcop** [comment]
Separation between drones and ai/borgs

**Comment by optimumtact** [comment]
Lets see how it goes

**Pull request merged**
