### PR TITLE
makes vacuums "cold", sort of

### LINKED ISSUE #15726: floor tiles always have 20C temperature?
### What is the problem?

if you build a bunch of floor tiles through space, they do not take on the temperature of space
### Why is it a problem, or what should have happened?

i built a megaconstruction of heat exchanger networks, but since the pipes were built on floors they remained 20C even when crossing 100 tiles through open space
### How can the problem be reproduced?

built floor in space, put heat exchanger pipes through it, observe 0 temperature drop
### What revision did the problem happen on? (Helpful, but not required)

latest

anyway just a small consistency issue that's a little weird.

### PR DESCRIPTION
**Pull request by duncathan**
Resolves #15726. This is a hack but due to the nature of things, this issue needed a hack to be resolved. The only alternative would be to make space not cold, but that's a gameplay point I don't want to give up. This hack sacrifices realism (vacuum having no heat capacity and this becoming the temperature of your breath) for gameplay (vacuums being cold, as players expect despite being unrealistic).

### CODE REVIEW

**Comment by Cyberboss** [comment]
@vuonojenmustaturska had a performance buff around this i think

**Comment by duncathan** [comment]
yeah, he did. the gameplay implications of doing that are not a road i want to go down for atmos, tho. it's unfortunate that we have to sacrifice a bit of performance to allow vacuums to be cold but i think that's really important to match players' expectations.

**Comment by WJohn** [comment]
You could always make pressure damage more severe, and maybe standing on space tiles kind of radioactive (maybe after the radiation rework) so it's just as deadly as it is now, without the annoyance that comes from being too slow to escape a breached floor/window, if you want to get rid of space being cold.

**Comment by Supermichael777** [comment]
Yeah space being cold is annoying. up pressure damage if you must, maybe simulate rapid depressurization vaporization freezing things. however I suspect that making space have atmos sim for this would mean the kind of lag we get from lavaland * # space z's

**Comment by XDTM** [comment]
Yeah, players' expectations of space being cold come from habit, nothing says it has to stay like that

**Comment by YotaXP** [comment]
Isn't the coldness supposed to be a result of low pressure, or something?  I may have to ask my physics nerd friend.

**Comment by lzimann** [comment]
i will fight for a cold space

**Comment by Anonmare** [comment]
Help you made everything cold

**Pull request merged**
