### PR TITLE
[READY]Da hydrowear update. Resprites hydro jumpsuit and adds horticultural waders.

### PR DESCRIPTION
**Pull request by Krysonism**
## About The Pull Request

This PR does two things:

It resprites the default botany jumpsuit and jumpskirt.
The new jumpsuit sprites are less flat, less noisy and the green colour is a slightly bluer shade. 

Secondly it adds the horticultural waders: type of apron made of thick leather, it is a bit less permeable than the normal apron but is otherwise identical in function. It is available from the hydrobe.

botasuit_comp
bota_waders64

## Why It's Good For The Game
I have always had a dislike for the standard hydro outfit. It is a mess of bright green, blue and yellow. It gets even worse when someone puts on a botany bandana.  An eyesore is how i would describe it.

The problem areas in my mind are the backpack, apron and jumpsuit.

The backpack can be replaced with a leather satchel so that is a not much of an issue. But the apron doesn't have a decent replacement and i think most players will want to wear their department jumpsuit.

I personally think my new hydroponics jumpsuit looks a lot better, I know respriting such an old core sprite is going to incite controversy, let me know what you think in the comments.

The waders are a stylish and thematically appropriate option to the apron that covers up a lot of your very bright jumpsuit to prevent it from stealing the show.

They kind of looks like something a Victorian gardener would wear and they seem like they would be a good choice in the wet, thorny and dirty environment of the hydroponics lab.

## Changelog
:cl:
add: Added the horticultural waders to the hydrobe.
imageadd: Resprited the hydroponics jumpsuit & jumpskirt
/:cl:

### CODE REVIEW

**Comment by cacogen** [comment]
i like the old green better

**Comment by trollbreeder** [comment]
New jumpsuits look more cyan than green. I prefer the old suits.
Maybe make them a darker shade of green instead of making them bluer?
Horticultural waders are nice, though.

**Comment by fludd12** [comment]
My colorblind ass can barely tell the difference lmao

**Comment by CRITAWAKETS** [comment]
Old ones look better. The new ones just feel like you added some blue onto the central command jumpsuit.

**Comment by cacogen** [comment]
@fludd12 probably depends on your screen, i couldn't see a difference on my phone

**Comment by fludd12** [comment]
Oh I'm literally red/green colorblind I mean.

**Comment by optimumtact** [comment]
bro conflicti

**Comment by Krysonism** [comment]
I will solve this once I get home from work.

**Comment by spookydonut** [comment]
@Krysonism fresh conflicts

**Comment by cacogen** [comment]
change it to the old green

**Pull request merged**
