### PR TITLE
Buffs the Technophile Sect

### PR DESCRIPTION
**Pull request by ATH1909**
## About The Pull Request

The robotic limbs of androids now have the damage reduction values that normal augmented limbs do.

The amount of favor received per point of cell charge for a cell sacrificed to the Technophile chaplain sect has been multiplied by 10 (1 point of favor per 3,000 points of cell charge -> 1 point of favor per 300 points of cell charge).

The amount of favor required to perform the Rite of Synthetic Conversion has been multiplied by 2 (500 points of favor ->1,000 points of favor).

The amount of time required to perform the Rite of Synthetic Conversion has been reduced from 1 minute to 30 seconds.

## Okay, throw me some numbers.

In order to gain favor as a Technophile chaplain, you have to sacrifice charged cells. The amount of favor that you gain from sacrificing a cell is equal to [cell's CURRENT charge]/3,000, rounded down.

Power cells made from 100 potency plants with both the electrical activity trait AND the capacitive cell production trait will have a starting charge (and maximum charge capacity) of 40,000 power units, making them tied with bluespace power cells for being **the largest (feasibly) crew-attainable power cells in the game** (unless you count beam rifle power cells, but those can't be removed from their beam rifles).

Sacrificing one of these maxed out botany cells (or a fully-charged bluespace power cell, if you're trying to grind for favor the "intended" way) will give you a mere **13** points of favor. The Rite of Synthetic Conversion costs **500** points of favor to perform, which is slightly GREATER than the amount of favor gained from sacrificing **38 fully-charged bluespace cells** (or 38 maxed out botany cells). You have to pay this price **EACH TIME YOU INVOKE THE RITUAL**.

Oh, but there's more: In order to turn those aforementioned maxed out botany plants into power cells, you have to use 5 pieces of cable coil on each of them. This means that if you're grinding for favor using just maxed out botany cells, you'll have to spend **over 190 pieces of cable coil for each invocation of the Rite of Synthetic Conversion**.

And just to add salt to the wound, performing this ritual on someone requires a full minute of both of you doing nothing but watching a bar fill up or reading the occasional ritual invocation line.

And remember, the chaplain sacrificed one of their strongest abilities (the ability to heal organic limbs with their bible) to gain access to this "amazing" ritual.

Meanwhile, a roboticist can just full-aug you (in less time than it'd take to perform the Rite of Synthetic Conversion on you) to give you better benefits than what being an android gives you, without needing to go on a 30 minute+ quest to obtain the materials/items necessary to convert you. Unlike androids, full-augged people get brute and burn damage reduction on each of their limbs, the ability to use nanites (including mechanical repair nanites), the ability to retain genetic powers from before their conversion, and the ability to process chems.

This entire situation is just really sad (especially since the Technophile sect is pretty cool flavor-wise), and this PR aims to fix that.

## Changelog
:cl: ATHATH
balance: The robotic limbs of androids now have the damage reduction values that normal augmented limbs do.
balance: The amount of favor received per point of cell charge for a cell sacrificed to the Technophile chaplain sect has been multiplied by 10 (1 point of favor per 3,000 points of cell charge -> 1 point of favor per 300 points of cell charge).
balance: The amount of favor required to perform the Rite of Synthetic Conversion has been multiplied by 2 (500 points of favor ->1,000 points of favor).
balance: The amount of time required to perform the Rite of Synthetic Conversion has been reduced from 1 minute to 30 seconds.
/:cl:

### CODE REVIEW

**Comment by ATH1909** [comment]
> If the argument is they are SUPPOSED to be augged then just aug their parts instead of give them the android role which comes with additional traits that I think are being downplayed a bit.

I'm saying that the android RACE is supposed to be augged, not just this specific means of obtaining it.


> I do not want them remotely capable of competing **with a roboticist who is dedicating the same amount of effort they are** (including proto beside the altar). It's meant to be a sorta rare ritual after you've amassed huge amounts of power with the rarer rounds where you happen to churn out a noticeable portion of the station.

??????????????

Roboticist printing borg parts at roundstart == researching, printing, and charging to full power 30+ T5 power cells???

> Again I'm not a fan of treating sects like they need to compare favorably to the rest of the game. They are meant to be small tweaks to your play style if you so choose with potential rewards for creative approaches.

This is reminding me a LOT of those "nonhumans should be mechanically inferior to humans" arguments. Being an adjustment to your playstyle/goals is not mutually exclusive with not being hilariously bad power-wise.

> If you honestly think that changing it to be twice or x5 as fast keeps it in this niche then ok but otherwise not really a fan.

Alright, I'll boost the amount of favor required to 1,000 points.

**Comment by ExcessiveUseOfCobblestone** [comment]
I was including the surgery in my thinking.

I am willing to try this.

**Comment by ATH1909** [comment]
Thank you!

**Comment by Doosteroni** [comment]
no thank you

**Pull request merged**
