### PR TITLE
fixes centcom_podlauncher delimbing not working as expected, adds a new "Yeet Organs" option to the podlauncher

### LINKED ISSUE #40535: centcom_podlauncher delimb function doesnt work as expected
[Round ID]: n/a tested on private server

[Reproduction]: if you select the "de-limb" function on the centcom_podlauncher verb as an admin, instead of delimbing it yolo's all the target's internal organs out of their body

### PR DESCRIPTION
**Pull request by MrDoomBringer**
Fixes #40535
:cl: MrDoomBringer
fix: Centcom-launched supplypods will now properly delimb you (if they are designated to do so) instead of touching you then literally yeeting all of your internal organs out of your body.
admin: Centcom can now specify if they want to yeet all of your organs out of your body with a supplypod
/:cl:

added a new button to the centcom podlauncher that cinematically removes every organ of whoever is hit by a supplypod

### CODE REVIEW

**Comment by Barhandar** [comment]
keep the yeeting as an option for admins

**Comment by Potato-Masher** [comment]
The future is now.

**Comment by DaxDupont** [comment]
Pod verb is the most fleshed out feature in this whole fucking game at this point

**Comment by Borisvanmemes** [comment]
YEET ORGANS, YEET, FUCKING, ORGANS.
oh my sides hurt.

**Comment by ShizCalev** [comment]
conflict

**Comment by ShizCalev** [comment]
conflict

**Comment by MrDoomBringer** [comment]
when u have like 10 droppod PRs open at once, merge conflict is all that exists

**Pull request merged**
