### PR TITLE
Grammatical fix to Detective's Camera.

### LINKED ISSUE #14232: Poor dash placement, minor issue with detective's camera description.
Description: "A one use - polaroid camera. 30 photos left."
Should be "A single-use polaroid camera. 30 photos left."

### PR DESCRIPTION
**Pull request by lordpidey**
Fixes #14232
Also removes description saying 30 photos left, as that number did not change as the number of photos remaining decreased.  It still shows number of photos remaining on examine.

### CODE REVIEW

**Comment by swankcookie** [comment]
This is unnecessary. Get rid of the description all together. IMO, the name change is unnecessary as well.

**Comment by Aranclanos** [comment]
Why is the description on the map

**Comment by swankcookie** [comment]
I guess people wanted the detectives camera to be flakey.  I'm voting both Desc and name get removed.

**Comment by lordpidey** [comment]
@Aranclanos If I had to guess, it's because the detective's camera has 30 pictures, as opposed to a normal camera's 10.  And while that could be done pragmatically, it would mean having yet another object type.  And then the logic goes, if one small var is changed, why not multiple.

**Comment by swankcookie** [comment]
on interesting thing is that the max_photos var wasnt increased, so once you get under 10 photos left, you can still never go above it

**Comment by phil235** [comment]
Someone please make a detective camera that is a subtype of camera, so we can remove these awful map edits.

**Comment by swankcookie** [comment]
ill get on it

**Comment by swankcookie** [comment]
Can i put up a PR for it durring the freeze, or should i wait?

**Comment by Aranclanos** [comment]
OP do you think you can handle that or not, it's really easy with initialize() and the description proc that I don't remember the name.

**Comment by lordpidey** [comment]
Sorry for the delay, I'm fairly sure I can handle it.  I'll make a subtype of camera.  It should be done by later today.

**Pull request merged**
