### PR TITLE
Fixes smoke spell being not-robeless

### PR DESCRIPTION
**Pull request by Helg2**
Smoke from non-wizard book required wizard clothes, so here goes my bad-code.
## About The Pull Request
Saw this image happen with smoke from ninja bundle, so decided to fix it.

~~I'm aware that this probably can be fixed with just 1-2 lines of code, but still no one did it.
Checked if it inflicts smoke spell from spellbook and as far i can tell it doesnt. Maybe it does, but cant be sure in anything.
You are also able to improve smoke/free with spellbook, but chances to get both of this books are too low to bother i think.~~
Be sure to ping me in here, so i'll be able to see.
## Why It's Good For The Game
You can cast smoke spell without robes, as intended.
## Changelog
:cl:
fix: smoke spell becomes robeless
/:cl:

### CODE REVIEW

**Comment by Wayland-Smithy** [comment]
It looks like only `spell_requirements = NONE` needs overriding, so you may be able to get away with just that and have less tech dept should the parent spell be modified later.

**Review by JohnFulpWillard — CHANGES_REQUESTED** [review]
The change was made when ``proc_holders`` were removed in https://github.com/tgstation/tgstation/pull/67083 - Smoke spell is not supposed to require robes, so I'd rather you change parent.

image

**Comment by Helg2** [comment]
Oh, okay

**Comment by Helg2** [comment]
Does that also mean that there are few spells with same situation? I mean, which are supposed to cast even without robes, but dont.

**Comment by JohnFulpWillard** [comment]
this would have to be checked on a case-by-case basis, this spell in particular was changed accidentally because it was a massive refactor PR, shit happens.

**Comment by Helg2** [comment]
Is tg wiki truthful enough to check it out for this?

**Comment by JohnFulpWillard** [comment]
It could be an indicator but I wouldn't trust it fully.
Best bet would be gitblame or just verifying the old behavior from https://github.com/tgstation/tgstation/pull/67083

**Comment by Helg2** [comment]
Well, as far as i checked, other spells dont have similar issues.

**Comment by Fikou** [comment]
the chaplain smoke spell already has spell_requirements = NONE, which will be redundant, can you remove it from that one?

**Comment by Helg2** [comment]
@JohnFulpWillard when

**Comment by JohnFulpWillard** [comment]
ah i lost track of the PR sorry

**Pull request merged**
