### PR TITLE
Goon chat is now a preference

### PR DESCRIPTION
**Pull request by lzimann**
I've noticed that my pc actually lags a bit with goon chat, so, since @MrStonedOne gave us the option of doing this, might aswell do it.

### CODE REVIEW

**Comment by Ninja137** [comment]
How the fuck do you lag from text chat

**Comment by lzimann** [comment]
It's a js that is constantly doing something, not just text.

**Comment by banthebantz** [comment]
[https://www.youtube.com/watch?v=O6hKlHYjuR8](url)

**Comment by Iamgoofball** [comment]
No, stop. I don't want to code something taking advantage of goonchat's superior support for shit and get told "lol its a preference so we cant add it".

**Comment by MrPerson** [comment]
I gotta be honest, I agree with the goofster here. If/when people start using goonchat to do cool stuff, the alternative chat is going to get removed anyway because it's broken.

**Comment by MrStonedOne** [comment]
The alt chat HAS to stick around. We can't be waiting for goon chat to load to show connection failed notices, and the CDN needs to be able to show messages to clients and it doesn't have the goon chat framework.

**Comment by ChangelingRain** [comment]
The alt chat has to stick around, yes, but it doesn't have to be a preference.

**Comment by Iamgoofball** [comment]
Yeah, I'm not against leaving the old chat in as the fallback if shit breaks. That doesn't mean it hass to be a preference, though.

**Comment by MrStonedOne** [comment]
Call it unsupported, add a indicator to show-server-revision and ahelps about them using it

**Comment by Iamgoofball** [comment]
You know the forum/github warriors who will raise the shitfit over it aren't educated enough to use common sense!

**Comment by Xhuis** [comment]
I do think that having it as a fallback is the better option here. Even the 4-year-old, terrible laptop that I'm typing this from doesn't have any stuttering from it; the enhanced capabilities that goonchat offers outweighs the small amount of performance drops it may cause.

**Comment by Shadowlight213** [comment]
A lot of it is byond not responding when you jump to areas or players as a ghost. People playing won't notice any performance drop, but admins do.

**Comment by ChangelingRain** [comment]
If jumping to areas is what's killing your performance, I have some doubts that goonchat is the cause.

**Comment by Fox-McCloud** [comment]
Going to also agree with Goof on this one; doing this is essentially going to handicap advanced features of goonchat in the name of "it has to be there for regular chat, too" which just wont' be the case, at all.

There should be a fallback, not a dual support.

Dual support technical systems, in the long term, only cause headache and massive amounts of extra labor costs.

**Comment by MrStonedOne** [comment]
@Fox-McCloud I already addressed that:

Call it unsupported, add a indicator to show-server-revision and ahelps about them using it

The indicator in show-server-revision should be non-obvious, and in the same line as the commit hash. maybe add `ac.` before the commit hash so it shows up as `ac.a9148c9`

**Comment by MrStonedOne** [comment]
But let me repeat it again:

Call it unsupported, add a indicator to show-server-revision and ahelps about them using it

The indicator in show-server-revision should be non-obvious, and in the same line as the commit hash. maybe add `ac.` before the commit hash so it shows up as `ac.a9148c9`

**Comment by MrStonedOne** [comment]
Here, how about I say it one more god damn time.

Call it unsupported, add a indicator to show-server-revision and ahelps about them using it

The indicator in show-server-revision should be non-obvious, and in the same line as the commit hash. maybe add `ac.` before the commit hash so it shows up as `ac.a9148c9`

**Comment by MrStonedOne** [comment]
There is zero reason to gimp goonchat because old chat exists as an option.

So there is zero reason to not have old chat as an option.

**Comment by MrStonedOne** [comment]
It's that fucking simple.

**Comment by Iamgoofball** [comment]
Sounds good.

**Comment by lzimann** [comment]
The problem is, I am tired of hearing "but someone will do something in the future", almost one month of goon chat merged and there were no attempts of "advanced features", start doing shit or don't come here saying "but what if"

**Comment by Cyberboss** [comment]
Old chat is unsupported

**Pull request closed without merging**
