### PR TITLE
eye of 'u ded' turret is less 'u ded' - Ocular Warden change

### PR DESCRIPTION
**Pull request by ghost**
the reason-because i died

no but in reality these things are annoying little demonic spiders that perpetuate every fucking base to the point i can't so much as scratch my ass without being I SEE YOU'D because this faggot is behind a barricade

STARING at me

EVERYWHERE

:cl: Oculine
add: Ocular wardens are less awful to deal with because they do less damage now. 
/:cl:

### CODE REVIEW

**Comment by Xhuis** [comment]
:eye: :fire: :fire: :fire: 😨

**Comment by jughu** [comment]
Ocular wardens is so annoying with xray too

**Comment by kevinz000** [comment]
u ded pls nerf

**Comment by kevinz000** [comment]
actually yeah good change this shit is too strong

**Comment by Shadowlight213** [comment]
How the fuck are people dying to them? They are weak as hell. Every time I see a warden, it barely hurts me before I just throw rods at it or something.

**Comment by jughu** [comment]
Because they put mostly it behind windows and it be hard to hit still you need to get trough and it hurts escpecially with xray

**Comment by SgtxRootbeer** [comment]
then use x-ray laser with your x-ray vision.

**Comment by jughu** [comment]
>implying auctally rnd will be done in clockwork

**Comment by ChangelingRain** [comment]
If you're making it more fragile, it needs to do more damage.
If you're making it do less damage, it needs to be less fragile.

**Comment by AdamElTablawy** [comment]
Or, I could not to either for a very spammable demonic spider for an already nearly unassailable clockwork base filled with absurd machinery that nobody can attack?

Seriously. One warden when the clock's starting behind a sandbag or something, bad enough. Wardens and mania motors and sigils? God wipe my ass clean now because i'm shitting bricks.

**Comment by jughu** [comment]
Yeah either way you make them more expensive or a limited amount of it

**Comment by jughu** [comment]
Not forgetting cogscaarabs can fire guns and already walking around in the base with the ocular eyes

**Comment by Supermichael777** [comment]
remove cogscarab

**Comment by KingPhilipIII** [comment]
I've never once had an issue with Wardens. If my memory serves, a punch was enough to floor it.

**Comment by optimumtact** [comment]
you should talk to joan about your changes first

**Comment by Xhuis** [comment]
That's a shitty attitude, oranges. Why is one gamemode suddenly untouchable unless the person who makes the most contributions approves of the changes? Forgive me for being under the assumption that this codebase was open source and anyone could contribute.

**Comment by optimumtact** [comment]
no

**Comment by Xhuis** [comment]
That's all, folks.

**Comment by Iamgoofball** [comment]
just pull a goofball

**Comment by Xhuis** [comment]
Sorry. I already did that yesterday.
#21732

**Pull request closed without merging**
