### PR TITLE
CRISPR for Base Gene editing

### PR DESCRIPTION
**Pull request by read-0nly**
## About The Pull Request

Changes DnaConsole.DM and tgui to add a new function, CRISPR editing. This allows the overwriting of a solved gene with another known gene by use of a "CRISPR string" representing the full transmutation required. It thus requires manually transcribing the known genes to create a string that replaces that specific gene with the specific required gene. Follows the idea of how [CRISPR-Cas9](https://en.wikipedia.org/wiki/CRISPR_gene_editing#Genome_engineering) currently needs both what you want to replace and want to replace it with.

So you write down the full sequence for both genes, then combine them by the lead of each pair like so:
```
 GC CG CG CG GC GC TA TA CG AT TA AT AT GC GC TA	< Replacement Sequence
 |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |
AG GC CC AC AG AG CT CT TC AA GT TA AA AG TG AT   	< CRISPR string
|  |  |  |  |  |  |  |  |  |  |  |  |  |  |  | 
AT GC CG AT AT AT CG CG TA AT GC TA AT AT TA AT   	< Old sequence
```

This would give you the gene string AGGCCCACAGAGCTCTTCAAGTTAAAAGTGAT, which you would then feed in when using CRISPR on a live human's mutations. The difficulty and threshold of knowledge required should hopefully limit abuse, but it's not over - If you mess it up, instead you get a scrambled ACIDFLESH with no guides. To recover it, you need to manually set it to the proper sequence, then overwrite ACIDFLESH with the desired sequence. If you mess up on more than one gene, they'll collapse into ACIDFLESH, so you could lose a permanent slot with it. And then to add to the risk, since we're messing with viruses and DNA, you also get infected with a random virus every time you use it.

I dunno, this has consumed the last two days. Mostly posting to see if there's any interest at all, it needs more polish for sure but I want to make sure I'm bringing it in the right direction to get it approved.

I'm thinking we should need to solve the whole sequence of all base mutations first, and then we could feed the full sequence but with the desired sections swapped, instead of this weird zipper string. That way it'd follow the ATCG rules too, and adds further complexity to the task (needing to solve/activate all genes to be able to properly transcribe them). Every time the swap happens the order of the mutation changes, so with each change you can't just reuse the previous string but with a new section. It could be limited to swapping one mutation at a time to prevent a wholesale swap.

## Why It's Good For The Game

Adds a way to sidestep instability by editing base genes, but with a complexity and risk high enough to dissuade casual grief. Occasional project of turning someone into a supersoldier, if you're willing to take the trouble. 

## Changelog
:cl:
add: Adds CRISPR - a gene editing method that lets you overwrite base mutations
/:cl:

### CODE REVIEW

**Comment by read-0nly** [comment]
I saw the error, it was from a dumb idea for a single-character debug mode. fixed, recompiling

**Comment by Doosteroni** [comment]
Looks pretty fukken sweet

**Comment by moocowswag** [comment]
Genetics needs more to do and this is perfect for that.

**Comment by read-0nly** [comment]
Praise be unto Travis! Tested the rebuild, everything still works as well as it did before

**Comment by LemonInTheDark** [comment]
You'll need to revert those changelog changes, it's caused by an automatic action on your repo, ask in discord if you need help with that

**Comment by read-0nly** [comment]
Pretty sure I got the actions fixed, we'll see if it comes back, struggling to undo the commits since then - if I really can't get it figured out I'll delete my fork, refork, turn off actions immediately, and re-modify the relevant files then make the PR again

**Review by Twaticus — CHANGES_REQUESTED** [review]
return of the default state brit bat pls remove

**Comment by read-0nly** [comment]
Not sure I understand that - but here's what I'll do: I'll close this for now, re-fork, turn off actions, and re-modify the files. I'm pretty sure that should prevent whatever mess happened here. Thanks for your patience guys, still not super familiar with github. I'll take the advantage to not merge to master as suggested by CyberBoss. If anything about this plan is likely to get into trouble, if you could just point me in the direction of the relevant docs I'll do my own reading, just to not waste your time. Thanks again!

**Comment by read-0nly** [comment]
I'll wait to make sure those actions aren't triggering before resubmitting, and take the opportunity to finish implementing the CRISPR charge counters in the meantime

**Pull request closed without merging**
