### PR TITLE
Mecha followup 2

### LINKED ISSUE #53759: Mech huds wipe any hud you already have upon exiting.
Recreation:

Step 1: Get a medical hud, usually from the glasses.
Step 2: Get into an Odysseus.
Step 3: Get out of the Odysseus.

You now no longer have a hud.

@TiviPlus

### LINKED ISSUE #53979: Mech Problems Refactor Edition Part 2: The Clarke
**The Clarke (and all working mechs) cannot move diagonally.**
Because the Clarke can't move diagonally, it's operating on some pretty serious tank controls, which makes it's speed really awkward for mining through the often diagonal tunnels of lavaland and the extremely bendy, narrow tunnels of icemoon.

**The Clarke can strafe.**
The clarke was never meant to strafe, it's a mech with tracks. This is probably because it's inhereting a ton of features from the parent type of mech and none of it fits what the original clarke was meant to be doing.

**The Clarke has no working lights**
I don't know why this was a thing, but upon creation, the clarke lacked headlights.

Alerting Doctor @TiviPlus.

### LINKED ISSUE #54000: Mech Problems Refactor Part 3: The Unlogging: Revengence
**Mechs (and all sealed vehicles, like the clown car) are completely unlogged when they explode**
Mechs exploding is entirely a consequence of them being turned into sealed vehicles. But as a result, when a mech detonates in an explosion that will easily kill people near it, the explosion is entirely unlogged.

You can chain mech explosions for a fairly sizable boom that is entirely unlogged. Very good.

**Mech guns are entirely unlogged when shot.**
I believe old mechs used to have logging for this.

**Mechs seem to runtime a fuckton when they're destroyed**
This gets spammed a lot every time a mech is destroyed.

```[2020-09-27 08:32:10.089] runtime error: Cannot execute null.return pressure().
 - proc name: process (/obj/vehicle/sealed/mecha/process)
 -   source file: _mecha.dm,421
 -   usr: null
 -   src: the Durand (/obj/vehicle/sealed/mecha/combat/durand)
 -   src.loc: Reinforced glass floor (134,134,2) (/turf/open/transparent/glass/reinforced)
 -   call stack:
 - the Durand (/obj/vehicle/sealed/mecha/combat/durand): process(2)
 - the Durand (/obj/vehicle/sealed/mecha/combat/durand): process(2)
 - Objects (/datum/controller/subsystem/processing/obj): fire(0)
 - Objects (/datum/controller/subsystem/processing/obj): ignite(0)
 - Master (/datum/controller/master): RunQueue()
 - Master (/datum/controller/master): Loop()
 - Master (/datum/controller/master): StartProcessing(0)
```

**Mechs can have their parts deleted from explosions**
Mechs that get hit with explosions seem to have the potential to have their parts destroyed. This isn't the normal interaction where a mechs equipment is destroyed. It is just ex_act deleting their cells and stuff and throwing errors.

```[2020-09-27 08:34:15.818] runtime error: Cannot execute null.return pressure().
 - proc name: get stats part (/obj/vehicle/sealed/mecha/proc/get_stats_part)
 -   source file: mecha_topic.dm,64
```

**Clowncar seems to runtime a lot when it releases it's foam**
This could also be mech related somehow, I'm unsure.

```[2020-09-27 08:47:17.645] runtime error: Cannot execute null.reachableAdjacentTurfs().
 - proc name: spread foam (/obj/effect/particle_effect/foam/proc/spread_foam)
 -   source file: effects_foam.dm,175

[2020-09-27 08:47:18.069] runtime error: Cannot execute null.reachableAdjacentTurfs().
 - Warning: further proc crash messages are being suppressed to prevent overload...
 - 
```

**BONUS ROUND: Wormhole Generators stopped working entirely**
Basically, wormholes? Forghedaboudit.

Helpies @TiviPlus I'm in maint and the badman killed me.

### PR DESCRIPTION
**Pull request by TiviPlus**
## About The Pull Request

fixes https://github.com/tgstation/tgstation/issues/53759
fixes https://github.com/tgstation/tgstation/issues/53979
fixes https://github.com/tgstation/tgstation/issues/54000
fixes mech power not using deltatime
## Why It's Good For The Game

less breaking good

## Changelog
:cl:
fix: fixed a few mech bugs
admin: Moved mecha gun logging to attacklog instead of mechalog
/:cl:

### CODE REVIEW

**Review by Couls — APPROVED** [review]
no obvious mistakes in the code

**Comment by ShizCalev** [comment]
Conflicts.

**Comment by Rohesie** [comment]
Will this make a comeback?

**Comment by TiviPlus** [comment]
Yea once I unlazy myself(maybe later today)

**Pull request closed without merging**
