### PR TITLE
Staff of Change now makes hacked drones

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
Because currently being turned into a drone and getting told you can't interact with anyone ever again is worse than if you'd just been hit by an instant death bolt.

### CODE REVIEW

**Comment by GunHog** [comment]
Why not make purged borgs while you are at it?

**Comment by Supermichael777** [comment]
:+1::100:

**Comment by tuypo1** [comment]
no no no no no just having the ability to have hacked drones in the code is bad enough now having it possible to happen without admin intervention

:-1:

**Comment by KorPhaeron** [comment]
Wizard mode basically is admin intervention though

**Comment by SweaterKittens** [comment]
Getting droned is absolute shit, I'm 100% on board with this. It should be a fun, productive way to get back in the round not a worse-than-death sentence from staff of change.

**Comment by freerealestate** [comment]
Don't staves of change still turn you into chickens, chicks and tiny lizards? How is this any worse?

**Comment by KorPhaeron** [comment]
Those are also awful and Id like to remove them as well but at least youre allowed to talk to people in those roles

**Pull request merged**
