### PR TITLE
Makes supermatter melt walls if it finds itself in one

### LINKED ISSUE #44046: Placing a supermatter crystal in a wall prevents it producing gas and prevents it delaminating.
Noticed this on my test server and through several rounds on /tg/Terry.

## Reproduction:
1. Get supermatter engine
2. Place wall on supermatter crystal
3. Turn on the emitters
4. Watch as even without cooling gas and even without scrubbing capacity it works fine

### PR DESCRIPTION
**Pull request by AnturK**
Fixes #44046
Also fixes SM radio getting blown up in explosions (explosions still do nothing special to SM)

~Could possibly damage the sm directly instead of storing the gas.~

### CODE REVIEW

**Comment by Barhandar** [comment]
Are you saying I'll be able to singulo delam SME by just clicking on the turf below it with a RCD once? NOICE

**Comment by AnturK** [comment]
It will work same as SM in a walled off 1x1 turf

**Comment by vuonojenmustaturska** [comment]
Might make more sense to have the SM kill any closed turf it's on

**Comment by OverlyGeneric** [comment]
Walls can still be used to prevent people from running into the SM.

**Pull request merged**
