### PR TITLE
Completely Useless: fix orion trail text and remove number from Pun Pun

### LINKED ISSUE #11736: Pun Pun now has a monkey number
You hug Pun Pun (844) to make him feel better!

this relentless cloning of the pun pun must be fixed

### LINKED ISSUE #11807: Orion Trail text is not updated
This is what it says on live. However, selling them will only net you 7 of each.

### PR DESCRIPTION
**Pull request by feemjmeem**
Fixes #11807 
Fixes #11736 

These are unimportant low-hanging fruit so OF COURSE I DID THEM

### CODE REVIEW

**Comment by ike709** [comment]
"Fixes" before each issue number

**Comment by feemjmeem** [comment]
done; though it looks like it associated with the issues anyway

**Comment by feemjmeem** [comment]
I edited the name of this PR because I kept reading it as "snip pun pun's member"

**Comment by Jalleo** [comment]
@feemjmeem the fixes then reference tells github this issue is fixed once pr is merged

**Pull request merged**
