### PR TITLE
New 'hear' span class

### PR DESCRIPTION
**Pull request by kingofkosmos**
## About The Pull Request
 Makes a new span class called 'hear' and uses it instead of 'italics' in all heard messages, it is the same color as 'notice' span.
And removes lots of extra spaces from the BrowserOutput-files (the indents don't look correct in the Github browser but you can see the raw file and it looks better at least in Notepad++ and Atom).

## Why It's Good For The Game
This is part of making messages more consistent colorwise with each other, making the chat more readable.

### CODE REVIEW

**Comment by kingofkosmos** [comment]
Ready for reviewing.

**Comment by ShizCalev** [comment]
pics please

**Comment by kingofkosmos** [comment]
Before:
Capture2

After:
Capture1

**Comment by ExcessiveUseOfCobblestone** [comment]
so it's just notice but in italics?

**Comment by actioninja** [comment]
conflict

**Comment by kingofkosmos** [comment]
>so it's just notice but in italics?

Exactly.

**Comment by AnturK** [comment]
Is this up to date with font % changes in css ?

**Comment by kingofkosmos** [comment]
> Is this up to date with font % changes in css ?

Yes, the latest commit is where I resolved those and kept the % changes.

**Pull request merged**
