### PR TITLE
Fixes champrojector camera bugs

### LINKED ISSUE #31833: Using a chameleon projector in a closed locker locks your camera in that locker until you break the effect
https://i.imgur.com/Wa7Y3IX.gifv

### PR DESCRIPTION
**Pull request by ghost**
:cl: More Robust Than You
fix: Fixes champrojector camera bugs
/:cl:

alternative to #31934
Fixes #31833

### CODE REVIEW

**Comment by kevinz000** [comment]
is this tested

**Comment by Shadowlight213** [comment]
This only fixes the camera bug. The bugs with contents arent fixed.

**Comment by MoreRobustThanYou** [comment]
@kevinz000 not in the slightest

**Comment by PKPenguin321** [comment]
Fixes https://github.com/tgstation/tgstation/issues/31833
Although it's utilizing just manually calling the cancel-camera-view thing which seems pretty hacky

**Comment by MoreRobustThanYou** [comment]
@PKPenguin321 tbh lots of things do

**Comment by Cyberboss** [comment]
Close the issues in your desc

**Pull request merged**
