### PR TITLE
Fixes cyborgs not dying when they fall into chasms

### PR DESCRIPTION
**Pull request by imedial**
## About The Pull Request
When a cyborg gets gibbed, its MMI pops out and is still able to talk. Funny thing about chasms, they gib you, which leaves you still able to talk despite the fact that you should be dead, so this nulls out the cyborgs MMI if they fall into a chasm, leaving the player properly dead albeit round removed
## Why It's Good For The Game
It fixes a bug that almost never happens
## Changelog
:cl:
fix: borgs no longer drop MMIs when chasmed
/:cl:

### CODE REVIEW

**Comment by SmArtKar** [comment]
See #85782

**Comment by imedial** [comment]
> See #85782

yeah I saw it after I made it and felt like an idiot 🤦 I'll close and reopen it later

**Comment by ATH1909** [comment]
aren't you supposed to be able to fish people out of chasms?

**Comment by deathrobotpunch** [comment]
> aren't you supposed to be able to fish people out of chasms?

you can’t fish items

**Comment by Dawnseer** [comment]
Yes you can?

**Comment by imedial** [comment]
The issue is that the MMI doesn't die, so you can just talk while in the chasm

**Comment by Dawnseer** [comment]
I don't see the issue. Let them scream into the void

**Comment by btcbuster** [comment]
I think it would be better if it just disabled the radio access of the mmi, since theres a normal toggle switch for it. I also hoped you checked AI shells for this

**Comment by Metekillot** [comment]
> I think it would be better if it just disabled the radio access of the mmi, since there's a normal toggle switch for it. I also hope you checked AI shells for this

See a good thing about this is that you don't have to hope You can just read the code to see what they did. That's why GitHub is so good.

**Comment by Odairu** [comment]
> I think it would be better if it just disabled the radio access of the mmi, since there's a normal toggle switch for it. I also hope you checked AI shells for this

Its not about radio, and AI shells dont drop their MMI or Posibrain

**Comment by Odairu** [comment]
They stay alive so their options are ghost out, or sit there and wait, when they should be dead

**Pull request merged**
