### PR TITLE
Adds automatic punctuation.

### PR DESCRIPTION
**Pull request by AnCopper**
Hello people of teegee, today I come to you with this PR of utmost importance.

## About The Pull Request

Takes the code from TGMC, which took the code from beestation, which probably took the code from somewhere else.
 
Webedit pilled.

## Why It's Good For The Game

MY IMMERSION

grammar

## Changelog

:cl:
add: automatic punctutation
/:cl:

### CODE REVIEW

**Comment by Rohesie** [comment]
Use a regex 🗞️

**Comment by optimumtact** [comment]
or we could just not do this at all and not pay any ofhte pointless cost.

**Comment by optimumtact** [comment]
in fact yes, I will close this at 24 hours, there are people who may want to play as illiterate or uneducated people and omitting punctuation can help them.

**Comment by AnCopper** [comment]
> in fact yes, I will close this at 24 hours, there are people who may want to play as illiterate or uneducated people and omitting punctuation can help them.

How many people in the past year have you actually seen that do though?

**Comment by Mickyan** [comment]
In written communication punctuation or lack thereof is useful to get tone across, like this is a pretty relaxed statement I don't care enough to punctuate

This a mildy aggressive remark made with determination. I will put a period at the end so everyone understands nothing else needs to be said about the matter because I am right.

**Comment by Mothblocks** [comment]
heeeeell no people move so fast in this game i genuinely have to tower post to get anyone to listen

also tower posting presents an erratic tone nothing else can in text

**Comment by LemonInTheDark** [comment]
Your lack of effort depresses me. Don't port code without telling us who made it

**Comment by ExcessiveUseOfCobblestone** [comment]
> > in fact yes, I will close this at 24 hours, there are people who may want to play as illiterate or uneducated people and omitting punctuation can help them.
> 
> How many people in the past year have you actually seen that do though?

Uneducated? Tons 😏

**Comment by AnCopper** [comment]
> > > in fact yes, I will close this at 24 hours, there are people who may want to play as illiterate or uneducated people and omitting punctuation can help them.
> > 
> > 
> > How many people in the past year have you actually seen that do though?
> 
> Uneducated? Tons 😏

Fair enough.

**Comment by LemonInTheDark** [comment]
Closing due to a lack of credit for the author and not testing the pr. Also because I don't particularly like the change. (Lasagana posting begone)

@optimumtact too slow

**Pull request closed without merging**
