### PR TITLE
Lets LabeledList.Item's label wrap if they want. Docs the rest of the props.

### PR DESCRIPTION
**Pull request by vincentiusvin**
## About The Pull Request
Title.
No UI should see any difference, need this for another PR I'm making.

## Why It's Good For The Game
Need this for another PR I'm making.

### CODE REVIEW

**Comment by stylemistake** [comment]
This probably goes horribly if you mix the two.

**Review by stylemistake — APPROVED** [review]

**Comment by Timberpoes** [comment]
Can you show us a before-and-after of this? Could we get away with adding it to the kitchen sink menu for example so we can see exactly what this change does?

@stylemistake Is this something we want to see documented in https://github.com/tgstation/tgstation/blob/master/tgui/docs/component-reference.md#labeledlist as well? It's starting to become out of date with a number of niche props and some missing components.

**Comment by stylemistake** [comment]
> Is this something we want to see documented

Yes

**Comment by vincentiusvin** [comment]
<details>
<summary>Before:</summary>


</details>

<details>
<summary>After:</summary>


</details>

We don't have a labeledlist example in the sink, i can add one if you want.

**Comment by stylemistake** [comment]
@vincentiusvin did you try having `labelWrap` with `true` on one item but not the other?

**Comment by vincentiusvin** [comment]
> @vincentiusvin did you test `labelWrap` with `true` on one item but not the other?

Yep

**Comment by stylemistake** [comment]
I'm sold.

**Pull request merged**
