### PR TITLE
Holorifle: 'Energy' Pump-Action 'Shotgun'

### PR DESCRIPTION
**Pull request by necromanceranne**
## About The Pull Request

I was thinking about decent ~~improvised~~ adapted weapon and what would make for a semi-difficult to construct but powerful weapon. This is what I ended up on. The Holorifle. As seen in Fallout: Dead Money. You know, the best DLC.

Screenshot 2020-03-14 21 19 34

Screenshot 2020-03-14 18 40 32

Basically, the holorifle is a powerful shotgun-like energy weapon that does fairly hefty damage per shot. 40 burn, then a 'burn' status effect. The ammo and the gun however require a lot of resource gathering, and it's difficult to get one of these early on. It also only holds 4+1 shots.

I also added the ability to put microfusion cells into a bandolier. (I adjusted up the total number of shells too, because it's kind of annoying how it can't fit three boxes of shells and you always end up with three shells left in three ammo boxes of shotgun shells)

## Why It's Good For The Game

~~There is, like, two weapons that use improvised weaponcrafting. The pneumatic cannon and the improvised shotgun. I think we could do with a third.~~

It's not improvised anymore. It's readapting riot shotguns into something else. Should probably be roughly equal in power anyway, so it works as a good sidegrade.

## Changelog
:cl: NecromancerAnne
add: The holorifle! A difficult and time consuming energy pump-action 'shotgun' to craft!
/:cl:

### CODE REVIEW

**Comment by optimumtact** [comment]
the last thing we need is improvised shotguns or weapons for that matter.

**Comment by necromanceranne** [comment]
Improvised is maybe the wrong word to use, given the work you need to even craft one of them should I split up the gun crafting elements a bit more. It was an improvised weapon in the original concept. 

I had considered it requiring riot shotguns to craft onto as a base. Would that be better and less likely to allow crew to be armed with them?

**Comment by Eskjjlj** [comment]
Can you extinguish the holofire? From what I'm reading this might do 30 damage + an unavoidable additional 30 damage over time so if you manage to shoot someone twice there is high chance they're going to crit.
That's not really different from current shotguns though. Just asking if you can somehow extinguish the holoburn as a counterplay.

**Comment by necromanceranne** [comment]
At the moment, no. It's probably a little high in terms of damage at the moment.

**Comment by Borisvanmemes** [comment]
Why would a person use this over a normal riot shotgun other then style?

**Comment by Tlaltecuhtli** [comment]
copyright content

**Comment by vpellen** [comment]
So if I'm reading this right, the ammo requires 2 metal, a tier 3 cell, a tier 3 capacitor, and a tier 3 laser. Okay, fair enough. That's a pretty heavy load for a powerful shell.

The gun itself requires 5 metal, 15 cable, 5 package wrapper, a tier 3 capacitor, a holopad circuit board, and a... riot shotgun?

Why the hell would you bother to hack together a makeshift gun if you've already got access to the armory? Am I missing something blatantly obvious?

**Comment by SkeletalElite** [comment]
> Why the hell would you bother to hack together a makeshift gun if you've already got access to the armory? Am I missing something blatantly obvious?

Not to mention the fact that they've said the damage seems a little high, but making it any lower would just make it worse than using the original shotgun and loading slugs, which do 60 damage and can hold more ammo without needing to reload.

**Comment by necromanceranne** [comment]
Not really makeshift at this point. It's more an alternative weapon. I'm still trying to figure out a good balance for damage so the damage is very much subject to change.

Worth noting that once you get shot with this, the DoT is unavoidable. You can't put it out and it works in space.

**Comment by necromanceranne** [comment]
I was given a fun idea. The burn now isn't fire damage. It's clone damage.

Also the shot is now 40 burn.

**Comment by Shadowflame909** [comment]
More clone damage means more work for medical.

It also means less side-stepping medical with antag tools.

Because I haven't reached my "usage of the word medical quota" Good day for medical!

**Comment by SkeletalElite** [comment]
> I was given a fun idea. The burn now isn't fire damage. It's clone damage.

Good change. Even if the overall damage on the shot is a little lower this makes it worth it because its very difficult to heal. Making it a good way to deal with a persistent threat who always keeps slipping away.

**Comment by LordSaladin** [comment]
Why not add it to the advanced beam weaponry tech node seeing that node only unlocks the pa rifle and this would fit in that node.

**Comment by necromanceranne** [comment]
What in the ever loving fuck has happened.

**Comment by necromanceranne** [comment]
I'm real sorry I think something pretty bad just broke, I'll reopen this at a later date.

**Pull request closed without merging**
