### PR TITLE
Adds one brain damage statement

### PR DESCRIPTION
**Pull request by yorii**
[Changelogs]: 

:cl: yorpan
add: Brain damage makes you say one more thing.
/:cl:

[why]: This one actually made me laugh I'm sorry to admit it.

### CODE REVIEW

**Comment by Bluespace** [comment]
Robux is old news, change it to vbucks to keep up the current memes.

**Comment by CosmicScientist** [comment]
Can't have vbucks because it'd instead be STOPP SPAM ALL CHAT WITH TRAAADE

**Comment by Armhulen** [comment]
eh

**Comment by yorii** [comment]
travis hates me

**Comment by Jared-Fogle** [comment]
you forgot a comma but other than that this needs to be added

**Comment by chesse20** [comment]
lol

**Comment by yorii** [comment]
well, that was a weird indentation... fixed those things now

**Pull request merged**
