### PR TITLE
adds electrical pie

### PR DESCRIPTION
**Pull request by mamiipolat**
resim
sprite should be changed
## About The Pull Request
energy pie that electrifies when splatted

## Why It's Good For The Game
new toy for clown

## Changelog

:cl: Mamaii and Enesbabo
add: addded energy pie 
/:cl:

### CODE REVIEW

**Comment by optimumtact** [comment]
This is a thrown ranged stun so has balance implications although energy bars are not super common.

**Comment by mamiipolat** [comment]
> This is a thrown ranged stun so has balance implications although energy bars are not super common.

i know this should be balanced and changed sprites should i make this pr a draft?

**Comment by Loafin34** [comment]
theres a battery acid pie already, we could change it to do this effect

**Comment by Pickle-Coding** [comment]
Could have the shock come from transferring the liquid electricity instead of directly applying its own shock. This would limit it to actually having to try and get the person to injest it.

**Comment by ZephyrTFA** [comment]
> unblockable ranged stun

**Comment by AtomTheProphet** [comment]
Can ethereals get charged from this?

**Comment by deathrobotpunch** [comment]
bye bye sweet electrical pie

**Comment by ZephyrTFA** [comment]
sorry that was supposed to be a closing comment not a normal comment.

**Pull request closed without merging**
