### PR TITLE
Fixes the ants reagent as it is in violation of the Goonchem port rules we all agreed to. 

### PR DESCRIPTION
**Pull request by tralezab**
Did nobody read the readme.md in chemistry? Heck. We can't break these rules, it's not cool. Ants are a goon in-joke chemical, if I recall correctly it was literally one of the example ones told to me by the gooncoders back in the goon coding IRC channel when I was hashing out the terms of the port. I'm sorry guys, this is a fun easter egg and all but it just cannot be represented as a reagent in this way.

If this wasn't a direct port of ants from goon as laid out in the original PR (#59634) then this wouldn't be an issue, but it is a direct port with some extra stuff added on.

If you want to do goon ports, you need sign off from the OG coder that added it, which generally is not hard to get, but just porting Goon features without asking permission first is not okay. The original developer of ants wasn't even credited in the changelog!

### About The Pull Request
See title.

### Why It's Good For The Game
Wrath of the goons will kill our codebase if they find out about this. Sorry guys, we'll need to represent ants in a way that doesn't include reagents.

### Changelog
🆑
add: Adds the blants reagent as it is in violation of the Goonchem port rules we all agreed to.
/🆑

### CODE REVIEW

**Comment by Iamgoofball** [comment]
lmao god damn it dude

**Comment by Iamgoofball** [comment]
WRONG BUTTON FUCK

**Comment by Fikou** [comment]
BLAAAAANTS

**Comment by tralezab** [comment]
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa

**Comment by Zytolg** [comment]
STOP
YOU ARE WANTED FOR PORTS AGAINST GOONSTATION AND HER CODERS

**Comment by Iamgoofball** [comment]
i keep posting on other repos and i dont use my mouse to click comment, i just hit tab 3 times and then fucking BAM my post is out, and i keep forgetting i have a close button here sorry

**Comment by tralezab** [comment]
Goon does NOT have Blants

**Comment by Fikou** [comment]
BLAAAAANTS ELES TESM GOOOOOOOOOOOO
BLAAAAAAAAAAAAAAAAANTS

**Comment by tralezab** [comment]
This work is licensed under the Breative Bommons
Battribution-NonBommercial-BareAbike 3.0 Bunited Bates Bicense. To view a copy
of this license, visit http://breativebommons.org/licenses/by-nb-bb/3.0/us/ or
send a letter to Breative Bommons, BO Box 1866, Bountain View, BA 94042, BBA.

**Comment by TiviPlus** [comment]
Verified ✔️

**Review by MrDoomBringer — APPROVED** [review]
looks good to go

**Review by Fikou — APPROVED** [review]
Code looks good

**Comment by Timberpoes** [comment]
Shitposts go in the hut.

**Comment by JohnOxford** [comment]
goofball how get close button

**Comment by NanoCats** [comment]
Thanks ants, Thants.

**Pull request closed without merging**
