### PR TITLE
[Omega] Adds Camera Network to Omega Station

### LINKED ISSUE #23352: Omega Station has almost no cameras.
Omega Station has cameras on bridge, the brig, the teleporter, and EVA storage.

That's it. That's all.

### PR DESCRIPTION
**Pull request by JohnTheDonut**
## **Omegastation Camera Network**
Adds ALOT of cameras on Omegastaion this is to form a fully functioning camera network system for mainly the AI to utilise (And be able to preform functions and operate properly as compared to other stations) and is also there for on station security forces to utilise. Areas that do not have cameras include - Maintenance tunnels, Bathrooms, Personal Dorms.

## **Changelog**
:cl: Tofa01
Add: Adds a camera network onto the Omega Station.
/:cl:

## **Fixes #23352**

_Please note the metric shit tone of additions and deletions are due to converting this map to TGM._

### CODE REVIEW

**Comment by ChangelingRain** [comment]
This is more work, but you should copy the cameras from Delta instead; they use a slightly different ctag format, and have names based on the area they're in.

**Comment by Tofa01** [comment]
I used the prebuilt security cameras from the map editor that had ctag values already assigned so i assume they are the ones from delta, i tried to match the different ctag cameras as best i could to their areas bit i had to create some new instances of cameras and rename them because this map is a bit different compared to others.

**Comment by ChangelingRain** [comment]
The map editor's cameras are built from all the maps you have open, so you might have gotten cameras from other maps; you'll probably have to check your work

**Comment by Tofa01** [comment]
Of course I'll double check ASAP.

**Comment by Tofa01** [comment]
Just took a proper look and double checked the cameras i added they all seem to be the default security cameras except rotated all of them contain and are located on the default "SS13" network the only variable that is different is the c_tag. I have also tested this the cameras appear on the Camera Lists for security, etc And the AI is able to utilise the cameras. So it all seems good its better then having no cameras at all.

**Comment by Tofa01** [comment]
Ready for merge everything looks good.

**Pull request merged**
