### PR TITLE
Restores Maintenance Drones to Robotics

### PR DESCRIPTION
**Pull request by JJRcop**
## About The Pull Request

Drones are back!

If you've played the derelict drones before, these are similar except for being on the station.
To describe drones briefly: They are tiny robots with hands that repair the station and have laws preventing them from interfering with others.

You can now make them again in techwebs. I put them a bit further up in the tech tree so it shouldn't be as common. This does not restore the drone dispensers to the map.

## How it's different from last time

- They can't do much except move around when they are close to a being, alive or dead.
- No more binary chat
- Some bugfixes
- Back in 9c04ff81a0, the drone vision filters were removed. They have not been restored this time, so drones can see beings again
- The drone cargo pack was not restored, just techwebs right now
- As mentioned, drone dispensers are not mapped.

## Why It's Good For The Game

Drones are fun and can help repair the station. Too many players were not listening to the laws, so I figure a gameplay solution would help. Drones are now at the absolute mercy of all beings and can't fight back or do anything except flee. The binary chat change keeps them segregated from the station AI again.

If the item usage limit isn't far enough we can make even further changes.

## Changelog
:cl: JJRcop
add: Maintenance Drones are available as Robotics research once again!
tweak: Drones can no longer use items when near a being.
del: Drones can no longer understand binary chat or machine language.
/:cl:

### CODE REVIEW

**Comment by improvedname** [comment]
Atleast make it use the chameleon version, because i get very mad when a drone goes to armoury to steal an BP helmet for example, or the captains space helmet

**Comment by JenqaDev** [comment]
i've been waiting for this PR for too long
DRONES FOR LIFE

**Comment by trollbreeder** [comment]
Drones are F R E E from their unused prison.

**Comment by improvedname** [comment]
Idk why my comment was marked off-topic, it was pretty much on topic.
Because drones always stole headgear that had alot of armour values to it just for cosmetic values.
And i know theres a chameleon drone (like the bardrone) who has a hat that can change into hats and doesn't drop it on the ground. if you used that kind of drone instead of the normal drone(with no hat) they just turn into these filthy stealing hat thieves

**Comment by 81Denton** [comment]
Before you put more work into this: Have you cleared the PR with oranges or other maintainers?
I personally love playing as a drone, but they still have the issue where their laws are near impossible to enforce or even log properly. 

If anything, porting MoMMIs from /vg/ might be the better choice.

**Comment by optimumtact** [comment]
it needs to go via the headadmins

**Comment by AdamElTablawy** [comment]
might as well make them cost gold, like posibrains do, given that played properly they're better engiborgs

**Comment by optimumtact** [comment]
im going to close this until you get headadmin signoff

**Comment by Mickyan** [comment]
that shy component is super neat though I hope you can still add it if this doesn't work out

**Pull request closed without merging**
