### PR TITLE
Ambrosia gaia balancing

### PR DESCRIPTION
**Pull request by ghost**
- Earthsblood is now _much_ less prevalent in each branch of ambrosia gaia.
  - Adding to this, earthsblood now deals rapid brain damage.
- Ambrosia gaia now grows weeds incredibly rapidly, making it frustrating to cultivate.
- Tweaked research levels of ambrosia gaia to biotech 6 and materials 4.
- Added missing spans to a lot of hydroponics tray messages and tweaked existing ones.
- Moved cherry bombs to `misc.dm`, solidifying their position as xenobiology-only.
- Cherry bombs now set off the black powder inside of them instead of directly exploding.
  - Black powder amounts have also been tweaked. At full (100) potency, cherry bombs explode with a strength of (-1, 1, 3, 0).

### CODE REVIEW

**Comment by coiax** [comment]
So wait, cherry bombs are now just in that pile of food that you can get from silver cores? And then from those you made seeds and give them to botany?

**Comment by Xhuis** [comment]
Ideally, if Botany has cherry bombs, then yes, they come from silver cores. Abuse of growable explosions otherwise proved too abusable for them to be easily acquirable.

**Comment by drynwyn** [comment]
I think the issue with cherry bombs was the power, not the ease of access. I would make them powerful incendiaries rather than weak bombs- That way, they can have an immediate and potent effect, as they deserve for the effort required, but don't create lasting hull breaches or disable large areas of the station.

**Comment by PKPenguin321** [comment]
Gatfruit

**Comment by Kromgar** [comment]
Oh god gatfruit i forgot about that shit

**Comment by Zilenan91** [comment]
Cherry Bombs probably would've been fine if they exploded at IED levels.

**Pull request merged**
