### PR TITLE
Fixes floor is lava and advanced darkness

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
@tkdrg 

I had to leave for dinner before I could hit commit on this, @Incoming5643 figured out I needed a spawn() to stop the events flipping out.

### CODE REVIEW

**Comment by Aranclanos** [comment]
more info please, what are you fixing and why does it need a spawn()

**Comment by KorPhaeron** [comment]
Because there is a sleep in weather (for the duration), if there is no Spawn() then the event gets stuck on Start() and spawns 1 new weather per tick until the first weathers duration is up and Start() can finally finish

**Comment by MrStonedOne** [comment]
This sounds like the spawn should be in weather rather then event control.

Can you forsee any point when something might start the weather up and want to know when it finished?

**Comment by KorPhaeron** [comment]
@MrStonedOne 

Preventing two weathers from being active at once in the same place maybe

**Comment by Aranclanos** [comment]
spawn inside of weather_start_up() and merge after that

**Comment by KorPhaeron** [comment]
@Aranclanos

**Pull request merged**
