### PR TITLE
Bomb Collars

### PR DESCRIPTION
**Pull request by ghost**
This PR adds bomb collars that can be worn in the head slot. There is a special remote detonator that can be used to control these collars. To link a collar to the detonator, hit the the detonator with said collars. Collars may be unlinked by using a screwdriver while it is not locked.

The detonator has three options: Locks, Detonation, and Status. Locks will allow you to lock or unlock worn collars, preventing or allowing them from being removed. A locked collar can never be removed, even with acid. Detonation allows remote detonation of collars synced to the detonator, and will after a short time instantly kill the person wearing the collar and destroy the collar (but not gib the wearer). Status will display the wearer, area, X/Y coordinates, and lock status of every linked collar.

Currently, these collars are admin-only. Suggestions as to what they can be added to the game for would be appreciated (currently, I'm thinking of adding a few to the armory). These collars also support custom IDs for easy sorting, i.e. the name of the person wearing it.

### CODE REVIEW

**Comment by Iamgoofball** [comment]
Mezz gun when?

**Comment by PKPenguin321** [comment]
easily 100x more effective than implants when it comes to releasing known traitors from the brig

give them to cargo so traitors and sec alike can have them

**Comment by Xhuis** [comment]
I figured the detonator would also be pretty cool because if the traitor could manage to take it they could unlock their own collar and slap it in their captors.

**Comment by GunHog** [comment]
Add them to Security, and make them orderable from cargo, so we can get more.

**Comment by Cebasiz** [comment]
this is a fantastic idea

**Comment by Kromgar** [comment]
Make a syndicate bomb collar that has a bigger boom. It also gives a notice not to just lel suicide because you have a collar on you

**Comment by AlexCrimson** [comment]
Seems too strong to give to Sec. Just leave them as an admin spawned item.

**Comment by PKPenguin321** [comment]
>Seems too strong to give to Sec. Just leave them as an admin spawned item.

i don't really see how, you'd pretty much already need to be in their captivity for them to get it on you and at that point all they can do is release you with it or execute you which they can do anyways

**Comment by Dorsisdwarf** [comment]
This should work like handcuffs instead of going in the head slot, so people can go back to working productively with the collar on

**Comment by freerealestate** [comment]
neat

I've always wanted a Battle Royale gamemode

**Comment by pudl** [comment]
I would like to see them utilized as a traitor item. Spawn one, slap it on an assistant, and said assistant now has to follow the orders of the traitor or else they die.

**Comment by GunHog** [comment]
You could make it a jumpsuit accessory, perhaps? That is what Cheri did with pet collars.

**Comment by Nanotransistor** [comment]
Whatever you do, dont give them to sec, they already have enough stuff to deal with released prisoners. Security would just give this to everyone specially during gang, rev, cult, and traitor removing any chance of creative play and rp.

**Comment by freerealestate** [comment]
If it were a traitor item, the explosion would have to be big enough to
deter arrest

Otherwise people would just attack/arrest the collared victim on sight

**Comment by pudl** [comment]
@freerealestate That's the point. The traitor could hypothetically send someone into sec then detonate them, basically like a portable bomb. That's cool.

**Comment by Xhuis** [comment]
I'm going to keep it as a head item both for fluff reasons (nothing protecting the head from the explosion) and because, gameplay-wise, it hinders the person wearing it more and gives an incentive not to just robust your captor for the detonator.

**Comment by Xhuis** [comment]
Changing title because it's no longer WIP, just not implemented

**Comment by Xhuis** [comment]
Bomb collars have been added in two forms. Cargo can order bomb collar crates with three each for 40 points, and there's a closet with five of them in the prisoner transfer centers on Box and Meta.

**Comment by pudl** [comment]
@Xhuis fucking dropped

**Comment by Fox-McCloud** [comment]
Interesting. Really no more abusive than chem implants, to be honest--just more convenient.

**Comment by Steelpoint** [comment]
I like this idea for Sec since it adds a interesting alternative to perma or execution

**Comment by Supermichael777** [comment]
What if your detainee is say the only miner on shift, he needs his helmet for the job this is supposed to force him to continue doing. anyway the damage should be high enough(I suggest 1000 brute/1000 burn which will instantly kill anyone in any armor or when the new armor pr goes through 100 armor penetration) that the average detainee will not have the equipment to survive it. Now as for suggestions, monkeying as a ling should cause the collar to unlock(because they get smaller and the collar stops fitting),freedom implant should drop it at your feet like it was cuffs, and emaging it should produce an error for the detonator and unlock it so you need to ditch it before the guy pulls the trigger. however this should be  handled after people get used to the concept. actually as it stands this might be relatively survivable if you can get some form of inherent damage reduction from burn or brute and some healing sauce.

**Comment by Anonus** [comment]
it's already 400 and targets the head, which won't have armor, because it's a head item.

**Comment by Steelpoint** [comment]
The item should not be easily breakable or else it will not be used. 

Your contesting this item with the finality of executing someone, if this item is to be a good alternative to execution then it needs to be very reliable. Don't forget that any traitor that is wearing this item is only alive because of the exsistance of this item and as such we should not make it easy or even possible at all for a traitor to get the collar off barring them overpowering the person who put the collar on (Warden or HoS).

Personally I would only advocate a Changeling being able to escape a collar, because in doing so they will simply confirm their exsistance to the station meaning the next time any antag, ling or otherwise, is captured then the collar will not be a option.

**Comment by AlexCrimson** [comment]
Chem implants could be removed. Bomb collars cannot. Its so boring. Giving Sec a way to 100% kill anyone who has a collar. Like giving sec the means to instantly teleport criminals to the brig. You are just taking away steps and ruining the fun.

**Comment by Xhuis** [comment]
@Supermichael777 Then the miner would get a new job. Security would find ways around this.
@Steelpoint Bomb collars cannot be broken by conventional means - the only way to escape it is to turn into something besides a human because it's otherwise locked on your character.
@AlexCrimson Your arguments don't make any sense. I introduced this as an alternative to execution, and they're quite limited so if they want to kill someone they can do it in a far more efficient ways. In my two years of playtime, I have seen chemical implants used _once_ by a head of security who turned out to be a changeling. These collars were introduced as a means of allowing parole while effectively ensuring cooperation.

**Comment by freerealestate** [comment]
Surely monkeying is too easy a strategy to get them removed? Maybe it
should explode if the pressure is released from the inside edge of the
collar.

**Comment by AlexCrimson** [comment]
Because people only ever use items in SS13 the way they were intended to be used, right?

People dont use chem implants because its too much hassle to get the chems.

**Comment by Steelpoint** [comment]
I'm a bit wary of even monkeying being effective in removing the collar. Why not simply make it that a Changeling can shift their head out of a collar and that monkeying will just detonate the collar due to the pressure release?

**Comment by Xhuis** [comment]
@Steelpoint Might make that as a resist function.

**Comment by Kromgar** [comment]
Only for lings though right? Resisting out of a bomb collar or depressuring the ring seems like a good way to go boom boom

**Comment by Tokiko1** [comment]
There's a good reason nobody uses chem implants: A single charcoal pill, probably even just a syringe from medbay is enough to survive and clear most implant mixes in a few seconds unless you somehow manage to get your hands on some traitor chems. Worse yet, chem implants can be activated by the implanted person, so you don't even need to time the pill correctly.

This is a much better alternative. You can't easily cheat 400 brute to the head.

**Comment by GunHog** [comment]
I had a chemical implant used on me once, as a wizard's apprentice. Sec captured and interrogated me for information on my master. They eventually implanted me and were about to let me go, right when my master broke me out.

I then got a message in my head, from the HoS, saying that he was disappointed. I died from the implant as my master was uselessly trying to keep me alive.

Anyway, I am fine with these, as long as the corpse remains brainable. Or even brains the person, as EI NATH does. Also, I seriously recommend making the *jumpsuit accessories*! Cheridan did this with pet collars, and it would also mean that you can give the prisoner an irremovable jumpsuit with locked sensors. This will leave the prisoner free to use any head items.

**Comment by Xhuis** [comment]
I'm keeping them as head items for two reasons.

1. I'm not sure how feasible this would be as a jumpsuit accessory.
2. I want these to take up the head slot. They're supposed to be limiting, and they're too bulky to fit headgear on.

**Comment by palpatine213** [comment]
Bomb collars should gib you if you suicide.

**Comment by Kromgar** [comment]
You shouldn't be able to suicide with a bomb collar imo.

**Comment by Xhuis** [comment]
Then people would just ghost.

**Comment by freerealestate** [comment]
Suicides can't be cloned anyway, so why should their bodies be gibbed?

**Comment by Xhuis** [comment]
What? Bomb collars don't gib.

**Comment by freerealestate** [comment]
i know, I was replying to @palpatine213.

**Comment by palpatine213** [comment]
@freerealestate 
Suicides can be borged however. Plus, seeing their character literally gib is going to dicourage players as they are visually seeing that they won't come back into the round rather than just knowing it mechanically.
Unfortunately, gibbing raises the question of how the equipment on the player is going to be handled, so it probably won't work well.

**Comment by GunHog** [comment]
Blow up the head only, not gib the entire body, and leave a brain!

**Comment by Xhuis** [comment]
Okay, there's a bit of confusion about how this works, so let me clear it up.
1. It does not gib the body.
2. It can only detonate if it is locked beforehand.
3. It simply does 200 brute and 200 burn to the head. It is worn on a head slot so that a helmet cannot be used to reduce this and possibly keep the victim alive.
4. It does not leave a brain because it does not cause gibbing or head explosion.
I cannot do head explosion until dismemberment is added. Once it is, bomb collars will make the head explode and possibly leave a brain.

**Comment by Miauw62** [comment]
once dismemberment is in it should just dismember the head

**Comment by Xhuis** [comment]
I've lost interest in this, if anyone wants to continue it they can but I'm gonna close it for now

**Pull request closed without merging**
