### PR TITLE
reagent dartgun inhand no longer looks weird

### LINKED ISSUE #77502: reagent dartgun sprite is scuffed as fuck
## Reproduction:

1.Get reagent dartgun
2. put it in your right hand
3. look to the side
4. it's horrible

image

### PR DESCRIPTION
**Pull request by Slorbin**
## About The Pull Request

all of the sprites for the reagent dartgun was broken. there was never even an 'inner-in-hand' sprite at all. this fixes it all
## Why It's Good For The Game

fixes #77502
## Changelog
:cl:
fix: you can actually tell what hand a reagent dartgun is in now
/:cl:

### CODE REVIEW

**Comment by Wallemations** [comment]
iconndiff is only showing that one file was changed while github says two were changed
seeing how they're in-hands, I'm assuming they're both just a mirror of the other?

**Comment by DeerJesus** [comment]
Kinda.  Some of the icons are shifted about to fit in correct hands. It
works fine in game.

**Comment by Wallemations** [comment]
Ping me when you fix the conflicts and I'll toss it in

**Comment by DeerJesus** [comment]
> Ping me when you fix the conflicts and I'll toss it in

What’s conflicting? Did new in hand weapon sprites just come out?

**Comment by Wallemations** [comment]
> > Ping me when you fix the conflicts and I'll toss it in
> 
> What’s conflicting? Did new in hand weapon sprites just come out?

Probably. It doesn't really matter, just as long as you fix the conflict lol

**Comment by DeerJesus** [comment]
@Wallemations open this again i had to close it to fix some shit

**Pull request merged**
