### PR TITLE
Fixes Deltastation

### PR DESCRIPTION
**Pull request by AnturK**
Leftover ; cause maploader to break

### CODE REVIEW

**Comment by coiax** [comment]
@xxalpha can we get the map merger to strip this or something

**Comment by xxalpha** [comment]
It does, this was text edited and not ran through the map merger.

**Comment by AnturK** [comment]
Yep, my fault.

**Comment by xxalpha** [comment]
The map loader shouldn't care about these, honestly, Byond doesn't.

**Pull request merged**
