### PR TITLE
Crabs now look like they're moving when they move.

### PR DESCRIPTION
**Pull request by ishitbyabullet**
Clickity Click!

:cl: Nabski
imageadd: Crabs have a movement state sprite
/:cl:

Sprites were made by Nabksi.
It would be nice to make crabs even more cute, or some shit I guess, by making them be able to walk. This would also truly immerse you into the spaceman experience for all those HRP crab simplemob players aka no one.

_also it makes them look more fucking terrifying when chasing after you_

EDIT: I am a chumbis. Here's a gif of it in action.
crab

### CODE REVIEW

**Comment by davethwave** [comment]
Crabs look better than when people walk. We just kind of glide around on the ground as the crab get a cool walking animation. Cool PR though, upvote from me here.

**Comment by SpaceManiac** [comment]
To resolve merge conflict:

1. Install Python 3.6+
2. Run `tools/hooks/install.bat` to set up the automatic `.dmi` merger
3. `git fetch upstream master`
4. `git merge upstream/master`

Or do 3+4 and then resolve conflict by hand.

**Comment by Anonmare** [comment]
https://i.imgur.com/ZQwPoZ3.jpg

**Comment by ishitbyabullet** [comment]
@SpaceManiac I really hope I don't have to do that. I'll try that tomorrow in worst case scenario, though.

**Comment by ishitbyabullet** [comment]
alright dudes no more being busy or lazy. time to do it.

**Comment by ishitbyabullet** [comment]
alright dudes i just tried doing it with space maniac's help and my shit is just fucked so he has to do it.

atleast we learned some things.

**Pull request merged**
