### PR TITLE
Paperplane balance fix

### PR DESCRIPTION
**Pull request by Mercenaryblue**
:cl:
tweak: Drastically reduced the chances of eye damage when throwing a paper plane.
/:cl:

### CODE REVIEW

**Comment by Core0verload** [comment]
Nerfing the paper plane? what's wrong with you

**Comment by Mercenaryblue** [comment]
It was just way too common a proc. Like, one in five.

**Comment by PKPenguin321** [comment]
:+1: 
could also just remove the weaken instead too

**Comment by Mercenaryblue** [comment]
Or replace it for stun, but eh, its fine, just too common.

**Comment by RandomMarine** [comment]
Kind of kneejerk, paper planes were just implemented, of course people are going to abuse them for a while.

**Comment by Mercenaryblue** [comment]
Probably. It was my fault anyway. I expected that eye damage to only occur when you aimed at the eyes.
It always happened. So the new proc rates bring it more in line with the original vision.

**Pull request merged**
