### PR TITLE
Mob buckled to mulebots

### LINKED ISSUE #9082: You can not spray "space cleaner" while riding a mule bot
But you can honk, though. Would be nice if you could do that, for some next level clowning. You can while riding the jani-cart, but that is less hilarious.

### LINKED ISSUE #11099: Mulebots can create teleporting human-chair hybrids
Server revision compiled on: 2015-08-07
951ddb3ff412d055eb4dcac5973e2db0c24b1563 

How to:
Buckle someone to a roller chair (I assume roller beds would also work or the janicart)
Hack a Mulebot to make it accept anything, not just crates (load platform clunks wire)
Drag the chair on the Mulebot
Drag the still buckled person away to make the chair teleport on their head
Enjoy your terrifiying human-chair hybrid
You can drag the same chair on another Mulebot to have the chair float higher on the person
You can then ask someone to push the human-chair hybrid on your sprite (rest and have someone push it or move you under it) and then buckle yourself to the chair to become a human-chair hybrid and propel yourself with a fire extinguisher (can't walk due to being buckled)

If someone unloads the Mulebot then human-chair hybrid teleports away to where the Mulebot unloads

I present to you Honky the Human-Chair Clown

ss13 human chair
ss13 human chair2

### PR DESCRIPTION
**Pull request by phil235**
- Changes how mulebots handle loading mobs. It now buckles them to the bot. Fixes #11099 Fixes #9082
- You can no longer load objects containing mobs or with mobs buckled to them.
- Some simplification in mulebot code (buzzing sound code)
- Loading is now instantaneous and the mode BOT_LOADING is removed.
- The mulebot can no longer do certain stuff while off.
- Removing unneeded comments.
- Fixes mulebot loading/unloading being possible through border windows.
- Fixes mulebot not dropping its loaded cargo when qdel'd (wasn't a problem for explosion but for alien acid for example)
- All ventcrawlers (xeno, monkey, drone, slime) and tiny mob (mouse, lizard, butterfly, etc) can now pass through plastic flaps without lying down (instead of just monkey and slime previously).

### CODE REVIEW

**Comment by Dorsisdwarf** [comment]
>you can no longer load objects containing mobs or with mobs buckled to them

NoooooooOoooooOOoooOOo

**Comment by phil235** [comment]
@Dorsisdwarf  If someone finds the time to fix the issues related to chairs and closets becoming prisons once loaded on a mulebot then we can readd that.

**Comment by Durkel** [comment]
On a side note, I think you can just resist out of the buckle like normal and it will fix itself. I used to do this shit on a roller bed about a year ago but I was too lazy to report it.

**Comment by phil235** [comment]
@Durkel Perhaps resist would work, but you'd end up inside the mulebot's contents (although moving might fix it ), but I know that you can't resist out of a closet when loaded on a mulebot.

**Comment by Jalleo** [comment]
Not if we have a feature request to reimplement this for later down the line stating the known issues about it.

**Comment by Core0verload** [comment]
@phil235, yes, I'm against it.

**Comment by RemieRichards** [comment]
This means you can shoot/attack from MULEbots now doesn't it? since you're no longer inside the MULE.

**Comment by phil235** [comment]
@RemieRichards yep, here comes the mulebot driveby shooting!

**Comment by RemieRichards** [comment]
@phil235 Excellent :+1:!

**Comment by freerealestate** [comment]
>You can no longer pass through plastic flaps by getting on a mulebot.

can the mulebot even leave cargo with a rider on some of its routes now then? seeing as to go some places it takes the delivery room, leaving by the plastic flaps?

>yep, here comes the mulebot driveby shooting!

but buckled mobs can't use items?

**Comment by phil235** [comment]
>can the mulebot even leave cargo with a rider on some of its routes now then? seeing as to go some places it takes the delivery room, leaving by the plastic flaps?

Yeah, if the mulebot go through the delivery room plastic flaps it won't be able to pass it with a mob buckled. It wouldn't be consistent to let a standing mob pass through a plastic flap.

>but buckled mobs can't use items?

They can use items, they're buckled in standing position, like a chair.

**Comment by freerealestate** [comment]
Shouldn't mulebot riders be able to pass plastic flaps simply because there
are only a few mulebots, their controls are accessed locked to a few people
and it takes a bit of work to make them rideable? Plastic flaps inside
departments are guarded by access-locked windoors, after all. I always
rationalised people passing plastic on mulebots as the mulebot providing
the force needed to displace the plastic flaps, which a human couldn't do
alone due to them being too heavy. My headcanon, though.

**Comment by Dorsisdwarf** [comment]
I think that more things should  be able to go through plastic flaps, not less. :-1:

**Comment by phil235** [comment]
@Dorsisdwarf I'll see what I can do to make it pass through.

**Comment by phil235** [comment]
To be honest, there's no easy way to make mobs buckled to mulebot pass through plasticflaps, and It'd be inconsistent with the other objects used to buckle mobs. You can't pass through plastic flaps while lying on a roller bed or buckled to an office chair.

**Comment by phil235** [comment]
Alright, mobs buckled to mulebots can now pass through plasticflaps.
 
I also made all ventcrawlers and tiny sized mobs pass instead of just monkey and slime. It lets us simplify the code a bit.

**Pull request merged**
