### PR TITLE
Motor oil can now catch on fire

### PR DESCRIPTION
**Pull request by ShizCalev**
It's logical.

:cl: ShizCalev
fix: Motor oil can now catch on fire. Better do your job, janitor!
/:cl:

### CODE REVIEW

**Comment by zxaber** [comment]
Fix?
Also;
`var/attacked_by_hot_thing = I.is_hot()`
`if(attacked_by_hot_thing)`
Why not just
`if(I.is_hot())`

**Comment by ShizCalev** [comment]
@zxaber The same value is used 3 times in that if statement, so it's cached to a var to instead of calling it repeatedly to reduce the number of redundant proc calls as the value won't be changing during it.

**Comment by zxaber** [comment]
I see, fair enough.

**Comment by Tlaltecuhtli** [comment]
what if you make a napalm decal too which is a better version of oil? currently napalm is garbage and only works while inside a mob

**Comment by nicbn** [comment]
Deep frying oil should catch on fire too

**Review by SpaceManiac — DISMISSED** [review]

**Comment by SpaceManiac** [comment]
Merge conflict but otherwise LGTM

**Review by SpaceManiac — APPROVED** [review]

**Pull request merged**
