### PR TITLE
Completely removes Hilbert's Hotel and its associated ruin from the game.

### LINKED ISSUE #47425: Bag of Holding Bomb teleported people into Hilbert's Hotel
Issue reported from  Round ID: 122280 (/tg/Station Sybil [ENGLISH] [US-WEST] [100% LAG FREE])

Reporting client version: 512.1484

So, not entirely certain as to why or what happened but two people caught in a BoH Bomb got teleported to Hilbert's Hotel.

I mean, it makes sense I guess. And it's actually kind of cool. But I'm pretty sure this isn't intentional.

### LINKED ISSUE #48527: hilbert's hotel has some dumb code that changes the secret room only once the paper saying which room it is has spawned
by default the secret room's number is 1337, this changes once the crumbled paper which would list the secret number spawns, but this means that 1. the code changes every time a paper spawns and 2. you could end up not getting a real secret code because the paper's init doesnt run.

### PR DESCRIPTION
**Pull request by Timberpoes**
## About The Pull Request

image
image
image

Fixes #48527
Fixes #47425

## Why It's Good For The Game

The Hotel is a runtime machine. When it swaps rooms, its turfs runtime. When people are actively using it, things in it constantly runtime. It's half broken, half buggy. Turfs don't remember contents. Sometimes blank rooms spawn. Sometimes nothing at all.

It's not worth the time and effort to fix or maintain it.

I'm opening this PR to completely remove it.

## Changelog
:cl:
del: Hilbert's Hotel and its associated ruin have been removed from the game.
/:cl:

### CODE REVIEW

**Comment by kriskog** [comment]
>It's not worth the time and effort to fix or maintain it.
I disagree with this as its a very cool and unique piece of content. I doubt it would take much to fix, but I am not currently in a position to put in the time to fix it.

**Comment by Timberpoes** [comment]
> 
> 
> > It's not worth the time and effort to fix or maintain it.
> 
> I disagree with this as its a very cool and unique piece of content. I doubt it would take much to fix, but I am not currently in a position to put in the time to fix it.

We currently have an off-station content freeze.

There's design docs with cool things on-station we could be doing in the meantime.

If it was just the runtimes, it MAY be something I'd invest a chunk of time into fixing properly. This is not one of those cases. Even without the runtimes, features of it are fundamentally broken. They need fixing too.

I disagree this it's worth the time and effort to maintain this, its historical and lore value notwithstanding.

**Comment by msgerbs** [comment]
For those of us not into ruins, what is Hilbert's Hotel?

**Comment by zxaber** [comment]
The ruin is a bluespace research room. The item, when used, asks you for a room number and then transports you there. I don't know the specifics, but one room is special, and the room number is found on a piece of paper in the ruins.

Functionally, it exists as an entire hotel room (or several, I suppose) in your pocket, with the caveat that you drop the item when you teleport (since thematically you're actually going inside it) for anyone to find and steal. You also can't drag anything into it, and borgs cannot enter without the help of a humanoid and a bluespace bodybag.

**Comment by Timberpoes** [comment]
> 
> 
> For those of us not into ruins, what is Hilbert's Hotel?

It is broken.

**Comment by Timberpoes** [comment]
Also another bug report I have received is that you can teleport to the hotel even while stunned.

**Comment by Acer202** [comment]
> For those of us not into ruins, what is Hilbert's Hotel?

Hilbert's hotel is a bluespace orb that when used in hand will let you input a room number, and it pulls you in to visit that particular instance of a room among an infinite array of them. Each hotel room has a bit of food in a kitchen, a sitting area with a jukebox, two beds with random bedsheets, and a shower area with fancy soap and mirrors. Very nice thing to have when the station has gone crazy and you just want a breather. Also with the bluespace body bag nerf, it'd be just about the only way you could pocket-carry someone.

This is my favorite space ruin item and I'd be really sad to see it go. It has problems, but it's nothing that couldn't be fixed, I'm sure.

**Comment by LemonInTheDark** [comment]
I plan on taking a look see at this code in a bit, was gonna do it earlier but uhhhhhhhhh.
The atmos runtime shouldn't be that hard to deal with, someone forgot to clean up active turfs I'm betting.
I'll look into the other issues while I'm in there, see what I can make of it.

**Comment by Fikou** [comment]
> We currently have an off-station content freeze.

content freeze, not fix freeze

**Comment by Tlaltecuhtli** [comment]
being able to use as stunned literally requires 2 lines of copypaste to be put in the attackself proc to fix it
```
if(!user.canUseTopic(src, BE_CLOSE, FALSE, NO_TK))
     return
```

**Comment by Livrah** [comment]
As I see the fix: remove an item and leave ruin with broken display case. Bluespace stuff inside worth exploring on its own and leaving the ruin as memento

**Comment by unit0016** [comment]
You... aren't wrong, but I agree with Livrah. IF We're removing Hilbert's (which, still, seems a tad extreme to me), leaving a broken displaycase and leaving the rest of the stuff intact won't hurt. Space Exploration is bland as it is, removing ruins is just hurting it more.

**Comment by Winterous** [comment]
> 
> 
> As I see the fix: remove an item and leave ruin with broken display case. Bluespace stuff inside worth exploring on its own and leaving the ruin as memento

Or just replace its contents with a portal gun.

**Review by Cyberboss — APPROVED** [review]
F

**Comment by Acer202** [comment]
Aww why merge this when there's three PR's up to fix the issues?

**Comment by Doosteroni** [comment]
Oh what the hell cyber

**Comment by Dennok** [comment]
Yep

**Comment by Dennok** [comment]
All this atmos runimes related to map template loading

**Pull request merged**
