### PR TITLE
Power Kickers for ert and deathsquads, but this time I'm not a complete insane GIT

### PR DESCRIPTION
**Pull request by ghost**
🆑 ArmAndHammer
add: Added power boots!
add: they kick HARD, gamers. make sure they're on the ground for best effect!
add: they also kick through DOORS so they're great for breaching like a cool guy
/🆑

wyzack wants /betterbreaching/ with deathsquads and erts and i can't agree more. ~~it's cool, it's in the code, and soon some fucker will add it to rnd. hell yeah~~

Honestly erts and deathsquads are a lot less about balance and a lot more about tacticool stuff. deathsquads have pulse rifles. Will eswords and pulserifles be better than power boots? Almost always, is the answer. This is just something fun to break through doors with instead of the lame pulse rifle entry.

(should I give a version to the hos lads should i do it SHOULD I?!)

### CODE REVIEW

**Comment by Armhulen** [comment]
priority list:
1. move it to it's own file
2. the boot items
3. the door kick function
4. sprite improvements
5. sounds

**Comment by Armhulen** [comment]
i'm unbelievably stupid and my refusal to clean my language for the betterment of coding will get me removed very soon i'm sure

**Review by ExcessiveUseOfCobblestone — CHANGES_REQUESTED** [review]
BASIC_HIT

also fix mushpunch i told you how

**Comment by Alek2ander** [comment]
Needs a subtype that kicks people from the server

**Comment by fludd12** [comment]
^ but only if it also makes them disappear until they reconnect so you kick them into next week.

**Comment by optimumtact** [comment]
still can't code either lmao

**Pull request closed without merging**
