### PR TITLE
Fixes the xeno pen being immediately broken out of

### PR DESCRIPTION
**Pull request by JohnFulpWillard**
## About The Pull Request

Turns out on Birdshot, Xenos can spit out of the xenobio pen through this
image

Making it incredibly easy to break out of.

I moved it up a tile, and to keep it consistent, I moved the bottom one down a tile as well, giving some more space to the xenobio pen as well
image

## Why It's Good For The Game

Xenos cant break out of  the xenobio pen immediately, again.

## Changelog

:cl:
fix: [Birdshot] Xenos can no longer immediately destroy the shield wall generator to break out.
/:cl:

### CODE REVIEW

**Comment by Time-Green** [comment]
Was alien aueens being able to acid through rwalls fixed?

**Comment by JohnFulpWillard** [comment]
> Was alien aueens being able to acid through rwalls fixed?

I think they can use their acid spit through the barrier and go straight to the shield wall generator, they just gotta break the one window.

**Comment by Time-Green** [comment]
> Was alien aueens being able to acid through rwalls fixed?

Nevermind this just got fixed in #76873

**Comment by JohnFulpWillard** [comment]
image
image

**Pull request merged**
