### PR TITLE
Stasis bed now considers diagonals for linking to op computers

### PR DESCRIPTION
**Pull request by optimumtact**
:cl: oranges
tweak: The stasis bed now links in all directions, including diagonals
/:cl:

### CODE REVIEW

**Comment by Dennok** [comment]
If you make stasis bed connects to OP comp in all dir, make OP comp connects to OP tabble or stasis bed in all dirs.

**Comment by Archanial** [comment]
To be consistent optables should do the same thing too.

**Comment by PKPenguin321** [comment]
Mind if I reopen this with the suggested change? Seems like a 1 liner

**Comment by optimumtact** [comment]
@PKPenguin321 yes if you're still interested

**Comment by PKPenguin321** [comment]
Done

**Pull request closed without merging**
