### PR TITLE
Add bitflag arguments to Github style guide

### PR DESCRIPTION
**Pull request by timothymtorres**
## About The Pull Request
This encourages contributors to use a bitflag argument as a replacement for multiple boolean arguments. 

The benefit is that it makes the code more readable since procs end up growing over time as people add more. I've seen this happen and had to implement several large refactors to fix this in the following areas:

- #78754
- #73434
- #64124

Additionally several maintainers considered this to be a vast improvement and I think we should adopt this into our style guide.

## Why It's Good For The Game
Better code standards that we should universally adopt.

## Changelog
N/A

### CODE REVIEW

**Comment by optimumtact** [comment]
I agree with this.

**Review by Mothblocks — CHANGES_REQUESTED** [review]
:-1: Huge disagree.

1. This adds surface area outside of the proc in the form of a detached `__DEFINES` addition. Deleting a proc is now more likely to create unused defines, and the `__DEFINES` file gets more cluttered as a result. You also have to update two documentations at once.
2. It makes specifying default arguments harder, unless you *also* want to require every flag be set.
For example, if I have the following proc:

```dm
/proc/do_thing(flag1 = TRUE, flag2 = FALSE, flag3 = TRUE)
```

How do I, as a consumer, specify that `flag1` should be FALSE, without mucking with the other flags? With simple named arguments...
```dm
do_thing(flag1 = FALSE)
```

...and everything else will default. With flags, this is not so simple. You can't just do `~FLAG1`, because that'll also set `flag3` to FALSE. There's no simple way to do this--you have to specify the other arguments.

3. "This is very verbose and can also result in double negatives"

Flags do not at all make this less common, and we already have rules against it. `NOTELEPORT` and `NO_DEATH_MESSAGE` are examples of this.

4. Bitfields are for **saving memory** above all else. There are times when they are useful for other purposes, such as can_defib's bitfield making it easy to check multiple conditions at once, but they are primarily for memory. They should not be part of an API contract unless it is convenient for other reasons.

5. It makes it harder to call by admins and by Lua scripts.

**Comment by timothymtorres** [comment]
## Maintainability

> This adds surface area outside of the proc in the form of a detached `__DEFINES` addition.

There are caveats to this.  Defines don't always have to be inside a defines file unless the code is used outside. If this is required, there is usually a pre-existing defines file for other related constants that you can put it next to. In my PR examples that I listed, none of them required me to create a new `__DEFINES` file.

> Deleting a proc is now more likely to create unused defines

Counterpoint - I have caught *unused arguments* by refactoring procs to use bitflags in my listed PRs.

I'm also surprised that a linter isn't catching unused defines since there are warnings for unused variables. Is this something we can use `grep()` and count the number of matches as a possible solution?

> the `__DEFINES` file gets more cluttered as a result. You also have to update two documentations at once.

Much of the code that uses bitflags only has code documentation on the bitflag defines. If this is really an issue, we can omit the documentation from the bitflag and just keep it on the proc. (or vice-versa) I think it's nice to do both but it could definitely be a maintainability issue.

## Flexibility

> It makes specifying default arguments harder, unless you also want to require every flag be set.

It's easy. You have the option of setting the default bitflag argument to whatever flag you want. It can be `NONE`, `ALL`, or a combination of flags. You can also override it on a subtype just like with named arguments.

```dm
obj_1/proc/do_thing(bitflags=NONE)
// or like this
obj_1/proc/do_thing(bitflags=FLAG1)

// override
obj_1/obj_2/do_thing(bitflags=(FLAG1|FLAG2))

// store set of bitflags as a define
#define COMBO_FLAG (FLAG_2 | FLAG_3 | FLAG_4 | FLAG_5)
do_thing(COMBO_FLAG)
```

> For example, if I have the following proc... With flags, this is not so simple... There's no simple way to do this

For your example there *is* a simple solution:

```dm
#define DEFAULT_COMBO_FLAG (FLAG_1 | FLAG_3)
/proc/do_thing(bitflags=DEFAULT_COMBO_FLAG)
do_thing(FLAG_3) // too easy
```

> You can't just do ~FLAG1

You can. With bitflags we have a lot more flexibility compared to named arguments:

`do_thing(COMBO_FLAG & (~FLAG_1))` or do it in a define `#define SPECIAL_COMBO_FLAG (DEFAULT_COMBO_FLAG & (~FLAG_1))`

All of these are valid solutions.

## Scalability

> This is very verbose
> Flags do not at all make this less common

One big thing I think you are overlooking is scalability. Bitflags scale very well and have brevity. Named arguments do not, especially once you get past a few arguments.

```dm
// using named arguments 
/proc/do_thing(flag1 = TRUE, flag2 = FALSE, flag3 = TRUE, flag4 = FALSE, flag5 = TRUE, flag6 = FALSE, flag7 = TRUE, flag8 = FALSE, flag9 = TRUE)
// what if I need to call the arguments exactly like this in +100 places like I had to do in my gib() refactor
do_thing(flag1=FALSE, flag3=FALSE, flag4=TRUE, flag7=FALSE, flag8=TRUE)

// bitflag arguments
#define DEFAULT_FLAGS (FLAG1 | FLAG3 | FLAG5 | FLAG7 | FLAG9)
#define COMBO_FLAG (FLAG5 | FLAG8) // same arguments as do_thing() when it's called with named arguments
do_thing(COMBO_FLAG) 
```

This is the same reason why a single boolean argument is fine, but once you go beyond that it starts to look ugly. It doesn't scale and the code legibility starts to suffer.  The same principle applies to named arguments once you go past a few arguments.

## Performance

> Bitfields are for saving memory above all else. 

In my use case for this PR it's directed at improving code readability. However there is a niche benefit in performance since bitflag arguments can *directly* use bitwise operations to store and manipulate the argument data. I have seen people make the mistake of storing booleans into lists while bitwise operations give us `O(1)` performance.

## Debugging

> It makes it harder to call by admins

Admins already use `DEFINE_BITFIELD` to debug. We _should_ be able to add it to arguments as well.

<details>
<summary>Bitflag admin tools</summary>

dreamseeker_KKfR3dOm07

</details>

## Scripting

> It makes it harder to call by Lua scripts.

I know you are fluent in Lua (as am I) so this is for others in the audience.

Lua 5.3+, and LuaJIT have native support for bitwise operators. If auxlua is using Lua 5.1 (which is common) you can import a frequently used [bit library](https://bitop.luajit.org/).  Using bitwise operations with Lua isn't as convenient as other languages since you can't directly use operators. Instead you have to rely on calling functions by name. 

```lua
local bnot = bit.bnot
local band, bor, bxor = bit.band, bit.bor, bit.bxor
local lshift, rshift, rol = bit.lshift, bit.rshift, bit.rol

local flags = {
    FLAG_1 = 2^0,
    FLAG_2 = 2^1,
    FLAG_3 = 2^2,
} 

bor(flags.FLAG_1, flags.FLAG_3) -- this is equivalent to (FLAG_1 | FLAG_3)
```

It's annoying but not that big of a deal.

## Conclusion

If you are _still_ are not convinced, then let me tell you the best part.

Bitflag arguments syntax errors create _compile_ errors. This means that our CI will catch it! 
Named arguments syntax errors create _runtime_ errors. This means that our CI will NOT catch it!

**That is a big deal.**

---

#### Bitflag Arguments Benefits:

- ✅ Syntax errors are caught by our CI
- ✅ Bitflags arguments scale better for readability
- ✅ Performance boost in niche scenarios
- ✅ More flexibility when manipulating arguments
- ✅ Less verbose than named arguments

#### Bitflag Arguments Cons:

- ❌ More documentation maintainability burden
- ❌ Lua scripts are more annoying to code
- ❌ Admins need more tooling to properly debug

**Comment by Mothblocks** [comment]
> There are caveats to this. Defines don't always have to be inside a defines file unless the code is used outside. If this is required, there is usually a pre-existing defines file for other related constants that you can put it next to. In my PR examples that I listed, none of them required me to create a new __DEFINES file.

The surface area of creating a new __DEFINES file versus adding onto one is the same. There are multiple places that now require updating. Code surface area should be minimized as much as reasonable in a codebase like ours with weak static analysis tools and heavy iteration.

> Counterpoint - I have caught unused arguments by refactoring procs to use bitflags in my listed PRs.
> I'm also surprised that a linter isn't catching unused defines since there are warnings for unused variables. Is this something we can use grep() and count the number of matches as a possible solution?

Greps are not good for static analysis, and the use of the language should be your first line of defense (with an asterisk, we'll get to that later). As an example, we use `PROC_REF` instead of just writing the name directly for the static analysis that the language gives us for free. We *could* build a linter to do the same thing, but the language itself helps use prevent these mistakes.

Arguments going unused is one thing--but when surface area increases, the chances of this go up. Surface area MUST be kept to a minimum.

```dm
// using named arguments 
/proc/do_thing(flag1 = TRUE, flag2 = FALSE, flag3 = TRUE, flag4 = FALSE, flag5 = TRUE, flag6 = FALSE, flag7 = TRUE, flag8 = FALSE, flag9 = TRUE)
// what if I need to call the arguments exactly like this in +100 places like I had to do in my gib() refactor
do_thing(flag1=FALSE, flag3=FALSE, flag4=TRUE, flag7=FALSE, flag8=TRUE)

// bitflag arguments
#define DEFAULT_FLAGS (FLAG1 | FLAG3 | FLAG5 | FLAG7 | FLAG9)
#define COMBO_FLAG (FLAG5 | FLAG8) // same arguments as do_thing() when it's called with named arguments
do_thing(COMBO_FLAG) 
```

It is extremely uncommon to have this many flags, and at this point the proc is already **doing too many things**. Using flags here is not solving the core issue, the verbosity is your tell that you're doing something wrong.

Even in this example, if you're doing the same several flags over and over again, it would be better to have a basic proc like:

```dm
/proc/do_thing_combo()
    do_thing(x = TRUE, y = TRUE, etc)
```

> However there is a niche benefit in performance since bitflag arguments can directly use bitwise operations to store and manipulate the argument data. I have seen people make the mistake of storing booleans into lists while bitwise operations give us O(1) performance.

Bitfields *are* marginally faster as arguments than boolean parameters, this is true. However, we do not design for speed when it decreases productivity in other factors, and this is one of those cases.

> Lua

You have completely missed my point which is moreso that changing flag values happens far more often than changing parameter names, and you also once again increase the surface area of the code and possibility for the Lua script to break. It is not a huge deal if Lua scripts break but it's another point down for this kind of style.

> Then let me tell you the best part.
> Bitflag arguments syntax errors create compile errors. This means that our CI will catch it!
> Named arguments syntax errors create runtime errors. This means that our CI will NOT catch it!
> That is a big deal.

There are a significant amount of cases where we choose **not** to take the most statically sound approach because it decreases productivity.

As an example, we hit bugs all the time due to not enough args or too many args being provided. You can avoid these entirely by making wrapper macros with procs, but this wastes people's time. 

Bad named arguments is something we hit all the time--DreamChecker should definitely be built to support this. Especially since even under your proposed solution, we are still using bools when there is less than one flag.

---

Another thing that I realized that flags make significantly harder is being dynamic. Whereas today I can `should_gib = has_plasma` as a named argument, with bitfields my code now needs to be significantly uglier, either packing a flags variable or somehting like `| (has_plasma ? SHOULD_GIB : NONE)`.

**Comment by optimumtact** [comment]
it being caught at static is far preferable to the mess of poorly defined null runtimes we get in production due to all the shitty named flags added by people without any care or consequence.

**Pull request closed without merging**
