### PR TITLE
Fixes communications consoles

### PR DESCRIPTION
**Pull request by Tacolizard**
speedmerge pls

### CODE REVIEW

**Comment by RemieRichards** [comment]
Jesus christ.
Clean your branches before you PR, just because we can squash and merge doesn't mean you can make a PR like this.

**Comment by Tacolizard** [comment]
@RemieRichards PLEASE tell me how to do that

**Comment by ohnopigeons** [comment]
>40 commits for a single string change

What in absolute FUCK

**Comment by RemieRichards** [comment]
None of this:
image

I had to zoom out to 80% to even fit it in.

**Comment by Tacolizard** [comment]
@RemieRichards The only way I know how to keep my master up to date with this repo is to rebase to this repo each time there's an update. The 'test' commit is just a test that i made once, but it gets duplicated each time i rebase. The only way I know to COMPLETELY clean my branches is delete my repo and re-fork. Please tell me how to stay up to date without logging all these commits.

**Comment by RemieRichards** [comment]
\>you rebase whenever you want to update
What on earth are you doing that for?

**Comment by Tacolizard** [comment]
So that when I make my changes, they're made off the latest code from this repo

**Comment by ohnopigeons** [comment]
You don't need to do that for small changes, ESPECIALLY one as minor as this

**Comment by RemieRichards** [comment]
Clearly you didn't understand what I meant, because text fails to convey intent a lot of the time.
You should only rebase when your branch is severely outdated, or broken.
You should instead be git pulling from the upstream repo (this one).

**Comment by Tacolizard** [comment]
Well I didn't do it for this change, It's just that this change is a branch off of my master, which I have been rebasing fairly frequently

**Comment by ohnopigeons** [comment]
https://git-scm.com/book/en/v2/Git-Branching-Rebasing

See 'The Perils of Rebasing'

**Comment by PKPenguin321** [comment]
test
Revert "test"

**Pull request closed without merging**
