### PR TITLE
 Moves GPSes and bluespace crystals to appropriate folders

### PR DESCRIPTION
**Pull request by ChangelingRain**
Fixes an unreported(?) bug where you could still toggle EMPed gpses.

### CODE REVIEW

**Comment by Jordie0608** [comment]
https://github.com/tgstation/tgstation/pull/25925#issuecomment-292033245

**Comment by ChangelingRain** [comment]
I cannot unfuck the line endings.

**Comment by Iamgoofball** [comment]
@Cheridan @optimumtact 
Are we moving away from the code/modules/meme layout?

**Comment by lzimann** [comment]
@Iamgoofball Yea, but they are no longer telesci specific and have more general uses, they don't need to be in telesci module anymore.

**Comment by Cheridan** [comment]
yeah lzimann's right

**Pull request merged**
