### PR TITLE
Crabs can wear hats and hold stuff.

### PR DESCRIPTION
**Pull request by KazeEspada**
"your scientists were so preoccupied with whether or not they could that they didn't stop to think if they should. " -Ian Malcom, Jurassic Park

Based on the thread: https://tgstation13.org/phpBB/viewtopic.php?f=9&t=5914

### CODE REVIEW

**Comment by KorPhaeron** [comment]
powercreep

**Comment by Zilenan91** [comment]
Crab pet for the Chef when?

**Comment by KazeEspada** [comment]
chef has pete.
crab is toxins pet.

**Comment by Zilenan91** [comment]
crab people, crab people, explode like crab, walk like people

**Comment by Bawhoppen** [comment]
balance :baby_chick: :baby_chick: :baby_chick: :baby_chick: :baby_chick: :baby_chick: :baby_chick: :baby_chick: :baby_chick: :baby_chick: :baby_chick:

**Comment by Cheridan** [comment]
>check code
>scream only a little

**Comment by KazeEspada** [comment]
If you test it, you will scream more!

**Comment by MMMiracles** [comment]
So, a drone In a crab suit?

**Comment by KorPhaeron** [comment]
Wouldnt simple_animal/hand/drone and simple_animal/hand/crab make more sense?

**Comment by KorPhaeron** [comment]
20<KorPhaeron>30 KazeEspada, are you planning on redoing the crab thing
18<KazeEspada18> Not really, it was a meme PR. If I did, I would just make it reference the crabs as "crab drones"
18<KazeEspada18> and some sort of "It looks like a crab, it feels like a crab, why the fuck is there screws and lights?"

If Kaze changes his mind this can be opened again

**Comment by FantasticFwoosh** [comment]
Y'know people might sneer at this but bio-organic drones (game mechanically though they are crabs) creatable via xenobio gold coring (rolling for crabs) might be a discreet way to get your traitor objectives by ventcrawling into areas post transferrence potion, and running away with the nuke disk or something/using your small size (if crab was scaled down) to robust people.

Crab sticks are also a recent thing for food.

**Pull request closed without merging**
