### PR TITLE
Buffs the detomax pda bomb by removing its RANDOM EXPLOSION MECHANIC.

### PR DESCRIPTION
**Pull request by Supermichael777**
Proportionally increases the harmless failure chance. Also stops its description lying.

### CODE REVIEW

**Comment by Miauw62** [comment]
the other changes are unnecessary.

**Comment by xxalpha** [comment]
Please don't report it in the changelog otherwise everybody will be buying this immediately. Just let it be a rumor.

**Comment by Dorsisdwarf** [comment]
Changelog is misspelt.

**Comment by Core0verload** [comment]
:+1:

**Comment by Xhuis** [comment]
:+1:

**Comment by WJohn** [comment]
:+1:

**Comment by PKPenguin321** [comment]
still too much RNG involved for it to be worth the purchase, imo

**Comment by callanrocks** [comment]
They're pretty shit as it stands, they can blow up a PDA, hardly damage anything and will rarely kill anyone, people might actually use them if they didn't have a chance to screw up.

**Pull request merged**
