### PR TITLE
Mining Cyborg GPS

### PR DESCRIPTION
**Pull request by GunHog**
- Adds a GPS tool to mining cyborgs.
  Sprite by @WJohn!

:cl:
Name: Gun Hog
rscadd: In response to alarmingly high mining cyborg losses, Nanotrasen has equipped the units with an internal positioning beacon, as standard within the module.
/:cl:

Merge Token: https://github.com/tgstation/tgstation/pull/18505

screenshot 2016-06-12 14 27 55

### CODE REVIEW

**Comment by coiax** [comment]
Does the GPS exist always inside the cyborg even if not equipped

**Comment by Shadowlight213** [comment]
@Coiax yes. All borg modules are like that.

**Comment by GunHog** [comment]
Correct, you do not need to touch it except when trying to track other miners or boss monsters.

**Comment by fludd12** [comment]
Not that I have any business commenting on /tg/ stuff, but you might want to make the GPS able to be turned off, in case of emag/law subversion.

**Comment by GunHog** [comment]
It is, as demonstrated in the image, you can turn it off through alt-click just as a hand-held one can!

**Comment by fludd12** [comment]
Ah alright, sorry to bother ya! Over on paradise, I don't think there's an
off switch for the things.

**Pull request merged**
