### PR TITLE
Removes Oxygen Blob, it was too underpowered.

### PR DESCRIPTION
**Pull request by Iamgoofball**
see title

### CODE REVIEW

**Comment by GunHog** [comment]
Change it to a reagent that halts breathing, requiring medical assistance.

**Comment by Incoming5643** [comment]
and so it was found that without oxygen, blob did not evolate

**Comment by Cheridan** [comment]
So why not just buff it instead? :V

**Comment by RemieRichards** [comment]
double the values.
triple them.

replace it with a gib call on the target.

**Comment by Razharas** [comment]
Improve dont remove

**Comment by Cheridan** [comment]
Make it suck out the oxygen from the air as well. :^)

**Pull request closed without merging**
