### PR TITLE
Red Security Sprites

### PR DESCRIPTION
**Pull request by Steelpoint**
Just when I thought I was out, they pull me back in.

This PR is a continuation of a prior PR. It reverts the security sprites back to the original Red colour scheme, this was approved by Ausops, who was disowned the compromise Grey Security sprites, and Kor.

Link to prior PR: https://github.com/tgstation/-tg-station/pull/17753

Link to the original Grey Security PR (Which was dishonestly titled): https://github.com/tgstation/-tg-station/pull/17280

This PR does not violate the terms of the feature freeze, as it's a pure sprite change and thus falls within the rules of authorized PR's that can be merged.

### CODE REVIEW

**Comment by Steelpoint** [comment]
Why?

**Comment by Steelpoint** [comment]
Pinging @KorPhaeron considering he gave me the go ahead to put this PR up in the first place.

**Comment by Iamgoofball** [comment]
STOP TOUCHING THE UNIFORMS AAAAA

My PR is still better

**Comment by Steelpoint** [comment]
Considering Goofs PR is closed for the month I request this PR be opened again.

@KorPhaeron n @optimumtact

**Comment by Iamgoofball** [comment]
ITS A BUGFIXXXXXXX

**Comment by Steelpoint** [comment]
Bug fix or otherwise this PR can be merged or at least reviewed, whereas your's is unlikely too.

**Comment by freerealestate** [comment]
in english?

**Comment by Steelpoint** [comment]
Merge conflicts should be fixed.

**Comment by Steelpoint** [comment]
Pinging everyone for review. @Cheridan or @KorPhaeron.

Also pinging @optimumtact so we get a balanced perspective on this delicate issue.

**Comment by Supermichael777** [comment]
oranges hates security and fun don't listen to him.

**Comment by KorPhaeron** [comment]
Let it all end

**Comment by KorPhaeron** [comment]
My only regret is now I can't put my name in the changelog and take all the credit for being a hero

**Comment by Steelpoint** [comment]
Why is everyone commenting on this and then removing their comment?

**Comment by KorPhaeron** [comment]
We're gaslighting you

**Comment by Steelpoint** [comment]
Oh shit all the comments only appereard AFTER I posted

**Comment by Bawhoppen** [comment]
:tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada:

**Comment by Steelpoint** [comment]
Also what changelog?

**Comment by Steelpoint** [comment]
Thanks bby

**Comment by KorPhaeron** [comment]
My PR originally had a changelog this entire thing has been one big ploy for my reelection campaign

**Comment by Steelpoint** [comment]
You got my vote.

**Pull request merged**
