### PR TITLE
Adds grab chance multipliers for having free/occupied hands, wearing grappling gloves, being a hulk, etc.

### PR DESCRIPTION
**Pull request by nikothedude**
## About The Pull Request

This PR was born out of me thinking "it doesnt really make sense how we can so easily grab people when our hands are occupied" and then going "wouldn't it be cool if there was a debuff for having occupied hands", and THEN going "why don't hulks get a buff to their grabs/resists?" and THEN going "why not let grappling gloves increase grab effectiveness".

Basically - hulks can maintain and break out of grabs more easily, gripper gloves/krav maga gloves increase grab resilience, having free hands increases your grab resilience - but having occupied hands massively decreases it, to encourage having a hand to grab someone with at _least_.
## Why It's Good For The Game

I'd like to clarify this is one of those PRs mainly made out of "you know, this seems cool".

Firstly - it just makes _sense_ to have grab resilience scale with how many hands you have available to grab someone. And, as I was informed, it might help beat some cheese strategies like shovecuff, grab+block, etc.

For the other changes - I'm a lot less sold on them, and frankly I just made them because I thought they were cool, but...

Gloves: Gripper gloves are honestly kinda underwhelming, so having them increase grab strength would be a neat buff to something so underused. For krav maga gloves - they don't allow people to instantly get an aggrograb, so it SHOULD be fine, but I'm fine with removing it. It was msotly just added for thematics.

Hulk: It just makes sense, honestly. You are extremely strong, so grabs should be easy to keep, and easy to break out of.
## Changelog
:cl:
balance: Grab resilience now scales off how occupied your hands are, scaling inversely with how many of your hands are occupied
balance: Hulks now have significantly stronger grabs and can break out of grabs significantly easier
balance: Gripper/Krav maga gloves now boost the resilience of your grabs
/:cl:

### CODE REVIEW

**Comment by nikothedude** [comment]
im not too terribly invested in this PR beacuse of the whole "i just thought it was cool" angle, so if it isn't well received it'll probably go poof

**Comment by mc-oofert** [comment]
grab combat buff

**Comment by carlarctg** [comment]
Shove cuff is cancer and this buffs it. Not very pleasant byproduct.

Maybe make aggro grabbing people cancel do_afters and thus cuffing?

**Comment by GuillaumePrata** [comment]
Shove cuff being cancer should not stop this PR, it is such a flavorful help for security, or antags with security like gear, that isn't GUNS or BATON and those are quite hard to come by.

I do think the numbers could be more streamlined. Tackling already is a big math soup, easier to have everything be either 1.5 or 2 as a start and if anything becomes an issue, it can be moved around in the future.

**Comment by moocowswag** [comment]
Its possibly a nerf to shove cuff since its heavily reliant on you grabbing the victim while cuffs are in your active hand 

idk the code but having a single item in your hands btter be a nerf to grabs or ill be sad

**Comment by dieamond13** [comment]
HAUL gloves should get the gripper glove boost too since their whole point is they can grab things and move them easier

**Comment by nikothedude** [comment]
could totally make it into: Huge debuff for both hands used, small debuff for one hand used, nothing for both hands free, but I'm not too inclined on spending my brainpower on thinking about that right now as I am beyonfd exhausted

**Comment by nikothedude** [comment]
ill test that commit later dont worry

**Comment by nikothedude** [comment]
having this reopened cause of the recent wave of unarmed combat prs

**Pull request closed without merging**
