### PR TITLE
Speeds up part of the dust animation by a frame or so, makes remains/dust spawn aligned lower on the tile

### PR DESCRIPTION
**Pull request by MrMelbert**
## About The Pull Request

- Speeds up the torso part of the dust animation by a few frames, as was requested but I didn't do before merge
- Makes remains/dust spawn from being dusted towards the bottom of the tile

Videos (take before the remains/dust change)

https://github.com/user-attachments/assets/7e9fe699-a44b-49d5-a4d0-2304e09283d5

https://github.com/user-attachments/assets/7b426340-5d3d-49fa-91f1-52b2fc3a560c

## Why It's Good For The Game

Should help sell the effect a bit more

## Changelog

:cl: Melbert
image: Speeds up some frames of the dust animation slightly
image: Dust/remains spawned after being dusted are now aligned towards the bottom of the tile
image: Bigger mobs now produce bigger piles of ash
image: Plasmamen now dust into plasma bones
/:cl:

### CODE REVIEW

**Review by LemonInTheDark — CHANGES_REQUESTED** [review]
use pixel_z/w please. way cleaner effect then before
also IT ISN'T A FRAME FRAMES ARE CLIENT DEPENDENT HITS WITH A ROCK

**Comment by MrMelbert** [comment]
hey man I said frames because I literally edited the animation's frames

**Comment by LemonInTheDark** [comment]
YOU USED IT AS A UNIT OF TIME THE LENGTH OF A FRAME IS ENTIRELY VARIABLE MY VENGEANCE WILL BE SWIFT

**Comment by Wallemations** [comment]
> YOU USED IT AS A UNIT OF TIME THE LENGTH OF A FRAME IS ENTIRELY VARIABLE MY VENGEANCE WILL BE SWIFT 

IN THIS SENSE IT IS CORRECT AS IT IS IN RELATION TO OTHER PARTS OF THE SAME SPRITE'S ANIMATION AND NOT THE ACTUAL TIME THAT ANIMATION IS PLAYED!!!

**Review by Wallemations — APPROVED** [review]
I hate fruit

**Comment by LemonInTheDark** [comment]
> IN THIS SENSE IT IS CORRECT AS IT IS IN RELATION TO OTHER PARTS OF THE SAME SPRITE'S ANIMATION AND NOT THE ACTUAL TIME THAT ANIMATION IS PLAYED!!!

INTERESTING POINT, YET YOU MISS A CRUCIAL DETAIL! A SPRITE'S ANIMATION CAN HAVE DIFFERENT DELAYS FOR DIFFERENT GAPS BETWEEN FRAME, SO EVEN ACCEPTING RELATIVE TIME THIS IS IMPERCISE. FRAME HAS NO ANCHOR TO GIVE IT MEANING, RELATIVE OR CONCRETE.

**Review by LemonInTheDark — APPROVED** [review]

**Comment by mc-oofert** [comment]
why did we merge the new dust animations again they look pretty bad compared to the old dinky animation where you dont start slowly disappearing from top to bottom and it looks like you actually become dust

**Comment by Loafin34** [comment]
yeah it looked so strange and the body didnt collapse like in the 2006 one

**Pull request merged**
