### PR TITLE
Detective's capes and fixing dark detective's fedora

### PR DESCRIPTION
**Pull request by FeenieRU**
## About The Pull Request

Adding some detective's capes. Fixing dark detective's fedora's armor stats.

## Why It's Good For The Game

I fixed non-armored detective's fedora and adding some stuff.

<details>
  <summary>IT WAS TESTED</summary>

image

image

image

</details>

## Changelog
:cl:
add: Added detective's cape-variant of trenchcoat for accessory slot
fix: Fixed armor stats for dark detective's fedora
/:cl:

### CODE REVIEW

**Comment by Pumpkinoe** [comment]
Won't this cause some confusion with people wearing the unarmored cloak version and the armored outerwear version?

Won't this also look really bad over some suits? (Particularly larger suits)

Making the detective's dark fedora have armor has also been done before and was rejected.
https://github.com/tgstation/tgstation/pull/72098

**Comment by FeenieRU** [comment]
> Won't this cause some confusion with people wearing the unarmored cloak version and the armored outerwear version?

IDK how to answer, because I didn't understand question. They have different names and different available slots to wear, so you can't wear unarmored cape as trenchcoat in suit slot.

> Won't this also look really bad over some suits? (Particularly larger suits)

Not great problem, we still have chiefs' capes that look bad on huge suits (RD MOD, bomb suit)

> Making the detective's dark fedora have armor has also been done before and was rejected.

I think it can't be serious reason for closing PR. It sounds like a joke:
_armour creep on items **that don't make sense** is explicitly not allowed_
Why "don't make sense" if it is literally only detective's fedora? Why not allowed, who forbid?

**Comment by Wallemations** [comment]
It doesn't really look much like a cape since from what I can tell the arms still go through the sleeves??
I mean I'm all for having a draped trenchcoat cape thing but this is just kinda confusing me as to why

**Comment by Pumpkinoe** [comment]
> It doesn't really look much like a cape since from what I can tell the arms still go through the sleeves?? I mean I'm all for having a draped trenchcoat cape thing but this is just kinda confusing me as to why

It's not /actually/ a cape, it's just the icon of the trenchcoat but placed in the cloak slot.

**Comment by kawaiinick** [comment]
Thats kinda dumb to have 2 items that look exactly the same with only difference being they go into different slots. Also it will probably look strange if you wear your trenchcoat over eva or modsuit

**Comment by Pumpkinoe** [comment]
> Not great problem, we still have chiefs' capes that look bad on huge suits (RD MOD, bomb suit)

I also checked - and the Head of Staff cloaks all look pretty much fine on huge suits, since they are designed to go over and cloak - not stick tightly to the body.

**Comment by EricZilla** [comment]
I'm gonna be real here, "It will look bad with some other clothing options" is not the problem you are making out here. Just don't wear that combo lmao. Calling them capes is weird though, dunno how I feel about jackets in the neck slot.

**Comment by Pumpkinoe** [comment]
> I'm gonna be real here, "It will look bad with some other clothing options" is not the problem you are making out here. Just don't wear that combo lmao. Calling them capes is weird though, dunno how I feel about jackets in the neck slot.

Kinda the point I was trying to make is that it's a bad idea to have capes in the neck slot. I may have articulated that badly!

**Comment by DrDiasyl** [comment]
Cloak looks too similar to a basic trenchcoat, should have more unique sprite (like heads cloaks)

**Comment by FeenieRU** [comment]
> The cloak looks too similar to a basic trenchcoat, and should have more unique sprites (like heads cloaks)



> > Not great problem, we still have chiefs' capes that look bad on huge suits (RD MOD, bomb suit)
> 
> I also checked - and the Head of Staff cloaks all look pretty much fine on huge suits, since they are designed to go over and cloak - not stick tightly to the body.

image

**Comment by Pumpkinoe** [comment]
Pretty sick now!

**Comment by FeenieRU** [comment]
> > Not great problem, we still have chiefs' capes that look bad on huge suits (RD MOD, bomb suit)
> 
> I also checked - and the Head of Staff cloaks all look pretty much fine on huge suits, since they are designed to go over and cloak - not stick tightly to the body.

You're sure?
image

**Comment by Pumpkinoe** [comment]
> You're sure?

i did say 'pretty much fine'
it's a very, very small clipping issue - whereas i feel like it might be a lot more noticeable with a jacket
either way, my main issue with it has already been fixed

im not a maintainer anyways

**Comment by L0pz** [comment]
Detective's vendor should have a batman outfit...

**Comment by GuillaumePrata** [comment]
> Making the detective's dark fedora have armor has also been done before and was rejected.

It was a mistake at that time and it would be a mistake again.

There is no good reason to have a recolor of an item have different stats than the other, even more when the detective already has 6 armored vests on their closets, place has as many armored vest options than the literal armory.

The only thing it achieves is noob baiting new players that see the standard of armor that security has not apply to 1 piece of clothing because someone forgot a line of code eons ago.

**Comment by FeenieRU** [comment]
please, make it alive

**Comment by Twaticus** [comment]
detective doesnt need a cape

**Comment by Dawnseer** [comment]
By that margin, why do we have any capes at all? Does any job really need them?

**Pull request closed without merging**
