### PR TITLE
you may now weld a crate

### PR DESCRIPTION
**Pull request by mc-oofert**
## About The Pull Request

https://github.com/user-attachments/assets/bc104e6d-6007-4e9f-ab9f-b810d0f5d664

## Why It's Good For The Game

no reason to be unweldable

## Changelog
:cl:
add: you may weld a crate
/:cl:

### CODE REVIEW

**Comment by AMyriad** [comment]
whatabout mail crates?

**Comment by Loafin34** [comment]
what about wooden crates?

**Comment by optimumtact** [comment]
can you resist out of it after it's been welded?

**Comment by mc-oofert** [comment]
> what about wooden crates?

you may not weld any subtype of crate that is not metal or sprite doesnt match

**Comment by mc-oofert** [comment]
> can you resist out of it after it's been welded?

crates are a subtype of closets so yes you can

**Pull request merged**
