### PR TITLE
Adds a new Emergency Shuttle, Transport Zeta

### PR DESCRIPTION
**Pull request by JetBrody**
## About The Pull Request
Adds a new abductor themed shuttle to the game, available for 8k credits! The shuttle is only unlocked after alien technology has been researched!

zeta

## Why It's Good For The Game
The shuttle offers some unique items and layout compared to others currently available. Two singular entrances with the brig in the back means security needs to walk prisoners to the brig area to secure them. Unique unlock mechanism encourages either bringing alien tech back from Lavaland or stealing some from an abductor.

A few unique items aboard, including alien tools, the experimental cloner, and a void core can provide interesting opportunity if utilized in the window of time that the shuttle is on station. 

## Changelog
:cl: Hulkamania
add: Added Transport Zeta, and abductor themed shuttle, to the shuttle list for 12k credits!
/:cl:

### CODE REVIEW

**Comment by wesoda25** [comment]
It looks really fucking cool and sounds super cool, but doesn’t 12k seem a little low? This seems like 25k would be nice, makes sense ICly and makes it a bit more rare. Not some impossible task either.

**Comment by JetBrody** [comment]
The price is totally adjustable. I mostly settled on 12k because it offers less silly memery than the wabbajack shuttle, which is priced at 15k. 

Not 100% settled on that price though!

**Comment by ishitbyabullet** [comment]
stop buffing rob robinson

**Comment by partykp** [comment]
"Additionally the brig and command center both are only behind glass/grilles making break ins to these areas easier than normal."
Why though

**Comment by JetBrody** [comment]
The price is totally adjustable. I mostly settled on 12k because it offers less silly memery than the wabbajack shuttle, which is priced at 15k. 

Not 100% settled on that price though!

> 
> 
> "Additionally the brig and command center both are only behind glass/grilles making break ins to these areas easier than normal."
> Why though

Dual reasoning. The main one is that abductor doors aren't see through by nature, so if you want to be able to see into/out of those areas then you need windows to flank the door. The other is that intentionally putting a flaw into it opens up more antag play opportunity. The windows still take time to break and countermeasures can be used to stop it, but the option is there.

I played with plasma windows but found them to be too strong and didn't quite fit the visual theme. If this ends up being a big hangup I could change it to be strictly walls flanking the doorways but then you'd run the risk of not knowing if people are outside or not.

**Comment by Whoneedspacee** [comment]
why such an expensive price if its so shitty for command and security roles

just doesnt make much sense to me

**Comment by JetBrody** [comment]
Because if you're really fast enough you could run on, grab the void core and put it in your fuckoff combat mech. That plus the experimental cloner on board and the alien tools gives it unique things that are difficult or normally impossible to access in game. 

As I said, if it's a real big sticking point I can change the cockpit  and/or security area to be fully walled off, but it would restrict vision.

**Comment by FloranOtten** [comment]
> Because if you're really fast enough you could run on, grab the void core and put it in your fuckoff combat mech. 

The core isn't really a massive bonus. A Phazon isn't very good on a shuttle, as it's only bonus is walking through walls, and there's not much need for that on the shuttle.

**Comment by Fikou** [comment]
> > Because if you're really fast enough you could run on, grab the void core and put it in your fuckoff combat mech.
> 
> The core isn't really a massive bonus. A Phazon isn't very good on a shuttle, as it's only bonus is walking through walls, and there's not much need for that on the shuttle.

i mean imagine blob that delays shuttle

**Comment by XDTM** [comment]
Are the walls indestructible like abductor ships?
Also, i'd suggest requiring alien tech to be able to order this shuttle, to make it more special.

**Comment by Fikou** [comment]
the shape is kinda ugly, you could make it more like a + than just a big square

**Comment by anconfuzedrock** [comment]
I very strongly suggest this be cheaper but tied to abductors in some way. be it the station getting the tech or abductors simply appearing on station. "station can get alien tech if they use it in 3 minutes or if its blob or rev" is kinda weak and dull tbh.

**Comment by FantasticFwoosh** [comment]
Could be more insidious with the failed clone decorative machines or something, i also agree the circular shape detracts from how pretty it could be by making it obnoxiously angled with wide interiors unflattering to the patterns, it could be a long sleek shuttle like the "train" ship, or one with multiple compartments such as the syndiate cruiser and play off just as well. 

Ayysteroid is not that much to look at.

**Comment by JetBrody** [comment]
It's shaped like that because it's shaped like a UFO you massive donk.

And no, the walls are not indestructible, they're the same walls a player can make using the alien alloy on a wall girder.

Someone had the suggestion of tying it to being unlocked by an abductor death, but alien tech would also work. I can look into that.

**Comment by OverlyGeneric** [comment]
I mean it's cool but it doesn't look good and seems only to be fancy gizmo abuse.

**Comment by ishitbyabullet** [comment]
> Could be more insidious with the failed clone decorative machines or something, i also agree the circular shape detracts from how pretty it could be by making it obnoxiously angled with wide interiors unflattering to the patterns

Can you draw a shitty ms paint image of what you're thinking of?  I can't think of how an flying saucer shaped shuttle could look like that in a good way without it being the equivalent of an away mission.

I can't even tell what you're thinking of in the first place.

**Comment by JetBrody** [comment]
Thanks to the *very patient* folks in coding-general I should be updating it soon to be gated behind researching alien-technology. I'll update it soon after I double check things to make sure it's kosher.

**Comment by shellspeed1** [comment]
ayyyy

**Review by SpaceManiac — APPROVED** [review]

**Comment by ishitbyabullet** [comment]
I wish I knew what they thought was wrong with it still.

**Pull request merged**
