### PR TITLE
Gives the nuke ops an assault pod in place of their teleporter

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
Image of Yaktocat

The pod however, has no destination to start.

For the price of 30 telecrystals you can buy a device which lets you select a station area to send the pod to (randomly picking a tile within it, assault pods aren't 100% accurate). The pod makes an explosive noise when landing. I made the assault pod code flexible enough that you can easily make an ERT or security drop pod if you wanted (dropping into lavaworld one day maybe)

The pod is covered in weak turrets (40 health, 20 damage bullets).

The pod can't launch again once launched.

The pod can't be launched if CHALLENGE OPS is active and the time limit has not passed.

> but kor what if the pod lands on someone op pls nerf

Telebombing already instagibbed people with no chance of fighting back, this is less accurate, a single use, and requires at least one op to go onboard.

> but muh teleporter

This is what I really wanted for ops when I first gave them the teleporter anyway, it's more thematic (see: assault ships in space battle vs nanotrasen having all the bluespace tech in general) and I think way cooler anyway

> but kor you didnt even remove the teleporter from the shuttle

I'll do that in another PR because box is frequently edited and I dont want to solve merge conflicts on this after we argue balance for 2 weeks. I'd also have to remove the consoles from every other map.

:cl: Kor
rscadd: Nuke Ops now have an assault pod. A 30tc targeting device will allow you to select any area on the station as its landing zone. The pod is one way, so don't forget your nuke.
rscdel: The teleporter board is no longer available for purchase in the uplink.
/:cl:

### CODE REVIEW

**Comment by Bawhoppen** [comment]
the pod itself looks kind of silly 
also syndie base remap someday :(

**Comment by KorPhaeron** [comment]
Looks better ingame when there aren't semitransparent grey boxes (what turrets look like in the map maker) over the corners

**Comment by Dorsisdwarf** [comment]
Pod itself looks cool. room it's in not so much.

**Comment by KorPhaeron** [comment]
Dunno what else to thrown in a tiny airless room honestly.

**Comment by Cebasiz** [comment]
so how does this even function

does the pod essentially overwrite where it hits, like physically transplant itself to the medbay, for instance?

or does it just teleport the ops in?

or ?

**Comment by RemieRichards** [comment]
@Cebasiz is smashes into medbay, replacing any tiles there, and killing anyone it lands on.

**Comment by Cebasiz** [comment]
oh, sure. 

i have no problem with the concept i guess but it looks big.

like really big. like if i took that thing and slammed it into security i'd have a pretty good chance of destroying several sec and the armory.

is that intentional?

does it not delete guns that get stuck under it?

**Comment by KorPhaeron** [comment]
>does the pod essentially overwrite where it hits, like physically transplant itself to the medbay, for instance?

Yeah.

**Comment by KorPhaeron** [comment]
They could pretty much do the same thing with telebombs already. Warp bomb+press button and everyone is dead before they can move.

And its 7×7 so pretty big yeah.

**Comment by KorPhaeron** [comment]
And yes it would delete the guns

**Comment by KorPhaeron** [comment]
Maybe it could make a warning report so you have a few seconds to clear the area

**Comment by Cebasiz** [comment]
well, it does have the power of a bomb. i'd just make it slightly more expensive because it does add slightly more power to the function of the teleporter (you don't have to use one of the onboard bombs) 

otherwise i don't think it's too bad. 

does it gib, though? the force of impact probably should but i can hear the complaining already.

and what happens if the disk is under it? i can see ops getting pretty pissed when it respawns in an inaccessible wall.

there's probably a few edge cases to iron out but i like the concept.

**Comment by KorPhaeron** [comment]
Doesnt gib.

And deleting the disk would respawn it in maint and the ops could easily scoop it up (but the chances of the disk being on the ground instead of on a person are tiny)

**Comment by Cebasiz** [comment]
ah, okay if it doesn't gib then no issue.

anyway looks neat stamp of approval etc

**Comment by GunHog** [comment]
I do like love the concept :+1: 
However, the mapping job is quite poor, on both the pod itself and the edits to the map. It seriously needs improvement, in my opinion.

**Comment by KorPhaeron** [comment]
Not sure how to improve a ball of metal covered in guns

**Comment by Ricotez** [comment]
more guns, obviously

**Comment by MrStonedOne** [comment]
Shuttle code will only delete anchored things in it's path, the rest is thrown to the edge

**Comment by Steelpoint** [comment]
I can look at restyling the map to be onboard of Syndicate war ship or something, it makes a bit more sense.

**Comment by KorPhaeron** [comment]
@Steelpoint 

Would be cool. Area is named mothership after all.

@Wjohn can you approve my somewhat spare form over function drop pod mapping if someone else is agreeing to remap the area once its merged?

**Comment by WJohn** [comment]
I think it's fine, honestly. Not like the current syndie ship is very pretty anyway.

**Comment by Nanotransistor** [comment]
This seems way more fun than the teleporter :+1:

**Comment by Anonus** [comment]
The syndicate should have some way to call the shuttle to the station, because if they use this and don't have someone to send the shuttle they'll get cucked in the most hilarious way.

**Comment by KorPhaeron** [comment]
>The syndicate should have some way to call the shuttle to the station, because if they use this and don't have someone to send the shuttle they'll get cucked in the most hilarious way.

This is already true of the teleporter plus they can carry the nuke on this if they're feeling particularly brave.

Should probably be a solution for that though.

**Comment by Giacom** [comment]
Maybe it would be better if it was smaller? Or how about instead of transporting an entire room, you have small pods which act like closets and allow players to jump into them. There can even be multiple closet pods dropping in or one for all 5.

**Comment by Bawhoppen** [comment]
Yea I think it would be better smaller, more of a tactical drop pod ya know

**Comment by Steelpoint** [comment]
Problem with making it smaller is that if the other PR letting you 'buy' new team mates come in then things get complicated.

What I can think of is making it that the pod can only reliably hold four or so people. 

Here's a mock of what I mean.

**Comment by Robustin** [comment]
YES

The game needs this.

The description should make it clear that its a one-way thing though. I can't imagine how many ops are going to evac to the pod and try to treat it like a shuttle.

**Comment by Iamgoofball** [comment]
I feel like the current pod design Kor has is fine. I'd love to roll out in one of those into medbay.

**Comment by Bawhoppen** [comment]
The design doesn't matter that much I guess. Can always be tweaked later on.

**Comment by Jalleo** [comment]
Bigger is always better a really tiny pod would be useless

**Comment by optimumtact** [comment]
@Robustin but imagine how funny it will be to see a nuke ops team try to evac in the pod and then die

**Comment by Anonmare** [comment]
Looks a lot like the Colonial Marines pod
Also would be hilarious if every OP went on and got cucked when they forgot their shuttle, though I've always liked the idea of having one OP stay behind on the shuttle with a bunch of consoles to act as Mission Control.

**Comment by Lumipharon** [comment]
My rock is cock hard.
I have been askin for a way to ram the syndie shuttle in the station for ages now. This is neat as fuck.
I think the area where the pod lands should cause an actual (weak) explosion however, so it's less like a pod jsut materialises on top of the station, and more like it blows a hole into it.

Also just add a menu to the military pda to move the syndie shuttle remotely (and syndie lock the damn thing so some dong fucker doesn't give it to the crew when they fail to activate their explosive implant)

**Comment by Shadowlight213** [comment]
@MrStonedOne @KorPhaeron is there a way to make a reusable version of this? Basically have a template pod that is used to spawn copies on demand for like single person pods?

**Comment by KorPhaeron** [comment]
Pods are their own subtype of shuttles, and the targetting item vars can be set to match the dimensions of said shuttle, so you can make these same as any other.

**Comment by Fox-McCloud** [comment]
>Maybe it could make a warning report so you have a few seconds to clear the area

Yeah, this; even if its' only 10-15 seconds, it still gives people the chance to move out of the way so they're not totally screwed.

**Comment by Lumipharon** [comment]
Make it so that the warning doesn't say where it will land, so everyone runs around like headless chickens and/or runs into the place where the pod ends up.

**Comment by Iamgoofball** [comment]
>closed

FUCK

**Comment by tigercat2000** [comment]
@Iamgoofball https://github.com/tgstation/-tg-station/pull/13758

**Pull request closed without merging**
