### PR TITLE
Resprited tails from fish infusion.

### PR DESCRIPTION
**Pull request by Ghommie**
## About The Pull Request
Back when I made #87030 I got a bit lazy when it came to spriting the fish tails and just ported a few ones from furry servers and made them inherit the hair color. Let me tell you, those sprites kinda look bad, and the fact that they've the same colors of hair is kinda... fuzzy, and doesn't sit well with me, like some hairball stuck in a cat's throat.

So I took upon myself to actually make them better (and also give gill overlays a couple extra pixels), at the cost of some of my free time and their wagginess, because fuuuuuck wagging animations for anything that isn't a somewhat amorphous fluffy tail. Fish don't wag their tail.

They also get one of several blue/grey tints if the owner of the part doesn't have a peculiar skin tone like lizards or ethereals or moffs.

Anyway, comparison time:

OLD:
immagine

NEW:
immagine

Both from byond screenshots but I cut and pasted them in paint instead of asesprite because old habits die hard.

## Why It's Good For The Game
Better sprites. Perhaps the selection of blues could be improved a bit idk.

## Changelog

:cl:
image: resprited fish tails from fish infusion.
/:cl:

### CODE REVIEW

**Comment by CCC23** [comment]
the long con to add shark girls to the game

**Comment by Ghommie** [comment]
I believe I should improve the sides of the long tail variant.

**Comment by Wallemations** [comment]
No more wag?

**Comment by Ghommie** [comment]
No more wag, but you can still flop.

**Review by Wallemations — APPROVED** [review]

**Pull request merged**
