### PR TITLE
Clown box of hugs now starts with a spare clown mask and medinana

### PR DESCRIPTION
**Pull request by carlarctg**
## About The Pull Request

Title.
Medinana's a new codersprited banana subtype, containing a reasonable amount of omnizine and banana juice. The seeds have zero endurance and lifespan since adding things to botany is definitely not in the scope of this PR

## Why It's Good For The Game

I always felt the box of  hugs was a bit not goofy enough. I mean if you give the clown a pink box with hearts on it, it's gotta have something clown related right? That's my reason for replacing the epipen with a banana. It also gives the clown a spare wig and mask, in case they lose their old one/it burns/they get cloned/whatever, since before there was pretty much absolutely no way to get a new one if you lost your first one.
I'm not exactly sure how _strong_ exactly the banana is as-is, but making it the only one of its kind should be enough, since it's not really that much stronger than just carrying around a few warm donk pockets.

## Changelog
:cl:
add: Clowns stationwide have gotten tired of being beaten up and having their wigs stolen. They now start with a medinana and spare wig in their bag.
/:cl:

### CODE REVIEW

**Comment by bgobandit** [comment]
stop spoonfeeding everything, git gud or order a costume crate

**Comment by cacogen** [comment]
I'd like more unique clowns items that aren't shit. I hate the golden bike horn, the water flower and I'm sure there's other trash you get in your inventory I dump straight away. I'm not sure another snowflake banana and spare mask (as Bgobandit says you can get another mask via costume crate) is going to cut it though. Mimanas exist and they're stupid and piss me off for reasons I can't articulate.

**Comment by Tlaltecuhtli** [comment]
they already get a banana for healing

**Comment by Repukan** [comment]
You can just use the seed editor to make more of those bananas.

Shit powercreep

**Comment by Farquaar** [comment]
Banana juice heals clowns, if I recall correctly. I don't see how adding a special banana makes any sense given that clowns start with a banana that is already capable of healing them.

**Comment by carlarctg** [comment]
> You can just use the seed editor to make more of those bananas.
> 
> Shit powercreep

FUCK 

yeah no idea how to fix that. probably best to close this PR since people don't seem to like it and it's going to take me forever to figure out how to make sure the plant can't be botany'ed
ty all for voicing ur opinion, and thanks repukan for pointing that out

**Pull request closed without merging**
