### PR TITLE
Fixes accesses and onstation flag on the elite bar pod, revises bathroom a little

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request

For the luxury elite bar pod:
This fixes accesses (eg no more bar access needed to open the closet) and sets the vending machines to no longer believe they are on station. The bathroom was also reworked a little so there's not so much awkward dead space.

Since it's also somewhat related to mining/lavaland and doesn't seem worth a PR on its own, this also sets the lavaland fridge to all access

## Why It's Good For The Game

Access fixes so miners can actually use what they pay for and less awkward bathroom.

The lavaland cafeteria seems about on the level with maintenance kitchens or other secondary areas and holds booze, so it doesn't seem sensible to have it chef locked.

## Changelog

:cl:
fix: Lavaland's cafeteria fridge is no longer access-locked.
fix: The mining vendor's bar pod's machinery no longer has access restrictions miners can't use.
fix: The bar pod's vending machines no longer believe they are on station.
qol: The bar pod's bathroom also has less unused space.
/:cl:

### CODE REVIEW

**Comment by JohnFulpWillard** [comment]
Isn't the vending machine's on station meant to make the items inside free? Miners all have credits and can spend it if they want drinks, even if it's a bar they bought themselves.

**Comment by YehnBeep** [comment]
> Isn't the vending machine's on station meant to make the items inside free? Miners all have credits and can spend it if they want drinks, even if it's a bar they bought themselves.

This was pointed out to me by someone that plays miner.

Space ruin vending machines are free... and perhaps more pertinently, lavaland vending machines are free too. It seems weird/inconsistent to me that the most expensive point item, then, charges you for the privilege of so much as wanting a glass to drink from.

But if that's what whoever has authority on these things wants, I can revert that part.

**Comment by Singul0** [comment]
add mirrors in the bathroom

**Comment by YehnBeep** [comment]
Kicking myself for missing that. Done and done ~

**Review by Maurukas — APPROVED** [review]

**Pull request merged**
