### PR TITLE
miasma temp and pressure

### PR DESCRIPTION
**Pull request by granpawalton**
## About The Pull Request
Miasma now spawns at normal bodytemp or 310.15 kelvin instead of 0 kelvin and it stops spawning above 315 kpa

## Why It's Good For The Game
Having a way to make something below 0 kelvin is very bad in many ways, also miasma requiring pressure conditions will only effect people directly trying to farm miasma from monkey rooms or etc

## Changelog
:cl: granpawalton
tweak: miasma now only spawns below 315 kpa
fix: miasma now spawns at room temperature instead of 0 kelvin
/:cl:

### CODE REVIEW

**Comment by HomocidlePancakes** [comment]
No more permanent plasma fires. Yeet.

**Comment by Tlaltecuhtli** [comment]
shouldnt miasma spawn only between 0 C and 100 C ? cold stuff shouldnt rot

**Review by Cw3040 — CHANGES_REQUESTED** [review]
Should make miasma generate at the internal body temp of the organism. So, for a perfectly healthy human it would be 37C; for a lizard it would be the ambient temp of the area etc

**Comment by granpawalton** [comment]
@Tlaltecuhtli it already doesnt spawn below -10C but i dont see any cases where it would heat up above 100C and not break the pressure requirement

**Pull request merged**
