### PR TITLE
Adds Cultural Sodas to the game

### PR DESCRIPTION
**Pull request by Hiynastrike**
## About The Pull Request

This PR adds 6 new beverages themed after the 6 playable species along with a unique vending machine to sell them from. As I've been told during development to not make these combat focused to deter powergaming. All the drinks give is a solid mood buff and cool you down

-Humans | Spaceraid (Gatorade): a sports drink that the Terra Raiders claim was their key to victory during an American football game. Non-Humans refuse to stomach it out of principle.

-Lizards | Rattsi (Moxie): a soft drink that promises to bring the flavors of the Lizard homeworld across the galaxy. Other species aren't a fan of it's rodent based ingredients

-Moths | Fuzznet (Fernet con Coca/Inka Kola): an unusual blend of tea created by mothpeople, it's impossible for others to drink it's fibrous contents

-Ethereals | Electro (Tropico): a beverage made from the electricity enriched fruits of the Ethereal planet. You need to be an ethereal to appreciate it's deep and fruity flavor

-Plasmamen | Plazz (Kvass): a beverage that harkens back to an earlier time in Plasmaman history, one of endless possibilities as the race stared upwards at the stars.

-Felinids | Spring Nya (Pocari Sweat): a sports drink popular amongst Cat-people in Space Japan, many tourist from across the universe have come to try it, and have been left very disappointed and physically unwell

The Exotic Drink Machine:
-Sells 10 of each drink
-has it's own fancy sign animation

## Why It's Good For The Game

I believe it fleshes out the universe when there's more products available on a station staffed with so many different alien species and the only snacks available are from Human dominated worlds that have general universal appeal.

## Changelog
:cl:
add: 6 new beverages
add: Exotic drinks vending machine designed to carry the 6 new beverages
add: Beverages also available from your local Robust Softdrinks machine
imageadd: each drink has it's own sprites for full and complete
imageadd: exotic drink machine has complete sprites and an animated sign
spellcheck: more of a note than a feature "fiberous" should be spelt "fibrous". I missed that, sorrry
/:cl:
exoticdrinks

### CODE REVIEW

**Comment by Mothblocks** [comment]
https://github.com/tgstation/tgstation/pull/60608

feature freeze, pr next month please

**Comment by LemonInTheDark** [comment]
I tried to warn you moth man

**Comment by EOBGames** [comment]
Hey so, I have to say I'm not a fan of this PR. I was the one who added lizard food recently, as well as wrote a lot of the current species lore on common core (https://github.com/tgstation/common_core), and I feel like this plays too much into the old stereotypes of the species rather than actually deepening their society and culture. The idea of cultural drinks is awesome, obviously- it's moreso the flavour presented that I take issue with.
The main example I'd point to here is the lizard soda: my aim with the lizard food PR was to show that lizards, and their food, and culture, was more than just rats on poles, and it does feel like a big step back to go straight back to that old meme.
If you wanna discuss ideas for changing this up so it's more in line with common core, or whatever, I'm available on discord (Emerald_or_Bust#1314) or I guess we could always discuss it here, given there's gonna be about a month of downtime on the feature.

**Comment by Hiynastrike** [comment]
> Hey so, I have to say I'm not a fan of this PR. I was the one who added lizard food recently, as well as wrote a lot of the current species lore on common core (https://github.com/tgstation/common_core), and I feel like this plays too much into the old stereotypes of the species rather than actually deepening their society and culture. The idea of cultural drinks is awesome, obviously- it's moreso the flavour presented that I take issue with.
> The main example I'd point to here is the lizard soda: my aim with the lizard food PR was to show that lizards, and their food, and culture, was more than just rats on poles, and it does feel like a big step back to go straight back to that old meme.
> If you wanna discuss ideas for changing this up so it's more in line with common core, or whatever, I'm available on discord (Emerald_or_Bust#1314) or I guess we could always discuss it here, given there's gonna be about a month of downtime on the feature.

that's a fair statement, as we probably have two wildly different personal or accepted lore about the Lizardpeople, mine including a tropical Miami-like city and a culture devoted to mining but I feel because alien worlds are probably like Earth (as in an entire planet filled with drastically different cultures, people, and languages) It shouldn't be too hard to accept that somewhere on Tizira there's a culture that has small mammals as a staple source of protein. I don't do this to disparage lizards as I play one myself. I would prefer wildly different views of Lizards to prevent their homeworld lore from turning into a Planet of Hats

**Comment by EOBGames** [comment]
> > Hey so, I have to say I'm not a fan of this PR. I was the one who added lizard food recently, as well as wrote a lot of the current species lore on common core (https://github.com/tgstation/common_core), and I feel like this plays too much into the old stereotypes of the species rather than actually deepening their society and culture. The idea of cultural drinks is awesome, obviously- it's moreso the flavour presented that I take issue with.
> > The main example I'd point to here is the lizard soda: my aim with the lizard food PR was to show that lizards, and their food, and culture, was more than just rats on poles, and it does feel like a big step back to go straight back to that old meme.
> > If you wanna discuss ideas for changing this up so it's more in line with common core, or whatever, I'm available on discord (Emerald_or_Bust#1314) or I guess we could always discuss it here, given there's gonna be about a month of downtime on the feature.
> 
> that's a fair statement, as we probably have two wildly different personal or accepted lore about the Lizardpeople, mine including a tropical Miami-like city and a culture devoted to mining but I feel because alien worlds are probably like Earth (as in an entire planet filled with drastically different cultures, people, and languages) It shouldn't be too hard to accept that somewhere on Tizira there's a culture that has small mammals as a staple source of protein. I don't do this to disparage lizards as I play one myself. I would prefer wildly different views of Lizards to prevent their homeworld lore from turning into a Planet of Hats

You do make a fair point about the planet of hats thing, though I still feel like rat soda is just too strange to be a mainstream thing- that said, I do think I've thought of a solution. Making it clear it's a weird and niche soda even for most lizards (something which fits nicely with it being based on Moxie, at least if my understanding of Moxie and it being an _acquired_ taste is correct) would help smooth over the worst of my issues with its flavour.

Also, just to mention, I didn't think you were doing this to fuck around with lizard lore, it's more just that I've started to get annoyed with the "haha lizard eat rat" meme with how often I've seen it, especially when I've now dedicated a fair bit of time trying to get them away from it. Sorry if I came off as accusing, ultimately I know this PR is looking to improve the culture of our non-human species and that's a good goal we both share.

**Comment by AlinaStarkova** [comment]
> 
>it's more just that I've started to get annoyed with the "haha lizard eat rat" meme with how often I've seen it

im just surprised people dont meme about cats eating mice as much considering cats dont just eat rats, they hunt them for sport lol.

**Comment by Hiynastrike** [comment]
> > > Hey so, I have to say I'm not a fan of this PR. I was the one who added lizard food recently, as well as wrote a lot of the current species lore on common core (https://github.com/tgstation/common_core), and I feel like this plays too much into the old stereotypes of the species rather than actually deepening their society and culture. The idea of cultural drinks is awesome, obviously- it's moreso the flavour presented that I take issue with.
> > > The main example I'd point to here is the lizard soda: my aim with the lizard food PR was to show that lizards, and their food, and culture, was more than just rats on poles, and it does feel like a big step back to go straight back to that old meme.
> > > If you wanna discuss ideas for changing this up so it's more in line with common core, or whatever, I'm available on discord (Emerald_or_Bust#1314) or I guess we could always discuss it here, given there's gonna be about a month of downtime on the feature.
> > 
> > 
> > that's a fair statement, as we probably have two wildly different personal or accepted lore about the Lizardpeople, mine including a tropical Miami-like city and a culture devoted to mining but I feel because alien worlds are probably like Earth (as in an entire planet filled with drastically different cultures, people, and languages) It shouldn't be too hard to accept that somewhere on Tizira there's a culture that has small mammals as a staple source of protein. I don't do this to disparage lizards as I play one myself. I would prefer wildly different views of Lizards to prevent their homeworld lore from turning into a Planet of Hats
> 
> You do make a fair point about the planet of hats thing, though I still feel like rat soda is just too strange to be a mainstream thing- that said, I do think I've thought of a solution. Making it clear it's a weird and niche soda even for most lizards (something which fits nicely with it being based on Moxie, at least if my understanding of Moxie and it being an _acquired_ taste is correct) would help smooth over the worst of my issues with its flavour.
> 
> Also, just to mention, I didn't think you were doing this to fuck around with lizard lore, it's more just that I've started to get annoyed with the "haha lizard eat rat" meme with how often I've seen it, especially when I've now dedicated a fair bit of time trying to get them away from it. Sorry if I came off as accusing, ultimately I know this PR is looking to improve the culture of our non-human species and that's a good goal we both share.

*-"A health tonic turned soft drink created in Opsilon, Tizira. Some lizardpeople are disgusted by it's unusual ingredients, but it maintains nationalistic popularity amongst Opsiloners."

*-"mmmm, the delicious taste of Opsilon in a bottle."

**Comment by EOBGames** [comment]
> *-"A health tonic turned soft drink created in Opsilon, Tizira. Some lizardpeople are disgusted by it's unusual ingredients, but it maintains nationalistic popularity amongst Opsiloners."
> 
> *-"mmmm, the delicious taste of Opsilon in a bottle."

Better than I could have come up with- fits perfectly with the Moxie comparison.

**Comment by KittyNoodle** [comment]
Ethereals can’t taste

**Pull request closed without merging**
