### PR TITLE
[s]Medical Remap: Chemistry/Genetics Swap, Chemist/Medical Doctor Merged Into One Job

### PR DESCRIPTION
**Pull request by Iamgoofball**
dreammaker_2017-11-09_18-44-30
scrnshot2
scrnshot3

With the change to Sleepers (#32535), Medical will need to produce medicine itself instead of relying on sleepers to heal, but they now allow you to halt the progression of death(and everything else) on a mob, putting them in complete stasis until removed.

To balance this, Chemistry got a lot of buffs to creating meds (#32550), and as such are able to mass produce needed medicines, chemicals, and ~~drugs~~useful misc. reagents. To make sure they can produce everything they need, they have swapped with Genetics for lab space, and been given additional labs to produce in to ensure they don't destroy the rest of the lab/medbay/station while doing their job.

Medical Doctor and Chemist have been merged.

Genetics got a bit of a downsize due to having a LOT of extra room they didn't really need to function at optimal levels. The Morgue trays were reduced and moved out front of the lab, since
1. people dont use trays often
2. when they do, nobody sees the lights indicating "hey there's a ghost clone me"
3. people should be processing corpses at the ~~kitchen for those tasty burgers~~crematorium/chapel

Due to cloneloss not being a thing after you leave the cloning pod (#32572) the Cryo section has been downgraded to one tube, and 2 more sleepers replace the extra tube, for more patient stasis.

@KorPhaeron @Armhulen @Ausops will need this testmerged alongside:
#32572
#32550
#32535

for maximum effect

Q&A:
**chemistry autism fort wtf**
I'm aware it looks ugly and is a bit 'tism forty, but I plan to do an aesthetics pass, and the r-walls are mainly there to prevent explosions from propogating too far.

**why cant i steal the chem dispenser**
fuck off

**genetics needs more space**
I'm willing to debate this with you.

**fuck you**
8====D

**chemistry cant be talked to directly**
dreammaker_2017-11-09_16-27-40

### CODE REVIEW

**Comment by kevinz000** [comment]
Very good for a goof pr

**Comment by kevinz000** [comment]
Only complaint is lack of public windoor though. If you're concerned about security make it behind an airlock or something.

**Comment by kevinz000** [comment]
Also you going to update the other maps or let their makers do it.

**Comment by Iamgoofball** [comment]
other maps will be updated by their makers, i aint about that life and we only support #bestmap #boxmap

**Comment by Iamgoofball** [comment]
public windoor was replaced by requests console and wall mounted hallway vendor

**Comment by Iamgoofball** [comment]
>double walls are horrifically degenerate and you should be ashamed, i have an idea or two that would move things around slightly and get rid of them

negative, the point is blast resistance bby

>chemistry doesn't really need r walls and the double r walls are extremely ridiculous, it looks more secure than the armory

read above

>trays should have dark coloured floor under them for old times sake

see aesthetic pass bit

>i don't know why chemistry has dark floors now it doesn't look fitting imo

^

>you don't really need a sleeper in there do you? I'm assuming it's to test on the monkeys but it seems out of place

puts the monkey in complete stasis

**Comment by Qbopper** [comment]
also it fucks over botanist shitters stealing the chem dispenser so even if i didn't like the pr i would be obligated to support it

**Comment by Qbopper** [comment]
there has to be a better solution to chemists blowing up than making the department more secure than pretty much anything but the AI sat, i'm not sure why you want the blast resist so badly

if it's because retard chemists making a breach in the station that's fine, get someone to fix it, that's how the game works

if it isn't then idk please explain i don't get it

**Comment by AuroranAI** [comment]
The double doors into chemistry looks goofy as hell, Maybe shift the bottom door down one and add an rglass window?

The maint to the right of chemistry looks goofy as shit since there's no real point of having a tiled entryway into research. Maybe strip the floor down to plating and take out the two buffer doors?

If you get rid of the double rwalls you can shift the upper heater up a space and use those triple-wide doors in the heater room, getting rid of the ugly double doors there(if those have a up-down sprite, anyways).

**Comment by deathride58** [comment]
If TG had hippie's lcasschem, then the layout would actually be pretty decent

But locking chemistry behind double r-walls without lcasschem...?
This PR would work a lot better on hippie than it would here.

**Comment by swindly** [comment]
untitled

**Comment by deathride58** [comment]
image
Okay what the fuck is this

That little chamber there is supposed to connect science with genetics, which is now chemistry.

Goof are you high or just horrible at mapping

**Comment by Iamgoofball** [comment]
>if it's because retard chemists making a breach in the station that's fine, get someone to fix it, that's how the game works

If admins are okay with it, then I'll revert it so it's easier to get in

**Comment by Iamgoofball** [comment]
Whoops

**Comment by Iamgoofball** [comment]
>That little chamber there is supposed to connect science with genetics, which is now chemistry.

Intentional

**Comment by Qbopper** [comment]
apologies for fuckhuge post

@swindly that's just a symptom of how the mapping works it should look fine in game i think

@deathride58 ty forgot to add that to my OG post that looks really bad and is just lazy, but he did say he was gonna make a pass so hopefully it wouldn't be left as is

@Iamgoofball i just wanted you to explain your reasoning for the blast protection, that's all

just to hammer home how abundantly ridiculous the number of rwalls is here's other secure areas



the engine



tcomms



armory



brig (it even has areas with no rwalls)



bridge + more



proposed chemistry rework

do you see why i take issue with it

**Comment by Iamgoofball** [comment]
Just needs less rwalls

**Comment by JJRcop** [comment]
This should be a maint door, it was removed.
well

If you intended it, not great.

**Comment by Qbopper** [comment]
i'll mock up what i had in mind hang on

**Comment by Iamgoofball** [comment]
Or blast resistant walls somehow

**Comment by PKPenguin321** [comment]
The science airlock that formerly connected with genetics should just be reskinned to a maint airlock now

**Comment by deathride58** [comment]
image
what the fuck
three welding fuels when chemistry can pump out infinite welding fuel anyhow?

**Comment by AuroranAI** [comment]
image
The only issue is how the asthetics look with the rest of the map

**Comment by Qbopper** [comment]
excuse mouse handwriting i forgot paint has a text tool

**Comment by KorPhaeron** [comment]
>double walls everywhere

>four chemist slots

>no morgue

>no request desk

>maint door gone

goof please

**Comment by swindly** [comment]
Five chem dispensers for four chemists to make medicine for three doctors to apply.

**Comment by AuroranAI** [comment]
for no doctors to use and for randoms to self serve outside medical*

**Comment by Iamgoofball** [comment]
>double wall
Will replace with le plastic
>4 chemist slots
Read the OP
>no morgue
Read the OP
>no request desk
Read the Q&A
>no maint door
I'll readd it

**Comment by KorPhaeron** [comment]
if you want like seventy people to be allowed in chem why not just remove the chemist job and let med doctors have access

**Comment by Qbopper** [comment]
@KorPhaeron i think that was his eventual goal

**Comment by JJRcop** [comment]
A neat idea is two intercoms on either side of the same wall, next to the fridge, both on a new chemistry frequency, and both open mic and speaker.

**Comment by Qbopper** [comment]
wait yeah what the fuck why is there 5 dispensers apparently i can't count

we don't need that many, 4 would be plenty

**Comment by Iamgoofball** [comment]
5 is in case 1 gets stolen or blown up

And yeah I wanna merge MD and chem but >>>editing every map file in 1 pr

**Comment by deathride58** [comment]
@KorPhaeron I proposed that idea on Cit for different reasons and folks ended up screeching for hours. If the suggestion was received horribly in an environment where there's more people ERPing than there are people powergaming, I don't think people would be willing to accept that idea in an environment where powergaming runs rampant, regardless of how good of a change it'd actually be.

@Iamgoofball Quit smoking. If you just want chemistry to have more chem dispensers, just make use of the fluff-filled glass table to plop an extra chem dispenser down. You don't need to add 3 extra chem dispensers just because chemists are too dumb to make meth in chilled dispensers. The entire chemistry > genetics swap is also pretty dumb, especially with the justification of "It's more secure". If you wanna look at secure chemistry done right, take a look at old hippie's chemlab. All you have to do is replace the normal walls of chemistry with r-walls, nothing more, nothing less. The chemistry > genetics swap also fucks with genetic's status as a department belonging to both medical and science, as suddenly there's an entire department between genetics and science.
The justification of "genetics had so much unused space" is also pretty dumb, considering your chemistry redesign has even more unused space than genetics had.

**Comment by newfren** [comment]
Why does chemistry get twice the monkeys genetics does. How much synthflesh do you think I'm making.

**Comment by Qbopper** [comment]
for real though having 5 chemistry machines in case one gets blown up (get good) or stolen (your own damn fault considering how much stuff there is between the machines and freedom) is hugbox as hell, and i don't call shit hugbox-y at all

**Comment by KorPhaeron** [comment]
How did we get from "sleepers are are lazy and boring" to "five chem dispensers inside fort knox"

**Comment by Iamgoofball** [comment]
Because people whined removing chems from sleepers is the end times and chemistry is the most interesting part of medbay

**Comment by Iamgoofball** [comment]
Viro is just heal viruses and genetics is hulkxray spam

**Comment by PKPenguin321** [comment]
Half of goof's PRs hugbox medical when he's trying to do the opposite because he has no idea what he's doing is why, Kor

**Comment by deathride58** [comment]
Also:
>rwalls are there to stop explosions from propagating too far

image
This is the result of one single methsplosion in a 100u beaker, the average methsplosion caused by the average unrobust chemist.
The damage is laughable at best, you don't even need internals to repair it.
You shouldn't hugbox chemistry to compensate for embarrassingly unrobust chemists.
Hugboxing chemistry to the point where accidents cause no damage whatsoever is a sign that you should consider actually playing the game.

**Comment by Iamgoofball** [comment]
alright then, I'll show you why this is a bad idea

**Comment by Iamgoofball** [comment]
@KorPhaeron get in IRC

**Comment by Iamgoofball** [comment]
@deathride58 @KorPhaeron @Qbopper 
dreammaker_2017-11-09_18-36-14
dreammaker_2017-11-09_18-36-23

there, rwall spam removed, exterior walls still r-wall but that's to prevent just welder-wrench-hey i have access to infinite murderchems

the triangle bit was turned to metal walls because it looks hella cool and less boxy

added a break-in point in the monkey pen

**Comment by Iamgoofball** [comment]
additionally I'm just gonna bite the bullet and merge MD/chemist

**Comment by newfren** [comment]
why does this need to be secure

**Comment by Iamgoofball** [comment]
@newfren literally makes the deadliest shit in the game that isnt a max cap(and then those sometimes)

also the lifeblood of medbay

**Comment by JamesDenholm** [comment]
This is still fucking insane son

**Comment by qbmax32** [comment]
why dont we make the medical system more complex and make it harder to slap a bruise pack and bandage on a wound to make everything better instead of stupid, pointless changes

**Comment by newfren** [comment]
No I mean like why does it need the [s]

**Comment by Iamgoofball** [comment]
@qbmax32 players dont want that

@newfren oh didnt want to spam when closing/renaming/reopening, i've been chewed out for not renaming the PR before

**Comment by Iamgoofball** [comment]
@JamesDenholm welcome to goofcode

**Comment by Qbopper** [comment]
ignoring the other problems WHY DID YOU KEEP THIS IN **FUCK**

**Comment by Iamgoofball** [comment]
read the meme

**Comment by Qbopper** [comment]
your opinion is straight up incorrect multiple wlals next to eachother never looks good

**Comment by Iamgoofball** [comment]
it blew up instantly, blast proof walls did nothing

marked as [s] because i dont want to listen to ooc circlejerk about "winning against goof"

**Comment by Qbopper** [comment]
lol

**Comment by epochayur** [comment]
what the hell is going on

**Comment by Arianya** [comment]
we won against goof!!

**Pull request closed without merging**
