### PR TITLE
You can now turn the SM Off

### PR DESCRIPTION
**Pull request by GuillaumePrata**
## About The Pull Request
This PR changes how the Hypernob Crystal works and add 1 crystal into CE's locker. Something important as turning the main engine offline should have their approval (Or an Axe if there is no CE around...)

Before you could use it to space proof clothes or insert into atmos device to prevent internal reactions.
Now it can also be used on the SM to turn it off, resetting it to the inert stage it has at roundstart.

To turn the SM off it needs to have less than 300 of Internal Energy and then you just have to slap the crystal on the SM.

Since maintainers had a few concerns about the pressure proofing on the original PR, I reworked the HN crystal instead of making a new item.
As a crystal is given at roundstart, we can't have pressure proofing anymore, else people might just consume the crystal like that and break the main point of this PR, having a way to turn the SM off 20-30 minutes in.
Preventing reactions inside atmos devices is something I rarely see done, so I doubt it will conflict with the goal of the PR and won't need to be removed.

I can swap to a brand-new item if maintainers request.

## Why It's Good For The Game

hn crystal delam

This is something I thought was good for the game for years and I'm annoyed I didn't code it earlier...
It's the first step on other bigger changes I may, or may not, do to the SM soonTM.

With the option to turn the SM offline, building better setups becomes a lot easier to manage and if someone accidentaly trigger a SM shard you can turn it off again (with a small prep) instead of just spacing it or rushing a SM chamber at cargo so the shard doesn't explode.

Without this option, the best way to build your custom setup is to RUUUUUSH at roundstart as fast as you can before the station goes dark and the assistants are breaking in to do your job.
That is a horrible meta to have, extremely hostile to engineers that want to try a complex setup and for the crew that is worried about going powerless and early shuttle calls.

Now we can start doing a healthier meta. We start the SM with a very basic setup, let the SMES charge, setup solars if you want more time and start preparing the gas and materials your setup will need.

When everything is done, you lower the SM power to turn it offline, build your setup with as much patience as you need since the SMES can hold the station's lights On for a good time while you enjoy the best side of the SM.
Custom setups with friends.

## Changelog
:cl: Guillaume H. Prata
add: Hypernoblium crystals can now be used on a low power SM [Less than 300 of Internal Energy] to turn it off. Let the SM charge the SMES units with a basic setup while you do the prep work, then put the beast to sleep while you work on your custom setups without any rush.
balance: A Hypernob Crystal was added to the CE's locker so talk with your boss when it's time to upgrade the SM, or bring your axe to their office I guess...
balance: Hypernob Crystals can't pressure proof clothes anymore.
/:cl:

### CODE REVIEW

**Comment by JupiterJaeden** [comment]
I don't see why this functionality couldn't be added to a new item instead of stripping the previous functionality of hypernob crystals FNR. You haven't provided any balance reasons why hypernob crystals should not be able to be used for pressure proofing. "You can do it other ways" isn't a balance reason. There are lots of ways that different departments can achieve the same result in different ways, this doesn't inherently make anything unbalanced.

**Comment by GuillaumePrata** [comment]
> I don't see why this functionality couldn't be added to a new item instead of stripping the previous functionality of hypernob crystals FNR.

On #60436, the PR that added the crystals, both Mothblocks and Lemon brought up concerns about how it worked.
Mothblocks said that she knew the Crystallizer would end up as a machine where you sit in your department doing tasks and get power ups.
Lemon said it was on his plan to remove space proofing being a widely available thing to achieve, we have Genetics, Xeno, HN Crystal, Augmentation and possibly a few more.

> There are lots of ways that different departments can achieve the same result in different ways

A lack of pressure is a nice power up for most departments, but Engineering is the department with the job to fix breaches.
It is silly that they can instead give pressure potions to the crew and make a huge slice of the main task the department has, keeping the station in a livable condition, not that important anymore.

And something I forgot to add to the PR body, as a crystal is given at roundstart, we can't have pressure proofing anymore, else people might just consume the crystal like that and break the main point of this PR, having a way to turn the SM off 20-30 minutes in.

**Comment by JupiterJaeden** [comment]
> Mothblocks said that she knew the Crystallizer would end up as a machine where you sit in your department doing boring tasks and get power ups.
> Lemon said it was on his plan to remove space proofing being a widely available thing to achieve, we have Genetics, Xeno, HN Crystal, Augmentation and possibly a few more.

The way space proofing works currently in many cases makes it difficult to achieve COMPLETE space proofing from just one department, which I think promotes inter-departmental cooperation or at the very least, more interesting combinations of space proofing solutions. Why do we need to start stripping that content more? For what reason do we need to make space more absolutely dangerous?

As for the crystallizer machine promoting just staying in atmos, well, you could say the same for any job that primarily involves just sitting in your department making shit, such as xenobiology, genetics, and even ordinance. By this logic we should remove those as well. Maybe there is a larger debate to be had here, but I don't see why hypernob crystals in particular should be targeted.

> A lack of pressure is a nice power up for most departments, but Engineering is the department with the job to fix breaches.
It is silly that they can instead give pressure potions to the crew and make a huge slice of the main task the department has, keeping the station in a livable condition, not that important anymore.

I have never once seen engineering just give up on fixing breaches because they made hypernob crystals lol. Also hypernob crystals do not fully space proof you by themselves, so it wouldn't be enough anyways?? 

> And something I forgot to add to the PR body, as a crystal is given at roundstart, we can't have pressure proofing anymore, else people might just consume the crystal like that and break the main point of this PR, having a way to turn the SM off 20-30 minutes in.

I'm suggesting you make a new item, instead of just randomly stripping the functionality of an old item and shoving new functionality in. What you stated here is not a concern if you just... make a new item.

**Comment by Jackal-boop** [comment]
Keep the old functionality. The crystals are already rarely produced and I doubt this will make them much more common. Plus the crystals require much more knowledge to make them compared to say genetics mutations or what have you. Very silly to remove it

**Comment by GuillaumePrata** [comment]
> Why do we need to start stripping that content more?

IMO, Science should be the "Space proof people" department with mutations, MODsuits, Xenobiology, Augmentation and possibly future DNA infusions. It is a nice identity for the department to keep.

> By this logic we should remove those as well. Maybe there is a larger debate to be had here, but I don't see why hypernob crystals in particular should be targeted.

This is a big discussion indeed, I'm just nibbing at HN crystals as maintainers already expressed concerns in the past.

> What you stated here is not a concern if you just... make a new item.

Also added to the body, but the removal is to fix concerns maintainers had in the past. If they changed their opinion, I will gladly make a new item.

**Comment by DaydreamIQ** [comment]
I'd argue it'd make more sense removing the presssure proofing capabilities from Xeno rather than Atmos. This just kind of spits in the face of the people who spend the entire shift making the stuff in the first place, move it to its own item and leave the hypernob crystal be

**Comment by JohnFulpWillard** [comment]
This helps my broader goals of removing xenobiology content from atmos which I think is a net positive

**Comment by HoodMilk** [comment]
Given that Hypernob as a gas stops things from reacting, the crystal stopping the SM is very flavorful and makes more sense than randomly giving pressure protection.

**Comment by MTandi** [comment]
Having the option to do the same/similar thing in different ways is a fun part about ss13. If you have no access to science, this is a nice workaround. It is time intensive and makes crystalizer worth bothering with. 

You will barely see HN crystals made for this niche use case. You could just order an inert shard in a box and make your own chamber instead.

Move space proofing to some other crystal or make the crystal grindable for HN dust with old functionality if you don't want to mix logic. Is it really an issue to have a single use space proofing in heads office? The CMO has health analyzer implant, so why not?

**Comment by Likteer** [comment]
Not much new to say about the balance change itself, 
but I REALLY don't like it being vaguely mentioned in PR body, then left for changelog.

It's a change that's going to affect much more people. It should be in the title.

**Comment by Pickle-Coding** [comment]
300MeV is quite an arbitrary energy level, so it would suck if the CE guessed wrong and tossed their crystal away for nothing. Also waiting for a specific number to be reached feels kinda weird.

I think it might be better if the hypernoblium crystal just got stuck onto the SM (it's hypernoblium so it's okay) until it reaches the requirements to be effective, or if it just applied an effect on the SM that shuts it down when it meets the requirement. You should also make it remove the matter energy amd check if the sum of the SM energy and matter energy are below 300MeV.

**Comment by FlufflesTheDog** [comment]
I do love the concept of being able to properly reset a supermatter crystal, and it's something I've wanted for a long time.
But I also don't feel great about how this does it. Just slapping an item that spawns round-start on it doesn't feel very interesting. Something like a gas which can actively sap internal energy for example sounds like it could be more interesting and engaging, as mentioned above.

Worth noting as well, if isn't actually _that_ difficult to do even extensive redesigns with the supermatter active. Letting the energy drop reasonably low will greatly decrease heating, remove the gravitational pull, and decrease waste production enough to make it safe to use the RPD inside the chamber, or pump all the coolant into the chamber for long enough to tear up piping without making a mess of the air.

About the pressure-proofing, (which I admittedly only found out even existed a few days ago,) I'd be quite sad to see it go. Engineering is perhaps the one department which actually _needs_ some form of space-proofing to do their job in many cases. It just doesn't feel right wearing a modsuit everywhere, and imo it's a bit odd for something so close to their job description be made more reliant on other departments.

**Comment by MTandi** [comment]
Guys, how about making SM decay on its own when there is no gravity?

Engineering can then go and turn GravGen off temporarily to change SM setup and turn it back on when done.

**Comment by GuillaumePrata** [comment]
> Is it really an issue to have a single use space proofing in heads office? The CMO has health analyzer implant, so why not?

The implanter has only 1 use, implant someone, you can't missuse it.
The HN crystal would have 3 uses, but we all know that most of the time the CE would just pressure proof their wintercoat instead of using it for future SM upgrades.

**Comment by carlarctg** [comment]
> > Is it really an issue to have a single use space proofing in heads office? The CMO has health analyzer implant, so why not?
> 
> The implanter has only 1 use, implant someone, you can't missuse it. The HN crystal would have 3 uses, but we all know that most of the time the CE would just pressure proof their wintercoat instead of using it for future SM upgrades.

So just put it on a different frickin' item, what the hell is this logic?

**Comment by GuillaumePrata** [comment]
> 300MeV is quite an arbitrary energy level, so it would suck if the CE guessed wrong and tossed their crystal away for nothing. Also waiting for a specific number to be reached feels kinda weird.

True, I just choose a low number the SM achieves easily if it is left alone on a "passive" setup.
I didn't want to overcomplicate it in any way, having a complex system would go against the goal of changing the SM meta.

> I think it might be better if the hypernoblium crystal just got stuck onto the SM (it's hypernoblium so it's okay) until it reaches the requirements to be effective, or if it just applied an effect on the SM that shuts it down when it meets the requirement.

Something similar was my first draft of the idea, would work like the destabilizng crystal, but I couldn't figure out a neat way to have both work on the same system and not conflict.
I'll try to think more of ways to do it again because it is honestly just a better UX, people wasting their roundstart crystal is not something that should happen so I will likely just make that we can't use the Crystal on higher power SMs.

**Comment by GuillaumePrata** [comment]
> So just put it on a different frickin' item, what the hell is this logic?

> Since maintainers had a few concerns about this functionality in the PR that added it, I put it on the HN crystal instead of making a new item.

It is in the PR body, removing the pressure proofing is something maintainers want as far as I'm aware and the new functionality fits more with what Hypernoblium is design wise, a gas that stops reactions.
If they ask me, I make it a new item instead.

**Comment by carlarctg** [comment]
This 'removes xenobiology content' logic is also uh, clearly not grounded in anything resembling actual gameplay. Xenobiology can FIREPROOF clothing, not PRESSURE-PROOF it. The pressure proof potion they _technically_ have is only obtainable through a stupid convoluted overcharged extract which takes thirty minutes to set up, at best, if you don't get unlucky with RNG. It's literally more common to see rainbow slimes than a single pressure potion, which i have never seen ingame.

It doesn't 'remove xenobiology content', it just 'removes [...] content'.

Crystals making it so atmos techs sit in their department for 30 minutes to get buffs? They're not personal buffs, they're for the station. What else could an atmos tech _possibly_ do, with how gas reactions work?

Unlike 'Xenobiology', when pressure crystals are made, they are routinely handed off to the crew by atmospheric technicians, allowing everyone to benefit from them. Meanwhile xenobiology is so stupid convoluted and bloated that it is VANISHINGLY rare for the station to gain any benefits from even a perfect xenobiology run. You always, ALWAYS have to barge into the subdepartment to scrounge for something, unlike atmos techs and their pressure crystals.

**Comment by SkeletalElite** [comment]
Also like, why should there be a way to turn off the SM.

Isn't the whole point that this crystal is like super dangerous and needs to be maintained carefully. Why does it need an "off button"

**Comment by GuillaumePrata** [comment]
> Also like, why should there be a way to turn off the SM.

From the PR body.
Without this option, the best way to build your custom setup is to RUUUUUSH at roundstart as fast as you can before the station goes dark and the assistants are breaking in to do your job.
That is a horrible meta to have, extremely hostile to engineers that want to try a complex setup and for the crew that is worried about going powerless and early shuttle calls.

> Isn't the whole point that this crystal is like super dangerous and needs to be maintained carefully.

Nothing changes in how dangerous the crystal is, the only way to turn the SM off is when it is on extremely low power already.

Experienced players can already uograde a SM without issues while it is on low power mode because it far from dangerous on that state.

**Comment by Inari-Whitebear** [comment]
Finally an answer to my question: "Why is the SM off at shift start?"

**Comment by Jackal-boop** [comment]
you should put that your removing h-nob space proofing in the title

**Comment by Jackal-boop** [comment]
also id like to re-iterate that removing space proofing really isnt needed, atmos is the one form of space proofing that really requires any skill

**Comment by EricZilla** [comment]
It would be funny and on brand if dusting the psychologist would also turn it off, since they have a deep connection to the supermatter crystal

**Comment by Prussen** [comment]
I like the idea and lore-wise it makes sense, but there's no reason to strip content from atmos (something that should really be mentioned in the title). It's pretty much one of the only ways of becoming space proof mentioned that actually requires some time and thinking - genetics is a cookie clicker game until you get the right mutation and MODsuits really don't require that much thought to put together and are rather bulky and inconvenient in comparison to the other options. Even if as an atmosian you are using a hypernob setup someone else taught you, you'll probably need to understand it in order to actually use it successfully. 

Perhaps if another atmos item was given space proofing ability this PR would be good. Maybe metallic hydrogen elder atmosian armour needs some love after the nerfs (unrelated: the axe needs a buff, it requires significantly more effort to produce but has the same stats as the cleaver, something you can get in 1 minute). Though admittedly this wouldn't make that much sense without some changes and would likely make space proofing the whole crew harder without the helping hand of genetics, but that might be what you're looking for.

**Comment by SinfulBliss** [comment]
This destroys one of the ONLY ways atmospherics can actually help the crew on LRP. 

This turns an entire crystallization process, forming these hypernob crystals, which atmosians have worked at learning, into a way to make SM reset buttons? Why would you even need several of these? Not a fan

**Comment by rasepretep** [comment]
I need to point out that the PR removes a major feature of the hypernoblium crystal, pressureproofing, but it's only very off-hand mentioned in the body.

It's not in the title, there's no Removal tag (although the feature removal is tagged a Balance, which is questionable whether or not it's the right one for it), the first line that mentions it just glosses over the fact as "Now it can **also** be used on the SM to turn it off" and then a couple of paragraphs later mentions that the pressuproofing is being removed because there is a round start crystal.

I'd much prefer to have PRs clearly labeled in what they do, if the change is significant enough, rather than labeling them in such a way that makes them look like the coder is trying to hide something from first glance view, whether or not that was the intention. That just fosters mistrust.

On the subject of the PR itself, I'd be interested to see how often it'll be used. Presumably the idea is that engineering sets up the basic SM setup, charges the SMESes to full and then stops the SM to upgrade it, without station going out of power. Whether engies are going to bother with the extra step is anyone's guess.

**Comment by Pickle-Coding** [comment]
People are overreacting lol. Completely passive pressure proofing for the entire round isn't a very interesting feature worth keeping. It needs to go regardless of this PR.

**Comment by Lufferly** [comment]
Atmospheric technicians should be fixing areas of the station that have low pressure, not sitting in their cave for a half hour and coming out with magic space rocks that make hull breaches not scary anymore. This is a good pr, though correct me if im wrong, but just looking at the code it seems that you are supposed to use the crystal on the SM, and I feel like people might just throw it at the SM and get confused why it doesn't work.

also why didnt u copypaste your entire pr body into the title?

**Comment by dragomagol** [comment]
Fikou requested this be closed but got locked out of github, owned

**Comment by TheVekter** [comment]
image

**Comment by GuillaumePrata** [comment]
While more interesting, it wouldn't fix the main goal of the PR.
The hostile meta we have to deal with every round around the SM and the conflict of interests, crew wanting power to be setup as fast as possible because the most basic bitch SM is enough to power all the station, and the engineers wanting to do cooler setups that would take too much time and leave the station dark.

Still, I want to make the SM go offline for flavor alone so I will see if I can get the Freon idea working to salvage something of the original intent.

**Pull request closed without merging**
