### PR TITLE
Supermatter Area / Air Alarm Tweak

### PR DESCRIPTION
**Pull request by Penguaro**
:cl: Penguaro
tweak: Box Station - The Vents and Scrubbers for the Supermatter Air Alarm are now isolated from the rest of the Air Alarms in Engineering.
/:cl:

[why]: # (Please add a short description [on the next line] of why you think these changes would benefit the game. If you can't justify it in words, it might not be worth adding:) 
The Air Alarms for Engineering include the specific scrubbers of the coolant loop for the Supermatter Engine. As such, it is easy to inadvertently disrupt the coolant when changing the operating mode on the air alarm in an emergency. Also as map edits go through, sometimes the scrubbers and vents are renumbered and if a player doesn't check each round, they may set up the wrong scrubbers for the coolant loop. Now there is a new area designated for the Supermatter Engine that forces the Air Alarm in the chamber to just recognize the three vents/scrubbers instead of the rest of the room.

### CODE REVIEW

**Comment by Penguaro** [comment]
If this is accepted, I'll do this for the other stations with Supermatter Engines as well.

**Comment by CPTANT** [comment]
Yes this is a good change.

Had several instances of air alarm settings in engineering fucking up the supermatter.

**Comment by octareenroon91** [comment]
Maybe my toaster will even load the vent/scrubber control screen with this change.

I'd been forced to use straight 'draught' or 'contaminated'

**Comment by Penguaro** [comment]
Edit - Fixed PR notes for grammar.

**Comment by lzimann** [comment]
Does this add an air alarm to the SM area?

**Comment by Penguaro** [comment]
@lzimann No. It just changes the area of the SM Chamber from Engine to a new area, Engine_sm. This forces the air alarm, vents, and scrubbers to isolate from the rest of engineering.

**Comment by lzimann** [comment]
You should probably add one so it's easier to control the scrubbers there, otherwise you will have to build one yourself when you want to do that.

**Comment by Penguaro** [comment]
@lzimann There already is an air alarm right there. Current map design has it unlocked at round start as well to aid in SM setup.

**Comment by lzimann** [comment]
Yes, but is the airlarm on the new area?

**Comment by Penguaro** [comment]
No physical equipment was moved. Only Areas were changed. This was tested and the Engine_SM area Air Alarm only comnects to the vents and scrubbers in chamber. The external Engine area air alarm no longer sees those three scrubbers and vents.

**Pull request merged**
