### PR TITLE
better impaired sight overlays

### PR DESCRIPTION
**Pull request by actioninja**
## About The Pull Request

as title
looks like this:

Partially impaired (lockers):
first one

more impaired (welding masks):
more

## Why It's Good For The Game
overlays in fact support transparency now

## Changelog
:cl:
imageadd: better impaired vision overlays
/:cl:

### CODE REVIEW

**Comment by TheSilverNuke** [comment]
No more checkered vision...

**Comment by cacogen** [comment]
we live in the future

**Comment by MrPerson** [comment]
This is so good looking that in a year when anyone sees the old sprites they're going to vomit

**Comment by MrDoomBringer** [comment]
history being made before our very eyes

**Comment by Jared-Fogle** [comment]
What does nearsighted look like?

**Comment by actioninja** [comment]
top one

**Comment by LemonInTheDark** [comment]
god damn action

**Comment by Jared-Fogle** [comment]
Played a few rounds of this, it looks great but it's overtuned a lot. Nearsighted is extremely difficult to play now, and you can barely see anything with a welding helmet/goggles on. Were these intentional? Would you accept a PR that makes them a bit more similar to their existing values?

**Comment by Rohesie** [comment]
Looks like a good outcome if welding helmet/googles impair your vision and nearsighted without glasses are an actual problem.

**Comment by actioninja** [comment]
> Played a few rounds of this, it looks great but it's overtuned a lot. Nearsighted is extremely difficult to play now, and you can barely see anything with a welding helmet/goggles on. Were these intentional? I'm assuming yes since they were your example pictures. Would you accept a PR that makes them a bit more similar to their existing values?

I never responded to this, but making the overlays more impactful was the intention.

**Pull request merged**
