### PR TITLE
Prevents GODMODE mobs from dying to organ removal

### PR DESCRIPTION
**Pull request by QualityVan**
This's why dummies were dying on the title screen, incidentally.

### CODE REVIEW

**Review by coiax — COMMENTED** [review]
GODMODE doesn't stop death, it only stops damage.

**Comment by optimumtact** [comment]
GODMODE should prevent most forms of death

**Comment by coiax** [comment]
@ChangelingRain please comment on the balance implications of casting the invulnerability spell in clockcult, and then removing someone's brain

**Comment by PKPenguin321** [comment]
>clockcult has GODMODE coded in as a player accessible feature

there's the real issue

**Comment by lzimann** [comment]
GODMODE should prevent most, if not all, forms of death.

**Pull request merged**
