### PR TITLE
turf meter

### PR DESCRIPTION
**Pull request by Dennok**
:cl:
add: Meters can be attached to the floor by screwdriver
/:cl:

### CODE REVIEW

**Comment by Cyberboss** [comment]
Why?

**Comment by ExcessiveUseOfCobblestone** [comment]
👍 to turf meters
👎 to bad changelog and no rationale

**Review by duncathan — APPROVED** [review]

**Comment by ExcessiveUseOfCobblestone** [comment]
@duncathan ENFORCE THE STANDARDS REEEEEEEEEEEEEE

**Comment by Dennok** [comment]
Incredible, i forgot about this.

**Pull request merged**
