### PR TITLE
Fire alarms now make a horrible racket when triggered.

### PR DESCRIPTION
**Pull request by KazeEspada**
http://vocaroo.com/i/s12Nsz3rItui

Licence on the sound is Attribution 3.0 so I am not sure where to put that.

### CODE REVIEW

**Comment by GunHog** [comment]
I love sirens! :+1:

**Comment by KazeEspada** [comment]
I will be honest, it sounded WAY better before I converted it to .ogg

**Comment by GunHog** [comment]
> I will be honest, it sounded WAY better before I converted it to .ogg

The excuse of every admin who plays a midi, ever!

**Comment by Incoming5643** [comment]
can we make it so ghosts don't hear fire alarms? Evey round now all I hear in the last 15 minutes is an unending cascade of beeps

**Comment by WJohn** [comment]
This sounds very... muffled? I dunno, I downloaded the sound file and it still sounds sort of muffled, like it's in another room.

Also holy shit no I don't want me ears to be ringing from that noise.

**Comment by KazeEspada** [comment]
You only hear it when near an active alarm.

**Comment by WJohn** [comment]
Yes, and it is very rare that there is ever just one isolated active alarm. Generally either an entire department or the whole station is on fire, or everything's fine.

**Comment by Dorsisdwarf** [comment]
How about you use the classic BbbrrrIIIIINGGGGG fire alarm rather than an industrial meltdown sound effect?

**Comment by KazeEspada** [comment]
Alarms are supposed to be annoying. Probably needs a test merge.

**Comment by KorPhaeron** [comment]
>Alarms are supposed to be annoying. 

Yeah in real life because they are urgent.

When I am floating about as a ghost (or walking in the main hall after the clown pulls an alarm) my life is not in danger and I dont need to be assailed by awful sounds.

**Comment by KazeEspada** [comment]
I could add a filter to play sound and make it ignore ghosts.

**Comment by MrPerson** [comment]
I would rather blow my head off than listen to this sound for even one second. No.

**Comment by optimumtact** [comment]
PREFERENCE

**Comment by xxalpha** [comment]
I don't like it and fire alarms can be turned on by anyone.

**Comment by MrPerson** [comment]
We don't want to let players upload midis because they can spam annoying shit but this is ok?

**Comment by KazeEspada** [comment]
I mean it makes sense in character, and was kinda of a trollish thing to do. Hey, at least I thought it was funny.

**Comment by Cheridan** [comment]
the sound should only play when the alarm first turns on

**Comment by Dorsisdwarf** [comment]
Kaze I'm going to say again this would be so much better with a bell fire alarm sound

**Pull request closed without merging**
