### PR TITLE
deletes tge cat species cuz it doesnt matter and is just a bad feature

### PR DESCRIPTION
**Pull request by Iamgoofball**
its not lihe this shit fucking matters anyadyad thetrs no fuckint point in kerponng this shit in the cofrbase it's just more dumb fucking gameollay clutter that wevcant do anythujg with and dkesnt make inr a resting stoties or comlelling barratives and fuck this shit lol i mean eeally think about it its just humans but wiru cat ears on their heads like how is this interesying at all itsv just cat earss like come on maje sonetyikny intersruig like flgimg bug people who cab like aee through walls bur only see in heat gidion like thernals and shit but cant aee anything that isnt hot make sime original slecies for ss13 thanks

### CODE REVIEW

**Comment by c420-o** [comment]
based

**Comment by Iamgoofball** [comment]
ill maje it compile whej.comcast fixes t htt e internet so i can pull agaun

**Comment by c420-o** [comment]
goof are you drunk

**Comment by Iamgoofball** [comment]
itsca free country and notning matters anyways lol

**Comment by Timberpoes** [comment]
Go home goof, you're drunk.

**Comment by Timberpoes** [comment]
The only joy I get in life is closing Goof's felinid PRs.

**Comment by MoonFalcon** [comment]
what if goof was right

**Pull request closed without merging**
