### PR TITLE
Adds some silly new meson failure excuses

### PR DESCRIPTION
**Pull request by ChangelingRain**
I may have gotten bored. Please take a message as to why your mesons no longer work.

### CODE REVIEW

**Comment by xxalpha** [comment]
rare neutrino collision disruption

**Comment by Kromgar** [comment]
The neutrinos have mutated

**Comment by lordpidey** [comment]
"a scratch on the lens"
"budget cuts"
"the magic smoke escaping"
"the on button being held down by lavaland's gravity"

**Comment by ChangelingRain** [comment]
the magic smoke can't escape, since mesons continue to work off lavaland!

**Comment by MSBeholder** [comment]
Mesons are in cosmic rays, an abundant type of energy in space but not on planet surfaces since atmosphere breaks them down.

https://en.wikipedia.org/wiki/Meson
https://en.wikipedia.org/wiki/Cosmic_ray

The perfect excuse if I were to keep an awful nerf like this on my code.

**Pull request merged**
