### PR TITLE
Removes slowdown from Reactive Teleport Armor and increases activation chance

### PR DESCRIPTION
**Pull request by GunHog**
The Reactive Teleport Armor's slowdown has been removed.
The armor's activation chance has been increased to 50%!
It also actually works now!
- The "armor" has zero defensive stats.
- ~~The chance to teleport is only <b>35%</b>.~~
- The whole point of the armor is to take a gamble, it is just as likely to make your situation worse than better!

I believe the armor is a fun item that deserves to be used more. For many RDs the only thing stopping them was the slowdown penalty to wear something that has no defensive values anyway! This should help to encourage more RD players to roll the dice to see if they escape _or get spaced!_ No longer should it be a nigh worthless traitor target item that an RD does not care about losing!

### CODE REVIEW

**Comment by hornygranny** [comment]
:+1:

**Comment by ACCount12** [comment]
:+1:
And buff chance to 50%. Or add a bit of armor stats. It has some bullet-stopping metal in it after all.

**Comment by GunHog** [comment]
I like the idea, ACCount, but I do not want to risk being denied if I go overboard.

**Comment by ACCount12** [comment]
no risk no fun

**Comment by GunHog** [comment]
Well, what values would you suggest? And would @hornygranny be okay with this?

**Comment by hornygranny** [comment]
just increase it to 50%

**Comment by GunHog** [comment]
So I was testing the armor, and discovered that it <b>did not actually work!</b>. I fixed that too.

**Comment by MrPerson** [comment]
Activation chance wasn't that important anyway since the vast majority of cases where you were getting attacked involve a lot of attacks which means a lot of chances to activate.

**Comment by Kromgar** [comment]
Finally. Now I can use the armor all the time. That slowdown was horrible

**Pull request merged**
