### PR TITLE
Departmental Officers now have access to most of their department

### PR DESCRIPTION
**Pull request by Son-of-Space**
## About The Pull Request

This pull request equalizes the access that departmental security is given for their department, giving departmental security officers access to all areas in the department which aren't head-specific. For example, the engineering security officer wouldn't have access to the tech storage room or the ce's office, but does have access to tcomms, engine equipment etc.

This is done so that all departmental security officers are equally enabled to respond to issues in their department and have the access that a basic member of the department would have. Currently, cargo officers are able to respond to any issue not in the vault or QMs office, but officers in science could only respond to issues in the science hallway, research room, or circuit room, and are unable to respond to issues in any other place in the department.

I believe that the reason for the above is that when new accesses have been added to departments, they neglected to add these areas for departmental security officers.

Upon further research, for things like virology or xenobio, it feels like keeping security officers out was intended, so I'll label this both a fix and a balance change.

## Why It's Good For The Game

Departmental security officers should be able to reliably respond to security issues in the department. While some areas like virology and xenobiology were deliberately separated from being accessible by security officers previously, I believe it is an antiquated design crutch that does not properly reflect the modern ways that antagonists work, and certainly doesn't reflect the standards that are currently set for officers.

Giving officers these accesses make departmental assignments something with genuine utility instead of something that gives you an armband and enables officers to feel/be felt like a part of their designated department.

These changes also make sure that departmental assignments are treated equally and have equal utility, making it easier to collectively change the feel of departmental security in the future.

## Changelog

:cl:
fix: departmental officers' access across departments has been standardized, and previously lost accesses were added back
balance: Departmental security officers have access to more areas in their departments, including xenobiology or virology
/:cl:

### CODE REVIEW

**Comment by Son-of-Space** [comment]
Since I anticipate that this PR will be controversial and after speaking with maptainers, I will be willing to walk back access additions like xenobiology or virology if the consensus from our team is that they should not be added so that we can add the fix portion of this.

**Comment by the-orange-cow** [comment]
I've always wondered why this wasn't the case from the beginning.

**Comment by Son-of-Space** [comment]
The biggest concern that I personally have with this is giving security officers the ability to do things like make robots or xenobio potions.

I think the best solution to that would be to move the research console, robotics consoles/fabs, slime consoles, etc. to require ACCESS_RESEARCH and put the research room / circuits room (the rooms that use it right now) to ACCESS_SCIENCE (the general access)

**Comment by zxaber** [comment]
I'd mostly be upset with officers coming into robotics and demanding items or pushing me away and just using the exofab themselves. It's a lot harder to flash and dumpster someone that starts with sunglasses and a disabler. (The captain and RD sometimes do this, but then they're both allowed to by rank.)

**Comment by Son-of-Space** [comment]
Ideally the solution to the above is to tell the RD, Captain, Warden, or HOS about that.

**Comment by zxaber** [comment]
Ideally, yes, but on most of our servers, the chain of command is corroded by apathy.

**Comment by Son-of-Space** [comment]
The HoP has never had control over things like warrants and I don't think we would want them to.

Officers yelling at the AI for access to a place they normally wouldn't have access to is much more interesting and non-annoying than them yelling at the AI for access they should logically already have.

**Comment by Son-of-Space** [comment]
> Ideally, yes, but on most of our servers, the chain of command is corroded by apathy.

If this is the case then why don't security officers abuse their access in the departments where they already have most of the departmental access?

I think the answer here is that the controls already in place work.

**Comment by optimumtact** [comment]
No, the depts they have access to don't have any valuable tools.

P/S the cargo officer does indeed abuse their access, especially during revs

**Comment by Son-of-Space** [comment]
I think that sec officers using the cargo console to forcibly order mindshields from a cargo department that may be compromised when they're required to do so as a reasonable effort to deconvert the crew in a conversion mode isn't really a great example.

I also think that hacking doors, despite having the new engineer skillchip, is still relatively easy. If an officer wants to abuse their position by using areas they aren't supposed to, that's already very easy for any one of them that decides to pick up a toolbelt. The only thing not having access does is discourage good officers (who in my mind wouldn't be carrying around a toolset 24/7) from reasonably doing their jobs.

Powergaming is going to be an issue regardless, but I don't believe it's an issue we should be trying to solve for at the expense of better gameplay and is inherently an admin issue. I think exploring the idea of officers having access to the departments they're supposed to service is more important and something we should try out. The primary barrier to this being successful is likely going to be a misconception that access equal permission. I think we'll see an increase in people abusing the extra access early on but that it will peter out with time, especially if players take care of those issues in character as would be expected.

**Review by san7890 — APPROVED** [review]
In comparison to normal ebb and flow of the game as it is right now (what with greytiding, etc.), there's typically only one security officer (and they are never _guaranteed_ to start with being assigned to a specific department, just _preferred_.)

In my mind, it could allow security officers to become more enmeshed in the department they follow. I've personally experienced the sort of dis-satisfaction with ending up in a silly "departmental guard" status and go around the station instead of sticking to the base where I was assigned, but it might not be unworthwhile to allow security officers who choose to remain in a department to create those connections or maybe learn something new, rather than try and nip at the heels of those they're meant to be guarding. Access does not equal permission, but "permission" is purely derived from whatever will happen in the IC context.

Unless you get the edge case "overflow" event, I don't think there's much of any problem allowing a singular security guard to lurk around the department. They're loyal to security and the station and will probably let other members of security into the department with their access, but that's also IC-derived. Some things that remain in my mind is the difficulty in getting a revolution/cult started, but the accesses are already geared towards public areas anyways (or at least areas with windows that you can see in). This is most definitely a balance change, but it's a balance change that I am interesting in seeing play out on production servers.

**Pull request merged**
