### PR TITLE
The GAGening: Families edition

### PR DESCRIPTION
**Pull request by Twaticus**
## About The Pull Request

Removes/converts most families gear in favor of new customizable clothing items using GAGs.
Some new items arent perfect replicas of all the old gear, but having recolorable items is a nice trade-off imo.
Removes some gear without a replacement. Some hats, armor, yuri set, just dont like it.
Remaining families gear moved to the costume vendor. Deckers, jackbros, henchmen.
dreamseeker_cYD15M9ekK
clothing in order:
fancy hat(previously saints hat)
infinity scarf(driscoll suit)
buttondown shirt w/shorts
buttondown shirt w/ pants
sweater(majima/dutch/irs jacket)
oversized coat(morningstar/phantom suit)
fancy coat(saints suit)
waistcoat
football gear(sybil/basil boys)

## Why It's Good For The Game

Clears some icon space while adding recolorable items for future use.

## Changelog

:cl:
imageadd: Converts some families gear into recolorable items in the clothesvendor. Includes a hat, scarf, 3 jackets, football gear, and buttondown shirt with shorts/pants. Adds a recolorable waistcoat.
/:cl:

### CODE REVIEW

**Comment by tralezab** [comment]
This entire pull request as narrated by Hanna Tireman herself (big support or TWATICUS's work)
https://vocaroo.com/1lDOspAUQtfj

**Comment by Wallemations** [comment]
Adding more reasons the clothesmate & costume vendor need tabs

This is a good way of reducing the amount of families icon bloat without outright removing most of it though, nice work

**Comment by Colovorat** [comment]
NOOOOOOOOOO NOT THE OSI ARMOR PLEASE FOR THE LOVE OF GOD KEEP IT

**Comment by Mothblocks** [comment]
Before fixing screenshot tests, can you please update from upstream? I just merged another PR that fixes the hair on the revs icon, so it would conflict with yours if you don't.

**Review by tralezab — APPROVED** [review]
spritetainer can merge if they approve of the sprite-side of this pr, code looks good

**Comment by Iamgoofball** [comment]
Why was I not contacted about this PR?

**Comment by Iamgoofball** [comment]
This is a massive downgrade in the quality of the sprites, and a massive removal of a lot of clothing items players actively used. Additionally, I was told that we would not be axing the families clothes during the removal process for families. I reached out to your spritetainer team and received the response of "guh" and "ill look into it" and was not contacted at any point.

This is art that I paid for and commissioned from professional artists who have been working with SS13's art style for years, and you are butchering it just so that people can recolor it neon pink, while also scrapping a ton of it for little reason other than "just dont like it".

Let's try to find a compromise here, because quite frankly this is content players are using and you've provided no reason for us to need to actually remove it.

**Review by Fikou — CHANGES_REQUESTED** [review]
you accidentally removed the ipc helmet

**Review by Fikou — APPROVED** [review]

**Comment by Iamgoofball** [comment]
I've reached out to the headcoders regarding this PR to request a DNM until a headcoder consensus can be reached on the subject, as you refused all attempts to reach a compromise or discuss the issue, and actively threatened to remove more content when questioned.

**Comment by Iamgoofball** [comment]
As mentioned on the discord, I've got a stat dump of the most vended clothesmate clothing. I posted the .csv used to generate this in the discord 
[message (3).txt](https://github.com/tgstation/tgstation/files/9226557/message.3.txt)
As you can see by the data, families clothing such as the Morningstar beret and jacket are some of the top vended items by players, with the vast majority of Families clothing items outperforming non-families clothing items that have been in the clothesmate for years. Families clothing is immensely popular with the players and I see no reason to change it in such a way or remove it when players clearly utilize it.
The .csv I used is available at https://file.house/l3yY.csv
explorer_EdSMggEfCE

**Comment by Iamgoofball** [comment]
The script used to generate the above data:
```
import csv
import json

if __name__ == "__main__":
    amt_of_clothing_machines = 0
    clothing_dict = {}
    with open('vending.csv') as csvfile:
        reader = csv.DictReader(csvfile)
        for row in reader:
            database = json.loads(row['json'])
            for vending_machine in database["data"]:
                if vending_machine == "/obj/machinery/vending/clothing":
                    for clothing in database["data"][vending_machine]:
                        if not clothing in clothing_dict:
                            clothing_dict[clothing] = 0
                        clothing_dict[clothing] += int(database["data"][vending_machine][clothing])
        sorted_results = sorted(clothing_dict.items(), key=lambda x: x[1], reverse=True)
        for x in sorted_results:
            print("Times Vended: " + str(x[1]) + ": " + x[0])
```

**Comment by Iamgoofball** [comment]
fikou is working on pulling more recent data from 09/27/21 to 7/30/2022 to get the full usage of the clothesmate since families went in

**Comment by Twaticus** [comment]
since there seems to be some confusion, a list of previous clothing items vs what i consider a suitable replacement. some already existing items, converted items, and new items i made to fill this specific niche. obviously some items will not have the same markings/flair, but the customization abilities far exceed the need for those specific static pixels.

CLOTHING/HATS
soviet ushanka - renamed and replaces ushanka
irs hat - preexisting hat
tmc hat - no real replacement
pg hat - recolorable beanie
decker hat - headphones
morningstar hat - recolorable beret
saints hat - recolorable, renamed to fancy hat
allies hat - preexisting helmet
yuri helmet - no real replacement
sybil/basil boys helmet - recolorable football helmet

CLOTHING/GLASSES
osi glasses - preexisting glasses
phantom glasses - no real replacement

CLOTHING/MASK
driscoll mask - recolorable bandana

UNDER/COSTUME
majima pants - recolorable pants
dutch uniform - recolorable shirt/pants, recolorable waistcoat
irs jumpsuit - recolorable shirt/pants
osi jumpsuit - recolorable shirt/pants, recolorable sweater
tmc jumpsuit - black undershirt, recolorable pants
pg jumpsuit - orange jumpsuit/prison jumpsuit
driscoll jumpsuit - recolorable shirt/pants, recolorable waistcoat
morningstar jumpsuit - recolorable shirt/pants
saints jumpsuit - recolorable shirt/pants
phantom jumpsuit - recolorable shirt/pants, recolorable waistcoat
allies uniform - blue undertank, recolorable jeans
soviet uniform - recolorable shirt/pants
yuri uniform - recolorable shirt/pants
sybil/basil boys uniform - recolors football suit

SUIT/COSTUME
majima jacket - recolorable sweater
dutch jacket - recolorable sweater
driscoll suit - recolorable scarf
irs suit - recolorable sweater
osi suit - pre-existing armor
tmc suit - recolorable sweater
pg suit - preexisting jacket
decker suit - no real replacement
morningstar suit - recolorable oversized coat
saints suit - recolorable, renamed to fancy coat
phantom suit - recolorable oversized coat
allies armor - preexisting armor
soviet suit - no real replacement/preexisting armor
yuri coat - no real replacement
sybil/basil boys armor - recolorable football armor

CLOTHING/FEET
majima shoes - recolorable sneakers
jackfrost boots - no real replacement
deckers shoes - renamed to glow shoes
morningstar shoes - recolorable sneakers
saints shoes - recolorable sneakers
phantom shoes - recolorable sneakers
sybil/basil boys shoes - recolorable sneakers

**Comment by MrStonedOne** [comment]
>obviously some items will not have the same markings/flair, but the customization abilities far exceed the need for those specific static pixels.

Unacceptable.

Do not dumb down the game's sprites to fit everything into generated/generic color blending.

**Comment by MrStonedOne** [comment]
All of the things without a direct 1:1 replacement in the """new""" system needs to stick around until the customination system can generate that exact outfit.

And you still need to communicate to the players **EXACTLY** how to replicate the old designs, meaning telling them what *exact* options/color they would need to pick, or designing a playlist system so they don't have to know this info.

**Comment by Twaticus** [comment]
> Do not dumb down the game's sprites to fit everything into generated/generic color blending.

its not dumbing down. its giving more player freedom

> All of the things without a direct 1:1 replacement in the """new""" system needs to stick around until the customination system can generate that exact outfit.

i dont care for keeping a ton of costumes that can be replicated by using less sprites. we dont need them as they currently stand and ive offered alternatives to let the player make whatever they want on the fly instead

> And you still need to communicate to the players **EXACTLY** how to replicate the old designs, meaning telling them what _exact_ options/color they would need to pick, or designing a playlist system so they don't have to know this info.

i will gladly implement pre-made versions once we have vendor tabs. the list is far too long in its current state.
that being said, i'd also feel way more comfortable adding certain flairs which the old costumes had if this were to happen. since then the 'basic' version can be in one tab, and the 'families' version(which use the basic version plus the flair) can be in a separate tab

**Comment by MrStonedOne** [comment]
>i will gladly implement pre-made versions once we have vendor tabs. the list is far too long in its current state.

You can not remove it until a magical future comes along.

If you can not 1:1 port it over to the new system, then you have to keep the old versions in the code.

@tgstation/commit-access add `DO NOT MERGE` and `BLAME MSO`

**Comment by VladinXXV** [comment]
> And you still need to communicate to the players **EXACTLY** how to replicate the old designs, meaning telling them what _exact_ options/color they would need to pick, or designing a playlist system so they don't have to know this info.

this has always been one of my biggest problems with GAGS. everything objectively looks worse because I am a player with no real understanding of color. once something is GAGSified even if i could theoretically make it look exactly how it used to, I'm never going to be able to figure it out.

**Comment by optimumtact** [comment]
@MrStonedOne what are you upset about? These are extraneous costumes left over from goof's unused gamemode.

This would be like blocking someone respriting the maid costume because it wasn't a one to one resprite?

**Comment by Iamgoofball** [comment]
>i will gladly implement pre-made versions once we have vendor tabs. the list is far too long in its current state.

then i will implement vendor tabs

**Comment by Iamgoofball** [comment]
meanwhile, i have pulled the stats from 9-27-2021 to yesterday at 23:59:59 for vending machine usage

the TMC hat that was removed with "no real replacement"?
literally the 6th most vended item in the clothesmate
```
(base) C:\Users\iamgo\Downloads>python ss13_clothing.py
Times Vended: 3147: /obj/item/clothing/head/beret/black
Times Vended: 2344: /obj/item/clothing/neck/stripedredscarf
Times Vended: 2300: /obj/item/clothing/shoes/laceup
Times Vended: 1983: /obj/item/clothing/neck/stripedbluescarf
Times Vended: 1767: /obj/item/clothing/suit/jacket
Times Vended: 1750: /obj/item/clothing/head/tmc
Times Vended: 1730: /obj/item/clothing/suit/hooded/wintercoat/custom
Times Vended: 1648: /obj/item/clothing/gloves/fingerless
Times Vended: 1504: /obj/item/clothing/shoes/cowboy/black
Times Vended: 1427: /obj/item/clothing/shoes/swagshoes
Times Vended: 1232: /obj/item/clothing/suit/soviet
Times Vended: 1225: /obj/item/clothing/head/morningstar
Times Vended: 1167: /obj/item/clothing/neck/stripedgreenscarf
Times Vended: 1096: /obj/item/clothing/neck/scarf/red
Times Vended: 1072: /obj/item/clothing/head/ushanka/soviet
Times Vended: 1037: /obj/item/clothing/suit/jacket/miljacket
Times Vended: 1032: /obj/item/clothing/suit/morningstar
Times Vended: 1019: /obj/item/clothing/shoes/winterboots
Times Vended: 923: /obj/item/clothing/glasses/osi
Times Vended: 921: /obj/item/clothing/under/costume/soviet_families
Times Vended: 918: /obj/item/clothing/accessory/pride
Times Vended: 871: /obj/item/clothing/shoes/morningstar
Times Vended: 855: /obj/item/clothing/under/costume/swagoutfit
Times Vended: 847: /obj/item/clothing/under/pants/jeans
Times Vended: 811: /obj/item/clothing/glasses/orange
Times Vended: 767: /obj/item/clothing/under/suit/black_really
Times Vended: 725: /obj/item/clothing/neck/necklace/dope
Times Vended: 703: /obj/item/clothing/neck/scarf/black
Times Vended: 694: /obj/item/clothing/glasses/red
Times Vended: 655: /obj/item/clothing/head/beanie/black
Times Vended: 653: /obj/item/clothing/under/suit/charcoal
Times Vended: 636: /obj/item/clothing/glasses/regular
Times Vended: 621: /obj/item/clothing/suit/mothcoat/winter
Times Vended: 611: /obj/item/clothing/neck/tie/red
Times Vended: 606: /obj/item/clothing/suit/phantom
Times Vended: 602: /obj/item/clothing/under/costume/morningstar
Times Vended: 599: /obj/item/clothing/shoes/sneakers/black
Times Vended: 599: /obj/item/clothing/suit/jacket/leather/overcoat
Times Vended: 570: /obj/item/clothing/under/syndicate/tacticool
Times Vended: 560: /obj/item/clothing/suit/pg
Times Vended: 543: /obj/item/clothing/accessory/waistcoat
Times Vended: 540: /obj/item/clothing/suit/jacket/leather
Times Vended: 494: /obj/item/clothing/suit/yuri
Times Vended: 493: /obj/item/clothing/suit/osi
Times Vended: 488: /obj/item/clothing/suit/dutch
Times Vended: 480: /obj/item/clothing/head/wig/natural
Times Vended: 480: /obj/item/clothing/under/pants/camo
Times Vended: 475: /obj/item/clothing/head/yuri
Times Vended: 472: /obj/item/clothing/head/fedora
Times Vended: 469: /obj/item/clothing/shoes/sandal
Times Vended: 418: /obj/item/clothing/shoes/cowboy/white
Times Vended: 415: /obj/item/clothing/shoes/cowboy
Times Vended: 414: /obj/item/clothing/shoes/yakuza
Times Vended: 402: /obj/item/clothing/under/pants/classicjeans
Times Vended: 401: /obj/item/clothing/under/costume/osi
Times Vended: 395: /obj/item/clothing/under/costume/yakuza
Times Vended: 389: /obj/item/clothing/suit/irs
Times Vended: 384: /obj/item/clothing/under/pants/blackjeans
Times Vended: 375: /obj/item/clothing/under/suit/sl
Times Vended: 367: /obj/item/clothing/head/cowboy_hat_white
Times Vended: 362: /obj/item/clothing/suit/poncho
Times Vended: 360: /obj/item/clothing/head/saints
Times Vended: 359: /obj/item/clothing/under/suit/white
Times Vended: 355: /obj/item/clothing/suit/ianshirt
Times Vended: 345: /obj/item/clothing/head/irs
Times Vended: 337: /obj/item/clothing/suit/allies
Times Vended: 333: /obj/item/clothing/head/sombrero
Times Vended: 328: /obj/item/clothing/neck/tie/black
Times Vended: 326: /obj/item/clothing/suit/driscoll
Times Vended: 322: /obj/item/clothing/under/pants/track
Times Vended: 320: /obj/item/clothing/neck/large_scarf
Times Vended: 312: /obj/item/clothing/head/cowboy_hat_grey
Times Vended: 308: /obj/item/clothing/under/costume/yuri
Times Vended: 308: /obj/item/clothing/suit/yakuza
Times Vended: 303: /obj/item/clothing/shoes/deckers
Times Vended: 300: /obj/item/clothing/under/costume/dutch
Times Vended: 297: /obj/item/clothing/under/costume/irs
Times Vended: 290: /obj/item/clothing/head/that
Times Vended: 289: /obj/item/clothing/under/pants/khaki
Times Vended: 283: /obj/item/clothing/suit/jacket/puffer
Times Vended: 281: /obj/item/clothing/under/costume/tmc
Times Vended: 281: /obj/item/clothing/under/suit/burgundy
Times Vended: 281: /obj/item/clothing/suit/saints
Times Vended: 274: /obj/item/clothing/head/bowler
Times Vended: 269: /obj/item/clothing/under/costume/driscoll
Times Vended: 267: /obj/item/storage/backpack/henchmen
Times Vended: 265: /obj/item/clothing/glasses/phantom
Times Vended: 263: /obj/item/clothing/suit/deckers
Times Vended: 252: /obj/item/clothing/under/dress/skirt
Times Vended: 246: /obj/item/clothing/glasses/regular/jamjar
Times Vended: 243: /obj/item/clothing/suit/toggle/suspenders/gray
Times Vended: 242: /obj/item/clothing/head/deckers
Times Vended: 241: /obj/item/clothing/suit/tmc
Times Vended: 237: /obj/item/clothing/under/costume/phantom
Times Vended: 235: /obj/item/clothing/neck/scarf
Times Vended: 235: /obj/item/storage/belt/fannypack
Times Vended: 235: /obj/item/clothing/neck/scarf/purple
Times Vended: 233: /obj/item/clothing/under/rank/centcom/officer/replica
Times Vended: 219: /obj/item/clothing/neck/tie
Times Vended: 202: /obj/item/clothing/under/costume/saints
Times Vended: 202: /obj/item/clothing/under/costume/deckers
Times Vended: 198: /obj/item/clothing/under/pants/black
Times Vended: 195: /obj/item/clothing/head/mothcap
Times Vended: 194: /obj/item/clothing/under/misc/overalls
Times Vended: 186: /obj/item/clothing/shoes/phantom
Times Vended: 184: /obj/item/clothing/head/beanie/rasta
Times Vended: 180: /obj/item/clothing/neck/tie/horrible
Times Vended: 172: /obj/item/clothing/head/allies
Times Vended: 172: /obj/item/clothing/suit/jacket/letterman_red
Times Vended: 168: /obj/item/instrument/piano_synth/headphones/spacepods
Times Vended: 168: /obj/item/clothing/under/dress/redeveninggown
Times Vended: 164: /obj/item/clothing/head/beanie
Times Vended: 163: /obj/item/clothing/head/beanie/purple
Times Vended: 160: /obj/item/clothing/under/suit/navy
Times Vended: 159: /obj/item/clothing/neck/scarf/pink
Times Vended: 159: /obj/item/clothing/neck/scarf/zebra
Times Vended: 157: /obj/item/clothing/under/dress/striped
Times Vended: 157: /obj/item/clothing/mask/gas/driscoll
Times Vended: 156: /obj/item/clothing/head/pg
Times Vended: 154: /obj/item/clothing/shoes/saints
Times Vended: 153: /obj/item/clothing/glasses/monocle
Times Vended: 153: /obj/item/clothing/suit/jacket/puffer/vest
Times Vended: 152: /obj/item/clothing/under/costume/pg
Times Vended: 149: /obj/item/clothing/under/pants/tan
Times Vended: 148: /obj/item/clothing/head/basil_boys
Times Vended: 148: /obj/item/clothing/shoes/basil_boys
Times Vended: 146: /obj/item/clothing/mask/balaclava
Times Vended: 146: /obj/item/clothing/head/beanie/red
Times Vended: 142: /obj/item/clothing/neck/scarf/darkblue
Times Vended: 138: /obj/item/clothing/suit/jacket/letterman_nanotrasen
Times Vended: 135: /obj/item/clothing/neck/tie/blue
Times Vended: 134: /obj/item/clothing/shoes/sybil_slickers
Times Vended: 132: /obj/item/clothing/neck/scarf/green
Times Vended: 128: /obj/item/clothing/under/dress/sailor
Times Vended: 125: /obj/item/clothing/neck/scarf/cyan
Times Vended: 124: /obj/item/clothing/suit/sybil_slickers
Times Vended: 120: /obj/item/clothing/under/dress/skirt/purple
Times Vended: 120: /obj/item/clothing/under/syndicate/tacticool/skirt
Times Vended: 119: /obj/item/clothing/under/dress/skirt/blue
Times Vended: 119: /obj/item/clothing/under/suit/henchmen
Times Vended: 114: /obj/item/clothing/neck/scarf/yellow
Times Vended: 114: /obj/item/clothing/head/sybil_slickers
Times Vended: 111: /obj/item/clothing/under/costume/allies
Times Vended: 110: /obj/item/clothing/under/dress/blacktango
Times Vended: 110: /obj/item/clothing/neck/scarf/orange
Times Vended: 110: /obj/item/clothing/under/misc/mailman
Times Vended: 108: /obj/item/clothing/head/beanie/darkblue
Times Vended: 106: /obj/item/clothing/suit/jacket/letterman
Times Vended: 104: /obj/item/clothing/head/beanie/green
Times Vended: 102: /obj/item/clothing/suit/basil_boys
Times Vended: 100: /obj/item/clothing/head/mailman
Times Vended: 96: /obj/item/clothing/under/pants/red
Times Vended: 94: /obj/item/clothing/under/costume/basil_boys
Times Vended: 93: /obj/item/clothing/under/costume/sybil_slickers
Times Vended: 92: /obj/item/clothing/suit/toggle/suspenders/blue
Times Vended: 91: /obj/item/clothing/under/rank/centcom/officer_skirt/replica
Times Vended: 90: /obj/item/clothing/suit/mothcoat
Times Vended: 86: /obj/item/clothing/head/kippah
Times Vended: 84: /obj/item/clothing/under/suit/checkered
Times Vended: 83: /obj/item/clothing/under/pants/mustangjeans
Times Vended: 81: /obj/item/clothing/under/pants/white
Times Vended: 79: /obj/item/clothing/head/beanie/yellow
Times Vended: 79: /obj/item/clothing/under/dress/skirt/red
Times Vended: 75: /obj/item/clothing/under/costume/kilt
Times Vended: 73: /obj/item/clothing/mask/bandana
Times Vended: 72: /obj/item/storage/belt/fannypack/red
Times Vended: 70: /obj/item/clothing/head/beanie/orange
Times Vended: 69: /obj/item/clothing/under/dress/skirt/plaid
Times Vended: 68: /obj/item/clothing/head/beanie/cyan
Times Vended: 68: /obj/item/clothing/under/suit/white/skirt
Times Vended: 67: /obj/item/clothing/head/jackbros
Times Vended: 66: /obj/item/clothing/under/costume/jackbros
Times Vended: 64: /obj/item/clothing/mask/bandana/color/striped
Times Vended: 63: /obj/item/clothing/head/beanie/striped
Times Vended: 61: /obj/item/clothing/head/beanie/christmas
Times Vended: 60: /obj/item/clothing/under/dress/skirt/plaid/blue
Times Vended: 56: /obj/item/clothing/suit/apron/purple_bartender
Times Vended: 56: /obj/item/clothing/suit/jacket/letterman_syndie
Times Vended: 54: /obj/item/clothing/under/rank/civilian/head_of_personnel/suit/skirt
Times Vended: 54: /obj/item/clothing/head/taqiyahred
Times Vended: 53: /obj/item/clothing/head/beanie/stripedred
Times Vended: 49: /obj/item/clothing/under/dress/skirt/plaid/purple
Times Vended: 49: /obj/item/clothing/neck/scarf/christmas
Times Vended: 46: /obj/item/clothing/under/costume/jabroni
Times Vended: 45: /obj/item/clothing/mask/bandana/skull
Times Vended: 44: /obj/item/clothing/under/dress/sundress
Times Vended: 42: /obj/item/storage/belt/fannypack/blue
Times Vended: 41: /obj/item/clothing/mask/bandana/color
Times Vended: 39: /obj/item/clothing/mask/bandana/striped
Times Vended: 39: /obj/item/clothing/suit/costume/morningstar
Times Vended: 34: /obj/item/clothing/head/ushanka
Times Vended: 34: /obj/item/clothing/under/rank/civilian/bartender/purple
Times Vended: 33: /obj/item/clothing/suit/costume/soviet
Times Vended: 31: /obj/item/clothing/shoes/jackbros
Times Vended: 27: /obj/item/storage/belt/fannypack/black
Times Vended: 27: /obj/item/clothing/head/beanie/stripedgreen
Times Vended: 24: /obj/item/clothing/mask/bandana/color/skull
Times Vended: 22: /obj/item/clothing/head/beanie/stripedblue
Times Vended: 21: /obj/item/clothing/under/dress/skirt/plaid/green
Times Vended: 21: /obj/item/clothing/under/dress/skirt/turtleskirt
Times Vended: 20: /obj/item/clothing/under/costume/geisha
Times Vended: 18: /obj/item/clothing/suit/costume/saints
Times Vended: 17: /obj/item/clothing/under/rank/captain/suit/skirt
Times Vended: 17: /obj/item/clothing/suit/costume/phantom
Times Vended: 17: /obj/item/clothing/suit/costume/driscoll
Times Vended: 14: /obj/item/clothing/suit/costume/osi
Times Vended: 14: /obj/item/clothing/under/pants/slacks
Times Vended: 13: /obj/item/clothing/under/costume/soviet
Times Vended: 13: /obj/item/clothing/under/shorts
Times Vended: 11: /obj/item/clothing/suit/vapeshirt
Times Vended: 11: /obj/item/clothing/suit/costume/yakuza
Times Vended: 11: /obj/item/clothing/suit/costume/tmc
Times Vended: 10: /obj/item/clothing/suit/toggle/suspenders
Times Vended: 9: /obj/item/clothing/suit/costume/deckers
Times Vended: 9: /obj/item/clothing/suit/costume/poncho
Times Vended: 8: /obj/item/clothing/suit/costume/allies
Times Vended: 8: /obj/item/clothing/under/jeanshorts
Times Vended: 6: /obj/item/clothing/suit/costume/pg
Times Vended: 6: /obj/item/clothing/suit/costume/dutch
Times Vended: 5: /obj/item/clothing/suit/costume/irs
Times Vended: 4: /obj/item/clothing/head/rasta
Times Vended: 3: /obj/item/clothing/under/dress/tango
Times Vended: 3: /obj/item/clothing/suit/costume/ianshirt
Times Vended: 3: /obj/item/clothing/suit/costume/yuri
Times Vended: 2: /obj/item/clothing/suit/costume/sybil_slickers
Times Vended: 1: /obj/item/clothing/suit/costume/basil_boys
```
query used:
```SELECT * FROM `feedback` WHERE `key_name` = 'vending_machine_usage' AND datetime BETWEEN '2021-09-27 00:00:00' AND '2022-07-29 23:59:59'```

.csv available at https://file.house/wd77.csv

**Comment by MrStonedOne** [comment]
> @MrStonedOne what are you upset about? These are extraneous costumes left over from goof's unused gamemode.
> 
> This would be like blocking someone respriting the maid costume because it wasn't a one to one resprite?
> 
> personally my preference was to remove all of them as extraneous with the original families removal PR but mothblocks decided not to do that.
> 
> not sure exactly why you think they have any intrinsic value that's worth you getting involved here.


Can't mask a removal as a refactoring into a system.

Gotta label the pr with the removal front and center, and at that point, the removal isn't atomic, and it has to go into its own pr.

You know this

I know this

Twat knows this.

I don't understand why you are surprised.

**Comment by optimumtact** [comment]
I don't understand because it's a costume sprite in a vending machine that most players won't interact with

**Comment by Twaticus** [comment]
> If the removal specifically is what bothers you then fine, add back the missing sprites and make a new PR removing them or whatever.

can do

> Can't mask a removal of some of the most requested outfits in the autodrobe as a refactoring into a system. I won't let you.
> Gotta label the pr with the removal front and center, and at that point, the removal isn't atomic, and it has to go into its own pr.

the very first word in the pr is 'Removes' so dont pretend like being 'masked'. if the label is the issue then thats fair, 'removal' tag was not originally there and thats my fault for not thinking to add it.
but i would also like to know why exactly you think removal would not be allowed in this type of pr? its entirely based around a specific section of clothing, not random bits here or there. one section. everything that was added was to compensate for things that were being removed.

**Comment by Twaticus** [comment]
re-added select families attire from the list above. including all items labelled as 'no real replacement', some items labelled as 'preexisting' which wasnt accurate upon a revisited viewing. notify me if something glaring is missing

CLOTHING/HATS
irs
tmc
decker
yuri
allies

CLOTHING/GLASSES
phantom
osi

CLOTHING/MASK
driscoll

UNDER/COSTUME
yuri
dutch
osi
tmc

SUIT/COSTUME
decker
soviet
yuri
tmc
pg

CLOTHING/FEET
jackfrost
saints

**Comment by MrStonedOne** [comment]
I mean what my **actual** issues are isn't that much of a secret.

I hate content removal and I hate content being jammed into inflexible systems and frameworks and I hate content removal disguised as content being jammed into inflexible systems.

Its just that I can really only *reasonably* put my foot down about the last item in that list so i really don't understand why its such a surprise that when people give me the opening to stop content removal I take it.

**Comment by Fikou** [comment]
mso is satisfied

**Comment by LemonInTheDark** [comment]
judge

**Comment by optimumtact** [comment]
> I mean what my **actual** issues are isn't that much of a secret.
> 
> I hate content removal and I hate content being jammed into inflexible systems and frameworks and I hate content removal disguised as content being jammed into inflexible systems.
> 
> Its just that I can really only _reasonably_ put my foot down about the last item in that list so i really don't understand why its such a surprise that when people give me the opening to stop content removal I take it.

markiplier-punch

**Comment by Colovorat** [comment]
> notify me if something glaring is missing

OSI armor? or am i retarded

**Comment by SethLafuente** [comment]
Why in the fuck did you remove morning star beret beret boots and coat non of the options you presented are similar while the beret cannot be recolored like morning star this PR did nothing useful other than remove customizability of characters and this had no reason to be done if you think morning star beret is just a reskinned beret maybe you don't care enough about clothing fashion to even make a removal PR of it

**Comment by optimumtact** [comment]
You have received a 1 day timeout for posting on an old PR.

Take it up with them in discord or on the forums.

**Pull request merged**
