### PR TITLE
Custom emotes no longer replace the pronouns

### LINKED ISSUE #27613: gender-neutral to gendered term conversion in emote code is too agressive
for example, i was trying to give my character some flavor when he was in tool storage picking up a toolbox and gloves by emoting
"george melons hums the 'Mission Impossible' theme to himself"
which came out as
"george melons hums the 'Mission Impossible' hime to himself"
by what i assume is the
them -> him code,
therefore
them+e -> him+e

### PR DESCRIPTION
**Pull request by lzimann**
Fixes #27613

Surprised it took this long to have this issue, guess no one uses the custom that much.

### CODE REVIEW

**Comment by SgtxRootbeer** [comment]
im not quite fond with this fix... but i guess there isnt much of an easier way to handle it.

**Comment by lzimann** [comment]
It doesn't make sense having pronoum replacement on customs.

**Comment by RemieRichards** [comment]
it's pronoun @lzimann, you've typo'd it in the proc name too.

**Comment by lzimann** [comment]
stupid english

**Pull request merged**
