### PR TITLE
Adds cult variants for simple mobs + Shuttle Loan event

### PR DESCRIPTION
**Pull request by MMMiracles**
I found it odd that there was syndicate and russian variants for simple mobs but not cultists, so I fixed that.

Also adds a cult variant of the shuttle loan events for ruskies and syndicats.

Theres a regular and spacebound version of the cultist, as well as simple mob variants of constructs. Probably only really useful for !!FUN!!mins or mappers who want to make spooky cult bases without directly needing players to actually control said cult mobs.

### CODE REVIEW

**Comment by Dorsisdwarf** [comment]
:+1:

**Comment by RemieRichards** [comment]
Simple mob constructs makes me want to cry.
because they're already simple mobs!

**Comment by MMMiracles** [comment]
Simple simple-mobs.

**Comment by Dorsisdwarf** [comment]
The Religious Outreach event will only fire when called by an admin, is that intended? (It's not in the proc which chooses what flavor of fuck you central are sending the station)

**Comment by RemieRichards** [comment]
@MMMiracles 
1. remove your simple animal constructs
2. Repath the current actual construct simple animals to have /hostile in their path (/simple_animal/hostile)

Done, this means when they have a client (player) nothing changes, but without a client they'll act like normal hostile animals (they have the cult faction so it won't be an issue with them eating teammates when they disconnect)

**Comment by Anonus** [comment]
iirc, actual custists don't have the cult faction.

**Comment by RemieRichards** [comment]
Then they should have it added during antag+conversion.

**Comment by MMMiracles** [comment]
i honestly don't know why i didn't just change the paths to begin with now i feel silly.

**Comment by RemieRichards** [comment]
@MMMiracles you didn't add the cultist faction to roundstart or converted cultists!
```M.factions += "Cultist"``` does the trick.

**Comment by Razharas** [comment]
@MMMiracles plz respond

**Comment by Razharas** [comment]
Looks like its dead

**Pull request closed without merging**
