### PR TITLE
Removes the mini meteor from the autolathe and cargo crate drop pool

### PR DESCRIPTION
**Pull request by TheVekter**
## About The Pull Request

Yeeeaaaahhhh, turns out that when DoomBringer made this change he didn't know that an emagged mini meteor turns into a pretty robust little grenade. These can't really exist in large quantities or they become pretty fucking dangerous.

## Why It's Good For The Game

Giving traitors unlimited grenades for the cost of 500 plastic and 3 TC is a bad idea
## Changelog
:cl:
del: Removed the ability to print mini meteor toys from the autolathe and obtain them from cargo crates.
/:cl:

### CODE REVIEW

**Comment by BeeSting12** [comment]
They should be left in the crates since that's a random chance of getting them plus it costs money. You wouldn't be able to spam them like you could with autolathes.

**Comment by TheVekter** [comment]
Eh, good point.

**Comment by ATH1909** [comment]
You could just remove the emag effect (a plastic toy with no electronics having an emag effect is even lampshaded by the mini-meteor itself) instead, y'know.

**Comment by ATH1909** [comment]
Also:
>  turns out that when DoomBringer made this change he didn't know that an emagged mini meteor turns into a pretty robust little grenade.

image

**Comment by MrDoomBringer** [comment]
lmao imagine reading github comments

**Comment by ATH1909** [comment]
> lmao imagine reading github comments

That's why I included your response to my comment there, which proves that you did indeed read the comments of that PR (and even responded to one (mine) that was made after the comment that pointed out that mini-meteors have an emag effect).

MrDoomBringer exposed

**Comment by ATH1909** [comment]
For what it's worth, emagged mini-meteors cause only a single tile light explosion when they hit someone, which deals <=30 brute damage to them (no burn), deafens them, and knocks them down (no unconsciousness or hard stun) for a while. You can't print more mini-meteors in bulks of 5 or 10 (you HAVE to print them one at a time), they're small items, not tiny ones (so only 15 of them can fit in a trash bag (and only 30 of them can fit in a bluespace trash bag), and https://github.com/tgstation/tgstation/pull/50940 is gonna make mini-meteor murderbones even jankier to perform.

On the other hand, I managed to almost (one member survived) wipe an entire ERT (after Korol murderboned almost everyone else on the station) with a discounted support holoparasite and a bluespace trash bag full of emagged mini-meteors (that I got the plastic for from a (flawed) plumbing setup), and Grod's Law ("You cannot and should not balance bad mechanics by making them annoying to use.") is a thing.

**Comment by MrDoomBringer** [comment]
@ATH1909 sorry i only read every other comment 

also no i did see that comment but didn't bother to look into what the effect actually was, figured it was something benign and not turning it into a fucking grenade lmao
my bad

**Comment by TheVekter** [comment]
> 
> 
> For what it's worth, emagged mini-meteors cause only a single tile light explosion when they hit someone, which deals <=30 brute damage to them (no burn), deafens them, and knocks them down (no unconsciousness or hard stun) for a while. You can't print more mini-meteors in bulks of 5 or 10 (you HAVE to print them one at a time), they're small items, not tiny ones (so only 15 of them can fit in a trash bag (and only 30 of them can fit in a bluespace trash bag), and #50940 is gonna make mini-meteor murderbones even jankier to perform.
> 
> On the other hand, I managed to almost (one member survived) wipe an entire ERT (after Korol murderboned almost everyone else on the station) with a discounted support holoparasite and a bluespace trash bag full of emagged mini-meteors (that I got the plastic for from a (flawed) plumbing setup), and Grod's Law ("You cannot and should not balance bad mechanics by making them annoying to use.") is a thing.

See, you would think that based on the code, but I tossed one at a human and it blew its fucking leg off and sent it into soft crit because for _reasons_ it causes more than one explosion.

So I'm looking into that as well.

**Comment by MrDoomBringer** [comment]
@TheVekter The reason is it causes an explosion whenever it bumps into something, but not one big enough to destroy itself, so the explosion causes it to get thrown into something else, sometimes the same object, making another explosion, until it finally breaks. (I think)

**Comment by Pugie** [comment]
_Laughd in infinite emagged arcade maxcaps_

**Pull request merged**
