### PR TITLE
Sutures and Mesh can no longer be used on yourself to combat lone-wolf powergaming by refusing medical treatment

### PR DESCRIPTION
**Pull request by Iamgoofball**
## About The Pull Request

Sutures and Mesh can no longer be used on yourself to combat lone-wolf powergaming by refusing medical treatment

## Why It's Good For The Game

Real fucking tired of people deciding how they're going to be treated when they come to medbay instead of doctors getting to choose, if you want to bypass the doctors and burn down medbay supplies now you need a buddy at minimum

just had a round of medbay on terry where
1. security barged in and took medical supplies to treat themselves with and refused to let doctors treat them
2. greytiders barged in and took medical supplies to treat themselves with and refused to let doctors treat them
3. paramedics barged into surgery and stole patients doctors were actively working on because they felt the doctors weren't "fast enough"

admins refuse to administrate terry to not make it 24/7 TTT TDM so if we want people to play the video game the way we intend(medical doctors treat people for injuries), then we need to force these changes through the code

i literally watched the admins recall the shuttle three times because it was a toe stub early call in one round only for the crew to call it a fourth time, this time the crew decided they would tell the admins to commit suicide via command announcement, and admins just gave up and sent a deathsquad

we literally cannot rely on admins to do any form of enforcement on the way ss13 is intended to be played from the codebase's perspective if we do not physically force it to be so

i am so fucking tired of every single job outside of security requiring you to be a professional at SS13 combat if you want to be able to do your job without people forcing their way into your department and doing the job for themselves cutting you out

## Changelog
:cl:
balance: Sutures and Mesh can no longer be used on yourself to combat lone-wolf powergaming by refusing medical treatment
/:cl:

### CODE REVIEW

**Comment by Iamgoofball** [comment]
lmao @ one of the admins who kept ignoring all ahelps that round about endless greytiding downvoting this PR

**Comment by ZAMODA** [comment]
**GOOF YOU WERE DOING SO GOOD, WHY MAKE IT CRASH AND BURN SO HARD?!**

**Comment by arnociiroc** [comment]
antag buff 👍

**Comment by Naloacisamazing** [comment]
Lmao, Lol even

**Comment by Jackraxxus** [comment]
Put me in the screencap

**Comment by Iamgoofball** [comment]
@IndieanaJones maybe any of the 50 billion other ways to heal that isn't sutures or mesh

**Comment by ZAMODA** [comment]
> @IndieanaJones maybe any of the 50 billion other ways to heal that isn't sutures or mesh

what other ways? chems? things that you have to risk breaking into medical or asking someone to get for you? traitor heals? things that you have to spend TC on, which not all antags have access too. What else is there?

**Comment by ZAMODA** [comment]
also, why not give it a **chance** to fail instead of outright refusing? that way solo antags can still have them be an option while keeping medical/buddy system more viable?

**Comment by ExcessiveUseOfCobblestone** [comment]
didnt there used to be a heal penalty for these when self-tending or did we just nerf the healing of them in general?

**Comment by SkeletalElite** [comment]
> didnt there used to be a heal penalty for these when self-tending or did we just nerf the healing of them in general?

it still exists, its slower to use on self than others

**Pull request closed without merging**
