### PR TITLE
Fixes admin healing not giving blood back.

### PR DESCRIPTION
**Pull request by Menshin**
In doubt, use the prefix notation.

Solves one half of #7638 .

### CODE REVIEW

**Comment by paprka** [comment]
Damn, thanks. It should fix changelings as well.

**Comment by Deantwo** [comment]
:+1:
:100: points to @Menshin!

**Comment by WJohn** [comment]
What about fleshmend or whatever their non-stasis heal is, does that restore blood currently?

**Comment by Menshin** [comment]
It calls _restore_blood()_, so it should.

**Pull request merged**
