### PR TITLE
Goats eat glowshrooms

### PR DESCRIPTION
**Pull request by coiax**
:cl: coiax
add: Goats on the station have developed a taste for glowshrooms, and
will eat them if they encounter any.
/:cl:

Glowshrooms are hard to get rid of, so let's add some additional plant
destroying abilities to the chef's goat. Hope he didn't butcher it into
meat!

### CODE REVIEW

**Comment by octareenroon91** [comment]
Please make Pete glow.

**Comment by SgtxRootbeer** [comment]
Does this work on shadow shrooms too?

**Comment by coiax** [comment]
Yes.

**Comment by Militaires** [comment]
Make pete glow when he eats them

**Review by Cyberboss — APPROVED** [review]

**Comment by coiax** [comment]
@lzimann this PR is causing #26954 to happen on my VM. Fucking rip me.

**Comment by Jalleo** [comment]
@coiax Update the code then it may work afterwards (aka a cleanbot proc should be fixing it if you have it)

**Comment by optimumtact** [comment]
you did add a proc, I wonder if we're hitting a proc limit

**Comment by coiax** [comment]
@Jalleo I did rebase from the latest master, it did not help.

**Comment by Cyberboss** [comment]
Based on the things that have caused it, I doubt it's the proc limit.

**Comment by Fox-McCloud** [comment]
Should probably also make the Scythe work on glowshrooms too.

**Pull request merged**
