### PR TITLE
All departments get their own flavor of station bounced radio

### PR DESCRIPTION
**Pull request by DAKKA-WAAAGH**
## About The Pull Request
imfuckingtrippingballsrn

As title says, every department gets their own station bounced radio. They're locked to their department's frequency and that's about it. You can print them from protolathes too! Incredible.

Here's what they look like in-game, alongside what happens in the chatbox:

image
image

## Why It's Good For The Game
Another way for players to communicate. Is it convenient? Not entirely. I'm sure people who are smarter than me can come up with more uses than I can though.

The command one is shiny and gold and command mains are always desperate for that sweet, sweet gold!

## Changelog
:cl:
add: Added station bounced radio to each department
add: Added each radio to respective protolathe
imageadd: Added new sprites for each radio
imagedel: Removed old sprite
/:cl:

### CODE REVIEW

**Comment by OneAsianTortoise** [comment]
Damn bro -16

**Comment by Paxilmaniac** [comment]
> (dogs can wear the radios on their backs)
> 
> image

dog fashion = false or whatever the var is to stop dogs wearing shit

**Comment by Time-Green** [comment]
This is really cool but you gotta get your GBP up first. Either ping someone when you made some fixes or make a new PR when your GBP isn't negative anymore

**Comment by Sealed101** [comment]
> dog fashion = false or whatever the var is to stop dogs wearing shit

WEAK

**Comment by Ekaterina-von-Russland** [comment]
A really cool PR closed over this cryptic "GBP", sad. What even is GBP?

**Comment by DAKKA-WAAAGH** [comment]
> A cool PR closed over this mysterious "GBP", sad. What even is GBP?

Evil. A system made for coders -- not mappers (me) or spriters

**Pull request closed without merging**
