### PR TITLE
Adds holocarp purchase for 10TC

### PR DESCRIPTION
**Pull request by coiax**
:cl: coiax
rscadd: The Syndicate have been supplied with holocarp fishsticks from the cult of Carp'sie. Do not trust any transparent fish that you sea. Ahem, we mean see.
/:cl:

Holocarp are like holoparasites, with some differences.
- You can have more than one in a single person
- You are unable to select the type, it is determined entirely randomly
- They look like holocarp, and have fish names and colours

This PR is complete, technically, but mostly exists for a test merge to evaluate the balance and cost of a 10TC fishstick.

### CODE REVIEW

**Comment by Cheridan** [comment]
why

**Comment by KazeEspada** [comment]
2 random holos vs 1 specifically tailored holo

This is like bundles all over again, but better.

**Comment by coiax** [comment]
If two holocarps for 20TC proves to be too good, we'll either remove having more than one carp and lower the price, or put it at 11TC? But only 1 TC cheaper for a random type seems like a poor deal.

**Comment by KazeEspada** [comment]
It will be better sometimes and sometimes you may get two holos who help only a little.

**Comment by Cheridan** [comment]
we have stands already, we don't need to add "Stands but they're fish so random" when we already have a bloated traitor equipment list.

ffs i thought this was april fools content, why is it in master

**Comment by Zilenan91** [comment]
Yeah no :-1: 

Stands are already bad, all this is going to do is let people buy two of them every round and go on turbomurder sprees.

**Comment by coiax** [comment]
Because they're differently themed guardians. What's not to like? Also, never actually got merged into April Fools because I based it on master of then, and not the april fools branch

**Comment by KazeEspada** [comment]
They are random tho. Which means you don't always get the stand you are aiming for. Although, two stands of any type is pretty great(as long as both aren't getting shot).

**Comment by Zilenan91** [comment]
Yeah they are random but over 50% of stands are better than eswords in terms of deadliness. Literally the only one that would be inefficient at murdering are explosive stands.

**Comment by drynwyn** [comment]
In fairness, both stands would draw from the same health pool, which is a non-trivial disadvantage- having two isn't twice as good as having one.

**Comment by AdamElTablawy** [comment]
why though

**Comment by KazeEspada** [comment]
Still a better buy than a bundle.

**Comment by Bawhoppen** [comment]
:-1:x:100: 
hey look more unnecessary things for traitors to buy

**Comment by PKPenguin321** [comment]
bawhoppen you have a problem. i believe it may be a phobia of fun. seek therapy

**Comment by KazeEspada** [comment]
@Bawhoppen You mean like.... the bundles?

**Comment by optimumtact** [comment]
It's no more or less fun that the stands, so it's just bloat at that point

I might be tempted if they did something unique like fired fish stick magic at people or something

**Comment by KazeEspada** [comment]
I kinda like the idea of two random stands for 20 TC. I think its a bit more powerful murderbone wise than one stand, but at least they dont have the armory cause no emag.

**Comment by Zilenan91** [comment]
They can easily get the armory by using the holos to break walls, or kill a sec officer what with how lethal these things are.

**Comment by Core0verload** [comment]
Doesn't fit my design vision.

**Comment by coiax** [comment]
@Archie700 because they have the same minimum player count as holoparasites. Unless you think it should be higher?

**Comment by Archie700** [comment]
@coiax One holoparasite on lowpop is bad enough since it's easier for the traitor to kill people one by one with low security and fewer people in general.

Two holocarp is even worse, since now you have TWO different stands that can take on more people. Yes, you have a bigger target, but now you can slaughter the station even faster if you play your cards right.

**Comment by coiax** [comment]
@Archie700 I will boost the minimum population required to 40.

**Comment by KorPhaeron** [comment]
Redundant and people already take stands way too much, maybe hide a way to get this on lavaland or in space ruins

**Comment by Core0verload** [comment]
Carp-Sie's altar in space?

**Pull request closed without merging**
