### PR TITLE
Mech Speech Bubbles, POI list for Observe

### PR DESCRIPTION
**Pull request by AnturK**
- Speech Bubbles for mechs
- Global POI List - mechs,nuke disk,singularities. Orbit now uses that. Jump-To-Mob left as is.

### CODE REVIEW

**Comment by WJohn** [comment]
Finally :+1:

**Comment by Shihrt** [comment]
YESSS :+1: :+1: :+1:

**Comment by PKPenguin321** [comment]
Now all we need is so that if you're a gangster/rev/cultist, other gangsters/revs/cultists can still see your HuD icon when you're in a mech

**Comment by AnturK** [comment]
I guess i can add HUD icons, one moment.

**Comment by AnturK** [comment]
Well here it is but i'm not sure i like it, It's kinda busy with mechs filling almost whole tile.

**Comment by PKPenguin321** [comment]
holy fuck you did it
:+1: x :100:

**Comment by KorPhaeron** [comment]
Nice

**Comment by Bawhoppen** [comment]
Showing the Icon doesn't make sense though, how would you know its THAT person inside it?

**Comment by PKPenguin321** [comment]
who cares if it makes sense tbh

**Comment by Bawhoppen** [comment]
You left me with countless comedic ways to answer that, but I won't.

The reason you see an icon after someone flashes you, is they brainwash you so you know they're a headrev, and is simply just as a gameplay mechanic to help keep track of it.

**Comment by Dorsisdwarf** [comment]
:-1: Mechjacking has been a way to infiltrate teamantag bases since time immemorial

**Comment by CPTANT** [comment]
:-1:  On the hud

A major aspect of mechs is that you are not supposed to know who is inside.

**Comment by Supermichael777** [comment]
you could always wear a "liberated" id. and mech pilots in team-antag bases who don't speak or showt themselves are gong to get dunked the moment they start doing anything besides shoot at security and even then its a toss up.

**Comment by Shadowlight213** [comment]
:-1: on the mech huds.

**Comment by duncathan** [comment]
@AnturK kill the HUD; I wanna merge this but the HUD is too controversial for my tastes
Do it in another PR if you want

**Comment by AnturK** [comment]
Here,If anyone wants it it's in the history.

**Pull request merged**
