### PR TITLE
Nuke Ops Rework

### PR DESCRIPTION
**Pull request by actioninja**
## About The Pull Request

A series of experimental changes with the intent of making nuke ops a more engaging gamemode for everyone involved.

- Ops nuke has to be planted in a specific random location.
- When a nuke is armed, the location it was armed in is announced to all crew members
- Nuclear bombs have a minimum timer of 5 minutes
- Nuclear bombs can now be defused, which immediately results in a major crew victory. This is not simple or fast.
- Nuclear bombs have to be anchored to be armed, and can't be unanchored once armed.
- All nukies receive 50 TC as a base
- Nukie shuttle always has a 20 minute delay before it can be launched
- War Challenge has been removed

If these work out or are well received, I have more ideas for deeper reworks. This is more of a cursory pass to see if a completely different vision of nuke ops with roughly the same idea and theming could work.

## Why It's Good For The Game

The current issue with ops is that blitz ops is trivially easy, stealth is still way too easy and normally means station goes delta with nothing crew can do and many not being aware there were even ops.
War ops is ironically considered the better gamemode by most players, but a lot also view it as a waste of a round, and it's been pretty contentious on the adminstration front. I also personally agree with the viewpoint that it thematically goes against a lot of core ideas of the game, but that's more of an aside.

The intention of these changes is unifying stealth and war into one giga nukie memefest.

The intended way for nukies to play following this change is to be as stealthy as possible up until the plant, upon which they will need to successfully defend against the crew immediately rushing to wherever they planted.

Despite this being the intended way to play, of course you could go loud immediately from the beginning, or use some kind of sneaky trap-based tactic once the nuke is armed, or etc.

What people dislike about war is the announcement, breakdown of command, and so it was removed.
What people like about war is the whole station working together to take down a loud big threat, which is what the announcement does.

## Changelog
:cl:
balance: Nuclear Operatives Rework
balance: Nuke has to be planted in a specific location that is randomly picked roundstart
balance: When a nuke is armed, the location it was armed in is announced to all crew members
balance: Nuclear bombs have a minimum timer of 5 minutes
balance: Nuclear bombs can now be defused, which immediately results in a major crew victory. This is not simple or fast.
balance: All nukies receive 50 TC as a base
balance: Nukie shuttle always has a 20 minute delay before it can be launched
balance: Nuclear bombs have to be anchored to be armed, and can't be unanchored once armed.
balance: War Challenge has been removed
/:cl:

### CODE REVIEW

**Comment by Iamgoofball** [comment]
counter-terrorists win

**Comment by Taylorkills2** [comment]
Ehh, I like the changes to how the Nuke will work, but what happens when the Ops get syndicate bombs at a discount and mass syndicate bomb without any warning? Now the entire station is spaced with almost no warning(perhaps literally no warning if the ops stealth infiltrate and c4 the bomb core).
Only thing that survives is borgs(who can't attack the nuke ops) and a small handful of people which will almost certainly be gunned down before they can do anything against the Nuke Ops.
As much "unfun" War Ops and Stealth Ops, and Blitz Ops are, I'm pretty certain this will just create a meta where the Ops kill everyone/thing before they arm the bomb, then everyone gets to wait the 5+ minutes for the round to end.

**Comment by SkeletalElite** [comment]
If there isn't already nukies should have a choice between a few locations.

Additionally, I think it would be good if they were allowed to use the station nuke as well with the benefit that it has a slightly lower minimum time.
Also they can arm without the disk if they want but the minimum time is higher if they do that.

**Comment by Tlaltecuhtli** [comment]
what if someone uses the blueprints? can ops make it so the  annoncement says "nuke planted in ligma balls"

**Comment by Mickyan** [comment]
Small issue I see with this is what happens when the countdown is almost over and nukies are forced to leave the nuke unguarded to retreat to the shuttle, would be easily fixed by adding a short delay between the end of the countdown and actual explosion during which the nuke can't be defused anymore

**Comment by kriskog** [comment]
Needs to make sure it cant be memed by boh bombs and shit like that. Theres quite a few ways of cheesing the defense too, like just building rwalls around the nuke. Not sure how to prevent that though.

**Comment by Michael-Ashfield** [comment]
Saboteur borg RCD spam and syndie bomb spam to stop non-suited crew will be the new meta.

Is this balanced for the amount of time it will take the escape shuttle to arrive and escape. If its 20min for the nukies to arrive, and minimum 5min for the nuke to blow, that leaves very little margin for getting the disk and planting the nuke before the crew has left.

**Comment by SkeletalElite** [comment]
So I see that you have a check to make sure nukies can't interact with the wires
Does this check stop sabo borgs too?

**Comment by HomocidlePancakes** [comment]
Do you still need the disk?

**Comment by anconfuzedrock** [comment]
every op round where the ops have their own nuke instead of using the vault nuke is an op round where lord jesus christ is weeping

**Comment by Yenwodyah** [comment]
Why keep the war ops shuttle timer around?

**Comment by kriskog** [comment]
The 20 minute timer is good, it forces people to slow down and might make it easier to lay a plan. It will also allow crew to settle into the round before the action kicks off.

**Comment by evilcyborgmrt** [comment]
20 min timer is way too long. It would suck to roll antag and have to alt tab for 20 minutes before you could do anything.

**Comment by SkeletalElite** [comment]
I agree 20 minutes is too long.
Maybe 10 would be better. That's plenty of time for the crew to get settled in and by the time the OPs are all geared up and have a plan there will only be a few minutes left instead of just tab out and wait 10-15 minutes

**Comment by nightred** [comment]
The 20 minute timer is not for the antags only, They should be planning not alt tabbing out.
The crew also needs that 20 min to do initial setup, get resources, station round start is about 20 min until most basic items are unlocked and ready to be used.

**Comment by trollbreeder** [comment]
Sounds like cult with the blood magic replaced with guns, guns, and some other uplink items. And without conversion (not counting hypnoflash).

**Comment by ATH1909** [comment]
So now you're only gonna have 5 minutes to grab a space suit ("AI OPEN EVA RIGHT THE FUCK NOW") and a half-decent weapon and stop a fully-armed and armored terrorist squad (who will laugh at the puny spears that you try to throw at them) before their nuclear device detonates and kills everyone?

5 minutes is nowhere near long enough for most of the crew to acquire weapons that can pose an actual threat to ops in, say, shielded hardsuits, especially if you also have to factor in the time needed to get a space suit so that you don't die in the rooms that the ops have depressurized.

IMO, a better rework would be to just make ops need to use the station's nuke core instead of their own nuke. Maybe replace the space tiles around most vaults with reinforced walls, too, so that it's harder to depressurize the vault (and the hallway surrounding the vault).

**Comment by AWalton** [comment]
50 TC limit greatly limits the variety of loadouts you'll see, especially if the ops are now required to hold off the entire station from one location for five whole minutes.

**Comment by knacker48** [comment]
Wait you're getting rid war ops? That was the only halfway balanced version of nuke ops, the twenty minute window you got was there so you can prepare for them and have a fighting chance. Now its just stealth ops but arrives artificially late.

You say that the part that people liked about war ops was the banding together of different departments to take down the huge incoming threat, but what good is that if you only really have 5 minutes to take care of them. This just gets rid of all the planning and frantically working towards some meaningful deterrents and leaves us with 'I hope you weren't wasting the first 20 minutes of your shift on your autism projects'.

This almost feels like the combining of the worst aspects of nuke ops as it still has the out of nowhere round ends that stealth and nuke ops had combined with an even more frantic collapsing of command, as I'm almost certain that even now HoP or cap are still gonna give out AA as they did with nuke ops, provided they haven't been killed yet

**Comment by itseasytosee** [comment]
Its gonna be impossible for nukies to escape now

**Comment by ATH1909** [comment]
> Its gonna be impossible for nukies to escape now

Nah, all you gotta do is leave one guy behind at the nuke op base and tell him to, instead of having fun assaulting the station/defending the nuke with the rest of the team, hand over all of his TC to the rest of the nuke op crew and alt+tab out to browse Reddit or something until the round ends (with some occasional movement to keep from being disconnected for inactivity). When the nuke blows and kills the rest of the team, the ops will still greentext because of their single "Home Alone" op that they left back at their base.

~~If the guy you select to stay behind protests this, get an admin to bwoink him for not aiding his team as a team antag.~~

It's like ash walkers all over again- you gotta leave one guy behind at the nest/base so everyone else can go raid the station.

**Comment by Geikkamir** [comment]
I still think it would be better to give Nukies like 2-4 steal objectives in addition to the disk. The real problem with all versions of Ops in my opinion is that everything is too focused on one location. The disk is the only thing that matters so the best strategy is to just throw everything into bumrushing the captain, and likewise protecting the captain for the crew on war ops. This doesn't really solve that problem because the game is still choked down to a single location after the Ops get the disk.

The strategy would be a lot more diverse if the Ops plans had to account for more than just alpha-striking the captain. Having to choose how to approach several objectives dispersed throughout the station instead of always committing everything to a single attack presents a much more interesting challenge. 

Ops might, for instance, have to choose between splitting up and trying to approach several objectives at once, making themselves more vulnerable but giving the crew less notice, or sticking together and approaching them one by one, which makes them more difficult to kill, but gives the crew more time to respond.

Just my two cents.

**Comment by AdamElTablawy** [comment]
if you were going to go for goon ops you might have instead gone all the way instead of half-assing it

might as well just remove the escape requirement at this point too, given that trying to escape would leave the nuke undefended

@Geikkamir something like that in a similar gamemode was already tried and it blew ass

**Comment by Bawhoppen** [comment]
While current nukeops does have some problems, I can't see this alternative being a long-term success. Milling around one place defending it does not seem like it would be all that interesting. w The current one is at least relatively more dynamic and forces all sorts of interesting situations, with people moving around trying to get to places, dealing with perilous threats, etc. This just seems like it will lead to some meta of ops building walls or destroying everything around the place they have to defend, or something.

It might be a breath of fresh air initially when it's first tested... but so was warops when it was first added. Just doesn't seem that viable for being a fun replacement in my eyes.

**Comment by Pugie** [comment]
What's the point of having defusal if nukies can just cut a fuckup wire to fry the circuitry? Am I missing something here?

**Comment by actioninja** [comment]
> What's the point of having defusal if nukies can just cut a fuckup wire to fry the circuitry? Am I missing something here?

nukies can't interact with the wires.

**Comment by Pugie** [comment]
> nukies can't interact with the wires.

Ah, my bad. Cool changes, would be nice to finally curb nuke ops being end shift in 3 minutes the gamemode.

**Comment by actioninja** [comment]
I had a longer response typed up and then accidentally deleted it, but in short:

1. exact times are subject to change
2. previous TC was 25 by default and went to around 70 with 6 operatives
3. depressurization or wall spam might become the meta strat, but I'll deal with that when it's gotten to
4. Not interested in making the station nuke the only or a possibility of a target
5. There already is a lot of anti-cheese countermeasures built in that I just didn't mention.

**Comment by cacogen** [comment]
interested to see how this works out

**Comment by ATH1909** [comment]
> 3. depressurization or wall spam might become the meta strat, but I'll deal with that when it's gotten to

So you're aware that a cancerous strat exists, yet want the maintainers to merge this PR BEFORE you make an anti-cheese measure for it? Op rounds are gonna be real ""fun"" while you make your fix PR...

**Comment by actioninja** [comment]
I think you're forgetting that most people don't play the game as their own personal bug hunt meta abuse sandbox.

I want to see first if it's truly a problematic strategy that is a surefire way to win, and also a thing called a testmerge exists.

**Comment by Tlaltecuhtli** [comment]
can ops arm beer nuke?

**Comment by actioninja** [comment]
I think I'm done with balance and features for a while.

**Comment by cacogen** [comment]
that's a shame

**Comment by Mickyan** [comment]
this had great potential, i'm sad

**Comment by Pugie** [comment]
Noooo

**Comment by Bokkiewokkie** [comment]
Definitely sad that you closed it, though I can't blame you with how big of a discussion (and PR) this is.

**Pull request closed without merging**
