### PR TITLE
3/4 sprite boxes REDONE

### PR DESCRIPTION
**Pull request by Militaires**
:cl: Basilman
add: New box sprites
/:cl:

REDID BOXES, SPRITES SOON

not so thicc

### CODE REVIEW

**Comment by ChangelingRain** [comment]
why are these like super, super tall

**Comment by ChangelingRain** [comment]
also beepsky is on one of your boxes is that a feature

**Comment by Militaires** [comment]
@changelingrain photobomb

if they appear 2 tall i can e-z edit

**Comment by coiax** [comment]
I don't like them.

**Comment by uraniummeltdown** [comment]
way too thicc

**Comment by MrStonedOne** [comment]
I hate them

**Comment by MrStonedOne** [comment]
I hate this trend to 3/4

**Comment by Mindustry** [comment]
How do these boxes fit in our bags when they look like they can hold a human.

**Comment by KorPhaeron** [comment]
bad

**Comment by KorPhaeron** [comment]
@WJohn gets the real decision though

**Comment by PKPenguin321** [comment]
3/4ths perspective more like thicc/thiccths perspective

**Comment by Jordie0608** [comment]
I was wondering why these looked small until I realised they weren't the MGS cardboard boxes.

**Comment by Ausops** [comment]
i thought these were the boxes you hide in, they gotta be way smaller for the storage boxes

**Comment by Cheridan** [comment]
he redid the sprites

**Comment by Militaires** [comment]
thanks to @wjohn for showin me the light

**Comment by anconfuzedrock** [comment]
why don't you just take the regular box sprite and rotate it 90 degrees

**Comment by Militaires** [comment]
@anconfuzedrock cause then u wont tell what any of the imagery on the boxes is youll need to put your mouse to know

**Comment by Militaires** [comment]
GIT SHAT ITS FUCKING BED

**Comment by WJohn** [comment]
They're smaller now, and the coloring is better, I helped with some of it.

**Comment by PKPenguin321** [comment]
Show them in game

**Comment by Mindustry** [comment]
wheres the heart on the box of hugs?

**Comment by WJohn** [comment]
They're overlays.

**Comment by Incoming5643** [comment]
My personal opinion is that even if a change to 3/4s is in the cards for structures/machinery that it shouldn't extend to items, as it makes them blend into the background and look nonsensical in the hand/storage slots.

**Comment by MrStonedOne** [comment]
Consistency for consistency's sake seems counter productive.

Some things look better in some perspectives.

**Comment by Thunder12345** [comment]
How will 3/4 perspective work with anything that isn't shaped like a perfect cuboid?

**Comment by Kromgar** [comment]
These still look bad

**Comment by Militaires** [comment]
i mean you guys dont seem to like them but little to none of you told me WHY they're bad or just gave me reddit downboats

**Pull request merged**
