### PR TITLE
Adds helpers for commonly used tools.

### PR DESCRIPTION
**Pull request by ShizCalev**

### CODE REVIEW

**Comment by Qustinnus** [comment]
good shit

**Comment by optimumtact** [comment]
this is bad, toolflags should exist

**Comment by optimumtact** [comment]
cyberboss finish your dan construction overhaul

**Comment by RemieRichards** [comment]
@optimumtact dan isn't here right now, but I'm taking messages for him.

**Comment by lzimann** [comment]
This is ugly, but so are all the tools so idk

**Comment by Cyberboss** [comment]
construction overhaul would be orthogonal to the tools overhaul

**Comment by lzimann** [comment]
hey i'm doing something to take care of all these istypes, so don't merge please etc

**Comment by Cyberboss** [comment]
I much prefer lzi's solution tbh, istype spam needs to stop

**Pull request closed without merging**
