### PR TITLE
Fixes all the occasions where a wizard could find/make sandals and get the nerfed sandals.

### LINKED ISSUE #22234: Wizard: Battlearmor gives old sandals
As the title says, messing about on a test server as wizard and the battlearmor buy gives you the old/regular sandals instead of the new magical sandals.

MAYBE: Returning an item to yourself hits you with that item.
Haven't been able to reproduce it.

### PR DESCRIPTION
**Pull request by Incoming5643**
Instead of the "new ones" (read, old ones) introduced in #22164

Fixes #22234

### CODE REVIEW

**Comment by ExcessiveUseOfCobblestone** [comment]
I thought the shoes weren't needed though?

**Comment by Incoming5643** [comment]
They aren't needed but the intention wasn't to nerf the wizard. Walking around without shoes because acid ate them away still sucks

**Comment by ExcessiveUseOfCobblestone** [comment]
but that isn't a reason to give them acidproof, whereas previously it would literally ruin there ability to wizard.

**Comment by Cyberboss** [comment]
Im okay with a wizard nerf of this magnitude

**Comment by Incoming5643** [comment]
The sandal/magic subtype was literally made to give wizards shoes of the same quality as they previously had. It is the only reason they exist, and wizards are ALREADY getting them.

They were just inconsistently applied to other ways of dressing as a wizard that the wizard sometimes uses because the last PR didn't properly update all the paths.

**Comment by jughu** [comment]
Yeah i removed acidproof and fireproof from normal sandals which was like every sandal in existance
And added a subtype for wizard so theu cant smelt his sandals off and throw glass shards everywhere so he has a harder time to move

**Comment by jughu** [comment]
A stack of glass shards could be a instakill for a wizard if used right with acid

**Comment by jughu** [comment]
And thats why i added the subtype

**Comment by ExcessiveUseOfCobblestone** [comment]
seems a bit silly and hugbox-y to give a wizard that when he has plenty of mobility spells to avoid them altogether or avoid them long enough to get shoes.

Anyways I'll probably """fix""" that later since this PR is just being consistent.

**Comment by jughu** [comment]
Try avoiding it in the moment of adrenaline and you walk in a stack of glass shard without shoes and then instacrits

**Pull request merged**
