### PR TITLE
Footstep sounds for bare feet

### PR DESCRIPTION
**Pull request by nero1024**
Bare feet will make the correct footstep sounds now and added some new samples to go with them.

:cl: Nero1024
soundadd: Bare feet will now make the correct footstep sounds.
/:cl:

It works and it's technically ready to be merged as-is ~~however some additional features I would like to add has got me stumped.~~
~~TODO:
-Get digitigrade/clawed feet to play the claw footstep sounds (how to check for mutant/digitigrade bodyparts?)~~ Nope, some other time.

### CODE REVIEW

**Comment by Iamgoofball** [comment]
do i even need to say it

**Comment by Iamgoofball** [comment]
i'm going to say it anyways so people dont play dumb, this is foot fetish crap especially since the first part of the commit history is them adding claw footstep sounds and their avatar is their deviantart OC or something, i'd reverse google search it to confirm but you know something something doxxing
fuckoff

**Comment by Jordie0608** [comment]
\>the first part of the commit history is them adding the files for their PR to work
Goof are you serious

**Comment by Jordie0608** [comment]
Don't add commented out code or files if you're not going to use them; leave it for a later PR if you're not going to do it now.

Also you should download a git client and not use the web editor.

**Comment by obscolene** [comment]
>i'm going to say it anyways so people dont play dumb, this is foot fetish crap especially since the first part of the commit history is them adding claw footstep sounds and their avatar is their deviantart OC or something, i'd reverse google search it to confirm but you know something something doxxing
>deviantart OC
you mean furaffinity

**Comment by Niknakflak** [comment]
Footsteps were a great addition.

As a sound designer, the footstep sound I evaluated sounded sticky, like your foot sticking to the floor. 
This was the hard floor, aka the most likely floor everyone will be on.  
However, I'm not dealing with downloading like 9 sounds just to hear them especially since I can only ever play them one at a time, one after another and not in the context of how they will be in game.

Therefore, I request a video preview to hear what they sound like actually ingame please.

**Comment by MMMiracles** [comment]
@Iamgoofball the leather club is 2 blocks down

**Comment by ma44** [comment]
**web editor intensifies**

**Comment by epochayur** [comment]
\>sound pr
\>no video/sound clip of it actually in motion

if this is a joke, it's a bad one

**Review by GuyonBroadway — CHANGES_REQUESTED** [review]

**Comment by fludd12** [comment]
Just a heads up, you might want to clean up your branch! A lot of these commits are messy and such. Look up how to squash commits with `git rebase`, and the repository will look a lot cleaner.

**Comment by obscolene** [comment]
I think the real question here is whether maintainer-permission was granted for a PR with features specific to nonhuman races.

**Comment by nero1024** [comment]
Here's a webm of the sounds in (a hastily set up) action.
https://my.mixtape.moe/lrtohp.webm

**Comment by Iamgoofball** [comment]
It's good to hear how it mixes with other sounds shizcalev

**Comment by epochayur** [comment]
finally we can know the true terror of hearing _*SCHLAP SCHLAP SCHLAP*_ from down a dark hallway and seeing a nude, blood-drenched assistant running at you full-speed with an e-sword

**Comment by nero1024** [comment]
Okay, so I've been working on a new PR that is essentially a new and improved version of this with some additional stuff tacked on. Closing.

**Pull request closed without merging**
