### PR TITLE
Adds support for dead cyborg sprites, and adds said sprites for Medical and Service models

### PR DESCRIPTION
**Pull request by zxaber**
## About The Pull Request

Adds support for dead cyborg sprites, and adds sprites for the default medical cyborg and all service cyborgs
## Why It's Good For The Game

Dead borgs are often left by the wayside, and partly because it's not really obvious that they're dead. For most borg sprites, being as they are non-humanoid, simply making them be horizontal would look terrible. Instead I've added support for *_offline icon states.

The offline versions of the default medical borg (and mimicking Kent service borg) feature the screen and thrusters turning off. They are also moved downwards slightly, as if having fallen to the ground.
image

The four humanoid service borgs *do* turn horizontal, but because they're the only humanoid sprites, I see it as acceptable.
## Changelog
:cl:
add: Medical and Service borgs now are more noticeable when offline.
/:cl:
I had also intended to include disabling the borg light/eye overlay while they're dead, but that's actually already the case. So there is somewhat of a tell, even if it's not the most noticeable for a few (like the engi borg).
<details>
  <summary>Image</summary>

image

### CODE REVIEW

**Comment by SomeoneYouProbablyKnow** [comment]
If the goal is to make it obvious consider adding MORE stuff, spark effects, sprite rotation, anything. As it's it's only making it a bit more visible (just as long as faking death as borg still works, it's really fun)

**Comment by atlasle** [comment]
the engineering and mining borg just look turned around

**Comment by Fikou** [comment]
i cant deathgasp anymore

**Review by Wallemations — APPROVED** [review]

**Comment by Sealed101** [comment]
consider using matrix bullshit for the oldborg service borgs because borgs can wear hats and just setting the borg's icon to horizontal won't magically rotate the hat

**Comment by zxaber** [comment]
That's a good point.

I'm not sure how best to do that selectively, though. I'd rather not use a hard-coded list of rotatable sprites.

**Comment by zxaber** [comment]
I'll be back to this soon, but possibly not before the stale bot gets upset.

**Pull request closed without merging**
