### PR TITLE
normalize .dm EOLs to use LF + force

### PR DESCRIPTION
**Pull request by mloc**

### CODE REVIEW

**Comment by RemieRichards** [comment]
What the christ is this

**Comment by Dorsisdwarf** [comment]
Unless this is really important, this needs to be DNM until we can sort through the commit with a fine comb, since this is so big you could have literally reverted runspeed and goonchem or made assistants spawn with pulse rifles and git compare can't tell us

**Comment by Jordie0608** [comment]
This is replacing all the CRLF line endings with LF.

**Comment by Man-Shroom** [comment]
>Over 1,000 files changed

Adminbus port doesn't seem so bad now does it Remie?

**Comment by RemieRichards** [comment]
@Man-Shroom Oh fuck off.

**Comment by xxalpha** [comment]
This needs its own special freeze. Won't this conflict with everything?

**Comment by AnturK** [comment]
Just put something in .gitattributes and wait for changes instead of changing all files..

**Comment by Razharas** [comment]
Last attempt of doing this gave me PTSD, im officially triggered

**Comment by Razharas** [comment]
No but seriously didnt we try this exact thing about a year ago and if blew in our faces so hard we were forced to revert it?

**Comment by Man-Shroom** [comment]
@RemieRichards kek

**Comment by Fayrik** [comment]
How about we don't change the entire project in a single pull?

**Comment by Dorsisdwarf** [comment]
Or if we have to do it in a single pull, how about not a single commit?

**Comment by Miauw62** [comment]
>entirely changing every single file in the entire project
>not adding newlines to files without newlines at the end of the file

cri

**Comment by Mloc** [comment]
last time was LF -> CRLF which git really doesn't like
this is forcing LF which is sane and git likes it.
this stops stupid mixed up files and stuff like cf2048b897056ae0da4dc0be424ef73c9abccada
the second commit can be re-done with this if a maintainer would prefer to do it:
````
shopt -s globstar
dos2unix **/*.dm
````

**Comment by GinjaNinja32** [comment]
[There are no non-whitespace changes in the second commit; here's a diff with whitespace ignored.](https://github.com/Mloc/-tg-station/commit/4d41a9cb5ef7ed8332def99b17263f8d6b4e33a0?w=0).

**Comment by vista-** [comment]
Protip: put ?w=<any number> at the end of the URL to ignore whitespace, it works universally on any PR URL.

**Comment by optimumtact** [comment]
:+1: thank you Mloc

**Comment by MrPerson** [comment]
Why though? How many times have we had that "git reports a file as different despite being the same" issue over the past 4 years?

**Comment by callanrocks** [comment]
oh my

**Comment by CorruptComputer** [comment]
Isn't LF just for unix? Will this still work for people on windows?

**Comment by vista-** [comment]
Yes, it will force LF when you do any (modifying / pushing) git command.

**Comment by MrStonedOne** [comment]
and the merge conflicts start.

hahaha

**Comment by Mloc** [comment]
merge conflicts don't really matter here
if someone wants to merge it I can redo the last commit very quickly and it won't conflict

**Comment by optimumtact** [comment]
If you're a windows user, set git up to automatically convert line endings on push pull
https://help.github.com/articles/dealing-with-line-endings/

**Comment by Mloc** [comment]
this commit forces that

**Comment by CorruptComputer** [comment]
What about when you download a zip, for quick testing of a PR? Because that's how I downloaded this to see if it broke, and when I opened something up it had no new lines.

**Comment by GinjaNinja32** [comment]
The zip will contain LF. If you set up Git to checkout as CRLF (which may be the default on Windows systems, I'm not sure), then the following will work:
```
$ git fetch upstream pull/[ID]/head:[branch]
$ git checkout [branch]
```

**Comment by Mloc** [comment]
@CorruptComputer What did you open it up in?

**Comment by CorruptComputer** [comment]
@Mloc Notepad++

**Comment by MrPerson** [comment]
The filesize decrease of this is irrelevant. What purpose does it serve again?

**Comment by vista-** [comment]
Make line endings standardized and sane.

**Comment by MrPerson** [comment]
What practical effects does this have?

**Comment by Jordie0608** [comment]
It stops things like this from happening https://github.com/tgstation/-tg-station/commit/cf2048b897056ae0da4dc0be424ef73c9abccada

**Comment by optimumtact** [comment]
merge conflicts :cry: 

please merge this faster next time

**Comment by Razharas** [comment]
@Mloc

**Comment by optimumtact** [comment]
Please merge as soon as is updated

**Comment by Razharas** [comment]
Well mloc didnt respond for half a month i guess this is it then
@mloc ping some maintainer if you want to reopen this

**Pull request closed without merging**
