### PR TITLE
YOU CAN NO LONGER OVERDOSE ON WATER

### LINKED ISSUE #47265: You are able to OD on chems that don't have an OD point
So far this has been seen in Potassium Iodine and Water. Im gonna go out on a limb here and assume it wasnt intended for you to be able to OD on water of all things. This has no actual effect but does show you as OVERDOSING when scanned with an analyzer

Issue reported from  Round ID: 121879 (/tg/Station Sybil [ENGLISH] [US-WEST] [100% LAG FREE])

Reporting client version: 512.1488

### PR DESCRIPTION
**Pull request by ATH1909**
## About The Pull Request

Fixes https://github.com/tgstation/tgstation/issues/47265.

My PR that "fixed" the interaction(s) between skeletons and milk accidentally made it so that you can "overdose" on any chem that doesn't have an overdose threshold, which is, uh, bad. To make matters worse, this bug (which SHOULD be fixed in this PR) made it so that they can't even properly process milk (an issue that that PR was *supposed* to fix).

## Why It's Good For The Game

This is kind of an important bug to fix, both for confused medical doctor mains and for people who are playing as skeletons this Halloween.

## Changelog
:cl: ATHATH
fix: You can no longer overdose on water.
fix: Skeletons and such should now be properly able to process milk (for realzies this time).
/:cl:

### CODE REVIEW

**Comment by AtlasRules** [comment]
i do hope you know
you can overdose on water IRL

**Comment by PKPenguin321** [comment]
was gonna say, yeah... should have a pretty high threshold but from what i understand it makes your organs stop working

**Comment by ATH1909** [comment]
> was gonna say, yeah... should have a pretty high threshold but from what i understand it makes your organs stop working

Well, that'll probably have to be added in a future PR, as I'm not going to risk my bugfix not getting merged because I attached a new feature to it.

**Comment by Shadowflame909** [comment]
how much bloat, lag, and time would it take to give all ODless reagents a 1000u OD that gives your liver max organ damage?

**Comment by Twaticus** [comment]
drink more water

**Comment by Arturlang** [comment]
Yknow, there is this thing called testing ones PRs locally.

**Comment by davethwave** [comment]
Well this was kinda a unexpected bug out of the blue. Who could have anticipated a fix for skeletons processing milk cause OD on water and stuff.

**Comment by Fikou** [comment]
a woman drank 10l of water for a week straight, watch what happened to her brain

**Pull request merged**
