### PR TITLE
FEATURE FREEZE: Surprise temporary thaw

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
Thank you for all the hard work so far everyone. I know freezes can get boring/demoralizing, so starting now, for the next week anyone who has fixed at least one issue this freeze may open a single PR that ignores the freeze restrictions.

Please keep the PR relatively small (something that can be merged without too much effort or back and forth, no new game modes etc) so maintainers don't get too bogged down.

### CODE REVIEW

**Comment by Bluespace** [comment]
b-but the issue count is higher than when the freeze began

**Comment by praisenarsie** [comment]
no it wasn't

**Comment by iskyp** [comment]
it was over 1100 when the freeze began

**Comment by KorPhaeron** [comment]
@Bluespace 

A) That is false

B) New issues being opened doesn't mean other issues weren't fixed

**Comment by iskyp** [comment]
reminder that there are 5 pages of "needs reproducing" labeled issues with a lot being months and years old

**Comment by Bluespace** [comment]
oh i thought it was at 1000 when the freeze began :)

**Comment by CPTANT** [comment]
Someone has to close some dupe issues, the same supermatter issue is reported like 5 times.

**Comment by KorPhaeron** [comment]
@cptant

tag me in them

**Comment by PKPenguin321** [comment]
This PR better get merged

**Comment by Bombpants** [comment]
Hey did cluck cult get removed?

**Comment by Xhuis** [comment]
CC is off rotation

**Pull request closed without merging**
