### PR TITLE
Prevents ahelping youtube links

### PR DESCRIPTION
**Pull request by Cyberboss**
Requested

### CODE REVIEW

**Comment by optimumtact** [comment]
code solution to an admin problem 👎

**Comment by duncathan** [comment]
I'm with oranges here

**Review by deathride58 — CHANGES_REQUESTED** [review]
Make this a config thing, or just give admins a preference to simply not get notifications from ahelps containing youtube links.

Also, people can just bypass this by replacing the dots in the URL with (DOT) or similar

**Comment by lzimann** [comment]
this is stupid and pointless

**Pull request closed without merging**
