### PR TITLE
Larger Extinguishers

### PR DESCRIPTION
**Pull request by MadmanMartian**
:cl:
add: Adds two larger fire extinguishers. Large and bluespace.
/:cl:

[why]: # Requested by a dude in FTL13 who plays chief engineer a lot, seemed like something that should be in the upstream.

### Todo:
 - [x] Have it acquirable from somewhere (Not sure where, suggestions requested)

### CODE REVIEW

**Comment by Mark9013100** [comment]
Large Extinguisher should be in an advanced engineering node, bluespace extinguisher in one of the bluespace nodes, have them printable at Engineering protolathes and maybe Medical protolathes.

**Comment by SgtxRootbeer** [comment]
And the sci lathe, since toxins.

**Comment by Bombpants** [comment]
Cyro extinguishers that can cool the water to help deal with high temp fires?

**Comment by Kagus** [comment]
> Cyro extinguishers that can cool the water to help deal with high temp fires?

That's literally how /TG/ extinguishers work.

**Comment by Bombpants** [comment]
So there is no benefit of having super cooled water vs room temp water?

**Comment by Kagus** [comment]
There is, that's why extinguishers already cool down the water placed inside of them. This is why they're used against slimes; slimes aren't hurt by water, but they _are_ hurt by cold temperatures. You spray water at them, the water is magically cold because of the extinguisher, the slime gets hurt. The backpack extinguishers (atmos' resin launchers) spray water that's slightly colder than the normal extinguishers put out, if I remember correctly.

I suppose you could have cryo extinguishers that chill it even more than the backpacks, but the difference of 10-20 degrees isn't that huge, so to get a tangible and desirable effect you'd need to really crank the cooling up a notch (which has its own issues). It also doesn't really follow the cryo container trend of keeping its contents nonreactive, since that's a non-issue in a fire extinguisher.

---
What _I_ really wanna know, is if we could get one a' these in pepperspray flavor.

**Comment by FantasticFwoosh** [comment]
Im partly dissapointed these don't have some unique function like being back mounted with a nozzle like the other large quantity reagent spraying packs, it feels like '**_make it bigger'_** is being counterintuitive to **_'make it smarter'_** as a improvement.

- Especially given the advanced extinguisher has foam.

Still i could readily understand some of the reasons why more capacity is better, just not all of them. Maybe make a 'advanced firefighting tools' node with some other helpful gear to be accessed like other people said from engielathe?

**Comment by optimumtact** [comment]
Have them printed from the engineering lathe and add them on techwebs

Fwoosh if you want to add more firefighting tools knock yourself out.

**Comment by Poojawa** [comment]
Isn't this literally the point of the atmosia backpack firefighting gear though.

**Comment by SgtxRootbeer** [comment]
These can fit in backpacks, needed for the engineer/tech who doesn't have time or ability to run to engineering and grab the backpack extinguisher.

**Comment by Barhandar** [comment]
Cooperate with chemist to put firefighting foam in an extinguisher instead, or foam grenades.

**Comment by Poojawa** [comment]
Convenience for the sake of lazy convenience is bad. 

What would be a better option is to remove the resin component and add the backpack firefighting gear to the Engineering protolathe so there can be more than one. Maybe buff it's contained water as well so you can spray for a good while.

**Comment by octareenroon91** [comment]
>Cooperate with chemist to put firefighting foam in an extinguisher instead, or foam grenades.

How do you load foam?

need a new extinguisher-filler machine?
lathe designs that call for foam?

**Comment by optimumtact** [comment]
oh wait I forgot we already had the backpack sprayers.

I guess we don't need these, thanks ftl 13

**Comment by Kagus** [comment]
> > Cooperate with chemist to put firefighting foam in an extinguisher instead, or foam grenades.
> 
> How do you load foam?
> 
> need a new extinguisher-filler machine?
> lathe designs that call for foam?

Yeah, we need to fix some of the tips/descriptions related to extinguishers... You can only load one substance into extinguishers, and that can only be done via certain containers (large tanks, primarily). Normal and backpack extinguishers take water, advanced extinguishers take foam. You can only reload advanced extinguishers via large foam tanks ordered via cargo (last I checked, no maps spawned with them pre-existing), chemistry can only use their firefighting foam for chem grenades and such.

**Pull request closed without merging**
