### PR TITLE
Lavaland Pizza Party

### PR DESCRIPTION
**Pull request by MMMiracles**
pizza

A rest-stop for miners to sit down, have a slice of """'""fresh"""'"" pizza, then take a cool refreshing drink from the punch dispenser.

RIP Timmy.

### CODE REVIEW

**Comment by KorPhaeron** [comment]
What is the DEEP LORE and also this just kinda just seems like an empty room without much new to it

**Comment by JJRcop** [comment]
https://www.youtube.com/watch?v=VoPR88koEIw

**Comment by MMMiracles** [comment]
A ruin to hide in during ashstorms while supplying a darker meaning to its existence if people actually bother to examine their surroundings.

**Comment by Zilenan91** [comment]
yeah man I can totally relate to a bunch of kids dying in hell during their pizza party

**Comment by MMMiracles** [comment]
There are no kids in the ss13 universe, only man-children.

**Comment by Steelpoint** [comment]
While I would argue we should keep lavaland ruins thematic to the location, but considering we already have a bunch of ""whacky"" non-sensicle ruins such as the Vet Clinic or the Bro Dude Bio Domes then I don't see a reason to enforce lore and consistency.

**Comment by optimumtact** [comment]
not every ruin has to be interesting all the time

**Comment by KorPhaeron** [comment]
The vet clinic has deep lore about being on lavaland

**Comment by MMMiracles** [comment]
The deep lore is the series of unfortunate events that led to little timmy's birthday pizza-bash being teleported via bluespace anomaly into hell itself.

its got free food, complimentary party hats, and an almost-depressing backstory for those who bother to look into the ruin a little more while waiting out the ashstorm.

RIP Timmy.

**Comment by Fox-McCloud** [comment]
It was a party to die for after the Disco Inferno.

**Comment by Jazaen** [comment]
You can explain everything using one of these words: NT, syndicate, WizFed, Nar'sie, bluespace.

**Comment by MMMiracles** [comment]
I'll have you know I made TWO fix PRs and the only memebalance PR I've made so far was the potion of flight.

i'm being oppressed

**Pull request merged**
