### PR TITLE
Adds international garbage day, a day to respect janitors everywhere

### PR DESCRIPTION
**Pull request by optimumtact**
## Changelog
:cl:
add: International garbage day is added, say thanks to your local janitor
/:cl:

### CODE REVIEW

**Comment by Shapsy** [comment]
jannies rise up

**Comment by PKPenguin321** [comment]
finally some appreciation

**Comment by MCterra10** [comment]
This is the content we need

**Comment by HomocidlePancakes** [comment]
GARBAGE DAY! *shoots you*

**Comment by MMMiracles** [comment]
I cant wait for people to forget about this till next year when the janitor is packing heat

**Comment by Borisvanmemes** [comment]
Remember to say thank you to the jannies, or we unperson you.

**Comment by wesoda25** [comment]
You should also give them ERT gear cleaning supplies

**Pull request merged**
