### PR TITLE
Gives non-antagonist combat-upgraded AI the ability to turn on your suit sensors. By force.

### PR DESCRIPTION
**Pull request by Buggy123**
# Now with **ANTAG FREEZE COMPLIANCE**!

Combat-upgraded non-traitor AIs now have a ability that allows them to enable and lock-on all suit sensors, permanently.

The only way to disable them is to damage the jumpsuit itself or get a jumpsuit that doesn't have a sensor in the first place. Making new jumpsuits, using unworn jumpsuits, and such will not work; if it has sensors, they're always enabled.

There are obvious tells that the suit is hacked if you either examine the suit or try to change the setting, but otherwise it doesn't alert anyone on usage.

Costs 25 points, because it's about as, or more obvious than camera upgrades, and it only tells you where people are and if they're still alive, unlike cameras which let you see. Also, a Asimov Combat AI doesn't have all that much to spend points on anyway, so cost isn't super important.

Also adds a equivalent upgrade disk, which can be printed in science if they have unlocked illegal tech, just like the Surveillance upgrade disk,

:cl: 
Add: Growing frustration in the Artifical Intelligence Connectunity has led to the development of a virus that forcibly enables suit sensors. Nanotrasen has outlawed this virus and forbidden all AI from using it, but beware that many AI upgrades disks still have a copy of the virus!
/:cl:

### CODE REVIEW

**Comment by carshalash** [comment]
Based

**Comment by HomocidlePancakes** [comment]
No.

**Comment by Buggy123** [comment]
>No.

Honestly, Malfs are so rare that I see more combat-upgraded AI than I do Malfs. This is more of a feature than you'd think.

**Comment by AnonymousNow** [comment]
This sounds cool at first reading, but the difference between a malfunctioning/Syndicate AI and a subverted one is a couple of degrees, at most, and I know I'm looking at this from a non-antag medical overwatch perspective, which is not where it's going to do the most damage.

**Comment by trollbreeder** [comment]
How about an upgrade disk for SUIT SENSORS you can print from the science techfab, like the surveilance disk?

**Comment by Buggy123** [comment]
>How about an upgrade disk for SUIT SENSORS you can print from the science techfab, like the surveilance disk?

Oh, good idea!

**Comment by trollbreeder** [comment]
PR looks ready for review.

**Comment by kriskog** [comment]
For the unitiated, this was his first PR. #48349

**Comment by itseasytosee** [comment]
Is there a reason you don't want normal malf AIs to have this ability? If you see it as too op for whatever reason you would think that the subversion of the ai would invalidate that

**Comment by kriskog** [comment]
There is currently an antag freeze, and this is his idea to avoid waiting for that to end.

**Comment by optimumtact** [comment]
no

**Comment by Tharcoonvagh** [comment]
Could you provide a reason

**Comment by Buggy123** [comment]
>no
Yes, a reason would be nice.

>There is currently an antag freeze, and this is his idea to avoid waiting for that to end.

I would be more patient if the antag freeze had any sort of end date set aside from "when we get more crew content" (which this is), or if the last update on it wasn't "well it's been literally months and we basically have no new crew content". Because, to me, that just screams that the antag freeze is borderline permanent.

**Comment by Timonkeyn** [comment]
can we like, merge this? i like this idea

**Comment by optimumtact** [comment]
doing an end run around an antag freeze is frowned upon.

If you want the freeze to end, make crew content, if you're not willing to do that, you are part of the problem.

**Comment by Toxici11i** [comment]
> doing an end run around an antag freeze is frowned upon.
> 
> If you want the freeze to end, make crew content, if you're not willing to do that, you are part of the problem.
> 
> There's no way I'd ever greenlight global crew suit sensors turned on for non antag AI's so this idea is effectively dead in the water.

"crew content" involves removing stuff like cloning removal, buffs to roundstart medbay e.g extra organs, you can now make a machine that spits out organs and other misc changes
n i c e

**Pull request closed without merging**
