### PR TITLE
Folders: tgui, refactor, qol

### PR DESCRIPTION
**Pull request by mozi-h**
## About The Pull Request

- [x] Relocate premade folders into a separate `folders_premade.dm`
- [x] Add tgui ✨
- [x] Make papers insertable by clicking on it with the folder (yeah!)
## Why It's Good For The Game
Snazzy new UI is always great. Makes folders more fun to use and makes it consistent with the new clipboards (see #57289)

grafik
grafik
(Respects syndicate logo)

## Changelog
:cl: mozi_h
add: Folders have a snazzy new look. (Check out those colours!)
qol: Rapidly pick up paper by clicking on it with a folder. Alt-click to remove an item from a folder.
refactor: Split and cleaned up folder code.
/:cl:

### CODE REVIEW

**Comment by TheBonded** [comment]
Clipboards next?

**Comment by ArcaneMusic** [comment]
image
Where's the code?

**Comment by optimumtact** [comment]
where's the code?

**Comment by mozi-h** [comment]
> Clipboards next?

Not sure if you're trolling or not, @TheBonded, but I already have a PR open for that. Check this PR's description.

**Comment by TheBonded** [comment]
> > Clipboards next?
> 
> Not sure if you're trolling or not, @TheBonded, but I already have a PR open for that. Check this PR's description.

Sorry, I'm exhausted and somehow missed that. Please ignore my ignorance

**Comment by mozi-h** [comment]
I only now notices, I called the branch `tgui-clipboards`. This confused me a lot. Wow.
The one actually for clipboards is `fix-clipboards`; this was intended to be `tgui-folders`. Big facepalm.

**Pull request merged**
