### PR TITLE
The captain's laser is now the captain's laser, not centcom's laser

### PR DESCRIPTION
**Pull request by silicons**
Can now be unlocked by captain ID.

### CODE REVIEW

**Comment by Cyberboss** [comment]
Balance change, this was intentional

**Comment by PKPenguin321** [comment]
Freeze

**Comment by PKPenguin321** [comment]
Hey wait this was frozen it could be reopened

**Comment by Cyberboss** [comment]
@lzimann

**Comment by lzimann** [comment]
i mean it will most likely be denied anwyay

**Pull request closed without merging**
