### PR TITLE
Revert "Unit tests radio, saymode, and language prefix keys"

### PR DESCRIPTION
**Pull request by MrsTonedOne**
Reverts tgstation/tgstation#71328 (@Zonespace27 )

Departmental shorthand (.h/:h) is a convenience alias that should apply to all jobs and all race types and all classifications. ITS SUPPOSE TO FUCKING CONFLICT.

if you are ai and not in a holopad, it should go to binary.

if you are ai and in a holopad, it should go to the holopad.

if you are borg it should go to binary

if you are xeno it should go to alien

Removing it from the AI over a stupid need to made universal broad reaching rules that can be declared upon the code was stupid.

This entire unittest is needlessly overboard and over generic putting "rules" that are not backed up by logic on the codebase in a way that hinders making good UX, not help.

The datumized saymode system not being able to handle this complexity when the old hardcoded system could is a problem with the datumized saymode system and not the fucking :h shortcut for holopad.

:cl: Common fucking sense
fix: The changes to Mafia and holopad say prefixes was reverted.
spellcheck: Mafia changeling say prefix has no longer been changed to .1, and has been returned to .j
spellcheck: AI Holopad say has no longer been changed to .2, and has been returned to .h
/:cl:

### CODE REVIEW

**Comment by MrStonedOne** [comment]
from the og pr.

> I'd argue it's bad UX to say "h is radio shorthand, unless you're a specific role using a niche feature, then it's holopad speak"

THEY ARE THE SAME FUCKING FUNCTION.

h == do alternative say.

in jobs for humans, this is the primary department.

in races with alt communication modes who lack the ability to wear headsets (ai, xeno), it can be a shorthand for those alt communication modes.

this is the same function.

Calling it bad UX because you want to pigeon hole it to 'radio' because thats it's most common use is bad logic.

**Comment by necromanceranne** [comment]
The argument of the original PR seems sound. Keeping radio keys from overlapping is probably best just in case a single mob somehow obtains multiple channels that use the same letter. I don't see how that isn't something to watch out for in the future, since a developer could (and I'm pretty sure at least once has) caused a conflict in this way.

**Comment by MrStonedOne** [comment]
> I agree with most of what was said but I think the better option for holopads would be to remove .h entirely and, like any other crewmember, just let them speak through it by talking normally.

THEN HOW DOES THE AI TALK TO PEOPLE IN ITS CORE WHILE IN A HOLOPAD? HOW DO THEY USE THEIR INTERCOMS WHILE IN A HOLOPAD?

**Comment by MrStonedOne** [comment]
ALSO

HOLOPADS START WITH THE LETTER H

ITS BETTER UX TO JUST LET THEM USE THAT THEN TRY TO ENFORCE SOME SILLY ABSOLUTIST NO CONFLICT RULE VIA UNIT TESTS.

**Comment by JohnFulpWillard** [comment]
> THEN HOW DOES THE AI TALK TO PEOPLE IN ITS CORE WHILE IN A HOLOPAD? HOW DO THEY USE THEIR INTERCOMS WHILE IN A 

The AI can disconnect like anyone else

It makes more sense that the AI wouldn’t talk through their core while projecting themselves elsewhere, and it’s not that big a deal honestly.

**Comment by optimumtact** [comment]
are you upset with the idea of testing it at all so people are aware of it? or that there's no easy way to allow conflicts to be valid in the context of the test?

**Comment by necromanceranne** [comment]
> > THEN HOW DOES THE AI TALK TO PEOPLE IN ITS CORE WHILE IN A HOLOPAD? HOW DO THEY USE THEIR INTERCOMS WHILE IN A
> 
> The AI can disconnect like anyone else
> 
> It makes more sense that the AI wouldn’t talk through their core while projecting themselves elsewhere, and it’s not that big a deal honestly.

They don't stop hearing people. Also, I believe anyone near them can still hear what they say as a hologram, just not what is on the other side of the call. If the AI wants to response they can just do so.

**Comment by MrStonedOne** [comment]
> are you upset with the idea of testing it at all so people are aware of it? or that there's no easy way to allow conflicts to be valid in the context of the test?

Both.

Conflicts should be allowed. and I'm mad the unit test was an excuse to dumb down the saymode shorthands instead of reworking the saymode system. I have a solution, but i'm withholding it until this revert pr is merged.

We are running out of alphabet to use here, allowing them to conflict in code in situations where they would not conflict in practice is the correct thing to do in that situation.

Also saymode hotkeys that do different things in different contexts is **good** UX. seeing that described as bad UX was super triggering.

***

>I'd argue it's bad UX to say "h is radio shorthand, unless you're a specific role using a niche feature, then it's holopad speak"

Everything about this sentence was bad logic.

"niche"? in other words "i want to paper over the [longtail](https://en.wikipedia.org/wiki/Long_tail) because human individualism is inconvenient to my unit test so i can just use the 'niche' weasel word to make it go away." why don't we remove every role except security and assistant. its bad ux to say left click attacks a person unless you're a niche role that doesn't based their shift on combat.

Convenience meaning the same button does two different things depending on what makes the most sense for the context is bad ux? 

Sorry, alt click has to go. it's bad ux to say it does x unless y

Sorry, the airlock ai/borg control panel has to go, it's bad ux to say clicking on a door means it opens unless you're a specific role using a niche feature.

***

So the 3rd reason i'm mad was the use of the `niche` word to justify papering over the [longtail](https://en.wikipedia.org/wiki/Long_tail) that is ais using holograms?????

Also there seemed to be no consideration for how players have to actually use these interfaces:

**It was expected the player would memorize all shortcodes, when no player does this.**

They guess based on logic (s for **s**ecurity, or c for **c**ommand) and only bother to memorize the exceptions to this (u for s**u**pply, n for science, v for service). All the og pr did was add a new item to this exception list that players have to memorize while claiming this ux improving feature of most shorthands being guessable was somehow a ux harming feature. This means it made the game worse, not better.

tbh, having dsay, and asay being saymode shorthands mean that those letters are locked off from all other roles is a net downgrade, more and more and more reason why they SHOULD be allowed to conflict.

**Comment by necromanceranne** [comment]
> Conflicts should be allowed. and I'm mad the unit test was an excuse to dumb down the saymode shorthands instead of reworking the saymode system. I have a solution, but i'm withholding it until this revert pr is merged.

More than just our repo stands to gain from any improvements you could make to saycode. Why not pr both at the same time so maintainers are confident in the fidelity of this alternative solution?

**Comment by zxaber** [comment]
> > THEN HOW DOES THE AI TALK TO PEOPLE IN ITS CORE WHILE IN A HOLOPAD? HOW DO THEY USE THEIR INTERCOMS WHILE IN A
> 
> The AI can disconnect like anyone else
> 
> It makes more sense that the AI wouldn’t talk through their core while projecting themselves elsewhere, and it’s not that big a deal honestly.

I have held three separate conversations simultaneously (near core, over binary, and through a holopad). Don't take this from me.

**Pull request merged**
