### PR TITLE
Tactical Energy Gun Unique Sprites

### PR DESCRIPTION
**Pull request by Steelpoint**
This PR gives the Tec Eguns that the ERT Security Officers use a unique sprite, as discussed during that PR here: https://github.com/tgstation/tgstation/pull/27387

These sprites are based off of the old gunsmithing sprites that Ausops made.

tacegun

:cl: Steelpoint
add: ERT Sec Tactical Energy Guns now have a unique sprite.
/:cl:

### CODE REVIEW

**Comment by kevinz000** [comment]
yay

**Comment by kevinz000** [comment]
now that they look like assault rifles
i have even more of ar eason to spray them around fnr to be cool and robust!

**Comment by Bawhoppen** [comment]
eguns are pistols

**Comment by YakumoChen** [comment]
eguns are too long to be pistols, they look more like carbines.

**Comment by Steelpoint** [comment]
I would assume most energy weapons are carbine sized.

**Comment by GunHog** [comment]
They look so rugged! :+1:

**Comment by Armhulen** [comment]
No NO I LIKED THE EGUN

**Comment by Tacolizard** [comment]
cool idea, but the sprites are a little weird.

**Comment by Iamgoofball** [comment]
These are for erts you fuckwit autists

**Comment by Armhulen** [comment]
I know they are

**Comment by Steelpoint** [comment]
They only replace the Security Officers Energy Gun, the rest of the ERT get standard Eguns.

**Comment by Iamgoofball** [comment]
>ERT Sec

**Comment by Bawhoppen** [comment]
eguns and lasers aren't carbines or rifles, they are literally supposed to be blaster pistols 

mediumlaserpistol

**Comment by Steelpoint** [comment]
Honestly it's just all head canon. This literally only affects one admin only role anyway, this is not replacing all egun sprites.

**Comment by InsaneHyena** [comment]
Cease and fucking desist with your tactictool fetish.

**Comment by Iamgoofball** [comment]
@InsaneHyena they are literally supposed to be tacticool motherfuckers

**Pull request merged**
