### PR TITLE
Remake: Gravity guns

### PR DESCRIPTION
**Pull request by silicons**
For the love of all that is holy please do not merge conflict
Take 3.
 Rework of #17303 
Gravity guns
A gun that manipulates gravity. Has a default radius of 5 tiles
Two modes: Attract and repulse. Will throw items at whereever it hits on attract and fling items away on repulse.
Affects anything not anchored to the floor. 
No energy cost.
5 second delay between fire
Mildly expensive R&D item.
:cl:
rscadd: Gravity Guns! It is a mildly expensive R&D gun that has a 5 second cooldown between shots, but doesn't need to be recharged. It has two modes, attract and repulse. For all your gravity-manipulation needs!
/:cl:

### CODE REVIEW

**Comment by kevinz000** [comment]
>It conflicts

**Comment by Jordie0608** [comment]
This is why you shouldn't use Git for Windows

**Comment by kevinz000** [comment]
Whew.

**Comment by optimumtact** [comment]
There goes kehki, buffing science

**Pull request merged**
