### PR TITLE
Allow horizontal mobs to fit into crates

### LINKED ISSUE #15352: Open crates don't block movement
While the crate is closed, it blocks the path normally(you bump into them), but if they are open you just go throught them

### PR DESCRIPTION
**Pull request by neersighted**
Also make stuffing into crates/lockers a mild stun akin to tabling (needed to make you horizontal to fit into a crate).

Closes #15352 as intended behavior

Adds spacecat to fix an earlier revert
Sprites by @Cheridan

:cl:
add: Horizontal (lying) mobs now fit into crates
add: Mobs may now be stuffed into crates, as with lockers
add: Stuffing into a locker deals a mild stun (the same as tabling)
/:cl:

### CODE REVIEW

**Comment by GunHog** [comment]
Mekhi....goes in the crate?

**Comment by PKPenguin321** [comment]
Lockers are now portable tables that don't require a grab. AFAIK dragging someone to a locker wouldn't interrupt stripping, handcuffing, chokeholding, etc. so this is basically better than old tabling

**Comment by neersighted** [comment]
Those things use do_after so they will be interrupted. Also, tabling doesn't require a grab anymore (or at least it shouldn't after Kor removes grabs from tables). It takes 4 seconds to put someone in a locker. The time/delay is the same as before, I only added the weaken so you can stuff mobs into crates and cleaned up the code.

**Comment by bgobandit** [comment]
my dream of shipping the clown to security is now easier

**Comment by neersighted** [comment]
Also here's the spacecat

Spacecat

**Comment by tkdrg** [comment]
Does this mean I can abuse crates to go through plastic flaps

**Comment by neersighted** [comment]
Sure I guess

**Comment by phil235** [comment]
Make sure this doesn't cause issues when mulebots are loaded with a crate containing a mob.

**Comment by Fox-McCloud** [comment]
:-1: 

You can use this to abuse going through plastic flaps plus, as already mentioned, this is a portable table.

**Comment by KorPhaeron** [comment]
Plastic flaps were a mistake

**Comment by swankcookie** [comment]
plastic flaps really do make absolutely 0 fucking sense.

**Comment by neersighted** [comment]
Like I keep on saying, its `do_after` for 4 seconds! 4 seconds of not switching hands, moving, or clicking anything...

**Comment by Fox-McCloud** [comment]
@neersighted 

Yes, for a 4 seconds stun--pretty easy to keep someone stunlocked by just spam dragging them to the locker.

**Comment by MMMiracles** [comment]
Remove the stun and its perfect. I want to send the clown into security via a weapons/implant crate, they'll never see it coming.

**Comment by neersighted** [comment]
@Fox-McCloud It's not a 4 second stun, its a two second stun! `Weaken(2)`. It takes 4 seconds of `do_after` to drag someone and apply the stun.

**Comment by Fox-McCloud** [comment]
@neersighted 

Nah, that's a ~4 seconds stun; a stun keeps you locked down for 1 cycle; the mob process fires every 2 seconds, ergo, 2 cycles = 4 seconds.

Granted, it can be a bit *less* than this, depending on how far into the loop you get stunned (meaning you could hypothetically be stunned for 3 or even 5 seconds), but on the whole, you'll be stunned for ~4 seconds.

**Comment by neersighted** [comment]
My point still stands about how it gives very obvious messages and it requires 4 seconds of not moving or changing hands etc to stun someone. Also it shoves them in the locker and closes it, you need to re-open it and attack them.

**Comment by Chocobro** [comment]
>stunning someone then locking them in a crate for hours
erp sensors are increasing

**Pull request merged**
