### PR TITLE
Adds z5 (asteroid) to travis checks

### PR DESCRIPTION
**Pull request by Cyberboss**
Are we maintaining this or what?

### CODE REVIEW

**Comment by KorPhaeron** [comment]
We're not

**Comment by Cyberboss** [comment]
Will close if this fails

**Comment by Cyberboss** [comment]
Since it works, might as well do it

**Comment by lzimann** [comment]
Even if we don't use it, we still have support to it so 👍

**Comment by KorPhaeron** [comment]
Pretty much all the major servers outside of /vg/ use lavaland or are porting lavaland now we don't actually have to support asteroid anymore

**Comment by lzimann** [comment]
Then someone needs to pull the trigger on it completly(probably a better idea than leaving something that might not even be working properly)

**Comment by optimumtact** [comment]
Yeah just remove it

**Pull request closed without merging**
