### PR TITLE
adds some placeholder and not sprites for various fish sources

### PR DESCRIPTION
**Pull request by carlarctg**
## About The Pull Request

adds some placeholderish sprites for various fish sources

- plasma river: lava texture but it's the first frame slowly looping horizontally 
- tray: literally just a little bit of a tray sprite
- rift: literally just the rift but horizontal. i think that's funny
- fry: lava texture but yellow and doesn't glow as much

added debug portal with all fish locations

## Why It's Good For The Game

i dont like fishing in blue deep fryers

## Changelog

:cl:
image: adds some placeholder and not sprites for various fish sources
code: added debug portal with all fish locations
/:cl:

### CODE REVIEW

**Comment by Ghommie** [comment]
Ngl, for a moment I thought you were talking about the radial icons, and I felt a little sad, but yeah, thank you for adding overlay states to these sources. I felt a little dried out after I sprited the icons for the radial menus that I didn't bother about the overlays.

**Comment by Ghommie** [comment]
Anyway, can I get a screenshot of how the fish-porter looks with the carp portal overlay? The rest is absolutely fine, I just have to see this one.

**Comment by carlarctg** [comment]
image
 
@Ghommie @Wallemations

**Review by Ghommie — APPROVED** [review]
The portal is a bit goofy, but that's ok.

**Pull request merged**
