### PR TITLE
New Sneaker Sprites by Any%!

### PR DESCRIPTION
**Pull request by Imaginos16**
## About The Pull Request
https://www.youtube.com/watch?v=aM8YOBvq-jc

OH YEAH BABY, TRIPLE PR IN A DAY!

This PR adds new and improved sneaker sprites made by the talented @zestybastard (aka Any%) of Shiptest!
image

This PR ALSO adds a resprite of the magboots by @TripleZeta (thank you)
image

## Why It's Good For The Game
 It was a pretty low bar and man, I'm much happier seeing these sneakers than the shit we had before.

## Changelog

:cl: Any%, TetraZeta, PositiveEntropy
imageadd: Resprites all magboots!
imageadd: Resprites Sneakers!
/:cl:

### CODE REVIEW

**Comment by Fikou** [comment]
the mob sprites for the magboots are wider than normal shoes and it makes them look off, could you look into changing that?

**Comment by Imaginos16** [comment]
> the mob sprites for the magboots are wider than normal shoes and it makes them look off, could you look into changing that?

I could see about making them a pixel less wider.

**Comment by Imaginos16** [comment]
Ended up giving some minor retouches to the magboots, screenshot was edited accordingly to reflect these minor changes. @Fikou this one's for you bro.

**Comment by bluetshirtguy** [comment]
they look so baggy! eugh.

**Comment by DrDiasyl** [comment]
Real drip just dropped.

**Comment by Dorsisdwarf** [comment]
Really nice sprites.

**Comment by Twaticus** [comment]
just double checkin that cowboy/bling/shadowling shoes are removed for being unnused

**Comment by GoldenAlpharex** [comment]
I really like the new look of the magboots!
The shape of the new sneakers is nice, although I feel like the shading is a bit too light? Like, it's a bit hard to see it for darker colors (black and purple in your screenshot).

**Comment by Imaginos16** [comment]
> just double checkin that cowboy/bling/shadowling shoes are removed for being unnused

forgot to respond, they are.

**Pull request merged**
