### PR TITLE
Beaker sprite tweaks and additions v2

### PR DESCRIPTION
**Pull request by Twaticus**
## About The Pull Request

Adds opacity to bottles, beakers, large beakers, and reagent fills so theyre no longer extremely dark. Adds @maxymax13 's resprites of the x-large(plastic) and metamaterial(gold) beakers to match the new beakers. Adds a 1u sprite for reagent fills of all bottles/beakers. Removes unnused vials and melted beaker icons.

dreamseeker_25WnFmKFNQ
Bottle, Beaker, Large Beaker, X-Large Beaker, Metamaterial Beaker

## Why It's Good For The Game

Consistent beakers good.

## Changelog
:cl: Twaticus, maxymax13
imageadd: Resprites x-large & metamaterial beaker. Normal beaker & reagent color sprite tweaks. Adds 1u reagent sprites back to beakers.
/:cl:

### CODE REVIEW

**Comment by maxymax13** [comment]
image

**Comment by maxymax13** [comment]
why are you removing the sexy vial sprites yet keeping the 500 million definitively unused recolored filled bottle sprite garbage in chemical.dmi noooooooooo

**Comment by FernandoJ8** [comment]
Beautiful.

**Comment by MrMelbert** [comment]
fixes #58624

**Comment by UnokiAs** [comment]
God work 👍

**Comment by cacogen** [comment]
now redraw the rest of the game in this fuzzy painterly style

**Comment by maxymax13** [comment]
> now redraw the rest of the game in this fuzzy painterly style
just because you can't find your prescription glasses doesn't mean the game is fuzzy and painterly, your eyesight is

**Comment by cacogen** [comment]
That's what your sprites look like

**Comment by maxymax13** [comment]
> That's what your sprites look like

count the useless shades of grey in the floor tile sprite and come back to me

**Comment by cacogen** [comment]
You could've made the beakers 3/4 while keeping them consistent with the art style the majority of sprites still have. If that art style is boring and outdated then whoever's in charge could decide on a new one for spriters to aim for. At the moment, a lot of the new sprites are worse and not even consistent with each other. It's change for its own sake. It's a sign of a lack of regard for quality and it's disappointing to see it happen to this game.

**Comment by maxymax13** [comment]
> 
> 
> You could've made the beakers 3/4 while keeping them consistent with the art style the majority of sprites still have. If that art style is boring and outdated then whoever's in charge could decide on a new one for spriters to aim for. At the moment, a lot of the new sprites are worse and not even consistent with each other. It's change for its own sake. It's a sign of a lack of regard for quality and it's disappointing to see it happen to this game.

ok buddy good for you

**Comment by cacogen** [comment]
I thought I should explain my point of view on the issue so you understand where I'm coming from but it doesn't matter

**Comment by FernandoJ8** [comment]
> 
> 
> You could've made the beakers 3/4 while keeping them consistent with the art style the majority of sprites still have. If that art style is boring and outdated then whoever's in charge could decide on a new one for spriters to aim for. At the moment, a lot of the new sprites are worse and not even consistent with each other. It's change for its own sake. It's a sign of a lack of regard for quality and it's disappointing to see it happen to this game.

https://i.imgur.com/0zNqozd.png

WHERE'S THE SOUL??11!?

**Comment by LemonInTheDark** [comment]
> 
> 
> You could've made the beakers 3/4 while keeping them consistent with the art style the majority of sprites still have. If that art style is boring and outdated then whoever's in charge could decide on a new one for spriters to aim for. At the moment, a lot of the new sprites are worse and not even consistent with each other. It's change for its own sake. It's a sign of a lack of regard for quality and it's disappointing to see it happen to this game.

Twat's the one in charge. We go by their opinions, and over time we'll develop a consistent art style based on what they like. that's the goal here

**Comment by cacogen** [comment]
I haven't seen any evidence of a plan in the works to hold spriters to a specific, new style. That's a suggestion I made then as a way of satisfying the apparent desire for new sprites while doing away with the current random approach. 

So far there have only been unneeded changes often with worse sprites that aren't even consistent with each other. What you're saying just sounds like "if Twaticus likes it it goes in and the more it happens the more it will develop into its own mismatched style which I don't care about". 

It's not even clear why the sprites are being changed to begin with. The changes are never justified outside of "new = good". Which would be true if they didn't look worse and/or not fit with the things around them. It's never the sprites that actually need updating, like stuff that's a holdover from OpenSS13. It's always the same common, front and centre sprites so whoever is making the PR can have an immediately visible effect on the game with little effort. I never make this complaint when somebody is adding sprites like in-hands or suit storage icons, because that's always an improvement.

The soul argument is braindead and a meme by popularised by losers pining for a time when they weren't irrelevant. It amounts to "shit = good, because I was young then". We could have a consistent art style with good, modern sprites. I haven't gone to Goon for years but I remember being impressed by their new ones at the time. 

But this approach will always result in worse sprites, sprites that don't fit the game or each other and sprites that have become iconic being replaced with shit for no other reason than somebody wanted to and enough people pressed the thumb up button. 

I'm aware I'm wasting my time here but this is undeniable.

**Pull request merged**
