### PR TITLE
Dockerize the station

### PR DESCRIPTION
**Pull request by chris-hill1990**
This pr is still in progress but i wanted to share what i was working on and get some feedback early as this will be my first time committing something to the main repo

[Changelogs]: # (Your PR should contain a detailed changelog of notable changes, titled and categorized appropriately. This includes, new features, sprites, sounds, balance changes, admin tools, map edits, removals, big refactors, config changes, hosting changes and important fixes. An example changelog has been provided below for you to edit. If you need additional help, read https://github.com/tgstation/tgstation/wiki/Changelogs)

:cl: 
server: Dockerize the station allowing new servers to run on docker infrastructure and admins that are less experienced to spin  a server up faster
/:cl:

[why]: # (Please add a short description [two lines down] of why you think these changes would benefit the game. If you can't justify it in words, it might not be worth adding.)

I have often run in to issues where i moving hosting providers or just want to spin a quick server for me and my friends up but that requires cloning the repo remembering how to get the host ready for byond which version the game needs and all of the things that go along with getting a server up and running so to make it faster and easier on my self i built a dockerfile to do all the heavy work for me.

### CODE REVIEW

**Comment by optimumtact** [comment]
I think we have one already somewhere @Cyberboss

**Comment by Cyberboss** [comment]
Yeah it's literally in /Dockerfile

**Comment by chris-hill1990** [comment]
> I think we have one already somewhere @Cyberboss

I am sorry i dident see the .docker folder i normally associate with docker

**Comment by optimumtact** [comment]
also check out https://github.com/tgstation/tgstation-server

Thanks for the PR anyway

**Pull request closed without merging**
