### PR TITLE
Removes the undefined sprite in melee_lefthand.dmi leftover from the cricket bat

### PR DESCRIPTION
**Pull request by Wallemations**
## About The Pull Request

Removes the undefined sprite I accidentally left in melee_lefthand.dmi

## Why It's Good For The Game

Makes it so other people who put things in melee_lefthand.dmi don't convulse in disgust at the sight of an undefined sprite.

### CODE REVIEW

**Review by Twaticus — APPROVED** [review]
yeah sorry about that i missed it in the first review

**Comment by Rohesie** [comment]
Removed the changelog as it is not necessary for such a simple change.

**Comment by Wallemations** [comment]
yea sorry about leaving that in there, I didn't realize it

**Comment by Rohesie** [comment]
Thanks a lot for the fix! :)

**Pull request merged**
