### PR TITLE
Prevents the captain's sabre from rustling jimmies

### PR DESCRIPTION
**Pull request by Tacolizard**

### CODE REVIEW

**Comment by ma44** [comment]
Rustle jimmies?

**Comment by Tacolizard** [comment]
yes

**Comment by DoctoreMad** [comment]
?
?
**???**

**Comment by Armhulen** [comment]
????????????????????????????????????????????????????????????????????????????????

**Comment by GunHog** [comment]
I...do not understand...I was expecting a Goof meme PR hiding a nerf. I do not even know what this does.

**Comment by ShizCalev** [comment]
needs a sheathing sound instead

**Comment by Cyberboss** [comment]
Why? This should only apply to backpacks?

**Comment by Tacolizard** [comment]
i added a sheathing sound but forgot to set this var to remove rustling sounds.

**Comment by Xhuis** [comment]
The fact that the variable name is `rustle_jimmies` is the best thing in the codebase.

**Review by Cyberboss — CHANGES_REQUESTED** [review]
Refactor and make the storage the storage entry sound modifiable so that it can just be changed at the object level

**Comment by Tacolizard** [comment]
why? that doesn't make sense. backpacks rustle because they're made of cloth, not because the things you put inside rustles.

**Comment by GunHog** [comment]
The saber only fits in the saber sheath and a BoH.

**Comment by ShizCalev** [comment]
@Tacolizard So you can make metal things (like swords) rustle with a metallic sound and soft things make a thudding (normal) rustle sound, I'd assume

**Comment by WJohn** [comment]
wait this is an actual variable?

**Comment by GunHog** [comment]
It certainly is, WJ!!

**Comment by Armhulen** [comment]
i genuinely thought this was a meme pr

**Comment by lzimann** [comment]
Change the variable name while you are at it. Vars with a shit name are awful and should be purged.

**Comment by Tacolizard** [comment]
closing because people hate fun

**Comment by GunHog** [comment]
Who hates fun? You were told to refactor it, not close it!

**Comment by PKPenguin321** [comment]
This was actually a good and valid change, a refactor could come later

**Comment by Tacolizard** [comment]
but i don't feel like refactoring it, and until you accept my privelige not too, i will forever let you wallow in this unfixed bug.

**Comment by Tacolizard** [comment]
@GunHog specifically, LeoZ hates fun

**Comment by optimumtact** [comment]
Why on earth are you demanding he refactor an entire system to fix a bug

**Pull request merged**
