### PR TITLE
Increases the slice time of walls from 10 to 20 seconds

### PR DESCRIPTION
**Pull request by actioninja**
## About The Pull Request

Walls now take 20 seconds to slice open instead of 10

## Why It's Good For The Game

Walls are a bit too easy to get through with basic tools. This isn't a crippling change but one that will make you think twice about trying to cut open walls in public areas.

## Changelog
:cl:
balance: Walls take 20 seconds to cut with a welder instead of 10
/:cl:

### CODE REVIEW

**Comment by Timonkeyn** [comment]
"cult has time to leave or prepare a spell" vs "wait what is that sound? Oh a crewmember breakin into my base"

**Comment by Ratvar** [comment]
"and not many jobs have legitimate access to RCDs" - well, maybe not every job should be able to do engineering's job just as good without any preparation

**Comment by CPTANT** [comment]
Trespassing and burglary are part of the game, a part that is actively being removed by all these changes to walls, windows, jackhammers, thermite etc.

**Comment by CPTANT** [comment]
Also actually important areas already have reinforced walls.

**Comment by actioninja** [comment]
Thinking more about it this is a bit of a reaction to something that's not happening yet.

**Pull request closed without merging**
