### PR TITLE
Splits up the plane masters file to be easier to browse and reference

### PR DESCRIPTION
**Pull request by ninjanomnom**
The title says it all, there is nothing else. Feel free to bikeshed about code organization here.

### CODE REVIEW

**Review by LemonInTheDark — CHANGES_REQUESTED** [review]
I'm fine with pulling the template off into its own file, at least in theory (it is a bit worse since it pulls away the default target value, we should maybe remove that it masks things hard) but I'm not a big fan of the rest of this. 

Might just be cause I wrote it but most of the associations here are sorta vauge, and keeping the planes in different files like this prevents searching in file for plane values to look them up quickly. Also it makes groupings more concrete and inflexible, and requires groupings in some cases where it doesn't really make sense.

Also also the PMs were organized in the same manner as the _layers.dm defines, by value (and thus draw order), and this kinda kills that which is a shame.

**Comment by ninjanomnom** [comment]
It's mostly the split of the base type from the all the implementations I care about. I wouldn't be too against putting all of them in one file, but speaking as someone less familiar with all the plane masters around, it was annoying to look through them all for one or the other, especially with a couple of them having large blocks of logic.

Personally my workflow with code is I have multiple editor windows open: one primary for files I'm modifying, one secondary for reference code that I won't be making changes in, and either a third window for if I need to reference multiple things at once or more usually the byond docs or browser. When I was working a little bit with a new plane master to add a special effect I could easily enough reference render order with the defines file, but the massive single file for plane masters made it difficult to also reference the base type procs and an example implementer separately from the new type I was adding. I have no clue how similar this is to other people though so if that's not how most people work then my changes here may not make sense.

**Review by Ghommie — APPROVED** [review]
Regardless, it's an _overall_ improvement which could make searching through the planes code somewhat easier in my uncultured opinion, even though Lemon's point is legit, it could mean less unrelated stuff to scroll through.

**Comment by LemonInTheDark** [comment]
shoulda closed, in tears rn

**Comment by ninjanomnom** [comment]
Shit I should have made this draft because I wanted to discuss this at leisure with you, want me to put all the plane master subtypes in one file?

**Comment by LemonInTheDark** [comment]
yes I would like that

**Pull request merged**
