### PR TITLE
Universal Mulligans [DNM {yet}]

### PR DESCRIPTION
**Pull request by Incoming5643**
*All modes can now use the midround antag (mulligan) system to switch into each other

*All modes can now be individually set to either end on antag death or continue on until the shuttle is called

*All modes can now choose to use or not use the midround antag system

*The midround antag system now has its own list of configurable probabilities, separate from the traditional probabilities

*The midround antagonist system is now capable of firing multiple times in one round if all the replacement antagonists are ALSO neutralized (note: because of how the system works, this will almost never happen without badmining)

*These round options have been moved into their own config file, mode_options.txt

 *Adds an integrity check to mulligan antag, it has lower priority than the life and time check. Due to how integrity works, this should prevent mulligans in instances of widespread fires, loose singularities, and excessive bombing

*The check antagonist panel has been updated to show what the current settings for continuous rounds and midround antag are, and toggle them from their default config state for the round if desired.

Still to do:
- [ ] Testing Testing Testing
- [ ] code beautification
- [ ] requests

### CODE REVIEW

**Comment by Incoming5643** [comment]
Important note: This isn't me saying all mode SHOULD switch into each other. It's just a configurable option now.

**Comment by Jalleo** [comment]
Mulligan new tensioner?

**Comment by Incoming5643** [comment]
"it's not the end of the world, but you can see it from here"

**Comment by Marflowerose** [comment]
Could there also be a config to check station integrity before making more antags? Getting wizards and blobs when singulo has eaten most of the station is a bit silly.

**Comment by ACCount12** [comment]
Station already has enought chaos, there is no need to add more. This is why tensioner was removed. 

At least make this system toggleable in config, with default to "off".

**Comment by Incoming5643** [comment]
It's not the tensioner, it doesn't throw anything unless the entire previous threat has been mitigated utterly. All dead for most antags, all destroyed for lings. How many rounds have you seen where every single traitor was killed? We're nearing half a dozen checks to avoid the system as well.

The system is config toggled out the ass: Every single mode has four, count em, four config options in how it functions:

1. "continuous" allows you to dictate what rounds end with the deaths of the antags. Any round that does this is automatically out of the running for midround antag entirely

2. "midround_antag" is what actually allows you which round types use the system. You can use as many or as few as you want, including none of them.

3."midround_failure" allows you to set what happens in rounds where midround antagonist runs but runs up again one of the aforementioned checks. You can either have the round end immediately (as wizard/blob/malf/raginmages) or continue onward with no further action (every other round type). The settings for this toggle perfectly match what already happens on round end by default

4."midround_probabilities" allows you to set what the rounds actually reroll to. Hate chaos? Set it up to only go to traitor, ling, or extended. Love chaos? Set every round to go to Nuke, Wizard, or Blob. It's UTTERLY up to you!

So no it's not going to default to off, I've coded plenty of things that defaulted to off and no one ever turns them on. I want people to try this.

**Comment by ACCount12** [comment]
Try this, then turn it off. Forever.

Mixed game modes is not just chaos, it's *wrong sort of chaos*. You just dealt with traitor threat, but then you get wizard then changelings ohmygod calltheshuttle. Events system on /tg/ codebase already makes long rounds nearly impossible, and your tensioner is making them impossible at all.

**Comment by Incoming5643** [comment]
It's <u>not</u> the tensioner.

The tensioner threw antags on top of antags according to the round length. It often lead to insane amounts of chaos because the system had no way of knowing how crazy or calm the round was, it fired blindly.

Mulligan Antag only occurs if the old threat is removed from the station utterly. Modes do not "mix" so much as transition from one to another. In most rounds mulligan antag will never runs at all, and this is entirely by design. I will now break it down by round type to convince you that this is the case.

Traitor:
Mulligan only occurs in traitor if every single traitor is dead at the same time. If any complete their objectives and decide to lay low the rest of the round, mulligan won't occur. If any get arrested and brigged, mulligan won't occur.

Ling
Mulligan only occurs in ling if every single ling's body is destroyed. If any complete their objectives and decide to lay low the rest of the round, mulligan won't occur. If any are too timid to really be found out as a ling, mulligan won't occur.

Traitor/Ling: See above sections

Double agents: Mulligan only occurs in double agents if every single agent is dead at the same time. DAs are outright encouraged to quiet down after killing their target, as they are themselves being hunted. It's near impossible for every single agent to kill each other at the same time, and at least one or two is apt to live for greentext. Mulligan will almost never fire in DA.

Nuke Ops: Mulligan only occurs in nuke if all five operatives are dead at the same time. This one is reasonable. Nuke ops has a fair chance to mulligan, but a LOT of recent changes to nuke op has been on the front of removing crew access to their round specific toys, even after the ops are dead.

Rev: Mulligan only occurs in revolution if the entire losing side is wiped out. If the heads win every rev needs to die or be deconverted. If the Revs win every remaining loyalty implanted crew member needs to be deimplanted or killed (note, killing a implanted person will let you have them in the round sans implant). This will almost never ever happen, it would need to be an absolute stomp.

Gang: Mulligan only occurs in revolution if the entire losing side is wiped out. This works much the same as in revolution, and will almost never occur.

Cult: Mulligan only occurs in cult if the entire cult is killed or deconverted. This is unlikely, while some of the cult is apt to be caught if they are bad, between the starting group there is almost always one or two members who will go deeply covert and never be caught even if the cult is ultimately unsuccessful.

Wizard: Mulligan only occurs in wizard if the wizard, any apprentices, and any other exotic wizard based antags are all dead. Depending on a wizard's build this can happen quite a lot. People complained about 10 minute wizard rounds often, and it was rounds like that that were largely the impetus for mulligan antag in the first place.

Ragin Mages: See Wizard

Malfunction: Mulligan occurs in Malf if the AI dies. This will happen a lot, but moreso than other modes malf mulligans are apt to fail the many checks set in place for this system. Any malf worth its salt will have killed enough people/destroyed enough of the station by the time it was killed. It will usually only permit mulligans for the real fluke AIs

Blob: Mulligan occurs in blob if all blob cores are destroyed. This will happen occasionally, but like malf blobs tend to destroy a lot of station and kill a lot of people. It will often fail to mulligan unless it was caught at an extremely early phase or was really ineffective as a blob.

Monkey: Mulligan only occurs in monkey if every single infected monkey dies. The body counts in monkey rounds tells me that a mulligan monkey round will be a thing of near mythical levels. Also it's <i>monkey mode</i>.

**Comment by ACCount12** [comment]
So it is actually turned off permanently? Nice.

**Comment by Incoming5643** [comment]
I'm saying the system is designed in pretty much every possible way to err on the side of "maybe things are interesting enough". 

It will fire,  but I doubt even 10% of rounds will actually mulligan even if it was left on for every single roundtype, and a lot of those that do will only transition into something equally as manageable. Default probabilities (which can be changed) only have a mulligan'd mode transition into something that's not some combination of traitors and/or lings 35% of the time. By my estimate we're talking maybe two or three rounds a week that may get "a little crazy" because of mulligans.

Just take my word for it I've done everything I can to make this not the tensioner 2.0. I DO have plans for a tensioner mode, but this isn't that. That'd be a "ridiculously low chance to occur or admin only" type thing.

**Comment by Jalleo** [comment]
This is why its called mulligan I just needed to point it out so anyone else who says it now can read this. Thank you for explaing your plans in great detail Incoming. Good luck with the rest of the mulligan as long as it develops well it can be a great addition long term.

**Comment by Incoming5643** [comment]
For people finding it a little hard to grasp here's a look at the front end admins will see in round.

On the check antagonist panel during a round under the heading "Continuous Round Status" one of the following self explanatory phrases will be seen:

"End on antagonist death" : Continuous is off, nothing else matters
"Continue if antagonists die, not creating new antagonists": Continuous is on, but midround_antag is off.
"Continue if antagonists die, creating replacement antagonists, continuing if it cant" Continuous and midround_antag are on, but midround_failure is off.
"Continue if antagonists die, creating replacement antagonists, ending the round if it cant": All three toggles are on.

Clicking any part seperated from a comma will switch the toggle for that part, so clicking "continue if antagonists die" will always change the entire statement to read "End on antagonist death" but clicking on "ending the round if it can't" will only change THAT part to read "continuing if it cant".

Note that if a round is in "Continue if antagonists die, not creating new antagonists" and the antagonist is already dead, toggling to "creating replacement antagonists" will start the process of adding the antags right there.

**Comment by Incoming5643** [comment]
initial bug checking pass reveals: Lots of shit to fix before this is ready

**Comment by Incoming5643** [comment]
This isn't dead, but like a lot of my bigger projects it's ended up getting "chunked out" into smaller, easier to digest pieces (some have already been merged in fact). That and I just don't feel like refixing mulligans when I just finally got the system working right. Expect bits and bobs of this over the coming weeks.

**Pull request closed without merging**
