### PR TITLE
Adds a new option for admins, a way to toggle immersive movement.

### PR DESCRIPTION
**Pull request by GuppyLaxx**
Admins can now trigger an immersive way of movement for all living beings.

Why : Naksu wanted this.

### CODE REVIEW

**Comment by GuppyLaxx** [comment]
discord_2018-06-29_23-59-36
i love my life

**Comment by cacogen** [comment]
https://www.youtube.com/watch?v=iRZ2Sh5-XuM

**Comment by Bawhoppen** [comment]
Southpark Station 13

**Comment by vuonojenmustaturska** [comment]
Thank you, this is great

**Comment by ninjanomnom** [comment]
Make this automatically enabled on april fools

**Comment by Iamgoofball** [comment]
Now we just have to revive cheridans speech

**Comment by optimumtact** [comment]
not worth it

**Comment by PKPenguin321** [comment]
This is incredible

**Comment by rustledjimm** [comment]
this is amazing.

**Comment by Stickymayhem** [comment]
AND ITS ALREADY DEAD FOLKS

**Comment by DrChef** [comment]
I tried it today and I don't know how I feel about it. It isn't bad, but I'm not used to having a pseudo walk animation.

**Comment by Anonmare** [comment]
I'm going down to space park, going to have myself a time
Friendly faces everywhere, cremembers without validhunting temptation

**Comment by Jared-Fogle** [comment]
on second look at this why did you add another /Move when there's already a /Move on L449?

**Pull request closed without merging**
