### PR TITLE
(april fools) all humans+nonhumans are augmented with experimental reagent generating augments (unremovable)

### PR DESCRIPTION
**Pull request by mc-oofert**
## About The Pull Request

all subtypes of humans are given a experimental reagent generating augment
this augment is not removable
it generates a random reagent at a random pace and at a random max volume

## Why It's Good For The Game

nanotrasen experiment or something idk

## Changelog
:cl:
add: everyone is forcefully augmented with unremovable experimental reagent generating augments
/:cl:

### CODE REVIEW

**Comment by LemonInTheDark** [comment]
udderly fucked

**Comment by Blacklist897** [comment]
PLEASE NO THINK OF THE RULE 8 BANS

**Comment by LemonInTheDark** [comment]
this is rule 8 banbait for sure

**Comment by NanoCats** [comment]
> Unknowingly spawn with saline reagent generator in my body

> Randomly explode at some point in the round (does that still even happen?)

**Comment by BoneSeer** [comment]
I for one approve of the rule 8 ban wave.

**Comment by EricZilla** [comment]
Imagine coding a nice lil feature for the wise cow only for it to be immediately used for this

**Comment by Admiral-Gigaton** [comment]
jimmy how dare you violate the game like this

**Pull request closed without merging**
