### PR TITLE
Adds nanite program rules, disables program installation from the chamber, allows cloud sync toggling

### PR DESCRIPTION
**Pull request by XDTM**
## About The Pull Request

Big changes in nanite town!

Major changes:
- Sensor nanites (most of them) can now be installed as internal rules to programs, using their current setting. Rules must be met for the program to stay active, but it won't affect triggering.
Example: using a brute damage sensor set to 10, you can make a regen program only stay active if the user has more than 10 brute damage
- Nanite chamber can no longer install/uninstall programs. It's an option that nobody uses and that requires me to mirror a lot of UI modifications on the cloud console to the chamber console on every change. It still functions as a scanner, though, which can see programs and codes if upgraded.
- Nanites can now have their cloud sync enabled or disabled. It can be set manually on a nanite chamber or modified through a newly added program (Cloud Sync). The cloud id remains unmodified, but until re-enabled nanites won't sync to their cloud.
- Added a cloud sync sensor, which can also be used as a rule.
- The viral program (the one that copies the programming onto other nanites) now disables cloud sync if it doesn't overwrite cloud ID, guaranteeing that no matter what the program changes are going to stay.

Capture

## Why It's Good For The Game

**Rules:** QOL feature for programs, since what required two extra sensor programs can now be tacked on to the single program, making it easier to make and making the whole list less cluttered.
**Nanite chamber:** doesn't really affect gameplay since nobody used the option afaik. Now that cloud sync is the only way to modify programs, it's mandatory to have such a weak point when using them. If you keep the sync disabled instead, you're vulnerable to corruption from emps and shocks.
**Cloud disabling:** as stated above, lets the user make a choice between being immune to corruption but vulnerable to sabotage, and being immune to sabotage but unable to receive modifications and vulnerable to environmental corruption.

## Changelog
:cl:
add: Sensor nanites (most of them) can now be installed as internal rules to programs, using their current setting. Rules must be met for the program to stay acti
ve, but it won't affect triggering.
del: The Nanite chamber can no longer install/uninstall programs. It can still view them.
add: Nanite cloud sync can now be disabled without affecting cloud ID.
add: Added two new nanite programs: Cloud Sync (allows modification of cloud sync status) and Cloud Sync Sensor (detects cloud sync status).
tweak: Viral nanites now disable cloud sync, if they don't modify Cloud ID, making them always effective.
/:cl:

### CODE REVIEW

**Comment by terranaut1** [comment]
I like all of this except for the cloud sync disabling. Powergaming yourself with nanites should leave you open to being fucked with without an easy way out that you can toggle at will with a voice command.
You can already sort of circumvent it through "emergent gameplay" but at least if you do it like all your work is lost if your nanites get corrupted and you need to start over from scratch.

**Comment by XDTM** [comment]
I'm not 100% satisfied with full control over disabling either, so i'm thinking of a potential downside or cost for doing so.

**Comment by Tlaltecuhtli** [comment]
lower the max programs for people without cloud?

**Comment by XDTM** [comment]
Having one or the other as fixed is fine, since the downside for no cloud is being vulnerable to corruption. The issue is with people who'll switch on the cloud only when they need to, getting the best of both worlds.

**Comment by optimumtact** [comment]
I think that pretty much all the nanites should require cloud activation to work because that's exactly how mega corps would work in the future.

Please create your amazon nano account to enable your amazon :tm: health services

**Comment by XDTM** [comment]
I'm with you on that, but i wanted to preserve the corruption aspect when they're affected by EMPs in some way, since permanent cloud would always keep them synced.

**Pull request closed without merging**
