### PR TITLE
Adds a tool to cut up an input dmi into a smoothing dmi

### PR DESCRIPTION
**Pull request by RemieRichards**
Requested by @Ausops

* Supports new (https://github.com/tgstation/tgstation/pull/22096) diagonals!
* Only partially supports Perspectives
* Provides an ExampleInput to show you what an input needs to look like
* Provides an ExampleDiagInput to show you what a diagonal input needs to look like
* Provides an Input version of Wall.dmi to assist with the above

Takes specifically created+named input states and cuts them up into the necessary, correctly named, smoothing states.

### CODE REVIEW

**Comment by Supermichael777** [comment]
SMOOTHED INDESTRUCTIBLE WALL? ITS MORE LIKELY THAN YOU THINK!

**Comment by xxalpha** [comment]
Mint stuff, china plate. :plate:

**Comment by RemieRichards** [comment]
## DIAGONALS

**Comment by Ausops** [comment]
just top downs left?

**Comment by xxalpha** [comment]
What?

**Comment by Ausops** [comment]
tables with a top down perspective, remie made a distinction between normal turfs, diagonals, and smooth structures like tables, I assume thats the last thing she's got to do

**Comment by xxalpha** [comment]
Ah I get it.

**Pull request merged**
