### PR TITLE
Fixes clowncar sucking up Armsy

### PR DESCRIPTION
**Pull request by AlinaStarkova**
## About The Pull Request
Prevents the Clown Car from sucking up Armsy

## Why It's Good For The Game
Because a clown car sucking up Armsy is pretty much the same issue with being able to suck up Megafauna.

## Changelog
:cl: Nari Harimoto
tweak: Clowncar can no longer suck up Armsy
/:cl:

### CODE REVIEW

**Comment by Qustinnus** [comment]
I personally think being able to bring station destroying megafauna is not comparable, and I don't think this change is necessary. But I don't really think it matters too much either way.

**Comment by AlinaStarkova** [comment]
> 
> 
> I personally think being able to bring station destroying megafauna is not comparable, and I don't think this change is necessary. But I don't really think it matters too much either way.

multiple people have complained in the discord about it, and while not a direct comparison, this is a heretic finisher and is meant to be a round ender for the most part, highly destructive, to be able to be ended with a simple clown car just doesnt fit, its not supposed to be easy to kill. regardless, i only did this fix because people asked me to, i dont care much either way as its probably rare for this to ever happen

**Comment by GuyonBroadway** [comment]
If heretics managed to summon armsy AND a traitor clown has lived long enough to buy a clown car and gets oppertunity to use it... yeah that's funny.

**Comment by ATH1909** [comment]
This makes the clown car unable to suck up ANY heretic monster (rust walkers, ash men etc.), not just armsies. The problem here isn't that clown cars can suck up specifically armsies, but rather that they can suck up creatures with astronomically high move_resist values (like those of armsy and his segments).

**Comment by ATH1909** [comment]
Also, you've put this check only in Bump(), instead of the proc that actually moves the creature into the car, so clown cars can still vore armsies via other means, like click+dragging them into the car.

**Comment by AlinaStarkova** [comment]
> 
> 
> Also, since you've put this check in (only) Bump(), you can still use click+dragging to put armsies in clown cars.

oof, ill add the check to the pull as well, though this fix doesnt seem very popular hahaha

**Comment by GuyonBroadway** [comment]
Compromise, add a difficult to trigger situation where armsy can absorb the clown car and become car'sie.

**Comment by AlinaStarkova** [comment]
> Compromise, add a difficult to trigger situation where armsy can absorb the clown car and become car'sie.

huh, that sounds complicated, this is my first time using github and the file tree is complicated as hell. took me hours to fix just this

if people really want it though i can look into making it possible for armsy to drag the car i to itself, which makes it so armsy can then suck up anyone it bumps into as if it was a clown car. that doesnt seem THAT hard to implement tbh

**Comment by AdamElTablawy** [comment]
The hilarious edgecase of an eldritch arm-monster from beyond reality with incredible strength scampering in terror from an idiot clown in a funny car is pure SS13 and removing it is bad.

**Comment by AlinaStarkova** [comment]
> The hilarious edgecase of an eldritch arm-monster from beyond reality with incredible strength scampering in terror from an idiot clown in a funny car is pure SS13 and removing it is bad.

regardless of it being an edgecase, i was told multiple times by multiple people that clowncar isnt supposed to suck up anything with that high of a move resist value, so i made the fix, wether or not it merges isnt really a concern of mine. its up to the coders how they want the clowncar to function

**Comment by Qustinnus** [comment]
When I made the clown car I made it not suck up megafauna because oranges asked. If I wanted anything else with a high move resist to be resistent I would've just checked their move resist.

**Comment by GuyonBroadway** [comment]
> > The hilarious edgecase of an eldritch arm-monster from beyond reality with incredible strength scampering in terror from an idiot clown in a funny car is pure SS13 and removing it is bad.
> 
> regardless of it being an edgecase, i was told multiple times by multiple people that clowncar isnt supposed to suck up anything with that high of a move resist value, so i made the fix, wether or not it merges isnt really a concern of mine. its up to the coders how they want the clowncar to function

If the issue was with moveresist values then thats an issue with more than just armsy.

**Comment by AlinaStarkova** [comment]
> > > The hilarious edgecase of an eldritch arm-monster from beyond reality with incredible strength scampering in terror from an idiot clown in a funny car is pure SS13 and removing it is bad.
> > 
> > regardless of it being an edgecase, i was told multiple times by multiple people that clowncar isnt supposed to suck up anything with that high of a move resist value, so i made the fix, wether or not it merges isnt really a concern of mine. its up to the coders how they want the clowncar to function
> 
> If the issue was with moveresist values then thats an issue with more than just armsy.

im aware, but i already tried to add a move resist check with ATHATHs help, it didnt work, so for now a manual check for each case is how im doing it, in this case its megafauna and armsy, idk what other mobs have an overpowering move resist

**Comment by AlinaStarkova** [comment]
and can you guys stop bothering ME about this stuff, i dont care, i made this PR because i was asked to make it. thats it. i dont care about the result

**Comment by Qustinnus** [comment]
You are the author of the pr, you are literally the only one we can ask because we have no clue who these "other people" are you keep referring to.

**Pull request closed without merging**
