### PR TITLE
Dogs now bark at felinids and mailmen

### PR DESCRIPTION
**Pull request by Ryll-Ryll**
## About The Pull Request
AI dogs can now rarely bark and paw at nearby felinids and people wearing mailman clothing. Also fixes dog harass/attack AI to now only close within 3 tiles of a target before stopping, and only attacking if the target approaches them (or the dog is pushed into them I guess) like originally intended.
## Why It's Good For The Game
Adds more little fun moments and life to the game. also grrr cats
## Changelog
:cl: Ryll/Shaps
add: Dogs will now occasionally bark at their two mortal enemies: felinids and mailmen
fix: Dogs set to attack will now only close within 3 tiles of their target, and must be approached further by their target (or pushed next to their target) to actually attack
/:cl:

### CODE REVIEW

**Review by MrMelbert — CHANGES_REQUESTED** [review]

**Comment by Shadowflame909** [comment]
I guess we'll be seeing felinid chefs make some more ian burgers (Not HOP approved!)

**Comment by Fikou** [comment]
what about cat cats too rather than just human cats

**Comment by Ryll-Ryll** [comment]
> what about cat cats too rather than just human cats

would lead to too much interaction between basic mobs without any benefit to players

**Comment by Fikou** [comment]
> > what about cat cats too rather than just human cats
> 
> would lead to too much interaction between basic mobs without any benefit to players

oh no things in the game interact between themselves and make the game world feel more real. how terrible.

**Comment by JohnFulpWillard** [comment]
ian and runtime are best friends, get real

**Comment by Ryll-Ryll** [comment]
> > > what about cat cats too rather than just human cats
> > 
> > 
> > would lead to too much interaction between basic mobs without any benefit to players
> 
> oh no things in the game interact between themselves and make the game world feel more real. how terrible.

it'd just be spam messages without any depth, if you want to write enough depth to justify the interaction feel free to follow up

**Pull request merged**
