### PR TITLE
Splits tramstation.dmm into single z-level files

### PR DESCRIPTION
**Pull request by Thunder12345**
## About The Pull Request

Replaces tramstation.dmm with new map files tramstation_upper.dmm and tramstation_lower.dmm, each containing a single z-level. Adds both levels individually to the ALL_MAPS define so all station map files are still being compiled with that define.

## Why It's Good For The Game

Using separate files for each level of a multi-z map is required for mapdiffbot to show changes on higher z-levels. This also reduces potential for merge conflicts on the map as edits to the two different levels are entirely independent of each other.

## Changelog

No changelog as this change is totally internal and changes nothing player- or admin-facing.

### CODE REVIEW

**Comment by Mothblocks** [comment]
finally

**Comment by tralezab** [comment]
goood and this should be a standard

**Comment by MMMiracles** [comment]
it would sure be great if we had a mapping program that rendered multiz views properly from multiple files before you did this

fastdmm2 has multiz rendering but it only works on a single file and this kinda fucks my whole flow ngl

**Comment by Thunder12345** [comment]
> it would sure be great if we had a mapping program that rendered multiz views properly from multiple files before you did this

We do and it’s called StrongDMM

**Comment by MMMiracles** [comment]
> > it would sure be great if we had a mapping program that rendered multiz views properly from multiple files before you did this
> 
> We do and it’s called StrongDMM

Last time I checked, StrongDMM doesn't do this:
image

**Comment by Fikou** [comment]
that's not what splitting means idiot

**Comment by LemonInTheDark** [comment]
> it would sure be great if we had a mapping program that rendered multiz views properly from multiple files before you did this
> 
> fastdmm2 has multiz rendering but it only works on a single file and this kinda fucks my whole flow ngl

You got fucked by monster

**Comment by Zytolg** [comment]
If you want to do this, I want to see it get linted. It'd be easy to check for and I don't want to have to tell every mapper in the future that their PR is invalid because they did everything the way most editors guide them towards (putting it all in one map file). I'm sure the maptainers will agree. Everything else is basically policy, and while I think it'd be better to fix mapdiffbot towards rendering all z's in a given map file, I can see where we stand to benefit form the consistency this would bring. That's my preference, but I'll go with whatever both maptainers decide on. With that being said, this isn't really a high priority issue and **all** map PR's should include screenshots of the changed areas in the PR text to begin with. Mapdiffbot is nice, but can and will fail.

**Comment by Maurukas** [comment]
I've been pretty clear that there are currently pros and cons to each map format. They each have different levels of support with the available mapping tools, and there is not a clear advantage to either one. SS13 will run maps in either format without caring about it. The decision of which one to use has been left to the creator of the map.

I'm not convinced that choice should be compulsory.

**Comment by LemonInTheDark** [comment]
I genuinely feel really crummy about this whole thing. It's just kinda a failure of tooling.
Mapdiffbot wasn't built to support 1 file multiz, and fixing that would require redoing the program. The host of the app doesn't like the concept just in general, so any attempt to add support there is bust.

But counter to that, no existing map editor lets you treat two files as one. Fast and strong dmm would require a similar refactor to mapdiffbot in terms of how files and maps are stored, but spair_ appears to be awol, and monster seems to think it's a mapdiffbot problem.

The whole thing is a mess, and it makes me sad.

If I had the time and knowhow I'd make my own tool, but I don't, and I'm sure whatever I made would have some flaw built in too 
image
:sadkirby:

**Comment by Mothblocks** [comment]
@tgstation/maptainers Your ball park on merging or closing--MapDiffBot or StrongDMM?

**Comment by LemonInTheDark** [comment]
moth that's the wrong ballpark

**Comment by Mothblocks** [comment]
Explain

**Comment by LemonInTheDark** [comment]
StrongDMM just straight up just doesn't render multiz in the way mmm uses, with transparency where there should be transparency and such. That's just FastDMM2, which was in theory built to better support multiz maps.

But FastDMM2 only supports multiz maps doing that if they're in the same file, and monster seems unwilling to change that.

It's very frustrating because it's something that should be supported, but none seems to want to support it, and removing it is a genuine blow.

I think that's why murkas doesn't want to set a standard, since it's ultimately a preference thing, and that somewhat comes down to who's actually developing the map actively.

**Comment by Mothblocks** [comment]
If they don't want to set a standard then they can close it, that's what I meant by "it's in your ballpark"--they have to decide which they value more

**Comment by Maurukas** [comment]
>I genuinely feel really crummy about this whole thing. It's just kinda a failure of tooling.

Tooling which you neither produced nor contributed to to as far as I'm aware. You have nothing to feel crummy about. The current state of the tooling is better than it has ever been in the state of the game. While it has limitations, ancient spacemen from half a decade ago would be in awe of what we now have.

That said I've made my point and discussed it with Inept. While there's incomplete support in our primary mapping tool, I don't want to force maps into either format. My condition for standardizing the map format would be good support in StrongDMM, including the ability to visually overlay separated map files. Until that time, FastDMM2 remains a viable option for mapping because of its stronger support - even if it's not a recommended solution.

**Pull request closed without merging**
