### PR TITLE
Freon no longer freezes some clockwork things it really shouldn't

### LINKED ISSUE #29528: Freon freezes ratvar's timer.
This lets you shut the roundtype down by rushing in with a freon canister and opening it vaguely nearby the portal.

Can we remove freon already it's broken in almost every single way.

EDIT: Can be bypassed by creating a new portal. Still utterly nuts.

### PR DESCRIPTION
**Pull request by ghost**
:cl: Xhuis
fix: Massive portals in spacetime as well as the elder gods they summon can no longer be frozen by a canister of freon.
/:cl:

Freon no longer freezes Ratvar and the Ark. Both of their sprites disappear when they're frozen and that should not be happening.

### CODE REVIEW

**Comment by optimumtact** [comment]
no balance changes during the freeze

**Review by Cyberboss — APPROVED** [review]

**Comment by Anonmare** [comment]
Orange reading comprehension

**Comment by Kromgar** [comment]
Freon should actually shut down clockwork structures because the cogs freeze up

**Comment by ike709** [comment]
a47

**Comment by optimumtact** [comment]
@Anonmare it's obviously a balance change, it works around a certain bug by sidestepping the actual issue (blending not working on some icons) but does not actually fix it, at most you could call this an oversight on the part of the clockcult devs, but in my opinion it's a balance change.

**Comment by Xhuis** [comment]
This is not a balance change. It has no bearing on balance. It fixes Ratvar and the Ark's sprites being made invisible by freon.

**Comment by Kromgar** [comment]
Freon gums up the cogs and causes them to stop functioning thus stopping the opening of the clockwork ark. 

Instead of making it immune to freon make it so you can melt the ice and the icon doesn't disappear

**Comment by Iamgoofball** [comment]
This is an oversight on my end

**Comment by ShizCalev** [comment]
Should I merge this into #29533? It does the same thing for other items more or less; that way there's less copypasta proc returns

**Comment by Xhuis** [comment]
Sure.

**Comment by tortellinitony** [comment]
yea just let the other PR do this since it has a better solution

**Pull request closed without merging**
