### PR TITLE
Gives the pirate ship a cell charger

### PR DESCRIPTION
**Pull request by cacogen**
## About The Pull Request

Puts a cell charger on the default pirate ship.

## Why It's Good For The Game
Allows pirates to recharge their suit cells, which deplete quickly, without having to rely on a station charger (or cells).

## Changelog

:cl:
balance: The default pirate ship now has a cell charger to recharge suit cells
/:cl:

### CODE REVIEW

**Review by Son-of-Space — APPROVED** [review]
Map changes are solid.

I don't really have any comment on the balance part besides adding a cell charger instead of a full charger is a pretty good compromise for people that think a full charger might be too much.

**Comment by wesoda25** [comment]
Personally I think it'd be a better idea to just include extra cells on the ship. Electric machinery on a wood ship sounds odd to me. 

May be talking out of my ass here though, could be plenty of exceptions present on the ship.

**Review by san7890 — CHANGES_REQUESTED** [review]
image

I'm not really a fan of the clutter created by having the laser guns right on top of their charger. You can maybe move the vent into the center of the room (the atmos doesn't need to be configured like that) and create a new table for the laser guns/charger (but separately). Feel free to mark this PR as "Ready to Review" when this is addressed. Let me know if you need any help with this.

**Comment by cacogen** [comment]
They were already like that.

**Comment by san7890** [comment]
> The laser guns on top of the gun recharger were already like that.

image

No?

**Comment by cacogen** [comment]
There's another set to the left of the cell charger, on top of a gun charger, that were already there before I edited the map. It's standard and normal and you don't need to second guess me or bikeshed over something so inconsequential. I've been contributing map edits for a very long time.

**Pull request merged**
