### PR TITLE
Makes turrets less of a joke

### PR DESCRIPTION
**Pull request by Dorsisdwarf**
Cuts the warm-up and cool-down time of turrets by 50%. This cuts the amount of time between shutdown and being ready to acquire targets is down from ~2 seconds to ~1 second.

Effects:
This means you have to be quicker on your feet to do the "dodging in and out of the doors killing turrets with basically no risk" method of soloing the AI, with less margin of error for fucking up your timing. 
It should also make it impossible to do the "just waiting until they begin shutting then running in and turning the APC off in your 2-second window of invulnerability" method.

This is basically a worst case scenario ree
(Note that the gif doesnt include the time between the turrets detecting you and beginning to open because I'm bad at timing)

I'm not wedded to the "50% cut" thing, and I could easily be persuaded to remove the change to the turret-closing time and only buff the opening.

:cl: Dorsidwarf
balance: Nanotrasen Robotics Supply Division has successfully petitioned to replace the "My First Robot" motors in turret coverings with a standard commercial brand. As such, they will now open faster.
/:cl:

### CODE REVIEW

**Comment by kevinz000** [comment]
finally fuck people (myself included) cheesing it that way lmao.

**Comment by WJohn** [comment]
Those are still taking an extremely long time before they actually start firing. Is that because they never selected their mode before? They could definitely be faster on the "deployed, about to fire" front.

**Comment by ExcessiveUseOfCobblestone** [comment]
turrets need an overhaul reee

**Review by Cyberboss — APPROVED** [review]

**Comment by Robustin** [comment]
Turret killing was never "No risk" as long as lag exists and judging from the GIF im looking at, its downright impossible with melee weapons.

**Comment by Tokiko1** [comment]
Sounds like this will just make people more likely to weld in through the few reinforced walls from space rather than try and actually run the turret gauntlet. Not sure if that's more fun for the AI player.

**Comment by Dorsisdwarf** [comment]
You cant "run the turret gauntlet" already, you either shoot them from the doors, throw foam grenades/push canisters to block the bolts, or you're immune to stuns. Also the idea of being able to rush into the AI core and kill a turret with a toolbox or a fireaxe then run back out is stupid. 

@WJohn Yes, there's a turret variable controlling the fire delay (the in-between-shots cooldown is applied before its allowed to fire the first time) but I didnt touch that because I wanted to make the turrets not-useless, while cutting that would make them far, far too strong

**Comment by AnturK** [comment]
Make this a variable or define please.

**Comment by Dorsisdwarf** [comment]
If you varedit, the animation will break.

**Comment by WJohn** [comment]
Turrets still seem to be a complete joke. Nothing you still can't handle by darting around a corner and taking a shot one at a time. They still have a monstrous delay where they're black, before they turn blue and ready to fire.

**Pull request merged**
