### PR TITLE
Optimizes and simplifies glowshroom spreading

### PR DESCRIPTION
**Pull request by Iamgoofball**
holy shit this was needlessly complex
:cl: Iamgoofball
tweak: Glowshrooms no longer grow onto walls, but should grow faster and properly spread to all nearby open turfs.
del: Removes fancy directional icon work for glowshrooms, they were near impossible to actually notice and only added to overhead.
/:cl:

### CODE REVIEW

**Comment by kevinz000** [comment]
It was complex and fine, but you didn't remove the one part of it that was the worst thing possible.
The infinite timer loop that you completely passed over.

**Comment by ExcessiveUseOfCobblestone** [comment]
They're pretty noticeable?

**Comment by Jord1081** [comment]
If this removes the icons will it cause problems for any lavaland ruins that have the directional icons? Only one I can think of is the birthday party, but I think there may be one or two more.

**Comment by ExcessiveUseOfCobblestone** [comment]
no because, like most goof removals, it's half-assed enough to avoid doing that work of removal proper.

**Comment by Iamgoofball** [comment]
i didnt remove the icons themselves

**Comment by Iamgoofball** [comment]
@ExcessiveUseOfCobblestone This is your last warning. Cease these hostile deriding insults on my PR or I will contact Github.

**Comment by SpaceManiac** [comment]
Doesn't compile and hasn't been touched for two weeks, ping to reopen, the usual, etc.

**Pull request closed without merging**
