### PR TITLE
Updates travis

### PR DESCRIPTION
**Pull request by CorruptComputer**
Ported from bay.

### CODE REVIEW

**Comment by Incoming5643** [comment]
keep in mind there's a few step_[xy] = 0 in the map files already because byond makes the stupid choice of hard defining an edited var even if its edited to its default value.

**Comment by CorruptComputer** [comment]
What the fuck is that last commit? I never did that.

**Comment by CorruptComputer** [comment]
Ready for merge!

**Comment by RemieRichards** [comment]
This is a QOL improvement for the Github (Improves the speed of Travis builds, and adds some checks to Travis) so it's getting fast tracked.

**Comment by Chocobro** [comment]
RIP map prs

**Pull request merged**
