### PR TITLE
Fixes minor issues on icebox medbay

### LINKED ISSUE #63968: New icebox medbay issues
## Round ID:

[176325](https://scrubby.melonmesa.com/round/176325)

## Reproduction:

Play new icebox medbay, after #63804 (props by the way) was merged

### Wrong icebox medbay cargo console 

Full supply request console, instead of the medical cargo console was placed in medbay.

### Exposed wires / missing floor tile

There are exposed wires in and around cryo (left, north and ~~freezer~~)

### Door opener doesn't work

The security post's door opener button doesn't open the door. Also tried pressing with full access.

### CMO table unreachable

The top left table with the paper is unreachable in CMO's office.

### PR DESCRIPTION
**Pull request by AlinaStarkova**
## About The Pull Request
some things must have broke/went missing during the map conflict i fixed the other day, minor issues atleast.

this should fix everything in and closes #63968
also adds a viro food dispenser again.

## Why It's Good For The Game
fixes

## Changelog

:cl: Nari Harimoto
fix: The icebox gremlins went and fixed some minor issues the construction crew made of the new Icebox Medbay
/:cl:

### CODE REVIEW

**Review by MrMelbert — CHANGES_REQUESTED** [review]
- The med storage and surgical rooms have no firelocks under their doors (there's also no fire-alarm in med storage, so...)
- Sus
image

**Comment by the-orange-cow** [comment]
The viro lab has no basic virus food dispencer.

**Comment by MrMelbert** [comment]
> The viro lab has no basic virus food dispencer.

That's already fixed in this PR

But side note, while not necessary in this PR but there's barely any newscasters or status displays around the whole place

**Comment by AlinaStarkova** [comment]
No clue what the merge conflict even was, i merged from master and none of the latest edits caused any conflicts whatsoever on my end, so uh, whatever

**Review by MrMelbert — APPROVED** [review]

**Review by MrMelbert — CHANGES_REQUESTED** [review]
one other thing actually
image
this shower + sink are arranged in a way both cannot be plumbed (the duct pops up roundstart, disconnecting the sink)

**Comment by AlinaStarkova** [comment]
> one other thing actually image this shower + sink are arranged in a way both cannot be plumbed (the duct pops up roundstart, disconnecting the sink)

image

**Comment by AlinaStarkova** [comment]
added a borg charger to medbay, so CMO and medical can charge their modsuits
image


I also went and swapped all corner decals for full tile decals, whoever added these decals in has my many thanks, it cuts down 4 decals on all these tiles, to just 1 decal, saves a lot of lines in the map and removes 3 objects from each tile
image

**Review by MrMelbert — APPROVED** [review]

**Pull request merged**
