### PR TITLE
Removes space pirate ruin from the ruins list

### PR DESCRIPTION
**Pull request by Tacolizard**
This removes the space pirate ruin from the ruins list. The map file is still in the repo

:cl: fun-hater update
rscdel: The space pirate ruin will no longer spawn.
/:cl:

at first this was a meme but actually like we have a lot of good ruins, what's the point of keeping one that seems to only serve as a source of OP loot and a way to expose bugs. Yes the ruin isn't the source of the bugs but there are so many that they should be fixed before this ruin is possibly re-added

### CODE REVIEW

**Comment by ShadowDeath6** [comment]
How did people miss this bug

**Review by Jalleo — CHANGES_REQUESTED** [review]
Improve do not remove

**Comment by TechnoAlchemisto** [comment]
PICTURES NEEDED FOR SPRITE CHANGES BEFORE/AFTER TOO PLS

**Comment by Cyberboss** [comment]
The problem isn't the ruins, the problem is the space pirates

**Comment by ExcessiveUseOfCobblestone** [comment]
This is a bad way to fix them, but I would be wrong in saying this is a bad fix.

**Comment by FantasticFwoosh** [comment]
Im waiting for a maintainer to wade in and overrule you but in the meantime i could kiss you.

**Comment by PKPenguin321** [comment]
fix the CL

**Comment by coiax** [comment]
You really should just be honest with your title and changelog.

**Comment by coiax** [comment]
Also, because of how git works, removing code doesn't really reduce the size of the repo, because it's still stored in the history. Git repos really only get bigger.

**Comment by optimumtact** [comment]
Your PR has been edited due to having a misleading or incorrect title, consider this a friendly warning, your PR's must have a properly descriptive title and body content if they are going to do something significant.

**Review by Razharas — APPROVED** [review]
Final solution is always the best one

**Comment by Cyberboss** [comment]
If maintainers are serious about this, THIS DOESN'T FIX ANY OF THE LISTED ISSUES

**Comment by optimumtact** [comment]
noted

**Review by optimumtact — CHANGES_REQUESTED** [review]
The ruin exposes these bugs but is not the root cause of them, any grounds for removal is on content grounds only.

**Comment by Tacolizard** [comment]
oranges, #25816 got a pass, but I don't even though my title was way more descriptive?

**Comment by optimumtact** [comment]
#25816 does not substantially alter or rebalance the game, again please note my wording

>Your PR's must have a properly descriptive title and body content if they are going to do something significant.

**Comment by MMMiracles** [comment]
this doesn't even fix the issue, just hides it from public sight.

also you forgot to actually remove it from the ruins list you dingus.

**Comment by kevinz000** [comment]
yet another good change by our friendly tacolizard :^):^):^)

**Comment by FantasticFwoosh** [comment]
@MMMiracles you are noted as being its creator, and probably should account for the reasons given for its removal that its too much to fix in what could have been designed better in the first place. Same story as the space battle away mission (which was also your doing and met the same fate)

> Throwing it into the most distant parts of space as a ruin then guarding it with 340 health mobs with the prospect of looting it for entire tables of high end gear if you can actually KILL anything was as *out-of sight-and-out-of-mind* as you could get.

https://github.com/tgstation/tgstation/pull/19085#issuecomment-230120713

https://github.com/tgstation/tgstation/pull/19085#issuecomment-230121906

> Look at the complaints on the actual map PR, in hindsight a lot of those points only got more valid.

@optimumtact  "We have to balance the quality of art vs the need to evolve as a game." 

> LOL

**Review by duncathan — CHANGES_REQUESTED** [review]
This PR does not actually address any code issues and thus should be ineligible during the freeze.

**Comment by FantasticFwoosh** [comment]
Nessecary changes to the PR title & description under maintainer supervision was made, removing the ruin that sees very little use and also has a range of other problems beside from the listed issues

> Im not sure what additional convincing is required without actively polling at peak times whether people care enough to keep it in.

> Issues do not require to be resolved if they do not exist or the playerbase doesn't care if it doesn't exist as the ruin itself is a moneysink of time & energy since the entire ruin would need to be ripped up and re-evaluated to be made into a equal state of other non-aesthetic space maps like the Sky Tomb.

**Comment by Jordie0608** [comment]
@duncathan maps changes are allowed, even if it's one like this.

Since they've been edited out what were the issues referenced here?

**Comment by FantasticFwoosh** [comment]
If memory serves me correct (I only glanced at the issues in the original content) just github issues with the pirate simple mobs, which are 1/4 of the ruin

#23863 & #22796

**Comment by optimumtact** [comment]
Fwoosh you are starting to annoy me and I will close this pr

**Comment by Grazyn** [comment]
> This PR does not actually address any code issues and thus should be ineligible during the freeze.

@duncathan removals/reverts are allowed during the freeze

**Comment by Sligneris** [comment]
Fix the bugs, but I don't see why you'd have to delete the space ruin.

**Comment by FantasticFwoosh** [comment]
If we are citing content rather than bug reasons, (though pirates being on the ruin with associated bugs is also a problem)

" @optimumtact _The ruin exposes these bugs but is not the root cause of them, any grounds for removal is on content grounds only"_

E.I see above arguements/drama

**Comment by coiax** [comment]
Needs pictures? Really @optimumtact?

**Comment by Sligneris** [comment]
Then I still have yet  to see any good reasons for removing content.

**Comment by kevinz000** [comment]
i believe it's called tacolizard once again touching things that he doesn't fully understand.

**Comment by Militaires** [comment]
@kevinz000 dont talk shit about TL they fixed a higgs buggson

**Comment by RemieRichards** [comment]
@Militaires when?

**Review by RemieRichards — CHANGES_REQUESTED** [review]
A pirate appear.

**Comment by Militaires** [comment]
@RemieRichards 
_breathes deeply_

#22894

**boi.**

**Comment by RemieRichards** [comment]
Eh, not really, that's not the solution it just happened to solve the issue.
The real issue was byond's direct x redistributions didn't included a rather important file, the SDK just happened to include that file.

The real fix was lummox adding that file in properly. 

it's a nice find, but it wasn't the fix.

**Comment by FantasticFwoosh** [comment]
There was a picture in the original PR thread, why are you requesting it. Here's a before & after.

**Comment by Tacolizard** [comment]
@RemieRichards no i fixed it i definitely fully understood why that was the fix as well

**Comment by Tacolizard** [comment]
is keeping it in the repo but off the ruins list a good compromise?

**Comment by Tacolizard** [comment]
actually though on the topic of the higgs-bugson, I did a lot of research to figure that one out. It was really hard because most people on the codebase I talked to just told me to get a better computer

**Comment by MMMiracles** [comment]
i think the real compromise is fixing the actual issues instead of removing the thing that exposed the issue

**Comment by Tacolizard** [comment]
@MMMiracles if there are this many problems with the ruin, it shouldn't be in the game until it's fixed

**Comment by MMMiracles** [comment]
sounds like a whole lot of opinion and avoiding the issue, which is especially dumb during a code freeze that exists solely to fix these issues.

**Comment by Tacolizard** [comment]
whatever. someone else take the heat if you want this removed.

**Comment by FantasticFwoosh** [comment]
In which case Tacolizard, it might be worth consulting other mappers like WJohn to give this dirty map a deep clean because if we can't remove it, then we might as well give it such a facelift and then fumigate it of bugs for re-purposing.

Unless you'd like to agree to remap it @MMMiracles

**Comment by MMMiracles** [comment]
All I see being an issue are the apparently-bugged pirates, which are an actual issue that needs to be addressed, but deciding to kill off a ruin solely because you don't want to fix the actual problem and have a differing opinion on the ruin itself.

**Comment by FantasticFwoosh** [comment]
Two birds one stone.

**Comment by duncathan** [comment]
removing the ruin from the list but keeping it in the code is better; ruins like these are often run downstream

**Comment by optimumtact** [comment]
Or you know, Fwoosh/Taco should stop complaining about a space ruin that is rarely seen and does not affect their round in any way unless they choose to go out into space and find it.

**Pull request closed without merging**
