### PR TITLE
Re-adds the touch effect of legion souls.

### PR DESCRIPTION
**Pull request by TechnoAlchemisto**
Partial Revert of #20352

Keeps the removal of the healing over time, reverts the removal of the use of it as a one use healing item.

### CODE REVIEW

**Comment by KorPhaeron** [comment]
Why did that part get removed

**Comment by lzimann** [comment]
what is the point of having the full heal when implanted if you ahve full heal when used anyway

**Comment by KorPhaeron** [comment]
Because the implanted one triggers when you're in crit/is hands free/doesn't decay

**Comment by Kromgar** [comment]
Lzimann its essentially a free get out of crit card you cant use legion souls when in crit if they are in your backpack and your unconcious

**Comment by Ergovisavi** [comment]
Can we talk about how this nerf actually made legion implants more broken than they were before

Because now they're literally adrenaline implants that instantly fully heal you and that has significantly more negative gameplay impact than the slow heal ever did

**Comment by Kromgar** [comment]
Wait it gives adrenaline now? Niiiice

**Comment by lzimann** [comment]
No just full heal

**Comment by Ergovisavi** [comment]
You're forgetting that the full heal is also a complete removal of all CC effects.

Imagine that you baton someone and go to cuff them, and then they instantly get back up due to this.

It's an adrenaline implant, essentially. Really bad.

**Comment by lzimann** [comment]
i think you cant use action buttons while stunned, not sure though

**Comment by TechnoAlchemisto** [comment]
You can't, they'd have to crit them for this to work.

**Comment by TechnoAlchemisto** [comment]
Although, if this is the admin heal it might decuff people too.

**Pull request merged**
