### PR TITLE
Ignore this PR, it's a testmerge for an event.

### PR DESCRIPTION
**Pull request by nervere**
## About The Pull Request

-Assistants are now the only job on DeltaStation.
-Assistants now have 300 slots.
-Assistants now spawn with a limited outfit datum.

These are the changes requested by the admins running the Battle Royale event on the event hall tonight at 7:00P.M. PST / 10:00P.M. EST.
byond://sybil.tgstation13.org:4337

### CODE REVIEW

**Comment by nervere** [comment]
Reopening because I have to add a new commit and closed PRs don't take new commits.

**Comment by Fikou** [comment]
no i wont ignore

**Comment by Nickkoranda** [comment]
close this now now NOW

**Comment by InsaneKatrina** [comment]
R E D   L A B E L ! !

**Comment by wesoda25** [comment]
hot

**Pull request closed without merging**
