### PR TITLE
Restores Right-Click Functions to Mechs

### PR DESCRIPTION
**Pull request by zxaber**
## About The Pull Request
The way you check for click modifiers apparently changed. Using the old check, Right-Clicking inside a mech would result in a Left-Click action (using the Left Arm equipment), which made the Right Arm equipment unusable.

This updates the Mech code to use the new check.
## Why It's Good For The Game
Bugfix.
## Changelog
:cl:
fix: Mechs can use Right Arm equipment again.
/:cl:

### CODE REVIEW

**Comment by Sealed101** [comment]
why was this an inconsistent issue i wonder. sometimes it would work fine, sometimes it would break.

**Comment by zxaber** [comment]
During testing, I made a list var on the mech and copied the `modifiers` list to it upon clicking.

image

There is no key for `button`, so far as I can tell it shouldn't have been working at all. In any case, it hasn't been working whenever I tried for some time now.

**Comment by zxaber** [comment]
Apparently the bug might actually be a Byond version thing. I'll close or set to ready after I test.

**Comment by zxaber** [comment]
Tested with an updated client and the issue is gone. So this is actually unnecessary.

**Pull request closed without merging**
