### PR TITLE
Lead pipe readjustments

### PR DESCRIPTION
**Pull request by grungussuss**
## About The Pull Request
- the lead pipe drop sound now only triggers on throw, otherwise it'll use the metal sheet drop sound.
- fixed thrown items not respecting the sound_vary var
## Why It's Good For The Game
It was never my intention that players create noise machines or annoy people greatly with this sound, since players decided to abuse it - I'm fixing it.
## Changelog
:cl: grungussuss
fix: thrown items now respect the vary variable when making drop sounds.
sound: lead pipe now only makes an obnoxious drop sound when thrown., reduced its sound by 10db
/:cl:

### CODE REVIEW

**Comment by Singul0** [comment]
1. Lead pipe is added as an nifty (though unwieldy) melee loot found in maints for greytiders to use, 3 years ago.
4. A month ago a PR adds funny sounds for the lead pipe
5. Players, predictably uses it as a noise machine instead of it's original use as an redundant weapon (other people in said PR warned of this)

Solution?
Soft removes the lead pipe in every station maints.

Surely there is a better way to go about doing this instead of completely soft removing the item by erasing it from the maint loot table. The other changes besides that change is already enough imo

**Comment by Sadboysuss** [comment]
> Surely there is a better way to go about doing this instead of completely soft removing the item by erasing it from the maint loot table. The other changes besides that change is already enough imo

It's not removed from the loot table at all, all I did was remove it from guaranteed mapped in spawns, some maps had them there at all times so players could go there knowing that it is there every time.

**Comment by Singul0** [comment]
> > Surely there is a better way to go about doing this instead of completely soft removing the item by erasing it from the maint loot table. The other changes besides that change is already enough imo
> 
> It's not removed from the loot table at all, all I did was remove it from guaranteed mapped in spawns, some maps had them there at all times so players could go there knowing that it is there every time.

Eh. my bad. didn't read it closely enough. though. it seems like a very extreme change still.

**Comment by Xackii** [comment]
And where can I get a lead pipe now?

**Comment by Sadboysuss** [comment]
> And where can I get a lead pipe now?

it randomly spawns in maintenance, like it always did

**Comment by Xackii** [comment]
Well, don't know. The only thing I see is that you removed the lead pipe from north star and garbagetrack? did anyone actually fly into space to find a lead pipe? pirate_irs is this a pirate shuttle? and soviet_bear is actually a map from a basketball minigame for ghosts. There are not many places where you can loot a lead pipe roundstart.

**Comment by Sadboysuss** [comment]
it shouldn't be possible to have more than 2 lead pipes in a round at once, maybe I should've clarified that

**Comment by Xackii** [comment]
You will have to bite the throat of everyone who wants to add a lead pipe to their map in the future.

**Comment by Sadboysuss** [comment]
> You will have to bite the throat of everyone who wants to add a lead pipe to their map in the future.

could do a unit test for that, but I'm not sure if it's actually needed

**Comment by LemonInTheDark** [comment]
I don't think it makes sense to touch mapped in pipes because like, it's just one/at most two per map.
This seems mostly like an admin issue to me. If you want to make the noise harder to spam that's fine but like, you should not need to build your code around people spamming it.

**Comment by Singul0** [comment]
removing all mapped instances of lead pipes and enforcing a limit of two lead pipes per round seems unwise tbh, as a mapper I love putting random stuff/junk around where it suits them. like say, a lead pipe in the IRS ship torture chamber.

I get why you would remove static instances of it in station maints, but also removing the ones in other places seems excessive. since. as I have said before, it's not like people would go out of their way to pick-up / loot lead pipes when exploring. the stuff is wieldy to haul around. if they're comitted enough to haul it to the station as a funny noise machine. let them.

**Comment by Sadboysuss** [comment]
alright I'll revert the map edits

**Comment by mc-oofert** [comment]
just revert the sound problem solved

**Comment by necromanceranne** [comment]
The issue with it just being on throw is that I can set up a pair of disposal inlets and outlets to launch and then catch the pipes over and over via conveyor belts. You can definitely still noise spam these things.

**Comment by Sadboysuss** [comment]
> The issue with it just being on throw is that I can set up a pair of disposal inlets and outlets to launch and then catch the pipes over and over via conveyor belts. You can definitely still noise spam these things.

Then let the admins ban them or something, I just saw someone picking it up and dropping in quick succession, this should mitigate it so you need more effort and it's more obvious to an admin that the player is purposefully making noise to annoy people.

**Comment by ZephyrTFA** [comment]
If players are spamming the sound to the detriment of others that is a player/player/admin issue

**Comment by ninjanomnom** [comment]
Nah this is prety reasonable to have a more intense throw sound for some things

**Comment by Sadboysuss** [comment]
reduced the volume by 10db per the discussion in discord

**Pull request merged**
