### PR TITLE
Adds "fun balloons"; tools to make things happen

### PR DESCRIPTION
**Pull request by coiax**
A fun balloon is an object that regularly checks a condition, and if that condition is fulfilled, it "pops" which causes some sort of effect. A balloon can also be popped by an admin ghost clicking it.

The first concrete example of this is a "sentience fun balloon", which when popped, gets all living mobs in a short range, and offers control of them to ghosts. Special versions of these balloons, triggered by the emergency shuttle timer being 60 seconds or less have been added to the Emergency Escape Bar and Shuttle 667.
- Replaces the sparkles from repulse from a hard {} edited random item to a class of its own that handles its own overlay addition and self deletion.

Current bugs:
- [ ] When a shuttle balloon pops, it spams all observers at least 5 times with popups, and I don't know why.

### CODE REVIEW

**Comment by Niknakflak** [comment]
More admin meme items are a bad idea.
It also makes it so perfectly fine shuttles like the escape bar, can't be loaded in non meme rounds anymore for fear of ruining rounds

**Comment by coiax** [comment]
Niknak, if you're loading in the escape bar and not giving the bar staff sentience, you're not doing it right. The thing literally has tables that only barstaff can cross.

This is less of an admin meme tool and more just a place to put effects that I need somewhere to put, that can also be used during the admin running their own events.

**Comment by Niknakflak** [comment]
Balloons offering control to ghosts is the issue

**Comment by Cheridan** [comment]
admins dont deserve nice things tbh

**Comment by Bawhoppen** [comment]
remember when kor tried to add noghost zones and admins wanted to be immune to that

**Comment by optimumtact** [comment]
Rip balloon

**Comment by optimumtact** [comment]
ping me when you get back to this and it's in a ready state

**Pull request closed without merging**
