### PR TITLE
Gaining Vanguard will remove existing stuns

### PR DESCRIPTION
**Pull request by ChangelingRain**
:cl: Joan
rscadd: Gaining Vanguard, such as from the Linked Vanguard scripture, will remove existing stuns.
/:cl:

### CODE REVIEW

**Comment by Cyberboss** [comment]
Joan didn't get the memo

**Comment by ChangelingRain** [comment]
I know my pr is going to be frozen and closed. But that's no reason not to put the work in!

**Comment by lzimann** [comment]
joan pls

**Comment by Cyberboss** [comment]
Great example setting!

**Comment by KorPhaeron** [comment]
PRs that violated the freeze have to wait a week longer to be PRd or else people will keep opening their feature PRs during freezes

**Pull request merged**
