### PR TITLE
Makes the transparency of the UI styles consistent

### PR DESCRIPTION
**Pull request by TrustyGun**
All of the UI styles now have the same transparency.

[Before](http://i.imgur.com/gQDtL4p.png)

[After](http://i.imgur.com/bUDZhtx.png)

[Ingame After Pics](http://imgur.com/a/JuEDX)

### CODE REVIEW

**Comment by WJohn** [comment]
Kind of impossible to tell with those pics, at least for me.

**Comment by ike709** [comment]
@WJohn  Midnight and slimecore are way more transparent, along with certain icons in plasmafire and operative.

I dunno how I feel about this... I've always liked midnight the way it was.

**Comment by TrustyGun** [comment]
@ike709 
Essentially all the icons have the same transparency as the "main" (hands, clothing) icons in plasmafire.

Before hand, midnight and slimecore was nearly opaque.

**Comment by Bawhoppen** [comment]
looks gross, what does it look like actually ingame?

**Comment by TrustyGun** [comment]
[Here's what it looks like ingame.](http://imgur.com/a/JuEDX)

**Comment by Bawhoppen** [comment]
eh doesn't look as good as opaque version :-1:

**Comment by TrustyGun** [comment]
closed against popular request

**Pull request closed without merging**
