### PR TITLE
Emergency aid lockers will now include emergency surgery tools

### PR DESCRIPTION
**Pull request by tralezab**
## About The Pull Request

Adds the emergency scalpel, hemostat, retractor, and cautery.
The first three are slower tools.
The cautery is a shitty white lighter which I'll let you figure out why that's not as good as a proper cautery

## Why It's Good For The Game

image

Our medical system switched to being surgery based for more proper healing awhile back, but the changes to the emergency supplies were very minor, and in short: not enough. The democratizing of medical supplies is a good direction, scarcity is a design on something that doesn't need to be, medical mains don't actually want that and I think it was a mistake to go down that direction. Medical quickly gets flooded when serious amount of corpses happen, people can't make it to med, tense situations could arise where people break out surgery tools. The thing about surgery tools is that it is either completely unneeded or very needed but localized entirely to medical, which means surgery is still locked mostly to entirely a medical only prospect.

## Changelog

:cl:
add: Emergency surgery tools are now supplied in aid lockers
/:cl:

### CODE REVIEW

**Comment by tralezab** [comment]
I honest to god thought this would not pass some sanity on the emergency kit but local unit testing turned out okay

**Comment by Ryll-Ryll** [comment]
This wasn't exactly what I meant, but now that I think about it, I'm actually willing to back this for testmerging. I don't think people will bother with field surgery enough for this to become a primary way for people to treat each other as opposed to going to medbay, but if people want to take the extra time to strap down someone and treat them in a slower way, why not?

**Comment by Ryll-Ryll** [comment]
Though we might want to possibly add a separate emergency++ medical kit that includes the emergency surgical tools, and have them replace 1/3rd of the current emergency medkits

**Comment by Livrah** [comment]
Ghetto surgery is a thing. Maybe just add these tools somewhere?

**Comment by Sealed101** [comment]
emergency medical tools are a glass shiv, a bedsheet and a toolbelt. and even then there are alternatives for worse situations. these kits kind of defeats the spice of ghetto surgery though. iirc the speed modifiers for these and best picks for ghetto tools are somewhat even as well

**Comment by Ryll-Ryll** [comment]
Ghetto surgery isn't great, it requires a bunch of different random items that aren't very intuitive to remember, and in general are far too much of a PITA to bother doing versus other ways of getting healed. I'd wager very very few people really use ghetto surgery on a round-by-round basis

**Comment by Colovorat** [comment]
We merge pr's to make so only medical can do healing/surgery.
Now we create pr with ghetto tools, so anyone can do surgery.
You need to finalize your thoughts on who you want to be able to do medical jobs

**Comment by Colovorat** [comment]
> emergency medical tools are a glass shiv, a bedsheet and a toolbelt. and even then there are alternatives for worse situations. these kits kind of defeats the spice of ghetto surgery though. iirc the speed modifiers for these and best picks for ghetto tools are somewhat even as well

Some alcohol and basic bed should negate most of ghetto tools decreased speed

**Comment by Ryll-Ryll** [comment]
> We merge pr's to make so only medical can do healing/surgery.

I've been pretty consistent about pushing back against PR's that do this, as well as arguing against it on the discord, it's just that I don't see every single PR that does that

**Comment by LemonInTheDark** [comment]
> Ghetto surgery isn't great, it requires a bunch of different random items that aren't very intuitive to remember, and in general are far too much of a PITA to bother doing versus other ways of getting healed. I'd wager very very few people really use ghetto surgery on a round-by-round basis

Shouldn't we make it more usable then? Otherwise we're basically sunsetting a whole swath of features rather then fixing them up.

**Comment by ATH1909** [comment]
you can't actually do any surgery with these tools without drapes, a bedsheet, etc.

technically, you can cut up the emergency gauze in the medkit into cloth using the emergency scalpel, then turn that cloth into a bedsheet, but most players aren't gonna know that that's a thing

**Comment by Colovorat** [comment]
Ghetto surgery is so so niche. Like most people don't even know that you can make shiv.
And i don't want to be that guy, but goof gonna create a revert PR if this gets merged because muh assistants "gonnda do all of medical work"

**Comment by Colovorat** [comment]
Also i had an idea that you can start surgery without drapes but it would give speed penalty for all steps of surgery.

**Comment by Palpetinus** [comment]
I honestly do not understand why surgery is being gatekept like this. 
You have the choice between
1. lying a patient down (bed/table/rest), where determines ultimate speed
2. go aaaaall the way to dorms to grab a bedsheet or acquire one through other, unorthordox means
4. grab 2 tools from fuck knows where, toolbelt and maybe you're finding a kitchen knife
5. (optional) strip the patient for more speed
6. if your patient still hasn't died because pre-surgery acquisition takes 5 minutes, now slooooowly heal them

OR
1. smack that "brute heal" patch you found at medbay 10 minutes in onto a patient for the same effect

Which one do you think people are doing right now? Hm...
Surgery outside of medbay is so heavily discouraged, it's downright nonexistent.

**Comment by Sealed101** [comment]
why not implement paper notes in emergency medkits that hint at or outright state the various objects that you can use in ghetto surgery, as well as alcohol disinfecting and suitable places for it like beds and tables

**Comment by GuillaumePrata** [comment]
We already have ghetto surgery (Which could be polished to work better) for the times that medbay can't fix people for one reason or another.

IMO democratizing access to surgery is one step into making Medbay suffer the same issue that Engineering has.
Engineers are the best equipped to deal with breaches but the barrier for the crew to do engineer's job is so low that engineers don't even leave their bunker when people scream that medbay was bombed, by the time they walked there, some random doctor already fixed the hull with some leftover metal from the explosion itself.
And then it becomes a shitty cycle, Engineers don't go fix minor damage because someone else will do it, people don't trust engineers to do their job so they go and do it themselves.
Neither side is happy with how this work, other than those engineers that enjoy sitting in a room making a fortress with every department's machinery or sitting at the SM/HFR room and watching numbers go up.

We already have players that drag their friends to medbay maints/holodeck to revive them because they don't trust doctors, we shouldn't enable more of that mentality.

**Pull request closed without merging**
