### PR TITLE
Revert "Adds a happy greeting for my friends the admins who I love!"

### PR DESCRIPTION
**Pull request by Shadowlight213**
Reverts tgstation/-tg-station#11336
Almost every admin including headmins don't like this.

### CODE REVIEW

**Comment by Dicks1** [comment]
If this doesn't get merged quickly I might just remove/ban every coder I can find.

You have 1 hour.

**Comment by WJohn** [comment]
But I like it!

**Comment by Jalleo** [comment]
Like i said before this should ask the admin if they want to be announced or not.

**Comment by Aloraydrel** [comment]
The only positive message I get goes away 

;_;

**Comment by Cheridan** [comment]
moral of the story

never show appreciation for admins

**Comment by MrStonedOne** [comment]
>moral of the story

>never show appreciation for admins

**Comment by hornygranny** [comment]
:+1:

**Comment by Iamgoofball** [comment]
things like this is why people dont like admins

**Comment by Aranclanos** [comment]
the admins are tsun they actually like it

**Comment by Niknakflak** [comment]
Reopen this

**Comment by Shadowlight213** [comment]
@Cheridan can you reopen this please?

**Comment by optimumtact** [comment]
Please provide feedback via our feedback forums thank you

**Pull request closed without merging**
