### PR TITLE
Cogscarabs will now visually flip over when stunned

### PR DESCRIPTION
**Pull request by ChangelingRain**
It does a flip. It's stuck on its back, and can't do anything, because it's on its back.

### CODE REVIEW

**Comment by Expletive** [comment]
antag freeze reeeee

**Comment by Iamgoofball** [comment]
cosmetic feature reeeee

**Comment by WJohn** [comment]
It should be animated, make the legs wriggle like it's trying to right itself!

**Comment by vcordie** [comment]
what wjohn said please, or have them slowly rotate or rock. will help differente between scarabs that are dead and scarabs that are simply stunned

**Comment by RemieRichards** [comment]
@WJohn @ChangelingRain thoughts?
 

http://www.mediafire.com/view/p5y2894895aeql9/flipped.dmi

**Comment by Shadowlight213** [comment]
It's cute

**Comment by DoctoreMad** [comment]
This is clearly a clockwork cult nerf
(I appreciate it)

**Comment by ChangelingRain** [comment]
That is wonderful and I'm adding it immediately.

**Comment by Militaires** [comment]
this is going to cause cogscarab + cock cockscarab erp
remove this pr from the premises

**Comment by The-clown-known-as-Pepe** [comment]
is this the famous slippery slope?

**Comment by vcordie** [comment]
stop trying to ruin the cute

**Comment by The-clown-known-as-Pepe** [comment]
@Iamgoofball please help identify is this a slippery slope or not.

**Comment by Iamgoofball** [comment]
Potential, watch post merge for signs of slipping

**Comment by The-clown-known-as-Pepe** [comment]
@Iamgoofball can you post that meme picture about slippery slope again?

**Comment by dannno** [comment]
it's visual indication of a mechanic 👍

**Comment by Iamgoofball** [comment]
oranges has it

**Pull request merged**
