### PR TITLE
Removes EXPERIMENTOR

### PR DESCRIPTION
**Pull request by ohnopigeons**
:cl:
del: The E.X.P.E.R.I.MENTOR has been removed from all stations.
/:cl:

The E.X.P.E.R.I.MENTOR was added with the intention of either replacing or being an alternative to Destructive Analyzer RnD. It has done neither. Instead of replacing the DA it became a separate machine which practically no one uses or has fun with. It is also barely being maintained, consisting of minor fixes; the last content tweak was over a year ago as far as I can tell. With new upcoming RnD overhauls coming soon™ the experimentor is even less relevant.

### CODE REVIEW

**Comment by unrealair** [comment]
I like it because I like strange objects

**Comment by GunHog** [comment]
It is useful for having a chance to preserve the items you are scanning, so you have a CHANCE to not lose a high-value item, like an ebow.

**Comment by qbmax32** [comment]
As a science player, I think this is a bad PR, the experimenter is good for strange objects and the like and I hate to see it go. Rather then remove it entirely? Why not upgrade it with the new science changes coming soon(tm)?

**Comment by RogueSteampunker** [comment]
To be honest, I don't think utter removal is necessary. Granted, it's usage in RnD is rather minimal, there's still enough usage in Strange Objects and potential reworkings that it could possibly be kept around. Now, what it's purpose besides SOs would have to be worked out, but utter removal just seems to harsh for it.

**Comment by Really-Good-Soda-Flavor** [comment]
Don't remove this unless you can provide a substantive alternative.

**Comment by kevinz000** [comment]
>With the upcoming RND pr, this is even more useless

Didn't know you knew w hat I was coding! :-1:

**Comment by ohnopigeons** [comment]
@kevinz000 Are you going to incorporate the Experimentor?

**Comment by kevinz000** [comment]
Don't know, don't care, if I happen to need it I'll just make git overwrite the conflict.
If you're not reworking R&D I don't see why you would randomly remove the "telescience replacement machine" just because you don't know how to use it. People do use it, and it has its own functions that people like to have fun with.

**Comment by YakumoChen** [comment]
Strange objects have niche antag uses (particularly the bomb, teleport, and animal summon), antag freeze

**Comment by YakumoChen** [comment]
Not to mention the niche station uses that strange objects have (infinite meat, infinite cleaning foam, flashbang to aid sec)

**Comment by YakumoChen** [comment]
Also has uses to get normally unobtainable power cells

**Comment by ohnopigeons** [comment]
It's being removed from a code maintenace perspective, as it's received no updates in more than a year for something that's practically half-finished. It's also completely failed in its primary purpose, which is to be an alternative to the Destructive Analyzer RnD, given how few people actually use it as an alternative. As the comments in this PR have shown, its primary usage has been complementary to facilitate powergaming.

The relics, while fun, never made sense from a roleplay/setting perspective. Their usage had always been niche and minimal. And frankly speaking the science department already has the most amount of fun (and powerful) content in the game, with the possible exception of botany. It has 4 sub-departments with their own unique gameplay and mechanics (5 if you include genetics). It doesn't need another one, especially if they don't even use it at a regular level.

**Comment by vcordie** [comment]
>code maintence perspective
I'm sorry, you don't appear to be the dedicated code janitor, nor do you appear to be a maintainer.


You appear to be writing unsubstantiated bullshit, would you like to turn on ALL CAPS?

**Comment by ohnopigeons** [comment]
This was based off a conversation I was a part of with an actual maintainer so I'd appreciate it if you didn't write unsubstantiated ad hominems right off the bat

**Comment by Tokiko1** [comment]
You could remove door attached assemblies with the same reasoning, but why would you?

**Comment by ohnopigeons** [comment]
If you mean https://github.com/tgstation/tgstation/pull/28188
It was literally added two weeks ago, is based off of IRL social interactions and contributes to emergent gameplay.

The experimentor fits none of these. It exists as an unused alternative to further research levels, whose primary purpose was to replace the original rnd for being unfun. As can be seen from the comments, no one even mentions or defends the experimentor's mechanics, only the end results (and how they can powergame with it).

**Comment by KorPhaeron** [comment]
I agree the experimentor is trash but I think we should wait and see how the RnD rework plays out before cutting out another chunk of the department

**Comment by Tokiko1** [comment]
I was refering to the ability of placing timers/signallers/etc assemblies on door wires. It's a mechanic that almost nobody uses either, though on a second thought it is probably not fair to compare those to the experimentor as it has a much wider range of potential applications and interesting situations it may create.

**Comment by ohnopigeons** [comment]
That's just the thing though, the experimentor itself is a half-finished rework. Regardless of how the new rework turns out the experimentor doesn't need to be in the code.

**Comment by KorPhaeron** [comment]
I agree it should go long term but I'd rather not have science players already in a foul mood by the time the RnD rework is being tested or it might influence its survival.

I know that sounds like stupid political shit but being careful about the timing of drama is a reality in a project like this

**Comment by KorPhaeron** [comment]
And its such an inconsequential, half finished, underpowered piece of junk it doesn't really hurt to let it sit in the meantime

**Comment by ohnopigeons** [comment]
If it's only delaying the inevitable, solely for political reasons, I can accept that.

**Comment by Cyberboss** [comment]
Then do this some other time

**Comment by FantasticFwoosh** [comment]
All the science mains come out of the woodwork to defend the experimenter.

**BUT DON'T MAKE OR CONTRIBUTE IDEAS TOWARDS PR'S TO FIX & EXPAND IT'S FUNCTION** 

There's no interest for the experimentor unless somebody does something, its literally a stale in-game feature by your own admission.

**Pull request closed without merging**
