### PR TITLE
Abductor Ships are now farther apart

### PR DESCRIPTION
**Pull request by loqoman**
:cl:
tweak: Abductor ships are now farther apart
/:cl:

Reasonable complaints about explosions in one abductor ship affecting the other abductor ships
PR fixing #28119

### CODE REVIEW

**Comment by KorPhaeron** [comment]
Kind of a waste of space. Invisible explosion blockers might work better

**Comment by lzimann** [comment]
Invisible walls are the way to go on this. No point in spreading them(also makes it worst for spectators).

**Comment by loqoman** [comment]
I didn't even know that existed, ill switch that up as soon as I can.

**Comment by lordpidey** [comment]
Actually, how would you feel about using the ruin system to spawn the ships?

**Comment by Cyberboss** [comment]
That would just make them accessible to the crew

**Comment by lordpidey** [comment]
Well, spawn the ships when you make a new abductor team.

If they're accessible when there are abductors, that seems reasonable.

**Comment by Armhulen** [comment]
Way too big for the scope of this PR

**Comment by loqoman** [comment]
@lordpidey @Cyberboss 

Thats wayyyyyyy above my pay grade. I just came here to move some boxes around

**Comment by loqoman** [comment]
Do explosion blockers already exist? If not, I could try my hand at coding them.

**Comment by lzimann** [comment]
Could just put some invulnerable walls(centcom walls) and edit their icon state. Might need to add a new empty icon state(or even edit their icon to be like space).

**Comment by loqoman** [comment]
@lzimann 
Ah, thanks.
If you can't tell this i'm still figuring this out.

**Comment by lzimann** [comment]
Don't worry, if you ever need any help, feel free to drop by on \#coderbus (at rizon.net).

**Comment by Cheridan** [comment]
Might still be a good idea since you can hear what's going on in the other ships which is kind of goofy

**Comment by loqoman** [comment]
Its so broken

**Pull request closed without merging**
