### PR TITLE
Removes pre-scanning

### PR DESCRIPTION
**Pull request by 4dplanner**
:cl:
del: You can no longer pre-scan in the cloner
/:cl:

Edited:

Scanning reduces the consequences of death to a far more minor level than is reasonable. Its effect on the game is to reduce tension by making scanned crewmembers immortal while cloning still stands, thus making the game generally more boring.

Scanning also opens up the issue of post-scan knowledge, which is especially problematic given tgstation's usual stance on RP knowledge restriction. Post-scan knowledge cuts down the variety of stealth antag playstyles, and as such makes the game more boring yet again.

It makes the game more boring, so it should be removed.

### CODE REVIEW

**Comment by Ziiro** [comment]
I know you're saying it's not, but this screams of some pretty serious "i ded". Trying to remove a pretty important feature used by big brain players and antags with the only real explanation of "Game is better off without it" is pretty laughable.

**Comment by improvedname** [comment]
I guess the new meta is pod blood bank

**Comment by Mark9013100** [comment]
Removing autocloning would be better, pre-scanning without phasics requires interaction with another player, which is better than silently barging in and slamming yourself in the scanner.

**Comment by 4dplanner** [comment]
"pretty important"

why is it important that death doesn't mean anything?

**Comment by 4dplanner** [comment]
> silently barging in and slamming yourself in the scanner.

also removed by this PR, great fun

**Comment by davethwave** [comment]
If you were going to do it, this way is not really good in my opinion. I would think that instead you would have to make it so that you can only use the prescan thing only if you upgrade x component so people would have a better chance at getting used to not getting prescanned.

**Comment by epochayur** [comment]
i ded :(

**Comment by Ziiro** [comment]
>why is it important that death doesn't mean anything?

You still lose all your gear. Or items you need for greentext. Death is pretty meaningful, even if you can get a new body.

**Comment by 4dplanner** [comment]
>Die as a sec officer

**Comment by OmegaShoots** [comment]
Sounds like someone died to an antag that scanned themself.

Ironic being that the feature attempting to be removed would have prevented that lmao

**Comment by yoyobatty** [comment]
Removed my comment because I told the truth?

**Comment by 4dplanner** [comment]
I big smart so I say I ded

**Comment by danhibiki** [comment]
Cloning dindu nuffin why you coming at it like that

They lose their gear and at worst they come back at severe damage that already bones them for some time. At worst your dealing with someone who set up an autocloner somewhere and is bringing themselves back. Why remove something that brings players back into the game under the pretense of a science/miner nerf?

**Comment by 4dplanner** [comment]
The purpose isn't to nerf science and mining, it's a happy side effect.

**Comment by WarRage333** [comment]
I DED and other not DED becuz they SCAN angery

**Comment by 4dplanner** [comment]
>  Next, most servers have a rule to forget the exact circumstances around death when cloning, so your 'immulsion' ruining thing is moot.

This is the tgstation github

**Comment by 4dplanner** [comment]
Also "he not like thing so he SALTY" big brain meme

**Comment by HideAndSeekLOGIC** [comment]
I did some research on that topic, and I've found no conclusive evidence one way or the other for /tg/ rules on cloning memories. Thus, I apologise for stating this as fact.

The reason for why I called this PR salty is because it has all the signs of a salty PR - lazy, badly written, removing a feature which can generate salt in unrobust players, "big brain meme", deleting comments which disagree with this PR, etc. If maybe you put a bit more thought into this, much fewer people would be calling this saltcode.

I also can't help but notice you didn't have any rebuttals to my other arguments.

**Comment by 4dplanner** [comment]
Your points are not worth responding to. You show an ignorance of the very server whose github you are posting on, and almost everything you say is nonsense. For example: I can't delete comments, I'm not a maintainer. I'm not going to respond to the rest of your points, and this isn't because they're too difficult to respond to, but just that they are dumb and aggressive.

**Comment by HideAndSeekLOGIC** [comment]
My point is, it benefits miners either equally or less than normal crewmembers. If you read what I wrote then you'd know why, but it looks like I'll have to repeat myself in slightly simpler terms.

Normal crew items are on station
Miner items are on lavaland

Normal crew rarely get gibbed
Miners very often simply disappear

Normal crew barely need starting equipment
Miners need a full set of gear

If a miner dies, autocloning isn't giving him the opportunity to go out, pick up their items and continue where they left off - it's giving them the chance of continuing the round, if only as an ordinary station dweller. Going back to lavaland from cloning should take no less than 10 minutes even if everything goes smoothly, and that's not accounting for the many ways miners can have their items permanently lost. I don't need to elaborate further, as anyone could probably put two and two together and realise that autocloning isn't a quicksave for miners.

With all the effort you're putting into this, why not do a rebuttal instead of continuing to play the 'ur argument dumb' card? If anything here is 'painful', it's watching you double down over and over by trying to insult me instead of actually trying to think.

**Comment by yoyobatty** [comment]
So basically you died by someone who took time to do planning ahead. Just make a private cloner.

**Comment by 4dplanner** [comment]
You're right, I am putting far too much effort into this. I've handled this PR badly. As such, I will delete all my previous responses and stick to the simple rule of not responding to anyone who has proven unwilling to debate this purely on its own merit without ignoring that I've stated multiple times I've never died or lost greentext as a result of autocloning.

**Comment by HideAndSeekLOGIC** [comment]
Making it _look_ like effort has been put into it would do well for starters

**Comment by Repukan** [comment]
Remove autocloning too

**Comment by PKPenguin321** [comment]
from the perspective of an antagonist who has to kill people who have scanned themselves in the cloner: 👎 
having to hurriedly sabotage the cloner before they can be revived is a rush and i strongly enjoy it

**Comment by 4dplanner** [comment]
> Remove autocloning too

I think I have, how could autocloning work without records?

**Comment by 4dplanner** [comment]
> having to hurriedly sabotage the cloner before they can be revived is a rush and i strongly enjoy it

That's a fair point, but having to route every scanner murder through one part of the station limits how different murder experiences can be. I personally don't think it's worth it overall, but that's a value judgement.

**Comment by Repukan** [comment]
@PKPenguin321 There's nothing fun or intuitive for a player to hunt down maint hidden autocloners set up by powergamers.

Frankly autocloning and records make death meaningless unless you lose important or exclusive equipment. There's no point in adding things that may add paranoia or further the broadness or depth of the combat system if dying will be an easy way out of interacting or dealing with such things.

Why take care of yourself and avoid fights when you can come back anyways? Why even care about internal damage and treating it when you can heal yourself faster by stabbing yourself and being cloned with the Mk 3 Autocloner produced by science ten minutes in?

**Comment by PKPenguin321** [comment]
>There's nothing fun or intuitive for a player to hunt down maint hidden autocloners set up by powergamers.

The only time I've had to do that was as part of the crew because an antag set it up. Whenever I'm antag the autocloner is always in genetics or just in the halls in public. Both can challenging to sabotage but it never feels unfair

**Comment by Jujumatic** [comment]
look at the thumbs up, look at the thumbs down. see that thumbs down? that's got more votes than the thumbs up. that means we don't want this saltcode cancer staining our beautiful spaghetticode. please fuck off thank you :)

**Comment by ninjanomnom** [comment]
Keep it respectful in here.

@Jujumatic Votes aren't an authority on what gets merged and there have been serious discussions among maintainers to do exactly this before. Personally I'd be in favor of this but this is a pretty serious change.

**Comment by JMoldy** [comment]
Pre-scans follow one of the important meta rules of SS13 robustness: being prepared can save your life. Most people don't even bother to get pre-scans the majority of the time. 
It's not something that can't be countered, in most cases just wipe the records if you want someone to not get cloned. The hardest one to stop is personal autocloners but they're a bit uncommon and usually built in specific areas anyway.

**Comment by subject217** [comment]
body control is the interesting part of keeping someone out of the game after they're dead as an antag. destroying a public use machine because you need to kill one guy who happens to be a powergamer and don't have genetics access isn't fun, it just makes the game more annoying for the other uninvolved people.

**Comment by Kawaii-Big-Boss** [comment]
I don't even disagree with this PR. If RnD did their jobs, autocloner abuse is very powerful and results in the clone coming out very fast and with pretty much no disabilities or cell damage. Saying "this is easy to abuse" is wholly unnecessary. Anything that ticks SciMed back a notch after "totally not virology" Nanites, the fuckup that was circuits as a whole, and how easy it is to abuse their systems to become god within seven minutes is a welcome change in my opinion.
Death mattering is an important part of SS13.

That being said, this probably isn't the way to do it and reeks of grudgecode. I can't exactly say if it is or isn't, but considering the huge wave of "i ded" PRs which have flooded into /tg/station and gotten merged despite everyone in the comments being against it, a change like this seems a lot like he just died to an antag or security officer who autocloned themselves. Especially because it's just a flat removal of the ability to pre-scan rather than any other alternatives to making death matter more. Lethal combat right now is awful, there's no reason to use a pistol over a taser. Something like that being addressed over an autocloner which has to first be set up in an area, upgraded, and so on would make more sense. Hell, even just making it so repeated clones have more disabilities or giving the cloner a soundloop so you can hear them running would make fighting autocloners less annoying, not to mention the guy who gets cloned loses all of their stuff to begin with so it's not like it 100% mitigates death, unless you're willing to put even more time into setting up a base/hiding shit around the station so you can get your gear back, or at least an I.D.

Hell, you could have even made the autocloner a different machine entirely, maybe ripped off from Goonstation, which is what a lot of coders love doing any way, and giving the cloner a biomatter requirement so cloning isn't free. Which is why this PR makes no sense to me. There's so many better ways to deal with autocloner abuse and instead you just choose for the laziest, quickest option of removing it entirely from the game. but who cares it's gonna get merged any way by oranges

**Comment by HideAndSeekLOGIC** [comment]
@subject217 it's possible to just delete records instead of nuking the entire machine. If the traitor has some amount of access (which they should generally get eventually), they can take that option and no-one would be the wiser.

**Comment by subject217** [comment]
You'll notice that I said "without Genetics access". I am aware that it is possible. It's also heavily inconvenient and basically never done unless you can do it easily and are trying to be stealthy.

**Comment by daklaj** [comment]
lmao autorespawn in a permadeath game
this should have been done years ago, kys casuals

**Comment by yoyobatty** [comment]
Who ever said this was a permadeath game? You're telling me this is the only way to revive? This just allows the crew to be cloned.

**Comment by 81Denton** [comment]
@HideAndSeekLOGIC You need head of staff access to delete records, IMO it is easier to just bomb/break the cloner.

**Comment by ATH1909** [comment]
> @HideAndSeekLOGIC You need head of staff access to delete records, IMO it is easier to just bomb/break the cloner.

Wait, really? I've never encountered this before.

**Comment by 81Denton** [comment]
https://github.com/tgstation/tgstation/blob/d7f8595cf9e8753a9c340d0ba80e64da95f1c641/code/game/machinery/computer/cloning.dm#L9

**Comment by GhostEcho** [comment]
Im not entirely against this, though if you're gonna use justification, a RP justification on /tg/ isn't really convincing anyone

**Comment by 4dplanner** [comment]
The reasons I gave in the current version of the PR are gameplay based, not RP based. The only reference to RP in there is pointing  out that another way of solving one of the problems, i.e. an RP restriction, is not viable on tg.

**Comment by 4dplanner** [comment]
Tg is also not noRP, so I think the role play aspects are worth considering  (if not as strongly )

**Comment by RogueSteampunker** [comment]
>Scanning reduces the consequences of death to a far more minor level than is reasonable. Its effect on the game is to reduce tension by making scanned crewmembers immortal while cloning still stands, thus making the game generally more boring.

It's purpose is to ensure the mass amount of easy gibbing options we have aren't complete no save permadeaths as long as you take the right precautions to circumvent that. Not to mention of course that a person's removal of that benefit is a single delete from someone who'd want them dead is a thing, so you knowww.

>Scanning also opens up the issue of post-scan knowledge, which is especially problematic given tgstation's usual stance on RP knowledge restriction. Post-scan knowledge cuts down the variety of stealth antag playstyles, and as such makes the game more boring yet again.

stealth antag playstyles that are borked by pre-scans would just be as borked by regular corpse scanning, though. No amount of cloning removal will stop the fact that you plunged a syringe of morphine into someone that was a tile away from you.

The entire thing just seems silly to remove on the basis of "oh, it makes things boring" when in reality 90 percent of it's use is to make sure someone just doesn't end up permanently dead cause they're in lavaland, or removed from the game permanently cause ez gibs.

**Comment by nervere** [comment]
This is a pointless removal, and it doesn't address the problem you're seeking to address.
A much better alternative would be removing autocloning.

**Comment by RandomMarine** [comment]
Instead of this, add a new machine where all clone records are sent to and stored. Stick it someplace semi-secure like the CMO's office.

Antags can disable the machine to kill pre-scanning.
Protags can counter an antag's hidden autocloner by deleting their record from this machine.
Also stops the current 'screwdriver cloning console to instantly delete all records' nonsense.

Introduce counterplay instead of nixing features.

**Comment by 4dplanner** [comment]
> This is a pointless removal, and it doesn't address the problem you're seeking to address.
> A much better alternative would be removing autocloning.

I don't get how you can say this doesn't address the problem, and yet also say removing autocloning would. Removing scanning removes autocloning.

**Comment by 4dplanner** [comment]
> Introduce counterplay instead of nixing features.
Having features isn't immediately a good thing

**Comment by 4dplanner** [comment]
> > Scanning reduces the consequences of death to a far more minor level than is reasonable. Its effect on the game is to reduce tension by making scanned crewmembers immortal while cloning still stands, thus making the game generally more boring.
> 
> It's purpose is to ensure the mass amount of easy gibbing options we have aren't complete no save permadeaths as long as you take the right precautions to circumvent that. Not to mention of course that a person's removal of that benefit is a single delete from someone who'd want them dead is a thing, so you knowww.
> 
> > Scanning also opens up the issue of 
> stealth antag playstyles that are borked by pre-scans would just be as borked by regular corpse scanning, though. No amount of cloning removal will stop the fact that you plunged a syringe of morphine into someone that was a tile away from you.

Hiding bodes is a more fun gameplay mechanic than smashing the cloner.

**Comment by 4dplanner** [comment]
As to gibbing, just clone the brain

**Comment by 4dplanner** [comment]
The point is removing this feature instantly adds more gameplay in the form of hunting for bodies/brains. Adding counterpla is less fun than that.

**Comment by Barhandar** [comment]
Your ided makes autocloner upgrade, as well as stuff like getting DNA from the cloner's entries, useless. Additionally it removes any usefulness from backup cloners due to being unable to actually _use_ them.
>The point is removing this feature instantly adds more gameplay in the form of hunting for bodies/brains. 

It doesn't because people already hunt for bodies/brains since _people don't scan themselves in_.

Also, learn to quote in a single comment already.
>I don't get how you can say this doesn't address the problem, and yet also say removing autocloning would. 

Because prescan without autocloning still lets the doctor visit the thing and hit "clone". **That you don't realize this is a pretty strong indicator that you are not fit to make this kind of balance changes.**

**Comment by ninjanomnom** [comment]
Code is code, we don't care about who prs the code and anyone can pr any change. Maintainers make the decision on whether something is merged. No one is "unfit" to make changes.

**Comment by 4dplanner** [comment]
> Your ided 
> Because prescan without autocloning still lets the doctor visit the thing and hit "clone". **That you don't realize this, is a pretty strong indicator that you are not fit to make this kind of balance changes.**

I'll phrase thus more simply: if removing autocloning solves the problem, so does this PR.  THIS IS BECAUSE THIS PR REMOVES AUTOCLONING. whether or not other problems are added is irrelevant to the point I made.

**Comment by 4dplanner** [comment]
Do you understand now?

**Comment by 4dplanner** [comment]
If the complant is that without removing cloning completely the problem isn't "solved" but merely ameliorated, who cares

**Comment by RogueSteampunker** [comment]
>Hiding bodes is a more fun gameplay mechanic than smashing the cloner.

not fun for anyone who isn't a traitor, since it's basically maint cloner 2: electric boogaloo

>The point is removing this feature instantly adds more gameplay in the form of hunting for bodies/brains. Adding counterplay is less fun than that.

Not if that brain has been tossed out an airlock, cause fuck having difficulty getting rid of someone permanently (^:

>I'll phrase thus more simply: if removing autocloning solves the problem, so does this PR. THIS IS BECAUSE THIS PR REMOVES AUTOCLONING. whether or not other problems are added is irrelevant to the point I made.

"even if my pr has flaws, you can't call me out on them, so fuck you."

**Comment by 4dplanner** [comment]
> "even if my pr has flaws, you can't call me out on them, so fuck you."

Please consider the context, this is a really dumb. I was saying that other flaws are irrelevant to one specific comment, i.e. "doesn't even address the problem".

**Comment by venomsnak** [comment]
seems like a great way to keep people out of rounds and reduce the overall player base.

**Comment by adamkad1** [comment]
i know right? i barely ever prescan myself, but this guy seems really salty to me, hope it wont be fullmerged

**Comment by JMoldy** [comment]
For reference, here's a portion of the list of ways that you can die that you can't be cloned from without a pre-scan: falling in a chasm, falling in lava, having your brain removed and cooked, being cremated, touching any of the engines, xenomorph chestbursting, being eaten
being properly spaced is also pretty hard to do because getting a body back is a serious pain but not completely impossible (I've recovered a few bodies from spacing)

There are a lot of different ways that you could even fix autocloning to be less powerful while still keeping it relevant. A few examples would be having it interface with the suit sensor console, adding an implanter to the autocloner that senses user death, adding a delay to the autoclone function (which would be nice even without). Having it interact with the suit sensors console might even make people listen to the CMO screeching about it every round, and gives an opportunity for a stealthily murdering traitor an opportunity to prevent autocloning without making it easier to murderbone around the hallways

**Comment by Cyprex** [comment]
If it hasn't been said already, from what I've heard /tg/ policy is that you remember everything up to and including your death when getting cloned, but you may not use any information you learned while you were a ghost or from deadchat. Or in short: You always remember everything that happened while you were alive. Could an admin confirm this?

**Comment by Bawhoppen** [comment]
@Cyprex I'm not an admin, but that's definitely been the policy for as long as /tg/station has been a thing.

**Comment by subject217** [comment]
yep that's always been the cloning policy

**Comment by rustledjimm** [comment]
Personally I would say just remove autocloning.

**Comment by Arianya** [comment]
This is one of those "pulling off the bandaid" changes that is always going to be unpopular even if its ultimately better for the game as a whole, IMO.

That said, pre-scanning existed before autocloning and in my experience was never really an issue, so it'd probably be best to remove autocloning as opposed to pre-scanning, but I'm not precious on that point.

**Comment by rustledjimm** [comment]
Removing autocloning was Naksu's dying wish and we should respect that.

Remove autocloning.

**Comment by anconfuzedrock** [comment]
We're all too eager to add things like ied spears, clock cult, lavaland, autocloning itself, and overthrow. It shouldn't be this hard to remove something that goes so blatantly against the game's philosophy just because it's a convenience to some. It doesn't matter if the pr is "I ded" or not. if someone added the instagib rifle to traitors for 1tc, the I ded pr that removed them would still be a good pr. Though the motive is questionable, it isn't wrong, and the act itself is good.

Or as I would've said a year ago and I am saying in my head:

H U G   B O X

**Comment by 4dplanner** [comment]
As to the "remove autocloning, not pre-scanning" point: personally, I feel that pre-scanning is less bad than autocloning but still isn't actually a positive thing to have in the game for lesser versions of the same reasons. It also becomes a terrible version of autocloning if medics check the cloning machine every now and then.

**Comment by 4dplanner** [comment]
Though there are obvious workarounds as of now, such as

**Comment by 4dplanner** [comment]
I feel the last message was poorly phrased, so in essence: pre-scanning isn't too bad, it doesn't cause the same huge issues as proper autocloning does, but it is bad for the same reasons.

**Comment by Magikarpet** [comment]
Rock, hugbox tends to be a bad argument because it can go both ways. You can argue that being too bad to destroy/sabotage the cloner is the fault of the traitor, and that we're needlessly buffing traitors because people are bad and lazy.

I think autocloning itself is poorly designed, and while i do think losing all your items is far worse than being dead at times, the prevalence of easy body destruction methods has made it kinda silly to remove. Any naked assistant with no items can already permanently destroy a body, and any sharp weapon can be used to extract a brain rendering a body impossible to clone unless botany is active. 

Autocloning also gives traitors a genuine reason to target medical instead of chucking bodies into space/destroying them in 10 seconds of effort much like how telecomms, the RnD servers, the cyborg destruction console, and atmospherics are big targets for a lot of antagonists. Unless someone finds your bodies now you can just straight up ignore medical without giving much of a shit.

[spoiler]EMP kits are 2 telecrystals and you can spam them in medical maintenance on most maps to permanently kill someone in the cloner and destroy it in one click thank me later[/spoiler]

**Comment by 4dplanner** [comment]
>Any naked assistant with no items can already permanently destroy a body, and any sharp weapon can be used to extract a brain rendering a body impossible to clone unless botany is active.

Why is this a bad thing? If someone's in a position to dispose of your body, then you have been defeated. Why shouldn't you take the consequences? Ordinary cloning serves the useful purpose of reducing the damage of driveby murderboners, but the fact that you can easily stop someone from respawning is a feature, not a bug.

**Comment by carshalash** [comment]
Seems to meme on miners pretty bad, not being able to see them on suit sensors is already pretty annoying.

**Comment by snekibreki** [comment]
this is the ultimate "i died" pull request

**Comment by Magikarpet** [comment]
Death has consequences (Losing all of the things on your body, losing time, and likely having to spend more time to reclaim basics like your ID) and prescanning still takes a few minutes to clone them. If medical isn't too efficient the time it takes for someone to obtain their basics(clothing, ID) can hit 10 minutes(for them to actually recognize a prescan, some rounds i see autoscan turned off despite there being scanned players who are dead).

Prioritize medical as a target if you want to go on a murder rampage. If you don't prioritize chemistry as an antagonist and they create chem bombs to kill you should chemistry be nerfed? If mining ends up finding a meat hook and they kill you and end your murder spree due to you not expecting it is it mining being too powerful? Should tasers be nerfed because you got tased and died one round as you started murderboning? If you leave telecomms up is it science/medical's fault someone was cloned or spotted you murdering someone and screamed you were a traitor? I don't see some consistent conspiracy where over a third of the station gets prescanned and cloned the second they die by powergaming doctors. An important thing as an antagonist is to figure out what department  you want to sabotage or murder if you're murderboning to prevent them from getting you with their job items.

I hate using the phrase but unironically git gud and adapt, traitors have multiple tools to deal with everything listed especially and including cloning. If other antagonists concern you, changelings can completely disguise themselves as another person and aoe emp the cloner, wizards can straight up blow up cloning and massacre people inside, ninjas can destroy APCs and emag the cloner with their sword, revolutionaries can work together and swarm medical to destroy the cloner, nuke ops have bombs and EMPs, while cultist soulstoning prevents autocloning and forces them into the stone.

it's also just as easy to ruin a clone without ever entering medical for subtle options. A few examples as a hint: drop an emp grenade in the maintenance tunnel/rooms beside cloning, set a bomb by cloning to vent and destroy the cloner, sabotage power to medical earlier in the round by cutting wires in maint, flood plasma into medical via distro, or subvert the AI/a silicon so that they shut off the apc and delete records


This is just a salt reaction but one change too hard in one direction will make this less popular and more imbalanced than if you dealt with dismemberment/shuttle gibbing/sources of gibbing to counteract methods of body destruction as counter-balance. Unless this is a complete salt pr to remove something that you lost to.

**Comment by Mark9013100** [comment]
>>silently barging in and slamming yourself in the scanner.

>also removed by this PR, great fun

Except the problem I had was explicitly autocloning, not pre-scanning in it's entirety.

**Comment by elyina** [comment]
Lets face it pals. Autocloning is cancerous to the game. I say that as someone that abuses the fuck of it while mining/fighting megafauna, and during antag rounds. Yeah, it's fun to have, but it's bad for the game.  It's sort of like playing with a gameshark. You shouldn't be able to rush headlong into any dangerous situation you want without fear because of your free infinite extra lives. That's not what SS13 is about. It's gonna sting at first, but this is for the greater good.

**Comment by duckay** [comment]
That's not the point of this, it's that we're removing an option to let a player have a second chance for a reason I still don't know to this very day.

There are several factors in getting pre-scans, such as APC power and use of your storage within the cloner and if you are not being autocloned, you rely on medical to clone you, everything hinges on medical for second chances, if not research for autocloning, if you are a traitor during a moment where you killed someone in say maintenance and not go for cloning(or murderbone really early into the game), don't be surprised when you are faced with a failure.

**Comment by xeroxemnas** [comment]
This is an absolutely cancerous pr that reeks of anger. It's not even that hard to sabotage the cloner as an antag anyway. I once just emagged the fucking thing and gibbed anyone trying to clone themselves. Easy as fuck. OP is just extremely bad at the game.

**Comment by ExcessiveUseOfCobblestone** [comment]
Personally, I would rather see cloning in the tech tree past the reconstruction surgery so that "cloning" people via defib/reconstruction is the common method and prioritizing the medical "branch" (instead of say le epic mining meta) has value.

Would also be nice to, should autocloning be kept, to have a restrictive amount of records the console can hold at once. That way it's not a guaranteed jail-free card unless you make a private one.

**Comment by tortellinitony** [comment]
Gross

**Comment by HideAndSeekLOGIC** [comment]
I love how you did the good ol' "LALALALALA I CAN'T HEAR YOU" after I gave you two relatively obvious arguments for why this PR won't accomplish what you want it to accomplish. You, sir, are a little salty bitch who I have completely lost any and all respect for - you brush away any arguments which try to offer alternatives or counterpoints (aka everything almost everyone else has said), you delete your own comments when you realise you're a fucking dumbass, you act like you know everything and you pretend your opinion is the only one that matters.

You are the final boss of the salt PR. Fuck you and others who think your behaviour is normal. I'm looking forward to the day you cunts get tired of this and tg can finally be fun.

**Comment by optimumtact** [comment]
Right it's pretty obvious the answer is just to remove auto cloning

(Later I will remove all cloning but you're not ready for that yet)

**Comment by Cyberboss** [comment]
Talked it over, we're just gonna kill this sooner rather than later

**Pull request merged**
