### PR TITLE
Repaths knives to not all be children of the kitchen knife.

### PR DESCRIPTION
**Pull request by itseasytosee**
## About The Pull Request
Basically makes the code less dumb, took a long time. I worked hard to make sure there were no unintended effects (minus the fact you can no longer get spoons from the experimentor). No player-facing effects.

## Why It's Good For The Game
I thought it looked weird that all cultist and combat knives were subtypes of the kitchen knives. But hey maybe I just wasted my time

### CODE REVIEW

**Comment by itseasytosee** [comment]
If I did this right there are ZERO gameplay consequences.

**Comment by Sealed101** [comment]
https://github.com/tgstation/tgstation/blob/6c01cc2c010c8dc15c5500434ae8e55261511781/code/modules/research/experimentor.dm#L62

**Comment by LemonInTheDark** [comment]
no please come back

**Comment by LemonInTheDark** [comment]
> 
> 
> this is a huge nerf to experimentor's irradiate reward pool

Huge and experimentor are oxymorons

**Comment by Sealed101** [comment]
> > this is a huge nerf to experimentor's irradiate reward pool
> 
> Huge and experimentor are oxymorons

please let me enjoy rnd content

**Comment by itseasytosee** [comment]
I don't know what's screwing up the checks.

**Comment by LFSpirits** [comment]
> @Sealed101 explain how this affects the experimentor?

The experimentor's irradiate option has a chance when it malfunctions to change the inserted item to a random item of a few select categories. One of these being kitchen items. Which involves knives. You can shove in some random junk and possibly get a rainbow knife, envy's knife, cyborg knife, etc. Granted, it's a low chance considering what all there is to roll from.

**Comment by ATH1909** [comment]
> > this is unironically a huge balance change for heretics, who need to use knife subtypes to create their heretic blades (which will often need to be replaced if you're shattering them, btw).
> > this also nerfs pAI cleanbots, although that's less of a big deal.
> 
> no its not did you read the code

ooooooooooooooooooooooooooh

**Comment by itseasytosee** [comment]
That experimentor issue is a real odd problem huh. I have no clue about solutions.

**Comment by itseasytosee** [comment]
That's the simplest solution, but it would still be a change, because you won't be able to get spoons and stuff. Ill look into it.

**Review by Maurukas — APPROVED** [review]
Mapping is a simple path replacement and looks fine.
I'll leave it to the maintainers to review the mechanical and heretic related issues this causes.

**Review by LemonInTheDark — CHANGES_REQUESTED** [review]

**Comment by LemonInTheDark** [comment]
Keep an eye on issue reports in case we missed something yeah?

**Pull request merged**
