### PR TITLE
Fixes all remaining addtimers missed

### PR DESCRIPTION
**Pull request by optimumtact**
Utilising some gnarly grep and sed hacking

edit:for own reference

    git grep -l -e 'addtimer' --and -e 'FALSE' | xargs sed -i 's/addtimer(\([^,]\+\),\([^,]\+\),\([^,]\+\), \?FALSE \?,\(.*\))/addtimer(\1,\2,\3, TIMER_NORMAL,\4)/'

### CODE REVIEW

**Comment by optimumtact** [comment]
@Cyberboss did you rely on the github search?

**Comment by optimumtact** [comment]
@tgstation/commit-access can't update the server till this is merged/test merged without having major breakages

**Comment by Iamgoofball** [comment]
# TWENTY-FOUR HOURS

**Comment by optimumtact** [comment]
Unlike you I can tag my pr's with the red tag

**Comment by Cyberboss** [comment]
REEEEE I GIT GREPPED WHY ARE THERE SO MANY

**Pull request merged**
