### PR TITLE
Revert "Gives gangs new surplus rifle, mounted machine gun, and more"

### PR DESCRIPTION
**Pull request by Cyberboss**
Reverts tgstation/tgstation#27195

Closes #27584

This is too much shitcode for me

### CODE REVIEW

**Comment by kevinz000** [comment]
aAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA HE DID PIXEL PROJECTILES WRONG

**Comment by Robustin** [comment]
What are you ranting about Kev  it's projectile code that dozens of other systems use.

**Comment by kevinz000** [comment]
Closes #27584

**Comment by kevinz000** [comment]
@Robustin you use preparePixelProjectile to you know, prepare the pixel projectiles, NOT set the targets and offsets manually as that doesn't actually do what you want!

**Comment by kevinz000** [comment]
Ok lets explain it this way when you set x_o and y_o you made it target the THREE SQUARES INFRONT OF THE GUN IF YOU CLICK RIGHT INFRONT OF YOU GIVING YOU A 180 DEGREE ANGLE.
Far away it's the same three squares but it's MUCH further away so the angle will be TINY and you can effectively GGNORE people ridiculously easy with that!

**Comment by Robustin** [comment]
>Kev thinks two 45 degree angles add up to 180 degrees.

Fuck off retard.

**Comment by kevinz000** [comment]
@Robustin ASSUMING THE BUG REPORT IS TRUE ABOUT BEING ABLE TO CLICK RIGHT INFRONT OF YOU
user clicks one tile directly away
targets_from x y = 100, 100
target x y = 100, 101
x y target offsets can be 0,1 1,1 -1,1 1,2 -1,2 0,2 -1,1 -1,-1 -1, 0
-1,1 and -1,-1 is a 180 arc around the gun
who's the retard now

**Comment by Robustin** [comment]
Go revert megafauna and all the other non pixel projectiles then, multiple maintainers suggested not using PP, so shitting your pants because REEEEEE this gun doesn't perform exactly like I want it too!!!!!! When I've repeatedly posted the projectile code for this gun with you around in IRC just reeks of shitposting.

**Comment by Robustin** [comment]
>who's the retard now

I rest my case

**Comment by kevinz000** [comment]
@Robustin this is the only case where xo and yo are set by the player and is being used to control your gun's spread.

**Comment by PKPenguin321** [comment]
angery

**Pull request closed without merging**
