### PR TITLE
Cytology 1.1: autoresampler vats

### PR DESCRIPTION
**Pull request by Krysonism**
## About The Pull Request
This PR updates the growing vat to allow it regrow the sample upon completion.

Resampling can be toggled by interacting with it with an empty hand.

Emagging the vat permanently locks the resampling toggle.

It also buffs the volume of the vat from 200u to 300u and gives it a new sprite.

bild

## Why It's Good For The Game

Allowing elaborate and interesting cytology setups was always a goal of mine and while plumbing allowed for that on the reagent handling side, it was limited by the fact that you manually had to add more sample after each completed run. The resampler when combined with the existing plumbing and conveyor mechanics should allow us to build some interesting set ups.

The resampler can also be used for nefarious purposes such as setting up vat that spawns bears in a public area.

Previously, it was easy to accidentally overfill your vat and not have room for all the reagents you need. This was very unfun since you'd then have to drain vat and lose a lot of precious time and resources, the volume increase should alleviate that.

The new sprite also helps make the vat less of an eyesore.

## Changelog

:cl:
balance: Growing vats can now be set to regrow the sample upon completion.
balance: Increased the volume of growing vats from 200 to 300u.
/:cl:

### CODE REVIEW

**Review by tralezab — CHANGES_REQUESTED** [review]
T

**Comment by tralezab** [comment]
(i'll give this a full review later)

**Comment by Zytolg** [comment]
I'm going to have to murder some xenobiology machines soon. I can taste it now...

**Review by tralezab — CHANGES_REQUESTED** [review]
some complaints about the usage of signals, quirky overlay stuff, and some misc things. otherwise looks good

**Review by Twaticus — APPROVED** [review]

**Review by tralezab — APPROVED** [review]

**Pull request merged**
