### PR TITLE
Experimental Cobbisection [150+ Hours and Ready]

### PR DESCRIPTION
**Pull request by ExcessiveUseOfCobblestone**
### Dissection (Prev Experimental Dissection) Is Now Roundstart
**Goal**:give medbay a task they can do outside of normal healing on the off chance they're overstaffed and/or are in need of work. 

### Dissection (Prev Experimental Dissection) Is Now Tiered
**Goal**: I'm still not seeing competition in the medical tree that I'd like to see. Now that science benefits from going to this tree, I expect it to be a prominent if not the main pick.

**Goal**: Provide Medical bargaining power with Science. Want you cool gear bros? Better indulge us a bit if you want us to farm corpses.

**NOTE:** You will NOT be punished for doing low tiered surgeries then unlocking further tiers. It adjusts your rewards depending on if the body has been experimented on before and gives you the difference, it will **not** block you from doing the surgery entirely.

#### Repeatability
**Goal**: Make it less balanced around the all/nothing mechanic and more with rewarding constantly running the surgery.

Failing the surgery will give you a pity amount (1%, something slightly more than none in grand scheme) but more importantly will NOT add the trait that disables you from using that body for the surgery again.

#### Silicons can now perform dissection
Since It's not All/Nothing I decided to allow silicons to be able to help out. This is the first (and only) surgery that they can potentially fail.

#### Nerfs (yikes!)
Needed to nerf it to compensate for the fact that it was now roundstart. The hardest one was pointgain. I decided to mega nerf it so tiered would be desired. This was also a result in the shift of balance off the RNG and more on the repeatability.

### Dissection Can Now Be Performed on ANY LIVING MOB
**Goal:** Cooperation between Mining (returning Mobs) and Medbay (turning these mobs into points)

The foundation is really lacking imo since I didn't want to dance around with numbers in this PR. Currently all mobs that aren't human and aren't explicitly listed in `check_value` are 300 points per surgery.

I hope you guys can add more mobs to the pool with better rewards (imagine dissecting the dragon for science!)

#### Step Configuration Edit
Needed to change just for repeatability in the dissect step (didn't like the end step being the proceeding step).

I replaced the incision step with a post-dissection clamp step to keep the theme of scalpel > hemo (dissection uses scalpel)

#### Implement Changes / Probability Effects
Rewards using the researched tools (further integrates medsci coop), lowers standard gear to appropriately balance higher tiers.

#### Prices are Define Bound
Everything is relative to a single number via calculating off a define instead of independent values. Balance discussion shifts from "Is X number fair" to a more tangible "Is this mob worth X times the amount of a normal human". If everything is strong/low we can just edit a single number!

## Changelog
:cl: Cobby x Medbay
balance: (Experimental) Dissection is now roundstart.
balance: (Experimental) Dissection is now tiered and give higher point outputs than their predecessors.
add: All living mobs with corpses can be dissected.
code: Attention, all ss13 gamers! I need YOUR help adding mobs to the pool so they don't get the lame 60% of normal human pricing! You can dissect DRAGONS FOR CRY IT OUT LOUD!
balance: You are NOT punished for doing the lower tier surgeries then unlocking higher ones!
add: Borgs can perform dissection but they are not 100% successful.
tweak: Shifts balance of dissection surgery towards spammability vs. rng mechanic.
balance: All point rewards are severely nerfed to promote doing this multiple times (since it's now available from the getgo).
tweak: If you fail the dissection step, you get a pity reward (1% credits) and can repeat the step until you successfully dissect the being.
tweak: Lowered probabilty of success on default tools, increased probability for researched tools.
tweak: removed 2nd incision step, added clamp step post dissection (repeatability purposes).
/:cl:

### CODE REVIEW

**Comment by ExcessiveUseOfCobblestone** [comment]
Conflicts partially with #44819

**Comment by GuyonBroadway** [comment]
Give spiders a somewhat higher point value so xenobiospiders have a use besides "go fugg sdayshon :DDDDD"

**Comment by Dawson1917** [comment]
give ashdragons like 10k points when dissected, on par with a single anomaly core. if you're chad enough to kill an ash drake and haul its ass up to the station before the 40 minute mark where all research is done then you deserve the points. clearly only for bragging rights

**Comment by Tlaltecuhtli** [comment]
dissecting antags should give more points

**Comment by XDTM** [comment]
Kinda feels like failing has no consequence now though

**Comment by fludd12** [comment]
I feel that failure should still have a consequence, but also not make the body completely worthless - maybe reduce the total output on a success by each failure (x75%? It's worth balancing.)

**Comment by drderp3635** [comment]
I like the abducter one, but usually whenever you have abducter tech you are already finished with r&d and dont need more points. Might I suggest being able to do these surgeries for the same value of credits?

**Comment by Nabski89** [comment]
When are we going to be able to build frankenstiens out of base body parts and toss a brain into it! The anti-dissection.

**Comment by ExcessiveUseOfCobblestone** [comment]
So it's 12.5 seconds assuming normal circumstances.

12.5/60/90 = 0.002 or 0.2%

This means that for every 5 failures you have effectively wasted 1% of your total round time assuming 90 min rounds. Now tack on steps pre dissection, steps post dissection, switching bodies out on the optable (or risk an even higher fail chance), and then repeating the same surgery once you get the upgrades and it becomes very clear that while it might not have a downside explicitly put in code, there's a consistent cost to doing this regardless of success/failure that I think justifies my light-handedness towards failing the singular step.

Also to be frank i'd be pissed off if I failed 5 times and now the body is effectively useless, which is why I really would prefer the balance be around the repeatability moreso than a punishing mechanic for trying to help the station.

**Comment by XDTM** [comment]
Personally I think a mechanic that either passes or fails then prevents further attempts is less frustrating; once you're done, you're done, for better or worse.
You can still interact with the system by using surgery helpers like sterilizine, or you could even replace that with a multi-tier system that could range from no points to extra points accounting for situational bonuses (sentient, still alive, undamaged, mutated etc.)

Having a repeat-till-it-works system forces the surgeon to keep repeating the procedure if they want optimal results; it is an effective gating method like you said, but very unfun for the surgeon.

**Comment by ExcessiveUseOfCobblestone** [comment]
The probability in a normal circumstance is 45, and that's not including sterilizine. You shouldn't be failing a bunch of times consecutively unless RNG is really just hecking you over.

My point was more that the "punishment" for doing this, fail or pass, is that it preoccupies you. For a medical doctor, the surgery has an inherit downside in that you can't heal while you're playing with the insides of dead bodies. 

That said, I also tried to consider the situation where someone was a dedicated body churner hence why points are lower. Probably can be boosted after some testing since there's also a dead person bottleneck unless you're working with botany or xenobio or cargo.

**Comment by ExcessiveUseOfCobblestone** [comment]
> 
> 
> I like the abducter one, but usually whenever you have abducter tech you are already finished with r&d and dont need more points. Might I suggest being able to do these surgeries for the same value of credits?

I'd rather that be handled as a generic rnd mechanic more than a direct product of this surgery.

**Comment by XDTM** [comment]
Another idea would be making the surgery 100% reliable, but with varying point gain, again based on factors relating to how scientifically interesting is the corpse.

Wasting time due to rng is really unfun, as any viro or xenobio main could tell you, and i think we should avoid adding anything like that again if possible, even if it's a 50/50.

**Comment by ExcessiveUseOfCobblestone** [comment]
tbh I don't want to rebalance it again in the scope of the PR but I'd be okay with that.

Maybe a bonus for unique organs and stuff sounds really cool.

**Comment by CPTANT** [comment]
This PR made me realize, the surgical arm implant is actually the best tier tools available, how unintuitive since they look exactly the same like regular tools.

**Comment by ExcessiveUseOfCobblestone** [comment]
based, ill fix this 2nite

**Comment by CPTANT** [comment]
The functionality for other mobs is cool, but otherwise this is just a nerf to dissecting.

**Comment by ExcessiveUseOfCobblestone** [comment]
I don't see how it's an overall nerf.

### Nerfs
1. Lower Point Output per body (Huge Nerf)
2. Lower Probabilities if not using advanced tools(Medium Nerf/ Huge if Buff 2 didn't exist)
3. Lower Failure Compensation (Medium Nerf)

### Buffs
1. Roundstart vs. Experimental Tech (huge buff)
2. Failing does not deny success points (huge buff)
2a. The step is repeatable so if you fail you can keep doing the step vs. having to restart the surgery. (QoL/Minor Buff)
3. SurgeryArm improves the probability better than pre-nerf (minor buff)
4. All Mobs can be dissected (huge buff)
5. Can research higher point outputs (minor mitigation to nerf 1) and use bodies already dissected on (minor buff)

**Comment by CPTANT** [comment]
>Roundstart vs. Experimental Tech (huge buff)

It was already made roundstart recently

>Failing does not deny success points (huge buff)

success chance was already 80% with sterilizine (And maybe even high mixed in with ethanol?)

**Comment by ExcessiveUseOfCobblestone** [comment]
Yeah forgot about that even though I just had to fix conflicts from it >.>

Regarding failure, that's still a 1/5 chance to fail and not be able to get nearly as much points as possible. It's entirely possible to have lost 8000 points based on RNG if you were finally able to get the pesky alien queen even fully decked out.

Forgot to mention borgs can do the surgery as well now too which is another buff.

I guess i'll concede it's an overall nerf numbers wise, but I think expanding out the applications in which you can perform the surgery as well as shifting away from the all/nothing makes it overall stronger than previously.

**Comment by GLACoding** [comment]
500 Points for starters is incredibly low, a basic tech level costs around 2500. Current dissection grants around 2000 (with a 1/5 failure which only grants 200 points, which can be averaged to 1640 per dissection).
The BEST dissection, which is a **10000** point investment, only grants 1500 per human, lower then the shift-start average we have right now.

Currently, medical can work their way up to high level surgeries and other medical tech because of this 1640 point income.
This change means shift start medical barely makes a mark in sciences income which will probably relegate dissection to the mid-game or later, as that's the only point science will have finished researching their own stuff to spend points on higher level medical tech. At which point medicals got little incentive to keep working for points if they've already got their tech.


> Can research higher point outputs (minor mitigation to nerf 1) and use bodies already dissected on (minor buff)

Being able to reprocess corpses doesn't alleviate this.
If an MD dissected a bunch of corpses from the morgue/genetics then later managed to convince R&D to get the best dissection tech, they now need to reprocess ALL their corpses they just went through. Doubling (or even tripling if they used advanced for whatever reason) their workload.
Its just a waste of time to process them at the start if the points are so low and you'll need to dissect them again anyway.


> Failing does not deny success points (huge buff)

The "all or nothing" we have now works, you either get the points or don't, then you can dump the corpse and go hunting for more. As opposed to sitting in a surgery room reprocessing over and over again. Which you'll need to do with the scalpel now only having a 40% chance to work.

This change just makes early game dissection way too painful and pointless, to pave the way for later game dissection which costs so much. science wont buy it. I'd prefer keeping medical able to pay up for their tech.

**Comment by GLACoding** [comment]
On the other hand I really do like the mob corpse change, but I don't feel like its going to be a huge buff as you stated because:

Miners (the main source of xenofauna) don't have much incentive to go through the hassle of dragging corpses over to surgery to be dissected, they wont be able to closet stack corpses as they would be busy dragging an ore box.
They **do** have a lot of incentive to butcher them for diamonds or hide to strengthen themselves.

The dragon you mentioned is more likely to be butchered there and then for hide components rather then dragged all the way to surgery for a dissection, especially if they have to wait for a re-dissection due to low level tech.

This might create a job role for MD's to go down to lavaland and grab specimens for dissection, which is interesting, but I would point out this feels like more of a science thing than medical.
This isn't really a flaw, just something I thought I'd point out.

**Comment by GLACoding** [comment]
> Regarding` failure, that's still a 1/5 chance to fail and not be able to get nearly as much points as possible. It's entirely possible to have lost 8000 points based on RNG if you were finally able to get the pesky alien queen even fully decked out.

Actually you can use bacchus or honey to guarantee success, which you should probably be doing if you get a high value target.

**Comment by ExcessiveUseOfCobblestone** [comment]
I've changed the adjustment to reward doing the earlier surgeries.

For humans, this means you can get 1500 for doing advanced but if you managed to do the earlier surgery (or do it off the optable i guess) you can get an extra 500 for total 2000. Previously this would mean just 1500.

Whatever it is right now i'm going to have that nerfed. 1 body should not be equaling 1 lower level tech roundstart.

**Comment by Angustmeta** [comment]
I could not find dissection last round on Terry, ID 112733. Updated according to changelog.

**Pull request merged**
