### PR TITLE
Converts Efficiency Station to tgm 2: Electric boogaloo

### PR DESCRIPTION
**Pull request by WJohn**
Except not really because steelpoint is a thief and did it before me but this apparently fixes something??

### CODE REVIEW

**Comment by optimumtact** [comment]
Are you sure you merged correctly? There are some strange things in the diff there.

Did you add files?

**Comment by WJohn** [comment]
No no, steelpoint already converted to tgm.

Also, this new file type is super prone to bloated line difs because of the readability changes. It now shows everything that's on a tile over the course of multiple lines, vertically, instead of horizontally. Some minor changes will give you huge line bloat.

**Comment by RemieRichards** [comment]
@WJohn yes, thats -the entire point of the format-
More lines == less chance two people will touch the same line == less map conflicts.

**Comment by optimumtact** [comment]
yes but why does wjohn have changes here, what has he done?

**Comment by WJohn** [comment]
Oh, I also added generic landmarks. I thought I pointed this out in the first PR, maybe I forgot.

**Pull request closed without merging**
