### PR TITLE
Nerfs Cigarettes

### PR DESCRIPTION
**Pull request by Tacolizard**
🌮 town
:cl:
:tweak: cig smoke time reduced from 300 to 150
/:cl:

sure in real life it takes like 5 minutes but in-game things are sped up a huge amount. Cigs shouldnt last so long.

### CODE REVIEW

**Comment by optimumtact** [comment]
Tacoliz going back on that ban list smh

**Comment by Tacolizard** [comment]
@optimumtact what did i do

**Comment by optimumtact** [comment]
I have no idea, ask kor

**Comment by KorPhaeron** [comment]
Feature freeze

**Comment by KorPhaeron** [comment]
I don't think think such an irrelevant item needs nerfs

**Pull request closed without merging**
