### PR TITLE
Adds flag to mark items as holograms

### PR DESCRIPTION
**Pull request by Razharas**
Adds flag to mark items as holograms
Will fix the tablecrafting with holoshit and unreported autolathe abuse
https://github.com/tgstation/-tg-station/issues/15046
This is not a fix as one needs to edit flags of all items in holodeck types and i dont want to touch maps ever in my life

### CODE REVIEW

**Comment by Iamgoofball** [comment]
:+1: cant wait for greytide salt

**Comment by TrustyGun** [comment]
Rip Holo-Chainsaw Meta

Also you should make it so you cant pick up chairs, or deconstruct items that have the HOLO flag

**Comment by lzimann** [comment]
I think the chair thing was changed to behave like that recently already

**Comment by Dorsisdwarf** [comment]
I'm not hot enough on flags to know if this will work for mobs, but if it doesn't one should be included for mobs too. See: #16574

**Comment by Razharas** [comment]
I can make it be atom level flag but thatll be a lot of code changes to make everything check for holoflag and them mapping to add it to all things holodeck

**Comment by Jordie0608** [comment]
@Razharas do you want to do the above in this PR or a later one?

**Comment by coiax** [comment]
If we're using a HOLOGRAM flag to indicate an items intelligibility for use in crafting and whatnot, that will work fine. But for anything more complicated, we'll need to modify how holodecks work.

Currently, all holodecks keep track of their component items, and derez them if they leave. Items that are capable of spawning additional items have special code to register their children items with the holodeck.

A HOLOGRAM flag would probably have to work through adding the item to SSobj.processing and regularly checking to see if they're in a holodeck zone and derezzing if not. This would lose some of the subtly of current holodecks, where if emagged items tend to last longer, and also the whole safeties thing.

**Comment by KorPhaeron** [comment]
@Razharas

**Comment by Razharas** [comment]
@KorPhaeron

**Pull request merged**
