### PR TITLE
Makes goonchat robust.

### PR DESCRIPTION
**Pull request by MrsTonedOne**
The old chat is kept active, we still push to it, so it stays up to date should goonchat fail to load but seem load or go away.

Added a OOC verb to fix goonchat, this system logs what was needed to fix it, so we can narrow our focus better.

Workaround for #28717 until I can get home and figure out how to prevent it. (might also fix it)

I'm not at my computer right now, I coded this on my laptop in the web editor at a friends house, somebody download this and test how it works and then maybe test merge this.

I likely won't be back home until monday to properly look at #28717

I also had to fix a bug in to_chat that would keep group/mass messages from showing to all recipients if one of the recipients hadn't loaded the chat yet or had a broken chat.

### CODE REVIEW

**Comment by nicbn** [comment]
Looks robust

**Comment by Jordie0608** [comment]
Tested a bit.
- `Force reload` seems to trigger the `cookie from banned account` message, although I can't imagine it's something to worry about
- At the `How about now?` prompt, both buttons lead to the `Welp, I'm all out of ideas` prompt; occurs for both `Force reload` and `Refresh`. 
- I spammed my way around each of options a bunch and got this focus-stealing error; neither option stopped it from re-appearing but it was gone once I closed and reconnected. Couldn't reproduce.
capture

No issues I noticed aside from those; although I've never had problems with goonchat thus far.

**Comment by MrStonedOne** [comment]
The `How about now?` prompt should now properly work.

The bug dialog box isn't avoidable thou, trying to send output while loading goonchat can cause that, its mainly in byond and IE and how they interact.

**Comment by MrStonedOne** [comment]
@KorPhaeron @ChangelingRain @lzimann Somebody test merge this if it hasn't been

**Pull request merged**
