### PR TITLE
Deletes Clock Cult

### PR DESCRIPTION
**Pull request by ShizCalev**
Press F.

Closes #38156 

Icons & Sounds are still present due to mixed usage in numerous locations.

### CODE REVIEW

**Comment by 81Denton** [comment]
F

**Comment by praisenarsie** [comment]
guys don't tell hippie or they will go fucking nuclear

**Comment by Aurantiaco** [comment]
here's to you, ratvar and brass
rest forever in github's ass
the last and final pr is yours
our agony is your triumph

**Comment by lordsaladin** [comment]
Yet another removed mode.

**Comment by Repukan** [comment]
Beat me to it damn

**Comment by ExcessiveUseOfCobblestone** [comment]
If you haven't already please keep the assets and toss them under the fluff/divine

**Comment by moonheart08** [comment]
RIP in pieces

**Comment by CosmicScientist** [comment]
Does this kill the plushie and the plushie battles?

**Comment by chesse20** [comment]
no support

**Review by ChangelingRain — APPROVED** [review]
"Yes, I will maintain clockcult now that I've reworked it"
how's that working out?

**Comment by Repukan** [comment]
Remove the golems too

**Comment by DaxDupont** [comment]
F

**Comment by CitrusGender** [comment]
W-whoa

**Comment by kevinz000** [comment]
Hey uh, could we revert clockcult back to old clockcult and give it another try?

**Comment by AlexTheSysop42** [comment]
Yeah clockcult had an amazing theme, it'd be a shame to see it go completely

**Comment by Firecage** [comment]
There goes best cult.

Also, please don't remove clockwork golems.

**Comment by rustledjimm** [comment]
As long as the assets, icons and sounds etc. are kept I'm happy with this. I prefer clock cult assets over blood cult to be honest.

**Comment by Shadowflame909** [comment]
Are you sure you don't mean to remove the other one? It's pretty sad when every mode that's new and fresh and isn't "traitor or ling's" will never last.

**Comment by rustledjimm** [comment]
>new and fresh

you haven't been here long have you

**Comment by Kromgar** [comment]
Clock cult had a REAL snazzy theme. Too bad it couldn't be made into a workable mode that wasn't a fucking pain for everyone involved.

**Comment by Aloraydrel** [comment]
People pretending to like clock cult is the best joke

**Comment by francinum** [comment]
Revert it to OldCC and remove it from rotation.

**Comment by Shadowflame909** [comment]
>New Clock-cult

Can't beat the facts. Samurai-Jimm! You still get my point. There's a raisin we don't get new modes. This is that raisin. It makes me sad how much-undeserved hate clock-cult gets. IMO, no one really gives reasons to why they hate it other than "It's a good meme to hate on it." Or "Everyone else is doing it."

**Comment by Kromgar** [comment]
@Shadowflame909 

1: If the clock cultists are killed to 1 person still have to wait 40 minutes until you can finally go to reeebe.

2: Kidnap memes are pretty much near unstoppable due to teleport in anywhere yo ufucking want mwehehehe.

3: If 2/3rds of the crew alive is converted round didn't end and you still had to wait out timer

4: Assaulting reebe is never enjoyable.

**Comment by Repukan** [comment]
Shadowflame maybe you ought to read the thread and see the polls to realize it was a flawed piece of shit and not a meme to hate it.

**Comment by Shadowflame909** [comment]
@Repukan  You n00b. I am reading the thread and half the thread is gone already! The rest of it isn't really giving me anything.

@Kromgar  Yeah these are pretty good reasons.  I feel like 1, 3, and 4 are solvable by stealing wizard and speedy rev code though.

**Comment by chesse20** [comment]
polls are wrong bring back clolck clult

**Comment by SgtxRootbeer** [comment]
Revert it to oldcc
Newcc suffers the same problem away missions and space-bases for bloodcult suffered from
The action isn't on the station, it's elsewhere, and the cultists can hide out way too easily.

**Comment by Repukan** [comment]
If you felt so strongly about clock cult nothing was stopping you for the last few months on fixing it and balancing it.

**Comment by BeeSting12** [comment]
repukan is right as usual clock cult sucked and im glad its out of rotation

**Comment by ExcessiveUseOfCobblestone** [comment]
Which admins are running cc to get 22 people to downvote the removal of a gamemode we don't run?

**Comment by Shadowflame909** [comment]
Man cobby... that's the silliest comment you've made yet! A mode doesn't have to be in rotation for people to enjoy it. IE traitor Bros, monkey, sandbox. Raging mages and nation's aren't even modes anymore. Yet they get requested all the time!

**Comment by Repukan** [comment]
But why

**Comment by CosmicScientist** [comment]
We had a good limerick as well.

**Comment by ShizCalev** [comment]
a) didn't compile
b) conflicts from hell
c) too much effort to resolve a & b

**Comment by ShizCalev** [comment]
restored the branch in case someone else wants to finish this off.

**Pull request closed without merging**
