### PR TITLE
Megafauna / Mob Abilities

### PR DESCRIPTION
**Pull request by Whoneedspacee**
## About The Pull Request

[Video Showcase](https://www.youtube.com/watch?v=fE9AgxZXbPs)

This majorly overhauls the cooldown action subtype to allow for shared cooldowns and for targeted abilities where you can queue up an ability and then click a target. I would've put this on the base action system since I believe most of these subtypes behaviors should simply be on the base action system but that'd be way overstepping what I'm wlling to refactor for this PR.

On top of this. most megafauna abilities are being converted to these actions to allow for use on almost any living mob with almost no jankiness (though using ash drake flying abilities will make an ash drake sprite appear and im not sure how to replace this at all, so not everything converts perfectly).

It's not a perfect system but it's way better than what is there currently by a longshot and I'm sure there are some better ways to build on it / use it that I'm just not currently seeing right now so I'm PRing this 3 megafauna before completion to get some code review.

## Why It's Good For The Game

This doesn't really directly impact gameplay while obviously giving more usability for these abilities (bubblegum charging on any mob, various projectile attacks now being mostly re-usable code). This as well as giving this utility to admins, though not the easiest to customize but at least making it possible to make somewhat custom player controlled mobs in-game. Custom AI controlled mobs will most likely wait until the basic mobs refactor is complete and then it should be almost trivial to have random selection of actions.

As you'll see in the video if you wish to watch, there could be much better visual tools for adding abilities to mobs. If anyone has any basic recommendations on how to make it much better let me know, though I'm not really interested in making a huge project out of that.

## Changelog

:cl: Whoneedspacee
refactor: Refactors major megafauna abilities to be mob actions which are grantable to any living mob. This also might unintentionally affect megafauna patterns / cooldowns, feel free to make a git issue about it.
admin: Added a verb under admin events which lets you grant mob actions to a marked living mob.
/:cl:

### CODE REVIEW

**Comment by Whoneedspacee** [comment]
> You currently have a negative Fix/Feature pull request delta of -7. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

I'm trying okay jeez

**Comment by TheMidnightRose** [comment]
So what you are saying is, I can finally create somewhat customized AI controlled megafauna in the near future?

**Comment by Whoneedspacee** [comment]
> So what you are saying is, I can finally create somewhat customized AI controlled megafauna in the near future?

If floyd finishes his ai controllers it'll be realistic for an admin to do it with this as well yeah, though you'll be limited to the actions and how you can edit them in game.

In some cases this can be limiting where I haven't bothered to spend a lot of time making the feature like ash drakes swoop attacks because I'm pretty burnt out.

In some cases like with projectile attacks with var editing on the ability you could have attacks that aren't currently in the game in any capacity, especially by changing the projectile sent out.

The hope is that these sytems become more fleshed out as people add more mob abilities to the game and eventually you have even more customization on your end, but we'll see if it sticks.

**Comment by ArcaneMusic** [comment]
Does this fix #53726?

**Comment by Whoneedspacee** [comment]
> Does this fix #53726?

It could be fixed very easily with this yes, I'll add that to them at some point in this pr then.

**Pull request closed without merging**
