### PR TITLE
Reverts #57957

### PR DESCRIPTION
**Pull request by SmArtKar**
## About The Pull Request

Reverts #57957 because every round turns into a virus shitshow after it got merged.

## Why It's Good For The Game

Viruses spawning every 5-10 minutes is not cool.

## Changelog
:cl:
del: Reverted new miasma and infection system
/:cl:

### CODE REVIEW

**Comment by LemonInTheDark** [comment]
Please don't "fix" problems by reverting the pr that causes them, especially if they're number related and not an overall behavior change

**Comment by ATH1909** [comment]
> Please don't "fix" problems by reverting the pr that causes them, especially if they're number related and not an overall behavior change

well, you don't have a fix pr for it up yet. we can at least testmerge this one in the meantime.

**Comment by PolishUser** [comment]
Fastmos 2: electrical boogaloo
>inb4 MSO will fix it 3 months later

**Comment by LemonInTheDark** [comment]
my life is a series of disappointments and failures

**Pull request closed without merging**
