### PR TITLE
Converts sec armories to using the (not) random mapping spawners

### PR DESCRIPTION
**Pull request by Jolly-66**
## About The Pull Request
Title.

## Why It's Good For The Game
Armories aren't really a dense area mapping wise, just a few guns there, armor there, and some fluff security stuff (like HUDs or whatever).

This PR just converts most of the heavy stuff (armor, helmets, guns) into spawning helpers with the aim to make mapping armories just a tad bit quicker and easier.

The only thing this does kinda nuke is the neatly stacked stuff, which the mapping helpers kinda suck at doing, but its not totally woeful.

## Changelog

:cl: Jolly, timothymtorres
code: Jolly: Armories across all maps have been tweaked slightly. Report to a Nanotrasen security advisor for any missing guns, armor, helmets or anything else that was there previously (that means, post an issue on Github if theres an issue!!)
code: timothymtorres: Random item spawners now support better control of their X/Y pixel offset.
/:cl:

### CODE REVIEW

**Comment by timothymtorres** [comment]
If you want better control of pixel x/y offsets you should make the last part of this code into it's own vars.

https://github.com/tgstation/tgstation/blob/616772574efc407b895f5d9526f00df384564ebd/code/game/objects/effects/spawners/random/random.dm#L67-L77

**Comment by Jolly-66** [comment]
I'll come back to this later once I talk to @timothymtorres more about the system.

**Comment by timothymtorres** [comment]
Should be good to go now.

**Review by Maurukas — APPROVED** [review]
Very nice.

**Pull request merged**
