### PR TITLE
BirdBoatstation PR

### PR DESCRIPTION
**Pull request by Tokiko1**
PR'd this map so it can be used on the server. You probably don't want to merge it? Maybe?

Thread with pictures: https://tgstation13.org/phpBB/viewtopic.php?f=11&t=4223

### CODE REVIEW

**Comment by Wyzack** [comment]
Really want to see this map on Basil, what will it take?

**Comment by MrStonedOne** [comment]
1 round test run on sybil starting.

**Comment by MrStonedOne** [comment]
Compile failed:

````
This will handle downloading from git, merging the pr locally, compiling the ser
ver, and applying the update.
Please enter the pr number (without a # or anything of the sorts):11829
updating to pr 11829
Updating repo
Already on 'master'
Your branch is ahead of 'origin/master' by 6 commits.
  (use "git push" to publish your local commits)
HEAD is now at ba07442 Merge pull request #12028 from phil235/AddbloodRuntimeFix

Already up-to-date.
Merge made by the 'recursive' strategy.
 _maps/birdstation.dm                            |   37 +
 _maps/map_files/BirdStation/BirdStation.dmm     | 2620 +++++++++++++++++++++++
 _maps/map_files/BirdStation/job/job_changes.dm  |  123 ++
 _maps/map_files/BirdStation/job/removed_jobs.dm |   38 +
 _maps/map_files/BirdStation/misc.dm             |   63 +
 _maps/map_files/BirdStation/teg.dm              |   23 +
 _maps/map_files/BirdStation/telecomms.dm        |   20 +
 _maps/map_files/BirdStation/z2.dmm              | 1091 ++++++++++
 _maps/map_files/BirdStation/z3.dmm              |  505 +++++
 _maps/map_files/BirdStation/z5.dmm              |  309 +++
 10 files changed, 4829 insertions(+)
 create mode 100644 _maps/birdstation.dm
 create mode 100644 _maps/map_files/BirdStation/BirdStation.dmm
 create mode 100644 _maps/map_files/BirdStation/job/job_changes.dm
 create mode 100644 _maps/map_files/BirdStation/job/removed_jobs.dm
 create mode 100644 _maps/map_files/BirdStation/misc.dm
 create mode 100644 _maps/map_files/BirdStation/teg.dm
 create mode 100644 _maps/map_files/BirdStation/telecomms.dm
 create mode 100644 _maps/map_files/BirdStation/z2.dmm
 create mode 100644 _maps/map_files/BirdStation/z3.dmm
 create mode 100644 _maps/map_files/BirdStation/z5.dmm
Current folder detected to be the "B" folder. Game is currently running, Updatin
g to the "A" folder.
Removing old files
gamecode\a\libmysql.dll - Access is denied.
The process cannot access the file because it is being used by another process.
Copying files
Sharing violation
compiling change log
Reading changelogs...
 Reading C:\tgstation-server\gamecode\a\html\changelogs\phil235-AddbloodRuntimeF
ix.yml...
  Added 1 new changelog entries.
 Reading C:\tgstation-server\gamecode\a\html\changelogs\phil235-DeadDna.yml...
  Added 1 new changelog entries.
Cleaning up...
 Deleting C:\tgstation-server\gamecode\a\html\changelogs\phil235-AddbloodRuntime
Fix.yml (delete-after set)...
 Deleting C:\tgstation-server\gamecode\a\html\changelogs\phil235-DeadDna.yml (de
lete-after set)...
building script.
loading tgstation.mdme
loading interface\skin.dmf
loading map_files\BirdStation\BirdStation.dmm
loading map_files\BirdStation\z2.dmm
_maps\map_files\BirdStation\z2.dmm:599:error: cannot find file
_maps\map_files\BirdStation\z2.dmm:599:error: expected )
Failed to load map file C:\tgstation-server\gamecode\a\_maps\map_files\BirdStati
on\z2.dmm.
tgstation.mdme.dmb - 2 errors, 0 warnings (9/28/15 6:37 pm)
DM compile failed. Aborting.
Press any key to continue . . .
````

**Comment by Tokiko1** [comment]
Weird, looks like the file for the second z level is missing, even though it's included in this PR.

**Comment by Tokiko1** [comment]
Should work once again. Looks like z2.dmm broke from some recent updates.

**Comment by MrStonedOne** [comment]
<Mrs_Sybil> AUTOMATIC ANNOUNCEMENT : PR test job started. Updating master then merging PR #12111 locally

#12111 includes this map as well as map rotation

**Comment by Tokiko1** [comment]
Note that if you want to merge this you probably should not do this directly after map/path change PRs are merged as this will break the map and travis doesn't check if birdstation compiles.

**Comment by Jordie0608** [comment]
You can add the map to travis as part of this PR by appending .travis.yml with DM_MAPFILE="birdstation".

**Comment by Tokiko1** [comment]
Oh I had no idea it was this easy! Thanks!

**Comment by Jordie0608** [comment]
Merging since it's ready for map rotation as to avoid some crashy stuff.

**Pull request merged**
