### PR TITLE
New torch sprites, fixed missing inhands

### LINKED ISSUE #35007: There is no inhand sprite for torches
image

you can close it if you don't like having 4 digit issues :3

### PR DESCRIPTION
**Pull request by Lexorion**
## New torch sprites, fixed missing inhands
Closes #35007 

Not perfect but better, I guess.
I changed the light color from red to orange and fixed the inhands,
Apparently there were old inhand sprites but they were unused so I replaced them aswell.

### CODE REVIEW

**Comment by MrDoomBringer** [comment]
suuuuch a better flame thank god

**Comment by Xhuis** [comment]
Now all we need is pitchforks.

**Comment by lordpidey** [comment]
We have pitchforks, currently only the devil subtype is used.

**Comment by praisenarsie** [comment]
yeah but that one looks more demonic tbh

**Review by WJohn — APPROVED** [review]

**Comment by ExcessiveUseOfCobblestone** [comment]
@Lexorion i love you please bare my code-children

**Pull request merged**
