### PR TITLE
Minor Sprite Changes [witch hunter, oldcaparmor/centcom]

### PR DESCRIPTION
**Pull request by ishitbyabullet**
## About The Pull Request
Hey, this changes a few sprites. I fixed the centcom and oldcaparmor sprites. I also tweaked the cross for the witch hunter outfit
## Why It's Good For The Game
I want to fix the sprites of the two armors I mentioned. I also think it would be best to just change the chaplain witchhunter sprites however I just decided to modify the cross a bit.
## Changelog
:cl: Bald People
tweak: Witch hunter outfits are slightly different. You may notice the difference. Maybe.
fix: The centcom armor and old captain armor sprites no longer look like they were poorly recolored. Admins can finally have more options for Centcom now!
/:cl:

### CODE REVIEW

**Comment by ishitbyabullet** [comment]
Showcase of said sprites
image

**Comment by KomradeSpectre** [comment]
>Changing witch-hunter outfit from red to blue.

But why? Generally, red tends to go better with black and gold. I'd suggest just making that an alternative variant of the outfit instead of replacing it with your own subjective choice of color palettes.

The removal of color noise on the other outfits is fine, but the first outfit change is a bit...weird.

**Comment by ishitbyabullet** [comment]
> But why? Generally, red tends to go better with black and gold.

Perhaps changing just the cross will work. The main reason is that the sprite comes from a grimdark place with basically almost no changes.

**Comment by Tharcoonvagh** [comment]
>chrono legionnarie
ok

**Comment by Detective-Google** [comment]
bald

**Comment by carlarctg** [comment]
red is better than blue

**Comment by Anonymous583** [comment]
let captains be green again

**Comment by nemvar** [comment]
I like the red witch hunter. I don't think its copyrighted so why the change?

**Comment by ishitbyabullet** [comment]
A better alternative would just be a different witch hunter sprite tbh.

I don't like the blue color that much however it was given as advice. I'll change it to black and red.

**Comment by Fikou** [comment]
you should change mark 2 swat suits too c:

**Comment by ishitbyabullet** [comment]
I actually don't know where the sprite first came from anymore since I just remembered what I was told when I asked about it. I also realized that another sprite, that even appears in an old codebase I have, looks similar to the witchhunter outfit.

Fuck it. I'll just change the cross. I still think that we need a completely different witch hunter sprite however I don't even know who made what first anymore.

**Pull request merged**
