### PR TITLE
Tactical wall girders are back!

### PR DESCRIPTION
**Pull request by ACCount12**
Removed a chance for projectiles to pass wall girder. Using dispaced wall girders as ghetto shields was fun, and i miss it.

### CODE REVIEW

**Comment by optimumtact** [comment]
:-1: you can see through a girder, you can potentially shoot through a girder

**Comment by dannno** [comment]
If it's a ghetto shield it should have a chance to fail.
That's what makes it ghetto.
:-1:

**Comment by ACCount12** [comment]
25% is too much. And why you can't shot through a locker or machine? You can see through them,

**Comment by optimumtact** [comment]
I guess

whatevers, maybe a reduced chance

**Comment by phil235** [comment]
ACCount12, I actually had in mind to expand shot passing through to all machines but haven't found the time and motivation to do it since.

**Comment by Cheridan** [comment]
The whole point of this being added was so that people couldn't use girders to block AI turrets and easily win Malf rounds and such.

**Comment by ACCount12** [comment]
Malf has APC escape on/tg/, so there is no way to win Malf round easily.

**Comment by Boredone** [comment]
Honestly, girders still work pretty well, atleast if wrenched down.

**Comment by ACCount12** [comment]
No, there is 20% chance to not block projectile if wrenched down. And the point of girder was blocking projectiles when unwrenched.

**Comment by phil235** [comment]
Feel free to adjust blocking chance values but :-1:  to complete removal.
Personally I don't think 25% is too high. When you consider the slow rate of fire of the AI turrets the girders are still great shields during malf.

**Comment by Jalleo** [comment]
This was changed to prevent powergaming the entire mechanic of shooting stuff and it being blocked with almost nil side effect is bad.

**Comment by Anonus** [comment]
Of course, the change didn't do much because computer frames are the same thing but without a chance to let projectiles pass.

**Comment by Boredone** [comment]
Out of curiosity, how hard would it be to make girders and such like crates or lockers, which destroy themselves when they are damaged enough?
That sounds like it would be a good compromise.

**Comment by Nienhaus** [comment]
:-1:

**Comment by WJohn** [comment]
I've personally always felt like you should be able to shoot through girders rather than be able to use them as shields, but only with lasers. They'd act more like grilles and windows then.

**Comment by Dorsisdwarf** [comment]
I agree with that

(although you can shoot through grilles with bullets just fine)

**Comment by MrPerson** [comment]
Unnecessary nerf to lasers and malf AI's imo

**Comment by Dorsisdwarf** [comment]
ojh yeah, also
:-1: 
to this change

**Comment by Dorsisdwarf** [comment]
Also if you really really want to GG NO RE a malf AI, just grab a metal foam grenade/ one of the 3 atmos backpacks and fill that core right up.

Then begin stage 2: APC hunt boogaloo

**Comment by hornygranny** [comment]
this was added for a reason

**Pull request closed without merging**
