### PR TITLE
Fixes closet locking while keeping unlock/lock functionality from inside the locker intact

### PR DESCRIPTION
**Pull request by silicons**
:^)

### CODE REVIEW

**Comment by jughu** [comment]
@korphaeron maybe if you deny this kevinz will do auctall adminning for once

**Comment by optimumtact** [comment]
how many locks have you seen on closets that work on both sides?

this is a dumb pr

**Comment by kevinz000** [comment]
@jughu you don't even play tg anymore

**Comment by Supermichael777** [comment]
lockers actually usually have an internal escape lever or mechanism that can easily be manipulated from the inside.

**Comment by ExcessiveUseOfCobblestone** [comment]
Fix techwebs next

**Comment by Bawhoppen** [comment]
@Supermichael777 Our version of that ingame is being able to bash it open by kicking it enough.

**Comment by Cyberboss** [comment]
What @Bawhoppen said

**Pull request closed without merging**
