### PR TITLE
Fixes #9815 - Lizards, rejoice!

### LINKED ISSUE #9815: Lizards have chance of joining with wrong sprite. (Maybe humans too.)
So, it was brought to my attention that the coders thought the post-server wars gender bender bug was fixed. But it is still going strong, and has been ever since the server wars.

Basically, when you join the game as a lizard, you appear to have a 50/50 chance of your sprite not matching your genetic gender. A male has a female body and vice versa. It has led to interesting things IC, like a lizard MD specializing in sex change operations for lizards whose bodies were messed up by NT.

I have only observed this happening to lizards, but I never play human characters. It may happen to humans as well.

### PR DESCRIPTION
**Pull request by SvartaSvansen**
I found the lizard misgendering issue (#9815) lying inside /datum/preferences, in the chunk of code that initializes a character on spawn. The mutant race icon is updated before the character's gender is set, when the gender is still randomized. So in the case that your lizard has the wrong sprite, for a small fraction of a second it actually was that gender when its icons were regenerated. But its icons weren't regenerated again after its gender was set to your preference.

I moved the if(character.dna) block to the end so everything is set before hardset_dna() calls regenerate_icons(). With those four null arguments, it doesn't touch anything that was set before it, so values that are already set won't be overridden by a default or randomized value.

Lizards, rejoice! The days of joining with a body of the opposite sex are over!

I also cleaned up the code a bit in the process. I found out that update_mutcolor() is called twice when a character is spawned in (my note about the redundant regenerate_icons() call is wrong), and it fails to set a mutant color the first time. I moved things around so update_mutcolor() is only called once and succeeds the first time.

### CODE REVIEW

**Comment by palpatine213** [comment]
Feature

**Comment by Incoming5643** [comment]
you'll need to update this because hardset_dna changed in #9808 to stick features in. Sorry.

**Comment by Razharas** [comment]
@SvartaSvansen Plz respond

**Comment by Razharas** [comment]
Looks abandoned, ask for reopening if you want to return to it

**Comment by Cheridan** [comment]
fucks sake just do a manual merge

**Comment by phil235** [comment]
Closing this, I updated the PR in #10889

**Pull request closed without merging**
