### PR TITLE
Makes Ctrl+shift+click pass user

### PR DESCRIPTION
**Pull request by Gandalf2k15**
## About The Pull Request

Literally just makes the CtrlShiftClick signal pass user, like all the other mouse actions.

## Why It's Good For The Game

Makes the use of the CtrlShiftClick signal actually useful.

### CODE REVIEW

**Comment by Mothblocks** [comment]
I'm letting you know now that if you put this horrible hotkey on anything, then there's an extremely good chance I'm going to ask you to change it to something more accessible 😄

**Review by Mothblocks — APPROVED** [review]
Approving for consistency, though.

**Comment by RaveRadbury** [comment]
CTRL+Shift+Click is currently an admin hotkey to quickspawn ghosts into humans

**Comment by Mothblocks** [comment]
Yeah, it's also on a few more things. Admin specific stuff is, whatever, but I think it's a really stupid hotkey combination for anything in game, and as a personal grudge it's also just really difficult for me to do since my hands are a bit weak.

**Comment by Gandalf2k15** [comment]
i'll be sure to make good use of it trust me

**Comment by Mothblocks** [comment]
i doubt it

**Pull request merged**
