### PR TITLE
Updates Our Nanotrasen Copyright To 2562

### PR DESCRIPTION
**Pull request by tralezab**
## About The Pull Request

image
Phew that was close

## Why It's Good For The Game

Don't want to get in hot water

## Changelog

Not really important for a player

### CODE REVIEW

**Review by MrMelbert — APPROVED** [review]
important for legal reasons

**Review by stylemistake — APPROVED** [review]

**Comment by stylemistake** [comment]
Cybersun approves

**Comment by Dorsisdwarf** [comment]
Wouldnt it make more sense to make this automatically update the date like elsewhere in the code?

**Comment by Iamgoofball** [comment]
can we make this slightly less IC honestly

im really tired of people calling Scientists to "fix their computer" and then i get there and its a tgui BSOD

**Comment by Iamgoofball** [comment]
like its absolutely hilarious, but also people don't grok that it's an actual issue until it happens to them on an OOC panel like setup character or something

**Comment by githubuser4141** [comment]
> can we make this slightly less IC honestly
> 
> im really tired of people calling Scientists to "fix their computer" and then i get there and its a tgui BSOD

100% agree, if you're going to mix up IC language with a IRL error at least make it obvious it's a real error, it took me a few takes to realise what it was and the fast moving text and animations don't help either. IMO a error message shouldn't have any colorful text or animations, it should get to the point of reporting what went wrong instead of blabbing about random sci-fi gobbledygook and then (maybe) telling you the actual error in the  fine print.

**Pull request merged**
