### PR TITLE
Lamp resprite

### PR DESCRIPTION
**Pull request by Krysonism**
## About The Pull Request
bild
bild

This PR resprites the desk, green and banana lamps.

I did the desk and green lamps. Imaginos did the banana lamp.

## Why It's Good For The Game
The old lamp sprites were really low quality.

## Changelog
:cl:
imageadd: The desk, green and banana lamps have been resprited. 
/:cl:

### CODE REVIEW

**Comment by notfrying1pans** [comment]
im gonna be real with you these have s o u l

**Review by Twaticus — APPROVED** [review]

**Comment by Farquaar** [comment]
ＳＯＵＬＬＥＳＳ

**Comment by cacogen** [comment]
they look out of place :)

**Comment by Dorsisdwarf** [comment]
They're beautiful sprites ~~but i think the angle is technically wrong for our new perspective and the tables they sit on are hideous~~ and I think this is a good addition to the game.

**Comment by Mothblocks** [comment]
first resprite ive seen in a while with no thumbs downs

**Pull request merged**
