### PR TITLE
Adds record of toilet combat

### PR DESCRIPTION
**Pull request by ArcaneDefence**
## About The Pull Request

Logs a direct method of dealing damage to a person that wasn't logged previously

## Why It's Good For The Game

Prevents bullies from escaping the ever watchful eyes of j*nnies

### CODE REVIEW

**Review by Cyberboss — APPROVED** [review]

**Comment by cacogen** [comment]
Toilet combat, which is a concept that needs to be expanded upon

**Comment by MissFox0810** [comment]
If you are going to do logging of stuff. you need to use the correct logging method. rather than call the direct log hooks
log_message(message, message_type, color=null, log_globally=TRUE)

**Comment by Cyberboss** [comment]
Bleh, sorry @MissFox0810 I read your comment but didn't process it in time.

@ArcaneDefence if you can make that change it'd be appreciated.

**Comment by ArcaneDefence** [comment]
> 
> 
> If you are going to do logging of stuff. you need to use the correct logging method. rather than call the direct log hooks
> log_message(message, message_type, color=null, log_globally=TRUE)

`log_combat` calls `log_message` twice, once on the user once on the target 
I'm at a complete loss on what you're telling me here

**Comment by MissFox0810** [comment]
Oh wait. never mind. In my blindness i thought i saw log_attack. never mind me! :D.
Im just working on a PR that updates all the old log_attack to use log_combat or log_message.

**Pull request merged**
