### PR TITLE
Repipes Box

### LINKED ISSUE #11170: Box: Incinirator camera is not connected to anything
This is the camera monitor by the turbine.

### LINKED ISSUE #11284: The floor left of medbay maintenance is missing a pipe for the waste distro.
http://puu.sh/jH2DO/3b0e8c849e.png basically shows it

missing from the left of the medbay maintenance door

### LINKED ISSUE #11290: Rogue air scrubber in virology
it's not connected to the pipeline next to it and there's a scrubber directly to the right of it
It's not connected to the pipeline next to it and there's a scrubber directly to the right of it.

### LINKED ISSUE #11931: Pun-Pun has no real_name.
Null for some reason. Other monkeys have a real_name so not sure what is up with Pun-Pun

### PR DESCRIPTION
**Pull request by WJohn**
Repipes boxstation. This touches every department and hallway and is going to get conflicts REALLY EASILY so I'd really appreciate it if this wasn't held off on for two weeks.

This DOES NOT touch atmosia or the disposal loop.

Moved mulebot delivery to R&D
Air alarm in toxins and misc lab starts unlocked
Minor rewiring in engineering

Fixes #11290
Fixes #11284
Fixes #11170
Fixes #11931

### CODE REVIEW

**Comment by Supermichael777** [comment]
:+1: :100:

**Comment by duncathan** [comment]
oh sweet jesus :+1: x :100:

**Comment by GunHog** [comment]
WJ deserves Xeno merges for a month.

**Comment by Dorsisdwarf** [comment]
Just to clarify I'm using the first half of the tag (IE someone test this shit out ASAP so we can merge as soon as it's been 24 hours)

**Comment by Anonus** [comment]
This isn't really better, a lot of pipes that really should connect, like in science or viro, don't connect and that's super fucking weird and just as bad as box is right now.
This is pretty bad there's no justifiable reason for it to do that
Again, this is pretty bad
Medbay is probably the worst offender, though.

**Comment by GunHog** [comment]
Yes, how have you repiped Box? I am curious now, that I think of how I can move around while ventcrawling.

**Comment by WJohn** [comment]
All pipes now come from maintenance where possible, and believe me Anonus it is VASTLY better than what we previously had where pipes would do friggin' loopdy loops everywhere. I specifically DO NOT want pipes running through the entire length of departments, but sometimes I can't really do much about it with something like toxins storage there in research.

**Comment by tuypo1** [comment]
say well its to late now but pipes should be expansive it makes ventcrawling fun

its vital that you be able to hit the cloner with a dissonant shriek as a monkey ling

if you move pipes out of departments it shuts down a playstyle that is both fun for antags and creates interesting scenarios for non antags

**Comment by tuypo1** [comment]
ok i have not had a chance to try the new layout yet as i have been away now that i have i fucking hate it it seems like ventcrawling is now good for nothing but escaping having it mostly in maint is not worth what was lost

**Pull request merged**
