### PR TITLE
Resprites toolbelts

### PR DESCRIPTION
**Pull request by AMyriad**
## About The Pull Request

Adds the following to the game:
Toolbelt sprites from https://github.com/BeeStation/BeeStation-Hornet/pull/2487 by [SomeAngryMiner](https://github.com/SomeAngryMiner)
Tool overlays from https://github.com/yogstation13/Yogstation/pull/13679 by [nmajask](https://github.com/nmajask)
And a couple more overlays and tweaks by me 

image image
image image 

## Why It's Good For The Game
I'm enamored with all the nice spriting you guys have done here, so it makes me sad to see the old ugly toolbelts and advanced tools here
image image

## Changelog
:cl: AMyriad, nmajask, SomeAngryMiner
image: Added new toolbelt sprites
/:cl:

### CODE REVIEW

**Comment by cnleth** [comment]
> old ugly toolbelts

The last toolbelt resprite was less than a year ago https://github.com/tgstation/tgstation/pull/75901

I think the ones we have at the moment are much more "modern", but that's just my opinion

**Comment by Higgin** [comment]
The greebling on the inside of the belt and position it gives to the tools behind the belt messes with the legibility here imo, but the shading/lighting are nicer in some spots.

**Comment by Dorsisdwarf** [comment]
Its always funny to see pretty fresh and new sprites get called old and outdated by someone who doesnt know how new they are and is just filling in boilerplate reasoning, but I do actually like these ones. They don't seem better or worse than the current sprites and are more "in perspective" I think.

**Comment by thgvr** [comment]
image
Honestly not great. Super hard to make out most of the shapes, and the shading is very messy. Couple weird stray pixels and stray pixel colors hiding around, too, which is even more strange.

Here's a quick suggestion I came up with: 
image

**Comment by deathrobotpunch** [comment]
don’t fix what isn’t broken

**Comment by Fikou** [comment]
they look worse i think

**Comment by EEASAS** [comment]
they certainly look worse, and how will this affect the local soul population

**Comment by EricZilla** [comment]
I like the little pouch its fun, we can pretend we use screws and such. I'm a fan of the primary color of the bee belts, but they are a little busy for my tastes.
I'd also have liked to see a before and after of the tools.

**Comment by Rex9001** [comment]
I think these actually look more dated than our current designs, these look a bit more muddy to me.

**Comment by Xackii** [comment]
It feels like the toolbelt has been worn out and has turned white. I don’t see any difference except that the new sprites are paler and more incomprehensible

**Comment by RengaN02** [comment]
desouled

**Review by Wallemations — CHANGES_REQUESTED** [review]
I'm honestly not a fan of how busy the new little satchel and metal clip make it look compared to the current one

**Comment by Xackii** [comment]
add a cardboard toolbelt with this sprite

**Comment by AMyriad** [comment]
> I'm honestly not a fan of how busy the new little satchel and metal clip make it look compared to the current one

Aye fair enough. I don't have the time for respriting this thing right now so I'll be shelving it for the time being.
Thank you all for the honest input and critique here though.

**Pull request closed without merging**
