### PR TITLE
Birdshot Cargo Changes

### PR DESCRIPTION
**Pull request by GremlinSeeker**
## About The Pull Request

Some QoL changes for cargo, mostly just with the goal of cutting down on the sheer amount of airlocks in cargo. I also added a small cargo lobby to aid in pushing the ORM a tad closer to the miners and cutting down on the airlocks in and out of cargo. 
## Why It's Good For The Game

Less claustrophobic, more space. The changes are very minor, just small changes to the layout without completely overhauling it. 

You can see the changes below.
image

re-added dnd room:
image

new cargo lobby area:
image

the freed up space: 

image

## Changelog
:cl:
add: Birdshot Cargo now has a lobby and is slightly more open overall.
add: Re-added the DnD room  to Birdshot

/:cl:

### CODE REVIEW

**Comment by Blacklist897** [comment]
every day im reminded that arc mining killed birdshots dnd room

**Comment by DaCoolBoss** [comment]
Massive improvement. Might want to change your "Add" CL tag to a "QoL" tag though, since this isn't a feature.

**Comment by GremlinSeeker** [comment]
> every day im reminded that arc mining killed birdshots dnd room

hahaha, that's a great idea, I think I'll add it back I found an old picture of it. There's a useless room south of cargo in maintenance that'd fit it perfectly.

**Comment by Maurukas** [comment]
You've got a merge conflict. Get that resolved and double check, it looks like there's a few odd changes getting pulled in, like this bit here:
image

I don't think the 2x2 block is intentional.

**Comment by Ghommie** [comment]
Unfortunately, all of this will have to be redone because of the wallening (I didn't notice thi PR until then). I understand it'll take a while to re-do it, so for the time being I'll close this PR.

**Pull request closed without merging**
