### PR TITLE
Fixes joining the game with the wrong dir

### PR DESCRIPTION
**Pull request by Rohesie**
* The issue was a precedence one in the chair buckling. When spawning on a (shuttle) chair, it would buckle the mob and move it to the turf, changing its direction to a diagonal one. The solution is to first move to the turf and then attempt buckling.
* Improved a variable name a little.
* Fixes the more general issue of buckling moving the buckling mob after setting the dir, instead of before (the dir will change on the move proc as well).

## Changelog
:cl:
fix: Buckling to nearby objects and roundstart shuttle buckling now result in the proper facing direction.
/:cl:

### CODE REVIEW

**Review by Cyberboss — APPROVED** [review]

**Comment by newfren** [comment]
Does this also fix the issue of buckling yourself to a chair from an adjacent tile facing you the wrong way?

**Comment by Rohesie** [comment]
> 
> 
> Does this also fix the issue of buckling yourself to a chair from an adjacent tile facing you the wrong way?

It does not. Didn't realize the issue was deeper until now that you mentioned it. I'll take a peek at that.

**Comment by Mothblocks** [comment]
> Edit: fixed now, that should no longer be a thing.

Changelog, then 🙂

**Review by Mothblocks — APPROVED** [review]
Needs changelog as this includes player facing changes

**Comment by Rohesie** [comment]
Changelog added.

**Pull request merged**
