### PR TITLE
Tanks Show Pressure When Examined

### PR DESCRIPTION
**Pull request by ghost**
Ya this is pretty much all tanks.

### CODE REVIEW

**Comment by phil235** [comment]
Probably needs the "kPa" unit at the end.

**Comment by Durkel** [comment]
Tanks for the info.

**Comment by bustygoku** [comment]
I think it's KPa or kPA i forgot

**Comment by phil235** [comment]
It's "kPa", for kiloPascal

**Comment by bustygoku** [comment]
Fixed

**Pull request merged**
