### PR TITLE
PDA Notekeeper 2.2

### PR DESCRIPTION
**Pull request by Deantwo**
Notekeeper:
- Now uses [PenCode](https://tgstation13.org/wiki/Paper_BBCode) rather
  than HTML.
- Now uses the same font as paper. Meaning that signature has a
  different font, same as paper.
- Editing the notes now uses **stripped_multiline_input** proc.
- Cancelling the input box no longer deletes all the notes.
- Added a horizontal rule between the Edit button and notes section.
- Incremented the Notekeepers version number by 0.1 because of this new
  notekeeper update.
- Scanning paper with your PDA now saves most of the content to the var
  that is shown as default text in the edit input box.
- Scanning paper now states that it is saved to the notekeeper.
- Can no longer scan blank paper. User is notificed of this.

NTRC Chatroom:
- Set Nick now does not allow "" as a name, and cancelling the input box
  doesn't delete the nick.
- Set Channel now has a length limit of 15 rather than 255.
- Message now does not send "" messages, and cancelling the input box
  doesn't send a message.
- Added a horizontal rule between the buttons and chat section.

Other:
- Changed the **msg_input** proc to use **stripped_input**.

### CODE REVIEW

**Comment by Deantwo** [comment]
Thinking about trying to make the [photocopier](https://github.com/tgstation/-tg-station/blob/bff2e62a0f28e7838ad19f1b955e0f4250362e02/code/modules/paperwork/photocopier.dm) print what is in the PDA's notekeeper next, but let me get some feed back on this first.

**Comment by ike709** [comment]
feel free to have PDAs use NanoUI while you're at it

**Comment by Deantwo** [comment]
When scanning paper, it is impossible to get the original PenCode that was used to write the paper.
Without adding a lot of crap to paper that is, and if it is only to make PDA's scan paper better, I don't think it's worth it.

So when you scan a paper, the notekeeper will display the paper totally as it was.
But once you click the *Edit* button, you only get a few of the PenCode tags in the input box.
I could make it save more like: [b], [i], [hr], [center], [field], etc. But felt that it wasn't that important right now, IC you can think of it as bad text scanning software!

**Comment by Deantwo** [comment]
Also fixed s few bugs I found in the *NTRC Chatroom* feature.

**Comment by RemieRichards** [comment]
With how you've implemented PenCode here being identical to how you've done so on newscasters, it'd probably be best to make it one global proc, to save copy pasting parsePenCode().

**Comment by Deantwo** [comment]
> feel free to have PDAs use NanoUI while you're at it

Not sure I feel comfortable trying to do that just yet. Still only working on minor things.

> With how you've implemented PenCode here being identical to how you've done so on newscasters, it'd probably be best to make it one global proc, to save copy pasting parsePenCode().

Yeah was thinking of doing that, but I kinda ended up with having it in two different PRs.
And I am not 100% sure how to do that, but maybe I'll try and do it if they get merged I guess.
Was thinking about adding it to [__HELPERS/text.dm](https://github.com/tgstation/-tg-station/blob/bff2e62a0f28e7838ad19f1b955e0f4250362e02/code/__HELPERS/text.dm).

**Comment by RemieRichards** [comment]
@Deantwo it's fine to keep doing it this way for your two PRs (since it'd be annoying to merge them)
so long as you improve it in another PR after they're both merged.
__HELPERS/text.dm sounds like a good place to put it yes.

**Comment by Deantwo** [comment]
Trying to fix a few more NTRC bugs.
Closed until I am done.

**Comment by Deantwo** [comment]
Had to do some fixes in the [chatroom.dm](https://github.com/tgstation/-tg-station/blob/bff2e62a0f28e7838ad19f1b955e0f4250362e02/code/game/objects/items/devices/PDA/chatroom.dm) file.
I feel stupid for trying to fix some of that on the PDA side when it was the NTRC code that wasn't safe.
I even found two runtime error... index out of bounds... but it should all work now.

**Comment by Deantwo** [comment]
Oh I hadn't even saved the file to add the version number to NTRC in the last commit.
I am getting tired, someone make me stop coding!

**Comment by Miauw62** [comment]
Now make the one with defines and the global proc, @DeanTwo :V

**Comment by Deantwo** [comment]
Working on it.
At lest I will be once I am done replying to you everywhere! XD

**Pull request merged**
