### PR TITLE
MMI'd clockcultists put in AI cores will properly lose clockcult status

### PR DESCRIPTION
**Pull request by ChangelingRain**
:cl: Joan
rscadd: You can now put syndicate MMIs and soul vessels into AI cores.
/:cl:

But will only lose antag when actually made an AI, instead of when placed in the frame.
Also it'll delete the MMI when destroyed instead of ending up never deleting the MMI; you can't decon it with an MMI inside anyway.

i ended up refactoring huge chunks of ai code kill me please

### CODE REVIEW

**Comment by GunHog** [comment]
Does this just cover _regular_ MMIs, and **not** soul vessels?

**Comment by ChangelingRain** [comment]
soul vessels can't actually be put in AI cores but that can be changed

**Comment by GunHog** [comment]
It should be! They are just Steampunk MMIs, they should be able to be whatever a normal MMI/Posibrain can! Soul vessel put in to AI core becomes Steampunk AI! Saves the human cultist the step of making the AI and then proceeding to convert it, while still preventing a bug where a non-antag puts a brained cultist into one thinking it is safe.

**Comment by ChangelingRain** [comment]
you can put soul vessels in ai cores now
the new ai won't get a new name; it'll stay as the vessel's name

**Comment by Armhulen** [comment]
It should get some gear name, evil or not

**Comment by ChangelingRain** [comment]
soul vessels are always evil and thus will always get a special name
standard converted ais won't, though; might change this?

**Pull request merged**
