### PR TITLE
Nar'Sie plush can't invoke now

### PR DESCRIPTION
**Pull request by YakumoChen**
## About The Pull Request
removes the ability to use a narnar plush to be an extra rune chanter.

## Why It's Good For The Game
remove powercreep
i see these in every single cult powergamer backpack, it removes half the effort of converting. 
go get a shade buddy instead

## Changelog
:cl: Yakumo Chen
balance: Nar'Sie plushes have been purged of their heretical stuffing and can't be used to invoke runes any more.
/:cl:

### CODE REVIEW

**Comment by optimumtact** [comment]
what are you the new robustin or something

**Comment by YakumoChen** [comment]
there's not enough code, fuck

**Comment by YakumoChen** [comment]
added more code.

bypassing the entire restriction of needing two people to convert by having a toy in your bag you got from a hacked chaplain vendor is needlessly powercreep.
Much less any rune that requires more than two people.

**Comment by wesoda25** [comment]
ya good PR

**Comment by bigfatbananacyclops** [comment]
just get good

**Comment by ATH1909** [comment]
Why would you encourage the keeping of a shade in your backpack? It's incredible unfun to be able to do nothing but talk as a shade because a cult member won't let you out of your stone. The existence of the plushie means that one less shade will be relegated to such a hellish existence (hopefully).

**Comment by imsxz** [comment]
spirit realm allows for solo converting and that’s a roundstart thing

**Comment by ATH1909** [comment]
Also, in case there were any misconceptions about this, only one plushie counts per rune; you can't just activate the Nar-Sie summoning rune solo by using 8 plushies.

**Comment by ATH1909** [comment]
> spirit realm allows for solo converting and that’s a roundstart thing

Also this. The plushie really just cuts out some of the jankiness and hassle.

Also, the plushie adds another "tell" for cults (hey, someone broke into my office and stole the Nar-Sie  plushie!) and requires a multitool and money to obtain (as a cultist and without admin intervention), which I think are decent downsides anyway.

**Comment by wesoda25** [comment]
Spirit realm greatly injures the caster while the rune is active.

**Comment by wesoda25** [comment]
Also this doesn’t encourage keeping a shade it encourages working together with your team aka how you were intended to succeed in cult.

**Comment by Tlaltecuhtli** [comment]
make spirit realm ghosts not count for invocation too

**Comment by bigfatbananacyclops** [comment]
there is alot of funny functions that makes it nice to learn more about objects and interaction, I wouldnt say the cakehat is a good one but there’s many that my memory cannot recall, why is this pr good for the game? Crush powergamers? Cult will still have spirit realm which can be used always, the narsie plushie is 75 credits and not any assistant can get it, i think there is different alternatives to this,  narsie plushie is a toy item and if you wouldn’t like it so accessible, then we can raise the price.  I honesty enjoy experimenting or learning about stuff in ss13 and thats what really makes me content sometimes.

**Comment by wesoda25** [comment]
What features

**Comment by YakumoChen** [comment]
>Also this. The plushie really just cuts out some of the jankiness and hassle.
Also, the plushie adds another "tell" for cults (hey, someone broke into my office and stole the Nar-Sie plushie!) and requires a multitool and money to obtain (as a cultist and without admin intervention), which I think are decent downsides anyway.

you know whats also a tell for cult powergamers

having three IDs in your bag, a cult dagger, and full security gear

stop playing with toys

**Comment by YakumoChen** [comment]
>why is this pr good for the game? 

it was introduced as a "funny interaction" that was thinly veiled and ridiculous powercreep for a mode that does not need powercreep.

I don't even know WHO did this, because they are github banned. My best guess is MRTY since it lacks the extreme bloat and needless bug denial of goofcode.

**Comment by Shadowflame909** [comment]
Meth speed got nerfed and it increases the damage by 1.5x on every attack

Good way to die to what would previously put you in the red. Like being set on fire.

If cult was OP they wouldn't have more losses then wins.

Even though I honestly didn't even know this was a thing. This antag unironically doesn't need a nerf.

**Comment by YakumoChen** [comment]
cult is just revolution easy mode

**Comment by daklj** [comment]
if you have to resort to arguments like removes powercreep or stops powergaming to justify a PR then you know your PR is shit and you have just died

also cult has 26% win rate in last month (and revolution has 38%)

**Comment by Nickkoranda** [comment]
I don't think win % should be counted for. We have multiple variables, including the event hall, that would skew the data.

**Comment by Akrilla** [comment]
Feels like more lately interesting interactions/features have been getting removed, I dunno if that's just bias though. Never seen people use this, and seen many more use the spirit realm method. Feels arbitrary. You could start removing half a dozen interesting items because it's "powercreep".

**Comment by nemvar** [comment]
tbh just remove spirit realm. Ghosting is mostly an OOC space and doesn't have a place in normal gameplay. In my vision of cult, neither spirit rune, shades nor nar'sie plush would exist. Make cultists actually work together in a fucking team mode ffs.

**Comment by YakumoChen** [comment]
If you never see it, you won't be affected by the change then. I see it almost every cult round, its only used to powergame.

**Comment by optimumtact** [comment]
lets keep it civil please

**Comment by Akrilla** [comment]
> tbh just remove spirit realm. Ghosting is mostly an OOC space and doesn't have a place in normal gameplay. In my vision of cult, neither spirit rune, shades nor nar'sie plush would exist. Make cultists actually work together in a fucking team mode ffs.

Cult's whole theme is about souls/supernatural, I think they're a good fit.

**Comment by optimumtact** [comment]
I think that's a little offtopic for this change

**Comment by HomocidlePancakes** [comment]
Remove plushie from chaps vendor. Keep the neat interaction. Problem solved.

**Comment by ExcessiveUseOfCobblestone** [comment]
> it was introduced as a "funny interaction" that was thinly veiled and ridiculous powercreep for a mode that does not need powercreep.

It was explicitly stated when PR'd either as it's own feature or as part of the narsie plushie that this functionality would be available. It was just meant to be a cute feature so please be careful how you frame this, the original author did not intend for it to be a go-to mechanic and was certainly not trying to be malicious (disclaimer: I didn't PR that).

**Comment by wesoda25** [comment]
PRed as a funny feature now its a way to solo cult. At the end of the day the only challenging factor to cult is that it requires teamwork, and stuff like this, summon all, and spirit realm all bypass that in stupid ways and it’d be nice to see them all removed/nerfed in some capacity.

**Comment by ExcessiveUseOfCobblestone** [comment]
I wasn't making a call on whether or not I think this PR was good, I'm saying please be respectful in regards to how you're framing the interaction's inception.

**Comment by ExcessiveUseOfCobblestone** [comment]
Personally I'd like to see it kept with the easy to obtain bits removed.

I'm thinking if you have an arcade in chapel it will include the plushie as a prize option.

That said, I'm fine with merging this until a middle ground PR is made since it's clear that it's becoming an issue.

**Comment by wesoda25** [comment]
Also the cult win rate doesn’t seem accurate (event hall skewing results probably accurate) bc to me, cult in its current state has been the best balanced its ever been by far.

**Comment by py01** [comment]
Balance is irrelevant, there shouldn’t be an item which lets you circumvent a major gating mechanic of the mode. If cult is weak, improve it in other areas that don’t conflict with the main mechanics.

**Comment by MrPerson** [comment]
"It lets you avoid pocket shade, which is unfun for the shade!" is an awful argument. If pocket shade sucks, it should be removed, not given a janky bypass.

**Comment by anconfuzedrock** [comment]
cult aka the only gamemode where someone can hide 4 stuns up their armsleeve that stun and mute long enough to fuck someone's butt in one stun no cuffs necessary headset can stay on, cult, yeah, cult is the one that needs bullshit removing the minimal teamwork needed for the gamemode. what happened to 3 people chanting just for a conversion?

**Comment by bigfatbananacyclops** [comment]
Sometimes spirit realm isnt that useful, ive got to be in situations where there is no ghost in dchat able to support me in spirit realm. Either because there isnt any ghosts or theyre planning to not help the cult. Cults can have 4 stuns under their sleeve, but people usually never makes holy melons which is incredibly easy to make, holy melons makes you inmune to magic and it is strong depending on the potency, that’s some funny meme feature but im not gonna joke, holy melon or chaplain sword is the great counter vs cult, it makes you completely inmune to magic and that’s the only reason it encourages people to go for batons or sec gear or just melee. Im pretty sure the cult rate is correct, cult happens to win when they have a good player leading support. There is already some nerfs for cult conversion, body drag slowdown, which is a really big one, people can see me and interfiere and its really annoying but i take it anyways.

**Comment by Shadowflame909** [comment]
So if we're aware of cults low winrate shouldn't we all be aware of how it got nerfed again by 4dplanners drag PR?

Traitor is the chumbis mode that unironically needs a nerf. Not this.

**Comment by wesoda25** [comment]
Nerf PR literally nerfed everyone and in the process made things more balanced, if you doubt this I will gladly provide numerous examples.

**Comment by wesoda25** [comment]
> Drag PR literally nerfed everyone and in the process made things more balanced, if you doubt this I will gladly provide numerous examples.

**Comment by bigfatbananacyclops** [comment]
Nerfed everyone including the cult which consists of constantly converting, and has a great impact on them.

**Comment by CRITAWAKETS** [comment]
Personally i think that the plushie should be removed from the chaplain vendor but be able to be made by the cult in some way when they get red halos. Using cloth on an altar, perhaps?

When you have red halos you dont really have too much use in conversion, and getting cloth for it can prove difficult unless you plan ahead.

**Comment by wesoda25** [comment]
>Cult can't stun and take someone across half the station

>Sec can't run into a cult base, stun someone, and drag them to brig

Simple solution would to be stealthy, make a offer rune close to the person you want to convert, etc etc.

**Comment by Shadowflame909** [comment]
More like building teleport runes in obvious places and then erasing them afterwords. But

>made things more balanced

This is a debate for another day

**Comment by YakumoChen** [comment]
>It was explicitly stated when PR'd either as it's own feature or as part of the narsie plushie that this functionality would be available. It was just meant to be a cute feature so please be careful how you frame this, the original author did not intend for it to be a go-to mechanic and was certainly not trying to be malicious (disclaimer: I didn't PR that).

Cute or not, it's become a very clear cut case of powercreep and I would rather see it removed as opposed to any sort of workaround or """compensation buff""" as it trivializes an important aspect of cult without any downside or risk. 

If you'd like to keep the interaction I suggest you code it so it says the words when chanting but doesn't count as an invoker. I am not that skilled at coding, so this is my solution.

Balance aside, there already exists multiple other ways to solo cult without needing a powergame toy. Pocket Shades can be used back against the cult and the sprit rune requires taking damage and fiddling with the rune jank, as well as having a ghost. If you can't get one of those to work, I suggest you do it how cult is actually intended and get another cultist to help.

**Comment by ExcessiveUseOfCobblestone** [comment]
It wasn't powercreep and still isn't, it was never added to compete with the rest of the game. It was just a funny interaction.

**Comment by adamkad1** [comment]
is this ided?

**Comment by ExcessiveUseOfCobblestone** [comment]
iconverted

**Pull request merged**
