### PR TITLE
Put unit tests in a box, fixes sporradic gun test failure

### PR DESCRIPTION
**Pull request by Mothblocks**
## About The Pull Request
Puts test into a box, created from a map template. In the future, this map template will ideally be customizable by tests.

This simulates the common case of testing things on a station, rather than out in space.

### CODE REVIEW

**Comment by MrDoomBringer** [comment]
Will this cause something like an explosion-unit-test to permanently affect the room? Or is the map intended to be reloaded for each test

**Comment by Mothblocks** [comment]
An explosion unit test would mess up the room, yeah, but it would have before as well. 

Something like that should either spawn its own level or set a flag to reset the testing area back to normal.

**Comment by Mickyan** [comment]
wouldn't it make more sense to use indestructible floors and walls

**Comment by Mothblocks** [comment]
The goal of tests is to be as accurate to the real world as is helpful, indestructible walls and floors are not realistic. This is the same reason I didn't just block out all atmos from coming in.

**Pull request merged**
