### PR TITLE
Removes some spawn calls from assembly code

### PR DESCRIPTION
**Pull request by Aranclanos**

### CODE REVIEW

**Comment by Core0verload** [comment]
Why do you want to remove these spawn calls? Do you know why they are there?

**Comment by MrStonedOne** [comment]
Ya, Those have a purpose, infinite loop prevention.

**Comment by Core0verload** [comment]
First two are to prevent signals getting "stuck", third prevents infinite loops.

**Comment by MrPerson** [comment]
spawn() like that is a shitty way to "fix" a bug anyway

**Comment by Core0verload** [comment]
It's neccessary. Better use some spawn() than crash server,

**Comment by MrPerson** [comment]
There are better ways to fix the bug

**Comment by Core0verload** [comment]
Name a way to fix a loop. Name a way to fix signals getting "stuck". If you can't, GTFO.

**Comment by Razharas** [comment]
@Aranclanos 
Cmon faget say something in your defence

**Comment by optimumtact** [comment]
press f to pay respects

**Comment by Razharas** [comment]
No activity from op for a month hile unreolved issues - closed

**Pull request closed without merging**
