### PR TITLE
Makes alien queen immune to hulk/mech stuns

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
The final boss of the aliens should at least be able to fight back against these things. They are literally helpless right now if either of them shows up. I know aliens aren't exactly weak, but hard counters like that aren't the way to make it fun. Alien queens can't be stunned at all now.

### CODE REVIEW

**Comment by GunHog** [comment]
Beat me to it. Honk.

**Comment by WJohn** [comment]
<3 <3 <3

**Comment by Kromgar** [comment]
Kor we know Wjohn is your waifu

**Comment by Cheridan** [comment]
> I know aliens aren't exactly weak, but hard counters like that aren't the way to make it fun. 

And rock-paper-scissors balance that you're going for here is better? :V

**Comment by Anonus** [comment]
It's the classic style of balance, so it must be doing something right.

**Comment by Steelpoint** [comment]
Eh, I mean this seems fine.

Won't stop a few laser cannon rounds from ruining a xeno's day.

**Comment by GunHog** [comment]
As a queen, I am more afraid of the atmos tech with a flamethrower than I am the RD with a laser cannon. Two hits will take me out, but I only need one to stun and tongue him. One burst from a flamethrower means that my nest burns away, and I have to retreat or die to the sheer heat.

**Comment by WJohn** [comment]
A flamethrower is pretty easy to counter though. You just need to have a bunch of resin walls for the entrance, creating a series of chokes and corners. If fire comes through, plug it with a wall and no heat will get in. Furthermore, make some holes to space, so it slows and kills people who try to get in and also destroys fires and puts you out.

**Comment by hornygranny** [comment]
:+1:

**Comment by WJohn** [comment]
This is made obsolete by gunhog's upcoming PR, which includes this and fixes some bugs related to it.

**Pull request closed without merging**
