### PR TITLE
buffs milk for skeletons and plasmamen

### PR DESCRIPTION
**Pull request by PKPenguin321**
if you are a skeleton or a plasmaman, milk will have a 100% chance of healing 1 brute damager per tick in addition to the previous 20% chance of healing 1 brute per tick

:cl: PKPenguin321
rscadd: Milk, which is good for your bones, is now extra beneficial to species that are mostly comprised of bones.
/:cl:

### CODE REVIEW

**Comment by KorPhaeron** [comment]
At least compile your code before making a PR

**Comment by PKPenguin321** [comment]
gah fuck i thought i'd just make a silly thing on the fly with the inbuilt editor, i figured it was only 3 lines what could go wrong

**Comment by PKPenguin321** [comment]
fugg

**Comment by Cheridan** [comment]
0 dmg

**Comment by KorPhaeron** [comment]
Try again when it compiles

**Comment by PKPenguin321** [comment]
mark my words kor i will be back
and i will have my milky vengeance

**Pull request closed without merging**
