### PR TITLE
Adds crafting blindfolds, hacked autodrobes contain a blindfold and muzzles

### PR DESCRIPTION
**Pull request by anconfuzedrock**
:cl: 
rsadd: you can now craft blindfolds out of cloth.
rsadd: blindfolds/muzzles can be found in hacked autodrobes.
/:cl: 
I hope I did the changelog right, its 2 cloth for a blindfold, 1 blindfold in autodrobe, 2 muzzles. originally there was only gonna be the blindfold in the autodrobe but I realised I had no idea where else to add a way to get muzzles on all maps.

### CODE REVIEW

**Comment by Haevacht** [comment]
Rule 8 Banned.

**Comment by bgobandit** [comment]
the lizard makes this PR

suspicious

**Comment by anconfuzedrock** [comment]
for the record I only want the blindfold for isaac memes https://hydra-media.cursecdn.com/bindingofisaacrebirth.gamepedia.com/9/9d/Lilith_App.png?version=b88bce7f3312e0044378e7ca31572c31 and that made me think of how its impossible to get muzzles too

**Comment by Anonmare** [comment]
Is the new cult meta to stun, muzzle and convert?

**Comment by anconfuzedrock** [comment]
no because thunder talked me out of making it possible to make muzzles out of cloth

**Comment by Cheridan** [comment]
Wait, are they craftable or not?

**Comment by anconfuzedrock** [comment]
what whatd i do wrong

**Comment by anconfuzedrock** [comment]
I think I fixed it

**Comment by anconfuzedrock** [comment]
alright nevermind its ok

**Pull request merged**
