### PR TITLE
Readds bz canisters to cargo order packs

### PR DESCRIPTION
**Pull request by improvedname**
i dont know why it was removed but it auctall had an use

:cl: improvedname
add: Adds bz to cargo
/:cl:

[why]: # (Please add a short description [two lines down] of why you think these changes would benefit the game. If you can't justify it in words, it might not be worth adding.)

Lets be honest here, BZ has one use and thats stopping slimes from functioning at all.
and yes i know you can make it at atmos, but honest its to much of an hassle for that one purpose and it had great use at xenobiology so your slimes wouldn't starve as you did your work.

### CODE REVIEW

**Comment by ExcessiveUseOfCobblestone** [comment]
oh come on BZ had one use and that was to grief.

also this allows you to skip the whole "making your own BZ" for the purpose of stimulum, not to have and hold BZ.

**Review by Tlaltecuhtli — CHANGES_REQUESTED** [review]
change your profile pic if u want this meged

**Comment by improvedname** [comment]
@ExcessiveUseOfCobblestone players actions have nothing to do with the feature it auctally had and that was stopping slimes from metabolozing.

**Comment by improvedname** [comment]
@Tlaltecuhtli please have something usefull to say.

**Comment by Tlaltecuhtli** [comment]
what is bz anyway and why it costs 2000 money

**Comment by ExcessiveUseOfCobblestone** [comment]
BZ is a hallucination gas which has use in the SM (iirc) and xeno (for sure).

It's also used in the production of stimulum which is my only real concern with this. Just make it cost a bit more than 2K, I got to get around to messing with exports/cargonomy.

**Comment by improvedname** [comment]
ill increase it to its former prize before i had buffed it which is 4000

**Comment by XDTM** [comment]
i just want people to see my precious hallucinations

**Review by Tlaltecuhtli — APPROVED** [review]

**Comment by Potato-Masher** [comment]
Goodie, more chances for hallucinations to happen so I can plant C4 on them. Ghostly floating C4 is no joke, you know.

**Comment by Buggy123** [comment]
@ExcessiveUseOfCobblestone 
I thought that since fusion is disabled, stimulum is so astounding painful to make that no one ever bothers with it.

**Comment by ExcessiveUseOfCobblestone** [comment]
Probably correct. I haven't bothered trying to make it myself.

**Comment by Buggy123** [comment]
I honestly had to check to see if it was even still possible, I _think_ it is but I sure as hell wouldn't want to make it now that the 10 minute recipe for 99.9% pure stim is broken. Its a pretty shitty stimulant tbh, if i want stun immunity i'll go get a bot that autoinjects meth instead.

**Comment by Robustin** [comment]
>Removing one of the only reasons for atmos to exist

**Comment by improvedname** [comment]
Sorry oldman should i remove water vapor from cargo for you?

**Comment by DaxDupont** [comment]
@improvedname but he loves water and water slips

**Comment by improvedname** [comment]
@Robustin withen that reason i might aswell remove every gas from cargo. Oxygen, Plasma, Nitrious Oxide, Nitrogen. And don't pretend atmos auctally ever makes the bz gas for the xenobiologist that needed it yhey just get a fire axe and fuck off somewhere

**Comment by Robustin** [comment]
I would be fine if we pulled every gas from Cargo honestly, its just clutter and redundancy. But at least those are basic gases.

The point is that BZ is not supposed to be easy to obtain, making it a button click defeats one of the only recipes that atmos is in a unique position to produce.

**Comment by improvedname** [comment]
Yes i agree with you robustin it will make a job pointless, but that wouldn't be the case if the atmos tech auctall did their job most of the times so this is needed.

**Comment by Bawhoppen** [comment]
As much as I love giving everything to cargo (which we seem to have an aversion to doing), this probably does ruin the whole atmos gas creation process a little too much.

**Comment by XDTM** [comment]
On the other hand, it's nice to give cargo the niche of being a way to skip some job progression, for a price

**Comment by KorPhaeron** [comment]
If cargo prices meant anything sure

Exports+stock market+techweb disks completely broke the prices

**Comment by XDTM** [comment]
maybe we should go back to periodic station budget, and maybe completing random tasks for NT the allowance would increase

like station projects lite

**Comment by Bawhoppen** [comment]
Would need a complete overhaul, not incremental change, that's for sure.

**Comment by CrackParrot** [comment]
Or how about we tweak and re-add fusion instead, so it can give the atmos techs a chance to be useful?

**Comment by ExcessiveUseOfCobblestone** [comment]
@XDTM The future of cargo is Tycoon Cargo

**Pull request merged**
