### PR TITLE
(Testmerge) The Chef can now deliver food to prisoners easily!

### PR DESCRIPTION
**Pull request by Iamgoofball**
All he has to do is drop food down the prison chute, and it'll be safely delievered to prisoners!

_Warning: Do not put carbon or silicon based lifeforms down the chute._

Example:
https://file.house/o_Dt.webm

### CODE REVIEW

**Comment by ninjanomnom** [comment]
freeze

**Comment by PKPenguin321** [comment]
But I want it

**Comment by PKPenguin321** [comment]
Can the special disposal pipe be moved elsewhere so I can make devilish disposal traps

**Comment by Buggy123** [comment]
Agreed, this is pretty great, and if it can't be added now because of the freeze I'd like it if it was reopened afterwards.

log(8, X) means the logarithm of base 8, right? If so, I'm thinking the only way to get a strangelet loaf would be lots and lots of recursion? You'd have to throw millions of things into the machine to get a strangelet loaf otherwise.

**Comment by YakumoChen** [comment]
why are we giving prisoners esword wall-destroying weapons though

**Comment by Rinoka** [comment]
... Because it's SS13?

To be real with you, though, from skimming the code? It looks like this might take actual investment to make ridiculous loaves, so there's not really anything to say against it. And if the sec doesn't like the chef hurling easy-escape items down the hatch, then... brig 'em, or break the disposals pipe? C'mon, now.

**Comment by Shadowlight213** [comment]
OOC: Sartorius7: Also since goof was too much of a shit to notice the bug with the publicly available version of the loafer, do not switch it to nugget mode, it will create a grey goo of nuggets that will infinitely duplicate themselves and give you so many runtimes that the server WILL crash

**Comment by Sartorius7** [comment]
Except the loafer deletes itself when switched to nugget mode so this isn't an issue.

**Comment by MoreRobustThanYou** [comment]
@Iamgoofball reopen this shit

**Comment by Buggy123** [comment]
there's no feature freeze now, reopen please.

**Comment by F-OS** [comment]
this code is balanced for goon, aka ss13 arcade mode where most rounds have 30 players and last 30-40 minutes, therefore the force values are kinda cancer, before a reopen @Iamgoofball needs to balance this for tg

**Comment by Iamgoofball** [comment]
no

**Pull request closed without merging**
