### PR TITLE
Removes the upgraded h2 axe

### PR DESCRIPTION
**Pull request by LemonInTheDark**
## About The Pull Request
Removes the upgraded version of the h2 axe, the one with lifesteal
I intended to clear this up before the pr adding this got merged, but I overslept. Don't ask

## Why It's Good For The Game

It's a very hard to get tool, but it's just kinda like, a fire axe but with slightly more damage and lifesteal. Endgame atmos content should be atmos related, not just a good weapon. Also it's way too time consuming to acquire, so its overpoweredness is balanced by its rarity. I don't like tools that are setup like this, since they just end up bloating wiki articles.

## Changelog
:cl:
del: Removes the upgraded hydrogen axe
/:cl:

### CODE REVIEW

**Comment by GuillaumePrata** [comment]
I love you

**Comment by LemonInTheDark** [comment]
I love me too

**Comment by ATH1909** [comment]
> Endgame atmos content should be atmos related, not just a good weapon.

I mean, atmos houses one of the two roundstart fire axes on most maps, and they are called FIRE axes. I think that's enough for a valid connection.

**Comment by Tlaltecuhtli** [comment]
doesnt seem that op when a chainsaw made out of autolathe does same damage, or bone axe maded by killing 3 watchers

**Comment by ATH1909** [comment]
> Also it's way too time consuming to acquire, so its overpoweredness is balanced by its rarity.

... So it's balanced, no? Like, this isn't one-shotting people or anything, it's just an upgraded fire axe that gives you a bit of health back when you hit people with it. You could make it tendril loot and no one would bat an eye.

> I don't like tools that are setup like this, since they just end up bloating wiki articles.

I mean, an entry for upgraded h2 fire axes would take up... one sentence (in the wiki's description for normal h2 fire axes), or maybe a single table entry at most? I really don't see wiki bloat as being an excuse here. Hell, I don't think upgraded h2 fire axes are even ON the wiki currently, which is probably why you usually don't see anyone making them. By this logic, the plushie relationship code should be removed because it would bloat the wiki if we put it on there.

**Comment by LemonInTheDark** [comment]
> ... So it's balanced, no? Like, this isn't one-shotting people or anything, it's just an upgraded fire axe that gives you a bit of health back when you hit people with it. You could make it tendril loot and no one would bat an eye.
> 
> I mean, an entry for upgraded h2 fire axes would take up... one sentence (in the wiki's description for normal h2 fire axes), or maybe a single table entry at most? I really don't see wiki bloat as being an excuse here. Hell, I don't think upgraded h2 fire axes are even ON the wiki currently, which is probably why you usually don't see anyone making them. By this logic, the plushie relationship code should be removed because it would bloat the wiki if we put it on there.

I want to keep atmos the role trim, and focused on maintaining the station. This doesn't help with either of those problems, and if it was ever documented enough to be used would just end up being noise to someone trying to understand the role. Adding endgame content that won't ever be used isn't a good way to move forward.

**Comment by GuillaumePrata** [comment]
I just don't like when end content is used to as a "selfish goal" on a job that should be about round maintenance.
Engineering, like Medbay and Security, exists mostly to keep the round working and if they have incentives to move away from that to work on selfish pet projects it just goes against the intent of the role IMO.
I personally hate this axe because it looks like mining loot already and people joining as atmos, ignoring breaches and alarms to make a mining items is silly.

**Comment by Ghilker** [comment]
Oh no! You're gonna "axe" it! 
IMG_20210306_092841_563

**Comment by Kylerace** [comment]
> 
> 
> Oh no! You're gonna "axe" it!
> IMG_20210306_092841_563

potato already made that joke look at the branch name silly

**Comment by Ghilker** [comment]
> > Oh no! You're gonna "axe" it!
> 
> potato already made that joke look at the branch name silly

That's why I made the comment ¬¬

**Comment by Sethnov** [comment]
its not that hard to get though

**Review by 81Denton — APPROVED** [review]
A little bloat is ok as a treat, but not when it's completely incoherent and only obtainable through autism projects that have no connection to the rest of the game.

**Review by Twaticus — APPROVED** [review]
🙂

**Review by Mothblocks — APPROVED** [review]

**Review by Cyprex — APPROVED** [review]

**Comment by Cyberboss** [comment]
Conflicts

**Comment by DrCrawler** [comment]
NOOOOOOOOOOOOOOOOO, NOT THE H2 AXE, WHYYYYYYYYYYYY. I DEMAND NEW AXE THEN. Like realy, readd something like the axe. It was an op weapon and there is only 2 slightly weaker versions... THE NORMAL AXES. Why have _2_ normal axes then? Lets make axes printable. You get what im talking about? Axe is the strongest melee a normal spessman can get. H2 axes can be _M A D E_ with _L I M I T E D_ resources. I hope it gets reverted...

**Comment by LemonInTheDark** [comment]
Hell I didn't even remove the normal h2 axe, you're giving me ideas tho.

**Comment by Mothblocks** [comment]
i think you should

**Comment by Sethnov** [comment]
please dont remove h2 axe you break my heart as a atmos main

**Comment by Mothblocks** [comment]
in the near future you'll be getting fun gameplay instead 😃

**Comment by Sethnov** [comment]
sounds like goon where they don't have atmospherics, i like my gameplay about gasses and only gasses, the station having nuke ops, nah man, my atmos is more important lol.

**Pull request merged**
