### PR TITLE
[MAP] Boxstation HoS/CMO Hardsuit + RD's Prototype Bombsuit

### LINKED ISSUE #12120: misplaced gas flow meter
in maint east of the gateway there is a gas flow meter not connected to any pipes presumably broken in the recent piping overhaul

it just looks ugly and out of place and can make people who don't know about it think somebody is fucking with atmos

Server sybil

server revision c9433333ce605e1b0afc9e73e9e4d3aaedeebb0f

scrnshot1

its right above the ghost in the center

### LINKED ISSUE #12239: Nuke terminal layer same as alien weed layer
As a result, the terminal sprite will disappear underneath the weed sprite apparently.

### PR DESCRIPTION
**Pull request by Steelpoint**
With the introduction of map rotation and voting I noticed quickly how every single non-box map (barring Ministation due to no HoS Position) has a HoS and CMO hardsuit in their office.

Considering this I am proposing to bring Boxstation in line with every other map we have and to give the HoS/CMO a personal hardsuit, this spawns inside his office akin to all other maps.

This PR also removes the command EVA space suits.

In addition this PR adds the RD's Prototype Bombsuit to his office.

screenshot 2015-10-09 13 14 25

screenshot 2015-10-09 13 37 55

screenshot 2015-10-10 09 23 08

screenshot 2015-10-09 13 37 52

Also.
Fixes #12239
Fixes #12120

### CODE REVIEW

**Comment by optimumtact** [comment]
:-1: this is a reason to remove them from the other maps, not add them to box.

**Comment by PKPenguin321** [comment]
>this is a reason to remove them from the other maps, not add them to box.

emptyquote

**Comment by Bawhoppen** [comment]
Remove command EVA if you do this, because now the HOS, RD both have suits

**Comment by Steelpoint** [comment]
I may as well toss the CMO his Hardsuit and remove the command EVA suits.

**Comment by KorPhaeron** [comment]
Security needs jetpacks more than they need more hardsuits if you're gonna go through the fight of another sec buff PR.

Clunky slow suits aren't worth much if the other guys are moving at OLDSPEED with no obstructions.

**Comment by Steelpoint** [comment]
I would have a easier time of putting in a HoS/CMO Hardsuit than giving Security easy to access jetpacks.

**Comment by KorPhaeron** [comment]
Well it's your fight/PR, but it will have negligible in game impact since the HoS already has access to a slow (and therefore useless for combat) hardsuit. Doesn't seem worth the arguments this is going to start.

**Comment by Steelpoint** [comment]
Well I could give the HoS/Sec hardsuits a built in jetpack akin to other hardsuits.

Don't engi hardsuits have that?

**Comment by KorPhaeron** [comment]
In built jetpacks are dumb. The jetpack is a massive advantage, giving up your backpack slot is a fair trade off for free movement.

**Comment by Steelpoint** [comment]
True, I can look at it but I don't know, as I said I think trying to give sec even a single jetpack is going to be more resisted than just a Hardsuit.

**Comment by Dorsisdwarf** [comment]
:+1: 

why not it's not gonna make a difference

**Comment by WJohn** [comment]
The HoS hardsuit should absolutely not be tucked away behind the tables like that, you know better than that by now. Put it above the locker and move that table's contents to the corner.

**Comment by Steelpoint** [comment]
Its very easily accessible and does not disturb the layout of the rest of the room.

Also some other maps tend to tuck it in the corner.

**Comment by WJohn** [comment]
It's just sort of a common no-no to tuck some form of locker or computer behind tables, it's very rarely done anywhere else and frankly just looks ugly.

**Comment by Steelpoint** [comment]
screenshot 2015-10-09 14 52 22

**Comment by WJohn** [comment]
Thank you, much appreciated.

**Comment by GunHog** [comment]
I am quite upset about this, Steelpoint. I had asked WJohn to do this for me to get the RD hardsuit in the map and Medical hardsuit for the CMO, in exchange for removing Command EVA.

I had been waiting for a chance to get the change PR'ed since the code for it got merged, but the armory PRs were in the way, along with the bugfix. I may never get the chance now, if this one goes through :/

Would you at least add the RD hardsuit to this? If your reasoning is to have Box in line with the other maps, notice that I had made the same request and had mine added to each alt map as well. To keep the hardsuit count the same, you could consider replacing the extra hardsuit in the armory with the HoS suit - only two people had natural armory access anyway, you and the warden.

**Comment by Steelpoint** [comment]
I thought the RD Bombsuit was already on the map, though I guess I missed that your PR only added it to the code and not on the map.

I'll put the RD Bombsuit in his office.

**Comment by GunHog** [comment]
Oh, well, I have no objections, then :+1: Command EVA's spot could stand to be more pretty or not look like it was just ripped out or something (That is a true statement, but still...)

**Comment by Steelpoint** [comment]
Hopefully the changelog works.

screenshot 2015-10-09 20 00 18

**Comment by xxalpha** [comment]
Steelpoint, since you're making a map edit, make the self-destruct nuke a default instance. Currently it is edited to be on layer 2, it should be on layer 4 by default.

**Comment by WJohn** [comment]
And while you're at it would you mind fixing #12120? It's a super fast and easy fix for both of these.

**Comment by Steelpoint** [comment]
Note to self, redo piping so its easier to get around the station instead of having to detour 10,000 light years around.

**Comment by WJohn** [comment]
Steelpoint I literally JUST redid piping like a week or two ago.

**Comment by Steelpoint** [comment]
I know, the problem there is that under both of our pipe layouts, and even the one before I did the massive overhaul, that they were both not really designed with being able to use them to move around the station in mind.

They serve their purpose of supplying air but using them to vent crawl is a serious pain.

**Comment by Steelpoint** [comment]
The Nuclear Detonation is now on layer 4, and the gas flow meter has been moved over a actual pipe.

**Comment by xxalpha** [comment]
Put 

Fixes https://github.com/tgstation/-tg-station/issues/12239
Fixes https://github.com/tgstation/-tg-station/issues/12120

In the OP so they are closed automatically.

**Comment by GunHog** [comment]
I know this is <b>Super</b> nitpicky, but if you do decide to change the map again because of something else, would you please swap the file cabinet with the suit storage, or perhaps put the potted plant where the SSU currently is, the SSU in the corner where the cabinet is, and the cabinet by the door where the plant is?

The cabinet being near the papers, pen and stamp makes sense, the SSU in the corner near the equipment locker, and the plant for decoration near Lamarr's cage.

It is not a big deal, just a "while you are in the neighborhood" kind of thing.

**Comment by Steelpoint** [comment]
Only problem with moving the pot plant away from its current location and placing the cabnit there is that it makes accessing the wiring underneath the room's APC harder,

Its a bit of a edge case but it might be relevant considering the proximity to Toxins and the rooms relevance during a Malfunctioning or Subverted AI.

**Comment by GunHog** [comment]
Oh, you have a good point there. Maybe you could leave the plant where it is, move the cabinet to the top left corner of the office, putting the stamp with the bin and pen, and have the SSU be in the bottom right corner?

**Comment by Steelpoint** [comment]
I'll look to shifting things around.

**Comment by Steelpoint** [comment]
Am I imagining things or did someone set it so that virtually every single door on the station is a glass airlock?

**Comment by WJohn** [comment]
They're not glass airlocks, steelpoint. We just changed it so airlocks are now handled as overlays (this includes whether they have a solid or glass fill). Since the map maker doesn't show overlays, we're left with fairly basic shells of the airlocks.

**Comment by Steelpoint** [comment]
Very good.

**Comment by pudl** [comment]
The piping shouldn't revolve around easy use for antagonists. New vent crawling is awful and maybe whoever ported it should have had the foresight to know that this would happen. Sacrificing the integrity of a smooth, easy to repair atmos that helps out with repairs and engineering isn't worth yet another fucking buff to aliens or monkeys or whatever so they can be absolutely everywhere, as always.

**Comment by Steelpoint** [comment]
screenshot 2015-10-10 09 23 08

That's it.

The PR is merge ready.

**Comment by PKPenguin321** [comment]
i still dont get why the RD needs a hardsuit aside from the fact that gunhog plays RD a lot

**Comment by GunHog** [comment]
Greet work Steelpoint, thank you!

**Comment by MrPerson** [comment]
Yeah I gotta agree. The RD does not need a hardsuit by any stretch of the imagination.

**Comment by Steelpoint** [comment]
While I'm no RD player it can give some great versatility to RD's in certain circumstances. Such as helping out in fixing damage after a failed Toxins incident, and being among the firs responder to a crisis. Also it can help if a bomb does not properly detonate on the testing range and the RD wants to check it out.

It's really just a literal bombsuit that has space protection, it offers no real protection to anything else.

The difference between this suit and anyone else is that if a bomb goes off near the user, everyone else will be gibbed while the user's naked corpse will be flung 100 kph in a random direction.

**Comment by Steelpoint** [comment]
While I'm fixing this merge conflict I'm going to touch the armoury.

Nothing serious, just mainly to place flashers down inside auxiliary tool storage.

**Comment by Steelpoint** [comment]
Also the suit storage's need to move, they block the APC.

**Comment by Steelpoint** [comment]
All good, only new change here is that the armoury saw a minor shift around in equipment, in addition to the Aux Sec Storage was readded to the evidence room with the secway and flashers and other (good lights) equipment.

Pic.

screenshot 2015-10-10 20 39 50

**Comment by Bawhoppen** [comment]
good work steelpoint, modifying a PR that was just supposed to give HOS a suit in order to fulfill your sick armory agenda

seriously though don't fucking change the armory, leave the flashers in there and leave evidence storage alone where it fucking works

**Comment by Steelpoint** [comment]
The Flashers were not in there, that was the problem I noticed.

**Comment by Steelpoint** [comment]
I mean jesus, of course I'm going to pick up on minor and anoying issues with Security when I PLAY as the role.

Just as anyone would for their more played role.

**Comment by Steelpoint** [comment]
Also note to self, next PR readd bulletproof armour back to the armoury.

**Comment by Bawhoppen** [comment]
Steelpoint, don't destroy evidence storage just because YOU think its not necessary.
Its there for RP, Gameplay, and Balance reasons, That where you're obviously supposed to put evidence for trials and such, and thats another entry point into security through that window out of view from the main brig, and you can hide in the lockers.

**Comment by Bawhoppen** [comment]
Also the flashers are in the security office.

**Comment by Steelpoint** [comment]
Most people make a entry point into the brig by breaking down the windows or storming the entrance.

Evidence Storage is rarely used for anything aside from tossing a empty backpack into it, and anything of value is usually stored in the armoury or on the person of the officer who found the item.

The room is still all access and it's still just as viable to break into it from the outside now as it was before.

Also, I did note the flashers being in the sec officer and as I said that's a bad decision, they should be held in storage and I think sec aux storage is more thematic, also I like the extra light bulbs.

**Comment by Bawhoppen** [comment]
Just because a feature like evidence storage doesn't see that much use from players, does not mean it should exist. Its not all about being the most efficient, or who can win the most. Evidence storage should stay. If you want to add an aux storage thats fine, but don't replace evidence room.

**Comment by optimumtact** [comment]
Bawhoppen has a point, we don't have to justify every single feature by it's gameplay Steelpoint.

**Comment by pudl** [comment]
How about you get your fat greasy fingers off of the armory and I'll do it myself in a PR so your PR is actually not a piece of shit for once.

**Comment by GunHog** [comment]
As absolutely *painful* as it is to agree with QQ/pudl/allura, he is right - this is not an armory PR, and it will only be held back several days or even closed if changes to the armory were to be added here. Please finalize this PR and request a review before more conflicting PRs pop up!

**Comment by pudl** [comment]
-_- I thought we were friends, guess I was wrong.

**Comment by GunHog** [comment]
And now I feel like a jerk. Well, I guess I have been a jerk. I am sorry. I have just always noted that we do not really agree much on things, it is quite rare!

**Comment by WJohn** [comment]
I'd be fine with merging this if you did away with the armory change, that's a separate highly controversial PR all on its own.

**Comment by pudl** [comment]
@WJohn How about you also tell him that making the place where command suits used to be a weird derelict thing is dumb too, because keeping a little cranny for something that wasn't actually historical (like the old grav gen room before it was re purposed) is dumb.

**Comment by GunHog** [comment]
We never did address that. Command EVA is now a pimple just hanging off. It should be a supply room or something.

**Comment by pudl** [comment]
The way he still hasn't reverted it. -_- smh

**Comment by Steelpoint** [comment]
Maybe because I have sleep and work requirements?

Can't be on all the time.

**Comment by Steelpoint** [comment]
Armoury changes were reverted.

Also Pudl you really should have waited for this PR to be finished, merge conflicts and all.

**Comment by WJohn** [comment]
I appreciate the armory being split into its own PR. The last thing to clean up here is that EVA. I wouldn't be too bummed out merging it as-is, but I hope I'm not asking you too much if you could change it into something functional. Maybe some EVA equipment storage of sorts, like medkits or whatever. I'm sure you can think up of a theme for that storage area.

**Comment by Steelpoint** [comment]
Ok I'll look into that.

**Comment by Steelpoint** [comment]
I've renamed the area into Command Tool Storage and remade the former Suit Storage room.

screenshot 2015-10-11 18 21 59

**Comment by GunHog** [comment]
It is better than being an empty, ripped out room :+1:

**Comment by Steelpoint** [comment]
I would appreciate this be merged/reviewed before the inevitable merge conflict.

Thanks in advance.

**Pull request merged**
