### PR TITLE
Fixes mineral wall icons.

### LINKED ISSUE #10509: Mineral Wall smoothing errors
sybil muppet installation xviii 2015-07-10 154503
Due to their stripes, mineral walls smooth rather badly and turn into a jumbled mess. I'd suggest removing the stripes altogether from them, along with the center corner that was taken out of normal and r-walls.

@WJohn @xxalpha

### PR DESCRIPTION
**Pull request by WJohn**
What it says on the tin. Mineral walls were not originally designed to handle the new smoothing system we put in place, so they looked very ugly (and I knew this ahead of time) but we were tired and wanted to get this in before conflicts would pour in. I've had the time to fix em up now, at least until someone actually redoes mineral walls as a whole because holy shit are they ugly.

Also fixes minor shading issue with inside wood table corners, and changes map maker carpet sprite to the full tile thing we had before instead of all closed off like that.

Fixes #10509

### CODE REVIEW

**Comment by duncathan** [comment]
Screenshots?

**Comment by WJohn** [comment]
Augh getting screenshots will take forever but okay. They look like the sprites in the issue except without the lines or the central chunks in the 2x2 walls.

**Comment by WJohn** [comment]
I goofed up slightly on the uranium/plasma walls but it's still better than what we had and I can't be arsed to go back and redo the whole damn thing blegh.

**Comment by duncathan** [comment]
Looks much better. The uranium/plasma thing can be fixed if someone redoes the sprites.
:+1:

**Pull request merged**
