### PR TITLE
Raises LSG cooldown

### LINKED ISSUE #14265: The wizard Moist Nugget thing is really strong
They can just shoot massive chains of bullet hell everywhere, could definitely use a nerf.

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
To 75 seconds.

If people think raising the cost is a better solution instead that is also fine by me

Fixes #14265

### CODE REVIEW

**Comment by WJohn** [comment]
This thing is more powerful than ei nath.

**Comment by KorPhaeron** [comment]
@WJohn 

Wizards most powerful spells are their mobility (jaunt and blink and stuff), not EI NATH anyway

**Comment by optimumtact** [comment]
What a load of lies kor

**Comment by KorPhaeron** [comment]
1v1 wizard mid

**Comment by Anonus** [comment]
>most powerful
fight my fukken smoke forcewall blind scrying orb wizard I dare ya

**Comment by Aranclanos** [comment]
don't make fake issue reports to push balance changes please

**Comment by lzimann** [comment]
Well the problem is that this spell is broken how it is.

**Comment by KorPhaeron** [comment]
Jalleo> KorPhaeron your gun summon spell for the wiz is too strong
<KorPhaeron> probably
<KorPhaeron> I'm not sure if I'm alowed to nerf it though
<Cheridan> ehh
<Jalleo> its more like tiny balance changes
<Cheridan> if its something that's like horribly gamebreaking then sure fix it
<Antur> it's wizard
<Antur> that doesn't even need balance
<Jalleo> Cheridan it is a bit ill explain in a little bit
<Cheridan> but i'd rather people not get caught up in stuff like balance wars during freeze

**Comment by optimumtact** [comment]
it's not broken you terrorist liar

**Pull request closed without merging**
