### PR TITLE
The Wizard's Den now has dynamic lighting

### PR DESCRIPTION
**Pull request by ChangelingRain**
someone complained at me on irc about this and I had in fact forgotten the lighting

### CODE REVIEW

**Comment by kevinz000** [comment]
Thanks nya

**Comment by KorPhaeron** [comment]
@ChangelingRain 

Do the lava forges glow red yet I have not kept track

**Comment by ChangelingRain** [comment]
They do!

**Comment by WJohn** [comment]
does this shuttle even have lights to start with? wouldn't he be in the dark?

**Comment by ChangelingRain** [comment]
It has lights, yes.

**Pull request merged**
