### PR TITLE
[DNM] Remove ping counter, as an experiment to see if it fixes the auto reconnect issue

### PR DESCRIPTION
**Pull request by Mothblocks**
## About The Pull Request
Removes the ping counter to see if it will fix the reconnect issue.

With @stylemistake 's review, I will test merge this. If it works, I'm thinking just move the `roundrestart` message to not when the server is restarting, but when the round ends. You don't really have any reason to know your ping at that point anyway.

### CODE REVIEW

**Comment by stylemistake** [comment]
Good enough for the testmerge, tell me how it goes.

**Comment by Mothblocks** [comment]
Test merging on Bagil and Sybil.

**Comment by Timberpoes** [comment]
Failed to autoreconnect Round ID: 156573

No reconnect button appeared.

Had to reconnect manually using Options and Messages window
image

**Comment by optimumtact** [comment]
I suspect it's something else initiating a send during that period but I don't have a good theory on what it might be, hrefs getting played back when the history loads maybe?

**Comment by Mothblocks** [comment]
@Timberpoes Did this happen on more than one round? Do other people report this happening? I just woke up, but I can play a round later today to see if I get the same issue. If so, I'll close the PR and try something else, maybe just blocking `sendMessage` when the round is restarting or something.

**Comment by Timberpoes** [comment]
> 
> 
> @Timberpoes Did this happen on more than one round? Do other people report this happening? I just woke up, but I can play a round later today to see if I get the same issue. If so, I'll close the PR and try something else, maybe just blocking `sendMessage` when the round is restarting or something.

image

Same again Round ID: 156575

Did not reconnect, no reconnect option in chat.

Nobody else has reported it, but I'm not sure people are aware and/or are probably just used to the jank. I doubt anyone outside of the coding circle even knows it's TMed.

**Comment by Mothblocks** [comment]
Good enough for me :+1:

**Comment by stylemistake** [comment]
> Did not reconnect, no reconnect option in chat.

Looks like a different issue, that is probably no longer caused by tgchat.

Original error message looked like this:
image

**Pull request closed without merging**
