### PR TITLE
Updates Wirebrush Sprite, removes unused advanced wirebrush sprite

### PR DESCRIPTION
**Pull request by kinneb**
## About The Pull Request
Resprites the wirebrush!
Old Sprite:
image
New sprite:
image
image

## Why It's Good For The Game
Resprites coder sprites, makes them look better.
Removes old and unused coder sprite. Rest in peace.
## Changelog
:cl:
imageadd: Resprites the Wirebrush
imagedel: Removes the sprite for the Advanced Wirebrush
/:cl:

### CODE REVIEW

**Comment by Helg2** [comment]
Can you show how it looks in-game?

**Comment by kinneb** [comment]
alright, i think im being stupid with these merge conflicts, and i know whats causing them

**Comment by VladinXXV** [comment]
for a second there you almost had me convinced the advanced wirebrush wasnt removed. rest in piss.

**Review by Imaginos16 — APPROVED** [review]
Very nice work!

**Comment by LSommers** [comment]
Looks nothing like an actual wire brush, looks more like an oversized single-row comb. Bristles don't even look like wire, which is why a wire brush is _called_ a wire brush. It's got wire bristles. The "coder sprite" looks more like the one in my house than whatever in god's name that's supposed to be.

**Comment by san7890** [comment]
in the year 2563 wirebrushes were acquired by "big toothbrush"

**Comment by LSommers** [comment]
Had a surprisingly productive chat with Kinneb on discord 
Hope to see some tweaks to the sprite soon to reach a happy medium

**Pull request merged**
