### PR TITLE
Removes all but the barebones timers for runechat

### PR DESCRIPTION
**Pull request by LemonInTheDark**
## About The Pull Request

Instead of using timers to trigger the fadeout, we use animate() 
We start by queuing up all our alpha fades, then if we are shortened, we calculate the alpha we should be at, set our alpha to that, then animate from there to 0

This requires ANIMATION_PARALLEL on the pixel offsets to ensure they don't reset the alpha animation, and it does mean that a second alpha animate could reset the pixels, but that's a chance I'm willing to take.

The timer work here was almost all of the cost, this should reduce the overhead of this proc signficantly, making runechat more fit for use under high stress.

I have got it to end slightly early, but it's very minor and I've only seen it once, so yaknow, good enough.

## Why It's Good For The Game

Speeeed

## Changelog
:cl:
refactor: runechat should be a lot cheaper on the server. I've changed how it functions, if it behaves weird yell at me please don't just ignore it
/:cl:

### CODE REVIEW

**Comment by Kylerace** [comment]
https://user-images.githubusercontent.com/15794172/229337112-2180de13-15bc-43ce-a38f-c0365dc7d6b4.mp4
tested to confirm it looks fine on local, it might not on live due to ping but its already further than my attempt

**Comment by san7890** [comment]
should we TM this or is this good to ship

**Comment by LemonInTheDark** [comment]
We could tm sure, that'd be a good shittest

**Comment by LemonInTheDark** [comment]
Seems to work alright, wait 12 hours to see if we get reports maybe?

**Pull request merged**
