### PR TITLE
Adds new traitor objectives involving calling the shuttle.

### PR DESCRIPTION
**Pull request by lordpidey**
Adds a set of traitor objectives regarding calling the shuttle.

They're set to be relatively rare, because of how disruptive they can be.

Also adds a gamemode where all traitors have to get the shuttle called at the thirty minute mark.  It's called "Clusterfuck"

:cl: lordpidey
add: Added new traitor objectives involving minimizing the number of shuttle calls, or calling the shuttle a specific number of times.
add: Added new traitor objectives involving calling the shuttle within a set period of time.
add: Added new out of rotation gamemode where all traitors have the same objective, to get the shuttle called at the thirty minute mark.
/:cl:

### CODE REVIEW

**Comment by Jared-Fogle** [comment]
fuck no. players should decide when shuttle gets called. we're trying to make rounds last longer and SOLVE the 20-30 minute shuttle calls.

**Comment by LemonInTheDark** [comment]
Why is this good for the game?

**Comment by lordpidey** [comment]
That's why every call objective has a MINIMUM time until shuttle call.

There's a good chance the traitors will be trying to extend the round with this objective.

**Comment by Jared-Fogle** [comment]
I don't WANT traitors extending the round past what players want either. I don't want them ending it sooner either. Admins already get pissed at antags for repeatedly recalling the shuttle when basically everyone is dead. We don't need the game encouraging this.

**Comment by lordpidey** [comment]
> Why is this good for the game?

While yes, this will get stale fast if they happen often, having these objectives exist, and be relatively rare should introduce significant variety into the gameplay.

Take a look at the objectives, they're the rarest objective to have.

Plus, it adds a new gamemode that will be admin only (at least it's intended to be admin only) to have a very hectic thirty minute mark.

**Comment by Jared-Fogle** [comment]
I don't care if it's rare, it's harmful to the game we're trying to craft. "It's stupid, but it's rare, so it's fine" is a design axiom that we've been trying to eliminate over recent time.

> Plus, it adds a new gamemode that will be admin only (at least it's intended to be admin only) to have a very hectic thirty minute mark.

Admins can already do whatever bus crap they want to get a thirty minute round, they do it often.

**Comment by optimumtact** [comment]
I'm strongly opposed to any kind of mechanics that encourage shuttle calls

:-1:

**Comment by LemonInTheDark** [comment]
> 
> 
> > Why is this good for the game?
> 
> While yes, this will get stale fast if they happen often, having these objectives exist, and be relatively rare should introduce significant variety into the gameplay.
> 
> Take a look at the objectives, they're the rarest objective to have.
> 
> Plus, it adds a new gamemode that will be admin only (at least it's intended to be admin only) to have a very hectic thirty minute mark.

More content is not a compelling reason, why is incentivizing shuttle call wars/rushing good for the game?

**Pull request closed without merging**
