### PR TITLE
adds a REALLY FLASHY COSTUME to autodrobe

### PR DESCRIPTION
**Pull request by Militaires**
:cl: BASILMAN YOUR MAIN MAN
add: added a really really flashy costume to the autodrobe!
/:cl:

@excessiveuseofcobblestone

ignore the rogue pixel is gone

### CODE REVIEW

**Comment by Cheridan** [comment]
*groan*

**Comment by optimumtact** [comment]
he looks like my tiny orange borgguy

**Comment by AnturK** [comment]
>Can't activate it to flash

0/10

**Comment by Militaires** [comment]
@antur i was gonna do that but now that flash stuns it has to be a non-gameplay thingy item

i can make a tator subtype later

**Comment by Thunder12345** [comment]
Just make it do the flashing animation without actually flashing anyone

Bonus points if it lights the place up while it's flashing

**Comment by Armhulen** [comment]
make it only work while all your lights are off and every five seconds it emits maximum light around you

**Comment by Shapsy** [comment]
That looks awful

**Comment by Militaires** [comment]
@shapshy i modelled it after you.

**Comment by WJohn** [comment]
No thank you.

**Comment by Militaires** [comment]
how is this meme pr

**Comment by anconfuzedrock** [comment]
I know its ok to make it a flash if overuse can cause it to fucking explode you

**Comment by MrPerson** [comment]
How is this not a meme pr?

**Comment by Militaires** [comment]
@mrperson dude it's just a costume with a pun and name gimmick

**Comment by xxalpha** [comment]
i don't get it

**Comment by KorPhaeron** [comment]
Art director said no

**Comment by ChangelingRain** [comment]
The flash bulb doesn't even look right jeez

**Comment by ExcessiveUseOfCobblestone** [comment]
good pr

**Comment by Iamgoofball** [comment]
@WJohn because furry shit and anime references are OK but actual references to the game aren't

**Pull request closed without merging**
