### PR TITLE
Re flavors the laser arm implant to be Gauss weaponry, new sprites and flavor text.

### PR DESCRIPTION
**Pull request by itseasytosee**
## About The Pull Request
Removes the laser implant from the uplink and replaces it with the arm implanted gauss rifle, which is functionally identical. This is the first stage of my plan to fix everything I don't like about the laser arm gun implant. The beams fired are thinner and yellowish. A non implanted gauss rifle (functions identically to the laser gun) can be found in the admin menu and I may rework and implement it at a later date. Also, this adds some proper item sprites to the gun so you actually know what hand it's in.
[Video](https://cdn.discordapp.com/attachments/568963791123906572/754836078183055450/2020-09-13_17-45-47.mp4) (slightly outdated)

## Why It's Good For The Game
These are mostly for lore and consistency reasons.
The laser rifle breaks the theming of the nanotrasen uses lasers and the syndicate use bullets. (or "hard light" in some cases).
Currently, the gun functions identically to the captain's laser gun except it is implanted in your arm and mess you up if you get hit by an emp. Knowing the syndicate have the technology to create a self-charging gun, yet they send operatives to attempt to recover it cheapens both the objectives and the laser arm implant. Finally, gauss weaponry is cool as shit.
In the future, I intend to change the rifle to make it better suited for the role restriction (ie. mechanically tying it in with the job like other role restricted items.) and add some ammunition or recharge mechanic, possibly with a buff for balance. See https://github.com/tgstation/tgstation/pull/49398 if you want to read my and other losers' opinion on it.

## Changelog
:cl: itseasytosee
tweak: The laser arm implant item has been replaced with a gauss rifle implant, which is functionally identical aside from visuals and flavor text for the time being.
imageadd: The gauss rifle implant now has proper item sprites, now you know what hand it's in!
soundadd: The gauss rifle now has its own sounds
/:cl:

### CODE REVIEW

**Comment by itseasytosee** [comment]
Pictures tomorrow it's 4 in the damn morning.

**Comment by Barhandar** [comment]
>and add some ammunition or recharge mechanic

Could be shooting user's blood or using nutrition for energy; requiring explicit ammo kiiiinda misses the point of an implant.

**Comment by Ryll-Ryll** [comment]
gauss...... mmmm I've wanted gauss for a long time

**Comment by itseasytosee** [comment]
>  blood or using nutrition for energy

That's a pretty good idea

**Comment by itseasytosee** [comment]
There were previously no item sprites you would have no idea what hand its in but I added some and new in hands.

**Comment by msgerbs** [comment]
This seems strange to me as a player, lore aside. A gauss gun fires projectiles. If I see the word gauss I'm thinking it's something I'll have to reload.

**Comment by itseasytosee** [comment]
The ammo would almost definitely be energy-based in some sort. In a gauss weapon, the projectile could be just a small ball bearing that the weapon could fashion from your body mass over time.

**Comment by carlarctg** [comment]
> This seems strange to me as a player, lore aside. A gauss gun fires projectiles. If I see the word gauss I'm thinking it's something I'll have to reload. I would really prefer this just be left alone until you're ready for a full rework with ammo or whatever.

just think of it like the syndiborg gun, it 3d prints bullets....somehow.

**Comment by itseasytosee** [comment]
Video added

**Comment by necromanceranne** [comment]
We actually have a gauss projectile sprite. It's what penetrators use.

**Comment by itseasytosee** [comment]
Yep! I modified the heavy one.

**Review by Twaticus — APPROVED** [review]

**Review by Twaticus — CHANGES_REQUESTED** [review]
wait why is the gun grey but the inhand blue

**Comment by itseasytosee** [comment]
Nice catch.

**Review by Twaticus — APPROVED** [review]

**Comment by theboy6545** [comment]
> > and add some ammunition or recharge mechanic
> 
> Could be shooting user's blood or using nutrition for energy; requiring explicit ammo kiiiinda misses the point of an implant.

pretty sure there is a slime core thing that does damn near the same as the implant but shoots blood

**Comment by itseasytosee** [comment]
@Twaticus want to help me out here?

**Comment by Twaticus** [comment]
hey i just say if the sprites are cool sorry mang

**Comment by itseasytosee** [comment]
I'll come back to thins when my pc is fixed.

**Pull request closed without merging**
