### PR TITLE
[DRAFT] Standardizes Maintenance Access on MetaStation

### PR DESCRIPTION
**Pull request by Son-of-Space**
## About The Pull Request

Standardizes MetaStation Maintenance Doors with the following restrictions:
1. Common maintenance access doors are MAINT_ACCESS only. No snowflake access unless required to access a role-required room in maintenance. (i.e. direct route to abandoned bar has bar access)
2. Common maintenance access doors are UNRESTRICTED on the way out.
3. Transition doors inside maintenance are UNRESTRICTED
4. Common Department Maintenance requires only generic department access
5. Role-Specific Maintenance access requires Role-Specific Access

## Why It's Good For The Game

Pros:
-Reliable access to maintenance with no special, unseen requirements. Players get what they have on their tin.
-Departments can reliably access their department's maintenance without lots of extra mapping work to do it. (Reduces chance for errors in mapping as well)
-Anyone who somehow finds their way into maintenance has at least one reliable way out
-Easier mapping in the future, paves the way for concise use of future mapping helpers.
-Players do not need to get MAINT_ACCESS to play a way into an area of maintenance.

Cons:
-Players don't need MAINT_ACCESS to reliably have a way out of maintenance, making it less dangerous to use
(I would argue this con is moot: access as it stands encourages people to get access instead of playing their way into the maintenance area. This change makes it so instead of requiring you to get access, you have to use the game's mechanics to access "playing their way in")
-It is slightly easier for antagonists to hide away in maintenance
-Maintenance is less exclusive to roles that use it for gameplay (cytologists, assistants, etc.)
-Reduces the need for a role to perform its function (HOP handing out maintenance access) (Though, if making this go from a requirement to a desire when it comes to accessing maint significantly reduces HOP gameplay, do we really even have HOP gameplay?)

## Changelog

:cl:
qol: Maintenance is more consistent on MetaStation
balance: Maintenance is more accessible on MetaStation
fix: Removed unnecessary access requirements on some doors on MetaStation
/:cl:

### CODE REVIEW

**Comment by AlinaStarkova** [comment]
are you planning to do this for the other maps too?

**Comment by Dorsisdwarf** [comment]
If internal maintenance doors are now unrestricted, doesn't this mean that any member of department has full access to the entire segment of maintenance that touches their department?

**Comment by Son-of-Space** [comment]
> If internal maintenance doors are now unrestricted, doesn't this mean that any member of department has full access to the entire segment of maintenance that touches their department?

Yes - Except for the areas that are set to be run down at the start of shift. In fact it might be an interesting idea to have a run down spawner on more of the miantenance doors. I'm forgetting if it's randomized or not if it ends up actually run down but worth investigating.

**Comment by AlinaStarkova** [comment]
> > If internal maintenance doors are now unrestricted, doesn't this mean that any member of department has full access to the entire segment of maintenance that touches their department?
> 
> Yes - Except for the areas that are set to be run down at the start of shift. In fact it might be an interesting idea to have a run down spawner on more of the miantenance doors. I'm forgetting if it's randomized or not if it ends up actually run down but worth investigating.

the run down spawner has a chance of working normally, welded at round start, bolted at roundstart. or be replaced entirely with a wall iirc, i dont know the rates of them, but yes the spawner has a chance of being unchanged

**Comment by Son-of-Space** [comment]
Do not merge. Leaving up for maptainer feedback but intend to implement these changes while implementing the new mapping helper tools from PR #65580

**Comment by LemonInTheDark** [comment]
I like people being trapped in maint, will be sad to see that go

**Review by Maurukas — COMMENTED** [review]
Inept will also be taking a look at this tomorrow if he has time.

I don't have strong opinions on this topic, but from what I see here, at a minor cost to HoP gameplay, maintenance becomes an area much more usable to the crew. I've been in rounds where someone has built something cool in maintenance, but going to visit it means begging someone to let me out afterwards. Or going to track down the HoP who by this point is nowhere near their office.

>Transition doors inside maintenance are UNRESTRICTED

This is probably my biggest concern here, as this opens up the entire station maintenance to all job roles, with the limitation being that they can enter only via their department. I'm not saying no here. I'm just saying this potentially has a large impact on gameplay.

**Comment by Learner10** [comment]
> Inept will also be taking a look at this tomorrow if he has time.
> 
> I don't have strong opinions on this topic, but from what I see here, at a minor cost to HoP gameplay, maintenance becomes an area much more usable to the crew. I've been in rounds where someone has built something cool in maintenance, but going to visit it means begging someone to let me out afterwards. Or going to track down the HoP who by this point is nowhere near their office.
> 
> > Transition doors inside maintenance are UNRESTRICTED
> 
> This is probably my biggest concern here, as this opens up the entire station maintenance to all job roles, with the limitation being that they can enter only via their department. I'm not saying no here. I'm just saying this potentially has a large impact on gameplay.

It's not a very good argument example to use input from other people with regards to the good it'll do, when said people are likely very capable of just adjusting the door to the thing in the first place. Comes with the territory of good building.

Now, while I do like the idea of making maint more traversable to those already inside, this'll come at the expense of antags who commit treachery in the dark halls by raising foot traffic. Which is why I think things should be changed so that either travelers can utilize transition doors to the rest of maint, or so that people in maint can use any exiting door without proper ID. Having both just means the guy who's hacking some man's head off over near the library maint might be discovered by the chaplain who stepped into maint, or the cultist base behind science was found because the bartender took a stroll behind service.

And really, out of said two proposed changes, only one of them will REALLY have a bigger impact, and that's being able to get out from inside. Most of what stops people from poking their noses around in maint is the idea that getting out might not be so easy. Especially if they suddenly need to escape after witnessing a crime. At least with transitory doors, they'll be able to run a bit farther and prolong the chase, but if they can just escape out of maintenance, then the fun can't begin.

**Comment by LemonInTheDark** [comment]
😿

**Pull request closed without merging**
