### PR TITLE
Thermomachine separate files

### PR DESCRIPTION
**Pull request by Ghilker**
## About The Pull Request
See title

## Why It's Good For The Game
Readability, future uses will be easier to access

### CODE REVIEW

**Comment by Cyberboss** [comment]
Remove the changelog, not a player-facing change

**Review by Cyberboss — APPROVED** [review]

**Comment by LemonInTheDark** [comment]
Maybe it's just cause I'm used to shitcode, but splitting something up this hard seems like it would hurt readability more then it helps. 5 files for one object seems worse then one file per object.

@Cyberboss this is more a structural design thing so if I'm wrong feel free to just railroad this yeah?

**Comment by Ghilker** [comment]
> Maybe it's just cause I'm used to shitcode, but splitting something up this hard seems like it would hurt readability more then it helps. 5 files for one object seems worse then one file per object.
> 
> @Cyberboss this is more a structural design thing so if I'm wrong feel free to just railroad this yeah?

I disagree that it hurts readability, I think that scrolling through a 500 lines file is worse than searching inside specific files, like if I need graphic stuff is in the proper file, or if I wanted to change something about tools I'd do it easily (wich I want to do)
I could remove one file, the process atmos one, but eh, I think is fine like this

**Comment by Ghilker** [comment]
I see your point, and yes maybe I went a bit too far and could merge some of these into one. Tho the thing I wanted to do is having a clear separation of the procs so that I can work better when I have to make some of those defaults. But I guess I could do it without it?
Tho I really like having separate files (even not growing ones) that have been sorted to contain procs and other parts that correlate to each other (like graphics, tools, etc)
@LemonInTheDark if you want I could decrease the separation by one or two files, or you could just close this and I'll do the changes without this

**Comment by LemonInTheDark** [comment]
I'll close this. I think a file should be responsible for containing all the info about some type.
Splitting define sprees is good, and some of your other stuff is maybe alright, but this is a bit too granular

**Pull request closed without merging**
