### PR TITLE
Makes blood rage more clear

### PR DESCRIPTION
**Pull request by Buggy123**
This debate is getting really annoying lets settle it.

### CODE REVIEW

**Comment by Kromgar** [comment]
So... what debate is this?


Also there should be an interaction with blood cult so that BLOOD CULTISTS. Makes sense for Blood Cult to have a quasi-immunity or be able to see through the "Blood Rage".

 I used chaos in a bottle once to win a cult round as we were about to summon narsie. We managed to not kill eachother because we could see other cultists because of the  cult hud so we ripped apart the attacking army of hop and a bunch of assistants.

**Comment by Buggy123** [comment]
Basically every single admin I've asked has had a different answer to "if a team antag gets blood rage'd, should he attack his teammates" and "if you get blood raged, are you supposed to attack everyone or is it okay if people ignore them and go for the valids".

Tbh its getting really annoying to have to ahelp every single time I want to use a blood contract or bottle of mayhem just to see if it will have the desired effect.

Also there's plenty of ways to win a cult round if you get close enough to use a bottle of mayhem. Bombs, hellfoam, flamethrowers, etc. It doesn't seem necessary to gimp bottle of mayhem when there's plenty of other ways to destroy a cult with proximity.

**Comment by Kromgar** [comment]
Oh no i used the bottle so we could survive tosummon narsie. 

But regardless you should probably hide the antag huds or cult icons. Let's be real here people will metagame it when they see a demon with a cult icon over their head

**Comment by Buggy123** [comment]
I'll try and see if i can do that.

**Comment by Buggy123** [comment]
o-ok, didn't need the antag hud thing anyway i guess.

**Pull request merged**
