### PR TITLE
512 forward compatibility merge

### PR DESCRIPTION
**Pull request by ninjanomnom**
#32159 but rebased

@MrStonedOne requested we just merge it. It's forward compatibility only anyways and the longer we wait the more \refs there are.

### CODE REVIEW

**Comment by ninjanomnom** [comment]
It compiles but travis fucked up ¯\\_(ツ)\_/¯

**Comment by MrStonedOne** [comment]
update the byond version. its the map crash that was already fixed

**Comment by MrStonedOne** [comment]
=\. our trick of doing every map in one compile job is fucking up.

i don't think lummywinks would support that. anywho, the solution is actually that travis shouldn't be compiling on 512 until the servers are configured to use 512 as their main branch, (and we stop supporting 511 for dev.)

**Comment by Cyberboss** [comment]
Can you check once more for \refs please, I think a few were added

**Comment by ninjanomnom** [comment]
I did already @Cyberboss

**Comment by ninjanomnom** [comment]
I'll fix this in a bit, I need to fix some issues involving tags.

**Pull request merged**
