### PR TITLE
Fixes mechanicals being able to be implanted

### LINKED ISSUE #23916: Cyborgs can be implanted
lol

### PR DESCRIPTION
**Pull request by Cyberboss**
Fixes #23916

:cl: Cyberboss
fix: Cyborgs and bots can no longer be implanted
/:cl:

### CODE REVIEW

**Comment by coiax** [comment]
Are you saying we can't explosive implant our 80TC syndicate borg anymore

**Comment by TehZombehz** [comment]
I forget, is it more or less expensive to order an extra squadmate and do the same thing?

**Comment by BeeSting12** [comment]
Squadmates are 25 TCs so probably less

**Comment by AnturK** [comment]
This is horrible fix, just change the check on implant proc to  > 0

**Pull request closed without merging**
