### PR TITLE
Removes sulpheric acid requirement from most computer boards

### PR DESCRIPTION
**Pull request by silicons**
image

@Robustin good idea for once <3

Next up, each department getting their own rnd console with view-only technology and departmental printers + basic stock parts for all!

### CODE REVIEW

**Comment by Cyberboss** [comment]
I for one enjoy the little forced interaction of the scientist and chemist, because you know it WILL happen every round

**Comment by kevinz000** [comment]
@Cyberboss i'm still hearing that no one manages to get materials but science and cargo and maybe engineering  and that engineering never builds people stuff so the next best thing to somehow convincing people to do things for others is let others do things themselves.

**Comment by Repukan** [comment]
Hugbox

**Comment by 81Denton** [comment]
Doesn't this go against the "departmental interaction" meme that gets brought up in every balance discussion?
It's not even comparable to botanists who can use absurd amounts of mutagen/saltpetre, this is just "hey can you fill this beaker with sacid" once a round.

**Comment by Robustin** [comment]
The short answer if Kor approves then it fits with our design.

My personal answer is that I think forced interaction should only be meaningful. My belief is that if an interaction makes one side feel like a fast food cashier then the interaction isn't healthy for the game. It also comes down to the fact that Sulphuric acid only has one source and it's all too common for chemistry to end up inoperable by the time you have a need for it.

I honestly believe that making computer and machine boards more accessible to the average player will increase cross-dept. interaction as a whole because while you sacrifice a totally rote and meaningless interaction (yelling at chemists for SA), you lower the barrier to people creating new machines, expanding their departments, and hopefully sometimes adding to others.

**Comment by 81Denton** [comment]
I agree with what you said, that kind of interaction is pretty pointless. 
I'm sure I could train my dog to push the "dispense sacid" button whenever he sees a scientist approach the windoor.

**Comment by coiax** [comment]
I think we should keep the acid requirement, but give science a chem dispenser, BUT make all chem dispensers use cartridges.

**Comment by CPTANT** [comment]
I thought RnD usually just makes their own chem dispenser.....

**Comment by DaxDupont** [comment]
Now antags can no longer sabotage the station by destroying the chem dispensers and spacing all the boards/acid. 
That was a good meme while it lasted.

**Comment by ExcessiveUseOfCobblestone** [comment]
The gene machine exists and you guys believe there's no way to get acid and it only has one source????? 

The acid requirements being dropped won't somehow magically encourage Mr. Melons to give you that board, wtf?

If you want the interaction to be meaningful, make it meaningful instead of removing it.

I'm under the impression an interaction, even if not the most exciting of ones, is still better than no interaction at all.

**Comment by DaxDupont** [comment]
@ExcessiveUseOfCobblestone apparently the botanist couldn't make acid because "not without the mutagen" but in hindsight don't nettles have acid?

**Comment by 81Denton** [comment]
Nettles have sacid production. Even without mutagen, just hack a seed vendor or order them from cargonia.

**Comment by ExcessiveUseOfCobblestone** [comment]
@DaxDupont @81Denton Nettles have sacid and DNettles have f/pacid but the catch is you can't grind (well you couldn't in the past, dunno if you can now with the grinder fix a while back) them hence the need to insert the gene into another plant.

**Comment by arsserpentarium** [comment]
Oh? Really?
How about interdepartmental interaction? Timegates? Balance?
What will obtain with this feature nasty powergamers in first five minutes of round?

Did I forget something?

**Comment by kevinz000** [comment]
@ExcessiveUseOfCobblestone to placate the weed mob I will be giving them Gene machine designs and the ability to print stock parts up to tier3 when I PR inprinters for all.

**Comment by ExcessiveUseOfCobblestone** [comment]
Giving people easier access to l00t to placate other people getting easier access to l00t doesn't fix the problem or the gripe people have.

What exactly is wrong/bad about the acid requirement and can we retain the relationship without whatever is wrong/bad with it?

Personally I'd prefer a "bad" interdepartmental relationship over no interdepartmental relationship at all.

**Comment by jughu** [comment]
@kevinz000  sulphuric*

**Comment by ShizCalev** [comment]
Removes player-player interactions. 👎

**Comment by WJohn** [comment]
i like the idea of boards requiring chems, but *just* sulfuric acid is insufficient complexity to get there. make the chemists have to spend a little time to prepare that shit for high level boards.

**Comment by ExcessiveUseOfCobblestone** [comment]
If you want chemists to have to do a bit more to make the interaction meaningful simply replace sulfuric acid with p/facid

**Review by Cyberboss — APPROVED** [review]

**Comment by imsxz** [comment]
Pretty sure on metastation that chem is less than a screen away from RND, can literally walk out of the maints and be there in a few seconds... God forbid science ever has to TALK to someone amirite muh DEPARTMENTAL INTERACTIONS:tm: xd

**Comment by DaxDupont** [comment]
On both Delta and Meta RnD and chemistry can wave at each other.

**Comment by Iatots** [comment]
Time for quartz mining.

**Comment by Robustin** [comment]
MFW The entire point of the PR is so other departments can make their own machines and it devolves into debating the distance between RND and Chemistry. 

Filling a default chem is not an interaction, it's not meaningful and finally it's not fucking loot.

**Comment by Bawhoppen** [comment]
It is totally a limiting resource and is another thing to prevent scientists from huddling up in their box?????

**Comment by Buggy123** [comment]
>implying scientists even have a box since research was gelded

**Comment by Bawhoppen** [comment]
They are literally the most powerful department by a margin still

**Comment by ExcessiveUseOfCobblestone** [comment]
> Filling a default chem is not an interaction, it's not meaningful and finally it's not fucking loot.

ok make it facid so it will fill the first two criterion.

Can you please post where someone called acid loot.

**Comment by YakumoChen** [comment]
Remember when crew had reasons to walk outside their department at least once during the round?

Forcing people out of their departments is needed to encourage more antag activity / opportunities and doesn't make everyone suspicious of the one miner who left cargo because miners have literally no reason to ever leave it now

**Comment by optimumtact** [comment]
\>robustin thinks it's a good idea

\>has more downvotes than upvotes

jogs my nog

**Comment by ExcessiveUseOfCobblestone** [comment]
it has certainly left my almonds unactivated.

**Comment by Cyberboss** [comment]
@KorPhaeron get in here and decide on this

**Comment by KorPhaeron** [comment]
I don't see how walking over to the guy with the infinite chem generator and asking him for some of his infinite chems in a cup and then never talking to him is this really awesome gameplay everyone wants to keep

On the other hand it is one more slight annoyance/hurdle for trying to get your stuff built in each department when we haven't figured out a proper method of resource allocation for techwebs/minerals yet

**Comment by optimumtact** [comment]
wtf kor is yes or no too hard?

**Pull request merged**
