### PR TITLE
undoes some unneeded nerfs to plasma blasts

### PR DESCRIPTION
**Pull request by imsxz**
:cl:imsxz
balance: plasma cutter turrets have their old damage again
balance: plasma blasts have their dismemberment back
/:cl:
unneeded nerfs

### CODE REVIEW

**Comment by ishitbyabullet** [comment]
https://github.com/tgstation/tgstation/pull/40495

I personally like Imsxz's PR more, though.

**Comment by SgtxRootbeer** [comment]
This doesn't apply to the mech and is missing the Pressure change effect

**Comment by imsxz** [comment]
@SgtxRootbeer mech nerf was intentional and justified. add a mecha pka if you want them to have a mining gun

**Comment by SgtxRootbeer** [comment]
@imsxz 
intentional, maybe, but justified, they were definetly not.
the mecha was not subject to the same issues of spam that the handheld PCs were.

**Comment by zxaber** [comment]
I agree with Sgtx on the mech cutter. Your reasons for the handheld cutter nerf were justified, but they don't really apply to the mech. While ~~Ripleys~~ Firefighters are not intended to be full on battle mechs (nor did the mech cutter ever measure up to a kitted Durand), mining mechs need something to fight the hostile mobs on Lavaland.

At a stack of metal and some plasteel and glass plus print time for the mech alone, it was never as spamable as the handheld cutter. The mech's cutter need not be pressure-immune, and hell, it need not even have dismemberment chances. It just needs to damage lavaland mobs in low atmos environments.

**Comment by Barhandar** [comment]
>mech nerf was intentional and justified. add a mecha pka if you want them to have a mining gun

It wasn't justified because there isn't a mecha pka yet. You can re-do the nerf _when it gets added_, but for now when the only mining gun on mech is plasmacutter, it should be reverted.

**Comment by ExcessiveUseOfCobblestone** [comment]
PR a KA item for the mech before it gets merged then, you have plenty of time.

**Comment by SgtxRootbeer** [comment]
>unnecessarily nerfs something
>only acceptable solution is to add something else
that is how you @ExcessiveUseOfCobblestone, everyone!

**Comment by ExcessiveUseOfCobblestone** [comment]
That would imply I think any of these balance pingpongs are worth their salt when in reality the PC is getting removed in favor of KA upgrades that provide a similar functionality, or at least that's the desired goal.

Spot on otherwise though.

**Comment by SgtxRootbeer** [comment]
so your plan is to remove the pc in favor of a mecha ka that accepts upgrades?

**Comment by ExcessiveUseOfCobblestone** [comment]
All PCs, as well as an upgrade for KAs that bores through walls much like the PC functions now.

**Comment by imsxz** [comment]
This PR has nothing to do with mecha plasma cutters, feel free to handle it in your own pull request if you want. Keep the discussion out of here, it's very misleading and off topic/out of the scope of this PR.

**Comment by Barhandar** [comment]
This PR undoes nerfs to plasma blasts, which is what mecha plasmacutters shoot. It's exactly as much in scope as un-nerfing PC turrets.

**Pull request merged**
