### PR TITLE
Dullahan Fixes

### LINKED ISSUE #70890: Dullahans can't read, shoot guns or use strip menus
## Round ID:

N/A, local testing

## Testmerges:

N/A

## Reproduction:
Become a dullahan, and try to read your PDA, shoot a gun, or remove someone's clothes. I assume this happens because the head falling off during on_species_gain removes these.

### PR DESCRIPTION
**Pull request by Jacquerel**
## About The Pull Request

Let's see if these can be like 50% playable by Halloween

Fixes #70890 (mostly)
Also one half of #71020 but does not close it because they still cannot hear audible messages

There was a list of issues in #70890 which are largely fixed by this, but some of them were not _bugs_. 
Anything which is simply an obvious consequence of "not having a head or being able to wear anything on your head" isn't and cannot be fixed, because this species doesn't have a head.
That means that all of these things are still true:
```
Dullahans have no radio
Can't get spaceproofed because without the helmet you still take pressure damage
Can't wear modsuits
Can't wear sunglasses or HUDs
Can't wear clown mask
```

The issue causing everything _else_ is that when we sever the head, we remove the brain. Removing the brain removes the traits `TRAIT_ADVANCEDTOOLUSER, TRAIT_LITERATE, TRAIT_CAN_STRIP`. Without these three traits, Dullahans are blocked from several important actions.
Easy fix: Make these properties of the dullahan species independent of whether they have a brain or not. Clearly they can do these things without brains, on account of not having them.

Additionally I gave dullahans their own head subtype which preserves internal organs, because their brains and eyes were decaying and giving them brain trauma and blindness.

Finally, I changed a few things from checks in `spec_life` to signal responses, because `spec_life` checks for "did I gain a head recently?" are gross.

## Changelog

:cl:
fix: Dullahans can read, strip people, and utilise tools.
fix: Dullahan brains and eyes will not decay while inside their living severed head.
/:cl:

### CODE REVIEW

**Review by ZephyrTFA — CHANGES_REQUESTED** [review]
I don't want snowflake code for a species we "support" find a way to turn this into a trait TRAIT_DETACHED_HEAD

**Comment by Kapu1178** [comment]
the yearly tradition

**Comment by Jacquerel** [comment]
> I don't want snowflake code for a species we "support" find a way to turn this into a trait TRAIT_DETACHED_HEAD

the simpler alternative is to just give Dullahans all of those traits without reinserting their brain, although it's more fragile
I don't think we can make a headless supertrait which takes the place of the ones the brain usually applies without it being far stupider and with a bigger footprint than what I am currently doing

**Comment by ZephyrTFA** [comment]
i would rather the species be removed then to snowflake it even more than it already is

**Review by ZephyrTFA — APPROVED** [review]
we're so back

**Review by san7890 — COMMENTED** [review]
forgot to hit submit

**Pull request merged**
