### PR TITLE
Tramstation: Science Rework & other stuff i guess

### LINKED ISSUE #69222: Tramstation Ordinance Lab is currently not setup correctly
## Reproduction:

The input injectors inside the ordinance lab are not on by default, and the igniter in the mix chamber is completely nonfunctional.

### LINKED ISSUE #73883: Stray Shutters button in Tramstation Warehouse
Reporting client version: 514.1589

## Round ID:
[201527](https://scrubby.melonmesa.com/round/201527)

## Testmerges:
- [Minigame DLC - Intergalactic Basketball League](https://www.github.com/tgstation/tgstation/pull/72459)
- [Nanotrasen Budget Programme - Mothball Edition [BIRDSHOT STATION]](https://www.github.com/tgstation/tgstation/pull/73502)

## Reproduction:
There is a stray shutters button in tramstation's warehouse in cargo.
Screenshot 2023-03-09 164640

### PR DESCRIPTION
**Pull request by MMMiracles**
## About The Pull Request

- Science has been completely revamped from the ground up with a more multi-z design in mind while making it easier for some jobs to actually do their jobs.
- Science now has a dedicated testing chamber along with a larger monkey storage (da monke pit) to do various things with.
- Xenobiology is now contained to one floor for easier general workflow while moving the larger containment pen and cytology equipment to its own dedicated creature experimentation room directly above Xenobiology. Accessed through maintenance or Xenobiology itself.
- Robotics and Genetics now has a front desk! This seems like an obvious thing with hindsight.
- The genetics monkey pen has been replaced with a larger monkey pit (da monke pit) with more foliage and roundstart monkeys. This may or may not been one of the reasons I wanted to remake the department.
- Made Ordnance a bit bigger in general and replaced the suckysucky air tanks with a smaller version of the oxygen storage tank in Atmos. I was told this may have unforeseen consequences.
- I remodeled the drone bay in Cargo to stick out slightly less since I didn't like how it looked. Not much else changed there.
- The vacant commissary office was moved up towards departures, with a small barber shop taking its place in the original location. I hope the entrepreneurs of the crew appreciate the extra traffic flow.
- The surrounding maintenance modules were remodeled partially to fit the changes. Loot was kept mostly the same between modules apart from 'atmosci_attachment_b' ending up getting removed due to space no longer being there for it.
- The gear in the secret outpost has been nerfed because roundstart combat gloves and a suspicious toolbox is maybe too much for our crew.
- All elevator doors on the lower floor now start open by default.

Closes #69222
Closes #73883

## Why It's Good For The Game

I didn't like the current Xenobiology setup and from what I've heard, the multi-z setup for it was more of a nuisance than anything else. I wanted to give it a proper rework and I figured I might as well do the whole department since I'll have to rework the nearby maintenance modules anyway.

## Changelog

:cl: MMMiracles (tramstation)
add: Tramstation's Science department has received a substantial remodel! Please consult your local tour guide for more information.
add: The Vacant Commissary office has been moved to the top floor near Departures, with a new Barber shop taking its place on the lower floor. 
/:cl:

image
image
image
image

### CODE REVIEW

**Comment by the-orange-cow** [comment]
Thank you, multi z xeno was annoying and ordnance was cramped.  And genetics having a window is great too.

**Comment by iamcooldan** [comment]
xenobio is lacking a slime stasis chamber for bz users

**Comment by Sealed101** [comment]
> xenobio is lacking a slime stasis chamber for bz users

the large containment pen is on the lower floor

**Comment by rageguy505** [comment]
Did the rework touch #69222 ?

**Review by Maurukas — COMMENTED** [review]
Looks good. A couple minor things:

* I am  unable to locate shutter controls for the lathe and science front desk. You might want to do separate buttons for the front set and back set
* No external control button for the mech bay shutters
* No bolt controls for the lower entrance to the commissary. Is this intentional?
* The elevator door in science on Z 1 is closed at roundstart, it needs to be open, otherwise the elevator must be summoned to Z 2 at least once before it can be used.
     * This is also an issue on the cargo elevator, which wasn't touched in this PR.
* RD Office has no lights in it.

ATs here with a certain modular arrangement:
image
image

**Review by Maurukas — COMMENTED** [review]
Some things I missed last time:
* Missing APC in Mechbay
* Misisng APC in the upper science lobby (also missing air alarm)
* Missing APC in lower science lobby
* Missing APC in this maint section near engineering:
image

Atmos in the main cargo bay needs a pass - it contains only one scrubber and no air alarm

**Comment by Helg2** [comment]
@MMMiracles Why did you change qm's doors to doors with glass...

**Pull request merged**
