### PR TITLE
Adds capture the flag to Z2

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
With a map by ausops. Spawners are off by default to discourage mass suicide, admins will have to enable it at their discretion. Maybe I should add an admin button to enable them or auto-enable that after half an hour or something.

http://i.imgur.com/h7rya0s.png

:cl: Kor
rscadd: Capture the flag has been added in space near central command. The spawners are disabled by default, so be sure to harass admins when you die until they let you play. The arena was mapped by Ausops.
/:cl:

### CODE REVIEW

**Comment by KazeEspada** [comment]
Use the gateway timer.

**Comment by kevinz000** [comment]
Make the station have rows of adv camera consoles for monitoring and security cameras
THEY GOTTA WITNESS US MAN

**Comment by Dorsisdwarf** [comment]
Thats what entertainment consoles do kevs.

**Comment by MMMiracles** [comment]
Entertainment consoles still use the regular camera-switching instead of the adv consoles, though. Having to switch between a list to watch a moving fight in the area would suck.

Just make a subtype of the xenobio adv console that only works in the thunderdome/ctf arena area and replace the current entertainment TVs with those. 10x better instantly.

**Comment by lzimann** [comment]
:+1:

**Comment by neersighted** [comment]
:+1:

**Comment by Jordie0608** [comment]
Might as well just replace the thunderdome with this.

**Comment by neersighted** [comment]
Can we get a proper coder lounge/fight club/testing area please?

**Pull request merged**
