### PR TITLE
Tweaked the mechfabricator's construction times

### PR DESCRIPTION
**Pull request by alxmra**
## About The Pull Request

So, I noticed how long it takes to print some cyborg parts and how fast it prints mech parts, so I tweaked a little some of the contruction times.

## Why It's Good For The Game

It's good for the game because it allows roboticists to finish the cyborgs and little bit faster at roundstart(basically when everyone comes and asks for borging or augmentations).
I also tweaked a little bit the mechs construction time, it was a little too fast, in my opinion.

## Changelog
:cl:
tweak: tweaked a few things
/:cl:

### CODE REVIEW

**Comment by FloranOtten** [comment]
if the mech construction times were too fast, why decrease them? Durand torso to 150 kind of defeats the point of extending the chassis time by 50.

**Comment by HomocidlePancakes** [comment]
They are slow only without upgrades, and making shells without upgrades is a waste of resources.

**Comment by JenqaDev** [comment]
FYI: by "too fast" I meant the mech printing.

**Comment by SynnGraffkin** [comment]
Upgrade your fabricator's lasers or manipulators (can't remember which) for speed. Even if it is tier 2 lasers from industrial, it still helps a bit and it is still early game since industrial is usually first.

**Comment by ExcessiveUseOfCobblestone** [comment]
Fix Changelog

**Pull request closed without merging**
