### PR TITLE
[s] Fixes my life

### PR DESCRIPTION
**Pull request by optimumtact**
Thank you to @deathride58 for this

### CODE REVIEW

**Comment by optimumtact** [comment]
@tgstation/commit-access

**Review by SpaceManiac — APPROVED** [review]
LGTM, seems a fair limit, curious if something broke this parser or someone just put a *lot* of these in there, though

**Comment by deathride58** [comment]
It'd probably be worth it to change the hardcoded field limit into a proper define to ensure it remains consistent if anyone ever wants to increase/decrease it in the future, but the PR as-is should get the job done.
Paper code is in desperate, _desperate_ need for a complete rewrite, as it seems like every other year someone finds a brand new way to fuck servers up with nothing but pen and paper

**Comment by Whoneedspacee** [comment]
fucking genius

**Pull request merged**
