### PR TITLE
Unflipped the thermomachine and makes it not call update_apperance every atmos tick.

### PR DESCRIPTION
**Pull request by vincentiusvin**
## About The Pull Request
Title, really.

This was why it was flipped:
https://github.com/tgstation/tgstation/blob/11302feef45d2bc0fc717ee426114c2c7e52caeb/code/modules/atmospherics/machinery/components/binary_devices/thermomachine.dm#L57-L58

## Why It's Good For The Game
less unnecessary calls, less snowflake cases.

## Changelog
Not really necessary but might be useful if bugs are found.
:cl:
code: Some code changes to thermomachine ports and appearance. No gameplay changes expected though.
/:cl:

### CODE REVIEW

**Comment by Ghilker** [comment]
It was flipped because code wise made more sense to have the main port as airs[1] but if @LemonInTheDark is fine with this I won't complain

**Comment by vincentiusvin** [comment]
I agree, it made more sense as one but everything else have it at two so i guess this makes it easier if someone wanted to change it later down the line.

**Comment by Ghilker** [comment]
Fair, one would say to flip them all so that airs[1] is the main port for everything, but is a job for another pr

**Comment by LemonInTheDark** [comment]
I'm chill with this.
God why didn't I merge this before

**Pull request merged**
