### PR TITLE
Stops Saeg from freezing admins

### PR DESCRIPTION
**Pull request by Iamgoofball**

### CODE REVIEW

**Comment by Armhulen** [comment]
f legacy

**Comment by Iamgoofball** [comment]
https://puu.sh/uNGHG/5d6f384940.dmi

**Comment by Jordie0608** [comment]
I'm not sure this'll do anything.

**Comment by Iamgoofball** [comment]
We'll need to test it to be certain I don't have saeg's ban list to test with

**Comment by Jordie0608** [comment]
The freezing was from HTML building a page out of 1000+ rows returned and not SQL so the row count doesn't matter here as the query is now limited to return 50 rows only.

**Comment by Iamgoofball** [comment]
hm

**Comment by Iamgoofball** [comment]
can someone testmerge this

**Comment by optimumtact** [comment]
Not required and also contains no checks for things disappearing or bans updating during the sleep.

**Pull request closed without merging**
