### PR TITLE
Beating santa causes presents to fly out of him

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
@RemieRichards @tkdrg @duncathan @Cheridan @Jordie0608 

Quickmerge for christmas please thanks

### CODE REVIEW

**Comment by Shapsy** [comment]
someone had a bad christmas

**Comment by Jalleo** [comment]
No it should be Coal dammit.

**Comment by bgobandit** [comment]
make the clown suit do this but for bananas

**Comment by Thunder12345** [comment]
\>make the clown suit do this but for bananas
\>"PIERROT'S THROAT, EVERYONE, BEAT THE CLOWN!!"

**Comment by bgobandit** [comment]
exactly

**Comment by KorPhaeron** [comment]
I thought this would be well recieved because of the "beat clown to make him honk" PR but people find this more mean than funny so nevermind.

Sorry to anyone I upset.

**Comment by Shapsy** [comment]
santa is sacred kor he should have hearts appear when you beat him

**Comment by Zilenan91** [comment]
It's not funny to beat up Santa

**Pull request closed without merging**
