### PR TITLE
Allows circuits to be things other than items

### PR DESCRIPTION
**Pull request by Garen7**
[Changelogs]: # (Your PR should contain a detailed changelog of notable changes, titled and categorized appropriately. This includes, new features, sprites, sounds, balance changes, admin tools, map edits, removals, big refactors, config changes, hosting changes and important fixes. An example changelog has been provided below for you to edit. If you need additional help, read https://github.com/tgstation/tgstation/wiki/Changelogs)

:cl: Garen
code: you can make a circuit assembly exist within another object while redirecting all its signals to the original assembly by assigning a type to the variable wrapper_path
tweak: drone assemblies are now mobs
tweak: the pen assembly is now a pen
/:cl:

[why]: # (Please add a short description [two lines down] of why you think these changes would benefit the game. If you can't justify it in words, it might not be worth adding.)
If drones are going to act like mobs then they should be mobs, also this allows them to be shot by a gun and prevents them from running over tables. This also helps people make more interesting circuit assemblies.

### CODE REVIEW

**Comment by ahkent** [comment]
for what its worth this is delightful to me and i can't wait to make silly clothes

**Comment by optimumtact** [comment]
It shows flexibility of circuits but I'm not sure it makes sense as an actual idea, how does the circuit steer the drone?

If anything the circuit behaviour should be a component itself and the actual underlying item is just the physical extrapolation of the item in the real world.

**Comment by Garen7** [comment]
@optimumtact I tried to do that in #39566 but was asked to close it because I coded it poorly and also because that way is a lot more code changes than this way. If you'd rather me fix that old PR into a suitable state then let me know.

**Comment by ahkent** [comment]
for some types of circuit behavior, it makes more sense to have it as a component. but for others, the behavior is something thats 100% dependent on the actual shape of the assembly- which would be strange to include as a component. it's less obvious with the pen example because "can write" makes just as much sense as "is a pen", but in the case of, say, a circuit with a belt loop it's more obvious.

**Comment by Razharas** [comment]
Curcuits should be essense components of "silicone" objects like dna should be essense component of all "carbon" objects

**Comment by BlueNothing** [comment]
I'm excited for the possibilities this PR opens up.

**Comment by BlueNothing** [comment]
Any news on this?

**Comment by ATH1909** [comment]
Why close it instead of merge it?

**Comment by optimumtact** [comment]
because I don't want to merge it, but I was willing to see if someone else was

**Comment by optimumtact** [comment]
sorry man, it looks like nobody wants to review this particular item and merge it and I'm not comfortable with it.

**Comment by Garen7** [comment]
its cool man, don't worry about it

**Pull request closed without merging**
