### PR TITLE
Adds bigoted language to the Terms of Service violation banned content entry

### PR DESCRIPTION
**Pull request by cacogen**
## About The Pull Request

Adds bigoted language to the Terms of Service violation banned content entry.

## Why It's Good For The Game

No one reads the Terms of Service and you wouldn't expect they'd disable a repo for this so contributors should be told about it specifically.

### CODE REVIEW

**Comment by daklj** [comment]
cuck station

**Comment by optimumtact** [comment]
Don't be a pest

**Comment by cacogen** [comment]
Why'd you close this?

**Comment by optimumtact** [comment]
Contributors will know when they get told, otherwise it's fairly common sense, treat it like a semi business environment.

**Pull request closed without merging**
