### PR TITLE
Adds a pie-flavored pie

### PR DESCRIPTION
**Pull request by lostobj**
## About The Pull Request

adds pie-flavored pie
made from two pies

## Why It's Good For The Game

pie
yup
p.s. please open the bunker and free me from tom fulp's dungeon please god

## Changelog

:cl:
add: adds pie-flavored pie
/:cl:

### CODE REVIEW

**Comment by AtomTheProphet** [comment]
pie^2

**Comment by Helg2** [comment]
Can someone explain the reference?

**Comment by OneAsianTortoise** [comment]
> Can someone explain the reference?

https://youtu.be/tKB4h9gvmm0

**Comment by optimumtact** [comment]
@JohnFulpWillard free him

**Comment by EricZilla** [comment]
I think it should be rectangular too, since the pies are squared

**Comment by Time-Green** [comment]
Brilliant

**Pull request merged**
