### PR TITLE
Removes 30 item cap on tablecrafting

### PR DESCRIPTION
**Pull request by Iamgoofball**
why was this even a thing?

### CODE REVIEW

**Comment by phil235** [comment]
It was mostly for realism, it's kinda hard to craft stuff on a super crowded table.

**Comment by Iamgoofball** [comment]
in this case, the realism is detracting from the enjoyment of the game

**Comment by Boggart** [comment]
I hit this limit constantly while cooking anything. (Usually when not the chef but filling in as the clown or something else so you're trying to spam out a bunch so that there's enough food without you babysitting it.)

**Comment by Fox-McCloud** [comment]
But...mai immershun.

:+1:

**Comment by WJohn** [comment]
Improved table crafting WHEN?

**Comment by Miauw62** [comment]
this is good :+1:

**Comment by ike709** [comment]
I still don't like tablecrafting.

**Comment by RemieRichards** [comment]
@WJohn when people actually tell us what to improve about it.
there are 1000s of "Tablecrafting is shit!" comments, and 0 "Tablecrafting is bad because of X" comments.

**Comment by freerealestate** [comment]
it's unintuitive

i don't know what i can make with it

i don't know what ingredients i need

**Comment by Miauw62** [comment]
hand crafting has the same problems, really.
we really need to remove the table part of tablecrafting and just add a craft button somewhere on the UI.

**Comment by RemieRichards** [comment]
@Iamgoofball not going to close it, but I request you do so, as my PR encompasses this fix.

**Comment by Iamgoofball** [comment]
I love the pr

**Pull request closed without merging**
