### PR TITLE
BCI overlay fix

### LINKED ISSUE #65197: BCI Circuit overlays/huds do not show up
(This has gone on for months I just neglected to report it because I`m not sure if it is related to another issue)

Reproduction:
< Set up any of the hud/overlay functions with BCI 
< Give the hud/overlay an entity to target and then trigger it.
< Weep as nothing appears

I think this might be related to another issue #62543 as it also started happening at a similar time when that bug appeared, I`m not sure.

And I think there was a pr that changed layering or something with Hud effects, but I can`t find it.

If round ID is required along with a video/images I`ll happily fabricate it all within 24 hours.

### PR DESCRIPTION
**Pull request by SmArtKar**
## About The Pull Request

Fixes #65197 

Here's how it looked before:
image

The issue appears here
image

And here's how it looks now:
image
image

## Changelog

:cl:
fix: BCI overlays now actually work
imageadd: Changed BCI counter overlay numbers to make them more readable
/:cl:

### CODE REVIEW

**Review by Twaticus — COMMENTED** [review]
screenshots please

revert base hud_numbers its a nice detail
image

**Review by Twaticus — CHANGES_REQUESTED** [review]
that was supposed to be a requested change oops

**Comment by moocowswag** [comment]
speedmerge.

**Comment by SmArtKar** [comment]
> screenshots please
> 
> revert base hud_numbers its a nice detail image

it was completely unreadable before due to high contrast

**Comment by Twaticus** [comment]
understandable

**Review by Twaticus — APPROVED** [review]

**Pull request merged**
