### PR TITLE
Revamps the Beach away mission

### PR DESCRIPTION
**Pull request by EuSouAFazer**
## About The Pull Request

The beach has been revamped - it is no longer ancient and looks and feels much, much better.

image
image
image

image
image

## Why It's Good For The Game

The beach's map has been masssively improved - it no longer is just a few square rooms on a beach, having a lot more to do and interact with.

- A fully new hotel area has been added for MRP purpouses, gimmicks and a medical area.
- Fishing poles and fishing toolboxes can be found scattered around to catch some tropical fish
- All Terrain Vehicles and a dressing room have also been added
- The bar and kitchen area has been significantly expanded to fit with modern TG's cooking
- An arcade and Space Cola quiosk have also been added
- The place, in general, looks a lot better

## Changelog
:cl: Fazzie
add: A lot of new content has been added to the beach away mission
qol: It also looks substantially better, too!
/:cl:

### CODE REVIEW

**Comment by EuSouAFazer** [comment]
What do you MEAN the fruit bowl's pixel_y is banned

image
image

**Comment by BlueMemesauce** [comment]
can you post pictures becuase the hotel doesnt show up on map diff bot

**Comment by EuSouAFazer** [comment]
Captura de tela 2023-09-24 224251

Captura de tela 2023-09-24 224429

Captura de tela 2023-09-24 224508

Sure; the mapdiff bot cut this area out so here it is

**Comment by EuSouAFazer** [comment]
Added some pics, if that's what was preventing it from being merged

**Review by Maurukas — APPROVED** [review]
This is *nice*. This is really nice. There is a ton of Kilo level detail work here, and this is a map that desperately needed some love.

I'm not finding any issues here, and without pipenets, powernets or complex atmos, there's not a lot that can go wrong on this one.

**Pull request merged**
