### PR TITLE
[Ready] Icebox Again Fork Fixed

### PR DESCRIPTION
**Pull request by Whoneedspacee**
## About The Pull Request

Video: https://www.youtube.com/watch?v=kX-mH4k8b6k&t=

Thanks to @wesoda25 and @KomradeSpectre and @trollbreeder for making ruins for ice moon

Adds icebox, it's boxstation on top of the ice moon mine, lavaland and space ruins don't spawn on this map. There are 3 z levels, the top level with the station and some ruins and mobs, the middle level with some ruins, and the bottom level with megafauna and more dangerous ruins. No need for a gravity generator. Bombcap multiplier does not work on the station level because bluespace blah blah blah.

Icemoon has it's own unique atmos quite like lavaland, you need a winter coat, explorer suit, equal or better to withstand the cold temperature. It has a couple unique mobs and spawners for them with polar bears and wolfs, wolfs run away at low health and polar bears attack faster. There are also now snow legions for ice moon.

Refactors some parts of the weather system, adds ZTRAIT booleans for specific weather rather than targeting areas like the mining ZTRAIT, allowing for more fine control. You can now also make weather target outdoor areas automatically, making weather much easier to setup for a zlevel so you don't have to specify every area it targets.

Refactors many parts of the tunnel generation system for lavaland, you can now have areas specify whether tunnels, flora, mobs, or megafauna can be allowed in them. This makes it much easier to map in ruins and make sure generation won't mess with them. Also fixes a bug where tunnels were checking areas around the object creating the tunnel and not the front of the tunnel, which let tunnels move through areas it shouldn't have. You can also have a variable tunnel width if you desire now.

Rocks can now be mined for volcanic ash which can allow for glass creation on places that don't have basalt or sand turf.

Refactors a part of ruin spawning which allows for ruins to be placed in multiple areas. This makes multi-z ruin spawning much more possible since before you needed the top and bottom z levels to have the same area.

The wabbajack proc has an argument to specify the type of transformation now, (transform into a human, not a xenomorph, etc)

Fixes a bug where asteroid mobs never showed their aggro icon state.

Syndicate shuttle can now land on mineral turfs.

Adds minetype "none" so some stations can have their own custom minetype on the map json itself and not have errors logged.

Adds new blood drunk miner type that can be spawned from destroyed nether portals.

Adds anywhere ruins which are ruins that can be placed anywhere without messing with atmosphere and other things (generally ruins with turf passover everywhere, maybe some ruins could be converted to this if not already).

Nuclear Operative lockers now spawn with a diamond drill so they can drill through mineral turfs, especially needed for if they fall off the top z level.

Blobs can no longer place their starting core on a no blob allowed area, they already couldn't swap their core to such a position so it makes sense that they shouldn't be able to place themselves on it by default.

## Why It's Good For The Game

It's pretty much a normal station except with a few turns that I think might make the game more interesting. There's planetary atmosphere so there's the potential for gas mining that is less feasible on the station. Power is going to be more of a concern since the supermatter can't automagically super cool everything with space, though using freezers for cooling is still an option if you want a normal SM setup, solars and the TEG might be more viable options.

The potential for multi-z exploration is interesting though I'm sure there will be some issues there because... it's multi-z. Chucking people down z-levels instead of into space will also be hilarious (and possibly more dangerous).

Overall I'm not really sure how it will go, but hey it's a votable map so if people don't like it the statistics will speak for themselves, at the very least something interesting for a bit or for admin events.

## Changelog
:cl:
add: Icebox Station has been added, explore the depths of the Ice Moon with boxstation right on top of it, don't forget your coat and internals!
add: You can now mine rock flora into volcanic ash to make glass.
/:cl:

### CODE REVIEW

**Comment by trollbreeder** [comment]
finally, after all these years, a form of planetstation
you could've gone with anything but box, though

**Comment by wesoda25** [comment]
Is it possible to overlay any map on the icemoon, and just have it randomly choose between space and the icemoon?

**Comment by tmtmtl30** [comment]
probably not possible now, since there are pretty significant changes to mining (and i imagine the rest of the map as well). it'd be an interesting project though

**Comment by TheSilverNuke** [comment]
Has the excessive BZ issue been fixed?

**Pull request merged**
