### PR TITLE
Adrenaline and freedom implants in rnd have been replaced with tracking and chem ones

### PR DESCRIPTION
**Pull request by Shadowlight213**
Letting rnd mass produce antag gear, isn't a good idea.

:cl:
add: Tracking implants and chem implants have been added to rnd
del: Adrenaline and freedom implants have been removed from rnd
/:cl:

### CODE REVIEW

**Comment by vcordie** [comment]
rood

**Comment by GunHog** [comment]
Ultimate suck.

**Comment by kevinz000** [comment]
Kek

**Comment by ma44** [comment]
SLIPPERY SLOPE

**Comment by Armhulen** [comment]
another bribe inbound

**Comment by vcordie** [comment]
nonsense. doesn't affect me, why would i bribe for it.

**Comment by Fox-McCloud** [comment]
Adrenaline is so difficult to get to begin with, dunno if that's worth it.

That said, this is *probably* generally for the best, even if I don't like it.

**Comment by Bawhoppen** [comment]
R&D powergame is dumb, this is for the best

**Comment by FantasticFwoosh** [comment]
@Fox-McCloud its literally just ephedrine you can get from mutated coffee plants, the coffee robusta strain.

**Comment by CPTANT** [comment]
since when could rnd produce fucking freedom and adrenal implants.

**Comment by lzimann** [comment]
For a long time. Althought with my experience this rnd's adrenal had some downsides, plus no one ever reaches the required level. Though, removing antag gear from rnd is probably better.

**Comment by ma44** [comment]
Reminder that two of the downvotes are by accounts that never did anything (chiefwaffles and thefastfoodguy)

**Comment by DoctoreMad** [comment]
@ma44
NOTHING IS BEYOND OUR REACH
NOVUS ORDO SECLORUM
**R&D SHALL RISE AGAIN**

**Comment by ma44** [comment]
Not if you nerf it hard like botany

**Comment by lzimann** [comment]
@KorPhaeron

**Comment by Fox-McCloud** [comment]
>its literally just ephedrine you can get from mutated coffee plants, the coffee robusta strain.

@FantasticFwoosh 

Not exactly; adrenaline implants *instantly* removes all stuns, on use, and removes 75 stamina damage.

Additionally it injects omnizine, synaptizine, and stimulants.

Adrenaline implants reduce 4 stun/weaken/paralysis every cycle in addition to 5 stamina loss vs ephedrine's 1 for each.

adrenaline implants are several orders more powerful than just ephedrine. The instant removal of all stuns, on use, is one of the most powerful aspects of the adrenaline implant.

**Comment by Iamgoofball** [comment]
# R&Dtards BTFO

**Pull request merged**
