### PR TITLE
Adds Vulpkanin, Tajaran, Skrell, and IPCs to the game.

### PR DESCRIPTION
**Pull request by Iamgoofball**
If the digitigrade lizard buff is still open then this shouldn't be closed.
#22115

### CODE REVIEW

**Comment by Cheridan** [comment]
IT HAS CONFLICTS

**Comment by Arianya** [comment]
ITS ALSO NEW RACES WHEN THATS SPECIFICALLY PROHIBITED

**Comment by calzilla1** [comment]
THE MEMES

**Comment by dannno** [comment]
for christ sake

**Comment by GunHog** [comment]
The funniest part of this is that if anyone but him tried to PR this, Goof would twist himself in half and post **SLIPPERY SLOPE** and other such memes.

**Comment by Iamgoofball** [comment]
@GunHog that's because I know it'd get merged

**Comment by YakumoChen** [comment]
Reminders that catbeasts are instant valid

**Comment by PKPenguin321** [comment]
hahaha

**Comment by KorPhaeron** [comment]
>reopening this

**Pull request closed without merging**
