### PR TITLE
Security "Compli-O-Nator 3000" new sounds

### PR DESCRIPTION
**Pull request by DrDiasyl**
## About The Pull Request

Changes security gas mask hailer sounds to more crispy, high quality, intimidating ones. **(The Emag Beepsky roast line is not touched)**
You can listen to both old and new here:

https://github.com/tgstation/tgstation/assets/42353186/504aebc4-467b-4144-bcad-59f68595b687

https://github.com/tgstation/tgstation/assets/42353186/78615904-f63a-4454-be62-41aad6753637

Also now the sound hailer plays are 50% quieter to negotiate new sounds being louder by default.
## Why It's Good For The Game

Security hailer sounds are old and have an audio quality familiar to the 2008 Flash game, while the voice actor of it sounds pretty dull and not very understandable.

This changes hailer sounds to more crispy, high quality, intimidating ones to put fear in the criminals of the station, made by me in Audacity™️ via heavily modifying free TTS by [elevenlabs.io](https://beta.elevenlabs.io/) (Attributed).
## Changelog
:cl:
sound: Security "Compli-O-Nator 3000" hailers sounds have been changed
/:cl:

### CODE REVIEW

**Comment by Iamgoofball** [comment]
@DrDiasyl What's your pipeline for doing the audio effects? If we can distill it into ffmpeg filters we could make this apply automatically when talking through a sec hailer when TTS is active.

**Comment by DrDiasyl** [comment]
> @DrDiasyl What's your pipeline for doing the audio effects? If we can distill it into ffmpeg filters we could make this apply automatically when talking through a sec hailer when TTS is active.

I was using a guide on YouTube on how to make a voice sound like Combine from Half-Life 2 in Audacity, I don't think we can utilize Audacity in the TTS.

**Comment by DaydreamIQ** [comment]
Do they still have the funny emag line?

**Comment by VladinXXV** [comment]
this kills tg culture, or something like that.

On a more serious note, I feel like these are a bit harder to understand, but as long as we're still putting the lines in chat I don't really care that much.

**Comment by mc-oofert** [comment]
soulless and the sounds are less distinguishable than the prior ones

**Comment by Serxule** [comment]
cloaker rp

**Comment by DrDiasyl** [comment]
> Do they still have the funny emag line?

Well if you read the body
> Changes security gas mask hailer sounds to more crispy, high quality, intimidating ones. **(The Emag Beepsky roast line is not touched)**

so answer is - yes

**Comment by Toastgoats** [comment]
It'd be nice if you redid the shut up crime line, the delivery is a little wonky.

**Comment by ArcaneMusic** [comment]
"Go ahead, make my day" also came out a bit garbled personally. It just kinda stumbled over the "make my day" part. Try running it as "Go ahead, make, my, day", and see if that would help sell the delivery while cleaning up the clarity at the same time.

**Comment by BlueMemesauce** [comment]
>Also now the sound hailer plays are 50% quieter to negotiate new sounds being louder by default.

wont this make emag.ogg quieter than intended?

**Comment by Pumpkinoe** [comment]
image
me serving my benefactors

**Comment by DrDiasyl** [comment]
> >Also now the sound hailer plays are 50% quieter to negotiate new sounds being louder by default.
> 
> wont this make emag.ogg quieter than intended?

Right, will make the file itself louder then.

**Comment by Googles-Hands** [comment]
I am the law is a downgrade imo

**Comment by moocowswag** [comment]
pick up that can

**Comment by DrDiasyl** [comment]
@Iamgoofball, do you know how to modify the txt file without somehow causing heat death of the universe?

**Comment by Dorsisdwarf** [comment]
These arent all perfect but I like their vibe much better than the robo bass + mild reverb that was added to quickly replace the old stolen effects.

**Comment by DrDiasyl** [comment]
> These arent all perfect but I like their vibe much better than the current robo bass + mild reverb that was added to quickly replace the old stolen effects.

Old ones were stolen? 🤨

**Comment by Learner10** [comment]
I can only hear Combine callouts, and it's so perfect for it. There's a few that need tweaking or retakes, but the spirit is right where it needs to be.

**Comment by Dorsisdwarf** [comment]
> > These arent all perfect but I like their vibe much better than the current robo bass + mild reverb that was added to quickly replace the old stolen effects.
> 
> Old ones were stolen? 🤨

yeah see 22183

**Comment by DrDiasyl** [comment]
This PR is already 14 days old? Wow how fast time flies.
But I'm having my patience until it merges

**Review by ninjanomnom — CHANGES_REQUESTED** [review]
This should use tts for the sounds instead of having premade sound files

**Comment by DrDiasyl** [comment]
> This should use tts for the sounds instead of having premade sound files

Ooh... @Iamgoofball please save me 🙏

**Comment by DrDiasyl** [comment]
@ninjanomnom but what about situations when TTS is down (which is too often to be honest), or if there is no TTS (like a downstream).

TTS is a thing we can't fully depend on.

**Comment by ninjanomnom** [comment]
Then the text of the message still goes in chat. TTS is still being developed so it's unstable, but I'd like to depend on it. Mask audio isn't important enough to merit having backups for server failures.

**Comment by Iamgoofball** [comment]
@ninjanomnom can we wait until we have a real server again that isn't literally hosted off of my box first

**Pull request closed without merging**
