### PR TITLE
Advanced Syndicate Infiltrator, Kilo-pattern Emergency and additional shuttles.

### PR DESCRIPTION
**Pull request by Okand37**
## About The Pull Request

Includes a set of kilo pattern shuttles for the arrival, cargo, ferry, labour, and mining types along with a new and purchasable emergency shuttle. Additionally, it adds a new type of syndicate infiltrator, codenamed the tortoise. All of these shuttles are accessible via the shuttle loader and work on any station barring the arrival and cargo variants. Shuttles in order from most important to least important:

**emergency_kilo**; a fully modeled shuttle including two small cargo bays, a more spacious infirmary, and regular security and E.V.A. amenities. Main bay seats 40, 2 E.V.A., 7 Holding Area, 6 Cockpit, 2 Infirmary.
"A fully functional shuttle including a complete infirmary, storage facilties and regular amenities." **Priced at 5000 credits.**
image

**infiltrator_advanced**; nicknamed the "tortoise," this syndicate shuttle includes a beefier redesign of the original syndicate infiltrator complete with medical bay, armory, power systems, dual airlocks and a centralized preparation room. Important access-way doors function off of syndicate access (req_access=150). Design helps mitigate bomb damage while allowing for more close-quarters boarding combat. Currently accessible from the shuttle loader, may see itself added with a new syndicate shuttle selector depending on reception.
image

 
**mining_kilo**; modernized mining shuttle interior with a small bundle of emergency supplies. With the new(er) directional shuttle docking system, should work on any station.
image

**labour_kilo**; slightly reskinned labour shuttle, compatible replacement for any standard gulag shuttle. Features an additional seat and modernized interior.
image

**ferry_kilo**; in addition to regular seating, features two rechargers, emergency supplies and radios, and a rear-placed ferry shuttle request console. Compatible with the universal ferry dock.
image

**cargo_kilo**; a regular, run-of-the-mill cargo shuttle with a fancier interior. Crates are onloaded through the bottom blast door, and offloaded at the top. May be incompatible with certain docks or conveyors.
image

**arrival_kilo**; a standard sized arrival shuttle meant for low to medium populations. Closets and arcade machine replace by conventional emergency supplies, easily accessible for new players.
image

## Why It's Good For The Game

The kilo-pattern emergency shuttle provides a new and fresh design to the choice of available, fully functional shuttles for purchase by the crew. In addition, the syndicate advanced infiltrator adds a new venue for syndicate operatives and opens up the possibility of various shuttles being added to the syndicate's arsenal for use to help compliment their unique gimmicks or operative styles.

## Changelog
:cl: Okand37
add: Nanotrasen Shipyards have released a set of Kilo-pattern shuttles including a new Kilo Emergency Shuttle, purchasable for 5000 credits!
add: Syndicate Skunkworks have ushered in a new model of the infiltrator-pattern shuttle designed for operative insertion and extraction. Rumours report the new shuttle to be an up-armoured version of the original design that Nanotrasen Intelligence workers have taken to calling the "tortoise."
admin: New shuttles are accessible from the shuttle loader!
/:cl:

### CODE REVIEW

**Comment by zeroisthebiggay** [comment]
these are very cool kilo station when

**Comment by FloranOtten** [comment]
That cargo shuttle is incompatible with Meta conveyors.

**Comment by Okand37** [comment]
> That cargo shuttle is incompatible with Meta conveyors.

> All of these shuttles are accessible via the shuttle loader and work on any station barring the arrival and cargo variants.

Don't worry, I'm aware! Some of the shuttles are to be used at a later date, but I added them as a batch group since they're all related. The rest of them will work independently and can be used on any station, but the arrival and cargo variants are meant for a specific dock in mind.

**Comment by FloranOtten** [comment]
> > That cargo shuttle is incompatible with Meta conveyors.
> 
> > All of these shuttles are accessible via the shuttle loader and work on any station barring the arrival and cargo variants.
> 
> Don't worry, I'm aware! Some of the shuttles are to be used at a later date, but I added them as a batch group since they're all related. The rest of them will work independently and can be used on any station, but the arrival and cargo variants are meant for a specific dock in mind.

Kilo station confirmed?

**Comment by WJohn** [comment]
These are... very warning line intensive. It's actually rather distracting. I think you desperately want to use a border of some type because those look good but warning lines are really the only ones available. Might be best to use your own border types instead.

**Comment by Okand37** [comment]
> These are... very warning line intensive. It's actually rather distracting. I think you desperately want to use a border of some type because those look good but warning lines are really the only ones available. Might be best to use your own border types instead.

Looks fine to me!

**Comment by anconfuzedrock** [comment]
Yes it looks fine to you, that's why you're the one who added them. Wjohn is someone who isn't you, and is able to recognise flaws in your design.

Protective hats fucking everywhere is probably not an idea, Assistants shouldn't get free hard hats literally off the arrivals shuttle especially when pdas already have lights.

**Comment by Okand37** [comment]
> Yes it looks fine to you, that's why you're the one who added them. Wjohn is someone who isn't you, and is able to recognise flaws in your design.
> 
> Protective hats fucking everywhere is probably not a good idea, Assistants shouldn't get free hard hats literally off the arrivals shuttle especially when pdas already have lights.

lol

**Comment by anconfuzedrock** [comment]
well lol to you too, if you're so incapable of receiving any form of criticism.

**Comment by WJohn** [comment]
wtf confusedrock that wasn't what i was going for at all. i feel like there's too many warning lines and it's too intensive on the eyes and that maybe something *other* than black/yellow stripes literally everywhere could be done instead. we have other stripe colors, some things also simply do not need to have stripes just because they're there.

i know okand likes to have extremely detailed and intricate floor patterns, and it's recognizably their work. i just felt like it's gone a bit overboard here in the cramped conditions of shuttles.

**Comment by Okand37** [comment]
> wtf confusedrock that wasn't what i was going for at all. i feel like there's too many warning lines and it's too intensive on the eyes and that maybe something _other_ than black/yellow stripes literally everywhere could be done instead. we have other stripe colors, some things also simply do not need to have stripes just because they're there.
> 
> i know okand likes to have extremely detailed and intricate floor patterns, and it's recognizably their work. i just felt like it's gone a bit overboard here in the cramped conditions of shuttles.

It'd definitely be nice to have some more borders, maybe something simple and black/grey to help separate clashing colours a bit more. I tend not to use the white stripes since they aren't full on borders and don't really do much to break up colours, in my opinion. 

I'd be down to using different varieties of  borders if we had them, but I suck at spriting so I probably won't make them myself. For the most part I'm happy with the hazard stripes, though, but that's just me personally.

**Comment by CRITAWAKETS** [comment]
What is the Kilo prefix for? I guess i am unenlightened. I wish to be enlightened on the ways of "Kilo".

**Comment by Okand37** [comment]
> What is the Kilo prefix for? I guess i am unenlightened. I wish to be enlightened on the ways of "Kilo".

As a comparison, it'd be like saying Delta is a "Delta-pattern" station and its shuttles are "Delta-pattern" shuttles. Essentially, a similarly themed group of designs/schematics.

**Comment by FloranOtten** [comment]
Called it

**Pull request merged**
