### PR TITLE
Add a new ambient track to space

### PR DESCRIPTION
**Pull request by the-og-gear**
## About The Pull Request
Adds in a new ambient track for space exploration! The track is hand-produced by myself, designed to evoke a more ethereal feel from the listener.
The filename is intentionally not the track's actual name, an attempt to somewhat standardize sound file names so we know their use-case without digging for the filename in code. The original track name and author is also intentionally embedded in the metadata, in an attempt to ensure the history of sounds is able to be documented.

At the request of comments, [here's a link to listen to the track without downloading.](https://voca.ro/1c5Mjlu1N5iz)
## Why It's Good For The Game
A new ambient track never hurt nobody! Really though, it helps to break up the monotony of having five tracks for space exploration, even if it is just a short clip of something new. Hearing title3.ogg for the fifteenth time gets a little old, honestly.
## Changelog
:cl:
sound: One (1) new space ambience track has been added. Good luck and godspeed.
/:cl:

### CODE REVIEW

**Comment by Helg2** [comment]
Leaving a source to listen track without downloading it would be usefull.

**Comment by atlasle** [comment]
a vocaroo link could work

**Comment by the-og-gear** [comment]
Vocaroo link added to original PR text. Enjoy.

**Comment by optimumtact** [comment]
what license are you releasing this under?

**Comment by the-og-gear** [comment]
Defaulting to CC BY-SA 3.0, ideally. I do not plan to release it on any platforms other than shoving it into a github repository and letting it exist, hence the metadata being included with the file to give proper history.

**Pull request merged**
