### PR TITLE
Removes Meteor Mode

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
It is laggy. It is the same every time. People just go afk in a space ruin or on mining, or failing that the bridge, then wait an through an agonizing half hour+ of lag while nothing happens before a ~minute of actual fun when they all try and jump on the shuttle.

You can't even play this mode, there is nothing the crew can reasonably do to actually fight the meteors, you can't do your job, can't do any roleplay, can't build anything, don't get to fight or interact, you just sit in a room off z level for half an hour.

### CODE REVIEW

**Comment by PKPenguin321** [comment]
:-1: :x: :100: please no that was seriously such a funny round

**Comment by Banana-Fist** [comment]
There are obvious problems that need fixing, funny or not, from a design standpoint it's technically broken and should be removed until it's at least playable without admin intervention on multiple accounts.

**Comment by KorPhaeron** [comment]
What he said.

15 minutes of real time to pass through 2-3 minutes of game time is not acceptable, and neither is the round not ending because the shuttle can't move anymore.

**Comment by Incoming5643** [comment]
It usually does not reach that point, I've seen plenty of meteor modes rounds that successfully completed. Something went very wrong that round somewhere

**Comment by KorPhaeron** [comment]
@Incoming5643 

Guess we can test it again or just disable it from rotation for another 2 years before we put it back and find out its broken again

**Comment by KorPhaeron** [comment]
@Incoming5643 

Also what maps were those rounds on?

**Comment by PKPenguin321** [comment]
If you want to reduce lag on it, you could remove smoke from meteor explosions. It might not be much but it's something, I just added support for it in the bomb tesla PR.

**Comment by Incoming5643** [comment]
@KorPhaeron admittedly they were all box

**Comment by KorPhaeron** [comment]
I have zero proof at all but I feel like atmos lag gets way worse on metastation for some reason

**Comment by Jalleo** [comment]
@KorPhaeron its actually the fires and smoke and probably that meteors do not slow down in their spawning.

**Comment by Fox-McCloud** [comment]
It's a stupid game mode

:+1:

**Comment by yackemflam** [comment]
HOW TO FIX THE LAG
STEP ONE
SLOW THE METEORS SPAWNING RATE OR SOMETHING

reasoning:
>Meteor spawn
>Meteor spawn
>Meteor hit
>Meteor spawn
>Meteor spawn
>Meteor hit
>Meteor spawn
>Meteor spawn
>Meteor hit
>Meteor hit
>SERVER SLOWS DOWN A LITTLE
>METEORS SPAWNING DONT GIVE A SHIT
>Meteor spawn
>Meteor spawn
>Meteor spawn
>Meteor spawn
>Meteor spawn
>Meteor spawn
>Meteor spawn
>Meteor spawn
>METEOR HIT
>Meteor spawn
>Meteor spawn
>Meteor spawn
>Meteor spawn
>Meteor spawn
>Meteor spawn
And then there are 50 meteors in spess and the server slows down to a crawl.
Meteors spawning rate doesnt slow down with the server.
:honk:

**Comment by ike709** [comment]
It'd be cool if it adjusted the spawn rate based on how much lag it was causing.

**Comment by KorPhaeron** [comment]
If someone wants to fix it we can readd it. It's only adding/removing one file.

**Comment by Jalleo** [comment]
I am going to look on how to fix that either wedbesday or thursday if nobody else does. (I suggest someone else does)

**Comment by KorPhaeron** [comment]
I wish I was more surprised that so many people are voting against removing a mode that literally does not function and requires an admin restart so people can keep playing the game

**Comment by Bawhoppen** [comment]
Kor, on basil meteor is played as a legit mode occasionally, so improve don't remove

**Comment by Supermichael777** [comment]
meteors should del if they reach their original z level

**Comment by AnturK** [comment]
Remove it from the default config please.

**Comment by optimumtact** [comment]
This should be a config adjustment on the prod servers as other servers might be using meteors.

**Comment by Metacide** [comment]
16-08-21-recallpleasewecanrebuild

**Comment by optimumtact** [comment]
There is literally zero wrong with the metor code.

It's atmos and explosion code that bears the blame.

**Comment by AnturK** [comment]
While it's true that performance of meteor mode has nothing to do with the code, i wouldn't mind removal of a mode that can be easily replaced by few admin button presses.

**Comment by KorPhaeron** [comment]
Proposing this again because it's still bad and I'm still getting complaints about it.

**Comment by Cuboos** [comment]
Nice Meme

**Comment by XDTM** [comment]
Meteor mode is 20 minutes of ghostchat before a real round

**Comment by YakumoChen** [comment]
Meteor Mode is fun, just tune down the spawn rate or maybe make the spawn rate less intense over time to simulate the meteors slowing down (and also reduce lag).

Maybe if meteors actually hit on impact instead of going through walls like butter before impacting, there'd be less issue.

**Comment by PKPenguin321** [comment]
Reeeeeeeeeeeeeeeeeeeeee

**Comment by Incoming5643** [comment]
We fixed this, there's even less an reason to do this than before

**Comment by KorPhaeron** [comment]
@Incoming5643 

But there is nothing to do the whole time. At least when an admin is running it manually they can mix it up with other kinds of events, or send the shuttle in a reasonable time period.

**Comment by Ergovisavi** [comment]
Get meteor mode out of here. It's not fun and never will be. We have entire zlevel dedicated to ignoring this fucking trash. You don't even interact with meteors because they're just random explosions, there's nothing to actually react to.

R E M O V E

**Comment by Incoming5643** [comment]
It's one of the oldest mode and in terms of maintainability its basically free. Any attempt to remove it for any reason can only be based out of salt. If you don't like the mode, d o n ' t  r u n  t h e  m o d e.

**Comment by CyberbossJHCB** [comment]
You don't need to remove it entirely, just remove it from rotation, I may fix it one day

**Comment by Cuboos** [comment]
Some tweaks to meteor might be nice. Maybe tone it down just enough so that engineers can repair the damage or maybe some sort of fortification could be set up so the round doesn't just end as soon as the message pops up. But Meteor is fun, i've seen some crazy shenanigans happen because of meteor. I once saw a meteor kill 8 people at once on the shuttle, shit was hysterical.

**Comment by PKPenguin321** [comment]
yeah just pull this from the rotation, it is still very fun if an admin wants to run it now and then

**Pull request closed without merging**
