### PR TITLE
Change hydroponics tray and chem dispenser AltClick behavior to be used by RMB 

### PR DESCRIPTION
**Pull request by timothymtorres**
## About The Pull Request

This fixes some consistency issues that were mentioned from refactoring the rotation component in #64441.  Hydroponics trays and chem dispensers have had their AltClick functionality transferred:

- Hydroponics trays now empty their reagents with RMB
- Chem dispensers now eject their beakers with RMB

This was done so that AltClick will always be used for rotation.  Just like how CtrlClick is used to drag objects, we want to have the same level of consistency with the hotkeys.  I also added code comments indicating that the AltClick proc was blacklisted from objects that inherit rotation.  This is to prevent people from using the hotkey later on since it is not indicated it's being used for anything.

## Why It's Good For The Game

Better consistency for hotkeys.

## Changelog

:cl:
qol: Chem dispensers have been changed to eject beakers using RMB instead of AltClick.
qol: Hydroponics trays have been changed to empty reagents using RMB instead of AltClick. 
code: Any object that inherits the simple_rotation component will always use AltClick.
/:cl:

### CODE REVIEW

**Review by Mothblocks — CHANGES_REQUESTED** [review]
Change all those to `return ..()` please

**Comment by Angustmeta** [comment]
Can you still right click a tray with plant analyzer (to scan reagents) without having the empty tray prompt pop up?

**Comment by timothymtorres** [comment]
No, it specifically has to be with an empty hand.

**Comment by MrMelbert** [comment]
> No, it specifically has to be with an empty hand.

Damn, currently you can empty the tray with an empty hand and that's hella useful :/

**Comment by Mothblocks** [comment]
I'll see what happens I suppose

**Comment by Mothblocks** [comment]
@MrMelbert We can bring back that behavior but we need a dedicated RightClick or similar proc that works just like the other Click/AltClick.

**Comment by MrMelbert** [comment]
i will cope

**Pull request merged**
