### PR TITLE
Moves hands to a new sprites, uniforms no longer need holes

### PR DESCRIPTION
**Pull request by nicbn**
[Changelogs]: #
:cl: nicbn
fix: Now if you lose arms you won't be able to see through your uniform.
/:cl:

Yes I already patched all holes for hands in uniforms
Yes uniforms that show more than hands still need holes
Yes suits still need holes

### CODE REVIEW

**Comment by epochayur** [comment]
>loose

**Comment by MrDoomBringer** [comment]
finally jesus

**Comment by nicbn** [comment]
Oh no not the merge conflict with the dmi

**Comment by praisenarsie** [comment]
> fix: Now if you loose arms you won't be able to see through your uniform.

lose*

**Comment by ShizCalev** [comment]
ty

**Comment by ShizCalev** [comment]
now we can add cutting people's hands off for petty theft without having to completely amputate their arms, buwhaha

**Comment by FantasticFwoosh** [comment]
Excuse me while i go sprite hooks.

Yarr

Are feet expected to get the same treatment so we can install peglegs below the knee?

**Comment by nicbn** [comment]
Feet are easier to do, just split the sprites and do the same thing I did for hands but with another layer

**Comment by FantasticFwoosh** [comment]
Weaponised peglegs confirmed.

**Comment by nicbn** [comment]
Travis is drunk I think

**Comment by praisenarsie** [comment]
maybe it's time to make it so you can target hands and feet seperately from arms and legs

**Comment by nicbn** [comment]
I'm against making hands and legs new targets, but if you wish to do it go on

**Review by ShizCalev — CHANGES_REQUESTED** [review]
Briefly looking over the changes, will go more in depth later;

All the parade outfits need to be redone. The jackets are cut off, seems priority went to the vests instead? The captain's is completely wrong - belt missing, pants going up the back, ect. Same for assistant formal.

Atmos tech suit's stripe doesn't extend all the way up the leg.

Also most of these sprites have a shadow where the hand used to be. Perhaps that should be moved to a slight transparency around the hand's sprite instead and clean up the shadow on all the uniform sprites.

**Comment by nicbn** [comment]
The shadow thing is so that there won't be any major different between how sprites used to look like and how they look like now. Goon uses this approach too.

I'm not going to redo parade outfits, that's out of the scope of this PR. I didn't got what you mean by jackets being cut off, I stated on the PR that I vests still need holes. The captains and assistant formal belt thing is like this because this is the only way I was able to fill the hole without it looking like garbage.

**Comment by ShizCalev** [comment]
It seems you've misunderstood what I was saying.

I wasn't telling you to completely redo the outfits, I'm telling you to review the changes that you made as these changes wouldn't look good when someone loses their hands and the spot is visible.

image

Example of what I mean. Left is the old sprites, middle is the sprites you have submitted, right is what I'm suggesting to fix the blatant mismatches in the outfits. 

Also 
image
The blue area that is circled is what I meant by the vest, since it's a vest underneath the jacket on those sprites.

**Comment by nicbn** [comment]
@ShizCalev

**Review by ShizCalev — DISMISSED** [review]
corrections:
(these are all in order to make it easier.)

captain - black in hand area
atmos - stripes don't extend to the belt
pirate - hand area still transparent
centcom - black in hand area
sexyclown - hand area still transparent
mailman - inconsistent stripe (it's supposed to be a solid stripe leading up along the side)
sundress - hand area still transparent
ALL _d (except for qm_d & tactifool_d) - hand area still transparent
chef_d - completely transparent
hosalt - belt inconsistent
hosalt_d - inconsistent with hosalt
celtcom_d- hand area still transparent
redskirt - inconsistent waistline

plasmaman - Does this PR work with their outfit? Wouldn't their hands be visible?

trek_next_engsec - inconsistent waistline compared to N & S sprites
trek_next_command - inconsistent waistline compared to N & S sprites
trek_next_medsci - inconsistent waistline compared to N & S sprites
all proceeding _d - hand area still transparent
all proceeding color variants - belt inconsistent (the pixels are loops)
mummy - inconsistent pattern
scarecrow - nothing's actually wrong with this one, just wanted to say good work with it.
lobster - inconsistent patterns
drfreeze - bandoleer inconsistent on east sprite

**Comment by nicbn** [comment]
>pirate - hand area still transparent
>sexyclown - hand area still transparent
>sundress - hand area still transparent

> Yes uniforms that show more than hands still need holes

The area is not hand area is arm area

**Comment by ShizCalev** [comment]
@nicbn 
image
For everything that I'm talking about, I'm referring to the areas that -you- edited, as such it's within scope of the PR.


Also for `hand area still transparent`, I am talking about the area where only hands occupy, and not where the arm area is. Overlay a sprite that had hand holes previously and you'll see the aforementioned gaps which are still visible. In most cases, you just have to bring it up by one more row of pixels.

Example: Sundress
image
Corrected
image

Sexy clown;
image
Corrected
image

ect ect.


Also shading an area & completely replacing a pattern with just a single color are not the same thing. Keep it consistent with the rest of the uniform, just make it darker.

**Comment by nicbn** [comment]
I don't see why the trek next sprites are inconsistent.
And I don't know how to keep the mummy stripes without it looking like garbage or looking inconsistent.

**Comment by ShizCalev** [comment]
Conflict.

**Comment by Cyberboss** [comment]
@nicbn

**Comment by nicbn** [comment]
FUCK

**Comment by nicbn** [comment]
Ok something went wrong

**Pull request closed without merging**
