### PR TITLE
Renames generic armor and athletic shorts

### PR DESCRIPTION
**Pull request by ghost**
Changes the names of the armor vest, and the athletic shorts.

- Renames the generic "armor" to "armor vest."
- Renames the detective's armor vest. Previously it was just named "armor" as well, now it's "detective's armor vest."
- Puts the color of the athletic shorts in their name.

[why]: # (Please add a short description [on the next line] of why you think these changes would benefit the game. If you can't justify it in words, it might not be worth adding:) For consistency, every other colored clothing item I've seen in the game tells you what color it is. With the armor vest, I thought it would sound better with a bit more descriptive name. Plus this should help with chameleon clothing.

### CODE REVIEW

**Comment by ExcessiveUseOfCobblestone** [comment]
color-blind friendly pr

**Comment by Bawhoppen** [comment]
Is it necessary to rename the shorts? They're all technically athletic shorts so the name would still be accurate. This falls into a much larger category where we have to decide on our form of consistency regarding clothing and things like that.

**Comment by ExcessiveUseOfCobblestone** [comment]
color blind people can't tell the difference without naming baw.

**Comment by Bawhoppen** [comment]
okay but does it really matter if they know the difference between completely aesthetic differences

**Comment by ExcessiveUseOfCobblestone** [comment]
"some guy in blue shorts just killed the captain"

**Comment by Militaires** [comment]
good pr for logan paul

**Comment by Bawhoppen** [comment]
if you're colorblind in real life you're colorblind in game

that argument seems like a stretch

**Comment by coiax** [comment]
Chameleon clothing can already cope fine with different items with the same name

**Comment by ExcessiveUseOfCobblestone** [comment]
yes that's how colorblind works Baw,  being colorblind IRL doesn't "turn off" when you play your 2d atmos sim....

**Comment by Bawhoppen** [comment]
@ExcessiveUseOfCobblestone did you not understand my comment

**Pull request merged**
