### PR TITLE
Mapping tool: adds a "structure" spawner that can be used to create "…

### PR DESCRIPTION
**Pull request by kyrahabattoir**
…sets" of objects in a turf at runtime rather than having to stack objects in the map editor. Included are two presets for window and rwindow with a "wiring friendly" icon.

Here is what the "window spawners" looks like in editor:
ineditor

And once the game started, they are replaced by the list of objects they represent.
ingame

Why this is a good idea:
-Making windows, replacing windows, doing electrified grilles is tedious.
-Depending of the order in which you add/remove them it may or may not create a new tile map entry. Less unique tile entries, while not critical, is always nice for commits.
-It means less "stuff" on a given tile, that's always nice for the mapper.
-The spawner icon let you see the underlaying wire/pipe.

### CODE REVIEW

**Comment by xxalpha** [comment]
:+1:

**Comment by Dorsisdwarf** [comment]
:+1:

**Comment by Miauw62** [comment]
would have been more useful with the old windows, but still neat :+1:
@Metacide @WJohn

**Comment by CorruptComputer** [comment]
This is really good :+1: 

Is it be possible to change things in these with var editing?

**Comment by WJohn** [comment]
:+1:

**Comment by kyrahabattoir** [comment]
@CorruptComputer fraid not, but i could maybe make it varedit some stuff.

**Comment by Stickymayhem** [comment]
I can't think of anything other than windows this would be useful for but making it able to var edit things would make it extremely versatile.

**Comment by kyrahabattoir** [comment]
@Stickymayhem The problem is that i don't know of a good way to give them generic var editing, and to pick which of the elements they spawn should be var edited for instance. i mean if they have a huge list attached to them for var editing, it would make them more complicated to use than simply spawning the items themselves.

only way i can see is that you could only varedit very generic things with it and it would copy it to all the target objects: color & id  for instance.

And yeah, i basically made them for windows initially. But i figured there was no harm in making it easy to create other types.
A version with blast shutters for the bridge comes to mind but they require id tagging so, not exceptionally useful i suppose.

**Pull request merged**
