### PR TITLE
Craftable HUDsunglasses

### PR DESCRIPTION
**Pull request by 81Denton**
:cl: Denton
add: You can now craft and disassemble HUDsunglasses! Check out the clothing section of the crafting menu.
/:cl:

Recipe goes like this: sunglasses + HUD + 5 cables = HUDsunglasses. If you want to turn HUDsunglasses into something else, you can remove the HUD part as well.

### CODE REVIEW

**Comment by Kromgar** [comment]
Hud diagnostics now the rd is invincible

**Comment by 81Denton** [comment]
There aren't any sprites for diagnostic HUDglasses, sadly

**Comment by Bombpants** [comment]
Medical hud sunglasses?

**Comment by GuppyLaxx** [comment]
💦 💦 💦 💦

**Comment by fludd12** [comment]
Can you do the same thing for prescription, or would that be too *energy pastry*

**Review by Cyberboss — APPROVED** [review]

**Pull request merged**
