### PR TITLE
new speedwagon sprites: car now runs people down easier

### PR DESCRIPTION
**Pull request by Militaires**
:cl: BASILMAN YOUR MAIN MAN
add: The BM Speedwagon has been improved both in terms of aesthetics and performance!
/:cl:

OLD
speedwagonoldside
speedwagonold

NEW 

newspeedwagon1
newspeedwagon
newspeedwagon0

let's crime it up

since it's so huge now it now crashes into people within the range of its sprite while someone is driving it

### CODE REVIEW

**Comment by Kromgar** [comment]
Fucking wot

**Comment by InsaneHyena** [comment]
Even speedwagon has a new sprite!

**Comment by Militaires** [comment]
afraid

**Comment by Armhulen** [comment]
"new speedwagon sprites"

Actually buffs the speedwagon to crush everyone down the hallway

**Comment by Kromgar** [comment]
image

**Comment by Robustin** [comment]
Don't replace the old sprite, having a "car" that fits through doors is nice, this thing is the size of a fucking hallway. There's room in this world for both.

**Comment by WhiteHusky** [comment]
Either it needs to be 1x2 to fit through doors or 2x3 and be halted by doors smaller than it's size because this is going to be overpowered as fuck at it's current state.

**Comment by ShadowDeath6** [comment]
this actually does fit through 1x1 areas, if you look at the gif in the OP it opens and goes through one of the three doors

**Comment by Armhulen** [comment]
>goes through 1x1 areas

>can hit anyone in a 3x3 aoe

wow cool wow what a """"sprite change""""

**Comment by Militaires** [comment]
@whitehusky @armhulen @robustin

it's already overpowered as fuck and adminspawn anyways

since ill be making a wiz version dont worry ill just give it a craaaaaazy tradeoff like maybe it runs on the wizard's blood as fuel or something

**Comment by Militaires** [comment]
also 

@armhulen

>"new speedwagon sprites"

>Actually buffs the speedwagon to crush everyone down the hallway

dont try to say that's not funny

**Comment by KorPhaeron** [comment]
misleading title try again

**Comment by Militaires** [comment]
@korphaeron the car's name is the BM speedwagon you dumbo

**Comment by GunHog** [comment]
The title is misleading because it is more than just a sprite change. The larger size plus your need to adapt code for it means that your title is no longer comprehensive. Your title does not include the fact that the bigger sprite increases the hitbox - this makes this PR a **balance change**.

**Comment by darkpaladin109** [comment]
Either make it hit people only 1 tile like before or make it only fit down 3 tile wide areas or however many tiles in front it can hit people from now.

**Comment by Militaires** [comment]
@darkpaladin109 why do you want balance features for an adminspawn item that's intended to be bullshit

if you want balanced speedwagon put the feedback on the wizard version when it comes out

**Comment by KorPhaeron** [comment]
No point in having an item so overpowered that admins never spawn it though

**Comment by Militaires** [comment]
@KorPhaeron they can give it to death squad

and also run people over at centcomm

**Pull request merged**
