### PR TITLE
Increases contrast of the new APC sprites

### PR DESCRIPTION
**Pull request by ghost**
_Top is the old, bottom is the new revision_
new_apcs

_Left is new, right is old_
new_vs_old
new_vs_old2
new_vs_old3
new_vs_old4

The APC sprites introduced in #29809 are good in quality but suffer from a few issues; the main one here is that the screens lack contrast, which makes the sprite appear very blurry as a result, as well as unrealistically dim. The new sprites have much darker screen borders and slightly brightened bars on the displays, which makes them much less hard on the eyes.

Closes #29900 
Closes #29922

### CODE REVIEW

**Comment by Kromgar** [comment]
👍

**Comment by PKPenguin321** [comment]
the red and BSOD ones now look worse IMO from being too dark

**Comment by WJohn** [comment]
I think this is a better solution, yes. I was worried that upping the contrast of the text would make things stand out too much, but it seems good. I also somehow completely forgot that APCs actually emit colored light depending on their state, so the sprite-side lighting was totally unecessary and just served to blur things.

**Comment by MoreRobustThanYou** [comment]
i prefer this, yeah

**Comment by PKPenguin321** [comment]
i dont think this is enough of an improvement to make them better than the old sprites, and as i already said it actually makes two of them worse

**Comment by lzimann** [comment]
There's almost no difference between them, and they still look bad...

**Comment by MoreRobustThanYou** [comment]
@lzimann the colors stick out more

**Comment by kingofkosmos** [comment]
Can you make a pic how these look when placed on a west-, east- or north-facing wall? I think that's the main issue with these new ones. They try to force a 3D perspective which only works if they're on a south-facing wall.

**Comment by MoreRobustThanYou** [comment]
@kingofkosmos I don't think these sprites rotate with the walls, at least not on hippie (which has the new sprites, too)

**Comment by YakumoChen** [comment]
Honestly I don't like the new sprites, the power indicators (Machines, Lights, Doors) are too hard to read at a glance, too much sprite real estate is taken up by sprite fluff that doesn't serve a function. The old ones were much more readable by contrast and everything sort of bleeds together with the new sprites.

**Comment by Dorsisdwarf** [comment]
These still look bad and I have no idea how the original PR got through, but this PR makes them slightly less bad

**Comment by kingofkosmos** [comment]
IMO their problem lies is that they are in one certain 3D perspective and the walls are in 4 different ones, and mixing different perspectives on the same tile looks bad.

**Comment by WJohn** [comment]
Closed because #29931 makes this obsolete, as I've had it include the increased contrast from this one.

**Pull request closed without merging**
