### PR TITLE
another comment that didn't add much [DNM]

### PR DESCRIPTION
**Pull request by optimumtact**

### CODE REVIEW

**Comment by Shapsy** [comment]
Oranges is our savior

**Comment by JJRcop** [comment]
c-c-c-... c-........ c-color:us:

**Comment by GunHog** [comment]
^ This. We need a standard set before the "armour" and "colour" spellings get out of hand and start causing maintainability issues.

**Comment by RemieRichards** [comment]
You two realise that variable CANT be called color right? jfc.

**Comment by JJRcop** [comment]
inkcolor :)

**Comment by duncathan** [comment]
realistically it should be called ink_color; it's more clear what exactly it's for and afaik color is more standard across the code and it's good to be consistent

**Comment by optimumtact** [comment]
I'll work on renaming that var DNM for the time being

**Comment by Iamgoofball** [comment]
>ink_colour

**Comment by JJRcop** [comment]
::us:(

**Comment by optimumtact** [comment]
we can't use color for a varname, so we may as well go with the british spelling across the board

**Comment by Iamgoofball** [comment]
doing ink_color was so that we didn't have to use colour you citrus

**Comment by GunHog** [comment]
https://github.com/tgstation/-tg-station/blob/master/code/game/objects/items.dm#L48
>var/list/armor = list(melee = 0, bullet = 0, laser = 0,energy = 0, bomb = 0, bio = 0, rad = 0)
var/armo<b>u</b>r_penetration = 0 //percentage of armour effectiveness to remove

This is why we need need a standard for spellings.

**Comment by Thunder12345** [comment]
Should've left it at just the comment

**Pull request closed without merging**
