### PR TITLE
Adds a new lobby music.

### PR DESCRIPTION
**Pull request by Militaires**
@KorPhaeron 

:cl: basilman
soundadd: added a new lobby music
/:cl:

### CODE REVIEW

**Comment by kevinz000** [comment]
rsc bloat :^)

**Comment by KorPhaeron** [comment]
jesus christ

**Comment by Militaires** [comment]
jojus christ

**Comment by SweaterKittens** [comment]
FOR THOSE WHO AREN'T GOOD AT CODE-DIVING

[](https://www.youtube.com/watch?v=KnU7oQRur54)

**Comment by Militaires** [comment]
diving more like touching a single atom of h2o

**Comment by SweaterKittens** [comment]
I'm not good with code. This is for all the laymen who want to hear the song of your people, Militaires

**Comment by PKPenguin321** [comment]
If you want to play songs to the server, convert it to a <1mb ogg and ahelp a link to admins, don't bloat our lobby songs

**Comment by Militaires** [comment]
@PKPenguin321 this is already 800 kb

**Comment by PKPenguin321** [comment]
subjective. i personally disagree, this is just a jojo meme with horns

**Comment by SweaterKittens** [comment]
While this song is hilarious, I feel like it'll get old pretty quick. It's probably better off left as something an admin can play in-game occasionally.

**Comment by ExcessiveUseOfCobblestone** [comment]
sorta like every other lobby song

**Comment by Jordie0608** [comment]
This song is All Rights Reserved per the creator's soundcloud page thus incompatible with our licence (and also a bad idea).

**Pull request closed without merging**
