### PR TITLE
Fixes the 'stuffed legion' recipie

### LINKED ISSUE #23927: Stuffed legion recipe calls for legion head, requires a legion skull, and what the fuck is that?
Please change the recipe to ask for the right stuff. 
Also, what the fuck is a legion skull? A renamed brain from dismembered heads?

### PR DESCRIPTION
**Pull request by FantasticFwoosh**
:cl: Moonlighting Mac says
fix: Due to a clerical error in the chef's cookbooks now being resolved, you can now make the pristine cookery dish "Stuffed Legion" out of exotic ingredients from Lavaland. 
experiment: After being found again you will now be able to enjoy its special blend of flavors with your tastebuds. Mmm.
/:cl:

[why]: # (Please add a short description [on the next line] of why you think these changes would benefit the game. If you can't justify it in words, it might not be worth adding:) 
This piece of food is a worthy culinary addition to the kitchen as it both heals & feeds spacemen for the labors of miners bringing back even empty legion souls to use in crafting rather than discard them. The medicinal tricordazine present within also allows miners to heal over the course of their station lunch-break.

This fix amends the issue highlighted in #23927 and introduced by a mixture of a unobtainable object in the recipe & a broken sprite reference (a typo fix of a underscore needed to "stuffed_legion" in food.dmi) introduced in @TrustyGun 's flawed original PR #17219

Fixes #23927

### CODE REVIEW

**Comment by Repukan** [comment]
>Fwoosh coding 

IT BEGINS

**Comment by FantasticFwoosh** [comment]
You'll never shine if you don't glow.

**Comment by Core0verload** [comment]
Then remove legion skull too. It's unobtainable AND unused now.

**Comment by FantasticFwoosh** [comment]
No point @Core0verload it was unobtainable & unusable before, but its still a object people could use in future. I don't feel like there's anything to gain from destroying it. I have personal plans for it.

**Pull request merged**
