### PR TITLE
Screw Box Part 2: Bad Wall-pipe Tendency

### PR DESCRIPTION
**Pull request by mrhugo13**
## About The Pull Request
Changed most if not all of the pipe-net to be more pleasing and less painful to deal via trying to minimize wall-pipes and making better use of the hallways for said pipes.

Images to compare with [webmap](https://affectedarc07.github.io/SS13WebMap/TG/BoxStation/index.html)
dreammaker_2020-04-24_13-37-29
dreammaker_2020-04-24_13-37-39
dreammaker_2020-04-24_13-38-02
dreammaker_2020-04-24_13-38-09
dreammaker_2020-04-24_13-38-46
dreammaker_2020-04-24_13-38-52
dreammaker_2020-04-24_13-39-31
dreammaker_2020-04-24_13-39-35
dreammaker_2020-04-24_13-39-41
dreammaker_2020-04-24_13-39-59

## ~~TODO before turning into a proper PR~~
- [x] Fix Command/Main-hallway pipe-grid.
- [x] Fix Security/Security-hallway pipe-grid.
- [x] Fix Medbay pipe-grid.
- [x] Fix all Service departments pipe-grids.
- [x] Fix Engineering pipe-grid.
- [x] Fix Cargo pipe-grid.
- [x] Fix Science pipe-grid.
- [x] Clean up any mess in maintenance.
- [x] Become messiah of atmosians by fixing/improving the Boxstation turbine piping.
- [x] Finish/Fix up loose ends (I.E: Arrivals & Escape)

## Why It's Good For The Game
I don't think i need to tell you that using wall-pipes this liberally is terrible and should be kept to an absolute minimum, but yeah, wall-pipes are terrible and makes atmos have a generally harder time without providing much reward for it.

## Changelog
:cl: Vondiech
balance: Nanotrasen has overhauled Boxstations pipe-grid blueprint, and has so far found that Atmospheric Technicians & Station Engineers has had a decrease in deaths caused by extreme mental exhaustion.
/:cl:

### CODE REVIEW

**Comment by trollbreeder** [comment]
Wall pipes < Piping on different layers

**Comment by mrhugo13** [comment]
Should've further improved Security, Security Hallway, Dorms, Arrivals, and North-East Maintenance.

Will get onto the next item on the list tomorrow.

**Comment by mrhugo13** [comment]
Medbay done and did some groundwork for science/service.

**Comment by mrhugo13** [comment]
Service Departments off the list and their maint mostly cleaned up, might re-visit it for the 8th item on the list.

**Comment by mrhugo13** [comment]
I really don't feel like tackling box again today, I'm still aiming to have this PR done by the end of the week but for now I'm putting it off.

**Comment by mrhugo13** [comment]
Did both Engineering _&_ Cargo today to make up for doing barely anything yesterday.

**Comment by mrhugo13** [comment]
That's _should_ be all of it now... Science is done and i fixed up a few things that i didn't have solutions at the time for, but do now. Maint should be as clean as i can get it and most if not all loose ends have been dealt with.

**Comment by mrhugo13** [comment]
fuck

**Comment by mrhugo13** [comment]
This was way too big of an oopsie so i'm just gonna PR it again

**Pull request closed without merging**
