### PR TITLE
Black crossbreed extracts for xenobio

### PR DESCRIPTION
**Pull request by Seris02**
## About The Pull Request

Adds transformative crossbreed extracts from https://tgstation13.org/wiki/Guide_to_xenobiology.

Also if anyone can think of a better way to write the code that I added in scanner.dm, please tell me, because I absolutely hated writing it and I still hate it.

## Why It's Good For The Game

Xenobio crossbreeds are good and should be finished.

## Changelog
:cl:
add: transformative xenobio crossbreeds
/:cl:

### CODE REVIEW

**Comment by CRITAWAKETS** [comment]
No features november kinda dooms this, please just PR after december and hope xenobio doesnt get removed.

**Comment by Seris02** [comment]
Ah. Well, that sucks, alright then.  Still gonna keep it up until it passes the checks and I fix all the things needed, then I'll take it down, I suppose.

**Comment by Seris02** [comment]
Actually, might as well keep it up anyway, November is nearly over.

**Comment by LemonInTheDark** [comment]
Closing due to #54733, I'm not sure on the status of xeno, personally I dread furthering the powercreep, but this can be discussed at a later date

**Comment by moocowswag** [comment]
power creep (uncountable) (collectible games, video games, role-playing games) The situation where updates to a game introduce more powerful units or abilities, leaving the older ones underpowered.

I really wouldnt say this is more powerful than what xenobio currently has to offer, its a t4 slime crossbreed that to most players would only help them defend xenobio, provided that player puts the time into it. (which means delaying better alternatives such as golem spam or some of the more combat oriented crossbreeds.)

**Comment by Rukofamicom** [comment]
@Seris02 I'd like to point out that I have a code bounty for this active on Beestation's repo.

**Comment by Seris02** [comment]
I'm gonna be honest, it's extremely compatible with the plans there, only a few things would need to be changed buuuuut I'm too lazy to do that right now. You can have someone else port over this if you want.

**Comment by Blevruz** [comment]
Should this be reopened?

**Pull request closed without merging**
