### PR TITLE
Deletes a Clock Cult changelog mistakenly left in the strings folder for four years. 

### PR DESCRIPTION
**Pull request by MrMelbert**
## About The Pull Request

Removes `strings/clockwork_cult_changelog.txt`

## Why It's Good For The Game

Saves us a few bytes

## Changelog

Not needed

### CODE REVIEW

**Comment by JohnFulpWillard** [comment]
stop deleting fun

**Comment by capsaicinz** [comment]
1984

**Comment by optimumtact** [comment]
A smiling mr bean takes up the photo, the words rsc debloating appear in bold impact white text

**Comment by Mothblocks** [comment]
Bring back stargazers and I ewill merge this

**Comment by LemonInTheDark** [comment]
I'll merge you with the floor

**Pull request merged**
