### PR TITLE
Fixes the amazing disappearing c4

### LINKED ISSUE #15785: Invisible C4
### What is the problem?
C4 goes invisible when you place it on a space_heater

### How can the problem be reproduced?
Turn space heater on
Place C4 on space heater (With long timer for suspicion clearing long con)
Turn space heater off
C4 disappears

Probably works on other objects that change their sprite, can't think of any though.

### PR DESCRIPTION
**Pull request by Incoming5643**
I don't really buy into this fix token meme but whatever, here's an easy one so I can stay solvent in case it somehow manages to stick.

fixes #15785

### CODE REVIEW

**Comment by Incoming5643** [comment]
and no unless you want to code in a "priority overlays" system there's really no quicker way to do this.

**Comment by Iamgoofball** [comment]
@incoming throw it on fastprocess

**Comment by Incoming5643** [comment]
Wouldn't that throw all of SSobj on fast process?

**Comment by Iamgoofball** [comment]
No? Its just the c4

**Comment by Incoming5643** [comment]
Does checking for an overlay in a list of overlay cost a lot, my gut worries that maybe it does.

**Comment by coiax** [comment]
If the c4 doesn't disappear when it's added back to the overlays, you could drop out of the fast processing list. Alternatively, given that C4 is temporary, you could probably cope with fastprocessing it, it is only visual after all

**Comment by Incoming5643** [comment]
It is temporary but the timer can be set to up to 60000 seconds

**Comment by Cruix** [comment]
Would it be better to just have a separate list of overlays that should always remain on top, and change all instances of "overlays.Cut()" and "overlays +=" with procs that handle it?

**Comment by phil235** [comment]
that's a pretty hacky solution :confused:

**Comment by Incoming5643** [comment]
it's a pretty hacky problem

**Comment by Incoming5643** [comment]
closed because I can see an elegant solution but I don't have the wherewithal to work for it and it'd be dishonest to fix a problem in a sub optimal way.

**Pull request closed without merging**
