### PR TITLE
Adds tip about being able to make a windoor stay open by clicking it open rather than bumping it open

### PR DESCRIPTION
**Pull request by MrsTonedOne**
I've already added this to live.

### CODE REVIEW

**Comment by bgobandit** [comment]
if only people mentioned all these tips the first 20 times I asked for tips

**Comment by Anonus** [comment]
People don't know this somehow.
You should note that it can be closed by clicking it again.

**Comment by AlexCrimson** [comment]
I didnt figure this out for quite a long time. Sure is a super useful tip. Like Alt + clicking on a tile.

**Comment by MrStonedOne** [comment]
it won't conflict, we don't touch the same lines

**Comment by duncathan** [comment]
I literally never knew this

**Comment by CosmicScientist** [comment]
:+100: this is something I only figured out after trial and error, closing it again took even longer to find out especially since I learnt this in the upload windoors where the sprite gets covered over by the one pane of glass (unless you alt+click but this was back when we still had locker right+click options so screw knowing that).

**Pull request merged**
