### PR TITLE
/obj/screen --> /atom/movable/screen

### PR DESCRIPTION
**Pull request by TemporalOroboros**
Repaths screen objects to /atom/movable

## About The Pull Request
Repaths screen objects to be based off of `/atom/movable` instead of `/obj`

~~Please DNM until I get around to testing it.~~ Done

## Why It's Good For The Game
Might reduce some memory usage?

## Changelog
:cl:
code: Repathed screen objects
/:cl:

### CODE REVIEW

**Comment by Jared-Fogle** [comment]
> Please DNM until I get around to testing it.

draft pr's are a thing

**Comment by TemporalOroboros** [comment]
> 
> 
> > Please DNM until I get around to testing it.
> 
> draft pr's are a thing

Found it

**Comment by YPOQ** [comment]
According to https://secure.byond.com/forum/post/2256093 subtypes of /atom/movable are just subtypes of /obj.
Try VVing a screen object and see if it still has obj-specific vars.

**Comment by TemporalOroboros** [comment]
@YPOQ Just tested it, apparently this is valid?

**Comment by Rohesie** [comment]
> 
> 
> According to https://secure.byond.com/forum/post/2256093 subtypes of /atom/movable are just subtypes of /obj.
> Try VVing a screen object and see if it still has obj-specific vars.

This only refers to the internal id, but the softcode variables should be different.

**Comment by Rohesie** [comment]
This is a very good change.
Let us know when it's tested and ready.

**Comment by TemporalOroboros** [comment]
@Rohesie I tested it a bit and it worked as expected. It would probably be ready to merge now.

**Comment by Cyberboss** [comment]
Conflicts

**Comment by Rohesie** [comment]
Could you get the conflicts solved?

**Comment by TemporalOroboros** [comment]
Alright. But it might take a while, my professors really packed this weekend.

**Comment by Rohesie** [comment]
There's no rush, focus on your classes. That should take priority.

**Comment by TemporalOroboros** [comment]
@Rohesie I finally got around to it.

**Comment by Cyberboss** [comment]
👍🏿

**Pull request merged**
