### PR TITLE
Adds microtransactions allowing players to buy lag,

### PR DESCRIPTION
**Pull request by MrsTonedOne**
lag is no longer free

### CODE REVIEW

**Comment by evsey9** [comment]
NANI?!

**Comment by ninjanomnom** [comment]
💰 💵 💰 💵 💰 💵 💰 💵 💰 💵 💰 💵 💰 💵 💰 💵 💰 💵 💰 💵 💰 💵 💰 💵 💰 💵 💰 💵 💰 💵 💰 💵 💰 💵 💰 💵 💰 💵 💰 💵 💰 💵 💰 💵 💰 💵 💰 💵 💰 💵 💰 💵 💰 💵 💰 💵 💰 💵 💰 💵 💰 💵 💰 💵 💰 💵 💰 💵 💰 💵 💰 💵 💰 💵 💰 💵 💰 💵 💰 💵 💰 💵 💰 💵 💰 💵 💰 💵 💰 💵 💰 💵 💰 💵 💰 💵 💰 💵 💰 💵 💰 💵 💰 💵 💰 💵 💰 💵 💰 💵 💰 💵 💰 💵 💰 💵 💰 💵 💰 💵 💰 💵 💰 💵 💰 💵 💰 💵 💰 💵 💰 💵 💰 💵 💰 💵 💰 💵 💰 💵 💰 💵 💰 💵 💰 💵 💰 💵 💰 💵 💰 💵 💰 💵 💰 💵 💰 💵 💰 💵 💰 💵 💰 💵 💰 💵 💰 💵 💰 💵 💰 💵 💰 💵 💰 💵 💰 💵 💰 💵 💰 💵 💰 💵 💰 💵 💰 💵 💰 💵 💰 💵 💰 💵 💰 💵 💰 💵 💰 💵 💰 💵 💰 💵 💰 💵 💰 💵 💰 💵 💰 💵 💰 💵 💰 💵 💰 💵 💰 💵 💰 💵 💰 💵 💰 💵 💰 💵 💰 💵 💰 💵 💰 💵 💰 💵 💰 💵 💰 💵

**Comment by ACCount12** [comment]
I don't think this would give players enough sense of pride and accomplishment. Better pack the tick-packs of lag into microtransaction lag-boxes, with each pack containing a random amount of lag.

**Comment by ninjanomnom** [comment]
included in #32757

**Pull request closed without merging**
