### PR TITLE
TEST PR - REMOVE COMMENTS (NUMBER TWO) (NULL EDITION)

### PR DESCRIPTION
**Pull request by san7890**

### CODE REVIEW

**Comment by san7890** [comment]
oh god dammit this was supposed to be on my fork

**Comment by san7890** [comment]
i'll be back later

**Comment by Mothblocks** [comment]
Empty bodies show up as *null*?

**Comment by san7890** [comment]
@Mothblocks Unless I'm reading this error wrong.

image

https://github.com/tgstation/tgstation/actions/runs/3382875608/jobs/5618241641

**Comment by Mothblocks** [comment]
Wow

**Pull request closed without merging**
