### PR TITLE
Voluntary scream sounds (but with spam prevention)

### PR DESCRIPTION
**Pull request by ModDownloading**
Lets voluntary screams make sound again, but tacks on a 5 second cooldown (now only for the audio, not the emote itself) for spam prevention.
5 seconds is an arbitrary number I came up with in about that much time, I'm more than willing to listen to suggestions of other cooldown lengths if you feel 5 seconds is too long/too short.

## Why is this good for the game

Because having a cooldown seems to work to prevent similar noise or hand-object making emotes (like blowing kisses or deathgasps), so this should be able to return scream sounds without the spamming.

I considered the alternative of merging the oxyloss screams (20 oxygen damage per scream, no screaming if you are 20 health or fewer away from crit), but this seems like a better option and cooldowns are already implemented in emote code so no need to create a new var just to check if something is voluntary in mob/living/carbon/human/emote or if something is a scream in datums/emotes.

## Changelog
:cl:
add: Voluntary screams can now produce sound, with a cooldown.
/:cl:

### CODE REVIEW

**Comment by ModDownloading** [comment]
Woah there bot, I've only ever made one feature pull request before this and that was last year, which I closed myself since it got changed. Why am I at -9?

**Comment by RaveRadbury** [comment]
> Woah there bot, I've only ever made one feature pull request before this and that was last year, which I closed myself since it got changed. Why am I at -9?

Have you made any PRs on TGMC?

**Comment by moocowswag** [comment]
Have you ever heard 50 people scream at the same time? 

No

*pulls out nanite remote* Would you like to?

**Comment by Qustinnus** [comment]
this PR implies that people could ever voluntarily scream with audio.

**Comment by ModDownloading** [comment]
@moocowswag Ha, if that becomes a problem, I'm willing to try implementing a blacklist for nanite forced speech.

**Comment by Qustinnus** [comment]
also the alternative of 20 oxy damage is ridiculous. Besides that, the audio cooldown should be separate from the normal cooldown.

**Comment by tralezab** [comment]
I hope you're ready to find out why we don't have this

**Comment by ModDownloading** [comment]
@Qustinnus The 20 oxy damage thing was to try and counter salbutamol bypassing the scream damage, but I understand it's ridiculous now. As for the audio cooldown that would still allow people to spam the emote even without the sound, and involuntary emotes still produce the message and the sound because involuntary emotes don't check for cooldown anyway.

If you want me to add an audio cooldown instead of the regular one, it might take me a bit to figure it out, but with a bit of help I would be completely fine with implementing it.

**Comment by Qustinnus** [comment]
if you want to simulate loss of breath there's a literal var for it called breathloss iirc. Also I don't really care if people spam the emote with text, they could do that before, blocking an emote entirely is silly especially for as long as 5 seconds.

**Comment by ModDownloading** [comment]
The *deathgasp emote is already blocked for 15 seconds, and even blowing kisses has a 3 second cooldown. I'm open to changing the 5 seconds if you think that's too long.

**Comment by Qustinnus** [comment]
those both have good reasons to have a cooldown, especially kissing.

**Comment by ModDownloading** [comment]
Point taken, is there an alternative change to the code that you think I should do? I don't think we have a cooldown for audio only yet, but if you could edit some of the code or at least tell me how to do it I would be completely fine with implementing it.

**Comment by maxymax13** [comment]
> 
> 
> those both have good reasons to have a cooldown, especially kissing.

is avoiding the station sounding like AAAH AAAAH AAAAAAH AAAAAAH AAAAAAH even more than it already does not a good reason

**Comment by ModDownloading** [comment]
@maxymax13 Qustinnus suggested replacing the regular cooldown with a cooldown just for the audio, I don't think he was advocating for just reducing the cooldown in general.

**Comment by ModDownloading** [comment]
Actually now I'm going to try implementing the audio cooldown instead since it seems like a good idea.

Just going to edit this PR, no reason to open up a new one since the description won't change much.

**Comment by ModDownloading** [comment]
Ok, the code isn't done yet but it's getting there, going to try and figure out what's going wrong. Anyway, now that the cooldown is only for the audio and not the emote itself the 5 second limit might need changing. Any suggestions?

**Comment by RaveRadbury** [comment]
> Ok, the code isn't done yet but it's getting there, going to try and figure out where I'm supposed to define my new function. Anyway, now that the cooldown is only for the audio and not the emote itself the 5 second limit might need changing. Any suggestions?

Just put it back to where it was, if someone (me) wants to run around screaming in panic because someone is trying to kill me I should be able to hammer my scream hotkey w/o spamming the audio (because it's on cooldown)

**Comment by ModDownloading** [comment]
Fixed the issue, I was being dense and accidentally tried to run the function through the user instead of as a part of the emote.

@RaveRadbury Not to worry, the new way this PR works is that there's only a cooldown on the audio, so you can hammer that button as you're being chased and it will only intermittently make a sound, but always print out the "[player] screams!" message.

**Comment by TheBonded** [comment]
> Have you ever heard 50 people scream at the same time?
> 
> No
> 
> _pulls out nanite remote_, Would you like to?
> 
> I dont know how playing a ton of sounds will effect the servers but i do know using forced speech on everyone at minimum cooldown is enough to slow the server down and grind it to a halt so might need to be prepared to black list screaming emotes from nanite forced speech, could be alot worse.

Does this work with *spin? You could *spin everyone into throwing up endlessly, or *flip people into stuns, and eventually death

**Comment by moocowswag** [comment]
The forced speech cooldown is too high to proc those negative effects last time i checked.

But still something to watch out for future negative effects added to emotes, like scream spam causing oxyloss could have ended poorly.

**Comment by ModDownloading** [comment]
Bugfixing time.

**Comment by Fox-McCloud** [comment]
5 seconds seems reasonable to me.

We have a system very similar to this---if a bunch of people, together, are spamming it, exclusively, it can get annoying once in a while, but, for the most part, it's a reasonable cooldown.

The first week after we had it though, it was...kinda awful---after it was no longer the "new" thing to use "just cause", it was more than reasonable though.

**Comment by ModDownloading** [comment]
Ok problem solved, I needed to create a separate var because piggybacking off of the regular emotes_used caused issues. Already tested it and it works as intended. Should be good for reviewing/merging now!

**Comment by XDTM** [comment]
One of the major reasons i avoided Goon in favor of /tg/ were the incessant scream sounds i kept hearing while playing, i really hope this won't turn into that

**Comment by Qustinnus** [comment]
goon has like 30 audio range with massive reverb all over so thats a bit different

**Comment by ModDownloading** [comment]
That plus goon has a lot more medbay stuff that causes screaming (styptic powder is a BIG part of goon medbay), and I've played enough goon to confirm that's where most of the screaming comes from. If it becomes an issue, I'm open to the idea of making a Hear/Silence Emote Audio preference button, but I doubt it will be that big of a problem.

**Comment by Mothblocks** [comment]
I already don't like the incessant NRP emote spam people do all the time, and I remember this being really awful on places like Goon and CM. 

> Woah there bot, I've only ever made one feature pull request before this and that was last year, which I closed myself since it got changed. Why am I at -9?

A feature is -10.

**Comment by ModDownloading** [comment]
@Mothblocks Did you add the label because you want me to extend the cooldown on the audio or because we should wait for a vote/additional maintainer input?

**Comment by Mothblocks** [comment]
I added the label in case any other maintainer feels differently.

**Comment by Farquaar** [comment]
I hope this gets merged. I can think of many situations where a scream for help would have saved my life.

**Comment by stylemistake** [comment]
Nobody will hear your screams when everyone screams for the memes.

**Comment by tralezab** [comment]
*hits my hotkey to spin flip clap cough laugh scream*
nothing personnel kid

**Comment by Qustinnus** [comment]
@tralezab arent you an admin

**Comment by tralezab** [comment]
bazelart is

**Comment by ModDownloading** [comment]
If it is absolutely necessary, I would be willing to make the audio cooldown 10 or even 15 seconds instead. I can't justify going higher than that because deathgasps already have a 15 second cooldown, and are typically more obnoxious than screaming. This much of a cooldown would make spamming impossible, but I'm hesitant to change it to 15 unless its the only way the PR will get merged.

**Comment by Mothblocks** [comment]
> Claps, laughing and coughing don't have cooldowns and would be more spammable than screaming anyway, unless you think I should tack on audio cooldowns to them too (but that would be an issue for another PR).

Coughing doesn't make a noise, but clapping and to a lesser extent laughing are spammed all the time. That's what I'm basing my disdain for it on--people do it no matter what the cooldown would be.

**Comment by ModDownloading** [comment]
@Mothblocks Ok, if I change the cooldown to 15 seconds that's on par with deathgasp, which people can hotkey and spam right now with a more obnoxious sound than screaming.

If someone really is insistent on creating a cacophony, they can do it already, but they will likely get a talking to by the admins for spamming. Having a scream cut in there every 15 seconds won't change much there, and it is far less likely to be spammed than clapping or laughing literally every second.

Could you please reconsider this if I change the cooldown to 15 seconds?

**Comment by Mothblocks** [comment]
Deathgasp doesn't make a sound, I'm not sure what you're talking about.

> but they will likely get a talking to by the admins for spamming

They never, ever do.

**Comment by ModDownloading** [comment]
@Mothblocks Lizard and borg deathgasps make sounds, they're both in the voice folder, and whether or not the admins have a talking with people who are spamming isn't the core of what I was trying to say, I was just pointing out that if someone is clapping and laughing every second, having them scream every 15 seconds isn't going to change much as it's still a cacophony. Therefore, having voluntary screaming isn't going to have a major contribution to people spamming, but will allow people with more benign intentions to have another sound to use.

**Comment by Qustinnus** [comment]
@Mothblocks

I do think there's merit in voluntary scream audio, what if we make it give breathloss so that spamming it makes people self-own?

**Comment by Mothblocks** [comment]
That's what a lot of servers do, but the spam persists no matter what--people still spam spin even though it makes you barf, for instant.

**Comment by ModDownloading** [comment]
@Qustinnus @Mothblocks I could attach breathloss here too, possibly on top of an audio cooldown, that would make it impossible to scream if you're below a certain breath threshold.

**Pull request closed without merging**
