### PR TITLE
Human sounds now depend on body type

### PR DESCRIPTION
**Pull request by JohnFulpWillard**
## About The Pull Request

So there's currently a problem where our human sounds are dependent on whether you are a male or female, however we have 4 genders in-game.
This leads to scream sounds being female if you're anything but a Male, and gasp shock sounds being male if you're anything but a Female. This is very inconsistent, and I think as a better way of handling this, it should all be handled by Bodytype, since we only have 2 and is a separate choice from gender. This means regardless of gender, you can still choose what sounds your character will make.

## Why It's Good For The Game

Mostly explained in the about section, this lets people who play as they/them & it/its to decide what they should sound like.
I guess as a bonus, it means men now appear more like women if they choose the female bodytype, and vice versa. Or at least I think it's a bonus? I'm not really knowledgeable in this sort of stuff.

I kinda have the same argument as why I think TTS should be accurate. You should be able to customize your character to how you want it, and I think that choosing the non-male/female ones shouldn't give you inconsistent voices.

## Changelog

I actually don't know what to label this.

:cl:
code: Your bodytype now decides what gendered sounds you make.
/:cl:

### CODE REVIEW

**Comment by githubuser4141** [comment]
> it means men now appear more like girls if they choose the female bodytype, and vice versa. Or at least I think it's a bonus? 

So, not trying to come across as a tryhard or a smartypants or anything, but I think the terminology "men and girls" might be seen the wrong way, usually "men and women" is seen as the more "correct" thing to say. Just saying, since I think this server's trying to distance itself from traditional 4chan culture (ofc, it's not nearly as bad as what they'd say on there, lol.)

**Comment by JohnFulpWillard** [comment]
changed it now, sorry

**Comment by lessthnthree** [comment]
Why not let the player pick male/female scream, no matter what body type or set gender?

**Comment by JohnFulpWillard** [comment]
> Why not let the player pick male/female sounds, no matter what body type or set gender? It's already a dropdown for moth laugh etc, why not break human laugh to human male laugh/human female laugh.

Where is the dropdown for moth laugh?

**Comment by nikothedude** [comment]
> Why not let the player pick male/female sounds, no matter what body type or set gender? It's already a dropdown for moth laugh etc, why not break human laugh to human male laugh/human female laugh.

i think thats a downstream thing, tg doesnt let you pick your laugh type

**Comment by lessthnthree** [comment]
Damn, I thought it was here but it was late and I didn't check.

**Pull request merged**
