### PR TITLE
Adds a new barsign sprite

### PR DESCRIPTION
**Pull request by Lexorion**
## Adds a "Maid Cafe" barsign sprite
 (woops,gif is too short! Animation is longer/better ingame)
More barsigns are great so I made this. Also good for events.

### CODE REVIEW

**Comment by bgobandit** [comment]
no player references

**Comment by Lexorion** [comment]
What do you mean?

**Comment by bgobandit** [comment]
memes

**Comment by Lexorion** [comment]
???

**Comment by Repukan** [comment]
-1
Opens up a slippery slope for more fetish shit

**Comment by Lexorion** [comment]
I disagree, maid costumes are already part of the game and I don't think this barsign changes a lot. I did not make the maid costumes and I don't think anyone will use this PR as a reason to add their fetish to the game!

**Comment by calzilla1** [comment]
GAS THE MIME KAWAII WARS NOW

**Comment by Repukan** [comment]
Soon Tm

Leaky cloaca bar
Lusty xeno maid (we already have this for whatever God forsaken reason)

Maids belong in anime, not a space station. This just fully accentuates how out of place it is.

**Comment by ShadowDeath6** [comment]
>not putting the gentoo AI :^) face on it

It's a cool idea I guess but that cat face on the sign triggers me more than I want to admit

**Comment by Magikarpet** [comment]
out of all the fetish shit like the miku costume, sexy clown and mime outfits, actual gay porno uniforms, cat ears, maid xenos, and other actual anime/porno shit how is a maid cafe a "slippery slope fetish thing"? It legitimately feels like you're spewing out a buzzword with no care to context or logic.

**Comment by sawrge** [comment]
Cute!

**Comment by Shapsy** [comment]
Why do you jump immediately to porn, it's a reference to actual maid cafes that exist in real life and are not a product of porn in the slightest

**Comment by Shapsy** [comment]
I don't think you fully understand the word fetish

**Comment by KorPhaeron** [comment]
maid cafes are absolutely a fetish thing

**Comment by Militaires** [comment]
i genuinely regret contributing to fetish shit and now i understand how retarded and out of place this trend is

it's literally people putting in dumb retarded things they like just cause they like it, not even cause "it's cool stuff" it's just cancer i dont want to see any more of

**Comment by Militaires** [comment]
>I disagree, maid costumes are already part of the game

> **maid costumes are already part of the game**

the slippery part of the slope, and now you're making it even slippier.

**Comment by Lexorion** [comment]
What keeps you or anyone else from removing them though? Yes,this is a dumb argument but if it bothers some people **THAT** much,just get rid of it. I'm not even forcing a fetish on anyone,it's just an optional sign.

**Comment by Militaires** [comment]
@Lexorion maintainers and dumb catgirl mains who will yell at you "LOL YOU HATE FUN???? MEOW MEOW MEOW" are who will stop you lexorion, you know this very well.

**the sign itself isnt bad, it's just something reading maid cafe and it's pretty neat, it's that you're giving incentive to more fuckers to add nasty nasty shit**

**Comment by FantasticFwoosh** [comment]
Thank you for your repentance @Militaires , we would like to enroll you into S.C.A.T.

> There's a catperson on the sign, integration efforts have failed to pass cats off just as mutants because most of the coders & admins are pro-animorphic catpeople/fetish approving.

**Comment by Lexorion** [comment]
Well,I'm not quite sure where we draw the line. What _is_ too much? I get your concern but I still doubt that this will help others to get their fetishes into the game.

**Comment by Iamgoofball** [comment]
# S L I P P E R Y
# L
# O
# P
# E

**Comment by Iamgoofball** [comment]
# SLIPPERY SLOPE FOREVER PROVEN TRUE

**Comment by Iamgoofball** [comment]
# ALWAYS PROVEN

**Comment by FantasticFwoosh** [comment]
Well said general goofball.

@Lexorion the culture is already within the game with the connection between maids and catpeople in the same microcosm of culture via a certain game franchise (with ERP) called neoparika or something like that. 

> So you can reason that after we removed all the prior references outside of the SS13 previously, that this is a outstanding reference to that game that would be justified to being removed, same way as we couldn't have talking toy skeletons because that is the property of Undertale etc.

**Comment by Iamgoofball** [comment]
well we did merge talking toy skeletons and that shitty robbie rotten meme and GUESS WHAT NOW THAT THEY ARENT HIP AND KOOL YOU DONT LIKE THEM ANYMORE

**Comment by TrustyGun** [comment]
if more cat-people shit were being added then i will be more inclined to agree with you guys, but its a cat face on a barsigb

**Comment by Iamgoofball** [comment]
# DO YOU NOT UNDERSTAND WHAT THE SLIPPERY SLOPE MEANS

**Comment by FantasticFwoosh** [comment]
@TrustyGun look at the list of things @Magikarpet posted, it only took the maid costume alone and the connection to cat people to further expand. This is the sloping effect of using prior advancements to push a further agenda.

It will only get progressively worse with the references until they are somehow implemented into every department and aspect of the TG server, no matter how subtle they might be.

**Comment by bgobandit** [comment]
>maid cafes being a copyrighted thing that can be sued over

thank you for my daily entertainment

**Comment by FantasticFwoosh** [comment]
You were scared enough to be hesitant with the talking toy skeletons to which it was closed multiple times.

**Comment by Iamgoofball** [comment]
copyright isnt the actual issue its just an excuse

stop adding weeb shit to my spacemans that get used by 1 or 3 fat neckbeards

**Comment by Magikarpet** [comment]
The issue with the line of thinking that this is a "Slippery Slope" thing lies within my post. There are far better arguments than a silly barsign would cause people to add content for said lubricated slope. There are posters that discuss lizard cloaca, xenos in compromising positions, objectives relating to you being pregnant/find the person you love on station and other sexual things if you fear creepy sexual content. There are cat ears as a purchasable items and digitigrades if you fear furshit content. There are multiple anime kawaii uguu references in clothes vendors and as a wizard item in the form of the witch costume if you fear anime trash.

There is literally a better excuse in every direction with other things and it honestly feels like people are looking at this like a yiff yiff thing rather than a silly barsign to add on with the rest of the silly barsigns in the game

This is honestly as stupid as thinking the valentines day event is going to cause everyone to erp

**Comment by Iamgoofball** [comment]
@Magikarpet 
i have fought the addition of EVERY SINGLE ONE OF THOSE ITEMS

i keep getting ignored

**Comment by Repukan** [comment]
Did you not remember the shitstorm raised due to grade legs too.

Slippery slope is just easier to write and explain than using the word precedent. It all comes down to "well this is allowed, why not this."

Which is exactly the problem. Maid cafes are exclusively a fetish thing, even when no sex is involved, due to the context regarding them. Adding something like an "innocent bar sign" will lead to people pointing and say "how come that's allowed but this isn't"?

**Comment by Magikarpet** [comment]
I generally do the reasonable thing and look at the comments on a pr before browsing it to avoid stupid discussions that go into an infinite circle of group x vs group y, especially on any nonhuman additions

ordinarily i wouldnt care about the barsign or this pr at all but the slippery slope discussions seem like an escalation of other conflicts in other prs and general issues people have with other similar content

Although I sincerely doubt that this would add more fetish shit to the game. The reason I'm fine with it is because I feel like it would only allowing dumb maid barman memes to run which people try to support/sabotage said bar with everyone having a giggle over it in the end. But who knows, maybe I'm wrong

**Comment by ShadowDeath6** [comment]
never forget who added the boss of this gym fetish shit to the game

**Comment by PKPenguin321** [comment]
I'll show you who's boss of this gym

**Comment by Repukan** [comment]
Fuck you

**Comment by Screemonster** [comment]
If you don't want it here I'm sure there are plenty of stations that do.

**Comment by Iamgoofball** [comment]
boss of this gym was a finely aged meme

**Comment by Repukan** [comment]
Of course, it certainly feels more in touch with bay, paradise or vore

**Comment by Repukan** [comment]
Also the fuck you was part of the gachimuchi meme chain

**Comment by WJohn** [comment]
i say we leap off the slippery slope and see what lies at the bottom of the pit

i wanna find out.

**Comment by Repukan** [comment]
Of course Mr. "Leaky Cloaca" is on board

**Comment by Repukan** [comment]
Sadly the pit is not "pulsing" for us

**Comment by MMMiracles** [comment]
I mean, this is less of 'someone could fetishize it' and more of 'the entire concept was born out of a fetish."

Probably not the best thing to add.

**Comment by sawrge** [comment]
you people are the biggest queers on the face of the planet and i am smarter than every single one of you

**Comment by sawrge** [comment]
03_clasic-with-bikes-inside

**Comment by ExcessiveUseOfCobblestone** [comment]
Imagine being this booty blasted over a feature that most people don't even know exist and even moreso most people don't even pay attention to.

I agree with goof typically on the slippery slope memes but I honestly cannot fathom how an item that no one even cares to look at half the time will somehow bring on the dawn of catgirl emotes and Purrr-RP or whatever.

**Comment by Repukan** [comment]
We have head patting and tail wagging, these could be used as excuse to add purring.

**Pull request merged**
