### PR TITLE
Extends the cargo conveyor belts into a sushi-style loop

### PR DESCRIPTION
**Pull request by TheVekter**
Changes the cargo conveyor belt to be a bit nicer, easier to use.
- Each of the 2 seconds is controlled by a different switch, so you can run one while having the other one off.

### CODE REVIEW

**Comment by Incoming5643** [comment]
SQUANDERED

**Comment by Chocobro** [comment]
oh baby

**Comment by TheVekter** [comment]
god I fucked it up too, that's the best part

**Comment by GunHog** [comment]
Pictures are pretty much required for map changes!

**Comment by TheVekter** [comment]
Added

**Comment by ike709** [comment]
#7777 wasted. Atleast it is an actual PR...

**Comment by TheVekter** [comment]
I'll fix this in the morning.

**Comment by phil235** [comment]
The blast doors look like they are behind the conveyor, will it appear like that ingame as well?

**Comment by TheVekter** [comment]
Nah, blast doors do that in Dream Maker. They automatically end up under whatever you put them on.

Updated the screenshot in OP. I put the warning tape down around the conveyor for ~consistency~.



Here's what it looks like in-game, @phil235.

**Comment by TheVekter** [comment]
Woo, fixed the map diffs. \o/

**Comment by fj45** [comment]
What if you had the three sections (upper, middle and bottom) separate so techs could have more control of how they move crates around? 
Might not be possible though.

**Comment by paprka** [comment]
Conveyer belts a shit so no

**Comment by TheVekter** [comment]
@fj45 Can you doodle that out for me? I'm having trouble seeing it.

In the current revision, the top half is controlled by one switch and the bottom by another.

**Comment by paprka** [comment]
ss 2015-02-17 at 09 17 29

**Comment by fj45** [comment]
"In the current revision, the top half is controlled by one switch and the bottom by another."

Oh, that should work fine, but you could also have this setup: 

http://i.imgur.com/ToUMeVM.png

**Comment by Jordie0608** [comment]
Changelog

**Comment by TheVekter** [comment]
@Jordie ain't done yet

**Comment by Jordie0608** [comment]
Map merging messed up =P

**Comment by Jalleo** [comment]
I prefer the second one with the one tile seperation @TheVekter

**Comment by Cheridan** [comment]
merge conflict because you didn't use the mapmerge tool :V

**Comment by TheVekter** [comment]
Did too. I'll fuck with this in the morning.

**Comment by Anonus** [comment]
There are airtight plastic flaps, mining used them in one or two spots.

**Comment by TheVekter** [comment]
@Jalleo that's the one in the PR, bro.

**Comment by TheVekter** [comment]
There's the map merge issues fixed, but I'm not seeing any merge conflicts on my end. Hm.

**Comment by TheVekter** [comment]
The station's cargo techs thank you.

**Comment by paprka** [comment]
Pretty sure this reverted something

**Comment by WJohn** [comment]
Always happens.

**Pull request merged**
