### PR TITLE
Removes 'release all' buttons from ORM

### PR DESCRIPTION
**Pull request by RandomMarine**
:cl: RandomMarine
del: The ore redemption machine no longer has 'release all' buttons. Remember to take just what you need and leave some for the other departments.
/:cl:

With the advent of departmental protolathes, keeping the release all button on the ORM is doing more harm than good. More often than not scientists still rush to snatch every sheet available the instant their their request console beeps.
Let's see what needing a little bit more time, clicks and keystrokes does to that habit.

### CODE REVIEW

**Comment by Spaceinaba** [comment]
1) this will not stop material hogging
2) other departments dont use the mats

**Comment by RandomMarine** [comment]
1. Goal isn't to stop entirely. But to discourage. A little extra time can go a long way for that, and to give others time to examine and identify.
2. Absolutely incorrect.

**Comment by 81Denton** [comment]
Other departments can't use the mats if Urist McLabcoat is hogging everything

**Comment by Tlaltecuhtli** [comment]
others department never uses the lathes, if they really wanted they could just ask science (they dont even have ORM access and the fact that no one reported it really shows how much other departments use minerals)

**Comment by Anonmare** [comment]
Honestly you can just remove the ORM's access requirements, you can screwdriver+crowbar the ORM to make it drop all of its sheets which is so easy even a blind clown can do it.

**Comment by ExcessiveUseOfCobblestone** [comment]
I honestly can't imagine people not wanting cool toys, I think they just don't expect the miner-science relationship to be infringed without catching flak for it.

**Comment by Spaceinaba** [comment]
with NEU SCIENCE DEPORTMENTAL LATHS science doesnt research anything that doesnt benefit them anymore from what I can see. Just click the mining upgrades and then b-line for bags of holding.

**Comment by davethwave** [comment]
usually stuff like medical and such research is researched last of all despite it's usefulness so there's never really a use to mats and when there is from what I see they usually just apply the screwdriver and crowbar method.

**Comment by ExcessiveUseOfCobblestone** [comment]
> with NEU SCIENCE DEPORTMENTAL LATHS science doesnt research anything that doesnt benefit them anymore from what I can see. Just click the mining upgrades and then b-line for bags of holding.

unfortunately the only way I see fixing this is making tech more generalized to fit non-science stuff with the science stuff and adjust prices.

You can't lead a horse to water so you gotta force it to drink with code :(

**Comment by Kromgar** [comment]
Motherfucker before there was a release all you know what I did as a miner? Type 50 really quick in every window. It doesnt take much effort

Also if they ever implemented being able to use bluespace to send materials to each department it not be so fucking shit when somebody hogs it all?

**Comment by Shapsy** [comment]
I swear to God the department lathes say something about having bluespace material bins or whatever but I have no clue what that actually means

**Comment by Hatfish** [comment]
Some day that materials delivery PR will get merged and people won't have to kill scientists just to print a light replacer.

**Comment by Mark9013100** [comment]
Much needed change.

**Comment by MrDoomBringer** [comment]
A better fix would be a button that allows someone to dispense a certain percentage of the mineral in stock (like the chem dispenser), rather than being all or nothing.
image

**Comment by 81Denton** [comment]
>Some day that materials delivery PR will get merged
Until that gets merged in 2020, it might be a good idea to remove access restrictions for the ORM.

**Comment by davethwave** [comment]
I would rather expand the access rights rather than removing them entirely.

**Comment by 81Denton** [comment]
Is there really a point when every department has a lathe and you can just screwdriver+crowbar anyway?

**Comment by ExcessiveUseOfCobblestone** [comment]
you could just not have the ORM public access and let supply manage how much goes where 🤔

**Comment by Poojawa** [comment]
make IDs have a point value quota they can extract, which resets after 15 minutes.

**Comment by 81Denton** [comment]
>make IDs have a point value quota they can extract, which resets after 15 minutes.

That's about the average /tg/ round length and would just lead to people deconstructing the ORM by default.

**Comment by imsxz** [comment]
@ExcessiveUseOfCobblestone deltastation ORM isnt public access, and people usually break in to get mats if cargo doesnt open the door. Same with boxstation.

**Comment by ExcessiveUseOfCobblestone** [comment]
Then you can escalate / arrest them.

**Comment by Poojawa** [comment]
then make the ORM impossible to deconstruct while it has ores in it, 8^)

or reward their impatience and greed with slag.

**Comment by ExcessiveUseOfCobblestone** [comment]
BUILD A WALL (between the orm and non-supply)

**Comment by davethwave** [comment]
Just thought of a fun idea... How about making the ORM and mat storage separate structures in cargo where only a cargo tech/ shaft miner can access. If there are no cargo techs or a qm available the storage area would be available to the public.

**Comment by RandomMarine** [comment]
A larger change to how mineral distribution works is warranted, but is beyond the scope of and not mutually exclusive to this PR.

**Comment by Hatfish** [comment]
There's a PR up for that but it's dead in the water now.

**Pull request merged**
