### PR TITLE
Added further limitations on the sound emitter circuit component

### PR DESCRIPTION
**Pull request by Watermelon914**
## About The Pull Request

Sound emitter circuit component has had its volume reduced to have a maximum of 30.
Pitch can only be between 0.5 and 1.5 now.
Sounds can still be played backwards
Added a configuration option to disable circuit component sounds, which admins can toggle in the circuit menu.

## Why It's Good For The Game

I've had complaints of the sound emitter circuit component being abused, so this is an attempt to reduce how much it can be abused by, by decreasing the maximum volume as to not let players cause ear damage. Also, pitch could be set to absurdly low values, so this also fixes that.

## Changelog

:cl:
admin: Added a way for administrators to globally disable circuit component sound emitters.
balance: Further limited the sound emitter component so that maximum volume is reduced and pitch is capped between -50 and 50
/:cl:

### CODE REVIEW

**Comment by iwishforducks** [comment]
no more farting....
(thank god, it was getting run into the ground)

**Comment by Redrover1760** [comment]
First, is making a preference to mute circuit sounds still not a thing in the making? That seems like the obvious thing to do to start off with.

Second, Moo has told me that a pitch range of .3 to 1.8 is probably better? Is it possible to do that instead of removing all the fun that the non circuit noise abusers have instead? The volume nerf should already really help of course.

**Comment by moocowswag** [comment]
Well values restrictions over 1 can definitely be more relaxed because they arnt exponential.

like 1.5 to 3 is double the pitch of 1.5 but 0.5 to 0.25 is half.

My main concern is people might think its louder than it actually is since the vidoes of it that I posted on discord have the sound centered on me (volume drops off ALOT with range)

**Review by MrsTonedOne — APPROVED** [review]

**Comment by optimumtact** [comment]
why is the admin team not banning people doing this

@Mothblocks @MrMelbert @Timberpoes 

I want a justification as to why we can't have nice things because your admins are apparently incapable of doing their job?

**Comment by Mothblocks** [comment]
i have been

**Comment by Watermelon914** [comment]
> Well value restrictions over 1 can definitely be more relaxed because they arnt exponential.
> 
> like 1.5 to 3 is only double the pitch of 1.5 but 0.5 to 0.25 is half with double duration of 0.5. (Not arguing for 3 / 0.25 to be allowed just using them as an example)
> 
> Also the CURRENT lower and upper limits that are proposed are not equal if thats what you were going for, 0.5 = double duration half pitch, 1.5 = 1.5 pitch and duration as far as i can tell, but i guess it makes sense to limit higher values more to avoid ear rape.
> 
> As for volume main concern is people might think its louder than it actually is since the vidoes of it that I posted on discord have the sound centered on me (volume drops off ALOT with range and I dont know how low 30 sounds from range)

I thoroughly tested this, a maximum volume of 30 is plenty loud still. It's just not ear-shattering loud

**Comment by Mothblocks** [comment]
conflicts

**Pull request merged**
