### PR TITLE
Yee-haw Update: Cowboy hats and more!

### PR DESCRIPTION
**Pull request by Farquaar**
## About The Pull Request

https://youtu.be/AFa1-kciCb4

Ever wondered why we had cowboy boots in the autodrobe and clothesmate, but no hats? 
Ever wanted to start a posse but the fluorescent lighting was beating down on your head? 
Ever wanted to run your bar like an old-timey saloon but you were too ashamed of your bald spot? 
Ever wanted to say "See you Space Cowboy" and actually mean it? 

This is the PR for you! 

image
Left to Right: Desperado Hat, Drifter Hat, Sheriff Hat (with Sheriff Vest), Ten-Gallon Hat, & Deputy Hat

All hats are craftable using two sheets of leather. The vest can be crafted with four sheets, and can be attached to jumpsuits.
The drifter hat and the ten-gallon can be found in the clothesmate. The others can be found in the autodrobe.
Every item has in-hand sprites!

This PR does not alter fugitive bounty-hunter items in any way.

## Why It's Good For The Game

It always puzzled me that we had so many western-themed items, clothing, and references, but no hats to back it up. Now we can run cowboy gimmicks to our heart's content, and admins have more than enough to cobble together an event straight out of the old-space-west.

## Changelog

:cl:
imageadd: Due to lobbying pressure from the Yee-haw Conservation Society, Nanotrasen vending machines now stock five new cowboy hats and an old-west vest.
/:cl:

### CODE REVIEW

**Comment by Ryll-Ryll** [comment]
fucking tease

**Comment by Farquaar** [comment]
>  
> fucking tease

I just gotta separate the poster commit out of this branch because I'm a noob

**Comment by wesoda25** [comment]
Wtf i was so hyped

**Comment by dragomagol** [comment]
smh

**Comment by Kylerace** [comment]
@Farquaar you can set it to draft instead

**Comment by Ryll-Ryll** [comment]
There's a trait I added a while ago, TRAIT_NICE_SHOT, that makes you better at ricocheting bullets into people, in the hopes that someone would someday add a cowboy hat (or Revolver Ocelot related piece of clothing) that I could tie it to. Feel free to integrate that trait into your clothing items as you see fit

**Comment by Farquaar** [comment]
> 
> 
> @Farquaar you can set it to draft instead

gotcha

**Comment by Farquaar** [comment]
Oh god it's even worse than before

**Comment by Farquaar** [comment]
I just want to revert a commit
why is life so difficult

**Comment by Farquaar** [comment]
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

**Comment by o0cyann0o** [comment]
Ive been waiting for this for so long.... fuck yes brother..............

**Comment by Bawhoppen** [comment]
Your git is probably fucked just make a new branch and copypaste the cowboy stuff over, IDK why this happened

**Comment by Toastgoats** [comment]
Expecting people to close this on principle after seeing the woody cosplay, but I sincerely hope it gets merged.

**Comment by jlsnow301** [comment]
incredible that github does not offer a yeehaw reaction for this >:(

**Comment by Farquaar** [comment]
I'm going to try my hand at making a new PR on a new branch. Stay tuned.

**Pull request closed without merging**
