### PR TITLE
Organizes the Update Paths tools folder and provides a readme

### PR DESCRIPTION
**Pull request by Son-of-Space**
## About The Pull Request

Puts the scripts for Update Paths in a "scripts" subfolder, labels them all according to their associated PR for easy sequential updating on paths, and provides a readme for how to use the tool and how to make the scripts for it.

I don't know what the label would be for this.

## Why It's Good For The Game

Makes it easier for people to use the update paths tool, update their paths, etc.

## Changelog

:cl:
code: Reorganized the UpdatePaths folder
/:cl:

### CODE REVIEW

**Review by san7890 — COMMENTED** [review]
Might be more worthwhile to change the readme to an MD file so if you go to https://github.com/tgstation/tgstation/tree/master/tools/UpdatePaths , it'll automatically pull up that file (among other pros of having a MarkDown file).

**Review by san7890 — COMMENTED** [review]
Something that may also be of use (will require some work, but would be great to see) is adding a comment to the top of every .txt file with the merge base commit. Here's what I mean.

Let's take the first one: 55614_replacemonkeys.txt . You would go to https://github.com/tgstation/tgstation/pull/55614 and scroll down here:

image

Then, just click on that "hash", and then get the following link: `https://github.com/tgstation/tgstation/commit/f66ca346263273121059ec5cc5031e616b4332af`

Then, you can add a comment that says something like:

`# This file was added in commit f66ca346263273121059ec5cc5031e616b4332af`.

It's pretty hard to do this in retrospect since you don't know exactly what commit hash your PR will be merged under, but this will be a nice future-proofing thing. It's good to have the PR number somewhere, but we are always no more than 5 minutes away from being kicked off GitHub, so it's nice to have commit hashes when feasible to ensure we can build from somewhere. Would be great if you could pass that in this PR, otherwise I'll probably do it myself.

**Comment by Son-of-Space** [comment]
I talked to San and I don't think we're going to do the above.

**Comment by Son-of-Space** [comment]
@AnturK

**Pull request merged**
