### PR TITLE
Blobbernaut chem attacks 2, return of the chem attack

### PR DESCRIPTION
**Pull request by ChangelingRain**
:cl: Joan
tweak: Reduces Lexorin Jelly's oxygen damage significantly.
experiment: Blobbernaut chemical application on attack is back, but much less absurd this time; blobbernauts with an overmind will do 70% of the normal chem damage(plus 4) and attack at a much slower rate than the blob itself can.
wip: As an example, a blobbernaut with the Ripping Tendrils chemical would do 14.5 brute and 10.5 stamina damage per hit.
/:cl:

Lexorin Jelly is slightly darker, Ripping Tendrils is slightly brighter.
Fixes Pressurized Slime giving a message when killed by fire or an explosion.
Fixes core blobs to not need a spawn(0) and a few other fixes.
Lowers core blob overmind get delay to 15 seconds.

Full list of blobbernaut hits to crit/stun, assuming no attempts to escape, armor, or bio protection;
CURRENT/NO OVERMIND: 5 to crit
Ripping Tendrils; 7 to crit, stun at 5
Reactive Gelatin; 5 to 10 to crit, Average of 7(not 7.5)
Energized Fibers; 10 to crit, stun at 5
Boiling Oil; 6 to crit
Sorium; 7 to crit, assuming no nearby walls
Envenomed Filaments; 7 to crit, stun at 5
Lexorin Jelly(AFTER NERF), 4 to crit
Cryogenic Liquid; 9 to crit, stun at 7
Dark Matter; 7 to crit, assuming no nearby objects
Hallucinogenic Nectar; 8 to crit
Pressurized Slime; 7 to crit, stun at 5

### CODE REVIEW

**Comment by GunHog** [comment]
Ooooh yeeeeees! :+1:

**Comment by Zilenan91** [comment]
So you mean crit by stun right, because I don't remember blobbernauts being able to stun people.

**Comment by Anonus** [comment]
No, as they're applying the blob chemicals, some of which have stamina damage and can thus stun.

**Comment by Anonus** [comment]
And yes, hallucinogenic nectar and cryogenic liquid are outliers there, but they have pretty debilitating status effects.

**Comment by tkdrg** [comment]
Looks good, will merge in one hour if it's ready;

**Comment by Anonus** [comment]
confirmed I can literally do anything to blobs and nobody will notice

**Pull request merged**
