### PR TITLE
Adds Shrine Maiden's Outfit for the Chaplain

### PR DESCRIPTION
**Pull request by MadoFrog**
## About The Pull Request

This adds a shrine maiden's outfit and wig to the autodrobe, as well as the gohei as a null rod transformation. [Preview](https://i.imgur.com/2HjJ5vj.png).

The gohei is intended as a defensive measure. It has a force of 5, a block chance of 60, and can purify items the same way a bible can.

## Why It's Good For The Game

It ~placates the weeaboos~ adds another eastern religious option for the chaplain.

## Changelog
:cl:
add: The shrine maiden's outfit and wig is now available in the chaplain's autodrobe
add: The chaplain's null rod can now transform into a gohei
/:cl:

### CODE REVIEW

**Comment by Shadowflame909** [comment]
Wow Reimu

Space has not been very kind to you

**Comment by TerraGS** [comment]
The fated wizard battle approaches

**Comment by ATH1909** [comment]
Why does this have a block chance of 60% while the godstaff null rod forms only have a block chance of 50%? Why would you ever choose one of the godstaff null rod forms over the gohei null rod form?

**Comment by optimumtact** [comment]
oh hell no

**Comment by optimumtact** [comment]
nice sprite though, add it to the costume vendor

**Pull request closed without merging**
