### PR TITLE
Radiation sign no longer has blood on it

### PR DESCRIPTION
**Pull request by nicbn**
Muh imerson

### CODE REVIEW

**Comment by ChangelingRain** [comment]
You can still see the spots that had blood. I think you need a better cleaner.

**Comment by nicbn** [comment]
You mean the spots in the bottom right? I kept them in purpose as they are more like a dirt layer.

**Comment by Bawhoppen** [comment]
I always wondered why it did

**Comment by Xhuis** [comment]
I always thought it was just rust or grime.

**Comment by ShizCalev** [comment]
Would you mind cleaning up the jagged edges a touch too while you're playing with it?
image

**Comment by WJohn** [comment]
Likewise, I just thought it was rust or grime too, and that the sign was metal to allow for that.

**Review by ShizCalev — APPROVED** [review]

**Pull request merged**
