### PR TITLE
[READY] Plasmaman Language: take two

### PR DESCRIPTION
**Pull request by Tacolizard**
:cl: Tacolizard Forever
add: Plasmamen now have their own language. It can be accessed with the 'p' key.
/:cl:

sorry for closing and reopening, i had to delete my fork and remake this pr.

if lizards can have a language why not plasmamen?

v2 changes:
- unfucked my git
- added language icon.

this language will look significantly different than others ingame, due to its high word-length.

### CODE REVIEW

**Comment by GunHog** [comment]
Make sure pAI and Librarians can use it. 

Requesting that silicons be able to understand it as well.

**Comment by Tacolizard** [comment]
@GunHog this pr changes the same exact files that the lizard language does, so i'm pretty sure it already does.

**Comment by Shadowlight213** [comment]
@GunHog silicons can't understand the lizard language.

**Comment by FantasticFwoosh** [comment]
Correction, coiax is making changes that they can @Shadowlight213

**Comment by KorPhaeron** [comment]
What does the icon look like

**Comment by Tacolizard** [comment]
https://gyazo.com/5bf57eb6c89f95730c7ba518461f7dc6

**Comment by Shadowlight213** [comment]
@Fantasticfwoosh pr?

**Comment by Bawhoppen** [comment]
this seems unnecessary at best

**Comment by Tacolizard** [comment]
ask oranges :^)

**Pull request closed without merging**
