### PR TITLE
Some small xenobio gold slime changes 

### PR DESCRIPTION
**Pull request by Bawhoppen**
Removed lusty xeno maid from gold slime spawns (simple animal xenos are just sad)
added a FUN replacement in order to keep the RNG chances the same

### CODE REVIEW

**Comment by idontwannasignup** [comment]
Thank god, now those god damn memers will leave me alone.

**Comment by Fox-McCloud** [comment]
Don't care about the maid one, much.

:-1: 

This is literally giving ghosts (and Xenobio players themselves) the ability to have Fireball, blink, and Magic Missile. That's a bit much, IMO.

**Comment by Bawhoppen** [comment]
if they get sentience potioned I don't think they can actually use their abilities FYI

**Comment by Bawhoppen** [comment]
also did you forget magicarps are a thing

**Comment by Fox-McCloud** [comment]
I did not---and those are ..kinda bad, IMO and probably shouldn't be gold-core spawnable.

**Comment by Bawhoppen** [comment]
if you try to remove magicarps you will get crucified by every single science player ever

**Comment by Bawhoppen** [comment]
WJ YOU DO NOT DARE ADD THAT TAG OKAY SIMPLE ANIMAL XENOS ARE PATHETIC AND A DISGRACE TO XENOS BESIDES THIS IS EVEN BETTER NOW BECAUSE THERE ARE NOW WIZARDS TRYING TO MURDER THE SCIENTISTS

**Comment by LatD** [comment]
Xeno maid was always a weird one among the hostile gold mobs. It would fit better to the water-to-gold-slime mobs which just spawns friendly animals.

**Comment by GunHog** [comment]
Do not remove the maids, do what Lat says and move them to the friendly mobs list. You have zero justification for removing them entirely. The combat Xeno simple animals should be replaced, but the maid is just a harmless and cute one in a dress. We had a player one do her job and save Science from slaughter demon assaults.

**Comment by FantasticFwoosh** [comment]
Its a pity you didn't rip the magi-carp or even the chaos magi-carp code because wizards wearing dinky robes to indicate what they are casting with a variety of spells (red wizards fire etc) would have been a nicer change to see and a early warning to scientists and crew.

Also you're forgetting transference potions for easy fireball spam murderbone green-text and the fact this is a direct down-grade (assuming its a simple mob naturally rather than a hand using hybrid like drones) from a fireball magi-carp for not being space/at-mos immune.

**Comment by idontwannasignup** [comment]
Wait, transference potions? Is that what rainbow slimes do!?

HOLY FUCK WHY HAVEN'T I BEEN WORKING ON THAT ALL THIS TIME

**Comment by idontwannasignup** [comment]
Bawhoppen knows what he's talking about, if you remove the carps then what's the fucking point of Xeno. 
Adding wizards just makes it all that much harder in case you're unfortunate enough in having someone work with you in Xeno and watch as they open a slime pen while you're in the cage with 2 carps and a fuckin wizard. You're dead man! Dead!

**Comment by Incoming5643** [comment]
gold cores are never supposed to spawn human mobs

**Comment by Bawhoppen** [comment]
>implying wizards are humans

my reason for removing the xeno maid is they're not even a real xeno
simple animal xenos should not exist and are a disgrace to all of xenos

**Comment by KorPhaeron** [comment]
Stop trying to remove /tg/ culture and also add wizards to xenobio at the same time

**Comment by Bawhoppen** [comment]
what part of simple animal xenos being bad do you guys not understand

**Comment by kevinz000** [comment]
The part about it being bad

**Comment by GunHog** [comment]
> my reason for removing the xeno maid is they're not even a real xeno
simple animal xenos should not exist and are a disgrace to all of xenos

WJ and I both agree that the simple animal Xenos are indeed a disgrace, but... **the maid is an exception.** Unless we can have a proper xeno in a maid dress, she is fine as she easy.

**Comment by Bawhoppen** [comment]
unless we get snpc xenos I will not stand to let xenobio be able to make AI controlled xenos

**Comment by PKPenguin321** [comment]
>WJ and I both agree that the simple animal Xenos are indeed a disgrace, but... the maid is an exception. Unless we can have a proper xeno in a maid dress, she is fine as she easy.

oh come on you and i both know that wj is a degenerate xeno fetishist though

**Pull request closed without merging**
