### PR TITLE
Revert "Remove second copy of jQuery used only by IRV polls"

### PR DESCRIPTION
**Pull request by MrsTonedOne**
Reverts tgstation/tgstation#37944

This special version was to preserve ie8/linux compatibility for headmin elections

### CODE REVIEW

**Comment by optimumtact** [comment]
`Tested, works, IE8 too.`

**Comment by MrStonedOne** [comment]
ie8 is not officially supported in the newer version, ie8 is only officially supported in this verison. This is the last version to officially support ie8

**Comment by optimumtact** [comment]
`Tested, works, IE8 too.`

**Comment by SpaceManiac** [comment]
Just double-checked under Wine. Whether or not IE8 is officially supported, the ability to vote in IRV polls has not in fact broken.

image

**Comment by optimumtact** [comment]
@MrStonedOne is this a case of you putting your foot down for arbitrary reasons again or are you happy that the poll still works

**Comment by MrStonedOne** [comment]
Its a case of I want to double check for myself but my old laptop I use for ie8 testing is broken so I just need to get around to uninstalling ie11 so i can test

**Pull request closed without merging**
