### PR TITLE
Added a taser function back to the Advanced Energy Gun

### PR DESCRIPTION
**Pull request by GunHog**
Gives Advanced Energy Gun a taser mode.
- Like normal tasers, it can fire five shots before depleting the weapon.

Allows them to accept Seclites.
- It does not look any more wonky than the original sprites, so I do not see an issue in doing so.

Taser mode overlay sprites by @Steelpoint!

screenshot 2015-09-10 11 10 44

### CODE REVIEW

**Comment by Supermichael777** [comment]
what the hos gun is for also tasers are disgustingly strong with a lethal mode this was changed for a reason. :-1:

**Comment by Niknakflak** [comment]
Yea but advanced energy guns are rarely made and even more rarely given to security.  I don't see a problem with this.

**Comment by Steelpoint** [comment]
Yeah this seems fine. Gives a incentive for RnD to produce and make safe these weapons and issue them since they'll be more useful than overglorifyd Eguns.

**Comment by Durkel** [comment]
Eh, seems alright. I rarely ever see those things printed anyway and this might give them more life.

**Comment by SconesC** [comment]
I... They didn't already have this?

**Comment by Fox-McCloud** [comment]
A self-recharging gun that has tase and lethals on the same gun.

Yeah, I don't think this is a good idea, at all--especially with the likelihood that R&D reliability is going to get axed.

:-1:

**Comment by SconesC** [comment]
@Fox-McCloud You know this is what we USED to have, right? Prior to disablers becoming the norm.

**Comment by Fox-McCloud** [comment]
Yes, I'm more than aware of that; it was changed for a very specific reason; taze and lase is a lame tactic with little to no counterplay---made all the worse when you have a gun that self recharges.

Now that disablers are the norm and there's been an increased amount of counterplay, this is a major step backwards--especially now that it has taze, disable, AND lethal....it's even *more* powerful than it previously was, before disable became standard.

If this is going to return, at least drop the disable feature.

**Comment by Lumipharon** [comment]
disablers aren't the norm - it just means people always have tasers now instead of being able to rely purely on e-guns.

If reliability gets removed these become rather good, but I don't care either way to be honest.

**Comment by Cookiesndip** [comment]
> Oh no, a gun locked behind a ton of research, minerals, and firings pins have a stun AND laser function! OP OP OP!

Jesus christ.

**Comment by AlexCrimson** [comment]
These were rarely used because they were not reliable. Considering that mechanic is being removed, i dont think we need to buff these guns. Tasers were nerfed for a reason. These guns are really damn easy to make with R&D.

**Comment by PKPenguin321** [comment]
this is fine, we used to have it and it was never abused and probably still wont be abused because research wall and firing pins a shit. :+1:

**Comment by xxalpha** [comment]
It's supposed to be advanced.

:+1:

**Comment by Aloraydrel** [comment]
:+1:  Finally another reason to print out r&d stuff

**Comment by bustygoku** [comment]
More tase+lase, yaaaaaaaaaaaaaaaaaaaaaaaaaaaay.

**Comment by Core0verload** [comment]
:+1:

**Pull request merged**
