### PR TITLE
Sign restructure

### PR DESCRIPTION
**Pull request by ShizCalev**
Splits apart signs.dm into seperate files for plaques, maps / directions, warning signs, and department signs. Makes new paths to cut down the massive ass convoluted tree of everything. 

Corrected a couple missing periods and other grammar issues.

Also removed the old DreamStation map signs, since the map was removed well over a year ago.

### CODE REVIEW

**Comment by ShizCalev** [comment]
Turns 
image


into 
image
image

**Comment by optimumtact** [comment]
barsigns should load from config and we all know it

**Comment by WJohn** [comment]
cool

**Comment by Cyberboss** [comment]
Map diffs are inaccurate because of me

**Review by ninjanomnom — APPROVED** [review]

**Pull request merged**
