### PR TITLE
Revert "Port AI static to vis_contents"

### PR DESCRIPTION
**Pull request by optimumtact**
Reverts tgstation/tgstation#38644

This is badly broken, so this will be test merged until we can figure out how long the lag fixes to vis contents are going to take

### CODE REVIEW

**Comment by optimumtact** [comment]
https://imgur.com/a/MkS0Lt9 for some examples of the offset static and the AI seeing lavaland in all it's technicolour glory

**Comment by Cyberboss** [comment]
#38734

**Comment by SpaceManiac** [comment]
Alright, I was finally able to reproduce the "everything is visible" issue when I loaded on a full station rather than Runtime, it seems like a BYOND thing. The vis_contents are still on the turfs, and the image is still in `client.images`. VVing the image out of and back in to `client.images` did not help, but reconnecting did.

Further testing eventually crashed Dream Seeker so that's nice.

**Comment by Cyberboss** [comment]
Was this fixed in 1434?

**Comment by Cyprex** [comment]
It was fixed in 1432
http://www.byond.com/forum/?post=2379470

**Pull request closed without merging**
