### PR TITLE
Submission sigils are less effective

### PR DESCRIPTION
**Pull request by ghost**
Stun + convert trap is slightly bullshit especially since it's easily spammable.

Now submission sigils are brighter and take longer to convert. A fair trade since now they're basically cheap guvaxes instead of GG step and conv traps.

:cl: Adam
tweak: Submission sigils are brighter and take nine seconds instead of seven to convert.
/:cl:

### CODE REVIEW

**Comment by MimicFaux** [comment]
A fair balance. If you want to make an auto-converter in maint, use the more expensive sigil (that can also nab implanted)

**Comment by jughu** [comment]
Just make them darker pls

**Comment by ChangelingRain** [comment]
:canada:

**Comment by Supermichael777** [comment]
I have seen people use these as Free antag, auto-convert is BAD

**Comment by Shadowlight213** [comment]
Why make them both bright light AND longer to convert??
Why not one of the two? There's no reason for this at all.

**Comment by AdamElTablawy** [comment]
brightness-since they'll be no longer used as GG convert traps unless someone's autistic/looking for free antag it makes it easier for cultists to see and thus use to convert people with 

two-it removes the excuse of 'oh i thought the sigil was gone' when the stun trap wears off to eliminate hunting 4 antag 3000

**Comment by Shadowlight213** [comment]
Should add a sigil that damages people and converts their corpse into components for a fun metabreaker. You might be getting free antag if you step on that sigil. Or you might be getting gibbed!

**Comment by ChangelingRain** [comment]
:canada: 
there's a point here in that convert traps are a shitty thing but this doesn't actually fix it, as transgression sigils will still stun for long enough to convert aboooout half the time.
i'll do something about this and it'll involve Counterplay of some sort instead of just 'okay you walked wrong now you're being converted get fucked'

**Pull request closed without merging**
