### PR TITLE
Adds festive sugar cookie designs for holiday.

### PR DESCRIPTION
**Pull request by jaw-sh**
## About The Pull Request
Adds six new cookie icons which are picked at random for sugar cookies made during the Festive Season holiday event.

## Why It's Good For The Game
Sugar cookies are an important part of the holiday season.

image

## Changelog
:cl:
add: sugar cookies will now spawn with a random Christmas-themed icon during the Festive Season.
/:cl:

### CODE REVIEW

**Comment by Qustinnus** [comment]
Would you mind if I make a cookie cutter later and let you pick what kind of cookie you want?

**Comment by jaw-sh** [comment]
> Would you mind if I make a cookie cutter later and let you pick what kind of cookie you want?

Sure, that sounds like a good idea. You should be aware there are also some Halloween designs that'd be worth including and standardizing (they have their own class for both icons and are specifically crafted somehow).

**Comment by Qustinnus** [comment]
good call, will peek into that once I get there.

**Comment by tralezab** [comment]
I knew my man would pull through with the festivities fuck yeah

**Comment by jaw-sh** [comment]
> I knew my man would pull through with the festivities fuck yeah

I'll get the mail stuff done in the next few days, this has been a very busy month rip

**Comment by tralezab** [comment]
don't sweat it, take your time

**Comment by MrDoomBringer** [comment]
> imageadd: six new sugar cookie designs in food.dmi

Can probably remove this from the changelog, generally no need to mention it if it's not a player-facing change

**Review by Twaticus — APPROVED** [review]

**Comment by LemonInTheDark** [comment]
Fix your conflict and we should be good

**Comment by jaw-sh** [comment]
@LemonInTheDark Tested in-game. DMI automerger handled it.

**Comment by tgstation-server** [comment]
Your Fix/Feature pull request delta is currently below zero (-3). Maintainers may close future Feature/Tweak/Balance PRs. Fixing issues or helping to improve the codebase will raise this score.

**Pull request merged**
