### PR TITLE
Nerfs acid

### PR DESCRIPTION
**Pull request by Iamgoofball**
this shit is too good it needed a nerf i don't care about "muh metas" just use the even better stuff you have available

nothing should be able to go "1-click-lol-no-armor"

this goes well when mixed with #9894

### CODE REVIEW

**Comment by freerealestate** [comment]
thank fuck

are acid clouds still bullshit?

**Comment by Iamgoofball** [comment]
This makes them way less bullshit

**Comment by freerealestate** [comment]
great

**Comment by Lumipharon** [comment]
Honestly acid strength isn't even that much of an issue.

The real issue is how deadly it is with foam and smoke, due to the way it spams touch reactions 500 times.
Other then acid and mutagen, (and I guess the touch healing chems), nothing else really abuses the touch spam of smoke and foam.

**Comment by Cookiesndip** [comment]
Don't add this, it's a ridiculously shitty change that just adds more hugboxing. What the heck is even left in terms of medbay departmental weaponry? Slow-acting poisons? So you can run around with an ineffective and 50/50 looted syringe gun at roundstart and inject people with poisons that will bring you to crit in 15-20 seconds, more than enough time to run screaming (or, if with mutadone), to PDA the Captain/HoS. Can't spike cryo, because it's not like that won't totally be noticed the instant someone opens the interface to turn it on. So what is left goof? What is even left?

Do you even give a fuck about the thread you made yourself (https://tgstation13.org/phpBB/viewtopic.php?f=10&t=3802)? This reeks of reactionary nerfing (I was robusted by acid, pls nerf).

**Comment by Miauw62** [comment]
if you use hugbox unironically in the first sentence of your comment, it'll get deleted.

**Comment by Delimusca** [comment]
should make the reaction procs have a min volume so spraying someone with homeopathic levels of diluted acid doesn't do anything.

**Comment by optimumtact** [comment]
hugbox

**Comment by freerealestate** [comment]
rip 
u will be missed

**Pull request closed without merging**
