### PR TITLE
Makes the ORM give more sheets per level and makes stock parts prices rely more on miners getting ores

### PR DESCRIPTION
**Pull request by ma44**
:cl: ma44
tweak: The ORM now give 1 sheet per ore per upgrade
tweak: Stock parts prices are now much more reliant on mining getting some minerals. 
/:cl:

### CODE REVIEW

**Comment by GunHog** [comment]
This is probably going to get closed, just so you know.

**Comment by PKPenguin321** [comment]
Korrrr they're touching science agaiiin

**Comment by FantasticFwoosh** [comment]
It was nerfed with sort of good reason, this is just a veiled revert to the old system. 

And also stock part rebalances punishes other departments too hard. This isn't your best brainchild ma44

**Comment by GunHog** [comment]
Upgrading things are one of the things people love about Science. You should not be discouraging it, as I find it to be quite a good way to organize trade with other departments.

**Comment by ma44** [comment]
Rebalancing this stuff

**Pull request closed without merging**
