### PR TITLE
Revert "Automatic unbuckle by player moving"

### PR DESCRIPTION
**Pull request by ghost**
Reverts tgstation/tgstation#30239

I MEAN
COME FUCKING ON

THAT PR THAT JUST TOLD YOU WHAT TO DO WAS BETTER... ALMOST EVERYONE HATED THE AUTO UNBUCKLE PR

### CODE REVIEW

**Comment by Qustinnus** [comment]
T A C T I C A L     C H A I R S

**Review by Cyberboss — APPROVED** [review]

**Comment by alexkar598** [comment]
Who is the moron who merged that pr?which have most people against it rather than for it

**Comment by MoreRobustThanYou** [comment]
@alexkar598 blame @optimumtact

**Comment by Iamgoofball** [comment]
TACTICAL_CHAIRS

**Comment by alexkar598** [comment]
Make it so trying to move while buckled give you 1 brute damage since the chair buckle hits you

No don't do that

**Review by alexkar598 — APPROVED** [review]
The worthless stamp of approval

**Comment by ike709** [comment]
https://github.com/FTL13/FTL13/pull/2131 Defect to FTL13, we don't have automatic unbuckling.

**Comment by MrStonedOne** [comment]
@MrPerson watch this: https://www.youtube.com/watch?v=rcrdJD8whfE

Done, ok, now that you're back with us:

Here is how to fix the new player issue:

Turn it into a training opportunity.

Edit the alert icon to say "buckled" on the icon itself.

Add a message that says they are buckled when they try to move

Leave it at that.

Any player will naturally see the buckled message, see the buckled icon, and try to click it or at the least hover over it.

Engineering the situation so the player natively figures it out is much better than hand holding them. It feels more rewarding.

**Review by MrsTonedOne — APPROVED** [review]

**Comment by Grazyn** [comment]
I'm starting to think the coder who added auto unbuckling was actually a victim of tactical buckling. No other reason to persist so much against overwhelming negative feedback, especially when the other PR about the "you're buckled" message was objectively better and solved the issue anyway.

**Comment by Iamgoofball** [comment]
Tactical buckling doesn't exist

**Comment by ShadowDeath6** [comment]
how can you be a victim of tactical buckling when you're mashing the resist hotkey like you should be doing?

**Comment by PopNotes** [comment]
someone needs to glitter bomb oranges as hard as fucking possible for merging that PR

**Comment by PKPenguin321** [comment]
>Tactical buckling doesn't exist

You do not play

**Comment by Grazyn** [comment]
Tactical buckling isn't used in combat but before starting the attack. It's especially useful on the shuttle or in chaotic situations with a lot of text scrolling in the chat window. You quickly buckle your target and then go to town on them, it's the equivalent of making them skip their turn.

**Comment by Iamgoofball** [comment]
Yeah I'm going to throw a do_after and red bold text on buckling someone to a chair, that's dumb.

**Comment by nicbn** [comment]
Man if you merge this I'll make a revert pr so hard

**Comment by nicbn** [comment]
And I don't even care about it that much
I just want to spread the chaos seeds

**Comment by ExcessiveUseOfCobblestone** [comment]
If they panic [which most people do] you've effectively immobilized someone for at least a free few hits. It does exist, i've done it on numerous occassions.

**Pull request merged**
