### PR TITLE
[DNM/WIP] Projectile Dampening Fields for Peacekeeper Cyborgs

### PR DESCRIPTION
**Pull request by silicons**
Everything is still in #26893
Remade because I decided to switch branches before refactoring literally everything i've coded for this to use proximity checkers ={

### CODE REVIEW

**Comment by GunHog** [comment]
Lol Kev breaking things

**Comment by Repukan** [comment]
Lmao another broken quality Kev tm code

**Comment by kevinz000** [comment]
@Repukan they remembered we have prox checkers so i have to use that.

**Comment by kevinz000** [comment]
ok fuck this this is not going to work.

**Pull request closed without merging**
