### PR TITLE
Adds more Ethereal colors.

### PR DESCRIPTION
**Pull request by nianjiilical**
## About The Pull Request

image

Increases the number of ethereal colors from 8 to 18. I did this on a new monitor, so the colors might be off, but its its a one line change to add/remove them, so.

I did this and tested it locally but GitKraken is being a shit so here's a webedit.

## Why It's Good For The Game

image

## Changelog
:cl:
add: Some weird shit happened in space, and now Ethereals are appearing in new colors. Scientists are baffled.

/:cl:

### CODE REVIEW

**Comment by trollbreeder** [comment]
What if we did what lizards are already doing and tie ethereal colors to mutantcolor?

**Comment by LemonInTheDark** [comment]
Give me my color names back eeeeeeeeeeeeeeeeeeeeeeeeeer

**Comment by Michael-Ashfield** [comment]
I'm a bit worried the faint colours may make ethereals look dead or injured while they are full health.

**Comment by ATH1909** [comment]
> What if we did what lizards are already doing and tie ethereal colors to mutantcolor?

Would that make the spray tan OD change ethereal glow colors?

**Comment by trollbreeder** [comment]
> Would that make the spray tan OD change ethereal glow colors?

Currently, spray tan OD turns races with mutantcolor (lizards) orange. If ethereal color was refactored to mutantcolor, _yes, you would have orange ethereals._
That'd be a bit more consistent, too, and require less snowflake (depending on your definition of snowflake) with a predetermined color palette list.
But if you didn't want to do a refactor (due to lazyness or otherwise), you could set ethereal color to be a color input instead of a predetermined, pre-approved list.
Doing either of those two will help with being able to recognize specific ethereals at a glance.

**Comment by RaveRadbury** [comment]
@trollbreeder it sounds like you've thought this through, why not put your idea forward as an alternate PR? Get that contributor badge.

**Comment by trollbreeder** [comment]
@RaveRadbury I'm more of a theoreticals guy, which is why i'm suggesting instead of doing. Also i'm anxious that i'll accidentally delete the entirety of cargo or something like that while trying to PR my changes.

**Comment by Qustinnus** [comment]
No, mutcolor is a bad idea as there's too much colors I think are too over the top.

**Comment by Qustinnus** [comment]
This pr itself is really good though, the colors look nice.

**Pull request merged**
