### PR TITLE
Removes particles from Slimed and Slime Food status effects to fix fps lag in xenobio

### PR DESCRIPTION
**Pull request by Iamgoofball**
## About The Pull Request

Removes particles from Slimed and Slime Food status effects to fix fps lag in xenobio

## Why It's Good For The Game

Particles, when used in excessive density, lag the shit out of clients because BYOND. Xenobiology not only creates a lot of particles using both of these status effects, it also rapidly duplicates because of the design of xenobiology. Ergo, massive lag as xenobiology scales up in size over the round progression. This is bad for obvious reasons. Last PR got ignored by both keyholders and maintainers #86076 so I'm remaking it because letting an FPS fix stale out is incredibly bad.

Long-term for particles, because they're a dumpster fire from BYOND but we don't want to restrict people from using the feature, we should have a particle management subsystem that keeps track of particle density in an area using the cell system to automatically approve/deny creation of particles to avoid too high of clientside costs, and also automatically handling using shared holder particles in nullspace and adding to viscontents so we can use one particle everywhere it's needed without creating multiple

ccing @armhulenn cuz they're a particle gamer

## Changelog

:cl:
fix: Removes particles from Slimed and Slime Food status effects to fix fps lag in xenobio
/:cl:

### CODE REVIEW

**Comment by SmArtKar** [comment]
the bot does not translate pings into discord if you were wondering

**Comment by Iamgoofball** [comment]
@SmArtKar manually ping keyholders then thanks

**Comment by ninjanomnom** [comment]
You say it shouldn't have been staled out but you marked it as TM only and also put no description on it.

**Review by ninjanomnom — CHANGES_REQUESTED** [review]
I wouldn't be shocked at all if this is causing problems but it would be useful to have client profile examples while surrounded by slimes both with and without this change. Possibly can give it to lummox and get improvements in particles later or at the very least get an idea of the relative amount of lag created per particle.

**Comment by Time-Green** [comment]
A lot of lag is created by having different particle generators. I did some testinf a while ago and you could probably speed this up a lot by having only one particle generator and sharing that instance with everything else that needs those same effects. 

It can look a bit jarrin since particles would move identically, but you can also have like 2-3 instances and share those

I’m on phone rn but I made a PR a while back with lava particles that included a lot of these optimisations

**Comment by IndieanaJones** [comment]
I do agree with Goof this is a big issue though, the last couple times I've walked into xenobiology, my fps died from all the slimed monkeys. Definitely needs some form of solution, Time seems to have worked on something similar so perhaps it'd be good for a kickoff point to having particles for this that don't lag the game

**Comment by Ghommie** [comment]
> It can look a bit jarrin since particles would move identically, but you can also have like 2-3 instances and share those

You could have two or even three instances and it'd look less jarring without harming the client fps too much.

**Comment by Iamgoofball** [comment]
@Ghommie please merge

**Pull request merged**
