### PR TITLE
Makes cult items less of a vomit coaster

### PR DESCRIPTION
**Pull request by DaxDupont**
[Changelogs]: # (Your PR should contain a detailed changelog of notable changes, titled and categorized appropriately. This includes, new features, sprites, sounds, balance changes, admin tools, map edits, removals, big refactors, config changes, hosting changes and important fixes. An example changelog has been provided below for you to edit. If you need additional help, read https://github.com/tgstation/tgstation/wiki/Changelogs)

:cl: Dax Dupont
balance: Cult items will no longer be a long ride on the vomit coaster if picked up by a non cultist.
/:cl:

[why]: I picked up a cult sword while testing at centcom, and I nearly had to vomit from the dizzyness, not only is it extreme, it lasts ages.

We really shouldn't punish people for like 3 minutes for picking something up out of curiosity. Cult is miserable enough as is.

### CODE REVIEW

**Comment by Barhandar** [comment]
Pretty sure this happened because dizzy was fixed to function but the values, made expecting the old system (so it caused few seconds, not minutes), weren't changed.

**Comment by KorPhaeron** [comment]
Wondering if it should even do it at all on pickup, you cant just leave their shit all ovsr the place during arrests

**Comment by Barhandar** [comment]
>Wondering if it should even do it at all on pickup, you cant just leave their shit all ovsr the place during arrests

Pull into a locker, no?

**Comment by Iamgoofball** [comment]
@KorPhaeron people arrest cultists?

**Comment by Barhandar** [comment]
Just dragging works for one item, I was thinking of multiple.

**Comment by Rinoka** [comment]
meh, maybe put a small delay on it too? would let sec officers handle it cautiously, but punish them if they pick something up and get stunned or smth else

**Comment by SgtxRootbeer** [comment]
Allow them to hold one item, and stun them if they pick up another or try to use the item

**Comment by DaxDupont** [comment]
@Cyberboss mapdiff is trying to run for some reason and stuck

**Pull request merged**
