### PR TITLE
Adds departmental wardrobe vendors to all maps

### PR DESCRIPTION
**Pull request by 81Denton**
:cl: Denton
add: Departmental wardrobe vendors have been added to all maps.
spellcheck: Sorted cargo packs (wardrobe refills//alphabetically) and mining vendor items (by price), again.
/:cl:

This PR adds the departmental wardrobe vendors from #37859 to all maps, replacing the closets.

Everything else is essentially the same - in a bunch of spots I had to move air alarms/intercoms so they wouldn't be blocked by the vendor.
Whenever closets had extra items in them, I put them in nearby closets/on tables (stethoscopes, medical belts etc.). Extra winter jackets/satchels were removed, since they're included in the vendor anyway.

Also, I grouped the cargo refill packs and put them at the bottom of the toys/costumes section for better visibility.

### CODE REVIEW

**Comment by Firecage** [comment]
<3 Yes

**Comment by RandomMarine** [comment]
>in a bunch of spots I had to move air alarms/intercoms so they wouldn't be blocked by the vendor.

Wall-mounted objects are technically on the floor tile just ahead of them, so a vendor in that spot shouldn't even be blocking them at all.

**Comment by 81Denton** [comment]
Huh, that makes sense. It's probably better to not have anything behind them anyway, so players have an easier time finding the air alarm etc.

**Comment by DaxDupont** [comment]
also for repairs

**Review by SpaceManiac — CHANGES_REQUESTED** [review]
* Delta Bar vendor is blocking access to the corner table
* Vendor in Omega and Meta librarian's study is making the space more cramped than it ought to be, should be removed or moved somewhere else IMO

**Comment by 81Denton** [comment]
@SpaceManiac I moved the Delta vendor so it won't block the table anymore. For Meta/Omega, imo the best choice was making the private studies larger:
https://i.imgur.com/gvUY5lK.png
https://i.imgur.com/JNe7Xyk.png

**Review by SpaceManiac — APPROVED** [review]

**Pull request merged**
