### PR TITLE
Replaces ID cards with sniper rifles

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
People will now spawn with sniper rifles instead of ID cards. Sniper magazines have been increased to hold 50 rounds each in case people miss the doors they are trying to open. Sniper rifles now fit in your ID slot.

### CODE REVIEW

**Comment by zenek123321** [comment]
+ 1

**Comment by zenek123321** [comment]
+1 i support this

**Comment by Thunder12345** [comment]
I don't know whether to give this :+1: or :-1: so I gave both

:+1: for simplifying the door opening process

:-1: for the inevitable complaints about everyone having all access

**Comment by FantasticFwoosh** [comment]
:honk:

**Comment by Grazyn** [comment]
Should stop HoP powercreep, I say testmerge this

**Comment by Shapsy** [comment]
Do sniper rifles fit in PDA's?

**Comment by jughu** [comment]
Can i make additional magazines from the id computer?

**Comment by Chnkr** [comment]
👎  Sniper does not fit in my PDA.

**Comment by Thunder12345** [comment]
>👎 Sniper does not fit in my PDA.

FIX THIS NOW

**Comment by ShadowDeath6** [comment]
>Not making PDAs laser gatlin guns that can hold sniper rifles

It's like you're asking for people to complain about needing a buff.

**Comment by PKPenguin321** [comment]
This seems fair.

**Comment by Yoshmaster** [comment]
finally

**Comment by ExcessiveUseOfCobblestone** [comment]
Stolen shamelessly from that one lizard

**Comment by AdamElTablawy** [comment]
seems fine to me tbh

if everyone has a gun nobody can misbehave with them

that's why if you elect me president i will issue flamethrowers to every american

**Comment by FlavoredCactus** [comment]
Speedmerge it. Speedmerge it. Speedmerge it!!!!!!!!!

**Comment by Thunder12345** [comment]
In all seriousness this should at least be testmerged for a round to let everyone feel the pain of the syndicate scientists

**Comment by Grazyn** [comment]
There are still a few bugs to fix before this can be merged, the RD and CMO don't get the rifle and it doesn't hold 50 rounds anyway, you start with 5 and that's it. Not enough to guarantee the door-opening functionality

**Comment by Dorsisdwarf** [comment]
This has been testmerged the last 2 rounds.

Hell on fucking earth I'm being overrun.

No no no no no no no

**Comment by KorPhaeron** [comment]
@Dorsisdwarf 

Not a maintainer sorry

**Comment by AdamElTablawy** [comment]
@KorPhaeron this really isn't funny anymore

**Comment by KorPhaeron** [comment]
@AdamElTablawy 

Maybe people shouldn't test merge obvious joke PRs and run them into the ground

**Comment by AdamElTablawy** [comment]
who the fuck testmerged it then

**Comment by KorPhaeron** [comment]
Shadowlight

**Comment by MrStonedOne** [comment]
No train saw lasers

3/10

**Comment by Buggy123** [comment]
my greatest regret is missing this testmerge.

**Pull request closed without merging**
