### PR TITLE
Removes the clogged vents random event

### PR DESCRIPTION
**Pull request by Mothblocks**
## About The Pull Request
Removes the clogged vents, aka "backpressure surge" event. Preserves the beer nuke behavior, however.

## Why It's Good For The Game
This event doesn't work properly, at all.

On a local, you can see what the event is supposed to do. The foam disappears after about 5 seconds. 

In actual production servers, it lasts AGES. Today on Bagil, it lasted *ten and a half minutes*. I used a stopwatch.

During this **ten and a half minutes**, at the best of times getting anywhere is migraine inducing. At the worst of times, your department is destroyed by acid that was only meant to be there for 5 seconds.

Today, a head admin asked me if we could disable this event, and that they personally cancel it every time it comes up. I don't see a reason to keep code we're not going to maintain and that would otherwise be disabled by admins.

I don't think anyone is dying to keep this in. If you *really* are, then I invite you to not only reproduce the lag accurately on a local, but also optimize foam code, which to me is a complete headache.

The beer nuke is still going to have these same problems. It's still going to last ages, it's still going to lag like shit, but that's not a hill I'm going to die on. The beer nuke is funny.

## Changelog
:cl:
del: The scrubbers network no longer experiences backpressure surge. No ejection of contents will occur.
/:cl:

### CODE REVIEW

**Comment by optimumtact** [comment]
A lot of suppositions about the cause here but not much in the way of hard evidence, so I'm loathe to remove it.

**Comment by Maurukas** [comment]
You beat me to it. Armhulen said he wanted to grab data on it first, but I am in complete agreement that this event needs to die in a fire. Beer Nuke, at least, has to be deliberately triggered, and it requires a nuke code. 

This can come back when it's not a server destroying, agony inducing pile of lag.

**Comment by trerri** [comment]
Even if this event lasted five seconds I would still hate it as it completely ruins the station with decal spam that no janitor will ever feasibly clean and applies a bunch shitty effects to mobs.

**Comment by Jared-Fogle** [comment]
I have confirmed with oranges that he is now okay with this removal after profiling.

**Comment by Ziiro** [comment]
speed merge

**Comment by TheVekter** [comment]
Okay good, so I'm not the only one that hates these?

> Beer Nuke, at least, has to be deliberately triggered, and it requires a nuke code.

Last time I tried to set off the beer nuke on live, it didn't work. I had to manually trigger the beer flood event.

**Comment by Jared-Fogle** [comment]
I've seen the beer nuke work consistently on Bagil.

**Comment by msgerbs** [comment]
Today we had some sort of fire (CLF3?) foam come out from this event and make virology complete cut off from the rest of the station for a good 5+ minutes while this even slowly ran its course. I think this even theory from a flavor standpoint but I think it makes more sense to limit it to one or several areas rather than the entire damn station where you just cross your fingers and hope you're somewhere that gets something harmless like cleaning foam and not acid or CLF3.

**Pull request merged**
