### PR TITLE
Fixes Bitrunner lacking job-based bounties

### LINKED ISSUE #84283: Bitrunner cargo bounties seem to be fully random/not tied to job
Reporting client version: 515.1637

## Issue Summary
When getting a bounty target as a bitrunner, it seems to generate choices from ALL possible bounties across all jobs, leaving you with few choices you can actually get.

## Round ID:
231040

## Testmerges:
- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)
- [Cult Vs. Heretic: 7 Months Later Edition](https://www.github.com/tgstation/tgstation/pull/82877)
- [Moves tool use back higher in the chain, but makes it so tool acts are only called on non-combat-mode](https://www.github.com/tgstation/tgstation/pull/84083)
- [Bitrunning: Combat domain](https://www.github.com/tgstation/tgstation/pull/84196)

## Reproduction:
Be a gamer
Get a bounty to sell a canister of BZ
Cry

Screenshot 2024-06-23 212446

### PR DESCRIPTION
**Pull request by TheVekter**
## About The Pull Request

Fixes #84283 by just adding actual bounties for Bitrunner, giving them something more interesting to do than random bounties for jobs they don't have access to. These bounties revolve around optionally turning in the special rewards from each of the bitrunning domains (a bike horn, the abductor plush, beach ball, etc) for a credit reward. I considered the idea of making each one drop a specific bounty chit that you turned in for a reward, but at that point it's just "paying you per domain" and I'm not sure how that would balance with economy.

This is more just meant to be a framework for others to add things that might be a little more interesting.

This also adds a special drop from the Pizzeria domain because I thought it was funny.
## Why It's Good For The Game

Bitrunners should have bounties they can actually reasonably complete.
## Changelog
:cl: Vekter
add: Bitrunners can now access specific bounties asking for the item rewards from specific bitrunning domains.
fix: Fixed bitrunner pulling from a pool of literally every bounty available.
/:cl:

### CODE REVIEW

**Comment by MrMelbert** [comment]
Very clever bounties, I like

**Comment by OuroborusReporter** [comment]
Blessed PR, now I can tell the QM to stop yelling at me for not helping cargo while going for the Five Nights at Ian's speedrun WR

**Comment by TheVekter** [comment]
> Blessed PR, now I can tell the QM to stop yelling at me for not helping cargo while going for the Five Nights at Ian's speedrun WR

There's a little something fun in this one for you, then.

**Comment by DaCoolBoss** [comment]
Beach ball is abusable, can stockpile beachballs for 50 credit each (can be as low as 20 credits with right coupon + station trait) from cargo goodies section.

**Comment by TheVekter** [comment]
> Beach ball is abusable, can stockpile beachballs for 50 credit each (can be as low as 20 credits with right coupon + station trait) from cargo goodies section.

Good point. I've removed that one.

**Pull request merged**
