### PR TITLE
Fixes monkey stealing items with hands full.

### LINKED ISSUE #37645: Having your PDA snatched by a monkey makes it invisible
Round ID: 87370 (Bagil)

(If you put round ID in square brackets you can't see what's written there. is that intentional?)

While playing as a bartender, I held my PDA in my hand, and Pun Pun decided to snatch it.
...but the PDA didn't go to Pun Pun's hands.
And it wasn't on the floor.
It was invisible.

Naturally, I assumed it was lost.
But no, it became part of me. I could receive and reply to messages, just could not see the PDA itself and access its interface.

The first time this happened, I asked an admin to have all my items dropped. It reappeared then.

But the second time it did, I took off my jumpsuit myself. Then put it on. It did NOT appear back.
And when an admin tried to drop all my items, it did not appear either. It was a part of me.

Amazing.

[Reproduction]: Have Pun-Pun or any other monkey snatch your PDA while it's in your hand.

To get confirmation of it becoming part of you, ask someone to PDA you.

### PR DESCRIPTION
**Pull request by AnturK**
Fixes #37645

Never tried to move the item if it failed to equip on the monkey.

### CODE REVIEW

**Comment by SouDescolado** [comment]
There is a problem is that it can succeed the `M.temporarilyRemoveItemFromInventory(pickupTarget) ` check and fail the `!QDELETED(pickupTarget)` inside the IF. The temp-remove should not be used this way. Same happens with plasmeme goes to gulag via teleporter. Check #42859

**Comment by AnturK** [comment]
That check is mostly redundant here, if it's already in gc queue then it should already be in nullspace and will (hopefully) be deleted after this ref clears. Otherwise it's in invalid state.

**Comment by SouDescolado** [comment]
Got it

**Comment by AnturK** [comment]
I'll remove it in a moment, there's really no need for it here.

**Comment by ShizCalev** [comment]
Why doesn't temporarilyRemoveItemFromInventory check for gc queuing?

**Comment by AnturK** [comment]
doUnequip in general doesn't check the item state and just cleans inventory side stuff. Some additional sanity but that would change a lot of non-obvious interactions and i'd rather not do in this PR without testing.

**Review by Cyberboss — APPROVED** [review]

**Pull request merged**
