### PR TITLE
Revert "Removes umbras"

### PR DESCRIPTION
**Pull request by optimumtact**
Reverts tgstation/tgstation#18755

This broke master

### CODE REVIEW

**Comment by kilkun** [comment]
rest in peperone

**Comment by Xhuis** [comment]
eh? How'd it break it?

**Comment by optimumtact** [comment]
Compile error, for some reason I didn't spot your pr didn't have travis

https://travis-ci.org/tgstation/tgstation/builds/139322397

**Comment by Xhuis** [comment]
Damn, all right. #18819 is the replacement.

**Pull request merged**
