### PR TITLE
Reduce volume of shipambience

### PR DESCRIPTION
**Pull request by grungussuss**
## About The Pull Request
Reduced the volume of the shipambience that plays at all times in powered rooms by 20 decibells
<details>
<summary>Comparisons</summary>
<br>
### Old:

https://github.com/user-attachments/assets/56987f28-2965-4628-bf7f-d43f7b77b362

### New:

https://github.com/user-attachments/assets/274aadb6-4464-4f64-a4da-60b26bf73c19

</details>

## Why It's Good For The Game
Ambience should be in the background, when power gets turned off it becomes really apparent how loud this ambience is, because it's a loop and can be heard by all players at almost all times, reducing the volume of it should help with how extremely distracting it is.
## Changelog
:cl:
sound: generic ship ambience volume has been reduced
/:cl:

### CODE REVIEW

**Comment by Ghommie** [comment]
I agree it should be reduced, but isn't this perhaps a little too much?

**Comment by Sadboysuss** [comment]
> I agree it should be reduced, but isn't this perhaps a little too much?

I can make it -10 or -15 decibells, you choose

**Comment by Ghommie** [comment]
Uuuh, -10?

**Comment by Sadboysuss** [comment]
done

**Comment by YakumoChen** [comment]
I literally can't hear it in the second video with over-ear headphones and reasonable volume

**Comment by Sadboysuss** [comment]
> I literally can't hear it in the second video with over-ear headphones and reasonable volume

video isn't updated

**Pull request merged**
