### PR TITLE
Removes some obsolete chems

### PR DESCRIPTION
**Pull request by Iamgoofball**
>do goonchem
>remove trekchems due to being made obsolete by goonchems, people whine and bitch because a new layer of complexity was added
>they get pissy and add it back again
>try to use the re-added trekchems to argue the goonchems are obsolete better remove them all 2 years later

fuck you assholes i see your long con, get fucked 

Love,
Goofball

### CODE REVIEW

**Comment by WJohn** [comment]
wew

**Comment by kevinz000** [comment]
Fuck off goofball :^)

**Comment by Nabski89** [comment]
If you want to look serious, at least fix the sleepers.

**Comment by ChangelingRain** [comment]
reason number one reagent ids are a bad idea: this pr compiles

**Comment by Iamgoofball** [comment]
@ChangelingRain 
I just removed the recipe, it's fine.

**Comment by uraniummeltdown** [comment]
paradise's sleepers use goofchems, could change it to those

**Comment by calzilla1** [comment]
NO

**Comment by XDTM** [comment]
they're really handy for when you only have a chem dispenser to work with

**Comment by ShadowDeath6** [comment]
Antitoxin was pretty nice tbh since it let you treat toxins damage without purging chems

**Comment by ExcessiveUseOfCobblestone** [comment]
the goofchems are objectively better so yeah 👍

**Comment by PKPenguin321** [comment]
What prompted this?

**Comment by Niknakflak** [comment]
NO

Leave them alone.

**Comment by SgtxRootbeer** [comment]
If you do this, add soymilk to the bartender's drink dispenser

**Comment by ExcessiveUseOfCobblestone** [comment]
w-w-what

**Comment by Armhulen** [comment]
fucking DO IT

**Comment by AdamElTablawy** [comment]
I am in approval of this 👍

**Comment by Iamgoofball** [comment]
@SgtxRootbeer I thought we got rid of you retards who only heal with bar drinks ages ago.

@ExcessiveUseOfCobblestone back when goonchem was first ported annd the trekchems removed, people would in protest destroy chemistry roundstart and heal only using tomato/lime juice and milk

**Comment by ExcessiveUseOfCobblestone** [comment]
@Iamgoofball For once I feel bad for the goofball, I understand why he's insane now

**Comment by SgtxRootbeer** [comment]
@iamgoofball
You realize that asking a chemist for anything more complicated than a beaker of sulphuric acid is too much for 90% of chemists, right?
Using the bar isn't done in protest, but out of necessity.

**Comment by ExcessiveUseOfCobblestone** [comment]
I hope you're joking

**Comment by Niknakflak** [comment]
<NikNak> I like how you said "removes obsolete chems" instead of "removes trek chems" to avoid more negative publicity Iamgoofball 
<NikNak> that's manipulative and shitty
<Iamgoofball> they're obsolete though?
<Iamgoofball> what's manipulative here
<Iamgoofball> they were made obsolete by the goonchems
<Iamgoofball> just ask WJohnston he coined the term obsolete here
<NikNak> if people use them more/just as much, they aren't obselete
<Iamgoofball> too bad
<NikNak> V(._.)V this is why you lose headmin
<Iamgoofball> i get things done
<NikNak> I mean
<NikNak> not really anymore than people who aren't you

**Comment by ExcessiveUseOfCobblestone** [comment]
are people actually making these? Stypic and SS are Better by far

**Comment by SgtxRootbeer** [comment]
in science, i usually use those to heal myself after purging greyshits from rnd. its easy if all you got is a portable chem dispenser.

**Comment by Niknakflak** [comment]
Here's the data https://atlantaned.space/newSS13tools/stats/singleStat.php?stat=chemical_reaction
syptic powder is made more than most everything but tricordazine is made more than silver_sulfadiazine with the other trek chems still being made pretty often

**Comment by ShadowDeath6** [comment]
I only see these used in sleepers and medborgs and when chemists make their autism hyper unkillable patches that heal every form of damage by 5 every tick

**Comment by Niknakflak** [comment]
This data is only chemical reactions so it doesn't take sleepers into account I don't think and most trek chems are still made quite a bit over goon chems

**Comment by ExcessiveUseOfCobblestone** [comment]
> https://atlantaned.space/newSS13tools/stats/singleStat.php?stat=chemical_reaction

i'm [unjokingly] convinced! didn't even know this existed tbh

**Comment by XDTM** [comment]
I use trekchems a lot as a non-chemist; additionally, basic goofchems can only be used via patch, which following a recent nerf has a fairly long delay, and thus leaves no option for healing in pill form besides trekchems. So you can use the brute patch for both instant and over time healing, or the brute pill to heal less but without having to stand still. They're hardly obsolete and are instead healing chems that have a different use.

**Comment by XDTM** [comment]
Also i don't think there's an actual threat of goofchems being removed, i think they offer separate benefits and drawbacks, which is nice as it gives chemists a little bit of choice instead of having to go with an objectively best chem.

**Comment by PKPenguin321** [comment]
These chems being in game don't equate to goofchem being removed if that's what you're concerned with, goof

**Comment by AnonymousNow** [comment]
After chemistry was broken and painstakingly rebuilt by different coders, we managed to get a nice state of equilibrium with our current chemicals. I don't like the direction this is taking.

**Comment by RandomMarine** [comment]
So, why don't people make trekchems?

**Bicaridine**
One 29u pill heals 146 brute over more than two minutes.
Overdoses over 30u

**Styptic Powder**
One 40u patch heals 40 brute instantly, and then 200 brute over time.
Doesn't overdose.

Hmm, almost seems like it's a balance issue.

**Comment by Niknakflak** [comment]
Did you read the stats

**Comment by lordpidey** [comment]
One of the hilarious side effects of trekchem usage is trying to sleeper someone who has anti-tox in them.

If you aren't paying attention, you might mix tricord in them, and set them over the OD limit.

**Comment by XDTM** [comment]
Bicar is also much quicker to make if you need healing very fast, instead of having to fiddle with the chem-master (if you even have one available). You can just drink it from the beaker! For those benefits, you get a few drawbacks, it makes sense.

**Comment by RandomMarine** [comment]
@xdtm You know you can just splash a beaker of styptic over yourself if you're ever in that situation?

**Comment by XDTM** [comment]
It only gives the instant healing, making it worse in the long run. Silver sulf is also more complicated to make, requiring ammonia, than kelo.

**Comment by Iamgoofball** [comment]
Why would I undermine the harder chemistry with higher rewards to add easymode chems like bicard and tricord?

**Comment by XDTM** [comment]
How are you undermining it? They're far more used even with trekchems.

**Comment by RandomMarine** [comment]
>Harder

>Four clicks instead of three

**Comment by XDTM** [comment]
It also leaves annoying byproduct, and it's some more clicks than that since ammonia is H3N, not in the basic chems.

**Comment by Iamgoofball** [comment]
>only usable effectively by patches

**Comment by XDTM** [comment]
>They're far more used even with trekchems.

**Comment by RandomMarine** [comment]
Patches are pretty much functionally equivalent to pills except
-10 reagent volume
-delay on self-use
+++++++++++++++++NOT RESTRICTED ON WHAT THE RECIPIENT IS WEARING

**Comment by XDTM** [comment]
I feel like the current state of things is great: goofchems are superior in 90% of the cases, offering vastly superior healing and lack of overdose, but it can only be made with a chem master (so Chemistry or a very dedicated RnD). People with only a chem dispensers have to rely on the less efficient treckchems, but aren't completely cut off from healing chems. And trekchems still have a small niche in Chemistry due to them being able to be consumed instantly in pill form, making goofpatches not an absolute 100% pick.

**Comment by Iamgoofball** [comment]
Then why are people telling me goonchems are obsolete to trekchems?

**Comment by Iamgoofball** [comment]
Also the patch nerfs were dumb

**Comment by PKPenguin321** [comment]
They're wrong is why

**Comment by PKPenguin321** [comment]
>goofchem added to get rid of easy mode trekchem healing
>could have just given trek chems an OD but whatever
>goofchems turn it to be even easier mode healing (instant, higher dosage, more of it, etc)
>trek chems are given tiny OD so they just kill you half the time and are a mockery of their old selves
>try to remove trek chems again anyways because they're somehow still too good

??????????????

**Comment by optimumtact** [comment]
bye bye trek chems

**Comment by RandomMarine** [comment]
Rebalance. Don't remove.

**Comment by TechnoAlchemisto** [comment]
Hehe

**Comment by Arianya** [comment]
Why do patches go through any clothing anyway, it makes no sense.

**Comment by RandomMarine** [comment]
@Arianya It was mostly because of pre-lavaland mining. It was lame to take pressure damage to take a pill or apply a patch.

Nowadays? Is there really much of a point beyond general quality of life?

**Comment by SgtxRootbeer** [comment]
@arianya
It explains why they take time to apply, your unbuckling your pants/lifting shirts and whatnot to apply the patch underneath clothing.

**Comment by Arianya** [comment]
@SgtxRootbeer Except that if you apply a cyanide patch to someone else its instant and penetrates all clothing

**Comment by ShadowDeath6** [comment]
>slip nuke op
put a patch on him through his heavily armored suit

**Comment by RandomMarine** [comment]
It's not instant. It's the same delay as forcing pills on somebody. Difference is you don't need to strip anything first.

**Comment by AdamElTablawy** [comment]
stypic and silver sulpha patch delay is a joke anyway since any competent chemist will in a fight just splash a beaker of it on themselves for that sweet 100 heal of whatever damage you wanted and run around hopped up on atropine 

mostly i just want trek chems gone because they're shit and it pisses me off when chemists make them thinking they're good instead of making the actual good chems useful for healing

**Comment by Doppeltongue** [comment]
Why remove chems that do something different and allow for an alternative choice?

**Comment by RandomMarine** [comment]
Because apparently some people are saying trekchems are better?

And this somehow justifies removing them?????

**Comment by Arianya** [comment]
I believe the actual answer is "goof is paranoid and thinks that removing all competition will make goofchem unassailable"

**Comment by AdamElTablawy** [comment]
i believe the actual answer is he's trolling and you're taking the bait

**Comment by Steelpoint** [comment]
Eh, this is removing variety any choice from chemist players. I don't see the huge balance implication of having trekchem and goonchem chemicals available.

**Comment by ShadowDeath6** [comment]
it gives you more healing per second if you stack chems but that's the most powerful it can get

**Comment by optimumtact** [comment]
bye bye trek chems

**Comment by Cheridan** [comment]
Please add a short description of why you think these changes would benefit the game.

**Comment by Arianya** [comment]
He also forgot a changelog for a change that definitely affects players.

**Comment by optimumtact** [comment]
Good to see this sensible and wise change attracting positive discussion.

**Comment by Arianya** [comment]
@optimumtact you forgot to remove the original post by goof if you only want positive discussion 😄

**Comment by Niknakflak** [comment]
Seems unpopular

**Comment by Buggy123** [comment]
I have nothing against you goof but I dislike goon chems and want trekchems back 👎

**Comment by AnonymousNow** [comment]
I was one of the most vocal opponents of Goofchem, and my predictions ended up being right; but after it was fixed, months on, it reached a good equilibrium. Removing Trekchems would disrupt that balance - I cannot approve.

**Comment by Arianya** [comment]
61 comments use to live here. Now it's a ghost town.

Hmm, I wonder what happened here?

**Comment by optimumtact** [comment]
What kind of a name is Soap anyway

**Comment by ChangelingRain** [comment]
>close niknak pr

**Pull request closed without merging**
