### PR TITLE
Jukebox resprite

### PR DESCRIPTION
**Pull request by Kmc2000**
## About The Pull Request

Simple sprite fix-up for the jukebox, making it 3/4 and a bit more lively.

## Why It's Good For The Game

Demo:
https://file.house/QcT6.mp4

Current:

Proposed resprite:

## Changelog
:cl: Kmc2000
imageadd: Jukebox resprited so it's nicer to look at.
/:cl:

### CODE REVIEW

**Comment by optimumtact** [comment]
in b4 ten thousand comments and culture arguments about soul

**Comment by tralezab** [comment]
should be merged regardless of any arguments because this version has no black outline plain and simple as that

**Comment by WJohn** [comment]
hmm. i dunno, this needs work. quite a lot of work. i think you could go for some more vivid wood colors, some more distinct details. this looks messier than the previous one.

**Comment by Tlaltecuhtli** [comment]
are jukebox even in the map

**Comment by Dorsisdwarf** [comment]
I agree with WJ, replacing an old style sprite with a new style sprite should actually require a better sprite not an equally shitty one, or what's the point?

**Comment by Kmc2000** [comment]
I don't see how this is equally shitty at all.

**Comment by anconfuzedrock** [comment]
I think this new sprite looks shitty but in the same shitty way sprites like the mech charger look, this fits the game better in my eyes. it's less jarring a transition. ugly machinery tends to be glossed over by the eyes, while jarring machinery attracts attention to how out of place it is.

**Comment by optimumtact** [comment]
Jukeboxes aren't mapped anywhere due to their massive lag inducing tendencies

**Comment by FloranOtten** [comment]
I prefer the old one, to be honest. Why replace a sprite if the replacement is shit, too?

**Comment by optimumtact** [comment]
@Kmc2000 can you show the sprite in game?

**Comment by Kmc2000** [comment]
@optimumtact
https://file.house/QcT6.mp4

**Comment by optimumtact** [comment]
looks okay to me

**Comment by dee-dubya** [comment]
The new one doesn't look bad in game, although I'd like to see the old one in game to compare it to. From the sprites alone, the old one looks a lot better imo.

**Comment by ExcessiveUseOfCobblestone** [comment]
Grey Plating and Wood Flooring pls

**Comment by actioninja** [comment]
conflict

**Pull request closed without merging**
