### PR TITLE
Clockwork floors now only heal toxin damage on servants of Ratvar

### PR DESCRIPTION
**Pull request by ChangelingRain**
:cl: Joan
rscdel: Clockwork floors now only heal toxin damage on servants of Ratvar.
/:cl:

It's slightly more healing but it's only toxin damage. Synergy with Sentinel's Compromise.

### CODE REVIEW

**Comment by AdamElTablawy** [comment]
cultists can build all-heal structures for themselves.

perhaps mending motors should heal clock cultists in ratvar gear as well to compensate for nerfing floors to heal for the most uncommon damage type next to clone?

**Comment by GunHog** [comment]
I do not see why I would bother wasting my alloy on flooring now, except to make it look cooler. Toxin, like Adam says, is an uncommon damage type, and after this will only serve as decoration.

**Comment by InsaneHyena** [comment]
It's intended to work in combination with sentinel's compromise that heals your brute/burn and deals toxic damage to you, Gun Hog.

**Comment by coiax** [comment]
Cultist pylons require plasteel, don't heal toxin damage, and giving servants free unlimited healing renders all the other forms of healing pointless

**Comment by coiax** [comment]
Joan, how will this interact with Incoming's "invert toxin damage to slimepeople" change

**Comment by ChangelingRain** [comment]
It will probably just literally kill them

**Comment by ChangelingRain** [comment]
Update it will no longer murder slimepeople relentlessly

**Pull request merged**
