### PR TITLE
[DNM] Adds the ability to toggle run/walk with a hotkey

### PR DESCRIPTION
**Pull request by freerealestate**
**Edit:** So turns out Ctrl+V can't be used as a hotkey because it'll fuck up pasting, so don't merge this until I find a new key. Suggestions welcome. It's hard finding available keys that don't feel like Twister to use.

Took me a couple of hours to figure out how to do this (run/walk didn't have its own verb to assign a hotkey to). Not sure if I've done it right, so please critique the code if I've made a mistake. Tested it thoroughly with all mobs capable of toggling walk. Haven't had any runtimes or noticed other bugs.

Idea from this thread: https://tgstation13.org/phpBB/viewtopic.php?f=9&t=4156

I originally tried it with holding shift to walk, but the button presses/releases don't always register so you'd sometimes end up walking by default and having to hold shift to run, which required clicking the button manually to fix, which was annoying.

### CODE REVIEW

**Comment by Chocobro** [comment]
but what about shift-Lclick examining? does this remove that? because that was extremely useful.

**Comment by freerealestate** [comment]
Nope, it doesn't. However, this'll interfere with that. I'll have to pick a different key. Thanks for mentioning that.

**Comment by RemieRichards** [comment]
@freerealestate you don't have to close the PR to swap the key over.

**Comment by freerealestate** [comment]
'kay.

**Comment by Jordie0608** [comment]
Ctrl is also used, for pulling.

**Comment by Iamgoofball** [comment]
and alt is used for alt-click

why do we need a hotkey for run/walk? you hardly need to switch

**Comment by freerealestate** [comment]
Because you encounter puddles quite often and this makes it easier to avoid them. What's your problem with it?

Anyone have any suggestions on what keys aren't taken?

**Comment by Iamgoofball** [comment]
maybe add a pref. toggle to enable/disable the hotkey?

**Comment by WJohn** [comment]
Is it possible to make it walk only while HOLDING shift? It'd be much better than a toggle, and it's fairly intuitive.

**Comment by MrStonedOne** [comment]
You can do combo hotkeys

like control+shift (ais/borgs use this for toggle access override on airlocks)

**Comment by freerealestate** [comment]
I was thinking about that. I thought it might be a pain though. Seems to be
the easiest solution, at least for non-hotkey players. I think I'll just do
V for hotkey players.

**Comment by freerealestate** [comment]
So I tested it again with shift but the problems mentioned in the OP were still present. Decided on V due to its reachability when using WASD, and Pause because it was the nearest usable key for those who use the arrow keys.

**Comment by optimumtact** [comment]
:+1: v-tech just kicked in yo

**Comment by Killbasa** [comment]
I don't see the point of this. A hotkey for  essentially just when the janitor is mopping? Really?

**Comment by Cheridan** [comment]
Killbasa that's an an argument against Walk/Run in general, but if we're going to have it then we might as well make it user-friendly

**Comment by optimumtact** [comment]
Hotkeys rock

**Pull request closed without merging**
