### PR TITLE
Fixes lots of map issues on box TAKE 2

### LINKED ISSUE #6495: Blastdoor of atmospherics desk appears behind table on box
Blastdoor of atmospherics desk appears behind table on box instead of in front of it, so you don't see it and get confused at why you can't get on the table.

### LINKED ISSUE #6659: [Map Feature Request] Body Bags in Sec's Execution Chamber
I would like to see a couple body bags close to the Execution Chamber. Because after people have been executed, I'd rather not have to drag their corpses around without a body bag.

### LINKED ISSUE #6819: [MAP] Turbine vent monitor isn't connected to any cameras
Used to watch the turbine vent.
Shows a list with cancel being the only option.

### LINKED ISSUE #6941: Camera consoles in science don't work
The grey camera consoles in science,Research monitors I think, Don't seem to be working.

### LINKED ISSUE #7093: Turbine vent monitor without cameras
In the (new) incinerator there is the turbine, and a "turbine vent monitor" on the wall. (like the toxins launch monitor)
But there are no cameras around the turbine.
I suppose this is a mapping issue.

### LINKED ISSUE #7110: Mapping Error: Gateway Shutters Control
Pretty sure the required access on the shutters control button is incorrectly set; it's currently set for "cargo" access of all things. Shouldn't this be gateway or even RD level access? Cargo makes literally no sense.

### PR DESCRIPTION
**Pull request by WJohn**
Now with fewer merge conflicts!

Changes execution chamber and AI sat a bit to be much prettier.
New execution chamber:
http://i.imgur.com/cpYgAY2.png
New AI sat:
http://i.imgur.com/hzPAhMk.png

Fixes #7110
Fixes #7093
Fixes #6941
Fixes #6819
Fixes #6659
Fixes #6495

### CODE REVIEW

**Comment by Menshin** [comment]
:+1:

**Comment by WJohn** [comment]
Apparently tcomms vents and scrubbers were never connected to the station, this fixes that.

**Comment by Ikarrus** [comment]
>Changes execution chamber and AI sat a bit to be much prettier.

Much more cluttered with visual noise, you mean. I don't like these changes.

**Comment by WJohn** [comment]
It's really not terribly cluttered, almost all of this stuff is always hidden under the floor.

**Comment by Ikarrus** [comment]
Don't use dark tiles so much. They blend in with the walls.

If you changed the shade of the tiles it wouldn't be so bad.

**Comment by WJohn** [comment]
MERGE CONFLICTS THIS WILL RETURN AGAIN

**Pull request closed without merging**
