### PR TITLE
[READY]Makes the reactive tesla armor actually shoot out lightning

### PR DESCRIPTION
**Pull request by silicons**
This actually makes it less effective on groups than before as before you could instacrit the shuttle with it!
Also this is adminspawn anyways.

### CODE REVIEW

**Comment by Cheridan** [comment]
>Also this is adminspawn anyways.

you know as well as anyone that everything adminspawn only becomes obtainable eventually :P

**Comment by jughu** [comment]
This could be a fun defensive traitor item if balanced tbh

**Comment by Kromgar** [comment]
@Cheridan The veil render is obtainable?

**Comment by kevinz000** [comment]
@Cheridan don't worry no one in their right mind will ever let me merge something to give science this.
:^)

**Comment by KorPhaeron** [comment]
Doesn't this make it stun?

**Comment by kevinz000** [comment]
I'll take that out but iirc Tesla engine didn't stun me last time I got hit?

**Comment by kevinz000** [comment]
stun removed btw.

**Pull request merged**
