### PR TITLE
Removes Grab from photocopier

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
You can still copy asses with click+drag

### CODE REVIEW

**Comment by PKPenguin321** [comment]
b a d    o m e n s

**Comment by Fox-McCloud** [comment]
why?

**Comment by KorPhaeron** [comment]
@Fox-McCloud 

Grab must die

**Comment by Fox-McCloud** [comment]
Any particular logical or technical reason for this other than "it must die" without any rational explanation?

**Comment by PKPenguin321** [comment]
No
That's why is a cancerous campaign which I detest

**Comment by Jalleo** [comment]
What can be done though is remove it all so then we can have only three states of intent which will simplify the hci.

**Comment by Iamgoofball** [comment]
@Fox-McCloud Grab code is by far some of the snowflakiest, shitty, barely working as intended code we've ever had, right up there with ninja code. Pull does everything it did, but better.

**Comment by Fox-McCloud** [comment]
Not...really---there's strangling, dragging multiple people at once, tabling, etc.

**Pull request merged**
