### PR TITLE
Adds apc outages and slips to the blackbox

### PR DESCRIPTION
**Pull request by Lett1**
Like the title says, apc power alerts and slips are now tracked in the blackbox.

For power outages, the area and timestamp is recorded:
`{"data":{"1":{"area":"The area power controller","time":"2019-05-01 19:52:52:9"}}}`
For slips, the object that slipped and a count of how often it did is recorded:
`{"data":{"/obj/item/grown/bananapeel":1,"/turf/open/floor/plasteel":1,"/obj/item/pda/clown":1}}`

### CODE REVIEW

**Comment by ATH1909** [comment]
With this PR merged, will those automatic slipping devices (the ones with conveyor belts and such) spam the blackbox with slipping logs if there are people in them? Maybe slips against dead and/or catatonic people shouldn't be logged?

**Comment by Lett1** [comment]
> With this PR merged, will those automatic slipping devices (the ones with conveyor belts and such) spam the blackbox with slipping logs if there are people in them? Maybe slips against dead and/or catatonic people shouldn't be logged?

The logging action is done in the slippery component, if it uses that it will get logged.

**Comment by nfreader** [comment]
I'm moderately concerned about slips spamming the feedback log and making it balloon in size but I trust what you're telling us.

**Comment by Lett1** [comment]
> I'm moderately concerned about slips spamming the feedback log and making it balloon in size but I trust what you're telling us.

We can always just testmerge it and see how it goes.

**Comment by optimumtact** [comment]
can you explain why you feel it's necessary to record slips?

**Comment by Lett1** [comment]
> can you explain why you feel it's necessary to record slips?

I'm planning to add the round end scoring from /vg/, slips is part of the weird stats it shows. I can remove it from the blackbox if you don't want it there.

**Comment by optimumtact** [comment]
it's fine on the blackbox subsystem it just doesn't need to go into the db, so you shouldn't use record feedback

**Comment by Lett1** [comment]
> it's fine on the blackbox subsystem it just doesn't need to go into the db, so you shouldn't use record feedback

So, do it like /vg/ and have a big associated list for possible stuff thats scored?

**Comment by optimumtact** [comment]
well some of it probably already exists in other locations for counts but basically yeah

**Pull request closed without merging**
