### PR TITLE
Adds code coverage badge

### PR DESCRIPTION
**Pull request by MrsTonedOne**
Coverage

### CODE REVIEW

**Comment by RemieRichards** [comment]
This should be on the server repo too tbh after what just occurred.

**Review by Cyberboss — APPROVED** [review]

**Comment by Jalleo** [comment]
I have no idea of whats just occured so uh. Can I ask what happened?

**Comment by Cyberboss** [comment]
No

**Comment by Jalleo** [comment]
Okay then.

**Pull request merged**
