### PR TITLE
Makes the antitamper mechanism prevent tampering 2: electric boomaloo

### PR DESCRIPTION
**Pull request by Screemonster**
:cl:
tweak: The anti-tamper mechanism on abandoned crates now resists tampering.
tweak: Secure, non-abandoned crates can be given a %chance of exploding when tampered with. Defaults to 0.
/:cl:

Rewrite of #20880.
Instead of going off on bullet_act as before, this PR incorporates the changes Phil325 made in #20793 because wow that is so much nicer.

Secure crates now have a "tamperproof" var that determines the chance of it blowing up when anything happens that would cause it to bust open.
They have the same chance of detonating when caught in the radius of an explosion - without this, testing showed a _disappointing lack_ of horrible cascading explosions as the crates don't explode hard enough to bust their neighbours open in one go.

By default, the explosion chance is zero, obviously this can be varedited in-game or in future updates if someone wants to make guncargo risky by setting certain crates to have different probabilities (as suggested on the forums - no need to make weed control crates tamperproof, but weapon crates might benefit)

Abandoned crates have a 90% chance of boom because solve the puzzle you bums. Boom() has been removed from abandoned crates as the proc has been moved up to the parent.

### CODE REVIEW

**Comment by phil235** [comment]
I don't really see the point of moving the tampering thing to all secure crates. And having the tampering effect be a probability is odd. Loot crate are special so it's reasonable to have an explosive rigged in it, but not for secure crate shipped directly from centcom.

Also, why not put the tampering code in take_damage() instead?

**Comment by Screemonster** [comment]
Because I'm a dummy and I completely missed that proc when I was reading through all the changes that had been made to how damage works. That would make more sense.

Probability was there to have an (admittedly low) chance of getting some goodies the old-fashioned way. If people would rather not have RNG involved then setting it to a 1 or 0 would be easy enough.

As for all crates, that's more for the functionality of being able to, say, map a crate other than a loot crate onto a space ruin or similar with the tamperproof var set to be non-zero.

**Comment by optimumtact** [comment]
Why do you keep making new pr's ?

**Comment by optimumtact** [comment]
are you going to move this to take_damage ?

**Comment by Screemonster** [comment]
Was away for a couple of days and hoping to get some input. Made a new PR 'cause the damage overhaul getting merged meant it was simpler to start over.

**Comment by optimumtact** [comment]
Thanks

**Pull request merged**
