### PR TITLE
Fixes to gas station ruin in icebox

### PR DESCRIPTION
**Pull request by EEASAS**
## About The Pull Request
Fixes some things(check mapdiff2 for them)
mainly the double terminal that probably was giving the ruin 0 power consumption i think
removes the double invisible tiny fans and replaces them with double vents
fixes the areas a bit
removes some modifiers on the APC 
## Why It's Good For The Game
Fixes are good for the game
## Changelog
:cl:
fix: Fixed some things in Ice Box's gas station ruin
add: Adds some things in Ice Box's gas station ruin
/:cl:

### CODE REVIEW

**Comment by ZephyrTFA** [comment]
"check mapdiff" is not a valid explanation of your pr.
List your changes

**Comment by EEASAS** [comment]
fine

**Review by Maurukas — CHANGES_REQUESTED** [review]
Double check your pipenets, you've got 8 atmos pipes that are throwing errors in unit tests. This means you have multiple pipes on or pointing to the same turf.

**Comment by EEASAS** [comment]
i dont know how to update a file in the github web editor help aa

**Comment by EEASAS** [comment]
yea its fixed @Maurukas

**Pull request merged**
