### PR TITLE
corrects surplus rifle name to mosin nagant

### PR DESCRIPTION
**Pull request by praisenarsie**
the uplink gives a mosin instead of a surplus apparently

### CODE REVIEW

**Comment by Dorsisdwarf** [comment]
I thought the mosin *was* the surplus rifle

**Comment by JJRcop** [comment]
@Dorsisdwarf is right, mostly. We currently have the mosin nagant and surplus rifle. Both use the same sprite, and they are supposed to be the same rifle, except the mosin nagant is bolt action and the surplus rifle is semi auto. Instead of renaming this uplink item, remove the surplus rifle from the code, since the bolt action one is much more interesting and is the one used by the uplink item. I don't think the name of the gun should be said in the uplink menu, it fits the game better thematically.

Here's the gun to remove https://github.com/tgstation/tgstation/blob/52c0d78037b4752b465d019d509138310169cd3b/code/modules/projectiles/guns/ballistic/automatic.dm#L388-L412

**Comment by praisenarsie** [comment]
@KorPhaeron remove surplus rife y/n?

**Comment by Bawhoppen** [comment]
You need to change the desc as well too then, because now the desc and name don't line up (except from the perspective of being a joke, however we know that by intent it wasn't made to be that way)

If that made no sense, it's a really complicated explanation for why I think you should change the desc based on subtle hints and perspective. 
Basically just trust me and change it to a generic desc about Mosins.

**Comment by KorPhaeron** [comment]
@praisenarsie Sure, someone else can add a garand with its own sprite if they really want a garand

**Comment by praisenarsie** [comment]
busy, will reopen sometime later

**Pull request closed without merging**
