### PR TITLE
Adds a small art gallery to the Metastation library.

### PR DESCRIPTION
**Pull request by Firecage**
## About The Pull Request
This PR simply adds a small Art Gallery to the Metastation library where the virtually never used reading rooms used to be. It also adds easels, canvasses, and spray cans to the library back room.

image

## Why It's Good For The Game
It was kind of annoying that the library on Meta had useless reading rooms, yet lacked the nice art gallery which Deltastation had. So this remedies that, and perhaps more people might visit it then when it is Meta.

## Changelog
:cl:
add: The reading rooms on Metastation has been renovated into a small art gallery.
/:cl:

### CODE REVIEW

**Comment by Mickyan** [comment]
it's missing the private collection in the curator office if you want to add that

**Comment by Angustmeta** [comment]
Can you fit at least one private reading room somewhere? Those are very comfy and useful.

**Comment by Firecage** [comment]
I am honestly unsure where I would even put a reading room. The location where I put the gallery is probably the ideal location for a gallery to be. And, well, expanding into maint might not work since I would have no idea how to fit that in.

**Comment by kriskog** [comment]
You've (accidentally) removed a display case. Carpet also looks a bit awkward, try removing it?

**Review by kriskog — CHANGES_REQUESTED** [review]
You've (accidentally) removed a display case. Carpet also looks a bit awkward, try removing it?

**Comment by Firecage** [comment]
....How the heck did I remove a display case, not notice it, and even keep the camera there.

**Comment by kriskog** [comment]
Merge conflict

**Comment by Firecage** [comment]
@kriskog I realised that, trying to resolve it, and can't figure out how. And wondering why it is conflicting with bar stuff....

**Comment by Firecage** [comment]
So....removing the sofa I added to the library, somehow resolved the merge conflict.

Okay.

**Pull request merged**
