### PR TITLE
nerfs flightsuit zoom

### PR DESCRIPTION
**Pull request by silicons**
sometimes i look at my own code and wonder how i act like i'm drunk when i'm not drunk.
29x29 --> 25x25.

### CODE REVIEW

**Comment by praisenarsie** [comment]
were YOU drunk though?

**Comment by lzimann** [comment]
Gotta give a reasoning.

**Comment by kevinz000** [comment]
it's unwieldly and it is op.

**Comment by KieranCat** [comment]
25 is a good range for flightsuit zoom

**Comment by Robustin** [comment]
What a coincidence, I wonder if you're drunk too when you do this shit.

Letting you quadruple your vision because you put on a stupid jetpack was absurd. 25x25 is still almost triple the area and it makes no damn sense for a suit whose purpose is flying. 

If you want the user to see where they are going, it makes infinitely more sense to just shift their vision forward like scopes do - so they lose situational awareness but gain longer vision in a single direction. You know that actually sounds thematic and not just "I want a suit that makes me a god".

**Comment by Bawhoppen** [comment]
Robustin is right. We go way overboard way too often when it comes to benefits from stuff like this.

**Comment by kevinz000** [comment]
lol robustin

**Comment by Bawhoppen** [comment]
lol kevinz "shameless powergame" 000

**Comment by Spaceinaba** [comment]
today on "everything i dont like is powergaming"

**Comment by PKPenguin321** [comment]
but kev is (or at least was) notorious for that tho

**Pull request merged**
