### PR TITLE
During moth week, teleporter accidents make you Moths

### PR DESCRIPTION
**Pull request by Fikou**
## About The Pull Request

During moth week, teleporter accidents turn you into a moth instead of a fly

## Why It's Good For The Game

It's a funny interaction I think.

## Changelog
:cl:
expansion: During moth week, teleporter accidents make you Moths
/:cl:

### CODE REVIEW

**Review by Mothblocks — APPROVED** [review]
lol

**Review by Kylerace — APPROVED** [review]

**Review by coiax — APPROVED** [review]

**Comment by Iamgoofball** [comment]
:+1: lmao

**Comment by optimumtact** [comment]
@coiax I assigned this to myself, can you explain why you merged it

**Comment by Mothblocks** [comment]
excited fro moths

**Comment by optimumtact** [comment]
mothblocked again

**Comment by Timberpoes** [comment]
coiax power play.

The mothperson agenda at work.

**Pull request merged**
