### PR TITLE
Tgui input refresh

### LINKED ISSUE #63629: Succumb TGUI input requires text to succumb
If you try and succumb, the TGUI input that appears requires some sort of input to it, whereas it used to accept nothing

### LINKED ISSUE #63777: TGUI Number input cannot be autofocused/selected
## Round ID:
Current

## Testmerges:
Current

## Reproduction:
TGUI number input cannot be autofocused or autoselected, it's using numberinput.js which is incompatible. 

Numberinputmodal will have to use a custom or rewritten input component that accepts only numbers, max values and min values, and is written in class component format.

### PR DESCRIPTION
**Pull request by jlsnow301**
## About The Pull Request
This PR addresses a number of issues surrounding tgui inputs (some I caused, some that existed prior- assign gbp however you like)

- Fixes #63777 - the new component autofocuses, auto selects.
- Fixes issues that existed with tgui alerts. Rewritten ground up, the window now responds to user preferences and no longer clips messages.
- Sets all occurrences of number inputs to use a strict sanity check.  
- Fixes #63629 .... which is my mistake entirely

## Why It's Good For The Game
TGUI number input is now much more like the byond numberinput. It's entirely less annoying now that it autofocuses
Adds in some code improvements
Covers more error cases
TGUI inputs are now all consistent with user prefs handling

## Changelog

:cl:
fix: Tgui number input now uses a new component that makes it easier to use. It now autofocuses and autoselects, just like the original. 
fix: Alert modals have been rewritten. Messages no longer clip, they also now respond to TGUI input preferences (UI tab) and you can press ESC to close.
fix: You should now be able to enter a blank text to succumb.
/:cl:

### CODE REVIEW

**Comment by Colovorat** [comment]
thank god holy fuck, thank you man

**Comment by Iamgoofball** [comment]
Issue created by you, as per new maintainer policy, no GBP gain

**Comment by jlsnow301** [comment]
> Issue created by you, as per new maintainer policy, no GBP gain

I'm fine with either or...

**Comment by jlsnow301** [comment]
This is ready whenever

**Comment by stylemistake** [comment]
when... you code it?

**Pull request merged**
