### PR TITLE
Removes jabroni outfit

### PR DESCRIPTION
**Pull request by Wilchenx**
:cl: Wilchen
del: Removed jabroni outfit
/:cl:

"Jabroni ouftits are purely fetish content in a game community where it is so despised. Whereas nearly everything else of this type is treated with contempt, some people think this should stay. For the drama it causes, and the people who dislike it, I see hardly a reason for it to remain in the game, it is not worth it. There is no reason to treat this differently than any other fetish content."

### CODE REVIEW

**Comment by Ledwin1233** [comment]
no
i need my jabroni outfit to robust people in

**Comment by optimumtact** [comment]
https://www.youtube.com/watch?v=C19PIEe5Ti8

**Comment by subject217** [comment]
[epic](https://i.imgur.com/3Rwdwpi.png)

**Comment by 81Denton** [comment]
I expected nothing less than a web edit PR that doesn't even compile

**Comment by Iamgoofball** [comment]
the difference here is we don't pretend this ISN'T fetish content

**Comment by GuyonBroadway** [comment]
Do you think we can get away with spamming gachi till cyberboss is forced to close this pr?

**Comment by Jordie0608** [comment]
ishiggydiggy

**Comment by subject217** [comment]
absolutely based and redpilled jordie, upvoted, liked, and subscribed

**Comment by PKPenguin321** [comment]
we do not deserve jordie

**Comment by Wilchenx** [comment]
now this is epic

**Pull request closed without merging**
