### PR TITLE
Space dragon resprite.

### PR DESCRIPTION
**Pull request by Toastgoats**
## About The Pull Request

Exactly what it says on the tin, it's a full reskin of the current space dragon, designed to be bigger and carpier while still being in the same spirit as the original sprite.

All formatting and code, such as the dragon's coloring mechanic/GAGS has been unchanged, only the sprite itself is affected.

Idle animation

Finished wing spritesheet

## Why It's Good For The Game

Some players have been dissatisfied with the current space dragon sprite, particularly with it's death state and some design quirks. While I like the original noodle dragon, I've been told to pitch this as a full replacement, so I will.

## Changelog

:cl: Toastgoats
imageadd: New space dragon sprite!
/:cl:

### CODE REVIEW

**Comment by Imaginos16** [comment]
Swag dragon

**Comment by cacogen** [comment]
reignited

**Comment by Sealed101** [comment]
looks awesome but why hands-claws-whatever this is

**Comment by Toastgoats** [comment]
> looks awesome but why hands-claws-whatever this is

Did hands, thought they looked like the vibe check meme hands, people on the discord server thought the same thing and liked em so I rolled with it.

**Comment by MrDoomBringer** [comment]
Sprite would probably look a lot better without the hands but they're funny so keep them

**Comment by IndieanaJones** [comment]
I don't know if I completely dig the hands myself but you're the artist 👍

**Comment by CRITAWAKETS** [comment]
I think the hands might look less out of place with longer claws, just maybe.

**Comment by Farquaar** [comment]
Fan of the sprite
Not really a fan of the hands

**Comment by necromanceranne** [comment]
I think the hands are cute

(Dexterity when)

**Comment by MetalClone** [comment]
It looks cool but it looks more lizard-y than space carp-like

**Comment by UnokiAs** [comment]
Make the dragon able to grab and throw people with a force of 1000 with his little hands would be based

**Comment by Toastgoats** [comment]
Putting in some last minute changes I forgot to put in

**Comment by Imaginos16** [comment]
Seems to be an overwhelmingly positive change

**Pull request merged**
