### PR TITLE
Soil no longer starts with full nutriment and water

### PR DESCRIPTION
**Pull request by ChangelingRain**
:cl: Joan
bugfix: Soil no longer starts with full nutriment and water.
/:cl:

### CODE REVIEW

**Comment by Niknakflak** [comment]
:-1: should make chemistry dispensers start with zero energy and apcs start empty as well to go along with this bad change

**Comment by ChangelingRain** [comment]
we must exit lemon hell and this is the fastest way

**Comment by Niknakflak** [comment]
Wait this soil, not even trays.  I dont give a fuck if its soil

**Comment by Kromgar** [comment]
Lemons no longer exist

**Comment by Hatfish** [comment]
This will make it impossible to grow things as a lavaland role, big :-1:

**Comment by PKPenguin321** [comment]
soil that's placed by maps at roundstart should have full nutrient and water. new soil turfs that are made by players should be empty. this PR is incomplete because it just removes both.

**Comment by bobdobbington** [comment]
Can you please fucking not I'm tired of maintainers conspiring with ma44 to completely ruin my department. The cash lemons were removed, the null crates were removed. This makes assistant garden kill all your plants almost immediately if you don't know what you're doing. In actual IRL gardening, potting soil comes with a nutrient load.

**Comment by PKPenguin321** [comment]
meme tags reee

**Comment by KorPhaeron** [comment]
wouldn't this kill any attempt at makeshift botany in maint/lavaland etc

**Comment by bobdobbington** [comment]
yes

**Comment by ma44** [comment]
I'm not conspiring with maintainers to fucking nerf Botany to the ground, i even tried to revert cash lemons ;-;

**Pull request closed without merging**
