### PR TITLE
Magic Mania 1.84 Antag hud system for wizards

### LINKED ISSUE #6992: No way to identify Wizard apprentices
Needs to be a way to identify when someone's your apprentice, even if they've mindswapped. This'd make going confusion wizard actually worth doing without fucking everything up and accidentally killing each other.

### PR DESCRIPTION
**Pull request by Incoming5643**
untitled-2 copy
Yellow on blue for wizards, White on red for apprentices. Remember these guys elnath on snap judgement, the icons SHOULD be garish

The huds won't be activated when there's just one wizard, but when another magic user is brought in the huds will appear for both of them to allow for easy identification in the face of rampant mindswaps and/or identity shinanagans and/or getting turned into a cow by a staff of change.

The huds are on by default in ragin' mages.

Fixes #6992

### CODE REVIEW

**Comment by Iamgoofball** [comment]
Thanks man, that's an issue off my plate for ragin' mages

**Comment by Lumipharon** [comment]
Man, not being able to tell who people are is half the fun of mindswapping.
Also it means if you summon magic, and a crew member mindswaps a mage/apprentice, they'll know. Oh well.

**Comment by Incoming5643** [comment]
That's not how minds work Lumi

**Comment by AlexCrimson** [comment]
One step closer to AntagHUDs for ghosts/observers?

**Comment by tkdrg** [comment]
I considered adding an observer HUD with my rewrite, but gave up because of the possible meta. One step closer to adding these to admins, though, I suppose.

**Comment by paprka** [comment]
Give apprentices scarves!

**Comment by optimumtact** [comment]
We don't have time to fufil all your fetishes pap

**Comment by Razharas** [comment]
Inconsistent with headrevs/revs
Make it blue for wizs and red for apps

**Comment by Razharas** [comment]
Also id still make them unable to cast shit in the den

**Comment by tkdrg** [comment]
Also conflicts

**Pull request merged**
