### PR TITLE
Updates all storage bag icons

### PR DESCRIPTION
**Pull request by Wallemations**
## About The Pull Request
Updates all storage bag icons to new and improved sprites.
Based off my mailbag sprite
8 of the 10 sprites are done by @Imaginos16.

Also splits the biobag into a virologist & scientist bag.

## Why It's Good For The Game
New sprites good
Also they look cute! Look at these lil' things.
image

## Changelog

:cl: Wallem & Imaginos
balance: Splits biobags into virology & science bags. Virology bags can't hold slime cores or cytology equipment, and science bags can't hold medipens & bloodbags.
imageadd: Changes all storage bag sprites
/:cl:

### CODE REVIEW

**Comment by Wallemations** [comment]
Some people seem confused over this, no this is not SATCHELS that you put on your back.
These are those ones you put on your belt that scoop up items really quick.
I personally wanted to rename them to "pouches" in this PR but some people didn't seem keen on that.

**Comment by UnokiAs** [comment]
Cute bags

**Comment by Amrabol** [comment]
In case you did not seen my message in coding-general add sprite for xeno bag to belt.dmi and belt_mirror.dmi

**Comment by Dorsisdwarf** [comment]
The rare soul-adding sprite PR

**Comment by Wallemations** [comment]
> In case you did not seen my message in coding-general add sprite for xeno bag to belt.dmi and belt_mirror.dmi

Did this pr at like 2am last night and forgot to do that, just finished it rn. That should be all the sprites.

**Review by Twaticus — APPROVED** [review]

**Comment by OrionTheFox** [comment]
> Some people seem confused over this, no this is not SATCHELS that you put on your back. These are those ones you put on your belt that scoop up items really quick. I personally wanted to rename them to "pouches" in this PR to help differentiate them but some people didn't seem keen on that.

PLEASE rename them to pouches, the term 'pouch' is never used for any items and would be perfect for 'bag that fits in your pocket'

**Comment by Wallemations** [comment]
> > Some people seem confused over this, no this is not SATCHELS that you put on your back. These are those ones you put on your belt that scoop up items really quick. I personally wanted to rename them to "pouches" in this PR to help differentiate them but some people didn't seem keen on that.
> 
> PLEASE rename them to pouches, the term 'pouch' is never used for any items and would be perfect for 'bag that fits in your pocket'

Rn I just want these sprites merged, so I don't want to have to get everything re-accepted or whatever. I also don't want to lump these in with a name change. I plan on doing a different PR for a name change once this one goes through, so it can be decided there instead of here.

**Pull request merged**
