### PR TITLE
Computers emitting light

### PR DESCRIPTION
**Pull request by ghost**
This makes computers emit a small bit of light. Probably a better way to go about this but hey no more pitch black computer screens

### CODE REVIEW

**Comment by WJohn** [comment]
:+1:

How much light are we talking about here? Only visible on its own tile in pitch blackness? Extends out by 1?

**Comment by Iamgoofball** [comment]
colored lighting when

**Comment by paprka** [comment]
it pretty much only lights the tiles directly around them

**Comment by Alek2ander** [comment]
Broken computers show a bluescreen and should technically be lit as well... :beetle:

**Comment by Dorsisdwarf** [comment]
Can broken computers be made the absolute minimum brightness just on their own tile, so you can see them, but not by them.

**Comment by Miauw62** [comment]
:+1: for more spoopy atmosphere

**Comment by paprka** [comment]
@Dorsisdwarf yeah I can do that

**Comment by AndroidSFV** [comment]
Can AI uploads or other potentially useful/damaging computers that might be built by an antag in some dark corner of maint not do this, at the same time?

**Comment by paprka** [comment]
That defeats the purpose of the PR

**Comment by Jordie0608** [comment]
Changelog

**Comment by paprka** [comment]
Changelog.

Also, computers that are bluescreened will emit light too now.

**Comment by RemieRichards** [comment]
@paprka good to go (I assume yes)?

**Comment by paprka** [comment]
Yeah, I'd test it on your end though, especially the machine subsystem

**Comment by RemieRichards** [comment]
Alright, I'll check it when I get home (about 12:45)

**Comment by paprka** [comment]
No rush!

**Pull request merged**
