### PR TITLE
Adds the dmm2tgm converter to MapMerge

### PR DESCRIPTION
**Pull request by CorruptComputer**
ITS HAPPENING

Disclaimer: May break.

### CODE REVIEW

**Comment by RemieRichards** [comment]
Absolutely not, you've not ported the tool correctly AT ALL.

**Comment by CorruptComputer** [comment]
@RemieRichards 
````
"aaa" = (
	/turf/space,
	/area/space)

"aab" = (
	/turf/simulated/mineral/random/low_chance,
	/area/mine/explored)
````

Looks alright to me, whats the problem?

**Comment by CorruptComputer** [comment]
Also with vars edited:
````
"aaf" = (
	/obj/effect/landmark/start{
		name = "Assistant"
	},
	/obj/structure/stool/bed/chair/comfy/beige{
		dir = 4
	},
	/turf/simulated/floor/carpet,
	/area/hallway/secondary/entry{
		name = "Arrivals Lounge"
	})
````

**Comment by CorruptComputer** [comment]
Real one can be found here: https://github.com/tgstation/-tg-station/pull/10866

**Pull request closed without merging**
