### PR TITLE
Adds soap/mop/rag/cleanbot cleaning animation

### PR DESCRIPTION
**Pull request by kawoppi**
## About The Pull Request
Using soap, mops or rags places an animation overlay (bubbles) on what you are cleaning, while you are cleaning it. [See it in action over here.](https://youtu.be/d3pVBcFrz78) When you're cleaning a floor tile the overlay will appear above all filth/blood/vents/holopads on that tile. The overlay will appear below any people/furniture on that tile though. When you're cleaning a person/furniture the overlay will appear on top of what you are cleaning. 

The animation is not hidden when it is outside of your FOV. I could not find a way to combine that with also having it appear under furniture. But seeing blood disappear outside of your FOV gives away the same information anyways.

[Cleanbots also use the animation now (they are very fast cleaners though).](https://youtu.be/2_zCbuphPSI)

## Why It's Good For The Game
Cleaning can be slightly awkward currently. You know that you're cleaning, but everyone else just sees you standing there staring at nothing. The cleaning animation shows that you are actually doing something. Hopefully it will prevent people from accidentally moving you while you're cleaning. It should also make it easier to clean people, since they'll be less likely to  walk away and unknowingly interrupt the cleaning.

## Changelog

:cl:
add: added animation for cleaning things with soap, mops, rags or cleanbots
imageadd: added cleaning bubbles animation
/:cl:

### CODE REVIEW

**Comment by wesoda25** [comment]
Would it be possible to make it only appear above whichever thing you are cleaning? Looks a bit funky to appear above mobs.

**Comment by kawoppi** [comment]
Yes, but that causes problems when cleaning bloody floors. Clicking the floor tile instead of the blood itself will clean all blood, filth and gibs off that tile in one go. The overlay would when appear above the tile, but under any blood/gib sprites. Some gib sprites can completely obscure the animation this way. There's also the issue of things like holopads obscuring the animation when you're cleaning the tile under it.

Tomorrow I'll try out some different layers/planes to hopefully find a way to display it under mobs but at the top of a tile.

**Comment by Elli-Skala** [comment]
Another assault mop nerf 😔

**Comment by Wallemations** [comment]
> Yes, but that causes problems when cleaning bloody floors. Clicking the floor tile instead of the blood itself will clean all blood, filth and gibs off that tile in one go. The overlay would when appear above the tile, but under any blood/gib sprites. Some gib sprites can completely obscure the animation this way. There's also the issue of things like holopads obscuring the animation when you're cleaning the tile under it.

You could give the layer swapping a lower boundary
Like
```if(above_clean_layer < [above whatever layer cleanable decals are on])
      above_clean_layer = [Previously mentioned layer]
```

**Comment by kawoppi** [comment]
It should look better now, also applied the animation to cleanbot cleaning.

I'm worried about having copy-pasted the same cleaning animation code in four different places. I think I have an idea on how to fix that so I'm going to give that a try before undrafting the PR.

**Review by Twaticus — APPROVED** [review]

**Comment by kawoppi** [comment]
The animation code is now in the cleaner component instead of copy-pasted to four different places.

**Pull request merged**
