### PR TITLE
Fixes abductor surgery designs

### PR DESCRIPTION
**Pull request by XDTM**
They weren't appearing in the production list even with the required tech.

### CODE REVIEW

**Comment by GunHog** [comment]
I did not know these things existed, lol. Do the alien surgery tools work faster, or are they simply for flavor like the alloy?

**Comment by OtherDalfite** [comment]
Abductor surgery tools are ridiculously fast. I (think) they also pass through all clothing, as I've operated on an engineer who had a full hardsuit on, and didn't fail once.

**Comment by GunHog** [comment]
Does that count for surgeries other than the special abductor experimentation surgery?

**Comment by XDTM** [comment]
They're 4 times as fast, but do not pass through clothing, although that's a very nice idea. Abductor experimental surgery is special and does not need to remove clothing, that's why it worked for you.

**Pull request merged**
