### PR TITLE
Reactive Teleport Armor can teleport the user to space tiles again

### PR DESCRIPTION
**Pull request by Ikarrus**
Now they actually have a risk to using them!

### CODE REVIEW

**Comment by Kromgar** [comment]
Still my favorite item in the game

**Comment by Iamgoofball** [comment]
This is dumb :-1:

**Comment by KorPhaeron** [comment]
Cool

**Comment by Steelpoint** [comment]
Good change.

**Comment by Xhuis** [comment]
thumbsup

**Comment by Kromgar** [comment]
You should be able to install some manipulators and bluespace crystal into it to make it safer... like a lower chance of being spaced

**Comment by Dorsisdwarf** [comment]
:+1: to PR
:-1: to pwrgm suggestion

**Comment by Fox-McCloud** [comment]
:-1: 

If it's OP, then nerf it's chance or bring the slowdown back--"lolrng" take people out of the round isn't fun or a good way of balancing things (need I mention the teleporter?).

**Comment by Ikarrus** [comment]
You can avoid the RND by simply keeping away from the station exterior. The teleport range is only 6 tiles.

**Comment by Lumipharon** [comment]
Good. Made no sense that it would try avoid space, considering it's 'random'.

**Comment by KorPhaeron** [comment]
Or just don't put the armor on at all. It's high risk, high reward

**Comment by Fox-McCloud** [comment]
@KorPhaeron 

That same argument could have been used against teleporters...and yet it didn't hold water either.

**Comment by Steelpoint** [comment]
You could argue the teleporters can avoid going to space by virtue of the more processing power the teleporter has available to it, whereas the smaller teleporter armour lacks that.

**Comment by KorPhaeron** [comment]
@Fox-McCloud 

Teleporters put you in deep space, which was more or less gibbing you. They were also the only reliable way to get to certain places

**Comment by Miauw62** [comment]
:-1:, this is a pretty stupid solution.
maybe if you tried engaging your brains instead of REVERT REVERT REVERT, you could think of a solution.
such as making the teleport stun you for some time and irridiating you a little.

**Comment by Steelpoint** [comment]
I always thought it made sense that this armour was meant to be a very high risk, high reward item in that it could save you, but if your too close to space you might accidently space yourself.

Don't forget that this item only should space you if your near the exterior of the station, I'm sure the older version used to be a flat chance to drop you into deep space.

**Comment by Miauw62** [comment]
so you get an unfun chance to gg no re ur ded near the exterior (6 tiles, which is a short distance!), and in the interior nothing changes and its as OP as ever?

**Comment by KorPhaeron** [comment]
Uhm I did engage my brain when I originally added this and gave it this downside on purpose.

It's a mad science item inspired by something orks use in Dawn of War, being randomly killed by your own armor fits perfectly with the theme.

**Comment by Miauw62** [comment]
"fits within the theme" is not a justification for shoddy gameplay.

**Comment by KorPhaeron** [comment]
How is it shoddy gameplay? Sometimes its such an amazing protective item it not only blocks the hit, it sends you sailing clear of your assailant.

Sometimes it's such a shitty item it turns the clown disarming you into a death sentence.

Very high risk, very high reward. Strong items that have a catastrophic failure chance are not uncommon in games

**Comment by Iamgoofball** [comment]
Alternate nerf up here:
https://github.com/tgstation/-tg-station/pull/10131

**Comment by Miauw62** [comment]
well yes, but it /kills you without anything you can do about it/.
well, i guess you could just not use it on the edge of the station, which would be fair.
except that the range of this thing is only six tiles. unless you're fighting in maint, you will basically never be spaced.
so this nerf is only really effective in a narrow amount of cases.

**Comment by RemieRichards** [comment]
@Ikarrus replace line 120, ```src.loc = picked``` with ```forceMove(picked)``` please.

**Comment by KorPhaeron** [comment]
Or just not put the armor on, that is also a way to avoid spacing. You're willingly gambling if you choose to use it

**Comment by GunHog** [comment]
Wear it with a bag of holding for EXTRA RISK!!

**Comment by Ikarrus** [comment]
It's not !!SCIENCE!! without the risk of hilarious bodily harm

**Comment by Ikarrus** [comment]
More opinions here if you guys want it https://tgstation13.org/phpBB/viewtopic.php?f=10&t=3955

**Comment by RemieRichards** [comment]
@Ikarrus make the change please.

**Comment by Ikarrus** [comment]
I'm stuck away from home so I can't make the change for at least another hour :E

**Comment by RemieRichards** [comment]
arrrrrgh

**Comment by optimumtact** [comment]
:-1: please put this to community vote

**Comment by Ikarrus** [comment]
I am stuck away from home and wont be able to make the change for at least another hour :(

**Pull request merged**
