### PR TITLE
Rice Dough can be made in a beaker

### LINKED ISSUE #77966: Rice Dough is unmakeable due to Uncooked Rice recipe
## Round ID: 
[213479](https://scrubby.melonmesa.com/round/213479)

## Testmerges: 
N/A

## Reproduction:

1. Plan to make Noodles
2. See how to make Noodles
3. Rice dough - **10u Flour + 10u Rice + 10u Water**
4. Attempt to make Rice dough
5. Uncooked Rice is made instead
6. See Uncooked Rice's recipe
7. **10u Rice + 10u Water**
8. Scream

Suggestion: Change Uncooked Rice's recipe to need 15u Water instead of 10u.

### PR DESCRIPTION
**Pull request by blueDev2**
## About The Pull Request

Rice dough can be made in a beaker using 20u of Rice Flour and 10u of Water. 10u of Rice Flour is made from 5u of Rice and 5u of Flour. Rice dough can still be crafted manually using the crafting menu and the original recipe. 
## Why It's Good For The Game

Cooks can sometimes get swamped with work, especially on a high-pop shift or when there are no botanists. By making rice dough more convenient to make, cooks don't need to spend as much time in the crafting menu. 
Rice Flour is made from mixing equal parts Rice and Flour. Since no recipe other than Rice dough uses both Rice and Flour in it's Recipe, it should be fine to turn those regents into the intermediate reagent "Rice Flour".
Fixes #77966
## Changelog
:cl:
qol: Rice Dough may be made in beaker instead of being crafted, but the rice and flour must be added first
/:cl:

### CODE REVIEW

**Comment by blueDev2** [comment]
I can't really do anything about the integration test, but rice dough, dough, and uncooked rice can all be made with the beaker.

**Comment by Comxy** [comment]
I think you are better off making the recipe for rice dough = uncooked rice + dough, so you don't have to make that unnecessary balance change

**Comment by blueDev2** [comment]
> > I can't really do anything about the integration test, but rice dough, dough, and uncooked rice can all be made with the beaker.
> 
> I feel like a logical solution to this is to make a new reagent, `rice_flour`, that is produced by grinding rice. And then just make the reaction use that instead of flour.
> 
> Or even have it be a subtype of normal flour, that way it can be used interchangeably with regular flour in some recipes. Would be a nice thing to have if you are running out of flour and still have some rice on hand, too.

I made "rice_flour", but I made it as a mixture of rice and flour. I think if it was produced by grinding rice, it would have considerable 'balance' issues

**Comment by blueDev2** [comment]
> I think you are better off making the recipe for rice dough = uncooked rice + dough, so you don't have to make that unnecessary balance change

Uncooked rice is precipitated out of the beaker as an item. If it remained a reagent, I would agree with you.

**Review by Ghommie — APPROVED** [review]

**Comment by Ghommie** [comment]
I'm actually a tad stupified that rice dough (and therefore dough) requires regular flour,. It's indeed senseless, though will all the recent changes, additions and issues with food, I shouldn't be surprised.

**Pull request merged**
