### PR TITLE
Updates Slime Potion sprites

### PR DESCRIPTION
**Pull request by Wallemations**
## About The Pull Request
Tin
Also adds additional colors to try and reduce the amount of reused colors.

https://github.com/user-attachments/assets/b02dffa0-c835-4bb2-b96d-5054ed86d137
## Why It's Good For The Game

Those were OLD OLD sprites
Also, I swapped the lava-protection potion and speed potion sprites as I felt the potion that makes stuff red to make it go fast should probably be red.
## Changelog
:cl: Wallem
image: Updates slime potion sprites, adds some new colors and rearranges some others.
/:cl:

### CODE REVIEW

**Comment by Donkier** [comment]
they kinda look like factorio science packs

**Comment by Wallemations** [comment]
> they kinda look like factorio science packs

I used the science packs as a reference!

**Comment by Wallemations** [comment]
I just remembered the UI for the slime console probably also needs a change but unfortunately someone else is using my computer until further notice

 image

**Comment by Wallemations** [comment]
I lowered the rainbow one's frame count and updated the slime camera console's UI sprites to match new slime & potion sprites

**Comment by Paxilmaniac** [comment]
installing factorio disco science mod

**Comment by Imaginos16** [comment]
Sure, this is nice!

**Pull request merged**
