### PR TITLE
Removes goonchat ping display

### PR DESCRIPTION
**Pull request by Cyberboss**
We don't need to waste server resources running two ping trackers. Also reworks the connectivity checker loop to use the controller instead of sleeps

### CODE REVIEW

**Comment by ChangelingRain** [comment]
It'd be more helpful if the goonchat ping tracker just used the status panel ping, since you can't always be in the status panel tab to look at it.

**Comment by Nilons** [comment]
@ChangelingRain This, it should just display what the status panel does so its not taking up the resources of 2 ping trackers but still giving the utility of always being able to see ping.

**Comment by DoctoreMad** [comment]
Alternatively remove the status tab Ping bar

**Comment by Cyberboss** [comment]
The goonchat ping isn't even the correct ping. It's the ping for the chat window only.

**Comment by DoctoreMad** [comment]
Well sounds like my alternative isn't good then.
Can you just have it be server ping, then?

**Review by ChangelingRain — CHANGES_REQUESTED** [review]
Please make the goonchat ping tracker just use the status panel ping.

**Comment by optimumtact** [comment]
It's better than the one in the status panel, just get rid of that

**Comment by lzimann** [comment]
@Cyberboss

**Comment by Cyberboss** [comment]
laze

**Pull request closed without merging**
