### PR TITLE
Vending refills can now be cracked open

### PR DESCRIPTION
**Pull request by spessbro**
## About The Pull Request
Vending machine refills will now break and spew items on the floor as they do leaving behind a broken refill.

## Why It's Good For The Game
Right now abusing vending machines is very easy but also very boring. This pr streamlines the process while making it expandable by having the refills be able to be destroyed but those being items means there are different things you need to do to crack them open

## Changelog
:cl:
add: Vending machine refills are now breakable
removed:  Vending machine refills will no longer spew out items when broken
/:cl:

### CODE REVIEW

**Comment by Krysonism** [comment]
80% is far too high.

That is thousands or tens of thousands worth of goods.

**Comment by ArcaneMusic** [comment]
This can EASILY be abused to obtain copious amounts of some of the rarest vending objects in the game.
Please god no.

**Comment by spessbro** [comment]
> This can EASILY be abused to obtain copious amounts of some of the rarest vending objects in the game.
> Please god no.

This does the same stuff that happens when you break a vending machine with a spear what do you mean?

**Comment by MrDoomBringer** [comment]
@spessbro this takes a lot less effort

**Comment by spessbro** [comment]
> @spessbro this takes a lot less effort

to break an item you need either a bomb, a whole lot of acid, a plasmafire or a gun all of which you could use to break a regular vending machine before. This definitely takes more effort.

**Comment by dondonpow** [comment]
CODER FIGHT

**Comment by MrDoomBringer** [comment]
@spessbro yes but with this you can get a shitton of vendor refills and make two sodacan-IEDs and place it ontop of the stack to get all the loot, taking massively less time and effort than breaking an equivalent number of vendors.

Also, after you get a gun or whatever, there's basically no cost to breaking them, compared to vending machines needing to be constructed over and over.

**Comment by wesoda25** [comment]
I dream of a world where I can attach c4 to a vending refill and it violently explodes sending a flood of snack foods in all directions.

**Comment by msgerbs** [comment]
I thought breaking a vending machine only dropped some of the items?

**Comment by Jared-Fogle** [comment]
@msgerbs you'd be right

```
	// busting open a vendor will destroy some of the contents
			if(found_anything && prob(80))
				continue

```

**Comment by msgerbs** [comment]
Well there ya go. This is a *massive* balance change then.

**Comment by Winterous** [comment]
Aren't luxury items (the expensive ones usually) never dropped by bashing a vendor? If so, and if that's also true for this PR, doesn't that remove the need for concern over it being "abused to obtain copious amounts of some of the rarest vending objects in the game."?

**Comment by Iatots** [comment]
The ideal way would be to have mini-bounties for cargo and have them choose what to refill a vendor with.

**Comment by Tlaltecuhtli** [comment]
premium items are deleted by bashing the vendor, just make cracking the refill have a chance of give you mummy curse

**Comment by Jared-Fogle** [comment]
I dislike this, and it seems others (including the person who would be most trustworthy on this topic, ArcaneDefence) dislike this as well.

**Pull request closed without merging**
