### PR TITLE
Darkens regular lights

### PR DESCRIPTION
**Pull request by dragomagol**
## About The Pull Request
Darkens regular lighting.

image

image

image

### Before & After
image

## Why It's Good For The Game
Makes halls are a little spookier, and departments feel like little bastions of safety. Hopefully will get us to put some more thought into light placement! 

## Changelog

I have no idea what tag this should even have, I miss tweak.

:cl: Kapu1178
qol: made regular lighting slightly darker
/:cl:

### CODE REVIEW

**Comment by Kapu1178** [comment]
Kapu1178 pls the numbers are very important 😞

**Comment by Mooshimi** [comment]
I already can't see shit please no

**Comment by Jacquerel** [comment]
Does this make it so that the aurora event in the kitchen isn’t virtually invisible?

**Comment by Mothblocks** [comment]
Any chance you can get pictures before too?

**Comment by YakumoChen** [comment]
Don't we already have this with the night lighting?

**Comment by dragomagol** [comment]
> Any chance you can get pictures before too?

Added

**Comment by Wallemations** [comment]
Why would we need to make the halls "spookier"? This isn't a horror game, and the night lighting already exists to lower the light levels.
The way I see it this just makes the game harder to see for no reason

**Comment by Likteer** [comment]
Yikes

**Comment by moocowswag** [comment]
Maybe make it triggered by something rather than a new norm?

It might be hard but mayyyybeee have the lights dim/brighten based on how much excess power is in the powernet? (which is consistent with shocked airlocks in a sense where apcs dont actually limit the amount of power is going into the machines/doors it powers)

**Comment by Mooshimi** [comment]
I like the idea of this as more of a random station trait, not every shift

**Comment by Twaticus** [comment]
too dark :(

**Comment by Wallemations** [comment]
> > Why would we need to make the halls "spookier"? This isn't a horror game, and the night lighting already exists to lower the light levels. The way I see it this just makes the game harder to see for no reason
> 
> 
> 
> `Space Station 13 is a paranoia-laden roleplaying game set against the backdrop of a nonsensical, metal death trap masquerading as a space station.`

I'm sure it's up to opinion, but the part that makes me paranoid about this game is the antags, not the lighting system. When I imagine a corporate office hallway, I usually think of it as well-lit. It'd be up to the antags to stop that from being the case. I'd feel paranoid if I was walking down a pitch black hallway knowing there's a ninja or nightmare on the station, not if the lights are just a smidge dimmer. This just makes it feel like it's always Night Shift, you know?

**Comment by dragomagol** [comment]
I'm thinking that regardless of the end status of this PR, there should be a lighting pass over existing maps. Making medbay use cooler lighting, bar use warmer lighting, maybe more dim lights in maint.

**Comment by Mothblocks** [comment]
I'm going to close this because the art lead doesn't like it

**Comment by LemonInTheDark** [comment]
I wanna do some fenangling to lighting that would involve some stuff like this, will talk to twat when I do for clearance

**Pull request closed without merging**
