### PR TITLE
Plain medkit sprites (competitor to the other)

### PR DESCRIPTION
**Pull request by bigfatbananacyclops**
## About The Pull Request

Resprited medkits to a 3/4 dimension plain looking medkits with clamps holding it shut.
Added different medkit maploadouts to brute and o2 as well

## Why It's Good For The Game
I came to a dilemma of which sprites i should pick, both looked good, i am going to let people decide which one to pick since shizcalev suggested i should.

This are the plain sprites

pixil-frame-0 (25)
pixil-frame-0 (27)
pixil-frame-0 (28)
pixil-frame-0 (29)
pixil-frame-0 (30)
pixil-frame-0 (31)
pixil-frame-0 (32)
pixil-frame-0 (33)
pixil-frame-0 (34)
pixil-frame-0 (35)
pixil-frame-0 (36)
pixil-frame-0 (37)
pixil-frame-0 (45)
plain kits

I kept the bezerk the same because it makes sense for a combat kit to come reinforced.
There's a little problem about the kits with white or black cross, they dont have an inhandsprite, neither did the old sprites with symbols.

Anyways once again, i removed the old symbol medkit sprites because they can confuse people and make them think something else, an object with a radiation sign doesn't really look like something a medkit would probably have, it would probably point out it contains hazards. Since + is the most common i think its best for it to be on all of them.
(i have no idea why there's a purple kit, i sprited it anyways)

### If you like this medkits, upvote, if you like the other ones with reinforced corners, please use confetti emoji

https://github.com/tgstation/tgstation/pull/45252
Closes #45252

If you don't like neither then i really can't do anything about that.

By the way im updating soon the other sprited with white crosses & black crosses on the other PR

## Changelog
:cl:
imageadd: added new sprites for all medkits, toxin haves three medkit types, brute, burn, oxy & rad has two different as well.
/:cl:

### CODE REVIEW

**Comment by partykp** [comment]
This one is way better, fits with the aesthetic more imho.

**Comment by ishitbyabullet** [comment]
That PR is older. The vote is already rigged.

**Comment by Detective-Google** [comment]
It's a shame to 'waste' the more rugged sprites but these seem better for a *medical bay* wheras the other harder corner medkits remind me more of IRL hard case first aid kits

**Comment by Akrilla** [comment]
thicc plus

**Comment by MrPerson** [comment]
Whichever set gets chosen, the other set can always be used in a ruin or something down the line.

**Comment by wesoda25** [comment]
Yes these are perfect

**Comment by JohnOxford** [comment]
for whatever reason the look makes me want to believe that these are the kind of medkits you walk over and immediately get restored to full health while a guy in the background says "GOOD TO GO" as loud as he can.

10/10

**Comment by nemvar** [comment]
I will be honest, I like the darker ones better.

**Comment by PKPenguin321** [comment]
Way nicer, good work

**Comment by wesoda25** [comment]
> I will be honest, I like the darker ones better.

wrong opinion detected

**Comment by Poojawa** [comment]
just make it randomly choose a box from both sets.

**Comment by ishitbyabullet** [comment]
Poojawa, it wouldn't make sense. One looks like a normal first aid kit and the other looks like it better be some heavy duty shit. I'll be damned if all I find inside are some band aids.

**Comment by actioninja** [comment]
Seems like people like these a lot more.
Are you ready for an army of people bitching as soon as this is merged?

**Comment by Detective-Google** [comment]
reddit time woooooo

**Pull request merged**
