### PR TITLE
Stray Meteor event, five new special meteors, and another reason to build meteor shields

### PR DESCRIPTION
**Pull request by Rhials**
## About The Pull Request

meteors

Adds the Stray Meteor random event, as well as a few new special meteors to be featured in it (as well as to meteor waves, but to a lesser degree). Other than these special meteors being a part of meteor waves, the meteor wave event itself is unchanged by this new event.

A single meteor is thrown somewhere in the vicinity of the station, accompanied by a brief warning announcement. To make things more interesting, five new special meteor types have been created to accompany the original three (flaming/irradiated/tunguska). The special meteors have been added to the meteor wave pools, but have lesser weight than the standard meteors. Enough about that though...

<details>

<summary>LETS MEET THE CONTESTANTS</summary>

Bluespace meteor -- chance to teleport upon slamming into something. Destruction varies wildly, but generally always looks pretty cool from ghost view.

Frozen carp -- y'know technically none of these are "meteors" until they get near the earth's atmosphere, so if I say it's a meteor, it's a meteor. Destruction a little more than space dust. Drops a live carp when it breaks.

Bananaium meteor -- honks/slips anyone it hits. Phases through walls/floors instead of destroying them. Has a very very high number of hits, but they tick continually down as it passes through more stuff. If you're lucky, it will pass through the station without breaking open its bananium core...

Cluster meteor -- explodes into meteor fragments upon impact. Destruction on par with a big meteor at times, but varies. Probably the most destructive potential of the bunch.

EMP meteor -- Engineers HATE this one.

</details>

## Why It's Good For The Game

Throws a bit of concentrated chaos into the round, as opposed to the more widespread chaos of meteor waves. Engineering might appreciate the opportunity to actually fix a meteor breach for once, instead of getting 10 minutes into repairs and having the shuttle called because they can't be everywhere all at once. As for the different meteor types added, variety is the spice of life.

Also, gives me an excuse to yell "BRACE FOR IMPACT" every once in a while as Captain. This technically counts as command content. 

## Changelog

🆑
add: Adds a new random event -- Stray Meteor. Throws a meteor in the direction of the station, with a very brief warning beforehand.
add: New special meteor types added -- Bluespace, EMP, Bananium, Cluster, and the Frozen Carp.
/🆑

### CODE REVIEW

**Comment by exymian** [comment]
Thing with meteor events and why its bad is because;
1) Too much destruction in too little time
2) Happens instantly and you can't prepare for it
3) Meteor shields are absolutely terrible as the cover only 3 tiles. You can't set them up every round because meteors are rare and even if you do they are basically useless


-I like that you made it so only 1 meteor hit, thats smart. 
-With its cool variety, i think it would be more fun to let it hit the station and its only 1 meteor.

I'd like to ask; 1) How long does it take for it to hit the station after it gets announced ? 2) If it instantly hits after it gets announced, would you be okay with giving the crew couple of minutes so they get prepared to fix it and for the shuttle to not be called. Maybe add an ETA onthe announcement.

**Comment by timothymtorres** [comment]
> Bananaium meteor -- honks/slips anyone it hits. Phases through walls/floors instead of destroying them. Has a very very high number of hits, but they tick continually down as it passes through more stuff. If you're lucky, it will pass through the station without breaking open its bananium core...

The phase effect should apply to the bluespace meteor, other than that all of this is great!  +1

**Comment by Palpetinus** [comment]
What if you
wanted to do a 60 minute autism project
but god said
"METEORS HAVE BEEN DETECTED ON COLLISION COURSE WITH THE STATION"

The unique ones sound really interesting, except for the cluster one which is just "hurr destroy station" again. Maybe it's too off-topic but maybe meteors need an announcement, saying they'll arrive in X minutes to give the station time to set up shields.

**Comment by Rhials** [comment]
> Thing with meteor events and why its bad is because;
> 
> 1. Too much destruction in too little time
> 2. Happens instantly and you can't prepare for it
> 3. Meteor shields are absolutely terrible as the cover only 3 tiles. You can't set them up every round because meteors are rare and even if you do they are basically useless
> 
> -I like that you made it so only 1 meteor hit, thats smart. -With its cool variety, i think it would be more fun to let it hit the station and its only 1 meteor.
> 
> I'd like to ask; 1) How long does it take for it to hit the station after it gets announced ? 2) If it instantly hits after it gets announced, would you be okay with giving the crew couple of minutes so they get prepared to fix it and for the shuttle to not be called. Maybe add an ETA onthe announcement.

1 -- A few seconds of warning is given, but by the time the announcement is made the meteor is already flying towards the station. Just enough time is given to move away from windows and to mobilize engineers for a potential breach.

2 -- Preparation time would probably end up being unnecessary for the purposes of this event, since the damages from a single meteor likely aren't enough to warrant a shuttle call unless it hits something REALLY important. Even if you knew where it was going to hit, there's little you can do to really mitigate a meteor impact before it occurs.

That being said, giving some prep time when it comes to meteor _waves_ as well as some more robust portable shields could make them a bit more interesting. Having the opportunity to pick two or three specific areas to secure against a wave before it hits could introduce some strategy to meteor waves beyond "cover your ass and pray it doesn't hit anything important". But alas, that is an idea best left until after this one gets out the door.

**Comment by Shadowflame909** [comment]
yummy carppopsicle. Chef's gonna love this!

**Comment by Mothblocks** [comment]
> Too much destruction in too little time

more proof reconstruction being terrible is one of the biggest problems of ss13

**Comment by moocowswag** [comment]
> 2. Happens instantly and you can't prepare for it.

From what i can tell, if the station has meteor shields as an objective there is a higher chance of meteors spawning, i lost count of the amount of timed i ghosted after being screwed over by meteors/shuttle call from meteors and then read the note on the bridge saying station shield was the objective.

**Pull request merged**
