### PR TITLE
Krav Maga Implementation 2: Krav Maga for the traitor uplink

### PR DESCRIPTION
**Pull request by PKPenguin321**
The implant and the gloves are available. The gloves are a traitor variant that are disguised like normal black gloves.

See #16843 for more info on Krav Maga.
See https://github.com/tgstation/-tg-station/pull/16945 for part 1.

:cl: PKPenguin321
rscadd: Traitors can now order Krav Maga gloves and implants from their uplinks.
/:cl:

### CODE REVIEW

**Comment by Zilenan91** [comment]
Can we not give traitors an item that lets them deal with crowds

**Comment by Bawhoppen** [comment]
traitors DO NOT NEED MORE STUFF OKAY 
THIS IS REDUDANT

**Comment by PKPenguin321** [comment]
hm
i did not think the whole "build off the last branch" thing through all the way, this still gives gloves to sec officers

**Comment by Robustin** [comment]
I still have PTSD from the wrestling belt. I saw Krav Maga in action at Thunderdome and it was just another obtuse "LOL U GOT FUKT" melee system. At least carp made you forsake ranged weaponry, we don't need more martial arts memes.

**Comment by PKPenguin321** [comment]
okay new plan, close this for now. if part 1 gets merged, open it with JUST the traitor uplink changes. if part 1 is closed, open it with the krav improvements and the uplink changes.

>Can we not give traitors an item that lets them deal with crowds

krav by itself is not good at dealing with crowds

**Comment by PKPenguin321** [comment]
@Robustin 

>I still have PTSD from the revolver. I saw the revolver in action at Thunderdome and it was just another obtuse "LOL U GOT FUKT" gun system. At least the ebow made you forsake high ranged damage, we don't need more lethal gun memes.

>I still have PTSD from the ebow. I saw the ebow in action at Thunderdome and it was just another obtuse "LOL U GOT FUKT" gun system. At least the esword made you forsake ranged stuns, we don't need more stun gun memes.

>I still have PTSD from the esword. I saw the esword in action at Thunderdome and it was just another obtuse "LOL U GOT FUKT" melee system. At least the stun baton made you forsake high melee damage, we don't need more lethal weapon memes.

>I still have PTSD from the stun baton. I saw the stun baton in action at Thunderdome and it was just another obtuse "LOL U GOT FUKT" melee system. At least the esword made you forsake guaranteed melee stuns, we don't need more lethal stun memes.

**Comment by Core0verload** [comment]
Krav Maga really fits the traitor uplink better than sec locker.

**Pull request closed without merging**
