### PR TITLE
Removes the headpatting code and the slapping code

### PR DESCRIPTION
**Pull request by optimumtact**

### CODE REVIEW

**Comment by kevinz000** [comment]
ORRRAAAANNNGGGGEEESSSSSS!!!!

**Comment by Bawhoppen** [comment]
he's gonna selfmerge then he'll have won the codebase

**Comment by Bawhoppen** [comment]
that is, unless we stop him now

**Comment by Shadowlight213** [comment]
Good pr

**Comment by ShadowDeath6** [comment]
This was his plan all along

**Comment by Iamgoofball** [comment]
coderbus_closed

**Comment by InsaneHyena** [comment]
Remove weeb

**Comment by FantasticFwoosh** [comment]
Im not horribly invested to see it go or stay eitherway, patting is nice but its a waste of a emote.

**Comment by The-clown-known-as-Pepe** [comment]
>removing harmless features most of the playerbase uses that do not impact game balance

how about no

**Comment by Limski** [comment]
STOP NERFING CATGIRLS

**Comment by RemieRichards** [comment]
My finger slipped again.
I sure am clumsy.

**Comment by obscolene** [comment]
why is this testmerged

**Comment by lzimann** [comment]
24h at least

**Comment by optimumtact** [comment]
Happeing

**Comment by ChangelingRain** [comment]
unhappen

**Comment by optimumtact** [comment]
I've removed slapping as well

**Comment by lzimann** [comment]
This is happening. If anyone wants it back, readd as an emote, or even use the already existing custom emote, that lets you do anything you want. This is a snowflake check, I should've denied it the first time and moved on.

**Comment by vcordie** [comment]
>removing harmless features that most of the community like
I have a feeling someone's not going to get re-elected.

**Comment by optimumtact** [comment]
maintainers are picked, not elected

**Comment by ChangelingRain** [comment]
_pets oranges_

**Comment by Shadowlight213** [comment]
Joan closing a revert of code they merged, violating rules.
Also, conflict of interest as they sit in the petting irc channel

**Comment by optimumtact** [comment]
Scandulous, Joan is a lorebus puppet!

**Comment by VeryRealAccount** [comment]
no fun allowed

**Comment by RocKeD** [comment]
I never use these but why remove features that don't impact gameplay?

**Comment by optimumtact** [comment]
for fun

**Comment by Limed00d** [comment]
why would you do this

**Comment by optimumtact** [comment]
for fun

**Pull request merged**
