### PR TITLE
Lowers the bar for Disk, Please!

### PR DESCRIPTION
**Pull request by Ryll-Ryll**
## About The Pull Request
Back in #48094 I added an achievement, Disk, Please! for:

- Being a Nuke Op
- Having a loaded rocket launcher
- Finding the Captain conscious
- Hold the Captain up

Only now as I'm writing this do I realize I never actually added the damn check to see if they were actually holding the nuke disk, oops! Despite this, a while back atlanta ned told me no one had even gotten this achievement, which is sad. So I've changed the requirements: You now have to hold up any conscious non-nukie who has the disk with the loaded launcher. Sure it's a bit easier to cheese since it need not be the Captain, but this is more interesting anyway.

## Why It's Good For The Game
I wanna see someone get this

## Changelog
:cl: Ryll/Shaps
tweak: The "Disk, Please!" achievement will now be granted to any nuclear operative who holds up any conscious non-nukie holding the disk, rather than needing the Captain. Good luck!
/:cl:

### CODE REVIEW

**Comment by WarlockD** [comment]
The real problem I have with this is that all nukies need to do is hold up everyone to check if they have the disk.  No achievement, they don't have the disk.  On the other hand there is no way to get the achievement otherwise humm.

**Comment by ArcaneDefence** [comment]
>The real problem I have with this is that all nukies need to do is hold up everyone to check if they have the disk.

They have a literal pinpointer program to locate the disk.

**Comment by WarlockD** [comment]
Well I retract my message.  I don't play nukies much hah

**Comment by PKPenguin321** [comment]
I mean, *hypothetically* you could still game it if you somehow lost your pinpointer but still had a rocket launcher on you, but that's such a non-concern

**Comment by TheVekter** [comment]
> 
> 
> I mean, _hypothetically_ you could still game it if you somehow lost your pinpointer but still had a rocket launcher on you, but that's such a non-concern

I could be wrong but I don't even think you get achievements until after the round ends.

Plus... You're a nukie, I mean. If you think they have the disk, apply shotgun.

**Pull request merged**
