### PR TITLE
Revert "Changeling Rebalance: Kill It With Fire, feat. Armblade Rework"

### PR DESCRIPTION
**Pull request by optimumtact**
Closes #83841
Closes #83843

### CODE REVIEW

**Comment by sylvia-from-fulp-station** [comment]
armblade
never forget what they took from us

**Comment by Sadboysuss** [comment]
yes.

**Comment by Astrogem2** [comment]
I really do think its was too much at once and too much being changed. Removing things isn't always the best idea to make people change. Add different appealing options to make people change what they choose, or split off what's already too powerful in one into separate things.

**Comment by optimumtact** [comment]
The timeline of the whole original PR is fucky so i'm calling a mulligan, this is reverted, but the PR can explicitly be reopened for further scrutiny by maintainers.

**Comment by nukularpower** [comment]
just steal the goon ling instead of agonizing over 10 different equally bad ways to "fix" it imo

**Pull request merged**
