### PR TITLE
Adds a new attack to the Legion megafauna.

### PR DESCRIPTION
**Pull request by nemvar**
## About The Pull Request

Adds a new attack to Legion: Summon Sentinels!

When the legion performs this attack, it spawns up to three legion sentinels nearby. These sentinels disappear after two minutes.

What is a legion sentinel? A legion sentinel is a kind of turret structure that shoots every ~4 seconds at all nearby mobs that don't share a faction. The beam pierces everything but the sentinel itself can't see through walls. It is also highly telegraphed by shooting a tracer 0.4 seconds into the same direction as the actual projectile will go before it will shoot. The sentinals themselves don't get damaged by this beam, but big daddy legion and his other underlings do.

## Why It's Good For The Game

The legion fight is extremely boring because the boss itself doesn't do much. This will hopefully slightly spice up the encounter. Now you have to be careful to not get overwhelmed by the sentinels, but very skilled miners may use them to destroy the small legion skulls by baiting them into their projectiles.

This hopefully increases the challenge that this fight poses, especially after the legion has split into multiple skulls.

## Changelog
:cl:
add: A new attack has been added to the legion megafauna.
/:cl:

### CODE REVIEW

**Comment by wesoda25** [comment]
video

**Comment by tralezab** [comment]
the sprite looks good but it's very hard to tell that it is a stationary thing.

**Comment by nemvar** [comment]
https://www.youtube.com/watch?v=lmtC1qw0R78&feature=youtu.be

I don't have any footage of me actually trying to beat the boss. It's recommended that you turn off the sound, I messed up while recording.

**Comment by HomocidlePancakes** [comment]
Legion crusher trophy when?

**Comment by ATH1909** [comment]
The time between the tracers and the actual shots seems really short. Is it even possible to properly react to them (instead of just blindly moving around constantly (as people already do, no?) and hoping that they don't hit you) within 0.4 seconds? I dunno, maybe I'm just not enough of a pro gamer/miner.

**Comment by nemvar** [comment]
You're right. Even with this change I'm really unhappy with how the fight plays out and it's even more sluggish. Back to the drawing board.

**Comment by Michael-Ashfield** [comment]
I would be careful about increasing the difficulty as Legion currently stands as a decent 'stepping-stone' fauna, something which newer miners can actually take on. Rebalancing them to make them ultra hard like the Drake and Bubblegum just blocks off more content and would make less people want to learn mining.

**Comment by nemvar** [comment]
In my vision of legion, it would be a scale between difficulty and reward. Something like being able to kill it much faster if you fight multiple skulls at once but it also being proportionally harder.

Here's my current 'design doc' for it.
Remove one size from legion. The fight is way too repetitive. Slighly increase HP. Slightly alter the size of the sprites. Biggest size is WAY too big for it's own good and smallest just looks cramped.
Each size gets it's own mechanics.
Size 5: REMOVED
Size 4: Gets two appendeges tethered to it. Terraria style. One will shoot projectiles and skulls, the other one will lash out at the player. They can't move further away than 5/6 tiles from the main boss. Around 400 HP (not that much really). The big boss usually tries to maintain some distance, but will sometimes go in for a melee attack. Otherwise it doesn't do much.
Size 3: Loses the arms. This is the 'ranged' phase. The legion tries to maintain some distance from the player and keeps spawning turrets/skulls.
Size 2: It goes all in. It will try to charge most of the time and sometimes throws itself at the player. If not charging, it will quickly spawn a skull.
Size 1:  The smallest size will do nothing but spawning skulls, but it can spawn up to 2 to of them per attempt. If the spawned skulls die, it will take damage.

If you damage one of the main boss pieces while another one is nearby, the second skull will take around 25% of the damage.

All of this is so the fight is more varied and to reward miners that manage to fight multiple skulls at the same time. You can get an easier fight by seperating the boss, but it's also going to be slower.

**Comment by ishitbyabullet** [comment]
we have advanced from dungeon guardian to skeletron if this PR idea ever gets made.

**Pull request closed without merging**
