### PR TITLE
[READY] [TESTED] Fusion Rework Episode V: The Phantom Fusion

### PR DESCRIPTION
**Pull request by mirrorcult**
for more detailed info on this pr see #37756 
also I am very sorry for not getting this out faster

:cl: cyclowns
add: Fusion has been re-enabled! It works similarly to before, but with some slight modification.
tweak: Fusion now requires huge amounts of plasma and tritium, as well as a very high thermal energy and temperature to start. There are several tiers of fusion that cause different benefits and effects.
tweak: The fusion power of most gases has been tweaked to allow for more interesting interactions.
tweak: BZ now takes N2O and plasma to create, rather than tritium and plasma.
fix: Fusion no longer delivers server-crashingly large amounts of radiation and stationwide EMPs.
/:cl:

[why]: Fusion is a really interesting reaction at its core and it's a little sad to see it get disabled because of all the dumb broken shit that came along with it. This PR plans to fix those issues and make the interactions a little more interesting, while also gathering player feedback. Here's some explanation for the individual changes I've currently made (that are different from the last pr at #37756, see that one for more indepth changes)

- Changing various gases fusion power
While this looks like a huge deal, because of the way that power ratio is calculated, a gas' ability to accelerate fusion is more about the fusion-power-to-specific-heat ratio rather than its fusion power (I wanna change this, but thats for another day). This means pluoxium is relatively bad (1/8 ratio), stimulum is really good (7/5 ratio) and BZ is up there (3/4 ratio).

- Addition of a fourth fusion tier above high (super)
More interesting interactions, especially now that power ratio is uncapped. Also wanted another way to generate good amounts of stimulum and pluoxium, but this may end up changing to different gases or other benefits in the future. This might be a bit *too* good but it's hard to get to 50 power ratio without either of those anyway.

- New sounds for fusion!
fun, also gives actual feedback for when a fusion reaction happens. Shouldn't be annoying since fusion reactions almost never happen in chains and it only occurs when radpulses are released.

- Changes to the way radpulse power is calculated
I decided to include another !!FUN!! graph. This time its a rational function rather than linear so I can utilize horizontal asymptotes. The problem with old fusion is that radiation could go super fucking high, but now its capped to 30000 (since its multiplied by 2 for super reactions, could change in the future). Graph is at https://www.desmos.com/calculator/j5h7d4cfen.

- General tweaking of defines
Mostly just to reduce insane temperatures, might end up upping the reaction energy defines in a future PR but we'll see how it turns out.

I'm not going to abandon this assuming this actually gets merged. If shit's borked, please make an issue and @ me so that I can do some minor reworks. I already have stuff that I want to do, but will do at a later date so that this isn't even more of a stupidly long overhaul that no one cares about.

Also a testmerge would be cooooooooooooool

### CODE REVIEW

**Comment by praisenarsie** [comment]
The Phantom Fusion

**Comment by DaxDupont** [comment]
Not again

**Comment by MrDoomBringer** [comment]
shouldnt this be titled "episode V"?

**Comment by Dorsisdwarf** [comment]
Uh, 30 kilorads is a really gargantuan amount of radiation isnt it? like ultra-mega never-going-to-decontaminate-because-it-instantly-irradiates-the-shower-and-anything-nearby big

**Comment by praisenarsie** [comment]
@MrDoomBringer it should be and i'll make sure he changes it

**Comment by cyclowns** [comment]
@praisenarsie fine >:(

@Dorsisdwarf 30 kilorads is a LOT of radiation, but you have to consider:
- the fact that its still an order of magnitude less than old fusion
- how hard it is to feasibly get that amount of rads
- super fusion is meant to be ridiculously dangerous
- its going to be hard to utilize the rads as a weapon since basically everyone is alerted that you're doing it from the shockwave

**Comment by praisenarsie** [comment]
watch it lag the server

**Comment by KomradeSpectre** [comment]
Watch Lane make this PR get unmerged within a week with his antics.

**Comment by cyclowns** [comment]
if i cant figure out a way to break this and i'm the fool that made it i dont think anyone else can

**Comment by Cyprex** [comment]
>if i cant figure out a way to break this and i'm the fool that made it i dont think anyone else can
Famous last words.

**Comment by AlexTheSysop42** [comment]
Does the burn sim still cause fusion?

**Comment by cyclowns** [comment]
if you read this PR or the old PR's body at all you would find that it doesn't
the reqs have been changed back to plasma and tritium instead of plasma and carbon dioxide, and it requires a lot more plasma and tritium than the burn sim could provide

**Comment by AlexTheSysop42** [comment]
oh plasma and trit instead of plasma and CO2, didnt notice

**Pull request merged**
