### PR TITLE
Micro-optimize TGUI_CREATE_MESSAGE for 70% (?) speed ups

### PR DESCRIPTION
**Pull request by Mothblocks**
## About The Pull Request
Disclaimer: I don't know how to do math, not sure if that number is correct.

image

Hardcodes in the URL+JSON encoding of type, as it should be consistently a string.

Adds a unit test to ensure the behavior works.

## Why It's Good For The Game
`send_message` is consistently one of the hottest procs in terms of overtime and such. This change should, at least somewhat, help that. Whether or not this is the main bottleneck in `send_message`, I'm not sure.

### CODE REVIEW

**Comment by Mothblocks** [comment]
image

What the fuck

**Comment by SplinterGP** [comment]
> 
> 
> image
> 
> What the fuck

image

**Comment by LemonInTheDark** [comment]
We should do a testmerge to split send_message up into bits so we can see where the cost actually is

**Comment by stylemistake** [comment]
Really cool, mothblocks!

Here's a few ideas:

1. What if instead of urlencoding, tgui was base64-encoding? This would save a lot of bytes (1.14x size in base64_encode vs 3x size in urlencode), and potentially faster because rust_g.
2. Another potential way to micro-optimize is to feed comma separated `[type],[payload]` into the output, since based on BYOND documentation, when separating values with comma, browser function gets called with multiple arguments.

**Review by stylemistake — APPROVED** [review]

**Comment by Mothblocks** [comment]
> Another potential way to micro-optimize is to feed comma separated [type],[url_encode(payload)] into the output, since according to BYOND documentation, when using a comma separator, browser function gets called with multiple arguments.

I imagine that'll be as fast as this, but actually readable, so I can definitely look into that.

> What if instead of urlencoding, it was base64-encoded? This would save a lot of bytes (1.14x vs 3x in urlencode), and potentially faster because rust_g (or slower because it's a dll call).

I'm skeptical that it would still be faster after going through the DLL boundary, but we can try it.

**Comment by Mothblocks** [comment]
Actually, if you're approving this, I'll just stick with this and we can look at the other improvements later. 😄

**Pull request merged**
