### PR TITLE
Creampie changes

### PR DESCRIPTION
**Pull request by ghost**
Regular creampies do not stun (syndicate pie-cannon pies still stun as normal). The clown's crate now has 25 creampies in it, up from 1.

Clown gets more prank gear, less combat gear.

:cl:
balance: Standard creampies do not stun. The clown's crate now has 25 creampies.
/:cl:

### CODE REVIEW

**Comment by kriskog** [comment]
Should just move the stun to the pies shot by the normal cannon, as carrying that bulky thing around takes up lots of useful space. I will miss pullin a pie out of my pack on pursuing sec when tiding though, nothing riles them up more.

**Comment by wesoda25** [comment]
Maybe just a one second knockdown with no item drop?

**Comment by MCterra10** [comment]
Pies don't need to lose the stun, just rest to dodge it if you're a proper gamer

**Comment by Tlaltecuhtli** [comment]
you can catch pies and throw them back

**Comment by Iatots** [comment]
Why would you think the two pies that spawn on station are the problem and not the taser-light cannon?

**Comment by HomocidlePancakes** [comment]
:joy: HE :joy: DIED :joy: TO :joy: A :joy: CREAMPIE :joy:

**Comment by py01** [comment]
I like #47777 47777

**Pull request closed without merging**
