### PR TITLE
[s] Puts a limit on atoms teleportable by a pad per teleport

### LINKED ISSUE #38399: Briefcase teleporters have no limit on how many items they can teleport at a time, and can absolutely destroy the server.
[Round ID]: # 89253

[Reproduction]: # Buy briefcase teleporter. Put a large amount of items on it. Teleport them back and forth, and watch the server freeze for increasing amounts of time. It's likely due to the massive amount of sparks this creates rather than the teleporting itself, so maybe it's fixable by just reducing the sparks to 1 per teleport, instead of 1 per item?

This was discovered in VR where a syndie research thingy person brought a couple hundred carp and were teleporting them back and forth until they were found and deleted. I don't even think this stuff is logged.

### PR DESCRIPTION
**Pull request by DaxDupont**
[Changelogs]: # (Your PR should contain a detailed changelog of notable changes, titled and categorized appropriately. This includes, new features, sprites, sounds, balance changes, admin tools, map edits, removals, big refactors, config changes, hosting changes and important fixes. An example changelog has been provided below for you to edit. If you need additional help, read https://github.com/tgstation/tgstation/wiki/Changelogs)

:cl: Dax Dupont
fix: Puts a limit on atoms movable at once by telepad.
/:cl:

[why]: Fixes #38399
Seems like the best solution without refactoring do_teleport. Not only that moving a fuckton atoms at once probably has more than one potential downside.

Number negotiable.

### CODE REVIEW

**Comment by DaxDupont** [comment]
@KorPhaeron maybe but a limit is sensible as well for now, seeing I am worried about other things that will lag if teleported en masse.

**Comment by ExcessiveUseOfCobblestone** [comment]
Not a fan of the bandaid here, I think the do_teleport arg is more of a root-cause (and easy) remedy

**Comment by SpaceManiac** [comment]
Agreed. Let's try just moving the spark creation outside the loop, and only put an atom limit if that still isn't enough.

**Review by SpaceManiac — CHANGES_REQUESTED** [review]
Agreed. Let's try just moving the spark creation outside the loop, and only put an atom limit if that still isn't enough.

**Comment by DaxDupont** [comment]
Then it becomes not my problem.

**Pull request closed without merging**
