### PR TITLE
Justice Enforcer Security Crate

### PR DESCRIPTION
**Pull request by MMMiracles**
So apparently this magnificent helmet (made by dannos I think) was added awhile ago, and has seen slim in-game use. This adds a crate to the manifest for when security really needs to get their LAW on.

:rotating_light:Example of proper law enforcement:rotating_light:
justiceserved

The crate comes with 1 siren helmet and 1 sechailer for 30 points, security access-locked. It'd cost cargo 150 points to supply an entire 5-man security team with these incase cargo feels generous and security feels extra special that day. Combine with sec segways to become the ultimate security task force.

### CODE REVIEW

**Comment by Dorsisdwarf** [comment]
Try 20 points, 30 points means that helmet is more expensive than four/five energy guns or six lasers

**Comment by MMMiracles** [comment]
Price helps prevent the abuse of half the crew running around in them for non-stop "WEEWOOWEEWOOWEEWOO"

**Comment by SconesC** [comment]
yeah these helmets are OBSCENELY annoying and I think it's best that we never see them

**Comment by Anonus** [comment]
WEEWOOWEEWOOWEEWOO

**Comment by Boggart** [comment]
For extra ~~pain~~ fun, put one on your head, hold one in each hand and turn them all on.

**Comment by MMMiracles** [comment]
As of right now unless cargo is just swimming in points, I doubt a competent QM/cargo staff would be willing to throw more than 30+ points at security for a gimmick item.

**Comment by MMMiracles** [comment]
honkhonk

**Comment by Steelpoint** [comment]
This is pretty nifty actually, and the high cost means it won't be easily spammable.

**Comment by OhEmGee** [comment]
w e e o o o b o y s

**Comment by Cheridan** [comment]
still better than sechailers

**Pull request merged**
