### PR TITLE
Fixes syndicate mobs not attacking unconcious people

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
@Shadowlight213 forgot to set robust_searching when he changed their stat attack.

Also makes faithless attack people in crit.

### CODE REVIEW

**Comment by Shadowlight213** [comment]
@KorPhaeron I knew about this, but was actually holding off on fixing this until I got around to trying to make them prioritize living people. From observations of var editing it on, I found that while attacking people in crit, they would ignore conscious players and make themselves easy targets.

**Comment by KorPhaeron** [comment]
@Shadowlight213 

Someone actually added code a while back that makes mobs swap targets if they're being hit so you can't kite them, so they should still be able to defend themselves

**Comment by lzimann** [comment]
why :(

**Comment by dumpdavidson** [comment]
nerf to healing virus. i like it.

**Pull request merged**
