### PR TITLE
berserker hardsuit now has mining suit levels of explosive protection

### PR DESCRIPTION
**Pull request by Fikou**
## About The Pull Request

ok this might have been a dumb decision

## Why It's Good For The Game

you wont gib from gibtonite because you decided to take some loot anymore

## Changelog
:cl:
balance: berserker hardsuit now has mining suit levels of explosive protection
/:cl:

### CODE REVIEW

**Comment by Cyprex** [comment]
Replace "now has" with "buffed to"

**Comment by Fikou** [comment]
why

**Comment by Winterous** [comment]
Wow it has some pretty shit protection, I thought it was a subtype of the ERT suit for some reason.

**Comment by Fikou** [comment]
lol

**Comment by BYONN** [comment]
This seems nice, as Winterous said, it does have shit protection (I mean it's the same as the mining suit, but it's spaceproof, no slow down, and fireproof, but can't upgrade melee protection)
I was kind of mad about the melee protection, until I put on the hardsuit and engaged the helmet. Apparently you get a new ability called Berserk, and it passively gains charge I believe. If it's fully charged you can use the Berserk mode and get both fast attacking and walking speed, a melee protection bonus (50), and noslips, judging from the code.
One think I don't like is the fact that you can't use guns anymore when using berserk. Considering this is mining loot, and there are miners who mainly use PKAs (l ike me), it's good if you want to run away or you primarily use the crushers

**Comment by Winterous** [comment]
Oh, it was reworked, and it did used to be a subtype of ERT. You successfully bamboozled me Fikou.

**Pull request merged**
