### PR TITLE
New Null Rod Sprites

### PR DESCRIPTION
**Pull request by Mey-Ha-Zah**
## About The Pull Request

Updates a few Null Rod sprites, and few non null rod sprites, including the Supermatter sword.
image

## Why It's Good For The Game

Old sprites give me a headache, so does doing inhands, which I will get around to, but at least the icon sprites look better.

## Changelog
:cl:
image: Updated several Null Rod Graphics. Also updated: the supermatter sword.
/:cl:

### CODE REVIEW

**Comment by carlarctg** [comment]
The new SM sword sprite ruins the initial joke, that it 'stands perfectly balanced on its hilt', because it looks diagonal.

https://camo.githubusercontent.com/93ffbec613f42833e9435dfc22adb67b378be3c62f5001a71fb97561d4f25127/68747470733a2f2f696462322e616666656374656461726330372e636f2e756b2f696d616765732f32353836323339392f37363036312f31313336353736383838323737383739393130302e676966

Also, it looks more like a flaming sword than a supermatter one? The supermatter itself doesn't flicker red and yellow 

https://camo.githubusercontent.com/63687528b33bbf4fe2e43e0823177b0d0c6a35df449447b215f80b845464a795/68747470733a2f2f696462322e616666656374656461726330372e636f2e756b2f696d616765732f32353836323339392f37363036312f323637373538383938323733343937353133362e676966

https://camo.githubusercontent.com/8b2651d3e244a0e2357051d3476133954767c80fa87177f02f689efe5a90d0c8/68747470733a2f2f696462322e616666656374656461726330372e636f2e756b2f696d616765732f32353836323339392f37363036312f363639383237353535383536323337323233392e676966

The moonlight greatsword resprite... Honestly just seems like a downgrade. It turns it from a 'Greatsword' to a shortsword with a long hilt. It also loses its blade runes and flickers slowly.

https://camo.githubusercontent.com/29b2f9362e2be2697e5e6500f03731e4208a1bef2f900930fded38e4bc22de9b/68747470733a2f2f696462322e616666656374656461726330372e636f2e756b2f696d616765732f32353836323339392f37363036312f31353835383337313235323539343433373238352e676966

https://camo.githubusercontent.com/f4579754f558a19562ccdb8a4b8785c09eb9f2a579cced1a3fdb894676794cf7/68747470733a2f2f696462322e616666656374656461726330372e636f2e756b2f696d616765732f32353836323339392f37363036312f31313532303836373339303738353730393536392e676966

Similar with the extradimensional blade. Though the blade size isn't decreased, the large handguard makes the blade overall look tinier and again more like a shortsword. Perhaps look into 64x64 sprites to get the feel you're looking for? This isn't an issue with the back sprite though.

https://camo.githubusercontent.com/2198c691e7abe243ba8c2c20303a919e9fad96402a5ba5e0f9fdc513075625f3/68747470733a2f2f696462322e616666656374656461726330372e636f2e756b2f696d616765732f32353836323339392f37363036312f31313236333230343832313632323839373433372e706e67

https://camo.githubusercontent.com/a66f33ae4b660354950753aacdd0a37080ad49f756868a6e22018df63ff4030f/68747470733a2f2f696462322e616666656374656461726330372e636f2e756b2f696d616765732f32353836323339392f37363036312f363039323730363736343633373934323730372e706e67

The hammer just seems.. less interesting, with flatter colors, less contrast, turning the texture of silver snd gold into dull grey and bland yellow.

As a nitpick, the pitchfork's new red feels more pink than anything and doesn't feel very infernal.

I'm sorry for so many criticisms, I just want this to be the best it could be and reduce the amount of players that will shit their pants about change bad. The rest of the sprites look excellent, great job.

Apologies for the link spam, I'm on mobile. I'll put real images in when I get to the computer.

**Comment by Mey-Ha-Zah** [comment]
I can address the SM Sword, but as for the others, it's a matter of preference. I did what I liked and I had fun doing it. (Up until inhands)

**Comment by MrMelbert** [comment]
I think a lot of the sprites look pretty cool but I will agree that the Moonlight Greatsword / Force Weapon looks really blurry now, like I'm missing my glasses.

**Comment by Fikou** [comment]
i think the new katana (you didnt mention you changed that), moonlight greatsword, supermatter sword, god staves and bo staff are downgrades, even if their previous sprites weren't very good

**Comment by DATA-xPUNGED** [comment]
The new katana is lovely, def gonna use that more often. The blue glowing sword's hilt looks like a downgrade though

**Comment by Mey-Ha-Zah** [comment]
Wish is my command, new SM sword spawns on its hilt, but these damn things topple so easy, you can never get it standing straight again.

image

**Comment by Thunder12345** [comment]
> Wish is my command, new SM sword spawns on its hilt, but these damn things topple so easy, you can never get it standing straight again.
> 
> image

Just make a vertical sprite in the first place, rotating the diagonal sprite looks horrible because of all the displaced pixels, most noticably the hilt is absolutely mangled.

**Comment by Mey-Ha-Zah** [comment]
> > Wish is my command, new SM sword spawns on its hilt, but these damn things topple so easy, you can never get it standing straight again.
> > image
> 
> Just make a vertical sprite in the first place, rotating the diagonal sprite looks horrible because of all the displaced pixels, most noticably the hilt is absolutely mangled.

uggggghhh I don wanna....
ALright I'll do it, give me a few days cause I have other stuff that requires my attention at the moment.

**Comment by moocowswag** [comment]
Keep in mind floor sprites tend to be larger and exaggerated compared to in-hand sprites, esp for tools and weapons,

Because of this its hard to tell how large a “greatsword” should be when on the floor

**Comment by Serxule** [comment]
can you show all the sprites? since you've apparently changed more than what is shown and that (imo) seems deceptive

**Comment by Mey-Ha-Zah** [comment]
I've updated the SM Sword to now have a Spawn Sprite (Vertical) and the Diagonal sprite for wielded.

**Pull request merged**
