### PR TITLE
Removes tramstation from the map rotation.

### PR DESCRIPTION
**Pull request by ANAME593**
removes tramstation
## About The Pull Request
removing tramstation from the game.
## Why It's Good For The Game
i can say for certain that tramstation is a heavily hated map that nobody really likes. not just that but whenever it's tram the pop goes down, I think the lack of love for tram makes it eligible for removal there is no reason to have a map that quite literally nobody likes at all.
## Changelog
:cl:
del: Tramstation has been removed from the map rotation
/:cl:

### CODE REVIEW

**Comment by ANAME593** [comment]
if this gets 10 dislikes i will close it, i didn't realize people actually like tram.

**Comment by MrrFiish** [comment]
Horrible PR everyone loves tram this BETTER not be merged.

**Comment by LemonInTheDark** [comment]
We keep things for a reason. Tram makes some people upset because of eh idk any number of things, but if we didn't want it that bad it would have been punted long time back. Especially cause the guy who made it is still around and working on it. Hard to kill something when it's changing with time

**Comment by ANAME593** [comment]
I thought it was a map the playerbase hated, turns out im wrong hence the PR.

**Pull request closed without merging**
