### PR TITLE
Makes spawned hot cross buns edible again

### LINKED ISSUE #57135: Couldn't eat hot-cross bun
Reporting client version: 513.1539

## Round ID:
[156963](https://scrubby.melonmesa.com/round/156963)

## Testmerges:
- [Tramstation: choo choo MORE MAP COMIN' THROUH](https://www.github.com/tgstation/tgstation/pull/56509)
- [Experi-Sci: Techweb nodes may now require you to perform "scientific" experiments](https://www.github.com/tgstation/tgstation/pull/54093)

## Reproduction:
1. Click self with hot-cross bun
2. Hit self with hot-cross bun

Other food items were fine

### PR DESCRIPTION
**Pull request by cacogen**
## About The Pull Request

Fixes #57135. 

You no longer hit yourself in the face with these. 

Also does the following:
- Formats the taste list properly (so it doesn't taste indescribable)
- Fixes grammar in name and desc
- Adds BREAKFAST foodtype
- Adds pastry taste
- Makes it require a bread slice rather than a whole loaf (not economical)
- Moves it to the bread category

## Why It's Good For The Game

You can eat spawned hot cross buns.

## Changelog
:cl: cacogen
fix: Spawned hot cross buns (e.g. one in cafe on MetaStation) are edible again
balance: Hot cross buns now use a bread slice instead of a loaf of bread (more economical)
/:cl:

### CODE REVIEW

**Comment by ilikesaying** [comment]
no context

**Comment by RaveRadbury** [comment]
Sliced meats and sliced watermelon are also failing to get the edible component, any chance you could look at those, cacogen?

**Comment by Pugie** [comment]
you look like you could use a pork bun

**Comment by cacogen** [comment]
@RaveRadbury 

I'll have a look for the GBP, but if it's anything like the issue with butchering not adding the edible component I won't know how to fix it.

**Comment by cacogen** [comment]
@RaveRadbury 
I sliced a watermelon and all the slices were edible. A slice I spawned wasn't, though. I sliced a piece of edible meat and all the cutlets were edible. Spawned cutlets of the same type were edible, too.

Your issue might've been fixed.

**Comment by cacogen** [comment]
@Qustinnus 
Is this the correct way to fix this? I've noticed some items are edible even without food_reagents set. Hot cross buns have the edible component.

**Comment by LemonInTheDark** [comment]
For my own benefit could you explain what exactly was breaking the edibility here?

**Comment by cacogen** [comment]
With this and the watermelon slices, all it took to make them edible was to give them food_reagents.

**Comment by LemonInTheDark** [comment]
I'm just gonna pray there's nothing else like this

**Comment by LemonInTheDark** [comment]
Oh also document the bread slice thing, if you could update the wiki page that'd be pretty based

**Comment by cacogen** [comment]
Shit I'd forgotten about the wiki. I"ll do that.

**Comment by LemonInTheDark** [comment]
:)

**Comment by cacogen** [comment]
Adding the hot cross bun to the wiki page made me realise this should've been made from a bun. Think these were added before buns were.

**Comment by cacogen** [comment]
Actually, the buns we have are hamburger buns. Based on Wikipedia, these are a type of sweet roll which are different to pastries so the pastry base wouldn't make sense either. I'll stick with sliced bread.

**Pull request merged**
