### PR TITLE
Re-adds previously merged beret sprite changes.

### PR DESCRIPTION
**Pull request by pireamaineach**
Head.dmi was rebased for, "Mime Trickery." I'm willing to bet I fucked up head.dmi somehow, though it doesn't seem that way.
Mildly modifies the beret sprites, removing the divot seen in the side view of them, thus making them look less garbage. IconDiffBot for the changes.
:cl:
Tweaks the sprite of the berets.
/:cl:

### CODE REVIEW

**Comment by BuffEngineering** [comment]
Oh god I even checked and when I saw the french beret was red I thought it worked, my bad.

**Comment by optimumtact** [comment]
alright mate?

**Comment by pireamaineach** [comment]
> alright mate?

Well, I mistook the close button as a cancel comment button. 'Twould be in the right place.

**Comment by optimumtact** [comment]
I've had it happen to me.

**Pull request merged**
