### PR TITLE
Adjusts the cloning pod fluff text as per Cheridan's request

### PR DESCRIPTION
**Pull request by Iamgoofball**
16:40   Cheridan    holy fuck can we please add another "suddenly" in there

### CODE REVIEW

**Comment by BlueNothing** [comment]
I prefer it as-is.

**Comment by kilkun** [comment]
i think its a meme pr bluenothing

the double usage of "suddenly" is awkward

**Comment by Cheridan** [comment]
It's not a double usage, if you count the next line they use the word sudden FOUR times.

**Comment by GeneralGoose** [comment]
it doesnt look natural
may as well just put suddenly after each word

**Comment by ike709** [comment]
do it

**Comment by kilkun** [comment]
wew i didn't notice the second "sudden" in the first line

**Comment by Cheridan** [comment]
seriously though please rewrite it to not be dumb

**Comment by Cheridan** [comment]
seriously though!!

**Comment by Razharas** [comment]
>I was just pretending guise dont do this

Dont call in a grave, its a pr you endorsed

**Comment by Cheridan** [comment]
>razharas doesn't understand sarcasm because he was raised in a bitter, humorless land

:sob:

**Comment by optimumtact** [comment]
They expect one of the descriptions in the wreckage brother

**Pull request closed without merging**
