### PR TITLE
Adds logging to cutting down trees

### PR DESCRIPTION
**Pull request by kriskog**
## About The Pull Request
Its that time of year again, and people are cutting down christmas trees. Adds logging to cutting down trees, and an admin message if the tree is of the xmas variety.
I thought about putting it in the xmas subtype, but we delete src in the attackby proc so it gets a little awkward. 

## Changelog
:cl: Skoglol
admin: Cutting down (xmas) trees is now logged.
/:cl:

### CODE REVIEW

**Comment by wesoda25** [comment]
based as fuck

**Comment by PKPenguin321** [comment]
if people are flinging shit over this it's better for us to just remove tree cutting

**Review by 81Denton — APPROVED** [review]

**Comment by 81Denton** [comment]
Speed merging this since it's time sensitive and has caused major headaches for admins

**Comment by optimumtact** [comment]
why didn't you just make the xmas tree immune?

**Comment by kriskog** [comment]
Grinches genuinely enjoy cutting down christmas trees, why should we only cater to the other kind of people? Shit creates conflict, conflict is the name of the game.

**Comment by optimumtact** [comment]
because im not a grinch

**Pull request merged**
