### PR TITLE
Armour of Fate [WIP]

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
It rolls a d20 when hit, triggering some zany effect or another.

I only have about half the effects done, was hoping other people had good ideas for the missing rolls

### CODE REVIEW

**Comment by Anonmare** [comment]
How about a chance of mindswapping the hitter and the wearer?

**Comment by newfren** [comment]
At around 10 it should just do irrelevant bullshit - spawning butterflies, recolouring people, making everyone shout something, shitting toys everywhere, whatever.

**Comment by Lumipharon** [comment]
chance for the armour to change wearers to the attacker.
Chance for the attacker (or wearer) to get sucked into the armour for all time.
Chance for the weapon to explode on hit (arm exploding from punching would be great if dismemberment ever got done)
Chance to honk ineffectually on hit( the armour or the weapon)

**Comment by Jazaen** [comment]
No, on 10 summon something that makes everyone suffer. Lord Singuloth or Nar'sie maybe? Mindswitch would be good too, I suppose. Or maybe have it run switch minds event.

**Comment by AlexanderUlanH** [comment]
d20 on any hit no questions asked is a pretty disadvantageous system when that d20 has two options that instantly kill the wearer.  It could make more sense if higher hit damage made the die roll more unpredictable, where a 0 force hit would be a 10 almost every time, and a 100 force hit was likely to be either 1 or 20.

**Comment by Robustin** [comment]
>Armour

MY GREAT GREAT GREAT GREAT GREAT GRANDFATHER DIDN'T DIE FACE DOWN IN THE MUD AT BUNKER HILL SO THAT WE WOULD CONTINUE TO SPEAK THE KING'S TONGUE.

**Comment by KorPhaeron** [comment]
Working on too many things at once

**Pull request closed without merging**
