### PR TITLE
Cat men can now occupy all non-command roles

### PR DESCRIPTION
**Pull request by Supermichael777**
:cl: 
tweak: Cat men have finally achieved equal discrimination.
/:cl:

Now animus and lizards are equal.

If you have a complaint other then hating anime then please state it.

### CODE REVIEW

**Comment by TechnoAlchemisto** [comment]
cat people are disgusting

**Comment by TechnoAlchemisto** [comment]
also i hate anime

**Review by francinum — CHANGES_REQUESTED** [review]
Heresey

**Comment by optimumtact** [comment]
Sorry but mutants are dumb

**Comment by RemieRichards** [comment]
Gonna reopen this to give it a non-meme chance.

though @Supermichael777 removing the anti-mutant checks basically make this overrided proc useless, so you should remove this instance of it, that'd be need for a serious merge consideration

**Comment by Bawhoppen** [comment]
good we are a progressive codebase

**Comment by Dorsisdwarf** [comment]
no fuck off.

**Comment by KorPhaeron** [comment]
It makes sense to have them consistent with lizards

**Comment by Anonmare** [comment]
Remove genetrash from premises
God is a Human

**Comment by Iamgoofball** [comment]
# SLIPPERY SLOPE

**Comment by TechnoAlchemisto** [comment]
cat people were a joke and now it's gone too far

**Comment by Iamgoofball** [comment]
# I WARNED YOU ALL

**Comment by optimumtact** [comment]
Goof I'm deleting your posts because you keep using big text, please stop

**Comment by Iamgoofball** [comment]
But big text SLIPPERY SLOPE is tg culture

**Comment by ExcessiveUseOfCobblestone** [comment]
I knew as soon as I saw this thread the goofmobile would be coming soon.

**Comment by ExcessiveUseOfCobblestone** [comment]
It's Adam and Eve not Nyadam~ and Eats-The-Apples

**Comment by optimumtact** [comment]
@KorPhaeron @Cheridan this should be a config option for the server to decide on right?

**Comment by KorPhaeron** [comment]
@optimumtact 

Protect command roles from mutants or whatever is already a config option, and so is turning off cat people entirely, I don't think we need a third config to have cats as assistant only

**Comment by HankMoodyExperience** [comment]
feline creep

**Pull request merged**
