### PR TITLE
Peaceful Waypoint/Core Territory are now not completely reliable indicators of antag status

### PR DESCRIPTION
**Pull request by Mothblocks**
## About The Pull Request
When the shown threat (which is already unreliable) is below 20, it would choose either Core Territory or Peaceful Waypoint.

This exposed reliable meta information. If the report said "Core Territory", you can guarantee there are roundstart antagonists. If the report said "Peaceful Waypoint", you can guarantee there are not.

This has been changed to now have a 15% chance to show the *opposite* result.

## Why It's Good For The Game
With Dynamic under my lead, the report is meant to be something that gives you a good sense of what the round is going to be (it's inaccurate, but *usually* in the right area), but without ever exposing guarantee-able meta information.

## Changelog

:cl:
balance: The Dynamic report for Peaceful Waypoint/Core Territory no longer guarantees providing any meta information. Previously, "Core Territory" guaranteed there were roundstart antagonists, and "Peaceful Waypoint" guaranteed the inverse. There is now a 15% chance to show the opposite result, meaning you can use the report as a good guess of what is coming, but cannot rely on it.
/:cl:

### CODE REVIEW

**Comment by newfren** [comment]
the pr comment and the changelog say opposite things: one that peaceful waypoint used to guarantee no antags, one that core territory used to guarantee no antags.

**Comment by ATH1909** [comment]
isn't the point a greenshift supposed to be that it's safe for you to completely let your guard down?

**Comment by SkeletalElite** [comment]
> isn't the point a greenshift supposed to be that it's safe for you to completely let your guard down?

That is what the report was emulating, old secret green shift where it tells you off the bat there's no antags and then everyonee commits suicide because no one wants to play anymore

**Comment by Mothblocks** [comment]
> isn't the point a greenshift supposed to be that it's safe for you to completely let your guard down?

It was useless for this even before, since it only checked *roundstart* antagonists, but made no comment about midrounds, or even delayed antagonists like revolutionaries.

There's a better way to implement this that I've talked about in coderbus a lot, where if:

1. The threat is below any amount to spawn an antagonist (I believe this is 4, with thieves)
2. The paper reports this (the shown threat is not out of the 0-20 range)

...then it goes into green alert. Fikou and Melbert both showed interest in this.

**Comment by Mothblocks** [comment]
@newfren Good catch! Fixed.

**Comment by Dorsisdwarf** [comment]
I always thought that non-secret extended was a mistake so I'm glad to see this metatell fixed

**Comment by ExcessiveUseOfCobblestone** [comment]
reminder this paper sucks

**Pull request merged**
