### PR TITLE
Revert "Revert "Revert "Removes alien driveby"""

### PR DESCRIPTION
**Pull request by Firecage**
Reverts the Revert of the Revert.

### CODE REVIEW

**Comment by Agouri** [comment]
IS THIS SOME KIND OF JOKE

**Comment by Miauw62** [comment]
>agouri

**Comment by Steelpoint** [comment]
I'm Commander Shepard and this is my favourite PR in coderbus.

**Comment by Anonus** [comment]
WE'RE HAVING ISSUES, PLEASE STAND BY

**Comment by Ricotez** [comment]
increasethedecrease

**Comment by Aranclanos** [comment]
reeeeeeeEEEEEEEEEEEEEEEEEEEEEE

**Comment by Firecage** [comment]
Hey, atleast I am doing it properly Aran!

**Comment by Aranclanos** [comment]
ok back to square one

**Comment by peoplearestrange** [comment]
Aranclanos commented an hour ago

reeeeeeeEEEEEEEEEEEEEEEEEEEEEE (vert)

**Comment by CPTANT** [comment]
Get the fucking hint. Nobody wants your facehugger nerf.

**Pull request merged**
