### PR TITLE
Reverted a few bureaucracy sprites

### PR DESCRIPTION
**Pull request by ghost**
Reverted the paper bin, cabinets and drawer sprites from https://github.com/tgstation/tgstation/pull/20829 to their old forms. The paper bin doesn't really look good, the sprites of all these look really off compared to everything else, looks like they belong on Goon. I think @WJohn should improve the old sprites rather than introduce 3/4th perspective ones out of the blue.

I'll leave the cabinets and drawer alone if enough people like them but the paper bin has got to go

:cl:
tweak: reverted the paper bin, cabinets and chest drawer sprites to their old versions
/:cl:

### CODE REVIEW

**Comment by chanoc1** [comment]
would go good with new salt shaker and pepper shaker sprites :^)

**Comment by nullbear** [comment]
I agree with the paperbin but disagree with the rest. And it's not really 'out-of-the-blue' seeing as there are two other ways to introduce new sprites:

A: gradually/in extra small amounts (which is the most jarring)
B: all at once (which is very difficult and especially in the case of ss13, likely unfeasible for mere mortals)

Wjohn did a good job of modifying MANY sprites that all follow a very consistent art-style, and is working on modifying more. Its probably going to be noticeably jarring for a while, but hard-reverting them limits any progress to spriting.

They're just sprites, and have very little effect on the gameplay, if any, by being different from the old ones, so reverting them isn't really a high priority.

If you don't like them, i recommend that you improve them + improve other sprites so that they aren't as jarring in relation to other newer/better and more consistent sprites that will be added.

**Comment by WJohn** [comment]
I agree that paper bins are not good, and I'll see to it that they get a resprite soon. Don't worry about that. As for the rest, I DID improve the old sprites, this is what I came up with. The hideous things we had before would still look goon-ish with my color palette but in a shittier perspective.

**Comment by nullbear** [comment]
I meant that for uraniummeltdown. #Improve_dont_remove

**Comment by FantasticFwoosh** [comment]
Without meaning to knock the effort that went into making them, i agree they should be reverted, and if they require sprites they should have another try another time.

For anybody who disclaims that there isn't a problem with them, i ask you, do any of you play very bureaucracy central roles like HOP or cargo/Qm frequently? It is very grinding to have to look at those sprites in your place of work especially for 30+ or more minutes.

> All the sprites are too shiny and plastic, this not only makes them stand out too much but also implies that they are 'tacky' & 'cheap' which well might be what you want to drive towards, but implicatively in peoples associative mind are quite bad when you think about them as the only option, with no higher quality limit, or even difference in quality between this tacky stuff (pens that run out after a while/paper bins with less capacity) and the good normal robust stuff.

> Everything in the current TG aesthetic is actually rather grungy industrial (metal pens, plain paper-bins and draws, complex machines like the PA etc) rather than this new age of consumerism and bright colours that came in later in the 20th century with the introduction of mass production lines using cheap materials. Sure it might be mass produced, but i like to think of it in a purely methodical applicative sense rather than concepts like (make a cheap product so that people buy it made out of plastic vs/ make a cheap product but make sure its robust so we dont have to waste replacing it)

> They are oddballs, if you were driving towards that aesthetic, it'd probably be better to renovate all the surrounding sprites too given the contrast of the existing aesthetic and the suggested one rather than something so locationally specific like bureaucracy, this includes chairs/tables too and then look and think about the changes that you made.

**Comment by optimumtact** [comment]
As wjohn is the art director they have final say on all sprites.

Your pr will be denied once 24 hours is up.

**Comment by WJohn** [comment]
jesus this feels mean?? i didn't call for a DNM, but i will clean up these sprites personally in a little bit so whatever.

**Comment by nullbear** [comment]
xD well i mean its not like very much work or skill goes into a revert.

**Comment by PKPenguin321** [comment]
Cabinets and drawers are fine, paper bin is bad

**Comment by uraniummeltdown** [comment]
Well if @WJohn is fixing the paper bin sprite it's alright then

**Comment by optimumtact** [comment]
I don't care if it's mean, I'm not paid to be polite

**Pull request closed without merging**
