### PR TITLE
resprites air alarms

### PR DESCRIPTION
**Pull request by CoiledLamb**
## About The Pull Request
foreword: this will not negatively impact the wallening
okay now that we've got that out of the way - 
image
resprites air alarms to be closer to the older versions, and the wallening vers.
image
## Why It's Good For The Game
the current air alarms are _fine_, but they carry with them some bad habits - grey outlines on the body, and unnecessary animations on the screens. as well as being obfuscated by having the safe reading being blue, rather than green. this will help to make things more contiguous going in to the wallening, but will also serve for some quality of life benefits, as the readout will be much clearer.
## Changelog
:cl:
image: resprites air alarms
/:cl:

### CODE REVIEW

**Comment by Jolly-66** [comment]
return to sovl

**Comment by Likteer** [comment]
I think the current sprites are better

**Comment by Prussen** [comment]
Worse sprite

**Comment by CoiledLamb** [comment]
if you have any suggestions on how to improve them feel free to ping me on discord 👍

**Comment by mc-oofert** [comment]
fucked up

**Comment by SyncIt21** [comment]
For feedback better ask the original spriter for air alarms. @MTandi thoughts?

**Comment by MTandi** [comment]
It's very wide. I'm afraid it will be hard for AI to tell left-facing from right-facing one. You'd need to make it directional again to overcome this, but I made the previous sprite to get rid of directional. 

Also it looks too 3/4 for our walls. I thought you planned this for wallening.

**Comment by MTandi** [comment]
>unnecessary animations on the screens

Also, what? If you remove the animations, it's a downgrade IMO.

**Comment by CoiledLamb** [comment]
> It's very wide. I'm afraid it will be hard for AI to tell left-facing from right-facing one. You'd need to make it directional again to overcome this, but I made the previous sprite to get rid of directional.
> 
> Also it looks too 3/4 for our walls. I thought you planned this for wallening.

i already made directionals, wallem doesn't rlly want em, so i'm inclined to say it's fine. i could make it shorter but i don't rlly think it's necessary
also no, i don't care if these are overwritten by wallening ones, as those are built with the walls in mind and make good use of that. i just like em more than the current if i'm being honest

**Comment by CRITAWAKETS** [comment]
> this is a misconception, animations do not always improve a sprite. it's fine to have them static as the key thing they are displaying is the color - the graphs, exclamation marks, and bits of fluff text imo do not add anything to the alarm, the color communicates enough

I'd say keep some kind of tell that isn't color, you never know if someone's going to be colorblind and unable to tell which color the air alarm is on easily. Hell, full monochromatic colorblindness is a game quirk so there's even more incentive to do this.

**Comment by CoiledLamb** [comment]
> > this is a misconception, animations do not always improve a sprite. it's fine to have them static as the key thing they are displaying is the color - the graphs, exclamation marks, and bits of fluff text imo do not add anything to the alarm, the color communicates enough
> 
> I'd say keep some kind of tell that isn't color, you never know if someone's going to be colorblind and unable to tell which color the air alarm is on easily. Hell, full monochromatic colorblindness is a game quirk so there's even more incentive to do this.

someone approached me on disc about this so i decided to do a fade in/fade out for the severe alarms. green doesn't really need anything imo. but yeag this will come probably tomorrow

**Comment by lessthnthree** [comment]
The current air alarm sprite is better. Change the colors and such to improve how it looks yeah. But the design of the old one isn't something to bring back.

**Review by DATA-xPUNGED — CHANGES_REQUESTED** [review]
The old animations made the Air Alarm really pop out when it warned of danger. Also, they had a different shape for each mode, which helped with the colorblind. You should at least make the different modes have different icons?

**Comment by CoiledLamb** [comment]
> The old animations made the Air Alarm really pop out when it warned of danger. Also, they had a different shape for each mode, which helped with the colorblind. You should at least make the different modes have different icons?

like i said i will add animations for the varying dangers so colorblind ppl can tell them apart

> The current air alarm sprite is better. Change the colors and such to improve how it looks yeah. But the design of the old one isn't something to bring back.

nah, i like the ones i made better. throwing out my work entirely to tweak one i like less is not worth the time and effort i'd be putting in to make that happen.

**Comment by san7890** [comment]
i'm fond of it

**Comment by thgvr** [comment]
this is so much better it's not even funny

**Comment by Jacquerel** [comment]
Unless I am mistaken you are planning to add more animations so I am drafting this to prevent anyone from jumping the gun, please undraft if I got the wrong end of the stick.

**Comment by CoiledLamb** [comment]
> Unless I am mistaken you are planning to add more animations so I am drafting this to prevent anyone from jumping the gun, please undraft if I got the wrong end of the stick.

yeag I have a bit of work to do on this one, have been sick with covid but I'm finally getting over it so I'll try and work on it tonight. thanks jacq

**Comment by EricZilla** [comment]
Guys yall know colorblindness exists in real life too not just the game lmao

**Comment by DATA-xPUNGED** [comment]
> Guys yall know colorblindness exists in real life too not just the game lmao

I honestly forgot about the colorblindness quirk

**Pull request merged**
