### PR TITLE
Adds an animation to being electrocuted, like in cartoons!

### PR DESCRIPTION
**Pull request by RemieRichards**
## Content
- Adds an Electrocution animation! `electrocution_animation(duration)` turns you skin, mutant body parts, and hair black for the duration of the animation, then resets them to their usual values.
  while doing this a flashing skeleton also appears on the user, it's just like a cartoon!
- If the user doesn't have dna or a species, a rough "generic" animation is played instead, this should never happen, but it's there as a fallback
## Code
- Adds a `forced_colour` argument to a few mutant body part procs on `/datum/species`, so that I can force them to render black, without hacks
- Humans (and other species that have `use_skintones = 1`) now correctly use `update_color()`
  You will see no visual difference, but it was necessary to flash the human base icon black without hacks, this also reduces the snowflake nature of the human species somewhat.
## Examples

Human:
humanelectrocution

Lizard:
lizardelectrocution

Lightning Bolt:
wizardshock

### CODE REVIEW

**Comment by Chocobro** [comment]
this is adorable oh my god
shoutouts to original Mickey Mouse cartoons
:+1::heavy_multiplication_x::100:

**Comment by xxalpha** [comment]
:+1:

The lizard tail has no skeleton though.

**Comment by fleure** [comment]
Holy shit, best PR

**Comment by AnturK** [comment]
Hilarious, but seems to busy for something as common as shockings. Maybe only if damage passes some threshold.

 Also skeleton over clothes looks kinda weird but not sure that's intended

**Comment by Jordie0608** [comment]
What if someone is a skeleton, or a slimeperson? A flashing skeleton on them would look rather strange.

**Comment by RemieRichards** [comment]
@xxalpha it's cartilage, like a shark, or human noses and ears (also no lizard skeleton sprite)

@AnturK adding a threshold is easily possible, just swap ```if(.)``` for ```if(. >= SOME_THRESHOLD)```
I'm leaving it at this for now though, because it's funny, and SS13 could do with a bit more low-level zaniness. As for the skeleton, that can be rendered at any layer, simple change.

@Jordie0608 get me species specific variations (such as no skeleton, or a fleshy core thingy) and I'll implement them. also flashing skeleton on skeleton would be... well it'd be invisible, you wouldn't be able to tell so that 1 case is atleast covered :P

**Comment by Miauw62** [comment]
lmao :+1:

**Comment by Core0verload** [comment]
:-1: Too long and too ugly.

**Comment by GunHog** [comment]
Very silly, I like it! :+1:

**Comment by SconesC** [comment]
Probably should have a threshold because that's a much better use of it

Oh he touched a door and did THAT flash well damn he done fucked up

**Comment by Iamgoofball** [comment]
this is fucking brilliant

:+1:

ignore anyone who whines reelismz

**Comment by Anonus** [comment]
The skeleton shouldn't show up unless they're currently black because otherwise it looks weird as fuck.

**Comment by Miauw62** [comment]
it SHOULD be a threshold, that would be cooler.

**Comment by GunHog** [comment]
Agreed with Meow. Show it when it does near max damage, to show that this guy just got DROPPED by cruel engineers / clever rogue AI who overloaded the powergrid!

**Comment by Cheridan** [comment]
this is the dumbest thing i've ever seen

ship it :+1:

**Comment by Profakos** [comment]
This is the most beautiful PR
It only needs to also make hair spiky/messy/etc if the voltage is REALLY high, then it achieves perfection.

**Comment by PKPenguin321** [comment]
this is wonderful :+1:

**Comment by Ergovisavi** [comment]
>LIZARD
>HUMAN SKELETON

THE CONSPIRACY WAS REAL :+1:

**Comment by Lumipharon** [comment]
>lizards are all really just humans in scaley suits

**Comment by kingofkosmos** [comment]
Will this work with electric chairs?

**Comment by optimumtact** [comment]
http://www.oranges.net.nz/~oranges/memes/webm/spooky_skellingtons.webm

**Comment by RemieRichards** [comment]
@kingofkosmos if they properly use ```electrocute_act()```, yes

**Comment by Profakos** [comment]
Electric chairs call ```burn_skin()``` directly, sadly.

**Comment by veganzombeh** [comment]
> Rendering the skeleton beneath the clothes legitimately looks awful, so it's staying as is
Maybe blackening the clothes too would look better? It really does look weird having the skeleton over the clothes.

**Comment by Xhuis** [comment]
Seems a little over-the-top, and it seems like it would just get annoying after a time. Reluctant :-1:

**Comment by JJRcop** [comment]
:+1:

**Comment by Lumipharon** [comment]
Reserve it for powerful shocks (like electric chair) to keep it actually meaningful.

**Comment by Iamgoofball** [comment]
So when do we get birds flying over your head if you're stunned?

**Comment by Xhuis** [comment]
how long until we revert :^)

**Comment by Iamgoofball** [comment]
how long until xhuis stops being a nerd :^)

**Pull request merged**
