### PR TITLE
Resprited teleporter beacons

### PR DESCRIPTION
**Pull request by SmArtKar**
## About The Pull Request

3/4 version of tracking beacon to go along Wallening

image

vs the current one

image

## Why It's Good For The Game

Old, flat, crusty sprite

## Changelog
:cl:
image: Resprited teleporter beacons
/:cl:

### CODE REVIEW

**Comment by Dorsisdwarf** [comment]
Great sprite!

**Review by Twaticus — APPROVED** [review]
cute i wanna step on it

**Comment by Loafin34** [comment]
could you make it a little bit more crusty, like the old sprite?

**Comment by AMyriad** [comment]
critical question does the light blink?

**Comment by SmArtKar** [comment]
> critical question does the light blink? o_o

It does

**Pull request merged**
