### PR TITLE
adds some fresh memes to gibbering

### PR DESCRIPTION
**Pull request by ghost**
chelp
copi that
i bleending
i fix the breath

### CODE REVIEW

**Comment by tkdrg** [comment]
Please no

**Comment by RemieRichards** [comment]
SWOLLOW isn't getting in
this PR + SWOLLOW = this PR isn't getting in.
PR - SWOLLOW = PR getting in

please finish maths.

**Comment by dannno** [comment]
>no i bleending

:-1:

**Comment by paprka** [comment]
added bleending and 'i fix the breath'

**Comment by dannno** [comment]
:+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1:

**Comment by paprka** [comment]
Removed swollow since erp reference and remie has a boner for fenex

**Comment by optimumtact** [comment]
dank memes

**Comment by Iamgoofball** [comment]
Needs all the memes from @hornygranny pull request

**Comment by paprka** [comment]
i'm not gonna add ayy lmao that's already too played out, we only need the freshest of memes in our game

**Comment by Niknakflak** [comment]
Pass.

**Comment by mikecari** [comment]
>le giraffe gamestop employee
Copy that. :^)
http://i3.kym-cdn.com/entries/icons/original/000/017/051/copy_that.jpg

**Comment by Miauw62** [comment]
>no ayy lmao

:+1:/10

**Comment by paprka** [comment]
auto-9gag-1591014

**Comment by dannno** [comment]
miauw confirmed for doesnt even know the best memes

**Comment by mikecari** [comment]
ayy lmao seals the deal, pap.

**Comment by dannno** [comment]
>people want the babiest tier meme

**Comment by dannno** [comment]
ok no
wait
make it so that retards can only say "ayy lmao"  when xenos are within sight

**Comment by paprka** [comment]
i wish

**Pull request closed without merging**
