### PR TITLE
Fix bundle

### LINKED ISSUE #21233: Changelings cannot use biodegrade to escape cocoons
Made myself into a changeling via xenobiology. Unfortunately, a spider put me in a cocoon before I burst. Waiting two minutes? Fuck that, bought biodegrade, and it didn't work. Kor had to yank me out of the cocoon.

### LINKED ISSUE #21251: No way to dump the contents of transit tubes
This is inconvenent if you need to put people in it to rescue them and cant dump them out

### LINKED ISSUE #21254: Abductor Plasma Organ Implant Still Gibbing People
The plasma organ implant the abductors can put in people is still gibbing the recipient, even though it was supposed to be removed months ago. This was found when a CE, with no other implants, but wearing his hardsuit and mag boots, was experimented on, had the plasma organ put in, and then exploded seconds after returning to the station.

### LINKED ISSUE #21258: Disposal outlets are not immune to fire
[Note]: Disposal chutes, outlets, and what-not are not immune to fire, resulting in them breaking after a short time in an inferno. How am I supposed to make a hell-furnace that I can throw people into easily without my disposal pipes? 

Recommend this bug be put on top priority.

### PR DESCRIPTION
**Pull request by ghost**
:cl: Xhuis
add: Disposal units, outlets, etc. are now fireproof.
add: Changelings can now use biodegrade to escape silk cocoons.
/:cl:
- Fixes #21258 
- Closes #21254 (Isn't actually happening. Maybe a downstream?)
- Closes #21251 (See comments. Not actually an issue.)
- Fixes #21233 (Never existed, added.)

### CODE REVIEW

**Comment by tedward1337** [comment]
Based Xhuis

**Comment by optimumtact** [comment]
Why should they be fireproof?

**Comment by phil235** [comment]
Disposals are already nearly fireproof: 90% armor and 200 hp means it would take 100-200 cycles to burn them.

**Comment by Xhuis** [comment]
I wasn't actually sure if they were meant to be fireproof or not. The issue post made it sound like they were at one point but suddenly weren't for reasons unknown. If you want me to scrap it, just let me know.

**Comment by PKPenguin321** [comment]
They were indestructible before Phil meme

**Comment by optimumtact** [comment]
they were indestructible before we added the ability to destruct things, not because of a conscious choice. Just because we lacked the ability to simulate it.

I know people will take time to get used to these things, but exceptions should only be made in certain cases such as clothes and backpacks that genuinely affect the gameplay in a significant way.

**Comment by PKPenguin321** [comment]
i think disposals traps that shoot into heated plasma gas chambers is funny though

**Comment by optimumtact** [comment]
Then add heat resistant pipes that require plasteel in their construction.

**Comment by phil235** [comment]
@Xhuis I really don't care whether they are fireproof or not tbh, it's a question that needs to be asked to players.

**Comment by PKPenguin321** [comment]
@optimumtact but then they'll get almost no use at all
we really need a new class of metal that bridges the gap between regular metal and plasteel

**Comment by duncathan** [comment]
There is no good gameplay reason to leave disposals chutes vulnerable to fire. Until atmos techs have a reason to want to fix them, it'll just leave more unfinished repair work to make fires more broken and hard to fix. Adding a new type of disposals chute that is fireproof is also bad, since the chutes currently do not consume resources to build, and already have pointlessly long construction times. This is fine as-is.

**Pull request merged**
