### PR TITLE
Syndicate MODsuit resprite - sleek edition

### PR DESCRIPTION
**Pull request by Fikou**
## About The Pull Request

Sorts MODsuit icon files into clothing and modules
Makes it so modules (specifically armor booster here, but also the loader arms and ash accretion) can be colored like the control unit. and also lets them use any icon file for the overlay, so downstreams dont suffer
Resprites the Syndicate MODsuit to a sleeker design, also abandoning the armor booster cutting like a third of the sprite out, instead its similar to the elite suit, where being in space mode just gives you a different helmet design, being slits rather than eyes
Old:
image
New:
image
image
image
image

## Why It's Good For The Game

syndies deserve a cooler design, the elite suit already serves the bulky suit purpose, so a sleeker one fits nice.

## Changelog

:cl: Fikou, Azlan, PositiveEntropy, Capsaicin
imageadd: new sprites for the syndicate modsuit (and honkerative)
/:cl:

### CODE REVIEW

**Comment by Farquaar** [comment]
Bold
Brazen
Unapologetically defiant
These are some words in my thesaurus that are necessary to describe the new Syndicate MODsuit sprites

**Comment by itseasytosee** [comment]
Improvement 👍

**Comment by Serxule** [comment]
whats the armor booster mode look like

**Comment by theta060** [comment]
> whats the armor booster mode look like, unless im just stupid

i think the lowest one is armor booster

**Comment by Ebin-Halcyon** [comment]
>and also lets them use any icon file for the overlay, so downstreams dont suffer

Thanks Fikou, love you long time.

**Review by Twaticus — APPROVED** [review]

**Review by tralezab — APPROVED** [review]
looks good

**Pull request merged**
