### PR TITLE
Pacifists can now use mech drills on closets containing living beings

### PR DESCRIPTION
**Pull request by Irafas**
Also alters variable names to be more consistent with how pacifism is handled with guns.

:cl:
add: Pacifists can now drill closets containing living beings 
/:cl:
Just a quick update after #36401 altered drill behaviour, and to make code more consistent.

### CODE REVIEW

**Comment by XDTM** [comment]
I'd leave code-only stuff out of the changelog, it's meant to convey gameplay changes to players more than documenting PRs

**Comment by ExcessiveUseOfCobblestone** [comment]
Why are harmful objects given vars across code and not simply having a flag on objs for it :/

**Comment by Irafas** [comment]
@XDTM Ah right okay then. How would I describe this PR then as all the changes are to code with no game play changes? Would I leave the changelog blank or just shorten them to be simpler?

@ExcessiveUseOfCobblestone Dunno. This is just an update to a previous PR i made (#36293) after changes in #36401 made some code redundant. Still going through the process of learning Byond and having it so all objects have a harmful flag seems like a difficult task. Would certainly make managing what objects pacifists can use easier though.

**Comment by ExcessiveUseOfCobblestone** [comment]
@Irafas just remove the changelog outright if there are 0 gameplay effects, otherwise word it relative to what a non-coder needs to know.

**Comment by XDTM** [comment]
It's minor enough to not really need a changelog, but if you want you could add something like "Mech equipment can now be used on lockers while affected by pacifism."

**Pull request merged**
