### PR TITLE
Adds Chemical Explosive to RnD

### PR DESCRIPTION
**Pull request by nullbear**
Adds a chemical explosive, discoverable via RnD, as a lovechild between a syndicate bomb, and a
chemical grenade.

It can store up to 4 beakers, as opposed to the 2 beakers grenades have,
but cannot be planted in public areas stealthily, has a minimum timer of 60 seconds,
and can be defused similarly to the training-bomb in security.

To create: Research one tier above large grenade requisites. Requires metal and a
diamond to produce -> Wire the device using a cable coil, then fill with between one and
four beakers (The bomb should not be possible to activate without a payload.) -> Screwdriver the panel closed -> (optional: Wrench the
bomb, anchoring it to the ground and preventing it from being moved once activated.) ->
Activate the timer (60-60000 seconds).

Will notify admins if the explosive has been primed.

---

Feedback?

Can be easily nerfed by increasing minimum timer, or increasing protolathe requisites, if needed.

### CODE REVIEW

**Comment by Core0verload** [comment]
Looks like a wall of copypasta.

**Comment by nullbear** [comment]
It is, it doesn't need to be unique.

**Comment by Core0verload** [comment]
Make it a subtype then. Bomb payloads are modular for a reason.

**Comment by Jordie0608** [comment]
But it does have to conform to code standards https://github.com/tgstation/-tg-station/blob/master/CONTRIBUTING.md#no-duplicated-code

**Comment by GunHog** [comment]
Copy-paste is one of the things maintainers are overtly obsessive about eliminating. You _must_ make it a child of the current Syndiebomb. It would be easier as well, as all you really need to do is a little renaming. Most of the new code would be regarding your bomb's payload, instead of the assembly itself.

**Comment by nullbear** [comment]
Cool ,ill edit this then.

**Comment by GunHog** [comment]
Code stuff aside, I love the idea of a chemical bomb assembly, I wonder what @Iamgoofball thinks of it as well. If it looks just like a Syndicate bomb, it could be used for pranks as well! I do hope that recoding and testing of this goes well!

**Comment by nullbear** [comment]
image
Quick pic of 2 detonations, one is of a basic clf3 grenade. The second is of a bomb setup with 1200u of clf3. Note, because of the way chembombs work, the fire has a limited range, and will not spread through walls.

As to looking like a syndibomb, it's grey like the training bomb, but with a red light.

**Comment by Core0verload** [comment]
It looks way too !!FUN!! for /tg/station coderbus.

**Comment by nullbear** [comment]
Should i add a joykill nerf to it then? Something like an increased cost, timer, and maybe a radio alert to yell once it's been primed?

**Comment by Core0verload** [comment]
At least make it a regular bomb subtype with a special payload. Try appeasing Gods of Github Maintaining by sacrificing 250 lines of copypasta.

**Comment by nullbear** [comment]
Yeah, i was just being stupid and lazy. (which is silly cause honestly it would have been easier to do it this way from the start.) 

Just about done, another question though: As the payload will need to be removed, and loaded with chemicals before it can be of any use. Should there be one of these explosives in toxins or misc_research with a paper next to it explaining how to do so? Or should we trust players to be clever enough to figure it out on their own?

**Comment by GunHog** [comment]
Give them a paper, do not trust players to be clever, many are not.

**Comment by Archie700** [comment]
>players to be clever enough 

ahahahahahahaha

**Comment by Bawhoppen** [comment]
>not makeable in R&D
wheres muh powercreep

**Comment by Shadowlight213** [comment]
The cost feels too low when you take protolathe and orm upgrades into account.

**Comment by nullbear** [comment]
i don't honestly play too much in RnD, and don't know how much the cost plays out.

I figure, it should be possible to make 3-4 of these with an active and cooperative mining team, assuming you make nothing else that is expensive. (Keep in mind, players will typically also be trying to get bluespace beakers in order to properly synergize with this, which cost a bit themselves.)

What would you recommend the cost to be?

**Comment by GunHog** [comment]
Kor currently plans to continue his nerfs against Science, so I do not recommend inflating the price too much.

**Comment by RandomMarine** [comment]
Somebody, someday, is going to spend TC to remove bombcap and make a 32/65/132 with this.

And it will be glorious.

**Comment by nullbear** [comment]
Alright, should be good now.

**Comment by ChangelingRain** [comment]
You can do an in-post changelog by editing the main post to include the following
````
:cl: name(optional, if not set takes github username)
rscadd: changes
tweak: this can use any of the changelog code things
/:cl:
````

**Comment by Iamgoofball** [comment]
# Y E S :+1:

**Comment by Lumipharon** [comment]
This can make rediculously powerful bombs. This will produce bombs that exceed anything except well made, bombcapless toxins bombs.

That said, I like the idea, but seriously fuck R&D powercreep. This takes fuck all time and resources to make bombcap bombs/AIDS bombs, and if the wires work like a syndie bombs then you can just makes 50 of them and set them all of instantly because fuck timers when you have signallers.

**Comment by Core0verload** [comment]
There is a reason why SS13 is a research station.

**Comment by PKPenguin321** [comment]
\>muh research station

There is a reason why SS13 is called a *video game.* It's supposed to be fun for as many people as possible, and scientists getting fucking everything in the game four seconds in to every round is often the opposite of fun.

**Comment by Lumipharon** [comment]
>There is a reason why SS13 is called a video game. It's supposed to be fun for as many people as possible, and scientists getting fucking everything in the game four seconds in to every round is often the opposite of fun.

**Comment by Zilenan91** [comment]
Science doesn't need this

**Comment by nullbear** [comment]
> That said, I like the idea, but seriously fuck R&D powercreep. This takes fuck all time and resources to make bombcap bombs/AIDS bombs, and if the wires work like a syndie bombs then you can just makes 50 of them and set them all of instantly because fuck timers when you have signallers.

You can't set them up with timers/signallers?

As well, for nerfing stuff, it's not really a huge issue to toss a safeguard on it, alerting the station when/where it's been armed, giving the crew at LEAST 60 seconds to go straight to it, and attempt to disarm it, without just a sudden "lolboom".

As well, it's set up so that it can be easily be changed from 4 beakers, to 3 beakers.

I can however understand the sorrow from seeing rnd getting yet another cool thing. Perhaps make it a cargo thing instead? ie. cargo gets bomb assembly minus payload. RnD gets payload.

**Comment by Lumipharon** [comment]
You can attach signallers to the boom wire (also the activation wire if you really want) to safely detonate it from a distance whenever you want.

Also nade assemblies can also have timers and signallers so I'm not sure what *you* meant.

**Comment by Shadowlight213** [comment]
Yeah, science already has toxins for the big explosions. They don't need this.

**Comment by nullbear** [comment]
well put it somewhere else then. The mechanic is sound. Maybe antag chemist?

**Comment by Ninja137** [comment]
Why not just make the 4-beaker bomb assembly be something buildable with normal materials, and make it require a few parts from a lathe/protolathe?

**Comment by nullbear** [comment]
I thought of that, but i was lazy and was worried it could be even less balanced. Any suggestions on recipes? Keep in mind there are two parts, the payload, and the bomb device. Though technically the payload is enough.

**Comment by Dorsisdwarf** [comment]
Make the bomb chassis orderable (Costing more than their roundstart points obviously) from cargo, but R&D can make the payload with research

Departmental synergy is nice, and R&D dont rely on cargo enough these days. 1 trip and BOOM INFINITE GUNS

**Comment by Cheridan** [comment]
What @Shadowlight213 said. Science already has an entire room dedicated to mixing and creating explosives. Boiling down the process to a button push is stupid.

**Comment by Iamgoofball** [comment]
@Cheridan if anything this is way more useful for hellfoams and stuff, not kabooms

**Comment by KorPhaeron** [comment]
It'd be cool if people actually made zany chem bombs with these, but they'll probably just use it to bypass the transfer valve limit and spam explosives

**Comment by Iamgoofball** [comment]
@KorPhaeron if they wanted to make explosives with R&D that aren't TTVs, you can already do that with large grenade shells, bluespace beakers, and the right chem mix

this is really overkill for those, this is only good for zany chem bombs

**Comment by nullbear** [comment]
I'm gunna leave it as it is for now, until it's proven to be unbalanced, or a good recipe is decided on.

**Comment by Bawhoppen** [comment]
no matter what happens make sure this gets merged as admin-only atleast

**Comment by Lumipharon** [comment]
>proven to be unbalanced

>only 6 ttvs because lots of explosion are gay
>syndie bombs got removed from DA because lots of explosions are gay
>bomb cap because huge explosions are gay
>can't make anything more then a tiny bomb via grenade without R&D research and minerals because lots of explosions are gay

**Comment by Zilenan91** [comment]
Syndie bombs got added back to DA after DAs stopped getting told they were DAs.

**Comment by nullbear** [comment]
Idea for recipe, to improve balance and availability.

Tablecrafting** the payload/bomb core** -> Super Matter Bin + Grenade Casing x2 + C4/Gibtonite
_This makes use of tablecrafting, requires science to reach a certain level of research (super matter bin, could be made harder by making it require ultra matter bin instead.) Allows better access to the rest of the crew, as super/ultra matter bins aren't too hard to muscle out of science. And requires cooperation from cargo/mining unless you are an antag. Gibtonite is pretty high profile, so it will be harder for a player to create very many without attracting attention, unless they are an antag. Easiest access to building this, is mining, or scientist antags._

Sheetcrafting the **Bomb Assembly** = 4-10 Plasteel Sheets.

_Plasteel is quite widespread across the station, and most departments can easily access it. But without cargo or xenobio, there is a limited amount. The bomb assembly itself is quite high profile, as it can't be picked up, only dragged. The quantity of plasteel required can be used to help balance the recipe as well. _

The crafting of this device will require a few steps: Create the bomb assembly. Create the payload. Load the payload with chems. Put the payload into the bomb assembly. Wire it. Activate it.

**Comment by Shadowlight213** [comment]
I approve. That's actually a really good way to balance it.

**Comment by Lumipharon** [comment]
If it required gitbnite to make the payload, instead of massproducing infinite beakers for fuckhuge bombs, that would be neat, if somewhat rare.

**Comment by Iamgoofball** [comment]
@Lumipharon thatd make it never show up, since when is a miner(the only job with access to gibtonite) ever going to cooperate with a chemist to make a bomb

**Comment by duncathan** [comment]
goofball got a RAGING hard-on the moment he saw this pr

**Comment by Iamgoofball** [comment]
^

**Comment by nullbear** [comment]
most chemists don't get all that pissy about having their lab busted into on /tg/ i've noticed. Still, it's very easy for an antag chemist to get it, and miners will typically be forced to collaborate with chem in order to get one for themselves. So i feel like it would be a 50/50 thing. "I'll bring you gibtonite if you let me play in your lab."

I've got a tek recipe somewhere for RDX and anfo that could possibly see some use on the server as well, ideally with the rdx being used as a chemist-friendly alternative to c4 or gibtonite, though being a tad trickier to make in-game than it is in real life.

**Comment by Lumipharon** [comment]
@Iamgoofball I was referring to null's suggestion, which doesn't involve chemistry at all. Also since when has science ever needed chemistry's help for anything? Not for years, that's for sure.

**Comment by Shadowlight213** [comment]
@Lumipharon I'm pretty sure the bomb payload needs gibtonite or c4 to be made now.

**Comment by nullbear** [comment]
Yeah i've already changed the recipe. It's fine to be merged whenever if y'all think it's been balanced enough.

**Comment by nullbear** [comment]
There's an issue with player-constructed bomb assemblies not being added to the machine processing list, which means they will never detonate. Dunno how i should fix that, or if that's a problem higher up, as i can't see where it would be an issue within my own code. Any suggestions on how to fix that?

**Comment by nullbear** [comment]
Cool. Fixed issue with new, and nerfed the timer a bit, which should only really affect nonantag bombers. Made bombs emaggable, causing them to be slightly more dangerous. (cant tell how much time is left.)

**Pull request closed without merging**
