### PR TITLE
Fixes diseases being unrenamable

### PR DESCRIPTION
**Pull request by actioninja**
## About The Pull Request

I don't know what the original purpose of this check was

## Changelog
:cl:
fix: You can rename diseases in the pandemic
/:cl:

### CODE REVIEW

**Review by stylemistake — APPROVED** [review]

**Comment by HomocidlePancakes** [comment]
Will the same disease with another name need to be cured separately?

**Comment by stylemistake** [comment]
I think diseases with same fingerprints share the same name, so changing the name of a disease would change it for the rest. Although actioninja might have changed that mechanic.

**Comment by kriskog** [comment]
@homocidlepancakes Disease names are irrelevant, they are stored and compared by an ID built from their symptoms.

**Comment by TheSilverNuke** [comment]
Merge merge merge

**Comment by BadSS13Player** [comment]
Uh, why doesn't this have a priority label?

**Pull request merged**
