### PR TITLE
Shaps PR except I actually know how the english language works

### PR DESCRIPTION
**Pull request by wesoda25**
## About The Pull Request

Masculine and Feminine have been replaced by Male and Female, cuts the parentheses explaining pronouns. 

## Why It's Good For The Game

First part is just good grammar, second part is to cut back on pointless visual clutter. Male/Female/Other options look much more visually pleasing this way (trust me they do!!), and aside from that, if you don't know how pronouns work you shouldn't be playing on tg anyways. 

## Changelog
:cl: wesoda gamer the twenty fifth
tweak: changed text on gender options to make them grammatically correct and visually pleasing
/:cl:

### CODE REVIEW

**Comment by wesoda25** [comment]
i might know how english works but im no so certain on code so lets see if this works

**Comment by optimumtact** [comment]
but I don't trust you at all ryan "feet meat" cobb

**Comment by Shadowflame909** [comment]
this PR feels like dorms 4

but im a dorms 3 man

**Comment by wesoda25** [comment]
> but I don't trust you at all ryan "feet meat" cobb

Targeted harassment isnt a joke

**Comment by optimumtact** [comment]
it is to me

**Comment by Shapsy** [comment]
I was gonna change this overnight but then I woke up and it was merged so yeah go ahead

**Review by SpaceManiac — APPROVED** [review]

**Comment by Arathianen** [comment]
Good PR

**Pull request merged**
