### PR TITLE
Improves crew monitor performance

### PR DESCRIPTION
**Pull request by Cyberboss**

### CODE REVIEW

**Comment by Cruix** [comment]
Dead mobs have suit sensors too

**Comment by Cyberboss** [comment]
living_mob_list is for mobs of type /living. It says nothing as to whether they are dead or not

mob_list includes shit like ghosts, new_players, and AI-eyes

**Comment by Cruix** [comment]
Based on https://github.com/tgstation/tgstation/blob/03bd3cab32a168a4948fc5ca52bcc566deaedec2/code/modules/mob/living/death.dm#L58 I do not think that is true

**Comment by RemieRichards** [comment]
@Cyberboss wrong.

**Comment by Cyberboss** [comment]
Well shit, why is there no human list reee

**Pull request closed without merging**
