### PR TITLE
Removes umbras

### PR DESCRIPTION
**Pull request by ghost**
People have been expressing dislike about umbras, and since I don't want to get through yet _another_ storm of jerks complaining that something is bad without telling me how to improve it, I'm not going to and instead I'm removing umbras in every way.

### CODE REVIEW

**Comment by lzimann** [comment]
the griff ghost is dead

**Comment by KorPhaeron** [comment]
Can we have revenants back instead

**Comment by Xhuis** [comment]
See OP. Revenants caused a huge amount of controversy and were modified in such a way that they directly went against the original vision I had for them. I want to revert them wholly and gather player feedback in order to write the miniantag again from scratch in a fun and interesting way.

**Comment by Incoming5643** [comment]
People getting mad because they got killed by a griefghost isn't controversy, they're just being salty.

**Comment by coiax** [comment]
I've never seen seen an umbra yet, what's wrong with them? Can they be any worse than the original grief ghost?

**Comment by KorPhaeron** [comment]
coiax go on server and I'll make you one, they have so little impact on the round it wouldn't even matter

**Comment by Xhuis** [comment]
Oh, come on, surely more than a _mouse_. Ian's no question, though, since he's the most impactful role in any round regardless of outcome.

**Comment by KorPhaeron** [comment]
A mouse can

1) Talk to people

2) Pull people

3) Go on sick espionage missions in the vents

I don't think umbra whisper actually works right now

**Comment by optimumtact** [comment]
It must, I've been whispered at by the grief ghost 2

**Comment by Bawhoppen** [comment]
xhuis I warned you

**Comment by AlexCrimson** [comment]
Its just not interesting. The only real fun thing to do is make people do near-antag shit by whispering them, and that gets old fast.

Like i said a long time ago, you shouldve just played through Ghost Master and made Revenant into a rip-off of that.

**Comment by Firecage** [comment]
So....why aren't we re-adding reverants again in the place of Umbras? Since Reverants were actually fun to play as.

**Comment by ChangelingRain** [comment]
Revenants were absolute assholes but they at least did something rather than literally nothing like umbras do right now.

**Comment by X-TheDark** [comment]
What about a "empower" themed Umbra, you know, channeling your Vitae into someone to give them some sort of powers (additionally, abilities that unlock the longer you "attune" yourself with your host), maybe some sort of healing thing (you know, tit-for-tat kind of deal - give me bodies, I'll heal you, probably). 

Would give incentive to give you bodies and you'd have the choice of either becoming validhunters best friend or traitors best friend. I wonder if it'd be a bit too much, though.

Obviously, also include something that Umbra can use to backstab people once it's in the person long enough ?

**Comment by Thunder12345** [comment]
You're being told they're bad because they do literally nothing. Revenants were a bit unfun to have around, but they actually *did* something. Umbras drain one corpse and have enough essence to last the entire round, then just find peoploe alone and press a button to gain a point. That's literally all they do. Give them some more powers instead of just removing them.

**Comment by Xhuis** [comment]
@Thunder12345, people are just asking for them to be removed, so I'm obliging them.

**Comment by optimumtact** [comment]
Well since you don't seem to want to maintain the umbra and I have low hopes of anyone else picking it up

**Comment by kilkun** [comment]
Revenants were unfun when people played them to win, however they are absolutely fucking hilarious if they play their role right. They are the clowns of the miniantag. The only sidetag with greater humor potential is the abductors, and that's a fucking crapshoot if your scientist is balls.

Umbras are just useless pieces of shit that can stun you for 5 seconds and basically do nothing else. Unfun to play, unfun to play against.

**Pull request merged**
