### PR TITLE
Revert "Fixed 2: Electric boogalo, gives lusty xenomorph maid reskin to DONORS (are you happy now)"

### PR DESCRIPTION
**Pull request by Dorsisdwarf**
Reverts tgstation/tgstation#18545

Putting aside the abomination that is W "I think aliens are sexy" Johnston's actual sprite,
I strongly disagree with donor content in the game.

When lizards were added, "Slippery slope fallacy, will never go further"
When lizards were given thousands of customisation choices "Slippery slope this is as far as it gets"
When catgirls were made roundstart "you hate fun" (At least this one was binned)
When angels were added "Who even cares its just wings"

But we have to draw the line against or-"I have seized control of the PR system"-anges somewhere and I think it's here, at adding OOC in-game resprites for donors.

### CODE REVIEW

**Comment by Iamgoofball** [comment]
dorsisdwarf you realize this is donating to BYOND, right

not server donors?

**Comment by Iamgoofball** [comment]
i detest the sprite but it allows us to make BYOND some cash off of stupid furries

**Comment by Bawhoppen** [comment]
whats with travis

**Comment by WJohn** [comment]
I didn't even draw this sprite. That was basil.

Also this got closed twice before. Please stop.

**Comment by coiax** [comment]
Because this is a branch made directly on the main repo, travis is doing it twice.

**Comment by Dorsisdwarf** [comment]
What got closed twice before.

I saw this got merged and made a revert because fuck this shizz

**Comment by Zilenan91** [comment]
Everything else aside, the actual maid outfit could be implemented much much better. Let xenos hit vending machines to make them dump out their contents and eventually a maid costume gets spewed out that if a BYond donator clicks on as a xeno makes them wear the thing.

It'd be an easter egg at that point, and a good one, and not just saying, "HEY YOU WANT SOME MEMES HERE'S SOME MEMES"

**Comment by Militaires** [comment]
@Dorsisdwarf  i sprited and programmed this, and it was also my idea.

buckle up soldier, it's ground attack ;)

**Comment by Militaires** [comment]
also, i don't see why you would want to remove something only a fraction of the community has access to already, and you now there will be less people who will be donors.

if you can't have fun, let other people have it, when I made this I didn't put "omg lol fetish" in mind, people projected that onto it.

**Comment by coiax** [comment]
We have other cosmetic only options for byond donators as well, ghost colours and orbits.

**Comment by Incoming5643** [comment]
but they don't impact gameplay, this changes the hitbox, which technically means that donators get an in game advantage/disadvantage based on spending money. That's a big no no.

Also people are making fun of us over this, and my feelings are hurt :(

**Comment by GunHog** [comment]
> Everything else aside, the actual maid outfit could be implemented much much better. Let xenos hit vending machines to make them dump out their contents and eventually a maid costume gets spewed out that if a BYond donator clicks on as a xeno makes them wear the thing.

I suggested, multiple times, to simply have it such that using a xeno maid outfit on a queen would make her a maid, but that suggestion was denied in favor of this. Oh well. If this PR gets merged, I can make the alternative myself without the legal issue of using @Militaires' work without his consent. (Would one of the code-laywers please confirm this?)

**Comment by Militaires** [comment]
@GunHog  eh probably wont get merged, this was done two times before and shut down, and @cheridan attested to this being their fetish SOOO

**Comment by Iamgoofball** [comment]
@gunhog code that has been merged is relicensed to AGPLv3, and assets get relicensed to some CC version,  with the project being the new official author

**Comment by GunHog** [comment]
Okay, goodie. So if this donor feature gets axed, I will go ahead and try PRing the less paywall based method.

**Comment by Militaires** [comment]
@GunHog it's made to generate revenue to fill the small bank we're eating into quickly, taking that way is meh.

i hope you dont think this is my only paywall plan, i'll add more ghost cosmetics

**Comment by optimumtact** [comment]
Can you not please, this is a thing that will appear SO RARELY, that it is unlikely you will ever see it.

There is nothing fetish about the actual sprite, it's only an association you have in your head.

**Comment by Cheridan** [comment]
>I strongly disagree with donor content in the game.

>When lizards were added, "Slippery slope fallacy, will never go further"
When lizards were given thousands of customisation choices "Slippery slope this is as far as it gets"
When catgirls were made roundstart "you hate fun" (At least this one was binned)
When angels were added "Who even cares its just wings"

literally none of your examples have anything to do with donor content

**Comment by Dorsisdwarf** [comment]
>There is nothing fetish about the actual sprite, it's only an association you have in your head.

It's also an association literally hardcoded into the game referring to it as the "fetish outfit"

**Comment by optimumtact** [comment]
so remove the comment

**Comment by Iamgoofball** [comment]
@Cheridan 
I think what he means is how all 4 of those items were added behind a lock of some kind so literally everyone didn't have it or have access to it(except the customization on lizards but thats kinda a different situation entirely) to get away with a merge, then having the lock removed

**Pull request closed without merging**
