### PR TITLE
Adds Flash and Surgery toolset implants to R&D

### PR DESCRIPTION
**Pull request by silicons**
Adds surgical implant to R&D at a similar cost/research requirement but slightly higher then the toolset implant.
Adds flash arm implant to R&D at a moderate cost/medium-high research requirement.
:cl:Mekhi
rscadd: R&D can now print surgical toolset implants.
rscadd: R&D can now print flash arm implant.
:cl:

### CODE REVIEW

**Comment by TehZombehz** [comment]
Am I wrong to imagine using the flash implant as leaving you obligated to say 'talk to the hand'?

**Comment by optimumtact** [comment]
Fine with the surgical implants, against the flash

**Comment by LaharlMontogmmery** [comment]
Looking at the flash, the EM level you need to attain to be able to build it is five...

I think it's one of those levels where you need the help of other departments to reach it. Not sure tho.

**Comment by Hatfish** [comment]
EM 5 can be obtained within minutes of roundstart, level 6 is when you need help from botany or mining.

**Comment by Shadowlight213** [comment]
@kevinz000 as much as I hate to say it, as I do like toolsetlike implants being cheap, the surgery might need to be made more expensive than the toolset one since it contains a circular saw, which would be a nodrop force 15 sharp weapon.

**Comment by kevinz000** [comment]
On it

**Comment by XDTM** [comment]
or make it non-force 15

**Comment by Niknakflak** [comment]
>gun_hog thumbing this up

SURPRISE SURPRISE

**Comment by xxalpha** [comment]
None of this is cybernetic, make them augments.

**Comment by XDTM** [comment]
They're just as cybernetic as the already-existing toolset implant

**Comment by GunHog** [comment]
You seriously need to stop being a jerk, NikNak, I have not done anything to you. The flash implant is a BORG DESTROYER and is probably not the best thing, but the surgical implant is probably something Robos would love to have strapped to their arms, doctors too.

**Comment by optimumtact** [comment]
can you remove the flash and put it in another PR?

**Comment by KorPhaeron** [comment]
Stale.

If you want to put flash and surgery in different prs we can revisit

**Pull request closed without merging**
