### PR TITLE
Fixes slime people hating toxic / gross food.

### PR DESCRIPTION
**Pull request by ghost**
🆑 Floyd
fix: Slimepeople have found a love for sugary and/or toxic dishes. Blorble!
/🆑

does #36317 but actually done properly and spending more than 5 seconds to look at the code. stop trying to get GBP with low quality PRs.

### CODE REVIEW

**Comment by ShadowDeath6** [comment]
I can guarantee you spent less than 5 seconds looking at code to make this pr

**Comment by Qustinnus** [comment]
yea because I already spent multiple hours making it so I didn't have to look much

**Comment by Repukan** [comment]
Why is one of the arguably strongest races receiving more non-sensical buffs?

**Comment by Repukan** [comment]
Will science powercreep ever stop? Find out next season!

**Comment by Qustinnus** [comment]
i dont care if this gets closed i just thought cobby's PR was of shit quality. downvote it so it gets closed.

**Comment by Qustinnus** [comment]
actually cobby closed his pr, closing mine is literaly 4d chess

**Pull request closed without merging**
