### PR TITLE
 Some big changes to MetaStation EVA, Teleporter and Gateway 

### PR DESCRIPTION
**Pull request by nicbn**
I inspired myself in KiloStation to make these changes. There are now much less EVA suits (only 4). The gateway is smaller and looks more abandoned. The maintenance section is bigger and I also enlarged the corporate showroom as the other rooms got smaller.

This is more focused in balance than the current design. There's now a connection between EVA and teleporter, and they overall have less resources (like EVA suits) to offer, because conflict is part of the game and it shouldn't be solved by having a lot of roundstart resources.

image

:cl:
balance:  Some big changes to MetaStation EVA, Teleporter and Gateway 
/:cl:

### CODE REVIEW

**Comment by ishitbyabullet** [comment]
firefox_2019-07-30_16-45-29
I notice some windows in the middle room don't have shutters to close. I also noticed the weird lighting at the right side. I hope those are already fixed since it looks odd tbh.

**Comment by TheChosenEvilOne** [comment]
Showroom way too wide, halving the amount of EVA suits is bad and gateway no longer feels like star gate. I do like the teleporter room.

**Comment by nicbn** [comment]
I plan replacing showroom with something else in the future, but I'll leave it there for now.
@ishitbyabullet I'll fix this in a moment

**Comment by Dawson1917** [comment]
I don't like there being only 4 EVA suits unless cargo buys more, since now people are going to be very reluctant to let you borrow one for space exploring or setting up solars when engineering is lazy. Only 4 people (other than heads of staff) being able to survive a large hull breach at escape or the center of the station is unfitting for a server that averages 70 people on the station at once. EVA suits already become a valuable and quickly-snatched resource during mass destruction of the station. Blobs (and Infection if it's merged) will also be buffed as it's rare to see a blob fight where the frontlines aren't depressurized.

The Gateway shouldn't look dilapidated - it's meant to be Nanotrasen's next frontier. Just look at the brochures! It's meant to look like the SGC and is pretty good in its current state. 

Teleporter is meh. Just horizontally wide instead of vertically long.

Showroom looks bad with the empty space and lack of showcases, and those damn extra walls in the top corners.

**Comment by nicbn** [comment]
> I don't like there being only 4 EVA suits unless cargo buys more

That's the point. Conflict. The station shouldn't give people what they want, if you want something you gotta face challenges to get it. Also many other stations have around 4 EVA suits, it's Meta that is the special snowflake here.

> The Gateway shouldn't look dilapidated - it's meant to be Nanotrasen's next frontier. Just look at the brochures! It's meant to look like the SGC and is pretty good in its current state.

Space Station was never supposed to be state-of-art. Nanotrasen is known for metal deathtrap manufacturing, and gateway is never used by important Nanotrasen people (heads of command for example), only class-D personnel, so why should Nanotrasen even care?

> Showroom looks bad with the empty space and lack of showcases, and those damn extra walls in the top corners.

I didn't really like showroom either and I'm planning on removing it completely, but I'm keeping it as placeholder for now.

**Comment by FloranOtten** [comment]
>Space Station was never supposed to be state-of-art. Nanotrasen is known for metal deathtrap manufacturing, and gateway is never used by important Nanotrasen people (heads of command for example), only class-D personnel, so why should Nanotrasen even care?

Class what personell? You mean assistants?

Gateway is a new frontier. What are you on about? The entire station is state of the art. It's a deathtrap, sure, but it's still a brand new plasma research station.

**Comment by nicbn** [comment]
> Class what personell? 

I see you're not a man of culture
Whatever, the whole Gateway design was based off Kilostation. I thought it fits the SS13-paranoia-deathtrap mood well, so I ported it to Meta.

**Comment by Dawson1917** [comment]
There's already conflict over the 8 EVA suits, frequently. Pretty much every time a situation is bad enough that many people need to wear EVA suits, they'll all be taken. 

>Also many other stations have around 4 EVA suits, it's Meta that is the special snowflake here.

Box has 4, though it is for lowpop. Pubby has 4 but extra space suits for some people (think chaplain and QM). Delta and Meta have 8. I feel like Meta should have 8 since it is the primary map played on TG, with our general highpop of 60-80 players.

>Space Station was never supposed to be state-of-art. Nanotrasen is known for metal deathtrap manufacturing, and gateway is never used by important Nanotrasen people (heads of command for example), only class-D personnel, so why should Nanotrasen even care?

Some of the gateway brochures and missions mention being top-class research facilities IIRC. No matter how bad the actual location is, NT would surely want to show off the gateway room to investors who likely will never even step through the gate

**Comment by Swagile** [comment]
There's 8 space suits because meta station is meant to hold more players over all (60+).

People still have to fight for EVA suits even with 8 there.

**Comment by Swiftkor** [comment]
I like the idea about adding more scarcity to EVA suits but I'm not a fan of the map edits themselves.

**Comment by dee-dubya** [comment]
> Box has 4, though it is for lowpop. Pubby has 4 but extra space suits for some people (think chaplain). Delta and Meta have 8. I feel like Meta should have 8 since it is the primary map played on TG, with our general highpop of 60-80 players.
Where did you get this misinformation from? Box isn't a lowpop station. It was THE station for a very long period of time, and would frequently handle 50+ players without any issue.

As for the PR itself...honestly I don't see the big deal. If more hardsuits become a necessity during a round, it's not like you can't order more from cargo. They're not very expensive.

**Comment by Detective-Google** [comment]
IMO this could be solved by making EVA suits spawn based on pop (at a ratio of 1:10 people or whatever) that way there's always a scarcity instead of either way too many or way too few

**Comment by Shadowflame909** [comment]
What kind of experiences have you had that make you believe more escalation is a good idea?

**Comment by nicbn** [comment]
EVA is a storage for "special cases" such as space exploration. It is not "take in case of emergencies" - see real space stations, the EVA suits are not there for in-ship emergencies, as you'd normally be dead before you could reach the suits anyway.

In case of emergencies either engineering should fix it or cargo should order new suits.

That being the case, I don't see why a higher population needs more suits. It's not like you need 10% of the population to be exploring space or whatever

**Comment by wesoda25** [comment]
remove gateway to free up the space you want

**Comment by YakumoChen** [comment]
The gateway is required for some spawns (like swarmers) and for when away missions are actually used.

**Comment by ATH1909** [comment]
> What kind of experiences have you had that make you believe more escalation is a good idea?

Shadowflame909 brings up a good point here. What are you expecting to be the outcomes of these conflicts (often between non-antags) over space suits? Are you expecting anything other than violence to occur (from these conflicts) if the station is depressurizing, people are taking damage, and there are only four space suits to go around?

And before you point it out, yes, we do have stations with only 4 EVA suits in rotation, and we don't see routine violence from them... which means that your PR likely won't have much of an effect. It will either add nothing to the game or make it worse.

Oh yeah, and I agree with that other guy who said that this is a pretty big buff to blobs.

**Pull request closed without merging**
