### PR TITLE
Removes the Blood Cult ruleset at the request of oranges.

### PR DESCRIPTION
**Pull request by Iamgoofball**
## About The Pull Request

See title.

## Why It's Good For The Game
My boss says it goes, so it goes.
Discord_yeaRXfxltZ

## Changelog
:cl:
del: Removes Blood Cult from the roundstart rulesets. Administrators may still spawn cultists manually.
del: Please note that Cultists are separate from Heretics, which do still exist and are still available to play normally.
/:cl:

### CODE REVIEW

**Comment by carshalash** [comment]
Congrats old man robustin, your horrible changes are the reason this happened.

**Comment by LemonInTheDark** [comment]
here we go again

**Comment by maxymax13** [comment]
aerial reddit strike incoming

**Comment by interestingusernam3** [comment]
goof PR

**Comment by legoscape** [comment]
Eat pant orange man. 
original

**Comment by optimumtact** [comment]
@Iamgoofball if you ever claim again that I requested you to do something without having me actually requested you to do it I will permanently ban you from github, forums and discord and ask mso to put you on the blacklist

**Comment by optimumtact** [comment]
> Eat pant orange man.


https://user-images.githubusercontent.com/2544323/119631898-71315e80-be64-11eb-888f-d31d499ec7c1.mp4

**Comment by CRiPLe1000** [comment]
👏 👏 👏 
image
👏 👏 👏 
@maxymax13 like anyone cares enough for reddit """raid"""

Stop giving goof attention

**Comment by Iamgoofball** [comment]
not only did i not post this on reddit, but that post is from 18 days ago, come on

**Comment by CRiPLe1000** [comment]
First, you did not have enough time, second of all, you try to create a drama by posting how "tgstation is removing X", which is not only clickbaity, but also dishonest as its you that TRIES to remove it. Dude, take some responsibility and claim that its your work for fuck sake, at least people will know to ignore your bullshit.

**Comment by Iamgoofball** [comment]
4 hours is plenty of time to post on reddit, how slow do you think people type?

**Comment by NamelessFairy** [comment]
> 4 hours is plenty of time to post on reddit, how slow do you think people type? I didn't post this PR on reddit intentionally.

For reference the last reddit post had an 11-12 minute gap between the PR and the reddit post. If this was being posted on reddit it would have been done so by now

**Comment by CRiPLe1000** [comment]
> > 4 hours is plenty of time to post on reddit, how slow do you think people type? I didn't post this PR on reddit intentionally.
> 
> For reference the last reddit post had an 11-12 minute gap between the PR and the reddit post. If this was being posted on reddit it would have been done so by now

Ok, i take it back, my fault. The second point still stands in my opinion.

**Comment by legoscape** [comment]
> First, you did not have enough time, second of all, you try to create a drama by posting how "tgstation is removing X", which is not only clickbaity, but also dishonest as its you that TRIES to remove it. Dude, take some responsibility and claim that its your work for fuck sake, at least people will know to ignore your bullshit.

No, making drama by posting tg is removing x is kind of a standard post by now. 
image
It's a meme that our coder base removes content and hasen't added actual content for a while.

**Comment by Hamurlik** [comment]
just resprite cult to big chungus in responce to redditors

**Comment by legoscape** [comment]
This is a great idea.

**Pull request closed without merging**
