### PR TITLE
fixes entertainment monitor

### LINKED ISSUE #54607: Entertainment monitors don't work
## Reproduction:

1. Cause an entertainment monitor to go live by activating a motion sensitive camera in the thunderdome arena.

2. Teleport to the station and try examining or clicking on an entertainment monitor.

3. You expect to be able to see through cameras within the arena, but nothing happens.

### PR DESCRIPTION
**Pull request by Fikou**
## About The Pull Request

Makes the entertainment monitor actually work by giving it atom ui interact flag.
this isnt fully working yet so dnm, it needs to update as long as youre a viewer

## Why It's Good For The Game

this was broken for a year

## Changelog
:cl:
fix: fixes entertainment monitors! click on them to see entertainment
/:cl:

---

Closes #54607

### CODE REVIEW

**Comment by Cenrus** [comment]
Thanks, gonna close #54607

**Comment by Mothblocks** [comment]
I don't want this merged without these changes. I don't find them to be out of scope. If we just let entertainment monitors work at all times, then admins will have to know about that when using it for testing (as it's the easiest environment to test in), and people will watch the monitors expecting boring testing crap. 

Force admins to say "hey, we want this to show up on the monitors", and you make it so when people see an event is going on, they'll know it'll be good.

image

**Comment by Fikou** [comment]
mothblocks smells

**Comment by Mothblocks** [comment]
like what

**Comment by Fikou** [comment]
> like what

poop

**Pull request closed without merging**
