### PR TITLE
Adds custom epipens to plumbing chemical press.

### PR DESCRIPTION
**Pull request by Xander3359**
## About The Pull Request
This adds the ability to make custom medipens through the use of the rapid plumbing device in the chemical press.
## Why It's Good For The Game
Custom medipens have been requested multiple times over in the discord, I personally think it's a nice option to have for things such as emergency meds that require fast application in small amounts.
## Changelog
:cl:
add: Chemical Press can make custom medipens with a max capacity of 15 units.
/:cl:

### CODE REVIEW

**Comment by Cheshify** [comment]
15 units may be a little much if you can use this to instantly dunk 15u of harmful chems into people, or 15u of powerful chems into yourself.

**Comment by Cheshify** [comment]
Otherwise I actually really like this PR

**Comment by Helg2** [comment]
I don't think this is a good idea to add mass-produced traitor gear like this. Stuff like Nitrous Oxide or Lexorin will fuck you up even with 15u

**Comment by ZAMODA** [comment]
why not make it have a delay before applying, hell you could even have a lore reason for it, with it being a "knockoff" of normal pens.

**Comment by Helg2** [comment]
> why not make it have a delay before applying, hell you could even have a lore reason for it, with it being a "knockoff" of normal pens.

What's the differences between this and patches then?

**Comment by SgtHunk** [comment]
Isn't the entire point of custom medipens being unobtainable (unavailable through medipen refiller/chem dispenser) that it's not good design being able to dump chems into someone with no counterplay or good visual tell

**Comment by Jackal-boop** [comment]
Maybe have a sub type for these custom pens that have a do after and Inject their chems after a second or so

**Comment by YuliceTheDruid** [comment]
I wanna say this is the third time I've seen this PR, but it's most likely going to get slapped because yeah, an instant injection of 15u of any chem is insanely deadly, especially when you can do it without any windup or tells since medipens fit in a pocket or a boot.

**Comment by YuliceTheDruid** [comment]
> Maybe have a sub type for these custom pens that have a do after and Inject their chems after a second or so

This is literally just a regular syringe at that point

**Comment by blackdav123** [comment]
> > Maybe have a sub type for these custom pens that have a do after and Inject their chems after a second or so
> 
> This is literally just a regular syringe at that point

Patches already do this but with 40u capacity instead of 15.

**Comment by Fikou** [comment]
not happening

**Comment by Time-Green** [comment]
I'm sorry but no, instant injections are already broken, only saved by being traitor and CMO only. I am not convinced of your "Why this is good for the game" either.

How does this help with healing people? If someone's incapacited, you can just syringe them. If they're resisting treatment, their problem. This is nothing but a gamer tool to instantly end any confrontation. You fail to adress this at all

I'm just going to shut you down right now because I dont believe this can ever be good for the game

**Comment by Time-Green** [comment]
fikou ninja'd me but you get it

**Comment by Xander3359** [comment]
@Time-Green Would this be better if instant injection injection only works on self-use?
Idea being that you are able to instantly apply healing chems for self-use, but attempting to use it on someone else has a delay on it.

**Comment by Time-Green** [comment]
> @Time-Green Would this be better if instant injection injection only works on self-use?
> Idea being that you are able to instantly apply healing chems for self-use, but attempting to use it on someone else has a delay on it.

At that point it’d just be a labeled syringe, right? Not really much different than a patch but for the blood stream? I think I’d be okay with that, I don’t think fast self-application is really that much of a problem

**Comment by YuliceTheDruid** [comment]
> @Time-Green Would this be better if instant injection injection only works on self-use? Idea being that you are able to instantly apply healing chems for self-use, but attempting to use it on someone else has a delay on it.

This would literally work exactly like Syringes do currently. You can even inject all of a syringe at once by using it in hand to change the transfer amount.

**Pull request closed without merging**
