### PR TITLE
Adds a knockedout trait, begins refactoring mobility

### PR DESCRIPTION
**Pull request by Rohesie**
Atomizing #48923

* Adds `TRAIT_KNOCKEDOUT` for effects that force unconsciousness upon the user.
* Death coma trait and Unconscious and Sleeping status effects immediately add and remove themselves from the knockedout trait's sources as they come and go.
* Removed checks that are now superfluous as `stat` is updated immediately.

Chipping away the need to update mobility one piece at a time, and creating more generic checks.

### CODE REVIEW

**Comment by optimumtact** [comment]
conflicts

**Comment by Rohesie** [comment]
Github is extremely broken. I'll open a ticket and see if the support team can do something about it so I don't have to nuke the whole thing and fork again.

**Comment by Moja10** [comment]
Go Rohesie!!!

**Comment by Rohesie** [comment]
I don't have the appropriate emoji here to react to that.

**Pull request closed without merging**
