### PR TITLE
[April Fools] Live Moth Reaction

### PR DESCRIPTION
**Pull request by RigglePrime**
## About The Pull Request

Live moth reaction.
unknown (5)

## Why It's Good For The Game

*shrug

## Changelog

Nar Nar will now react to the station being blown up.

:cl: Riggle
add: Live moth reaction
/:cl:

### CODE REVIEW

**Comment by Kubisopplay** [comment]
This guy deserves maintainer

**Comment by Son-of-Space** [comment]
Live Moth Reaction

**Comment by RigglePrime** [comment]
Updated with gif :)

**Comment by themilkman420** [comment]
this should be merged

**Comment by bruhlookatthisdood** [comment]
> this should be merged
yes

**Pull request closed without merging**
