### PR TITLE
Kidnapping won't destroy implants, nodrop items

### LINKED ISSUE #73985: Kidnapping side objective deletes uplink implants present in other traitors.

### PR DESCRIPTION
**Pull request by Jacquerel**
## About The Pull Request

Fixes #73985
Kidnapping was looping through mob contents to find items to remove from you, rather than equipped items. It was then forcemoving them out of you, destroying the functionality of implants and nodrop items.

Being kidnapped will now only remove equipped items from you (not everything inside you) and will not forcemove nodrop items out of your inventory (so it won't confiscate your chaplain armblade).
Additionally, anything you picked up in the kidnapping area was being sent to nullspace on exit, I changed this to have them drop on the ground instead.

However, due to this long-standing convention we now have an expectation that items are not trivially moved in or our of the kidnapping area, so it also loops through any storage implants you may have and dumps their contents too.
There are still ways around this (cavity implantation, for instance) but they seem uncommon and restrictive enough that they're probably not a big deal.

## Why It's Good For The Game

Kidnapping another traitor destroying their implants was an annoying and unpleasant experience (especially if it was their uplink implant), and does not seem to have been intended.
Also removes weird behaviour where your arm blade might fall off because you got kidnapped.

## Changelog

:cl:
fix: Implants and items which you cannot drop will no longer be forced out of your character when you are kidnapped.
fix: Objects you try to take back from the kidnapping location as souvenirs will drop to the ground when you leave instead of being destroyed, except shirts and shoes (make sure to pick up your monographed synidcate T-shirt).
/:cl:

### CODE REVIEW

**Comment by coiax** [comment]
Let me ask a fair question: Why would we want to strip storage implants of people kidnapped? What could they bring in, and/or out that would affect things poorly?

**Comment by Teleported-Bread** [comment]
> Let me ask a fair question: Why would we want to strip storage implants of people kidnapped? What could they bring in, and/or out that would affect things poorly?
> 
> The 🌌 🧠 play is to calculate any items they're holding when they're returned, and have the Syndicate charge the station _extra_ for everything they bring back. (Sorry mate, but our hostage just brought back a katana, that's 500cr extra)

Letting people have stuff like tele beacons, the hand teleporter, hilbert's hotel, a red/blue box, and so on inside of the place people go when kidnapped is not a good idea. Also, this is mostly a fix pr, and it'd be weird for it to not fix everything.

**Comment by zxaber** [comment]
Did you check with tracking implants? IIRC those act as a teleport beacon.

**Comment by Jacquerel** [comment]
> Did you check with tracking implants? IIRC those act as a teleport beacon.

Tracking beacons should be covered by the area's `NOTELEPORT` flag, which should block _most_ methods of ingress/egress.
The storage dumping is more of an excess of caution for silly exceptions like bluespace bodybags or sapient pocket-sized simplemobs (who under the previous system would have been trapped in nullspace instead).

**Pull request merged**
