### PR TITLE
Vendors now tip in the opposite direction when struck from inside of a wall

### LINKED ISSUE #72873: Vending Machine Attacking Inside of Wall
## Round ID:

ROUND - 198656

## Reproduction:

Got Stuck in Wall as Nightmare via Jaunting. Due to light being able to go through walls. Got stuck in the corner of the wall with Vending machine the only possible escape. AFter hitting the vending machine fell (no damage) then after another hit it crushed me through wall without moving.

### PR DESCRIPTION
**Pull request by Rhials**
## About The Pull Request

When someone standing on a closed turf strikes a vendor, the vendor will now instantly tip over, in the _opposite_ direction. This will provide no chance for goodies, meaning you cannot build walls on top of yourself and abuse this for free stuff.

https://user-images.githubusercontent.com/28870487/213960163-e520d6fc-ab3f-4b56-9fcb-ca9859b11631.mp4
## Why It's Good For The Game

Leaving your jaunt in a wall and having some unexpected piece of machinery blocking you in is a very common occurrence, whether it be while playing nightmare, wizard, or heretic. If it's a console or machine, you just bash it down with whatever you have handy, but if that machinery happens to be a vendor, you're screwed. 

This should preserve the risk/reward of hitting vendors for free stuff, without fucking over people who unexpectedly jaunt into a bad position.

Most importantly -- Vendors can't crush people through walls. That doesn't make any sense! They don't even move onto your tile!

Closes #72873.
## Changelog
:cl:
balance: Hitting a vendor from inside a wall will cause it to fall away from you, rather than crushing you without being able to move to your tile.
/:cl:

### CODE REVIEW

**Comment by Pumpkinoe** [comment]
This might cause some really funny shenanigans honestly

Imagine a wizard jaunting behind a vending machine and accidentally pancaking someone unexepcted

**Comment by improvedname** [comment]
unanchor vendor, tactical vendor combat now!!

**Comment by private-tristan** [comment]
my (unsuspecting) target watching me drag a vending machine next to them and watch as I build a wall under my feet:

**Comment by Shadowflame909** [comment]
Prank em john

**Pull request merged**
