### PR TITLE
Cat people can now be heads again

### PR DESCRIPTION
**Pull request by RemieRichards**
The CEO of nanotrasen married a catgirl and decided this is the truth now.

### CODE REVIEW

**Comment by optimumtact** [comment]
This is a config option, but nice bait

**Comment by RemieRichards** [comment]
@optimumtact false, the config is for deciding if roles can be heads, not for undoing their parts, this does not remove that config option, merely ONE of its effects

**Comment by dannno** [comment]
*does a backflip* wahoo yip yipee *karate kicks you in the head* wachaaaaa hoo wah yip wahoo

**Comment by KorPhaeron** [comment]
Already a config option. If catgirls existing is a headmin issue than so is this

**Comment by RemieRichards** [comment]
@KorPhaeron Please read.

**Comment by dannno** [comment]
hiyaaahhhh *chops a wood block in half* hoooowaaaaahhhhhh *takes a martial stance*

**Comment by optimumtact** [comment]
Grove street, home, at least it was until I fucked everything up

**Comment by The-clown-known-as-Pepe** [comment]
@Iamgoofball 

summoning the goof because i want to laugh at his retarded reasoning for this not to be merged

**Comment by obscolene** [comment]
@KorPhaeron 24 hour rule

**Comment by KorPhaeron** [comment]
If the config option is on, they become heads but lose their ears

If the config option is off, they become heads and keep their ears

If you remove this then even with protect authority enabled they will keep the ears

You're essentially removing the config as far as it pertains to cat people

**Comment by dannno** [comment]
ooowwwwwwoooaahhh *muscles tense as i extend my arms and prepare for a crane kick*

**Comment by lzimann** [comment]
https://github.com/tgstation/tgstation/commit/96d24a8133eebc5bf1c01bf82bdff0f01cfd7a21

**Comment by RemieRichards** [comment]
@KorPhaeron "as far as it pertains to cat people"
Yes, the config remains in place for other species.

**Comment by RemieRichards** [comment]
@lzimann not relevant.

**Comment by optimumtact** [comment]
All you had to do was follow the train CJ

**Comment by lzimann** [comment]
It is relevant. You either remove this and return the other thing, or leave as it is.

**Comment by Mark9013100** [comment]
Aw shit, here we go again.

**Comment by KorPhaeron** [comment]
The only thing this PR will accomplish is 24 hours of drama followed by this being closed or it being merged and catgirls disabled

**Comment by dannno** [comment]
HHHWWWWACHA *DOES A DEVASTATINGLY POWERFUL CRANE KICK INTO KORS STUPID HEAD*

**Comment by KorPhaeron** [comment]
*dodges*

**Comment by dannno** [comment]
EHHHHHHHHHHHHHHHHH?

**Comment by dannno** [comment]
HHHHHHWWWHHAAAATTAAAA *does a triple backflip to create space as i reevaluate the power level of my opponent*

**Comment by RemieRichards** [comment]
@dannno n-nani!?

**Comment by ShadowDeath6** [comment]
When it was first implemented it pertained to catpeople, you should make a different config if you want to separate nonhumans and mutant humans

**Comment by dannno** [comment]
*crouches low and quickly throws a salvo of throwing stars at everyone on this pr*

**Comment by Magikarpet** [comment]
danno do you want a kitkat i've got one with me

**Comment by optimumtact** [comment]
I’ll have two number 9s, a number 9 large, a number 6 with extra dip, a number 7, two number 45s, one with cheese, and a large soda.

**Comment by dannno** [comment]
HMPH *deftly combat rolls past karp and grabs the kitkat and then jumps into the rafters*

**Comment by The-clown-known-as-Pepe** [comment]
@KorPhaeron *pets blorble*

**Comment by dannno** [comment]
ohhhhhh *is intrigued by the kitkat because im a ninja and i dont eated gaijin food before only pocky*

**Comment by sawrge** [comment]
@oranges fries with that? Also would you like to supersize to an XL Baja Blast 2: Son of the Dew for an extra dollar

**Comment by DoctoreMad** [comment]
THE JAPANOFORNIA VERSUS SOUTHERN NORTH KOREA RAGES ON

**Comment by dannno** [comment]
*jumps down from the rafters* AYAYAYA OOOOOUUHHH *cartwheels at sawrge and does critical damage*

**Comment by Mark9013100** [comment]
YOU PICKED THE WRONG HOUSE FOOL!

**Comment by sawrge** [comment]
*charges my birdlaser aimed directly at dannos head, gathering several types of macromolecular pseudoions into one powerful energy beam of radiation*

**Comment by dannno** [comment]
*my eyes widen as the incredible blast washes over me and the screen turns white*

**Comment by RemieRichards** [comment]
*grabs popcorn

**Comment by sawrge** [comment]
*uses pieces of the ionized danno to craft D4/\/ N0, the final android in my robot army* NOW YOU SHALL ALL SEE *leads an armed revolt on coderbus*

**Comment by dannno** [comment]
ＰＥＲＩＳＨ ＭＯＲＴＡＬＳ *opens my robot mouth to fire my robot mouth laser at the coderbus* 	ＡＡＡＡＡＡＡＡＡＡＡＡＡＡＡＡＡＡＡＡＡＡＡＡＡＡＡＡＡ

**Comment by dannno** [comment]
＊ＳＵＰＡＡＡＡ＊

**Comment by KorPhaeron** [comment]
*throws food in dannos mouth*

**Comment by kevinz000** [comment]
Lmao

**Comment by Aliannera** [comment]
what the

**Comment by dannno** [comment]
*eats it* ＯＭＮＵＭＮＵＭＹＵＭ ＭＭＭＭ 	ＷＡＩＴ ＦＵＣＫ

**Comment by sawrge** [comment]
*robots rip apart kor Phaeron and Lzimann and Remie Richards but oranges is spared because she was a plant the whole time*

**Comment by dannno** [comment]
*begins to spark and go critical* ＭＡＳＴＥＲ Ｉ ＴＯＵＣＨＥＤ ＴＨＥ ＶＥＩＬ ＯＦ ＬＩＦＥ ＳＡＶＥ ＭＥＥＥＥＥＥＥＥ

**Comment by The-clown-known-as-Pepe** [comment]
@kevinz000 *pets kevinz*

**Comment by sawrge** [comment]
You've done all you can........

...my son.

**Comment by Iamgoofball** [comment]
# SLIPPERY SLOPE

**Comment by dannno** [comment]
ＯＨ *explodes real big*

**Comment by kevinz000** [comment]
>goof was right

**Comment by dannno** [comment]
the PR is exploded now

**Comment by ShadowDeath6** [comment]
goof should be maintainer to avoid the slippery slope from the get go

**Comment by Magikarpet** [comment]
both of you siltbreaker is fucking out asotpo roleplaying you cutts play it it gives youlevels on your compendium

**Comment by sawrge** [comment]
*Pieces of robot go flying everywhere. For miles, mechanical shrieks can be heard as their central programming faults and their brains short circuit, ending their existence. The coders are freed. The remaining machines jerk erratically before powering down, falling into heaps among their brothers. Amongst the more damaged ones, crimson pools from their forms. Blood. Metal is shed to reveal flesh, now rent from the bones. The brothers of Dannoman, those that had followed him, those that wanted nothing more than to protect their sibling, their friend. Dr. Sawrge buckles to the ground in tears. He awaits his fate.*

**Comment by Magikarpet** [comment]
http://blog.dota2.com/2017/06/exclusive-battle-pass-campaign-siltbreaker-act-i/ im NOT JOGKIN

**Comment by The-clown-known-as-Pepe** [comment]
>removing roleplay features

/hippie/station

**Comment by optimumtact** [comment]
"roleplay" features

**Comment by The-clown-known-as-Pepe** [comment]
"""""""""roleplay""""""""" features

**Comment by kevinz000** [comment]
Now we know players aren't the issues with the slide to hippie.

**Comment by optimumtact** [comment]
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""roleplay""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""" features

**Comment by lzimann** [comment]
@Magikarpet i don't need more levels though!

**Comment by The-clown-known-as-Pepe** [comment]
/"""""""""hippie""""""""/station

**Comment by optimumtact** [comment]
@kevinz000 that's rich coming from someone who maintains code for citadel

**Comment by Aloraydrel** [comment]
imagine getting mad over pixels lel

**Comment by optimumtact** [comment]
@Aloraydrel didn't you advocate for the banning of ERP?

**Comment by The-clown-known-as-Pepe** [comment]
@optimumtact we already have vore on alien hunters


you may want to remove that @Iamgoofball

**Comment by WJohn** [comment]
You can also eat monkeys if you're obese.

**Comment by optimumtact** [comment]
SLIPPERY SLOPE

**Comment by The-clown-known-as-Pepe** [comment]
WHO IS LUBBING THE SLOPE, HELP

**Comment by Aliannera** [comment]
help i can't stop slipping fucking clown

**Comment by The-clown-known-as-Pepe** [comment]
>slipfucking clown

l-lewd

**Comment by Repukan** [comment]
What the fuck

**Comment by Aliannera** [comment]
In all honesty lets not do this. Keep it as a config you silly coders.

**Comment by Mark9013100** [comment]
UPBOATED

**Comment by Aloraydrel** [comment]
Sorry my trap gf is a cat girl so I want erp back now

**Comment by Iamgoofball** [comment]
Are you ok remie, first it's claiming cat mutations aren't optional and now repeatedly reopening your own PR

I don't get to reopen my own meme PRs

**Comment by obscolene** [comment]
@Iamgoofball yeah because your maintainer erp buddies do it for you

**Comment by optimumtact** [comment]
you've lost it obscolene, you've lost it!

**Comment by Iamgoofball** [comment]
The separation between my asshole and PRs is absolute unless its goatse

**Comment by Pascal125** [comment]
Why do people feel the urge to meme on a PR like this.
Just congratulate the CEO of Nanotrasen and deal with it.

**Comment by Repukan** [comment]
👎

Keep nonhumans from head roles.

**Comment by factoryman942** [comment]
nyaa 🐱 🐱 🐱 🐱 🐱

**Comment by Repukan** [comment]
Also this will deal to a huge fucking can of worms with silicon policy

**Comment by Pascal125** [comment]
That is quite frankly my expression when i see the silly arguments exerted as a result of PR's like this. Yes.

**Comment by Aliannera** [comment]
I'd hate to say it, but Repukan is right.

**Comment by Repukan** [comment]
😘

**Comment by Cheridan** [comment]
anime was a mistake

**Pull request closed without merging**
