### PR TITLE
Adds Anacea as a makeable toxin

### PR DESCRIPTION
**Pull request by swindly**
:cl: Swindly
add: Adds a new toxin: Anacea. It metabolizes very slowly and quickly purges medicines in the victim while dealing light toxin damage. Its recipe is 1 part Haloperidol, 1 part Impedrezene, 1 part Radium.
/:cl:

It's still a better tator toxin than formaldehyde.

### CODE REVIEW

**Comment by ExcessiveUseOfCobblestone** [comment]
what happens when you do charcoal+this? is it an arms race?

**Comment by swindly** [comment]
They purge each other, but anacea will win.

**Comment by Iamgoofball** [comment]
yeah, you're gonna want calomel for this fucker

**Comment by kevinz000** [comment]
:-1: Too powerful for non traitor toxin.

**Comment by XDTM** [comment]
Calomel is a medicine! Really, this + any poison both makes the poison unpurgable and prevents 95% of the ways of curing toxin damage. Too strong until we have a non-chem based way of purging chems, like a dyalisis machine or something.

**Comment by swindly** [comment]
>Not powerful enough to be a traitor toxin

>Too powerful to be a non-traitor toxin

😕

**Comment by PKPenguin321** [comment]
This is fine but maybe exclude it from purging certain chems, like calomel

**Comment by swindly** [comment]
Its normal purge is now lowered from 6 to 5 units per tick. If the victim has calomel or pentetic acid, the purge for all medicines is reduced to 0.5 units per tick.

**Comment by Supermichael777** [comment]
drink uhhh fuck Millk? no lime! wait its one of these all natural botany juices......

**Comment by ExcessiveUseOfCobblestone** [comment]
stop teaching people the power of botany michael!

**Comment by FantasticFwoosh** [comment]
Welp time to spam 200 units of iced tea made from the infinite bartender dispenser.

**Pull request merged**
