### PR TITLE
Replaces chasms from lavaland tendrils with lava.

### PR DESCRIPTION
**Pull request by CRITAWAKETS**
## About The Pull Request

This PR replaces the chasms from the tendrils that spawn when they are destroyed with argueably less deadly lava. This PR does not change the clown ruin's chasms, as per the destructive nature of clowns and because they are easier to avoid.

## Why It's Good For The Game

Getting instantly killed and becoming unclonable because you didnt see some different pixels in your meson view is not fun.

## Changelog
:cl:
balance: Lavaland legion tendrils now spawn lava instead of chasms.
/:cl:

### CODE REVIEW

**Comment by Tlaltecuhtli** [comment]
hugbox u can literally be chasm proof with jaunter on belt

**Comment by Onule** [comment]
> 
> 
> hugbox u can literally be chasm proof with jaunter on belt

do jaunters work if it's attached to an explorer's webbing on belt?

**Comment by Tlaltecuhtli** [comment]
it says belt slot

**Comment by wesoda25** [comment]
Chasms suck

**Comment by Arathianen** [comment]
What wesoda said. Fuck chasms.

**Comment by shellspeed1** [comment]
> 
> 
> > hugbox u can literally be chasm proof with jaunter on belt
> 
> do jaunters work if it's attached to an explorer's webbing on belt?

Nope

**Comment by LoGIRz** [comment]
I've died to a chasm with a jaunter on because I got caught by a goliath tendril. If the one supposed hard counter can't absolutely guarantee your safety and you can't do anything else while you're "still alive and falling" like crush a bluspace crystal or use a hand tele chasms feel like snowflake code

**Comment by bgobandit** [comment]
chasms are also extremely shitty if you are lagging

**Comment by zxaber** [comment]
Chasms are great for the initial rush where you have to grab the box in the time limit. After that, they're unfun and bullshit traps for some other unrelated miner to bumble in because the lighting decides it wants to update once a minute.

Overall, good change, but maybe consider making an initial explosion, perhaps one that also specifically gibs anyone within the old area (and deletes the box), to preserve the one good part of chasms.

**Comment by Tlaltecuhtli** [comment]
if you are lagging ypu are gonna die from anything else

**Comment by Dawson1917** [comment]
be dragging box back to base
some other miner destroyed a tendril at some point
5% darker patch of ground appears on screen for half a second, don't notice in time
permanently deleted from round

engaging

**Comment by daklj** [comment]
thats lavaland for you, pick a different role, be more careful or use a jaunter if you don't like perma dying)))

no need to hugbox hardcore gamers playground

**Comment by Dawson1917** [comment]
> 
> 
> thats lavaland for you, pick a different role, be more careful or use a jaunter if you don't like perma dying)))
> 
> no need to hugbox hardcore gamers playground

there's hugbox and then there's getting rid of random insta-death tiles that not a single person finds entertaining to any degree, ever

**Comment by nicbn** [comment]
>no need to hugbox hardcore gamers playground

Is this sarcasm?

**Comment by ExcessiveUseOfCobblestone** [comment]
If you have a conceptual issue with chasms then PR a change to them rather than slowly phase them out while keeping them the same trashiness associated with them.

If they're legitimately not fun then keeping them in as-is makes no sense.

**Comment by FloranOtten** [comment]
They're not fun whatsoever. Oh boy, I didn't notice the gamer patch because my light is still illuminating a spot 50 yards away, guess I'm permanently round removed!

**Comment by ExcessiveUseOfCobblestone** [comment]
Right... so my follow up would be why is this PR just touching the ones associated with chasms if ALL of them, regardless of situation, is not "fun"?

**Comment by MCterra10** [comment]
Perhaps a timer after which the chasms despawn would be good. Still have the rush of grabbing the box and legging it back down the tunnel, and loot still vanishes if you don't get it in time, but you don't Insta die 30 minutes later because you forgot about that spot

**Comment by zxaber** [comment]
@cobby
The clown ruin chasms aren't as bad, because they are always at the same spots around the outside. They can be learned and thus expected.

**Comment by ExcessiveUseOfCobblestone** [comment]
I was under the impression chasms were to cause cautiousness.

If you can basically ignore them because you know where they spawn consistently, that seems to defeat the purpose. I wouldn't consider those instances warranting for keeping them in.

That said, I don't like outright removal of them. Any instance where a jaunter is on your belt and you're still dying to chasms can be considered a bug.

**Comment by Tlaltecuhtli** [comment]
having the chasm spawn and then disapear Xs later seems  the  middleground

**Comment by ExcessiveUseOfCobblestone** [comment]
Just... fix any jaunter bugs?

There's so many tools to mitigate this issue I don't see how anyone dies to this unless you're just running flippantly, which is what chasms are suppose to btfo

**Comment by CRITAWAKETS** [comment]
"so many tools"

lets see all the tools that can help. Jaunter and thats it.

The jaunter takes up your belt slot which doesnt sound that bad, but for a miner thats basically being unable to mine and fight at the same time since you can have a medipen in your pocket or your mining scanner. Reminder that the other pocket HAS to be taken up for your mining satchel.

**Comment by ExcessiveUseOfCobblestone** [comment]
Sandbags and the darksouls pebbles can be used to either halt you from stepping into the chasm OR be used to mark a tile that's adjacent to a chasm.

**Comment by ExcessiveUseOfCobblestone** [comment]
Yes, chasm protection comes at a cost. Welcome to lavaland.

**Comment by CRITAWAKETS** [comment]
lava also hurts when you walk into it and you can be stopped with sandbags

the difference is just that one burns you to death although you can be husked and is easily visible while the other just instantly deletes you, making you unclonable while being basically invisible

**Comment by zxaber** [comment]
Re: sandbags and glowstones
These require the miner that killed the tendril to place them down. Chasms aren't a huge issue for the miner that makes them; they'll remember where the pit is. It's an issue for everyone else that walks through lavaland and doesn't know the pit is there.

If chasms weren't insta round remove, they wouldn't be such a big deal. It's a combonation of round remove, trouble seeing them especially when lighting updates lag behind, and the only real counter being something you have to completely give up a belt slot for. None of it is fun except the initial rush when grabbing a chest before the chasm collapses and kills you.

**Comment by ExcessiveUseOfCobblestone** [comment]
https://tgstation13.org/phpBB/viewtopic.php?f=10&t=8278&hilit=chasms&start=50

**Comment by necromanceranne** [comment]
I mean didn't you yourself say stuff like chasms was bad for the game as permanent round removal was too common? This is a pretty easy way to get removed from the round by pure accident by simply walking into them during light lag/actual lag.

**Comment by carlarctg** [comment]
i for one would like to see my belt slot not be Designated Obvious Jaunter Slot as that's really lame. like said above you kind of need one because lag WILL fuck you over otherwise eventually

i know "oooga boooga comes at a cost" but "cost" doesn't mean "literally only option, use 750 credits on this or hope lag doesnt fuck you over"

**Comment by Dorsisdwarf** [comment]
Maybe the Jaunter should just work from anywhere in your inventory so miners actually use it

**Comment by ExcessiveUseOfCobblestone** [comment]
> I mean didn't you yourself Cobby say stuff like chasms was bad for the game as permanent round removal was too common? This is a pretty easy way to get removed from the round by pure accident by simply walking into them during light lag/actual lag.

No, I did not say chasms were bad for the game (because round removal was too common). I did say perma round removal options were bad In a general context though. Going to lavaland to toss someone into a chasm located randomly between rounds vs. Crematorium/Gibber/Shuttle Gibbing all semi-evenly strewn across the map at persistent locations are a bit different, however. Heck, the most common way to get to the chasms from the station involve a perma-removal.

Removing chasms partially or even wholesale would not fix what you're referencing.

To be clear, I don't mind changing them mechanically to not perma-delete you. I think they should independent of lava though so that it requires different mechanism to traverse.

That said, you guys need to git gud. Lighting/Lag doesn't matter if you're going how you came. You have pebbles (mark where TO or NOT TO go, idc), sandbags, and literally every tool available to materials since they can be smelted either by welder or by lava.

**Comment by zxaber** [comment]
Again, it's not an issue if you're the miner that made the chasm. It's easy to remember where the chasms are, but can be hard to catch one made by another player.

**Comment by ExcessiveUseOfCobblestone** [comment]
how does a player "make" one? Only thing I can think of is tendies. You should know if there's a tendy nearby your path...

**Comment by CRITAWAKETS** [comment]
thanks cobby now im going to validhunt every miner that doesnt blockade the chasms they create, very cool!

**Comment by ExcessiveUseOfCobblestone** [comment]
You can't even win against something that doesn't move or attack, I'm not too worried about you PKing. Just be sure to obey escalation (don't leave them on lavaland, that's basically lockering tbh).

Also says quite a bit when you try to use holding people responsible for creating dangerous hazards to do a bare minimum in keeping the area safe as a downside. 

Anyways, I already said you could change the chasm to not be so damning. Heck you could also make a ghost tendril that faintly lights up the chasm space after tendy death if you wanted to so it's a static light, eliminating all but actual lag and player stupidity (both of which are more/less out of my hands).

**Comment by zxaber** [comment]
>You should know if there's a tendy nearby your path...

They only give off GPS coordinates when they're alive. If you're digging a tunnle that happens to intersect another miner's path, or you're just following their path, it's quite easy to stumble upon a pit from a tendril you never knew existed.

I'm not really sure what the appeal of keeping chasms is. They're not really fun to avoid if you see them. They're certainly not fun to fall into when it means you're uncloneable and ded. I guess falling in with a jaunter might give a sense of satisfaction at your preparedness, but I feel like it would just be annoyance that you have to buy another jaunter and work your way back to where you were (abet with a bit of relief that you're not dead).

**Comment by fludd12** [comment]
I feel like the people arguing for removal dig straight down in minecraft.

On topic, though, chasms already give off a slight glow, making them visible even in darkness.  Even without this, lavaland is truly _supposed_ to be a place where you are wary of walking in any new area. How does "I lagged and fell into a pit that deletes me" differ from "I lagged and walked into a dragon that deletes me," aside from the fact that one moves and the other doesn't?

The change doesn't personally affect me, so I won't argue _too_ heavily against removal if that's what people want, but I kinda think it's solving a problem that is better addressed by players.

**Comment by ExcessiveUseOfCobblestone** [comment]
> If you're digging a tunnle that happens to intersect another miner's path, or you're just following their path, it's quite easy to stumble upon a pit from a tendril you never knew existed.

If you traverse the unknown knowing chasms may exist during a lightlag spike or all around lag spike I'm not sure what to tell you. If it's not during either, i'm also not sure what to tell you. Watch your step?

>I'm not really sure what the appeal of keeping chasms is. They're not really fun to avoid if you see them. They're certainly not fun to fall into when it means you're uncloneable and ded. I guess falling in with a jaunter might give a sense of satisfaction at your preparedness, but I feel like it would just be annoyance that you have to buy another jaunter and work your way back to where you were (abet with a bit of relief that you're not dead).

They're not "fun" in the sense that one gets a joy when seeing chasms (I don't), they're "fun" in the sense they add to the challenge and harshness of lavaland.

**Comment by Learner10** [comment]
What about taking things in a new direction? Where stepping off a ledge into a chasm gives a 30 second to a minute of grace period for someone to save your ass before you plummet into a bottomless pit? Essentially, it'd make Jaunters still viable (and maybe even give you time to pull them out), reduce the frustration of insta-death from invisible floors, keep the absolute death threat rush of "GET DAT BOX".

If this is not viable, option 2 is making the chasms more noticeable. Half of the issue with them is how simply impossible it is to spot them. Give a tiny red spot in the middle of them like they've got very deep lava pools, or something like that, and they'd stand out just a little more.

**Comment by ExcessiveUseOfCobblestone** [comment]
I'm fine with Option 1 (wyci). Option 2 I'm not sold on, they're supposedly not hard to avoid (or are they?) when you're not experience lag.

**Comment by YakumoChen** [comment]
>The jaunter takes up your belt slot which doesnt sound that bad, but for a miner thats basically being unable to mine and fight at the same time since you can have a medipen in your pocket or your mining scanner. Reminder that the other pocket HAS to be taken up for your mining satchel.

mfw he doesn't know the scanner works in your box
mfw he doesn't know about Boot Slots for medipens
mfw he can't hodl a plasma cutter and PKA at the same time to mine and fight
mfw he uses anything in his second pocket besides a light or GPS or legion core, the only items that benefit from pocket slots

miner newbie detected, I guarantee he duel wields PKAs and probably thinks Heirophant is a difficult megafauna. Get good bro, Lavaland is rules of nature, if you can't handle one of the several ways you can perma-die you should stay back on station as one of the hugbox jobs.

**Comment by MCterra10** [comment]
Elitist miners smh

**Comment by KowardKrusher** [comment]
this some googoogaga shit

**Pull request closed without merging**
