### PR TITLE
Improves bee lore

### PR DESCRIPTION
**Pull request by Iamgoofball**
:cl: Iamgoofball
experimental: Improves bee lore.
/:cl:

### CODE REVIEW

**Comment by Iamgoofball** [comment]
I think we have the WORLD RECORD CLOSE FOLKS

TAKE THAT @Bawhoppen

**Comment by Iamgoofball** [comment]
SUB 10 SECOND WORLD RECORD ANY%

**Comment by PKPenguin321** [comment]
This is top PR material though

**Comment by Bawhoppen** [comment]
fuckkkkkkkkkkkkkkkkkkkkkkkkkkk my record

**Comment by blobbernaut** [comment]
porting to hippie as i write

**Pull request closed without merging**
