### PR TITLE
[WIP] Adds a new emergency shuttle

### PR DESCRIPTION
**Pull request by redmoogle**
Adds a new emergency shuttle named "Centcomm Flagship Shuttle"

Reasons why it is good

- Unique from, other shuttles

- Might pull people away from buying shitty shuttles

It cost 75 Thousand credits (75,000) and might interest people to buy it rather than something like "Oh, Hi Daniel"

TODO: Garden Area

Comes with a big bridge and engineering
Comes with some tcomms
Comes with vendors
Has a lot of(9 Specifically EVA, 2 Atmos, 2 Engi) Suit Storage Units
Medbay comes with cryo and chem

Has 4 drones(BarDrone, EngiDrone, MedDrone, SecDrone)

Pictures:
image

## Changelog
:cl:
rscdel: Be a colossal fuck up and accidentally delete datums 
rscadd: Adds the Centcomm Flagship for 75,000c
/:cl:

### CODE REVIEW

**Comment by redmoogle** [comment]
Exitited twice on the last two builds with exit code 1 what did it mean by this

**Comment by redmoogle** [comment]
also who made the travis bot get triggered over spelling centcomm like centcomm and not centcom

**Comment by Ratvar** [comment]
Not enough cyborg chargers for a flagship, i think. Maybe a functional AI core?

**Comment by Barhandar** [comment]
You need to actually follow changelog format.

**Comment by WJohn** [comment]
No. Absolutely not. 1 million credits is a fuckton, and this shuttle is awful.

image

**Comment by redmoogle** [comment]
It's not done quite yet you could just suggest a price change or more stuff

**Comment by redmoogle** [comment]
Anyways what about 250,000 Credits? @WJohn

**Comment by redmoogle** [comment]
Don't know where that rouge door for the entrance came from. Must have had it accidentally selected

**Comment by elyina** [comment]
Could you add one or two small cells to the brig area, like the donut station and (I think) raven shuttle have? I love those.

**Comment by redmoogle** [comment]
Alright I'll get on to that; I'll also update the pictures

**Comment by Electronics** [comment]
I think it needs a good number more seats as well.

**Comment by redmoogle** [comment]
Already did that but I need to put some ert spawners in

**Comment by knacker48** [comment]
On the normal shuttle there's an airlock near the back so that people on the outside can get in. Would that be something you would be able to add?

**Comment by nemvar** [comment]
May I suggest a  sink and a fridge with rice/flour for the kitchen.

**Comment by redmoogle** [comment]
The kitchen has been outright moved will add some donkpockets

**Comment by redmoogle** [comment]
also yes i can add the airlock I've just been sick so I haven't been to productive

**Comment by anconfuzedrock** [comment]
lmao the cockpit has 1 less seat than the rest of the ship what is this meme we have the syndie gun shuttle or the asteroid one if we want a good shuttle

**Comment by redmoogle** [comment]
@anconfuzedrock the thing that sets this shuttle apart is the partial tcomms and the 4 drones on the shuttle

**Comment by anconfuzedrock** [comment]
Partial tcomms is mostly useless and drones are a negative
Inb4 bought on blob for drones
Jk daniel would be bought for money

**Comment by redmoogle** [comment]
At this point I feel like I'm effectively getting nowhere with this and have decided to close it, and dedicate myself to more important projects.

**Comment by PKPenguin321** [comment]
Don't worry about it, mapping takes a while to get good at and you have to fail a few times before you get the swing of it.

**Comment by redmoogle** [comment]
i have some higher priority such as the hoom project

**Pull request closed without merging**
