### PR TITLE
Nerfs the 357 revolver's damage from 60 to 40

### PR DESCRIPTION
**Pull request by SlasherX01**
## About The Pull Request
The 357 revolver will do 40 damage per shot instead of 60

## Why It's Good For The Game
i believe the 2 shot kill is too powerful for a traitor item even with its high TC cost, a 3 hit kill makes it a viable option but a bit less horrible to play against, even if you wear armour you still won't be able to take many shots due to its high damage so it also lacks counters. the release of prog tots actually removes the fact that "oh its costs alot of tc don't nerf it" due to their ability to swiftly gain TC.

## Changelog

:cl:
balance: the 357 revolver does 40 damage per shot instead of 60
/:cl:

### CODE REVIEW

**Comment by moocowswag** [comment]
Im not sure what to think about this, its a powerful ranged weapon weapon with limited counters, maybe if it made a unique sound when you pull it out itl be more... "telegraphed?"

Maybe take out some of the wound malus to compensate for the nerf? From -30 to -20? Im pretty sure damage amount is considered when wounds are rolled so by nerfing the malus too it should keep a similar wound chance.

Unless you want to nerf the wound chance ontop of the damage in which case ignore the last paragraph.

**Review by Fikou — CHANGES_REQUESTED** [review]
Your changelog or PR body doesn't mention the cost change.

Your "Why it's good for the game section" is incredibly small and not sufficient for changing the balance of one of the most reliable traitor weapons.

**Comment by DaydreamIQ** [comment]
I'm personally alright with this since it'd make gatfruit weaker as a whole, but the deagle PR would make this entirely irrelevant if that goes through

**Comment by Helg2** [comment]
Shield? Never heard of it

**Comment by Pickle-Coding** [comment]
Can you explain why an antagonist being scary is bad? Unless people murderboning the entire station with this is a meta, I don't see a problem with this.

**Comment by SlasherX01** [comment]
> Can you explain why an antagonist being scary is bad? Unless people murderboning the entire station with this is a meta, I don't see a problem with this.

i dont like the idea of a 2 hit gun, and it really doesnt matter if you have armour because that changes the hits from 2 to 3 this pr would actually give you a chance against this gun.

**Comment by SlasherX01** [comment]
> Can you explain why an antagonist being scary is bad? Unless people murderboning the entire station with this is a meta, I don't see a problem with this.

you can easily murderbone with this,  most normal crew members are unarmoured (2 shot kills) so its only a matter of time

**Comment by moocowswag** [comment]
> > Shield? Never heard of it
> 
> they'll break in 1-2 bullets in a fight against a 357

1-2 more hits can double your survivability altho its rng heavy.

(The real answer is to just spam glass windows)

**Comment by ATH1909** [comment]
> i dont like the idea of a 2 hit gun, and it really doesnt matter if you have armour because that changes the hits from 2 to 3 this pr would actually give you a chance against this gun.

you could alter the minimum delay between shots instead of the projectile's damage, then, no? the ebow two-shots as well (IIRC) and nobody complains about that.

the .357's entire schtick is being a monstrously powerful revolver; nerfing its damage per shot greatly diminishes it's appeal.

**Comment by Jackal-boop** [comment]
> > Can you explain why an antagonist being scary is bad? Unless people murderboning the entire station with this is a meta, I don't see a problem with this.
> 
> i dont like the idea of a 2 hit gun, and it really doesnt matter if you have armour because that changes the hits from 2 to 3 this pr would actually give you a chance against this gun.

The gun is meant to be powerful. It's got a loud ass telegraph and leaves casings on the floor. This things main gimmick is being able to put down people near instantly in a fast and bloody and loud way. Also you can't exactly murder bone with it. You can't use speed loaders with it, which means once you run out of rounds you need to dedicate a good amount of time to reloading the cylinder

**Comment by ATH1909** [comment]
> > > Can you explain why an antagonist being scary is bad? Unless people murderboning the entire station with this is a meta, I don't see a problem with this.
> > 
> > 
> > i dont like the idea of a 2 hit gun, and it really doesnt matter if you have armour because that changes the hits from 2 to 3 this pr would actually give you a chance against this gun.
> 
> The gun is meant to be powerful. It's got a loud ass telegraph and leaves casings on the floor. This things main gimmick is being able to put down people near instantly in a fast and bloody and loud way. Also you can't exactly murder bone with it. You can't use speed loaders with it, which means once you run out of rounds you need to dedicate a good amount of time to reloading the cylinder

did somebody remove the .357 speedloader from the uplink??

**Comment by ATH1909** [comment]
also, progression_minimum exists as a variable you can tweak if you want to make sure that the crew has access to enough gamer gear to deal with a .357 'boner. you could even alter the progression_minimum of the speedloader instead of the gun itself if you want to limit 'boning but not brutal, isolated murders

**Comment by Redrover1760** [comment]
> I'm personally alright with this since it'd make gatfruit weaker as a whole, but the deagle PR would make this entirely irrelevant if that goes through

The issue is gatfruit, not the .357

**Comment by RuneQuester** [comment]
I have rarely seen the .357 used for a large-scale murderbone. Why? Because, yes, it has the highest base damage of any weapon tied with the pulse rifle, but its a *gun*. This means it has ammo, and you need to actually HIT the target. The DESWORD, on the other hand, has a 100% hit rate if you click your target in melee, consumes no ammo, and does fantastic damage, and has blocking. 

It doesn't need a nerf! It really doesn't!

**Comment by CRITAWAKETS** [comment]
i've rarely seen the .357 used for murderbone because pretty much everyone feels bad after using it because its so damn OP

**Comment by optimumtact** [comment]
Finish removing stuns first and we can talk

**Comment by Technical-l** [comment]
i know im late as fuck here but you say that 357 has no counters and yet simply wearing bulletproof armor raises the shots to kill from 3 (regular armor vest) to 5. it drops a 60 damage gun to 24 damage

**Pull request closed without merging**
