### PR TITLE
Add a new holodeck program: photobooth

### PR DESCRIPTION
**Pull request by Lett1**
## About The Pull Request

Adds a photobooth program to the holodeck which provides:

- Pure white floor
- Pure black floor
- 2 Cameras
- A dresser
- A mirror
- Two adaptive paint buckets
- Three spray cans

Also changes the name of the "white" tile to "pure_white", and adds two new simple floors that are just black and white.

Outdated image:
Captain in the photobooth, looking fine

## Why It's Good For The Game

The main idea behind this pr is to make it easier for artists/wiki people to screenshot characters on the wiki. Outside of that, it also allows people to change their look or make nice group shoots with the cameras.

## Changelog
:cl:
add: Added a new holodeck program: Photobooth
add: Comes with three cameras and black and white floors, a dresser and a mirror.
/:cl:

### CODE REVIEW

**Comment by Tlaltecuhtli** [comment]
add a spray can too and paint buckets

**Comment by Lett1** [comment]
> add a spray can too and paint buckets

Done, good idea.

**Comment by Ratvar** [comment]
If only you could literally spawn holoobjects and change holoturfs by clicking them... that would let one make real grand pieces
Can't carpet tiles and tables be removed? Yeah, they are fancy, but you cannot clean white cube with them here

**Comment by BebeYoshi** [comment]
No green screen for memes?

**Comment by Lett1** [comment]
> No green screen for memes?

You can use the included paint buckets to recolor the floor however you like.

**Pull request merged**
