### PR TITLE
1 weird trick to normalize files in a repo [maintainers hate him]

### PR DESCRIPTION
**Pull request by optimumtact**
WAHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH

GORIOUS CONFRICTRUER?

END OF RINE

### CODE REVIEW

**Comment by KazeEspada** [comment]
fuck off

**Comment by WJohn** [comment]
DESPERATELY FIGHTING FOR THE TAGS.

**Comment by Razharas** [comment]
This pr is officially open for memeing in the comments

**Comment by optimumtact** [comment]
we have to do our part for global warming

**Comment by PKPenguin321** [comment]
what the fuck

**Comment by swankcookie** [comment]
got some merge conflicts, @optimumtact

**Pull request closed without merging**
