### PR TITLE
Updates CONTRIBUTING.md for MapMerge2

### LINKED ISSUE #35467: Mapping Standard for CONTRIBUTING.md is a bit outdated.
https://github.com/tgstation/tgstation/blob/master/.github/CONTRIBUTING.md#mapping-standards

Doesn't mention mapmerger2

### PR DESCRIPTION
**Pull request by ShizCalev**
fixes #35467

### CODE REVIEW

**Comment by praisenarsie** [comment]
now im happy

**Comment by MoreRobustThanYou** [comment]
i'm not gonna use fucking mapmerge2

**Comment by Cyberboss** [comment]
I now have a script that pings me whenever you make a map edit, so yes you goddamn are

**Comment by MoreRobustThanYou** [comment]
why can't I use the pre-MM2 TGM mapmerge? It works fine for me.

**Comment by SpaceManiac** [comment]
Old mm is susceptible to [this BYOND limitation](http://www.byond.com/forum/?post=2340796), and causes problems in DreamMaker because it never deletes unused keys containing paths that have since become invalid.

**Comment by xxalpha** [comment]
So just fix the bug instead of copy pasting the mapmerger with some git hooks and calling it a 2?

**Comment by SpaceManiac** [comment]
The internals were largely rewritten and the exact dependencies had changed such that I didn't want to remove the old version until I was sure the new version worked. That said the new code has been in circulation for a while, so maybe it's time.

**Comment by xxalpha** [comment]
I looked at the code, the core of it wasn't largely rewritten.

**Pull request merged**
