### PR TITLE
Autolathe boards are now only printable by Cargo to increase interdepartmental cooperation.

### PR DESCRIPTION
**Pull request by Iamgoofball**
## About The Pull Request

Autolathe boards are now only printable by Cargo to increase interdepartmental cooperation.

## Why It's Good For The Game

The autolathe is cargo's thing, and I'm tired of seeing Scientists literally never leave their department ever. The eggheads need to touch hallway tiles once every so often.

## Changelog

:cl:
balance: Autolathe boards are now only printable by Cargo to increase interdepartmental cooperation.
/:cl:

### CODE REVIEW

**Comment by Pickle-Coding** [comment]
Give cargo a real job instead of trying to force interaction with them.

**Comment by ForrestWick** [comment]
Maybe let engis also print them, just to be safe.

**Comment by necromanceranne** [comment]
Engis do get tools and electronic boards (for apcs/fire alarms/airlocks) in their protolathe. For the most part, besides misc stuff like conveyor belts, they don't really need an autolathe and they can make one with their access to tech storage.

**Comment by 81Denton** [comment]
I don't think that a one-sided "hey print me XYZ" is meaningful crew interaction, we removed similar things like the sacid requirement for circuit boards for a reason.

Instead this should be looked at from the angle of "does this department need an autolathe in their core gameplay?". Engineering should have access as well regardless.

**Comment by chefferz** [comment]
> 
> 
> > Give cargo a real job instead of trying to force interaction with them.
> 
> A job is real when it's meaningful and has crew interaction, so this actually slightly moves the needle towards that, despite what you're saying.

Here's the core issue with this.

The monetary system is already incredibly flawed and underbaked as is. This is attempting to force people to route all their requests through cargo for anything that's printed in the autolathe.

The context of this PR is because people want cargo to **START CHARGING** for parts, something that has been argued in the discord the past two-three days, _and after an admin ruled that if a department builds autolathes in their departments for public use, Cargo/QM can't run around and disassemble them._

All this is going to do is fuel more needless toxicity. This is a station that has cross department collaboration, and if you really want to play the "roleplay" card, why on earth would departments be forced to buy tools from Cargo from their own paycheck? All this is going to do is start wars where engineering starts charging for power, or medbay starts charging for heals.

**Comment by InvalidArgument3** [comment]
Modsuits will solve the cargo-science lack of interaction (coming 2021)

**Comment by chefferz** [comment]
> 
> 
> None of you are correct, the core issue with this PR is that it's a piecemeal change that ultimately will only move the needle a tiny amount.
> 
> It's barely even worth the effort of words you are wasting on it.

Understandable, yes. But for this to even remotely function correctly the money mechanic would have to be fully overhauled, and

> 
> 
> > > > Give cargo a real job instead of trying to force interaction with them.
> > > 
> > > 
> > > A job is real when it's meaningful and has crew interaction, so this actually slightly moves the needle towards that, despite what you're saying.
> > 
> > 
> > Here's the core issue with this.
> > The monetary system is already incredibly flawed and underbaked as is. This is attempting to force people to route all their requests through cargo for anything that's printed in the autolathe, and use this "money" mechanic that is really only useful in niche circumstances like antag objectives and buying crates for personal use.
> > The context of this PR is because a very small group of people people want cargo to **START CHARGING** for parts, something that has been argued in the discord the past two-three days, _and this PR was made after an admin ruled that if a department builds autolathes in their departments for public use, Cargo/QM can't run around and disassemble them (which is what happened in a round, because apparently there's "competition")_
> > All this is going to do is fuel more needless toxicity. This is a station that has cross department collaboration, and if you really want to play the "roleplay" card, why on earth would departments be forced to buy tools from Cargo from their own paycheck? All this is going to do is start wars where engineering starts charging for power, or medbay starts charging for heals.
> > One of the arguments made for this was that cargo needs money for people who want to order expensive crates, but each department has their own budget and that budget is used when crates are _ordered through the order console that's inside each department_
> > This PR is only being made to support the above, and about trying to allow cargo to monopolize the boards used to support a large amount of things used in game.
> 
> you know this is tg, right

Yes, and TG Code is already incredibly fast paced code fast as-is.

So what happens when cargo gets bombed and you can't print out anything anymore because autolathe boards are unable to be made?

**Comment by JustANormalHooman** [comment]
I really think that giving Engineering access to the board would alleviate a lot of concern for stuff. Engineers are not intrinsically motivated by money, and could thus be used as a monopoly-buster in a case where cargo attempts to charge money for parts. This is not Eris station, where charging for literally everything is expected. Medbay does not ordinarily charge for healing, and science doesn't charge for part upgrades. On another note, Science and Engineering seem naturally designed to act as monopoly-busters in current design, or at least as some form of backup in case cargo is bombed, since their circuit printers can print anything that isn't a protolathe board (if the science team replaces the departmental one with the non-departmental one that is). Denying the entire crew an autolathe becomes as easy as getting rid of the spare board and the normal cargo protolathe, and deconning the autolathe that already exists. This makes cargo much more likely to be the target of antagonistic actions because they hold such an important monopoly and are a single point of failure. Autolathes are needed for a lot of things and this would just make things rather annoying for everyone.

**Comment by ForrestWick** [comment]
> Engis do get tools and electronic boards (for apcs/fire alarms/airlocks) in their protolathe. For the most part, besides misc stuff like conveyor belts, they don't really need an autolathe and they can make one with their access to tech storage.

If cargo gets blown up, there should prolly be a fallback tbh

**Comment by Mothblocks** [comment]
If cargo gets blown up, then the round should feel it by a measurable degree. Just like how every single department in the game should be.

oranges is right. This change doesn't really *do* anything. People already move out the ORM and just end up breaking into cargo anyway.

**Comment by InvalidArgument3** [comment]
> oranges is right. This change doesn't really _do_ anything. People already move out the ORM and just end up breaking into cargo anyway. It affords a little extra hand to cargo to be a place people might actually go someday.

I feel there's more interaction in that hypothetical situation with getting engi to rebuild cargo and its machines than >cargo lathe's gone, call shuttle! 20 minutes in. Like it is when a prankster bombs the new unrepairable research server at the start of the round.

**Comment by Wollywoger** [comment]
Highly worth noting Science can print omni-circuit printer boards, and the engineer circuit printer is an omniprinter (which itself can print more omniprinters!), which all omni-circuit printers ignore departmental flags like this.

**Comment by chefferz** [comment]
" I'm tired of seeing Scientists literally never leave their department ever. "

Cytology has to go out of their way to swab samples and orchestrate with other departments to get the chemicals needed to produce.

Genetics has to go out in the hallways and scan people if the want to get sets of genes more easily figured out.

Scientists themselves go out of their department to upgrade boards across the station.

Robotics and xenobio are probably the only two departments that tend to remain in their own zones, the latter moreso purely because of the time needed to actually get things like rainbows and crossbreeds.

Please put the real reason you made this PR, because of the argument on Skyrat and the admin comment about how autolathes are allowed in other departments, so you decided to make an upstream PR for ??

**Comment by Iamgoofball** [comment]
the argument on skyrat is irrelevant to this PR, it simply reminded me that I wanted to make this PR, and that this is a PR we'd want upstream

do not discuss the downstream here again

**Comment by KittyNoodle** [comment]
also sci upgrading boards only happens after angry chemists burn down the walls with thermite

**Comment by CRITAWAKETS** [comment]
> you are either lying or inoptimal if you think geneticists are leaving their rooms to scan genes

scanning genes can actually be really good sometimes so experienced geneticists actually do that since it cuts down on time

**Comment by Mothblocks** [comment]
you scan the monkeys that come from the like 7 monkey cubes + fire extinguisher

**Comment by CRITAWAKETS** [comment]
> Robotics and xenobio are probably the only two departments that tend to remain in their own zones, the latter moreso purely because of the time needed to actually get things like rainbows and crossbreeds.

Should probably mention that for robotics, the reason they dont leave is usually just that they're too busy. Also the job is of an open-ended nature so they can kinda just do anything.

**Comment by tralezab** [comment]
> > you scan the monkeys that come from the like 7 monkey cubes + fire extinguisher
> 
> would be a good method if the monkeys werent constantly trying to kick your ass

diagnosis: skill issue

**Comment by newfren** [comment]
This pr doesn't actually stop scientists from turtling in their department for the reason Wollywoger said, so what is the purpose?

**Comment by Farquaar** [comment]
This feels like a solution looking for a problem. Can somebody even point to a round where people have been holed up in their departments mass-building autolathes?

**Comment by Capsandi** [comment]
This is a good change,  but it does show that autolathes are a poorly planned bottleneck to as much general equipment as you want. A single stack of metal and glass is enough to pass out toolsets to most of the station, and isn't it strange how the most reliable place to find surgery tools is in the cargo department? Not sure what a good replacement would be but this is fine for now.

**Comment by wraith-54321** [comment]
I agree that this is just too small of a change to really have any impact, and if cargo does start charging for parts/tools from their autolaths I feel a lot of the time they may just end up getting tided for a board, also the effect of this goes down a lot once tech is done.

**Comment by Fryzzie** [comment]
If your taking away autolathes, you need to add the proximity sensor and conveyer to the sci-lathe, as their required for robotics and arent available otherwise

**Comment by Sparkezel** [comment]
Isn't it the role of engineering to be able to print all electronics? By doing this change you pretty much go against design philosophy of both cargo and engineering. If anything cargo should be only able to buy autolathe boards ,you could make the technology inaccessible due to copyright or something :))) or you should make the board only accessible to engineering omnilathe instead,

**Comment by zxaber** [comment]
Or move all engineering-relevant boards tothe engi protolathe.

**Comment by Iamgoofball** [comment]
@Mothblocks the design philosophy of cargo
when-the-money

**Review by Timberpoes — CHANGES_REQUESTED** [review]
I am DNMing this because the PR description is misleading and it does not accomplish its own justification of why it's good for the game. It doesn't explain it either.

This is DNM until I get more explanation of the following:
1. What this PR actually does with some evidence you understand the systems in place. Currently this PR makes it so that autolathe boards are printable by Cargo (via techfab), Engineering (via their non-departmental circuit imprinter) and Science (via their ability to make non-departmental circuit imprinters). This doesn't match your description or goals. It also indicates a lack of testing.
2. What items have you removed from each department via their inability to make autolathes? What core job content (if any) relies on these items for each department? Why is this good?

This PR is also DNM due to the misleading PR body and changelog. You can either change the code to make your PR body/CL true, or change the PR body to reflect the reality of what you changed. Either way, that also needs to be rectified before this PR advances.

Once these two DNM concerns are handled, ping me on Discord and I'll look at it again. I can't say it'll cause me to remove DNM, since I currently don't believe this will be a good or positive change for the game in any event - But I can't say for sure because your PR body is so lacking, so I can only block it on those grounds. 

If you're struggling, find any maintainer(s) willing to champion this specific PR. If there's a strong enough argument for this PR from them, I'll back off as long as they note my specific concerns. This still requires your PR body and changelog to actually match what your code changes are.

Note: I don't automatically assume that departments being forced to rely on eachother is beneficial by default. I believe each department should have a reasonable level of self-reliance for core job content and departmental inter-reliance is good for gating advanced job content or QoL - See CRISPR genetics requiring a virus with a specific symptom (advanced job content), or upgrading the chem dispenser with better parts unlocking some bonus compound chems (QoL).

You **will** need to explain why what you've created leaves the game in a better place than if you changed nothing. Saying "cross-departmental cooperation" simply isn't enough. The game would be utterly miserable to play with arbitrary cross departmental reliance injected because ??? it's got what plants crave ???.

This is my perspective to help you understand my reasoning behind why I'm opposed to this change. Hopefully it helps you explain your reasoning in a way that addresses my concerns.

---

Now on to the critique!

Science and Engineering can both still make autolathe boards with this PR.

Engineering can make them through their non-departmental circuit imprinter.

Science can make them through making their own non-departmental circuit imprinter to match engineering, then printing the circuits from there.

Science and Engineering are not making an autolathe for tools. Engineering can print all tools full stop and Science can print all baseline tools and the experimental welding tool. Science can also print a bunch of neat medical tools, so they're not using the autolathe for that either.

image

Science's use of the autolathe is going to be almost exclusively for Robotics, which can require prox sensors, conveyor belts and other misc stuff like buckets for cleanbots.

This does however make it so Medical and Service can't build autolathes without going through Science, Engineering or Cargo first.

**Pull request closed without merging**
