### PR TITLE
Remove duplicate chaplain armor datums

### LINKED ISSUE #72348: There are 13 definitions of `chaplainsuit_armor`
## Reproduction:

image

### PR DESCRIPTION
**Pull request by timothymtorres**
## About The Pull Request
Fixes #72348 

Caused by #71986  Looks like they used some type of regex to mass c/p multiple duplicate armor values across many items.

## Why It's Good For The Game
Less c/p code.

## Changelog
Not needed.

### CODE REVIEW

**Comment by ZephyrTFA** [comment]
Correct!
See https://github.com/tgstation/tgstation/blob/master/tools/armor_list_to_datum.cs

**Comment by ZephyrTFA** [comment]
Breaking down what the script does.

It keeps track of the last active byond tree.
Remembers its name using the last two tree level identifiers.
Looks for `\tarmor = list(`
And then cuts that into a datum to append
When it finds a point where the tree changes, or EOF, it slots in the armor datum string

**Comment by ZephyrTFA** [comment]
Guess I should've used three tree levels

**Comment by timothymtorres** [comment]
Talked with Zephyr on discord and he made #72354 as a full solution to the entire problem.

**Pull request closed without merging**
