### PR TITLE
Love is stored in the heart (adds the love chem to hearts)

### PR DESCRIPTION
**Pull request by 00-Steven**
## About The Pull Request

Pretty much just sets the default food reagents for hearts to have 2.5u love in addition to the base 5u nutriment.
Then makes the friendly quirk double the volume and contents of your heart when it first gets applied, and also applying a 1.5 scale transform to it so it looks bigger too.
image
The transform does still feel a bit wonky though.
## Why It's Good For The Game

It came to me in a dream.
Or more so, I think it's incredibly funny, both just to say and the implied niche interactions from it.
Like hearts tasting like love, extracting love from people's hearts, friendly people having Physically bigger hearts.
Really a sopping-with-blood still-beating heart is just the _best_ gift for a friend.

It's still wildly more annoying to procure than just getting the k1ss skillchip and using that to extract love.
## Changelog
:cl:
add: Love is now stored in the heart.
balance: Characters with the Friendly quirk now have physically bigger hearts.
/:cl:

### CODE REVIEW

**Comment by thgvr** [comment]
Scaling sprites makes them look horrible, use a different sprite.

**Comment by 00-Steven** [comment]
If you're volunteering.

Anyhow, I'm not a spriter, and there's multiple different possible heart sprites- trying to do it that way just for this is just awkward.
This is roughly how brains do it, too.

**Comment by AtomTheProphet** [comment]
> Scaling sprites makes them look horrible, use a different sprite.

He hated the heart! The whole organ!
No one knows why, no one quite knows the reason. 
It could be his head wasn't screwed on just right.
It could be, perhaps his shoes were untied.
But I think that the most likely reason of all
May have been that his heart was two sizes too small.

**Comment by optimumtact** [comment]
What can the love chem be used for.

**Comment by 00-Steven** [comment]
Very little.
image
Jokes aside, it's the exact same chem as granted by the K1SS skillchip you can buy from the plasteel chef vendor.
I've changed nothing regarding how it works.

It only works if you've ingested it, and gives a mood bonus depending on how long it's been in your system for.
If you manage to get over 50u in your system, you'll overdose, and on each overdose cycle have a 10% chance of getting a heart attack.
Finally, it just has a high `taste_mult` and makes your food taste like love with even very little of it.
That's it.
That's all it does.

To compare this method to how much you get using the skillchip, it's a bit less than one stick of butter worth.

**Comment by carlarctg** [comment]
remove it from heart of darkness

**Review by MrMelbert — APPROVED** [review]
Awesome. Does mean hearts will taste like grandma's cooking when you bite into it but i'm sure that's fine

**Comment by Jackraxxus** [comment]
Deep lore: Your character's grandma is a lizard

**Comment by Jacquerel** [comment]
>This is roughly how brains do it, too.

It looks bad on brains as well but I do agree that it's not actually a solveable problem if you want larger hearts.

**Comment by 00-Steven** [comment]
re: robotic hearts
I mean yes, _technically_ cybernetic hearts have love, but you can't grind or eat those normally. You could deep-fry them, but that still doesn't let you grind them, and eating them doesn't give you the love in them.

re: heart of darkness
yeah that's funny gimme a moment

**Pull request merged**
