### PR TITLE
Fixes augmentation surgery allowing non-robot limbs

### LINKED ISSUE #22813: Bug with limb replacement surgery(augmentation) & Bug with Prosthetic Replacement surgery.
Lets take digigrade legs for example. If you want to replace someones existing leg with a digigrade leg, you first have to do amputation surgery on said leg, and then do the prosthetic replacement surgery on them to replace their leg.

If you don't do this, and instead opt for the Augmentation option to try to replace their leg, instead of replacing their leg with a digigrade leg, it will replace their leg with a cyborg one(or at least, it looks 100% like a leg augmented by a cyborg limb).

Either it should only allow you to use cyborg limbs during the augmentation surgery, or it should correctly replace said limb with the one you intend to replace it with and be renamed to Limb Replacement Surgery. Heck, the Prosthetic Replacement surgery should possibly also be renamed.(This also explains why that frankenstein I tried to make instead ended up as an augmented human.)

Edit: Also, apparently I am suffering from terrible Engrish today.

Edit 2: Okay, time to expand the bug report. So, I tried to replace someones legs with Plasmeme legs. Now, as with above, the augmentation surgery gave them a cyborg leg. Buuut, when I tried to do it like I did with Digigrade legs....well. It correctly gave them the toxin damage that adding mutant limbs is supposed to do, but it didn't replace their leg with a plasmeme leg. Instead it gave them a perfectly normal human leg. (Or atleast, the leg looks like a perfectly normal human leg. The medical analyzer still lists it as a Synthetic Plasmaman leg). Thus I guess I now have to change the title aswell.

### PR DESCRIPTION
**Pull request by RemieRichards**
```&&``` -> ```||```
Fixes #22813

### CODE REVIEW

**Comment by Firecage** [comment]
Remie, this only fixes one half of the issue though. It doesn't fix the second part of it, that Prosthetic Replacement surgery is also buggy.

Besides, wouldn't it be best to rename it to Limb Replacement Surgery, and have it work for robot limbs, and any mutant race limbs(including putting humans ones in Ligger scum)

**Comment by RemieRichards** [comment]
The replacement surgery is fine, there's only this bug in play as far as I can see and now it's fixed.

**Comment by Firecage** [comment]
Remie, how is it fine though? It literally doesn't work right. Like try to replace someones legs with lizard, plasmeme, flymen, etc. legs, they will instead get human looking legs. The only legs which works for limb replacement is Digitigrade legs, for some reason I am unsure why.

**Comment by RemieRichards** [comment]
Hmm, it is true, Incoming broke it then.

**Comment by Firecage** [comment]
@RemieRichards Mmm, over Admin PM, Kevinz did inform me of what it might be. Like normal ligger limbs, fly limbs, skeleton limbs, etc, aren't actual items. Its more of the appearance actually being set on that limb. The reason Digitigrade legs works, is because they are their own item. And browsing the code, what he said seems to be true. So the best fix I can think of, is actually adding those limbs as actual items, aka real limbs. As a bonus point, admins when then be able to spawn them aswell.

**Pull request merged**
