### PR TITLE
Clown gets a unique breath tank filled with anesthetic

### PR DESCRIPTION
**Pull request by genessee596**
**THE WHAT**
The clown gets a unique breath tank in his internals box called a 'emergency prank tank'. It contains mostly oxygen, with a trace amount of N2O -- not enough to knock you out, but after breathing it for a while you'll start to laugh. Honk!

_Inventory Item Sprite_
image
_On-Belt Sprites_
image
_In-Hand Sprites_
image

**THE HOW**
Sprites were slammed into the 'tanks.dmi', 'belt.dmi', 'tanks_lefthand.dmi' and 'tanks_righthand.dmi'. The actual item files for the tank is in the 'tank_types.dm' file, and the code that has the tank spawn in the clown's internals box is in the 'boxes.dm' file.

**THE WHY**
The clown gets a bunch of unique gear already, so now he can have a nice laugh as he floats in the void of space! Also, uses N2O which is sadly underused.

## Changelog

:cl:
add: Added the 'emergency prank tank', a unique breath tank that spawns in the clown's internals box. Contains 99% oxygen and 1% N2O, causing whoever breathes it to laugh after a short amount of time.
/:cl:

### CODE REVIEW

**Comment by carlarctg** [comment]
misleading title

**Comment by TheChosenEvilOne** [comment]
'Clown gets a funny unique breath tank'

**Comment by spessbandit** [comment]
this should replace the clown's regular internals

**Comment by genessee596** [comment]
> this should replace the clown's regular internals

It does.

**Comment by Tlaltecuhtli** [comment]
it should be half n2o and o2

**Comment by genessee596** [comment]
> it should be half n2o and o2

That would knock out the user in seconds -- even having it as low as 10% N2O knocks the user out within 5 seconds of turning on internals.

**Comment by actioninja** [comment]
conflict

**Comment by actioninja** [comment]
stale

**Pull request closed without merging**
