### PR TITLE
ignore_walls in playsound() is now by default FALSE

### PR DESCRIPTION
**Pull request by grungussuss**
# This is a big one
## About The Pull Request
I noticed that ALL of our sounds by default pass through walls, from the slightest button click, to the bolt rack of a gun, to a PDA message notification.. so I fixed it...
I checked all 3135 instances of `playsound()` to make sure the sound should or shouldn't pass through walls: Very loud sounds like: gunshots, meteor impacts, explosions still ignore walls.
#### No longer can be heard through walls:
- footsteps
- bolt racks and gun handling (magazine in, magazine out)
- PDA message notifications
- Eating and drinking
- Attacking with an item that resulted in no damage
- All abstract item sounds (including slap)
- Storage rustle and drop/pickup sounds
- Various machine beeps
- Flashes can't be heard through walls
- Projectile impact sounds
- Stepping through gibs
#### Still ignores walls:
- SM
- Attacks with melee weapons that result in damage
- Esword turn on and turn off sounds
- Gunshots
- Honks still ignore walls cause it's funny
- Bomb beeping can still be heard through walls
- Explosions
- Resonance cascade sounds

A test merge of this pr is necessary to make sure nothing was missed.
## Why It's Good For The Game
Currently almost every sound we have in the game ignores walls, this means you can flick a light switch and a person on the other side of the wall will hear it.
Why is this bad?
- Making no noise during stealth gameplay is impossible even if you are attempting to make as little noise as possible
- Hearing every little thing happening outside of the room you are in contributes to ear fatigue greatly and reduces the merit of important gameplay audio cues.
- Removes the focus of RP interactions from the room you are currently in.
- Reduces the usefulness of secret bases to zero because a minor fart can reveal your position.

With this change, the problems listed before are solved or mitigated.
### The main reason for this change:
Increasing effectiveness of stealth gameplay will gravitate players towards a more stealthy playstyle, allowing for more mystery, paranoia and overall will drive the story better than loud gameplay as murderbone isn't very interesting or fun.
## Changelog
:cl:
balance: footsteps can no longer be heard through walls.
balance: flashes can no longer be heard through walls.
balance: gun handling sounds can no longer be heard through walls.
balance: PDA message notifications can no longer be heard through walls.
sound: sounds will no longer ignore walls by default.
/:cl:

### CODE REVIEW

**Comment by EEASAS** [comment]
DEAR GOD

**Comment by dalmationer** [comment]
ough can you make wheelchair sounds not audible through walls? they're EXTREMELY loud. i'll be hanging out in my evil little maint lair as paraplegic and I'll move a tile and everyone within a screen will be like 'SHE'S IN THAT SECRET ROOM'

**Comment by Sadboysuss** [comment]
> Hm feels a bit odd the SM doesnt' ignore walls, especially since it's largely surrounded by walls? And rather loud at that

My mistake, SM is unaffected by pressure and ignores walls

**Comment by Sadboysuss** [comment]
> can you make wheelchair sounds not audible through walls?

already like that, or at least the code says so, haven't tested that one yet:
```php
/datum/element/noisy_movement/proc/play_sound(atom/movable/source, old_loc, movement_dir, forced)
	SIGNAL_HANDLER
	if(!forced && !CHECK_MOVE_LOOP_FLAGS(source, MOVEMENT_LOOP_OUTSIDE_CONTROL) && source.has_gravity())
		playsound(source, movement_sound, volume, TRUE)
```

**Comment by dalmationer** [comment]
> > can you make wheelchair sounds not audible through walls?
> 
> already like that, or at least the code says so, haven't tested that one yet:
> 
> ```
> /datum/element/noisy_movement/proc/play_sound(atom/movable/source, old_loc, movement_dir, forced)
> 	SIGNAL_HANDLER
> 	if(!forced && !CHECK_MOVE_LOOP_FLAGS(source, MOVEMENT_LOOP_OUTSIDE_CONTROL) && source.has_gravity())
> 		playsound(source, movement_sound, volume, TRUE)
> ```

oh huh really? something might be bugged then because I was sure they pass through walls very well

**Comment by Sadboysuss** [comment]
> oh huh really? something might be bugged then because I was sure they pass through walls very well

I meant that's how it works with my change because I changed the parent type to ignore walls by default.

**Comment by JupiterJaeden** [comment]
I strongly, strongly dislike this PR. Hearing random/spooky noises from/in maintenance or just around the corner out of sight is a HUGE contributor to the paranoia of the game, not a detractor from it. It’s not as easy as you claim to immediately locate where such a sound is coming from. 

I have many fond memories of hearing little foreshadowing sounds in maintenance for big things that pop up later, like cults and such. 

Also: making flashes not be able to be heard through walls is a HUGE change to rev balance and I don’t think revs needed buffing whatsoever.

**Comment by Sadboysuss** [comment]
I'm still up to changing stuff. We can for sure get to a compromise where some spooky sounds will still be heard, while fluff sounds would not. I need a maintainer to form their opinion, though

**Comment by Kylerace** [comment]
There's a major performance issue with making sounds as common as footsteps not ignore walls: when playsound is passed ignore_walls = FALSE it will find the clients who can hear it by calling get_hearers_in_view(), which is a pretty expensive proc when a large radius is passed in (e.g. most playsound() calls). When ignore_walls = TRUE it will instead just find a list of clients on the z level and cull those who are too far away, which is much cheaper. 

Players cause a lot of footsteps sounds, a lot a lot. This pr will need to be TM'd and if it increases SSInput cost like I think it will footsteps will need to be left out

**Comment by thgvr** [comment]
Most of these are incredibly weird to make not heard, and will really ruin the ambience of the game...

>    footsteps - Hearing people walk around inside of departments, in maint, etc how is this a bad thing?
    bolt racks and gun sounds - these are pretty important gameplay sounds that should be heard if nearby.
    PDA message notifications - again, it's auditory feedback for things happening in the world.
    Eating and drinking - ditto
    Attacking with an item that resulted in no damage - whatever
    All abstract item sounds (including slap) - this is just strange, why would they be silenced by being a room over?
    Storage rustle and drop/pickup sounds - same as guns, it's a gameplay oriented sound.
    Various machine beeps - more ambience. how is this bad?
    Flashes can't be heard through walls - Again, another gameplay oriented sound that is an auditory tell of an item being used, revs, etc
    Projectile impact sounds - part of ambience soundscape, again, how is this bad?
    Stepping through gibs - whatever, but this shouldn't be silent most likely.
    
Some of the reasons you gave for these are very odd, let's break it down:

>Making no noise during stealth gameplay is impossible even if you are attempting to make as little noise as possible

Things like being heard walking around seems moot here, you can walk intent and not make footstep sounds. For this, I would explore maybe having walk mode on make sounds quieter/falloff faster such as interacting with inventory.

>Hearing every little thing happening outside of the room you are in contributes to ear fatigue greatly and reduces the merit of  important gameplay audio cues.

What do you consider an important gameplay cue? If you hear someone walking in maint near you and cocking a gun or firing at a wall, or flashing people on the other side of the wall, etc. Do you not consider those "important gameplay cues"?

>Removes the focus of RP interactions from the room you are currently in.

If anything you lose out on interactions in the room you are currently in, and it makes the world feel less grounded when you just can't hear things going on outside of your direct area.

>Reduces the usefulness of secret bases to zero because a minor fart can reveal your position.

This is more an issue of map design and things like mesons than sounds. Sounds giving away your position has always been a key part of the experience. Not being able to hear dastardly things, flashes, guns etc from other rooms.

Again, with things like footsteps, there's already measures for making them silent... walking. I don't see how it's a good thing to nullify that by making it silent for sneaking around in maintenance while running at full speed. It feels like the design is at odds with the things that already exist to mitigate sounds.

> I'm still up to changing stuff. We can for sure get to a compromise where some spooky sounds will still be heard, while fluff sounds would not. I need a maintainer to form their opinion, though

What do you honestly consider a "fluff sound"? Almost all sounds are "fluff" in the end, however it's important for the game's soundscape as it is much better to have audio feedback for a lot of things than have the game be completely silent most of the time. This is a thing that tgstation has only recently begun to work on and it has improved the experience a lot.

**Comment by Sadboysuss** [comment]
@thgvr You make a good point, we can definitely make a lot of these sounds ignore walls even if it doesn't make too much sense from an in-world view (cough cough, footsteps heard through walls), I'm not gonna get too much into it right now since I'm very tired, but I'm interested in seeing how it will affect gameplay in a test merge, or what a maintainer thinks about this change.

**Comment by Singul0** [comment]
Love the pr, but why do you discriminate between ranged attacks not causing sounds over walls but melee does? Doesnt make any sense. Especially since (imo) melee should be stealthier than gunshots

**Comment by Sadboysuss** [comment]
Both melee attacks that cause damage and gunshots still ignore walls

**Comment by Loafin34** [comment]
You should be able to hear sounds through a wall by leaning on it. That way, the geneticist won't notice the cuffing happening in maints, but a paranoid assistant might. Also, leaning feature.

**Comment by optimumtact** [comment]
> You should be able to hear sounds through a wall by leaning on it. That way, the geneticist won't notice the cuffing happening in maints, but a paranoid assistant might. Also, leaning feature.

it's not possible to modify the sound engine in this way.

**Pull request closed without merging**
