### PR TITLE
Turns the thunderdome into a map template

### PR DESCRIPTION
**Pull request by SuperNovaa41**
AND REMOVES the template from centcom.dmm
It didn't need to be there especially when we have this perfectly good
map template system (also lemon asked me to do this)

:cl:
fix: The thunderdome side rooms will now properly reset.
admin: The thunderdome is now a placeable map template.
/:cl:

### CODE REVIEW

**Comment by unit0016** [comment]
Damn, Present Wars is gonna be screwed by this.

**Comment by SuperNovaa41** [comment]
> Damn, Present Wars is gonna be screwed by this.

What do you mean

**Comment by unit0016** [comment]
> What do you mean

There's been a habit on manuel as of recent where an admin places a infinite christmas tree in the thunderdome, maybe adds some walls around, and chucks a handful of ghosts in for a deathmatch. They modified the little nook where the thunderdome is currently stored for ease of resetting it.

Having no way to edit the thing on the fly's gonna make that a bit more tedious 💀

**Comment by carshalash** [comment]
But... present wars...

**Comment by SuperNovaa41** [comment]
> But... present wars...

Admins can still upload custom map templates and just reset it themselves with that if they really care

**Review by Kylerace — APPROVED** [review]
code good

**Pull request merged**
