### PR TITLE
Airlocks no longer runtime when a blob destroys them

### LINKED ISSUE #46173: Airlock wires runtime if a non /mob/living causes them to be cut
## Round ID:

https://tgstation13.org/parsed-logs/basil/data/logs/2019/08/26/round-117116/runtime.txt

## Reproduction:
```
[2019-08-26 23:32:43.891] runtime error: undefined proc or verb /mob/camera/blob/electrocute act().
 - 
 - proc name: electrocute mob (/proc/electrocute_mob)
 -   source file: power.dm,324
 -   usr: Blob Overmind (832) (/mob/camera/blob)
 -   src: null
 -   usr.loc: the floor (214,128,2) (/turf/open/floor/plasteel/dark)
 -   call stack:
 - electrocute mob(Blob Overmind (832) (/mob/camera/blob), the upgraded power cell+ (/obj/item/stock_parts/cell/upgraded/plus), Telecomms Server Room (/obj/machinery/door/airlock/hatch), 1, 1)
 - Telecomms Server Room (/obj/machinery/door/airlock/hatch): shock(Blob Overmind (832) (/mob/camera/blob), 50)
 - /datum/wires/airlock (/datum/wires/airlock): on cut("Auxiliary Power 1", 1)
 - /datum/wires/airlock (/datum/wires/airlock): cut("Auxiliary Power 1")
 - /datum/wires/airlock (/datum/wires/airlock): cut all()
 - Telecomms Server Room (/obj/machinery/door/airlock/hatch): obj break("melee")
 - Telecomms Server Room (/obj/machinery/door/airlock/hatch): take damage(280, "brute", "melee", 0, 1, 0)
 - Telecomms Server Room (/obj/machinery/door/airlock/hatch): take damage(400, "brute", "melee", 0, 1)
 - Telecomms Server Room (/obj/machinery/door/airlock/hatch): take damage(400, "brute", "melee", 0, 1)
 - Telecomms Server Room (/obj/machinery/door/airlock/hatch): blob act(the blob (/obj/structure/blob/normal))
 - the blob (/obj/structure/blob/normal): expand(the floor (214,128,2) (/turf/open/floor/plasteel/dark), Blob Overmind (832) (/mob/camera/blob), 1)
 - Blob Overmind (832) (/mob/camera/blob): expand blob(the floor (214,128,2) (/turf/open/floor/plasteel/dark))
 - Blob Overmind (832) (/mob/camera/blob): ClickOn(Telecomms Server Room (/obj/machinery/door/airlock/hatch), "icon-x=24;icon-y=7;left=1;scre...")
 - Telecomms Server Room (/obj/machinery/door/airlock/hatch): Click(the floor (214,128,2) (/turf/open/floor/plasteel/dark), "mapwindow.map", "icon-x=24;icon-y=7;left=1;scre...")
 - Py01 (/client): Click(Telecomms Server Room (/obj/machinery/door/airlock/hatch), the floor (214,128,2) (/turf/open/floor/plasteel/dark), "mapwindow.map", "icon-x=24;icon-y=7;left=1;scre...")
```
Don't, Use, Usr, In, Procs, Idiot.

### PR DESCRIPTION
**Pull request by nemvar**
## About The Pull Request

title.
Fixes https://github.com/tgstation/tgstation/issues/46173

Ideally this wouldn't use usr at all but here we are.

### CODE REVIEW

**Comment by AnturK** [comment]
Airlock shock accepts mob, electrocute_act carbon, here you do living. So which one is it.

**Comment by nemvar** [comment]
electrocute_act accepts living, same with airlock shock. The args are lying to you.

**Comment by AnturK** [comment]
I know it's bit unrelated but could you update them please.

**Comment by AnturK** [comment]
Someone update the params please.

**Pull request merged**
