### PR TITLE
Advanced space hitch-hiking apparatus (Mura-Brand Banjo)

### PR DESCRIPTION
**Pull request by Acer202**
## About The Pull Request

Mura, noticing a disturbing lack of banjos in space, decided to start making some!

spacebanjo

https://youtu.be/aDeAxmIOzGs

## Why It's Good For The Game

-Adds a very nice banjo to the musician's arsenal, which hopefully may offset the ear-destruction that is the violin and accordion.
-Play rag on something that sounds nice. 
-Space redneck shenanigans.
-Murder people with a banjo.

## Changelog
:cl:
add: Mura space banjos are now in stock at your local NT instrument supplier! Start picking today!
/:cl:

### CODE REVIEW

**Comment by actioninja** [comment]
what are the samples from?

**Comment by Acer202** [comment]
> what are the samples from?

Samples are from my own Gibson Banjo. I recorded each and every note, then processed them for noise reduction and consistency.

**Comment by actioninja** [comment]
Based as fuck.

**Comment by Jimmius** [comment]
time to play the outer wilds soundtrack

**Comment by CRITAWAKETS** [comment]
Oh my god those attack verbs are amazing.

Maybe make the force of the banjo slightly higher? 12 brute while giving a tiny bit of the drunk walk effect for a second, say?

**Comment by carlarctg** [comment]
image
player reference alert


make it do a BWONK noise when hitting someone. yknow like the engineer frontier justice taunt

**Comment by cacogen** [comment]
whatever happened to 'no new player references'

**Comment by wesoda25** [comment]
Who the hell is Mura and why are they trying to shill banjos

**Comment by Acer202** [comment]
> Maybe make the force of the banjo slightly higher? 12 brute while giving a tiny bit of the drunk walk effect for a second, say?

While I do like the idea of making silly things like that, I don't want to have worry about balance issues around this—I just want a nice fun instrument for the players to enjoy first and foremost. Perhaps if it's requested by a few people, but otherwise I'll just be leaving this as-is.

> whatever happened to 'no new player references'

This wasn't mentioned in the pull request wiki, could you share where you heard that? I can remove that bit if need be, but that makes me kinda sad, since I made this mainly because of IC motivations.

> Who the hell is Mura and why are they trying to sell me a banjo

You hear something crackle in your ears for a moment before a voice speaks. "Please stand by for a message from Mura McNamara. Message as follows: **Hey there! Cargo shuttle hitchhiker extraordinaire Mura here! Picking is good for the soul, and it's hard to do without getting a big smile on your face! Give it a try, you'll love it! Remember to always do your best, and stay spessy.** Message ends.

**Comment by Krysonism** [comment]
I say let the reference stay in since he put in all the effort to record the notes himself.

**Comment by optimumtact** [comment]
hmmmmmmmmmm

**Comment by carlarctg** [comment]
merge this with the player reference because mura is a cute cat

**Comment by anconfuzedrock** [comment]
I say don't break the rule for no logical reason

**Comment by Acer202** [comment]
> I say don't break the rule for no logical reason

The reason I decided to brand it at all was something I believed was thoughtful—a reminder to the spaceman who examines it that one person spent several hours recording, editing, spriting, and learning to use git just so they can enjoy a silly new instrument in the spessmans game. A big reason why I stuck with Mura's character for 1100 hours on /tg/ was because I liked to bring people a bit of hope and joy whenever I could, and the banjo, being something I always found bringing a smile to my face, seemed like a nice thing to spread the message of being a good spaceman with—something Mura really advocates for. Slapping her name on it is thus also an attempt to remind people of a good personality. And finally, because of some recent changes in my life, It might also be my parting gift to /tg/, so it would mean a lot to me if it were to stay as-is.

**Comment by anconfuzedrock** [comment]
Okay. many people have thousands of hours in ss13 and like their characters, including me. I can think of three who have player references. all of those are extremely subtle- you probably don't think much of the mug in the medbay lobby. None of these references were to the player creating the change. This isn't suggesting you make the reference subtle; This is suggesting you remove the reference.

**Comment by Cyanshitcoder** [comment]
time to solve some practical problems

**Pull request merged**
