### PR TITLE
Updates milkshake sprites, adds two milkshake recipes.

### PR DESCRIPTION
**Pull request by KathrinBailey**
## About The Pull Request
• Updates all milkshake sprites, specifically moving the weird glass lid looking part.
• Attempts to preserve #70804 by keeping the same color scheme for the straws.
• Adds in banana milkshakes, obtained by juicing bananas.
• Adds in strawberry milkshakes, obtained by juicing berries.

## Why It's Good For The Game
Additional milkshake flavors to complete the menu. Strawberry and banana are almost as iconic as chocolate!
### Reasoning behind changing the sprites
New sprites remove the weird glass partition between shake and cream, and removes the dome lid.

The chocolate milkshake was unusually dark beforehand. It looked like coffee, almost. I've made real milkshakes before, using ice cream, milk, ice and cocoa powder. Even with a _lot_ of cocoa powder, it isn't getting dark as the old sprite. The new sprite is roughly what my milkshakes looked like. 

The straws have been changed to be angled instead of piercing straight through the cream. I think it looks better angled too.

The vanilla shake previously looked far too yellow. Vanilla isn't _that_ yellow and it'd have confused players into thinking it might've been the new banana milkshake. 

## Sprites
image
image

## Changelog

:cl:
add: Banana and strawberry milkshakes! Made by juicing berries and bananas respectively, with ice and cream.
/:cl:

Thanks for your time y'all, Happy Halloween.

### CODE REVIEW

**Comment by carshalash** [comment]
We need to make actual **STRAWBERRIES** one day instead of just using generic berry juice.

**Comment by KathrinBailey** [comment]
> We need to make actual **STRAWBERRIES** one day instead of just using generic berry juice.

I agree, I think some other codebases have done a good job at it.

**Comment by Shadowflame909** [comment]
> We need to make actual **STRAWBERRIES** one day instead of just using generic berry juice.

strawberries are a myth promoted by syndicate spies. There was no nanotransen induced strawberry disaster of 20xx. (Which can be found in the secret files in the vault) Any talk otherwise is treason and should be reported to the security department for re-education.

**Comment by Mothblocks** [comment]
are you actually playing with the default arial font? download the font that doesnt come with windows anymore https://file.house/q8Ld.fon

**Review by Twaticus — APPROVED** [review]

**Comment by KathrinBailey** [comment]
> are you actually playing with the default arial font? download the font that doesnt come with windows anymore https://file.house/q8Ld.fon

Well gee, thank you for fixing Runechat on every server that has it for me.
My highlight text was so big it was unreadable, and the character speech text was very difficult to read too.
It happened ever since I reinstalled Windows a few months back.

**Comment by Mothblocks** [comment]
Yeah it is something we need to fix, we can't legally ship that font

Anyway please merge from master so the failed tests go away

**Pull request merged**
