### PR TITLE
Delete _maps/map_files/MetaStation/MetaStation.dmm

### PR DESCRIPTION
**Pull request by NexusLeader**
Hoping this doesn't get into a PR on the main server. Trying to edit a fork here

### CODE REVIEW

**Comment by NexusLeader** [comment]
Fuck fuck

**Comment by CRITAWAKETS** [comment]
nonono, let him cook

**Comment by NexusLeader** [comment]
Oopsie. Just doing mapping changes and i'm being a idiot

**Comment by NexusLeader** [comment]
i forget how to edit without forcing a commit ;-;

**Pull request closed without merging**
