### PR TITLE
Removes PAIs from mulebots.

### PR DESCRIPTION
**Pull request by LanCartwright**
Enough of this shit.
4 war nukeops died to ONE mulebot. if that isn't bullshit enough. Nothing is.

Immune to stuns. Extremely difficult to kill. Kills in 3 hits.
No more. If it's AI controlled fair enough but this human control is ridiculous. Enough of it.

### CODE REVIEW

**Comment by coiax** [comment]
I ded plz nerf.

pAI mulebot removal is extremely popular for about a couple of days, and then people remember that mulebots are op and start being cautious and the nerf rabble dies off.

**Comment by Shapsy** [comment]
Being able to kill someone just by bumping into them and it being all over is shit

**Comment by PKPenguin321** [comment]
Nuke ops can kill a mulebot with like 2 or 3 bursts from any of their machine guns, maybe they should just get good

**Comment by LanCartwright** [comment]
can't do shit against the mulebot that camped corners. you can't just "lol shoot them" when all they need to do is touch you.

**Comment by PKPenguin321** [comment]
Except that you literally can

**Comment by coiax** [comment]
wow, someone camped a corner, ergo it's op? maybe they could buy an EMP grenade.

**Comment by Shapsy** [comment]
End this EMP meme, mulebots are simple mobs and are unaffected by EMP's. I just tested it out, it doesn't do anything, stop supporting people who use ion rifles on things that aren't borgs/AI's/mechs

**Comment by PKPenguin321** [comment]
If it doesn't do anything that's a bug because I have had mulebots outright killed by EMPs before.

But yeah literally walk away from the mulebot and shoot. Nuke ops are probably the best equipped to deal with them.

**Comment by Niknakflak** [comment]
This is not a bug, was opened after the freeze, pls close

**Comment by LanCartwright** [comment]
EMPs don't work, they instantly stun just by touching you, and they kill in three hits.

name one thing stronger that this context and one avaliable round after round.

**Comment by coiax** [comment]
> EMPs don't work

Incorrect. EMPs turn the mulebot off, and halve the cell charge.

**Comment by LanCartwright** [comment]
They don't even stun the mulebot. whats the point when they rarely run out of power?

**Comment by coiax** [comment]
> name one thing stronger that this context and one avaliable round after round.

Supermatter shard, available at 10000 credits, will instantly stun an op in full armour with just one item detonation. Can render someone immune to the effects with mesons + radiation suit, can be stored in space to prevent harmful effects.

**Comment by LanCartwright** [comment]
that doesn't move by itself.

**Comment by Shadowlight213** [comment]
Feature freeze in effect. No balance memes allowed.

**Comment by LanCartwright** [comment]
then we'll wait for the freeze to thaw

**Comment by Niknakflak** [comment]
lmao this should get closed

**Comment by KorPhaeron** [comment]
They really do need to be nerfed but FEATURE FREEZE

**Comment by Supermichael777** [comment]
but its not a feature. We shouldn't stop BALANCING THE GAME to make it more fun and engaging just because we hit an arbitrary number of issues(half of which aren't even bugs). also simple animal robots should never have become pai controllable, at least not without receiving Asimov/Drone law set (or at least
1. Do not harm or favor sentient beings.
2.Preform your designated function.). 
Heal-bots should heal everyone
Mule-bots shouldn't crush.
Clean bots shouldn't start cults.
Floor bots shouldn't become relevant.
Securitrons should dispense JUSTICE without regard for the identity of "Criminals". if a crew-member is shooting a fluke THAT'S ASSAULT NO FIGHTING.

**Comment by Eaglendia** [comment]
^ Pretty much all of this is ridiculous (except for cleanbots starting cults lmao is that a thing? sounds like it should have been covered by #17640).

I don't think I need to state my opinion. Mulebots have fifty fucking health. They die to four laser hits and most of the operative primaries will kill them in 2-3. Likewise, pAIs have always been made to follow their master's prime directive rather than some drone lawset, which adds depth to them as a whole. Once the freeze ends, consider perhaps reducing the Mulebot's brute resistance (it is a bit high) - or make bots/pAI-bound bots affected and potentially destroyed by EMP (iirc EMPs will fuck up a pAI so I don't see why they lose this weakness once stuffed into a bot) rather than just adding more special rules like this.

**Comment by coiax** [comment]
I've finished actual live testing on Sybil.

- pAIs in Mulebots are affected by EMPs; they are ejected and affected by the EMP (which means guaranteed silence, possible death)
- pAIs time to kill is around 2-3 seconds once they connect, pretty much irregardless of armour, which is frankly incredibly excessive
- If you manage to actually hit the Mulebot with a spray of bullets, it dies very quickly.
- pAI Mulebots can be stopped by a 2TC item called an EMP implant, which can be activated when stunned, and maybe in the future Warops should consider picking them up.

**Comment by Bawhoppen** [comment]
nice meme 
:-1: 
now get out you downstream shitler, nobody likes you

**Comment by KorPhaeron** [comment]
To everyone yelling "git gud" surely it is not coincidence that these things have wiped out entire operative squads multiple times on their own.

**Comment by LatD** [comment]
And also entire station crews of tens of people several times. This is also basically just a remake of my month old PR, if it helps getting this merged through that feature freeze.

**Comment by Cheridan** [comment]
there's infinite possibilities to make these things balanced instead of just removing the feature

**Comment by Dorsisdwarf** [comment]
It was an awful feature though since nobody uses pAI mulebots for anything other than killbots.

**Comment by optimumtact** [comment]
Reopen when the freeze is ended thank you.

**Pull request closed without merging**
