### PR TITLE
fixes supermatter sliver throwing

### LINKED ISSUE #53963: Throwing supermatter sliver (if you could get it) does nothing because of proc paths
https://github.com/tgstation/tgstation/blob/4e821cafc331c25a7e128650a5daeccc5a06f9f0/code/game/objects/items/theft_tools.dm#L152

https://github.com/tgstation/tgstation/blob/4e821cafc331c25a7e128650a5daeccc5a06f9f0/code/game/objects/items/theft_tools.dm#L263

The first one should be `/obj/item/nuke_core/supermatter_sliver` or, since you can't feasibly get it in your hand to throw, absent altogether.

### PR DESCRIPTION
**Pull request by Fikou**
## About The Pull Request

fixes #53963

## Why It's Good For The Game

sdgasdasd

## Changelog
:cl:
fix: fixes supermatter sliver throwing
/:cl:

### CODE REVIEW

**Review by LemonInTheDark — APPROVED** [review]
👍

**Comment by MoonFalcon** [comment]
Does this enable supermatter slivers to disintegrate whoever they hit? And does it work if launched? I've always hated that i couldnt make a disposals loop with an sm shard in it and disintegrate everyone inside

**Comment by MoonFalcon** [comment]
and if so, are there ways we can combat just how op this would be? If you spam click a sm with the scalpel you can take up to like 3 shards. People could just throw these for 1 hit kills. Maybe we could increase the radiation that a sm shard puts off?

 Or make it physically harm you to have on you without it being contained

**Comment by Fikou** [comment]
> and if so, are there ways we can combat just how op this would be? 

if you touch it you die, and the shard deletes itself too

>If you spam click a sm with the scalpel you can take up to like 3 shards. 

bug

**Pull request merged**
