### PR TITLE
Removes butcher knife from autolathe.

### PR DESCRIPTION
**Pull request by Helg2**
## About The Pull Request
Salt pr.
Current meta sucks.
It's still obtainable in-game by hacking cook's vendor. And you can find it on space ruins.
## Why It's Good For The Game
Station will have metal (of course only if roboticists are dead).
15 damage with 15 wound bonus weapon is quite too good for something you can just get from autolathe.
## Changelog
:cl:
balance: You can no longer make butcher knives in autolathe.
/:cl:

### CODE REVIEW

**Comment by MTandi** [comment]
Going to resolve this in a workaround way

**Comment by Rex9001** [comment]
Good change, makes the item less mass producable but its still there (hacked chef vendor) I hate having no metal because muh cleaver

**Comment by DaydreamIQ** [comment]
Pretty sure Goof already tried doing this and got denied

**Comment by Teleported-Bread** [comment]
#71254 tried this and got denied, though it seems that doing MSO's suggestion in the aforementioned PR (making it produce a dull cleaver) may be mergeable.

**Comment by Helg2** [comment]
Even if dull it will spend shit-tone of metal.

**Comment by Rex9001** [comment]
Make it cost less material and make it dull

**Comment by DaydreamIQ** [comment]
Just change the material cost if its such an issue, sounds like an administration problem if anything

**Comment by Helg2** [comment]
I mean i can but that will just leave useless item in autolathe.

**Comment by Striders13** [comment]
good pr, bad description

**Comment by Fikou** [comment]
> Make it cost less material and make it dull

then its just the kitchen knife which you can get from the same autolathe?

**Comment by Livrah** [comment]
Cleavers are still avaliable at chef's vendormats, right? 
Totally agree with this change. There is no reason not to print one of this every single round and people do it. 
Main problem from what I've seen that every "bad guy" gets chopped on the spot instead of non lethal takedown (or at least without gorillion wounds and roundremove).
Also each one costs 30k~ iron. I have a feeling this is sole reason why Terry's lathes have no metal every round.

**Comment by thematycer** [comment]
ah, second attempt of this Ideadpr, maybe on third try it will get removed

**Comment by Rex9001** [comment]
> > Make it cost less material and make it dull
> 
> then its just the kitchen knife which you can get from the same autolathe?

Eh true, just remove it from the autolathe

**Comment by necromanceranne** [comment]
I have a sneaking suspicion that this is cargo cult behavior. Reminds me of the obsession around the cake hat for a while.

Butcher cleavers are almost statistically identical in every way to circular saws. In some ways they may even be worse, since circular saws have a much higher bare flesh wound bonus.

The only reason people are getting butcher cleavers is because...other people are getting them. They're just good weapons. We have a lot of good weapons.

**Comment by GuillaumePrata** [comment]
> Butcher cleavers are almost statistically identical in every way to circular saws. In some ways they may even be worse, since circular saws have a much higher bare flesh wound bonus.

> The only reason people are getting butcher cleavers is because...other people are getting them.

I 100% agree with this, but I still think this PR would be nice for the game.

Having weapons be job locked is a thing we should encourage more so PVP encounters go differently, yes, people can just grab circular saws with some extra effort and be even deadlier if this PR is merged, but it is nice to have Cleavers be a chef's weapon, Saws be a doctor's weapon, etc, etc.

**Comment by BlueMemesauce** [comment]
Well this is a useless PR then, circular saws are just as powerful so people are just gonna print that instead
You'll have to remove circular saws too for there to be a point to this PR, but that doesn't make much sense since it's a medical tool.

**Comment by ATH1909** [comment]
15 force melee weapon imba 😔

**Comment by san7890** [comment]
If you're going to make a PR don't justify it by having "Salt PR" as one of your five justification sentences, you should actually have some meat especially for such a controversial change: https://github.com/tgstation/tgstation/blob/master/.github/CONTRIBUTING.md#justifying-your-changes

**Comment by san7890** [comment]
if you're also trying to cash in on the trend of opening a controversial "removes X" Pull Request in an attempt to goad people into doing an actual thorough and proper rework of a game mechanic, I will have to kindly request that you do not do that - or at least be cognizant of this trend now that I have informed you that it exists. It's not fair to the development culture here.

**Pull request closed without merging**
