### PR TITLE
makes techwebs bearable [24 HOUR RULE, ORANGES!]

### PR DESCRIPTION
**Pull request by ghost**
🆑 optional name here
tweak: A bug was fixed in the NTOS operating system! Multiple research servers now contribute towards overall point gain.
/🆑

[why]: allows players, if they have the knowledge of how to construct and the parts, to increase point generation with multiple RnD servers.
[24 hour rule oranges]

### CODE REVIEW

**Comment by optimumtact** [comment]
If you make another pr that has been denied already you will be gitbanned

**Comment by awesine** [comment]
24
hour
rule
@optimumtact

**Comment by optimumtact** [comment]
10,000 poxes on your stupid head

**Comment by awesine** [comment]
24
hour
rule
@optimumtact

**Comment by awesine** [comment]
why was this closed even

**Comment by optimumtact** [comment]
this specific change has been denied by our design lead within the last month

**Comment by duncathan** [comment]
there is no rule that says maintainers must let PRs stay open for 24 hours. there is a rule that says we must allow fair discourse for a given change. the fair discourse for this change happened in a previous PR; see #33719 for more details. 

by the way, if you have an issue with a maintainer's decision, please contact another maintainer in #coderbus and politely ask whether that action was justified. if the second opinion is in line with the original action, please accept the decision and do not reach out to more maintainers about the issue. thank you!

**Pull request closed without merging**
