### PR TITLE
 Ensures Legional continuality

### PR DESCRIPTION
**Pull request by ChangelingRain**
Legion's name is now capitalized, for that 'important boss' feel. Also, so you can more easily find it in the mob list.
The splitting Legion is no longer deleted when splitting, so ghosts remain orbitting it and admin VV menus still work on it after splitting.
You can't wand of death a Legion with remaining splits anymore.
Fixes a bug where Legion's pixel_x/y would be fucked up until it attacked something.

### CODE REVIEW

**Comment by KorPhaeron** [comment]
thanks

**Comment by RemieRichards** [comment]
Their need to be tiny legion skulls orbiting the Legion, and the number of skulls is how many splits it has left.

**Comment by KorPhaeron** [comment]
Maybe you could automatically set the new legions target to what it was attacking before the split, should help with the lag a bit if they are skipping the loop to find the target

**Comment by ChangelingRain** [comment]
Target now gets set when it splits.

**Comment by RemieRichards** [comment]
and my suggestion? *loud cough*

**Comment by ChangelingRain** [comment]
That one's sightly more complex and definitely a feature!
I might do it once the freeze is over, though.

**Comment by RemieRichards** [comment]
it fixes the lack of visual feedback with how long the fight will continue for.
also the freeze has fixed like, 3 net bugs this one is a huge flop already.

**Comment by ChangelingRain** [comment]
I'd ignore the freeze but I'm sure somebody would yell at me.

**Comment by KorPhaeron** [comment]
Players having no idea how long the fight will last and laughing off stage 1 as easy is half the fun though

**Comment by Cheridan** [comment]
It would be cool if you made it gender = PLURAL except for when it was at its smallest :open_mouth:

**Comment by KorPhaeron** [comment]
@changelingrain

are you going to do the gender thing or should I merge

**Comment by ChangelingRain** [comment]
Merge away that sounds like a feature

**Pull request merged**
