### PR TITLE
Modifies the SRM-8 mecha rocket rack to not suck so hard.

### LINKED ISSUE #23286: SRM-8 missile rack is stupidly weak
See title. It spawns 0 0 2 explosions. that's garbo.

### PR DESCRIPTION
**Pull request by ghost**
Ups it from a 0 0 2 to a 0 1 2. need to test for balance, but it should have a bit more of the uumph you expect from the second highest end mecha weapon, not to mention a fuck mothering MISSILE LAUNCHER ON A SPACE STATION SHOULD CAUSE BREACHES.  

any maintainer is free and ENCOURAGED to modify this because 0 1 2 up from 0 0 2 is shit balance. It just needs to...be better then it currently is. it feels a bit shitty right now.  moar terrain damage, less bullshit, this is primarily intended to get the ball rolling on discussion about this piece of shit exosuit weapon.

Fixes #23286

### CODE REVIEW

**Comment by ExcessiveUseOfCobblestone** [comment]
> balance

> it's a rocket launcher

hmmmm

**Comment by kevinz000** [comment]
NO.
This already has a 3x3 aoe of knockout, this does NOT NEED a buff to instacrit anyone they hit.

**Comment by francinum** [comment]
It's a fucking missile, at the current time it appears to be loaded with some tin cans the syndicate had lying around, and maybe a snap pop for an explosive charge.

**Comment by kevinz000** [comment]
If anything make it have a better range, right now it hitswhatever you click, as in it can't be used on anything offscreen, that would be a way better buff as people can't just stay 8 tiles of you to stay out of missile range.

**Comment by kevinz000** [comment]
from what I can see:
WITHOUT BOMB ARMOR: ex_act(3) has a 50% knockout chance and does 30 brute damage excluding any possible fire effects, and a 17% chance to dismember a limb. ex_act(2) has a 70% chance to knockout, does 120 damage split between brute and burn, and a 25% chance that rolls twice to sever up to 2 limbs.

**Comment by vcordie** [comment]
> If anything make it have a better range, right now it hitswhatever you click, as in it can't be used on anything offscreen, that would be a way better buff as people can't just stay 8 tiles of you to stay out of missile range.

I have no idea how to do that.

**Comment by kevinz000** [comment]
good time to learn.

**Comment by vcordie** [comment]
yeah. thinking about somehow putting in some snowflake case so it destroys more terrain without buffing its damage. need thoughts.

**Comment by Supermichael777** [comment]
this is a gun like object not a real gun it literaly throws a missile at something

**Comment by PKPenguin321** [comment]
missiles should straight up gib they're fucking missiles

**Comment by dannno** [comment]
pointless change to something that never gets used
literally doesn't matter if it gets merged or not

**Comment by francinum** [comment]
it's not used because it's a piece of shit.

**Comment by Cyberboss** [comment]
Add `Fixes #23286` to PR body

**Comment by Robustin** [comment]
I've been waiting years for this change. The SRM in its current form is a bad joke. It's less than a fucking welderbomb and its clunk as fuck to you.

**Comment by Thunder12345** [comment]
There's an actual rocket projectile now is there any reason no to use that?

**Comment by XDTM** [comment]
A direct hit with a rocket would definitely crit/dismember, the stats that @kevinz000 gave would be good imo. It would also allow you to breach walls with rockets, i think, which would make for a pretty fancy syndicate entrance.

**Comment by AdamElTablawy** [comment]
Why not simply make it use a rocket projectile?

Hell, the gryojet ammo exists. Why not use that? That's an exploding projectile.

**Comment by vcordie** [comment]
Anyone who can actually make the rockets behave like rockets and have an idea to make them not so hilariously weak, let me know, I'll close this and let you take over.

**Comment by Robustin** [comment]
@XDTM Kevinz doesn't suggest any new numbers bro. He just comments on what the proposed PR numbers would do.

As I understand it the current rocket ONLY inflicts ExAct(3) within 1 tile of where the rocket lands. It's not instant so you have to shoot and if youre target is moving, that means you have to lead your shots and someone yakkety sax'ing in a wide area will have a good chance of dodging any missile shot at them. 

Even if you do manage to catch someone in the explosion, its basically a coinflip if you actually knock them out - the brute damage only isn't going to stop anyone and with legstuns going away soon, that's the only benefit. So you can see how shit the missile is currently. Basic RND mechs can take a pacifier that can spray multiple taser projectiles per second, which is far preferable to shooting one projectile with a long delay between shots that has a 1-tile AOE effect which a 50% chance of actually stunning. 

The ExAct(2) at the impact point isn't even that big of a buff, but at least it ensures that if you manage to hit someone directly in the fucking face with a fucking missile launcher fired from a big scary (expensive) syndie mech that it will at least fucking fuck their shit up. You simply cannot justify its current state of "I hit an assistant in the face with a missile launched from my mauler and the dude just kept fucking running at full speed with minor bruising".

**Comment by ShadowDeath6** [comment]
I think the best course of action is to make it like the hades carbine or something and have it shoot resprited gyrojet shots like someone said however long ago

**Comment by vcordie** [comment]
Anyones free to contribute any code that would modify it to be a proper projectile that travels past the screen

**Comment by Thunder12345** [comment]
@vcordie take the example of all the other mech guns, we have an actual rocket projectile and everything

**Comment by kevinz000** [comment]
https://github.com/tgstation/tgstation/blob/12570805bd393d4e1dbc9070d3e35e5012f6a705/code/modules/projectiles/projectile/special.dm#L46
copy/paste rename vars adjust explosion damage and you have a projectile.

**Comment by Thunder12345** [comment]
Or use the same projectile/a child with different values

**Comment by vcordie** [comment]
Closing until I get some feedback on my forum thread and have time to fix this (along with mechs at large) properly.

**Pull request closed without merging**
