### PR TITLE
Washing machines now behave like buildable machines + new sprites.

### PR DESCRIPTION
**Pull request by ArcaneMusic**
## About The Pull Request

image

Washing machines have been given a basic tech design and placed on the research tree. There was an issue that I cannot for the life of me find from a long time ago which listed machines that cannot be built, but exist roundstart. One such example was the washing machine, another was the copier.

This makes a machine that is available roundstart available to build, using a basic stock part spread (matter bin/manipulator).

Additionally, I desoul'd the sprites. Discussion of such is open.

## Why It's Good For The Game
Machines that exist and cannot be repaired or replaced in any way is silly, unless their core value exists in the volatility. Something as silly and mundane as a washing machine probably shouldn't be up there with reactive teleport armor in how boned you are if it disappears without a trace.

Plus, I wanted to make some pretty sprites and I got an excuse.

## Changelog

:cl: ArcaneMusic Ft. EricZilla/Sampslig

qol: Washing Machines are now buildable like regular machines off the biological processing node..
imageadd:  New Washing Machine Sprites
/:cl:

### CODE REVIEW

**Comment by Likteer** [comment]
Great idea, not so good desoul. Have you accounted for the bloody sprite that happens if you wash animals inside (in Minecraft)?

**Comment by Megamaw** [comment]
I never got the 'soul' thing before now. But I think I do, now. 

Like, these are ostensibly better than the originals, but there's something charming about the old ones I can't quite put my finger on.

**Comment by Twaticus** [comment]
not working for me

**Comment by Megamaw** [comment]
> not working for me

okay i'll bite what's not working. the code, or the resprite? because frankly i think we should be able to build new washing machines

**Comment by Twaticus** [comment]
it was just for the sprites, i must have completely glazed over the rest of the PR. it can be reopened or remade with just the code changes. my apologies.

**Comment by Megamaw** [comment]
yeah the core concern i had was that it wasn't an atomic change. the sprite changes weren't doing it for me, either but the other half was just "you can now build washing machines"

**Pull request closed without merging**
