### PR TITLE
Plasmamen no longer die instantly to the wizard cursed items event

### PR DESCRIPTION
**Pull request by ChangelingRain**
Rip plasmeme

### CODE REVIEW

**Comment by Iamgoofball** [comment]
YOU SAID THE HOUSE WOULD BE EMPTY

**Comment by ChangelingRain** [comment]
I may have started some fires. Like medbay, and mech bay. Any other fires were either someone else or accidents!

**Comment by Iamgoofball** [comment]
Why did you have mosquito coil in your locker?

**Comment by TechnoAlchemisto** [comment]
plasmamen are a curse on this codebase

**Pull request merged**
