### PR TITLE
bans new files called misc/miscellaneous

### PR DESCRIPTION
**Pull request by Kylerace**
## About The Pull Request
its equivalent to a useless variable name except it also shows up in file search

## Why It's Good For The Game
image
pointed out by @tralezab

### CODE REVIEW

**Review by Mothblocks — APPROVED** [review]

**Review by Timberpoes — APPROVED** [review]

**Comment by Mothblocks** [comment]
>  pointed out by tralezab

um ive been saying this for several months now

**Review by MrsTonedOne — CHANGES_REQUESTED** [review]
Nope.

Not gonna play this game.

There will always be a need for this kind of file.

Trying to shoehorn 100% of things into something that only fits 99% of things isn't gonna work.

You're perfectly organized code base isn't going to ever come to fruition. millions of billion dollar companies haven't been able to get this to happen, a small open source team isn't going to either.

Suggested change:

> New files must have unique names. you cannot make new files called any common name such as unsorted, misc, defines, etc. Consider misc_helpers or atmos_defines.

**Comment by Kylerace** [comment]
> You're perfectly organized code base isn't going to ever come to fruition. millions of billion dollar companies haven't been able to get this to happen, a small open source team isn't going to either.

**Comment by Rohesie** [comment]
There's a ton of repeated names.
It doesn't help that the runtimes only provide the name of the file, but not the path.
I'm in favor of requiring people to be a bit more descriptive.
Also to encourage them to make new files if necessary, for proper categorization of things.

**Comment by Kylerace** [comment]
> You're perfectly organized code base isn't going to ever come to fruition. millions of billion dollar companies haven't been able to get this to happen, a small open source team isn't going to either.

we're not trying to make a perfectly organized codebase, just stop bad practices that lead to harder development for people working with your code in the future. its certainly easy to add something to misc.dm number 1235 but not grouping together related code into relevant files is a drain on long term ability to work on the code. also now that i think about it this doesnt say anything about adding to already existing nondescriptive files

the only thing i think we're losing here is that working on several 10 line files that contain a single object declaration that really doesnt fit with anything else is arguably harder than grouping them together into an explicit misc file, but allowing this leads to people not organizing perfectly organizable code. to clarify i mean:

- new very small feature that cant reasonably be organized into an existing descriptive file and there are no other related features that can be paired with it in a new common file: not ideal, arguably worse to separate than to clump together. but if the feature is ever expanded upon or a similar one is added it is certainly better for it to already be in its own file than to be in line 1310 of misc_clothing.dm
- new very small feature that cant reasonably be organized into an existing descriptive file but there are other related features that can be paired with it in existence already: perfectly fine, make a new file that groups all of them together but again since they are randomly placed it is hard to find them all since theyre disorganized, necessitating further work to fix the problem. 
- new feature or group of features that do have an existing descriptive file: absolute positive, putting those features into a misc file just obfuscates code.

>New files must have unique names. you cannot make new files called any common name such as unsorted, misc, defines, etc. Consider misc_helpers or atmos_defines.

i like this, non unique but technically descriptive file names are annoying when they could easily be made unique (see: computer.dm, which one? you decide) but i dont believe this is mutually exclusive with banning misc/whatever. 
personally im not one to strive for perfection in something as abstract and nebulous as code quality beyond a certain point of reasonable competence, but i dont see why this requirement pushes past reason.

**Comment by Kylerace** [comment]
good points shared on discord, ill think about this some more

**Comment by Kylerace** [comment]
i dont care anymore

**Pull request closed without merging**
