### PR TITLE
Increases default minute topic limit

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request

Increases the default MINUTE_TOPIC_LIMIT from 100 to 200

This change takes the per-minute limit from 1/6th to 1/3rd of the per-second*60 limit.

## Why It's Good For The Game

I've had players, from diverse mainstream servers not just TG, able to consistently hit the 100/minute limit in the course of normal/legitimate play. That the default rate limit keeps tagging ordinary players suggests that it is too low.

I think it would be beneficial to new server operators if the default were to better accommodate normal play, and so would be less likely to need to hunt down a configuration option when it starts affecting players.

## Changelog

:cl:
server: Default-configuration MINUTE_TOPIC_LIMIT has been increased
/:cl:

### CODE REVIEW

**Comment by Profakos** [comment]
Indeed, I always get spammed by these warnings when Geneticists are solving DNA sequences at a rapid pace...

**Comment by optimumtact** [comment]
Im unlikely to shift this unless MSO approves it as a sensible default. so it's pretty unlikely it will get merged as he's not very active.

**Comment by YehnBeep** [comment]
Ok, well, I'll leave it anyways just in case.

**Comment by optimumtact** [comment]
yeah you never know, sometime's he comes out of nowhere with burst of activity.

**Pull request merged**
