### PR TITLE
Occupational Corruption Device

### PR DESCRIPTION
**Pull request by Orchian**
## About The Pull Request

Adds a new traitor item exclusive to Heads of Personnel and Quartermasters that triggers a bureaucratic error

## Why It's Good For The Game

Adds a new method for traitors to cause indirect havoc to the station at large

## Changelog
:cl:
add: Added a new traitor item for HoP and QM, the OCD
/:cl:

### CODE REVIEW

**Comment by anconfuzedrock** [comment]
all this seems to do is create an inconvenient problem that in no way is related to the traitor doing it and won't even change people's behaviour. if traitors had a button that they could press that would stun everyone for 10 seconds includin the traitor using it at some unpredictable point in the future, that would be a pretty lame traitor item with no use. this seems like just a "press to cause minor problem" button with no depth or possible interesting use cases. the pot of greed of traitor items, except not even good.

**Comment by wesoda25** [comment]
Self deletion is pretty lame, considering that similar items such as the crab phone don't have such a feature. There should be evidence.

**Comment by Jack7D1** [comment]
Its frankly the HOPs MO to be mildly inconvenient. This would fit perfectly

**Comment by XRandomXManX** [comment]
I can how having 15 captains, all with aa arriving on the station could stir up some chaos and fun for a job that can just walk up and take whatever objective they're after

**Comment by anconfuzedrock** [comment]
> Its frankly the HOPs MO to be mildly inconvenient. This would fit perfectly

Yet this doesn't seem to be a thing the HOP did. It's just a random event. When the HOP does it there's no difference between him doing it, and the random event just triggering. All it is is a waste of tc and i doubt anyone would ever buy this more than once. It's like if the janitor had a button to cause a backpressure surge, except the janitor actually benefits from that since he has galoshes, uh.. it's like if medbay could press a button to cause meteors, except that the HOP causing a job lister error has even LESS synergy because the HOP already has the ability to change the job listings minorly. It's more like if engineers could cause a random event that gives everyone on the station insulated gloves. Yeah, that seems about right.

**Comment by ATH1909** [comment]
> > Its frankly the HOPs MO to be mildly inconvenient. This would fit perfectly
> 
> Yet this doesn't seem to be a thing the HOP did. It's just a random event. When the HOP does it there's no difference between him doing it, and the random event just triggering. All it is is a waste of tc and i doubt anyone would ever buy this more than once. It's like if the janitor had a button to cause a backpressure surge, except the janitor actually benefits from that since he has galoshes, uh.. it's like if medbay could press a button to cause meteors, except that the HOP causing a job lister error has even LESS synergy because the HOP already has the ability to change the job listings minorly. It's more like if engineers could cause a random event that gives everyone on the station insulated gloves. Yeah, that seems about right.

maybe buff it by letting the HoP choose which job the event chooses, allowing for them to increase the number of slots for a head of staff job, which they normally can't do

**Comment by genessee596** [comment]
Seems like a waste of TC if you don't get some control over what job gets overflown. Why would I spend 2 TC on something that
1) has a good chance of happening during the round anyways
2) could be completely useless, removing the cap on something dumb like botanists or lawyers instead of what i wanted
3) is entirely reliant on latejoiners deciding that they want to go whatever job gets overflowed
4) can get overwritten by the random event happening again at any point during the round

Right now, what would happen is a traitor would use it exactly once. Then, they realize how useless the item is, and it falls into obscurity.

**Comment by optimumtact** [comment]
it's perfect

**Pull request merged**
