### PR TITLE
emitter beams go on forever

### LINKED ISSUE #32781: Emitter shots randomly disappear
It is no longer possible to do emitter loop memes I am sad, is this intentional or a bug?

### PR DESCRIPTION
**Pull request by praisenarsie**
:cl: Frozenguy5 & JJRcop
add: Emitter beams now go on forever.
/:cl:

Fixes #32781

this raises the problem of emitter spam and how it can crash servers

### CODE REVIEW

**Comment by coiax** [comment]
They should probably qdel at SOME point...

**Comment by DaedalusGame** [comment]
ah yes, i want back the times when you could instantly delaminate the sm by rotating one reflecty boi

**Comment by Spaceinaba** [comment]
goobye  blobs never liked them anyways

**Comment by Buggy123** [comment]
:+1: A fun change in many cases and not _that_ much of a negative change in other cases.

Insta-delamming the SM is already perfectly possible, the fastest I've seen it delam without employing emitter tricks or throwing stuff into it is about 5 seconds and resulted in a max size explosion.

Shooting it at a blob all at once could work, but it would take a _long_ time to build up and would be really obvious and easy to sabotage if it was anywhere near the blob. Also, its a major hazard for the chaotic crew fighting the blob because if they step into the reflection path for even a moment they instantly die.

Server crashing memes are possible but, it'd be pretty obvious and there are _already_ plenty of ways to massively lag or crash the server which have gone unfixed for a while. Fairly certain I know of at least one that isn't logged and almost no one else knows about.

On the plus side, you get fun memes like emitter-mirror mazes and bar rage cages with instant death walls, all jolly good fun.

**Comment by Jalleo** [comment]
Set it to 200 we dont wabt infinite loops occuring.

**Comment by Robustin** [comment]
Not worth the lag/crash risks for the tiny niche of benefits it would bestow. Higher range seems like a decent compromise.

**Comment by ExcessiveUseOfCobblestone** [comment]
needs to die if it gets reflected a bunch or switches z levels ( and any other way that could make them indefinite to stack4lag)

**Comment by Bawhoppen** [comment]
It will eventually hit something if it changes zlevels anyways (since it had to be fired from an emitter anyways and it would hit that if nothing else)

I like the idea of firing blindly into space to kill everyone.

**Comment by vuonojenmustaturska** [comment]
Considering we only fairly recently resolved another issue where emitters were used to crash servers, I'm not going to be merging something that obviously enables different means of crashing the server.

**Pull request closed without merging**
