### PR TITLE
updates mosin mob sprite

### PR DESCRIPTION
**Pull request by ReinaCoder**
## About The Pull Request
Updates the mosin mob sprites. Also moves the sprites to the 64x64 gun sprites file and changes some code accordingly 
image
image
## Why It's Good For The Game
the obj sprites were resprited but the mob sprites were untouched, this pr updates the sprites and brings them in line with the obj
## Changelog
:cl:
image: the mosin and prime nagants' mob sprites have been updated
/:cl:

### CODE REVIEW

**Comment by Wallemations** [comment]
On my phone at the moment, is the right one the Madoka one?

**Comment by necromanceranne** [comment]
It's the regal mosin. Silverscales use them.

**Comment by Singul0** [comment]
long gun go pew pew

**Comment by Wallemations** [comment]
> It's the regal mosin. Silverscales use them.

Noted

**Review by Wallemations — APPROVED** [review]

**Pull request merged**
