### PR TITLE
Fixes handle_fall() log spam

### LINKED ISSUE #22796: Those exploding pirates
```
ADMIN LOG: Explosion with size (0, 1, 5, 0) in area Unexplored Location (149,206,6 - JMP)
ADMIN LOG: Explosion with size (0, 1, 5, 0) in area Unexplored Location (149,205,6 - JMP)
runtime error: 
[00:46:53]Cannot execute null.handle fall().
[00:46:53]proc name: fall (/mob/living/carbon/fall)
[00:46:53]  source file: carbon.dm,229
[00:46:53]  usr: null
[00:46:53]  src: Vivian Stroble (/mob/living/carbon/human)
[00:46:53]  src.loc: null
[00:46:53]  call stack:
[00:46:53]Vivian Stroble (/mob/living/carbon/human): fall(1)
[00:46:53]Vivian Stroble (/mob/living/carbon/human): update canmove()
[00:46:53]Vivian Stroble (/mob/living/carbon/human): death(1)
[00:46:53]Vivian Stroble (/mob/living/carbon/human): death(1)
[00:46:53]Vivian Stroble (/mob/living/carbon/human): death(1)
[00:46:53]Pirate (/obj/effect/mob_spawn/human/corpse/pirate): create(null)
[00:46:53]Pirate (/obj/effect/mob_spawn/human/corpse/pirate): New(null)
[00:46:53]Pirate (/mob/living/simple_animal/hostile/pirate): death(null)
[00:46:53]Pirate (/mob/living/simple_animal/hostile/pirate): death(null)
[00:46:53]Pirate (/mob/living/simple_animal/hostile/pirate): update stat()
[00:46:53]...
[00:46:53]Pirate (/mob/living/simple_animal/hostile/pirate): adjustHealth(15, 1, 0)
[00:46:53]Pirate (/mob/living/simple_animal/hostile/pirate): adjustHealth(15, 1, 0)
[00:46:53]Pirate (/mob/living/simple_animal/hostile/pirate): handle temperature damage()
[00:46:53]Pirate (/mob/living/simple_animal/hostile/pirate): handle environment(/datum/gas_mixture/space (/datum/gas_mixture/space))
[00:46:53]Pirate (/mob/living/simple_animal/hostile/pirate): Life(2)
[00:46:53]Pirate (/mob/living/simple_animal/hostile/pirate): Life(2)
[00:46:53]Pirate (/mob/living/simple_animal/hostile/pirate): Life(2)
[00:46:53]Mobs (/datum/subsystem/mobs): fire(1)
[00:46:53]Master (/datum/controller/master): Loop()
[00:46:53]Master (/datum/controller/master): StartProcessing()
runtime error: 
[00:47:29]Cannot execute null.handle fall().
[00:47:29]proc name: fall (/mob/living/carbon/fall)
[00:47:29]  source file: carbon.dm,229
[00:47:29]  usr: null
[00:47:29]  src: Raegan Shick (/mob/living/carbon/human)
[00:47:29]  src.loc: null
[00:47:29]  call stack:
[00:47:29]Raegan Shick (/mob/living/carbon/human): fall(1)
[00:47:29]Raegan Shick (/mob/living/carbon/human): update canmove()
[00:47:29]Raegan Shick (/mob/living/carbon/human): death(1)
[00:47:29]Raegan Shick (/mob/living/carbon/human): death(1)
[00:47:29]Raegan Shick (/mob/living/carbon/human): death(1)
[00:47:29]Pirate Gunner (/obj/effect/mob_spawn/human/corpse/pirate/ranged): create(null)
[00:47:29]Pirate Gunner (/obj/effect/mob_spawn/human/corpse/pirate/ranged): New(null)
[00:47:29]Pirate Gunner (/mob/living/simple_animal/hostile/pirate/ranged): death(null)
[00:47:29]Pirate Gunner (/mob/living/simple_animal/hostile/pirate/ranged): death(null)
[00:47:29]Pirate Gunner (/mob/living/simple_animal/hostile/pirate/ranged): update stat()
[00:47:29]...
[00:47:29]Pirate Gunner (/mob/living/simple_animal/hostile/pirate/ranged): adjustHealth(15, 1, 0)
[00:47:29]Pirate Gunner (/mob/living/simple_animal/hostile/pirate/ranged): adjustHealth(15, 1, 0)
[00:47:29]Pirate Gunner (/mob/living/simple_animal/hostile/pirate/ranged): handle temperature damage()
[00:47:29]Pirate Gunner (/mob/living/simple_animal/hostile/pirate/ranged): handle environment(/datum/gas_mixture (/datum/gas_mixture))
[00:47:29]Pirate Gunner (/mob/living/simple_animal/hostile/pirate/ranged): Life(2)
[00:47:29]Pirate Gunner (/mob/living/simple_animal/hostile/pirate/ranged): Life(2)
[00:47:29]Pirate Gunner (/mob/living/simple_animal/hostile/pirate/ranged): Life(2)
[00:47:29]Mobs (/datum/subsystem/mobs): fire(1)
[00:47:29]Master (/datum/controller/master): Loop()
[00:47:29]Master (/datum/controller/master): StartProcessing()
```

While we're here, does anyone know why these pirates are so prone to exploding?

### PR DESCRIPTION
**Pull request by ghost**
Fixes #22796?

### CODE REVIEW

**Comment by Shadowlight213** [comment]
This...doesn't fix the bug at all.
The problem is that the mob is being spawned in nullspace.

**Comment by Xhuis** [comment]
The bug seems unresolvable or nobody's ever tried. This is just a sanity check that prevents the problem it causes.

**Comment by Shadowlight213** [comment]
No it literally wont fix the runtime.
The null.handle_fall() is the TURF being null. Not the mob.

**Comment by Xhuis** [comment]
Aah. I'll put one there too, then.

**Comment by Shadowlight213** [comment]
Also, this literally is just hiding the runtime, which means the bug is probably never going to be fixed now.
I recall I tried basically this with sparks runtimes at one point and got yelled at by maintainers.

**Comment by Xhuis** [comment]
I can easily try to fix this, but I have no idea where to start. any ideas?

**Comment by Shadowlight213** [comment]
Start from here.
https://github.com/tgstation/tgstation/blob/master/code/modules/mob/living/simple_animal/simple_animal.dm#L287
There was a similar issue before that was fixed by #20098 so the cause is likely related.

**Comment by Core0verload** [comment]
Maybe I'll try to track this bug too.

**Comment by Xhuis** [comment]
That'd be helpful. Life has kept me occupied so H haven't been able to work as much as I'd like.

**Comment by KorPhaeron** [comment]
Doesn't fix the issue

**Comment by Xhuis** [comment]
So much for working on it more I guess

**Comment by KorPhaeron** [comment]
Two lines of code in the wrong file sitting open/being closed will not impact your ability or anyone elses to work on it more

**Comment by Xhuis** [comment]
This kills the branch

**Pull request closed without merging**
