### PR TITLE
Adds the log copier from /vg/

### LINKED ISSUE #7047: Public Game Logs
Head Admins would like to get some form of publicly accessible game, attack, and admin logs for the benefit of the players.

We'd have the IPs and CIDs censored, and only logs from at least a day earlier (or round, if possible) would be available so they can't cheat the current round. 

Asay chatter could also be kept private as we do occasionally have sensitive conversations in there, like we do in adminbus. But I think everything else should be put up for grabs.

### PR DESCRIPTION
**Pull request by tkdrg**
Credits for this tool go to N3X15 over at /vg/.
This removed IPs/CIDs from logs. It's intended to support public logs.
Fixes #7047

### CODE REVIEW

**Comment by MrStonedOne** [comment]
how tested is this at sanitizing the logs?

**Comment by CorruptComputer** [comment]
Why was this closed?

**Comment by tkdrg** [comment]
Veto'ed by the host apparently. See #7047

**Comment by ike709** [comment]
rip

**Comment by Tenebrosity** [comment]
Well, this would've done a shitload for transparency and admin accountability. Thanks HG, Anone and SoS.

**Pull request closed without merging**
