### PR TITLE
Removes language encryption keys

### PR DESCRIPTION
**Pull request by LemonInTheDark**
## About The Pull Request

We want languages to be special to species, these devalue that and make them far too common.
The listen only thing does this especially badly. I'm sorry arcane I know it's good for cargo but this vibes horrible and we shouldn't have it

## Why It's Good For The Game

You should be able to talk privately via language with minimal snoopage

## Changelog
:cl:
del: Removed language encryption keys from cargo, s bad for species talking among each other, a thing we want them to do
/:cl:

### CODE REVIEW

**Review by Mothblocks — APPROVED** [review]

**Comment by Helg2** [comment]
Did someone ever used them at least?

**Comment by DATA-xPUNGED** [comment]
> Did someone ever used them at least?

i've bought them ONCE when some lizards were speaking in draconic to spite a speciest
They stopped right after it arrived ¯\_(ツ)_/¯

**Comment by RedBaronFlyer** [comment]
> Did someone ever used them at least?

They're situationally useful on those rare occasions when you really need to listen in on someone speaking a different language or if there's a non-human with the foreigner quirk. Other than that, not really. The 600 credit price for a single one, and it being a private order (so no cargo budget) means that it rarely gets used. I've played for a year and a half and I've only seen it ordered or used twice.

**Comment by carshalash** [comment]
You guys are going overkill on this **non-issue.**

**Comment by CRITAWAKETS** [comment]
i've literally never seen anybody buy these because rarely do you need to _speak_ a language, only understand it. And for understanding languages, there are many, many cheaper ways of doing so.

**Comment by Singul0** [comment]
as if cargo hasn't have their cargo budget made useless as is already.

**Comment by RedBaronFlyer** [comment]
> as if cargo hasn't have their cargo budget made useless as is already.

If there was some way for cargo to supply its budget to help with whatever, I'd be 100% for it. I play Cargo Tech a lot, and it pains me when we have 60k in the budget after buying an expensive shuttle and insurance, and still have nothing to spend it on. You can only order so much pizza, department equipment, mosins, etc., before it gets redundant.

**Comment by BlueMemesauce** [comment]
> as if cargo hasn't have their cargo budget made useless as is already.

These didn't use the cargo budget.

**Comment by carlarctg** [comment]
I'm in favor purely because nobody uses these and they bloat the goodies tab

**Comment by SomeoneYouProbablyKnow** [comment]
No one's using them because by the time it arrives and you get it from cargo you no longer need to use it. And knowing languages is not important enougu for G-amers to have it on their uber shiftstart checklist

**Comment by YuliceTheDruid** [comment]
I mean the biggest issue for me with the language keys and why I never used them is because they take up the same fucking slot as a department key (!!!). Something that could be used to listen in on sec, sci, cargo, or any other department, or used for a syndie key or a binary key if you're a traitor.

**Comment by SomeoneYouProbablyKnow** [comment]
Can always hot swap headsets, DJ In da booth

**Comment by AlamoTurtle** [comment]
A major argument against allowing the bilingual quirk to select language was that if you were that desperate to know a language, you could buy a language encryption key from cargo. There's no reason to remove that option, I feel.

**Comment by RedBaronFlyer** [comment]
> A major argument against allowing the bilingual quirk to select language was that if you were that desperate to know a language, you could buy a language encryption key from cargo. There's no reason to remove that option, I feel.

It's yet another instance of coding monkey paw, just like the janitor key system, instead of just giving janitors paramedic-style access.

"Man, I wish the bilingual trait would let me select what language to know, instead of knowing gibbering or slime talk"
*monkey paw curls*

**Comment by OverwatchVoice** [comment]
Languages are already pretty obscure and rarely used, giving even less options for ways to engage with the mechanic feels dumb

**Pull request merged**
