### PR TITLE
removes an unused variable from lungs.dm

### PR DESCRIPTION
**Pull request by TJatPBnJ**
hexane is now gone

### CODE REVIEW

**Review by Mothblocks — APPROVED** [review]

**Comment by TJatPBnJ** [comment]
fuck
how do i github

**Comment by TJatPBnJ** [comment]
nobody saw that

**Comment by Jared-Fogle** [comment]
Great work sir

image

this is why you dont pr from master. make a new branch for your feature and use that

**Comment by TJatPBnJ** [comment]
fuck

**Pull request closed without merging**
