### PR TITLE
Parrot-Cracker Balance

### LINKED ISSUE #15482: Poly's cracker mechanic is mathematically ridiculous
speak_chance is a percentage out of 100. Normally it starts at 3.

3
6
12
24
48
96
192
stupidly bigger and bigger numbers that are pointless because it's a percentage out of 100

exponents go up fast, kids

### PR DESCRIPTION
**Pull request by octareenroon91**
Exponential growth is now at a more tolerable level.  It takes 20 crackers to push a parrot from 1% to 100% chance to speak.

Fixes  #15482 .

### CODE REVIEW

**Comment by Incoming5643** [comment]
Practical odds

Base Chance: 3%
1 Cracker: 31%
2 "          ": 52.47%
3 "          ": 66.729%
4 "          ": 76.7103%
5 "          ": 83.69721%
6 "          ": 88.588047%
7 "          ": 92.0116329%
8 "          ": 94.40814303%
9 "          ": 96.085700121%
10 "        ": 97.2599900847%
11 "        ": 98.0819930593%
12 "        ": 98.6573951415%
13 "        ": 99.0601765991%
14 "        ": 99.3421236194%
15 "        ": 99.5394865336%
16 "        ": 99.6776405735%
17 "        ": 99.7743484014%
18 "        ": 99.8420438810%
19 "        ": 99.8894307167%
20 "        ": 99.9226015017%
.
.
.
∞ "         ": 100

**Comment by octareenroon91** [comment]
OK, what would be better, a ratio of 0.95 in place of0.7?

**Comment by Jalleo** [comment]
How can you even get a cracker i never worked it out.

**Comment by Supermichael777** [comment]
by kitchen magics.
its pastery dough with salt and peper

**Comment by Buggy123** [comment]
Just salt, actually.

Also fun removal :-1:

**Comment by octareenroon91** [comment]
I thought this would be fun-neutral.

**Comment by bgobandit** [comment]
:+1:

**Comment by tkdrg** [comment]
You should do at the very least 0.9. 0.7 is waaay too low.

**Comment by octareenroon91** [comment]
Yeah, exponential decay of the silence chance was pretty crappy.

I've gone back to exponential growth, but with a much lower base.

**Pull request merged**
