### PR TITLE
Gives the reactive armor slowdown 1 again

### PR DESCRIPTION
**Pull request by Shadowlight213**
Reverts it from best armor to specialized armor.

### CODE REVIEW

**Comment by Aloraydrel** [comment]
adios meme armor

**Comment by PKPenguin321** [comment]
will likely conflict with https://github.com/tgstation/-tg-station/pull/16241

**Comment by Lumipharon** [comment]
No one will use it if you add slowdown again.
When it had slowdown before no one used it, and that was when it had none of the other nerfs it has recently acquired.

**Comment by PKPenguin321** [comment]
>No one will use it if you add slowdown again.

Fine by me tbh

>other nerfs it has recently acquired

None have actually been merged yet

**Comment by Lumipharon** [comment]
radiation memes. 

Also if no one will use it then it might as well just be removed, which is dumb. Sticking a reasonable CD on it is enough of a nerf that it isn't objectively the best defence anymore, which is fine.

**Comment by Notamaniac** [comment]
You could give it slowdown when it's active instead, so it discourages people from having it on 24/7 and actually have to use brainpower when to use it or not.

**Comment by Lumipharon** [comment]
That's actually a good idea.

**Comment by KorPhaeron** [comment]
Howabout we have one nerf at a time instead of 3?

**Comment by Dawgas** [comment]
I honestly don't get why people would use this piece of shit item anyway

Can't people "git gud" instead of demanding that literally everything be nerfed because they lost??

**Comment by PKPenguin321** [comment]
>I honestly don't get why people would use this piece of shit item anyway

It literally has a 50% chance to completely negate all stuns/all damage from any source and move you from harm's way. It is objectively the best armor in the game.

**Comment by KorPhaeron** [comment]
Merged a different nerf, we can revisit this if we decide we need another

**Pull request closed without merging**
