### PR TITLE
Running unit tests no longer requires a launch parameter

### PR DESCRIPTION
**Pull request by Ryll-Ryll**
## About The Pull Request
Unit tests currently require you to compile with the UNIT_TESTS define in _compile_options.dm AND run the server with a special unit test parameter in order to actually run. Dreamdaemon doesn't have an option to add launch params, and I'm a baby who doesn't want to switch back and forth between a powershell window to actually run the tests, so I asked around if removing the parameter would break anything. @Cyberboss and @Jared-Fogle said they didn't see any issues with it, though obviously I don't know how the git/test pipeline works, so more insight would be appreciated.

Obviously this removes the ability to compile with UNIT_TESTS and still be able to choose between launching the game and launching the unit tests, but I don't know if anyone actually does that in practice. Also pinging @MrStonedOne cause I dunno if this may affect any of the server pipeline

## Why It's Good For The Game
Makes running unit tests a little easier and less alt-tab intensive on local

### CODE REVIEW

**Comment by Cyberboss** [comment]
Not changelog worthy

**Review by Cyberboss — DISMISSED** [review]

**Comment by Jared-Fogle** [comment]
someone used the wrong branch :thinking:

**Comment by Ryll-Ryll** [comment]
shhhhhhh

**Comment by AnturK** [comment]
If you're doing this remove the param from travis script

**Review by MrsTonedOne — APPROVED** [review]

**Review by Cyberboss — CHANGES_REQUESTED** [review]
What Antur said

**Comment by optimumtact** [comment]
> Dreamdaemon doesn't have an option to add launch params

Wat, you just add -params "test-run" to the cli

**Comment by Ryll-Ryll** [comment]
updated travis

**Comment by Cyberboss** [comment]
@optimumtact think they mean through the GUI

**Review by Cyberboss — APPROVED** [review]

**Pull request merged**
