### PR TITLE
Revert "Introduces the new taser"

### LINKED ISSUE #16416: New Hybrid Taser's laser mode displays no sprite
>Hold your taser
>Swap to "kill" mode
>Watch as it becomes invisible

### PR DESCRIPTION
**Pull request by Core0verload**
Reverts tgstation/-tg-station#15671. Because @Cheridan merged this shit change nobody but him wanted. 

What the fuck?

Also fixes #16416.

### CODE REVIEW

**Comment by ChangelingRain** [comment]
Wait, what cheridan why

**Comment by lzimann** [comment]
shit change, revert it please

**Comment by ChangelingRain** [comment]
WE HAVE TESTMERGING FOR A REASON

**Comment by PKPenguin321** [comment]
:+1: For revert

**Comment by TrustyGun** [comment]
wow that's fucking stupid :+1:

**Comment by Zilenan91** [comment]
:-1:  Nah it's good

**Comment by CPTANT** [comment]
:-1: 

And holy shit, stop acting like everyone was against this, the MAJORITY of people were in favour of at least testing this.

**Comment by lzimann** [comment]
That's right, TESTING. It was just merged like everyone liked. And it was a bad change anyway.

**Comment by PKPenguin321** [comment]
why do we even need this change @CPTANT 
is it because it's your codebaby or do you have an actual reason because i remember you telling me that we should add it because i was "afraid of change" or something but that's all

**Comment by optimumtact** [comment]
Please don't revert war with a headcoder

**Comment by CPTANT** [comment]
@PKPenguin321  Like already stated multiple times the change is primarily because the taser is now cut into 2 extremes. A 1 shot gg no re taser with shit range and ammo and a beamspam to the max disabler.

Merging the 2 into 1 new weapon brings them both to the nice middle ground.

**Comment by Xhuis** [comment]
Probably a good idea to revert this

**Comment by Shad0vvs** [comment]
Just give sec 1hp next time.

**Comment by vista-** [comment]
DOUBLE TAP!

**Comment by Armhulen** [comment]
Revert when

**Comment by Cheridan** [comment]
The tasers had ALREADY been tested, with the only issue people had with it was a bug that was fixed.

**Comment by Zilenan91** [comment]
It's different so they hate it

They'll get used to it in a week

**Comment by lzimann** [comment]
the light laser is pretty much useless

**Comment by Steelpoint** [comment]
Give it time before you revert it, or try to.

There should be a rule that any change has a minimum of one week from its merge date of not being reverted outside of the change either being broken or horribly unbalancing.

**Comment by Zilenan91** [comment]
Yeah actually if anything the light laser needs a buff

**Comment by Core0verload** [comment]
@Cheridan, this PR took two shitty taser modes and united them into one, which has all the downsides of both.

**Comment by Supermichael777** [comment]
secretly its THE GOON TASER

**Comment by AdamElTablawy** [comment]
Goon taser isn't too bad actually.

Anyway, I like the new taser. It's more a buff than anything-the first shot instantly disarms the guy and slows them down, the second's a stun. Even if you miss the second shot you have an unarmed, slow target and a nice big ol clip with huge range to down them with, plus flashbangs, flashes, and pepperspray.

The light laser isn't meant for killing people-it's meant to make roundstart sec capable of dealing with simple mobs like carp, spiders, or blob spores more effectively. Versus a human, if's effectively a tickle, because sec shouldn't be lasering everyone they see to death anyway and giving sec officers access to roundstart lasers is dumb. A weak 'fuck off space carp' setting on the taser is better than the obnoxious, overpowered as shit beamspam prior setting it had.

I like it, so do a lot of other people. The only people who don't seem to like it are the about 8 people yelling here about it-it's a good compromise between 1hit gg with shit range and 3hit permanent gg with insane range and speed and clip. Tazer loses no effectiveness, really-the first hit is an instant disarm and slows the guy, and unless they're packing 4 more guns, that means an easy target. It gives someone maybe one more second tk react-with the new tazer firerate, the second bolt is already coming by the time the first one connects.

Granted, nobody's going to care what I say anyway in defense of it because people are stubborn and will just stuff dicks in their ears and say 'it sucks REEEE'.

But still, don't revert, this was very much needed it's well liked.

**Comment by Iamgoofball** [comment]
I like the new taser. It's fun to get hit by and fun to use

**Comment by Xhuis** [comment]
\>fun to get hit by
TIL that goofball is a masochist

**Comment by KazeEspada** [comment]
@AdamElTablawy Have you tried to tased Mehki? He's packing four more guns.

**Comment by Bawhoppen** [comment]
probably better to go back to normal :+1:

**Comment by Robustin** [comment]
>TFW when you don't comment on a shit PR because you think nobody would ever be stupid enough to merge it

**Comment by Cheridan** [comment]
but you did comment on the pr

**Comment by Cheridan** [comment]
grats guys you survived the second testmerge of taserinos

**Comment by PKPenguin321** [comment]
r e k t

**Pull request merged**
