### PR TITLE
That's it. *GAGS'ifies your berets*

### PR DESCRIPTION
**Pull request by GoldenAlpharex**
## About The Pull Request
Berets now make use of GAGS, which means that they can now all look nice and more consistent.
Here's what we have so far (actually this has changed and all the badges except one were removed at Twaticus' request):
image
As you can see, the Captain and Central Command now both have their own beret, although there's currently no way to obtain them, but I probably will add the Captain's beret to their locker.

There's also a few icons that I added that weren't used yet, but they're really, really pretty so I thought that I might as well include them now while I'm at it. I didn't want to add too many actual berets now, to not create too much bloat and to not turn this is a feature PR.

What's left to do:

- [x] Delete all the old beret sprites.
- [x] Make it so certain berets can't be customized in their vendors. I shouldn't have to say why.
- [x] Adjust a few of the sprites so they look a bit better.
- [x] ~~Maybe add a few more berets now if that's what maintainers want.~~ ~~They don't want more, I guess.~~ Actually they do, let's add some more then, might be in a future PR though, we'll see.

I also made a change to GAGS to make it so not all GAGS-ified items could be recolored in vendors. It's now flag-based, and has been documented in the README.md of GAGS-related stuff.

## Why It's Good For The Game
Now all the berets use the same base sprite, which wasn't previously the case, as many of them used an older, uglier sprite that didn't look quite as nice as this one.

## Changelog
:cl: GoldenAlpharex, with some help of Imaginos (PositiveEntropy)
imageadd: Added a new badge to display on future berets.
expansion: Nanotrasen's fashion department decided to release a brand new series of berets, meant to replace the old collection and featuring a wider array of possibilities!
refactor: Berets are now converted to GAGS, with more options for customization and greater consistancy between the sprites.
code: Not all GAGS sprites can be recolored in vendors by default anymore.
/:cl:

### CODE REVIEW

**Comment by Imaginos16** [comment]
EPIC

**Comment by LemonInTheDark** [comment]
I don't like adding more berets. I think reserving them for sec and the mime lends them a relative rarity, and while I understand that people like the aesthetic, I dislike moving them out of that niche. Could you elaborate on this?

`:cl:GoldenAlpharex, with some help of Imaginos (PositiveEntropy)`
This line will cause the changelog to fail to generate, you need a space after `:cl:`

**Comment by optimumtact** [comment]
if you add so much as a single extra uniform sprite to a single locker I will punch a beret shaped hole in your heart

**Comment by maxymax13** [comment]
bring back the maint beret altar

**Review by Twaticus — CHANGES_REQUESTED** [review]
i'd say scrap the extra badges and just use the one from hos beret. gold for hos/warden, silver for sec/fancy sec/durathread. flat_cap needs to be added aswell. 

image

regarding the extras, i'd be fine with a basic colorable beret being added to the dorms vendor,
and department berets if they spawn in department vendor and not lockers but only if the maints sign off

**Comment by maxymax13** [comment]
twaticus no remember what happened with the RD beret the maints are going to push the indiana jones button and a rolling boulder will crush you

**Comment by GoldenAlpharex** [comment]
> i'd say scrap the extra badges and just use the one from hos beret. gold for hos/warden, silver for sec/fancy sec/durathread. flat_cap needs to be added aswell.
> 
> image

I mean, the extra badges don't exactly take up a lot of space (it's like, what, 7 pixels for the biggest ones?) and add some nice color and shape variation in my opinion. I forgot the flat cap, I knew I missed it but I forgot the name of it.

> regarding the extras, i'd be fine with a basic colorable beret being added to the dorms vendor,

Already a thing in the autodrobes, I don't know if the ClothesMates have the black beret, but if they do, it would be colorable as well.
> and department berets if they spawn in department vendor and not lockers but only if the maints sign off

I mean, that really wouldn't take me long, that's why I already added a few more badges, it would be really quite easy.

I still need to talk with ninja to figure out how to stop some of them from being colorable in the vendor.

**Comment by Twaticus** [comment]
eh the color badges are ugly i'd rather them be kept uniform with gold/silver

**Comment by Twaticus** [comment]
> twaticus no remember what happened with the RD beret the maints are going to push the indiana jones button and a rolling boulder will crush you

the RD beret PR of '89? nothing happened that day

**Comment by GoldenAlpharex** [comment]
> eh the color badges are ugly i'd rather them be kept uniform with gold/silver

I mean, I know you won't see it from icon diff, but I also added some actually nicer icons, like a shield-like badge (for sec, probably), a cross (for medbay, probably), and a kind of police-looking one, that I'm not sure where to put, but it just looks too good to not keep it.

**Comment by Fikou** [comment]
does this change the vintage/archaic beret?

**Comment by GoldenAlpharex** [comment]
> does this change the vintage/archaic beret?

It does, but I tried to respect the original colors as much as possible. There's still one of them that I kind of messed up, as you can see in the provided screenshot, but yeah, they're modified to fit in GAGS.

**Comment by Fikou** [comment]
> > does this change the vintage/archaic beret?
> 
> It does, but I tried to respect the original colors as much as possible. There's still one of them that I kind of messed up, as you can see in the provided screenshot, but yeah, they're modified to fit in GAGS.

the entire point of them is for them to look like old beret sprites before they were resprited, might as well remove them if youre gonna change them

**Comment by GoldenAlpharex** [comment]
> > > does this change the vintage/archaic beret?
> >
> > It does, but I tried to respect the original colors as much as possible. There's still one of them that I kind of messed up, as you can see in the provided screenshot, but yeah, they're modified to fit in GAGS.
> 
> the entire point of them is for them to look like old beret sprites before they were resprited, might as well remove them if youre gonna change them

I mean, I don't mind doing that, I just thought that it was interesting to keep some slightly different ones in reference to those.
I could also just restore the sprites if we really want to keep them.

**Comment by optimumtact** [comment]
> i'd say scrap the extra badges and just use the one from hos beret. gold for hos/warden, silver for sec/fancy sec/durathread. flat_cap needs to be added aswell.
> 
> image
> 
> regarding the extras, i'd be fine with a basic colorable beret being added to the dorms vendor,
> and department berets if they spawn in department vendor and not lockers but only if the maints sign off

seems fine

**Comment by optimumtact** [comment]
a pref would be beteter

**Comment by AlinaStarkova** [comment]
> 
> 
> I don't like adding more berets. I think reserving them for sec and the mime lends them a relative rarity, and while I understand that people like the aesthetic, I dislike moving them out of that niche. Could you elaborate on this?
> 


berets exist for science already, and its also not too hard to get one from science or the costume vendor either to wear as any job

**Review by Twaticus — APPROVED** [review]

**Pull request merged**
