### PR TITLE
Lightens airtank outlines slightly

### PR DESCRIPTION
**Pull request by ChangelingRain**
# New

# Old

### CODE REVIEW

**Comment by RemieRichards** [comment]
Wow that's subtle.
How about making the outlines match the colours, like most of our sprites?

**Comment by dannno** [comment]
there is no actual recognizable difference to me.

**Comment by Steelpoint** [comment]
I can't see a difference. At least not one that anyone will notice.

**Comment by WJohn** [comment]
Yeah me neither. This must be extremely minor, but whatever.

**Comment by RemieRichards** [comment]
As I said, there is a difference, but it's incredibly subtle

**Comment by RemieRichards** [comment]
It's a change of
61,54,52 ->77,74,74
(rgb)

**Comment by optimumtact** [comment]
I can't tell a difference either

**Comment by kilkun** [comment]
why

**Comment by dannno** [comment]
No matter how hard I look, it's practically just the same image.

**Comment by davidchan13** [comment]
Is that light functional? Seems like they'd be a really good in-hand/on-sprite indication to the value of how much Air or gas is in a tank (Like, under 100kpa is red, 101-303 yellow, 304-1014 green?)

**Comment by CosmicScientist** [comment]
I can tell it's changed when I look at the on ground plasma tank with the line on its side... maybe not for the rest though.

**Pull request merged**
