### PR TITLE
Tabbles and racks can be disassembled only on non help.

### PR DESCRIPTION
**Pull request by Dennok**
## About The Pull Request
Tabbles and racks can be disassembled only on non help.

## Why It's Good For The Game
No more unintended table and rack disassembly.
Engi want to place his tools on tabbles, why it cant?

## Changelog
:cl:
add: Tabbles and racks can be disassembled only on non help.
/:cl:

### CODE REVIEW

**Comment by Dennok** [comment]
Or make it non help intent check?

**Comment by PKPenguin321** [comment]
Non help is better

**Comment by Tlaltecuhtli** [comment]
reinforced tables exist for this reason

**Comment by Dennok** [comment]
> reinforced tables exist for this reason

No, it exist from another reason. And you unable to place toggled on welding tool on it.

**Comment by Akrilla** [comment]
yeah bit silly you can't place tools on a table because it thinks you're trying to interact with it.

**Comment by Alek2ander** [comment]
You can just throw tho

**Comment by Dennok** [comment]
> You can just throw tho

Problem when you do this in zero gravity

**Comment by SynnGraffkin** [comment]
I mean, if there is zero gravity then there are more pressing issues than putting your tools on tables. The only tools this effects is wrenches, screwdrivers, and lit welders, which personally I would have to ask why are you put a lit welder down unless it is experimental.

**Comment by WarlockD** [comment]
I have to agree with the change.  Sometimes my inventory is to full and just want to put it down on a table.  Its not like your setting up and tearing down tables all shift.

**Comment by dee-dubya** [comment]
You can't put an unlit welder on a table either. It'll just tell you "you need to turn the welder on" thinking that you're trying to interact with it rather than place the item down.

**Comment by Dennok** [comment]
Nice! +100% calls of "why i cant disassemble tabble"

**Pull request merged**
