### PR TITLE
Sleepypen refills are now capped at 15 volume

### PR DESCRIPTION
**Pull request by Robustin**
:cl: Robustin
balance: Sleepypens can now only be refilled with 15 units of chemicals, down from 45. 
/:cl:

Long overdue change. Saw another PR trying to remove the refill function outright, so I'm going to pull the rare dick move of opening a competing PR to #30840 so that we can produce a more reasonable solution. 

Closes #30840

### CODE REVIEW

**Review by Cyberboss — DISMISSED** [review]

**Comment by RandomMarine** [comment]
Why close #30842?

**Comment by CPTANT** [comment]
It's weirdly inconsistent that it comes filled with 45u but can only hold 15u.....

**Comment by XDTM** [comment]
Industrially-compressed chemicals vs pouring chems in

**Comment by Ergovisavi** [comment]
The chemical reagent system is not and never will be balanced or fun to be struck with. Allowing for the refilling of an instant injector only leads to worse gameplay for everyone involved, as a result.

**Comment by Robustin** [comment]
What XDTM said, manual refills with a syringe are not as efficient.

I don't think its the best gameplay either but neither is a lot of our combat. 15 units of most poisons are at least tolerable to deal with and the more powerful ones require more effort and forethought than "dump 45 units of random poison from the poison kit into a pen and watch me instantly kill people with it".

**Comment by Ergovisavi** [comment]
If the concern is that people are currently just using it for instant kills (agreed upon to be horrible) and that they are currently refilling it with such amount that any dingus will do it with any amount of chemicals (also terrible), but you're still allowing people to use it to instantly kill people (STILL terrible) why not solve the actual issue instead of slapping a band-aid on it and calling it good?

Why not just convert it to a self-recharging hypospray with a cooldown? Suddenly you can actually determine exactly how the item functions and can make it effective without making it stupid. People who already have access to chemicals are not exactly hurting for methods to apply them.

**Comment by CPTANT** [comment]
There is nothing wrong with being killed by a sleepypen.

I swear for some people any form of killing by antags is "horrible".

**Comment by Robustin** [comment]
@Ergovisavi 

At 15 units nothing should be instant, but it will be lethal for certain mixes if left untreated.

The problem is two-fold:

1) 45 units means you can be brainless in mixing poisons because as long as you throw multiple damaging poisons into the mix, it will be very lethal. With 15 units you cannot just spam different poisons for a lethal effect. 

2) 45 units also means you can stack the most potent effects and present multiple instant effects (stun, mute, tons of damage) in order to "instantly kill" someone. To my knowledge that simply isn't possible at 15 units - and if it is that's a balance issue for the poison, not for the pen.

**Review by Cyberboss — APPROVED** [review]

**Comment by Supermichael777** [comment]
does it work through hardsuits? Then its still fucking good.

**Comment by Anonmare** [comment]
@Supermichael777 No, I checked the hypospray and its ignore flags are at 0, and since sleepy pen doesn't have the var, that means it's inherited it and won't go through hardsuits.

Medipens *will* though, but they're not refillable.

**Comment by AdamElTablawy** [comment]
neurotox clf3

that'll kill you even with 15u

remember that 15u is a syringe's injection, and syringe guns are perfectly capable of guaranteed kills within about four seconds even with a shit mix

**Comment by Robustin** [comment]
@AdamElTablawy 

I've literally never died that fast to anything out of a syringe gun. Honestly CFL3 is probably due for a balance pass.

**Comment by ExcessiveUseOfCobblestone** [comment]
Most chems are due for a rebalance but people want to nerf the chem entirely when it's just inject method that could use a nerf [since most medicines are also not as effective via injection].

**Comment by Supermichael777** [comment]
Hey robustin ever been hit with 10u neurotoxin and 5u mute toxin? you die awful fast.

**Comment by Robustin** [comment]
That still requires manual killing and gives nearby witnesses the obvious tell that someone just stunned you (and witnesses can see who did it).

**Comment by Supermichael777** [comment]
sure its overt, but you still die.  The problem with chems is individual fights not how does it fair against the disarm spamming hoards.

**Comment by Robustin** [comment]
Individual fights have not and never will be fair in this game, I'm just trimming some of the most bullshit aspects that have required addressing for a long time.

**Comment by KorPhaeron** [comment]
I don't care about this either way someone close it or merge it or whatever

**Comment by Cyberboss** [comment]
I personally don't like the inconsistency

**Pull request closed without merging**
