### PR TITLE
Revamps donutstation engineering/supermatter rooms.

### PR DESCRIPTION
**Pull request by ShizCalev**
Fixes #43352

:cl: ShizCalev
fix: Revamped Donutstation's engineering and supermatter rooms to fix a number of issues that prevented proper functionality, and resolved numerous aesthetic complaints.
fix: Fixed Jones actions on a couple away mission fridges.
/:cl:

todo:
- [x] test to ensure proper functionality.

### CODE REVIEW

**Comment by FloranOtten** [comment]
Does the AI have sight of both of the pumps in the access airlock?

**Review by SpaceManiac — DISMISSED** [review]
Boy does Donut have a lot of mapping errors but here are the ones in scope to this PR

Unconnected scrubbers pipe located at Supermatter External Access (140, 127, 2) (JMP)
Unconnected air supply pipe located at Supermatter External Access (140, 127, 2) (JMP)
Unconnected pipe located at Supermatter External Access (140, 127, 2) (JMP)
Unconnected air supply pipe located at Engineering (144, 118, 2) (JMP)
Unconnected pipe located at Engine Room (151, 133, 2) (JMP)
Unconnected pipe located at Engine Room (151, 132, 2) (JMP)

/obj/machinery/atmospherics/pipe/simple/scrubbers/hidden/layer3 ...stacking... around Engineering (145, 113, 2)
/obj/machinery/atmospherics/pipe/manifold/scrubbers/hidden/layer3 ...stacking... around Engineering (145, 114, 2)
/obj/machinery/atmospherics/pipe/simple/scrubbers/hidden/layer3 ...stacking... around Engineering (145, 112, 2)
/obj/machinery/atmospherics/pipe/simple/scrubbers/hidden/layer3 ...stacking... around Engineering (145, 115, 2)
/obj/machinery/atmospherics/pipe/simple/scrubbers/hidden/layer3 ...stacking... around Engineering (145, 116, 2)

**Comment by ShizCalev** [comment]
ty

**Review by SpaceManiac — APPROVED** [review]
Substantial improvement, I'll keep an eye on if it ends up needing further cleanup after the other donutstation PR

**Pull request merged**
