### PR TITLE
Moves atom functionality from SSobj to SSatoms

### PR DESCRIPTION
**Pull request by Cyberboss**
Been meaning to do this for a while now

### CODE REVIEW

**Comment by MrStonedOne** [comment]
just kill off ssobj.

processing is a datum thing anyways

**Comment by Cyberboss** [comment]
Its 90% objects getting processed though.

On Feb 15, 2017 1:36 PM, "Kyle Spier-Swenson" <notifications@github.com>
wrote:

just kill off ssobj.

processing is a datum thing anyways

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/tgstation/tgstation/pull/24139#issuecomment-280098228>,
or mute the thread

**Comment by Fox-McCloud** [comment]
>Its 90% objects getting processed though.

Every single reagents datum is processed every cycle unless it has `set_reacting(FALSE)`, so there' actually a LOT of non-objects in the processing list.

**Comment by optimumtact** [comment]
Gah

**Pull request merged**
