### PR TITLE
Brings a beloved feature back to the codebase

### PR DESCRIPTION
**Pull request by vuonojenmustaturska**
:cl: Naksu
code: Waddling is now available as a component
/:cl:

### CODE REVIEW

**Comment by ExcessiveUseOfCobblestone** [comment]
without implementation....

evil evil girl

**Comment by ninjanomnom** [comment]
You did this cyberboss, without the ease of components this would never have happened.

It's not too late to burn it all down

**Comment by JJRcop** [comment]
Penguins should get this by default.

**Review by SpaceManiac — APPROVED** [review]

**Comment by zamolxius** [comment]
give this to clown roundstart

**Pull request merged**
