### PR TITLE
Adds CE power tool sprites for the toolbelt

### LINKED ISSUE #30280: toolbelt has no sprite for CE's upgraded tools
jaws of life / power drill / experimental welder

### PR DESCRIPTION
**Pull request by ghost**
:cl: Xhuis
imageadd: The hand drill and jaws of life now have sprites on the toolbelt.
/:cl:

Sprites shown below (WARNING: GRAPHIC)

I'm quite happy with the hand drill sprite but the jaws of life sprite is bleh enough that I added a viewer advisory warning above the image. Nonetheless, it's far preferable to having none at all.

Fixes #30280.

### CODE REVIEW

**Comment by ChangelingRain** [comment]
Do those positions conflict with any other tools you can put in a toolbelt?

**Comment by Xhuis** [comment]
The screwdriver overlaps the wrench due to it being a different version of the same tool, and the jaws of life very slightly overlap the multitool, but otherwise they're functional

**Comment by DoctoreMad** [comment]
>Both of them overlap yeah, _but otherwise its functional_

Now that's patrician as hell :^)

**Review by Cyberboss — APPROVED** [review]

**Comment by Xhuis** [comment]
It works, doesn't it? :P

**Comment by DoctoreMad** [comment]
Its just funny because it reminds me of admin appeals that start with "I didn't do anything traitor-like except this little thing and this other little thing and-"

**Pull request merged**
