### PR TITLE
Fix for mobs falling off the mob_list, as suggested by Carn.

### LINKED ISSUE #7317: Mobs are randomly removed from the moblist
Alright, going to ref this to @Ergovisavi because he knows what's going on (from a coding standpoint).

Essentially what's happening is, every so often, a player disappears from the moblist. No one's sure why it's happening but it needs to be looked into. CANNOT REPRODUCE, but I'll ping anyone who wants to be pinged when it happens.

Side-effects:
*Players cannot die, can take up to 500+ brute to no ill effect.
*If stunned/disabled/what-have-you, they stay in tha tstate. Can't be revived in any way.
*They don't show up in the moblist, so you can't interact with them in any way. No ban, no kick, no get-mob, nothing.

Someone mentioned it basically stops them from updating.

Seriously needs to be fixed, this requires us to remake an entire player every time it happens.

### PR DESCRIPTION
**Pull request by Boggart**
Carn suggested this to fix mobs falling off the mob_list, I tested it on my local and found no issues but the issue is very hard to reproduce.

Fixes #7317.

### CODE REVIEW

**Comment by TheVekter** [comment]
Well, let's give it a shot! I'll report after update if we get it again.

**Comment by Razharas** [comment]
Well seems easy enough

**Comment by Razharas** [comment]
Well since the original issue is under CRITICAL tag i suppose this can be fastmerged

**Comment by TheVekter** [comment]
Haven't seen or heard any of this happening again. I'll be keeping an eye out for it.

**Pull request merged**
