### PR TITLE
Removes Internals Screen Element

### PR DESCRIPTION
**Pull request by Fox-McCloud**
I dunno why this wasn't done eons ago.

Removes the internals screen element.

now that action buttons are a thing, are reliable, and optimized, there's really not a need for dedicated screen elements that interact with an object.

As such, this removes the longggg present internals/o2 button, in favor of just using an action button.

:cl: Fox McCloud
del: Removes discrete internals button (use the action button for tanks)
/:cl:

### CODE REVIEW

**Comment by RemieRichards** [comment]
I cri

**Comment by outbools** [comment]
used to this so much i want to cri

**Comment by optimumtact** [comment]
I"m against this, why are you removing functionality for no reason

**Comment by outbools** [comment]
Actually it would be fun to watch how some "veterans" dies from deprivation because of this!

**Comment by outbools** [comment]
https://nanotrasen.se/wiki/index.php/Guide_for_beginners

Hell beginner guide should be updated to exclude this button and include Action buttons because they are not present in wiki right now

**Comment by outbools** [comment]
w-wait we are not on Paradise aren't we...

**Comment by outbools** [comment]
mccloud y u so confusing reeeeeeeeeeeeeeeeeeeeeeeeee

**Comment by outbools** [comment]
https://tgstation13.org/wiki/Starter_guide
update wiki

**Comment by calzilla1** [comment]
S T O P

**Comment by Fox-McCloud** [comment]
@optimumtact 

Because I'm not. Any time you equip a tank, you get an action button that allows you to toggle on/off your internals. 

Having a *dedicated* button for a single object (that you won't even have on you 95% of the game, unless you're an engineer or something) is just silly. It wastes space and is reminiscent of a bygone era.

There's literally no need for a dedicate internals button anymore; it's basically just an "always there" action button that hogs space and isn't used the vast majority of the time.

**Comment by Grazyn** [comment]
Speaking of clutter, there should be a button to hide ALL the HUD (call it "cinematic mode" or something")

**Comment by RemieRichards** [comment]
@Grazyn F11, hit it twice.

**Comment by Grazyn** [comment]
Wew, things you learned that can be game changing

**Comment by lzimann** [comment]
It's f12 not f11.

Also I'm against this change, no reason to happen.

**Comment by lzimann** [comment]
It's also funny you mention "less cluttered UI" when action buttons do the complete opposite of that.

**Comment by Fox-McCloud** [comment]
Action buttons are dynamically allocated based on having them or not; that's a *lot* better than having a fixed, unmovable screen element for a *single* item on your screen that is not used by the vast majority of players for the vast majority of their game.

Yes, having lots of buttons with actions on them is cluttered, but it's better than having a bunch of fixed, unmovable icons that you can never hide or get rid of.

I'd really like to hear some actual logic applied against this change being made other than "I'm used to it" or "I like it".

**Comment by Cyberboss** [comment]
I'm for this, action buttons just make it redundant.

**Review by Cyberboss — APPROVED** [review]

**Comment by ExcessiveUseOfCobblestone** [comment]
Thinking this isn't used constantly is really odd.

**Comment by Shadowlight213** [comment]
I don't like this, as the internals button made it really easy to tell if your internals were on or off. Plus, the button was a well known location, allowing it to be quickly turned on in stressful situations.
It would be nice if the visual element was kept at least, with it just not functioning as a button.

**Comment by Fox-McCloud** [comment]
There's no need for it though, when the action button for tanks, which turns incredibly bright green is just as clear.

Heck, with this PR, it makes those action buttons behave far more consistently, since a lot of instances of turning on internals (or turning them off) *wouldn't* update the action button and leave it its normal dull color.

**Comment by Tacolizard** [comment]
i do support this, I'm just hesitant because I like the spriting on the internals button a lot.

**Review by ChangelingRain — APPROVED** [review]

**Comment by MrPerson** [comment]
I tried to do this 2 years ago and got shot down. So yeah obviously this is still necessary.

**Comment by PKPenguin321** [comment]
I like this button

**Comment by lzimann** [comment]
People still use this button, I still use the button, there's no harm in leaving it in.
As for screen clutter, that's just not true, the icon is small and non intrusive, you barely notice it, and it doesn't fuck with your view or anything(like equipped equipment does).

**Comment by Yiu113** [comment]
Not gonna lie without this button I'd probably end up forgetting if I had internals on or not and end up gassing myself or choking to death half of the time. Really see no point in removing it, it's tiny.

**Comment by calzilla1** [comment]
You knooow you COULD just make it a preference.

**Comment by optimumtact** [comment]
hell no

**Comment by Iamgoofball** [comment]
@Fox-McCloud 
here's how you deal with this:
make it a speshul snowflake action button that looks like the old internals button and goes where it used to go instead of being in the AB bar

that way it's not there when you don't need it, we keep the old UI memes, and everyone's happy

**Comment by Cyberboss** [comment]
Overwhelming olds stuck in their ways, oh well

**Comment by Fox-McCloud** [comment]
Unfortunate. Sometimse changes have to be made, regardless of majority opinion (movement speed, space speed, etc). 

Ohhhh well.

**Comment by PKPenguin321** [comment]
Super necro but I'm going through old notifications
This is just a thought but I would actually be okay with it if this button was made into a dedicated action button that appeared only if you had both a mask and an air source. It could use the same icon or whatever.
I like the button because it saves me from having to search for the correct air tank action button, especially if I have multiple of them for whatever reason (oxygen tank and jetpack for example), so if its functionality was preserved and it was just moved to an action button instead of it being removed and forcing the player to click the airtank action buttons we'd get sort of a compromise

**Pull request closed without merging**
