### PR TITLE
Felinids using gripper gloves now "pounce" instead of "leap" and "tackle".

### PR DESCRIPTION
**Pull request by uomo91**
## About The Pull Request

pounce

## Why It's Good For The Game

pounce

## Changelog
:cl:
tweak: Felinids now "pounce" instead of "leap" and "tackle" when using gripper gloves.
/:cl:

### CODE REVIEW

**Comment by optimumtact** [comment]
```
Code adding, removing, or updating the availability of alien races/species/human mutants without prior approval. Pull requests attempting to add or remove features from said races/species/mutants require prior approval as well.
```

**Comment by uomo91** [comment]
I know of that clause in the contributing guidelines but I didn't consider a couple text strings displaying differently to be a "feature".
If you would like I can close it.

> ```
> Code adding, removing, or updating the availability of alien races/species/human mutants without prior approval. Pull requests attempting to add or remove features from said races/species/mutants require prior approval as well.
> ```

I knew of that clause in the contributing guidelines but I didn't think changing a few text strings counted as a "feature". If you'd like I can close this.

**Comment by wesoda25** [comment]
gag

**Comment by itseasytosee** [comment]
against god and nature.

**Comment by optimumtact** [comment]
You need to seek approval from a maintainer.

I am not going to approve this, but some other maintainer might.

**Comment by Ryll-Ryll** [comment]
The meme PR I wanted to make but didn't have the courage to do. I would've given felinids a free +1 to tackles on top of it so it's probably for the best I never did.

**Comment by kappa-sama** [comment]
please don't port this if there is a god in this world

**Comment by ancientpower** [comment]
lol

**Comment by minichibis** [comment]
doesnt seem unreasonable to me but im not a maintainer

**Comment by Qustinnus** [comment]
Dislike this change, I dislike giving races these snowflakey checks for rather cringy changes that just appease the wrong type of player who do the nyaaaa type roleplay.

**Comment by itseasytosee** [comment]
Do not foster cringe.

**Comment by spookydonut** [comment]
I will not be approving this change

**Comment by interestingusernam3** [comment]
Fetish content, speedmerge

**Comment by Fabian272** [comment]
Leave the leap in but replace the tackle with pounce

**Comment by Rohesie** [comment]
This looks incredibly harmless and much more subtle than the meowing-speech for example. Most players won't even notice it's a thing.
It's in line with the felinid species, so unless it gets veto'ed soon I'll merge it.

**Pull request merged**
