### PR TITLE
Adds a drill sergeant's hat in the warden's locker

### PR DESCRIPTION
**Pull request by VileBeggar**
## Changelog
:cl: Vile Beggar
add: Warden now has an added drill hat in his locker.
/:cl:

## About The Pull Request
Adds a drill sergeant's hat into the warden's locker. 
Sprites aren't made by me but I saw them gathering dust in the code though.

image

## Why It's Good For The Game
More choice in fashion is good. The warden doesn't have much of a job to do besides looking pretty at the desk and this hat helps him do that better.

### CODE REVIEW

**Comment by praisenarsie** [comment]
image

**Comment by necromanceranne** [comment]
Please make this cause whoever is wearng it to yell at microphone volume.

**Comment by VileBeggar** [comment]
> 
> 
> Please make this cause whoever is wearng it to yell at microphone volume.

i guess i could make it do that if you emag it for some dumb-ass reason

**Comment by zxaber** [comment]
This should be added to the list of borg-compatible hats.

**Comment by FantasticFwoosh** [comment]
But what if you just want to be :canada:

**Comment by Nickkoranda** [comment]
Canadians don't exist in space, obviously

**Comment by Steelpoint** [comment]
The hat was always odd looking when we added it years ago, and it was removed because no one wore it.

Not forgetting this was originally for the Head of Security, not the Warden.

**Comment by HomocidlePancakes** [comment]
download

WHAT THE HELL ARE YOU TWO DOING? GET YOUR ASS DOWN HERE NOW! AND YOU TOO!
WHAT DO YOU THINK THIS IS? FUCKING CLOWN PLANETE? PULLING ON YOUR BATONS LIKE A PACK OF FUCKING CLOWNS! You obviously want to know what a real man has so get down on your knees and take every single rubber pelet out of my gun NOW! Disobidience huh? That's a mistake.

**Comment by FantasticFwoosh** [comment]
```
/obj/item/clothing/head/warden/drill/speechModification(M)
	if(copytext(M, 1, 2) != "*")
		M = " [M]"
		var/list/canada_words = strings("canada_replacement.json", "canadian")

		for(var/key in canada_words)
			var/value = canada_words[key]
			if(islist(value))
				value = pick(value)

			M = replacetextEx(M, " [uppertext(key)]", " [uppertext(value)]")
			M = replacetextEx(M, " [capitalize(key)]", " [capitalize(value)]")
			M = replacetextEx(M, " [key]", " [value]")

		if(prob(3))
M += pick("eh?, EH?")
```
I rest my case.

**Comment by VileBeggar** [comment]
damned i fucked it up i'll reopen it later

**Pull request closed without merging**
