### PR TITLE
Rebalances Donksoft vendors.

### PR DESCRIPTION
**Pull request by DaCoolBoss**
## About The Pull Request

Notable changes:
- Prices have been increased across the board. They're about on par with the good clean fun vendor now.
- Less of each item. The machine will have to be restocked more often.
- Fake emags and fake hot potatoes are now avaliable.
- The ammo boxes are half-size boxes (20 darts) in the non-syndicate vendor. Each foam dart costs 5 credits, and every riot dart costs 10 credits. The syndicate vendor sells the old size of boxes (40 darts) for the same price, getting twice as many darts per credit.
- Syndicate balloon is now in the contraband section. There is only one of them per vendor and they cost 999 credits.
- Replica space suits come in boxes now, instead of the parts being bought seperately.
- All toy guns bought from the syndicate vendor are loaded with riot darts.
- No more discounts for service jobs. Everyone pays the full price.

## Why It's Good For The Game
The current vendor isn't balanced very well, the pricing is a placeholder and the vast amounts of gear in them make them a destabilizing element when it makes its way on station. Spawning a lot of high-end riot dart guns is easy, and the fact that this has 5 syndicate balloons with a value of 20 telecrystals avaliable for effectively free is simply absurd. Reining it in a little makes it easier for mappers and admins to put these machines in player-accessible spots without worrying about it derailing rounds or empowering griefers.

Additionally, this change makes this vendor play nicer with the new vending restock economy.

None of the pricing changes affect any vending machine that was mapped in off the station z-level. Lavaland syndicates will continue not to be charged for using their machine.
## Changelog
:cl:
balance: Donksoft vendors now stock slightly more items, slightly less of each item, and has increased prices across the board.
/:cl:

### CODE REVIEW

**Comment by DrAmazing343** [comment]
I mean, arguing that the riot dart guns is strong is pretty decent, but why even bring up the syndie balloon/telecrystal argument?? Is there a way to turn them BACK into 20TC? Otherwise, I guess it's whatever. Never seen much issue with the vendor to begin with.

**Comment by moocowswag** [comment]
> I mean, arguing that the riot dart guns is strong is pretty decent, but why even bring up the syndie balloon/telecrystal argument?? Is there a way to turn them BACK into 20TC? Otherwise, I guess it's whatever. Never seen much issue with the vendor to begin with.

Syndicate balloon is meant to be a luxury item that tells everyone that you are better than them.

its arguably still pretty cheap since a tot can unlock illegal tech then buy several balloons with briefcase full of cash purchases or steal from peoples ids.

**Comment by DaCoolBoss** [comment]
Moocow's got it, but to add to that I just think it cheapens the balloons when you can trivially make a bunch. The machine stocking a single balloon forces buyers to restock the vendor and pay a thousand bucks a pop whenever they want one, which is much healthier for the item's prestige. My point about them being 20TC is because these items are premium items with a premium price tag, and this vendor previously did not respect that.

But to be completely clear here: my goal isn't taking things away from the players, it's just tying this stuff closer to the economy and vending restock systems. At the end of the day multiple syndicate balloons is not a real issue and I'm not trying to solve it. My balloon changes don't even stop multiple balloons coming out of the vendor. What my changes do is make the balloons function as a mid-level credit sink, makes the donksoft vendor restocks more valuable (they're used as loot rewards but currently don't see a lot of use), and allows restockers the ability to earn significant chunks of cash for every balloon they restock.

**Comment by deathrobotpunch** [comment]
does this really warrant a balance change

**Comment by Exester509** [comment]
> does this really warrant a balance change

It's pretty minor, but it affects the availability of riot darts, which have actual combat use.

**Comment by DaCoolBoss** [comment]
> does this really warrant a balance change

I have plans for making these vendors more player-accessible. With their current pricing they end up as spam factories whenever players get their hands on them, nerfing avaliability and prices lets players still use all the fun stuff without it quickly getting out of hand and giving half the station a practically free riot-dart-c20, which is a viable stun weapon in its own right. Post nerf, if someone has a riot dart c20 or something it's because they wanted it enough to spend 400 space bucks on it, not because someone bought all 10 on a whim and left 6 on the floor.

Also I think it is genuinely more engaging and fun for the players this way. The new foam force pricing scheme divides players depending on personal wealth, with the poorest players having access to limited reloads and only the weakest weapons while players with more disposable income are able to afford the best guns, more tactical options, and more ammo - maybe even riot darts to cheat with if they can hack the machine. This inherently unfair system both increases the variety in foam force wars (since not everyone can afford the best stuff) and encourages low-tier players to either develop strategies for use when outgunned, or engage with the economy system (cargo bounties, trading with other players, crime, etc) to get better equipment. The lower number of high tier guns avaliable add to this depth, since now it's possible for a 4-man posse to hog all the LMGs if they get there first or something like that. If a gun is sold out, cargo can order vendor restocks and fill it back up - earning a percentage of the cash spent (which is now significantly higher). This is especially attractive with the bigger bulkier items being particularly expensive - someone running around with a syndicate balloon and foamforce LMG broadcasts to everyone around that restocking the machine will make a significant chunk of cash.

**Comment by ElGitificador** [comment]
as things are now it sounds like an unnecessary nerf to the donksoft which is a pretty cool vendor. maybe this would make more sense if you added it in the future pr in which you plan to make them more accessible. and i dont think being unable to enjoy the vendor because you didnt bother grind creds is really that engaging and fun

**Review by ExcessiveUseOfCobblestone — CHANGES_REQUESTED** [review]
The pricing changes I dont think stand on their own given their current accessibility. The theoretical PR that makes this change warranted needs to be on our tracker and this PR linking to it, or this change needs to be removed.

**Comment by ninjanomnom** [comment]
You don't need an issue to make balance changes though @ExcessiveUseOfCobblestone ? Not wanting those changes is fine but asking for a linked issue is very strange

**Comment by ExcessiveUseOfCobblestone** [comment]
> You don't need an issue to make balance changes though @ExcessiveUseOfCobblestone ? Not wanting those changes is fine but asking for a linked issue is very strange

asking for the PR doing that is suppose to coincide with this one else the change doesnt make sense (or to put it on that one instead), not an issue.

**Comment by DaCoolBoss** [comment]
All prices are now 50 credits / 100 credits / 100 credits across the common / contraband / premium catagories.

**Comment by ExcessiveUseOfCobblestone** [comment]
update and ping me on discord

**Comment by ExcessiveUseOfCobblestone** [comment]
the price piece im ok with reverting later if this feels bad just to clarify

**Review by ExcessiveUseOfCobblestone — APPROVED** [review]

**Pull request merged**
