### PR TITLE
[READY] Makes plasmaman helmets have visors.

### PR DESCRIPTION
**Pull request by pireamaineach**
I want to die.

## About The Pull Request

See title.

## Why It's Good For The Game

Plasmamen get the same welding protection as everyone else, that is with welding helmets, with the same trade-off and negatives. Goggles are rather hard to obtain for most roles, (provided https://github.com/tgstation/tgstation/pull/45460 is reverted, which is kind of ought to be) and plasmamen aren't able to use helmets.

Basically nullifies the concept of using this as flash protection unless used by a particularly quick-witted plasmaman, (or someone willing to always be half-blind) while still offering welding protection.

I might consider re-adding transparent helmets but only if humans wear them, as it doesn't look good on plasmamen, which is the whole point of the helmet.

## Changelog
:cl:
balance: Plasmaman helmets now have welding visors, which can't stack with their torches in the helmet and are visible.
fix: Clicking on the helmet with any item no longer tells you that someone's already drawn a face on it, you can't put infinite faces on it.
tweak: Plasmaman helmets hide masks again, the sprites are no longer transparent. Mind, the original bounty just wanted it so you could see faces through it, not for it to be transparent.
tweak:Plasmaman helmets now have special smile sprites rather than pulling from the EVA one, as the visors are different sizes.
balance: You can't eat through plasmaman helmets anymore.
/:cl:

### CODE REVIEW

**Comment by Dawson1917** [comment]
Isn't the concession of species that they aren't going to be able to do everything in the game as well as normal people without going through some effort? Plasmamen getting sore eyes if they don't go the extra mile and fetch welding goggles or welding gas masks or sunglasses seems fair enough to me. NT providing them with snowflake welding visors inside their helmets? Doesn't make sense knowing how brittle and unsuited for heavy construction work plasmamen are lore-wise.

**Comment by pireamaineach** [comment]
Gameplay > Lore

Welding goggles aren't that accesible. Plasmamen aren't more powerful because they can get the same thing 2 minutes before you.

**Comment by pireamaineach** [comment]
Plasmamen are actually incredibly useful for engineering work if you understood what you were talking about, but I suppose that's too much to ask.

**Comment by Dawson1917** [comment]
Personally I want non-human species to suck shit at particular parts of the game so they aren't just "human, but take extra damage and are rad immune". Suppose that's too much to ask.
Deal with your eyes getting sore when you want to weld a hundred objects. Not demand a snowflake welding helmet get included with your race for no reason other than "I don't like having to put in extra effort for welding immunity than humans". Non-humans can't be good at everything.

**Comment by pireamaineach** [comment]
Okay chief. Because they can weld roundstart due to it being particularly hard for them to get welding protection they are oh pee.

News flash, plasmamen do suck shit at certain parts of the game, and to reduce them to nothing but their baseline modifiers is fucking stupid.

**Comment by Darkgenerallord** [comment]
You can just get welding goggles from an autolathe.

**Comment by pireamaineach** [comment]
Good job not reading into this at all. Oranges plans on adding those to the tech webs because it's obvious powercreep on welding helmets.

**Comment by Dawson1917** [comment]
> Okay chief. Because they can weld roundstart due to it being particularly hard for them to get welding protection they are oh pee.

Never said they were OP. I said I want nonhuman races to deal with the difficulties of being a different species, not get snowflake workarounds because they don't want to deal with their species' weaknesses. 
Can't take off your envirosuit helmet? Tough luck! Looks like you'll have to go the extra mile to get the benefits various helmets and headwear can offer. Not get a free welding mask inserted into your enviro-helmet at roundstart.

**Comment by pireamaineach** [comment]
>Can't take off your helmet and thus the only accessable form of welding protection is off the table.
Oh boy tough luck guys you'll just have to suck it up along with all the other downsides that come with that no upsides allowed here bucko.

**Comment by Dawson1917** [comment]
> 
> 
> > Can't take off your helmet and thus the only accessable form of welding protection is off the table.
> > Oh boy tough luck guys you'll just have to suck it up along with all the other downsides that come with that no upsides allowed here bucko.

You have your rad immunity, disease immunity, and easy space immunity. Suck it up indeed.

**Comment by pireamaineach** [comment]
Ah yes these very circumstancial and tiny benefits yours for only:
1.5x damage modifiers 
Can't be defibbed
Barely ever gets cloned
Burns to death without suit.
Needs constant internals.

What a steal.

**Comment by pireamaineach** [comment]
It's very easy to cite only downsides or only upsides, problem is it doesn't hold up under scrutiny.

**Comment by Dawson1917** [comment]
It's almost like nonhuman species are meant to be inferior to humans by intention!
Not having welding immunity is not as much a debilitating downside as you make it out to be. You can weld a few things with 0 protection and be fine, or in the worst case get shortsightedness. Eye damage can be fixed by wearing prescription glasses (whole box sitting in medbay) because they passively heal eye damage. It's a minor downside that you just have to deal with or work around as a plasmaman by fetching a welding gas mask, goggles, or sunglasses.

**Comment by Michael-Ashfield** [comment]
I think it is important to note that weakness to welding for plasma man only ever became a species weakness about a week ago. This PR seems to be a compromise between those who found it bad that plasmamen were flash immune and those who want plasmamen to be more flash vulnerable than other species (Only very slightly more immune than moths).

**Comment by pireamaineach** [comment]
This doesn't make plasmamen better than humans, or even close the same league as them. It's QoL that saves you having to having to wait for science to develop welding gas masks just so you can weld shit. Goggles are finnicky to get to due how limited they are. 
If this is so minor, why do you care so much? Welding protection on a toggle is a pretty fair buff to a helmet that is permanently attached to them. 
"bu bu bu bu bu my hard mode race"

**Comment by pireamaineach** [comment]
Moths were actually more immune than plasmamen. Since they couldn't be flashed period.

**Comment by pireamaineach** [comment]
People wanted the intrinsic plasmaman protection from flashing replaced with visors, but the original P.R. just removed the protection all together because they were allowed to, and thus I had to.

**Comment by Dawson1917** [comment]
Lacking the QoL features humans can easily acquire is intentional for nonhumans. With a helmet permanently sitting on your head, you lose out on being able to pick and choose headwear like humans or most other races. That's intentional. Welding helmets fall under one of the things you lose out on, making plasmamen less suited for welding than other races (except moths who need even more protection) unless they work around the problem by getting their hands on protective eyewear like welding goggles or protective facewear like welding gas masks.

Moths being flash immune was a bug due to nobody giving them proper eyes. They're intended to need two layers of protection (welding mask + sunglasses) if they want to weld.

>"bu bu bu bu bu my hard mode race"
I never said this. I don't think plasmamen need to be ""the challenge race"" like some people. I think every nonhuman species needs to have very real disadvantages, downsides and advantages so they aren't the godawful "human, but different sprite" we can see in moths, ethereals and felinids. Plasmamen having many restrictions is one of the main reasons I think they're the only good nonhuman race available.

**Comment by pireamaineach** [comment]
They have many restrictions, why does something as basic and necessary for station life as welding need to be one? This is the reason plasmamen had protection in the first place, hell they've had welding visors on /vg/ for years now.

**Comment by Dawson1917** [comment]
The most urgent things you need to do welding for (welding vents/scrubbers in your workplace during a flood, unwelding a door, welding down a wall) can be done without protection without walking away blind. Bigger tasks like being the one guy welding every vent on the station during a xeno infestation will need protection you have to work for.
Given your other PR is going to add welding goggles to RnD I think that's an adequate workaround for plasmamen who need mass welding protection

**Comment by pireamaineach** [comment]
First of all, isn't not, second, need RnD's help to do something as basic as welding isn't a good species limitation. It's not fun, it's just annoying and tedious when it doesn't have to be

**Comment by ATH1909** [comment]
Having a weakness to flashes/vulnerability to eye damage from welding is already one of the major downsides of moths; we don't need to give a SECOND race the "they get screwed over by bright stuff" vulnerability. Also, the removal of flash protection on plasmaman helmets was an awful decision, and this PR attempts to lessen the impact of that PR a bit. Also also, this is more of a QoL improvement than anything.

In short, I fully support this PR.

**Comment by granpawalton** [comment]
>Be me, atmos tech who doesnt role on any antag because I just want to play around with that aspect of the game and will often suicide when disrupting things like war ops happen

Plasma man is already so weak! Make my engineering race even better at engineering, we deserve this buff!

**Comment by MacBlaze1** [comment]
I support this PR, because this is the actual solution that the maintainers wanted to this problem, and now we can actually implement it.

**Comment by actioninja** [comment]
conflict

**Comment by pireamaineach** [comment]
Oh fucking brilliant. I literally can't fix this shit until Friday.

**Comment by pireamaineach** [comment]
What fucking changed in the plasmaman.dm, anyway?

**Comment by pireamaineach** [comment]
Okay someone directly merged their changes to the helmet into master while my PR was still up FUCKING

**Comment by ExcessiveUseOfCobblestone** [comment]
Revert the goggle change then add a plasmaman helmet with welding capabilities in the same node as the welding gas mask.

That way you have to opt into the """free""" welding protection rather than having it with you from the getgo.

**Comment by pireamaineach** [comment]
So your basic take-away of this P.R. is "don't do this P.R."

What's the problem with having it from the get-go?

**Comment by ExcessiveUseOfCobblestone** [comment]
The issue is that it needlessly gives people who have no need to use X the ability to use X in a game where supply/demand on top of preparation plays a key role in situations. The roles that NEED welding protection both have welding goggles Pre-Autolathe PR.

You can have a helmet for plasmamen that has a welding visor, but it shouldn't be roundstart. If being roundstart and having welding protection built into the helmet are inseparable to you, then yes the response from me would be to "don't do this PR".

**Comment by pireamaineach** [comment]
Except the fact is that we've presented reasons why they should. It's unreasonably difficult for plasmamen to access welding protection relative to the rest of the station, and so they're given a helmet that emulates the LOWEST FORM of welding protection available. It being unreasonably difficult to find welding protection isn't a good species mechanic, nobody really wants it, this was the solution oranges wanted to begin with.

**Comment by ExcessiveUseOfCobblestone** [comment]
"They suck so much already" isn't a valid rationale.

Replace the goggles with the plasmaman helmet /w visor, thereby reverting the goggles PR. That way they are literally just like humans in that regard without any techweb binding.

**Comment by pireamaineach** [comment]
The goggles PR is already long reverted mate.

**Comment by pireamaineach** [comment]
Plus that's obvious powercreep on welding helmets.

**Comment by ExcessiveUseOfCobblestone** [comment]
Sorry just back from vacay and the only PR about it in my notifs was closed.

**Comment by pireamaineach** [comment]
I think oranges did that one himself actually.

**Comment by ExcessiveUseOfCobblestone** [comment]
How is that powercreep at all? We're not buffing something to compete with welding helmets?

**Comment by pireamaineach** [comment]
The helmet is space-proof, reminder. If the helmet is printable the powercreep is obvious.

**Comment by pireamaineach** [comment]
The helmets need to be conditioned to only be accessible through cargo or by spawning as a plasmaman.

**Comment by pireamaineach** [comment]
Also how is this free protection?

**Comment by ExcessiveUseOfCobblestone** [comment]
How about a recipe to craft them that requires the helmet then? Not really a fan of that design concept that the plasmamen are trash but their default gear is so good that it's powercreep to implement variants of it through our normal channels.

Free meaning you get it without having to go out of your way. Protection in both welding and other benefits from using a welding mask such as flash protection.

**Comment by pireamaineach** [comment]
This effective does nothing for most stationers in the realm of flash protection. That's like arguing a welding helmet is flash protection. The fact of the matter is, the vision debuff is going to prevent 99% of people from using it for that.

Plasmamen's default gear is effectively all they have, as they have much less freedom in equipment choice than humans. This's effectively giving them tier 1 human gear for free but they can't as easily upgrade.

**Comment by pireamaineach** [comment]
Plasmamen's default gear is good, used to be fairly good, now it's just, "eh, I guess it's good, space-proof and welding visor." Problem is anyone who can access a suit can access a helmet, so the space-protection winds up being a wash, and the welding visor is easily achievable for any stationer via a quick trip to cargo.

**Comment by ExcessiveUseOfCobblestone** [comment]
A welding helmet IS flash protection though? It is only not used as frequently due to the overabundant availability of sunglasses since those don't burden at all (which I think is an issue as well but OOS).

You just turn it on when you see the flash and run then turn it off when you're a safe distance (or kill them). It's not like there's a delay or punishment if you toggle it as-desired.

> Plasmamen's default gear is effectively all they have, as they have much less freedom in equipment choice than humans. This's effectively giving them tier 1 human gear for free but they can't as easily upgrade.

While the burden is intended, the lack of upgradability in their attire is simply because no one has coded it yet. I don't think the lack of upgradable gear "tiers" is justification to putting upgrades on their "base" gear.

> Problem is anyone who can access a suit can access a helmet, so the space-protection winds up being a wash

Yeah dis is icky. Preferably it would work/be fluffed as a "special material" that protects against normal atmosphere but not vacuum although that's OOS.

I don't think i'm going to be sold on the whole roundstart thing. I don't care how you'd like to approach it but having it as a default for all roles is not something I'm going to merge.

**Comment by pireamaineach** [comment]
>Literally bound to the suit, can't even use the helmet outside without a EVA suit anyway. "Eeeeeh nerf it anyway."

Having upgrade teirs for plasmamen would be fluff for a minority race anyway. The way it works now is fine, the way it worked before was fine, this will actually be good.

**Comment by pireamaineach** [comment]
@actioninja Fixed merge conflicts.

**Comment by pireamaineach** [comment]
Let me uh. actually make it work, one second

**Comment by pireamaineach** [comment]
Weird. It works fine when I compile it.

**Pull request merged**
