### PR TITLE
Makes the Syndibase look more evil, except i didnt forget mapmerger this time.

### PR DESCRIPTION
**Pull request by AarontheIdiot**
## About The Pull Request

 This replaces the boring riveted walls and regular windows in the Syndicate nuke ops base with intimidating Plastitanium windows and walls that are also indestructible. And I actually used MapMerger this time.

Screencap: https://imgur.com/a/ZUw8euT

## Why It's Good For The Game

 Makes the Syndibase feel more evil.

## Changelog
:cl:
tweak: Changed the Syndibase walls to look more evil.
/:cl:

### CODE REVIEW

**Comment by nemvar** [comment]
Put an extra layer of unbreakable walls around everything that leads to space, otherwise nukies can get to centcomm.

**Comment by AarontheIdiot** [comment]
> Put an extra layer of unbreakable walls around everything that leads to space, otherwise nukies can get to centcomm.

The plastitanium walls here are indestructible.

**Comment by nemvar** [comment]
Oh alright

**Comment by Tlaltecuhtli** [comment]
is the multi wall area next to the bathroom where fluke ops get buried alive

**Pull request merged**
