### PR TITLE
Red Beanie Description updated

### PR DESCRIPTION
**Pull request by Tacolizard**
:cl: NanoTrasen "Hip and With-It" Department
add: red beanie meme
/:cl:

### CODE REVIEW

**Comment by Niknakflak** [comment]
As the person who added this
I dont understand the reference so :-1:

**Comment by TechnoAlchemisto** [comment]
Shitty reference.

**Comment by Cheridan** [comment]
Sorry this meme isn't up to par with our established meme standards

**Comment by Iamgoofball** [comment]
That's illegal you know

**Pull request closed without merging**
