### PR TITLE
Electronic assembly changes and additions

### PR DESCRIPTION
**Pull request by JStheguy**
[Changelogs]:
:cl: JStheguy
add: Electronic assemblies can now have their casings colored using the new assembly detailer, get yours at your nearest integrated circuit printer!
add: Added 2 new electronic assemblies, 2 new electronic mechanisms, and 3 new electronic drones.
add: Added wall-mounted electronic assemblies in 3 sizes, simply slap it against a wall to stick it up, and then anchor it in place with a wrench.
imageadd: Added the new sprites for the new assemblies, and color-able overlays for every assembly, to allow for the aforementioned coloring feature.
tweak: Scanners can now scan power cells, circuitry tools, and integrated circuits, assuming the player isn't able to use them normally. I.E. if the assembly is closed.
tweak: Using wrenches to anchor down assemblies now works for all assembly types except drones, as opposed to just working for electronic machines.
tweak: Examining an assembly now shows some text telling you what tools to use to do what, like many other objects currently do.
/:cl:

[why]: Not being able to scan things like power cells was kind of a bother, being able to color assemblies seems like a nice little customization feature to have, nothing wrong with having some more options for how assemblies can look, and anchoring only being a thing you can do with electronic machines was arbitrary.

image
The new assemblies.

image
Every assembly (except the type-a drone and wall-mounted assemblies) with some color.

image
The 16 colors that can be chosen from the assembly detailer.

### CODE REVIEW

**Comment by arsserpentarium** [comment]
Wow.
Please, make inhand sprites for all these luxury.
Really needed.

**Comment by GunHog** [comment]
:+1: @Not-Cat-Slime (Xhuis)

These are stunning additions. I might have to come back to playing Scientist, if only for the circuits! The humanoid one I had mistook for you adding circuit armor! Still, they look amazing!

**Review by WJohn — APPROVED** [review]

**Comment by arsserpentarium** [comment]
I want to say thanks to you for your decent work. Your sprites are very beautiful.

**Comment by francinum** [comment]
As much as I find circuits a bad feature, these sprites are really nice.

**Comment by AverageJoe82** [comment]
Your sprites are the greatest man, also maintainers pls speed merge because I need to PR something that uses this before the feature freeze

**Comment by arsserpentarium** [comment]
At attempt to recucle assembly, automatic components removal doesn't work.However, you can recycle empty assembly.

**Comment by JStheguy** [comment]
Well, I've been playing with circuits a lot on the server, where this PRs been testmerged, and it seems to be working entirely fine for me, and I just ran a quick test on my local download of my branch and it works just as fine there too.
Can you give any other information about what was happening when you encountered this issue?

**Comment by arsserpentarium** [comment]
I've printed needed scheme twice.So I've tryed to recycle excess assebly.
It started recyce.And beginned removing components. But actually no components was removed.
Then I tryed again with same effect.
After I manually removed all of them, it properly recycled empty shell.

**Comment by JStheguy** [comment]
I'll be honest, I can't replicate the problem locally.

**Comment by arsserpentarium** [comment]
Okay.maybe problem with something else.

**Pull request merged**
