### PR TITLE
Spin and flip emotes in IC tab

### PR DESCRIPTION
**Pull request by carlarctg**
## About The Pull Request

you can now spin and flip without accelerating your carpal tunnel

## Why It's Good For The Game

less annoying to spin and flip

## Changelog
:cl:
add: *spin and *flip are now available in the IC tab.
/:cl:

### CODE REVIEW

**Comment by Dawson1917** [comment]
Tabs are already quite bloated, IC tab especially. Emotes really don't need to be piled on as well. 
Also, the higher the number of commands in a tab, the more it lags out your client, and this is VERY noticeable on tabs like Admin, which is only around 2-3x the size of IC. You can ctrl-V if you're really intent on doing an emote ten times a second.

**Comment by Akrilla** [comment]
time to see people walking down the corridor spamming the flip button

**Comment by carlarctg** [comment]
IC tab isn't really bloated? If your performance is an issue just switch to the objects tab since it has like 4 verbs.

**Comment by Cyprex** [comment]
This really doesn't need to be in the IC tab.

**Comment by Electronics** [comment]
You can also Ctrl+Up to select stuff from your command history if you want to spam it

**Comment by Shapsy** [comment]
Powercreep

**Comment by ExcessiveUseOfCobblestone** [comment]
verbs r bad

**Comment by carlarctg** [comment]
ctrl-up is clunky and annoying to use

**Comment by PKPenguin321** [comment]
@Electronics hotkey mode plebs dont know this feel

**Comment by optimumtact** [comment]
no more verbs please

**Pull request closed without merging**
