### PR TITLE
Ratvarian Spears will stun any targets they're thrown at

### PR DESCRIPTION
**Pull request by ChangelingRain**
:cl: Joan
tweak: Ratvarian Spears will now stun any mob they're thrown at instead of just enemy cultists and silicons, though the stun is still longer on enemy cultists and silicons.
/:cl:

Spears are better to throw = more spears thrown = higher spear turnover(#19826) is more useful

### CODE REVIEW

**Comment by anconfuzedrock** [comment]
yea ratvar sucks right guys its not like he has infinite antag drones or anything you know what ratvar needs ratvar needs to be the only thing that can stun shit thats not a human or borg

**Comment by KorPhaeron** [comment]
>40 damage and a stun

:tada:

**Comment by ChangelingRain** [comment]
Cogscarabs can't throw spears also you're kind of sounding incoherent there

**Comment by anconfuzedrock** [comment]
oh no my weapon is gone and the target is stunned so I can easily kill them now what ever will I doooooooooo (finish them off)

**Comment by ChangelingRain** [comment]
Cogscarabs can't ventcrawl.
Do you actually know anything about the gamemode or are you just opposing my changes on principle?

**Comment by AdamElTablawy** [comment]
They can't ventcrawl and raid the armory. 

Also, thrown stuns are bad because throws are so fucking fast it's impossible to dodge-hence why people don't like thrownbatons.

Might want to either nerf the damage or lower the stun, because while ONE weapon might be gone you're probably carrying a lot of weapons to kill the guy with if you're actually using the spear.
@anconfusedrock

Make sure you know what you're talking about before you start complaining.

**Comment by ChangelingRain** [comment]
The stun is now no longer enough to cuff on its own.

**Comment by anconfuzedrock** [comment]
I swear they could ventcrawl but they still hella op for something you can make infinitely

**Comment by ChangelingRain** [comment]
They're literally worse than humans combatwise; 50 health, can be stunned, can't wear armor, can be hit by projectiles, cannot even potentially swap places with an enemy.
The only thing they're better at is A: disabler immunity and B: doesn't slow down until you kill it

**Comment by PKPenguin321** [comment]
And C: Microscopic impossible to click sprite that moves at sanic speeds at all times

**Comment by anconfuzedrock** [comment]
how the fuck can they be literally worse they are small and gas and shit dont work and they spaceproof while fast as fuck I have had one take on the entire space hotel once AND WIN

**Comment by ChangelingRain** [comment]
See list of reasons they're worse in direct combat that I just posted????

**Comment by PKPenguin321** [comment]
they are actually really good because they are fast and almost impossible to hit

**Comment by Kromgar** [comment]
They are fast and you have to fucking click theiry tiny ass sprite.

Not to mention they can use ther proseltyizers to break into armory via space by changing the doors through escape pod to armory

**Comment by Bawhoppen** [comment]
Joan, nobody would have clicked on this PR if you had just named it differently, Using the word "Stun" in any PR title automatically leads to autistic hugbox cucks coming and thumbs-downing it

**Comment by ChangelingRain** [comment]
All the discussion isn't even about the spear it's about the cogscarabs

**Comment by Bawhoppen** [comment]
they wouldnt have clicked on the PR in the firstplace though

**Pull request merged**
