### PR TITLE
Trashbag can pick up ammo casings and reagent_containers/food/drinks again.

### LINKED ISSUE #12110: Can't pick up bullet casings with rubbish bag
Also goes for other items of trash in certain conditions too. For example I encountered a couple of ramen cups by themselves and they wouldn't pick up until I moved them onto a pile of trash and picked up the whole pile.

This was with the janiborg's rubbish bag, by the way, if it makes a difference.

### PR DESCRIPTION
**Pull request by phil235**
Fixes #12110 
- Dipping a lit cigarette into a reagent container heats up the liquid (like every other heat sources) and only unlit cigarette can be dipped to absorb the liquids now.

### CODE REVIEW

**Comment by Lumipharon** [comment]
Pretty sure putting a cigarette in a beaker of liquid is just going to extinguish it yo.

**Comment by Shapsy** [comment]
Well not if it's flammable

Would probably be better to say that instead of dipping it in the reagent, you heat the bottom of the beaker

**Comment by Lumipharon** [comment]
Even then, although I can't figure out exactly by looking at the pr in the code, the heat gain would have to be TINY, even compared to a lighter.

Stick your hand over a lit cigarette vs a zippo. You'll barely (if at all) feel the cigarette.

**Comment by phil235** [comment]
I can easily lower the value that cigarettes return with is_hot() so it's less than a zippo.

**Comment by Wyzack** [comment]
We are one step closer to assistants heating crank on a spoon with a lighter in a dark maint tunnel

+1

**Pull request merged**
