### PR TITLE
Fixes #55112 - Swapping items no longer eats things

### LINKED ISSUE #55112: swapping items is eating things
Issue reported from  Round ID: [150800](https://scrubby.melonmesa.com/round/150800) (/tg/Station Manuel [ENGLISH] [US-WEST] [ROLEPLAY] [99% LAG FREE])

Reporting client version: 513.1528

when I use the Equipment Swap command/hotkey, the original item disappears. this could prove disastrous for certain things where important items are lost unintentionally

### PR DESCRIPTION
**Pull request by Mothblocks**
## About The Pull Request
i was right the first time

## Changelog
:cl:
fix: Quick swapping items no longer deletes them.
/:cl:

### CODE REVIEW

**Comment by optimumtact** [comment]
this is shit code

**Comment by Jared-Fogle** [comment]
yeah

**Review by LemonInTheDark — DISMISSED** [review]
lol

**Comment by Jared-Fogle** [comment]
DNM - It's being test merged right now, but it means that when you quick swap a jumpsuit it drops all your stuff. I'm going to fix this.

**Comment by joybod** [comment]
yay, i reported a bug and it got fixed

**Comment by Pugie** [comment]
Just remove it this 'feature' is a bug, a germ, a DISEASE.

**Comment by Jared-Fogle** [comment]
if someone finds another bug with quick swap you won't find me defending against that

**Pull request merged**
