### PR TITLE
Spiderpalooza 2: Queen Powers! (Very very WIPPY!)

### PR DESCRIPTION
**Pull request by ghost**
Adds viewing through the eyes of your other spiders, and this one might be controversial so I cut it out of the original PR but remotely executing spiders that won't listen to you. Hoo boy!

### CODE REVIEW

**Comment by Armhulen** [comment]
ALSO: focusing on the food pr first so this might sit for a tiny bit

**Comment by AnonymousNow** [comment]
Seems fun, though I'm not sure about the remote execution power. Might be useful if xenobiology breeds a queen and one of her offspring starts attacking the crew?

**Comment by GunHog** [comment]
Close this, then work on it more when you finish the first. Also, I would like to jack your spider queen code for Xenos.

**Comment by AnonymousNow** [comment]
Remotely executing xenos is even better, since suddenly people are discouraged from murderboning for the sake of murderboning and instead encouraged to bring live specimens back to the nest for breeding.

**Comment by GunHog** [comment]
I was more interested in the 'remote viewing' feature

**Comment by AnonymousNow** [comment]
Also cool.

**Comment by WJohn** [comment]
Huge improvement over the sprites we have now. Good stuff.

**Comment by Armhulen** [comment]
good idea, spiderpalooza 2 will return!

**Comment by FantasticFwoosh** [comment]
Makes you wonder whether a xenobiologist might attempt a transference potion swap with a queen in order to gain this power.

**Pull request closed without merging**
