### PR TITLE
Fixes decals causing 20k runtimes and blood not cleaning

### PR DESCRIPTION
**Pull request by TiviPlus**
## About The Pull Request

decals will unregister signals and wont try to clean twice
## Why It's Good For The Game

Runtimes and bugs are bad

## Changelog
:cl:
fix: Fixes decals causing 20k runtimes and blood not cleaning
/:cl:

### CODE REVIEW

**Comment by bobbahbrown** [comment]
can you briefly explain why you had to make this change

**Comment by LemonInTheDark** [comment]
Please update your pr body and title to match our contribution guidelines, describe your pr and the information around it in full.

**Comment by optimumtact** [comment]
Please consider this a friendly warning, your PR's must have a properly descriptive title and body content that explains the purpose of the PR.

Your current title and or body content does not meet requirements, so please update it.

**Comment by optimumtact** [comment]
I'm gonna give you 24 more hours to explain what you're actually doing and then I'm going to send you and this PR to the shadow realm.

**Review by Timberpoes — CHANGES_REQUESTED** [review]
You're not Dennok and even Dennok is no longer allowed to do what Dennok does.

Please address the above concerns.

**Review by Timberpoes — APPROVED** [review]

**Comment by cacogen** [comment]
dennok has no need of the human language

**Pull request merged**
