### PR TITLE
Adds small lavaland ruin

### PR DESCRIPTION
**Pull request by AnturK**
dreamseeker_2018-07-23_14-34-58

Can you solve this ancient mystery ? (Probably but let's keep it suspenseful)

Could use some improvements and scaling up but should work as is. Also better puzzle and border sprites.

### CODE REVIEW

**Comment by Supermichael777** [comment]
totally wont end badly

**Comment by Bluespace** [comment]
Loot seems meh. Swap the soulstone for an eye of god, and the immortality talisman for the teleport cubes.

**Comment by WJohn** [comment]
i mean. the face that it's tiny and an obvious circle we see elsewhere makes this a really simple puzzle.

**Comment by AnturK** [comment]
We don't have a lot 96x96 icons so i simply picked one that's recognizable.

**Comment by MrDoomBringer** [comment]
i might be dumb but it looks like `!unwanted` references the _wrong_ tile. Why is that?

**Comment by AnturK** [comment]
Bleh, i forgot to change variable name after i made the empty and normal tile check in same loop. Will fix.

**Comment by Repukan** [comment]
Loot is fine, you don't need to add the super tier of loot to a ruin that has no inherent lethal danger for the person interacting with it.

**Comment by AnturK** [comment]
Well that was fast, wanted to get some feedback in but i guess it's okay.

**Pull request merged**
