### PR TITLE
non-easter rabbits can lay eggs again

### PR DESCRIPTION
**Pull request by ATH1909**
## About The Pull Request

Restores the Easter egg of all rabbits being able to lay Easter eggs if fed (instead of just Easter rabbits), which was unintentionally removed by a rabbit refactor.

Note that non-Easter rabbits will start with no eggs loaded, so they won't lay any unless they're fed.

Easter rabbits no longer start with more eggs in them than their normal egg capacity should allow.

## Why It's Good For The Game

Rabbits being able to lay eggs when fed was an explicitly intentional feature (https://github.com/tgstation/tgstation/pull/57597) added by me around two years ago. It was unintentionally removed by san7890 in his rabbit refactor because he assumed it was just sloppy coding.

image

I don't _think_ this PR violates the freeze?

## Changelog

:cl: ATHATH
fix: An Easter egg related to, well, Easter eggs has been returned.
fix: Easter rabbits no longer start with more eggs than their standard egg capacity.
/:cl:

### CODE REVIEW

**Comment by san7890** [comment]
i still really don't like this change

**Comment by san7890** [comment]
I've thought on it a bit more and even though it was explicitly added and inadvertently removed (by myself)- I still do not think it is a good idea for either the direction or style of this game. Rabbits in real life do not lay eggs, why should completely average rabbits (that don't have egg baskets baked into their sprites) be able to shit out eggs after you feed them carrots?

Easter rabbits laying eggs is something I can cope with at the end of the day because it's a silly thing for a holiday, but I really do not like the idea of any run of the mill rabbit just being fed to lay eggs. It doesn't make any logical or intuitive sense (reliance on an understanding of a _very obscure_ game mechanic, literally only you were the only one who noticed), and it just simply doesn't really fit into the Retro Sci-Fi theme of the game- it is complete fantasy 24/7/365.

I've already discussed this with you (around the time of the screenshot you posted in your PR Body), and I think that even though it was not documented, a failing on my part, it was simply because the notion of a normal rabbit didn't exist- they were all inherently easter. As per the changelog of that refactor:

```txt
add: The species of Rabbits signed a declaration saying that they no longer wanted to be a part of Easter. After a long four-year separatist movement and a lot of bloodshed, they aren't!
```

I don't want to go back there, I want normal rabbits that behave in normal rabbit ways that aren't always made to be gamified to get cool egg loot. I intend on closing this after 24 hours unless any other maintainer feels that they have any other strong objections to anything I've outlined here.

**Comment by Mothblocks** [comment]
brother just say you dont like it and close it

**Comment by Mothblocks** [comment]
pov: you are athath and you made a pull request

image

**Comment by ATH1909** [comment]
> I've thought on it a bit more and even though it was explicitly added and inadvertently removed (by myself)- I still do not think it is a good idea for either the direction or style of this game. Rabbits in real life do not lay eggs, why should completely average rabbits (that don't have egg baskets baked into their sprites) be able to shit out eggs after you feed them carrots?

I don't think the "X doesn't do this in real life" argument works here. Chickens don't lay a dozen eggs in 30 minutes in real life. Bees aren't immune to the vacuum of space in real life. Plushies don't conjure a baby plushie if you smack them together enough in real life. Rabbits don't pop out of hats if you tap them with a wand in real life.

And who's to say these are normal rabbits? IIRC, lore-wise, several of our animal species are genetically-altered descendants of their real life counterparts.

> Easter rabbits laying eggs is something I can cope with at the end of the day because it's a silly thing for a holiday, but I really do not like the idea of any run of the mill rabbit just being fed to lay eggs. It doesn't make any logical or intuitive sense (reliance on an understanding of a _very obscure_ game mechanic, literally only you were the only one who noticed), and it just simply doesn't really fit into the Retro Sci-Fi theme of the game- it is complete fantasy 24/7/365.

IDK, I think someone at some point in the future will try to feed a rabbit a carrot and be pleasantly surprised. I think the reason it hasn't been naturally encountered much yet is because rabbits themselves are pretty rare.

And yeah, nobody's going to report that rabbits can't be fed carrots if they don't know that there's supposed to be a special rabbit-carrot interaction. It'd be like making a bug report for being unable to feed ants sugar.

> I've already discussed this with you (around the time of the screenshot you posted in your PR Body), 

Did we? I couldn't find much in the discord logs after that screenshot.

> and I think that even though this specific aspect of the feature/refactor was not outlined in the PR- it was simply because the notion of a normal rabbit didn't exist- they were all inherently easter. As per the changelog of that refactor:
> 
> > add: The species of Rabbits signed a declaration saying that they no longer wanted to be a part of Easter. After a long four-year separatist movement and a lot of bloodshed, they aren't!

They're still not Easter rabbits, which lay eggs without being prompted and say special Easter lines. I think they're distinct enough.

> I don't want to go back there, I want normal rabbits that behave in normal rabbit ways that aren't always made to be gamified to get cool egg loot.

I just thought that mass-producing carrots for rabbits would be a neat little side project for some botanists to do, sort of like bees or grinding Mediborg's Amputation Adventure with ligament hooks.

**Comment by san7890** [comment]
> Did we? I couldn't find much in the discord logs after that screenshot.

image

also your argument that "since some aspects of the game are silly, everything should be skewed towards silly" is flawed in that most of those aspects are bugs/consistency issues waiting to be fixed. plushies are plushies they can do whatever they want because they are not bound to the same rules as biological organisms (of which exist in real life in our time). as far as doing top hat stuff, just because something is a fun interaction that can happen sometimes based on a popular conception of magicians (as well as having the rabbit having the potential to make fun of the played-out trope) is much more different than being able to cheese your ways to popping out chocolate eggs. i agree that it's quite interesting to teach and learn about, but i wholesale reject the concept that every rabbit in 500 years has a fucking egg sac

**Comment by moocowswag** [comment]
After seeing the clown car deer pr i think any arguements that something is weird, illogical or unintuitive or too silly for the game are irrelevant.

**Comment by Mothblocks** [comment]
this is way too niche and useless to be a station quirk. should either be a feature (even just on easter is ok) or shouldnt be.

**Comment by moocowswag** [comment]
What about in the future adding this to dna splices to genetics so you can splice animals together like giving a rabbit chicken dna.

**Pull request closed without merging**
