### PR TITLE
Fixes Police/Classic Baton Mob Sprites

### PR DESCRIPTION
**Pull request by Steelpoint**
Fixes the sprites for the baton to be consistent on all sides and angles.

screenshot 2016-05-31 15 01 42

Fixes https://github.com/tgstation/tgstation/issues/16309

### CODE REVIEW

**Comment by swankcookie** [comment]
can someone explain to me why this even exists?

**Comment by Steelpoint** [comment]
What? The Police Baton?

Its essentially a Stun Baton without the need to recharge, and is a loot item from the Derelict.

**Comment by swankcookie** [comment]
I know that we, as a community, have essentially given up any pretense of making sure objects fit into the reasonable scope of the timeline and bio of the station, but this one just makes no sense to me for some reason. Why does the detective, who starts mere feet from the brig, start with a wooden stick instead of the highly upgraded stun baton. Thematically, it makes a little sense, but realistically, it's kinda bonkers.

**Comment by Steelpoint** [comment]
I'm pretty sure the Detective uses a Stun Baton as well.

The Police Baton is a straight upgrade.

**Comment by ChangelingRain** [comment]
Avoid inhand conflicts!

**Comment by Steelpoint** [comment]
That was a very quick merge, seven hours.

**Comment by PKPenguin321** [comment]
This also fixed https://github.com/tgstation/tgstation/issues/14844

**Comment by LanCartwright** [comment]
honestly I'm not an entire fan of this because it is technically a tonfa and holding it in quirky ways isn't unreasonable.

**Pull request merged**
