### PR TITLE
Resprites Generic Jumpsuits to 3.0 Style

### PR DESCRIPTION
**Pull request by Imaginos16**
## About The Pull Request
Jumpsuits were last updated in 2017, by the beloved Dannno, back when he did PRs. His philosophy was to introduce a consistent palette for /tg/ back in the day!

This time, however, I will introduce you to the 3.0 style of Jumpsuits, lovingly called "The Jumpsuit of All Time"!
image

What's even the philosophy behind this besides looking extremely lovely? Glad you asked!
Some of the more observant of you may have noticed that the recent resprites, primarily from security and medical, utilize this jumpsuit as a base! This is by design, since this jumpsuit is meant to be used as a springboard to create and update older jumpsuits into not only a more consistent, but also an extremely elegant style that will make you proud to wear the attire wherever you go!

Here is the 3.0 jumpsuit in different colors, rainbow and the prisoner variant:

image

For a quick Q/A:

"What will happen to Dannno's 2.0 style?" - It'll live on in some cosmetics, primarily the hydroponics jumpsuits that were done by Kryson, but they will otherwise be replaced.

"What about the Ancient Jumpsuit?" - To keep into the theme of what it is supposed to be, the oldest version of the assistant's grey, it will not be changed and retain its old, 1.0 Goon Era aesthetic.

## Why It's Good For The Game
This PR will truly mark the beginning of the update in style for clothing and attire in /tg/station and hopefully improve the aesthetic quality of our codebase!

## Changelog

:cl: PositiveEntropy
imageadd: Nanotrasen has now officially updated all generic jumpsuits and the prisoner one, marking the third rendition of jumpsuit styles being added into station!
/:cl:

### CODE REVIEW

**Comment by realthomas69** [comment]
very nice!

**Comment by GoldenAlpharex** [comment]
jmpsiut

**Comment by MrDoomBringer** [comment]
i hate to see it change 
but its a good change

**Comment by cacogen** [comment]
Why is there never a comparison to the sprites being changed? IconDiffBot is too small.

**Comment by Serxule** [comment]
yeah can we get a comparison? not sure what the old ones look like

**Comment by MrDoomBringer** [comment]
as someone with >2000 hours in assistant the above two comments sadden me deeply

**Comment by KathrinBailey** [comment]
image
This line looks really jarring, with the female fitting it kinda looks like moobs/man chest.
Might just be me, though?

**Comment by Imaginos16** [comment]
> image This line looks really jarring, with the female fitting it kinda looks like moobs/man chest. Might just be me, though?

That's just how jumpsuits are. There are talks for a female form fitting at some later point to better this issue.

**Comment by cacogen** [comment]
Is it so much to ask for a full-size comparison to the old one so we can clearly see which is better? Every sprite change should be required to do this, instead of trying to sneak the changes past people.

**Comment by KathrinBailey** [comment]
> That's just how jumpsuits are. There are talks for a female form fitting at some later point to better this issue, but its otherwise not relevant.

Maybe I wasn't clear enough, my gripe was with what the yellow paint.exe line was highlighting.
It looks like some attempt at shading under the armpit mixed in with an attempt of showing a pocket for one's pens and pencils.
It goes too far towards the front of the chest to look like the shading option.
It goes way too far under the armpit to look like a pocket.

I haven't ever seen or heard of any jumpsuits, both the work kind and the women's fashion kind, that have any sort of weird fabric folds for mobility or anything of the sorts like it.

Again, might just be me, but if that is indeed a shadow, it sticks out a lot and looks a little weird. Especially on the jumpskirts. Other than that, it's all fine.

**Pull request merged**
