### PR TITLE
Meta service area overhaul, botany revival

### PR DESCRIPTION
**Pull request by nightred**
## About The Pull Request

This is a new service area for meta that works at improving many things.
* Kitchen and cold room access
* Botany has space and style
* Bar back is now connected to bar
* Included moved tcomms
* Engineering lobby and Atmospherics areas have had improvements to make room for the expanded service area.
* Service hall is now connected to maintenance hall with a mini break room.

Pics!
image

## Why It's Good For The Game

Improved flow of the department

## Changelog
:cl:
tweak: Meta service overhaul the great botany.
/:cl:

### CODE REVIEW

**Comment by Cartographer-D** [comment]
I like this layout a lot. Good changes, expands on what I did in my last PR and just does it much better.

Two things I noticed:
You should make the engineering lobby door line up with the rest of the hallway (Move it one tile up)
You should flip that windoor in the freezer as right now the window retracts into empty space.

**Comment by nightred** [comment]
> You should make the engineering lobby door line up with the rest of the hallway (Move it one tile up)
> You should flip that windoor in the freezer as right now the window retracts into empty space.

Touched both items up

**Comment by carshalash** [comment]
I have my own bar again. Love it.

**Comment by wesoda25** [comment]
Ok but can we have old bar back

**Comment by nightred** [comment]
> Ok but can we have old bar back

Old bar back would kill bar front and move half the stuff to the back, walking space it is better here is a tweaked layout.

**Comment by Helianthus00** [comment]
These scrubbers/vents are missing pipes.
missing pipes
The areas seem inconsistent here. 
area inconsistencies
 Great work overall though, I like it a lot.

**Comment by nightred** [comment]
> These scrubbers/vents are missing pipes.
> The areas seem inconsistent here.
> There is a wall under this door

Fixed up all three points

**Comment by Tlaltecuhtli** [comment]
do mulebots work?

**Comment by nightred** [comment]
> do mulebots work?
> 
> the scrubber/pumps near the tcomm storage have wrong decals, and the door could be made symmetric easly insead of being one tile off

Had a duplicate, and a wall improperly placed, fixed this up

**Comment by nightred** [comment]
> the door could be made symmetric easly insead of being one tile off

there i moved that door in the end

**Comment by nightred** [comment]
I belive that there is is in a workable state. all areas plumbed access is setup disposals atmo and electrical all look good to me.
If anyone has an issue please post.

**Review by Timberpoes — DISMISSED** [review]
These changes seem to be very well received. It appears all issues have been addressed.

I will be merging this within the next 12-24 hours, this is to put people on notice that if they have their objections or concerns against this being merged, speak up now or it's going in the game! Muahahahaha.

**Comment by Helianthus00** [comment]
I'm back again to nitpick. Some of these are real issues, some are just opinions. I'll put the most important stuff first.
There is an extra sortpipe here for hydroponics. This really shouldn't cause issues unless the janitor sends a package, but should still be fixed.
hydro sortpipe
Extra scrubber in the bar backroom over a L scrubber pipe. This might cause issues with the pipenet, might not but it looks accidentally placed.
scrubber
Extra disposals pipe
extra disposals
Hydroponics gets maint access here and to their maint door, the janitor should also get it to the doors I circled.
janitor
I think this could use more cable redundancy still. Here are two places that would work best.
redundancy2
cable redundancy
Finally, I don't like this one plasteel tile here. I know the old meta freezer had one under the freezer, but I just don't like it. Entirely up to you if you change it or not though.
floor

**Comment by nightred** [comment]
> There is an extra sortpipe here for hydroponics. 
> Extra scrubber in the bar backroom over a L scrubber pipe. 

Done

> Extra disposals pipe

I do not see it and ca not find it int he surrounding tiles.. odd...

> I think this could use more cable redundancy still. Here are two places that would work best.

I am not a fan of redundant wires all over the place but i will adding it.

> Finally, I don't like this one plasteel tile here. I know the old meta freezer had one under the freezer, but I just don't like it. Entirely up to you if you change it or not though.

It has a machine on it and a separating glass sheet, i think the different tile looks good here.

**Comment by Helianthus00** [comment]
Looks great then. That disposals pipe must have been my misclick. 

> 
> It has a machine on it and a separating glass sheet, i think the different tile looks good here.

Yeah I totally respect not wanting to change that tile, just wanted to bring it up while I was dragging out issues. I did another quick sweep and things seem to be fine.

**Comment by Timberpoes** [comment]
@Helianthus00 Thanks for taking the time to look things over in a lot more detail. You're my hero!

**Review by Timberpoes — DISMISSED** [review]
Same old, same old. Looking to merge within 12-24 hours.

Any last minute adjustments, now's your time to suggest them so you can force another set of changes that remove my approved tag.

**Comment by Timberpoes** [comment]
@EOBGames has requested the opportunity to also look over this PR in due course.

I'm happy for this to happen and will delay merging pending his feedback!

**Comment by EOBGames** [comment]
Alright it's finally review time

Technical stuff first:

image
duplicated cameras here, next to the atmos door

image
doubled wire here

image
here too, under the AI sat lobby door

image
this lightswitch is chillin' on the circuit imprinter.

image
I think this one is more down to the "loot spawner", but it seems to spawn items around it regardless of grilles/doors (I also noticed a cockroach embedded in a door by the jannie closet. Perhaps might be worth moving these to more open areas, or removing the ones that are in tighter corners like this one.

Now onto more personal opinion stuff:

I'm not a fan of the tile decals on wood. One possible suggestion I have to make them look a bit less awkward is perhaps upping the alpha levels to make them less transparent. (I really wish we had better options for trimming rooms, i.e. stuff that isn't explicitly designed for tiles, but oh well).

image
The overlapping of decals here kinda looks bad. I'd either place the stripes on top, or remove them in favour of just the trimline. There's a few examples I see of this around the place, but here in particular is probably the most egregious.

Now we get to the really good points:
Engineering is a great bit of mapping. Ties together everything that's necessary in the area, gives both engineering and atmospherics an easily accessible front desk, removes the long, awkward hallway down to telecoms storage, has a nice security office, and the AI satellite access feels better now too. Excellent job.

The new service hall feels much less awkward compared to the old one. My only possible complaint is that there's still a few chokepoints, and as a frequent janitor player passing the bartender in that hallway while I've got my cart will be a recipe for a bad time. That said, I can see no easy way to change this.

The bar itself does feel small, but it's well decorated and has everything you would expect. The space for the bartender is nice, as is the kitchen.

All in all, I really like this PR, and think it's an excellent change to metastation. I now pass this back off to you, @Timberpoes, to merge once the above technical issues are resolved, and the suggestions are either accepted or rejected.

**Comment by nightred** [comment]
> duplicated cameras here, next to the atmos door
> doubled wire here
> here too, under the AI sat lobby door
> this lightswitch is chillin' on the circuit imprinter.
> I think this one is more down to the "loot spawner", 

These items have been fixed up.

> I'm not a fan of the tile decals on wood. 
> The overlapping of decals here kinda looks bad

I like the trim line but it does pose an issue to redecorating, and they look bad solid so i will remove for now.
Botany decals are cleaned up for overlap and reduced a bit.

Thank you for the nice comments.

**Review by Timberpoes — APPROVED** [review]
Right. I've seen positive responses from pretty much all parties involved. It's time to greenlight this change!

**Pull request merged**
