### PR TITLE
Removes slowdown from riot suits

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request
Removes the slowdown from riot suits in an effort to make them more useful to security.

## Why It's Good For The Game
Riot suits have for a while firmly sat in the "garbage-tier" for experienced players because slowdown more or less completely obstructs security from doing their jobs as any perp can outrun them. Given Oranges recently expressed a desire for coded changes that make sec less ridiculously vulnerable to tiders and easy to loot, particularly with hallway shoves, I believe making riot armor an actually useful tool to deal with tiders via its innate shove/knockdown immunity could help.

## Changelog
:cl:
balance: Riot suits no longer have slowdown
/:cl:

### CODE REVIEW

**Comment by Dawson1917** [comment]
image
i thank you for the support my dear friend

**Comment by Shapsy** [comment]
I actually like riot armor right now and have successfully used it a few times since the shove change got merged, it definitely has a niche it didn't have before

**Comment by Yttriums** [comment]
Maybe just go like... 20% or 30% slowdown? The current slowdown is a lot but it does feel right to have a penalty.

**Comment by Dawson1917** [comment]
My intention is to make riot armor better at responding to, well, rioters, in the form of greytiders. We all know security are very, very easy to neutralize since the last disarm rework, turning them into walking low-risk loot pinatas for tiders who want free top notch gamer gear. If security is frequently getting hassled in the round by tiders, they can have riot suits distributed to some officers to be immune to shove spam and make apprehending said tiders a much easier process. 

I don't feel that riot armor is, in practice, for battles of attrition, as most fights boil down to whoever gets stunned first and punched to death. Armor makes little to no difference in your survivability when that happens. 60% melee resistance is also not that incredible; shaft miners can have that much melee resist in the first 5 minutes of their round, as well as greater bullet and laser resist than the riot suit.



> 
> 
> Maybe just go like... 20% or 30% slowdown? The current slowdown is a lot but it does feel right to have a penalty.

Any slowdown at all allows for targets to run laps around you, unfortunately. Getting slowed down in a fight very frequently means certain loss, as seen with anyone who gets shot twice by a disabler.


This PR was mainly made in response to orange's proposed security buff thread (https://tgstation13.org/phpBB/viewtopic.php?f=9&t=23429) in which I found many of the suggestions to be, in my opinion, way overkill. Much of the reasoning behind that thread is that greytiders have no trouble btfo'ing security in your standard round, hence me preferring to buff the crowd control security gear to be less of a pushover when dealing with tiders rather than, say, making sec innately having lower stun times across the board or being immune to dropping items when shoved against a wall, as is being considered in that thread.

**Comment by Anonmare** [comment]
Wait, I thought the riot suit had its slowdown removed once before already?

**Comment by Shapsy** [comment]
50% +10% full body melee resist is incredible though. That's by far the highest value melee resist you can get on station, and it's applied to every limb rather than just your chest

As for security being "very very easy to neutralize since the last disarm rework", how? Just don't stand next to a wall with your weapon out. The soft stun is literally half a second and you can just move away. What are you doing wrong to regularly die to getting pushed by greytiders? 

Stuns aren't anywhere as game over in big group fights like cult base raids or open fighting in the hallways, and it's not at all uncommon to get stunned, whacked a few times, then stand back up because the other person was busy attacking someone else. Those fights are where riot armor shines, since they force people to go out of their way to focus you down or go for a gun instead.

**Comment by wesoda25** [comment]
i liked the change because it removed riot gear from a murderboners checklist

**Comment by Repukan** [comment]
Shameless cargo buff

**Comment by PKPenguin321** [comment]
The reason these have historically had slowdown is because they've also always had some of the best melee armor in the game and were also available roundstart. We didn't want sec defaulting to using them every round. I worry that may be a problem with this PR

**Comment by Shapsy** [comment]
honestly I think it's also just good flavor that the giant bulky padded armor is less maneuverable and better at holding a position than chasing people down

**Comment by Tlaltecuhtli** [comment]
riot armor is for tanking

**Comment by ATH1909** [comment]
Can we just merge this PR instead of implementing orange's idea to make sec officers not drop their held items when knocked down/stunned?

**Comment by necromanceranne** [comment]
As if armor really matter in melee. It's entirely in gunfights that armor has any real meaning.

**Comment by Arathianen** [comment]
Melee armor is a joke in practical terms. Riot armor is a joke fot that precise reason.

Riot armor is good for one thing. Stopping the tide from shoving you and looting you.

Also, it has less ranged armour than a basic vest making it extremely bad at dealing with a real threat.

There is no real reason why the riot suit should have such a slowdown. It's not good in crisis situations and the slowdown makes it not good in 'tide situations. So it's just bad.

**Comment by optimumtact** [comment]
The issue with this approach is that it makes security and the armoury further loot heavy locations.

The whole purpose of the combat training I was thinking of was to add shove resist and stamina defence in a way that didn't result in these becoming a checklist item on murderboning antags shopping lists

**Comment by Arathianen** [comment]
I think it's a good stopgap measure for now. It's also not reaaaally good be a murderboner item.

Let's think of a scenario of Johhny Murderbone. He has his esword out, he already blew up beebsky and has his baton armed and is ready for some gamer action.

By the time time he has access to the armoury, he is probably a known threat. When people deal with known traitors, they won't be using disablers and stun batons. They will be grabbing the shotguns.

If our Johnny gets shotgunned, he is in crit in 2 hits.

So our Johnny is smart and grabs the bulletproof armor like always.

**Comment by Dawson1917** [comment]
@Shapsy as someone who frequently greytides the life out of security, I can attest that it is extremely easy to stunlock and loot any member of sec with the simple simple shove > tablestun and strip maneuver. If not just shoving sec the moment they pull their baton out to arrest someone or myself.
Sec attracts new players who aren't that gud, yes, but it's also often the most experienced players who are greytiding sec every single round, and we can clearly see that sec needs some kind of way to not be so easily destroyed by any given crewmember. 



> 
> 
> The issue with this approach is that it makes security and the armoury further loot heavy locations.
> 
> The whole purpose of the combat training I was thinking of was to add shove resist and stamina defence in a way that didn't result in these becoming a checklist item on murderboning antags shopping lists
> 
> mixed feelings I guess

I am very, very averse to adding innate skills or buffs to any jobs. I don't believe riot armor would be a supremo pick for murderboners as the bullet & laser resist is basically non-existent and the clear counter for someone everyone knows is using riot armor as shown by the huge sprite. I think it also contrasts well with bulletproof armor's excellent bullet resistance but terrible melee and laser defences. Sec body armor's 30% bullet, melee, and laser resist is still excellent for general damage resistance and I don't think riot armor without slowdown will shift the meta away from warden's/HoS' vests for full-body protection or captain's vest for ridiculous chest protection or RD's telearmor for ignoring a free shot frequently and making you harder to stun.

**Comment by CPTANT** [comment]
Riot armour isn't that useful for anyone looting the armory because it stands out and security will fight you with disablers and lasers anyway.

**Comment by actioninja** [comment]
The slowdown was intentionally added to make riot not the go to armor everyone equips roundstart because it's got extremely good utility, as well as a neccesity to prevent you from getting fucked over in a murderbone.
I didn't know how insane movespeed was at the time so something like 0.25 would probably be better though.

**Comment by Dawson1917** [comment]
> 
> 
> The slowdown was intentionally added to make riot not the go to armor everyone equips roundstart because it's got extremely good utility, as well as a neccesity to prevent you from getting fucked over in a murderbone.
> I didn't know how insane movespeed was at the time so something like 0.25 would probably be better though.

If you decide to be a big strong security mans who asks the warden to let you into the armory roundstart for riot armor you are going to get completely _fucked_ by any traitor with a stetchkin, revolver, cargo gun, advanced mimery, etc, god forbid surprise ops. If it becomes the new roundstart meta for security officers I can always change it

**Comment by OmegaShoots** [comment]
To have made this PR with the excuse of "the greytide just outruns it" means you do not understand how to use riot armor, and how it's used in real life.

It is a defensive item used in mostly stationary combat situations, or when fighting a threat that you are not running after.
Officers shouldn't not be just grabbing these and walking around the station with them for no reason, they're to be used in emergencies/specific fights like say a blob or such where your target isn't on the run, and the massive amount of extra melee protection is well needed.

If you walk around the station in riot gear because you want to be le edgy swat man, then you are a bad officer and DESERVE to be stolen from.

**Comment by Dawson1917** [comment]
The intention is to give your officers riot armor when rowdy civilians are giving security trouble. As in, tiders. Riot armor is the only already-existing equipment that grants shove immunity, which is why I'm buffing it to make it useful outside just blob and raiding cult bases, with the tradeoff that any _actual_ traitors will be able to kill you easily with guns.

If you have any better ideas for making security less vulnerable to tiders they would be very valuable on Orange's [security buff thread](https://tgstation13.org/phpBB/viewtopic.php?f=9&t=23429)

**Comment by Shapsy** [comment]
bro just don't stand next to a table

**Comment by necromanceranne** [comment]
Riot armor is a complete joke in any scenario that doesn't involve fighting unarmed assistants in close quarters since anything of actual relevance/actually can kill you bypasses it and abuses your immense slowdown. Again, armor is a practical joke and will be so long as stuns and disabling effects or various status effects like object embedding ignores these defenses completely. Bolas, thrown spears, cult stun hands, thrown edaggers, the works. If the grey has a toolbox he will opt to throw it and scatter. And most of the high damage weapons carry armor penetration so even the actual upside of the armor falls flat.

Shoves are powerful but not so powerful as to want to be slowed to overcome them.

**Comment by optimumtact** [comment]
Alright lets give it a go then

**Comment by ATH1909** [comment]
Orang man gud

**Pull request merged**
