### PR TITLE
Changes a reference to be in theme with its location

### PR DESCRIPTION
**Pull request by Niknakflak**
Non-meme/Non-closure for dumb reason edition.

Comment, like, and subscribe

### CODE REVIEW

**Comment by pudl** [comment]
wut da zog

**Comment by Zilenan91** [comment]
niknakflak is in admins.txt

this means nnf is a reference in the code

remove nnf

**Comment by Shadowlight213** [comment]
Done

**Comment by MMMiracles** [comment]
the ride never ends

**Comment by PKPenguin321** [comment]
:-1:

**Comment by KorPhaeron** [comment]
https://www.tgstation13.org/phpBB/viewtopic.php?f=2&t=194&start=400#p175345

I think it's amusing that niknak is making dark souls fanart

**Comment by TechnoAlchemisto** [comment]
G r u d g e  C o d i n g

**Comment by Niknakflak** [comment]
shitart can be made from anything

**Pull request closed without merging**
