### PR TITLE
Bodyparts will now always appear above items and are not destroyed by the blob

### PR DESCRIPTION
**Pull request by ChangelingRain**
IE; they act similarly to how mobs act.

### CODE REVIEW

**Comment by KorPhaeron** [comment]
H U G B O X

**Comment by Firecage** [comment]
But why should the blob not be able to destroy them?

**Comment by ChangelingRain** [comment]
The blob can't destroy a human's corpse, so why should the limbs be any different?

**Comment by Firecage** [comment]
Because who knows? Considering the blobs can destroy walls, eat borgs whole, etc., it doesn't make much sense if it can't even eat a simple arm or leg.

**Comment by Incoming5643** [comment]
>The blob can't destroy a human's corpse, so why should the limbs be any different?

You're very lucky I made blob zombies or I'd make a pull to let blobs destroy corpses right now.

**Comment by Alek2ander** [comment]
feature request: zombie limbs

**Comment by optimumtact** [comment]
@KorPhaeron can you be more explicit about being opposed to a pr or not? It's difficult to interpret your stance.

**Comment by KorPhaeron** [comment]
I dont really care either way

**Comment by optimumtact** [comment]
Well please remember that your words hold a lot of weight

**Comment by optimumtact** [comment]
Anyway for consistencies sake.

**Pull request merged**
