### PR TITLE
Adds two more drinks, Bastion Bourbon and Squirt Cider

### PR DESCRIPTION
**Pull request by ghost**
:cl: Xhuis
add: Added Bastion Bourbon, which you can mix with tea, creme de menthe, triple citrus, and berry juice. When it's in your system, it will very slowly heal you as long as you're not in critical. When it's first added to your system, you heal an amount of each damage type equal to the volume taken in, with a max of 10. This is turned to a max of 20 for anyone in critical.
add: Added Squirt Cider, which you can mix with water, tomato juice, and nutriment. It's nutritious and healthy!
/:cl:

I sprited Bastion Bourbon for practice, and decided to add it to the game as an actual drink. It functions as close to health tonics as would be allowed in SS13 while not completely breaking balance, by healing a small amount of damage when you first ingest it, with a hard cap of 10 of each type (20 in crit.) and 1 unit healing 1 of each type.

It also slowly heals damage while it's in your system (1 brute and burn, 0.5 tox, 3 oxy, and 5 stamina), but metabolizes quickly at 0.8 units per tick.

Squirt Cider is just a healthy drink, with both nutritious value and a small amount of satiety boost (equal to 1/6th that of vitamins.)

* **Bastion Bourbon:** equal parts tea, creme de menthe, triple citrus, berry juice (makes 2u instead of 4)
Bourbon
* **Squirt Cider:** equal parts water, tomato juice, nutriment
Cider

### CODE REVIEW

**Comment by Buggy123** [comment]
squirt.
cider.

**Comment by Xhuis** [comment]
[Squirt Cider!](http://bastion.wikia.com/wiki/Squirt_Cider)

**Comment by Buggy123** [comment]
that's some hefty innuendo right there

**Comment by fludd12** [comment]
Heh, and my boyfriend and I are working on stabsinthe.

**Comment by cebutris** [comment]
Working on Stabsinthe for Citadel code! If it goes well I'll see about porting it here!

**Comment by arsserpentarium** [comment]
Are you sure, that squirt cider isn't for citadel?
Are you sure, that that thing is consumable?

**Comment by ExcessiveUseOfCobblestone** [comment]
If this is added im making a drink that requires HP and BB and is toxic.

**Comment by Buggy123** [comment]
>Squirt Cider: equal parts water, tomato juice, nutriment

wait.

that's tomato juice.

that's just watered down tomato juice.

**Comment by ExcessiveUseOfCobblestone** [comment]
it's bad ketchup

**Comment by Xhuis** [comment]
Shit, the secret's out!

**Comment by epochayur** [comment]
>Bastion Bourbon: equal parts tea, creme de menthe, triple citrus, berry juice

🤢

**Comment by Xhuis** [comment]
The sum is more than its parts, promise.

**Comment by Xhuis** [comment]
@ExcessiveUseOfCobblestone You can if you'd like, but with the recent nerfs HP is for the most part never going to be made now due to its weaker healing in combination with the huge amount of reagents you need to make a small amount. BB's healing in normal health is weaker than any real combination of reagents.

**Comment by ExcessiveUseOfCobblestone** [comment]
It wasn't made much at all to begin with, it only became a note-worthy problem upon being given roundstart.

And yes, while they aren't epic healing chems on their own, more avenues of healing allow for stacking.

now I have to think of a cute drink though >:(

**Pull request merged**
