### PR TITLE
Block OOC during cinematics

### PR DESCRIPTION
**Pull request by AnturK**
Then again the spam is usually funny.

### CODE REVIEW

**Comment by optimumtact** [comment]
outs that it's fake though

**Comment by AnturK** [comment]
Yeah, that's why i'm not sure it's good idea.

**Comment by Iamgoofball** [comment]
Just make the normal nuke block OOC too.

**Comment by Tlaltecuhtli** [comment]
admin issue

**Comment by Grazyn** [comment]
is it possible to block OOC but spam the chat with fake OOC messages?

**Comment by PKPenguin321** [comment]
Fun removal

**Comment by Anonmare** [comment]
Doesn't really matter if it's outed as a fake nuke since the round end will go on regardless whilst a real one ends it in which case the OOC spam won't matter

**Comment by AnturK** [comment]
Switched to just blocking ooc during all cinematics.

**Comment by DaxDupont** [comment]
but arm spam

**Comment by ninjanomnom** [comment]
If you want to get *real* fancy you could modify the ui to hide everything but the cinematic

**Review by SpaceManiac — APPROVED** [review]

**Comment by optimumtact** [comment]
@AnturK just make all cinematics have an OOC block

**Comment by AnturK** [comment]
Already did, forgot to take off WIP tag.

**Pull request merged**
