### PR TITLE
[s]Adds the Booze and Soda Synthesizer to Plumbing.

### PR DESCRIPTION
**Pull request by Iamgoofball**
## About The Pull Request
Adds the Booze and Soda Synthesizer to the plumbing tool.
dreamseeker_TGMiu84wcj
jdUCfP7RSs
dreamseeker_I9H6bvrOJA
tgEp5br7Up

## Why It's Good For The Game
Building plumbing automation to make your favorite brews is always a good time, and can be used to get fancy medicinal effects(or poison effects) to your pills.

## Changelog
:cl: Iamgoofball
add: Added the Booze and Soda synthezisers to Plumbing.
experimental: It's good to be back.
/:cl:

### CODE REVIEW

**Comment by qbmax32** [comment]
ITS HAPPENING

**Comment by Iamgoofball** [comment]
just found out Synthesizers are not the intended way for chemicals to be introduced to the plumbing system, closing this PR until I find out the design goals going forward

**Comment by carlarctg** [comment]
nooo don't close the pr you're so cute haha

**Comment by Couls** [comment]
goof while you're here can you revive GOAP

**Comment by Pugie** [comment]
BACCHUS FACTORY WHEN

**Comment by Tlaltecuhtli** [comment]
i think it would be more interesting with a chem factory fermenting barrel

**Comment by 81Denton** [comment]
Don't bother messing with [s] unless it's for a security issue

**Comment by 81Denton** [comment]
Also what tlal said, integrating fermentation barrels into chem factory would be great.

**Comment by Iamgoofball** [comment]
@81Denton I wanted to prevent in game spam.

**Pull request closed without merging**
