### PR TITLE
Adds random seed feedback

### PR DESCRIPTION
**Pull request by Cyberboss**
@nfreader

### CODE REVIEW

**Comment by nfreader** [comment]
I'd stick this in `ss13round` tbh.

**Comment by optimumtact** [comment]
it won't work stop

**Comment by Jordie0608** [comment]
What does this even do?

**Comment by coiax** [comment]
We're recording random number generators in feedback now?

**Comment by Iamgoofball** [comment]
@Jordie0608 you can seed byond's RNG

**Pull request merged**
