### PR TITLE
Revert "Temporarily removes stock computers (#GoofFixYourShit)"

### PR DESCRIPTION
**Pull request by Iamgoofball**
Reverts tgstation/tgstation#19952

EXPORTS IS THE FUCKING PROBLEM CAN YOU READ AAAAAAAAAAAAA

### CODE REVIEW

**Comment by TheColdTurtle** [comment]
oh shit, he is doing it the madman

**Comment by optimumtact** [comment]
You can only get it back if you fix the stock spikes.

**Comment by PKPenguin321** [comment]
@Iamgoofball 
>>>Temporarily

i figured the idea was a revert would be in order once exports were fixed, because exports aren't necessarily the issue, but they help amplify the issue

**Comment by Bawhoppen** [comment]
I like the idea of stocks but this removes them until cargo points and prices can be fixed in general (whatever you want to say causes them)

**Comment by Cheridan** [comment]
So the hypothesis right now is that excessive exports leading to lots of money allowing you to buy tons of stocks was what lead to price spiking. Now that meme lemons are gone we can readd these and see where we're at.

**Pull request merged**
