### PR TITLE
Revert "Updates the Syndicate revolver into a new revolver (with the same stats)"

### PR DESCRIPTION
**Pull request by Mothblocks**
Reverts tgstation/tgstation#71704

The @tgstation/sprite-team  did not approve this PR, I misread and thought they did and would not have merged it if I had paid attention

:cl:
del: Blink and you'll miss it, the syndicate revolver has come back.
/:cl:

### CODE REVIEW

**Comment by Mothblocks** [comment]
@optimumtact I'm dumb

**Comment by Overuseddart** [comment]
I thought this was a revert war and was excited to see goofball shitposting.

**Review by Twaticus — APPROVED** [review]

**Comment by JohnFulpWillard** [comment]
merging now because they incorrectly still replaced the sprite instead of making it a new state, breaking the icon entirely

image

**Comment by JohnFulpWillard** [comment]
wrong button

**Pull request merged**
