### PR TITLE
pAI can't pull people

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
Thanks mekhi

### CODE REVIEW

**Comment by coiax** [comment]
I think there's a flag for this.

**Comment by optimumtact** [comment]
I don't think there is a flag

**Comment by WJohn** [comment]
was this tested literally at all? jesus christ how does shit like this still get past us?

**Comment by karlnp** [comment]
mekhi has shame?

**Comment by WJohn** [comment]
like this is a lot of bugs
https://github.com/tgstation/tgstation/issues/22206

**Comment by TehZombehz** [comment]
Y'know, it may be in the sillytips text file but it's always been true:
>This is a game that is constantly being developed for. Expect things to be added, removed, fixed, and broken on a daily basis

No one is without shame.

**Comment by coiax** [comment]
I was wrong, there isn't a flag, this is how no pulling on blobbernauts is done.

https://github.com/tgstation/tgstation/blob/f292bc2b3151ee136fc14c5563a0ce47f391419a/code/game/gamemodes/blob/blobs/blob_mobs.dm#L229

Perhaps we should actually make a NOPULL flag for mobs

**Comment by optimumtact** [comment]
I started a grab rewrite but it's like my sliprewrite

**Comment by dannno** [comment]
if you spell "mekhi" backwards its "goofball"

**Comment by PKPenguin321** [comment]
>mekhi's """"buggy"""" features
>flight pack that didn't require any research """bug"""
>free all access with a pAI """bug"""

hmmm

**Comment by kevinz000** [comment]
what the fuck it didnt pull when i tested it reee!

**Comment by KorPhaeron** [comment]
Mekhi is taking too long

**Pull request merged**
