### PR TITLE
Liberation Station 2: Freedom Strikes Back

### PR DESCRIPTION
**Pull request by MMMiracles**
image

Includes a brand new vending machine called the Liberation Station, a badmin's one-stop shop for all things patriotic and free. 

Comes equipped with various ballistics and if hacked, dispenses patriotic jumpsuits and freedom sheets to protect you from night terrorism.

Edit was done after the picture was taken to get rid of the blue clipping over the hands.

### CODE REVIEW

**Comment by SconesC** [comment]
time to fight communists -in style-

**Comment by PKPenguin321** [comment]
:us: :us: :us:
:+1:

**Comment by MMMiracles** [comment]
i dont see what could be causing merge conflicts so im just going to assuming travis hates me.

**Comment by pudl** [comment]
because someone else is fucking with vending.dm (psst it's goofball)

**Comment by MMMiracles** [comment]
goof where are you im gonna liberate the shit out of you

**Comment by optimumtact** [comment]
You're conflicting with master, I don't believe travis currently checks if you conflict against other PR's

**Comment by MMMiracles** [comment]
i cant tell what else is conflicting with master at this point after skimming through the files, im having lots of fun right now.

**Comment by Miauw62** [comment]
ASS BLAST USA
Op 9-mrt.-2015 11:31 schreef "MMMiracles" <notifications@github.com>:

**Comment by MMMiracles** [comment]
YEEEAAAH

**Comment by MMMiracles** [comment]
i just realized how many files were changed

holy fuck backpedel backpedel its all gone wrong how did i even manage this

**Comment by PKPenguin321** [comment]
>mfw 30,000 lines changed to add a vending machine

**Pull request closed without merging**
