### PR TITLE
Improves selections for head of staff fashion

### PR DESCRIPTION
**Pull request by Eaglendia**
When cloaks were back slot items, they allowed wearers the trade-off of additional armor at the cost of carrying capacity. Now, the head of staff cloaks are suit slot items with the signature aesthetic of a given head of staff. While it might be ridiculous to allow these cloaks to hold the same items as armor, or other suits and vests, it seems reasonable that they might be tailored to carry a particular item suitable to each head of staff.

The Captain's cloak can carry the antique laser gun, the Head of Security's cloak can carry their unique energy gun, the CMO's cloak can carry the hypospray, the RD's cloak can carry a hand teleporter or RPED, and the CE's cloak can carry an RCD or RPD.

:cl: Eaglendia
add: Central Command has released a new, more functional run of their most stylish fashion line.
add: Head of Staff cloaks can now hold specific items - the antique laser gun for the Captain, the replica energy gun for the Head of Security, the hypospray for the Chief Medical Officer, the Hand Teleporter or RPED for the Research Director, and the RCD or RPD for the Chief Engineer.
/:cl:

### CODE REVIEW

**Comment by TechnoAlchemisto** [comment]
yeah I guess I forgot about that stuff when I changed them to exosuit slots +1 n shit

**Comment by SweaterKittens** [comment]
THANK YOU!

**Comment by KazeEspada** [comment]
CE's cloak should also hold the RPD as well. ATMOSIA!

Maybe the RPED for the RD since thats more researchy than the hand teleporter.

**Comment by Bawhoppen** [comment]
let the CE's carry the blueprints instead, and let the RD's carry lamarr

**Comment by TheNightingale** [comment]
The armour on the HoS' cloak still makes me cry, but otherwise, :+1:

**Comment by Zilenan91** [comment]
Isn't the HoS' cloak more protective than regular sec armor?

**Comment by TheNightingale** [comment]
It's better at taking bullets, but worse against lasers, and it's a straight-up downgrade from the trenchcoat. Armour stats are weird.

**Comment by Shapsy** [comment]
I'd say just let the CMO's and RD's carry the same junk as a labcoat can, since they're basically the same thing

**Comment by hornygranny** [comment]
can we just standardize the armor of fashion choices @KorPhaeron

**Comment by KorPhaeron** [comment]
@hornygranny 

That means a new set of HoS armour waiting to be handed out to his underlings for every fashion alt choice you have. Unless we start letting people use vouchers or transform the armour like some weird chameleon shit.

**Comment by Bawhoppen** [comment]
@KorPhaeron  still waiting on loadout system

**Comment by Eaglendia** [comment]
Honestly I forgot the station blueprints actually had a function other than getting stolen. Are they something that a lot of people actually use?

**Comment by Bawhoppen** [comment]
occasionally yes

**Comment by Zilenan91** [comment]
Rename areas to Xenobiology Lab and xenobio can use their consoles to spew slimes there

**Comment by KorPhaeron** [comment]
You have to do rscadd:

Not add

**Comment by Jordie0608** [comment]
add works too for the bot generation

**Comment by kevinz000** [comment]
reactive teleportation cloak

**Pull request merged**
