### PR TITLE
Makes "Flash burnt out!" Message Bigger

### LINKED ISSUE #22963: Not a bug but flash text is too tiny
You know when your fighting... 
And you try to flash but it burns out and you dont notice it because the giantic red attack messages scrolls it off and the black flash bulb message away...
 Pls mak text bigger

### PR DESCRIPTION
**Pull request by JohnTheDonut**
Makes "Flash burnt out" message bigger so that during combat it is now more obvious to the user that the flash has been burnt out when fighting.

I am also very new to coding for TG station and coding in general so any suggestions on how i should do anything are very welcome.

:cl:
Tweak: tweaked a few things
:cl:

Fixes #22963

Sorry i had to close the previous PR and open this one, i broke my branch when i tried to overwrite the commit i made.

### CODE REVIEW

**Comment by XDTM** [comment]
You need to check of loc is a living before defining it as such; add if (isliving(loc)) before your code. Also, the burnout message will display twice to the user as you set it right now, since they get both the visible message and the direct one.

**Comment by XDTM** [comment]
Or replace if (loc) with if (istype(loc)), but the former is the more commonly used variant.

**Comment by Tofa01** [comment]
Ok so i put in the code so only the user will see the direct message how do i go about getting only other users to see the visible message?

**Comment by XDTM** [comment]
visible_message can take more parameters: the first one will be what everyone else sees, the second one, if set, what only the user sees, and the third one, if set, is what people who are close but can't see it hear.

The way i'd go about this is this, replacing from line 50
```
if(ismob(loc))
   var/mob/M = loc
   M.visible_message("<span class='danger'>[src] burns out!</span>","<span class='userdanger'>[src] burns out!</span>")
else
   var/turf/T = get_turf(src)
   T.visible_message("<span class='danger'>[src] burns out!</span>")
```

**Comment by Tofa01** [comment]
I see so if i add more parameters to the M.visible_message it changes what happens and what people can and cannot see. Very interesting thanks so much for dealing with my "Noob-nes" i am going to test and then merge the commit and hope i don't break my branch this time. Are there any resources that you would recommend to help me with future issues and learning stuff? Oh also by the way i heard some kind of feature freeze was happening and they were giving out antag tokens if this gets merged i would like to give you my "points" or however that works because well you pretty much wrote the code.

**Comment by XDTM** [comment]
Don't worry about tokens, you can only get one anyway and i have already made fixes, so i've got mine.
As for resources, the dream maker's help page is pretty handy to see how the code basics work.
https://tgstation13.org/wiki/Understanding_SS13_code and https://tgstation13.org/wiki/SS13_for_experienced_programmers have been useful for me as well, and for anything else you can visit the coderbus irc channel (irc.rizon.net/coderbus).

**Comment by Tofa01** [comment]
Wow yeah thanks i am going to read all of that and do a bit of research for myself, thanks for all the help too really appreciated. I guess this is ready to merge whenever if its still wanted to be merged.

**Comment by optimumtact** [comment]
Stamped [QM's approval]

**Pull request merged**
