### PR TITLE
Updated MetaStation.v40B.dmm to MetaStation.v40C.dmm

### PR DESCRIPTION
**Pull request by Metacide**
-Also updated MetaStation/z2.dmm
-Added missing drinks showcase to the bar.
-Added missing slot machines to the casino.
-Added missing maintenance loot spawners throughout maintenance.
-Added missing intelliCard to RD office.
-Added missing atmospheric technician lockers to atmospherics.
-Added missing Janicart and Secway to the custodial closet and brig, respectively.
-Added missing blast doors under cell windows in xenobiology.
-Added missing blast doors under windows around the HoS' office.
-Added a drinks shaker to the Captain's quarters.
-Added more department direction signs.
-Added vendomat and slot machine to the ghetto bar.
-Added a variety of winter coats to dorms and one to each department that has a sprite.
-Added a zippo lighter, and cigarette and coffee vendors, to the council room.
-Switched direction of conveyer-belts in cargo bay for easier tagging and mailing of ordered crates.
-Fixed lack of security batons in brig security lockers - they are intentionally absent from departmental lockers.
-Fixed chapel shutters not working.
-Fixed a few instances of incorrectly empty medkits on roundstart.
-Fixed a missing disposals pipe in the brig control room.
-Fixed tiles in the south-west of the central hallway incorrectly being area-designated as space.
-Fixed mushroom pizza causing compile issue
-Renamed telescience lab to experimentation lab
-Replaced nuke-op staging point station map with the one specific to MetaStation.
-Other minor alterations

15-02-15 14-20 metastationv40c full - 800
Full detail image: https://dl.dropboxusercontent.com/u/858120/Static/SS13/MetaStation/15-02-15%2014-20%20MetaStationv40C%20Full.png

Wiki updated: https://tgstation13.org/wiki/index.php/MetaStation
Please feel free to post feedback in the thread: https://tgstation13.org/phpBB/viewtopic.php?f=11&t=399

### CODE REVIEW

**Comment by Metacide** [comment]
Anyone have any idea why this fails?

**Comment by RemieRichards** [comment]
@Metacide 
_maps/map_files/MetaStation/z2.dmm:548:error: undefined type: /obj/item/weapon/reagent_containers/food/snacks/mushroompizzaslice
_maps/map_files/MetaStation/z2.dmm:548:error: unknown type

**Comment by Metacide** [comment]
Bah. Right, I'll look into it a bit later on. Thanks.

**Comment by Metacide** [comment]
Looks fixed?

**Comment by Metacide** [comment]
Right, looks like it's fixed. Thanks very much. :+1:

**Comment by Metacide** [comment]
Alright, this should be good to pull whenever someone has a moment.

**Comment by Metacide** [comment]
Many thanks.

**Pull request merged**
