### PR TITLE
You can't eat appendices scot free anymore (ew)

### LINKED ISSUE #49267: appendixes are no longer poisonous to eat
They used to have the bad_food chem in them, but https://github.com/tgstation/tgstation/pull/48596 unintentionally (according to qustinuus) removed that chem from them.

### PR DESCRIPTION
**Pull request by spessbro**
## About The Pull Request
appendices have bad food in them

## Why It's Good For The Game
fixes #49267

## Changelog
:cl:
fix: appendices are toxic again
/:cl:

### CODE REVIEW

**Comment by RaveRadbury** [comment]
This won't stop lizards, they enjoy bad food.

**Comment by Jared-Fogle** [comment]
thats alright

**Review by Mothblocks — APPROVED** [review]

**Comment by CRITAWAKETS** [comment]
Add a way to remove the bad food, something like deep frying or grilling. I want to serve appendices goddamit

**Comment by Farquaar** [comment]
> 
> 
> This won't stop lizards, they enjoy bad food.

What else is new? :^)

**Comment by spessbro** [comment]
ey yo where the frick is me fix tag >:(

**Pull request merged**
