### PR TITLE
Admin only event: Station-wide Human-level Intelligence

### PR DESCRIPTION
**Pull request by coiax**
:cl: coiax
add: Added a new admin only event: Station-wide Human-level Intelligence. Like the random animal intelligence event, but affecting as many animals as there are ghosties.
/:cl:

Will lead to mouse and cockroach uprisings. Also a good solution for salty ghosts wanting to be part of an ERT. Give them a random mouse in maint, and watch them attempt to valid people anyway.

### CODE REVIEW

**Comment by gt33** [comment]
inb4 spess cat invasion

**Comment by PKPenguin321** [comment]
Is it admin only? If not, how rare is it?

**Comment by coiax** [comment]
> **Admin only** event: Station-wide Human-level Intelligence
>add: Added a new **admin only** event: Station-wide Human-level
Intelligence.

**Comment by lordpidey** [comment]
Looks like someone missed out on the human level intelligence.

**Comment by PKPenguin321** [comment]
Implying I'm literate and not randomly mashing my keyboard and getting extremely lucky

**Comment by OtherDalfite** [comment]
This should have a vote before it as to whether ghosts would like to be included as i can see people getting upset if they become a cockroach just as theyre about to get cloned

**Comment by coiax** [comment]
It's already opt in, it uses the ghost role system we have.

**Pull request merged**
