### PR TITLE
Sentient Matter Station Trait

### PR DESCRIPTION
**Pull request by tralezab**
## About The Pull Request

Very rarely, a station trait will fire that will let the supermatter be a playable ghostrole. You can't move or anything so it's a lot like being a sentient blade, but you do get to shit on the chief engineer as they set you up.

## Why It's Good For The Game

I cannot fathom a more jarring experience than starting the engine for the 200th time only to have it shittalk you. IMAGINE the dumb shit that can come out of this in general. Every situation where you interact with the SM becomes hilarious and stupid and I like that

## Changelog

:cl:
add: Added a rare station trait, the sentient matter trait!
/:cl:

### CODE REVIEW

**Review by Mothblocks — CHANGES_REQUESTED** [review]

**Review by Twaticus — APPROVED** [review]

**Comment by Stalkeros2** [comment]
OH MY GOD MONOLITH
PRAISE ROCK!!!!!!!!!!!! :D

**Comment by KittyNoodle** [comment]
Instead of delaming like normal make it grow legs for a minute then explode

**Comment by tralezab** [comment]
I like the dog pr better and I don't want to step on its toes

**Comment by tralezab** [comment]
also guys just try adding a font to ss13 you will literally suffer the effects of not hydrating in any way for two weeks in the time frame of 2 hours

**Comment by KittyNoodle** [comment]
NOOOOOOOOOOOOOOOOOOOOOOOOO

**Comment by esainane** [comment]
@tralezab Mind if I try picking this up? I really want to see this in game

**Pull request closed without merging**
