### PR TITLE
You can now control the solar panels directions in tramstation AIsat Solars

### LINKED ISSUE #75168: Tramstation AI Sat solars not working
## Reproduction:
This is more of a mapping issue; the AI sat solar array console can't connect as-is with the roundstart setup, need to bypass the SMES to get it to work so the SMES is feeding itself which is a bit troublesome.

### PR DESCRIPTION
**Pull request by Singul0**
## About The Pull Request
Does what it says on the tin.
closes #75168
gambar
## Why It's Good For The Game
bugfix le good?
## Changelog
:cl:
fix: The console for the solar panels of AIsat solars tramstation are now actually connected together
/:cl:

### CODE REVIEW

**Comment by san7890** [comment]
i only trust @Maurukas to review this PR since if anything breaks and anyone else merges it, vire'll be the ones that fix it.

**Comment by Singul0** [comment]
It's not ideal, 2 APC's need to be charged before the power goes to the SMES. But it works

**Review by Maurukas — CHANGES_REQUESTED** [review]
Please disconnect the AI APC from the solar side of the grid and connect it to the SMES side like so: 
image

This will let the AI charge from the SMES, and it's only a single additional cable.

**Comment by Singul0** [comment]
I have committed the changes you asked for.

> Please disconnect the AI APC from the solar side of the grid and connect it to the SMES side like so: image
> 
> This will let the AI charge from the SMES, and it's only a single additional cable.

**Review by Maurukas — APPROVED** [review]

**Pull request merged**
