### PR TITLE
Fixes metastation science delivery chutes causing fractures to anyone who enters.

### LINKED ISSUE #56651: Mapping issue with metastation science.
When you take the disposal system to science the window next to the disposal bin is too close to the outlet - the result is guaranteed fractures.

### PR DESCRIPTION
**Pull request by Potato-Masher**
## About The Pull Request
Fixes #56651 
Taking the disposals chutes from Metastation cargo to science's exterior output would spit you out and slam you into the directional window that was too close the the output, resulting in bone fractures. I've moved a few things around to ensure that the chute is at least usable without immediate risk of self injury.

I've also moved a crate out of the output of the service hall chute, as that also would cause fractures after exiting.

A few touch ups on the decals have also been made by adding those fancy colored siding decals to the edges of the output areas, just like what the new Meta science had. Why? I thought it looked nice.

## Why It's Good For The Game
Consistent with the other delivery chutes, which don't break your bones.

## Changelog
:cl: Potato Masher
fix: Taking Metastation's delivery chute to science and service should no longer cause bone fractures.
/:cl:

### CODE REVIEW

**Comment by Potato-Masher** [comment]
Something was merged in the past few hours, I'll need to go back and update. Converting to draft for now until I get it resolved.

**Comment by Potato-Masher** [comment]
Alright, looks good now. Reverting draft state.

**Comment by notfrying1pans** [comment]
I was going to ask this yesterday but I'd recommend renaming this to something like "Various meta delivery chute tweaks" as you did more than just add a tile to sci's chute.

**Comment by Son-of-Space** [comment]
Please make sure that the rest of the delivery chutes are also working properly while you do this. Triple check if you can.

I can't see the edits that you've done for the chutes in the map diff, so please make sure that they still follow the main hallway as much as possible and don't go over walls as much as possible, too.

**Comment by Potato-Masher** [comment]
> Please make sure that the rest of the delivery chutes are also working properly while you do this. Triple check if you can.
> 
> I can't see the edits that you've done for the chutes in the map diff, so please make sure that they still follow the main hallway as much as possible and don't go over walls as much as possible, too.

I may have not been descriptive enough, but I have not touched a single piece of pipe or the chutes themselves. I just shifted the entry to sci lobby over a tile, moved one crate, and added department colored siding to the exit areas just like science had before. 

And yes, I tested locally, they still work and no bones are broken.

**Comment by EOBGames** [comment]
Sorry for taking so long to get to this- it does now seem to be conflicting, though. Once you resolve that please ping me on discord, Emerald_or_Bust#1314, and I'll merge this ASAP.

**Pull request closed without merging**
