### PR TITLE
Grille Sprite Change

### PR DESCRIPTION
**Pull request by ghost**
From /vg/station
grille

As you can see the /vg/ grille looks a LOT better under windows, the /tg/ grille is unequal and doesn't look as nice
The /tg/ grille is sticking out of the left sides of the windows and looks awkward

:cl:
imageadd: Grilles have new sprites
/:cl:

### CODE REVIEW

**Comment by ACCount12** [comment]
It looks better, but wait, are you 👍 yourself? Most people here are not autistic enough to do THAT in public.

**Comment by Armhulen** [comment]
no actually it looks awful

**Comment by TrustyGun** [comment]
yeah, this looks kind of bad. maybe with smoothing, but even then, ehh.

**Comment by ACCount12** [comment]
Yes, it looks worse when multiple grilles are close together. Smoothing is necessary here.

**Comment by Grazyn** [comment]
Honestly, how can you say not only that it looks better, but A LOT better? It looks objectively worse, with that weird black separator which is also misaligned with the window.

**Comment by DoctoreMad** [comment]
What I really was thinking of was getting a grille that was easier to click under without having to ctrl(Or was it alt?)+click the tile then click the tile in the menu. That way I can push people into a shocked grille easily.

**Comment by DoctoreMad** [comment]
To give this sprite credit, it DOES make windows look better when its under one.

**Comment by psykzz** [comment]
Having the always on grillenot interweave properly is annoying, can you do something more like
image

(Also not sure why smoothing is affecting it like that, as i've never sprited)

**Comment by DoctoreMad** [comment]
@psykzz 

just

**Comment by Dorsisdwarf** [comment]
gross 👎

**Comment by uraniummeltdown** [comment]
@psykzz Grilles are still awkwardly sticking out of the window and are unequal and uneven, look at the window under the man, alternating grey and black pixels above the window looks bad
The solid border of the /vg/ sprite is a lot better than the uglyness around the edges

**Comment by duncathan** [comment]
this would be ok with smoothing but otherwise it's a joke

**Comment by psykzz** [comment]
@uraniummeltdown I disagree that its better with this proposal though, while your case is better for a single grille, its horrible in pairs.

**Comment by WJohn** [comment]
I am strongly against these, and a better alternative PR exists. These lack shading, the tiling is even more obvious (which is bad) -- I'm closing this in favor of the other one.

**Pull request closed without merging**
