### PR TITLE
Revision to cobbychem v1

### PR DESCRIPTION
**Pull request by Surrealaser**
-Replaces organ damage with varying degrees of stamina and nutrition drain (hopefully driving more business to the chef) proportionate to amount of damage healed by these core chems:
Libital: Low stamina drain, high nutrition drain.
Aiuri: High stamina drain, low nutrition drain
Multiver: Moderate stamina and nutrition drain.

-Aiuri now counts as painful RE: mood.

Why: Allows use of core chems without long term consequences that are at best tedious and annoying to rectify, while still balancing them with material downsides. Also prevents utilization of core chems as stealth kill options with perfect plausible deniability (especially multiver).

### CODE REVIEW

**Comment by optimumtact** [comment]
no

**Comment by Surrealaser** [comment]
> no

Why?

**Comment by ExcessiveUseOfCobblestone** [comment]
the plausible deniability of multiver, or really any C2, decreases significantly with dose.

**Comment by Surrealaser** [comment]
@ExcessiveUseOfCobblestone you can apply it very quickly as a medborg for example, and they don't even know what you're injecting; I've used it to great effect in MalfAI rounds

**Comment by ExcessiveUseOfCobblestone** [comment]
which is true of any chem though? If I start injecting you with say chloral then you won't really know you've been hit with a bad chem until you're knocked out.

Medbay staff (including borgs) have, by nature of their job, more reason to be dragging a body around than others, so I don't see how a chem change ratifies that. You would just change the chemical used.

**Comment by Surrealaser** [comment]
@ExcessiveUseOfCobblestone I can't chloral someone instantly and without drawing suspicion is the thing though; using a needle always takes time, and is conspicuous. As is it's hard to get people to stand still long enough to administer disease cures when they see a needle at work with a perfectly valid reason

**Pull request closed without merging**
