### PR TITLE
Makes grille sprites slightly nicer

### PR DESCRIPTION
**Pull request by ChangelingRain**
Before; White mouse:
grille,you bitch
After; Grey mouse:
grille, you're amazin

### CODE REVIEW

**Comment by ChangelingRain** [comment]
There's a good chance you won't see shit because it's a very subtle change.

**Comment by Cheridan** [comment]
wow messing with a classic :put_litter_in_its_place:

**Comment by PKPenguin321** [comment]
Before/after pic pls

**Comment by coiax** [comment]
The greys are softer?

**Comment by Mercenaryblue** [comment]
Spot the difference?

The mouse!

**Comment by Bawhoppen** [comment]
grilles sprites haven't changed for like 12 years

**Comment by Shapsy** [comment]
You made the mouse black?

**Comment by pudl** [comment]
ugliest shit i ever done seen in my whole life

**Comment by ShadowDeath6** [comment]
Why must we play god?

**Comment by Jalleo** [comment]
I dont see the change can someone point it out?

**Comment by Chocobro** [comment]
@Jalleo slightly darker shading in the gaps between the bars

**Pull request merged**
