### PR TITLE
Removes chattering from toys

### PR DESCRIPTION
**Pull request by Niknakflak**
- Chattering is very annoying
- Each sound file is less than a second long and are really just a series of buzzes
- Saves us 300kb of data by removing it
- Brings back the charm of the simple click sounds to the toys

### CODE REVIEW

**Comment by kilkun** [comment]
NO

**Comment by jughu** [comment]
DONT DO DIS

**Comment by coiax** [comment]
Niknak grudge coding all my features away

**Comment by Niknakflak** [comment]
I'm not sure what you are talking about? I find this feature incredibly annoying and a waste of 300kb of annoying buzz sounds.

**Comment by kilkun** [comment]
>waste of 300kb
is this 1993?

you wanna talk about waste lets talk about the horrid state of expression optimization.

**Comment by ChangelingRain** [comment]
>300kb

That's basically an excuse.

**Comment by xxalpha** [comment]
300KB for a small feature is not acceptable.

**Comment by kilkun** [comment]
1GB is less than $1 these days

its fine.

**Comment by Incoming5643** [comment]
You should have waited until @coiax went on vacation or something first

**Comment by kilkun** [comment]
wow then i guess we should just remove all sound since it adds nothing to the game and takes up the majority of the codebase space anyways.

**Comment by Niknakflak** [comment]
nice argument

**Comment by ChangelingRain** [comment]
sound/effects/pope_entry.ogg is 252kb
sound/spookoween/bats.ogg is 376kb
sound/spookoween/ghost_whisper is 296kb

also I'd just like to point out that a similar argument to "Each sound file is less than a second long and are really just a series of buzzes" can be applied to all the instruments, all of which have more, and larger, sound files

**Comment by KorPhaeron** [comment]
I think it's kind of silly but we have hard this argument too many times, and multiple maintainers have now approved it, it's not worth the drama again

**Pull request closed without merging**
