### PR TITLE
Shuttle gibbing code improvements

### PR DESCRIPTION
**Pull request by Absolucy**
## About The Pull Request

Adds a resistance flag, `SHUTTLE_CRUSH_PROOF`, adds it to the existing things that have it, and adds it to the immortality spectres.

## Why It's Good For The Game

Gets rid of some hardcoded checks, making it easier for future code (or admins) to make things immune to shuttle crushing.

Also makes it so immortality spectres are immune to being shuttle crushed, as that kinda ruins the whole "immortality" thing...

## Changelog
:cl:
refactor: Improved shuttle gibbing code, adding a new resistance flag, `SHUTTLE_CRUSH_PROOF`.
fix: Immortality revival spectres can no longer be crushed by shuttles.
add: The ghost of Poly can no longer be shuttle-crushed, nor can anything incorporeal.
/:cl:

### CODE REVIEW

**Comment by deathrobotpunch** [comment]
give ghost of poly that flag so the crew has no way to get rid of him 😆

**Comment by SyncIt21** [comment]
Why make it a trait? Why not just a simple flag? You have a number of slots to choose from either `obj_flags` or `flags_1` or for your case the best is `resistance_flags`(maybe create a flag like `SHUTTLE_CRASH_PROOF`).

Storing traits takes up more memory compared to a simple bit flag.

**Comment by Absolucy** [comment]
@SyncIt21 Yeah, it could be a `resistance_flag`, I just thought a trait would be more versatile.

**Comment by SyncIt21** [comment]
>  I just thought a trait would be more versatile.

To this what i said was

> Storing traits takes up more memory compared to a simple bit flag.

So i would advice you to make it a flag instead of a trait. We gain no versatility from this.

**Comment by Absolucy** [comment]
Alright, will do.

**Comment by Absolucy** [comment]
Done. 

@deathrobotpunch you can close https://github.com/tgstation/tgstation/pull/81730, I rolled it into this PR

**Comment by deathrobotpunch** [comment]
> @deathrobotpunch you can close #81730, I rolled it into this PR

thanks

**Comment by san7890** [comment]
i got confused at why 1621 CI was failing so lets see if this resolves that

**Comment by san7890** [comment]
Nope it's a issue only detectable in 515

**Comment by Absolucy** [comment]
I'm confused, since it seems to be erroring here:

```
/obj/effect/abstract
	resistance_flags = parent_type::resistance_flags | SHUTTLE_CRUSH_PROOF
```

Even tho other pieces of code in master are doing the same thing, like here: https://github.com/tgstation/tgstation/blob/master/code/modules/surgery/implant_removal.dm#L87

**Comment by MrMelbert** [comment]
Alt test failures are a byond bug, we need to bump min compiler version to fix it (#81841)

**Review by Ghommie — APPROVED** [review]

**Pull request merged**
