### PR TITLE
Don't message admins when a grenade goes bang

### LINKED ISSUE #14934: Clusterbangs spam admin logs
Since the change to announce every grenade detonation (why?), every sub cluster logs going off, then then every single grenade part logs going off as well, resulting in giant walls of text for admins and an unreadable chat.

### PR DESCRIPTION
**Pull request by optimumtact**
Keeps it in the game log though (for investigations)

Fixes #14934

### CODE REVIEW

**Comment by TechnoAlchemisto** [comment]
Is this going to keep grenades being primed notifying us?

**Comment by optimumtact** [comment]
Yes grenade primes are still messaged to admins - I figured two notifications was over the top and this handily deals with the clusterbang spam

**Comment by MrStonedOne** [comment]
:+1:

**Comment by Buggy123** [comment]
I was the one who originally added this - does this open #8317 again?

**Comment by optimumtact** [comment]
@Buggy123 the location of an explosion is still logged to the game log, I simply removed the line that sends the admins an alert

So 8317 will still be solved as I only intended for it to be a log entry in case an admin ever needed to investigate the exact explosion locations

**Comment by KorPhaeron** [comment]
Thank you

**Pull request merged**
