### PR TITLE
Fixes a VV runtime

### PR DESCRIPTION
**Pull request by Core0verload**
I LIED. This PR contains no fixes, and probably contains a lot of bugs. Just don't spoil it to players until it's too late.

This PR adds ponies as April Fools only (triggered by AF event) roundstart playable race. Also there is a prob(15) that "human" race will switch to "pony" at pref save load. Because I just want to see server burn.

Ponies have a mutant color, colored hairstyles and tails. Styles are chosen randomly, color matches the hair color. There is a small chance to spawn with wings, alicorn, or both. Feel free to add those choices to player panel, I was simply too lazy to do that for an one-day event. Ponies hide clothing icons on them to avoid icons breaking, but don't hide belt or inhands. Ponies are banned from heads.

Ponies have a "pure friendship" reagent in them instead of blood. When injected in human it switches it's intent to help, displays random friendly messages and sometimes makes the human hug nearby people. Attention: friendship can be addictive!

This PR requires no config changes and will only enable itself on April Fools. All changed prefs will be reverted at the end of event.

### CODE REVIEW

**Comment by Bawhoppen** [comment]
like i said still want chat emotes for cutie marks

**Comment by Core0verload** [comment]
Feel free to implement them. I don't even understand what "chat emotes for cutie marks" means.

**Comment by Bawhoppen** [comment]
https://tgstation13.org/wiki/Emoji_cheat_sheet

emoji I guess is the term

**Comment by KorPhaeron** [comment]
Open april fools shit when its actually april fools

**Comment by duncathan** [comment]
Tbh I was excited to see what the fix was

**Pull request closed without merging**
