### PR TITLE
Bone Armor Sprites

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
learntoembedkor

If changing the body_parts_covered flags offends the spirit of the freeze I can remove that and do it later, it'd just not match with the new sprite otherwise

### CODE REVIEW

**Comment by TechnoAlchemisto** [comment]
stop having good sprites

**Comment by WJohn** [comment]
👍  aus sprites forever

**Comment by KorPhaeron** [comment]
They're not aus sprites but that is flattering I'll let her know you thought so

**Comment by Zilenan91** [comment]
Ash Walker bone warriors :+1:

**Comment by Cheridan** [comment]
changing the flags is fine

**Pull request merged**
