### PR TITLE
Fixes two riding datum runtimes

### PR DESCRIPTION
**Pull request by silicons**
saw this flooding server logs.

### CODE REVIEW

**Comment by optimumtact** [comment]
Shoudn't you see why these are running when ridden is null?

**Comment by kevinz000** [comment]
@optimumtact i don't know ask @Militaires

**Comment by optimumtact** [comment]
You're just papering over the runtimes, this isn't a fix, I shouldn't have to keep explaining this to you.

These runtimes are important because they tell us there is something wrong about how the code was intended.

You have to look at the whole system and make a holistic decision if it's valid for the values to be null at this point and then if not, go and find out why they are

**Comment by optimumtact** [comment]
You need to investigate and prove that these should or can be null at this point.

**Pull request closed without merging**
