### PR TITLE
Changes medkits contents

### PR DESCRIPTION
**Pull request by bigfatbananacyclops**
## About The Pull Request

Hi, i decided to add different and various tools to medkits, note that the only medkits i changed were burn, oxy, tox & brute, just those.

*Contents of BRUTE KIT changed, now contains:
-Three stypic patches of the original ones
-One gauze
-Changed, now haves a pill bottle containing 4 trophazole pills
-A salicyclic medipen injector
-Health analyzer

*BURN KIT
-Three sulf saud patches of the original ones
-Changed, now haves a medical spray full of rhigoxane
-A oxandrolone medipen injector
-Epipen
-Health analyzer

*TOXIN KIT
-Charcoal pill bottle (contains three pills)
-Three thializid syringes
-A potassium iodide pill bottle (contains three pills made out of 15u each)
-Pentetic medipen injector
-Epipen
-health analyzer

*OXYGEN KIT
-3 perf syringes
-Replaced dexalin pills with a salbutamol injector.
-Changed, now have a pill bottle containing iron pills of 30u, for bloodloss.
-Epipen
-health analyzer

ADDS
dexalin, kelotane, bicardine, potassium iodide & antitox pill (all 15u)
pill bottles of the chems mentioned above, the pill bottles contains three of them.
salicyclic acid, oxandrolone & pentetic acid syringe

## Why It's Good For The Game

I know trekchems were recently made unmixable and it may put you to question why i am placing them in kits.

 The toxin kit was changed to have just a bunch of charcoal pills, i don't think that could be considered a actual kit, a medkit is meant to have different and various tools to counter & treat the specific damage, a bunch of pills is just a pill bottle, i dont think it is a kit anymore, this is what the oxygen deprivation used to be before when it had a bunch of salbutamol pills, it was changed, and syringes work good, but i think it should have different tools to be used by people, different methods and ways to properly use chems on people, because a knowledged doctor would know not to spend the oxandrolone on a minor burn, so it will require some knowledge about which chem is better for what situation, or just skill.

The reason i added only 3 pills to those bottles is because i want to still encourage chemists to work, talking from personal experience, i used to just grab charcoal pill bottles and shove em in the fridge and have that checked, then i'd move one with other chems, i know it's really silly that a pill bottle has a really low amount if pills, even if it was 7 too, in reality, pill bottles would have around 50 pill bottles, its illogical it haves three and i would attempt to code a pill card so it haves some kind of logic.

I added tiers of different chems in each kit so they can all be used differently for specific severity of damage, trekchems are meant to be for minor, salicyclic, oxandrolone and pentetic for severe. I also added a different measure to reduce radiation levels in toxin kit, potassium iodide pills, the toxin kit is pretty much meant for both radiation & toxin.

I replaced the oxandrolone pill with a syringe, the reason i did that is so i can add different tools and not just a bunch of singular pills, 15u is still enough to heal severe burn damage, it can 60 burn damage and prevent you from going into a critical condition if you have burns above 50 damage, you then can use a silver saud patch to heal the rest of the burns.

## Changelog
:cl:
add: Adds 4 new pill types, 4 new pill bottle types, a rhigoxane spray type, three medipen types & four syringe types
tweak: Changed burn, brute, oxy & toxin kit contents,
/:cl:

EDITED, made some changes.
Kelotane pills replaced with rhigoxane medical spray in burn kit.
Bicaridine pills replaced with trophazole pills in brute kit.
Salbutamol pill replaced with iron pills in oxy kit.
second edit:
Dexalin pills replaced with a salbutamol medipen injector in oxy kit, to prevent them from being used for lexorin.
Changed toxin kit.
removed antitox & charcoal pills.
added instead three thializid syringes along with a charcoal pill bottle, contains three pills.

### CODE REVIEW

**Comment by bigfatbananacyclops** [comment]
also i added that ''peee pee poo poo' name accidentally, sorry, blame @imsxz

**Comment by necromanceranne** [comment]
I'm surprised you're using trekchems instead of some of the new chems. A spray bottle of the new burn chem and some of the new brute chem that requires food would be pretty good instead so as to provide consistency with what chemistry can produce and also get people familiar with those chems.

The new toxin chem requires dilution so it wouldn't be too great in a medkit so honestly I feel like charcoal probably should remain the staple chem in that kit. Antitoxin is kinda unnecessary. Potassium iodine pills are nice though.

Dexalin is a weird chem to me since it's robot exclusive. Is this to tackle blood loss safely? Maybe instead you should just have iron pills if that's the case. Perf is for any other case of oxyloss and then cryo is ideally how you would deal with heavy oxyloss from bleeding.

**Comment by bigfatbananacyclops** [comment]
I was actually considering to add a thializid iv drip to the toxin kit, but they were added recently so i didn’t want to touch them. I added dexalin pills so they can be used for minor oxygen damage, however, iron pills are not a bad idea. @necromanceranne

**Comment by Dawson1917** [comment]
Kind of a big buff to medkits but since the removal of sleepers they and medivendor items are responsible for 90% of healing. The added variety is good from a standpoint of being able to optimise healing when you're knowledgeable about the medical system but I doubt this will get merged because of the recent tirades against trekchems

**Comment by bigfatbananacyclops** [comment]
@Dawson1917 By big buff, do you mean like too many supplies for a kit, or efficiency, I limited the amount of pills so it still gives the chemist a job to do, it may have different chems. However, if we were talking about nukeops, i dont think it could probably buff them alot, nuke ops can buy a cheap syndie kit with synthflesh patches that goes through your suit, they have a combat injector as well, goes through suit, and still get burn and brute from other kits, if the nuke ops were to use the other chems they would have to take the hardsuit off in order to use syringes & pills, even if it can heal them efficiently when recovering in the ship, they still have sleepers and may have mediborgs, so there is no difference.

**Comment by Dawson1917** [comment]
Buff as in there's overall more supplies (3 brute patches and 3 15u bicardine pills in brute kits as opposed to 4 brute patches, and also salicylic but that and oxand are rarely used for being garbo) and some rarer reagents that you never get unless chemistry is doing their job, like the pentetic acid syringes. A singular 15u syringe of the stuff per toxin kit is going to do very little realistically but that a reagent previously inaccessible outside of chemistry exists at the start of the round might raise powercreep alarms for some. Singular salbutamol pills in oxygen kits strike me as unlikely to happen since there was a clear intention to replace salbutamol with perfluorodecalin, which might be fine considering oxygen kits are in 50% of the oxygen lockers strewn around the station. I still like this PR, but it clashes with the ongoing recent nerfs to medical

**Comment by ATH1909** [comment]
Expect doctors to raid the oxy kits around the station for JUST the salbutamol pills in them, since they are so much simpler/less of a hassle to use than perf syringes.

Make of that what you will.

**Comment by bigfatbananacyclops** [comment]
@ATH1909 Now that sounds like a meta issue that should probably be solved by either removing them from lockers, or making them rarer to be found. I would honestly expect a good player in medical to do that, and i would find it uncommon to happen, but they’ll probably collect only around 3-5 pills and waste their time. Salicyclic acid & oxandrolone arent pretty much garbo, they can do alot, theyre meant to be one use to treat severe damage and it can fix you out of that state, alternatively you can just use the other chems to heal, but oxandrolone and salicyclic is one use and fast heal, if you have 50 damage above it can heal 60 of the damage and work efficiently, i know its meant to be more accessible but it isnt a rare chem, realistically its already a recipes chem in NT, it just haves more complexity to be made, its, its not meant to be rare, burn kits right now have two pills of 24u oxandrolone, it works very well when you have extreme burns but as i said, I didn’t want to add a bunch of pills so i picked syringe form, and it still works well with 15u, it also prevents the pill from somewhat being used to OD someone. The kit only comes with one syringe and if it was tempted to be used to kill someone with od, they’d have to be fast while injecting and get two burn kits. The powercreep of meds right now are sprays and patches by the way, due to them being able to to through hardsuits, I wouldn’t call it powercreep, more like cheese. Medkits are not meant to be for a huge amount of people so, they’re more like for 3 people or a single person, even if they use up the oxandrolone, salicyclic or pentetic, they still have the other tools or meds.

**Comment by wesoda25** [comment]
Remove the pentetic acid and I’d say this isn’t half bad. It won’t be an issue for rads, but it will present a problem for traitor chemists and shit since pent is the greatest cuck all to toxins.

**Comment by bigfatbananacyclops** [comment]
@wesoda25 Probably, chems like lexorin, sulfonal, phlogiston, heparin are still very strong.

**Comment by Krysonism** [comment]
**Thializid** syringes could replace the anti-toxin, although this method of application doesn't heal as much damage as fast  as anti-toxin or charcoal(1 per tick + 3 per injection).

It still purges toxins slightly faster than anti-toxin and charcoal( 2 for the first 3 ticks, 1 for the next 37 ticks)

**Trophazole** and **rhigoxane** pills could be added to the kits instead of the trekchems, to no ill effect, but trophazole heals less on its own than bicard.

**Comment by Krysonism** [comment]
Another thing to keep in mind is that this PR makes lexorin ghetto craftable again.

**Comment by SkeletalElite** [comment]
I'd say switch the trek chems out for the new chems.

**Comment by bigfatbananacyclops** [comment]
@Krysonism you’re right, i might remove it, however, lexorin should’ve been nerfed instead of recipe changed, i was expecting a oxy healing chem would come too with the new chems.

**Comment by ExcessiveUseOfCobblestone** [comment]
cringe

**Review by Tlaltecuhtli — APPROVED** [review]
sounds good

**Comment by ExcessiveUseOfCobblestone** [comment]
@Tlaltecuhtli stop using the review mechanic to 2cents, you'll get banned for it.

**Comment by bigfatbananacyclops** [comment]
made some changes. EDITED, made some changes.
Kelotane pills replaced with rhigoxane medical spray in burn kit.
Bicaridine pills replaced with trophazole pills in brute kit.
Salbutamol pill replaced with iron pills in oxy kit.

**Comment by Krysonism** [comment]
> 
> 
> Thializid is lethal and there’s no way to treat liver damage, you just have to replace it.

Taking a full thializid syringe is only dangerous if your liver is about half dead.

**Comment by imsxz** [comment]
liver damage heals over time (0.1 every time liver processes)as long as you arent running around taking a shitload of it

**Comment by bigfatbananacyclops** [comment]
Removed the trekchems pills & pill bottles since they're being removed

**Comment by Krysonism** [comment]
I like the variety! 

If the maintainers think this is too big of a buff, there is always the option to remove a couple of the round start medkits to compensate.

**Comment by optimumtact** [comment]
im going to assume cobby meant no when he commented cringe

Take your trek chems and shove them right up your own butthole

**Comment by ExcessiveUseOfCobblestone** [comment]
Trekchems got removed from the PR, sorry I was sorta reviewing this with the user privately over discord conversations so it wasn't being auditable here.

**Review by ExcessiveUseOfCobblestone — COMMENTED** [review]
I can be sold on the T3s only if they're converted to single-use medipen so you have to use it all at once rather than being able to manipulate them with chemmaster (don't forget multiple medkits are provided roundstart).

**Comment by bigfatbananacyclops** [comment]
@ExcessiveUseOfCobblestone I was considering to make them medipens at the beginning, but then i started thinking, what if people uses them lethally to OD someone? maps spawn with atleast three medkits, so it is possible to OD someone with oxandrolone or salicyclic, i added salbutamol because it cant OD however but if you say so, ill do it.

**Comment by bigfatbananacyclops** [comment]
Added the category 3 medipens to the kits, by the way i noticed the rhigoxane yellow spray sprite would show up invisible, i couldn't find the issue so i replaced it with the large spray sprite meanwhile. i might fix that in another PR

**Comment by ExcessiveUseOfCobblestone** [comment]
OD is a feature and all medkits have a health analyzer

**Comment by ExcessiveUseOfCobblestone** [comment]
Todo: Subtype the oxy kits in lockers vs the ones in medbay and takeout the salbu for locker variants.

10u should be fine I guess until I BTFO all meds (tm)

**Pull request merged**
