### PR TITLE
New dirt sprites and jungle chasms

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
Ausops sprited these maybe he has pictures

### CODE REVIEW

**Comment by ExcessiveUseOfCobblestone** [comment]
> jungle chasms

Are you expecting them to do anything or just be like LOL DELETED like lavaland?

**Comment by KorPhaeron** [comment]
@ExcessiveUseOfCobblestone 

They drop you into lavaland

**Comment by XDTM** [comment]
aw ye it's still happening

**Comment by Fox-McCloud** [comment]
> posts PR for new sprites for a thing

>> Doesn't post pics

Korrrrrrrr 😛

**Comment by PKPenguin321** [comment]
Ban kor from not putting pictures

**Comment by lzimann** [comment]
add pictures

**Comment by Cuboos** [comment]
Post pics already

**Comment by KorPhaeron** [comment]
It's a brown square and the same chasms we have no but surrounded by a brown square

**Pull request merged**
