### PR TITLE
Update cigs_lighters.dm

### PR DESCRIPTION
**Pull request by gy1ta23**
## About The Pull Request
Fixes cheap lighter description

## Why It's Good For The Game

Before, reading the description of the cheap lighter would immediately ruin the player's immersion. If this change is enacted, players can play the game safely knowing that their immersion will not be ruined by a lighter.

## Changelog
:cl:
spellcheck: fixes cheap lighter description
/:cl:

### CODE REVIEW

**Comment by actioninja** [comment]
Aren't the cheap lighters actually free though

**Comment by gy1ta23** [comment]
Just checked, they cost ten credits

**Comment by gy1ta23** [comment]
A aaa

**Comment by gy1ta23** [comment]
OH GOD DAMN IT I LEAVE MY COMPUTER ON FOR 2 MINUTES AND THIS HAPPENS

**Pull request merged**
