### PR TITLE
Removes Lone Operative's starting Bulldog, gives him 8TCs more instead

### PR DESCRIPTION
**Pull request by Omni44**
## About The Pull Request

As in title
## Why It's Good For The Game

I think it's good for the game as loneop is fairly rare antag to get, and while that bulldog is cool, it basically makes player commit to working with weapon arbitrarily chosen by coderman. With lots of gear being basically exclusive to nukies, this will hopefully encourage people to experiment with loadouts more. I doubt it would tip the balance in favour of loneop too much.

## Changelog
:cl:
del: Removed Bulldog from loneop's starting gear
tweak: Added equivalent of bulldog's cost to loneop's uplink
/:cl:

### CODE REVIEW

**Comment by Fikou** [comment]
could you round it down or up to 30/35 tc so its not an ugly number

**Comment by IndieanaJones** [comment]
Better suggestion, take 1 TC away so they have 27 TC.

**Comment by Homingpenguins** [comment]
what do you mean an odd number? its divisible by 9, which practically makes it cursed. make it 29 instead, going by that logic.

**Comment by IndieanaJones** [comment]
> what do you mean an odd number? its divisible by 9, which practically makes it cursed. make it 29 instead, going by that logic.

I can't divide 27 by 2, so yeah, I will say it is an odd number.

**Review by ExcessiveUseOfCobblestone — CHANGES_REQUESTED** [review]
if its meant to be relative to the default value, define the default value.

**Comment by ExcessiveUseOfCobblestone** [comment]
that is not something i willing to merge without, please fix this.

**Comment by Jared-Fogle** [comment]
It's been 7 days--let us know if you make this change.

**Pull request closed without merging**
