### PR TITLE
Adds cigar cases

### PR DESCRIPTION
**Pull request by ghost**
cigars
Sprites from Nienhaus' sprite thread on the forums.

Adds three cigar cases. They can be acquired via a coin in a cigarette machine. They come in three flavors; Cohiba Robusto, Premium Havanian, and just regular premium. They contain seven cigars each.

Also removed the two Havanian cigars from the premium list (since you can just buy a case now) and ups the Robust Gold packets to 2 to compensate (and also because Robust Gold is fancy and you need more of it always).

:smoking: :man:

### CODE REVIEW

**Comment by Nienhaus** [comment]
Cool. :+1:

**Comment by Fox-McCloud** [comment]
:+1:

**Comment by pudl** [comment]
nienhaus can u pls resprite them to be smaller, one of my biggest issues with the cases on NT was their massive size. they covered shit on tables when you laid them down to look cool

**Comment by Nienhaus** [comment]
@pudl The size is because my friend requested them to show that they have all 8(I think that's how many it was) shown as much in the box. I'll try changing it when I get home over the weekend if I remember.

**Comment by xxalpha** [comment]
:+1:

**Comment by phil235** [comment]
You can't close the cigar case once it's open. Also, all cases accept all types of cigars which means you can fill a cohiba cigar case with havanian cigars but the case sprite will look like it has cohiba cigars.

**Comment by xxalpha** [comment]
That's because all fancy storage boxes don't close. He could add that functionality now.

**Comment by Xhuis** [comment]
@phil235: Logically, all cigars fit in there. There's the same issue with cigarette packets and lighters, where the lighter shows as a cigarette.

@xxalpha: I'll see what I can do, I guess. How do you propose it's done, alt-clicking? Object verbs?

**Comment by xxalpha** [comment]
attack_self calling update_icon and the update_icon doing the magic

**Comment by Xhuis** [comment]
ok i've spent a bit of time trying to get these boxes to close
it's just being difficult
there's no real reason to close them anyway besides just looking nice
if you can come up with a solution, make one and pr it to this branch
otherwise this is merge-ready

**Comment by Xhuis** [comment]
any reason this can't be merged

**Pull request merged**
