### PR TITLE
Space no longer gets hot except it actually works this time

### LINKED ISSUE #46621: SM burning from fusion heating up space?
Issue reported from  Round ID: 119561 (/tg/Station Terry [EU] [100% LAG FREE] [New-Dedi])

Reporting client version: 512.1479

So i was doing the first batch of fusion in a canister and i started building a chamber in the room above the incinerator (the map was metastation). I made a 2x2 (inside) room with reinforced floors, heat pipes and injectors surrounded by reinforced walls and one reinforced window with a grill. right near the window i made a hole to space so that the heat escaping from the window wont flood the station (the space tile was surrounded with atmos holofan)

i started the fusion, and it all went well for the first 5/10 minutes, but then the CE tells me that the space pipe is heating up

i was speechless because i couldnt see how my fusion that was far away and sealed up from the station could heat up the SM space loop

Any idea on why? and can someone fix this issue? cause i really want to make a fusion reactor with collectors array to make power

### PR DESCRIPTION
**Pull request by blessedmulligan**
## About The Pull Request
fixes #46621

Hopefully stops 'gas_mixture/immutable's from having their temperature changed without being immediately reset. Stops space from heating up and messing up the supermatter.

## Why It's Good For The Game

hot space bad
## Changelog
:cl:
fix: Space can no longer get hot. In particular, doing fusion near space tiles won't wreck the SM.
/:cl:

### CODE REVIEW

**Comment by willox** [comment]
I think you should check for gc_share like the other code does to avoid calling `garbage_collect` on non-immutable mixes unnecessarily.

Like this one:
https://github.com/tgstation/tgstation/blob/064ae62eeaa3990034f2bf818a27e1adfa9d3dcc/code/modules/atmospherics/gasmixtures/gas_mixture.dm#L350-L351

**Comment by blessedmulligan** [comment]
good catch

**Comment by Ghilker** [comment]
merge it please so that we can make real fusion reactor!

**Comment by optimumtact** [comment]
why does this work

**Comment by blessedmulligan** [comment]
it makes sure the sharer's temp is reset at the end of temperature_share() if it's immutable, which previously didn't happen.

**Comment by optimumtact** [comment]
Let it be known, superconductivity was a mistake

**Comment by PKPenguin321** [comment]
imagine making a fire so hot it literally heats up the entirety of the vacuum of space

**Pull request merged**
