### PR TITLE
Dials back the boxes [poll]

### LINKED ISSUE #12006: Cardboard box ! easter Egg shares a global cooldown between all boxes
@Incoming5643

### PR DESCRIPTION
**Pull request by Incoming5643**
There are no more random boxes

Maps now have two guaranteed spawns, one in maint and one in the cargo warehouse. You can still build more boxes yourself.

The ! easter egg can now only ever proc once per box. Once it's triggered that's the end of it.

Fixes #12006 

A guide to merging:

If you merge this:
Don't merge #12049
Don't merge #12015
You can merge #12023 but probably won't

Poll: https://tgstation13.org/phpBB/viewtopic.php?f=10&t=4785

### CODE REVIEW

**Comment by Incoming5643** [comment]
Pulls dedicated to cardboard boxes: 6

**Comment by KorPhaeron** [comment]
>The ! easter egg can now only ever proc once per box. Once it's triggered that's the end of it.

Bad PR

**Comment by Chocobro** [comment]
I mean you could just close #12015 yourself feller

**Comment by Iamgoofball** [comment]
>The ! easter egg can now only ever proc once per box. Once it's triggered that's the end of it.

:-1:

**Comment by Supermichael777** [comment]
> The ! easter egg can now only ever proc once per box. Once it's triggered that's the end of it.

:-1:

**Comment by Incoming5643** [comment]
please stop shitposting your downthumbered people are gonna maybe take it half seriously

**Comment by Iamgoofball** [comment]
we're serious, remove the once per box bit

**Comment by Incoming5643** [comment]
Alright then I'm confused. Are you folks rallying for old ! rules or do you want it gone too? Compromising on two fronts here.

**Comment by Anonus** [comment]
Once per box is BAD! Stay determined, keep it in!

**Comment by Iamgoofball** [comment]
@Incoming5643 

Old ! rules

**Comment by Incoming5643** [comment]
https://tgstation13.org/phpBB/viewtopic.php?f=10&t=4785

**Comment by Dorsisdwarf** [comment]
>The ! easter egg can now only ever proc once per box. Once it's triggered that's the end of it.

:-1: Acting like I can't see assistants in boxes sneaking into the armory as warden, then getting the ! easteregg when I finally spot them moving is the best

**Comment by Firecage** [comment]
If I knew how to do the thumbs-down icon, I would do it.

**Comment by phil235** [comment]
:+1: Although I'd prefer the "!" thing to be completely removed.

**Comment by Miauw62** [comment]
agree with phil

**Comment by Miauw62** [comment]
snakesnakesnaaaake

**Comment by Shadowlight213** [comment]
! is worth it when the Captain opens the box containing nuke ops

**Comment by Cheridan** [comment]
clip 2015-09-28 at 09 27 12

**Pull request merged**
