### PR TITLE
Rethemes the Necropolis

### PR DESCRIPTION
**Pull request by ChangelingRain**
:cl: Joan
tweak: The Necropolis has been rethemed.
/:cl:

There's one room inside it, containing Legion.

### CODE REVIEW

**Comment by ShizCalev** [comment]
tag = "icon-cracked_tile1 (*)";
icon_state = "cracked_tile1";

tag = "icon-pristine_block1 (*)";
icon_state = "pristine_block1";

on literally everything

reeeeeeeeeee

**Comment by ChangelingRain** [comment]
Yes I know that's what "generate icon states from directions" does, it sucks, but I can't easily remove them either

**Comment by Ergovisavi** [comment]
Brighten it up a little, maybe? I can barely see the gate.

**Comment by FantasticFwoosh** [comment]
Looks nice, it'd be also be nice if we could be getting some non-invincible aesthetic walls so we can rebuild the temple elsewhere as a reward for running the circuit and re-playing the boss rooms (if such a thing is ever feasable)

Oh, and if you gave the ashwalker hut a makeover too with said aesthetic non-boss walls that'd be dandy. It's their god and all, and technically this is their temple, handcrafted millenia ago by hundreds of millions of ash-walker slaves before some cataclysm wiped their civilisation out or something.

Carries a 'Apocalypto' vibe of forbidden temples and such, nice to see. Is this a prototype for planet-station vaults?

**Comment by KingPhilipIII** [comment]
I didn't realize ashwalkers were living in an old temple. But thats neat.

**Comment by GunHog** [comment]
So imposing. So dark. So much doom. I am very spook.

**Comment by GunHog** [comment]
@DoctoreMad please explain your :-1: !!!

**Comment by Supermichael777** [comment]
The necropolis is not so huge as to require millions, each of the pyramids was constructed by a few thousand workers in the fallow flood seasons over the course of a single lifetime (note: start your mega-tomb project early!) about 40 or 50 years with bronze tools. assuming they made it with at least that level of tooling (based on there armor) a structure of this size would be fairly similar.

Additionally based on the volcanism and high surface concentrations of metals i would suspect it was showered by debris from a nearby planetary or lunar collision triggering global seismic events.

**Comment by Hatfish** [comment]
demons invaded lavaland and built everything with hell magic, that's also why there's all that fantasy stuff everywhere you look.
fuckin nerds

**Comment by Grazyn** [comment]
"Lavaland" is just a volcanic region of the planet, there are other more pleasant biomes (jmad's "winterstorm" map will be set in the mountainous area) but minerals are only found there.

**Pull request merged**
