### PR TITLE
Revert "Medbay Changes (Box)"

### PR DESCRIPTION
**Pull request by lzimann**
Reverts tgstation/tgstation#21971

>The general reaction has been dislike.

If the general reaction has been dislike, what is the point of merging it?

### CODE REVIEW

**Comment by Thunder12345** [comment]
>I'll teach the admins not to run a poll when I ask

Grudge merging

**Comment by jughu** [comment]
The general are validhunters and murderboners

**Comment by WJohn** [comment]
give it some time. i don't understand why people hate map changes so damn much it's bizzare. learn the new ins and outs of the map and get an edge over everybody else, no? shouldn't you want that?

**Comment by Firecage** [comment]
I haven't personally noticed the general reaction being negative, except the minority who are mad because people has a higher chance of surviving.

**Comment by lzimann** [comment]
The side entrance is awful.

**Comment by jughu** [comment]
H U G B O X

**Comment by Arianya** [comment]
@lzimann Can you explain why its awful or?

**Comment by uraniummeltdown** [comment]
Give it a few days, run a few polls. It's not as terrible as you think, when it was testmerged for a bit ~5 days ago most doctors found it useful.

**Comment by Cyberboss** [comment]
My only grudge is against the side entrance. But its a big fucking grudge

**Comment by Arianya** [comment]
Seriously whats the big issue with the side entrance??

**Comment by Cyberboss** [comment]
Literally no other department has multiple entrances. Also I have enough trouble trying to keep the autism out and my floors clean as CMO already, this just makes it nightmarish.

**Comment by Arianya** [comment]
I mean all departments have multiple entrances via maintenance, all of them more secretive then these side doors.

**Comment by jughu** [comment]
Science has a side entrance from genetics and theres maint to genetics and roboics ???

**Comment by Grazyn** [comment]
I really don't like the top walls in the lobby replacing the windows, it's a minor change but it prevents plasma fire from spilling into the hallway once the firelocks go down. Every other department has a setup that allows fire to spread around the firelocks by burning through the windows.

**Comment by Cyberboss** [comment]
MAIN entrances

**Comment by PKPenguin321** [comment]
:-1: Give it more of a chance, and if the main issue is the side entrance, remove just that

**Comment by Cyberboss** [comment]
I will once this gets closed. The remainder of the changes are absolutely fine

**Comment by Incoming5643** [comment]
The directional windows on the front desk add a bizarre layer of security to what is essentially an optional roleplay post. Nowhere else are directional windows laced over tables like this (and directional windows in general are usually avoided). The Crew Monitoring Console cheapens the CMO's role, as that computer was one of the very few perks of taking that job. Removing the windows in front of the cryotubes increases the risks of someone getting stuck inside without anyone noticing.

**Comment by uraniummeltdown** [comment]
The directional windows+windoor on the desk were probably a mistake I'm in favor of removing those, but I think the front windows and the cryo windows are better replaced by walls, else Medbay's too transparent. Also, does anyone actually use the Medical Records console? There is another Records console next to the Sleepers anyway seems pointless having 2 of the same console a few tiles away from each other.

**Comment by Cyberboss** [comment]
@Incoming5643 Uhhh, both vendors dispense HANDHELD crew monitors. It was never limited to the CMO.

**Comment by RandomMarine** [comment]
There was a time when handheld crew monitors weren't even things.

Anyway >kneejerk PR

**Comment by lzimann** [comment]
It's a revert to something that wasn't even supposed to be merged.

**Comment by Incoming5643** [comment]
Handheld crew monitors were bad feature bleed too.

**Comment by Iamgoofball** [comment]
@lzimann Then maybe you should of run a poll when he asked

**Comment by lzimann** [comment]
No one asked me to run a poll though.

**Comment by XDTM** [comment]
Even with 4-6 portable crew monitors it's rare that a doctor notices your death on the sensor, and even rarer that he does something about it. Imagine if only the CMO could use the sensors on a static console.

**Comment by xxalpha** [comment]
Be wary of auto map reverts.

**Comment by Aloraydrel** [comment]
Remove the side doors and it would be fine tbqh

**Comment by Cyberboss** [comment]
@xxalpha As long as no other box changes get merged before this we're fine

**Comment by optimumtact** [comment]
I hope that my point about us being unable to gain feedback and hence acting in a vacuum has been appropriately taken on board.

**Comment by ChangelingRain** [comment]
fruit should not be trusted

**Pull request merged**
