### PR TITLE
Fixes bypassing cargo export values on minerals

### PR DESCRIPTION
**Pull request by Iamgoofball**
See title. People used this to get around our nerfs.

### CODE REVIEW

**Comment by Dorsisdwarf** [comment]
so coins are now useless again

**Comment by Grazyn** [comment]
Well they work as luxury shuttle ticket fare. Only diamond or higher though, unless someone fixed that bug that fails to check containers for money when boarding the shuttle

**Comment by coiax** [comment]
Lazy. Why not just have the vault just use the coin prices?

**Comment by SgtxRootbeer** [comment]
So this is how you make coins useless again

**Comment by octareenroon91** [comment]
Fucking make whatever three places materials coins work use the same system of values.

**Comment by lzimann** [comment]
make it use the mineral's value instead of removing it entirely

**Comment by Iamgoofball** [comment]
No. If you want to put coins in the budget, just export them properly.

**Comment by duncathan** [comment]
i agree with goofball

**Pull request merged**
