### PR TITLE
Kilostation: Gives Cargo a drone bay that isn't literally just maint (cargo + departures remap)

### PR DESCRIPTION
**Pull request by MrMelbert**
## About The Pull Request

This PR gives the cargo bay of Kilostation a drone bay that isn't half public maintenance. In the process, cargo itself has experienced some remapping and re-arranging, and so has the departures/arrivals lounge (and hallways around it). Pictures below (slightly outdated)!

<details>
<summary>Cargo now has a full on drone bay to their own instead of being half in maintenance.</summary>
  
image

</details>

<details>
<summary>The mailroom's been expanded slightly due to having to remove some maintenance in between. It now has a crate return belt for public use.</summary>
  
image

image

</details>

<details>
<summary>Cargo itself had to be expanded very slightly outwards into space.</summary>
  
image

</details>

</details>

<details>
<summary>The QM's office and the cargo office received some TLC in the meantime.</summary>
  
image

</details>

<details>
<summary>Because the cargo shuttle had to be expanded out into space, the escape shuttle dock had to as well, to avoid shuttle collision. Departures has been expanded very slightly, and the sec checkpoint was made into an actual customs office. </summary>
  
image

</details>

Other misc. changes:
- Intercom coverage in front of the mailroom improved, hydroponics had some wall mounts shifted due to this
- Various changes to the departures/arrivals hallway and the hallway in front of cargo

## Why It's Good For The Game

Kilo's cargo was really really needing of some TLC as it was showing its age. Multiple new features were added but the bay itself never changed, just stuff was shoved in. The Drone Bay was completely open to anyone with maint access which lead to tiders stealing drone supplies often. Now, the cargo bay as a whole has been brought into the new age.

## Changelog

:cl: Melbert
add: Kilostation: Cargo / Drone Bay remap, departures expansion.
/:cl:

### CODE REVIEW

**Comment by ShizCalev** [comment]
Mind tossing some pics up? Diff isn't loading.

**Comment by MrMelbert** [comment]
> 
> 
> Mind tossing some pics up? Diff isn't loading.

There are pics in the PR body, I put them in the collapsibles to keep it readable!

**Comment by ShizCalev** [comment]
image
Not quiiiiiite sure how I feel about this overlap tbh

**Comment by ShizCalev** [comment]
image
Camera in the disposals room is backwards

**Comment by ShizCalev** [comment]
image
Drone room as well

**Review by Maurukas — CHANGES_REQUESTED** [review]
Looks fantastic. Minor issue with the powergrid here: the lower half of cargo needs to be wired into the power line from upper maint now.
image

**Pull request merged**
