### PR TITLE
Allow tgui input() to be 0, fix SMES components

### LINKED ISSUE #14965: Can't adjust SMES input/output
The pop up window when you try to change the input/output says: New input target (0-0). If you type any number it will just set it to 0. Using arrow buttons will set it to 0 as well and grey out the arrows.
Also deconstructing the SMES won't return a capacitor, but you need it to rebuild.

This was on ministation btw

### PR DESCRIPTION
**Pull request by neersighted**
Fixes #14965

### CODE REVIEW

**Comment by MrStonedOne** [comment]
Note, this bug can allow for accidental singulo/tesla releases, should be simi quick merged

**Comment by Razharas** [comment]
How capacitor did end up removed at all?

**Comment by duncathan** [comment]
neer was trying to blame razh but I set him straight
https://github.com/neersighted/tgstation/commit/d9162b653c3dd850d9a2697e06de708bc7dba996

**Comment by neersighted** [comment]
I ded
rip

**Pull request merged**
