### PR TITLE
Adds new emoji.

### PR DESCRIPTION
**Pull request by harmonyn**
Imgur

Feast your eyes on syndie, carp, dosh, liz, fedora, medal, and the most important emoji of all: the eggplant emoji.

:cl:
rscadd: Seven new emoji have been added to hasten the death of the English language.
/:cl:

### CODE REVIEW

**Comment by optimumtact** [comment]
assume the icons are original work?

**Comment by bgobandit** [comment]
nah fam they are lightly condensed from existing icons

**Comment by installgen2** [comment]
I give this my approval

**Comment by LanCartwright** [comment]
image
image
image
image
image
image
image
image
image
image

**Comment by neersighted** [comment]
:+1:

**Comment by stal888** [comment]
you're a big eggplant

**Comment by LanCartwright** [comment]
image

**Comment by JJRcop** [comment]
I'm gonna take this time to mention that a lot of the other emoji are condensed versions of existing stuff, so this is not a problem.

**Comment by optimumtact** [comment]
I was just making sure they weren't ripped from any other font sets

**Comment by optimumtact** [comment]
@LanCartwright can you not shit up the issue tracker with useless comments thanks

**Comment by bgobandit** [comment]
suck my :eggplant:

**Comment by KazeEspada** [comment]
@optimumtact I found his comment funny and normally I think hes an asshole.

**Comment by optimumtact** [comment]
What's funny about the eggplant emoji repeated like 40 times

**Comment by Aloraydrel** [comment]
:eggplant:

**Comment by stal888** [comment]
🍌

**Comment by lzimann** [comment]
why is there an eggplant emoji

**Comment by KazeEspada** [comment]
@optimumtact I meant the second one with the news article.

**Comment by kevinz000** [comment]
>NO TABLE
Bgo did you get killed by a changeling?

**Comment by bgobandit** [comment]
tables don't really translate well to emoji mekhi

**Comment by Bawhoppen** [comment]
still waiting for :chelp: and :co2:

**Comment by neersighted** [comment]
What the fuck is :co2:

**Pull request merged**
