### PR TITLE
Holosignification

### PR DESCRIPTION
**Pull request by DrDiasyl**
## About The Pull Request
Cleans up holosigns sprites and moved them to a separate DMI file from "effects.dmi"

https://github.com/user-attachments/assets/24471537-f80c-4bdb-95d9-b9adacd4a2fb

Adds a new ability to Engineering and Security holosigns, they now can be opened from afar with their creator. You can still always break them or pass on WALK.

https://github.com/user-attachments/assets/12502d71-0c5d-447e-9d6e-c2ca773e57e3

Now 2 Security holosign creators are in the SecVendor.
Security holosigns now take 2 seconds instead of 3 to create.

Holosigns no longer block projectiles.

Also improved the holosigns code with better cooldowns and such.
## Why It's Good For The Game
Holosigns, especially Security ones are underused due to them taking too much time to create for not that much and also being available only with research.

Adding 2 to SecVendor, cutting the time for creating a Security holosign, and giving it a neat ability to be opened (although anyone can pass a closed one on a walk) can make it more viable for Security to engage with crew interestingly like building checkpoints or making blocks when pursuing a criminal. Criminals will have to now think about evading such checkpoints.

Making sprites cleaner, especially adding the words "SEC" on the Security holosign and "HAZARD" on the Engineering holosign will now convey the message of not passing it at least a little stronger.

It was weird for a flimsy holograph to be able to stop ALL projectiles, even lasers. This created more confusion than being used for "tactical" advantage, especially when barrier grenades are better for shielding in firefights.
## Changelog
:cl: DrDiasyl aka DrTuxedo
add: Security and Engineering holosigns can now be opened with their projector by clicking them from afar
add: SecVendor starts with 2 Security holosigns
qol: Holosigns don't block projectiles anymore
qol: Security holosigns now take 2 seconds to create instead of 3
image: Janitor, Security, Medical, and Engineering holosigns now have cleaner sprites
code: Holosigns now use proper cooldowns instead of the world.time
spellcheck: Holosigns and holosign creators' descriptions give more information now
/:cl:

### CODE REVIEW

**Comment by Iamgoofball** [comment]
I like everything but the holographic wet floor sign; I feel like that's a downgrade, the spinny sign was cooler.

**Comment by DrDiasyl** [comment]
> I like everything but the holographic wet floor sign; I feel like that's a downgrade, the spinny sign was cooler.

By its looks, it was animated by literally squashing the wet floor sign sprite with anti-aliasing on. Which was rather messy.

**Comment by Wallemations** [comment]
Did you not touch the atmos & medbay ones?

**Comment by DrDiasyl** [comment]
> Did you not touch the atmos & medbay ones?

Medbay one is the blue one on the left.
Atmos one is untouched.

**Comment by Wallemations** [comment]
> > Did you not touch the atmos & medbay ones?
> 
> 
> 
> Medbay one is the blue one on the left.
> 
> Atmos one is untouched.

Shouldn't the medbay one have an icon?

**Comment by Eronymun** [comment]
> > > Did you not touch the atmos & medbay ones?
> > 
> > 
> > Medbay one is the blue one on the left.
> > Atmos one is untouched.
> 
> Shouldn't the medbay one have an icon?

I was going to say, I thought it was the engineering hologram wall (engineers get two different holograms).

**Comment by DrDiasyl** [comment]
> Shouldn't the medbay one have an icon?

Well, it only flashes a biohazard symbol when it denies a person.

**Comment by Wallemations** [comment]
> > Shouldn't the medbay one have an icon?
> 
> 
> 
> Well, it only flashes a biohazard symbol when it denies a person.

When it's not flashing that symbol, maybe it should have a soft + sign so people know it's a medical thing at a glance

**Comment by DrDiasyl** [comment]
> > > Shouldn't the medbay one have an icon?
> > 
> > 
> > Well, it only flashes a biohazard symbol when it denies a person.
> 
> When it's not flashing that symbol, maybe it should have a soft + sign so people know it's a medical thing at a glance

image
image

**Pull request merged**
