### PR TITLE
Adds a riot foam dart option to hacked autolathes (Winter Thaw 2017)

### PR DESCRIPTION
**Pull request by ghost**
_This feature was created as part of the [Winter Thaw of 2017](https://tgstation13.org/phpBB/viewtopic.php?f=10&t=9307) regardless of consensus or if it gets merged._

:cl: Xhuis
add: Riot foam darts can now be constructed from a hacked autolathe.
/:cl:

One dart requires 1000 metal. A box requires 50000 metal (40 darts). Individual darts are cheaper because \>carrying around individual bullets. Values may need adjusting.

### CODE REVIEW

**Comment by lzimann** [comment]
how the fuck does an autolathe make a box anyway

**Comment by jughu** [comment]
>put pen in every one of them and you created a 10 stam + 5 brute weapon altough... 40 pens be quite the hunt

**Comment by Kromgar** [comment]
riot foam darts? as in these are supposed to be used to stop people?

**Comment by Robustin** [comment]
Theyre meme foam ammo that does a small amount of stamina damage, you spray them at someone and they think its harmless, suddenly theyre slow/stunned and getting murdered... I guess. 

Theyre still just a meme.

**Comment by Xhuis** [comment]
It's pretty significant. 25 stam is nothing to laugh about.

**Comment by MrPerson** [comment]
Please don't encourage people to carry around individual darts. That's obnoxious and retarded.

**Comment by Supermichael777** [comment]
use screwdriver for 25 brute

it makes the toy gun all to real

**Comment by Supermichael777** [comment]
also buy box
autisticly emptie and shove darts back in
profit

**Comment by FantasticFwoosh** [comment]
Beanbags that stun off force collision are technically better, but this works as a alternative (beside using shotgun darts full of tiring chem from a emagged soft drink dispenser) in non harmfully bringing them down via stamina.

**Comment by anconfuzedrock** [comment]
this kills pens in darts

**Comment by jughu** [comment]
Secret cargo buff

**Pull request merged**
