### PR TITLE
Abduction Update 2.5

### LINKED ISSUE #9137: Abductor baton seems to stop working
I don't know why but it woulden't work on any mode in any armor mode
Revision 0611eacfbc273d7a135e3b96d09c4126cd09a017 
other gear worked perfictly.

### LINKED ISSUE #9194: Ayyylien shuttle table on the left is not correctly connected.
They both appear to be facing north, leaving a gap in the middle.

### PR DESCRIPTION
**Pull request by AnturK**
I probably should have waited a moment with that one.
- Adds make abductor buttons on traitor panel
- Fixes clotheless surgery
- Fixes #9194
- Makes probing into baton mode, to keep it consistent with stunbatons. Fixes #9137 
- Adds buying spare gear for experimentation points. Currently you can buy baton,helmet,silencer and scientist tool.
- Makes kidnapping Ian possible
- Adds tech-origin to abductor items
- Fixes abductees not being displayed at roundend

### CODE REVIEW

**Comment by WJohn** [comment]
Could you fix #9194 in this PR too?

**Comment by GunHog** [comment]
All of the Abductor tech needs to have origin techs. If the Abductors are unrobust and lose their equipment in a fight against the crew, the crew should be able to deconstruct them for mad Science levels! It is highly advanced alien technology, surely that would mean something?

**Comment by AnturK** [comment]
Sure, i'll add some tech levels to the gear

**Comment by AnturK** [comment]
For the love of god never mix spaces and tabs for indentation

**Comment by AnturK** [comment]
About the tech values : anything that's below top-tier is not really a reward with our current system.

**Comment by peoplearestrange** [comment]
There's an issue with monking Abductors. If they are monkied they have no way to get back to the ship or ever be de-monkied. I'm not sure if other "alien" mobs can be monkied (such as lings, blobs, shadowlings) but it seems a little implausible that their DNA would be the same as humans.

Also what does probing actually do with the "Baton tool"? Having to not be on help intent is kinda counter intuitive, but I'm assuming thats what you're saying is being changed in the PR?

**Comment by AnturK** [comment]
Merge conflict fixed. Not sure why but the floor icon file was reverted some way back.

**Pull request merged**
