### PR TITLE
Removes stock borrowing

### PR DESCRIPTION
**Pull request by Iamgoofball**

### CODE REVIEW

**Comment by Kraseo** [comment]
Big words used by a big baby.

**Comment by Iamgoofball** [comment]
@Kraseo fuck you and die

**Review by Razharas — APPROVED** [review]
Well coder himself thinks it was bad idea i can only agree

**Review by ChangelingRain — APPROVED** [review]
Goof does not appear to be aware he does not have complete control of everything.

**Comment by Iamgoofball** [comment]
i hate you all including myself and hope we all die in a massive fucking fire

**Comment by optimumtact** [comment]
For your continued insults and general poor attitude your contributions to this repo are no longer welcome.

Don't come back.

**Review by francinum — APPROVED** [review]
Nobody actually used this shit.

**Comment by ExcessiveUseOfCobblestone** [comment]
ma44 did, which is why we're here.

**Comment by francinum** [comment]
@ExcessiveUseOfCobblestone I mean nobody of value

**Comment by ExcessiveUseOfCobblestone** [comment]
@francinum tbf he can't even use it anymore without copping a ban for ban-evading, as he's currently perm'd from Supply jobs.

**Comment by ma44** [comment]
>tfw only way for anything dealing with cargo to be removed is for me to abuse it

**Pull request merged**
