### PR TITLE
[READY] Moves Genetics to the Science department and makes Geneticist a science job

### PR DESCRIPTION
**Pull request by TheVekter**
## About The Pull Request

This PR moves the Genetics Lab to Science and converts the job to work purely under the RD as opposed to the CMO and RD. This is part of the research overhaul I'm working on, see the following thread for context:

https://tgstation13.org/phpBB/viewtopic.php?f=9&t=24991

This is part of trying to split Scientist into a few separate jobs instead of it being a mad dash for whatever department you want. Xenobiologist is next.

Metastation:
image

The space this took up on Meta is being taken by an expansion to the morgue. Considering replacing it with some patient rooms for cloned players to get dressed/grab their stuff instead of having to drag their body all around that tiny little cloner room. @EdgeLordExe had a concept for a job that would use that space, so they'll likely be using it at some point.

Important to note is that **the cloner is NOT leaving the medbay**. Doctors and EMTs will now be responsible for cloning, as the cloner pretty much runs itself.

TODO:

- [x] Metastation
- [x] Boxstation
- [x] Deltastation
- [x] Pubbystation
- [x] Kilostation
- [x] Donutstation (I actually didn't have to change Donut because the mad cunt who made it put Genetics right next to Science.)

## Why It's Good For The Game

As it is right now, Scientists kind of just scramble to grab whatever job they want. With other departments like Engineering and Medical being split into multiple jobs, there's no reason Scientist shouldn't be. This will help keep things focused directly on experiments in Genetics instead of them being pestered about fixing someone's defects, all of which can be done either through chems or surgeries now.

## Changelog
:cl:
tweak: Geneticists are now purely under the purview of the Science department. They will report directly to the Research Director.
tweak: Moved the Genetics lab to the Science wing, replacing the Experimentor and associated lab. This is a change on Metastation, Boxstation, Pubbystation, Deltastation, and Kilostation.
tweak: Geneticist access updated to grant access to the Science wing.
tweak: Changed the Geneticist's outfit item sprites and bags to match their correct color.
del: Removed the Experimentor from all labs as part of a full R&D rework.
/:cl:

### CODE REVIEW

**Comment by TheVekter** [comment]
It's worth noting that I'm not removing the Experimentor code. Might have a place in the rework I'm working on.

**Comment by mrhugo13** [comment]
IMO with this change, genetics clothing should probably be changed to something from the science/scientist color palette,

**Comment by EdgeLordExe** [comment]
thanks a lot for that. i already designed the psychologist office while still having genetics. If this gets merged ill definately use that space for psychiatrist office

**Comment by TheVekter** [comment]
> IMO with this change, genetics clothing should probably be changed to something from the science/scientist color palette,

Considering this, but the dark blue is pretty solidly their color.

**Comment by trollbreeder** [comment]
I suggest merging chemistry into science aswell, and merging geneticist, roboticist and chemist into scientist. Trim the fat!

**Comment by JJRcop** [comment]
hudgeneticist in icons/mob/hud.dmi and idgeneticist in icons/obj/card.dmi are blue, which is for medical jobs

**Comment by TheVekter** [comment]
> hudgeneticist in icons/mob/hud.dmi and idgeneticist in icons/obj/card.dmi are blue, which is for medical jobs

Thanks. I'll resprite these tonight.

**Comment by BadSS13Player** [comment]
Does Science really need more sub-departments?

**Comment by TheVekter** [comment]
> Does Science really need more sub-departments?

Yes. I honestly think it does. Part of what you're not realizing is that toxins mixing is going to Atmos as part of their job in the full overhaul. That will only leave Robotics (who can also handle nanites), Genetics, and Xenobiology. I intend to make XB into its own job as well.

**Comment by CAPTTLasky** [comment]
Is there any chance you could make the room less square?

**Comment by CAPTTLasky** [comment]
Also I would think about working with Edge on moving the department since he wants to add psychiatry to medbay and that could fill up the spot in genetics.

**Comment by Arathianen** [comment]
I am in full agreement with this change and it was part of the stuff I had suggested as a heavy science main.

By the way, I think CMO should have sci (and if possible, genetics) access. Not sure if this would fit with this PR though.

**Comment by TheVekter** [comment]
The conflicts are because someone merged the Meta brig changes before this. Shouldn't be hard to fix.

> By the way, I think CMO should have sci (and if possible, genetics) access. Not sure if this would fit with this PR though.

I'm not really sure I follow the logic here. CMO won't have any domain whatsoever over Genetics after this change - it's purely a Science job, and thus under the RD.

> Is there any chance you could make the room less square?

I can try, but the way maint is laid out nearby kind of restricts my creativity on it.

**Comment by Jordie0608** [comment]
you ok there vekter

**Comment by TheVekter** [comment]
Never rebase master to your branch, kiddos.

**Comment by TheVekter** [comment]
I realized something while scooting all the genetics clothes over to `rd/` - someone, at some point, changed the color of the jumpsuit and jumpskirt to a sort of dark teal, but never updated the jacket or backpack. Hence, nobody probably realized it had been changed as nobody ever takes their damn jacket off. I went ahead and re-sprited the bags and will finish the coat later today.

image
Here's a comparison, with the jacket still using the old blue.

**Comment by carlarctg** [comment]
kills experimentor for no raisin :-1:

**Comment by TheVekter** [comment]
> kills experimentor for no raisin

Sorry, mate. Meta has somewhere I might could have squeezed it, but sure as hell not in Kilo or Pubby. It's still in the code if someone wants to make it better, or I might find a way to work it into the new R&D.

**Comment by Shadowflame909** [comment]
isn't there an active PR to make the experimentor useful?

I thought you made it Vekter

**Comment by Bawhoppen** [comment]
I'm pretty sure that scientist used to be separated into different jobs on /tg/, but were ultimately unified into one because there supposedly wasn't that great of a reason for them to be separated in the first place. 
I imagine that it mainly had to do with the mobility for scientists to switch between different areas of science as people got bored/died/banned, rather than being locked into a single specific one. It was also probably kinda pointless to have them divided since people could just go to the HOP roundstart and get all of the department's access anyways.

**Review by kriskog — CHANGES_REQUESTED** [review]
Only checked metastation structural mapping stuff

Fix these pipes, also the one miscolored door tile.
image

Disposal dead end, also this used to be genetics mail sorting and its missing from new genetics.
image

Cable dead end
image

Why the loop? Doesnt seem to connect to anything
image

**Comment by TheVekter** [comment]
Good catch, also apparently I'm map conflicted again so I'll fix it while I'm cleaning that bullshit up.

> isn't there an active PR to make the experimentor useful?
> 
> I thought you made it Vekter
> 
> Yeah what was the point of this, and it's apparently still being worked on part 2 #48238

Yeah, that was my project. I talked it over with a few maintainers and kinda realized it maybe wasn't the healthiest direction to take things in. I feel like making point generation less of a focus and instead pushing towards requiring specific progress for each department is going to be way better and easier to balance in the long run.

**Comment by PKPenguin321** [comment]
Far as I knew they already were part of science, and them being vaguely related to medbay on top of that made them more unique. I'm not sure what this PR is out to do, and there's no reasoning in the OP. What's up with that?

**Comment by TheVekter** [comment]
> Far as I knew they already were part of science, and them being vaguely related to medbay on top of that made them more unique. I'm not sure what this PR is out to do, and there's no reasoning in the OP. What's up with that?

The reasoning is in the thread I linked, but the basic idea is threefold:
1) When departmental tech comes out, having jobs straddle the line and report to multiple heads will be confusing, as, in this case, geneticists would have to decide which department their research points go to. This simplifies that by putting them in, what I think, is the most logical department for them - yes, they handle stuff dealing with the human body, but it's significantly more a science than anything medical related.
2) The next PR I'm doing is going to split Science into a few different jobs and I'd rather move Genetics to Science than leave it with nothing but Roboticist and Xenobiologist.
3) It's always bugged me that two heads have control over one department, especially when one of them, the CMO, arguably doesn't really have anything to do with it aside from Genetics being located in Medical.

So tl;dr simplification

**Comment by PKPenguin321** [comment]
>When departmental tech comes out, having jobs straddle the line and report to multiple heads will be confusing, as, in this case, geneticists would have to decide which department their research points go to. This simplifies that

Why is this bad? What good does simplifying it do? Having a meaningful choice seems more appealing.

You can list genetics as a science job without actually moving it to science. It's already a science job as it is, and that's worked fine for years. Most maps put science just across the hall from genetics anyways, like meta and box.

Two heads having say over one sub department is unique and has lead to good conflict in the past, so I don't like that that's being removed either.

**Comment by TheVekter** [comment]
> Two heads having say over one sub department is unique and has lead to good conflict in the past, so I don't like that that's being removed either.

I can't honestly say that I've ever seen a situation where this has been a thing. If it comes up, it's not often enough for it to really matter based on what I'm doing.

> Having a meaningful choice seems more appealing.

Except it doesn't, since I can already imagine Medical getting all pissy that Genetics is using all of their research for Science instead of them, something this system's supposed to prevent.

> You can list genetics as a science job without actually moving it to science. It's already a science job as it is, and that's worked fine for years.

"It's always worked for years" isn't a reason to not make a change. This frees up more room in Medical for other jobs, like @EdgeLordExe's Psychiatrist job.

**Comment by PKPenguin321** [comment]
>This frees up more room in Medical for ... Psychiatrist job.

This is a tangible reason I can get behind. Thanks

**Comment by Bawhoppen** [comment]
first paramedic, next psychiatrist

we yog now

**Comment by TheVekter** [comment]
Box is up, gonna spend the rest of this weekend doing the other maps.

MapDiffBot works now, just check it.

**Comment by trollbreeder** [comment]
Please keep scientist unification.

**Review by kriskog — DISMISSED** [review]

**Comment by StonebayKyle** [comment]
I don't care too much about where the geneticist goes, but I do not want to see the scientist job split up. I don't see reasoning about why it's a good idea in here or on your forum post, aside from "make lit like the other departments." I'll save most of my complaints for the associated post and(?) PR, though.

**Comment by davethwave** [comment]
new paramedic stuff conflicting I guess.

**Comment by cacogen** [comment]
I do like your overall idea (though it will make the competition to roll xenobio stiff). I don't like moving genetics to science though. Can't explain why, historical bias I guess. I used to think the split department thing was retarded but I made my peace with it a long time ago and now it feels like part of the game to me. It used to be geneticists would be expected to drop what they were doing to clone people, but I guess that's handled by doctors more nowadays (as well as random crew/borgs, that hasn't changed). The inconsistency between generic "scientists" (these only exist in fiction, scientists work in specific fields) and the specific medical jobs also never made sense to me. Again I've made peace with it. But that's not to say I wouldn't like to see it changed.

I think a more strategic way of handling this from the player's point of view would be to make the jobs independent first, and then it will make more sense to add geneticist to the "collection". You could argue there's overlap between what MDs do and what roboticists do (replace lost limbs), yet they work in separate departments.

**Comment by TheVekter** [comment]
> I don't care too much about where the geneticist goes, but I do not want to see the scientist job split up. I don't see reasoning about why it's a good idea in here or on your forum post, aside from "make it like the other departments." I'll save most of my complaints for the associated post and(?) PR, though.

Yeah, this can be discussed more in that PR. I've just always found it quite silly that there's one major job for that department that does everything but all the other departments have specialized variants.

> You could argue there's overlap between what MDs do and what roboticists do (replace lost limbs), yet they work in separate departments.

I'm actually planning on doing away with this - going to make a variant of borg arms that are just prosthetic limbs that can be printed at Medical. They're already the go-to for replacing organs, why is this a responsibility that Roboticists have?

**Comment by TheVekter** [comment]
I ended up having to do Pubby a little different because the layout in Science is pretty cancer on there. I just co-opted some of the available maintenance space for the Genetics office, so now it's the only map left with an Experimentor on it. You're welcome I guess.

Also if this passes Travis we're good to go.

**Review by actioninja — CHANGES_REQUESTED** [review]
Mapping feedback:
Meta:
Bit barren and square. It works though.
Box:
Gee bill, *three* terminals?
Same as the other, bit barren and square.

Delta:
Odd placement, but works. Pretty closely matches the rest stylistically.
Medical area looks pretty odd now by comparison.

Donut:
lol donut

Kilo:
I like this one and don't have any complaints.



Pubby:
I actually like how you crammed in genetics, even if it's a little awkward.
Roundstart gondolas in medical is a no-go, as much as I like the concept. Gondola meat turns other people into gondolas, and so on. Just begging for griefing. If you want to make them a special subtype that doesn't drop gondola toxin meat, I'll hesitantly allow it.
This would be a good spot for a chemistry lab.

Code review to follow.

**Review by actioninja — COMMENTED** [review]
code looks fine, neutral review to avoid dismissing the map review

**Comment by TheVekter** [comment]
> Mapping feedback:
> Meta:
> Bit barren and square. It works though.
> Box:
> Gee bill, _three_ terminals?
> Same as the other, bit barren and square.

I'll add some decals to spice them up a bit, I suppose. It's hard to not make things in either of these blocky.

> Delta:
> Odd placement, but works. Pretty closely matches the rest stylistically.
> Medical area looks pretty odd now by comparison.

It does, but I'm pretty sure Edge is still planning on putting his psych thing there, so he'll fill the room out better than I did.

> Donut:
> lol donut

lol donut

> Kilo:
> I like this one and don't have any complaints.

Thanks, I'm actually really proud of how this came out. I originally thought there wasn't any way I could do it given the room, but I made it work.

> Pubby:
> I actually like how you crammed in genetics, even if it's a little awkward.
> Roundstart gondolas in medical is a no-go, as much as I like the concept. Gondola meat turns other people into gondolas, and so on. Just begging for griefing. If you want to make them a special subtype that doesn't drop gondola toxin meat, I'll hesitantly allow it.

Reeeeeee gondolas are cool and we don't see them enough but you're right so I guess I'll make them dogs or some shit

> This would be a good spot for a chemistry lab.

Out of scope (though a good idea! Maybe I'll do that.)

**Review by actioninja — APPROVED** [review]

**Comment by actioninja** [comment]
I'm not seeing a decent argument against this.

Movement of genetics here frees up room in medical for new coming jobs like psychologist, as well as on maps that do not have a chem lab yet a chem lab. Genetics never made sense in medical, once upon a time they were supposed to manage cloning but those days are very long gone with free MD access to the cloner. Even then cloning is more a job that makes sense for MDs to be doing with it being "geneticist responsibility" more of a archaic formality that got dispensed with.

The whole dual department thing is a somewhat reasonable concern, but as stated I don't think I've ever even seen that come into play.

Scientist should have been broken up a long time ago. The way it is now is just the ultimate excuse for scientist being the dumping ground for shit like nanites and circuits that have zero crew integration and don't make sense as a full job. Requiring new large features like this to *properly be their own* job would be a massive step forward.

# Redditors are severely disabled and huff farts

**Comment by Bawhoppen** [comment]
@TheVekter Maybe I missed something but I can't find the BEPIS on the new Metastation version in the Mapdiffbot

**Comment by TheVekter** [comment]
Unless I fucked something up, it should be in the firing range room.

**Comment by TheVekter** [comment]
It's not, I blame merge conflicts. I'll fix it.

**Comment by Bawhoppen** [comment]
@TheVekter I think it would be a better fit in the nanite lab or maybe the break room instead of the firing range (unless you mean you carved out a new section next to the firing range)

**Pull request merged**
