### PR TITLE
Customization in its prime!

### PR DESCRIPTION
**Pull request by ExcessiveUseOfCobblestone**
Every form of object has the **POTENTIAL** to be customized in name and description.

This would allow things like structures [See: Quantum Pads] to be renamed and described if they received `unique_rename = 1`

### CODE REVIEW

**Comment by ExcessiveUseOfCobblestone** [comment]
UGH WHY

**Comment by XDTM** [comment]
you deleted obj/weapon

i think it's not happy

**Comment by ExcessiveUseOfCobblestone** [comment]
t-t-there we go

**Comment by Aurantiaco** [comment]
CUSTOMIZING MY **DOG**

**Comment by optimumtact** [comment]
This is a step too far IMO

**Comment by ma44** [comment]
ma44 has renamed nuclear authentication disk to cash lemon

**Comment by ExcessiveUseOfCobblestone** [comment]
I had plans to put this in just obj/item as per Remie's request, but I figured [as mentioned] that this would highly benefit quantum pads as well as future structures.

Again, this does not give every object the rename/description editing ability [it's off by default], but does provide the framework should someone want to give the ability to their [object] later down the road.

**Comment by RemieRichards** [comment]
I agree with this, so long as it's only activated in places that make sense.
eg:
quantum pad -> "totally safe guys I swear"

**Comment by optimumtact** [comment]
Well, okay then

**Pull request merged**
