### PR TITLE
Revert "Removes left inhand files, automatically mirrors inhands"

### PR DESCRIPTION
**Pull request by ChangelingRain**
Reverts tgstation/tgstation#22032
This Doesn't Fucking Work
you can't just flip these
literally, you can't
seriously
i'm not kidding

### CODE REVIEW

**Comment by Incoming5643** [comment]
well wait a minute there's a difference between "doesn't work" and "does work, just is applied incorrectly"

**Comment by KorPhaeron** [comment]
Weird, it worked with the ID I was testing with

**Comment by ChangelingRain** [comment]
it also looks super ridiculous and I don't know how to fix it without outright reverting it

**Comment by ChangelingRain** [comment]
ids have tiny sprites so maybe you didn't see the issue

**Comment by Supermichael777** [comment]
the issue is its not swaping E and w when its inverting them

**Comment by KorPhaeron** [comment]
I only tested when facing north/south, I guess that'd be why.

@optimumtact @RemieRichards 

Any ideas to make west/east work or should we just revert?

**Comment by ChangelingRain** [comment]
you'd pretty much have to have a program to do it, given that the process to swap the handedness of a sprite is a little more involved than just flipping it, even discounting any sprites that, by definition, will have differences that can't be flipped.

**Comment by RemieRichards** [comment]
you would have to redraw the mob every time they changed dir. (or atleast store a ref to all those images and change their matrices, which still requires a partial redraw)
Hint: that's not happening.

**Comment by KorPhaeron** [comment]
Guess we're stuck with this then

**Comment by optimumtact** [comment]
Just set the transform matrix correctly based on mob direction, it's not difficult

**Pull request merged**
