### PR TITLE
Pulse Pistol Recharge Addition

### PR DESCRIPTION
**Pull request by Steelpoint**
This PR allows Pulse Pistols to be placed into a recharger to recharge them when they run dry.

The issue with Pulse Pistols is that the moment you run dry with it, the weapon becomes useless. In some cases this is a downgrade for the ERT. At least Energy Guns can be recharged. 

This alteration should give Red Alert ERT more staying power.

:cl: Steelpoint
tweak: Pulse Pistols can now be recharged.
/:cl:

### CODE REVIEW

**Comment by Bawhoppen** [comment]
are you sure it wasn't a bug because they used to be able to

**Comment by optimumtact** [comment]
You're doing okay so far steelpoint, stay well grounded

**Comment by kevinz000** [comment]
this was intentional but good change

**Comment by Steelpoint** [comment]
I think this was a undocumented change Paprika made when he made a lot of changes to the ERT a year or so ago. I've only noticed this issue recently and I think the Pulse Pistol is not so powerful that it needs to be heavily restricted in recharging.

Not to mention only red alert ERTs get Pulse Pistols, which are a admin only event, so I think this is a acceptable change. Several admins have expressed at times how under powered the red alert ERT are for what they tend to be called in for.

**Comment by Jordie0608** [comment]
Actually it was way back in https://github.com/tgstation/tgstation/commit/69924a15bef0628f11be0c563c6fc1f908b5fea3#diff-422486af7203a2035b746ac4fe55c104R43

**Comment by GunHog** [comment]
That change does not seem to be documented in the PR; Perhaps it was a botched conflict fix?

**Review by Cyberboss — APPROVED** [review]

**Pull request merged**
