### PR TITLE
Makes garbage collection of gases actually work most of the time.

### PR DESCRIPTION
**Pull request by SyncIt21**
## About The Pull Request
This is molar accuracy
https://github.com/tgstation/tgstation/blob/d1af6d9dcf58733fee767c9779b10e96dfd51dee/code/__DEFINES/atmospherics/atmos_core.dm#L55
This is how we quantize moles of a gas
https://github.com/tgstation/tgstation/blob/d1af6d9dcf58733fee767c9779b10e96dfd51dee/code/__DEFINES/atmospherics/atmos_mob_interaction.dm#L14
And this is when gases are actually garbage collected
https://github.com/tgstation/tgstation/blob/d1af6d9dcf58733fee767c9779b10e96dfd51dee/code/modules/atmospherics/gasmixtures/gas_mixture.dm#L74-L75

**The Problem?**
 `<= 0` is way too strict and rarely happens in game(not saying it doesn't happen at all but very rarely). Thus gases are not garbage collected most of the time because we have `0.0005` moles of some gas lying around just taking up memory doing nothing.

While this is not particularly harmful it is actually VERY DANGEROUES for sensitive atmos machinery like the super matter shard and it can cause the player to see 0 moles of gas on a turf when you use the gas analyzer. In this setup all the vents are off & scrubbers are in full expanded siphoning mode

Screenshot (202)
Doesn't make sense right?

,If you VV analyze the gas on the turf you can see a very tiny amount of gas present on the turf
Screenshot (203)

Do the math. try quantizing `0.000583`
Answer =` 6.000000000000001E-4`
Is it `<= 0` ?. Nope so no garbage collection occurs

Now let's take an real life example.

**Meet Dan**
 Dan is a dumb noobie first time atmospheric technician who has been asked too install a super matter shard in the engine room. After pumping the pipes full of protonitrate to see if the pipes work he begins siphoning the room to drain out all the gases so he can install the shard inside. 
He has been told that Proto Nitrate can cause the shard to activate so it's very important there is no trace of it left in the room, `Dan` uses his long ranged gas analyzer on the turf to ensure there is no proto nitrate on the turf, after making sure there is
 `0 moles`[deceptive] of it left he begins to install the shard. Watch what happens next

https://user-images.githubusercontent.com/110812394/236784309-9412c03d-ba8c-4fb2-8d7c-40557c3b5ca2.mp4

Dan was a poor victim of floating point inaccuracy. Rest in peace

**How to make sure you don't end up like Dan?**
From a player stand point there is nothing you can do, You can test the pipes using an inert gas like N2 before pumping in Proto nitrate but why must you take the long route? It's much easier to do this from a coding stand point

`if(cached_gases[id][MOLES] < MINIMUM_MOLE_COUNT)`
`MINIMUM_MOLE_COUNT = 0.01`

So now when the number of moles of gas falls below 0.01 the gas is automatically removed thus improving performance and saving people from Dan's fate. No need to quantize at this point to account for floating points, it's relatively faster

## Changelog
:cl:
fix: gas analyser displaying 0 moles of gas left on the turf 
fix: gases not getting garbage collected due to floating point inaccuracy
/:cl:

### CODE REVIEW

**Review by LemonInTheDark — CHANGES_REQUESTED** [review]
Tile to tile sharing is an important part of how this function is used, but it matters the most to pipe to pipe sharing.

The most common method of moving gas over pipes is by using pressure. 
It's most important for hot gas, since well it'll have a very high pressure. We very much do not want this hot gas to delete itself as soon as it moves, because only a tiny fraction of it is moving over.

This is why the value is so low currently. We don't want to delete gas in a way that people will notice.
Leaving it around in comparison is less of a big deal, since it doesn't just like break fusion and other high heat things.

The value is actually down to its original low right now, used to be e7 because old fusion was fuckin stupid #57634

I'm not willing to lower it further without solid evidence that it won't just start deleting gas at our highest achievable temps.

If that's a roadblock (and I think it might be), then the problems you bring up here would be solvable with less aggressive rounding on very small numbers (if we would round to 0, instead display the nearest non 0 value), and a minimum threshold applied to the supermatter and things like it. This is how gas reactions work if you notice, could just steal the constant from them

**Comment by SyncIt21** [comment]
Ahh your right damn.  High pressure gases would move very small amount of moles lesser than this threshold and would delete itself(sorry for repeating what you said I'm just understanding this now).

Is there a way in game to fully clear a tile of its gases  without any coding changes? Or is the only alternative to make the supermatter not so sensitive, Maybe make it start reacting only when there is MINIMUM_MOLE_COUNT of gases available?

Thoughts?

**Comment by SyncIt21** [comment]
Also I will test the minimum mole transfer limit in game using the HFR . If we can still move gases around at fusion level 6 using the best fuel mixture possible ( hypernob and antinob ) then it should be safe to merge this.
If not then I'll close this immediately

**Comment by Pickle-Coding** [comment]
It is quite known that the supermatter is dangerous in a void, and it makes sense. The supermatter produces plasma and oxygen which quickly puts it into a hostile state if there isn't a bunch of gas to lower their composition.

The only case where it's safe in a void is when there is literally 0 gas to process, causing a singularity that breaks the math, and if the energy is 0, so no gas production. It would make sense in that condition to process as if it was in a plasma oxygen mixture if it's in a void, as that is its natural state, but that is an uncommon condition.

I don't see why the gas analyzer rounds so heavily when it could just be displayed in scientific notation. Could just be based on significant figures instead.

**Comment by SyncIt21** [comment]
> it's in a void, as that is its natural state, but that is an uncommon condition

Creating that void is the problem , that is very uncommon and I don't know how to physically achieve that in game without a coding change.

Maybe making the supermatter process only when there is above 0.01 moles of a gas present is the best solution,  also another thing I haven't mentioned is that supermatter runtimes with divide by 0 errors in this 0 mole environment, so putting a minimum threshold would also fix that runtime.

Yeah I'll go in that direction, I'll transform this whole PR into a supermatter one

**Comment by LemonInTheDark** [comment]
> Ahh your right damn. High pressure gases would move very small amount of moles lesser than this threshold and would delete itself(sorry for repeating what you said I'm just understanding this now).

You don't need to apologize. Ended up here because of a failure of documentation on my part. This should have been clearly spelled out somewhere, and it wasn't. 
We could in theory raise the threshold for turfs, since they have a subtype, but that does make me slightly uncomfortable cause of things that share into turfs.

This was more a failure of info sharing then a disagreement of principles, your ideas sound fine, I look forward to em.
The constant was an appeal to tradition btw, if you want to tweak it and things don't break horribly then I'd be on board with that too.

**Comment by SyncIt21** [comment]
> > Ahh your right damn. High pressure gases would move very small amount of moles lesser than this threshold and would delete itself(sorry for repeating what you said I'm just understanding this now).
> 
> You don't need to apologize. Ended up here because of a failure of documentation on my part. This should have been clearly spelled out somewhere, and it wasn't. We could in theory raise the threshold for turfs, since they have a subtype, but that does make me slightly uncomfortable cause of things that share into turfs.
> 
> This was more a failure of info sharing then a disagreement of principles, your ideas sound fine, I look forward to em. The constant was an appeal to tradition btw, if you want to tweak it and things don't break horribly then I'd be on board with that too.

I actually wanted to focus mostly on the supermatter delaming in vacuum so i looked around and saw this solution would suffice. But yeah when dealing with atmos stuff, I mostly have no idea what i'm doing, thank's for the insight

**Pull request closed without merging**
