### PR TITLE
FAMILIES 5.0: Original Lore Edition

### PR DESCRIPTION
**Pull request by Iamgoofball**
## About The Pull Request

Families has been completely written to be original content across the board.
Security has been integrated into Families in full. Security now counts as a Family.
Three new Families have been added, old Themes have been reworked and remastered, and two new Themes have been added.

dreamseeker_IO45Jpc7IE

https://user-images.githubusercontent.com/4081722/177399147-eea6284d-b5b2-40a5-8827-0bf6ca5b89e7.mp4

## Why It's Good For The Game
The goal of these changes:
Resolve all of the bad gameplay from subpar themes.
Properly integrate Security into Families to reduce administrative burden and to properly separate true neutral crew from station-aligned crew.
## Changelog

:cl:
refactor: All of Families has been rewritten to be original content.
refactor: Security has been integrated into Families in full as a Family.
add: Audio has been added for every Families theme radio broadcast.
refactor: Families is now Common Core lore compliant.
add: Three new Families have been added, old Themes have been reworked and remastered, and two new Themes have been added.
/:cl:

### CODE REVIEW

**Comment by Stonetear** [comment]
Any chance we can get he ball to make you have an outline or glow, or something?  Last time I played football families, we used a potted plant as the ball since it has great visibility in the chaos.

**Comment by Iamgoofball** [comment]
I could probably make the football glow, yeah. I'll look into it.

**Comment by Mothblocks** [comment]
Sent a message about this privately but we don't plan on continuing Families development

**Comment by Feasel** [comment]
That's lame.

**Comment by Mothblocks** [comment]
This is your announcement

**Comment by Iamgoofball** [comment]
thanks for eroding my trust in the admins again, very cool

**Comment by BrandonSmith6** [comment]
> Sent a message about this privately but we don't plan on continuing Families development

Any reason why? I would like to know the reason for rejecting good content without even pointing out anything wrong with it.

**Comment by Mothblocks** [comment]
It was sent as a DM to them but Goof reposted the message I sent them here if you want to look: https://ptb.discord.com/channels/326822144233439242/326831214667235328/995810673604968550

**Pull request closed without merging**
