### PR TITLE
Remove multiverse from wizard

### PR DESCRIPTION
**Pull request by lzimann**
Hopefully it's the right way to remove it from wizard

:cl:
:rscdel: Removed multiverse war from wizard
/:cl:

### CODE REVIEW

**Comment by ChangelingRain** [comment]
thank god holy shit

**Comment by GunHog** [comment]
FUN REMOVAL :-1:

**Comment by KorPhaeron** [comment]
If it's bad why is it taken more than half the spells checkmate athiests

**Comment by Lumipharon** [comment]
People like to do bad things.

**Comment by PKPenguin321** [comment]
:skull: RIP :skull:

**Comment by Zilenan91** [comment]
rip in shit the memes are too strong for a normal item

**Comment by KorPhaeron** [comment]
@Zilenan91 

It's not a normal item, it's 4/5 of the wizards spell slots.

If a wizard decides to trade his round for highlander (and it is defintely his round, because the entire thing is about him killing everyone), why is that bad?

How is multiverse any worse than x5 summon events/guns/magic?

Hell how is it worse than an ei nath/MM wizard camping lockers?

**Comment by Zilenan91** [comment]
Because it's such an easy way to fuck the round. You spawn it, and suddenly comms go completely silent because everyone stabbed everyone else to death.

**Comment by KorPhaeron** [comment]
Wizard exists solely to fuck the round though

**Comment by Zilenan91** [comment]
Yeah but with almost every other item he has to put actual effort into it, this is just fire and meme and it gets old after 3 wizards do it in a row.

**Comment by KorPhaeron** [comment]
>summon X
>effort

**Comment by KazeEspada** [comment]
Eh, the guns can be turned against you. And only like 5 crew members become antags, wasting 4 slots on it, gets you about 20. The memesword makes 100% of the crew antags.

**Comment by xxalpha** [comment]
>summon X
>good

**Comment by kevinz000** [comment]
NO

**Comment by Anonmare** [comment]
Eh, Multiverse sword shares the load. Let Wizard rounds be maximum memes if the Wizard wants, least shit happens instead of fucking stealth wizard

**Comment by Dorsisdwarf** [comment]
Multiverse sword should gib the wizard, fail his objective, and disqualify him from multiclone for the whole round.

**Comment by Shadowlight213** [comment]
Remove it from wizard until we get fucking antag huds for multiverse.
The sheer amount of ahelps for people getting killed by their own clones because they look NOTHING ALIKE is ridiculous. The entire thing is terribly implemented.
If you want to have wizard have highlander, than give the wizard the highlander button. Not the shitty multiverse one.

**Comment by KorPhaeron** [comment]
>Remove it from wizard until we get fucking antag huds for multiverse.

This is a fair condition actually go ahead and remove it I'll re-add it if I ever do HUDs (not very likely)

**Comment by Razharas** [comment]
Time to nerf wizard

**Comment by Niknakflak** [comment]
Thank god

**Pull request merged**
