### PR TITLE
Ups the player and station name length limits

### PR DESCRIPTION
**Pull request by Iamgoofball**
:cl: Iamgoofball
tweak: Station and Character names are now allowed to be longer.
/:cl:

I think they could use a buff in length, as I've seen captains have pretty creative names get cut in half and the joke ruined, and the name limit is really fucking small like come on goddamn

### CODE REVIEW

**Comment by optimumtact** [comment]
Limitation breeds true creativity

**Comment by Iamgoofball** [comment]
let's limit ourselves to 16x16 why dont we

**Comment by Cheridan** [comment]
Also, if your input is greater than the limit then it should just error out, instead of doing the message and then just cutting it off.

**Comment by GeneralGoose** [comment]
@Iamgoofball sprtites? no no
go back to ascii

**Comment by evsey9** [comment]
merge it

**Comment by Firecage** [comment]
I don't see why the station need needs to be longer than 50 characters. There's no logical reason for it to be that long, unless someone wants to be a meme.

**Comment by Archie700** [comment]
@Firecage

>goofball

What do you think?

**Comment by MrStonedOne** [comment]
The old limit of 26 is too small, 52 how ever is too much. just do 40.

**Comment by Jalleo** [comment]
No 42 for those references.

**Comment by Cheridan** [comment]
Yeah I agree that 52/100 is too far in the other direction.

**Comment by optimumtact** [comment]
42/80 should be fine

**Pull request merged**
