### PR TITLE
Fixes bus ruin

### PR DESCRIPTION
**Pull request by 81Denton**
This fixes the bus ruin, the citrus fruit is in the driver's seat now

### CODE REVIEW

**Comment by Nickkoranda** [comment]
Clearly a powergaming nerf, no more roundstart cherry bombs from ruins. Could also use more references to other maintainers.

**Comment by MrDoomBringer** [comment]
@Nickkoranda the cherry bomb is there it just got moved

**Comment by Nickkoranda** [comment]
sorry i have the iq of a stick

**Comment by Qustinnus** [comment]
spaceninja spawn landmark on one of the seats for ninja :^)

**Comment by ATH1909** [comment]
> spaceninja spawn landmark on one of the seats for ninja :^)

Or just a dead ninja corpse if you don't want to add more ghost role spawners.

**Comment by Qustinnus** [comment]
it was a maymay

**Review by SpaceManiac — APPROVED** [review]

**Pull request merged**
