### PR TITLE
Removes prisoner crash ruin from codebase

### PR DESCRIPTION
**Pull request by coiax**
It's admin disabled, I don't want to get in the habit of having to
support disabled map content. I've never seen it loaded by an admin
either.

No changelog, because it's already not in rotation on our servers.

- Also removes the "gym" entry from the blacklist, because that got
removed ages ago.

### CODE REVIEW

**Comment by kevinz000** [comment]
normally i'd err on removing ruins for being "unused" but this time i feel like this is the right choice for this, as all it was was a ghost role that aimed to get to the station and grief.

**Comment by FantasticFwoosh** [comment]
All migrant type ghost ruins (where there is nothing to keep them there) have more or less a mechanical objective to get to the station

The fact this was a antagonist doing so wasn't great.

**Comment by RandomMarine** [comment]
In a perfect world, the objective would be "go to the station and roleplay". But there's always at least one fuck that only cares about valids.

**Comment by Iamgoofball** [comment]
:-1:

i get yelled at when I remove content we added that admins threw a hissy fit over and disabled, why does this PR get a pass?

**Comment by FantasticFwoosh** [comment]
@Iamgoofball shh shh, now goofball, people are just a little bit touchy about stuff, that's all.

**Comment by BeeSting12** [comment]
the prisoner ruin was pretty good

**Comment by lzimann** [comment]
@korphaeron

**Comment by lzimann** [comment]
It was never good.

**Pull request merged**
