### PR TITLE
CEV-Eris 3/4 matchbox sprites. Also personally resprited cigar boxes.

### PR DESCRIPTION
**Pull request by Ghommie**
## About The Pull Request
Dunno whoever resprited the matchbox first, traced their existence in the commit history back to the day their repo was full russian and couldn't bother using a translator. Also their cigar boxes sprites are a tad too big imo, and hold about 8 cigars instead of 5.

## Why It's Good For The Game
~~Soulless~~ Better 3/4 top-down sprites.

## Changelog
:cl:
imageadd: CEV-Eris matchbox sprites.
imageadd: Resprited cigar boxes.
/:cl:

### CODE REVIEW

**Comment by cacogen** [comment]
if you made a sprite uglier than the original, would it have more soul?

**Comment by PKPenguin321** [comment]
Looks terrible, way too rectangular. All of these are strictly downgraded. Side note, was 3/4ths ever intended for held objects? I thought it was only for map objects.

**Comment by PKPenguin321** [comment]
image
but seriously this is awful, looks like a minecraft block

**Comment by Ghommie** [comment]
Topdown is also intended for held objects (prime example most boxes and non-rusty toolboxes), most items just don't use the old cavalier view, so it's slightly less relevant.
But yes, I see how the cigar box sprites could use some improvements, thanks for the review.

**Comment by cacogen** [comment]
these could be better but the old sprites are nothing to write home about and i support the change to 3/4

**Comment by Jordie0608** [comment]
Cigar box does look like a block. Maybe some interior detailing or shading would help?
Do you want to try that now or later?

**Pull request closed without merging**
