### PR TITLE
Emag can no longer be spammed on shuttle console

### LINKED ISSUE #21140: Emag spams escape shuttle
Emagged shuttle messages appear as many times as clicked

I don't know how it handles the timer internally but it could lead to abuse where the shuttle launch time could be extended

### PR DESCRIPTION
**Pull request by Cyberboss**
Fixes #21140

:cl: Cyberboss
fix: Emag can no longer be spammed on shuttle console 
/:cl:

### CODE REVIEW

**Comment by pudl** [comment]
THIS DOES NOT NEED A CHANGELOG

**Comment by optimumtact** [comment]
this needs a changelog

**Comment by CyberbossJHCB** [comment]
I NEED AN ADULT!!!!

**Comment by Cheridan** [comment]
This doesn't need an adult.

**Pull request merged**
