### PR TITLE
Spacebattle Rework

### PR DESCRIPTION
**Pull request by MMMiracles**
I mean it still kinda sucks but now its slightly less of a loot pinata. 

Ranged mobs will now drop the syndicate-pinned variant of their weapons. Still allows potential mass-access to weapons but now at least you need a plasma cutter and a spare pin to use them.

Melee mobs will not drop their eswords/eshields on death. Apparently the syndicate wised up and added some sort of self-destruct mechanism to their energy weapons for their operatives.

Reduced the total mob count. In exchange, I added a few of those shiny mech mobs in their place. I hope you brought an ion rifle!

In turn of the new lack of immediate weapons, I've added an armory cache to the back section of the ship surrounded by r-walls and protected by the few Nanotrasen personnel left alive. There's probably a door control to get in if you really don't feel like welding down r-walls.

Placed and moved around some awaystarts around, mostly to help so walking out the immediate door will probably not end in immediate death for some positions.

### CODE REVIEW

**Comment by Iamgoofball** [comment]
you mapmerged right

**Comment by MMMiracles** [comment]
@Iamgoofball I did. I touched up the side asteroids so they're less of a god-awful blocky mess, which is probably a chunk of the edits.

**Comment by Iamgoofball** [comment]
Ah, makes sense.

**Comment by KorPhaeron** [comment]
>Reduced the total mob count

Please edit the syndir ships according. There os currently exactly one sleeper/chair/pod etc to account for every mob on the map and how they got there

**Comment by MMMiracles** [comment]
@KorPhaeron i did not anticipate that much thought being put into the mission.

**Comment by KorPhaeron** [comment]
I poured my heart and soul into this awful series of empty hallways full of loot

**Comment by Cheridan** [comment]
that's why he's design lead

**Comment by MMMiracles** [comment]
i apparently only added two less syndicates when i re-did them. 

can I just say the extra 2 chairs are excess thats a lot of work to change.

**Comment by Buggy123** [comment]
Bu-but muh loot piles :-1:

**Comment by KorPhaeron** [comment]
There is a specific number of chairs/sleepers for normal ops vs chairs/sleepers for space suit ops as well, the mission has the deepest lore

**Comment by Shadowlight213** [comment]
@KorPhaeron Holy shit. That's impressive

**Comment by Shadowlight213** [comment]
@mmmiracles I'd suggest taking a look at the space syndie mobs as well. Them dropping nuke op hardsuits is kinda powerful.

**Comment by Jalleo** [comment]
Xcom fragments for the shields to make NT variants when?

**Comment by TheNightingale** [comment]
They kind of need to drop usable weapons on death. Like this, if you go through the gateway with anything but the entire Armory or a self-recharging gun, you're going to have a bad time; the melee mobs are bad enough (they block all projectiles), but if you can't take their shields and swords to fight the rest, that's going to be quite difficult. Will the NT personnel in the Armory cache attack you if you approach them? And what exactly is in there?

**Comment by MMMiracles** [comment]
@TheNightingale Cache has some laser weapons, ranging from generic laser rifles to some better things. Its fair to assume given the situation on the ship that they'd probably KoS anyone trying to break into their armory/safe haven.

Also I moved spawn points for the sole purpose of making it so its more likely you'll be put in an area where you can go past the death mobs and obtain some sort of weapon before dying to them.

**Comment by LanCartwright** [comment]
No offense but this is an good awful idea.

Awful for the fact you're removing reward for beating an away mission, and good because this somewhat balances it.

Aside from this, removing loot is generally awful in my opinion.

**Comment by RemieRichards** [comment]
@LanCartwright stop reading github, go to bed.

**Comment by tkdrg** [comment]
@KorPhaeron should probably be the one to have the final say on this

**Comment by MMMiracles** [comment]
@KorPhaeron Is this up to your deep-lore standards?

**Comment by KorPhaeron** [comment]
I guess it doesn't really matter since the away mission sucks anyway, I will always have my memories of stupid detail attention

**Comment by LanCartwright** [comment]
actually hack apart half the stuff. i'm tired of seeing everyone with c20rs, eshield esword, nukeop armour all the time

**Comment by Shadowlight213** [comment]
@MMMiracles isn't the current spawn point for the away mission in the room directly above the exit gateway? With the walls being deconstructable, all you need is some basic tools to get out. Don't even need to fight the mobs.

**Comment by MMMiracles** [comment]
@Shadowlight213 Yeah, unless multiple people have huge issues with this I don't see the big problem with it. I hid all the actual non-pinned weapons behind r-walls and blast doors, guarded by more ranged mobs. You can probably escape by slipping past mobs but you won't get anything decent out of it.

This is done by the way just sayingggg.

**Comment by tkdrg** [comment]
@KorPhaeron merge it or break it

**Comment by KorPhaeron** [comment]
Well it probably cant make it worse

**Pull request merged**
