### PR TITLE
Removes Birdstation and associative files

### PR DESCRIPTION
**Pull request by Niknakflak**
Removes Birdboat station

I dislike it but I don't have super duper strong feelings one way or the other since it only comes up if an admin sets the map directly or if the preference voting rarely decides to set it and even then most times an admin will change the map just because birdboat is birdboat.

Some notable issues with birdboat so far
- Not maintained
- Atmos is broken
- It explodes every round because nobody knows how to stabilize the super matter shard ever.  The map is literally a timebomb everytime it's run.
- Spiders every round

### CODE REVIEW

**Comment by MrStonedOne** [comment]
your pr doesn't compile bird boat station.

rejected.

**Comment by coiax** [comment]
:-1: for removing fun

**Comment by Niknakflak** [comment]
Working on it

**Comment by kyrahabattoir** [comment]
:-1:

**Comment by Cheridan** [comment]
The map author has an almost fascinating obsession with potted plants. They're in the AI upload, they're in freaking tcomms, they block airlocks in hallways. I guess that's where the boatbirds are meant to live, or something?

**Comment by Imagebard** [comment]
Happy little potted plants

**Comment by Incoming5643** [comment]
It also has far more cardboard boxes than boxstation.

**Comment by ChangelingRain** [comment]
There are 108 potted plants on birdboat.
There are 110 cameras on birdboat.

There are 220 cameras on boxstation.
At birdboat plant density, boxstation would have 216 potted plants.

**Comment by KorPhaeron** [comment]
Literally my favourite map

**Comment by Zilenan91** [comment]
NO

**Comment by Core0verload** [comment]
-1 ultra snowflake map to maintain. :+1:

**Comment by ike709** [comment]
improve not remove

**Comment by Zilenan91** [comment]
"""""""""""""""""design lead""""""""""""""""" kor save us

**Comment by Niknakflak** [comment]
Making way for the soon to be finished new maps

**Comment by Sligneris** [comment]
Remove the birds. Remove the memes. Save the world.

**Comment by as334** [comment]
Literally the best map in rotation. Delete this.

**Comment by Aloraydrel** [comment]
Ew

**Comment by Armhulen** [comment]
remove it *after* we get the good maps, not before

**Comment by PKPenguin321** [comment]
fix atmos and keep it pls

**Comment by InsaneHyena** [comment]
Birdboat is non-ironically best station to exist, it just needs fixed atmos.

**Comment by Zilenan91** [comment]
It was intentional for it to not have atmos because of how small it is. One canister kills everything. It just needs a scrubber system for vent crawlers and it'll be objectively perfect for SS13

**Comment by Cheridan** [comment]
It's not acceptable for its atmos to be "lol broken on purpose." If flooding is too powerful then don't have the whole thing run on one network. Have subnetworks, like how sec in boxstation is off the main network with its own atmos.

**Comment by optimumtact** [comment]
The reality is that aside from box and meta, none of the maps are closely maintained or liked by players.

I think we need to rethink our approach to map rotation here.

**Comment by SidonCC** [comment]
If you like this map you have mental problems

**Comment by Niknakflak** [comment]
>merge conflicts

COAAIIIXXXXXXXXXXX

**Comment by KorPhaeron** [comment]
>removing the only map that has a different playstyle

Why have map rotation at all?

**Comment by coiax** [comment]
Of course there are going to be conflicts, I changed a file that you're proposing to remove? It's not like it's a difficult conflict to resolve.

**Comment by Niknakflak** [comment]
I understand wanting something different from box and meta but right now we have birdboat being used for meme rounds because of the reasons I stated above.  It's one thing to have a different playstyle in a station with different layout but it's another thing to just have it be extremely lethal in unfun ways.  You can have lethality or "metal death trap" without spider spam or engineering just exploding every round.  It's not fun to die from massive spiders and it's not fun when engineering just wipes itself and ends your round.  I'd rather get this removed and make way for the new maps.

**Comment by Zilenan91** [comment]
Birdboat is the only map that is even somewhat different from Meta. Every other map is more or less exactly the same with departments in different places. None of them are as unique as Birdboat is.

If the problem is that people can't figure out the SM shard then they need to git gud because it's not hard to set those up. 

I don't understand what the problem with the spiders is, they are the best part of the entire map.

**Comment by Imagebard** [comment]
>Spiders in maint

I seriously hope there are no green eyes there

**Comment by Zilenan91** [comment]
There's a sand temple in birdboat maint with green eyed spiders it's the best part of the map

**Comment by Imagebard** [comment]
>with green eyed spiders

**Comment by Zilenan91** [comment]
I can't stress enough how much !FUN! the nurse spiders are

**Comment by optimumtact** [comment]
@Imagebard sorry we don't allow anime girls on our repo

**Comment by Imagebard** [comment]
All those thoughts are leaving me panic striken.

**Comment by Niknakflak** [comment]
Resolving those conflicts was hell for me and I had mso and oranges walk me through it the entire way and it still sucked

**Comment by optimumtact** [comment]
The map was never very popular and the designer left, so on that basis I think it's best if we remove this to make way for a new range of maps

barring another maintainers explicit disagreement before lunch tomorrow NZST I'm going to merge this

**Comment by coiax** [comment]
Make a PR with the issues and I'll fix them.

There are no "new range of maps" that are incoming that are being stopped by birdboat existing.

Design lead literally disapproves.

**Comment by Niknakflak** [comment]
But headcoder approves, please go, you caused lots of pain already

**Comment by kyrahabattoir** [comment]
It's funny how goon can switch map every now and then yet the tg playerbase refuses to play anything but box and "box-like"

It's like players are simply unable to adapt.

**Comment by Imagebard** [comment]
Its funny how goon probably has people maintaining the map in your example but doesn't in this one.

**Comment by kyrahabattoir** [comment]
Hey you make a code change that break maps you should fix them.

**Comment by KorPhaeron** [comment]
>make room for new maps

I wasnt aware we had limited map slots

**Comment by kyrahabattoir** [comment]
No but just imagine it could CONFUSE people right?

**Comment by coiax** [comment]
> Hey you make a code change that break maps you should fix them, not just fuck around just so it will pass travis.

Um, it's a removal of a map, that travis tries to build. You **have** to modify travis when you're doing something like removing one of the supported maps. NikNak hasn't done anything wrong here.

**Comment by kyrahabattoir** [comment]
That's not what i ment @coiax I was replying to @Imagebard that when one change code that breaks map it's their responsability to fix the maps, and not "just enough" to make it pass travis.

The reason we have broken maps is that people only care that it works on box.

**Comment by coiax** [comment]
My mistake, I apologise.

**Comment by Imagebard** [comment]
In other news if coiax is SERIOUSLY going to fix the bugs then I will retract my vote on this.

**Comment by KorPhaeron** [comment]
Coiax is maintaining the map now

**Comment by Imagebard** [comment]
Hivemind intensifies internally.

**Comment by coiax** [comment]
Please list bugs in an orderly constructive fashion.

**Comment by Jordie0608** [comment]
1. Datum antags isn't done

**Pull request closed without merging**
