### PR TITLE
Adds a new engineering jumpsuit

### PR DESCRIPTION
**Pull request by ghost**
[Changelogs]: # (Your PR should contain a detailed changelog of notable changes, titled and categorized appropriately. This includes, new features, sprites, sounds, balance changes, admin tools, map edits, removals, big refactors, config changes, hosting changes and important fixes. An example changelog has been provided below for you to edit. If you need additional help, read https://github.com/tgstation/tgstation/wiki/Changelogs)

:cl: Mark9013100
add: Added the engineering hazard jumpsuit, can be found in the engidrobe. Sprites by sgtsammac.
/:cl:

[why]: # (Please add a short description [two lines down] of why you think these changes would benefit the game. If you can't justify it in words, it might not be worth adding.)

Gives engineering a little more variety in their appearance, and shouldn't deviate too much from their department scheme. 

Screenshots incase the bot doesn't provide.

### CODE REVIEW

**Comment by FantasticFwoosh** [comment]
Is this overkill with the high vis jacket we have already? It would have been nice to see it in the discord channel so people could have roundtabled it with opinions first (unless i just missed that)

**Comment by Mark9013100** [comment]
Didn't think of asking the discord, I'll post this in creative-general and maybe tg-station-general and garner some feedback, though I'm not much of a spriter but I'll see if there's anything I can do.

**Comment by Mark9013100** [comment]
Not sure why Travis failed.

**Comment by BebeYoshi** [comment]
> Not sure why Travis failed.

Just update your branch with the /tg/station master branch

**Comment by davethwave** [comment]
The only concern I have is that it could be confused with a prisoner uniform.

**Comment by Mark9013100** [comment]
>Just update your branch with the /tg/station master branch

That will a bit problematic, I'm not entirely knowledgeable of Git, I'll ask on coding-general and see if I can get help with that.

**Comment by BebeYoshi** [comment]
https://tgstation13.org/wiki/Guide_to_working_with_tgstation_as_an_upstream_repository
The rebase part should be what you are looking for

**Comment by Mark9013100** [comment]
Thanks, will Travis run again or will I need to do more?

**Comment by BebeYoshi** [comment]
If you do everything that is said there and push it, it should run again automatically

**Comment by Mark9013100** [comment]
@davethwave I feel like the arm and leg stripes are distinct enough to differentiate it from the prison jumpsuit, though I do imagine there will be a few cases of someone mistaking this for a prisoner jumpsuit.

**Comment by Bombpants** [comment]
@Mark9013100  Could you invert the colors and have the suit be a neon green/ yellow color with orange stripes?

**Comment by Mark9013100** [comment]
@Bombpants I'll see what I can do, might be tomorrow before I can get on that.

**Comment by Bawhoppen** [comment]
@davethwave Well, even if it is, that's just emergent gameplay.

**Comment by HomocidlePancakes** [comment]
Guy looks more like a test subject

**Comment by Mark9013100** [comment]
@Bombpants almost got the green alt done, I'll post it below/on this comment when done

**Comment by davethwave** [comment]
Something you would expect a Christmas elf while making toys to wear I guess. Perhaps strike off the red and see if there is another color that could go with it?

**Comment by davethwave** [comment]
The way it looks now looks ok in my opinion.

**Comment by Bombpants** [comment]
@davethewave. Maybe it would look better full size from an in game screen shot?

**Comment by Mark9013100** [comment]
I'll be getting some screenshots of the three within an hour

**Comment by Bombpants** [comment]
I definitely can see how the original can be confused with a prison jumpsuit if someone catches it at a glance.

**Comment by Bawhoppen** [comment]
I mean, but that's really not a problem. An orange jumpsuit can be confused with a prison suit. It really doesn't matter?

**Comment by Bombpants** [comment]
No, you’re right about that. It doesn’t (and shouldn’t) matter. I still think that the yellow with orange looks like the most SPACE OSHA approved.

**Comment by Bombpants** [comment]
No, you’re right about that. It doesn’t (and shouldn’t) matter. I still think that the yellow with orange looks like the most SPACE OSHA approved.

**Comment by Mark9013100** [comment]
Going to let a poll run on the forums for a few days to see which sprite people prefer most, https://tgstation13.org/phpBB/viewtopic.php?f=11&t=19897&view=unread#unread

**Comment by Partheo** [comment]
I like them and I appreciate the desire for more variety, but these have way too much contrast, IMO. For an outfit as basic as the jumpsuit, they stand out way too much and I don't think it's exaggeration to say that these are painful to look at.

I like the colors but together they just don't work. I feel like the problem is especially apparent from the side, where the tiny yellow parts hog way too much of my visual attention.
image
This is still a problem from the front too. I would reduce contrast somehow.

**Comment by Mark9013100** [comment]
I'll see about muting the colors @Partheo

**Comment by Mark9013100** [comment]
https://i.imgur.com/rKaLUGa.png @Partheo does this seem any better?

**Pull request merged**
