### PR TITLE
Removes infinite reflector loops, projectiles now fall off 5 base range per reflection.

### PR DESCRIPTION
**Pull request by silicons**
Fixes https://github.com/tgstation/tgstation/issues/40881

### CODE REVIEW

**Comment by Bombpants** [comment]
Feature

**Comment by GuyonBroadway** [comment]
Will this stop them if the two mirrors are point blank range anyway?

**Comment by GravitronBlue** [comment]
Torn on this PR, resolving the lag with emitter loops should absolutely happen, yet personally I don't want to see emitter loops gone as a feature that engineers can [abuse](https://i.imgur.com/FAcLePl.png).

Perhaps an alternative like VGstation's [optical emitter beams](https://cloud.githubusercontent.com/assets/7573912/10382438/54afb16c-6e24-11e5-9953-1c7e0d5c6c27.png) and having it as a separate system would be worth consideration in the future.

**Comment by TimeIsEndless** [comment]
How about making a cap on how many emitter beams can be active at once?

**Comment by GuyonBroadway** [comment]
What if anytime emitter beam passed into a tile with other emitter beams it had a chance to collide with and cancel out one of them?

At a low amount of beams, like 5-6 this will happen very rarely but once we approach absurd spessmen levels it starts to happen a lot and might be just enough to start making vast quantities of laser in a small area to self limit.

**Comment by subject217** [comment]
This is currently an admin issue as any idiot with two reflector boxes can bring the projectiles subsystem to a grinding halt and render it completely non-functional. This simply has to be removed because of the constant abuse.

**Comment by ExcessiveUseOfCobblestone** [comment]
Probably helps out with #39815 as well (although the bullet is 200 range so lol)

**Pull request merged**
