### PR TITLE
Wizard traps are damage proof, but can be erased with a null rod

### PR DESCRIPTION
**Pull request by coiax**
:cl: coiax
fix: Wizard traps are now indestructible to normal damage, but can be erased with a holy weapon.
/:cl:

- CTF traps are still indestructible and null rod proof.

I forget that object damage is a thing.

### CODE REVIEW

**Comment by coiax** [comment]
They're not supposed to be destroyed with a guy with a fire extinguisher.

**Comment by coiax** [comment]
There is a whole mechanic where you can just disarm the wizard traps by throwing anything across it, this isn't an intentional feature.

**Comment by coiax** [comment]
Not quite.

**Comment by Time-Green** [comment]
It takes about 30 seconds of smacking to destroy it, and wizard spawns alot of them, at least at some other way of getting rid of them.

**Comment by Supermichael777** [comment]
yeah their pure cancer and too deadly for a permanent hazard. its spam animation all over again

**Comment by coiax** [comment]
See changed title.

**Comment by ExcessiveUseOfCobblestone** [comment]
That's why you just lower the cooldown so they can spam traps. These aren't suppose to be uncounterable, they're suppose to be goofy and obnoxious.

**Comment by Time-Green** [comment]
Do we really need more objects that can only be removed with a nullrod?

**Comment by KorPhaeron** [comment]
Having shit that can only be destroyed by a single almost irreplacable item that belongs to a joke job isnt good when cult does it either

**Comment by ChangelingRain** [comment]
Yeah being able to just fill a hall with traps only one guy can deal with is bad
Also, this would be the only wizard spell to interact with the null rod, which is even more confusing for players, who probably won't immediately assume something a wizard did can be null rodded.

**Pull request closed without merging**
