### PR TITLE
adds a sprite to the "show roundend report" button

### PR DESCRIPTION
**Pull request by MrDoomBringer**
do we get gbp for making sprites? we should get gbp for making sprites.

:cl: MrDoomBringer
imageadd: roundend report button now has a lil icon
/:cl:

recycling assets is bad mmkay
**pic:**
image
**edit: i changed it a bit**

**shining testimonials:**
image

### CODE REVIEW

**Comment by MrDoomBringer** [comment]
image

**Comment by MrDoomBringer** [comment]
@fludd12 i did exactly that, and have been for the past year. maybe i fucced up this time

**Comment by fludd12** [comment]
Fair enough. I blame the same got demons that made me dirty my master three times in the same day. Someone call a chaplain

**Review by WJohn — APPROVED** [review]

**Comment by alexkar598** [comment]
Use git from and line and stop using weird GUI clients

**Comment by fludd12** [comment]
Weird gui clients are the future, alexkar! Soon our gui-enabled master race will rule the tgstation PRs!

**Comment by Cyberboss** [comment]
commit shit, get squashed

**Pull request merged**
