### PR TITLE
Adds springrolls

### PR DESCRIPTION
**Pull request by SomethingFish**
## About The Pull Request

Adds spring rolls to the game. Credit for the sprite all goes to @Sheits, thank you VERY much.
image
image

## Why It's Good For The Game

Spring rolls good. Adds another use of rice instead of just using them in rice bowls.

## Changelog

:cl:
add: The chefs have come up with a new use for rice and made these delicious vegetarian spring rolls to add to their menu.
/:cl:

### CODE REVIEW

**Comment by Hornyass114514** [comment]
I don't remember anything about rice in spring rolls

**Comment by SomethingFish** [comment]
vietnamese spring roll wrappers are made of rice paper, so even though the sprite isnt the ones made with rice paper, i thought it would be nice to include it as an ingredient

**Comment by OrionTheFox** [comment]
Is it possible for a sprite to be **too** good? That sticks out like a sore thumb simply because it looks so amazing lmaoooo

**Comment by Sheits** [comment]
> Is it possible for a sprite to be **too** good? Feels like it sticks out like a sore thumb simply because it looks so amazing lmaoooo

YEah it looks like shit ingame lmfao

**Comment by SomethingFish** [comment]
updated the icon and the recipe because @Sheits over here redrew the sprite to make it a vietnamese spring roll kinda goated

**Comment by Farquaar** [comment]
Doesn't look like any spring roll I've ever seen
image
https://en.wikipedia.org/wiki/Spring_roll

**Comment by AdipemDragon** [comment]
I am... very unsure about the baked in gray bounce lighting on the bottomright on these new ones, genuinely makes these look like image downscales

**Comment by BlueMemesauce** [comment]
> Doesn't look like any spring roll I've ever seen image https://en.wikipedia.org/wiki/Spring_roll

it's vietnam style spring roll

**Comment by SomethingFish** [comment]
image
this is what its supposed to look like but without the prawns

**Comment by Sheits** [comment]
> I am... very unsure about the baked in gray bounce lighting on the bottomright on these new ones, genuinely makes these look like image downscales

The bounce light is shifted towards blue, I did this because 90% of this game is grey?

**Comment by Jacquerel** [comment]
These have been very nice sprites in a vacuum but I’m not sure they fit with the rest of the game assets, there’s a much higher colour density and they aren’t outlined.  
Foods and drinks often break those rules mind but it seems like things are becoming more unified over time.

**Comment by Sheits** [comment]
> These have been very nice sprites in a vacuum but I’m not sure they fit with the rest of the game assets, there’s a much higher colour density and they aren’t outlined. Foods and drinks often break those rules (especially outlines) but I think that other commenter is right about the grey shifting. If you put this on other tiles (a wooden table, a wooden floor, a checker tiled floor, all commonly found near the kitchen) it would become much more obvious, which is partially why a lot of tg sprites are outlined. Without that at the edges it'd probably look fine anywhere.

Thanks, ill look into this & get screenshots ingame when im not as busy as I totally agree with this. I also wanted the sprites to have more contrast against the grey counter which is why I used a lower contrast outline on the highlighted areas. Personally I wanted to avoid this version of spring rolls due to the clusterfuck of highly saturated colours as I am fairly inexperienced working with pixel art.

I do not, however want to listen to some backhanded comment saying "idk it looks like a downscaled image" with no further explanation.

**Comment by SomethingFish** [comment]
alright final sprite update because we have stuff to do other than ss13
old sprite vs new sprite:
image
image

**Review by Mothblocks — APPROVED** [review]

**Pull request merged**
