### PR TITLE
Absolute paths and changes one liner if's/else's/else if's.

### PR DESCRIPTION
**Pull request by Firecage**
This changes the few remaining relative paths into absolute paths, and also changes this:

if(blah)    whateverthehell
to
if(blah)
    whateverthehell

### CODE REVIEW

**Comment by WJohn** [comment]
do you want to get conflicts

because this is how you get conflicts

**Comment by Firecage** [comment]
Yes

**Comment by Incoming5643** [comment]
RIP datum antags

**Comment by Firecage** [comment]
@Incoming5643 Well, you could always just finish datum antags and then I fix the merge conflicts here after datum antags are merged. *shrugs*

**Comment by optimumtact** [comment]
if we're gonna recommend these we may as well also clean up our own messes

**Comment by Razharas** [comment]
Dont call it a grave
Its a pr you opened

**Pull request merged**
