### PR TITLE
The least surprising nerf: Null Crates & Emagged Plasma Export Bonus

### PR DESCRIPTION
**Pull request by Robustin**
Yes cargo still needs a general revamp but in the mean time lets maybe not give out 134TC of traitor gear  for every stack of plasma you export (no thats not a joke, yes thats actually how much TC you get from 1 stack of plasma sheets). 

Cost up to 20k from 14k

Crate TC value down to 30 from 50

Bonus for exporting plasma while emagged is removed. Plasma is already the best export, giving it a 50% bonus for someone slapping it with an emag is just bad design. 

Our stat page borked up cargo stats recently but for the last 2 months Null Crates were the single most popular item ordered by Cargo. I know its fun getting boatloads of traitor gear but it shouldn't be a god damn Syndicate armory that would make nukeops blush with envy.

### CODE REVIEW

**Comment by Repukan** [comment]
I'd be more interested in maybe also letting random guns come instead of TC items.

Like the guns in the space pirate ruin with ammo attached. Imagine getting a grenade launcher or a bioterror sprayer from the nukies.

**Comment by Supermichael777** [comment]
give it a 5% chance of horrible death ant its cool

**Comment by Iamgoofball** [comment]
remember when i made it a proper syndicate crate to prove a point that the concept was OP and it was LEFT IN

**Comment by PKPenguin321** [comment]
Either raise the cost or decrease the TC value, not both

**Comment by calzilla1** [comment]
Make it also have a chance to send over a bundle

**Comment by ma44** [comment]
Make tatortots only able to order this (along with a emag)

Also if you make it add fingerpritns upon viewing and no visible message, then it won't be a neat antag test

**Comment by Robustin** [comment]
Does the syndiecrate code support bundles?

@ma44 

I actually considered making emags disable ordering EXCEPT null crates so that Cargo wouldn't have an incentive to befriend every traitor they meet.

**Comment by BeeSting12** [comment]
anyone else remember before it was made null crates that it would just give you spec ops crates or a syndicate bundle? felt a little less OP back then, y'know? like yeah sure you get a shitton of syndie gear and you can still do a pretty good murderbone with it but it's not like you got every item in the uplink.

**Comment by BeeSting12** [comment]
and i'd say nerf one or the other, either the cost or amount of TCs worth inside. the plasma nerf should stay

**Comment by uraniummeltdown** [comment]
what's with all the nerf PRs, I thought Robustin was a man of the people

**Comment by Robustin** [comment]
Nerf PR's doesn't mean its bad for the players.I basically did this as I'm coding the heists because I realized it will be impossible to use TC as a motivation for antags, especially if it involves stealing credits/cargo supplies when you can just walk in the front door and say "How do you do QM, I'm a syndicate traitor with an emag, would you like access to more TC's than a warops this shift?" "Why yes sir I would like that!"

Null crates made it impossible to provide an IC motivation for anyone who had access to cargo during a traitor round. That's bad for the players and bad gameplay in general.

**Comment by GunHog** [comment]
He betrayed us. Just remember that if everyone has Syndie gear, then the round becomes a lot more interesting! As a Traitor, I will often walk to cargo, wait for people to leave, quickly emag the ordering console and leave. I will then wait to see if someone notices. 

Now, I never knew that emagging the console made plasma exports more rewarding. I guess because you are selling it to the Syndies at this point? I am fine with that being remove, but I do not support nerfing the crate. Seeing as Robustin nerfs generally cannot be stopped, I will ask that only the price increase goes in, not the amount of gear found in the crate.

**Comment by Robustin** [comment]
As a compromise I might put the TC back to 50 but bump the cost up to 25k, that still 60% more value for 25% more price than the current proposed nerf.

**Comment by Durkel** [comment]
an·tag·o·nist
/anˈtaɡənəst/

noun

    1. a person who actively opposes or is hostile to someone or something; an adversary: "he turned to confront his antagonist"

If you're idea of being a antagonist is to give nanotrasen and security fuck loads of syndicate gear then you're doing it wrong.

Besides the shitpost this a good nerf, The stats alone speak for itself on how insane the null crates are.

**Comment by Robustin** [comment]
Yea thankfully most people are on board with this. Something is seriously wrong when Cargo is importing more syndicate gear than anything else.

**Comment by ma44** [comment]
So when does botany get to grow syndicate gear?

**Comment by LanCartwright** [comment]
Consider the following;
Buying a null crate consumes the emag.

**Comment by uraniummeltdown** [comment]
Nah it shouldn't consume the emag, the emag should go inside the console, like slotting it in to capture the syndicate frequency or something

**Comment by sawrge** [comment]
Hey man follow me on twitter @swedishgirl97

**Comment by ma44** [comment]
wat

**Comment by ExcessiveUseOfCobblestone** [comment]
why 97?

**Comment by MMMiracles** [comment]
If anything, remove the damn implant bundle from potential selection.

The implant bundle has every traitor implant available, including the uplink implant (20-tc uplink). You can essentially turn the TC spent on the emag into infinite TC due to the uplink implant and a plethora of get-out-of-jail-free abilities.

**Comment by YakumoChen** [comment]
It's not bundles anymore Miracles

**Comment by Robustin** [comment]
@kevinz000 reacted with thumbs down....

Why am I not surprised.

**Comment by kevinz000** [comment]
@Robustin sorry friend my powergame side won over my common sense side this is a good nerf just i don't like it because i'm going to get hit the hardest.

**Comment by lzimann** [comment]
This seems reasonable.

@KorPhaeron

**Review by lzimann — CHANGES_REQUESTED** [review]
Atomize your changes. A pr for removing plasma bonus and one to the syndicate crate rebalance.

**Comment by duncathan** [comment]
this is a Nerf to traitor cargo; atomized enough imo

**Comment by duncathan** [comment]
yknow what I like both of these

**Pull request merged**
