### PR TITLE
[FEATURE] Movable Abandoned White Ship V2

### PR DESCRIPTION
**Pull request by Steelpoint**
Fixed Merge Conflicts Edition:  https://github.com/tgstation/-tg-station/pull/7196

Minor changes I've made.
- I've allowed the white ship the ability to return to its point of origin.
- I replaced the white syndi spacesuit with a second medical hardsuit.
- You can now pilot the ship to the derelict station.

Image of the ship docked at the derelict.
screenshot 2015-01-24 20 25 18

### CODE REVIEW

**Comment by Deantwo** [comment]
I know the ship is like super old and stuff... but it just... it looks wrong when compared to the current BoxStation.

**Comment by Steelpoint** [comment]
Its a relic of a older time, kinda the point imo.

**Comment by iyaerP** [comment]
This is a thing of beauty. MERGE IT!

**Comment by Deantwo** [comment]
Does it still dock to BoxStation the same way as in #7196?
Because was not all that good.

Does it actually have to dock to the BoxStation?
Couldn't it just stop near the station. Would give engineers something to, like building a docking area out to it.

**Comment by Steelpoint** [comment]
It still docks as described in the last iteration.

I personally prefer it docking directly on the station, simply because it puts the lower arrivals docking ring to good use instead of it just being there.

**Comment by Deantwo** [comment]
Doesn't the [Emergency Response Team](https://tgstation13.org/wiki/Emergency_Response_Team) or [Death squad](https://tgstation13.org/wiki/Death_squad) dock there?

**Comment by Steelpoint** [comment]
They dock in the area above it.

**Comment by Steelpoint** [comment]
Is this good to merge?

**Comment by Steelpoint** [comment]
Oh yeah, fixed merge conflicts as well as fixed missing areas from another PR.

**Comment by WJohn** [comment]
That PR fixed those areas though... Is your stuff outdated, perhaps?

**Comment by Steelpoint** [comment]
I would assume the mapmerger would have fixed that.

Why would it update the map but not the areas?

**Comment by WJohn** [comment]
I have no god damned clue anymore, man. The blast doors don't appear to be layer 2.9 anymore like I made them in atmos or on the bridge anymore and I really haven't got a clue what's going on.

**Comment by Steelpoint** [comment]
Can this be merged please? Its getting old.

**Comment by Steelpoint** [comment]
Updated with Changelog.

**Pull request merged**
