### PR TITLE
Makes the Hivemind Link power not absolute garbage

### PR DESCRIPTION
**Pull request by ATH1909**
## About The Pull Request

Hivemind Link is a default power that all changelings get. Did you even know it existed?

No, it's not the thing you use to communicate to other lings in lingchat.

Hivemind Link allows you to spend 8 seconds altering the flesh in the head of a target whom you've aggressively grabbed (while sending ominous/scary messages to them). Once you're done, your target will receive 40u of salbutamol and the ability to communicate in (and see/hear) hivemind chat... for only the next three minutes. Once those three minutes are up, they are kicked out of hivemind chat. Did I mention that every time you temporarily link someone to the hivemind with this ability, they automatically scream in hivemind chat? And did I also mention that you have to wait until this power expires on one target in order to use it on another?

This PR reworks Hivemind Link to make it actually useful to use as a power, but bumps up its price to 2 DNA points to compensate (meaning that it's no longer a default ling power).

Hivemind Link now permanently inducts people into the hivemind and can now add multiple people to the hivemind (although you still have to add them one at a time), but also now takes 12 seconds to fully perform, no longer gives your target 40u of salbutamol, and is no longer a free/default power (it now costs 2 DNA points, as mentioned above).

## Why It's Good For The Game

Hivemind Link SUCKED before. Now lings can use it to keep in touch with mortal collaborators and/or use it as a meme option in the place of something like transsting.

## Changelog
:cl: ATHATH
balance: The Hivemind Link changeling power now permanently inducts people into the hivemind and can now add multiple people to the hivemind (although you still have to add them one at a time), but also now takes 12 seconds to fully perform, no longer gives your target 40u of salbutamol, and is no longer a free/default power (it now costs 2 DNA points).
/:cl:

### CODE REVIEW

**Comment by ATH1909** [comment]
I'd recommend looking at the code for this PR in Split mode instead of Unified mode, since Unified mode looks like it shows this PR's changes in a weird way.

**Comment by Dawson1917** [comment]
i can spend 2 points on adrenals or fleshmend or armblade or biodegrade... or i can spend 2 points on glorified slimeperson chat...hmmm...

it should still be a default ability. if a ling is working with a traitor, the game is already long won without them even needing to communicate

**Comment by PKPenguin321** [comment]
I still hate this because it still basically just serves to be a buff to ling-sec, honestly it never should have been added in the first place. This is an improvement though since nobody will ever buy it at 2 points anyways, and if a ling-sec does buy it they're down 2 points. :+1:

**Comment by ATH1909** [comment]
> i can spend 2 points on adrenals or fleshmend or armblade or biodegrade... or i can spend 2 points on glorified slimeperson chat...hmmm...

As PkPenguin321 said, it's a pretty potent ability for sec lings, which is why it's priced at 2 points.

> it should still be a default ability. if a ling is working with a traitor, the game is already long won without them even needing to communicate

By that logic, we should just hand the game on a silver platter to any two antags who meet each other and decide to work together. Romerol still costs 25 TC, even though two traitors have to work together to buy it (usually). In other words, there should still be a cost to abilities that become potent/are available when two antags work together.

**Comment by Dawson1917** [comment]
>sec lings

lingcurity are cancer and shouldn't exist in the first place, i don't see a valid argument for balance in "friendly changelings" linking all of security to their hivemind to come to their rescue whenever another antag attacks them

assuming i'm not out of the loop and that's what you meant by sec lings

**Comment by ATH1909** [comment]
> > sec lings
> 
> lingcurity are cancer and shouldn't exist in the first place, i don't see a valid argument for balance in "friendly changelings" linking all of security to their hivemind to come to their rescue whenever another antag attacks them
> 
> assuming i'm not out of the loop and that's what you meant by sec lings
> 
> edit: an important thing to note is that the original intention of this ability was to interrogate people, namely for their uplink codes, in exchange for their life (hence limited ling channel access and salbutamol to keep the victim alive). its downfall was that nobody was obligated to tell you anything and most players would rather die than benefit an antag who just beat them to crit.
> your change is more like free comms for traitors and lings teaming up when they already have no difficulty murderboning the entire server just by aiding eachother, without needing their own private comms channel while doing it

If we wanted to encourage using this ability for interrogation instead of long-range communication, I could return this ability to its old state but also make it give your victim a temporary compulsion to obey you (only while they're in crit, however, so that a ling can't crit you, brainwash you, heal you up, and send you out on a suicide mission before the brainwashing expires).

**Comment by Dawson1917** [comment]
Yup if you add some fluff text that tells the victim they have to be truthful/obey what you say for a while I'd 100% be behind this as well as the 2 point cost, would have a lot of use if you interrogate the right person

**Comment by nemvar** [comment]
Wow wee, brainwashing for 2 ling points. No way that's a bad idea.

**Comment by Cyprex** [comment]
Sounds like an administration headache "But admin I missed the flavor text" "But admin I had no idea"  and that's provided we can even verify when they were and weren't in crit. That said, as it is 2 points is way too much. 1 at most

**Comment by Arathianen** [comment]
I think 2 points is too much for this. 1 point is already pushing it.

**Comment by ATH1909** [comment]
> Wow wee, brainwashing for 2 ling points. No way that's a bad idea.

It'd be brainwashing that'd last until you leave crit or until a minute or so passes, whichever comes first. In other words, you could force your victim to tell you what they know before they die, but you couldn't force them to go and try to kill their friends (unless they can somehow do that while in crit).

**Comment by ExcessiveUseOfCobblestone** [comment]
I thought you got memories (IE traitor codes/objs) on absorbies

**Comment by PKPenguin321** [comment]
>I thought you got memories (IE traitor codes/objs) on absorbies

yes

**Comment by ExcessiveUseOfCobblestone** [comment]
so this really only seems practically useful in pulling people who shouldn't be in hivemind chat into hivemind chat.

Even now this ability is a bit dumb, basically it's a practical :g mute since no one is gonna wanna out themselves (unless you're killing the guy, which defeats the purpose of the ability).

**Comment by Naloacisamazing** [comment]
The hivemind link stuff has seen the most use in dynamic where someone gets pulled into it due to some sorta thing happening. Traitors helping lings and stuff of a similar nature. Although alot of people (including myself) dont realize it disappears in a few minutes. Upside of that obviously is a traitor can work with a ling/ a group of lings. The obvious downside is that your putting yourself in a hilariously defenseless position by allowing lings to choke you where they could easily open up with an attack. Not to mention that it shows your character name no matter your disguise. in my opinion that seems balanced enough as is. if a ling has to attack another ling they are obviously going to also attack the named traitor filled with loot who is on the hivemind comms.

**Comment by ExcessiveUseOfCobblestone** [comment]
mmmm dynamic already has that patented "but what if a changeling gets their hands on it" smell.

**Comment by ExcessiveUseOfCobblestone** [comment]
Closing due to lack of maintainer interest

**Pull request closed without merging**
