### PR TITLE
The AI cant read messages anynore

### PR DESCRIPTION
**Pull request by JoshAdamPowell**
## About The Pull Request
The AI can no longer read any messages from central command.

An alternative to #87563.

I maintain that that PR is better but here is a compromise. Please read that PR for the reasoning.

## Changelog
:cl:
balance: After an argument at Central Command, the AI can't read any messages from CentCom, lest the AI steal the Vice-Admiral's excellent recipe for a sauce Bernaise.
/:cl:

### CODE REVIEW

**Comment by Loafin34** [comment]
i actually like the changelog we should merge it because of that

**Comment by IgiariValkyr** [comment]
While I'm all for "if the ai wants to read it so bad, it can get the paper held up to the camera", who really gives a **fuck** if it can read centcomm messages or not?

**Comment by deathrobotpunch** [comment]
tbh this is way worse

**Comment by JoshAdamPowell** [comment]
> tbh this is way worse

I agree

**Comment by JoshAdamPowell** [comment]
> While I'm all for "if the ai wants to read it so bad, it can get the paper held up to the camera", who really gives a **fuck** if it can read centcomm messages or not?

I don't care about Centcom messages but I do care about the AI reading the threat report.

**Comment by Steel-Serperior** [comment]
What exactly is the benefit of the AI not being able to read messages from CC?

**Comment by Dorsisdwarf** [comment]
> What exactly is the benefit of the AI not being able to read messages from CC?

The AI can read it, therefore random assistants can instantly shout "AI tell me the status report NOW!" the moment it appears, therefore command can't say, choose to lie to the crew about the threat to prevent panic/boredom suicides/whatever. The AI can send a borg to look at it, but that takes time and gives the captain a chance to hide the paper copies.

**Pull request closed without merging**
