### PR TITLE
Tiny skill neatness tweaks

### PR DESCRIPTION
**Pull request by Ryll-Ryll**
## About The Pull Request
#50656 introduced a few tiny issues, namely a typo'd extra TP to the admin "full monty" ahelp info bar which is supposed to lead to the skill panel but doesn't, and skill printouts using the datum name instead of the skill name. This corrects these issues (and then removes it from the full monty anyway, because like the language menu, it's not something admins need often).
[](https://i.imgur.com/aqMwZpT.png)
This is the full monty, for reference

## Why It's Good For The Game
Neatens up admin tools, displays correct names

## Changelog
:cl: Ryll/Shaps
admin: Removed errant TP from the admin full monty
/:cl:

### CODE REVIEW

**Review by ghost — APPROVED** [review]
thank u looks good. cant believe i missed that [i]

**Comment by MrDoomBringer** [comment]
goddammit i just fixed the [i] thing on #51297

**Comment by Ryll-Ryll** [comment]
@MrDoomBringer fug, if you wanna just roll the other change into your PR too I can just close this. Skills page makes more sense just being in the player panel and all that

**Comment by MrDoomBringer** [comment]
lmao nah its chill its better to have the fixes in the fix pr

**Pull request merged**
