### PR TITLE
Access chemical reagents correctly from the cached list

### PR DESCRIPTION
**Pull request by optimumtact**

### CODE REVIEW

**Comment by optimumtact** [comment]
@MrStonedOne did how this work change in 511?

**Comment by optimumtact** [comment]
This was an admin edit that added a strong to the reagents list, not a bug

**Comment by nullbear** [comment]
Reagents don't use cached lists right now?? That's what my pr I'm working on right now changes. Reagents are a list of instantiated datum/reagents and I'm changing it to be a cached list and it runs way faster.

**Comment by optimumtact** [comment]
no idea, I didn't look at the code too closely before making the PR

**Comment by RemieRichards** [comment]
@optimumtact that's a statement, not a question (the ?? doesn't help, but it's a statement)

**Comment by optimumtact** [comment]
oh, right, well the var is named cached_list but appears to just be a local reference to the datum reagent list anyway

**Pull request closed without merging**
