### PR TITLE
Move the chemistry fridge between the front desks

### PR DESCRIPTION
**Pull request by nukeop**
Everyone's doing it anyway. This will save some trouble.

### CODE REVIEW

**Comment by Iamgoofball** [comment]
:+1:

**Comment by Lumipharon** [comment]
Nice.

**Comment by Xhuis** [comment]
but its thops dpertmental interakshuen!!!!

( :+1: )

**Comment by PKPenguin321** [comment]
:+1:

**Comment by daman997** [comment]
this is ok :+1:

**Pull request merged**
