### PR TITLE
Industrial lubricant does not taste like cherry

### PR DESCRIPTION
**Pull request by Addust**
## About The Pull Request

Industrial lubricant should not be flavoured.
Please provide alternate flavours if necessary, preferably of the industrial variety.

## Why It's Good For The Game

ERP bad, and admins seem to have hated WGW more

## Changelog

:cl:
del: Nanotrasen has removed flavouring from industrial lubricant.
/:cl:

### CODE REVIEW

**Comment by Paxilmaniac** [comment]
Remove the by popular demand comment if you're doing that

**Comment by Jacquerel** [comment]
If you're removing the joke, don't make it taste of a concept.

**Comment by optimumtact** [comment]
I've personally sampled over 300 industrial lubricants and can confirm they all have a cherry taste

**Comment by optimumtact** [comment]
i also tried pastes, they mostly taste like rice crispies

**Pull request closed without merging**
