### PR TITLE
Adds turning on the spot to binoculars

### PR DESCRIPTION
**Pull request by LemonInTheDark**
## About The Pull Request
I hooked into the direction change signal to allow people using the binoculars to turn in place, and to make it actually work.

## Why It's Good For The Game

Spin spin

## Changelog
:cl:
add: You can now turn in place while using the binoculars, and it will behave as expected
/:cl:

### CODE REVIEW

**Comment by LemonInTheDark** [comment]
[Video](https://cdn.discordapp.com/attachments/326831214667235328/712817244186476624/2020-05-20_17-00-17.mp4)

**Comment by 2whatever2** [comment]
You can turn by holding CTRL + movement key. But that sucks so good PR

**Comment by ATH1909** [comment]
What happens if you use *spin while using binoculars?

How does this affect sniper rifles? How does this affect fighting someone who's approaching from a diagonal direction while you're wielding a sniper rifle?

**Comment by LemonInTheDark** [comment]
> 
> 
> What happens if you use *spin while using binoculars?
Spin works as expected, check the video. 
> How does this affect sniper rifles? How does this affect fighting someone who's approaching from a diagonal direction while you're wielding a sniper rifle?
As of now, it doesn't. I'm working on making zoom a component, or something similar.

**Comment by LemonInTheDark** [comment]
Closing this in presuit of better things

**Pull request closed without merging**
