### PR TITLE
Adds Icemoon Ruin: Syndicate Lab

### PR DESCRIPTION
**Pull request by DaCoolBoss**
## About The Pull Request
Adds the Syndicate Lab to the Icemoon ruin pool. This can spawn on either the cave or deep cave layers. It's a fairly small ruin so it's easily missed, but it is packed full of danger and treasure.

The outside of the lab is mostly covered in snow. There are a few small gaps that may or may not be filled in by the cave generation algorithm. From most angles, it blends into the ice moon enviroment. However, meson glasses will reveal the structure at a glance.

This lab has multiple hostiles to provide threat, there's a turret near the entrance (on the interior), a patrolling eviscerator, and two ranged syndicate agents with shotguns. The ruin is pressurised by default, so mining weapons are less effective.

As loot, the lab contains a Donk Co musket (single-shot combat shotgun, like the old pipeguns), two syndicate explorer's suits, a syndeye disk, a syndicate toolbox and some small gimmick items. The agents blow up on death so you can't have their shotguns or gear.
## Why It's Good For The Game

I collected feedback for a while on ruins and a common complaint is that Icebox's ruins are lacking in variety, especially in the loot and action departments.

To address the loot issue, I've added a bunch of loot to this ruin that previously could not spawn on Icebox. Mostly this is the fluffy and gimmicky stuff currently exclusive to space ruins, like the Donk piñata and anomaly releasers. Nothing especially powerful or round defining, because the ruin can spawn close to the station and isn't particularly hard to clear.

Threats are likewise all things that aren't usually avaliable on icebox. Prepare for lasers, buckshot, slashing damage and all relevant wounds. Without a syndicate card or agent ID the doors won't open and the ruin is powered, so miners can die to hacking the door open, then getting run over by a patrolling dedbot. Very funny. The ruin is designed not to be easily rolled by mining gear, but it remains a viable option. Lasers are designed to be particularly good here, to reward cooperation with security.
## Changelog
:cl:
add: Adds the Syndicate Lab to the Icemoon ruin pool.
/:cl:

### CODE REVIEW

**Comment by Singul0** [comment]
any cool lore inside?

**Comment by DaCoolBoss** [comment]
Nothing major on lore. It's just a combination lab and living space that the syndicate put down on the ice moon, researching plasma ore mostly.

**Comment by mc-oofert** [comment]
free lethal shotgun for fighting 3 enemies that are really easy to murder

**Comment by DaCoolBoss** [comment]
We somehow managed to survive the hermit den having a regal pipegun in it, we'll survive this too. If it gets abused it can be changed.

**Comment by MoonDeer728** [comment]
> any cool lore inside?

syndicate

**Comment by scrunklershrungle932** [comment]
can the climbing rope be replaced with the syndicate climbing rope thing?

**Pull request merged**
