### PR TITLE
Bullet sprite (before you shoot them not the projectile) upgrades

### PR DESCRIPTION
**Pull request by Paxilmaniac**
## About The Pull Request

Resprites most bullets, some ammo boxes, and the mosin stripper clip because itd look bad otherwise.

It looks something like this:
image

What's left:

Make 357 its own sprite
Get in game pictures of it
Maybe do speedloaders too we'll see
## Why It's Good For The Game

Current bullet sprites are suboptimal
## Changelog
:cl:
qol: Pistol ammo boxes now have sprites for being empty, so you can tell at a glance if they have bullets or not
imageadd: A large number of the sprites in ammo.dmi have been redone, which for the players means refreshed shotgun shells, bullets, and ammo boxes.
/:cl:

### CODE REVIEW

**Comment by Paxilmaniac** [comment]
> image
> I feel like the black lines (meant to represent the bullet?) look weird - doing this in 3/4 is super hard but making them rounder would go a long way. Also why not a brown/copper color instead of black?

because our bullets are made of iron not copper, and the dark color contrasts the lighter base more so i think it looked better

**Comment by Mey-Ha-Zah** [comment]
I'm not good at explaining myself but. I'll try. 
The designs look too different from the original bullets, especially the smaller lower caliber square ones. Maybe they are more readable, maybe it's just me preferring more rounded designs.
How would the bullets look on the ground when fired or when spilled?
Can we see these ingame?

**Comment by Likteer** [comment]
Those look like bottles of nail polish, not bullets. 
Not more detailed, just a strange perspective and coloring.

Sorry friend, but this doesn't seem it.

**Comment by MrDoomBringer** [comment]
> because our bullets are made of iron not copper

Not a good enough reason, don't compromise your aesthetics for silly crap like that. Why isn't the casing grey too in that case? Should every item printed from iron in the autolathe be grey?

**Comment by Paxilmaniac** [comment]
> > because our bullets are made of iron not copper
> 
> Not a good enough reason, don't compromise your aesthetics for silly crap like that. Why isn't the casing grey too in that case? Should every item printed from iron in the autolathe be grey?

The made of iron part was made up really the real reason I said was "I thought it looked better"

**Comment by Paxilmaniac** [comment]
> My colors are dogwater but this is how i'd work a more rounded 3/4 bullet shape (even tho a 3/4 perspective imo isn't necessary for a sprite this small). Not saying you need to do exactly this, but a similar shape/shading might help a little.

I get what you're saying, I'm trying something out right now to see if it'll look much good
image

**Comment by Mey-Ha-Zah** [comment]
> image

Other arguments aside, the tip wouldn't be rounded.

**Comment by MrDoomBringer** [comment]
image
Mey-ha do you mean more pointy like this

**Comment by Mey-Ha-Zah** [comment]
it's hard to do point with even pixels

**Comment by Helg2** [comment]
Also if you're making opened boxes either make it change its icon on every different amount of bullets or it's pointless.

**Comment by DaydreamIQ** [comment]
I know its been said already but the shells look more like lipstick than what they are. The top down perspective on them just doesn't look good at all, also this is probably a me issue but besides the Buckshot and the dart rounds I'm having a little trouble figuring out which is which at a glance (Tho making dart actually having a dark sticking out of it is cool, why the hell wasn't that a thing with the original)

**Comment by orthography** [comment]
Hey! I really like what you were going for, but the sprites feel a little indistinguishable when they're all together like this.

It might be a bit more effective to show a before and after for each part (as sucky as that sounds) so they don't blend together.

**Comment by Wallemations** [comment]
I'm a fan of the shotgun shells but not the other rounds, as those just look like tubes of black lipstick or something.

**Comment by SomeoneYouProbablyKnow** [comment]
I'm not sure i like them but it's real tricky to judge a sprite like this (namely small and rotatable) from sprites alone. Would be nice to see some ingame sprites

From the icons themselves they look a bit flat, try adding some more shading as if they are lit by a light from the side. Also your primary colors are a bit too bright for my liking especially for an object like bullets that should not draw this much attention to itself.

Maybe those are not real problems ingame but who knows.

**Comment by DrDiasyl** [comment]
This feels weird, like if TGMC got mixed with the Eris.

Generally it's fine, but I dislike that spent shotgun shell burnt part looks too perfect.

**Comment by DrDiasyl** [comment]
I think instead of making those this way, we should keep them flat and sprite them just laying horizontally

**Comment by dwasint** [comment]
i'm not the biggest fan of the shotgun shells mainly because of the shading 
image

normally it looks like they are flush with the tube part of the shell, but here because of the shading it looks like it kinda dips in a fair bit, no idea how you'd solve this with so few pixels but thats just my thoughts on the shells, i like the regular bullets though

**Comment by KathrinBailey** [comment]
You should show what these look like in-game when used casings get strewn across the floor.

**Pull request closed without merging**
