### PR TITLE
Gives cake cats their wagging abilities

### PR DESCRIPTION
**Pull request by xPokee**
## About The Pull Request
I made the cake cat do a wag.
## Why It's Good For The Game
Every other cat laying sprite had a wagging animation, yet the cak lacked one, so I added one.
## Changelog
:cl:
image: added a wagging tail for cake cats to match other cats
/:cl:

### CODE REVIEW

**Comment by Jacquerel** [comment]
image

Something has gone very wrong here

**Comment by ZephyrTFA** [comment]
You fucked up something here. Please fix your icons.

**Comment by Sealed101** [comment]
there's nothing wrong with the dmi, it seems that it's a diffbot thing. someone poke aa

**Comment by xPokee** [comment]
> You fucked up something here. Please fix your icons.

I checked everything in the icon file, I didn't see anything wrong with it

**Comment by xPokee** [comment]
> > > You fucked up something here. Please fix your icons.
> > 
> > 
> > I checked everything in the icon file, I didn't see anything wrong with it
> 
> Well the bot did, so re-download icon file and Cherry-pick your change into the new one

How do I do that? I'm really new to making PRs and stuff. When I redownloaded the file everything looked fine in it too??

**Comment by xPokee** [comment]
No clue how that got so fucked up, but it looks normal now

**Comment by optimumtact** [comment]
they probably have alpha hitboxes around them to make them easier to click and you accidentally removed it.

**Comment by Wallemations** [comment]
image

Are these just static PNGs or are there just a shitload of frames?

**Comment by xPokee** [comment]
> image
> 
> Are these just static PNGs or are there just a shitload of frames?

There should only be four frames, I can double check in the morning

**Review by Wallemations — APPROVED** [review]
I opened the file itself, for some reason the icon bot is only putting out png images instead of gifs
you're fine

**Pull request merged**
