### PR TITLE
Bombs in lavaland no longer ignore the bomb cap

### PR DESCRIPTION
**Pull request by lzimann**
Being able to easily almost halt the server entirely is not really nice to anyone.

Closes #32424

### CODE REVIEW

**Comment by SyruseEln** [comment]
fun removal
i ded
tritium was a mistake

**Comment by qbmax32** [comment]
lavaland is an excellent testing ground and superbombs are good for mining. cease

**Comment by vuonojenmustaturska** [comment]
For the record, I would have made this exact same PR if LeoZ hadn't been faster. This PR is necessary as admins are refusing to handle people who kill the server with assmos bombs in lavalands on a regular basis

**Comment by ExcessiveUseOfCobblestone** [comment]
Why not make it triple the bomb cap so it's 15,30,60?

Will that lmao the server?

**Comment by nicbn** [comment]
Why don't we remove the bomb cap and optimize explosions?
You know, like how real game companies would do.

**Comment by Ratvar** [comment]
"real game companies"
where

**Comment by davethwave** [comment]
Why there is a bomb cap that's not hardcoded, but nobody has ever reached without killing the server though...

**Comment by juanototo2** [comment]
It's
A
Feature

Sometimes looking at Toxins autism too much and crack Lavaland is just satisfying to watch.

**Comment by lzimann** [comment]
Of course it is a feature, no one implied otherwise, I am however removing said feature in this PR.

**Comment by KorPhaeron** [comment]
Bombs have already been heavily optimized. The reason the server is suffering unplayable lag for 10 minutes instead of outright freezing or crashing is because of the optimizations.

We're also not a real game company but if we were it wouldn't make much sense for us to leave an easy path to choking the servers accessible to players

**Comment by Hatfish** [comment]
Assmos was a mistake.

**Comment by Repukan** [comment]
This isn't a real game company lmao

**Comment by Grazyn** [comment]
2 considerations I posted in the assmos thread as well:

1. IIRC the explosion itself isn't the source of the lag, it's the thousands of ores being thrown around. An admin told me this the first and only time I detonated a Freon bomb on Lavaland. 

2. You can currently make a server-halting bomb with just noblium in one slot and a regular emergency oxygen tank in the other. It's as powerful as a Freon bomb and much easier to make (you just need fusion to filter out the noblium).

**Comment by Jalleo** [comment]
Or we could change which proc we use for bombs to the one merged in this PR
 https://github.com/tgstation/tgstation/pull/20319

**Comment by optimumtact** [comment]
@nicbn why dont' we shit fairy dust out and snort it like cocaine too

look forward to your pull optimizing all those ore and debris throws about that lets us remove the bomb cap

**Pull request closed without merging**
