### PR TITLE
[All stations] Cleaned up var-editted areas

### PR DESCRIPTION
**Pull request by ShizCalev**
Half of the station was var-renamed duplicate areas and APCs were rebelling because of it. 

Shouldn't have any more random power failures.

### CODE REVIEW

**Comment by WJohn** [comment]
Oh for shit's sake mmmiracles that's NOT OKAY.

**Comment by MMMiracles** [comment]
Other stations had some var-named areas so I didn't see the issue???

**Comment by ShizCalev** [comment]
@MMMiracles fuck there are. will have fix them too. :(

**Comment by MMMiracles** [comment]
well, good to know for future reference, considering it was never said not to do this anywhere nor did anyone ever bring it up the multitude of PRs addressing the map.

**Comment by ShizCalev** [comment]
That explains why Delta always loses gravity immediately after atmos is blown up.

**Comment by ShizCalev** [comment]
Will do a refactor to clean up the 20 different copies of port and starboard maint so they're nested instead of being all over the place in a different PR one day.

**Comment by ShizCalev** [comment]
Doing final checks to make sure nothing is unpowered on the maps now.

**Comment by ShizCalev** [comment]
All checks good, no issues found. 

This is ready for merge.

**Pull request merged**
