### PR TITLE
Automatic DME Generator/Merge Machine

### PR DESCRIPTION
**Pull request by redmoogle**
## About The Pull Request

Automated DME Generator, basically it generates the entire DME before building so you dont have to be assed to tick files or if I do gitignore the dme no DME conflicts ever(not that there probably ever is but w/e)

## Why It's Good For The Game

Makes coding slightly less of a pain in the ass, spaghetti code only takes 3 seconds to run

Only thing I dislike is that stylesheet gets pushed down one(fixed _not_)

## Changelog
:cl:
code: DME file is now automagically generated
/:cl:

### CODE REVIEW

**Comment by Ghilker** [comment]
why remove halloween

**Comment by redmoogle** [comment]
> 
> 
> why remove halloween

This file is unused theres another one

**Comment by Ghilker** [comment]
> > why remove halloween
> 
> This file is unused theres another one

ok but why remove it here

**Comment by redmoogle** [comment]
> 
> 
> > > why remove halloween
> > 
> > 
> > This file is unused theres another one
> 
> ok but why remove it here

breaks the other file

**Comment by LemonInTheDark** [comment]
We shouldn't rely on external tooling like this, and it breaks spacemandmm. You're going to need more justification then just a qol improvement for this

**Comment by redmoogle** [comment]
Going to rewrite this to nodejs tommorow

**Comment by Cyberboss** [comment]
Good because we're definitely not adding python as a core build dependency.

**Comment by redmoogle** [comment]
> Good because we're definitely not adding python as a core build dependency.

Except for that part where python is much faster than nodejs at doing this _unironically_ without doing sorting either

**Comment by Mothblocks** [comment]
...and also requires extra installation steps considering our entire tooling chain is in Node.JS right now, which is handled entirely by CBT, and has the nasty potential to drift versions.

**Comment by AnturK** [comment]
Bad. Breaks sdmm, adds needless layer of complexity and obfuscation to the build and adds hard python dependency on top.  Average user now needs to be aware of these blacklists now. If this is intended for some automated dm generators they can handle dme modification themselves since they need to be dme aware anyway.

**Comment by redmoogle** [comment]
> 
> 
> Bad. Breaks sdmm, adds needless layer of complexity and obfuscation to the build and adds hard python dependency on top. Average user now needs to be aware of these blacklists now. If this is intended for some automated dm generators they can handle dme modification themselves since they need to be dme aware anyway.

Be capable of reading. _I said I was rewriting this_, and no they really dont need to be aware of the blacklist because im _working_ on that

**Comment by optimumtact** [comment]
I don't buy the argument of obfuscation for QoL, ultimately it makes people less capable of working on tgstation when they're missing fundamental concepts like ticking files for inclusion into DME and compiling TGUI's files.

:-1: from me

**Pull request closed without merging**
