### PR TITLE
Heads of Staff now have basic Maint access

### PR DESCRIPTION
**Pull request by Iamgoofball**
> be doctor turned CMO
> happen to be gang head
> respond to help cry in maint, have to be let in by the HoS
> no one's there, HoS fucks off
> i get stuck in there and run into a security room that opened because I can't get out through ANY OF THE DOORS CONNECTING TO PUBLIC HALLWAYS
> WITH A CMO ID
> HoS comes back, stuns me, searches me, finds my shit, executes on the spot
# salt

:cl: Iamsaltball
rscadd: Heads of Staff now have basic Maint. access.
/:cl:

### CODE REVIEW

**Comment by Lumipharon** [comment]
Just remove sec and assmaint again, that's the superior option. At this rate you might as well remove maint access requirements altogether.

**Comment by TechnoAlchemisto** [comment]
You already made this pr

**Comment by PKPenguin321** [comment]
No

**Comment by Shadowlight213** [comment]
:+1: assistants and sec having maint while the fucking heads don't always pissed me off.

**Comment by GunHog** [comment]
Stop touting this as a grudgecode PR. I want this to actually get in, Goof!

**Comment by optimumtact** [comment]
Yah this makes sense to be honest.

send feedback to email@oranges.net.nz

**Comment by Lumipharon** [comment]
reee~ what is the point of maint access if you just give it out to everyone by default?
Getting maint access from the hop - especially as a fellow head of staff takes precisely 2 seconds.

**Comment by TechnoAlchemisto** [comment]
Yeah, maint isn't supposed to be a place everyone can go, it's supposed to be a sketchy dark tunnel only some people have access to.

**Comment by GunHog** [comment]
Why should that include assistants and Sec, but not heads?

**Comment by PKPenguin321** [comment]
Heads should be maintaining their department not dashing into maint for them valids

**Comment by Iamgoofball** [comment]
daily reminder I made this after I wasn't able to save a patient as the CMO and got caught as an antag because of it

**Comment by Lumipharon** [comment]
>I tried to save a guy in space but didn't have a space suit
>all heads should have spacesuits by default

>I wasn't able to do R&D because no one was mining
>all of science should have mining access

It's almost as if like, relying on other people is a thing in this game.

@GunHog I've always been a proponent of no ass or secmaint - the game was honestly far better for antags when that was the case, but assbabies cried that having to interact with another human being to get maint access was a terrible thing.

**Pull request merged**
