### PR TITLE
You can't shove recently batoned people into a wall

### PR DESCRIPTION
**Pull request by JohnFulpWillard**
## About The Pull Request

This removes the ability for people that were recently batoned to be shoved into a wall. This doesn't affect shove stun, only the initial wall shove, although https://github.com/tgstation/tgstation/pull/81886 is doing things with that if you're interested.

This will basically only be affecting stunbaton/stunprod, because telebaton/contractor baton knock you down on the first hit anyways, meaning that shoving them while they are already on the ground will still stun them.

Video demonstration:
https://github.com/tgstation/tgstation/assets/53777086/aa00a00b-7d94-4d82-ba3a-5dd3d6d1f883

## Why It's Good For The Game

Currently the "I was batoned" trait is meant to prevent double batoning by the same person, and give some reaction time to the person being batoned (at least until they fall to the ground), but it has a massive loophole in that you can shove them into a wall to prevent them from being able to do anything in said reaction time. It's a lame strategy that goes against the baton's 2 hit to stun mechanic, so I think we should patch this up.

## Changelog

:cl:
balance: Recently batoned people (during the opening when they can't be batoned a second time) can now no longer be shoved into a wall in that time either.
/:cl:

### CODE REVIEW

**Comment by necromanceranne** [comment]
I'm not sure I get the issue here. The target has to actually be positioned against an object that allows a shove to knock them over for this to be a problem. That's an entirely separate attack as well, why punish someone for making one attack first over another entirely arbitrarily just because both are knockdown related?

This also introduces a really awkward scenario. If the target has baton resistance, an invisible effect that prevents knockdowns from batons, doesn't that mean that hitting them with a stun baton renders them both shove knockdown immune AND baton knockdown immune for the duration of the baton effect?

Also, I feel like this steps on the toes of riot suits somewhat. Batoning someone effectively conveys to them the suits strongest defense benefit. That seems very silly to me as well.

**Comment by JohnFulpWillard** [comment]
> why punish someone for making one attack first over another entirely arbitrarily just because both are knockdown related?

The punishment of a single click not knocking the enemy down is not a large one, the player being hit is still going to be affected by the effects of being shoved

> If the target has baton resistance, an invisible effect that prevents knockdowns from batons, doesn't that mean that hitting them with a stun baton renders them both shove knockdown immune AND baton knockdown immune for the duration of the baton effect?

It should yes, I don't see that as much of an issue.

> I feel like this steps on the toes of riot suits somewhat

Riot suit is something you get to protect yourself against shoves, getting batoned is something someone else is doing to you. They are vastly different scenarios and don't affect eachother. We shouldn't expect players to get riot suits so officers can't stun-shove, but we should expect baton users to at least require 2 baton hits to stun, which we have delay specifically to avoid double stunning.

**Comment by ATH1909** [comment]
also this seems really unintuitive for someone to know without codediving/looking it up/being told by a friend

**Comment by necromanceranne** [comment]
You could just make it a balloon alert like 'knockdown blocked' or something.

**Comment by Pickle-Coding** [comment]
Does it really matter enough to make a reaction that doesn't make sense? If I recall correctly, someone has to pull a baton out which leaves a visual of what's going to happen, they then have a small cooldown before they can even baton the target. Once they baton, there is another small cooldown before they can even shove the target.

Doesn't really look like it's a particularly broken combination, and I haven't even seen or heard of it being used before. If there's a non-emergency balance change, it should at least make sense ICly of why it's the case, and not be another strange and arbitrarily chosen if check with no rhyme or reason, which this game is already particularly bad at.

> You could just make it a balloon alert like 'knockdown blocked' or something.

I don't think that will be enough. It may explain that it's blocked, but people will still be confused on why that's happening, because this change doesn't make any sense in the first place.

**Comment by JohnFulpWillard** [comment]
image

**Comment by ATH1909** [comment]
okay but this doesn't tell the player WHY they're managing to stay up

**Comment by JohnFulpWillard** [comment]
That's fine, as long as you know that it is intended that they can't be shoved down then you can reasonably figure out what caused it.

**Comment by ATH1909** [comment]
> That's fine, as long as you know that it is intended that they can't be shoved down then you can reasonably figure out what caused it.

bruh ain't no way someone who doesn't know about this pr is gonna figure out that it's the baton that caused it

people aren't going to casually sit down and lab this shit out, they're going to see this message while analyzing a heated combat and have no idea what of the 10 different factors in play caused it

I'd sooner leap to "oh, they were on some kind of drug" than "my baton prevented me from shoving them down"

**Comment by JohnFulpWillard** [comment]
The same can be said about riot gear then, nowhere is it told to someone shoving another guy with riot gear that their armor blocks shoves. I think it is pedantic and we should be able to assume that someone can figure this out.

**Comment by ATH1909** [comment]
riot gear is specifically designed for holding back poorly-armed rioters and at least looks special and imposing, batons have no logical connection to not letting you be shoveknockdowned

adding a special message for riot armor being the cause of the immunity would also be nice, though

**Comment by ATH1909** [comment]
at LEAST give it a "can't wallshove a baton'd target!" message or something

**Comment by atlasle** [comment]
all for the unclear message, who cares if the game doesnt spell out everything for you, also youre so dishonest if you think people wont figure this out within a week, its using a baton we're talking about not some atmos level mechanic

**Comment by ATH1909** [comment]
> all for the unclear message, who cares if the game doesnt spell out everything for you, also youre so dishonest if you think people wont figure this out within a week, its using a baton we're talking about not some atmos level mechanic

misinformation about mouthpunching increasing your punches' knockdown chance persisted for YEARS

and I thought that improving in-game communication re: mechanics was one of the things we were actively trying to improve (see: mouseover tooltips about left click/right click interactions)

**Comment by ATH1909** [comment]
> all for the unclear message, who cares if the game doesnt spell out everything for you, also youre so dishonest if you think people wont figure this out within a week, its using a baton we're talking about not some atmos level mechanic

also how is this dishonest???? like I'm advocating for rewording a message (and/or giving a balloon alert) to better indicate a mechanic that would otherwise be hidden tech passed around between people in the know, that's the opposite of trying to deceive people for my own gain.

**Comment by optimumtact** [comment]
you don't need to write an ethics essay you've made your request people don't have to oblige you.

**Comment by MrMelbert** [comment]
I want to merge this, but I have a vague memory of Mothblocks wanting a feedback message for this or something? Not sure

**Comment by optimumtact** [comment]
if you've never used it why do you care?

**Comment by Redrover1760** [comment]
> if you've never used it why do you care?

Its unintuitive and doesnt solve any issues regarding ss13 stun combat.

**Pull request closed without merging**
