### PR TITLE
Ghosts now have a language menu

### PR DESCRIPTION
**Pull request by coiax**
:cl: coiax
add: Ghosts can now modify their own understood languages with the
language menu.
/:cl:

- Language menu is now on /atom/movable, and can be opened by any atom
with the `open_language_menu` proc.
- Used for testing, and simulating what various station members hear.

### CODE REVIEW

**Comment by cedarbridge** [comment]
Does this reset properly when the ghost is returned to a mob or does the ghost carry the languages with it?

**Comment by Incoming5643** [comment]
Why would an observer ever want to not just understand everything?

**Comment by AnturK** [comment]
What incoming said. I see no reason for this.

**Comment by Tacolizard** [comment]
Tip no. 1 of open source software: never question the need for a feature, just add it.

**Comment by coiax** [comment]
Ghost mobs are separate from living mobs.

- You might want to drop all languages to simulate what the crew would hear
- Occasionally ghosts lose all their languages for reasons I am not clear on
- This gives people a chance to appreciate the language scrambling features

**Comment by XDTM** [comment]
Maybe for the same reason some keep darkness on, for looking at what a particular team sees and hears.
But debugging seems like the most useful part, and i kinda feel like it might as well be a debug tab command.

**Comment by Incoming5643** [comment]
>Occasionally ghosts lose all their languages for reasons I am not clear on

Using a feature to cover a bug is not a great thing to do.

Other reasons are valid though, if somewhat iffy.

**Comment by lzimann** [comment]
If you are debugging, you already have admin tools to change your language. As for ghosts, this is kinda stupid honestly.

**Comment by octareenroon91** [comment]
Go for it

**Comment by Niknakflak** [comment]
Dumb, ghosts should just understand everything all the time

**Pull request closed without merging**
