### PR TITLE
Fix mistake in bottle hitting message.

### LINKED ISSUE #8491: Breaking a bottle on your own head has the wrong gender
[tw] magic unmasky poopy butt spell
@Miauw62 
bottlesmashing

### PR DESCRIPTION
**Pull request by phil235**
Fixes #8491

### CODE REVIEW

**Comment by Chocobro** [comment]
fixes #8491

**Comment by Incoming5643** [comment]
resolves #8491

**Comment by RandomMarine** [comment]
rectifies #8491

**Comment by pudl** [comment]
corrects #8491

**Pull request merged**
