### PR TITLE
[s] Fixes hiding the nuke disk on the arrivals shuttle

### LINKED ISSUE #27399: You can put the nuke disk on the arrivals shuttle making it unobtainable for a period.
Title says it all. Someone stuck it in a medkit and the shuttle went back into space leaving it stranded.

### PR DESCRIPTION
**Pull request by Cyberboss**
Fixes #27399 
Closes #27623

### CODE REVIEW

**Comment by Kromgar** [comment]
aren't [s] posts supposed to be hidden?

**Comment by Cyberboss** [comment]
Just to the game servers

**Comment by coiax** [comment]
Instead of being able to ground the arrival shuttle, why not just have it relocate the nuke disk when it leaves?

Or modify the nuke disk's "in_bounds" check to not include the arrival shuttle area, which does the same thing, but in a different manner

**Comment by octareenroon91** [comment]
There's no real special advantage to anchoring the arrivals shuttle.

**Comment by coiax** [comment]
I think my PR is better, fight me. :P

**Comment by Cyberboss** [comment]
k

**Pull request merged**
