### PR TITLE
Adds audio for gasping.

### PR DESCRIPTION
**Pull request by ghost**
:cl:
soundadd: gasping is now vocal
/:cl:

this audio is triggered by any code that runs the gasp emote, manually gasping wont trigger the sound to avoid degeneracy and spam.

https://streamable.com/gm3tz

audio is from my audio collection

### CODE REVIEW

**Comment by ATH1909** [comment]
Maybe add some more sudden gasps in there as well?

Should manually emoted gasps make more of a "dramatic" gasp than a "can't breathe" gasp?

**Comment by Qustinnus** [comment]
You cant manual gasp with sound atm

**Comment by Dawson1917** [comment]
image
Why does nobody listen?

**Comment by necromanceranne** [comment]
_I-I can't take all of it, sempai~!_

**Comment by ArcaneMusic** [comment]
This'll really give that "Flooding a room with neurotoxin" flavor that this game needs

**Comment by PepperPrepper** [comment]
(Apologies in advance if this is already a feature)
Would the gasping noises play in a completely airless environment?
 if they do then I would suggest that if you are in space/ a depressurized room the gasping audio would be muted maybe with a message like "Person tries to gasp but no sound comes out!".
This would also be a fix for the whole catgirl gasping thing as they would make no noise if they had an empty tank on.

**Comment by Qustinnus** [comment]
I think you can't hear audio in space anyways afaik

**Comment by knacker48** [comment]
...well except for bike horns

**Comment by actioninja** [comment]
You can hear audio but it's much quieter and also falls off differently

**Comment by Potototatoh** [comment]
audio from your collection my ass

**Comment by Qustinnus** [comment]
lol ok buddy I've been collecting royalty free audio for years for game dev

**Comment by Qustinnus** [comment]
time for round two

**Pull request merged**
