### PR TITLE
Kinetic Crusher Change!

### PR DESCRIPTION
**Pull request by Shadowflame909**
We cannot live in a world where Kinetic Crushers have an untouchable light thus harming the poor shadow folk.

I say we remove thy light, and if anyone does not like thy. Just get a flash light in you're pocket. Thank
you for reading. um, insert shadow person icon.

### CODE REVIEW

**Comment by kevinz000** [comment]
Just make it toggleable dood

**Comment by DoctoreMad** [comment]
Do you know how clumsy Kinetic Crushers are? For starters, miners either drag them or put them in the backpack slot.

**Comment by Xhuis** [comment]
I feel like you haven't actually used a kinetic crusher. The light on them is very useful in my eyes because you don't have a kinetic accelerator to attach a seclite too, and unless you lug around your backpack, missing one so you can store your accelerator on your back makes every storage slot valuable, and having two flashlights takes up too much.

At least make it a toggle, I think.

**Review by ChangelingRain — CHANGES_REQUESTED** [review]
Make the light a toggle. Preferably by putting a flashlight inside it somehow since that's cleaner than copying light toggle code from anywhere.

**Comment by Shadowflame909** [comment]
Looks like I won't be helping out my fellow shadow brothern today.

**Comment by Armhulen** [comment]
or just do it bro

**Pull request closed without merging**
