### PR TITLE
Fixes the name of R&D's clothing.

### PR DESCRIPTION
**Pull request by Iamgoofball**
## About The Pull Request

See title.

## Why It's Good For The Game

The name needs to be correct. After all, there's not a scientist in the world who goes without his speed suit.

## Changelog
:cl:
fix: Fixes the name of R&D's clothing.
/:cl:

### CODE REVIEW

**Comment by D4C-420** [comment]
This implies that wearing a sci mans clothing will make you faster which is blatantly false as no scientist has succeeded in out running me with a bat.

**Comment by Timberpoes** [comment]
Why?

**Comment by tralezab** [comment]
What?

**Comment by Sinestia** [comment]
Another home run

**Comment by Nexofas** [comment]
Next up 
>Renames Security clothes
>Batongsuit

**Comment by LemonInTheDark** [comment]
I'm not sure what this is a ref to, but it's sure not a fix

**Comment by Mothblocks** [comment]
Please consider this a friendly warning, your PR's must have a properly descriptive title and body content that explains the purpose of the PR.

Your current title and or body content does not meet requirements, so please update it. 

Your changelog is also inaccurate, so please update it.

**Comment by maxymax13** [comment]
I am no longer warning friendily. Consider this a threat. You MUST update your PR's title and body to better explain the purpose of the PR, to meet requirements.

**Comment by optimumtact** [comment]
Please consider this a friendly warning, your PR's must have a properly descriptive title and body content that explains the purpose of the PR.

Your current title and or body content does not meet requirements, so please update it.

**Comment by RaveRadbury** [comment]
It's a Venture Bros. reference

**Comment by Timberpoes** [comment]
Do what mothblocks asked, please.

**Comment by optimumtact** [comment]
this isn't real

**Pull request closed without merging**
