### PR TITLE
Restores Maintenance Botany on Meta & Redoes SE Solars

### PR DESCRIPTION
**Pull request by Son-of-Space**
image

## About The Pull Request

This PR slightly expands maintenance on Meta by Science to restore maintenance botany to its former glory. It was an old staple on the map that nobody really wanted to see go. It also does some work on the corresponding set of solars.

Maintenance Botany:
image
image

New Solars:
image

Whole Area:
image

## Why It's Good For The Game

Restores a piece of soul to meta that nobody really wanted to see go. Returns a little maintenance niche for players to perform discrete projects or for a cult base to form.

## Changelog
:cl: Son of Space
add: Maintenance Botany on Meta has been restored
/:cl:

### CODE REVIEW

**Comment by Son-of-Space** [comment]
Disclaimer: Those rats are not map spawns, just happened to have rolled the event there. Very menacing, yes yes.

**Comment by spessbro** [comment]
1. atomize your prs, redoing SE solars should be separate from this 
2. the embershroom seeds shouldn't start on-station, the other seeds should be gone too since that's what the resupply canister is there for

**Comment by Capsandi** [comment]
I dislike the solar change, maps usually(I believe donut had different setups) have a single configuration of the solar panels. Additionally, I predict this configuration would be more difficult to move through, which would be fine if it were to match the other solar arrays, but it doesn't.

**Comment by Son-of-Space** [comment]
> 
> 
>     1. atomize your prs, redoing SE solars should be separate from this
> 
>     2. the embershroom seeds shouldn't start on-station, the other seeds should be gone too since that's what the resupply canister is there for

1. Solars have to be moved and redone to make room for the botany area. They're directly connected to each other and part of the same change.

2. I'll remove the embershroom seeds, but the others stay. It's a part of the theme of maintenance botany. A few extra seeds doesn't hurt anything, and there's no seed vendor in there. In fact, I'll probably remove the resupply canister.

**Comment by Son-of-Space** [comment]
> 
> 
> I dislike the solar change, maps usually(I believe donut had different setups) have a single configuration of the solar panels. Additionally, I predict this configuration would be more difficult to move through, which would be fine if it were to match the other solar arrays, but it doesn't.

Luckily solars are already really easy to set up. This configuration makes it so the solars are as far away from the bomb testing site as possible. I'll wait for more feedback on them.

**Comment by notfrying1pans** [comment]
ive never seen bomb tests damage se solars before

**Comment by spessbro** [comment]
>     2. I'll remove the embershroom seeds, but the others stay. It's a part of the theme of maintenance botany. A few extra seeds doesn't hurt anything, and there's no seed vendor in there. In fact, I'll probably remove the resupply canister.

the point of only having the resupply canister is to force you to deconstruct another vendor to get it and that way you can get sec on your ass for it

**Comment by Son-of-Space** [comment]
> 
> 
> ive never seen bomb tests damage se solars before

MetaSci has undergone significant changes.

**Comment by Son-of-Space** [comment]
> 
> 
> > ```
> > 2. I'll remove the embershroom seeds, but the others stay. It's a part of the theme of maintenance botany. A few extra seeds doesn't hurt anything, and there's no seed vendor in there. In fact, I'll probably remove the resupply canister.
> > ```
> 
> the point of only having the resupply canister is to force you to deconstruct another vendor to get it and that way you can get sec on your ass for it

...What?

If they want a seed vendor, they can just break into tech storage or print one. They don't have to deconstruct anything. This area is supposed to be a place where you can grow plants incognito, not an area that's supposed to spur you into raiding other places.

**Comment by AlinaStarkova** [comment]
> > 
> > 
> >     1. atomize your prs, redoing SE solars should be separate from this
> > 
> >     2. the embershroom seeds shouldn't start on-station, the other seeds should be gone too since that's what the resupply canister is there for
> 
> 1. Solars have to be moved and redone to make room for the botany area. They're directly connected to each other and part of the same change.
> 
> 2. I'll remove the embershroom seeds, but the others stay. It's a part of the theme of maintenance botany. A few extra seeds doesn't hurt anything, and there's no seed vendor in there. In fact, I'll probably remove the resupply canister.

the resupply canister is so you can build a seed vendor in maint botany, without building a resupply from cargo

i think he means the layout, atmoize the solars layout, you can move the airlocks here of course, then make a branch of this branch that changes solar layout (so that PR will require this one to merge firsr)

**Comment by notfrying1pans** [comment]
> This configuration makes it so the solars are as far away from the bomb testing site as possible. 

But you moved solars downwards which is closer to the bomb site

**Comment by AlinaStarkova** [comment]
> > 
> > 
> > ive never seen bomb tests damage se solars before
> 
> MetaSci has undergone significant changes very recently.

bomb test range is as far away from solars as it was from any part of the station before, if not even farther, its nearly at the edge of the map down south

**Comment by Son-of-Space** [comment]
> 
> 
> > > ```
> > > 1. atomize your prs, redoing SE solars should be separate from this
> > > 
> > > 2. the embershroom seeds shouldn't start on-station, the other seeds should be gone too since that's what the resupply canister is there for
> > > ```
> > 
> > 
> > 
> > 1. Solars have to be moved and redone to make room for the botany area. They're directly connected to each other and part of the same change.
> > 2. I'll remove the embershroom seeds, but the others stay. It's a part of the theme of maintenance botany. A few extra seeds doesn't hurt anything, and there's no seed vendor in there. In fact, I'll probably remove the resupply canister.
> 
> the resupply canister is so you can build a seed vendor in maint botany, without building a resupply from cargo
> 
> i think he means the layout, atmoize the solars layout, you can move the airlocks here of course, then make a branch of this branch that changes solar layout (so that PR will require this one to merge firsr)

if people don't like the solars layout, I'll just change it. That's a lot of extra unnecessary work for something that's right next door and is still getting moved regardless.

**Comment by Zytolg** [comment]
He gave you what I did not.
Maintony

**Comment by ATH1909** [comment]
Does this keep the omegaweed seeds?

**Comment by Son-of-Space** [comment]
> 
> 
> Does this keep the omegaweed seeds?

Just regular weed seeds. I was informed that the special ones were removed in a maintenance loot sweep and I wanna keep things relatively on the level.

**Comment by Son-of-Space** [comment]
Quadruple checked this. Should be ready.

**Pull request merged**
