### PR TITLE
Adds nekomimetic, the felinid language

### PR DESCRIPTION
**Pull request by kriskog**
## About The Pull Request
Originally intended to be part of #48309.

image

## Why It's Good For The Game
Currently felinids are the only roundstart species without a language, this sees to that.

## Changelog
:cl: Skoglol
add: Adds nekomimetic.
/:cl:

### CODE REVIEW

**Comment by TomFulpWillard** [comment]
Felinids aren't unique enough of a race to have their own language. They're just humans with cat ears and a tail.

**Comment by GuillaumePrata** [comment]
> Felinids aren't unique enough of a race to have their own language. They're just humans with cat ears and a tail.

Yes, but we shouldnt use the argument of "they are only a human reskin" on a PR that tries to make em more unique, there were PRs that got closed in the past and had the same argument.
They need unique things to be a more interesting species, unless the goal is too keep em as a boring Human reskin...

**Comment by zxaber** [comment]
Ah yes. elegant and sophisticated language of hairball.

I know gameplay and lore are often separated by design, but it seems to me that for species-specific things, we should be bridging the gap a bit. Far as I recall, felinids are supposed to be genetically-modified humans in-lore. With that in mind, how likely is it that they'd actually have their own species-specific language?

**Comment by Tharcoonvagh** [comment]
Why not make it more.. uhh... cat related? I dont wanna feel like Im in an anime whenever a catperson speaks their language

**Comment by wesoda25** [comment]
Aren’t catgirls literally just genetically modified humans? It made sense that they didn’t have their own language.

**Comment by GuyonBroadway** [comment]
.Yes, but we shouldnt use the argument of "they are only a human reskin" on a PR that tries to make em more unique, there were PRs that got closed in the past and had the same argument.
They need unique things to be a more interesting species, unless the goal is too keep em as a boring Human reskin...

It's be nice if they had something to differentiate them from a gameplay perspective rather than going something that'll just enable meowtagaming. Currently every other nonhuman race has some kind of mechanical downside but felinids don't,

**Comment by RaveRadbury** [comment]
> Why not make it more.. uhh... cat related? I dont wanna feel like Im in an anime whenever a catperson speaks their language

Fear of Anime gives you a fear of felinids.

**Comment by boy2mantwicethefam** [comment]
Wowwwww, you meow like a cat! That means you are one, right? Shut the fuck up. If you really want to be put on a leash and treated like a domestic animal then that’s called a fetish, not “quirky” or “cute”. What part of you seriously thinks that any part of acting like a feline establishes a reputation of appreciation? Is it your lack of any defining aspect of personality that urges you to resort to shitty representations of cats to create an illusion of meaning in your worthless life? Wearing “cat ears” in the shape of headbands further notes the complete absence of human attribution to your false sense of personality, such as intelligence or charisma in any form or shape. Where do you think this mindset’s gonna lead you? You think you’re funny, random, quirky even? What makes you think that acting like a fucking cat will make a goddamn hyena laugh? I, personally, feel extremely sympathetic towards you as your only escape from the worthless thing you call your existence is to pretend to be an animal. But it’s not a worthy choice to assert this horrifying fact as a dominant trait, mainly because personality traits require an initial personality to lay their foundation on. You’re not worthy of anybody’s time, so go fuck off, “cat-girl”.

**Comment by Couls** [comment]
This PR is a mimichuu boop

**Comment by davethwave** [comment]
Dang, this makes me wish we could have circuits back just for the fact you could use them to create universal translators and link them to the coms system.

**Comment by Epsilos** [comment]
imagine if mice didn't hear the fake japanese, but just a bunch of synonyms for "KILL/EAT MOUSE" instead

**Comment by Qustinnus** [comment]
https://youtu.be/lTr13GV0iC8

**Review by 81Denton — COMMENTED** [review]
Let's work on something that makes the race more mechanically unique and also something that gives it an impactful downside (for example, plasmamen have their oxygen allergy and moths are vulnerable to flashes) before we implement a meowtagaming language

**Comment by 81Denton** [comment]
Let's work on something that makes the race more mechanically unique and also something that gives it a downside (i.e. plasmaman oxygen allergy or moth flash vulnerability) before we implement a meowtagaming language

**Comment by PKPenguin321** [comment]
😬

**Comment by optimumtact** [comment]
@81Denton this is already approved

**Comment by 81Denton** [comment]
oh I was grilling while you were discussing that in coding-general

**Comment by kriskog** [comment]
> 
> 
> Let's work on something that makes the race more mechanically unique and also something that gives it an impactful downside (for example, plasmamen have their oxygen allergy and moths are vulnerable to flashes) before we implement a meowtagaming language

The metagang argument was used against #48309 too, which literally added languages for all the other species. We survived that addition, we will survive this one too.
The other species have a balance between their drawbacks and upsides, while felinids dont really have either. Moths can eat clothes to max out mood really easily and fly in no-grav, but get flashed easier. Plasmamen needs a suit and breathing plasma, but are completely cold and radiation immune. 

Cats on the other hand are harassed on a regular basis, which leads to removal of every drawback anyone has ever added. Where's laser pointer leaping? Chocolate allergy? There are also no upsides of playing a cat, except you get the *wag emote. And I dont think there can be, because even just adding a completely harmless language to them leads to this kind of PR discussion.

**Comment by LemonInTheDark** [comment]
Holy fuck skog you said it wouldn't be done. madman

**Comment by GuyonBroadway** [comment]
>The metagang argument was used against #48309 too, which literally added languages for all the other species. We survived that addition, we will survive this one too.
The other species have a balance between their drawbacks and upsides, while felinids dont really have either. Moths can eat clothes to max out mood really easily and fly in no-grav, but get flashed easier. Plasmamen needs a suit and breathing plasma, but are completely cold and radiation immune.

Cats on the other hand are harassed on a regular basis, which leads to removal of every drawback anyone has ever added. Where's laser pointer leaping? Chocolate allergy? There are also no upsides of playing a cat, except you get the *wag emote. And I dont think there can be, because even just adding a completely harmless language to them leads to this kind of PR discussion.

Well presently they are getting the upside of a communication channel nobody else besides the librarian is privy to at the downside of...

uh...


Yeah nothing worth mentioning, sure they "take more hearing damage from bangs" but they can neagte that with a quick trip to the chemist for some of that hearing healing chem or just borrow a bowmans. No other race gets to negate their racial disadvantage that easily.  The reason no other race in the game gets Pr discussions like these because no other race in the game gets as many PR's like these and no other race in the game has ended up as functionally humans with no notable upsides or downsides. Whenever someone tries to do a PR like this for other races you DO get this level of discourse, see the time someone tried to port digitgrade shoes from citadel for more information.

**Comment by kriskog** [comment]
Every other species has their own language, you dumbass.

**Comment by wesoda25** [comment]
lmao maintainers using the prs they reverted to justify other prs. Maybe don't revert those things???

**Comment by GuyonBroadway** [comment]
>Every other species has their own language, you dumbass.

'Cept human, and every other species is mechanically different from human 'cept cats.

**Comment by ReplicantTerry** [comment]
Alternative idea, make it so that only cats with the foreigner trait get this language, instead of uncommon as they speak currently. The upside is they get their meowtagaming language, the downside is they lose the actual useful language.

**Comment by Timberpoes** [comment]
Or we can just add a new language for felinids without being salty children.

The laser pointer jump was merged. The cool claw mutation was not. Every other nonhuman species has a language unique to them. You're not covered under Asimov. You're not able to roll a head role.

The entire point of this PR is to give felinids something to distinguish them from baseline humans. A language is a fairly benign addition that accomplishes just that.

You can argue all you want that felinids are just mutated humans. This PR seeks to change that status quo and push them more towards a more unique species.

**Comment by cacogen** [comment]
aren't moths bad enough

**Comment by actioninja** [comment]
no

**Comment by IndieanaJones** [comment]
Felinid should be a race of solely nerfs.

**Comment by AffectedArc07** [comment]
nya

**Comment by ReplicantTerry** [comment]
can silicons understand and speak this?

**Comment by GuyonBroadway** [comment]
>Law 4: If its name ends in -kun it's exempt from law 1

**Comment by kriskog** [comment]
> 
> 
> can silicons understand and speak this?

Forgot to add it to them, thanks

**Comment by carshalash** [comment]
Based

**Comment by Jared-Fogle** [comment]
Does the curator know it?

**Comment by GuyonBroadway** [comment]
This "language" would be significantly less terrible if it wasn't basicaly shit-weeaboo-memease, like half that crap would get you a talking to for breaking what little rp rules there are on the lowrp servers. To say nothing of the medrp servers.

**Comment by Acer202** [comment]
> This "language" would be significantly less terrible if it wasn't basicaly shit-weeaboo-memease

I agree a bit. It would be nice if it were a collection of cat noises, like "mrrp, trrr, eow, row, ch, hss, eoow" and so on. Cats make lots of noises, from chitters, purrs, mrrps, meows, hisses, chirps, chatters, and such. Please enjoy some talking cats:

https://www.youtube.com/watch?v=Dsu2d6kIRfI

At the same time, though, the fear of anime thing lines up with how this is pretty well, so maybe it's best to stay as it is. Something to consider.

**Comment by san7890** [comment]
I don't see what the issue is when it comes to "EW WHAT THE FUCK THEY SOUND JAPANESE I DISLIKE THIS INTENSELY" when Moffic is just random Nordic language. It wouldn't be nearly as interesting (or funny), and more-so hamfisted, if we changed Moffic to "Bzz Flutter Fly Lamp" whatever.

**Comment by cacogen** [comment]
>I agree a bit. It would be nice if it were a collection of cat noises, like "mrrp, trrr, eow, row, ch, hss, eoow" and so on. Cats make lots of noises, from chitters, purrs, mrrps, meows, hisses, chirps, chatters, and such. Please enjoy some talking cats:

anime or furry, pick your poison

**Comment by kriskog** [comment]
> 
> 
> Does the curator know it?

He gets all, it works off language subtypes

**Comment by Acer202** [comment]
> anime or furry, pick your poison
Aye, one of the choices implies that felinids developed and learned their own clique meme language while the other implies they understand cat noises because cat DNA or something. I can't tell which is better to go with, but I thought I'd pitch the idea since they like laser pointers now because cat DNA anyways.

**Comment by Rohesie** [comment]
I hate this, very cursed.

**Comment by Moja10** [comment]
Gonna close this PR soon, didn't like the code quality. The words chosen for their language were subpar uwu fucky  wucky words at best, dog porn at worst. Overall, you need to step up for future PRs. You are doing your best! I believe in you!

**Review by Twaticus — APPROVED** [review]
i like the icon

**Comment by AffectedArc07** [comment]
Fucking power move

**Comment by Orchian** [comment]
The madmen did it, they actually did it

**Pull request merged**
