### PR TITLE
Security Officers start with Krav Maga Gloves

### PR DESCRIPTION
**Pull request by Iamgoofball**
Krav Maga was originally designed as the anti-tider. It allows you to kick the shit out of assistants who walk up to your brig, break the windows, and bait you into attempting an arrest so they can kill you and steal all your gear in self defense. It's only really good for this, because it does not match up against ranged weapons at all, having no defense or counter against it. Punching isnt gonna do anything against a flamethrower or a shotgun, but it will stop the assistant with a toolbox.

If you get your gloves stolen as a security officer somehow with this, I'd be really suprised, and that assistant deserves the reward.

Plus, imagine all the cool kung fu combat fights between sleeping carp traitors and krav maga security officers!

:cl: Iamgoofball
rscadd: Security Forces now start with Krav Maga gloves.
/:cl:

### CODE REVIEW

**Comment by callanrocks** [comment]
Have you tried not being shit at sec?

**Comment by PKPenguin321** [comment]
YOU RETARD YOU'RE SUPPOSED TO LET ME DO IT NOW THAT IT HAS YOUR NAME ON IT IT'S GONNA GET SHITPOSTED ON

**Comment by PKPenguin321** [comment]
OH GOD IM ALREADY TOO LATE

**Comment by kevinz000** [comment]
Security DOES NOT NEED KUNG FU AND THIS IS COMING FROM A SECURITY PLAYER.

**Comment by Iamgoofball** [comment]
actually I'm gonna let the experts do this

**Comment by Bawhoppen** [comment]
PKP this was retarded it doesn't matter if its goof

also this literally makes no sense from any angle
:-1: x :100:

**Comment by Man-Shroom-** [comment]
If the roundstart Krav Maga gloves go in then I demand that stungloves be added back into the game as well, since the only argument against stungloves was 'you can't disarm them.' If this goes in, it will set a precedent for weapons that cannot be disarmed, and thus stungloves should be allowed

Side note: Goof, krav maga has been in the game for all of 7 minutes and you are trying to give it to sec now come on lad

**Comment by PKPenguin321** [comment]
>Goof, krav maga has been in the game for all of 7 minutes and you are trying to give it to sec now come on lad

this may or may not have been the purpose of krav maga

**Comment by Man-Shroom-** [comment]
lad

**Pull request closed without merging**
