### PR TITLE
Tweaks to robo-tourists

### PR DESCRIPTION
**Pull request by ghost**
:cl:
balance: Robotourists pay more for food now
qol: Only one robo-tourist will wait at the door at any time, preventing constant spam if you only have 2 seats.
qol: more variation in robo-tourist colors
/:cl:

just some small tweaks, chef is way worse off than bartender right now and if I want to kill bounties for chefs in the future the only way is for prices to go up.

Colors are a bit more varied now as well, a lot of them ended up being grey due to the high rgb colors.

### CODE REVIEW

**Comment by Time-Green** [comment]
A+! I keep getting panic attacks trying to make a baguette so the bots overwhelming you less is great

Can you make bots make like sparks when they leave? They just dissapear and it’s quite jarring

**Comment by wesoda25** [comment]
Can you please make it so that they don't have insane health values? Invincible objects are bad for the game.

**Comment by Qustinnus** [comment]
image

**Comment by Qustinnus** [comment]
stop trying to kill the chef's bots wesoda or i will make them gib any mob with your ckey

**Comment by Pugie** [comment]
If they die they die stop obsessing over protecting your rp creations. If someone smashes barbot they just get shot and that's life.
We don't give other types of robots 1000hp do we? If they die that's fucking LIFE they respawn anyways

**Comment by wesoda25** [comment]
Oh I thought they were still on 100000000000000 health, 1000 is better but still a bit ridiculous. If someone wants to be a dick to the chef and break them, let them be a dick and break them. It's an IC issue that players will handle IC.

**Comment by Qustinnus** [comment]
no thanks. maybe when admins don't let people bait chefs into getting into fights all round.

**Comment by Pugie** [comment]
Sorry but the separation between code and adminning is absolute >w<

**Comment by Qustinnus** [comment]
which is why the health doesn't change.

**Comment by wesoda25** [comment]
Qustinnus explained on discord that the health is a bandaid solution until we get robot retaliation to attacks so I guess my complaint was a little mislead. Assuming it doesn’t take too long I’m content to wait.

**Comment by cacogen** [comment]
>Only one robo-tourist will wait at the door at any time, preventing constant spam if you only have 2 seats.

Thank God for that. Hopefully it makes a meaningful difference to the overwhelm.

The food prices are still nothing compared to bounties, though. Again, why would a cook put in all that effort if they see assistants selling pot plants or whatever for similar amounts with less work? Removing bounties to railroad them into cooking for tourists will be especially egregious if the prices don't reflect a similar amount of work. People won't even use the feature if they don't feel it's worth their time.

**Comment by Qustinnus** [comment]
@cacogen like I told you the last 2 times, feel free to suggest or PR better prices.

**Comment by cacogen** [comment]
Sorry, I haven't seen that. 

If I were doing it I'd time making the dishes and some of the bounties and make the pricing equitable based on that. Maybe define pricing tiers based on every few minutes it takes. 

I don't like the bounty system as it is currently either so I don't know it that well but from what I've seen collect 12 pot plants is like 400 cr and the lowest tier assistant bounties are like 140 cr for a strange object found in maint so I'd probably start pricing around there. 

Ideally I would make a system to automatically calculate the minimum time spent to at least have everything in a logical order price tier wise. You could use  minimum griddle time and crafting time, for example. Everything that takes a predictable time dictated by the game.

You could also add stat tracking to figure out the median time taken by players to complete each order. That might be the most accurate way of pricing things.

**Comment by Mothblocks** [comment]
why are you all talking about health, this pr doesn't do anything about that

**Comment by Kylerace** [comment]
> 
> 
> why are you all talking about health, this pr doesn't do anything about that

the bikeshed is nice this time of year

**Pull request merged**
