### PR TITLE
Cleans up explosives at syndie base

### LINKED ISSUE #31637: Monkeys from the lavaland syndicates outpost can pull out bombcores from the walls.
Neuroplasty reported this earlier but closed their report.

Weird!

### PR DESCRIPTION
**Pull request by ShizCalev**
Fixes #31637

If the wall is bombed it will explode. The wall can be dismantled with a welder to extract the explosive charge.

### CODE REVIEW

**Comment by Darkgenerallord** [comment]
bad fix, let me use them as grenades

**Comment by ShizCalev** [comment]
Actually yeah, that's only half-fixing it. One sec.

**Comment by Dorsisdwarf** [comment]
replace every wall in the syndiebase with these walls. None shall survive.

**Comment by ShizCalev** [comment]
@Dorsisdwarf That'd be hilarious. Would do it in another PR unless requested to make the change, however.

**Comment by ShizCalev** [comment]
That said, I would like @KorPhaeron to chime in if they'd prefer;

1) The walls to explode when cut open with a welder (as if it were an anti-tamper/self-destruct measurement to prevent people from breaking in)
or
2) If they're fine with the explosion only being triggered when the walls are bombed and dropping the bombcore when dismantled (which is how the PR currently is to maintain old behavior.)

**Pull request merged**
