### PR TITLE
Make the spelling of analyzer consistent through the code base

### PR DESCRIPTION
**Pull request by ORCACommander**
## About The Pull Request

analyser was only used 17 times in the code base including changelogs, analyzer was used 610 times. Changed all instances of analyser in core files to analyzer to increase consistency and search-ability.

## Why It's Good For The Game

search engine optimization

## Changelog
:cl:
spellcheck: cleaned up what analyzer is used
/:cl:

image

image

### CODE REVIEW

**Review by Mothblocks — APPROVED** [review]

**Comment by Mothblocks** [comment]
if ur really bored you can put it in check_grep.sh too

**Comment by optimumtact** [comment]
It's explicitly forbidden to change spellings of things between american -> english as the only outcome of a PR

**Comment by optimumtact** [comment]
also if you are going to try to force one or the other, I'm going to pick the british spelling.

**Comment by ORCACommander** [comment]
> 
> 
> It's explicitly forbidden to change spellings of things between american -> english as the only outcome of a PR

https://camo.githubusercontent.com/65c75dda3a26cb2210f29d906a0213251f896933a7c8e201791c4f9df69c78fb/68747470733a2f2f66696c652e686f7573652f6c386c4e2e706e67

Your denial is completely wrong versus the guidelines you screenshotted. "Generally frowned upon" does not mean forbidden, its the same line of judging someone for wearing socks with their sandals. I didn't write this pr to be pedantic. One of my players spent far to much time trying to find the Chemical Analyzer when following _your tutorial documents._ I threw it to a tg pr pull because i hate merge conflicts and this would eventually trickle down to my server and i would not have to maintain override files or core file edits.

Quite frankly i would have had no problem with you saying no if it was just" well there little to no gain to be had here despite someone having done the leg work and another staff member has signed off on it but then...

> 
> 
> also if you are going to try to force one or the other, I'm going to pick the british spelling.

And that right there is where you crossed the line from guidelines enforcement to being a dick

I'm not trying to enforce american vs uk. I am trying to enforce consistency. 610 vs 17. Your tutorial documents use the American spelling and so does 97% of the rest of the game and its not like its a flavor text section where a regional spelling variant does not matter. this has to deal with internal ID's and how the UI searches for items

**Comment by optimumtact** [comment]
please dm me on discord if you have any more concerns

**Comment by Mothblocks** [comment]
To be clear, had I looked up "analyser" and learned it wasn't just a typo, I would've done the same thing 🤷

**Pull request closed without merging**
