### PR TITLE
remove human requirement for invisible_wall

### PR DESCRIPTION
**Pull request by lizelive**
mime borg is hilarious
## About The Pull Request

remove human requirement for invisible_wall

## Why It's Good For The Game

mime borg is hilarious

## Changelog

:cl:
balance: remove human requirement for invisible wall
/:cl:

### CODE REVIEW

**Comment by san7890** [comment]
this is probably fine because at least you can law 2 a borg to stop making invisible walls

**Comment by carlarctg** [comment]
> this is probably fine because at least you can law 2 a borg to stop making invisible walls (or even law 2 it to break it's vow (is that how it works??))

crimes against mimanity

**Comment by lizelive** [comment]
> crimes against mimanity

funny thing : mime ai can't break oath and oath prevents stating laws. leads to some classic mime moments while sec is beating you to death for not stating laws

**Comment by Livrah** [comment]
Why only the wall?

**Comment by lizelive** [comment]
> Why only the wall?

borgs cant really use boxes or chairs.

**Comment by Helg2** [comment]
I think he meant the advanced mimery, such as finger gun and etc.

**Pull request merged**
