### PR TITLE
Removes multiverse sword once again from wizards

### PR DESCRIPTION
**Pull request by lzimann**
:cl: Lzimann
del: Multiverse sword is no longer buyable by wizards
/:cl:

This is absolutely garbage and I have no idea why it was added again

### CODE REVIEW

**Comment by Arianya** [comment]
Probably doesn't need outright removal, more just needs some modifications to make it interesting/not deathmatch.

**Comment by Armhulen** [comment]
its for the best

**Comment by Aloraydrel** [comment]
adios 10 minute gamemode

**Comment by KorPhaeron** [comment]
Last time it was removed people said they'd want it back if it had huds.

It now has huds. Can we poll players on it?

**Comment by lzimann** [comment]
hud doesn't solve the problem of it being incredible annoying and shit though

**Comment by KorPhaeron** [comment]
Can't you just not play for ten minutes if you dislike it though? Obviously enough people do that it keeps getting picked

**Comment by lzimann** [comment]
it's happening every wizard round though, and it's a thing that should be admin-only and very ocasionally in my opinion

**Comment by Iamgoofball** [comment]
@lzimann shiny toy syndrome, everything gets run into the ground the first week how do you not realize this

give it another week and they'll forget about it

**Comment by lzimann** [comment]
nah, last time it happened the same thing, this thing won't improve/be more enjoyable with time, it will stay bad and unpleasent

**Comment by KorPhaeron** [comment]
If it's not enjoyable why are so many people taking it then

**Comment by lzimann** [comment]
because it's a big "fuck you all" button that one person has control over

**Comment by lzimann** [comment]
also if this gets closed I'll make multiverse an actual preference so people that don't like/want it have a better way to always opt out instead of having to disable wizard's pref all the time

**Comment by KorPhaeron** [comment]
Imagine a cult round where you couldn't convert people without the cult pref on

**Comment by Aloraydrel** [comment]
Rather have summon guns/magic spam honestly compared to multimeme

**Comment by XDTM** [comment]
If the mode stays i'd like that preference too, i can't observe without instantly being pulled by some guy making a clone. After all, unlike cult, it's not conversion, it grabs a ghost.

**Comment by KingPhilipIII** [comment]
I don't see why this is such a problem. Honestly you spend more time spectating when you get murdered early in the round and your corpse annihilated. What's ten minutes. 

As far as being a big 'Fuck Everyone' button, while the player base can be a bit aggressive, I think that's being unfair. If I pick Multiverse War, it's because I have fun doing battle with the crew with my legion of randomly dressed minions.

**Comment by KorPhaeron** [comment]
@XDTM 

Yeah, but you get banned if you suicide or ghost once converted so you're still being forced to play

@lzimann 

If you can make the multiverse preference default to on I'll merge it

**Comment by Supermichael777** [comment]
having played a memeverse round adding huds was a flimsy dodge to dispose of all the issues people had with it as "Resolved"

**Comment by Supermichael777** [comment]
Hell run a server poll

**Comment by KorPhaeron** [comment]
How is adding exactly what people asked for a flimsy dodge

**Comment by ShadowDeath6** [comment]
Using conversion antags as a reference to not having a preference for a ghost role isn't a good comparison, considering that people who are dead /clicked observe have original bodies or have opted to or not to play the game. Imagine if swarmers pulled ghost roles, people would have their possible cloning / defib fucked over and all the people who just want to watch the round progress would either be forced to play or be a detriment to the antag all around. 
Conversion antags are different, as it doesn't create an entirely new body for your key, you still get to do the stuff that you planned to do in the round provided it wasn't some dumb antag hunting thing.

**Comment by JJRcop** [comment]
Bad idea: grab the closest ghost to the wielder

**Pull request merged**
