### PR TITLE
Prisoners can actually eat now.

### PR DESCRIPTION
**Pull request by BeeSting12**
[Changelogs]: # (Your PR should contain a detailed changelog of notable changes, titled and categorized appropriately. This includes, new features, sprites, sounds, balance changes, admin tools, map edits, removals, big refactors, config changes, hosting changes and important fixes. An example changelog has been provided below for you to edit. If you need additional help, read https://github.com/tgstation/tgstation/wiki/Changelogs)

:cl: BeeSting12
fix: Sustenance vendors are free.
/:cl:

Sustenance vendors should be free so perma prisoners can eat without having to pay.

### CODE REVIEW

**Comment by Iamgoofball** [comment]
@BeeSting12 They were already free, they're an Offstation Vending machine

**Comment by Barhandar** [comment]
No they aren't free lol.

**Comment by Iamgoofball** [comment]
i forgot about the permabrig one lmao

👍

**Comment by FantasticFwoosh** [comment]
Pity prisoners can't raise $50 bucks for a cup of coffee (enough to survive a space journey) by doing prisoner activities and interacting with other inmates.

**Review by SpaceManiac — APPROVED** [review]

**Pull request merged**
