### PR TITLE
Changes Admin Prison to be Anti-Telekinesis: Walls off equipment rooms, replaces computers, and makes the tables tidy

### LINKED ISSUE #60967: Admin prisoned players with Telekinesis can access visible consoles
## Reproduction:

If a player with Telekinesis is put into the admin prison they can interact with various consoles in their view range, one of these includes a security record console which they can use to alter security records and/or purge them, which is something we ideally don't want admin prisoned players doing

### PR DESCRIPTION
**Pull request by epicgamer545**
First PR, may require some changes or something because I don't know how to do anything bleh
## About The Pull Request

We already had issues with crewmembers with telekinesis making changes to the security records (purging them and what not). And, nothing has been done about it, not yet, anyway. Not only record computers are a problem as well.

image
Previously, prisoners can access the sec vendor with telepathy, and, since the vendor is free, spam the vendor and be an annoyance. Sure, I believe that it is not as big of a problem as purging the security records, but I feel like it's against what the prison is supposed to stand for; It's supposed to stop them and get them to listen to ahelps thrown at them.

I've decided to make a bit of changes to the prison to make it so that people with telekinesis won't fuck up things as much. This replaces real computers with nonfunctional ones, adding walls to equipment areas to make sure prisoners don't spam the vendor, and deletes guns/weapons from the tables so they won't grab them.

## Why It's Good For The Game

image
This PR is more tailored to admins dealing with no-good-doers, and goes for the vibe of "HEY, SOMEONE IS PMING YOU, REPLY TO THEM INSTEAD!" Of course, this leads to prisoners not interacting with the current round, and, less chance of them going insane and breaking all the windows with a telekinesis auto-rifle.

Plus, this can always be reverted in-case someone comes up with coding stuff in instead. I'm all through with that and willing to work with whoever to solve the issue.

Also, of course, Closes #60967

## Changelog

:cl:
admin: Nanotrashen made some top-of-the-line changes to their top-of-the-line prison by walling off their equipment area and removing some spare guns they somehow left on the tables. We also stole the security computers, so people with telekinesis can't access them.
/:cl:

### CODE REVIEW

**Comment by OceanFish1** [comment]
I think telepathy and telekinesis are two different things

**Comment by epicgamer545** [comment]
> I think telepathy and telekinesis are two different things
fuck

> if you have x-ray you can still mess with things so this is a half-solution
Even if you did have X-ray, the things you could do is less severe than what you could do before, but, yeah, this is a half-half.

**Comment by ZephyrTFA** [comment]
I mean, its a "admin only" level. Why not just have it use showcases instead. And just not have the actual console there

**Comment by san7890** [comment]
one day admin prison will just be a 1x1 cube surrounding by "NO ERP" posters and i'm okay with that. if admin prison didn't help "fill out" the size of centcom i would have already done that.

**Comment by epicgamer545** [comment]
I'm happy to see I could help (even by doing minor changes)

**Comment by Iamgoofball** [comment]
why is admin prison not just a 3x3 cube in space

**Comment by epicgamer545** [comment]
> why is admin prison not just a 3x3 cube in space
admin prison: ultra-1984 edition

**Pull request merged**
