### PR TITLE
unfucks filters

### LINKED ISSUE #31595: Mapping is broken by gas ID refactor
#31528 broke mapping.

Saving any map after it was merged causes the following to be written to the map file, and for DM to error when loading the saved map;

2f9gace

### LINKED ISSUE #31596: Gas filters seem to be having some issues
It's currently impossible to select any gas other than 'Nothing'. A player reported it, I tested it with the same filter, can't change it to any other gas. Different filter, no luck. 

Server revision 7531b5, only testmerge is Kevin's flying thing.

### PR DESCRIPTION
**Pull request by duncathan**
Fixes #31595
Fixes #31596

my name is dunc and i break things for a living

### CODE REVIEW

**Comment by duncathan** [comment]
oh ffs my branch was dirty?

**Comment by optimumtact** [comment]
yes it was

make sure you make each branch of the latest master
```
git fetch upstream
git checkout -b newbranch upstream/master
```

**Comment by duncathan** [comment]
these commits are already on our master so w/e i guess

**Comment by duncathan** [comment]
quickmerge would be lovely cuz currently mapping is broken

**Comment by ShizCalev** [comment]
Need to change it on the maps too, otherwise this is only half-fixing it.

**Comment by duncathan** [comment]
oh what i swore i did that weird

**Comment by ShizCalev** [comment]
The fetch reverted some of your stuff from the looks of it.

**Comment by duncathan** [comment]
@ShizCalev done

**Pull request merged**
