### PR TITLE
Removes morphine from nurse spiders, other spider rebalances

### LINKED ISSUE #20752: Spiderwebs have the wrong icon set
@phil235 `jarektheraptor | The webs are broken for spiders, they spawn tables with smiley faces.`

### PR DESCRIPTION
**Pull request by Shadowlight213**
Removes morphine from nurse spiders
Fixes spider web, cocoon, spiderling sprites
Halves cocoon breakout time, fixes camera going to nullspace
Fixes #20752

:cl:
del: removed morphine from nurse spiders
tweak: cocoon breakout time is faster
fix: Spiderwebs are no longer tables
/:cl:

### CODE REVIEW

**Comment by PKPenguin321** [comment]
about time we got rid of the morphine

**Comment by Anonmare** [comment]
The morphine used to be literally Hitler

**Comment by Supermichael777** [comment]
SPIDERS ARE SUPPOSED TO BE MY ADMIN FAP ROUND ENDER REEEE
/s

Good stulf

**Comment by PKPenguin321** [comment]
Fixes https://github.com/tgstation/tgstation/issues/20752

**Pull request merged**
