### PR TITLE
Merges together many jobs.

### PR DESCRIPTION
**Pull request by TheAssistant**
Roboticist has been merged into Scientist.

Cargo Technician and Shaft Miner have been merged into Quartermaster.

Atmos Tech has been merged into Engineer.

Virologist, Chemist, and Geneticist have been merged into Medical Doctor.

All possible job slots are now available to people joining at roundstart.

The same amount of job slots available before are available now.

This is to allow departments to work together easily without arguments over who has what job. Science works this way, and it works well.

### CODE REVIEW

**Comment by Incoming5643** [comment]
Seems like a huge loss of identity for little gain.

Low pop extended access for jobs largely do what this does, without you know, communism.

**Comment by Chocobro** [comment]
:-1: vastly unnecessary.

**Comment by TheAssistant** [comment]
how so?

people already go to the HoP line and get access to the other areas in their department roundstart anyways, why not skip the process?

**Comment by GunHog** [comment]
:-1: This is something Heads of Staff should be able to handle in their own departments. They need a way to alter the access of people in their own department, whereas the HoP would manage department changes, giving the clown all-access, etc.

**Comment by TheAssistant** [comment]
@GunHog using an ID console as a head of staff already lets you do that, yet it doesn't get used ever

**Comment by GunHog** [comment]
Yes, I am referencing that. You have to <b>go to the bridge</b> to do that, at which point it is easier to just send the person to the HoP. I wanted to try giving heads their own consoles, but that got shot down.

**Comment by Cheridan** [comment]
Yeah, like @Incoming5643 stated this is basically already a config option.


*Atmos + Engineer:* Some merit. With the addition of hardsuits, Atmos is basically engineers with minus some tools and gloves. So this seems ok. It's annoying that Engineers can't access air alarms. Downside is it's more people with access to messing with the singularity.
*Cargo Tech + Miner:* No merit. There are only 3 mining hardsuits, so if all...6? of them want to mine they have to box it out or whatever. Cargo tech was added in the first place because 3 QMs were basically too strong, they would just all get yellow gloves and RCDs and build forts just for the heck of it.
*Virologist, Chemist, and Geneticist + MD:* Little merit. For Viro, Chemist, and Geneticist, this is a bad change. Those jobs would now be overcrowded. Can you imagine 3 people trying to do Virology at once? Holy shit. This mostly benefits bored doctors, but if all the doctors are off playing with genetics or whatever then who is actually waiting to heal people?

**Comment by hornygranny** [comment]
I can see Atmos + Engineering, the others no.

**Comment by Chocobro** [comment]
you've merged cargo techs and shaft miners into qms. as I said the last time someone attempted this, there is only one quartermaster in a cargo bay, naval or commercial. everything goes through him. having multiple is a terrible, unrealistic idea. along with that, it would entirely erase any chain of command in the cargo bay, something that roleplay desperately relies on.
I see entirely no point in having an atmos tech suddenly be an engineer. they're supposed to be experts in one thing, and that's atmos. i'm not going to pretend they also know how to set up a black hole safely.
virologist, chemist and geneticist all do very different, but equally important jobs. turning it into another science department means you should basically rename them to be scientists.
this will also get flack from people who genuinely prefer their special job names.
all in all :-1:

**Comment by TheAssistant** [comment]
@Cheridan @hornygranny 
what about scientist + roboticist?

as right now roboticist is just scientist with robot access at roundstart basically

**Comment by PKPenguin321** [comment]
Pretty sure someone tried this once before but only with cargo all merging into QMs, it got shot down instantly.
Aside from that, big :-1: from me. I see no real value in doing this. Departments are separate for a reason.

**Comment by ike709** [comment]
:-1: 
No... Just... No. I shouldn't even have to explain why this is a horrible idea.

**Comment by optimumtact** [comment]
There was an attempt

**Comment by duncathan** [comment]
:-1:
The only thing this is good for is lowpop but wait we have skeleton crew for that don't we.

**Comment by Fox-McCloud** [comment]
:-1: 

No...just...yeah, not going to bother formulating an argument against this.

**Comment by Aranclanos** [comment]
>account created today
>only one PR
>sole purpose of making people argue

have a donger
8====D

**Comment by Cheridan** [comment]
it made some discussion at least

**Comment by Miauw62** [comment]
currently considering just purging this PR

**Comment by Thunder12345** [comment]
End it. End it all.

**Comment by TheAssistant** [comment]
Some very good feedback was given here. I see now why this is a bad idea.

**Pull request closed without merging**
