### PR TITLE
READY DONK UPDONKATED

### PR DESCRIPTION
**Pull request by EOBGames**
## About The Pull Request
**READY-DONK'S BACK!!**
image
Gives a (sorely needed) new lick of paint to Ready-Donk. The sprites are based off of the import vendor trays from Skyrat (https://github.com/Skyrat-SS13/Skyrat-tg/pull/16215), originally by Paxilmaniac, and I think they really help nail the microplastic-laden ready meal aesthetic that Ready-Donk was always meant to embody.

As a fun extra, I also threw together some sprites for some TV dinner classics, Salisbury Steak and Country-Fried Chicken, and figured I might as well go the extra mile and actually add them in.
## Why It's Good For The Game
More Ready-Donks means more sodium for the crew, and more sodium equals more gooder.

Also, if I'm being honest with myself and with everyone else, the current crop of sprites for Ready-Donk never really captured the feel I was aiming for with them; this new set is both generally better (I think, anyway) and actually looks like what it's meant to be.
## Changelog
:cl:
add: DONK CO. HAS UNVEILED A NEW RANGE OF READY-DONK PRODUCTS! GET THEM AT CARGO TODAY!
image: READY-DONK: NEW LOOK, SAME GREAT TASTE
/:cl:

### CODE REVIEW

**Comment by Dawnseer** [comment]
The chefs are never going to recover

**Comment by necromanceranne** [comment]
Finally, the visceral revulsion I get looking at microwave meals at the supermarket, in-game!

**Review by Wallemations — APPROVED** [review]
Disgusting, great job!

**Comment by Paxilmaniac** [comment]
beautiful

**Pull request merged**
