### PR TITLE
Removes very dumb song references from the fox descriptions

### PR DESCRIPTION
**Pull request by Iamgoofball**
how did this make it past the great firewall of meme removal

### CODE REVIEW

**Comment by Supermichael777** [comment]
it could have been left if it repeated things like poly. dead mice also make a reference by the way.

**Comment by PKPenguin321** [comment]
what happened to that rare description PR

**Comment by Incoming5643** [comment]
It was a joke

**Comment by WJohn** [comment]
But... memes! How could you?

**Comment by Cheridan** [comment]
>GOOFBALL COMPLAINING ABOUT MEMES

**Comment by PKPenguin321** [comment]
>It was a joke

it shouldn't have been

**Comment by pudl** [comment]
The description is, hilariously enough, not a reference to the internet meme. In the PR, Nien didn't know what a fox said (it originally purred) and he added the "I wonder what it says?" only after he changed the noise to geckers.

**Comment by bgobandit** [comment]
>not a reference

this is like ian not being Ein

**Comment by Iamgoofball** [comment]
aran MVP

**Pull request merged**
