### PR TITLE
DEFIB: Splits up "no heart" and "body too old" messages

### PR DESCRIPTION
**Pull request by Iamgoofball**
This was confusing new players.

### CODE REVIEW

**Comment by TechnoAlchemisto** [comment]
have their been many situations where bodies do not have hearts

**Comment by coiax** [comment]
There was a round where the CMO replaced the heart of someone via surgery in assumption that would allow for successful defibs. Just put a TOO LONG DEAD message or something.

**Comment by Core0verload** [comment]
@TechnoAlchemisto, it's pretty common when abductors are around.

**Comment by PKPenguin321** [comment]
haha yeah i remember being dead once and the CMO kept dragging me away from the other doctors when they were trying to clone me saying "HE NEEDS A HEART TRANSPLANT"
:+1:

**Comment by Shapsy** [comment]
Hey goof while you're fucking around in there with the defib, could you move the "patients chest is obscured" warning to before the big delay for putting the paddles on the chest, it's painful seeing people waste time trying to shock a hardsuited guy.

**Pull request merged**
