### PR TITLE
Modification of last PR, makes spec ops good for breaching and good against grenades that cause damage via air. New knockout crate for Emagged supply consoles

### PR DESCRIPTION
**Pull request by ma44**
Old PR: https://github.com/tgstation/tgstation/pull/19416

All in title

Feel free to discuss

### CODE REVIEW

**Comment by PKPenguin321** [comment]
???

**Comment by PKPenguin321** [comment]
What does this accomplish? Now the emagged crate sucks and the new crate you added just has randomly assorted crap. Both crates are now pointless. I don't understand why you thought this was the best compromise?

**Comment by Zilenan91** [comment]
Yeah neither of these crates do anything

**Comment by TechnoAlchemisto** [comment]
Smoke grenades fucking suck and these crates aren't very good.

**Comment by jughu** [comment]
>knockout kit 1500 points just for a simple sleepy pen with just some useless as fuck grenades

>special ops crate sleepy pen and fire emp smoke grenades for 2000

Its very overpriced and replace the smoke grenades with custom ones maybe filled woth uh chloral hydrate or whatever knocks you out

**Comment by Bawhoppen** [comment]
smoke grenades better than I used to be I buffed them with a sweet ass sprite and desc bitches

**Comment by Aloraydrel** [comment]
Gross

**Comment by KorPhaeron** [comment]
Does not seem popular, sorry

**Pull request closed without merging**
