### PR TITLE
Fixes #2878, Zeroth laws can be removed with core boards

### LINKED ISSUE #2878: OneHuman is impossible to remove
##### Revision that this bug was encountered on (REQUIRED!! Type 'show-server-revision' ingame to find out - note that 'current revision' isn't helpful!): #####
89d684a244916e0dec408642af1706b0e0826a5e

##### Which server were you playing on? (REQUIRED!! e.g. TG-Sibyl1, TG-Sibyl2, Badgerstation, Facepunch, Pinkstation, /VG/... etc.) #####
Urist McStation

###### What did you expect to happen? ######
To be able to purge or otherwise overwrite a OneHuman upload on an AI.

###### What happened instead? ######
Squat. Purging, giving it a new core module, and resets all do nothing to remove OneHuman.

###### Why is this bad/What are the consequences? ######
An unsuspecting crew resetting/purging/re-Asimoving the OneHuman'd AI only to have it strike again.

##### Steps to reproduce the problem (remember to be specific! Those little details can save us hours of work!): #####
1. Upload OneHuman
2. Purge/reset/Asimov AI
3. Check laws with the admin command, note how the OneHuman law is still there
4. Cry
5. Upload lawset that doesn't care about humanity/kill AI/beg for your robot overlord's mercy

##### Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?): #####
Nothing.

##### Anything else? #####
I can only assume this is a consequence of OneHuman uploading into the zeroeth slot, like the traitor AI law, making it impossible to remove. This is something fairly easy to get around, namely by uploading PALADIN, Corporate, or Tyrant, but it's still pretty weird.

### PR DESCRIPTION
**Pull request by Jordie0608**
Fixes #2878

Zeroth laws aren't removed from antag AIs however the functionality is added with this.

### CODE REVIEW

**Comment by GunHog** [comment]
This creates normal and expected behavior. Purging a one-human AI and hitting it with normal Asimov is expected to work, so it should. :+1:

**Comment by tgstation-server** [comment]
Zero laws are treated that way because they are suppose to be special. I
think it makes more sense to remove ways you can add zero laws

**Comment by Jordie0608** [comment]
OneHuman is the only non-antag way to get zeroth laws.

**Comment by Supermichael777** [comment]
one human is a defanition right?
just make it append to the end of the law-set

**Comment by phil235** [comment]
merge conflict

**Comment by Jordie0608** [comment]
Resolved

**Pull request merged**
