### PR TITLE
Take 2: Adjust the firelocks in service sector of Icebox

### PR DESCRIPTION
**Pull request by fippefi**
## About The Pull Request

From the top and all over again. Re-do of the #66820, this time from a branch instead of being a stupid dummy. :)

Orig description:
Removes firelocks from botany and service airlocks on the 2nd Z-level, puts firelock on botany maint instead. This stops the constant fire alert spam. Besides, what are we trying to protect from with these firelocks, the snow?

## Why It's Good For The Game

Fixes the fire alert spam in botany and service back corridor.

## Changelog

:cl: fippe
fix: Botany and Service firelocks in Icebox moved around to stop fire alarm spam
/:cl:

### CODE REVIEW

**Review by san7890 — APPROVED** [review]
Still looks fine to me, thank you!

**Comment by fippefi** [comment]
please do not forget to stamp my forehead for the tomfoolery, @magatsuchi

**Comment by MetalClone** [comment]
please do this for icebox xenobio as well, it drives me fucking insane

**Comment by Son-of-Space** [comment]
Firelocks are not meant to be on maintenance doors. This is so players can still get around without a crowbar if they have maintenance access. It isn't consistent with the rest of our map design. Having the firelocks on the upper stairs also prevents that room from being depressurized without players having a visual indicator of what's happening.

There is likely a more elegant solution to this than removing the firelocks and changing the consistency of how our firelocks are placed.

**Comment by Son-of-Space** [comment]
Here's some things that will reduce the fire alarm being triggered:
image
1. putting the scrubber and vent setup closer to the airlock to make sure it's properly processing air before it gets up the stairs
2. Putting the fire alarm away from the stairs in case the pressure differentials between the two levels cause the fire alarm to trigger while it's processing
3. Adding a proper 2-door firelock to the outside so people don't trigger the air from getting in.
image
4. Swapping the fire alarm and camera setup with the window so the fire alarm is away from the stairs (for the same reason as number 2)

I debated throwing firelocks over the main big door but I think it's fine as is for blocking out the air and it's much less jank.

**Comment by Son-of-Space** [comment]
If you want to reference these changes more closely I put up a branch on my repo https://github.com/Son-of-Space/tgstation/tree/BotanyAlarmFix

**Comment by fippefi** [comment]
>Firelocks are not meant to be on maintenance doors. Having the firelocks on the upper stairs also prevents that room from being depressurized without players having a visual indicator of what's happening.
Yeah, I realized this during the first round of this PR (which got autoclosed by me fixing my fork's branches with a hard reset) and removed the maint firelock. Also, the upstairs firelocks being like that is completely understandable but also kind of jank as is...
Putting an actual airlock on the mini-garden does make sense, but now I'm debating making it one-tile wide instead since it's clearly not meant to be a main access airlock, so being a small one like most maint airlocks would make more sense.


> I also did remove the firelocks from the external doors as that piece isn't consistent (and apparently can also trigger the fire alarm)
Yeah, this is probably the first thing I noticed - firelocks sense the temperature in their own tile, so being adjacent to outside can decrease their temperature, which leads to cold air alarm. Somewhat counterintuitively only the firelocks detect fires, fire alarms do not have a check_atmos loop so they are completely insensitive to any fires being set.

**Comment by fippefi** [comment]
I'm making some of the asked edits to the map at the moment, so don't be surprised if there's funny activity from the PR bots

**Comment by fippefi** [comment]
Implemented the changes upstairs as recommended: the firelocks are back and the alarm's moved slightly. Additionally I put windows to the tree section because it is a nice-looking bit of the station, and a bit of greenery being better visible is just nice.

That said, I started wondering while mapping that maybe the bridge-flanking snow tiles should be made void spaces at some point? It's not in the scope of this PR, but I would like to put it up for the consideration. Increasing the amount of Z-level see-through on icebox would allow it to have a bit more character as a research station over ice chasms.


When it comes to the downstairs, the firelocks and airlock got reworked. There's a bit of extension (about a tile southward) to the room, which gives a bit more playing room for shuffling the trays around. The vents now sit between the stairs and the airlock and window area, giving the spot more resistance against minor breaches. With the single-tile airlock and no fire locks in the downstairs area, the fire alarms are a thing of the past.
Two smaller edits: There were two air control panels in the room for some reason, I removed the duplicate one by the newscaster at the top. The maint also got extended just a lil' bit, but I didn't really add or edit anything in there aside adding a bit of dirt and moving the heater and gas tank to the corner.

I also made some rearrangements to the area outside with the fence. It's a bit less aesthetically pleasing due to no longer being perfectly rounded, but it still looks fine. Barely anyone uses that area due to pressure considerations, anyway. And there's an additional wall bit to terminate the end of the fence with the area-characteristic tram struts-over-chasm look makes it seem like the station stitches together the rifts in the ice. Structurally this also makes sense, because right above that spot is the main corridor and captain's quarters.


Finally, the area map - it's barely changed, just for reference. The bit outside of the airlock is just like pre-PR, to give the lightbulbs outside the power from the botany APC.

**Review by san7890 — CHANGES_REQUESTED** [review]
Few things given the fact that this PR changed gears a bit, and there were a few oversights:

<details>
<summary>Click me for images</summary>
image

This tile with the Red X should have the mining area that surrounds the rest of the department.

image

This area used to have fences around it... and I still think it should have fences. I get that it adds a bit to the "danger", but this is still sorta meant to be a "safer" area in contrast to the rest of the wastes on the IceMoon. Please replace those fences and move the mounds elsewhere. 

image

These two windows should have the "plating" turf underneath them, like the other windows in this room.
</details>

Irregardless, thank you for the contributions. I also thank you for adding photographs of your changes as well, those are always nice to have for other people to see your changes at-a-glance. I'll be marking your PR as a "draft" for internal management purposes, feel free to mark it "Ready for Review" when you're ready.

**Comment by fippefi** [comment]
Made the fence fixes and fixed the upstairs plating. 👍

**Comment by fippefi** [comment]
There's also the mining floor tile fix put in place now.

**Review by san7890 — APPROVED** [review]
Thank you!

**Pull request merged**
