### PR TITLE
QoL tweaks for map merger

### PR DESCRIPTION
**Pull request by YotaXP**
- Group files by directory.
- Trim off the useless portion at the beginning of the paths.
- Allow users to enter a range of numbers, in addition to individual numbers.
# Before / After

### CODE REVIEW

**Comment by xxalpha** [comment]
Are tgstation and metastation etc., their own categories?

**Comment by YotaXP** [comment]
It just goes by directory, so sure.

**Comment by xxalpha** [comment]
That's a lot better then.

**Comment by Metacide** [comment]
Wow, that's great. Thanks! :+1:

**Pull request merged**
