### PR TITLE
[s] you can no longer inject html in ahelps

### PR DESCRIPTION
**Pull request by Fikou**
## About The Pull Request

oh no no no

## Why It's Good For The Game

image
image

## Changelog
:cl:
fix: you can no longer inject html in ahelps
admin: you cant either, jannies
/:cl:

### CODE REVIEW

**Comment by CitrusGender** [comment]
It's usually in good faith to ask the Headmins before merging an Administrative PR.

**Comment by JamieD1** [comment]
Have you tried this as a non admin?

**Comment by Fikou** [comment]
> Have you tried this as a non admin?

im not a tg admin

**Comment by FloranOtten** [comment]
> > Have you tried this as a non admin?
> 
> im not a tg admin, test was on live servers

Yes. It was.

**Pull request merged**
