### PR TITLE
Adds a BLT sandwich to the game

### PR DESCRIPTION
**Pull request by SomethingFish**
## About The Pull Request

Adds a BLT sandwich to the game, including a sprite for it. It can be crafted with bread slices, two bacon, one cabbage, and one tomato.

image

## Why It's Good For The Game

Spaceman game thirteen would really benefit from having people eat a nice BLT once in awhile, plus the sandwich category only has one actual sandwich with meat in it (don't tell me a hotdog is a sandwich). Also, highly requested by some people (myself and this guy).

image

## Changelog

:cl:
expansion: Adds a BLT sandwich as a new food to the game.
/:cl:

### CODE REVIEW

**Comment by Twaticus** [comment]
ca24aa94b463302dcbed96dc70da1fc1

**Review by Kylerace — APPROVED** [review]
code is good

**Comment by SomethingFish** [comment]
> > don't tell me a hotdog is a sandwich
> 
> of course it isnt, hotdogs are a type of taco

image

**Comment by Kylerace** [comment]
its the truth

**Pull request merged**
