### PR TITLE
Mineral flow consoles & storage

### PR DESCRIPTION
**Pull request by AnturK**
I'm not feeling these ones both code and design side but @KorPhaeron asked nicely so i got this into workable state.

I feel making this material container property and integrating with already existing machinery would be better. Maybe some upgrade part that adds the network capability ? 

TODO:
- [x] Switching vault storages in orm/flow console
- [ ] Mapping
- [x] Handling temporary non-interactable states (emp/power/whatever else)

### CODE REVIEW

**Comment by SgtxRootbeer** [comment]
So, what's this do exactly?

**Comment by Cyberboss** [comment]
Ew, teleportation? We have disposals and mules!

**Comment by AnturK** [comment]
Feel free to integrate these

**Comment by KorPhaeron** [comment]
@cyberboss

Yeah but nobody uses them

**Comment by Cyberboss** [comment]
I'm saying this system could

**Comment by ACCount12** [comment]
Teleportation is just bad. It's impossible to interfere with, and it removes all the fun of screwing with people's resources.

**Comment by Buggy123** [comment]
I don't think it's necessary, but having it work through disposals would be acceptable I think. Otherwise, this is a much-needed addition.

**Comment by Repukan** [comment]
Instead of removing department interaction just remove fortifications from cargo to make it easier to breach so players can lynch cargonians if they insist on not doing their job/hoard all the materials.

**Comment by kevinz000** [comment]
Repukan no one does which is why I'm divided on this instead of disliking it due to qm getting too much power.

**Comment by AnturK** [comment]
I don't believe this is the right solution. I might repurpose flow console so you can monitor the amounts/requests without sending it immediately instead.

**Pull request closed without merging**
