### PR TITLE
Fix synthetic arm blade origin_tech

### PR DESCRIPTION
**Pull request by octareenroon91**
Minor tweak: there was a typo in the origin_tech string.

### CODE REVIEW

**Comment by GunHog** [comment]
You should add a game tip that says you can emag limbgrowers for synthetic arm blades, as I was not aware of this!

**Comment by FantasticFwoosh** [comment]
Its not nessecary since they were removed from medical anyway and aren't in regular practice.

**Comment by XDTM** [comment]
You can build them in R&D

**Comment by FantasticFwoosh** [comment]
Yes but to go all the way for the effort to build something that was removed from map standard just to emag it?

**Comment by XDTM** [comment]
It does give tech and an armblade (if you can get someone to implant it i guess)

**Comment by octareenroon91** [comment]
You can just wield it

**Comment by FantasticFwoosh** [comment]
Should probably fix that or make it do less damage when wielded else its kinda pathetic.

**Comment by octareenroon91** [comment]
Then you need research to succeed, access + materials, plus a trustworthy assistant.

**Pull request merged**
