### PR TITLE
Makes Cayenne a proper carp, adds sentience potion to nuke op uplink

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
Admins keep putting people in the body and then the poor thing can't even swim in space.

Now ops can take care of the whole thing for four telecrystals.

### CODE REVIEW

**Comment by Bawhoppen** [comment]
you maniac

**Comment by neersighted** [comment]
:+1:

**Comment by Zilenan91** [comment]
Sentience potions in their uplink actually opens up so much future improvements. I could see somebody uploading vermin cluster grenades to the Op uplink that they could sentience to be a nuisance.

**Comment by PKPenguin321** [comment]
sentient viscerator squad is go

**Comment by drynwyn** [comment]
>a space carp is actually a bat
tgstation, quality coding since 2012

**Comment by Niknakflak** [comment]
:-1: its a bat for a reason and admins put players in cayenne so it can be a pet and not impact the round at the same time.

**Comment by Fayrik** [comment]
Really, I agree with Niknakflak here... But...
If you're going to add this, please, please, **please** change Cayenne's languages so that we don't immediately have Backseat Driver: Space Carp Edition every other ops round.
It's a fish, not a drill sergeant.

**Comment by KorPhaeron** [comment]
Sentience potions grant human languages anyway.

**Comment by Bawhoppen** [comment]
fix that first then

**Comment by KazeEspada** [comment]
400 space carp is already a valid Nuke Op tactic.

**Comment by Shadowlight213** [comment]
Keep the current lore about cayenne being defanged and make their melee damage 0.
Would fix cayenne's problems, while keeping them from impacting the round.

**Comment by Bawhoppen** [comment]
I was going to give ops a free sentience potion when I finally got to my remap

**Comment by KazeEspada** [comment]
Why would cayenne be defanged? She's literally a failed carp cube.

**Comment by Bawhoppen** [comment]
>she

how dare you

**Comment by KorPhaeron** [comment]
@shadowlight213

Current lore is actually "blunted" and still does damage (6)

However if they have a sentience potion they could just buy a dehydrated carp for 1tc anyway. I would rather not punish people for using the mascot.

Also cayenne's real strength is in dragging soap anyway

**Comment by Zilenan91** [comment]
I mean, we might see Ops becoming beastmasters. Buying a retarded amount of carp and then sentiencing them to flood the station with carp.

**Comment by KorPhaeron** [comment]
@Zilenan91 

At 5tc total each that sounds like a pretty bad strategy. Carp aren't very strong.

**Comment by Zilenan91** [comment]
They are if they go in a big group and you can blow the armory. Like a ghetto, kinda shitty reinforcement.

**Comment by Bawhoppen** [comment]
carps = cannon fodder


like viscerators but more fun

**Comment by drynwyn** [comment]
First of all, Beastmaster ops would be great, and should absolutely be a thing, are you kidding me. 

SECONDLY, the ops would be limited by the number of available ghosts- though they could certainly deploy a large number of space carp led by a smaller number of sentient space carp.

**Pull request merged**
