### PR TITLE
[ready]Adds lazy airlock cycle pair system

### PR DESCRIPTION
**Pull request by MrsTonedOne**
When bump opening one of the pair, the other will attempt to close. Opening will not wait on the close or require a successful close.

This system is disabled when emergency access is enabled on the door (~~todo, make it check both doors~~)

~~No map example because map merger is broke for me. (YAY PYTHON, fucking idiots)~~

Added to every paired up airlock set on box station (including the one going to brig, bridge, engine room)

todo:

Add a way to set the direction via airlock electronics.
~~Add a system to detect when shuttles are docked to bypass.~~ done.

https://tgstation13.org/msoshit/2016-07-26-0834-14.webm

:cl:
add: Added Lazy airlock cycling. Bump opening an airlock with this system will close its partner. This system has been added to most airlocks that go to space on boxstation, as well as airlocks to secure areas like brig, bridge, engine.
tweak: This can be overridden by click opening, having a shuttle docked, or setting emergency mode on one of the doors.
/:cl:

### CODE REVIEW

**Comment by KorPhaeron** [comment]
bring back the old map merger

**Comment by Hatfish** [comment]
What happens when two people try to open both airlocks at the same time?

**Comment by MrStonedOne** [comment]
they just open

**Comment by Saegrimr** [comment]
I'm not entirely sure how its finding the linked door. Is it really just them facing a specific direction or is there an "id" var like buttons use?

**Comment by RemieRichards** [comment]
@Saegrimr it searches ```limit``` number of tiles in ```cyclelinkeddir``` direction until it finds a door to pair with.

**Comment by Alek2ander** [comment]
Why not attempt a cycle on any legal (not crowbar/emag) door opening? Click-open, ID-swipe open, silicon open, etc.

**Comment by optimumtact** [comment]
When you say broken, is it a real issue or are you just too fucking retarded?

**Comment by MrStonedOne** [comment]
>Why not attempt a cycle on any legal (not crowbar/emag) door opening? Click-open, ID-swipe open, silicon open, etc.

Because people need some way to saying they don't want that to happen, and i figured doing it like windoors do and bump opening for normal, click open for exceptional, would be easier.

**Comment by MrStonedOne** [comment]
>When you say broken, is it a real issue or are you just too fucking retarded?

It's broken in that nowhere in the non-existent readme file does it state what version i need and my python3 is too old apparently (that i'm sure i installed because of an issue with the newer python3s and some tool i was using)

**Comment by MrStonedOne** [comment]
I'll look at adding this to airlock electronics for custom doors that do this later.

Other mappers can add this to the other maps.

**Pull request merged**
