### PR TITLE
Removes Shamebrero penguin

### PR DESCRIPTION
**Pull request by ghost**
Completely unused admin only inside joke for an admin who had a fit for breaking admin rules and quit.  unused ever since alphonzo left, as he was the only one using it. It takes about 20 seconds of var editting to get the same thing as the shamebrero penguin, as it brings nothing new to the game.

seems really dumb

### CODE REVIEW

**Comment by optimumtact** [comment]
grudge PR

disgraceful conduct for a head admin

**Comment by improvedname** [comment]
Shamebrero for the frog for removing shamenrero penguin

**Comment by optimumtact** [comment]
You can pretend all you want but the reality is that you are still so incredibly mad over some imagined slight from this person that you're dragging us into your petty little grudge.

Pathetic and irresponsible from someone who is supposed to be a leader.

**Comment by Armhulen** [comment]
I don't need someone to tell me how I feel about a situation, I wanted this removed since the day it was added, when me and alphonzo were good friends. Maybe you should be maintaining the code so i don't have to make this pr instead of declaring some imaginary grudge to defend the lack of you doing your job!

**Comment by optimumtact** [comment]
Which part of my job do you imagine I'm not doing right now?

There's no reason to be merging your PR before 24 hours, so it's not like there's any other meaningful maintainer related contributions to be made here.

Please stop deflecting away from the criticism with wild ideas.

**Comment by Armhulen** [comment]
You let random crap admin toys through, that's the failure of you maintaining the code. One week wonder code like robbie rotten suits and penguins with hats are the problem and now that they sit derelict until someone mans up and removes them means you aren't doing your job of making our code not look like some kind of pseudo hippie joke

**Comment by optimumtact** [comment]
I don't know if you're aware of this but I am not the final authority on what enters or exits the codebase and though I strongly advocate against such changes I am not always in a position to deny them.

To assign blame for all miscellaneous items in the code to me is inaccurate and biased.

**Comment by Armhulen** [comment]
I can't blame you for their additions, I can blame you for closing the prs that remove them and I can blame you for dismissing those prs as grudges.

**Comment by optimumtact** [comment]
I did not close your removal PR last time and I did not close your removal PR this time either, I am merely commenting that you are clearly holding a grudge over this.

**Comment by Armhulen** [comment]
I was against the salt shuttle, I was against the sentient moodlets spawnable in game, and I was against the robbie rotten suit. is it too far fetched to believe that I am also adamant about removing more immersion breaking and degenerate code?

**Comment by optimumtact** [comment]
okay, I will take you at your word

**Comment by improvedname** [comment]
Just a hat, let it go.
Let it fall unto the ground, on the sand. Of space mexico

**Comment by ninjanomnom** [comment]
What the fuck happened between you two

**Comment by Armhulen** [comment]
I thought our debate was pretty productive, it's not like oranges and i hate eachother over a penguin with a hat

**Comment by CitrusGender** [comment]
arm is actually correct in this circumstance

**Comment by chesse20** [comment]
DONT REMOVE FEATURES PLZ

**Comment by cacogen** [comment]
DRAMA

**Comment by zamolxius** [comment]
did u jost insult hippie

**Comment by ExcessiveUseOfCobblestone** [comment]
I'm waiting for the sheep that's actually a group of KGPenguin spies that give you a quest and occasionally spawn at botany if you rename the area to "Lumbridge".

**Comment by ExcessiveUseOfCobblestone** [comment]
Since it was brought up here, Alphonzo was not a bad admin. He just didn't properly discuss the megafauna policy, decided to spawn them (sanely) anyways, and left in bad taste after he lost all the dungeon master aspects of admin, which basically means demotion for people who treat the role as anything more than robocop.

Not saying what he did was right, but the issue could have been handled better all around.

**Comment by Armhulen** [comment]
this is more about derelict code than alph, shamebreros are just an item in game and the mob is just copying the shamebrero on top of a penguin

**Pull request closed without merging**
