### PR TITLE
New fireball sprite

### PR DESCRIPTION
**Pull request by Lexorion**
## Replaces the old fireball sprite with a new one
I wanted to try animating fire and ended up making a fireball so I thought we could use it perhaps?

 
old one on the right^
 
shooting it

### CODE REVIEW

**Comment by GunHog** [comment]
It looks so GOOEY!! :smile:

**Comment by Lexorion** [comment]
Magma goo,heh. Well you won't see it staying in one place so it should be Ok.

**Comment by WJohn** [comment]
Not bad, could be more erratic like fire normally is, but it is supposed to be a fire BALL with some semblance of cohesion.

**Comment by Armhulen** [comment]
It looks like he's just SNEEZING at his enemies

**Comment by Bawhoppen** [comment]
@Armhulen intended

**Comment by duncathan** [comment]
"not bad" from wjohn is good enough for me

**Pull request merged**
