### PR TITLE
Gives the Military Jacket some suit storage options. (2)

### PR DESCRIPTION
**Pull request by phil235**
This is an updated version of #10485 by @SconesC .

 It can hold all the minor items that the bomber jacket can, as well as the 10mm pistol, the .357 revolver, and the .38 .

Made the military jacket into an actual jacket.

### CODE REVIEW

**Comment by Aranclanos** [comment]
does the armor value change by mistake?

**Comment by phil235** [comment]
@Aranclanos No, /obj/item/clothing/suit/jacket doesn't have specific armor values and all I did was move the miljacket from clothing/suit to clothing/jacket so armor is still the same.

**Comment by Aranclanos** [comment]
oki

**Comment by optimumtact** [comment]
Fucking suit storage man

**Comment by Ikarrus** [comment]
Small request, but could you add the same suit storage options to the leather jacket and coat? Mostly for gang uniforms, and I think those clothes are still rare enough to not upset anything outside of that.

**Comment by phil235** [comment]
@Ikarrus done

**Comment by KorPhaeron** [comment]
You'll need to update the path of the "officer" equipment for the multisword in artefact.dm sincw you just merged my fix

**Comment by phil235** [comment]
Aran, no, the code won't be compiling now. I'll make a hotfix.

**Comment by Aranclanos** [comment]
if it doesn't compile people can't play
if they can't play there's no game
if there's no game we're free

**Pull request merged**
