### PR TITLE
Replaced Mending Motor with Prolonging Prism and Mending Mantra

### PR DESCRIPTION
**Pull request by ChangelingRain**
:cl: Joan
rscdel: Removed Mending Motor.
rscadd: Added Prolonging Prism, with the same cost, icon, and tier that Mending Motor had. Prolonging Prism will delay the arrival of emergency shuttles at the cost of power. In addition, the emergency shuttle dock will be obviously afflicted while it is active.
rscadd: Added Mending Mantra, which is a Script that will rapidly repair nearby structures and constructs.
/:cl:

Shuttle calls will (almost)always be affected by alert level, even if they're admin calls.

### CODE REVIEW

**Comment by GunHog** [comment]
Why are you replacing Mending Motor? It is one of the best structures! :disappointed:

**Comment by ChangelingRain** [comment]
https://atlantaned.space/newSS13tools/stats/monthlyStats.php?year=2017&month=03&stat=clockcult_scripture_recited
The stats for april aren't up yet, but I have a suspicion that they'll be very similar.

**Comment by GunHog** [comment]
It was going unused? Those idiots! They do not know how AWESOME it is :(

**Comment by Robustin** [comment]
Even if it were used more it would just exacerbate the most frustrating aspects of trying to breach a CC base. It's easily the best candidate for replacing, and CC has a TON of fat that needs to be trimmed. 

This is very good, though I'm not wild about the color still. Even a little more purple would be nice if you're set on "magic color" but keep in mind the Ark and most of the turf conversion "magic" is bronze...

**Comment by ChangelingRain** [comment]
The prism doesn't provide a location, but if the shuttle can be recalled it uses twice as much power and gradually takes damage, which further increases the power cost and decreases how long it delays.
I'm not actually sure how long it'd delay on average but that's mostly because it's a pain to calculate.

At code green it can delay indefinitely/until it takes enough damage that it only slows the shuttle down/until it actually forces the shuttle to recall.
At blue, it's the same but it costs more(less uptime) and delays less, so the shuttle will come sooner.
At red it's basically making the shuttle act like it's at green alert, assuming it remains at full health.

**Comment by Durkel** [comment]
I don't like this. It doesn't actually tackle the issue of why players are forced to call the shuttle every time there's a cult and instead forces players to linger in the shit of a conversion mode. That and if you're able to build this you've probably either already won or spent so long building a base you're going to get destroyed by science memes.

**Comment by Repukan** [comment]
>shuttle extension 

Hell no.

Even less for clock cult. Once they're established in the AI base or what have you and sec is dead, calling the shuttle is often the last option for civilians.

**Comment by ChangelingRain** [comment]
the intention is that these are a stopgap measure for the cult due to limited power but I need to actually balance them like that because right now they're really just kind of overtuned.

**Comment by Armhulen** [comment]
Shadowling (great game mode guys) had a spell that extended shuttles calls and quote from xhius

"The worst designed spell i've made" or something like that

**Comment by KorPhaeron** [comment]
Time to walk out an airlock as security I guess.

Having the optimal and most common strategy being a round short circuit is not much fun but neither is being trapped in an increasingly unwinnable and otherwise miserable situation.

I wouldnt be surprised if sec players started logging off or just started killing everyone on station as soon as they saw this thing was on.

**Comment by XDTM** [comment]
The problem is that running away is the first and not the last strategy used. Calling the shuttle should be cutting losses and getting a draw, not a victory condition.

**Comment by KorPhaeron** [comment]
I agree which is why in the alternate universe where I finished planetstation you can end the round early with the nuke but have to tough it out for escape

**Comment by Wyzack** [comment]
Come the fuck on. Conversion antag modes are already miserable to play as security as your options are either go turbohitler and win or else lose to slow attrition. All this is going to do is make it so the cult gets extra time to wank about how super powerful and cool they are before Ratvar comes. Why do we need this?

**Comment by Wyzack** [comment]
Sorry for the doublepost but wouldn't it be better to make the mode less fucking miserable to play for both sides to de-incentivize shuttle calls rather than trying to lock people into playing it when they clearly are not enjoying it?

**Comment by Aloraydrel** [comment]
Can't wait to have my shuttle delayed for conversion mode #5 so they can finish up winning

**Comment by ChangelingRain** [comment]
I'm not actually really surprised by the response; I did this entirely to, I don't know, taunt robustin basically.

**Comment by ChangelingRain** [comment]
Though mending motor is still bad and replacing it with mending mantra remains a good idea

**Comment by Robustin** [comment]
@KorPhaeron 

Rev called. Sometimes forcing the crew to confront the enemy is the best solution. With Blood Cult it was a good middle ground, security can escape faster by going on the offense, but regardless the cult can't delay forever. A similar concept for CC would be perfect. If Sec wants to flee, at least force a single confrontation and not just locking down the bridge/caps for 2 minutes.

The only alternative is nerfing Red Alert but that would be even harder to get through.

**Comment by KorPhaeron** [comment]
You can end rev by killing 3 people. Every (clock)cultist is their own revhead but also armed with magic powers.

Revs grow weaker if they hide. They lose momentum. If revs try and hide and farm I can go kick their door down because their farming is tied to the departments for the most part. They cant build a space cube accessible by a tele rune hidden behind a false wall in maint. Cults can hide and you're more or less stuck waiting for them to kill you. Rev wins by engaging and fighting, cults win by avoiding you. The latter feels helpless.

Any gear revs have, I can take and use. They are ground down by attrition just like I am.

If security gets wiped in rev, thats usually game. If security gets wiped in cult they are treated to 15-20 minutes of deadchat while people do the summoning/wait for the shuttle to go home.

And plenty of people cite rev as a reason why they dont play sec or heads

**Comment by ChangelingRain** [comment]
Possible concept; consume a one-time large amount of power/components to destroy the shuttle console when it arrives and delay it leaving for X minutes, preceded by the crystal effect on the dock.

**Comment by Robustin** [comment]
Yes Kor but this isn't a shuttle blocker, it just buys time. This isn't Gang War's infinite recall. This isn't Slings "+15 minute slap in the face that you can't even prevent". The shuttle curse worked out very well for the blood cult and CC has a coder who can create an even more nuanced way to delay the shuttle. Keep in mind that if RNG blesses the CC with the CE or another head at roundstart, you can achieve something far more powerful than most delay mechanisms by infinitely recalling. A CC mechanism could simply delay while providing security/loyalists with an idea of where the interference is coming from. 

Also at least blood cult is very proactive about keeping its victims in the round. The only time that sec corpses don't get put to use is near the end when the cult is about to win anyway.

**Comment by Repukan** [comment]
Yeah but blood cult doesn't have as much op shit gated by time or resources.

It's kinda bad to compare bloodcult and CC when CC has holoparasites, self serving conversion traps, aggro buildings, mass spells (lighting, invul, brain damage and confusion.)

I would argue the most bullshit thing blood has that could even compare is juggers and that's just barely.

**Comment by KorPhaeron** [comment]
>this isn't a shuttle blocker

Joan didnt give hard numbers, but estimated that it'd block anything less than red alert indefinitely, and cause red alert to take as long as green (20 minutes). I am aware it takes damage, but you could always build another one (or repair it?)

Unless she did a poor job explaining it, it sounds even harder to deal with than shadowling or gang.

**Comment by Robustin** [comment]
Which is why I'm disappointed this got shut down so fast. Tweak the numbers, make it reasonable, make it fair.

**Comment by YakumoChen** [comment]
The main problem with cults is that being security is suffering infinitely because every aspect of playing against cult is annoying:
-Catching a cultist means fighting a guy with magic powers who may have one-use stun batons or limited stun immunity depending on the cult. CC has holoparasites (making the cultist have a stun-immune and impossible to kill buddy), blood has EMP.
-Assuming you actually get the fucker to the brig, a blood cult can just teleport them away, GG Waste Of Time, and Clock can teleport their whole team to you if they want to do a confrontation.
-Assuming the chaplain exists / lived long enough to give sec holy water, that means feeding the cultist holy water and having someone stand near him for 5 whole minutes waiting for them to deconvert, leaving less people who can actively fight the cult and forcing others to play babysitter.
-After all that, you better have implants or they'll just walk right back to the cult base and make all your work pointless as they get reconverted anyway.
-Assuming you finally do all that and get a cult-immune buddy, hand him a taser and watch him die to cult in 5 minutes, giving the cult a consolation prize: a free taser to kill you with. Also a posibrain / construct, to also kill you with.
-Also both cults have methods to throw infinite numbers of cult baddies at you with ghost spam / clock posis respectively.

Have fun!

**Pull request closed without merging**
