### PR TITLE
Miscellaneous Abduction improvements (wip)

### PR DESCRIPTION
**Pull request by ghost**
Fixes a lot of the questionable code and snowflake checks in the Abduction gamemode, in addition to changing kekworthy grammar and making it consistent.

### CODE REVIEW

**Comment by AnturK** [comment]
:+1: I suck at writing fluff.

**Comment by phil235** [comment]
@Xhuis Still WIP?

**Comment by Xhuis** [comment]
I completely forgot about this existing.
Yeah, for now it is.

**Comment by Xhuis** [comment]
Eh, I'm gonna close this. I don't have time to fix the conflicts and I need to get back to work on revenants

**Comment by AnturK** [comment]
You mind if i grab and put this in new PR ?

**Comment by Xhuis** [comment]
No problem at all @AnturK

**Pull request closed without merging**
