### PR TITLE
[s] quenches the cults thirst

### PR DESCRIPTION
**Pull request by PKPenguin321**
https://tgstation13.org/phpBB/viewtopic.php?f=9&t=32&p=49625#p49625

oh no

### CODE REVIEW

**Comment by Incoming5643** [comment]
OH YEAH!

**Comment by Cheridan** [comment]
no cobyrighted material :^))

**Comment by PKPenguin321** [comment]
What copyrighted material? This is just demonic blood jug man, here to quench the cult's thirst for blood.

**Comment by Cheridan** [comment]
oh ok good point

**Pull request merged**
