### PR TITLE
Discstation Hotfix #3

### PR DESCRIPTION
**Pull request by Strathcona**
More fixes to medbay power, removes unconnected pipes and fixes the extra cameras on z4 while adding back some loot that was missing.

### CODE REVIEW

**Comment by Shadowlight213** [comment]
You still have some areas named incorrectly.
The escape pod above the arrivals shuttle has the arrival shuttle area
The toxins test site has the research and development area
The research testing range is the toxins test site area
Toxins itself is part of the RND area.
The gravity generator room area only covers half of the actual room
Vault area seems to be shifted up a tile for some reason
Law office to courtroom door still has that rwall. coords:(95,113,1)

**Comment by Strathcona** [comment]
Got all of those except for the misnamed areas. I know that, for instance, the maint areas are named incorrectly and I'd like to name them by location but I'm not sure how to make that change.

**Comment by Jordie0608** [comment]
@Strathcona Just change the name var of the area.

**Comment by Strathcona** [comment]
This is ready for merger.

**Pull request merged**
