### PR TITLE
[s]Fixes being able to launch the arrivals shuttle by hiding in closets and bodybags

### PR DESCRIPTION
**Pull request by Cyberboss**
:cl: Cyberboss
fix: You can no longer depart on the arrivals shuttle by hiding inside things
/:cl:

### CODE REVIEW

**Comment by kevinz000** [comment]
when is cyberboss getting maintainer?

**Comment by Incoming5643** [comment]
I feel like there's a more general way to deal with this.

**Comment by ChangelingRain** [comment]
what about mechs? or anything else you can put people in

**Comment by MrStonedOne** [comment]
I feel like this might be better served by searching thru the mob list and running get_area on them

**Comment by FantasticFwoosh** [comment]
Lame lack of PR joke, i've fixed it for you - 

🆑 Cyberboss
fix: Due to the influx of hidden operatives, Centcomm has made investigative checks more thorough before allowing the arrivals shuttle to depart
/🆑

**Comment by KingPhilipIII** [comment]
Where does the shuttle even go when it departs?

**Comment by Cyberboss** [comment]
Transit space

**Pull request merged**
