### PR TITLE
Makes Ice Box Botany Cozy as Fuck [MULTI-Z] [FUCK CABLE HUBS]

### PR DESCRIPTION
**Pull request by tralezab**
## About The Pull Request

Makes botany down a zlevel, gives them an exit so they can collect plants on the ice moon...

image

image

## Why It's Good For The Game

I dunno I think it's better if it isn't blam me brother

## Changelog
:cl:
add: Botany is remade for ice box!
/:cl:

### CODE REVIEW

**Comment by tralezab** [comment]
COOOOOOOOOOOOOOOON
FLICTS?????????????

**Comment by Tlaltecuhtli** [comment]
idk man, why make the botanist isolate themselves in the basement

**Comment by tralezab** [comment]
It lets them collect native plants!

**Comment by Helianthus00** [comment]
If I had any gripes, it would be that there aren't enough grow trays in the common botany area. I like the bee alcove, but I think the trays should start in the main area and be moved there if that is how the botany folk want to play the round. 

Overall, I think this is a great direction for Icebox to move in, and the railings/glass floors/catwalks look great in multi-z levels. I'd be very happy if other areas of Icebox were reworked to have multiple levels like this.

**Comment by tralezab** [comment]
I tried to keep the number of botany trays the same as before

**Comment by tralezab** [comment]
Also, just for some mapping updates, i've added some more lights and cleaned up decals that should be there but weren't.

**Comment by Helianthus00** [comment]
> 
> 
> I tried to keep the number of botany trays the same as before

I guess my point is, it feels like there are a lot less. Having two be at the top by themselves and three in the bee area makes it seem like there are only 8 trays at first glance. That and botanists will never be satisfied if you don't give them 14-15 trays. Really up to you though, just throwing my two cents in.

**Comment by tralezab** [comment]
Hm! We do have a lot more space to work with here...

**Comment by Whoneedspacee** [comment]
INFINITE TRAYS

**Comment by Whoneedspacee** [comment]
frankly though this does bring up a good topic

how can we ever hope to improve over meta if we only keep doing the same things it does, we should really try to spread our wings on this which yeah does involve stuff like more trays because multiz so more space.

**Comment by tralezab** [comment]
updated op with new changes

**Comment by Angustmeta** [comment]
- Needs holopad. Maybe one on bottom floor if that works (visible from top) and one outside botany desk on upper floor. People come to botany desk to ask for plants very often. 
- Remove bottom biogen and build the top biogen into a wall/window. Replace with a table with extra wrench or something. Delta has 2 biogens which just makes it annoying for people to check which one is loaded, and having it on top floor makes the botanist need to leave the autism fort more often. 
- Stool is for savages. I'd like an office chair or two. 
- Trash is going to be a big problem. I generally need to throw bottles into the disposal bin very often. A trashbag or at least a trash bin would be needed on bottom floor or it will become littered with bottles most rounds. 
- Grinder and chemmaster needs to be moved to bottom floor (still next to each other) as the backroom is just too far away. When you need to grind you often walk back and forth between trays and grinder to pick up new harvests every 20 seconds.

**Comment by tralezab** [comment]
@Angustmeta Thanks for the help!

**Comment by Angustmeta** [comment]
Oh and the requests console and security camera on upper floor looks unreachable.

**Comment by Dennok** [comment]
> Oh and the requests console, security camera and light fixture on upper floor look unreachable.

Console, i think, from bottom level. Fixture and camera reach ability, i see, unnecessary.

**Comment by Angustmeta** [comment]
You need to be able to cut the camera and replace broken lights.

**Comment by tralezab** [comment]
Couldn't find /any/ good space to put the biogen, i'm gonna leave it as is for the moment. everything else handled

**Comment by Helianthus00** [comment]
I'd highly suggest moving the biogen between the kitchen and botany and moving the food processor to replace one of the kitchen tables.

**Comment by Tharcoonvagh** [comment]
I feel like this  area is a bit too barren, I would recommend putting at least a potted plant in the corner there

**Comment by tralezab** [comment]
i agree

**Comment by tralezab** [comment]
i've been made aware that using three parentheses is... not kosher!

**Review by Timberpoes — APPROVED** [review]

**Pull request merged**
