### PR TITLE
Removes the mass zombie infection admin secret

### PR DESCRIPTION
**Pull request by Iamgoofball**

### CODE REVIEW

**Comment by qbmax32** [comment]
silly goofball

**Comment by kevinz000** [comment]
WTF I LIKE GOOFBALL NOW?!!

**Comment by PKPenguin321** [comment]
Wrong!

**Comment by Niknakflak** [comment]
Shoo, admins should have unrestricted access to do whatever because if this gets merged and your dumb reverts aren't, the ONLY thing this does is make it so admins have to do this all manually, BUT we can still do it.

You can never stop us ;)

**Review by lzimann — CHANGES_REQUESTED** [review]
[You have to remove them from here aswell](https://github.com/tgstation/tgstation/blob/048c531952b8cbb9f26970b5757b9056a760b00b/code/modules/admin/admin_verbs.dm#L93)

**Comment by Cyberboss** [comment]
No real good reason to remove a verb that's probably only ever used after the shuttle docks

**Pull request closed without merging**
