### PR TITLE
Gives krav maga gloves to standard sec officers

### PR DESCRIPTION
**Pull request by PKPenguin321**
Part of 3 PRs intended mainly for test merging (and possibly eventually actually merging if the test goes well) that have to do with giving sec krav maga

[Check out the krav maga for sec poll on the forums right here.](https://tgstation13.science/phpBB/viewtopic.php?f=10&t=6466)

Check out https://github.com/tgstation/-tg-station/pull/17045 and https://github.com/tgstation/-tg-station/pull/17046 for the other two sister PRs

:cl: PKPenguin321
rscadd: Standard sec officers now start the round with krav maga gloves.
/:cl:

### CODE REVIEW

**Comment by Man-Shroom-** [comment]
only if stungloves are re-added

stungloves would obviously be nerfed in the following ways

1. Only one charge
2. Don't stun for a silly amount of time
3. Very obvious sprites

**Comment by PKPenguin321** [comment]
@Man-Shroom- 

screenshot 8

**Comment by Zilenan91** [comment]
people heard stun gloves and they associate this with stun gloves when they're not really comparable

**Comment by Core0verload** [comment]
But these things ARE stun-gloves, except with a shorter stun. But they pack more features: mutesting gloves, toolbox hands gloves, etc.

**Comment by PKPenguin321** [comment]
yes but man_shroom is demanding that we readd stungloves before implementing these. readding stun gloves would serve no purpose to balance these. and these are not stun gloves, even if they do have a stun. the stun is extremely short, about the same amount of time as a push from a disarm.

is pushing with a disarm stungloves too? they both stun, so by your logic they are.

**Comment by Core0verload** [comment]
Except the disarm has no guarantees, and this gives 100% stun guaranty from the first click. Yep, stun gloves.

**Comment by PKPenguin321** [comment]
yes, but it is a super short stun comparable only with a disarm push. and it can't even be used on people that are already stunned, unlike disarm pushes and stun gloves. your argument is moot.

**Comment by Core0verload** [comment]
Super short stun is more than enough to pick up the dropped gun, and then kill gun's owner with it.

**Comment by Zilenan91** [comment]
It's also quite literally a push, so if you pick up their gun you'll have like 0.2 seconds to attempt to shoot them with it.

**Comment by PKPenguin321** [comment]
same with a disarm or a push which you already have by default anyways

**Comment by Iamgoofball** [comment]
# stun glove retards pls go

**Comment by Core0verload** [comment]
Disarm, push, etc - all random based. No way you are getting any reliability with those. And your gloves are 100% reliable, they never fail as long as you can click your target. Literally stun gloves.

By using the same logic as you do, I could add changeling gloves to players roundstart. Because why not? They can become lings at roundstart anyway.

**Comment by PKPenguin321** [comment]
You are wrong

**Comment by Iamgoofball** [comment]
Oh my god core, I know you're retarded but this is too far

**Comment by Core0verload** [comment]
My point stands. This thing IS stun gloves, except with more modes: mutesting, harmbaton, etc.

**Comment by Iamgoofball** [comment]
You first

**Comment by ChangelingRain** [comment]
>They're gloves and they stun, so clearly they're the same as stungloves
fun logic, here

**Comment by Core0verload** [comment]
Not the same. They clearly have less stun and more modes. But they are a kind of stun gloves, no doubt.

**Comment by KorPhaeron** [comment]
Stungloves: Easily blended in, couldn't disarm them/drop them, stunned on hit

These gloves: Easily blend in, can't be disarmed or dropped, stun on hit (plus more!)

How are they not stun gloves?

**Comment by PKPenguin321** [comment]
No Kor please not you too I thought you were smarter than this

1. These gloves are big and red and poofy, very visible, much like object inhands
2. The stun they do is about as long as a push which you can do with your hands/can't be disarmed of anyways (Yes I know it's guaranteed whereas a push is not but that might be kind of the point)
3. The stun is about as long as a push, it's barely a 'stun' and more of a guaranteed disarm
4. Stungloves can be found on anybody anywhere whereas these gloves will only be found on certain sec jobs, they're highly predictable

Those are just the reasons I have with the gloves themselves. Would you like to hear more about how sleeping carp can instantly neckgrab anybody, or how sec literally has batons that are better in pretty much every way except that they can be disarmed (which isn't even guaranteed like I already said)?

**Comment by KorPhaeron** [comment]
>These gloves are big and red and poofy

Oh. I thought they were black.

**Comment by PKPenguin321** [comment]
The stealth variant (that I might give to traitors later) currently is, but isn't implemented and is still subject to change. The ones for sec look like these:
sprites

**Comment by xxalpha** [comment]
I have no problem with this item, but I think security doesn't need more shit.

Give it to ERT, Syndicates and one in the vault safe.

**Comment by Zilenan91** [comment]
ERT will die in the exact same way they always do and the vault will just make random assistants hack into it for a few days before stopping because the vault is really hard to break into not even counting anyone stopping you.

**Comment by KorPhaeron** [comment]
Maybe the warden one

**Comment by Iamgoofball** [comment]
Why, this won the poll

**Comment by KorPhaeron** [comment]
It won a plurality, but it's not like it had overwhelming support. Majority of players in fact voted against all officers having it.

**Comment by Iamgoofball** [comment]
server poll?

**Comment by Zilenan91** [comment]
Server poll would be nice.

**Pull request closed without merging**
