### PR TITLE
Minor Sprite Changes [witch hunter, oldcaparmor/centcom] and One Deleted Sprite

### PR DESCRIPTION
**Pull request by ishitbyabullet**
There SHOULD be no sound or UI tweaks. It's just 4 dmis being changed. There also shouldn't be 89 file changes. Should be only 4. This is the reason why this PR is closed now.

**NOTE TO CODE REVIEWERS: I AM SORRY YOU WERE REQUESTED. IT WASN'T MY DOING. ONCE AGAIN, SORRY.**
## About The Pull Request
Hey, this changes a few sprites as well as completely removing one. I fixed the centcom and oldcaparmor sprites, tweaked the cross and colors for the witch hunter outfit, and got rid of this old metroid sprite which is from the really olden days according to a friend. I thought metroid sprites were mass wiped off ss13 due to copyright issues anyways.
## Why It's Good For The Game
Because I like the centcom armor, I see no purpose for the metroid sprite, and that witch hunter sprite feels really familiar. I just can't put my tongue on where it came from though. Eh, I'm sure someone will be able to figure it out for me. _For anyone that gets what I am saying, yes, I told them about what I am doing._
## Changelog
:cl: Rob Robinson ft. his invalid and wrong opinions
tweak: The year is 2550 (according to the wiki). Due to the time period, the chaplain's witch hunter outfit could not possibly exist! Chrono legionnaires have replaced them with outfits that have a normal cross and are blue now instead. Maybe we'll get the old outfit back in 500 years or so!
fix: The centcom armor and old captain armor sprites no longer look like they were poorly recolored. Admins can finally have more options for Centcom now!
del: what's this green, floating thing? Eh, just get rid of it. No one has ever seen it anyways.
/:cl:

### CODE REVIEW

**Comment by ishitbyabullet** [comment]
i knew this wouldn't work immediately.  time to fix it.

**Comment by ishitbyabullet** [comment]
One of my commits has 37 changed files.

The pr itself only says 4. I am confused and hope this doesn't impact anything.

**Comment by cacogen** [comment]
god i'd completely forgotten about metroids

**Comment by SkeletalElite** [comment]
> One of my commits has 37 changed files.
> 
> The pr itself only says 4. I am confused and hope this doesn't impact anything.

It appears your PR has so many changed files because its reverting all the sprite changes in #45826

**Comment by Akrilla** [comment]
this pr is reverting stuff but it's my fuckup since I literally also reverted stuff, fixing now

**Comment by SkeletalElite** [comment]
> this pr is reverting stuff but it's my fuckup since I literally also reverted stuff, fixing now

yeah it's also reverting your intentional sprite changes though too, which needs to be fixed.

**Comment by ishitbyabullet** [comment]
So, what should be done to fix it?

Also the difference are caparmor/centcom worn sprites, all witch hunter sprites, and no more metroid obj sprite.

**Comment by Akrilla** [comment]
Just merge master into your branch, then make sure your sprites are added back into the files, and that should be fine

**Comment by ishitbyabullet** [comment]
what the fuck

**Comment by ishitbyabullet** [comment]
please work this time, PR.

**Comment by Akrilla** [comment]
I believe in you

**Comment by ishitbyabullet** [comment]
image
**github, i am just trying to change a few sprites. are you kidding me? are you seriously kidding me right now? i don't need every fucking maintainer oh god**

**Comment by ishitbyabullet** [comment]
Alright, gang, this is going horribly wrong. I'll try again another time.

I'm sorry you were pinged, maintainers. I didn't mean for 4 changed DMIs to fucking change 89 files stealthily.

**Comment by Akrilla** [comment]
github claims another victim

**Comment by ExcessiveUseOfCobblestone** [comment]
lol

**Comment by ExcessiveUseOfCobblestone** [comment]
he deleted the entire repo the madman

**Pull request closed without merging**
