### PR TITLE
Closet Anomaly station trait.

### PR DESCRIPTION
**Pull request by Ghommie**
## About The Pull Request
Well, it's a station trait that makes a small number of (non-secure) closets function as if splashed with eigenstatium (which turns them into teleportation cabins of some sort). However, they're subtler, they lack the transparency and blueish tint, and don't make sparks.

This PR also demotes the Eigenstate subsystem to a singleton global datum. It doesn't fire, it doesn't init, it plain doesn't belong amongst the big boys.

## Why It's Good For The Game
This should be a mildly interesting station trait.

## Changelog

:cl:
add: Added a 'Closet Anomaly' station trait, which links and turns a portion of the roundstart closets into impromptu teleporters.
/:cl:

### CODE REVIEW

**Comment by Xkallubar** [comment]
Fun

**Comment by Admiral-Gigaton** [comment]
Can this send the captain's locker contents to the chef's fridge?

**Comment by Ghommie** [comment]
Nope, secure lockers are exempt from this.

**Comment by wesoda25** [comment]
Harry potter head canon now official. holodeck = room of req. this = vanishing cabinets. wizards = wizards. assistants = muggles. 🧙‍♀️🧙‍♀️

**Comment by Admiral-Gigaton** [comment]
> Harry potter head canon now official. holodeck = room of req. this = vanishing cabinets. wizards = wizards. assistants = muggles. 🧙‍♀️🧙‍♀️

Miners are... squigs was the name I think

**Pull request merged**
