### PR TITLE
Resprites for Leather Satchel & Briefcases

### PR DESCRIPTION
**Pull request by Twaticus**
## About The Pull Request

Repsrites leather satchel so its no longer just a sized down image. Resprites briefcase, secure briefcase, and mindshield lockboxes to the current perspective. Changes briefcase inhands to the correct color, gives lockboxes their own inhands.
dreamseeker_Q0IzLwWgdr

## Why It's Good For The Game

Consistency.

## Changelog
:cl:
imageadd: updated leather satchel, briefcase, secure briefcase, and mindshield lockboxes sprites
/:cl:

### CODE REVIEW

**Review by Mothblocks — APPROVED** [review]

**Comment by Pugie** [comment]
SOUL

**Comment by SmArtKar** [comment]
N O I C E

**Comment by Pugie** [comment]
FUUUUUUUUUUCK

**Comment by Jared-Fogle** [comment]
they cant keep getting away with thsi

**Comment by ShibaInuLord** [comment]
MY SOULLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL

**Comment by Jared-Fogle** [comment]
its ok we still have the exact same chapel floor, light switch, and sec cameras that were in the oldest versions of ss13

**Pull request merged**
