### PR TITLE
Makes hits from multitools sound as painful as they are.

### PR DESCRIPTION
**Pull request by TerraGS**
:cl:
tweak: Removed tap.ogg from multitool so getting hit by one sounds as painful as it really is.
/:cl:

Noticed hitting someone with a multitool sounded deceptively harmless, only realizing I was doing damage when I was explicitly told. This should prevent future confusion.

### CODE REVIEW

**Comment by TerraGS** [comment]
Maybe I should've labeled this a code change since I'm not actually deleting the sound itself.

**Comment by MrDoomBringer** [comment]
yeah, set it as a tweak

**Comment by MrDoomBringer** [comment]
also cus removal tag steals ur gbp i think

**Comment by TerraGS** [comment]
What is gbp?

**Comment by subject217** [comment]
MrDoomBringer is talking about Coderbus GBP which are sort of a score to keep people making fixes. You can see yours [here.](https://atlantaned.space/coderbus/) Both removals and tweaks aren't worth any GBP though.

**Comment by TerraGS** [comment]
Oh well that's fine. This wasn't supposed to be anything major. Just a single line removed.

**Comment by lordpidey** [comment]
Honestly, you should probably change the damage instead of the sound.

It doesn't make sense for it to deal damage.

**Comment by TerraGS** [comment]
I'm not trying to make any functional changes with this.

**Comment by OmegaShoots** [comment]
rip silent killer
kidnapping someone as a traitor and killing them with a multitool in maint shall be no more

**Pull request merged**
