### PR TITLE
[UNTESTED] [WEB-EDIT] [BAD SHITPOST] Maintastation [METASTATION OVERHAUL!!!]

### PR DESCRIPTION
**Pull request by EOBGames**
Hi, I'm Inept-at-Job! You may remember me from such PRs as "Frosty Saviour" and "Adds a selection of Exploration Items". Today I'm here to bring you the best map PR in the history of map PRs, maybe ever: Maintastation!
maintastation
Maintastation makes Meta into the map it was always meant to be- a dark, terrible maze of stupidly designed corridors, made by a madman in one night! It also removes several _extraneous and pointless_ details from the map, such as thunderdome screens, light switches, security cameras, and every light on the station! Finally, the curse of night lighting is dead and buried!

### CODE REVIEW

**Comment by uomo91** [comment]
I feel this expands on Meta's vastly diminutive maint and will be a great improvement, speedmerge!

**Comment by ArcaneDefence** [comment]
The amount of effort going into this shitpost is impressive.

**Comment by LemonInTheDark** [comment]
No one man should have all this power

**Comment by ATH1909** [comment]
Testmerge this for April Fools.

**Comment by ATH1909** [comment]
Playing AI on this map is going to be actual torture, and I don't know if that's a good thing or a bad thing.

**Comment by EOBGames** [comment]
hey come on I thought of our silicon friends, in fact I'll update the map with even more love for silicons

**Comment by EOBGames** [comment]
there we go, now I hope I can be forgiven by our silicon friends

**Comment by nikothedude** [comment]
id like to see a version of the map with the cameras please

**Comment by EOBGames** [comment]
that would just be spoiling the surprise

**Comment by nikothedude** [comment]
this isnt maint enough. make the dorms rooms maint as well, and add a few random electrified grilles here and there, since yknow maint has those, and oh! of course, randomly bolt and weld and depower some doors! and random wooden barricades, yes, those are important!

**Comment by nikothedude** [comment]
i almost forgot, you need to have the rat event make rats spawn fucking EVERYWHERE, since yknow, everything is maint.

**Comment by nikothedude** [comment]
Other than that, I am very very excited to see this map enter our rotation! we know players LOVE big maintenance, so this will be a TREAT

**Comment by oklews** [comment]
Rad storms are just a cool sight now, they pose NO threat to the most intensely protected station NT offers

**Comment by EOBGames** [comment]
> this isnt maint enough. make the dorms rooms maint as well, and add a few random electrified grilles here and there, since yknow maint has those, and oh! of course, randomly bolt and weld and depower some doors! and random wooden barricades, yes, those are important!

every door has a random chance to be messed with.
...you're definitely onto something with the grilles though

**Comment by spookydonut** [comment]
proudly declaring its untested and a web-edit in the pr title isn't a gamer move.

also its not mapmerged.

**Comment by trollbreeder** [comment]
its supposed to be a bad april fools joke @spookydonut

**Comment by EOBGames** [comment]
The attempt on my life has left me scarred and deformed.
(Also @spookydonut it is mapmerged, that's just how many things this PR changes)

**Comment by cacogen** [comment]
i hope this gets in on april fools. ai's fucked

**Comment by spookydonut** [comment]
> 
> 
> The attempt on my life has left me scarred and deformed.
> (Also @spookydonut it is mapmerged, that's just how many things this PR changes)

you deleted over a thousand mapkeys?

**Comment by EOBGames** [comment]
> > The attempt on my life has left me scarred and deformed.
> > (Also @spookydonut it is mapmerged, that's just how many things this PR changes)
> 
> you deleted over a thousand mapkeys?

There were over 4 thousand turf decals alone, and that was only part of what I changed.

**Pull request closed without merging**
