### PR TITLE
Removes old ass belt.dm

### PR DESCRIPTION
**Pull request by Cyberboss**
@Xhuis update your master reee!!!

### CODE REVIEW

**Comment by Cyberboss** [comment]
Also if you changed stuff in here it had zero effect.

**Comment by lordpidey** [comment]
https://xkcd.com/37/

**Comment by Xhuis** [comment]
What...?

**Comment by Cyberboss** [comment]
You added this file with the clockcult rework

**Comment by Xhuis** [comment]
Whuuuuuuh? Huh. In that case, uh, out with the trash!

**Comment by nicbn** [comment]
Did you test the belts?

**Comment by Cyberboss** [comment]
https://GitHub.com/tgstation/tgstation/tree/master/code/game/objs/items/belt.dm

**Comment by Slignerd** [comment]
That's a 404 though

**Comment by Cyberboss** [comment]
https://github.com/tgstation/tgstation/blob/master/code/game/objects/items/storage/belt.dm

**Pull request merged**
