### PR TITLE
Ports oracle's janitor cart sprites

### PR DESCRIPTION
**Pull request by nicbn**
[Changelogs]: #

:cl:
imageadd: New janitor cart sprites (by Quantum-M)
/:cl:

Stolen from https://github.com/OracleStation/OracleStation/pull/1123

See beesting comment for pics

### CODE REVIEW

**Comment by BeeSting12** [comment]
Pics from oraclestation PR.

**Comment by WJohn** [comment]
I like that you can see the water in the mop bucket. Does it only have a filled/empty state, or multiple levels like beakers?

**Comment by nicbn** [comment]
Only filled/empty
This PR is only a port, but I can add greyscale for reagents and multiple levels later on another PR

**Comment by nicbn** [comment]
@Dorsisdwarf you got your pics

**Review by Cyberboss — APPROVED** [review]

**Pull request merged**
