### PR TITLE
triggers @coaix

### PR DESCRIPTION
**Pull request by MrsTonedOne**
@tgstation/commit-access CONTRIBUTING.md update.

### CODE REVIEW

**Comment by ExcessiveUseOfCobblestone** [comment]
STOP

**Comment by KorPhaeron** [comment]
The nazi stuff was part of the diff and I thought you were calling coiax a nazi and got really confused

**Review by Cyberboss — APPROVED** [review]

**Review by Shadowlight213 — APPROVED** [review]

**Review by PKPenguin321 — APPROVED** [review]

**Comment by Iamgoofball** [comment]
@KorPhaeron please censor your words, that word cannot show up in a search of the codebase

**Review by Iamgoofball — APPROVED** [review]

**Comment by Razharas** [comment]
Wow this anti-nazi stuff surely is against first amendment

**Comment by lzimann** [comment]
UNNECESSARY MULTILINES MUST DIE

**Review by ChangelingRain — APPROVED** [review]
RIDICULOUS MULTILINING IS TERRIBLE

**Review by ExcessiveUseOfCobblestone — APPROVED** [review]

**Comment by Iamgoofball** [comment]
@Cheridan help

**Comment by PKPenguin321** [comment]
One of my favorite PRs of this year

**Review by Shadowlight213 — APPROVED** [review]

**Comment by coiax** [comment]
But... I only multi-line strings? So this doesn't actually affect me?

**Comment by coiax** [comment]
To be honest, I'm more triggered by you butchering my name, MSO

**Comment by coiax** [comment]
I don't even contribute that much anymore...

**Comment by lzimann** [comment]
well, you were the only one that ever did it, and multi-lined shit that would fit more than fine in one line

**Comment by Cheridan** [comment]
this is a bullying-free zone, do not bully the coiax

**Comment by Cyberboss** [comment]
CHERI PLS!!!

**Comment by RemieRichards** [comment]
Coiax or not, this is a good change.

**Comment by Cheridan** [comment]
:C

**Pull request merged**
