### PR TITLE
Adds emp, emag, and repairs for barsign. 

### PR DESCRIPTION
**Pull request by Mandurrrh**
Exactly what the title says! Adds the ability to emag, emp, and a repair process to the new changeable barsign. Emagged barsign cannot be repaired. Emped bar sign can be repaired with screwdriver>cablecoil>screwdriver. Icons for both states. Thank you to @GunHog 

emped bar sign by @Chocobro 
barsignemp
emaged bar sign
syndibarsign

### CODE REVIEW

**Comment by dannno** [comment]
this should probably be merged after https://github.com/tgstation/-tg-station/pull/7942 and https://github.com/tgstation/-tg-station/pull/7992

**Comment by Mandurrrh** [comment]
It was originally made 4 days ago and got fucked up from paprika drama so it should go first.

**Comment by dannno** [comment]
it will

**Comment by Chocobro** [comment]
:+1: emp sprite by me

**Comment by Cheridan** [comment]
Dannno if it's an issue I'll do a manual merge on it, but I'm gonna go ahead and merge this for Mandurrrh since yeah she was inconvenienced by muh sign drama.

**Comment by dannno** [comment]
racist

**Pull request merged**
