### PR TITLE
New telecomm sprites

### PR DESCRIPTION
**Pull request by Lexorion**
## Replaces the old telecomm sprites with new ones
**Left**: Old ones
**Middle**: Proposed in #28285 before (didn't make it)
**Right**: Edited, new ones

### CODE REVIEW

**Comment by MoreRobustThanYou** [comment]
I LOVE EM (the ones on the right)

**Comment by Lexorion** [comment]
Woops forgot to fix something with the AAS_Off sprite (second last), will fix in a bit

**Comment by WJohn** [comment]
Awesome, you finished these up!

**Comment by nicbn** [comment]
third last could be more squarish, but it is really nice

**Comment by nicbn** [comment]
Can you increase the depth of the three last?
the sprites are great.

**Review by Cyberboss — APPROVED** [review]

**Comment by Dorsisdwarf** [comment]
last two look too thin, but these are okay i guess

**Comment by WJohn** [comment]
Yeah it'd be nice if you made the last two one pixel thicker.

**Comment by Lexorion** [comment]
Will do in a tiny bit, not at home!

**Comment by Bluespace** [comment]
Please get some server feedback too!

**Pull request merged**
