### PR TITLE
Flashman: The Suit

### PR DESCRIPTION
**Pull request by ExcessiveUseOfCobblestone**
:cl: Cobby
add: A suit made for people who love the new flash update!
/:cl:

Reasoning: It's a silly vanity item, and some people enjoy being able to dress up as wacky things. Unlike, say, the robbie rotten meme outfit, dressing up as a parody version of a weapon in the game will always be in good taste and not just a monthly meme.

flashman

### CODE REVIEW

**Comment by ExcessiveUseOfCobblestone** [comment]
f 

m

l

**Comment by ChangelingRain** [comment]
honestly this sprite is worse than the other one

**Comment by Kromgar** [comment]
Good god coder sprites are so bad

**Comment by ExcessiveUseOfCobblestone** [comment]
That's what I was going for, it was meant to be a silly item [hence why I added the big flash head]

**Comment by ExcessiveUseOfCobblestone** [comment]
I don't want to deal with the conflicts, whatever they are.

**Comment by Armhulen** [comment]
noOOOOOOOOOOOOOO

**Pull request closed without merging**
