### PR TITLE
Adds cybernetic lungs(and an upgraded and actually useful variety) to the game.

### PR DESCRIPTION
**Pull request by Firecage**
:cl: Firecage
add: The NanoTrasen Department for Cybernetics (NDC) would like to announce the creation of Cybernetic Lungs. Both a stock variety to replace traditional stock human lungs in emergencies, and a more enhanced variety allowing greater tolerance of breathing cold air, toxins, and CO2.
/:cl:

I am pretty sure that everything works. I would appreciate any feedback for this simple cybernetic item.

### CODE REVIEW

**Comment by JJRcop** [comment]
These should be susceptible to EMP. (Do we even apply EMP to organs yet?)

**Comment by Firecage** [comment]
Mmm, perhaps, if I get more feedback I will add an EMP effect to it to stop breathing. If no more feedback, I will make another commit for that alone though, would prefer not to do it for now for a single thing though.

**Comment by PraiseRatvar** [comment]
im p sure you can emp organs unless @Tacolizard was lazy.

**Comment by Firecage** [comment]
Mmm, trying to decide how EMP's would affect cybernetic lungs though. Mmm...

**Comment by JJRcop** [comment]
You can EMP cybernetic limbs but it doesn't do organs as far as I can tell. https://github.com/tgstation/tgstation/blob/030f08c8c69d315aa04930d1539db89025370ca1/code/modules/mob/living/carbon/human/human_defense.dm#L464-L478

**Comment by JJRcop** [comment]
Nope, I forgot to check carbon.
https://github.com/tgstation/tgstation/blob/030f08c8c69d315aa04930d1539db89025370ca1/code/modules/mob/living/carbon/carbon_defense.dm#L206-L210

**Comment by Firecage** [comment]
Ah, so it does do organs in general and doesn't necessarily require a special snowflake effect for an organ? Good.

**Comment by Repukan** [comment]
The whole point of cybernetic organs is them getting fucked by EMPs.

It's not an if you want to add it, it needs an EMP fuck up.

**Comment by PraiseRatvar** [comment]
@Firecage make it so krav maga's lungpunch has no effect and it's just a regular punch

**Comment by FantasticFwoosh** [comment]
I still think  "advanced cybernetic lung" and a regular cybernetic lung would still be justified rather than put a 1 of a type lung to be so special everyone's going to rush to implant it.

- So far the generic cybernetic heart has proved its value for being a cheap & disposable replacement, if we had generic replacement lungs we can replace all the chest cavity of a person without making them a powercrept implant-monster.

Here's how to nerf/fix strong androids - Give them all baseline cybernetic organs and watch them freak out when they get EMP'd despite being quasi-organic.

**Comment by The-clown-known-as-Pepe** [comment]
@Firecage is it possible to breathe lavaland air with upgraded lungs?

**Comment by Firecage** [comment]
Mmm, no, it still has the same minimum oxygen requirement as normal lungs, and Lavaland has oxygen as 14 instead of 16.

**Review by Cyberboss — APPROVED** [review]

**Comment by Tacolizard** [comment]
@Firecage It calls the emp_act() but by default emp_act() is just an empty proc on every organ. in order for emps to do anything you need to fill in that proc. 

@PraiseRatvar >:( i wasn't lazy i added emp to the cybernetic organs I added, it's just not a generic function on all organs

**Review by Tacolizard — CHANGES_REQUESTED** [review]
needs to actually have an emp_act()

**Comment by Firecage** [comment]
Oh, right, forgot about this. Uhhh, will add the emp_act effect later, wonder what specifically though.

**Comment by Repukan** [comment]
It's bad practice to not add an EMP effect because then it would be a net upgrade with no possible drawbacks.

**Comment by GunHog** [comment]
EMP effect should perhaps be just them shutting down for a while, long enough for a healthy player to pass out from oxyloss. A player hit by this will recover unless he has taken enough damage from other sources to fall into crit.

You could also consider muting the player (lungs offline, no air for your voice box) for the duration of the shutdown period.

**Comment by Firecage** [comment]
Well, I actually like the muting one.

**Comment by JJRcop** [comment]
I feel like it would be snowflake to have the muting be in the lungs, from what gun_hog said, you shouldn't be able to speak if you cant breathe period.

**Comment by Tacolizard** [comment]
@JJRcop @Firecage @GunHog 

Talking has nothing to do with your lungs. Your larynx vibrates the air in your throat to make noises. If your lungs didn't function, you could still talk. You'd be able to talk in short bursts as as your larynx pushes out the air and you wait for your throat to be filled back up from natural pressure.

**Comment by GunHog** [comment]
That is a good argument, but gameplay wise, it is a good downside to use. How would you figure we could hand-wave this, Tacolizard? Too busy gasping? Erratic lung function (instead of shutdown) disrupting your breath, resulting in stammering?

**Comment by KorPhaeron** [comment]
Just have the EMP turn them off for some period of time, you'll take a ton of oxyloss that way

**Comment by Firecage** [comment]
I want to update this PR....but bloody hell...the past few days...just...so...fucking...tired...

**Comment by GunHog** [comment]
Set the `losebreath` variable on the mob to simulate the shutdown.

**Comment by Firecage** [comment]
For the weirdest fucking reason, Dream Maker is taking an ETERNITY to compile these days? The fucking hell?

**Pull request merged**
