### PR TITLE
Makes SM delamination have a final countdown + some other minor tweaks

### LINKED ISSUE #36970: Supermatter instant delam megathread
https://github.com/tgstation/tgstation/issues/34732
https://github.com/tgstation/tgstation/issues/35468
https://github.com/tgstation/tgstation/issues/33507
https://github.com/tgstation/tgstation/issues/33982
https://github.com/tgstation/tgstation/issues/28638

### PR DESCRIPTION
**Pull request by ninjanomnom**
:cl: ninjanomnom
add: The SM has a guaranteed 30 second final countdown before delamination now
balance: The SM will take less damage from low pressure environments
balance: The SM has a slightly reduced max damage per tick
/:cl:

fixes #36970

This should help with the main culprit of sm sudden death and give a bit of time for the other kinds of failure.

I'd been considering the final countdown thing for a while now since SM delaminations are often hard to tell are about to happen. This gives a small period of time to be appropriately panicking regardless of how hard everything fucked up.

Considering it took less damage while in space/no air the reduced damage in low pressure environments makes sense.

### CODE REVIEW

**Comment by nicbn** [comment]
Dun dun dun dun
Dun dun dun dundun

**Comment by nicbn** [comment]
No causality field please

**Comment by CPTANT** [comment]
The supermatter already gives a huge countdown. Instant delamination is a bug that should be fixed, not bandaided like this.

**Comment by ninjanomnom** [comment]
This deals with a couple of the instant delamination issues in addition to the countdown. The countdown though is something I've been considering for a while now as a more dramatic way of marking the incoming disaster. It's not *just* a bandaid fix.

**Comment by Davidj361** [comment]
@praisenarsie 
>there should be an ai vox countdown and it gets more static or broken as it get closer to the explosion with scary electric sound in the background.
With the AI voice or announcement voice? Because announcement voice is usually used for this.

**Comment by MrDoomBringer** [comment]
[@praisenarsie @DaveTheHeadcrab omg fuck yes this in my ss13 please](https://youtu.be/F3vjcql7RB8?t=285)

**Comment by RandomMarine** [comment]
>I'd been considering the final countdown thing for a while now since SM delaminations are often hard to tell are about to happen.

Reminder that engineers have tablets which can run the SM monitor program.

**Comment by arsserpentarium** [comment]
You should make countdown to countdown yo countdown. Voice of every new iteration of countdown should be more distorted.

**Comment by MimicFaux** [comment]
For all those wanting a distorted countdown, This is pretty much exactly what we want.
https://www.youtube.com/watch?v=R3PuAKR2vlA

**Comment by ninjanomnom** [comment]
@RandomMarine I was referring to the rest of the crew. If the engineers don't know it's happening you have some bigger problems.

**Comment by RandomMarine** [comment]
The rest of the crew aren't really in any immediate danger from the SME exploding in their faces while they're trying to fix it?
Why do they need a precise countdown?

**Comment by Jalleo** [comment]
@RandomMarine it can randomly go from fine to explode in a instant. This is to help manage that.

**Comment by CPTANT** [comment]
It just shouldn't go from 100% to 0% instantly in the first place.....

**Comment by ninjanomnom** [comment]
Other parts of the SM can be made slightly more dangerous if there's a minimum time for delamination. Having a proper countdown for when the SM explodes gives the whole event a more tangible sense of danger than otherwise.

The other parts of this pr would probably do the job on their own but having an actual timer for the coming explosion is helpful. As an engineer fluctuations in the game lag will often change the rate the sm gets damaged and knowing you'll have at least 30 seconds of time even if you get fucked over by those fluctuations makes it easier to stay until the last moment trying to fix the problem.

That last moment scramble to repair the SM is what I'm trying to encourage here.

**Comment by MrDoomBringer** [comment]
even if it has some small flaws, five seconds doesn't really effect _that_ much, while at the same time it makes the SM explosion so much more interesting from a gameplay perspective. The pros really outweigh the cons here imo

**Pull request merged**
