### PR TITLE
New sprites for escape pods and dark shuttles

### PR DESCRIPTION
**Pull request by Core0verload**
This PR adds new sprites and objects that are not in game yet.

Dark shuttle airlock and windows:
sh_windoors

New badass pods, based on sprites found on tgdb:
sh_newpod

### CODE REVIEW

**Comment by Militaires** [comment]
i like it, alot, like alot.

**Comment by Niknakflak** [comment]
Besides the shuttle pod engines and the shuttle pod airlock, the "dark" icons are literally 100% the same as the other icons just darkened which can be achieved through the color variable, setting their color hex value to a gray dark color, which simply darkens the sprite.  That being said, why would you also make a completely new dmi for these icons and not just put them where the old shuttle windows and airlocks are?

**Comment by Core0verload** [comment]
> That being said, why would you also make a completely new dmi for these icons

Because of how airlock icons / smooth icons work. They would conflict if put in a single .dmi

>the "dark" icons are literally 100% the same as the other icons just darkened which can be achieved through the color 

Dark icons are not "100% the same", you can try to achieve the same effect with color var and fail. Why? Door bolts.

**Comment by PKPenguin321** [comment]
arent bolts overlays that wouldnt be affected by applying color to the base sprite

**Comment by Core0verload** [comment]
>arent bolts overlays that wouldnt be affected by applying color to the base sprite

Have you ever tried applying color to humans? Overlays _are_ always affected by base item's color.

**Comment by WJohn** [comment]
These look pretty great. The only thing I'm not fond of is the border on the diagonal walls. The borders look sort of like padding, and that'd be fine if it was at least consistent around the pod, but it isn't right now.

Engines look fantastic.

**Comment by AnturK** [comment]
> Have you ever tried applying color to humans? Human icons are made out of overlays. Overlays are always affected by base item's color.

RESET_COLOR exists not that's really relevant to this PR

**Comment by Bawhoppen** [comment]
the pod looks too mechanical and rough and not as sleek, and while the old shuttle walls looked quite bad I liked what they were going for

**Comment by ChangelingRain** [comment]
Yeah I don't like those pod sprites so much, and the door isn't even in the same style as the rest of the pod.

**Comment by GunHog** [comment]
The Syndie Shuttle is beautiful. The pod walls look smashing! The door, as Joan points out, looks weird-ish. The engines, while looking BEEFY, come in at a very odd looking angle. It probably would not look so out of place if Space-cliffs were added as well.

**Comment by Niknakflak** [comment]
Bolts applies to the airlock, now the windows and shutter.  Windows are shutter different sprites are un-needed

**Comment by KorPhaeron** [comment]
The engines being at a different perspective than the walls look weird as hell

I like the rest though

**Comment by Ausops** [comment]
the engines look weird because they were made a long time ago for use with other things with that perspective

please don't use them

**Comment by KorPhaeron** [comment]
@Ausops 

I miss you come home

**Comment by Aloraydrel** [comment]
AUSOPS COME HOME PLEASE!! YOUR SOUP IS COLD

**Comment by optimumtact** [comment]
@WJohn was that a yes or no on this?

**Comment by Core0verload** [comment]
If anyone is wondering, I will fix conflicts once there is a merge/no merge decision.

**Comment by WJohn** [comment]
I'll okay this if the diagonal walls are fixed. The borders don't look terribly good.

Frankly we just need to get away from our oldstation engines they're hideous.

**Comment by Core0verload** [comment]
Not sure what are you talking about, let alone how to fix it.

**Comment by WJohn** [comment]
I mean the diagonal walls and the outside "border" they seem to have. Take a look at the pictures you provided, and notice how the border there doesn't align correctly with the horizontal or vertical wall sprites. That doesn't look terribly good.

**Comment by optimumtact** [comment]
stale.

**Pull request closed without merging**
