### PR TITLE
[READY]Circuitry lab.

### PR DESCRIPTION
**Pull request by arsserpentarium**
My attempt to make better circuitry lab project for box,meta,and delta.
Box:
image
Meta:
image
Delta:
image

### CODE REVIEW

**Comment by deathride58** [comment]
Any screenshots from dreammaker?

**Comment by arsserpentarium** [comment]
delivered

**Comment by deathride58** [comment]
Aight, so a couple of gripes

- Pipes and wires are going through walls when it isn't necessary to do so. This is a poor practice that results in issues during gameplay for atmos techs and engineers.
- The orientation of the tables seems like it'd be pretty awkward during gameplay, especially during melee combat in the area. The chairs facing the walls also make the area feel a lot more cramped than it really is.
- There's way too many seats compared to the amount of scientists that will likely be making actual use of the lab. You don't need to accommodate for all of the available job slots outside of deltastation. You only really need to accommodate for two scientists, if xenobiology's accommodations are anything to go off of.
- There's no need for reinforced tables in the labs, as that hinders the potential for players to renovate the area
- The design of the tables makes the area feel more like a corporate office than the workshop it's supposed to be. You could probably check pinterest or google images for inspiration to make the area feel like a workshop.
- You might also want to take inspiration from John Romero's map design philosophies. Take a little bit of time to study Romero's maps in the classic DOOM games, most of the important philosophies transfer over well to SS13 map design. To be a little more specific, you might end up with a much more interesting area with much more interesting gameplay if you take the phrase "symmetry is lazy" to heart.

Hopefully ya got some good ideas on how to improve things after reading that wall of text. I wish ya luck, man.

**Comment by arsserpentarium** [comment]
1.not too much.
2.well,comfy chair+ big table. This configuration is providing the biggest possible work area.
3.mkay
4.reinforced table is screwdriver-proof. That,'s main reason to do so.
5.circuitry lab IRL is a lot like office. But with soldering tools,wires and parts. 
6.give me a link.

**Comment by Repukan** [comment]
Too much metal

**Comment by Tlaltecuhtli** [comment]
maybe a bit of cells and a practice laser to test murder drones

**Comment by arsserpentarium** [comment]
There is 2 stacks of metal now. So it's ok anount of metal.

There is cells under metal sheets. I' could add laser gun. But probably it should be added on rack or into closet. What can I put there along with practice gun? It's rather stupid to put closet for only one object.

**Comment by Iamgoofball** [comment]
Literally ignore anyone bitching about too much metal, it's the most common material in the game

**Comment by Bawhoppen** [comment]
Don't remove the firing range from the misc lab. Just add it in somewhere else.
Also it IS too much metal. I don't know what goof is on, but I'd say you should probably ignore him (from his history if nothing else)

**Comment by Bawhoppen** [comment]
Also additionally, pipes and wires going through walls is a big mapping no-no, ask WJ about it if you don't believe me.

**Comment by arsserpentarium** [comment]
1.you need about 18 sheets of metal for somewhat wothful drone. And it's still much less metal,then robotics has.
2. I'll try to stick it somewhere,if I'll know,where. But now science hasn't guns.  So why bother?
Also firing range was removed only on boxstation.
On meta I've replaced some maint.
On delta I've renovated abandoned RnD.
3.well, on 2 of 3 maps it can't be avoided. Because there is only one door.

**Comment by arsserpentarium** [comment]
Also, Bawhoppen, I wonder. Basically I hear from you suggestions to nerf something,or make something more difficult and less usable.
Do you think, that SS13 is too simple?

**Comment by Ratvar** [comment]
All that plasteel for all those ripleys/bloodcult machines, mmmm

**Comment by jughu** [comment]
>says reinforced tables are used because you cant screwdriver them
>uses normal table for delta ????

Besides all you need is 1 table and a chair to auctally being able to work

**Comment by Bawhoppen** [comment]
@arsserpentarium Whether something is currently over-simplified or not, is kind of based on the specific topic. I ultimately think we want to create mechanics that aren't shallow, and add a meaningful feeling of complexity, while still having the integrity to be a reasonable game mechanic. This will help provide a strong aura of realistic flavor, while also ensuring a suitable balance game-wise.  This, of course, matters quite alot, considering this game first and foremost, is about roleplaying, where your immersion significantly impacts how much you can actually enjoy the game.

However, this particular case revolves around the issue of over-supplying individuals with certain resources. Imagine hypothetically, if we just gave all antags free explosives to use everywhere all the time. It would completely remove the novelty and excitement of actually managing to bomb things. This applies to the effort needed to achieve something aswell. We saw this with old R&D, where you just did a few button presses every round, to be able to get all kinds of crazy and powerful guns, which basically removed all the thrill from being able to get ahold of them. (See this everywhere else in the world too. Tell me the last time you thought an explosion in an action movie was cool.)

Giving a couple extra sheets of metal is a much more minor scale, but every little tidbit adds up to the devaluation in certain areas of the game. You should have to do some work to reach the cool and fun parts of the game, rather than SS13 just being another bit of cheap quick amusement. To make a good feature, you always should always show some level of restraint, which is something alot of people tend to not like to do.

**Comment by Bawhoppen** [comment]
Also my downvote was only a modest one, I don't have any huge gripes with this specific one besides what I already said, and even then it's minor.

**Comment by Tlaltecuhtli** [comment]
move the crate with shooting targets to the drone lab and add some practice lasers

**Comment by Bawhoppen** [comment]
Oh and just because scientists don't get guns typically, doesn't necessarily mean they shouldn't have some kind of firing range to test contraptions that shoot stuff. Though it does make it alot more niche and less important.

**Comment by arsserpentarium** [comment]
0.You are right. But sometimes some things are just frustating. Like battles between scientists for metal for their printer. There is no thrill to do so. Because of you are getting to tinker with some construction, you don't want to encounter problem of rapidly acquiring needed metal.
1.honestly,I just tired to roam around in attempts to steal 25 metal. So 2 full loads of printer is exactly needed amount per user.
2.there was unbelievably cool explosions in Song of fire and Ice. Seriously. Lannisters BURNS! 
3.Old RnD was shit. But still better, than techpoints system.
Old was like "tell Santa poem to get present". You should at least know the poem to tell(sequence of minimaxed items).  So you can get your super guns incredibly fast if you have skill and knowlege.
Now it is like "wait in line to get present to someone else." Techpoints is depends only on your survival. And barely can offer something interesting to scientists. And only legitimate way to speed them is to be preciecly drunk.  It sucks.
4.mkay.I'll stick crate in.
5. Tell me where to put firing range.  Or just add it yourself later, if you think,that it is so important.

**Comment by Repukan** [comment]
Scientists can get metal from

1.Tool Storage
2.Autolathe
3. Mine it themselves with their pods
4. Robotics
5. Deconstructing tables

They should make some effort to procure materials, not have everything spoon-fed to them.

**Comment by davethwave** [comment]
They forget that the chairs to the walls are even made of metal and can be deconstructed easily if you so desperately need metal

**Comment by davethwave** [comment]
They forget that the chairs to the walls are even made of metal and can be deconstructed easily if you so desperately need metal

**Comment by arsserpentarium** [comment]
But still,if you wanna tinkering,metal-rushing is just irritating. It could be fun if you are trying to mass-produce smth. 
Why not remove metal from robotics to doom them beg cargo and deconstruct chairs,tables and walls?

**Comment by davethwave** [comment]
all robotics needs is one stack of metal which would allow them to get a engineering borg. Then that borg can pump out as much metal and glass as the station needs. A fully upgraded borg recharger regenerates 4 metal/glass per second or so when fully upgraded and the engineering borgs can hold 50 sheets of metal at a time. The borg just needs to build 5 modular computer frames and deconstruct to get a full stack of metal for someone. The only way for this to not work is for the room with the charger to be unpowered or the person who is the borg decides to become a mediborg or something similar and run off.

**Comment by GunHog** [comment]
Going though those sorts of hoops should be unnecessary.

**Comment by epochayur** [comment]
arsser delivers yet again

iirc, 25 metal sheets is enough to completely top off an ICP, which means you can have two people working on any machine they could possibly want for a good while with just a single stack. I really don't think metal is so much of a big deal that there can't be one stack to get the ball rolling. If it was out in the lobby for public use, that's one thing, but R&D and robotics both have enough mats to get them off the ground. With this effectively being its own sub-department, I doubt adding a little more so prospective circuit scientists don't have to race assistants to tool storage/bogard mats from the public autolathe will hurt anything. Worst case, the extra metal can be removed later.

Also, who the hell actually uses the firing range?

**Comment by Bawhoppen** [comment]
It's nice to have a firing range in case someone actually wants to use it

**Comment by epochayur** [comment]
like for what? actually curious, not being accusatory

**Comment by coiax** [comment]
I like the idea, except the execution on Meta. It cuts the maintenance section passage off, so you can't get through without Science access.

**Comment by arsserpentarium** [comment]
Yet again:
1.Either you can point to me to the place for science firing range.
2.Either you can map it yourself.
3.Or you can just fuck it.
This is 3 main possibilities for you, how to deal with this situation.

**Comment by Bawhoppen** [comment]
I didn't say it was the hugest deal, don't get the wrong idea

**Comment by arsserpentarium** [comment]
Box:
image
Meta:
image
Delta:
image
I've tryed to fullfill most of requests.

**Comment by arsserpentarium** [comment]
I want advice,how to fix conflict.

**Comment by jughu** [comment]
Remove the expirimentor place it in the misc testing room for box expirimentor doesnt need a whole room for itself place the expirimentor in the misc containtment and you have a whole room for circuits without messing with firing range and you rnd right around the corner

**Comment by Bawhoppen** [comment]
The experimentor actually does need its own room. If you have ever used it, you'd agree with me on this one

**Comment by JStheguy** [comment]
Speaking as someone who's put a decent bit of time into circuitry, I'll be honest, these lab designs seem kinda bloated, for lack of a better term.
The labs being decked out with a protolathe AND an autolathe seems very overkill and only tangentially related to the purpose of a circuitry lab, the Vendomat is completely useless as nothing it vends is actually used for integrated circuits, and the library publishing setup is not going to be very useful, given that the character limit on books is too small to hold anything other than the most basic of designs.

Also you misspelled technical as "Tecnical" when you edited lib_machines.dm

**Comment by jughu** [comment]
Bawhoppen i mean the room at box next to the firing range with the  reinforced floor section

**Comment by Bawhoppen** [comment]
That's too small of an area and is close to sensitive stuff. It needs to be somewhat isolated and secure, otherwise everything around it gets EMPed, gassed, or blown up

**Comment by arsserpentarium** [comment]
1. Bawhoppen is right. Experimentor needs it's own room. And it's much more often used, then firing range.
2.Vendomat is needed yo get signallers.
3. Protolathe to get more power cells/printers.
4.autolathe not directly related to circuits,but for me it's more easy to use.
5. You can stick into book any design. You should just make the book with blank list, then add design by parts.

**Comment by Partheo** [comment]
Looks like lazy mapping to me, I just don't like the look of it.
Also, it's a small thing, but I hate the armchairs. It makes no sense to have armchairs in a workshop, especially at a table that encircles the chair. Just imagine sitting in a comfy armchair and turning around, over the armrest, to solder a component on your left. On a reinforced table no less. It doesn't fit. I would make them office chairs.

**Comment by arsserpentarium** [comment]
I'll change chairs. But can you tell another advices?
I've tried hatd,but it's my first mapping experience.

**Comment by arsserpentarium** [comment]
I've tryed to upload my design to regular library console. 
I've made blanc book. Then I added my code in two parts. All was correct. Then I sticked it into scanner, uploaded book and tryed to find it in catalogue. Unholy fucking shit. It was... Well... I didn't expected it.
Uh...fuck...got wood. Looks like it's much more difficult to find your blueprint.even if you've uploaded it.

**Comment by epochayur** [comment]
there's a reason no one plays librarian

**Comment by ExcessiveUseOfCobblestone** [comment]
Either delete the metal in the circuit lab or delete the metal right outside of it please.

**Comment by arsserpentarium** [comment]
Carolyn Miller | Farmbot MK4.20 | Reference
Try to find it on Bagil. it works.

**Comment by FantasticFwoosh** [comment]
@Bawhoppen you are correct on the experimentors room requirements, but we don't need the experimentor nessecarily.

**Comment by arsserpentarium** [comment]
relics is still fun. Because of corgispawner.

**Comment by FantasticFwoosh** [comment]
Maybe, but thats a very fickle edge-case benefit given that the experimentor only has one beneficial malfunction, and limited tech level gain from upgrading items to get better tech value strange objects.

Outside of that it has a lethal and poor decision marked past of summoning meteors, throwing fireballs in scientists faces (still does that) and turning people into xeno hunters that people just rammed button prompts for.

**Comment by nicbn** [comment]
Box APC is not even wired

**Comment by ShizCalev** [comment]
@nicbn Fixing that

**Review by ShizCalev — CHANGES_REQUESTED** [review]
Found a ton of issues, I'll open a PR on your branch.

**Comment by arsserpentarium** [comment]
I found where merge fucked up.I fixed it.

**Review by ShizCalev — CHANGES_REQUESTED** [review]
https://github.com/arsserpentarium/tgstation/pull/3

Box:
Fixed unwired APCs
Fixed broken wiring
Fixed unconnected piping
Fixed removed testing lab APC
Fixed missing cameras
Fixed incorrectly named / configured APC
Added request console
Fire alarm

Meta
Fixed broken wiring
Fixed unconnected piping
Fixed missing cameras
Fixed incorrectly named / configured APC
Added request console
Fire alarm
Fixed maintenance access being wrong
Corrected maint floor patern to match the rest of the station
Fixed missing firedoors
Fixed missing decals

**Comment by arsserpentarium** [comment]
uhhhh...thanks.

**Review by ShizCalev — CHANGES_REQUESTED** [review]
Can't put my rubber stamp on Meta since you bisected maintenance without creating a new path. 

Might want to try shifting the testing range and circuit lab down and right a bit, making a new entrance to the lab on the south side and making a maint corridor around the west / north side of the circuit lab. Just make sure to adjust the bomb testing site to match up as well.

**Comment by arsserpentarium** [comment]
What is better?

**Comment by GunHog** [comment]
I prefer the bottom one, because I do not need to move as much to reach all the equipment.

**Comment by arsserpentarium** [comment]
Looks like it's ready.

**Comment by arsserpentarium** [comment]
uhhhhh

**Comment by ShizCalev** [comment]
top one was alot better imo.

**Comment by arsserpentarium** [comment]
I've tried to make room that way to make possible to access all necessary equipment without crossing test area. Usually in similar IRL labs it is necessary requirement to workshop.  
How important is similariry to IRL labs in SS13?

**Comment by Bawhoppen** [comment]
Somewhat.

**Comment by ExcessiveUseOfCobblestone** [comment]
Replace an end table with the machinery.

**Comment by arsserpentarium** [comment]
Not the best idea. I need either duplicate machinery. Or player will need to switch places.rather stupid.

**Comment by Tlaltecuhtli** [comment]
oh also add 1 camera console with science network for cam drones

**Comment by arsserpentarium** [comment]
Ugh...okay...I'll try.

**Comment by Bawhoppen** [comment]
Don't add that camera console. That's giving players too much to start with.

**Comment by arsserpentarium** [comment]
well, not to start with. Barely they will obtain camera console in other case.

**Comment by nicbn** [comment]
Science already has a test chamber that is almost never used, why should we have another?

**Comment by ExcessiveUseOfCobblestone** [comment]
@arsserpentarium do the top layout and replace the two tables hitting the rwall west side with the 2 machines. You can also move the photocopier to the east wall, move the vending machine east one tile, and pixel_var edit that stock machine looking computer+table so the area appears much more open for "testing".

**Comment by arsserpentarium** [comment]
image
How about this version? target stake,lasers, vendomar with signallers are near that room, but not inside.

**Comment by ExcessiveUseOfCobblestone** [comment]
Put everything but the disposal bin on the bottom wall opposite of the cubicles and I think it'll look alright.

**Comment by ShizCalev** [comment]
Just looking at that pic;
Space tiles under the windows
No fire extinguishers
No cameras
Are there firedoors underneath the airlocks? Is the wiring complete there too?
No request console
Could use a few more posters or something to make the walls less bland.
Both stations look like they're just copypasta'd, mind shuffling the stuff on the tables around a touch?

**Comment by arsserpentarium** [comment]
Got it

**Comment by arsserpentarium** [comment]
image
How about this?

**Comment by GunHog** [comment]
I would suggest moving the protolathe and autolathe to the current location of the bottom-middle tables.

**Comment by arsserpentarium** [comment]
delete bottom-middle tables?

**Comment by arsserpentarium** [comment]
FFFFFFFUUUUUUUUUUUCCCKEN RAAAAAAAAAGEE!LOCAL REPO CORRUPTED!HIMMELDONNERWETTER!

**Comment by arsserpentarium** [comment]
didn't deleted tables.I forgot.Without table question all done.If you very want it, I'll make it, but ,honestly I'm lazy.

**Comment by arsserpentarium** [comment]
image
final

**Comment by ChangelingRain** [comment]
The fire alarms in the box and meta versions aren't properly centered to the walls, and the delta version lacks them entirely.
In addition there's a huge chunk of pipe under reinforced walls in the box version and that's just not on.

**Comment by arsserpentarium** [comment]
There is fire alarm. But I can't dig out pipes from wall: no space for them

**Comment by ShizCalev** [comment]
Conflict.

**Comment by ChangelingRain** [comment]
All of your fire alarms have improper pixel shifts, and you need to fix that.

**Comment by arsserpentarium** [comment]
which I should use?

**Comment by arsserpentarium** [comment]
New branch to unfuck merge.
https://github.com/tgstation/tgstation/pull/34493
Everything fixed so far.

**Pull request closed without merging**
