### PR TITLE
Changeling revive won't work while the changeling is on fire

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
:cl: Kor
add: Changelings are now unable to revive while on fire.
/:cl:

Why: Changelings often smash the gibber and crematorium right away and then the crew is stuck dealing with a whole team of monsters that are constantly unstunning, healing, coming back to life on a 40 second timer with very few reliable ways to restrain them temporarily never mind eliminating them for good.

This seemed like a lore friendly way to give people a backup option for delaying a changelings respawn without completely nullifying their ability to do so (fire is gonna go out eventually, unless maintained)

I'm not 100% sold on this so arguments as to why this is awful are welcome

### CODE REVIEW

**Comment by Armhulen** [comment]
thinglings

**Comment by Cyberboss** [comment]
>with very few reliable ways to restrain them temporarily never mind eliminating them for good

Cargo/prison shuttles

**Comment by PKPenguin321** [comment]
Buckling lings onto bonfires sounds hard core

**Comment by epochayur** [comment]
600px-thing17

**Comment by KorPhaeron** [comment]
@Cyberboss those are the few yeah

**Comment by TimeIsEndless** [comment]
Sounds great. now there is an actual reason to put them in the turbine incinerator.

**Comment by Ratvar** [comment]
Throw them into slime cells/ put them on meatspike

**Comment by Potato-Masher** [comment]
Sounds good to me.

(thingling > ...protoling?)

**Comment by ma44** [comment]
*throws a zippo lighter*

**Comment by MoreRobustThanYou** [comment]
Reminds me of my old ling overhaul pr

**Comment by Robustin** [comment]
RCDing a naked ling was already the best solution because you'd do it in a deserted corner and then get a 2nd or 3rd ling when they try to bail him out. 

2nd best method is killing them naked, dragging them a couple z_levels out, then leaving them in deep space with no way to move when they revive. 

But while I don't think there's a "problem" with finding ways to keep lings dead, adding one more niche to the list isn't going to be too problematic either.

**Comment by InsaneHyena** [comment]
This kills the minerling. Good riddance.

**Comment by evsey9** [comment]
this makes plasmafloods even stronger now

**Comment by JohnMcLaime** [comment]
RCDing to bait other lings as the guy above said.
Ripley drill gibs corpses.
Gib them with gulag/mining shuttle.
Or 100 100 potawater grenade.

**Comment by PKPenguin321** [comment]
??

**Pull request closed without merging**
