### PR TITLE
Shrink serum

### PR DESCRIPTION
**Pull request by jughu**
Shrink serum which can make yourself half the size if you get enough of it currently not in game and admin only

shrink serum to compete with its counter growth serum

:cl: Jughu
add:Adds shrink serum
/:cl:

### CODE REVIEW

**Comment by XDTM** [comment]
how small can you get with this + dwarfism

**Comment by jughu** [comment]
this let you up to 0.5 size not lower

**Comment by Cyberboss** [comment]
Recipes???

**Comment by jughu** [comment]
NOT yet

**Comment by jughu** [comment]
read pr body nerd

**Comment by Shapsy** [comment]
If admins really want to resize someone they can do it directly via variables, this just feels like trying to add something to the main game in multiple stages.

**Comment by jughu** [comment]
ok somoene give me a good uh recipe then involving growth serum atleast in the recipe

**Comment by RandomMarine** [comment]
It'd be something that every powergamer will just demand in droves to make their sprites harder to click on.

**Comment by Aloraydrel** [comment]
What is resize

**Comment by jughu** [comment]
YOU ALL RUIN MY DREAMS YOU GITHUB BULLIES ;(((

**Comment by Cyberboss** [comment]
RIP in piece

**Comment by calzilla1** [comment]
RIP in peinis

**Comment by jughu** [comment]
i mean with growth serum is basically just like shrink serum but just mis targetting

**Pull request closed without merging**
