### PR TITLE
Fixes exosuit console issues

### PR DESCRIPTION
**Pull request by ShizCalev**
Fixes #41299

:cl: ShizCalev
fix: Fixed exosuit console showing some code by accident.
fix: Restored the ability to send EMP pulses via the exosuit console
fix: Fixed tracking beacons being added to mechas located at ruins allowing you to metagame their spawning.
fix: Fixed exosuit consoles presenting some values via scientific notation (ie pressure being 3.258e-5)
/:cl:

Also cleaned up the output a bit since it was all presented as a single line wall of text.
image

### CODE REVIEW

**Comment by Tlaltecuhtli** [comment]
@Razharas 
tgui is a downgrade

**Comment by Barhandar** [comment]
pure html machinery is order of magnitude faster to operate than tgui

**Review by SpaceManiac — APPROVED** [review]
fix your font rendering settings, that screenshot is making my eyes bleed

**Comment by SpaceManiac** [comment]
full-size version looks just as bad, must be a monitor thing

**Pull request merged**
