### PR TITLE
Nerfs CLF3 and re-enables it.

### PR DESCRIPTION
**Pull request by Iamgoofball**

### CODE REVIEW

**Comment by Razharas** [comment]
It still only affects turfs?
Meh

**Comment by Iamgoofball** [comment]
It lights people on fire, too. I'm considering making it melt objects too.

**Comment by Cheridan** [comment]
I certainly hope this fixes
#7100 
#7075 
#7076 
#7094

**Comment by Iamgoofball** [comment]
clf3 can stay dead for now

**Pull request closed without merging**
