### PR TITLE
Renames Mindbreaker Toxin to Mindbreaker Serum

### PR DESCRIPTION
**Pull request by DaCoolBoss**
## About The Pull Request
See title.
## Why It's Good For The Game
The name implies it either does toxin damage or damages the brain. It doesn't do either, it makes you hallucinate.
## Changelog
:cl:
spellcheck: 'Mindbreaker Toxin' now named 'Mindbreaker Serum'
/:cl:

### CODE REVIEW

**Comment by necromanceranne** [comment]
I think it does liver damage actually.

**Comment by zoomachina** [comment]
> A potent hallucinogenic compound that is illegal under space law. Formerly known as LSD, but was renamed so people understand that it is not a "fun time"
(c) wiki

**Comment by DaCoolBoss** [comment]
> I think it does liver damage actually because it is the TOXIN subtype.

This is the kind of misconception that made me want to rename it. Normally this is the case, but for mind breaker it isn't true because it's toxpwr stat is 0.

> > A potent hallucinogenic compound that is illegal under space law. Formerly known as LSD, but was renamed so people understand that it is not a "fun time"
> 
> (c) wiki

I don't see the problem here. The operative scary word is 'mindbreaker'.

**Comment by Time-Green** [comment]
I don’t think serum is anymore accurate. ‘Toxin’ is also ss13 lore

**Pull request closed without merging**
