### PR TITLE
Adds departmental circuit imprinters to each department

### PR DESCRIPTION
**Pull request by silicons**
Also moves service lathes/printers to HoP office on all maps except omega and delta. On omega they're still in the top entrance to the bar, and on delta they're still in the service hallway.
Yes I know they don't have much if any at all designs but we can argue about who gets what after I suffer from not knowing how to map.

### CODE REVIEW

**Comment by Iamgoofball** [comment]
why

just merge into protolathe

**Comment by FantasticFwoosh** [comment]
Even better just let the department lathes print off particular types.

**Comment by 81Denton** [comment]
I'd like it better if the service lathe was not inside the HoP office. Hell, most HoPs can't be bothered to be in their office for access changes at all.

**Comment by praisenarsie** [comment]
# kevinz stop smoking powercreep

**Comment by praisenarsie** [comment]
actually wait this is basically bring back old rnd except just giving it to every department

**Comment by kevinz000** [comment]
@praisenarsie no it's so people can actually print their machines.

**Comment by kevinz000** [comment]
old rnd is science got everything.

**Comment by Hatfish** [comment]
>Also moves service lathes/printers to HoP office on all maps except omega and delta
can you not just find somewhere to place it where all civilian jobs can access it without having to break and enter?

**Comment by kevinz000** [comment]
@Hatfish ok then where else?

**Comment by Hatfish** [comment]
Primary or auxilary tool storage would be easily accessible by all civilian departments.

**Review by Cyberboss — CHANGES_REQUESTED** [review]
Service lathe belongs in tool storage

**Comment by Alek2ander** [comment]
There's this room called Tech Storage that's literally made for storing circuits.

But no, that would mean sometimes actually having to leave your room.

**Comment by 81Denton** [comment]
>There's this room called Tech Storage that's literally made for storing circuits.

Tech storage is access restricted, why the hell would you put unrelated department printers there

**Comment by Bawhoppen** [comment]
@Alek2ander I got shut down so hard when I tried to move circuits that should belong there into there. It's an uphill battle for trying to make a reasonable change. Godspeed to you good sir if you try such a thing.

**Comment by ShizCalev** [comment]
image

Probably would be better to just merge it's features into the protolathe to cut down on redundancy.

**Pull request closed without merging**
