### PR TITLE
Have you tried pooling the beams?

### PR DESCRIPTION
**Pull request by Iamgoofball**
An ancient shitpost.

### CODE REVIEW

**Comment by JJRcop** [comment]
This whole list should be in strings

**Comment by XDTM** [comment]
The return of braindamage lines

**Comment by LemonInTheDark** [comment]
On one hand I want your soul over some of your code, on the other, it's good to have ya back.

**Comment by trollbreeder** [comment]
do you know who wrote all the brain damage lines

**Review by Cyberboss — CHANGES_REQUESTED** [review]
Move these to strings

**Comment by ExcessiveUseOfCobblestone** [comment]
brain damage lines 2.0, now all we need is for goof to post about how these lines are bad and we can get 2/2

**Comment by Tharcoonvagh** [comment]
Who you gonna call

**Comment by optimumtact** [comment]
brain damage lines 2.0

**Pull request closed without merging**
