### PR TITLE
Include temporary library for getting sleeping procs

### PR DESCRIPTION
**Pull request by Mothblocks**
@LemonInTheDark wanted this to be able to hunt down the progress bar hard dels.

Code is here: https://gist.github.com/Mothblocks/06b415afd75672fb03637804435350d2

Intended to be reverted once we figure out the issue, or if we realize it's not related. This library is not stable.

### CODE REVIEW

**Comment by Mothblocks** [comment]
Failing because I think I need to build these for newer Ubuntu

**Comment by ZephyrTFA** [comment]
Instead of making this temporary, can we make it a compile flag? I feel like this will be useful for more stuff in the future

**Comment by Mothblocks** [comment]
i want no expectation on me to maintain this

**Comment by Mothblocks** [comment]
http://www.byond.com/forum/post/2884204

**Pull request merged**
