### PR TITLE
Makes his grace available for GREYTIDE

### PR DESCRIPTION
**Pull request by jughu**
Greytide praises toolboxes too OK

:cl: Hyena
Tweak:makes his grace available for assistants
/:cl:

[]: # (Please add a short description of why you think these changes would benefit the game. If you can't justify it in words, it might not be worth adding:)I PRAISE THY MIGHTY TOOLBOX

### CODE REVIEW

**Comment by Militaires** [comment]
yes

**Comment by Armhulen** [comment]
yes

**Comment by Cyberboss** [comment]
Play chaplain you autists :-1:

**Comment by InsaneHyena** [comment]
No. Job-specific traitor items should be job-specific. I don't care if His Grace is a chaplain item or an assistant item, as long as its exclusive for one of them.

**Comment by ShadowDeath6** [comment]
>Makes evil body consuming monster that just so happens to look like a toolbox so chaplain can feed the unholy beast as traitor
"It toolbox and astants like toolboxes so it for assistant too"

**Comment by ChangelingRain** [comment]
Multiple assistant traitors are WAY more likely than multiple chaplain traitors.

**Comment by Kraseo** [comment]
considering there's only one chaplain slot roundstart your math is solid joan

**Comment by jughu** [comment]
considering hop can open more chaplain slots

**Comment by SgtxRootbeer** [comment]
Couldn't people do the agent card trick with a friend?

**Comment by Iamgoofball** [comment]
:-1:

His Grace is specifically themed around chaplains. Keep it to the chaplain, idiot.

**Comment by Cheridan** [comment]
Job-specific traitor items should be job-specific.

**Pull request closed without merging**
