### PR TITLE
Temporarily removes the magnetic control console

### LINKED ISSUE #49025: Holodeck Firing Range target stake doesn't work
Issue reported from  Round ID: 128971 (/tg/Station Manuel [ENGLISH] [US-WEST] [ROLEPLAY] [99% LAG FREE])

Reporting client version: 513.1507

To reproduce: 
Holodeck, turn on the firing range
go to the control panel
do as the instructions said
nothing happens?
Képernyőfelvétel (10)

### PR DESCRIPTION
**Pull request by Tharcoonvagh**
## About The Pull Request
It is currently bugged and refuses to work properly

## Why It's Good For The Game
less shit

## Changelog
:cl:

del: magnetic control console temp removed

/:cl:

If this isn't the proper way please don't yell @ me

### CODE REVIEW

**Comment by Tlaltecuhtli** [comment]
unmap it?

**Comment by HomocidlePancakes** [comment]
Why are you closing the issue? You aren't fixing it, you are just temporairly removing it. Heck, why does it even need a temporary removal?

**Comment by PKPenguin321** [comment]
Yeah this is useless

**Comment by Neo-0** [comment]
?????????? https://github.com/tgstation/tgstation/pull/49639/files#diff-36ef65aab023692ae8d692035b72b331R192

**Comment by Tharcoonvagh** [comment]
Alright, im removing it from centcom docks then

**Comment by spookydonut** [comment]
Not the way to do this.

**Comment by Tharcoonvagh** [comment]
You know what frick this

**Pull request closed without merging**
