### PR TITLE
replaces flashlights in hacked assistvend thingy with flashlights in regular toolvend

### PR DESCRIPTION
**Pull request by anconfuzedrock**
:cl: rock
tweak: if we can have glowsticks in toolvends why not flashlights amirite guys
/:cl:

### CODE REVIEW

**Comment by Cheridan** [comment]
powercreep

**Comment by Cyberboss** [comment]
branchname

**Comment by lzimann** [comment]
title and commit name

**Comment by anconfuzedrock** [comment]
what they are fine

**Comment by PKPenguin321** [comment]
Leave them in the one they're already in but make it not require hacking duh

**Comment by Iamgoofball** [comment]
glowsticks are better

**Pull request merged**
