### PR TITLE
Updates outpost 45

### PR DESCRIPTION
**Pull request by Yobrocharlie**
## About The Pull Request

Adds xenomorphs a bit more environmental storytelling and loot to be had at outpost 45, this pr has far less to it than some of my other ones and is definitely far less ambitious but it gets the point across.
update45
update450

## Why It's Good For The Game

Outpost 45 is a heavily outdated gateway destination a destination that people look at see the purple and are instantly dis-interested in for they know it is just a waste of time- no more.

## Changelog

Added xenomorphs and rewards for killing xenomorphs to outpost 45.
all of the xenomorphs in the gateway are edited in strongdmm to not instantly die from the atmosphere.

:cl:
add: Added more things
/:cl:

### CODE REVIEW

**Comment by Yobrocharlie** [comment]
hmm seems like its too hot for the carbon xenos thats- interesting

**Comment by Yobrocharlie** [comment]
[08:47:23] Runtime in code/datums/elements/body_temp_sensitive.dm,86: The alien drone (567) loaded on in a loc with unsafe temperature at [74, 72, 10] (area : UO45 Caves): 363.9K. Acceptable Range: 250K - 350K,

thats odd i just updated it to where the max temp should be 365 not 350, and this is reflected in the code just not in the error log for some reason
oddruntime

**Comment by Yobrocharlie** [comment]
I updated the carbon mobs to where they shouldnt be taking damage anymore however for some reason they are.

**Comment by Yobrocharlie** [comment]
There are 515 active turfs at roundstart caused by a difference of the air between the adjacent turfs. To locate these active turfs, go into the "Debug" tab of your stat-panel. Then hit the verb that says "Mapping Verbs - Enable". Now, you can see all of the associated coordinates using "Mapping -> Show roundstart AT list" verb.

I checked in debug, nothing, im fairly certain that this is just due to the nature of outpost 45 being covered by plasma and i think this can be ignored. I have solved all other issues with this PR and the only runtime this PR causes is one caused by outpost 45 itself.

**Comment by SmArtKar** [comment]
Why are those carbon xenos anyways? I'm pretty sure that only simple/basic ones have AI, and carbons are purely for players.

**Comment by Pumpkinoe** [comment]
Yeah these should REALLY not be carbon xenos. Carbon xenos have absolutely no AI and will just stand there as they get slaughtered.

**Comment by Admiral-Gigaton** [comment]
> Yeah these should REALLY not be carbon xenos. Carbon xenos have absolutely no AI and will just stand there as they get slaughtered.

And can get sentience potion or brain transplant to start an artificial xeno storm by griefers and grantags

**Comment by DaCoolBoss** [comment]
> There are 515 active turfs at roundstart caused by a difference of the air between the adjacent turfs. To locate these active turfs, go into the "Debug" tab of your stat-panel. Then hit the verb that says "Mapping Verbs - Enable". Now, you can see all of the associated coordinates using "Mapping -> Show roundstart AT list" verb.
> 
> I checked in debug, nothing, im fairly certain that this is just due to the nature of outpost 45 being covered by plasma and i think this can be ignored. I have solved all other issues with this PR and the only runtime this PR causes is one caused by outpost 45 itself.

I spotted what's causing this. On turfs with "planetary_atmos = TRUE", ie your astroid floors, they will constantly attempt to return to their default gas values ("initial_gas_mix"). You have astroid floors where the initial_gas_mix is "co2=173.4;n2=135.1;plasma=229.8;TEMP=351.9", but you've changed the "temperature" value to 363.9 elsewhere. At round start, that temperaure is going to lower on those tiles until it reaches 351.9 degrees.

Simplest way to fix this is to delete all the temperature values you've changed, and move them to the initual_gas_mix. I'd reccomend taking the time to make a new define for your outpost 45 gas mix and put it on a new subtype of /turf/open/misc/asteroid

**Comment by Yobrocharlie** [comment]
> > There are 515 active turfs at roundstart caused by a difference of the air between the adjacent turfs. To locate these active turfs, go into the "Debug" tab of your stat-panel. Then hit the verb that says "Mapping Verbs - Enable". Now, you can see all of the associated coordinates using "Mapping -> Show roundstart AT list" verb.
> > I checked in debug, nothing, im fairly certain that this is just due to the nature of outpost 45 being covered by plasma and i think this can be ignored. I have solved all other issues with this PR and the only runtime this PR causes is one caused by outpost 45 itself.
> 
> I spotted what's causing this. On turfs with "planetary_atmos = TRUE", ie your astroid floors, they will constantly attempt to return to their default gas values ("initial_gas_mix"). You have astroid floors where the initial_gas_mix is "co2=173.4;n2=135.1;plasma=229.8;TEMP=351.9", but you've changed the "temperature" value to 363.9 elsewhere. At round start, that temperaure is going to lower on those tiles until it reaches 351.9 degrees.
> 
> Simplest way to fix this is to delete all the temperature values you've changed, and move them to the initial_gas_mix. I'd reccomend taking the time to make a new define for your outpost 45 gas mix and put it on a new subtype of /turf/open/misc/asteroid

I didnt actually change any of the temperature values only the temperature values of some of the xenos in the away mission to be slightly more heat resistant so they dont die. and those tiles with changed temperature were not a product of my doing.

**Comment by Yobrocharlie** [comment]
> Why are those carbon xenos anyways? I'm pretty sure that only simple/basic ones have AI, and carbons are purely for players.

no

**Comment by EOBGames** [comment]
Alright, you asked for a definitive answer, and I guess here it is- I just don't think this does anything to actually make the experience of Outpost 45 more interesting. It drops some loot in, sure, but that doesn't do much to meaningfully make the process of playing through more fun; only adds an incentive to slog through. I do apologise for the previous few PRs not getting much interest, but I think, looking over them to refresh myself, a large part of that is that they just weren't doing enough to make Outpost 45 worth actually doing as a player.

For anyone, including you, looking at revamping Outpost 45 in future, I'd suggest going to the fundamentals- the gateway as a whole is bad, and bandaid loot patchups and incremental alterations won't fix that: pretty much the entire thing needs gutted and redone with a modern touch and more eyes to creating an experience that's actually fun to play through.

**Comment by Yobrocharlie** [comment]
> Alright, you asked for a definitive answer, and I guess here it is- I just don't think this does anything to actually make the experience of Outpost 45 more interesting. It drops some loot in, sure, but that doesn't do much to meaningfully make the process of playing through more fun; only adds an incentive to slog through. I do apologise for the previous few PRs not getting much interest, but I think, looking over them to refresh myself, a large part of that is that they just weren't doing enough to make Outpost 45 worth actually doing as a player.
> 
> For anyone, including you, looking at revamping Outpost 45 in future, I'd suggest going to the fundamentals- the gateway as a whole is bad, and bandaid loot patchups and incremental alterations won't fix that: pretty much the entire thing needs gutted and redone with a modern touch and more eyes to creating an experience that's actually fun to play through.

i aint doing allthat

**Pull request closed without merging**
