### PR TITLE
[Ministation] Cleaned up all the remaining vents & scrubbers that use…

### PR DESCRIPTION
**Pull request by kyrahabattoir**
…d invalid icon states,
-rebuilt the engine pipework so that they use the right pipe types
-rebuilt toxins research burn chamber piping.

Before:
before
After:
after

### CODE REVIEW

**Comment by kyrahabattoir** [comment]
I realize that engineering has a lot of air alarms and vents running on the same frequencies, i will fix that later by making each air alarm manage it's own set of vents.

**Comment by pudl** [comment]
@kyrahabattoir mind if you let me update the map real quick, i just want to fix some area and firelock issues. thanks.

**Comment by kyrahabattoir** [comment]
@pudl sure, all yours!

**Comment by pudl** [comment]
want me to do the windows for you? @kyrahabattoor

**Comment by pudl** [comment]
whoops @kyrahabattoir

**Comment by kyrahabattoir** [comment]
I would wait for windows until https://github.com/tgstation/-tg-station/pull/9799 is merged to be honest, no sense in working too hard :)

**Pull request merged**
