### PR TITLE
Change the admin message for prays to only show the deity if it's a chaplain/cultist

### PR DESCRIPTION
**Pull request by lzimann**

### CODE REVIEW

**Comment by MimicFaux** [comment]
:+1:

**Comment by Niknakflak** [comment]
Why? I like this in all prays.  It doesnt even matter if its just extra info for other prays

**Comment by lzimann** [comment]
it is annoying as fuck seeing in all messages

**Comment by Incoming5643** [comment]
It might be a good idea for it to appear for everyone if the prays are made in the chapel. Since in that situation it might be roleplay.

**Pull request merged**
