### PR TITLE
Nerfs Reinforced windows.

### PR DESCRIPTION
**Pull request by itseasytosee**
## About The Pull Request
Its been three years since anyone has taken a swing at reinforced windows, so now its my turn to step up to the plate, and I'm hitting them hard. (Specifically approved by maintainers)
P@
p2

### THE CHANGES

Breaking:
80% Melee armor -> 20% Melee armor
11 Damage reflection -> 10 Damage Reflection (In practice, allows fire extinguishers, knives, and O2 tanks to be used effectively)
Health of 150 -> Unchanged!

Deconstructing
The welding step of deconstruction takes 33% less time
The wire cutter step is now instant (similar to r-walls)
Removed the crowbar step

Before:

https://user-images.githubusercontent.com/55666666/165217767-34c06470-c22d-414b-8724-81fd2cfca966.mp4

https://user-images.githubusercontent.com/55666666/165217965-3cceb2f5-a05a-45b1-916c-0069ed9339d4.mp4

After:

https://user-images.githubusercontent.com/55666666/165841178-0d3f9cf6-6197-4007-b983-f346dc891f21.mp4

https://user-images.githubusercontent.com/55666666/165841199-ab996113-8f9a-4540-bb91-4474c43072de.mp4

## Why It's Good For The Game
Reinforced windows as they stand right now are incredibly robust, and incredibly prevalent. They very much outclass other security structures that they are around.
For example, walls take about 14 seconds to deconstruct with a welding tool and a wrench. Windows take about 40 seconds, and require a full tool belt.
An r-window takes a whopping 25 hits with an every sword to destroy, an airlock takes 15 hits and can be hacked in around 20 seconds, less if you have knowledge of the area's wires.
If the wall's weakness is deconstructing, and the airlock's weakness is hacking, then the window's weakness should be blunt force trauma.
A design document which I used to outline these changes: https://hackmd.io/ukaoe8rFRvCta-4ISR-SSg?view

## Changelog

:cl: itseasytosee

balance: Reinforced windows have been made quicker to deconstruct and easier to break

/:cl:

### CODE REVIEW

**Comment by DrDiasyl** [comment]
I wanted to say "I like my reinforced windows - reinforced", but your points are very good. Other security is much weaker then some windows hah.

**Comment by CRITAWAKETS** [comment]
You forgot to nerf the absolutely insane stats of plasmaglass and plastitanium windows.

**Comment by Colovorat** [comment]
> You forgot to nerf the absolutely insane stats of plasmaglass and plastitanium windows.

 I think they should stay the way they are, maybe little nerf to plasma window, but at least they require effort to place, rwindows are just round start

**Comment by Pandarsenic** [comment]
Steps to deconstruct could stand to be a _tiny_ bit faster.

(I absolutely think lasering glass SHOULD be less efficient than smashing it, though, because literally _what the fuck_ how stupid is it to try to destroy a CLEAR thing with a LASER are you shitting me)

I would suggest plasma glass getting a little weaker so it's at least possible to smash with something that isn't a fireaxe (still stronger than current Ironglass windows, though) and plastitanium remaining the same since it is a combination of two miner-type substances.

What are the new "strikes to destroy" values, compared to the old ones?

Old, for reference, on a single-face window (half a full window's value)

> Toolbox (real)		32
> Circular Saw		25
> Surgical Drill		25
> Laser Scalpel		24
> Laser ScalSaw		23
> Spear (Wield)		21
> Spear (Throw)		18
> Insufficient Force	Scalpel, Oxygen Tanks, Fire Extinguisher, etc.

**Comment by Wallemations** [comment]
You mention the time it takes to deconstruct an R-window in relation to the time it takes to deconstruct a wall, but what about R-Walls? Aren't those the walls that these windows would normally be seen next to? I'm almost certain those take FOREVER to deconstruct.
Not opposed to the idea of this nerf, just want some clarification on how it relates to the other reinforced things.

**Comment by Fikou** [comment]
> You mention the time it takes to deconstruct an R-window in relation to the time it takes to deconstruct a wall, but what about R-Walls? Aren't those the walls that these windows would normally be seen next to? I'm almost certain those take FOREVER to deconstruct. 

have you ever played this video game
rwindows are everywhere, there is literally not a single instance of a regular window on deltastation. we slap them literally next to everything

**Comment by Palpetinus** [comment]
At first I was seething at the mere mention of getting my precious anti-tider windows nerfed, but the hackmd.io makes sense.
BUT
In that case, high security areas like secure tech storage (literally has a plasteel-reinforced high security door) or the armory (all the station's lethals) should maybe switch to plasmaglass instead of reinforced windows?
It'd be a bummer to have to roundstart reinforce half the station because the "stock" security is lacking.

**Comment by Pandarsenic** [comment]
> At first I was seething at the mere mention of getting my precious anti-tider windows nerfed, but the hackmd.io makes sense. BUT In that case, high security areas like secure tech storage (literally has a plasteel-reinforced high security door) or the armory (all the station's lethals) should maybe switch to plasmaglass instead of reinforced windows? It'd be a bummer to have to roundstart reinforce half the station because the "stock" security is lacking.

This seems like a thing to do in a month or two from a merge, once people have gotten over the novelty of Rwindows being breakable again.

**Comment by MacBlaze1** [comment]
> 

there has been talk in #coding-general about buffing normal windows and deescalating this madness. Id never thought I would see the day windows were made sane again. Maybe its a sign of the times that greytiders get the bullet.

**Comment by Shadowflame909** [comment]
Glad to see that I can break into departments without needing to powergame a whole tool belt again.

**Comment by YakumoChen** [comment]
I think the wirecutter shouldn't be instant, just because its easier to communicate the step was done with a loading bar. Make it at least like, half a second or something near-instant but long enough to see the bar.

**Comment by Snowyypanda** [comment]
some parts of the station have regular windows instead of reinforced ones, can you please change them to reinforced instead?

**Comment by optimumtact** [comment]
the fat controller laughed

"you are wrong"

**Comment by Shadowflame909** [comment]
> Is there any specific outcome in game you're seeing that makes this necessary?

Reinforced windows are really really easy to make with two of the most common materials in the game, yet are as strong as r-walls in terms of being a barrier to breaking and entering

That alone is pretty bad balance

**Comment by tralezab** [comment]
I think normal windows should get a little stronger and then get actually mapped in around so you can have your weaker windows that aren't so pathetic they're essentially two sneezes away from being an open turf

**Comment by Palpetinus** [comment]
> yet are as strong as r-walls in terms of being a barrier to breaking and entering

All you need for a reinforced window is:
Toolbox, time
Prisoners constantly break out of perma with stuff just lying around there

All you need for an r-wall is:
Wrench, wirecutters, crowbar, screwdriver, welder, about twice as much time if you don't know the steps by heart
(Or 50 thermite, but that's a new can of worms)

So no, they're far from being r-walls

**Comment by Ghilker** [comment]
>16 seconds to smash them
>36(33) to properly remove them
>no reason to deconstruct a window when breaking it is faster

image

**Comment by Shadowflame909** [comment]
I agree. It's not an impossible obstacle. Prisoners can make spears and bats with time and persistence. But that doesn't mean it still isn't a great obstacle far unworthy of it's durability and practice.

In a doomed station. I want to be able to pick up a toolbox or fire extinguisher from the ground near me and break open an r window to escape from doom, and have it not take several minutes to do so either. I shouldn't have to pre-emptively grab a whole tool belt in my backpack just to survive what will commonly become an obstacle in an average round.

I have the same issue with new firelocks requiring metagame too but I digress

**Comment by Palpetinus** [comment]
> I neglected to mention that the most fearsome fact of tough reinforced windows is they unlike r-walls. Their ease of creation let's them be spammed like no one else's business

Yes and no, depends on how you define "ease" here
To merely construct the tile, yes, r-windows are piss easy. 2 rods, 2 sheets of reinforced glass, around five seconds of fiddling
But then you have a loose window that can be pulled off and a grille. To properly secure it, you need a screwdriver and a crowbar, the crowbar step taking a long time to a total of around 20 seconds.
Compared to r-walls, which take 2 iron and 3 (?) plasteel, the material cost is low. But you can construct r-walls in around the same time, girder first and reinforcing twice. This then takes a tedious minute to deconstruct.

I don't think we will ever have a perfect balance here anyway. If you make them too weak, people might just switch to glass walls (girder+glass), at least those require a welder and are otherwise indestructable (besides hulks, explosions..)

**Comment by thgvr** [comment]
I regularly find myself using reinforced windows instead of walls because of how strong they are if you don't have a fireaxe.

**Comment by Mothblocks** [comment]
> I think normal windows should get a little stronger and then get actually mapped in around so you can have your weaker windows that aren't so pathetic they're essentially two sneezes away from being an open turf

this is the best fix, though it's a fair bit of work

mostly delta

**Comment by Pickle-Coding** [comment]
It's too easy to tide currently. It should be harder, not easier! Windows should get stronger so they take longer to break than to deconstruct. Maybe 60 seconds to break if you have a chainsaw or something.

Your why it's good for the game and design document never explained why making it even easier to break a window is good for the game. Blunt force trauma being a weakness should require high blunt trauma resistence still, as that actually destroys the structure and requires less tools.

**Comment by itseasytosee** [comment]
> the fat controller laughed
> 
> "you are wrong"
> 
> I have no faith in the admin team credibly addressing the situation that lead to this change and unless I see any concrete change in administrative policy I don't see a reason to merge this.
> 
> Is there any specific outcome in game you're seeing that makes this necessary?

Numbers are adjustable if you have any specific worries. The original nerf was overkill, so I am of the belief there should be some change if another solution is not implemented.

**Comment by Wallemations** [comment]
> > You mention the time it takes to deconstruct an R-window in relation to the time it takes to deconstruct a wall, but what about R-Walls? Aren't those the walls that these windows would normally be seen next to? I'm almost certain those take FOREVER to deconstruct. 
> 
> 
> 
> have you ever played this video game
> 
> rwindows are everywhere, there is literally not a single instance of a regular window on deltastation. we slap them literally next to everything
> 
> 

Y'know I hadn't thought about that.
In that case the real fix would seem to me to just be swapping out some reinforced windows with normals

**Comment by CPTANT** [comment]
The problem is that regular glass windows are too weak which means all the mappers put reinforced windows everywhere.

It should be really simple:

Areas with walls should have normal windows

Areas with reinforced walls should have reinforced windows

A normal window should be slightly weaker than a normal wall, the reinforced window slightly weaker than a reinforced wall.

**Comment by YakumoChen** [comment]
Buff full tile glass windows to like 100 HP or something with no armor so they're not made of paper

**Comment by itseasytosee** [comment]
> Buff full tile glass windows to like 100 HP or something with no armor so they're not made of paper

Current windows have 50 HP

**Comment by YakumoChen** [comment]
> > Buff full tile glass windows to like 100 HP or something with no armor so they're not made of paper
> 
> Current windows have 50 HP

9 hits with a toolbox plus grille is a bit more comparable to taking an iron wall down than 5

**Comment by TheBonded** [comment]
@Palpetinus you do realize you can create windows inhand by using the material inhand and dont need to make the grille first right? also its instant, i think, thought that might just be normal windows. you can run through maints and drop like 5 of these behind you to block whoever is chasing you

**Comment by itseasytosee** [comment]
> > you do realize you can create windows inhand by using the material inhand and dont need to make the grille first right? also its instant.
> 
> This pr will nerf the fortnite strat of spamming glass windows when there are nukies gunning you down.
> 
> Although probably not by much.

Surprisingly, not at all. The PR makes no changes to health, and r-windows take full damage from bullets, unlike melee hits.

**Comment by Mothblocks** [comment]
Lmao the fortnite strat

**Comment by Coastfront** [comment]
The only reason r-windows being as tanky as they are for how easy they are to make is an issue is because glass windows are so fucking bad that mappers never use them.
Nerfing R-windows, While it'll make the areas that SHOULDNT be hard to get into easier, it'll make the areas that SHOULD be hard to get into easier, which is bad.
If we replaced all the unnescary 5e+25 r-windows placed in every fucking instant of a window existing with normal windows that just have like double hp or some shit, then we wouldn't have the issue of "thing that is harder to get rid of than normal walls being literally everywhere"

**Comment by timothymtorres** [comment]
@san7890 how much work would it take to replace all the r-window spawners on a map with regular windows and then do touch-ups to add r-windows where needed?  StrongDMM has a replace feature that we could use to swap out all instances.  

I'm thinking any windows adjacent to space should probably be r-windows by default.

**Comment by CursedBirb** [comment]
Does this mean that sec will be able to fortify brig at 10 min mark due to the fact that breaking into sec now takes only 32s(two r-windows)?

**Comment by TheBonded** [comment]
> > Does this mean that sec will be able to fortify brig at 10 min mark due to the fact that breaking into sec now takes only 32s(two r-windows)?
> 
> Don't forget the electrified grille

yeah, 34 seconds, not 32

**Comment by CPTANT** [comment]
> @san7890 how much work would it take to replace all the r-window spawners on a map with regular windows and then do touch-ups to add r-windows where needed? StrongDMM has a replace feature that we could use to swap out all instances.
> 
> I'm thinking any windows adjacent to space should probably be r-windows by default.

I Disagree on defaulting to r-windows to space, arrivals/departures does not need the same protection from space as perma/AI sattelite or some other areas. I very highly suggest to stick to wall=window rwall=rwindow

**Comment by TheBonded** [comment]
> > @san7890 how much work would it take to replace all the r-window spawners on a map with regular windows and then do touch-ups to add r-windows where needed? StrongDMM has a replace feature that we could use to swap out all instances.
> > I'm thinking any windows adjacent to space should probably be r-windows by default.
> 
> I Disagree on defaulting to r-windows to space, arrivals/departures does not need the same protection from space as perma/AI sattelite or some other areas. I very highly suggest to stick to wall=window rwall=rwindow

having arrivals/departures fully syphoned because the detective missed a single revolver shot (or any other number of reasons for a normal window to be smashed, since they dont have any minimum amount of damage required to damage them) would suck. especially since these two places are almost always connected to the main halls, which would get partially depressurized and cooled down before the fire alarms went down. 

keep all public windows next to space reinforced, maint windows can all be normal.

**Comment by wesoda25** [comment]
> Does this mean that sec will be able to fortify brig at 10 min mark due to the fact that breaking into sec now takes only 32s(two r-windows)?

They couldn't before, so probably not.

I agree with oranges in that I really doubt admins will do much about this, I imagine most would just leave it IC unless there was a pattern of history or something.

**Comment by TheBonded** [comment]
@wesoda25 after this change it will take 16 seconds with an empty toolbox to smash a reinforced window

**Comment by itseasytosee** [comment]
If it is the common consensus, I would find it very reasonable to adjust the armor values further in order to make the breaking time closer to the deconstruction time.

**Comment by TheBonded** [comment]
> If it is the common consensus, I would find it very reasonable to adjust the armor values further in order to make the breaking time closer to the deconstruction time.

I think a FAR better solution would be to buff normal windows, maybe even buff normal windows to be the same as reinforced windows are now, and buff reinforced windows to be better than or on par with non reinforced plasma windows

**Comment by wesoda25** [comment]
Sounds excessive to me 🙁

**Comment by itseasytosee** [comment]
> > If it is the common consensus, I would find it very reasonable to adjust the armor values further in order to make the breaking time closer to the deconstruction time.
> 
> I think a FAR better solution would be to buff normal windows, maybe even buff normal windows to be the same as reinforced windows are now, and buff reinforced windows to be better than or on par with non reinforced plasma windows

Non reinforced plasma windows suck. They are only slightly better than normal glass If I remember correctly.

**Comment by itseasytosee** [comment]
Updated armor values and the videos! Deconstruction and destroying with a toolbox are now about 30 seconds, which lines up with my design doc.

**Comment by optimumtact** [comment]
I do not approve a nerf to reinforced windows, I approve a buff of other security related structures, but I am happy that deconstruction on reinforced items by force takes much longer than deconstruction with tools.

**Comment by itseasytosee** [comment]
NOOOOOO

**Pull request closed without merging**
