### PR TITLE
[WIP] Replaces HoS's laser gun with an energy-revolver

### PR DESCRIPTION
**Pull request by vuonojenmustaturska**
## About The Pull Request

Very much work in progress just to outline this idea:
1. replace hos gun with the revolver
2. replace ion rifle and temperature gun with the rifle variant
3. they both use the same ammo, the hos gun is just cooler

## Why It's Good For The Game

Porting these to use ammo instead allows increasing the palette of possible effects without adding more guns with infinite ammo into the armory that shoot a projectile that only works against magic blobs during an eclipse. Also revolvers are much cooler than dewilt laser guns you put into a charger.

No changelog because this is extremely wip

horrible codersprites below: 
rifle
hosgun

### CODE REVIEW

**Comment by SgtxRootbeer** [comment]
Are we seriously nerfing the tempgun

(Someone actually check if this is a Nerf... I haven't read the code)

**Comment by Shapsy** [comment]
But then can't the HoS just carry around 10 speedloaders and not have to worry about ammo? Wouldn't this prevent him from switching between lethal/non-lethal on a single gun, making it less generally useful?

**Comment by Akrilla** [comment]
I thought a huge point of the HoS gun was to be highly versatile/effective vs the traditional weapons in the armoury. Ammo in itself is incredibly clunky to manage, and just slows the whole process down. It shouldn’t be that I feel like just grabbing and energy gun over the weapon I start with.

**Comment by Repukan** [comment]
Replace it with a normal revolver

**Comment by habader** [comment]
give hos pulse rifle with only destroy mode

**Comment by necromanceranne** [comment]
If we just wanna give the HoS the BIGGEST GUN at least don't make it a six-shooter flashlight. If you pull that gun out it should be to smoke someone.

**Comment by Tlaltecuhtli** [comment]
why not the lawgiver at this point

**Comment by Shadowflame909** [comment]
Give the HoS a one bullet Pulse Rifle.

Instant 50 damage

**Comment by FantasticFwoosh** [comment]
Its a meme but we could have just presented the HOS with a reimbursable coupon ticket to just buy a gun of their choice from his head console. I don't like removing the HOS energy gun but i also like variety, thats my two cents anyway.

I guess it all checks out, but shouldn't that ammo be at least producible from RnD research to print more of at sec deptlathe if its special enough to use? Seems like a soft nerf on availibility even if its pretty powerful.

**Comment by SpaceManiac** [comment]
Closing as Stale for being Work In Progress for over a week with no updates. If you want to continue work, reply here or ~~ping~~ be a maintainer.

**Pull request closed without merging**
