### PR TITLE
Rebalances thermals

### PR DESCRIPTION
**Pull request by ghost**
"fixes" https://github.com/tgstation/-tg-station/issues/8041

Normal thermals no longer have a negative flash protection that will give you eye damage if you get flashed or flashbanged or emp'd while wearing them

Syndicate thermals, however, still do. The ones disguised as mesons for the uplink.

### CODE REVIEW

**Comment by Xhuis** [comment]
:+1:

**Comment by optimumtact** [comment]
Does this allow for severe antag meta by flashing people and checking eye damage?

**Comment by dannno** [comment]
no

**Comment by optimumtact** [comment]
:+1: then

**Comment by dannno** [comment]
really sometimes you shock me with these questions oranges

**Comment by Fox-McCloud** [comment]
I'd go a step further; give the thermals flash protection; also I believe these are still impacted by EMP; might want to have a check for flash protect first, for them.

**Comment by optimumtact** [comment]
It's just a thought I had

**Comment by Dorsisdwarf** [comment]
May affect #6669

**Pull request merged**
