### PR TITLE
Removes revenants breaking windows

### PR DESCRIPTION
**Pull request by JohnFulpWillard**
## About The Pull Request

Replaces Revenant's ability to break windows with the ability to just damage them until 50 (or lower) integrity left.

## Why It's Good For The Game

They are a low-weight antagonist meant to terrorize the crew to suck their souls, but end up ending the round in every single round there's a revenant, because they can near-immediately get the window-breaking spell then fuck off to space and space the station from the outside where no one can hit them.

This ability isn't fun for anyone but the revenant, it doesn't advance the round forward in any meaningful way, just ending it over an antagonist that can be literally anywhere it wants to with wall-phasing crap.

With Blob, you at the very least know where the Blob is, it's announced, ect. Sentient diseases can be countered by Medbay, and has to build up. Revenants are spared this, and get basically a 'end round now' button just by sucking 1-2 bodies, a quick visit to the morgue for a non-antag prepped Medbay.

## Changelog

:cl:
balance: Revenants' defile ability no longer breaks windows, only damaging it until nearly broken. The damage dealt to windows has also been slightly lowered.
/:cl:

### CODE REVIEW

**Comment by tralezab** [comment]
ideally there would be some kind of replacement since breaking windows has been aa somewhat sizable part of what revenant does, that being a good thing or not

**Comment by cacogen** [comment]
just make it do less damage imo

**Comment by JohnFulpWillard** [comment]
> ideally there would be some kind of replacement since breaking windows has been aa somewhat sizable part of what revenant does, that being a good thing or not

The main focus of revenants were to drain essence from weak/dead crew to suck their bodies out. It only because a 'sizable' part of what revenants do because its overpowered and immediately ends the round, so gets abused every time.

**Comment by Y0SH1M4S73R** [comment]
I mean it definitely is shitty for revs to just space the station because they can, but the aesthetics of the defile ability damaging/breaking windows make sense. Perhaps revs could be unable to break windows separating safe atmospheres from dangerous ones.

**Comment by moocowswag** [comment]
Make it so the revenant has to be in a turf with gasses/pressure to damage windows?

So, revenant appears -> corrupts the area around it and the spooky air thrashes against the windows -> people run in and beat him up.

**Comment by MrMelbert** [comment]
In the Revenant rework I have finished* but not PR'd I kept window damaging but made it so they could never fully break a window, just crack it (can't damage past 50% health or such).

**Comment by JohnFulpWillard** [comment]
reopening because I still find this to be a problem and the revenant rework doesn't seem to be close

**Comment by cacogen** [comment]
fastmos was a mistake

**Comment by Shadowflame909** [comment]
cant believe a grief ghost just got its ability to grief nerfed...like putting a CD on the clowns ability to honk

**Pull request merged**
