### PR TITLE
Meh this branch is broken and I can't be assed to fix it, rip, goofball stop getting actual good changes ruined by spamming.

### PR DESCRIPTION
**Pull request by silicons**
I saw that the previous PR was closed even with upvotes, because, well, goofball was being a child and spamming shit, so I'm just going to remake this and hope that people haven't changed their minds.

Previous PR : https://github.com/tgstation/tgstation/pull/25391

### CODE REVIEW

**Comment by PKPenguin321** [comment]
👎 still no reasoning

**Comment by ChangelingRain** [comment]
If you want it to be less of a nerf, you could do a self-progressbar to show long much longer you have until it goes away.

**Comment by GunHog** [comment]
I disagree with the PR regardless of who makes it.

**Comment by kevinz000** [comment]
Hey I'm just reopening it because it had potential and I liked it, but goofball had to be a big baby and ruin it by spamming OOC when he didn't understand what someone meant.

**Comment by kevinz000** [comment]
why the hell doesn't this compile hmm

**Pull request closed without merging**
