### PR TITLE
Drunk people no longer feel cold

### PR DESCRIPTION
**Pull request by JohnFulpWillard**
## About The Pull Request

Simple PR, if you're drunk then you no longer feel the effects (or get the warnings) of cold temperatures.
This makes things like cryosting and the coldness of space give you no warning or tell of why you're being hurt, but it also means you don't suffer its slowdown.

## Why It's Good For The Game

It's a small bit of realism that doesn't do much to change the game, but gives some extra bonus/drawback to alcohol that isn't really changing the game by any means.

## Changelog

:cl: JohnFulpWillard, Atlasle
balance: You no longer feel cold if you're drunk. You still take damage, but get no warning or slowdown.
/:cl:

### CODE REVIEW

**Comment by Paxilmaniac** [comment]
Now all we need is an interaction with being drunk and having car keys in your pocket

**Comment by SomeoneYouProbablyKnow** [comment]
> Now all we need is an interaction with being drunk and having car keys in your pocket

The drunk driving update. Add the collision thing from skateboards to whatever you are driving drunk be it a janicart a secway or a horse.

**Comment by Striders13** [comment]
apparently the anti freeze cocktail does this already, can you replace it with some other  effect?

**Comment by jughu** [comment]
> apparently the anti freeze cocktail does this already, can you replace it with some other effect?

Anti freeze heats you up like coffee does as the name says anti freeze your not freezing

what the pr does is more a miner salve effect where you cant really tell if ur being hurt, except only for cold here

**Pull request merged**
