### PR TITLE
Changes book code slightly

### PR DESCRIPTION
**Pull request by LemonInTheDark**
## About The Pull Request
Caps the length of books to the length of paper

## Why It's Good For The Game

My gut told me we should do this

### CODE REVIEW

**Comment by TemporalOroboros** [comment]
From a practicality standpoint this is probably for the best. From a logic standpoint I'm sort of irritated that all books are apparently pamphlets.

**Comment by LemonInTheDark** [comment]
It might be worth changing someday when you can put more then one bit of paper in a book, but for now it'll do

**Comment by RaveRadbury** [comment]
We've had people do whole stories via multiple entries into a book, is this going to prevent that? It will be sad to see it go.

**Comment by LemonInTheDark** [comment]
Honestly I'm not sure how I feel about that. On one hand long stories are good, on the other they could in theory split the book up into volumes.

That said, 5k characters might be too short, and maybe we should double that.

**Comment by OmegaDarkPotato** [comment]
Speaking as someone who just dropped a 13k character story into the archives (9993) (read it) I'm also here to petition the min length being changed. Is 20k that absurd, even if most stories never hit it?

Or maybe even 8x the length of paper at 40k...

**Comment by RaveRadbury** [comment]
40k might be good tbh, I was talking to Lemon about it yesterday, I think they might look at some more library book entries to find a good limit.

**Comment by LemonInTheDark** [comment]
Hold this thought, I've got a better idea

**Pull request closed without merging**
