### PR TITLE
New shuttle chair sprites by Ausops

### PR DESCRIPTION
**Pull request by zaracka**
shuttle chair

:cl: Ausops
imageadd: New shuttle chair sprites.
/:cl:

Completes #38732. Made shuttle chairs a child of comfy chairs again (`/obj/structure/chair/comfy/shuttle`) by reverting a few PR's as per Cyberboss's request. The "armrest" covers the player similar to comfy chairs when sitting in them. Made sure not to revert the goon directory chairs.dmi which means the current sprite is still in the code. Sprites by Ausops.

### CODE REVIEW

**Comment by ExcessiveUseOfCobblestone** [comment]
beside `:cl:` put Ausops

**Comment by epochayur** [comment]
can we please just merge one of these bastards already

**Comment by XDTM** [comment]
The repeating cycle of someone trying to resprite stuff with a controversial new sprite until ausops comes in with an extremely high quality sprite that settles all discussion

**Comment by alexkar598** [comment]
Is this new brain damage lines?????

**Comment by praisenarsie** [comment]
i feel like there's a bit too much depth on the back on the chair

**Comment by DaxDupont** [comment]
Perfect!

**Review by SpaceManiac — CHANGES_REQUESTED** [review]
I take it `goon/icons/obj/chairs.dmi` is now unused? If so, delete it.

**Comment by zaracka** [comment]
Done.

**Comment by Memager** [comment]
thanks

**Pull request merged**
