### PR TITLE
Colossuses hate sleeping carp

### PR DESCRIPTION
**Pull request by ChangelingRain**
Like #19699 but not "accidentally" merged then reverted by oranges.

It will chase you down at high speed and murder your ass for daring to try and cheese it.

### CODE REVIEW

**Comment by Durkel** [comment]
Learn this one neat trick to kill megafauna, colossi hate him!

**Comment by KorPhaeron** [comment]
Apparently this has become a big deal on basil, to the point where one guy got 2 of them on the station in the same round

**Comment by KorPhaeron** [comment]
but adding a check every time it gets a target just seems so wrong and snowflake

**Comment by ChangelingRain** [comment]
I'd make it a more generic proc for if they're immune to projectiles but carp is the only thing that is, soooooooooooo

**Comment by Xhuis** [comment]
Maybe make actual space carp piss them off too, for fluff/hilarity.

**Comment by Davdichan** [comment]
@Xhuis oh god, lavacarp. Get tossed in Gulag, mind your own business between storms, suddenly a massive red text in the chat box.

>THE CARP STANDS UP

And half a dozen lava proof carp rush you from the lava.

**Comment by ChangelingRain** [comment]
I may or may not have been tempted to add dead(ie, sleeping) carp to the list of stuff that'd enrage a colossus.

**Comment by Repukan** [comment]
oh god nice

**Pull request merged**
