### PR TITLE
picked up bees and mice can now fit in boxes.

### LINKED ISSUE #53515: bees are too large to fit inside of boxes
they're BEES

how are they larger than a BOX

### PR DESCRIPTION
**Pull request by Ghommie**
## About The Pull Request
Title. They are tiny.

## Why It's Good For The Game
This will fix #53515.

## Changelog
:cl:
expansion: Picked up bees and mice can now fit in boxes.
/:cl:

### CODE REVIEW

**Comment by Y0SH1M4S73R** [comment]
I would have gone about this in a different way. Instead of setting the weight of the holder object in `bee/mob_pickup()`, I'd have given a var named `held_w_class` to `/mob/living`, and have `mob_holder/Initialize()` set the weight class to the `held_w_class` of the mob it contains. Just my $0.02.

**Comment by Fikou** [comment]
you could have a global assoc list of mob sizes to item sizes

**Comment by TemporalOroboros** [comment]
Better. Rename `w_class` to `size` and move it to `/atom/movable`. That way you can unify `w_class` and `mob_size`.

**Review by Mothblocks — CHANGES_REQUESTED** [review]
> I would have gone about this in a different way. Instead of setting the weight of the holder object in bee/mob_pickup(), I'd have given a var named held_w_class to /mob/living, and have mob_holder/Initialize() set the weight class to the held_w_class of the mob it contains. Just my $0.02.

I agree with this. This should probably be the behavior for mice as well, for instance.

**Comment by Learner10** [comment]
The mime uses invisible box full of bees! It's quite effective!

**Comment by Ghommie** [comment]
Sorry for being late on this one.

**Pull request merged**
