### PR TITLE
[MDB IGNORE] Removes ballast from thermomachines

### LINKED ISSUE #66440: Advertised thermomachine layer change with multitool doesn't work
Reporting client version: 514.1583

## Round ID:
[182004](https://scrubby.melonmesa.com/round/182004)

## Testmerges:
- [Hud Image Culling By Z Level: Theft edition](https://www.github.com/tgstation/tgstation/pull/65189)
- [Optimizes Runechat](https://www.github.com/tgstation/tgstation/pull/65791)
- [Makes it possible to speed up the tram](https://www.github.com/tgstation/tgstation/pull/66348)

## Reproduction:

Spawn a thermomachine.  Examine its descriptive text.

_With the panel open:
-use a multitool with left-click to change the piping layer and right-click to change the piping color._

Screwdriver the thermomachine, and try use the multitool on it (combat mode off)

_You open the maintenance hatch of the omni Temperature control unit.
You put the hand drill into the toolbelt.
You hit the omni Temperature control unit with the multitool._

The right click (change pipe colour) works, and as a work around you can crowbar the thermomachine and use a multitool on the circuit board to change the layer, however, it does not function as described on the thermomachine.

### PR DESCRIPTION
**Pull request by LemonInTheDark**
## About The Pull Request

Removes ballast from thermomachines. That means anything to do with moving heat rather then creating it or destroying it.

I don't think ballast is something that's useful to keep around, since it functions to make cooling things harder for what amounts to no real reason.

We still have space as an infinite source of cold, it's pointless to gate it.

I'm removing all uses of two ports, cooling, efficency, work skipping, waste heat, and safeties.
This means dropping quite a lot of behavior.

There's no emag effect currently for instance, because it renabled some previously buggy behavior that was caused by ballast, which I'm nuking.

Also doing away with metal h2 upgrades to the thing, because even though I like the idea, it has no purpose as of now.

Removing ballast has made a lot of the logic and checks that were done in process_atmos pointless, so they can go too.
I'm keeping the barebones behavior of how power consumption works, because I like it.

Efficency is going because it was almost always like 80% without ballast, and I didn't think it was something worth having.
Cooling as a concept can go interestingly enough, because there's no difference between heating and cooling, just the temperature we're targeting.

I've also restored heat capacity to its old value, since the current one was bumped up a bit to compensate for other aspects of the machine that limit heating speed.

I think that's about it? I'm also removing failure states, because they too were linked to ballast
Cleaned up the examine a bit, and removed some redundant code 

Oh, and I'm removing the redundant icon states and gags entries, since well, they aren't used anymore. 
Also removed some from the js file

Fixes https://github.com/tgstation/tgstation/issues/66440
Someone forgot to remove the old multitool act proc. Broke behavior. I've fixed it

## Why It's Good For The Game

I was a bit worried about this feature initially, but let it be because it wasn't causing any harm.
Ghil has been unable to go in the direction he wanted to with heat management, because it unlike this change was something I am not down with.

Because of that, thermomachines have been in this kinda annoying state, where they're easy to use in some ways, but have a lot of extra stuff you need to manage.
Because we're finally starting to work on making atmos more accessible, it needs to go.

Oh and btw, I've split my work into a few different commits, so you can look at what I removed separate from the repath. FYI.

If you're just here to mald about ballast, piss off. I am not interested in playing host to you.

## Changelog

:cl:
del: Removed the concept of ballast from thermomachines, you no longer need some gas to heat in order to cool things.
/:cl:

### CODE REVIEW

**Comment by timothymtorres** [comment]
This requires some mapping to fix right?  Atmos, SM, Kitchen, maybe even telecomms.

**Comment by LemonInTheDark** [comment]
> This requires some mapping to fix right? Atmos, SM, Kitchen, maybe even telecomms.

Tim you should check my changed files more closely

**Comment by Colovorat** [comment]
Good riddance

**Comment by Cheshify** [comment]
As hard as I know this probably is, this is absolutely required. Atmos is in a state wherein a lot of the mechanics are very cool and interesting, but so mind-numbingly difficult for new players to grasp, and also allow for some game-breaking bugs.

Thermomachines transferring heat while a good concept, all it does is give atmos techs a chore, make toxins & cryo less accessible to non-atmos mains, and set the temperature of waste to around 100,000K every shift if a hyper competent atmos tech isn't on-board to spend 20 minutes of their shift setting up an overly complex cooling system that genuinely accomplishes nothing.

Good PR

**Review by san7890 — CHANGES_REQUESTED** [review]
This stuff was pretty annoying for mappers to have to deal with, so it's nice to see it go away. Did a quick pass for map stuff, two very minor requests.

<details>
<summary>Images within</summary>

image

On DeltaStation, could you please get rid of this delivery decal here? It's a remnant from when you removed the canister port, and it makes no sense to have the decal otherwise.

image

On IceBoxStation, I know for a fact that this isn't your fault, but while you're shuffling stuff around would you mind moving this fire extinguisher to face west on the wall (at the point of my arrow)? Will save a pass on this sort of stuff later on since it's cramped right now. 
</details>

Thank you!

**Comment by LemonInTheDark** [comment]
Yeet brother

**Comment by Ghilker** [comment]
https://user-images.githubusercontent.com/42839747/164623422-e79a323d-db48-4add-9e82-8dce4ea5ef83.mp4

**Comment by SnoopCooper** [comment]
Sad to see, genuinely liked TMs moving heat around. You could do a couple of clever things with it. Felt fun to play with too, with the exception of hot waste. Though when I’ve played that hardly matter/takes two minutes to fix.

**Comment by SnoopCooper** [comment]
Also, this kinda leaves an empty space in the atmos toolbox for a heat pump component. The TM had the advantage of being able to move heat energy from cold to hot like an IRL heat pump. The ingame heat pumps can't do that. This will make getting heat without using the HFR a lot harder.

**Comment by cacogen** [comment]
>Also doing away with metal h2, because even though I like the idea, it has no purpose as of now.

can't you make like a fireaxe out of this or smtg

**Comment by Zytolg** [comment]
Moving heat was neat, but I agree on the point of this being frustrating to map. @LemonInTheDark most Heaters connect up to the scrubbers network so it should be quite easy to remove. Worry about the main stations and I'll put the bullet in the ruins/centcom/shuttles once all is done.

**Comment by Mothblocks** [comment]
> Also doing away with metal h2, because even though I like the idea, it has no purpose as of now.

Is that in this pull request? It's not in the changelog.

**Comment by Ghilker** [comment]
> > Also doing away with metal h2, because even though I like the idea, it has no purpose as of now.
> 
> Is that in this pull request? It's not in the changelog.

He should word that better because it seems that he's removing the metal H2 as a whole, but is only the upgrade for the thermomachine that he's removing since that did the exact same thing he's reverting now

**Comment by LemonInTheDark** [comment]
> Moving heat was neat, but I agree on the point of this being frustrating to map. @LemonInTheDark most Heaters connect up to the scrubbers network so it should be quite easy to remove. Worry about the main stations and I'll put the bullet in the ruins/centcom/shuttles once all is done.

I don't take half measures, it's all done already

> > > Also doing away with metal h2, because even though I like the idea, it has no purpose as of now.
> > 
> > 
> > Is that in this pull request? It's not in the changelog.
> 
> He should word that better because it seems that he's removing the metal H2 as a whole, but is only the upgrade for the thermomachine that he's removing since that did the exact same thing he's reverting now

lu ghil

> Sad to see, genuinely liked TMs moving heat around. You could do a couple of clever things with it. Felt fun to play with too, with the exception of hot waste. Though when I’ve played that hardly matter/takes two minutes to fix.

Yeah. yeah.
I realize it makes generating heat a bit more tricky, but that's something I'm at base ok with, since it's not like it locks anything off.

**Pull request merged**
