### PR TITLE
Don't use turf icons for abilities

### LINKED ISSUE #100: Weird uses of sprites
There are a few bits of the code that use like, signs and walls as... action button sprites? or item sprites? it's fucking deranged.
Please make actual sprites for these, it should be pr'd upstream, but with 3/4ths these will look horrible untouched

See wallening todo:

### PR DESCRIPTION
**Pull request by Jacquerel**
## About The Pull Request

Fixes https://github.com/wall-nerds/wallening/issues/100
Replaces a couple of instances of abilities using the icons of walls or floors with different, somewhat more descriptive icons.

I will be honest I do not understand why two of these were even using iron walls as an icon.
Both of these instances were cases of "I want to surround something" so I have replaced them with this icon:
image

I have also replaced the "freeze floors" ability icon with the ice cube icon, rather than a 32x32 ice floor icon.
image

I removed a bunch of old copies of goggles items from the `robot-items` dmi and made them just reference the corresponding item sprites that they were copies of, because they were out of date with the items and using deprecated sprites. X-Ray now just looks like the red sam fisher goggles instead of a caution sign (not that it is obtainable in game).

Oh also I added a tooltip to Ice Demon afterimages because it didn't have one.

## Why It's Good For The Game

The previous icons don't even look like anything.

## Changelog

:cl:
image: Bubblegum Hallucination Surround Charge, Wendigo Shockwave Scream, and Ice Demon Floor Freeze all have more appropriate action icons.
qol: Adds a tooltip to Ice Demon Afterimages ability.
image: Cyborg view items now use the same sprites as their corresponding goggles instead of old versions of those sprites.
/:cl:

### CODE REVIEW

**Comment by MrMelbert** [comment]
```dm
/datum/unit_test/ability_icons()
    for(var/datum/action/action_type as anything in typesof(/datum/action))
        if(findtext(action_type.button_icon, "/turf")
            TEST_FAIL("Turf icon being used for an action!")
```
(A joke, for legal reasons)

**Comment by LemonInTheDark** [comment]
I love you

**Comment by LemonInTheDark** [comment]
Also there's I think some stuff unaddressed here, iirc there's some usage of the warning sign sprite

**Comment by Jacquerel** [comment]
Aha I looked for use of signs.dmi in _ability_ code only and didn't find it, I will get that one too

**Pull request merged**
