### PR TITLE
Headcrab Infection Fix

### PR DESCRIPTION
**Pull request by Comxy**
## About The Pull Request
There are headcrab corpses on the new meateor ruin. However, apparently you cannot infect corpses with them once you take the steps to get one all the way back to the station. This makes it so that you can infect corpses again with those headcrabs.
## Why It's Good For The Game
I think it is balanced since headcrab lings are already a nerfed version of changelings, and there are a lot of steps to take to transform yourself into a headcrab ling. You need to get rainbow slimes, lazurus injector by mining, and you need to find the meateor ruin to fetch a dead headcrab. I did this myself and was left there has a mere slug until I started praying.
## Changelog
:cl:
balance: Headcrab corpses can infect humans again.
fix: All headcrab corpses are now able to infect humans again.
/:cl:

### CODE REVIEW

**Comment by Jacquerel** [comment]
This was intentional.

**Comment by Comxy** [comment]
Then why put headslug corpses in your ruin. Didn't you think people wouldn't get baited, only to get themselves stuck in a useless mob.

**Comment by Jacquerel** [comment]
To make it clear that changelings were there at some point.
If you want to reopen this, get prior approval from a different maintainer first.

**Comment by Comxy** [comment]
I don't see how that will help since I doubt many people will read the description but whatever, that is that then I guess.

**Pull request closed without merging**
