### PR TITLE
Holy water no longer adds confusion

### PR DESCRIPTION
**Pull request by lzimann**
:cl: Lzimann
tweak: Holy water no longers makes you confused.
/:cl:

### CODE REVIEW

**Comment by Iamgoofball** [comment]
time to forcefeed this to everyone roundstart

**Comment by MMMiracles** [comment]
@Iamgoofball security already does this and has been doing this whenever the concept of 'cult' even thinks of appearing on-station. All this does is make that stun+cuff+drunk more tolerable for those on the receiving end.

**Comment by Kromgar** [comment]
Everyone already gets forcefed the shit when cult round happens so how about we make it tolerable?

**Comment by Robustin** [comment]
Common sense change

**Comment by optimumtact** [comment]
Well if it's what the people want

**Pull request merged**
