### PR TITLE
Gives Nar-Sie a new summon sound

### PR DESCRIPTION
**Pull request by ghost**
:cl: PopNotes
soundadd: Nar-Sie now sounds like an eldritch abomination that obliterates worlds instead of a sweet maiden that gently whispers sweet nothings in your ear.
/:cl:

# All credit for the sound goes to @PopNotes from [HippieStation](https://github.com/HippieStation/HippieStation/pull/2364). I take no credit for it.

[Here's ](http://puu.sh/wHm7V/92992edbcd.wav)what it sounds like.
I asked in Coderbus if this violated the freeze, and was told that it didn't. Please tell me if it does.

### CODE REVIEW

**Comment by WJohn** [comment]
much better than "I'm here"

**Comment by Xhuis** [comment]
That makes me think of something.
When Nar-Sie goes to a bar, what does she say?
"I'm beer"

**Comment by Repukan** [comment]
Just stick to coding

**Comment by Xhuis** [comment]
If the fact that this is a pull request is any indication, I am, in fact, coding.

**Comment by GunHog** [comment]
It sounds like something I would hear right before a boss in Dead Space. So, bravo!

**Comment by PopNotes** [comment]
I did not give you permission to use this.

We're going to have serious trouble.

**Comment by PopNotes** [comment]
lmao nah I made you think for a sec tho

**Comment by DoctoreMad** [comment]
@PopNotes False copyright claims are a crime

**Comment by PopNotes** [comment]
and your grease-coated visage is a crime against reality

**Comment by InsaneHyena** [comment]
The current one is better. Stick to clock cult.

**Comment by Xhuis** [comment]
Is whining all you ever do right?

**Comment by PopNotes** [comment]
insanehyena's most recent post is a prime argument against incestuous procreation

**Comment by DoctoreMad** [comment]
>that means your parents were related

Yeah
They're husband and wife

**Comment by PopNotes** [comment]
exactly
they were related before the marriage too

**Comment by Ausops** [comment]
>narsie not a sweet maiden whispering sweet nothings into your ear
>sweet maidens whispering sweet nothings into your ear not the best sort of eldritch abomination
>xhuis of ((((ratvar)))))) fame in charge of changing narsie lore

**Comment by Xhuis** [comment]
I would be tempted to agree _but_ Nar-Sie doesn't strike me as that kind of eldritch abomination.

**Comment by optimumtact** [comment]
it looks exactly like a giant floating burnt vagina

**Comment by PopNotes** [comment]
> it looks exactly like a giant floating burnt vagina

the black waffle

**Review by Cyberboss — APPROVED** [review]

**Pull request merged**
