### PR TITLE
Quantum Pads

### PR DESCRIPTION
**Pull request by XDTM**
:cl: XDTM
add: Quantum Pads are now buildable in R&D!
add: Quantum Pads, once built, can be linked to other Quantum Pads using a multitool. Using a Pad who has been linked will teleport everything on the sending pad to the linked pad!
add: Pads do not need to be linked in pairs: Pad A can lead to Pad B which can lead to pad C.
add: Upgrading a Quantum Pad will reduce the cooldown, charge-up time, and power consumption.
add: Quantum Pads require a bluespace crystal, a micro manipulator, a capacitor and a cable piece.
/:cl:

Quantum Pad Sprite (aka shitty recolor of a telepad):
qpad
qpad

### CODE REVIEW

**Comment by kevinz000** [comment]
TELEPORTER GOIN' UP!!

**Comment by kevinz000** [comment]
Wait, so if you click on it you get teleported, not the one or ones on the pad? Wew :)

**Comment by XDTM** [comment]
check again, it teleports all the stuff on the pad ya silly

**Comment by MimicFaux** [comment]
New traitor meta. Conveyorbelt pointed into lava + quantum pad

**Comment by XDTM** [comment]
You can make a one-way quantum pad to perma now :^)

**Comment by FantasticFwoosh** [comment]
Adding a function to multi-tool the co-ords to a regular teleporter rig (so you can choose what quantum pad you wish to get to) would also be neat.

So right now we have

> Teleporter to teleporter & beacon static but teleports things put through to other units & abstract 'marker' places

> Regular telepads that work like quantum pads (teleporting everything on the tile) but can shoot outwards at new co-ordinates and retrieve items without a pad, collect miners off lavaland etc with a bit of applicative math (which is a bit hard for a novice to do)

> Now this linked telepad hybrid that quite neatly just creates what you could refer to a 'wormhole' link between two places.

**Comment by Chnkr** [comment]
Please ensure you cannot put these on the cargo shuttle.

**Comment by XDTM** [comment]
i think cargo shuttles delete everything that's inside of them after travelling

**Comment by KorPhaeron** [comment]
Telefragging when

**Comment by ShadowDeath6** [comment]
a human teleporting onto another human should do clone damage to both of them tbh

**Comment by ExcessiveUseOfCobblestone** [comment]
> tcomms device
>> reskinned into telepad
>>> reskinned into Quantum Pad
>>>> what will be next?

**Comment by ExcessiveUseOfCobblestone** [comment]
@XDTM add a check for z=2 or whatever the transit zlevel is because hugbox.

**Comment by Armhulen** [comment]
> a human teleporting onto another human should do clone damage to both of them tbh

just give them the changeling horror form skin simplemob and they both control it

**Comment by XDTM** [comment]
@ExcessiveUseOfCobblestone quantum pads are already banned from the cargo shuttle, don't worry

**Comment by TehZombehz** [comment]
The path is open.

**Comment by AdamElTablawy** [comment]
so basically teleport runes for R&D then since they both have the exact same effects

not a bad idea tbqh

**Comment by XDTM** [comment]
Just in case you feel they could be op, they have a chargeup time of 3 seconds, 30 seconds cooldown and need to be manually linked to choose a destination.

**Comment by SgtxRootbeer** [comment]
Wait, why don't you add a quantum pad control computer that allows you to choose which pad you wish to go to instead?
(If it is linked it would bring up a GUI similar to the teleport rune)
You can make it a machine instead of a console and put in parts requirements, like only 5 pads for a t1 scanner.

**Comment by XDTM** [comment]
Three reasons: it would make it more complicated to build and use, it would do the exact same thing a teleporter can do right now, and i haven't the slightest clue on how to code Topic or consoles in general properly.

**Comment by ExcessiveUseOfCobblestone** [comment]
what happens with max tier parts

**Comment by ShadowDeath6** [comment]
maxed parts should teleport the entire room to the other telepad

**Comment by XDTM** [comment]
max tier parts reduce the channel to 1 second and cooldown to 10 seconds, and it uses 1/4 of the base power on teleport

**Comment by XDTM** [comment]
no wait, on max parts channel is 1 seconds, but there's no cooldown

**Comment by JJRcop** [comment]
superposition of bleeding and not bleeding

**Pull request merged**
