### PR TITLE
More Food Sorting

### PR DESCRIPTION
**Pull request by Owai-Seek**
## About The Pull Request

Moves the following:
Enchiladas, from MEAT, to MEXICAN
Meat Bun, from PASTRIES, to MEAT
Hotdog, from PASTRIES, to SANDWICHES
Melon Bowl, from MISC, to SALADS
Oatmeal, from SALAD, to SOUPS (And changes the object path to match.)

Does the traitorous task of adding the GRAIN tag to Enchiladas. May god have mercy on my soul.

## Why It's Good For The Game

Better sorting allows for things to be found easier.

## Changelog
:cl:
qol: Enchiladas, Meat Buns, Hotdogs, Melon Bowls, and Oatmeal, are now recategorized. Also, Enchiladas are now tagged as GRAIN
/:cl:

### CODE REVIEW

**Comment by maxymax13** [comment]
a hotdog isnt a sandwich, it just isn't

**Comment by Farquaar** [comment]
Meat buns aren't pastries, but hotdogs are sandwiches
What drugs are you on, lad?

**Comment by Owai-Seek** [comment]
> a hotdog isnt a sandwich, it just isn't

> Meat buns aren't pastries, but hotdogs are sandwiches
> What drugs are you on, lad?

Don't make me put them in the Burger tab.

**Comment by Farquaar** [comment]
> 
> 
> > a hotdog isnt a sandwich, it just isn't
> 
> > Meat buns aren't pastries, but hotdogs are sandwiches
> > What drugs are you on, lad?
> 
> Don't make me put them in the Burger tab.

This isn't a mere flight of fancy
This is madness

**Comment by Capsandi** [comment]
According to the "cube rule of food" chart, an authority on the matter of what is a sandwich, hotdogs are a type of taco.  Put them under Mexican for now

**Comment by LemonInTheDark** [comment]
Merge conflicts, merge conflicts for sale

**Comment by LemonInTheDark** [comment]
<For the sake of posterity, I just fixed up their branch for them, this wasn't secretly my code all along>

**Pull request merged**
