### PR TITLE
death to war clockscarabs

### PR DESCRIPTION
**Pull request by ghost**
the whole concept of 'easily refillable fucking annoying as shit clock drones that beat the fuck out of you that can be constantly spammed' pisses me off and them being able to fire guns at all makes me angry

so that's gone, no more guns for clockscarabs, and they're slower and weaker

die, warscarabs, die

:cl: salt
add: Clockscarabs are yet shittier at combat and cannot fire guns. At all. They also have less health.
/:cl:

### CODE REVIEW

**Comment by francinum** [comment]
I ded pls nerf

**Comment by AdamElTablawy** [comment]
hey if joan can do it so can i

**Comment by kevinz000** [comment]
i ded pls nerf

**Comment by jughu** [comment]
Then firing gun is pretty op tbh

**Comment by jughu** [comment]
Plus they have all access if they clockworkfy the doors which takes like 3 seconds

**Comment by FantasticFwoosh** [comment]
Why do they exist again?

Last time i made one they just sort of looked at me and asked (What do i DO?) and to be honest if you're outright not building anything early in the game (hiding your caches etc), there isn't much point to make them in the first place.

Not least now these war-drones being annoying and hard to hit being nerfed into the ground, ratvar needs bigger constructs.

**Comment by Shadowlight213** [comment]
They need to be able to use scriptures to make clockwork structures.

Also I guess anima fragments should be made cheaper to fill in the gap of all the various cc defenses being nerfed.

**Comment by optimumtact** [comment]
you should talk to joan about your changes first

**Comment by PKPenguin321** [comment]
This should be reopened, very valid PR

I don't get why it has to go through Jo"buffs clock cult"an first

**Pull request closed without merging**
