### PR TITLE
Fixes runtimes when admin ghosting out of a camera eye

### PR DESCRIPTION
**Pull request by SuperNovaa41**
## About The Pull Request
title

## Why It's Good For The Game
runtimes bad

## Changelog

:cl:
fix: Admin ghosting from a camera eye will no longer runtime.
/:cl:

### CODE REVIEW

**Comment by JohnFulpWillard** [comment]
🤣

**Comment by SuperNovaa41** [comment]
Alternative to 
image

**Comment by JohnFulpWillard** [comment]
> Alternative to image

we should do this

**Comment by SuperNovaa41** [comment]
This will fix any camera eye (navigation computer, ai, etc)

**Pull request merged**
