### PR TITLE
Maintenance drones can use RCDs, RPEDs, Spray Bottles, and Holosign Projectors

### PR DESCRIPTION
**Pull request by ChuChu42**
## About The Pull Request

makes maintenance drones able to pick up RCD and RPEDs in order to use for upgrading and repairing the station as per their laws state

you used to be unable to pick these up due to "using this item may break your laws"
which made no sense since they could be used to repair and upgrade station gear

this fixes that
## Why It's Good For The Game

drones can now easily repair and maintain station equipment like they are programmed to do so

additionally with the use of RCD they no longer need to carry around metal sheets and glass sheets all the time, making their job way easier
## Changelog
:cl:
balance: Maintenance drones now can use RPED, RCD, Holosign, and Spray bottles
/:cl:

### CODE REVIEW

**Comment by jughu** [comment]
its a thing because drones used it to grief antags in the past

**Comment by SyncIt21** [comment]
> tweak: Maintenance drones now can use RPED, RCD, Holosign, and Spray bottles

tweak is not a valid Changelog label, Yours is a balance change so use the "balance" label

**Comment by K4rlox** [comment]
> > tweak: Maintenance drones now can use RPED, RCD, Holosign, and Spray bottles
> 
> tweak is not a valid Changelog label, Yours is a balance change so use the "balance" label

tweak shows as a changelog label but okay?

**Comment by SyncIt21** [comment]
> tweak shows as a changelog label but okay?

It's outdated and nobody has bothered to fix it. Notice how your PR has no label because the CI did not recognize "tweak" as a valid label

**Comment by ExcessiveUseOfCobblestone** [comment]
Is there a good argument for why they should have an easy time repairing the station that extends beyond "it's their ingame job"?

**Comment by deathrobotpunch** [comment]
> Is there a good argument for why they should have an easy time repairing the station that extends beyond "it's their ingame job"?

is there a good argument for why engineers should have an easy time repairing the station that extends beyond "it's their ingame job"?

**Comment by ExcessiveUseOfCobblestone** [comment]
> > Is there a good argument for why they should have an easy time repairing the station that extends beyond "it's their ingame job"?
> 
> is there a good argument for why engineers should have an easy time repairing the station that extends beyond "it's their ingame job"?

Yes, compared to drones since they are not a secondary ghost role and they carry more risk when facing say a space breach because theyre carbons so their ability to repair should outperform the ghost role.

Damage to the station has much less of an impact when you have simplemobs who likely have a grudge against the messmaker able to easily fix items if you're not cognizant of their presence.

**Comment by K4rlox** [comment]
> > > Is there a good argument for why they should have an easy time repairing the station that extends beyond "it's their ingame job"?
> > 
> > 
> > is there a good argument for why engineers should have an easy time repairing the station that extends beyond "it's their ingame job"?
> 
> Yes, compared to drones since they are not a secondary ghost role and they carry more risk when facing say a space breach because theyre carbons so their ability to repair should outperform the ghost role.
> 
> Damage to the station has much less of an impact when you have simplemobs who likely have a grudge against the messmaker able to easily fix items if you're not cognizant of their presence.

drones cannot easily navigate in space due to not having weight so they cannot easily repair breaches

ontop of that, what do you have against drones?
did you get your ice cream stolen by a drone or something?

**Comment by ExcessiveUseOfCobblestone** [comment]
> drones cannot easily navigate in space due to not having weight so they cannot easily repair breaches

I mean more like an indoor breach where gravity is still intact but carbons have to get specialized gear to address the opening where as a drone does not. Im sure there are other examples where there are perks to being a drone vs. the actual job dedicated to engineering where youre a carbon (or even a silicon i guess).

Im simply trying to understand the design of the role before I make/break the PR, im of the opinion drones should not be as good at their job as they would be if they were an engineer so when I try to prompt a convo to get the thoughts as to other reasons besides it being in their job description It keeps getting evaded.

**Comment by jughu** [comment]
drones were just a way to keep playing a small role when you round removed it shouldnt be engi++ otherwise you should go engiborg

**Comment by K4rlox** [comment]
everybody is set on the RCD part

i also made them able to upgrade machines, as well as clean floors and block gas flow

**Comment by K4rlox** [comment]
bumping 👍

**Review by Ghommie — COMMENTED** [review]
I'll give this a twirl if you change the spray to a soap bar, should they ever need to clean the occasional stain. The holosign creator is totally fine, and the RCD and RPED too... kinda.

**Pull request merged**
