### PR TITLE
removes message_admin spam from the centcom podlauncher ui

### PR DESCRIPTION
**Pull request by MrDoomBringer**
## About The Pull Request
removes message_admin spam

## Why It's Good For The Game
message_admin spam is bad

### CODE REVIEW

**Comment by Fikou** [comment]
whats up

**Comment by MrDoomBringer** [comment]
tfw u click the create pull request button too fast
i accidently added a bunch of debug message spam

**Comment by Fikou** [comment]
whats up

**Comment by MrDoomBringer** [comment]
the sky
not the nasdaq amiright

**Pull request merged**
