### PR TITLE
Menage A Trois - Putting IceBoxStation In One DMM File

### PR DESCRIPTION
**Pull request by san7890**
## About The Pull Request

Hey there,

I got it to work. I thought something would horribly break. However, nothing did. Not a peep out of runtimes, and cave+ruin generator appears to have worked flawlessly. I'm astounded, maybe I just did everything right, or maybe there's a deep demon lurking underneath the surface. Irregardless, it works:tm:.

There is a new annoying thing where you must click up twice in StrongDMM to get up to the "Station" level of IceBox, but such is the price we pay for being able to visualize everything in one window. Let me illustrate my point with a few screenshots:

This is what the mining base looks like on IceBox on Production.

image

This is what it will look like after this PR:

image

The difference is "practical obscurity" and "day". The ability to perfectly parse both z-levels at once without hotswapping, comparing coordinates, or having multiple panes can not be understated for mappers.

<details>
<summary>Want more?</summary>

Chapel, Production:
image

Chapel, OneDMM:
image

Xenobiology, Production:
image

Xenobiology, OneDMM:
image

</details>

## Why It's Good For The Game

Mappers can now visualize mapping on all three Z-levels of IceBox at once. I believe this will aid a more cohesive experience rather than having to work it out in your mind or wait for a compile.

## Changelog

:cl:
qol: IceBoxStation is now contained in one map file, instead of three. This is good for mapping. If things on IceBox break, please make an issue report.
/:cl:

Note: I assembled this map by copy-pasting the Z-Levels in. If you have any current projects on IceBox, just replace that section with a good ol' "Select Copy+Page" into your desired Z-Level.

Also, minor freeze in regards to IceBox content until this gets merged. Apologies.

### CODE REVIEW

**Comment by JohnFulpWillard** [comment]
non-player facing changelog 😦

**Comment by san7890** [comment]
WHAT THE FUCK IT UNDID MY WORK

**Comment by Mothblocks** [comment]
No mention of this breaking MapDiffBot to the point of uselessness?

**Comment by san7890** [comment]
> No mention of this breaking MapDiffBot to the point of uselessness?

It's probably useful for at-a-glance stuff, but anyone who elects to merge mapping changes shouldn't have a reliance on the MapDiffBot renders. Every time I try to use it for even small mapping reviews, I miss out on critical information such as the wiring, areas, etc. I also can not give exact tile coordinates using MDB to aid mappers in fixing the problems they may have using MDB, nor can I _absolutely ensure_ that the subtype we wish to use will work. Every time I try and conduct a review, the renders prove to have a decent level of usefulness in their differential function, but I still must open it up on local in my StrongDMM to ensure a quality review can happen without the contributor having to scratch their heads and say "where... is this?"

Will MDB be handicapped when it parses this map? Yes. Was it already handicapped, and will continue to be handicapped as the mapping scene moves more and more towards Multi-Z stations? The concept of a Multi-Z station is not going away (based on the threads we have open, Chilled and Catwalk stations both heavily rely on Multi-Z). I grant that we will ramp up in a level of uselessness when it comes to this tool on this map. I also have noted that MapDiffBot is currently undergoing a major rewrite, and I welcome the persons who work on developing such tools to add Multi-Z capability to this function.

Having Multi-Z Planetary Maps (which will have the same exact issues that you perceive will happen here) _are not going anywhere fast_. I would rather do more work (work that people presume I do, when I don't) than continuously have to wring my hands and say "that thing that people think I use would break, frowny face".

As far as merge conflicts are concerned, the most edited parts of the station were always the top floor first, and the 2nd floor second, with the 3rd floor being... third. However, beyond minor fixes, I do not believe there to be a PR that touched either the 2nd/3rd floor without already having touched the 1st floor in some capacity (at the very least, to set up cabling/piping to feed the bottom two levels). Conflicts may be a _touch_ more common, but I do not think they will rise in any substantial capacity.

**Comment by san7890** [comment]
dammit it ate my work again

**Comment by LemonInTheDark** [comment]
[deja vu, I have been in this place before](https://github.com/tgstation/tgstation/pull/63213)
flying down the street

**Comment by Fikou** [comment]
can we not make mdb useless

**Comment by MCHSL** [comment]
If this gets merged and MDB needs an update to handle z-levels (or you want any other features), open an issue here: https://github.com/MCHSL/mapdiffbot2

**Comment by Jolly-66** [comment]
> If this gets merged and MDB needs an update to handle z-levels (or you want any other features), open an issue here: https://github.com/MCHSL/mapdiffbot2

Thats for the new one (in beta).
Unless /TG/ already upgraded to it, then disregard this comment.

**Comment by LemonInTheDark** [comment]
> If this gets merged and MDB needs an update to handle z-levels (or you want any other features), open an issue here: https://github.com/MCHSL/mapdiffbot2

This'd be useful regardless honestly, we already have maps in this format

**Comment by Maurukas** [comment]
I've already come out pretty strongly in previous PRs about forcing a map format, or  converting of an existing map when the tool support is incomplete for either format.

Does SDMM fully support single-file? Is it ready for general use? SDMM 2.0 is still labeled as alpha in SpaiR's repo. From what I see it's improved. 
Do all the tools support it? I believe most of the scripts and CI simply won't care and handle either format.
Does MapDiffBot handle it? Looks like no. There's no issue up on the MDB repo. San mentions that MDB is being rewritten, but will it accommodate this format? What is the timescale for that rewrite?

**Comment by MCHSL** [comment]
> Does MapDiffBot handle it? Looks like no. There's no issue up on the MDB repo. San mentions that MDB is being rewritten, but will it accommodate this format? What is the timescale for that rewrite?

The rewrite is already up and running as a beta on some codebases alongside normal MDB, you can see a run (here)[https://github.com/ParadiseSS13/Paradise/pull/17723/checks?check_run_id=6264087727]. It already supports multiple Z-Levels per map, the `:1` in the filename means it's the first Z-Level. I'm not happy with code quality but otherwise the rewrite is nearly complete.

**Comment by AffectedArc07** [comment]
> No mention of this breaking MapDiffBot to the point of uselessness?

MDB2 supports MultiZ now 

However, you should still put dmms in split files

**Comment by Maurukas** [comment]
First, thank you both for your work on this. Every improvement to the mapping tools is appreciated.

> However, you should still put dmms in split files

If single files are now fully supported by our mapping tools, are there any advantages to split file that I am missing? The only one I see now is merge-conflict avoidance - this essentially makes Icebox' map file three times larger.

**Review by Maurukas — APPROVED** [review]
Alright. This has been thoroughly discussed. MDB2 and SDMM2 give this layout the superior (and complete) tooling.  We'll use this format going forward unless someone comes up with a compelling reason not to in a specific case.

This is going to conflict very, very hard with any other PRs open that touch Icebox, and probably require them to be redone. There are also likely to be some issues associated with this, but I'm hoping none of them are catastrophic since I last checked it out.

**Pull request merged**
