### PR TITLE
Mania Motors now do minor damage and continue to affect targets after they leave its range

### PR DESCRIPTION
**Pull request by ChangelingRain**
:cl: Joan
rscadd: Mania Motors now do minor toxin damage over time and will convert those affected if the toxin damage is high enough.
balance: The effects of a Mania Motor continue to apply to targets after they leave its range, though they will fall off extremely quickly.
rscdel: Mania Motors no longer cause brain damage.
/:cl:

When I say minor, I mean if you're standing right next to the motor it takes a minute and 15~ seconds for enough damage to built up to convert you, though as the effects linger leaving the range may not prevent you from being converted.

### CODE REVIEW

**Comment by octareenroon91** [comment]
>90 tox and  you autoconvert.

This could be interesting.

**Comment by Repukan** [comment]
What happens if someone with previous tox damage walks near it.

You know this makes engineers easier to convert because of the shard right.

**Comment by ChangelingRain** [comment]
if somebody with 90 tox walks near it they're getting converted, yes; also I'm not too worried about somebody with like 5 tox being easier to convert because it's still about a minute assuming perfect conditions.

**Comment by octareenroon91** [comment]
Yeah, it's one sideways glance from crit, when toxin isn't typically the main damage type on a person.

Maybe we'll see some more Uranium Rooms.

**Comment by CPTANT** [comment]
The thing shouldn't convert in the first place since there are already THREE other things Clockcult has to convert.

**Comment by Repukan** [comment]
Make it so breathing oxygen slowly converts you too

**Comment by CPTANT** [comment]
Seriously, having 4 different ways of converting is overkill.

**Comment by Repukan** [comment]
Gotta compensate for shit cultists

**Comment by ChangelingRain** [comment]
To be fair, I'm intending this thing more as a defense than as a main conversion method like geis or the sigils; that's why it does damage and has all the confusing/damaging effects.

**Comment by CPTANT** [comment]
Then why not remove the conversion and buff the confusion/damage?

**Comment by ChangelingRain** [comment]
The conversion isn't actually a significant power/balance cost especially with this version, which makes it much more of a bonus effect if you have targets who remain in range too long.
I also don't really want to buff the damage OR confusion, because it's a pretty strong effect, especially if it lingers like it does now.

**Pull request merged**
