### PR TITLE
chem dispensers now use plasma to work

### PR DESCRIPTION
**Pull request by Ghilker**
## About The Pull Request

Chem dispensers now uses plasma gas with power to  refill their internal buffer. The plasma consumption is half of the power consumption

Help with mapping would be greatly appreciated
## Why It's Good For The Game

dispensers now use some kind of material for their production, in this case plasma; 
the idea is to add a small layer of dept to the production of chemicals so that it expands many factors of the game, from the lore aspect (plasma research station), to the roleplay aspect (the requirement to ask atmos/engi or cargo for a fresh canister), the dangers of plasma handling and a potential new source of fires for atmos to fight (currently the only source is atmos and most of the times they cause the fires as antag).
## Changelog
:cl:
add: chem dispensers now use plasma to work.
/:cl:

### CODE REVIEW

**Comment by GPeckman** [comment]
> Chem dispensers now uses plasma gas with power to refill their internal buffer. The plasma consumption is half of the power consumption

Okay, does this mean half a mol of plasma per unit of power or what?

**Comment by Ghilker** [comment]
> > Chem dispensers now uses plasma gas with power to refill their internal buffer. The plasma consumption is half of the power consumption
> 
> Okay, does this mean half a mol of plasma per unit of power or what?

basically yes

**Comment by Pickle-Coding** [comment]
Could you explain how the plasma would get transferred? Does the chemistry dispenser have an atmos node, or does it take from tanks?

**Comment by Ghilker** [comment]
> Could you explain how the plasma would get transferred? Does the chemistry dispenser have an atmos node, or does it take from tanks?

it's an atmos machinery now, so it works similarly to thermomachines and cryo, it has a port and you connect a pipeline to it

**Comment by mc-oofert** [comment]
caption

**Comment by dieamond13** [comment]
How does this effect the use of capacitors?

**Comment by Ghilker** [comment]
> How does this effect the use of capacitors in the machine?

it increases the recharge rate, so it increases the consumption rate

**Comment by Ghilker** [comment]
i like the other one better

**Pull request closed without merging**
