### PR TITLE
Fix improper null coalescence with has_antag_datum

### LINKED ISSUE #54385: Players sometimes have no names while talking
Issue reported from  Round ID: [148253](https://scrubby.melonmesa.com/round/148253) (/tg/Station Sybil [ENGLISH] [US-WEST] [100% LAG FREE])

Reporting client version: 513.1528

"
image

image
image

### PR DESCRIPTION
**Pull request by Mothblocks**
## About The Pull Request
Fixes an incorrect correction of `has_antag_datum` to use `?.`. This does not work since `has_antag_datum` returns 0 or an object, meaning `has_antag_datum()?.property` is essentially `0.property`.

Fixes #54385.

## Changelog
:cl:
fix: Fixed improper radio names.
/:cl:

### CODE REVIEW

**Comment by MrPerson** [comment]
Wouldn't it be better to make has_antag_datum() return null instead of 0? Does anything depend on that 0 behavior?

**Comment by Jared-Fogle** [comment]
The answer to your first question is yes. The answer to your second question is I don't know.

**Comment by Jared-Fogle** [comment]
Looks like the answer is no.

**Review by Rohesie — APPROVED** [review]
I hate this proc

**Comment by wesoda25** [comment]
speedmerge speedmerge

**Review by Cyberboss — APPROVED** [review]

**Comment by LemonInTheDark** [comment]
Radio names are important ok

**Pull request merged**
