### PR TITLE
Adds d1 and d100 dice

### PR DESCRIPTION
**Pull request by Incoming5643**
Dice bags are now filled like this:

You will always get a standard assortment of six dice (d4, d6, d8, d10, d12, d20)
The seventh die will be chosen from the remaining exotic dice (d1, d2, d00, d100)

Moves dice bags from firstaid.dm to dice.dm

### CODE REVIEW

**Comment by PKPenguin321** [comment]
>d1

excuse me but i am not sure that is even possible

**Comment by Incoming5643** [comment]
Paint a 1 on a sphere sometime

**Comment by Bawhoppen** [comment]
image

**Comment by duncathan** [comment]
These are both useless, and missing out on, say, a d20 in the dice bag will ruin your DnD experience. :-1:

**Comment by CosmicScientist** [comment]
:-1: if I know what rolling a dice for dice means, it's that you won't get the dice you need.

Make it all dice or no dice.**/pun**

d1 also sounds unnecessary but a d100 is welcome.

**Comment by freerealestate** [comment]
what the hell is the point of a d1

**Comment by Supermichael777** [comment]
proving to an ai that self determination is an illusion. you can chose to roll a die but you cannot chose the result. The result is ether random or has already been chosen for you. Free will is an illusion, an quirk of complex organic chemistry. also proves your insane as rolling a die over and over never lets you roll 0.

**Comment by Incoming5643** [comment]
I have placated the metaroleplayers

**Comment by tuypo1** [comment]
@Supermichael777 
but the ais not a computer its a human brain pluged into a computer

**Comment by Dorsisdwarf** [comment]
Is freddy ready?

**Comment by Incoming5643** [comment]
it's been ready. Dunc's suggestion is valid, but at this point it doesn't save any lines over how I do it.

**Pull request merged**
