### PR TITLE
Taser begone

### PR DESCRIPTION
**Pull request by nemvar**
## About The Pull Request

Replaces the taser mode on the old egun with disabler mode.

## Why It's Good For The Game

BEGONE

## Changelog
:cl:
balance: The taser mode on the old egun has been replaced with a disabler.
/:cl:

### CODE REVIEW

**Comment by Fikou** [comment]
kinda cringe tbh

**Comment by wesoda25** [comment]
I’m confused as to whether or not you missed when we removed these guns from the game?? They’re in there now only for admin purposes and its a shame to just remove them.

**Comment by Fikou** [comment]
> I’m confused as to whether or not you missed when we removed these guns from the game?? They’re in there now only for admin purposes and its a shame to just remove them.

this is a gun from charliestation that can fire only 1 (one) taser bolt and the only normally obtainable taser
removing it is kinda cringe

**Comment by HomocidlePancakes** [comment]
No : (

**Comment by wesoda25** [comment]
Oh i have no opinion on this anymore

**Comment by ishitbyabullet** [comment]
Who the fuck is going to rush charlie station for the one shot taser?

Even if someone does it because of my post or this PR, I am pretty sure almost no one ever did or does that.

**Comment by TerraGS** [comment]
Absolutely no demand for nor appreciable benefit from this PR.

**Comment by duckay** [comment]
this conficts with protoguns' lore. it's terrible energy is based on that the cell is still in development, and so is the alternative fire mode, which is expected to be replaced by disable in the next model, K15

**Comment by PKPenguin321** [comment]
sounds like this just needs to be removed from the map that it's on

**Comment by wesoda25** [comment]
> sounds like this just needs to be removed from the map that it's on

the gun is kinda necesarry for the task of cleaning out hivebots, or at least useful. really the only light at the end of the tunnel for someone on the space ruin. 

just keep it, at the end of the day who gives a shit if it can shoot one golden bolt

**Comment by FloranOtten** [comment]
Kinda cringe tbh. Why remove it? It's a single taser shot on a ruin that has a chance of spawning on a Z level far away. It'd be easier to steal the HoS gun from the locker.

**Comment by anconfuzedrock** [comment]
if you actually care then for the sake of balance it's easier to make a shotgun grenade or dart full of instadeath poison so you should be removing those as well


nobody should actually care though this gun is fine

**Comment by ShizCalev** [comment]
image

**Pull request closed without merging**
