### PR TITLE
Crew pinpointers now fit on medical belts

### PR DESCRIPTION
**Pull request by ghost**
:cl: Xhuis
tweak: Crew pinpointers now fit on medical belts!
/:cl:

This always felt out-of-place to me, so I changed it. Inventory tetris is never fun.

### CODE REVIEW

**Comment by SgtxRootbeer** [comment]
INVINTORY BUFF

**Comment by Xhuis** [comment]
Something something storage creep something something hugbox.

**Comment by improvedname** [comment]
have 7 crew trackers in your belt to track down your victims

**Comment by Anonmare** [comment]
@improvedname Important for bounty hunter gimmicks

**Pull request merged**
