### PR TITLE
more debug stuff to solve atmos runtimes

### PR DESCRIPTION
**Pull request by duncathan**
```
The following runtime has occurred 4583 time(s).
runtime error: list index out of bounds
proc name: process atmos (/obj/machinery/atmospherics/components/trinary/filter/process_atmos)
  source file: filter.dm,89
  usr: null
  src: the gas filter (/obj/machinery/atmospherics/components/trinary/filter)
  src.loc: the floor (167,119,1) (/turf/open/floor/plasteel)
```

trying to figure out what's going wrong
as always, I need as much useful data as possible from live to find the problem

### CODE REVIEW

**Comment by duncathan** [comment]
Please squash when merging this
I should know better by now than to use the github editor on my phone

**Comment by RemieRichards** [comment]
Uh, not try/catch.
can you not just use an if to check the index is valid?
try/catch is ludicrously slow in byond, worthless even.

**Comment by duncathan** [comment]
I don't even know what the index being supplied is; I want to know exactly what is causing the runtime and doing it this way will guarantee it.
I know it's slow but it's by no means worthless.

This is only a temporary measure; I'll likely only need it to be live for a day or two before I can fix the error proper and revert the debug stuff.

**Comment by RemieRichards** [comment]
You can find out the index by just outputting it, there's no need to use as ridiculously slow a construct as DM's try/catch

**Comment by duncathan** [comment]
What am I gonna check to know whether the runtime will be caused? How will I be certain I'm covering all cases? I don't know the context of the error; I don't know what change may have caused it; I don't know which cases are even working properly. Using try/catch guarantees I will get the useful information I need to fix the error. Once I get some data, I'll be able to change this to a simple and much faster if statement, or just fix the runtime outright. Either way, I only expect this code to be live for a day or two, just to collect data.
Getting this data on my own is infeasible, as it is with nearly every atmos runtime I've ever fixed.

**Comment by RemieRichards** [comment]
>The following runtime has occurred 4583 time(s).
>runtime error: list index out of bounds
>proc name: process atmos (/obj/machinery/atmospherics/components/trinary/filter/process_atmos)

The index is wrong.
print the index, this specific "out of bounds" is for using a number higher than the ```.len```, gases and consequently ```filter_type``` is supposed to be a string, for this bug to be occurring, it's a number.

simply throw a shitfit/exception when it receives a non-text filter_type, outputting what it was.

**Comment by duncathan** [comment]
fucking hell I leave for six months and forget that `istext()` exists

**Comment by RemieRichards** [comment]
even if it didn't, ```if(isnum(filter_type))``` :P

**Comment by duncathan** [comment]
yeah that's better

**Pull request merged**
