### PR TITLE
turns triple ai mode into a station trait

### PR DESCRIPTION
**Pull request by Fikou**
## About The Pull Request
removes the triple ai mode secret and makes it into a station trait

## Why It's Good For The Game
it seems to be an interesting way to spice up the gameplay of a given round

## Changelog
:cl:
add: turns triple ai mode into a station trait
/:cl:

### CODE REVIEW

**Review by Mothblocks — APPROVED** [review]

**Comment by Dorsisdwarf** [comment]
it does kinda screw over any malf ais that roll, because if either of their partners see them do anything malf they can immediately suicide pact by turning off their shared APC.

**Comment by BlueMemesauce** [comment]
Even then, the other AIs could open the doors and turn off the turrets to let people card all the AIs and find the malf AI. The malf AI could rush the overload machine ability to blow up the other AIs, but they wouldn't have enough time to prepare anything else and would probably die to the crew. I don't think there's any way a malf AI could survive. Although having both a malf AI and this scenario would be pretty rare so maybe we could just ignore that situation.

**Comment by Vect0r2** [comment]
What if a malf roll made all three of the AIs malf?

**Comment by DATA-xPUNGED** [comment]
> > it does kinda screw over any malf ais that roll, because if either of their partners see them do anything malf they can immediately suicide pact by turning off their shared APC.
> 
> They can't do this under Asimov, Crewsimov, Hippocratic Oath, Corporate, UN, Mother Drone and arguably Hogan lawsets. Which is most round start ones. Nutimov, Paladin and Reportertron lawsets allow this though so maybe blacklist those ones from being selected round start with this trait if it's a problem?

Why wouldn't they be able to do it with asimov? Law 1 of preventing human harm precedes law 3

**Comment by carshalash** [comment]
Not a fan, borgs always go to a single AI in multi AI situations.

**Comment by ATH1909** [comment]
> Not a fan, borgs always go to a single AI in multi AI situations.

we could randomly split up the roundstart borgs amongst them? and maybe add more roundstart borg slots if this trait rolls?

**Comment by DaCoolBoss** [comment]
> Why wouldn't they be able to do it with asimov? Law 1 of preventing human harm precedes law 3

Law 3 is always in effect, the clause is only partial. Helping the crew by fighting a blob, blocking bullets when nukies are shooting the captain, or wading into a plasma fire to save burning humans is a case of prioritising their safety over yours. Throwing self preservation out entirely to suicide bomb nonhuman antags is just straight up ignoring your law 3. Humans are more important, sure, but you cannot suicide unless there is literally no other choice or you're ordered to.

**Comment by Dorsisdwarf** [comment]
> > Why wouldn't they be able to do it with asimov? Law 1 of preventing human harm precedes law 3
> 
> Law 3 is always in effect, the clause is only partial. Helping the crew by fighting a blob, blocking bullets when nukies are shooting the captain, or wading into a plasma fire to save burning humans is a case of prioritising their safety over yours. Throwing self preservation out entirely to suicide bomb nonhuman antags is just straight up ignoring your law 3. Humans are more important, sure, but you cannot suicide unless there is literally no other choice or you're ordered to.

This is not really true, because if one of your core coworkers is malf then you are obligated to kill them by any means necessary, because malf ais always kill people, blow up the station, forceborg, etc. They dont have peaceful objectives unlike normal ais - they are going to harm the humans.

**Pull request merged**
