### PR TITLE
Spiderpalooza 1: Foods!

### PR DESCRIPTION
**Pull request by ghost**
image

The new sprites for spider eggs are also animated! (final product MUCH faster, this is the only gif i got!)

New food, spider lollipops!

New sprites for sashimi!

NEW SPRITES FOR GREEN EGGS N HAM! (eggs animated, not shown here!)

## THANK YOU ONULE!

### CODE REVIEW

**Comment by jughu** [comment]
NEED PICS

**Comment by Armhulen** [comment]
PICS DELIVERED also the eggs are now animated

**Comment by GunHog** [comment]
That....Is...So...GROSS!!! :+1:

**Comment by sawrge** [comment]
Snackin out gamer style

**Comment by WJohn** [comment]
Huge improvement over the sprites we have now. Good stuff.

**Comment by Armhulen** [comment]
all thanks to onule

**Comment by Iatots** [comment]
Well, into the trash goes green eggs and ham.

**Comment by FantasticFwoosh** [comment]
People can work around it, either to make new sprites or a plausible additional ingredient that happens to be green as flavouring.

**Comment by Armhulen** [comment]
new ham sprite get good

**Pull request merged**
