### PR TITLE
Readds :joy:

### PR DESCRIPTION
**Pull request by silicons**
adds :joy: to OOC emotes.

### CODE REVIEW

**Comment by Armhulen** [comment]
good kevvvy..........................

**Comment by Repukan** [comment]
Kill yourself

**Review by Cyberboss — APPROVED** [review]

**Comment by Anonmare** [comment]
😂😂😂😂😂

**Comment by ExcessiveUseOfCobblestone** [comment]
@Repukan I think you mean 🅱️ ill 🅱️ ourself

**Comment by lzimann** [comment]
Let's not.

**Comment by kevinz000** [comment]
:(

**Pull request closed without merging**
