### PR TITLE
Adds dope necklaces

### PR DESCRIPTION
**Pull request by PKPenguin321**
Three can be found in the clothesmate when a coin is inserted.
Normal gangs (not sleeping carp) can buy them for 1 influence each.
They are purely cosmetic, aside from making you a straight thug. (In other words, they are purely cosmetic.)
They are a jumpsuit accessory, meaning they can be pinned to your jumpsuit like a tie or a medal.

RIP #12741 ;-;7

05b12238-7e70-11e5-99a3-1058d74db11c

Better sprites are welcome, wanted, and appreciated.

:cl: PKPenguin321
rscadd: Dope golden necklaces have been added. They're a jumpsuit attachment like ties and are completely cosmetic.
rscadd: Dope necklaces can be bought from the clothesmate with a coin. Three are in the clothesmate by default, so you can get your posse going. Gangs that aren't Sleeping Carp can also purchase necklaces for 1 influence each. Dope.
/:cl:

### CODE REVIEW

**Comment by Supermichael777** [comment]
HOLLA HOLLA GET DOLLA

**Comment by PKPenguin321** [comment]
nooooo

**Comment by GunHog** [comment]
What if they contributed to your influence just a little, the same as gang uniforms do? They are SWAG, but do make it obvious that you are valid.

**Comment by PKPenguin321** [comment]
interesting idea that i've played with but i have no idea how to get that to work lol

**Comment by Zilenan91** [comment]
Can't you copy paste the influence bonus code from gang jumpsuits and tweak values?

**Comment by PKPenguin321** [comment]
you'd think so but unfortunately its way more complicated, there isnt really an "influence bonus code"
i wish it were that simple

**Comment by RemieRichards** [comment]
@Zilenan91 
"how to get your PR closed 101"

**Comment by Supermichael777** [comment]
Those codersprites are truly shitty, for something purely cosmetic you need to have it actually look good.

**Comment by PKPenguin321** [comment]
i agree but unfortunately our spriters are a bunch of fuckboys who dont want dope accessories apparently

**Comment by Aranclanos** [comment]
@WJohn will know if the sprites are shitty or not

**Comment by WJohn** [comment]
Tolerable mob-sprites, extremely shitty on-floor sprites. :-1:

**Comment by Iamgoofball** [comment]
I think he's using stretch to fit in the example img, check the icon file itself

**Comment by WJohn** [comment]
I did, it's shitty there too.

**Comment by Iamgoofball** [comment]
Redo the sprites fam tbh imo

**Comment by PKPenguin321** [comment]
yeah the on-floor sprites are ass
i guess i could look at it but i am kinda shit at spriting
>a dull piss yellow color (not even gold)

what's even the difference :sob:

**Comment by swankcookie** [comment]
@PKPenguin321 I can do some respriting, if you're interested.

**Comment by swankcookie** [comment]
http://imgur.com/DusV9tb

**Comment by PKPenguin321** [comment]
aight so i merged a thing from my boy @swankcookie hopefully that did the do

**Comment by swankcookie** [comment]
You can expect my spriting bill shortly.

**Comment by WJohn** [comment]
Those sprites are significantly better, I'm fine with those being in.

**Comment by swankcookie** [comment]
oh, stop it, you....

**Comment by duncathan** [comment]
Something went wrong with your diff.

**Comment by tkdrg** [comment]
@PKPenguin321 fix this

**Comment by PKPenguin321** [comment]
i don't even know what's going on
i might just remake the PR

**Comment by PKPenguin321** [comment]
\>branch name is bling-never-dies
\>pr dies anyways
im a failure

**Pull request closed without merging**
