### PR TITLE
Fixes rollies and pipes spawning with nicotine

### PR DESCRIPTION
**Pull request by Tacolizard**
The New() proc remove the 15u of nicotine that pipes and rollies inherit from cigs.

### CODE REVIEW

**Comment by optimumtact** [comment]
This is not the right solution, instead the reagent and amount to store should be stored as vars or otherwise that can be overwritten by the children so they can spawn with their own starting chemicals instead.

Or and perhaps even better, a proc intial_reagents that spawns the intial reagents for the ciggarette and can be overriden to do nothing (or spawn it's own custom reagents) for child types.

**Comment by Tacolizard** [comment]
yeah, but like, this is easier and simpler. If a child needs to spawn with reagents then all you have to do is make a child that has a New() proc with reagents.add_reagents()

**Comment by coiax** [comment]
@optimumtact The reagent list IS stored on the cigarette type.

**Comment by RemieRichards** [comment]
2 maintainers say no, ask for a reopen once you've changed it or make a new PR with the changes.

**Comment by coiax** [comment]
Look at the `list_reagents` var on /obj/item/clothing/mask/cigarette

**Comment by optimumtact** [comment]
I did not even see that lol

**Pull request closed without merging**
