### PR TITLE
Updates the katana sprite and all its associated mob sprites.

### PR DESCRIPTION
**Pull request by CRITAWAKETS**
## About The Pull Request

This PR updates the katana sprite to one which does not look like it was made in about 30 seconds. It also updates all the associated mob sprites to proper coloring and styling for the new sprite.

## Why It's Good For The Game
Left is new, Right is old.

(yeah it just doesnt appear in white, lol)

Here's an example in a location you'd see. I kinda think the table is basically the worst-case scenario since its basically in the middle of the katana's color spectrum.

## Changelog

:cl:
imageadd: The Spider Clan has issued a recall of all it's katanas, replacing them with new ones that are differently styled. Something about the old ones being literally impossible to find in bright conditions. Or maybe they just didnt like how it looked so they changed its "sprite".
/:cl:

### CODE REVIEW

**Comment by Dorsisdwarf** [comment]
why's it so purple

**Comment by CRITAWAKETS** [comment]
because color tinting looks cool and good

**Comment by EricZilla** [comment]
Its made of plasma + titanium alloy so it cuts good and is off purple thats why

**Comment by Imaginos16** [comment]
Looks nice, good job.

**Pull request merged**
