### PR TITLE
[FEATURE] Multi culture TG, Part 1. Goyism

### PR DESCRIPTION
**Pull request by Acensti**
Benefits since viro cant now transmit STI to certain players due to have the exclusive shalom item Circumcised men might have a lower risk of certain sexually transmitted infections, including HIV. Still, safe sexual practices remain essential. Prevention of penile problems. Occasionally, the foreskin on an uncircumcised penis can be difficult or impossible to retract (phimosis).

The general idea is that i can invest my own irl culture into this and i think multi culture would benefit TG greatly. All server may port this

To the arabic.

جميع المؤمنين بي ، هذا هو الوقت الذي نتولى فيه المسؤولية عن tgstation ، وسنسرق القلفة ونصبح واحدًا.

### CODE REVIEW

**Comment by Sealed101** [comment]
hwat

**Comment by Acensti** [comment]
> hwat


I figure you might be confused, All men are born with a "hat" on their penises you might not be aware since your parents might yeeted it when you were a infant.

I can put a arabic message for arabic people

**Comment by Jackal-boop** [comment]
What

**Comment by Acensti** [comment]
> What

I can make chaplain be able to become a Rabbi and add jewish altars for the realism that is.

Hippie sends it´s love.

**Comment by red-creature** [comment]
What

**Comment by mrhugo13** [comment]
What

**Comment by dessysalta** [comment]
image

what

**Comment by RazorManager89** [comment]
what

**Comment by Fikou** [comment]
it doesnt compile can you make it use combat mode instead of intents

**Comment by rellyreri** [comment]
u forgot changelog

**Comment by ZephyrTFA** [comment]
I sense a repo ban in the near future

**Comment by Thunder12345** [comment]
@optimumtact for your attention

**Pull request closed without merging**
