### PR TITLE
Adds narrow exceptions to the silicon lathe tax

### PR DESCRIPTION
**Pull request by GPeckman**
## About The Pull Request

As part of the long-term rework of the material and money economies, all carbons are required to pay a small lathe tax when printing items from protolathes outside their department. This does not apply for lathes in the department. Cyborgs are also required to pay a lathe tax. When printing any item from any protolathe, the cyborg's cell loses 2000 units of power (for context, the default borg cell has 10000 capacity, and the best printable cell has 40000). Unlike carbons, there are no departmental exceptions. All items printed from a techfab or protolathe are subject to the power tax. This PR is intended to add some very narrow exceptions to the power tax. Borgs with the organ bag module will be able to print organs without incurring the tax, and borgs with the RPED module will be able to print stock parts (but NOT circuit boards) without paying the tax.
## Why It's Good For The Game

Regardless of whether the power tax is needed, maintainers have made it clear that the tax will not be removed wholesale (#76032). However, the tax can make it more difficult for borgs to do their jobs. Mediborgs have the organ bag module, which allows them to pick up, carry, and implant organs, both natural and cybernetic, into their patients. There are doubtless situations where a mediborg has to treat a corpse with rotted and/or missing organs, and power tax will add unnecessary difficulty, especially considering that each individual type of organ will incur the power tax separately. Replacing the heart, liver, lungs, and stomach will drain 80% of a borgs cell, assuming the cell is not upgraded. Similarly, borgs with the RPED upgrade are expected to make and install stock parts, and there are 6 different kinds of stock parts that are used in machines around the station.

By adding narrow exceptions for these scenarios, borgs will be able to do their jobs more easily without the risk of unbalancing the economy. I would like to stress that these exceptions are, in fact, narrow. The discounts will only apply to borgs with the organ bag or RPED modules, and only for relevant items, as borgs are not expected to print items that they cannot use.

EDIT: Exceptions have also been added for the beaker manipulation apparatus and pseudocircuitry module.
## Changelog
:cl:
balance: Borgs with the organ bag module can print cybernetic organs without paying the silicon lathe tax.
balance: Borgs with the RPED module can print stock parts (but NOT circuit boards) without paying the silicon lathe tax.
balance: Similar exceptions made for the beaker manipulator and pseudocircuitry module.
/:cl:

### CODE REVIEW

**Comment by Fikou** [comment]
image

**Comment by Kubisopplay** [comment]
Add beakers to medical, and energy cells and APC/air alarm electronics to engi.

**Comment by Ryusenshu** [comment]
> As far as I'm aware, energy cells are a subtype of stock_parts and should already fall under these exceptions. Regarding circuitry, engiborgs already start with a module (Electroadaptive Pseudocircuit) that allows them to build firelocks, air and fire alarms, and APCs. Beakers are a good catch though, I'll add it if the maintainers have no qualms about that.

Borgs have to print apc/alarm/thingymagic boards to refill that circuit
They can use that module on those to get that counter back up

**Comment by GPeckman** [comment]
Alright, I can see about adding exceptions for that too.

**Comment by Helg2** [comment]
Wouldn't the expections made for borgs the same way as for humans be better? So engi borg can use engi lathr, and med borg can use med lathe.

**Comment by GPeckman** [comment]
The difference is that borgs won't _need_ to print most things from their departmental lathe, and the maintainers have concerns that borgs could be law 2'd by humans to print stuff as a way of bypassing the lathe tax. Hence, exceptions should be as narrow as possible.

Also I've realized that if I'm adding this many exceptions I should probably refactor the code and make it use defines more.

**Comment by optimumtact** [comment]
This simply embeds the failed concepts more rather than actually reworking them.

**Comment by ATH1909** [comment]
> This simply embeds the failed concepts more rather than actually reworking them.

which are?

**Comment by GPeckman** [comment]
The idea with using defines is that, rather than creating these lists of exceptions every single time a borg prints something from a lathe, the lists of exceptions are calculated once and stored as a define. I'm currently testing the reworked code, once I'm confident it works I'll push the commit and you can examine it in detail.

**Comment by GPeckman** [comment]
All my tests were successful. Exceptions have been added for beakers with the beaker manipulation apparatus and the 4 relevant circuitry types for the pseudocircuitry module. The code has also been refactored, it now uses a for loop rather than a chain of if-statements to determine if an exception applies. Adding new exceptions will also be a breeze now, just a matter of adding a new entry to the global list of exceptions.

**Comment by Jackal-boop** [comment]
why dont maints want the silicon tax fully removed?

**Comment by CRITAWAKETS** [comment]
> why dont maints want the silicon tax fully removed?

https://en.wikipedia.org/wiki/Sunk_cost

**Comment by Comxy** [comment]
Based. What was the problem by the way? Have borgs been printing too much prolathe items based on law 2 requests for the tax to be instigated? Maybe this is byond me but I get confused when I see 30 lines of text, I can barely understand what is going on

**Comment by Ryusenshu** [comment]
> Based. What was the problem by the way? Have borgs been printing too much prolathe items based on law 2 requests for the tax to be instigated? Maybe this is byond me but I get confused when I see 30 lines of text, I can barely understand what is going on

Not really, the tax came with silicons already included for some reason

**Comment by moocowswag** [comment]
> Borgs have to print apc/alarm/andsuch boards to refill that circuit They can use that module on those to get that counter back up

Also using that module uses a ton of power so borgs already get hit by a pretty large power hit when using it

**Comment by Kubisopplay** [comment]
Oh right, also kitchen items exceptions for serviceborg, since printing oven trays for 2 thousand energy sucks


> This simply embeds the failed concepts more rather than actually reworking them.

As you may have seen, arcane refused to remove the tax, even after being pointed out that AIs could print this entire time, and they haven't caused any destruction of the economy.

**Comment by TheVekter** [comment]
This probably isn't getting merged. Fair warning.

**Comment by GPeckman** [comment]
As far as I can tell, service borgs have no way of picking up the baking trays, or of putting them in and out of the oven. I don't think that exception is necessary, and the exceptions are based on the modules a borg has, not the model.

**Comment by Kubisopplay** [comment]
> As far as I can tell, service borgs have no way of picking up the baking trays, or of putting them in and out of the oven. I don't think that exception is necessary, and the exceptions are based on the modules a borg has, not the model.

They do in fact have a module that allows them to pick up trays, in service upgrades.

**Pull request closed without merging**
