### PR TITLE
New sprites for venus human traps, cockroaches, and headslugs.

### PR DESCRIPTION
**Pull request by KazeEspada**
newsprites
Cockroaches and Headslugs are animated. They wiggle.

### CODE REVIEW

**Comment by WJohn** [comment]
Pretty much anything is an improvement so :+1:

**Comment by Iamgoofball** [comment]
The Venus Human Trap is the goon sprite.

Where did you get it? Was it given to you by one of the dev members?

**Comment by KazeEspada** [comment]
Jungle station code.

**Comment by ShadowDeath6** [comment]
Is that the purring maggot sprite from LifeWeb?

**Comment by KazeEspada** [comment]
I may be a sprite thief. What's it too yeah?

**Comment by ShadowDeath6** [comment]
Confirmed sprite thief, what will the playerbase think?

**Comment by KazeEspada** [comment]
Players dont care, they just like shiny new sprites.

**Comment by RemieRichards** [comment]
@KazeEspada We can't use the Goon sprite, its from a leak.
You need to change it.

**Comment by duncathan** [comment]
Yeah we're gonna need to know the license for each of these before we can merge

**Comment by KazeEspada** [comment]
Junglestation is AGPL(it might be GPL) currently.
Lifeweb was morally ambiguous GPL I think.

**Comment by RemieRichards** [comment]
@KazeEspada Again, thats not a Junglestation sprite, its from a Goon leak, I even have the DMI myself to prove it, you can NOT use the Goon sprite.

If you can't confirm Lifeweb as GPL, you can't use it either. Confirm or bust.

**Comment by Cheridan** [comment]
>startoad

**Comment by GunHog** [comment]
CHERIDAN NO

**Comment by Cheridan** [comment]
We need to quarantine the area. It's the only way to be sure it doesn't spread.

**Comment by Zilenan91** [comment]
I'm pretty sure the headslug sprite above is the cortical borer sprite Lifeweb ripped from Bay

**Comment by RemieRichards** [comment]
@Zilenan91 it isnt actually, bay use a cortical borer sprite that I made (they originally had a 1-directional version, which I cleaned up and made 4-dir)

**Comment by Zilenan91** [comment]
Huh okay

**Comment by RemieRichards** [comment]
@Zilenan91 it exists from when I tried to port borers here, but it died, bay decided to take some of the PRs improvements back with them, including the sprite.

~weird little neat fact~

**Pull request closed without merging**
