### PR TITLE
Military Belt is not a backpack

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
Why was this merged being able to store the entire armory in your belt slot is silly

### CODE REVIEW

**Comment by PKPenguin321** [comment]
kneejerk :^)

**Comment by xxalpha** [comment]
It was merged because you let it be merged?

**Comment by KorPhaeron** [comment]
Believe it or not I do not personally make a decision on all 70+ prs that happen each week

**Comment by Zilenan91** [comment]
Something needs to be done about Ops in general. They've had so much power creep lately.

**Comment by xxalpha** [comment]
Are you saying you can't handle the burden of directing an entire game's design direction and that you are ready to pass the torch to someone else willing?

**Comment by octareenroon91** [comment]
Max total w_class of 14. That's four guns, not seven.

**Comment by optimumtact** [comment]
@xxalpha how about you ram your ignorant head up your ass a few times and then realise that it's impossible for one person to review 70+pr's merged by a team of more than 5 maintainers.

nor should they have to, maintainers should be smart enough to not merge stuff like this

**Comment by Bawhoppen** [comment]
Kor if you do this military belts can't even hold stun batons
seriously, you can easily just put the guns in your backpack instead, the military belt only has 7 slots you can't hold the entire armory

**Comment by Zilenan91** [comment]
The military belt is a fucking ammo/tool belt ops don't need to hold stunbatons or literally anything else.

**Comment by Bawhoppen** [comment]
I also use it to hold grenades, c4, bombs, emags, pistols, pinpointers, etc etc
thats what its meant for, if theres a rare case where an op gets a stunbaton he should be able to stick it in his belt

**Comment by Zilenan91** [comment]
No he shouldn't because it's a fucking ammo/utility belt not something you give to a beat cop

**Comment by Bawhoppen** [comment]
thats not what it is brah
if it was just that then there would be a whitelist for what it could hold already

**Comment by KazeEspada** [comment]
Storage has whitelists....

**Comment by Bawhoppen** [comment]
military belt does not have a whitelist
we could add one but it does not

**Comment by Lumipharon** [comment]
It was fine before, just merge this.
NT had a belt of holding if you wan this shit.

**Comment by Bawhoppen** [comment]
I want it to be able to hold batons

**Comment by Jalleo** [comment]
I believe the security belt has a override for a stunbaton.

**Comment by xxalpha** [comment]
@optimumtact don't get so mad at a joke

**Comment by Bawhoppen** [comment]
@Jalleo it doesn't, its max_w_class 3 but it has a whitelist

**Comment by coiax** [comment]
I thought the point of a military belt was that it was like a belt but had no item restrictions, and came at the cost of being BRIGHT RED.

Could you keep it at the current size capacity but add stun batons being explicitly whitelisted if that's the aim?

**Comment by Bawhoppen** [comment]
with our current code you cannot whitelist an item that is bigger than the max_w_class to fit
I could code in some snowflake thing but meh

**Comment by coiax** [comment]
You could blacklist guns if that's the concern.

**Comment by AdamElTablawy** [comment]
it's not a fucking 'ammo belt'

it's intended to hold shit, important shit, not just ammo

because otherwise there's no reason to have it as a traitor item or an ops item

the most a nukeop can hold in that belt is 3 laser guns at the most and that's if they want to sacrifice all their important storage for grenades, c4, pinpointer, emags, ect

**Comment by Bawhoppen** [comment]
actually I am dumb, why don't I just make the baton smaller anyways?

**Comment by KorPhaeron** [comment]
Cause then it would fit in pockets/boxes.

We need to double the weight class of everything and the capacity of everything like we did with tc so we can have more freedom in setting sizes

**Comment by Bawhoppen** [comment]
should we actually?

**Comment by KorPhaeron** [comment]
I think it'd be useful yeah

**Comment by Jordie0608** [comment]
So whats the verdict here? Merge?

**Comment by KorPhaeron** [comment]
@Jordie0608 

Please do yeah. Probably doesn't matter either way but I can't lose to bawhoppen now

**Comment by Bawhoppen** [comment]
thats abuse of power

**Comment by KorPhaeron** [comment]
Putting w_class 3 items in belts is an abuse of the games tenuous relationship with realism

**Pull request merged**
