### PR TITLE
Allow people to use a handful of Unicode letters in their names

### PR DESCRIPTION
**Pull request by MrPerson**
## About The Pull Request

Specific list of letters allowed here: https://en.wikipedia.org/wiki/List_of_Unicode_characters#Latin-1_Supplement
Everything in the Letters: Uppercase and Letters: Lowercase except the eth and thorn. These are all standard English letters with marks on them other than the German letter ß. I'm kind of iffy on including that one tbh. They should all be pretty easy to replace if you don't have the necessary letters on your keyboard by for example calling "Rãul" as "Raul".

Raw HTML interfaces (mostly PDAs and VV) will fuck up display of these letters, but goonchat, tgui-next, and browser datum interfaces will display them fine. 

## Why It's Good For The Game

Spanish, French, German, etc names can be more unique and flavorful.

## Changelog
:cl:
add: You can use letters like Ò and é in your name.
/:cl:

### CODE REVIEW

**Comment by Fikou** [comment]
can i play as Führer now

**Comment by PKPenguin321** [comment]
>Raw HTML interfaces (mostly PDAs and VV) will fuck up display of these letters

:-1: because of this, it should be addressed first

**Comment by optimumtact** [comment]
yes I am also opposed to this.

Realistically we should expose as config the set of allowable planes for
A) ic speech
B) names

This would allow a specific server to customise to their chosen target market as required.

**Comment by MrPerson** [comment]
I was reasonably sure this would get opposed, but I figured it was worth a stab and see what people thought.

**Comment by XDTM** [comment]
Minor issue, but people would be unable to specify people with unicode characters when using voice of god

**Comment by Ohagi-Chan** [comment]
Same with siccing your slimes on people

**Comment by kopoba** [comment]
Олег is watching you

**Comment by Michael-Ashfield** [comment]
This would make it quite difficult to call people by their name unless you ate 10/10 with your keyboard shortcuts for these fairly obscure and little-used characters.

**Comment by MrDoomBringer** [comment]
would make it harder to do any in-game mechanic that requires typing in someone's name, right? Ie searching for criminals on the sec console

**Comment by nero1024** [comment]
Not everyone has a keyboard that can punch in special characters or be arsed to set their input method to "US International keyboard". Lïké mè.

**Comment by MrPerson** [comment]
Those issues can be worked around, but frankly I don't think it's worth the effort.

**Pull request closed without merging**
