### PR TITLE
Replaces Xenomicrobes with Sulfuic Acid

### PR DESCRIPTION
**Pull request by GunHog**
- Xenomicrobes replaces with Sulfuric Acid in the Experimentor.

I have received feedback from the admins, and they feel logging has not quelled the abuse. 

_Hornygranny suggested making it turn people into simple animals, I will try to find a way for that to work!_

### CODE REVIEW

**Comment by WJohn** [comment]
Can we throw out the experimentor already, it's literally worse than telesci in that it's griefier and less useful in every single way.

**Comment by RemieRichards** [comment]
Make it Pacid.
Love me some pacid.

**Comment by GunHog** [comment]
Remieeeeeeeeeeeeeeeeeeeeee! Noooooo! I do not want it to be instakill-lel-death!

**Comment by RemieRichards** [comment]
Hehe.
Sacid is still my baby anyways.
it's just half the power of pacid :)

**Comment by GunHog** [comment]
Yes, we all know how you like to strip everyone! :P

**Comment by RemieRichards** [comment]
Come again? :S heh

**Comment by GunHog** [comment]
Buffing acid to strip people more effectively, and then the xenoblood PR for stripping people's shoes...

**Comment by RemieRichards** [comment]
yes I got the joke. I was playing :3

**Comment by Jordie0608** [comment]
http://keepachangelog.com/

**Comment by GunHog** [comment]
I hath laid a sacred changelog file upon thine altar, great one!

**Pull request merged**
