### PR TITLE
Fixes admin observer special radio keys double sanitizing input

### LINKED ISSUE #59859: Using .j to chat in character as an admin messes up some characters
## Round ID:

[164943](https://scrubby.melonmesa.com/round/164943)

## Reproduction:

Speaking through .j
image

Speaking in character
image

### PR DESCRIPTION
**Pull request by Wayland-Smithy**
## About The Pull Request

Moves `/mob/dead/observer/say()` message sanitize code to after the special admin radio keys logic that will also sanitize.
Changes an if else chain to a switch statement,

## Why It's Good For The Game

Fixes: #59859

## Changelog
:cl:
fix: Fixed admin observer special radio keys double sanitizing input.
/:cl:

### CODE REVIEW

**Comment by LemonInTheDark** [comment]
pretty sure both of the other say methods double sanitize, you should fix it while you're here.

Admittedly I think I'm the only one who uses them, but

**Comment by Wayland-Smithy** [comment]
Yeah you're right those are double sanitizing too.

**Comment by LemonInTheDark** [comment]
part of me is a little worried that this could be abused to embed like, javascript code in asay.

Maybe it would be better to handle this with early returns in observer.say(), rather then a sanitize arg? idk.

**Comment by Wayland-Smithy** [comment]
> this could be abused

Admins can abuse SDQL also but we don't code around that. Should they not just be dedmined for that kind of behavior?

Sure though I'll remove the `sanitize` args and the checking for it in the `/mob/dead/observer/say()` code since the whole special keys block early returns anyway.

**Pull request merged**
