### PR TITLE
Allows alt-clicking for some stuff

### PR DESCRIPTION
**Pull request by ghost**
In short:
1. You can alt-click lockers to lock or unlock them
2. You can alt-click breath masks to adjust them
3. You can alt-click baseball caps to flip them

Locker object verb is also removed

### CODE REVIEW

**Comment by PKPenguin321** [comment]
can't you not remove them but add them to a null tab so they can still be typed or whatever

**Comment by Xhuis** [comment]
I have never seen a verb typed with the exception of admins spawning things.

**Comment by Jalleo** [comment]
The ejecting of id or pen is typeable.

**Comment by Atskadan** [comment]
every verb IS typeable, jalleo, but everyone uses the verb tabs

**Comment by RemieRichards** [comment]
Don't remove the verbs ffs.
Keep them around in the Tabs and if not the BARE MINIMUM, give them null categories so they can be typed.

**Comment by MrPerson** [comment]
No one in the entire history of this game has ever or will ever manually type out "Toggle Lock"

**Comment by RemieRichards** [comment]
Yes, which is why I said that one can go away.

**Comment by Miauw62** [comment]
>type toggle
>hit up arrow a few times

you don't have to type it in full
also it has long since been etablished that alt-click is not intuitive for new players. (we need a way to make it obvious to them that alt-click does shit)

**Comment by Atskadan** [comment]
put it in the guide to new players section on the wiki :l

**Comment by Xhuis** [comment]
Flipping verb has been re-added, but not the locking one. The locking one was kinda pointless, and from what I can tell a good few people feel the same way

**Pull request merged**
