### PR TITLE
Tweak Item Placement and Some Doors in MetaStation Medbay

### PR DESCRIPTION
**Pull request by calmilamsy**
## About The Pull Request

This all revolves around the new MetaStation medbay. While the new design is nice, I have some issues with its item placement and doors.

- Moved HUDs and belts into the storage area.
- Moved the nitriles into the storage cabinet on the right, also stacked them like the HUDs and belts are.
- Moved the lathe and charger to the bottom left.
- Moved the vendors to the center, next to the entrances.
- Moved some of the stuff on the treatment center tables around, added a suture.
- Added two extra sets of HUDs and belts, as all stations have a couple spare.
- Moved the folder and stethoscope in the cryo room to be next to the tubes.
- Removed the extra mediwrench in storage. There is already a second one in the coldroom, a third is completely overkill.
- Named the coldroom airlock door.

## Why It's Good For The Game

- The HUDs and belts being in a frequently visited area by non-medical staff makes them easily stolen, no other map has them like this, so I've moved them to medbay storage instead.
- The lathe and charger were moved down to allow for a larger table, and to prevent crowding at roundstart as the nitriles were next to it.
- The vendors were moved to the storage entrances to create more room for placing tables. The lathe and charger took their old placement.
- Lots of stuff was piled onto the treatment center tables, so with the moving of the HUDs and belts, there was more space to use, so I spaced stuff around and added a suture.
- The extra HUDs and belts are there for MD promotions, or just extra MDs in general. We had them before, and on every other station, and there were times there were no belts for extra MDs.
- Moved the folder and stethoscope to de-clutter the bottom cryo table. Also makes more sense in my opinion.
- Removed the storage mediwrench because there are already four wrenches, including the ones in chemistry and virology.
- Every other door in medbay has a name for the room its attached to, so I've named this one too, to make it more obvious.

## Changelog
:cl:
tweak: Changed some item and machine positions in MetaStation medbay.
tweak: Add space cleaner to the operating room and medbay storage in MetaStation.
fix: Named the MetaStation medbay coldroom airlock appropriately.
/:cl:

### CODE REVIEW

**Comment by AlinaStarkova** [comment]
I spoke to Inept about the chemistry doors the other day, he very explicitly wants them to be science doors. just fyi

**Comment by AlinaStarkova** [comment]
Oh also you need to merge from master, one of my PRs that fixes a few mapping errors on meta med was just merged, so you have a conflict for it now

**Comment by calmilamsy** [comment]
> 
> 
> I spoke to Inept about the chemistry doors the other day, he very explicitly wants them to be science doors. just fyi

Ah, alright.

**Comment by EOBGames** [comment]
I'm happy to see most of these changes implemented, but I'm not budging on space cleaner. It was removed to give janitor some degree of relevance which is eroded very quickly if everywhere that can get a bit dirty is given a roundstart supply of cleaner.

**Comment by EOBGames** [comment]
> I spoke to Inept about the chemistry doors the other day, he very explicitly wants them to be science doors. just fyi

Also just as an aside, I made the chem doors sci-coloured to distinguish them in a small way- given this is now like, the 5th time it's been called out as bad and the third attempt made to change it, I'm past the point of caring.

**Comment by calmilamsy** [comment]
> I'm happy to see most of these changes implemented, but I'm not budging on space cleaner. It was removed to give janitor some degree of relevance which is eroded very quickly if everywhere that can get a bit dirty is given a roundstart supply of cleaner.

Sure, I guess. If there is no janitor, there is nothing stopping medbay from just making medisprays filled with cleaner if push comes to shove.

> Also just as an aside, I made the chem doors sci-coloured to distinguish them in a small way- given this is now like, the 5th time it's been called out as bad and the third attempt made to change it, I'm past the point of caring.

Maybe gave them orange trimmed doors?
I don't think we have orange trimmed sprites though, only engis full orange/yellow doors, sadly.

**Comment by calmilamsy** [comment]
Reverted my cleaner and door colour changes.

**Comment by AlinaStarkova** [comment]
> 
> 
> > I'm happy to see most of these changes implemented, but I'm not budging on space cleaner. It was removed to give janitor some degree of relevance which is eroded very quickly if everywhere that can get a bit dirty is given a roundstart supply of cleaner.
> 
> Sure, I guess. If there is no janitor, there is nothing stopping medbay from just making medisprays filled with cleaner if push comes to shove.
> 
> > Also just as an aside, I made the chem doors sci-coloured to distinguish them in a small way- given this is now like, the 5th time it's been called out as bad and the third attempt made to change it, I'm past the point of caring.
> 
> Maybe gave them orange trimmed doors?
> I don't think we have orange trimmed sprites though, only engis full orange/yellow doors, sadly.

someone is working on GAGS doors which will allow us to make doors of any colors, but they arent yet in

**Review by Maurukas — CHANGES_REQUESTED** [review]
This is reverting the changes to the SM piping from #59997, and I don't think you intend to do that. Can you re-merge master and resolve the diffs that are happening in the supermatter engine?

**Comment by calmilamsy** [comment]
> 
> 
> This is reverting the changes to the SM piping from #59997, and I don't think you intend to do that. Can you re-merge master and resolve the diffs that are happening in the supermatter engine?

I have no idea how that happened. Ill try fixing it without nuking my fork.

**Comment by calmilamsy** [comment]
Okay, that just broke things even more.
Great. Thanks git.

**Pull request closed without merging**
