### PR TITLE
Changes the construction of durands and phazons back to advanced capacitors and scanning modules.

### PR DESCRIPTION
**Pull request by Aranclanos**
pap back the fuck off??

### CODE REVIEW

**Comment by Razharas** [comment]
Id prefer any type of capacitor and scanner would go but the better the type the better the mech will be in result

**Comment by WJohn** [comment]
Yeah it's not exactly intuitive which type you have to use. At the same time I have no idea what the quality of these parts should even affect.

**Comment by GunHog** [comment]
Have it check for T2 or higher, so any set works?

**Comment by Razharas** [comment]
https://github.com/tgstation/-tg-station/pull/12036 <= A much better solution

**Pull request closed without merging**
