### PR TITLE
Cyborgs can fake-announce asimov when emagged

### PR DESCRIPTION
**Pull request by etherware-novice**
## About The Pull Request
Emagged borgs can announce asimov instead of syndOS lawset 

## Why It's Good For The Game
Lets emagged borgs be stealthier, while still not being completely indetectable if someone notices you arent responding to ai upload.

## Changelog

:cl:
add: cyborgs can fake announce asimov
/:cl:

### CODE REVIEW

**Comment by Shadowflame909** [comment]
This will be useful! Unless its a round with a different round start law set. But no one should be valid hunty enough to notice that....right?

**Comment by JohnFulpWillard** [comment]
Currently, Malf AIs have a zeroth law that they don't state, they have their default lawset which they can.
Now you're moving Emagged borgs to behave more like Malf AIs, which I disagree with for the following reasons:

1) Any Traitor can get an emag, and it's already incredibly powerful to have a borg on your side because of the access alone. If you take into account their module and how emags have infinite uses and can theoretically emag infinite borgs, and compare it to the rest of the Traitor uplink, I hope you can agree that they don't need another buff. It also turns the emag even more into the item you get just for borgs, and nothing more.

2) Hiding laws seems counterproductive to what we want out of Silicon. Malf AIs are able to get away with this because they're a high impact ruleset on par with Wizards, Nukies, and Revolutions, and because they're their own antagonist compared to any Traitor that can get an emag and convert a cyborg. It also makes cyborgs hiding laws way more common, which I don't find very interesting.

If another maintainer wants to disagree with my reasoning, they can remove the tag and (hopefully) give reasoning why, but I'm against this.

**Comment by msgerbs** [comment]
My counterpoint for this is that you already can fake asimov laws, it's just really annoying to do so. I don't see a problem with making it less annoying to do. If we want law announcements to be infallible they should probably not be indistinguishable from normal chat messages.

**Comment by dragomagol** [comment]
I agree with john, no need to buff emagged borgs

**Comment by GuillaumePrata** [comment]
This would cut on a really fun side of EMAGed cyborgs, making up an excuse to get away from people asking for your laws.

From making up laws on the spot, to just saying you have none, to calling them a dumbfuck non-human and that you don't need to follow their requests for stating laws or the direct way of just murdering them on the spot.

**Comment by zxaber** [comment]
Agree with JohnFulp; while this would be super helpful, having someone ask for your laws (usually) means you (or your VIP) already slipped up and you were seen doing something you shouldn't be doing. Figuring out your way around that obstacle is the penalty for the slip up.

**Comment by Mothblocks** [comment]
2 maintainers said they didnt want it

**Comment by LemonInTheDark** [comment]
John "Silicon Demon" fulp

**Pull request closed without merging**
