### PR TITLE
Gives the ORM a visual indicator showing which side is the input and which is the output

### PR DESCRIPTION
**Pull request by Wallemations**
## About The Pull Request
Gives the ORM a light on either side showing which is the input and which is the output, blue for input, red for output.
ORM

## Why It's Good For The Game
Useful for if anyone decides to move the ORM.

## Changelog

:cl: Wallem
qol: The ORM now has color-coded lights showing which side is the input and output. Blue for input, red for output.
/:cl:

### CODE REVIEW

**Comment by KonKonBreezeFox** [comment]
FINALLY

**Comment by Wallemations** [comment]
> Could you make the indicators different shapes?

I honestly have zero clue what I would be able to change these shapes to. They're dim lights, they're not gonna have like squares or circles in 'em

**Comment by Jacquerel** [comment]
Is there a reason this doesn't just have directional sprites?
It just feels a little weird for it to work this way when it depicts a little furnace with a belt leading either in or out of it 😅

**Comment by CPTANT** [comment]
> 

Maybe just have only one light for the input?

**Comment by Wallemations** [comment]
image
Emissives

**Comment by AlinaStarkova** [comment]
Definately make the indicators only show when unwrenched, seeing them at all times even when they cant even be rotated (its wrenched down and operational) is visual bloat we dont need to constantly see

that said im also tempted to try my hand at adding directional variations of this sprite, hmm, probably wont do it for awhile tho

**Comment by Wallemations** [comment]
> Definately make the indicators only show when unwrenched

That would defeat half of the point of the sprite.

**Pull request merged**
