### PR TITLE
Aliens roar when tailsweeping

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
Forgot to make them roar when they did the attack.

### CODE REVIEW

**Comment by WJohn** [comment]
Could I ask you to add the tail-smash sounds that cuboos also made for #12000? There's a sound for hitting humans and hitting cyborgs, and it adds extra satisfaction to the hit.

**Comment by Supermichael777** [comment]
make them say REEEEEEEEEEE.

**Comment by Memendia** [comment]
slowly this server will change into Colonial Marines.... ever so slowly..

**Comment by WJohn** [comment]
God no never get that shitty backwards RP in a PVP gamemode noise out of here reeeeeee

**Comment by Memendia** [comment]
It fun shitty backwards RP in a PVP gamemode though

**Comment by WJohn** [comment]
Aw, I was hoping for the extra sounds. Oh well.

**Comment by KorPhaeron** [comment]
@WJohn 

I'd have to redo how repulse works for that, I think

**Pull request merged**
