### PR TITLE
high passed ship ambience

### PR DESCRIPTION
**Pull request by actioninja**
## About The Pull Request

High passes the ship ambience sound so it's no longer an outrageously loud bass rumble louder than nearly every other sound in the game

## Why It's Good For The Game

I'm working on some new sounds that have a shitload of low end and I don't want them adding with the stupid ship ambience that's currently there and blowing out people's eardrums.

## Changelog
:cl:
soundadd: ship ambience is no longer an outrageously loud bass rumble
/:cl:

### CODE REVIEW

**Comment by wesoda25** [comment]
I like it

**Comment by ShizCalev** [comment]
Definitely hear a lot of white noise in it now.

**Comment by actioninja** [comment]
That's how it sounded before. If you want to find a better sound for it, go for it, but it's a really low quality sound that you can't really hear clearly because it's got this ridiculously loud <100hz roar.

**Comment by PKPenguin321** [comment]
The super bass sounds have had me muting ambiance for years now so I'm glad to see them toned down a bit

**Pull request merged**
