### PR TITLE
Cyborg Balance

### PR DESCRIPTION
**Pull request by Robustin**
:cl: Robustin
balance: The Syndicate Cyborg LMG now costs 5x more energy to fire.
balance: The Secborg disabler now costs 10x more energy to fire and can longer be used to harm. The Secborg laser now costs 3.5x more energy to fire.
removal:  The Secborg baton has been removed.
/:cl:

Another long overdue change. Currently Syndieborgs can fire over 1,200 rounds before needing to recharge their default cell (it was over 1000% more efficient to shoot your gun to travel through space than it was to use the Ion Thrusters). Secborgs with a high-cap cell (available at roundstart) could fire 300 disabler rounds. 

In addition,  the secborg baton poses a problem. People understand that borgs can flash them with little warning. And people also understand what a borg shooting at them means. Even an officer has to "show" their baton to use it. The secborg baton has no "tell" and with one of the longest stuns in the game it is part of the frustration associated with Secborg strength. Furthermore it also the notorious source of Secborg harm, 15 brute allowed these borgs to quickly and efficiently kill crewmembers when its laws (frequently) allow. 

We already (regrettably) gave flashes a long stun. The secborg can use this in combination with the disabler to detain suspects. This PR also has the effect of removing all sources of harm from an un-hacked Secborg - if it wants to kill people on its own it will have to exercise at least a sliver of creativity.

### CODE REVIEW

**Comment by Repukan** [comment]
Syndieborg is fine when an AOE burst shot can cripple it to death in most cases.

**Comment by kevinz000** [comment]
dumb as fuck.
Syndieborgs are already easily countered.
And as for secborgs why would you remove their melee hard stun?
What the fuck?

**Comment by Robustin** [comment]
Every gun in the non-Cyborg gun game has a considerable cost for firing it Kev.

Cyborgs, for all their advantages, have demonstrated absolutely no need to be exempt from this rule.

**Comment by jughu** [comment]
If people can counter syndie borgs without problem why not secborgs? Lol

**Comment by optimumtact** [comment]
@KorPhaeron @ausops @Armhulen disable secborgs

**Comment by praisenarsie** [comment]
^

if you want them enabled, at least be a semi-decent headmin and poll it?

**Comment by CPTANT** [comment]
Disable secborgs.

**Comment by AdamElTablawy** [comment]
consider allowing someone to bloody examine a secborg to see what module it has equipped

**Comment by Robustin** [comment]
It will always have the baton equipped Adam, the whole point is you never know when theyre going to thwack you with it.

**Comment by Bawhoppen** [comment]
We need less of number balance changes, and more of actual overhauls

**Comment by Supermichael777** [comment]
How about a cyborg baton variant. Put in a delay, overlays, and audio cues to make it obvious that its in click to win mode.

Or make cyborg flashes easier to repair/replace because they will burn through it/get lightly grazed by rads and fucked.

Modual overlays in general would save a lot of grief.

**Comment by kevinz000** [comment]
@AdamElTablawy YOU ALREADY CAN!

**Comment by KorPhaeron** [comment]
Secborg and syndiborg changes do not belong in the same PR whatever else happens

**Comment by Ausops** [comment]
i thought they were disabled after the week long run, they shouldn't be enabled

**Comment by imsxz** [comment]
@kevinz000 their flash is a melee hard stun. it will work fine against most targets. god forbid we make secborgs weak to melee combat when against eye protection

**Comment by davethwave** [comment]
They should be enabled on Bagil I believe, it's been a week or so since I've been on but they should still be there, also a good idea on the nerf Robustin.

**Comment by davethwave** [comment]
By the way if you can try to revive the engineering PR you did a long while back https://github.com/tgstation/tgstation/pull/24564 or try to integrate some of the mechanics like the power to points or money system you had and the tools from it I think it would be possible now. Now that techwebs have been added a buff to engineering probably wouldn't look out of place.

**Comment by Robustin** [comment]
Secborgs are dead, so I'll turn this into a Syndieborg one when I get around to it

**Pull request closed without merging**
