### PR TITLE
Removes Sulfuric Acid requirements from computer parts

### LINKED ISSUE #34905: CPU boards from computers still need acid to make
Issue reported from  Round ID: 82490 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

I'm pretty sure we removed the need for acid

### PR DESCRIPTION
**Pull request by epochayur**
See title

:cl: Epoc
tweak: Removed Sulfuric Acid requirements from computer parts
/:cl:

because no for sulf for the lathes I guess, hopefully I beat cyberboss to it this time
Fixes #34905

### CODE REVIEW

**Comment by epochayur** [comment]
pretty sure this doesn't need the revert tag?

**Comment by praisenarsie** [comment]
read the tag again

**Comment by epochayur** [comment]
woops looks like i've got brain problems

**Comment by ExcessiveUseOfCobblestone** [comment]
Autolathes should be able to hold acid instead.

**Review by Cyberboss — APPROVED** [review]

**Pull request merged**
