### PR TITLE
Reverts sprite changes done on crates

### PR DESCRIPTION
**Pull request by OverwatchVoice**
## About The Pull Request

Reverts [#75785](https://github.com/tgstation/tgstation/pull/75785)
preview

## Why It's Good For The Game

The sprites introduced in the afforementioned PR have been met with a mixed reception.
This PR is here to see if there's enough demand for them to be changed back.

## Changelog
:cl:AmBush

image: Recently added crate sprites have been reverted.

/:cl:

### CODE REVIEW

**Comment by kinneb** [comment]
ping me on discord if this gets merged because it (sadly) obsoletes my sprite pr: https://github.com/tgstation/tgstation/pull/75858

**Comment by LSommers** [comment]
> ping me on discord if this gets merged because it (sadly) obsoletes my sprite pr: #75858

"Did you get crates unmerged?"
"Yes."
"What did it cost?"
"Kinneb sprite PR."

**Comment by optimumtact** [comment]
if the sprite tainers merged it despite objections in the first pr there is zero chance they would care about your opinion a second time, so what world would this achieve anything

**Comment by DATA-xPUNGED** [comment]
> if the sprite tainers merged it despite objections in the first pr there is zero chance they would care about your opinion a second time, so what world would this achieve anything

Because now we've gave the new crates time to settle, to prove that it wasn't just nostalgia, and people STILL don't like them. That's why.

**Comment by optimumtact** [comment]
it has been four days that is not enough time for anything to settle at a minimum you would be looking at a month.

**Comment by YehnBeep** [comment]
> if the sprite tainers merged it despite objections in the first pr there is zero chance they would care about your opinion a second time, so what world would this achieve anything

Why add the do not merge label if this is the case? Shouldn't it be left to them to decide if they should flag it so or not?

**Comment by optimumtact** [comment]
because the amount of drama it caused has meant everyone trying to do their best originally have stepped back, so this is now my problem.

**Comment by TheVekter** [comment]
This bullshit caused at least one spritetainer to step down if not more, please stop being fucking childish about sprites.

At the end of the day, the only people who's opinion matters on sprites are the maintainers, who are actively working to set a specific look that's in line with their vision and a general perspective change called The Wallening.

It's not going to be reverted. You can either accept that you've done what you can to try and influence the game and you're just going to not like how they look for the foreseeable future, or you can be petulant about it and kick and scream until oranges gets sick of you and gitbans you.

It's definitely not going to be changed by someone who has literally never contributed to the project and in fact created their own repository simply titled "crate-revert" with the sole purpose being to remove someone's work because they don't like it.

image

I don't think you're here to be productive, but if you are, a suggestion? Make changes to what's there. The basic look is locked in and will not be changed, so if there's things that you don't like about them, do what you can to improve them.

**Comment by ExcessiveUseOfCobblestone** [comment]
if it isnt broke, do not PR a kneejerk revert without asking someone.

**Comment by YehnBeep** [comment]
So, also as someone who does not have a strong opinion on new crates vs old crates:

I do not think the PR maker was particularly impolite or uncivil so as to warrant this level of abuse.

**Comment by optimumtact** [comment]
I dunno... after all they are a beestation player

**Comment by Davidththird** [comment]
claims "dont revert it isent broken"
pr itself tried to fix something that wasn't broke
truely double standards at play here

**Comment by OverwatchVoice** [comment]
> because the amount of drama it caused has meant everyone trying to do their best originally have stepped back, so this is now my problem.

If an unwarranted change faces a lot of negative feedback, you don't use the drama stemming from it as an excuse to not make changes to it.

Dismissing everything I said with "They used to play beestation so that must mean they're just nostalgic" is plain rude, and shows your stance is that of degrading others instead of trying to face legitimate criticism constructively.

**Comment by optimumtact** [comment]
I don't need to face criticism i'm the headcoder i can do what I want

**Comment by Timberpoes** [comment]
He's already headcoder. There's nothing you can do to stop him.

**Comment by redlink2579** [comment]
Honestly, the sprite is awesome but they are just too big in my opinion, I don't think revert the change is going to do much better

**Pull request closed without merging**
