### PR TITLE
QoL change for derelict drones

### PR DESCRIPTION
**Pull request by Midaychi**
Scatters random maint loot around derelict zlevel, and adds one spot to clown shuttle and one to dj station.
Adds the boards for circuit imprinter, protolathe, and rdconsole
Adds and scatters almost enough stock parts to build those three machines around the derelict.
(You should be able to make the rest with the autolathe)
Drones should be able to salvage enough metal and glass and wires to make and feed these machines, or steal it from the station via teleporter.

Mapmerged.
I compiled and tested, but please check it out too incase I accidentally removed or overwrite something important.

### CODE REVIEW

**Comment by lordpidey** [comment]
I like it.

Would it also be possible to add an "air mix" room in derelict atmos, so that the drones can at least in theory make a livable station?

**Comment by Midaychi** [comment]
Maybe, but not in this pr. Currently, drones can make a piping device, and strategically pilfer gasses from the station when nobody's looking.
Bolting on gas tank rooms might make the derelict too lucritive for station crew.

**Comment by Supermichael777** [comment]
what about sulphuric acid?

**Comment by Jalleo** [comment]
Could a damaged shuttle be setup that connects to the abandoned mining station while adding a smelter and a pickaxe there? Also i believe the drones would be able to make a portable chemistry dispensor from those parts if they have a circuit so giving them 40 units of acid in a beaker should be enough

**Comment by Midaychi** [comment]
Added 6 new low rate maint spawners, upgraded an existing one to be larger.
Added two standing air tanks with a little bit of air in them. It's not much but it's a start. Steal the rest from the station like a pro.
Added a shovel and ore satchel to the clown shuttle, because that's something they might have also had for their trip.
Added nutrimax/seed vendor to the ex-security area. Good soviets grow food for their fellow man. (there were a space and cultivator somewhere but they've gone missing. Huh!)
Added a beaker of sulfuric acid.. somewhere. I forgot. It's probably not important.

**Comment by Midaychi** [comment]
Good for merge. I'm not making any more changes to this pr unless it's rebasing to fix merge conflicts, or if its fixing any bugs that people bring up.

**Pull request merged**
