### PR TITLE
remove furfaggotry/weeaboo degeneracy

### PR DESCRIPTION
**Pull request by roleplaylover4000**
i'm not goofball btw

### CODE REVIEW

**Comment by RemieRichards** [comment]
Sure you're not.

**Comment by Iamgoofball** [comment]
This wasn't me but i approve of this PR

**Comment by Iamgoofball** [comment]
Even I don't work off master.

**Comment by jughu** [comment]
you forgot,
Corgi suit.
Carp Suit.
Easter bunny suit.

**Pull request closed without merging**
