### PR TITLE
YOU GO TOO FAR

### PR DESCRIPTION
**Pull request by Iamgoofball**
Fixes the description on the toilet.

### CODE REVIEW

**Review by Cyberboss — DISMISSED** [review]

**Review by Cyberboss — APPROVED** [review]

**Comment by F-OS** [comment]
what happened to the meme pr tag

**Comment by DoctoreMad** [comment]
It was normalnormative and removed to applease the transgods.

**Comment by F-OS** [comment]
cis scum

**Comment by Dorsisdwarf** [comment]
I dont seem to get whatever joke this is trying to make.

**Comment by xxalpha** [comment]
It's a reference to a web comic. In short, bad memes.

**Comment by GunHog** [comment]
It is a ref to this: http://dresdencodak.com/2009/09/22/caveman-science-fiction/

**Comment by KorPhaeron** [comment]
Good compromise might be putting a toilet with this desc in the ash walker base

**Comment by Iamgoofball** [comment]
Wow reopen when

**Pull request closed without merging**
