### PR TITLE
gives hop his own space suit (kinda)

### PR DESCRIPTION
**Pull request by Fikou**
## About The Pull Request
the hop locker now has the old space suit (basically eva suit but with a little better fire/bio/acid protection and flashproof)

## Why It's Good For The Game
gives hop his own suit for emergencies without making it too much snowflake
makes sense that nanotrasen would give the hop their old quality suit

## Changelog
:cl:
add: The Head of Personnel's locker now contains a space suit we found in our storages.
/:cl:

### CODE REVIEW

**Comment by Dawson1917** [comment]
HoP already has access to EVA which is right across from his office. There were a lot of reasons for why Mr. Paperwork shouldn't have a personally reserved hardsuit in the discussion for the previous PR that wanted to add his own suit. All the other heads have hazards specific to their workplace that warrant a personal hardsuit - the HoP shouldn't be in hazardous situations

**Comment by MrFluffster** [comment]
Make a proper sprite for it you lazy butt.

**Comment by Fikou** [comment]
> Make a proper sprite for it you lazy butt.

literally the whole point of it is to be the old space suit

**Comment by Fikou** [comment]
> HoP already has access to EVA which is right across from his office. There were a lot of reasons for why Mr. Paperwork shouldn't have a personally reserved hardsuit in the discussion for the previous PR that wanted to add his own suit. All the other heads have hazards specific to their workplace that warrant a personal hardsuit - the HoP shouldn't be in hazardous situations

this isnt a rearmored caps swatsuit or a hardsuit, just a regular space suit without anything fancy
also hopline explosions happen all the time and hop is like the second biggest target after cap

**Comment by optimumtact** [comment]
What is it with people and adding a space suit to the HoP? I have denied this so many times

**Comment by Fikou** [comment]
> What is it with people and adding a space suit to the HoP? I have denied this so many times

i dont know ive seen it only pr'd once and it was a caps swat suit with a few stat changes

**Comment by Eaglendia** [comment]
> also hopline explosions happen all the time and hop is like the second biggest target after cap
So let him deal with it. The HoP should be in charge of their own safety. Being a *consistent* pick-off for free AA and a gun is the player's fault. There's a lot of things the HoP can do to make themselves a harder target to bag, and not having nice things that some other heads of staff have is kind of core to the role's identity.

**Comment by Fikou** [comment]
> So let him deal with it.
this lets him deal with it, most people wont do anything about the explosion except screaming ;help hopline, but this might make the hop think alright time to fix this, grab the suit and fix it

**Comment by MrFluffster** [comment]
> > So let him deal with it.
> 
> this lets him deal with it, most people wont do anything about the explosion except screaming ;help hopline, but this might make the hop think alright time to fix this, grab the suit and fix it

He can grab the one from the room right in front of his office, that he has access to

**Comment by kriskog** [comment]
Why is an old spacesuit better than a modern one?

**Comment by wesoda25** [comment]
hello i am play space station and i am think this is dumb

**Comment by cacogen** [comment]
but why? just give yourself EVA access

**Comment by HomocidlePancakes** [comment]
Ok. Ok. Here is a compromise. What if we gave HoP his custom suit, BUT put it in EVA?

**Comment by PKPenguin321** [comment]
I honestly can't believe this is real, this was the sarcastic joke argument back when we were arguing about whether the RD should get a hardsuit

**Comment by Akrilla** [comment]
I feel like if the hop were to ever get their own space suit, having it just the old standard one, and stuffed in a locker looks quite sad :pensive:

**Comment by Tlaltecuhtli** [comment]
real hops just fax centcomm request for space immunity

**Comment by Fikou** [comment]
h

**Pull request closed without merging**
