### PR TITLE
Riot Shotguns can be bought from Cargo

### PR DESCRIPTION
**Pull request by genessee596**
## About The Pull Request

**THE WHAT:**
This PR adds Riot Shotguns to the Cargo supply catalog under the 'Armory' tab. These shotguns are identical to the ones that spawn in the armory at roundstart. Riot Shotguns can be bought in a three-pack for 6000 credits, or a single-pack for 2500 credits.

**THE HOW:**
Simply adding a few lines of code to the 'packs.dm' file makes this simple PR possible.

**THE WHY:**
Firstly, I found it odd that you can't get Riot Shotguns from anywhere except the armory, and even then you only get three or four to work with. So here we are.

Secondly, Cargo has access to a large amount of ranged weaponry; however, the only weapon that they can buy that is capable of using shotgun shells is the Combat Shotgun, which is both unwieldy and makes security extremely nervous -- which is justified, considering that it can drop a person to crit in literally one second ( Fires once per 0.5 seconds, two buckshots point-blank makes someone go horizontal ). The Riot Shotgun aims to solve this by being more versatile to store (can be sawn-off, unlike the combat shotgun), as a cheaper alternative to the Combat Shotgun, and as a firearm that makes security a little less antsy than the Combat Shotgun does.

## Changelog
:cl:
add: Riot Shotguns can be bought in Cargo for 6000 credits for a 3-pack, or 2500 credits for a 1-pack.
/:cl:

### CODE REVIEW

**Comment by genessee596** [comment]
First PR ever, please leave feedback in the comments!

**Comment by Repukan** [comment]
Why would cargo ever need more versatile shotguns?

**Comment by PKPenguin321** [comment]
Are these not just worse combat shotguns? I think it's fine

**Comment by Fikou** [comment]
you can sell riot shotguns for bounties i think

**Comment by ExcessiveUseOfCobblestone** [comment]
now bump up combats 😏

**Comment by Dorsisdwarf** [comment]
>you can sell riot shotguns for bounties i think

The bounty is 5,000 for 2

**Comment by Shapsy** [comment]
Riot shotguns can be stowed in armor and sawed off so they're not strictly worse than combat shotguns

**Comment by genessee596** [comment]
> now bump up combats 😏

Actually, that was going to be the next PR I did, haha

**Comment by PKPenguin321** [comment]
>Riot shotguns can be stowed in armor and sawed off so they're not strictly worse than combat shotguns

Oh, well I figured combat shotguns could do that too but idk

**Comment by Tharcoonvagh** [comment]
make the compact shotgun researchable

**Comment by Fikou** [comment]
> > you can sell riot shotguns for bounties i think
> 
> The bounty is 5,000 for 2

yeah but whats the sense that centcom wants to buy riot shotties from the crew but also sels them

**Comment by Dorsisdwarf** [comment]
> 
> 
> > > you can sell riot shotguns for bounties i think
> > 
> > 
> > The bounty is 5,000 for 2
> 
> yeah but whats the sense that centcom wants to buy riot shotties from the crew but also sels them

I was confirming what you said dude

**Comment by Dawson1917** [comment]
cargo needs less guns not more

especially not ones they can stick in their backpacks

**Comment by carlarctg** [comment]
cant wait for valider cargo techs and QMs to not have to be horribly blatant lugging a shotgun around, now they can just pocket shotgun antags!

**Comment by dee-dubya** [comment]
I can't wait to storm cargonia and for them all to have sawn-offs in their backpacks, ready to self-antag against the incoming security force.

**Comment by ExcessiveUseOfCobblestone** [comment]
killing security for doing their job is a bannable offense though 😏

**Comment by PKPenguin321** [comment]
IC issue

**Comment by ExcessiveUseOfCobblestone** [comment]
gonna btfo cargo stuff until budgets get fixed

**Comment by carlarctg** [comment]
@ExcessiveUseOfCobblestone budgets got fixed
still don't like the idea of every QM having a sawn off riot shotgun in their backpack

**Comment by optimumtact** [comment]
I just dont' really see any need for this one

**Pull request closed without merging**
