### PR TITLE
flashbangs no longer damage blob tiles

### LINKED ISSUE #15178: Flashes don't affect the blob.
Flashes don't affect the blob, only flashbangs specifically affect it. Meaning making flash powder grenades in chemistry is completely useless.

### PR DESCRIPTION
**Pull request by silicons**
anturkey no fun allowed
fixes #15178

paging @KorPhaeron 

🆑 
rscdel: flashbangs no longer hurt blobs
/:cl:

### CODE REVIEW

**Comment by CPTANT** [comment]
Blob is super weak currently, and flashbangs damaging blobs makes no sense whatsoever.

**Comment by Robustin** [comment]
This needs to happen, but only once there is an effective AOE anti-blob weapon that isn't an Xray laser.

**Comment by CPTANT** [comment]
With how shit blob currently is you don't need it.

**Review by Cyberboss — APPROVED** [review]

**Comment by kevinz000** [comment]
Eh cptnt is right (for ONCE LOL) @Robustin we can add another aoe weapon when blob isn't an utter joke

**Comment by Robustin** [comment]
Blob is mostly a joke due to scaling issues. At certain breakpoints it goes from "joke" to "incredibly powerful".

I'd much rather see you take a crack at that, increase passive chem generation at the server pops where the blob has the worst situation (i.e. right before 2bleb is triggered) and decrease it after the breakpoint where the blob has the best situation (i.e. right after 2bleb is triggered).

**Comment by Hatfish** [comment]
finally sec will finally stop flashbanging everyone trying to fight the blob, that's probably the worst part of fighting blobs.

**Comment by Repukan** [comment]
Maybe when techwebs are finished we can add AOE weapons in combat specialist path.

**Comment by kevinz000** [comment]
@Hatfish you forgot that with the right people wit hflashbangs they can easily destroy half the blob.

**Comment by CPTANT** [comment]
I've solo'ed blobs like this. If you are sec just grab a box of flashbangs and lots of guns. Then start spamming those flashbangs while you duel wield laser the core.

**Comment by YakumoChen** [comment]
Yeah blob is a complete joke unless crew is completely incompetent. As I have outlined on the forum https://tgstation13.org/phpBB/viewtopic.php?f=9&t=12964 blob needs some real buffs and changes to not make it the same every time.

This is every single blob round that has ever happened:
Blob spawns
Blob gets maybe a node and a factory and the point thing before the blob alert goes off
AI finds the blob
Crew rushes the blob with the entire armoury, welding tools, and whatever else
If the crew is competent or blob is shit the blob dies
otherwise the blob will start to grow despite crew fighting it
science must research xray lasers and mining has to deliver or else the blob wins

**Comment by KorPhaeron** [comment]
Changelog

**Comment by BeeSting12** [comment]
Just use bombs lmao. They affect all but the strong blob tiles.

also theres a tip of the round relating to this that needs removal

**Pull request merged**
