### PR TITLE
Re-adds cloning, as a body-only, simpler, researchable option

### PR DESCRIPTION
**Pull request by XDTM**
## About The Pull Request
Re-adds a greatly simplified version of cloning, which is only able to clone bodies from dna sequences. It is unlocked by the genetics node in techwebs, the same that unlocks dna scanners.

How does it work:
- There are two machines: the cloning console and the cloning pod. Each can be connected to multiple of the other, so you can have one console managing multiple pods or multiple consoles managing the same pod (for whatever reason). They are connected to each other via multitool, and there is no area or range limit.
- The way to obtain cloning records is via the cloning scan-disk: simply print one from the protolathe, slap it on someone to scan their dna sequence, pop it in a console, and either save it for later or use it to initiate the cloning procedure.
- Clones generated by a cloning pod are, of course, mindless, but can be used to harvest organs, as test subjects, or as backup bodies for people whose original is no longer an option.

The new UI:
clonery

## Why It's Good For The Game

Cloning is a sci-fi staple and it would be a pity to not have it in some form in this game.

This implementation should not cause the issues that caused the removal of original cloning, since it's not a revival method, and any healing procedure that requires a new body could already be done by using monkeypeople.

## Changelog
:cl:
add: Re-added cloning, as a researchable option under Genetic Engineering.
add: Cloning will now always create mindless bodies.
add: To use cloning, simply create a cloning console and a cloning pod and link them with a multitool; create a dna scan-disk, slap it on someone to scan their DNA, and use it in the cloning console, where you can save the record or use it for cloning.
/:cl:

### CODE REVIEW

**Comment by Tlaltecuhtli** [comment]
what if medbay just had a dna console and monkey people....

**Comment by trollbreeder** [comment]
Does this mean we can have experimental cloners back?

**Comment by XDTM** [comment]
Yes, if this PR is merged i'll remake the ruin with this version (plus the experimental cloner gimmick, of course)

**Comment by trollbreeder** [comment]
Oh thank god. This is the best timeline after all.

**Comment by Time-Green** [comment]
Great PR! It paves the way to a different kind of cloning, where you could perhaps extract DNA from fossils or something and create t-rex people.

Maybe make it consume water and carbon? That way it isn't 100% free

**Comment by itseasytosee** [comment]
I think there should be a consumable of some sort. Synthflesh seems like a good option but maybe at higher levels, it should be able to use more common things like gibs, nutrients, and blood.

**Comment by pireamaineach** [comment]
Too easy once more to bring people back into the round.
You shouldn't a brain transplant away from, "like nothing happened!"

Still an improvement I guess, but I don't see why we're back-tracking from the removal.

**Comment by XDTM** [comment]
I started from the premise that you could already do that with monkeys and mutadone, so this wouldn't be a huge change from that. If it does become problematic in the sense that it mkaes normal healing obsolete, some cost or speedbump can be added to the cloning process.

**Comment by pireamaineach** [comment]
If a body is so unrecoverable that they need a genetics body, the shouldn't get to retain their identity perfectly.

A better idea is making plastic surgery use text inputs rather than randomised names.

**Comment by Qustinnus** [comment]
It might be interesting to make the pod a plumbing machine.

**Comment by Ziiro** [comment]
If you want to get plumbing involved, just have it require synthflesh to make a body

**Comment by BadSS13Player** [comment]
> If a body is so unrecoverable that they need a genetics body, the shouldn't get to retain their identity perfectly.
> 
> A better idea is making plastic surgery use text inputs rather than randomised names.

You can just scan it and print an injector to use on the monkeyperson.

**Comment by optimumtact** [comment]
I'm not ready to allow this PR yet.

Maybe in another month or so.

**Comment by trollbreeder** [comment]
not cool oranges, this was a good PR

**Comment by Ziiro** [comment]
24 hour rule

**Comment by optimumtact** [comment]
Sorry troll, but I don't believe people have had enough time to adjust to the meta yet. It's still shaking out.

once we know where we are, we can decide where to go from there.

**Comment by pireamaineach** [comment]
This P.R. is stuck in the out-dated logic that we need cloning in some form. Medic mains would disagree.

**Comment by Time-Green** [comment]
> This P.R. is stuck in the out-dated logic that we need cloning in some form. Medic mains would disagree.

I'm a medic main and I'm fine with it. This locks cloning behind techwebs and would still require a competent medical doctor to do the brain swap and defibrillate. I do think it could be made harder by adding a constant chemical supply and or giving the clones some sort of debuff.

**Comment by XDTM** [comment]
Mind you, i was definitely on board with the removal of original cloning, and the author said that they would have no problem with body-only or experimental cloning but since it was tied to normal cloning code it would require a rework to simplify it (hence, this PR). 
@optimumtact , i'd ask you to reconsider mostly for this reason.

Plus, I thought that the current meta of making monkeypeople as spare bodies is really janky and unintuitive to newcomers, and i wanted to make a more official way of replicating human bodies.

**Comment by pireamaineach** [comment]
SS13 is not intuitive to newcomers, and it shouldn't be. I think monkey cloning is perfect in it's disadvantages and knowledge requirement.

Custom input facial surgery though...

**Comment by PKPenguin321** [comment]
While I do really want this I think oranges has a point, just come back in a month. No big deal

**Comment by cacogen** [comment]
Really like the new UI. The disk itself doing the scanning is kinda tacky and Goof-tier though. Either way, this deserved to be pulled now.

**Comment by Dennok** [comment]
> A better idea is making plastic surgery use text inputs rather than randomised names.

Rename potions from xenobio.

and you can return your name by geneticks if body dont gibbed.

**Comment by cacogen** [comment]
>Rename potions from xenobio.

Only luminescents with a pink core in them can make these iirc which makes them fairly rare when compared to surgery

**Comment by Dennok** [comment]
> > Rename potions from xenobio.
> 
> Only luminescents with a pink core in them can make these iirc which makes them fairly rare when compared to surgery

I think all understand, why surgery cant give you any (chief, cap,HOS,HOP) name, it's too easy to acquire. And locked by nothing. Just need someone to operate you.

Xeno locked by time. Get luminescent not too hard. Here 33.3% that you get it on mutating, and slime2slime mutation instant. And at last if you dont want be a slime, you can return to human form by using green extract.

**Comment by cacogen** [comment]
fair enough

**Comment by pireamaineach** [comment]
Just lock names which are already on the manifest, lol.

**Comment by Dennok** [comment]
> Just lock names which are already on the manifest, lol.

Yes, i see it.
Mad surgeon hunt on people and force change names on `clown`

**Comment by pireamaineach** [comment]
Epic surgery change.

**Comment by WarlockD** [comment]
What if instead of sythflesh you have to load up monkey cubes?  It be just a genetics pod that does a UI+UE injection.  Make it independent from the DNA console so you have to have genetics get the Ui+UE disk, and medical uses the disk to make the clone.  Otherwise the pod just makes a randomized human body.

Honestly, I would hold of on any kind of clone copying system till someone sits down and generalizes the DNA system.  That is make every creature have DNA to make Corgi/Xeno/lizzard hybrids.  Though that amount of work is insane.

**Comment by stylemistake** [comment]
@optimumtact I think it's time to revisit this PR.

**Comment by optimumtact** [comment]
I don't believe we need it, people seem to have adapated sufficently

**Comment by XDTM** [comment]
Honestly the only reason i'd want this now is to replace monkey-cloning. It's unconventional and fun, but its role should be as a creative solution, not the main body replacement method.

**Comment by ExcessiveUseOfCobblestone** [comment]
cloning already exists indirectly anyways if you can interact with genetics.

just human a monkey > brain replace > UI/UE edit.

**Comment by PKPenguin321** [comment]
right but if it's the same thing but less cool then why not

**Comment by XDTM** [comment]
The "just human a monkey" step seems like making a ghetto option the only option. Kinda like if security had no handcuffs and had to craft cablecuffs instead.

**Comment by cacogen** [comment]
monkeying was how you'd revive people before cloning

**Comment by trollbreeder** [comment]
i dislike becoming a john doe monkey if my head gets removed from my body and my body gets spaced but hey, lizard/human abomination!
also it's largely convenience and monkeys are technically faster because empty clones take time to make while monkeys go cube, water, mutadone, debrain, rebrain, defib, honk

**Comment by ExcessiveUseOfCobblestone** [comment]
not sure how tossing a body in then AFK is cooler than literally editing genomes (actively) to recreate and then transferring a brain (actively) to revive a player and keep their old identity.

Not sure how that's more "ghetto" either outside of the fact the activity is no longer a complete medical activity unless you steal boards.

Either way, i'm not interested in old-cloning and not sure I will find myself in a position where I'd want it back. I would be fine with making the active revival methods more "interesting", whatever that may entail.

**Comment by XDTM** [comment]
The ghetto bit is that, if you asked an outsider how a futuristic space station how they make more bodies, i'm confident they'd go with some sort of cloning technology, and not printing monkey cubes made from plants and then injecting them with a medicine that cures genetic disabilities.

Again, a close comparison is handcuffs and cablecuffs. One is made for the security's job, the other is fashioned from stuff whose primary use is something else. Yes, the second can pretty much replace the first, but it'd feel odd for security to look for cable coils and craft a bunch of cablecuffs to do their job.

Also, **i'm absolutely in NO way advocating for old cloning**, only the empty cloning part which would still require the brain swap surgery to be used for revival. Honestly i'd be fine with making the body random as well to make it completely parallel to using monkeys, it's just that it wouldn't make much sense for _cloning_ technology.

**Pull request closed without merging**
