### PR TITLE
RIP TRAVEL MODE, ALL HAIL EVA MODE

### PR DESCRIPTION
**Pull request by Robustin**
Always bugged me but I finally remember to do something about it.

Travel mode = Go slower = Super un-intuitive 

EVA mode = Wow this mode actually describes what it does for me

Also adds a few words to each mode change to describe what they actually do in case they don't know what EVA stands for. 

Example: **"You switch your hardsuit to EVA mode, sacrificing speed for space protection."**

### CODE REVIEW

**Comment by lzimann** [comment]
isn't there an action button for that aswell that would need to be changed

**Comment by coiax** [comment]
If it's a well designed action button, it would just call the procs to do that.

**Comment by Robustin** [comment]
If you mean the button description it just says "Change Helmet Mode", these are just descriptions and messages the user gets.

**Comment by PKPenguin321** [comment]
Probably easier to just rename the action button, tool tips system allows you to effectively stuff descriptions of the actions in there

**Comment by Robustin** [comment]
"Change helmet mode" suffices for now, I always tracked it in my chatbox anyway.

**Comment by Lumipharon** [comment]
robustin, for the love of all that is good, could you also remove the lights from eva mode?
There is literally, LITERALLY no beneficial reason for a nuke op to have lights on, EVER, let alone in space, where it's 100% illuminated to begin with.

**Comment by duncathan** [comment]
i really don't think the competitive semantics balance is something we should be concerned about, @Dorsisdwarf

**Comment by Robustin** [comment]
I could remove it but this was going to be a minor change. Plus at least lights gave you a nice visual indicator you were in space mode and they would be off when you needed to be inside and stealthy anyway.

**Comment by Lumipharon** [comment]
If you don't wan it clogging this pr that's fair enough, but there is no logic in giving nuke ops who all come standard with nvg's, big bright lights that literally serve only to make it easier for the crew to murder them.

And there are plenty of times you want to be in eva mode on station - ie: in bombed out areas like after killing comms, when entering or leaving the station etc.

**Comment by HankMoodyExperience** [comment]
>admins literally have to hold the new player nuke operative hands this hard

**Pull request merged**
