### PR TITLE
Removes drone overlays and the associated code

### LINKED ISSUE #20284: Drones can't see more than 1 tile of Ash Drakes
(Drone (729)) (?) (PP) (VV) (SM) (FLW) (TP) (REJT): drones see only 1 tile of lesser ash drakes on both blank and static filters

Not supposed to be like that,I think.

### LINKED ISSUE #38031: The ability to have different kinds of static overlays in drones is too niche of a feature to continue supporting.
I bet if I did a scan of preferences I'd find 99% of people never change it from default and it involves allocating a bunch of images for mobs then looping over all of them whenever we want to do anything with them.

See #38019 for an example of why its not worth the hassle to continue supporting.

@RemieRichards tagged to defend their feature if they want.

### PR DESCRIPTION
**Pull request by vuonojenmustaturska**
Closes #38031
Closes #20284

🆑 : Naksu
del: Removed drone overlays
/:cl:

@KorPhaeron take a look at this if you merge the drone removal

### CODE REVIEW

**Comment by RandomMarine** [comment]
This should've been done away with regardless of what happens to drones. It's broken and ran counter to its intended purpose.

**Review by imtakingabreakdontatme — APPROVED** [review]

**Review by ChangelingRain — APPROVED** [review]
these were honestly the worst thing for drones to have, since it made telling if you were interfering *harder* in an ironic turnabout

**Comment by praisenarsie** [comment]
hey i remember opening a pr for this
#29745 :thinking:

**Comment by vuonojenmustaturska** [comment]
remie is not around to deny the PR anymore

**Pull request merged**
