### PR TITLE
Updates prescription glasses and hipster glasses onmob sprites, removes green glasses

### PR DESCRIPTION
**Pull request by Niknakflak**
Sprites by lexorion
Going to conflict once phil's big refactor is merged.
They kind of look more-so like sunglasses before but the old sprites were garbage.
Only changes the onmob sprites.
Picture: 
image

### CODE REVIEW

**Comment by pudl** [comment]
They were translucent for a reason

**Comment by Niknakflak** [comment]
You mean ugly as fuck

**Comment by Bawhoppen** [comment]
dont worry niknak I hate allura more than you :+1:

**Comment by Niknakflak** [comment]
I dont hate them

**Comment by Niknakflak** [comment]
This is gonna get to chill for awhile until phil's PR is merged, then I got to resolve double the conflicts!

**Comment by ChangelingRain** [comment]
improve don't remove

**Pull request merged**
