### PR TITLE
Makes combat mechs scale based on parts

### PR DESCRIPTION
**Pull request by Razharas**
Makes combat mechs scale based on parts
Capacitor adds emp resistance 10% per level
Scanning module reduces step power drain by 5 per level
Fixes https://github.com/tgstation/-tg-station/pull/12032
Also much better than it

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
Do mechs really need to be even more powerful than they currently are?

Afterall robotics and R&D can print them off like mad and there's not a whole lot security can do against them without an ion rifle.

**Comment by Razharas** [comment]
The fact that R&D and robotics can print them like cakes but doesnt do it for some reason is indicating for me that mechs are underused
Also after security buff mechs became less deadly

**Comment by WJohn** [comment]
This is super cool, by the way :+1:

**Comment by Durkel** [comment]
Good improvement, scaling parts should have been a thing for awhile.

**Comment by xxalpha** [comment]
Neat.

**Comment by Lumipharon** [comment]
I don't think it's a good idea to make the turbo murder mech more emp resistant, but eh.

**Comment by Durkel** [comment]
Sudden thought, but could you make the nuke op mechs start with better than average parts? No every buys the damn things.

**Comment by Lumipharon** [comment]
Also,

>The fact that R&D and robotics can print them like cakes but doesnt do it for some reason is indicating for me that mechs are underused
Also after security buff mechs became less deadly

Even with t4 parts in the fabs, mechs still require a lot of minerals to make.
Very often miners (when they mine at all) will mine enough to happily make shit, but not enough to shit out an endless stream of mechs.

Also honestly sec buffs effected combat mechs very little, if at all.

**Comment by Anonus** [comment]
Mechs with lower-tier parts should be LESS powerful than they currently are, so basically you need second-tier stuff and not just the basic shit-tier parts if you don't want a slightly weaker mech.

**Comment by Fox-McCloud** [comment]
>Mechs with lower-tier parts should be LESS powerful than they currently are, so basically you need second-tier stuff and not just the basic shit-tier parts if you don't want a slightly weaker mech.

Very much agree with this; whatever capacitors/scanners mechs currently require, that should generate their current values, with lesser parts making them *worse* and parts better than what they currently use making them...well...better.

**Comment by Core0verload** [comment]
This is fine as is. No nerfing required.

**Comment by Anonus** [comment]
I don't see buffing mechs as a good thing given that they're already massively powerful and nigh-invulnerable if used properly

**Comment by kevinz000** [comment]
Well, mechs still doesn't stop a flashbang so there is stuff sec can do if the mech user isn't overprepared.

**Comment by Shadowlight213** [comment]
Wish this had affected ripleys. The power drain reduction would have been great as you can't use the energy relay on mining.

**Comment by Lumipharon** [comment]
If you're really ghetto, you can get a plasma and/or uranium reactor, and a prototype welding tool.
Mine plasma and uranium, weld it into sheets, and put them into the ripley for power.

Or just like, use a bluespace cell.

**Comment by Fox-McCloud** [comment]
You can't turn plasma ores into sheets.

**Comment by Lumipharon** [comment]
Well that's gay. Uranium still works, not sure if the reactor effects the driver with the radiation it lets off though.

**Comment by Fox-McCloud** [comment]
Yeah, I'm really not sure why it's a "thing" to be honest; it certainly means the plasma cutters aren't as efficient in the field.

**Comment by Shadowlight213** [comment]
It was removed due to plasma cutters I think.

**Pull request merged**
