### PR TITLE
Ports Making Mobs with the FLB hairstyle trip occasionally

### PR DESCRIPTION
**Pull request by MrsTonedOne**
Ports Aurorastation/Aurora.3#3677

@hornygranny

### CODE REVIEW

**Comment by RandomMarine** [comment]
Cats are the new floorbraids.

**Comment by OneOneThreeEight** [comment]
suck on this, slig

**Comment by Bawhoppen** [comment]
Need more minor flavor like this :+1:

**Comment by Qustinnus** [comment]
floor length braid powercreep

**Comment by RandomMarine** [comment]
But real talk is both a floorbraid and RNG check being made every single time someone moves a performance concern?

**Comment by optimumtact** [comment]
snowflake code, add a flag to the mob set when the hair type is chosen and unset when it's not.

**Comment by megatiger78** [comment]
Capes cause trips, get stuck in fans, doors, catch fire more easily, and are pulled into vents when?

**Comment by OneOneThreeEight** [comment]
https://www.youtube.com/watch?v=4R2aW03pwL0

**Comment by Doppeltongue** [comment]
Didn't clowns/clumsy people used to trip over their own feet? If FLB causes tripping then, clown/clumsy should also trip. It'll also make clowns miserable which enhances the happiness of the crew.

**Comment by fludd12** [comment]
Could make it a hidden statuseffect, and toggle it on for the hair, clown shoes, capes, etc

**Comment by Slignerd** [comment]
@OneOneThreeEight Shouldn't you and the folks you brought with you go back to Aurora?

**Comment by Pacmandevil** [comment]
>Silgnerd implying that I had anything to do with this PR being made

Standards have been lowered

**Comment by Slignerd** [comment]
Where did I implied anything of the sort?

I've just commented on you guys going out of your way just to post something akin to "lmao slig btfo XDD"

**Comment by Pacmandevil** [comment]
considering the "you guys" was just a single person, of which I thumbs up, I seriously think your skin needs to get a bit thicker.

**Comment by Bawhoppen** [comment]
Please ignore the Slig we welcome our guests

**Comment by optimumtact** [comment]
Not even a hidden status effect, just a clumsy footwork status effect that makes you trip.

**Comment by OneOneThreeEight** [comment]
@Slignerd How do you balance tipping your mighty intellectual fedora in this PR between getting offended at harmless teasing? I cannot imagine using so much time in my day expressing to other people how mad I get when people namedrop me in jest.

**Comment by MrStonedOne** [comment]
neat

**Comment by optimumtact** [comment]
it isn't his github, the separation is absolute

**Comment by KorPhaeron** [comment]
First funny PR of the anime moral panic but it is stale/unfinished

**Pull request closed without merging**
