### PR TITLE
Fixes Reverted Marine Rifle Sprites

### PR DESCRIPTION
**Pull request by Steelpoint**
For some reason someone accidently reverted the marine carbine sprite names to the older variant. 

This PR fixes it so you can actually see the rifle in game. 

:cl: Steelpoint
fix: Fixes Iron Hawk marine carbine not having a visible sprite.
/:cl:

### CODE REVIEW

**Comment by kevinz000** [comment]
Why do I feel guilty even though I'm pretty sure I'm not responsible.

**Comment by Steelpoint** [comment]
Accidently reverting someone else's changes is a fear we all have.

**Comment by Niknakflak** [comment]
sometimes it's funny though

**Comment by KorPhaeron** [comment]
Simple icon change already approved, invisible guns are bad

**Pull request merged**
