### PR TITLE
Add Ethereal lungs to the limbgrower

### PR DESCRIPTION
**Pull request by GuillaumePrata**
## About The Pull Request
Saturday morning, calm shift.
I spend most of my time staring at CANARY waiting for an atmos alarm to pop up while I sit at the foyer hearing what random craziness Poly is spewing and wondering about the previous and more interesting shifts.
When suddenly,  an atmos alarm pops up at the Incinerator.
"Fucks sake, I bet the other atmos are torching the place again..."
I rush there expecting to fix a fire, but instead I find the start of something great...

hydrogen farm

The madman kidnapped an Ethereal to use as an organic Hydrogen farm, nothing I haven't seen before but... my hands start shaking, a spark of brilliance and potential in my eyes as I mumbled the words:
"I always hear that organic things are healthier... so what if we throw the Electrolyzer away and instead, print Etheral lungs in the limbgrower and implant them on monkeys..."
To our sadness, Ethereal lungs weren't added to the Ethereal disk design, this fixes that!

## Why It's Good For The Game
Ethic and organic Hydrogen farms are the future!
ethical hydrogen farm

## Changelog

:cl: Guillaume Prata
expansion: Ethereal lungs can be printed with a limb grower now.
/:cl:

### CODE REVIEW

**Comment by Megamaw** [comment]
the gripping mad science moment being instantly deflated really sells me on this one.

**Comment by Orchian** [comment]
I love this, and the side effect of Ethereals being able to get replacement lungs is also good

**Comment by Stonetear** [comment]
Just as a question, why aren't all of the exotic  xeno organs in the limbgrower? Perhaps it makes sense just to put them all in?

**Comment by GuillaumePrata** [comment]
> Just as a question, why aren't all of the exotic xeno organs in the limbgrower? Perhaps it makes sense just to put them all in?

I think most, if not all the round start species organs can be printed, other than Ethereal heart for balance issues (And lore).
The Ethereal Lung is just a new organ that didn't get added.

**Comment by LemonInTheDark** [comment]
What the fuck is this

**Pull request merged**
