### PR TITLE
Use 15 cable on TTVs to turn them into a fancy back item

### PR DESCRIPTION
**Pull request by mc-oofert**
## About The Pull Request

Allows you to use 15 cable on a TTV to allow it to be worn on your back
Wirecutting TTVs that have cable on them gives it back and makes it unable to be worn again
2023-06-27 18_51_29-Pride Warehouse Epsilon

2023-06-30 19_36_50-White Doctor's Course Upsilon

## Why It's Good For The Game

Looks cool, sci drip
Still usable as a prank bomb (no tanks, still shows two), for sci funnies
Can practically achieve the same with a BCI/other-activated TTV (Traitor sci trolled by 1 shove, loses bomb, still results in detonating with BCI/other activation, Traitor sci shoved, does not lose bomb on back, still results in detonation)

## Changelog

:cl:
add: You can use cable on TTVs to make them wearable on the back
/:cl:

### CODE REVIEW

**Comment by TheVekter** [comment]
So these can still function even if they're strapped to someone's back? Can we come up with a way (either via traitor item or crafting) to make one that can't be removed without assistance? I want to live out my 30 Minutes or Less fantasies.

**Comment by mc-oofert** [comment]
> So these can still function even if they're strapped to someone's back? Can we come up with a way (either via traitor item or crafting) to make one that can't be removed without assistance? I want to live out my 30 Minutes or Less fantasies.

yeah theyre still TTVs, afaik goon does the same thing and nobody complained and their toxins is MUCH easier than ours

**Comment by SomeoneYouProbablyKnow** [comment]
> So these can still function even if they're strapped to someone's back? Can we come up with a way (either via traitor item or crafting) to make one that can't be removed without assistance? I want to live out my 30 Minutes or Less fantasies.

Strap a speedometer circuit to it and live out your Speed fantasies.

**Comment by Teleported-Bread** [comment]
> So these can still function even if they're strapped to someone's back? Can we come up with a way (either via traitor item or crafting) to make one that can't be removed without assistance? I want to live out my 30 Minutes or Less fantasies.

I believe prox sensors wouldn't work on worn items, so you could set it up to detonate if its removed

**Comment by LemonInTheDark** [comment]
> Still usable as a prank bomb (no tanks, still shows two)

this is a bug, please don't do this

**Comment by mc-oofert** [comment]
> > Still usable as a prank bomb (no tanks, still shows two)
> 
> this is a bug, please don't do this

worn icon overlays are hard ok

**Comment by nukularpower** [comment]
> > Still usable as a prank bomb (no tanks, still shows two)
> 
> this is a bug, please don't do this

thats just how TTVs work atm, regardless of this PR - if you pick up a ttv with no tanks attached, it looks like it has 2 in hand

**Comment by ExcessiveUseOfCobblestone** [comment]
what is BCI?

Im a little concern since we moved these out of backpacks but Im unsure if the problem was more about the stealth or the fact that you have to go through the takeoff time as well as actually trying to defuse it before the person catches on (they have an instant click button so you will very likely lose)

**Comment by Rex9001** [comment]
Bci is a circut type that can be inserted inside of a person to give action buttons to for example send a signal.

**Comment by optimumtact** [comment]
> worn overlays are hard

figure it out

**Comment by mc-oofert** [comment]
> > worn overlays are hard
> 
> figure it out

hard as in beyond my skill level

**Comment by moocowswag** [comment]
> > Still usable as a prank bomb (no tanks, still shows two)
> 
> this is a bug, please don't do this

Too late :(

**Comment by Loafin34** [comment]
you might want to refactor TTVs or some biz so that only TTVs with two tanks can be added. good luck trying, though.

**Comment by Wallemations** [comment]
> > > worn overlays are hard
> 
> > 
> 
> > figure it out
> 
> 
> 
> hard as in beyond my skill level

Either ask someone to help you or set it so only complete TTVs can be used for this

**Comment by mc-oofert** [comment]
> Either ask someone to help you or set it so only complete TTVs can be used for this

ruins the funny of running into departures with a TTV with no tanks and getting lynched

**Comment by Wallemations** [comment]
> 
> 
> > Either ask someone to help you or set it so only complete TTVs can be used for this
> 
> 
> 
> ruins the funny of running into departures with a TTV with no tanks and getting lynched

You can literally just use empty tanks if you want that. 

My previous statements still stand

**Comment by mc-oofert** [comment]
> You can literally just use empty tanks if you want that.
> 
> My previous statements still stand

as if

**Comment by optimumtact** [comment]
don't make features out of your depth of ability then

**Comment by moocowswag** [comment]
Whoever made ttvs is in twouble

**Comment by mc-oofert** [comment]
> don't make features out of your depth of ability then

what if theoretically i simply did not want to

**Comment by mc-oofert** [comment]
> don't make features out of your depth of ability then

actually im pretty sure what youre asking me for isnt even possible

**Comment by optimumtact** [comment]
then remove the feature that doesn't work that you don't want to put hte effort into.

It's a very simple calculus.

**Comment by mc-oofert** [comment]
> then remove the feature that doesn't work that you don't want to put hte effort into.
> 
> It's a very simple calculus.

ruins the funny though

**Comment by mc-oofert** [comment]
> then remove the feature that doesn't work that you don't want to put hte effort into.
> 
> It's a very simple calculus.

@optimumtact does this count
2023-06-30 19_36_50-White Doctor's Course Upsilon

**Pull request closed without merging**
