### PR TITLE
Skubman, the World's Worst Superhero

### PR DESCRIPTION
**Pull request by EOBGames**
## About The Pull Request
Adds the skub suit to the autodrobe, at the request of @bobbahbrown.
fatskubsuit
Finally, you can show off your love for skub.
(Sorry for taking like a month to make this PR, bee man)

## Why It's Good For The Game
Skub man good? Skub man bad?

## Changelog
:cl: Inept
add: Skub man good? Skub man bad? Get your Skub man suit in the autodrobe today!
/:cl:

### CODE REVIEW

**Comment by Qustinnus** [comment]
Weren't extra uniforms banned

**Comment by Qustinnus** [comment]
Weren't extra uniforms banned

**Comment by EOBGames** [comment]
we all know ninja man is a skub lover, he'd never close this PR

**Comment by MacBlaze1** [comment]
> we all know ninja man is a skub lover, he'd never close this PR

Watch him let someone else close it lmao

**Comment by AnturK** [comment]
I hate it

**Pull request closed without merging**
