### PR TITLE
You can now mount canvases on walls

### PR DESCRIPTION
**Pull request by Robustin**
It always bugged me that once you "painted" something on a canvas your only choices for displaying it were leaving it on the floor or dragging around an easel. 

Now you can easily hang/remove it from a wall.

### CODE REVIEW

**Comment by XDTM** [comment]
I think you can pass paintings through walls, if you do it like this

**Comment by Robustin** [comment]
Feature, canvases contain quantum entangled nanomachines that allow for viewing and interaction through solid objects.

Thats why the NT budget can only afford to give us 3 of em.

**Comment by bgobandit** [comment]
why not make it a child of signs like picture frames

**Comment by Robustin** [comment]
I was having issues with picture frames and some of the rules they had. 

I also didn't really like the idea of needing tools to manage such a casual aspect of the game.

I'll take another look at it to see how it handles the wall bit if people really care.

**Comment by bgobandit** [comment]
yeah like I know there are some bugs in picture frames I need to fix but

**Comment by optimumtact** [comment]
bruh this is an awful hack

**Comment by PKPenguin321** [comment]
Call parent somewhere

**Comment by Robustin** [comment]
Figures we couldn't live in a simple world where people get to put memes on walls, I'll have to test how I can get this to work like frames.

**Comment by Alek2ander** [comment]
You can do the wallmount meme where it's actually on the turf in front of the wall

**Comment by Robustin** [comment]
I suspect thats what frames do anyway, still need to check.

My life has never been the same since I learned every APC in the game is actually sitting on the floor and just pixel_shifted to the wall.

**Comment by duncathan** [comment]
will reopen when no longer stale

**Pull request closed without merging**
