### PR TITLE
It's oranges

### PR DESCRIPTION
**Pull request by Thunder12345**

### CODE REVIEW

**Comment by YotaXP** [comment]
Totally not a player reference.

**Comment by Anonmare** [comment]
Slippery slope

**Comment by Anonmare** [comment]
Powercreep.

**Comment by PraiseRatvar** [comment]
buff oranges while you're at it

**Comment by Repukan** [comment]
S l o p e

**Comment by kilkun** [comment]
S l i p s

**Comment by ma44** [comment]
At this rate we will have to nerf slips to prevent slippery slopes from ever happening again.

**Comment by FantasticFwoosh** [comment]
Where is kor pineapple?

**Comment by kilkun** [comment]
where is @KorPhaeron [Kor Phaeron](http://warhammer40k.wikia.com/wiki/Kor_Phaeron)

**Comment by AnturK** [comment]
It's closed.

**Review by optimumtact — APPROVED** [review]
mildly odd fetishism of the fruit aside

this is the correct spelling

**Comment by CosmicScientist** [comment]
:tangerine:

**Comment by KorPhaeron** [comment]
Glad I got an @ for a spellcheck PR

**Pull request merged**
