### PR TITLE
New Satchel and Backpack Sprites!

### PR DESCRIPTION
**Pull request by Imaginos16**
## About The Pull Request
Hi all! Been a while since I've done a PR, eh? Well, suffice to say that while I have been on quite a break to recuperate my strengths, I've been working on my pixel art on the meantime. Particularly, I wanted to address a certain elephant in the room when it came to respriting items: Backpacks, and Satchels.

image

Every departmental backpack and satchel, including the grey ones, were entirely redone.
As for the engineering ones, I've ported the ones from Beestation done by @Agameofscones , with some mild tg-fication to suit our style better (Seen in PR: [#2677](https://github.com/BeeStation/BeeStation-Hornet/pull/2677))

## Why It's Good For The Game
Backpacks and Satchels have been in the chopping block for as long as I can remember, and after a bout of inspiration, I was able to finally tackle them! Unfortunately for duffels, I'm still working on those and felt it'd be better to address backpacks and satchels first before taking them on!

I truly hope you all enjoy this, as this was an extremely fun project to work on :)

## Changelog

:cl: PositiveEntropy, Triiodine
imageadd: Resprites all backpacks and satchels in their entirety!
/:cl:

### CODE REVIEW

**Comment by Fikou** [comment]
Lovely, colors on the botany ones look a bit weird and it's sad to see nothing with leather/explorer satchels but still awesome.

**Comment by Imaginos16** [comment]
> Lovely, colors on the botany ones look a bit weird and it's sad to see nothing with leather/explorer satchels but still awesome.

Yeah, leather I've intentionally ignored. I hate to make promises, but I do eventually want to handle duffels, so expect the ones I skimmed on to be retouched.

**Comment by Ebin-Halcyon** [comment]
> Lovely, colors on the botany ones look a bit weird and it's sad to see nothing with leather/explorer satchels but still awesome.

Tbf, explorer gear is already pretty well sprited, isn't much you can change other than slightly alterered color palettes.

**Comment by the-orange-cow** [comment]
Thanks for getting rid of the traffic cop yellow on the botany gear, I always hated how that looked.

**Comment by Imaginos16** [comment]
I hope I didn't mess this up, the concept of screenshot tests is still very new to me.

**Comment by Bawhoppen** [comment]
I think people would freak out less if more resprites were like this 👍

**Comment by bluetshirtguy** [comment]
Not sure if it's possible to change but the rear sprite for the grey backpack has a very flat almost boxy look at the bottom of the sprite.

**Comment by Imaginos16** [comment]
> Not sure if it's possible to change but the rear sprite for the grey backpack has a very flat almost boxy look at the bottom of the sprite.

That is, unfortunately because of how belts overlay with the backpack, so its like black on black. I don't know how I'd fix that. Maybe I could ditch belts in their entirety in the future perhaps, or something idk.

**Comment by Iamgoofball** [comment]
i wear satchels explicitly so that i dont have to see the stupid backpack sprites, why did we make the satchel straps mega thick?

**Comment by Mothblocks** [comment]
> I hope I didn't mess this up, the concept of screenshot tests is still very new to me.

If the error popup doesn't come back, you're  fine

**Comment by Agameofscones** [comment]
> i wear satchels explicitly so that i dont have to see the stupid backpack sprites, why did we make the satchel straps mega thick?

those look like the on-mobs I did for Bee as well. I used the same strap setup from CM since it's important to know when a player has a weapon their back (And I'm a ~~perennially lazy~~ efficient spriter). Doesn't make a whole lot of sense for TG design wise tho.

**Comment by normie5-cell** [comment]
Looks like Eris

**Review by Twaticus — APPROVED** [review]

**Comment by Agameofscones** [comment]
> > > i wear satchels explicitly so that i dont have to see the stupid backpack sprites, why did we make the satchel straps mega thick?
> > 
> > 
> > those look like the on-mobs I did for Bee as well. I used the same strap setup from CM since it's important to know when a player has a weapon their back (And I'm a ~perennially lazy~ efficient spriter). Doesn't make a whole lot of sense for TG design wise tho.
> 
> Personally it was because I felt it was a nice design decision, to help differentiate it more from backpacks, and have people notice that the person wears a satchel. I don't get this criticism that bags should almost be near-invisible. Might as well not bother having options like satchels or duffels at that point.

I don't disagree, I like big straps, but I know the vibe on TG is thin straps or none at all. Just to reduce PR friction might want to reduce em' to 2px thick.

**Pull request merged**
