### PR TITLE
Refactors the latejoin list

### LINKED ISSUE #27957: people are getting put INSIDE chairs on the arrivals shuttle
WHAT THE FUCK

### PR DESCRIPTION
**Pull request by Cyberboss**
Gonna need a testmerge on this
Also adds a return value to listclearnulls

Fixes #27957 
Closes #27963

### CODE REVIEW

**Comment by duncathan** [comment]
Has this been test merged?

**Comment by optimumtact** [comment]
it's stale

**Comment by lzimann** [comment]
It was testmerged and fucked up late joining.

**Comment by Cyberboss** [comment]
We put it up for a testmerge, but it had bus, I'll fix em soon

**Comment by Cyberboss** [comment]
>tfw can't be assed

**Comment by Cyberboss** [comment]
Ready

**Pull request merged**
