### PR TITLE
"Return to lobby if preferences unavailable"

### PR DESCRIPTION
**Pull request by Incoming5643**
Adds a new option to how the game handles a situation where a player doesn't qualify for any jobs they have set. Previously you could only have it set to play a random job (risky and potentially unfun) or play assistant (greytide).

Players that use this but fail to qualify for anything they want get returned to the lobby. Because of how the game handles antag selection a player who is disqualified in this way is available for antagonist roles that choose before job handling (malf/nuke ops/wizard), but not for ones that choose after (everything else). Going forward with a little work monkey/blob (the other two "the job doesn't really matter" modes) antags could be added to the other list if so desired.

I feel that this would almost completely remove all the roundstart suicides/greytide by providing a "way out" for people who would otherwise get shunted into roles where they would have no desire to play the game and/or just be an asshole. It would also keep crew sizes down on hyper bloated servers.

:cl:
add: You now have the ability to automatically "back out" of a round if you miss your chance at all the jobs you have set to low or higher. This is found on the toggle at the bottom of the jobs window
add: Due to a quirk of game mode code this option will fail to work if you've been selected as an antag, but then, you've been selected as an antag! In this situation, you'll be assigned a random job.
experiment: <b>Whatever your previous selection for this field was has been lost, so be sure to update it.</b>
/:cl:

### CODE REVIEW

**Comment by hornygranny** [comment]
>stale
:^)

**Comment by Incoming5643** [comment]
Just a wee bit

**Comment by Incoming5643** [comment]
Pull is ready but preferences_savefile.dm is being a code and I cannot fix it

**Comment by optimumtact** [comment]
Update your editor and git configuration to leave the line endings alone when they're already set you meme

**Comment by Iamgoofball** [comment]
>>>2014

**Comment by Incoming5643** [comment]
PR cancelled due to failure to computer

**Pull request closed without merging**
