### PR TITLE
Adds a rack of Syndicate-branded souvenirs to the kidnapping holding area, including a new t-shirt

### PR DESCRIPTION
**Pull request by andrea-feather**
## About The Pull Request

Changes one of the washing machines in the kidnapping area to a rack full of Syndicate tourist merchandise, featuring three Syndicate balloons, a cap gun, and three copies of a new souvenir t-shirt. Also adds a poster on the wall.

image

image

image

(It _will_ be all you get, because the only thing you can transfer to and from the holding area is clothing. This also ensures that Syndicate balloons will retain their elite and exclusive niche)

The souvenir tee is based off of the cook jorts + tee, but with a few tweaks. In particular, it uses the modern jean shorts sprite as the bottoms, instead of the older jorts used in the cook jorts sprite. (I'm planning on making another PR that updates those slightly.) For extra traitorous flavor, it always starts with its sensors off.

## Why It's Good For The Game

It adds a bit more Syndicate flavor to the still very ninja-y holding area. More importantly, it's funny.

## Changelog

:cl:
add: The Syndicate is now branching off into cheap tourist merchandise -- collect your limited edition t-shirt today by entering the nearest kidnapping pod!
/:cl:

### CODE REVIEW

**Comment by Rhials** [comment]
I got kidnapped by the syndicate and all I got was this stupid t-shirt

**Comment by skylord-a52** [comment]
Slight update: Decided I liked it better without the belt.
image

**Comment by nianjiilical** [comment]
have you considered making people wearing the t-shirt have the same negative moodlet on security/heads of staff that syndicate posters do because that would be funny

**Comment by skylord-a52** [comment]
> have you considered making people wearing the t-shirt have the same negative moodlet on security/heads of staff that syndicate posters do because that would be funny

Someone already suggested it on the Orbstation discord and I initially rejected it, but now that two people have suggested it independently, I might have to... I don't know! I'll have to look into how that's actually done first, and whether it's within my extremely limited BYOND capabilities.

**Comment by necromanceranne** [comment]
I was gonna make a joke about a lousy t-shirt but hey, you already did it.

**Comment by JohnFulpWillard** [comment]
I disagree with the mood debuff it's just a piece of clothing, and isn't antagonist equipment, I don't see why we should be just stacking mood debuffs on people for wanting to play a certain job.

**Comment by necromanceranne** [comment]
> I disagree with the mood debuff it's just a piece of clothing, and isn't antagonist equipment, I don't see why we should be just stacking mood debuffs on people for wanting to play a certain job.

because it's funny and it is connected to an antagonist action that technically the player can choose to not interact with.

**Comment by nianjiilical** [comment]
> I disagree with the mood debuff it's just a piece of clothing, and isn't antagonist equipment, I don't see why we should be just stacking mood debuffs on people for wanting to play a certain job.

i dont think it should be a huge mood debuff i just find the idea of security mobbing some guy to rip off his syndicate t-shirt and throw it in the cremator because it makes the captain salty inherently amusing

**Review by dragomagol — APPROVED** [review]
Love it

**Pull request merged**
