### PR TITLE
Webedit, fixes sanity checks for tackle and wellcheers. (WEBEDIT PR, TESTED IN VSC.)

### LINKED ISSUE #81852: Tackle and Wellcheers use the wrong defines for (literal) Sanity checks.
## Issue Summary
Tackle and Wellcheers use the wrong defines for (literal) Sanity checks.
Tackle looks for your Sanity_level, but uses SANITY_INSANE(This is used for mood level), but not SANITY_LEVEL_INSANE
Same goes for Wellcheers.
```
if(human_sacker.mob_mood.sanity_level == SANITY_INSANE) //I've gone COMPLETELY INSANE

-----------------------------

datum/reagent/consumable/wellcheers/on_mob_life(mob/living/carbon/affected_mob, seconds_per_tick, times_fired)
	. = ..()
	affected_mob.adjust_drowsiness(3 SECONDS * REM * seconds_per_tick)
	var/need_mob_update
	switch(affected_mob.mob_mood.sanity_level)
		if (SANITY_INSANE to SANITY_CRAZY)
			need_mob_update = affected_mob.adjustStaminaLoss(3 * REM * seconds_per_tick, updating_stamina = FALSE)
		if (SANITY_UNSTABLE to SANITY_DISTURBED)
			affected_mob.add_mood_event("wellcheers", /datum/mood_event/wellcheers)
		if (SANITY_NEUTRAL to SANITY_GREAT)
			need_mob_update = affected_mob.adjustBruteLoss(-1.5 * REM * seconds_per_tick, updating_health = FALSE)
	if(need_mob_update)
		return UPDATE_MOB_HEALTH
```

```
#define SANITY_INSANE 0 (This is mood variable defines, goes from 0 to 150
#define SANITY_LEVEL_INSANE 6 (This is Sanity_level defines, it goes from 1(Sane) to 6(Insane).
```
Small note if relevant, wellcheers code was changed from mood_level to sanity_level [here](https://github.com/tgstation/tgstation/commit/1119c9684be245fdb734a2c61ab0569a1cd6a96d)
image

As a side note, I've been trying to get VSC to clone my fork for this repo with some difficulties, If I get it running, it should be just a simple define swap to fix these issues.

## Round ID:
Doesn't Matter

## Testmerges:
Doesn't matter

## Reproduction:
So far this makes Insanity level tackles impossible.
And makes wellcheers only drain stamina (It also makes you drowsy but that's always the case for any mood.)

### PR DESCRIPTION
**Pull request by 2whatever2**
## About The Pull Request
Fixes both tackle Insanity checks and wellcheers sanity check. 

I couldn't get make VSC clone my fork so I just did a webedit, and tested changes with VSC.

https://github.com/tgstation/tgstation/assets/24631139/73730216-0c0a-45ee-8ee3-94c7695f4337

https://github.com/tgstation/tgstation/assets/24631139/90d96a5f-98cd-4bf5-b1d3-d0e0d14a917a
## Why It's Good For The Game
Bugfixes are good.
Fixes https://github.com/tgstation/tgstation/issues/81852
## Changelog
:cl:
fix: Tackle and wellcheers code for sanity values now function.
/:cl:

### CODE REVIEW

**Comment by necromanceranne** [comment]
nyoops

**Comment by jughu** [comment]
[verified ✔]

**Comment by SyncIt21** [comment]
Add "Fixes #81852" to your PR body to link the issue

**Comment by ExcessiveUseOfCobblestone** [comment]
your crown, king

**Comment by 2whatever2** [comment]
> Add "Fixes #81852" to your PR body to link the issue

Looks like cobby already did it, but uh yeah I forgor to do that 💀 I'll just link the issue anyway.

**Pull request merged**
