### PR TITLE
Profane Scholar Chaplain outfit resprite

### PR DESCRIPTION
**Pull request by ReinaCoder**
## About The Pull Request
The Profane Scholar suit was resprited recently and while the new sprite was a definitely improvement on the old one, it completely changed the look of the outfit by changing the colours and increasing the saturation.
This PR takes the general shading and design of the resprite and changes the colours to be more like the original sprite (and the reference).
image

## Why It's Good For The Game
The darker colours suit the outfit more

## Changelog

:cl:
imageadd: The Profane Scholar outfit has been resprited 
/:cl:

### CODE REVIEW

**Review by Imaginos16 — APPROVED** [review]
Ahhh… Kos…. Or some say Kosm…

**Comment by the-orange-cow** [comment]
> Ahhh… Kos…. Or some say Kosm…

AWOOOOOOO

**Comment by RuneQuester** [comment]
Grant us eyes..grant us EYES on the INSIDE

**Comment by weesnaw-ops** [comment]
This is appearing darker in game than it shows in the preview.

**Pull request merged**
