### PR TITLE
Moved round end sounds to strings

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by MrPerson** [comment]
Keep in mind this means the roundend sounds won't be included in the rsc. Which may not even be a bad thing, I dunno.

**Review by Cyberboss — CHANGES_REQUESTED** [review]
1. It doesn't belong in the strings folder, just `flist()` the roundend sounds folder

1. If you're going to do this, you need to make the sounds use a content delivery system like the admin verb. so that the server won't lag sending them at the end of the game

**Comment by lzimann** [comment]
Sounds are not strings though.

**Comment by Cyberboss** [comment]
Just `flist` the round end sound folder

On Jun 17, 2017 11:54 AM, "Leo" <notifications@github.com> wrote:

Sounds are not strings though.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/tgstation/tgstation/pull/28529#issuecomment-309223194>,
or mute the thread

**Comment by Cyberboss** [comment]
IDK if this PR is worth it tbh

**Comment by lzimann** [comment]
It's not.

**Comment by Cyberboss** [comment]
The rsc doesn't change often enough to warrant sending them dynamically

**Pull request closed without merging**
