### PR TITLE
Revert "Adds swimsuits for the summer ball event"

### PR DESCRIPTION
**Pull request by Iamgoofball**
1. Admins have access to the view variable tools and SDQL. They can add custom uniforms easily. 
2. the /tg/station server has a serverside_modifications.dm setup on the codebase, they can add dmis with the same method.
3. The content is unused in our codebase, and we have a history of denying pull requests that add unused non-framework content.
4. If they want to use the costumes, they can just test-merge the PR. It doesn't need to be open or merged for the test merge to work properly.

Stop cluttering the codebase with one time use event items. There's a reason we made a branch for April Fools.

Closes #38348
Closes #38372

### CODE REVIEW

**Comment by Iamgoofball** [comment]
as an added note, why aren't these underwear

i dunno about you but usually you don't wear your two-piece on top of your USSR shirt and heart boxers

**Comment by Shadowflame909** [comment]
>Spam. Not disruptive content.

Do better! Also to goof. This seems like a bad idea.

**Comment by optimumtact** [comment]
if you're being marked as spam it's because your comment is no more substantial than using the thumb emojii, which is what you should be doing

**Comment by GuyonBroadway** [comment]
Goof is correct though, temporary content should be added by a new form like april fools day as opposed to bloating the codebase with unused features.

**Comment by Armhulen** [comment]
I'd just make these underwear, yeah

**Comment by PKPenguin321** [comment]
Again, these should be placed in the beach bum ruin

**Comment by ShizCalev** [comment]
@PKPenguin321 see #38348

**Comment by ShizCalev** [comment]
image

🤔

**Comment by SgtxRootbeer** [comment]
can oranges quit hiding comments?

**Comment by GuyonBroadway** [comment]
Well for now the best way to keep things from being hidden is by keepin on topics (and its better than outright deletion IMO) but as it stands I think the swimsuits PR being merged the way it did was a blunder based on code standards and existing precidents. 

Sure add some swimming gear for whatever **[shuffles deck, draws 7 cards]**  Catgirl schoolground loaded potato chips blanket fantasy, summer ball you want but don't then use it as an excuse to slip in things to the codebase that would not fly under normal circumstances.

Honestly thats as bad as going "Fixed: Security not having the means to beat every antag by default".


Ok maybe thats a little bit hyperbole, but even so making something a permenant fetaure under the guise of a once yearly event is pretty dishonest.

**Pull request closed without merging**
