### PR TITLE
SMES tgui-next

### PR DESCRIPTION
**Pull request by spookydonut**
## About The Pull Request
image

### CODE REVIEW

**Comment by spookydonut** [comment]
@stylemistake#1991 what the heck:
```
            var/target = params["target"]
            var/adjust = text2num(params["adjust"])
            to_chat(world, "t:[target] a:[adjust] raw:[params["target"]]")
```
```
t:10000 a: raw:10000
```
```
            <Button
              icon="forward"
              disabled={data.inputLevel === data.inputLevelMax}
              onClick={() => act(ref, 'input', {target: '10000'})} />
```

**Comment by spookydonut** [comment]
fixed, fucking hell

**Comment by Neo-0** [comment]
where is the "set" button?

**Comment by spookydonut** [comment]
> 
> 
> where is the "set" button?

waiting on @actioninja to code the component for it

**Pull request merged**
