### PR TITLE
Changes Rock Description to be more descriptive

### PR DESCRIPTION
**Pull request by Niknakflak**
Adds more detail to rock descriptions.  This is very much needed, I'm not sure why this wasn't added before?  The game is better now.

### CODE REVIEW

**Comment by Buggy123** [comment]
much-needed feature, no idea how its been ignored so long.

**Comment by ike709** [comment]
It's not just a boulder... It's a rock!

**Comment by QualityVan** [comment]
They're minerals.

**Comment by FantasticFwoosh** [comment]
Can you smell what they're cookin?

**Review by Cyberboss — APPROVED** [review]

**Comment by Y0SH1M4S73R** [comment]
>when the maintainers merge an actual goofball-tier shitpost PR

**Pull request merged**
