### PR TITLE
Adds more variety in virus cures, more consistent difficulty scaling.

### PR DESCRIPTION
**Pull request by kriskog**
## About The Pull Request
Edit: Now picks from a bigger list for each level, for a bit of variety and to avoid all random diseases sharing the same cure.

Makes the higher levels harder than previously, while adding a more consistent increase in difficulty of getting a hold of virus cures. 

List is now:
1 - Copper, Silver, Iodine, Iron, Carbon
2 - Potassium, Ethanol, Lithium, Silicon, Bromine
3 - Table salt, Sugar, Orange juice, Tomato juice, Milk
4 - Spaceacillin, Saline-glucose solution, Epinephrine, Charcoal
5 - Oil, Synaptizine, Mannitol, Space drugs, Cryptobiolin
6 - Phenol, Inacusiate, Oculine, Antihol
7 - Leporazine, Mindbreaker toxin, Corazone
8 - Pax, Happiness, Ephedrine
9 - Lipolicide, Salicyclic acid
10 - Haloperidol, Aranesp, Diphenhydramine
11 - Modafinil, Anacea

Level 1 and 2 have simple chems, some can be gotten through grinding stuff.
3 has kitchen/bar/hydro stuff
4 has stuff easily found in medbay or medbay vendors
5 has three chem drugs
6 has five chem drugs
7 has slightly harder drugs
8 is drug themed, has drawbacks
9 is a bit harder again
10 are worse, has fairly bad drawbacks so eat sparingly.
11 are hard to make, anacea has chem purging and some slight tox damage.

Will need a wiki update.

## Why It's Good For The Game
Makes high virus resistance more favorable, and creates some need for some obscure chems.

## Changelog
:cl: Skoglol
balance: Added lots of new virus cures, made cure difficulty scale more consistently. Cures are now picked from a list of possible cures per resistance level, multiple diseases at the same level no longer always share a cure. Looking at you table salt.
/:cl:

### CODE REVIEW

**Comment by wesoda25** [comment]
Works for me since I use haloperidol as my defense chem as chemistry

**Comment by Shadowflame909** [comment]
I still wish gold was a cure, maybe lower though?

Fancy metal was thought to be a cure at one point.

**Comment by imsxz** [comment]
holy water cure for faith healing

**Comment by kriskog** [comment]
Silver is a biocide, so they werent wrong. This is spess though.

If I were to readd gold it would probably be instead of ethanol. Holy water is too limited in supply if the chaplain dies/never came to work, it wouldnt be fair.

**Comment by Shadowflame909** [comment]
We just gotta make holy water a resistance 20 cure. resistance t  w e n t y

**Comment by kriskog** [comment]
I contemplated extending the list, but the balance implications are huge. What kind of viruses can you make at say resistance 20 that are bad enough to kill everyone if they cant find a cure? I don't know, but the job of figuring out is big.

**Comment by kriskog** [comment]
Fuck, wrong button

**Comment by Tlaltecuhtli** [comment]
gold was fine tho

**Comment by Shadowflame909** [comment]
If you really want to mess people up, forget Holy water. Make Strange Reagent a virus cure. Holy Water + Omnizine + Unstable Mutagen. Now that's a harsh virus cure.

**Comment by RandolfTheMeh** [comment]
I personally believe any chemical with a plasma catalyst should be higher. Modafinil really shouldn't be the max resistance chem in my opinion since its incredibly low metabolism rate means you can give someone like 0.5u and they'll be cured. There's no need to use the pandemic, one batch of modafinil is all you need. 

Now if the max resistance cure was the fast-metabolizing ClF3, though.

**Comment by kriskog** [comment]
Yeah, modafinils metabolization is fine. The amount of cure available is rarely a bottle neck since you usually get cured off 5-10u of anything. 

As for plasma catalyst, it's fairly easy to deal with. Plasma sheets are plentiful roundstart, all you need is a grider (or mortar and pestle). It is the only reason I left leporazine in, since it is a two chem drug otherwise.

**Comment by imsxz** [comment]
break the reinforced table at chemistry and grind the plasteel for plasma lol

**Comment by necromanceranne** [comment]
Personally the real thing keeping viro back is that holodeck pandemic. Literally anyone can make vaccines which somewhat defeats the purpose virology. 

This is a good first step towards making viro less hot garbage though.

**Comment by Mickyan** [comment]
I'm not too happy (heh) seeing Happiness on that list since it's supposed to be a contraband drug but meh.

While you're in there I would suggest swapping table salt and sugar

**Comment by Tlaltecuhtli** [comment]
i would prefer an not only chem as cure way with: gold , doctror_delight, BZ metabolites, bs dust, glycerol as all of these "hard cures" are 1 click macros

**Comment by kriskog** [comment]
Not everyone got a macro ready, and we got to keep in mind a disease could easily kill you in 2 minutes from infection. 

I am considering making the lower end chems pick from a bigger list per level, as random diseases seem to get table salt 90% of the time.

**Comment by Tlaltecuhtli** [comment]
people that dont have macros are probably already dead from meth explosions (macros are even in the wiki)
having an hard to get cure means people will cure once and then use the pandemic machine

**Comment by bgobandit** [comment]
is synaptizine even used for anything anymore?

**Comment by Shadowflame909** [comment]
@bgobandit Lesser Virus Plasma for that epic eternal youth

**Comment by kriskog** [comment]
Okay, I am doing random cures for each level to change how random diseases always getting the same cure on level 1.

**Comment by ATH1909** [comment]
> Personally I think the real thing keeping viro back is that holodeck pandemic. Literally anyone can make vaccines which somewhat defeats the purpose virology.

The virologist can always sabotage the holodeck pandemic, and if they didn't, it gives the crew some counterplay against a death virus that kills people really quickly.

**Comment by kriskog** [comment]
This runtimes, DNM till I fix it.

**Comment by kriskog** [comment]
It's fixed

**Review by 81Denton — APPROVED** [review]

**Comment by kriskog** [comment]
Pending meta changes after the patch chem OD PR, salicyclic acid may need to be replaced. Its fine for now though.

**Pull request merged**
