### PR TITLE
Buffs C4 to ensure it actually breaches doors.

### PR DESCRIPTION
**Pull request by Iamgoofball**
:cl:
balance: C4 is now 1/2/3, up from 0/0/3.
balance: X4 is now 1/2/5, up from 0/2/5.
/:cl:

### CODE REVIEW

**Comment by Fikou** [comment]
doesnt this make parapen c4 a viable strategy again but replace parapen with whatever stun item you have
it also makes x4 pretty useless since it only makes the light range a bit bigger

**Comment by nemvar** [comment]
heck yeah, c4 gibbing is back baby.

**Comment by EgorDinamit** [comment]
Wont this breach the floor too?

**Comment by EgorDinamit** [comment]
Also I don't think it's a good idea, since people can put C4 on items and use it as grenade

**Comment by jlc1206** [comment]
C4 already has a thrown item penalty

**Comment by MMMiracles** [comment]
para+c4 sounds like an awful thing to bring back and I say this as someone who used to do it because I thought it was funny

**Comment by Shadowflame909** [comment]
C4 put on Shurikens dont embedd. I know i've tried.

But you can tie c4 onto items like bolas. So that's epic.

Good PR all in all.

**Comment by Iamgoofball** [comment]
C4 already gibbed people you strapped it to.

**Comment by Iamgoofball** [comment]
Also, gibbing leaves a brain nowadays. Ye olde parapen c4 did not leave a brain

**Comment by Fikou** [comment]
> C4 already gibbed people you strapped it to.

no it didnt

**Comment by nemvar** [comment]
You don't seem to have read c4 code. Please don't make a fool out of yourself.

**Comment by Ikoden** [comment]
Yesterday I caught a clown traitor. He wished to go out with a bang and hinted at his C4. I strapped it to him. It only delimbed him. Like took an arm and something.

**Comment by BeeSting12** [comment]
God bless, thank you goof.

**Comment by necromanceranne** [comment]
Goof these cost 1tc and let you strap them to objects in boxes, which lets you able to use them as improvised bombs. This makes them minibombs as well for 1tc.

This isn't the solution and makes for a whole host more problems.

**Comment by PKPenguin321** [comment]
the whole point is that they're bombs, anne

**Comment by necromanceranne** [comment]
And my point is that a minibomb is literally just one point higher in light power yet costs four times the tc. Those aren't used primarily by traitors to blow apart a room it's used for a quick body gibbing and disposal. You would be an idiot to spend 4 tc on using it as an actual explosive in a fight unless you're using it to catch people underfoot while being chased.

**Comment by Ryll-Ryll** [comment]
1/2/3 is kind of a big step up from 0/0/3 for something as cheap as C4, plus it pretty much kills the difference between C4 and X4. C4 already has a niche as a cheap sabotage device for blowing up objects/obstacles, making it a minibomb that's slightly harder to use at a sixth of the price just seems poorly thought out

**Comment by SumFaggotPlayTester** [comment]
Fugg it all speed merge this now. I need to yarr harr my way through to station to steal all its booty as a spess pirate & I need this now. Drunk playtester here confirming this is a good PR

**Comment by HomocidlePancakes** [comment]
Syndi minibomb needs a buff.

**Comment by necromanceranne** [comment]
Okay so, lemme explain in greater detail why this is a bad idea. I don't know why I need too but apparently I do. Probably because people aren't aware of the mechanics around these things, or those who are likely are licking their chops at the idea of more easy murderboning on the cheap and likely being disingenuous.

So, c4 can have a signaller attached to it's wires as it's simply a grenade. So using a screwdriver, you can attach a signaler to detonate it remotely. This makes it usable as a normal bomb. This lets you basically use c4 as a minibomb not technically, but literally. With a signaled explosion that is far more precise than trying to count seconds. Even then, you could just have a timer assembly and do it that way instead. So effectively, with some juryrigging with not very difficult to acquire parts, you can make a stick of c4 just a minibomb. Not even hyperbole, that's literal. And it's at a 5 tc discount to boot. you can buy 9 of them for 8 tc. Which is an obscene discount on price.

You cannot however use the special attachment effect to make something else a bomb and throw that so it blows up as part of the countdown, as the throw speed and force of the object it's attached too is reduced heavily.

HOWEVER, this doesn't stop bolas with c4 attached to them wrapping around peoples legs if you throw it into them point blank. Which makes this bomb essentially the new elance with a signaller attached since you can now run away from your very slowed down opponent and signal the bomb for an easy gib. The only way to stop this is to cut off your own leg, which only the captain's sabre is a near guarantee to do.

Actually, this is worse. Goof, you're giving traitors a roundabout smite with a bomb attached for 1 tc and maybe 4 if they spend it on the very versatile throwing weapons kit.

The upper limit on the timer is 60000 seconds if you want to set it that. Which means you can prep your bomb bolas ahead of time and signal them accordingly and never worry about premature detonations.

Also operatives have cqc which is parapen++ so that means cqc and c4 the target and whoops you killed him easy peezy.

Also, did you test this. I tried using a minibomb under an airlock and it didn't blow up the airlock either, it just spaced the hull underneath it.

**Comment by Iamgoofball** [comment]
If dev explosions aren't destroying airlocks something is wrong with airlock ex_act

**Comment by necromanceranne** [comment]
Well, it destroyed it but left a wreckage. But so did the current c4 so like this is a big ???

**Comment by Fikou** [comment]
> If dev explosions aren't destroying airlocks something is wrong with airlock ex_act

maybe make it do a light explosion twice? that would cause the airlock to explode leaving the frame and then the frame to explode

**Comment by Tlaltecuhtli** [comment]
if people complain about "parapen" + c4 then remove the "parapen" as [any item in the game] + parapen is a mistake

**Comment by Tharcoonvagh** [comment]
just nerf doors instead

**Comment by PKPenguin321** [comment]
the paranoid obsession with "parapen c4!!!" is seriously overplayed considering how we basically dont even have real stuns anymore and how even if we did you could just "stun + cut off head and debrain with esword" to do effectively the same thing

**Comment by Angustmeta** [comment]
Should buff minibomb as well. It's only 1, 2, 4, about same as new C4, but costs 500% more TC.

**Comment by Ryll-Ryll** [comment]
Why is the conversation even about the fairness of parapen + C4, the fact that this is putting the power of an existing 6TC item into a 1TC item should be enough of a reason to deny this PR. C4 costs 1TC a piece because it's a niche tool for breaking structures and breaching rooms, if this PR was really aimed at fixing C4's inability to do that, you could just make it manually qdel whatever door/wall it's stuck to. Instead, this PR tries to pull a switcheroo by giving it the power of an already existing and much more expensive item far beyond what it needs to do its job while acting like it's still the same power level as before

Like if you just wanted this because people running around using 20 C4 minibombs to blow up the station sounds funny, cool, just say that in your PR. Don't lie about it and try to pass off a massive buff as a usability fix

**Comment by Ryll-Ryll** [comment]
It's especially dumb that people are defending it by saying "well c4 is a bomb of course it explodes" and "what's the problem, you can just esword people's brains out anyway" (wtf eswords cost 8TC why are you acting like they're directly comparable) even though the whole point of this PR is supposedly because C4 doesn't remove doors

**Comment by nemvar** [comment]
@Iamgoofball 
This is what c4 prime currently looks like. It does this in addition to the normal explosion.
```
/obj/item/grenade/c4/prime(mob/living/lanced_by)
	[...]
	if(target)
		if(!QDELETED(target))
			location = get_turf(target)
			target.cut_overlay(plastic_overlay, TRUE)
			if(!ismob(target) || full_damage_on_mobs)
				target.ex_act(EXPLODE_HEAVY, target)
	[...]
```
The sensible choice for mininal side effects would be to replace the EXPLODE_HEAVY with EXPLODE_DEVASTATE since that would only buff structure damage. (full_damage_on_mobs is FALSE for all c4 + subtypes)

If you however actually want a straight strength buff to c4, please just fucking say so.

**Review by 81Denton — CHANGES_REQUESTED** [review]
hmmmmm

X4 doesn't even work, C4 makes minibomb sized holes which is bad for the plethora of reasons that @necromanceranne mentioned.

@nemvar's comment is the most sensible choice here since the last thing we need is a massive antag buff.

**Comment by Ikoden** [comment]
> 
> 
> @Iamgoofball
> This is what c4 prime currently looks like. It does this in addition to the normal explosion.
> 
> ```
> /obj/item/grenade/c4/prime(mob/living/lanced_by)
> 	[...]
> 	if(target)
> 		if(!QDELETED(target))
> 			location = get_turf(target)
> 			target.cut_overlay(plastic_overlay, TRUE)
> 			if(!ismob(target) || full_damage_on_mobs)
> 				target.ex_act(EXPLODE_HEAVY, target)
> 	[...]
> ```
> 
> The sensible choice for mininal side effects would be to replace the EXPLODE_HEAVY with EXPLODE_DEVASTATE since that would only buff structure damage. (full_damage_on_mobs is FALSE for all c4 + subtypes)
> 
> If you however actually want a straight strength buff to c4, please just fucking say so.

This seems like the best solution. You nerds make good points about 1TC mini syndie bomb or 1 TC bola gib.

**Comment by Dorsisdwarf** [comment]
So to summarise this pr it

1. Doesn't actually do what the author claims it is for.
2. Completely invalidates a more expensive traitor weapon
3. Brings back the dark days of throwing C4 stuck to things with a voice analyser to instagib them


If you wanted to just restore the capability of C4/X4 as a breach item, why not just make it run a breach() action on whatever its stuck to that checks for walls/doors and deletes them before applying the explosion to guarantee entry? As it is, this PR serves no purpose but to buff an annoying uncounterable round removal meme strat

**Comment by Tlaltecuhtli** [comment]
code can support being able to detect if its attached to "annoying items" and have a lesser effect than on a wall/machine/floor

**Comment by zxaber** [comment]
Why not just make airlocks destroyed by explosions not drop an assembly? That seems like it would fix the issue entirely.

**Comment by BeeSting12** [comment]
Yeah I'm thums downing this I was under the impression it would actually destroy airlocks, no need to make c4 into minibombs if they can't even destroy airlocks

**Comment by PKPenguin321** [comment]
>It's especially dumb that people are defending it by saying "well c4 is a bomb of course it explodes" and "what's the problem, you can just esword people's brains out anyway" (wtf eswords cost 8TC why are you acting like they're directly comparable) even though the whole point of this PR is supposedly because C4 doesn't remove doors

right so this is directed at me
yea ur right this is stupid with the bomb changes especially if it doesnt even actually work on airlocks so i take that back
the esword part stands though, maybe esword was a bad example because it costs TC but you can decapitate/debrain with fucking anything, welders for one. parapen+c4 hasnt been an issue in literal years but c4 has been unable to gib for that time because of what i can only assume is the salt equivalent PTSD

**Comment by Pugie** [comment]
You can't decapitate/debrain with welders that's straight up not true.

**Comment by TheVekter** [comment]
This is an issue with airlocks, not with C4.

**Comment by PKPenguin321** [comment]
>You can't decapitate/debrain with welders that's straight up not true.

have you tried it? they do 15 burn, that's enough to disintegrate the head

**Comment by necromanceranne** [comment]
I think the reason it is dusting body parts is to do with the damage type. I think welders are doing damage as actual fire, and strictly burn, unlike the cakehat.

**Comment by PKPenguin321** [comment]
nah theyre the same, it turns out it's the w_class, anything below normal size can't dismember

**Pull request closed without merging**
