### PR TITLE
Add game logging to abductor gland mind control.

### PR DESCRIPTION
**Pull request by Timberpoes**
## About The Pull Request

Can't see anywhere that abductor gland mind control directives get logged, so I added game logging where the admins get messaged.

## Why It's Good For The Game

Logging good.

### CODE REVIEW

**Comment by bloons3** [comment]
Can this get  tagged with Logging?

**Comment by Timberpoes** [comment]
> 
> 
> Can this get tagged with Logging?

For you, my friend, anything is possible.

**Comment by bloons3** [comment]
> > Can this get tagged with Logging?
> 
> For you, my friend, anything is possible.

I only ask, since I admin bee and we like to steal all of TG's logging PR's.

**Comment by Timberpoes** [comment]
> 
> 
> > > Can this get tagged with Logging?
> > 
> > 
> > For you, my friend, anything is possible.
> 
> I only ask, since I admin bee and we like to steal all of TG's logging PR's.

No problemo. Hopefully it helps or proves useful to you!

**Pull request merged**
