### PR TITLE
Pneumatic cannons now only fire one item per click by default

### PR DESCRIPTION
**Pull request by ATH1909**
## About The Pull Request

As the title. This affects both normal pneumatic cannons and improvised pneumatic cannons (it technically affects harpoon guns too, but they can normally only hold one item at a time anyway), which would both fire all of their contents at once before this PR.

This PR also nerfs the storage capacity of improvised pneumatic cannons, bringing it down from w_class 20 to w_class 10 (I could even be persuaded to bring it down to w_class 6, to lower the potential/effectiveness of improvised pneumatic cannons loaded with genetically-engineered plants).

## Why It's Good For The Game

Improvised pneumatic cannons are a notorious source of one shot kills (just load one up with 20 glass shards and click on someone, for example), but currently aren't really very useful for doing anything OTHER than one-shotting people due to them needing to be reloaded after every shot. This PR brings improvised pneumatic cannons closer to the throwing-aid tools that I think that they were intended to be.

## Changelog
:cl: ATHATH
balance: All kinds of pneumatic cannons now fire their contents one at a time, instead of all at once (by default).
balance: The storage capacity of improvised pneumatic cannons has been halved.
/:cl:

### CODE REVIEW

**Comment by ATH1909** [comment]
Note to self: after the antag PR freeze ends, add a subtype of the pneumatic cannon item for traitor botanists called the "coconut gun" that can fire in spurts.

**Review by ghost — APPROVED** [review]

**Comment by ATH1909** [comment]
Also, I hope that someone gets the reference in the branch name of this PR.

**Comment by ATH1909** [comment]
Idea here: I could make that near-useless power level 3 setting (the one that knocks you onto your ass whenever you fire the cannon) fire all of the items in the cannon at once instead of however many items the cannon normally fires.

Do y'all want me to do that?

**Comment by Krysonism** [comment]
I get that pneumatic cannons are broken, but do we really need to nerf it at both ends?

**Comment by Michael-Ashfield** [comment]
> Idea here: I could make that near-useless power level 3 setting (the one that knocks you onto your ass whenever you fire the cannon) fire all of the items in the cannon at once instead of however many items the cannon normally fires.

Why not for each power level you can shoot that many items, so power 3 shoots 3 shards, power 1 is 1 shard.

The real gamer play is shooting super matter shards anyway

**Comment by ATH1909** [comment]
> > Idea here: I could make that near-useless power level 3 setting (the one that knocks you onto your ass whenever you fire the cannon) fire all of the items in the cannon at once instead of however many items the cannon normally fires.
> 
> Why not for each power level you can shoot that many items, so power 3 shoots 3 shards, power 1 is 1 shard.
> 
> The real gamer play is shooting super matter shards anyway

Ah, but what if the base amount of items that a future subtype of the pneumatic cannon is supposed to shoot by default isn't 1, but instead, say, 5? It's an idea that I'll consider for a future follow up PR if it gets enough support, I suppose.

**Comment by 81Denton** [comment]
Good change. 
If they get abused a lot, it might also be worth looking at the two epic launcher payloads of lit welding tool + plasma dipped cigar and CLF3 beaker + chemical grenade.

**Comment by nemvar** [comment]
Can you make them normal sized again?

**Comment by ATH1909** [comment]
> Can you make them normal sized again?

Nah, otherwise they'd become ghetto stetchkins/eguns if you load them up with the right items (I think). The lack of subtlety helps balance them, sort of like cattle prods (and, to a lesser degree, improvised shotguns).

If you wanna do that in a new PR after/if this PR gets merged, though, go for it.

**Comment by OverlyGeneric** [comment]
Not a bad band-aid fix but probably would be better to scale up the air cost for each item inserted.

**Comment by AdamElTablawy** [comment]
You don't need to nerf the storage capacity AND the 'throws all objects' part. The inability to throw multiple objects is likely sufficient.

**Pull request merged**
