### PR TITLE
Add rolling pin datum to wooden plank recipes

### PR DESCRIPTION
**Pull request by erwgd**
With 2 wooden planks you can craft a rolling pin.

(In the first commit, 10 planks were required to craft a rolling pin; in the second, 1 plank was required)

### CODE REVIEW

**Comment by KorPhaeron** [comment]
Should probably just be 1

**Comment by Cheridan** [comment]
1 wood, 1 metal rod? To act as the axis.

**Comment by Lumipharon** [comment]
A traditional rolling pin is just wood yo.

**Comment by optimumtact** [comment]
Only americans would have a metal cored rolling pin

**Comment by KorPhaeron** [comment]
I have a wood cored rolling pin, Cheridan is just weird

**Comment by Cheridan** [comment]
Man, whatever. As if I bake.

**Comment by Iamgoofball** [comment]
@Cheridan is triggering me please ban him @github

**Pull request merged**
