### PR TITLE
Fixes tool-based flashes being stuck at intensity 1

### PR DESCRIPTION
**Pull request by zxaber**
## About The Pull Request
A long-old bug due to the use of `min(flash_strength, 1)`. The intention was clearly to have the flash be *at least* level 1, because flash_strength defaults to nothing but can be set to 2. However, `min(x,y)` uses the lowest value, making it always return 1. So we change it to `max()`.
## Why It's Good For The Game
Bugfix. Sunglasses users cope.
## Changelog
:cl:
fix: Tool-based flashes (read: from welders) are no longer incorrectly locked at flash level 1. Wear proper PPE!
/:cl:

### CODE REVIEW

**Comment by sylvia-from-fulp-station** [comment]
sometimes mistakes exist for so long that players consider them features of the game; sunglasses block visual effects from flashbangs, flashes being used in your face, etc; its not unreasonable for them to give some degree of welder protection given their exclusivity. i think the real issue is how clunky other welding equipment is to use vs Sunglasses which are set and forget with 0 downsides.

**Comment by zxaber** [comment]
We already have set-and-forget options as mid/late upgrades. Flash-protecting cybernetic eyes have a protection of 2, as do most modsuits. Experimental welders were (and probably still are) set to only have a flash rating of 1, meaning that aside from infinite fuel, the other bonus they grant is compatibility with sunglasses.

Squashing it all into flash or no flash removes depth from the game, and if we wish for that to be the case we should have a PR dedicated to it. In the meantime, having to toggle welding helmets is at least more interesting than roundstart set-and-forget, and it really bugs me that roundstart Security would have better welding protection than roundstart Robotics/Engineering.

**Comment by necromanceranne** [comment]
Man, this is such an old bug, it's about time it got fixed. Weird that sunglasses were just straight up better welding goggles.

**Comment by improvedname** [comment]
yeah my base routine as engineer was litteraly getting sunglasses i had no reason to use welding goggles like ever

**Comment by Helg2** [comment]
Fixing such an old bug, when things were already balanced multiple times around it is cringe.

**Comment by zxaber** [comment]
> Ah yes, finally i can not only flash sec moths, but all the sec at once.

This specifically, and solely, affecting the blind/eye damage from welder arc flash. Handheld flashes, flash grenades, and the like are unaffected.

But yes, sec memebers can no longer weld with their sedhuds alone.

**Comment by Helg2** [comment]
Ah, okay then.

**Comment by YuliceTheDruid** [comment]
>Sunglasses nerf

😭

**Pull request merged**
