### PR TITLE
fish sprite improvement

### PR DESCRIPTION
**Pull request by tralezab**
## About The Pull Request

makes some of the older fish sprites much much better. eob added them for their lizard culture pr but i wanted to them justice
i will be also looking at the wot mols fish (?)

## Why It's Good For The Game

good sprites good

## Changelog
:cl:
imageadd: better fish and fish food sprites
/:cl:

### CODE REVIEW

**Comment by ArcaneDefence** [comment]
Please consider this a friendly warning, your PR's must have a properly descriptive title and body content that explains the purpose of the PR.

Your current title and or body content does not meet requirements, so please update it.

**Comment by Arkatos1** [comment]
emojis died for this

**Comment by ProfessorSniff** [comment]
> # just some fish sprites improvement
## About The Pull Request
> makes some of the older fish sprites much much better. eob added them for their lizard culture pr but i wanted to them justice
> i will be also looking at the wot mols fish (?)
## Why It's Good For The Game
> good sprites good
--- 
at least, i think. i struggled reading this a bit

**Comment by optimumtact** [comment]
Please consider this a friendly warning, your PR's must have a properly descriptive title and body content that explains the purpose of the PR.

Your current title and or body content does not meet requirements, so please update it.

**Comment by tralezab** [comment]
foiled again..

**Comment by KubeRoot** [comment]
Can you just manually adjust the GBP gain for the PR for shit like this

**Comment by optimumtact** [comment]
@tralezab I really must remonstrate with you about your behaviour.

It's public knowledge that the maintainer team is struggling to keep up with the flow of pull requests entering the tracker.

Deliberately obscuring the intention of your PR's with incomplete titles and messed up PR body descriptions is increasing their workload unnecessarily, being able to discern the authors intent is important, and it's up to you to be a team player to help out with that process.

if you continue this pattern of behaviour I don't feel I have any other choice but to remove you from contributing until you are willing to be a team player, or our workload decreases enough that we can handle such PR's

**Comment by Twaticus** [comment]
idk what this means so im just gonna trust u
image

**Review by Twaticus — APPROVED** [review]

**Comment by optimumtact** [comment]
it means he's a dipshit who's added extra states

**Comment by tralezab** [comment]
will fix

**Pull request merged**
