### PR TITLE
Directional Signage v2

### PR DESCRIPTION
**Pull request by lessthnthree**
## About The Pull Request
A slight re-pass of the directional signage on walls. 
-All signs now have a consistent 3px x 5px font and an improved arrow.-
-All arrows are now consistently on the right hand side instead of an inconsistent side based on department.
-VAULT and CARGO are now fully displayed, DRM is expanded to DORM

image

## Why It's Good For The Game
Improved look, consistency good.

## Changelog

:cl: LT3
imageadd: Minor improvements to station wayfinding signage
/:cl:

### CODE REVIEW

**Comment by gonenoculer5** [comment]
@lessthnthree Could you add a screencap of what they used to look like for comparisons sake? Thanks!

**Comment by lessthnthree** [comment]
> @lessthnthree Could you add a screencap of what they used to look like for comparisons sake? Thanks!

Icondiffbot in Checks: https://github.com/tgstation/tgstation/pull/72388/checks

**Review by Twaticus — APPROVED** [review]
do note these have already been redesigned for the wallening project

**Comment by lessthnthree** [comment]
> do note these have already been redesigned for the wallening project

yeah that's fine. work's been done, use 'em for however long until wallening.

**Pull request merged**
