### PR TITLE
Vitamins 2: Electric Boogaloo

### PR DESCRIPTION
**Pull request by ghost**
https://github.com/tgstation/tgstation/pull/32458 updated

🆑 Xhuis and More Robust Than You
add: Nutrition has been revamped! Food, drinks, and some medicines now have varying healthiness. Eating healthy foods and maintaining a good vitamin balance will allow you to very slowly heal minor wounds, and bolster your immune system!
add: Very slow natural healing has been added. If you're unhealthy, this will not function! Healing is roughly equal to 0.01 + (0.05% of your vitamin count). Your liver will also purge toxins at a rate of 0.05 + (0.02% of your vitamin count). Neither of these values can drop below zero.
add: Junk food like candy and soda will cause you to become unhealthy, whereas chef meals and plants will make you more healthy. Juices will also do this.
add: If a healthy diet isn't an option, vitamin supplements are available from the medical bay, as well as gamma globulin shots intended for malnutrition that massively increase vitamin count!
/🆑

### CODE REVIEW

**Comment by Buggy123** [comment]
If hypervitaminosis causes tox damage then it should probably be cured by revive().

**Comment by ACCount12** [comment]
I see a massive system with one purpose: remove fun. Playing the game is fun, having to eat healthy food every 10 minutes is the opposite of fun.

**Comment by ExcessiveUseOfCobblestone** [comment]
awww MRTY learned about vitamins today :3

**Comment by Armhulen** [comment]
eat vitamims <3

**Comment by Buggy123** [comment]
The nazi inside me has been screaming at me for the last 2 hours, its [hypervitaminosis](http://www.dictionary.com/browse/hypervitaminosis), not hypervitamintosis.

**Comment by Xhuis** [comment]
I appreciate the revival, but if a PR with unanimous positive support was never merged by any maintainers because none of them could be bothered, I don't see why they would be different this time

**Comment by KorPhaeron** [comment]
@tgstation/commit-access does anyone care about it this time I still think it's lots of complication for no noticeable gameplay impact

**Comment by MoreRobustThanYou** [comment]
@KorPhaeron it makes the chef useful, and discourages just eating 4no raisins at the point where you get hungry, and adds a benefit to being well fed

**Comment by MoreRobustThanYou** [comment]
wtf @optimumtact

**Pull request closed without merging**
