### PR TITLE
Allow ghosts to use any NanoUI interface.

### PR DESCRIPTION
**Pull request by neersighted**
:cl: neersighted
add: Nanotrasen is proud to announce that even the dead can use our state of the art NanoUI technology.
/:cl:

### CODE REVIEW

**Comment by WJohn** [comment]
I dunno whether to call it a fix or a feature. Does this mean they can now snoops around computers and whatnot without interacting with anything?

**Comment by neersighted** [comment]
Yep, it's a feature.

**Comment by Shadowlight213** [comment]
Oh neat. This lets admins interact with shit as ghosts.

**Comment by WJohn** [comment]
Actually I was wondering, is there a way to allow admins to actually play with the buttons on these interfaces while keeping regular ghosts from doing so?

**Comment by neersighted** [comment]
That is the case. Admins get NANO_INTERACTIVE, ghosts get NANO_UPDATE.

**Comment by Jalleo** [comment]
Make sure to have fixes hashwhatever in your topic area to auto close fixed issues.

**Comment by optimumtact** [comment]
@neersighted if this fixes a known issue, add 
Fixes #issuenumber
to the top pr comment and it will automatically close that issue when this pr is merged.

**Comment by neersighted** [comment]
@optimumtact It doesn't fix an issue really... It is still an issue. Just one that NanoUI can help resolve. But it still wont be resolved until everything nanos.

**Comment by Jalleo** [comment]
Then you can say it fixes itand make a new issue saying which ones are still not fixed.

**Pull request merged**
