### PR TITLE
makes plasmamen roundstart options

### PR DESCRIPTION
**Pull request by Iamgoofball**
disco inferno, requested by sweaterkittens in coderbus

### CODE REVIEW

**Comment by daman997** [comment]
le free spacesuit skeleton

**Comment by Anonus** [comment]
hue hue hue
It's not that easy, you FOOL. They need plasma tanks and the suits, or they'll become flaming corpses every round.

**Comment by Incoming5643** [comment]
Horrendously unbalances changeling transformation sting and makes posing as one much harder.
Literally zero options for how they look, they all look the same every single round.
"Have fun stripping confirming my identity without killing me or catching on fire!"
Meme race

I could probably remember more reasons for why this is a terrible idea. I'm still amazed they even got merged to begin with.

/10

**Comment by SweaterKittens** [comment]
Obviously, I would love this. Plasmamen are fun as hell, and are almost a complete downgrade from humans, meaning that they exist for fun and rp, not just for every memer to play one as a joke. Their "free space suit" /has/ to stay on or you burst into flames and die. Anyone who's claiming they're too good is totally off base.

@Incoming5643 
Then make them illegible to play as a changeling, much in the same way Lizards can't be heads. Easy enough, not enough of a reason to nix them completely. As far as posing as one? You just have to take their suit. And that's ONE objective in ONE gamemode. The fact that they're easy to kill and impossible to clone means that people aren't going to be playing them as memes, they're going to play them because they really want to play them.

**Comment by AlexCrimson** [comment]
Remember when coders agreed that none of the starter races would have any pros/cons over eachother? Heh...

**Comment by RemieRichards** [comment]
@SweaterKittens actually you can clone them, you just have to get the suit onto the new body quick enough for them to not burn to death.

**Comment by SweaterKittens** [comment]
@AlexCrimson 
I think the idea was that by having races that could be potentially better than humans, thereby enabling powergamers and the like. And obviously you risk "Cantina Station 13", like Aurora and Paradise. But with nonhumans that are worse, you're not going to get any powergamers playing them, and there will be fewer players of them over all.

@RemieRichards 
I did not know that, I always saw them die almost immediately, but that's good to know. Perhaps upgraded cloners would be helpful in that case.

**Comment by Iamgoofball** [comment]
quite frankly lizards were a goddamn mistake

plasmamen is at least an original SS13 meme and not a furry race

**Comment by Incoming5643** [comment]
Even if everything else was fixed I just can't support something that would lead to having a significant portion of the playerbase spawn as visually identical mobs. Do you know what kind of fresh hell that would play for trying to find someone?

**Comment by SweaterKittens** [comment]
@Incoming5643 
I imagine that if this gets merged, eventually the unique job-specific suits would get merged as well. Additionally, I think you're overestimating how many people are going to be playing a race that's nearly a direct downgrade.

**Comment by Xhuis** [comment]
Even if this is enabled, they still need to start with their suits.

**Comment by PKPenguin321** [comment]
this is an awful idea, for precisely the reasons incoming listed

**Comment by Miauw62** [comment]
i needed that

**Pull request closed without merging**
