### PR TITLE
Bugfixes , bugfixes, bugfixes

### LINKED ISSUE #4168: Spess helmets don't hide masks.
I'm not sure if this is a flag issue or what, but you can clearly see a breath/gas mask under RIG helmets and such.

### LINKED ISSUE #10044: Lizard snout is poking through helmet
This is the SHARP snout that's doing that, may apply to the regular one too.

@Incoming5643

### LINKED ISSUE #10513: The 'Toggle Helmet Light' verb allows toggling the flashlight attached to a security helmet even if the wearer is unconscious/dead

### LINKED ISSUE #10538: Atmos fire helmets spawn in the wardrobe closet instead of the atmos closet.
It doesn't make any sense for a essential part of a outfit to be separated.

### LINKED ISSUE #11806: Syndicate simple mob swat helmets change when they die
Default swat helmet path is the red colored one, but the syndicate agent simple mobs have old sprites for their clothing

### PR DESCRIPTION
**Pull request by phil235**
- Fixes Atmos fire helmets spawning in the wardrobe closet instead of the atmos closet. Fixes #10538
- Fixes syndicate simple animal sprite not showing the right helmet. Fixes #11806
- Fixes Toggle Helmet light verb on security helmet with seclite attached being usable while dead. Fixes #10513
- Fixes Lizard snout is poking through helmet. Fixes #10044
- Fixes Space helmets not hiding masks (breath masks protruding) and glasses (especially the large gar glasses). Fixes #4168
- <b>Eva harsuit helmet no longer has a semi transparent part (incompatible with hiding masks and glasses, and causes lizard snout protruding from that helmet)</b>
- Made equip_to_slot() and unEquip proc more OOP at the carbon level which removes some duplicate code between monkey and human.
- Readding code\modules\mob\living\carbon\brain\login.dm that someone (probably me) unchecked some time ago by mistake.
- <b>Made the atmos tech firefighting helmet hide the mob's hair and block syringes.</b>

### CODE REVIEW

**Comment by Shadowlight213** [comment]
Aww. Rip cool transparent helmet.
Remove lizard snout. They conflict with too many fun things.

**Comment by bgobandit** [comment]
remove lizard in general

**Comment by KorPhaeron** [comment]
Can we fix the syndicate sprite by removing the ugly stripes from the helmets instead of putting ugly stripes on the mobs?

**Comment by Incoming5643** [comment]
I think I actually already fixed that snout issue already, are you sure it was still happening?

**Comment by phil235** [comment]
@Incoming5643 yep, it was happening, I tested it.

**Pull request merged**
