### PR TITLE
Cargo ui refactor -> TS

### LINKED ISSUE #81442: cargo request reason fucks up the apostrophes
Reporting client version: 515.1630

## Issue Summary
cargo request reason fucks up the apostrophes

## Round ID:
[223804](https://scrubby.melonmesa.com/round/223804)

## Testmerges:
- [Temp keybinds patch for 515.1628](https://www.github.com/tgstation/tgstation/pull/81089)

## Reproduction:
type an apostrophe into your request for a crate
it looks like this
image

### PR DESCRIPTION
**Pull request by jlsnow301**
## About The Pull Request
Refactors cargo ui, fixing some visual bugs, just making it look better in general

Should be no gameplay effect other than it looking better

<details>
<summary>pics</summary>

Il0e6EWjUa

Screenshot 2024-04-17 230621

Screenshot 2024-04-17 235319

Screenshot 2024-04-17 234758

Fixes #81442
Screenshot 2024-04-18 000750

Made a type grabber for backend data in case you want to make your own typescript uis
`logger.log(getShallowTypes(data))`
image
Otherwise cargo's data is unreadable

</details>

Any UI over 500 lines should get broken up to reduce cognitive load
~~Any ui in javascript shouldn't exist~~
## Why It's Good For The Game
Cargo UI is better
Typescript
## Changelog
:cl:
fix: Cargo's supply console has been upgraded visually.
/:cl:

### CODE REVIEW

**Comment by EricZilla** [comment]
Could you make it so when buy privately is checked its also orange? I always feel like that thing is my enemy

**Comment by jlsnow301** [comment]
> Could you make it so when buy privately is checked its also orange? I always feel like that thing is my enemy

image

**Comment by SyncIt21** [comment]
What about both a department and private order on the same item?

Like say I order 2 BZ canisters, 1 through the department app and 2nd privately. How does it show on the cart?

**Comment by jlsnow301** [comment]
> Like say I order 2 BZ canisters, 1 through the department app and 2nd privately. How does it show on the cart?

took a look at it and it was formatted strangely, i condensed the text and moved department over (was originally after cost)
image

**Comment by SyncIt21** [comment]
Clean

**Comment by Helg2** [comment]
You could maybe also replace the `Restricted` text with lock icon and add a help message for it.

**Comment by jlsnow301** [comment]
> You could maybe also replace the `Restricted` text with lock icon and add a help message for it.

good idea!

**Pull request merged**
