### PR TITLE
Removes volume control for admin midis

### LINKED ISSUE #17361: "Set Admin Volume" defaults to 0 since PR
For some reason the "Set Admin Volume" in preferences is defaulted to 0 rather than 100.
This has confused a lot of admins as they assume they can no longer hear midi/ogg's being played.

It does, after changed, stay at the level it is set to between rounds and log in/out.

Also someone mentioned the "Hear Admin Midi's" toggle button no longer works due to this either (even when at 100) though I have not tested that myself yet.

### PR DESCRIPTION
**Pull request by Shadowlight213**
Fixes #17361 
Removed by popular demand I guess.

### CODE REVIEW

**Comment by Cheridan** [comment]
Why are you removing this one? Just remove the on/off toggle since you can replicate the same thing by setting volume to 0

**Comment by Shadowlight213** [comment]
Because feedback on the pr to remove the toggle was that the volume control was unwanted.
I'm reopening the other pr and people can vote on which they prefer.
#17395

**Comment by optimumtact** [comment]
@Cheridan the volume control is pointless

**Comment by lzimann** [comment]
i've never had a situation of lowering volume, if anything i just click "stop sounds"

**Pull request merged**
