### PR TITLE
Adds a new arcade prize, take two

### PR DESCRIPTION
**Pull request by PKPenguin321**
🆑 Supermichael777 & PKPenguin321
add: Added fake pits. Get them from the arcade machine.
/🆑

Reopened PR of https://github.com/tgstation/tgstation/pull/24399 by @Supermichael777

### CODE REVIEW

**Comment by ShadowDeath6** [comment]
I can get down with those commit names

**Comment by Kromgar** [comment]
Your still sick fucks

**Comment by jughu** [comment]
You shoukd auctally fall in but  you crawl out after

**Comment by octareenroon91** [comment]
Falling in would possibly be OP.

**Pull request merged**
