### PR TITLE
The Nanoing (Episode 2: The Fix Wars)

### LINKED ISSUE #9856: Air Alarm vent reset button doesn't work
When you set an Air Alarm's vent output pressure to anything else than default and then press the "reset"-button next to it, it doesn't reset.

### PR DESCRIPTION
**Pull request by Fayrik**
Everyone hates their button presses getting ignored. This should make that happen a little less on a few items.
~~(Unfortunately, Air Alarms and APCs aren't going to see the benefit here, but sucks to be them.)~~

I've also taken on board the comments from the first pull request, and fixed an indentation error on one of the HTML templates and made the massive block of code that was called in ui_interact into two procs, so now adding new NanoUI interfaces will be a lot less copy and paste and a lot more actual function.

~~...And I've also made it so that canisters no longer spew out (probably) toxic gasses when you tug an air tank out of them. Flooding areas with canisters is still as easy as ever, you're just not going to do it by accident any more.
(Unless you're REALLY fukken stupid.)~~

Edit:
Caved in to maintainer pressure and removed the amazing feature that stopped the canisters from being the single most annoying thing to use.
Added some fundamental TK compatibility to NanoUI. Sorta. Needs more work but it's in a halfway decent state now.
Fixes #9856

### CODE REVIEW

**Comment by optimumtact** [comment]
Awesome work :+1:

**Comment by PKPenguin321** [comment]
>...And I've also made it so that canisters no longer spew out (probably) toxic gasses when you tug an air tank out of them. Flooding areas with canisters is still as easy as ever, you're just not going to do it by accident any more.

:+1: :+1: :+1: :+1: :+1: :+1: 
inb4 "why do we need this hugboxy change wah"

**Comment by Lumipharon** [comment]
That usually happened because you click close valve, then remove the tank, but it decides to not actually close the valve.

Is there a fix about for the chem dispenser window? It's supposed to be wide enoguh for 4 columns, but it's slightly too narrow so it's a retarded 3 columns and some empty space.

**Comment by Fayrik** [comment]
Oh yeah, I forgot to inb4 that myself, thanks @PKPenguin321 

@Lumipharon No, I haven't fixed the chem dispenser window, but I've been focused on the functionality so far, and templates/aesthetics slipped my mind. I've noticed a similar issue in the air alarm actually, but they should both be as simple as tweaking the width when the UI is created.
If I find time before this PR gets pulled, I'll throw that in as well.

**Comment by Miauw62** [comment]
Canisters spewing out gas when you remove a tank and forget to close the
valve should stay in.
Op 13-mei-2015 01:28 schreef "Lumipharon" <notifications@github.com>:

**Comment by Cheridan** [comment]
Agreed

**Comment by PKPenguin321** [comment]
>Canisters spewing out gas when you remove a tank and forget to close the
valve should stay in.

nah, just leads to bwoinks for sincere accidents most of the time and can be used as an excuse for griefing ("oh i didnt mean to flood plasma in engineering i just accidentally took the tank out before closing the canister on accident i'm sorry")
plus the nanoUI isn't always fully responsive meaning it could potentially not respond to closing the canister before you remove the tank, meaning even more accidental annoying leaks

**Comment by Lumipharon** [comment]
Gas leaks because you forgot to close the valve are fine, I'm just saying it's not unusual for the UI to not respond when you try close the valve, which leads to leaks due to no real fault of the player.

**Comment by Miauw62** [comment]
You're supposed for the valve button to say "closed" before you take the
tank out, though.
Op 16-mei-2015 07:20 schreef "Lumipharon" <notifications@github.com>:

**Comment by phil235** [comment]
Yeah, canister spewing gas when you remove your tank w/o closing the  canister valve needs to stay.

**Comment by PKPenguin321** [comment]
>Yeah, canister spewing gas when you remove your tank w/o closing the canister valve needs to stay.

but why
nobody that wants this has presented any real reasoning for it, while the reasons against it are pretty plentiful

**Comment by Lumipharon** [comment]
Because whyhugbox?

If you forget to close the valve then it's your own damn fault.

The only issue for me is occasionally you clickclose but lag says no, which is not a player issue.

**Comment by PKPenguin321** [comment]
l m a o
read my first comment on this pr

**Comment by Cheridan** [comment]
Workplace accidents are /supposed/ to happen.

**Comment by PKPenguin321** [comment]
but again, lag with the UI can cause gas to be released, which wouldn't even happen in real life
that's hardly a workplace accident, more like an unavoidable OOC force causing plasma to be released
and again, it can be difficult to tell grief apart from genuine accidents with this mechanic

**Comment by Dorsisdwarf** [comment]
Lag on the UI simulates the realism of a spaceman who's in such a hurry he doesn't even take a quarter-second look to see if he turned the valve all the way before he runs off for donk pockets

**Comment by phil235** [comment]
@Fayrik Still working on this? I'll merge it if the valve autoclosing part is removed.

**Comment by Fayrik** [comment]
I've got a few hours free. I wondered why I had abandoned this and went to remove the "hugboxy autoclose", but then immediately saw the half fixes I'd started writing to complete this PR.

So. By the end of today, this PR will either be ready to pull or dead.
Watch this space I guess?

**Comment by phil235** [comment]
Did you test it on a local server?

**Comment by Fayrik** [comment]
I tested it as I wrote the code, and everything immediately checks out. That doesn't rule out the possibility of more issues. The air alarm bug is a prime example, I'd tested the air alarms when I added that, and it all looked to be working fine, I just didn't notice that the reset button wasn't actually changing the value.

**Pull request merged**
