### PR TITLE
Ready] Adds a smaller IRC nudge bot to the tools/ folder

### LINKED ISSUE #4256: IRC bots crash all the time
Is this related to us? We still have the bots on our folders, don't we?

Basically, the IRC bots disappear and don't join again for whatever reason. This has been happening since they are a thing I believe.

### PR DESCRIPTION
**Pull request by tkdrg**
This is meant as a replacement to the 2.4k line monstrosity that is
NanoTransenBot.py, and will hopefully be faster and break less often.

Features:
- NTbot-compatible nudge.py socket listener.
- Supports NickServ IDENTIFY.
- Attempts reconnection on socket timeout.

Fixes #4256

TODO:
- [x] ~~Make the config nudge.py compatible.~~ No longer needed.
- [x] ~~Move bot/ to tools and put this under bot/~~~ Old bot is kill
- [x] Replace the % strings with .format() strings ~~thus making the bot valid python2~~ nope
- [x] Wait for nickserv to answer before joining #adminbus, reauth and rejoin if getting a 477 (https://www.alien.net.au/irc/irc2numerics.html)
- [x] Update nudge.py to oranges' python3 version
- [x] Fix reconnection to use alt nicks if possible, or wait on reconnection if the nick isn't available
- [x] ~~Kill the bot if either of the threads die so the watchdog can restart it~~ Shouldn't be needed anymore?
- [x] Reconnect if the socket dies for any reason instead of only on socket.timeout
- [x] ~~Make the main thread manage the other threads and restart them in case they fail~~ Shouldn't be needed?
- [x] The nudge thread should keep a buffer list in order to keep any messages lost during downtime

### CODE REVIEW

**Comment by optimumtact** [comment]
:+1:

**Comment by MrStonedOne** [comment]
Can you actually separate the client from the config

and make the config nudge.py compatiable?

The tgstation-server toolset does a lot of directory mangling and would need a way to give nudge.py the config without it having to load in the bot and have it start up.

Oh, and if this tests out fine, I'd like you to consider moving bot/ to tools and putting this under bot/ so that i would have less work to do on updating the updater tools to manage it

**Comment by optimumtact** [comment]
https://www.oranges.net.nz/~oranges/nudge.py

here's a version I tested to work okay in python3.

**Comment by MrStonedOne** [comment]
This pr fixes #4256

**Comment by optimumtact** [comment]
Just delete the old one

**Comment by tkdrg** [comment]
@MrStonedOne I pushed another iteration of the bot if you feel like taking a look, I did mostly everything you asked apart from the config stuff. The old config is ugly and I personally would rather make a new one with another format, if possible.

**Comment by optimumtact** [comment]
If you want to wait till you've connected to IRC for sure before sending the join message
wait for
ERR_NOMOTD = '422'
or
RPL_ENDOFMOTD = '376'

**Comment by tkdrg** [comment]
This is merge ready now.

**Pull request merged**
