### PR TITLE
Simplifies diagonal smoothing icon states.

### PR DESCRIPTION
**Pull request by xxalpha**
Sprite work by @ChangelingRain 

All this does is simplify the diagonal smoothing icon states so spriters have an easier time, because they were needlessly complicated.

### CODE REVIEW

**Comment by RemieRichards** [comment]
Also helps me with the Cutter Tool!

**Comment by Thunder12345** [comment]
Does this actually change the appearance of anything significantly, or is it just another way to make something that looks the same?

**Comment by RemieRichards** [comment]
@Thunder12345 will look the same in game, but looks easier to understand+work with in the .dmi files.

**Comment by WJohn** [comment]
👍 
Regular smoothing is fine, but diagonal smoothing is voodoo even to me, and I helped you make it.

**Comment by ChangelingRain** [comment]
Here's how it works now; you have three sprites, two for swapping based on if there's a wall in the opposite direction of the way the diagonal wall faces, and one that's basically the rest of the wall and won't change:

abductor
For example, abductor walls only swap the corner, so that's what they have for the swapping sprites.

pod
Pod walls, on the other hand, don't swap anything, so they just have one sprite and nothing to swap out.

**Comment by RemieRichards** [comment]
@ChangelingRain the tool doesn't produce output like that, where you have two blanks, instead you'll have one blank, one corner, and one diag-wthout-corner.

it all still works though.

**Pull request merged**
