### PR TITLE
podpeople, wishgranter victims, and clones no longer get 0 as one of their affixes (?)

### PR DESCRIPTION
**Pull request by ghost**
just look at the code, i explained it the best i can. for reference, monkeys go 1 to 999, and xenos go 1 to 999. this is just making it work out the same. posibrains do 100 to 999 but they're sillycones.

### CODE REVIEW

**Comment by francinum** [comment]
What's the problem with having 0 as an ID?

**Comment by ExcessiveUseOfCobblestone** [comment]
🚲 🏠 the PR

**Comment by Armhulen** [comment]
look i can make monkeys count as 0 for the id

**Comment by Armhulen** [comment]
swap it around a little hoo haa

**Review by vuonojenmustaturska — DISMISSED** [review]

**Comment by ExcessiveUseOfCobblestone** [comment]
PR the 🚲 🏠 ?

**Comment by Armhulen** [comment]
what's wrong with bikeshedding

making the code consistent and having pod person (0) is weird anyways

**Comment by Armhulen** [comment]
sue me i'm not getting a fix for this anyways

**Comment by QualityVan** [comment]
I support this because in byond counting starts at 1.

**Comment by ShizCalev** [comment]
patient 0

**Review by ShizCalev — CHANGES_REQUESTED** [review]
hit it on /datum/industry/it/generateProductName too please.

**Comment by ExcessiveUseOfCobblestone** [comment]
@Armhulen just seems silly to get upset over something that has a 1/1000 chance of happening and, when it does, has no mechanical effect on gameplay.

If you want ultimate bikeshed, I'd rather see monkey and xeno get 0 instead (patient 0 as shiz mentioned)

**Comment by Armhulen** [comment]
I'm not upset! This was like 2 seconds of webbiting! If this gets closed I can make it patient zero and that's fine

**Comment by ShizCalev** [comment]
do the thing plz.

**Pull request merged**
