### PR TITLE
The Humanening

### PR DESCRIPTION
**Pull request by axietheaxolotl**
## About The Pull Request

Tin!

image

A large part of this was inspired by memager's redux humans, @Onule 's mob sprites, and CEV Eris' new humans, that aren't actually that new anymore. Credit to those people!

## Why It's Good For The Game

Currently humans are one of the oldest sprites in the game, dating in-part to R4407. This is very obvious if you look at it for more then second. But this, this is brand new! Better looking sprites straight for your eyeballs to enjoy.

This'll prob take some getting used to, which is fair. But I feel this is an important step. So, yeah.

## Changelog

:cl:
imageadd: Brand new human sprites!
/:cl:

### CODE REVIEW

**Comment by SmArtKar** [comment]
Dixel: Return Of The King

**Comment by D4C-420** [comment]
Now even the living don't have souls

**Comment by axietheaxolotl** [comment]
> What do they look like with uniforms on?

image

**Comment by Simplehorror** [comment]
image
Old sprites

**Comment by Simplehorror** [comment]
image
Old icons

**Comment by ThePyroTechnician** [comment]
but axie it's not thursday yet they can't be double cheeked up now

**Comment by MrDoomBringer** [comment]
The fact that there's almost no negative reaction despite changing a major sprite that almost everyone is used to speaks volumes about the quality of the work. Well done.

**Comment by Victor239** [comment]
What happened to the ideas for taller humans or the mythical 3/4th perspective human? This incremental improvement isn't worthy of being dubbed "The Humanening" IMO.

**Comment by newfren** [comment]
Can you show what other skin tones look like please?

**Comment by Twaticus** [comment]
mspaint_3T8pB7cN5Q
you think you can just take our tits and ass and get AWAY WITH IT

**Comment by Acer202** [comment]
> mspaint_3T8pB7cN5Q you think you can just take our tits and ass and get AWAY WITH IT

This, come on! pfff

**Review by Imaginos16 — APPROVED** [review]
The dumpy might be flatter but at least the sprites are good

**Review by ShizCalev — APPROVED** [review]

**Review by rye-rice — APPROVED** [review]

**Comment by Arctrooper8** [comment]
Very nice, I have to point out some issues I find with the head though.

I feel it just looks worse than the old head. For example, that "ear pixel" on the north and south sprites looks out of place and really hurts the shape of the head. 
(New head with weird "ear pixel")
norf
souf
(Old head for comparison)
image
image

I'd suggest just making it the same color as the rest of the head border.

I also think there are some part where the border is too dark:
sharp
sharpf

Secondly the male and female sprites have the exact same head. I think this is a downgrade in terms of details in comparison to the old sprites, the difference between head sprites helped the gender choice be more than just tits or no tits.

old:
female
image
male
image

new:
female
image
male
image

Overall though I think this is a wonderful PR, but please at least give my comment some consideration.

**Review by Twaticus — CHANGES_REQUESTED** [review]
needs the booty back

**Comment by Acer202** [comment]
> needs the booty back

Our hero!

**Comment by Ketrai** [comment]
Wait any proper reason this was denied? The PR has 20+ upvotes. 
Like sure, /TG/ isn't a democracy, and it doesn't have to be. But I feel like it's at the very least test-merge worthy with that kind of support.

**Comment by Iamgoofball** [comment]
the artist refuses to re-add the ass

**Comment by MMMiracles** [comment]
i just realized they literally gave spacemen the hank hill ass
image

defined ass cheeks at the cost of flat ass and no booba...

**Comment by Fikou** [comment]
> Wait any proper reason this was denied? The PR has 20+ upvotes. Like sure, /TG/ isn't a democracy, and it doesn't have to be. But I feel like it's at the very least test-merge worthy with that kind of support.

it was testmerged on all servers

**Pull request closed without merging**
