### PR TITLE
[ON HOLD] Adds chambelts to chamkits and ups the price

### PR DESCRIPTION
**Pull request by ghost**
_**ON HOLD DUE TO FEATURE FREEZE, REOPEN AFTER FREEZE IS OVER**_

:cl: More Robust Than You
add: chamkits now contain chambelts
tweak: chamkits now cost 8 tc
/:cl:

### CODE REVIEW

**Comment by lzimann** [comment]
Freeze

**Comment by kevinz000** [comment]
How about not raising the price and separating it instead hmm?

**Comment by meeeeme** [comment]
Doubling the price for 1 new item??? Make it 6 or don't raise it at all.

**Comment by Iamgoofball** [comment]
Yeah that's excessive

**Comment by YakumoChen** [comment]
The military belt pretty much already exists for this express purpose

**Comment by meeeeme** [comment]
Maybe make the military belt chameleon because no one uses it anyway

**Pull request closed without merging**
