### PR TITLE
Adds a new buckknife sprite!

### PR DESCRIPTION
**Pull request by ghost**
Yay, new buck knife sprite, here it is
combat

almost all credit to meyhazah for making the sprite

### CODE REVIEW

**Comment by Mey-Ha-Zah** [comment]
Now that's a fucking knife mate.

**Comment by GunHog** [comment]
Very manly.

**Comment by ExcessiveUseOfCobblestone** [comment]
Space Rambo

**Comment by WJohn** [comment]
This looks like a diagonal version of the switchblade. Not very creative at all. 👎

**Comment by Mey-Ha-Zah** [comment]
The handle is the one part that bugged me the entire time I was working on this. Nothing I could do seemed physically appealing but I guess I can adjust that and the shine.

Also I was working off an image pulled from the internet for the knife, similarities to switchblade are coincidental.

**Comment by WJohn** [comment]
Hm. Taking a closer inspection of the knife does reveal a lot of details on it. I think my main gripe really is just the lack of shine on the knife, and perhaps on the handle too.

Fix those and you could probably replace the boring old combat knife with this.

**Comment by Mey-Ha-Zah** [comment]
Here, 
combat knife final

And bigger version so plebs can see it up close without having to open an image program.
combat knife large

**Comment by WJohn** [comment]
Better. I still think it's not shiny enough (metal is friggin crazy glossy) but it's fine now.

**Comment by Bawhoppen** [comment]
I'm about to fucking stab someone with an actual knife armhullen wtf why didn't you merge my PR to your branch

**Pull request merged**
