### PR TITLE
[READY]Techwebs update: Syndicate technology, adds console graphical/list toggles, fixes materials not being able to be put in

### LINKED ISSUE #33321: Protolathes and Exosuit Fabricators do not appear to accept materials
This is replicable as of 917572c, with 85ddf6b and 418f9ed testmerged.

Using in-hand materials on protolathes and exosuit fabricators does not result in the materials being consumed by the machine.

### PR DESCRIPTION
**Pull request by silicons**
all uplink items now can unlock syndicate tech.
decloner moved to syndicate tech, which now contains that, large ebows, cyborg illegal upgrades, and suppressor.
Fixes #33321

### CODE REVIEW

**Comment by 81Denton** [comment]
The lathe fix is a godsend.

**Comment by XDTM** [comment]
decloner should be abductor tbh, it's a copy of their gun

**Comment by Supermichael777** [comment]
yeah its also deadly as fuck.

**Comment by Tlaltecuhtli** [comment]
speedmerge this

**Comment by MrMaclang** [comment]
speedmerge, this makes science playable

**Comment by davethwave** [comment]
I was wondering what was going to happen to that cyborg upgrade. By the way how do you actually unlock the node for the syndi tech?

**Comment by Anonmare** [comment]
I believe you need to deconstruct a piece of syndicate technology to reveal the node, same with abductor

**Comment by bobbahbrown** [comment]
please merge this for the love of all that is playability

**Comment by Cyberboss** [comment]
yolo, this better work @kevinz000

**Pull request merged**
