### PR TITLE
gorilla sprites

### PR DESCRIPTION
**Pull request by pubby**
# image image GORILLAS image image

image

image

image

image

image

### CODE REVIEW

**Comment by PraiseRatvar** [comment]
DO NOT SAY FREEZE, THIS IS GOOD PR

**Comment by Cyberboss** [comment]
Gorillas can't survive frozen conditions

**Comment by ChangelingRain** [comment]
this isn't a feature pr

**Comment by pubby** [comment]
## Things that are exempt from this:

- Sprite PRs

**Comment by lzimann** [comment]
it's rather useless adding sprites with no use though

**Comment by WJohn** [comment]
These are... actually really well drawn. Nice.

**Comment by Qustinnus** [comment]
thanks i can put these on my planets :^)

**Comment by ExcessiveUseOfCobblestone** [comment]
planet station????

**Comment by Tokiko1** [comment]
Bring Gorrilas back!

**Comment by FantasticFwoosh** [comment]
Where is the sprite when the gorilla attacks to disembowel you?

**Comment by YakumoChen** [comment]
Dicks out for Harambe

**Comment by Super3222** [comment]
Do you see banana man? Hopping over on de white hot sand.

**Comment by dannno** [comment]
the sprites are very nice 
a very good callback to the gorillas of old

**Comment by Niknakflak** [comment]
When they are added, I demand and expect harambe references

**Comment by Supermichael777** [comment]
https://www.youtube.com/watch?v=P9yruQM1ggc

**Comment by Yoshmaster** [comment]
can't believe they're readding these

**Pull request merged**
