### PR TITLE
Adds cardboard IDs to the game: The broke man's agent ID.

### PR DESCRIPTION
**Pull request by Ghommie**
## About The Pull Request
This PR adds a new craftable item to the game that, in a way, works somewhat like ID cards, as in it gives the wearer an identity of some sort, and that can be modified similardly to the agent ID, but...

It doesn't provide access.
It doesn't trick security bots and turrets.
It doesn't work with chameleon masks.
It doesn't have a bank account.
It doesn't fit inside wallets or PDAs.
It doesn't show a trim (it's just cosmetic) on the security HUD.
It doesn't look like an ID card.

(It does however, synergizes well with sign language and face-covering mask, but in the face of all the things id doesn't do, should I change that? idk)

Basically, it's not an ID, it's just a piece of cardboard with name and job written on it.
aww
(null)scrnshot1

## Why It's Good For The Game
Often, player shenanigeans rely on ID cards with gimmicky names and jobs to advertise themselves or provide a (feeble) disguise for it.
The idea is to provide players a cheap tool for their tomfoolery, that doesn't get much in the way of balance. Compared to actual IDs, cardboard IDs' only advantage is the fact they're more easily produceable.

Also this PR converts a bit of snowflakey code into signals, and fixes the name part in hallucination messages being shown "Unknown" while the speaker is wearing a mask but also an ID.

## Changelog

:cl:
add: Added cardboard IDs to the game. They can be crafted with a cardboard sheet and wirecutters and modified with a writing tool. While worn, these will modify the visible name of the wearer just like actual IDs, though they aren't real IDs and won't work as such.
/:cl:

### CODE REVIEW

**Comment by DATA-xPUNGED** [comment]
So soulful...

**Comment by Ghommie** [comment]
> So soulful...

Yea, the sprites are meant to be somewhat soulful to convey that they're quite shoddy (and that I was a bit lazy, maybe)

**Comment by MrDoomBringer** [comment]
no the whole pr is soulful this is shaps tier

**Review by optimumtact — APPROVED** [review]

**Comment by DATA-xPUNGED** [comment]
> > So soulful...
> 
> Yea, the sprites are meant to be somewhat soulful to convey that they're quite shoddy (and that I was a bit lazy, maybe)

I'm not criticizing the sprites, they're, well, cardboard, can't get fancy with that. The whole PR is just what ss13 should be

**Review by Wallemations — APPROVED** [review]
Seeing how these are meant to be handmade the sprites looking wonky make sense to me

**Comment by etherware-novice** [comment]
heyo!

as the original creator of the discount id i like ur new sprite it looks cool
can u provide credit tho? thx 
https://github.com/BeeStation/BeeStation-Hornet/pull/7321

**Comment by Ghommie** [comment]
> heyo!
> 
> as the original creator of the discount id i like ur new sprite it looks cool can u provide credit tho? thx [BeeStation/BeeStation-Hornet#7321](https://github.com/BeeStation/BeeStation-Hornet/pull/7321)

I understand you're probably assuming this drew inspiration from your PR, but allow me to dispel that notion and say that it actually isn't. The code is drastically different, as well the recipe and the sprites, and the fact that two people had a similar concept in mind doesn't imply one is derived from the other, moreso something frankly this easy to idealize.
Apologies if this reply sounds cold to you, but I'm not going to provide credits to something or someone not involved in the creation of this PR in any way. And even if I did, it'd e too late now that this is merged.

Also thanks for the compliment on the sprite, but I think yours is prettier. ^^

**Comment by etherware-novice** [comment]
thx! sry hah, same idea different brain have a good day

**Pull request merged**
