### PR TITLE
Fixes chemical implant manual activation oversight

### PR DESCRIPTION
**Pull request by silicons**
*deathgasp is like an action button that works while stunned.

### CODE REVIEW

**Comment by Buggy123** [comment]
So, this goes from being able to activate chemical implants while stunned, to... not?

This isn't a "fix", this is a balance change.

**Comment by Ratvar** [comment]
make changeling adrenal stop working when he is stunned and call it a fix

**Comment by AlexTheSysop42** [comment]
It's probably called a fix because #36021 was supposed to completely remove manual activation but missed this

👎 though, manual activation is cool

**Comment by kevinz000** [comment]
@AnturK I wasn't going to touch the other functions, just remove manual usage

**Comment by kevinz000** [comment]
@Buggy123 please do not comment false accusations when the last PR should have removed it entirely but you even commented on the debacle yet didn't notice it?

**Comment by ExcessiveUseOfCobblestone** [comment]
I agree kekhi, I'm just saying it was intended in the original pr. It's not a "fix" or "oversight" when that was explicitly allowed for in the previous pr.

**Comment by Buggy123** [comment]
>@Buggy123 please do not comment false accusations when the last PR should have removed it entirely but you even commented on the debacle yet didn't notice it?

I don't remember it, so I noticed it, commented on it, and then forgot.

**Comment by ExcessiveUseOfCobblestone** [comment]
kekhi is wrong because it explicitly quotes in the "debacle" that the author intentionally left out *deathgasping

**Comment by kevinz000** [comment]
oh it was pointed out already
well the problem with that afaik that made oranges reopen and speedmerge it was they're being used for adrenals by security/otherwise instead of their intended purpose considering they're on a prisoner management console. my pr that actually worked never specified the deathgasping issue.

**Comment by improvedname** [comment]
who cares just remove it lol
#drama station protect an unbelanced feature like theres no tommorow

**Pull request merged**
