### PR TITLE
Fix monkey AI runtime because Mothblocks didn't listen to AnturK.

### PR DESCRIPTION
**Pull request by Timberpoes**
## About The Pull Request

:fire::fire::fire::fire::fire::fire::fire::fire::fire::fire:

image

:fire::fire::fire::fire::fire::fire::fire::fire::fire::fire:

Runtime introduced by #60667

Copy-paste error in proc refactor in `/datum/ai_controller/monkey/proc/TryFindWeapon()` means that invalid arguments are passed to the controller's `queue_behavior()` proc.

Other conversions were done in this style:
image

But this single conversion retained the current_behaviours arg:
image

This has been cleaned up and should stop my local runtiming every 30 seconds unless I purge all monke from the world.

## Why It's Good For The Game

Feex.

## Changelog
:cl:
fix: Fixed runtime in monkey AI which would prevent monkey from pickpocketing weapons or picking weapons off the ground.
/:cl:

### CODE REVIEW

**Comment by Mothblocks** [comment]
my pr already fixed it you're fixing something else

**Comment by Timberpoes** [comment]
> 
> 
> my pr already fixed it you're fixing something else

Which PR?

**Comment by LemonInTheDark** [comment]
Your pr fixed one runtime, missed the rest of em.

**Review by LemonInTheDark — APPROVED** [review]

**Comment by Timberpoes** [comment]
> 
> 
> Your pr fixed one runtime, missed the rest of em.

There are multiple queue_behaviour runtimes? Which PR? Aaaaaaa.

**Comment by LemonInTheDark** [comment]
https://github.com/tgstation/tgstation/pull/60964

**Comment by Mothblocks** [comment]
i ran ci twice on a sporadic error and it passed both times

**Pull request merged**
