### PR TITLE
Reduce number of space z-levels on Kilo so it OOMs slower

### PR DESCRIPTION
**Pull request by SpaceManiac**
might help

### CODE REVIEW

**Comment by optimumtact** [comment]
most of it is lighting objects and corners

**Comment by optimumtact** [comment]
it's not using near space tiles for all of space is it?

**Comment by SpaceManiac** [comment]
this more works around the problem than solves it. removing z-levels is an easier way to lower memory usage than rearranging the entire map to cover less surface area

**Comment by actioninja** [comment]
Normally we're not really butting against the memory limit, I'm convinced there's some kind of leak and not neccesarily that kilo is too complex.

This is fine in the mean time though.

**Comment by optimumtact** [comment]
What do you mean? We're well above 1G every round

**Comment by actioninja** [comment]
It's not like we have *tons* of headroom but why kilo in particular is the only one that hits memory limits late into a round? Other maps can run long rounds just fine, and if kilo was too complex shouldn't it have memory issues early into the round?

**Comment by Taylorkills2** [comment]
I mean at least it's trying something, I don't think the problem happens on lowpop, so I don't think it's testable without testmerging it.
 If nothing else this is a good testmerge candidate to see whether you can get a medium/highpop Kilo round to go beyond about 1hr&10min without crashing.

**Pull request merged**
