### PR TITLE
[APRIL FOOLS] Streamlines the Map Rotation

### PR DESCRIPTION
**Pull request by Zytolg**
Currently, the /tgstation/ map roster is an unstandardized mess, with many stations being behind in feature upkeep. Since we (the mapping team) are currently too busy pursuing our own projects (see new maps), we have decided to remove maps from the rotation and focus the experience all into what we feel our currently our best maps.

## About The Pull Request

This PR introduces a brand new maptainer approved map, [Pheobe](https://www.youtube.com/watch?v=_L-CYkXmJzw)- wait.. *Ahem- Phobos 4 Station. Setting wise, this station takes place in a moon that orbits a planet recently acquired by NanoTrasen. The planet, designated as Mars 4, is a tribute back to Nanotrasens orgins on mars, and is the 4th planet to be christened as such by the Megacorperation. The 3 moons, are naturally dubbed as Phobos 4, Deimos 4, and _{we shot this one down with a shiny new CANNON_}. More lore on the station itself will be available in the lore repository at a later date.

The station itself is the first step in an ongoing project by the tgstation mapping team to reinvent the gameplay experience from a map standpoint. For a very much time now, players have struggled, and made it very well known, that our current stations are just simply too small, and there just simply is not enough freedom to truly engage in the centers of emergent gameplay, those being atmospherics, construction, and lastly, but most importantly, looting and prolifically exploring maintenance. Upon review of the current maps, feature list, and observing at least 100 rounds on Terry & Campbell, we have come to the same conclusion. Phobos station shrinks many oversized overabused, and frankly boring parts of the conventional station design that we have all come to know. With all that new space, we've created even more maintenance and construction space. Don't worry, there are plenty of secrets and loot to find within this new maintenance labyrinth. While Departments did get smaller, that doesn't mean they got worse. Downsizing these spaces really allowed us to create detailed and unique experiences that players will now doubt appreciate. There's a lot of character to this station, and we think that will be one of it's biggest strengths.

While this is only part [1] of [Many]. I expect this to set a new precedent for how map design is considered moving forwards in addition to hyping up what is to come. 

Onto some more administrative bits, as per map policy, this Map will replace Metastation in the map rotation. While Metastation is indeed our most up-to-date, played, and perhaps even our bar-setting map, we at the mapping team feel that it sets a negative bias towards newcomer maps to the rotation. It's been a good long run since 2015, and we pay our respects to it for all it has done for /tgstation/.
**Metatstation is to be removed from the map rotation permanently** (excluding event content)

Due to this being a multi-stage project, Deltastation has also been removed from the map rotation in order to create room for the soon to come stage 2 map of the project. This is also being done to give newer maps such as Tram and Icebox more time in the spotlight, though we expect this new station to dominate the scene. Kilostation was a candidate for removal since it's simply too high quality for our map rotation, but due to maptainer mandate, Kilostation still has at least 3 more months in the map rotation. 

This station reuses metastations shuttles, but adds a secret new whiteship. _See if you guys can find _it.__

## Why It's Good For The Game

Our code is full of techdebt, and everyone knows it. The same goes for our maps, and I dub eet _Map Debt_. As has been said by our glorious overlord and commander-god, if nobody is going to maintain our maps, then we should toss 'em out. This PR takes a different approach by removing the only map in the rotation that sees regular upkeep, therefore freeing up people to work on bringing our other maps up to parity with features, while giving players time to appreciate them too. 

Introducing a new map, while freshening things up for the game as a whole, also sets the standard for what is to come. This is a massive project being undertaken by the [mapping team](https://www.youtube.com/watch?v=Qh9KBwqGxTI), and we are getting to a point where we can happily reveal what the in's and out's of our new mapping vision is- headed by our glorious leader @EOBGames (maptainer). 

Metastation and Deltastation are old and aging designs, that though popular, set a negative precedent for new map reception. This ("mapnamehere" isn't "meta/delta") is ultimately harms the game by discouraging newcomer mappers from further improving their maps due to disproportionate negatively charged unhelpful feedback. We also believe that this will give newer maps an actual chance to receive attention, rather than being played on a server twice a day (due to the outcome being a vote between two -currently- unpopular maps). 

Congratulations on getting this far for an April Fools post. 

## Changelog
:cl:
add: Phobos 4 Station
add: The Nanotrasen Courier Ship
del: Sayonara Metastation
del: Deltastation got code Delta'd
balance: The new map rotation should have a more even dispersion of votes.
fix: Negative Mapping Feedback: Forever. 
code: Shuttle stuff
config: Removing Metastation and Deltastation. Sets Phobos 4 as the default. 
/:cl:

**No, I'm not going to show pictures, because these things are better as a surprise, and has already been reviewed by mapman.**

### CODE REVIEW

**Comment by Sparkezel** [comment]
My only problem is that tram just doesn't fucking exist on terry so it will me stuck on ice

**Comment by LemonInTheDark** [comment]
I sure do love sending alerts, april fools was a great idea, etc etc

**Comment by Zytolg** [comment]
Added cams to the bridge just now, so this can be updated when someone sees this. Sleepy time for me.

**Comment by Zytolg** [comment]
Shuttle had a pathing issue with some really old plates. Straight up removed them and things should pass the checks now.

**Pull request closed without merging**
