### PR TITLE
PDA Fixes and Changes and Cargo Console Fix

### PR DESCRIPTION
**Pull request by Peliex**
## About The Pull Request

Was updating the documentation about PDAs on the wiki and saw some minor issues, threw in the bug fix for issue https://github.com/tgstation/tgstation/issues/75231 as well because why not.
Also added the ability to put medipens into PDAs, they're small and pen-like enough, right?

## Why It's Good For The Game

Cargo console double printing makes it even more paperwork hell than it's supposed to be.
Paramedics not having their own PDA color scheme seems mostly like a carryover from the old PDA system.
I don't even know how to value giving the ability to place medipens into the PDA because it honestly is not something almost anyone will ever do.
Giving QM the robocontrol app twice does nothing, removing the line is just a line saved.

## Changelog

:cl:
add: Can now put medipens into crew PDAs
add: Gave Paramedics a different colored PDA
add: Gave Psychologist their own PDA
imageadd: New alternate PDA pattern
imageadd: Changed some PDAs to use the new alternate pattern
fix: Sending back the Cargo Shuttle will no longer print a shopping list.
fix: removed the duplicate robocontrol program from QM's PDA
/:cl:

New PDA Patterns
Updated Captain to use new pattern

### CODE REVIEW

**Comment by JohnFulpWillard** [comment]
What do the new PDAs look like in-game?

**Comment by Peliex** [comment]
> What do the new PDAs look like in-game?

I will upload some images, but for now I'm actually making some more changes to the PDA designs, so I will have an image of all of them to show.

**Comment by SyncIt21** [comment]
Fixes #75231

**Comment by EricZilla** [comment]
Hell yeah double stripe reimplemented now everyone looks a little more unique

**Review by Twaticus — APPROVED** [review]

**Review by Wallemations — APPROVED** [review]
PDA sprites look good

**Pull request merged**
