### PR TITLE
Overhauls the entrance to Engineering on PubbyStation to allow for better access control, makes techfab accessible to Atmos.

### PR DESCRIPTION
**Pull request by TheVekter**
## About The Pull Request

As it is right now, the techfab isn't available to Atmos techs that start without skeleton crew access. I've made up an updated lobby for Engineering that adds a few details and gives both departments access to the techfab. This also necessitated moving the Atmos counter and input/output pipes a bit.

image

## Why It's Good For The Game

Better access for Atmos techs to actually use the cool shit R&D can get them.

## Changelog
:cl:
tweak: Reworked the entrance to Engineering on PubbyStation to give Atmos techs access to the techfab on non-skeleton shift rounds.
/:cl:

### CODE REVIEW

**Comment by TheVekter** [comment]
Ah yes the usual map bullshit, won't know if I actually fucked the merge until map diff bot finishes.

**Comment by Farquaar** [comment]
Screenshot?

**Comment by TheVekter** [comment]
> Screenshot?

Added.

**Comment by TheVekter** [comment]
I need to redo most of this because the file it was based off of was *violently* broken in the usually weird ways .dmm files get broken. Gives me a chance to clean some of it up, at least.

**Comment by TheVekter** [comment]
Added an APC to the bottom right of that room and made it its own section instead of just stealing power from the hallway. I also moved those air meters over to the left wall.

**Comment by spookydonut** [comment]
Looks good!

**Pull request merged**
