### PR TITLE
OH GOD HOW DID THE MAPS GET SMALLER?

### PR DESCRIPTION
**Pull request by Jalleo**
Space ruin maps are now a bit smaller in general and standardized to use near station where lattices are at and other generic standards for stations.

### CODE REVIEW

**Comment by Jalleo** [comment]
There is possibly one or two ruins which I didnt directly touch but mapmerged by laziness. I apologise.

**Comment by calzilla1** [comment]
Did you touch the maps at all?

**Comment by ShizCalev** [comment]
You can shave 1 more row off abandonedzoo

**Review by ShizCalev — CHANGES_REQUESTED** [review]
https://github.com/Jalleo/-tg-station/pull/4

**Comment by Jalleo** [comment]
Okay doing that now

**Comment by Jalleo** [comment]
@calzilla1 most maps had space/noop tiles removed that were not needed as they were extra rows. Also added nearstation to the lattices locations because it kinda solves the light weirdness you can get sometimes.

**Comment by Jalleo** [comment]
It is done.

**Review by ShizCalev — APPROVED** [review]

**Pull request merged**
