### PR TITLE
Added theatre access to bartender

### PR DESCRIPTION
**Pull request by FluffTheMoth01**
Signed-off-by: Space Prius <bubba041102@gmail.com>

## About The Pull Request

This simply adds theater access to the bartender.

## Why It's Good For The Game

90% of the costumes can't _tastefully_ be used by the clown or the mime, and would honestly fit in for the bartender. This also allows extra theming to be done in the bar, and prevents the bartender from coming to the HoPline every round asking for it anyway.

## Changelog
:cl:
tweak: Bartender now has Theatre access
/:cl:

### CODE REVIEW

**Comment by Qustinnus** [comment]
bad

**Comment by optimumtact** [comment]
maid cafe

**Comment by tralezab** [comment]
It's his bar with a theatre, but not his theatre backroom?

**Comment by Dorsisdwarf** [comment]
Reiterating my previous statement that I will bully any bartender I see in a stupid clown outfit.

**Pull request merged**
