### PR TITLE
you can now craft glass floors on lattice

### PR DESCRIPTION
**Pull request by ghost**
:cl: qustinnus
add: you can now craft glass floor on lattice by using (reinforced) glass sheets on it.
/:cl:

### CODE REVIEW

**Comment by TheBonded** [comment]
Will the glass floor show space underneath it, or show the z level below it like on icebox?

**Comment by Qustinnus** [comment]
that depends on whats under it, space or the zlevel below ;)

**Comment by Fikou** [comment]
can you make glass floors be damagable then so we dont have craftable indestructible floors

**Comment by Qustinnus** [comment]
need to figure out how to fix the OOP of floors

**Pull request closed without merging**
