### PR TITLE
[READY]Adds Combat Mode!

### PR DESCRIPTION
**Pull request by silicons**
:cl:
experimental: Combat Mode has been added! Toggle it with the button or with the key "C" in hotkey mode! While it is enabled, rightclick will be an in game action instead of opening a menu like it normally does! There is a verb in OOC tab for if context menus get stuck off.
rscadd: While combat mode is activated, rightclicking on someone at a distance will display a message based on your current attack intent! More features to come!
code: Detect rightclicks by checking for params["right"] in procs in the clickchain. Params will be expanded to attack_hand and UnarmedAttack and species attack processes. 
/:cl:
Maintainers: This also shifts several screen defines into new screen_objects subfolder for readability!

remove the code improvement label this isn't an improvement ;)

sound/sprite sources and code inspiration kudos to @deathride58 

### I AM NOT PORTING CITADEL'S COMBAT SYSTEM, JUST PUTTING IT OUT THERE BEFORE ANYONE THINKS I'M ABOUT TO COMMIT TREASON OR SOMETHING.

### CODE REVIEW

**Comment by Shadowflame909** [comment]
I see damage numbers going up. Does this buff unarmed combat what's going on Kev...or is this combat mode from citadel where you gain stamina drain.

**Comment by kevinz000** [comment]
@Shadowflame909 i am not going to port citadel's new combat system .

**Comment by Shadowflame909** [comment]
Well that's pretty great. Speed merge when.

**Comment by Repukan** [comment]
Can we port DREAMER too

**Comment by deathride58** [comment]
The sound for combat mode activation is from lifeweb/interbay, with a heavily modified version of the same sound for the deactivation noise. It was mainly intended as a placeholder until I could slap together better/less legally questionable sounds, but I got too lazy to actually replace 'em.

One less thing for us to maintain over at cit, though, woo! \o/

**Comment by davethwave** [comment]
What's DREAMER?

**Comment by 81Denton** [comment]
>What's DREAMER?

One man murderbone with an M. Night Shamalayan twist if the dreamer greentexts

**Comment by Barhandar** [comment]
>first of all, get rid of the right click context menu in its entirety. it's incredibly slow and obsolete since shift click examine and ctrl click pull exist, as well as alt click to view everything on a tile.

Alt click view everything is _much_ slower to use on small lists and has far lower information density.
>the walk/run button as well as resist buttons could both be axed with minimal tweaks and nothing would be lost.

Lol no.

Basically what WJohn said about removals is terrible and stupid but what they said about additions, namely this PR, is good.

**Comment by kevinz000** [comment]
right click context menu is very useful but you will not ever end up using it in combat unless you want to die from the delay it'll cause.
you know what's slower than right click context menu? an interface for bringing up vv/whatever/examining/pickup/verbs rather than letting people right click. 
there is a hotkey for this if you did not notice too, unless you somehow don't play with hotkeys?
this allows for special attacks and interactions and better frameworks to make combat less shit. this pr will not do that by itself, however.
i don't see how it's worse to allow people to right click which is a button right next to lmb which they'll be using the most. i also don't see how changing intents is hard when there's hotkeymode and nonhotkeymode people dealt with it already until now.

**Comment by Barhandar** [comment]
>right click context menu is very useful but you will not ever end up using it in combat unless you want to die from the delay it'll cause.

Inb4 people will start dying because they forgot to switch to combat mode and right-clicked.

**Comment by subject217** [comment]
>first of all, get rid of the right click context menu in its entirety. it's incredibly slow and obsolete since shift click examine and ctrl click pull exist, as well as alt click to view everything on a tile
Used an RCD recently WJohn? Or a tape recorder? Are you going to make those work with nothing but shift clicks and alt clicks?

**Comment by AlexTheSysop42** [comment]
Move to top is only in the context menu, it's buggy but it works sometimes

**Comment by Shapsy** [comment]
Right clicks aren't fantastic but alt clicking and having to move over to the other side of your screen to sort through a stack of things on a tile is pretty awful

**Comment by Spaceinaba** [comment]
maybe I have turbo tism but like I use alt clicks so much I don't think I have right clicked on anything other than my suit to turn suit sensors on in like 400 years

**Comment by AlexTheSysop42** [comment]
Object --> adjust suit sensors

**Comment by mattroks101** [comment]
Oh nice InterLifeTG. I'm glad my work could be watered down to the point that a fraction of it is finally PR'd to TG.

In all seriousness though for what point? Unless you actually have active plans to rework all of combat then what's the point of even adding this?

**Comment by kevinz000** [comment]
@mattroks101 I believe I've stated the intention to do so a month ago

**Comment by kevinz000** [comment]
Gotta start somewhere.

**Comment by qbmax32** [comment]
We lifeweb now boys

**Comment by ninjanomnom** [comment]
As I said in #coderbus I'm only in support of this if the right click dropdown menu is removed and all the things using it are changed to something else. Until then I'm with wjohn.

**Comment by PKPenguin321** [comment]
i'm confused as to why this is even needed? doesnt seem to do anything in its current state

**Comment by kevinz000** [comment]
@PKPenguin321 so coders can add rightclick functions to items like alternate attacks.
I also have bigger plans for combat mode in the future. I'm adding it now because atomic pull requests, and it's nice to have people get used to toggling it and not get overwhelmed later
@ninjanomnom It's vital for some things though, how would I replace it? Admins need it and people need it because fuck altclicking, and popups are laggy as shit.

**Comment by ninjanomnom** [comment]
Yes people need it and replacing the dropdown functionality with something that works would be the problem. Nonetheless I'm still against this until that's done. There are options other than opening popups.

**Comment by kevinz000** [comment]
maybe i am approaching the problem the wrongw ay

**Pull request closed without merging**
