### PR TITLE
Fixes last minute shuttle buys

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
Buying the meteor shuttle 1 second before docking results in it instantly hitting everyone without warning

### CODE REVIEW

**Comment by HankMoodyExperience** [comment]
top kek

**Comment by Cyberboss** [comment]
F E A T U R E

**Comment by Armhulen** [comment]
FUCKING FEATURE

**Comment by improvedname** [comment]
Shuttle transformers

**Comment by improvedname** [comment]
So will this remove the ability to buy shuttle aslong its called?

**Comment by KorPhaeron** [comment]
Yeah

**Pull request merged**
