### PR TITLE
bad mafia

### PR DESCRIPTION
**Pull request by Ghilker**
Remove distasteful reference to a IRL mafia and terrorist organization and a racist section in the description of the "Cosa Nostra Starter Pack"
Replace the name with "Mafioso Starter Pack".

## Changelog

:cl:
del: change the name of the "Cosa Nostra Starter Pack" to a more generic "Mafioso Starter Pack", remove racist innuendo in the description
/:cl:

### CODE REVIEW

**Comment by InsaneRed** [comment]
what

**Comment by PolishUser** [comment]
Is this a bait? Where is the racist part?

**Comment by Krysonism** [comment]
Peal clutching PR.

Cosa nostra starter pack has some flair. Mafia starter is just bland.

As far as the description goes , everyone knows you have to be Italian by blood in order to become a made man.

**Comment by SuperNovaa41** [comment]
Ghilker they wont hurt you

**Comment by SuperNovaa41** [comment]
Also i dont think this counts as a removal... Unless you want to lose the gbp for this

**Comment by Ghilker** [comment]
> Simply using the name of a group is not racist on our part, nor is it condoning their actions

the racist part is not the name of the group, is literally this part `ethnicity-based racketeering operation`
Also i know is not condoning their actions, and i don't see one reason to not remove them then

**Comment by SuperNovaa41** [comment]
> > Simply using the name of a group is not racist on our part, nor is it condoning their actions
> 
> the racist part is not the name of the group, is literally this part `ethnicity-based racketeering operation` Also i know is not condoning their actions, and i don't see one reason to not remove them then

Having a generic `Mafia` to replace it as lame, as it least replace it with something

**Comment by Ghilker** [comment]
> Having a generic `Mafia` to replace it is lame, at least replace it with something interesting

You can come up with the name in game if you really want, i won't be making an interesting name for it, stop romanticizing organized crime

**Comment by SuperNovaa41** [comment]
> > Having a generic `Mafia` to replace it is lame, at least replace it with something interesting
> 
> You can come up with the name in game if you really want, i won't be making an interesting name for it, stop romanticizing organized crime

Wanting creative names for things ≠ romanticizing crime
Stop trying to bend my words

**Comment by Edelor68** [comment]
Acknowledging ethnicity or that something is ethnicity based is not racist. The mafia may have offshoots in other countries, but as rdragan wrote, is an Italian organization.
On top of that, mentioning or talking about a group does not inherently carry a judgement with it.
If the description would say something about how dope the mafia is maybe this would be a different story but there is nothing like that here.
We can't remove every mention of something that could have something bad associated with it.

**Comment by Mickyan** [comment]
There's no benefit to keeping this it's in poor taste and clearly it bothers someone

I can see how you might think otherwise when your knowledge of the subject doesn't go past movies and tv shows

**Comment by Ghilker** [comment]
Is is absurd that i want to remove a terrorist group name from the game? Cause if it is well, it makes me question what the hell is wrong with you. I don't think that an Isis cargo pack would be accepted, so why this one is good? 

I'm not advocating to remove the mafia game or term, because is a generic term, i just don't want a IRL criminal group in the game files. Is it that bad?

**Comment by Iamgoofball** [comment]
:+1:
i genericized the Mafia and Mob in Families to avoid issues like this

**Comment by MetalClone** [comment]
coming up with some in-universe ss13 names as a replacement would be more befitting of a solution than simply changing it to just Mafia. Perhaps Plasma Punk Starterpack and "set up your own resource based-racketeering" something of the sort. Supermatter, Bluespace could all be good alternatives.

**Comment by Krysonism** [comment]
How about we accept that this is a fictional work for adults and not a morality play for school children.

If a Hollywood movie or a novel mentioned  x bad group or bad person, you wouldn't bad an eye, but when it comes to our game some people turn into Tipper Gore on steroids.

You can't always cater to the most sensitive person with an internet connection.

The correct approach is to diagnose a lack of testicular fortitude and prescribe a dose of grow a pair.

**Comment by Mickyan** [comment]
It's called setting a consistent tone, if you want to eat babies while wearing a nazi uniform there's probably other codebases where you can do that

**Comment by Ghilker** [comment]
> How about we accept that this is a fictional work for adults and not a morality play for school children.

Oh it still is, that's why mafia, traitor, murderers, suicide, and other adult themes are still there, but the difference here is that those are generalized and not directly referencing a IRL terrorist group that is currently damaging my culture and actively killing people.

**Comment by githubuser4141** [comment]
> How about we accept that this is a fictional work for adults and not a morality play for school children.
> 
> If a Hollywood movie or a novel mentioned x bad group or bad person, you wouldn't bad an eye, but when it comes to our game some people turn into Tipper Gore on steroids.
> 
> You can't always cater to the most sensitive person with an internet connection.
> 
> The correct approach is to diagnose a lack of testicular fortitude and prescribe a dose of grow a pair.

Kinda agree, but unfortunately a lot of people who play this are underage and the admins don't seem able or willing to get rid of them. IMO the server should share underage bans from other 18+ severs like VG, Fortuna, Skyrat, etc if the admins don't feel comfortable asking people for their ID.

**Comment by BlueMemesauce** [comment]
Cosa Nostra is literally a terrorist organization which has commited bombings that killed multiple people. For example: https://en.wikipedia.org/wiki/Via_dei_Georgofili_bombing

Yes, there are syndicate operatives that bomb the station, but the syndicate doesn't actually exist. Would it be acceptable if there was a crate for Al-Qaeda or Ku Klux Klan equipment? No, of course not.  Cosa Nostra is a real organization that exists in the real world and has killed real people with terror attacks.  Its absurd that it should be included just because it is creative or interesting. It shouldn't be included in the game, even if people unfamilar with it don't see it as offensive.

**Comment by SuperNovaa41** [comment]
> Cosa Nostra is literally a terrorist organization which has commited bombings that killed multiple people. For example: https://en.wikipedia.org/wiki/Via_dei_Georgofili_bombing
> 
> Yes, there are syndicate operatives that bomb the station, but the syndicate doesn't actually exist. Would it be acceptable if there was a crate for Al-Qaeda or Ku Klux Klan equipment? No, of course not. Cosa Nostra is a real organization that exists in the real world and has killed real people with terror attacks. Its absurd that it should be included just because it is creative or interesting. It shouldn't be included in the game, even if people unfamilar with it don't see it as offensive.

You're right, by making a mere mention of their name we are also participating in terrorism

**Comment by Ghommie** [comment]
> 
> Is is absurd that i want to remove a terrorist group name from the game? Cause if it is well, it makes me question what the hell is wrong with you.

It's not absurd, but pulling a damnatio memoriae on anything with an underlying negative connotation can be a touchy thing to do. Nothing is wrong with you or them, some people just don't perceive it as offensive and your actions as justified as you do. 

>I don't think that an Isis cargo pack would be accepted, so why this one is good?

You ought to understand that some topics are more sensitive than others and that their sensitivity is not universal. This is due to a number of factors such as social phenomena, culture, history (personal or not) and most importantly recent events and media. The example you have done is actually one hell of hot potato because of a series of events that are well-know around the world and are not worth mentioning. Anyway, comparing the two like that is slighty tactless and sensationalist. It wouldn't be denied only because of its association with real life terrorism, but also for being too controversial much like references to the national-socialist party or slurs (well, this is also due to the ToS).
These are only some considerations, I'm not against the changes per se (though the real crime was not also removing spaghetti meatballs).

**Comment by Pickle-Coding** [comment]
We don't need to be roleplaying as 19th-21st century terrorists in a game set in the 26th century. The people that do should he finding a better gimmick.

**Comment by TheRealScarHomie** [comment]
ay tone

**Comment by psychicweaver** [comment]
gabagool? ova' heaaaaah

**Comment by psychicweaver** [comment]
Italian_American

**Comment by cacogen** [comment]
you know quasimodo predicted all this

https://www.youtube.com/watch?v=udfsweRoops

**Comment by Kylerace** [comment]
why are you people like this

**Comment by Krysonism** [comment]
Maints are so eager to kowtow to the most annoying types of people in the world they forget the 24 hour rule.

**Comment by Kylerace** [comment]
> 
> 
> Maints are so eager to kowtow to the most annoying types of people in the world they forget the 24 hour rule.

i dont understand im not kowtowing to the people who hate this pr at all in fact im doing the opposite of what they want.

**Comment by optimumtact** [comment]
@Kylerace why did you speed merge this? ???

**Comment by Kylerace** [comment]
@optimumtact i merged it 6 hours before 24 because i didnt look at the time

**Comment by optimumtact** [comment]
sus

**Pull request merged**
