### PR TITLE
Adds Station's Date To NTos Window (check the time+date on your tablet!)

### PR DESCRIPTION
**Pull request by san7890**
## About The Pull Request

Hey there,

Since the transition from the old HTML PDAs to the modern TGUI Tablets, we've been missing that hole in our life... going "uuuuhhhh" and then checking our phones to figure out what month, day, or even year it is!  Much easier to glance at your phone than to tramp around the station in desperate search of a calendar. This PR just re-adds that bit of missing flavor by putting the date persistently.

## Why It's Good For The Game

image

Although I've memorized that the date in SS13 is our current year plus 540 years, 99% of the station hasn't. It's also good flavor to remind them that canonically, they're going through the same dates we are, just another 540 days in the present. We already communicate the time, so why not pass through the date as well (much like modern OS's)?

## Changelog

:cl:
qol: Nanotrasen realized they forget to implement the date function into the new NTos tablets, so they doubled back and added those next to the time.
/:cl:

### CODE REVIEW

**Comment by stylemistake** [comment]
This will overflow spectacularly when multiple programs are running, and on small windows.

**Comment by san7890** [comment]
> This will overflow when multiple programs are running, and on small windows too.
> 
> > just another 540 ~days~ years in the present

Yeah, I noticed that there was some weirdness with it overlapping with the "NTos" header if I tried to do something like "Sun, Oct 23, 2022". Do you think reducing the amount of excess characters, i.e.: "Oct/23/2022" would work instead?

**Comment by optimumtact** [comment]
image

**Comment by stylemistake** [comment]
Maybe it would make sense to hide a full date behind a tooltip?

**Comment by san7890** [comment]
> Maybe it would make sense to hide a full date behind a tooltip?

image

I got it to look like this now, decided to be more verbose with the date since we had the real-estate for it. The NtOS "logo" is off-center now, I tried to fool around with the settings (or creating a new divider class and fiddling with the scss file), but I couldn't get it to work to get back to the center. Is it okay like this, if not: please do let me know how I can get it back to be "centered" in the header.

**Review by stylemistake — APPROVED** [review]

**Pull request merged**
