### PR TITLE
Makes cyborg damage more... showy

### PR DESCRIPTION
**Pull request by dragomagol**
## About The Pull Request
Makes cyborgs blink yellow when they're dead. The icons were lying around in the code for some reason, so why not repurpose them?

Borg death blink:
https://www.youtube.com/watch?v=DtYSHSSZVs8

Makes cyborgs emit particles when they reach a certain damage threshold. Smoke for brute, sparks for burn. I think I want to tweak them a little more, but it's hard to troubleshoot when the particle editor keeps throwing a BSOD.

Borg particles:
https://www.youtube.com/watch?v=Xh64rZkrp-U

## Why It's Good For The Game
It's really really annoying when you're sitting dead in robotics and everyone assumes you're AFK because the roboticist isn't wearing a diagnostic hud (agony).

The particles I just think are cool flavour, plus it's a way for silicons to show actual signs of wear and tear.

## Changelog
:cl: Tattle
qol: dead cyborgs now blink yellow lights
qol: damaged cyborgs have smoke particles when they've taken brute damage, and sparks for burn
/:cl:

### CODE REVIEW

**Comment by Loafin34** [comment]
can you change the mediborg's one so that it shows up on the big screen instead of down there?

**Comment by lizelive** [comment]
cool. how do you feel about smoke for burn / spark for brute

**Comment by alien3301** [comment]
Is the death blinking visible if the borg isn't looking at the camera?

**Comment by dragomagol** [comment]
> Is the death blinking visible if the borg isn't looking at the camera?

On some borgs it is! It depends on their light overlays. You can peek at them in the icondiffbot output.

**Comment by alien3301** [comment]
> > Is the death blinking visible if the borg isn't looking at the camera?
> 
> On some borgs it is! It depends on their light overlays. You can peek at them in the icondiffbot output.

You really should make it visible from any direction. Maybe add some tiny lights to borg sprites or smth.

**Comment by alien3301** [comment]
Actually you could just force turn on their headlamp with yellow like how malf AI delta does it. That would be pretty noticable.

**Comment by BHat0451** [comment]
The original sprites were actually for Ratvarian cyborgs IIRC, since when they were converted to Clock Cult they'd have yellow-orange eyes (the sprites used here) to give them away unless their headlamps were on (which led to headlamps constantly enabled being suspect for cyborgs)
A good reuse for an unfortunately otherwise abandoned thing

**Comment by krookodilehunter** [comment]
i feel like the burn sparks are a little hard to see, but otherwise these are great additions!

**Pull request merged**
