### PR TITLE
Lets ethereals wear underclothes

### PR DESCRIPTION
**Pull request by Iamgoofball**
## About The Pull Request

Lets ethereals wear underclothes

## Why It's Good For The Game

i dunno why we dont let people playing ethereals accessorize
also requested by a discord person
## Changelog
:cl:
add: Lets ethereals wear underclothes
/:cl:

### CODE REVIEW

**Comment by red-creature** [comment]
god goof i love you so much

**Comment by squi1-rasb** [comment]
Based

**Comment by Iamgoofball** [comment]
can someone restart the CI i got that rng syndicate card failure

**Comment by LemonInTheDark** [comment]
I don't want this. Ethereals are meant to be unique, different from humans. We've given them hair because people wanted to look different. We've given them beards for the same reason. I don't want to give them undercloths.

I'll be closing at 24 hours

**Comment by LemonInTheDark** [comment]
> can someone restart the CI i got that rng syndicate card failure

It's fixed on latest master, so if you merge it'll go away

**Comment by TheBonded** [comment]
> I don't want this. Ethereals are meant to be unique, different from humans. We've given them hair because people wanted to look more like humans, more customizable. We've given them beards for the same reason. I don't want to give them underclothes.
> 
> I'll be closing at 24 hours

@LemonInTheDark  but can't moths and lizards already do this? hell, I'm pretty sure even plasmamen can do it, though they're always wearing an envirosuit due to the oxygen in the air. Why single out ethereals?

**Comment by LemonInTheDark** [comment]
Yes. But moths and lizards are teetering on the edge of being bad races in the first place, and it makes me really sad to see something truly alien slowly degrade to human + lighting

**Comment by optimumtact** [comment]
k

**Pull request closed without merging**
