### PR TITLE
Makes wizard academy defender respect prefs

### PR DESCRIPTION
**Pull request by Shadowlight213**
I swear, at this rate I might just make a global ghost role pref for these things.

### CODE REVIEW

**Comment by Zilenan91** [comment]
It would likely be for the best for you to make there be a universal "Away Mission Antagonist" pref

**Comment by Shadowlight213** [comment]
@Zilenan91 wouldn't have a point really. Wizard academy is the only one with a popup.

**Comment by Zilenan91** [comment]
I guess, but in the future it could be useful, especially for that medieval battlefield away mission getting made right now

**Comment by Shadowlight213** [comment]
@Zilenan91 I'm pretty sure the medieval one wont use popups but will instead have the ghosts click on it. Wiz academy is the only one that uses the popup.
It would be better to make a global toggle really. But that's for a different PR.

**Pull request merged**
