### PR TITLE
Polished Bounty Hunters

### PR DESCRIPTION
**Pull request by dolphinemote**
## About The Pull Request

This PR gives a slight update to existing basic Bounty Hunters by giving them a new non-fullbright shuttle.
The shuttle is a small, double-bottomed fuel tanker that has a hidden room for a bluespace capture machine.
I took the binoculars and the bluespace launchpad, but gave them the contractor's helmet - it suits with one of their loadouts: it has spaceproof armor, but no helmet, which is why they used the basic EVA helmet before.
This PR also changes their old antag icon to a new one that looks like a prisoner or warden.

newHunterShuttle

proofOfTesting2

How it was before:
old

## Why It's Good For The Game

Previous shuttle looked really old, and fullbright stuff never really looked good.
Hope that also might add some flavor to the hunters.

## Changelog
:cl:
add: Basic Bounty Hunters now get a new shuttle and antagHUD icon.
fix: Removed a couple of lines from the area code that made old Bounty Hunters' shuttle fullbright
/:cl:

### CODE REVIEW

**Comment by Cheshify** [comment]
image
A few of these rooms are good but the ship has a severe case of "random open space without anything in there."
I would suggest removing that unused and inaccessible pod section, honestly. Overall shape of the ship is good too, I like that it isn't another perfectly symmetrical design. Also, you have this big stretch of plating that could go with some decals, dirt, or more proof of living space for the bounty hunters.

**Comment by Dirt-Dweller** [comment]
> image A few of these rooms are good but the ship has a severe case of "random open space without anything in there." I would suggest removing that unused and inaccessible pod section, honestly. Overall shape of the ship is good too, I like that it isn't another perfectly symmetrical design. Also, you have this big stretch of plating that could go with some decals, dirt, or more proof of living space for the bounty hunters.

From the second image, the big space by the interrogation room is filled with plasma gas (supposedly to help in interrogation), so putting things in there wouldn't make much sense. I do agree with you on that long strip, however.

**Comment by Cheshify** [comment]
> From the second image, the big space by the interrogation room is filled with plasma gas (supposedly to help in interrogation), so putting things in there wouldn't make much sense. I do agree with you on that long strip, however.

Even if it has a purpose, it just doesn't look very good or have a distinct way to access it. Even then, should the bounty hunters be given access to an absolute shitload of plasma? Maybe for refilling flamethrowers? Don't have it be just fluff, let them use it and justify why they should have access to it.

**Comment by Pumpkinoe** [comment]
the question is - is it a ship, or is it a box?

**Comment by DATA-xPUNGED** [comment]
While you're at it, can you add the IPC bounty hunter back in the form of an android? It was removed alongside IPCs and never replaced

**Comment by Cheshify** [comment]
image
I like this remap, so I'm going to nitpick more. The walls of this just don't look great with the diagonals on the inside, try putting them on the outside.

Also, you have *so much* unused space devoid of tiles or purpose. For these smaller ships, it's okay to tighten things up.

**Comment by Cheshify** [comment]
Also, basketball hoop but no basketball is a sin.

**Pull request closed without merging**
