### PR TITLE
Raises EMP flashlight cost

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request
edit: changing emp flashlight to 4 now, valid point brought up that you can literally just buy emp kits for 2 tc too instead of this

changes emp flashlight to 4 tc

i ded
## Why It's Good For The Game
-Emp flashlight has always been stupidly cheap compared to a lotta other stuff in the uplink for what its worth and capable of. Stops borgs, headsets, energy weaponry, and it even auto recharges in a very subtle manner, all for the cost of 2 tc. Plus some other stuff. Leaving the flashlight in surpluses untouched.

## Changelog
:cl: SuicidalPickles
tweak: EMP flashlights have had their cost changed to 4 telecrystals.
/:cl:

### CODE REVIEW

**Comment by ATH1909** [comment]
What if we made the radio jammer block out the names next to comms chatter so that AIs and such couldn't use them to track people?

**Comment by imsxz** [comment]
Ided

**Comment by imsxz** [comment]
wait no don’t upvote my comment I was shitposting

**Comment by anconfuzedrock** [comment]
why would you want more people buying large emps
radio jammer isn't the worst traitor item because of its price, it's the worst traitor item because it doesn't even entirely jam the fucking radio

**Comment by ExcessiveUseOfCobblestone** [comment]
large obvious emps get you killed faster than stealthy ones.

**Comment by py01** [comment]
It's not to hard to alter the jammer to completely block radio

**Comment by BeeSting12** [comment]
Lower the jammer, leave the EMP light

**Comment by OverlyGeneric** [comment]
emp flashlight was needing a cost-bump anyway.

shit's broke, yo.

**Comment by PKPenguin321** [comment]
Brief history
- secborgs exist and are cringe and OP
- much debate boils down to "just emp them loll"
- only readily available emp to traitors is the kit (which included the fflashlight and was more expensive though I forget exactly how much)
- i make a pr to separate the flashlight from the kit and lower the price of both to 2 TCs in response
- secborgs are now removed

This PR is probably fine

**Comment by necromanceranne** [comment]
Flashlight fits into the ebow+esword budget now so you can drop someones comms after you stun them. Not sure if ebow is even remotely in a good spot since the stamina changes but before it was a really damn good combo.

**Comment by Anonmare** [comment]
EMP flashlight is grossly powerful for its price to be honest.

It's a perfect borg stunner, drains energy weapons dry, is a discount emag for weaponsing defibs, a better mutepen than the actual mutepen and against fully augged people - it's effectively an e-sword (it does about ~15 burn to mechanical limbs. Each.)

**Comment by AnturK** [comment]
Went with #44313 for now, so the jammer cost change might require rethinking.

**Review by ExcessiveUseOfCobblestone — CHANGES_REQUESTED** [review]
Just touch EMP flashlight, Radio Jammer got a buff and I haven't been able to gauge if it is worth a TC change (especially a lower one).

**Pull request merged**
