### PR TITLE
Revert "Removes alien driveby"

### PR DESCRIPTION
**Pull request by Cheridan**
Reverts tgstation/-tg-station#12163

1v1 me

### CODE REVIEW

**Comment by WJohn** [comment]
FOURTH TIME'S THE CHARM RIGHT?

**Comment by Cheridan** [comment]
you can do it if you believe

**Comment by Aloraydrel** [comment]
DETERMINATION

**Comment by Dorsisdwarf** [comment]
Damnit cherry, mine was so much more fluent in why aran is a butt

**Comment by GunHog** [comment]
The one person with the power to defeat Aranclanos! :+1:

**Comment by bgobandit** [comment]
in before close

**Comment by Thunder12345** [comment]
Yolomerge before Aran sees it

**Comment by GunHog** [comment]
It does not matter. Cheri is the repo owner. If Aran tries to stop him, Cheri can take away his maintainer rights.

**Comment by Dorsisdwarf** [comment]
Aran technically can't stop *any* maintainer's PR, since they can  merge it before he sees it.

**Comment by Anonus** [comment]
PRAISE THE CHERIDAN

**Comment by Wyzack** [comment]
Cheriden has gone from villian to hero of the people. Praises be

**Comment by Aliannera** [comment]
The great coder battle of our time. Praise be Cheridan.

**Comment by TechnoAlchemisto** [comment]
We live in a world without boundaries

**Comment by freerealestate** [comment]
you couldn't have just reopened the other one?

**Comment by Cheridan** [comment]
@freerealestate sure but that's lacking in impact

**Comment by freerealestate** [comment]
i see

**Comment by Incomptinence** [comment]
THEY SAY CHERIDAN'S CHESTBURSTER GREW THREE SIZES THAT DAY.

**Comment by Dorsisdwarf** [comment]
Context: 
>"Yeah this is just awful, please revert before it's too late."

>"have you ever uh considered
how retarded this is"

>"plz revert fam this nerf is smh"

>"'Im just going to sidestep the whole "how bad a change is this" discussion"

>"Change is pretty stupid"

>"Why are you "testing this" by merging, when we had that whole thing that lets us test pr's WITHOUT MERGING?"

>"Why leave the stun in at all when you are this salty"

> "What the actual fucking flipping fuck I've never been this disgusted that something got merged before, not even removal of cigarette internals. Why would anyone think this was a good idea?
Facehuggers take two minutes to implant. They're consumed the moment they land on someone's face, and if they're removed during those two minutes, the implantation is canceled. This means xenos need to flawlessly keep every infection victim down for the full two minutes to infect anyone, lest they get up for a split second and remove the facehugger.
There're plenty of reasonable balance changes if you have a problem with facehuggers' being stun mines/throwing weapons in addition to xenos' way of reproducing, but this way of fixing it is just confusing (especially since there ISN'T A CHANGELOG ENTRY) and makes facehugging mechanically clumsy."

>"Yay lets neuter our round ending antags that are not all that common anyways, despite no one thinking it was a good idea besides Aran and completely sidestepping our ability to test things without merging them. Quality."

>" so there's a threat that I can't just walk up to with a fireaxe and beat to death?"

>"this severely crippled early game hive play."

>":-1: xenos are supposed to be round enders. This is stupid."

>"enjoy never getting victims as a queen unless you can find monkeys, or people line up for your spit."

>"this turns alium into a test of who has a better ping: the alium clicking to stun someone or the target clicking to remove facehugger after getting up"

>"Do not make dramatic balance changes like this."<-MSO

>"But yea, this is just dumb. I feel no reason to repeat the reasons already given in this thread."

>"by nerfing xeno's ability to implant people, you are going to have a lot more salty ghosts as there's going to be more corpses and less new xenos meaning more people in deadchat not getting back in the round."

>"It's pretty obvious that aran asked raz to merge this"

>"WHY. NO ONE WANTED THIS."
>"You still need to drag them down the instant they're facehugged and keep them down uninterrupted, at which point you may kill them because screw keeping these guys alive anymore, you'll have far too little time to do even that because of this change."

>"t it would be nice if we could void the one week revert rule for this case due to it being merged without the majority consent of coderbus and the playerbase."

>"Inb4 aran closes any reverts with "this is stupid""

*"It it would be nice if we could void the one week revert rule for this case due to it being merged without the majority consent of coderbus and the playerbase."*

**Comment by Bawhoppen** [comment]
Force merge it yourself cheri

**Comment by Anonus** [comment]
The one week revert rule isn't even a thing as far as I know.

**Comment by Aranclanos** [comment]
this is a comment

**Comment by Giacom** [comment]
>leaving in the bad coding formats

Wow you're so lazy Cheridan :sweet_potato:

**Comment by Aranclanos** [comment]
OH WOW NICE DONE CHERI WOW

**Comment by Aloraydrel** [comment]
Lmao

**Comment by duncathan** [comment]
Can't even be cucked by his boss

**Comment by Thunder12345** [comment]
:fire::fire::fire::fire::fire:

**Comment by Miauw62** [comment]
its been 5 days and still everybody hates this

fite me irl

**Comment by peoplearestrange** [comment]
I came for the PR, stayed for the drama.

**Pull request merged**
