### PR TITLE
Automatic TGS DMAPI Update

### PR DESCRIPTION
**Pull request by comfyorange**
This pull request updates the TGS DMAPI to the latest version. Please note any breaking or unimplemented changes before merging.

### CODE REVIEW

**Comment by Mothblocks** [comment]
@optimumtact :(

**Comment by LemonInTheDark** [comment]
merges dmapi change on tg
doesn't merge update to dmapi in tgs
wtf why is the tgs bot updating our codebase 
:walter:

**Comment by Mothblocks** [comment]
i DIIIID

**Comment by Timberpoes** [comment]
> 
> 
> merges dmapi change on tg doesn't merge update to dmapi in tgs wtf why is the tgs bot updating our codebase :walter:

This part of the change can't be merged on TGS. `IsAdminAdvancedProcCall()` isn't a proc there.

**Comment by optimumtact** [comment]
@Cyberboss don't make me revoke the PAT

**Comment by LemonInTheDark** [comment]
> 
> 
> > merges dmapi change on tg doesn't merge update to dmapi in tgs wtf why is the tgs bot updating our codebase :walter:
> 
> This part of the change can't be merged on TGS. `IsAdminAdvancedProcCall()` isn't a proc there.

Can we just revert the security change

**Comment by optimumtact** [comment]
right that's it your pAT is going bye bye

**Comment by optimumtact** [comment]
@Cyberboss revoked the PAT (it needs to be refreshed anyway due to the new format), contact me when you're around again.

**Pull request closed without merging**
