### PR TITLE
(Draft) Turns janitor borgs into walking crew operated vacuum cleaners

### PR DESCRIPTION
**Pull request by StrangeWeirdKitten**
Needs a fair bit more work, but it's in an acceptable place to draft and gauge interest / review while I continue pushing changes. This is mostly for CI since it's faster for me to let github run CI then it is for me to run unit tests locally

## About The Pull Request

I've had a dream to make janitor borgs vacuum cleaners that the crew can use. This is just an added feature, not a replacement

This adds a vacuum cleaner item and functionality to janitor borgs with two modes: Suck and Wash. This allows janitor borgs to become more of a side-kick in the viscera cleanup detail. Clean the floors. Clean the walls. Vacuum up the bullets and trash into the cyborg's trash bag.

Every janitor borg will have a hose you can grab so that you may use them as proper, walking vacuum cleaners.

- [x] Mop Functionality (Does not apply wetness to the floor as this should be a fairly powerful mechanic)
- [x] Vacuum functionality
- [x] Hose locking to allow the cyborg to not allow their hose to be used.
- [x] The ability to offer a crewmember use of their hose
- [x] Extensive examine text to explain everything
- [ ] Sprites
- [x] Sounds
- [ ] Testing / Code documentation / Cleanup

I got a few sounds from soundsnap.com that I plan on cutting up and using.

https://github.com/tgstation/tgstation/assets/95130227/2f44054f-ed6e-49b5-9988-f1d5bf0ac2c7

## Why It's Good For The Game

Janitor borgs are AA cleaning machines, but it's pretty much the extent of what they can do. I feel like they can do with a little bit more of a co-op mechanic that is powerful, a very good cleaning option, and can clean up entire shootouts. If you manage to get a friend, this is an option that has zero water management.

## Changelog

:cl:
add: Janitor borgs have been made into mobile vacuum cleaners for the crew to use.
sound: Vacuum cleaner sounds from soundsnap.com
/:cl:

### CODE REVIEW

**Comment by StrangeWeirdKitten** [comment]
I'll be happy to take any code review or comments. This feature is like 33 percent done code wise and still needs its proper sounds and sprites.

**Comment by Jackal-boop** [comment]
Is this gonna be like the wall-e cleaner bot

**Comment by projectkepler-ru** [comment]
We joke about crew-served weapon. now what about crew-served janitorial weapon

**Comment by Sadboysuss** [comment]
what happens if there is no janitor but the borg wants to be janiborg? Also you may benefit from a design doc.

**Comment by StrangeWeirdKitten** [comment]
> what happens if there is no janitor but the borg wants to be janiborg? Also you may benefit from a design doc.

I don't need a design doc for one item I'll eventually explain with a video. I'm not reworking the entire janitor borg. I'm just adding a feature.

Also they can still clean normally with a mop or the cleaning mode action button, or offer the hose to anyone else with hands. It's an option, not a replacement

**Comment by san7890** [comment]
it would be appreciated if you could open up another fix pr while this pr is ongoing so i feel more comfortable with you being able to dig yourself out of the impending pit of gbp debt

**Comment by StrangeWeirdKitten** [comment]
> it would be appreciated if you could open up another fix pr while this pr is ongoing so i feel more comfortable with you being able to dig yourself out of the impending pit of gbp debt

I need to finish this PR first.

**Comment by moocowswag** [comment]
What happens if the janiborg dies like a janiborg and a janitor are cleaning the hallway during revs, does the janitor still get to use the vacuum after the borg has been flashed and beaten to death? Does the damage causing its modules to disable pull the vacuum out of the janitors hands?

**Comment by StrangeWeirdKitten** [comment]
> What happens if the janiborg dies like a janiborg and a janitor are cleaning the hallway during revs, does the janitor still get to use the vacuum after the borg has been flashed and beaten to death? Does the damage causing its modules to disable pull the vacuum out of the janitors hands?

If the borg dies, it'll disable the vacuum.

**Comment by moocowswag** [comment]
Also im begging you let us vacuum revenant and shades and visible ghosts

**Comment by StrangeWeirdKitten** [comment]
Will finish later

**Pull request closed without merging**
