### PR TITLE
pAIs cannot be converted to Ratvar

### PR DESCRIPTION
**Pull request by ChangelingRain**
Hey, look, a free servant that basically can't die!

### CODE REVIEW

**Comment by Armhulen** [comment]
Hahahahahahahaha How The Fuck Is Pai Cult Real Hahahaha Nigga Just Wipe The Card Like Nigga Cremate It Haha

**Comment by KorPhaeron** [comment]
Can you nar-sie summon with pAIs now that they can walk around?

**Comment by ChangelingRain** [comment]
I don't think you can convert pAIs to Narsie so no

**Comment by Supermichael777** [comment]
they cant drag anymore right?
Right?
fucking griffbots

**Pull request merged**
