### PR TITLE
Some action button fixes

### LINKED ISSUE #11005: Morphs lag the game.
Because morphs can swallow shit, putting it inside them, a morph can eat a fuck ton of items, causing /mob/living/handle regular hud updates to lag as it processes all thousand some objects for hud icons every tick.

### PR DESCRIPTION
**Pull request by AnturK**
Fixes implant/stuff inside you action buttons.
Turns action buttons off for morphs.
Fixes #11005

### CODE REVIEW

**Comment by RemieRichards** [comment]
Travis isn't your fault, pip is out of date rofl.

**Comment by RemieRichards** [comment]
@AnturK when morphs die to they poop out all the things they ate? if not you may as well just qdel() the things they eat.

**Comment by AnturK** [comment]
Yeah, the items pop out on death.

**Comment by MrStonedOne** [comment]
thats just a warning, it failed because the download failed. just re-run it.

**Pull request merged**
