### PR TITLE
Add a new and improved mapmerge

### LINKED ISSUE #29210: Mapmerge corrupts small maps with full dictionaries
Mapmerge doesn't trim smaller maps due to the extremely high value set to trigger trimming, resulting in their dictionaries getting overfilled and causing the map to corrupt when merging.

Suggested fix - update the python script to;

1. Check for unused keys
2. Always delete/replace unused keys
3. Check for new keys
4. Replace new keys with a random key from the available pool (to reduce probability of merge conflicts)
5. No longer bother sorting the dictionary alphabetically

### PR DESCRIPTION
**Pull request by SpaceManiac**
Key benefits of the new mapmerge include:
* multi-Z support,
* effective reuse of deleted keys,
* automatic handling of key overflow,
* and utilizing a git pre-commit hook to eliminate the need to run batch files manually.

Requires Python 3.6 (one year old so it should be fine). Batch files are provided to perform certain tasks, but the pre-commit hook is all that is needed most of the time. In my tests with TortoiseGit users, the scripts are successfully run in its bundled Git for Windows environment. Those who use Git for Windows or MSYS2 directly will have no trouble.

Install Python dependencies by running `tools/mapmerge2/requirements-install.bat`. Install the pre-commit hook by running `tools/hooks/install.bat`. The next commit will run the mapmerge automatically, or run `tools/hooks/python.sh -m precommit` manually to inspect the output before committing.

I'm working on putting this info in a nicer form into appropriately-placed README files. I'll also take care of updating the wiki if this gets merged.

Open to feedback, of course.

@ShizCalev 

Closes #29210.

### CODE REVIEW

**Comment by ShizCalev** [comment]
Assuming this will close #29210

**Comment by optimumtact** [comment]
the problem with a git commit hook is that now you're teaching people how to apply that.

good luck

**Comment by SpaceManiac** [comment]
If the commit hook turns out to really not work for most people, the old batch file method is still supported as a fallback, and the other benefits continue to apply.

**Comment by SpaceManiac** [comment]
[Wiki updated](https://tgstation13.org/wiki/Map_Merger). Will be lurking coderbus as usual if any problems come up and will continue to update the wiki page as needed.

**Comment by xxalpha** [comment]
>effective reuse of deleted keys,

This generates more conflicts more often.

**Comment by SpaceManiac** [comment]
@xxalpha In theory or in practice? I'd love to be linked to some examples.

**Pull request merged**
