### PR TITLE
Merge skew Compile Error fixes 

### PR DESCRIPTION
**Pull request by SyncIt21**
## About The Pull Request

Fixes a bunch of merge skews

## Changelog

:cl:
fix: merge skew helll
/:cl:

### CODE REVIEW

**Comment by Time-Green** [comment]
I got sniped by 10 seconds ARGHHH

**Comment by SyncIt21** [comment]
> I got sniped by 10 seconds ARGHHH

Gotta move fast :D

**Comment by SyncIt21** [comment]
Screenshot (99)

Where are these random failures coming from

**Comment by Time-Green** [comment]
Merge skew p2

**Comment by JohnFulpWillard** [comment]
it goes on and on and on
the ride never ends

**Comment by SyncIt21** [comment]
Anyone wants to fix all compile errors just commit to this branch. Don't create a separate PR for everything!

**Comment by Time-Green** [comment]
> Anyone wants to fix all compile errors just commit to this branch. Don't create a separate PR for everything!

no one was going to but now I kinda fucking wanna you gbp hog

**Comment by Time-Green** [comment]
I already have the fix just double checking it works

**Comment by SyncIt21** [comment]
> > Anyone wants to fix all compile errors just commit to this branch. Don't create a separate PR for everything!
> 
> no one was going to but now I kinda fucking wanna you gbp hog

Gotta move smart :DDDDD

**Comment by Time-Green** [comment]
im this close to shooting you into the sun

**Comment by Mothblocks** [comment]
you dont need to put any changelog if its not player facing its just confusing

**Pull request merged**
