### PR TITLE
THAT'S IT I'M DONE WITH YOU ALL

### PR DESCRIPTION
**Pull request by Wilchenx**
:cl: Delete
balance: Reduces the limit of changelings per round to maximum of two.
/:cl:

### CODE REVIEW

**Comment by PKPenguin321** [comment]
>optional name here

Delete

**Comment by Wilchenx** [comment]
@PKPenguin321 weird suggestion but okay

**Comment by DaedalusGame** [comment]
#35430 has already been closed once

**Comment by vuonojenmustaturska** [comment]
do we even have this mode in rotation

**Comment by praisenarsie** [comment]
changeling is not in the rotation but i bet ya it's in hippie's rotation

**Comment by Spaceinaba** [comment]
Isn't scaling turned on though? Shouldn't you modify the coefficient or something or am I confused? Cus if it is I don't thin anything will change from this pr (also you modified changeling and not traitorling so this pr does even more nothing)

**Comment by GuppyLaxx** [comment]
lmao nice try

**Comment by epochayur** [comment]
tag: "i ded"

**Comment by kevinz000** [comment]
Config issue.

**Comment by ExcessiveUseOfCobblestone** [comment]
kitty's first pr

**Comment by epochayur** [comment]
the salt radiating from this PR is immense

**Comment by Wilchenx** [comment]
yeah i goofed and edited wrong gamemode

**Pull request closed without merging**
