### PR TITLE
Blob chemical tweaks

### PR DESCRIPTION
**Pull request by ChangelingRain**
:cl: Joan
tweak: Sporing Pods produces spores when expanding slightly more often.
tweak: Replicating Foam now only expands when hit with burn damage, from all damage, but does so at a higher chance. Free expansion from it is, however, more rare.
tweak: Penetrating Spines does slightly more brute damage, and Poisonous Strands does its damage 50% faster.
/:cl:

Player-per-core scaling is now 1 per 25, from 1 per 20.

### CODE REVIEW

**Comment by KorPhaeron** [comment]
>produces spores slightly more often.

I actually failed to kill a sporing pods blob with a gatling gun because it just made so many fucking spores that my shots got blocked (and then I got xrayed to death by my teammates)

**Comment by Incomptinence** [comment]
@KorPhaeron 

You deserved it! Long live the blob! down with the gatling oppressor!

**Comment by Aloraydrel** [comment]
At least one chem can counter the meme gat

**Comment by KorPhaeron** [comment]
The point isn't that the gatling is fair, the point is that its gonna be pretty difficult for normal stuff to manage such a blob if even the gatling cant

**Comment by ChangelingRain** [comment]
korncerns addressed.

**Comment by Incomptinence** [comment]
@KorPhaeron 

You do realise traditional xrays don't care about the number of spores they can kill as many in a line as they touch?

Like maybe stop bringing your code baby crutch to every fight and think.

**Comment by KorPhaeron** [comment]
This isn't about gatlings though, this is about trying to use a bog standard laser in the same situation and just drowning in in spores instead (because unlike a gatling, you dont have a million follow up shots to clear the spore swarm afterwards).

**Comment by LatD** [comment]
The spore blob is one of the best blob types to counter guns because guns are just wasting shots and the spores are moving all the time. Good old welding tool will be really strong since the actual blob does so little damage.

**Comment by KorPhaeron** [comment]
Hard to welding tool any blob when it's crawling with blobbernauts though

**Comment by yackemflam** [comment]
Kor, the blobbernauts deal 8 damage
It takes a total of 13 hits to take down someone from 100% to crit without armor.
There's a reason people don't like sporing blob

**Comment by ChangelingRain** [comment]
When I said sporing pods' damage is all spores it *really is*

**Comment by AdamElTablawy** [comment]
yeah sporing blob is basically harmless without spores

**Comment by KorPhaeron** [comment]
I guess if everyone feels strongly about it you can go with your original plan then

**Pull request merged**
