### PR TITLE
Dullahan Fixes

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
Fixes https://github.com/tgstation/tgstation/issues/32175

Fixes https://github.com/tgstation/tgstation/issues/32231

Fixes https://github.com/tgstation/tgstation/issues/32317

Fixes https://github.com/tgstation/tgstation/issues/32205

By next Halloween these might actually work

Might be better to just remove them though

### CODE REVIEW

**Review by ShizCalev — APPROVED** [review]

**Comment by Qbopper** [comment]
>Might be better to just remove them though

delet this

**Comment by DoctoreMad** [comment]
This guy that wants the benefits of fun and unique mechanics without having to combat the bugs that arise form it will lose the former and get the latter.

**Comment by newfren** [comment]
Never remove these they are fun as heck.

**Comment by YakumoChen** [comment]
does this tackle the biggest bugs like the radio channel bug?

**Comment by duncathan** [comment]
Presumably it addresses the 4 issues mentioned in the post; perhaps you should read them to see

**Review by ninjanomnom — APPROVED** [review]

**Pull request merged**
