### PR TITLE
Remove cattleprod from suit storage slots

### PR DESCRIPTION
**Pull request by Mooshimi**
## About The Pull Request
-changes cattleprod weight class to huge
-Fixes: #38568

## Why It's Good For The Game
-fixes a long-standing oversight

## Changelog

:cl:
balance: cattleprods can no longer be held in suit storage slots
/:cl:

### CODE REVIEW

**Comment by Mooshimi** [comment]
@necromanceranne Thank you for the feedback on this

**Comment by TheBonded** [comment]
it doesn't make a whole lot of sense if you could put this on your back but not a suit storage slot, since most things that fit on your back also fit on suit storage slots (a notable exception being backpacks, for balance reasons). For example, the 3 main types of shotguns, eguns, and the pipegun.

**Comment by optimumtact** [comment]
most of those only fit in suit storage slots if an appropriate type of suit is there, it's long estabished that different suits support different sets of items and this change is entirely inline with that.

**Review by ExcessiveUseOfCobblestone — APPROVED** [review]

**Comment by ExcessiveUseOfCobblestone** [comment]
Stun Prods should eat the back slot or a hand slot, you should not find having one desirable outside necessity.

**Pull request merged**
