### PR TITLE
Fixes the issue of women on Charlie Station spawning with facial hair.

### LINKED ISSUE #47752: Oldstation Ghostrole has Follicular Inconsistency
You can't normally make a woman with a beard in regular gameplay, but female survivors coming out of the oldstation ghostrole pods can and do frequently have full beards and moustaches.

I'm guessing that this is an oversight and not a brave and stunning example of trans inclusionism.

### PR DESCRIPTION
**Pull request by Firecage**
## About The Pull Request
This PR simply fixes the issue where women on Charlie Station might spawn with facial hair as often as their male colleagues.

Fixes #47752 

## Why It's Good For The Game
Bearded women, while funny, might not be in their best interest.

## Changelog
:cl:
fix: Female employees on Charlie Station no longer wears facial hair.
/:cl:

### CODE REVIEW

**Comment by Timonkeyn** [comment]
That's transphobic

**Comment by MCterra10** [comment]
This was a FEATURE

**Comment by Timonkeyn** [comment]
Wow thanks for the 6 laughing emojis reddit

**Review by 81Denton — APPROVED** [review]

**Comment by AnonymousNow** [comment]
Jokes aside, though bearded women do exist in real life, there being none (usually) amongst the general station populace made this a consistency issue.
Hey, remember when someone suggested giving beards mechanical bonuses? Good times.

**Comment by 81Denton** [comment]
Tbh the feature we need is floor length hair getting caught in airlocks, vehicles and other machinery like power drills

**Pull request merged**
