### PR TITLE
Xeno nest wars Random Event

### PR DESCRIPTION
**Pull request by RemieRichards**
New event! Xeno nest wars, 2 opposing colours/strains of xenos are spawned with objectives to kill off the other's nest.

Only one of the two alien infestation events can ever happen naturally, The Current one or the Xeno nest war.

Possibilities:
Black vs. Red
Black vs. Yellow
Red vs Yellow
(These are the only canon colours so yeah)

When a queen lays an egg the egg take's the queen's colour, the facehugger take's the eggs, the embryo the hugger's the larva the embryo, etc. etc. to maintain the "strain"

Muh xeno fluff/canon:
Black xenos are xenos
Red xenos are from the books
Yellow xenos are from AvP Extinction

### CODE REVIEW

**Comment by Jalleo** [comment]
Images plz

**Comment by RemieRichards** [comment]
of what?
Black is your standard xeno sprites now
Yellow is yellow xenos
Red is red xenos

That's it.
I've varedited both colours before and they look fine.
(If @WJohn could find a way to greyscale xenos though they'd probably end up looking a lot nicer)

**Comment by Jalleo** [comment]
Thats why I want images just to see how much the sprites need to be retuned if its too ugly.

**Comment by WJohn** [comment]
I'm not exactly sure why the xenos would even want to fight eachother, they'll be more than busy enough fighting the crew, and by the time they actually DO fight eachother for who gets dibs on the hosts, the shuttle has been called and the round has ended.

**Comment by RemieRichards** [comment]
@WJohn they get objectives to kill the others.
so the only incentive is muh greentext but that seems to work for the rest of the game.

**Comment by Dorsisdwarf** [comment]
Closed why?

**Comment by FantasticFwoosh** [comment]
I think adding a caste of xenomorphs seperate to the black sentient xenomorphs that is just a red simple animal would be a sufficient lore amendment to such issues like facehuggers put on the map by coders as to invoke a chance of kickstarting black sentient xenos for free antag. Red xenomorphs going batshit charging at black xenos would also be funny flavour.

> Its not from a black sentient xenomorph so its not going to start a player xenomorph epidemic but is probably still going to kill the guy, and kickstart whatever the red xenomorph does.

As to say all red xenomorphs & bursting red aliens would be non-player controlled and keep the unique black xenomorphs as a deliberate feature rather than a over-used trope.

**Pull request closed without merging**
