### PR TITLE
Adds an admin punishment: Spewapalooza

### PR DESCRIPTION
**Pull request by ghost**
At first I was like, why can't I set how many organs the spew_organ proc spews? I want to spew more of them! And then I was like, why isn't this an admin punishment? A quick pr later and here we are: Spewapalooza, the admin punishment that makes you vomit out every single organ in your body. Brain, heart, eyes, ears, all of it. AWESOME.

### CODE REVIEW

**Comment by Arianya** [comment]
We need more non-lethal admin punishments

OOS for this PR I'm just sayin'

**Comment by davethwave** [comment]
Virtualization.(teleports the offending crew member to the VR place to spend the rest of their shift in the murderdome once that stuff gets set up as a "Virtual NPC") Cuban Pete(turns someone who has been using bombs to destroy the station to this name if he/she goes too far)

**Comment by davethwave** [comment]
Hunt(gives another antag the goal of killing said person, if there is no antags like a extended round without any ghost roles yet then create a chrono legionnaire with the goal of assassinating the person and leaving without any other casualties) Woody's revenge(turns the reader into a sentient book that can't move but is only able to whisper)

**Comment by davethwave** [comment]
almost instantaneous but unstoppable deaths happen if you are missing a liver, heart, and brain. I believe that you can survive without lungs as long as you use your medipen fast enough though. There are in total about 8 organs in total.(ears, tongue, eyes, liver, appendix, heart, brain, stomach. So you have about a 3/8 or a 4/8 chance for said person to die if it's random.

**Comment by Armhulen** [comment]
You can vomit your own brain so

**Comment by Armhulen** [comment]
@davethewave this version does every organ

**Comment by Armhulen** [comment]
@kevinz000 ?

**Comment by Armhulen** [comment]
@ExcessiveUseOfCobblestone OK OK WOAH

**Pull request closed without merging**
