### PR TITLE
Delete ISSUE_TEMPLATE.md

### PR DESCRIPTION
**Pull request by MrsTonedOne**
this is fucking lame.

The details get split up, and it makes it harder to really see what they are reporting, case in point: #15977

I had to re-read that 5 times to understand what they were talking about.

Its the same for most of the issues.

### CODE REVIEW

**Comment by optimumtact** [comment]
:-1: you'll get used to it

**Comment by MrStonedOne** [comment]
https://github.com/tgstation/-tg-station/issues/15978

most of the fields were redundant and stupid.

**Comment by Incoming5643** [comment]
:+1: Complacency is for the complacent

**Comment by MrStonedOne** [comment]
https://github.com/tgstation/-tg-station/issues/15971

again, "why is this bad" is useless, spliting up the reproduction and issue details seems odd and it would have been better to list both inline with eachother "when doing blah with blah and blah, blah happens"

**Comment by MrStonedOne** [comment]
https://github.com/tgstation/-tg-station/issues/15970

Redundant redundancies.

**Comment by optimumtact** [comment]
So then update the issue template

**Comment by MrStonedOne** [comment]
https://github.com/tgstation/-tg-station/issues/15922

And here we see the wild goofball, shitposting, enabled by a shitty issue template.

**Comment by phil235** [comment]
Just because "what is the problem" and "why is that a problem" can sometimes be redundant for some issues doesn't mean it's not useful. The what is for the person to describe the circumstances, the why is for the person to explain their rationale. The second question is here so maintainer can see what assumptions the person is making about the issue.

**Comment by MrStonedOne** [comment]
>you'll get used to it

I've been waiting for me to get used to it for 2 weeks now.

I haven't, in fact it's only gotten worse, as now all i can focus on is how bad this issue template is, as is the entire idea.

Issue templates rarely help, there is a reason I ignore it on byond as well.

**Comment by xxalpha** [comment]
My only problem is that the template questions make it harder to focus on the information I want to read.

**Comment by phil235** [comment]
@MrStonedOne Are you suggesting we go back to freeform issues ? Personally I'd rather waste 5 seconds to read a couple of redundant lines on an issues than waste 10 minutes trying to figure out what the OP is trying to get to by searching the code.

**Comment by phil235** [comment]
>#15922
And here we see the wild goofball, shitposting, enabled by a shitty issue template.

You think goof's issue would be more comprehensible without the template?
Don't blame the template when it's the OP who can't be assed to fill the template properly.

**Comment by PKPenguin321** [comment]
Just put a line that says "Please note that following this template is optional if you can describe the issue well enough without it, but it can be helpful to give your report clarity." or something to that effect

**Comment by Zilenan91** [comment]
Yeah I just delete the template whenever I make an issue. It's completely redundant and muddles the message in walls of text.

**Comment by Shadowlight213** [comment]
Same. I just delete it. Never saw a use for it really.

**Comment by Iamgoofball** [comment]
That issue made by me was going to be shitpost regardless of the template or not. You're pulling shit out of your ass at this point.

You know better than this, come on.

**Pull request closed without merging**
