### PR TITLE
Fixes Midi2Piano Tool

### PR DESCRIPTION
**Pull request by HourlyLimit**
## About The Pull Request

I put back pclip turns out the other way I was using copy to clipboard did not work well, Made the program run once and it will always be on top so you do not lose the window, and it will tell you when it's copied the sheet music to your clipboard.

## Why It's Good For The Game

Fixes The Midi2Piano Tool also now you can't lose it under other windows.

### CODE REVIEW

**Review by san7890 — CHANGES_REQUESTED** [review]
We shouldn't be bundling/distributing the actual pyperclip code in this repository, users should be `pip install`ing that as a module. If you want to, you can include a bat script that will set up the virtual environment and handle installing pyperclip in the `tools/midi2piano`

**Comment by PeriodicChaos** [comment]
> We shouldn't be bundling/distributing the actual pyperclip code in this repository, users should be `pip install`ing that as a module. If you want to, you can include a bat script that will set up the virtual environment and handle installing pyperclip in the `tools/midi2piano`

**Comment by PeriodicChaos** [comment]
> We shouldn't be bundling/distributing the actual pyperclip code in this repository, users should be `pip install`ing that as a module. If you want to, you can include a bat script that will set up the virtual environment and handle installing pyperclip in the `tools/midi2piano`

Misclicked when trying to comment oops, also thanks for the idea I have gone ahead and done that now. Thanks for the fast response.

**Review by HourlyLimit — COMMENTED** [review]
Done so. 👍

**Pull request merged**
