### PR TITLE
More vines for the god of vines

### PR DESCRIPTION
**Pull request by Razharas**
- Added bluespace vines that are able to grow through walls, glass and
  anything and everything
- Added space-protective vines that change the space into "vineturfs"
  which are basically resprited floors
- Made vines be able to spread into space
- Changed some vinecontroller vars, now you can adjust the speed of
  spreading both by capping the max vines per tick and new-vines to
  existing-vines spread ratio
- Made the chance to mutate per spread be dependant on the potency of the
  seed
- Made the spreading speed be dependant on productivity of the seed(can be
  both slower and faster then current one)
- Fixed some potential runtimes with calling destroy() instead of qdel()
  where needed
- Removed the colon added by carn, its all checked in Enter call few lines
  later anyway
- Added special proc to all seeds that give plant anazyler special
  information if needed in form of list of strings that will be displayed
  to user one by one
- Added special proc to seeds that make them have some special chem
  interactions on growth if needed
- Made vine mutations have quality of either good, bad or neutral
- Made some chems remove the mutations of certain quality from growing
  seeds
- Made some chems tweak potency and production of the growing vine seeds
  both ways so you can make unmutatable slowly growing vines if needed
- Vine seeds now show mutations on the plant analyzing
- Cut some copypaste in analyzer proc
- I like vines
- I also like oranges, he is the only reason this pr happened, the master of the git, the unfucker of the fucked, the seer in the land of git-blind

### CODE REVIEW

**Comment by AlexCrimson** [comment]
Spread into space? Well that sure sounds like fun.

**Comment by Deantwo** [comment]
Vines don't need oxygen and room temperature?

**Comment by WJohn** [comment]
without oxygen vine dont evoluate?

**Comment by Razharas** [comment]
They dont need shit

**Comment by Lumipharon** [comment]
Jesus fuck pleas no, vines are awful enough as it is, without vines growing through walls and literally filling the z-levels. Atleast make them admin only. Also when chucklefucks make 100 potency/high productivity seeds (and they will) It will be pretty gay without 50 goats.

**Comment by Razharas** [comment]
They are admin onlyalready, apart from the whatevercolouritis slime core that spawns lots of op shit like gatfruit anyway

**Comment by AlexCrimson** [comment]
Err... that slime core just spawns stuff you can eat. Why would it spawn space vines? You cannot eat Kudzu pods, can you?

So the Bluespace Vines are a completely new type that come from a completely new seed, not a mutation of normal vines?

**Comment by Razharas** [comment]
Kudzu pods are fruit like any other, so its spawnable by that slime core
But then again its more of a slime core problem

**Comment by AlexCrimson** [comment]
So its not really adminspawn/slime core only. You can grow space vines in Botany easily enough. Am i misunderstanding something?

**Comment by Razharas** [comment]
How can you get spacevines in botany not from admins or slimecore?

**Comment by palpatine213** [comment]
Please no. Vines already can fuck up badger, and we really don't need ones that can go through walls. :-1:

**Comment by AlexCrimson** [comment]
Unless something has changed that i am not aware of, you can get space vines by injecting trays with a high weed level. That will spawn Kudzu in the tray and allow you to produce pods, which are then turned into seeds and can be used in-hand to spawn a tile of space vines.

**Comment by Razharas** [comment]
>you can get space vines by injecting trays with a high weed level

What

**Comment by AlexCrimson** [comment]
Uh i suck at explaining game mechanics. You know how Hydroponic Trays have a weed and pest level? Once it is over 5/10, you can inject stuff into the tray to spawn bad things. For pests it will spawn spiderlings, for weeds it will spawn one of many different "weeds" or "mushrooms". You can get stuff like Deathnettles, Destroying Angels, Fly Amanita etc. One of the random spawns is Kudzu aka Space Vines.

Its in the code somewhere, but i couldnt find it even if i wanted to.

**Comment by Iamgoofball** [comment]
@Razharas you should totally make chem blob versions of all vines when you add new vines

**Comment by Lumipharon** [comment]
Raz, stahp. You realise how easy it is to make space vines?
The ONLY thing you need is SUGAR.
Apply sugar to empty botany tray/dirt patch.
Keep applying.
Get kudzu.

**Comment by AlexCrimson** [comment]
I know sugar increases the weed/pest level, but im pretty sure you need to inject at least 5units of mutagen to "spawn" things. Could be wrong.

**Comment by Lumipharon** [comment]
Hm looking at the code you're right, but the person I was making the example about never had access to chem, maybe he was getting radium or uranium from somewhere, which also works.

**Comment by Razharas** [comment]
Man i never knew that mutating trays with high levels of shit spawns spiders and kudzu and stuff
I was under impression it was unobtainable under normal conditions, guess with so much content as we have its hard to track it all

@Iamgoofball 
Vines and blobs operate entirely different, blobs use one chem, vines use multiple mutations which are not under the chem controlling system, blobs apply chems only on expand, vines have multiple effects on all kinds of situations like growth, death, fire act, eat, chem applying and so on, not to say all chems for blobs are intentionally harmful, while vines actually have good mutations like transparency, toxins and co2 filtering, light emitting and now space covering, so blending these systems is kinda hard

Factually there are a few ways, can remove kudzu from randomspawning upon weeds, can nerf bad effects and buff good effects both of mutations and seedspawning, can add some kind of mutation controll system so you can cultivate good kudzu and/or bad kudzu if needed(my dream actually, but damn that shit is hard), in worst case can remove some especially bad mutations(that will suck all the fun out of vinefighting though, muh chainexplosions)

**Comment by RemieRichards** [comment]
@Razharas while you can talk about vines being different to blobs now they both came from the same route, Biomass. it's even stated in the vine files that they're straight copy pastes of the biomass.

**Comment by AlexCrimson** [comment]
I dont see an issue with just leaving things as is. No need to remove the FUN from tator Botanists just because a few of the vine mutations are really strong. Its already a very uncommon situation for a Botanist to grow a strong strain of Kudzu. Just wanted to make it clear that its very possible to get the stuff as a normal player.

**Comment by TZK13** [comment]
Please don't remove the ability for botanists to grow kudzu to accommodate this, that would be terrible.

**Comment by Razharas** [comment]
Before you couldnt grow potent or impotent kudzu because it was unaffected by the seed vars, it was always the same usual kudzu no matter how potent or productive it was

@RemieRichards 
I talk about coding difficulties exclusively, gameplay-wise its ok, but mutations are very different to chems and thus will need a lot of changes to adjust them to blob gameplay

**Comment by Lumipharon** [comment]
Kudzu is pretty fun because it can just make the station unplayable - if not outright utterly lethal, while requiring almost zero effort - you just make a bag of seeds then plant them everywhere.

It's especially bad with certain strains, and with a smaller/goatless crew.

Don't even get me started on the old gib vines, oh lawd they shit was 10/10.

**Comment by TZK13** [comment]
It's unfair to say that it requires zero effort especially considering how you pretty much confirmed that you've never tried it, the RNG of mutating plants is as present as ever with kudzu as it's only one of a variety of possible mutations when you use unstable mutagen on a tray with weeds in it.

**Comment by Steelpoint** [comment]
I like vines, I like these changes.

:+1:

**Comment by Lumipharon** [comment]
While I haven't made vines (because I find it griefy as shit and unfun for literally everyone else) I have done plenty of botany, it is very easy to get things done with a dropper and some chems.

A single 30u bottle of mutagen is enough to get multiple plants to 100 potency, and each application of (5) mutagen is a straight 10% chance for kudzu to start with.

**Comment by TZK13** [comment]
It still requires more effort and is far, far more interesting than the standard traitor fare.

Saying "he" makes me thing otherwise but are you referring to Saiga when you mention somebody growing kudzu all the time? I've literally never seen anybody else but them and me mutate kudzu before because it's such an unknown feature.

**Comment by Lumipharon** [comment]
Saiga did that for a while, and it was awful. Other people have done it though, the most notable in recent times being rob, where he did it EVERY SINGLE ROUND for literally a week.

It's not really interesting in that it can very easily swamp the entire station, fucking over the entire crew, with extremely minimal effort by the person initially.

One time an admin spawned us literally dozens of goats an we still couldnt clear all the vines.

**Comment by Bram961** [comment]
If this ever becomes a thing, we better get bluespace goats.

**Comment by Jordie0608** [comment]
Changelog

**Comment by phil235** [comment]
Travis failed.

**Comment by phil235** [comment]
I played around with it locally and got this runtime:
runtime error: undefined proc or verb /turf/space/break tile to plating().

proc name: ex act (/turf/simulated/floor/ex_act)
  source file: floor.dm,66
  usr: Kyra Gray (/mob/living/carbon/human)
  src: space (136,139,1) (/turf/space)
  call stack:
space (136,139,1) (/turf/space): ex act(2, null)
explosion(the floor (137,139,1) (/turf/simulated/floor/plasteel), 1, 2, 4, null, 1, 0, 2)

**Comment by Razharas** [comment]
Fixed

**Pull request merged**
