### PR TITLE
Minor Away Mission Fixes

### PR DESCRIPTION
**Pull request by ishitbyabullet**
## About The Pull Request
Fixes a few minor issues in the pre-existing away missions as well as removing some bloat from one of them. I also asked for permission to do this.

**Edit: Yeah, I got an answer by a headmin that it just isn't in the config according to him. That goes beyond what I can do so my work here is done.**
## Why It's Good For The Game
**Wild West:**
- Projectile guns aren't real guns. This also isn't a creepypasta so it makes no sense for blood to be inside the walls.

**Snow Cabin:**
- A few item descriptions have been changed for various reasons. I deleted this one completely impossible-to-reach room since it had no use as well as having a minor issue where one of the items moved on it's own will which was annoying. I also deleted a room that, in hindsight, required metagaming to reach. Not good design.

**Moon Outpost 19:**
- It's always weird when you reach the edge of the map and find a bunch of riveted walls....

**Underground Outpost 45:**
- Error tiles are annoying.  

**Cloning:**
- There's a still existing object that requires a previously removed sprite.

## Changelog
:cl: Bald People
add: Various away missions now have minor fixes. 
add: The horrific experiment structure has it's icon_state restored
Tweak: SnowCabin has been changed a bit. No more empty void of despair!
/:cl:

### CODE REVIEW

**Comment by ATH1909** [comment]
> Snow Cabin:
> 
> There was an intended thing meant for admins to delete some indestructible walls/players to find a way around in order to explore additional content for fun. In hindsight, this was basically bloat so I removed the stuff that literally requires an admin/clever usage of game mechanics to reach.

Nah, keep it, it's a fun easter egg and is pretty much the most interesting thing about the snow cabin away mission. You can get it pretty easily with a phazon, IIRC.

**Comment by ishitbyabullet** [comment]
> 
> 
> > Snow Cabin:
> > There was an intended thing meant for admins to delete some indestructible walls/players to find a way around in order to explore additional content for fun. In hindsight, this was basically bloat so I removed the stuff that literally requires an admin/clever usage of game mechanics to reach.
> 
> Nah, keep it, the fun police stuff is a funny easter egg and is pretty much the most interesting thing about the snow cabin away mission. You can get in pretty easily with a phazon, IIRC.
> 
> Instead of deleting the content behind the indestructible walls, why not just replace the invincible door-like walls with actual (centcom-grade) bolted doors?

Centcom-grade bolted doors wouldn't even be strong enough in my eyes. I also know that a phazon could easily do it. I just don't feel like it makes sense anymore.

**Comment by ATH1909** [comment]
> > > Snow Cabin:
> > > There was an intended thing meant for admins to delete some indestructible walls/players to find a way around in order to explore additional content for fun. In hindsight, this was basically bloat so I removed the stuff that literally requires an admin/clever usage of game mechanics to reach.
> > 
> > 
> > Nah, keep it, the fun police stuff is a funny easter egg and is pretty much the most interesting thing about the snow cabin away mission. You can get in pretty easily with a phazon, IIRC.
> > Instead of deleting the content behind the indestructible walls, why not just replace the invincible door-like walls with actual (centcom-grade) bolted doors?
> 
> Centcom-grade bolted doors wouldn't even be strong enough in my eyes. I also know that a phazon could easily do it. I just don't feel like it makes sense anymore.

Add something a bit stronger then, just not unbreakable.

The fun police content is hilarious, and it'd be saddening to see it go.

**Comment by ishitbyabullet** [comment]
> 
> 
> Add something a bit stronger then, just not unbreakable.
> 
> The fun police content is hilarious, and it'd be saddening to see it go.

The only thing as strong as something indestructible is something else that is indestructible. This means It should technically REQUIRE an admin to access it. Therefore, it is content bloat which makes it unnecessary. Also, besides you, I don't know if anyone has ever even SEEN it so this wouldn't be much of a tragedy.

However if it's decided that this is too much to include in a PR currently then I'll begrudgingly leave it in for now. Until then, it has no place being there because it just seems way too out of place and lolrandom.

**Comment by ATH1909** [comment]
> > Add something a bit stronger then, just not unbreakable.
> > The fun police content is hilarious, and it'd be saddening to see it go.
> 
> The only thing as strong as something indestructible is something else that is indestructible. This means It should technically REQUIRE an admin to access it. Therefore, it is content bloat which makes it unnecessary. Also, besides you, I don't know if anyone has ever even SEEN it so this wouldn't be much of a tragedy.
> 
> However if it's decided that this is too much to include in a PR currently then I'll begrudgingly leave it in for now. Until then, it has no place being there because it just seems way too out of place and lolrandom.

Thanks.

Also, don't forget to update the changelog.

**Comment by ishitbyabullet** [comment]
> Also, don't forget to update the changelog.

I wasn't going to remove it yet however I can just sense this getting the PR canceled anyways so fine. I'll just change what I think are the dumbest parts of it in general. _Still trying to figure out if these actually appear though._

**Review by Twaticus — APPROVED** [review]

**Pull request merged**
