### PR TITLE
Adds icons for lizard and corn bread slices in the mouth (head)

### LINKED ISSUE #67431: Rootbread slices have no worn icon
Reporting client version: 514.1583

## Round ID:
[184074](https://scrubby.melonmesa.com/round/184074)

## Testmerges:
- [Disables soft lock on traitor objectives](https://www.github.com/tgstation/tgstation/pull/67385)
- [Adminwho now caches feedback links until admins are reloaded (and also works again)](https://www.github.com/tgstation/tgstation/pull/67307)

## Reproduction:
image

### PR DESCRIPTION
**Pull request by Iatots**
## About The Pull Request
Adds icons for holding lizard and corn bread slices in your mouth (head).
Also lowers the side icon for all other bread slices by 1 px to make it match the front sprite, as a bonus it no longer looks like a bread beard.

## Why It's Good For The Game
fixes #67431 

## Changelog

:cl:
imageadd: added icons for lizard and corn bread slices in mouth (head)
/:cl:

### CODE REVIEW

**Comment by Iatots** [comment]
sorry for the delay setting up a new rig
breads

**Comment by TheSilverNuke** [comment]
This is just like one of those Japanese anime...

**Comment by ShizCalev** [comment]
conflict.

**Comment by optimumtact** [comment]
I prefer your other one.

**Pull request closed without merging**
