### PR TITLE
[s] Holocarp are purchasable for 9 TC

### PR DESCRIPTION
**Pull request by coiax**
Purchase holocarp (random typed guardians that are holographic fish) for
9 TC on April Fools Day! Because I made them for April Fools last year,
but didn't finish them last time.

### CODE REVIEW

**Comment by KorPhaeron** [comment]
PRs dont need to be open to be testmerged

**Comment by Cyberboss** [comment]
@KorPhaeron You should probably be tagging these so we can gather them all when it's time

**Comment by Iamgoofball** [comment]
@KorPhaeron 
But they also won't update, so if we need to push a bugfix and re-testmerge it it wont get picked up unless the PR is open

**Comment by KorPhaeron** [comment]
@Cyberboss 

As far as I know headmins are only merging a few anyway so unless you bug and ask them specifically about your PR having it open or not won't do much good

**Comment by PKPenguin321** [comment]
We never really had a consensus
I'd still like to see an April fools branch

**Pull request closed without merging**
