### PR TITLE
Singularity resprite by UDaV73rus

### PR DESCRIPTION
**Pull request by Iamgoofball**
## About The Pull Request

https://file.house/VmHn.mp4

## Why It's Good For The Game

Pretty sprites go brrr
## Changelog
:cl: UDaV73rus
imageadd: Resprited the Singularity
/:cl:

### CODE REVIEW

**Comment by Ghilker** [comment]
nice

**Comment by TheSilverNuke** [comment]
I like it, but would it be possible to get rid of the random clouds of black between the dust being sucked in?

**Comment by ArcaneMusic** [comment]
It's almost photorealistic, which, yeah looks nice, but I feel like this loops around into "too realistic for our art style."

**Comment by SuperNovaa41** [comment]
No soul

**Comment by SuperNovaa41** [comment]
> It's almost photorealistic, which, yeah looks nice, but I feel like this loops around into "too realistic for our art style."

Also yeah I agree with this, it looks cool but does not match the style of anything else we have really

**Comment by 81Denton** [comment]
This doesn't fit our current art style and honestly looks like a hot mess of random colored gas particles and sparks.

**Comment by Iamgoofball** [comment]
I think it looks very pretty.

**Comment by Iamgoofball** [comment]
>I like it, but would it be possible to get rid of the random clouds of black between the dust being sucked in?
Spriter says no. I'm not compromising their artistic vision.

**Comment by MrDoomBringer** [comment]
What? This is literally just a downscaled GIF. Object sprites like this have no place in our codebase.

**Comment by Fikou** [comment]
we finally got the sequel to the 5mb of russian anthem
image

**Comment by Mothblocks** [comment]
yeah can we not add 18 mb of sprites

**Comment by iwishforducks** [comment]
glad to see we're catching up to the realistic minecraft HD texture packs

image

**Comment by maxymax13** [comment]
normally when you resprite something it's supposed to look better and visually clearer, this looks like a black and red chicken nugget

**Comment by arnociiroc** [comment]
stage two do be lookin like a cheese puff

**Comment by tommysalami3** [comment]
The original singularity sprite is so incredibly iconic and consistent that changing it is basically impossible. Even if this sprite was objectively better or jaw-droppingly gorgeous it wouldn't be merged. It ticks all the boxes for shit that makes it impossible to resprite.
- Sprites been around for years
- Current sprite is good
- Has multiple sprites that are dependent on referencing this one ( Singularity hammer, orbit animation, singulo toy, singulo clown car )
- Completely ingrained in the community.
It was kind of a lost cause the moment you started man.

**Comment by maxymax13** [comment]
>     * Sprites been around for years
> 
>     * Current sprite is good
> 
>     * Has multiple sprites that are dependent on referencing this one ( Singularity hammer, orbit animation, singulo toy, singulo clown car )
> 
>     * Completely ingrained in the community.

this same argument could be applied to literally everything that got resprited to 3/4 in 2017, this sprite sucks but that is an awful argument

**Comment by tommysalami3** [comment]
> > ```
> > * Sprites been around for years
> > 
> > * Current sprite is good
> > 
> > * Has multiple sprites that are dependent on referencing this one ( Singularity hammer, orbit animation, singulo toy, singulo clown car )
> > 
> > * Completely ingrained in the community.
> > ```
> 
> this same argument could be applied to literally everything that got resprited to 3/4 in 2017, this sprite sucks but that is an awful argument

Yeah but those sprites got changed to something thats good and doesn't add 3000% file space.

**Comment by Jhyrachy** [comment]
I really like the style exactly because it doesn't fit the current style.  
A singularity is something alien, a tear in space and time that destroy everything it touch.

But maybe making it 18mb is a bit excessive

**Comment by Mothblocks** [comment]
you cant say that no sprite isn't replaceable because we killed the toolbox sprite

**Comment by Mothblocks** [comment]
that being said i'm not adding 18 more mb to the rsc for something that is seen once every...maybe 50 rounds (and doesn't look better)

**Comment by MrDoomBringer** [comment]
> Yeah but those sprites got changed to something thats good and doesn't add 3000% file space.

cringe argument
anyways
goof what were you thinking

**Comment by Ketrai** [comment]
@Iamgoofball Who made this anyways? And how? Original art/software used? Is it a gif from somewhere else or?

**Comment by Ketrai** [comment]
https://cdn.discordapp.com/attachments/694611413582348288/744046619313569842/unknown.png Or this one which I believe is from NSV13

**Pull request closed without merging**
