### PR TITLE
Buff the captain's hat's stats

### PR DESCRIPTION
**Pull request by ghost**
# Improves the stats of the captain's hat.

## About The Pull Request

This pull request will change the base stats of the captain's parade hat and captain's hat so that they match those of similar gear like the HOS' hat.
- Melee resistance: 25 -> 40
- Bullet resistance: 15 -> 30
- Wound resistance: 5 -> 10

## Why It's Good For The Game

The captain's gear has usually been on par or superior to that of the HOS and the rest of security, so it only makes sense that their headgear is of at least similar stats. Currently even the security beret has higher stats (double the bullet resistance and 5 extra melee resistance). The low melee resistance of the captain's hats is an especially prominent problem because it drops the captain's headgear's melee protection to level 3, which means that they can get bottle-smashed and stunlocked (not very good considering that in a nukie round the captain could just get stunlocked and killed with a mere bottle-smash spam, leading to the station's annihilation).

:cl:
balance: made the captain's hat armor on par with the sec helmet
/:cl:

### CODE REVIEW

**Comment by Goriusrok** [comment]
ided pr skill issue kid

**Comment by optimumtact** [comment]
No thanks

**Comment by Jackal-boop** [comment]
I wonder when optimum last played captain

**Comment by optimumtact** [comment]
i've never played captain because i'm a sigma male

**Pull request closed without merging**
