### PR TITLE
Renames stun effects and changes stun input values as preliminary work for changing stuns to status effects

### PR DESCRIPTION
**Pull request by ChangelingRain**
`Weaken` is now `Knockdown`, since it knocks you down.
`Paralyse` is now `Unconscious`, since it knocks you unconscious.
All values for these, plus `Stun` and `Sleeping`, are now 10 times larger, ie; in decisecond times instead of tick times. This has no effect just yet.

- [x] I need to make the stun times 20 times larger, not 10 times, since each life tick is ~2 seconds/20 deciseconds on average

### CODE REVIEW

**Comment by nicbn** [comment]
Nice

**Comment by Fox-McCloud** [comment]
I disagree with naming stun as such; most games in today's era all demonstrate a stun as being something where you're standing up and dazed.

Weaken also fits its name nicely, IMO, and doesn't really need to be changed either.

Paralyze though? Yeah, that one doesn't fit its name-sake very well.

Changing the functionality of paralyze, entirely is going to create massive amounts of confusion for a lot of coders, downstreams, and other repositories that port from you guys.

So if you're going to rename stun and not stick with the original naming, I recommend something completely and entirely unrelated to the original terms.

**Comment by XDTM** [comment]
Gotta agree on stun, thinking about it, but weaken sounds like an effect that would reduce damage output or is related to stamina damage, not a stun + drop.

**Comment by ChangelingRain** [comment]
Well I do need to split paralyse into "can't move, but can still hold items and act" and "can't move, can't hold items, can't act" so turning it from paralyse to `Root` and `Stun` would probably be a good idea

**Comment by XDTM** [comment]
i agree on the terms, they're the stardard in gaming and recognizable

**Comment by KorPhaeron** [comment]
@tgstation/commit-access

**Comment by ShadowDeath6** [comment]
I think stun should remain the same, :+1: on knockdown and unconscious though

**Comment by lzimann** [comment]
the old names were bad and confusing, the new ones are good

**Review by lzimann — APPROVED** [review]
Went over everything and looks all good.

**Comment by kevinz000** [comment]
possibly make the "can't hold items, can't act", "knocked on the floor", "unconscious", and "can't move" different? that way items can apply it custom instead of having to choose.

**Comment by ChangelingRain** [comment]
that would be more ideal but unconscious kind of includes "can't hold items, move, act" already and I don't think splitting 'knocked on the floor' out of that would be good

The rest, though, would be way better as their own effects so you can do more interesting things.

**Pull request merged**
