### PR TITLE
Beds and Benches: The Aesthetic Revolution [re-PR'd With EOB's Blessing]

### PR DESCRIPTION
**Pull request by Zytolg**
## About The Pull Request

Ever since I saw @EOBGames PR this, I've wanted it. I've needed it. I've been delaying some mapwork FOR this. This is an identical PR to #61689, just updated so that it's not conflicting with anything. I've done everything @Krysonism asked for from last time too. That's right spacemen, double beds are back, and more cursed then ever. Cursed to succeed that is!

## Why It's Good For The Game

We. Don't. Have. Benches. 
Benches are a hallmark of any public space! You can sit on them, sleep on them, stand on them, even sleep on them! Our stations have a ton of chairs, but chairs don't really communicate public that well. Benches do. As for the beds? Well Inept wants them, and you know what? I respect that. 

LOOK AT IT!

Revolution Beds and Benches

And Like I said, this PR has been blessed by our glorious maptainer himself.

MaptainerAPPROVALPUNS

🦖  TO THE CHANGELOG MY DUDES!

EDIT: Ports the Benches and Double Bed Sprites from Skyrat

## Changelog

:cl:
expansion: Sofas now include the Bench Type. These are buildable with 2 metal plates from the crafting menu.
expansion: Beds can now be rotated (flipped), and include the Double Bed Type. Miners can also make Double Pod Beds to really feel like an Alaskan King. 
expansion: Bedsheets to match! Try to share those big blankets with a lizard if you see that they're shivering!
code: Stuff that lets you interact with the benches and beds in-game, so that you too can enjoy being a king. 
sprites: Ports the Benches and Double Bed sprites from Skyrat
sprites: Flipped Beds
/:cl:

### CODE REVIEW

**Comment by EOBGames** [comment]
Just confirming I gave permission for this, now I'm going back to the beach- my mai tai's getting warm. See you all in November!

**Comment by Time-Green** [comment]
Looks really good! But uh, why do the upper door rooms have windows now? Unless you're into exhibitionism, it's better we don't see what happens there

**Comment by GoldenAlpharex** [comment]
Two questions, what's `abed` there for, and how do we rotate the bedsheets?

Also, you forgot to add all the directional sprites for the double cosmos bedsheet.

**Comment by cacogen** [comment]
Maybe the benches should be built out of titanium given how futuristic they look

**Comment by cacogen** [comment]
They don't look like they're made out of iron, they don't look like the other metal furniture we have, they look more like what the station's shuttles are made out of and they look like something from a sci fi utopia.

**Pull request merged**
