### PR TITLE
adds some cameras to runtimestation

### PR DESCRIPTION
**Pull request by ghost**
Though #34505 already fixed an issue caused by this lack of cameras, it also occurred to me that it might be handy to have them for other testing purposes (like me messing with ratvarian camera observers earlier today) so I figured I'd include them

### CODE REVIEW

**Review by ShizCalev — DISMISSED** [review]

**Comment by Cyberboss** [comment]
Hijacking for a test

**Comment by Xhuis** [comment]
🤔

**Comment by Cyberboss** [comment]
Conflicts

**Comment by Buggy123** [comment]
image
Uhh...

**Comment by Cyberboss** [comment]
test bot please ignore

**Pull request merged**
