### PR TITLE
Pipe code cleanup

### LINKED ISSUE #11398: Horizontal HE pipes can't be installed on top of vertical regular pipes
bugreport

If you lay a horizontal HE across a vertical pipe (top of picture), or vice versa, it states there is already a pipe at that location. However, the opposite (bottom of picture) can still be installed.

### PR DESCRIPTION
**Pull request by duncathan**
#11218 must be merged before this PR.

This PR essentially finished up the work I began with #10560 in making atmos more OOP.
Changes:
- The #defines in component_base.dm have been moved to __defines/atmospherics.dm. They have also been modified slightly, with a couple new ones as well:
  - The `NODE1` etc. defines now define the full ~~`nodes["n1"]`~~ `nodes[1]`; now instead of `nodes[NODE1]` you simply need `NODE1`
  - The `NODE_I` etc. defines have been added, which are used in place of ~~`nodes["n[I]"]`~~ `nodes[I]`
  - The `DEVICE_TYPE_LOOP` define has been added; which is used in place of the multiple repeated `var/I = 1; I <= device_type; I++`
- The `nodes` list and `device_type` var have been moved to the `obj/machinery/atmospherics` level.
- Most pipe procs have been made OOP, and some which were shared with components have been moved to the `obj/machinery/atmospherics` level.
- The new proc `can_be_node` was added to aid in making `atmosinit` more OOP.
- Heat exchange pipes are no longer children of simple pipes. This was done to increase modularity; now one could, with relative ease, code heat exchange manifolds and 4-way manifolds.
- `parents`, `airs`, and `nodes` are now numbered lists, not associative.
- The new proc `nullifyNode` was added to aid in making `Destroy` more OOP.
- `QDEL_HINT_FINDREFERENCE` was given a minor change to prevent an edge case in which objects referenced by objects for which one was finding references would fail to GC properly, despite otherwise working fine.
- The debug verb "Display del() log" now also shows a list of paths which are not returning a qdel hint.
- The `testing()` message for when an object doesn't return a qdel hint will now only appear once per path.

Fixes #11398.

### CODE REVIEW

**Comment by MrStonedOne** [comment]
I'd actually like to see you remove the associated list in favor of numbered lists.

All you'd have to do is initialize the list properly by doing nodes.len = number in new(). you could even do that in component_base's new() using that one var that says how many sides something has

**Comment by duncathan** [comment]
I'll see what I can do about the lists. It should be pretty easy to do now. 
As for commit titles, I'll keep that in mind in the future. Note, however, that the ones in here are multi-line, and have more information to help identify.

**Comment by duncathan** [comment]
Also I should update ministation's paths; I forgot about the TEG using h/e pipes.

**Comment by duncathan** [comment]
Alright, I did what @MrStonedOne asked. 
Also, this is less a fix, more a refactor.

**Comment by Jalleo** [comment]
merge conflict @duncathan

**Comment by duncathan** [comment]
Yeah I know; I've been away the past week so I haven't been able to get to it.

**Comment by duncathan** [comment]
Conflicts fixed. It also seems as if I've fixed #11398 with this PR; I'm not sure what fixed it but I can't reproduce it on this branch so that's cool.

**Comment by MrStonedOne** [comment]
Please test your code with the following steps:

Test 1:

Wrench up and place back down 1 of every kind of pipe: Simple with 2, 3, and 4 sides, and component with 2, 3, and 4 sides.

(these should already be on the map and connected to something and should have something in them and a meter visible so you know that the gases don't get lost)

Wait 60 seconds. (exactly)

Use the debug verb view del() log, see if any pipe related items are in there, if so, there are loose references pointing to deleted things laying about preventing clean deletion, fix, as unclean deletions cost 0.8ds. (an object's destroy proc should handle clearing any reference that points to it, and should ensure it has no references that point to other things)

Final test:

Spawn a singulo in arrivals, var edit its energy to 9001, possess it, draw a path between arrivals and atmos.
Check for runtimes.
Check for atmos machinery in the del log. (it may take longer for it to process the deletion queue)

**Comment by duncathan** [comment]
First test was all clear; second test left no runtimes (woo) but a few things left in the del log. I'll see what I can do about those.

**Comment by Razharas** [comment]
@duncathan

**Comment by duncathan** [comment]
Once #11505 goes through I'll get back to this one

**Comment by Razharas** [comment]
Its through @duncathan

**Comment by duncathan** [comment]
Ok, all that's left is for me to make components GC properly. DNM this until I've got that down.

**Comment by duncathan** [comment]
Woo! All done. I get no runtimes or failed garbage collects when performing @MrStonedOne's tests as instructed. I've tested all pipes and components and everything seems to be in working order. Turns out I'd done a check in the wrong spot which made components fail to GC if one of their nodes was null.
This is now merge-ready.

**Pull request merged**
