### PR TITLE
Fixes pope spam

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
It's messages/sounds are no longer global. Giant red text every 20 seconds was kind of annoying.

In response to https://tgstation13.org/phpBB/viewtopic.php?f=10&t=6911&view=unread#p185481

@sawu-tg

### CODE REVIEW

**Comment by InsaneHyena** [comment]
Thank God.

**Comment by sawu-tg** [comment]
Thanks @KorPhaeron. I was gunna put this in my next update but you beat me to it.

**Comment by coiax** [comment]
Probably needs its own collection of sounds that isn't just all the hallucination stuff

**Comment by sawu-tg** [comment]
@coiax If someone can make some, that'd be great, but apart from that there's not really many fitting sounds in the game, and i'm no sound maker so I can't really make much more.

**Pull request merged**
