### PR TITLE
Johnathan Rock and Tim Ebow are traitors, also grabs can be triggered at any range, try it out

### PR DESCRIPTION
**Pull request by assblastusafucktheai**
ass blast U S A

### CODE REVIEW

**Comment by MMMiracles** [comment]
theres always a first for something, i guess

**Comment by Incoming5643** [comment]
Doesn't seem to compile, did you test this locally?

**Comment by lzimann** [comment]
how do you feel being this pathetic

**Comment by lollerderby** [comment]
pr of the year

**Comment by Incoming5643** [comment]
>it compiles

Well now don't I have egg on my face

**Comment by kilkun** [comment]
😂👌

Wew lad

**Comment by kevinz000** [comment]
Hey guys where's the I DED and Balance labels I agree tim ebow needs a nerf and I need a buff.

**Comment by Durkel** [comment]
My very own meme pr, Thanks man.

**Comment by Shadowlight213** [comment]
When will people learn that this saltiness leads to everyone NOT going after them and giving them a free pass for tatoring?

**Comment by tedward1337** [comment]
Now this is shitposting

**Comment by kyrahabattoir** [comment]
We already have plenty of ass, :-1:

**Comment by PKPenguin321** [comment]
wow this is really thinking outside the box

**Comment by Zilenan91** [comment]
Ops profile pic even kinda looks like an anus if you squint a bit and have a stroke

**Comment by Jordie0608** [comment]
why is this still open

**Comment by PKPenguin321** [comment]
b/c if you close it it announces the PR closing to the server and ick ocks again

**Comment by francinum** [comment]
tag [s] before closing, obv

**Comment by Zilenan91** [comment]
ban github for ic in ooc

**Comment by Jordie0608** [comment]
I waited for both server's rounds to end; no harm done

**Comment by Shadowlight213** [comment]
never 4get Russel lombardi is a traitor.

**Comment by PKPenguin321** [comment]
nice going oranges

**Comment by kevinz000** [comment]
DO IT AGAIN

**Comment by Sj212** [comment]
jarshmellow plays jarsh mellow

**Comment by CitrusGender** [comment]
posting in historical bread

**Pull request closed without merging**
