### PR TITLE
"Return to lobby if preferences unavailable" Revengence

### PR DESCRIPTION
**Pull request by Incoming5643**
A remake of #4308

:cl:
add: You now have the ability to automatically "back out" of a round if you miss your chance at all the jobs you have set to low or higher. This is found on the toggle at the bottom of the jobs window
add: Due to a quirk of game mode code this option will fail to work if you've been selected as an antag (what a tragedy!) In this situation, you'll be assigned a random job.
/:cl:

### CODE REVIEW

**Comment by MrStonedOne** [comment]
>experiment: Whatever your previous selection for this field was has been lost, so be sure to update it.

I'll pr an update that will convert their old preferences to the new system.

**Comment by RemieRichards** [comment]
Yeah that's unacceptable with the update system we have.

**Comment by Incoming5643** [comment]
felt wrong to burn a version on something so trivial

**Comment by RemieRichards** [comment]
It's far worse to burn everyone's preference settings.

**Comment by AlexCrimson** [comment]
My hero!

...i still think we need a policy to stop the suiciders though.

**Comment by optimumtact** [comment]
Test merge please

**Comment by Incoming5643** [comment]
There might be strange effects of doing a test merge that updates the save file version.

Specifically afterward when the save file is now higher than the max.

**Comment by optimumtact** [comment]
Ok

**Pull request merged**
