### PR TITLE
Secbots/Beepsky no longer can be buckled

### PR DESCRIPTION
**Pull request by bigfatbananacyclops**
beepsky has been bullied for generations, greytides will no longer fuck with him, this is a quick buff so they dont mess with him while i rebalance him later.
beepsky/secbots cant be buckled to chair anymore (sorry greytides).

:cl:
balance: secbots no longer can be buckled
/:cl:

### CODE REVIEW

**Comment by Higgin** [comment]
bit gauche to upvote your own PR - would rather see the ultimate rework than making the hardstun bot stronger now

**Comment by moocowswag** [comment]
Give it flat damage reduction and make it a normal stun baton hit.

**Comment by jughu** [comment]
(In the long run the same thing will still happen except you do it 2 times more

**Comment by bigfatbananacyclops** [comment]
the sole purpose of the buckling proof is that people cheese beepsky by putting him buckled to a chair under an airlock and kill him. You can pretty much get a free baton at the very first minute of the game.

The HP increase is given due to people using floortiles or stacked items to slowly kill beepsky and get a free baton, they're cheesing him over his incredibly slowspeed. Everything here is fair.

Whoever is disagreeing is mad because you cant cheese beepskys baton anymore. :)

**Comment by jughu** [comment]
window plane cbeese is just as simple as the chair

**Comment by bigfatbananacyclops** [comment]
> window plane cbeese is just as simple as the chair im not defending the thing here im just kinda saying beepsky is a lost case anyways due sucky pathing

im planning on giving him greater speed and maintenance patrol routes

**Comment by Elli-Skala** [comment]
Wheel chair beepsky is dead 😔

**Comment by SomeoneYouProbablyKnow** [comment]
This isn't gonna fix the issue. What's gonna end up happening is an arms race between you and people killing secbots, you won't win.
What you'll end up doing is making dragging a beepsky around as a borg or an officer more enticing. Which is cringe.

The problem is that batons are SO valuable people are killing innocent secuitrons over them. And as much as i love the little rusk bucket it's... kinda meant to be killed? The deck should not be stacked in favour of security. Beepsky is already the most robust officer as is.

**Comment by bigfatbananacyclops** [comment]
> This isn't gonna fix the issue. What's gonna end up happening is an arms race between you and people killing secbots, you won't win. What you'll end up doing is making dragging a beepsky around as a borg or an officer more enticing. Which is cringe.
> 
> The problem is that batons are SO valuable people are killing innocent secuitrons over them. And as much as i love the little rusk bucket it's... kinda meant to be killed? The deck should not be stacked in favour of security. Beepsky is already the most robust officer as is.

yes, it's not meant to fix the entire issue. like i said, its meant to prevent people from looting him early game.

**Comment by SomeoneYouProbablyKnow** [comment]
I'm not sure if the idea of an "early game" makes sense. Most players are going to have the same tools throughout the round unless sec opens armoury or something. What does change is the level of chaos on the station, easier to get away with killing a bot when half the station's on fire. But if you make it harder it will be harder 50 minutes in as well.

If you wamt to make it harder early game specifically make it blast an alarm on the sec channel that it's being attacked instead of locking non seccies out of doing anything to the bot (assuming this works, most likely there will be a new method in a week instead, batons are just THAT valuable)

**Comment by DaCoolBoss** [comment]
Buckle change is good. Health change doesn't solve anything, just punishes people who aren't cheesing.

**Comment by MrDoomBringer** [comment]
As someone whose been a professional beepsky killer for many moons, the only real fix here is to make him not drop a stunbaton. Or just make him drop a broken stun baton that needs some special step to fix.

**Comment by bigfatbananacyclops** [comment]
With my 3000+ hour assistant and sec experience i can say this.

If the argument is that beepsky is not noob-friendly, well sir, all of ss13 isnt. It also doesn't take long to learn how to fool its ugly pathing.


One of the problem people dont agree with is, the HP beepsky has when you have time to react. And that is of course, because its nicer to have beepsky be a little bug you can brush off.

There is no difference, even if the hp changes, the supposed players being punished wouldnt make a difference because with 1 or 2 hits because they will be stunned regardless of the efforts, that is if you are close enough to beepsky, while hitting him. Needless to say the horde of tides will happily jump in to break beepsky together.

I don't see why greytide should get protection from beepsky, you aren't antags.

Regarding borgs/players using beepsky vs antags. It wont make a difference because you will be flashed by the borg and both of you will be faster than poor beepsky that (always) will get stuck in any L turn. EVEN if beepsky was unchanged, the problem posed would be the same BECAUSE no antagonist item can exceed 45 hp that would one hit beepsky melee, meaning you will always have to click him twice you risk being stunned in between.

Btw EMPs are widely used especially if your server reeks of borg players.

There is are dozens of ways for antagonists/NONANTAGONISTS to counter secbots, and less likelihood for them to affect you in any way. If you are spotted by beepsky and maintain distance, you won my friend.

B-but what about robotics mas producing secbots?!! Unacceptable!!!
I hope you find a way to click three mobs at once because it doesnt exist, again, wouldn't make a difference if they weren't changed.

Here's a list of how you can outrun a secbot incase u arent an antag :
-walk away
-lockers/crates
-take ur id off
- firelocks to block the way off

Beepsky right now is punishable, he will no longer be.

**Comment by ExcessiveUseOfCobblestone** [comment]
> As someone whose been a professional beepsky killer for many moons, the only real fix here is to make him not drop a stunbaton. Or just make him drop a broken stun baton that needs some special step to fix.

this i think makes more sense, the problem with buffing beepsky is that it needs to be tempered with like a slowdown on pull or something that makes it unwieldy to bring around for when you lose in combat.

**Comment by SomeoneYouProbablyKnow** [comment]
> As someone whose been a professional beepsky killer for many moons, the only real fix here is to make him not drop a stunbaton. Or just make him drop a broken stun baton that needs some special step to fix.

Yea but unless the special step itself is locked behind like... sec gear or something it's just a quick chore. No one stops you from taking a power cell which you need to fix current beepsky batons.

Also the more special steps you add the less normal players are able to access the mechanics, and that's not cool. 
(Normal not as in new but just player going about their round not powergaming for every possibility nor already planning on yoinking a baton already)

Still think the best way would be for beepsky to yell in sec comms when it's attacked instead of any stat changes. There will always be a method to cheese beepsky, only way to change that is to include other people in the equation.

**Comment by jughu** [comment]
make it drop a special mini stunprod which fits in backpack but is a worse stun baton

**Comment by ExcessiveUseOfCobblestone** [comment]
I haven't really been convinced this is a good cure or even a realistic bandaid to beepsky grieffing.

Again, beepsky isnt just fire and forget although its typically used that way, it has the capacity to be pulled easily and babysit people using it to lock down individuals WHILE they are also part of the situation.

A bot that takes several saws/toolbox worth of hits to just kill the thing doesnt sound very fun. If we are going to buff the standalone potential, we need to solidify that by nerfing its "babysit" potential.

**Comment by ExcessiveUseOfCobblestone** [comment]
I'm fine with the buckling change standalone fyi

**Comment by bigfatbananacyclops** [comment]
done, i removed the hp buff, now this will only affect its ability to be buckled

**Comment by Ghommie** [comment]
Edited CL and title following the aforementiond backstep.

**Pull request merged**
