### PR TITLE
Adds OOC verb to show the last round end report you've viewed

### LINKED ISSUE #37873: Can we please return the roundend report to the chatbox
1. You can't access it after the round ends
2. The pop-up window gets in the way of the post-round murder you're either committing or trying to avoid

### PR DESCRIPTION
**Pull request by Cyberboss**
Works just by storing the html in a data file. Too lazy to do it any other way

:cl:
add: You can now view your last round end report window with the "Your last round" verb in the OOC tab
/:cl:

Closes #37873

### CODE REVIEW

**Comment by KorPhaeron** [comment]
cool

**Comment by MrStonedOne** [comment]
Closing a window doesn't necessarily delete it's contents, you could very likely just do a winset to open the window by name and any existing window would just be redisplayed from the clients memory

**Comment by MrStonedOne** [comment]
if you aren't going to store it client side, It would be cool if it would save for people who joined or observed but left before round end. I don't know if it depends on information on the client or not.

**Review by SpaceManiac — CHANGES_REQUESTED** [review]

**Comment by SpaceManiac** [comment]
Bugfixed for you, you can do the mind thing or leave it to a later PR at your leisure.

**Review by SpaceManiac — APPROVED** [review]

**Comment by optimumtact** [comment]
uh, how big is this directory gonna get?

**Comment by Cyberboss** [comment]
1 file per ckey

**Pull request merged**
