### PR TITLE
[READY]Combat Overhaul Staging: Limb Specific Stamina and status effect click delay modifiers

### PR DESCRIPTION
**Pull request by silicons**
No gameplay changes other than
:cl:
experimental: Limb-specific stamina damage (EG: getting shot by security for being bad at the game) now obeys limb damage caps. However, being stamina damaged won't stop that limb from being damaged.
/:cl:

### CODE REVIEW

**Comment by cacogen** [comment]
i don't

**Comment by ExcessiveUseOfCobblestone** [comment]
FIX YOUR CURRENT FEATURES KEKHI

**Comment by Razharas** [comment]
This is good design decision

**Comment by Supermichael777** [comment]
Other then being an unapologetic sec nerf why?

**Comment by kevinz000** [comment]
@Supermichael777 how am i nerfing sec

**Comment by arsserpentarium** [comment]
Add pain threshold.

**Comment by kevinz000** [comment]
@arsserpentarium OH GOD THE PAIN

**Comment by Anonmare** [comment]
oof

**Comment by PKPenguin321** [comment]
This does still respect the 200 overall damage cap right

**Comment by kevinz000** [comment]
@PKPenguin321 stam will still be respecting the normal stamina caps this just adds limb caps to it

**Pull request merged**
