### PR TITLE
Mimana fix

### LINKED ISSUE #8218: Mimana plants don't work consistently (plus small botany bugs)
Grew 100 potency mimanas, ate one, hoped to be silent 5ever. I could talk right the fuck away and the silencing effect seemed to only kick in randomly. Something to do with chem processing?

also I'm not making a separate issue for this but oat stalks appear as "oat Stalks" and not "Oat Stalks" like the capitalization should be

### PR DESCRIPTION
**Pull request by phil235**
- Fixes mimana not dropping mimanapeel when eaten.
- Fixes typo in oat stalks
- Moving dizziness, drowsiness and jitteriness natural decreases all inside the carbon/handle_regular_status_updates() proc.
- Drowzyness now drops faster when resting.
- Adjustment to mutetoxin effect on mob.. Fixes #8218

### CODE REVIEW

**Comment by Chocobro** [comment]
nice-u jobbu

**Comment by bgobandit** [comment]
How will this affect other things that use reagent processing (for instance, EVERYTHING)?

**Comment by Fox-McCloud** [comment]
Don't recommend the change to how reagents process a bit slower, though there may be a better solution.

On Goon, reagents process roughly every 3 seconds (I'm guessing actually 2.7); reagents processing every other life tick is going to make a lot of chems incredibly overpowered or their chance will proc too much in too short of a time.

If there's a better way this can be accomplished, then so be it, but reagents only processing every 3 seconds is better, overall, for balance.

**Comment by phil235** [comment]
I'm restoring reagent metabolizing speed to its original value,  all the reagents on_mob_life() procs are balanced for this speed. Goofball changed that speed two month ago without changing any of the reagent procs accordingly, thus breaking the balance of many reagents and chemicals.

**Comment by phil235** [comment]
I'm removing the metabolization change and instead use a simple buff of mutetoxin effect to fix #8218 .

**Comment by Lumipharon** [comment]
Does the metobolization thing mean that chems (presumably non goon ones) essentially won't work consistantly, if they're designed around trigger more often then they do now?
IE: Working 50% of the time or some shit?

**Comment by phil235** [comment]
The slowdown only potentially breaks reagents with effects that change variables that naturally get back to normal through life() (dizziness, silent, jitteriness, drowsiness, stunned, weakened, paralysis etc..).

**Comment by Iamgoofball** [comment]
Alright so I got a system whipped up in my goonchem part 5 PR that makes the oldchems tick every second, and goonchems tick every 3 seconds. This solves the problem of oldchems being fucked over and doesn't require yet another month of balancing and tweaking on goonchem.

**Comment by Lumipharon** [comment]
Why did you even make goon chems tick at a different rate to begin with?

**Comment by Fox-McCloud** [comment]
@Lumipharon 

Because on Goon their chems tick every ~3 seconds (I suspect 2.7 actual), and many of their rates are balanced around that; kick up the chems to process at the default rate and you suddenly have a problem with most of the numbers.

**Comment by Lumipharon** [comment]
But shouldn't it be a simple matter of dividing the number by whatever ratio our process rate is compared to theirs?

**Comment by Iamgoofball** [comment]
@Lumipharon two reasons:

1. Everyone just finally got used to the new chemicals and are willing to actually use the damn things. Changing it up that drastically again will just cause a repeat of the last 3 months of "fuk goonchem it's op/upuseless"
2. I tried balancing the chems to our tickrate, it made a shitton of stuff insanely overpowered and underpowered even when nerfed/buffed. The amount of damage it dealt/healed wasn't the issue, it was how fast it was going.

**Pull request merged**
