### PR TITLE
RDS-havers now get Gibbering

### PR DESCRIPTION
**Pull request by PowerfulAtom111**
## About The Pull Request

Player characters afflicted with the RDS brain trauma now get the gibbering language in addition to the ones they already know. the PR looks like a webedit (it is) because i cannot clone repos because my connection SUCKS but rest assured i tested it by just downloading it all normally

## Why It's Good For The Game

someone who is insane may not always be able to articulate their ideas in a way we might consider "language," either by accident or on purpose just to show those stupid sheep. the greatest minds of the station need to be able to speak to one another without persecution for their ideas

## Changelog
:cl: PowerfulAtom111
add: after a quick galactic meeting, insane people around the universe can now speak gibbering to express their ideas free from the prying ears of the walls
add: as an insane person, taking your meds deafens your ears to the holy tongue all the other insane people are speaking
spellcheck: added a bit of text to the RDS quirk and the RDS medical record text to highlight the insane's new abilities
/:cl:

### CODE REVIEW

**Comment by Metekillot** [comment]
So they get a 4 point positive perk and +8 points on top of it?

**Comment by PowerfulAtom111** [comment]
> So they get a 4 point positive perk and +8 points on top of it, in exchange for keeping a supply of mindbreaker?

no they just get gibbering. they dont get to choose another language entirely they just get gibbering. on the off chance there is another insane person then its like 50/50 if they actually believe the other is genuinely insane or just fucking with them

**Comment by PowerfulAtom111** [comment]
okay after a lot of fucking around and testing i finally got gibbering to go away when you take your meds and come back when you go off them for too long. downside is that it extends to more than just quirk RDS now, and any schizophrenic can babble nonsense

**Comment by PowerfulAtom111** [comment]
but i have an idea

**Comment by PowerfulAtom111** [comment]
> but i have an idea
 nevermind i tried it and it yelled at me :(
image

**Comment by HoodMilk** [comment]
[https://youtu.be/FyWypcG8A2U?si=VLFBC4K4w1NdpOeE](url)

**Comment by projectkepler-ru** [comment]
maybe use switch statement or have it be an on quirk remove?

**Comment by PowerfulAtom111** [comment]
> maybe use switch statement or have it be an on quirk remove?

if i put it on quirk remove then people with normal hallucinations wont get gibbering removed when theyre cured, so i opted to let the hallucinations handle removing gibbering that way both RDS people and normal schizophrenics get it removed when they stop hallucinating

**Review by tralezab — APPROVED** [review]

**Pull request merged**
