### PR TITLE
Death Squad and ERT Armor now has jetpacks built in

### PR DESCRIPTION
**Pull request by ghost**
:cl: More Robust Than You
balance: Death Squad and ERT hard+spacesuits now have jetpacks built in
/:cl:

After all, deathsquads/ERTs are more likely to be deployed to a destroyed station... and what if the gravity is dead? DEATH COMMANDOS ARE NOT WEAKENED BY A LACK OF PUNY GRAVITY!!

### CODE REVIEW

**Comment by Armhulen** [comment]
Why not

**Comment by DoctoreMad** [comment]
Freeze

**Comment by MoreRobustThanYou** [comment]
@DoctoreMad wasn't the freeze only for like antags?

**Comment by DoctoreMad** [comment]
~PvP in general.~ Oh why do you care I'm a shitposter

**Comment by MoreRobustThanYou** [comment]
this isn't THAT much of a PvP balance, kinda more QoL I think.

**Comment by KorPhaeron** [comment]
Freezw

**Comment by Steelpoint** [comment]
I would say yes to the Deathsquad.

I would argue to place reskinned Advance Magboots in the ERT armoury as a alternative.

**Pull request closed without merging**
