### PR TITLE
Minor maintenance for plumbing

### LINKED ISSUE #83538: Cannot grind down Plumbing constructor. Wrench is no good either!
Reporting client version: 515.1636
## Issue Summary

Plumbing constructor is used to construct and deconstruct plumbing mechanisms.
Character tries to grind it down instead.

## Testmerges:
- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)
- [Fixes free chemsplosion reagent purging by replacing it with the same thing but dangerous](https://www.github.com/tgstation/tgstation/pull/83195)
- [STATION TRAIT GAMEMODE: Station-Wide Background Checks](https://www.github.com/tgstation/tgstation/pull/83307)

## Reproduction:
Make chemical grinder.
Try to deconstruct it with plumbing constructor.

Also, characters are unable to attack it, because they all want to try to grind ANYTHING THEY HOLD IN THEIR HANDS, instead of attacking.

I have to throw hatchets at it to make it disappear.

also anyone can remove the layer switching bound to mousewheel on plumbing constructor? It creates more problems than it should.

### PR DESCRIPTION
**Pull request by SyncIt21**
## About The Pull Request
**1. Qol**
 - Screentips & examines for welder, wrench & plunger tools
 - Examining plumbing machinery will display the reagents & their respective volumes present inside
 - Plumbing grinder now has a grind/juice mode which can be changed by hand
 
**2. Code Improvements**
 - Rapid plumbing device now uses the new attack chain(`interact_with_atom()` & `interact_with_atom_secondary()`) instead of the general `attackby()`
 - Same attack chain improvements applied for plumbing grinder
 -  Plumbing grinder now processes items that enter into it asynchronously 

**3. Fixes**
 - Fixes #83538. Contains various sub changes
     - You can now attack the plumbing grinder with any item in combat mode without the grinder trying to consuming it
     - You can deconstruct the plumbing grinder with the Rapid plumbing device without the grinder trying to consuming it
     - You cannot grind abstract & hologram items in the plumbing grinder
 - Growing vat now uses the correct layer selected on rapid plumbing device

## Changelog
:cl:
qol: more examines & screentips for plumbing machinery
qol: plumbing grinder has a grind/juice mode which be toggled by hand
code: improved attack chain for RPLD & plumbing grinder
fix: You can deconstruct the plumbing grinder with the RPLD
fix: You can attack the plumbing grinder with any item in combat mode without getting that item consumed
fix: You cannot grind abstract/ hologram items in the plumbing grinder
fix: growing vat now uses the correct layer selected on rapid plumbing device
/:cl:

### CODE REVIEW

**Comment by EuSouAFazer** [comment]
Iirc the cytology growing vat was always locked to layer 3, is there a possibility of fixing that aswell?

**Comment by SyncIt21** [comment]
> cytology growing vat was always locked to layer 3, 

So building a growing vat with the cytology rapid plumbing device would always put it at layer 3? Sure I'll look into it

**Comment by PapaMichae1** [comment]
I don't love the behavior of the plumbing chemical grinder defaulting to grinding and juicing as a fallback; it renders it impossible to juice most items since the majority of juicable items are also grindable. I'd rather it was a toggle to set mode or something

**Comment by SyncIt21** [comment]
> I don't love the behavior of the plumbing chemical grinder defaulting to grinding and juicing as a fallback; it renders it impossible to juice most items since the majority of juicable items are also grindable. I'd rather it was a toggle to set mode or something

Sure why not. I can make it toggleable

**Pull request merged**
