### PR TITLE
Hang Loose Bruh! The Beach Biodome Revamp, Reborn

### PR DESCRIPTION
**Pull request by EOBGames**
## About The Pull Request
This PR revives #48548, which was a casualty of Aethernaut's sudden departure from the community. The bulk of the ruin is the same as that PR, but a few alterations have been made:
1. The tiny fans have been removed, in favour of an actual atmospherics system.
2. The freezer has been replaced with a small casino, for more to do.
3. Minor aesthetic additions and tweaks.

beachbiodome

Major thanks obviously have to go to Aethernaut for the revamp.

## Why It's Good For The Game
It revamps one of the more disliked ruins in the game, making it more enjoyable for the players who take the ghost roles, and less likely to influence events on the station at large.

## Changelog
:cl:
add: The Beach Biodome Lavaland ruin has been revamped. Hit the beach and catch some waves, brah!
/:cl:

### CODE REVIEW

**Comment by itseasytosee** [comment]
I don't know because you never mentioned it in the Pr but how is this supposed to fix the current issues with the beach dome? 
I think the major complaint was that it did not really serve the ghost role purpose of helping players learn a system and it was just being used as a +1 up.

**Comment by EOBGames** [comment]
> I don't know because you never mentioned it in the Pr but how is this supposed to fix the current issues with the beach dome?
> I think the major complaint was that it did not really serve the ghost role purpose of helping players learn a system and it was just being used as a +1 up.

Not every ghost role needs to function as a tutorial space imo. As for being used as a 1-UP, the girders blocking the exit can't be broken by anything the beach bums have access to.

**Comment by itseasytosee** [comment]
In that case unlike drone stations and charlie, there is not much to do other than make drinks and swimming pool RP.
I think what you did is good but I'm trying to be the devils advocate.

**Comment by kriskog** [comment]
That's not quite true, it is possible to break out of this one. But it will take a bit of effort at least, and its sure as heck better than what we currently have.

**Comment by kriskog** [comment]
Also, you can cook, bartend, grow weed, play the arcades, take a long shower. Just dont set your expectations too high.

**Comment by Naloacisamazing** [comment]
@kriskog  IIRC its not possible to break outta this without help from a miner, In a conversation I had with aethernaut he made the girders impossible to break without a higher damage weapon that the bar boys could get

**Comment by bluetshirtguy** [comment]
It also depends on if he has internals or not. it makes the outside atmos usually deadly even if he can break the girders

**Comment by kriskog** [comment]
@Naloacisamazing Oh yeah, you are right. He snowflaked the girders, needs a weapon above 22 damage which is more than a thrown spear.
How are miners supposed to help them out? Or get in? Theyd need a wrench in that case, or drain air so their PKA works. If they cant get in, just put this in space and save the lavaland budget.

**Comment by HomocidlePancakes** [comment]
You can cut girders with cutters, that’s how.

**Comment by FantasticFwoosh** [comment]
Im quite sure that ashwalkers are going to cattle-drive goliaths into those girders, so they can get to the tasty morsels of lazy bro-dudes inside.

**Comment by Fikou** [comment]
its not a biodome anymore

**Comment by ChemicalRascal** [comment]
> Im quite sure that ashwalkers are going to cattle-drive goliaths into those girders, so they can get to the tasty morsels of lazy bro-dudes inside.

Such is the way of the beachbum, my dude. We party until we die! Be excellent to one another and embrace the sweet relief of death, my dude!

**Comment by gitbirb** [comment]
wheres the dance machine/jukebox?

**Comment by kriskog** [comment]
They are right, it is no longer a dome since its not round. Time for a rebranding!

**Comment by cacogen** [comment]
it's still gonna suck

**Comment by kriskog** [comment]
But it will suck in a more contained way. No more sucking for everyone, just the few people who decided to (not) spawn here.

**Comment by cacogen** [comment]
Perhaps the only difference between me and other people is that I've always demanded more from the sunset

**Comment by IndieanaJones** [comment]
I would much prefer they just be removed or their gameplay reworked instead of giving them more mostly useless things to do.  This seems like something people will enjoy for like a few days, and then the ruin will return to its role as a spawn blocker for the actually good roles.

**Comment by kriskog** [comment]
Id like the two pipes going to the middle part covered up somehow, otherwise this is fine. Could give them a few more canvases too I guess

**Review by kriskog — CHANGES_REQUESTED** [review]
Id like the two pipes going to the middle part covered up somehow, otherwise this is fine. Could give them a few more canvases too I guess

**Review by kriskog — APPROVED** [review]

**Pull request merged**
