### PR TITLE
[WIP] The warden now innately knows krav maga, but can only use it while inside of Sec

### PR DESCRIPTION
**Pull request by ATH1909**
## About The Pull Request

This PR is an alternative to https://github.com/tgstation/tgstation/pull/49079.

Basically, the warden's Krav Maga now works like the chef's CQC in that it can only be used while inside of Sec. It's also no longer tied to a pair of gloves that can be stolen/looted by murderboners, instead being innately known by the warden. Note that admins can still spawn in the old version of the gloves (which have/has a new description now) and nuke ops can still buy combat gloves plus, and the version of Krav Maga that's learned from those will work anywhere.

Also, I removed the mostly-pointless, RNG-dependent, weapon-stealing thing from Krav Maga's disarm_act() and replaced it with the ability to shove people while knowing krav maga (in other words, Krav Maga disarms now work like normal disarms, so you can stun knocked down people and stuff with them now).

Also, yes, you can use warden!Krav Maga in security checkpoints.

## Why It's Good For The Game

This PR incentivizes wardens to stay in the brig instead of validhunting in maint/patrolling the halls with their shotgun and gamer gloves. Also, murderboners won't be able to steal the krav maga gloves anymore and use them to stun people without visibly holding a weapon.

Krav Maga will still be very strong, but antags will usually only have to face it if they're trying to invade/escape from Sec or steal from the Armory, which should both be very dangerous things to try to do anyway.

imsxz approved:
> you guys have some exceptionally good ideas and suggestions, however, im extraordinarily lazy. if i had to choose id go with athath's for sure.

## To-Do List:
* Buff lung punch. I'm probably gonna buff its oxyloss damage, add some confusion and/or eye blurring to its effects, and make it make its target drop whatever they're holding if it connects.
* Add punchdamagelow to the damage of harm_act() attacks with Krav Maga.
* Make the warden not need to eat while they're in the brig/Sec.
* Make the warden slowly regenerate (or maybe just fall into a regenerative coma if they get critted?) while in Sec, so that they can pull an anime comeback when they pull themselves out of crit and shotgun that murderboner in the back.
* Allow wardens to pry open unpowered sec doors (and sec shutters) with their bare fucking hands, even if they're bolted.
* Add some reskinned insulated gloves to the warden's locker as replacements for the gloves that I removed from it.
* Maybe make leg sweep knock you down for 8 seconds instead of hardstunning you for 4 seconds, to make it overshadow the other moves slightly less. Note that this just turns the one click stun into a two click stun, as krav maga users will be able to shove knocked down people for a 4 second hardstun if this PR goes through.
* Make it so that if you leg sweep or lung punch someone while on disarm intent and have a free off hand, your character will automatically snatch the weapon(s?) that your opponent dropped out of mid-air and equip them in their off hand (but still keep your main hand free, so that it won't be annoying). Add some badass flavor text to this (maybe even add a *flip?).
* Make Krav Maga more effective against people who've been set to arrest, detained, or paroled, to add a(nother) minor incentive for wardens to actually set people to arrest when I fucking tell them to (and to set people whom they release to "paroled" in case they act up again). Don't make the bonus too large, though, or powergaming wardens will start setting everyone's status to "paroled" during their downtime, "just in case".
* Add a button that explains some of these mechanics to you when pressed, sort of like how CQC does it.
* Give warden headsets   B I G T E X T .
* Maybe replace that "midisecians" joke in the description(s) of the Krav Maga implant with something else; it doesn't really match up with the rest of the VERY DEEP Krav Maga lore.
* Maybe give Krav Maga a block chance against unarmed attacks, sort of like what held chairs have? I dunno, I kind of like it when a prisoner doesn't have to depend on RNG to escape from the clutches of an incompetent warden.

## Changelog
:cl: ATHATH
add: Krav Maga now has some extra   L O R E .
del: Krav Maga gloves no longer spawn in the warden's locker.
balance: Wardens now know Krav Maga innately, but can only use it while inside of Sec. Maybe this will finally incentivize you to STAY IN THE FUCKING BRIG, WARDENS.
balance: Krav Maga disarms now work like normal disarms, so you can stun knocked down people and stuff with them now (before, it used to just try to make an RNG-dependent weapon-stealing attempt that was probably a holdover from before the disarming system got reworked).
/:cl:

### CODE REVIEW

**Comment by ninjanomnom** [comment]
I'd rather not add more innate benefits to jobs and this TODO list is a joke.

**Comment by ATH1909** [comment]
> I'd rather not add more innate benefits to jobs and this TODO list is a joke.

Only SOME of the to-do list is a joke.

And hey, we have the chef's CQC as a precedent. If a civilian can be allowed to know deadly martial arts while they remain in a certain area, why not a specially-trained member of sec?

**Comment by imsxz** [comment]
close my PR once youve made a decision about whether or not to merge this one, maintainers. i prefer this idea MUCH more than my own.

**Comment by ninjanomnom** [comment]
I don't care about precedent and the chef's cqc is similarly bad imo

**Comment by ATH1909** [comment]
For legal reasons, I'm gonna have to save adding those things that I mentioned in that to-do list for future PRs. I wanted to put them in this PR, but the coders on Discord said that it'd be a bad idea to try adding some of the goofier ideas in with the saner ones.

I think the PR in its current state should be able to stand on its own pretty well, so once I get around to testing the current state of this PR tomorrow, I'll be able to remove the [WIP] tag, I think.

**Comment by PKPenguin321** [comment]
that todo list is too much

**Comment by Qustinnus** [comment]
@ninjanomnom can you elaborate on your distaste for innate abilities? I feel like they make good sense for specific jobs such as warden where the training is implied. And they allow for jobs to actually matter and not prevent some random joe from powergaming as hard.

**Comment by TheVekter** [comment]
Are you taking the piss

I'm okay with the Warden's kung fu being restricted to the brig, but come the fuck on. If some of these are a joke, remove them so we know what you're _actually_ working on.

**Comment by necromanceranne** [comment]
>Make the warden not need to eat while they're in the brig/Sec.

What are they, a fucking monastic jailer? Do they need to recite fucking poetry before ventilating a man to death with their shotgun?

**Comment by TheVekter** [comment]
> 
> 
> > Make the warden not need to eat while they're in the brig/Sec.
> 
> What are they, a fucking monastic jailer? Do they need to recite fucking poetry before ventilating a man to death with their shotgun?

There's this fucking meme about the warden leaving the brig where people get incredibly shitty about it, so some people want a function where he never leaves so he can't play supercop.

**Comment by Shadowflame909** [comment]
I will only accept these editions if there's a roundstart life candle in the armory that only the warden cab link with, and upon leaving security they instantly die.

**Comment by Shadowflame909** [comment]
I will only accept these additions if there's a roundstart life candle in the armory that only the warden cab link with, and upon leaving security they instantly die.

**Comment by Tlaltecuhtli** [comment]
problem with innate is that hop can just open 20 warden slots while turning every area into armory with blueprints during war ops

**Comment by Shadowflame909** [comment]
> problem with innate is that hop can just open 20 warden slots while turning every area into armory with blueprints during war ops as krav naga is one of the rare items that work with ephedrine for 24/7 speed without downsides

Cqc chef says this doesn't happen.

And CQC is always stronger then krav maga

**Comment by improvedname** [comment]
Cqc chef had the issue before but you can make it area turf spefific

**Comment by HomocidlePancakes** [comment]
Warden can eat ass. If he loses the gloves it's his fault.

**Comment by nightred** [comment]
here is some ideas to stop the roundstart special skill idea.
Remove the area requirement for this and make it a skill subtype of unarmed so anyone can learn it with training. Scale the effects based on skill. Give the warden 9-10 (or near max) points in it round start

**Comment by ninjanomnom** [comment]
>can you elaborate on your distaste for innate abilities?

Roundstart benefits are fine in general but properties of the job that stick with you are what I don't like. Equipment is fine since anyone can use it but abilities that you can only get through starting as a specific job are distasteful to me. It's like a sort of gameplay design version of code spaghetti. I'd prefer it be possible to work your way towards any setup even if in practice it ends up being difficult to achieve.

**Comment by Ty-the-Smonk** [comment]
> > can you elaborate on your distaste for innate abilities?
> 
> Roundstart benefits are fine in general but properties of the job that stick with you are what I don't like. Equipment is fine since anyone can use it but abilities that you can only get through starting as a specific job are distasteful to me. It's like a sort of gameplay design version of code spaghetti. I'd prefer it be possible to work your way towards any setup even if in practice it ends up being difficult to achieve.

I mean if warden could get antag then it would be a bigger issue, also how does this affect combat gloves +?

**Comment by wesoda25** [comment]
This PR will be good as long as you don’t do a single thing on your to do list

**Comment by ExcessiveUseOfCobblestone** [comment]
the chef CQC meme is an exception, and a bad one at that.


all of this work so krav can keep its hard stun seems a bit silly...

**Comment by itseasytosee** [comment]
10/10 lore death to nanochips

**Comment by optimumtact** [comment]
not funny, did not laugh.

**Comment by ATH1909** [comment]
> > > can you elaborate on your distaste for innate abilities?
> > 
> > 
> > Roundstart benefits are fine in general but properties of the job that stick with you are what I don't like. Equipment is fine since anyone can use it but abilities that you can only get through starting as a specific job are distasteful to me. It's like a sort of gameplay design version of code spaghetti. I'd prefer it be possible to work your way towards any setup even if in practice it ends up being difficult to achieve.
> 
> I mean if warden could get antag then it would be a bigger issue, also how does this affect combat gloves +?

Combat gloves + have a different description, but still work the same way that they did before.

Also, aw, this got closed.

**Comment by LemonInTheDark** [comment]
Needed rework, he just memed too hard for the citrus

**Comment by HomocidlePancakes** [comment]
No.

**Pull request closed without merging**
