### PR TITLE
Removes donut steelpoint

### PR DESCRIPTION
**Pull request by InsaneHyena**
#:cl:
del: Removes crashed marine transport from lavaland

/:cl:

[why]: # There is literally no excuse for this to exist. It's like crashed prisoner transport, but this time with a single heavily armed donut steel (basically, Steelpoint's excuse to add more tacticool guns) that goes to the station to validhunt. This is disgusting.

### CODE REVIEW

**Comment by Iamgoofball** [comment]
:-1:

**Comment by DoctoreMad** [comment]
>👎

Goofball predicts what is going to happen to his life: The post

**Comment by InsaneHyena** [comment]
Don't bully Goofball, he's a good boy who dindu nuffin

**Comment by Kromgar** [comment]
We already had the fucking hermit ruin where you have no gear other than an oxygen tank, a pick, a orange space suit and a survival knife and your supposed to get to the station. Oh and his light source is glowshrooms. 

Meanwhile steelpoint adds an ezmode hermit who has a gun with extra ammo clips and fancy ass armor.

**Comment by DoctoreMad** [comment]
(Remove hermit while you're at it)

**Comment by MMMiracles** [comment]
dont you touch the HERMIT

**Comment by DoctoreMad** [comment]
Touch my HERMIT

**Comment by obscolene** [comment]
garbage ruin that adds nothing of value to the game

**Comment by InsaneHyena** [comment]
But what about all that LORE about one Earth goverment, and all of those cool ballistic weapons?

**Comment by DoctoreMad** [comment]
>one Earth goverment

Illuminati round type when
Earth Government is trying to swallow Nanotrasen without anyone knowing. A few of the crew members start as Masons, an head of staff starts as head mason.
Masons have weaker mind control tools that can reverse convert mindshielded crewmembers, has goal of breaking Security and Captain into seceding form CentComm.

I was writing this ironically but then I realized that A)Someone is going to take it seriously and B)Oh god reverse revolutionary sounds horrible

**Comment by Armhulen** [comment]
just DO IT

**Comment by dannno** [comment]
yeah fuck this

**Comment by tortellinitony** [comment]
Yeah fuck it

**Comment by Bawhoppen** [comment]
Just remove the ruin, don't remove the new content

**Comment by DoctoreMad** [comment]
Nothing in the game will use it though

**Comment by kevinz000** [comment]
what bawhop said
admin events!

**Comment by Bawhoppen** [comment]
not everything has to be used every round

**Comment by dannno** [comment]
admin """"""""""""""""""Events"""""""""""""""""""""""""

**Comment by Cheridan** [comment]
Bahaha that lore. Steelpoint's snowflake marines strong enough to defeat actual Nar-Sie

**Comment by Kromgar** [comment]
Wow @Steelpoint A+ Fucking lore marines capable of beating nar'sie

**Comment by RandomMarine** [comment]
Oh come on that's a legit lovecraft reference. @Cheridan @Kromgar

**Comment by PKPenguin321** [comment]
its a reference to the bug where the escape/cargo/mining shuttle landing on narsie and delete it

**Comment by Steelpoint** [comment]
Seems a bit premature to remove it. Instead of letting me balance the role out you just want to gut it entirely?

I've already proposed a PR to replace the Combat Medkit.

I've also got a plan for a PR to slightly rework the weapons the Marine spawns with.

My intention for this addition was never malicious. I just ask to be given time to work on the role instead of just jumping onto the 'revert' train.

**Comment by Steelpoint** [comment]
Also there seems to be some misinformation.

The rifle has a limited fire range of five tiles, not fifty unlike most guns. The rifle does not have a burst fire function. Also you can not produce more bullets, or buy more magazines, for the gun on station.

**Comment by InsaneHyena** [comment]
I don't want any trace of this shitpile to remain in the code.

**Comment by Steelpoint** [comment]
Irrespective there is precedent in this, in that you don't remove the entire code + map + sprites. If you simply just remove the part that spawns the ruin and leave the rest.

Gutting the whole thing is just vindictive.

All I can say is that I have some changes I am making to lessen the roles impact on a round and I ask to be given the chance to effect those proposals, we've given other projects months of time to finalise their balance, I'm just asking for a week to implement and see the effects of a change.

**Comment by InsaneHyena** [comment]
As you can see, a lot of people, including the mantainers, want this out. Now. Just look at the vote disparity - your OC isn't exactly popular, and I don't think the problem is the gun, or the gear, or anything like that. I think it's the fact that you created a blatant self-insert, and it's something you can't fix or disguise no matter how much balance PRs you make.

**Comment by Steelpoint** [comment]
If the character being a Marine is the issue then I can re-work it that you are instead a pilot or ships technician.

Heck I could make it random, a random choice between a marine, pilot, technician or something else, with different equipment and so on.

I never created this as a self insert but you only have my word for that.

**Comment by Steelpoint** [comment]
Yeah I think I'm going to go with the idea of a randomized role selection. Either a Marine with unique armour a slightly buffed survival knife, a Technician with CE Engineering tools or a Pilot with Night Vision Goggles. 

I'll remove the firearm as well, keep it to Capture The Flag as a insta kill gun. 

PS: Hope you did not remove the gun sprites in this PR. They are used elsewhere.

**Comment by Bawhoppen** [comment]
he just clicked the autorevert button I'm pretty sure

**Comment by InsaneHyena** [comment]
I actually removed them all manually, because I had no idea an auto-revert button existed.

**Comment by Steelpoint** [comment]
I'll propose my alterations based on the outcome and state of this PR. If this PR removes the entire code+sprite+map then I'll simply drop any further changes, if the PR is either closed or if it just removes the ruin from spawning on the map I'll work on my proposal.

I would ask to be given the chance to make my changes, but I'll leave that to the powers that be.

**Comment by DoctoreMad** [comment]
Steelpoint, the overall idea of having a 2nd hermit role that has to reach back to the station except its stronger than a normal hermit is a bad one.

**Comment by Kromgar** [comment]
@Steelpoint your proposed ideas are literally just it's Hermit with armor and a gun too!

**Pull request merged**
