### PR TITLE
Makes the cargo-orderable space suit a generic engineering hardsuit

### PR DESCRIPTION
**Pull request by silicons**
Fine as is, but if someone could get me sprites for a civillian hardsuit that'd be great.
Changes the space suit you can order for 3k points into a single generic hardsuit instead of .. a space suti and.. two helmets... also, it now only contains a single mask instead of two.

### CODE REVIEW

**Comment by Cheridan** [comment]
>its a kevinz powercreep pr

**Comment by Shapsy** [comment]
Why

**Comment by CPTANT** [comment]
Why did the space suit crate contain 2 helmets?

And why does it make sense to turn it into an engineering hardsuit?

**Comment by BeeSting12** [comment]
Because 90% of engineers steal the hardsuit and fuck off and die every round, leaving engineering without a hardsuit.

**Comment by lzimann** [comment]
so add a new crate with engineers hardsuit and engineering id locked?

**Comment by CPTANT** [comment]
Lol the crate now orders 1 spacesuit without a helmet and 1 hardsuit.

**Comment by Bawhoppen** [comment]
stop with the powercreep

**Comment by FantasticFwoosh** [comment]
People wearing EVA suits with this change are now valid for trying to leave with station objectives.

I approve.

**Comment by PKPenguin321** [comment]
:-1: Blatant powercreep

**Comment by SgtxRootbeer** [comment]
Maybe give robotics either the ability to make hard suits, or make a tool(s) for the Ripley that can operate like every tool in the default tool belt, interface with devices, build "machines", and a radiation armor upgrade.

**Pull request closed without merging**
