### PR TITLE
Crafting menu now opens on compact mode by default

### PR DESCRIPTION
**Pull request by lzimann**
Hopefully it is the right way to do that.

Compact mode is way better looking than the full menu.

### CODE REVIEW

**Comment by RemieRichards** [comment]
I'm torn... you're replacing something I made with... something I made.
It may be better to rip it out to a preference, something like ```tgui_compact``` "will display compact forms of tgui interfaces where possible"

**Comment by lzimann** [comment]
If you think a preference is better I can close this and make an actual pref. I just think the compact mode is way prettier and better to look at than that huge amount of letters the normal mode gives.

**Comment by Razharas** [comment]
Before/after screenshots plz

**Comment by lzimann** [comment]
[Before](http://puu.sh/qJ8eL/025ccde013.png)

[After](http://puu.sh/qJ8f8/43aa148cef.png)

It's just the compact toggle(if you hover over "craft" it will show the requirements).

**Comment by RemieRichards** [comment]
My original screenshot from when I added it shows it off better:

compacto

**Comment by optimumtact** [comment]
Saeg had a great suggestion on the forums somewhere to replace the tabs at the top with icons so you can fit all the categories on the view - with a mouseover tooltip full name.

**Pull request merged**
