### PR TITLE
Lets the wizard turn into an immovable rod

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
Briefly, anyway. Using the spell will transform you into an immovable rod, sending you travelling around a full screens worth in the direction you were facing when you used the spell.

:cl: Kor
add: The wizard has a new spell, Rod Form, which allows him to transform into an immovable rod.
/:cl:

### CODE REVIEW

**Comment by kevinz000** [comment]
wew

**Comment by lzimann** [comment]
you know this is a bad idea

**Comment by jughu** [comment]
Only if the rd catches the immovable rod if he clicks on it with a plant pot and insta kills the wizard

**Comment by AnturK** [comment]
Kinda silly with so small cooldown.

**Comment by AdamElTablawy** [comment]
ragin' mages is gonna get shafted, i'll tell you that much

**Comment by KorPhaeron** [comment]
@anturk

I am open to raising the cooldown. I had it up at 60 to compare to EI NATH beforr I remembered fireball is like 6 seconds

**Comment by KorPhaeron** [comment]
@memo lzimann

Why is it a bad idea?

**Comment by KorPhaeron** [comment]
@lzimamn what's wrong with it?

**Comment by AdamElTablawy** [comment]
honestly i feel like it'd make rounds a bit too long and hard.

you can't play a normal round without getting shafted these days, nowadays.

iron-eed this sort of stuff to stop and my honest concern is that issues like this penetrate right to the heart of the problem.

okay i'm done with the shitty puns that barely make sense

**Comment by Supermichael777** [comment]
expecting a wizard round to be fun for more then 4 people

**Comment by xxalpha** [comment]
This is a fun pr.

**Comment by GunHog** [comment]
This is an awful idea, and I support it!

**Comment by ChangelingRain** [comment]
this is such a bad idea

**Comment by Steelpoint** [comment]
this really is such a bad idea

**Pull request merged**
