### PR TITLE
Move the clown and mime's unique crayons to their PDAs.

### PR DESCRIPTION
**Pull request by Expletive**
:cl:
tweak: The Clown and Mime can now find their unique crayons stored inside their PDAs
/:cl:

Since PDAs can store crayons, and can have non-standard pens at roundstart, this seems like a natural thing to do.

### CODE REVIEW

**Comment by vcordie** [comment]
sure why the fuck not

**Comment by improvedname** [comment]
Haalt halt halt!
Dont forget the option pen uplink what would happen if you dont have a pen

**Review by Cyberboss — APPROVED** [review]

**Comment by nicbn** [comment]
> Dont forget the option pen uplink what would happen if you dont have a pen

Good point.

**Review by Cyberboss — APPROVED** [review]

**Comment by Cyberboss** [comment]
As a side effect traitors and mimes can't use pen uplinks, Allowing crayon uplinks is for a different PR.

**Pull request merged**
