### PR TITLE
Starting a vote now opens the UI

### PR DESCRIPTION
**Pull request by jlsnow301**
## About The Pull Request
It can be pretty easy to miss the vote window, it's a single chat message and an icon.
I made it so that the UI comes up once there is an active vote.
This also tweaks the vote UI and fixes some small issues with it (mostly spacing).
Added some documentation to the vote subsystem.

## Why It's Good For The Game
More active voters for polls, map votes, restart.

## Changelog

:cl:
qol: The vote panel now opens when there is an active vote. No more missing the prompt!
/:cl:

### CODE REVIEW

**Comment by Serxule** [comment]
so this automatically opens it for everyone when a vote starts? that sounds like a horrible idea if you're in the middle of fighting, etc

**Comment by Ghommie** [comment]
As Serxule said, it can be pretty annoying for those busy doing different tasks. I would suggest you restrict these to lobby/observer players. Good idea anyway.

**Comment by MrDoomBringer** [comment]
\>fighting someone
\>about to get owned
\>quick! start a vote!
\>take their baton while they're distracted and kill them

**Comment by Imaginos16** [comment]
A server I play in made the vote sfx the vine boom sound. While I 100% agree with the solution in this PR, I feel a loud, obnoxious sound that's very hard to miss could be an alternative in the cases someone is in the middle of a fight.

**Comment by jlsnow301** [comment]
i'm thinking of changing it to just alert twice or something. the changes to vote ui stay, however

**Review by stylemistake — APPROVED** [review]

**Comment by Mothblocks** [comment]
*Definitely* not, this is some really annoying UX.

I would like to see other ways this can be done, like pinning something in the chatbox the same way admins playing music is, for example.

**Pull request closed without merging**
