### PR TITLE
Adds the golden revolver

### PR DESCRIPTION
**Pull request by Incoming5643**
d10_icon

Shakes the screen like a bastard and sounds really painful, but only does normal revolver damage.

A little easter egg weapon for a game you should have played.

Will be added to summon guns at some point

### CODE REVIEW

**Comment by PKPenguin321** [comment]
should be added to gang

**Comment by KazeEspada** [comment]
Goldeneye?

**Comment by Incoming5643** [comment]
That'd be the golden gun, this is the golden revolver

**Comment by GunHog** [comment]
Nuclear Throne?

**Comment by Incoming5643** [comment]
we have a winner

**Comment by GunHog** [comment]
Also, yes, golden guns for Gang. Gang could use more in terms of things that look cool. Does not have to be the revovler, but just more "bling".

**Comment by Incoming5643** [comment]
The golden revolver is strictly worse than the normal one, because the super shake makes rapid fire nearly impossible.

**Comment by Zilenan91** [comment]
Detective revolver skin?

**Comment by PKPenguin321** [comment]
golden revolver being strictly worse may actually be good for balancing gangs having them, since there would be a lot of revolvers

**Comment by Zilenan91** [comment]
Let's not give gangs revolvers

**Comment by PKPenguin321** [comment]
but it's so shiny

**Comment by hornygranny** [comment]
this was in perfect dark :cop: :e-mail: :arrow_right:

**Comment by Incoming5643** [comment]
@Dorsisdwarf Conflicts Resolved

**Comment by tkdrg** [comment]
it's admin only so memes are fine

**Comment by tedward1337** [comment]
YES

**Comment by Bawhoppen** [comment]
you didn't even get the right game in OOC ted 0/10

**Pull request merged**
