### PR TITLE
Exotic Blood

### PR DESCRIPTION
**Pull request by Incoming5643**
Adds a new species var, exotic_blood, that can be used with species that don't have traditional blood so you can still draw something from them with syringes if such a thing logically makes sense.

It's used here to allow slime jelly to be drawn from slimepeople (and the far less seen jellypeople)

In both cases slime jelly is produced from nutrition, and will always do so unless you've got either extremely low nutrition or extremely high slime jelly.

Practical effects of this:

*You can kill slimepeople in a few special ways, you can syringe all the jelly out and once they run out of nutrition to replace it they'll stop breathing, chems that help clear toxins also screw them over BADLY in this way.

*slimepeople get free access to a semi-potent toxin whenever they want provided they have a syringe on hand, but have to manage their nutrition if they rely on it. Also it's immediately obvious they're at fault as slime jelly can't be produced anywhere beside xenobiology and produces unique messages.

*Other chems can be syringed wholesale out of slimepeople as well provided they haven't been metabolized yet.

### CODE REVIEW

**Comment by Iamgoofball** [comment]
does this mean I can make someone's blood liquid dark matter

:+1:

**Comment by Incoming5643** [comment]
you can absolutely do that and shadow people are already a thing

**Comment by ExplosiveCrate** [comment]
If you add a changelog, you should note that processing monkeys yields a blood bucket, so people won't complain that blood reactions are broken.

**Comment by AnonymousNow** [comment]
What about making xenomorphs have acid for blood, since it's already bright green?

**Pull request merged**
