### PR TITLE
Nerfs teamwork

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
https://tgstation13.org/phpBB/viewtopic.php?f=10&t=7805&view=unread#p209917

### CODE REVIEW

**Comment by nullbear** [comment]
Can we actually testmerge.

**Comment by Kromgar** [comment]
Fuck you and your memes.

Emp blob is op when blobs team up. Just destoriyng the blob releases emp bursts. So emp blob and other blob created emp traps

**Comment by Iamgoofball** [comment]
>conflicts already

**Comment by phil235** [comment]
Can we stop with the joke PRs please?

**Comment by calzilla1** [comment]
No

**Comment by Iamgoofball** [comment]
No

**Comment by evsey9** [comment]
testmerge

**Comment by JJRcop** [comment]
Something is coming

**Pull request closed without merging**
