### PR TITLE
Fix heretic sacrifice minigame to drop legcuffs

### LINKED ISSUE #69435: Leg cuffs make heretic sacrifice minigame unsurvivable (Not a bug) (Maybe an oversight)
## Round ID:
[189138](https://scrubby.melonmesa.com/round/189138)

## Testmerges:
#69023 
#68239 

## Reproduction:
1. Get leg cuffed before being sent to the shadow hand realm.
2. Have no chance of survival
3. Cry and Die

I think this shouldn't happen that way, the leg cuff should be removed in my opinion because it basically removes the whole minigame aspect of being sacced.

### PR DESCRIPTION
**Pull request by timothymtorres**
## About The Pull Request

Fixes #69435

Legcuffed people would die during the heretic minigames.  They now have their legcuffs removed before the minigame is started.

## Why It's Good For The Game

Herectic minigame won't be instadeath if you are legcuffed.

## Changelog

:cl:
qol: heretic sacrifices will drop their legcuffs before entering the minigame (bolas, bear traps)
/:cl:

### CODE REVIEW

**Comment by itseasytosee** [comment]
Don't you think it would be easier to just, ya know, remove the leg cuffs?

**Comment by SuperSlayer0** [comment]
Maybe just make people drop legcuffs before getting sent to the sacrifice area?

**Comment by Miczu555PL** [comment]
Just make them drop their leg cuffs. I want my bola back I always forget about it..

**Comment by timothymtorres** [comment]
I stole the code from leg amputation at:

https://github.com/tgstation/tgstation/blob/7844b34a5fc507a3fd53ed2fc9eea690e9c1f0c7/code/modules/surgery/bodyparts/dismemberment.dm#L286-L295

**Pull request merged**
