### PR TITLE
NERFS GOLIATHS

### PR DESCRIPTION
**Pull request by Cheridan**
resprites their stupid tentacles so you can actually freaking see them

tentaclegif

### CODE REVIEW

**Comment by optimumtact** [comment]
>lavaland favouritism intensifies

**Comment by PKPenguin321** [comment]
nice sprite

**Comment by ChangelingRain** [comment]
Resprite it so it works on all terrain, not just lava/basalt.

**Comment by optimumtact** [comment]
@ChangelingRain that doesn't make much sense

**Comment by Cheridan** [comment]
its really just opening a portal to the lava dimension, like how Cyclop's eye lasers work

**Comment by ChangelingRain** [comment]
This replaces the normal goliath tentacle if for some reason we're on a map that doesn't have lavaland, resprite it so it works on all terrain.

**Comment by KazeEspada** [comment]
Just have goliath tendrils associated with their sprite

**Comment by Iamgoofball** [comment]
>its really just opening a portal to the lava dimension, like how Cyclop's eye lasers work

**Comment by optimumtact** [comment]
its really just opening a portal to the lava dimension, like how Cyclop's eye lasers work

**Comment by GunHog** [comment]
I like the thin, long version, though. It looks more flexible...something that can be used for...applications which require fine coordination...

**Comment by Shadowlight213** [comment]
Leave it to gunhog to make it about erp..

**Comment by Cheridan** [comment]
"NO STOP ATTACKING I'M A FRIENDLY GOLIATH UGUU~~"

**Comment by Steelpoint** [comment]
I like it. 

Worst case couldn't you make a sub-type of a Goliath for each terrain type and alter the tentical ground  colour for different areas?

**Comment by RandomMarine** [comment]
Why not just have the tentacles themselves adjust sprite based on the turf they spawn on?

**Comment by KorPhaeron** [comment]
>its really just opening a portal to the lava dimension, like how Cyclop's eye lasers work

**Pull request merged**
