### PR TITLE
Add config for discord bot prefix

### PR DESCRIPTION
**Pull request by optimumtact**
This allows you to set this in config, save having to hardcode it

I also fixed a mistake where only one message was changed in the
messaging from the account linking system

### CODE REVIEW

**Comment by checkraisefold** [comment]
This is denyed

**Comment by optimumtact** [comment]
you are denyed, denyed entry to this organisation ever again

**Comment by Jared-Fogle** [comment]
@MrStonedOne something something host and config updates

**Comment by Jared-Fogle** [comment]
this is approved

**Pull request merged**
