### PR TITLE
Demonic Frost Miner can spawn again

### LINKED ISSUE #62901: Demonic frost miner arena doesn't spawn correctly
## Reproduction:
Be demonic frost miner, don't have your arena (or you) spawn because there are some walls and 3 dogs underneath you

Topmost layer of the arena is present (the big arena-sized hole and the hut), there's nothing in the hole and a structure 2 levels below. I'm pretty sure this is not intended.

### LINKED ISSUE #72943: Demonic frost miner still fails at loading occasionally
Reporting client version: 514.1585

## Round ID:
[198842](https://scrubby.melonmesa.com/round/198842)

## Testmerges:
- [Refactors Suicide Verb + Basic Mobs Can Now Suicide](https://www.github.com/tgstation/tgstation/pull/72919)
- [Refactors crew records](https://www.github.com/tgstation/tgstation/pull/72725)
- [Potentially fixes roundstart firelock hell](https://www.github.com/tgstation/tgstation/pull/72887)

## Reproduction:

(id assume this is because it spawned on top of the lake below sec)
image

### PR DESCRIPTION
**Pull request by Whoneedspacee**
## About The Pull Request

Fixes #72943
Fixes #62901

This fixes specifically icebox multi-z ruins not spawning with their counterpart below ruins because the area for the underground portion of icebox was not whitelisted so there were no valid spawn positions.

## Why It's Good For The Game

Multi-z icebox ruins working is good.

## Changelog

:cl:
fix: Multi-z Icebox ruins including the Demonic Frost Miner can now be placed again
/:cl:

### CODE REVIEW

**Comment by Sealed101** [comment]
hi

_For future reference, [these](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) are all the keywords that can be used to link issues/PRs._

**Review by Ghommie — APPROVED** [review]

**Comment by msgerbs** [comment]
Unless somebody else fixed it, this still doesn't fix the core issue which is that the mapping subsystem doesn't check if the lower part can spawn when picking the location. This may help in some cases but will not fix all of the issues with multi-z ruins.

**Comment by Whoneedspacee** [comment]
> Unless somebody else fixed it, this still doesn't fix the core issue which is that the mapping subsystem doesn't check if the lower part can spawn when picking the location. This may help in some cases but will not fix all of the issues with multi-z ruins. What actually needs to happen is that linked ruins need a rewrite to place them all at once in a single execution instead of just plopping the linked ruins into the queue to be placed later.

It's not perfectly seperated and working properly yeah, but it's pretty close to since the placing of the above ground ruins happens first which means that the middle z levels are empty when the lower parts are placed, obviously this is changing as of late since people are making edits to multi-z maps so there are things placed by default.

Would definitely be cool if multi-z ruins checked if both placements were valid before doing anything.

**Comment by msgerbs** [comment]
When I looked, the issue was not the other ruins since this was always one of the first to place, but rather the lower parts of the station. It would try to place too close to the station and be unable to place because the lower Z level was not an allowed location. I suppose a mostly-fix would be to adjust the areas so that there aren't any areas where the upper level allows ruins and the lower doesn't, but in some cases that would significantly shrink the area ruins can spawn in just to accomodate this one ruin.

**Comment by Whoneedspacee** [comment]
Definitely don't leave the issue up to mappers, the ruins themselves should really independently check before placing either.

**Pull request merged**
