### PR TITLE
Changes foam dart descriptions to be more lore friendly

### PR DESCRIPTION
**Pull request by Ryll-Ryll**
## About The Pull Request
The descriptions of the foam darts used in donksoft guns use the slogan of their real life dart blaster counterpart, "It's nerf or nothing". This PR changes that tagline to one that I think is funnier and actually uses the in-universe manufacturer's name: "It's Donk or Don't!"

## Why It's Good For The Game
I don't wanna toot my own horn or nothin', but I think that's a pretty funny line

### CODE REVIEW

**Comment by MrDoomBringer** [comment]
i laughed

**Comment by MrDoomBringer** [comment]
its fucking dont or dont jesus shaps how do you do it

**Comment by wesoda25** [comment]
> its fucking dont or dont jesus shaps how do you do it

In this context, Donk is indicative of doing in the Donk style of things. So the meaning of the statement is intact since it’s “do it this brands way or don’t do it at all”. You really should have known this.

**Comment by cacogen** [comment]
donk or do not there is no nerf

**Review by Mothblocks — APPROVED** [review]
the nerf company personally pm'd me a long cease and desist about this. not sure what it says though i can't read

**Pull request merged**
