### PR TITLE
[WIP] PHOTOGRAPHY UPDATE ATTEMPT 2 - ELECTRIC BOOGALOO - Photo persistence and logging!

### LINKED ISSUE #7092: Photographs don't show janicart nor windows
Photographs do not show whole-tile windows.

They also do not capture the janicart.

They also do not get fire lights.

Nor Plasma.

Fix that shit.

### LINKED ISSUE #11276: Cyborg photo system
As a cyborg, the "view images" button always returns with "No Images saved", rather than the drop down of your pictures, no matter how many photos you have saved.
Printing works normally and gives you a list of the photos you took however.

Unsure if the same issue comes with the AI.

### LINKED ISSUE #23184: Taking photos with cameras is fucky
About 7 times out of 10, if you try to take a photograph of something with a camera, nothing will happen. I have no idea why or what's causing this, but it's on the server right now, so it isn't related to my picture frames PR.

### PR DESCRIPTION
**Pull request by silicons**
https://github.com/tgstation/tgstation/pull/28908 but it'll work when I'm done 
REQUIRES #38098 

//OUTDATED DESCRIPTION BELOW, MOST OF IT IS STILL VALID THOUGH.

- [ ] photo album persistence based on id
- [x] save photos based on round in log folders

Adds support for custom sized photos
Refactor photos and photography to use the datum photo
Tweaks to silicon photo selection to make it useful and better
Cyborgs now sync photos with their ai on lawsync 
Photos are now stored every round for Atlanta Ned to put on his site so we can laugh at embarresing moments
Planned: captain photo album persistence along with others.

Fixes #7092
Fixes #23184
Fixes #11276

:cl: 
rscadd: Cameras now support photos up to 15x15 in size, and independent x/y tile heights!
refactor: Photos and photography in general will use /datum/photo to store photo information, instead of /obj/item/weapon/picture.
tweak: Cyborgs can now print pictures for a cheaper cost.
tweak: Cyborgs now properly sync pictures with the AI and grabs pictures with the AI.
experimental: Photos are now logged by round ID with filenames of their numerical id and a json of their information if the variable is enabled!
MORE TO COME----

### CODE REVIEW

**Comment by ishitbyabullet** [comment]
well, that's one way to stop people from sending nudes.

**Comment by BeeSting12** [comment]
>fails the travis

Typical kevinz PR

**Comment by kevinz000** [comment]
@BeeSting12 
image

**Comment by BeeSting12** [comment]
lmao

**Comment by Mark9013100** [comment]
This won't affect taking photos of the CE's blueprints for the objective right?

**Comment by kevinz000** [comment]
@Mark9013100 it will work as before.

**Comment by Mickyan** [comment]
How's the the album going to work exactly? Same item with instanced contents?

**Comment by improvedname** [comment]
Album will just be full of catgirl nudes

**Comment by kevinz000** [comment]
@Mickyan it saves the location of the json information and actual image of photos put into it sorted by album id
when it's being restored it tries to find both, if it can't the picture is tossed out, if it can (which is most of the time unless we somehow run out of disk space?) the photo is recreated from it perfectly

**Comment by MrDoomBringer** [comment]
There should really be a persistent photo gallery in the Library, for the curator to maintain.

**Comment by DaxDupont** [comment]
Why does this have transit changes in it.

Also make sure sec consoles won't break, or other places like the copier.

That and how are you saving photos? I'd just store them as base64 and render them all with a single html file tbh

**Comment by kevinz000** [comment]
@DaxDupont .png as iirc it's more efficient that way? I dunno I could also do b64
Also transit is because the transit PR is awaiting review and I need the changes in here, whne it's merged I can just rebase

**Comment by DaxDupont** [comment]
Base 64 can store the contents of any file. Containing them in a single
file per round vs 20 different pngs seems preferable

**Comment by msgerbs** [comment]
Will this make other stuff show on the camera that currently doesn't, like items and stuff?

**Comment by kevinz000** [comment]
@msgerbs they should be showing

**Comment by optimumtact** [comment]
flat icon is a hack, photography will never work, repent your sins and demand a byond side solution from the Lummox

**Comment by Shadowflame909** [comment]
now admins wont be able to log lewd pictures muhahaha

**Pull request closed without merging**
