### PR TITLE
Abductor Only Gland-Determination / Mystifies Glands From Non-Abductors

### PR DESCRIPTION
**Pull request by coiax**
:cl: coiax
add: Abductor scientists, or people who have had training similar to an
abductor's scientist will be able to examine alien glands to determine
their scientific purpose.
add: Abductor glands now have their appearances randomized.
/:cl:

the `has_trait` proc on /mob now also checks the mind datum for that trait
by default. I would say that MOST of the time, you expect the traits of the mind
to matter as much as the traits of the body.

No changes to add or remove trait or anything like that.

Had a lot of fun making up dumb sciencey sounding explanations for the
glands.

Removes the "scientist" var from the species datum, don't need that
anymore.

TRAIT_ABDUCTOR_TRAINING and TRAIT_ABDUCTOR_SCIENTIST_TRAINING are the
important key traits here, assigned in the antag datum. Being an
abductor doesn't give you experience with all their tools, after all.

TRAIT_SURGEON (another trait the ayy scientist has) gives you access to
all surgeries, rather than a more snowflake-style species check.

Fun fact: An abductor scientist turned into a medical borg will be able to
access all surgeries.

@XDTM @4dplanner

### CODE REVIEW

**Comment by ExcessiveUseOfCobblestone** [comment]
Alternatively: Randomize the sprites so there's no selective usage of organs, good or bad.

Else you may as well change the name on both the type and the unit that holds them.

**Comment by BeeSting12** [comment]
Will this prevent abductor agents from doing surgeries?

**Comment by Ratvar** [comment]
to davethwave:
I just literally said what you said. But also talked about how examine text will ease it for everyday_players to be shitters, as opening wiki is concept they are not able to grasp entirely.

**Comment by Bawhoppen** [comment]
As was somewhat mentioned already, won't this lead to scientists just putting in the most harmful/beneficial thing into people every time? Having it random allows interesting things to occur, rather than the scientist just following the meta.

An alternative I'd prefer is if it just showed what they did after the experiment was complete and you sent them back to the station. Then the scientist can decide to use that same organ, or try a new one.

**Comment by coiax** [comment]
@BeeSting12 This doesn't change surgery behaviour, only the scientist *should* have been able to begin experimental surgery, according to the code.

**Comment by XDTM** [comment]
Remember that this does not change anything from the status quo since the icons were a tell already.

**Comment by 4dplanner** [comment]
> Remember that this does not change anything from the status quo since the icons were a tell already.

Technically a few glands use the same sprite due to defaulting, I believe

**Comment by ExcessiveUseOfCobblestone** [comment]
Right, either do it proper with naming if you want them to pick and take their preferred gland (which you can expect to get nerfed following) or randomize the icon (preferred option). 

It should be obvious from the getgo or it shouldn't be a tell at all except through observing the response on ~~humans~~ subjects.

**Comment by XDTM** [comment]
Abductors have freedom of choice with which surgeries they want to do on the victim before teleporting it back, brainwashing in particular; why would it be a problem if they got to choose the gland? Especially considering that _they already can_, without apparently causing issues.

**Comment by Ratvar** [comment]
Because it becomes easier for everyday players (point of PR), theoretically letting it become an issue, eh

**Comment by ExcessiveUseOfCobblestone** [comment]
I don't exactly care which decision is chosen since I think we can explore both soundly, all i'm saying is either make it clear which gland you're pulling out before you're even pulling it out, **or** make it completely random as i'm assuming that was the intention.

If you're still having to pull out each gland from the "glandporium" and examine it before you can figure out which glands do which (assuming that's the direction you want to go), this PR does basically nothing as xdtm alluded to.

TO BE CLEAR, idea is fine. Execution, as is, is not.

**Comment by 4dplanner** [comment]
This is a bit of a late response, but I don't think streamlining the process and making it more intuitive for new players is doing "basically nothing".

**Comment by ExcessiveUseOfCobblestone** [comment]
All signs point to it being vague and randomized though except literally the icon (some of them even share the icon), all other aspects of the gland are explicitly made to not be intuitive. If it's going to be changed to be clear in functionality, it needs to be changed properly.

Again, just make it clear which is which **before you have to pull it out of the glandporium**.

**Comment by XDTM** [comment]
It does level the playing field between players who read the wiki/code and those who don't, which seems like an accepted design decision looking at wall decon hints and stuff like that.

**Comment by ExcessiveUseOfCobblestone** [comment]
I actually really like this approach where only ayys can determine the functionality.

I hope the icons get randomized so ONLY ayys can understand the glands in conjunction with this PR and it can't be gamed with code/wiki knowledge. That would be the most immersive imo.

**Comment by 4dplanner** [comment]
randomising icons would be pretty cool

**Comment by coiax** [comment]
@ExcessiveUseOfCobblestone Except I'd say most of the glands self identify within about 5 minutes for the victim, and anyone else watching them. Laying eggs, burping plasma, producing spiders, mentally shocking everyone around them, these are all fairly obvious tells.

The real "gems" as it were are unconditional ventcrawl, the occasional healing gland, and if you care about random reagents: the egg layer.

**Comment by ExcessiveUseOfCobblestone** [comment]
That's not the point of the PR to find out the glands byond the point of return though, you can do that now?

**Comment by coiax** [comment]
Yeah the point of the PR is to make it easier for abductor scientists to identify which gland is which. All of the glands are stored in coloured boxes, and you can always put back a gland if you don't want it.

**Comment by XDTM** [comment]
I do agree with the icon randomization along with the abdcutor-only description, if the patient is awake for some reason they won't see which gland they're gonna get.

**Comment by ExcessiveUseOfCobblestone** [comment]
I think my endgoal which I may more/less be trying to sucker into this PR is I want the colored boxes to indicate which is which but if you can put them back in then it should be fine.

Do add icon randomization tho since that will ensure only ayys can know which gland is which :)

**Comment by coiax** [comment]
Yeah, sure I can do that.

**Comment by ExcessiveUseOfCobblestone** [comment]
darn line endings....

**Comment by davethwave** [comment]
Yay

**Pull request merged**
