### PR TITLE
Buffs tracking beacon EMPs, and makes EMP damage temporarily disable mech equipment

### PR DESCRIPTION
**Pull request by zxaber**
## About The Pull Request

~~- All combat mechs now start with a tracking beacon pre-installed.~~
- Tracking beacons no longer self-destruct when EMPing a mech from the console.
- Tracking beacons now do an EMP_HEAVY instead of an EMP_LIGHT.
- Taking any EMP damage now disables mech equipment/weapons for three seconds (refreshes on further - EMP damage, does not stack). During this time, if the user is in a combat mech, their mouse circle changes from green to red, and an error message from the mech is given to the pilot. At the end of the duration, the mouse swaps back to green and a sound beep is played.

## Why It's Good For The Game
Adds some counter-play against mechs without making them nearly impossible to build. Hostile mechs can, of course, remove the console, but this is an obviously deliberate action, and more consoles can be created by printing the boards from any of the three circuit imprinters. Additionally, the weapons disable time means that fighting one with an ion rifle is a lot less dangerous if you can get a shot in before getting killed.

Non-combat mechs are not automatically beacon'd to allow traitor roboticists a workaround in the form of the Hidden Weapons Bay. They do, however, still temporarily lose use of their equipment when getting ion'd/EMP'd.

## Changelog
:cl:
balance: Utility mechs no longer automatically get beacons.
balance: Tracking beacons no longer delete themselves when EMPing a mech, and instead have a ten-second cooldown in-between EMPs. They also now do heavy EMP damage rather than light.
balance: Mechs that take EMP damage lose the use of their weapons and equipment temporarily. Movement and abilities are not effected.
balance: Mechs taking EMP damage no longer roll for a random malfunction.
/:cl:

I'm not done with mechs yet, I have plans for changing how weapons work (specifically physical projectile weapons). But this is a good starting place, and hopefully makes rogue mechs less of a pain in the ass while not restricting their creation and use against blobs/xenos/whatever.

TO-DO list so I don't forget because I gotta go do something else for a bit:
- [x] Make sure Nukie mechs don't get beacons
- [x] Fix the runtime when you EMP a mech without a pilot
- [x] Add cooldown to beacon EMPs

### CODE REVIEW

**Comment by zxaber** [comment]
PS,
Before this gets merged, I need to make sure that Nuke Ops mechs don't get beacons. It was something I thought about just as I was submitting the PR.

**Comment by wesoda25** [comment]
This might be the PR to make me stop thinking mechs are pure cancer

**Comment by YakumoChen** [comment]
how often can you EMP mechs from the console?

**Comment by Tlaltecuhtli** [comment]
does it mean you can build a console in maint and grief every mech in existence

**Comment by KrabSpider** [comment]
@yakumochen There's no cooldown IIRC

You can also stack multiple tracking beacons. Keep that in mind — unless that got patched out.

**Comment by zxaber** [comment]
@YakumoChen 
Not at the moment, but I've been asked to make a cooldown and I'll probably do that.

@Tlaltecuhtli 
Yes, but you can do the same against borgs. Far as I'm concerned, if it's not an issue for borgs, it's not an issue for humans (especially because humans can just hop out at anytime).

**Comment by Arathianen** [comment]
Good PR, with a caviat.

There needs to actually be a way to remove/disable beacon. That way mechs won't suddenly be 100% useless for traitors

**Comment by Tlaltecuhtli** [comment]
you cant blow up borgs as not antag but mechs are fine

**Comment by zxaber** [comment]
You could repeatedly lock down borgs, and no one could stop you if they can't find the console.

**Comment by FloranOtten** [comment]
This needs a way to remove the beacon. Without a beacon using mechs will become cancer, nonantag or no. Sec already gets overly trigger happy with the ions when they see a mech. I use mechs often as a traitor. They really aren't hard to counter. I don't think adding a magical DEAD button to the mechs will improve anything.

**Comment by FloranOtten** [comment]
Additionally, EMPs disabling mech equipment is SUCH cancer. I will never use a mech, then. You can spam ion rifle shots, so you'd be stuck without any way to fight ions. Walking gets fucked too from ions.

To recap; A mech that gets in range of a guy with an ion rifle can no longer flee, it can no longer fight, it can only sit there uselessly. Bad enough for nonantags with trigger-happy sec, worse for traitors, disastrous for nukies. Imagine a mauler stuck in place taking ion shots because you can't do jack shit in a mech anymore.

**Comment by zxaber** [comment]
Here's the dealio;

If I allow people to remove beacons, I might as well not even have this PR. The whole problem with beacons is that no one in their right mind is going to willingly add a beacon to their own mech. So allowing people to just remove them makes them, at best, useful against unseasoned roboticists.

The EMPs disabling mech equipment is the only other part of this PR that does anything. This PR makes them disable a mechs equipment, but not necessarily the movement. I'm toying with the idea of removing the randomized negative effects from EMP damage (they'd still have their same chance from other damage types).

We _just_ had a PR attempt to lock combat mechs behind security, so that no one gets them unless you break into the brig or somehow get on Sec's good side. Oranges is talking about locking them behind RD access as it is. Mech play and strategies as they currently exist are unlikely to stay, and I'm trying to add counters to mechs that don't entail locking them away from us peasants.

**Comment by 4dplanner** [comment]
Nukie mechs should probably not be disabled by EMPs, maybe give them "emp hardening"?

**Comment by FloranOtten** [comment]
I am more in favor of locking mechs behind things like Sec access or making RD the only one over this. Yeah it only disables the weapons but EMPs in general fuck over movement. This is already locking mechs behind Sec because Sec already shoots ions at anything that moves, and now those ions are 'click here to kill' buttons

**Comment by zxaber** [comment]
Update:

- Mech weapons disabling on EMP damage is now 3 seconds instead of 5.
- Mech taking random malfunctions from EMP is commented out and may be removed (damage from other sources can still cause random malfunctions).
- Beacons are still auto-placed in combat mechs, but now are placed when you complete the final step. Thus, Nukie mechs and admin-spawned mechs _shouldn't_ have beacons.
- Beacon EMPs now have a cooldown of 10 seconds in-between uses. 
- Apparently the Ripley-class of mechs, and the Odysseus, had beacons auto-added, and I'm not sure anyone knew. These have been removed, since the theme I'm going for is that the weapons targeting board has the beacon on it. I'm not super against _all_ mechs having a beacon, I suppose, but it seems unnecessary for utility mechs to be on the tracker by default.
- Fixed the runtimes I mentioned earlier
- Removed the tracking beacon hud icon from being on every mech ever (even if no tracking beacon existed.

These changes have generated some strong opinions on both side, so it might be best if we could test-merge to see what the effects turn out to be.

**Comment by Tlaltecuhtli** [comment]
midway is to improve how the beacons work but not make the mechs start with beacons, so RD/sec can put them on robo mechs or assistants can play tag with a rogue triple rocket gygax

**Comment by zxaber** [comment]
Maybe. I'll sleep on it, and see if anyone else wants to voice their opinion. The EMP changes might be enough to help security take on a rogue mech without a beacon.

**Comment by DaxDupont** [comment]
I'd make the cool down to at least 2+ minutes.

Main issue against this PR is that it's a game over button in a few presses, a longer delay will allow some time instead of death in under a minute

**Comment by GuyonBroadway** [comment]
Once every 40ish seconds but increase the disable amount. That way if the HoS coordinates with the RD or AI or whatever they can call for someone to buzz the mech while they open fire then run away before it boots back up.

**Comment by GuyonBroadway** [comment]
And also the pilot has time between buzzes to fight back.

**Comment by Eaglendia** [comment]
The changes to all of these effects are really good, imo, re: balancing combat exosuits. However, I think it's easy enough for a player to just run by and slap an exosuit beacon on a mech (it doesn't take any time to put them on or anything) that it's not really necessary to include them by default, right?

The buff to their effects will make it worthwhile for an RD to keep an eye out for mech construction and beacon them when they come up if necessary. Were it really a matter of concern you could have the mech send a radio message over the science channel when it's initialized.

**Comment by FloranOtten** [comment]
>And also the pilot has time between buzzes to fight back.

See, no, he doesn't. Because the HoS can just spam fire his ion rifle and the mech can do fuckall against it.

**Comment by zxaber** [comment]
@DaxDupont 
>I'd make the cool down to at least 2+ minutes.

>Main issue against this PR is that it's a game over button in a few presses, a longer delay will allow some time instead of death in under a minute

It's currently at three seconds for loss of weapons, and ten seconds before the next pulse. Again, you're able to freely move during this time, so nothing is stopping you from using your 70% weapons uptime to flatten whoever is in the RD's office.

I think people are way overestimating how much damage EMPs do to mechs, to be honest. You can't ignore it, sure, but it's not like two or three button presses to kill the mech.

@Eaglendia 
>The changes to all of these effects are really good, imo, re: balancing combat exosuits. However, I think it's easy enough for a player to just run by and slap an exosuit beacon on a mech (it doesn't take any time to put them on or anything) that it's not really necessary to include them by default, right?

Yeah, beacons are weird. If I was designing them myself, I'd have made the mech at least require being empty. It feels like they're sorta ducktaped to the back or something when you can slap them into a piloted mech like it's nothing.

>The buff to their effects will make it worthwhile for an RD to keep an eye out for mech construction and beacon them when they come up if necessary. Were it really a matter of concern you could have the mech send a radio message over the science channel when it's initialized.

The point of my concern (and I suppose others) isn't so much that combat mechs get created. It's just that once they go loud and Security has found out that the mech is rogue, they should have tools to deal with it. Proper ones, rather than the tickle beam ion rifle that they currently have.

**Comment by FloranOtten** [comment]
>The point of my concern (and I suppose others) isn't so much that combat mechs get created. It's just that once they go loud and Security has found out that the mech is rogue, they should have tools to deal with it. Proper ones, rather than the tickle beam ion rifle that they currently have.

Valid concern and noble interest. I just don't think that the tools sec has to deal with them should be such a hard counter the thing it was designed against becomes obsolete. Instead of disabling via EMP, how about lengthening the buzz to 15 seconds or something long, but make it only apply via the beacon. And lengthen the cool down to 1 minute. This would mean mechs are a mean threat but someone with access to a console (like the RD, wouldn't mind more consoles being placed) can team up with someone fighting the mech in order to give 15 second windows for damage to occur.

**Comment by dr-bee** [comment]
Wouldnt it be better to tie the beacons to the weapons and not the mech? this gives a clear disadvantage to shoving every weapon on a combat mech and makes the defense equipment more appealing.

**Comment by Arathianen** [comment]
To be honest, I think if the main issue is control, it would make more sense to have the weapons module be printed in the security autolathe then.

**Comment by necromanceranne** [comment]
If you are ballsy enough you could use a beaker of iron and uranium and pour a few units of each at a time into a separate third beaker just a short distance away from the mech to keep its equipment down.

Also ions completely obliterate mechs. Which is good. They've had no counter that wasn't explosive since forever. And single emps have been a complete joke and the ion was more or less just a laser rifle but actually capable of hurting the mech.

There is however still one major drawback to all this. One mech in particular doesn't give a flying fuck about equipment. The gygax. I feel it's time the Gygax got a rework if this PR goes through so that the actual best mech strategy, the Actuator setup, doesn't become just the default for mechanized violence.

**Comment by wesoda25** [comment]
You shouldn't be able to remove a beacon, but maybe you can emag a beacon before installing it in a mech to make it "faulty" and fail after like 5 pulses. 

But beyond that just dismantle the computer before you go be a cunt in your unrobust, riskless power armor.

**Comment by datorangebottle** [comment]
> But beyond that just dismantle the computer before you go be a cunt in your unrobust, riskless power armor.

I mean, this is just going to be the meta. Robotics is literally right down the hallway. They can stomp into the RD's office, blow open the door, and take out the console in a matter of literal seconds.

Thus, I think that 3/4ths of this PR will have no real effect on the game whatsoever, since it's usually roboticists who are doing the mech stompy bullshit- or worse, the RD- and they can just take out the console within literal seconds of making and equipping the mech.

I've always felt that a more drastic solution was needed- heavy EMPs like the tracking beacon is going to be should straight dump the operator on the floor. Or, make it take away about 25% max battery out of their current battery level. [or just have a good chance of outright fucking the battery up permanently]

Alternatively, just remove combat mechs. They add nothing of value to the game and cause a ton of other problems, beyond just being a balancing nightmare.

**Comment by zxaber** [comment]
@dr-bee
>Wouldnt it be better to tie the beacons to the weapons and not the mech? this gives a clear disadvantage to shoving every weapon on a combat mech and makes the defense equipment more appealing.

It wouldn't really change much; now that beacons don't delete themselves when EMP pulsing, there's no real difference to having three beacons over one beacon. The only thing that would actually be different would be that weapons bays on utility mechs would also get a beacon, which is something I wanted to avoid.

@Arathianen 
>To be honest, I think if the main issue is control, it would make more sense to have the weapons module be printed in the security autolathe then.

I really dislike the idea of locking robotics content behind security. Robotics doesn't answer to sec, they answer to the RD. Security has a reason to have anti-mech capabilities, but Robotics shouldn't be having to get authorization from them to build things, even dangerous things.

@wesoda25 
>You shouldn't be able to remove a beacon, but maybe you can emag a beacon before installing it in a mech to make it "faulty" and fail after like 5 pulses

Currently, the beacon is just auto-placed when you complete the last weld on a mech. I suppose I could allow emagging the weapon targeting boards, but I'm not sure if I like undermining beacons like that. Even if I decide to remove auto-beacons, I like the changes I've done to them to make them not useless.

@datorangebottle
>Thus, I think that 3/4ths of this PR will have no real effect on the game whatsoever, since it's usually roboticists who are doing the mech stompy bullshit- or worse, the RD- and they can just take out the console within literal seconds of making and equipping the mech.

With this PR, combat mechs get the same downside borgs get with a remote console. Breaking the console is (or at least, should be) an obvious tell, in the same way that watching a borg decon the borg console pretty much tips everyone off that the borgs are probably rogue. Anyway, more console boards can be built from circuit imprinters, and I'm almost certain that a spare board in tech storage, in case a mech breaks the console before smashing up the place.

>Alternatively, just remove combat mechs. They add nothing of value to the game and cause a ton of other problems, beyond just being a balancing nightmare.

See? This right here is what I'm trying to avoid.

**Comment by datorangebottle** [comment]
> With this PR, combat mechs get the same downside borgs get with a remote console. Breaking the console is (or at least, should be) an obvious tell, in the same way that watching a borg decon the borg console pretty much tips everyone off that the borgs are probably rogue. Anyway, more console boards can be built from circuit imprinters, and I'm almost certain that a spare board in tech storage, in case a mech breaks the console before smashing up the place.

These tells aren't always noticed, and not everybody can see them.

> See? This right here is what I'm trying to avoid.

I'm not sure why you are. Again, what do they add to the game that they should be kept? Yet Another Way of Killing The Entire Station?

**Comment by Angustmeta** [comment]
They don't need to spawn with this beacon imo. The other changes are heavy enough nerfs already. Probably even too heavy with EMP disabling weapons 10 full seconds. 5 os enpugh so the can actually try to do something about it. 

Managing to place a beacon on an enemy mech mid fight is fun and should not be taken away. Don't know how long it takes to place one, but having it be a somewhat fast action seems sensible.

**Comment by zxaber** [comment]
@datorangebottle
>I'm not sure why you are. Again, what do they add to the game that they should be kept? Yet Another Way of Killing The Entire Station?

They're useful against non-human antags (blob, xenos, even pirates). They're also something to do when you're out ghosts to take positronics and all the borgs are upgraded.

@Angustmeta
>They don't need to spawn with this beacon imo. The other changes are heavy enough nerfs already. Probably even too heavy with EMP disabling weapons 10 full seconds. 5 os enpugh so the can actually try to do something about it.

You're misreading. It's a 3 second weapons disable from any EMP damage source. The beacons themselves have a 10-second cooldown between pulses.

>Managing to place a beacon on an enemy mech mid fight is fun and should not be taken away. Don't know how long it takes to place one, but having it be a somewhat fast action seems sensible.

It's actually instant, even if there's a pilot. Not even a timer bar. I'm on the fence about removing the auto-beacons, since the EMP changes might be enough, and the buffed beacons _can_ be slapped onto a mech at any moment.

**Comment by Arathianen** [comment]
"Yet Another Way of Killing The Entire Station?"

I can't believe I gotta say this, but YES, more variety in ways to kill is inherently a good thing when it doesn't have obvious downsides.

This isn't call of duty. There are supposed to be more things than guns. I keep memeing about it, but there is a legit attitude that if you try to murder the station with anything more than a stunbaton and a cakehat you are "unrobust" and "doing it wrong".

Fuck that attitude.

**Comment by ATH1909** [comment]
> If I allow people to remove beacons, I might as well not even have this PR. The whole problem with beacons is that no one in their right mind is going to willingly add a beacon to their own mech. So allowing people to just remove them makes them, at best, useful against unseasoned roboticists.

Ah, but it WOULD make a difference: It'd make making a mech WITH a tracking beacon take less effort and time than making a mech WITHOUT a tracking beacon. Realistically, I suspect that most roboticists will only remove tracking beacons from their own mechs, and let them remain in the mechs that they make for other people (why put in effort to make it harder for you to stop someone who's misusing the mech that you gave them?), and I think that that would be enough.

**Comment by Angustmeta** [comment]
I indeed misread. Sounds good with 3s.

**Comment by datorangebottle** [comment]
> They're useful against non-human antags (blob, xenos, even pirates). They're also something to do when you're out ghosts to take positronics and all the borgs are upgraded.

You say that, but the mech is only fair against Blobs and other mechs- and the latter of which is only an actual engaging fight if neither of the mechs have their most broken and busted weapon that they have no reason not to have.

>literally everything Arathianen just said

That's gonna be a yikes from me, bro. Mechs are almost brainless in how they kill people currently, the only one having to put in actual effort is the person fighting against the mech. This PR aims to fix that, but likely won't. Mechs are impossible to balance around the rest of the game because of their nature as a second body with better guns, and nerfing them sufficiently makes them not feel powerful enough for their name.

Speaking of nerfing things sufficiently, Zxaber, how would you feel about the 3s disabling time be the mech with the most advanced parts, and having it go up to 10s- or more- for weaker parts? I believe there's already some sort of similar system with mechs being hardened against EMPs with better scanning modules, but don't remember.

> Ah, but it WOULD make a difference: It'd make making a mech WITH a tracking beacon take less effort and time than making a mech WITHOUT a tracking beacon. Realistically, I suspect that most roboticists will only remove tracking beacons from their own mechs, and let them remain in the mechs that they make for other people (why put in effort to make it harder for you to stop someone who's misusing the mech that you gave them?), and I think that that would be enough.

There isn't an argument here. "Yeah, lemme put this thing in, then allow people to completely remove it, therefore negating 3/4ths of the PR." I'd like to think your opinion of Zxaber is higher than that.

**Comment by zxaber** [comment]
I wanted the weapons disable time to be consistant across the board, so that sec players can get used to how many regular rounds the can fire before having to EmP again. Since there's no current way to know what parts a mech was built with, having the disable time change with parts might as well be random from the sec's viewpoint.

**Comment by necromanceranne** [comment]
You'll also almost always use the best parts anyway since in between getting mech tech and mining tech, you'd get parts to make sure your mineral usage is efficient.

**Comment by YakumoChen** [comment]
The whole argument whining about EMPs being better against mechs is almost laughable anyway. There's only one gun on the station even capable of EMPing in the first place. Ion guns are printable but that requires the research, and there's no guarantee it will be done (it's not required to get the tech to make any mech unless you want disablers on your mech). The consoles can be built to counter it, but rogue mech pilots aren't likely to encounter that sort of thing happening very often. """Winning""" against security at a that point is just a matter of barging into the armoury, taking the exactly one "mech counter" gun, and then bowling over the secfab or just murdering security.

Mechs do need stronger counters though like this PR because mechs are cancer to fight, almost as cancerous as the non-antags that build them and grief (which is about half the time the reason to fight a mech)

**Comment by Tlaltecuhtli** [comment]
security rpg 7 time

**Comment by FloranOtten** [comment]
I get that fighting mechs is cancer. Does that mean you should strip out half its functionality? If the SM was getting delammed every round in a method that's cancer to fight, do you add a button to space it?

>There's only one gun on the station even capable of EMPing in the first place. Ion guns are printable but that requires the research, and there's no guarantee it will be done.

If you have a combat mech, ion carbines are 2500 points away. I see sec carry them often enough.

>Mechs do need stronger counters though like this PR because mechs are cancer to fight, almost as cancerous as the non-antags that build them and grief (which is about half the time the reason to fight a mech)

They need strong counters, yes, but this is too much. This actively prevents you from using mechs to fight anyone unless you take out the seclathe and space the ion gun. Being stunned is cancer, because you can kill a mech within those ion shots. Durands are fucked, 'cause you can't run. Fun for gygaxes, which can actuate outta there but combine the EMP drain and the power draw for fun shenanigans.

**Comment by zxaber** [comment]
I don't really think mechs should be so powerful that you need not fear security.

If Durands in particular feel too weak after this change, I can always give them a buff. I've been wanting to make their ability more useful, and perhaps some EMP protection while it's active could help out.

**Comment by Dawson1917** [comment]
How will this affect malf and combat software AIs who take control of a mech? They're already made permanently dead if they die in the mech, adding automatic EMP beacons and buffing them could make the ability even worse than it already is. Maybe have the beacon automatically fried on a malf/combat AI taking control of a mech, since they'd logically be able to hack it.
Also yes please buff durands, they pale in comparison to gygaxes.

**Comment by FloranOtten** [comment]
>I don't really think mechs should be so powerful that you need not fear security.

I don't think they should be so weak that security should not fear it. This makes fighting mechs trivial. One guy spams ions the other guy shoots with guns, easy.

**Comment by zxaber** [comment]
Allowing a Malf AI to destroy the beacon isn't a terrible idea, but I'm hesitant to break the otherwise consistency we have going here. Anyway, to be honest, AI's have the easiest time denying access to a mech console (they've already been dealing with this in the form of the borg console), so I don't think it'll be too much unless the AI and its borgs completely ignore it.

In any case, I'd like to see how things play out with what we have before tweaking anything. Assuming I can get a test merge, I'll throw up a thread on the forums for feedback about the changes and we can go from there.

**Comment by Dorsisdwarf** [comment]
personally I dont think the beacon should be auto-added.

Mostly because this overrules my epic gamer strat of having one person man the console while a second person chases the mech with a backpack full of beacons, emping the mech over and over

**Comment by Daxxed** [comment]
Mechs have been the cause of many escalations and bans.
Being impossible to stop without lethals is bad, this change might be a bit brutal though.

**Comment by GuyonBroadway** [comment]
If a little shit whacks my hard built durand with a toolbox they are getting  warning.

Then a shove of encouragement.

And then it's a 1 way express ticket to fistfuck city.

**Comment by FloranOtten** [comment]
> Mechs have been the cause of many escalations and bans.
> Being impossible to stop without lethals is bad, this change might be a bit brutal though.

It's too brutal. I think there should be a hard counter but not a brick wall counter.

**Comment by Tlaltecuhtli** [comment]
plastic flaps

**Comment by zxaber** [comment]
After mulling over it for a bit, I've removed the auto-beacon part. EMP changes remain (unable to fire for 3 seconds), and the beacons are still buffed in general. Popping a beacon onto a mech doesn't require the mech to be empty and is instantaneous, so in a pinch you should be able to get one onto a mech that's causing issues (or might in the future). I think I'm gonna lower the Beacon's EMP cooldown to 5 seconds, though, since they're no longer auto-added.

I'm also planning on tweaking (and/or nerfing) a lot of mech weapons in the very near future, which will affect balance, so the auto-beacon may not be necessary at all.

**Comment by GuyonBroadway** [comment]
Idea: make it so you can literally throw a beacon at a mech to cause it to stick but also make it possible to remove with some effort. Like getting out and applying wirecutters for 20 seconds. This way beacons are an ever looming threat and thier counterplay forces you to fall back a while.

**Comment by FloranOtten** [comment]
Why even use the beacon, though? You can just keep the mech chainstunned with an ion rifle.

**Comment by Tlaltecuhtli** [comment]
@zxaber remember that rocket launcher was locked behind deconning 2 combat shotguns before techwebs(tm) happened

**Comment by zxaber** [comment]
@GuyonBroadway 
I dunno about throwing beacons. It's already easy enough to rush up to a mech and melee it, especially if you wait until it's turned around.

@FloranOtten 
Beacons are useful as a secondary method to fight mechs. Additionally, now that they don't break when you EMP-pulse a mech, people might actually start using them again on mechs they give away.

@Tlaltecuhtli 
That was before my time. Anyway, I have an upcoming mech ballistics PR that will affect the sustainability of missile use more than other weapons, and possibly a straight-up missile rework at some point.

**Comment by YakumoChen** [comment]
>I get that fighting mechs is cancer. Does that mean you should strip out half its functionality? If the SM was getting delammed every round in a method that's cancer to fight, do you add a button to space it?

I can't tell you how many times a mech has entered my FoV and I was dead within a minute because it fired the Instant Win Missile or just ran up to me and punched me to death because it was a Gygax.
Half the time it's a traitor that is going to proceed to bowl over security and is unfightable, because mechs have a massive health pool and their main weaknesses are very limited in accessibility, and the meta strats involve one-hit _sleeps_ which are even more deadly then stuns. 
The other half is because a roboticist went rogue because I saw they built a joyride mech with missiles and I told them to get the fuck out of it because I am paranoid of the first half of people, and they use that excuse to proceed to bowl over security and become unfightable because they think joyriding a deathmobile allows them to self-antag.

>If you have a combat mech, ion carbines are 2500 points away. I see sec carry them often enough.

Security doesn't have access to RnD most of the time, and that doesn't help when the mech is already in your brig destroying it and everyone in it.

>Being stunned is cancer, because you can kill a mech within those ion shots. Durands are fucked, 'cause you can't run. Fun for gygaxes, which can actuate outta there but combine the EMP drain and the power draw for fun shenanigans.
It's not even a stun. You can still move while ion'd. Gygaxes (which are the meta deathmech anyway) doesn't even need to give a shit, they can just bowl over the guy with the gun and punch him.

**Comment by FloranOtten** [comment]
>I can't tell you how many times a mech has entered my FoV and I was dead within a minute because it fired the Instant Win Missile or just ran up to me and punched me to death because it was a Gygax.
Half the time it's a traitor that is going to proceed to bowl over security and is unfightable, because mechs have a massive health pool and their main weaknesses are very limited in accessibility, and the meta strats involve one-hit sleeps which are even more deadly then stuns.
The other half is because a roboticist went rogue because I saw they built a joyride mech with missiles and I told them to get the fuck out of it because I am paranoid of the first half of people, and they use that excuse to proceed to bowl over security and become unfightable because they think joyriding a deathmobile allows them to self-antag.

Again, yeah, it's cancer to fight right now. But let's not jump the gun on just deleting the traitor functionality. IMO we should just delete the fucking missile rack, or lock it behind some majorly heavy legwork. 

>It's not even a stun. You can still move while ion'd. Gygaxes (which are the meta deathmech anyway) doesn't even need to give a shit, they can just bowl over the guy with the gun and punch him.

I was talking about Durands. Gygaxes need their own set of nerfs.

**Comment by necromanceranne** [comment]
Finally, a good fucking mech rebalance.

**Comment by FloranOtten** [comment]
God damnit.

**Comment by terranaut1** [comment]
Will getting EMP'd make a mech walk uncontrollably in random directions for fifty fucking years still or is that getting removed as a rebalance? It says "movement is not affected" so I hope you removed it and don't just mean "I didn't do anything to movement".

**Comment by zxaber** [comment]
All random malfunctions, including the uncontrollable walking, no longer have a chance to happen from EMP damage. They can still occur from other damage types.

**Pull request merged**
