### PR TITLE
Capitalize medbay machine names

### PR DESCRIPTION
**Pull request by Apogate**
they make announcements in the medic channel and every time EVERY TIME i see these shitty uncapitalized labels i yell

### CODE REVIEW

**Comment by Bawhoppen** [comment]
welcome to the repo

**Comment by coiax** [comment]
Objects should not have capital letters.

**Comment by ChangelingRain** [comment]
Objects absolutely should not have capital letters; there's probably another solution to this but it might be outside of your coding reach, at least depending on what solution it is.

**Comment by Militaires** [comment]
non-capital everythings are like a trademark of spessmen stop

**Comment by Apogate** [comment]
s-sorry

**Comment by coiax** [comment]
Welcome to tgstation. Don't worry, my first PR, everyone jumped at me, and I'm still here.

**Pull request closed without merging**
