### PR TITLE
Remove lodash vuln

### PR DESCRIPTION
**Pull request by Cyberboss**
GitHub ping

### CODE REVIEW

**Comment by optimumtact** [comment]
are we not using it?

**Comment by Cyberboss** [comment]
🤷‍♂️

**Comment by SpaceManiac** [comment]
tgui -> babel-core 6.26.3 -> lodash ^4.17.4

**Comment by Cyprex** [comment]
Consider leaving a comment so this dependency can be removed once babel-core updates their dependency.

**Comment by Cyberboss** [comment]
>implying we can ever update because ie8

_laughs in mso_

**Comment by nicbn** [comment]
One cannot even put comments in json

**Pull request merged**
