### PR TITLE
Shotguns blow people away at point blank

### PR DESCRIPTION
**Pull request by Ryll-Ryll**
## About The Pull Request
Shotguns now send their target flying backwards when fired point blank (clicking directly on their sprite while next to them, clicking behind them doesn't count). Most shotguns have 2 tiles of knockback, while double-barreled shotguns have 3 tiles (it's a super shotgun!)

The variable controlling this, pb_knockback, was added at the gun/ level, so it can be enabled on other guns as well.

## Why It's Good For The Game
This gives shotguns a bit more flavor and sets them apart from other weapons, giving them more versatility in close range encounters like maint tunnels and crowded cult base raids. If used smartly, you could knock people over into walls to disarm them or into other people to get a short stun. However, you're also knocking them away from you, which can make your follow-up shots harder, or you might knock them into a friendly. Emergent gameplay!

also blowing people away with shotguns is funny and very john woo

## Changelog
:cl: Ryll/Shaps
tweak: Shotguns now knock people backwards when fired directly on someone at point blank
/:cl:

### CODE REVIEW

**Comment by necromanceranne** [comment]
Does this include sawn-off improvised shotguns? I have concerns about those becoming stun weapons because of their concealability and ease of production. Nothing stops you making a followup shot if you slam them into a wall. And they're a child of the double-barreled shotgun too.

**Comment by Shapsy** [comment]
Yeah, those get the bonus knockback. I've never really seen people actually used improvised shotguns, and I'm not sure how much of a concern follow up shots would be for it since it's a single shot weapon isn't it? May as well remove the bonus anyway since that was just based on the double barrel aesthetic

Keep in mind that there's no stun for hitting a wall or person I'm pretty sure, just a knockdown. I can double check later, but I think the paralyzes for shoving are handled in the shove itself, not the collision?

**Comment by necromanceranne** [comment]
It's with the force of collision. It's why baseball bats are pseudo-stun weapons. Shoves are a bit different and all the stuff around shoves is exclusive to shoves. To get a feel of what it might be like, try out the power fist on it's lowest setting, I'm pretty sure that's a knock back of about two tiles.

I used to use sawn-off improvised shotguns with rubber shot as my point blank stun tool before rubber shot nerfed. If it became a poor man's power fist, I can see myself using them again for the same reason.

I just largely wanted to call your attention to the possibilities, not whether I want to make a statement about balance of the change overall.

**Comment by Pugie** [comment]
FLASHLIGHT!

**Comment by VileBeggar** [comment]
i'm surprised it took this long for someone to code it in since it was always a neat idea

**Comment by Fhaxaris** [comment]
Does shooting someone into a wall do damage, like with the baseball bat?

**Comment by MCterra10** [comment]
How it feels to play pyro

**Comment by TheVekter** [comment]
Ohhhh, this is fucking _aces_. Very cool. Worth noting that this is a stealth nerf though to combat shotguns, as double/triple tapping someone is a lot harder with this. Not that I'm complaining.

**Comment by AdamElTablawy** [comment]
Yeah, wall shots/hitting someone else will stun.

**Comment by Shadowflame909** [comment]
Are you saying that dressed up as Abraham Lincoln: 
>I can pop out of my grave
>And take an combat shotgun out from under my hat
>Blow Batman away with a rat-a-tat-tat

**Comment by actioninja** [comment]
being thrown into a wall stunning is a problem with that mechanic imo.

**Pull request merged**
