### PR TITLE
Gives tagger the art component

### PR DESCRIPTION
**Pull request by nemvar**
## About The Pull Request

Stuff drawn by people with the tagger quirk now has the art component.

## Why It's Good For The Game

Why the fuck not.

## Changelog
:cl:
tweak: The drawings from taggers (quirk) now give good moodlets on examine.
/:cl:

### CODE REVIEW

**Comment by Mickyan** [comment]
Nobody uses crayons for art because it messes the colors of the tiles and takes forever to draw anything

If you want to fix this properly give them a different spraycan that doesn't stun

**Comment by nemvar** [comment]
Crayons recoloring the entire turf was silly and didn't even make sense. If anything, removing that is the proper fix.

**Comment by Dawson1917** [comment]
>roundstart instantstun
Spraycans don't work as stuns on the majority of people because any gas mask, sec mask, or hardsuit helmet blocks it, there's only three uses per can, the stun is really fucking short and not useful unless you have a stunbaton to pull out in your bag and if that's the case, why even use a spraycan. And, you can PRINT spraycans at lathe if you're so adamant on using an unreliable shit stun instead of fetching wirecutters and getting a roundstart flash from the hopline or gulag shuttle like a gentleman gamer. So this PR doesn't fix this non-existent issue.

Crayons colouring turfs had its own use and differentiated it from spraycans, but whatever, changing that isn't a biggie. Making people with this quirk spawn with a crayon box instead of a spraycan, however, is extraordinarily pointless.
If you think spraycans having a 2-second stun limited to people who have no face coverage is a huge problem in need of attention, nerf that rather than arbitrarily removing a flavour item from people with the quirk while leaving it mass-produceable in autolathes.

**Comment by nemvar** [comment]
Does any of that change the fact that this quirk is literally only picked for the spraycan stun right now? Access restrictions are a real thing, even for something like a spraycan. The real problem with the spraycan is that you get it before most people get their protection against it, so the stun suddenly has a lot more value. Any kind of stun can easily get chained if you are creative enough, for example with a firelock.

Why do we have this kind of stuff on a quirk? That's the real question here. That's like making a quirk that gives people a roundstart kitchen knife. Sure, it's probably not overpowered, but it goes against the design principle of quirks to not be combat related.

Spraycan having a stun is fine. But it's not fine that you get it without any player involvement.

You also quoted me wrong.

>And, you can PRINT spraycans at lathe if you're so adamant on using an unreliable shit stun instead of fetching wirecutters and getting a roundstart flash from the hopline or gulag shuttle like a gentleman gamer. So this PR doesn't fix this non-existent issue.

This is literally not comparable. Both cases are not ROUNDSTART. You literally don't spawn with them. You have to go through normal gameplay to get what you want, like it fucking should be.

This PR fixes the issue that a quirk is barely picked for its stated reason (art) but instead mostly for something else. This doesn't fix a balance problem, it fixes a problem with design.

**Comment by Mickyan** [comment]
how lazy do you have to be to argue against taking 30 seconds to make a spraycan subtype instead of making the whole quirk worthless

whatever it's more effort arguing about it than just doing it myself later

**Comment by nemvar** [comment]
If the only value you get from a quirk is the roundstart item, the quirk has failed at a design level.

**Comment by Mickyan** [comment]
Not really but feel free to change it in a way that doesn't just make it worse if you're that good

**Comment by nemvar** [comment]
Are you physically incapable of making an argument? If so, I will just stop responding to you.

Because you are the one that started with insults and offtopic remarks. The only thing of value that came from your keyboard was that crayons recolor the turf, other than that you might aswell be trolling.

**Comment by Mickyan** [comment]
lol you came on discord ranting and calling me a snowflake for overlooking something so minor that it had never been brought up, not once, for nearly an entire year

yeah there's a reason why I'm not trying my hardest to be nice

**Review by SpaceManiac — APPROVED** [review]

**Comment by ATH1909** [comment]
> > roundstart instantstun
> 
> Spraycans don't work as stuns on the majority of people because any gas mask, sec mask, or hardsuit helmet blocks it

I think you're thinking of droppers; IIRC, spray cans actually check for the same things that flashes do (on carbons; they can't stun borgs, sadly).

**Comment by Dawson1917** [comment]
> 
> 
> > > roundstart instantstun
> > 
> > 
> > Spraycans don't work as stuns on the majority of people because any gas mask, sec mask, or hardsuit helmet blocks it
> 
> I think you're thinking of droppers; IIRC, spray cans actually check for the same things that flashes do (on carbons; they can't stun borgs, sadly).

All kinds of gas masks and hardsuit helmets block the stun from spraycans

**Comment by Dawson1917** [comment]
> 
> 
> Does any of that change the fact that this quirk is literally only picked for the spraycan stun right now? Access restrictions are a real thing, even for something like a spraycan. The real problem with the spraycan is that you get it before most people get their protection against it, so the stun suddenly has a lot more value. Any kind of stun can easily get chained if you are creative enough, for example with a firelock.
> 
> Why do we have this kind of stuff on a quirk? That's the real question here. That's like making a quirk that gives people a roundstart kitchen knife. Sure, it's probably not overpowered, but it goes against the design principle of quirks to not be combat related.
> 
> Spraycan having a stun is fine. But it's not fine that you get it without any player involvement.
> 
> You also quoted me wrong.
> 
> > And, you can PRINT spraycans at lathe if you're so adamant on using an unreliable shit stun instead of fetching wirecutters and getting a roundstart flash from the hopline or gulag shuttle like a gentleman gamer. So this PR doesn't fix this non-existent issue.
> 
> This is literally not comparable. Both cases are not ROUNDSTART. You literally don't spawn with them. You have to go through normal gameplay to get what you want, like it fucking should be.
> 
> This PR fixes the issue that a quirk is barely picked for its stated reason (art) but instead mostly for something else. This doesn't fix a balance problem, it fixes a problem with design.

This quirk isn't taken for the sake of getting an utterly shit, 3-use, easily blockable stun that is worse than _shoving_ 10 seconds sooner than rushing to cargo to grab a can. Or using wirecutters on a wall-mounted flash for a proper stun tool. I have legitimately never seen anyone even use these things for stuns outside of Respii and it's never for combat. I take the quirk so I can colour my clothes or spraypaint people's windows and mechs, not for a putridly bad stun. This PR doesn't address the problem, because the stun is still there. Remove it from spraycans if you think it's a problem, despite it very clearly being a non-issue. If you believe people are going to go on a killing spree in less than 30 seconds into the shift because they spawned with a _spraycan_ then you're very wrong.

**Comment by Alek2ander** [comment]
> What a thought-provoking piece of art. I'll remember that for a while.

-- The Janitor, looking at graffiti

**Comment by nemvar** [comment]
@Dawson1917 Sorry, I can't take you serious if you think a spraycan stun is worse than shoving. Any kind of hardstun is better than a shove, no matter how short, simply because it is easier to chain. Spraycan stuns give you enough time to table/firelock crush someone. Shoving doesn't do that.

Also, your entire accessibility argument is flawed, there's nothing in there that I couldn't throw back at your head. The difference between having to rush cargo/disassemble a flash and not having to do that shouldn't be understated because that's a good 40 seconds of the most important impactful time in the round.

And, as I said before, making balance decisions because someone added a spraycan to a roundstart quirk without thinking about the consequences is utterly backwards. Having spraycan stuns in the game is fine. There is nothing wrong with having decent options for ghetto weaponry, but there is something wrong with being gifted said weaponry at roundstart due to a system that isn't supposed to be combat related.

**Comment by Dawson1917** [comment]
I can't take you seriously if you think a three-use, 2-second stun limited to people with no facial coverage is more powerful than a 4-second stun applicable to _any_ humanoid. Both can be available roundstart. The difference is the more powerful one is free and available to everyone whereas the weak option which comes with non-combat uses costs a quirk point. You want to nerf the latter.

How often do you see people assassinated in the first minute of a round? Personally, I have seen it happen maybe two or three times in a thousand rounds, despite plenty of people spawning with better stuns and weapons - any antag head of staff. After the one minute mark, everybody will have had more than enough time to trot over to tool storage or dorms for wirecutters to grab a flash. Or even spend ten seconds making a stunprod. This is why nobody cares about anyone starting with the tagger quirk. Because it's a non-issue. Stop hugboxing everything that's ever killed or mildly annoyed you in a round.


_Clearly you haven't seen the magic of shove > wall throw chainstuns_

**Comment by ExcessiveUseOfCobblestone** [comment]
I have no idea what's going on in this PR but calm down anons.

**Pull request merged**
