### PR TITLE
Removes Internals HUD element

### PR DESCRIPTION
**Pull request by 13spacemen**
goldborderab

Removes the internals HUD element on the right side of the screen (the gas mask and tank icon)
Internals action buttons have a gold border and are always inserted in the top-left (first in list) by default

## Why?

It's been years since the internals tank action buttons were added and most players use those instead of the internals HUD element. I myself eventually found myself totally stop using the HUD and switch to action buttons only.

Action buttons are superior because:
Much easier to click on, correspond to whatever tank you have, can pick what tank to use if you have multiple, can be moved, only appear when you actually have a tank

Code-wise I left the define ui_internals in since blob health HUD uses it

:cl:
imageadd: Internals action buttons have a gold border and are inserted left-most by default
del: Removed the internals HUD icon (gas mask + tank icon)
/:cl:

### CODE REVIEW

**Comment by Iamgoofball** [comment]
:-1:
this is uglier than the internals hud icon i've been clicking for the last 10 years

**Comment by 13spacemen** [comment]
@Iamgoofball it does not move the action button there. It just removes the internals HUD entirely. I moved it there in the screenshot

**Comment by Iamgoofball** [comment]
even worse

**Comment by castawaynont** [comment]
sovl removal

**Comment by Kapu1178** [comment]
Good. It's more consistent with this change.

**Comment by Fikou** [comment]
move the other elements up

**Comment by 13spacemen** [comment]
@Fikou shifted them up 4 pixels
alertsinternals

**Comment by TheSmallBlue** [comment]
yes I COULD move the internals button to where it is now if this is merged, but it'd go over HUD notifs, it'd be finickier, and most importantly very ugly.

**Comment by 13spacemen** [comment]
@TheSmallBlue it does not go over HUD notifs, there is no overlap in normal gameplay, I just drew that in the OP pic to show you can move it if its about positioning

**Comment by TheSmallBlue** [comment]
Nono I know, what I'm trying to say is that I like the hud button because of the position and because of the look. As far as I understand on the position thing you're basically just saying "just move it to the place where the current hud button is now" which won't work because it'd overlap. I know it doesn't overlap by default

**Comment by Mothblocks** [comment]
Me and Lemon have talked a great deal about what the ideal UI looks like and it includes this but alongside locking the oxygen tank action to the top left, so that it's always consistent. I don't want this change without the other one.

**Comment by Twaticus** [comment]
no hell no

**Comment by theselfish** [comment]
...People use the airtank button in the top left?

**Review by Mothblocks — APPROVED** [review]
Me and Lemon both wanted this, I'm leaving it TM'd on Sybil for a bit to see how much I like it but in the round I played I think it went well

**Comment by zxaber** [comment]
The button on the right is smaller and more out of the way, and also always in the same spot. Action buttons can move depending on order obtained. More personally, I usually just moved the extra tank button into the action button ~~forever box~~ hidden buttons folder.

Not a hill to die on, but I liked the dedicated HUD element more.

**Comment by Mothblocks** [comment]
image

**Pull request merged**
