### PR TITLE
Webedit fixing GLOBAL_PROC advanced proc calls.

### LINKED ISSUE #49586: Runtime when attempting to call a global proc via Advanced ProcCall
Title, attempting to call a global proc using Advanced ProcCall fails and throws a runtime, calling procs with a parent(?) still works fine however.
#### Testmerges: Currently using [#49351](https://github.com/tgstation/tgstation/pull/49351) for local testing.

>[17:40:27] Runtime in callproc.dm,122: bad proc
proc name: WrapAdminProcCall (/world/proc/WrapAdminProcCall)
usr: -snip-/(-snip-)
usr.loc: (Central Primary Hallway (113, 141, 2))
src: world
call stack:
world: WrapAdminProcCall("some_magic_bullshit", "Gcd", /list (/list))
WrapAdminProcCall("some_magic_bullshit", "Gcd", /list (/list))
  -snip- (/client): callproc blocking(null)
  -snip- (/client): Advanced ProcCall()

#### Reproduction:
- Use the Advanced ProcCall verb, select no when prompted if proc is own by anything.
- Input a global proc name e.g. /proc/Gcd with 2 number arguments (Greatest Common Divisor proc)
- add in whatever arguments you wish
- Watch as the proc returns null and you get an unwanted runtime.

Straight to the point this report is mostly made out of concern on whether the fixes found in #42952 were actually implemented, since after tracing the issue and finding out it should already 
be fixed the actual TG git code doesn't show it being that way. The code history for `callproc.dm` doesn't show any other changes afterwards either.

As for the quickest fix itself:
https://github.com/tgstation/tgstation/blob/master/code/modules/admin/callproc/callproc.dm#L68
`returnval = WrapAdminProcCall(GLOBAL_PROC, procname, lst) // Pass the lst as an argument list to the proc`
was changed to:
https://github.com/tgstation/tgstation/pull/42952/files#diff-179d42b079dcb2502e1ed09ea3875101R87
`returnval = WrapAdminProcCall(GLOBAL_PROC, procpath, lst) //calling globals needs full qualified name (e.g /proc/foo)`

Ultimately unsure on any further information pertaining to this topic, couldn't find a coder on the servers though perhaps I still should have consulted coderbus before making this.

### PR DESCRIPTION
**Pull request by Ghommie**
## About The Pull Request
I'm perplexed no badmin fixed this yet.

## Why It's Good For The Game
This will close #49586 and let me easily test global procs in a local environment again.
I tested this while working on another branch. I'm just too tired to not make a webedit.

## Changelog
:cl:
fix: Badmins and coders alike, rejoice! Global advanced proc calls have been fixed.
/:cl:

### CODE REVIEW

**Comment by Jared-Fogle** [comment]
> I'm perplexed no badmin fixed this yet.

Cause it works? I'm confused, I've been using this for a while.

**Comment by Ghommie** [comment]
> 
> 
> > I'm perplexed no badmin fixed this yet.
> 
> Cause it works? I'm confused, I've been using this for a while.
Advanced proccalls with a target atom work, but have you actually tried calling procs not owned by datums such as `/proc/text2dir` through the advanced proc call debug verb?

**Comment by Jared-Fogle** [comment]
Oh, weird, it fails silently (well, other than the runtime that is). I must have assumed it worked because of that. Carry on.

**Review by Mothblocks — APPROVED** [review]

**Comment by AnturK** [comment]
This broke proc calling global procs in sdql

**Pull request merged**
