### PR TITLE
 Sulphuric Acid is no longer an option on the chem dispenser. Now has to be made with hydrogen, oxygen and sulfur.

### PR DESCRIPTION
**Pull request by praisenarsie**
🆑 Frozenguy5
tweak: Sulphuric Acid is removed as an option to the chem dispenser. You now have to make it with hydrogen (1), oxygen (1) and sulfur (1).
/🆑

I want to rework chemicals, to be hopefully more interesting and realistic, I also need to add much more reagents and reactions so a chemist's arsenal is more vast and flexible (or steal from goon because that's always a good idea). Also, I want to merge the portable chem dispenser and normal chem dispenser together because fuck them.

I'll also have to rename the reagent ids to work better with goofball/morty's chem macros (like stable_plasma (why is it stable?? what makes it stable??))

### CODE REVIEW

**Comment by BlueNothing** [comment]
This is bad, it should be Hydrogen(2), Sulfur(1), Oxygen(4). If you're going to make it realistic, do it right.

**Comment by praisenarsie** [comment]
@BlueNothing i don't want to make it THAT realistic, besides those numbers feel really odd and annoying. I want to make it so the chemist can still be comfortable with chemistry.

**Comment by ike709** [comment]
By using an incorrect formula, you're making chemistry _less_ realistic, not more.

**Comment by XDTM** [comment]
Gameplay is important too. And a formula that sorta resembles the real one is a step up from "it just appears", imo.

**Comment by praisenarsie** [comment]
alright i'll change it to Hydrogen(2), Sulfur(1), Oxygen(4) but what should the output/results be.

**Comment by arsserpentarium** [comment]
please,add reciepe for water.

**Comment by PaznerIV** [comment]
I would say 7 units since that would be the total amount you used and most recipes follow that same pattern

**Comment by Xhuis** [comment]
This feels a bit like complexity for the sake of complexity, especially since it's made for a larger set of changes that isn't yet coded.

**Comment by praisenarsie** [comment]
@Xhuis Good point. I'll come back with my actual overhaul (if I bother to code it).

**Comment by Tlaltecuhtli** [comment]
keep the recipe but dont  remove acid from chem dispensers

**Comment by FantasticFwoosh** [comment]
Its like that over in paradise station in (1,1,1) amounts, i mean i don't particularly mind mixing it but from a gameplay perspective i can see why you might want to slow down making 100u of sulph out the tap to throw at a wizard immediately. If i can change your mind @praisenarsie

**Pull request closed without merging**
