### PR TITLE
SMES units now accept charge even if the available input is less than the input rate.

### PR DESCRIPTION
**Pull request by ghost**
:cl: McBawbaggings
tweak: SMES units will now accept charge from the power network even if the available load is less than the input rate. Credit to Zaers for the original code.
/:cl:

This is a very old QoL port from https://github.com/Riesen/-tg-station/pull/59
The code is originally by Zaers.

image
Tested locally to ensure it works.

It's rather silly that when you set the solars SMES units to 90k, it won't charge when the solars are half on and such. What's the point in those SMES units if it's just simpler to wire the solars right into the grid.

### CODE REVIEW

**Comment by GunHog** [comment]
About time....

**Comment by RandomMarine** [comment]
Is there any reason to not set every SMES's input to max with this?

**Comment by McBawbaggings** [comment]
If you had 2 or more SMES units on a power network that didn't meet the max demand of both SMES units, you would probably want to split the load evenly between them since one would charge fully and the other would charge at a much lower rate.

**Comment by Jalleo** [comment]
Let it be uneven in charging. At least one ntil we make things better. 
Also I am fine with this PR but we really should make the output less OP if we do this.

**Comment by McBawbaggings** [comment]
Cheers lads.

**Pull request merged**
