### PR TITLE
Resprites plant grafts

### PR DESCRIPTION
**Pull request by ArcaneMusic**
## About The Pull Request

This pull request resprites plant grafts from the original rework of botany back in 2020.
I noticed them in game and realized these were pretty rough by both current standards as well as my own, so I took some time out to resprite these this afternoon, take a look:

image

## Why It's Good For The Game

Overall I feel like it's certainly a visual improvement over what I threw together years ago, plus it does tend to just look nicer at the end of the day in my opinion.

## Changelog

:cl:
image: New sprites for plant grafts!
/:cl:

### CODE REVIEW

**Comment by Arctrooper8** [comment]
I never even realized the brown thing on the bottom was supposed to be a bag. These look amazing!

**Comment by Cheshify** [comment]
The plants look great but I don't know about the dithering effect on those bags?

**Review by Ghommie — APPROVED** [review]
Not a fan of dithering, but these are undeniably better.

**Comment by Wallemations** [comment]
Dithering is fine for the material these types of bags are usually made of
Sorta potato-sack type stuff y'know

**Pull request merged**
