### PR TITLE
[READY] getFlatIcon performance!

### PR DESCRIPTION
**Pull request by silicons**
# Cuts processing cost by around 50% in most cases, with larger increases in some circumstances like lots of layers without "nesting" overlays, sideways stuff, etc etc.
FINAL RESULTS FOR CURRENT REVISION
image

## The only TG applicable bug found right now is a possibility of your cat ears being rendered in the wrong direction on photos and previews. Still works perfectly in game.

image
All fixed.

### CODE REVIEW

**Comment by kevinz000** [comment]
on that note, >1 hour for 8.8% performance increase
thxbyond

**Comment by kevinz000** [comment]
image

**Comment by StarSmasher44** [comment]
So which one is which?

**Comment by Cruix** [comment]
It looks like this will cause #19567 to reopen.

**Comment by kevinz000** [comment]
okay icons are generating on server but this happened 
image

**Comment by kevinz000** [comment]
image

**Pull request merged**
