### PR TITLE
Fix tram map second z level wrong space turfs

### PR DESCRIPTION
**Pull request by Ghilker**
## About The Pull Request
fix the second z level corner that had the wrong space turfs
image

## Why It's Good For The Game
map fix

no cl since there is no gameplay change

### CODE REVIEW

**Comment by Mothblocks** [comment]
???

**Comment by Kylerace** [comment]
Ah yes, aYr

**Comment by Ghilker** [comment]
> ???

the second z level corner had the wrong space turfs, i fixed it

**Comment by Mothblocks** [comment]
can you put that in the pr title and body rather than vague "fixed, i fixed it"

**Comment by ArcaneDefence** [comment]
.... Is this related to https://github.com/tgstation/tgstation/issues/58436

**Comment by LemonInTheDark** [comment]
> 
> 
> .... Is this related to #58436

Shouldn't be, no

**Pull request merged**
