### PR TITLE
[WIP] Makes action buttons bindable to empty hand usage

### PR DESCRIPTION
**Pull request by Dingo-Dongler**
## About The Pull Request

Allows players to on-the-fly bind different actions to "use in hand" with an empty hands. This is done by middle clicking the action button with the hand you wish to put the action in. There is currently no way to see what action is in what hand, which I will work on next. Making this PR early because I am very aware that this could be an ungraceful solution.

## Why It's Good For The Game

This should streamline some action-oriented stuff, like spellcasting and toolset implants.

## Changelog
:cl:
add: Middle clicking an action button binds it to a hand. "Use in hand" an empty hand to trigger its bound action.
/:cl:

### CODE REVIEW

**Comment by AnonymousNow** [comment]
Neat.

**Comment by Tharcoonvagh** [comment]
This will just turn tg into an action game

**Comment by lolman360** [comment]
Bind fireball > z > click someone

i love wizard now!

**Comment by cacogen** [comment]
All for UI improvements, not sure what this will do to balance

**Comment by PKPenguin321** [comment]
Might be kinda dumb with krav maga

**Comment by Dingo-Dongler** [comment]
I feel like this won't be too strong with longer cooldown stuff like fireballs, and low cooldown stuff like wizard's card shotgun and lightning bolt aren't used much anyways (likely because clicking the corner of the screen every two seconds is clunky af) so I don't think this would affect balance much.

**Comment by Dingo-Dongler** [comment]
Also to clarify since I think people are misunderstanding, this doesn't let you bypass cooldowns.

**Comment by Dingo-Dongler** [comment]
This is pretty clunky and doesn't even help for having more than two actions (rip krav maga), plus I have no idea how to represent this hudwise so I'm just gonna close this one down. Maybe I'll do something with binding actions to f1-12 in future, but don't count on it.

**Comment by remuluson2** [comment]
shame...

**Pull request closed without merging**
