### PR TITLE
Fixed some possible runtimes with pollCandidates()

### PR DESCRIPTION
**Pull request by Cruix**

### CODE REVIEW

**Comment by MrStonedOne** [comment]
I'm having trouble understanding what this does.

**Comment by AnturK** [comment]
Observers only get deleted when lacking a key so this isn't really an isssue ? Or is it ?

**Comment by Cruix** [comment]
It cancels the poll if the mob that the poll is putting someone into gets deleted before the poll ends.

**Comment by optimumtact** [comment]
Please fix the conflicts so I can merge.

**Comment by optimumtact** [comment]
Thanks

**Pull request merged**
