### PR TITLE
The yearly april fools maid costume sprite update

### PR DESCRIPTION
**Pull request by Ebin-Halcyon**
## About The Pull Request

Updates the maid outfit minorly tweaks the colors, makes it not make me sad whenever I look at it.

maid spin
## Why It's Good For The Game

I was a wee babby spriter back then. I am a slightly better spriter now and I want to fix my old stuff.
## Changelog
:cl:
imageadd: The maid costume has gotten it's colors slightly tweaked, should look nicer.
/:cl:

### CODE REVIEW

**Review by Imaginos16 — APPROVED** [review]
Yeah this is fine

**Comment by Ebin-Halcyon** [comment]
> why is it on a lizard

maxresdefault

**Comment by Mothblocks** [comment]
your title says april fools. is this actually intended to be merged?

**Comment by Ebin-Halcyon** [comment]
> your title says april fools. is this actually intended to be merged?

Yeah, just referencing I resprited the maid outfit last year on April fools as well.

**Pull request merged**
