### PR TITLE
[ON HOLD] Readds fun

### PR DESCRIPTION
**Pull request by ghost**
:cl: MORE ROBUST THAN YOU
add: HEADPATTING
add: SLAP THOSE CATS IN THE FACE TO MAKE THEM STOP WAGGIN THEIR STUPID TAILS!
/:cl:

### CODE REVIEW

**Comment by optimumtact** [comment]
hey man, you need to make them emotes

**Comment by ChangelingRain** [comment]
chilly

**Comment by qbmax32** [comment]
b a n  h e

**Comment by ShizCalev** [comment]
1e7

**Comment by Kraseo** [comment]
24 hour rule

**Pull request closed without merging**
