### PR TITLE
Wall-mounted nanomeds no longer have more contents than the Nanomed Plus.

### PR DESCRIPTION
**Pull request by harmonyn**
Fixes https://github.com/tgstation/-tg-station/issues/12392.

I didn't do a straight swap so @iamgoofball let me know if you have any objections

### CODE REVIEW

**Comment by Bawhoppen** [comment]
I forget, which is which? If I remember correctly I had a pointless argument against this

**Comment by bgobandit** [comment]
Wall-mounted are on the emergency shuttle and in patient rooms. Nanomed Plus is the main medbay vending machine.

**Comment by Bawhoppen** [comment]
So I did have a pointless arguement about it

the shuttle ones are relief supplies, while the nanotrasen one is auxilary supplies with the main supplies in their actual storage room

**Comment by duncathan** [comment]
@Bawhoppen that makes sense but is not intuitive so nah

**Comment by newfren** [comment]
I'm not sure exactly, but does this remove the calomel and other fun chems the walmeds had in syringes without giving them to the larger machines?

**Comment by Shapsy** [comment]
A swap would be better so the larger med machines have calomel/atropine/whatever that the current nanomeds do

**Comment by Bawhoppen** [comment]
A swap would be outrageous, if you must fuck with them, just make them equal then.

**Comment by Shapsy** [comment]
...why would it be outrageous?

**Comment by Iamgoofball** [comment]
can you just re-add all the wallmed's chems to the default vendor pls

it'll make medics have a better life

**Comment by bgobandit** [comment]
I can re-add the calomel and shit

**Comment by Dorsisdwarf** [comment]
I like that someone wasn't caught sneaking in a ridiculously OP change to give all the new chems and medical gear they could possibly want (The whole point of the new, shitty system was to make chemists have to work to give MDs their supplies) to medbay at roundstart.

I dont like that goof says "Thats the way it should be".

**Comment by bgobandit** [comment]
@Dorsisdwarf yeah to be honest that was my intention

**Comment by TheNightingale** [comment]
The rarer chemicals in there are essential for when Chemistry isn't doing their jobs. Add the calomel/atropine/mannitol/mutadone (etc) to the real NanoMeds, as well as an additional crew monitor (since now the two from the wall-mounted vendors are gone).

**Comment by Iamgoofball** [comment]
^
Pretty much this.

**Comment by Dorsisdwarf** [comment]
If chem aren't doing their jobs, call the CMO. If the chemists ignore the CMO, call sec and watch them be dragged kicking and frothing to the gulag

**Pull request merged**
