### PR TITLE
The Wallening Approacheth: Adds directional variants to most wall mounts

### PR DESCRIPTION
**Pull request by dragomagol**
## About The Pull Request
Adds directional variants to: 
- pepper spray refills
- virus food dispensers
- wall-mounted flashes
- wall-mounted igniters (sparkers)
- defib mounts
- door buttons
- notice boards
- urinals
- wall safes
- light switches
- wall nanomeds
- fireaxe cabinets
- request consoles
- bounty boards
- mirrors
- entertainment monitors
- aux base monitor
- ticket machines
- tube lights
- small lights
- AI and evac screens

Also replaces the varedited wall mounts on the lavaland base and Centcom with the above. 
Why just those maps? It seemed the most manageable right now with the relatively frequent mapping changes. 

## Why It's Good For The Game
Reduces map file sizes, easier to use when mapping.

### CODE REVIEW

**Comment by Mothblocks** [comment]
Changelogs are only for player facing changes, so I removed it.

**Comment by Fikou** [comment]
can you maybe do this for apcs/air alarms or even cameras/lights? this would make it so that if you type directional in the mapping editor you get shown every wallmount and can place them how you please

**Comment by dragomagol** [comment]
APCs and air alarms have directional variants already! Although APC directionals are `/obj/machinery/power/apc/auto_name/north`. The lights and cameras I'll add.

**Comment by Potato-Masher** [comment]
I thought fire alarms, intercoms and extinguisher cabs already had directional variants.

**Comment by dragomagol** [comment]
The fire alarms did have directional sprites! The rest don't have em.

**Comment by Zytolg** [comment]
Oh yes!

**Comment by Potato-Masher** [comment]
> The fire alarms did have directional sprites! The rest don't have em.

Oh, I get it now, sorry. I knew some wall mounts had direction variants for easier mapping but didn't consider this handled sprites as well.

**Comment by dragomagol** [comment]
> 
> 
> I thought fire alarms, intercoms and extinguisher cabs already had directional variants.

I only just realized while looking at one of the newer maps that I didn't make the fire alarm/intercom already had directionals, you're absolutely right.

**Pull request merged**
