### PR TITLE
Removes access to free emags and free changelings from R&D

### PR DESCRIPTION
**Pull request by Iamgoofball**
:cl: Iamgoofball
balance: no fun allowed in xenobio
/:cl:

i'm fairly certain we need to stop giving R&D access to all traitor gear regardless of timegate or not and stop pretending its OK

### CODE REVIEW

**Review by Jalleo — CHANGES_REQUESTED** [review]
Please state how scientists can access this.

**Comment by Armhulen** [comment]
He's changing polymorph to not include syndicate borgs.

**Comment by Euphausiacea** [comment]
Magic carps can be spawned through gold slime reactions, one of their available spells is polymorph

**Comment by Iamgoofball** [comment]
People would then make it sentient, and polymorph a volunteer until they were a syndicate borg.

Then they'd go to cargo and order all the null crates because I'm not allowed to remove those for some reason.

**Comment by Repukan** [comment]
Remove the changeling thing too

**Comment by Iamgoofball** [comment]
good idea

**Comment by Wilchenx** [comment]
he does it for free

**Comment by Jalleo** [comment]
How do the scientists access this? Cant we have a version of this proc for wizards with it unchanged and a new proc for the magic carp?

**Comment by Dorsisdwarf** [comment]
This should be fixed by removing polymorph carp from xenobio, not removing syndieborgs from the wizards of polymorph

**Comment by F-OS** [comment]
Goof stop removing features that are extremely difficult for people to get to and provide a reward for xenobio

**Comment by AlexTheSysop42** [comment]
I really don't like this PR but at least he's honest about it

**Comment by Iamgoofball** [comment]
@Dorsisdwarf They'll whine that it ruins their gameplay experience or some shit and bikeshed for weeks and I'm not about that life right now

@F-OS Don't pretend this wasn't easy to do.

**Comment by F-OS** [comment]
@Iamgoofball then make it harder, balance by removal is lazy.

**Comment by kevinz000** [comment]
I unironically want magicarps ruined from spawns entirely.

**Comment by arsserpentarium** [comment]
Goof, what's wrong with you?
I know, that you can do good things. Why don't you finish goofkitchen? Or sorting conveyors.
Why are you trying to remove actually fun things, which occures once in blue moon?

**Comment by Shadowflame909** [comment]
>First statues get removed from xenobio. >Now you want to remove the only fun magicarp. 
 Is this proof muh coders hate fun.

**Comment by Iamgoofball** [comment]
Thanks for confirming magicarps are literally only used for loot pinatas and free antagonist

**Comment by newfren** [comment]
It takes literally an hour to get changeling unless you get lucky with reds - then it might take like 40 minutes. Most rounds end before then.

Syndieborg removal from magicarp is whatever I think I've seen that happen like... 3 times total outside of a wizard round.

**Comment by Shadowflame909** [comment]
>Thanks for confirming magicarps are literally only used for loot pinatas and free antagonist

More proof how little you know about /tg/. There's a rule that if you willingly get polymorphed you don't gain antagonist status. So any of those rare things "Lmao free ling" or "Lmao free ash drake" You actually have to get hit at least 100 times to obtain. So, whats your argument again? You just want to remove enjoyable things that can only be obtained after the shifts reaches the hour mark for...

**Comment by optimumtact** [comment]
Id' rather merge a pr removing the null crate

**Comment by PKPenguin321** [comment]
>no fun allowed

this but unironically
fuck this pr, you are big gay

**Comment by Iamgoofball** [comment]
@optimumtact I've been shot down 3 times on that by two different codebase owners, if you want to merge it go for it but last I checked kor said no

**Comment by Iamgoofball** [comment]
>There's a rule that if you willingly get polymorphed you don't gain antagonist status

More proof how little you know about /tg/. Rules have never stopped anyone ever.

**Comment by improvedname** [comment]
Remove romerol from null crates too

**Comment by evsey9** [comment]
just remove nullcrates/xenobio magicarp

if a wizard is unrobust enough to let the crew have polymorph staff then it should be allowed

**Comment by arsserpentarium** [comment]
If rules never stopped anyone, why even bother to argue about free antags?
Everyoune is free antag.

**Comment by arsserpentarium** [comment]
But we shouldn't.
It's not good approach to delete things for stupid reasons.Better to balace things around required efforts to get them and probablity to encounter them in round.

**Comment by KorPhaeron** [comment]
@optimumtact

If goof fixed his dumb stocks randomly shooting to a million dollars we wouldnt need to remove any crates

**Comment by Iamgoofball** [comment]
@KorPhaeron They're still doing that?

Nobody fucking tells me these things.

**Comment by ExcessiveUseOfCobblestone** [comment]
@Iamgoofball I changed uplink items so you can edit null crate item chances from them without affecting syndicate crate chances.

Also lettuce not forget who made the null crate absolutely r* in the first place...

**Comment by KorPhaeron** [comment]
@optimumtact getting a million credits of anything is game breaking though

Even without null crates you can order more guns than the entire crew could hold

**Comment by Iamgoofball** [comment]
>Also lettuce not forget who made the null crate absolutely r* in the first place...

no shit man, and I've tried walking back those buffs multiple times

**Comment by Kromgar** [comment]
Only time I ever get xenolings is an hour + in and it isn't even free antag. Also magikarp with polymorph is just as rare

**Comment by AdamElTablawy** [comment]
tbh magicarp with polymorph isn't that rare now with breeder extracts and so forth. that being said, it comes in too late to make a difference on the round, is the key. by the time xenobio gets hordes of syndicate cyborgs, the round is already practically over, even if they streamline it.

**Comment by PKPenguin321** [comment]
This is unironically fun removal for the sake of it
Goof has lived long enough to see himself become the enemy

**Comment by deathride58** [comment]
Holy shit, finally. A goof PR that's actually good

**Pull request closed without merging**
