### PR TITLE
Pause before drag-drop-emptying container to the floor

### LINKED ISSUE #10532: Container content transfer is incredibly unintuitive and obnoxious
https://github.com/tgstation/-tg-station/pull/9980 needs to be reverted, at least partially.

You need to drag and drop containers onto your character to open them, but if you accidentally miss and hit the tile behind you? Enjoy stuffing all that shit back in the container fuck you!!!!

I can't think of any situation in which this would be used normally and wouldn't just mess with normal gameplay.

### PR DESCRIPTION
**Pull request by kingofkosmos**
Adds a two second do_after-pause when emptying a container's contents to the floor. This is to help it from happening by accident.

Fixes #10532
(at least partially)

### CODE REVIEW

**Comment by phil235** [comment]
:+1: Could even be said to fix #10532

**Comment by Core0verload** [comment]
:+1:

**Comment by kingofkosmos** [comment]
Btw the progress bar makes this look kinda funny since it appears on the tile you're dumping the stuff onto. If there's an easy way to make it appear above the user or above the container, lemme know.

**Comment by phil235** [comment]
>Btw the progress bar makes this look kinda funny since it appears on the tile you're dumping the stuff onto. If there's an easy way to make it appear above the user or above the container, lemme know.

Change the do_after's target to "src_object" , making the turf the target was silly since the turf is never moved or deleted.

**Comment by kingofkosmos** [comment]
Awesome, works perfect!

**Comment by Lumipharon** [comment]
2 seconds is like the same time to drop everything manually, but eh.

**Pull request merged**
