### PR TITLE
Head of Security/Research Director fluff items now below standard equipment

### PR DESCRIPTION
**Pull request by Steelpoint**
Slightly reorganises the Head of Security's and Research Directors personal locker so the newer "fluff" items are below the standard issue equipment.

It's annoying as a HoS to have a grey jumpsuit and a medal box blocking access to the rest of your items, so they are now below everything else. 

:cl: Steelpoint
tweak: Slightly reshuffles the Head of Security's, and Research Directors, locker to place fluff items below essential items.
/:cl:

### CODE REVIEW

**Comment by Difrit** [comment]
Give me back my dermal implant you swine

**Comment by GunHog** [comment]
Could you do this for the RD as well, while you are at it?

**Comment by Steelpoint** [comment]
Done.

**Comment by GunHog** [comment]
Thanks STP!

**Comment by RemieRichards** [comment]
@GunHog that is an entirely different person (sometinyprick)

**Comment by Steelpoint** [comment]
Way to ruin my fun @RemieRichards

**Comment by RemieRichards** [comment]
No, we've had it with the misleading name bullshit.
I've closed PRs for it before, as have others, be thankful I just renamed it.

**Comment by lzimann** [comment]
STeelPoint

**Comment by Armhulen** [comment]
Passive aggressive and mean :(

**Comment by GunHog** [comment]
Thanks Steels!

**Comment by ShadowDeath6** [comment]
initial commit is a meme

**Comment by Tacolizard** [comment]
@Difrit what are you talking about

**Comment by lzimann** [comment]
Conflicts

**Comment by Steelpoint** [comment]
Fixed

**Comment by Steelpoint** [comment]
Always something broken.

**Comment by Steelpoint** [comment]
Broken beyond repair, I'll do a second PR to address this.

Note to self, only ever use the actual Dreammaker to fix merge conflicts, don't use the crappy github text fix thing.

**Comment by GunHog** [comment]
> Note to self, only ever use the actual Dreammaker to fix merge conflicts, don't use the crappy github text fix thing.

Do not use the text editor **ever!**

**Pull request closed without merging**
