### PR TITLE
Change the word filter configuration to allow providing reasons, fix emotes not working in filters, and implement separate OOC/IC/PDA filters

### PR DESCRIPTION
**Pull request by Mothblocks**
## About The Pull Request
Adds support for word_filter.toml, which is formatted like so:

```toml
# This configuration file forms the in-game chat filter.
# Values are stored as "word" = "reason for being banned".

# Anything in here will be blocked from IC interactions, dead chat, and OOC
[shared]
"blockedinshared" = "This message is not allowed anywhere, please use a different weird test phrase."

# Anything in here is blocked just from IC interactions, such as chat or names, but is allowed in dead chat and OOC
[ic]
"blockedinic" = "This message is not allowed IC, please use a different weird test phrase."

# Anything in here is blocked from all IC interactions *except* PDAs.
# On /tg/, netspeak is OK in PDAs.
[ic_outside_pda]
"<(0_0<)" = "Kirby dancing is strictly prohibited on this server."
```

Fixes emotes not being blockable on the word filter due to word bounds, despite having been on the prod filter for a while.

Updates rust-g to support TOML.

CC @MrStonedOne

## Why It's Good For The Game
Aside from the bug fix, the additional functionality of providing reasons is useful to explain why ":)" is banned versus something like "reddit" versus something like "antag". 

## Changelog

:cl:
server: Added a new word filter configuration: word_filter.toml, which can specify *why* words are banned.
fix: Emotes are now properly filtered.
qol: For players, you will now see which word you said was filtered.
/:cl:

### CODE REVIEW

**Comment by optimumtact** [comment]
lagiter

**Comment by Mothblocks** [comment]
at worst case its still just a regex so im curious to see how much of a performance hit there is

**Comment by Mothblocks** [comment]
going to DNM this until a test merge to see performance before/afters, actually

**Comment by Mothblocks** [comment]
image

it's not laggy

**Comment by Mothblocks** [comment]
need to fix runtimes

**Pull request merged**
