### PR TITLE
Fixes table slamming through impassable objects

### PR DESCRIPTION
**Pull request by SuperNovaa41**
## About The Pull Request

basically as it stands you can table slam through things you shouldn't be able to. allowing people to essentially teleport
i.e. Walls, the Luxury Shuttle Scanner Gate, other things

## Why It's Good For The Game
surely you can guess

## Changelog

:cl:
fix: Fixes being able to table slam through impassable objects.
/:cl:

### CODE REVIEW

**Comment by Mothblocks** [comment]
i cant merge thios. someone did it to me 2 rounds ago

**Comment by SuperNovaa41** [comment]
> i cant merge thios. someone did it to me 2 rounds ago

i know i WATCHED IT WITH MY OWN EYES

**Comment by TheBonded** [comment]
shout out to the luxury shuttle being entirely invincible, meaning ordering it during nukeops is almost a guaranteed win, as well as preventing antags from greentexting if their target is in the luxury area. or, spawn a spacecoin bubble machine right before this shuttle arrives, and get a free pass to hijack without anyone being able to stop you. but it's not a grief shuttle so don't worry.

**Comment by Mothblocks** [comment]
being invincible to specific kinds of antagonists is not a grief shuttle lol

**Pull request merged**
