### PR TITLE
Add telescreen announcement when the thunderdome is active

### PR DESCRIPTION
**Pull request by SpaceManiac**
:cl:
add: Entertainment telescreens in the bar indicate when they will show something interesting.
tweak: Entertainment telescreens can be viewed from a distance.
/:cl:

Bargoers are now informed both visually and in chat when clicking on the thunderdome telescreens is likely to actually show something interesting. Additionally, thunderdome telescreens can be watched without being directly adjacent (think sports bar TVs).

### CODE REVIEW

**Comment by PKPenguin321** [comment]
so if we're testing shit in there should we just delete the cameras

**Comment by nicbn** [comment]
deleting and having to add cameras again is bad, make a button or a verb

**Comment by subject217** [comment]
having to remember to delete cameras every time is a PITA and this shouldn't be the default behavior. if someone *really* wants people to watch what's happening in the thunderdome they can just send a command report advertising it.

**Comment by ExcessiveUseOfCobblestone** [comment]
The immersion of admins testing things in the thunderdome can already be broken though, the actual solution is to simply not test in the thunderdome and instead test somewhere else in centcomm or on a local runtimestation if it's to cause mass destruction.

**Comment by subject217** [comment]
yah but you know it never works out that way and the regenerate thunderdome feature is super useful when testing anything explosive and adding a bunch of extra work for something that provides virtually zero benefit and can easily be accomplished already ingame simply by pressing a single button and typing a short message in the one case that you ACTUALLY want people to see stuff just requires more work in the long run.

**Comment by PKPenguin321** [comment]
>The immersion of admins testing things in the thunderdome can already be broken though, the actual solution is to simply not test in the thunderdome and instead test somewhere else in centcomm or on a local runtimestation if it's to cause mass destruction.

but the nice thing about tesitng in the thunderdome is that you can just click "reset thunderdome" when youre done and poof, no more mess

**Comment by Borisvanmemes** [comment]
Just say it's CGI to make sense of it IC, bam issue fixed.

**Pull request merged**
