### PR TITLE
Revert "BYOS shuttle restrictions (Shuttle changes #1)"

### PR DESCRIPTION
**Pull request by Cheridan**
Reverts tgstation/tgstation#23904

Change did not seem to be popular

### CODE REVIEW

**Comment by optimumtact** [comment]
The change is required because ordering this shuttle any later on in the round means it won't be ready by the time the round ends.

Not every change can be popular

**Comment by Cheridan** [comment]
A restriction is probably a good idea, but we can find a longer timeframe or other restrictions that makes the most amount of people happy.

**Comment by kevinz000** [comment]
"change did not seem to be popular"
T O O L B O X E S.

**Comment by KorPhaeron** [comment]
I think the fun lost by restricting peoples build projects is going to outweight the gains from restricting potential accidents with ordering the shuttle right before it docks

**Comment by optimumtact** [comment]
Calling it accidental is optimistic

**Comment by KorPhaeron** [comment]
Well if a captain buys the shuttle then red alerts a shuttle call the admins can just ban

**Comment by kevinz000** [comment]
no we can't otherwise we're going to have to deal with a wall of text from goofball and oxford :^)

**Comment by KorPhaeron** [comment]
@kevinz000 

If you're afraid of goof and oxford you're gonna have a hard time as an admin

**Comment by Iamgoofball** [comment]
i had a guy run in and buy this shuttle during nuke op while I wasn't looking

**Comment by kevinz000** [comment]
@Iamgoofball should of ahelped it.

**Comment by ChemicalRascal** [comment]
Again, this isn't hard. Just set the limit at fifteen minutes -- plenty of time to make a decision, but not so late that it won't be finished. Blammo.

**Comment by Grazyn** [comment]
I don't recall how long it takes for the shuttle to complete refuelling, but if there really must be a time limit on the BYOS, it shouldnt'd be lower than that. After all, if you're calling the shuttle as soon as it can be called, and buy the BYOS on top of that, it's already bordering on griefing, but 10 minutes are still more than enough to seal and pressurize it.

**Comment by coiax** [comment]
@Cheridan I did address @ChemicalRascal's concerns, we don't use the nuke ops definitions anymore.

But I AM surprised that the PR got merged, I thought @optimumtact cared about popularity, except I guess when he agrees.

**Comment by Cheridan** [comment]
@coiax oh ok then, sounds like the best option then is to just raise the limit to 15 and then it'll all be good. i'll close this as it doesn't need to be fully reverted.

**Pull request closed without merging**
