### PR TITLE
Things made out of magic ratvarian brass are immune to fire and acid

### PR DESCRIPTION
**Pull request by ChangelingRain**
This does not include sigils, which are made out of magic and happen to be incredibly fragile to downright everything instead.

### CODE REVIEW

**Comment by Shadowlight213** [comment]
Letting clock cultists remove sigils for a partial refund when?
It's silly how they die to one hit for everything else, but servants can't remove them if they fuckup the placement.

**Comment by ChangelingRain** [comment]
Probably never! Clockcult is all about executing things perfectly but really doesn't have a safety net for if you fuck stuff up, and it really doesn't NEED one because of how powerful all their stuff is.

Also fucking up sigil placement is super goddamn hard to do anyway(and servants can remove them, on harm intent only because there's a very good chance they'd ruin half their sigils otherwise)

**Comment by KingPhilipIII** [comment]
My bases are always built with absolute precision and calculations as a Ratvarian. The placement of a mania motor can have a big effect depending on how close it is to the entrance of your base. Or how many caches you can fit into a 3x3 room.

**Comment by KingPhilipIII** [comment]
Five. The number is five by the way, if you're trying to maintain stealth and not brassify the walls for all to see.

**Pull request merged**
