### PR TITLE
Fixes monkey cultists being unable to invoke runes

### LINKED ISSUE #72020: Monkey cultist bug? | Can't use runes directly.
Reporting client version: 514.1583

## Testmerges:
- [Fishing-themed Escape Shuttle](https://www.github.com/tgstation/tgstation/pull/71805)
- [DRAMATIC SHUTTLES!! You can now fly around the shuttle](https://www.github.com/tgstation/tgstation/pull/71906)

## Reproduction: Be monkey, Be cultist, No clever mutation?, attempt to use any rune directly, nothing happens. I can however draw them and use some magic? 

Monkeys seem unable to use cult runes? Clicking resulted in no message or action. Haven't tested with clever mutation or as evolved monkey.
EDIT: Thought i'd clarify the magic bit. Didn't get a chance to test most of it but blood rites cant seems to absorb blood as monkey but the direct touch spells work.

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request

Fixes monkey cultists being unable to invoke runes by making the rune attack_paw proc return attack_hand proc.

Fixes https://github.com/tgstation/tgstation/issues/72020

## Why It's Good For The Game

Fixes a bug, bugs are bad.

## Changelog

:cl:
fix: Monkey cultists are now able to invoke cult runes
/:cl:

### CODE REVIEW

**Comment by IndieanaJones** [comment]
Now do the same thing but for the heretic rune as well.

**Comment by MrDoomBringer** [comment]
We sure this wasn't intentional?

**Comment by IndieanaJones** [comment]
It shouldn't be.

**Comment by SuperSlayer0** [comment]
> Now do the same thing but for the heretic rune as well.

Okay

**Pull request merged**
