### PR TITLE
Makes lizard plushes hue shifted.

### PR DESCRIPTION
**Pull request by Krysonism**
## About The Pull Request

This PR slightly resprites the gags lizard plushies. The biggest change is baked in hue shifting.

The hue shifting works best when the colour is set to something that isn't too that isn't too saturated or desaturated.
before:
bild

after: 
bild

## Why It's Good For The Game

The original sprite had very low sprite quality. We should make an effort to improve low quality sprites before converting them to gags.

## Changelog
:cl:
imageadd: The lizard plushie sprite has been modified. /:cl:

### CODE REVIEW

**Comment by Krysonism** [comment]
The shading might be controversial. Let me know what you like / don't like about it.

**Comment by tralezab** [comment]
i like it king, thanks king heres your crown emperor 👑

**Comment by CRITAWAKETS** [comment]
three issues i feel:
1) head looks too small now
2) outlines are a bit too harsh
3) the feet looked better on the old sprite

oh and 4) why you move the eyes, old eye direction better, looked goofier

**Comment by tralezab** [comment]
can you do the plasmaman plushie next?

**Comment by MrMelbert** [comment]
The outline is harsh but the hue is p nice. 

~MUH SOUUUL~

**Comment by bluetshirtguy** [comment]
I guess the only thing I can think of is the arms are really hard to see in your version, they weren't easy to see before but now it's pretty insane.

**Comment by Krysonism** [comment]
> 
> 
> I guess the only thing I can think of is the arms are really hard to see in your version, they weren't easy to see before but now it's pretty insane.

Agree. i will make a version with prominent arms.

**Comment by Krysonism** [comment]
bild

I gave him little t-rex arms.

**Comment by Krysonism** [comment]
In the future, i would like to make rare variants with alternate eyes, tails and/or tongues. 

I don't know how to set best set this up with gags however. Feel free to ping me if you have a good implementation figured out.

bild

**Pull request merged**
