### PR TITLE
Quick Medkit Tweaks

### PR DESCRIPTION
**Pull request by Twaticus**
## About The Pull Request

Makes kits square, closer to the original. Changes bruit kits back to pink. Adds latches. Makes med briefcase slightly longer. Removes unnused purple kit.

Before:
dreamseeker_hqNCZLxlEp

After:
dreamseeker_MLpdfqcoOi

## Changelog

:cl:
imageadd: further medkit tweaks
/:cl:

### CODE REVIEW

**Comment by realthomas69** [comment]
i think they look very nice!

**Comment by Serxule** [comment]
imo there's a lack of detail but looks fine

**Comment by Wallemations** [comment]
> bruit

whip

**Comment by Twaticus** [comment]
> bruit

intro-1621426767

**Comment by Mosslick** [comment]
They melt into the medbay floor too badly

**Comment by Imaginos16** [comment]
Looks good!

**Pull request merged**
