### PR TITLE
Nuclear Emergency now ends if the operatives die

### PR DESCRIPTION
**Pull request by Buggy123**
See title.

:cl:
tweak: The round will now end immediately if all nuclear operatives die during nuke ops.
/:cl:

:man_shrugging: It just makes sense, they can't be cloned unless for some reason you scan them in a autocloner, and no one else can nuke the station at that point anyway. Plus even if the OPS are immediately decimated people will almost always call the shuttle and leave anyway so...

### CODE REVIEW

**Comment by QualityVan** [comment]
Counterterrorists need to defuse the bomb before round ends. Even if all the terrorists are dead a planted bomb can still go off.

**Comment by Kromgar** [comment]
Wasn't this a thing?

**Comment by Buggy123** [comment]
It should be. Also its astronomically unlikely that the ops will plant the bomb and _then_ die.

**Comment by Kromgar** [comment]
@Buggy123 Just fucking put in an exception for if the nuke is armed. The nuke ops still have a minor victory even if they all died

**Comment by Buggy123** [comment]
I'll try to figure it out i guess.

**Comment by juanototo2** [comment]
What about humiliating syndicate failure? Some people want that to happen

>Explode the bomb inside the syndicate base

>gave them back their bomb!

**Comment by Buggy123** [comment]
You have a point.

A lot people have asked for this though, so I'm not going to close it. Lets see what people think.

**Comment by vuonojenmustaturska** [comment]
This isn't a democracy though, make it check for an armed bomb. Check wizard code for an example, which checks for active phylacteries before allowing a `round_ends_with_antag_death` check to succeed.

**Comment by Noahnoah55** [comment]
Its not like the nukies building an autocloner in the shuttle would be impossible. Also having the ability to complete the syndicate humiliating victory would be nice.

**Comment by improvedname** [comment]
Just put a timer on it

**Comment by improvedname** [comment]
Btw they can be cloned and they wont explode if you remove their implant but then they can become loot pinatas which is a risk.

**Comment by PKPenguin321** [comment]
Provided that this is overriden if the nuke has been planted, 👍 
Admins already end the round when nuke ops all die (if they feel like it/are aware that they're allowed to) and if the ops build an autocloner or some silly shit admins can set it so that the round does *not* end on their death just as easily

**Comment by RandomMarine** [comment]
The game needs _less_ hard round-enders if it ever hopes to escape from the current low (more like no) RP state, not more.

**Comment by MMMiracles** [comment]
This pretty much shits on the although rare, but possible scenario of a lone op making the comeback after his team has been annihilated. Having a blatant tell to whether or not there's an operative still kicking around trying to do their objective is pretty dumb, especially considering most op rounds have them calling the shuttle as soon as possible.

**Comment by PKPenguin321** [comment]
MMMiracles makes a good point, I hadn't considered it being a meta-tell
I guess in that case this isn't necessary

**Comment by KorPhaeron** [comment]
Shuttle is usually coming anyway in nuke, no reason to have a jarring "you killed all the badguys" ending

Also the meta stuff

**Pull request closed without merging**
