### PR TITLE
Makes borer event admin only

### PR DESCRIPTION
**Pull request by Shadowlight213**
Our policy at the moment about borers is kind of a mess. Headmins recommended we disable them until we figure it out

:cl:
del: The cortical borer event is now admin only
/:cl:

### CODE REVIEW

**Comment by Durkel** [comment]
90% of borers I see do nothing but act as a heal slut, the other 10% go full asshole just murder whoever they can. They're a mess until they're either given a actual downside to having in you, or are treated as a 100% kill on sight antag.

**Comment by calzilla1** [comment]
I think if you kill a giant ass boss monster and the miners give you its hide instead of making armor out of it, i think it should give out a pretty fucking good reward

**Comment by calzilla1** [comment]
FUCK WRONG GIT

**Comment by PKPenguin321** [comment]
:+1: This was greatly needed, borers trigger me

**Comment by optimumtact** [comment]
If you're gonna rip it out just rip it out

**Comment by CPTANT** [comment]
What't the point of borers?  Its basically impossible for them to fail their objective and for the rest they just act as either turbo healing virusses or turbo assholes.

Unless you are an antag in which case they will probably just take you over and let you space yourself.

**Comment by Shadowlight213** [comment]
Their level of reproduction is pretty insane as well.
Honestly, once they have a couple hosts, they are unstoppable, since in the tine it takes to remove and hopefully kill 1, two or three will probably have been spawned.

Oh, also from what I heard, on other codebases the borer stun isn't long enough to infest, so they don't have an instant infest win ability like they do now.

**Comment by Super3222** [comment]
> Oh, also from what I heard, on other codebases the borer stun isn't long enough to infest

They always have on Yogstation.

**Comment by TehPear** [comment]
At this point I'm fine if they get ripped out. Honestly, after that PR got merged that gives people with mindshield implants immunity and some antagonist immunity but not others, it's just a mess. I still only see negative effects from that which people are going to cry tears about next even after that change. I hate dumb restrictions that really don't fix anything but are band-aids on a gaping wound that is still bleeding.

**Comment by uraniummeltdown** [comment]
Reduce event weight to 15 or even 10+ increase reproduction chems to 200 + reduce borer stun by 2-3s + thickmaterial protection + revert mindshield/cultist protection = fix borer

I'll put up a PR when I get back home

**Comment by PKPenguin321** [comment]
>Reduce event weight to 15 or even 10+ increase reproduction chems to 200 + reduce borer stun by 2-3s + thickmaterial protection + revert mindshield/cultist protection = fix borer

doesnt fix the underlying issue of them existing to make crew invincible and kill antags with no effort

**Comment by GunHog** [comment]
Set their direction. Are they infecting conversion antags? Convert the borer too! Sec has mindshields and are the first people to try and kill them. They should consider Sec a threat and anyone who opposes Sec is their friend.

**Pull request merged**
