### PR TITLE
Maps tesla into all 4 maps that used Singularity engine except Dream.

### PR DESCRIPTION
**Pull request by Iamgoofball**
MERGE THIS ASAP FOR FUCKS SAKE, OTHERWISE THE ENGINE ISN'T GONNA BE MAPPED IN ANYWHERE BUT DREAMSTATION

MERGE DREAMSTATION ASAP BTW TOO

I doublechecked the wiring and fixed the missing wires post-taking these images.

Singularity generator is in the secure storage so don't whine about it being gone.

### CODE REVIEW

**Comment by Incoming5643** [comment]
get out

**Comment by Iamgoofball** [comment]
no

**Comment by Incoming5643** [comment]
put em both on the platform

**Comment by Iamgoofball** [comment]
no

**Comment by Xhuis** [comment]
Whether or not they can both go on the platform probably depends on how the tesla engine is activated, since I don't actually know.

**Comment by Incoming5643** [comment]
if they're both on the platform and the Engineers are two dumb to pick one unless there's new handling for this, there'll be an explosion, and one will win out

**Comment by Iamgoofball** [comment]
singulo wins in that regard if it's tesla vs singulo

**Comment by Zilenan91** [comment]
:+1:  Tesla is probably the more fun engine because it doesn't instantly end the round like the singulo does, simply beating it up, stealing its lunch money, and leaving it in an alley.

**Comment by MrStonedOne** [comment]
:-1:

**Comment by Incoming5643** [comment]
<i>casuals</i>

**Comment by Bawhoppen** [comment]
:-1: meme tesla shit

**Comment by Incoming5643** [comment]
<em><sup>c</sup>a<sub>s</sub>u<sup>a</sup>l<sub>s

**Comment by KazeEspada** [comment]
:+1:

**Comment by Xhuis** [comment]
### ___AAAAAAAAAAAAAAAAAA___

**Comment by Incoming5643** [comment]
To be clear here the singularity is one of the most iconic objects in the entire game I can't approve of anything that would reduce the odds of the station dying before its might. At best anything gets equal billing with the lord.

**Comment by Iamgoofball** [comment]
singulo will die eventually

**Comment by Zilenan91** [comment]
Any reason for the closure?

**Comment by Iamgoofball** [comment]
see: new PR that got opened

**Pull request closed without merging**
