### PR TITLE
Updates shuttle curse icon

### PR DESCRIPTION
**Pull request by TechnoAlchemisto**
Reused sprites make me upset so now you get my sprites instead.

kill

### CODE REVIEW

**Comment by coiax** [comment]
What is it

**Comment by TechnoAlchemisto** [comment]
orb

**Comment by coiax** [comment]
Ohhhh. It's the cult shuttle curse. I thought it was the shadowling spell.

**Comment by WJohn** [comment]
Where is this used in game? I don't have a point of reference at all, so I can't tell how much better the sprite is with what it used to be.

**Comment by TechnoAlchemisto** [comment]
The actual icon is the bluespace projectile colored #FF0000

It didn't look bad per se, but I would prefer if everything had a unique sprite.

**Comment by coiax** [comment]
Wjohn, the old shuttle curse sprite is a dark red coloured scrying orb.

**Comment by Armhulen** [comment]
In techno's ideal station, every thing would have it's own sprite to call it's own

Patriotic :+1:

**Comment by KorPhaeron** [comment]
looks like a cherry

**Comment by Chocobro** [comment]
could do with being smaller imo
there's a fair bit of blocky grey

**Pull request merged**
