### PR TITLE
Adds (fake) ambient occlusion as a client preference

### PR DESCRIPTION
**Pull request by deathride58**
@MrStonedOne ambient occlusion is a shading technique that simulates how light behaves in the real world, where areas that aren't directly exposed to light tend to receive less lighting. In 3d rendered scenes with ambient occlusion present, this can easily be seen in corners and other crevices in geometry, and can also be visible when two objects are close to one another. Here's a Wikipedia article on ambient occlusion, for more in-depth detail.
This PR fakes the effect of ambient occlusion by adding a blurred, transparent drop shadow filter to the game plane, and adding a new floor plane. This creates the illusion of ambient occlusion, and makes objects stand out a little from the floor. In the screenshots I've provided in the original post of this PR, this is most noticeable underneath chairs and tables.

Here's a portion of one of the screenshots with ambient occlusion disabled. Take a close look at the floors right underneath the chairs and stools, and notice how the floor is completely lit underneath them.
image

And here's a portion of one of the screenshots with ambient occlusion enabled. You can see subtle shadowing underneath the chairs and tables, and the same subtle shading is visible where the walls and windows meet the floor.
image

If you legitimately do not notice a single difference between ambient occlusion being enabled/disabled, then your monitor might be to blame. If your monitor has either low contrast or low brightness, then the effect will be pretty hard to notice.

:cl: deathride58
add: Added ambient occlusion. You can toggle this on or off in the game preferences menu.
/:cl:

### CODE REVIEW

**Comment by Tlaltecuhtli** [comment]
the rtables look bad tho

**Comment by Bluespace** [comment]
it makes things pop much more, i like it

**Comment by nicbn** [comment]
Cardboard station 13

**Comment by PKPenguin321** [comment]
Juicy

**Comment by AnturK** [comment]
Don't care about the effect but implementation is horrible idea.

**Comment by deathride58** [comment]
@AnturK can you elaborate as to how exactly the implementation is horrible?

If the filter is applied to individual objects instead of a planemaster, then clientside performance will take a *MASSIVE* impact, the server will end up using a metric fuckload of memory, and it'll be impossible to toggle the effect on/off on a per-client basis.

I can't think of any other way the effect could possibly be implemented without harming client or server performance, and without introducing a bunch of weird bugs.

**Comment by AnturK** [comment]
It's not about performance it's about slicing default plane in two with arbitrary items thrown in.

**Comment by deathride58** [comment]
Can you elaborate on that?

I've made absolutely sure that the things that were moved to the floor plane were things that are on the ground, rendering underneath everything else in the first place. Things like vents, holopads, decals, catwalks, latices, etc, were moved to the floor plane, but everything else has remained untouched. Any other objects I've overlooked that are still on the game plane that should be moved to the floor plane can easily be added to the floor plane, as it's just one single var.

Keeping ambient occlusion disabled will make things appear exactly the same as they were prior to the addition of the floor plane. I've done extensive testing to ensure that this PR doesn't introduce any visible changes in layering or other graphical oddities. I've had this PR testmerged over at Citadel for about a month now (original PR that this PR mirrors can be found at https://github.com/Citadel-Station-13/Citadel-Station-13/pull/6251 ), and players haven't reported a single layering issue during the duration of the testmerge.

**Comment by Dorsisdwarf** [comment]
The fact that ghosts leave "shadows" with this is ugly and dumb but the rest of it is very nice

**Comment by optimumtact** [comment]
@AnturK not sure why you have structural issues with this, planes are just management layers to apply grouped effects

**Comment by AnturK** [comment]
With this there's no simple way to do full screen effects anymore and i'm pretty sure we already use that for something besides skewium. You at least need to group the plane masters somehow.

**Comment by deathride58** [comment]
Full screen effects are still easy to do. You just have to modify one extra plane. Skewium and rotatium are currently the only fullscreen effects that're more complex than `client.color`. Both skewium and rotatium are already updated to modify the floor plane as well as the game plane, and serve as good examples for people to follow when adding fullscreen effects

**Comment by MrStonedOne** [comment]
I toggled this on and off multiple times and see no difference.

If this pr is merged I'll open and test merge a revert because this either does nothing, or the player preference is broken.

I've looked at the two pictures and also can see no difference.

@deathride58 Please explain what your prs actually do. Giving two pictures and asking the viewer to play spot the difference is not explaining anything.

What the fuck is ambient occlusion?

Where on these pictures should I be looking?

When I toggle the preference, what changes should I be looking at?

**Comment by optimumtact** [comment]
If you can't see the difference you might need to get your eyes checked

I'm legally blind and I can see the shadowing below items

**Comment by PKPenguin321** [comment]
You don't see it? It's a sort of black glow that emanates from structures and mobs, which gives them more contrast and makes them pop out more.

**Comment by optimumtact** [comment]
it's just a shadow stencil

**Comment by deathride58** [comment]
@MrStonedOne ambient occlusion is a shading technique that simulates how light behaves in the real world, where areas that aren't directly exposed to light tend to receive less lighting. In 3d rendered scenes with ambient occlusion present, this can easily be seen in corners and other crevices in geometry, and can also be visible when two objects are close to one another. [Here's a Wikipedia article on ambient occlusion, for more in-depth detail.](https://en.wikipedia.org/wiki/Ambient_occlusion)

This PR fakes the effect of ambient occlusion by adding a blurred, transparent drop shadow filter to the game plane, and adding a new floor plane. This creates the illusion of ambient occlusion, and makes objects stand out a little from the floor. In the screenshots I've provided in the original post of this PR, this is most noticeable underneath chairs and tables.

Here's a portion of one of the screenshots with ambient occlusion disabled. Take a close look at the floors right underneath the chairs and stools, and notice how the floor is completely lit underneath them.
image


And here's a portion of one of the screenshots with ambient occlusion enabled. You can see subtle shadowing underneath the chairs and tables, and the same subtle shading is visible where the walls and windows meet the floor.
image


If you legitimately do not notice a single difference between ambient occlusion being enabled/disabled, then your monitor might be to blame. If your monitor has either low contrast or low brightness, then the effect will be pretty hard to notice.

**Comment by optimumtact** [comment]
either that or he's deranged

**Comment by MrStonedOne** [comment]
I notice it when you point out what to look for, yes, but not until then.

Also the preference doesn't appear to be working, the shadows remain when its disabled.

**Comment by MrStonedOne** [comment]
Now add what you told me to the OP so other people looking at this pr who don't know what ambient occlusion is know what the fuck this pr does.

**Comment by ChangelingRain** [comment]
This is especially noticeable with large, transparent objects, like doors and windows.

kinda feel like cameras and lights shouldn't have it, though, it looks odd on those

**Review by ChangelingRain — APPROVED** [review]

**Pull request merged**
