### PR TITLE
Removes shadowling

### PR DESCRIPTION
**Pull request by ghost**
:cl: optional name here
del: Shadowlings have been completely removed.
/:cl:
- Removes shadowlings from the code pending a rework.

Note that I _am_ going to re-implement shadowlings in some form.

### CODE REVIEW

**Comment by Incoming5643** [comment]
I really don't get why people feel the need to do this. You don't need to remove the old work to _start_ working on the new work. You can just, you know, do the new stuff then overwrite the old stuff when the new stuff's done. Is it a motivation thing? I don't get it at all.

**Comment by Xhuis** [comment]
Personal preference. I prefer starting with a clean slate instead of leaving behind old stuff.

**Comment by Jazaen** [comment]
Could you at least leave the Ascendants, to be used in admin fuckery?

**Comment by Zilenan91** [comment]
slings are real bad :+1:

**Comment by coiax** [comment]
> gamemode code changes

reeeee

**Comment by Fox-McCloud** [comment]
Just keep it in the code until its reworked.

**Comment by Firecage** [comment]
I dislike this honestly. Just do the rework and then replace the existing shadowling shit with it, don't remove it, then start a rework which may or may not ever get done.

**Comment by Cebasiz** [comment]
i always kind of liked shadowling tbh

**Comment by Xhuis** [comment]
@coiax What's up with gamemode code? I can close this if it's something important.

**Comment by coiax** [comment]
Just datum antags stuff, it's okay, if you're just removing it, that's a lot easier to cope with than changing it.

**Comment by Xhuis** [comment]
Hrm, okay. Just contact me if you want this closed.

**Comment by KorPhaeron** [comment]
This doesnt break prefs/saves does it?

**Comment by Jalleo** [comment]
It will break prefs if they are changed i think test it locally kor

**Comment by Xhuis** [comment]
It might, yeah. Not sure how to make sure.

**Comment by KorPhaeron** [comment]
Remie said prefs will be fine

**Comment by GunHog** [comment]
Awful.

**Comment by Zilenan91** [comment]
Shadowlings were never good in the first place

**Comment by Xhuis** [comment]
@GunHog I'm not going to let you - and everyone else - down on a replacement. I said I'd revive clock cult, and I did. I'm working on it, and you can count on that. It might be some time before I PR the replacement, however. /tg/ just got a new gamemode and I want to give it time before I throw another one in the mix.

**Comment by Cebasiz** [comment]
you're a cool guy unpronounceable name

i like you

keep on keepin' on

**Comment by Xhuis** [comment]
Zwee..

**Comment by Zilenan91** [comment]
I always thought it was Zoo-iss

**Comment by Incoming5643** [comment]
X-Ho-eez

**Comment by RemieRichards** [comment]
it's Zoo-ees

**Comment by GunHog** [comment]
Zoo-Wiice

**Comment by PKPenguin321** [comment]
It's Zuis kinda like Louis but with a Z.

Also I actually like shadowling as a game mode but I have faith xhuis will bring it back in a good way.

**Comment by Chocobro** [comment]
remie and gunhog have it right

**Comment by GunHog** [comment]
> remie and gunhog have it right

Because I heard **you** say it in your videos!

**Comment by Chocobro** [comment]
yeah

**Comment by PKPenguin321** [comment]
>Sorry, this pull request couldn’t be reverted automatically. It may have already been reverted, or the content may have changed since it was merged.

REEEEEEEEEEEEEEEEEEEEEEEEEE

**Comment by Xhuis** [comment]
It's been a little over six months since this went through. I wouldn't expect it to work flawlessly either. :P

**Comment by Xhuis** [comment]
To anyone afraid I wasn't going to stay true to my word, you don't need to worry. To anyone who reviled shadowlings and don't want then back, then look for the thread in the feedback forums and give me input on how to make the more enjoyable for everyone.

**Pull request merged**
