### PR TITLE
Change closet sprites to be "perspectiveish"

### PR DESCRIPTION
**Pull request by nicbn**
Changed closet sprites to be more "perspectiveish", like the new vending machines.

[Changelogs]:

:cl:
imageadd: Added new closet sprites
imagedel: Deleted old closet sprites
/:cl:

[why]:
SS13 perspective is inconsistent beetween sprites, some are front-top and some are front-diagonal. Most of the new sprites are front-top, so I changed up the closets to be like them. Also I think that perspective is much more beautiful.

closet02

infinite

### CODE REVIEW

**Comment by QualityVan** [comment]
Pictures!

**Comment by TrustyGun** [comment]
pictures plox

**Comment by dannno** [comment]
you must provide pictures my friend

**Comment by PraiseRatvar** [comment]
basically it follows the style of the recent sprite addition and they look nice anyway

**Comment by bgobandit** [comment]
the overlap looks incredibly shit

**Comment by Repukan** [comment]
Looks bad

**Comment by Repukan** [comment]
As in, they look too wide

**Comment by nicbn** [comment]
I tried to keep the original sprites proportion for doors, for me the overlap is really ok, but I'll try to small the doors up so they'll fit better.

**Comment by TrustyGun** [comment]
secure lockers look extremely off. why did you change the lock

**Comment by bgobandit** [comment]
the overlap is terrible, it looks like a goddamn ice cube tray, not individual lockers.

**Comment by dannno** [comment]
I don't understand what you mean by "overlap" when each sprite is 32x32 and they can't overlap like that

**Comment by nicbn** [comment]
I didn't changed the locks. Also can you be more specific? I can't fix the sprites if the only thing you say is that it looks like an ice cube tray.

**Comment by GunHog** [comment]
These look awful, in my opinion. There is not a clear lining separating the top and the door. As for the the personal closets on the right side, those look like a low-detail blob box - not at all an improvement.

I am against the 3/4 "top down" perspective, but I overlook this if the sprite contains improved detail in exchange. Water and welding fuel tanks are an excellent example of this. These sprites are not an improvement, nor do they have better detailing.

**Comment by TrustyGun** [comment]
@nicbn 
image
It's the light around the lock. It's too opaque on your lockers!

The ice cube complaint may be because of how boxy the new sprites look. If you look at the original sprites, they aren't a total box; the corners are more angular. This goes a long way to making a sprite look better and less "boring"

**Comment by dannno** [comment]
3/4 is not top down

**Comment by GunHog** [comment]
Correction noted.

**Comment by dannno** [comment]
You naive little snake. Fix it.

**Comment by Tacolizard** [comment]
if you're gonna use 3/4ths sprites just use goon's sprites. They have ones for lockers.

**Comment by nicbn** [comment]
I fixed some of the issues. I'm compiling now and I'll be uploading new screenshots.

**Comment by DoctoreMad** [comment]
>2 likes 9 dislikes

👍 where's the merge

**Comment by RandomMarine** [comment]
There is _never_ going to be a consistent art style. We have humans viewed from the side prancing around on completely top-down wall and tile surfaces and interacting with objects shown from all manner of perspectives.

It's not worth changing one set of sprites for another solely for the sake of perspective change. Just go with whatever looks better for what it represents because consistency is unattainable.

I like the old lockers better, anyway.

**Comment by Supermichael777** [comment]
like use 1/10 the alpha on the lock overlay

**Comment by dannno** [comment]
oh look it's a non-contributing shitposter who has fooled himself into thinking there's some kind of voting system

laugh at how stupid he is

**Comment by nicbn** [comment]
What I'm trying to do here is to take a step in the direction of a consistent art style. We could change the walls and other sprites that are inconsistent, but we need to start from somewhere.
Maybe most of the people who are pointing flaws on this art style is because of some kind of nostalgia they feel with old closets. But come on, the only reason we have /tg/, /vg/, para, goon and many other branches of SS13 now is because some time ago we decided to abandon all of nostalgia and started to evolve up the game.
Also I'd love if someone fixes the locks. GIMP doesn't work well with alpha, at least for me.

**Comment by dannno** [comment]
👍

**Comment by Repukan** [comment]
All feedback I have done in this pr was of stuff that didn't look aesthetically pleasing, and from my perspective on how wide the lockers seemed.

Don't out words or intentions on my fucking person, thanks.

**Comment by nicbn** [comment]
Most of the people does not means Repukan... And I said maybe, and maybe means maybe.
Also I didn't change the width of the front face of lockers, only the side face, which width is now zero.

**Comment by dannno** [comment]
Wasn't talking about you, butt breath

**Comment by Repukan** [comment]
My butt doesn't smell like breath

**Comment by nicbn** [comment]
I'd like you to comment this pull request only with useful information. If you liked it, thumb up the pull and, if you want, comment it. If you didn't, thumb down the pull and comment how I can improve it. This way I'm able to do some actual changes. Also feel free to upload new sprites with changes that you think I should have done (just please stick to the perspective).

**Comment by DoctoreMad** [comment]
>thumb down the pull and comment how I can improve it

Figuring out that SS13 will never have a consistent artstyle, realize that the best you can do is simply make sprites better. If switching to 3/4 would make a sprite look worse, why would you do it?

**Comment by Repukan** [comment]
When the locker doors are open, from what I can see in the picture, it seems too askew. Maybe try shifting up a little.

**Comment by PKPenguin321** [comment]
can you look at this and really think this is better
https://user-images.githubusercontent.com/7079721/27012726-d9ee756e-4ea3-11e7-92cd-bfbf3643ebaf.png
it looks like shit

**Comment by WJohn** [comment]
While I'm definitely for 3/4th, these sprites need some work. PKPenguin's picture is just not what's being displayed right now and is probably gonna warp what people think of the sprites (do edit your comment please).

So here's some things that need improvement:
1. The back of the lockers could be rounder, remove the very top left and very top right pixels to round it out a bit.
2. Could use a bit more highlights on the edges. It's currently only shown on the bottom edge, but should also affect the sides (but not the back).
3. I am NOT a fan of how the open sprites look, that needs some major rework as it is flat in front and also has 2 pixel thick borders for some reason, please redo these.
5. Could use a little bit sharper contrast on the top half of the locking panels, it's a bit too much gradient.
6. The Highlights stretching up either side of the lockers moving towards the top is a bit too much a gradient, too, please sharpen the contrast there as well.

If you fix these and I don't see any more problems, I think I'd be happy to merge this. After that we'll just have crates and computers to move to 3/4th and we'll have just about structure/machine done.

**Comment by nicbn** [comment]
> https://user-images.githubusercontent.com/7079721/27012726-d9ee756e-4ea3-11e7-92cd-bfbf3643ebaf.png

That sprite is an old one. Look at the new ones at the PR.

> When the locker doors are open, from what I can see in the picture, it seems too askew. Maybe try shifting up a little.
There is no room left for it in the 32x32 icon.

> Figuring out that SS13 will never have a consistent artstyle, realize that the best you can do is simply make sprites better. If switching to 3/4 would make a sprite look worse, why would you do it?
I personally think 3/4 actually looks way better. Also SS13 can have a consistent artstyle, but we won't achieve it if we don't change the sprites.

WJohn, I'll be working on it. Thanks for your answer.

**Comment by DoctoreMad** [comment]
>Also SS13 can have a consistent artstyle

I suppose I conceded that a consistent artstyle is a boon when nobody thinks it is
(Its not)

**Comment by dannno** [comment]
CM is making huge movements towards having a consistent style, and it is working.
We could have that.
and we will, hopefully
because we have an art director with a brain

**Comment by PKPenguin321** [comment]
we need an art director with eyes that doesnt merge nasty sprites

**Comment by dannno** [comment]
Pkpenguin here master nobody with Hot Gamer Opinions
blocked faggot

**Comment by nicbn** [comment]
I'm modifying goon closet sprites as they already are pretty detailed, soon I'll be commiting it here.

**Comment by MMMiracles** [comment]
3/4 looks dumb because if it isn't hugging the south-side of a wall then it looks out of place and oddly orientated. the top-down sort of sprites we currently have don't force a particular direction and therefore don't have this issue.

but it doesn't matter because the art maintainer likes it because ??? and weirdos like anime-face up there disregards opinions that are against it

**Comment by WJohn** [comment]
@MMMiracles that's just a matter of pixel shifting, and is easy to do.

**Comment by outbools** [comment]
Yeah dude you must be late at discussing 3/4 perspective concept

**Comment by MMMiracles** [comment]
doesn't matter if I'm late, still dislike it and will continue to prefer the current sprites over this attempt at perspective change, not like that matters though at this point.

**Comment by dannno** [comment]
Our current style looks just as awkward alongside walls, I genuinely do not understand that argument. That's the fault of the way we do walls.

**Comment by MMMiracles** [comment]
Current sprites still have that odd appearance, but it personally doesn't pop out as much to me as the 3/4 perspective does due to the lack of a defined direction. Maybe I'm just weird, but it was something that never bothered me in the years of playing until 3/4 started getting pushed.

**Comment by dannno** [comment]
It's because you haven't had to think about it until now.

**Comment by kevinz000** [comment]
wew
24 hours later: Pull request merged.

**Comment by MMMiracles** [comment]
I still look at both and think the original just fit in better, unless there is also plans on making walls that have actual perspective and aren't just rectangles.

**Comment by nicbn** [comment]
Going to make a new pull request later, with proper info.

**Pull request closed without merging**
