### PR TITLE
Anomaly Destroyer: handmade defuse device

### PR DESCRIPTION
**Pull request by MelokG000**
## About The Pull Request

Adds the Anomaly Destroyer, a handmade device that destroys anomalies completely (and its core too)
https://youtu.be/tonMpqtMCxw

## Why It's Good For The Game
sometimes you just need to remove the anomaly, not caring about its core, for example to save your department from its detonation, and you dont have time to scan it and input the code into a signaler
this PR adds an item that you can craft and destroy the anomaly without getting the core but faster than scanpulsing it
## Changelog
:cl:
add: anomaly destroyer - the ghetto variant of anomaly neutralizer that destroys the anomaly completely but does it instantly
/:cl:

### CODE REVIEW

**Comment by xKREKSx** [comment]
I am the spriter, if anyone cares

**Comment by Vect0r2** [comment]
In your title please put in the change that you remove signaling. Also I would replace balance with delete as I think it fits it better?

**Comment by Time-Green** [comment]
Why would anyone ever use this? It’s more difficult to make than the other options and destroys the anomaly?

**Comment by Dawnseer** [comment]
I guess it works faster than scanning, then signalling?

**Comment by Time-Green** [comment]
Why is this good for the game? This is a pretty severe change, and I don’t see any benefit to this

People also just wont have a way to get rid of the anomaly quickly? Like the recipe is quite a bit harder than just gettinf a signaller and scanner, and gives absolutely nothing??

**Comment by JohnFulpWillard** [comment]
This just seems like a downgrade honestly. It still requires the same tools as before+more+time crafting just so you don't have to put in a code (which is part of the fun of defusing a core for me) while also not getting your core.

**Comment by Dawnseer** [comment]
Honestly I'd use this, but removing the old way of scanning then using signaller seems a bit out there.

**Comment by Dawnseer** [comment]
Yeah well perhaps forcing people to use it isn't your best plan. Instead of making it the only way roundstart to do it, make it a side thing. Sure, they could scan it and then signal it. But when a Vortex anomaly hits, and you ain't got a neutralizer, you ain't gonna go over to scan it first. You stay clear undtil a neutralizer is there. Or you could have this. Make it another option instead of the only option.

**Comment by Dawnseer** [comment]
I would though? I'd much prefer to just get it over with than scan and then signal. Unless I was in the science department of course. But as a cargo technician? Or any other role that doesn't want the cores? I'd use it.

**Comment by Dawnseer** [comment]
Just make the craftable not one-use. Easy.

**Comment by Jackal-boop** [comment]
I like this change. There's no real reason to use fhe Anamoly neutralizer. This fixes that

**Comment by Dawnseer** [comment]
Only if you make it hard for them to make this one. Otherwise, if they don't want the cores (You vastly overestimate how many people care for the cores), they might enjoy this.

**Comment by Dawnseer** [comment]
Might wanna also change the changelog to reflect this

**Comment by Dawnseer** [comment]
It's been a few minutes, PRs can take days if not weeks to get looked at.

**Comment by Dawnseer** [comment]
Yep! Just a matter of chance. Is someone on the team on, and does that someone disagree strongly with what your PR does, then yep. It wasn't closed though.

**Comment by Time-Green** [comment]
It’s been only an hour and you’re already spiraling 🙂

DNM is of since the balance change js gone, but you dtill need to actually write a reason why this is good for the game, because I really don’t see it

**Comment by bob-b-b** [comment]
I don't see why this is a good thing?

Anomalies somewhat rarely get defused as is, people tend to just not bother chasing after them when they don't really give any benefit to most jobs. Even with the simple tool requirements of gas analyzer + signaler. But some anomalies are a lot more valuable with the recent anomaly gear additions so imagine the disappointment of chasing after an anomaly just to see some person has deleted it.

The anomaly neutralizer is expensive and locked behind multiple research nodes which is a large reason for why it's never used. It also can only be created via the science protolathe as far as I know.

A better way of dissuading usage of the signaller + gas analyzer combo could be adding multiple required scans or buffing up anomalies to trigger some kind of attack/pulse whenever a gas analyzer is used so you'd be more at risk when using the ''ghetto'' method of defusing an anomaly.

**Comment by Vect0r2** [comment]
Timegreen can you also remove the balance label as the 'balance' part of the PR was removed.

**Review by Wallemations — APPROVED** [review]
As much as I don't agree with the design principles of the object itself the sprite looks fine

**Comment by Dawnseer** [comment]
That was fast

**Pull request closed without merging**
