### PR TITLE
Fixes large jungle plants

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
!

### CODE REVIEW

**Comment by Steelpoint** [comment]
Excellent

**Comment by Steelpoint** [comment]
Rocks don't work.

**Comment by Steelpoint** [comment]
Also the alt variant of small bushes dont' show up in game.

**Comment by KorPhaeron** [comment]
@Steelpoint 

Alt variant of small bushes? I tried spawning all three of the jungle bushes and they showed up fine

**Pull request merged**
