### PR TITLE
Plasmamen don't have to shower anymore

### PR DESCRIPTION
**Pull request by VileBeggar**
:cl: Vile Beggar
tweak: Plasmamen have no need for regular showering anymore.
/:cl:

why: there's no reason for plasmamen to be smelly, they're just skeletons after all, are they not? it's just dumb.

### CODE REVIEW

**Review by Cyberboss — APPROVED** [review]

**Comment by ExcessiveUseOfCobblestone** [comment]
Plasmamen are walking corpses we should have an always dirty trait (preferably with option to remove overlay)

**Comment by wesoda25** [comment]
Plasmamen are already becoming the new meta, don’t let them escape hygiene. Skeletons don’t sweat, but plasma skeletons do. 

This angers me

**Comment by DapperMola** [comment]
> Plasmamen are already becoming the new meta

playing with a permanent movespeed decrease and increased vulnerability to burn damage is a meta?

**Comment by wesoda25** [comment]
Plasmamen have no slowdown. Complete flash immunity. Pretty sure virus immunity too. In the short term combat sense, they are most definitely better than other species. 

And since hygiene is fucking awful I don't want the powergamers switching to plasmamen to escape it.

**Comment by subject217** [comment]
they don't take extra brute damage currently

it's a very easy change though

**Comment by optimumtact** [comment]
just nerf plasmamen in some way

**Comment by ExcessiveUseOfCobblestone** [comment]
give them super mega burnmod they're made from plasma

**Comment by MegaEmpirical** [comment]
Taking extra brute will be horrible. Punches and everything else will be so bad. Plasmamen will never win unless they're actually armed with a range weapon if that happens.

I was perfectly fine being slow and not being deffibable. More often than not it takes people at least 3 tries to clone me into an almost acceptable fashion.

**Comment by optimumtact** [comment]
being worse than a default human is the point

**Pull request merged**
