### PR TITLE
Secway is no longer FAST

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request

Changes the secway's speed to be a bit slower - faster than a janicart but slower than running. + Doesn't have as much armor and integrity.

## Why It's Good For The Game

The secway is a peak gamer item. Good chance to block bullets, covers up some of your sprite to block melee hits, grants complete immunity to stamina damage and damage slowdown, provides slip immunity, and lets you ignore any speed penalties from your current equipment (hardsuits). There's really no reason not to take it.
Slowdown yeets out its gamer & murderboning potential as you no longer get a free shield or the ability to yackety sax around gunshots and speed away out of fights despite being on the verge of crit/stamcrit. 
It still has potential as a slowdown negation tool for overweight/hardsuited members of security (or tiders), but is no longer a downside-less boost in your combat power.

## Changelog
:cl:
balance: Secways have less armor and no longer move as fast as running. They're now 25% faster than janicarts.
/:cl:

### CODE REVIEW

**Comment by knacker48** [comment]
I thought the big problem with secways was their density? Like how they can basically block attacks if you're facing the right way

**Comment by Tlaltecuhtli** [comment]
aiming and crippling the leg of the driver stops it , just use ingame mechanics before rage pr'ing because you dont know stuff

**Comment by Fhaxaris** [comment]
what speed does it go right now? it is faster than running normally?

**Comment by Dawson1917** [comment]
> 
> 
> aiming and crippling the leg of the driver stops it , just use ingame mechanics before rage pr'ing because you dont know stuff

I've been abusing the secway for over a year tlat, don't accuse me of saltcoding :^)

Even if you go out of your way to switch aim for the one person riding the secway, they get to benefit from blocking your shots and any slowdown that would normally come from shooting the legs until it's actually crippled. Don't exaggerate this as being the solution to something so obviously strong.



> what speed does it go right now? it is faster than running normally?
> 
> the PR says it slows it down to janicart speeds.

Secway currently moves at full run speeds.

**Comment by Tlaltecuhtli** [comment]
the shots blocking by secway is literally a var  which is set to 30%(i think) if you want it to not block set it to like 5 prob?
slowdown is the same as drinking 5u from morphine(5u wont even give you sleep) which costs 20$ from medvendors  and you can just tap when engaging in combat

**Comment by Dawson1917** [comment]
> the shots blocking by secway is literally a var which is set to 30%(i think) if you want it to not block set it to like 5 prob?

Wouldn't fix the problem, and all vehicles have a chance to block projectiles. It isn't an issue on any other vehicles because its issue is its speed.

> slowdown is the same as drinking 5u from morphine(5u wont even give you sleep) which costs 20$ from medvendors and you can just tap when engaging in combat

5u - one sip - of morphine will apply a massive vision-obscuring overlay on your screen halfway through digestion, wears off quickly, does not ignore stamina damage, and requires diverting your attention to feeding yourself a pill / injecting a syringe mid-combat while the secway provides greater slowdown immunity passively, among its other benefits.

**Comment by ExcessiveUseOfCobblestone** [comment]
>  all vehicles have a chance to block projectiles

all vehicles tank projectiles by default, they have to be explicitly coded to hit the mob instead (as of now).

Why a scooter has the same HP pool as a player on top of 15% damage reduction of bullets, 20% melee is a bit confusing for me. Personally I'd rather make their HP pool small and keep the speed, the mobility should be the prominent feature of the thing.

**Comment by Dawson1917** [comment]
> Why a scooter has the same HP pool as a player on top of 15% damage reduction of bullets, 20% melee is a bit confusing for me. Personally I'd rather make their HP pool small and keep the speed, the mobility should be the prominent feature of the thing.

I could lower its 100 integrity down to around 40, but it'd still hold a lot of benefit even with that. And it'd be, like, more fragile than a scooter. As a tider (or if sec hasn't gotten into the armory and you're murderboning), you still get immunity to stamina and damage slowdown outside of stamcrit, get slip immunity, and can ignore your equipment slowdown. Even with it exploding after 2 laser shots, or one shotgun slug, I don't feel a lower integrity will fix the issues that come from having the innate benefits of vehicles while moving at max speed. Though I wouldn't see a problem with making it a bit faster than the janicart yet slower than run speed if that's what you prefer

**Comment by Tlaltecuhtli** [comment]
@ExcessiveUseOfCobblestone it is already coded to transfer projectiles to driver with a prob check

**Comment by carlarctg** [comment]
if it explodes to a single slug it's going to be kinda a pretty big downside

**Comment by Dorsisdwarf** [comment]
Wasnt the secway originally slower than running anyway and just got forgotten in a round of movespeed changes?

**Comment by anconfuzedrock** [comment]
it was as fast as, then slower by accident, then as fast as running again.

**Comment by Krysonism** [comment]
It seems pretty useless at actually catching criminals if you lower the speed. Reduce or lower the block chance instead.

**Comment by Dawson1917** [comment]
Updated to move at a middleground between run speed and janicarts/vehicle default. I still feel it's a bit too fast for all its benefits.

> It seems pretty useless at actually catching criminals if you lower the speed.

It's not meant for chasing people. It's a mallcop segway for overweight or hardsuited sec players.

>Lower the block chance instead

I already went over why just a lower block chance wouldn't fix the problem, and additionally most crew don't have access to guns so a lesser projectile block chance would be moot considering its other benefits.

**Comment by ExcessiveUseOfCobblestone** [comment]
> Wasnt the secway originally slower than running anyway and just got forgotten in a round of movespeed changes?

y-y-yes 😏

**Comment by gwhit94** [comment]
Main benefits of secway are being able to sling a duffel on your back, wear a hardsuit, eat all the vendor's donuts, and be beat up while still being able to move at speed. Big drawbacks are getting in the way of things, tide stealing it, or it being missing in general. Pro or con would be looking like Paul Blart. I like this change, but maybe there should be another secway in HoS office or sec backroom?

**Comment by Dawson1917** [comment]
It's still way faster than walking with a duffel or hardsuit or while fat. You just can't outrun everyone on the station with it anymore. And no, there definitely doesn't need to be _another_ secway.

**Comment by SkeletalElite** [comment]
I'd rather the blocking bullets get removed entirely. The slowdown avoiding is my favorite part of the secway.

**Comment by Dawson1917** [comment]
> 
> 
> I'd rather the blocking bullets get removed entirely. The slowdown avoiding is my favorite part of the secway.

Removing projectile blocking still leaves it at noslips with damage slowdown immunity. There's too much that needs to be changed for it, despite every vehicle having all these properties without being an issue, because the problem stems from its speed being higher than any other vehicle.

**Comment by ExcessiveUseOfCobblestone** [comment]
I'm still on team glass-~~cannon~~scooter where it keeps it's high speed but very easy to destroy (mfw when it absorbs 30% bomb damage just cuz lmfao).

**Comment by Dawson1917** [comment]
> 
> 
> I'm still on team glass-~cannon~scooter where it keeps it's high speed but very easy to destroy (mfw when it absorbs 30% bomb damage just cuz lmfao).

Dying in 2 lasers/gunshots leaves all its other benefits there so long as you don't run into a crewmember with a gun (armory opened, cargo, detective, cap, hos, hop). It'd still be a free boost in power to any sec, head or tider riding around on it so long as they don't run into someone with a stetchkin/revolver/ops.

**Comment by ExcessiveUseOfCobblestone** [comment]
yes, the glass cannon mechanic

**Comment by Dawson1917** [comment]
> yes, the glass cannon mechanic

these shouldn't be cannons 😬 

image

**Comment by PKPenguin321** [comment]
taking damage on the secway should make you fall off

**Comment by ExcessiveUseOfCobblestone** [comment]
> > yes, the glass cannon mechanic
> 
> these shouldn't be cannons 😬
> 
> image

yet your PR is the one keeping them with strong HP and armor, not my suggestion :smirk:

**Comment by ExcessiveUseOfCobblestone** [comment]
> Why a scooter has the same HP pool as a player on top of 15% damage reduction of bullets, 20% melee is a bit confusing for me. Personally I'd rather make their HP pool small and keep the speed, the mobility should be the prominent feature of the thing.

Get someone else to merge this or do my suggestion, this pr is granny

**Comment by ExcessiveUseOfCobblestone** [comment]
speed is still changed :smirk:

**Comment by Dawson1917** [comment]
> 
> 
> speed is still changed 😏

Vehicles will never be balanced by their nature if they're able to move at run speed. Changed speed is still faster than any other vehicle (sans cargo 1million bike) you can find on the station, it's just able to be outrun by people on foot.

**Comment by ExcessiveUseOfCobblestone** [comment]
The PR'd speed is FASTER than runspeed?

**Comment by Dawson1917** [comment]
? Move delay for humans is 1.5 on the server, 2.0 is vehicle default, 1.75 is this PR's secway speed

**Comment by ExcessiveUseOfCobblestone** [comment]
it should not be changed

**Comment by Fhaxaris** [comment]
epic merge, now it goes faster

**Comment by Dawson1917** [comment]
> 
> 
> epic merge, now it goes faster

higher move delay makes you slower!! slower!!

**Pull request merged**
