### PR TITLE
makes snow legions from portals drop skeletons (like tendril legions)

### PR DESCRIPTION
**Pull request by Hatterhat**
## About The Pull Request
Exactly what it says on the tin (snow legions only dropping ashen skeletons, like tendril legions).

Also changes the name of the "fromtendril" variable to "from_spawner", and comments it. Not sure if that warrants a changelong comment, but I'll go ahead and assume no.

## Why It's Good For The Game
being able to farm snow legion portals for an endless tide of bodies and/or equipment is a bit weird. also puts it a bit more in line with the legions of Lavaland

## Changelog

:cl:
balance: The source of the demonic portals that endlessly deposits snow legions onto the Icemoon no longer preserves the bodies nor gear of the damned (read: demon portal snow legions now only drop skeletons).
/:cl:

### CODE REVIEW

**Comment by Helg2** [comment]
image
kek

**Comment by ATH1909** [comment]
:NOOOO:

**Comment by mikederkan** [comment]
fantastic change, this has taken way too long

**Comment by Hatterhat** [comment]
> image kek

it's actually so over it's unreal

**Comment by YuliceTheDruid** [comment]
It's so fucking over bros the one reason to play icebox is being removed

**Comment by tralezab** [comment]
> > image kek
> 
> it's actually so over it's unreal

IT SHOULDN'T BE /THAT/ BAD TO DO THE REFACTOR

**Comment by Hatterhat** [comment]
> > > image kek
> > 
> > 
> > it's actually so over it's unreal
> 
> IT SHOULDN'T BE /THAT/ BAD TO DO THE REFACTOR

i have no clue what i'm doing here

**Comment by CCC23** [comment]
:*( no......

**Comment by ExcessiveUseOfCobblestone** [comment]
can you follow up with a headcoder about this since you arent actually making a new mob, its good to go otherwise

**Comment by Hatterhat** [comment]
> can you follow up with a headcoder about this since you arent actually making a new mob, its good to go otherwise

image

**Pull request merged**
