### PR TITLE
Unborks fire

### LINKED ISSUE #32337: Plasma not burning properly
Seemingly, igniter in Toxins mixing chamber on Pubby is not powerful enough to ignite the plasma/oxygen mix. I've tried both 66/33 and 50/50. Only a single-tile fire appears, but doesn't spread.

### PR DESCRIPTION
**Pull request by Supermichael777**
:cl:
fix: After literal minutes of testing our interns have found that fire does work and can still hurt you.
/:cl:

The file even says not to fuck with the defines. Fixes: #32337

### CODE REVIEW

**Comment by ACCount12** [comment]
Aren't the related defines moved to gas reaction code?

**Comment by Supermichael777** [comment]
the pr was atomized so badly i cant tell

**Comment by praisenarsie** [comment]
yeah i wondered why he removed alot of defines there but ignored it

**Comment by Supermichael777** [comment]
im compiling a clean copy to see if the bug is just old

**Comment by Supermichael777** [comment]
i think the bug report is old. i couldn't verify it.

**Comment by praisenarsie** [comment]
>old

**Comment by as334** [comment]
@Supermichael777 I'm gonna explain why everything about this PR is wrong. 1. The Fire defines aren't gone. They code wouldn't compile if they were, they were moved to reactions.dm on the request of the maintainers. 2. The code you're re-adding isn't anything related to the formation of fires, that's the part of the code that used to make water vapor extinguish fires.

**Pull request closed without merging**
