### PR TITLE
Add new lints

### PR DESCRIPTION
**Pull request by spookydonut**
## About The Pull Request
lying shouldn't be used, use mobility flags per the comment

### CODE REVIEW

**Review by Cyberboss — DISMISSED** [review]

**Comment by Dennok** [comment]
What doing SHOULD_BE_PURE()?

**Comment by spookydonut** [comment]
> 
> 
> What doing SHOULD_BE_PURE()?

https://github.com/SpaceManiac/SpacemanDMM/tree/master/src/dreamchecker#should-be-pure

**Comment by remove32** [comment]
living/lying is used pretty extensively for rotating
``` /mob/living/carbon/alien/humanoid/update_transform() //The old method of updating lying/standing was update_icons(). Aliens still expect that.
	if(lying)
		lying = 90 //Anything else looks retarded
	..()
	update_icons()
```
how is rotation handled for lying mobs at this point? thanks

**Comment by spookydonut** [comment]
> 
> 
> living/lying is used pretty extensively for rotating
> 
> ```
> 	if(lying)
> 		lying = 90 //Anything else looks retarded
> 	..()
> 	update_icons()
> ```
> 
> how is rotation handled for lying mobs at this point? thanks

mob code can change it directly, only one thing outside of it should be using it and thats unlinted

**Pull request merged**
