### PR TITLE
Inhand refactor

### PR DESCRIPTION
**Pull request by ghost**
Items now have two vars, 'righthand_file' and 'lefthand_file', which need to be set in order to display inhands. That's about it. The actual process of splitting these files up will take me a long time so I'm submitting this now for you to look at and merge in case i don't get to splitting the inhands this week.

### CODE REVIEW

**Comment by paprka** [comment]
Currently every item has 'items', but as inhands are split up into different files (guns, etc) you can just change their inhand_type var and make new files, basically never reaching the state limit again.

However, the actual task of splitting these inhands up will take me some time, so I'm putting this out there now for you guys to look at and possibly merge early if I get pulled away to do other things (my week coming up is REALLY busy with work :-1: )

**Comment by paprka** [comment]
Refactored /obj/item/weapon/gun

TODO:

/obj/item/weapon
/obj/item/clothing

Volunteers needed, holy shit this is a headache.

**Comment by paprka** [comment]
/obj/item/clothing inhands refactored

Big thanks to TZK13

**Comment by paprka** [comment]
This is ready, someone else can do obj/item/weapon some other time, it's fairly straightforward.

**Comment by dannno** [comment]
>this isn't merged yet

**Comment by paprka** [comment]
le 24h minimum

**Comment by dannno** [comment]
forget every god damn time

**Pull request merged**
