### PR TITLE
GPS Personalizations

### PR DESCRIPTION
**Pull request by ExcessiveUseOfCobblestone**
:cl: Cobby
tweak: The GPS set tag has gone from a limit of 5 characters to 20.
add: The GPS can now be personalized in both name and description.
/:cl:

Allows players to rename GPS's and their tags because the automatic renaming was going to be really long and probably obnoxious, and for labelling, which allows them to better describe what is at that particular location or lure them to an area with false promises. Consequently, this will also help alleviate the problem of finding your tag within the mess of many GPSs since you can type more than the 5 character code which nearly every other GPS has.

GPS tag setting is no longer all uppercase for the same reason.

### CODE REVIEW

**Comment by coiax** [comment]
Wait, can't you just use the GPS interface to rename it?

**Comment by ExcessiveUseOfCobblestone** [comment]
You COULD prior to this PR, you can't any longer because unique_rename is the goto for personalization! 

I'll probably make the GPS sort in a later PR to make the UI better, I wanted to get the button out though to clean it up.

**Comment by ExcessiveUseOfCobblestone** [comment]
Actually I don't like my reasoning for switching it to unique rename so i'll keep the unique rename, return the set tag function, and simply fool around with that.

**Comment by GunHog** [comment]
> Consequently, this will also help alleviate the problem of finding your tag within the mess of many GPSs

https://github.com/tgstation/tgstation/pull/26561
Umm, you know that I just redid the UI for this, right? Why did you not raise any such issues with me in my PR? I would have been happy to integrate your changes had you told me about them. Also, in the new UI, your own location is separate from the others on the list.

**Comment by ExcessiveUseOfCobblestone** [comment]
heck heck heck heck heck I'll just edit this in a later PR, I completely forgot about TGUI GPS

**Comment by Militaires** [comment]
NICE.

**Pull request closed without merging**
