### PR TITLE
Spookemojis

### PR DESCRIPTION
**Pull request by ExcessiveUseOfCobblestone**
Adds a Few emojis that are halloween-themed. 

It for some reason also wants to add beeuniforms, something that already exists.

### CODE REVIEW

**Comment by Durkel** [comment]
2spooky, please close.

**Comment by optimumtact** [comment]
Congratulations you pulled in all the changes on your bee branch.

Always make your new feature branches off the upstream repo master branch by doing
git checkout -b <featurebranchname> upstream/master

You'll have to cherry-pick the commit you made over to a new branch to fix this.

**Comment by ExcessiveUseOfCobblestone** [comment]
now it's all goofed up... *sigh*

**Comment by ExcessiveUseOfCobblestone** [comment]
ill be back shortly

**Pull request closed without merging**
