### PR TITLE
Food Expansion 6 - Pineapple, eggplant, and more!

### PR DESCRIPTION
**Pull request by MidoriWroth**
## About The Pull Request

This is my sixth food expansion, focusing primarily on adding more recipes for under-utilized ingredients such as pineapple, eggplant, and pickles. Included are a few more cookies, spaghettis, sushis, and other miscellaneous recipes for people to toy around with.

Hysk0xw
dWNLtus
zMOejJR
EvGani9
l8kCeEh
VcyvMAF

## Why It's Good For The Game

Adding more recipes for under-utilized ingredients actually makes them useful, and encourages people to make more diverse menus now that there are recipes which use them. Pineapple for example only had 3 recipes up until now. After this PR, it will have 8. Other than that, adding more recipe options allows for greater flexibility of chef gameplay, especially with simpler and easier to make options such as the falafel.

## Changelog
:cl:
add: Added 28 new food recipes!
/:cl:

### CODE REVIEW

**Comment by MidoriWroth** [comment]
May remove my noodle foods due to #75988 but idk, what do you guys think, i cant be fucked to remake all of them into the soup style.

**Comment by Rocko1345** [comment]
Will Macarons come in one color or can they be created with random colors?

**Comment by MidoriWroth** [comment]
> Will Macarons come in one color or can they be created with random colors?

Possibly! I don’t know how to specifically do that but I could maybe cannibalize the rainbow burger code to make it work

**Review by Wallemations — APPROVED** [review]
good sprites

**Comment by AdipemDragon** [comment]
do all the pineapple foods react appropriately to the pineapple liker/hater perks?

**Comment by carshalash** [comment]
Eggplant expansion aye?

**Comment by MidoriWroth** [comment]
> do all the pineapple foods react appropriately to the pineapple liker/hater perks? like is that handled automatically just Because there's pineapple in the ingredients or

oh yeahhhh i forgot about that, i'll add it in real quick

**Comment by AdipemDragon** [comment]
Also, I know it'd remove the ease of making it, but could you swap out the pastry base for some ammount of egg white?  (either 5u's or how much is in a single egg, dunno the value off the top of my head) currently egg white is just used in making pavlova in 2 different ways and that's it, and it'd work with you wanting to find more uses for food items like with pineapple

**Comment by MidoriWroth** [comment]
> Also, I know it'd remove the ease of making it, but could you swap out the pastry base for some ammount of egg white? (either 5u's or how much is in a single egg, dunno the value off the top of my head) currently egg white is just used in making pavlova in 2 different ways and that's it, and it'd work with you wanting to find more uses for food items like with pineapple

for which food exactly?

**Comment by AdipemDragon** [comment]
how'd i miss saying it, the macaron

**Comment by MidoriWroth** [comment]
> how'd i miss saying it, the macaron

oh for sure i could do that

**Comment by VladinXXV** [comment]
can we throw some pita or something in with the baba ghanoush? it'd be kinda weird to drink it like soup, and i don't think we really have a way to "dip" stuff.

**Comment by MidoriWroth** [comment]
> can we throw some pita or something in with the baba ghanoush? it'd be kinda weird to drink it like soup, and i don't think we really have a way to "dip" stuff.

yeah I can do that

**Comment by MidoriWroth** [comment]
added pita bread, tzatziki sauce, updated the ghanoush icon, and added some gyros.
LKRIxAs

**Comment by MidoriWroth** [comment]
what the heck happened

**Comment by MidoriWroth** [comment]
Looks like something in the spider code got messed up, i assume i just wait for it to get fixed?

**Pull request merged**
