### PR TITLE
Client loss on Login() handling

### PR DESCRIPTION
**Pull request by Rohesie**
The `client` variable can be nulled at any point between proc calls during `Login()`, at the very least between parent calls for sure. That can produce dirty additions to mob lists among other less problematic runtimes.
This attempts to handle it.

### CODE REVIEW

**Comment by AnturK** [comment]
I'm not sure silently returning here is good idea without actually handling removals and reversing whatever happened before in login. I guess it's a start.

**Comment by Rohesie** [comment]
`Logout()` should handle those. The idea is to stop as soon as possible not to add things after that proc has been called.
I'm assuming it is called, of course. If that's not true then the issue is bigger.

**Comment by optimumtact** [comment]
This needs a test merge for a round or two

**Comment by Jordie0608** [comment]
Testmerged on sybil.

**Comment by Rohesie** [comment]
I can go through the Login unwrapping if it's not called, but this is currently causing runtimes and not really doing it already.

**Pull request merged**
