### PR TITLE
Replaces usages of "c" or "$" with "Ꞥ"

### PR DESCRIPTION
**Pull request by actioninja**
## About The Pull Request

Magic space money. I don't really have a name for it yet, someone suggested Nanoscrip which I quite like.

Ꞥ is a pretty aesthetic stylized character we can put anywhere with utf-8 (anywhere as soon as we get 513, goonchat and tgui for now).

I've talked this over a bit with the lore nerds so they've had a bit of a heads up on this, before anyone complains about that.

Also ports vending machines to tgui next. Actual work here done by steamport from hippiestation, original pr: https://github.com/HippieStation/HippieStation/pull/12304

image

## Why It's Good For The Game

Arguments about "lol why this item cost $200????" with amazon screenshots are incredibly stupid.

USD is unlikely to be used 500 years into the future, company scrip has interesting thematic implications.

## Changelog
:cl:
add: Vending machines now use tgui-next
tweak: Money now uses "Ꞥ" instead of "$" or "c". Please report any leftover usages so they can be corrected as well.
/:cl:

### CODE REVIEW

**Comment by kopoba** [comment]
Will it work ingame?
My firefox on windows 7 didn't recognize this letter
image

**Comment by stylemistake** [comment]
I feel that there should be a space between the number and the currency symbol, and on the right. More in line with how europeans format currency.

**Comment by kriskog** [comment]
This is cool but how the fuck do I write it?

**Comment by CRITAWAKETS** [comment]
Nanocredits, my favourite.

**Comment by CAPTTLasky** [comment]
I like this a lot. Stylistically it looks cool, lore wise it makes sense for a corporation to establish a fake currency for their "employees."

The trick is, since groups like the Syndicate aren't affiliated with Nanotrasen currencies, would they still have normal credits? How would one go about exchanging currencies? What is the power of the Nanoscrip when compared to Syndicate Credits. What can the nanoscrip buy you in bread and eggs in a third world country compared to credits?

**Comment by Iatots** [comment]
Nukies have a couple vendors in their base too.

**Comment by SpaceManiac** [comment]
this is one of the weirder non-atomizations in a while

**Comment by PKPenguin321** [comment]
>not using simoleons

i§hygddt

**Comment by KingTerrytheTerrible** [comment]
can we use a character that people can see?=

**Comment by cacogen** [comment]
I was gonna use the copyright symbol, e.g. Coca-Cola Zero 355mL  ©100,000,000,000,000. This is better.  Also ~~ni~~

**Comment by optimumtact** [comment]
This can't be merged fyi, the servers are still on 512.

**Comment by SpaceManiac** [comment]
HTML interfaces could already do UTF-8 for ages, you just couldn't put it in names or anything else that's displayed in the native interface

**Comment by optimumtact** [comment]
they're using N anyway where its' not the js intefaces

**Review by SpaceManiac — CHANGES_REQUESTED** [review]
vending and N in separate PRs please

**Comment by actioninja** [comment]
doesn't render on windows 7, epic.

**Comment by cacogen** [comment]
Just make it an N or N$. Maybe https://justforex.com/education/currencies will offer some inspiration

**Comment by Krysonism** [comment]
I suggest the Ghanian cedi ₵ as the symbol for credits.

**Pull request closed without merging**
