### PR TITLE
Adds new landmark icons

### PR DESCRIPTION
**Pull request by ShizCalev**
Got tired to trying to guess wtf that X was on maps, so they all now have icons that mean shit!

from 
image

to **(OUTDATED, SEE COMMENTS)**
image

### CODE REVIEW

**Comment by Anonmare** [comment]
I can barely see anything on the bottom image unless I zoom it in

**Comment by ShizCalev** [comment]
@Anonmare you're talking about the full size?

**Comment by Anonmare** [comment]
No I mean actually zoom it in. Maybe my eyesight is going but the blue one is especially egregious against the dark backgrounds of the plating turfs.

**Comment by ike709** [comment]
The new icons are way less noticeable than the old icons 👎

**Comment by ShizCalev** [comment]
tweaking them, 1 sec.

**Comment by ShizCalev** [comment]
'bout this 
image

**Comment by PKPenguin321** [comment]
I think they look really good

**Comment by ike709** [comment]
I still think the partial squares with the question marks are less noticeable, but the blue ones with the mob type on them are better than just a plain "X".

**Comment by WJohn** [comment]
Yeah, these are nice.

**Review by WJohn — APPROVED** [review]

**Pull request merged**
