### PR TITLE
Attaching lizard tails works again.

### PR DESCRIPTION
**Pull request by harmonyn**
Fixes https://github.com/tgstation/tgstation/issues/22247.
Closes https://github.com/tgstation/tgstation/issues/19350.

### CODE REVIEW

**Comment by WJohn** [comment]
only took 7 months!

**Comment by RemieRichards** [comment]
@bgobandit are you saying this works, or are you guessing?

**Comment by bgobandit** [comment]
I have tested this on my machine and it works

**Comment by RemieRichards** [comment]
The normal, intended call chain of events, has ```update_body()``` call ```update_body_parts()```, which means there's a kink in the chain somewhere, which I'd argue is the real issue.

**Comment by bgobandit** [comment]
Mutant body parts aren't refreshed during that, I checked. Again, my guess is that this has something to do with the thing where jumpsuits hide mutant body parts, as the proc there specifically says it exists to not fuck around with update_body()

**Comment by RemieRichards** [comment]
body for humans does species, and then the carbon's implementation, which dies bodyparts, the species part of body for humans THEN calls mutant bodyparts, so the chain should be working.

**Comment by bgobandit** [comment]
not my circus, not my monkeys, this really only needs to call mutant body parts, it's like digitigrade hiding

**Comment by AnturK** [comment]
I agree with remie here, there seems to be some bigger issue here, if caling superproc fails here.

**Comment by bgobandit** [comment]
once again, that is out of the scope of this PR, which simply fixes lizard tail attachment

**Comment by RemieRichards** [comment]
A fix isn't a fix unless it's done right.

**Comment by optimumtact** [comment]
If you paper over this bug it will never get fixed, therefore I am not going to accept this.

**Comment by bgobandit** [comment]
It is not papering over the bug. Updating lizard tails only needs to call the proc for mutant body parts, it does not affect the rest of the body. Anyone else is welcome to factor update_body(), however it is out of the scope of this PR.

**Comment by optimumtact** [comment]
They have a point

**Comment by RemieRichards** [comment]
There won't be a refactor, as the call chain is already there, it's just broken/kinked somewhere along the way.

**Pull request merged**
