### PR TITLE
Gives service borgs pipe cleaners for wire art

### PR DESCRIPTION
**Pull request by TetraK1**
## About The Pull Request
Gives service borgs a pipe cleaner module for wire art.  However, as they don't have wirecutters, they won't be able to remove pipe cleaners they place.

## Why It's Good For The Game
Another thing to do as service borg.

## Changelog
:cl:Tetr4
add: Service borgs get pipe cleaners for wire art
add: you can altclick to pull up pipe cleaners
/:cl:

### CODE REVIEW

**Comment by TheRespectedMan** [comment]
A wholesome PR

**Comment by zombiegums** [comment]
thank you.

**Comment by MrDoomBringer** [comment]
Why not make it so the pipe cleaner synthesizer can also remove pipe cleaners? Seems silly to not let borgs remove them

**Comment by TetraK1** [comment]
Didn't do it originally because clicking with itself currently creates join, but no-one snipes pipe-cleaners over just clicking the turf, so I doubt anyone will miss it.

**Comment by PKPenguin321** [comment]
could just put it on alt-click

**Comment by TetraK1** [comment]
Anyone can alt-click to pull up pipe cleaners now, as I don't think there's any real reason humans and whatever shouldn't be able to.

Did most of the other method as well, but that needed refactoring that I haven't double-checked/commented.

**Pull request merged**
