### PR TITLE
Makes Medbay access more like Science, corrects an oversight with skeleton shifts.

### PR DESCRIPTION
**Pull request by RaveRadbury**
## About The Pull Request
Adds the necessary access to make medbay like science. Genetics already has access like robotics (being lifegiver roles that are separated from the rest of the department), so it was just a matter of making doctors, chemists, and virologists more like one another, access-wise.

Also, Virology access is not given to anyone during skeleton shifts even though every science department role (including genetics) gets xenobio access. That's been corrected.

## Why It's Good For The Game
Science's many jobs and few roles have managed to work out well enough that it hasn't been changed. Science demonstrates that free access between areas can produce better efficiency as other workers can take over abandoned spaces. I've heard a lot of criticism of both medical doctor and chemist roles as being a bit braindead and I think this will address that. The department doesn't have to grind to a halt because someone left their post, no break-in has to occur. Players can take care of interdepartmental concerns somewhat independently, as science does.

Also, if xenobio manages to do fine with having all the other scientists able to access it then viro can handle it. It will be !!FUN!!

## Changelog
:cl:
tweak: all medbay jobs have access to viro during skeleton shifts
tweak: chemist, doctor, and virologist share increased mutual access
/:cl:

### CODE REVIEW

**Comment by Barhandar** [comment]
Remove MD nerf, they're already incompetent and don't need the extra of being unable to clone on top, especially since geneticists might as well be NPCs.

**Comment by ATH1909** [comment]
> Remove MD nerf, they're already incompetent and don't need the extra of being unable to clone on top, especially since geneticists might as well be NPCs.

Will doctors still have the access needed to enter the cloning room, or are you just removing their ability to eject people from cloning pods early?

**Comment by Barhandar** [comment]
Also, the thing with scientists having shared access is that normally, there really isn't that much to occupy themselves with. Xenobio is the only job that actually has enough substance in entirety of sci to occupy players for long time. Bombs and research can be done with one person, nanites can only be done after the rest of the research, experimentor is broken garbage.   
Meanwhile both MDs and (technically) viro _do_ have stuff to do, depending on the shift, they're occupied with healing people/surgeries, and hence don't really need to be shared job. Also, access to viro only has a point when diseases can't have their cure easily seen - that only happens with stealthy diseases, everything else is just one health scan away from being cured.


Also chemistry is medical.

**Comment by ATH1909** [comment]
> Also, the thing with scientists having shared access is that normally, there really isn't that much to occupy themselves with. Xenobio is the only job that actually has enough substance in entirety of sci to occupy players for long time. Bombs and research can be done with one person, nanites can only be done after the rest of the research, experimentor is broken garbage.
> Meanwhile both MDs and (technically) viro _do_ have stuff to do, depending on the shift, they're occupied with healing people/surgeries, and hence don't really need to be shared job. Also, access to viro only has a point when diseases can't have their cure easily seen - that only happens with stealthy diseases, everything else is just one health scan away from being cured.

Or just one trip to the holodeck away from being cured.

**Comment by RaveRadbury** [comment]
I mis-understood cloning access, adjusting my PR

**Comment by ATH1909** [comment]
You should update the OP to reflect that.

@Barhandar Rave's no longer removing cloning access from the default access of doctors; you might want to remove your downthumb now.

**Comment by RaveRadbury** [comment]
Ah whoops, thought I got it all. Now it should be fully updated.

**Comment by Fikou** [comment]
"Also, Virology access is not given to anyone during skeleton shifts even though every science department role (including genetics) gets xenobio access. That's been corrected."
thats because theres no job called xenobiologist thats supposed to only do xenobio, there is for medbay

**Comment by RaveRadbury** [comment]
@Fikou skeleton access basically gives you all department access. This is the same across all departments but service.

**Comment by KetasDotepasto** [comment]
I'm not a fan of giving the medical doctor virology access. As @Fikou said, there is a virologist job, but there isn't a xenobiologist job. 

In addition, on all maps, there is only room for one virologist to work, since if there were 2 of them, they would compete for the Pandemic, which won't be fun for either.

Additionally, because of how viruses override each other, there is no point in having 2 healing viruses going around at once.

So, no, giving the medical doctor virology access will not be fun for either the medical doctor or the virologist. Because virology is different from xenobiology.

**Comment by RaveRadbury** [comment]
This isn't about making people compete for jobs. It's just a bit of redundancy so that people don't have to break into places when someone shirks their duties. Players manage to be respectful with Xenobio even though it clearly could support two scientists. Mutual access also opens up opportunities for people to learn more about their department's jobs, as clearly no one lets assistants in to "learn things".

**Comment by ExcessiveUseOfCobblestone** [comment]
On the fence about viro, It's the only job explicitly made for a single person and...

... being a viro and not being able to do your job because a MD is doing it when they could be healing is crap

... being a MD and making disease but having to give up your work because the viro came in 30 minutes in is also crap

unlike say scientist who aren't entitled to xenobio and, even if they decide to be butts about it, they can still help out since it's setup for multiple users.

**Comment by RaveRadbury** [comment]
@ExcessiveUseOfCobblestone Opening up viro presents opportunities for more virus stuff to occur that 
a. isn't hyper-worked custom viro stuff 
and b. isn't immediately blamable on viro
Currently _any_ virus stuff (including miasma disease) gets blamed on viro, relaxing departmental access helps diffuse that a bit.

Also, considering that you're on the fence and that this PR was made in response/support of #43075 is there any chance this could be tossed in to testmerge with the stasis PR? I could make the necessary adjustments aftwerward.

**Comment by RaveRadbury** [comment]
Seeing as #43075 has been merged, I'll strip out the fully-staffed viro access later today. If it really matters I'll try and PR that individually at a later date.

**Comment by ExcessiveUseOfCobblestone** [comment]
> a. isn't hyper-worked custom viro stuff

That's the point of viro in it's current iteration? 

> b. isn't immediately blamable on viro

That's a symptom of it but it's not really the purpose of why we have skeleton crew.

If it becomes a nuisance we can look at giving it back later, I don't think it's going to come to that though so long as viro isn't changed to be more handling infections instead of making your own healing virus then being MD for the rest of the round.

**Comment by RaveRadbury** [comment]
@ExcessiveUseOfCobblestone so you're saying that general viro access _should_ be removed?

**Comment by ExcessiveUseOfCobblestone** [comment]
I think it's probably reason for both so let's just keep it in and the worse that happens is someone gets mad and reverts it.

**Comment by ExcessiveUseOfCobblestone** [comment]
oh that means I don't have issues with the PR

**Comment by Angustmeta** [comment]
@RaveRadbury I believe this made it so Medical Doctors always have access to virology, regardless of skeleton crew. 

Chemistry also never have access to virology. Need to add virology to "access" as well I suppose.

**Comment by ExcessiveUseOfCobblestone** [comment]
oh no is this the dreaded "minimal access and access are actually flipped" thing

**Comment by ExcessiveUseOfCobblestone** [comment]
crap it is

**Comment by ExcessiveUseOfCobblestone** [comment]
@RaveRadbury I need you to fix this soon or I will when I'm back home.

https://github.com/tgstation/tgstation/blob/c0759780625e1364f9c18b2099dbfb8f5ad74820/code/modules/jobs/job_types/_job.dm#L6-L7

minimal_access is for NORMAL
access is for LOWPOP

**Comment by RaveRadbury** [comment]
@ExcessiveUseOfCobblestone Looking over it, everything is as I intended with the exception of Chemistry not getting skele Viro access. Whoops. I'll do a fix, look it over and tell me if you want me to strip "Full Staff" Viro access or anything else.

**Comment by ExcessiveUseOfCobblestone** [comment]
errrrrr me misread ur entire pr

**Pull request merged**
