### PR TITLE
Cobbduceus 3/X: ERP-Free Tend Wounds (#KeepTheirPantsON)

### PR DESCRIPTION
**Pull request by ExcessiveUseOfCobblestone**
## About The Pull Request

Tend Wounds can now be performed with clothes on, BUT at a 60% decrease to healing.

## Why it's good for the game

eases the yuck of surgery while still encouraging "proper" surgery

## CL

:cl:Cobby Touches Medbay... Again...
add: Keep their pants on! Now Tend Wounds can be done through clothing!
balance: It is less effective to perform Tend Wounds with clothes on.
/:cl:

### CODE REVIEW

**Comment by wesoda25** [comment]
This new medical balancing system is absolutely bizarre to me that now to preserve its integrity, we're actually making tend wounds go through cloning which makes sense bc ???

**Comment by ExcessiveUseOfCobblestone** [comment]
I'm doing this more as a convenience trading off efficacy and not necessarily out of necessity. Not sure what gave you that notion or even what "necessity" there was to begin with...

> we're actually making tend wounds go through cloning which makes sense bc ???

Compared to magic pills that just magically fix all your ailments? I'm so confused how people get bootyblasted about realism in my PRs but we've had snake oil for literal years and none of these people batted an eye(uri) like wtf lol?

**Comment by SynnGraffkin** [comment]
> Compared to magic pills that just magically fix all your ailments?

I mean, you're talking about medicine in 2500 that **_SHOULD_** have options without any side effects compared to the current year, where some medicines have more possible side effects that are worse than what they actually cure. The "Magic" would have been advancements in medical science to that point, and not what we've been given now, which has been **_BLINDLY_** full merged and never test merged.

**Comment by Krysonism** [comment]
I think having to put your trust in the doctor should be part of surgery. No one is going allow the doctor to remove their gamer gear if they can help it.

I think this would be fine if we implemented survey related infections and this gave a hefty infection related penalty.

15% faster healing is not going to compel the patient to remove their jumpsuit.

**Comment by FancyCyclops** [comment]
By the way, the fullmerge was an accident, apparently.

A fatal accident.

**Comment by nemvar** [comment]
A first step would be to fix that broken feature where adjusted jumpsuits are supposed to allow surgery.

**Comment by Mickyan** [comment]
if it's realism you crave we can remove chem patches and sprays being applied over clothes :>

**Comment by Cornarias** [comment]
> Medicines in the real world have nasty side effects including death/blindness/internal bleeding/etc., they're just not hyperbolized for the purpose of video game balance.

Ok, say what you want with regards to everything else, but this irks me. Balance aside, people need to stop believe modern medicine is as remotely dangerous as any would claim.

Hello there, my name is Cornarias. I work in the medical field, specifically in lab work involving identification and cure of patient ailments. Biomedical science is a general term, but that's my degree. That is to say, while I don't prescribe medicine, I am required to understand the effects of countless medications when analyzing samples to understand what the cause of a problem could be. Sometimes, this is medication.

Even a fraction of any of the medications that you have developed have been banned by international law. As in, if suggested the use of even 1 of your medications, with very little exception, and even if it was FAR less harmless, I would quite literally be put up for review of losing my medical license.

The most dangerous medications we currently have access to are for extreme, and I mean _extreme_, ailments which we are literally unable to safely cure any other way. Not only do those require lengthy amounts of time and paperwork, they are also _still significantly safer that functionally any chem that you have drafted_.

Let me break this down.

Medicines causing death: Literally none outside of extreme cancer treatments. Generally, even those don't kill, the cancer does. You will literally have your dosage dropped before they enter lethal levels. Though I'm not an oncologist, but I don't think anyone is here. In essence, these medicines over a prolonged time can cause death, but are only used when death is otherwise guaranteed, and the medication itself will never accelerate that. They're also unique in their function, not standard medication.

Blindness: No medicine has the side-effect of blindness that would be used should that symptom present itself. Of those with such side-effects, the onset of blindness is extremely slow and is only a major issue for long-term use. I cannot think of one that was not banned by the WHO.

Internal Bleeding: Any medication that causes internal bleeding can and will be _thoroughly_ tested. Not just in isolation, it will be administered in small quantities and tested per patient. Because the last thing you _ever_ want is to administer a thinning agent to a patient who doesn't need one. In the case of your chem, if someone is bleeding and / or physically damage via sharp or blunt trauma and I administered an anti-coagulant... _I would, unironically and without humour, be put on trial for criminal charges and face jailtime of at least 5 years._

The tying factor of the above? All of them are _potential side effects_ and not _guaranteed side effects_. They have a chance to occur per patient, and if the side effect occurs, then they are moved to another, safer medication which does the same thing. In real medical treatment we have a lot of options and redundancy to ensure that the least damage possible to the patient is done.

Lastly, this is still a soft 'sim' and RP (though low) at its core. Suspension of disbelief is surprisingly important. It's hard to suspend when I'm giving a bleeding man an anti-coagulant to heal him.

Your effects aren't hyperbolized. They're frustrating in every aspect, and entirely counter-intuitive to even medicine used a century ago.

-----

Sorry, I don't like it when people incorrectly talk about medicine with minimal understanding and spread misinformation. It's already an actual problem we have to handle on a daily basis.

**Comment by Kraseo** [comment]
i thought you yourself said you wanted more realism in medical cobby

**Comment by Cornarias** [comment]
> 
> 
> Are you guys purposefully not reading the "hyperbolized for video game balance" or...?
> 
> Yes, IRL not every medicine requires you to see a doctor immediately after taking it and fucks you sideways. Everyone who is participating in this understands that.

Outside of the fact that it's not even hyperbolized. Also, change "Not every" to "literally all".

Just don't use realism as an argument and I won't be upset that you were wrong.

**Comment by optimumtact** [comment]
okay you are all WILDLY offtopic, can we get back to the PR at hand please

**Comment by optimumtact** [comment]
Take it to the forum adam

**Comment by FancyCyclops** [comment]
Hmmm, these "off topic" comments seem to follow a certain theme.

I wonder what?

**Comment by optimumtact** [comment]
arguing about an unrelated chemistry change that has nothing to do with this PR and can be better addressed in the forum we already have for code feedback.

I'd advise you to not step closer to the cliff edge

**Comment by Cornarias** [comment]
Understandable and fair. I did forget that this was specifically the Tend Wonds PR, not the medical one. I'll be more cautious in future.

**Comment by lolman360** [comment]
cobbymed was a mistake. this is why i play citadel now. realistic chemical reactions for chems > completely doing a med rework in parts which makes it seem like you haven't even planned it out

**Comment by optimumtact** [comment]
have fun on citadel, don't come back

**Comment by ExcessiveUseOfCobblestone** [comment]
If you were looking for realism in medical you should have jumped that ship long before I even started looking at a rework.

**Comment by AdamElTablawy** [comment]
i still maintain the main reason lots of doctors don't do tend wounds is because the tools occupy a fair amount of inventory space and the failure chance makes it annoying to repeat the same step several times and get fucked over repeatedly

this is a decent change but when you combine 'clothes stay on' heal debuff with a stasis bed's 10% fail chance you're going to be spending a fair amount o time repeating the same goddamn step over and over

which is all fine and dandy in a quieter shift but when everything's going to shit and half the station is on fire and there's a blob in engineering-you know, exactly the time when doctors really don't have the opportunity to strip off their patient's clothes to tend wounds because there's 12 people running around screaming in the medbay and they all need to get back to work immediately or everyone dies-then it becomes a time delay that gets everyone killed and i'm pretty sure that's not what you're going for

**Comment by ExcessiveUseOfCobblestone** [comment]
I've done tend wounds on the stasis beds with the default surgical tools with very little failure rate (no sterilizine).

I do carry a set of tools in a dufflebag though but it's not like I need to 2hand anything, even a person fireman carry takes 1 hand and I still have a half of a hand in terms of pulling. with a medibelt, a backpack, and a dufflebag, I don't really see how inventory constraint is an issue.

There ARE some rounds where i'm bottlenecked by materials for a spare set of surgical tools but that's really only happened a couple of times.

**Comment by wesoda25** [comment]
Yeah just throw the tools into a duffelbag and lug it around to stasis beds as need be. Still, medical needs more tools.

**Comment by actioninja** [comment]
> Still, medical needs more tools.

you can print them from the medical lathe, you always have been able to.

**Comment by redmoogle** [comment]
also just use bedsheets in space of drapes if you need to

**Comment by ExcessiveUseOfCobblestone** [comment]
Don't waste plastic on surgical drapes tbh

**Pull request merged**
