### PR TITLE
Fixes railing corner sprite

### PR DESCRIPTION
**Pull request by KathrinBailey**
## About The Pull Request
Fixes that those annoyingly misaligned corners.

## Why It's Good For The Game
Judge for yourself. The shading is no longer inverted, and the railings align properly.
image
In case you aren't seeing it...
image
image

## Changelog

:cl:
imageadd: Railing corner sprites fixed to align with the railings.
/:cl:

### CODE REVIEW

**Comment by Profakos** [comment]
Wasn't this fixed in #73314?

**Comment by KathrinBailey** [comment]
goddamn heck it's been like like this for over a year and now I've finally gotten around to it someone's done it a week ago.

**Comment by Profakos** [comment]
I mean, maybe it has regressed already?

**Comment by lessthnthree** [comment]
No, we just haven't merged it downstream yet.

**Pull request closed without merging**
