### PR TITLE
Removes cortical borers

### LINKED ISSUE #25564: Borers that have taken control of their hosts see space as white

### LINKED ISSUE #25567: Borers who exit an exploded host are in an inconsistent state
1) Was borer inside human.
2) Someone puts an (exploding?) cigar on them.
3) They explode.
4) "The cortical borer bursts out of Host Name!"
5) My UI buttons still think I'm inside a host, so I can't do anything.

### LINKED ISSUE #25568: Spawned borers do not have scaling population objectives
Normally, if the borer event happened, it'd scale the required "escape with host" objective based on station population.

But if admins just straight up spawn a borer (which is generally what happens these days, because the event is disabled atm), it's always at 10.

### LINKED ISSUE #25700: Borers don't show up in Check Antagonists

### LINKED ISSUE #25701: Borers can become servants of ratvar
@ChangelingRain weeeeeew

>ADMIN: Durkel/(Tim Ebow) (FLW): >if you convert a player who's being controled by a borer(?|F) you convert the borer and not the host(?|F)

### LINKED ISSUE #28555: Ashstorms and cortical borers
[Note]: # (Please enter the commit hash and active testmerge numbers from the "Show Server Revision" verb if you can. If you believe the issue to be caused by a testmerge, please report it in its relative PR thread. State what the issue is from a "whats wrong" prospective. Issue reports should clearly allow maintainers to understand whats wrong and how to test/reproduce if that is not obvious. Avoid ambiguity. Start your issue report below both of these lines (or remove them))

[Admins]: # (If you are reporting a bug that occured AFTER you used varedit/admin buttons to alter an object out of normal operating conditions, please verify that you can re-create the bug without the varedit usage/admin buttons before reporting the issue.)

Server revision: 
https://github.com/tgstation/tgstation/commit/d0be33f480910f03db2b71736cab1f40c357679b

Cortical borers inside a host who walks through an ash-storm just dies, no matter if they pump their host full of healing chems.

### LINKED ISSUE #28731: Cortical borer + changeling +monkey devolve = death?
[Note]: # Based off origin/master commit: cb4ca0

[Admins]: # (If you are reporting a bug that occured AFTER you used varedit/admin buttons to alter an object out of normal operating conditions, please verify that you can re-create the bug without the varedit usage/admin buttons before reporting the issue.)

Uh, roundstart I was a traitor, but I traded to be a borer. I jumped into a ling, and we had fun for a while, but eventually sec caught on. at which point, she got handcuffed, and when she monkied to escape, we both got insta-ghosted.

### PR DESCRIPTION
**Pull request by Cyberboss**
Disabled live, questionably fun, buggy as hell in their implementation, and I don't want to even begin trying to fix them. If someone can begin to close these issues I'll change my mind.

Closes #28731
Closes #28555
Closes #25701
Closes #25700
Closes #25568
Closes #25567
Closes #25564

:cl:
del: Cortical borers have been removed
/:cl:

### CODE REVIEW

**Comment by Repukan** [comment]
They should be made more antagonistic if they're ever readded.

Free chem dispenser with revive is only funny so many times. It's a pain because it's a faux conversion antag (most of the playerbase is not aware in how to fight back or resist mind take over) and dealing with them is just awful.

**Comment by Iamgoofball** [comment]
Didn't we already remove these?

**Comment by ExcessiveUseOfCobblestone** [comment]
Ingame yes

**Comment by kevinz000** [comment]
they're not fun to play with.
>oh, so if I don't valid them i'm literally letting antagonists brainwash everyone, but if I do, everyone INCLUDING those who aren't borer'd will try to kill me because why the fuck not

>Yet if I go full powergame HoS and wreck everyone who tries to prevent me from removing their borers, I'll be hated for it

>Yet if I don't do it and let the borers multiply, I'll be called out for not doing my job

lose-lose scenerio, remove kebab.

**Comment by Supermichael777** [comment]
These were too cancer for almost every other code-base. VG even made them neutral faction, i.e. dunk them if their bothering you, effectively how we treat drones, because of how cancerous them having antag status was (and removed mind control because holy shit why) along with their more direct Parasyte ripoff getting the same treatment.

**Comment by Durkel** [comment]
so long a gay bowser, you won't be missed.

**Comment by Bawhoppen** [comment]
:+1:  The idea was interesting and seemed good on other codebases, but it just doesn't work on tg because of our powergame element

**Comment by lzimann** [comment]
No one showed even a minimum interest in fixing any of the issues borer have. If anyone really wants them, they should probably rewrite and rethink how borers are.

**Comment by Repukan** [comment]
Based

**Comment by PraiseRatvar** [comment]
changed the wiki i guess https://tgstation13.org/wiki/Cortical_Borer

**Pull request merged**
