### PR TITLE
[ready]rcd upgrades

### PR DESCRIPTION
**Pull request by Tlaltecuhtli**
:cl: 
add: rcd disk that gives rcd computer frame and machine frame designs
/:cl:

### CODE REVIEW

**Comment by Shadowflame909** [comment]
I think it should be the CE's RCD only.

Portable autolathe baby

**Comment by tuypo1** [comment]
The power creep is real

**Comment by OverlyGeneric** [comment]
to prevent power-creep virtue signallers, I would recommend doing a separate PR requiring RCDs to have ID-card locks.

if we're going for the CE's RCD only. that is.

**Comment by PKPenguin321** [comment]
@OverlyGeneric more like OverlyDismissiveOfGenuineCriticism

**Comment by Tlaltecuhtli** [comment]
no those are dumb ideas

**Comment by 81Denton** [comment]
You must be high if you think that this is powercreep with a 5k points node locked behind advanced engineering

**Comment by necromanceranne** [comment]
That shit ain't being touched for a good while if it's that far into the tech tree unless some dickhead rushes it.

**Comment by Cyprex** [comment]
This is a significant buff due to being able to construct multiple machine frames simultaneously. However, I believe that making construction easier isn't necessarily a bad thing, as it currently takes a while.

**Comment by Poojawa** [comment]
if you wanna balance the "power creep" just remove the ability to feed glass and shit into it, back to RCD Ammo only.

**Review by SpaceManiac — APPROVED** [review]

**Comment by YakumoChen** [comment]
I don't even get why anyone would think this is that useful to have in the first place

**Pull request merged**
