### PR TITLE
cuffsnapping is on right click

### PR DESCRIPTION
**Pull request by carlarctg**
## About The Pull Request

title

## Why It's Good For The Game

OOC: Blard of Jard: I was trying to cut a cargo tech's leg off for a spy bounty, but instead of just cutting his leg with it targetted on harm intent, it immediately cut his ties and he mag dumped me with his laz gun.

## Changelog

:cl:
fix: you now snip cuffs with right click to prevent accidental cuts
/:cl:

### CODE REVIEW

**Comment by JohnFulpWillard** [comment]
I think this might hurt the features visibility, maybe it works be better to move it to right click and give it context tip, so it would be a more intentional and visible action?

**Comment by carlarctg** [comment]
oke

**Comment by carlarctg** [comment]
image

**Comment by carlarctg** [comment]
image

**Pull request merged**
