### PR TITLE
Comment war continues

### PR DESCRIPTION
**Pull request by optimumtact**
shake it off

### CODE REVIEW

**Comment by duncathan** [comment]
...is that really unnecessary? I thought that that comment was saying that despite the special things the box can do, it's still just a box so it's weak and flimsy

**Comment by optimumtact** [comment]
yes it's a completely useless comment

**Comment by Iamgoofball** [comment]
:-1:

**Comment by Incoming5643** [comment]
https://www.youtube.com/watch?v=msf_J3QIXMg

But whatever man

**Comment by freerealestate** [comment]
was this pr really worth the effort it took to make

what does this actually achieve

**Comment by Dorsisdwarf** [comment]
This will lower the filesize by about 10 bytes.

**Comment by optimumtact** [comment]
I hate fun, so this gives me great personal pleasure

**Comment by optimumtact** [comment]
Would you prefer I made space slow again because I can do that instead.

**Comment by freerealestate** [comment]
>This will lower the filesize by about 10 bytes.

it's part of an ongoing "war" apparently, the purpose of which still remains a mystery

**Comment by pudl** [comment]
If you try to make space slow, I'm going to make you slow, but instead of coding it, it'll be with my fists.

**Comment by JJRcop** [comment]
@freerealestate 
>was this pr really worth the effort it took to make

Actually it might have taken a bit less effort than you might think, the branch name is "patch-1", that likely indicates that oranges used the GitHub web editing interface to make this change, since that is how the web interface names the resulting git branches. 
Using the web interface is a lot simpler than making the branch yourself, editing the file, adding to index, committing, and pushing, which is what normal procedure is.

**Comment by Incoming5643** [comment]
at least this got a pull request, the rest of the comments got destroyed in a direct merge https://github.com/tgstation/-tg-station/commit/40e97a5f7b25294b84c4b0e3f6977e0858877218

(I thought people weren't supposed to do that)

**Comment by optimumtact** [comment]
@pudl fight me irl, 1v1, fox only

**Pull request merged**
