### PR TITLE
New clockwork wall/floor sprites

### PR DESCRIPTION
**Pull request by ChangelingRain**
New sprites courtesy @SkowronX
space station 13 2016-05-30 214126
Clockwork walls now make a noise when adding a component to a cache. Clang.
Also includes glows for wall/floor spawning, but getting a pic of those is absolutely a pain in the butt.

### CODE REVIEW

**Comment by Anonmare** [comment]
Pretty, wish there were door sprites though or Clock airlocks.

**Comment by ChangelingRain** [comment]
There are but they don't work with our airlock sprite system(yet)

**Comment by Jordie0608** [comment]
Looks quite reminiscent of Thief

**Comment by Xhuis** [comment]
Coincidentally, this is also done in #18085 - sorry...

**Comment by ChangelingRain** [comment]
I already fixed the conflicts so no worries.

**Comment by xxalpha** [comment]
If you need help making the airlocks ask me or WJ in irc.

**Comment by ChangelingRain** [comment]
If you want to convert these airlocks, sure go for it http://puu.sh/paX5U/91d2231735.dmi

**Comment by ChangelingRain** [comment]
Possible floor sprite alteration;
space station 13 2016-05-31 153424

**Pull request merged**
