### PR TITLE
Fixes an issue with the spectral blade not properly detecting all orbiters

### LINKED ISSUE #47302: Spectral Blades are still fucked
## Reproduction: Orbit spectral blade, get yoinked back upon trying to fly away or orbiting something else.

This apparently was reported some months earlier but wasn't nailed down. I'd like to further add that it isn't just orbiting thats broken. The blade itself did zero damage with 10+ ghosts orbiting. This was even with the blade having a +5 modifier from event wizard memes. Each strike said it had 0 vengeful spirits despite most of dchat orbiting them. Getting yoinked back did not put you into the orbit animation, but rather forced your icon on top of them. The blade changed owners and the orbit followed the blade and not the previous owner.

### PR DESCRIPTION
**Pull request by 4dplanner**
## About The Pull Request
set parent.orbiters on register for orbiting component

## Why It's Good For The Game
Should hopefully fix #47302, but it's hard to tell with localhost testing

## Changelog
:cl:
fix: spectral blade should now behave better
/:cl:

### CODE REVIEW

**Comment by TheChosenEvilOne** [comment]
fucked up the :cl: there

**Comment by Fikou** [comment]
does it fix the vengeful ghosts not existing

**Comment by 4dplanner** [comment]
On localhost with 1 orbiter I was getting "hits with the force of 1 vengeful spirit" as expected.

**Comment by Ty-the-Smonk** [comment]
Why goose

**Pull request merged**
