### PR TITLE
Makes the hover overlays toggleable

### PR DESCRIPTION
**Pull request by BeeSting12**
Closes #39819 

:cl: BeeSting12
tweak: Storage overlays that tell you if you can put an item somewhere are now a preference.
/:cl:

See #39819 for why.

Not sure if I did this properly.

### CODE REVIEW

**Comment by optimumtact** [comment]
no

**Comment by MrDoomBringer** [comment]
based orange

**Comment by BeeSting12** [comment]
@optimumtact why?

**Comment by optimumtact** [comment]
because I think this is a good change and you will get over the UI change in a short order

**Comment by wesoda25** [comment]
Because mother oranges knows best with all her recently logged hours in the game.

**Pull request closed without merging**
