### PR TITLE
Replaces the stinger for emagged comms console announcements with a sinister 80s-style synth riff

### PR DESCRIPTION
**Pull request by Metekillot**
## About The Pull Request

Right now the emagged console sound is just a slowed down version of the normal sound; I think it'd be more soul if it were an espionage-y dark synth riff, like some cheesy shit you'd hear in Deus Ex whenever the villain gets revealed.

https://github.com/user-attachments/assets/6042f57f-e6cb-4745-9a55-bacf471e8730

Pulled off of pixabay and trimmed and pitched
## Why It's Good For The Game

Cheesy scifi synth riffs seem more on-brand than slowing down another noise.
## Changelog
:cl: Bisar
sound: Syndicate comms consoles now have a different noise for announcements.
/:cl:

### CODE REVIEW

**Comment by Iamgoofball** [comment]
what the fuck is "pixabay"

**Comment by LemonInTheDark** [comment]
Requires proper credit, is the license for this compatible?

**Comment by Pumpkinoe** [comment]
this feels kinda super obnoxious? idunno if it's just me but it feels loud and scratchy versus the deep and communicative announcement sound effect of the current emagged comms console. it feels like this'll start playing to everyone on station and they'll wonder what the hell triggered it?

**Comment by nianjiilical** [comment]
its a cool sound but i think its a bit long and, like, 'flat'?

i think sounds for station announcements should generally be very short and punctual, like an auditory punch of Hey Listen, while this is a very prolonged almost ambient sound that i can imagine a machine making every so often to fill air as opposed to something that grabs your attention for a second or two

**Comment by Metekillot** [comment]
> its a cool sound but i think its a bit long and, like, 'flat'?
> 
> i think sounds for station announcements should generally be very short and punctual, 

You make a good point, I rushed this too much because I redid it at the last minute 

> Requires proper credit, is the license for this compatible? 

License is compatible but I lost where I snatched the sample

**Pull request closed without merging**
