### PR TITLE
Fixes tool ingredients in table crafting

### LINKED ISSUE #9523: Pneumatic cannon construction fail with non-standard welders.
Reported by Demonfiren and tested out a bit.

Pneumatic cannon construction reports 'construction failed' if attempted with industrial welders or the welders with the larger tanks etc. Only normal welders seem to work. I don't think it's intentional.

### PR DESCRIPTION
**Pull request by ghost**
Is not a fix for #9523, for example allows use of an industrial welder for the flamethrower but does not allow a subtype/child/thing of screwdriver e.g. screwdriver/nuclear to make it with. I'll continue to try and work something out but until then this shouldn't be merged.

This should mean using something that inherits along the path of the intended item used in any table crafting recipe can work instead if desired by said table artisan.

**Final words,** the code already did what I thought this changed code (that's a laugh, it wound up being almost identical at the end) did instead. I do not know how to do what #9523 is asking for, I do not understand the majority of the code in this file, I'll leave this for someone else who knows what they're doing since the entirety of this was me asking two other people "What do?" when I hadn't even read the issue correctly.

### CODE REVIEW

**Comment by CosmicScientist** [comment]
Thanks @optimumtact and @MrPerson for the help!

**Comment by CosmicScientist** [comment]
This causes a bug where unfortunately you do not require any tools to make something, e.g. removing the pin from a gun with your bare hands instead of with a screwdriver.

It'd be nice if #9523's Easy Fix tag could be reassessed because I'm not entirely sure it's easy at least for a code illiterate to attempt such as me.

**Comment by optimumtact** [comment]
Hey no, don't give up, I'm fairly certain it's caused by the returning of the length of the array instead of true/false if it found all the right tools.

refactor it to be 

	for(var/needed_tool in R.tools)
		var/potential_tool = locate(needed_tool in possible_tools)
		if(potential_tool)
			possible_tools.Remove(potential_tool)
               else
                        return false
	return true

**Comment by CosmicScientist** [comment]
Alright I'll try that and if I can't get it to work I'll come back to coderbus. I'll reopen it as and when I can't find a bug when fiddling with testing.

**Comment by CosmicScientist** [comment]
Fixing in a second...

**Comment by CosmicScientist** [comment]
Aaaaand then I just realised how this flops apart even though it works.

**Pull request closed without merging**
