### PR TITLE
Kills off the last of the old shuttle walls

### PR DESCRIPTION
**Pull request by Bawhoppen**
tedium: the PR

I had a weird error with mapmerge lets hope it worked

### CODE REVIEW

**Comment by Bawhoppen** [comment]
okay well I will try again later

**Comment by xxalpha** [comment]
```_maps/map_files/BirdStation/BirdStation.dmm:22546:error: undefined type: /turf/closed/wall/shuttle/interior
_maps/map_files/BirdStation/BirdStation.dmm:22547:error: invalid variable name: icon_state
_maps/map_files/BirdStation/BirdStation.dmm:22549:error: unknown type
_maps/RandomRuins/LavaRuins/lavaland_surface_animal_hospital.dmm:221:error: undefined type: /turf/closed/wall/shuttle/smooth/nodiagonal
_maps/RandomRuins/LavaRuins/lavaland_surface_animal_hospital.dmm:222:error: invalid variable name: baseturf
_maps/RandomRuins/LavaRuins/lavaland_surface_animal_hospital.dmm:224:error: unknown type
_maps/RandomRuins/LavaRuins/lavaland_surface_animal_hospital.dmm:241:error: undefined type: /turf/closed/wall/shuttle/smooth/nodiagonal
_maps/RandomRuins/LavaRuins/lavaland_surface_animal_hospital.dmm:242:error: invalid variable name: baseturf
_maps/RandomRuins/LavaRuins/lavaland_surface_animal_hospital.dmm:244:error: unknown type
_maps/RandomRuins/LavaRuins/lavaland_surface_animal_hospital.dmm:246:error: undefined type: /turf/closed/wall/shuttle/smooth
_maps/RandomRuins/LavaRuins/lavaland_surface_animal_hospital.dmm:247:error: unknown type
_maps/shuttles/emergency_box.dmm:49:error: undefined type: /turf/closed/wall/shuttle/interior
_maps/shuttles/emergency_box.dmm:50:error: invalid variable name: icon_state
_maps/shuttles/emergency_box.dmm:52:error: unknown type
_maps/shuttles/cargo_box.dmm:92:error: undefined type: /turf/closed/wall/shuttle/interior
_maps/shuttles/cargo_box.dmm:93:error: invalid variable name: icon_state
_maps/shuttles/cargo_box.dmm:95:error: unknown type```

**Comment by Bawhoppen** [comment]
I fixed those ones though I thought, oh well, I'll try again later

**Comment by xxalpha** [comment]
**BWOINK**

I see you have some map conflicts, have you tried using the map conflict fixer?

**Comment by Bawhoppen** [comment]
what is the map conflict fixer

**Comment by xxalpha** [comment]
It's in the map merge folder.

**Comment by Bawhoppen** [comment]
no I mean how does it work also I have another problem thats a bigger issue

**Comment by Bawhoppen** [comment]
I mean, how does it work, and more importantly, how do I use it?

**Comment by xxalpha** [comment]
There's a readme.

**Comment by Bawhoppen** [comment]
okay this if FUBAR I must start fresh

**Pull request closed without merging**
