### PR TITLE
Makes the lich revive beam light green

### PR DESCRIPTION
**Pull request by ChangelingRain**
THEME! DESIGN! COLOR CHOICES!
space station 13 2015-11-08 230550

### CODE REVIEW

**Comment by Incoming5643** [comment]
the last two frames are set at 1 second instead of .1 second like all the other frames. Not sure if intentional

**Comment by Anonus** [comment]
Oh, dangit.

**Comment by Jordie0608** [comment]
Looks almost brown, could you make it a brighter green?

**Comment by WJohn** [comment]
Yeah I'd prefer a slightly brighter green. It's too dark.

**Comment by Anonus** [comment]
Yeah okay sure, it now matches the necrostone, roughly.

**Comment by Dorsisdwarf** [comment]
@Anonus is this ready to merge?

**Pull request merged**
