### PR TITLE
You can now wear emags as IDs and auto-hack doors!

### PR DESCRIPTION
**Pull request by ghost**
You can now wear emags in your ID slot. Doors will be automatically emagged if you bump in them when wearing an emag.

🆑
rscadd: Syndicate agents figured out that they can attach their cryptographic sequencers on jumpsuits and fry airlocks' ID scanners more easily.
/🆑

port of https://github.com/yogstation13/yogstation/pull/2291

### CODE REVIEW

**Comment by Supermichael777** [comment]
This seems more irritating than absolutely necessary.

**Comment by GunHog** [comment]
It carries the risk of the user being a lot more obvious, first because the user is now at risk of accidentally breaking airlocks with intent, and even worse, **someone examining you can see that you are wearing an emag.**

**Comment by kevinz000** [comment]
people smashing emags into every airlock they see is bad enough
you don't need to make it automatic. :-1:

**Comment by awesine** [comment]
"hurr hurr buffing a traitor item with an obvious and nice feature that carries with it a high risk and reward scenario is bad"

**Comment by PsyCommando** [comment]
Quick question, how do you fix a trail of fried doors? I mean, you have to spend at least 2 minutes dismantling the door, remove the fried airlock board, slapping in a new airlock board, and then reassemble it. Then the guy with the emag just runs past through the second you're done, and you gotta do that again.. 

Sure they could do that already, but since they have to do it manually, it slows them down a tiny bit, and deters them from frying more than needed, because people are lazy.

Also, is it me, or the emag is already basically the most overpowered piece of gear?

**Comment by MoreRobustThanYou** [comment]
@PsyCommando or just, carry a stack or 2 of metal, deconstruct door with RCD, set door access on RCD, reconstruct door. Repeat. Refuel RCD with metal stacks.

**Comment by kevinz000** [comment]
@MoreRobustThanYou now repeat that about 300 times because emag-sprees are notoriously hard to stop due to the sheer amount of open doors, even more so if they have noslips or a spacesuit.

**Comment by awesine** [comment]
@kevinz000 
or you just
fingerprint
the doors

i thought you were a sec main and knew how security mechanics actually worked

**Comment by PsyCommando** [comment]
@MoreRobustThanYou Hmm, I guess that's true. 

But still, its a bit much to expect 1 maybe 2 engineers to bother repairing a lot of doors on the station. Often they mostly just fuck-off in space and usually die. So it all goes down to other depts trying to fix it manually. Same with burned-out lights. (which janitors should be also fixing, but they don't)

**Comment by MoreRobustThanYou** [comment]
@Repukan yes but it's hard to see if someone's carrying an emag unless they're actively emagging shit.

**Comment by awesine** [comment]
the one disadvantage of this PR is that you wear it on your ID slot and is incredibly noticeable. this adds one way of countering it

**Comment by PsyCommando** [comment]
@awesine  I wouldn't consider it a disadvantage in itself. Since it would also have the effect of making you anonymous and still giving you full access.

**Comment by ShizCalev** [comment]
👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍

**Review by Cyberboss — APPROVED** [review]

**Comment by PKPenguin321** [comment]
thanks i hate it

**Comment by Kerbin-Fiber** [comment]
I only down and upvoted for this because I made the numbers 6 9

**Comment by Qbopper** [comment]
emagging doors is annoying as fuck and this means you can just have it in your pocket and run around emagging doors while also not having it in your hand where it can be seen or disarmed or dropped or whatever

**Comment by awesine** [comment]
@Qbopper you can see the ID slot of people when you examine them

**Comment by ExcessiveUseOfCobblestone** [comment]
The elephant in the room is that you get a free hand slot.

If the item was already conspicuous, how does making it slightly more conspicuous (but not really because an inhand sprite > doing the shift click litmus test) justify the buffs?

**Comment by Time-Green** [comment]
Just gonna copy my opinion from the original PR

LETS ADD ALL ACCES BUT IT COMPLETELY DESTROYS ALL THE DOORS AND ITS ABSOLUTELY HORRIBLE TO FIX!! WALK AGAINST A DOOR? ITS BROKEN FOREVER HAHAH RUN INTO ALL THE DOORS MAGICAL MAGNET MIND TRICKS DESTROY ALL THE DOORS YOU ARE UNSTOPPABLE RIP ENGINEERS OR ANYONE TRYING TO PRESERVE AT LEAST A LITTLE ORDER BECAUSE FUCK ALL SOME ASSISTANT LITERALLY HAS AN AUTO EMAG EMAGGING ALL THE DOORS HE EVEN THINKS ABOUT TOUCHING BECAUSE WOE THATS A GOOD IDEA WEW YEAH

**Comment by awesine** [comment]
LETS ADD SECURITY BUT IT COMPLETELY DESTROYS ANTAG STEALTH AND ITS ABSOLUTELY HORRIBLE TO FIX!! NOT WEARING GLOVES? YOU'RE FUCKED FOREVER HAHAH TOUCH EVERYTHING MAGICAL MAGNET MIND TRICKS FIND YOUR FINGERPRINTS YOU ARE DEAD INSTANTLY RIP TRATIROS OR ANYONE WITH AN ANTAG ROLE BECAUSE FUCK ALL SOME DETECTIVE LITERALLY HAS AN AUTO FINGERPRINT SCANNER GETTING YOUR STUPID FUCKING DNA HE EVEN THINKS ABOUT TOUCHING BECAUSE WOE THATS A GOOD IDEA WEW YEAH

**Comment by awesine** [comment]
do you want me to make more i can make more

**Comment by awesine** [comment]
LETS ADD GUNS BUT IT COMPLETELY DESTROYS COMBAT AND ITS ABSOLUTELY HORRIBLE TO COUNTER!! DON'T HAVE ADRENALS? YOU'RE FUCKED FOREVER HAHAH STUNNED FOR 20 SECONDS MAGICAL TASER MIND TRICKS GET SHOT ONCE YOU ARE DEAD INSTANTLY RIP ASSISTANTS OR LITERALLY ANYONE TRYING TO FIGHT SECURITY BECAUSE FUCK ALL SOME SECURITY LITERALLY SPAWNS WITH AN RANGED STUN STUPID FUCKING TAZER HE EVEN THINKS ABOUT TOUCHING BECAUSE WOE THATS A GOOD IDEA WEW YEAH

**Comment by awesine** [comment]
LETS GIVE THE RD ARMOUR BUT IT MAKES HIM INVINCIBLE AND TELEPORTS HIM AWAY WHEN YOU HIT HIM AND ITS ABSOLUTELY HORRIBLE TO COUNTER! BUMP INTO THE RD? HE JUST TELEPORTED AWAY MAGICAL BLUESPACE MIND TRICKS CAN NEVER BE KILELD RD IS UNSTOPPABLE RIP ANTAGS OR ANYONE TRYING TO ATTACK THE RD BECAUSE FUCK ALL HE LITERALLY SPAWNS WITH IT IN HIS LOCKER HE EVEN THINKS ABOUT WEARING BECAUSE WOE THATS A GOOD IDEA WEW YEAH

**Comment by awesine** [comment]
LETS ADD A ROLE BUT HIS LITERAL GOAL IS TO KILL PEOPLE AND COMPLETE OBJECTIVES AND HE GETS MAGICAL TRAITOR ITEMS TOO!! ARE YOU HIS OBJECTIVE? HAHA YOU ARE DEAD HE IS GIVEN YOUR NAME MAGICAL UPLINK MIND TRICKS DESTROY ALL OBJECTIVES HE IS UNSTOPPABLE RIP SECURITY OR ANYONE TRYING TO PRESERVE AT LEAST A LITTLE ORDER BECAUSE FUCK ALL SOMEFUCKFACE LITERALLY ROLLED ANTAG AND HE CAN DO WHATEVER HE WANTS!!

**Comment by awesine** [comment]
LETS ADD A NEW TYPE OF ANTAG BUT IT CAN LTIERALLY CONVERT YOU TO BE AN ANTAG!! GET FLASHED? YOU'RE NOW A REV GO KILL ALL THE FUCKING HEADS MAGICAL ANTAG FLASH TRICKS KILL ALL THE HEADS YOU ARE UNSTOPPABLE RIP SECURITY OR ANYONE TRYING TO PRESERVE AT LEAST A LITTLE ORDER BECAUSE FUCK ALL SOME CLOWN HAS A REVOLUTIONARY FLASH FLASHING EVERYBODFY HE EVEN THINKS ABOUT FLASHING BECAUSE WOE THATS A GOOD IDEA WEW YEAH

**Comment by awesine** [comment]
LETS ADD NEW ATMOS GASSES BUT IT COMPLETELY MAKES PLASMA AND NOW ATMOST TECHS CAN DESTROY THE STATION EASIER!! RUN INTO TRITIUM? YOU JUST MELTED IN 0.5 SECONDS HAHAH RELEASE TRITIUM EVERYWHERE MAGICAL GAS MIND TRICKS MELT THE STATION YOU ARE UNSTOPPABLE RIP ENGINEERS OR ANYONE TRYING TO NOT DIE BECAUSE FUCK ALL SOME ATMOS TECH LITERALLY HAS A GAS 10X STRONGER THAN PLASMA BECAUSE WOE THATS A GOOD IDEA WEW YEAH

**Comment by awesine** [comment]
LETS HAVE PLAYER-CODERS BUT IT COMPLETELY DESTROYS GAME BALANCE AND ARE ABSOLUTELY HORRIBLE TO BAN!! KILL A CODER? ITS NERFED HAHAH KILL ALL THE CODERS MAGICAL GITHUB MIND TRICKS NERF COMBAT YOU ARE UNSTOPPABLE RIP ROBUST PEOPLE OR ANYONE TRYING TO DO SOMETHING BECAUSE FUCK ALL SOME GOT SALTY AND IS NERFING EVERYTHING HE EVEN THINKS ABOUT NERFING BECAUSE WOE THATS A GOOD IDEA WEW YEAH

**Comment by awesine** [comment]
LETS ADD REPLACE RND BUT IT COMPLETELY MAKES SCIENTIST BORING AND ITS ABSOLUTELY HORRIBLE TO FIX!! TRY TO DO RND? HAHA YOU SIT AT A CONSOLE PLAYING COOKIE CLICKER FOR AN HOUR MAGICAL COMPUTER MIND TRICKS SUPER BORING YOU ARE WORTHLESS RIP SCINEITST OR ANYONE TRYING TO DO RND BECAUSE FUCK ALL SOME CODER HAS A PR NERFING ALL THE SCIENCE ANYTIME HE EVEN THINKS ABOUT TECHHWEBZ BECAUSE WOE THATS A GOOD IDEA WEW YEAH

**Comment by kevinz000** [comment]
@awesine it's not hard to fingerprint doors it's hard to catch someone when they're running around in maint with every door emagged, and here I thought you played.
Wait, you can't even play anymore 🤔

**Comment by Cyberboss** [comment]
Do more and I'm locking this PR

**Comment by ExcessiveUseOfCobblestone** [comment]
@awesine was sabotaging a pr you prefer part of your plan?

**Comment by RogueSteampunker** [comment]
>auto-hacking doors
>doors are fucking pains to repair
>no reasonable explanation WHY it is you'd want this

Please tell me you aren't serious? Cause I can't imagine this is anything but Robustin waiting to pull a "skewium in the smoke machine on the shuttle" gag, where he runs around mass-emagging door cause "haha le memes"

Yakkity-saxxing wth an emag just doesn't work due to the pause, and wearing an emag is a sure-fire way to get every assistant in a station-wide radius ready to buttfuck your tator ass. This is nothing but asking for assistants (and robustin) to mass emag doors for a quick shuttle call.

So, no thanks

**Review by Jalleo — CHANGES_REQUESTED** [review]
This is just flat out bad unless it somehow wears out the emag doing this. It literally will just cause a greytider that gets their hands on this to be MUCH WORSE. 

SO MUCH WORSE.

I have been a chief engineer fixing doors after EMAG sprees it takes longer than the round itself to fix the doors. That is if the hour takes a HOUR and they did it at the start of the round. ALSO people using this can literally go emag in ID RUN TO ARMORY STEAL ARMORY. WITHOUT having to manage their hands. 

This isnt just powercreep its SERIOUS powercreep. They can also go fuckup the SM by opening the doors to it VIA emag. How you gonna stop em. A TASER? the round started a minuite ago no sec engineer. (It would be worse if they open a can of something harmful right there too. No time to save the engine then....)

**Comment by Tlaltecuhtli** [comment]
can i emag borgs by buckling on them

**Comment by DaxDupont** [comment]
@RogueSteampunker @MoreRobustThanYou is not @Robustin

**Comment by KorPhaeron** [comment]
I don't see a reason to buff what is already the best traitor item in the game

**Pull request closed without merging**
