### PR TITLE
Fixes Efficiency Still Being a Thing on Circuit Imprinter

### PR DESCRIPTION
**Pull request by Fox-McCloud**
Fixes efficiency still being a thing on the imprinter---for reagents.

### CODE REVIEW

**Comment by Iamgoofball** [comment]
This is intentional by kor, r&d is hell without this

**Comment by Fox-McCloud** [comment]
Peculiar...odd that it was removed from the protolathe, but not the circuit imprinter.

**Comment by Core0verload** [comment]
Kor explicitly stated that acid being reduced with upgrades is intentional. You don't need mining to get acid, it costs nothing to produce, it just adds inconvenience to RnD work.

**Comment by KorPhaeron** [comment]
yeah, circuit imprinter is just tedium/timegate, they've already got infinite of it from roundstart

**Comment by Fox-McCloud** [comment]
@KorPhaeron 

Thanks for clearin' that up, wasn't aware.

**Pull request closed without merging**
