### PR TITLE
Floating animation and life() fixes.

### LINKED ISSUE #4567: Floating animation is not properly reset
Examples are wizard teleportation/jaunts, some fiddly stuff with engineers (I regularly see 'floating' hardsuit engies after they set up singulo mid-room and with gravity on), and possibly other non-movement transitions between gravity and nograv areas.

### LINKED ISSUE #5969: Spawning in zero-G doesn't result in floating
When you latejoin and spawn in the arrivals shuttle, if the station is in zero-G you don't start by floating. This makes it unclear why you're unable to move. Not until you throw an object or are otherwise moved from the tile you spawned on do you start to float up and down on the spot, indicating you're in a zero-G environment.

### LINKED ISSUE #6599: Humans lying in zero-G don't float properly
Sorry if this has already been reported, it's been around for awhile now. Human mobs, when prone in zero gravity, don't bob up and down like standing humans. Instead they float upwards further than standing humans do and then appear back at the bottom of the arc with no animation connecting the movement. It looks strange.

### PR DESCRIPTION
**Pull request by phil235**
- Fixes floating animation not updating correctly.
  Fixes #6599
  Maybe fix #4567 
  Fixes half of #6123
  Fixes #5969 
  The fix has a flaw though, in no gravity the falling to the ground & getting up animations can sometimes be skipped (and you look like you just instantly go from lying to standing).
- Makes life() procs for mob/living/carbon mobs more object oriented.

### CODE REVIEW

**Comment by RemieRichards** [comment]
>Makes life() procs for mob/living/carbon mobs more object oriented

I got 90% through doing that once, but I literally went mad trying to work out what I had and hadn't finished.

To you though, :+1:

**Comment by phil235** [comment]
I didn't touch any of the subprocs (handle_regular_update(), etc..), so there's still a fuckload of copy pasta there. And I didn't touch silicons and simple animals either.

**Comment by RemieRichards** [comment]
Ah well, I DID do that :P (Still, good work phil)

**Comment by WJohn** [comment]
This has been one of the ugliest and easiest to manifest pile of bugs we've had for ages.

**Comment by optimumtact** [comment]
Possible fixes #6123 although I accidentally lost the images being shown to demonstrate it.

**Comment by phil235** [comment]
It only fixes half of 6123. You can still get the large pixel shift by spamclicking the closet open and closed, but the bug isn't reliable (you really need to spamclick to counter the reset effect of life(), I only managed to get a max shift of 3 tiles before missing a click or getting tired) and you automatically get back to your original position if you stop spamclicking whether you leave the closet open or closed.

**Pull request merged**
