### PR TITLE
100 POSTS ITT REMOVES LIZARDS

### PR DESCRIPTION
**Pull request by Iamgoofball**
:cl:
del: 100 posts ITT removes lizards https://tgstation13.org/phpBB/viewtopic.php?f=55&t=7250 WE DID IT REDDIT
/:cl:

https://tgstation13.org/phpBB/viewtopic.php?f=55&t=7250

chrome_2016-07-15_01-26-27

### CODE REVIEW

**Comment by dhostak** [comment]
posting to make /tg/ great again

**Comment by Armhulen** [comment]
i'm proud of this hard work

**Comment by Thunder12345** [comment]
The day of the rope has come at last

**Comment by kilkun** [comment]
imo this pr alone should result in your honorary headminship

**Comment by InsaneHyena** [comment]
This is not a meme PR. This is the future. This is a GOOD CHANGE. This will finally get /tg/ rid of furfag cancer, and this MUST be merged.

**Comment by Thunder12345** [comment]
Between this, fly swatters and plasmamemes being utterly shit to play as, we may finally return to the human paradise

**Comment by optimumtact** [comment]
please stop making pr's you know will not be merged

**Comment by optimumtact** [comment]
The north beat the south in the civil war, we'll put you down again you dirty slave running democrats

**Comment by Armhulen** [comment]
we didn't even get to testmerge it

**Comment by demonfiren** [comment]
Master race conspiracy wins again.

**Pull request closed without merging**
