### PR TITLE
Turns Delta into a BattleRoyale Delta map

### PR DESCRIPTION
**Pull request by KathyRyals**
## About The Pull Request

Need this for events.

## Why It's Good For The Game

Number one victory royale
## Changelog
:cl:
add: Chug jugs
/:cl:

### CODE REVIEW

**Comment by KathyRyals** [comment]
YEET

**Comment by KathyRyals** [comment]
Need it open just to see if the tests go okay

**Comment by KathyRyals** [comment]
Test works, now yeet.

**Comment by InsaneRed** [comment]
no

**Comment by KathyRyals** [comment]
Yes

**Pull request closed without merging**
