### PR TITLE
2nd Amendment Update: All crew now start with a small self-defense disabler

### PR DESCRIPTION
**Pull request by Buggy123**
Adds the Personal Self-Defense Disabler (PSD), for when being decapitated by a ling for the 50th time gives you PTSD.

egun

The PSD is a small, easily concealed disabler. The micro-cell that powers it can only fire 6 shots, which is enough to disable a single person with 2 shots leeway. This is enough to disable or slow a attacker, allowing the user to safely escape or call security.

All crew start with a single PSD in their survival box. To avoid a attacker stealing a crewmember's weapon and using it against them or others, each PSD is fitted with a dna-locked firing pin which is pre-keyed to the owner's DNA.<br/>
<br/>

This was suggested by @zxaber and @jdawg1290, and Emerald_Or_Bust (github username unknown) created the sprite for it. Several other people liked the idea, so I decided to go ahead with it.<br/>
<br/>
# Why:
As I and several other people have observed, a crew member who is under attack has about two options:
1: shove them.
2: punch them.

This is rather inadequate against basically any sort of makeshift or actual weaponry, to the point of absurdity. This PR should help even the gap a little, making it at least plausible for a crewmember to escape a attacker.

Note that stuns, stun-resists, decent weaponry, and not being a carbon all counter this, which covers most antagonists. This means that basically all antagonists have a way around this if they spend at least a little effort to do so.<br/>
<br/>

:cl: 
Add: Recent internal investigations have revealed that crew mortality reports were missing, not because of a lack of death, but because the reports were too numerous to be shipped to the H&R department. After briefly examining the 4,395 warehouse complexes containing the past quarter's mortality reports, Nanotrasen has begun issuing self-defense weaponry to all crew.
/:cl:

### CODE REVIEW

**Comment by tmtmtl30** [comment]
i really really want to live through a testmerge of this

**Comment by tralezab** [comment]
Please include a section on why you think this is a good idea

**Comment by necromanceranne** [comment]
You can't murderbone if everyone is packing.

**Comment by Shadowflame909** [comment]
The antag nerf we needed

You can't murder the entire crew if the entire crew disable spams you first.

Also holodeck is gonna be destroyed every round if this were to truly get merged. Antags aint takin risks.

**Comment by necromanceranne** [comment]
Every kill is a reload. Use your victims disabler to kill another.

**Comment by zxaber** [comment]
I mean.
>To avoid a attacker stealing a crewmember's weapon and using it against them or others, each PSD is fitted with a dna-locked firing pin which is pre-keyed to the owner's DNA.

That is, at best, a ling strat.

**Comment by necromanceranne** [comment]
Fucking yikes.

**Comment by MishaTarkus** [comment]
This is a bad idea

**Comment by Buggy123** [comment]
>That is, at best, a ling strat.

You suggested it.

image

**Comment by LemonInTheDark** [comment]
> 
> 
> > That is, at best, a ling strat.
> 
> You suggested it.
> 
> image

AHAHAHHAHAHA

F

**Comment by zxaber** [comment]
I was refuting the "Every kill is a reload. Use your victims disabler to kill another" post ¯\\\_(ツ)_/¯

**Comment by gitbirb** [comment]
i can't wait to floorstun into disabler, and then toolbox my foes

**Comment by optimumtact** [comment]
not funny, did not laugh

**Comment by cacogen** [comment]
always thought something like this should be a part of a functional economy, in the equivalent of what we now know as blackmarket uplinks

**Comment by GreenTea988** [comment]
Call it the Personal Tiny Self-defence Disabler, or PTSD for short and you'll make a lot of people happy

**Pull request closed without merging**
