### PR TITLE
Chaos Donuts Actually Have a Sprite Now

### PR DESCRIPTION
**Pull request by wesoda25**
## About The Pull Request

title

## Why It's Good For The Game

they didnt have one, but wiki said they did, so I just basically copied the wiki picture

## Changelog
:cl:
imageadd: chaos donuts actually get their own sprite now
/:cl:

### CODE REVIEW

**Comment by FantasticFwoosh** [comment]
Im not a big fan (sort of looks like a inverted fruit rainbow slice than pastry) but i appreciate the effort going in to fixing the issue.

Is this a unintentional pride month thing?

**Comment by wesoda25** [comment]
i literally just copied the sprite that shows up on the wiki

**Comment by fluffe9911** [comment]
do meat donuts as well honk

**Comment by wesoda25** [comment]
Meat donuts have a sprite in code, is something bugged and the sprite not working?

**Comment by wesoda25** [comment]
hol up

**Comment by loserXD** [comment]
???

**Comment by wesoda25** [comment]
i fucked something ill fix it later

**Pull request closed without merging**
