### PR TITLE
Adds absolute territory

### PR DESCRIPTION
**Pull request by Incoming5643**
Adds alternate styles to the checkered skirts, which allows them to be worn slightly more revealingly.

d10_icon
Left is the alternate style, Right is the standard style. 
<s>Please choose your waifu accordingly</s>

As requested here (https://tgstation13.org/phpBB/viewtopic.php?f=5&t=3160) by @Chocobro who can't into git

### CODE REVIEW

**Comment by Chocobro** [comment]
i can't into git more like git can't into accepting files
i'm extremely salty about it please ask miauw who has been helping me through this traumatic time for the past few hours
i'm never making a pr ever again
thankyou, numbers.
![bang]
(http://www.gizmoandwidget.com/images/banggun.jpg)

**Comment by Chocobro** [comment]
close up, bottom is the alt
absoluteterritory

actual size
shortskirts

and one with floors under it
skirtsfloor

yes they're all misaligned in these images i have stopped caring at this point

**Comment by xxalpha** [comment]
PATTERN BLUE

**Comment by Atskadan** [comment]
NEED SHORTER SKIRTS

**Comment by Lumipharon** [comment]
absolute territory

**Comment by Atskadan** [comment]
do i recognize that anime girl based on this small portion of her lower body

**Comment by Chocobro** [comment]
do you

**Comment by Atskadan** [comment]
im fairly sure

**Comment by RemieRichards** [comment]
Looks like one of the girls from Toradora.

**Comment by Jordie0608** [comment]
Needs an Absolut Changelog

**Comment by Nienhaus** [comment]
Pretty sure that's Taiga.

**Comment by Lumipharon** [comment]
You're all terrible and clearly don't appreciate ZR if you can't recognise who that is.

**Comment by Kromgar** [comment]
I can't tell if you guys are joking or not but that's Rin Tohsaka

**Comment by Chocobro** [comment]
four more hours

**Comment by TZK13** [comment]
How can you even know what absolute territory is without being able to identify those legs as Rin Tohsaka.

**Comment by Chocobro** [comment]
it begins

**Comment by Atskadan** [comment]
haha i was right

**Pull request merged**
