### PR TITLE
Partially reverts toggle walk hotkey

### LINKED ISSUE #23537: User gets stuck in walk when alt-tabbing w/ Hotkeys enabled
Alt-tabbing toggles you into walk mode, however after tabbing back into the game, you are not returned running. (this is a pretty common issues for programs that have functions with alt that don't continue listening once the window loses focus.) 

Would it be possible to switch the run-toggle to a different key? It's rather inconvenient to tab back into a situation where it's critical that you are running (tator eswording you, bomb exploding, insert terrible thing here) and end up just hobbling away.

### PR DESCRIPTION
**Pull request by ghost**
Partial revert of #23291
Fixes #23537
Alt no longer toggles walk/run, but Alt+Up still does. It was really annoying accidentally toggling walk all the time.

:cl:
del: Removes the 'Alt' Toggle Walk hotkey. You can still Toggle Walk with 'Alt+Up' though.
/:cl:

### CODE REVIEW

**Comment by Arianya** [comment]
P u t  i t  o n  s h i f t

**Comment by Haevacht** [comment]
No Ari, because examine.

**Comment by Arianya** [comment]
Drive by examining is dummmmmb

**Comment by SweaterKittens** [comment]
Alt+Up is unbelievably inconvenient, at that point it's easier to just use the one in the UI. If you have to take your hand off of your mouse to use it, it's probably not a good hotkey.

**Comment by uraniummeltdown** [comment]
Honestly why do we even need a walk hotkey? The UI button is big and obvious enough. Most people don't willingly switch to walk mode anyway.

**Comment by SweaterKittens** [comment]
It was initially proposed and almost required when we nearly added the trample mechanic. Now it's simply a nice QoL feature that ideally could replace the UI button and work towards clearing up our shitty UI. I use it all the time.

**Comment by Arianya** [comment]
I'll agree ALT is a dumb key to have it on, especially for the issues it causes with alt tabbing.

**Comment by SweaterKittens** [comment]
On my computer, you have to hold it down to walk, it's not a toggle. That's way better than a toggle anyway.

**Comment by Arianya** [comment]
Its always behaved inconsistently for me. Sometimes it behaves like a toggle, sometimes like a press and  hold.

**Comment by Steelpoint** [comment]
When ever I alt-tab out of the game I come back to me walking.

Quality of life improvement is misleading.

I support moving the walk key away from alt.

**Comment by SweaterKittens** [comment]
It sounds like the biggest problem is the fact that for some people it's a toggle, which is super shitty. Why don't we just make it so you have to hold the key to walk? Solves the alt-tabbing issue, and keeps a nice, convenient hotkey.

If there's a better convenient hotkey, I wouldn't be opposed to that either.

**Comment by Tofa01** [comment]
Now i might be mentioning something outrageous BUT, what if we let players choose their hotkeys you know like 90% of games?

**Comment by RemieRichards** [comment]
@Tofa01 would require rework of keyhandling to be done in-code, tried before but never finalised.

**Comment by SweaterKittens** [comment]
Tofa that's absoLUTELY the best way to do, but as Remie said it's never been completed so everyone works around it.

**Comment by Cyberboss** [comment]
I feel like the fruit is gonna close this one too

@uraniummeltdown Add `Fixes #23537` to the PR body

**Comment by MrStonedOne** [comment]
Nobody here has stated what OS version they are on to help us fix the toggle issue.

Be the change you want to see in the world. I tested it multiple times and was unable to get the alt tab bug to trigger. how about everybody bitching about the alt tab bug actually try to help us fix it.

**Comment by Cyberboss** [comment]
I've definitely had it happen to me on Windows 10

**Review by Cyberboss — APPROVED** [review]
I'm going to say if we do decide to go with a push toggle, this is definitely the way to do it.

**Comment by MrStonedOne** [comment]
so now, every time somebody alt clicks, they are in walk mode?

**Comment by MrStonedOne** [comment]
Thats retarded

**Comment by MrStonedOne** [comment]
http://www.byond.com/forum/?post=2214392

**Comment by MrStonedOne** [comment]
I should point out to anybody on this thread who is not aware, `up` in macro code means the release of a key, not the up arrow key.

So this would trigger any time you release alt, regardless of anything else.

Alt click a PA to rotate it? now in walk mode

Alt click a tile to view it's contents? now in walk mode

Alt click a pipe to rotate it? now in walk mode

**Review by MrsTonedOne — CHANGES_REQUESTED** [review]
Alt click a PA to rotate it? now in walk mode

Alt click a tile to view it's contents? now in walk mode

Alt click a pipe to rotate it? now in walk mode

That isn't tenable, it can't work.

**Review by Cyberboss — CHANGES_REQUESTED** [review]
Yeah, MSO's right, I keep forgetting about alt clicking

**Comment by SweaterKittens** [comment]
That's super confusing. Huh. In any case, mine does not toggle, it's a hold, and it reverts back to run the moment I release Alt. I'm running Windows 7 Professional

**Comment by Steelpoint** [comment]
I'm on Windows 10.

It seems that when I alt-tab out of the game it'll be stuck on 'walk' mode, yet when I just hit tab in game it'll only stay in walk mode so long as I hold the alt button.

**Comment by Kromgar** [comment]
Toggle issue is on windows 10

**Comment by uraniummeltdown** [comment]
Oh I thought Alt+Up meant the actual Up arrow key, should I remove Alt+Up and keep Alt then?

**Comment by Cyberboss** [comment]
Close this PR, the bug is a BYOND issue that needs to be fixed

On Feb 17, 2017 12:42 PM, "uraniummeltdown" <notifications@github.com>
wrote:

Oh I thought Alt+Up meant the actual Up arrow key, should I remove Alt+Up
and keep Alt then?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/tgstation/tgstation/pull/24188#issuecomment-280717350>,
or mute the thread

**Comment by MrStonedOne** [comment]
http://www.byond.com/forum/?post=2214392 already fixed

**Pull request closed without merging**
