### PR TITLE
fixes clown mask EXTREMELY IMPORTANT

### PR DESCRIPTION
**Pull request by CRTXBacon**
This is a VERY important PR, it is near and dear to my heart as I have spent YEARS making this

:cl: CRTXBacon
tweak: Moves the clown mask south-facing sprite down one pixel, putting it on level with its other directional sprites. Henk.
/:cl:

[why]: The fact that the south-facing sprite of the clowns mask when equipped was one pixel higher than the others has bugged me for ages (a few minutes). It also means that my special snowflake light eyes appeared below the eyes of the clown mask.

### CODE REVIEW

**Comment by ExcessiveUseOfCobblestone** [comment]
Sir you put this in the base TGstation folder not in the appropriate file location, else the icon bot would show the actual differences.

**Comment by CRTXBacon** [comment]
Wait



Shit

**Comment by CRTXBacon** [comment]
Trying to find a way to upload the file from my phone.  Since its not an actual image file I can't upload it normally because... bleh?

**Comment by ExcessiveUseOfCobblestone** [comment]
I would recommend holding off until you get on an actual computer lol.

**Comment by CRTXBacon** [comment]
In my adventures I found an app that makes you pay to make edits.
Guess it'll wait

**Comment by CRTXBacon** [comment]
None if the above happened
Your eyes are deceiving you, bröther

**Comment by epochayur** [comment]
What you're seeing now is my normal state. This is regular editing.
And this, this is what is known as an edit that has ascended above an edit. or, you could just call this a webedit.
AND THIS
IS TO GO EVEN FURTHER BEYOND

**Comment by nicbn** [comment]
You deleted the slime icon state.

**Comment by CRTXBacon** [comment]
If that actually happened I'm going to shit down someone's pants.
All I touched was the clown mask.

**Comment by ATH1909** [comment]
> What you're seeing now is my normal state. This is regular editing.
> And this, this is what is known as an edit that has ascended above an edit. or, you could just call this a webedit.
> AND THIS
> IS TO GO EVEN FURTHER BEYOND

*BYOND

**Comment by CRTXBacon** [comment]
Dude

You already gave me a "Good first pr" tag

This is my third pr

**Comment by k-k-karma** [comment]
it's your first good pr

**Comment by CRTXBacon** [comment]
But my first PR got the tag too therefore your joke is invalid.

**Comment by nicbn** [comment]
it's your first good pr

**Comment by ExcessiveUseOfCobblestone** [comment]
The Mortimer Goth of coding

**Pull request merged**
