### PR TITLE
Buffs Magillitis

### PR DESCRIPTION
**Pull request by ShizCalev**
🆑 ShizCalev
balance: Magillitis will now ALSO affect humans.
/🆑

By make it affect humans as well as monkeys.

OOGA OOGA OOGA

### CODE REVIEW

**Comment by RandomMarine** [comment]
A traitor being able to instantly turn someone into a simple_animal with a single click is nasty.

**Review by Cyberboss — APPROVED** [review]

**Comment by calzilla1** [comment]
I wonder if this is a buff or a nerf to non humans

**Comment by Supermichael777** [comment]
Turning someone into a gorila is going to end up with your spine wraped around your neck

**Comment by GunHog** [comment]
Can Gorilla-ness be reverted to humanity as monkey-ness can?

**Comment by ShizCalev** [comment]
Mind you the reagent takes about 20 seconds to take affect on the target, in which time if they ingest charcoal they're able to negate the effects. Player controlled gorillas are also slightly easier to manage since they're unable to break down walls & doors like NPC ones can.

Also @RandomMarine: See 4TC unlimited use sleepypen (or even a hypospray) w/ slime toxin. This in comparison is used in a 16TC single use injector.

**Comment by kevinz000** [comment]
@ShizCalev yet the other things have a delay where you can get cloned.
this is rush someone roundstart to remove them from the round because who is the crew going to believe, a rampaging gorilla or the guy getting mauled by it?

**Comment by kevinz000** [comment]
also not everyone carries charcoal wtf.

**Comment by ShizCalev** [comment]
Wasn't saying everyone carries charcoal around, was just pointing out that there are ways to negate the effects.

**Comment by Armhulen** [comment]
if you make someone a gorilla without consent, you're basically dead

**Comment by AdamElTablawy** [comment]
yeah this is the rough equal of having a staff of change that always turns someone into a xeno drone

easy enough to kill but you're probably fucked if you don't have a good gun

**Comment by ShizCalev** [comment]
You have 20 seconds to run away after injecting someone before they transform.

20 seconds is enough to literally run from one end of Metastation to the other to get away from the person who's about to turn into a gorilla.

**Comment by AdamElTablawy** [comment]
It's also enough time for them to chase you from one end of metastation to the other, eagerly awaiting the chance to beat you to death as murder gorilla.

**Comment by KorPhaeron** [comment]
It's 15tc, should be at least somewhat fun to use.

Probably going to need a cure after this though

**Comment by KorPhaeron** [comment]
Thanks, I will merge the PRs together

**Comment by optimumtact** [comment]
Kor commented 20 hours ago

**Comment by KorPhaeron** [comment]
The other PR has not been open 24 hours

**Pull request merged**
