### PR TITLE
[BALANCE] Removes Flashbangs from SecVender/SecLockers

### PR DESCRIPTION
**Pull request by Steelpoint**
As in the title, the flashbangs in the SecVender are removed in this PR to make Flashbangs are more uncommon item.

I was going to remove the HoS's Box of Flashbangs and give him two flashbangs instead but I'll hold off until there's more, if any, feedback on that, considering he is the HoS.

### CODE REVIEW

**Comment by Miauw62** [comment]
>steelpoint
>nerfing sec

wot

**Comment by xxalpha** [comment]
are you alright

**Comment by Steelpoint** [comment]
Feedback from this thread: https://tgstation13.org/phpBB/viewtopic.php?f=10&t=4017&p=100810#p100393

I do agree flashbangs are extremely powerful, and any changes to sec, antags and everything else is going to involve giving and taking.

**Comment by Supermichael777** [comment]
on the verge of collapsing if we remove any more of their staples.

toataly following the advice of the thread. totally not an excuse to move the need train forward

**Comment by Supermichael777** [comment]
needing based off a 18 hour old des cushion thread with less than 6 participants

**Comment by Dorsisdwarf** [comment]
I  strongly dislike this change. Security don't need a nerf to their only serious method of crowd control, especially with the rise of Gang and Shadowling, a third and a fourth mass-conversion team antag mode

**Comment by Steelpoint** [comment]
In the scheme of things this simply removes four flashbangs.

This PR is not a balance change in a vacuum, I intentionally put this up alongside the PR that removes the taser firing delay. 

I'm hedging the bet that we'll be seeing a lot of rebalancing over the next few weeks, at least I hope we do, this will simply be one of the areas where security gives away something.

**Comment by SconesC** [comment]
I approve of this

You want flashbangs? HoS/Warden puts the box in the armory window.

**Comment by Stickymayhem** [comment]
Absolutely not.

Flashbangs are the best option for crowd control. Security misusing them for everything results in them running out pretty quickly and they almost never order more.

If you don't to restrict people by taking away their improvised/easily accessible weapons or through policy changes that favour security, stop fucking nerfing security.

**Comment by Steelpoint** [comment]
My intention is that this is, as I said prior, one of many buffs and nerfs to sec, antags and everyone else. Hopefully anyway. 

Also Sticky if you think sec needs some help in the policy department, then you have that capability.

**Comment by Stickymayhem** [comment]
I'd rather the game work than have to patch it with policy. I do what I can but a direct code change is always more effective than disallowing behaviour or adding yet more damn rules to the page.

**Comment by SconesC** [comment]
Probably relevant that you read the two threads that led up to this PR, Sticky, if you have not already

**Comment by PKPenguin321** [comment]
This is good for now, but if flashbangs ever get a direct nerf then this should be reverted

**Comment by Perakp** [comment]
:-1: 
Flashbangs are standard gear for security officers, and there need to be ways to easily replenish them (without help from cargo, warden or HoS). Them being in the vending machine makes sense.

As a security 'nerf' this is just bad, borderline bullying security players by introducing new inconveniences for their already stressful job.

Have you considered how easy is it for the HoS or captain or any armory looting antagonist to take ALL the flashbangs, if they are as powerful as you make them out to be this ought to happen all the time, and this update would make it even easier.

**Comment by Iamgoofball** [comment]
:-1:

i don't really see the reason for this

why does security need nerfs all of the sudden? i thought it needed buffs

**Comment by Cebasiz** [comment]
i don't think it's necessary. i'm fine with removing the taser delay in a vacuum. it doesn't need to be balanced by a nerf to something that's a security staple.

**Comment by Lumipharon** [comment]
nerf the AOE flash into the ground, but the flashbangs in the vendor are used by normal sec officers, who have 1-2 each, over all (including the vendor).

**Comment by Antimattercarp** [comment]
How about we wait for the meta to adapt to the lack of taser delay before we start with the cowboy balancing :-1:

**Comment by Killbasa** [comment]
@Antimattercarp, i agree that we should see how the taser change plays out before we do this.

**Comment by Falamazeer** [comment]
This is wrong.

Security doesn't need your help getting fucked.

**Comment by Steelpoint** [comment]
You do know that beforehand there were never enough flashbangs for each officer to get one for themselves? This change only removes four (4) flashbangs from the game and now requires you to ask the Warden or HoS for their flashbangs, in fact its uncommon for someone to touch the armoury flashbangs.

As I said prior, this is not a balance change in a vacuum.

**Comment by Falamazeer** [comment]
If it's not accessible it's use will drop, this is not needed, not wanted, and it just needs to go away.
They are a valid item, Hiding them in the armory with the sec huds and other nice shit that's tactically placed so antagonists have something nice for their efforts to cut in.

Your "give and take" attitude is bullshit, it's not yours to give, Those flashbangs are not a balance issue, Nerfing the losing side is not a balance issue. and even accounting for fixing taser delay, it's still not a balance issue because THE NORMAL STATE OF AFFAIRS was always both these things, and security was  still somewhat flimsy.

Fix the flashbangs, don't hide them so they are a bitch to get, and don't nerf them to the point where nobody wants to use them, Not even that long ago flashbangs dropped officer too, and not just when they had them in their hands/at their feet, increase  the range at which an officer will catch himself in his own blast, thus increasing the risk associated with it, and trimming the use cleanly.

**Comment by Steelpoint** [comment]
I forgot that someone placed flashbangs inside security lockers, symptom of me only playing HoS and never having to use the sec lockers.

I've removed them.

**Comment by Killbasa** [comment]
I was fine with removing the SecVender ones, but now this is just too much.

**Comment by Steelpoint** [comment]
I imagine people kept quite about the locker flashbangs hoping I would avoid them.

**Comment by Falamazeer** [comment]
Nice to see you and scones so responsive to outcry "join github so I can ignore you in two places"
And yeah, I'm lumping scones in with you shamelessly steelpoint.,

 If you're so out of touch that you didn't even notice the ones in the lockers due to only playing HoS (Read:Properly equipped) you have no buisness fucking up security. 

And no, I wasn't keeping quite hoping you'd forget, the way you were talking made me assume you'd accounted for them.

This change won't fuck with you in your primary role, but it'll fuck with me every time I play mine, and the flimsy reasoning of trying to get the HoS or warden to pass them out is a thinly veiled laugh at best, Most rounds an officer can't even get a replacement baton or taser which are absolutely critical to the job.

**Comment by Nanotransistor** [comment]
Would you consider replacing them with tear gas grenades? I feel they are good while fitting the theme of a civilian security force. The problem i have with flashbangs as of now is that they take no effort to use and have no downsides at all. An officer shouldn't be able to toss one and stare at it as it ignites.

**Comment by Steelpoint** [comment]
@Nanotransistor 

That's true, I'll add them to the lockers instead.

@Falamazeer 

I understand your concerns but many other people feel flashbangs are simply too powerful, and with the removal of the taser firing delay this change seems as a acceptable counterpoint.

I would also ask if we can take feedback to the flashbang thread on the forums, its easier to keep track of feedback there: https://tgstation13.org/phpBB/viewtopic.php?f=10&t=4017

**Comment by Falamazeer** [comment]
I did, and so did the majority of people who voiced disapproval.


And again "Join github so I can ignore you in two places"
Pick a narrative and stick with it, either this is where the decisions are made or it isn't.
Most people in both threads agree this is not a good idea.

**Comment by Supermichael777** [comment]
tear gas grenades are useless for dispersal because they dump the regents in the first person to walk through. it's more useful as a smokescreen and area denial. they are not as useful, until just now thy blocked shooting, and they have a slow ring dispersal rather than an instant area takedown. they are so inferior they are almost never used,

**Comment by Razharas** [comment]
Quick poll on coderbus revealed the current security is ok as is and dont need any buffs or nerfs

**Comment by Steelpoint** [comment]
Ah yes because I'm certain the members of the ivory tower of codeland know every facet of the game.

**Comment by Steelpoint** [comment]
I'll probely close this either way but I said I'll wait 24 hours before doing anything.

**Comment by duncathan** [comment]
What about replacing them with tear gas grenades, like mentioned above?

**Comment by Steelpoint** [comment]
I don't think removing the flashbangs in the first place is a acceptable way forward.

**Comment by Lumipharon** [comment]
teargas is really bad. It used to be marginally less bad, but it's never been good.

**Comment by Steelpoint** [comment]
Well at the very least this PR helped generate some discussion.

**Pull request closed without merging**
