### PR TITLE
Drakes have a toggle for a small sprite.

### PR DESCRIPTION
**Pull request by ghost**
God, I really hate accidently hitting myself when i'm a player controlled drake. And I know that you hate accidently hitting yourself when you're a player controlled drake. So for the good of drake society i'm making a small sprite toggle. I need to move over some things (including the actual sprite, which will be a lizard wearing drake armor unless you give me something much better)

### CODE REVIEW

**Comment by Armhulen** [comment]
I'm gonna do this for hopefully every megafauna

**Comment by RemieRichards** [comment]
>still uses queen sprites

lmao

**Comment by Armhulen** [comment]
I had to kinda rush this out and I'll fix everything when I can

**Comment by RemieRichards** [comment]
make it the janitor's tiny pet lizard, wags.
that should be the tiny drake sprite.

**Comment by Repukan** [comment]
>Queen

**Comment by Slignerd** [comment]
humanoid drake 4x

Here's the humanoid ash drake appearance, from that drake blood potion. Could be used as a base for the sprite, maybe you could make it wear ash drake armor, too.

**Comment by Repukan** [comment]
>A fucking ligger

We hit rock bottom and sligneris keeps digging.

**Comment by Slignerd** [comment]
You do realize dragons are reptiles, right?

**Comment by Armhulen** [comment]
You do realize dragons don't exist, right?

**Comment by Armhulen** [comment]
I'll probably go with slig's suggestion

**Comment by Grazyn** [comment]
Why does the humanoid form have to be reptilian? Dragons can look like humans in other major fantasy settings, like warcraft or DnD.

**Comment by Armhulen** [comment]
@Korphaeron prb no update this pr is for the good of ss13kind

**Comment by PKPenguin321** [comment]
>stealing my code

**Comment by Slignerd** [comment]
> You do realize dragons don't exist, right?

Neither do sapient frogs tbh 🐸

**Comment by praisenarsie** [comment]
bad pr

**Comment by Armhulen** [comment]
I dunno who you are but you should FUCK OFF

**Comment by praisenarsie** [comment]
a guy who knows when a bad pr is a bad pr

**Comment by Shihrt** [comment]
> Why does the humanoid form have to be reptilian? Dragons can look like regular humans in other major fantasy settings, like warcraft or DnD, or even The Witcher.

this isn't warcraft, dnd, or the witcher

**Comment by ishitbyabullet** [comment]
Forget ash drake sprites, how about toggle small sprites for all megafaunas?

**Comment by Armhulen** [comment]
I'm doing every megafauna. Atomized prs ftw!

**Comment by ExcessiveUseOfCobblestone** [comment]
the reason for having this is a very gamey "so i don't hit my own sprite". Everyone else sees your sprite and you still know you're the big bad dragon, so this argument over what the baby sprite should look like is really just bikeshedding.

**Comment by sawrge** [comment]
instead of this make it so players can not control megafauna

**Comment by DoctoreMad** [comment]
@sawrge 
Reflect for a bit.
Firstly that we would have to throw out one of our megafauna loots, because the point of it is to control megafauna.
Second is that, if a player is inside megafauna, the mods intended it to be.

**Comment by Repukan** [comment]
Doesn't mean that you should be forced to use a sprite that's not to your liking or suffer gameplay disadvantages.

**Comment by ExcessiveUseOfCobblestone** [comment]
You're still the big ashdrake to literally everyone else but yourself.

**Comment by Repukan** [comment]
Cobby if I wanted to play as a Lizard I would pick an autistic immersion breaking name and choose lizard.

**Comment by Repukan** [comment]
What does it matter to have customization in games if everyone else sees your stats and knows what you are?

**Comment by Repukan** [comment]
Why don't we go a step further and replace everything with ascii. We don't need visual cues since the chat will tell us what we already know and it prevents pointless bikeshedding.

**Comment by sawrge** [comment]
@DoctoreMad some of the mods are fucking retarded with this stuff so that's not really an argument

**Comment by Slignerd** [comment]
Is Repukan actually mad about a simple QoL functionality for an ash drake simply because of "lol liggers XD"?

**Comment by sawrge** [comment]
i'd say repukan should suck it up but the reality is very fucking rarely should admins be making player controlled megafauna if ever

**Comment by Slignerd** [comment]
Don't we still have that potion that has a chance to give you an ability to transform into an ash drake? Isn't ash drake still in staff of change pool?

**Comment by sawrge** [comment]
idklol

**Comment by sawrge** [comment]
thought it was lesser drake or some shit

**Comment by sawrge** [comment]
arm said he was doing this for every fauna tho which concerns me much more than doing it just for the one that already has ic means of being player controled

**Comment by Repukan** [comment]
>Fight monster that can take you out of the round permanently if you're careless
>Roll the dice and get drake transform
>Now you have to choose between suffering gameplay disadvantages or lose identity chosen roundstart

**Comment by Repukan** [comment]
Also I'm only arguing this much since it's the lesser Drake and there's plenty of media where dragon transformers can be human too.

**Comment by DoctoreMad** [comment]
>thought it was lesser drake or some shit

lesserdrakes are children of the ash drake type.

**Comment by Repukan** [comment]
Also don't even project anger on me you little fucking worm. 

I'm not the one making reddit threads to raise pitchforks when someone mentions adding a meme bird race

**Comment by Slignerd** [comment]
For as long as you're transformed into an ash drake, you lose the identity chosen roundstart either way.

You get it back as soon as you transform back though?

**Comment by ishitbyabullet** [comment]
@sawrge I said 'turn every megafauna into smallsprite' for private servers, not so the tg admins can make a sentient colossus fucking destroy the captain in a fistfight

**Comment by Pascal125** [comment]
I think people should stop whining over the most trivial matters and make a molehill out of it.

**Comment by ShadowDeath6** [comment]
couldn't you just make the sprite like 1 tile large instead of making them look like a player race despite having absolutely no gameplay similarities to said player race

**Comment by Onule** [comment]
Could always.. you know, literally scale it down to from 64x64 to 32x32?
dragon
smoldragon

**Comment by Dorsisdwarf** [comment]
>pascal appears in a github PR 
>"Its just a miner QOL that they appear to be lizardpeople when they use the drake potion ok there is literally no incredibly-easy option that is simpler and requires no drama from lizard-haters"

**Comment by Armhulen** [comment]
I'll just do what onule suggested since repukan is extremely bent about lizards

**Comment by DoctoreMad** [comment]
Caving in to terrorist demands eh?

**Comment by Slignerd** [comment]
Lizard-haters freaking out and causing drama is something to laugh at rather than actually listen to as if it's legitimate feedback tbh.

**Comment by SgtxRootbeer** [comment]
@Repukan this is a ash-drake only thing. the only person who sees the sprite is whoever is actually playing as a drake.

HAKUNA-YOUR-TATAS

**Comment by Slignerd** [comment]
I always wanted to roleplay as a baby dragon.

**Comment by Armhulen** [comment]
Dear god this pr will remove my tokens and double dear god some retards are arguing about lizards that ARENT EVEN IN MY PR!

**Comment by PKPenguin321** [comment]
That will be 0.25 good boy points please

**Comment by Armhulen** [comment]
If that gbp tax gets in im throwing tea into the river

**Comment by PKPenguin321** [comment]
Finish this and I'll PR it
I'm spamming fixes to farm GBP

**Comment by Hatfish** [comment]
fuck's sake this doesn't even change the sprite for anyone else, it's literally just there so you can bite people who are hiding behind your fatass dragon sprite.  why do you people have to drag lizard drama into any applicable situation, jesus fuck

**Comment by Pascal125** [comment]
Because people are fucking dumb.

**Pull request closed without merging**
