### PR TITLE
Fixes the last known Dreamstation issue

### PR DESCRIPTION
**Pull request by ChangelingRain**
[Report additional issues here.](https://tgstation13.org/phpBB/viewtopic.php?f=11&t=4661)

### CODE REVIEW

**Comment by Xhuis** [comment]
Besides the fact that it exists?

**Comment by Anonus** [comment]
Unfixable!

**Comment by Xhuis** [comment]
ayoo

**Comment by Anonus** [comment]
Dream on, because this dream is neverending.

**Comment by Jordie0608** [comment]
There's still no labour camp shuttle.

**Comment by Xhuis** [comment]
aayo

**Comment by PKPenguin321** [comment]
what exactly does this add to the map

**Comment by PKPenguin321** [comment]
this literally isnt the last known issue since i reported the lack of a coldroom on that thread you linked
do you even check your own thread tbh smh fam

**Comment by Dorsisdwarf** [comment]
He means github issue

**Comment by Anonus** [comment]
Xenobio DOES have a coldroom, it's the little engine-floored area right next to the large pen.

**Pull request merged**
