### PR TITLE
Adds heart-shaped boxes of chocolate to the valentines event

### PR DESCRIPTION
**Pull request by TehZombehz**
:cl:
add: Heart-shaped boxes of chocolates are now included in Valentine's Day event gifts
/:cl:

valchoc valchocopen valtinychoc
Includes inhands and a fancy container.
As per the changelog, medium-sized heart-shaped boxes containing 8 tiny chocolates will be added to people's backpacks as part of the Valentine's Day event.
I felt like it would make a nice addition to reflect the common tradition of exchanging chocolates on Valentine's Day.
I also fixed the description for egg cartons while I was there. Egg cartons have nothing to do with donuts.

### CODE REVIEW

**Comment by improvedname** [comment]
Be my validtine

**Review by ShizCalev — APPROVED** [review]

**Comment by ExcessiveUseOfCobblestone** [comment]
h-h-h-h-hi

**Review by WJohn — APPROVED** [review]

**Comment by WJohn** [comment]
The box could use better shading and be a bit taller than it is now, and an outline would be nice, but seeing as these are only gonna be visible for a few days it's not the worst thing. If you want to improve these, I'd appreciate it, but it's not absolutely necessary.

**Comment by AlexTheSysop42** [comment]
so I was reading valentine.dm and saw this
>to_chat(lover, "<span class='warning'><B>You're on a date with [date]! Protect them at all costs. This takes priority over all other loyalties.</B></span>")

What if the hos was valentines with a headrev?

**Comment by Bawhoppen** [comment]
@AlexTheSysop42 You protect them at all costs regardless of loyalty

**Comment by Bawhoppen** [comment]
If you try and use these boxes of chocolates, they become invisible

**Pull request merged**
