### PR TITLE
Makes 509 official.

### PR DESCRIPTION
**Pull request by MrsTonedOne**

### CODE REVIEW

**Comment by RemieRichards** [comment]
>Make's

you're doing it too now! hehe

**Comment by Fox-McCloud** [comment]
Isn't 1318 the most recent release?

**Comment by MrStonedOne** [comment]
I'm basing it off of what sybil is running. I figured i'd start pr-ing updates to travis based off of sybil's current verison

**Comment by Fox-McCloud** [comment]
Alright. Thanks.

**Comment by duncathan** [comment]
Thank god for maintainer powers

**Pull request merged**
