### PR TITLE
Resprites encryption keys

### PR DESCRIPTION
**Pull request by Kraseo**
Encryption keys are now less blockier and flat-coloured and a bit more diverse in colour taste and shape.
Also, syndicate and binary keys now have their own sprites because you might as well be caught red-handed with them in your headset anyways.

New sprites:
cyphers

### CODE REVIEW

**Comment by XDTM** [comment]
The syndicate encryption key having the same name and icon as a normal encryption key was probably intentional. Although, since there _isn't_ a real normal encryption key, it might as well have its own sprite and name.

**Comment by Kraseo** [comment]
Honestly, anyone could just use the radio and immediately see in blatant white over green/blue SYNDICATE. Or just hear every single radio channel by putting it on. The disguise was of no use, and people will realise you can talk in the syndie channel if they're smart enough to examine the key.

**Comment by WJohn** [comment]
These are definitely more interesting looking than what we had before. I'll likely be running these through my color palette in the future. Good work 👍

**Comment by Dorsisdwarf** [comment]
@XDTM pretty sure standard encryption keys were removed by paprika at some point, leaving only the "stealth" keys

**Comment by Supermichael777** [comment]
Because literaly pointless.

Remove Graido

**Comment by Militaires** [comment]
10/10

**Pull request merged**
