### PR TITLE
Arconomy: Trims out some of the worst bounties, replaces them with tasks that require basic amounts of effort.

### PR DESCRIPTION
**Pull request by ArcaneMusic**
## About The Pull Request

After doing some soul searching, I came to realize something.
Almost 100% of the original set of bounties that pubby PR'd in 2018 have been virtually untouched in the sway of time. Economy has gone a long say since then, but more importantly, some of the old bounties were just... completely worthless in terms of time investment and difficulty. You could complete them in seconds without a second thought. Here I've removed some of the truly egregious ones and offered replacements for the science bounties to give them tasks themed to the tasks their department allows.

Removals:
Assistant: Glass shard and Cheese Honker bounties.
_They're way too simple and barely worth the second thought to complete. if their value is even up to snuff. There is zero scarcity of windows to break for glass shards, and there will ALWAYS be more cheese puffs in the vendors. ALWAYS. Assistant category has enough diversity to make up for their loss._
Science: Basically all of them.
_There is no science to be done by walking to another department's lathe, printing out one of their researchable objects that in all likelyhood R&D just did, and then making several hundred if not thousand credits for being able to print out their very own loot. Not only are science bounties not indicative of any real effort in the current R&D system, but they didn't even when we were still using omnilathe printing! That's wack, yo._

Replacements:
Science:
_Modular Computer Bounties_
Science has 3 new bounties, to produce Tablets, Laptops, or ~~Static Consoles~~ (Not working just yet) to export. Modular computers are a Science specialty in terms of their parts and function, and being that they can produce the parts to manufacture them, the assembly of modular computers takes time and resources, but isn't a particular endeavor either.

_Genetic Mutator Injectors_
Finally, Geneticists have a bounty that actually begs to their job as opposed to just slimes and backpacks that they don't particularly need. Now, they have a specific task to produce an injector that contains a specific threshold of mutation instability that must be exceeded in order to claim the bounty. Genes can be combined if one lacks the higher instability mutations and needs to merge several weaker mutations.

_Activated Strange Objects_
What can I say, I have a soft spot for strange object artifacts. They're basically toys that have high power effects in-round, and for that I love em. This adds a second bounty for strange objects on station but for scientists these relics have to have had their true nature discovered in the experimenter, giving higher rewards but putting them in direct competition with players looking to score a strange object bounty.

## Why It's Good For The Game

Replaces some of the lowest common denominator bounties in-game with higher fidelity, and higher engagement tasks with the rest of the station. Science doesn't benefit from just printing out more experimental welders, they benefit by doing tasks that let them fiddle with and engage with the game's mechanics and features. Same for assistant bounties, even if they're all pretty generic or basic, buying some of the most common in-game food or breaking a halfdozen windows doesn't make for engaging gameplay.

## Changelog
:cl:
add: Science has been given a more experimentally themed set of bounties.
del: Much of the old science bounties were discontinued.
del: ...As have the glass shard and cheese honker assistant bounties.
/:cl:

### CODE REVIEW

**Comment by Barhandar** [comment]
Removing printing sci bounties when qustinnus wants to yeet techwebs is kinda dumb.

**Comment by Tlaltecuhtli** [comment]
laptops and ipads are even worse as you can just go buy them from the vendors outside sci

cheesie bounty could be changed by having the vendors have only 1 set for each vending machine so you have a chance of people eating them, making you go to for more remote vendors inside other departments

**Comment by Qustinnus** [comment]
techwebs is not being removed.

**Comment by Tlaltecuhtli** [comment]
is there a check if the laptops have the parts to work? like even an empty frame is considered an /obj/item/modular_computer/laptop, i think its better to focus on  stuff  thats more engaging like a laptop loaded with a job specific program or arcade tickets ( for assistants),  bio sampling tool loaded with sample of animals from gold slime/ vat growing, or "scans" of people(or monkey) with certain nanite programs in their blood

**Comment by Fikou** [comment]
not changing sec bounties 😔

**Comment by Hamcha** [comment]
I had the glass shard bounty 3 times in a row, it felt like a license to grief. Good riddance to junk bounties that give you near to no credits and are at worst a 5 minute pause.

**Review by Timberpoes — APPROVED** [review]
Alright. This has been sitting around collecting dust for long enough. Let's see how the Arconomy looks with these changes.

**Pull request merged**
