### PR TITLE
Some Command Resprites

### PR DESCRIPTION
**Pull request by Imaginos16**
## About The Pull Request

New changes: 
-Peaked Caps! These are replacing the old commander cap sprites, and overall give a more naval vibe to their style.
-The HoS trenchcoat has also been resprited/reshaded! Blame @axietheaxolotl for forgetting it

image

Now, one might ask:

"But Positiiiiive, where's the old white captain tunic?"

Glad you asked because I nuked it to oblivion. In its stead, I've made a new jacket for captains!
The logic behind this decision was that it looked out of place in the captain's wardrobe, so I opted for this instead, not only for consistency, but for something simple and serious, and rather stylish! (It is also a reference :) )
image

## Why It's Good For The Game
Better style, consistency, and to ensure that this game has peak, maximum drip at all times. Enjoy!

## Changelog

:cl: PositiveEntropy, Axietheaxolotl
imageadd: Resprites/Reshades the Head of Security's Trenchcoat!
imageadd: Resprites commander caps into peaked caps! Flex your naval prowess with them!
imagedel: Removes the old captain parade tunic, replacing it with Captain's Parade Jacket!
/:cl:

### CODE REVIEW

**Comment by axietheaxolotl** [comment]
Totally not biased, perfect PR. 👍

**Comment by Serxule** [comment]
while i don't think you had to get rid of the captains old armor tunic thing, which wasn't bad, i always switched it out anyways and this looks good regardless

**Comment by Colovorat** [comment]
Holy shit caps look pog, especially hos one

**Comment by bluetshirtguy** [comment]
they all look the same :b

**Comment by DrDiasyl** [comment]
Make HOS Trenchcoat togglable LOL

**Comment by Dorsisdwarf** [comment]
These look very nice, but isnt the captain generally themed with a darker blue?

**Comment by Imaginos16** [comment]
> These look very nice, but isnt the captain generally themed with a darker blue?

Its one to one the exact same blue the other captain stuff uses

**Comment by Dorsisdwarf** [comment]
> > These look very nice, but isnt the captain generally themed with a darker blue?
> 
> Its one to one the exact same blue the other captain stuff uses

Guess it just looks brighter out of context 👍

**Comment by Farquaar** [comment]
I prefer the old parade uniform. The new one looks nearly identical to the normal captain uniform. Might as well remove it altogether.

**Review by Twaticus — APPROVED** [review]

**Pull request merged**
