### PR TITLE
Ebows can no longer have KA mods installed

### LINKED ISSUE #20086: You can mod Ebows with KA modkits
You can use modkits on the ebow. Most mods won't work but some like the cooldown modification do work and make the weapon very strong.

### PR DESCRIPTION
**Pull request by ChangelingRain**
honestly why did this stick around it's a tiny amount of lines to fix/prevent
I even fixed the KA empty icon showing up on the ebow, too
Fixes #20086

### CODE REVIEW

**Comment by Lexorion** [comment]
closes #20086

**Comment by optimumtact** [comment]
WHY IS THE EBOW A KA

**Comment by Cyberboss** [comment]
@optimumtact This is why I drink

**Comment by ShadowDeath6** [comment]
is the price for not copypasting recharge code greater than the price for making ebow a subtype of KAs? who knows

**Comment by PKPenguin321** [comment]
Joan nobody did this because the proper fix is making a parent object for both KAs and ebows that has the auto recharge function but we're too lazy

**Comment by ExcessiveUseOfCobblestone** [comment]
ebows should accept KA mods :^)

**Pull request merged**
