### PR TITLE
[tm]Revert "Refactor Stat Panel styles and more TGUI-like appearance"

### PR DESCRIPTION
**Pull request by MrsTonedOne**
Reverts tgstation/tgstation#85257 for test merge until its issues can be fixed.

Next time @tgstation/commit-access please test merge large changes to admin tooling like this for longer and please actively get feedback from admins. 

I dislike giving the tabs a horizontal scroll bar

image

edit: to be clear: the old behavior before the pr was that the verb tabs would linewrap. not show a scrollbar

### CODE REVIEW

**Comment by MrStonedOne** [comment]
@AyIong Was this change to tab overflow behavior intentional?

**Comment by ZephyrTFA** [comment]
Please list the issues the prior PR caused.

**Comment by Mothblocks** [comment]
+1 on the scroll bar, horizontal scrolling is one of the most common disliked ux's

**Comment by MrStonedOne** [comment]
the pr has been live for less than a round.

As more issues come up i'll address them, but right now the biggest show stopper is listed in the pr, chat tabs have a scroll bar instead of linewrapping like they used to.

**Comment by AyIong** [comment]
> @AyIong Was this change to tab overflow behavior intentional?

Yeah, I thought no-one minded, given that the demonstration showed it was there.
I'll revert it, or, add setting to toggle it

**Comment by MrStonedOne** [comment]
One thing to keep in mind when making UI for this game, is a lot of people play this game because its runs on their shitty old computers.

So monitor widths of 1024 or 786 have to be designed for. Bringing font all the way down to 8 px is not enough to remove the horizontal scroll bar on my laptop.

image

it would murder to try and administrate this game under the default:

image

**Comment by MTandi** [comment]
Make tabs vertical

**Comment by MrStonedOne** [comment]
> Make tabs vertical

image

**Comment by lessthnthree** [comment]
Also this doesn't respect the font selected in the TGUI say options panel.

**Comment by AyIong** [comment]
> Also this doesn't respect the font selected in the TGUI say options panel.

He doesn't have to :D

**Comment by ZephyrTFA** [comment]
> Also this doesn't respect the font selected in the TGUI say options panel.

probably because the stat browser is infact not tgui

**Comment by AyIong** [comment]
> I was speaking to LT3 about this but didn't see it in writing anywhere on the PR so just dropping it here in case it gets forgotten. In addition to the horizontal scroll bar, some options are too long to display on one line and so it shows them in full when you hover.
> 
> This is very bad though because when trying to click something directly underneath you often just get blocked by the popup tooltip and have to move the mouse away to get rid of it to be able to click on what's underneath. Happens a lot while just trying to use the thing.
> 

Already fixed here - https://github.com/tgstation/tgstation/pull/85399
Thanks

**Pull request closed without merging**
