### PR TITLE
Increases Drone Speed

### LINKED ISSUE #34938: Drones are too slow
Apparently regular drone movement speed was also lowered when cogscarab speed was nerfed. There's no reason why regular honest hard working drones should suffer just because of few darker shade drones ruin their reputation and take their jobs.

### PR DESCRIPTION
**Pull request by Anonmare**
Fixes #34938

### CODE REVIEW

**Comment by Xhuis** [comment]
Uhm, make sure this is tested. I'm pretty sure that higher values are *slower* speed and this will make drones super slow.

**Comment by Anonmare** [comment]
@Xhuis That seems backwards, I'll set it to negative then

**Comment by Xhuis** [comment]
-2 makes ***SANIC DRONES***, which is amusing. I don't see any problem with it, but some maintainers might.

**Comment by Buggy123** [comment]
Sanic drones? Sounds like fun, merge asap :+1:

**Comment by Anonmare** [comment]
If they're a problem, just blow 'em from the console

**Comment by Durkel** [comment]
Don't make the drones max speed, They're already a bitch to kill when they start griffing.

**Comment by Buggy123** [comment]
>griefing drone
>not immediately ahelping because that is extremely bannable

**Comment by Buggy123** [comment]
TBH the server should just turn off whenever there isn't a admin on because everything is fucking horrible and the rules stop existing. Half the time it becomes fucking nations.

**Comment by ShizCalev** [comment]
isn't -2 max speed? that seems a bit much....

**Comment by Anonmare** [comment]
I can reduce it to -1 then

**Comment by newfren** [comment]
No keep my sweet boys fast as fuck

**Pull request merged**
