### PR TITLE
Adds The Goose bar sign, inspired by Yog.

### PR DESCRIPTION
**Pull request by harmonyn**
##  About The Pull Request

Adds a bar sign for The Goose, inspired by yog: https://github.com/yogstation13/Yogstation/pull/6520

## Why It's Good For The Game

Immortalizes everyone's favorite ~~poorly coded~~ station pet.

goose

## Changelog
:cl:
add: Nanotrasen has approved a new bar concept The Goose.
/:cl:

### CODE REVIEW

**Comment by Tharcoonvagh** [comment]
Make it vomit

**Comment by bgobandit** [comment]
it's not my sprite, I cannot into spriting

**Comment by MrDoomBringer** [comment]
@bgobandit we already have a vomit goose sprite

**Comment by bgobandit** [comment]
a) there is still the issue of animating a sign b) it's not my sprite, I would feel weird adding vomit to someone else's sprite

**Comment by nichlas0010** [comment]
https://www.youtube.com/watch?v=4zCgbA1jdIo

**Comment by plapatin** [comment]
should've been called "The Loose Goose" if you ask me

**Comment by plapatin** [comment]
graphic design is my passion
thegoose
https://drive.google.com/file/d/1JJp2fDjjAFHHuAEPEnWCkSbbw7YQwO3S

**Comment by bgobandit** [comment]
switched to plapatin's sprite with slight edits

**Pull request merged**
