### PR TITLE
Mimes can no longer speak.

### PR DESCRIPTION
**Pull request by Iamgoofball**
Haha, no.

Mimes shouldn't be able to speak. Their entire gimmick is "not speaking". Giving them a button to completely throw this gimmick they signed up for away is dumb and stupid and against the character.

### CODE REVIEW

**Comment by Shadowlight213** [comment]
...

**Comment by Armhulen** [comment]
[                                  ]

**Comment by KingPhilipIII** [comment]
Mimes that talk trigger me.

**Comment by Haevacht** [comment]
Less memeing more trophy cases and chisels.

**Comment by Armhulen** [comment]
>

**Comment by Armhulen** [comment]
> 

>

**Comment by JJRcop** [comment]
if you want to be more hardcore you could just make them not have a tongue

**Comment by Lakart** [comment]
I was thinking maybe more along the lines of them taking suffocation damage when they spoke but, ok.

**Comment by ShadowDeath6** [comment]
ling mimes???

**Comment by KorPhaeron** [comment]
Doesn't include reasoning in OP

**Comment by Shadowlight213** [comment]
The reasoning is clearly stated in mimespeak as:

**Comment by Iamgoofball** [comment]
reason added @KorPhaeron

**Comment by ChangelingRain** [comment]
Rip clockcult mimes, you should probably exclude mimes from jobs that can be clockcultists by default

**Comment by Iamgoofball** [comment]
antagging should be stripping limitations and spells by default

**Comment by ChangelingRain** [comment]
not being able to speak is literally only a limit with this pr for this specific antag, so add that, then.

**Comment by Iamgoofball** [comment]
I'm not adding it in this PR as this was a github meme and not a proper IDE setup as I'm dealing with save file R&D locally right now, I just heard players complain about mimes being able to talk and fixed it, 

I'll just exclude mimes from clockcult default for now like you said, in the future I'll standardize it so that clowns/mimes get clumsy/silence+spells removed if they roll antags or are converted to antags.

**Comment by ChangelingRain** [comment]
But mimes don't need to, and shouldn't, lose their silence and spell for just standard traitor, because they can get use out of it as a traitor.(and any other antag that, hey, does not literally require you to be able to talk)

**Comment by Iamgoofball** [comment]
Being able to make an invisible wall in front of you at all times is very powerful for escaping. It makes mime traitors more overpowered compared to normal traitors. They should be on an even playing field. Clowns also already lose their downside when they become antags so why should mimes be exempt?

**Comment by ChangelingRain** [comment]
Because this isn't a downside; traitor HoPs don't lose all-access, do they?

**Comment by Iamgoofball** [comment]
Allaccess can be obtained regardless of job somehow. Invisible walls can't.

**Comment by ChangelingRain** [comment]
The bartender can throw containers without spilling them, and they don't lose that either. Nor, for that matter, do chaplains lose their null rod if they happen to be a traitor.

**Comment by ChangelingRain** [comment]
Sure, maybe you can rip the god hand off a chaplain's arm, but you certainly can't rip our their carp-sie blessing that makes them not aggro carp. They should lose that, then, right goof?

**Comment by Incoming5643** [comment]
There's no honor in taking a vow of silence if you are physically incapable of breaking it. 👎

**Comment by Iamgoofball** [comment]
@ChangelingRain i didn't know your alt was Shadowlight213

do you not understand how "i'm a traitor and I can run down a maint shaft with security in pursuit annd put an unpassable invisible wall behind me to escape every time" is way worse than "i can slide drinks around tables without spilling them"?

I understand you're pissy I'm very slightly in some way glancing at your clockcodebabby, but please, calm it down.

**Comment by ChangelingRain** [comment]
I like how you ignored all the stuff about the chaplain to go after the single bartender mention.

**Comment by ChangelingRain** [comment]
And, I'd like to note, you're advocating for the removal of the mime's _bonus_ while equating it to the clown's _downside_.

dude what

**Comment by Iamgoofball** [comment]
Clowns and Mimes would lose ALL of their abilites equally. 

You also had the audacity to deliberately cockblock my PR annd get away with it by PRing a feature to your codebaby gamemode you know will get through because who dares deny Joan's clockcult changes that specifically was made in reaction to this PR AND gives you grounds to go "lol clockcult mimes need to be able to talk so they should have their speaking".

Get a life. I'm done with your petty bullshit. I'm trying to make a game and fix some issues with a job while you're throwing all the sand out of the sandbox to be a shithead so I can't fix issues because you can get away with it because you have a fancy namebadge and have bullied enough people that they won't deny you throwing all the sand out of the sandbox.

**Comment by RandomMarine** [comment]
Explain how a mime should be incapable of speaking if he so chooses.

**Comment by ChangelingRain** [comment]
Clockcult mimes already can't recite scripture unless they break their vow, smart guy.
And yes, it was in reaction to you, but that does not necessarily make specifically to ruin your shit.

**Comment by Iamgoofball** [comment]
The entire gimmick joke of the mime job is "you can't talk or make noise". It's the polar opposite of the clown and was likely designed as such. Letting them click a button to ignore this and have the freebie infinite no cost invisible wall is bullshit.

And I find that quite frankly hard to believe, you've blocked shit before on the basis of it even involving clockcult before. You throw a fit whenever anyone tries to touch clockcult. You state you're going to deny PRs that involve clockcult for the sake of "I hate this" when they provide a good reason for existing, have player support, and a load of positive comments. Why should I believe you're not just going to use that PR as another chip to get away with "this touches my codebaby indirectly denied"

**Comment by ChangelingRain** [comment]
I'm not even complaining about the vow, just how you're planning to apply the exclusion; I don't think it makes any sense to remove the mime's wall and silence for anything other than the one single antag that requires that you speak for pretty much everything.

**Comment by MimicFaux** [comment]
Mommy and Daddy are fighting again.

**Comment by ShadowDeath6** [comment]
to reiterate my point, mime lings can't talk because it says "hurr you can't break your vow aaaaaaaaa" when you transform into the captain and HoS asks you if you're okay

**Comment by ExcessiveUseOfCobblestone** [comment]
y-y-you know you don't *have* to go mime if you don't want to deal with the, you know, mime part.

**Comment by AnturK** [comment]
Wasn't this permanent before ? This really won't stop bad mimes from *talking.

Also, please add a changelog entry.

**Comment by ExcessiveUseOfCobblestone** [comment]
enjoythe mimeban then :^)

**Comment by Arianya** [comment]
> Mime should start on equal ground to all other antags and shouldn't get any flavour

Ah yes, the role with functionally no useful tools (not even slipPDA!) should have their one upside taken away so that they are literally just an assistant with fancy clothes. 

Not to mention talking mimes are frequently lynched so the talking is its own punishment. I'd agree with tying losing the wall with breaking your vow, however.

Fuck why am I defending mime I hate both it and clown. GOOF YOU'RE MAKING ME DEFEND MIME.

Also I guess the Chaplain better lose the smoke spell when antagged since its an unfair advantage you literally can't take away from him through IC means.

Also goof, stop being a special snowflake who can't take the slightest bit of constructive criticism without freaking out holy shit.

**Comment by Iamgoofball** [comment]
The smoke spell is a book that spawns in metastation that can be taken and looted.

**Comment by Arianya** [comment]
Yes, a book that no chaplain has ever not grabbed in the first 60 seconds and which becomes useless after one use.

**Comment by Iamgoofball** [comment]
Chaplain isn't always there round start. Try again.

**Comment by Arianya** [comment]
> Y-you see, this innate power equivelant to mime's wall isn't spawned in character spawning (for fairly obvious reasons) and t-thus you have no examples to counter my weird hateboner for mime walls

How about you try again and explain concisely why the chaplain (or any antag who gets a hold of the smoke spellbook, if you prefer) should be allowed to have innate, irremovable abilities with arguably GREATER power then mime wall (coughing makes people drop in hands. AOE Disarm to anyone not on internals!) while also having access to better access (including to the crematorium, an incredibly powerful antag tool) and job-specific tools (because the null rod and soulstone are spawned on the map, not with the job) while the mime should lose the wall while having none of the other perks.

**Comment by jughu** [comment]
Smoke spell is a instant disarm if you dont wear a gas mwsk
A sight of the field disrupter
Smoke spell OP makes chaplain op against double esword!!!!

**Comment by Iamgoofball** [comment]
Holy shadowlight213, I've been baited

**Comment by jughu** [comment]
I wouldnt mind a mime spellbook tbh

**Comment by RandomMarine** [comment]
That would enable the unholy combination of clownmime to possibly exist, which just wouldn't do.

**Comment by jughu** [comment]
Still add the mime spellbook for summon magic which would curse you and force you not able to speak but dont touch the mime!!!

**Comment by BeeSting12** [comment]
Part of being an antagonist is using your job's advantages to help you/your team out. It would be stupid if everyone was on an even playing field. Also just makes talking mimes valid tbh. I valid them anyway and I've never been bwoinked for it.

**Comment by coiax** [comment]
As @Incoming5643 said

>There's no honor in taking a vow of silence if you are physically incapable of breaking it. :-1:

That's why it's a vow, and not a genetic mutation.

**Comment by AdamElTablawy** [comment]
# ITPR a bunch of talking mimes come out to defend their right to talk

lmao fuck off, you picked the one job on the station that revolves around not talking and you're complaining you can't talk? if you talk as an antag mime for any reason you deserve death, let alone nonantag mimes

if a clock cult mime gets clock cult and they can't cast their fuckbaby spells then too bad for them joan, make an exception since blood cult can invoke their spells silently too or they can suck it the fuck up and go hardmode

**Comment by ChangelingRain** [comment]
Hey look, it's missing the point o clock!
Goof's arguing that antag mimes should be able to talk and not have their spell, for reference, and I'm arguing that that's ridiculous and should only happen for the one specific antag that requires talking.

**Comment by jughu** [comment]
Make talking mimes turn into clowns
And clowns that are silent for 5 minutes into mimes

**Comment by Grazyn** [comment]
What if. You talk and you lose the spell. Permanently. For the entire round. Doesn't matter if antag, non antag or cult (you have much better spells as cult anyway).

**Comment by jughu** [comment]
^^^^^^^^^^^^^^^^^^^^^^^^^

**Comment by Ausops** [comment]
I thought part of the reason why meatspikes were added was to deal with talking mimes, so why add duplicate code??

**Comment by KorPhaeron** [comment]
Too controversial sorry

**Pull request closed without merging**
