### PR TITLE
Adds champion armour to necro chests

### PR DESCRIPTION
**Pull request by Zuvassin**
ss 2016-04-26 at 06 20 35

Credit to Ausops for the sprites.

### CODE REVIEW

**Comment by KorPhaeron** [comment]
I am gonna merge this early when I wake up because of the files it touches and because I would hate to see someones first PR suffer icon conflicts.

Unless a maintainer has objections of course

**Comment by Cheridan** [comment]
this armor looks familiar for some reason!

**Comment by KorPhaeron** [comment]
Probably because Ausops had made many lovely sprites for us before, and his style is unmistakable

**Comment by KazeEspada** [comment]
:-1: 30 melee resist is the same as the bone armor and still inferior to a fully upgraded explorer suit.

**Comment by KorPhaeron** [comment]
It's a fire proof, space proof 0 slowdown suit, the values are very good for that

**Comment by KazeEspada** [comment]
I want armor that makes me better against mining mobs, not worse. This is like giving miners bluespace beakers. Sure, its good, but its not useful for them.

**Comment by KorPhaeron** [comment]
>being entirely immune to ash storms isn't good for miners

???

**Comment by KazeEspada** [comment]
Not at the cost of my melee armor it isnt. Now its just juggling gear.

**Comment by KorPhaeron** [comment]
I guess ditch it if you don't want it then

**Pull request merged**
