### PR TITLE
"Invisible healing is bad"

### PR DESCRIPTION
**Pull request by silicons**
Well now it's visible.

### CODE REVIEW

**Comment by ChangelingRain** [comment]
Ideally these should only show up if there's actual healing being done, not just having the symptom proc.

**Comment by kevinz000** [comment]
It has to be as visible as possible to appease the anti-viro lynch mobs :^)

**Comment by PKPenguin321** [comment]
no fix it

**Comment by kevinz000** [comment]
@PKPenguin321 the complaint was they don't know you have healing untill they have to fight you and realize. If you're not in combat and healed to full how will anyone know?

**Comment by TechnoAlchemisto** [comment]
the real problem with virology is you

**Review by optimumtact — CHANGES_REQUESTED** [review]
Visible only when healing stage is reached please

**Comment by kevinz000** [comment]
@optimumtact The symptoms themselves only get triggered when the healing activates

**Comment by WJohn** [comment]
So this does the medical beamgun healing visual cue effect on any source of healing, passive or otherwise? That's really good.

**Comment by XDTM** [comment]
This is only for viruses

**Review by optimumtact — APPROVED** [review]

**Review by ChangelingRain — CHANGES_REQUESTED** [review]
Glows should only show up if there was actual healing done when the symptom activated.

**Comment by PKPenguin321** [comment]
Do what Joan said

**Comment by kevinz000** [comment]
@ChangelingRain Fixed :^)

**Review by ChangelingRain — APPROVED** [review]

**Pull request merged**
