### PR TITLE
Significantly lowers Golem's innate armor

### PR DESCRIPTION
**Pull request by JohnFulpWillard**
## About The Pull Request

Lowers Golem's 55% innate species armor to 10%.

## Why It's Good For The Game

The Golem rework has fixed a lot of problems I had with Golems, but this was by far the most important thing for me. I thought the Golem rework itself would fix it, but instead I feel it was made worse due to their speed increase.
Innately, Golems have 55% armor from their species, that is not even comparable to any other species. There's only 2 other species that have this innate armor; Zombies at 20%, and Silverscales at 10%, but both of these are Antagonist roles while Golems aren't always going to be.

Golems also now revolve around eating Matierials for their buffs, so paired with their speed increase to match Humans, I don't think this free 55% armor is justified, or fair for people they get in a fight with.
They also already have alternatives to this, the Titanium food Golem buff, which gives them brute resistance and harder punches.

## Changelog

:cl:
balance: Golems' 55% species innate armor has been lowered to 10%
/:cl:

### CODE REVIEW

**Comment by tralezab** [comment]
Just thinking out loud here: We have a lot of 0 armor, normal movespeed races. I'd rather have the golems be a bit slower again than have them join the roster of 0 armor normal movespeed races.

**Comment by moocowswag** [comment]
they eat through materials like crazy to compensate so I would nerf their hunger rate or increase the amount of nutrition they get from eating materials to compensate.

**Comment by JohnFulpWillard** [comment]
The HackMD that was implemented stated that they wanted Golem speed to match Humans: https://hackmd.io/@Y6uzGFDGSXKRaWDNicSiEg/BkRr176st

I find the armor to be too high in the past already, but the movement speed increase made it way more obvious as a problem. I'd be fine with keeping it if we lowered it to a reasonable number like 15% or something, but I don't want to go against the hackmd after it's only very recently been implemented.

**Comment by ExcessiveUseOfCobblestone** [comment]
speed is fine, they should have some inbuilt armor though relative to other races since theyre not flesh.

**Comment by GuillaumePrata** [comment]
Having armor be the effect of a buff is a lot more interesting than innate armor.

Titanium already gives then some brute resistance on top of other effects, we could even give unique armor values to each different minerals to make golems consider which buff is the most beneficial for their goals at the moment even more.

**Comment by ExcessiveUseOfCobblestone** [comment]
the armor value im thinking shouldnt be any more than 10%, just to make it distinct enough from flesh heaps

**Comment by HoodMilk** [comment]
They can't wear clothes though? The whole point of them having the innate armor is because they can't wear armor otherwise. Taking it away makes them as sturdy as a naked assistant which is not very fitting for beings made of rocks.

Zombies and Silverscales can wear armor ontop of their innate armor, which is why theirs is so low, Golems can't so theirs is high.

**Comment by JohnFulpWillard** [comment]
> Zombies and Silverscales can wear armor ontop of their innate armor, which is why theirs is so low, Golems can't so theirs is high.

That would be a good point, if getting armor wasn't otherwise possible by Golems.
As said above, Titanium is a Golem food buff that gives extra armor (and punching damage). We should be pushing the species to using that, not innate free ones like it currently has.

**Comment by IndieanaJones** [comment]
I would buff the armor to 20% and then make mining tools do more damage to them.

**Comment by ATH1909** [comment]
> That would be a good point, if getting armor wasn't otherwise possible by Golems. As said above, Titanium is a Golem food buff that gives extra armor (and punching damage). We should be pushing the species to using that, not innate free ones like it currently has.

but the sources of armor available to golems (aside from the titanium augmentation) are also available to any human in a suit of armor, no?

**Comment by CCC23** [comment]
I didnt even notice that zombies and silverscales had armor it was so low reducing their armor to 20 will put them around the same area as MABYE a mining suit with the titanium buff while making them fully vunerable to EVERY OTHER TYPE OF DAMAGE THEIR IS with no reduction and no way possible to reduce those damages in a quick amount of time. The Buffs arnt supposed to make up for their weaknesses IE not being able to wear any armor/bulky hands their a BUFF not having to constantly eat titanium to have the equivilant resistance of a firesuit. This is just going to push golems to not specialize with any other ores and defeats the entire purpose of these minerals wearing off and changing.

**Comment by JohnFulpWillard** [comment]
> The Buffs arnt supposed to make up for their weaknesses

The buffs are meant to give benefits. Not having armor is not a weakness, no other species has armor.
Humans can get armor vests in-game, Golems can eat Titanium. It's 2 different ways of getting the same goal. While eating Titanium, you can't eat other materials, while Humans wear a vest, they can't wear other suits like space suits, modsuits, or something that can hold their department's tools like RPD/Engineering bag.

> This is just going to push golems to not specialize with any other ores and defeats the entire purpose of these minerals wearing off and changing.

Titanium already grants armor now, are all Golems currently only specializing in Titanium? This PR makes no change to the material.

**Comment by ATH1909** [comment]
> > I would buff the armor to 20% and then make mining tools do more damage to them.
> 
> Idk why Mining should be stronger aganist them. This has nothing to do with mining.

bc they're rocks

> > it should also be noted that the "armor" from titanium is actually a 0.7x multiplier for brute damage, which is distinct from armor. it doesn't apply vs. (burn) lasers or stamina weaponry, for example.
> 
> They don't need to be more resistant against those sources. They are protected against temperature and pressure, and are insulated.

I was clarifying for other readers who might not have known the titanium effect off the top of their heads. it only applying to brute damage is relevant here, as most of our roundstart sec weaponry and lethal sec weaponry deals stamina and burn damage, and welders are usually the best melee weapon a civilian will have on them.

> > The Buffs arnt supposed to make up for their weaknesses
> 
> The buffs are meant to give benefits. Not having armor is not a weakness, no other species has armor. Humans can get armor vests in-game, Golems can eat Titanium. It's 2 different ways of getting the same goal. While eating Titanium, you can't eat other materials, while Humans wear a vest, they can't wear other suits like space suits, modsuits, or something that can hold their department's tools like RPD/Engineering bag.

um ackshually luminescents can get armor using the minor adaman- :blam:

I see what you're saying here, but I don't think wearing armor as a human is nearly the trade-off you're making it out to be. for example, if a human needs to go into space, they can get pressure adaptation and chug coffee and still wear their vest. most exosuit storage slot items can also fit in your belt or your off-hand, and golems don't even get that exosuit storage slot in the first place.

you're also assuming that a 0.7x brute modifier+10 armor is equivalent to human armor, which is debatable. even against brute, you're doing worse than a basic sec vest+helmet against torso or head attacks.

> > This is just going to push golems to not specialize with any other ores and defeats the entire purpose of these minerals wearing off and changing.
> 
> Titanium already grants armor now, are all Golems currently only specializing in Titanium? This PR makes no change to the material.

no, because they currently don't need the titanium or gold effect to have a reasonable amount of armor.

**Comment by moocowswag** [comment]
Reminder they cant use batons or hulk so them having armor isnt the end of the world when they cant do much against stun combat, the innate armor only delays them from being executed so they can get help.

**Comment by ExcessiveUseOfCobblestone** [comment]
i approve of re-reviewing this if it is problematic but design-wise actually being armored should be associated with getting titanium (or equivalent if new mats arise) rather than inbuilt armor regardless of mats.

**Pull request merged**
