### PR TITLE
Vine fixes and tweaks

### PR DESCRIPTION
**Pull request by ChangelingRain**
Light vines now light up when at max growth and have a light cap, making them less bright.
Explosive vines explosion delay halved.
Aggressive vines now ex_act the turf they try to spread into as well.

### CODE REVIEW

**Comment by KorPhaeron** [comment]
>buff blob
>buff vines

You're outta control

**Comment by Anonus** [comment]
I've got better code and never post feedback threads I have eclipsed you

**Comment by duncathan** [comment]
Is the fix that you removed vines

**Comment by Zilenan91** [comment]
Oh god.

Aggressive Vines now bust walls hide your women, hide your departments, it's all ogre now.

**Comment by Razharas** [comment]
>Removing the prolonged chainexplosion

Just no
It has delay for a reason
Thats reason is eargasm when you hear explosions go off one after another for minutes

**Comment by Zilenan91** [comment]
True terror

**Pull request merged**
