### PR TITLE
Fixes FRAG-12 shells to make them explode

### PR DESCRIPTION
**Pull request by Thunder12345**
FRAG-12 grenade shells now explode as intended. Still no idea how they ended up broken in the first place, but they should work now.

### CODE REVIEW

**Comment by paprka** [comment]
2 things:

1) SHOULD work now? Test your shit.

2) They broke in the first place because you copypasted.

**Comment by Thunder12345** [comment]
I said should because they worked when I tested them last time, and they broke somehow.

**Comment by paprka** [comment]
https://github.com/tgstation/-tg-station/commit/a0476d975e646887948138e66ca747e215987aea

**Comment by tkdrg** [comment]
Confclits

**Comment by Thunder12345** [comment]
Paprika, I saw that, and still don't understand how that works when they exploded fine in testing, after that commit.

**Comment by Thunder12345** [comment]
Oh god, what have I done

**Pull request closed without merging**
