### PR TITLE
Deltastation Morgue is accessible from hallways + small fixes

### PR DESCRIPTION
**Pull request by Shadark**
## About The Pull Request

Deltastation morgue is now accessible from the main hallway. Chemistry area was reduced a bit to account for this modification:

image

I also moved the shower in the morgue to the bottom wall, then realized the water sprite from the shower was generated from the wrong place, I've also modified that sprite:

image

I've made sure that the door access is correct (chem access: pharmacy/chemistry; outside morgue door: morgue; internal: morgue/medical), chemistry APC is working, disposals are working as intended... In any case, if I'm missing something feel free to point it out. I've also added some nice chairs+vending machines in that "mini-hallway", as suggested.

Edit: As suggested, I've deleted the walls that were placed under windows at chem, made no sense tbh.
Edit2: When merging from master I've noticed a small power cable missing in sci maint, I guess it doesn't matter much but I've also readded it.

## Why It's Good For The Game

Some roles such as Chef, Botanist, Chaplain, Detective, Roboticist... have Morgue access roundstart, but in Deltastation they couldn't access the morgue without going through medical (where they don't have access). Now they're free to take all the corpses they want. And, obviously, is consistent with the rest of the maps that allow hallway access to the morgue.

## Changelog
:cl:
tweak: Deltastation Morgue is now accessible from the main hallway.
/:cl:

### CODE REVIEW

**Comment by Kaffe-work** [comment]
that shower is so cursed can it please come from the side of the wall

**Comment by Shadark** [comment]
> that shower is so cursed can it please come from the side of the wall

Honestly I kinda agree, but I tried to fit it in the left/right walls but it didn't seem like the right place (left wall was next to the operating table, not cool; right wall was very dark and you can't see the shower without other source of light)., down there it looks cool. Until you activate it 🤔

**Comment by Mickyan** [comment]
Think you could fix the chemistry lab windows facing the cryo room being placed over a wall while you're in there

Those striped floor decals are cursed though, especially the one on top, don't overlap decals like that

**Comment by kriskog** [comment]
Could you get rid of the science decals on the right of the chem room while you are at it? Leftovers from when that was genetics.

**Comment by Shadark** [comment]
Sure thing, I'll get to it on Monday probably.

**Pull request merged**
