### PR TITLE
Fixed multiple issues with dynamic.

### PR DESCRIPTION
**Pull request by TheChosenEvilOne**
## About The Pull Request
Fixed multiple issues with dynamic and removed the delayed roundstart ruleset code.

## Why It's Good For The Game
Fixes and stuff

## Changelog
:cl:
fix: Midround rulesets can again be executed.
fix: Revolution ruleset has been fixed.
code: Replaced the delayed ruleset type with a delay var.
/:cl:

### CODE REVIEW

**Comment by TheChosenEvilOne** [comment]
Ignore travis, it failed to install packages with apt-get.

**Comment by Cyprex** [comment]
Were there any delayed roundstart rulesets in at all or was this just a code thing?

**Comment by TheChosenEvilOne** [comment]
@Cyprex 
Revs was the only one that used delayed rulesets, I might replace the functionality with a delay var in the roundstart ruleset (It will just call execute after a delay).

**Comment by TheChosenEvilOne** [comment]
so, the actual reason why revolution ruleset never executed was the antag_flag_override variable, it checked if people wanted to be ROLE_REVHEAD instead of ROLE_REV and you can't have ROLE_REVHEAD in your traitor preferences. 
Basically: instead of checking antag_flag_override it just checked antag_flag.

**Pull request merged**
