### PR TITLE
Removes loudspeak option from command and AI radio

### PR DESCRIPTION
**Pull request by Aranclanos**
## About The Pull Request
Removes loudspeak option from command and AI radio

## Why It's Good For The Game
Makes announcements stand out way more and all chatter becomes more readable instead of constant font changes
edit: not only announcements stand out more, but every message that is important for the player will, like injections, forcefeed, stripping, etc.

### CODE REVIEW

**Comment by Swiftkor** [comment]
Good luck getting people to listen to any sort of commands. Nobody was complaining about this tbh

**Comment by necromanceranne** [comment]
We already had this pr and all the reasons we needed to keep loud speak have been addressed there. Especially for AI, since they have no ready means of differentiating themselves from their borg minions.

**Comment by wesoda25** [comment]
AI deserves it, command players get megaphones, take their radio. Nothing I hate more than a cunt who talks only on loud volume. Maybe give it like a 4 minute cooldown on radio? Kinda wack but better than what we have.

**Comment by YakumoChen** [comment]
:-1: The AI especially needs to be distinct from the rest of the silicons, and command often needs loud mode to actually direct their crew.

**Comment by wesoda25** [comment]
> 👎 The AI especially needs to be distinct from the rest of the silicons, and command often needs loud mode to actually direct their crew.

Good is the man who can command with big stick, great is the man who can command with no stick

**Comment by YakumoChen** [comment]
In an emergency people are going to pay attention to the big text on the screen, heads and AI need to stand out.

**Comment by ATH1909** [comment]
Aw shit, here we go again.

If loud text on head radios and AIs is really so annoying, just make it slightly smaller (but still larger than normal text) instead of removing it from them.

**Comment by 81Denton** [comment]
What's the reason to keep high volume command headsets when all head lockers spawn with megaphones already?

**Comment by Militaires** [comment]
AI can use console any time so it doesnt matter for them

**Comment by YakumoChen** [comment]
...Unless the consoles are destroyed, and the downtime for announcing is very long.

**Comment by Tlaltecuhtli** [comment]
isnt announcement a verb for silicons?

**Comment by Anonmare** [comment]
@Tlaltecuhtli It's not, announcements can only be done from the comm consoles. The AI can't authenticate itself to use the Head of Staff/Bridge announcers. The announcement verb you're thinking of is VOX, which is audio only and makes no text.

**Comment by HeartwawyHorror** [comment]
If everyone is screaming on the comms in, say, a blob or nuke ops situation, no one will be able listen to anything the captain or AI is saying if they only had regular-sized text. Coordination between crewmembers throughout the entire station and, by extension, a planned, organized response would be slowed down due to that.

**Comment by 81Denton** [comment]
I feel that outright removal is too radical of an approach. What I'd prefer is a cooldown on BIG BOLD TEXT so that it can't be spammed, but is still valuable for when you want to yell about the wizard/clown/whatever.

**Pull request closed without merging**
