### PR TITLE
Add a new round end sound

### PR DESCRIPTION
**Pull request by Cyberboss**
6 second cut of this version. Can't wait forever
https://tgstation13.org/phpBB/viewtopic.php?f=55&t=9489

:cl: Cyberboss
add: There's a new round end sound!
/:cl:

EDIT: https://raw.githubusercontent.com/Cyberboss/tgstation/751a182e04212387ba9ba6714565f753d6b0325b/sound/misc/disappointed.ogg

Same as oranges link, but his might eventually GC since I forced pushed

### CODE REVIEW

**Comment by optimumtact** [comment]
https://raw.githubusercontent.com/Cyberboss/tgstation/f6953d7c709433011786f60d286ee077bc4370dd/sound/misc/disappointed.ogg

**Comment by XDTM** [comment]
I love it

**Comment by Steelpoint** [comment]
My masterpiece reaches new heights.

**Comment by ChemicalRascal** [comment]
It's what we need. Not what we want, but what we need.

**Comment by PKPenguin321** [comment]
Impure hippie memes on my pure /tg/ server... 😡

**Comment by Steelpoint** [comment]
Don't worry, I edited out the hippy memes to get to the pure parts.

**Comment by Steelpoint** [comment]
Bump

**Pull request merged**
