### PR TITLE
Temporarily reverts stun baton passive charge loss

### PR DESCRIPTION
**Pull request by ghost**
Due to https://github.com/tgstation/-tg-station/issues/7916 and https://github.com/tgstation/-tg-station/issues/7598

This can drain officer stunbatons by up to 20~40% at roundstart. I believe the same thing happens with welding tools. This bug needs to be fixed ASAP, and I'm going to revert this change for now since it's a serious balance issue.

This feature will also need to go through a voting process before being uncommented again since it's kind of unpopular and I want to get more feedback on it WITHOUT the bug that sucks up all the power at roundstart.

### CODE REVIEW

**Comment by paprka** [comment]
Gonna make sure I can even reproduce the bug again before reopening.

**Comment by Miauw62** [comment]
We know the bug happens, even if it can't be reliably reproduced. Revert
this until we figure out what the fuck is going on.

**Comment by Deantwo** [comment]
Why not just set [losspertick](https://github.com/tgstation/-tg-station/pull/7917/files#diff-94cf9c598d9000693cd54ff7275f86b5R16) to 0?

**Comment by paprka** [comment]
It's still processing

**Pull request closed without merging**
