### PR TITLE
re-adds the yellow slimecore as an EMP-proof cell

### PR DESCRIPTION
**Pull request by InvalidArgument3**
## About The Pull Request
In #54198 yellow slimecores (And their reaction in #54569) were removed because a self-charging cell was pretty broken. I feel that removing it was too much, and instead their gimmick should have been replaced with something else. This PR makes it a 5,000 capacity EMP-proof cell (half a high-capacity). I got this idea after finding the 500 charge versions in engineering, but no one ever seems to use them. 

Note that only the cell is immune to EMPs. If a borg gets shot with the ion rifle, it'll still be hardstunned for 30 seconds, it just won't lose charge. 

## Why It's Good For The Game
adds a niche cell variant that engineering or robotics might use.

## Changelog
:cl:
expansion: The Yellow slimecore plasma reaction is back in the form of creating an EMP-proof cell.
/:cl:

### CODE REVIEW

**Comment by optimumtact** [comment]
no thanks

**Comment by Sealed101** [comment]
with such a capacity nobody would use it anyhow sadly also xenobio content is very frowned upon seeing as xenobio as a whole is in dire need of a rework. sad

**Comment by ATH1909** [comment]
uh, half the maxcharge of a roundstart high-capacity cell is a bit small, don't you think?

**Comment by moocowswag** [comment]
Emp really isnt something that the vast majority of the playerbase uses aside from carbon vs borg/mech combat and very few players even use them against sec to mess with their equipment.

Even when everyone was walking around with passive healing that could be flipped into a slow decay into death with just something as simple as emp it was still very rarely used.

Yellow slime cells are very likely to go un-used even with this niche.

**Review by Mothblocks — CHANGES_REQUESTED** [review]

**Pull request merged**
