### PR TITLE
Oldstation overall improvements

### PR DESCRIPTION
**Pull request by JohnFulpWillard**
## About The Pull Request

- Adds a supermatter chamber (very barebones to allow players to set the SM up themselves, moves the storage room around to make up for this

image

- Adds a Gravity generator (the ruin is no longer magically given gravity)

image

- Adds a custodial closet and plumbing

image

- Adds an external exit to Deltastation, so you don't have to blast a hole in the wall to move machines over due to them not fitting in the transit tubes

image

- Replaced Plasma tanks (rip singulo) in Engineering storage, with SMES parts and an emitter reflector.

image

- Moves the emergency power room's cables/APC around

image

- Fixes lack of vents in the bathrooms

image

- Adds a third RTG, to help the new power for Gravity. Depending on how well oldstation rounds go, I might remove this and leave them with just solars/SM

image

- Reworks Kitchen to look cool and not have everything just shoved in a single room. Also gives botany an actual vendor instead of a crate filled with bottles & a biogen

image

## Why It's Good For The Game

Oldstation is one of my favorite spawners and my biggest problem with it is people leave when they feel they 'beat' the ruin. Adding more Engineering stuff and improving Service stuff could potentially help with this, as it would feel more worthwhile to spend your time on working towards these projects and goals, rather than just leaving.

There also used to just have 2 rooms in the northwest that just didn't have anything. I assume the hallway left is supposed to be 'alpha' station which is completely gone, but the room north (which is now going to be gravity generator) had no real purpose other than to accidentally depressurize the only pressurized room in Beta since it had no firelocks. It just wasn't really worth being there.

## Changelog

:cl:
add: Charliestation now has a Supermatter and Gravity generator chamber.
balance: Charliestation now requires the gravity generator to have functional gravity. Its botany also has a biogenerator and nutriment vendor.
/:cl:

### CODE REVIEW

**Comment by dragomagol** [comment]
Did you change the vendors to be offstation vendors? Otherwise the ghost roles won't be able to use them

**Comment by JohnFulpWillard** [comment]
> Did you change the vendors to have `onstation = FALSE`? Otherwise the ghost roles won't be able to use them

It isn’t no as far as I’m aware, I’ll change it when when get home

**Comment by MTandi** [comment]
Thank you for putting passion into this. I really think this should be turned into a real map, rather than one of the ruins, to be able to run it in isolation from the main station.

>Adds a supermatter chamber (very barebones to allow players to set the SM up themselves, moves the storage room around to make up for this
I assume this is next to the medbay. Don't you want to move the storage with emitters to engineering area as well so that you don't need to haul everything from R&D?

>Adds an external exit to Deltastation, so you don't have to blast a hole in the wall to move machines over due to them not fitting in the transit tubes
I've been using the MOD suit clamp to carry the chests around 😄 

>Moves the emergency power room's cables/APC around
Did you consider making this a bit more reliable or maybe cutting the power lines to engi and RD so that external APCs won't try to charge from this initial generator, and it will properly power the bridge APC?

>biogenerator 
Not sure about this, biogenerator for me was a huge milestone - it makes things a bit too easy in the beginning. Just vendor machine with botany chemicals is enough IMO. 
Right now you have to work for your toolbelt by killing carps or xenos, and making leather from their hides. And giving people monkey cubes from the get go is a bit too much. Cardboard is a currency in the beginning too, you have to turn the lights box to a regular one as a temporary toolbelt, and it is good as it is.

**Comment by Jolly-66** [comment]
Tiny nitpick but can you make the new SM room dirtier?

**Review by san7890 — CHANGES_REQUESTED** [review]
Thank you for your work in keeping our ruins modern, it is well-appreciated. Few things that should be addressed follows:

<details>
<summary>Click For Images</summary>

image
Your airlock uses airless plating. Definitely correct that.

image
Here too.

Actually, there's a lot of mix between airless platings and turfs-with-atmos. For example, this area:

image

That area delineated in red appears to all be normal reinforced plating, with base airless plating surrounding it. Do you want this area to be airless, or do you want it to be full of air? Do a pass and decide what you want. I'll compile this ruin for a further review once those are rectified so I don't keep tripping up on this.

image
Proper space turf here, you want a real turf.
</details>

I also could not find the custodial closet you mentioned in the PR body. Could you provide the coordinates to those? I may be going blind.

**Comment by MTandi** [comment]
I tried to play a bit with it. If you wanted to force people to use the furnace to make 10 plasteel for the gravity generator, it won't work - belts don't work without gravity 😆 

gravity

The options are to either deconstruct this hollow reinforced window and throw the ore directly to the furnace, or get the plasteel next to the dead AI, which doesn't seem right.

**Review by san7890 — CHANGES_REQUESTED** [review]
Alright, got around to compiling it.

There's currently an ongoing bug with active turfs under closed firelocks, so I've elected to ignore those for now when there was nothing else to suggest another flaw. Compiling did clue me onto more (actual) active turf situations, rather than the ones I filtered based on my intuitive knowledge. Here are the following issues:

<details>
<summary>Click for (even more) images:</summary>

image
These five tiles are normal tiles, they need to be airless.

image
This turf needs to be airless.

image
These two turfs need to be airless.

image
This plating needs to be airless.

image

Airless plating here causing active turfs, please replace this to an aired tile (unless you want to make the whole gravity generator room airless.

image
These two doors have firelocks _and_ blast doors both in the _down_ position. Would you mind swapping it out to be default (open) firelocks and shut blast doors? It just seems excessive.

image

Would you mind shuffling around either the position of the air alarm of the APC? I feel like placing the APC in a more central portion of the room it's in may make a bit more sense, but that's up to you.

image

I _really_ hate how OldStation handles areas; it causes these weird ugly lighting things. I'll probably do a pass to fix lighting issues later, but it could be nice if you could figure something out (it might take a good while though). _Entirely_ up to you, not a requirement at all.

image

Excess power cable on this tile.

image

This probably wasn't caused by you, but there's a weird layering issue that would be nice if you could touch up.

It's correlated to these tiles on these coordinates in StrongDMM:

image

It would be nice if you could just replace the plating turfs in this section with some actual flooring (probably dark iron floors to match the rest of the Core Room?) to get that visual glitch outta there.
</details>

Anyways, there are some things that you should definitely fix, and some other potential suggestions. I'll probably do my own pass on that point I previously mentioned if you don't want to spend the time doing it (perfectly understandable), just a few things that would be nice while you're still having to fix the guts of this station.

If all goes well (don't introduce more issues fixing these finer parts), we should be good to go from there. Thank you!

**Comment by conk444** [comment]
You left gravity on the solar panel floor tiles

**Pull request merged**
