### PR TITLE
Remove tags from some maps

### PR DESCRIPTION
**Pull request by MrPerson**
~~Did not touch Bird, Disc, Dream, or Meta out of fear of conflicts.~~
Disc was left completely untouched. Dream was given only a single edit to keep the syndiebomb working. All map-specific custom z's, other main maps not listed above, and all the away missions were cleaned too.

Source of these tags is DM being stupid. When you use the "Generate instances based on icon states" option, for some ungodly reason it gives those instances a tag. Which is retarded, tags are supposed to be unique to each object.

I tried searching for legit uses of tag in code and found only a few landmarks and giving mobs a tag. In any event, setting tags on map objects is probably a really bad idea anyway. EDIT: Also the syndicate nuke uses a tag, so I hardcoded a syndicate bomb type. All the maps except asteroid and disk were fixed to use it. Those two both still use the old spawners.

Exact regex used to find these so you guys can check my work

; tag = "[^"]*"
# end/middle

(?<={)tag = "[^"]*";
# begin

{tag = "[^"]*"}
# solo

### CODE REVIEW

**Comment by Anonus** [comment]
some maps(dreeeeeam) use tags to show 'directions' on objects that don't have actual directions, like most of the wall objects, which saves some mapping time. that's basically the only legit use though

**Comment by MrPerson** [comment]
That would explain why dream had more than every other map combined

**Comment by Supermichael777** [comment]
arn't you supposed to use rotation and pixel shift for that?

**Comment by Anonus** [comment]
Pixel shift doesn't produce a different, selectable instance in the little menu thing, and some objects(read, newscasters, extinguisher cabinets, lightswitches) don't have directional sprites.
I didn't do a lot of testing on what did produce a different instance but a different sprite, a changed dir(which doesn't really help on something without directional sprites) or a tag all do.

**Comment by Jordie0608** [comment]
I think you've cut the tags that were just added in #12555

**Comment by Tokiko1** [comment]
Would be nice if you could cut them from bird aswell, I am not going to push another update for a bit.

**Comment by MrPerson** [comment]
Ok, that should resolve the syndicate bomb issue

**Comment by MrPerson** [comment]
Also since I'm here, did all the away missions too

**Comment by Jordie0608** [comment]
This is still deleting tags from the syndienuke. You may want to make your regex a bit more explicit.

**Comment by MrPerson** [comment]
I replaced it with a different type that has the tag built in.

**Pull request merged**
