### PR TITLE
adds a random job button

### PR DESCRIPTION
**Pull request by Fikou**
## About The Pull Request

adds a random job button to latejoin menu
image
partial port of https://github.com/fulpstation/fulpstation/pull/41

## Why It's Good For The Game

sometimes you stare at the latejoin menu for 30 minutes thinking of what job to pick

## Changelog

:cl:
add: Random Job button in Latejoin panel.
/:cl:

### CODE REVIEW

**Comment by TemporalOroboros** [comment]
Can you make it weight jobs by your preferred jobs? I don't particularly want to wind up playing as a head because I couldn't be bothered to pick a specific job.

**Comment by Fikou** [comment]
> Can you make it weight jobs by your preferred jobs? I don't particularly want to wind up playing as a head because I couldn't be bothered to pick a specific job.

you can just reroll

**Comment by moocowswag** [comment]
Does this let people bypass job bans?

**Comment by Jordie0608** [comment]
`IsJobUnavailable()` calls `SSjob.check_job_eligibility()` which checks for jobbans.

**Comment by GoodDays13** [comment]
oh wow, I just noticed this. I forgot I made the random button thing. this is cool, I didn't really expect it to get ported

**Pull request merged**
