### PR TITLE
makes load outfit from file work again

### PR DESCRIPTION
**Pull request by Seris02**
## About The Pull Request

for some reason any time load_from() is called in load_outfit(), it just returns null, no matter what happens, even if it gets to the return TRUE line, I have tried replacing TRUE with even something like "a", and it still returns null. I can't figure it out, so this is the next best way, unless someone else has a way that shows what the actual problem is.

## Why It's Good For The Game

bug fix

## Changelog

:cl:
fix: load outfit from file works again
/:cl:

### CODE REVIEW

**Comment by Seris02** [comment]
linters are failing but it isn't my fault this time

**Comment by LemonInTheDark** [comment]
@Seris02 pull master into your branch and push, so we can run ci properly

**Comment by Seris02** [comment]
@LemonInTheDark tada

**Comment by LemonInTheDark** [comment]
> for some reason any time load_from() is called in load_outfit(), it just returns null, no matter what happens, even if it gets to the return TRUE line, I have tried replacing TRUE with even something like "a", and it still returns null. I can't figure it out, so this is the next best way, unless someone else has a way that shows what the actual problem is.

Are you sure? that doesn't make a whole lot of sense. Where do you see the behavior like that?

**Comment by Seris02** [comment]
> > for some reason any time load_from() is called in load_outfit(), it just returns null, no matter what happens, even if it gets to the return TRUE line, I have tried replacing TRUE with even something like "a", and it still returns null. I can't figure it out, so this is the next best way, unless someone else has a way that shows what the actual problem is.
> 
> Are you sure? that doesn't make a whole lot of sense. Where do you see the behavior like that?

quite sure, yes
I tested it thoroughly, in the load_outfit proc, and no matter how much I went through it, load_from always returns null. If you wanna test it, replace the line where it tries load_from in the load_outfit proc, and instead simply make it happen before the if statement, then use a few to_chat()s, or whatever you want to do, and you'll see that it actually has loaded everything, but, the value returned by load_from is still null.

**Comment by LemonInTheDark** [comment]
What codebase were you testing on? was it this one?
Cause I've hopped on live and used the outfit manager, and that just straight up wouldn't work if load_from returns null, because of how the global list it uses is generated 
image

**Comment by Seris02** [comment]
Yes, I did test it on tgstation, and yes, that is exactly the problem. load_from will *always* return null for no apparent reason, even if the outfit loads properly without any errors.

**Comment by LemonInTheDark** [comment]
Loading this json file <https://cdn.discordapp.com/attachments/458452245256601615/891567553653121054/lmao-outfits.json> seems to work fine. It might be an error with what you're trying to manually load, since that bit of admin code only accepts single entries.

I mention another codebase because skyrat's loading sounds like it would do what you describe, since they override load_from without actually returning the parent's value. <https://github.com/Skyrat-SS13/Skyrat-tg/blob/master/modular_skyrat/modules/modular_items/lewd_items/code/technical_stuff_for_lewd.dm#L644>

Could be something else though, would be a hyper weird bug, since this like, literally shouldn't be able to happen. returns should rightly return something, and if they didn't it's most likely an issue with the engine itself, rather then our code

**Comment by Seris02** [comment]
...I'm fucking stupid
I just actually tested it like multiple times and I was thinking
"WHY IS IT NOT WORKING OR DOING ANYTHING"
and I realised that I was in fact
loading the skyrat station dme file
instead of the tgstation one
sigh
it is in fact that issue, yes, thank
I shall pr the fix downstream

**Comment by LemonInTheDark** [comment]
godspeed o7

**Pull request closed without merging**
