### PR TITLE
Cultist communication changes

### PR DESCRIPTION
**Pull request by ghost**
speeches

Top: Rune/Tome
Bottom: Innate communications

Makes some changes to cultist communications. In a nutshell, communing via tomes and runes will display the user's true name (sees through gas masks and such) alongside their job. If the user has no job - from admin-spawn or something - it will not do so. The emergency communications method remains unchanged in this regard for balance reasons. Constructs will have communications akin to tomes.

Also changed some grammar with said innate comms.

This is the second PR I made for this, since the other one had some issues.

### CODE REVIEW

**Comment by Ricotez** [comment]
:+1:

**Comment by Ikarrus** [comment]
>alongside their job
If they get a job change this information will be inaccurate.

**Comment by Xhuis** [comment]
As far as I know there is zero possible way to fix that. Even then said cultist can just explain their job change.

**Comment by AlexanderUlanH** [comment]
Obviously the rune knows the cultist's immutable true calling, which is imprinted onto a spessman's soul at birth.

**Comment by Dorsisdwarf** [comment]
Merge conflicts

**Comment by Xhuis** [comment]
wut. Had no idea, I'll fix 'em when I can

**Comment by Xhuis** [comment]
Crap. I accidentally pushed to the wrong branch. I'll see if I can fix this. Whoops.

**Comment by Xhuis** [comment]
Well it's broken and there doesn't seem to be much interest in this anyway. Closing it for now :\

**Pull request closed without merging**
