### PR TITLE
De-lags sandbox a bit

### PR DESCRIPTION
**Pull request by silicons**
instead of doing a gigantic initialization of some dumb info every time someone new spawns in and by doing so spike the server for a shitload of time, why don't we just do it once???

### CODE REVIEW

**Comment by lzimann** [comment]
Doing this won't change anything. It will still change every time.

**Review by Cyberboss — DISMISSED** [review]
Shit PR

**Comment by kevinz000** [comment]
@lzimann aren't static variables global?

**Comment by Cyberboss** [comment]
Yes, but what have you actually fixed?

**Comment by kevinz000** [comment]
@Cyberboss Unless I'm reading it wrong it only generates the info if the var is null, so after it generates once doesn't that mean it'll just use the cached copy?

**Comment by lzimann** [comment]
Yea, this is mostly fine since it has a null check, so it will indeed only generate once across all sandbox datums.

**Pull request merged**
