### PR TITLE
Bread and cake slices are small sized again

### LINKED ISSUE #53482: Bread, when sliced, is too large
## Round ID:
N/a

## Testmerges:
#53441 
#53439 

## Reproduction:
Make bread.
Cut bread.
Watch as the bread is normal size, too large to fit on a serving tray.
Turn bread into sandwich, which is small size and can fit on serving trays.
Every other food ingredient like this may fit on serving trays.
This change happened due to the great bread refactor of #53047.

### LINKED ISSUE #53572: Cake, when sliced, is too large. (please stop breaking chef ok thanks)
## Round ID:
N/a.

## Testmerges:
N/a.

## Reproduction:
Make cool carrot cake or something.
Cut with the new cool snazzy refactored cake.
Realise they're normal sized cake slices for some dumb dumb reason so you cant put them on a serving tray like before (this is happening with whatever is touched by the cursed coder thats refactoring food).
Cry as you have to manually move them.
Similar to #53482

### PR DESCRIPTION
**Pull request by itseasytosee**
## About The Pull Request

fixes #53482 fixes #53572 

## Changelog
:cl: itseasytosee
fix: Bread slices and are small-sized again.
/:cl:

### CODE REVIEW

**Comment by brotherbeyondd** [comment]
game fixed

**Review by Timberpoes — APPROVED** [review]

**Comment by Qustinnus** [comment]
There's a pr for this already

**Comment by Qustinnus** [comment]
https://github.com/tgstation/tgstation/pull/53574 this one in specific

**Comment by itseasytosee** [comment]
Ok, someone should close the issues then.

**Comment by Qustinnus** [comment]
they get closed after the pr is merged.

**Comment by itseasytosee** [comment]
no I mean you should but fixes#blahblahblah so it automatically closes and mentions the issue.

**Comment by Qustinnus** [comment]
lazy

**Comment by itseasytosee** [comment]
😠

**Pull request closed without merging**
