### PR TITLE
Increases the odds of the Modular Receiver dropping in maintenance

### PR DESCRIPTION
**Pull request by Impisi**
Been a while since I added it. It's still a bit too rare considering how niche the item is. Thus I'm slightly increasing the drop chance. I've yet to see anyone use it.

:cl: Impisi
tweak: Increased chances of Modular Receiver drop in Maintenance
/:cl:

### CODE REVIEW

**Comment by TechnoAlchemisto** [comment]
It's likely that nobody is using it because 1. Making the shotgun is a hassle and 2. People who want to make it aren't willing to scour maint for it, since there are easier ways of getting it.

**Comment by Impisi** [comment]
1. Yep

2. Change should some help this issue by making it easier to find

3. Change should increase exposure to the item, as random assistants will stumble upon it more often

I'd also like to make some more interesting improvised shells in the future. Right now we only have two, a inferior buckshot shell and a supremely difficult to craft clusterfuck shell. By adding more exotic (but not necessarily lethal) shells that could be theoretically be crafted from stuff lying around, more interest could be added to the item.

**Comment by matillo** [comment]
Making a shotgun is cool, there's plenty of options for ammo thanks to autolathes being plentiful but actually CARRYING an improvised shotgun is really not worth it. You require some sort of means to protect yourself FROM being caught with a shotgun and the imp shotty is not good enough. There's a lot of work just to get crowbar'd to death with your trash gun that fires once or more likely, nonce before being gulag'd.

**Comment by Fox-McCloud** [comment]
@TechnoAlchemisto 

Not to mention you have to have access to an autolathe.

**Pull request merged**
