### PR TITLE
Mining Outpost Overhaul: Island Living Edition

### PR DESCRIPTION
**Pull request by Thunder12345**
## About The Pull Request

Replaced the old mining outpost with a new base consisting of separate buildings on islands in the middle of lava. Added a few new areas and decorations to fill out the outpost. Changed the underfloor accessibility of lava so cables and pipes don't mysteriously disappear as they cross catwalks over lava.

<details>
  <summary>Mining Operations</summary>
Contains everything needed to be a miner. Connects to the Living Quarters to the west.

image
</details>

<details>
  <summary>Public Outpost</summary>
Public lounges, gear room, basic medical facility and xenobotany (hydroponics) lab. Connects to the Living Quarters to the north, and Gulag Guard Post to the west.

image
</details>

<details>
  <summary>Living Quarters</summary>
Bedrooms bathrooms and cafeteria, everything you need to live in hell. Connects to Mining Operations to the east, the Gulag Guard Post to the west, and the Public Outpost to the south.

image
</details>

<details>
  <summary>Service Building</summary>
Hosts the outpost's power, air, and comms systems. Disposals ends in a shack outside, with a manually operated, lava based trash incinerator. Connects to the Living Quarters to the south via maintenance.

image
</details>

<details>
  <summary>Gulag Guard Post</summary>
A basic security outpost from which to monitor the Gulag. Theoretically the only entrance and exit to the gulag by land, in practice this is not strictly true. Connects to the Gulag to the west, and the Living Quarters and Public Outpost to the east.

image
</details>

<details>
  <summary>Gulag</summary>
You work for your freedom here, prisoner. Don't try to escape by sprinting across narrow spots in the lava river, and definitely don't use your hydroponics area to grow illegal plants hidden on the island by your predecessors. Connects to the Gulag Guard Post to the east.

image
</details>

## Why It's Good For The Game

The current mining station is fairly boring and dated. In addition, the general layout of the outpost was bland and uninspired, about as exciting as any other hallway. This replacement offers a new and unique take with an interesting layout and new dangers to be aware of.

The bridges between buildings are exposed to the weather, meaning you could find yourself forced to choose between waiting out a storm in an isolated building with a potentially unfriendly roommate, or running through the storm to get back to a shuttle.

Power and communications are also more vulnerable in the new base, placed in a building on the mainland where ne'er-do-wells could gain access unnoticed and sabotage them, making the mining outpost less of a safe space with little risk of anything going seriously wrong. You don't get access to these just for having mining access, better call the relevant portion of engineering to help you.

Gulag prisoners also get a few new options to keep security on their toes, with a few different options for escape routes that encourage the warden to keep an eye on their charges instead of ignoring the gulag while waiting for the prisoners to do their sentences or kill themselves.

## Changelog

:cl:
add: The mining outpost was unfortunately destroyed in an industrial accident. A replacement has been constructed on a group of islands in the magma sea.
/:cl:

### CODE REVIEW

**Comment by TrashDoxx** [comment]
Double bed? SkyRat vibes.

**Comment by Thunder12345** [comment]
> Double bed? SkyRat vibes.

Shush it's for an extra comfortable sleeping experience in the luxury bedroom for important miners only

**Comment by private-tristan** [comment]
is the exit  just catwalks? would anyone be able to just... wirecut it and make miner's jobs much, MUCH harder
image

**Comment by Thunder12345** [comment]
> is the exit just catwalks? would anyone be able to just... wirecut it and make miner's jobs much, MUCH harder 

The catwalks over lava are a subtype, currently just plain indestructible unless I can come up with a good solution to make them breakable but not ridiculously easy to grief

**Comment by TrashDoxx** [comment]
> Shush it's for an extra comfortable sleeping experience in the luxury bedroom for important miners only

I wish I could hug my fellow miner's pick now.

**Comment by Son-of-Space** [comment]
Just to point out for those reviewing that both this and #67475 redo the same area and thus only one can be added.

I obviously have more to say than just that but I will refrain.

**Comment by G0nTar** [comment]
Nice, can't wait to check this whole new complex out, getting such SUS vives from the layout, and getting trapped or risking running thru the storm and using that as an ANTAG or prisoner extra options, makes it feel so much alive than the old one

**Comment by Zytolg** [comment]
> > is the exit just catwalks? would anyone be able to just... wirecut it and make miner's jobs much, MUCH harder
> 
> The catwalks over lava are a subtype, currently just plain indestructible unless I can come up with a good solution to make them breakable but not ridiculously easy to grief

Don't make these indestructible. It's bad form.

**Comment by Thunder12345** [comment]
> > > is the exit just catwalks? would anyone be able to just... wirecut it and make miner's jobs much, MUCH harder
> > 
> > 
> > The catwalks over lava are a subtype, currently just plain indestructible unless I can come up with a good solution to make them breakable but not ridiculously easy to grief
> 
> Don't make these indestructible. It's bad form.

If you have a better solution do let me know, and keep in mind this is lavaland so them being indestructible makes them act much like an aesthetically changed tile of normal ground

**Comment by madamheichou** [comment]
If you're going to make the sections of the mining base separate, you should really put tiny fans in the outer airlocks. The whole base will suffer more venting without them, even with the double-sets of airlocks on the exteriors, since exposure to the elements will be much more common and travel time will be longer than if it were all one complex like before.

**Review by san7890 — CHANGES_REQUESTED** [review]
Not a full review as of right now, but just one thing that was brought to my attention during Test Merges.

image

Any prisoner in the gulag is able to easily cross this catwalk, and gain entrance right up until that point. From there, they are able to break the APC, allowing them to be able to crowbar their way into the rest of the base. The same thing goes for the "Guard Post" section. I'm not sure if this was intentional to reward prisoner craftiness, but it just feels way too simple for me and should definitely be nerfed down. Is it possible to move the atmos/power supply line such that they aren't able to walk across the catwalk and get relatively free access to the rest of the station? It's just way too simple to my eyes.

Also, pickaxes are able to break reinforced windows. Try and balance around that as well in future revisions. I will do a fuller review in the coming days, but I would strongly advise you address this sooner-rather-than-later (as well as the issue linked to this PR: #67899) at the very least (it does indeed look sparse of fire extinguishers as well).

I'll mark this as a draft for now, just unmark it when the points are addressed.

**Comment by Spookuni** [comment]
Additional points to above that I caught after San left - you can jump the railing on the entrance to the sec post by walking north from the prisoner utilities catwalk to escape directly into lavaland / the public mining base, bypassing the need to use the maint tunnels.

Additionally, the new gulag appears to lack an oxygen can to refill the emergency oxygen tanks of prisoners - essentially limiting how long prisoners can be down there and use the system before they run out of O2 to mine with and get stuck. And the gulag mining machine appears to lack a lever for the conveyor, so prisoners have to crawl under the flaps and retrieve materials by hand.

**Comment by newfren** [comment]
The central gimmick of the lava bridges is really annoying when you're walking around down there because of how slow you walk across them. It also feels like this depowers worse than the old lavaland base (but I don't actually have any strong feeling on this it might just be that I had a few longer rounds with it).

**Comment by VladinXXV** [comment]
The bridges are a nightmare, not only because you're going slow as balls over them at all times, but because they're exposed to the elements. I get that's part of the gimmick, but it sucks. When you've got someone in critical condition in a part of the base with no shuttle, you just have to sit around and cry about it until the storm passes, because you KNOW they won't survive crossing the slow bridge in the storm.

Having so many more airlocks directly interacting with the outdoors also increases how much lavaland atmos is getting in. This is more dangerous, annoying, and causes scrubbers to have to do more work, which I believe does result in a higher power drain. 

Not having access to your own comms or power equipment as a miner sucks. No one wants to come down there and help you fix it. As a miner, you're more dangerous to them than they are to you. Engineering has better ways to spend their time (cleaning up the mess of bombings, SM delam, dragon, etc) than risk their life to put you back on the radio.

**Comment by rasepretep** [comment]
It's never been there before, so I'm guessing this is what brought it: There is now at least one corpse right outside the mining base that has standard Shaft Miner gear, everything a player normally spawns with when they pick Shaft Miner. Feels like an oversight to have freely available PDA, Shaft Miner ID, explorer gas mask, and mining voucher for anyone who can use/misuse them.

Whether it's an issue that needs fixing, or it can do more good than harm, that's up to you to decide. Just pointing it out.

**Review by san7890 — CHANGES_REQUESTED** [review]
Review Time

<details>
<summary>Images Within</summary>

image

*heavy breathing* this could work but one day the decal order will fuck up. you _could_ make an orange subtype of every decal but if you don't care enough that's fine too.

image

Passive Vent Here please, put it in the Mining Explore area. Also catwalks on floors EWWW

image

Move vents and scrubbers out from under lockers.

image

Move vent out from under locker.

image

Move the vent out from under the stool.

image

Erratic disposals pipe.

image

If this is a public area, unrestricted access into this hallway. Doesn't particularly make sense to have it terminate in maintenance, unless that's the discrete effect you're going for.

</details>

More rooms and hallways need intercoms in general, I would advise doing `Intercom-Range-Display` in Debug Mapping Verbs (too many to list here, but like mech bay, central hallways, some gulag rooms, eastern mining lounge room, etc.). More fire extinguishers would be nice too, but I understand if you don't really wanna add too many.

Overall, strong mapping work. I've probably missed something so I'll do another pass when the above is rectified.

**Pull request merged**
