### PR TITLE
Touches up the engine heater sprite so it's obvious they don't block air

### PR DESCRIPTION
**Pull request by ninjanomnom**
:cl: Wjohnston & ninjanomnom
imageadd: Engine heaters and engines have had a minor touch up so they don't meld with the floor quite so much.
tweak: Engine heaters don't block air anymore.
/:cl:

Damn you fruit for making me use some of my rare wjohn sprite tokens just to prevent a bad shuttle change!

It was mid discussion in the other pr (#38821) but to recap: Engine heaters not blocking air required a bit more thought to be put into shuttle design and changing that is a hugbox move. The issue was with the sprite where it was difficult to tell where the heater ended and the plating underneath began, giving it the impression of being a solid wall.

### CODE REVIEW

**Comment by 81Denton** [comment]
Yeah, that's much better than just not making them pass atmos. Aesthetically, I think that heaters+engines would look even better if they didn't have plating underneath as well.

**Comment by ninjanomnom** [comment]
That's a mapping thing but yeah a different turf for high heat environments would make sense.

**Comment by vuonojenmustaturska** [comment]
what do they look like on the floor though? i can't see a different in the diffbot renders

**Comment by ninjanomnom** [comment]
image

**Pull request merged**
