### PR TITLE
Dice of Fate -> Die of Fate

### PR DESCRIPTION
**Pull request by PKPenguin321**
dice -> die
$$$ this is a confirmed ez issue zone. $$$

Fixes https://github.com/tgstation/-tg-station/issues/15096

### CODE REVIEW

**Comment by Bawhoppen** [comment]
:-1: DICE IS A BETTER WORD

**Comment by PKPenguin321** [comment]
die

**Comment by duncathan** [comment]
@Bawhoppen dice is literally incorrect. One die, many dice.

**Comment by Bawhoppen** [comment]
my point still stands

**Pull request merged**
