### PR TITLE
html_interface removal and crew monitoring console refactor.

### LINKED ISSUE #22124: The Crew Monitoring console isn't actually tgui
It's a foreign bootleg tgui we got from a dollar store because we didn't read the label.
It tries to mimic tgui to fool us old grandmas into buying it thinking it's the real thing but they use underpaid basically-slave workers instead of advanced machining plants so the cuts are way off.

Not like we'd notice, we need to get Timmy a Christmas present.

[code/game/machinery/computer/crew.dm line 93](https://github.com/tgstation/tgstation/blob/1642a32ea0d1a899f90da18014bbed9d5de30e8c/code/game/machinery/computer/crew.dm#L93)

### PR DESCRIPTION
**Pull request by AnturK**
:cl:
del: Minimap gone from crew monitoring
/:cl:
Quick changes list:
- html_interface gone
- unused card interface gone
- minimap gone from crew console(subsystem not disabled in case something else wants to use it)
- `ui_host()` now takes user parameter
- Some assets moved around.

Fixes #22124

### CODE REVIEW

**Comment by Potato-Masher** [comment]
Wew. I will not be missing this. The map never seemed to work half the time anyways.

**Comment by MoreRobustThanYou** [comment]
HTML_ui will not be missed.

**Comment by YPOQ** [comment]
#22124 I think

**Comment by ShizCalev** [comment]
#11774?

**Comment by ShizCalev** [comment]
conflict.

**Pull request merged**
