### PR TITLE
Fixing the timeline (Paradox clone fixes)

### LINKED ISSUE #80557: Paradox Clones spawn with permanent mutations (not cured by mutadone)
## Issue Summary
It seems that Paradox Clones spawn with all of the mutations that the original character currently has, but taking mutadone doesn't remove them.

## Round ID:
[221083](https://scrubby.melonmesa.com/round/221083)

## Testmerges:
[#80508: 'Tones down cyborg lover to cyborg fan' by dragomagol at commit ea2bcc1a45](https://www.github.com/tgstation/tgstation/pull/80508)
[#80304: 'Increase TGUI connection lost threshold' by lessthnthree at commit 29474fd7c3](https://www.github.com/tgstation/tgstation/pull/80304)
[#80519: 'Add system for safely manipulating JSON databases and apply it to photo albums and photo frames' by Mothblocks at commit 8bea963b43](https://www.github.com/tgstation/tgstation/pull/80519)

## Reproduction:
Roll as a Paradox Clone of a character who currently has mutations

### LINKED ISSUE #82238: hcrandom force sets your hair to white, changelings that steal your identity get appropriately coloured hair
## Issue Summary
hcrandom force sets your hair to white, changelings that steal your identity get appropriately coloured hair

## Round ID:
over probably hundreds of rounds playing hcrandom

## Reproduction:
join the round as a hardcore random character
you will have white hair
get your genetics stolen by a changeling
their hair is like, brown with a blue beard, or whatever

### LINKED ISSUE #83388: Paradox Clones ignore hair gradient
## Issue Summary
Paradox clones don't spawn with the same hair color gradients that the originals do. If the gradient is a large part of the hair, this can make the clone exceedingly obvious.

dreamseeker_uqBKrpQ3iw

## Round ID:
[229225](https://scrubby.melonmesa.com/round/229225)

## Testmerges:
[#82298: 'Wawastation' by mc-oofert at commit 1f7ced9dd6](https://www.github.com/tgstation/tgstation/pull/82298)
[#82877: 'Cult Vs. Heretic: 7 Months Later Edition' by carlarctg at commit d65b59db1a](https://www.github.com/tgstation/tgstation/pull/82877)
[#83227: '[TM ONLY] Hijacked Revision Date for v3 TGS Api' by ZephyrTFA at commit 8575d21082](https://www.github.com/tgstation/tgstation/pull/83227)

### PR DESCRIPTION
**Pull request by Lufferly**
## About The Pull Request

Fixes #83388 (Hair gradients are now part of dna, if just making a snowflake check on paradox clones is a better way to do this I  can do that too)
Fixes #82238 (Hardcore random was not supposed to set your hair to white)
Fixes paradox clones (and changelings) not having correct heterochromia colors
Fixes #80557

## Why It's Good For The Game

Bugfixes; Paradox clones are supposed to at least be a copy of the target player as they are roundstart, but right now for funkier characters  they are being outed for having the wrong hair gradient or something, which feels bad. Hopefully this can bring us to a point where medical and security records cant out the clone.

## Changelog

:cl: Seven
fix: Paradox clones (and changelings) now properly copy hair gradients and heterochromia eye colors.
fix: Hardcore random no longer mistakenly makes your hair white, this was not a feature.
/:cl:

### CODE REVIEW

**Comment by PapaMichae1** [comment]
Any chance you could be persuaded to take a crack at https://github.com/tgstation/tgstation/issues/80557?
I tried myself but couldn't figure it out

**Comment by Lufferly** [comment]
> Any chance you could be persuaded to take a crack at #80557? I tried myself but couldn't figure it out

Done, when adding mutations no class was passed which means the default class was used, MUT_OTHER. This class cant be cured by ordinary means so it meant the mutations were for practical intents and purposes permanent. I dont really get why we copy mutations but im sure theres some case im not thinking about.

**Comment by Lufferly** [comment]
Making traits use the correct sub-trait (like getting the same family heirloom) will require a big thinking cap and ill do it in another pr if I can think of a good way.

Also since I made it so that having grad_style and grad_color as null not allowed anymore, how do I account for peoples preferences theoretically still having it saved as null?

**Comment by DaCoolBoss** [comment]
Another oddity that outs paradox clones is that the clone doesn't copy persistent scars, it always spawns with none. Don't know how easy that is to fix though.

**Pull request merged**
