### PR TITLE
Removes bedsheets from holodeck

### LINKED ISSUE #26258: Holodeck: You can make cloth by using wirecutters on bedsheets in Emergency Medical

### PR DESCRIPTION
**Pull request by nicbn**
[Changelogs]:
[]:
:cl:
del: Bedsheets from infinite cloth universe were removed from the holodeck.
/:cl:

Fixes #26258

### CODE REVIEW

**Comment by bunny232** [comment]
Infinite*

**Review by Cyberboss — CHANGES_REQUESTED** [review]
No, just make holodeck beds pass the HOLOGRAM property onto their sheets

**Comment by lzimann** [comment]
I am pretty sure it already has the hologram flag, might be lacking checks to prevent it being torn into cloth.

**Comment by nicbn** [comment]
I see no merge conflict. Also, this PR is for removing the bedsheets, not for keeping them with hologram check.
If you don't like it, close this PR and I'll make another one for fixing them later.

**Comment by lzimann** [comment]
Alright then.

**Comment by nicbn** [comment]
I may have forgotten to make another one to fix it later

**Pull request closed without merging**
