### PR TITLE
Slimes can now pass through grilles because le slime

### PR DESCRIPTION
**Pull request by Militaires**
:cl: Basilman
add: Slimes can now pass through grilles
/:cl:

[why]: # >iron mesh
>stops slime

shidfugkdugkd,xdhgks.

### CODE REVIEW

**Comment by FantasticFwoosh** [comment]
Local man doesn't play enough xenobio, all the reinforced windows in the cells can be broken to create a mass slime escape through the grates or bust through heat damage (which doesn't really affect slimes at all)

**Comment by Militaires** [comment]
then dont let the windows break weakboi

**Comment by Shadowflame909** [comment]
> 
> 
> Local man doesn't play enough xenobio, all the reinforced windows in the cells can be broken to create a mass slime escape through the grates or bust through heat damage (which doesn't really affect slimes at all)

Have you ever watched any animoo. All you gotta do is a get a sword and stab the slimes in their slime core to kill them. it's in the middle of there body like a heart.

**Comment by anconfuzedrock** [comment]
what of flaps

**Comment by Anonmare** [comment]
@FantasticFwoosh Slimes physically can't damage structures on their own, not even the weak as water, plain glass directional window

**Comment by Militaires** [comment]
@anconfuzedrock what do you mean those are IMPOSSIBLE to get around, everyone knows that.......

**Pull request merged**
