### PR TITLE
Fixes Plague Doctor Mask not being able to use internals

### LINKED ISSUE #85007: Plague doctor mask no longer supports using oxygen tanks
## Issue Summary
Try using plague doctor mask to breathe from a oxygen tank.
It doesn't let you.

## Round ID:
[232178](https://scrubby.melonmesa.com/round/232178)
## Testmerges:

[#84826: 'Adds new station map Nebulastation' by KikoWen0 at commit 36f1dfa793](https://www.github.com/tgstation/tgstation/pull/84826)
[#84951: 'Ghosts once again can see people's true names and roundstart jobs' by SmArtKar at commit 67b7238ae2](https://www.github.com/tgstation/tgstation/pull/84951)
[#84964: 'Reworks silicon/ai access checking & fixes some ui_act's' by JohnFulpWillard at commit 3951a2a798](https://www.github.com/tgstation/tgstation/pull/84964)

## Reproduction:
Obtain plague doctor mask. Obtain oxygen tank. Try using the plague doctor mask to breathe from the oxygen tank.

### PR DESCRIPTION
**Pull request by DATA-xPUNGED**
## About The Pull Request

Fixes #85007

## Changelog
:cl:
fix: Plague Doctor Mask can now be used with internals again, and is no longer unintentionally pepperproof.
/:cl:

### CODE REVIEW

**Comment by GPeckman** [comment]
> Seems to have accidentally made it pepperproof, which I doubt was intended

It literally was intended:

> Attempts to fix the plague hat having pepper spray and hugger protection, **moving it to the mask instead**

Also this change still doesn't make it properly facehugger-proof.

**Comment by Draggeru** [comment]
https://github.com/tgstation/tgstation/pull/84953 

It was intentional for there to be pepperspray protection, the only thing that the mask fails to do as intended is provide face hugger protection. However the only reason that it does not protect against face huggers is because hugger protection is from hats, not masks. 

I am not sure why you can no longer use internals, as the mask is a sub type of regular gas masks iirc

**Comment by GPeckman** [comment]
It's because of this line: 

https://github.com/tgstation/tgstation/blob/ac745206f70cd0d259e261aec4ede01954bf5086/code/modules/clothing/masks/gasmask.dm#L258

The plague doctor mask has the flag to let it block smoke effects and _only_ that flag. Which means it doesn't have the flag which makes it internals-compatible.

**Comment by DATA-xPUNGED** [comment]
Aight, it was intentional so i removed that from the PR

**Pull request merged**
