### PR TITLE
Fuck Pockets Pt. 2: Labcoat Boogaloo

### LINKED ISSUE #20437: genetics labcoats still have 2 pockets
yo what the fuck

### PR DESCRIPTION
**Pull request by Cyberboss**
Fixes #20437 finishes #20129

:cl: Cyberboss
del: Labcoats no longer have pockets
/:cl:

### CODE REVIEW

**Comment by Bill-Luxe** [comment]
_sad trombone_

**Comment by alexix1989** [comment]
Fuck you

**Comment by XDTM** [comment]
Finally i'll be able to fireproof my labcoats again

**Comment by Durkel** [comment]
Pockets were a mistake.

**Comment by lzimann** [comment]
we should just remove the entire pocket system already

**Comment by alexix1989** [comment]
Maybe you should remove nerfcoders?

**Comment by lzimann** [comment]
there's no need for it, it's just more storage powercreep, the pocket system shouldn't even exist

**Comment by Poldan** [comment]
Crazy nerfcoders. Somebody has griefed you WITH DANGEROUS CRAZY POCKETS? Now, you are crying like a baby?

**Comment by PKPenguin321** [comment]
pockets were all removed and this was left in by accident

**Comment by Aloraydrel** [comment]
pockets was shit anyway

**Comment by ExcessiveUseOfCobblestone** [comment]
God made today for the pockets we didn't catch yesterday

**Comment by optimumtact** [comment]
actually the pocket system has to exist because it's better than the previous snowflake system for hidden items in things.

The fact that the UI implementation was the wrong way around by default was the problem

**Comment by Cheridan** [comment]
thank you for the bugfix

**Comment by alexix1989** [comment]
Fuck you, fags.

**Comment by CyberbossJHCB** [comment]
index

**Comment by optimumtact** [comment]
@alexix1989 if you really want to see them back make a new pr with the UI handling that triggers normal actions first and some modifier key to get to pockets, or an action button so they don't get in cheridans way in the day to day and they won't even notice when I merge it

**Pull request merged**
