### PR TITLE
Fixes the air subsystem initialization.

### LINKED ISSUE #17149: Alien weeds don't spread on 95% of tiles
There's not much of a pattern to it either. Weeds won't spread when dropped on the vast, vast majority of tiles in the game. I haven't been able to discern any pattern in what makes certain tiles work and other don't. 

If a tile does start spreading, it will (usually) spread like normal, sometimes it will only spread about 1 tile around it and then stop.

### LINKED ISSUE #17156: Atmos is 110% fucked
>Put 2 canisters of plasma/oxygen mix into mix tank
>Twice as much as I normally do
>1x1 square of fire ignites, goes out within 60 seconds
>Max'd pumps won't fill the receiving canister, no sign of plasma or fire in the tank

### LINKED ISSUE #17170: Most tiles have NO adjacent atmos, WHYYY
I finally solved the mystery behind #17156 and #17149

I checked the vars on tiles around the station, 95% of them have NO adjacent atmos turf. This explains why weeds are broken on most tiles, why the toxins mix tank is borked, why foam isn't spreading, and why syphons and hull breaches don't suck air from the surrounding area. 

SS13 is supposed to be an elaborate atmos simulator masquerading as a game, it shouldn't be doing this: http://imgur.com/33v0was

### PR DESCRIPTION
**Pull request by phil235**
Fixes #17149
Fixes #17156
Fixes #17170

### CODE REVIEW

**Comment by lzimann** [comment]
does this fix the adjacent turf problems?

**Comment by PKPenguin321** [comment]
Based Phil
a
s
e
d

P
h
i
l

**Comment by duncathan** [comment]
Based Robustin, more like
That issue report was fantastic

**Comment by MrStonedOne** [comment]
wow... my B.

**Pull request merged**
