### PR TITLE
The rest of us don't care

### PR DESCRIPTION
**Pull request by optimumtact**

### CODE REVIEW

**Comment by Qustinnus** [comment]
but i care

**Comment by Kromgar** [comment]
Please make your titles more descriptive

**Comment by outbools** [comment]
Either make descriptive comment how to leave issue on github, leave @Cyberboss contact or just leave it be as it is now. "notify coders" is self-explanatory. "notify cyberboss" is not.

**Comment by optimumtact** [comment]
you are not an admin, so please refrain from commenting on this pr

**Pull request closed without merging**
