### PR TITLE
Plumbing fixes and tweaks

### LINKED ISSUE #47147: "remove"  botton in chemfactory machine does nothing
click nothing happens

### LINKED ISSUE #47154: certain reaction glitch out chemfactory devices
reaction that delete all chemicals in the container (smoke, potasswater, etc) cause  the reaction chamber to no longer pull chemicals from the duct net, the tank device works fine

### LINKED ISSUE #47162: are chem machines working with a pipe on top of it supposed to be intended?
https://monosnap.com/file/vxVRUzkgAlM2zhzxJ9mfyJTUSrXuZw

### LINKED ISSUE #47169: Reaction chamber content explosions
Round ID: 121642 Bagel
BYOND Version: 512.1484
Server revision compiled on: 
Master commit: 1cc50a151b993e786fdc177f751109c209bfeecc 
The following pull requests are currently test merged:
#46968: 'Kilo Station' by Okand37 at commit 3fb67cb9a7 

Local commit: 6b6dce967337ef58fce81cf214f1b721a1738826
Server tools version: /tg/station 13 Server v3.2.6.2

-------

Explosions that occur within a chem reaction chamber don't damage the chamber, but spam admin logs instead with:
`ADMIN LOG: Reagent explosion reaction occurred at AREA (COORDS) (JMP). Last Fingerprint: SOME GUY(?) (FLW).`

These should either damage the machine or not create explosion logs.

### LINKED ISSUE #47187: The ducts list of the plumbing component sometimes contains nulls.
## Taken from this log
https://tgstation13.org/parsed-logs/terry/data/logs/2019/10/18/round-121674/runtime.txt
But can be found in many other logs.

## Reproduction:

```
[2019-10-18 07:50:23.389] runtime error: Cannot execute null.remove plumber().
 - proc name: disable (/datum/component/plumbing/proc/disable)
 -   source file: _plumbing.dm,132
 -   usr: Brick Carr (/mob/living/carbon/human)
 -   src: /datum/component/plumbing/reac... (/datum/component/plumbing/reaction_chamber)
 -   usr.loc: the floor (71,146,2) (/turf/open/floor/plasteel)
 -   call stack:
 - /datum/component/plumbing/reac... (/datum/component/plumbing/reaction_chamber): disable()
 - /datum/component/plumbing/reac... (/datum/component/plumbing/reaction_chamber): toggle active(the reaction chamber (/obj/machinery/plumbing/reaction_chamber), 0)
 - CallAsync(/datum/component/plumbing/reac... (/datum/component/plumbing/reaction_chamber), /datum/component/plumbing/proc... (/datum/component/plumbing/proc/toggle_active), /list (/list))
 - the reaction chamber (/obj/machinery/plumbing/reaction_chamber):  SendSignal("obj_default_unfasten_wrench", /list (/list))
 - the reaction chamber (/obj/machinery/plumbing/reaction_chamber): default unfasten wrench(Brick Carr (/mob/living/carbon/human), the wrench (/obj/item/wrench), 20)
 - the reaction chamber (/obj/machinery/plumbing/reaction_chamber): wrench act(Brick Carr (/mob/living/carbon/human), the wrench (/obj/item/wrench))
 - the reaction chamber (/obj/machinery/plumbing/reaction_chamber): tool act(Brick Carr (/mob/living/carbon/human), the wrench (/obj/item/wrench), "wrench")
 - the wrench (/obj/item/wrench): melee attack chain(Brick Carr (/mob/living/carbon/human), the reaction chamber (/obj/machinery/plumbing/reaction_chamber), "icon-x=24;icon-y=13;left=1;scr...")
 - Brick Carr (/mob/living/carbon/human): ClickOn(the reaction chamber (/obj/machinery/plumbing/reaction_chamber), "icon-x=24;icon-y=13;left=1;scr...")
 - the reaction chamber (/obj/machinery/plumbing/reaction_chamber): Click(the floor (71,145,2) (/turf/open/floor/plasteel), "mapwindow.map", "icon-x=24;icon-y=13;left=1;scr...")
```

This list really shouldn't contain any nulls and it probably causes issues if it does. @Time-Green mind looking into it?

### LINKED ISSUE #47220: Pluming using reaction chamber to make plastic breaks the reaciton chamber
## Reproduction: 1. Get reaction chamber
2. but the oil, sulp acid, and ash trough it.
3, Heat to oil production
4. After the oil is made. it wont demand any new chems

### PR DESCRIPTION
**Pull request by Time-Green**
Fixes reaction chambers breaking when exploding or using smoke
Fixes multicolored ducts not properly connecting
Fixes a runtime when unwrenching machinery sometimes
Fixes reaction chambers not accepting filter output (more like filter refusing to send)
Fixes not being able to bulk print ducts
Fixes multiducts being off-centered
Fixes remove button of reaction chamber not working (just needed to recompile tgui)
Fixes being able to built ontop of ducts
Plumbing explosions only show up in the game log and don't spam admins anymore
You can now connect machines directly to each other without ducts
Moves the plumbing constructor from autolathe to medical protolathe

closes #47187
closes #47154 
closes #47220 
closes #47147 
closes #47162
closes #47169

I didn't fix the admin log spam, I just don't know how. Do I disable all plumbing logs? Do I just make them only log once? Do I make them silent? I'd like to know.

:cl:
fix: Fixes a bunch of plumbing bugs
tweak: Moves the plumbing RCD from autolathe to medical protolathe
tweak: You can now built plumbing machines without ducts in-between, if you so wish
/:cl:

### CODE REVIEW

**Comment by carlarctg** [comment]
id be mad if the medlathe wasnt practically public

fix the bug where manually wrenched together color pipes don't work please

**Comment by stylemistake** [comment]
You have accidentally committed the dev build of tgui.

**Comment by Time-Green** [comment]
@carlarctg try using your brain think power to read PR

**Comment by Time-Green** [comment]
@carlarctg try using brain think for read pr

**Comment by Time-Green** [comment]
I compiled the UI with the normal .bat this time.

You can now also directly connect plumbing machinery to each other

**Comment by 81Denton** [comment]
@Time-Green It would be best if you stop it from logging, else it ends up looking like this:

hhh

**Comment by Time-Green** [comment]
Explosions taking place in default plumbing equipment don't admin log anymore.
They still show up in the normal log in-case shit gets wild

**Pull request merged**
