### PR TITLE
Coffee Bar is for Coffee and Coffee Accessories

### PR DESCRIPTION
**Pull request by nightred**
## About The Pull Request

This is a coffee bar, because we have a lack of coffee and coffee based accessories on Meta

This has been endorsed by Inept against his better judgment I assume.
image

A pic because you want it.
image

## Why It's Good For The Game
Is it though?

## Changelog
:cl:
add: Meta now has more access to great coffee products and coffee accessories, we all need more latte's and maccha's, and cold brews in our lives.
tweak: Moved mule bots to the cargo storage
tweak: Moved all the tools in to the smallest room in the area, it is a mess
/:cl:

### CODE REVIEW

**Comment by CoffeeDragon16** [comment]
finally a pr that fits me

**Comment by Paxilmaniac** [comment]
finally, coffee and coffee accessories

**Comment by Tlaltecuhtli** [comment]
where is the toolvendor and toolboxes now?

**Comment by nightred** [comment]
> where is the toolvendor and toolboxes now?

They were used for parts to make this amazing coffee bar.

**Comment by RaveRadbury** [comment]
@ExcessiveUseOfCobblestone would a coffee dispenser and new coffee drinks be subject to the `bar drinks` clause of the design document?

**Comment by Jared-Fogle** [comment]
isn't cyberboss blocking map additions

**Comment by ExcessiveUseOfCobblestone** [comment]
He's blocking additional maps, not additions TO maps (aka edits) unless I missed something.

@RaveRadbury Let's go with yes for now, the purpose of the limit is to ensure we dont have 500 drinks that people will never use that are mechanically the same bar the magic "how fast does this knock me silly" number.

I would not mind seeing several bar drinks go for more non-alcoholic options though, as that could actually be given more meaningful purpose beyond what kind of bar/restaurant/etc. he wants to run.

**Comment by msgerbs** [comment]
Remember when bored assistants used to build stuff like this instead of mapping it in?

**Comment by ShibaInuLord** [comment]
remember

**Comment by wesoda25** [comment]
Wait this is a serious PR?

**Comment by TheVekter** [comment]
Hm. I kinda like the little tool nook that's there now. I don't know if I'd support this without it being moved somewhere.

**Comment by Mickyan** [comment]
why would you need tools, the coffee bar is already built

**Comment by Pugie** [comment]
COSTA PR COSTA PR

**Comment by nightred** [comment]
> Wait this is a serious PR?

I do not really know

**Comment by TheBonded** [comment]
Move the mulebot room (north of the coffee bar) to inside the cargo bay and replace it with a small tool storage, so people have access to tools

**Comment by Fikou** [comment]
please put a tool vendor somewhere so the only one isnt in engineering :-)

**Comment by Farquaar** [comment]
Anyone who thinks that this is not serious PR should be sent to work camp in forest

**Comment by Ryll-Ryll** [comment]
As the official tgstation Head Barista I approve this PR

**Comment by EOBGames** [comment]
Are people really arguing over whether this is serious or not? OF COURSE IT IS, COSTA RP ALL THE WAY

(P.S. I don't see a charger for my laptop, how the hell am I meant to work on my short novel while I drink my soy-milk frappuccino with 75 pumps of caramel)

**Comment by Krysonism** [comment]
I don't like adding more static food spawns to the maps.

**Comment by RaveRadbury** [comment]
I'd much rather see a proper coffee/espresso machine (dispenser) added to the bar

**Comment by Tlaltecuhtli** [comment]
at least sprite a tea pot or a coffee machine this looks  like a downgrade, as the tool storage is a mess

**Comment by Pugie** [comment]
Actually merge and add a barista service job.

**Comment by Yenwodyah** [comment]
Literally  just a vending machine behind a counter? No sugar, cream, milk, or ice? Come on, put some more effort into it.
Also put the toolboxes back, we need free tools available at roundstart.

**Comment by Pugie** [comment]
> we need free tools available at roundstart.
why

**Comment by nightred** [comment]
> Literally just a vending machine behind a counter? No sugar, cream, milk, or ice? Come on, put some more effort into it.
> Also put the toolboxes back, we need free tools available at roundstart.

The tool boxes are visable now, we have cream, milk, sugar, branding, the whole nines.

**Comment by Capsandi** [comment]
On the off chance this is merged, could you change the security airlock visible in the picture to a maints airlock? the public has access to both sides and it is very inconsistent

**Comment by nightred** [comment]
> On the off chance this is merged, could you change the security airlock visible in the picture to a maints airlock? the public has access to both sides and it is very inconsistent

Good to note and can be fixed up in a pr that will stay merged.

**Comment by Losenis** [comment]
Here's an idea. Coffee and derivates give a mood buff in the first 15 minutes of the round much like breakfast foods.

**Comment by msgerbs** [comment]
> 
> 
> Here's an idea. Coffee and derivates give a mood buff in the first 15 minutes of the round much like breakfast foods.

If you're going to do that, tie it to time of day in game, like the night lighting.

**Review by ShizCalev — CHANGES_REQUESTED** [review]
image

**Comment by KathrinBailey** [comment]
We need more coffee stuff in general, maybe even a coffee machine.

**Comment by EOBGames** [comment]
> We need more coffee stuff in general, maybe even a coffee machine.

once the feature freeze is over I have something in mind for that

**Comment by nightred** [comment]
Well, i was coming here to close this but i guess it is liked to much....

**Comment by wesoda25** [comment]
We have the bar though...

**Pull request merged**
