### PR TITLE
Update PDA sprites to better resemble real ones, and also makes the clown PDA Much Better

### PR DESCRIPTION
**Pull request by EricZilla**
## About The Pull Request

I've always been somewhat bothered by how the PDAs looked so I decided to take it into my own hands, as I understand it this is still allowed during the feature freeze, and trust me you dont want me typing code into your game, I promise.
OLD PDAS:
b4
NEW PDAS:
smole

I would really love if this got a test merge or something to see how people feel about changing up PDAs. All the emojis attached to this came from before the final draft so, best to ignore those

Shout out to:
citttted
Who gave me the idea for the end shape I went with, and contributing that amazing clown face.

And especially to Kryson who basically waltz in, did the perspective and hueshifting for me, and vanished into the night

## Why It's Good For The Game

PDAs have always been weirdly shaped. These new sprites are more realistic and look nicer to boot. I think they also help the tablet stand out more as a unique object. 
Showing people its not that hard to work with a post GAGS sprite is an important step even if its not merged, its really easy to work with once you experiment a little.
Also that clown PDA deserves to be in game even if its just that one. Look at him.

## Changelog
:cl:
imageadd: Centcom finally sent us new PDAs. The uh, clown one keeps looking at me.
/:cl:

### CODE REVIEW

**Comment by EricZilla** [comment]
PDA presentation

This is what the patterns look like, but the actual PDAs will be one sprite shorter in this PR because people liked that shape more.

If anyone is wondering what happened. I forgot to save the DMI. It was all on me.

**Comment by necromanceranne** [comment]
long

**Comment by jughu** [comment]
My nostelgia 🥴

**Comment by EricZilla** [comment]
image
For anyone who tries to even begin saying the current PDAs look like PDAs

**Comment by SmArtKar** [comment]
These are soulless and ugly as fuck.

**Comment by Fikou** [comment]
not worth bothering if u dont fully resprite them just making them thinner is pointless

**Comment by EricZilla** [comment]
> These are soulless and ugly as fuck.

They are literally just skinnier, so, obviously the originals must suck too?

> not worth bothering if u dont fully resprite them just making them thinner is pointless

This was meant to be a compromise between everyone who would bitch if I resprited them completely and me getting what I wanted (rectangles), I do have some more refined ones around but I never intended to use them, but I might

**Comment by EricZilla** [comment]
Okay so, I made even more PDAs, I'm not really sure, like if I should just completely swap this over to them or just, post them and see if there is interest?
full power

So here are some brand spanking new never before seen PDAs, with inspiration from a lot of various places before settling on a design I liked. I am really only putting these here in case like, yalls like them. So, if you want these PR'd instead of the ones I already PR'd just tell me, if not shruggo I'll just drop it.

**Comment by EricZilla** [comment]
Okay I listened to everyone who had constructive criticism to offer, and have completely reworked this PR, and created brand new PDAs from scratch that I think everyone is going to love.

**Comment by necromanceranne** [comment]
I like this redesign. The gameboy one looks the part now. (Nostalgia trip for me since I had a GBC just like it)

**Comment by maxymax13** [comment]
too flat and clear one looks like poopy doo doo

**Comment by jughu** [comment]
If i said let us choose between the 2 pda models this would be a feature 😞

**Comment by cacogen** [comment]
NO

**Comment by MrDoomBringer** [comment]
image

**Comment by EricZilla** [comment]
Yeah sure let me do the entire HFR as my third PR of all time

**Comment by EricZilla** [comment]
Closing this again again to work on version 5 now, have a nice day

**Comment by MrDoomBringer** [comment]
The sprites you made in this PR were honestly good (my only nitpick is the buttons are overly large and lack contrast). However, the sprites we have right now are _also_ good enough that new ones would really need to be a HUGE improvement to not be seen as change-for-the-sake-of-change. I worry you could be spending too much energy on this when you could be hitting some more in-need-of-improvement targets instead - especially if you're worried about not having perfect spriting skills.

**Comment by EricZilla** [comment]
I've been through a LOT of different iterations now, and I think they are firmly getting into the actual improvement territory.
Part of the issue is I wanted to change them but only a little, and a lot of folks did point out it was a bit of a waste of effort. At this point I am trying to genuinely improve them as opposed to just making them more to my personal tastes.

Timeline for funsies:
PDA presentation
full power
rosta
gamer2
 
Still deciding between that last one and a smaller varient
gamer1

**Comment by EricZilla** [comment]
Final two versions, super torn between the two leaning smale
lorg
vs
smole

**Comment by Iamgoofball** [comment]
i like these PDA sprites

**Comment by InsaneRed** [comment]
arent we switching over to tablets anyawy

**Comment by SmArtKar** [comment]
> arent we switching over to tablets anyawy

no we are not

**Comment by MrDoomBringer** [comment]
The new small sprites are much better imo 👍

**Comment by maxymax13** [comment]
the colors are a little flat, needs highlights, but not bad 👁️ 👁️

**Comment by EricZilla** [comment]
> the colors are a little flat, needs highlights, but not bad 👁️ 👁️
> clear one makes me cry tho

Just added them highlights in, and, clear made ME cry a lot

**Comment by Mothblocks** [comment]
>>  arent we switching over to tablets anyawy
>
> no we are not

uhh yes we are once they have full parity

**Comment by jughu** [comment]
Tablets are a lowkey joke

**Comment by EricZilla** [comment]
> > > arent we switching over to tablets anyawy
> > 
> > 
> > no we are not
> 
> uhh yes we are once they have full parity

Are we? Weird. Thankfully the tablet is super easy to do for GAGS, I was sort of making an attempt at setting it up for that in the future, though my hope was getting to pick what tablet color you get from the compo machine

**Comment by AndroidMK2** [comment]
PDAs looking kinda thicc tho o.O

**Comment by Cyberboss** [comment]
Rest in peace, pokedex PDAs

**Comment by cacogen** [comment]
they look just as bad as the old ones but now they have two rows of buttons underneath them instead

**Comment by Mothblocks** [comment]
its ok tablets will reach parity someday

**Comment by maxymax13** [comment]
why did you merge it with such a bad clear pda sprite it looks like a green cube that fell in aloe vera cream

**Comment by Cyanshitcoder** [comment]
Goodbye pipboy PDAs. New sprites look alright they just don't serve a purpose other than make them smaller in a game with too much pixel hunting as it is.
Can the mining scanners get a respite? They still look like old gas analyzers pallet swaps which wouldn't be a problem if they didn't share the same sprite

**Pull request merged**
