### PR TITLE
[READY] Modifies the coloration of base human body sprites

### PR DESCRIPTION
**Pull request by JStheguy**
## About The Pull Request
Our human sprites, currently, have an ugly greyish dull tinge to them. I've managed to somewhat remedy this by adding a reddish tinge directly into the base sprites, counteracting the unnaturally dull look that they would otherwise have.

image
This is an image of all the skintones in game, plus the base uncolored image. Every odd column is how the skintone looks ingame as of this PR, while the even columns show those same skintones with the modified base sprites.

image
And here is how the modifications look in game.

## Why It's Good For The Game
Our human sprites as-is make a lot of the available skintones look like they have some sort of horrible space skin disease and makes @WJohn blow a gasket. This change makes humans look less like they have some sort of horrible space skin disease

## Changelog
:cl:
tweak: Humans have more natural-looking skin coloration.
/:cl:

### CODE REVIEW

**Comment by optimumtact** [comment]
wow this was suprisingly easy for how much of an improvement it is

**Comment by JStheguy** [comment]
Really, the hardest part was realizing that applying color blending to already colored sprites actually has some useful applications.

**Comment by MrPerson** [comment]
Technically a "better" solution would involve color matrices.

But let's be real, unless you guys want colorized purple or yellow skin, this is probably fine for our needs.

**Comment by GuyonBroadway** [comment]
I sexually identify as a blue skinned neon green haired human with a purple beard who bombs the station every round and your failure to code in colour matrices that allows me to represent this is discrimination.

**Pull request merged**
