### PR TITLE
Fixes empty defib hud

### PR DESCRIPTION
**Pull request by JohnFulpWillard**
## About The Pull Request

The defib icon state was in between a bunch of antag hud icon states man it's not MY fault it's not with the REST of the medical huds

image

????????

image

## Why It's Good For The Game

defib hud icon shows up again.

## Changelog

:cl:
fix: Missing HUD icons (Defib, clown/mime fan) once again show up.
/:cl:

### CODE REVIEW

**Comment by Mothblocks** [comment]
the answer is because i added it and i still don't know how you reorder icon states

**Comment by JohnFulpWillard** [comment]
There were a bunch of icon states just smudged between the 50 gang icons and i just deleted them all, I went through individual ones this time to make sure I don't delete actual non antag huds.

**Comment by JohnFulpWillard** [comment]
> the answer is because i added it and i still don't know how you reorder icon states

Copy the icon state, click on the icon you want it to be next to, then paste it, and delete the old one.

**Comment by Mothblocks** [comment]
too much work lol

**Comment by MrMelbert** [comment]
if i had a dime for every time the defib hub broke, i'd have two dimes. which is not a lot, but it's weird that it's happened twice

**Comment by Mothblocks** [comment]
easiest unit test of ur life

**Comment by Twaticus** [comment]
ty for showcasing this masterpiece 
image

**Review by Twaticus — APPROVED** [review]

**Pull request merged**
