### PR TITLE
admins can now var edit the sound frogs make when they are stepped on

### PR DESCRIPTION
**Pull request by ghost**
it always annoyed me that this sound based fucker couldn't even have it's stepped on sound be changed. UNTIL TODAY. Thank me later kor.

ALSO 100TH PR was taken by a frog var addition instead of my mega project :thinking:

### CODE REVIEW

**Comment by Shadowflame909** [comment]
I want frogs to play the seinfield theme when stepped on. Someone make this the main sound of frogs.

**Comment by kevinz000** [comment]
freg

**Comment by MrDoomBringer** [comment]
https://www.youtube.com/watch?v=IZnTfsC-nqY

**Review by ninjanomnom — APPROVED** [review]

**Comment by vuonojenmustaturska** [comment]
yee blorble

**Pull request merged**
