### PR TITLE
Adds logging for pyroclastic slimes.

### PR DESCRIPTION
**Pull request by Coconutwarrior97**
## About The Pull Request
Slimes spawned from pyroclastic anomalies are now logged to game.log.

## Why It's Good For The Game

Makes it easier for admins to investigate whether a slime killing people is a pyroclastic slime or not.

### CODE REVIEW

**Comment by bobbahbrown** [comment]
Could you add the location to this log line? I think you could add something like [AREACOORD(src)] which would tag the location of the anomaly or swap src for the player to use the player

**Comment by Coconutwarrior97** [comment]
> 
> 
> Could you add the location to this log line? I think you could add something like [AREACOORD(src)] which would tag the location of the anomaly or swap src for the player to use the player

I don't think there would be any benefit to adding this on the administrative side of things. Is there some use it has for scrubby?

**Comment by bobbahbrown** [comment]
@Coconutwarrior97 

I would say generally with logging things that are specific events with a definite location it's not a bad idea to include that location. 

In terms of Scrubby there may be a use for it eventually but I don't have anything planned. In a similar area of thought it could be used for those who do map generations of round data.

As I'm not an admin I can't really attest to its utility for administrative purposes but in general it's not a bad idea.

**Comment by bobbahbrown** [comment]
Thank you!

**Review by SpaceManiac — APPROVED** [review]

**Pull request merged**
