### PR TITLE
Gives the engineering hardsuit 100% rad resistance.

### PR DESCRIPTION
**Pull request by CRITAWAKETS**
##  About The Pull Request

This PR gives the engineering hardsuit 100% rad resistance including to its helmet.

## Why It's Good For The Game

Simply put, this allows more creativity with autism projects. Want to make your SM immune to pyro anomalies? Well now all engineers can work on it, instead of just the CE and borgs.

CE hardsuit still keeps its very useful fire protection.

## Changelog
:cl:
balance: Engineering hardsuits now have been given better radiation shielding and can now sustain 100% of all radiation. Just dont lick the suit's paint.
/:cl:

### CODE REVIEW

**Comment by adamkad1** [comment]
This is fine

**Comment by mrhugo13** [comment]
This is fine

**Comment by Spepbuthewranglesgithub** [comment]
im sure this will go down very well and not result in fusion canisters that fuck over the entire station being a thing again.

**Comment by GuillaumePrata** [comment]
I can see a higher Rad resistance on it, but completely immunity will remove one of the fun aspects of SM building/fixing, choosing your suit to deal with the problems at hand
SM got bombed, tank the Radiation damage for the Hardsuit, someone opened the airlock to flood the room with heat/pyro anomalies grab a firesuit, else have the Radsuit.
We already have the CE suit that can deal with everything the SM can throw at you, we dont need more of that.

**Comment by HomocidlePancakes** [comment]
Powercrèpe

**Comment by Acer202** [comment]
I think this is a good idea, or maybe make the hardsuits 90% and have the hazard jumpsuits be 10% as well. As an engineer, if the engine gets a bit of fire, you're not going to last long when it comes time to fight a delamination without a hardsuit—it doesn't take long before you melt, And even with the hardsuit, you're going to become horribly irradiated and burned being so close to the engine. Lots of times I'm faced with being limited to screaming at the CE to get his butt over to the engine when things start going wrong, because that's my only realistic, non-suicidal option due to either temperature, rads, or both. The atmos hardsuit is already temperature proof, why not make the engineering suit the other half of the coin, with the CE suit being both in one?

**Comment by GravitronBlue** [comment]
I'd prefer a rework of how radiation protection works that still has scaled tier levels of protection.

Something I had in mind was along the lines of radiation absorbtion/max tolerable amount, with percentage based resistance factored in.

Likely leads towards situations where sitting in a highly irradiated area isn't safe forever, but with protection you can last longer before needing to decomtaminate at a suit storage unit or something. (I think that's how they work now) but for mild levels you're safe provided it dissipates faster than it's being irradiated.

Causing a rad bomb event or whatever is probably still going to kill you even with station tier rad protection and anyone who isn't deathsquad/ERT. I'm torn on whether this is actually a bad thing, but I'll take feedback on this.

**Comment by Farquaar** [comment]
Why not just wear a radsuit and leave the hardsuit to someone who's actually working in space?

**Comment by Tlaltecuhtli** [comment]
hugbox, as stated in the OP, there is no need for rad immunity for doing autism project just do it safely like everyone else, rads arent even that big of a threat when they give you  like 5 min before even reducing your hp to 50 and get slowed down you can fix whatever damage and then walk to medbay to take a pentetic medipen just fine or if you are autism just build your own medbay or a medibot and acknowledge that giving yourself rad immunity isnt needed the whole point of sm is that is dangerous immagine if you could just ignore it with something free and roundstart. this also BUFFs fusion funny people as there was no spaceproof / high fire resistence suit that was also rad immune other than CE now they can even not choose a weak combat stat race like plasmaman and just law 2 open door the ai while dragging a fusion can in brig

**Comment by FloranOtten** [comment]
Hugbox. One of the balancing acts with the SME is that you have to balance heat and pressure (hardsuit things) with radiation (radsuit thing). Making all engineers immune to all radiation is a bad idea.

**Comment by Jimmius** [comment]
cleaning up a nuclear meltdown that's spitting out rads while also massively on  fire shouldn't be safe. either wear the rad suit and burn to death, or wear the hardsuit to buy enough time to save the engine but probably die to rads. it's a heroic sacrifice that makes saving the engine more thematic than just sprinting around turning valves and pumps on with literally 0 risk other than maybe getting twatted by a gravitational anomaly

**Comment by CRITAWAKETS** [comment]
The engineering hardsuit has no burn resistance, just saying.

Also the singularity generator is a thing.

**Comment by optimumtact** [comment]
the rad suit exists, stop trying to creep hardsuits to cover every niche.

it wont' fly while i'm a headcoder

**Comment by GravitronBlue** [comment]
Just to try ending things on a better closing note, I'm fairly certain that engineering cyborgs already 
cover the niche for a fire and radiation proof user.

**Comment by Dennok** [comment]
Be golem, or android(beware EMP).
Push slimeranchers to make your rad suit fire, presurre, cold proof.
All accesible on autism rounds.

**Pull request closed without merging**
