### PR TITLE
Upgraded cybernetic ears now protect against flashbangs

### PR DESCRIPTION
**Pull request by ATH1909**
## About The Pull Request

Upgraded cybernetic ears now provide a level of ear protection (the same amount that a bowman headset gives, as far as I can tell).

Being hit by an EMP while you have cybernetic ears (of any quality) will now deafen you for either thirty seconds or a minute, depending on the strength of the EMP.

The descriptions of cybernetic ears and advanced cybernetic ears have been updated.

## Why It's Good For The Game

Advanced cybernetic ears are very underwhelming, and their benefits (halving ear damage and deafness lengths) don't address the actual reason people grab ear protection: not getting knocked down from half a screen away by flashbangs.

Welder eyes provide sunglasses-like protection (technically more, actually) for your eyes at all times, so I don't think that upgraded cybernetic ears providing bowman-like protection for your ears is out of line.

Your robocop supersoldier who stores everything they need within their body no longer has to awkwardly wear bowmans to avoid getting fucked by sonic powder. :yippee:

I was kind of surprised that deafness upon being emp'd wasn't a thing already. So, uh, it is a thing now. Since damage_multiplier doesn't affect the ear damage from being EMP'd, I opted not to apply damage_multiplier to the deafness from being EMP'd.

## Changelog

:cl: ATHATH
balance: Upgraded cybernetic ears provide ear protection, similar to bowmans.
balance: Being emp'd while you have a cybernetic ear of any quality now deafens you for up to a minute, depending on the strength of the emp.
spellcheck: Tweaked the descriptions of our two cybernetic ear variants.
/:cl:

### CODE REVIEW

**Comment by ExcessiveUseOfCobblestone** [comment]
#52248 still applies

**Comment by ATH1909** [comment]
> #52248 still applies

That PR was from 3 years ago, I figured opinions might have changed.

**Comment by moocowswag** [comment]
didnt they already protect against flashbangs?

**Comment by TheVekter** [comment]
I get where Cobby's coming from. Maybe have them significantly reduce the stun duration? You could flavor it by saying that they detect exceptionally loud sounds and shut down in response, with only some of it reaching the user's brain.

**Comment by YakumoChen** [comment]
I can see where this PR is coming from too but immunity to security equipment probably should be something you can shift click on someone and see (or see on their sprite) or be antagonist equipment

**Comment by optimumtact** [comment]
i'm really not happy that you reopened a PR with the same change after 3 years

**Pull request closed without merging**
