### PR TITLE
Zombies renounce roundstart pacifism while infected, and regain it when cured

### LINKED ISSUE #36669: Pacifism trups zombie
Issue reported from  Round ID: 85440 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 512

Zombies retain the pacifism thy had in life
You don't feel like harming anybody.x50000

### PR DESCRIPTION
**Pull request by ghost**
:cl: Xhuis
fix: The Pacifism trait no longer affects you while you're a zombie.
/:cl:

Fixes #36669. Webeditor PR, as I'm not in a position to test this locally, but it should work as intended, hopefully.

### CODE REVIEW

**Comment by lordpidey** [comment]
FEATURE

**Comment by ExcessiveUseOfCobblestone** [comment]
zombies can be cured....

**Comment by ExcessiveUseOfCobblestone** [comment]
@iskyp im sorry you had to test that locally when someone could have just told you it wouldn't regain by just looking at the changes made.

**Comment by iskyp** [comment]
I tested it locally just to make sure that I was reading the code correctly
took 5 minutes anyways not a big deal

**Comment by Xhuis** [comment]
Shoooould be pretty easy to fix.

**Comment by Xhuis** [comment]
That should fix it. I also let them keep the *mob* trait (so that pax zombies should theoretically still not be able to attack, hilariously), and just cleansed the trait datum instead. E M E R G E N T F E A T U R E S have been preserved.

**Comment by XDTM** [comment]
That solution seems really snowflake, tbh. I think that adding a system to remove roundstart traits in general and readd them when appropriate would be ideal and would prevent future issues as well.

**Review by Cyberboss — DISMISSED** [review]

**Comment by Cyberboss** [comment]
Generalize it though please

**Comment by Xhuis** [comment]
How so?

**Comment by Cyberboss** [comment]
@XDTM thoughts?

**Comment by KorPhaeron** [comment]
Emergent gameplay tbh

Why do we have a pacifist trait if there are so many exceptions for whenever someone would actually want to use violence?

**Comment by Xhuis** [comment]
@KorPhaeron 
>so many exceptions for whenever someone would actually want to use violence?

This PR included, there are exactly two scenarios that pacifism is cleansed: being a zombie, and being an antagonist. I'm not gonna neuter the trait so that it just affects you in ideal cases, but I figured that having pacifist zombies was silly. If you dislike this PR, I don't mind having it closed - just close the issue too so that it's not misconstrued.

@XDTM Something like that is theoretically doable, but such a sweeping change is outside the scope of this PR unless it's included in the "generalization" that's been requested. I still don't know what y'all want by that.

**Comment by XDTM** [comment]
While checking for the pacifism trait when someone turns into a zombie does work, it's a very specific case; if something similar comes up again we'd have to add another check, another specific var, and so on.
A generic system to disable/enable all relevant traits will keep the code neater and will very likely end up being useful to future coders.

**Comment by Xhuis** [comment]
So something like a `disable_trait_datum(path)` proc that would temporarily remove it, with a vice-versa `enable_trait_datum(path)` or somesuch?

**Comment by XDTM** [comment]
The way i'd personally do it is giving a `var/trait_type = "physical" or "mental"` to each trait, and have a `disable_traits(type)` proc. Zombie would shut down all mental traits, keeping the physical like nearsightedness. And like i mentioned a proc like transfer_traits(type) could be added in a separate PR, for mindswap and cloning.

Sidenote, the fact that there are two different systems that are called traits is going to get really confusing eventually

**Comment by Xhuis** [comment]
Since this could be better accomplished with a more in-depth method that I don't have the drive to code right now, I'll close this PR for the time being. When I next get the urge to work on traits, I think I'll try to make some sort of "enable/disable" system like has been mentioned. You nerds seem to like pacifist zombies anways. :p

**Pull request closed without merging**
