### PR TITLE
ports shuttle chairs from ftl

### PR DESCRIPTION
**Pull request by DaxDupont**
dreamseeker_2018-06-20_23-44-33

:cl: Dax Dupont
imageadd: CHANGE PLACES, SHUTTLE CHAIRS HAVE BEEN CHANGED AGAIN.
/:cl:

Since @Cyberboss is adamant about not reverting them completely, against everyone's better judgement, we needed to replace the horrible chairs.
These at least fit in a little better.

### CODE REVIEW

**Comment by GunHog** [comment]
Must you nuke them completely? You could put them in Head of Staff offices or something...

**Comment by DaxDupont** [comment]
@GunHog because they look like absolute cancer no matter where the fuck you put them

**Comment by deathride58** [comment]
Aren't these just goon's shuttle chairs sprites?

**Comment by CosmicScientist** [comment]
I guess aeroplane seats make more sense for a *shuttle* of all things.

**Comment by Memager** [comment]
old ones can be syndie seats

**Comment by DaxDupont** [comment]
@deathride58 i got them from ftl, not sure where ftl got em.

**Comment by Cyberboss** [comment]
Can these be changes to comfy chairs with an armrest overlay by any chance?

**Comment by optimumtact** [comment]
these also look quite shit

**Comment by DaxDupont** [comment]
@Cyberboss I can't do sprites well enough.
@optimumtact honestly I'd just go back to to old chairs.

**Comment by DaxDupont** [comment]
@Gannets I was wondering where they came from, FTL didn't log where the sprites came from.

**Comment by Gannets** [comment]
Well glad I could solve that mystery. Personally, I blame @Qustinnus for any and all trouble caused.

**Pull request merged**
