### PR TITLE
Sanity checks slime chems

### PR DESCRIPTION
**Pull request by Iamgoofball**
they were failing unit testing because they made the huge mistake of assuming they only ever mix in a slime core, which is stupid especially in this video game

### CODE REVIEW

**Comment by XDTM** [comment]
Tbh you kinda want a runtime if they happen outside of one

**Comment by Iamgoofball** [comment]
I'd rather not, especially when it gets in the way of unit testing

**Comment by AnturK** [comment]
All these seem to have required container set. How are these reactions happening outside of designated ones ? You're just hiding a bug instead of fixing it.

**Comment by Cyberboss** [comment]
Something about his test is probably forcing them to react regardless of container

**Comment by AnturK** [comment]
Please, if you're not adhering to the system requirements the test is effectively broken.

**Comment by Iamgoofball** [comment]
@AnturK would you like to go figure out how to set up a system that works perfectly with every potential atom in the game?

**Comment by AnturK** [comment]
I want you stop wasting my time with hyperboles and fix your test instead.

**Comment by Iamgoofball** [comment]
So you've got a solution then? It's not a hyperbole, it's a literal situation I ran into and is why this PR exists.

**Comment by Iamgoofball** [comment]
Additionally, why would I close a PR that adds sanity checks?

**Comment by XDTM** [comment]
I think that the overall reasoning is that adding those sanity checks won't prevent issues with the game; instead it will just prevent the runtime if something weird happens, hiding the mistake.
Since the whole point of these unit test is to throw errors for stuff that normally wouldn't, like conflicting chem recipes, it's better to not sweep stuff under the rug if it won't cause severe issues in game otherwise.

As for the solution, perhaps you can add some kind of force arg to ignore the required container and similar constraints? It won't be perfect, but at least it allows recipe testing for container specific reactions.

**Comment by AnturK** [comment]
You're literally testing system misuse. Do you expect fire reaction to work fine on airless turf if forced ? Do you expect Life tick to pass fine on uninitialized mob ? What's the point of a test that just does random calls.

And i really see no issue with implementation here. You just use the designated container ? What's the problem here ?

**Comment by Iamgoofball** [comment]
Because I have to type cast it.

**Comment by AnturK** [comment]
You mean like obj or atomeven where reagents are defined

**Comment by SpaceManiac** [comment]
Intended to support #39074 which is closed, and does so in an undesirable way.

If/when you return to this, my suggested solution is simply checking `required_container` on reactions and creating one of those to run the reaction in if a beaker is insufficient.

**Pull request closed without merging**
