### PR TITLE
Removes Starlight

### PR DESCRIPTION
**Pull request by Kapu1178**
## About The Pull Request
Mothblocks says that developers shouldn't have to use configuration or compile flags to get a smooth build & init speed. 

So we're removing Starlight, due to it's massive init cost.
(Coderbus link)
https://discord.com/channels/484170914754330625/484170915253321734/1050320740114767872

image

## Why It's Good For The Game
Improves development experience :D
## Changelog
:cl:
del: Starlight & related mutation
/:cl:

### CODE REVIEW

**Comment by dragomagol** [comment]
Completely opposed. Our visuals shouldn't be suffering because of optimizations like this.

**Comment by Kapu1178** [comment]
> Completely opposed. Our visuals shouldn't be suffering because of optimizations like this.

https://github.com/tgstation/tgstation/pull/71746

**Comment by timothymtorres** [comment]
I think removing the symptom entirely is overkill.  It would be better to just check the tile the player is on and if they are standing on a space tile or glass floor then apply it's effects.  I'd also increase the healing boost effect since it would make triggering the symptom more rarer.

**Comment by Timberpoes** [comment]
Mothblocks says many things.

If Mothblocks intended PRs like this to pop up, they can always reopen this.

But I don't like the way this PR just carves a feature out wholesale on what I consider flimsy reasoning from the body of your PR.

**Comment by LemonInTheDark** [comment]
> I think removing the symptom entirely is overkill. It would be better to just check the tile the player is on and if they are standing on a space tile or glass floor then apply it's effects. I'd also increase the healing boost effect since it would make triggering the symptom more rarer.

Tim that is unrelated

**Comment by Kapu1178** [comment]
> Would you not kapu

I'm not happy with hypocrisy actively degrating the user experience of the game. I'm making a point that this is stupid.

**Comment by Mothblocks** [comment]
There is no hypocrisy, you are just an asshole

**Pull request closed without merging**
