### PR TITLE
Removes Every Map Except Pubby

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request
I put ".8ball Should I remove every station except pubby" in tgstation-general and the bot said yes.

## Why It's Good For The Game
image

## Changelog
:cl:
del: Every station except pubby is d
/:cl:

### CODE REVIEW

**Comment by brotherbeyondd** [comment]
based

**Comment by trerri** [comment]
based

**Comment by 81Denton** [comment]
on one hand, pubby is love
on the other hand, 🤔

**Comment by Paxilmaniac** [comment]
This is so sad gamers the dream is over

**Pull request closed without merging**
