### PR TITLE
CQC PR: NO MERGE CONFLICT EDITION (hopefully)

### PR DESCRIPTION
**Pull request by Militaires**
henk

:cl: Basilman
A third martial art, CQC, has been added, comes with five powerful moves and innately superior punches, disarms, and grabs.
/:cl:

update: what the fuck clock cult get out of my pr
update: is there even a difference in that clockitems.dm file i didnt touch

### CODE REVIEW

**Comment by Militaires** [comment]
what the fuck clock cult get out of my pr hold on fixing this

**Comment by Militaires** [comment]
is there even a difference in that clockitems.dm file i didnt touch

**Comment by xxalpha** [comment]
>more martial arts memes

**Comment by Kraseo** [comment]
Remember the basics of CQC, Snake.

**Comment by PKPenguin321** [comment]
once again, stupider version of krav that exists exclusively to be harder to use + a MGS meme

**Comment by Militaires** [comment]
@PKPenguin321 

>harder to use

>i literally made an override of ctrl click to count as a grab to make this easier.

>grab + harm by itself is a reliable stun and you can put someone to sleep to top it off after that.

>you dont even need to use the meme moves to benefit from it as it increases your damage and makes your disarms more likely to succeed.

>much deadlier than krav which is shit and has 3 memey moves only, literally the only tactic that it is useful with is leg-sweep + spam lung punch, neck chop is a meme that is useless during combat.

>you can fucking kick people back like with a baseball bat, into walls, to make them barrel off into space at hi-speed or to hit someone else.

>your grab intent immediately aggressive grabs so if you use it they'll need to resist, and you can choke hold them during that so they're fucked, literally 1 click to assert dominance.

>harder to use

**Comment by optimumtact** [comment]
What did you do in bureaucracy.dmi ?

**Comment by Militaires** [comment]
@optimumtact 
sprite for CQC manual is kept there cause book.

**Comment by optimumtact** [comment]
as I said on the previous pr martial arts aren't used enough to justify having multiple selections for antags.

Just replace kravmaga with this if you intend to remake this pr.

**Comment by PKPenguin321** [comment]
Or don't because Krav's system is superior

**Pull request closed without merging**
