### PR TITLE
Adds space buoys

### PR DESCRIPTION
**Pull request by chanoc1**
:cl:
add: Added space buoys. Now you will never get lost in space again.
/:cl:

Added space buoys. Some nice fluff to make the station feel more alive.

### CODE REVIEW

**Comment by chanoc1** [comment]
shit

**Comment by JJRcop** [comment]
Whoa look at that diff

**Comment by chanoc1** [comment]
sh

**Comment by coiax** [comment]
The sprites are a little weird ( @WJohn ), but I like the idea. It's another way to make the outside of the station more navigable by people without jetpacks without having to spam lattices everywhere

**Comment by chanoc1** [comment]
whats up with the sprites? some CC would be nice

**Comment by chanoc1** [comment]
y'know something tells me im not doing this right

**Comment by SweaterKittens** [comment]
The sprites look a little two-dimensional to me, and while I really like the sign part, I think the bottom doesn't look very round. Just my two cents.

**Comment by chanoc1** [comment]
hm... ill make some edits=

**Pull request closed without merging**
