### PR TITLE
Removes Grandpa as a random first name

### PR DESCRIPTION
**Pull request by Coconutwarrior97**
## About The Pull Request

Removes Grandpa from the first name list. 

## Why It's Good For The Game

Grandpa is no longer an acceptable name under naming policy since it falls under a honorific/nickname, so there is no reason for it to be generated as part of a random name.

## Changelog
:cl:
del: Removed grandpa from the first name list. 
/:cl:

### CODE REVIEW

**Comment by anconfuzedrock** [comment]
merge this after we start consistently enforcing naming policy and ban bal DI and all the moths with one word names.

**Comment by bobbahbrown** [comment]
make grandpa a config option NOW

**Comment by Nickkoranda** [comment]
merge this now now NOW

**Comment by nemvar** [comment]
I hate this

**Comment by granpawalton** [comment]
Grandpa as a first name should have a heavier randomize weight than the others

**Comment by OverlyGeneric** [comment]
> Grandpa as a first name should have a heavier randomize weight than the others

Grandpa/Grandma should have significant weight for older people in the 80-90 ranges.

**Comment by Barhandar** [comment]
>grandpa isn't fine under naming policy  
>yet somehow argonian names for lizards do follow naming policy for lizards even though they're not verbs-the-noun

**Comment by Arianya** [comment]
Bikeshedding about policy or its enforcement is irrelevant here.

As is :-1:ing because you want Grandpa to be policy compliant.

If you want Grandpa to be naming policy compliant or you have complaints about the enforcement of the naming policy then that's Policy Discussion stuff. This is just bringing the code in line with the policy.

**Comment by FantasticFwoosh** [comment]
But 'Ostrava Of Nanotransen' and Weeb honorifics haven't been culled yet?

**Comment by ExcessiveUseOfCobblestone** [comment]
Pepper Oni still exists

**Comment by PKPenguin321** [comment]
I thought separation of server and code was absolute....

**Comment by ExcessiveUseOfCobblestone** [comment]
The alternative is people get banned because the game gave them a bad name.

**Comment by PKPenguin321** [comment]
You're able to check if they randomnamed

**Comment by PKPenguin321** [comment]
Foolish nu-maintainer, you're upsetting the natural order

**Comment by ExcessiveUseOfCobblestone** [comment]
I get paid per PR merged.

**Comment by RaveRadbury** [comment]
**_

> With this PR's merge, the thread of prophecy is severed. Restore a saved game to restore the weave of fate, or persist in the doomed world you have created.

_**

**Pull request merged**
