### PR TITLE
adds music sources to .ogg metadata for nerds

### PR DESCRIPTION
**Pull request by cacogen**
[why]: # (Please add a short description [on the next line] of why you think these changes would benefit the game. If you can't justify it in words, it might not be worth adding:) 

i always wondered where traitor.ogg was from and yesterday i happened to be playing minerva: metastasis and was surprised to hear it play. i looked it up and found that the track was originally from that mod.

i then looked up the other lobby music because i'd always been curious where those were from (only knowing the gameboy robocop theme) and found those had already been sourced by other members of the community over multiple youtube videos.

there's currently no centralised place to find this information and the first place people look is the files themselves so it makes sense to update the metadata to show it.

### CODE REVIEW

**Comment by Supermichael777** [comment]
The unifying factor is our lack of licensing for all of it

**Comment by coiax** [comment]
Bay prints the name of the track in the lobby.

**Comment by Niknakflak** [comment]
ok and?

**Comment by RemieRichards** [comment]
@MrStonedOne do you know if the metadata is stripped out when the sounds go into the rsc? I'm guessing no.

Cos otherwise I don't want this in the files themselves.

**Comment by cacogen** [comment]
>Cos otherwise I don't want this in the files themselves.

why?

**Comment by MrStonedOne** [comment]
ya, its not stripped.

**Comment by RemieRichards** [comment]
@cacogen I explained myself quite well I feel, but here it is again:
"If the metadata isn't stripped out of the rsc (MSO has just confirmed it is not), I don't want it in the files themselves"

The rsc gets sent to player's clients, this metadata has NO use to clients, as they won't even be able to look at it without decompiling their rsc, therefore this metadata should remain in the repository, and not in the files where it ends up getting bundled into the rsc, increasing the rsc's size needlessly.

Just a .txt of "path/to/some/sound.ogg -> FreeSound.org by Michael McMusic" in the sound folder would be good enough.

**Comment by AnturK** [comment]
It's 2KB IN 782KB file, but i can understand the sentiment. Maybe some place you can look it up in game would be better.

**Comment by optimumtact** [comment]
2kb lol

**Pull request merged**
