### PR TITLE
Buckle Up: Shuttles now punish you for riding safely

### PR DESCRIPTION
**Pull request by Iamgoofball**
:cl: Iamgoofball
fix: Shuttles throw you backwards again when they depart. Buckle up.
/:cl:

### CODE REVIEW

**Comment by Buggy123** [comment]
D O I T

**Comment by awesine** [comment]
test-merge

**Comment by ninjanomnom** [comment]
As mso said earlier knock it down to 1 or 2 and this is possibly a decent change.

**Comment by MMMiracles** [comment]
this essentially throws anyone not buckled in to the back of the shuttle, no matter how far up they are

it also means if the back is missing, they'll get flung into space

this is a good change

**Comment by 81Denton** [comment]
Does that apply to the mining shuttle, arrivals and white ship too? Very good

**Pull request closed without merging**
