### PR TITLE
Replaces the One Mind sprite

### PR DESCRIPTION
**Pull request by Kierany9**
## About The Pull Request
Instead of telekinesis halo but pink it's now the clock cult servitude aura but pink because you couldn't see the TK one too well behind hair/hats/beards

## Why It's Good For The Game
more pink = more quality

## Changelog
:cl: Kierany9
imageadd: The sprite for members of the One Mind has been updated to be much more noticeable.
/:cl:

### CODE REVIEW

**Comment by Mickyan** [comment]
rogue white pixel on the front (?) sprite, upper left corner

looks a bit odd to me tbh, how come the pulsing more pronounced around the feet and head?

**Comment by habader** [comment]
image?

**Comment by KomradeSpectre** [comment]
> image?

You can look at the sprite difference on the "Diffs - Pull Request" details at the bottom of the PR here.

**Comment by KomradeSpectre** [comment]
Aside from the rogue pixel tho (which I assume you accidentally grabbed onto by using mob/human.dmi/human as a base, it is a much better tell than the telekinesis overlay.

**Comment by Kierany9** [comment]
i don't see the rogue pixel
will get an ingame screenshot later, but the only thing that looks a bit weird are the side sprites showing less of an outline than the front/rear sprites

**Comment by KomradeSpectre** [comment]
image

It's on one of the frames of animation. Specifically this frame.

**Comment by Kierany9** [comment]
made the side sprites more thicc like the front ones, (hopefully) removed the rogue pixel and fixed some weird colours

image

**Comment by KomradeSpectre** [comment]
Did a glance over, rogue pixel is gone. Good work. Also, that's a nice tell similar to the clockcult's glowing aura.

**Comment by pizzatiger** [comment]
What if you had pink threads that connect to the slaves person and goes into the air, Give it a puppet strings type vibe

**Pull request merged**
