### PR TITLE
Fixes Wrestling Belt

### PR DESCRIPTION
**Pull request by Iamgoofball**
:cl: Iamgoofball
fix: Fixes the Wrestling Belt not being purchasable, Bawhoppenn style.
/:cl:

not being purchasable

### CODE REVIEW

**Comment by PKPenguin321** [comment]
Nice meme

**Comment by kevinz000** [comment]
How is this balanced..?

**Comment by Iamgoofball** [comment]
This is radically different from carp you wanna go m8??????

**Comment by PKPenguin321** [comment]
Yeah this thing is super fucking busted last I checked

**Comment by Iamgoofball** [comment]
no it works theres only visual effects

**Comment by PKPenguin321** [comment]
i mean busted as in it's overpowered as fuck

**Comment by Iamgoofball** [comment]
there's a simple way to fight it and it's "dont get in close quarters with the guy wearing the super bright yellow belt"

**Comment by PKPenguin321** [comment]
didn't go well the last few tests we had in which someone (actually i think it was you) went around killing literally everybody with instant permastun neckgrabs only to be eventually stopped by something even more overpowered (hacked mules)

**Comment by Iamgoofball** [comment]
hacked pAI mules*

**Comment by Thunder12345** [comment]
To be honest this should stay a TC trade thing. With how powerful it is it'll just end up getting used constantly until it's merged into the ground. I think it's a much better thing to have as a special gift from the admins for people trading their TC to become a wrestler.

**Comment by Iamgoofball** [comment]
remember when you fuckers told me "oh we can just make it a traitor item down the line"

**Comment by Iamgoofball** [comment]
this was added with the sole purpose of being a traitor item

**Comment by optimumtact** [comment]
No it was just for admin use.

**Pull request closed without merging**
