### PR TITLE
Gives krav maga gloves to the warden

### PR DESCRIPTION
**Pull request by PKPenguin321**
Part of 3 PRs intended mainly for test merging (and possibly eventually actually merging if the test goes well) that have to do with giving sec krav maga

[Check out the krav maga for sec poll on the forums right here.](https://tgstation13.science/phpBB/viewtopic.php?f=10&t=6466)

~~Check out https://github.com/tgstation/-tg-station/pull/17044 and https://github.com/tgstation/-tg-station/pull/17045 for the 2 sister PRs~~ They got closed

:cl: PKPenguin321
rscadd: The warden's locker now contains krav maga gloves.
/:cl:

### CODE REVIEW

**Comment by Man-Shroom-** [comment]
for posterity

only if stungloves are re-added

stungloves would obviously be nerfed in the following ways

1. Only one charge
2. Don't stun for a silly amount of time
3. Very obvious sprites

**Comment by FantasticFwoosh** [comment]
To be honest, while the warden isn't per say the most active out and about member of sec, they are the one most reliant on quick robust action via precise shots with gun-play or robust close hand combat. Being able to intercept a sudden strike team of nuke ops long enough for sec to pull together trying to burst in through armory will have to put up with the warden going full robust combat specialist on them. Taking down people without having a baton to steal on display is invaluable for such specialized personnel in charge of guarding the armory.

Giving the warden krav maga is probably more balanced than 10 security officers, and takes the spotlight away from the HOS (who's a walking pinata with command access and better tier stuff already)

**Comment by PKPenguin321** [comment]
yeah, IMO this is my favorite of the 3 PRs. warden has an extra good reason for having it over the rest of sec. if any of the 3 end up getting merged i'd like it to be this one.

**Comment by Core0verload** [comment]
Yes, this is the best one. It at least adds unique gear to warden, and warden currently lacks any. Plus, the warden must use those to protect brig and armory, not to hunt antags stationwide. It sort of balances itself out.

**Comment by xxalpha** [comment]
I have no problem with this item, but I think security doesn't need more shit.

Give it to ERT, Syndicates and one in the vault safe.

**Comment by Fox-McCloud** [comment]
>Add a spare pair to warden's locker too.

If you're going to do this, you might as well give it to the HoS, too, because he's just going to raid the locker for them, 'cause he can (or the Captain).

**Comment by PKPenguin321** [comment]
>>Add a spare pair to warden's locker too.

I will not

**Comment by Iamgoofball** [comment]
@PKPenguin321 Take them off the warden and then put them in the locker, so if hop opens warden slots we dont have 50 krav magas, and also so if there's an officer promoted to warden they're not shittier

**Comment by Nanotransistor** [comment]
Well, the warden already has the entire armory at his disposal if shit really hits the fan. I've seen more than one "borrow" and egun at round start.

**Comment by PKPenguin321** [comment]
Why is the HoP even able to create more wardens

**Comment by Iamgoofball** [comment]
@PKPenguin321 because he can reopen job slots of any job because thats his job and department?

**Comment by PKPenguin321** [comment]
I thought snowflake roles like warden and QM and heads weren't reopenable

**Comment by AdamElTablawy** [comment]
Only heads 

HoP can if he feels like it close every job but warden and watch the brig get angrily guarded by fifty flashbang-spamming neckbeards

**Comment by KorPhaeron** [comment]
Put it in his locker instead of on him please

**Comment by PKPenguin321** [comment]
Will do later today

**Comment by PKPenguin321** [comment]
Should be good to go

**Comment by KorPhaeron** [comment]
I regret this already and I have not hit the button yet.

**Comment by PKPenguin321** [comment]
Did you ever testmerge it at all

**Comment by KorPhaeron** [comment]
I thought you guys already tested this once

**Comment by KorPhaeron** [comment]
And no because we've been busy with goon crit and demon game modes and cult every other day and all sorts of stupid shit

**Comment by Iamgoofball** [comment]
mind putting this on the priority queue for testmerging? he's been waiting awhile

**Comment by PKPenguin321** [comment]
I begged for testmerge in coderbus a few times but afaik it never happened

I'm fine with not merging this until testmerges are ran, maybe a poll, whatever you want. It's no rush

**Comment by KorPhaeron** [comment]
I was just gonna merge this for real and then take feedback on that, it's a one line revert so its less effort this way than trying to babysit rounds to see them get used.

**Comment by Iamgoofball** [comment]
ale mao

**Comment by KorPhaeron** [comment]
This way we dont have to worry about other updates/testmerges kicking yours out before we find out anything interesting

**Comment by PKPenguin321** [comment]
True

Fire away then

**Pull request merged**
