### PR TITLE
Tactical anti ERP cameras in dorms 4

### PR DESCRIPTION
**Pull request by Ty-the-Smonk**
## About The Pull Request
Nanotrasen has recently employed cameras on the stations of box, meta, and delta in order to combat ERP shenanigans, they have been placed in dorms 4 specifically.

## Why It's Good For The Game
If illegal ERP is detected using these cameras they will automatically record and sell the tape to the highest bidder, meanwhile Nanotrasens finest will apprehend and smite the sinners

## Changelog
:cl:
add: Cameras to dorms 4
/:cl:

box
delta
meta

### CODE REVIEW

**Comment by Ty-the-Smonk** [comment]
i may have fucked up some where

**Comment by Ty-the-Smonk** [comment]
ill fuck with this later im going to bed

**Comment by PKPenguin321** [comment]
doesnt the camera in the main dorm area start with an xray upgrade
that or i would give it one every round at one point

**Comment by Ty-the-Smonk** [comment]
Nah it doesn’t start with it

**Comment by Ty-the-Smonk** [comment]
i fucked up and need to remake the pr

**Pull request closed without merging**
