### PR TITLE
Golem shells can no longer fit in bags

### PR DESCRIPTION
**Pull request by Robustin**
🆑 Robustin
tweak: Golem shells no longer fit in standard crew bags.
/🆑

RIP Personal-Army-In-Your-Bag Strats

### CODE REVIEW

**Review by XDTM — APPROVED** [review]

**Comment by Ratvar** [comment]
Clockscarab shells no longer fit in your backpack? Drone shells can no longer fit in your backpack?
Slime cor...

**Comment by Armhulen** [comment]
Not an argument lol

**Comment by Ratvar** [comment]
Rephrase: can you also forbid scarab/drone/cyborg shells into going in your backpack?

**Comment by PraiseRatvar** [comment]
cyborg skeletons can go in your backpack?

**Review by Cyberboss — APPROVED** [review]

**Comment by ExcessiveUseOfCobblestone** [comment]
Ratvar and PraiseRatvar on the same thread.

An omen, perhaps?

**Pull request merged**
