### PR TITLE
Pulls the plug on Omegastation

### LINKED ISSUE #36954: Omega mapping/atmos issues
I'll just write these in one ticket; easy fixes that would clutter the issues tab.

Mapping:
1) There are no solars. This pretty much guarantees a round end if the SME blows up.
2) The southern engineering windows are r-glass instead of r-plasmaglass. This is bad since a decent plasma fire will break them quickly.
3) All restricted areas can be reached by smashing r-glass windows. Armory, vault, captain's office, oof.

Atmos:
1) There are many areas with vents/scrubbers, but no air alarms. For example: genetics, the small hallways between engineering/atmos, the gravgen lobby.
2) Many areas either only have a vent or a scrubber. Armory, sec equipment room, gravgen, brig cells.

Not a bug, but could still be improved:
1) Most departments have plastic flaps, even though the station has no MULEbots.
2) Vault has no turrets and can be entered by smashing r-glass windows. AI/borg upload computers don't have r-glass windows and windoors in front of them either.
3) Vault, armory and AI sat don't have motion sensitive cams. Probably not a huge deal, considering how small the station is.
4) Medbay has no defib mount (no CMO locker) and no bloodpacks.
5) Botany and the kitchen aren't next to each other; there aren't disposals to send vegetables to the chef either.
6) There are no escape pods.

tl;dr Label: FUCK and also please replace Omega with Pubby until people have had time to fix all of this

### PR DESCRIPTION
**Pull request by 81Denton**
:cl: Denton
del: Omegastation has been scrapped.
/:cl:

Closes: #36954

https://tgstation13.org/phpBB/viewtopic.php?f=33&t=19438

Okand has left for CM; from what I see none of our mappers (me included) have the motivation to invest hours into fixing this hot mess.

We already have Pubbystation, which A) works much better as a lowpop map and B) is maintained by @pubby.

### CODE REVIEW

**Comment by Jalleo** [comment]
There has been plenty of time so I dont object to this.

**Comment by ExcessiveUseOfCobblestone** [comment]
If someone wants to maintain it they can just readd it anyways.

**Comment by Cyberboss** [comment]
Config based public contributor run mapping repository soon (tm)

**Review by Cyberboss — APPROVED** [review]

**Comment by miniusAreas** [comment]
this just paves the way for a new map.

**Comment by miniusAreas** [comment]
@81Denton Is there still time to have someone stand up and save Omega? Id be willing to revamp it and make it less geared twards lower populations. I also have long days of nothing to do and enjoy sitting in DMM for 6-12 hours straight.

**Comment by BeeSting12** [comment]
@miniusAreas 
You can always keep the map locally, fix it, and PR it again when it's done. For now, it's better to have it removed. There's tons of issues with it that will take many hours to fix.

**Comment by miniusAreas** [comment]
@BeeSting12 Fair enough. Ill get to work on it before a alternative can be placed in omegas place.

**Comment by subject217** [comment]
If you pr a fixed omega after it's removed people will just say "I have a personal dislike of Omega so I don't want to see it in the game again even if you solved the problems."

That being said, the time to step up and fix Omega was like, months ago.

**Comment by ExcessiveUseOfCobblestone** [comment]
You'd have much better luck and much less burnout co-maintaining pubby.

**Comment by Qustinnus** [comment]
we dont want more maps anyway

**Comment by Kmc2000** [comment]
replace it with cramstation

**Comment by Qustinnus** [comment]
lol at all the dislikes from non-coders that dont have to deal with 7 maps

**Comment by 81Denton** [comment]
F

**Comment by BeeSting12** [comment]
F

**Comment by ExcessiveUseOfCobblestone** [comment]
I've paid my respects tenfold for every round I played on that map and not facerolling buttons.

**Pull request merged**
