### PR TITLE
Adds Another Bible Sprite

### PR DESCRIPTION
**Pull request by RiskySikh**
## About The Pull Request
image

Since there are holy books for nearly every major religion, I thought it would nice to include one from the fifth largest religion in the world, Sikhism. The new holy book is the Guru Granth Sahib, which is a religious text for Sikhism. Pretty much gives the Chaplain more variety in selecting books, and it's nothing major.

## Why It's Good For The Game

Well, it gives the chaplain more choice when selecting a holy book and can spread their religion of choice with this new holy book.  

## Changelog
:cl:
add: New holy book for chaplain(Guru Granth Sahib)
/:cl:

### CODE REVIEW

**Comment by RiskySikh** [comment]
Credits to Kryson for making the sprite

**Comment by LordSaladin** [comment]
still no clock cult bible sprite smh.

**Comment by RiskySikh** [comment]
> 
> 
> still no clock cult bible sprite smh.

one day

**Comment by RaveRadbury** [comment]
This is good content. We should add content so the chaplain can keep the five Ks.

**Comment by RiskySikh** [comment]
> 
> 
> This is good content. We should add content so the chaplain can keep the five Ks.

I know there was a PR earlier that added religious clothing.

**Comment by Farquaar** [comment]
> 
> I know there was a PR earlier that added religious clothing. https://github.com/tgstation/tgstation/pull/43841/files

Turban sprite coming soon™

**Comment by RiskySikh** [comment]
> 
> 
> > I know there was a PR earlier that added religious clothing. https://github.com/tgstation/tgstation/pull/43841/files
> 
> Turban sprite coming soon™

thanks

**Comment by Fikou** [comment]
you fucked up line endings, the entire file shows as changed and it will fuck up blame

**Comment by RiskySikh** [comment]
> 
> 
> you fucked up line endings, the entire file shows as changed and it will fuck up blame

what line endings?

**Comment by Krysonism** [comment]
bible-fat_shaded_64

Here is another look at the sprite.

**Review by spookydonut — DISMISSED** [review]

**Pull request merged**
