### PR TITLE
*~~~~~~~~~~~ [READ THIS SHIT] Semi-code freeze is in effect ~~~~~~~~~~~*

### PR DESCRIPTION
**Pull request by ghost**
A large pull request is up to rewrite a lot of the master controller and other systems such as shuttles.

In order to expedite this process, avoid merging PRs that will conflict with the PR below. If you're the one who is making the PR, and it hasn't been made yet but it conflicts with Carn's PR, it's a better idea to hold off on creating it until the rewrite has been merged so you can present it without any conflicts.

https://github.com/tgstation/-tg-station/pull/6706

Map changes will almost certainly conflict due to the nature of map files, so **all mapping changes are frozen until the above PR has been merged.**

An easy way to tell if your PR/a proposed PR will conflict without the command line is to use github's compare function.

https://github.com/Carn/-tg-station/compare/SubSystems

Simply hit 'edit' at the right, select your fork instead of 'tg-station', and then your branch just to the right of that.

clip 2014-12-29 at 12 12 08

Then hit 'create pull request' to check if github can automatically merge the two PRs.

clip 2014-12-29 at 12 16 49

clip 2014-12-29 at 12 15 11

If you get this, you're good to go! If not, please hold off on making the PR to the TG codebase until the rewrite has been merged.

### CODE REVIEW

**Comment by paprka** [comment]
damnit guys

**Comment by WJohn** [comment]
SO COLORFUL

**Comment by ike709** [comment]
rainbow tags

**Comment by Nienhaus** [comment]
Don't lie to me D;

**Comment by Nienhaus** [comment]
No, I'm kidding.

**Pull request closed without merging**
