### PR TITLE
Removes now-defunct economy content.

### PR DESCRIPTION
**Pull request by ArcaneMusic**
## About The Pull Request
https://tgstation13.org/phpBB/viewtopic.php?f=10&t=25888
Forum thread as of today (3/11/20), all economy content is no longer being supported. Until further notice, all of my "arconomy" pr content will be removed in order to get rid of what is now effectively bloat. Continual development towards economy content will not be merged either. Knowing this, i don't want to preempt any ire or harm development any further.

You know that this covers a large portion of the codebase as well as i do. On the off chance that something breaks, this should likely take some testing to verify a lack of runtimes. Unless there's no other changes, it should be good to go.

## Changelog
:cl:
del: Medical Kiosks do not charge money anymore.
del: Vend-a-trays have been scrapped for an explosive defect.
del: Sales taggers and Barcodes have been recalled due to trace amounts of toxic glue.
/:cl:

### CODE REVIEW

**Comment by necromanceranne** [comment]
God, this is like reading a fucking obituary.

**Comment by Farquaar** [comment]
Where is the github crying emoji?

**Comment by Couls** [comment]
@Farquaar 😭

**Comment by Shadowflame909** [comment]
do we get the medical analyzers back? Or how does that pay medical kiosk work

**Comment by optimumtact** [comment]
wait until the poll

**Comment by GravitronBlue** [comment]
Any planned changes to the black market uplink too or will it remain untouched?

**Pull request closed without merging**
