### PR TITLE
Removes ragin mages

### PR DESCRIPTION
**Pull request by Bawhoppen**
Requested by design lead

### CODE REVIEW

**Comment by evsey9** [comment]
Fuck off

**Comment by KorPhaeron** [comment]
inb4 the same people that are whining about gang TDM come out to defend bullshit ragin mages

**Comment by Aloraydrel** [comment]
Why does kor hate k/d farming gamemodes?

**Comment by Bawhoppen** [comment]
was requested, don't blame me please

**Comment by evsey9** [comment]
I think the new gang stuff will be good, but dont get rid of ragin mages, its tg culture

**Comment by GunHog** [comment]
> was requested, don't blame me please

The blame goes to you, because you made the PR!

**Comment by Iamgoofball** [comment]
@KorPhaeron 

I ported this from vg because i thought it'd be funny

this is basically just a fuckaround meme round ala monkey, should just remove it from rotation instead tbh

**Comment by Kromgar** [comment]
Ragin mages is fun. It lets you actually get to be a wizard instead of once every year

**Comment by GunHog** [comment]
Wait, this was added to rotation? Why? I presumed, just from the name and flavor text alone, that this is something that admins were meant to manually force! The right way to do it is with a vote before the round or something.

Did someone seriously enable this on rotation?

**Comment by Tacolizard** [comment]
@GunHog its on rotation at super low odds (like less than 1% iirc)

**Comment by Dorsisdwarf** [comment]
hahah take it off rotation it's a joke admin mode why is it on rotation.

**Comment by Durkel** [comment]
>putting the admin only meme button in rotation as an excuse to remove it.

Quit being fuckheads.

**Comment by KorPhaeron** [comment]
Something being admin only isnt an excuse for it being a completley incoherent death match where everyone is just constantly dying and respawning and summon events is going off every 10 seconds

**Comment by Iamgoofball** [comment]
thats the point of RM yeah

idk I'm not too terribly attached I just feel it's a better "Everyone fights" mode compared to gang/rev/cults because everyone gets to play with the role we let people add fun OP shit to

**Comment by PKPenguin321** [comment]
Wait this is in rotation wtf

Also don't remove this from the code, it's pointless to do so when it can still be accomplished by mashing the wizard spawn button, at least a real game mode for it is cleaner than that

**Comment by Iamgoofball** [comment]
Also yeah admins are going to just smash the spawn button otherwise, this makes sure admins who want to do "lol lots of wizards" can just do it in one button press without breaking the round

**Comment by bgobandit** [comment]
the real question is who the fuck added this meme mode to rotation

**Comment by KorPhaeron** [comment]
@PKPenguin321 

I mean yeah admins can always ruin a round if they want to but we don't need to endorse doing so by having a button dedicated to it

**Comment by Dorsisdwarf** [comment]
so we can remove Highlander, Everyone Is The Traitor, and Toggle Nuke?

**Comment by dannno** [comment]
>its tg culture

you fucking stupid newfag oh my GOD

**Comment by dannno** [comment]
oh my fucking GOD

**Comment by KorPhaeron** [comment]
@Dorsisdwarf Removing the first two probably wouldn't be a bad idea, the nuke is often a logical way for a round to end

**Comment by Shadowlight213** [comment]
Can we remove gang if this gets merged then?

**Comment by WJohn** [comment]
Yeah and yet highlander exists, but we aren't removing that. If we made that an actual gamemode, would that be grounds to remove it? Or should we simply move it back to admin only like sensible people?

**Comment by KorPhaeron** [comment]
@WJohn 

I regret highlander and apologize for it

**Comment by SgtxRootbeer** [comment]
Actually, normal wiz should be removed and this should be kept

**Comment by XDTM** [comment]
Don't forget this is the only way many players will get to experience playing a wizard

**Comment by Repukan** [comment]
Axe it from rotation but keep the shortcut for admins I guess?

Although they could just make wizards by hand so no big loss.

**Review by Cyberboss — CHANGES_REQUESTED** [review]
Update the configs

**Comment by Armhulen** [comment]
Remove it from rotation but this is a fun, rare thing (or at least it should be) that should be kept

**Comment by KorPhaeron** [comment]
I don't think its really fair to put a stupid button in the game and then say its peoples fault for hitting the button when we could just remove the button

**Comment by GunHog** [comment]
> I don't think its really fair to put a stupid button in the game and then say its peoples fault for hitting the button when we could just remove the button

It is not that simple. It is fine for admins to hit the button. What was apparently done is that the button was put on _automatic._

**Comment by optimumtact** [comment]
This is a server policy question to enable or disable and is really meant for meme rounds.

**Comment by optimumtact** [comment]
and yes so is gang now that' it's active again

**Comment by KorPhaeron** [comment]
>people whine about TDM and norp and then refuse to remove anything that promotes it

trapped in the cycles of our guilt

**Comment by optimumtact** [comment]
also it's honestly quite a fun round every now and again, I'm surprised people would be against it.

It's over shortly and everyone dies fairly quickly

**Comment by optimumtact** [comment]
I like TDM Kor

**Comment by GunHog** [comment]
Not everyone hates TDM, I enjoy team antagonists (and working with the crew against a strong antagonist) quite a lot, myself!

**Comment by optimumtact** [comment]
Like honestly @KorPhaeron  where did this even come from? are you trying to prove a point?

**Comment by PKPenguin321** [comment]
Since when was ragin mages tdm?

You're aware tdm = team death match, aka two groups only working to kill each other with no other objective? The wizards aren't even teamed, they kill each other as much as they kill the station. The mode is just chaos, not tdm. Please stop making real terms into buzzwords and removing things based off of that.

**Comment by KorPhaeron** [comment]
@optimumtact 

Feels like every time I log on its some variant of cult or rev or other chaotic shitshow. I've played maybe a dozen times in the past month and maybe 1-2 of those rounds were traitor.

So its not this alone, but it adds up with all the other things that are barely SS13 anymore that are eating up what feels like more and more of the mode rotation

**Comment by optimumtact** [comment]
https://tgstation13.org/parsed-logs/sybil/config/game_options.txt
https://tgstation13.org/parsed-logs/basil/config/game_options.txt

These might not be up to date, but why are you going after the round mode that is zero probability?

It just seems misplaced, like go after clockcult or gang which are just refitted rev and cult modes

**Comment by KorPhaeron** [comment]
And I know as pure percentage of rounds played ragin mages is small, but the rounds it does happen (along with other buttons like highlander, or cult being forced) happen disproportionately during the prime hours for playing (US evening) so eats up a lot more if you discount all the empty aussie hour rounds skewing our stats.

**Comment by KorPhaeron** [comment]
I figured it'd be easier to start with a throwaway joke than removing things active coders and admins have heavily invested themselves in

**Comment by optimumtact** [comment]
I just don't know if it's a good approach

**Comment by KorPhaeron** [comment]
Me neither I was secretly relieved you closed it

**Comment by MrPerson** [comment]
just fuck already god

**Comment by Really-Good-Soda-Flavor** [comment]
Take it out of rotation and fuck off

**Comment by juanototo2** [comment]
get a room goddamnit

**Comment by Bawhoppen** [comment]
I was just trying to be nice to kor by being helpful, I didn't think people cared so much

**Comment by GunHog** [comment]
> I was just trying to be nice to kor by being helpful, I didn't think people cared so much

The true intent is to have someone else make the PR so he is technically not violating the rule against self-merging PRs.

**Comment by CosmicScientist** [comment]
[You've touched us all in our care centres, Baw.](https://tgstation13.org/phpBB/viewtopic.php?f=55&t=11452)

**Comment by AnturK** [comment]
I'm 99% sure there's some references to the mode in spellbook could, you should also purge these.

**Comment by Kromgar** [comment]
REEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE

**Comment by obscolene** [comment]
remove highlander too, please. remove anything in the game, even if it's admin spawn only, that doesn't promote rp. remove things like the instagib gun. lol!!!! who cares if it's not in the actual game??? just remove it!!!!!!!!!

**Comment by lzimann** [comment]
I mean, we probably should.

**Comment by Robustin** [comment]
You know highland is bad when people would prefer a bugged Vigilante-Gang round over it.

**Comment by optimumtact** [comment]
You shouldn't have merged this antur

**Comment by AnonymousNow** [comment]
When I don't play an MD, I find that rounds I'm in tend to be full of murder that I don't have the resources to control.

When I'm not around on the servers for a while, I find that gamemodes I like tend to be murdered, brutally, in cold blood.

In short, I need to set up a webcam behind every coder with a rolled-up newspaper attached.

**Comment by optimumtact** [comment]
what the fuck man

**Comment by AnonymousNow** [comment]
Don't make me use the newspaper, oranges.

**Comment by PKPenguin321** [comment]
fuck

**Comment by optimumtact** [comment]
I just manually run raging mages now

**Pull request merged**
