### PR TITLE
Clowns now bleed Colorful Reagent.

### PR DESCRIPTION
**Pull request by Iamgoofball**
## About The Pull Request

The clown now bleeds colorful reagent.

## Why It's Good For The Game

This will increase the party potential of clowns.

## Changelog
:cl: Iamgoofball
add: The clown now bleeds Colorful Reagent.
/:cl:

### CODE REVIEW

**Comment by Errorin** [comment]
I've been pushing for this for literally 6 years.

**Comment by Qustinnus** [comment]
ah yes truly the recipe any chemist wants to follow to save the clowns life

`required_reagents = list(/datum/reagent/stable_plasma = 1, /datum/reagent/uranium/radium = 1, /datum/reagent/drug/space_drugs = 1, /datum/reagent/medicine/cryoxadone = 1, /datum/reagent/consumable/triple_citrus = 1)`

**Comment by Errorin** [comment]
The clown will likely also look like a rolled up crest toothpaste after the station realizes what's inside of him.

**Comment by tralezab** [comment]
Yeah but what's the lore?

**Comment by Spepbuthewranglesgithub** [comment]
absolutely magical, at last people have a real reason to stab the clown, no flaws whatsoever*


> ah yes truly the recipe any chemist wants to follow to save the clowns life
> 
> `required_reagents = list(/datum/reagent/stable_plasma = 1, /datum/reagent/uranium/radium = 1, /datum/reagent/drug/space_drugs = 1, /datum/reagent/medicine/cryoxadone = 1, /datum/reagent/consumable/triple_citrus = 1)`

*except this.

**Comment by tmtmtl30** [comment]
do clowns really deserve blood transfusions anyway

**Comment by optimumtact** [comment]
they're just humans in a costume

**Comment by optimumtact** [comment]
they're just humans in a costume

**Comment by Iamgoofball** [comment]
shameful display

**Pull request closed without merging**
