### PR TITLE
Improves dark mode

### PR DESCRIPTION
**Pull request by Kmc2000**
## About The Pull Request

So, I took some time off after coding darkmode, I really thought..
What does darkmode mean to YOU. YOU, the consumer, the average player, the everyday /tg/ denizen.

And then it hit me
People don't use darkmode because light mode is actually usable!

In this revolutionary PR, I fix my greatest mistake by finally making white mode obsolete once and for all.

So, without further adieu, 

I present to you!

White mode 2!
https://file.house/ltE9.mp4

## Why It's Good For The Game

The one thing that was holding darkmode back was the existence of light / white mode. This PR fixes that so that darkmode can take its rightful place as the apex roleplay feature.

## Changelog
:cl: Satan
add: White mode is unusable now. Use darkmode!
/:cl:

### CODE REVIEW

**Comment by optimumtact** [comment]
can you actually make the colour mdoe a pref you shitposter

**Comment by actioninja** [comment]
Genius change, how did I never think of this?

**Comment by nicbn** [comment]
Can we add a neon mode that looks like 90s websites?
With like cyan background and strong pink font
Oh yeah and all buttons are gifs in all caps
Also your cursor is THREE DEE

**Comment by ShizCalev** [comment]
nope

**Pull request closed without merging**
