### PR TITLE
Makes changeling armblades sharp

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
So they can butcher things with it.

Important for cutting their way out of a morph.

### CODE REVIEW

**Comment by Anonus** [comment]
DULL BLADES

**Comment by Xhuis** [comment]
Might wanna make the subtype given by fake armblade sting not sharp.

**Comment by xxalpha** [comment]
You do that and then people can meta.

**Comment by KorPhaeron** [comment]
They can already meta by the fact that it does like 0 damage

**Comment by Bawhoppen** [comment]
Are they still unable to cut bread and stuff? That might have been fixed awhile ago but worth checking.

**Comment by PKPenguin321** [comment]
>Important for cutting their way out of a morph.

reee

**Comment by Razharas** [comment]
Makes sense

**Pull request merged**
