### PR TITLE
Ms brig fixes

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request

This fixes some issues from PR #48328. Namely, shutters being on secure gear storage when there shouldn't have been, a messed up disposal track, a wall in front of a door, and a evac sign blocking a window.

## Why It's Good For The Game

Fixes annoying things that were not supposed to be there.

## Changelog
:cl:
fix: Fixed some problems with the warden's office and shutters where they weren't supposed to be
/:cl:

### CODE REVIEW

**Comment by CAPTTLasky** [comment]
God my branches are messy

**Comment by SkeletalElite** [comment]
I haven't played since this was merged, but I can't tell if there is a set of buttons that allows you to control the doors. Previously the front desk had buttons that let you open and close the entrance doors which could be useful. Obviously front desk is gone, but I'd like to see these buttons in the warden's office instead

**Comment by Cenrus** [comment]
image

While you're at it, can you remove these totally unacceptable and sinful floor decals?

**Review by kriskog — DISMISSED** [review]

**Comment by CAPTTLasky** [comment]
> 
> 
> image
> 
> While you're at it, can you remove these totally unacceptable and sinful floor decals?

Yeah those are totally out of place, thanks for pointing them out!

**Review by kriskog — APPROVED** [review]

**Pull request merged**
