### PR TITLE
Removes weakeyes

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
A var on every living mob for a single changeling power is dumb and not needed, and not worth the headache for me to deal with when trying to give carbons eye organs.

Who knows if I'll actually finish this though, eye code is all over the place

### CODE REVIEW

**Comment by ChangelingRain** [comment]
LING BUFF LING BUFF

**Comment by Armhulen** [comment]
WEE WOO WEE WOO

**Comment by ExcessiveUseOfCobblestone** [comment]
this can probably be re-implemented once eyeorgans are a thing

**Comment by ShadowDeath6** [comment]
I think at one point thermals and shadowlings gave weakeyes.

**Comment by Iamgoofball** [comment]
@KorPhaeron just make mesons/NVGs/thermals do this

**Pull request merged**
