### PR TITLE
skeletons healing off milk works like it used to 3 years ago

### PR DESCRIPTION
**Pull request by Fikou**
## About The Pull Request
skeletons healing off milk was changed in the pr that made stomachs be what handles chems
this doesnt acutally work and its been broken for 3 years 
so we just revert back to the old way of doing it

## Why It's Good For The Game
its over

## Changelog
:cl:
fix: skeletons get boosted heals from milk again
/:cl:

### CODE REVIEW

**Comment by tralezab** [comment]
>so we just revert back to the old way of doing it

this solution sucks though

**Comment by optimumtact** [comment]
soul restored

**Comment by Mothblocks** [comment]
i was LITERALLY just talking about the 3 athath milk prs to a friend

**Comment by Mothblocks** [comment]
its just not the same without verified

**Comment by ChungusGamer666** [comment]
the bone stomach code should work
why does it not work

**Comment by Mothblocks** [comment]
its just not the same if its not a web edit

**Pull request merged**
