### PR TITLE
Fixes a morgue trays causing burn damage to corpses because it's TOO cold, also organ decay

### LINKED ISSUE #80302: Morgue trays husk people
## Issue Summary
Caused by https://github.com/tgstation/tgstation/pull/80219. Placing dead bodies inside tray causes them to recieve burn damage until they are husked. Takes about an hour or so.

40 minutes mark roundstart body
image

two minutes later

image

## Round ID:
N/A

## Testmerges:
N/A

## Reproduction:

1. Place dead crewmember inside a tray during some red alert bad thing something
2. Forget about them for an hour
3. Get your flash frozen husked body from thetray

### PR DESCRIPTION
**Pull request by Ghommie**
## About The Pull Request
This will fix #80302 for everything except ethereals, but ethereals take damage at above 0° C temp anyway so their organs cannot be preserved within the body.

Also fixing some wrong logic also from #80219, which lead to organs decay being but a fraction of what it should be.
## Why It's Good For The Game
Fixing issues.

## Changelog

:cl:
fix: Fixed organ decay being too low.
fix: Fixed morgue trays having excessively low temperatures that damage corpses.
/:cl:

### CODE REVIEW

**Comment by FlufflesTheDog** [comment]
Does not fix the husking. The temperature that humans start taking burn damage seems to only be -3C, and as a side note, doesn't scale linearly, not increasing in speed until an additional 70c below that.

Perhaps we could cap how much burn damage can be done to a corpse from being cold. I don't think its unreasonable to expect bodies to have a little bit of freezer burn after being in a literal freezer, its mostly the husking that's problematic (in my opinion)

**Comment by Ghommie** [comment]
Uhh, weird, I must have not evaluated my tests correctly, since they didn't seem to take damage until the temp was minus double digits celsius. Good thing the bodies still take damage at below 0° C temperature, since that leaves us with a (albeit tiny) margin we can set the temperature to.

**Comment by FlufflesTheDog** [comment]
I haven't tested this one but I have a feeling it wont work well. -3c to 0c is a tiny margin, which will presumably make it take a lot longer to actually become effective. And when I was testing, corpses were consistently 5c or so above the set point on the morgue, so may not work at all.

**Comment by AshtonFox** [comment]
I suggest changing the value of `var/minimum_temperature` to be _266.15 (K)_.

**Comment by Ghommie** [comment]
I put my faith on #80811. I've been neglecting this issue for too long, sorry.

**Pull request closed without merging**
