### PR TITLE
Adds a hotkey for interacting with your suit storage slot (item)

### PR DESCRIPTION
**Pull request by ATH1909**
## About The Pull Request

This PR adds a quick equip hotkey for the suit storage slot, similar to the quick equip belt hotkey  (control+E) and the quick equip backpack hotkey (control+B). It defaults to control+Q.

This PR also reorganizes some targeted quick equip hotkey code and makes it easier for other people to add their own various targeted quick equip hotkeys (for shoes, hats, pockets, etc.) in future PRs.

## Why It's Good For The Game

It always struck me as really odd that it was often easier/faster to quickdraw something from your backpack than it was to quickdraw something from your suit storage slot, which seems to me to be where you're intended to keep your ranged weaponry as a member of Sec. 

## Changelog
:cl: ATHATH (tested by Arcane)
add: Control+Q now serves as a hotkey for quickdrawing (or quicksheathing) an item from your suit storage slot.
/:cl:

### CODE REVIEW

**Comment by ATH1909** [comment]
I would also like to state that, unfortunately, this PR is untested, as I can't compile it on my computer without updating byond, and updated versions of byond currently don't play nice with Fulpstation. Since I'm banned from /tg/station but not Fulpstation, I think you can understand why I'm hesitant to update Byond just for this PR. Assistance in testing this PR would be greatly appreciated.

image
image
image

**Comment by ATH1909** [comment]
goddamnit travis

**Comment by optimumtact** [comment]
completely untested PR, your issues with fulp are not my concern

**Comment by ATH1909** [comment]
Thanks, oranges.

Arcane did some testing for me for this PR (thanks!), which is why oranges reopened it. They've been credited in the changelog now.

**Comment by spookydonut** [comment]
Thats a lot of words to try disguising a webedit pr

**Comment by ATH1909** [comment]
> Thats a lot of words to try disguising a webedit pr

Actually, this wasn't a webedit. Look at the commits if you don't believe me.

**Comment by ExcessiveUseOfCobblestone** [comment]
Re PR if you are planning on updating this.

**Pull request closed without merging**
