### PR TITLE
Ports one outfit from The Girthy Station

### PR DESCRIPTION
**Pull request by PKPenguin321**
## About The Pull Request

This PR adds the pink summer suit to the clothesmate.

This outfit was sprited by me, intended for the girthy station.

After showing my work to the good people of discord they convinced me there was enough demand for me to attempt to add the outfit to /TG/ proper.

Thanks to Krysonism for inspiring me to create this outfit.

## Why It's Good For The Game

Spacemen need some appropriate clothing in order to not overheat during the space summer.
It costs 75 credits so it also integrated with the goofconomy.

## Changelog
:cl:
add: a new suit has been added to the clothesmate!
imageadd: added sprites for the new outfit.
/:cl:

### CODE REVIEW

**Comment by Ziiro** [comment]
🤔

**Comment by tralezab** [comment]
image

**Comment by Jordie0608** [comment]
sinbin

**Comment by wesoda25** [comment]
id like to use this opportunity to say vote for bobbah brown headmin eletion 2k19

**Comment by optimumtact** [comment]
do not bring that shit here wesoda I will gitban you so fast

**Comment by wesoda25** [comment]
In all fairness tthis is the pr /obj/item/clothing/under/suit/dick/summer
	desc = "A revealing outfit perfect for a warm summer day."
	custom_price = 75

/obj/item/clothing/under/suit/dick/summer/pink
	name = "pink summer cockpants"

but i shall not push it

**Comment by WarRage333** [comment]
Hahaha... its a joke pr! 

Unless... ?

**Comment by Repukan** [comment]
Fetish content

**Comment by PKPenguin321** [comment]
I find it a bit crass that you would impugn my motives, but on the other hand it is not really a criticism of the feature itself and i have faith that the good people of github will see through this tactic.

I think, that unless you are a very sheltered person you would not find it that unusual if you saw a man wearing such an outfit on hot summer day in Berlin or London(I don't know about Dublin, never been).

**Comment by PKPenguin321** [comment]
It surprises me that someone could take offence to seeing an "immodest suit" in a video game for adults.

This is hardly the first six foot cock in sci-fi media.

Imagine someone going on an image board and complaining about seeing a man in somewhat revealing clothes in Deus Ex or the fifth element! They would be mocked for their opinion and labelled puritans!

**Comment by Krysonism** [comment]
Good work, but can we get some screenshots?

**Comment by Rowelll** [comment]
orang man bad

**Pull request closed without merging**
