### PR TITLE
necklaces again

### PR DESCRIPTION
**Pull request by PKPenguin321**
round three let's go
remake of https://github.com/tgstation/-tg-station/pull/13342
i don't have an image of the new sprites at this moment but i assure you they are pretty dope, shoutout to @swankcookie for brewing them up
pray that travis gives this the green

:cl: PKPenguin321
rscadd: Dope golden necklaces have been added. They're a jumpsuit attachment like ties and are completely cosmetic.
rscadd: Dope necklaces can be bought from the clothesmate with a coin. Three are in the clothesmate by default, so you can get your posse going. Gangs that aren't Sleeping Carp can also purchase necklaces for 1 influence each. Dope.
/:cl:

### CODE REVIEW

**Comment by Supermichael777** [comment]
Screenies for the RAW images
In-hand:
!(inhand)[http://imgur.com/JQFG0ub]
Character sprite(only one facing and no body for size comparison)
!(on body)[http://imgur.com/z4eK7PX]

**Comment by PKPenguin321** [comment]
thank you based tkdrg

**Comment by Supermichael777** [comment]
COUGH 24 HOURS

**Comment by tkdrg** [comment]
this pr was up for like 3 weeks before he had to remake it

**Comment by swankcookie** [comment]
@Supermichael777 Yeah that orange came out a little different then I'd hoped.  I've still got the sprites up on Mac,  so I'll take a look when I get home.

**Pull request merged**
