### PR TITLE
Fixes dirty in lavaland

### PR DESCRIPTION
**Pull request by lzimann**
Closes #27699

### CODE REVIEW

**Comment by Cyberboss** [comment]
Don't forget the z2 stuff

**Comment by lzimann** [comment]
Someone has to go over every area to check.

**Comment by Cyberboss** [comment]
@ChangelingRain pls

**Comment by ChangelingRain** [comment]
This is not my fault

**Comment by Kromgar** [comment]
It happened after you changed the zoning in lavaland so we blame you

**Comment by AnturK** [comment]
I'd honestly drop all this convoluted system and make these mapping objects that apply to their area.

**Comment by lzimann** [comment]
Well, until then we can at least have the areas having the correct flags

**Pull request merged**
