### PR TITLE
Removes the asteroid shuttle

### PR DESCRIPTION
**Pull request by Qbopper**
:cl: Qbopper
del: The asteroid shuttle crashed into a moon on the way to Centcomm and has been removed from the list of purchasable engines.
/:cl:

https://tgstation13.org/phpBB/viewtopic.php?f=10&t=11236

People hate it, and it's allegedly breaking shit

I have no personal stake in the PR and don't particularly care either way (unless reports of it breaking stuff is true), someone had to make the PR for the poor souls on the forums

### CODE REVIEW

**Comment by Kromgar** [comment]
If it's allegedly breaking shit why don't you fuckign fix it first?

**Comment by Qbopper** [comment]
because people hate it even when it isn't breaking stuff

**Comment by obscolene** [comment]
breaks literally everything, please merge ASAP so greytiders will stop breaking into bridge to purchase the shuttle and turn the round into an unending glitchfest

**Comment by BeeSting12** [comment]
To preface I like the asteroid shuttle, it's hilarious to bet on how many will die when it docks. But it looks to be pretty broken and if noone wants to fix it, I'd say for the shuttle be removed from the list until it can be fixed.

**Comment by Kromgar** [comment]
The thing is no one fucking reported asteroid shuttle is breaking the game

**Comment by KorPhaeron** [comment]
We have a config option to disable it and this doesn't actually fix whatever the underlying issue is

**Comment by Qbopper** [comment]
ye fair enough

**Pull request closed without merging**
