### PR TITLE
fixes a spelling error

### PR DESCRIPTION
**Pull request by ghost**
description = "Utility upgrades for cybogs."
    |
   V
description = "Utility upgrades for cyborgs."

[Changelogs]:
:cl: CthulhuOnIce
spellcheck: Fixed 'Cybogs' in research nodes.
/:cl:

[why]:
It's just a spelling fix.

### CODE REVIEW

**Review by ninjanomnom — APPROVED** [review]

**Comment by optimumtact** [comment]
do you like bees

**Comment by BeeStation** [comment]
Yes.

**Comment by optimumtact** [comment]
very cool

**Comment by ExcessiveUseOfCobblestone** [comment]
@BeeStation did you know the bee costume actually protects from bees?

**Comment by ExcessiveUseOfCobblestone** [comment]
@BeeStation did you know that in early implementation of bees you could get yields of 30+?

**Comment by TheDreamweaver** [comment]
@BeeStation did you know that in code, bees are gendered as female, as a reference to the fact that most working bees are female?

**Pull request merged**
