### PR TITLE
Added a search function to fabricators menus

### PR DESCRIPTION
**Pull request by Menshin**
Some players were missing the Ctrl-F functionality...

### CODE REVIEW

**Comment by GunHog** [comment]
Not the prettiest, but a great function nonetheless! May you also do this for ze autolathe?

**Comment by ike709** [comment]
AUTOLATHE!!!!!!!

**Comment by Menshin** [comment]
You lazy Cargonians...

**Comment by Deantwo** [comment]
:+1:

**Comment by phil235** [comment]
Pretty useful function :+1:

**Comment by Tenebrosity** [comment]
Great :+1:

**Comment by Jalleo** [comment]
:green_book: :+1:

**Comment by paprka** [comment]
:dollar:

**Comment by Cheridan** [comment]
my little menu can't be this cute

**Pull request merged**
