### PR TITLE
Gang Update

### PR DESCRIPTION
**Pull request by Ikarrus**
- Added a line on deconversion instructing the player that his character does not remember the identities of his former gang.
- the Gang intercept report should show up properly now.
- Made the deconversion notice more noticable to others.
- Experiment: Loyalty implants will no longer survive deconverting a gangster. Security now needs to use two of them if they want the permanent effects: The first to deconvert them, and the second to make them loyal.

### CODE REVIEW

**Comment by Kromgar** [comment]
Wait does he remember the gang member who recruited him? Because in rev you remember who flashed you

**Comment by Ikarrus** [comment]
No.

**Comment by Kromgar** [comment]
That was a quick response.

So why does gang get the benefit of you forgetting and Rev does not?

Hmmm... I suppose they don't target heads but all access is pretty fucking neato

**Comment by Ikarrus** [comment]
My motivations were

1) Gang bosses, while they are high profile targets, are not the object of the game.
2) Gangs are not as threatening as Revs, largely because of their slower rate of conversion, and because they're fighting each other as much as security.
3) Because of 2, security tend to steamroll the gangs by quickly implanting a gangster and extracting their identity from them

**Comment by Man-Shroom** [comment]
>All access is pretty fucken neato

What?

**Comment by Kromgar** [comment]
MURDER SHE WROTE.

For all access

**Comment by Supermichael777** [comment]
without rule enforcement of this rp element shitlers won't listen and with rule enforcement expect cries of baystation enforcement. plus loyalty implants are expensive and most people don't understand exactly how they are superposed to work, there is zero consistency across game modes.

**Comment by Ikarrus** [comment]
But we already have enforcements about this for rev and cult already???

**Pull request merged**
