### PR TITLE
Converting device radio to a component

### PR DESCRIPTION
**Pull request by WarlockD**
## About The Pull Request
Refactor of radio into a component.  Also refactoring how messages are sent to stop area/range searching of devices.  Not doing a tgui interface for this this go around, just doing the big refactor first then work on that latter.  Right now the replacement acts a bit like how the nnted_interface works.

## Why It's Good For The Game
It's a 7 year old interface that hasn't been updated.  It be nice to be able to construct linked devices like airlocks or shutters in game.  

Still a WIP.  I got atmos devices up just figuring out how assembly devices work with it.
## Changelog
:cl:
refactor: refactored radio code
/:cl:

### CODE REVIEW

**Comment by msgerbs** [comment]
You're my god damn hero.

**Comment by WarlockD** [comment]
Damnit I forgot I pr'd that network update.  Humm.  I might hold off on this and work on the network one replacing the atmos to using nntd.

**Comment by LemonInTheDark** [comment]
Jesus christ ero

**Comment by WarlockD** [comment]
> Jesus christ ero

Yea been in a rut lately and now all of a sudden I am working on the networking pr again AND a prolathe js update....what is wrong with me

**Pull request closed without merging**
