### PR TITLE
Removes the omni circuit printer from robotics on delta, meta, and box. [Ready for review]

### PR DESCRIPTION
**Pull request by BeeSting12**
Changes it to a sci departmental circuit printer.

:cl: BeeSting12
fix: Robotics' circuit printers have been changed to science departmental circuit printers to allow science to do their job more efficiently.
/:cl:

### CODE REVIEW

**Comment by SpaceManiac** [comment]
I was wondering when someone would notice

**Comment by 81Denton** [comment]
Can I have some uhhhh mapmerge

**Comment by BeeSting12** [comment]
ive used map merge before and for some reason its not working now and i have no idea why

**Comment by 81Denton** [comment]
Weird. If it's not working for you I can open a PR; looks like all other maps have the same issue (and also the sacid beakers they no longer need).

**Comment by ExcessiveUseOfCobblestone** [comment]
Keep SACID in for legacy and just so they can be weaponized :^)

**Comment by zaracka** [comment]
it should be only printing exosuit boards to be honest, leave machines and consoles to engineering

**Review by deathride58 — COMMENTED** [review]
Learn how to use mapmerge

**Comment by WarRage333** [comment]
Does medical even have a printer in storage? (on box?)

I know engi has one but any other department?

**Comment by BeeSting12** [comment]
Map merge issue was an issue with python not being pathed properly. It was still giving me errors when I logged off yesterday so I'm going to fix it soon (tm). Within 24 hours. 

@81denton I'll fix it on the remaining maps as well

**Comment by BeeSting12** [comment]
I get this error whenever I attempt to run mapmerge. Python is properly pathed now so I have no idea.

https://file.house/W1Rg.png

**Comment by BeeSting12** [comment]
I'm running map merge with a fresh download of the codebase and I still reproduced the issue.

**Comment by BeeSting12** [comment]
never mind guys i cant read simple instructions: https://file.house/GQMF.png

(i had python 2.7)

**Comment by ExcessiveUseOfCobblestone** [comment]
So funny watching people downvote prs that disadvantage science.

**Comment by fen0s** [comment]
Please, if you wanna remove omni printer from science, at least make omni printer for another department. Because sometimes you need to fix stuff that can get broken from damage, or from explosion.

**Comment by SpaceManiac** [comment]
There's one on Pubby that you missed also, if you take care of that one I can fix the spurious Box changes for you

**Comment by BeeSting12** [comment]
I will. Thanks

**Comment by ExcessiveUseOfCobblestone** [comment]
@Cyprex I think you at'd me on accident but the arbitrary difficulty of going out of science to get the circuit is intended when the entire purpose of techwebs was to shift the omnipotence from science

**Review by ninjanomnom — APPROVED** [review]

**Comment by Cyprex** [comment]
The departmental science circuit imprinter PRINTS omniprinter boards, so this is a reasonably quick replacement, and pointless churn in my opinion. Either go the whole way and remove omniimprinter boards or give science omni imprinters. This halfway solution was pointless in my opinion.
I addressed my post to you due to your claim people downvoted it because it disadvantaged science, because I believe this is just adds some minor clumsiness.

**Pull request merged**
