### PR TITLE
Add new fitness skill and mechanics

### PR DESCRIPTION
**Pull request by timothymtorres**
## About The Pull Request
dreamseeker_9pl5F22vN3

## New Fitness Skill
- Working out on the weight machines will require less stamina
- The exercised status effect durations are increased by the level
- The more fitness you have, the bigger your mob sprite

## Exercised Status Effect
- Boost your metabolism x2
- The max duration is determined by the fitness skill
- Uses multipliers based on a good diet and ~~steriods~~ medicine to increase the duration
- Will convert into fitness skill xp while sleeping based on the quality of sleep

## Weight Training Equipment
- Weight machines now drain stamina and nutrition
- Weight machines now give fitness xp
- Punching bags now drain stamina (wearing boxing gloves lowers it) and gives a small amount of fitness xp
- Being clumsy has a chance to hurt you, but it can be overcome with persistence. (the higher your fitness skill, the less chance of getting injuried)

## Why It's Good For The Game
HUSTLE FOR THAT MUSCLE!!!

dreamseeker_YFfxcRhaJE

## Changelog
:cl:
add: Add new fitness skill and mechanics for weight machines and punching bags.  Working out with a proper diet and good sleep will result in massive fitness gains.  As your fitness increases, so does your mass.
/:cl:

### CODE REVIEW

**Comment by CRITAWAKETS** [comment]
is this automatically shown on ExperTrak?

**Comment by Jacquerel** [comment]
I understand why you've done it but I do not love this scaling the mob's transform, this is an action which basically universally looks bad

**Comment by optimumtact** [comment]
image

**Review by Wallemations — CHANGES_REQUESTED** [review]
> The more fitness you have, the bigger your mob sprite

C'mon, at LEAST show us how that looks

**Comment by the-orange-cow** [comment]
Gym cape?

**Comment by HoodMilk** [comment]
I'll show you who's the boss of this gym.

**Comment by timothymtorres** [comment]
> C'mon, at LEAST show us how that looks

Added gym progress pics for each new level of fitness.

**Comment by Wallemations** [comment]
Jesus Christ it's literally just a resize, no pixel shifting to accommodate for height or anything

Like it's funny but I can't give this a pass

**Comment by Farquaar** [comment]
Instead of scaling total sprite height and width it should just deform/stretch your arms outwards. That would be hilarious.

**Comment by Wallemations** [comment]
> Instead of scaling total sprite height and width it should just deform/stretch your arms outwards. That would be hilarious.

Is that even possible?

**Comment by Wallemations** [comment]
Also if anyone else can remove the "needs pictures" tag for me that'd be great, can't do it on mobile

**Comment by timothymtorres** [comment]
> Jesus Christ it's literally just a resize, no pixel shifting to accommodate for height or anything

This is literally how all forms of enlargement are done.  The giant mutation, cyborg upgrade, and growth serum all use the same code.  The gym method of converting muscle gains into size is perhaps the hardest method to achieve this effect.  It requires a significant time investment and help from the chef or botany.

**Comment by Jacquerel** [comment]
> > Jesus Christ it's literally just a resize, no pixel shifting to accommodate for height or anything
> 
> This is literally how all forms of enlargement are done. The giant mutation, cyborg upgrade, and growth serum all use the same code. 

yeah and those all look pretty bad

**Comment by Farquaar** [comment]
> > Instead of scaling total sprite height and width it should just deform/stretch your arms outwards. That would be hilarious.
> 
> Is that even possible?

No idea. But would be amazing.

**Comment by ilikesaying** [comment]
https://www.youtube.com/watch?v=8_DUksyKPi0

**Comment by timothymtorres** [comment]
Added some prison food bonuses to fitness:

dreamseeker_YFfxcRhaJE

**Comment by Ghommie** [comment]
> Jesus Christ it's literally just a resize, no pixel shifting to accommodate for height or anything
> 
> Like it's funny but I can't give this a pass

Mob resizing actually shifts the icon so that it doesn't slip out the lower bounds of the turf. It's been like that for more than a couple months now.

**Review by Ghommie — APPROVED** [review]
Nothing glaring code-wise, the scaling distortion caused by resizing may be a lil' icky, but that's it.

**Comment by timothymtorres** [comment]
Ask and you shall receive.
- #79584

**Pull request merged**
