### PR TITLE
Carp infusion now changes how your skin looks to reflect your fishy nature

### PR DESCRIPTION
**Pull request by SmArtKar**
## About The Pull Request

dreamseeker_irtuNE9eaZ

Adds a carpskin effect using a bodypart overlay system similar to voidwalker limbs

## Why It's Good For The Game

Players should know that someone is into fishy business (also it looks cool)

## Changelog
:cl:
image: Carp infusion now changes how your skin looks to reflect your fishy nature
/:cl:

### CODE REVIEW

**Comment by necromanceranne** [comment]
Is there any way to generalize this? I might be interested in doing something similar down the line for other infusions.

**Comment by SmArtKar** [comment]
> Is there any way to generalize this? I might be interested in doing something similar down the line for other infusions.

sure

**Comment by SimplySmiley123** [comment]
Does it change anything on non-humans btw?

**Comment by SmArtKar** [comment]
> Does it change anything on non-humans btw?

RFm74kn

**Comment by OceanFish1** [comment]
looks legit
image

**Comment by CCC23** [comment]
PURPLE GUY?>

**Review by Wallemations — APPROVED** [review]
The man behind the river

**Comment by EricZilla** [comment]
Yasss fishe

**Pull request merged**
