### PR TITLE
Adds directional signs from bay

### PR DESCRIPTION
**Pull request by ghost**
Edited them a bit for clarity and to make the medbay sign blue but yeah, I didn't add these to the map or anything but they're super duper cool.

ss 2015-02-01 at 06 20 04

cool

### CODE REVIEW

**Comment by ike709** [comment]
contact the mappers!

**Comment by GunHog** [comment]
What? No cargo?

**Comment by Steelpoint** [comment]
Very nice.

**Comment by paprka** [comment]
Added the signs to the map in the main hallway.

**Comment by paprka** [comment]
ss 2015-02-03 at 03 20 36

**Comment by Tenebrosity** [comment]
Noice :+1:

**Comment by TZK13** [comment]
Cargo really does seem to be missing here, besides that this is nice.

**Comment by paprka** [comment]
there's only so much room on walls. Cargo really isn't as important as escape/engineering/medbay/sec to be honest and it's comparable to service in terms of departmental status.

**Comment by TZK13** [comment]
I dunno, this is entirely a personnel anecdote but the two locations I've seen people ask the directions for the most is Cargo and the janitor's closet. Obviously signs for the janitor's closet is ridiculous but I personally consider Cargo an important enough department to warrant it. Not a big deal though.

**Comment by Tenebrosity** [comment]
We need signs you can var edit the text of to put beside department entrances. Instead of psychically knowing where each door leads just by looking at them.

**Comment by Jordie0608** [comment]
Changelog probably.

**Pull request merged**
