### PR TITLE
Option for admins to show a song's title

### PR DESCRIPTION
**Pull request by Cyberboss**

### CODE REVIEW

**Comment by duncathan** [comment]
feature freeze fo fum i smell the blood of a closed pr

**Comment by optimumtact** [comment]
adds an extra step to play sound :-1:

**Comment by PKPenguin321** [comment]
Also add a cancel button for if I misclick the wrong sound

**Review by lzimann — CHANGES_REQUESTED** [review]
Default to No and add a cancel button(you will have to move the alert before the admin log).

**Comment by lzimann** [comment]
@cyberboss pls

**Review by lzimann — APPROVED** [review]

**Pull request merged**
