### PR TITLE
Fixes energy axe not having the sharp flag

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
Fixes https://github.com/tgstation/tgstation/issues/22827

### CODE REVIEW

**Comment by kilkun** [comment]
whats the point of having a positive flag for sharpness and not just using TRUE

**Comment by KorPhaeron** [comment]
Yes

**Comment by kilkun** [comment]
makes sense then

**Comment by Kromgar** [comment]
Well energy axes should be da sharpest there is

**Comment by KorPhaeron** [comment]
The next level of sharpness is for precision, it gives better surgery chances

**Comment by kilkun** [comment]
there should be one level above for 100% delimb chance.

**Comment by KorPhaeron** [comment]
It already has 100% delimb

**Comment by kilkun** [comment]
if it hit someone in the head it'll decapitate them in one hit from full health?

im 99% sure it wont

**Comment by improvedname** [comment]
No thats balance issues and targetting

**Pull request merged**
