### PR TITLE
Syndicate toolbox now has syndicate screwdriver.

### PR DESCRIPTION
**Pull request by xxalpha**

### CODE REVIEW

**Comment by bgobandit** [comment]
This kills tactical screwdrivers. Using screwdrivers to attack eyes in areas with similar backgrounds, making it harder to see. Yes, i am serious.

**Comment by xxalpha** [comment]
I..what?

**Comment by Bawhoppen** [comment]
also this allows any old traitor to steal the nuke core, when they really shouldn't be able to, also ruins potential syndie stealth stuff

**Comment by lordpidey** [comment]
@Bawhoppen No, it won't.  You still need the container to hold the nuke core.

**Comment by Bawhoppen** [comment]
it will let you open it atleast

**Comment by Anonmare** [comment]
Nothing really stopping any old traitor from stealing any of the other high risk items either tbh.
Honestly it makes sense for the Syndie toolbox to have better tools, all things considered.

**Comment by GunHog** [comment]
>it will let you open it atleast

If a Traitor wants to pop open the nuke core cover, and turn that section of the station into a radiation zone, I say let him!!

**Comment by xxalpha** [comment]
You can fix it with some metal, you just need radiation protection.

Making engineering roles more valuable.

**Pull request merged**
