### PR TITLE
Makes plasma/uranium/diamond tiles consistent with station tiles

### PR DESCRIPTION
**Pull request by Lexorion**
### Consistency for mineral tiles
I think it's nice to have some consistency so I changed the tiles a bit. Already started this when I replaced the gold tiles. Had to remake the plasma tile since I couldn't properly resize it. 
**Picture shows the changes (the tiles on the left are old)** 

I'll change the remaining 2 tiles (silver,bananium) in a different PR since I'm not really sure how I should change the bananium tile.

### CODE REVIEW

**Comment by WJohn** [comment]
Several things always bugged me about those but I never bothered to fix it myself, this is a good improvement, thank you.

**Comment by Supermichael777** [comment]
First off:Lin general these are better. 👍 

The pattern on the new plasma tiles seems kinda muted and the uranium tiles still look like hard candy. the diamond pattern is directional and feels out of place.

**Comment by ChemicalRascal** [comment]
IDK, I feel like the directional aspect is intended to be a kind of highlight on each individual bit in the panel, and to me that kind of makes sense?

**Comment by ChangelingRain** [comment]
The diamond pattern on the uranium tiles should be smooth between tiles.

**Comment by XDTM** [comment]
I feel like they should all smooth.

**Comment by KorPhaeron** [comment]
Everyone suggesting tweaks to the sprites are welcome to make the changes themselves, the proposed ones are still an improvement

**Pull request merged**
