### PR TITLE
the pr that will make /tg/station great again

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request

Removes the cause of all problems

## Why It's Good For The Game

Because nobody likes them except the degenerate incels that play them

## Changelog
:cl:
del: Removed furries
/:cl:

### CODE REVIEW

**Comment by bgobandit** [comment]
nyaat enough effort

**Comment by tralezab** [comment]
if the pr that fixes tgstation won't compile we're in a lot more trouble than i thought

**Comment by Whoneedspacee** [comment]
retard

**Comment by wesoda25** [comment]
God hes so dreamy

**Comment by PKPenguin321** [comment]
@Whoneedspacee DONT SAY THAT WORD AAAAAAAAAAAAAAAAAA

**Comment by Whoneedspacee** [comment]
uh oh you right

**Comment by ExcessiveUseOfCobblestone** [comment]
stop with the meme PRs

**Comment by wesoda25** [comment]
Burn in hell cobby

**Comment by ExcessiveUseOfCobblestone** [comment]
i'm holding onto this post so I can get u gitbanned if u look at me funny

**Pull request closed without merging**
