### PR TITLE
Beam rifles now slowdown while scoped

### PR DESCRIPTION
**Pull request by silicons**
maximum damage control

### CODE REVIEW

**Comment by GunHog** [comment]
It would be nice if the scope's action button remained visible while zoomed so I do not have to drop the rifle in order to cancel the zoom mode.

**Comment by WJohn** [comment]
The scope also needs to be way smaller, currently you can see insanely far with it. Maybe simply have it only shift your screen, like the regular ballistic sniper rifle works? Heck you could copy paste the mechanic outright.

**Comment by RemieRichards** [comment]
@WJohn No copy paste.

**Comment by kevinz000** [comment]
@GunHog it does, it's just tiny...
Anyways scoping is getting redone soon anyways.

**Comment by Razharas** [comment]
Hope that wont break pAIs

**Pull request merged**
