### PR TITLE
if this shows up on the base repo and not my fork please call me an idiot

### PR DESCRIPTION
**Pull request by plapatin**
## Changelog
:cl:
add: Added new things
add: Added more things
del: Removed old things
tweak: tweaked a few things
balance: rebalanced something
fix: fixed a few things
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

### CODE REVIEW

**Comment by plapatin** [comment]
GOD FUCK

**Comment by mrhugo13** [comment]
idiot

**Comment by trollbreeder** [comment]
idiot

**Comment by Buggy123** [comment]
toidi

**Pull request closed without merging**
