### PR TITLE
fixes firedoor layer for the last god damn time

### LINKED ISSUE #35650: deltastation experimentor west-side door is layered below firelock

### PR DESCRIPTION
**Pull request by ShizCalev**
fixes #35650

### CODE REVIEW

**Comment by Xhuis** [comment]
all of them? it's over at last? for good?

**Comment by Bawhoppen** [comment]
It's over at last... until next time

**Comment by factoryman942** [comment]
honk honk

**Review by Cyberboss — APPROVED** [review]

**Comment by ShizCalev** [comment]
bless

**Comment by Xhuis** [comment]
🙏

**Pull request merged**
