### PR TITLE
Clarifies treatment for severe burn wounds when scanned with a health analyzer

### PR DESCRIPTION
**Pull request by GPeckman**
## About The Pull Request

Severe burn wounds can become infected, and if the infection is left untreated for too long, the limb will 'lock up completely.' When this happens, then wound can no longer be disinfected. Instead, it must be amputated, augmented, or treated with cryogenics. Previously, the health analyzer would only mention augmentation and amputation as ways to treat this, and only if it was set to the 'detailed information on wounds' mode. On the normal mode, it would still say the same thing about disinfecting, even after the limb locked up. Neither mode said anything at all about cryogenics. Now, both modes will mention all three methods of treatment.

## Why It's Good For The Game

This should make it much easier for medical doctors to properly treat severe burn wounds. Making game mechanics easier to understand is almost always a good thing.

## Changelog
:cl:
qol: The health analyzer will now be more clear about how to treat burn wounds, especially seriously infected ones.
/:cl:

### CODE REVIEW

**Comment by MrMelbert** [comment]
I think cryo healing complete infection all along has just been an oversight that's never been fixed
@Ryll-Ryll Do you want it codified?

**Comment by GPeckman** [comment]
I've only ever seen people fix infected limbs that have gotten that bad using cryo. Never by augmentation or amputation. Fixing that would probably cause some growing pains, even with the improved description.

**Comment by nikothedude** [comment]
> I think cryo healing complete infection all along has just been an oversight that's never been fixed @Ryll-Ryll Do you want it codified?

It really shouldn't be, or at the very least it should be codified in a way that isnt the way it is _now_

Because honestly, as it stands, cryo counters infections so incredibly well they are absolutely rock-bottom in my triage threat assessments, despite the fact they probably _should_ be a little scary given how damn long it can take for limbs to necrose (at least on severe, not on catastrohpic)

**Comment by GPeckman** [comment]
My main concern is that IIRC medbay has no easy way to amputate or augment heads and torsos. As far as I know, they only start with surplus arms and legs.

**Comment by Loafin34** [comment]
yeah... getting shot twice by a laser gun due to some anteg rushing down the halls and leading to infection kinda sucks ass, especially with the fact you HAVE to disinfect the wound, which i have never seen people do. They either place a regenerative mesh on, or excise the burns, OR excise the infection after the fucking thirty seconds it took for you to get to medbay.

**Pull request merged**
