### PR TITLE
Update labor camp stacker accepted sheets.

### LINKED ISSUE #29578: Gulag point determining device is outdated
The gulag stacker doesn't take polycrystals, plasmatitanium, and titanium.

Consequently, it doesn't give them points for it either.

### PR DESCRIPTION
**Pull request by pubby**
Closes #29578

### CODE REVIEW

**Comment by PraiseRatvar** [comment]
HOLD IT

https://github.com/tgstation/tgstation/issues/16936#issuecomment-318842673

fix ;)

**Review by Cyberboss — APPROVED** [review]

**Comment by AnturK** [comment]
Shouldn't this and orm use the same list ?

**Comment by pubby** [comment]
I didn't do that because the ORM doesn't accept smelted sheets and the credits are different.

**Comment by AnturK** [comment]
I see, all good then.

**Pull request merged**
