### PR TITLE
Buggate 2015 PART 1: Slimes, drinks, and more!

### LINKED ISSUE #9066: Washing shoes with a clown stamp does nothing, Noslips can not be recolored in the washer.
What it says on the tin. Noslips one may be intentional for balance.

### LINKED ISSUE #9077: Wizard den lacks comms
Wizards used to be able to hear every channel from the den like nuke ops could but since the new shuttle it was removed.

### LINKED ISSUE #9098: cyborg reset/restart module boards have confusing  names
Both reset and restart modules boards have almost the same names, but they accomplish completely different tasks. It's confusing.

### LINKED ISSUE #9122: silver slime drink reaction can still create invisible "-drink" items
Using the silver slimes drink reaction still has a chance to spawn invisible, useless "-drink" items that can only be seen with alt-click or rightclick.

### LINKED ISSUE #9184: Napalm/Hooch recipe conflict
Hooch
required_reagents = list ("sugar" = 1, "ethanol" = 2, "fuel" = 1)

Napalm
required_reagents = list("sugar" = 1, "fuel" = 1, "ethanol" = 1 )

Trying to mix napalm in your beaker will result in hooch instead.

### PR DESCRIPTION
**Pull request by TheVekter**
- Fixes #9184: Hooch is now made with 2 parts Ethanol, 1 part welder fuel and 1 part Universal Enzyme (Catalyst).
- Fixes #9122: Silver slime cores will no longer spawn the drink parent item. However, they can still spawn glasses and other drinking vessels. Will fix this if it's wanted, but I find it humorous.
- Fixes #9098: While not an actual bug, clarification! Restart board = Reboot board now, and each board in the mechfab uses its actual name to prevent confusion.
- Fixes #9077: Wizard's den now has the same intercom as the Syndie shuttle! (Yes I know this has map issues I'll fix them in the morning)
- Fixes #9066: Noslips are now paintable. Painting them does not remove their noslip properties. I've also removed the unique description on brown noslips, as (given how low the impact of noslips is) it really should be harder to discern them than just examining them.

### CODE REVIEW

**Comment by Alek2ander** [comment]
Did you run the map cleaner after your map edits?

**Comment by Lumipharon** [comment]
Most things that use enzyme don't actually consume it - it's just a catalyst.
It's also (mildly) rare, and a pain to get more of, if you decided to say, produce a shitload of hooch.

**Comment by TheVekter** [comment]
No, that's why it's fucked up. I'll screw with it in a few. There's no way to run map cleaner on the z-level maps I don't think.

And I'll look into making it a catalyst.

**Comment by Man-Shroom** [comment]
Does this fix the unpaintable clown shoes bug?

**Comment by TheVekter** [comment]
I wasn't aware that being unable to paint clown shoes wasn't intentional.

**Comment by TheVekter** [comment]
Woo, that worked.

**Pull request merged**
