### PR TITLE
Lowers reactive armour activation chance

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
From 50% to 30%

### CODE REVIEW

**Comment by TechnoAlchemisto** [comment]
Adios Mekhi!

**Comment by kevinz000** [comment]
i ded

**Comment by Archie700** [comment]
No please don't nerf the meme powergame armour that is literally a terrible piece of shit

**Comment by Zilenan91** [comment]
How about instead of nerfing the bs armor we just take it out of the RD locker and put it on the derelict

**Comment by Archie700** [comment]
but muh traitor objective

**Comment by Zilenan91** [comment]
>caring about objectives

**Comment by Archie700** [comment]
actually how about we move it to armory like the reflector vest

**Comment by PKPenguin321** [comment]
Or we could remove it

**Comment by Zilenan91** [comment]
Moving it to the armory is a terrible idea because sec would use it every round. Should just be put on the derelict so we can pretend we have special space content.

**Comment by Archie700** [comment]
Should nerf it so that the rta has a lower chance to teleport for every time the person gets hit

**Comment by Robustin** [comment]
>Best piece of armor in the game goes to RD at roundstart

Like science dept. doesn't get enough perks as it is. This was long overdue. 50% for even stun-based projectiles is just stupid.  Even if you're smart enough to go for the cuff and strip, some other idiot is always going to screw it up. Even at 30% it will still be shitty, but any nerf to RTA is a good thing.

**Comment by Steelpoint** [comment]
Why don't you just make the reactive armour like real reactive armour, make it completely ignore up to three attacks that deal 15 or so damage.

That or remove it.

**Comment by GunHog** [comment]
If you are doing this, at least remove that stupid radiation thing.

**Comment by Buggy123** [comment]
:-1: As is, I've rarely had it actually help in a situation where I need it, instead it usually just teleports me away when someone throws random stuff at me. I don't see the need for a nerf.

**Comment by PKPenguin321** [comment]
>I don't see the need for a nerf.

then you clearly don't play enough, this is basically the best armor in the game. it pretty much negates any form of stuns or damage unless you get extremely lucky.

**Comment by Lumipharon** [comment]
Just like, add a fucking charge timer between teleports (20 seconds or something, or make it require a battery, with each teleport using up X charge.

Seriously, there are much more interesting ways to nerf this/

**Comment by PKPenguin321** [comment]
wyh don't we do all of the above tbh

**Comment by Aloraydrel** [comment]
pull the tirgger on the meme armor

**Pull request closed without merging**
