### PR TITLE
Adds missing box sprites and reworks some ammo boxes

### LINKED ISSUE #32668: Missing illustration sprites on boxes.
https://github.com/tgstation/tgstation/blob/7a3a66a4f8b8bc5c8e993d5e1b9bd61df90d36a5/code/game/objects/items/storage/boxes.dm#L315

https://github.com/tgstation/tgstation/blob/7a3a66a4f8b8bc5c8e993d5e1b9bd61df90d36a5/code/game/objects/items/storage/boxes.dm#L323

https://github.com/tgstation/tgstation/blob/7a3a66a4f8b8bc5c8e993d5e1b9bd61df90d36a5/code/game/objects/items/storage/boxes.dm#L331

https://github.com/tgstation/tgstation/blob/7a3a66a4f8b8bc5c8e993d5e1b9bd61df90d36a5/code/game/objects/items/storage/boxes.dm#L348

https://github.com/tgstation/tgstation/blob/7a3a66a4f8b8bc5c8e993d5e1b9bd61df90d36a5/code/game/objects/items/storage/boxes.dm#L567

Also, the shotgun shell boxes need to be 3/4 and there's probably a few more I missed.

https://github.com/tgstation/tgstation/blob/master/icons/obj/storage.dmi < the file of boxes and various crap that needs 3/4

### PR DESCRIPTION
**Pull request by Bokkiewokkie**
## About The Pull Request

Adds some box sprites for a lot of boxes that didn't have their own ones and changes the toy and shotgun ammo boxes to a design more similar to normal ones.
Fixes #32668

## Why It's Good For The Game

It makes boxes more easily recognisable from a distance and makes it so you don't have to examine a box before knowing exactly what's in it.

## Changelog

:cl:
imageadd: adds box icons for tons of boxes.
imageadd: changes the toy and shotgun ammo boxes so they're in the new art style.
/:cl:

### CODE REVIEW

**Comment by HomocidlePancakes** [comment]
12G boxes are fine as they are. They look somewhat in line with other ammo boxes.

**Comment by kriskog** [comment]
Could you get us some pictures?

**Comment by Bokkiewokkie** [comment]
> Could you get us some pictures?

Thanks for reminding me, some pictures are definitely useful when judging new images.
preview

Feel free to criticize my work aswell, I'm completely open to changing things or leaving them out!

**Comment by improvedname** [comment]
I dont like the buckshot/rubbershots one but i also feel like they could be turned into fancy sprites

**Comment by cacogen** [comment]
I like standardising the boxes

**Comment by Bokkiewokkie** [comment]
Made some new box types (and some more little icons) and just wanted to put them here to get people's opinions. (blue: medbox, purple: scibox, brown: cargobox)
Preview2
(bottom left and middle icons were already there but are just for comparison to the medbox)

**Comment by Bawhoppen** [comment]
I don't think all the boxes should be exactly the same, just the same consistent art style
having them all be exactly uniform in size will look kinda repetitive

ammo boxes can and probably should still be like longer but just in a proper 3/4ths art style

**Comment by cacogen** [comment]
The frames for department colour coding work. The line above looks odd. The
medical cross doesn't work. The yellow recoloured box works but I don't
like the colour much.

**Comment by Bokkiewokkie** [comment]
Alright I just removed the new box proposals for now since I feel like they're a little contraversial.
Also edited the shotgun ammo and toy boxes to be this:
preview3
Since it is pretty much just the old ones converted to the newer art style.

**Comment by Bawhoppen** [comment]
those new ammo boxes look pretty good to me :+1: (though why is one taller than the other?)
also might be worth trying to make them a little wider and see if they look even better that way

**Comment by Bokkiewokkie** [comment]
The left one being taller was a mistake I made when making the preview (The invisible background in an .dmi becomes black in other formats)
And I made the boxes longer in this image to give a feel of what they'd look like compared to the shorter ones:
preview4 preview3

**Comment by Bawhoppen** [comment]
Ah yeah, definitely go with the smaller ones I think. Anyways, good stuff!

**Review by Cyberboss — CHANGES_REQUESTED** [review]
Looks good, just delete the "_old" variants please. They exist in the git history.

**Review by Cyberboss — APPROVED** [review]

**Comment by Cyberboss** [comment]
Thanks for contributing to /tg/station!

**Pull request merged**
