### PR TITLE
More screen alerts

### PR DESCRIPTION
**Pull request by MrPerson**
High, blind, embedded objects, asleep, weightlessness, new law (silicons), hacked (cyborgs), and locked down (cyborgs). The new law alert times out on its own after 30 seconds. The code for timing out is rough but works.

Sprites are provided by ZyloWalsh and can be seen at https://tgstation13.org/phpBB/viewtopic.php?f=11&t=3167
Drunk isn't in atm because I was waiting on phil to finish some reagent stuff. Hallu kind of ruined the "surprise" so I decided not to use it. High uses the hallu icon instead. Weaken/stun/paralysis are also not in right now because I'm lazy. All the sprites are included even if they're unused.

Added a proc human/has_embedded_objects() that returns 1 if src has any objects embedded in any limbs.

### CODE REVIEW

**Comment by RandomMarine** [comment]
Instead of making the new law alert time-based, it should be able to be clicked to dismiss it so afk silicons will never miss a law change.

**Comment by MrPerson** [comment]
I suppose it could also clear when you view the new laws. Or both.

**Comment by kingofkosmos** [comment]
Would it be possible to have "you're being pulled" and "you're being grabbed" as status alerts? And clicking on the icon would equal the same as using disarm --> breaking the pull/grab.

**Comment by optimumtact** [comment]
@MrPerson please fix, this is a good un

**Comment by Razharas** [comment]
The fire hungers @MrPerson 
It needs old prs

**Comment by MrPerson** [comment]
Updated. Didn't want to sneak this in the middle of the freeze.

I'll do cancelling alerts later I guess.

**Pull request merged**
