### PR TITLE
 [WIP] Gives Different Borg Modules Flash Cooldowns

### PR DESCRIPTION
**Pull request by wesoda25**
## About The Pull Request

Different borg modules now have different types of flashes, tiers 1 to 3. Do note, a normal flash stun lasts ~12 seconds.

Tier 1
Cooldown: 4 seconds
Modules: Security, Peacekeeper

Tier 2
Cooldown: 14 seconds
Modules: Medical, Janitor, Clown, Butler

Tier 3
Cooldown: 20 seconds
Modules: Mining, Standard, Engineering

## Why It's Good For The Game

One of the greatest flaws of a majority of the servers silicon players is their tendency to validhunt. Installing cooldowns on borg flashes will decrease their mentality of catching criminals, and force players to do their best to prevent harm. Instead of chain stunning a traitor "because they can be harmful", borgs will now have to get creative, bolting the criminal down, which gives them room for escape.

Similarly, it will cement certain modules as more powerful in terms of stuns, due to their intended purpose. Peacekeeper and Security (updated even though its gone and should never come back) both get the shortest cooldown, as they are intended to prevent harm, which a flash is useful for. Medical, Janitor, Clown, and Butler modules all get a medium cooldown, which ends a bit after the stun for a flash expires (making chain stunning not possible). Mining, Standard, and Engineering modules, the most powerful and a valid hunters first choice, get the longest cooldown. This serves to enforce them as their intended functions, engineering fixing things, mining mining, and standard doing whatever the fuck they're intended for.

Expanding on this, cooldowns will make the modules more equally balanced. While you might get self repairing as an engiborg, or ranged attack as mining borg, you also get a much weaker flash variant. This will make players more willing to experiment with other borg modules, as opposed to just what was considered the strongest.

**Additional:** Up to now, I've been copypasting what was in my original PR (#42829). I gave up on that PR due to burn out, and didn't really plan on remaking it. However, imsxzs recent PR (#44571) has seemingly forced my hand, as while I do believe there is an issue with borg balance and valid hunting, imsxz's solution is not the best we could have. I'm just trying to put more solutions on the table, give MODS!! a variety of sorts to choose from. 

## Changelog
:cl:
add: borg flash variants tiers 1-3
balance: mining, engineering, and standard modules now have a 20 second flash cooldown
balance: medical, janitor, clown, and butler modules now have a 14 second flash cooldown
balance: peacekeeper and security modules now have a 4 second flash cooldown
imageadd: sprite for recharging flashes
/:cl:

also I still need to fix a bug (mr cobblestone!!) and I want to have a different sprite during cooldown, along with a message for use during cooldown (The flash is still recharging!). I am willing to change the length of borg flash cooldowns.

### CODE REVIEW

**Comment by carshalash** [comment]
It's something

**Comment by wesoda25** [comment]
also uh if you were paying attention to what I was saying on imsxz PR, I was going through a rollercoaster of opinions. Its bc I was under the impression that the dragging slowdown resulted in borgs not being able to pick up people. As they still retain this ability, I will assume that borg balance is not blown out of the water and proceed accordingly.

**Comment by PKPenguin321** [comment]
Janitor and Butler should be tier 3

**Comment by wesoda25** [comment]
> Janitor and Butler should be tier 3

Really? Sure they have their powers, but they really aren't that good. Neurotoxin was nerfed and butler alongside it, and janitor just has lube and the ability to pick up small items. If anything I was considering making med borg tier 3 (since flash + saw is a powerful combo), but not those two. Is there something I'm missing?

**Comment by carshalash** [comment]
I think the reasoning behind mining, standard, engineering being tier 3 is due to their quick access to be able to do something else while flashed while janitor and butler are kinda just meme roles and not too worrisome to leave them at 2.

**Comment by zxaber** [comment]
Far as I know, borg fireman carry is broken. Every time I try it, the person just falls off after a step.

**Comment by wesoda25** [comment]
> Far as I know, borg fireman carry is broken. Every time I try it, the person just falls off after a step.

action told me he couldnt replicate, I move forward with the understanding that it is not broken (btw were they cuffed, ik that was broken)

**Comment by wesoda25** [comment]
@ExcessiveUseOfCobblestone cobby i cant figure some stuff out and need you to hold my hand through this again!

**Comment by ATH1909** [comment]
I'll take this over imsxz's PR any day of the week.

Can the flashes still burn out?

**Comment by zxaber** [comment]
In a test server with the current build and I'm unable to get borg fireman carry to work for more than a single tile, regardless of if the human is handcuffed, or why they're horizontal.

**Comment by NoxVS** [comment]
Borg fireman carry does in fact not work. The most they can do is buckle someone to them, and people who aren’t conscious or are stunned will immediately fall off the borg once they stop moving. Borgs of medium and higher duration will be too slow to do anything because of the drag slowdown

Alternative idea - stop messing with borg flashes because of validhunting borgs. This should be a policy problem, not a code problem. Especially when the code “fix” is just “fuck borgs”. I somehow manage to not validhunt as borg despite having a flash, so maybe they don’t have whatever magic validhunting inducing effect you are hoping to achieve with this. It won’t stop the problem of valid hunters and will just result in the shitty borg players finding new ways to be shitty and the good borg players finding new things to play as because it’s not fun to play borg when all that you see is nerf after nerf. They are already so weak to many things and it’s so frustrating to see people suggest to make them even weaker. A flash is lethal. An EMP is lethal. If anyone with RD access gets a robotics console, a single button push is lethal. A traitor can subvert the AI, use an EMP implant, use a flash, use a laser pointer, emag the cyborg, steal ion weaponry and kill it from afar, make an EMP by just pouring a soda can of metal into a soda can of uranium. It’s laughably easy to kill a cyborg and these changes are just making it even easier.

**Comment by necromanceranne** [comment]
Butler borgs have an alternative to the flash against carbons that is far stronger. The spray can. It's like a flash but hit you with ignitably fluid, which lets them combo it into their lighter and then repeatedly apply the spray can for increasing fire stacks.

**Comment by HomocidlePancakes** [comment]
Imsxz did this better

**Comment by wesoda25** [comment]
Action put up a fix PR so we’re good. Anyways, I’m still on the fence about moving butler to tier 3, especially when their flash could be useful in stopping stuff like bar fights. Idk...

**Comment by datorangebottle** [comment]
Why can't Cyborgs validhunt when it's explicitly stated by their laws that they have to do so, in most cases?

I'm still confused as to how Cyborgs are different from any other job that can validhunt. Are we gonna remove the AI's ability to bolt doors shut because they use it to valid people?

**Comment by wesoda25** [comment]
> Why can't Cyborgs validhunt when it's explicitly stated by their laws that they have to do so, in most cases?
> 
> I'm still confused as to how Cyborgs are different from any other job that can validhunt. Are we gonna remove the AI's ability to bolt doors shut because they use it to valid people?

A borgs laws doesn't force them to valid hunt. I have seen countless borgs run past dying humans just so that they can prevent a harmful human from doing future harm. This ties into a reason as to why I think imsxz PR won't help, it'll just make borgs better at valid hunting. 

My PR keeps most modules from being able to chain stun, meaning valid hunting isn't really possible for them. Hopefully this will encourage them to actually keep dying humans from dying, as opposed to preventing future harm. 

Not to mention valid hunting isn't the sole reason for this PR.

**Comment by wesoda25** [comment]
Ok so I added a recharge sprite, some other stuff. Now I just need to add a failure message if you try to use it during recharge (easy), and fix a bug where borg flash icon (the one that appears on a borg) doesn't appear for AOE flash (idk how to fix this).

**Comment by ExcessiveUseOfCobblestone** [comment]
*sigh*

**Comment by wesoda25** [comment]
> _sigh_

cobby ur contractionally obligated to help me what do??

**Comment by ExcessiveUseOfCobblestone** [comment]
This sounds good lol https://github.com/tgstation/tgstation/pull/42829#issuecomment-466463461

**Comment by ATH1909** [comment]
Would it be possible to make the tier 1 flashes either unable to burn out or treat the borg doing the flashing like a revhead (for the purposes of the chances of the flash burning out after each flashing)? If having a flash with a cooldown short enough to chainflash someone or effectively flash a group of people is gonna be the peacekeeper borg's big new draw, it'd really suck if their ability to do that was dependent on them not getting terrible flash burn out RNG.

**Comment by wesoda25** [comment]
> Would it be possible to make the tier 1 flashes either unable to burn out or require more uses in a short period of time before they have a chance to burn out after a usage?

No flashes are fine.

To review, this is how flash code works (to my understanding): every time you use a flash theres a chance it will burn out. Using a flash multiple times at once increases this chance. So, my PR will basically make it harder for tier 2 and 3 modules to not burn out, but not impossible. I see no issue with this.

**Comment by carshalash** [comment]
I think mining being in tier 2 would be better due to ash lizards

**Comment by Timonkeyn** [comment]
i love this Change because borg battles were just Flash Combat and nof its tactical flashing

**Comment by wesoda25** [comment]
> This sounds good lol [#42829 (comment)](https://github.com/tgstation/tgstation/pull/42829#issuecomment-466463461)

i dont get it

**Comment by ExcessiveUseOfCobblestone** [comment]
what do you not get...

**Comment by Fikou** [comment]
combat borg module to decrease flash cooldown when

**Comment by wesoda25** [comment]
> it is clear the people want a silicon nerf and not a silicon buff so i have closed my PR, wesoda take the wheel

thank u imsxz but i legitimately think that borgs with disarms is just a new world of cancer and borg murders waiting to happen, I don't think it'll improve little if anything involving borgs and just create more issues

**Comment by terranaut1** [comment]
flashes are readily available for crew and if you flash a borg once you're basically guaranteed to win agaisnt him adn the borg can do nothing to defend against it.

all the crew that are dangerous to a borg / rogue AI - sec, engineers and and validhunters - have flash protection anyway.
this pr is bad and you should feel bad

**Comment by zombiegums** [comment]
I still think trying to balance around poor player behaviour is ???, but w/e. This precedent was established with secborgs getting nixed and drones being given the boot, so it's not surprising any more. 

Out of curiosity, if you see Asimov borgs ignoring dying humans in need in order to validhunt, do you ahelp them so that they can be told to stop ignoring their laws?

I picked peacekeeper during a mindswap wiz round, dosed the murderboning apprentice with pax so he couldn't kill an officer I was trying to grab back from him. He then went and got the ion rifle and game ended me when I tried to save another officer. Nothing I could do about that  and I was fine w/ it. Unlike organics, borgs have zero protection against anything that will stun them, that is the caveat of playing them. Your only recourse is to run away, and if you're running away - you're not validhunting or hard-stunning someone all the way to the brig. That is why I cannot wrap my head the issue people have with borgs outplaying them. 

If this is merged and anyone complains about getting caught by a borg, at least we'll know they're unrobust as there's literally zero excuse for it now. ;^)

**Comment by imsxz** [comment]
no because its not punishable to be a shitty borg player if you arent explicitly breaking your laws, ahelping it is wasting energy.

saying that "borgs have zero caveat against anything that stuns them" is kinda silly as well, given they only have like 5 fuckin things that stun them compared to the hundreds for humans. Flashbangs, flashes, and EMP's all can stun humans in their own circumstances. The way I look at it is "borgs arent immune to flashes" rather than "borgs are weak to flashes" (kinda like glass half full vs half empty).

Human's don't get magic protection against 90% of stuns against them unless you count stim chems which are seldom used.

It's well established that humans that die to borgs are unrobust already. The real cancer comes out when you dont want to/arent allowed to kill them but they insist on chasing you for whatever reason.

**Comment by terranaut1** [comment]
>The real cancer comes out when you dont want to/arent allowed to kill them but they insist on chasing you for whatever reason.
If a borg is chasing you for whatever reason and ignoring your "law two fuck off" then kill them because they're ignoring their laws and rogue borgs are free game tbh

**Comment by imsxz** [comment]
>dont want to kill them

killing borgs as a nonatag is lame as fuck and makes you gay

**Comment by zombiegums** [comment]
How is it not punishable to run past dying humans (current harm, because they will continue to decline in health until they get help) to try and catch someone who may or may not inflict future harm on people? They're literally ignoring law 1 and point 2 of Asimov + Human harm under Silicon Policy. The example that wesoda gave and the one I responded to is clearly a rule violation. 

Yeah, all of those things can stun organics - but they have ways of circumventing those through gathering gear to protect themselves from it, etc. If someone decides to get full body augs or cybernetic limbs, they should be under the assumption that if they get EMP'd they're gonna suffer for it. In fact, it's something I try and tell people before I bother giving them those surgeries. Borgs, on the other hand, can't choose to be immune to those things. 

If a borg is refusing to leave you alone (and has zero justification for it) and your only recourse is to kill them after giving them multiple warnings to shoo, I can't really fault you for acting on your warning. The point of contention for me is when a non-antag assumes an Asimov borg is going to interfere and kills them for it, especially if they then don't take steps to get the borg revived.

I think it's a shame you closed your PR, btw. Despite my posts there and here, I mostly wanted to understand why you guys believe borgs need to be nerfed without validhunting being the main reason. Obviously I am biased because borg is what I play, but because I don't validhunt and generally try to avoid combat, I needed more insight.

**Comment by imsxz** [comment]
admins cant prove if a borg player maliciously ignored the dying person or is just really tunnel visioned

i genuinely felt that my PR was a buff, i rarely use flash as borg personally outside of stunning other borgs or when im murderboning(for good or evil). Of course there are outliers where I'll flash someone as asimov with the intention of stopping them from commit harmies but i avoid it when i can because 90% of the time if i flash a desworder he gets lynched and thats no bueno. shove is a lot more versatile because it can be used when it *really* matters, most antags will have flash protection and so does sec so the times i see myself using flash are usually the times the person would have flash protection.

thats my personal take, dont interpret it as me saying that it's the correct way, but thats the logic i had going into it. I've been playing borg more recently and as an engiborg i wanted to shove someone into a disposals chute easily and push people onto glass tables easily.

**Comment by zombiegums** [comment]
ah i feel you, still i feel like it's something that could be noted down. if the borg player continues to exhibit that behaviour, a clear pattern could be established which would make it actionable.

yeah that's the insight that i was trying to get from your pr, because i use my flash pretty much as a defensive tool or to de-escalate fights and rarely play organic, so i genuinely wanted to know how shoving was better. i can see where you're coming from now, and when i spoke to others about it yesterday they shared similar sentiments. for me, as much as i dislike sec doing harm when there's literally no reason to, i just felt like shoving an officer would cause more issues (shoving an officer harmbatoning a dude who's detained, which then leads to the borg getting flashed and killed for interfering, etc).

i still feel like peacekeeper is overlooked, it is a good (but situational) module but i'd love for it to get more added to its kit so that it feels less niche. i just don't know what could be added that wouldn't make it seem like secborg 2.0. 

either way, ty for sharing your thoughts about this, i appreciate it.

**Comment by ExcessiveUseOfCobblestone** [comment]
> (shoving an officer harmbatoning a dude who's detained, which then leads to the borg getting flashed and killed for interfering, etc).

this is a policy/admin complaint issue as borgs are protected from being killed for following asimov.

**Comment by Detective-Google** [comment]
I love that the solution to borgs validhunting is to just kneecap borgs.

This pr seems pretty based on bagil players as well? I feel like this isn't necessary on Sybil 

Overall this is a rule/policy issue not a code issue, any braindead retard can kill a borg, and if you are commiting harm around borgs like a retard you deserve to have them eliminate the possibility of causing harm.

Do some shitbags use borg to run around validhunting? Yes.
Will this shit on people just trying to stop murderbone and do their job? Double yes

The problem I have with this pr is that it hinders good borgs just as much as bad ones

(Also if anything needs a balance check it's the stupid op emagged borgs, infinite stunbaton, infinite unobtainable chems, etc is ridiculous, even though it is a lot of fun to play emagged borg)

**Comment by wesoda25** [comment]
I play all servers

**Comment by wesoda25** [comment]
also cobby i like don't get wha tyou want me to give TRUE FALSE returns to and stuff

**Comment by ExcessiveUseOfCobblestone** [comment]
```
/obj/item/assembly/flash/proc/flash_carbon(mob/living/carbon/M, mob/user, power = 15, targeted = TRUE, generic_message = FALSE)
	if(!istype(M))
		return FALSE //fail2flash, easy enough
	if(user)
		log_combat(user, M, "[targeted? "flashed(targeted)" : "flashed(AOE)"]", src)
	else //caused by emp/remote signal
		M.log_message("was [targeted? "flashed(targeted)" : "flashed(AOE)"]",LOG_ATTACK)
	if(generic_message && M != user)
		to_chat(M, "<span class='disarm'>[src] emits a blinding light!</span>")
	if(targeted)
		if(M.flash_act(1, 1)) //if this is true we will always successfully flash the user, so a return goes under here but not needed for each individual sub-check
			if(M.confused < power)
				var/diff = power * CONFUSION_STACK_MAX_MULTIPLIER - M.confused
				M.confused += min(power, diff)
			if(user)
				terrible_conversion_proc(M, user)
				visible_message("<span class='disarm'>[user] blinds [M] with the flash!</span>")
				to_chat(user, "<span class='danger'>You blind [M] with the flash!</span>")
				to_chat(M, "<span class='userdanger'>[user] blinds you with the flash!</span>")
			else
				to_chat(M, "<span class='userdanger'>You are blinded by [src]!</span>")
			M.Paralyze(rand(80,120))
                        return TRUE // tada!
		else if(user)
			visible_message("<span class='disarm'>[user] fails to blind [M] with the flash!</span>")
			to_chat(user, "<span class='warning'>You fail to blind [M] with the flash!</span>")
			to_chat(M, "<span class='danger'>[user] fails to blind you with the flash!</span>")
                        return FALSE // all of these are failures
		else
			to_chat(M, "<span class='danger'>[src] fails to blind you!</span>")
                        return FALSE //this is a failure
	else
		if(M.flash_act())
			var/diff = power * CONFUSION_STACK_MAX_MULTIPLIER - M.confused
			M.confused += min(power, diff)
                        return TRUE // we flashed them
                return FALSE // we failed the flash_act
```

*sigh*

**Comment by wesoda25** [comment]
chief it aint workin

**Comment by wesoda25** [comment]
top 10 times professor cobblestone misled innocent ol wesoda

**Comment by optimumtact** [comment]
Maybe learn to code instead of making maintainers write your change in the review

**Comment by optimumtact** [comment]
@ExcessiveUseOfCobblestone if they can't code it don't spoon feed them just close the PR

**Comment by ExcessiveUseOfCobblestone** [comment]
> 
> 
> chief it aint workin

of course it didn't you don't have half of the (working) code from your previous PR in here.

**Comment by wesoda25** [comment]
no don tclose it ill figure it out

**Comment by ExcessiveUseOfCobblestone** [comment]
just PR literally the same thing you had from last time and fix that. It's saner to shave off bad code than it is to add good code (you've already previously written)

**Comment by wesoda25** [comment]
funny really everytime I open this its at the climax of my burnout

**Pull request closed without merging**
