### PR TITLE
Fixes shuttle paths [fuck me]

### LINKED ISSUE #19324: Shuttle rotation is basically just super broken now
sybil procreatory fortress omega 2016-07-14 205204
yeah uh I think @coiax broke this but he's gone, this is what happens to the white ship on dreamstation as long as it's not docked at the station

### LINKED ISSUE #19336: Using titanium on a displaced girder doesn't make a false wall, and deletes the Titanium.
Basically I tried to make a false wall on the emergency shuttle, but when I used the Titanium sheets on the displaced girder, it told me it made a false wall, but it didn't do anything, and instead just deleted the Titanium.

### PR DESCRIPTION
**Pull request by Bawhoppen**
All shuttles now use proper smoothing paths, I had to update them all by hand

I have a few more things to fix for titanium in this PR aswell

Also all syndie shuttles are now consistent with each other. (Added some more turrets since they aren't indestructible now)

(I was exaggerating/joking when I said its like 50 files changed but it turns out it actually is)

:cl: 
add: Titanium now spawns in mining again. 
add: It has uses in R&D and robotics production.
add: All shuttle walls are now using a new proper smoothing path. Mappers please make sure to use this path correctly in the future. (along with tiles)
/:cl:

Fixes https://github.com/tgstation/tgstation/issues/19336
Fixes https://github.com/tgstation/tgstation/issues/19324

### CODE REVIEW

**Comment by Bawhoppen** [comment]
but no conflicts :tada: 
wow thats lucky

**Comment by Bawhoppen** [comment]
62 files changed wew lad its like I'm a hotshot or something

**Comment by tedward1337** [comment]
You have to buy me dinner first Baw

**Comment by Zilenan91** [comment]
Why make titanium spawn again if we can't build shuttles, that's why it was removed

**Comment by Jalleo** [comment]
If you fixed the titanium falsewall issue please reference that being fixed

**Comment by Bawhoppen** [comment]
@Zilenan91 you will be able to soon and plus now its used in some recipes in R&D and such

**Comment by Bawhoppen** [comment]
why is travis not going

**Comment by Bawhoppen** [comment]
there he is travis old pal

**Comment by Bawhoppen** [comment]
damaged floors:
ss 2016-07-20 at 09 40 18


now remove that tag you cuck

**Pull request merged**
