### PR TITLE
Removed an inexplicable Cyrillic letter from the code.

### LINKED ISSUE #77906: 1 cyrillic letter in code
https://github.com/tgstation/tgstation/blob/master/code/game/objects/items/food/misc.dm#L60

The first letter "с" in "caramel_popcorn" icon state is cyrillic...

image

### PR DESCRIPTION
**Pull request by lizardqueenlexi**
## About The Pull Request

Resolves #77906

I've mercilessly torn the soul from the game and rendered it functionally unplayable. The icon state for caramel popcorn, for whatever reason, used a Cyrillic "с" in its name, which I've cruelly rendered into a Latin "c" instead.
## Why It's Good For The Game

It's not pronounced "saramel".
## Changelog
No player-facing changes.

### CODE REVIEW

**Comment by optimumtact** [comment]
we really need a lint for this

**Review by Ghommie — APPROVED** [review]

**Comment by mc-oofert** [comment]
soul removal

**Comment by Sealed101** [comment]
it's оvег соmгаdеs

**Comment by atlasle** [comment]
image these coders will really go ahead and change everything that makes this game

**Comment by Dawnseer** [comment]
The fall of tgstation

**Comment by AndroBetel** [comment]
>HOW did this even happen

cyrillic с and latin c are on the same key in russian keyboard layout, so it's a pretty common typo for slavs to do

**Comment by Kiromaka** [comment]
R.I.P - С.

**Pull request merged**
