### PR TITLE
Partial revert of datum poll creation, fixes duplicated irv votes

### PR DESCRIPTION
**Pull request by MrsTonedOne**
Partially reverts #50843 by @Jordie0608 - Datum based poll creation and vote handling update.

Reverts the part that removed a check for duplicated votes in IRV when displaying them to the player

Also fixes the code that would accept duplicated votes passed from the client. (not from jordie's poll refactor pr.)

The race condition still exists, thats harder to fix, counting code handles this correctly, and now at least the duplicated votes won't be re-displayed or multiplied exponentially.

### CODE REVIEW

**Comment by MrStonedOne** [comment]
Context: https://tgstation13.org/phpBB/viewtopic.php?p=594571

**Comment by Timberpoes** [comment]
loading tgstation.dme
loading interface\skin.dmf
code\modules\mob\dead\new_player\poll.dm:248:error: option_copy: undefined var
tgstation.dmb - 1 error, 0 warnings (3/5/21 1:27 pm)

**Review by Timberpoes — DISMISSED** [review]
loading tgstation.dme
loading interface\skin.dmf
code\modules\mob\dead\new_player\poll.dm:248:error: option_copy: undefined var
tgstation.dmb - 1 error, 0 warnings (3/5/21 1:27 pm)

**Comment by MrStonedOne** [comment]
Fuck you @Timberpoes

**Comment by Timberpoes** [comment]
> 
> 
> Fuck you @Timberpoes

To be fair, we currently have spurious CI failures on active PRs. I am currently checking most CI failing PRs to make sure the failure is not related to the PR and restarting CI checks where it isn't.

**Comment by Jordie0608** [comment]
Wew.

**Pull request merged**
