### PR TITLE
Enables the mice migration event

### PR DESCRIPTION
**Pull request by coiax**
:cl: coiax
add: Additional mice sometimes appear in the maintenance tunnels.
Engineers beware!
/:cl:

I probably had too much fun writing this.

### CODE REVIEW

**Comment by Firecage** [comment]
Coiax. May I just say the following?

No. NO. GOD NO. OH GOD WHY!?!?!?

**Comment by TehZombehz** [comment]
Due to Ragnarok, a whoop of energy draining parasites have stampeded into the place with all those juicy wires.

**Review by Cyberboss — APPROVED** [review]

**Comment by FantasticFwoosh** [comment]
10 mice on ministation is going to multiply to about 50 mice, i guarantee.

**_VERMINTIDE_**

**Comment by xxalpha** [comment]
Welcome back, with a good PR too.

**Comment by coiax** [comment]
@xxalpha, I'm literally just enabling a debug event I made when I made mouse start locations randomised. I've been mildly back for a while now. But thanks anyway <3

**Comment by xxalpha** [comment]
All I know is that rats.

**Comment by ExcessiveUseOfCobblestone** [comment]
Please rename it to the Squeakening

**Comment by optimumtact** [comment]
This is fine, but I do wish people would push event descriptions/names into files for easier modification and reading, rather than sandwiching them in code as lists (see ai laws and gibbering as examples I've added)

**Pull request merged**
