### PR TITLE
Adds the Syndicate Reinforcement Gateway 

### PR DESCRIPTION
**Pull request by Robustin**
:cl: Robustin, FantasticFwoosh
add: On a 40+ population station, Syndicate Traitors can now purchase a reinforcement gateway for 20TC. The gateway is anything but discrete - but if you can keep it intact, then an ever-growing stream of Syndicate thugs will arrive to assist you. 
/:cl:

The reinforcements are all (player-controlled) simple mobs for now. This version is test/merge ready. The mobs have a 50/50 chance of being ranged or melee and have 100hp. The ranged use a slow-firing 10mm gun, the melee basically use a switchblade. There is a small chance that an elite version will spawn, which deals roughly 2x damage. The mobs gib on death (no explosion though). The ranged variant also has an ability that lets them place a sandbag barrier every couple minutes, the melee variant gets a knife rush that lets them quickly move forward while attacking anyone in their path.

Requires 40pop to use. The timer between reinforcements starts at 4.5 minutes, getting 30 seconds faster with each cycle. After about 20 minutes, it will max out at 1 reinforcement per minute. The gateway emits sound when reinforcements arive and continuously emits a 5-radius colored light that changes color when a reinforcement is imminent. 

Why? Its fun, and traitor gameplay has been stale for ages. Requires strategy and planning to use effectively since it requires all of your TC, reinforcements cannot travel easily around the station, and reinforcements don't stand a chance 1v1 against most ranged weaponry. The gateway's placement will also require careful consideration, striking a balance between "easy access to the station" and "vulnerable to a counter-attack".

### CODE REVIEW

**Comment by optimumtact** [comment]
oh no

**Comment by qbmax32** [comment]
we need more ROBUSTINCODE(TM)

**Comment by Bawhoppen** [comment]
Fighting against simple animals (especially human ones) is never a fun mechanic.
I would've hoped you learned from that one time you spawned 50 syndicate simple mobs in the derelict and called it an event. It's pretty important in my eyes that you change them to proper humans in this PR, rather than later.

Also 20tc items are never good. If something is OP enough to justify being 20tc, it's probably too OP to be an uplink item in the first place.

**Comment by ma44** [comment]
Alongside the simple animals being controlled by humans, all of the syndicate simple that can spawn will always drop some combat boots, combat gloves, syndie IDs and armor vest + helmet

**Comment by subject217** [comment]
These simplemobs gib on death, assuming he used the correct ones, so there's no loot from them.

**Comment by Robustin** [comment]
No, there's plenty of Syndie mobs that don't drop anything, as I explained in the OP.

AI-simple mobs aren't engaging but under player control it opens up plenty of avenues of gameplay. Making them human requires a boat-load of snowflake code to prevent them from just being "Infinite Traitors", respawning Lexia Black as your minion with a Stechkin would be disastrous but keeping them as a mob with limited damage makes sure they don't get out of hand. I want it to be so that if Sec comes back with heavy armor and a shotgun that they can still push back multiple Syndies without having to worry about the syndies throwing soap at them in maint. 

My current feeling is that I would just spice up the simple mobs rather than write hundreds of lines of code so that they could play as humans without snowballing out of control using stolen guns/ID's/equipment. The "enhanced" simple mobs would get a few pseudo-spells that would help them protect each other and give them more tactical options besides "Shoot 1 bullet every 3 seconds".

**Comment by Iamgoofball** [comment]
welcome back robustin

**Comment by Robustin** [comment]
Thanks - are fire runtimes in Travis a thing now?

**Comment by PKPenguin321** [comment]
HoP-exclusive would fit this thematically

**Comment by MrDoomBringer** [comment]
Robustins back! welcome friend.

Also, what if instead of gateways, we had the syndicates get sent-in via the orbital supply-pod system? We already have syndicate supplypod sprites 😄

**Comment by Robustin** [comment]
I'll consider it. Fwoosh provided the gateway icon for Gang Wars though and it's pretty slick.

Drop Pods would certainly be loud but it would still be harder to locate if someone just puts them in a false-wall room in maint.

**Comment by ExcessiveUseOfCobblestone** [comment]
> simple mobs

> you intend to tweak the mobs, possible making them fully-human but with major restrictions on their ability to change equipment.

they're already given major restrictions on equip change (see: none), what do you need to tweak?

**Comment by FantasticFwoosh** [comment]
Yeah, nice to see my efforts being put to use.

It'd be cool if you could follow through it wormhole style to a z level to earn some pittance syndicate rewards like spare secret documents to sell but that's a crapshoot idea.

**Comment by ExcessiveUseOfCobblestone** [comment]
I wanted to shoehorn some skullgirl esque martial arts, would be cool if it opened a portal to fight "little boss" in a field of flowers.

**Comment by Robustin** [comment]
Plausible to have a kinda easter-egg trip through but that carries a lot of complications (making it on Centcom level can screw with post-round), You could send the sensitive/dangerous objectives there and then destroy the gateway too.

I gave the two reinforcement types an ability to flesh them out a bit more. The ranged Syndicate can deploy a sandbag barrier every 2 minutes, the melee Syndicate was pretty underpowered (these mobs move slower than humans, and only hit for 15) so I gave them a "Knife Rush" that has them quickly move forward - stabbing enemies along the way - and they will heal/reduce cooldown for each enemy they hit.

Overall with those abilities I'm orienting these guys to having an edge with in cramped fighting area, but they're not going to be able to do much fighting in the open, which seems fitting for the design of this device.

**Comment by FantasticFwoosh** [comment]
> Plausible to have a kinda easter-egg trip through but that carries a lot of complications (making it on Centcom level can screw with post-round), You could send the sensitive/dangerous objectives there and then destroy the gateway too.

Well as long as its pernamently enclosed, much of the generic teleporting equipment fails to function on centcomm anyway, would be fun to expand the syndicate base template into a actual mini-base.

> The ranged Syndicate can deploy a sandbag barrier every 2 minutes

Not super keen, these can be deconstructed & over time will clog up the area, they also offer the crew a significant amount of cover if they snuggle up to them while im sure simple mobs dont get the same benefit, what about a more contempary forcefield generator blockade but colored red like the cult juggernauts?

> "Knife Rush" that has them quickly move forward - stabbing enemies along the way - and they will heal/reduce cooldown for each enemy they hit.

Plausibly players can still block this by equipping a shield of some sort, can you put checks on it to make sure that the mob only heals if it actually lands a hit please.

**Comment by Dorsisdwarf** [comment]
if you're worried about the syndies gear-swapping if made human, make all their gear NODROP

**Comment by FantasticFwoosh** [comment]
> 
> 
> if you're worried about the syndies gear-swapping if made human, make all their gear NODROP

They're simple mobs.

**Comment by ExcessiveUseOfCobblestone** [comment]
One step closer to the genji dash...

**Comment by BebeYoshi** [comment]
Dumb question: Can they be stunned?

**Comment by ExcessiveUseOfCobblestone** [comment]
Not dumb & they're simplemobs so compare them to lavaland mobs.

AKA no they cannot be stunned despite looking like humans.

**Comment by BebeYoshi** [comment]
Can't simple mobs have a flag to be stunned just like minebots have?

**Comment by Robustin** [comment]
Minebots can be stunned?

If its not too snowflakey I wouldnt mind giving them some kind of reduced stun. I was considering changing their name to "Syndicate Automaton" or something as a harder tell that you can't taze them but without some kind of appropriate sprite it would just be silly. I guess the lore is that these guys are just hopped up on some really good space meth so they can't be stunned.

**Comment by Robustin** [comment]
I've added a HUD icon for the syndies and the Gateway owner. I figured that there was way too much risk of friendly fire if you had new reinforcements spawning in without even knowing what their leader looked like.

I also went the extra mile and gave the thing a password available to the owner, anyone who enters the password will join the owner's "team" so that the reinforcements will recognize them as an ally.

**Comment by Robustin** [comment]
I've added a Directive that will be given to reinforcements when they spawn, the owner (or other members who have entered the password) can change the directive. The default directive is essentially "Protect the Gateway and obey any traitors in your squad".

**Comment by duckay** [comment]
using steel rain will void the chance of tators just building a box with the beacon inside to stack up the amount of simplemobs.
also we need a clown/mime version of this

**Comment by tralezab** [comment]
may i pr the "Hilarious Reinforcement Gateway" to your branch as a clown only purchase?

**Pull request closed without merging**
