### PR TITLE
[CERE] Revised Robotics lab, revamped medbay, added lights to cargo shuttle

### LINKED ISSUE #29832: cerestation cargo shuttle is dark

### PR DESCRIPTION
**Pull request by ShizCalev**
🆑 ShizCalev
tweak: Cere's Medbay and Robotics areas are now more pretty! Rejoice!
/🆑

fixes #29832
Fixed door buttons in Medbay.
Fixed missing APC in tech storage
Fixed issues mentioned in @PraiseRatvar 's comment.

Pictures below

### CODE REVIEW

**Comment by PraiseRatvar** [comment]
this man has a few things to say about cere

**Comment by GunHog** [comment]
Pics plz?

**Comment by ShizCalev** [comment]
i haven't even committed yet, 1 sec. still revising a couple more areas.

**Comment by ShizCalev** [comment]
Robotics;

3mqhqaw

**Comment by GunHog** [comment]
ACCEPTABLE! :+1:

**Comment by ShizCalev** [comment]
Medbay:

3mqrdmt
3mqr15h
3mqqyxm
3mqrez7
3mqqahn

Patterns make the brain work harder, giving the perception of better quality. Cere's floors were all solid color, so giving it a bit more color to direct people around shouldddddd help a little.

**Comment by ShizCalev** [comment]
minor update for cryo:
3mqumns

**Comment by GunHog** [comment]
While you are at it, could you name the cloning room camera correctly? For some reason, I cannot find it on the Security Cam list, using a camera console. It could be a conflict or something like that.

**Comment by pubby** [comment]
Looks good.

**Comment by ShizCalev** [comment]
Viro still feels a bit empty, but I guess that just comes with the job.

**Pull request merged**
