### PR TITLE
Adds inhands for all the surgery tools.

### PR DESCRIPTION
**Pull request by nemvar**
## Why It's Good For The Game

Inhands good. Retractor and hemostat share inhands because I'm lazy.

## Changelog
:cl:
imageadd: added inhands for the cautery, retractor, drapes and hemostat.
/:cl:

### CODE REVIEW

**Comment by cacogen** [comment]
any inhand is better than no inhand but can we have a screenshot please

**Comment by MCterra10** [comment]
Bro do you even IconDiffs bro

**Comment by cacogen** [comment]
yeah but inhands are tiny sprites that don't make a lot of sense without a mob holding them

**Comment by ExcessiveUseOfCobblestone** [comment]
my bad i thought I merged this yesterday

**Pull request merged**
