### PR TITLE
Adds disco inferno shuttle.

### PR DESCRIPTION
**Pull request by DaxDupont**
[Changelogs]: 

:cl: Dax Dupont
add: Nanotrasen is happy to announce the pinnacle in plasma research! The Disco Inferno shuttle design is the result of decades of plasma research. Burn, baby, burn!
/:cl:

[why]: We need more funky shuttles, this actually puts the dance machine to good use! It's fun for the entire family, till it burns down that is.

Shuttle in transit: 
https://www.dropbox.com/s/5uwcj6ti13j6exq/discoinferno.mp4?dl=0

dreamseeker_2017-12-03_00-44-11

dreamseeker_2017-12-03_00-35-14

After corrections:
dreamseeker_2017-12-03_00-58-30

### CODE REVIEW

**Comment by epochayur** [comment]
pics

**Comment by DaxDupont** [comment]
@epochayur I readded the video, youtube blocked it for a bit

**Comment by DaxDupont** [comment]
Gonna add some pics too in a second

**Comment by Armhulen** [comment]
i mean it's ok

not a train of course

**Comment by Okand37** [comment]
You might want to consider making the walls highlighted in red "plastitanium/nodiagonal"

**Comment by DaxDupont** [comment]
You uploaded the wrong image but saw it in discord. fixing it.

**Comment by DaxDupont** [comment]
I can't fix the wall at the door for some reason, but the rest is fixed:
adu0lb1 1

**Comment by RogueSteampunker** [comment]
Lynch the Captain 2: Electric Boogaloo

**Comment by DaxDupont** [comment]
@RogueSteampunker Don't worry, absolutely nothing can go wrong.

**Comment by BeeSting12** [comment]
good shuttle, i like

**Comment by Mark9013100** [comment]
mandatory:
https://www.youtube.com/watch?v=A_sY2rjxq6M

**Comment by Grazyn** [comment]
Is the disco machine still ID locked to engineers? If so, that's gonna be a bummer

**Comment by jughu** [comment]
ALL THOSE YEARS WORKING FOR JUST A DANCE SHUTTLE?!?! 

NANOTRASEN REEEEE!!!

**Comment by DaxDupont** [comment]
@Grazyn Thanks for reminding me I have removed the access restriction.

**Comment by ShiggyDiggyDo** [comment]
Griffing: The Shuttle

**Comment by DaxDupont** [comment]
@ShiggyDiggyDo Worst thing that can happen is someone "accidently" setting it on fire with a lighter.

**Comment by DaxDupont** [comment]
I am gonna make a minor change still, sec

**Review by ShizCalev — APPROVED** [review]

**Comment by epochayur** [comment]
untitled

**Comment by Robustin** [comment]
This is basically a flying policy thread.

**Pull request merged**
