### PR TITLE
security officers should be allowed to be corrupt

### PR DESCRIPTION
**Pull request by creeperparty568**
[Changelogs]: # (Your PR should contain a detailed changelog of notable changes, titled and categorized appropriately. This includes, new features, sprites, sounds, balance changes, admin tools, map edits, removals, big refactors, config changes, hosting changes and important fixes. An example changelog has been provided below for you to edit. If you need additional help, read https://github.com/tgstation/tgstation/wiki/Changelogs)

:cl: corrupt officers
balance: Security Officers can be Traitors
/:cl:

[why]: # because it would be fun

### CODE REVIEW

**Comment by deathride58** [comment]
Have you been around when sec officers were able to roll traitor...?

If you have, you'd know exactly why this is a horrible idea.

**Comment by creeperparty568** [comment]
but it would be fun!

**Comment by Cyberboss** [comment]
Unless @KorPhaeron approves this, I'm closing it

**Comment by creeperparty568** [comment]
well i tried

**Comment by KorPhaeron** [comment]
We have a config option for this

**Pull request closed without merging**
