### PR TITLE
Add VS Code folder to gitignore

### PR DESCRIPTION
**Pull request by Cyberboss**

### CODE REVIEW

**Comment by AnturK** [comment]
While you're at it might as well add *.sublime-project and *.sumblime-workspace if anyone is using these.

**Comment by Cyberboss** [comment]
Something is demanding the line endings be converted :/

**Comment by optimumtact** [comment]
tempted to close these on the basis that people using crappy editors deserve death

**Comment by Cyberboss** [comment]
>Implying DM is a good editor

**Pull request merged**
