### PR TITLE
Giving the away missions some love: part 2

### LINKED ISSUE #12907: Some away missions spawn NODROP Hardsuit helmets

### LINKED ISSUE #12917: Away Mission Issues
**GENERAL**
`APCs are strange`
`Blast doors are broken`
`Shutter buttons are broken`
*BMPacker:*
`Generic Meat Snack items`
*Challenge:*
`Hardsuit helmet at 119,104`
*Example:*
`Exterior walls are not indestructable, it is possible to escape to the edge of the Z and see the second floor.`
`Sprite-less tiles`

### LINKED ISSUE #12947: "Challenge" awaymission is impossible
The gateway at the end of it is blocked by invisible shutters that cannot be opened. There is a button nearby but it lacks electronics to actually open the shutters.

### PR DESCRIPTION
**Pull request by MMMiracles**
Fixes several invisible item issues throughout all missions. Fixes broken shutter/blastdoors, floating buttons, and placed indestructible walls when needed. 

 Fixed a problem with the top section of the underground outpost only consisting of elevator buttons and shuttle walls (jesus christ how did this happen).

Fixes #12907
Fixes #12917
Fixes #12947

### CODE REVIEW

**Comment by Firecage** [comment]
MMMiracles. One more thing. You know the beach awaymission? I am pretty sure the bar walls used to be sandstone walls.

**Comment by MMMiracles** [comment]
Beach away mission already taken care of in the part 1 PR.

**Comment by WJohn** [comment]
I would like to point out that the hotel map *still* has a real, live xeno egg. Should probably get rid of that.

**Comment by Dorsisdwarf** [comment]
Someone should probbably get rid of most of the away missions imo
it's heartbreaking looking at the poorly-designed badly out of date buggy messes then considering all the work that went into your own

**Comment by Dorsisdwarf** [comment]
also @MMMiracles Is this ready to merge?

**Comment by MMMiracles** [comment]
It is.

**Pull request merged**
