### PR TITLE
lets boots with internal pockets hold station bounced radios

### PR DESCRIPTION
**Pull request by jughu**
swat.

### CODE REVIEW

**Comment by Bawhoppen** [comment]
>kevinz immediately complains how he has to powergame harder now in OOC after PR announcement

:thinking:

**Review by Cyberboss — APPROVED** [review]

**Comment by kevinz000** [comment]
@Cheridan shut the fucker down

**Comment by Cyberboss** [comment]
Pretty sure @Cheridan has denied stuff like this in the past tbh

**Comment by Cheridan** [comment]
i quit

**Comment by Cheridan** [comment]
still powercreep tho

**Comment by Iamgoofball** [comment]
@optimumtact this looks like a swat armor buff

**Comment by Bawhoppen** [comment]
It's not a SWAT buff don't you dare insult SWAT like that

**Comment by Cyberboss** [comment]
yeah let's not

**Pull request closed without merging**
