### PR TITLE
Updates posibrain.dm

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
If you're gonna ignore the "no player reference" thing at least include the guy who is responsible for the feature being ported, be nice.

### CODE REVIEW

**Comment by Metacide** [comment]
Instamerge as high priority?

**Comment by MrStonedOne** [comment]
What player references?

All I see are random letters.

**Comment by Shapsy** [comment]
Maybe just do GH

**Comment by GunHog** [comment]
I wuv u :+1:

**Comment by Cheridan** [comment]
sory no references

**Pull request closed without merging**
