### PR TITLE
[s] steven seagal sexually assaulted a ton of women so uh yeah lets not glorify him

### PR DESCRIPTION
**Pull request by Iamgoofball**
rip under siege jokes

[Changelogs]: # (Your PR should contain a detailed changelog of notable changes, titled and categorized appropriately. This includes, new features, sprites, sounds, balance changes, admin tools, map edits, removals, big refactors, config changes, hosting changes and important fixes. An example changelog has been provided below for you to edit. If you need additional help, read https://github.com/tgstation/tgstation/wiki/Changelogs)

:cl: optional name here
add: Added new things
add: Added more things
del: Removed old things
tweak: tweaked a few things
balance: rebalanced something
fix: fixed a few things
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

[why]: # (Please add a short description [two lines down] of why you think these changes would benefit the game. If you can't justify it in words, it might not be worth adding.)

### CODE REVIEW

**Comment by 81Denton** [comment]
🤔

**Comment by Armhulen** [comment]
Harsh but fair

**Comment by ExcessiveUseOfCobblestone** [comment]
abuse of [s]

**Comment by fludd12** [comment]
I didn't even know this was a reference to him. Is this being removed because of balance and you just want to say that, or is it being removed because of the reference? If the latter, just rename it, I guess. Plenty of chefs do fight scenes in television and such, to the point where it is a trope.

**Comment by Jalleo** [comment]
There isnt a suitable response in regards to the emotive responses we can easily give.

**Comment by iskyp** [comment]
if you're going to remove it because of the reference then either rename it or remove the cqc code relating to it as well

**Comment by Iamgoofball** [comment]
I'll nuke that too

I love the joke but it's in bad taste now

**Comment by optimumtact** [comment]
r/shitredditsays is that way

**Pull request closed without merging**
