### PR TITLE
NTOS and Paperwork Improvements

### PR DESCRIPTION
**Pull request by WhiteHusky**
:cl:CarlenWhite
add: Fields are supported when printing with a modular computer
add: PRINTER_FONT is now a variable
del: Removed the [logo] tag on Modular computers as the logo no longer exists
tweak: New lines on paper are parsed properly
tweak: [tab] is now four non-breaking spaces on papers
tweak: Papers have an additional proc, reload_fields, to allow fields made programmatically to be used
tweak: stripped_input stripped_multiline_input has a new argument: no_trim
fix: Modular computers no longer spew HTML when looking at a file, rather it is unescaped like it should
fix: Modular computers no longer show escaped HTML entities when editing
fix: Modular computers can now propperly read and write from external media
fix: Modular computers' file browser lists files correctly
spellcheck: NTOS File Manager had a spelling mistake; Manage instead of Manager
/:cl:
IDs being eaten by consoles should also be fixed by #23619

### CODE REVIEW

**Comment by WhiteHusky** [comment]
image
image
image

**Comment by WhiteHusky** [comment]
Piss_off_HoP.txt
dreamseeker_2017-02-02_00-09-25

**Comment by Cyberboss** [comment]
Your changelog is malformed. Add your name after the first CL, and a `/` before the second CL

**Comment by RemieRichards** [comment]
@Cyberboss name is optional, no name = PR author's username

**Comment by WhiteHusky** [comment]
Fixed the changelog. Added my BYOND CKey for credit.

**Comment by WhiteHusky** [comment]
image

**Pull request merged**
