### PR TITLE
Assembly bombs will accept more fuels and behave differently.

### PR DESCRIPTION
**Pull request by Pickle-Coding**
## About The Pull Request
Assembly bombs will accept more gasses. They are separated into fuel and oxidizers, and a bomb can not work if it doesn't have both of them. Each gas will modify the ranges of the explosion, and which temperatures and ratios would be most effective. The ranges have diminishing returns, so ridiculous sizes won't be easily obtainable, and the bomb ignores the maxcap so the explosion can have a wider variety. The explosions shouldn't be entirely better than the maxcaps, but exotic mixes could have some parts of the explosion better than the maxcap.

- [ ] Make the code not so horrible to read.
- [ ] Ensure the mixes are balanced.
- [ ] Write significantly more efficient code.

## Why It's Good For The Game
Adds more variety and depth to assembly bombs. Currently there is 0 reason to make a bomb that doesn't consist of plasma at 673.16 kelvin at the highest pressure you can achieve without leaking.

## Changelog

:cl:
expansion: Assembly bombs will work based on oxidizers and fuels. The oxidizers are oxygen, n2o, and nitryl. The fuels are plasma, hydrogen, tritium, and antinoblium.
code: Removed a bunch of redundant if checks in bomb.dm.
/:cl:

### CODE REVIEW

**Comment by Ghommie** [comment]
> 
> 
> Why is map diff bot angry?

Because there are some conflict with the master branch of your remote. You have to merge your branch with the remote master (or pull) and resolve the conflicts, which are in `code/modules/assembly/bomb.dm`. It's also good to keep the master branch of your repo updated with the remote.

**Comment by TemporalOroboros** [comment]
> Temperature now has an effect on the strength of the explosion, but it will dampen the modifiers and converge them to 0.9.

Because the strength of the explosion is dependent on the product of moles and temperature it is actually dependent on pressure now. If you keep the pressure constant and vary the moles/temperature the explosion strength remains the same.

> Antinoblium has very high devastation modifiers (could reach ranges up to high_impact range of maxcap), but no high_impact, light_impact, or flash range.

With the current modifier pure antinob can hit _double_ the current devastation range cap. It then gets capped back down, but if you wanted to remove the cap for these none of the other ranges exceed any of the other caps.

**Comment by Pickle-Coding** [comment]
> > Temperature now has an effect on the strength of the explosion, but it will dampen the modifiers and converge them to 0.9.
> 
>  Because the strength of the explosion is dependent on the product of moles and temperature it is actually dependent on pressure now. If you keep the pressure constant and vary the moles/temperature the explosion strength remains the same.

Yes. The strength stays the same, but the modifiers converge to 0.9. A high temperature bomb will leave a more generic explosion. This is to balance the fact that it would be cheaper to use high temperature bombs. A very high temperature plasma bomb will be slightly weaker than a tritium bomb, but stronger than a cool plasma bomb. A high temperature antinoblium bomb would also be slightly weaker than a tritium bomb. If you think there is a better way to balance this, let me know.

> Antinoblium has very high devastation modifiers (could reach ranges up to high_impact range of maxcap), but no high_impact, light_impact, or flash range.
> 
> With the current modifier pure antinob can hit double the current devastation range cap. It then gets capped back down, but if you wanted to remove the cap for these none of the other ranges exceed any of the other caps.

Thanks. Removed maxcap.

**Comment by Pickle-Coding** [comment]
Apparently the flash range of all bombs is 0, but I have no idea why.

**Comment by Potato-Masher** [comment]
How do these plasma singletanks compare to the ones that we currently have? How much weaker are they?

**Comment by Pickle-Coding** [comment]
> How do these plasma singletanks compare to the ones that we currently have? How much weaker are they?

68.6 moles of plasma at 373.15K will produce a 2, 3, 5 (devastation, high impact, low impact) explosion. Plasma at 673.16K at same pressure will produce a 2, 4, 7 explosion. Very high temperature plasma at same pressure will produce something like a 2, 5, 9 explosion.

Previously, 37.86 moles of plasma at 673.16K produced a 3, 5, 8 explosion.

**Comment by Pickle-Coding** [comment]
After discussion, I think this would anger maintainers so I'm not going to bother working on it anymore.

**Pull request closed without merging**
