### PR TITLE
Cleans up chasm paths

### LINKED ISSUE #30267: Chasm paths are all kinds of messed up
Originally chasms deleted things, and chasm/straight_down dropped things a z level

Now for some reason all the animation code is defined under

 /turf/open/chasm/straight_down/lava_land_surface

A lavaland only variant, with the wrong path at that because lavaland chasms delete rather than drop

Which leads to an even sillier path

 /turf/open/chasm/straight_down/lava_land_surface/normal_air

@Xhuis I guess since you added this code (I think?), I'm very confused why you put it in the place you did

### PR DESCRIPTION
**Pull request by silicons**
fixes #30267

### CODE REVIEW

**Comment by optimumtact** [comment]
you made the code worse IMO

**Comment by duncathan** [comment]
I agree with oranges

**Comment by optimumtact** [comment]
like if you have a switch var that changes the behaviour of the atom you've missed the point of object oriented design, which is that unique behaviour lives in substypes

**Comment by kevinz000** [comment]
@optimumtact https://github.com/tgstation/tgstation/issues/30267
how do i fix this

**Comment by optimumtact** [comment]
rearrange all base functionality in once class and subtype out the appropriate things into each class? it's not rocketscience.

**Pull request closed without merging**
