### PR TITLE
Syndicate Lava Base Remap

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
Okand remapped it and I tweaked a couple things codewise

Notable changes

-The syndicate ID works now

-The syndies have a camera console now

-The guns spawn in their hands so miners can't loot an empty base if no ghosts sign up

-Virology has virus food

-The exit has tiny fans

### CODE REVIEW

**Comment by GunHog** [comment]
Please make sure the viro section has a grinder!

**Comment by KorPhaeron** [comment]
https://embed.gyazo.com/ad6f839d9d44953d869a5fba9fb6cbbd.png

It does, this is more or less the base minus a couple things I moved around

**Comment by GunHog** [comment]
You removed the uranium :(

**Comment by SgtxRootbeer** [comment]
Can you add a smart fridge and a few Chem bags to the chemistry section? even evil studies might wanna mass produce stuff, like acetone, ammonia, etc.

**Comment by KingPhilipIII** [comment]
Honestly, most admins choose to meme around with the research lab and turn it into a full fledged Syndicate Colony. It's funny.

**Comment by GunHog** [comment]
Where are the self-destruct bombs????

**Comment by KorPhaeron** [comment]
I put the bombs back in, like I said that's Okand's screencap and not 100% up to date.

I'll add uranium/chem fridge/medical belt later though

**Comment by Armhulen** [comment]
can we testmerge

**Comment by XDTM** [comment]
You know, this place seems like the perfect explaination for the origin of the ops' fungal tuberculosis. Maybe there could be a sample or two of it in here.

**Comment by KingPhilipIII** [comment]
Yea. I remember reading from the disease page the fungal turberculosis is made by "Clandestine bioweapons specialists" and that basically describes this base perfectly. Although it may not be smart to let miners get their hands on it, so caution might be in order.

**Comment by KingPhilipIII** [comment]
You know what would be great? Empty humans dressed in CentComm uniforms handcuffed in the chemistry test area/Virology.

**Comment by XDTM** [comment]
Neither chemistry nor virology have significant RnD upgrades, though. They should, but they don't. I agree on the beakers.

**Comment by KingPhilipIII** [comment]
An autolathe should stay, so large beakers for grenades and grenade casings can be printed. For the casings requiring a protolathe, since they only require glass and metal can have the design disks for them on a table in chemistry or near the lathe.

**Comment by KorPhaeron** [comment]
@XDTM 

That was the inspiration for this base yeah

**Comment by Hatfish** [comment]
I don't suppose you could add a small xenobio section to the base somewhere, could you?

**Comment by KingPhilipIII** [comment]
Xenobio unfortunately requires a good deal of space to be easily used. You need numerous pens, kill chamber, computers and the equipment. With the size of the base already, xenobio would be better off in its own tutorial ruin, or we just completely rethink the idea behind this and we make tutorial SyndieStation13.

**Comment by Hatfish** [comment]
I mean, you could probably just toss a grey slime core and a box of monkey cubes into the storage room and let them build their own xenobio in that large open area near the bottom of the station.

**Comment by KingPhilipIII** [comment]
A handmade xenobio lab would be subpar to one made by map design, even with the best engineers on it. We have to remember this is a tutorial, so if someone doesn't know how to xenobio, one of the least stressful jobs, they're likely new or inexperienced with it, so I doubt they could build a lab for it either.

**Comment by XDTM** [comment]
plus you can't build xenobio consoles, as far as i know

**Comment by ChangelingRain** [comment]
You don't NEED the computers from xenobio, gosh. Scientists survived with subpar shitty equipment like extinguishers and double-windoored pens just fine.

**Comment by SgtxRootbeer** [comment]
Actually, you.could give the syndie scientists a xenobio computer and a small room labeled "xenobio lab" so they can switch camera networks and steal slimes from the station.

**Comment by KingPhilipIII** [comment]
It would be incredibly funny to watch the scientists fight as they try to figure out who stole their rainbow slime.

**Comment by GunHog** [comment]
Finally, I think of the laws they made for the Syndie AI so it couldn't pester the station. We should have an AI board that uploads the laws a Syndicate Cyborg gets.

Those are just emag laws.

**Comment by KingPhilipIII** [comment]
I know they are. But you can't emag an AI for convienent make-it-your-bitch laws.

**Comment by jughu** [comment]
>i need a memeconsole because im lazy

**Comment by MimicFaux** [comment]
At last, my colony events will grow more powerful than you can possible imagine.

**Comment by GunHog** [comment]
Reminder to put the uranium/chem fridge/medical belt in!

**Pull request merged**
