### PR TITLE
Removes MiniStation's special uplink prices

### LINKED ISSUE #20699: Ministation uplink config actually decreases telecrystal cost of weapons that promote murderboning
https://github.com/tgstation/tgstation/blob/35bfb9abb6d3e7952d14a1781c9ffc3a68d2df00/_maps/map_files/MiniStation/uplink_item.dm
Source

In ministation, the TC cost of murderboning weapons should be increased so no one runs around with weapons killing everyone. Unfortunately, the prices are outdated and actually makes the cost of the murderboning items decrease. 

**Esword**
Original: 8 TC
Ministation: 7 TC

**Revolver .357**
Original: 13 TC
Ministation: 10 Tc

**Singularity beacon** (pretty sure ministation doesn't have a sing)
Original: 14 TC
Ministation: 4 TC

**Mini Energy Crossbow**
Original: 10 TC
Ministation: 7 TC

**Syndicate minibomb grenade**
Original: 6 TC
Ministation: 6 TC (unchanged)

### PR DESCRIPTION
**Pull request by Giacom**
Fixes #20699

MiniStation has overridden uplink prices which aren't being updated or balanced, since they are now actually encouraging murderboning traitors due to the change which increases the amount of TCs you get from 10 to 20.

Removing it will cause less headaches in the future, as it'll revert to the default prices, unless anyone wants to be personally responsible for balancing the uplink prices for MiniStation, let me know and I'll close this PR for you.

### CODE REVIEW

**Comment by ma44** [comment]
This should be tweaked instead of removed.

**Comment by Giacom** [comment]
I haven't played this in a while, and don't have much time to tweak this, but I felt bad about it becoming an issue.  Like I said, if someone wants to take responsibility for it then let me know.

**Review by ma44 — CHANGES_REQUESTED** [review]
You should just delete this file as it has nothing and causes a compile error
_maps/ministation.dm:77:error: unable to open
"map_files/MiniStation/uplink_item.dm".
tgstation.mdme.dmb - 1 error, 0 warnings (9/27/16 1:17 pm)

**Comment by ma44** [comment]
Also remember to remove line 77 from the _maps/ministation.dm

**Comment by Giacom** [comment]
Thanks, forgot about the \#include.

**Comment by optimumtact** [comment]
Gia!

**Comment by Giacom** [comment]
Hi.

**Pull request merged**
