### PR TITLE
Tram malfunction adjustments

### PR DESCRIPTION
**Pull request by lessthnthree**
## About The Pull Request

Adjusts tram malfunction and the tram malfunction event to be more straightforward and similar to other telecoms machinery.

- Tram malfunction now requires engineering, borg, or AI to visit either the tram or the tram controller in telecoms to press 'reset' (previously: open the tram panel and find the appropriate tool to repair it)
- Tram malfunction event only stops the tram once per event roll
- Adjust announcement to include message that engineers need to reset the tram
- Removed loud priority_announce when the tram is fixed. Players know the tram is fixed because they are using it again
- Tram doors no longer force crush during malfunction, since engineers have no method to fix this
- EMP/communications blackout event will temporarily degrade crossing signals, otherwise the tram continues to function normally
- Loss of telecoms power will degrade crossing signals, otherwise the tram continues to function normally

Frequency of tram malfunction event is reduced to be in line with communications blackout and grav gen blackout, and a maximum of 3 occurrences per round

Signal failure:
Previously: Signals fail until reset has physically been done on the controller
New: Signal failure is moved to be part of the Communications Blackout event, lasting the duration of EMP blast that hits telecoms

Communication loss:
Previously: For the duration of the Tram Malfunction event there is a 5% chance the tram does a degraded stop, ending when the controller is repaired or the timer ends
New: A guaranteed 1 degraded stop per event roll. To balance the increase in occurrences it's been made easier to reset on the controller. If the tram is not reset by the end of the timer, it is done automatically

New telecoms room tram controller:
dreamseeker_AGHpKvyunZ

## Why It's Good For The Game

Making the tram friendlier for engineering to pick up/understand, it will function more predictably in the tram malfunction and communications blackout event.

## Changelog

:cl: LT3
add: Telecoms now has a central tram controller
add: Tram controller is now included in communications blackout event
qol: Tram malfunction event only stops tram once, requiring engineering to reset (no tools required)
qol: Tram malfunction event no longer sends a Central Command announcement when fixed
del: Tram doors no longer force crush you during tram malfunction event
del: Silicons can no longer control the tram when communication is lost
/:cl:

### CODE REVIEW

**Comment by Jackal-boop** [comment]
Engies can already reset the tram to fix it

**Comment by Blacklist897** [comment]
there is already a way to fix tram malfunction and I don't see how its related to telecoms

**Comment by Dorsisdwarf** [comment]
Doesn't this mean the rogue tram event now only lasts however many seconds it takes the AI to zoom over to tcomms and press a button? Almost every round has an AI.

**Comment by lessthnthree** [comment]
> I think the tram should be more nightmarish actually

> Doesn't this mean the rogue tram event now only lasts however many seconds it takes the AI to zoom over to tcomms and press a button? Almost every round has an AI.

It's going to increase the duration and make it more predictable depending on the component you're looking at. There's two failures that happen during the tram malfunction event:

Signal failure:
Previously: Signals fail until reset has physically been done on the controller
New: Signal failure is moved to be part of the Communications Blackout event, lasting the duration of EMP blast that hits the controller

Communication loss:
Previously: For the duration of the Tram Malfunction event there is a 5% chance the tram does a degraded stop, ending when the controller is repaired or the timer ends
New: A guaranteed 1 degraded stop per event roll. To balance the increase in occurrences it's been made easier to reset on the controller. If the tram is not repaired by the end of the timer, it is done automatically

**Pull request merged**
