### PR TITLE
Reduces the amount of lava tiles that emit light

### PR DESCRIPTION
**Pull request by LemonInTheDark**
## About The Pull Request

Ok so I found out that half our lighting sources are just lava pools This is becuase each turf has its own 5x5 square of light
This is stupid. Wastes init time.

Instead of this, lets do the space starlight style solution
So for each turf, draw a light overlay on top of it, in the shape of the lava itself.
(While we're here, let's make lava emissive so it can't get darkened by its own light)

Then, we'll draw a dark lighting mask on top of the lava turf's lighting underlay. This way we can avoid light stacking
This does mean we risk "missing" lighting that we should otherwise get, like if some very strong turf light was applied to the lava.

I think I'm generally ok with that tho, since the case is rare and 0.6 seconds of init + quartering our light source count is pretty good.

That 0.6 comes from saving 0.9 off lighting init, and losing about 0.3 to overlay shenanigins

EDIT:
It's likely more like 0.5 now since I took these numbers before I applied the light mask overlay

Before
image

After 
image

## Why It's Good For The Game

Init/cpu and memory savings

### CODE REVIEW

**Comment by tralezab** [comment]
actually a really nice color of lava now

**Comment by Imaginos16** [comment]
Hilarious

**Review by Imaginos16 — APPROVED** [review]
Sprites are obviously fine for the record.

**Comment by LemonInTheDark** [comment]
> This is pretty neat. Finding a big waste of init buried under the lighting code like this would be difficult for anyone else. Well done Lemon!

I honestly just took info from how I did space turfs, looked at how many lighting sources there were, and went from there. You don't need to hype me that much about it

**Pull request merged**
