### PR TITLE
Cyborg modules now automatically turn off when deactivated

### PR DESCRIPTION
**Pull request by ShizCalev**
:cl: ShizCalev
balance: Putting an item back into your inventory as a cyborg will now automatically turn said item off (ie welders, lighters, ect.)
fix: Cyborgs can now longer conceal unconcealable energy saws (ie ones that are activated) inside themselves. They will now turn off automatically.
/:cl:

### CODE REVIEW

**Comment by TheWiznard** [comment]
rip miner borg

**Comment by ATH1909** [comment]
In case it isn't clear (it IS the Internet, after all), TheWiznard, my thumbs up to your post is a thumbs up of agreement with you, not a thumbs up of agreeing with the mining borg nerf.

**Comment by BeeSting12** [comment]
Does this mean it's deactivated when it goes into their inventory or deactivated when it's dequipped but still in their three modules?

**Comment by Barhandar** [comment]
Yeah, mining borgs need mesons + satchel + mining tool, this fucks mining borgs over because they otherwise could keep scanner on and stored.

**Comment by ShizCalev** [comment]
Removed the pinpointer thing because it only seemed like a good idea when I was drunk as hell.

Also @BeeSting12 only when it goes into their inventory. Lemme clarify that in the changelog.

**Comment by YakumoChen** [comment]
ought to make an exception for mining scanners, at least. They're automatic for a reason, you don't see humans forced to hold the things unless they're manual.

**Comment by TheWiznard** [comment]
@YakumoChen inb4 "but cyborgs are a slave role!"

**Comment by optimumtact** [comment]
just make the scanner built into the miningborg so silicon apologists don't crap their stupid pants when they can't mine effectively

**Review by ninjanomnom — APPROVED** [review]

**Pull request merged**
