### PR TITLE
remakes the escape pod shuttle!

### PR DESCRIPTION
**Pull request by spockye**
## About The Pull Request
This PR fully remakes the Pod shuttle. What is the pod shuttle you may ask? well, the place pods go of course!
While the OLD one could only take a measly 4 pods, this new and totally tubular version can take a whopping 8!

the interior now consists of:
a docking hallway
a main room, with a bar and medbay
a garden
a bridge
two engines!

Old shuttle 
image

New shuttle
image

### Mapping March
Ckey to receive rewards: Spockye

## Why It's Good For The Game
The old pod shuttle is sadly quite old, and in my opinion, in need of a remake. This pr does exactly that! 
it also opens up the possibility for stations to have a total of 8 instead of 4 pods! (if someone ever makes a station that's large enough to deserve more than 4)
## Changelog
:cl:
add: remakes the old escape pod shuttle 
/:cl:

### CODE REVIEW

**Comment by Pumpkinoe** [comment]
really good work, looks like an actual recovery ship
mad respect

**Comment by Jacquerel** [comment]
This is an enormous improvement.
My only concern is enticing people who _haven't_ seen this PR to bother exiting that corridor into the nicer part.
Have you considered a welcoming glass door instead of the forbidding vault one? Maybe even just some windows, although I can understand in-universe why this would look like a secure airlock.

**Comment by YakumoChen** [comment]
Since when was taking a pod supposed to be a luxury offering compared to the eshuttle (and the place it lands)?

The recovery shuttle should be shitty, you think Nanotrasen pays a premium for those?

**Comment by AtomTheProphet** [comment]
> Since when was taking a pod supposed to be a luxury offering compared to the eshuttle (and the place it lands)?
> 
> The recovery shuttle should be shitty, you think Nanotrasen pays a premium for those?
> 
> It's also shaped like a dick and vagoo instead of anything remotely shuttle-like

This person just doesn't like anything nice.

**Comment by spockye** [comment]
> It's also shaped like a dick and vagoo instead of anything remotely shuttle-like

you might want to see a doctor

**Comment by YakumoChen** [comment]
> > It's also shaped like a dick and vagoo instead of anything remotely shuttle-like
> 
> you might want to see a doctor

It looks stupid
Taking the Easy Way Out shouldn't be rewarded with a fucking bar
The engines are held on with glass and rods that look like they would sooner rip off and tell the rest of the shuttle to fuck itself

**Comment by Jacquerel** [comment]
> Since when was taking a pod supposed to be a luxury offering compared to the eshuttle (and the place it lands)?

If you wanted to make a PR to make the centcomm arrival area more fun, it's Mapping March.
You may be turned town on grounds of not wanting to make centcomm more complicated, but you might not if this flies. You'd have to ask the mapping team.

**Comment by YakumoChen** [comment]
>  you wanted to make a PR to make the centcomm arrival area more fun or attractive, it's Mapping March.

I don't think either need to be particularly nice. This pod ship has better amenities than most shuttles you need to pay credits for, both with the medbay and for a shuttle with a bar. And players shouldn't be encouraged to take pods for most any reason outside the intended uses (being a coward antag, the shuttle is fucked, not near enough to the shuttle to escape)

**Comment by Jacquerel** [comment]
If you want to remake the escape pod shuttle into a hostile piece of crap, it's Mapping March. You can see which the mapping team prefer.

**Comment by LemonInTheDark** [comment]
I don't see how the quality of the map impacts how likely people are to take pods. people take pods/the shuttle for gameplay reasons, the status of the EOR map shouldn't impact that.

**Comment by san7890** [comment]
i have done nothing but take pods for the last four months (yes really) and this doesn't sway my opinion on if i should take the pod or take the shuttle - this looks like a much greater improvement over the previous iteration and am quite happy with how it turned out. good job.

**Review by san7890 — CHANGES_REQUESTED** [review]
You should definitely move all vents and scrubbers such that they aren't blocked by overlapping stuff, like chairs. They aren't functional, but it'll look better I promise.

**Review by san7890 — CHANGES_REQUESTED** [review]
image

move the ship up, it being so close to the edge gives me the heebies

image

maybe have an `/obj/structure/marker_beacon` here? looks pretty dull ingame otherwise

image

move this poster elsewhere (like on the western wall), looks really disorienting and weird with this offset here.


also in general, add a calendar or two, those are neat

**Comment by LemonInTheDark** [comment]
> image
> 
> maybe have an `/obj/structure/marker_beacon` here? looks pretty dull ingame otherwise

It should look nice with starlight, least I'd hope

**Comment by san7890** [comment]
> It should look nice with starlight, least I'd hope

it's not in a space area, it's in the ships' area so it just comes off as dark whenever you view it as a ghost. if you open the doors and let the light from the ship flow into that small bridge it looks a bit nicer.

**Comment by Zytolg** [comment]
Could you take a look at this when the lazyloading is active? I have a feeling this may be jutting into other maps on the Centcom-Z but it's become extremely difficult to tell since Lazy Loading was implemented.

**Comment by LemonInTheDark** [comment]
> > It should look nice with starlight, least I'd hope
> 
> it's not in a space area, it's in the ships' area so it just comes off as dark whenever you view it as a ghost. if you open the doors and let the light from the ship flow into that small bridge it looks a bit nicer.

it's next to a space tile right?

**Comment by san7890** [comment]
> Could you take a look at this when the lazyloading is active? I have a feeling this may be jutting into other maps on the Centcom-Z but it's become extremely difficult to tell since Lazy Loading was implemented.

that's not how lazyloading works, it loads it on the transit/reserved z-level, _not_ CentCom. it doesn't interfere with the mafia/CTF reservations though

**Comment by san7890** [comment]
> > > It should look nice with starlight, least I'd hope
> > 
> > 
> > it's not in a space area, it's in the ships' area so it just comes off as dark whenever you view it as a ghost. if you open the doors and let the light from the ship flow into that small bridge it looks a bit nicer.
> 
> it's next to a space tile right? Or am I like the guy in those england is hell memes

yeah, but it still just comes off as really dark for some reason...

**Comment by san7890** [comment]
image

also your window placements are non-symmetrical. either have double-windowed passageways on both sides or axe it from both.

**Comment by Googles-Hands** [comment]
@spockye The ships bridge should be locked behind CentCom access like the old one, no? Should I make an issue report?

**Comment by spockye** [comment]
> @spockye The ships bridge should be locked behind CentCom access like the old one, no? Should I make an issue report?

Is there a reason for the door to be access locked? If you want to, feel free though

**Pull request merged**
