### PR TITLE
Moderate de-clutter of some atmospherics stuff

### PR DESCRIPTION
**Pull request by duncathan**
Reorganized some stuff in code/ATMOSPHERICS. Really just put things where they belonged.
Removed multiple unused pipe vars and the never-called procs that used them.
Moved two pipe vars used only by h/e pipes and children thereof to h/e pipes.
Removed insulated pipes, because the only differences between them and normal pipes were the aforementioned unused vars.

Chances are I've fucked something up with the maps because of this; please let me know if I did.

### CODE REVIEW

**Comment by optimumtact** [comment]
You have changed all the line endings in these files btw, making the diff quite hard to read.
https://help.github.com/articles/dealing-with-line-endings/

**Comment by Miauw62** [comment]
@Aranclanos

**Comment by Aranclanos** [comment]
https://github.com/tgstation/-tg-station/pull/9640/files?w=1 for easier reading

**Comment by Cheridan** [comment]
You don't need to add a changelog file for something like this (in fact in this case it's probably better if you don't)

**Comment by duncathan** [comment]
I'll fix what you guys have pointed out when I get home, thanks.

**Comment by duncathan** [comment]
I actually have no idea how I fixed those merge conflicts but hey it looks good for now so I'm not complaining

**Comment by Jordie0608** [comment]
Need to run the map merger on tgstation.2.1.3.dmm

**Comment by duncathan** [comment]
this was a learning experience for sure

**Comment by Aranclanos** [comment]
👌

**Pull request closed without merging**
