### PR TITLE
[s] tgui now requires MS Edge! Welcome to the brave new webdev future!

### PR DESCRIPTION
**Pull request by neersighted**
:cl: memecoder
code: tgui now requires MS Edge! Better upgrade!
/:cl:

### CODE REVIEW

**Comment by neersighted** [comment]
Oops, I accidentally a button

**Comment by Cyberboss** [comment]
>Locking people to windows 10

'scuse me?

**Comment by nero1024** [comment]
Why not a browser that sane people use like Chrome or Firefox, or is Byond too integrated with Internet Explorer for that to be possible?

**Comment by Cyberboss** [comment]
Byond only uses whatever IE is on the system

**Comment by praisenarsie** [comment]
what is this wicked april fools joke

**Comment by neersighted** [comment]
image

I'm not sorry.

**Comment by JJRcop** [comment]
You only committed the compiled files.

**Comment by Cyberboss** [comment]
anyway, april fools memes don't need to be open

**Pull request closed without merging**
