### PR TITLE
Fixes atmos control not detecting Distro & Waste loop

### LINKED ISSUE #72243: cannot view station waste or distrobution loop
## Round ID:
[196988](https://scrubby.melonmesa.com/round/196988)

## Reproduction:
image
try to use the monitoring console

### PR DESCRIPTION
**Pull request by SyncIt21**
## About The Pull Request
Fixes #72243

just had to append `"_sensor"` to its id cause atmos_control console uses that suffix a lot

## Changelog
:cl:
fix: atmos control can detect distro & waste loop sensors
/:cl:

### CODE REVIEW

**Comment by SyncIt21** [comment]
There is something wierd going on with the GC
Screenshot (70)

**Comment by SyncIt21** [comment]
@Mothblocks just wondering maybe this was caused by #72033

**Comment by Mothblocks** [comment]
yes but also no

**Comment by Mothblocks** [comment]
its not your fault and maints already know to ignore it

**Comment by SyncIt21** [comment]
Life goes on 👍

**Comment by SyncIt21** [comment]
Any maintainer interested in reviewing & merging this? It's only 3 lines of code

**Pull request merged**
