### PR TITLE
Restaurant Customerbots now gib into robotic gibs

### PR DESCRIPTION
**Pull request by tralezab**
## About The Pull Request

Restaurant Customerbots now gib into robotic gibs

🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖🤖

## Why It's Good For The Game

Currently they explode into blood, which is forbidden lore.

## Changelog
:cl:
fix: Restaurant Customerbots now gib into robotic gibs
/:cl:

### CODE REVIEW

**Comment by LemonInTheDark** [comment]
image
He lacks critical information

**Comment by tralezab** [comment]
i made a mistake

**Comment by LemonInTheDark** [comment]
~~Please make your commit messages sane, it'd be really great if they were just the pr desc but in commit form, but a short description would do too, or hell just a meme. WHY ARE THEY FUCKING EMOJI ARMMMMMMMMMM~~

**Review by LemonInTheDark — APPROVED** [review]

**Comment by ATH1909** [comment]
> ~Please make your commit messages sane, it'd be really great if they were just the pr desc but in commit form, but a short description would do too, or hell just a meme. WHY ARE THEY FUCKING EMOJI ARMMMMMMMMMM~

sirthisisawebedit

**Comment by Fikou** [comment]
:trollface:

**Comment by Kylerace** [comment]
:trollface:

**Comment by interestingusernam3** [comment]
image

**Pull request merged**
