### PR TITLE
Spookification: Station Decorations

### PR DESCRIPTION
**Pull request by MMMiracles**
:cl: MMMiracles
add: Nanotrasen interns have taken time to decorate the various active stations to be more in line with the upcoming holiday of spooks.
/:cl:

[why]: Spooky!!!

Decorates the various main halls/departments with an assortment of pumpkins, spiders, spooky cobwebs and more.

**Changes**
- Spooky decorations across the halls/most departments
- Clothing vendors have had their prices heavily slashed so the crew can dress up
- Candy bowls at most front desks to distribute to the trick-or-treating greyshirts

### CODE REVIEW

**Review by ShizCalev — CHANGES_REQUESTED** [review]

**Comment by PKPenguin321** [comment]
is mapdiffbot dead?

**Comment by Borisvanmemes** [comment]
It died a while ago afaik.

**Comment by Cyberboss** [comment]
It'll be back eventually

@MMMiracles think you could possible tie these to halloween time somehow? maybe using the holiday system?

**Comment by MMMiracles** [comment]
@Cyberboss I was under the impression this stuff was just getting testmerged during whatever time period the halloween meme PRs were gonna get tested rather than being a toggle for yearly stuff.

**Comment by Cyberboss** [comment]
Ahh, nvm me then

**Pull request closed without merging**
