### PR TITLE
Cultist shades no longer count as cultists for the purposes of invoking runes until a minute after being released

### PR DESCRIPTION
**Pull request by Rhials**
## About The Pull Request

The following was made in response to a discussion overheard during the coderbus roundtable. 

Cult shades can no longer contribute to cultist rune invoking until they've been released from their soulstone from over a minute. If placed in a shell, they can properly invoke runes and assist you with converts/summoning as normal.

This also moves around some files/code related to cultist antag datums. Datum stuff is now in its own subfolder of the cultist folder in the antagonists module.

image

I hated testing this.
## Why It's Good For The Game

This discourages the common practice of murdering and soulstoning another player, then keeping them as a shade in their backpack used only for invoking runes. 

This is, of course, incredibly unfun for the player who has been shaded, and encourages playing singleplayer cultist instead of with your teammates as a team antagonist.

There are plenty of other ways to play singleplayer cultist. Create a summon rune, or put your shade in a shell. Carrying them around in your bag all round sucks.
## Changelog
:cl: Rhials
balance: cultist shades can no longer contribute to rune invocation until they've been out of their soulstone for a minute. Put them in a shell for God's sake!
code: sweeps up cultist antag datum code into its own subfolder.
code: cult shades now have their own antag datum.
fix: constructs now properly clear the cultist antag datum and transfer the mind slightly earlier.
/:cl:

### CODE REVIEW

**Comment by Jacquerel** [comment]
This one is coderbus ama approved

**Comment by moocowswag** [comment]
Id rather be a shade than be a juggernaut, shades themselves are very utility focused, they can safely scout with ventcrawl, they have just a high enough health pool to hit and run and they can be healed by pylons and artificers and they can quickly drag teammates away from bad combat situations or get them to a revive rune

Not letting shades be able to evocate runes just nerfs the shades and further encourages keeping them locked in a soul stone until a construct is made even though they are perfectly useful in the hands of a decent player.

**Comment by zoomachina** [comment]
How does this interact with that red rune that lets you summon ghosts?

**Comment by Rhials** [comment]
> How does this interact with that red rune that lets you summon ghosts?

It doesn't. Manifest rune cultists still function as they always have.

**Comment by MajorBugReports** [comment]
Forcing someone to give up shade after being sharded when a shade is still useful as well is bad design. Please consider better ideas in the future.

**Comment by Rhials** [comment]
> Forcing someone to give up shade after being sharded when a shade is still useful as well is bad design. Please consider better ideas in the future.

image

**Comment by carlarctg** [comment]
Instead of this change, why not make it so that shades cannot invoke runes for the first minute they're released? Stops singleplayer cheese and keeps Combat Shade alive.

**Comment by SkeletalElite** [comment]
> Instead of this change, why not make it so that shades cannot invoke runes for the first minute they're released? Stops singleplayer cheese and keeps Combat Shade alive.

Or make releasing a shade destroy the stone they're in and give roaming shades the ability to become a construct themselves by just clicking on an empty shell

**Review by L0pz — APPROVED** [review]

**Comment by ATH1909** [comment]
> Alternatively let shades free themselves from their soul stone at any time so if someone is just holding them in a bag they can just turn into a shade on their own and fuck off (maybe also combined with the ability to become a construct by clicking on a shell)

then they'd get bwoinked for sabotaging their team

**Comment by ATH1909** [comment]
are shades still able to activate (under their own power) runes that only require one cultist, such as teleport runes?

**Comment by Rhials** [comment]
> are shades still able to activate (under their own power) runes that only require one cultist, such as teleport runes?

I believe that, due to how runes calculate invokers and how this is resolved in this PR, this is still true. I’ll have to double-check.

regarding the other solutions proposed in the comments here, I don’t think any of them resolve the actual intent of this PR. It’s not about nerfing or majorly changing shades, it’s about preventing solo-cult gameplay and holding a player hostage as a means to an end.

**Comment by Rhials** [comment]
> Instead of this change, why not make it so that shades cannot invoke runes for the first minute they're released? Stops singleplayer cheese and keeps Combat Shade alive.

Actually, I like this one. I might do something along these lines.

**Comment by ATH1909** [comment]
> > Instead of this change, why not make it so that shades cannot invoke runes for the first minute they're released? Stops singleplayer cheese and keeps Combat Shade alive.
> 
> Actually, I like this one. I might do something along these lines.

you'd probably want, like, an icon (only visible by cultists) or something above the shade's head for those 60 seconds to easily indicate to fellow cultists that that shade can't help you sac yet

**Pull request merged**
