### PR TITLE
Makes the steal the plutonium core objective inform you that it is radioactive.

### PR DESCRIPTION
**Pull request by Iamgoofball**

### CODE REVIEW

**Comment by xxalpha** [comment]
Plutonium is a transuranic radioactive chemical element with symbol Pu and atomic number 94. It is an actinide metal of silvery-gray appearance that tarnishes when exposed to air, and forms a dull coating when oxidized. The element normally exhibits six allotropes and four oxidation states. It reacts with carbon, halogens, nitrogen, silicon and hydrogen. When exposed to moist air, it forms oxides and hydrides that expand the sample up to 70% in volume, which in turn flake off as a powder that is pyrophoric. It is radioactive and can accumulate in bones, which makes the handling of plutonium dangerous.

**Comment by WJohn** [comment]
A step in the right direction, but doesn't ultimately resolve the numerous problems the issue has.

**Comment by Xhuis** [comment]
just make the nuke explode when anyone gets near it
problem solved

**Comment by daman997** [comment]
how retarded does someone have to be to assume the PLUTONIUM core of a nuke is not radioactive

**Comment by Iamgoofball** [comment]
@daman997 

i said the same thing when I was seeing people complain in deadchat about dying from deconstructing the nuke unprotected

**Comment by Jalleo** [comment]
Maybe add a alarm 30-60 seconds after the core has been opened?
This would make it a harder objective

**Comment by Miauw62** [comment]
"how RETARDED does somebody have to be to not instantly understand a really unintuitive thing, amirite??????? xd"

**Comment by NSSherlock** [comment]
@daman997 
It probably should be obvious from a meta perspective (though it wasn't to me), but that's not an excuse for the in-game instructions not mentioning it.

@Jalleo
While you're at it, the vault itself should probably be harder to break into than hacking any old airlock.

**Comment by ColonicAcid** [comment]
miauw are you being dense on purpose or because it's epic

this fucking spoonfeeding is dumbfounded holy shit. if they dont have the common sense to extrapolate that  a plutonium core is FUCKING RADIOACTIVE and they didn't learn by dying to it then I don't know what to tell you buddy you should probably go play club penguin this game isn't for you.

**Comment by Miauw62** [comment]
le hugbox meme

**Comment by Cheridan** [comment]
sure

**Pull request merged**
