### PR TITLE
Trading Cards now show their rarity on their sprite

### PR DESCRIPTION
**Pull request by genessee596**
## About The Pull Request

This PR makes TCG Trading Cards show what rarity they are in the little 'N' box on the bottom. (Pictures for reference;)

image

Each rarity is tied to a certain color.
Gray -> Common
Green -> Uncommon
Blue -> Rare
Purple -> Epic
Yellow -> Legendary
(Misprints show the same rarity as their base card.)

## Why It's Good For The Game

Right now, you can't actually see what a cards rarity is without going to the github. If you want to buy/sell cards based on rarity (or just see how lucky you got), this can get super tedious. This fixes that.

## Changelog
:cl:
tweak: TCG brand trading cards now show their rarity on the card, with tiers of rarity attached to a background color on the 'N' box on the bottom right corner.
/:cl:

### CODE REVIEW

**Comment by genessee596** [comment]
Edit; I can do English now. Fixed a grammar mistake.

**Comment by MrDoomBringer** [comment]
You should just have the BG color or a border around the car be rarity tbh

**Comment by genessee596** [comment]
> You should just have the BG color or a border around the car be rarity tbh

Those are already tied to card's faction/department.

**Review by alexkar598 — APPROVED** [review]
Code looks good

**Comment by genessee596** [comment]
Fixing the merge conflict. Please hold.

**Review by Twaticus — APPROVED** [review]

**Comment by genessee596** [comment]
https://github.com/tgstation/tgstation/pull/51590

Go here

**Pull request closed without merging**
