### PR TITLE
Airlocks take small amounts of damage from Jaws of Life

### PR DESCRIPTION
**Pull request by NotRanged**
## About The Pull Request

Forcing open an airlock with the Jaws of Life tool now makes it take some damage. This leaves a small examine text, and has a chance to cause sparks. The examine text can be removed by repairing the airlock with a welder.

## Why It's Good For The Game

It gives departments a reason to go mildly >:( when people are jaws'ing their way inside - the damage makes sense considering you're forcing a struggling/resisting airlock open with a power tool. The examine cue it leaves also lets people know when someone with a power tool made their way inside.

## Changelog
:cl:
tweak: Airlocks take a small amount of damage and leave an examine hint when you Jaws of Life your way inside.
/:cl:

### CODE REVIEW

**Comment by brotherbeyondd** [comment]
Might not want to add that to the syndicate jaws of life, since they're meant to be the stealthier alternative to a door jacker for nukies.

**Comment by Fikou** [comment]
i feel like the message is unneeded, youre already gonna make examine longer with the slightly damaged text, so why this

**Comment by nightred** [comment]
You might want to cap the damage caused by the jaws of life at 25% to 50% max damage least the door be rendered useless after 12 uses of the jaws.

**Comment by NotRanged** [comment]
> You might want to cap the damage caused by the jaws of life at 25% to 50% max damage least the door be rendered useless after 12 uses of the jaws.

Disagree, 12 uses is like 2 full minutes of jaws-ing the airlock open. After 3 to 5 uses, the panel starts sparking. Airlocks can be repaired to full with only a single weld action.

**Comment by Jared-Fogle** [comment]
> It gives departments a reason to go mildly >:( when people are jaws'ing their way inside 

Why is this a good thing? If I have a reason to want to stop people from getting into my department with a jaws of life, I'm going to act anyway.

**Comment by Jeraky** [comment]
> > It gives departments a reason to go mildly >:( when people are jaws'ing their way inside
> 
> Why is this a good thing? If I have a reason to want to stop people from getting into my department with a jaws of life, I'm going to act anyway.

Agreed, all this seems to do is add another progress bar to people's (already miserable) lives. If an assistant breaks into a high-security area and steals dangerous or essential items, you don't put vault doors and reinforced walls in that area, you blame every employee that saw the assistant break in and did nothing about it, then you blame the officer that wasn't in his post, then you blame the det for not forensic scanning the airlock and catching whoever did it. And, if they're not going into a high-sec area, then i'd say they probably have a good reason to be there, i've jawed my way through medbay many times to save crit people.

**Review by SpaceManiac — CHANGES_REQUESTED** [review]
I think it makes logical sense for forcing an airlock open with the non-syndicate Jaws to damage it slightly, but it doesn't need to be a special status.

**Comment by NotRanged** [comment]
Okay, done

**Review by SpaceManiac — APPROVED** [review]
The damage number might be a little high and personally I would like to see syndicate jaws be stealthy, but this seems ok for now

**Pull request merged**
