### PR TITLE
Mime Resprites, AKA Mime Desouling

### PR DESCRIPTION
**Pull request by axietheaxolotl**
## About The Pull Request

See the tin.

mimepreview

Resprites the jumpsuit (done by @Imaginos16), Parcel Parceaux, skirt.

Also, I've changed the old sexy outfit for a new one.

image

This is also a good time to show off the new lace-up sprites I did, which you can see there.

## Why It's Good For The Game

The old mime stuff was fucking ancient. This is better.

image

## Changelog

:cl:
imageadd: New sprites for the Parcel Parceaux, base Mime mask, Mime outfit and skirt, and mime sexy outfit.
imageadd: new sprites for lace-up shoes.
code: Mimes spawn with lace-ups instead of black shoes
/:cl:

### CODE REVIEW

**Comment by thgvr** [comment]
The Soul Sucker claims another victim. Looks great.

**Comment by cacogen** [comment]
Sprite PRs should be required to provide a comparison to the sprites that they're changing. IconDiffBot's output is too small to see the differences clearly, and sprites look different in the game itself. But from what I can see there, these sprites just look like a less shaded version of the old ones. Might be better, might be worse. Can't tell. 

Oh, and you deleted the back sprite for bamboo spears.

**Comment by Serxule** [comment]
> Sprite PRs should be required to provide a comparison to the sprites that they're changing. 

^

**Comment by Serxule** [comment]
also, the sexy outfit looks more like a black and white cartoon version of mario, not at all sexy.

**Comment by axietheaxolotl** [comment]
> also, the sexy outfit looks more like a black and white cartoon version of mario, not at all sexy.

he doesn't know

**Comment by axietheaxolotl** [comment]
> Sprite PRs should be required to provide a comparison to the sprites that they're changing.

I literally showed the old sprites. Do you actually have eyes?

**Comment by Serxule** [comment]
> > also, the sexy outfit looks more like a black and white cartoon version of mario, not at all sexy.
> 
> he doesn't know

if im thinking what you mean, i do know, but it doesnt look good still.

**Comment by Serxule** [comment]
and why is the shading only on the lower torso

**Comment by Imaginos16** [comment]
> also, the sexy outfit looks more like a black and white cartoon version of mario, not at all sexy.

He doesn't know

**Comment by bluetshirtguy** [comment]
holy shit, we went from big sec milkers to porn references, the old mime suit isn't supposed to be modeled after something people busted their nut to my dude.

**Comment by JohnFulpWillard** [comment]
> > also, the sexy outfit looks more like a black and white cartoon version of mario, not at all sexy.
> 
> he doesn't know

> holy shit, we went from big sec milkers to porn references, the old mime suit isn't supposed to be modeled after something people busted their nut to my dude.

As someone who didn't know, and who didn't WANT to know, why the fuck would you do this

**Comment by Iamgoofball** [comment]
why does the mime look like mario

**Comment by axietheaxolotl** [comment]
> holy shit, we went from big sec milkers to porn references

You will NOT reference anything mature on a server meant for people over the age of 18.

**Comment by JohnFulpWillard** [comment]
> > also, the sexy outfit looks more like a black and white cartoon version of mario, not at all sexy.
> 
> he doesn't know

> holy shit, we went from big sec milkers to porn references, the old mime suit isn't supposed to be modeled after something people busted their nut to my dude.

As someone who didn't know, and who didn't WANT to know, why the fuck would you do this

> > holy shit, we went from big sec milkers to porn references
> 
> You will NOT reference anything mature on a server meant for people over the age of 18.

separation between server and codebase exists, and BYOND allows for as young as 13 to sign up.

**Comment by necromanceranne** [comment]
It's so subtle as to be a 'you know if you know' kind of reference.

If people would otherwise know of it, it would be the SFW stuff instead :P

**Comment by axietheaxolotl** [comment]
> It's so subtle as to be a 'you know if you know' kind of reference.

> If people would otherwise know of it, it would be the SFW stuff instead :P

^

**Comment by jughu** [comment]
Dont turn the mime into a mickey mouse ass looking

**Comment by bluetshirtguy** [comment]
> > holy shit, we went from big sec milkers to porn references
> 
> You will NOT reference anything mature on a server meant for people over the age of 18.

Fetish content for a server banning that nonsense

**Comment by SomeDongus** [comment]
Why did you use a female character to model the jumpsuit sprites, I want to know what it looks like without boobs.

**Comment by Sealed101** [comment]
livrah nerf

**Comment by Livrah** [comment]
Just PR for downstreams you are playing on already.

**Comment by RaveRadbury** [comment]
Could we not base entertainer costumes on porn, please.

**Comment by Coastfront** [comment]
Ah yes, Zorn mime. 
I get this is an 18+ server but do we infact have to tie a mime costume to porn.

We already have enough low quality porn from things that aren't even porn based you're just giving the library more material.

**Comment by axietheaxolotl** [comment]
> Just PR for downstreams you are playing on already.

No. :)

**Comment by Serxule** [comment]
> > holy shit, we went from big sec milkers to porn references
> 
> You will NOT reference anything mature on a server meant for people over the age of 18.

we arent an erp server, there is literally no reason to have everything be sexual, in fact it should be the opposite.

**Comment by necromanceranne** [comment]
It's a cute outfit who cares what it's from.

**Comment by capsaicinz** [comment]
all this seething about a vague reference to mime funnies truly proves the degeneracy of tg. they don't got their damn boobahs out and the primary way people are gonna find out if anything is by you yaps sputtering about it.

looks based and very desouled.

**Comment by Serxule** [comment]
|PROBLEMS WITH THE SPRITES|
1: the sexy mime costume is literally a porn outfit, its not a vague reference or funny meme, (and considering they gave security huge fucking tits, its reasonable to say they're purposefully trying to sexualize shit in tg, "hurr durr but serxule tg is 18+" we arent a fucking erp server, and dont try to pass it off as "ohhh funny tiddy sex porn haha"). 2: it looks shit anyways, like a black and white mario outfit, barely resembles a mime. 3: the normal sprites look like shit due to being half shaded for some reason, was the budget cut halfway through making it?
(can you tell im sick of this shit?)

**Comment by jughu** [comment]
Skyrat downstream strikes again

**Comment by Donpedrito** [comment]
I'm _really_ not a fan of those types of references being added to the game, this is the type of stuff that people will overuse specifically because they know it makes other players uncomfortable, like what used to happen with WGW and accusing people of ERP. I don't buy the argument of "people won't get the reference" or "they're in other animations too" when it's in the context of an outfit _literally_ called the sexy mime outfit.

I think the other outfits and the backpack look nice, though.

**Comment by tralezab** [comment]
> |PROBLEMS WITH THE SPRITES| 2: it looks shit anyways

just a reminder that this is its competition
image

**Comment by magatsuchi** [comment]
its a reference to an animated porn video that most people haven't even seen. better yet, its even less sexual in presentation than the current sexy mime outfit.

why do you guys have to get so angry over an 18+ reference in an 18+ game? i fail to understand

**Comment by Serxule** [comment]
> > |PROBLEMS WITH THE SPRITES| 2: it looks shit anyways
> 
> just a reminder that this is its competition image

it looks like a mime outfit, the new one doesnt, im not talking about the quality of it.

**Comment by magatsuchi** [comment]
> it looks like a mime outfit
> the new one doesnt

you HAVE to be trolling

**Comment by Serxule** [comment]
> its a reference to an animated porn video that most people haven't even seen. better yet, its even less sexual in presentation than the current sexy mime outfit.
> 
> why do you guys have to get so angry over an 18+ reference in an 18+ game? i fail to understand

refer to: "hurr durr but serxule tg is 18+" we arent a fucking erp server, and dont try to pass it off as "ohhh funny tiddy sex porn haha"
and: "I don't buy the argument of "people won't get the reference" or "they're in other animations too" when it's in the context of an outfit literally called the sexy mime outfit."

**Comment by magatsuchi** [comment]
> refer to: "hurr durr but serxule tg is 18+" we arent a fucking erp server, and dont try to pass it off as "ohhh funny tiddy sex porn haha" and: "I don't buy the argument of "people won't get the reference" or "they're in other animations too" when it's in the context of an outfit literally called the sexy mime outfit."

my bad, i didn't realize that "reference to something 18+" is erp, i'll be more cautious next time.

please don't use the word "fuck" IC anymore by the way, it has sexual connotations

**Comment by Serxule** [comment]
> my bad, i didn't realize that "reference to something 18+" is erp, i'll be more cautious next time.
> 
> please don't use the word "fuck" IC anymore by the way, it has sexual connotations

"you have to be trolling" you say, yet you are the one acting like an idiot

**Comment by Coastfront** [comment]
> its a reference to an animated porn video that most people haven't even seen. better yet, its even less sexual in presentation than the current sexy mime outfit.
> 
> why do you guys have to get so angry over an 18+ reference in an 18+ game? i fail to understand

because if a reference is funny then its good.
If its a reference to porn because "guys look its porn".
The sexy mime outfit isnt good either and the only reason people dont have a stroke over that-one is because it looks like shit and people use it to shitpost.
The new replacement sexy mime outfit is neither overtly ugly enough to be good enough to shitpost with, while also literally being A FUCKING PORN VIDEO REFERENCE.
The literal only funny part about it is outrage humor from people n o t wanting to literally have a thing, that is entirely modeled after, and therefore would effectively only exist because "haha porn"
even I, someone who did things for the sake of outrage humor, can see why people dont like it, and i already am not funny.

**Comment by Serxule** [comment]
> > it looks like a mime outfit
> > the new one doesnt
> 
> you HAVE to be trolling

and like i already said (as you seem to have not read anything i wrote) it looks like a black and white mario outfit, but with a few stripes.

**Comment by magatsuchi** [comment]
> and like i already said (as you seem to have not read anything i wrote) it looks like a black and white mario outfit, but with a few stripes.

dae suspenders = mario?

**Comment by 81Denton** [comment]
image

I've been trying to come up with constructive criticism for this without any success - this looks like hot shit and the reason to PR this being "hehe it's an obscure porn reference you wouldn't get it" isn't helping.

**Comment by magatsuchi** [comment]
> image
> 
> I've been trying to come up with constructive criticism for this without any success - this looks like hot shit and the reason to PR this being "hehe it's an obscure porn reference you wouldn't get it" isn't helping.

that's the old outfit not the PR one

**Comment by Donpedrito** [comment]
I forgot to mention, does this also add a black beret the mime can start with, or did you specifically choose a hat that isn't actually in the mime's wardrobe in order to make the porn reference more accurate?

**Comment by 81Denton** [comment]
> > image
> > I've been trying to come up with constructive criticism for this without any success - this looks like hot shit and the reason to PR this being "hehe it's an obscure porn reference you wouldn't get it" isn't helping.
> 
> that's the old outfit not the PR one

Ok I'm gonna dip before I embarass myself any further than that

**Comment by Serxule** [comment]
> > and like i already said (as you seem to have not read anything i wrote) it looks like a black and white mario outfit, but with a few stripes.
> 
> dae suspenders = mario?

imageedit_2_8145639036

**Comment by magatsuchi** [comment]
> > > and like i already said (as you seem to have not read anything i wrote) it looks like a black and white mario outfit, but with a few stripes.
> > 
> > 
> > dae suspenders = mario?
> 
> imageedit_2_8145639036

please delete i do not want sexual content on my git

**Comment by Coastfront** [comment]
image
Old sexy mime outfit:
Looks bad, Is a "sexy" outfit that looks like what you'd expect a deviant art oc to dress like.
Thats why its funny when people gimmick with it. The fact its ugly and looks like someones desperate attempt to have erp in the game, but not being good enough to make it look nice. It looking like shit is what stops it from being annoying imo.

image
as far as im aware, thats the new one. The only comedic value this has, is if someone gets the porn reference, And that is literally just comedic value that exists of "why is there a porn reference in the game?" and stops being funny after that. For everyone else, This looks very non-destinct, less "funny" to gimmick with because of that, and looks less obnoxious. which is almost the reason why the old outfit is funnier to wear.  People literally might not even register that its a different fucking outfit at a glance.

**Comment by tralezab** [comment]
if the best thing you can say about the old sprite was "it's so ugly people have fun with it" then maybe it isn't better than the new one

**Comment by Coastfront** [comment]
> if the best thing you can say about the old sprite was "it's so ugly people have fun with it" then maybe it isn't better than the new one

Okay whats the best thing you can say about the new one.
"Its a porn outfit so its funny for the first time you see it if you get the reference"?

**Comment by optimumtact** [comment]
JESUS H CHRIST PEOPLE, IF YOU HAVE SOME THING TO SAY ABOUT THE QUALITY OF THE SPRITE PLEASE SAY IT, I COULDN'T GIVE A  FLYING FUCK WHAT THEY BASED THE REFERENCE ON, SEXUAL OR NOT, DOES THE SPRITE LOOK BETTER THAN THE OLD ONE IS THE ONLY QUALIFYING CRITIERA THAT MATTERS.

**Comment by SomeDongus** [comment]
1984

**Comment by optimumtact** [comment]
I'm going to smack your nuts one thousand nine hundred and eighty four times

**Comment by RaveRadbury** [comment]
As a sprite without any other context it looks great.

As an outfit that's meant to be a performer costume with sex appeal it doesn't work except for those who already know the reference.

The current outfit could pass as burlesque or something like it, the new outfit doesn't have any of the same implications.

**Comment by VladinXXV** [comment]
I'll admit the new sexy outfit is a pretty funny reference. However, I gotta agree with Rave here, without knowing the reference there's nothing really "sexy" about it. The overalls do look a little silly and characters like Mickey Mouse or Mario do somewhat come to mind. As far as I can tell from the IconDiff bot, the gloves and bandana aren't included anywhere in this, yet I don't think you're wearing everyday red gloves or a normal red bandana. Not sure what's going on there, maybe I'm just missing something.

As for the other sprites, I actually like what's been done with the Parcel Parceaux, the straps are much more out of the way now. (though contribute to a different issue I mention later) You mention something in your changelog about changing the mask, but I can't find any changes made to it. Was this in error?

The alt sprites haven't been touched, I feel like it'd be good to change those what little you can to match the new sprites, lest pulling your shirt down suddenly make your skirt solid black.

As for the bread and butter of the PR - the main uniform and the skirt... well, the new sprites aren't terrible, but I don't have it in me to denounce the originals. They look significantly worse in the provided image due to the new straps on the Parcel Parceaux making it look like the entire top shoulder area of the uniform is black. Looking at the uniform alone is preferrable.

**Comment by optimumtact** [comment]
> As a sprite without any other context it looks great.
> 
> As an outfit that's meant to be a performer costume with sex appeal it doesn't work except for those who already know the reference.

Dude on what planet are you living on, there is absolutely no basis for having that costume other than as a meme, so replacing it with a seperate meme is completely valid so again, all that matters is what sprite looks better.

Do you have some kind of personal attachement to the other sprite?

**Review by Twaticus — CHANGES_REQUESTED** [review]
looks good waiting on alt sprites

**Comment by RaveRadbury** [comment]
> > As a sprite without any other context it looks great.
> > 
> > As an outfit that's meant to be a performer costume with sex appeal it doesn't work except for those who already know the reference.
> 
> Dude on what planet are you living on, there is absolutely no basis for having that costume other than as a meme, so replacing it with a seperate meme is completely valid so again, all that matters is what sprite looks better.
> 
> Do you have some kind of personal attachement to the other sprite?

No I just really don't like the new one.

The meme of the old one is akin to Halloween costumes being like "sexy nurse" etc, right?

This new one isn't like that, and it's not even a meme. It's just a reference, and not a common one.

**Comment by cacogen** [comment]
i like these (:

**Comment by Kurgis** [comment]
> The current outfit could pass as burlesque or something like it, -

Passes off as Cruella Deville.

**Comment by JinGiant** [comment]
False advertising, red gloves and pulled down bandanas do NOT exist

**Comment by necromanceranne** [comment]
> False advertising, red gloves and pulled down bandanas do NOT exist

Alt click the bandanna to make it into a neckerchief. Red gloves can be made by dying your white gloves in a washing machine along with a red crayon.

**Comment by JinGiant** [comment]
> Alt click the bandanna to make it into a neckerchief. Red gloves can be made by dying your white gloves in a washing machine along with a red crayon.

I didn't know you could alt click them. I was taking the rgb value of the gloves in photoshop and spray painting them too, thank you very much. Now I can finally be a proper mime.

**Pull request merged**
