### PR TITLE
Turns TRAIT_NOCLONE into TRAIT_BADDNA for consistency

### PR DESCRIPTION
**Pull request by XDTM**
:cl: XDTM
balance: DNA-damaging methods (changeling draining, mainly) no longer prevent alternative revival methods, but can no longer be circumvented by upgrading DNA scanners.
balance: Any source of husking now prevents cloning on unupgraded cloning scanners, instead of only husking caused by changelings.
balance: Husking now fully prevents revival from several non-cloning methods, including defibrillation, surgery, and strange reagent.
/:cl:

Why? Consistency! Also, the removal of prescanning/autocloning really simplifies this.

Changeling draining effectively prevents cloning until you transfer the brain to an intact body.

### CODE REVIEW

**Comment by Time-Green** [comment]
I do like the frankensteining this will cause doctors to resort to

**Comment by XDTM** [comment]
Further ideas:
- Extensive cellular/genetic damage causes BADDNA
- Excessive radiation damage causes BADDNA
- Acid damage can cause husking

Out of scope or acceptable?

**Comment by coiax** [comment]
Trait naming is inconsistent, but I feel it would be more readable at a glance if it was TRAIT_BAD_DNA.

I initially read it as TRAIT_BAD NYA~

**Comment by Tlaltecuhtli** [comment]
i dont think ling having a round removal with no counters is good

**Comment by Time-Green** [comment]
Revival surgery, brain transfer, strange reagent etc

**Comment by XDTM** [comment]
Only brain transfer works, but it's a simple procedure if you have surgical tools and a spare body

**Comment by anconfuzedrock** [comment]
Tlat plat blat splat, there are plenty of round removal ways already to the point that absorbing is _slow_ (shield gens, anyone?) and it doesn’t sound like it fucks the brains up.

**Comment by Time-Green** [comment]
Could you just remove the brain and clone that?

**Comment by XDTM** [comment]
no due to the NOCLONE trait being inherited

**Comment by Tlaltecuhtli** [comment]
wait nvm i read as husk cant be  cloned with t4

**Comment by optimumtact** [comment]
Conflicts (XDTM) you hav ea few like this

**Comment by optimumtact** [comment]
sorry I fucked you over by merging the prescanning for deados

**Comment by ExcessiveUseOfCobblestone** [comment]
Wasn't that the whole point of the upgraded cloning? To revive the changeling-sucked?

**Pull request merged**
