### PR TITLE
adds a 20 character limit to book titles

### LINKED ISSUE #17997: Book titles don't have a character limit
This allows a lot of chatlog griefing.

### PR DESCRIPTION
**Pull request by swankcookie**
fixes #17997

### CODE REVIEW

**Comment by PKPenguin321** [comment]
Fun removal

**Comment by MMMiracles** [comment]
that means titles ca

**Comment by swankcookie** [comment]
i don't care how long the tit

**Comment by swankcookie** [comment]
le is, just that it cant be li

**Comment by swankcookie** [comment]
ke 100 characters lo

**Comment by swankcookie** [comment]
ng

**Comment by Cheridan** [comment]
20 does seem a little low. What's the define for human name length limit?

**Comment by pudl** [comment]
What if i want to upload the entirety of Colorless Tsukuru Tazaki and His Years of Pilgrimage

**Comment by Jordie0608** [comment]
Make it 79 characters ( ͡° ͜ʖ ͡°)

**Comment by optimumtact** [comment]
This seems high priority and I have a quota to meet

**Comment by KorPhaeron** [comment]
20 is kinda low though

**Comment by Chocobro** [comment]
20 is excruciatingly low
if you're planning on uploading Chuck Tingle's "Pounded In The Butt By My Book Pounded In The Butt By My Book Pounded In The Butt By My Own Butt" you'll only ever get to "Pounded In The Butt "
yes, with that space at the end

(shoutouts to u tingle)

**Comment by Chocobro** [comment]
HE MADE ANOTHER SEQUEL
https://www.amazon.co.uk/Pounded-Butt-My-Book-Own-ebook/dp/B01FDZJHGO?ie=UTF8&ref_=asap_bc

**Comment by swankcookie** [comment]
any specific suggestions?

**Comment by optimumtact** [comment]
No swank, they can raise it themselves if it's that annoying

**Comment by swankcookie** [comment]
:+1:

**Pull request merged**
