### PR TITLE
Adds a new drink. The Hivemind eraser.

### PR DESCRIPTION
**Pull request by itseasytosee**
## About The Pull Request
Adds a new drink in memorialization of my favorite removed gamemode
image
Neat animated sprite
Based loosely on https://www.liquor.com/recipes/mind-eraser/
If you have suggestions for benign secondary effects I would love to hear them.

## Why It's Good For The Game
It made me sad knowing that hivemind was completely removed from the code with no memorial.
A toast to hivemind and to Kierany9
## Changelog
:cl:
add: New drink! The Hivemind eraser. Can be made with two parts black Russian one part thirteen-loko and one part grenadine.
/:cl:

### CODE REVIEW

**Comment by kriskog** [comment]
Not even /datum/reagent/consumable/ethanol/skoglol smh

**Comment by bluetshirtguy** [comment]
Benign? how about replaced I's and me with we and us? stuff like that.

**Comment by JJRcop** [comment]
Miniscule chance to trigger queen death effect in hivenode organs.

**Comment by PKPenguin321** [comment]
lol I forgot hivemind existed

**Comment by evilcyborgmrt** [comment]
Make it erase chunks of your chat log

**Comment by HomocidlePancakes** [comment]
“Hivemind Eraser” sounds bad. Remove the eraser part.

**Comment by Tlaltecuhtli** [comment]
make it give you the pink glow to trigger flashbacks

**Comment by Pugie** [comment]
Make initropidril a required ingredient and have the drink cause instant heart attack.

**Comment by ATH1909** [comment]
https://www.youtube.com/watch?v=f9O2Rjn1azc

**Comment by itseasytosee** [comment]
@HomocidlePancakes No pun in that

**Comment by Grazyn** [comment]
With a name like that I expected it to drop you out of any hivemind chat you're currently part of (ayys, xenos, golems, changeling etc.), it would be pretty cool but I supposed it would require exotic ingredients

**Comment by ExcessiveUseOfCobblestone** [comment]
now we need a HoG and CC drink

**Comment by itseasytosee** [comment]
Hand of god has the chap item and rat has a whole lavaland ruin and other brass items.

**Comment by bobbahbrown** [comment]
@itseasytosee Sorry to ping you here, but you won a prize in our community coding raffle for February. If you have discord, can you contact me? bobbahbrown#0001

[Or you could contact me through the forums.](https://tgstation13.org/phpBB/viewtopic.php?f=5&t=25418)

**Comment by itseasytosee** [comment]
@bobbahbrown Sure my discord is Welder#2424 I sent a friend request as I could not find you on the Tg discord

**Pull request merged**
