### PR TITLE
Ports the Ore Redemption machine to TGUI

### PR DESCRIPTION
**Pull request by Expletive**
:cl:
add: The Ore Redemption machine has been ported to TGUI. New features include the addition of "Release All" and "Smelt All" buttons.
/:cl:

Everything needs to be ported to TGUI, right? This one seemed simple enough, but it took me a while to make it stop crashing the entire server. Now it should be fine though. 

orm
orm2

### CODE REVIEW

**Comment by Bawhoppen** [comment]
the reason we don't port everything to tgui is because it can lag or something

**Comment by GunHog** [comment]
Nice!

**Comment by Expletive** [comment]
Oh. tgui.js is conflicting, and I'm not entirely sure how to fix that. But wouldn't it just involve adding changes and then recompiling tgui?

**Comment by GunHog** [comment]
Revert your changes to tgui.js, merge with latest master, compile again. Or you could just merge it with master, resolve conflicts automatically (using 'theirs' or 'mine'), and compile TGUI again. It really does not matter as long as nothing else conflicts, as the .js is made when you compile TGUI.

**Pull request closed without merging**
