### PR TITLE
Return 2 fighter to caravan ambush

### PR DESCRIPTION
**Pull request by Dennok**
## About The Pull Request
Return 2 fighter to caravan ambush that be lost in #37474

## Changelog
:cl:
add: Return 2 fighter to caravan ambush.
/:cl:

### CODE REVIEW

**Comment by Jordie0608** [comment]
This was intentionally removed ref https://github.com/tgstation/tgstation/pull/39182#issuecomment-405882121 and I'm not sure the issue behind it has been addressed, @ninjanomnom do you know?

**Comment by ninjanomnom** [comment]
It hasn't been resolved and I'm still not really sure the best way to go about fixing it

**Comment by Dennok** [comment]
Are you talking about the full identity of the camera and the door button, codes?
Yes i check it now and it share control. Make 2 template with changed camera and door button codes or make it change on load?
About unability of use 2 shuttles in one time i fix it in #45024

**Comment by WJohn** [comment]
Yeah the shared buttons and cameras are the problem.

**Comment by Dennok** [comment]
Just need to add in `link` proc to camera and door, changing it codes.

**Comment by Dennok** [comment]
scrnshot1
Now it works separately.

**Comment by Dennok** [comment]
i merge it to #45024

**Pull request closed without merging**
