### PR TITLE
Removes lizards from roundstart

### PR DESCRIPTION
**Pull request by Iamgoofball**
lizards attract creepy ERPers, and all interactions is just a variation on "race war gas liggers" in the end

### CODE REVIEW

**Comment by GunHog** [comment]
No. :-1: Stop removing things just because you do not like them.

**Comment by Iamgoofball** [comment]
i'd argue that it's more than me that dislikes them

if this doesn't go through I have another PR planned with a replacement for lizard that's superior and I can argue is actually /tg/ culture unlike furries

**Comment by Jordie0608** [comment]
Isn't this a config

**Comment by Iamgoofball** [comment]
the config disables lizards existing entirely, this makes them just not a round-start thing

**Comment by Incoming5643** [comment]
The config.mutant_races only changes if in game stuff acknowledges species and allows any race with roundstart = 1 to be chosen at round start. It doesn't remove lizards from existing any more than skeletons or slime people.

The only race with roundstart = 1 are lizards, so doing this is effectively the same thing as disabling the config option.

**Comment by Shapsy** [comment]
Who cares :-1:

**Comment by PKPenguin321** [comment]
yeah i'm pretty much okay with this

**Comment by SconesC** [comment]
YOU can SAVE TGSTATION, today, by EXPRESSING APPROVAL for this PR.

**Comment by Iamgoofball** [comment]
@Incoming5643 I want to leave them as admin meme time shit as a compromise tho

**Comment by Incoming5643** [comment]
I am vaguely neutral on this but I just want to say that removing config options that servers that run our code actually use is kind of a dick move.

**Comment by SweaterKittens** [comment]
Honestly, I feel as though a lot of the players who play Lizard-people are doing it ironically, and it makes the whole thing feel like a joke. However, there are more than a couple of good lizard players out there, and I'd hate for them to get snubbed because of the shitty, vocal portion of lizard players. I'm not against having them removed, but I also don't play a lizard,, so I'm a bit biased. I'd rather a compromise that discourages people playing them ironically or "for the memes" and encourages the people who play them for the unique experience of playing a nonhuman race.

**Comment by GunHog** [comment]
That is right, this is a CONFIG OPTION. So this PR is not needed at all, and is a disservice to all server admins who draw from this code.

**Comment by Iamgoofball** [comment]
@Incoming5643 it's a one line change, they can easily make it locally.

@sweaterkittens I never see these "good lizard players", all I see are people with dumb meme names and greytiding/doing dumb shit and using being a lizard to get people to attack them/deny them services and goods so they can escalate and greytide with it

@gunhog no changes will be made if we have to go through configs

**Comment by Incoming5643** [comment]
I don't see why people would think that someone who was looking to be a shitty player would suddenly stop being a shitty player just because they had to be human.

**Comment by Zilenan91** [comment]
For what purpose? 

Also goofball, if players are being creepy and weird, you can always just get an admin to tell them to knock that shit off. Even if they weren't lizards they'd do the exact same thing, and as it stands, I feel the only purpose of this pr is to piss people off.

**Comment by Iamgoofball** [comment]
@zilenan91 they can just defend it with "its ironic i swear!!1!" and win every time, if bugging admins worked this PR wouldn't be needed

the point of the PR is to remove cancerous mass from the codebase

@Incoming5643 this eliminates one of their excuses for being a shitty player that they try to hide behind

**Comment by Zilenan91** [comment]
Goofball this is literally grudgecoding. If they're being creepy tell them to knock that shit off instead of coding them out of the game.

**Comment by freerealestate** [comment]
in case of ad homs: i don't play a lizard and i never have because i dunno it's weird

but that doesn't mean i think they should be removed just because other people enjoy them and i don't

that mentality is worthy of /v/, and 2010 /v/ at that

Fig-1; the classic me-eem

(courtesy of MemeCentre)

**Comment by Iamgoofball** [comment]
i'm keeping this pull request open until i get some input from maintainers and headcoders

**Comment by Iamgoofball** [comment]
@zilean91 if telling them to knock that shit off worked this PR wouldn't be a thing

**Comment by Zilenan91** [comment]
Then talk to the player in question. There are better alternatives than ruining everything for everyone.

**Comment by WJohn** [comment]
Yeah no, I'm not in favor of this PR. While lizards are a boring super-generic species that is played by all the master memesters, I don't think it's ever a good idea to remove something on the basis of "I don't like it". If people are being creepy or weird, first off what are you doing playing SS13??? Second, get an admin to look into these edge cases, because that's all they are.

**Comment by freerealestate** [comment]
>maintainers and headcoders

why do they matter in this instance? it's not a code issue, it's a server issue. you should be running a poll.

**Comment by Fox-McCloud** [comment]
:-1: 

What's so bad about some players liking a different character experience than just human? If they're weird/creepy with it, that's its own special issue *that will occur regardless of if lizards exist or not*.

**Comment by Iamgoofball** [comment]
@freerealestate seeing as this is a pull request on the codebase this is indeed a code issue

**Comment by Iamgoofball** [comment]
@Fox-McCloud if they lose "but i'm a lizard" as a line of defense for being creepy and weird it's easier to get rid of them

**Comment by TechnoAlchemisto** [comment]
maybe there should be some sort of public poll about this instead of operating off the assumption that the majority of players would think lizards should be removed? 

instead of just assuming that your perceived notion of what the community wants is correct

**Comment by Iamgoofball** [comment]
i've said that more people than me want it gone

i haven't said the majority anywhere in this PR

**Comment by Steelpoint** [comment]
This is a server issue, not a code issue.

**Comment by CPTANT** [comment]
:-1: 

Who the fuck am I going to gas as Asimov AI when you remove the liggers?

**Comment by freerealestate** [comment]
>seeing as this is a pull request on the codebase this is indeed a code issue

it's not a bug fix, it's not an issue of how well the code runs, it's not a matter of balance, etc.

it's you trying to remove something you don't like based on your experience with it on the /tg/ servers

so the headcoders' and maintainers' opinions don't have any more expertise than the average player's in this instance

**Comment by Miauw62** [comment]
:+1:

**Comment by optimumtact** [comment]
The only reason I can think of for you making this pr is you don't think you have the numbers to push through a policy change on the server.

**Comment by Aranclanos** [comment]
this is a server config

**Pull request closed without merging**
