### PR TITLE
Heat pipes

### PR DESCRIPTION
**Pull request by Ghilker**
## About The Pull Request
The PR adds a system where heat can be safely and quickly moved around by using heat pipes and their devices.

Still a work in progress but is already in a local testable state, with the RPD you can place the heat pipes and the heat radiator (no logic on the placement yet). 
For now only the thermomachine has been reworked to use these pipes as a mean to move the heat around instead of using two ports
The pipes are autoconnecting and from all four sides
More machines and devices will come, if you have suggestions please leave them in the comments.

Thanks to @Time-Green for the plumbing code that i used and modified to make these pipes work

## Why It's Good For The Game
Better system to handle heat other than gases
This adds tools for people to be able to handle heat in an easier way. Atmos players will be able to manage thermomachines and the waste loop in a quicker and more interesting way instead of moving the heat around by using a gas system that is prone to clog. Other players will also be able to use this system, like engineers and scientists. 
In the end heat movements will be easier to control and much faster to deliver too. Thermomachines will also greatly benefit this as they'll go to use only one port (new players will have a much easier time to understand them) and they'll have a built in 500 heat capacity reservoir to handle low amounts of energy even if not connected to anything.

## Changelog

:cl:
add: Add heat pipe system (better CL will come when the PR is finished)
/:cl:

### CODE REVIEW

**Comment by Capsandi** [comment]
What would heat pipes accomplish which you cant already do with gas piping?
If the answer amounts to "because its easier to use" then I would look at simplifying gas temperature handling before adding a system to bypass it.
Thermo-machines are in a tricky spot right now what with being static machines alongside the quickly reconfigurable pipes but that would be better solved by adding an ability to easily package it into a held item with which you could redeploy it with.
And if confusion surrounding current heat handling methods is an issue, add tool tips to the rpd explaining the purpose of each gate/pump

**Comment by Ghilker** [comment]
> What would heat pipes accomplish which you cant already do with gas piping? If the answer amounts to "because its easier to use" then I would look at simplifying gas temperature handling before adding a system to bypass it. 

They are easier to use and they can handle far higher energy amounts much better than the gases could ever do, remember gas components will clog, those will not. 

> Thermo-machines are in a tricky spot right now what with being static machines alongside the quickly reconfigurable pipes but that would be better solved by adding an ability to easily package it into a held item with which you could redeploy it with. 

They can already be moved, just unhancor them

> And if confusion surrounding current heat handling methods is an issue, add tool tips to the rpd explaining the purpose of each gate/pump

There is a pr for that already

**Comment by LemonInTheDark** [comment]
I'm honestly not on board. I like people using gas for cooling. I think it lends some purpose to heat capacity, and I don't really like the prospect of adding "pipes but slightly different". Thermomachines aside, this seems a bit weird

**Comment by Ghilker** [comment]
I disagree cause moving heat with gases is pain but if you aren't willing to merge this there is no reason to keep it open

**Pull request closed without merging**
