### PR TITLE
Maybe fixes minds failing to GC?

### PR DESCRIPTION
**Pull request by Cyberboss**
I mean, they are referenced a lot so idk fam.

### CODE REVIEW

**Comment by AnturK** [comment]
Aren't mind meant to stay around for bookkeeping purposes ? Does anything actually qdel them directly ?

**Comment by Cyberboss** [comment]
They are qdel'd when people hit Observe

**Comment by RemieRichards** [comment]
@Cyberboss that's not true?

**Comment by Cyberboss** [comment]
https://github.com/tgstation/tgstation/blob/master/code/modules/mob/new_player/new_player.dm#L142

**Comment by RemieRichards** [comment]
Yes, congratulations, keep up with the conversation.

**Comment by Cyberboss** [comment]
Email replies don't show edits

**Comment by Cyberboss** [comment]
Also in regards to new_players needing minds, they don't but who wants to touch spawning code again? Not this guy.

**Pull request merged**
