### PR TITLE
Adds two wires to armory windows [Metastation]

### LINKED ISSUE #28972: Missing cables on metastation armory windows
^ Highlighted by the blue rectangle, there are no cables there to stop people from breaking in.

### PR DESCRIPTION
**Pull request by loqoman**
:cl: loqoman

tweak: Added two wires to Armory windows [Metastation]

/:cl:

Fixes #28972

### CODE REVIEW

**Comment by WJohn** [comment]
you forgot the map merger

**Comment by RandomMarine** [comment]
Please note that it's metastation in the changelog.

**Comment by loqoman** [comment]
@WJohn map merger?

**Comment by loqoman** [comment]
@WJohn Alright, how is that?

**Comment by WJohn** [comment]
still got 150,000 lines.

Here are the steps:

1. Use Prepare map tool.
2. Edit your map.
3. Use the TGM map merger.
4. Commit+push.

Since you've already commited a changed map, you'd have to get an earlier un-edited version of the map, then start from that. Or just make a new PR doing the above.

**Comment by loqoman** [comment]
@WJohn  Alright thanks, I'll probabbly end up making a new PR.

**Pull request closed without merging**
