### PR TITLE
Fixes runtime from cyber implants

### PR DESCRIPTION
**Pull request by Diamond-74**
## About The Pull Request

Adds an unregister signal that was missing 
## Why It's Good For The Game

Runtimes from changing implant bad.
## Changelog
:cl:
fix: Fixes runtime from augments not unregistering a signal.
/:cl:

### CODE REVIEW

**Review by MrMelbert — CHANGES_REQUESTED** [review]
In most cases setting `override = TRUE` is actually paving over a bug (that being it's not properly unregistering all signals)

In this case it seems to register `list(COMSIG_ITEM_ATTACK_SELF, COMSIG_ITEM_ATTACK_SELF_SECONDARY)` but only unregister `COMSIG_ITEM_ATTACK_SELF`. Perhaps try patching that first to see if it gets rid of the signal override runtimes

**Comment by Diamond-74** [comment]
Alright. Missed that it only unregistered one, thanks.

**Comment by Diamond-74** [comment]
Yea your idea worked in testing.

**Comment by SyncIt21** [comment]
Undraft your PR when ready.

**Comment by Diamond-74** [comment]
Oh, thanks. Didn't know I had control over that.

**Review by Mothblocks — APPROVED** [review]

**Pull request merged**
