### PR TITLE
Fixes progress bar spam building racks

### LINKED ISSUE #24056: Progress bars
Racks.
https://gyazo.com/f01a6fdc5cff0fdfd269f68140c309c9

### PR DESCRIPTION
**Pull request by Cyberboss**
:cl: Cyberboss
fix: Rack construction progress bars will no longer be spammed
/:cl:

Fixes #24056

These are dirt easy to fix and there are a lot of them, so keep reporting them

### CODE REVIEW

**Comment by RemieRichards** [comment]
Could this not be genericised to something the proc itself checks for?

ie:
1. do_after() called, sets var on object
2. do_after() is called again, sees var, returns early
3. do_after() ends, unsets var on object
4. do_after() is called again, sets var on object...

**Comment by Cyberboss** [comment]
That'd be nice, but then we run into the problem of parent procs outputting messages anyway and potentially doing other things.

Frankly, do_* needs an overhaul refactor but I'm too lazy to do it

**Comment by PKPenguin321** [comment]
I think stripping can create duplicate bars

**Comment by optimumtact** [comment]
do_after doesn't need an overhaul, the entire construction system does, it's just blatant iftype and copypaste code in every attack_by

**Comment by Cyberboss** [comment]
True dat. What we really need is some sort of handler list for attackby that is keyed by attacking obj type. Runs the proper proc and prevents dupes from the same person running.

I'd do it, but it sounds tedious and I have like 12 other projects rn

**Pull request merged**
