### PR TITLE
Fixes some belt sprite issues.

### PR DESCRIPTION
**Pull request by Coconutwarrior97**
## About The Pull Request

Some issues with update_icons.dm causes the item_state of items to not be set correctly to what they should be. This is a workaround making the item_state and icon_state of some belts identical, so no matter what item_state is set to it still references the correct sprite. 

Specifically fixes the utility belt, CE's utility belt, medical belt, and security belt.

## Why It's Good For The Game

Fixes some sprite errors with belts.

## Changelog
:cl:

fix: Fixes sprite errors with utility belt, CE's utility belt, medical belt, and security belt.
/:cl:

### CODE REVIEW

**Comment by Dorsisdwarf** [comment]
Relevant issue: #50895

**Comment by ExcessiveUseOfCobblestone** [comment]
i'm just going to demand people to call their iconstate and itemstate the same thing, it is a reoccurring issue that would be fixed by simply not calling the same thing 2 different things!

**Comment by actioninja** [comment]
@ExcessiveUseOfCobblestone I've considered just straight up nuking the item_state and other vars and having them all use the same name but some things share inhands

**Comment by ExcessiveUseOfCobblestone** [comment]
rip

**Pull request merged**
