### PR TITLE
Halves the time required for a changeling to absorb someone

### PR DESCRIPTION
**Pull request by ATH1909**
## About The Pull Request

This PR reduces the amount of time required for a changeling to absorb someone they have in a kill grab from 45 seconds to 22.5 seconds.

## Why It's Good For The Game

Changelings receive special benefits for absorbing other changelings (an increased number of points to spend on powers, a larger maximum chem storage capacity, etc.), incentivizing changelings to kill each other instead of working as a big happy family (or at least to not trust other changelings as easily). While this is a nice concept, there's a problem with it.

It takes only 40 seconds for a changeling to be able to resurrect themselves after (faking their) death, but it takes 53 seconds (8 seconds to go from not grabbing up to a kill grab, then 45 seconds to perform the succ after obtaining a kill grab) for a changeling trying to absorb them to successfully do so. This leads to an awkward meta of changelings handcuffing their changeling victims before absorbing them so that their victims won't just get up and walk away. Even if you handcuff them, a changeling with enough chems (and spare gene points) can escape an absorption attempt by activating Biodegrade, which could give them enough time to break your grip and force you to start the looooooooooong absorption process all over again.

With this PR, it will only take 30.5 seconds to go from not grabbing someone to having finished absorbing them, which will give you 9.5 seconds (or more, if your opponent is slow on the draw) of leeway if you try to kill and then absorb another changeling.

Also, sitting on a body in maint waiting for a _45 second long_ series of do_afters() to complete is not what I'd exactly call thrilling antagonist gameplay. Maybe now absorption will be slightly less outclassed by just stripping off someone's jumpsuit, stuffing them in a locker, and calling it a day.

## Changelog
:cl: ATHATH
balance: The amount of time required for a changeling to absorb someone they have in a kill grab has been reduced from 45 seconds to 22.5 seconds.
/:cl:

### CODE REVIEW

**Comment by Fikou** [comment]
the moments where you get to revive in a ling fight when you are almost absorbed are awesome this sucks

**Comment by zxaber** [comment]
If the main justification for this change is to prevent other lings from waking up mid-absorb, it seems like a better bet is to just increase the time for revive.

**Comment by ATH1909** [comment]
> If the main justification for this change is to prevent other lings from waking up mid-absorb, it seems like a better bet is to just increase the time for revive.

That affects more general changeling balance, though.

> the moments where you get to revive in a ling fight when you are almost absorbed are awesome this sucks

You'll still be able to get those if the other changeling tries to drag you into maint or something before absorbing you.

**Comment by optimumtact** [comment]
>This leads to an awkward meta of changelings handcuffing their changeling victims before absorbing them so that their victims won't just get up and walk away. Even if you handcuff them, a changeling with enough chems (and spare gene points) can escape an absorption attempt by activating Biodegrade, which could give them enough time to break your grip and force you to start the looooooooooong absorption process all over again.

What's awkward about it, this smacks of Ided

**Comment by ATH1909** [comment]
> > This leads to an awkward meta of changelings handcuffing their changeling victims before absorbing them so that their victims won't just get up and walk away. Even if you handcuff them, a changeling with enough chems (and spare gene points) can escape an absorption attempt by activating Biodegrade, which could give them enough time to break your grip and force you to start the looooooooooong absorption process all over again.
> 
> What's awkward about it, this smacks of Ided

I don't believe I've had an enemy changeling revive out of an absorption attempt yet. The closest this comes to being an ided is that I've been handcuffed and then absorbed (by another changeling) before as a changeling.

**Comment by bloons3** [comment]
> If the main justification for this change is to prevent other lings from waking up mid-absorb, it seems like a better bet is to just increase the time for revive.

BeeStation changed lings and gave them the headcrab ability by default, which turned into a cancerous meta that made absorbing another ling objectives impossible.

**Comment by Cyberboss** [comment]
I'd rather see the revive time nerfed than this buffed

**Pull request closed without merging**
