### PR TITLE
Single Tank Guide contraband poster

### PR DESCRIPTION
**Pull request by MTandi**
## About The Pull Request

Adds a contraband poster with a guide for high quality single tank bombs.

image

## Why It's Good For The Game

Nice poster for the contraband pool.

## Changelog

:cl:
image: added single tank bomb guide contraband poster
/:cl:

### CODE REVIEW

**Comment by carlarctg** [comment]
genius

**Comment by MTandi** [comment]
> I'm not the foremost expert on atmos code or how likely this actually is but spriting in a reference to a numerical value seems like asking for it to become out of date when the code changes.

It isn't supposed to be useful.

**Comment by san7890** [comment]
blowing yourself up because you listened to a poster fits in perfectly well with the whole "tablet microwave" thing so 👍

**Comment by MTandi** [comment]
One of the drafts that didn't go in

image

**Pull request merged**
