### PR TITLE
tray belt and worn sprite

### PR DESCRIPTION
**Pull request by Tlaltecuhtli**
:cl:
fix: tray wearable on belt and has sprite
/:cl:

### CODE REVIEW

**Review by Twaticus — APPROVED** [review]
is that a tray in your pants

**Comment by bobbahbrown** [comment]
[changelog: fix](https://imgur.com/SG6aOj5.mp4)

**Review by ShizCalev — APPROVED** [review]

**Comment by RaveRadbury** [comment]
Thanks for this, Tlal!

**Comment by BigGrease** [comment]
epic thank you

**Comment by PKPenguin321** [comment]
You forgot to mark this as a fix

**Pull request merged**
