### PR TITLE
Servants of Ratvar can now unsecure and move most Clockwork Structures

### PR DESCRIPTION
**Pull request by ChangelingRain**
:cl: Joan
rscadd: Servants of Ratvar can now unsecure and move most Clockwork Structures with a wrench, though doing so will damage the structure by 25% of its maximum integrity.
rscadd: Clockwork Structures become less effective as their integrity lowers, reducing their effect by up to 50% at 25% integrity.
tweak: You can now deconstruct unsecured wall gears with a screwdriver.
tweak: Wall gears now have much more health and can be repaired with a proselytizer.
/:cl:

`default_unfasten_wrench()` now has some slightly more proper checks; you can't secure stuff to something that isn't a floor, but you can unsecure it from the not-floor, and it won't change the anchored state unless it's the same state as when it started.

### CODE REVIEW

**Comment by ExcessiveUseOfCobblestone** [comment]
I believe you said earlier that "clockwork is all about perfection", which this seems a bit in the face of that.

Being able to move TCs over to cwall seems like a pretty powerful buff.

**Comment by ChangelingRain** [comment]
It's not.. exactly a buff, given that you can also move the wall. It's more a convenience thing.
It's definitely a buff for power-using structures, though, as you can move them near a sigil if you misplace it.

**Comment by XDTM** [comment]
I personally like the identity of clock cult as static cult and blood cult as mobilized cult. An alternative would be to let servants deconstruct their structures for a portion of the cost.

**Comment by ChangelingRain** [comment]
Alright, I've adjusted it; unwrenching structures damages them(you can't destroy them in this manner) and they get less effective with lower health(so you want to repair them, and moving them around has a 'cost' of sorts)

**Comment by ExcessiveUseOfCobblestone** [comment]
or just allow them to be removed for a partial-refund?

**Pull request merged**
