### PR TITLE
Uniformly aligns the crew jobs columns across dept headers in the View Crew Manifest window.

### LINKED ISSUE #67546: View Crew Manifest alignment off
## Testmerges: 
https://github.com/tgstation/tgstation/pull/67307
https://github.com/tgstation/tgstation/pull/67385

## Reproduction:
1. Observe round (whether a custom job role has been added matters I'm unsure)
2. Ghost Tab ->  View Crew Manifest

gif

### PR DESCRIPTION
**Pull request by atosti**
## About The Pull Request
This changes the job columns in the `View Crew Manifest` window (found under the Ghost tab) to be uniformly aligned across the different department headers. This will happen whether or not a department head is present in each department header (meaning the chevron-up symbol, `^`, is present in the list.)

Additionally, ridiculously long first and last names used to visually overlap onto the crewmember job column. This no longer happens, as the text is now truncated. 

(Note that the full names of crewmembers can still be viewed by simply resizing the crew manifest window to be wider.)

**Before (look at the right-most column):**
crew-manifest-before

**After:**
crew-manifest-final

For reference, this is how long names used to overflow:
long-names-issue

## Why It's Good For The Game
This creates a visually cleaner UI which follows a uniform format that is easier to read at a glance, especially when quickly scrolling through the entries. Moreover, it addresses the formatting issue mentioned in [#67546](https://github.com/tgstation/tgstation/issues/67546).

## Changelog
:cl:
fix: the jobs columns in the View Crew Manifest window are now uniformly aligned across department headers
fix: extremely long crewmember names are now truncated in the default view for the Crew Manifest window
/:cl:

Closes #67546

### CODE REVIEW

**Comment by BlueMemesauce** [comment]
its easier to read in the before in my opinion
we read from left to right in english so left alignment makes the most sense in 99% of cases

**Comment by atosti** [comment]
The more I look at it, the more I think @BlueMemesauce is right that a left-align is actually best for readability.

However there's still the issue of the jobs column looking indented for shorter job titles. A solution I'm considering is aligning the columns to a central point, dictated by the length of the longest job's title (in my images, that would be `Chief Medical Officer`).

For illustration purposes:
crew-manifest-idea

It would effectively shift the shorter job titles further left to match the length of the widest row present across all crew categories (Command, Security, Medical, etc.).

Any input from the maintainers on the the desired UI layout for this would be appreciated.

**Comment by stylemistake** [comment]
@atosti, when I looked at screenshots, I immediately thought that aligning columns instead of text would be a much better solution. If you can figure that out, that would be perfect.

**Comment by atosti** [comment]
I've updated the code to now align the job columns uniformly. Additionally, I updated the PR name and body to better reflect these new changes. Let me know if there's anything I missed or that needs improving.

**Comment by san7890** [comment]
pretty

**Pull request merged**
