### PR TITLE
Tweaks saline-glucose solution

### PR DESCRIPTION
**Pull request by swindly**
:cl: Swindly
fix: Saline-glucose solution can no longer decrease blood volume
add: Cyborg hyposprays can now dispense saline-glucose solution
add: Saline-glucose solution now increases blood volume when it heals
/:cl:

[]: # (Please add a short description of why you think these changes would benefit the game. If you can't justify it in words, it might not be worth adding:)
1. Saline-glucose solution can currently lower blood volume if blood volume is greater than 700.
2. Treating blood loss as a cyborg currently sucks.

### CODE REVIEW

**Comment by XDTM** [comment]
I agree with adding it to borgs but i'm not really sure it needs a nerf

**Comment by ExcessiveUseOfCobblestone** [comment]
lol SGS is garbage as is

**Comment by Shapsy** [comment]
Needs a slight buff more than it needs a nerf

**Comment by swindly** [comment]
Okay, it now increases blood volume when the heal is triggered.

**Comment by ExcessiveUseOfCobblestone** [comment]
I should make a dedicated blood fixing chem hmmmm

**Comment by XDTM** [comment]
You mean iron?

**Comment by ExcessiveUseOfCobblestone** [comment]
That's not a chem that's an element!

**Comment by RandomMarine** [comment]
>I should make a dedicated blood fixing chem hmmmm

Yeah, it's called blood.

**Comment by ExcessiveUseOfCobblestone** [comment]
You got me...

**Pull request merged**
