### PR TITLE
Corrects double barrel right inhand being the wrong sprite

### PR DESCRIPTION
**Pull request by actioninja**
## About The Pull Request

as title

## Changelog
:cl:
fix: right hand double barrel inhand is now the correct sprite
/:cl:

### CODE REVIEW

**Comment by Tlaltecuhtli** [comment]
improvised shotgun inhand looks like a riot one

**Comment by actioninja** [comment]
I never made an inhand for the improvised shotgun, riot is being used as the generic one.
I probably should but the improvised shotgun sprite is not great.

**Comment by carlarctg** [comment]
compact combat shotgun uses the normal combat shotgun sprite

**Comment by nemvar** [comment]
Ever considered that they always used to do that?

Basically all normal projectile guns used to have the same inhands, there's nothing wrong with some of them being duplicates for now.

**Review by SpaceManiac — APPROVED** [review]

**Pull request merged**
