### PR TITLE
Re-adds Spear to tablecrafting menu, SLAPCRAFTING IS STILL ALIVE

### PR DESCRIPTION
**Pull request by Iamgoofball**
READ THE TITLE

this just allows both methods

### CODE REVIEW

**Comment by PKPenguin321** [comment]
Kinda weird that we didn't have this in the first place

Also tag is kind of inaccurate

**Comment by Cheridan** [comment]
PK it's technically a partial revert of a full revert!

**Comment by Bawhoppen** [comment]
goof put it at the top like I had originally you donker

**Comment by lzimann** [comment]
oh yea i was going to do this but i forgot

**Pull request merged**
