### PR TITLE
replaces a copyrighted sound

### PR DESCRIPTION
**Pull request by grungussuss**
### comparison:

https://github.com/user-attachments/assets/31434a87-231c-4ffa-94b1-440b699c20ef

https://github.com/user-attachments/assets/0482062b-b6d0-4b1c-aca1-515a3589179b
## Why It's Good For The Game
let's not infringe on copyright
## Changelog
:cl: grungussuss
sound: the "curse you" sfx has been replaced
/:cl:

### CODE REVIEW

**Comment by Sadboysuss** [comment]
> who owns rights for that sound

Valve

**Comment by Kapu1178** [comment]
didnt credit me for finding it pensive

its a dota 2 sound effect. its Silencer's Arcane Curse cast effect.

**Comment by Sadboysuss** [comment]
> didnt credit me for finding it pensive

kapu reported the infringement

**Comment by EricZilla** [comment]
I think its really hard to understand the new version, it almost sounds like its "PURSE" then someone whispering "oooh"

**Pull request merged**
