### PR TITLE
Adds the sound emitter circuit component

### PR DESCRIPTION
**Pull request by Watermelon914**
## About The Pull Request

Adds the sound emitter circuit component. Allows the integrated circuit to play a sound of varying volume and frequency.

## Why It's Good For The Game

More job content

## Changelog
:cl:
expansion: Adds the sound emitter circuit component.
/:cl:

### CODE REVIEW

**Comment by Rohesie** [comment]
How possible is it to use this feature of yours to spam sounds?

**Comment by Watermelon914** [comment]
> How possible is it to use this feature of yours to spam sounds?
> Edit: one second cooldown. I'm slightly worried.

increasing the cooldown is no problem at all

**Comment by Watermelon914** [comment]
Additionally, I can make this component consume more power when triggered so that it'd run out of power pretty fast if spammed.

**Comment by Rohesie** [comment]
Both are good solutions. If you could apply both, that'd be good.
I have some concerns regarding automation in general, and it's an unfortunate fact that a fair amount of people derive most of their satisfaction from annoying others. Not giving them too many easily usable tools for that would be positive.

**Comment by Watermelon914** [comment]
> Both are good solutions. If you could apply both, that'd be good.
> I have some concerns regarding automation in general, and it's an unfortunate fact that a fair amount of people derive most of their satisfaction from annoying others. Not giving them too many easily usable tools for that would be positive.

probably the wrong pr to discuss the concerns of automation since this only adds the sound emitter. Feel free to discuss it on discord with me. I'll increase the cooldown to 2 seconds.

**Pull request merged**
