### PR TITLE
Heretics no longer need the amber focus,warm eldritch medallion or the eldritch robes to use spells (re-opened)

### PR DESCRIPTION
**Pull request by ANAME593**
## About The Pull Request
removes the need for a focus/medallion/heretic hood to use spells

## Why It's Good For The Game
the amber focus completely blows your cover as a heretic and isn't a fair trade off for the spells it lets you use.

for supernova specifically, 

i get my gbp sucks and i don't have a history of making any contribution to the code base but - this pr will genuinely improve the game in some way and i want you to allow some discussion to occur before closing this even if my gbp gives you the right to, i don't see why i need a good GBP to make prs that i believe will improve the game i've seen people making prs at -11 gbp (they got merged)  - this was re-opened because i dont think closing https://github.com/tgstation/tgstation/pull/68764 was a good idea at all especially since the reasoning was "he don't make bug fix"

## Changelog

:cl:
balance: heretics no longer have to use the  amber focus/eldritch medallion/eldritch robes to gain the ability to cast spells

/:cl:

### CODE REVIEW

**Comment by SuperNovaa41** [comment]
The requirement was pretty simple, make some fixes

**Comment by JohnFulpWillard** [comment]
Your last PR was rightfully closed by a maintainer, they told you to get your GBP up. Don't open new PRs to ignore what maintainers ask you to do, the github bot specifically says that negative PR means maintainers can close the PR at will without explanation needed.

**Comment by ANAME593** [comment]
> You currently have a negative Fix/Feature pull request delta of -5. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

"improving the codebase"

**Comment by ANAME593** [comment]
> I still don't want the focus to be straight up removed, if the spells aren't good enough I would rather they be buffed

so heretics get to become like cultists/wizards?

**Pull request closed without merging**
