### PR TITLE
explicitly allows flightsuits to pass mobs

### PR DESCRIPTION
**Pull request by silicons**
#32442 is going to remove the automatic passing from flying so now it has to be manually put.

### CODE REVIEW

**Comment by ChangelingRain** [comment]
I think this is kind of dumb really

**Comment by DoctoreMad** [comment]
The flightsuit? I mean, yeah it is.

**Comment by RemieRichards** [comment]
give it PASSBLOB too why don't you.

**Comment by Bawhoppen** [comment]
Flightsuits definitely don't need to keep this

**Comment by optimumtact** [comment]
should be obviou why it's closed

**Pull request closed without merging**
