### PR TITLE
Adds a brand new 100% original roundstart Alien Race to the game!

### PR DESCRIPTION
**Pull request by Iamgoofball**
:cl: Cheridan
add: Added a new race to the game. Check it out in the setup menu!
/:cl:
dreamseeker_2016-07-25_18-15-29

### CODE REVIEW

**Comment by Jordie0608** [comment]
So can we just close this right away.

**Comment by ChangelingRain** [comment]
I don't feel like humoring memes right now.

**Comment by Iamgoofball** [comment]
:+1:

**Comment by YakumoChen** [comment]
only if they're insta-valid

**Pull request closed without merging**
