### PR TITLE
Cobbduceus: Surgery Skill XP/Step Buffs

### PR DESCRIPTION
**Pull request by ExcessiveUseOfCobblestone**
## About The Pull Request

Bumps Up Surgery XP for all surgeries. If a surgery was lowered in XP it was done to fit the define system.

All Surgery XP values are based on a define for easier editing. Below is a table that explains the tiers.

First Row is XP Needed to Level, following rows is how many steps of that tier it would take to reach that level.

**NOTE:** Most surgeries have several easy steps on top of a higher tiered step. Some surgical steps have in between values to compensate for repeatability. Some surgical steps are based on a define but scale with other sources related to the surgery such as fat removed or reagents vomited out.

Tier | Formula | Value | Novice | Apprentice | Journeyman | Expert | Master | Legendary
-- | -- | -- | -- | -- | -- | -- | -- | --
N/A | N/A | Value | 100 | 250 | 500 | 900 | 1500 | 2500
Easy | N/A | 3 | 34 | 84 | 167 | 300 | 500 | 834
Medium | Easy*3 | 15 | 7 | 17 | 34 | 60 | 100 | 167
Organ | Medium*1.75 | 26.25 | 4 | 10 | 20 | 35 | 58 | 97
Advanced | Medium*2.5 | 37.5 | 3 | 7 | 14 | 25 | 41 | 68

## Why It's Good For The Game

Fits the skill with the 90 minute timeframe

## Changelog
:cl: Cobby
balance: Buffs Surgery XP values
/:cl:

### CODE REVIEW

**Comment by wesoda25** [comment]
thx bro

**Comment by RaveRadbury** [comment]
Does this make maxing the surgery skill easier to do within 90 minutes? I thought Oranges said that cap should be slightly higher so that surgery isn't maxed in any given 90 minute round?

**Comment by ExcessiveUseOfCobblestone** [comment]
https://tgstation13.org/phpBB/viewtopic.php?f=10&t=25420&p=539342#p538776

**Comment by ExcessiveUseOfCobblestone** [comment]
I'm expecting you to reach master/legendary with this setup and if that fails I can just easily change 1 file instead of 20+

**Review by bobbah — APPROVED** [review]

**Comment by Spepbuthewranglesgithub** [comment]
i still think that surgery is nothing but a garbage quick time event but ok you do you

**Comment by Mickyan** [comment]
Out of curiosity do you use a formula to calculate the average amount of XP you can gain in a 90 minute round or is it from personal experience

**Comment by ExcessiveUseOfCobblestone** [comment]
Outside of the table above, I've just been playing medical and realizing i'm doing good to get passed apprentice lol.

**Comment by ExcessiveUseOfCobblestone** [comment]
> i still think that surgery is nothing but a garbage quick time event but ok you do you

you're free to make it "fun" or make a new avenue which is both "fun" and puts emphasis on relying on someone else and not protagonism/mary sue style of play.

**Comment by trollbreeder** [comment]
I keep forgetting that skill is a mechanic that... exists.

**Comment by ExcessiveUseOfCobblestone** [comment]
> I keep forgetting that skill is a mechanic that... exists.

well in terms of surgery it's because you never really used it since you'd usually lvl up once, maybe twice in a round.

we need fireworksounds and skill~~capes~~ vanities

**Comment by Spepbuthewranglesgithub** [comment]
> you're free to make it "fun" or make a new avenue which is both "fun" and puts emphasis on relying on someone else and not protagonism/mary sue style of play.

i cant code so, no?

**Comment by ExcessiveUseOfCobblestone** [comment]
ok then it stays a quick time event until I or someone else can get to it 😏

**Comment by Tlaltecuhtli** [comment]
what if we make surgery into tetris

**Comment by dr-bee** [comment]
any chance of giving doctors a few free levels of this at roundstart? It makes sense for them to be slightly better at it than normal.

**Comment by ExcessiveUseOfCobblestone** [comment]
No, it's easy to get a few levels by just performing the surgeries you as a doctor are expected to do anyways.

**Comment by Spepbuthewranglesgithub** [comment]
> ok then it stays a quick time event until I or someone else can get to it 😏

_then do so, please._

**Comment by PKPenguin321** [comment]
@Spepbuthewranglesgithub that's way out of scope of this PR, chill

**Review by kriskog — APPROVED** [review]

**Comment by adamkad1** [comment]
Whats next, are you going to add actuall QTE's? like pressing buttons at the right time?

**Comment by cacogen** [comment]
>puts emphasis on relying on someone else and not protagonism/mary sue style of play.

giving jobs starting skills would reduce this but who likes having to rely on other people in this game

**Comment by adamkad1** [comment]
> No, it's easy to get a few levels by just performing the surgeries you as a doctor are expected to do anyways.

Yeah, do dissections. You start with a few corpses and research will love you

**Comment by ExcessiveUseOfCobblestone** [comment]
> 
> 
> Whats next, are you going to add actuall QTE's? like pressing buttons at the right time?

lol

**Pull request merged**
