### PR TITLE
[Delta] Misc map fixes

### LINKED ISSUE #25083: A lot of deltastation's warning lines used to be double warning lines
Delta's warning lines are super fucked and a lot of them used to be doubles but antur's decals didn't account for that and I didn't catch it so I guess somebody is going to have to fix those manually

### LINKED ISSUE #28110: Lighting around Syndicate shuttle messed up [delta]
https://file.house/TkJM.png

### PR DESCRIPTION
**Pull request by ghost**
Fixes a few checkered tiles in maintenance and disposals, also fixes two instances of two plating turfs on the same tile within medical.

The Syndicate ship should also have it's correct area too.

Brings back all/most of delta's missing warning lines.

Fixes #28110 
Fixes #25083

### CODE REVIEW

**Comment by WJohn** [comment]
Since you're touching delta, could you fix #28110 while you're at it? I messed up and forgot about the area.

**Comment by Mark9013100** [comment]
@WJohn sure

**Comment by Mark9013100** [comment]
@WJohn Should be fixed now.

**Comment by WJohn** [comment]
Thanks. Fixes #28110

**Comment by Mark9013100** [comment]
Going to try and resolve #25083 while I'm at it.

**Comment by Mark9013100** [comment]
Fixes #25083

**Comment by lzimann** [comment]
You have to put `Fixes # issue number` in the op. Leaving in the comments won't have any effect!

**Comment by Mark9013100** [comment]
@lzimann gotcha

**Pull request merged**
