### PR TITLE
Cycler Automatic Shotgun Alteration

### PR DESCRIPTION
**Pull request by Steelpoint**
:cl: Steelpoint
tweak: Nanotrasen Security have issued a new variant of the Cycler Automatic Shotgun. This new variant is equipped with a integrated holster system designed to allow the weapon to be placed onto standard issue NT armour akin to most other firearms. 
/:cl:

The Cycler Shotgun suffers from several issues that renders it a almost un-used weapon that is rarely taken by anyone.

My proposal is meant to make it slightly more viable.

The weapon is now classified as bulky item. Meaning it can be placed into your suit storage slot if you are wearing a applicable armour, but it still won't fit in a backpack.

-------------

Thank you for reading.

### CODE REVIEW

**Comment by GunHog** [comment]
So, it is now just a combat shotgun? You could not be bothered to fix it?

**Comment by Dorsisdwarf** [comment]
So its just a combat shotgun now? Why not just give him a combat shotgun and kill the cycler

**Comment by Steelpoint** [comment]
Its a automatic shotgun still.

**Comment by Dorsisdwarf** [comment]
The combat shotty is automatic

**Comment by Steelpoint** [comment]
Pretty much, except it looks different.

**Comment by AnturK** [comment]
You should probably change the name then since it makes no sense now.

**Comment by Steelpoint** [comment]
Well it still cycles shells. If we want I can try and think of a alternative name but it seems like a minor issue.

**Comment by jughu** [comment]
Fuck off steelpoint

**Comment by Repukan** [comment]
We have a lot of guns in the game, why not see which else is appropriate and give it to the warden?

**Comment by Repukan** [comment]
Or make it a random chance for the warden to get the pea shooter, shotgun or an NT based stetchkin

**Comment by jughu** [comment]
Thats called the metastation armour mr.

**Comment by KorPhaeron** [comment]
>Firstly, the dual-tube system is gone. Instead of nine (8) shells between two tubes, its down to six (6) shells in a single tube like every other shotgun in the game.

Why have it in the game then?

**Comment by Steelpoint** [comment]
It's technically different to the normal Combat Shotguns in that it can fit in a armour slot whereas the Combat Shotguns cannot. Giving it a advantage.

**Comment by ShadowDeath6** [comment]
Fun removal
You should just name it compact combat shotgun because that's what it is

**Review by Cyberboss — APPROVED** [review]

**Comment by KorPhaeron** [comment]
Seems less interesting to just have a gun but better rather than one that functions differently

Could just make a compact riot shotgun instead if you really want one of those rather than deleting the cycler

shotgun

**Comment by Dorsisdwarf** [comment]
sawn-off combat shotgun. fits in bag, inaccuracy +0.5

**Comment by Steelpoint** [comment]
Didn't even consider a saw-off variant of the Combat Shotgun.

But the end result is the removal of the Cycler Shotgun.

**Comment by ChangelingRain** [comment]
It being able to swap was the whole reason it was interesting, don't remove that, fix it!

**Comment by Steelpoint** [comment]
Its a gimmick that is half broken, even if its fixed its still a bad gimmick.

Hardly anyone uses it and those that do just fill it with buckshot and treat it as a Combat Shotgun but with three extra buckshot rounds.

I don't mind the outcome of this PR either way, since I think technically the Cycler is far more powerful as it stands.

At the very least I would suggest letting it be placed on the armour slot, if we want to keep the dual-tubes then we can

**Comment by jughu** [comment]
Stay off my warden gameplay steelpoint reee

**Comment by Steelpoint** [comment]
Its unreliable to use as the Warden.

If you use a split of buckshot in one tube and rubber bags in the other, you run the risk of the buckshot mixing in with the rubber shells, thus you'll accidently blast the arm off of someone you meant to stun.

I'll refit the PR to just make the Cycler fit in the armour slot, I think this would make the weapon more popular.

**Comment by Repukan** [comment]
But putting someone in crit is the best stun.

**Comment by Repukan** [comment]
They don't move, resist, and are quiet during their processing

**Comment by Steelpoint** [comment]
I dunno, I just find it perplexing a lot of people are defending a utterly unused item. I've never seen a Warden take the Cycler nor do I see people taking it when they break into security.

Anyway, I'm going to change it so the Cycler just fits in armour slots, the tube system will remain as is.

**Comment by PKPenguin321** [comment]
Try fixing it

**Comment by Steelpoint** [comment]
As I said, I don't have the expertise to fix the issues, hence I'm instead just now proposing a smaller change to encourage more usage of the weapon.

**Comment by GunHog** [comment]
Coderbus exists to help coders with their code. If you want to fix the cycler, join coderbus and ask for help.

**Comment by Repukan** [comment]
Bullshit, coderbus exists to suppress the masses and keep the prole in check

**Comment by GunHog** [comment]
Shh! You are not supposed to state that out loud!

**Comment by Robustin** [comment]
Make the thing not such a bullshit Rubicks Cube of a gun instead of just buffing it.

CLICK ONCE TO CHAMBER THE SHELL THEN CLICK IT AGAIN TO CHANGE THE TUBE THEN CLICK IT AGAIN TO CHAMBER THE SHELL FOR THAT TUBE....

**Comment by Repukan** [comment]
>Brainlet doesn't know how to unfuck his gimmick 5th dimensional post modern gun


Never gonna make it

**Comment by Supermichael777** [comment]
its gimmick is straight up broken because swapping tubes doesn't change what round is chambered.

**Comment by Cyberboss** [comment]
Maybe make it automatic and chamber + fire in one click?

**Comment by Steelpoint** [comment]
I'll leave fixing it in the hands of someone able to code.

**Pull request closed without merging**
