### PR TITLE
Triples the price on the bee grenade bundle.

### PR DESCRIPTION
**Pull request by Iamgoofball**
:cl: Iamgoofball
balance: Buzzkill Grenade Box Cost: 5 -> 15
/:cl:

Requested by maintainer. Went with a triple since 10 tc is still hilariously low. with op TC counts.
hexchat_2018-07-28_01-50-51

### CODE REVIEW

**Comment by 81Denton** [comment]
Whew, I honestly didn't expect them to kill so many people.

**Comment by Kagus** [comment]
The fuck? This has actually been killing people?

I am surprised and entertained. This will make it so nobody ever uses them, so good rebalance I guess.

**Comment by Kagus** [comment]
> I think most people also don't know that fire/bio/EOD suits make you bee immune

Also the bee costume, plasmaman suits, every hardsuit, and the EVA suits.

There's also the very real possibility that everyone's using beenades now because they're new and interesting, not so much because their effectiveness is worth more TC than an entire bulldog/C20r bundle.

**Comment by Kromgar** [comment]
New toys always get overused

**Comment by WJohn** [comment]
Why exactly do we have bee grenades when we have viscerator 'nades meant to fulfill basically the same role but are actually thematically appropriate?

**Comment by 81Denton** [comment]
The uplink has plenty of goofy items like Donksoft guns/dehydrated carps/nukie costume bundles already, I disagree about them being inappropriate.

**Comment by optimumtact** [comment]
There should be an obvious "joke" category though that all this stuff should be in

**Comment by MrDoomBringer** [comment]
@optimumtact those things aren't jokes, though. They are all viable and deadly when used right.

**Comment by Kagus** [comment]
The gloves of the north star are also potentially quite powerful, but they're still lumped under "(Pointless) Badassery", which is already the joke category in the uplink.

The question comes down to whether or not that kind of rearranging would make the uplink _more_ or _less_ navigable and intuitive than it already isn't.

**Pull request merged**
