### PR TITLE
Re-recorded the piano instrument to sound better! (hopefully)

### PR DESCRIPTION
**Pull request by Polyphynx**
:cl: Polyphynx
tweak: The piano now sounds more like a piano!
/:cl:

The current notes for the piano sounded a lot like a toy to me, so I went ahead and re-recorded all(most) of the notes on my own piano. There were 8 I didn't record since they're an octave lower than the standard 88-keys... and my piano is just standard. I don't think it's a problem. 
Overall, the file size of all the piano notes together is now about 100KB smaller.

I also removed some (to my knowledge) unused instrument files that were left in the sound folder. 

Was this necessary? Probably not. But here, have some comparisons for your listening pleasure!

[Comparison 1](https://vocaroo.com/i/s0FnaCMD3EzD)
[Comparison 2](https://vocaroo.com/i/s1De1gABMWKw)
It starts with the old version, then switches between new and old occasionally.

From my perspective, the old version's notes are a lot more distinct, but sound tinny and end abruptly. While the new version is softer and more natural sounding, but a bit more muddled.  
I made the notes mono @ 16kHz sample rate to keep the file size low. 
Let me know what you think. I can easily re-record some more

Edit: I might as well add an example of just the new recording, with everyone's favorite dwarf song: https://vocaroo.com/i/s1dGpohGXDeV

### CODE REVIEW

**Comment by cyclowns** [comment]
i like it

**Comment by ShizCalev** [comment]
wtb comparison without ship ambients.

**Comment by Polyphynx** [comment]
It's the genuine experience comparison™!

**Comment by Buggy123** [comment]
I appreciate that you went through all that effort to re-record the sounds, and they sound much better, but... are there not pre-recorded piano sounds on the internet? Anywhere?

Surely at some point a professional decided to record a piano, with professional equipment in a echo-proofed room, and said "Eh, fuck it, that took 2 minutes. I'll just give it out for free.".

**Comment by nero1024** [comment]
@Buggy123 You can find convincing piano sounds as soundfonts on the internet such as SGM or the Spyro Soundfont Collection or from some midi synth like the SC-~~55~~8850, however the trick is recording all those sounds and getting it to sound right in SS13; ain't nobody got time for that. I blame it on the arse-about way SS13 does musical instruments.

**Comment by Polyphynx** [comment]
@Buggy123 Doing a quick look, I haven't found any samples for each note. But I'm sure they're out there. 

For reference, I haven't recorded this with a microphone over an acoustic piano or anything. This was recorded on a Yamaha DGX-650 digital piano (not the best, but still fairly solid quality).
The original recordings come directly from the piano in WAV format. They're a lot crisper and higher quality, buuuut if I wanted to use those instead, the total file size would go up about 2MB, which I don't think would be worth just a redo of an instrument, so I kept each note around 10KB in size instead of 35KB.

**Comment by Iatots** [comment]
The normal piano's high pitch reminds me of western saloons, and it's kinda grown on me as a game staple.

**Comment by Buggy123** [comment]
>The original recordings come directly from the piano in WAV format. They're a lot crisper and higher quality, buuuut if I wanted to use those instead, the total file size would go up about 2MB, which I don't think would be worth just a redo of an instrument, so I kept each note around 10KB in size instead of 35KB.

Why not just convert the format and tweak the compression a bit with a converter?

Eh, whatever. It works, it sounds fine, its fine.

**Comment by Polyphynx** [comment]
I just gave it a try with the higher quality versions, simply converted to .ogg. Surprisingly there wasn't much difference in-game. I think the way the sound is handled prevents getting really crisp audio.

@Iatots 
Fair enough, I can see that. Though I'm pretty biased. My biggest issue with the old one was the abrupt cutoffs of each note.

**Review by ShizCalev — APPROVED** [review]

**Comment by JohnGinnane** [comment]
these sound great

**Pull request merged**
