### PR TITLE
Dish drive no longer spams with empty messages

### PR DESCRIPTION
**Pull request by YakumoChen**
## About The Pull Request
Removes the annoying message that the dish drive constantly spams for no reason.

## Why It's Good For The Game

I don't need to know the machine hasn't processed anything new every 6 seconds, thanks.

## Changelog

:cl:
fix: Dish drive no longer spams the bar/kitchen/etc when its idle with empty messages.
/:cl:

### CODE REVIEW

**Comment by Mickyan** [comment]
You should add a manual check like on line 117 instead of removing the message

**Comment by YakumoChen** [comment]
I don't know what the message was actually meant to convey. It only activates when you place something inside or it sucks something up (which it immediately activates)
It's just an erroneous message that plays every 6 seconds fnr

**Comment by Mickyan** [comment]
You can activate the dish drive manually with alt-clicking. You are removing a useful feedback message that was meant to only appear when the dish drive is activated manually.

It was added in #55065

**Comment by YakumoChen** [comment]
Oh

**Comment by YakumoChen** [comment]
> You can activate the dish drive manually with alt-clicking. You are removing a useful feedback message that was meant to only appear when the dish drive is activated manually.
> 
> It was added in #55065

There's already an error message on line 118 for that?

**Comment by YakumoChen** [comment]
Better?

**Pull request merged**
