### PR TITLE
fixes stealth player ref

### PR DESCRIPTION
**Pull request by dannno**
removes a deliberate player ref that was allegedly snuck by maintainers I guess
i'm just the messenger kev don't scream in ooc about how I'm ruining your life please

### CODE REVIEW

**Comment by kevinz000** [comment]
10/10 wait I actually do recall removing this? huh. @KorPhaeron didn't you catch this and didn't I remove it?

**Comment by kevinz000** [comment]
aha oh yeah I did remove it when kor saw it but I reverted the branch to fix a conflict or something.

**Comment by ExcessiveUseOfCobblestone** [comment]
what is the player reference?

**Comment by ChangelingRain** [comment]
this is definitely not obviously a reference

**Comment by dannno** [comment]
It was added specifically as a reference

**Comment by optimumtact** [comment]
I don't get the reference so no

**Pull request closed without merging**
