### PR TITLE
Revert "ClickOn now actually calls ranged right click attacks"

### PR DESCRIPTION
**Pull request by optimumtact**
Reverts tgstation/tgstation#61848

>I... don't know how this was missed. Ranged right clicks only called post secondary attacks

Yes, becaues that's exactly what happens with ranged normal left clicks using a weapon too

secondary_attack and attack are only for the melee click chain.

### CODE REVIEW

**Comment by tralezab** [comment]
click chain won today

**Comment by optimumtact** [comment]
afterattack would be better called generic_click or similar.

**Comment by LemonInTheDark** [comment]
I'ma be honest I've touched attach chains and I barely understand what these words mean

**Comment by tralezab** [comment]
> I'ma be honest I've touched attach chains and I barely understand what these words mean

It's quite simple potato, GOSH. only a handful of procs:

**Comment by Watermelon914** [comment]
Fixes #61883

**Comment by Mothblocks** [comment]
did not read

**Comment by Mothblocks** [comment]
cannot believe i merged alt-right-click i must have been high

**Comment by adamkad1** [comment]
Go home moth, you are drunk

**Pull request merged**
