### PR TITLE
4/7/20 fuck

### PR DESCRIPTION
**Pull request by redta1l**
## Changelog
:cl:
add: Added new things
add: Added more things
del: Removed old things
tweak: tweaked a few things
balance: rebalanced something
fix: fixed a few things
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

### CODE REVIEW

**Comment by MrDoomBringer** [comment]
image

**Comment by PKPenguin321** [comment]
WHEN YOU
     ‏‏‎ ‎ ‏‏‎ ‎ ‏‏‎ ‎ ‏‏‎ ‎ ‏‏‎ ‎ ‏‏‎ ‎    ‏‏‎ ‎ ‏‏‎ ‎ ‏‏‎ ‎ ‏‏‎ ‎ ‏‏‎ ‎ ‏‏‎ ‎ ‏‏‎ ‎  EAST TEXT
WHEN YOU

**Review by Ryll-Ryll — APPROVED** [review]
Looks okay to me

**Comment by Archanial** [comment]
Speedmerge

**Comment by CRITAWAKETS** [comment]
cant complain if theres nothing to complain about

**Comment by redta1l** [comment]
bro shit wrong branch *scream

**Pull request closed without merging**
