### PR TITLE
Revert "Removes emergency meetings"

### PR DESCRIPTION
**Pull request by Mothblocks**
Reverts tgstation/tgstation#74437

### CODE REVIEW

**Comment by tralezab** [comment]
## I don't want us to be enemies. Please. Look at this image, it means a lot to me, it's what I think about you.

image

## Okay?

**Comment by tralezab** [comment]
but my decision is final

**Comment by Mothblocks** [comment]
# Ok Im sorry

**Comment by Teleported-Bread** [comment]
7gpjs1

**Comment by Fikou** [comment]
Among Us

**Comment by JohnFulpWillard** [comment]
Keep posting about amongus

**Comment by MrDoomBringer** [comment]
this could be big

**Comment by Jolly-66** [comment]
maintainer fight maintainer fight

**Pull request closed without merging**
