### PR TITLE
adds startup music for most gamemodes

### PR DESCRIPTION
**Pull request by ghost**
These are short 5 second or so clips to remind people when they're made antag at roundstart. Currently affects:

Changeling
Traitor
Wizard
Nuke Op
Malf
Cult

Sounds by cuboos. You can PM me on IRC if you have more sounds to add to this or edits to make.

### CODE REVIEW

**Comment by paprka** [comment]
Hey this can be merged and cuboos never really made any new versions so why not

**Comment by Chocobro** [comment]
why not? because it's not finished

**Comment by paprka** [comment]
if edits to the startup sounds need to be made he can make them, that's the benefit of open source

**Comment by paprka** [comment]
Oops it doesn't compile nevermind

**Comment by tkdrg** [comment]
It does though? That was just asteroid being stupid, back in the day.

**Comment by paprka** [comment]
PRs recompile when you reopen them

**Comment by tkdrg** [comment]
Well duh, the branch never changed, so your branch still has asteroid, thus it won't compile.

**Comment by PKPenguin321** [comment]
This didn't deserve to die the sounds are all so good I like the malf one so much

**Comment by Cuboos** [comment]
It died because paprika doesn't know how to fucking listen, many of these needed to be-redone in some way and one or two of them were incomplete. I stopped working on them because it seemed like no one wanted these.

**Pull request closed without merging**
