### PR TITLE
yikes

### PR DESCRIPTION
**Pull request by Iamgoofball**
-snip-

### CODE REVIEW

**Comment by Armhulen** [comment]
:+1:

**Comment by kevinz000** [comment]
goofball

**Comment by kevinz000** [comment]
ok fine the last picture is quite good

**Comment by ninjanomnom** [comment]
deus vult!

**Comment by Armhulen** [comment]
d e u s

**Comment by Qustinnus** [comment]
merge or i haunt you all with shitposts

**Comment by Tacolizard** [comment]
and I get banned for meme PRs


huh

really makes you think

**Comment by GunHog** [comment]
The song is okay, I guess, but seriously, is anyone **ever** going to crack down on Goof for his meme titles and descriptions? The pictures are no big deal, but he is still not explaining what he is doing, nor is he giving a reason why.

Is all that text you have to read and edit **every time someone makes a new PR** just fluff? Are our codebase rules enforced only on a whim basis, by people who do not really care about them?

The content of the PR is fine, and I support the new song. The presentation however, is quite annoying.

**Comment by Iamgoofball** [comment]
the title is accurate

the description is a visual description of what the PR does

**Comment by GunHog** [comment]
Fine, I will take your obvious bait if only because I am bored.

The title does not say anything about what the PR does. I do not know what "Saracen" is, but the title screen is probably not being occupied by it. The pictures only go with the reference, which is meaningless to those who have not experienced it. 

What your PR actually does is add a new song. Your title does not indicate this. Your description does not indicate this. You know that, I know that, and I am extremely bored and I find this somewhat entertaining.

**Comment by Iamgoofball** [comment]
explaining a joke because you don't get it kills the joke

**Comment by Qustinnus** [comment]
I'm pretty sure most elementary and high schools have history lessons about the crusades, so I hope for you that you got to experience that.

**Comment by Cyberboss** [comment]
@GunHog this is gonna be closed anyway, idk why I'm even leaving it open

**Comment by Vivalas** [comment]
image

I mean, I like Sabaton as much as the next WH40K / History nerd but I don't see how this is SS13 themed.

Either way :+1: x :100:

:latin_cross:
:cat:                            
:fire:

 ***D E U S V U L T***

**Comment by Shadowlight213** [comment]
Can't get the song to play. 0/10

**Comment by Iamgoofball** [comment]
@Shadowlight213 download it locally and play with VLC or something if the chrome shit doesn't work

**Comment by Jordie0608** [comment]
General Goofball. Years ago you served the Pope in the First Crusade. Now he begs you to help him in his struggle against the Infidel. I regret that I am unable to present the Pope's request to you in person, but my Venetian Galley has fallen under attack, and I'm afraid my mission to bring you to the Papal States has failed. I have placed information vital to the survival of the Kingdom of Jerusalem into the memory index of this Bible unit. The Pope will know how to retrieve it. You must see this Bible safely delivered to him in the Papal States. This is our most desperate hour. Help me Iamgoofball. You're my only hope.

**Comment by optimumtact** [comment]
This is actually a great song though @Jordie0608

**Comment by trollbreeder** [comment]
goof wtf why are you necroposting a 2 year old PR

**Comment by Vivalas** [comment]
hark! my email brought me to the land of long dead dreams of coders past

**Comment by Qustinnus** [comment]
Goof doing damage control on old prs that's hilarious

**Comment by PKPenguin321** [comment]
Epic pr

**Comment by Iamgoofball** [comment]
thanks github for emailing everyone for title edits

**Comment by trollbreeder** [comment]
> thanks github for emailing everyone for title edits

nah it was me
i always sort PRs on recently updated when there's nothing new on the repo
coderbus sees all, goof

**Comment by Iamgoofball** [comment]
owned

**Pull request closed without merging**
