### PR TITLE
Gives Head of Security All Access

### PR DESCRIPTION
**Pull request by ghost**
He shouldn't need to beg the AI (who is rogue) and the captain (who is a comdom) to let him into rooms to bring justice to the station.  

In all seriousness security should have someone capable of opening doors for them, and the Captain being blown up in a crisis shouldn't leave the HoP as the backup all access.

### CODE REVIEW

**Comment by Ikarrus** [comment]
Why not just give security a door jack or something. Something that takes a few seconds and is loud as fuck to use.

It's thematically different without overpowering the HoS too much

**Comment by xxalpha** [comment]
At first I was like
vulpix

But then
newmeme


:-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1:

**Comment by KorPhaeron** [comment]
@Ikarrus 

What about one of those battering ram things SWAT teams have? Could be a bulky item for back that smashes open doors.

**Comment by MrStonedOne** [comment]
honestly, it should require the hos click the door with the id, kinda like doing a security override in startrek, but via id cards and not voice commands.

**Comment by Steelpoint** [comment]
What MrStonedOne said, a device that takes a few moments and is obvious the door is being opened would be a better solution.

**Comment by Ikarrus** [comment]
@KorPhaeron however you want to do it. The idea is that it allows security into areas without letting them basically control the station. Bonus fun for letting the item getting "misplaced" or put into the wrong hands.

**Comment by xxalpha** [comment]
A reasonably long opening time sounds better than straight up all access. From 10 to 20 seconds, give enough time for the people inside to notice and bolt the door shut if they're resourceful.

**Comment by KorPhaeron** [comment]
@Ikarrus 
>without letting security control the station

Lets trade HoS all access for removing officer maint so its not absolutely crawling with them from roundstart

**Comment by Ikarrus** [comment]
@KorPhaeron with the asscap assmaint without secmaint wouldnt be so ass.

**Comment by Dorsisdwarf** [comment]
Reminder that this actually lets the HOS also promote all officers to all-access, and provides a fourth(!) roundstart source of all-access

Captain
Captain's Spare
Head of Personnel
and now Head of Security

:-1: Give him a doorjack just like the pAI's

**Comment by KorPhaeron** [comment]
pAI doorjack is quite possibly the most useless item on the station.

**Comment by Dorsisdwarf** [comment]
Well, obviously a hell of a lot faster than sixty seconds.

**Comment by GunHog** [comment]
Absolutely not. :-1: The HoS is not the Captain. You guys keep nerfing the AI as a way of making the round more 'lethal', but here you buff the HoS, whose job is to make the station safe even moreso than the AI ever did?

Ranting aside, I do not agree with giving the HoS more access. He is not supposed to be able to go everywhere he wants at all times, else antags will have few non-specialized ways to escape.

And what options do we have to stop the HoS barging his way into every department just because he feels like it?

**Comment by Jalleo** [comment]
@korphaeron sec maint is a config

**Comment by Cheridan** [comment]
help i can't tell who's trolling who anymore

**Pull request closed without merging**
