### PR TITLE
The Celestial Gateway will now prevent the emergency shuttle from leaving

### PR DESCRIPTION
**Pull request by ChangelingRain**
:cl: Joan
rscadd: The Celestial Gateway will now prevent the emergency shuttle from leaving.
tweak: However, Centcom will alert, in general terms, the location of the Celestial Gateway two minutes after it is summoned.
/:cl:

Also, for ghosts, the Celestial Gateway now ticks once per second, and as such the countdown timer now includes odd numbers instead of jumping over them.

### CODE REVIEW

**Comment by GunHog** [comment]
Good change. NO ONE LEAVES UNTIL YOU DEAL WITH THIS!!

**Comment by Bawhoppen** [comment]
>Good change. NO ONE LEAVES UNTIL YOU vote restart

FTFY

**Comment by Shadowlight213** [comment]
Finally!

**Comment by TechnoAlchemisto** [comment]
Cults should make sure the shuttle doesn't get called, not have a way to prevent it from leaving.

**Comment by Tacolizard** [comment]
cults are already overpowered with shuttle control. basically once they reach and endgame state the rest of the round is scripted, and it's lame.

**Comment by Shadowlight213** [comment]
Only blood cult has the shuttle extender. Clock cult lacks one.
Plus, CC has to defend their end game thing much longer than blood cult has to.

**Pull request merged**
