### PR TITLE
Rename pirate_Interdyne.dmm to pirate_interdyne.dmm

### PR DESCRIPTION
**Pull request by Zonespace27**
## About The Pull Request
The interdyne pirate ship doesn’t spawn on linux because it, unlike windows, is case sensitive when it comes to filenames.
## Why It's Good For The Game
Things working is good
## Changelog
:cl:
fix: Interdyne pirates now spawn on linux-hosted servers
/:cl:

### CODE REVIEW

**Comment by JohnFulpWillard** [comment]
Won't this break for people pulling master from Windows? You'd have to rename the file entirely, not just edit capitalization

**Comment by Maurukas** [comment]
> Won't this break for people pulling master from Windows? You'd have to rename the file entirely, not just edit capitalization

This seems to work correctly on local for me. Is there a specific issue I'm not aware of?

**Comment by san7890** [comment]
mothblocks typically speaks about having issues with this, just try `pirate_interdyne_ship.dmm` to be safe

**Comment by Mothblocks** [comment]
Do not ever rename a file only on case because it breaks Windows, find some other way to rename it (also stale)

**Pull request closed without merging**
