### PR TITLE
Makes Ephedrine require Morphine instead of sugar

### PR DESCRIPTION
**Pull request by Tacolizard**
:cl:
tweak: Ephedrine requires 1 part morphine instead of sugar
/:cl:

This is mainly to make the station more dependent on botany, as botany is good but takes a long time and has few unique chems. This is also somewhat more realistic, and makes Ephedrine/meth, some of the best chems in the game, a bit harder to make. Plus morphine has no real use outside of making people go to sleep so you can kill them.

@Shapsy said that morphine is good for stabilizing crit, but let's face it; nobody does that shit.

### CODE REVIEW

**Comment by Iamgoofball** [comment]
:-1: if they're too strong lower addiction values

**Comment by Tacolizard** [comment]
@Iamgoofball They're not too strong, I just think that the recipe for these advanced chems should be advanced. And botany deserves more stuff because of how long botany takes. Currently, botany can do cool stuff but the rest of the station dosn't really need them that much. This also gives morphine a use.

**Comment by LanCartwright** [comment]
No.

**Comment by Iamgoofball** [comment]
plus the recipes are still 1:1 with goon and should stay that way

**Comment by Shapsy** [comment]
Medbay already starts with a ton of morphine bottles so this really wouldn't do anything, and morphine already has a wonderful use in that it stops all slowdown, especially useful if you're near death or blew off a leg or two

**Comment by Tacolizard** [comment]
@Shapsy Morphine bottles only contain 30u of morphine, so making large batches of ephedrine would be difficult unless you collected all the morphine. And collecting morphine bottles is pretty suspicious. 

The whole idea is there's limited supply. This wouldn't really affect chemistry unless they were trying to mass produce ephedrine/meth, in which case they have to do a bare minimum of bargaining with botany for a chem botany can't even use and thus has no reason to horde.

**Comment by kevinz000** [comment]
Stop ruining the codebase.

**Comment by Tacolizard** [comment]
@kevinz000 I'm gonna shit on this code one variable at a time

**Comment by pudl** [comment]
This is bad.

**Comment by optimumtact** [comment]
Little tweaks like this really dont' seem to have much impact and people don't like it.

**Pull request closed without merging**
