### PR TITLE
Adds a few jelly reagents, small chem adjustments for slimepeople

### LINKED ISSUE #34517: Luminescent: Cryoxadone/Tricord interaction
@XDTM 

When Luminescents use their major purple slime ability, they get dosed with 10u Tricordrazine.
Since toxin damage is reversed for slimepeople, they end up taking tox damage instead of healing it.

Similar issue with minor dark blue ability: The 5u cryoxadone end up causing tox damage. On top of that, the 5u frost oil metabolizes more slowly than the cryoxadone, which means you end up having ~1u left over in your system once the cryoxadone is gone.

### LINKED ISSUE #34539: Adminrazine kills TOXINLOVING species
Round ID: 82082

@XDTM 

A Race Swap event made a bunch of people slimepeople, and then Invincibility gave people Adminrazine, which heals toxic damage, resulting in about 10 people all dying simultaneously.

Given that Adminrazine is supposed to be GODMODE THE CHEMICAL, this is probably an unintentional bug.

### PR DESCRIPTION
**Pull request by XDTM**
:cl: XDTM
add: Added Regenerative Jelly, made with tricordrazine and slime jelly. It regenerates a bit faster, and won't harm jellypeople.
add: Added Energized Jelly, made with teslium and jelly. It works as an anti-stun chemical for slimepeople and speeds up luminescents' power cooldown, but non-jellypeople will just get shocked.
add: Added Pyroxadone, made with cryoxadone and slime jelly. It's basically inverse cryoxadone: it heals faster the hotter your body temperature is.
tweak: Cryoxadone no longer deals toxin damage to jellypeople.
tweak: Purple Slime Extracts no longer have their sugar->slime jelly reaction (obsolete with extract grinding), and instead have a blood->regen jelly reaction.
tweak: Purple Extract's major activation by Luminescents now give regenerative jelly instead of tricordrazine.
/:cl:

Gives a better purpose to purple slimes, makes slime jelly something nice to give to chemistry for improved healing, and makes it so luminescents no longer kill themselves with cryoxadone and tricordrazine.

Also reduced the amount of frost oil given to luminescents in dark blue's activation, so they match cryoxadone's duration.

Fixes #34517
Fixes #34539

### CODE REVIEW

**Comment by TimeIsEndless** [comment]
there might also be an issue with the damage caused by the frost oil to jelly people. When i tested it i died from the burn damage even though i had cryoxadone in my body

**Comment by XDTM** [comment]
Slimepeople have a 3x multiplier on cold damage, i guess cryoxadone ain't enough. Now that it won't also kill you with toxins it might be worth using for the other types of damage, i guess.

**Comment by newfren** [comment]
wait how do you get slime jelly now

**Comment by XDTM** [comment]
Grinding any slime extract yields 20 jelly per use left

**Pull request merged**
