### PR TITLE
Ends grey tiding, Assistant now requires 50 hours as security

### PR DESCRIPTION
**Pull request by MrsTonedOne**
I don't like @optimumtact

### CODE REVIEW

**Comment by Buggy123** [comment]
Put me in the screenshot!

**Comment by Hatterhat** [comment]
local stonerman goes completely insane

**Comment by Bawhoppen** [comment]
We in for the ride with this meme

**Comment by ike709** [comment]
I do like this idea

**Comment by Kromgar** [comment]
Shouldn't this be a config? It would fuck everyone downstream

**Comment by Buggy123** [comment]
Too bad

**Comment by Shadowflame909** [comment]
oh no? oh yes? I wanted to type oh no earlier. So pretend I did before that tag was added.

**Comment by BDpuffy420** [comment]
I like this idea.

**Comment by deathride58** [comment]
I don't idea this like

**Comment by optimumtact** [comment]
I idea this don't like

**Comment by BDpuffy420** [comment]
I really....REALLY like this idea.

**Comment by Repukan** [comment]
Perhaps we could add assistant tokens for successfully completing objectives and such. This would also encourage people to try to complete their objectives if the way assistant tokens. 

Perhaps this method of rewarding players can be explained as workers in NT having faulty clones that aren't apt for the job hey usually play. Make players earn these dna strands, or Chromosomes, by attempting to green text.

**Comment by BDpuffy420** [comment]
THIS PR WAS AN INSIDE JOB, CODE ORANGE IS A LIE. AND IS THIS IDEA IS GOOD!

**Comment by Qustinnus** [comment]
i like this idea

**Comment by DaydreamPuppeh** [comment]
I don't like orange

**Comment by deathride58** [comment]
I don't like this idea.

**Comment by Armhulen** [comment]
oh no

**Comment by SmokingKilz** [comment]
Ah, TG github. I fucking love this place, never change.

**Comment by Buggy123** [comment]
You can edit my comments BUT I CAN EDIT THEM BACK!

**Comment by Plapatin** [comment]
i'd play sec for 50 hours to do this honestly

**Comment by Armhulen** [comment]
that's a weird way to say "I don't like this idea."

**Comment by MollyKristoph** [comment]
penis

**Comment by KomradeSpectre** [comment]
testmerge or noballs

**Comment by DaedalusGame** [comment]
Testmerge or no balls.

**Comment by Shadowlight213** [comment]
It seems that we now know that the best way to measure the reaction to a pr is not through comments, but through upvotes, as oranges just changes all comments to suit their opinion.
I see 8 upvotes and no downvotes. this pr is very well received.

**Comment by optimumtact** [comment]
please don't spam the same comment a billiong times it's not productive

**Comment by Cyberboss** [comment]
Dupes are triggering me

**Pull request closed without merging**
