### PR TITLE
[ReadyForReview]Correct organ manipulation step for robotic prosthesis surgery

### PR DESCRIPTION
**Pull request by MrROBUST**
[Changelogs]: # (Please make a changelog if you're adding, removing or changing content that'll affect players. This includes, but is not limited to, new features, sprites, sounds; balance changes; map edits and important fixes)

:cl:
wip: rework surgical operations for robotic prostheses
/:cl:

[why]: # (Please add a short description [on the next line] of why you think these changes would benefit the game. If you can't justify it in words, it might not be worth adding:) 

Fix for #30623
I need some ideas for mechanic limbs surgical procedure. Now: open the shell with screwdriver, mess with organs, close the shell with screwdriver.

### CODE REVIEW

**Comment by The-clown-known-as-Pepe** [comment]
IPC's when

**Comment by SgtxRootbeer** [comment]
Maybe allow the recipient to lock their shell for a more lengthy surgery process (not completely locked out, but slower to access) so you can't slip a guy and steal his heart in 2 seconds

**Comment by Supermichael777** [comment]
Multitool to jump the electronic bolts on the chest in five seconds (or robotics/surgery access for instant)

**Comment by MrROBUST** [comment]
@SgtxRootbeer it's still a surgery, so you need a guy to liying on the table, and drapes to start. And of course more steps.
I don't want allow self surgeries or any special abilities. Just want to give more sense to operations on mechanical limbs. Instead of incise skin or burn an incision, which you don't have, etc.

**Comment by AnturK** [comment]
This going anywhere ?

**Comment by MrROBUST** [comment]
Well, it's kinda works.

**Pull request merged**
