### PR TITLE
Adds materials to ore

### PR DESCRIPTION
**Pull request by Core0verload**
It makes sense for uranium ore to have uranium in it.

This update means you can feed sand and raw iron ore to autolathe. You can use crusher as ghetto smelter too.

Also updated plasma ore tech levels to match plasma sheet levels and adds glass amount to sandstone.

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
These shouldn't give the same amount of materials as a full blown refined sheet.

**Comment by xxalpha** [comment]
Yeah they should definitely not have the amount of material a refined sheet has. Make it like one fourth of the mineral material amount.

**Comment by Core0verload** [comment]
That's pointless. If one uranium  sheet contains 1kg of uranium and you can get one sheet by smelting ore, ore has at least 1kg too.

**Comment by xxalpha** [comment]
But crusher and autolathe should not be better than the ore refiner machine.

**Comment by Core0verload** [comment]
They wouldn't be. Autolathe is basically a molecular assembler/disassembler and it can extract materials from ore without losses. But autolathe is limited to glass and metal. Crusher can grind anything, but without upgrades it will loss some of the material. Ore smelter isn't limited to glass and metal, it automatically stacks sheets and it gives you mining points. 

Ore smelter is better anyway. I just added some new ghetto methods of smelting.

**Comment by Supermichael777** [comment]
:+1: this alows swarmers to eat minerals

**Comment by Jalleo** [comment]
Until ore becomes stackable normally this is a fine situation for it to be in imo with it being able to be manually inserted. Once its changed then we need a discussion on reducing the efficency of conversion For all standard machines that it can be inputted into. Excluding ore redemption and smelter

**Comment by Fox-McCloud** [comment]
>That's pointless. If one uranium sheet contains 1kg of uranium and you can get one sheet by smelting ore, ore has at least 1kg too.

There's a thing called efficiency. If you wanted to be completely realistic, then a single ore should contain 8000 materials because that's what you can get out of a single ore with a maximum efficiency ore redemption machine. It's obvious the ore redemption machine isn't meant to be a violation of conversation of matter, but rather become more efficient in how much of the materials it can extract.

raw ore would be pretty hard to extract from if it wasn't a specialized machine, specifically designed to extract said materials.

**Comment by Core0verload** [comment]
Conflicts are resolved. Ready to merge.

**Comment by Core0verload** [comment]
@Jordie0608, remove [Merge Conflict].

**Pull request merged**
