### PR TITLE
Janiborgs can now repair damaged hull platings

### PR DESCRIPTION
**Pull request by ATH1909**
## About The Pull Request

The "plating repair tool" has been added to the game in the form of a printable upgrade for janiborgs. It's a subtype of the cautery that can repair burnt or damaged hull platings, allowing floor tiles to be placed over them once again.

The upgrade that adds it to a janiborg's list of tools can be printed once the Cyborg Upgrades: Utility tech node is researched.

## Why It's Good For The Game

Janiborgs get floor tiles (and a crowbar), but have no way of dealing with burnt platings. Thus, what ends up happening is that, after fixing some flooring after a minor explosion, you'll often be left with one or two ugly, OCD-triggering untiled spots on the floor that you can't put a floor tile over because you don't have a welder. What makes these spots even more infuriating is that it would actually be BETTER if they had been broken down to just being space-exposed rods, because then you COULD place a floor tile on their tile.

## Changelog
:cl: ATHATH
add: The "plating repair tool" has been added to the game in the form of a printable upgrade for janiborgs. It's a subtype of the cautery that can repair burnt or damaged hull platings, allowing floor tiles to be placed over them once again.
add: The upgrade that adds it to a janiborg's list of tools can be printed once the Cyborg Upgrades: Utility tech node is researched.
/:cl:

### CODE REVIEW

**Comment by ATH1909** [comment]
I'd also like to give janiborgs rods so that they can repair breaches in the floor, but that might be considered to be too much of an encroachment on the engineering and standard modules' turf (plus, then you still wouldn't be able to repair horizontal breaches to space...).

**Comment by optimumtact** [comment]
This seems like power creep to me, engi borgs can already do this. Is it really so hard for you to to work with other people.

**Comment by ATH1909** [comment]
> This seems like power creep to me, engi borgs can already do this. Is it really so hard for you to to work with other people.

Is yelling at a human to "PLEASE FOR THE LOVE OF GOD USE THIS WELDER ONCE PLEASE I'M FUCKING BEGGING YOU" really "working with other people"?

**Comment by ATH1909** [comment]
Like, this seems more like an oversight than anything, considering that janiborgs have floor tiles in their tool list and can repair breaches to space (that still have rods), but can't repair damaged hull plating.

**Comment by LemonInTheDark** [comment]
The jannie borg already dabs on janitors, no need to make it dab on other borgs as well

**Comment by SkeletalElite** [comment]
> This seems like power creep to me, engi borgs can already do this. Is it really so hard for you to to work with other people.

calling it power creep implies that repairing a damaged floor so you can put a tile down, actually has a significant impact on the game.

**Comment by Doosteroni** [comment]
Think about the poor engiborgs dammit! How ever will they fill a niche if janiborgs take away their one job!

**Comment by IndieanaJones** [comment]
I hate engiborgs.

**Comment by GoldenAlpharex** [comment]
As much of a good idea it is at first glance, realistically, Janiborgs shouldn't be repairing hull breaches normally, it should be an engiborg's job. I don't think this PR is necessary, if you want to repair the station, go Engiborg, if you want to clean it, Janiborg.

**Comment by SkeletalElite** [comment]
> As much of a good idea it is at first glance, realistically, Janiborgs shouldn't be repairing hull breaches normally, it should be an engiborg's job. I don't think this PR is necessary, if you want to repair the station, go Engiborg, if you want to clean it, Janiborg.

This PR does not improve the ability of the janiborg to seal a hull breach. 
What Janiborgs can already do: Use their floor tiles to seal a breach IF the breach already has lattice on it. The janiborg does not have the ability to place lattices: 
What janiborgs can do after this PR: Repair damaged floor plates as in there is no breach on that particular tile, it's just damaged. Floor tiles are unable to be placed on a damaged plate, it has to be welded to full durability first.

The amount of "repairing" being done in this regard is so incredibly minor to call this taking the engiborgs job is ridiculous. It's less about fixing the station and more about re-tiling areas that have suffered minor damage.

**Comment by ArcaneDefence** [comment]
> but it can also be used as a crude lighter or cautery.

Literally acknowledging that it's allowing janiborgs to treat wounds to some extent in the description

**Comment by msgerbs** [comment]
Thought: Allow placing tiles on top of damaged floors? After all it is literally just visual, and 9 times out of 10 they just get left alone anyway.

**Comment by ATH1909** [comment]
> > but it can also be used as a crude lighter or cautery.
> 
> Literally acknowledging that it's allowing janiborgs to treat wounds to some extent in the description

Can't most other borg types also cauterize wounds? Standard, mining, engiborgs, and saboteur borgs have welders, mediborgs and syndicate mediborgs have cauteries, service borgs have lighters, and emagged secborgs have laser guns. That leaves... janiborgs, PK borgs, clown borgs, syndicate assault cyborgs, and non-emagged secborgs as the only borg modules that currently CAN'T cauterize slashing and piercing wounds. Oh, the horror.

**Comment by edgeotron** [comment]
i dont like this, encourages people to work together less going against the core gameplay

**Comment by moocowswag** [comment]
It gives jani borgs more control within their own job, making sure the floors are cleaned and tiled.

But maybe we should make this an upgrade rather than an innate module.

**Comment by JohnFulpWillard** [comment]
I'd be fine with this if we exchanged it for nerfing something else about the janiborg so they're not just the janitor-slayer, like making their floor buffer upgrade be an upgrade rather than getting it at the start

**Comment by BlueMemesauce** [comment]
why is everyone in this pr acting like this is gonna completely ruin the balance of the game all it does is let janiborgs repair broken floor plating

**Comment by ATH1909** [comment]
> It gives jani borgs more control within their own job, making sure the floors are cleaned and tiled to be visually appealing.
> 
> But maybe we should make this an upgrade rather than an innate module.

fuck it, sure, it can be an upgrade

give me a minute

**Comment by ATH1909** [comment]
it's now available as an upgrade for janiborgs instead of being there by default

let the merge conflicts commence

**Comment by cacogen** [comment]
What thing to bikeshed. Repairing damaged plating. Something that conveys zero gameplay value and is entirely aesthetic. It's not even a welder it's a specific tool to compliment their tiles and crowbar.

**Comment by Doosteroni** [comment]
> What thing to bikeshed. Repairing damaged plating. Something that has zero gameplay value and is entirely aesthetic. It's not even a welder it's a specific tool to compliment their tiles and crowbar.

I'm just gonna leave this here you fucking clown
#52171

**Comment by IndieanaJones** [comment]
I don't see why jannieborg can't have this.  It's kind of an odd thing to complain about, fixing some aesthetic dents and marks in the floor.

**Review by SpaceManiac — APPROVED** [review]
Seems fine for now, can be tweaked if it turns out bad somehow

**Comment by optimumtact** [comment]
wow, merging powercreep

**Pull request merged**
