### PR TITLE
[MAP] Removes Deathtrap Spawn on Space Battle Away Mission

### LINKED ISSUE #13615: Bluespace artillery mission spawn bug
You get spawned in random locations, often with enemies that you cannot kill.

Can you fix this and make it spawn you in the dorms room where you're meant to be spawned?
Here is the correct spawning area:
http://puu.sh/lUuSY/9ab5abdaa9.jpg

### PR DESCRIPTION
**Pull request by Steelpoint**
Simple change, this removes two spawn points that put the player directly in the same room with multiple NPC Nuke Ops, giving them nearly no chance of defending one self.

There are several other dubious spawn points that put the player in a small room with the only exit next to a squad of Ops, but at least they give the player a chance to get their bearings.

Fixes #13615

### CODE REVIEW

**Comment by Jordie0608** [comment]
Might as well just remove those ships entirely, the main ship is the focus and I can't image many would want to jump into space to confront all the ops on the shuttles.

**Comment by Steelpoint** [comment]
Good point I'll look into it.

**Comment by KorPhaeron** [comment]
I put a shuttle/sleeper/drop pod/chair to account for every single syndicate mob on the map, please do not ruin my detail.

I agree with removing the spawn point for now but I hope to do a more complete overhaul once the freeze is over

**Comment by tkdrg** [comment]
this fixes #13615 apparently, please add that to the OP

**Comment by Steelpoint** [comment]
Fine I'll leave the changes to just the two bad spawn points.

**Comment by Shadowlight213** [comment]
Hugbox

**Comment by Steelpoint** [comment]
Insert buzzword here.

These two spawns place you into a confined room surronded by almost a dozen NPC Nuke Ops, their damage output is insanely high and frankly you get no chance to even see what's happening before you die.

**Pull request merged**
