### PR TITLE
Replaces all roundstart TTVs with "safe" versions

### PR DESCRIPTION
**Pull request by coiax**
:cl: coiax
rscadd: For safety purposes, all Toxin research must now be done with
safe tank transfer valves, which will only function on the Toxins
Testing Site. TTVs with no safeties can be ordered from cargo as before.
Please do not expose the circuitry on safe TTVs to high amounts of
electromagnetic current or illegal technology cards, as this will
violate your warranty.
/:cl:
- All TTVs on the maps are now "safe tank transfer valves" which will not toggle except on the testing site
- These safe versions can have their safeties disabled with an EMP or emag
- Safe TTVs can be ordered from cargo, 1000 points for 2
- Unsafe TTVs remain orderable from cargo, 6000 points for 2 as before

### CODE REVIEW

**Comment by Shapsy** [comment]
but why, not every single dangerous thing in the game needs to be locked behind an emag

**Comment by optimumtact** [comment]
Helll no

**Comment by Shadowlight213** [comment]
>instant close
Uhh. Don't we leave shit open for at least a day to get opinions? Instead of closing a pr due to personal opinion?

**Comment by optimumtact** [comment]
You can come back with a game poll showing at least a majority positive opinion before I'll even bother causing the shitstorm this pr will create

**Comment by coiax** [comment]
Firing pins, secborgs, bomb cap, cults one through seventeen, HoS' personal laser. Stop shutting down debate.

I don't even care about this issue, but you've made me care by treating me like goofball. That hurts, man.

**Comment by optimumtact** [comment]
Whatever man, if you wanna get yelled at it's on your head.

We're not merging this without a poll

**Comment by coiax** [comment]
Now that this PR is back open, I can go back to not caring about this. Literally just coded what people talked about in IRC; I have no personal attachment.

**Comment by PKPenguin321** [comment]
and to think that at one point "hugbox" was hardly more than just a meme

**Comment by TechnoAlchemisto** [comment]
bad because makes bombing impossible outside of traitor

**Comment by LatD** [comment]
You can still order normal TTVs from cargo or just take one of these to the room next to toxins and cause an EMP to disable the safety

**Comment by TechnoAlchemisto** [comment]
hugbox meme

**Comment by Zilenan91** [comment]
>Literally just coded what people talked about in IRC; I have no personal attachment.

Man no wonder people say coders don't play the game if this is true

**Comment by coiax** [comment]
I'm not threatened by this "slur" that I don't play the game, and I certainly have no personal attachment to Toxins bombs, either as an antagonist or protagonist. If you find it difficult to believe that I can code out something based on ideas floated in a discussion, then well, tough.

**Comment by Zilenan91** [comment]
Oh boy it seems someone is deleting comments on a pr that's literally a fucking meme in the first place

**Comment by optimumtact** [comment]
I'm deleting baseless comments that add nothing

i will monitor this PR very carefully, the forum admins may not give a shit about quality of discussion but I do.

**Comment by d3athrow** [comment]
cuddle station 13

**Comment by Aranclanos** [comment]
>I'm deleting baseless comments that add nothing

but what is a comment that adds something and what is one that adds nothing? Disagreeing does not add nothing? What claims do you have to be the master of the worth comments?
Does this comment add something? Or it's just many words of nothingness? Who is in charge of deciding that?

**Comment by Durkel** [comment]
Aren't the bombs meant to be used for mining, I know they never are, but isn't that the reasoning to having toxins in the first place? That and ordering normal valves is never going to happen ,you might as well just announce on the common channel you're going to kill people.

**Comment by Fox-McCloud** [comment]
one of the most retarded PRs I've seen in a long time.

This pretty much means that toxin bombs are useless outside of traitor. TTVs shouldn't be limited to traitor and only traitor, not to mention, I don't believe they should be "hugboxed" either.

This would be akin to making it so that only traitors can make chem grenade or mix dangerous chems in and of themselves----or the singularity couldn't be released (or atmos flooded) unless an emag was involved.

Sorry, big :-1: from me.

**Comment by clusterfack** [comment]
Great PR surprised you didn't do it earlier

**Comment by LatD** [comment]
I see this more like preventing those sub-5-minute maxcap bombs. EMPs are really easy to cause in science. You can do that in R&D, experimentor or xenobio so all this does is make the bomb preparations a little slower than 5 minutes.

Better comparison would be to have a normal gatling gun at test range round start and then complain when the normal firing pin is getting turned into firing range test pin.

**Comment by Shadowlight213** [comment]
My main complaint with them was mainly the maint door that toxins had. I've talked to both sec and toxins players and they've both told me that once the ttvs leave toxins, there's nothing you really can do about them.
Toxins sort of suffers from the same issue rnd did, where it's hard until you discover the correct bomb mix, and then afterwards it's easy to get max caps.
I mean, the only way to stop it is for sec to raid toxins early on, before they do anything, which is kinda metagaming.
Once bombs are set, they are basically a huge fuck you instakill and destruction in a large area.
It's not even size restricted like gibtonite or syndie bombs. You can carry them in backpacks.

**Comment by Bawhoppen** [comment]
I don't really care about this PR but Orange's is being a massive shitter by thinking he can just instaclose it because he doesn't like it, then micromanaging it after it was force reopened just because he is against it. (Controversial tag exists for a reason)

**Comment by MMMiracles** [comment]
You know whats really annoying?

Everytime EMP comes up when it comes to a counter/work-around, its either "EMPs are too rare to actually be used" or "you can just EMP x for the same effect so all antags have it".

seriously people for fucks sake make up your mind.

Security can be staffed in science and even has a camera to remotely check out every part of the department, let alone the HoS/captain/RD should probably be making sure they have the names of anyone who worked toxins when valves suddenly go missing.

i'll just leave it off with this:

H U G B O X
U              O
G              B
B              G
O              U
X O B G U H

**Comment by Man-Shroom-** [comment]
If people are concerned about bombs not being found when outside of toxins, we could maybe replace Pugley III with a bomb sniffing dog? or give the dog to sec idk

**Comment by KorPhaeron** [comment]
>I'm deleting baseless comments that add nothing

Why even have the PR open if not for the entertainment value?

**Comment by optimumtact** [comment]
good question

**Comment by Man-Shroom-** [comment]
but i can still do this orange man

**Comment by Cheridan** [comment]
haha what

**Comment by Core0verload** [comment]
@coiax, I like your anti-nerf style. Opening ridiculous nerf PRs for any shitty nerf idea, then getting them closed before someone will turn that ideas into serious nerfs.

**Pull request closed without merging**
