### PR TITLE
deep fryers are quieter now...

### LINKED ISSUE #33592: Deep-fryers are too loud.
literally the loudest looping sound rn

### PR DESCRIPTION
**Pull request by ghost**
i've had a lot of trouble with the volume myself too yeah, it's louder than the supermatter AFTER there was a pr to lower it's sound by god

fixes #33592

### CODE REVIEW

**Comment by optimumtact** [comment]
you already are on my friends list

**Comment by Armhulen** [comment]
it wasn't like that this morning

**Comment by Xhuis** [comment]
geT YOUR HUGBOX OUT OF MY KITCHEN!@!!!!!!!!!!!!!!!!!!!!

**Comment by Armhulen** [comment]
geT YOUR FRYERS OUT OF MY EAR!@!!!!!!!!!!!!!!!!!!!!!!!

**Comment by Xhuis** [comment]
🍟 📣

**Pull request merged**
