### PR TITLE
[MAP] Continuation Of Armoury Map PR + Magazine Removal

### PR DESCRIPTION
**Pull request by Steelpoint**
This is a continuation of Pudl's mapping PR located here: https://github.com/tgstation/-tg-station/pull/12021

It was closed due to merge conflicts compounding upon each other.

This PR is identical to https://github.com/tgstation/-tg-station/pull/12021 aside from the following.
- No Atropine Medipens, for now at least.
- Fixes several problems from the PR, such as...
  - Wrong Shotguns used: Fixed so Armoury uses Riot Shotguns, not stock Shotguns.
  - Incorrect Tagging: Armoury lockers had wrong number assignments, locker 2 got all the contents of locker 1 and 3 for example
- Addition of a Medkit to the armoury. Someone keeps removing it whenever I add it for some reason.

In game image (not including new Sec Auxiliary Storage)
screenshot 2015-10-03 21 20 30

### CODE REVIEW

**Comment by Steelpoint** [comment]
Also this PR removes the excess Auto Rifle magazines from the armoury.

**Comment by Shapsy** [comment]
I'm not a fan of putting the guns in lockers as opposed to racks because you can't tell if everything's still there at a glance

**Comment by Dorsisdwarf** [comment]
Controversial because the last PR was.

**Comment by Profakos** [comment]
How about using the glass windowed gun locker in guncase.dm, which shows how many guns are still in them.

**Comment by Zilenan91** [comment]
Are the lockers all access?

**Comment by KorPhaeron** [comment]
@zilenan91

Armory

**Comment by Shapsy** [comment]
...so you can't grab any guns if you don't have armory access, even if you went through the trouble to break in?

**Comment by Bawhoppen** [comment]
:-1: Changing shit for the sake of changing it. Old armory had a good feel to it, looked nice, guns were open, and was perfectly balanced. However this just looks like 'old armory was old looking, need 2 update it and destroy the balance at the same time'
Also you're giving them 5 steelrifles still?

**Comment by Jalleo** [comment]
It was confirmed armory access is bad on lockers rem

**Comment by SconesC** [comment]
"Old armory looked nice"

Rack holocaust was shit

**Comment by Nanotransistor** [comment]
Yeah lockers are not bad. Remove the lock and we are good.

**Comment by Zilenan91** [comment]
Yeah the reason the button that is there currently is all access is so antags could steal the guns. The lockers need to either be racks or openable by everyone.

**Comment by Steelpoint** [comment]
I only copied the PR as it was.

I like the lockers but I'll remove the access requirements.

**Comment by Zilenan91** [comment]
If you want a stylish way to display the guns, I know Hippie has these gun case things in their armory that they load their eguns and riot shotguns in. We might be able to incorporate that for our auto rifles and save space.

**Comment by SconesC** [comment]
we have them but they look awful

I actually suggested them to allura in the initial PR but there was an issue with them

**Comment by tuypo1** [comment]
problem with a glass locker is you still have a bunch off stuff piled up there you can technicly see them but to be able to make sense of it all you need to right click or alt click or something

**Comment by SconesC** [comment]
please stop posting on git i can only take so much second hand brain damage

**Comment by Steelpoint** [comment]
I can do the metal/glass gun lockers, only problem I can see is that you can only close the lockers if you hold a non-insertalbe item in your hand.

Let me work on something.

**Comment by Steelpoint** [comment]
Well good news is I can get them to work, I can spawn in these gun lockers filled with a pre-set firearm, up to four guns can fit inside one gun locker.

**Comment by Dorsisdwarf** [comment]
@Steelpoint Can you reduce the number of steelrifles/tactical kits in the armory to be in line with all the other gear?

**Comment by Shapsy** [comment]
I still personally like racks, they make sense for an armory, what's wrong with racks?

**Comment by GunHog** [comment]
I am not a Sec player, so I do not understand how those people think. I am of the same thinking of Shaps here: Why are you against racks? It makes sense to me. You can see the weapon you want and easily click it for pickup. 

Lockers add another click to the mix. My favorite armory design is from Baystation, where the equipment is nearly compartmentalized and displayed. Why do you prefer lockers?

**Comment by Steelpoint** [comment]
Sorry I have not been able to post, net in my state died on the arse.

I've got some proposals and change, but it'll have to wait.

I did make it that all the guns can spawn inside a gun case. It's neat and has no access requirements.

I'll look over the design, if you want bays design then say so

**Comment by SconesC** [comment]
Racks look fucking gross

Gunhog the bay armory requires another click as well because if the gun is under the stack you have to click open the windoor

**Comment by Bawhoppen** [comment]
We need like proper gun racks, like this


I'm sure steelpoint would approve of giving security that many guns too.

**Comment by Bawhoppen** [comment]
Also security has grey riot shotguns, not wooden color ones

**Comment by tuypo1** [comment]
no lockers

and yes stealpoint would love that many guns

**Comment by Steelpoint** [comment]
Ok Internet's back.

Here are my proposed changes, in image formet.

-------------

First, a new Ablative Helmet, to combo with the Ablative Vest.

screenshot 2015-10-05 01 28 56


-------

Second, a newer armoury based off of Baystation. (Ignore the locked Tac Lockers or the gun cases, they're being replaced.

screenshot 2015-10-05 01 30 55

**Comment by Bawhoppen** [comment]
Being replaced with racks or normal lockers? Racks are better than lockers still IMO

**Comment by Steelpoint** [comment]
Its being replaced with racks but I can't be asked to load up the game just for the updated rack image.

The auto rifles are in their own room due to them being tac equipment, I might even look into adding a form of webbing to hold magazines or small items. Similar to Bay and ACM.

**Comment by Bawhoppen** [comment]
I still think you should only give them 3 steelrifles, in order to be consistent with the eguns/lasers and such. Otherwise I could live with this, but maybe only 1 set of ablative/helmet.

**Comment by Bawhoppen** [comment]
Also leave tasers inside the armory itself, not the warden's office for balance.

**Comment by Jalleo** [comment]
Looks better but i want a proper image showing how it looks compared to edge of perma and sec equipment room.

**Comment by Miauw62** [comment]
JUST PUT THE AUTORIFLES ON A RACK ALONGSIDE ALL THE OTHER GUNS

PLEASE

**Comment by Steelpoint** [comment]
B-but then its not symmetrical.

--

Also the table in the Tac Room has a empty magazine and six 9mm bullets, for that cool appearance.

I also have to put the Space Suits somewhere, likely in that small grille area next to the Tac Room.

**Comment by Nanotransistor** [comment]
Hmm not sure about those helmets, and there being two sets of ablative. The armor is already strong enough, specially if paired with a riot shield. Other than that, armory looks good.

**Comment by Miauw62** [comment]
here's an idea: dont mix your balancing and map prs

**Comment by pudl** [comment]
I don't like the idea of my design being used unless the lockers go to use, since the PR was made specifically for lockers, and the reduction in size of the armory was just a side effect of that action.
Of course I can't stop you or anything, but that's just my request.
The armory windows, in my PR, weren't average windows as you put in your PR. They looked brighter because they were r-windows stacked on top of a 4 r-pane sandwich, for more security. So you'll want to either make it normal r windows or the double window thing I did.

**Comment by Cookiesndip** [comment]
So long as the lockers are all-access or replaced by racks, it's fine. Definitely an improvement from the current xbox hueg armory. HOWEVER: tasers should NOT be warden-side in a corner. That's what you actually need in an armory fight, especially as a traitor, and it's in the least accessible area possible, and, if you're breaking in through space, you have to go through a minimum of two rwalls or one rwall + rglass in front of every officer in the brig to get them. Put them in a fifth rack where you're standing instead, or etend the ion/ablative racks by one and put it there.

Though a helmet and a vest for ablative miiiiiiiiiight be OP.

Also: can you press the button to get into the steelrifles area from inside or outside? Just thinking in terms of nuke ops bombing the armory etc. Are there walls under the grilles, and do they extend into that dark area (i.e. can you cut a bunch of grills and hack in behind the riot armor).

**Comment by pudl** [comment]
I don't want unlocked lockers, that makes it redundant.

**Comment by Bawhoppen** [comment]
Lockers just look stupid, while racks make sense in an armory

**Comment by GunHog** [comment]
Is there going to be a decision on this soon?

**Comment by Bawhoppen** [comment]
Yea I don't like this, I also don't like the idea of ablative helmets, because I think it should be more of a vest you put on if you're fighting energy weapons, not a full set of armor, and only give them 1 ablative anyways. Show us an updated picture and then we'll talk.

**Comment by pudl** [comment]
I still don't want my design being used.

**Comment by Bawhoppen** [comment]
Yea I think we should just close this. Until we have a better design, we'll use the armory that functions well as is.

**Comment by Steelpoint** [comment]
I'm using my Bay style design, I just have to get around to finishing it off.

**Comment by Steelpoint** [comment]
Also the whole reason I did this PR was due to people saying they dislike the current armoury design, so is this a case of dammed if I do, dammed if I don't?

**Comment by Bawhoppen** [comment]
I'm no expert, but I'd say make the bay design a different pr, along with the ablative helmet to be a pr aswell on it's own.

**Comment by Anonus** [comment]
don't make an ablative helmet I will punch you

**Comment by Bawhoppen** [comment]
well he already did, it needs to be a seperate pr though IMO

**Comment by Steelpoint** [comment]
It isn't even on this PR yet, I simply posted it as a future proposal.

**Comment by Steelpoint** [comment]
Can I get this reviewed and accepted or denied, at minimum I just want to remove the excess magazines but I thought the map change was a good one.

**Comment by Steelpoint** [comment]
screenshot 2015-10-07 14 28 23

**Comment by Bawhoppen** [comment]
Don't leave the tasers in the warden's office, and only give them 1 ablative, make it have only 3 steelrifles OR give 4 lasers/eguns for consistency

**Comment by Bawhoppen** [comment]
Also make the walls facing south in the tactical gear room be non-rwalls, remove the rwall next to the suits aswell

**Comment by Bawhoppen** [comment]
I retract my statement about increasing egun and laser amount to 4, just make there be 3 steelrifles.

**Comment by Steelpoint** [comment]
screenshot 2015-10-07 14 39 31

**Comment by Bawhoppen** [comment]
You ignored my point about the rifles and the ablatives.

**Comment by GunHog** [comment]
Acceptable :+1: Would bomb

**Comment by Steelpoint** [comment]
screenshot 2015-10-07 14 56 13

**Comment by Bawhoppen** [comment]
instead of the emergency tanks, give them an actual tank dispenser maybe, otherwise 10/10 best change

**Comment by Jalleo** [comment]
Its better to have it as emergency ones than a tank dispensor.

**Comment by Bawhoppen** [comment]
Why would you say that?

**Comment by Jalleo** [comment]
One because the tank dispensors have way too many tanks in them and two it removes independance of security from atmos on spacewalks.

**Comment by Bawhoppen** [comment]
I dunno, real tanks are pretty common in o2 lockers, maybe just leave 2 on the table.

**Comment by Steelpoint** [comment]
There are two on the table.

**Comment by Bawhoppen** [comment]
I mean leave real o2 tanks, not emergency ones

**Comment by Dorsisdwarf** [comment]
I actually like this new design, but why is there a narrow backroom with the spacesuits in to let traitors steal all sec's spacesuits undetectably?

**Comment by Steelpoint** [comment]
There's no where else to put the suits and I really want this to be merged ASAP.

**Comment by Miauw62** [comment]
if raz can merge shitty prs fnr i cant get in trouble for this

**Comment by Anonus** [comment]
how did you manage to make a design even worse than it is currently
the rifles are far enough away from the warden's office that, if you get in, nobody will hear you
also that's a fuckton of light tubes you don't need than many tubes come on

**Comment by pudl** [comment]
Steelpoint, do you just genuinely not understand how buttons work at all?

**Comment by tuypo1** [comment]
whhhhattt

why why does my poor armory keep getting worse why steelpoint you don't even play warden you play hos

**Comment by GunHog** [comment]
This one was reverted by: https://github.com/tgstation/-tg-station/pull/12202

**Pull request merged**
