### PR TITLE
Adds a lavaland variant of wings.

### PR DESCRIPTION
**Pull request by Shadowlight213**
wings

Sprites partially credit to kor and his gf, since I basically put the watcher wings on a human with some edits.

New lavaland wings provide protection from lava when you are flying as well as normal effects.
The lavaland flight potion has been changed to this new type.

The new wings have no closed icon as they retract into your back.
:cl:
tweak: The lavaland flight potion has absorbed the ambient energies of the planet and become something more sinister
/:cl:

I'm debating on if I should add ash storm immunity as well, but I'll leave the decision up to @KorPhaeron 

Merge token #19517 when it's merged.

### CODE REVIEW

**Comment by Shadowlight213** [comment]
>travis fails completely unrelated to my pr

Nice.

**Comment by yackemflam** [comment]
Wait, why does this give you lava protectionif the other doesn't?

**Comment by Shadowlight213** [comment]
Because ikarrus flew too close to the sun.
Those have feathers, these don't..

**Comment by Durkel** [comment]
ugly as fuck tbh.

**Comment by jughu** [comment]
Looks like some miner ripped the wings off the watcher just to look cool

**Comment by Kromgar** [comment]
It would be cool if these actually looked like wings but they dont

**Comment by Shadowlight213** [comment]
I'm sorry. This is literally codersprites basically since I waited for like two months for sprites and never got them.

**Comment by Shadowlight213** [comment]
Sine people are saying the sprites are really shit. I guess I'll close it.

**Pull request closed without merging**
