### PR TITLE
Fixes the soul scythe having no sell value

### PR DESCRIPTION
**Pull request by Gboster-0**
## About The Pull Request

Whilst i was working on a PR for monke station i noticed that yall never changed the spellblade for a soulscythe in cargo code, so it was worth nothing and it never got noticed until i came along (no suprise since lets be honest, who the hell sells bubblegum loot anyways?

So here's the 1 line fix to make the soul scythe worth a few pennies from selling.

## Why It's Good For The Game

ive heard bugs are bad

## Changelog

:cl:
fix: fixed the soul scythe's sell value in the cargo shuttle
/:cl:

### CODE REVIEW

**Comment by Gboster-0** [comment]
whoops, a fuck-up

**Comment by Gboster-0** [comment]
well made this issue instead (https://github.com/tgstation/tgstation/issues/76829) since i have added 296,281 lines more than i intended on accident saying what the issue is in precision. Excuse me as now im going to bury my head in sand

**Comment by nikothedude** [comment]
What in the God damm

**Comment by LemonInTheDark** [comment]
it's ok this happens decently often don't worry about it

**Comment by dessysalta** [comment]
bookmarking this

**Pull request closed without merging**
