### PR TITLE
Adds screwdriver use sounds when opening panels on doors & vending machines

### LINKED ISSUE #22790: Vending Machines and Doors no longer make tool noise when you use a screwdriver on them
- See Title
- Also applies to the hand drill
- Air Filters and Light Fixtures (two that I checked) are unaffected, if that helps

### PR DESCRIPTION
**Pull request by Arianya**
:cl: Arianya
fix: Doors and vending machines once again make a sound when you screwdriver them.
/:cl:

Fixes #22790 

**Reasoning:** Doors should make a sound when screwdrivered because door hacking should be noisy and noticeable. I have no strong feelings regarding vending machines, I'm just adding it because it was mentioned in the issue.

I took a quick look but couldn't spot anything else that should have the sound that doesn't. Feel free to let me know if there is!

### CODE REVIEW

**Comment by Arianya** [comment]
Also, please tell me how to stop github from displaying the "Merge remote-tracking branch" commits ;~;

**Comment by GunHog** [comment]
You could run a 'squash' to do this, but there is really no need, all that matters in the end is the code difference.

**Comment by xxalpha** [comment]
You can't and they don't matter.

**Comment by Cyberboss** [comment]
If you get to a point where you have no open PRs, delete and recreate your fork

**Comment by RemieRichards** [comment]
@xxalpha "you cant"

Uh, it's called a rebase.

**Comment by Arianya** [comment]
I forgot to mention, theres one minor possible issue, which is that theres no usedelay on screwdrivering doors, so one can in theory just spam click to make the sound play over and over again, but I figure this isn't a huge concern since you'll most likely get batoned for doing so obsessively.

**Comment by Cyberboss** [comment]
Its been like that for literally forever, don't change it

**Comment by Haevacht** [comment]
Could spam the noise to draw someone inside to open it to stop you spamming it then dunk them too. Emergent gameplay!

**Comment by Mervill** [comment]
Definitely a Berenstein Bears situation. I swear I've heard the sound on vending machines but aparently that's never been a think.

Nice Job

**Comment by Arianya** [comment]
@Mervill It probably should be on anything you can screwdriver tbf, consistency issue, as Lzi put it.

**Comment by Mervill** [comment]
Yeah ... im not sure why that's not already the case

**Comment by improvedname** [comment]
This is not a fix
Itsa feature!

**Comment by Cyberboss** [comment]
It worked before, something broke it.

**Comment by improvedname** [comment]
Yeah i thought so firstly i thought it was intended because im pretty sure it was like this for a long way but then i thought aanout 2014 and remembered it

**Comment by xxalpha** [comment]
It's true, these sounds never played for vending machines.

**Comment by Mervill** [comment]
Does this also fix the hand drill sound?

**Comment by Arianya** [comment]
@Cyberboss play_sound, but yes.

@Mervill Should do, the hand drill is just a subtype of screwdriver. Whether it uses the screwdriver or handdrill sound effect is something I've not tested.

**Comment by Mervill** [comment]
mergebeg reeeeee

**Pull request merged**
