### PR TITLE
fix chain 2h

### LINKED ISSUE #17924: dual wielding chainsaws
Possible to dual wield chainsaws by having someone throw them and having the other person catching them.  This doesn't take the extra arm slot so you have a free hand and can repeat the process.

[Admins]: # (If you are reporting a bug that occured AFTER you used varedit/admin buttons to alter an object out of normal operating conditions, please verify that you can re-create the bug without the varedit usage/admin buttons before reporting the issue.)

### PR DESCRIPTION
**Pull request by Iamgoofball**
fixes #17924

### CODE REVIEW

**Comment by phil235** [comment]
You're not fixing the actual  issue. There's plenty of other places who uses put_in_active_hand() (and similar procs) to put items in your hand. The code in twohanded/required/attack_hand() (https://github.com/tgstation/tgstation/blob/a2aa3df3580f3e968ec9c7ce222a9b4dbf017a13/code/game/objects/items/weapons/twohanded.dm#L139) need to be moved to twohanded/required/put_in_active_hand() or something.

The only change necessary is probably to do "if(put_in_active_hand(I))" so we only catch the item if that succeeds.

**Comment by Iamgoofball** [comment]
that works

**Comment by Iamgoofball** [comment]
there you go

**Comment by phil235** [comment]
"The only change necessary in carbon/hitby()" not "The only change necessary"

**Comment by Iamgoofball** [comment]
fuq

**Comment by Man-Shroom-** [comment]
you'll get those tokens someday goof

**Comment by optimumtact** [comment]
Goof fix somethign at least

**Pull request closed without merging**
