### PR TITLE
vampires cant use mirrors

### PR DESCRIPTION
**Pull request by Fikou**
## About The Pull Request

vampires cant use mirrors

## Why It's Good For The Game

it breaks my immersion

## Changelog
:cl:
fix: vampires cant use mirrors
/:cl:

### CODE REVIEW

**Comment by 81Denton** [comment]
incredible

**Comment by itseasytosee** [comment]
based

**Comment by 81Denton** [comment]
also while this technically falls under the race content rule, I'll allow it

**Comment by Shadowflame909** [comment]
Wtf is this nerf PR

hello maintainers?? hello???

**Comment by knacker48** [comment]
devastating nerf for vampires

**Comment by CRITAWAKETS** [comment]
They should punch the mirror if they try to use it regardless of intent.

**Comment by ExcessiveUseOfCobblestone** [comment]
WHEN WILL MY REFLECTION SHOW

WHO I AM

INSIIIIIIIIIIDDDDDDDDDEEEEEEEEEEEEE

**Comment by ATH1909** [comment]
Make sure that they can still use magic mirrors, and I think this PR will be great.

**Review by Cyberboss — APPROVED** [review]

**Comment by Taylorkills2** [comment]
More vampire content is good, hopefully this doesn't stop Pride Mirror from being used, otherwise a bit of a noob trap.

**Comment by FantasticFwoosh** [comment]
This is why we would need peer-to-peer barbering. Just don't nick yourself with the razor blade infront of them.

**Comment by ATH1909** [comment]
> More vampire content is good, hopefully this doesn't stop Pride Mirror from being used, otherwise a bit of a noob trap.

Fikou has confirmed that that is intended, which is not something that I like.

**Comment by Shadowflame909** [comment]
Magic Mirrors peer into your soul to find out your dream appearance. They aren't really reflective surfaces.

Rejected!

**Comment by optimumtact** [comment]
I don't want vampires in the game

**Comment by Shadowflame909** [comment]
Vampire race removal PR confirmed

**Comment by itseasytosee** [comment]
RIP Halloween vampires
Might as well remove flymen at this point too

**Comment by Tharcoonvagh** [comment]
Remove magic

**Pull request closed without merging**
