### PR TITLE
Hangover spawns are dynamically generated instead of being placed on maps

### PR DESCRIPTION
**Pull request by Archanial**
## About The Pull Request

Hangover spawns are dynamically generated at the start of the round instead of being placed on the map.
`get_safe_random_station_turf` is now `get_safe_random_station_turfs` and can return list of turfs if needed.
Removed hangover spawners icons as well.

## Why It's Good For The Game

Less bloat in mapfiles

## Changelog

:cl:
code: hangover spawners are now dynamically generated
refactor: refactored get_safe_random_station_turf to get_safe_random_station_turfs
/:cl:

### CODE REVIEW

**Comment by MrMelbert** [comment]
On one hand, I appreciate this from a maintainability standpoint. 

On the other hand, it will result in hangover spawns being placed in places which are pretty unfitting. Currently hangover spawners are a mixture of randomly placed and placed deliberately in places (no spawns in the engine room or medbay treatment center. Lots of spawn in dorms and bar).

**Comment by timothymtorres** [comment]
This is great.  I hated seeing all the hangover icons spammed needlessly while I was mapping.

**Comment by MMMiracles** [comment]
this sucks because it directly takes away my ability to map funny hangover locations

**Comment by Archanial** [comment]
> it will result in hangover spawns being placed in places which are pretty unfitting

The code runs on areas and currently works on hallways. Bar or other areas could always get added.

**Comment by Wallemations** [comment]
> > it will result in hangover spawns being placed in places which are pretty unfitting
> 
> The code runs on areas and currently works on hallways. Bar or other areas could always get added.

If you're going to try and replace it with something automated, then at least make some version of the proc that has bar & dorm spawns weighted to be higher, just so it doesn't lose that effect.

**Comment by Archanial** [comment]
The closest to "weighted" version of this proc is running it several times with different areas.

**Comment by Mothblocks** [comment]
@tgstation/maptainers Do you want this or do you prefer the more specific control?

**Comment by Archanial** [comment]
This isn't dead, I just don't want to fix conflicts when it'll conflict with almost every map merge

**Comment by EOBGames** [comment]
> @tgstation/maptainers Do you want this or do you prefer the more specific control?

I've done a spot of discussion with @Maurukas and I worry that the answer isn't gonna make things much clearer-
We agree that hangover spawns are a currently tedious part of mapping and do require a lot of manual placement, which is a fair addition to the barrier of entry for station mapping, both making a new map and large-scale editing of an existing map.
We also agree that making this entirely a code thing does strip away significant control from mappers for placing funny hangover spawns- which is ultimately (in my opinion) what makes the hangover trait worth having.

To this end, I think there's a solution that might satisfy both sides of the equation, though I'm not sure how much work it is on the code side of things: making the majority of the system auto-generated (so that there's no requirement to carpet the bar with hangover spawns manually) but with a bespoke spawner to allow mappers some granular control over particularly funny hangover spawns (so we can still have a guy spawn on top of a tower or whatever).

If that can't be arranged, neither of us feel strongly enough about the PR to block it, but neither of us are particularly happy about it, either.

**Comment by Archanial** [comment]
In my opinion it's better to stick to one approach.

The "funny spawns" will still happen, although they will be significantly less likely.

I don't really understand what you mean by "bespoke spanwer" in that context. 

In my opinion it takes away very little from mappers and should've been done this way from the start.

**Comment by cacogen** [comment]
Why not just leave the spawner in and let mappers place it if they want?

**Review by Mothblocks — CHANGES_REQUESTED** [review]
I'm going to buff the maptainer's hesitancy then and ask that you support both. This could potentially done through a basic n% chance to get a random spawn, otherwise pick a pre-determined landmark.

**Comment by timothymtorres** [comment]
@EOBGames @Mothblocks Another possible solution is to make it a config option in the map json file.  If it's enabled then the hangover is selected from one of the manually placed spawners.  If it's disabled then it's dynamically generated.

**Pull request closed without merging**
