### PR TITLE
Auto Rifle Alt Mag Sprites

### PR DESCRIPTION
**Pull request by Steelpoint**
This is a trial PR to see if this feature is well recieved enough to expand to all other similar ammo.

This PR adds a small sprite to identify what kind of ammo is loaded (initally) into a Auto Rifle magazine. 

Currently, these are.

* Standard - No Colour
* Incendiary - Red
* Uranium Tipped - Green 
* Armour Piercing - White

mags

:cl: Steelpoint
add: Auto Rifle alt ammo mags (AP, Incendiary, Uranium Tipped) now have a coloured stripe to denote them.
/:cl:

[why]: # (Please add a short description [on the next line] of why you think these changes would benefit the game. If you can't justify it in words, it might not be worth adding:)

### CODE REVIEW

**Review by FantasticFwoosh — COMMENTED** [review]
Why is any of this here? Did you not git cherrypick your individual commit or something?

**Comment by Steelpoint** [comment]
No idea. I guess I'll have to re-download the code at some point.

**Comment by FantasticFwoosh** [comment]
Im literally just beggining to really get into cli but the git cherrypick command might help you if you are more competent than i am with cli

http://blog.asquareb.com/blog/2014/06/19/making-a-git-pull-request-for-specific-commits/

**Comment by GunHog** [comment]
Try running this in your git shell:
`git checkout master` Switch to master
`git fetch upstream` Get latest master
`git reset --hard upstream/master` Set local master to upstream master
`git push origin master --force` Sync your update to the website

**Comment by Steelpoint** [comment]
I don't have git shell. 

Seems too annoying to figure out, I'll just redownload the code one day.

**Comment by FantasticFwoosh** [comment]
Though its a impractical solution, it comes with github desktop https://desktop.github.com/

**Comment by Niknakflak** [comment]
>not using git shell
>too annoying to use

Everyone point and laugh

**Comment by Steelpoint** [comment]
Who do I beg to merge this?

**Comment by GunHog** [comment]
Do not beg. Be patient and wait for a maintainer to come to you. Begging may actually _decrease_ your chances of a merge by making one of them annoyed at you.

**Comment by Steelpoint** [comment]
Tis a joke.

**Comment by GunHog** [comment]
Btw this is entirely a sprites deal, so ask @WJohn to do it!

**Comment by Steelpoint** [comment]
Asking @Wjohn to review this please.

**Pull request merged**
