### PR TITLE
Buffs the clown

### PR DESCRIPTION
**Pull request by ghost**
Removes slowdown from clown shoes.

### CODE REVIEW

**Comment by Ergovisavi** [comment]
Alright

**Comment by daman997** [comment]
HONK

**Comment by Killbasa** [comment]
Sounds good

**Comment by Kromgar** [comment]
Clown op now pls nerf

**Comment by Supermichael777** [comment]
but there so big and clumsy

**Comment by KorPhaeron** [comment]
@Supermichael777 

The clown trains for years in the art of yakkety sax

**Comment by xxalpha** [comment]
:-1:

No

**Comment by Core0verload** [comment]
:+1: HONK :+1:

**Comment by PKPenguin321** [comment]
:+1: im ready

**Comment by AlexCrimson** [comment]
Ruining /tg/ culture one PR at a time.

**Comment by Firecage** [comment]
Yes!

Also....YES!

**Comment by WJohn** [comment]
:+1: 
YES.

**Comment by SconesC** [comment]
no longer will horrible clowns have to shed their shoes

no longer will it be easy to identify shitter clowns

**Comment by vista-** [comment]
:-1:, true clowns never had a problem with this 'handicap', it's not that hard to evade security / greytide. It's a disgrace for a clown to remove their blessed, loud & slow shoes just to be "better" at the game.

**Comment by bgobandit** [comment]
slow clown shoes are iconic, please no buff

**Comment by kevinz000** [comment]
:-1: How do I spot the clowns who cross the line of powergaming and shit on them now?

**Comment by Marflowerose** [comment]
Alternatively, make clown shoes able to be fueled by bananas to walk faster.

**Comment by TheVekter** [comment]
uhangi shoes

**Comment by Fayrik** [comment]
:-1: At least balance this by making true clowns walk slower than everyone else.
I want my god damn funny man to be funny.

**Comment by MrPerson** [comment]
Going slower isn't funny nor does it create funny situations. It's just annoying for the clown. :+1:

**Comment by cookingboy3** [comment]
I'm up for Marflowerose's idea of banana-fueled clown speed.

Then we can have posters about clowns doing bananas as drugs to make them go faster.

**Comment by tuypo1** [comment]
fuck no your insane

**Comment by Razharas** [comment]
Well since kor left this can be closed

**Pull request closed without merging**
