### PR TITLE
Alt click for PDAs

### PR DESCRIPTION
**Pull request by ghost**
- Alt click PDA to eject ID.
- Renames 'remove ID' to 'eject ID' so it isn't right next to 'remove pen' and doesn't cause more object verb fumbling.
- Enables HoP powergaming.

PDA light toggle proc when

### CODE REVIEW

**Comment by Thunder12345** [comment]
Alt clicks for the all click god

**Comment by Dorsisdwarf** [comment]
I like it.

**Comment by AlexCrimson** [comment]
Very awesome

**Comment by GunHog** [comment]
Neat :+1: You could consider making CTRL click control the flashlight.

**Comment by Deantwo** [comment]
>PDA light toggle proc when

What? When what? o.o
DEAR GOD TELL Me ALREADY!

**Comment by dannno** [comment]
CTRL+click is a good idea for the flashlight, you should definitely make it happen in this PR

**Comment by paprka** [comment]
It's buried in the PDA stuff. I have a better grasp on luminosity now, but I've had the life sucked out of me. Treating it like a simple flashlight with a new proc that checks for the option being enabled inside the pda itself wouldn't be too hard.

**Pull request merged**
