### PR TITLE
Revert "Hand labelers cannot be used on any mobs."

### PR DESCRIPTION
**Pull request by PKPenguin321**
Reverts tgstation/tgstation#25583

Reopens https://github.com/tgstation/tgstation/issues/17743

Fix it properly instead of butchering the feature

### CODE REVIEW

**Comment by optimumtact** [comment]
Yeah @lzimann probably shouldn't have merged that one

**Comment by PKPenguin321** [comment]
The issue's here: https://github.com/tgstation/tgstation/blob/2552f6ba470026a5262754faf8e360ffb617c486/code/modules/mob/living/simple_animal/friendly/dog.dm#L112

This shouldn't be run every time the dog is attacked, only when the dog is attacked by something it can wear. I don't think that equipping him is even handeld in attackby, is it? If so, I'm not sure why this proc is run on attackby at all

**Comment by bgobandit** [comment]
use a fucking pet collar, like I said

there's no need to support two separate systems for doing the same thing and have 5 snowflake checks in order to accomplish this

**Comment by ExcessiveUseOfCobblestone** [comment]
There's no point of the pet collar if there's another item that's readily available that can do the same thing.

**Comment by bgobandit** [comment]
there's no point of another item if it's buggy as shit and full of snowflake checks

**Comment by optimumtact** [comment]
please calm yourselves, limit swearing to the irc where it isn't public

**Comment by bgobandit** [comment]
if someone has an issue with the word "shit" I can only assume they are in second grade and thus should be permabanned for underage

**Comment by ExcessiveUseOfCobblestone** [comment]
this is a christian repository please bgo!

**Comment by Iamgoofball** [comment]
alternatively consider my PR

#25301

**Comment by AnturK** [comment]
I probably wouldn't mind it if the collars were easier to get. Right now getting them is a chore.

**Comment by ChangelingRain** [comment]
It's not a feature, it's a bug.

**Comment by PKPenguin321** [comment]
Giving names to your monkeys is a feature damn you

**Pull request closed without merging**
