### PR TITLE
Having the "Snob" trait will now make you drawl

### PR DESCRIPTION
**Pull request by wesoda25**
## About The Pull Request

Instead of: Binky the Clown says, "thing" we will now have: Drumbus the Snob drawls, "intelligent thing"

## Why It's Good For The Game

Fun. Would be nice for gimmicks.

## Changelog
:cl:
add: the snob trait will change your saymod from "says" to "drawls"
/:cl:

### CODE REVIEW

**Comment by Kapu1178** [comment]
how does "snob" = "drawl"? 

> The drawl is often perceived as a method of speaking more slowly and may be erroneously attributed to laziness or fatigue.

**Comment by wesoda25** [comment]
I associate the two 🤷‍♂️. I've seen drawling be used as a way of describing the speech of snobbish characters in a variety of books, I think. I considered "yawns" or "simpers," but figured "drawls" was the best.

If the PR gets downvoted I'll close it, personally I've just always connected the two and it never crossed my mind that others wouldn't.

**Comment by Kapu1178** [comment]
personally the term "Drawl" is very closely associated with "southern drawl", which is itself associated with the way hicks speak.

**Comment by RaveRadbury** [comment]
I like the spirit of it but I don't associate drawl with snobbery and I feel like overriding the saymod might be a bridge too far, especially if it overrides species saymods.

**Comment by Helg2** [comment]
Maybe make it like . += "snobbishly/snobby" so it would look like "says snobbishly" and "meows snobby"

**Comment by wesoda25** [comment]
Meh, seems a bit long. If drawls isn't universally understood/appreciated then this isn't a good idea - it'll just confuse most. Thanks for the honesty, into the recycling bin with this.

**Pull request closed without merging**
