### PR TITLE
Clockcult stuff has colored lighting

### PR DESCRIPTION
**Pull request by ChangelingRain**
sssstep one
picture

### CODE REVIEW

**Comment by Incoming5643** [comment]
I'm sure you were probably being sarcastic but yeah considering how washed out colored lights can make things look sometimes pics are very much a good thing

**Comment by Xhuis** [comment]
From the looks of it, caches don't have lighting, intentional?

**Comment by ChangelingRain** [comment]
They do have light but it's weak

**Comment by Xhuis** [comment]
Oh, ok. Still not used to perceiving anything that isn't a tile in brightness.

**Comment by Anonmare** [comment]
I think caches having very weak lighting is intentional since they're meant to be hidden, at the start at least

**Comment by KorPhaeron** [comment]
I don't think we should make the automatic revert button not work for /vg/ lighting until see if the memory leak is actually gone

**Comment by KorPhaeron** [comment]
>breaking the game to make clock cult slightly prettier

she can't keep getting away with this

**Comment by Anonmare** [comment]
@KorPhaeron SHE GOT AWAY WITH IT

**Comment by Xhuis** [comment]
absolute madwoman

**Comment by PKPenguin321** [comment]
fat clockcult nerf

**Pull request merged**
