### PR TITLE
Fixes sound loops not well, stopping. 

### PR DESCRIPTION
**Pull request by LemonInTheDark**
## About The Pull Request

They were being removed from the wrong subsystem

## Why It's Good For The Game

Apparently this gets annoying over time or something, I wouldn't know.

## Changelog
:cl:
fix: Things like microwaves will no longer have their sound stack
/:cl:

### CODE REVIEW

**Comment by InsaneRed** [comment]
thank you i was about to go insane from ashstorm sounds in lavaland

**Comment by TheMidnightRose** [comment]
Will this fix a similar issue with lavaland storm sounds not stopping as well?

**Comment by LemonInTheDark** [comment]
it's the same issue yeah

**Comment by TheMidnightRose** [comment]
While we wait, is there a way to force it to stop? Specifically for the lavaland storm sounds?

**Comment by LemonInTheDark** [comment]
you'd want to manually cut the sound loop subsystem's client timers list

**Pull request merged**
