### PR TITLE
Brings balance to the universe (Pest Spray nerf)

### PR DESCRIPTION
**Pull request by Robustin**
Pest Spray didn't appear in your hand before, I don't know why.

No, my last three deaths were to a plasma fire, changeling while AFK, and suicide. I have not been slip n' slapped for at least 24 hours. 

Yes this is dumb. I am Robustin, destroyer of slip memes.

### CODE REVIEW

**Comment by PKPenguin321** [comment]
>inb4 a massive wave of butthurt over adding an inhand

**Comment by Robustin** [comment]
I have no clue what I'm doing here, I'm just making the pest pray more consistent with Plant-B-Gone (the other botanist spray meme tool for the less robust who didn't rush the pest spray at roundstart EMILY RANGER).

If someone has a better solution by all means, but the invisible spray ejaculating from your hands meme must die. If we're ok with spray bottles being the most robust item on the station, people deserve an extra half-second to react when someone puts a sprayer in their hand... or has one in their hand waiting to spray at the last second as you walk by.

**Comment by Razharas** [comment]
:+1:

**Comment by Zilenan91** [comment]
can we just nerf slips instead

**Comment by Metacide** [comment]
This sounds perfectly sensible, should always have had an in-hand. :+1:

**Pull request merged**
