### PR TITLE
Adds Ass Slapping

### PR DESCRIPTION
**Pull request by Mooshimi**
## About The Pull Request
Adds ass slapping with slap hand.

## Why It's Good For The Game
Lets tailless races enjoy the wonders of tail tugging in spirit.

## Changelog
:cl:
add: Added ass slapping!
/:cl:

### CODE REVIEW

**Comment by Mothblocks** [comment]
...no?

**Comment by TheVekter** [comment]
1984

**Comment by Crushtoe** [comment]
head coder courageously faces the army of ass slappers

**Comment by Mothblocks** [comment]
one time someone walkjed up to me in the hop line and emoted "milks moth" and i still think about it

**Comment by Crushtoe** [comment]
i don't like mothblocks' story time

**Comment by Mooshimi** [comment]
> ...no?

can oranges vote

**Comment by Mothblocks** [comment]
yyes

**Comment by wesoda25** [comment]
Hulks should break someones tailbone and send them flying

**Comment by Toastgoats** [comment]
Buenos dias mandy

**Comment by castawaynont** [comment]
merge now

**Comment by rellyreri** [comment]
how is this any different from tail pulling

**Comment by interestingusernam3** [comment]
incredible

**Comment by Mothblocks** [comment]
i pull one of my cats tail sometimes and they like it

**Comment by optimumtact** [comment]
> how is this any different from tail pulling

one was mooshimi's idea, the other was mine

**Comment by itseasytosee** [comment]
> how is this any different from tail pulling

Tail pulling was made as a counter balance to a different terrible felinid PR

**Comment by Mothblocks** [comment]
whats erotic about pulling someones tail

**Comment by Mothblocks** [comment]
weird :|

**Comment by Crushtoe** [comment]
must suck to have a tail pulling kink when you don’t have a tail

**Comment by Mothblocks** [comment]
how is tail pulling a kink you are into some fucked up stuff man

**Comment by optimumtact** [comment]
what be happening here
oh no

**Pull request closed without merging**
