### PR TITLE
Removes the three built in BCI action components from the BCI integrated circuit shell

### PR DESCRIPTION
**Pull request by TheBonded**
## About The Pull Request
The BCI integrated circuit shell starts off with three unremovable BCI action components, and this pr removes all of them. To reflect this change, BCI shells now cost 1000 glass less, down to 1000 from 2000

## Why It's Good For The Game
Often I struggle to find a use for all three BCI action components, and I'm sure others have the same issue. They are unremovable, so if you were to just opt to ignore them you'd have 1-2 unused hud buttons on screen, which can clutter the screen and look ugly. If I, or anyone else making BCI circuits, want hud buttons, it's easy to just print more for only 1k glass each, and slot them in.

## Changelog

:cl:
del: Removed the three unremovable BCI hud buttons. If you need more, you can print them at any local component printer.
qol: BCI shells now cost 1000 less glass, to reflect the removal of the three built in BCI hud buttons.
/:cl:

### CODE REVIEW

**Review by Mothblocks — APPROVED** [review]
I told this to Watermelon too--now that they are printable, I wanted it to be kept to one as a mini-tutorial of what BCIs can do.

**Comment by Watermelon914** [comment]
I think you should remove all the actions and instead make bcis come with an integrated circuit with 1 action component in them.

**Comment by TheBonded** [comment]
> 
> 
> I think you should remove all the actions and instead make bcis come with an integrated circuit with 1 action component in them.
> 
> That'd be preferable imo so that people aren't left with an action that does nothing if their bci doesn't utilise that action. They'd be able to remove it freely.

in that case, would it not be better to remove all three BCIs and allow people to print their own integrated circuit and action component(s)? Considering no other circuit shell is printed with an integrated circuit already inside them.

**Comment by Watermelon914** [comment]
> > I think you should remove all the actions and instead make bcis come with an integrated circuit with 1 action component in them.
> > That'd be preferable imo so that people aren't left with an action that does nothing if their bci doesn't utilise that action. They'd be able to remove it freely.
> 
> in that case, would it not be better to remove all three BCIs and allow people to print their own integrated circuit and action component(s)? Considering no other circuit shell is printed with an integrated circuit already inside them.

It was added as a mini-tutorial thing but I don't think these components should be unremovable on the shell. The idea that I have is that you have a bci shell that starts with an empty integrated circuit in it with a bci action component

**Comment by TheBonded** [comment]
> 
> 
> > > I think you should remove all the actions and instead make bcis come with an integrated circuit with 1 action component in them.
> > > That'd be preferable imo so that people aren't left with an action that does nothing if their bci doesn't utilise that action. They'd be able to remove it freely.
> > 
> > 
> > in that case, would it not be better to remove all three BCIs and allow people to print their own integrated circuit and action component(s)? Considering no other circuit shell is printed with an integrated circuit already inside them.
> 
> It was added as a mini-tutorial thing but I don't think these components should be unremovable on the shell. The idea that I have is that you have a bci shell that starts with an empty integrated circuit in it with a bci action component

I do understand what you mean, and I agree that I should remove all three of the bci action components, my question is if it would be better to have the BCI shell not start with an empty integrated circuit already in it, since all other shells require you to print your own integrated circuits separately.

**Review by Mothblocks — CHANGES_REQUESTED** [review]
What Watermelon wants is not to remove all the actions, but to not make them unremovable.

In order to do this, though, the BCI needs to come with an integrated circuit.

I personally think that what you had before was fine and that Watermelon or I would be better equipped to make that PR.

**Comment by TheBonded** [comment]
> 
> 
> What Watermelon wants is not to remove all the actions, but to not make them unremovable.
> 
> In order to do this, though, the BCI needs to come with an integrated circuit.
> 
> I personally think that what you had before was fine and that Watermelon or I would be better equipped to make that PR.

in that case, would you want to close this pr? I do agree that being able to remove them would be far better, but I'm nowhere near experienced enough to code that, so it'd probably be best to leave that to you two.

**Comment by Mothblocks** [comment]
Your original PR of removing all but one is fine with me.

**Comment by Watermelon914** [comment]
#61521
Alright, I've done it on this PR

**Comment by Mothblocks** [comment]
cool im taking that one instead

**Pull request closed without merging**
