### PR TITLE
New Trait: Acute Blood Deficiency

### PR DESCRIPTION
**Pull request by Mickyan**
:cl: Mickyan
add: New negative trait: Acute Blood Deficiency. Keep your slowly decreasing blood level in check if you want to survive.
/:cl:

Major negative trait, your blood level is constantly decreasing. 
Iron regenerates just enough blood to increase your blood level very slowly, if you get shot up you'll need something stronger or a transfusion to survive.
Epinephrine and salbutamol can buy you some time but you'll still drop dead eventually.

Here's how it looks like if you neglect it:
~15 minutes: low blood symptoms 
~30 minutes: oxygen damage builds up
~32 minutes: fainting
~34 minutes: dead

### CODE REVIEW

**Review by Cyberboss — DISMISSED** [review]

**Comment by Cyberboss** [comment]
Good PR

**Comment by Spaceinaba** [comment]
NOW I CAN ACTUALLY BE PATCHOULI I LOVE YOU

**Comment by Mickyan** [comment]
@PKPenguin321 the first visible low blood symptoms you get are (afaik) just flavor text and it works as a warning to give you plenty of time to get treated before having any real issues, so I don't think it's necessary

**Comment by GunHog** [comment]
You choose to limit yourself!

**Comment by Shadowflame909** [comment]
I know! I think it'd be a funny way to make fluke ops even harder 😅

**Comment by iskyp** [comment]
>nuke ops
>hard
ok

**Comment by nicbn** [comment]
The IV drips will get stolen every round and medbay will be out of bloodpacks in like 20 minutes into the round.

**Comment by nicbn** [comment]
Also anemy is never treated with blood transfusion, 90% of the times you are just lacking iron in your bloodstream.

**Comment by Barhandar** [comment]
>The IV drips will get stolen every round and medbay will be out of bloodpacks in like 20 minutes into the round.

Edge cases are not all cases.  
>Also anemia is never treated with blood transfusion (except in critical conditions), 90% of the times you are just lacking iron in your bloodstream.

And mannitol is just a sweetener. And you can't wiggle around in a brain with a scalpel and fix brain traumas. Your point?

**Comment by Shadowflame909** [comment]
Well maybe medical will have to get up off there ass and order more blood packs from cargo, or humanize monkeys. Check there blood types and fill the blood packets with the corresponding correct amount of blood. Or, just produce a shitload of iron pills from chemistry.

**Comment by kevinz000** [comment]
anemic should do as it does in irl, make you weak/faint and slowly lose blood to a certain level, but not kill you if you don't get iron wtf

**Comment by Shadowflame909** [comment]
What happens if an anemic person doesn't get a blood transfusion kevinz. WHAT HAPPENS. D E A T H.

**Comment by Mickyan** [comment]
I like to assume that the few who will have the inclination to pick this up will know or at least eventually figure out that it's far less complicated to use saline-glucose solution or drink bloody marys at the bar. How's that for realism?

Severe cases of anemia will absolutely kill you without any treatment. I didn't see the reason to get so specific in the description.

It's also far more interesting from a gameplay standpoint: it's easy to keep in check (nutrients, iron, bloody mary, saline-glucose solution, blood packs to name a few common ways to treat it) but deadly if you ignore it for too long. The signs are VERY obvious when you're getting low on blood and you have plenty of time to react. Having to limp to medbay while constantly fainting because you ignored them for too long makes it just annoying and not as interesting as being a deadly disease looming over you at all times.

**Comment by Shadowflame909** [comment]
This seems like a gameplay feature that can heavily impact the amount of people in medbay. I hope there's an identifier of Anemia on health scanners. Or else people are going to feed people sabumatol and epi pens in sleepers and leaving them to croak. Also wasting cryoxadone..

**Comment by davethwave** [comment]
If you observe someone with a medical hud it shows what traits you have.

**Comment by PKPenguin321** [comment]
exaggerated anemic

**Comment by kevinz000** [comment]
@Mickyan most anemics will not die if they don't get a transfusion every day will they? even the seriuos ones.

**Comment by BebeYoshi** [comment]
Anemic should be something like, making you really fragile to bleed, unless you take iron, you're like in a "fragile" position, in which if you bleed, you can actually die even if it's a really minor bleeding, still would be a huge disadvantage, even a selft hit would be fatal. I don't know if such a thing is possible, but that's what I think

**Comment by GunHog** [comment]
This trait should not be nerfed or weakened in any way! It is entirely optional! You are choosing to put yourself into hard mode, just like the "pacifist" trait! I do like the 'fragile' idea, though. That could an idea for a minor version of this trait.

**Comment by Mickyan** [comment]
Thank you for the feedback, everyone. I had some time to think and do some more tweaking and I've made the following changes:
-Renamed trait to Acute Blood Deficiency (ABD), same meaning, more vague and threatening.
-Decreased the blood drain amount, death will occur after around 34 minutes. 

As I was testing this it became obvious that having to keep your blood level in check so often wasn't going to be fun in the long run, but I also I didn't consider that the biggest drawback is you can no longer rely on natural blood regeneration. 
Every time you get hurt it will take time off your clock. Stay healthy and it'll be easy be easy to manage with just taking some iron every now and then.

**Review by Cyberboss — APPROVED** [review]

**Comment by cacogen** [comment]
chronic

**Comment by BebeYoshi** [comment]
Amazing, seems like an awesome trait as of now, can't wait to see some character with it

**Comment by Shadowflame909** [comment]
I hope ling's can't abuse this.

**Comment by davethwave** [comment]
Abuse it how?

**Pull request merged**
