### PR TITLE
num2hex/hex2num defines 

### PR DESCRIPTION
**Pull request by vuonojenmustaturska**
## About The Pull Request
Radix support was added in 513. Might push some more stuff into this branch before 24 hours is up.

## Why It's Good For The Game
These actually have a fair number of calls. The built-ins are also surely much faster.

### CODE REVIEW

**Comment by vuonojenmustaturska** [comment]
this btw probably has a not-insignificant effect on lighting performance

**Review by AnturK — DISMISSED** [review]
Looks okay but that _helpers is going to become new unsorted.dm

**Comment by vuonojenmustaturska** [comment]
It's for shit that absolutely has to go early

**Review by AnturK — CHANGES_REQUESTED** [review]
Bump up MIN_COMPILER_BUILD, forgot to mention this.

**Pull request merged**
