### PR TITLE
Fixes #12326: High-capacity power cells on Boxstation having wrong capacity

### LINKED ISSUE #12326: Boxstation map high-capacity power cells have wrong capacity
They've been var-edited on the map to have 15000 capacity, while in the code they only have 10000 (and presumably when made by exosuit fabs and the protolathe too).

### PR DESCRIPTION
**Pull request by freerealestate**
**Changes:**
- Replaces var-edited high cap cells on Boxstation with plus sized versions with slightly modified icons
- Renames high cap cell in ninja suit and changes its sprite to reflect its custom capacity

Imgur
If people don't like the + sprite, I can remove it.

### CODE REVIEW

**Comment by KorPhaeron** [comment]
15k has been the standard robotics cell for like 3 years aaaaaa

**Comment by xxalpha** [comment]
Why the fuck was the high capacity changed to 10k?

**Comment by freerealestate** [comment]
Presumably so each cell is 10k more than the last.

**Comment by xxalpha** [comment]
Standard cells aren't 0 :angry:

**Comment by freerealestate** [comment]
So I found out that these var-edited cells predate: /tg/ https://github.com/tgstation/-tg-station/blob/662c08272acd7be79531550919f56f846726eabb/maps/trunkmap.dmm (our first map, from Goon r4407) and have been on every version of Boxstation since it was first created a few months later. Then after high capacity power cells were introduced, someone changed the paths of the var-edited cells on the map to make them high capacity ones, but didn't remove the var-edits.

So since these cells have been around since before /tg/ and outdate the high-capacity ones on our repo by 5 months, I might just change high capacity power cells to hold 15k.

**Comment by KorPhaeron** [comment]
Just put three 15k cells in robotics. If there is no cell type with 15k as the default, just make one.

**Pull request merged**
