### PR TITLE
You can now select a specific prosthetic slot

### PR DESCRIPTION
**Pull request by Cyberboss**
Taking desc meme suggestions

:cl:
add: Added 4 more prosthetic quirks to allow you to select which limb you want as a prosthetic
/:cl:

TODO: Remove potential powergame by taking all 5

### CODE REVIEW

**Comment by ExcessiveUseOfCobblestone** [comment]
How possible would it be to make it 1 item and you switch on the ones you want (obviously scaling in price)? AKA not bloating the list.

**Comment by Cyberboss** [comment]
Not at all possible without a heavy implementation rewrite

**Comment by Spaceinaba** [comment]
about time, you are a hero

**Comment by improvedname** [comment]
If you take them all 5 you become weaker
But just a lower dam cap

**Comment by Cyberboss** [comment]
I lack fucks to give

**Comment by Mickyan** [comment]
Maybe now this could be added as is? After the limb rework having 4 robotic limbs would be pretty brutal, 3 hits with a toolbox is all it takes to disable

**Comment by ExcessiveUseOfCobblestone** [comment]
you scared me when you said robotic

**Comment by Mickyan** [comment]
Code wise they're shitty robot limbs so it's technically correct ¯\_(ツ)_/¯

**Pull request closed without merging**
