### PR TITLE
Ports new animated medical scanner sprites from Polaris.

### PR DESCRIPTION
**Pull request by harmonyn**
#45422  About The Pull Request

Ports new medical scanner sprites from Polaris (https://github.com/PolarisSS13/Polaris/pull/6357) that animate when they scan. They have more tiers of scanner than we do, so I specifically ported Basic for regular and Improved for advanced:

polaris scanners

The traitor scanner doesn't have an animation currently, but it does have the same subtle visual difference (all red pixels up top instead of red-yellow-green) as our old sprite.

## Why It's Good For The Game

Because I like these sprites.

## Changelog
:cl: bandit
imageadd: Medical scanners now have animated sprites. Thanks Michiyamenotehifunana of Polaris.
/:cl:

### CODE REVIEW

**Comment by Shapsy** [comment]
Those sprites look amazing and I love them, but the phasic one seems a bit over the top for the advanced scanner. The decision to have an open electrical arc on a body scanner seems really weird

**Comment by bgobandit** [comment]
fair, it's easy enough to switch to one of the other two if you have a preference

**Comment by carlarctg** [comment]
i agree that it should probably be switched to either advanced or improved. probably advanced

**Comment by tralezab** [comment]
I'd go for improved because it's distinct enough

**Comment by bgobandit** [comment]
switched to improved, advanced doesn't look super different

**Comment by Tlaltecuhtli** [comment]
souless

**Comment by bgobandit** [comment]
the fuck is with the downvotes

**Comment by coiax** [comment]
This is probably out of scope for the PR, but you should have a clown face appear when someone with the clumsy gene scans the floor.

**Comment by bgobandit** [comment]
that's funny but a) I cannot into spriting that much and b) it seems kind of overkill to have two separate animations for a throwaway joke

**Pull request merged**
