### PR TITLE
Revert "Fixes instant summons and probably a few other edge cases"

### PR DESCRIPTION
**Pull request by optimumtact**
Reverts tgstation/tgstation#22890

### CODE REVIEW

**Comment by PKPenguin321** [comment]
But why 🤔

**Comment by Iamgoofball** [comment]
# SPEEDMERGE

**Comment by Iamgoofball** [comment]
@PKPenguin321 unequipping stuff deleted it

**Comment by PKPenguin321** [comment]
Haha nice

**Comment by Shadowlight213** [comment]
To be more precise, unequipping caused an infinite loop.

**Pull request merged**
