### PR TITLE
Bike horns, golden horns, rubber ducks, and air horns no longer plays sounds when crossed in Zero-G or by flying mobs.

### LINKED ISSUE #45854: Airhorn honks when you cross it even in zero G
Issue reported from  Round ID: 115647 (/tg/Station Bagil [ENGLISH] [US-WEST] [100% FREE LAG])

Reporting client version: 512.1471

### PR DESCRIPTION
**Pull request by Firecage**
## About The Pull Request

This PR makes it so that bike horns, golden horns, rubber ducks, and air horns no longer plays their respective sounds when they are crossed in Zero Gravity by mobs, nor when they are crossed by flying mobs. Thus some clown annoyance is removed.

Update: Due now using FLOATING instead of has_gravity(), and just for mobs, items going over bikehorns in Zero G still makes them squeak. No idea why that even exists, but what can you do.

Fixes #45854

## Why It's Good For The Game

Honestly, anything which makes the damn air horn screech less in my ear is a good thing.

## Changelog
:cl:
fix: Bike horns, golden horns, rubber ducks, and air horns no longer plays their respective sounds when crossed in zero gravity, nor when crossed by flying mobs.
/:cl:

### CODE REVIEW

**Comment by nemvar** [comment]
checking for gravity but not for flying. smh my head.

**Comment by Firecage** [comment]
You know, I actually didn't think about that, since I didn't check whether it checked for that already or not. I just assumed that whoever originally did it hopefully hated the horns enough to include it.

**Comment by Farquaar** [comment]
In space, no one can hear you honk

**Review by actioninja — CHANGES_REQUESTED** [review]
has_gravity is a nasty really heavy proc that's far, far heavier than it ever should be.
Just check for floating/flying move types on the mob.

**Review by spookydonut — COMMENTED** [review]
should there maybe not be a different signal for crossing in zero-g

**Comment by Firecage** [comment]
@actioninja Though, mmm, in that case, then items being thrown over bikehorns in zero G will still make them squeak though. On the other hand, that is minimal compared to your worry about how heavy the proc is. I'le change it later, even if it means that it will now only count for mobs.

**Comment by Firecage** [comment]
@actioninja Alright, updated to use FLOATING|FLYING move types. Of course, will have to think of another solution for items going over them causing squeaking due to has_gravity() being out. Though, yah, kinda silly it makes the squeaking even if thrown over the item and not just when landing on it.

**Pull request merged**
