### PR TITLE
Way way nerfs sashimi price

### PR DESCRIPTION
**Pull request by tralezab**
## About The Pull Request

This was CRAZY priced for back before the produce console was even an idea in my head, since it consisted of only ingredients you could not obtain.

## Why It's Good For The Game

300 credits for 20 credits worth of orderable goods was stimulating the economy and we hate that yes we do

## Changelog
:cl:
balance: sashimi pays waaaaaay less
/:cl:

### CODE REVIEW

**Comment by cacogen** [comment]
Can't argue with this but bounties are like 1000x more efficient profit-wise and if you want to make tourists worthwhile for cooks to feed tourists instead of doing bounties you'd multiply the payouts (and subsequently the console costs)

**Comment by tralezab** [comment]
I def. think that the bartender and chef doing this instead of bounties would be way better so i'm sure at some point in the future qust is going to cut bounties and increase the income from tourist service.

as in, bounties are kind of a crutch of jobs and tourist bots is a way more fleshed out replacement.

**Comment by cacogen** [comment]
I don't think you should cut bounties for everyone on behalf of the cooks and bartender until after you monetised all the other jobs

**Comment by Krysonism** [comment]
Increase the purchasing price of spider eggs and carp meat. 10 credits is far too cheap for exotic meat.

**Comment by interestingusernam3** [comment]
Why are those things even purchasable at the console

**Comment by cacogen** [comment]
1. Tourist orders carp sashimi
2. 99% of the time no ingredient sources

**Comment by Krysonism** [comment]
> 1. Tourist orders carp sashimi
> 2. 99% of the time no ingredient sources

Then maybe japanese bots should not have been added before we had suitable dishes for them to order...

**Comment by cacogen** [comment]
They order a few different Asian dishes. Carp sashimi is the only one I can remember with rare ingredients. If the pricing of those ingredients is too cheap then that's another reason to increase the payouts to be equitable to bounties. It would necessitate increasing the cost of ingredients. Which would make hydroponics more valuable too.

**Comment by Dorsisdwarf** [comment]
10 credits for rare meat while junk food is 3 times as much was bad pricing to begin with

**Comment by Qustinnus** [comment]
We can just remove the bounties for chef and bartender and leave the rest

**Comment by maxymax13** [comment]
> 
> 
> I don't think you should cut bounties for everyone on behalf of the cooks and bartender until after you've monetised all the other jobs

assistants get paid 200 credits for every window they break and 250 credits for every device they hack

**Comment by cacogen** [comment]
i.e. Don't cut bounties

**Comment by Qustinnus** [comment]
no. bounties are for the weak.

**Comment by cacogen** [comment]
If you are going to remove bounties for cooks and bartenders, I hope you'll do the obvious thing and make tourist payouts comparable. Otherwise cooks will be doing this, which is stressful, while assistants sell pot plants for 10 times as much

**Comment by Mothblocks** [comment]
one day we can dream that all our jobs will have content. it's a bright future

**Pull request merged**
