### PR TITLE
Adds an APC to the delta R&D servers

### LINKED ISSUE #25582: No APC in Delta R&D Server Room
You cannot turn off the power in the room as there are no APCs leading to it.

Asked an admin to confirm;

-- Administrator private message --
Admin PM from-Cedarbridge: Apparently not.
Click on the administrator's name to reply.
-- Administrator private message --
Admin PM from-Cedarbridge: Yeah, best I can tell the server room is just powered by magic
Click on the administrator's name to reply.

### PR DESCRIPTION
**Pull request by ChangelingRain**
Fixes #25582
Also fixes the grilles, which were wired but not properly connected to the powernet, and removes the apparently misplaced xenobio shutters below them.

### CODE REVIEW

**Comment by coiax** [comment]
pix

**Comment by ChangelingRain** [comment]
The only visible difference is an apc. Imagine the server room, but with an APC. that's it.

**Comment by Jalleo** [comment]
Doors were removed.

**Comment by KorPhaeron** [comment]
Where did the doors go

**Pull request merged**
