### PR TITLE
Fixes Metastation shuttle

### PR DESCRIPTION
**Pull request by Jordie0608**

### CODE REVIEW

**Comment by Jordie0608** [comment]
According to @coiax this issue was fixed by #17958, however the values are still different and I presume it would be better for them to align anyway

**Comment by Razharas** [comment]
I believe you and thelongbowman

**Comment by coiax** [comment]
Values are deliberately different. The dock's area is bigger than the shuttle. Doing so allows it to have other shaped shuttles dock with it.

**Comment by lzimann** [comment]
well, the dwidth 9 works fine(did it myself 2 or 3 times in-game).

**Comment by MrStonedOne** [comment]
Ya, I agree with coiax, keep it so it's as wide as it can support for better custom shuttle import support

**Comment by Razharas** [comment]
Now i agree with coiax and mso

**Pull request closed without merging**
