### PR TITLE
POWER ROUND 2: HYDROPONICS FIXES

### LINKED ISSUE #50373: More issues with New Botany.
## Round ID:
[133834](https://scrubby.melonmesa.com/round/133834), On Sybil

## Testmerges:
https://github.com/tgstation/tgstation/pull/50001
https://github.com/tgstation/tgstation/pull/50369

## Reproduction:
A list of issues from playing an hour+ long round of botany. Hopefully these aren't major breaks.
1. Instability isn't functioning at all. Tried it on watermelons and cherries, pushing their instabilities from 0 to every single threshold. Every threshold broken did not apply any stat changes to the plant, nor caused them to mutate into something else, regrettably. Neither through L4Z nor Mutagen.

2. Radium and Uranium do not function at all for plants, except as a powerful poison, when it should mess with stability as a worse alternative to mutagen.

3. Robust Harvest is for some reason, only buffing Potency, and not Yield, despite it supposed to be otherwise.

4. No plants traded chems, even when doing some cross pollination experiments to see if I could even move Corn Oil to a cherry.  

5. This one is a holdout from the first drop of the botany PR, but when I go for cuttings, half of them don't show up, which can be a pain when trying to figure out if you just got liquid contents, or perennial growth from a tomato plant.

### LINKED ISSUE #50377: Plant Grafts Are Invisible
Issue reported from  Round ID: [133869](https://scrubby.melonmesa.com/round/133869) (/tg/Station Manuel [ENGLISH] [US-WEST] [ROLEPLAY] [99% LAG FREE])

Reporting client version: 513.1513

What the title says.

### LINKED ISSUE #50379: High Instability Plants Don't mutate
Issue reported from  Round ID: [133869](https://scrubby.melonmesa.com/round/133869) (/tg/Station Manuel [ENGLISH] [US-WEST] [ROLEPLAY] [99% LAG FREE])

Reporting client version: 513.1513

I had a pair of 100 instability plants growing for a good chunk of the shift. No changes were detected in their chemical production, species or plant traits.

### PR DESCRIPTION
**Pull request by ArcaneMusic**
## About The Pull Request
Alright, as it turns out, almost everything that was broken was as a direct result of things that I altered in review, apparently silently broke, and never came up subsequently.
I took a fine comb over what was broken and reported as well as several things that I altered in review just to make sure they're working as intended again.

Fixes #50379, Fixes #50377, Fixes #50373.

## Why It's Good For The Game
Bugs are illegal.
And I'm the law.

## Changelog
:cl:
fix: Plant grafts, instability, plant crosspollination all work correctly again.
tweak: EZ nutrient and Robust Harvest have had their stat adjustments tweaked closer to their original intention.
/:cl:

### CODE REVIEW

**Comment by FancyCyclops** [comment]
This won't get merged immediately.

The pain needs to be relished in.

**Comment by ArcaneMusic** [comment]
> 
> 
> This won't get merged immediately.
> 
> The pain needs to be relished in.

Ya know you say that, but contrary to popular belief, I am not a bad person.

**Comment by actioninja** [comment]
speed merging so first impressions can be slightly better

**Comment by Tlaltecuhtli** [comment]
> This won't get merged immediately.
> 
> The pain needs to be relished in.

download his branch and play it, hydrophonics is singleplayer anyway

**Pull request merged**
