### PR TITLE
Fixes master

### PR DESCRIPTION
**Pull request by LemonInTheDark**
## About The Pull Request

Daily reminder to me/moth (I don't know who did this), think about what A changes before merging B
## Why It's Good For The Game

FUCKKKKKKKKKKKKKKKKKKKKKKKKK

### CODE REVIEW

**Comment by Qustinnus** [comment]
you might as well do the changes properly :^)

**Comment by LemonInTheDark** [comment]
I'm not risking it man

**Comment by LemonInTheDark** [comment]
https://github.com/tgstation/tgstation/pull/53193/commits/f02bde48c89f2c20e790d2148e8f4503c775ea95

**Review by stylemistake — APPROVED** [review]

**Pull request merged**
