### PR TITLE
buffs styptic, silver sulf, and synthflesh

### LINKED ISSUE #7178: New chems not working as they are intended to, Cult got nerfed by proxy for no reason from this chance
Right now there's a lack of balance for the new chemistry system. The emergency medipens are used less for trying to keep people alive but instead are used instead for the knockdown side effect to steal guns from security or nuke ops or just stunning the wizard and getting BWOINKed over it.

Also patches are doing 1:1 heals so it would take upwards of 6 patches to heal someone who was set on fire with light fire damage. Someone who got a large amount of fire damage requires over 15! patches. It shouldn't take over a hundred patches from chemistry just to deal with a mass causality event.

Stealth cult also got nerfed with the medbot change meaning that you always have to convert medbay to keep up with the research requirements.

Just bringing it up because it seems right now coderbus is unaware of the problems.

### PR DESCRIPTION
**Pull request by Iamgoofball**
Fixes #7178
too

### CODE REVIEW

**Comment by pudl** [comment]
im guessing you didnt test this

**Comment by Iamgoofball** [comment]
no, i did, it works

**Comment by pudl** [comment]
i just tested it now and styptic doesn't heal over time anymore, only on touch

**Comment by Deantwo** [comment]
Also can you make unconscious people not scream? Or do I have to make an issue for it?

**Comment by Iamgoofball** [comment]
@pudl you are incorrect

it heals over time for me

**Comment by Fox-McCloud** [comment]
Looks great and is 100% accurate to Goon---except the Synth flesh...

**Comment by Iamgoofball** [comment]
eh fuck it buffing synthflesh a bit

**Comment by Jordie0608** [comment]
Changelog.

**Pull request merged**
