### PR TITLE
Ruin placement will try very hard to place any ruins with negative costs before attempting any other ruins

### PR DESCRIPTION
**Pull request by ChangelingRain**
This means the Hierophant will show up pretty much every round.
You can also make any given ruin spawn basically every round with this.

### CODE REVIEW

**Comment by KorPhaeron** [comment]
Guaranteed anything seems weird when the entire gimmick is to keep things fresh and different per round

**Comment by ChangelingRain** [comment]
I mean this to be used more or less exclusively for bosses that might not otherwise spawn at all, since not everyone who might want to fight them can afford to play several rounds hoping for one to spawn.

Everything else should absolutely have a cost and be much more random.

**Comment by Hatfish** [comment]
>the sloth ruin will show up pretty much every round
Please god no, that thing is already annoying enough to work around without it appearing constantly.

**Comment by Kromgar** [comment]
Sloth is terrible

**Comment by Armhulen** [comment]
we should remove the sloth ruin already

**Comment by Anonmare** [comment]
Doesn't the sloth ruin have a player reference in it anyway?

**Comment by DoctoreMad** [comment]
No
You should still remove it

**Comment by Iamgoofball** [comment]
:+1: I need this for dorfs.

**Comment by Kromgar** [comment]
Sloth is funny until you see it every single round.

**Comment by ExcessiveUseOfCobblestone** [comment]
Sloth is a one time gimmick ruin.

If there's a purpose of cost 0 currently, why not make -1 an always spawn?

**Comment by outbools** [comment]
Whole system now looks rigged. There was a point in negative cost ruins to not spawn every round. 
OH WAIT THAT WAS ACTUALLY A MEANING OF THIS

**Comment by DoctoreMad** [comment]
Oh I just had a bad idea
Swarmer ruins can spawn again but they have -10 cost so you get more ruins in lavaland to explore.

**Comment by ExcessiveUseOfCobblestone** [comment]
^ what did he mean by this

**Comment by ChangelingRain** [comment]
negative costs don't increase the budget.

**Review by Cyberboss — APPROVED** [review]

**Comment by KorPhaeron** [comment]
Going to be a big waste of real estate if any more 0 cost ruins are added and half the free space is boss arenas for the top 1% of players

**Comment by KorPhaeron** [comment]
Sloth ruin every round is dumb as well not sure why you merged this as is @cyberboss

**Comment by ChangelingRain** [comment]
sloth doesn't spawn every round with this tho I updated it

**Comment by KorPhaeron** [comment]
Guess it still just grates on me that heirophant is off theme and lifted straight from another game and now its huge arena has priority over everything else for whatever reason

**Comment by Iamgoofball** [comment]
Kor I needed this for dwarves too

**Pull request merged**
