### PR TITLE
Makes the roundend theme a config

### PR DESCRIPTION
**Pull request by JohnFulpWillard**
## About The Pull Request

This isn't the song that plays at the end of a round (which is actually just the roundstart song played again), but the little few second theme that plays when a server reboots.
This sets it to use the same thing title music does.

## Why It's Good For The Game

- Allows admins to add/remove songs without having to manually VV edit it in round or go and edit code
- Removes more hardcoded things that shouldn't be hardcoded
- Makes roundstart and roundend's songs more consistent with eachother.

### CODE REVIEW

**Comment by JohnFulpWillard** [comment]
im mad because this works locally so idk why checks are failing

**Comment by Mothblocks** [comment]
CC @MrStonedOne -- files being moved into config

**Comment by Mothblocks** [comment]
I'm going to wait until @MrStonedOne has confirmed these are all moved over

**Comment by Mothblocks** [comment]
or maybe do it myself later

**Comment by JohnFulpWillard** [comment]
@Mothblocks Any update on this?

**Comment by Mothblocks** [comment]
mso is busy with forums so i'll have to do it myself

**Comment by Mothblocks** [comment]
actually i dont even think i have the ability to network link stuff

**Comment by MrStonedOne** [comment]
> actually i dont even think i have the ability to network link stuff

image

**Comment by Mothblocks** [comment]
I'll look into it, to learn if nothing else

**Comment by Mothblocks** [comment]
Done

**Pull request merged**
