### PR TITLE
improves bee lore

### PR DESCRIPTION
**Pull request by Iamgoofball**
## About The Pull Request

see title

## Why It's Good For The Game

improving bee lore is good

## Changelog
:cl:
spellcheck: improves bee lore
/:cl:

### CODE REVIEW

**Comment by Serxule** [comment]
elaborate

**Comment by TheBonded** [comment]
> elaborate

Bee lore is better now

**Comment by YakumoChen** [comment]
This is actually the second time I've seen goof make this PR.

**Comment by YakumoChen** [comment]
It wasn't funny 4 years ago

**Comment by AnturK** [comment]
Not starting this shit again

**Comment by Iamgoofball** [comment]
sir, 24 hours

**Pull request closed without merging**
