### PR TITLE
Removes "machine prototypes"

### PR DESCRIPTION
**Pull request by ACCount12**
They were added as a shitty stub to make cargo have some power over old R&D. Old R&D is no more, and cargo now has more power than ever. Time for it to go.

🆑 ACCount
del: "Machine prototype" is removed from the game.
/:cl:

### CODE REVIEW

**Comment by GuyonBroadway** [comment]
The machine prototype was literally the stupidest idea. It just meant that science had to wait for the box-haulers to haul enough boxes to get their arbitrary time-gate macguffin.

**Comment by imsxz** [comment]
Was it even needed for old RND? I'm not sure any designs needed engi 7

**Comment by Shadowlight213** [comment]
It was for a time, then cyber organs were added, which let rnd bypass the need to wait for cargo or botany.

**Comment by kevinz000** [comment]
lmao it was meant to be until people powercreeped rnd to shit (and it wasn't even me!)

**Comment by GuyonBroadway** [comment]
RnD got powercreeped for tech levels because every attempt at tech level delays was just having to wait for someone else to do a thing and that was boring.

**Review by Cyberboss — APPROVED** [review]

**Comment by optimumtact** [comment]
this is the kind of nice side effect that democratizing techwebs had.

**Pull request merged**
