### PR TITLE
Cloner checks if occupant is human rather than just carbon

### LINKED ISSUE #35014: Attempting to clone monkeys breaks the cloning pod
[Round ID: 82636]

If you scan a monkey and start cloning, it will result in initialization failure.  But something does happen.  The cloner creates a monkey mob inside the cloning pod, and never ejects it.

This results in the cloner being considered occupied and makes it impossible to clone anyone else.

### PR DESCRIPTION
**Pull request by Chuckleberry-Finn**
[Changelogs]: 
:cl: Jittai
fix: Cloning doesn't runtime (and indefinitely get stuck) on cloning non-humans.
/:cl:
 Fixes #35014

### CODE REVIEW

**Comment by arsserpentarium** [comment]
no, we should be able to clone monkey.

**Comment by ChuckTheSheep** [comment]
I'm not removing the ability to, just fixing the bugs that come from trying to.

**Comment by AlexTheSysop42** [comment]
Does this still let you clone other (humanoid) species?

**Comment by ChuckTheSheep** [comment]
Anything under the /living/carbon/human type path.

**Comment by uraniummeltdown** [comment]
Monkeys into a human subtype when?

**Comment by Cyberboss** [comment]
@MoreRobustThanYou

**Review by Cyberboss — APPROVED** [review]

**Comment by MoreRobustThanYou** [comment]
@Cyberboss i don't recall ever making a pr like that

**Comment by ChuckTheSheep** [comment]
I think monkey's may have the dna vars/procs needed, but the cloner only produces human bodys to graft the clonee's vars onto. (which is what caused the runtime)

**Pull request merged**
