### PR TITLE
Makes it less painful to add songs to the disco machine

### PR DESCRIPTION
**Pull request by silicons**
:/ >_<
:cl:
experimental: Songs can now be added to disco machines with add_track(file, name, length, beat). Only file is required, the other 3 should still be put in, though.
/:cl:

### CODE REVIEW

**Comment by Robustin** [comment]
Im pretty sure things break if you set beat to 0.

**Comment by kevinz000** [comment]
Ik

**Comment by Armhulen** [comment]
why would you though

**Comment by Ausops** [comment]
what's length do

**Comment by PKPenguin321** [comment]
It displays the length in seconds of the song when it's selected on the machine I think

**Comment by Ausops** [comment]
oh I see thanks, thought it was something entirely else

**Comment by kevinz000** [comment]
@PKPenguin321 It cuts off the song after the length expires so it actually matters (unfortunately)

**Pull request merged**
