### PR TITLE
[NO GBP] Fixes signal override and probably other related runtimes during area editing with station blueprints

### PR DESCRIPTION
**Pull request by SyncIt21**
## About The Pull Request
Fixes a tiny mistake i made in #73850 which caused a hell a lot of signal override runtimes during area editing with station blueprints. It happens allow it.

## Changelog
:cl:
fix: signal override & other area sensitive runtimes during area editing with station blueprints
/:cl:

### CODE REVIEW

**Comment by SyncIt21** [comment]
@ZephyrTFA , final patch.

**Comment by SyncIt21** [comment]
It's one "word" of code, anyone merge/review?

**Comment by SyncIt21** [comment]
How has one "WORD" of code gone unmerged this long???

AHHHHHHHHHHHHHHHHHHHH!!!!

**Comment by ZephyrTFA** [comment]
because I forgor

**Pull request merged**
