### PR TITLE
Allows admins to spawn atoms without calling Initialize

### PR DESCRIPTION
**Pull request by Cyberboss**
@PKPenguin321 Here you go

### CODE REVIEW

**Comment by MrPerson** [comment]
What's the use case here exactly?

**Comment by Cyberboss** [comment]
Setting variables before Initialize is run. E.g. button ids

**Comment by MrPerson** [comment]
Wouldn't it make more sense to just recall the setup proc(s) whenever the vars change?

**Comment by PKPenguin321** [comment]
nice

**Comment by Cyberboss** [comment]
Initialize is not engineered to be able to handle being called twice

**Comment by MrPerson** [comment]
There's a reason I said setup proc(s) and not Initialize(). For example when you change radio frequencies, I believe there's a proc called like set_frequency() or something like that. You can set it to call that function if an admin vv's the frequency var.

Basically what I'm getting at is that this is a workaround for the fact buttons (or whatever, I'm sure it's more than just buttons) are poorly coded so why not just fix buttons instead?

**Comment by AnturK** [comment]
Yeah, i agree this seems like a crude hack around bad code.

**Comment by RemieRichards** [comment]
The real fix has been shown above, override the vv var procs to update these on a case-by-case basis,

**Pull request closed without merging**
