### PR TITLE
Rename LICENSE-AGPLv3.txt to LICENSE

### PR DESCRIPTION
**Pull request by Cyberboss**
For github auto-detection

### CODE REVIEW

**Comment by DoctoreMad** [comment]
Change the license to WTFPL while you're at it.

**Comment by optimumtact** [comment]
While we're living in DoctoreMad's fantasy land, lets also change the game to be written in RUST + LUA

**Comment by DoctoreMad** [comment]
For millennia, MANY have tried to stain WTFPL's noble reputation. NONE have won, except in the darkness of their hearts. But WTFPL comes and gives freedom, and you too are invited, for WTFPL loves you unconditionally.

freedom

**Review by duncathan — APPROVED** [review]

**Comment by nicbn** [comment]
wtfpl-strip

**Comment by nicbn** [comment]
By the way we should use MIT.

**Comment by praisenarsie** [comment]
>auto-detection

**Pull request merged**
