### PR TITLE
Better closet sprites

### PR DESCRIPTION
**Pull request by ghost**
29433093-464b10e6-8374-11e7-8dfd-87a23897dd86
29433745-cc25706a-8376-11e7-8183-819e51623310
29433742-cc1e9b00-8376-11e7-9e91-ed79341d8453

:cl: More Robust Than You
spriteadd: Better closet sprites
/:cl:

### CODE REVIEW

**Comment by PKPenguin321** [comment]
3/4ths makes me ANGERY

**Comment by WJohn** [comment]
These are literally the same thing as last time.

#29991

**Comment by Xhuis** [comment]
Misleading title, sprites are not better.

**Comment by Jordie0608** [comment]
I lament that I put more effort into confirming this has the same md5 as the file in #29991 than was put into making this PR.

**Comment by Jordie0608** [comment]
As an aside this'd also break the tiling overlays on guncases that have somehow escaped being removed for horridness.

**Pull request closed without merging**
