### PR TITLE
Bandana GAGS: craftable, dyable and customizable + bandana neckerchief refractor

### PR DESCRIPTION
**Pull request by Ebb-Real**
## About The Pull Request

This PR turns bandanas into GAGS. The PR makes you able to craft a white bandana with 2 cloth, dye bandanas via washing machines, adds the striped bandana and color presets of bandanas to various vendors around the station. With the clothesmate vendor you can color your bandana any color you want.

The PR also refractors the old neckerchief code, it worked badly by deleting the bandana and replacing it with a completely new object. That meant you could just ajust your bandana and reset every single one of its values including health. With this PR it just makes the original bandana able to fit in the accessory slot and adjusts its pixel offset like regularly.

Bandana Preview

Bandana Vendor Preview

## Why It's Good For The Game

Bandanas are more useful for hiding your identity now that gasmasks have a blindness cone, bandana code seemed quite old so now it has been updated. You can now customize your bandana however you want. Makes dyeing clothing more consistent with stuff that would seem dyeable.

## Changelog

:cl:
expansion: Bandanas are now craftable from 2 pieces of cloth.
expansion: Adds the striped bandana and adds various preset colored bandanas to clothing vendors and lockers.
expansion: You can now dye bandanas with washing machines and customize bandanas from inside the clothesmate.
fix: You can no longer reset all the values of a bandana just by adjusting it, this included integrity.
imageadd: Adds bandana GAGS sprites.
imagedel: Removes old non GAGS sprites.
refactor: Refractors bandana neckerchief code.
/:cl:

### CODE REVIEW

**Comment by Colovorat** [comment]
what about durathread bandana?

**Comment by Ebb-Real** [comment]
yeah i should do that one too, i'll get to it and that failed check later. I should head to bed for now.

**Comment by Ebb-Real** [comment]
okay the striped bandana is fucking it up...

**Comment by Twaticus** [comment]
correct me if im wrong but i believe a plus side of GAGs is so you can add bits like the skull or stripe onto the original bandana without needing to make a "skull bandana" or "stripe bandana" sprite

**Comment by Ebb-Real** [comment]
> correct me if im wrong but i believe a plus side of GAGs is so you can add bits like the skull or stripe onto the original bandana without needing to make a "skull bandana" or "stripe bandana" sprite

as far as i know you need seperate greyscale configs and can't add things as an optional layer. You might be able to just put stripes and skull overlays onto the original in a new greyscale config without removing the pixels of the original bandana sprite if you want but i haven't tried it.

**Comment by Ebb-Real** [comment]
i'll try out just using original bandana cloth sprite for the others

**Comment by Ebb-Real** [comment]
it seems to work so i'll do that since it will prob be generally more convenient

**Review by Maurukas — APPROVED** [review]

**Comment by Ebb-Real** [comment]
that should be it

**Comment by Twaticus** [comment]
rad

**Pull request merged**
