### PR TITLE
Removes gorilla mutation chance from monkeys

### PR DESCRIPTION
**Pull request by Cyberboss**
This proved to be too powergamey

Closes #30120

### CODE REVIEW

**Comment by kevinz000** [comment]
cyberboss is a fucking hero.

**Comment by ExcessiveUseOfCobblestone** [comment]
make it a power with the req of FFF

**Comment by ShizCalev** [comment]
oh is that why i randomly had fucking gorillas beating me to death on my test server

**Comment by The-clown-known-as-Pepe** [comment]
add something that turns them into gorrilas as geneticist traitor item?

**Comment by DoctoreMad** [comment]
@The-clown-known-as-Pepe Get this PR merged first

**Comment by Tokiko1** [comment]
Remove them from player-controlled monkeys instead. And maybe make them rarer. Back in the old days, they were pretty damn rare. You'd only see a gorilla a day at best. But if you saw one, you were dead.

**Comment by RandomMarine** [comment]
It should just be a (very) small chance every time the DNA machine is used on a monkey or catatonic human.

Powergamers wouldn't be able to gorilla themselves. Radstorms wouldn't make mass gorillas. Occasional gorilla rampages in genetics would still happen.
The best part is that the risk factor would mean there's an actual reason to ~~kidnap~~ ask an assistant to be a genetics test subject.

**Comment by pubby** [comment]
I'm going to rework it into a random event.

**Comment by Ninja137** [comment]
Make them cultable, remove the ability to do anything ranged, actually make them able to bleed, and probably lower the health a bit and they'd be fine. As-is, they can eat multiple point-blank 12G shotgun shots, while being a superhulk.

**Comment by Ninja137** [comment]
Seriously though, keep it so that they can be made by radiation, at least in some form, even if it's rare.

**Comment by FantasticFwoosh** [comment]
> @Cyberboss: I DED PLS NERF.

would not be the first time either you immediately nerf something after coming in contact with it, and this is more heavy handed than #30120 which addresses the issue by not making it impossible but DIFFICULT to monkeyize & then radiate to a gorilla.

- This change would remove them from normal circulation into a xenobiology only hostile mob meme, which is a objective waste of time outside of scientists rushing gorilla's for strong docility & intelligence/transference potion interactions.

- You also can't stop admins from spamming gorillas either

**Comment by PraiseRatvar** [comment]
@FantasticFwoosh cyberboss plays a round like once in a millennium, this isn't an i ded. this is a much needed balance.

**Comment by PopNotes** [comment]
alternatively, make sentient monkeys NOT ABLE to become gorillas, so they remain entirely a pve hazard

**Comment by Cyberboss** [comment]
That is an inconsistent solution and not happening.

On Aug 23, 2017 10:10 AM, "PopNotes" <notifications@github.com> wrote:

alternatively, make sentient monkeys NOT ABLE to become gorillas, so they
remain entirely a pve hazard

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/tgstation/tgstation/pull/30108#issuecomment-324345183>,
or mute the thread

**Comment by PopNotes** [comment]
inconsistent _how_

**Comment by Cyberboss** [comment]
Something being player controlled should not affect a large gameplay factor
like that. A monkey is a monkey, whether or not it's player controlled
should not affect how it interacts with the environment.

**Comment by FantasticFwoosh** [comment]
On another note @PraiseRatvar the gorilla's endless ability to destroy things probably dont make them too popular with you either for disrupting clock cult modes, especially how often gorilla's tend to end up working for the station's interests to validhunt.

**Comment by GuyonBroadway** [comment]
Isn't it the case that player controlled gorillas can't actually smash walls like their AI controlled cousins?

Incidentally they cannot **"OOK OOK OOGA!"** instead of screaming and get the default "loud and pained whimper" message.

**Pull request closed without merging**
