### PR TITLE
Adds a exodrone subdepartment sign

### PR DESCRIPTION
**Pull request by rageguy505**
## About The Pull Request
Adds a sign for the exodrone rooms
image
## Why It's Good For The Game
Sub-departments usually have signs to find them easier. Exodrone rooms are usually out of the way. 
If you want i could add it to the maps in this PR, like meta's exodrone room in maint.
## Changelog
:cl:
add: Exodrone signage 

/:cl:

### CODE REVIEW

**Comment by rageguy505** [comment]
i added them to the map cause why not, also i removed a fire alarm in the meta one cause it had no firelocks and it took up the wall space

**Review by Maurukas — APPROVED** [review]

**Comment by rageguy505** [comment]
woops

**Comment by Twaticus** [comment]
thats a chair

**Comment by rageguy505** [comment]
its a drone 
image

Also how do you revert a commit, i was trying to fix a map merge issue that popped up

**Review by Wallemations — APPROVED** [review]
Idk anything about the 1000+ code changes but the icon is fine

**Comment by rageguy505** [comment]
> Idk anything about the 1000+ code changes but the icon is fine

i pressed a button and this happened

**Comment by LemonInTheDark** [comment]
> i pressed a button and this happened

You fucked up your git history (I hate git clients so much man)
You need to either fix it, or create a new branch, cherry pick the sprite/code changes you WANT onto it, and pr from that (I would recommend this if you are not comfortable with git).

We cannot do anything with the current state of this pr as merging it would fuck our git history and likely our repo.

If you would like help with this feel free to ask in coding general, should be quite easy to deal with.

**Comment by rageguy505** [comment]
ok easiest thing would be to just make a new one i think

**Pull request closed without merging**
