### PR TITLE
Borers can now no longer take control of implanted people or cultists

### PR DESCRIPTION
**Pull request by jakeramsay007**
:cl:
tweak: Borers can no longer take control of people who have a mindshield implant or are a member of either cult. This however does not stop them from infesting and controlling them through other means, such as chemicals.
/:cl:

This is to solve the issue of borers ruining cult rounds by revealing
every cultist there is, as well as to stop borers from having instant
access to kill weapons by simply infesting a security officer, HoS, or
the Captain.

They're not supposed to be a primary antagonist, just a secondary nuisance. This will help stop borers from being able to become a primary antagonist which can destroy rounds.

### CODE REVIEW

**Comment by Bawhoppen** [comment]
boo :-1: it was a good dynamic of if you fuck up and get borered you get fucked

**Comment by Kraseo** [comment]
or you could do like bay does and make things that cover ears/head make borers unable to crawl into your ear

**Comment by ShadowDeath6** [comment]
https://github.com/yogstation13/yogstation/pull/1168

**Comment by Shadowlight213** [comment]
Add rev and wizard too, if you want to do team antags

**Comment by calzilla1** [comment]
How about we just remove

**Comment by PKPenguin321** [comment]
Might as well do this for any antag

**Comment by TehPear** [comment]
May as well just remove them then.  If we're going to now start playing the game of protecting antagonist positions and security messing from messing with other antagonist positions. That and the fact I can forsee people just wanting mindshields to protect against them.

**Comment by GunHog** [comment]
The mindshield one makes sense, but instead of protecting conversion antags, why not spread the influence from the victim's mind to the borer? Although that could result in Cultist-Changelings or something. I think we need to clarify what borers are intended to be in regards to security, the crew, and other antags.

**Comment by ExcessiveUseOfCobblestone** [comment]
Why I dislike borers reason 532 [although this is just an extension of reason 1, which is they validhunt the primary antagonists of the round as side-antagonists]

**Comment by Super3222** [comment]
Wait - are you guys letting borers do whatever the fuck they want on your server?

**Comment by GunHog** [comment]
We have more freedom in terms of antags than most other codebases (which is a good thing imo)

**Comment by TehPear** [comment]
Also I doubt this will end up resolving issues beyond the fact the borer can't take control to cause problems which in turn will result in assumption of they're implanted or they're some kinda antag when they can't control them.  Another thing for example is borers still within a cultist would be able to hear them whispering their garble and see them do cult things, which they can hivemind that there are cultist to other borers, who can in turn inform other hosts that there are cultist on the station.

In the end I just see this as causing even more issues as people will abuse the fact they can't take control of their host which will result in likely them still outing other antagonist. Which is also pretty big part of how they're suppose to reproduce.

It wouldn't be so bad if there was resistance from being a cultist or mindshield implant from being controlled. Similar to how Shadowling had to break the mindshield implant to convert security. 

In the meantime I'm probably going to have to discuss borers with other admins if other restrictions should be in place for a borer doing certain things.

**Comment by jughu** [comment]
Yes they will know theres cult on the station atleast they will not take control of my ratvar cultist body and destroy the gateway just give borers the same antag status if they go in the brains of cult ((THE POWER OF NARSIE AND RATVAR converts the BORER))

**Comment by kevinz000** [comment]
btw it's not "If you fuck up you deserve it", borers can stun someone long enough to get in them at a range (at the very least they can, even if it's not at range as I'm not sure) and it's impossible to counter without being a changeling or having some kind of adrenals or stimulants.

**Comment by uraniummeltdown** [comment]
Just make the borer Paralyze Victim stun shorter

**Comment by jakeramsay007** [comment]
@TehPear It's not about stopping the cultists or antags from being outed, it's to stop the fact they can take control of a cultist and then kill other cultists like that. There's being an indirect threat, and then there's being a direct threat/godawful nuisance.

**Comment by Super3222** [comment]
You see - with so much freedom with borers they're going to be going vigilante all the time, miss the fact that they're a repopulating hivemind brain slug, and on their merry way fuck over a bunch of other antags actually playing their part.

I don't know what the plan for borers was on your part, but on Yogstation we want them to completely understand and realize that they cannot do anything outside of their objectives (which on our server is escape with X amount of borers and pretty much repopulate). Keep in mind that the situation isn't completely contained, and we're still trying to get some concrete rules posted in big, giant letters somewhere. However the staff on yog (I'm hoping) all has the same mindset on them.

Borers are extremely strong because the way they work gives them the mobility to freeze you, jump into you, and take over your body in less than 30 seconds. That's quite literally the fastest fuck over since magic missle+ei nath. It is that powerful. Now without any rules on how or when to use this great power players are obviously going to use it to their fullest - which is what they're doing right here on your server.

> Just make the borer Paralyze Victim stun shorter

That wouldn't really fix the problem per se. Borers STILL need to get inside of people. Without the stun they're either making a holy cross across their chest and jumping into the middle of a fight to snag somebody already stunned or getting squashed.

**Comment by ExcessiveUseOfCobblestone** [comment]
The problem is it makes sense for borers to give a big middle finger to antags because antags directly, negatively impact their objective [typically in the form of killing [[potential]] hosts].

**Comment by Super3222** [comment]
I think the point is with so much freedom the only thing that'll stop borers is guidelines outside of the code that defy that freedom or more balance PR's that'll completely nullify a borers ability to effect the main antagonists.

**Comment by TehZombehz** [comment]
Muh next level emergent gameplay!

**Comment by Shadowlight213** [comment]
@jakeramsay007
Add the protection to revs as well. Why are you giving it to cults and sec but not revs?

**Comment by jakeramsay007** [comment]
@Shadowlight213 To answer that question, simply because revs are not some sort of special antag. They're regular crewmembers who are tasked with slaughtering heads of staff. They don't get anything special, and they certainly don't have some eldritch god watching over them.

**Comment by jughu** [comment]
*brainwashed

**Pull request merged**
