### PR TITLE
Mimes get a positive mood instead for having a vow active

### PR DESCRIPTION
**Pull request by JohnFulpWillard**
## About The Pull Request

Removes the -8 mood penalty given to mimes for breaking their vow.

This mood penalty was actually a common talking point against my previous Mime PR https://github.com/tgstation/tgstation/pull/74674 and my response was to just remove the mood effect, but no one ended up doing it.
I did get a kneejerk revert PR within 48 hours though, that was cool i guess.

## Why It's Good For The Game

Mimes are a job like every other one on the station, and they should not be punished for taking breaks from it.
It is fine for mimes to break their vow when they need to use text/writing/spells?, it's a sandbox and this is such a weird way to try to limit players. They should want to keep their vow because it's their job not to, not because they will be slow as mods until they can remake it.

Comments argued it should give a positive moodlet so I added that. It's a +2 instead of Clown's +5 because they get spells out of it which is way better than turning yourself into a crawling soap I think.

## Changelog

:cl:
balance: Mimes get a positive moodlet for having an active vow of silence instead of a negative mood effect for breaking it.
/:cl:

### CODE REVIEW

**Comment by atlasle** [comment]
off duty mime is a really funny idea but maybe they shouldn't get to use their mime abilities without having their vow "turned on", dunno if it already works like that

**Comment by JohnFulpWillard** [comment]
It does

**Comment by Fikou** [comment]
i think you should make having the vow on give you a small mood boost

**Comment by Admiral-Gigaton** [comment]
only issue is "MIME SPOKE LYNCH" which will still happen. besides, arent we supposed to encourage the mime to, you know, MIME shit? whats the point if now the only downside is no more invisible walls while you scream "SHITSEC SHITSEC"

**Comment by Fikou** [comment]
mime spoke is a server rule thing, the codebase is separate from the server

**Comment by MrMelbert** [comment]
> i think you should make having the vow on give you a small mood boost

This puts it on par with the clown's +5 (wow +5? that's insane) for wearing their clown shoes

**Comment by ExcessiveUseOfCobblestone** [comment]
> i think you should make having the vow on give you a small mood boost

best way to go about it imo, you should be encouraged to communicate through miming. Things to bypass the restriction seems like an admin avenue based on poor player behavior than something thats fruitful for the code to try to patch out every instance of (that also messes up good faith uses of those items)

**Comment by timothymtorres** [comment]
Yeah, just keep it consistent like the clown's shoes might be the best solution.

**Comment by Singul0** [comment]
Sacrilege

**Comment by EricZilla** [comment]
I always felt it shouldn't give the mood negative while backstage, but this is probably better

**Comment by ATH1909** [comment]
if you don't want to commit to miming things, even in times of crisis, why are you playing a mime? at that point, you're just an assistant with the ability to make walls if he hasn't spoken in a while. the vow means nothing if there's no consequence to breaking it (other than being unable to use a spell that you probably just put on cooldown anyway).

dishonorable cowards, the lot of you.

**Comment by Jezzared** [comment]
Willard, serious question. Do you play mime?
If you do, what draws you to play it? Surely the answer is "because its fun to play a gimmicky role where my job is to entertain the crew, _and i can't talk while doing it_."

De-fanging this will only result in LESS cool mimes and interesting roleplay elements. A mime breaking their vow should be an exceptional act, whether it is to save someone, declare their evil presence, or make an exceptional joke in a split second.

You want to talk and be funny? Become a clown.

People talk about a removal of soul all the time in regards to spriting. I consider _this_ kind of thing to actually be a soul-killer. The more we homogenize jobs, the less jobs mean. Let jobs have their cool and quirky elements.

**Comment by optimumtact** [comment]
We need to have a conversation as headcoders about what we want to do here around the gimmick jobs being abandonable.

**Comment by Spookuni** [comment]
For as long as mimes get access to fucking magic breaking their vows should be a big deal - as others have mentioned exceptional circumstances can justify breaking their oath; but it absolutely shouldn't be something they can just walk away from when they don't feel it, especially since they can just turn their oath back on when the cooldown on it comes back up again.

**Comment by JohnFulpWillard** [comment]
Headcoder decision is Mime vow being broken should be permanent (and some stuff about opening a job slot?)

**Comment by CMDR-Gungnir** [comment]
> Headcoder decision is Mime vow being broken should be permanent (and some stuff about opening a job slot?)

The funniest moment I've ever had with either of the Entertainer jobs is a Mime in the Maints Tunnels during a radstorm taking off his mask, smoking a cigarette, and saying "I fucking hate this job." before putting the cigarette out, putting his mask back on, and walking away.

Not to mention the lack of ability to write on paper when the Vow is active (while some people can and will just use it in place of talking, there are others who need it for a gimmick), this is just a horrible idea.

**Comment by optimumtact** [comment]
you actually can write on paper, have been able to the entire time the change was active.

**Comment by CMDR-Gungnir** [comment]
> you actually can write on paper, have been able to the entire time the change was active.

Every time I've tried with anything other than the Mime's Crayon, it's told me that my vow is preventing me.

**Comment by optimumtact** [comment]
I guess mso failed to patch it on ever server then

**Pull request closed without merging**
