### PR TITLE
Bullets no longer directly damage the SM

### PR DESCRIPTION
**Pull request by Ghilker**
## About The Pull Request
Bullets get consumed as everything else

## Why It's Good For The Game
4 shots to the super dusting crystal shouldn't instantly delaminate it

## Changelog

:cl:
balance: bullets no longer directly damage the SM
/:cl:

### CODE REVIEW

**Comment by Bawhoppen** [comment]
They get dissolved upon contact, but the law of conservation of momentum still exists, and the kinetic energy still get transferred to the crystal.
Nothing wrong at all with being able to sabotage the SM... it should be a very secure item that requires protection.

**Comment by Maurukas** [comment]
How exactly does this benefit the game? What current ballistic weapon can delam in only four shots? The Makarov takes slightly less than two full mags to trigger a delam. The .357 revolver requires 7 shots. In either case, these items will cost the majority of a traitor's TC, and a reasonable bit of preparation to do.

**Comment by Ghilker** [comment]
> Maurukas suggested this to me:
> 
> > I proposed an alternative of just not allowing bullets to damage it over 700 (the threshold where it starts screaming in Common), so that the crew has an opportunity to react.
> 
> I like this better.

why the SM should stop at 700 damage from bullets? doesn't make sense either it takes damage or it doesn't

**Comment by magicaltheonething** [comment]
why does the SM constantly have to be given stupid changes, first its removing rad collectors for the SM, making most gasses obsolete if they dont make lightning, now we want to make it so we cant damage the SM? the only way this continues is eventually making the SM a glorified turbine at this point, i dont see the reasoning or point of any of these new editions. The SM is meant to be dangerous, its meant to fuck you over if you dont have a rad suit, or magboots, or put in the wrong gas, why do we keep making something that was intentionally dangerous less and less dangerous, basically removing the point of it from the game.

**Comment by magicaltheonething** [comment]
> why does the SM constantly have to be given stupid changes, first its removing rad collectors for the SM, making most gasses obsolete if they dont make lightning, now we want to make it so we cant damage the SM? the only way this continues is eventually making the SM a glorified turbine at this point, i dont see the reasoning or point of any of these new editions. The SM is meant to be dangerous, its meant to fuck you over if you dont have a rad suit, or magboots, or put in the wrong gas, why do we keep making something that was intentionally dangerous less and less dangerous, basically removing the point of it from the game.

Also i can now tesla the SM at round start, whereas before it took about 20 minutes to get everything set up for guarantied overcharged tesla.

**Comment by Mothblocks** [comment]
Merged #62079 instead

**Pull request closed without merging**
