### PR TITLE
Fixes the syndicate pistol's name

### PR DESCRIPTION
**Pull request by Iamgoofball**

### CODE REVIEW

**Comment by Shapsy** [comment]
goof no

**Comment by Cheridan** [comment]
up/downvote war go

**Comment by Armhulen** [comment]
ooooh my god first grilles and now this

**Comment by Zilenan91** [comment]
Again?

**Comment by Cheridan** [comment]
um sorry kor the upvotes are winning

**Comment by KorPhaeron** [comment]
I'm not getting these fast enough

**Comment by optimumtact** [comment]
@Cheridan are you blind?

**Comment by Cheridan** [comment]
they were winning earlier

**Pull request closed without merging**
