### PR TITLE
Edits security temperature gun description

### PR DESCRIPTION
**Pull request by Bawhoppen**
:cl:
add: The security temperature gun has a new description.
/:cl:

Sometimes some important events must be immortalized in history.

### CODE REVIEW

**Comment by LemonInTheDark** [comment]
This version of the weapon is actually older then that issue report, and there's a good chance its description is already a nod to the uh, incident https://github.com/tgstation/tgstation/pull/19807

**Comment by Bawhoppen** [comment]
> This version of the weapon is actually older then that issue report, and there's a good chance its description is already a nod to the uh, incident #19807

I considered it may be, but this version is a little more explicit in my eyes, since it's referencing the person who died to it, which was the meme, rather than whoever killed them with it, which was never really publically known.

**Comment by Mothblocks** [comment]
too on the nose, the older one makes me laugh whenever i think about it

**Comment by sirnat** [comment]
I have made it into the history of TG in a description, isn't this considered a wonderful thing? <3

**Comment by Mothblocks** [comment]
to be fair deswords probably should reflect temperature gun shots its an oversight that they dont

on the other hand...

**Comment by sirnat** [comment]
Im glad they didnt and it caused me to make a rage post <3

**Pull request closed without merging**
