### PR TITLE
Fixes an issue with /proc/truncate

### PR DESCRIPTION
**Pull request by ZephyrTFA**
## About The Pull Request

Truncate currently just flat out returns nothing if the string isnt above the max length.
This fixes that

## Changelog
:cl:
fix: Resolves my sanity as truncate now returns a valid value when it does nothing
/:cl:

@Mothblocks

### CODE REVIEW

**Comment by Mothblocks** [comment]
whatd i do

**Comment by ZephyrTFA** [comment]
> 
> 
> whatd i do

I blame you as the cause of this

**Comment by Mothblocks** [comment]
um 
image

**Comment by ZephyrTFA** [comment]
> 
> 
> um
> image

I reject your facts and blame you anyway

**Comment by ZephyrTFA** [comment]
Also has this really been sitting under the hood for almost an entire year
🤡

**Pull request merged**
