### PR TITLE
Removes freon and water vapor from the game

### PR DESCRIPTION
**Pull request by lzimann**
:cl: Lzimann
del: The age of Mr.Freeze is now over.
/:cl:

in the end it was just a bad and bugged meme

Also removes water vapor, I don't think adding low effort grief gas is a good idea.

CODER EDIT:
Closes #20297

### CODE REVIEW

**Comment by evsey9** [comment]
no

**Comment by ChangelingRain** [comment]
END THE AGE OF ICE

**Comment by InsaneHyena** [comment]
The cold never bothered me anyway

**Comment by Lexorion** [comment]
Fix Freon and readd it.

**Comment by Incoming5643** [comment]
Fix Freon then remove it

**Comment by PKPenguin321** [comment]
:-1:

**Comment by GunHog** [comment]
Goof may have a tenancy to add broken features and lacks understanding of the word "test", but he is braver than most coders. Freon could be a very good feature once fixed and brought up to snuff.

**Comment by PKPenguin321** [comment]
There is also a PR with loads up fixes up right now

**Comment by KorPhaeron** [comment]
Can you please just remove it from the maps for now since goof is allegedly fixing it?

**Comment by lzimann** [comment]
That still doesn't resolve the problems of watchers completly fucking you over

**Comment by TechnoAlchemisto** [comment]
The freeze bolt system needs to be fixed and not locked behind a large PR, it makes fighting mobs on lavaland 10 time harder.

**Comment by Alek2ander** [comment]
Winter is here

**Comment by bgobandit** [comment]
then make watchers less bullshit, don't throw out freon over such a small ass thing

**Comment by lzimann** [comment]
and freon is stupid tbh

**Comment by PKPenguin321** [comment]
You're stupid

**Comment by Iamgoofball** [comment]
@lzimann you realize the rework PR that's up makes ice cubes freon only, right

**Comment by KorPhaeron** [comment]
@Iamgoofball 

You tied it to a new feature though so it'll be in merge hell forever

**Comment by AdamElTablawy** [comment]
then split it up

**Comment by Iamgoofball** [comment]
@KorPhaeron :^)

**Comment by TechnoAlchemisto** [comment]
you should probably not hold an important fix hostage with your feature

**Comment by Dorsisdwarf** [comment]
Hell yes 

end the monopoly of retarded features being added and never, ever removed

**Comment by kevinz000** [comment]
@TechnoAlchemisto That's why we revert those features to teach him not to.

**Comment by Iamgoofball** [comment]
Fuck you.

**Comment by Iamgoofball** [comment]
You're an asshole.

**Comment by PKPenguin321** [comment]
:-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: water vapor is the best

**Comment by lzimann** [comment]
\> the best \>minutes of making everything wet simply by opening a canister

**Comment by PKPenguin321** [comment]
fuck yeah dude

its my new favorite cleaning tool as janitor, it's fucking excellent. set pressure to like 106 or something then turn it on and off really fast over messes.

**Comment by Iamgoofball** [comment]
that was its point too

clean excessively large messes

**Comment by optimumtact** [comment]
What killed the dinosaurs?

The ice age.

**Pull request closed without merging**
