### PR TITLE
Materials now use color matrices

### PR DESCRIPTION
**Pull request by Time-Green**
Material colors were quite ugly and unbearable. I used color matrices to make them less ugly and more bearable. Still not perfect, but looks alot better.
Example:
image
From left to right: Uranium, Plasma, Silver and Gold

Could probably be better, but I'm still experimenting with matrices.

:cl:
tweak: Material objects have a better color
/:cl:

### CODE REVIEW

**Comment by Qustinnus** [comment]
👍 


I think 513 will be the version that really lets us make materials look nice. (By letting us do things like the shimmer effect nicely)

**Comment by Qustinnus** [comment]
Can you post pics of the other materials? Preferably on the existing items that can be made out of mats. (Tables, chairs, toolboxes, armour)

**Comment by MrPerson** [comment]
How are you arriving at these particular matrices?

**Comment by Time-Green** [comment]
@MrPerson
I trial & error’d a lot and looked up some documentation on them.
Basically just use one matrix and then keep varediting them. 

It practically came down to this for simple colors:
First element red: color you want it to be
Second element green: color you want but very dark
Third element blue: color you want but slightly differend and very dark
Fourth element alpha: this is alpha, don’t change

Gold and silver were easy because they were mainly white and yellow,  they were pretty bright so I could just lighten them up and shift them towards the color I needed.

Uranium and plasma were more difficult, because they were darker by nature,  and included more trial and error. I don’t like how they turned out as much comprared to silver and gold.

I may give it another go by eliminating colors from uranium and plasma, instead of adding them.

**Comment by ArcaneMusic** [comment]
This is actually really cool to have as an option.
That said, mind throwing in a comment somewhere in the file to explain what you just explained here? Otherwise it'll be hard to pick up how this uses the color component here.

**Pull request merged**
