### PR TITLE
Gives cyborgs respective radio channels.

### PR DESCRIPTION
**Pull request by Kelenius**
## About The Pull Request

Gives the cyborgs access to their department's radio:

- Medical gets medical.
- Engineering gets engineering.
- Service and Janitor get service.
- Mining gets supply and science.
- Security gets security. In case it's enabled, spawned, etc.
- Peacekeeper gets nothing. You're not security, you have no business listening to them.
- Standard also gets nothing. Pick a side, filthy centrist.

This channel is not related to the encryption key that can be installed into any cyborg and works in addition to they key, if installed.

I didn't touch the syndicate cyborgs, they still use an encryption key. I don't want to mess with radio code more than necessary and their encryption key already gives them everything they want, so it's unlikely someone will ever mess with it. Not broken, no fixes.

## Why It's Good For The Game

It's a convenience change for the cyborgs. Engie, med, and mining need their channels to coordinate work. Service and janitor need their channels to dull the pain of being service/janitor borg.

## Changelog
:cl:
add: Cyborgs (except Peacekeeper and Standard) now have access to their department's radio.
/:cl:

### CODE REVIEW

**Comment by TheMidnightRose** [comment]
Wouldnt it be better to give Mining cyborgs the miner's comm key? Which is Sci/Suppy

**Comment by Kelenius** [comment]
A fine idea. I forgot they get science.

**Comment by TheVekter** [comment]
Good shit. Very nice.

**Comment by MacBlaze1** [comment]
Very nice shit, years ago I kept having to ask sci to install an engie key

**Comment by ATH1909** [comment]
Make sure that this PR won't run into the same problems that Fulp's version of this PR concept did.

**Pull request merged**
