### PR TITLE
Morph virus

### PR DESCRIPTION
**Pull request by ghost**
:cl:
add: A virus (adminspawn only for now, I plan to add a 20TC traitor item that contains it but it's getting late) that turns you into a morph slowly
/:cl:

It has no cure, but several symptoms are PRETTY obvious to anyone around, so they might try to kill/borg you.

### CODE REVIEW

**Comment by awesine** [comment]
this already exists 
it's on lavaland

**Comment by Kromgar** [comment]
This is literally in the greed ruin

**Comment by gt33** [comment]
Huh?

**Comment by awesine** [comment]
he means it's on the lavaland ruin
called
the
greed ruin

**Comment by Kromgar** [comment]
IT EXISTS. THERE IS A DISEASE THAT TURNS INTO MORPH

**Comment by gt33** [comment]
oh ok

**Pull request closed without merging**
