### PR TITLE
Moves all RnD's core consoles to the bridge.

### PR DESCRIPTION
**Pull request by ArcaneMusic**
## About The Pull Request

Removes science's access to a Core RnD Console. The only access science will have to core RnD will be the RD, from the Bridge. 

This is Orange's idea.
https://tgstation13.org/phpBB/viewtopic.php?f=10&t=25889
 
## Changelog
:cl:
del: Removes all core RnD Consoles from the Map, except for the bridge.
tweak: Replaces a console with a Core Console on each map's bridge.
/:cl:

### CODE REVIEW

**Comment by CRITAWAKETS** [comment]
Techwebs needs to be fleshed out before the final solution is done, just saying. Having a shift without any heads of staff or no RD will result in no research. (And you bet your ass the HoS or captain wont research anything)

**Comment by optimumtact** [comment]
it's oranges, but thanks

**Comment by HomocidlePancakes** [comment]
Why bridge? If it’s RD job, then why not RDs office?

**Comment by necromanceranne** [comment]
You can screwdriver RnD consoles to get a core console. You might want to add a spare core rnd console to the RD's locker and prevent the other boards from being made into core rnd consoles.

**Comment by Fikou** [comment]
> You might want to add a spare core rnd console to the RD's locker 

>implying RD players wouldnt upgrade their department with a core console every round

**Comment by Tharcoonvagh** [comment]
What's the difference?

**Comment by daklj** [comment]
>yet more power to heads

also you forgot the Why It's Good For The Game part

**Comment by ExcessiveUseOfCobblestone** [comment]
This has always been a part of the Techweb design, it's just that no one cba to do it (I think we had one PR earlier but it got closed cause someone wanted it on modular computers instead lol...)

**Comment by ExcessiveUseOfCobblestone** [comment]
> Techwebs needs to be fleshed out before the final solution is done, just saying.

Not sure how tech webs being fleshed out or not makes them more apt for untethering to science. If anything fleshing it out with the current dynamic being 'science owns it' makes it harder for the """"final solution"""" to be reached.

**Comment by AdamElTablawy** [comment]
So, what, science can't do R&D anymore? It's just the RD's job?

**Comment by ExcessiveUseOfCobblestone** [comment]
It would be the job of your department head to get tech related to your department.

Preferably we'd have it in a way you can queue techs so you don't have to back/forth.

**Comment by AdamElTablawy** [comment]
Okay, so what do scientists do then? Anything replacing R&D in science itself since it's on the bridge now or are R&D scientists supposed to look for another D to fuck themselves with

**Comment by ExcessiveUseOfCobblestone** [comment]
the latter

**Comment by Daxxed** [comment]
If I have to make myself valid as a miner to get some research you bet that console is coming with me to lavaland

**Comment by trollbreeder** [comment]
If you're leaving it on the bridge, everyone will forget about it because that's clearly not the area it belongs to, and it's unnoticeable next to all the OTHER consoles.
Scientists will rush to make the console so they can do 1/3rd of their job.
If you make it unable to be built, it's "Hey science where is my mining tech" except it's everyone screeching now, including scientists.

I don't see why this is good for the game. Enlighten me.

**Comment by dablusniper** [comment]
Why is this a thing

Why was this merged

What is going on 

aaaaaaaaaaaaaaaaaaaaa

**Comment by DinkleNH** [comment]
Ah yes, castrating science. Its good for the game, we promise.

**Comment by ExcessiveUseOfCobblestone** [comment]
Personally I'd rather tell you to go something other than scientist rather than say "why don't you just sit at the RND console and unlock tech". It's not a task, by design, that someone is meant to be babysitted for the duration of the round.

**Comment by bobubeu** [comment]
Yes, people that do R&D most of the time don't just AFK sit there at the console, they do other stuff but often that other stuff involves specific research which needs to be done to even access that stuff. Now they can't even do it because the research is entirely gated behind heads and whatever they want so the best chance they've got is a good captain or a head that actually listens to there pleas of what they want to be researched

**Comment by optimumtact** [comment]
No worries mate, she'll be right

**Comment by ExcessiveUseOfCobblestone** [comment]
y-y-you mean nanites lol?

**Comment by bobubeu** [comment]
Yes, nanites are a prime example since there time-sensitive due to requiring a unique currency generated by nanites themselves to research further nodes and the fact that the longer the shift has gone on for the less likely it is that people will pick up nanites. Among other projects like making your own medbay and or chemistry, setting up quantum pads, teleporters, launchpads ect. Not even taking into account actual job aspects that they need to do every shift such as mining gear research and getting better parts to upgrade the station, orm with which will now be delayed or not happen at all.

**Comment by saprasam** [comment]
can you atleast wait until theres a good reason to move the r&d console (aka. whatever the hell changes you're making) before you actually do it

**Comment by cacogen** [comment]
I thought this was supposed to be a protest PR but now we have to deal with this dumb shit

**Comment by Relaxem80** [comment]
So A: I'm just going to screwdriver the console so we can use it like normal
B: Nobody touches Nanites OR the Experimentor because it's unintuitive, functionally redundant to cybernetic surgery, or so hideously documented that nobody can even BEGIN to touch the things associated with it. Your gating technology to force people to use your half-finished, poorly documented, snowflake department.

**Comment by AdamElTablawy** [comment]
> So A: I'm just going to screwdriver the console so we can use it like normal
> B: Nobody touches Nanites OR the Experimentor because it's unintuitive, functionally redundant to cybernetic surgery, or so hideously documented that nobody can even BEGIN to touch the things associated with it. Your gating technology to force people to use your half-finished, poorly documented, snowflake department.

everyone uses nanites and they're both well documented and relatively easy to understand after about three minutes, so i think you might just have a bad case of stupid

**Comment by ATH1909** [comment]
Don't give Rohesie shit for merging this too early; the immediate merging of this PR was mandated by oranges (with a threat of freezing all code changes until it was merged): https://cdn.discordapp.com/attachments/326831214667235328/691556083172638780/unknown.png

**Comment by ATH1909** [comment]
IMO, we should just let both heads of staff AND scientists research techs.

**Comment by optimumtact** [comment]
he fell for it lmao

**Comment by cacogen** [comment]
"I was only pretending"

**Comment by adamkad1** [comment]
So basically, make golems useless, and let one hippy with screwdriver disable research entirely? epic

**Pull request merged**
