### PR TITLE
Resprites holochips

### PR DESCRIPTION
**Pull request by JStheguy**
[Changelogs]:
:cl: Nanotrasen Reserve Bank
imageadd: Holochips have been given a noticeable redesign, and now use a combination of color and shape to show how many credits are in an individual chip, along with using a new coloring scheme outright.
tweak: Holochips now show how many credits they contain in their name.
/:cl:

[why]: The current holochip sprites aren't very good, but these are at least an improvement. Plus the new visual scheme is more granular than the old one, making it easier to immediately tell the difference between, say, a 10 credit chip and a 20 credit chip.

virgin old sprites:
holocraps

chad new sprites:
holochaps

ive lost control of my life

### CODE REVIEW

**Comment by XDTM** [comment]
Good sprites, although i think you should remove the x1000 denomination in favor of a x1, so reaching another zero changes colors right away instead of having to reach 5.

**Comment by AnturK** [comment]
If you want to be real nerd make these use resistor codes.

**Comment by Militaires** [comment]
tbh you should've used greyscale and overlays

**Comment by XDTM** [comment]
but it does use greyscale and overlays

**Comment by Borisvanmemes** [comment]
These look GOOD.

**Comment by JStheguy** [comment]
> If you want to be real nerd make these use resistor codes.

Honestly I was originally  going to try  something like that but I couldn't figure out how to isolate the significant figures in a half-decent manner.

**Comment by bgobandit** [comment]
these look good but the old sprites look more like chips

**Comment by octareenroon91** [comment]
> > If you want to be real nerd make these use resistor codes.
> 
> Honestly I was originally going to try something like that but I couldn't figure out how to isolate the significant figures in a half-decent manner.

What part of sig figs wasn't working for you?

**Pull request merged**
