### PR TITLE
Removes illegal src edits and adds a lint for them

### PR DESCRIPTION
**Pull request by stanalbatross**
## About The Pull Request
removes edits of `src`, replaces them with proper vars

add a lint to prevent src editing

this is a copy in spirit of https://github.com/tgstation/TerraGov-Marine-Corps/pull/6032

## Why It's Good For The Game
less illegal src edits

## Changelog
:cl:
code: Removes illegal src edits and adds a lint for them
/:cl:

### CODE REVIEW

**Comment by Kapu1178** [comment]
what if someone wants to use `src = null`?

**Review by Mothblocks — CHANGES_REQUESTED** [review]
I bet you dollars to donuts your changes to admin code do not work.

Admin verbs, even when using `/datum/admins/proc`, have `src` set to the client/mob. Your code almost certainly breaks that.

Removing it in minerals is fine because `src` changes for turfs anyway.

**Comment by stanalbatross** [comment]
> I bet you dollars to donuts your changes to admin code do not work.
> 
> Admin verbs, even when using `/datum/admins/proc`, have `src` set to the client/mob. Your code almost certainly breaks that.
> 
> Removing it in minerals is fine because `src` changes for turfs anyway.

resolved, the tag verb was breaking, only needed a few src -> holder changes to work

**Comment by Mothblocks** [comment]
I'm not really sure what the problem with casting `src` early in those instances is, though--it's papering over a very weird BYOND quirk and removing them makes them even weirder IMO

**Comment by Mothblocks** [comment]
Like they aren't illegal at all, you just wrote that

**Comment by stanalbatross** [comment]
> Like they aren't illegal at all, you just wrote that

nah it was the tgmc guy who wrote that

**Comment by jlsnow301** [comment]
you wouldn't download a src

**Comment by Mothblocks** [comment]
I think the code this is replacing is fine because `src` cannot be trusted in those normally, but because `src` is often implicit, maintainers (and linters) would never know to look for it. I would instead rather this be a macro that you drop at the top of the procs that guarantees `src` is `/datum/admins`

**Pull request closed without merging**
