### PR TITLE
Better Supermatter Sounds

### PR DESCRIPTION
**Pull request by actioninja**
## About The Pull Request

Replaces supermatter sounds with a new sound system for it.
Works based on having a constant drone that randomly plays accent noises over it.
https://www.youtube.com/watch?v=k5kKc5mpl-A&feature=youtu.be

I've barely tested this

## Why It's Good For The Game

the old sounds are terrible

## Changelog
:cl:
soundadd: New supermatter sound system
/:cl:

### CODE REVIEW

**Comment by actioninja** [comment]
Testmerge this before full merging I was seeing some weird behavior on the SM when testing

**Comment by bigfatbananacyclops** [comment]
sounds more spookier and anomaly-ish, like a sound a weird vibrating metal would do. It also sounds like a saber for some reason, may i recommend what ever sound you used for the eswords slashes?

**Comment by TheSilverNuke** [comment]
It's got a bit of echoed reverb to it that I think could  use some cleaning up, outside of that not bad. Though I will say that the old sounds were good too, not terrible at all actually. I don't really mind one or the other, but this one sounds like it's got a lot of energy it's barely holding onto which I really like.

**Comment by PKPenguin321** [comment]
Could this be made to respect the ambiance toggle preference if it doesn't already

**Comment by YakumoChen** [comment]
Good, the old supermatter sounds were ear rape, especially if you were orbiting it where it was loud as shit.

**Comment by actioninja** [comment]
@PKPenguin321 unfortunately no because this uses playsound, and playsound doesn't support anything like mutable channels at the moment.

**Comment by PKPenguin321** [comment]
could you not just do something like
```proc/playambiance(user, sound)
     if(user.ambience_pref = FLASE)
          return
     playsound(user,sound)

**Comment by actioninja** [comment]
playsound doesn't play to users/clients it plays from a location which is then sent to clients in audible distance.
I don't even think it's needed, it's a gameplay sound, it's coming from something you can see and affect. Players looking to just disable ambience sounds with no source are going to accidentally disable something that tells you some gameplay info as well.

**Pull request merged**
