### PR TITLE
Gameplay bans 

### PR DESCRIPTION
**Pull request by ghost**
woops i forgot, can't be reopened by a maintainer if I rebase

:cl: darkbitt
admin: Added gameplay bans (softbans).
/:cl:

### CODE REVIEW

**Comment by Armhulen** [comment]
third time

**Comment by optimumtact** [comment]
I believe we have denied this before, because it has no value

**Comment by Armhulen** [comment]
ok but maybe rebasing isn't good for tiny prs

**Comment by ike709** [comment]
Give up morty. It's been denied already.

**Comment by awesine** [comment]
what does this do? only allow you to observe?
this actually sounds nice

**Comment by Armhulen** [comment]
@ike709 two head admins and the head coder said yes

**Comment by deathride58** [comment]
This is actually an alright feature, though. Shoving someone into a spectator-only position is actually a lot better than outright denying them access to the server if they've got a reason to be in a spectator position, like if they're an admin, mentor, or dev.

It also means folks like MRTY don't have to ban evade if they want to see their big reworks/features being testmerged ingame, which saves a lot of trouble for everyone involved.

**Comment by optimumtact** [comment]
MRTY shouldn't have got his dumb underage ass banned then

**Comment by MoreRobustThanYou** [comment]
🤔 How do you KNOW i'm underage, HMMMMMM?

**Comment by Qustinnus** [comment]
because if you aren't you would have been in a mental institute for your behavior

**Comment by optimumtact** [comment]
@MoreRobustThanYou because of the way you act

**Comment by deathride58** [comment]
Gameplayban + OOC ban + deadchat ban, then

Tada, now an idjit of a dev can observe their testmerged PRs without directly ruining the experience for other players.

**Comment by Armhulen** [comment]
yeah it shouldn't allow for talking in ooc or deadchat

**Comment by MrStonedOne** [comment]
we already have ooc bans and deadchat bans, those can be applied on their own if needed

**Comment by optimumtact** [comment]
Actually some wayt o apply them all at once would be useful.

Admins often complaint about having to jobban people across a range of jobs that are related

**Comment by MoreRobustThanYou** [comment]
THERE IS A WAY TO JOBBAN SOMEONE FROM AN ENTIRE DEPARTMENT

**Comment by optimumtact** [comment]
I said a range of jobs that are related MRTY

**Comment by Armhulen** [comment]
i'm trying to get this pr in but you're acting like a got damn fool mrty what r u doin

**Comment by MoreRobustThanYou** [comment]
@optimumtact oh ok

**Comment by KorPhaeron** [comment]
Having thought about this more, it is niche enough that we can just mass jobban and make a verbal agreement with people we want "gameplay" banned and perma them if they do anything but observe

No need to clutter up the code with something we may have wanted to apply to 2 or 3 people ever in server history

**Comment by MrStonedOne** [comment]
@optimumtact that sounds unrelated to this pr.

But ya, at some point a way to do checkbox based job banning would be nice. likely above morty's pay grade since it would need to auto-check for the department ones.

I'm thinking it would become part of a job ban datum system with things to generate the html from the datums. because atm every modification to job bans has four spots to edit just to add support for banning and that shouldn't be the case. (for example, Morty missed the one for the manual ban panel's drop down.)

**Pull request closed without merging**
