### PR TITLE
fixes scp ruin

### LINKED ISSUE #37253: SCP Ruin - Turret & Mob Factions are incorrect
Issue reported from  Round ID: 86598 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 512
the mobs and the turrets fight at round start because they have different faction and also trigger all the traps really shitty ruin i ll add

### PR DESCRIPTION
**Pull request by Tlaltecuhtli**
it works i guess should i just remove the mimics ?

fix:scp faction

fixes #37253

### CODE REVIEW

**Comment by BeeSting12** [comment]
you fucked up the changelog

**Comment by 81Denton** [comment]
:cl:
fix: fucking morty
/:cl:

**Comment by Tlaltecuhtli** [comment]
last time i made a changelog maintainers deleted it

**Comment by Cyberboss** [comment]
A change that is visible to players should have a changelog

**Pull request closed without merging**
