### PR TITLE
Pride week + rainbow floor tiles

### PR DESCRIPTION
**Pull request by Mothblocks**
## About The Pull Request
Adds pride week from June 23rd to the 29th, and makes the floor tiles rainbow.

dreamseeker_2021-05-22T00-29-21
dreamseeker_2021-05-22T00-29-31
dreamseeker_2021-05-22T00-30-07

Doesn't include rainbow jumpsuits or anything else. I just like the floor tiles.

## Why It's Good For The Game
It's cute.

## Changelog
:cl:
add: From June 23rd to June 29th, celebrates pride week w/ rainbow floor tiles.
/:cl:

### CODE REVIEW

**Comment by LemonInTheDark** [comment]
very cute

**Comment by uwubli** [comment]
very cute and bright, enough to be easy to notice but not enough to get eyestrain from it. love it!!

**Comment by maxymax13** [comment]
it's like april fools tiles but it's gay instead of giving all the players looking at it brain damage

**Comment by carshalash** [comment]
Can this come with renaming all knee-length socks to programmer socks for the duration of the week?

**Comment by toomykins** [comment]
fucking lmao

**Comment by interestingusernam3** [comment]
THE

1 WEEK OF PANIC BUNKER EVENT

**Review by Cyberboss — APPROVED** [review]

**Pull request merged**
