### PR TITLE
New Command Formal/Parade drip & Formal Clothing Crate

### PR DESCRIPTION
**Pull request by axietheaxolotl**
## About The Pull Request

Adds brand new Command parade clothing:

Layer 2

- HoS Dress
- Captain Female Parade, and Dress
- HoP Male, Female Parade, and Dress

Also ports over the HoP's formal jacket I did for another PR. #62917

image

image

Also, Formal outfit crate in the meeting room. Clementine wanted this.

## Why It's Good For The Game

Mandarin wanted a crate for formal clothing, it has been done and placed in the Meeting Room. Head man wanted it, so he gets it.

The clothing is cool, SS13 is my favourite dress up game. And, HoP has a severe lack of drip, it needs to be supplemented.

## Changelog

:cl:
add: Formal Clothing for the HoP, HoS, and Captain. Parade clothing crate in the meeting room.
imageadd: Slight recolouring of the HoS' parade outfit
/:cl:

### CODE REVIEW

**Comment by axietheaxolotl** [comment]
>six reviewers

this is a solid bruh moment

**Comment by axietheaxolotl** [comment]
fucking CI, god damnit.

**Comment by JohnFulpWillard** [comment]
This gives HoP access to HoS-level armor, why not put them all in their garment bags?

**Comment by Googles-Hands** [comment]
> This gives HoP access to HoS-level armor, why not put them all in their garment bags?

Oranges changed his mind and want's a clothing crate/vendor in the meeting room, not a fan of it but it's what he wants for some reason.

Also im not sure if the formal clothing has HoS armour value but if it does then it should really be moved to the locker/garment bag, I think exceptions can be made for those.

**Comment by Googles-Hands** [comment]
Actually doesn't this go against the clothing hackmd?

>**Avoiding endless new uniform sprites**
Heads of Staff can have a formal uniform, but only that one alternate, and the formal uniform must go in the formal clothing locker in the heads of staff meeting room/break room in the bridge

Unless you are removing the old formal clothing this is just bloat, maybe just keep that stuff with Skyrat.

**Comment by Farquaar** [comment]
The female sprites don't look like parade uniforms- they look like cocktail dresses.

**Comment by axietheaxolotl** [comment]
The dresses were inherently designed to look formal, and impractical. It's supposed to be a dress for formal events, as it's, you know, formal clothing.

Also, I wanted to just

**Comment by Farquaar** [comment]
Also you should probably know we're in a feature freeze for the rest of the month

**Comment by tralezab** [comment]
#62946 -- Unfortunately, we are currently in a feature freeze. Feel free to PR this next month.

**Pull request closed without merging**
