### PR TITLE
Adds shaking soda cans, buffs throwing soda cans at people

### PR DESCRIPTION
**Pull request by Ryll-Ryll**
## About The Pull Request
This started out as a joke on discord about buffing the throw damage of soda cans (have you ever had one thrown at you? they hurt!!), that ended up also growing into a feature I've wanted to add for a while- shaking soda cans for pranks!

https://streamable.com/ra7ctd
_Note: This PR shows the user getting a positive moodie from a can going off on a wall, that was fixed after the video was recorded_

Right clicking on an unopened soda can will shake it and raise its fizziness level, as will throwing soda cans at things. When you go to open a soda can, an RNG check is made based on how fizzy the soda is from being mishandled, with a failed check making the soda spray all over you and give you a negative moodlet (and everyone who sees it happen a milder positive moodlet!)

The throwforce for an unopened can of soda has been set to 12, slightly higher than a standard floortile (10) and equal with toolboxes. As mentioned before, though, every time you throw a soda, its fizziness rises, meaning each throw is more likely to burst it and kill the damage value. This puts it in a perfect spot where it's not worth stocking up on sodas just in case you get into a fight (cause you could just use floortiles, which stack up to 50), but seeing a nearby unopened can of soda and throwing it at your enemy could be an interesting addition to environmental combat.

You can try to detect if a can of soda is fizzed up by examining it twice rapidly. Depending on how fizzed up the soda is, you may be able to detect said levels of fizz, allowing you to ask for another untouched soda.

## Why It's Good For The Game
Shake up a soda a whole bunch, give to someone in a crowded room of people, give everyone a positive moodie when the rube opens the can!

## Changelog

:cl: Ryll/Shaps
add: Added shaking soda cans! Take an unopened soda can and right click it in hand to shake it all around, increasing its fizziness. 
balance: Having an unopened soda can hucked at you will actually hurt quite a bit, around the level of a toolbox. This also has a chance of bursting the soda can on impact, leaving it useless as a weapon after.
/:cl:

### CODE REVIEW

**Comment by DrDiasyl** [comment]
> should make it so that if you notice it could burst from fizz, you have better rng on having it not fizz on you

Oh like when you see the soda is shaked, so you open it slowly

**Comment by TemporalOroboros** [comment]
Would it be possible for the soda to produce foam when it bursts?

**Review by tralezab — CHANGES_REQUESTED** [review]
i swear it's gonna hit me some time soon that the QDEL_IN is a bad idea

**Comment by AnCopper** [comment]
image

**Comment by Orchian** [comment]
Toolbox-level of damage sounds a tad strong no?

**Comment by Wallemations** [comment]
Finally my Agent 47 traitor gimmick can become real.

**Comment by TheBonded** [comment]
didn't tex request this during the toolbox tourney? I think they wanted a super rare chance of it just maxcapping when you shook it.

**Comment by maxymax13** [comment]
soul content 👍

**Pull request merged**
