### PR TITLE
Boots (and Coat) of Winter in the Vendor of Clothes

### PR DESCRIPTION
**Pull request by Galdar02**
What it says on the tin

## About The Pull Request
I stuck a few pairs of Winter Boots (and a few Winter coats) into the Clothesmates
(Baby Moff's first PR, funnily enough a PR concerning boots)
## Why It's Good For The Game

I feel that it was a major oversight that the Winter Boots (and Coat) hadn't been put into the Clothesmate, i have now come to fix past mistakes

## Changelog
:cl:
Add: Winter Boots and Coats can now be acquired from Clothesmates  
/:cl:

### CODE REVIEW

**Comment by carshalash** [comment]
image
Local moth is hungry.

**Comment by Memedoktor** [comment]
God you really can't stop with your fuckin foot fetish, its all about you and eating programmer socks. this power creep is unacceptable go back to citadel with your one line of code change.

**Comment by KathyRyals** [comment]
> 
> 
> God you really can't stop with your fuckin foot fetish, its all about you and eating programmer socks. this power creep is unacceptable go back to citadel with your one line of code change.
> *this entire comment was requested by local horny moth for their bullying dosage

Classic non - contributor comment

**Comment by Jack7D1** [comment]
h

**Comment by Memedoktor** [comment]
@KathyRyals silence you erp degen

**Comment by Jack7D1** [comment]
Speed merge speed merge speed merge

**Comment by Galdar02** [comment]
👌

**Comment by Galdar02** [comment]
_also just gonna say this doesn't really deserve the good first PR tag, it's literally one line of code my guys_

**Comment by ExcessiveUseOfCobblestone** [comment]
why just the boots and not the jacket too?

**Comment by Galdar02** [comment]
Fuk

**Comment by Galdar02** [comment]
> why just the boots and not the jacket too?

Honestly i just wanted to make sure i would even be able to do it without fucking something up, think of it as WYCI coming to life for a young cood Moff

**Comment by ExcessiveUseOfCobblestone** [comment]
ok what if you did it but in this PR ;)

**Comment by Galdar02** [comment]
I mean i _could_ but i plan on doing a bit more then just the coat

**Comment by ExcessiveUseOfCobblestone** [comment]
the boots and the jacket are a set bro just add it here...

**Comment by Galdar02** [comment]
Fuk,f i n e

**Comment by Doosteroni** [comment]
Meh, the winter coat sprite is fucking terrible

**Comment by Galdar02** [comment]
Personal preferences my dude, i for one like the Winter Coat, it ain't gonna be as nice as the department specific ones but it's still nice￼

**Comment by Galdar02** [comment]
_nice_

**Pull request merged**
