### PR TITLE
Atmos Holofan barrier is slightly transparent and has a catchy animation

### PR DESCRIPTION
**Pull request by GuillaumePrata**
## About The Pull Request
Small improvements to the atmos holofan icon, easier for players to understand you can move through the barrier and that it holds firelocks open. Slightly transparent and with "blinking" lights so players can see it's not a normal firelock easier.
atmosholofan

## Why It's Good For The Game
Maybe now people will stop hulk smashing firelocks open while its neighbor is being held open by a holofan...
Also it ends the tactical combat holofan.

## Changelog

:cl: Guillaume Prata
qol: The atmos holofan barrier has a new animation and is slightly transparent to easily convey that you can move through it.
/:cl:

### CODE REVIEW

**Comment by ArcaneMusic** [comment]
Double check for a stray white pixel at the top left corner? It's there on the discord preview.

**Comment by GuillaumePrata** [comment]
> Double check for a stray white pixel at the top left corner? It's there on the github preview.

Isn't that a function of the bot? I remember seeing it in another PRs but I don't know what means exactly.
I know it is not a stray pixel at least.

**Comment by EricZilla** [comment]
I have been trying to find this sprite for ages, was intending to do something about the same, cept maybe change fire to BREACH or ATMOS

**Comment by Livrah** [comment]
It ruins tactical holofan.

**Comment by GuillaumePrata** [comment]
> It ruins tactical holofan.

Oh ye, I was going to add this on the "Why it is good for the game"
Thanks!

**Comment by LemonInTheDark** [comment]
@tgstation/sprite-team thoughts?

**Pull request merged**
