### PR TITLE
Adds a new body outline graffiti for crayons and gives the detective a white crayon

### PR DESCRIPTION
**Pull request by TZK13**
crayon body outline example

Also adds a waistcoat to the detective's closet so detectives can look as cool as that with ease.

### CODE REVIEW

**Comment by Alek2ander** [comment]
Can clicking a prone body with a crayon automatically create an outline?

**Comment by TZK13** [comment]
No, it works just like any other graffiti in that you select it and then click on the tile. I don't think it really needs any special mechanics behind it either really.

**Comment by ike709** [comment]
The sooner we can go full-CSI the better, :+1:

**Comment by Alek2ander** [comment]
Police tape when?

**Comment by Tenebrosity** [comment]
Neat

**Comment by paprka** [comment]
Well this is perfect, I would like that 'clicking a prone body makes an outline' thing though

**Comment by ike709** [comment]
@paprka port your sec/engy tape from NT so we can go full CSI

**Comment by paprka** [comment]
I will some day, there was some bugs with it I need to work out and it's been updated on baystation a lot.

**Comment by Miauw62** [comment]
Urist McStation's tg build had tg-friendly police tape.
Op 4-jan.-2015 02:27 schreef "paprka" <notifications@github.com>:

**Comment by paprka** [comment]
I don't think they fixed some of the bugs that I encountered on NT.

**Pull request merged**
