### PR TITLE
Updates eye of god sprite again

### PR DESCRIPTION
**Pull request by ChangelingRain**
New;
t1ck t0ck
8r8k H34DS

Old;
honk
HONK

The old(new) double eye didn't even loop properly techno aaaaaaa and you didn't update the onmob sprites either this is a crime
The sclera is like a tiny bit darker around the iris now also aaaaa

### CODE REVIEW

**Comment by optimumtact** [comment]
it literally looks the same

**Comment by ChangelingRain** [comment]
It doesn't aaaaaaaa

**Comment by PKPenguin321** [comment]
Change the sprite to a bikeshed

**Comment by Razharas** [comment]
Does the naked eye has a tiny eye lid in the sclera?

**Comment by TechnoAlchemisto** [comment]
yucka

**Comment by TechnoAlchemisto** [comment]
pucka

**Comment by pudl** [comment]
Left is new, right is old.

You didnt add that you also changed the color of the sclera again. You should probably do it.

**Comment by TechnoAlchemisto** [comment]
I really don't know what those white pixels at the top of the iris are for

**Comment by ChangelingRain** [comment]
It's a reference duh

**Comment by pudl** [comment]
I dont like the darker sclera but the fix is cool

**Comment by optimumtact** [comment]
it looks identical

**Comment by KingDairy** [comment]
no more homestuck references

**Comment by PKPenguin321** [comment]
hey wait a minute this looks like terraria

**Comment by PKPenguin321** [comment]
here's my submission for a new sprite
aaaa

**Comment by TechnoAlchemisto** [comment]
10

**Review by optimumtact — CHANGES_REQUESTED** [review]
Sprite is not a bikeshed

**Comment by WJohn** [comment]
Gets rid of the ugly white spot that comes in and out, so that's good 👍

**Comment by optimumtact** [comment]
It looks worse

**Pull request closed without merging**
