### PR TITLE
Airlocks open when items hit them

### PR DESCRIPTION
**Pull request by JJRcop**
## About The Pull Request

Airlocks open when items hit them

## Why It's Good For The Game

Airlocks open when items hit them

## Changelog
:cl: JJRcop
tweak: Airlocks open when items hit them
/:cl:

Airlocks open when items hit them Airlocks open when items hit them

### CODE REVIEW

**Comment by Tlaltecuhtli** [comment]
does it work for emag too?

**Comment by XDTM** [comment]
Simple animals dragging an ID can now drag the card into the door to open it, which is nice

**Comment by HomocidlePancakes** [comment]
You can’t move stuff without hands, only drag

**Comment by WJohn** [comment]
That's... pretty cool.

**Comment by ExcessiveUseOfCobblestone** [comment]
tactical airlock opening while making a run for it so when you run past it closes???

**Comment by bgobandit** [comment]
can this be restricted to only heavy items, it's stupid to have an airlock open if you throw a cigarette butt at it

**Comment by imsxz** [comment]
no because then you wont be able to throw ID into doors

**Comment by ExcessiveUseOfCobblestone** [comment]
you can check to see if it's a card or it's a normal/bulky sized object.

**Comment by JJRcop** [comment]
Now doesn't respond to anything under WEIGHT_CLASS_NORMAL unless it has some form of access.

Travis failure is baffling.

[Screenshot_20190613_223956](https://travis-ci.org/tgstation/tgstation/jobs/545526109#L1010)

Airlocks open when items hit them

**Comment by JJRcop** [comment]
Rebase in attempt to resolve Travis.

Airlocks open when items hit them

**Comment by ExcessiveUseOfCobblestone** [comment]
just bug me if you need to retry travis, don't need to make empty changes.

**Review by SpaceManiac — APPROVED** [review]

**Pull request merged**
