### PR TITLE
Gloves protect against cheap lighters

### LINKED ISSUE #11419: Cheap lighter burns through atmos hardsuit
Wearing full atmos hardsuit gear (which is supposed to have pretty much immunity to heat) and fiddling with cheap lighters can cause burns.

Edit. Probably also applies to black gloves and other supposedly heat resistant handgear.

### PR DESCRIPTION
**Pull request by Cyberboss**
Fixes #11419

:cl: Cyberboss
fix: Appropriate gloves now protect you from getting burned by cheap cigarette lighters
/:cl:

### CODE REVIEW

**Comment by ShadowDeath6** [comment]
buffs sec again smh

**Comment by TehZombehz** [comment]
Obviously a major hindrance on anti-sec combat.

**Comment by PKPenguin321** [comment]
[balance/rebalance]

**Comment by Anonmare** [comment]
Reee he buff sec lynch he now

**Comment by optimumtact** [comment]
Whoever wrote this proc needs a lesson in inheritance and OO design

**Pull request merged**
