### PR TITLE
Belts now have inhand sprites

### PR DESCRIPTION
**Pull request by epochayur**
Adds inhand sprites for the following items: 
-utility belt
-CE's belt
-medical belt
-security belt
-janitor belt
-explorer's webbing, explorer's webbing alt., & military webbing
-hunter's belt
-soulstone belt
-bandolier
-holster

belts_big

:cl: Epoc
imageadd: Belt items now have inhand sprites
/:cl:

Addresses part of #30081, feedback welcome

So in belt.dm, there's a bunch of items (grenade belt, assault belt, etc.) that have item_state = "security", so they just default to the regular security belt. I didn't know if this was something I could change without breaking something else, so I decided not to fuck with it. But, if I can give them unique icon names then I'll go ahead and make sprites for those as well. I was also lazy and didn't make any for fanny packs because fuck recoloring the same sprite 11 times. If this is well received then I'll finish their sprites too.

### CODE REVIEW

**Comment by ShizCalev** [comment]
one day todo _maybe_: tool icons for inhand belts.

**Comment by ShizCalev** [comment]
updating, 1 sec.

**Comment by Spaceinaba** [comment]
ayyy

**Comment by WJohn** [comment]
These really don't look great, but I think it's more important to get at least *some* sprites in for these rather than postpone it indefinitely or risk not getting them at all. We can always redraw these at a later date, they're serviceable enough for now.

**Review by WJohn — APPROVED** [review]

**Comment by epochayur** [comment]
@WJohn should I bother spriting any more of these?

**Comment by ShizCalev** [comment]
@epochayur Yes please.

**Pull request merged**
