### PR TITLE
Polishes some side sources of light and color

### PR DESCRIPTION
**Pull request by LemonInTheDark**
## About The Pull Request

[Circuit Floor Polish](https://github.com/tgstation/tgstation/commit/6b0ee9813271f693ceb44ad42277c36ef2e71268)

Circuit floors glow! but it looks like crap cause it's dim and the colors are washed out.
I'd like to make them look nicer. Let's make them more intense and longer range, and change the colors over to more vivid replacements.

While I'm here, these should really use power and turn on and off based off that. 
Simple enough to do, just need to hook into a signal (and add a setter for turf area, which cleans up other code too).

[Desklamp Upgrade](https://github.com/tgstation/tgstation/commit/8506b13b9c97bf740c3e97db04450555387dd126)

Desklamps look bad. They're fullwhite, have a way too large range.Crummy.
Let's lower their lightrange from 5 to 3.5, and make the ornate ones warmer, and the more utilitarian ones cooler. The clown one can be yellow because it's funny

I'm renaming a color define here so I'm touching more files then you'd expect

[Brightens Niknacks](https://github.com/tgstation/tgstation/pull/73936/commits/835bae28e9eb9946be53c9f5dac0a0a39f15ef21)

Increases the light range of request consoles, status displays, newscasters, and air alarms (keycard machines too, when they're awaiting input at least)
Increases the brightness of air alarms, I think they should be on par with apcs, should be able to tell when they're good/bad.
Increases the brightness of vending machines (I want them to light up the tiles around them very lightly, I think it's a vibe)

Fixes a bug with ai status displays where they'd display an emissive even if they didn't have anything on their screen, looking stupid. 
This was decently easy but required a define. Looked really bad tho

## Why It's Good For The Game

Pretty

<details>
<summary>
Circuit Floors
</summary>

Old
image
image

New
image
image
</details>

<details>
<summary>
Desk Lights
</summary>

Old
image
image

New
image
image

</details>

The niknack changes are more minor so I'm not gonna grab photos for them. I can if you'd like but I don't think it's necessary. Mostly a vibes in dark spaces sorta thing
 
## Changelog

:cl:
add: I made circuit floors brighter and more vivid.
add: Made air alarms, vending machines, newscasters, request consoles, status displays and keycard machines slightly "brighter" (larger light range, tho I did make air alarms a bit brighter too)
add: Tweaked desklamps. Lower range, and each type gets its own coloring instead of just fullwhite.
fix: AI displays are no longer always emissive, they'll stop doing it if they aren't displaying anything. Hopefully this'll look nicer
/:cl:

### CODE REVIEW

**Comment by Kapu1178** [comment]
good pr

**Comment by ZephyrTFA** [comment]
Failure is MDB2, and can be ignored

**Review by ZephyrTFA — APPROVED** [review]

**Comment by LemonInTheDark** [comment]
https://github.com/tgstation/tgstation/issues/73937
broke area contents, something is wrong.

**Comment by LemonInTheDark** [comment]
I was using the change_area proc inside of maploading, which because of an optimization to maploading lead to double inserting a turf into area contents. I do still need to hook into a proc on mapload tho, so I added a second subproc that's called when area is changed. I know it sucks but I'm not sure how else to handle it

**Comment by san7890** [comment]
did you completely kill the "off" circuit floor variant? would be appreciated if you made an updatepaths (https://github.com/tgstation/tgstation/tree/master/tools/UpdatePaths) with something like

```txt
/turf/open/circuit_floor/off : /turf/open/circuit_floor
```

probably don't need {@OLD} here because turf varedits are the devil. this is just to be polite to downstreams and people currently making maps that aren't in the repo right now

**Comment by LemonInTheDark** [comment]
I didn't, because some variations want to be like.. broken. the off tile in the elephant graveyard for example.

**Comment by san7890** [comment]
ah okay just making sure because my github was shitting out and wasn't sure of the extent

**Comment by newfren** [comment]
does the extra light range from the knickknacks fuck over nightmares

**Comment by LemonInTheDark** [comment]
it shouldn't, if they stand near it maybe but that was always a thing these lights could do

**Comment by Jezzared** [comment]
Lemon singlehandedly making being in the dark feel so much cooler than being in fullbright.

**Pull request merged**
