### PR TITLE
gives credit to people who more than deserve it

### PR DESCRIPTION
**Pull request by ghost**
@Substance455

ok really my bad here

there might be one more file I need to edit, but it looks like that one only works off of who made the pr and nothing else but i could be wrong

### CODE REVIEW

**Review by Cyberboss — CHANGES_REQUESTED** [review]
You need to edit .all_changelog.yml

**Comment by Armhulen** [comment]
really? what would i add there

**Review by Cyberboss — APPROVED** [review]

**Comment by Jordie0608** [comment]
It's a bit late but don't edit `changelog.html`; it's built from `all_changelog.yml`

**Comment by Chezzo** [comment]
Laganas didn't make that sprite, Waldo did.

**Pull request merged**
