### PR TITLE
Splits pizzaspaghetti.dmi into pizza.dmi and spaghetti.dmi

### PR DESCRIPTION
**Pull request by dragomagol**
## About The Pull Request
See title

## Why It's Good For The Game
Pizza and spaghetti don't need to be in the same dmi
Killing soul instantly

## Changelog

No player-facing changes

### CODE REVIEW

**Comment by Time-Green** [comment]
rip pizzaspaghetti.dmi 😔

**Review by Imaginos16 — APPROVED** [review]
I hate old contributors

**Comment by AdipemDragon** [comment]
I kinda wish the moth pizza was in the pizza dmi too just so Everything's There but i'm just gonna be happy that this is split.

**Comment by Wallemations** [comment]
Smh can't believe they didn't name that .dmi `italian.dmi` originally

**Pull request merged**
