### PR TITLE
Slightly raises the Crab-17 machine's drain rate and health

### PR DESCRIPTION
**Pull request by ghost**
:cl: Floyd / Qustinnus
balance: Crab-17 machine has higher health and higher drain rate now.
/:cl:

the crab-17 machine isn't meant to be destroyed by 500 idiots bashing it; it self-destroys when people are done checking out. The health was added by @MrDoomBringer as a fail-safe for if you /really/ wanted it gone. If the health change isn't acceptable I can just change it back to not having health, as this was the original idea anyway.

People complained about the drain rate being too low too so I kicked that up a bit as well.

### CODE REVIEW

**Comment by habader** [comment]
what how is it supposed to be destroyed

**Comment by ATH1909** [comment]
Just make it indestructible without cashing out, tbh.

**Comment by wesoda25** [comment]
tee hee hee lets make the already annoying thing that people use every round even better tee hee hee!!!

**Comment by Qustinnus** [comment]
tee hee let's post in bad faith on every PR and act surprised when people dont ever value my opinion

**Comment by nemvar** [comment]
If you are going to change something, make it impossible to withdraw your money as soon as the annoucement hits. You currently get a grace period where you can just get it out of your ID card.

**Comment by Qustinnus** [comment]
@barhander you're one of those people together with subject and wesoda

**Comment by wesoda25** [comment]
Very well qustinnus I’ll post my thoughts in as good faith as I can. The way I see it, the crab phone is like a red object in an entirely green room. Its blatant, it’s annoying, it hurts to look at (in this case listen to, sprites aren’t bad i wont lie), and it clashes with its environment horribly. 

There are 1001 ways to create a diversion as a traitor, and to me crab phone is just a very unimaginative, easy way out for traitors. I think its add odds with most of our code, and I really do dislike that traitors now have a button they can press to anonymously piss everyone off and get them in one area. 

The idea was funny on paper, I don’t think I saw the PR but if i did id probably have upvoted. But in game, its frankly a bad PR, and it gets worse the more times its used. I’d love if you’d put a diversionary economy themed PR up that was a bit more subtle, something that _didn’t_ force literally every player on the server to step to its drum. I don’t _want_ to post seemingly “good faith” feedback as to how you could improve the PR, because frankly I think we’d be better off without it.

**Comment by Shadowflame909** [comment]
What if we just Re-add the Stock Market

and the Crab-17 Item replaces every stock with "shitcoin" and you see all the numbers rapidly going down.

Buy high Sell Low

**Comment by HomocidlePancakes** [comment]
Imagine making large posts over something that doesn’t affect you in any way besides being an eyesore

**Comment by wesoda25** [comment]
> Imagine making large posts over something that doesn’t affect you in any way besides being an eyesore

Do you play the game??? If so you’ll know that it effects literally everyone in a round, which is the primary reason I don’t like it.

**Comment by Qustinnus** [comment]
we have the powersink etc as similar distractions, this item is one of the few that actually manages to do what its supposed to for 7 tc, the original PR was flooded with people who complained it wasn't worth 7 tc. The only thing I'd agree with is if people asked me to blacklist it from ops. Noone has actually asked me to do it but if they do I probably would.

**Comment by YakumoChen** [comment]
You should blacklist it from ops, it just gives ops a big target to EZ Bomb with their big red button and whatever disguise they need, and usually the captain is one of the many people that will rush to it, along with the flood of crew following them through whatever restricted access is needed to get to it. Nobody will pay attention to any sign of ops because they'll all be too busy rushing the machine to bash it down.

**Pull request merged**
