### PR TITLE
Changelings now shout "REEEE" when they screech

### PR DESCRIPTION
**Pull request by ghost**
:cl: Xhuis
soundadd: Changelings' resonant shriek now has a sound effect.
/:cl:

### CODE REVIEW

**Comment by PKPenguin321** [comment]
oh hell yeah

**Comment by Cebasiz** [comment]
meme PR first

**Comment by Xhuis** [comment]
Feels bad, man.

**Comment by Anonmare** [comment]
Kor "Put every ling in the execution wing" Phareon strikes again

**Comment by Xhuis** [comment]
Notorious hacker KorChan

**Comment by PKPenguin321** [comment]
ps xhuis give shadowling

**Comment by Xhuis** [comment]
People didn't like it and wanted it gone. One of these days I'll rework it though

**Pull request closed without merging**
