### PR TITLE
Click dragging mobs into disposals

### PR DESCRIPTION
**Pull request by imtakingabreakdontatme**
Why was this ever removed in the first place it makes feeding slimes a huge pain.

Added a check to make sure the person dragging isn't in a closet, and sets the LAssailant of the person being disposaled so slime friendship will still work

### CODE REVIEW

**Comment by GunHog** [comment]
Because pAI and other mobs that cannot logically dunk things can do so via this method. Check to ensure that only valid mobs can.

**Comment by KorPhaeron** [comment]
@GunHog 

stuff_mob checks for the user being carbon

**Comment by GunHog** [comment]
Well, if the check exists, then it should be fine. I still highly recommend a test of several mob types to be sure.

**Comment by phil235** [comment]
I think it was also removed because you could stuff prople in the bin while being in the bin yourself (or in a closet next to the bin).

**Comment by freerealestate** [comment]
Yeah, you removed it here for that reason: https://github.com/tgstation/-tg-station/pull/8205

>Stuffing another mob in a disposal unit is now only done via grabbing.(fixes bugs like stuffing someone while being inside the disposal yourself)

**Comment by Supermichael777** [comment]
but that actualy makes sense(reach out and grab them)

**Comment by freerealestate** [comment]
Yeah, it does. Surprise dunking. The closet thing, not if it's closed. Maybe that could be fixed by something else instead?

**Comment by KorPhaeron** [comment]
I can check to make sure the mobs loc is a turf

**Comment by freerealestate** [comment]
But surprise dunking

**Comment by phil235** [comment]
There's also the issue of slime friendship in xenobiology, for them to become your friend you need to have grabbed (or set the LAssailant var somewhere) the monkey you fed to them.

**Comment by KorPhaeron** [comment]
@phil235 

I'd rather have to remember to punch one monkey at the start to make every subsequent slime my friend than to deal with juggling intents and grabbing+clicking disposals and stuff.

**Comment by freerealestate** [comment]
It's not exactly intuitive for the players who won't know about it though. It'd be better to change it so that clicking and dragging a monkey into a disposal has the same effect.

**Comment by KorPhaeron** [comment]
@phil235 

Should be fine now

**Pull request merged**
