### PR TITLE
Reverts recent R&D tech changes

### PR DESCRIPTION
**Pull request by Core0verload**
This PR reverts most of tech level changes from #17576. Changes in machines are unaffected and reliability stays gone. Some minor stuff like getting biotech from genetics is unaffected too.

Well, I think we all saw the feedback on new RnD. @LatD's PR took it from "routinely sitting in dept for 10 minutes" to "routinely rushing from dept to dept, attempting to force everyone to work and begging spessmens to give you high tech items for 40 minutes, then crying because the shuttle is already called". At this point, RnD is simply not worth doing it.

I'm not sure how to improve RnD, but I'm sure @LatD's changes are _not_ improving it.

As a bonus point, changes that I'm reverting have murdered lowpop RnD and golems RnD.

### CODE REVIEW

**Comment by Core0verload** [comment]
This PR also removes design selling from cargo. With reliability removed, it allows for gaining insane amount of money, 2500 credits for every single design, including starting ones.

**Comment by coiax** [comment]
Science being able to get all of their top tier toys within 10 minutes is silly, and I trust @LatD's eye. So definitely :-1:

**Comment by Core0verload** [comment]
Except now it's "science being unable to get their top tier toys at all". I haven't saw a single T4 part for a while. RnD takes longer than a round lasts.

**Comment by PKPenguin321** [comment]
Maybe that's how it should be

Or maybe we should let latd run with his tweaks a while longer so he can get all the issues sorted out before reverting all his work because we can't stand not having infinite guns and mechs ten minutes in

**Comment by Core0verload** [comment]
I don't think LatD is moving in the right direction with his changes. They are centered around making RnD more annoying to do, and basing your game mechanics on annoyance is bad period.

**Comment by Jalleo** [comment]
The whole concept of R&D is wrong atm.

**Comment by Bawhoppen** [comment]
@Jalleo, yes R&D shouldn't just be stick things in and decon, it should be different hands on sections who all contribute their research components to the deconner and then they make their toys

**Comment by xxalpha** [comment]
R&D is bad, but if Latd is working on it currently then don't revert his work.

And stop cattering to 10 minute round players cancer.

**Comment by Core0verload** [comment]
I'm more concerned about lowpop when you just don't have enough crew to man all the depts.

**Comment by LatD** [comment]
About half the feedback I've got has been positive and most of the negative ones have been related to "I have to leave the R&D room now".

Yesterday there was a single golem in lavaland who managed to get R&D up and do R&D to get hyper kinetics and T4 parts alone. So it seems to work well enough alone too.

**Comment by Core0verload** [comment]
If a half of your feedback is torches and pitchforks, you are doing it wrong.

**Comment by xxalpha** [comment]
>If a half of your feedback is torches and pitchforks, you are doing it wrong.

That doesn't mean shit, to be honest.

**Comment by MrStonedOne** [comment]
fucking convenance creep is bad, lat's changes is good.

"I have to put, like, effort and time into the game"

Good.

**Comment by Aloraydrel** [comment]
I have faith lati will make science great again

**Comment by ChangelingRain** [comment]
>If a half of your feedback is torches and pitchforks, you are doing it wrong.

No, that just means it's controversial. Example: Global Warming.

**Comment by Durkel** [comment]
How many of you people actually do RnD? The ten minute rush was tedious, and now this is even worse. This is one the worst mistakes you can make while doing game design and that's to take something flawed and yet potentially overpowered and just make it more tedious to do so less people do it. What actual positive change does this bring to to your round? Are you having more fun nagging botany,genetics,cargo for something?

Old science wasn't fun, this science isn't fun either, and now we've tacked on requirements for jobs that already have responsibilities or were very low demand.

**Comment by LatD** [comment]
One thing that always keeps surprising me is how many people actually want every job to be like virology where you sit in a room isolated for most/all of the round. 

I agree that as a concept the current R&D isn't great and should eventually be remade but I haven't seen any great ideas to replace it in the forums or other places which is why I changed the levels to keep some of the old work-side but add a possibility to get some good valuable items that are not something you just get every single round.

One thing that really keeps confusing me with the complaints is that most people think you HAVE to work with other departments. You unlock like 90% of the items without ever leaving the room once all the levels are 5. People didn't have any problems when they didn't get x-ray guns, phazons or x-ray implants every round. Things haven't changed much but suddenly it's a huge problem even though the rework mainly ALLOWS the addition of new such items behind the higher tech levels. There are actually very few items actually behind those high tech levels even though there are now items that give those levels.

I'd also take the complaints and feedback much more seriously if I personally felt that R&D is now balanced and ready. But it's not. And that's why I have 2 PRs up to fix and balance it. And those won't be the last ones.

**Comment by Jazaen** [comment]
How long is this thing in? I suggest we have an in-game poll after two weeks or so, since it does affect more than just sci.

**Comment by Bawhoppen** [comment]
@latd my idea was pretty swell

**Comment by Lumipharon** [comment]
Current implementation isn't great because there's still issues with shit like botany people too strong at R&D, odd origin tech for some items etc. That shit can be fixed easily.

However I honestly don't see any issues with the overall change, considering THE ENTIRE PURPOSE was to change R&D from 'sitting in R&D for 10 minutes" to "having to interact with other players'.

Saying 'R&D is harder at low pop' is not a valid argument. The game is balanced around a functional sized crew - if you have less people, then yes, if you want all the toys you're going to have to do more shit, wew.

The main useful change that needs to happen is to have some better two way rewards for other departments helping science (ie: botany giving R&D a walking mushroom butt lets R&D unlock and give them a serum to make salad armour out of cabbage etc etc).

**Comment by Kromgar** [comment]
Now that Lumi is something I can agree with. Make it so the Departments REALLY want to work together. They get major rewards other than upgraded planters.

**Comment by Lumipharon** [comment]
Which is why I'm strongly opposing people saying revert.
This is an unironic case of improve don't remove - it's pretty unreasonable for such a large change to have all this shit from the get go.

**Comment by LatD** [comment]
Rewards like that are easy to add with this system, they were impossible to add with the old system (unless adding even weirder and more inconsistent levels like engineering 8, power 9, programming 7, since the old max levels were very unclear and constantly raised even more). The main point of the remake was to make the levels consistent and comparable and to then make the lategame items behind the gates, currently the gates are pretty empty when you look at the items which come available there. 

Adding more reward items would be great but I just can't do it all in one R&D remake PR and suddenly moving stuff like floral somatoray to combat 6 or something just doesn't make sense much. If someone wants to add a buffed version of it and put it behind some level gate that can be get with botany it would be really good.

**Comment by Lumipharon** [comment]
ranged RCD for engineering (like mech version, but without the r-wall deconning).
Faster shuttle or more available items for cargo (fluff however you care).
limb growing tank/augmented organs for medbay.
Higher tier power(s)/symptoms for genetics and viro respectively
Experimental slime potion that does somefancything for xeno
Some hilarious plant mutations/salad armour for botany
Etc etc. 
Just need someone to code and sprite some stuff, or move certain preexisting items into this category.

**Comment by optimumtact** [comment]
You've now put two separate controversial things into one PR and this will seriously harm your ability to get this merged, which is already quite low as this is a touchy topic and the PR you're reverting was design lead approved.

I'd recommend you split them into two revert PR's

**Comment by Core0verload** [comment]
@optimumtact, em, what? This PR exist solely as revert of @LatD's changes to tech levels.

**Comment by optimumtact** [comment]
Apologies I was basing this of your second comment, assume it's no longer true?

**Comment by Core0verload** [comment]
Assume it has no relevance. Designs selling feature existed solely for selling designs with maxed out reliability. Since reliability is no longer a thing, it was broken.

**Comment by LatD** [comment]
Selling designs should be removed anyway, that's probably not controversial in any way. You can still sell tech level disks right? I hope that's balanced.

**Comment by AdamElTablawy** [comment]
I personally do not like the R&D changes, mostly because they're nonsensical.

I mean, I am all for interdepartmental cooperation. Even if it means R&D is not often done, R&D can still get MOST of their important shit available without leaving R&D and in a fast period of time, and having to cooperate with other departments for more things to get from R&D is good, and I like that.

What I do not like is what you made them require.

Ghost chilis giving EMP. EMP???

Superpowers, for ENGINEERING research?

There is consistency issues here, in that everything required for a scientist to max R&D makes no sense because the final products are legitimately unrelated to the entire tech you are dealing with.

You also made it a bit TOO difficult for R&D to be maxed in the short, often bombed timeframes that we have. It's almost impossible now, and while 'good R&D is 2 strong' may be a common response, nerfing a job until it is almost impossible to do is a good way to kill a job, or an entire department. You've made the final tech level things too hard to get in the end. You've made a lot of it depend more on RNG now too-superpowers, ghost chilis, ect.

Also it makes golem R&D really really hard to finish in the end stop pooping on the poor golems.

It just feels like a badly implemented, temporary solution to a problem that can't be fixed without reworking R&D entirely, and one with no consistency and more unpleasant RNG towards the end.

**Comment by LatD** [comment]
I've mentioned like 5 times that we can't have xenobio, botany and genetics all giving biotech and no one giving engineering, EMP or powerstorage. Genetics is bioengineering for now. Add some progression-related item to engineering department and I'll gladly replace genetics powers with that. Ghost chili was also just a placeholder because without it people would again complain that there are no ways of getting that level. I'll most likely remove the ghost chili in my next small level tweak. I probably have to remove all biotech from xenobio in that which things a lot but maybe that will stop people complaining about genetics.

**Comment by Core0verload** [comment]
@LatD 
You can make xenobio give powerstorage-related items, such as slime power cell. You can make SMES board, engineering item, give high powerstorage. There is a billion of options and each is better than your hacky "fixes". And now you say: "let's remove biotech from xenobio, the dept that literally has 'bio' etched on it". 

It would be funny, but it isn't, because your shit changes somehow end up merged.

**Comment by LatD** [comment]
SMES having a high origin tech is a terrible idea since there are like 5 useless SMESes on the station which can be deconstructed.
But I just got even better idea to add to my next tweak so xenobio can keep its biotech. 

..I don't even know why this PR is still open.

**Comment by Core0verload** [comment]
Are you seriously complaining that SMES is too common to give high power storage?

**Comment by Bawhoppen** [comment]
@LatD honestly its not much of a rework if you don't fix core problems like that

**Comment by Lumipharon** [comment]
@Core0verload Yes. Considering the point of those tech levels is to rely on other departments doing things, not just decon a smes/print a board.

@LatD I would suggest you make the code changes to fix most of these issues, and then just ask spriters for suitable sprites.

**Comment by Cheridan** [comment]
improve dont remove :^0

**Comment by Core0verload** [comment]
Switching to Plan B.

**Pull request closed without merging**
