### PR TITLE
Golfposting

### PR DESCRIPTION
**Pull request by LetterN**
Adds :golf: and :golfer: (tfw github does not have that)

why: 

meme

edit: will this get testmerged or closed

### CODE REVIEW

**Comment by deranging** [comment]
yes

**Comment by Tlaltecuhtli** [comment]
priority high

**Comment by Bawhoppen** [comment]
I was originally skeptical about a github whitelist...

**Comment by ExcessiveUseOfCobblestone** [comment]
Downvote until infinity

**Comment by Qbopper** [comment]
How do I upvote on mobile

**Comment by AlexTheSysop42** [comment]
@Qbopper desktop mode

**Comment by Iamgoofball** [comment]
🏌️ ⛳️

**Comment by optimumtact** [comment]
under what license are these sprites?

**Comment by LetterN** [comment]
_angery lawyer sounds_
will reopen soon(TM)

**Pull request closed without merging**
