### PR TITLE
Icebox Station

### PR DESCRIPTION
**Pull request by Whoneedspacee**
## About The Pull Request

Video: https://www.youtube.com/watch?v=kX-mH4k8b6k&t=

Thanks to @wesoda25 and @KomradeSpectre and @trollbreeder for making ruins for ice moon

Adds some cool cthulhu sprites by @jegub for a possible future megafauna.

Adds icebox, it's boxstation on top of the ice moon mine, lavaland and space ruins don't spawn on this map. There are 3 z levels, the top level with the station and some ruins and mobs, the middle level with some ruins, and the bottom level with megafauna and more dangerous ruins. No need for a gravity generator. Bombcap multiplier does not work on the station level because bluespace blah blah blah.

Icemoon has it's own unique atmos quite like lavaland, you need a winter coat, explorer suit, equal or better to withstand the cold temperature. It has a couple unique mobs and spawners for them with polar bears and wolfs, wolfs run away at low health and polar bears attack faster. There are also now snow legions for ice moon.

Refactors some parts of the weather system, adds ZTRAIT booleans for specific weather rather than targeting areas like the mining ZTRAIT, allowing for more fine control. You can now also make weather target outdoor areas automatically, making weather much easier to setup for a zlevel so you don't have to specify every area it targets.

Refactors many parts of the tunnel generation system for lavaland, you can now have areas specify whether tunnels, flora, mobs, or megafauna can be allowed in them. This makes it much easier to map in ruins and make sure generation won't mess with them. Also fixes a bug where tunnels were checking areas around the object creating the tunnel and not the front of the tunnel, which let tunnels move through areas it shouldn't have. You can also have a variable tunnel width if you desire now.

Rocks can now be mined for volcanic ash which can allow for glass creation on places that don't have basalt or sand turf.

Refactors a part of ruin spawning which allows for ruins to be placed in multiple areas. This makes multi-z ruin spawning much more possible since before you needed the top and bottom z levels to have the same area.

The wabbajack proc has an argument to specify the type of transformation now, (transform into a human, not a xenomorph, etc)

Fixes a bug where asteroid mobs never showed their aggro icon state.

Syndicate shuttle can now land on mineral turfs.

Adds minetype "none" so some stations can have their own custom minetype on the map json itself and not have errors logged.

Adds new blood drunk miner type that can be spawned from destroyed nether portals.

Adds anywhere ruins which are ruins that can be placed anywhere without messing with atmosphere and other things (generally ruins with turf passover everywhere, maybe some ruins could be converted to this if not already).

Nuclear Operative lockers now spawn with a diamond drill so they can drill through mineral turfs, especially needed for if they fall off the top z level.

Blobs can no longer place their starting core on a no blob allowed area, they already couldn't swap their core to such a position so it makes sense that they shouldn't be able to place themselves on it by default.

## Why It's Good For The Game

It's pretty much a normal station except with a few turns that I think might make the game more interesting. There's planetary atmosphere so there's the potential for gas mining that is less feasible on the station. Power is going to be more of a concern since the supermatter can't automagically super cool everything with space, though using freezers for cooling is still an option if you want a normal SM setup, solars and the TEG might be more viable options.

The potential for multi-z exploration is interesting though I'm sure there will be some issues there because... it's multi-z. Chucking people down z-levels instead of into space will also be hilarious (and possibly more dangerous).

Overall I'm not really sure how it will go, but hey it's a votable map so if people don't like it the statistics will speak for themselves, at the very least something interesting for a bit or for admin events.

## Changelog
:cl:
add: Icebox Station has been added, explore the depths of the Ice Moon with boxstation right on top of it, don't forget your coat and internals!
add: You can now mine rock flora into volcanic ash to make glass.
/:cl:

### CODE REVIEW

**Comment by Whoneedspacee** [comment]
lol wrong branch haha

**Comment by Whoneedspacee** [comment]
jokes github rebasing the fork messed up everything so it forced me to use the wrong branch so now im using my old fork again lol

**Comment by Qustinnus** [comment]
wouldnt it be better for maintainers to just manually getting the old commit or waiting for github to fix their shit rather than re-PRing things

**Comment by Whoneedspacee** [comment]
whatever kid

**Comment by tralezab** [comment]
HE IS SHITPOSTING

**Comment by tralezab** [comment]
MODS

**Comment by tralezab** [comment]
in all seriousness this is the whole hog right here one button from being back and fixed so just this is easier

**Comment by tralezab** [comment]
image
image
image

**Comment by Whoneedspacee** [comment]
image
image
image

**Comment by tralezab** [comment]
You cheated not only the game, but yourself. You didn't grow. You didn't improve. You took a shortcut and gained nothing. You experienced a hollow victory. Nothing was risked and nothing was gained. It's sad that you don't know the difference.

**Comment by tralezab** [comment]
image

**Comment by Twaticus** [comment]
icebox moment

chrome_hpfKtMuF6k

**Comment by MMMiracles** [comment]
put me in the screencap

**Comment by Qustinnus** [comment]
@tralezab it was also easier to make a new fork instead of waiting on github to fix the old ones, but that has now also backfired. So I'd rather wait on github support to do their thing or have it be fixed by maintainers

**Comment by ExcessiveUseOfCobblestone** [comment]
no merges, only sorrows.

**Comment by HomocidlePancakes** [comment]
Pancakes wuz here.

**Comment by nemvar** [comment]
Disgusting light mode users above.

**Comment by TemporalOroboros** [comment]
There's a dark mode?

**Comment by wesoda25** [comment]
ok so i have a branch on my tgstation-1 fork, how do i get those changes to the current fork?

**Comment by optimumtact** [comment]
Please consider this a friendly warning, your PR's must have a properly descriptive title and body content that explains the purpose of the PR.

Your current title and or body content does not meet requirements, so please update it.

**Comment by tmtmtl30** [comment]
are we sure that this one needs review

**Comment by Tharcoonvagh** [comment]
Why box tho

**Comment by Tlaltecuhtli** [comment]
> Why box tho

because people prefer staying outside boxstation

**Comment by ATH1909** [comment]
icebox?

more like

beatbox

@Shadowflame909 psst, it's your cue

**Comment by Shadowflame909** [comment]
what?

Good PR

Hoping bubblegum gets replaced with a Yeti themed variant/10

**Comment by Nebulacrity** [comment]
Sounds better than Box.

**Comment by Neo1w** [comment]
> icebox?
> 
> more like
> 
> beatbox
> 
> @Shadowflame909 psst, it's your cue

nah, beatbox is just a box station with our changes
https://github.com/Nopm/Beat-Station/blob/master/_maps/map_files/Beat!Box/Beat!Box.dmm

**Pull request merged**
