### PR TITLE
The Gobbetting barmaid 2: No Enter Edition

### PR DESCRIPTION
**Pull request by FloranOtten**
## About The Pull Request
Replaces the wooden doors with wooden airlocks with special opening sounds.

## Why It's Good For The Game
Wooden airlocks are CRIMINALLY underused. They also look nicer than the mineral doors.

## Changelog
:cl:
tweak: Changes the wooden doors on the Meta Maint Bar with wooden airlocks. Sounds are the same.
/:cl:

### CODE REVIEW

**Comment by FloranOtten** [comment]
Woops, appear to have misplaced an airlock

**Review by SpaceManiac — CHANGES_REQUESTED** [review]
Looks like you misplaced a nearby rwall. 
See details under https://github.com/tgstation/tgstation/pull/43469/checks?check_run_id=91392086

**Comment by RaveRadbury** [comment]
What clearance do the new airlocks have? Most of the HFS in maint is behind maint access, but the Gobbetting Barmaid is a decidedly more social space.  It would be nice if the new airlocks didn't have to be bolted open for everyone else, give everyone a chance to admire them opening and closing.

**Comment by Grazyn** [comment]
It's a social place for maint dwellers, not the general population

**Comment by FloranOtten** [comment]
The airlocks have no access requirement.

**Comment by FloranOtten** [comment]
Fixed the extra viro wall

**Review by SpaceManiac — APPROVED** [review]

**Pull request merged**
