### PR TITLE
Renames the AI language.

### PR DESCRIPTION
**Pull request by Iamgoofball**

### CODE REVIEW

**Comment by YakumoChen** [comment]
but the current name is fine?

**Comment by Chronitonity** [comment]
@YakumoChen https://en.wikipedia.org/wiki/DECtalk

**Comment by YakumoChen** [comment]
text to speech is still in a human-understandable language though, that doesn't make sense to be a secret AI language

**Comment by YakumoChen** [comment]
also >no reasoning for change

**Comment by octareenroon91** [comment]
Changing EAL to a historical tech reference would be cool.

Not on a whim though.

**Comment by lzimann** [comment]
It doesn't even make any sense to rename.

**Comment by Iamgoofball** [comment]
It's the TTS from moonbase alpha you uncultured heathens

**Comment by Iamgoofball** [comment]
It's as spaceman as it gets

**Pull request closed without merging**
