### PR TITLE
Fix helm console

### PR DESCRIPTION
**Pull request by Jackriip**
Restructures the helm console and makes the map large enough to see

### CODE REVIEW

**Comment by Jackriip** [comment]
DON'T LOOK THIS WASN'T SUPPOSED TO BE HERE LMAO

**Comment by JohnFulpWillard** [comment]
RIP

**Comment by LemonInTheDark** [comment]
rip to a fake one

**Comment by nikothedude** [comment]
155714 upvotes why was it closed!!!

**Pull request closed without merging**
