### PR TITLE
Stop summoning in space you assholes

### LINKED ISSUE #23583: Bloodcult space base successfully summoned Nar'sie
@ChangelingRain

image

### PR DESCRIPTION
**Pull request by ChangelingRain**
C E A S E
FIXES #23583

### CODE REVIEW

**Comment by Kromgar** [comment]
But muh flashbangs... 


Most cultists are too stupid to coordinate using blood boil runes or emp. also fukkin flashbangs


Your just mad narsie is cooler than ratvar

**Comment by KorPhaeron** [comment]
What about using blueprints to make a space base though

**Comment by ChangelingRain** [comment]
that is what this fixes

**Comment by OtherDalfite** [comment]
Maybe not deep space(off station z-level), but i think building a space base should be allowed

**Comment by jughu** [comment]
@korphaeron shouldnt need blueprints when.you can make new areas

**Pull request merged**
