### PR TITLE
Revert "Write clear rules on descriptive and obvious names in the contribution guidelines"

### PR DESCRIPTION
**Pull request by MrsTonedOne**
Reverts tgstation/tgstation#56872

fite me

### CODE REVIEW

**Comment by Mothblocks** [comment]
this one still rings in my mind every so often

image

**Comment by LemonInTheDark** [comment]
```
For your entertainment, here's some of the alphabet of SS13, the variable names of real code:

A - Atom, area, admins, augury, advanced disease, arrivals shuttle, asset, award
B - Blob, button, blue, area again (for some reason), blindfold, bomb
C - Carbon, client, simple_animal in create_random_spawn for some reason, count, corner, circuit, cinematic
D - Datum, design, bank account (yes, really), duct, drone
E - Radial entry, explosive, eye, ethereal, edible, emitter
F - Flat, frame, flasher, fire alarm, fire ball, filter, foam
G - Green, ghost, guardian, gloves, goal, high five (again, for seemingly no reason), gang
H - Human, holder, hunter, item (as both h and H in drag_drop.dm), holopad
I - Item, icon, interview, organ, implant, ID, image, immobilized
J - Icon again, job, jaunt, jetpack, cult spell (for seemingly no reason)
K - Keycard, knockdown, kinetic blast, knife
L - List, living, lighting, laws, limb, lungs, loot, turf
M - Mob, month, matrix, mode, machine, message, mobile
N - Nuke, new player, new, area for some reason in weather.dm, nozzle, node
O - Object, observer, objective, robot (for some reason), closet, outfit, body parts
P - Client, paper, node, pack, plumbing, point, player details, projectile
Q - Turf, carbon, query, quirk, reagents
R - Regex, ref, robot, mech, radio, role
S - Silicon, swarmer, shuttle, shelter, start, symptom
T - Turf, techweb, quirk, tackle, temperature, cyborg gun
U - Under, uplink, user, turf, upgrade
V - Vote, vomit, rods, mask, vampire
W - Weakref, weather, item, wound, particle, wall
X - Xenobio, extract, golem, paper
Y - We don't seem to have used Y as a variable name for anything other than y coordinates. Hooray!
Z - Plasma tank, drone, victim
```

**Comment by Mothblocks** [comment]
i expect royalties

**Comment by Mothblocks** [comment]
anyway i'm closing this because the PR you are reverting was not :-1:'d or spoken up against by any maintainers (and was even merged by a head coder) and it seems from my discussion in our coding channels that we are generally happy about the rule change and the code that's come from it, i know i certainly am

**Comment by Kylerace** [comment]
:trollface:

**Comment by ninjanomnom** [comment]
ided pr

**Comment by BorisVcBorison** [comment]
1984

**Pull request closed without merging**
