### PR TITLE
Removes golem debug code that spams world

### PR DESCRIPTION
**Pull request by YPOQ**

### CODE REVIEW

**Comment by nicbn** [comment]
2fast

**Comment by praisenarsie** [comment]
2quick

**Comment by Xhuis** [comment]
Wtf this was a feature revert pls

**Comment by davethwave** [comment]
So what does the bug that this pr fixed even do that required such quick action?

**Comment by PKPenguin321** [comment]
shows the messages that were deleted in the Files Changed to the entire server constantly

**Pull request merged**
