### PR TITLE
Readds the walk hotkey

### PR DESCRIPTION
**Pull request by Cyberboss**
Before people complain about #23260 

Partial revert tgstation/tgstation#21357

~How about the 'C' key? Does anything use the 'C' key?~

Yell about why you think Alt won't work

### CODE REVIEW

**Comment by ChangelingRain** [comment]
copy uses it; C and V are off-limits accordingly

**Comment by Cyberboss** [comment]
@ChangelingRain https://github.com/tgstation/tgstation/pull/21039#issuecomment-256687037

**Comment by ChangelingRain** [comment]
Uh, but that's not true? If you're doing stuff with the output box you can still do hotkey stuff, though I guess it's true for popups

**Comment by Cyberboss** [comment]
Even so it wouldn't really matter. Who can copy text and walk at the same time in hotkey mode? Remember it's push-and-hold not a toggle

**Comment by anconfuzedrock** [comment]
why can't we do alt?

**Comment by Cyberboss** [comment]
Same reason as shift: alt clicking

**Comment by anconfuzedrock** [comment]
uh, you never are in a high speed chase where you need to alt click somebody. I think I use alt click like once a week, its way too cumbersome and clunky and unreliable.

**Comment by Incoming5643** [comment]
When I tried to add a run walk hotkey the best I could do in terms of hotkey mode was `/~

We really are tapped for hotkeys.

**Comment by ExcessiveUseOfCobblestone** [comment]
@Cyberboss put it on the shift key and give altclick the examine button for things [since alt is only ever used for things that are adjacent to the character.

It's not like people should be examining things on the fly with pinpoint accuracy anyways.

**Comment by kevinz000** [comment]
just put it on a preference jesus and no I like shift for examine alt is used for pointing ffs

**Comment by kilkun** [comment]
rebindable hotkeys when

**Comment by Hatfish** [comment]
Why can't it just be shift again?
It's not like you have to hold it down for that long to examine something, anyways.

**Comment by Cyberboss** [comment]
@Hatfish Everyone bitched about not being able to examine while running

**Comment by SweaterKittens** [comment]
Does TAB do anything important that makes it unable to be used for this?

**Comment by anconfuzedrock** [comment]
Jesus fucking Christ sweaterkittens that's how you turn on hotkey mode

**Comment by ExcessiveUseOfCobblestone** [comment]
> alt clicking for point
> not using the SUPERIOR shift MMB

disgusting. I bet you use hotkey mode too nerdo

**Comment by MrStonedOne** [comment]
If I remember correctly, binding to C broke copy and paste flat out.

**Comment by Cyberboss** [comment]
Okay, are there any objections to putting it on Alt?

**Comment by MrStonedOne** [comment]
alt is good. only hurts pointing realistically and we could move that to control+shift+middle click if needed

**Comment by lzimann** [comment]
Pointing is shift middle click.

**Comment by dannno** [comment]
i can't middle click and I demand you accommodate my needs

**Comment by Cyberboss** [comment]
You can still alt click, you'll just be walking in hotkey mode

**Comment by SweaterKittens** [comment]
How about you pump the brakes Rock, we're talking about hotkeys, not Serbian Genocide.  Chill out.

**Pull request merged**
