### PR TITLE
[WIP] Pubby Map Fixes

### PR DESCRIPTION
**Pull request by Son-of-Space**
## About The Pull Request

This PR will constitute many small fixes to PubbyStation. Please submit your QOL fixes in the comments and I will get around to adding them to this PR. This PR will not be making any major or significant changes to the layout or design of the station. If you want me to do changes like that, message me on discord. Ideally, this will be up for one week and then I'll finalize.

Currently the following issues are being fixed:
1. Lack of conveyors under disposal setups in cargo caused crates to pile up and be manually moved. This has been fixed.

## Why It's Good For The Game

Pubby needs love.

## Changelog
:cl:
fix: Small things on PubbyStation.
/:cl:

### CODE REVIEW

**Comment by Cartographer-D** [comment]
If I don't get any feedback by tomorrow, I'll set this to ready.

**Comment by Tlaltecuhtli** [comment]
does it fix space walls being in the wrong area?

**Comment by dragomagol** [comment]
Here's a Pubby mapping issue #54955

**Comment by Cartographer-D** [comment]
@dragomagol Thanks. I'll look at this today.
@Tlaltecuhtli What do you mean by space walls?

**Comment by Cartographer-D** [comment]
Closing to make way for the KiloStation PR

**Pull request closed without merging**
